### ISSUE TITLE
Pagination组件 调用onShowSizeChange事件会同时触发onChange事件

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#27563]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gaibian-antd480-forked-ukf8q?file=/index.js)

### Steps to reproduce
调用onShowSizeChange事件会同时触发onChange事件

### What is expected?
调用onShowSizeChange事件不会触发onChange事件

### What is actually happening?
触发了

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome  79.0.3945.88 |

**Comment by afc163** [comment]
这是预期行为，需要触发的，因为 current 会变化，详情看 https://github.com/ant-design/ant-design/issues/24913#issuecomment-642494039
