### ISSUE TITLE
Unable to test the Datepicker component using jest

### ISSUE THREAD

**Issue by Abhikumar98** [ant-design/ant-design#27568]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/datepicker-test-forked-or0vz?file=/src/index.test.js)

### Steps to reproduce
Testing the Date picker component.
Clicking on it
Change the data

### What is expected?
The expected date should be received and the value for the date picker should be changed.

### What is actually happening?
The value isn't changing and the tests are failing

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.13.1 |
| System | mac OS: 10.14.6 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
Try antd 4.x: https://codesandbox.io/s/datepicker-test-forked-wz395?file=/src/index.test.js

**Comment by Abhikumar98** [comment]
@afc163 We have a huge codebase and we cannot migrate to antd 4.x right now.

**Comment by nickmccurdy** [comment]
For anyone else with this issue who's having issues migrating, here are some alternatives: https://github.com/testing-library/react-testing-library/issues/824#issuecomment-726762501
