### ISSUE TITLE
input组件的onChange事件在中文输入法下莫名触发多次

### ISSUE THREAD

**Issue by tangguodada** [ant-design/ant-design#27561]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dark-cookies-y4k85?file=/index.js)

### Steps to reproduce
使用中文输入法，在输入框中连续输入数字

### What is expected?
按照输入的顺序正确展示数字

### What is actually happening?
在输入到第4位数字时，输入框重复展示

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome 86.0.4240.111 |

---
只有在windows电脑下，用中文输入法会出现此问题，mac电脑和英文输入法不会重现

**Comment by tangguodada** [comment]
[https://codesandbox.io/s/dark-cookies-y4k85?file=/index.js](url)

**Comment by afc163** [comment]
https://codesandbox.io/s/laughing-ishizaka-cwdcp?file=/index.js

这不是 antd 的问题，原生 input 也有一样的情况。

**Comment by tangguodada** [comment]
> https://codesandbox.io/s/laughing-ishizaka-cwdcp?file=/index.js
> 
> 这不是 antd 的问题，原生 input 也有一样的情况。

有什么办法可以解决这个问题吗

**Comment by wufeng87** [comment]
@tangguodada 你好，最后问题有解决办法吗？谢谢

**Comment by tangguodada** [comment]
解决不了，这是原生input的问题，切换成英文输入法即可，偶现问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wufeng87"<notifications@github.com&gt;; 
发送时间: 2020年12月8日(星期二) 中午11:55
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "糖果大大"<565019202@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] input组件的onChange事件在中文输入法下莫名触发多次 (#27561)





 
@tangguodada 你好，最后问题有解决办法吗？谢谢

**Comment by duzit** [comment]
<Input
            // 增加key 重新渲染; defaultValue 不会rerender
            // 解决改变值后 取消modal 再次打开的回显问题
            key={record.wlkMcCn}
            defaultValue={record.wlkMcCn}
            placeholder="请输入"
            // 使用 onBlur 解决输入中文触发 onChange 问题 但不能再使用 value 而使用 defaultValue
            onBlur={((val) => handleChangeValue(val, record, index, 'wlkMcCn'))} />
            
我是这样解决的
