### ISSUE TITLE
可不可以关闭datepicker的清除和输入功能

### ISSUE THREAD

**Issue by evilemon** [ant-design/ant-design#2756]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

#### 你期待的结果是：
**关闭datepicker的清除和输入功能**

**Comment by benjycui** [comment]
清除按钮可以用样式隐藏，输入功能无法禁用。

需要自定义样式我可以理解，但是交互也改。。。

**Comment by evilemon** [comment]
这个主要是  清除日期后，输入会console报错
