### ISSUE TITLE
Modal.confirm的国际化在打开后会被初始化成默认值，导致关闭时按钮的中文会变成默认的英文

### ISSUE THREAD

**Issue by webrischa** [ant-design/ant-design#27578]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
点击官网中的Confirm示例，点击取消或确认时中文会变回英文

### What is expected?
保持中文不变

### What is actually happening?
中文变成了英文

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Merge into #27597
