### ISSUE TITLE
增加一个Checkbox 的 ideterminate 状态

### ISSUE THREAD

**Issue by Chinglik** [ant-design/ant-design#2757]
![image](https://cloud.githubusercontent.com/assets/14192159/17737359/57c63a28-64bf-11e6-8959-0cfa29460435.png)

**Comment by Chinglik** [comment]
点解这么模糊？

**Comment by afc163** [comment]
@ddcat1115 原来已经有实现了，但是没有样式。https://github.com/react-component/checkbox/issues/3

样式在这里特别实现过一份：http://ant.design/components/transfer/

Checkbox 和 Table 中都没有做。

**Comment by ddcat1115** [comment]
收到，放在 1.x-stable 还是master？

**Comment by afc163** [comment]
master
