### ISSUE TITLE
slider 无法拖拽到最大值

### ISSUE THREAD

**Issue by pingbaobao** [ant-design/ant-design#27571]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce

`<Slider defaultValue={30} step={0.01} max={8151.23} />`

Slider 只能拖拽到8151.22 无法拖拽到最大值

### What is expected?
能拖拽到最大值

### What is actually happening?
`<Slider defaultValue={30} step={0.01} max={8151.23} />`

最大值设置8151.23
只能拖拽到8151.22 无法拖拽到最大值

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome |

---
做区间筛选
https://codesandbox.io/s/5lnke?file=/index.js:386-440   官方代码在线运行调试有相同问题

**Comment by liuxuelian0929** [comment]
不想升级版本，有什么好的方法直接解决吗？除了在最大值加上step的1/10以外。

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/slider/pull/714
