### ISSUE TITLE
Input 输入关键字后每按Enter或空格键后显示为一个关键字，即多选的模式

### ISSUE THREAD

**Issue by kothing** [ant-design/ant-design#27572]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Input 输入关键字后每按Enter或空格键后显示为一个key的关键字，类似Github仓库的Topics关键字，表单提交为一个单据打标签Tag

### What does the proposed API look like?
API：获取Input的值为string[]结构

**Comment by kothing** [comment]
Github仓库Topics效果
![image](https://user-images.githubusercontent.com/39289309/98217700-cf105e80-1f85-11eb-9e83-548ba0b75d0b.png)

**Comment by xrkffgg** [comment]
感觉和 https://ant.design/components/select/#components-select-demo-tags 差不多
