### ISSUE TITLE
setFieldsValue 无法修改触发它的表单项？

### ISSUE THREAD

**Issue by wenmin92** [ant-design/ant-design#27573]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fancy-frost-e4rks)

### Steps to reproduce
在任意 Input 中输入

### What is expected?
2 个 Input 应该都被设置为指定值

### What is actually happening?
触发 setFieldsValue 的 Input 无法被设置成指定值

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | 16.9.0 |
| System | 20H2 |
| Browser | 86.0.4240.111 |

**Comment by afc163** [comment]
应该用 normalize 来控制自己的值，`setFieldsValue` 用于设定其他控件的值。

https://codesandbox.io/s/friendly-hermann-dxbee?file=/index.js
