### ISSUE TITLE
getValueFromEvent can be async?

### ISSUE THREAD

**Issue by debotos** [ant-design/ant-design#27579]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
```js
getValueFromEvent={async (e) => {
  e.persist()
  const file = e.target.files?.[0]
  if (!file) return null
    return {
       name: file.name,
       size: file.size,
       type: file.type,
       data: await getBase64(file),
    }
}}
```

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | ^16.13.1 |
| System | MacOS 10.15.6 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Noop. You can not do this since React `value-onChange` is sync mode.
