### ISSUE TITLE
Tree 無法動態加入 checkedKeys

### ISSUE THREAD

**Issue by Bonnie8ni** [ant-design/ant-design#27574]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-wing-bhfp4)

### Steps to reproduce
動態更改 checkedKeys 沒有反應

### What is expected?
如實顯示 checked

### What is actually happening?
數據有寫入，但 checkedKeys 效果沒呈現

題外
相同數據要是改由 selectedKeys 卻會顯示（但只顯示第一個 seleted ）

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/spring-wave-uq6k3

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/507615/98223001-78f2e980-1f8c-11eb-9d1d-315b96c157c1.png">
