### ISSUE TITLE
When columns is set to useState in table, the state of the method points to the problem/将table的columns属性设置为useState打印数据发现数据不一致

### ISSUE THREAD

**Issue by Minfee** [ant-design/ant-design#27588]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blissful-herschel-qbd15?file=/src/table.tsx)

### Steps to reproduce
1. columns被设置为了useState/Columns is set to useState
2. 点击第一行数据的编辑/Click the edit of the first row of data
3. 将三个值都修改为1后点确定/Change all three values to 1 and then determine
4. 点击第一行数据后面的测试Data按钮，console.log出的数据为修改前的数据/Click the test Data button after the first row of data, and the data from console.log is the data before modification.
5. 点击表格外部的测试Data按钮， console.log出的数据为修改后的数据/Click the test Data button outside the table, and the data from console.log is the modified data.

### What is expected?
两个按钮输出接口都为修改后的结果/The output interfaces of both buttons are the modified results.

### What is actually happening?
结果不同/The results are different.

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 17.0.1 |
| System | macos 10.5 |
| Browser | chrome 86 |

---
偶然的尝试将columns设置为useState触发此bug，感觉是hooks出现了嵌套函数/Accidental attempt to set columns to useState to trigger this bug, feels like hooks has a nested function

**Comment by zombieJ** [comment]
数据更新的时候你没有调用 `setColumns` 重新设置 `columns`，这导致了 `columns[x].render` 里还是初始化的数据。请参考[闭包](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Closures)相关知识。
