### ISSUE TITLE
On Select dynamic options do not rerender when using React Hooks

### ISSUE THREAD

**Issue by cfontes** [ant-design/ant-design#27587]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-xarwcj-kg6tmv?file=index.js](https://stackblitz.com/edit/react-xarwcj-kg6tmv?file=index.js)

### Steps to reproduce
Create 2 selects where one will provide the options to by formInstance.setFieldsValue({ subList: value });

### What is expected?
When the first Select option is selected the next Select will be populated with the passed options

### What is actually happening?
No options on the second Select

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 17.0.0 |
| System | Ubuntu 18.4 |
| Browser | Chrome - 86.0.4240.75 |

---
This is a simple behaviour and pretty useful I am not sure how to make it work.

**Comment by zombieJ** [comment]
`shouldUpdate` is used for [renderProps only](https://ant.design/components/form/#shouldUpdate):
https://stackblitz.com/edit/react-xarwcj-xszlcr?file=index.js

**Comment by cfontes** [comment]
Hello @zombieJ thank you for the example.

I've read that part of the documentation but it's not very clear that you need to wrap the Item in another Item to rerender in cases like this.

Maybe would be nice to explain it better in the documentation!
