### ISSUE TITLE
antd如何实现css模块化

### ISSUE THREAD

**Issue by bless-19946** [ant-design/ant-design#2758]
- antd 版本:
windows8  antd ^1.8.0
google浏览器

我引入amtd，我希望可以实现antd的css 模块化
css样式文件可以实现模块化操作，但是对于生成的html文件并没有变化，有没有什么方法可以给antd实现css-modules

**Comment by benjycui** [comment]
你是想用 css-modules 还是想按需加载 antd 的组件样式？

**Comment by bless-19946** [comment]
我想用css-modules来处理，但是antd组件内部的类名无法模块化 比如：
![image](https://cloud.githubusercontent.com/assets/16424953/17766843/a602c076-655f-11e6-9f35-e9ab43ed86d2.png)

**Comment by benjycui** [comment]
是的，因为 antd 并没有使用 css-modules，不过只要你不用 ant- 前缀，就不会有冲突。

**Comment by bless-19946** [comment]
我现在需要覆盖下antd的样式，其他部分已经做了模块化，这时候应该怎么处理呢，你有什么解决方法么

**Comment by benjycui** [comment]
:global(.ant-*)

**Comment by afc163** [comment]
or

```css
:global {
  .ant-xx { 
  }
}
```

**Comment by jackple** [comment]
问题是, 这样一改, 就全局都改乱了, 我可能只需要.ant-btn在当前组件的样式有变化

**Comment by afc163** [comment]
```css
.xxx :global(.ant-btn){ 
}
```

**Comment by jackple** [comment]
@afc163 这也是一个方法, 谢谢
