### ISSUE TITLE
用户无法选择官网主题颜色

### ISSUE THREAD

**Issue by ityak** [ant-design/ant-design#27598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
滑到页面最下方, 更改主题颜色的时候, 会被右侧的锚点导航遮挡

### What is expected?
因为遮挡了, 就不能愉快的更换主题颜色了

### What is actually happening?
不能愉快的更换主题颜色

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 17.0.1 |
| System | win 10 |
| Browser | chrome  86.0.4240.183（正式版本） |

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/98322252-f9175e80-2021-11eb-8e60-a903830ef893.png)


上个截图看看

**Comment by ityak** [comment]
![image](https://user-images.githubusercontent.com/34937053/98327735-39c9a480-202f-11eb-866d-3ed916ad2692.png)

**Comment by ityak** [comment]
锚点导航的层级太高了挡住, 选颜色了
