### ISSUE TITLE
更新antd至1.9报错。

### ISSUE THREAD

**Issue by cnv587** [ant-design/ant-design#2759]
#### 本地环境

- antd 版本:
- 操作系统及其版本：window 10
- 浏览器及其版本: chrome 52

#### 你做了什么？
今天早上从antd1.7版本更新到1.9版本的之后所有的页面都报错 ，具体不知道是哪个组件造成的。其他没有更新过的代码均正常。

#### 实际上的结果：
![1](https://cloud.githubusercontent.com/assets/13713580/17761375/324dcb9c-6539-11e6-910e-f2935391cad0.png)

**Comment by afc163** [comment]
https://github.com/react-component/select/commit/3c7f4598731278601cae21ccd50df12f545a608f

Select Option 的 value 只能是 string 。
