### ISSUE TITLE
modal.confirm国际化，第二次执行时，又切换回英文

### ISSUE THREAD

**Issue by yinhunfeixue** [ant-design/ant-design#27597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)

### Steps to reproduce
1、刷新页面，将语音切换到中文

2、点击show confirm--此时，弹窗按钮显示为中文

3、关闭弹窗，再点击show confirm--，此时，弹窗按钮显示英文（出现异常）

4、之后，每次点击show confirm，按钮都是英文

### What is expected?
期望点击show confirm，按钮是中文

### What is actually happening?
点击show confirm，按钮是 英文

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | mac os |
| Browser | chrome |

**Comment by zombieJ** [comment]
We should change demo to hooks version.

**Comment by djllhs** [comment]
I have ths same problem

**Comment by Veveue** [comment]
+1

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/27376 breaks this.
