### ISSUE TITLE
一个小疑问（自动化测试）通过原生 js 修改某个 input 的 value 值，最后提交提示输入框未填写（项目是用 ant 开发的）

### ISSUE THREAD

**Issue by Fyuxuan** [ant-design/ant-design#27599]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://wu](http://wu)

### Steps to reproduce
因为现在做自动化测试遇到这个问题，不清楚是不应该这样去赋值，还是算一个 ant 的小 bug，没有监听到 input 的 value 改变了

### What is expected?
正确获取到值

### What is actually happening?
提示输入框未输入

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 无 |
| System | win10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
ant是react编写，脱离react形式对dom或者其他做修改，react是不知道的

**Comment by afc163** [comment]
不建议用原生 js 修改 input 值，建议用 React 生态内的测试套件。
