### ISSUE TITLE
Filter table column with empty value (empty string)

### ISSUE THREAD

**Issue by olgacherkasenko** [ant-design/ant-design#27619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/filter-and-sorter-antd480-forked-6c9fw?file=/index.js)

### Steps to reproduce
1. Click on Address filter
2. Choose empty value

### What is expected?
1. The checkbox must be ticked.
2. filters value in onChange function should be ""

### What is actually happening?
1. The checkbox isn't ticked.
2. filters value in onChange is "item_0"

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | ubuntu 18.04 |
| Browser | Chrome |

**Comment by afc163** [comment]
It is meaningless to leave `value: ''` as one of filters, please fill it by a nullable value like `'none'`.

**Comment by olgacherkasenko** [comment]
> It is meaningless to leave `value: ''` as one of filters, please fill it by a nullable value like `value: 'none'`.

There are values ​​that come from the server and this values are empty string. I need to have a filter by this value  (""). Is there is some opportunity to make this?

**Comment by lsimrsi** [comment]
@afc163 It is a legit use case to want to know which records do not have a value for a given column:

```
select * from table
where (col is null or col = '')
```

I should not have to arbitrarily change values of my data to `'none'` to get this information. That is an anti-pattern.

Please reopen this.
