### ISSUE TITLE
Modal 可以增加最小化的功能吗？

### ISSUE THREAD

**Issue by daisycyt** [ant-design/ant-design#27611]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在一个页面上弹出Modal框后，很多情况下需要同时操作Modal框与原页面，这时候希望可以暂时隐藏Modal，可否增加最小化的功能，谢谢

### What does the proposed API look like?
minimize: true

**Comment by yoyo837** [comment]
visible=false收起来，然后内部不销毁，是不是就相对于最小化了？

**Comment by afc163** [comment]
建议自行封装吧，目前没计划做这个功能。
