### ISSUE TITLE
Search 组件中的 button 应与 input 保持一致，没有阴影

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27615]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/input-cn/#components-input-demo-search-input](https://ant-design.gitee.io/components/input-cn/#components-input-demo-search-input)

### Steps to reproduce
查看组件

### What is expected?
Search 组件中的 button 和 input 保持一致，没有阴影

### What is actually happening?
Search 组件中的 button 有阴影
[![BhrtSS.png](https://s1.ax1x.com/2020/11/06/BhrtSS.png)](https://imgchr.com/i/BhrtSS)

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by xrkffgg** [comment]
Primary Button 默认是有的，这里是保持一样的。

如果不想要的话，其实可以自己覆盖。

```css
. ant-input-search .ant-btn-primary {
    box-shadow: none;
}
```

**Comment by AlanCutFlim** [comment]
唔，好的。我以为是个 BUG，因为平时见到的这种搜索组件，input 和 button 都是整体保持一致，没有阴影的。

[![BhR7E4.png](https://s1.ax1x.com/2020/11/06/BhR7E4.png)](https://imgchr.com/i/BhR7E4)

[![BhRYAH.png](https://s1.ax1x.com/2020/11/06/BhRYAH.png)](https://imgchr.com/i/BhRYAH)
