### ISSUE TITLE
textarea最大长度截取问题

### ISSUE THREAD

**Issue by zhangweiqiang666** [ant-design/ant-design#27612]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/f5ed19248f95a4561f9c33800756228d4efed3ce/components/input/TextArea.tsx#L116](https://github.com/ant-design/ant-design/blob/f5ed19248f95a4561f9c33800756228d4efed3ce/components/input/TextArea.tsx#L116)

### Steps to reproduce
传入一个😂 ，maxLength设为1，传入就出现乱码

### What is expected?
改变截取方式

### What is actually happening?
  

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 计算长度用的[...value].length,但是截取直接用的value.slice(0,maxLength)) |
| System | all |
| Browser | all |

**Comment by zhangweiqiang666** [comment]
<img width="1215" alt="截屏2020-11-06 下午6 25 12" src="https://user-images.githubusercontent.com/49194622/98355807-a360a780-205d-11eb-986f-771b5bea025d.png">

**Comment by afc163** [comment]
`console.log("😓".length); // 2`

**Comment by zhangweiqiang666** [comment]
> `console.log("😓".length); // 2`

我想你兵没有理解我的意思，在我上面提的issue组件中的136行使用的是[...value].length,那么截取的时候是都也需要用[...vlaue].slice()呢？
![F8OP5~~U4@ 23LKBXX{@MCG](https://user-images.githubusercontent.com/49194622/98389215-b8a1fa00-208e-11eb-861b-57962a4ec1b6.png)

**Comment by afc163** [comment]
@zhangweiqiang666 欢迎来个 PR 试着修复一下~
