### ISSUE TITLE
Message提示内容不能换行，如何能换行？

### ISSUE THREAD

**Issue by githubldld** [ant-design/ant-design#27628]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/so1by)

### Steps to reproduce
message.error("多行文本无法换行，添加\r\n也不能换行，如何才能实现换行呢");

### What is expected?
希望message.error()提示多行文本可以换行

### What is actually happening?
message.error()提示多行文本不能换行

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | react |
| System | windows 10 |
| Browser | chrome 86.0.4240.183 |

**Comment by zhangweiqiang666** [comment]
写成jsx message.error(<div>多行文本无法换行，添加\r\n也不能换行，如何才能实现换行呢</div><div>多行文本无法换行，添加\r\n也不能换行，如何才能实现换行呢</div>)

**Comment by zhangweiqiang666** [comment]
![HIH F)$4V6{LT0Y}RMIYVYU](https://user-images.githubusercontent.com/49194622/98444921-902e0480-214f-11eb-88ea-26d1043e0a12.png)
 写成jsx就行了

**Comment by githubldld** [comment]
多谢多谢！

**Comment by githubldld** [comment]
> ![HIH F)$4V6{LT0Y}RMIYVYU](https://user-images.githubusercontent.com/49194622/98444921-902e0480-214f-11eb-88ea-26d1043e0a12.png)
> 写成jsx就行了

多谢多谢！

**Comment by kapbook-caizhehao** [comment]
> ![HIH F)$4V6{LT0Y}RMIYVYU](https://user-images.githubusercontent.com/49194622/98444921-902e0480-214f-11eb-88ea-26d1043e0a12.png)
> 写成jsx就行了


> > ![HIH F)$4V6{LT0Y}RMIYVYU](https://user-images.githubusercontent.com/49194622/98444921-902e0480-214f-11eb-88ea-26d1043e0a12.png)
> > 写成jsx就行了
> 
> 多谢多谢！

你好，你们图片我打不开，可否重新发一下

**Comment by yoyo837** [comment]
重发图片你也打不开，需要挂梯子，
我手抄给你：

```jsx
message.info(<span>12314 <br /> 3213123</span>);
```

**Comment by lwq-js** [comment]
请教一下，如果是后端返回的，这种情况如何转换成jsx

**Comment by 1169938246** [comment]
message.error( message.error(<span dangerouslySetInnerHTML={{__html: res.message}}></span>))

**Comment by 1169938246** [comment]
> 请教一下，如果是后端返回的，这种情况如何转换成jsx


message.error( message.error(<span dangerouslySetInnerHTML={{__html: res.message}}>))

**Comment by 1169938246** [comment]
> 请教一下，如果是后端返回的，这种情况如何转换成jsx

message.error(<span dangerouslySetInnerHTML={{__html: res.message}}></span>)

**Comment by 1169938246** [comment]
![image](https://github.com/ant-design/ant-design/assets/30794661/deb2c107-c54e-4ed4-ae27-929e7ff08992)

**Comment by 1169938246** [comment]
> 请教一下，如果是后端返回的，这种情况如何转换成jsx

![image](https://github.com/ant-design/ant-design/assets/30794661/09ec24b4-b07b-4533-bace-c48185ae64a2)
