### ISSUE TITLE
Table Drag sorting with handler

### ISSUE THREAD

**Issue by cnLGMing** [ant-design/ant-design#27623]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler](https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler)

### Steps to reproduce
[Open the link](https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler)

### What is expected?
I can drag and drop in any order.

### What is actually happening?
The first one and the last one, you can't drag to the second.
But there will be no such problem in [codesandbox](https://codesandbox.io/s/p6xoz).

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.12.0 |
| System | macOS 10.15.6 |
| Browser | Edge  86.0.622.56  |

**Comment by afc163** [comment]
居然和 https://github.com/ant-design/ant-design/pull/26538/files#diff-372f09eb9133dea08dbd2362f5af433dee1f358f1f0d1d8a29d13d90c92d4070R6 有关。
