### ISSUE TITLE
Pagination showQuickJumper & showSizeChanger not working

### ISSUE THREAD

**Issue by ds1371dani** [ant-design/ant-design#27627]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jumper-antd480-forked-bch60)

### Steps to reproduce
use Pagination component with showQuickJumper & showSizeChanger props

### What is expected?
QuickJumper and SizeChanger should be displayed.

### What is actually happening?
only simple Pagination is displayed.

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.13.1 |
| System | ubuntu |
| Browser | firefox |

**Comment by afc163** [comment]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/507615/98457739-61527580-21c5-11eb-8361-6bf3b01f3df0.png">

Your codesandbox works as expected.
