### ISSUE TITLE
Modal没有完全遮挡其他元素

### ISSUE THREAD

**Issue by joesonw** [ant-design/ant-design#2762]
#### 本地环境

- antd 版本: 1.9.1
- 操作系统及其版本：osx
- 浏览器及其版本: nodejs6 + chrome

#### 你做了什么？
外层有一个Menu在左边, 右边是内容
右边子组件里使用了Modal

#### 你期待的结果是：

正常遮挡住所有元素

#### 实际上的结果：
左边Menu没被遮挡住

![image](https://cloud.githubusercontent.com/assets/1635441/17766096/f5d7a534-655b-11e6-8df3-8cafbc2f07e2.png)

**Comment by benjycui** [comment]
左侧 Menu 或者他的祖先元素的 z-index 比 Modal 的高了，调整下就好。

**Comment by joesonw** [comment]
@benjycui 都是默认的组件, 没有设置z-index, 而且modal设置了z-index 999 也没有用..

**Comment by benjycui** [comment]
> 左侧 Menu 或者他的祖先元素的 z-index 比 Modal 的高了

建议认真学习堆栈上下文的概念。

**Comment by afc163** [comment]
给个重现。

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
只能尝试修复了。。。

**Comment by benjycui** [comment]
其实我觉得是外层容器的原因 https://www.qianduan.net/that-thing-on-the-z-index/

@joesonw 你应该是修改了 Modal 的容器节点吧。

**Comment by joesonw** [comment]
在chrome中  把`.ant-menu-horizontal, .ant-menu-inline, .ant-menu-vertical` 这个类的z-index: auto注释掉就好了.

**Comment by joesonw** [comment]
新的`z-index: auto`好像也是有问题的哦.  http://codepen.io/anon/pen/OXYrQA?editors=001

**Comment by afc163** [comment]
你不给重现，无法定位，只能盲改。

**Comment by benjycui** [comment]
> @joesonw 你应该是修改了 Modal 的容器节点吧。
