### ISSUE TITLE
FormItem labelCol 能设置成响应式的么 ?

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#2763]
使用 Row Col能很好的实现响应式布局，但是FormItem的Label和Wrapper宽度就不知道如何设置 响应式的了。

![image](https://cloud.githubusercontent.com/assets/1686808/17766127/28fcd2fe-655c-11e6-9c28-7601347a9011.png)

```

const formItemLayout = {
  	labelCol: { span: 8 },//这里可以设置成响应式吗？
  	wrapperCol: { span: 16 },
};

<FormItem label="启用时间：" {...formItemLayout} required>
   ...
</FormItem>
```

**Comment by benjycui** [comment]
可以，labelCol 的值与 col 的属性一致。
