### ISSUE TITLE
Bug displaying the "Menu.ItemGroup" component

### ISSUE THREAD

**Issue by yandexphp** [ant-design/ant-design#27639]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-leaf-gxzto?file=/src/App.js)

### Steps to reproduce
Select the item "subItem 1" in the menu and in this item select any child item in the "itemGroup"

### What is expected?
Only 1 item that we have selected will be highlighted in color

### What is actually happening?
When 1 element is selected, then all others including the selected one are highlighted active color as selected

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Google Chrome - version: 86.0.4240.183 |

#

![image](https://user-images.githubusercontent.com/29909911/98465429-32eb8f00-21f3-11eb-982d-d46084ae405e.png)

**Comment by afc163** [comment]
Please add key to SubMenu and Menu.Item
