### ISSUE TITLE
官网滚动到底部时，锚点会遮挡其他内容

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27636]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
进入链接，并滚动到底部

### What is expected?
锚点的停留位置最好与文档内容的边界一致，不遮挡下方其他内容

[![Bo6o11.png](https://s1.ax1x.com/2020/11/08/Bo6o11.png)](https://imgchr.com/i/Bo6o11)

### What is actually happening?
锚点遮挡住了其他内容

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/27598

**Comment by afc163** [comment]
预期行为，不希望 Footer 挡住锚点。

**Comment by yoyo837** [comment]
他可能想说的是滚动到一定位置时锚点应该修改其position，比如改为非fixed

**Comment by yoyo837** [comment]
就如同一开始非fixed开始滚动后设置为fixed

**Comment by AlanCutFlim** [comment]
@xrkffgg @afc163 @yoyo837 
抱歉各位，我表述的不是很好。

我希望的是当 `article` 将要离开可视区域时，`锚点` 也应跟随离开，这样子相对于一直固定在那里遮挡住 `footer`，会不会更好一点？

我想到的方法是将 `锚点` 的 `postion` 改为 `absolute`，然后滚动时改变它的 `top` 值，下面粗糙地实现了一下想要的效果。

### 期望的效果
[![B7RRrn.gif](https://s1.ax1x.com/2020/11/09/B7RRrn.gif)](https://imgchr.com/i/B7RRrn)

### 目前官网的效果
[![B7RTGF.gif](https://s1.ax1x.com/2020/11/09/B7RTGF.gif)](https://imgchr.com/i/B7RTGF)

**Comment by afc163** [comment]
@AlanCutFlim 思路可行，就是离开 Article 区域可能不容易判断，可以来 PR 试试。
