### ISSUE TITLE
Dropdown action can not be triggered in some cases

### ISSUE THREAD

**Issue by peidongxie** [ant-design/ant-design#27633]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dropdown-action-can-not-be-triggered-in-some-cases-ftroe)

### Steps to reproduce
Move the cursor from the disabled Button to the Dropdown.

### What is expected?
Dropdown action is triggered. The dropdown menu is visible.

### What is actually happening?
Dropdown action is not triggered. The dropdown menu is still hidden.

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 17.0.1 |
| System | macOS Catalina 10.15 |
| Browser | Chrome 86 |

**Comment by afc163** [comment]
It is chrome issue, check this demo in Firefox and Chrome:

https://codesandbox.io/s/dropdown-action-can-not-be-triggered-in-some-cases-forked-xq6d2?file=/index.js

---x

related question: https://stackoverflow.com/questions/18113937/fire-onmouseover-event-when-element-is-disabled

---

There is no good solution for this, you could add margin better disabled element and Dropdown/Tooltip/Popover trigger element as workaround.

**Comment by peidongxie** [comment]
Thanks a lot.
I've add the margin, which solves this type of problem to some extent. However, if the margin is too narrow or the cursor is moved too quickly, it's still possible to reproduce. I may have to try something else.
Thanks again.
