### ISSUE TITLE
Table分页在-异步分页-的情况下selectedRowKeys, selectedRows不同步

### ISSUE THREAD

**Issue by lxdu** [ant-design/ant-design#2764]
#### 本地环境

antd 版本:1.9.1
操作系统及其版本:Windows 8.1企业版 beta (64-bit)
浏览器及其版本:Google Chrome 50.0.2661.94 m

#### 你做了什么？

 引入了 antd 的 Table
场景：Table的数据采用异步分页的方式获取
操作：在第1页选了一个数据，在第2页选了一个数据，并在rowSelection的onChange中打印了selectedRowKeys, selectedRows的值
注意：正常情况下获取到全部数据由前台直接分页展示没问题，只有在异步获取分页的情况下有问题

#### 你期待的结果是：

selectedRows的值能和selectedRowKeys值一样取到全部选中数据

#### 实际上的结果：

如图，两个值不同步
![image](https://cloud.githubusercontent.com/assets/18730972/17768540/0090e1ba-6567-11e6-85ab-d89489dafbe3.png)

**Comment by benjycui** [comment]
这个之前应该已经修复了 https://github.com/ant-design/ant-design/issues/2566

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by lxdu** [comment]
看过这个bug了，正常情况下获取到全部数据由前端直接分页展示没问题，在异步获取分页的情况下仍然存在问题

**Comment by 252402085** [comment]
我也是有这个问题，
异步获取分页的情况下，翻页后selectedRows的值能和selectedRowKeys值不一致

**Comment by afc163** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by 252402085** [comment]
http://codepen.io/anon/pen/rLgVqp?editors=0011
第一页选择数据，切换到第二页再选择数据时selectedRows的值能和selectedRowKeys值不一致

**Comment by afc163** [comment]
这个没法支持了，目前 selectedRowKeys 和 selectedRows 在本地模式下是保持一致的。

异步模式时，之前的 selectedRowKeys 会保留。但是由于 dataSource 已经更换，组件内部没法根据 selectedRowKeys 拿不到原来的 rows 了。为了性能，组件内部也不再保存整个对象。

只能上层自己维护一个 state.selectedRows 来保存之前的数据了，抱歉。

**Comment by dyygtfx** [comment]
居然不支持 唉

**Comment by sam-dingkang** [comment]
@afc163 
在业务层可以这样处理， rowKey={record => JSON.stringify(record)} ，然后在 onChange()方法中对selectedRowKeys.map(item => JSON.parse(item))，这样就可以获得每页的选中的数据对象了，有点黑科技，但是最简单。

**Comment by shenyiling** [comment]
@sam-dingkang 如果表单项 对象很大 这样合适吗

**Comment by sam-dingkang** [comment]
@shenyiling 如果record数据对象很大，可以筛选出你想要的数据组装成一个对象

**Comment by WALLE729** [comment]
同样的问题，不知道官方什么时候能解决

**Comment by WALLE729** [comment]
@sam-dingkang 按照你的做法，勾选的时候没有对勾了，反复点击两次，还会有报错

**Comment by 308787520huanhuan** [comment]
![111](https://user-images.githubusercontent.com/3348828/51586695-32e4a700-1f19-11e9-8862-c68e38179be2.png)

**Comment by 308787520huanhuan** [comment]
![22222](https://user-images.githubusercontent.com/3348828/51586724-560f5680-1f19-11e9-87c9-4d82489b197e.png)

**Comment by luckyscript** [comment]
mark

**Comment by coppyC** [comment]
我也来贴一下我的解决方案。
```ts
  // typescript, 用js的话需要去掉类型以及感叹号
  onRowSelect(keys: any[], rows: {}[]) {
    this.selectedRowKeys = keys as number[]
    if(keys.length === rows.length)
      this.selectedRows = rows
    else
      this.selectedRows = keys.map(key => (
        this.selectedRows.find((row: any) => row.id === key)
        || rows.find((row: any) => row.id === key)!   // 必在两者之中，加感叹号断言（js的去掉这个 "!"）
      ))
  }
```

对了，我这是的rowKey是id，如果不是的话也要做修改
还有我用的是 mobx ，如果没用的话，还需要改成 setState
综上: 要改这么多，所以仅供参考，除非你的技术栈我和一致 :)

思路:
this.selectedRows 保存了上一次选择的 rows
然后 每次过来的 keys 是完整的
所以只要把 keys 翻译成rows就行了
而且新翻译的 rows 绝对是[上一次保存的rows和这次过来的不完整rows并集]的子集
查表就完事了
然后为了性能，多做了一次浅比较
当keys, rows 的长度一致时，这个 rows 绝对是完整的
~~除非写了什么脏代码偷偷局部修改keys，~~ 一般不可能

此段代码时间复杂度为 0~2

**Comment by careteenL** [comment]
贴一下我的解决方案
使用场景：需要对表格翻页复选且记录所选项在顶部展示，且能在顶部对所选项删除。
大体思路：将需用到的除key之外的属性和key何成一个新的`syntheticKeys`，再在`onChange`中去拆分。
此方式局限在所需属性`不多且数据类型为number/string/boolean`，但基本也满足需求。
```js
const KEY_SEP = '--'
// 获取数据时 合成一个key
{
 key: `${row.id}${KEY_SEP}${row.name}`,
}
// 使用时
  const [selectedRow, setSelectedRow] = useState({
    syntheticKeys: [],
    keys: [],
    names: [],
  });
  const rowSelection = {
    selectedRowKeys: selectedRow.syntheticKeys,
    onChange: (selectedKeys: any) => {
      const syntheticKeys: string[] = [];
      const keys: number[] = []
      const names: string[] = []
      selectedKeys.forEach((key: any) => {
        const amendedKeys = key.split(KEY_SEP)
        syntheticKeys.push(key)
        keys.push(parseInt(amendedKeys[0], 10))
        names.push(amendedKeys[1])
      })
      const amendedRows = {
        syntheticKeys,
        keys,
        names,
      };
      setSelectedRow(amendedRows);
    },
  };
```

**Comment by gaoqiang19514** [comment]
> JSON.stringify(record)}

雪中送炭

**Comment by gaoqiang19514** [comment]
> @afc163
> 在业务层可以这样处理， rowKey={record => JSON.stringify(record)} ，然后在 onChange()方法中对selectedRowKeys.map(item => JSON.parse(item))，这样就可以获得每页的选中的数据对象了，有点黑科技，但是最简单。

你可真是个小机灵鬼

**Comment by gaoqiang19514** [comment]
> ```ts
> keys
> ```

请告诉我为什么你这么优秀？

**Comment by gaoqiang19514** [comment]
> 我也来贴一下我的解决方案。
> 
> ```ts
>   // typescript, 用js的话需要去掉类型以及感叹号
>   onRowSelect(keys: any[], rows: {}[]) {
>     this.selectedRowKeys = keys as number[]
>     if(keys.length === rows.length)
>       this.selectedRows = rows
>     else
>       this.selectedRows = keys.map(key => (
>         this.selectedRows.find((row: any) => row.id === key)
>         || rows.find((row: any) => row.id === key)!   // 必在两者之中，加感叹号断言（js的去掉这个 "!"）
>       ))
>   }
> ```
> 
> 对了，我这是的rowKey是id，如果不是的话也要做修改
> 还有我用的是 mobx ，如果没用的话，还需要改成 setState
> 综上: 要改这么多，所以仅供参考，除非你的技术栈我和一致 :)
> 
> 思路:
> this.selectedRows 保存了上一次选择的 rows
> 然后 每次过来的 keys 是完整的
> 所以只要把 keys 翻译成rows就行了
> 而且新翻译的 rows 绝对是[上一次保存的rows和这次过来的不完整rows并集]的子集
> 查表就完事了
> 然后为了性能，多做了一次浅比较
> 当keys, rows 的长度一致时，这个 rows 绝对是完整的
> ~除非写了什么脏代码偷偷局部修改keys，~ 一般不可能
> 
> 此段代码时间复杂度为 0~2


请告诉我为什么你这么优秀？

**Comment by Deja-vuuu** [comment]
亲测 ant4.4.0以上 直接加preserveSelectedRowKeys 是没问题的

**Comment by echo3582** [comment]
> 我也来贴一下我的解决方案。
> 
> ```ts
>   // typescript, 用js的话需要去掉类型以及感叹号
>   onRowSelect(keys: any[], rows: {}[]) {
>     this.selectedRowKeys = keys as number[]
>     if(keys.length === rows.length)
>       this.selectedRows = rows
>     else
>       this.selectedRows = keys.map(key => (
>         this.selectedRows.find((row: any) => row.id === key)
>         || rows.find((row: any) => row.id === key)!   // 必在两者之中，加感叹号断言（js的去掉这个 "!"）
>       ))
>   }
> ```
> 
> 对了，我这是的rowKey是id，如果不是的话也要做修改 还有我用的是 mobx ，如果没用的话，还需要改成 setState 综上: 要改这么多，所以仅供参考，除非你的技术栈我和一致 :)
> 
> 思路: this.selectedRows 保存了上一次选择的 rows 然后 每次过来的 keys 是完整的 所以只要把 keys 翻译成rows就行了 而且新翻译的 rows 绝对是[上一次保存的rows和这次过来的不完整rows并集]的子集 查表就完事了 然后为了性能，多做了一次浅比较 当keys, rows 的长度一致时，这个 rows 绝对是完整的 ~除非写了什么脏代码偷偷局部修改keys，~ 一般不可能
> 
> 此段代码时间复杂度为 0~2

亲测好用，感谢！
