### ISSUE TITLE
TypeError: Cannot read property 'addListener' of undefined [jest, react-testing-library]

### ISSUE THREAD

**Issue by AO19** [ant-design/ant-design#27658]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/AO19/typeError-cannot-read-property-addListener-of-undefined](https://github.com/AO19/typeError-cannot-read-property-addListener-of-undefined)

### Steps to reproduce
1. Clone the repo
2. Install packages
3. Run `npm run test` -> run all tests

### What is expected?
Test passes.

### What is actually happening?
Test fails.

TypeError: Cannot read property 'addListener' of undefined

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Firefox 81.0.1 |

---
This only happens, if Ant Design Components are in the project.  
Without AntD components, the test is passing.

This is not similiar to 4.0.0-rc.1 TypeError: window.matchMedia is not a function in Jest, because I'm using the recommended solution and the test still fails with a different error.

**Comment by afc163** [comment]
I don't know why but https://github.com/AO19/typeError-cannot-read-property-addListener-of-undefined/pull/1 works.

ref #21096
