### ISSUE TITLE
Tabs 删除 Tab 时，配合 Modal.confirm 会多出个空 Tab

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#27656]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7cg2t?file=/index.js)

### Steps to reproduce
1. 点击删除 Tab
2. 在弹出的 Modal 后面可以看到，后面多了个空的 Tab

### What is expected?
在 Modal 确认前不会多出一个空的 Tab

### What is actually happening?
在 Modal 确认前多出了一个空的 Tab

![image](https://user-images.githubusercontent.com/10294977/98520215-b4532800-22ac-11eb-98e8-67643ef1c4ad.png)

| Environment | Info |
|---|---|
| antd | 4.8.1 |
| React | latest |
| System | Linux kernel 5.4.72 |
| Browser | Chrome Dev 88.0.4315.5 |

---
另外，刚发现的：antd 4.8.1 版本，version 打印的是 4.8.0？

**Comment by huntdream** [comment]
别把`{modalContext}`放在`Tabs`里面

**Comment by yoyo837** [comment]
Tabs下只能有Tab.

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-xx8yv?file=/index.js
