### ISSUE TITLE
select demo 增加

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#2765]
常见场景，多选用户提示，可以用 setTimeout mock 请求
- labelInValue: 显示和value 不同 (id 和用户名)
- 网络请求限流控制: https://www.npmjs.com/package/lodash.throttle
- 时序控制，先请求 a 后请求 b 结果 b 的响应比 a 早

**Comment by afc163** [comment]
可以用 randomapi

- https://randomuser.me/
- https://randomapi.com/

https://github.com/ant-design/ant-design/blob/1.x-stable/components/table/demo/ajax.md

**Comment by benjycui** [comment]
是类似于这个么 http://react-component.github.io/select/examples/mul-suggest.html
