### ISSUE TITLE
官网底部 slogan 排版问题

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27660]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/overview-cn/](https://ant.design/components/overview-cn/)

### Steps to reproduce
进入链接，滚动到最底部查看 slogan

### What is expected?
❤️ 左右间距一致

### What is actually happening?
![image](https://user-images.githubusercontent.com/50612752/98531758-c5576580-22bb-11eb-848f-9bc2ccf2ff5e.png)

| Environment | Info |
|---|---|
| antd | 4.8.1 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
我的电脑上看着没问题：


<img width="253" alt="image" src="https://user-images.githubusercontent.com/507615/98532846-33505c80-22bd-11eb-861f-12480b371c0a.png">

**Comment by AlanCutFlim** [comment]
可以添加一个1920*1080的设备，然后用这个设备再查看一下。

![image](https://user-images.githubusercontent.com/50612752/98533312-c25d7480-22bd-11eb-9438-1c6f471b9198.png)

![image](https://user-images.githubusercontent.com/50612752/98533396-e5882400-22bd-11eb-98d8-cec8c6c9b492.png)

我使用的是1920*1080的屏幕，缩放比例100%，难道和这个有关系吗？

**Comment by xrkffgg** [comment]
I'm OK

**Comment by AlanCutFlim** [comment]
抱歉，不是官网的问题，换Firefox看好像就正常了。

![image](https://user-images.githubusercontent.com/50612752/98543355-584ccb80-22cd-11eb-8afe-72ef933a8525.png)
screen resolution: 1920 x 1080
browser: Chrome
zoom: 100%

![image](https://user-images.githubusercontent.com/50612752/98543631-bb3e6280-22cd-11eb-8b43-ddca055247ea.png)
screen resolution: 1920 x 1080
browser: Chrome
zoom: 150%

![image](https://user-images.githubusercontent.com/50612752/98543578-aa8dec80-22cd-11eb-9ac5-7b2b06aec8d2.png)
screen resolution: 1920 x 1080
browser: Firefox
zoom: 100%

![image](https://user-images.githubusercontent.com/50612752/98543925-28ea8e80-22ce-11eb-9920-652ef1f0f2cf.png)
screen resolution: 1920 x 1080
browser: Firefox
zoom: 150%

系统是黑苹果，不太理解这个现象。
