### ISSUE TITLE
Modal's onExited,onClosed or onDestroyed.

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#27661]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我希望能有个事件告诉我modal完全关闭得时候，那样modal就可以不再渲染了。
```tsx
function Example()
{
    const [content,setContent] = useState(null);
    function handleOpen(data)
    {
        setContent(<MyModal onExited={setContent.bind(null,null)} data={data}/>)
    }
    return <>
        <Button onClick={handleOpen.bind(null,"123")}>123</Button>
        <Button onClick={handleOpen.bind(null,"456")}>456</Button>
        {content}
    </>
}

function MyModal({onExited, data})
{
    const [visible, setVisible] = useState(true);
    function handleClose()
    {
        setVisible(false);
    }
    return <Modal visible={visible} onOk={handleClose} onCancel={handleClose} onExited={onExited}>{data}</Modal>
}

```

### What does the proposed API look like?
 onExited,onClosed or onDestroyed

**Comment by heroboy** [comment]
如果我的界面上有可能显示多种modal，并且同时只能显示一种的时候。我不必把每个可能显示modal都列出来，并分别维护他们的visible。而是在需要的时候`SetContent(<SomeModal onExited={setContent.bind(null,null)}/>)`

**Comment by afc163** [comment]
`afterClose`

**Comment by heroboy** [comment]
刚刚发现。但是为什么这个不是on开头的啊。
