### ISSUE TITLE
rc-trigger@5.1.0 has a leftover console.error

### ISSUE THREAD

**Issue by RasmusFredrikson** [ant-design/ant-design#27666]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/trigger/compare/v5.1.0...v5.1.1](https://github.com/react-component/trigger/compare/v5.1.0...v5.1.1)

### Steps to reproduce
Every component using rc-trigger for example Tooltip will spawn a console error (`Change::: true`)

### What is expected?
There shouldnt be a console.error

### What is actually happening?
A console error (`Change::: true`) is shown

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.9 |
| System | Windows 10 |
| Browser | Google Chrome: Version 86.0.4240.183 (Official Build) (64-bit) |

---
This is fixed in rc-trigger 5.1.1. https://github.com/react-component/trigger/compare/v5.1.0...v5.1.1

**Comment by afc163** [comment]
Fixed in rc-trigger@5.1.1, please remove your yarn.lock and package-lock.json, and reinstall node_modules.
