### ISSUE TITLE
Broken CodeSandBox in Table -> 'Fixed header and scroll bar with the page' example 

### ISSUE THREAD

**Issue by Avivhdr** [ant-design/ant-design#27665]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/b4w9h)

### Steps to reproduce
1. Go to https://ant.design/components/table/
2. Scroll down to 'Fixed header and scroll bar with the page' example
3. click on the 'codesandbox' icon.

### What is expected?
A working example

### What is actually happening?
error in codesandbox:
"ModuleNotFoundError
Could not find module in path: 'rc-util/lib/isMobile' relative to '/node_modules/rc-menu/8.8.3/node_modules/rc-trigger/lib/Popup/index.js'"

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | React |
| System | Web |
| Browser | Chrome/opera/edge |

**Comment by Nxtra** [comment]
Indeed, I am experiencing the same problem with multiple code sandboxes from the examples.

**Comment by Nxtra** [comment]
I don't know the core of the problem. You can fix it by downgrading the version of `antd` in `package.json`.
Set it to `"antd": "4.8.0" `.

**Comment by Avivhdr** [comment]
I used the Stackblitz example instead.
I just wanted you to know about this bug.

**Comment by afc163** [comment]
@CompuIves

**Comment by Nxtra** [comment]
This affects all CodeSandboxes linked to the examples on the antd website. 
Those working examples are one of the major selling points for antd towards new users.

**Comment by osamasayed** [comment]
What I did was to add `rc-util` package. `yarn add rc-util` and the error disappears.

**Comment by afc163** [comment]
Please remove yarn.lock and reinstall.

**Comment by afc163** [comment]
It is a codesandbox cache bug.
