### ISSUE TITLE
0.12 upload  如何让图片删除前让我做一个判断

### ISSUE THREAD

**Issue by xutiancheng** [ant-design/ant-design#2766]
- antd 版本:0.12
- 操作系统及其版本：win7
- 浏览器及其版本:chrome 版本 52.0.2743.19

      name:"upload",     
      listType: 'picture-card',
      defaultFileList: fileList,
      multiple: false,
      onChange(info){
          if(info.file.status == "done"){         
            self.props.uploadControl();
            self.props.updateArray(info.file.response);
          }
          if(info.file.status=="removed"){           
            self.state._deletePic(info.file);
          }   		
      },
点击删除图片，在删除请求返回前图片已经从页面上删除
import { Upload, Icon, Modal } from 'antd';

#### 你期待的结果是

在请求返回后再回调删除图片

**Comment by benjycui** [comment]
0.12.x 没有这个功能，需要新特性只能升级，然后 0.x.y 已经不维护了。

**Comment by xutiancheng** [comment]
升级了，可以兼容0.12的代码吗？

**Comment by benjycui** [comment]
请到官网查阅 Change log 和升级指南。
