### ISSUE TITLE
select 组件当 option 中没有找到对应 value 时，能否自定义回显值，现在是 value

### ISSUE THREAD

**Issue by Kshao123** [ant-design/ant-design#27678]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select 组件当 option 中没有找到对应 value 时，能否自定义回显值，现在是 value

### What does the proposed API look like?
..

**Comment by Fengly0503** [comment]
然后有解决方案吗？

**Comment by yoyo837** [comment]
目前不支持，需要加一个相关render方法的API

**Comment by huayu611** [comment]
当前我是新建一个组件把select套住，然后检查value在不在option 里面。如果不在，则为空。

**Comment by Fengly0503** [comment]
> 当前我是新建一个组件把select套住，然后检查value在不在option 里面。如果不在，则为空。

也只能这样了

**Comment by JuniorTour** [comment]
> 目前不支持，需要加一个相关render方法的API

@yoyo837 @zombieJ 打扰了，请问我可以接手并实现这个`自定义label渲染`的 feature 吗？

我预计会给 [rc-select](https://github.com/react-component/select) 的 [singleSelctor.tsx](https://github.com/react-component/select/blob/master/src/Selector/SingleSelector.tsx) 增加一个 `singleSelectorLabelRender?: (value: RawValueType) => string | React.ReactElement;` 属性，
支持传入一个函数，接收`当前选中值`为第一个参数`(value: RawValueType)`，返回 ` string | React.ReactElement`作为 ```<span className={`${prefixCls}-selection-item`} title={title}>```的子元素。

**Comment by yinjunjian0** [comment]
确实不少场景需要这个支持

**Comment by KJlmfe** [comment]
打扰了，想问下这个有什么进展么？

**Comment by pfdgithub** [comment]
看样子，没有任何进展

**Comment by pfdgithub** [comment]
为 rc-select 提了 PR ，支持了 labelRender 配置。  
https://github.com/react-component/select/pull/760  

@afc163 @yesmeck  @yiminghe @chenshuai2144 
有人能处理一下吗？使用场景还是挺多的。

**Comment by biology-w** [comment]
这个功能没有进展嘛？

**Comment by pfdgithub** [comment]
可能要世界末日才会有进展吧

**Comment by Zhang-ZhuYan** [comment]
2023年了有解决方案了吗，测试每次都把这个当bug来提

**Comment by jianglikui** [comment]
👀

**Comment by CyanCherry** [comment]
可能要收复美利坚省才有进展吧

**Comment by duxphp** [comment]
请问下不维护了么 这个一年了还没有合并么

**Comment by afc163** [comment]
@duxphp 欢迎 PR 哦，我们每周都在发版本。

**Comment by wparam** [comment]
找了一圈API, 原来是正常设定......

不过话说回来, 下拉框显示的值不在options里, 一旦用户改过, 最早显示的值就再找不回来吧.

**Comment by yoyo837** [comment]
> 找了一圈API, 原来是正常设定......
> 
> 不过话说回来, 下拉框显示的值不在options里, 一旦用户改过, 最早显示的值就再找不回来吧.

所以，这些应该由业务去处理，组件只是展示和交互，options给对就行，是不是历史的，从哪里来由业务逻辑处理

**Comment by wjj5728** [comment]
啥时候支持一下antd@4

**Comment by yoyo837** [comment]
> 啥时候支持一下antd@4

4.x 不再添加新功能支持了
