### ISSUE TITLE
Uncaught TypeError: Cannot add property key, object is not extensible

### ISSUE THREAD

**Issue by xieying** [ant-design/ant-design#27676]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/e5319bd1df8b716a84f80bc61193932c02dfcac0/components/transfer/index.tsx#L332](https://github.com/ant-design/ant-design/blob/e5319bd1df8b716a84f80bc61193932c02dfcac0/components/transfer/index.tsx#L332)

### Steps to reproduce
1.引入antd中Transfer组件
2.在代码中使用Transfer组件
3.浏览器访问项目，点击弹出穿梭框时提示Uncaught TypeError: Cannot add property key, object is not extensible

### What is expected?
正确显示穿梭框

### What is actually happening?
提示错误：Uncaught TypeError: Cannot add property key, object is not extensible

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.8.6 |
| System | Windows10 |
| Browser | Google Chrome  85.0.4183.121 （64位） |

---
通过将问题语句修改为record = {...record, key: rowKey(record)};后可正确运行

**Comment by Kryst4ljy** [comment]
我也遇到了这个问题，我的项目用npm run start在本地启动，点击显示穿梭框报错，但是打包上测试环境之后，可以正常使用，就很迷。

**Comment by BugHiding** [comment]
@afc163 您好。
https://github.com/ant-design/ant-design/blob/e5319bd1df8b716a84f80bc61193932c02dfcac0/components/transfer/index.tsx#L332

当`Transfer dataSource`传入 `immutable` 的数据时，这行会报错。
`Cannot add property key, object is not extensible`
