### ISSUE TITLE
onSelect tree node expend child 

### ISSUE THREAD

**Issue by xiaofengqqcom123** [ant-design/ant-design#27674]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
类似于multiple模式，单击父节点展开子节点（目前在非multiple模式下，展示子节点两种方式：1. 点击switcherIcon才展示下游 2. 手动控制expandKeys）
multiple Demo: https://codesandbox.io/s/xnjbo?file=/index.js

需求：点击节点展开子节点，请求后端接口，展示子节点

### What does the proposed API look like?
clickTarget:  switcherIcon(default)/ node

**Comment by afc163** [comment]
> 点击switcherIcon才展示下游

用默认模式加上 multiple 属性就行了。

https://ant.design/components/tree-cn/#components-tree-demo-basic

**Comment by xiaofengqqcom123** [comment]
> > 点击switcherIcon才展示下游
> 
> 用默认模式加上 multiple 属性就行了。
> 
> [ant.design/components/tree-cn/#components-tree-demo-basic](https://ant.design/components/tree-cn/#components-tree-demo-basic)

不要支持 选中多个

**Comment by afc163** [comment]
https://ant.design/components/tree-cn/#components-tree-demo-basic

这个有啥问题呢？
