### ISSUE TITLE
Cascader 在表格中加入校验需点击两次才能弹出下一级

### ISSUE THREAD

**Issue by monsuns** [ant-design/ant-design#2767]
#### 本地环境

- antd 版本:1.9.1
- 操作系统及其版本：windows 10
- 浏览器及其版本: chrome 52

#### 你做了什么？

引入Form表单,并加入级联选择框Cascader, 为级联选择加入Form验证, 则级联选择框无法自动弹出第二级或第三级, 需要点击两次, 如果去除Form校验则正常.
(首次加载可重现, 选择框有内容后更改内容则不需要点击两次. )

#### 你期待的结果是：

正常弹出, 正常验证

#### 可重现的在线演示

http://codepen.io/monsuns/pen/WxWZjp

**Comment by benjycui** [comment]
我就知道是这个原因。。。 http://ant.design/components/form/#this.props.form.getFieldProps(id,-options)

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by monsuns** [comment]
@benjycui 不使用getFieldProps 该如何加入表单校验? 官网上似乎没看到有示例代码

**Comment by benjycui** [comment]
> 但是loadData还是没法点击一次弹出下一级.

rc-cascader 需要做点修改。

**Comment by benjycui** [comment]
trace: https://github.com/react-component/cascader/pull/13

**Comment by benjycui** [comment]
如果需要 `changeOnSelect` 的话，等上面那个 PR 合并后就可以了。

但如果不想用 `changeOnSelect`，就会比较麻烦。。。

**Comment by benjycui** [comment]
> 但是loadData还是没法点击一次弹出下一级.

监听 Cascader[onSelect] 事件，并把 `activeValue` 设置回去即可。

**Comment by monsuns** [comment]
>监听 Cascader[onSelect] 事件，并把 activeValue 设置回去即可。

@benjycui 抱歉没有理解, 可否在 [示例代码](http://codepen.io/monsuns/pen/WxWZjp) 中修改给个例子? 万分感谢.

**Comment by FOCUSWEB** [comment]
请问这个问题修复过了吗？我在使用时还是出现这个同样的问题，最新版本
