### ISSUE TITLE
use dependencies in form item which is used in form list is not work, even though set the dependencies path by form list name

### ISSUE THREAD

**Issue by zhuyuedlut** [ant-design/ant-design#27687]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-btarfv?file=index.js](https://stackblitz.com/edit/react-btarfv?file=index.js)

### Steps to reproduce
- add sights 
- input Signt or Price
- see console.log
- change the sight but Price validate can not work

### What is expected?
change the form item value and the depended form item validate will work

### What is actually happening?
dependencies is not work

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.12.0 |
| System | windows |
| Browser | all |

**Comment by zhuyuedlut** [comment]
文档中说了dependencies 应该怎么设置，但是设置了form List的name仍然不起作用~

**Comment by zhuyuedlut** [comment]
@afc163 偏右大佬，具体研究了下源码，发现问题如下，当我formList中使用dependencies的时候，dependencies往往是['a', 0, 'c']这种形式，此时useForm.js中的代码的处理就会有问题，代码如下：
```
  _this.getFieldEntities().forEach(function (field) {
     // 注意这里，直接获取field的dependencies，若dependencies为数组，数组中的每个元素代表不同的field则没有问题
     // 若是数组的元素是代表FormList中类似层级的表示就像文档中写的['user', 1, 'xxxx']则后面根据namePath找到对应的fields
    // 永远不会找到
      var dependencies = field.props.dependencies;
      (dependencies || []).forEach(function (dependency) {
        var dependencyNamePath = getNamePath(dependency);
        dependencies2fields.update(dependencyNamePath, function () {
          var fields = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : new Set();
          fields.add(field);
          return fields;
        });
      });
    });
```

**Comment by ssloth** [comment]
> 文档中说了依赖关系应该怎么设置，但是设置了form List的名称仍然不起作用〜

例子中的 dependencies 这样写， [ ["sights", field.fieldKey, "price"] ]

**Comment by zhuyuedlut** [comment]
啊，复现url笔误打错了，但是设置为fieldKey也不会生效

**Comment by ssloth** [comment]
> 啊，复现url笔误打错了，但是设置为fieldKey也不会生效

deps 是 数组，path也是数组， 是个二维数组。 [[ ], [ ]]

**Comment by jdalrymple** [comment]
Even when updating the deps array, shouldnt it inherit the name from the parent Form List? Similar to how the name property does?: https://stackblitz.com/edit/react-btarfv-sgok81?file=index.js

**Comment by IrisZhang** [comment]
试试 [ [list_name, field.name, "price"] ]

**Comment by afc163** [comment]
```diff
- dependencies={["sights", field.fieldKey, "sight"]}
+ dependencies={[["sights", field.fieldKey, "sight"]]}
```

**Comment by akira0912** [comment]
thanks
