### ISSUE TITLE
Select mode="tags" 输入存在问题

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#27683]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#components-select-demo-tags](https://ant.design/components/select-cn/#components-select-demo-tags)

### Steps to reproduce
问题1：一直输入空格
问题2: 输入 aaa，然后一直输入空格

### What is expected?
问题1: 显示正常
问题2: 显示正常

### What is actually happening?
问题1: 空格不能一直按
问题2: aaa 被遮挡

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | lastest |
| System | mac |
| Browser | chrome |

---
3.x 版本看上去是可以的  https://codesandbox.io/s/optimistic-hooks-lbdvj?file=/index.js

**Comment by baxtergu** [comment]
ant-select-selection-item-content

**Comment by baxtergu** [comment]
我提交了一个PR修复了这个问题，麻烦有review权限的帮忙看下，感谢
