### ISSUE TITLE
Pagination component increases the number of records per page that can be input.Now you can only make a drop-down selection.

### ISSUE THREAD

**Issue by zhangqhzz** [ant-design/ant-design#27684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I can show the records I want on one page

### What does the proposed API look like?
To improve the showsizechanger parameter, you can input and drop down.

**Comment by afc163** [comment]
There is another bug (https://github.com/ant-design/ant-design/issues/27688) need to resolve before enable Pagination select `showSearch`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/42608 ~
