### ISSUE TITLE
[Tree] 拖动一个节点后，hover 效果和 title 提示不正确

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27692]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-draggable](https://ant.design/components/tree-cn/#components-tree-demo-draggable)

### Steps to reproduce
拖动 `0-0-0-1` 至 `0-0-0-0` 上方

### What is expected?
`hover` 效果出现在 `0-0-0-1`上，`title` 提示应为 `0-0-0-1`

### What is actually happening?
`hover` 效果出现在 `0-0-0-0`上，`title` 提示为 `0-0-0-0`

![tree3](https://user-images.githubusercontent.com/50612752/98782534-1ccc1180-2433-11eb-97ee-1f4938ae34a3.gif)

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
这个和浏览器有关系，antd 这边貌似做不了什么。

**Comment by AlanCutFlim** [comment]
@afc163  一些库如 `react-beautiful-dnd` 好像没有这样的问题。
https://react-beautiful-dnd.netlify.app/iframe.html?id=board--simple

![Kapture 2020-12-21 at 16 28 28](https://user-images.githubusercontent.com/50612752/102755775-d78fed80-43a9-11eb-8d2f-bd4ad1afed11.gif)
