### ISSUE TITLE
Set Avatar `size` is not working

### ISSUE THREAD

**Issue by Korn704** [ant-design/ant-design#27690]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/skeleton-fyltt)

### Steps to reproduce
When I use `<Avatar shape="circle" size={32} src={profileImg} />`,  
then I see the `<span />` is styled `width` and `height` are `32px`.
But the `<img />` tag not

### What is expected?
Avatar size should be set

### What is actually happening?
Avatar size cannot set

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | React |
| System | CodeSandbox |
| Browser | Chrome 86.0.4240.183 |

**Comment by hengkx** [comment]
没加样式， https://codesandbox.io/s/skeleton-forked-m84ii?file=/src/index.js
