### ISSUE TITLE
Table分页错误

### ISSUE THREAD

**Issue by carr123** [ant-design/ant-design#277]
var pagination = {
		    total: data.length,
		    current: 1,
		    pageSize: 3
};

<Antd.Table columns={columns} dataSource={data} pagination={pagination} />

我这样设置table每页显示3条数据，我的数据共有20多条。但是 Pagination 控件只显示左右箭头按钮，不显示页号码了，点击前一页后一页按钮也不翻页(被禁用了)。
我用的是antd@beta

**Comment by afc163** [comment]
给个简化的例子，按楼主的描述没有重现问题。
