### ISSUE TITLE
Modal.confirm弹窗确定和取消默认变成英文

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#27709]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-3ydbu6?file=index.js](https://stackblitz.com/edit/react-3ydbu6?file=index.js)

### Steps to reproduce
Modal.confirm弹窗确定和取消默认变成英文

### What is expected?
期望显示确定和取消

### What is actually happening?
目前显示cancel和ok

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.13.1 |
| System | window 10 |
| Browser | chrome 83.0.4103.61 |

**Comment by bihongbin3027** [comment]
![image](https://user-images.githubusercontent.com/15045200/98890440-ed6ee080-24d6-11eb-8e91-c5478b5a7922.png)

**Comment by afc163** [comment]
https://ant.design/components/modal-cn/#components-modal-demo-locale

或者

https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%EF%BC%9F
