### ISSUE TITLE
RangePicker 无法设置为中文显示

### ISSUE THREAD

**Issue by Mh2336393** [ant-design/ant-design#27701]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s4yh2?file=/index.js)

### Steps to reproduce
就设置不成中文 我们用户是国内用户啊 这个肯定不行~~~~~~~~~~~耗费了大半天时间 就这么个事  就这个事

### What is expected?
日期可以中文展示 

### What is actually happening?
英文展示，，各种设置都不管用 ConfigProvider 也用过了

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16 |
| System | windows10 |
| Browser | 谷歌 |

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/23891

**Comment by afc163** [comment]
使用 ConfigProvider 包裹整个应用即可：https://codesandbox.io/s/antd-reproduction-template-forked-sl8px?file=/index.js

**Comment by Mh2336393** [comment]
> 使用 ConfigProvider 包裹整个应用即可：https://codesandbox.io/s/antd-reproduction-template-forked-sl8px?file=/index.js

大佬爱你~

**Comment by afc163** [comment]
@Mh2336393 遇到问题先花点看文档，不要着急 https://ant.design/docs/react/i18n-cn

**Comment by Mh2336393** [comment]
> 使用 ConfigProvider 包裹整个应用即可：https://codesandbox.io/s/antd-reproduction-template-forked-sl8px?file=/index.js
还是不行demo可以 用到项目里面就不行 我是低版本升上来得 umi 和antd 都做了了升级 
![image](https://user-images.githubusercontent.com/48132028/98817436-0fc81600-2465-11eb-8c5b-8f31c47053d1.png)
![image](https://user-images.githubusercontent.com/48132028/98817466-16ef2400-2465-11eb-80a3-c8c7b324fea5.png)
![image](https://user-images.githubusercontent.com/48132028/98817504-240c1300-2465-11eb-99df-b1e457fe4714.png)
![image](https://user-images.githubusercontent.com/48132028/98817601-4aca4980-2465-11eb-8783-bbeb2b43e8ed.png)
node_modules 删了重装好几回了

**Comment by afc163** [comment]
@Mh2336393 给 repo 重现。

另外你如果用了 umi，都不需要手动加 ConfigProvider，这里开启一下就行：https://umijs.org/zh-CN/plugins/plugin-locale#default

**Comment by Mh2336393** [comment]
> @Mh2336393 给 repo 重现。
> 
> 另外你如果用了 umi，都不需要手动加 ConfigProvider，这里开启一下就行：https://umijs.org/zh-CN/plugins/plugin-locale#default
https://github.com/Mh2336393/-antd/tree/master

**Comment by Mh2336393** [comment]
master 下 npm run start 就能跑起来

![image](https://user-images.githubusercontent.com/48132028/98821797-f9bd5400-246a-11eb-9f9d-f7b5613e77b8.png)
![image](https://user-images.githubusercontent.com/48132028/98821830-0477e900-246b-11eb-9b68-1c4e101b18e2.png)

**Comment by zsl1549** [comment]
还是显示英文 太恶心了

**Comment by EricYangXD** [comment]
将 import 'moment/locale/zh-cn';
修改为：
import 'moment/dist/locale/zh-cn';

**Comment by mahao9** [comment]
> 在表单里面似乎获取不到value值了

**Comment by mahao9** [comment]
> 使用 ConfigProvider 包裹整个应用智能：https://codesandbox.io/s/antd-reproduction-template-forked-sl8px?file=/index.js

如果在form表单里面就取不到value了

**Comment by wywsoor** [comment]
我发现了问题了 造成这个原因的是安装 node modules 是通过cnpm 安装的 删除依赖从新使用npm安装即可解决问题

**Comment by xsjcTony** [comment]
> 将 import 'moment/locale/zh-cn'; 修改为： import 'moment/dist/locale/zh-cn';

正解

**Comment by Hubartist** [comment]
> 将 import 'moment/locale/zh-cn'; 修改为： import 'moment/dist/locale/zh-cn';

我的解决方案是把moment升级到antd依赖的版本，然后采用上面的方式导入moment就可以解决了

**Comment by zhoujinjina** [comment]
在表单中使用日期选择框,汉化后表单onFinish中的values获取不到date，显示undefined，这是为啥啊

**Comment by SmartWrh** [comment]
> import 'moment/dist/locale/zh-cn';

正解！折腾半天也是醉了= =
