### ISSUE TITLE
请问ant design vue 的国际化不支持印尼语吗？

### ISSUE THREAD

**Issue by pwyGouxiong** [ant-design/ant-design#27708]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们用的ant design vue  做国际化时发现ant design vue文档里所支持的语种不包括印度语，但是发现ant design react的文档里有支持，请问ant design vue 的国际化不支持印尼语吗

### What does the proposed API look like?
期望支持

**Comment by afc163** [comment]
反馈错地方了。

**Comment by yoyo837** [comment]
https://github.com/vueComponent/ant-design-vue
