### ISSUE TITLE
Tree child has wrong indent when deleted

### ISSUE THREAD

**Issue by kovalenkovpu** [ant-design/ant-design#27702]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tree-children-deletion-wo0mv)

### Steps to reproduce
1. Use `Tree` component of Ant Design;
2. Create 2-level data source structure (parent-child relation);
3. Create `Title` component to pass to `title` field of tree data item;
4. Create `onDelete` handler for deleting child node which removes current child from data source;
5. Pass `onDelete` handler to each data item via `title` field;
6. Create handler for rendering tree data based on data source and pass it to `treeData` prop of a `Tree`;
7. When tree is rendered - click on delete icon to remove child node.

### What is expected?
Child node is removed from tree, no layout effects are present.

### What is actually happening?
Child node is removed from tree, but for some period of time (hundreds of ms) left indent of child is reset and child node is aligned left. 

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0.0 |
| System | Windows 10 Enterprise |
| Browser | Google Chrome Version 88.0.4315.4 (Official Build) dev (64-bit) |

---
That doesn't happen in all cases, no specific logic is noticed.

**Comment by tdawes** [comment]
I'm spotting the same thing when changing the children property of a data node. The old data is de-indented and painted momentarily before the new data is loaded. 

Is there any progress on this?

**Comment by allenm** [comment]
Try rc-tree@5.2.2 , this bug has been fixed .  Wait antd@4.17.0.

**Comment by mhco1** [comment]
hi, thank, serius, your code help me

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/tree/pull/743
