### ISSUE TITLE
ref拿到的tree组件多了renderTree和setTreeRef方法，而无tree组件的很多方法，如scrollTo等

### ISSUE THREAD

**Issue by a873054267** [ant-design/ant-design#27711]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/a873054267/antd-tree.git](https://github.com/a873054267/antd-tree.git)

### Steps to reproduce
1. npm i 
2. npm start
3. 在控制台查看tree对象

### What is expected?
tree具有scrollTo函数

### What is actually happening?
tree无scrollTo函数

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.2.0 |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
Please upgrade to antd 4.x
