### ISSUE TITLE
[建议]级联组件等类似树结构的希望统一treeDataSimpleMode 、fieldNames

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#27710]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望能够达成后台给定统一标准的数据，前台类似的展现结构组件能够统一使用数据
如TreeSelect、Tree、Cascader
比如TreeSelect的属性treeDataSimpleMode 就很好，后台仅给列表就能树形显示，那能否将几个树形组件API统一呢
另外Cascader的fieldNames属性也很好，也希望各树形组件能支持

### What does the proposed API look like?
Cascader的fieldNames通用
TreeSelect的treeDataSimpleMode通用

**Comment by afc163** [comment]
Trace #24282
