### ISSUE TITLE
Input 通过value设置值后，表单验证不会通过。

### ISSUE THREAD

**Issue by tangsj** [ant-design/ant-design#2771]
#### 本地环境

- antd 版本: 1.2.1
- 操作系统及其版本： OSX EI Capitan 10.11.6
- 浏览器及其版本: Chrome 52

#### 你做了什么？

Input {...nameProps} value={ service.name } placeholder="输入机构名称"

this.props.form.validateFields((errors, values) => {
 // 验证不会通过 
});

#### 你期待的结果是：

表单验证通过

#### 实际上的结果：

依然提示内容未输入

#### 可重现的在线演示
无

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1353

http://ant.design/components/form/#this-props-form-getfieldprops-id-options
