### ISSUE TITLE
compact dark theme

### ISSUE THREAD

**Issue by AlexKutschera** [ant-design/ant-design#27718]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to see a dark compact theme similar to the light compact theme but with dark mode

### What does the proposed API look like?
same as with the light compact theme

**Comment by afc163** [comment]
See https://ant.design/docs/react/customize-theme
