### ISSUE TITLE
Slider - a style error occurs when the marks span is too large

### ISSUE THREAD

**Issue by Vermouth1995** [ant-design/ant-design#27716]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-flower-937bq)

### Steps to reproduce
```
<Slider
        marks={{
          10: "10M",
          20: "20M",
          100: "100M",
          200: "200M",
          1000: "1000M",
          2000: "2000M",
          10000: "10000M"
        }}
      />
```

### What is expected?
显示完整的 marks

### What is actually happening?
显示不完整

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | react |
| System | win10 |
| Browser | Chrome 86.0.4240.183 |

**Comment by afc163** [comment]
It is not a bug, the`key` of marks should be in a range of `0 ~ 100`.

https://codesandbox.io/s/stupefied-keldysh-do0jw?file=/index.js
