### ISSUE TITLE
[Tabs] Tabs 横向滚动时清空 Tabs 会导致添加按钮消失

### ISSUE THREAD

**Issue by HSunboy** [ant-design/ant-design#27712]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/hsunboy/pen/yLJGabq?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2F](https://codepen.io/hsunboy/pen/yLJGabq?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2F)

### Steps to reproduce
滚动 Tab bar，然后点击 delete 清空 Tab bar

### What is expected?
add 按钮置于开头

### What is actually happening?
add 按钮消失

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.x |
| System | mac |
| Browser | chrome 80  |

**Comment by rinick** [comment]
@zombieJ
Please check my PR in the rc-tabs project
