### ISSUE TITLE
Layout component members

### ISSUE THREAD

**Issue by Toumani** [ant-design/ant-design#27727]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm using Kotlin/JS to build a react App and I wish to use Ant Design. I want to import Layout.Header, Layout.Content, Layout.Footer and Layout.Sider as components. Doing so is quite complicated, since those components are not exported at the root. I suggest to make them available like other components (i.e. import { Header, Content, Footer, Sider } from 'antd').

### What does the proposed API look like?
I suggest to add 
> export { default as Header } from './layout/header';
> export { default as Content} from './layout/content';
> export { default as Footer } from './layout/footer';
> export { default as Sider} from './layout/sider';
in `ant-design/components/index.tsx` and create the corresponding folders and files as indexes.
Hope this can help other developpers.
Thank you for your amazing work!

**Comment by afc163** [comment]
We won't export Header, Content, Footer, Sider from antd, first level components is limit.
