### ISSUE TITLE
Link disabled style error

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#27725]

**Comment by hengkx** [comment]
@xrkffgg 线上是好的？

**Comment by hengkx** [comment]
我记得是不是 有人修过 ，但是我用的是最新的悬浮颜色不对

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/98945421-744ea800-252d-11eb-8823-50ed6ca39484.png)

**Comment by xrkffgg** [comment]
.. 我以为是 button 的 link 呢
