### ISSUE TITLE
Modal.confirm等方法无法设置getContainer

### ISSUE THREAD

**Issue by haite** [ant-design/ant-design#27730]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
统一设置Modal.confirm等方法的弹窗的挂载节点

### What does the proposed API look like?
Modal.config({
    prefixCls,
    getContainer
});

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/23085#issuecomment-632071222
