### ISSUE TITLE
Table: bug (?) with "index" prop of Column's "render"

### ISSUE THREAD

**Issue by e965** [ant-design/ant-design#27732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-pagination-table-index-bug-60o4w)

### Steps to reproduce
0. Open a demo
1. Look at the "Render prop Index" column
2. Go to another table page

### What is expected?
Index value will match the data and change on each page

### What is actually happening?
Index value is static

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0.1 |
| System | Windows 10.0.19041 |
| Browser | Google Chrome 86.0.4240.198 |

---
It is possible that this was intended. In this case, please tell why this behavior was done.

**Comment by afc163** [comment]
It is not a bug, `index` is designed to be current page number.

In ajax mode for example, dataSource only contains current page data, there is no way to know real index from top.

https://ant.design/components/table-cn/#components-table-demo-ajax
