### ISSUE TITLE
SELECTION_NONE for table selection option

### ISSUE THREAD

**Issue by KrishnaPG** [ant-design/ant-design#27733]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
SELECTION_NONE clears any current selections from the table.

Currently only "all" section is supported with Table.SELECTION_ALL,   But if one or two rows are selected by the user and want to clear those selections, there is no "efficient" way (other than to manually unselect each of them, or use the "select all" and then "select invert" - both of which are not effective UX, since they require multiple mouse clicks).

### What does the proposed API look like?
Where the         Table.SELECTION_ALL,     Table.SELECTION_INVERT, are present, kindly add the SELECTION_NONE option.

**Comment by n0ruSh** [comment]
@afc163 I would like to pick this one. If we add a `SELECTION_NONE` option as suggested in the issue, a label for the option is required which also needs to be localized. I can put in Chinese version `清空所有` and English version `Clear current page`. Any suggestions how to get the translations for other locales :- ?

**Comment by afc163** [comment]
@n0ruSh LGTM
