### ISSUE TITLE
使用Tag遇到的问题

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#2773]
#### 本地环境

- antd 版本: 1.9.1
- 操作系统及其版本：chrome 54.0.2824.0 dev-m (64-bit)
- 浏览器及其版本: windows10

#### 你做了什么？

通过一个数组生成一组tag，标签可以删除，删除标签的时候请求服务端进行删除

#### 你期待的结果是：

服务端返回失败的时候，对应的tag没有被删除

#### 实际上的结果：

服务端返回失败的时候，对应的tag被删除了

**Comment by benjycui** [comment]
现在 `Tag` 不支持异步关闭。

先说明你这样做的考虑。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/1267

**Comment by faithfairy** [comment]
在 afterClose 的事件中，触发重新请求数据队列，删除的那条无法重新渲染出来。

**Comment by benjycui** [comment]
> 删除的那条无法重新渲染出来。

这不是正常么。

**Comment by faithfairy** [comment]
不好意思，是我弄错了，是正常的。

**Comment by cdscawd** [comment]
。。。
