### ISSUE TITLE
InputNumber enter 4 digits  formatter 5 digits error

### ISSUE THREAD

**Issue by 445339805** [ant-design/ant-design#27748]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number/#components-input-number-demo-formatter](https://ant.design/components/input-number/#components-input-number-demo-formatter)

### Steps to reproduce
置于 win10 系统，微软输入法，中文模式下，谷歌浏览器 86.0.4240.198，点击https://ant.design/components/input-number/#components-input-number-demo-formattern链接，$ 的 demo，随机输入4位数字1

In win10 system, input method, Microsoft Chinese mode, the Google browser 86.0.4240.198, click on the link https://ant.design/components/input-number/#components-input-number-demo-formattern, $ demo，Enter 4 digits

### What is expected?
正常显示4位数字
Display 4 digits normally

### What is actually happening?
显示5位数字
But it shows five digits

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | react |
| System | win10 |
| Browser | chrome 86.0.4240.198 |

---
变为 5位数字后，后面每输入一位数，会增加3位，（必现微软中文输入法  上面链接 InputNumber 官网$输入框 demo）
When it becomes a five-digit number, it increases by three digits for each subsequent digit entered

**Comment by dbfu** [comment]
这个问题你解决了吗？

**Comment by i3web** [comment]
保持关注。而且只有微软拼音输入法才会毕现。其他中文输入法（QQ拼音）就没有这个问题。

**Comment by i3web** [comment]
底层是组件是rc-input-number，也会出现一样的问题

**Comment by i3web** [comment]
关于此问题，调研了一下，可能是chrome版本升级引起的。
已知会出现问题的chrome版本(最新)是87.0.4280.88.
从github的反馈issue来看，最早出现该问题的日期是在2020年10月27号(https://github.com/ant-design/ant-design/issues/27403)
我尝试将chrome版本降级为9月10日的版本(85.0.4183.102)，发现未出现这个问题。
电脑的微软拼音输入法未有任何改动。
具体是哪个chrome版本升级引起的，可采用二分法

**Comment by i3web** [comment]
各个chrome版本对应的发布日期
```
87.0.4280.88 2020年12月3日
87.0.4280.661 2020年11月8日
86.0.4240.198 2020年11月12日
86.0.4240.111 2020年10月21日
86.0.4240.75 2020年10月8日
85.0.4183.102 2020年9月10日
```

**Comment by afc163** [comment]
@i3web 最新版的 Chrome 是否还会重现这个问题。

**Comment by afc163** [comment]
目测最新版本 Chrome 依然有这个问题。

**Comment by EliezerWu** [comment]
Safari浏览器，版本14.1.1 (15611.2.7.1.6, 15611)，按“中/英”按键切换中文也会出现这个问题

**Comment by zombieJ** [comment]
Close since `rc-input-number` refactor
