### ISSUE TITLE
表单项  form-item 帮助文本导致高度跳动。

### ISSUE THREAD

**Issue by lzqtxwd** [ant-design/ant-design#27746]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/21206](https://github.com/ant-design/ant-design/issues/21206)

### Steps to reproduce
快速触发帮助文本隐现。

### What is expected?
表单项form-item高度不会跳动

### What is actually happening?
高度跳动。导致表单项内容位置抖动。

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | W10 |
| Browser | chrome\ff\edge |

**Comment by kangkang12** [comment]
![image](https://user-images.githubusercontent.com/34826299/99033548-1ade8b80-25b6-11eb-9d72-bd2d4193ed79.png)

**Comment by Veveue** [comment]
+1

**Comment by afc163** [comment]
> 快速触发帮助文本隐现

如何稳定重现呢？

**Comment by kangkang12** [comment]
![20201116_133729](https://user-images.githubusercontent.com/34826299/99216637-14981b80-2811-11eb-9eea-1c6694f9e266.gif)
触发表单校验报错。再取消表单报错。偶现。。有的时候第一次操作就出现了。。。

**Comment by afc163** [comment]
我刚才操作重现了一次，确实是低概率偶现。

**Comment by kangkang12** [comment]
![image](https://user-images.githubusercontent.com/34826299/99216920-cf281e00-2811-11eb-80c0-45693d180c86.png)
这个看运气  有时候第一次操作就出现了  。。。这两个类名同时出现就会有这个问题。。。

**Comment by kangkang12** [comment]
还有个问题，请教一下大佬。
![image](https://user-images.githubusercontent.com/34826299/99217173-69886180-2812-11eb-8fd2-033be369ad2c.png)
edge。。表格固定列。。没有分割线。。这个问题是不处理了吗？？

**Comment by zombieJ** [comment]
#26824 这个重新调整了逻辑，我看看能不能抽出来。

**Comment by Yunnkii** [comment]
请问这个问题有没有解决啊？

**Comment by Yunnkii** [comment]
@zombieJ @afc163

**Comment by Yunnkii** [comment]
@afc163 @zombieJ

**Comment by Yunnkii** [comment]
请问这个 issue 现在的进度怎么样了？

**Comment by daoket** [comment]
被.ant-form-item-with-help 下面的 margin-bottom: 0; 覆盖造成的，调整下 css 优先级即可。

**Comment by a584738858** [comment]
所以解决了嘛，这个问题

**Comment by cheerful-li** [comment]
+1

**Comment by Homingciu** [comment]
是有概率会在success的时候，还添加.ant-form-item-with-help（margin-bottom）导致的

**Comment by flatpig** [comment]
+1

**Comment by SaberWang8023** [comment]
所以现在这个问题解决了嘛？4.16.11还是有这个问题哎～
![image](https://user-images.githubusercontent.com/18320357/128826473-67ba368b-d9d2-42b3-a1a8-9d5a29c8b945.png)

**Comment by DanyZzzzz** [comment]
感觉是不想搞这个问题了

**Comment by Jervis2049** [comment]
I also encountered this problem, it seems to have not been solved.

**Comment by Jervis2049** [comment]
```less
  :deep(.ant-form-item-has-success) {
    &:not(.ant-form-item-with-help) {
      margin-bottom: 24px;
    }
  }
```

**Comment by CanMr** [comment]
![image](https://user-images.githubusercontent.com/30115608/148155143-20a1da5c-e0ac-482d-919c-926cfc59032e.png)
vue3的这个版本也有同样的问题，就是不改吗？2020年的问题2022年都不解决  每次都要靠手动重置才可以解决 我要日你哥

**Comment by ronnycyy** [comment]
@afc163 @zombieJ 
您好，我研究了一下，有如下结论

**稳定重现方法**
1. 在`input`里输入`1`，删除，触发检查
2. 在`0.3s`内 `输入1再删除`

**抖动原因**
`.ant-form-item`设置了`0.3`秒`margin-bottom`从`0px`过渡到`24px`，这和`.ant-form-item-with-help .ant-form-item-explain`的`height`的过渡相互配合，工作得很好。但如果在`0.3s`内按下删除，将导致`margin-bottom`直接为`0`，于是仅剩`.ant-form-item-with-help .ant-form-item-explain`的`height`在变化，于是发生了抖动。

**解决方案**
我提供了一个[PR](https://github.com/ant-design/ant-design/pull/33636)，实验发现加上这一行以后，`margin-bottom`不会直接为`0`，有空看下吧

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/33644

**Comment by CanMr** [comment]
> @afc163 @zombieJ 您好，我研究了一下，有如下结论
> 
> **稳定重现方法**
> 
> 1. 在`input`里输入`1`，删除，触发检查
> 2. 在`0.3s`内 `输入1再删除`
> 
> **抖动原因** `.ant-form-item`设置了`0.3`秒`margin-bottom`从`0px`过渡到`24px`，这和`.ant-form-item-with-help .ant-form-item-explain`的`height`的过渡相互配合，工作得很好。但如果在`0.3s`内按下删除，将导致`margin-bottom`直接为`0`，于是仅剩`.ant-form-item-with-help .ant-form-item-explain`的`height`在变化，于是发生了抖动。
> 
> **解决方案** 我提供了一个[PR](https://github.com/ant-design/ant-design/pull/33636)，实验发现加上这一行以后，`margin-bottom`不会直接为`0`，有空看下吧

我就是这样解决的。本地环境没有问题 发到测试环境和生产环境就有这个问题出现，我希望的是 不要每次都手动解决

**Comment by Jasonlee6789** [comment]
请问大佬，为什么我一个<Form>里面的两个<Form.Item>高度为什么不一样？
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/50064245/165223176-c9b8fa23-50b4-47ed-bcdb-4976c607cbdc.png">
<img width="490" alt="image" src="https://user-images.githubusercontent.com/50064245/165223353-3a5e2ea5-a864-4602-add4-818b4df471ac.png">

**Comment by zombieJ** [comment]
> 请问大佬，为什么我一个
> 
> 里面的两个<Form.Item>高度为什么不一样？
> <img alt="image" width="1231" src="https://user-images.githubusercontent.com/50064245/165223176-c9b8fa23-50b4-47ed-bcdb-4976c607cbdc.png">
> 
> 
> <img alt="image" width="490" src="https://user-images.githubusercontent.com/50064245/165223353-3a5e2ea5-a864-4602-add4-818b4df471ac.png">

开新的 issue 并提供重现哈~
