### ISSUE TITLE
Upload 的 customRequest 怎么取到 fileList 的值？一直是空的

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#27749]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upload-onchange-forked-frvsg?file=/index.js)

### Steps to reproduce
上传一个或同时上传多个

### What is expected?
customRequest 能获取到最新的 fileList

### What is actually happening?
一直为空

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
customRequest 是处理上传，为啥需要在这里 获得 fileList？

**Comment by linxianxi** [comment]
> customRequest 是处理上传，为啥需要在这里 获得 fileList？

需要在成功的时候做一些逻辑，需要这个。不行的话就算了，换别的方式。

**Comment by yoyo837** [comment]
上传中和上传完成会触发onChange

**Comment by linxianxi** [comment]
> 上传中和上传完成会触发onChange

customRequest 以后能支持
