### ISSUE TITLE
Overflow hidden how being applied to drawer on visible

### ISSUE THREAD

**Issue by jibin2706** [ant-design/ant-design#27750]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-blackwell-5ocdj?file=/src/App.js)

### Steps to reproduce
1. click on open button
2. scroll on the body or the drawer

### What is expected?
The overflow style should be hidden

### What is actually happening?
The body is scrollable

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome 86 |

**Comment by afc163** [comment]
antd don't work well in React StrictMode now, please remove it until we support.

You can trace https://github.com/ant-design/ant-design/issues/26136 for further progress.

**Comment by monolithed** [comment]
@afc163 is closed, but overflow: hidden is still missing. 

I tried to toggle it myself, however, this is a very bad way to solve the problem and I already see where it does not work.

```tsx
afterOpenChange={(open) => {
       document.documentElement.classList.toggle('hidden', open);
}}
```
