### ISSUE TITLE
升级最新版，访问页面有异常错误

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2775]
antd版本：1.9.1
react版本："react": "^15.0.2",  "react-dom": "^15.0.2",

调试时候谷歌浏览器，Uncaught SyntaxError: Unexpected token <  blockpage.cgi?ws-session=1425159067:1 

请问这是什么错误，虽然页面可以正常访问，但是该错误不知是如何引起，把版本切换原来的版本此错误消失

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by wuhaih** [comment]
经定位问题，不是组件问题，是index.html 页面解析有误，
以下是我的单页index.html  官方初始化项目已去除了
    <meta charset="UTF-8">
    <title id='index_title'></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

增加啦
<html lang="en">

请问有什么区别麽?
以下是我的HTML配置，写的比较粗糙，见谅哈

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title id='index_title'></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" type="text/css" href="./portal.css"/>

    
    
</head>
<body>
<div id="index"></div>
</body>

**Comment by benjycui** [comment]
@wuhaih 你这 comment 无法看。

**Comment by wuhaih** [comment]
10.37.84.131:15871/cgi-bin/blockpage.cgi?ws-session=18446744071915717806:1 Uncaught SyntaxError: Unexpected token <

这段脚本执行不成功啊，是因为公司网络限制，但是我想知道为什么运行HTML会执行这段代码？

**Comment by afc163** [comment]
给不了重现的话，无法帮助到你。
