### ISSUE TITLE
Key events on checkbox

### ISSUE THREAD

**Issue by nicolasrhc** [ant-design/ant-design#27757]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-oq6w7?file=/index.js)

### Steps to reproduce
You just have to call the checkbox component, click on it, and press a key

### What is expected?
The onKeyDown and onKeyPress events are expected to be called when a key is pressed and the onKeyUp event to be called when the key is released

### What is actually happening?
The onKeyDown and onKeyPress events are not called on keypress, and the onKeyUp event does not exist in the component, although it is in the native htm component

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | windows 10 |
| Browser | chrome |

**Comment by BraisedChicken** [comment]
是 rc-checkbox 的问题吧，rc-checkbox的表现和这边是一致的。
