### ISSUE TITLE
Carousel组件无法设置垂直轮播

### ISSUE THREAD

**Issue by zOAOz** [ant-design/ant-design#27769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel-cn/](https://ant.design/components/carousel-cn/)

### Steps to reproduce
自己去设置下垂直vertical属性就知道了

### What is expected?
我通过查看源码已经知道问题在哪里了，props.vertical被重写了，这个是啥操作

### What is actually happening?
尽快修复问题吧

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | win10 |
| Browser | 最新的 |

---
\node_modules\antd\lib\carousel\index.js 在这个文件的77行，有一行这样的代码，props.vertical = dotPosition === 'left' || dotPosition === 'right'; 这个有点问题啊
上面是 var dotPosition = _this.getDotPosition();
方法时这样
function getDotPosition() {
      var _this$props$dotPositi = this.props.dotPosition,
          dotPosition = _this$props$dotPositi === void 0 ? 'bottom' : _this$props$dotPositi;
      return dotPosition;
    }

**Comment by zOAOz** [comment]
希望尽快修复吧

**Comment by yoyo837** [comment]
`antd`的`Carousel`是对`react-slick`的二次封装，并不对所有属性原样支持，比如`vertical`属性，请使用`left`和`right`来得到`vertical`的效果

**Comment by zhaochuangxin** [comment]
> `antd`的`Carousel`是对`react-slick`的二次封装，并不对所有属性原样支持，比如`vertical`属性，请使用`dotPosition`的`left`和`right`来得到`vertical`的效果

那意思就是不支持垂直切换了是吧！

**Comment by zhaochuangxin** [comment]
> 希望尽快修复吧

请问你这个垂直切换得问题解决了吗？

**Comment by xrkffgg** [comment]
https://ant.design/components/carousel/#components-carousel-demo-position\

这个 left right 不就是垂直的么
