### ISSUE TITLE
form.list add(initvalue) fields.map(item) why item does not contain this add's initvalue

### ISSUE THREAD

**Issue by qiansimin88** [ant-design/ant-design#27763]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-dynamic-form-items](https://ant.design/components/form-cn/#components-form-demo-dynamic-form-items)

### Steps to reproduce
1. 通过按钮添加add(1)
2. fields.map(field => console.log(field))
3. field 拿不到初始值，只有默认的{  fieldKey: 0
isListField: true
key: 0
name: 0 }

### What is expected?
1. 既然 form.list  add(init, index) 第一个参数接受一个初始值，那么我肯定需要在代码里 判断这个初始值的，可我在fields.map(item)  这里的Item拿不到我的初始值，只有默认的{  fieldKey: 0
isListField: true
key: 0
name: 0 }

### What is actually happening?
我想拿到我自己设置的初始值

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.12 |
| System | mac |
| Browser | chrome |

---
RT

**Comment by afc163** [comment]
see #24562

**Comment by afc163** [comment]
@zombieJ Form.List 动态新增项如何设置初始值，也是个日经帖了。

**Comment by zombieJ** [comment]
加

**Comment by afc163** [comment]
@zombieJ 可以关了么

**Comment by JackDan9** [comment]
请增加到react-component中在文档当中也体现一下吧，不然没办法去做了。

**Comment by d0ublezer0** [comment]
hello.
i have similar problem:
when add form list field onValuesChange received undefined value for each newly added field
https://stackblitz.com/edit/react-nj4v5o
