### ISSUE TITLE
Instructions customize less variable for hover 

### ISSUE THREAD

**Issue by herbertpimentel** [ant-design/ant-design#27767]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Please can you provide instructions on customize-theme section about how to change the antd default behavior for hover; 

and default behavior for hover is make it lighter than primary color

how can I change this behavior to make hover on elements be darker than primary color

i am sorry, but I am struggling with that. I already tried a lot of changes with no success.

### What does the proposed API look like?
add on customize-theme  section a example of how to change hover color

@hover-color-base

**Comment by afc163** [comment]
It can't be done now.

**Comment by monolithed** [comment]
I have the same request. I use Ant Design as a wrapper for building other systems with its own brand colors and behavior . 

For example [Alibaba](https://best.aliexpress.ru), [Tencent](https://www.tencent.com/en-us/index.html), [Taobao](https://world.taobao.com) and [Alipay](https://open.alipay.com/platform/home.htm) look different. 

What is the purpose to use Ant Design without any customization?
I believe this issue should be reopened.
