### ISSUE TITLE
Setting openKeys property on SubMenu

### ISSUE THREAD

**Issue by jakob-ed** [ant-design/ant-design#27773]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My use case is that I have a Dropdown that opens a Menu with many nested SubMenus so that I end up with a menu with many levels which can be tedious to navigate through. I want to achieve the following end user experience:
- The user navigates through the Menu and SubMenus and eventually selects a Menu.Item
- (The Dropdown with the Menu inside closes)
- **New:** The user opens the Dropdown Menu again and **all the SubMenus leading to the previously selected Menu.Item are still open**

Currently, I can't find a way to achieve this behavior. 

- Proposal 1: I think an option to solve it would be to allow `openKeys` to be set on `SubMenus` as well (like how it already works on `Menu`). [Here is an example to demonstrate what it could look like](https://codesandbox.io/s/antd-reproduction-template-forked-kd6rs?file=/index.js).
`rc-menu` appears to support `openKeys` on `SubMenu` already, however, there is no mention of this in the documentation, just found the prop in the code: https://github.com/react-component/menu/blob/v8.10.0/src/SubMenu.tsx#L66

- Proposal 2: Even more comfortable in my opinion would be an option to set "nested open keys" from the `Menu` component itself instead of from `SubMenu`. The API on `Menu` could be like an array of arrays: `<Menu openKeys={[["submenu-1"], ["submenu-1-1"]]}>`, with the nth array specifying open keys on the nth menu level. So in this example, on the first menu level, `submenu-1` should be open and on the second menu level `submenu-1-1` (which is nested inside `submenu-1`). Then the keys retrieved through `onOpenChange` could be easily used to set `openKeys` which would make things easier. 

### What does the proposed API look like?
- Proposal 1: `<SubMenu openKeys={["submenu-1-1"]}>` (See code example https://codesandbox.io/s/antd-reproduction-template-forked-kd6rs?file=/index.js)

- Proposal 2: `<Menu openKeys={[["submenu-1"], ["submenu-1-1"]]}>`, with the nth array specifying open keys on the nth menu level.

**Comment by afc163** [comment]
I prefer current usage, `openKeys` should be flatten without nested structure which is simpler.

**Comment by jakob-ed** [comment]
Ok @afc163, but just to confirm: What I'm trying to accomplish (setting SubMenus to be open) can not currently be done, right?

**Comment by afc163** [comment]
```
openKeys={["submenu-1", "submenu-1-1"]}
```

**Comment by MrFarhan** [comment]
@afc163 i am using the simple menu below is my code:

```
      <Menu
        defaultSelectedKeys={["5"]}
        mode="inline"
        style={{ justifyContent: "center" }}
        openKeys={[activeTab]}
        onOpenChange={(e) => setActiveTab(e[0])}
      >
        {renderMenuItems(items)}
      </Menu>
```

is there a way to make the sub menu open when i click on sub menu, when i add the activeTab in the openKeys, i am unable to click on the menu dropdown , i want it to dynamically open sub menus and only one menu to open at a time.
