### ISSUE TITLE
Cannot trigger <Select> <Uploader> <Dropdown> when using fastclick lib.

### ISSUE THREAD

**Issue by Haixiang6123** [ant-design/ant-design#27774]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Haixiang6123/learn-fastclick](https://github.com/Haixiang6123/learn-fastclick)

### Steps to reproduce
1. git clone the project
2. npm install 
3. npm start
4. use chrome devtools to toggle mobile view
5. goto localhost:3000
6. Try to click the Select, Uploader or Dropdown

### What is expected?
At PC browser: Expect to trigger drodown, upload event.
At mobile: Expect to trigger dropdown, upload event.

### What is actually happening?
At PC browser: Everything is fine.
At mobile: No dropdown mens and no upload events are triggered

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | react |
| System | Mac |
| Browser | Chrome |

---
I believe the fastclick library somehow has some side effects on the <Select> <Upload> and <Dropdown> component. I tried to dig into the details, but can't find out why the fastclick affects these components. Can anyone help this?

I do know using fastclick is not a good practice when using Antd (PC version), but this would be a serious problem when someone wants to have the Antd styles (Not Antd Mobile) at mobile development, and he also adds the fastclick to avoid 300ms problem.

Not sure if this is a bug or not. Hope someone could explains how those events are not triggerred when adding fastclick lib. Thx~

**Comment by afc163** [comment]
Just don't use it, nothing we can do about it.
