### ISSUE TITLE
Inconsistent and incorrect behavior of onChange event of DatePicker.RangePicker

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#27779]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/range-picker-antd482-forked-ws2xs)

### Steps to reproduce
1. Use 2 date range pickers: with and without showTime, log onChange event
2. open range without time and select dates
2a. re-open range and change date
3. open range with time and select dates
3a. re-open range and change date 

### What is expected?
when date/time is changed, onChange should be called with current values.

### What is actually happening?
- for range without time, onChange called when both dates are selected and when one of values is changed
- for range with time, onChange is called ONLY when OK button is clicked (but for that there is another event onOk)

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.12 |
| System | windows 10 |
| Browser | chrome 86 |

---
This prevents using picker in controlled mode. 

I use it in always opened mode inside another dropdown (table filter), which has its own OK key. 
It works with date range, but I cannot use it when I need also time.

Also date-only range can work better without restrictions for "both dates selected".

**Comment by afc163** [comment]
It is by designed, when RangePicker has time panel, there is no explicit end point (date cell or time panel cell?), so we have to use Ok button as a next step trigger and `onChange` would be triggered then.

**Comment by urrri** [comment]
You so helpful 👎 
You have very good and customizable library 👍 
and your components allow to be used not just in default mode. 
In my case - in always open (flat) mode together with your filter. 
(I don't want to have dropdown inside dropdown)
But this behavior breaks any other usage.

**Comment by jaworek** [comment]
Would it be possible to add prop that makes RangePicker and DatePicker without time to also show "Ok" button. This would allow having consistent behaviour across various pickers.

**Comment by jaworek** [comment]
I still think it is inconsistent behaviour. Without time onChange is triggered on select every time. This is especially the case with RangePicker. I can change "from" date and it will be applied immediately, but with time I need to press button to trigger it.
I think it would be useful to have option to trigger onChange on every click, whether it is date or time.

**Comment by wadrn** [comment]
I have met the same issue

**Comment by ryanypm** [comment]
I have met the same issue, The user is very uncomfortable and complains, I can only customize the control~

**Comment by mathieu-anderson** [comment]
I agree with jaworek, it is inconsistent behaviour and the reasoning behind it participates in this inconsistency: if `onChange` triggers on every user interaction in `RangePicker` without `showTime`, there is no resaon for the behaviour to not be the same if you add a `showTime` prop.

There might be *technical* reasons for this behaviour to be hard to implement, but it does not change the fact that it is a widely shared concern, as we can see by the many duplicates of this issue.

**Comment by kennybecerra** [comment]
Same issue, anyone have workaround for implementing a pseudo "ok" button on rangepicker when time is disabled ?

**Comment by fe-linjin** [comment]
> It is by designed, when RangePicker has time panel, there is no explicit end point (date cell or time panel cell?), so we have to use Ok button as a next step trigger and `onChange` would be triggered at it as well.

But if I rely on onCalendarChange to get disabledDate，It doesn't work!

**Comment by FengHuangDong** [comment]
Why close issue? I don't think the problem has been solved so far either
