### ISSUE TITLE
升级版本之后出现依赖错误导致react报错

### ISSUE THREAD

**Issue by cnv587** [ant-design/ant-design#2777]
#### 本地环境

- antd 版本:
- 操作系统及其版本：window10
- 浏览器及其版本:chrome 52.x

#### 你做了什么？
更新antd报错

#### 你期待的结果是：
![1](https://cloud.githubusercontent.com/assets/13713580/17802987/1300035c-6626-11e6-81ad-ba5c20983e28.jpg)
![2](https://cloud.githubusercontent.com/assets/13713580/17802992/16df6544-6626-11e6-9449-79268a8034af.jpg)

**Comment by afc163** [comment]
用 npm3

https://github.com/ant-design/ant-design/issues/2030
