### ISSUE TITLE
Form conditional field not working with React.StrictMode

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#27770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-rules-antd482-forked-5q0u6)

### Steps to reproduce
fill the first input (Name) and commit: it works fine.
check and uncheck the checkbox without filling the second field (Nickname), click the check button, it will complain that the second field is required.

### What is expected?
when "Nickname is required" checkbox is not selected the second field should not be required.

### What is actually happening?
when "Nickname is required" checkbox is not selected the second field is required.

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.31 > 17.01 |
| System | Mac OS  |
| Browser | all |

---
it works as aspected if you remove React.StrictMode

**Comment by afc163** [comment]
Trace #26136
