### ISSUE TITLE
AutoComplete里的children设置的className不会渲染到DOM上

### ISSUE THREAD

**Issue by flynn-eye** [ant-design/ant-design#27776]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-gxvdkm?file=index.js](https://stackblitz.com/edit/react-gxvdkm?file=index.js)

### Steps to reproduce
https://stackblitz.com/edit/react-gxvdkm?file=index.js

### What is expected?
自己设置的classname属性能出现在DOM上

### What is actually happening?
className好像被覆盖了

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | react 16.9.53 |
| System | macos 10.15.7  |
| Browser | chrome  86.0.4240.198 |

**Comment by xrkffgg** [comment]
AutoComplete 其实是使用的 Select。建议采用 Demo 用法，使用 Option 或 其自定义组件。
