### ISSUE TITLE
table scroll属性x设置宽度为某一值的时候，动态改变table宽度会卡顿

### ISSUE THREAD

**Issue by tanwei0425** [ant-design/ant-design#27775]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://admin.hellotanwei.cn/course/classification](https://admin.hellotanwei.cn/course/classification)

### Steps to reproduce
1. table单页数据50（大于50以上会有明显卡顿）
2. table设置scroll属性 scroll={{ x:800 }}
3. 展开收缩左侧menu（table会动态改变宽度，此时就会卡顿）

### What is expected?
不会卡顿

### What is actually happening?
卡顿

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

---
menu收缩展开会改变table的宽度，这个时候会特别卡，performance观察：Run Microtasks占用大比例时间（是否有大批量轮询）
![image](https://user-images.githubusercontent.com/37789693/99179751-7eee8480-275b-11eb-986c-46ab1627464a.png)

**Comment by tanwei0425** [comment]
antd pro table 也会出现此类问题

**Comment by tanwei0425** [comment]
> 您好@ tanwei0425。请通过分叉此链接https://u.ant.design/codesandbox-repro或最小的GitHub存储库来提供在线复制。`Need Reproduce`如果在7天内没有任何活动，则带有标记的问题将被关闭。
> 
> 你好@ tanwei0425，我们需要你提供一个在线的重现实例煞于我们帮你排查问题。你可以通过单击[此处](https://u.ant.design/codesandbox-repro)创建一个codeandbox或提供一个最小化的GitHub仓库。7可能未跟进的issue被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-forked-8kwkh?file=/demo.js
打开后把browser区域（也是就显示区域），拉大一些，越大越明显

**Comment by ineedacatmiao** [comment]
我也遇到问了   help  me

**Comment by NOBOUNDer** [comment]
我也遇到这个问题了，只要设置了scroll.x  在左侧menu伸展收缩和窗口resize的时候，表格就特别卡顿。我目前版本是4.10.2

**Comment by edc-hui** [comment]
遇到表格卡顿问题的，安装virtualizedtableforantd4这个库，实现虚拟列表。亲测卡顿问题会解决

**Comment by qykingle** [comment]
啥时候能解决这个问题？

**Comment by yfs-2000** [comment]
我这边也是 非常卡  目前好像没有什么解决方案

**Comment by wansuiasdn** [comment]
貌似更新后出现的问题？以前使用老版本antd 貌似没遇到过这个情况，在为表格设置scroll 后 sider 改变menu 折叠，基本就是ppt了，且可视界面越大，越卡

**Comment by XuedongZhou** [comment]
同样的问题，table 使用 scroll  属性后，折叠展开侧边栏，很卡顿。

**Comment by LuDongWei** [comment]
"antd": "4.11.2" 这个版本，在大窗口 table 使用  
```
                   scroll={{
                        x: '100%',
                        scrollToFirstRowOnChange: true
                    }}
                    sticky={{
                        getContainer: () => document.getElementById('root')
                    }}
```
侧边栏折叠很卡，延迟4s左右

**Comment by xykjlcx** [comment]
同样遇到了这个问题

"antd": "^4.14.0",
 "@ant-design/pro-table": "^2.30.8",

观察了一下，在开启了“scroll={x:值}”之后，点击menu的收起，若屏幕宽度计算为不需要横向滑动，收缩前是滑动的，就会非常卡

当把浏览器窗口宽度放的小一点，menu收起后，table计算还是不够显示的，仍需要横向滑动，就不会卡

**Comment by Zixiaobowen** [comment]
我也遇到了同样的问题

**Comment by LittleEven** [comment]
升级组件库后遇到了这个问题，这个有解决方案了吗？

**Comment by michaelpeterlee** [comment]
We encounter a performance issue with 4.10.x; is likely another artefact from the same issue:

`Table` + `Sider` toggle is choppy.

`Table` re-renders many times during the toggle animation. You may like to consider throttling `Table` rendering as a possible solution for this UseCase.

**Comment by lbjlsy** [comment]
same problem

**Comment by c-ujung** [comment]
antdpro v5一样遇到 了这个问题，

`"antd": "^4.14.0",
"@ant-design/pro-layout": "^6.15.3",`

表格数据10行，只要设置了`scroll={{ x: '100%', scrollToFirstRowOnChange: true }}`，侧边导航菜单就很卡。
希望解决一下吧，谢谢

**Comment by wuxushun** [comment]
我也遇到了，table疯狂重新render上千次

**Comment by wuxushun** [comment]
什么时候才能解决，这个影响很大

**Comment by afc163** [comment]
PR is welcome~

**Comment by Azir1** [comment]
同问

**Comment by zhengpingwu** [comment]
同问，遇到+1

**Comment by liqingitt** [comment]
+ 1

**Comment by zechau** [comment]
any idea?

**Comment by nkHub** [comment]
我的也是，一直在重新计算样式，，渲染特别慢。。10s...

**Comment by shenzhongkang** [comment]
same problem, my scroll.x is "max-content", when i toggle aside menu collapsed, my page rendered with low performance.

**Comment by nkHub** [comment]
> 我的也是，设置scroll.x=某个值，一直在重新计算样式，，渲染特别慢。。10s。。 scroll.x改成max-content样式却会乱，加载特别快。。

嗯，好像是存在许多溢出的时候会很卡。

**Comment by qixm-burnish** [comment]
4.18中，设置`scroll.x`为`max-content`，数据列多了以后会出现严重卡顿。不过把每列设置固定宽度，`scroll.x`设置固定宽度后，卡顿效果明显改善
