### ISSUE TITLE
How to return to the previous page number after the pagination page is refreshed? Is there a best practice for this?/分页页面刷新后如何回到之前的页码，这个有最佳实践了么？

### ISSUE THREAD

**Issue by ccloveak** [ant-design/ant-design#27780]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/list/basic-list](https://preview.pro.ant.design/list/basic-list)

### Steps to reproduce
Clicking 2 3 4 in paging  /分页按顺序点击234之后

### What is expected?
Click the browser  back button to return to the third page and the second page
/浏览器点击后退 回到第三页 第二页

### What is actually happening?
retun the other page

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | mac |
| Browser | chrome |

---
Project only  used  react-router & react hooks（有不使用redux的解决办法么，跟https://github.com/ant-design/ant-design/issues/780 提的是同一个问题）

**Comment by hengkx** [comment]
keep alive可以实现不

**Comment by yoyo837** [comment]
可以和表格个性化数据一起存储到后台

**Comment by ccloveak** [comment]
我大概说下我的解决方法在pro-table 2.6.3里有点问题，不过在最新的2.11.4里已经能很理想的实现里（11.26）。 把每次在页面上的操作的 “page ”跟 “搜索关键字” 用history.push到url的？后面，然后每次数据的获取是通过url获取的 （这样是为了防止一次性大量数据对性能的影响）刷新后直接从url里获取数据 当前page  当前的搜索关键字
