### ISSUE TITLE
在 Menu 中动态新增 SubMenu 并默认展开，往新增的 SubMenu 中添加 Menu.Item 后，视图不更新。

### ISSUE THREAD

**Issue by wyh-code** [ant-design/ant-design#27789]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-clarke-1yioy?file=/src/App.js)

### Steps to reproduce
1、新增 SubMenu。
2、往新增加的 SubMenu 中添加 Menu.Item

### What is expected?
视图中显示新增的  Menu.Item

### What is actually happening?
数据已经更新，视图没有更新

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.12.0 |
| System | macOs 10.15.7  |
| Browser | chrome 81.0.4044.138 |

---
关闭新增的  SubMenu，再展开后，会显示新添加的  Menu.Item

**Comment by Zhipeng-Chang** [comment]
Hi! I noticed this issue is still labelled as "help wanted", do you still need help for this one?

**Comment by wyh-code** [comment]
> Hi! I noticed this issue is still labelled as "help wanted", do you still need help for this one?

yes

**Comment by Dingo203** [comment]
I also find this problem, is this issue fixed now?

**Comment by yoyo837** [comment]
rc-menu 重写中，目前alpha

**Comment by afc163** [comment]
Fixed in `antd@4.16.1`: https://codesandbox.io/s/silly-gareth-63mvu?file=/src/App.js
