### ISSUE TITLE
v3升级至v4后，内嵌菜单收缩，submenu鼠标悬停不显示子项，没有子项弹出

### ISSUE THREAD

**Issue by wanghx123** [ant-design/ant-design#27782]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/#header](https://ant.design/components/menu-cn/#header)

### Steps to reproduce
1.将v3升级至v4，使用的方法是antd官方给的兼容方法
2.使用的是内嵌菜单
3.点击收缩，鼠标悬停至父菜单submenu上
4.发现没有子组件弹出，但是有阴影弹出的效果，v3版本正常

### What is expected?
v4内嵌菜单，鼠标悬停至父菜单submenu上有子组件弹出

### What is actually happening?
v4内嵌菜单，鼠标悬停至父菜单submenu上没有子组件弹出

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.1 |
| System | windows10 |
| Browser | Chrome谷歌  火狐 |

**Comment by yoyo837** [comment]
更新到最新版试一试

**Comment by chenzhizhen** [comment]
我也碰到了相同的问题，而且在页面使用submenu也是只有阴影，menu item不显示

**Comment by wanghx123** [comment]
> 我也碰到了相同的问题，而且在页面单独使用submenu也是只有阴影，menu item不显示

有解决方法么？

**Comment by wanghx123** [comment]
> 更新到最新版试一试

最开始的时候是更新到4X最新版本的，但是出现了这个问题之后  降到了4.0.0  还是有这个问题

**Comment by chenzhizhen** [comment]
在code sandbox无法重现，create-react-app引入antd也是正常的，还不清楚跟什么相关
```
<Menu mode="horizontal">
        <Menu.SubMenu title={'user'}>
          <Menu.Item key="logout">
            logout
          </Menu.Item>
        </Menu.SubMenu>
      </Menu>
```
<img width="192" alt="Screen Shot 2020-12-01 at 5 42 27 PM" src="https://user-images.githubusercontent.com/20811053/100726838-6be8df00-3400-11eb-8797-e7f298725682.png">

**Comment by chenzhizhen** [comment]
> > 我也碰到了相同的问题，而且在页面单独使用submenu也是只有阴影，menu item不显示
> 
> 有解决方法么？

我这边的问题好像是因为样式不全, 把style从`true`改成`css`就好了
```
"extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
  ],
```

**Comment by chenzhizhen** [comment]
@wanghx123 我这边的问题是，项目是蛮久之前的老项目，用的还是roadhog，我估计是less版本比较低，部分语法不识别，使用antd.less有问题，直接import antd.css可以正常弹出子项。不知道是否对你的问题有所参考。

**Comment by afc163** [comment]
升级 less 版本到 3.x 以上。
