### ISSUE TITLE
The resetFields Func clear the TreeSelect component with some error(使用useForm中的resetFields方法清除树选择组件报错)

### ISSUE THREAD

**Issue by ZaccheoMoon** [ant-design/ant-design#27784]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-b39ss?file=/src/pages/home/index.tsx)

### Steps to reproduce
1.The dependency package is installed using yarn.（使用yarn安装相关依赖包）
2.Click on the Treeselect and select some values.（点击modal中的树形选择组件并随意选中某些值）
3.Click the reset button.（点击重置按钮）

### What is expected?
no error

### What is actually happening?
Reported some errors such as'Uncaught TypeError: Cannot read property 'removeEventListener' of null ','Uncaught TypeError: Cannot read property 'removeEventListener' of null'

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | 17.0.1 |
| System | macOS 10.15.7 |
| Browser | chrome86.0.4240.111 And FireFox82.0.3 |

**Comment by ZaccheoMoon** [comment]
@afc163 help!bro!

**Comment by ZaccheoMoon** [comment]
> Hello @ZaccheoMoon. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @ZaccheoMoon, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

have already uploaded

**Comment by ZaccheoMoon** [comment]
Have already uploaded @xrkffgg @afc163

**Comment by kerm1it** [comment]
This example https://codesandbox.io/s/antd-reproduction-template-forked-b39ss?file=/src/pages/home/index.tsx doesn't work.

**Comment by ZaccheoMoon** [comment]
I don't konw what happended on CodeSandbox.If example doesn't work on CodeSandbox, you can download this example to run locally on Github.
Link: [https://github.com/ZaccheoMoon/antd-demo](https://github.com/ZaccheoMoon/antd-demo)
Tks~

**Comment by afc163** [comment]
Please reinstall after remove `node_modules` and `yarn.lock`, then try again.
