### ISSUE TITLE
ant-table and  mobx state tree

### ISSUE THREAD

**Issue by zeden** [ant-design/ant-design#27791]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://4x5di.codesandbox.io/)

### Steps to reproduce
just check a wallet

### What is expected?
to rerender the table

### What is actually happening?
not rerender

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | react |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
Your `<Checkbox />` is missing `onClick` or `onChange` callback.
