### ISSUE TITLE
[RangePicker] Missing border style when hover range starts from first day of a month

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27798]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker](https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker)

### Steps to reproduce
- Enter the link and find the date type RangePicker
- Select a start date
- Select last day of the month as end date
- Click the end date in input, then hover over next month

### What is expected?
The first cell of the hover range has left border style
![4C39F6A7-466C-4512-A730-547E953ED162](https://user-images.githubusercontent.com/50612752/99239495-19bb9180-2836-11eb-9f00-fc4007727fdb.png)

### What is actually happening?
The first cell of the hover range miss left border style
![282C9D94-99AD-4F9F-9232-D8B8936A6F84](https://user-images.githubusercontent.com/50612752/99239464-0f999300-2836-11eb-9c6b-826651c9c928.png)

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by xrkffgg** [comment]
https://ant.design/components/date-picker/

I see it's normal.

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/99250500-b6862b00-2846-11eb-8f45-16e3782c929b.png)

**Comment by AlanCutFlim** [comment]
@xrkffgg Seems like your start day and end date are set the same day (end date is not the last day of a month), please follow the steps bellow

- Select `2020-11-01` as start day, select `2020-11-30` as end date
- Then choose end date and hover next month
- Or please set the same date in the picture i provide

**Comment by xrkffgg** [comment]
I see.

**Comment by xrkffgg** [comment]
同样起始时间选择1号，同样出现样式问题。

**Comment by AlanCutFlim** [comment]
@xrkffgg  是的，在 DateRangePicker 的选择年份面板中也有同样的问题

**Comment by xrkffgg** [comment]
得需要知道 Panel 里的第一个和最后一个才行，光加样式的话，会出现其他的 bug 。样式区分不开了。

我又想了一下，也许这并不是 bug ，这样表示范围是从上一个 Panel 过来的。

@zombieJ 来瞅瞅

**Comment by xrkffgg** [comment]
### 图 1
![image](https://user-images.githubusercontent.com/29775873/99344807-e0356580-28cb-11eb-9cd9-80fdf3ea67d2.png)

### 图 2
![image](https://user-images.githubusercontent.com/29775873/99344824-e9263700-28cb-11eb-9ac3-8b6f4ab0910b.png)

---

这 2 个地方的 样式一模一样，如果给图 2 加上左边框，图 1 也会加上。我是没办法了，除非每个月的 1 号和最后 1 号有单独的 className。

@zombieJ 😭😭

**Comment by xrkffgg** [comment]
@kerm1it help

**Comment by kerm1it** [comment]
https://github.com/ant-design/ant-design/blob/652374ff4cd759d76a0aa323f4c2e1730224842a/components%2Fdate-picker%2Fstyle%2Fpanel.less#L322

看看这里，虽然类名一样，但是加了 first-child 之类的伪类选择器。

**Comment by xrkffgg** [comment]
这个我试了，不行

**Comment by xrkffgg** [comment]
我再试试

**Comment by kerm1it** [comment]
估计就是这里的选择器逻辑问题，有些边界效果没想到。

**Comment by AlanCutFlim** [comment]
@xrkffgg  使用紧邻选择器 `+` 似乎能解决 hover next month 时的问题

```css
td.ant-picker-cell.ant-picker-cell-range-end.ant-picker-cell-range-end-near-hover.ant-picker-cell-range-hover.ant-picker-cell-range-hover-edge-start.ant-picker-cell-selected + td::after {
  left: 6px;
  border-left: 1px dashed #7ec1ff;
  border-top-left-radius: 2px;
  border-bottom-left-radius: 2px;
}
```

![image](https://user-images.githubusercontent.com/50612752/99355507-5f826380-28e3-11eb-9741-e08e224bce5b.png)

![image](https://user-images.githubusercontent.com/50612752/99355515-65784480-28e3-11eb-864e-7cceacef0c8e.png)

**Comment by xrkffgg** [comment]
@AlanCutFlim 但还是会出现 图 1 的问题。

**Comment by AlanCutFlim** [comment]
@xrkffgg 我这里没有出现问题，你可以看看。

[https://codesandbox.io/s/fanweixuanzeqi-antd484-forked-7i3fe?file=/index.js](url)

![image](https://user-images.githubusercontent.com/50612752/99356493-3793ff80-28e5-11eb-83c1-9e6c4f9f614b.png)

**Comment by xrkffgg** [comment]
嗯，应该还需要再完善下，当都选择 2020-11-30 时，还会出现这个问题。

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/99357642-3663d200-28e7-11eb-9f01-7530819fcd0b.png)

**Comment by xrkffgg** [comment]
你的思路不过，我光想着后面那个，你根据前面 selected 来筛选，这下基本解决了。

**Comment by xrkffgg** [comment]
😂 前面的不好加

**Comment by AlanCutFlim** [comment]
😂 我正想问你前面的应该怎么处理呢，CSS 没办法选择前一个元素。

**Comment by xrkffgg** [comment]
用了个黑魔法，稍微掩盖了一点，但实际上还有点欠缺的。

![image](https://user-images.githubusercontent.com/29775873/99366762-07a02880-28f4-11eb-9a84-ee829529e661.png)

**Comment by xrkffgg** [comment]
还是筛选 selected 的，只不过强制让它给前一个加样式。

**Comment by xrkffgg** [comment]
正常操作，不仔细看的话，看不出太大的样式问题

**Comment by AlanCutFlim** [comment]
@xrkffgg 其他情况感觉已经可以了，但是如果只 hover 最后一天的话，很容易感觉出一些问题(右侧留白有点多)，好像边框的圆角也没有生效。可能还是再加个 className 好解决点。

start date: `2020-12-01`, end date: `2020-12-10`, hover date: `2020-11-30`
![image](https://user-images.githubusercontent.com/50612752/99369959-0a048180-28f8-11eb-801f-ae70af375c27.png)

start date: `2020-12-02`, end date: `2020-12-10`, hover date: `2020-11-30`
![image](https://user-images.githubusercontent.com/50612752/99369984-1557ad00-28f8-11eb-9a02-63695095dd96.png)

**Comment by xrkffgg** [comment]
现在的 className 我只能想到这个办法了😂😂

**Comment by xrkffgg** [comment]
不放大看，不盯着看，其实还好

**Comment by xrkffgg** [comment]
真大佬出马吧

**Comment by kerm1it** [comment]
试试这个好使么？
https://codesandbox.io/s/antd-reproduction-template-forked-vx7z2?file=/index.css

**Comment by xrkffgg** [comment]
> 试试这个好使么？
> https://codesandbox.io/s/antd-reproduction-template-forked-vx7z2?file=/index.css

都选 2020-11-30 时候挂了

**Comment by xrkffgg** [comment]
其实后面选的还好，主要是起始。起始时间选个 2020-10-01 ，然后点起始，选9月

**Comment by xrkffgg** [comment]
最简单的，我感觉给每个月的起始时间和结束时间，加个 className

**Comment by kerm1it** [comment]
@xrkffgg  再试试

https://codesandbox.io/s/antd-reproduction-template-forked-vx7z2?file=/index.css

**Comment by xrkffgg** [comment]
测试点：
1. start: `2020-09-01` end: `2020-09-30` 鼠标点击 end，鼠标悬浮 10-1 10-8，观察样式；
2. start: `2020-09-01` end: `2020-09-30` 鼠标点击 start，点击上一个月份，鼠标悬浮 8-31 8-24，观察样式；
3. start: `2020-09-30` end: `2020-09-30` 鼠标点击 end，鼠标悬浮 10-1 10-8，观察样式；
4. start: `2020-09-01` end: `2020-09-01` 鼠标点击 start，点击上一个月份，鼠标悬浮 8-31 8-24，观察样式；
5. start: `2020-09-09` end: `2020-09-10` 鼠标点击 end，鼠标悬浮 9-11 之后，观察样式；
6. start: `2020-09-09` end: `2020-09-10` 鼠标点击 start，鼠标悬浮 9-8 之前，观察样式。

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/27828

我的方案 第2 和第4，虚框会多了 6px，其他符合预期。

**Comment by yoyo837** [comment]
> 最简单的，我感觉给每个月的起始时间和结束时间，加个 className

加了class也还是不能完美解决？

**Comment by xrkffgg** [comment]
> > 最简单的，我感觉给每个月的起始时间和结束时间，加个 className
> 
> 加了class也还是不能完美解决？

加了新的 className，就可以以这个作为判断来精准定位并完善样式。

**Comment by yoyo837** [comment]
那加呗，即使没有具体是css，dom 的 class属性也是有语义的

**Comment by yoyo837** [comment]
这又来个类似的 #27855
