### ISSUE TITLE
Table可伸缩列问题：只要有一列加了省略ellipsis: true,  拖动大小时就会超出表格宽度

### ISSUE THREAD

**Issue by tanqiyuan** [ant-design/ant-design#27793]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keshensuolie-antd483-forked-4nzeg?fontsize=14&hidenavigation=1&theme=dark&file=/index.js:847-855)

### Steps to reproduce
随便拖动列，会超出表格带下和窗口

### What is expected?
拖动列不会影响表格的宽度

### What is actually happening?
实际超出的表格宽度，甚至窗口

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | laster |
| System | Windows10 |
| Browser | chrome.84 |

---
Table的列只要有一列加了省略ellipsis: true,  拖动大小时就会超出表格宽度， 不加就很正常

**Comment by AmberAtSE** [comment]
我也是有相同的问题，求解

**Comment by Moderation-T** [comment]
求解+1

**Comment by DevanXU** [comment]
+1

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26413#issuecomment-802563939
