### ISSUE TITLE
Notification Component Positioning 

### ISSUE THREAD

**Issue by fr7m7moud** [ant-design/ant-design#27808]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
hello,
In the NotificationOptions of  the Notification Component it's allowed only to specify the bottom and the top only,
but the thing is I want to specify the left and right also, because I want to show the notification box on each component separately 
so if I have 4 component each on of them will have it's own notification box only appear on top of it not on the entire view port

### What does the proposed API look like?
export interface NotificationOptions {
  message: React.ReactNode;
  description?: React.ReactNode;
  className?: string;
  top?: number;
  bottom?: number;
  left?:number;
  right?:number;
  duration?: number | null;
  onClose?: (e: any) => void;
  placement?: placementType;
}

**Comment by xrkffgg** [comment]
Try https://ant.design/components/notification/#components-notification-demo-custom-style
