### ISSUE TITLE
RangePicker crashes with multiple formats + showTime

### ISSUE THREAD

**Issue by patrickshipe** [ant-design/ant-design#27812]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-15j6i?file=/index.js)

### Steps to reproduce
1. Select a date in the range picker.
2. You will see error "format.match is not a function"

### What is expected?
RangePicker functions as normal. Uses first element of format array for formatting and others for parsing.

### What is actually happening?
When prop "format" has multiple strings in the array, RangePicker crashes upon date selection.

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.1 |
| System | macOS Catalina |
| Browser | Chrome 86 |

**Comment by afc163** [comment]
There is a weird example: https://ant.design/components/date-picker/#components-date-picker-demo-format , that pass `dateFormatList` to DatePicker instead of RangePicker.

@zombieJ come and check this issue.
