### ISSUE TITLE
DatePicker with dayjs does not follow ConfigProvider locale

### ISSUE THREAD

**Issue by JesperWe** [ant-design/ant-design#27815]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/JesperWe/antd4-generate-picker](https://github.com/JesperWe/antd4-generate-picker)

### Steps to reproduce
Run the JavaScript demo (tree/master/antd-demo) in the linked repo. 

### What is expected?
All placeholders and buttons are translated, day names are Swedish and week starts on Monday.

### What is actually happening?
Placeholders and buttons are correctly translated, but day names are English and week starts on Sunday, which is wrong for the configured `sv_SE` locale.

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.12 |
| System | MacOS |
| Browser | Firefox 82.0.3  |

**Comment by afc163** [comment]
You need `dayjs.locale('sv')`.

See https://github.com/ant-design/ant-design/issues/24596#issuecomment-636403266 and https://github.com/ant-design/ant-design/issues/27276#issuecomment-715889654

**Comment by JesperWe** [comment]
That does not change anything.
Still doesn't work.
See updated reproduction repo.

**Comment by afc163** [comment]
Please update to antd lastest version and reinstall node_modules after remove yarn.lock.

```
- "antd": "4.0.0-beta.1",
+ "antd": "^4.0.0",
```

**Comment by afc163** [comment]
Also follow https://ant.design/docs/react/replace-moment to replace momemt to dayjs, otherwise in your case you just use moment without sv_SE locale.

**Comment by JesperWe** [comment]
I am following that, my repo is a clone of https://github.com/xiaohuoni/antd4-generate-picker which is linked in that page.
(This is why it was using an old AntD version)

I have upgraded Ant, this does not fix the problem.

**Comment by JesperWe** [comment]
I have identified the problem.

If I change the Ant imports in https://github.com/xiaohuoni/antd4-generate-picker from to `antd/es/...` it works.

You should update the Javascript demo in https://github.com/xiaohuoni/antd4-generate-picker to this (or remove the link to it from https://ant.design/docs/react/replace-moment)
