### ISSUE TITLE
The Select Component shows the clearIcon with null defaultValue

### ISSUE THREAD

**Issue by MicheleJohn** [ant-design/ant-design#27811]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7ux1x?file=/index.js)

### Steps to reproduce
1) Declare a Select Component
2) Add the allowClear and defaultValue props
3) Set defaultValue prop to "null"
4) Now the clearIcon is visible even if there's nothing selected

### What is expected?
When i set the defaultValue equals to null, i want that the clearIcon is not displayed

### What is actually happening?
When i set the defaultValue equals to null, the clearIcon is visible even if nothing it's selected

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | React 16.13.1 |
| System | Windows 10 Pro 20H2 |
| Browser | Chrome 86.0.4240.193 |

---
The question is: why do you want to set the deafultValue prop to "null"? Well, there could be a "ternary if" in the defaultValue statement that decides if there is or not a default value to be selected.
For example: "defaultValue={ user.fiscalCode !== paziente.fiscalCode ? paziente.fiscalCode : null }".

**Comment by afc163** [comment]
It is intented, `null` is considered as valid value of Select.

https://github.com/ant-design/ant-design/issues/2367#issuecomment-232538295
