### ISSUE TITLE
space 水平时，增加wrap属性支持换行同事size可以设为数组

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#27823]
```
wrap = true
size = [8, 8]
```

**Comment by hengkx** [comment]
@afc163 @zombieJ 怎么看

**Comment by afc163** [comment]
解决什么问题？

**Comment by hengkx** [comment]
现在 不能 换行

**Comment by afc163** [comment]
看上去和 https://github.com/ant-design/ant-design/pull/26695 的需求有点类似。

**Comment by hengkx** [comment]
有共同的 还是有些 差别 ，应该和row的 比较相近

**Comment by afc163** [comment]
wrap 可以加，甚至应该默认是 true，Space 相当于有间隙的 inline-block。

**Comment by afc163** [comment]
`size=[8, 8]` 这种不好搞，更像是 Grid 来 cover 的场景了。

**Comment by hengkx** [comment]
> `size=[8, 8]` 这种不好搞，更像是 Grid 来 cover 的场景了。

如果不是数组的话 垂直的间距就必须和水平间距一样，虽然我觉得正常使用他们就应该是一样的

**Comment by afc163** [comment]
垂直间距没法搞的，对于 Space 来说，你不知道哪个 item 是第二行的。也不能给所有 item 都加上 marginTop。

**Comment by hengkx** [comment]
蛋疼 ，垂直 没有间距的话 出来的 样式 又很丑

**Comment by hengkx** [comment]
不对，。 是不是 可以给每个Item加marginBottom 然后给 Space 加负值抵消掉

**Comment by afc163** [comment]
也有个办法是给所有 item 上下各加上加上一半的间距，`size={[8, 8]}` 时，大家都加上 `margin: '4px 0'`

**Comment by hengkx** [comment]
> 也有个办法是给所有 item 上下各加上加上一半的间距，`size={[8, 8]}` 时，大家都加上 `marginTop: 4, marginBottom: 4`

这样还是有个问题 我只有一行 还加了 margin 和之前的逻辑 冲突了

**Comment by hengkx** [comment]
space上面加marginTop -4可以抵消掉吗

**Comment by zombieJ** [comment]
可以的：https://codesandbox.io/s/jibenyongfa-antd484-forked-4y98c?file=/index.js:537-560
