### ISSUE TITLE
babel-plugin-antd  按需加载与 webpack 的require.ensure 代码分割问题

### ISSUE THREAD

**Issue by Superman-wc** [ant-design/ant-design#2782]
#### 本地环境

"antd": "^1.8.0",
"atool-build": "^0.7.1",
"babel-plugin-antd": "^0.4.0",
"babel-plugin-transform-runtime": "^6.8.0",
"babel-runtime": "^6.6.1",

操作系统：mac os 10.10

Node 5.10.0
npm 3.8.0

#### 你做了什么？

使用 antd-init 创建和项目

####entries/index.js
import {Button} from 'antd'; //主入口文件中包含引用Button， 

####routes/index.js
//动态加载路由组件
<IndexRoute getComponents={(location, callback)=> {
                    require.ensure([], function (require) {
                        callback(null, require('../containers/Home/Home'));
                    }, 'javascript/Home');
                }}/>

####Home.jsx
import React, {Component, PropTypes} from 'react';
import {Button} from 'antd';  //组件代码里也引用Button

####编译结果
javascript/Home.js    //生成的代码分割文件中 包含了 Button的代码

####理想结果
Button 代码只应该在入口文件的编译结果中， 
require.ensure 生成的分割文件不应该包含，
多个动态路由加载的组件中可能都会用到Button 这样常用的组件

###改写import的写法

####entries/index.js
import Button from 'antd/lib/button';   // 入口里这样写

####Home.jsx
import Button from 'antd/lib/button';   // 动态加载的组件里也这样写

###编译结果
javascript/Home.js //生成的代码分割文件中不包含 button的代码了

##结论
babel-plugin-antd 的按需加载有问题啊，

**Comment by sorrycc** [comment]
应该是 webpack 的问题，require.ensure 的拆分没考虑 babel 插件可能对文件的 import 进行修改，找时间用 webpack2 + system.import 试下。

**Comment by nalantianyi** [comment]
@sorrycc 我尝试使用webpack2 + system.import ，但是并没有解决这个问题，实际上，只是css有问题，js是正常的<br/>参见这个http://stackoverflow.com/questions/42456917/css-code-splitting-with-webpack-2-and-react-router<br/>目前好像没有什么办法<br/>但是你的roadhog中是怎么处理的呢，看了你的源码是基于webpack1，源码中我并没看到相关的处理，能否分享下你是怎么处理的，谢谢
