### ISSUE TITLE
Menu.SubMenu SubMenu.js:452 Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by fkocovski** [ant-design/ant-design#27837]
![2020-11-17 11_55_44-Window](https://user-images.githubusercontent.com/9000611/99381799-da3f8480-28cb-11eb-92a9-96944e57487d.png)
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu/#API](https://ant.design/components/menu/#API)

### Steps to reproduce
# note
I couldn't manage to reproduce it in sandbox but in my application since updating to 4.8.3 and 4.8.4 it happens always. Might need some further help to isolate the issue

**this problem doesn't happen with 4.8.2**

# steps
- Have a Menu.SubMenu inside a Menu component
- Hover over the submenu
- open the dev console
- The stacktrace shows the illegal invocation

### What is expected?
That the submenu component works as before when hovering

### What is actually happening?
Stacktrace and white screen, the submenus in the whole application are not hoverable anymore

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser |  86.0.4240.198 |

**Comment by fkocovski** [comment]
Hey @afc163 thanks for labeling the issue. As mentioned I couldn't reproduce it in sandbox and would love some help to isolate the issue. Any chance for some support? Thank you

**Comment by afc163** [comment]
We don't have enough information to resolve it without reproduce.

**Comment by afc163** [comment]
It may related to 

https://github.com/react-component/menu/blob/115a21cbd50a07441e89dafe05021415b7089b10/src/SubMenu.tsx#L186

and

https://github.com/react-component/menu/blob/115a21cbd50a07441e89dafe05021415b7089b10/src/SubMenu.tsx#L223

**Comment by fkocovski** [comment]
Ok I'll try to reproduce it somehow, thank you.

**Comment by Aspedm** [comment]
I have same error.

**Comment by Aspedm** [comment]
I think this error not fully antd problem. This error most likely associated with webpack or with CRA.

**Comment by mcabrams** [comment]
Seeing this as well - popped up in my cypress tests

**Comment by itcat99** [comment]
same

**Comment by 942778086** [comment]
need add call(window) to cancel methods of custom object

**Comment by guogeer** [comment]
I catch the error only in antd@4.8.4, and I try reback version to 4.8.2, the error is not existed.

**Comment by yoyo837** [comment]
@guogeer Could you provide a online reproduction?

**Comment by guogeer** [comment]
@yoyo837 I try

**Comment by guogeer** [comment]
@yoyo837 i try forked my old project, then 'npm install'. i cannot find the bug in new project with same code.
the bug only exist in old project. i record sreen and upload baidu pan, expect to help you.
https://pan.baidu.com/s/1aYHHZkFHrAePHFiy8eu_vw。提取码：w9p4

**Comment by yoyo837** [comment]
Could you remove `node_modules`, `package-lock.json` or `yarn.lock` then try again?

**Comment by fkocovski** [comment]
> Could you remove `node_modules`, `package-lock.json` or `yarn.lock` then try again?

This appears to have fixed the issue on my side. I already had tried removing the `node_modules` but apparently it was not enough, `package-lock.json` had to be removed too. Our application gets built on CI/CD and it makes always a fresh `npm install` so I still can't really understand how this helps. Care to shed some light on this @yoyo837 please?

**Comment by pmh555** [comment]
Looks like outdated dependencies in rc-menu that's causing this (`rc-util: ^5.0.1`). If you're using yarn, adding `resolutions` to package.json is a workaround for now.

```
"resolutions": {
  "rc-util": "^5.5.0"
}
```

**Comment by hankaibo** [comment]
I also encountered the same problem when I upgraded to 4.8.4.
It solves my problem, thank you @pmh555 ,😁

**Comment by yoyo837** [comment]
@pmh555 @hankaibo If you follow https://github.com/ant-design/ant-design/issues/27837#issuecomment-729541536, no need `resolution`.

**Comment by appleshell** [comment]
same problem, @yoyo837 's advice works.

**Comment by wygkzqa** [comment]
same issue

**Comment by NiuNiuer** [comment]
same problem

**Comment by afc163** [comment]
See @yoyo837 's comment: https://github.com/ant-design/ant-design/issues/27837#issuecomment-729541536

**Comment by ZhaojiaLii** [comment]
It doesn't work on my side...I'm trying to figure out why but I've tried updating resolution with rc-utils: 5.5.0, delete node_modules and yarn.lock and then rebuild the project, nothing changed....

**Comment by ZhaojiaLii** [comment]
And I've revert the Antd version from 4.8.5 to 4.8.2, the error was still there

**Comment by afc163** [comment]
@ZhaojiaLii It should be fixed in https://github.com/react-component/menu/releases/tag/v8.10.1 right now. Please try upgrade node_modules and yarn.lock and package-lock.json again.

**Comment by ZhaojiaLii** [comment]
> @ZhaojiaLii It should be fixed in https://github.com/react-component/menu/releases/tag/v8.10.1 right now. Please try upgrade node_modules and yarn.lock and package-lock.json again.

resolution the rc-menu vertion to v8.10.1 right?

**Comment by ZhaojiaLii** [comment]
the yarn install returns : Couldn't find any versions for "rc-menu" that matches "8.10.1"

**Comment by afc163** [comment]
It is existed: https://www.npmjs.com/package/rc-menu

**Comment by ZhaojiaLii** [comment]
> It is existed: https://www.npmjs.com/package/rc-menu

Thanks it works now!
🐂🍺

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/util/commit/f272d40483f64ec44826d36b433dae1836c491ab
