### ISSUE TITLE
Slider component causes "Cannot read property 'forcePopupAlign' of null" error after unmounting

### ISSUE THREAD

**Issue by ngerasimoff** [ant-design/ant-design#27834]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-5x9ekr?file=index.js](https://stackblitz.com/edit/react-5x9ekr?file=index.js)

### Steps to reproduce
Switching between routes causes an error in the console. When  my slider component is mounted... everything goes well, but if I switch to another route I get this error from the ant's SliderTooltip component. Error occurs when tooltipVisible prop is active.

### What is expected?
no error in the console

### What is actually happening?
Cannot read property 'forcePopupAlign' of null

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.1 |
| System | Win 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
> https://g8kq4n--run.stackblitz.io

It is empty.

**Comment by ngerasimoff** [comment]
> > https://g8kq4n--run.stackblitz.io
> 
> It is empty.

My bad.I fixed the link
