### ISSUE TITLE
[Table] Extra border shows up near scrollbar when table is set "bordered" and "scroll" at the same time

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27835]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudingbiaotou-antd483-forked-i8vnc)

### Steps to reproduce
- Enter the link and check the area near scollbar
- If you want a clearer view, please zoom in a little bit

### What is expected?
There is only one border
![image](https://user-images.githubusercontent.com/50612752/99377959-daf30d80-2901-11eb-9983-9f01efa9b4c2.png)

### What is actually happening?
There is two border near scroll bar
![border111](https://user-images.githubusercontent.com/50612752/99366754-053dce80-28f4-11eb-8eb2-bb1ea7d843ae.png)

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
It is hard to resolve because we can't know wherther user enable scrollbar-display in MacOS.

**Comment by AlanCutFlim** [comment]
Sorry for not digging into this problem, never notice there is such a setting in MacOs. It did make a difference after i switch the setting.

I'm also curious why codesandbox's scrollbar never change no matter how i change the scrollbar-display setting, and they look almost same in both MacOs and Windows.

**Comment by afc163** [comment]
It may rewrite the scrollbar styles.
