### ISSUE TITLE
Typescript Definition file missing things

### ISSUE THREAD

**Issue by bouniflax** [ant-design/ant-design#2783]
Hello,

There are missing attribute for TableProps coming from the rc-table.

For example : 
```
defaultExpandAllRows?: boolean;
rowClassName?: Function;
expandedRowClassName?: Function;
//...and others from rc-table
```

Maybe your interface can extend the rc-table one.

Also, when compiling using typescript 2.0.0, there is an issue with `React.FormEventHandler` type.
It should be written as `React.FormEventHandler<any>`

For example : 

```
// Checkbox
interface CheckboxProps {
  /** 指定当前是否选中*/
  checked?:boolean,
  /** 初始是否选中*/
  defaultChecked?:boolean,
  /** 变化时回调函数*/
  onChange?:React.FormEventHandler<any>,

  style?:React.CSSProperties
}
```

Thank you your lib is awesome, still getting into it but great !

**Comment by afc163** [comment]
#1846 No finished yet
