### ISSUE TITLE
Form Fields Duplicated

### ISSUE THREAD

**Issue by cedric-matheus** [ant-design/ant-design#27842]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-form-duplicated-fields-7tx7s)

### Steps to reproduce
1 - Input a text on input.
2 - See duplicated fields on console.log

### What is expected?
One input field.

### What is actually happening?
Two input field.

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.0 |
| System | Ubuntu 18.04 |
| Browser | All |

---
It's very simple...

**Comment by cedric-matheus** [comment]
[UPDATE] If you remove react strict mode, it will work correctly again.

**Comment by zombieJ** [comment]
https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode

Hmmm... We should detect this since field register on constructer which makes 2 twice.

**Comment by zombieJ** [comment]
Seems not way to clean up for constructor since node not call any other lifecycle in Strict mode.

ref https://github.com/ant-design/ant-design/issues/27311
