### ISSUE TITLE
Col with object props doesn't break at 480px (screen-xs)

### ISSUE THREAD

**Issue by LilyMGoh** [ant-design/ant-design#27843]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-43e4r?file=/index.js)

### Steps to reproduce
Open device toolbar from Chrome Devtool (https://43e4r.csb.app/) and inspect the column, you'll notice that the grid is not responsive at 480px (xs) breakpoint.

### What is expected?
It should break at the breakpoints defines in the theme: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L279

### What is actually happening?
It does not break at 480px

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | Mac OS |
| Browser | Google Chrome |

---
I think the culprit might be from this line of code: https://github.com/ant-design/ant-design/blob/6e0981d1df77e19ef8d697c72384b785c1d33204/components/_util/responsiveObserve.ts#L9

**Comment by afc163** [comment]
That is right, `@screen-xs` is unused in Grid responsive styles: https://github.com/ant-design/ant-design/blob/4aa06ca28b772d63e944da37b3cefb3f1737a440/components/grid/style/index.less#L75-L84

The comment is misleading and I will remove it.

**Comment by LilyMGoh** [comment]
@afc163 Does this mean that Ant officially not support the 480px breakpoint?
