### ISSUE TITLE
表格中 展开行按钮和多选框按钮可以互换位置吗？

### ISSUE THREAD

**Issue by potatoCC** [ant-design/ant-design#27847]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-moon-x09i6?file=/index.js)
![image](https://user-images.githubusercontent.com/28758664/99493564-688a3800-29aa-11eb-8a32-1373bc6a0730.png)
### Steps to reproduce
可看本issue标题

### What is expected?
可以互换位置

### What is actually happening?
现在没有api去设置

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | react 17 |
| System | mac os 10.15.7 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://codesandbox.io/s/confident-leakey-g1uo6?file=/index.js
