### ISSUE TITLE
Tree组件如何实现最下面的子节点横向排列，这样比较节省空间

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design#27844]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree组件如何实现最下面的子节点横向排列

### What does the proposed API look like?
，，，

**Comment by yoyo837** [comment]
横向排列是什么意思？

**Comment by xuyanzhuqing** [comment]
try it
` scss
.ant-tree-list-holder-inner {
    display: block !important;
    .ant-tree-treenode {
      &.last-tree-item {
        display: inline-flex!important;
        width: 33.33%;
      }
    }
  }
`
