### ISSUE TITLE
Form rule min=1 does not work

### ISSUE THREAD

**Issue by peter-jerry-ye** [ant-design/ant-design#27845]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd484-forked-tuvgd)

### Steps to reproduce
选择几个选项后全部删除

### What is expected?
在无选中的情况下报错

### What is actually happening?
无报错

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.14.0 |
| System | MacOS Catalina |
| Browser | Chrome 86.0 |

---
对于array，min=1和required相同，但是如果min=1是无效的，建议在文档中标注

**Comment by afc163** [comment]
Fixed in https://github.com/yiminghe/async-validator/pull/257
