### ISSUE TITLE
建议Table组件的dataSource属性或者其他数组属性增加一个属性验证observableArray

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#2784]
当使用mobx-react时，声明的数组@observable list=[] 直接作为Table的dataSource属性时会报验证错误，每次都要toJS处理一下才不会报错，可以给dataSource属性多加个验证吗
dataSource: PropTypes.oneOfType([PropTypes.array, PropTypes.observableArray])

**Comment by benjycui** [comment]
```bash
> React.PropTypes.observableArray
undefined
```

表示没有这个方法。

**Comment by zhangchao828** [comment]
@benjycui 不好意思，是我自己看错了，这些验证方法是mobx-react自己提供的
![qq 20160822132916](https://cloud.githubusercontent.com/assets/15683846/17844483/af4f4c20-686c-11e6-86fa-b97f4795b71c.png)

**Comment by benjycui** [comment]
如果我没搞错,mobx 自身也没有提供对应的 PropTypes 的校验方式，所以这个 feature request 应该是无法实现。

**Comment by zhangchao828** [comment]
@benjycui https://github.com/mobxjs/mobx-react/pull/59
我是大概看了一下这个，自己也没去试过

**Comment by zhangchao828** [comment]
那我只能老老实实每个都toJS一下了
