### ISSUE TITLE
Upload: edit the "file" object at the end of the upload

### ISSUE THREAD

**Issue by jeanmatthieud** [ant-design/ant-design#27841]
- [X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Component: Upload
Antd version : latest

I'm using antd Upload component to upload a list of files.
I'm initializing the list of files with the "defaultFileList" property with previously uploaded files.
When the user uploads a new file, the webservice called returns some data about the new file (including the URL).

Currently, there is no way to change the property of the new listed file, except managing manually the "fileList" property, which is not convenient.
I would like the ability to change the content of the "file" object of a newly uploaded file, maybe with some optional property (eg: "fileTransformer") on the "Upload component" (as the "file" object already contains the response from the server, it will be trivial to transform it).

### What does the proposed API look like?
```
<Upload
...
fileTransformer={(file) => (file.response) ? { ...file, url: file.response.url, size: file.response.size } : file}
...
/>
```

**Comment by afc163** [comment]
You can control fileList, edit it in onChange.

**Comment by lucataglia** [comment]
<img width="1557" alt="image" src="https://github.com/user-attachments/assets/888f9b9f-c035-4f48-81e4-4b7d584f44ab">

I'm struggling too in adding new info into the File object managed by the Upload component. Trying spreading new values into the object seem to remove all the old fields but the uid. I'm not getting the answer "edit it in onChange", can you provide a working example ?
