### ISSUE TITLE
能不能暴露一个API，可以通过button控制Collapse开启与关闭？

### ISSUE THREAD

**Issue by wildor1** [ant-design/ant-design#27851]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
form点击提交之后，collapse自动关闭

### What does the proposed API look like?
暴露一个数组，在button的onClick里可以控制开启关闭

**Comment by afc163** [comment]
可以用 activeKey 控制 Collapse 的行为。
