### ISSUE TITLE
在表格展开行时，双击行展开需要返回一个新数组才能更新试图，而点击展开图标却不需要返回一个新数组，这是为什么？

### ISSUE THREAD

**Issue by potatoCC** [ant-design/ant-design#27853]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kezhankai-antd484-forked-gtoji?file=/index.js)
![image](https://user-images.githubusercontent.com/28758664/99505557-f02c7280-29bb-11eb-8994-3439e507cc0f.png)
![image](https://user-images.githubusercontent.com/28758664/99505597-fcb0cb00-29bb-11eb-8e90-9fe35f485b97.png)

### Steps to reproduce
查看点击展开图标钩子函数和双击表格行，钩子函数

### What is expected?
期待行为一样

### What is actually happening?
实际不一样

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.14 |
| System | mac os  |
| Browser | 谷歌 |

**Comment by afc163** [comment]
确实很奇怪。

**Comment by zombieJ** [comment]
expand 内部会有 render，不要依赖 mutable 数据：
https://ant.design/docs/react/faq-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BF%AE%E6%94%B9%E7%BB%84%E4%BB%B6%E4%BC%A0%E5%85%A5%E7%9A%84%E5%AF%B9%E8%B1%A1%E6%88%96%E6%95%B0%E7%BB%84%E5%B1%9E%E6%80%A7%E7%BB%84%E4%BB%B6%E4%B8%8D%E4%BC%9A%E6%9B%B4%E6%96%B0%EF%BC%9F
