### ISSUE TITLE
[RangePicker] Missing hoverRange border in year panel when start date and end date are in the same year

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27855]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker](https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker)

### Steps to reproduce

- Enter the link and find the date type RangePicker
- Select a start date and end date in year `2020`
- Then click the end date in input and enter the year pannel in the right side
- Hover next year in the year panel
- If you can't reproduce it, please follow the steps in the GIF below
![bug233](https://user-images.githubusercontent.com/50612752/99507313-2f5bc300-29be-11eb-90cf-a9c425ce543d.gif)

### What is expected?
There is border

### What is actually happening?
There is no border
![image](https://user-images.githubusercontent.com/50612752/99507944-fa9c3b80-29be-11eb-80d1-192295743051.png)

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by yoyo837** [comment]
Seem similar as #27798

**Comment by AlanCutFlim** [comment]
@yoyo837  Kind wired, if i change the start date after that, the hoverRange border gets back again

![normal233](https://user-images.githubusercontent.com/50612752/99513869-0f300200-29c6-11eb-984f-922706ef8937.gif)

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
