### ISSUE TITLE
Menu open change keys empty when controlled and change collapsed

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#27856]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cebianbuju-antd484-forked-ui4b9?file=/index.js)

### Steps to reproduce
1. open devtools console
2. click **切换** button

### What is expected?
openKeys should be keep when change collapsed

### What is actually happening?
openKeys empty

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by yoyo837** [comment]
#24967
