### ISSUE TITLE
Expansion of tree is slow.

### ISSUE THREAD

**Issue by Sven65** [ant-design/ant-design#27852]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-tree-expansion-forked-toyx4?file=/index.js)

### Steps to reproduce
1. Have a tree with alot of data
2. Render the tree
3. Try to expand a tree node
4. Notice that it takes extremely long to do so.

### What is expected?
That the tree doesn't take ages to expand and collapse.

### What is actually happening?
It's taking ages to expand and collapse.

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | ^16.14.0 |
| System | Windows 10 OS Version 1909 (Build 18363.1016) |
| Browser | Google Chrome 86.0.4240.198 |

---
The issue seems to not happen as frequently if I set an absolute **pixel** height on the tree itself, but as doing so will break my layout, that's not a restriction that I can abide by.

**Comment by afc163** [comment]
We resolve the perfermance issue by adding fixed height which could enable visual scroll for large data Tree.

There is no other solution for now.

**Comment by Sven65** [comment]
Alright. Do you have any plans for other solutions?
