### ISSUE TITLE
Select搜索和远程数据结合时，精确搜索选项列表也没有数值

### ISSUE THREAD

**Issue by WeiHuiYing** [ant-design/ant-design#27866]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qqbxk)

### Steps to reproduce
精确搜索的时候，选项列表没有数值

### What is expected?
选项列表展示当前精确搜索的数值

### What is actually happening?
选项列表无值

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.8.6 |
| System | win7 |
| Browser | google版本 86.0.4240.75（正式版本） （64 位） |

**Comment by afc163** [comment]
例子里指定了 `filterOption={false}`，把搜索结果交给后端了。
