### ISSUE TITLE
Passing showToday to RangePicker 

### ISSUE THREAD

**Issue by yhy-1** [ant-design/ant-design#27863]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, only DatePicker is able to pass a showToday props. I would like this feature included in RangePicker. This would be a Today in both the start and end date panel. 

### What does the proposed API look like?
<DatePicker
showToday={True}
...
/>

**Comment by afc163** [comment]
Today button is a shortcut to select today in DatePicker, there is preseted range to match it for RangePicker as well.

https://ant.design/components/date-picker/#components-date-picker-demo-presetted-ranges

**Comment by panda6412** [comment]
What if I want to set the only startDate with preset ranges.

I have tried two ways below that cannot solve my requirement.
```
<DatePicker.RangePicker ranges={{ 'today': [moment()] }} />
```

```
<DatePicker.RangePicker ranges={{ 'today': [moment(), undefined] }} />
```
