### ISSUE TITLE
给后端工程师用的开箱即用的框架

### ISSUE THREAD

**Issue by layidao** [ant-design/ant-design#27874]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望能解决80%后端工程师的“开箱即用”的需求, 一个不懂前端的后端工程师拿到这个框架需要从头学习怎么用怎么改这个框架,时间成本稍微高了一点. 很多使用此框架都是做管理系统用,做管理系统的基本都要有, 用户登录,基于角色的菜单管理,功能管理等等,像这样的需求每个拿到框架的人都需要从头做,那么为何不出个版本,把这些功能都做了呢, 对于不懂前端的人可以改个 配置中的域名就可以访问自己的api,然后只要根据自己的业务,把精力都放在登录后的CRUD页面就好了. 
可能每家对于登录,分角色的动态菜单需求还是有差别的,但如果官方给出一个版本,比葫芦画瓢也很容易改出自己需要的版本.

### What does the proposed API look like?
期望官方出一套,含有登录,基于角色的动态菜单的后台管理版本

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design-pro

**Comment by afc163** [comment]
https://scaffold.ant.design/

**Comment by layidao** [comment]
> https://github.com/ant-design/ant-design-pro

这个好像没有基于角色的动态菜单吧

**Comment by yoyo837** [comment]
> > https://github.com/ant-design/ant-design-pro
> 
> 这个好像没有基于角色的动态菜单吧

有的，代码调整下就可以了，不过也许这一块不算开箱即用

**Comment by layidao** [comment]
> > > https://github.com/ant-design/ant-design-pro
> > 
> > 
> > 这个好像没有基于角色的动态菜单吧
> 
> 有的，代码调整下就可以了，不过也许这一块不算开箱即用

如果官方给一个版本,对于没有前端基础的人,照猫画虎就可以开工了,麻烦大神出个面向后端的 pro版的吧,照顾一下前端小白,也扩展一下后端用户, 您看看这个项目https://github.com/flipped-aurora/gin-vue-admin ,这种对于纯后端用户还是蛮有用的,当然不需要像它这个给出后端服务, 只要给出标准的基于角色的标准接口,和接口吐出什么样的标准格式菜单数据就好了
