### ISSUE TITLE
Tabs横向溢出时如果有Tooltip影响下来菜单使用

### ISSUE THREAD

**Issue by md5pk** [ant-design/ant-design#27889]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0713h?file=/index.js)

### Steps to reproduce
点击右侧Tabs下拉菜单，鼠标移动试着选择不同Tab

### What is expected?
下拉菜单不出现Tooltip

### What is actually happening?
下拉菜单Tab上的Tooltip影响菜单使用

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.10 |
| System | Windows 10 |
| Browser | Chrome 86 |

**Comment by md5pk** [comment]
搜了一下其他的issue，和这个有些相似：https://github.com/ant-design/ant-design/issues/27699
但感觉本质上是不同的问题，所以还是开了一个新的。

**Comment by md5pk** [comment]
可不可以指定下来菜单只显示纯文本，不显示react component ?
和这个feature request差不多： https://github.com/ant-design/ant-design/issues/27721

**Comment by zombieJ** [comment]
@md5pk 
嗯，看起来是同一个需求。我合并过去了。

**Comment by zombieJ** [comment]
merge into #27721
