### ISSUE TITLE
About InputNumber can input characters

### ISSUE THREAD

**Issue by Passion-Logan** [ant-design/ant-design#27882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Avoid checking by yourself, although it can be solved easily

### What does the proposed API look like?
The name of this component is InputNumber, so it should only be able to input numbers. Expect to modify it so that users cannot enter characters other than numbers

**Comment by afc163** [comment]
See 

https://github.com/ant-design/ant-design/issues/27014
https://github.com/ant-design/ant-design/issues/9421
