### ISSUE TITLE
.less中的@keyframes无法保持原来的命名

### ISSUE THREAD

**Issue by hellobbq** [ant-design/ant-design#2788]
#### 本地环境

- antd 版本: 1.9.1
- 操作系统及其版本：windows10
- 浏览器及其版本: chrome 52.0.2743.116 m

#### 你做了什么？
index.jsx :
`import './common.less'`

common.less
`@keyframes aaa {}`
or 
`:global { 
@keyframes aaa {}
 }`
#### 你期待的结果是：

index.css
`@keyframes aaa {}`

#### 实际上的结果：

index.css
`@keyframes aaa____hellxsfsdfsdf {}`

**Comment by afc163** [comment]
非 antd 问题，请自行探索 webpack 工作流。
