### ISSUE TITLE
Typography editable in Collapse.Panel header

### ISSUE THREAD

**Issue by lukasluecke** [ant-design/ant-design#27885]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cm26w)

### Steps to reproduce
Put editable Typography in Collapse Panel header

### What is expected?
Typography should prevent click event propagation, so the panel doesn't collapse/open when clicking the edit icon

### What is actually happening?
The panel collapses/opens when clicking the edit icon

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.1 |
| System | macOS 10.15.7 |
| Browser | Safari 14.0 |

**Comment by lukasluecke** [comment]
Same issue for the enter keypress when saving the editable value.

**Comment by lukasluecke** [comment]
There is already a reproduction link right there 🤨

**Comment by afc163** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/507615/99748516-a48edb80-2b17-11eb-9bd8-480bdca3aab7.png">

**Comment by lukasluecke** [comment]
Oh damn, sorry. It didn't save my changes. Updated now 🙈

**Comment by lukasluecke** [comment]
@afc163 Could you relabel this, please? I'll look into creating a PR for fix soon as well, if no one else does 🙂

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-x4de4?file=/index.js
