### ISSUE TITLE
Select component performs a React state update after unmounting

### ISSUE THREAD

**Issue by pmwmedia** [ant-design/ant-design#27887]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/pmwmedia/antd-reproduction-select-performs-illegal-update](https://github.com/pmwmedia/antd-reproduction-select-performs-illegal-update)

### Steps to reproduce
1. Checkout https://github.com/pmwmedia/antd-reproduction-select-performs-illegal-update
2. npm install
3. npm test

### What is expected?
The select component should not try to perform any illegal React state update after being unmounted.

### What is actually happening?
The select component tries to perform an illegal React state update after being unmounted.

Output warning:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
        in List (created by OptionList)
        in OptionList (created by ForwardRef(Select))
        in div (created by SelectTrigger)
        in div (created by Align)
        in Align (created by CSSMotion)
        in DomWrapper (created by CSSMotion)
        in CSSMotion (created by PopupInner)
        in PopupInner (created by Popup)
        in div (created by Popup)
        in Popup (created by Trigger)
        in ForwardRef (created by Trigger)
        in Trigger (created by SelectTrigger)
        in SelectTrigger (created by ForwardRef(Select))
        in div (created by ForwardRef(Select))
        in ForwardRef(Select) (created by Select)
        in Select (created by ForwardRef(InternalSelect))
        in ForwardRef(InternalSelect) (created by MyComponent)
        in MyComponent
```

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.14.0 |
| System | Windows 10 and Ubuntu 18.04.5 |
| Browser | Chrome 86, Internet Explorer 11, and Firefox 81 |

---
The issue only occurs when trying to unmount the select component while it is opened. It seems that this issue was introduces with antd 4.6.0 as the issue does not occur with antd 4.5.4 and earlier, but does occur with antd 4.6.0 till 4.8.4.

**Comment by silentim** [comment]
<Dropdown overlay={<Menu><Menu.Item><a href="/some">text</a></Menu.Item></Menu>}>....</Dropdown>

While click a link within dropdown items, also has similar error:

devScripts.js:5836 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at PopupInner (http://192.168.0.8:8000/templates/umi.js:340310:23)
    at div
    at Popup
    at http://192.168.0.8:8000/templates/umi.js:343230:25
    at Trigger (http://192.168.0.8:8000/templates/umi.js:340762:96)
    at Dropdown (http://192.168.0.8:8000/templates/umi.js:314594:28)
    at Dropdown (http://192.168.0.8:8000/templates/umi.js:78397:75)

**Comment by zombieJ** [comment]
Did you get the error in browser? Or it's test only?

**Comment by silentim** [comment]
Yes, get error in the browser, both production and development

**Comment by pmwmedia** [comment]
@zombieJ It is possible to reproduce this issue in browsers. Actually, I have firstly seen it in my browser when I was testing something different. However, this issue appears very seldom in my browser, because it seems to be a matter of timing. By my unit test, I can reproduce this issue for 100%. If I click manually in the browser, I I will be able to reproduce this issue in maybe 1 of 100 tries.

**Comment by pmwmedia** [comment]
I found a workaround by calling `await new Promise(setImmediate)` before unmounting the `select` component.

This indicates that Antd triggers a `setTimeout` call when opening the selection menu of a `select` component, but doesn't cancel the timeout when unmounting the component.

**Comment by WangJM001** [comment]
i have the same problem on `DropDown`
![image](https://user-images.githubusercontent.com/20501316/105009457-75dca500-5a75-11eb-8bd7-e57034aac17c.png)

**Comment by Virgil-N** [comment]
i have the same problem on DropDown +1
