### ISSUE TITLE
Modal. confirm打开的对话框的”确认“按钮默认被focus，导致鼠标失去hover效果

### ISSUE THREAD

**Issue by fstg0504** [ant-design/ant-design#27896]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
打开modal组件的确认对话框，点击文档的confirm方法弹出的对话框的确认按钮默认被focus，颜色是浅色，导致鼠标hover没有变化，需要鼠标随便点击页面，取消了按钮的focus，才可以正常显示hover效果的颜色

### What is expected?
对话框弹窗出来后，确定按钮默认不被focus，应该显示正常的颜色，鼠标可以hover改变它的颜色

### What is actually happening?
对话框弹窗出来后，确定按钮默认被focus，鼠标失去了hover效果，需要点击一个页面任何地方取消按钮的focus才可以正常使用hover效果

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | react |
| System | mac |
| Browser | 谷歌 |

---
其他版本也有这个问题，不知道是故意这样设计的还是个bug，反正我公司ui认为这是个bug

**Comment by afc163** [comment]
这是预期的，需要保证按钮可以默认被下一步键盘响应。如果对 UI 表现的要求高于对可访问性的要求，可以用 `autoFocusButton: false` 关闭。
