### ISSUE TITLE
Tree组件里的checkbox可以像checkbox一样，可以点击文字进行选中

### ISSUE THREAD

**Issue by wildor1** [ant-design/ant-design#27901]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree组件点击文字可以勾选

### What does the proposed API look like?
textToChecked

**Comment by afc163** [comment]
https://codesandbox.io/s/controlled-tree-antd484-forked-hg0y3
