### ISSUE TITLE
Table组件，当设置了sticky属性或固定表头后，表头的内容将不参与该列的宽度计算，导致标题换行

### ISSUE THREAD

**Issue by Leo233** [ant-design/ant-design#27906]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7k3l7?file=/index.js)

### Steps to reproduce
1.使用table组件，并设置以下属性：
```
<Table
  columns={columns}
  dataSource={data}
  scroll={{ x: "max-content" }}
  sticky
/>
```

2.将某一列的标题设置为较长，同时将其内容设置为较短。

3.然后就会发现标题的内容将不会影响到该列的宽度计算，从而出现标题换行的现象

### What is expected?
当Table组件设置了sticky属性或固定表头后，表头的内容仍然参与到该列的宽度计算

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.1 |
| System | macOs 10.14.6 |
| Browser | chrome 87.0.4280.67 |

**Comment by afc163** [comment]
固定表头后，表头和内容区域实现上是两个 Table，目前是表头的宽度会和内容区域宽度进行同步（很难双向同步，这是先有鸡先有蛋的问题）。如果表头明显更宽，建议指定宽度。

```diff
  {
    title: '一个很长的标题',
    dataIndex: "age",
+   width: 130,
    key: "age"
  },
```

**Comment by vaynevayne** [comment]
有没有什么api可以直接获取所有列的width?  如果想解决, 可以看看这个思路

先不设置 sticky , 获取宽度, 修改columns, 设置 sticky , 这样绕一圈应该就行了, antd table 内部要是可以自己执行这段逻辑就好了,
这里的难点应该是: 等所有数据都渲染完成再获取宽度, 但是不知道何时浏览器渲染完成, 获取宽度的时机比较难找, 
有个办法就是antd 渲染之后会给单元格加上一个渲染完成的classname, 比如在onCell里加, 这样弄个定时器去读取是否都有这个classname就行了, 不过虚拟table不支持这样, 也没必要支持
@afc163

**Comment by cwjbjy** [comment]
> 有没有什么api可以直接获取所有列的width? 如果想解决, 可以看看这个思路
> 
> 先不设置 sticky , 获取宽度, 修改columns, 设置 sticky , 这样绕一圈应该就行了, antd table 内部要是可以自己执行这段逻辑就好了, 这里的难点应该是: 等所有数据都渲染完成再获取宽度, 但是不知道何时浏览器渲染完成, 获取宽度的时机比较难找, 有个办法就是antd 渲染之后会给单元格加上一个渲染完成的classname, 比如在onCell里加, 这样弄个定时器去读取是否都有这个classname就行了, 不过虚拟table不支持这样, 也没必要支持 [@afc163](https://github.com/afc163)

太棒了，目前我在React18中遇到了类似的情况。设置sticky 后表头会出来的慢。我用你推荐的方法解决了

**Comment by cwjbjy** [comment]
> 有没有什么api可以直接获取所有列的width? 如果想解决, 可以看看这个思路
> 
> 先不设置 sticky , 获取宽度, 修改columns, 设置 sticky , 这样绕一圈应该就行了, antd table 内部要是可以自己执行这段逻辑就好了, 这里的难点应该是: 等所有数据都渲染完成再获取宽度, 但是不知道何时浏览器渲染完成, 获取宽度的时机比较难找, 有个办法就是antd 渲染之后会给单元格加上一个渲染完成的classname, 比如在onCell里加, 这样弄个定时器去读取是否都有这个classname就行了, 不过虚拟table不支持这样, 也没必要支持 [@afc163](https://github.com/afc163)

但先不设置 sticky , 之后设置 sticky , 表头的标题会抖动，估计是触发了重排引起的
