### ISSUE TITLE
Modal confirm自定义关闭图标

### ISSUE THREAD

**Issue by qq1292137282** [ant-design/ant-design#27900]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在项目中需要统一弹框的关闭图标，confirm没有提供自定义关闭图标的参数

### What does the proposed API look like?
Modal.confirm({
    closeIcon: <Icon />
})

**Comment by qq1292137282** [comment]
antd版本：3.23.4

**Comment by afc163** [comment]
3.x 不维护了，4.x 里可以提供支持。

**Comment by qq1292137282** [comment]
好的，谢谢
