### ISSUE TITLE
Checkbox.Group的onChange方法增加prevValue参数

### ISSUE THREAD

**Issue by fbambi** [ant-design/ant-design#27903]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前Checkbox.Group的onChange只能获取当前选中的全部checkedvalue，而无法获取本次选中/未选中的value。
![image](https://user-images.githubusercontent.com/16192754/99767332-d450da00-2b3d-11eb-8e1b-edf0ed29a8ce.png)

某些业务场景需要根据增量变化二次调整checkedValue，比如某两个checkbox互斥。可以增加一个prevValue参数，让开发者自己推算增量

### What does the proposed API look like?
```jsx
<Checkbox.Group
  onChange={(checkedValue, prevValue) => {
    // 上一次选中的值
    console.log(prevValue)
  }}
>
</Checkbox.Group>
```

**Comment by afc163** [comment]
受控模式直接拿 useState 里的 value 就行了。

**Comment by fbambi** [comment]
> 受控模式直接拿 useState 里的 value 就行了。

场景是Form内的CheckboxGroup，onChange内部通过form.getFieldValue获取的值已经是新的了。这个状态下只能用useRef

**Comment by fbambi** [comment]
@afc163 can you reopen it? I can create PR for this, if you think it's right

**Comment by fbambi** [comment]
> @afc163 can you reopen it? I can create PR for this, if you think it's right

@afc163 is there any response? :smile:

**Comment by afc163** [comment]
看上去你更应该用 normalize：https://codesandbox.io/s/jibenshiyong-antd485-forked-z49kx?file=/index.js

或者 Radio？

**Comment by fbambi** [comment]
> 看上去你更应该用 normalize：https://codesandbox.io/s/jibenshiyong-antd485-forked-z49kx?file=/index.js
> 
> 或者 Radio？

`normalize` solve my problem:smile:
