### ISSUE TITLE
Badge徽标数为1时，打开Chrome浏览器并开启Google翻译，数字‘1’会显示‘1个’

### ISSUE THREAD

**Issue by xiangcs** [ant-design/ant-design#27907]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/badge-cn/#header](https://ant.design/components/badge-cn/#header)

### Steps to reproduce
Badge徽标数为1时，打开Chrome浏览器并开启Google翻译，数字‘1’会显示‘1个’

### What is expected?
展示数字‘1’

### What is actually happening?
展示‘1个’

| Environment | Info |
|---|---|
| antd | undefined |
| React | 版本 87.0.4280.66（正式版本） （64 位） |
| System | window 10 |
| Browser | Chrome 浏览器 PC 端 |

**Comment by afc163** [comment]
这个我们好像做不了什么。。。
