### ISSUE TITLE
IE-11 Upload组件上传部分图片，会被自动旋转

### ISSUE THREAD

**Issue by enjoy-wind** [ant-design/ant-design#27913]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/upload-cn/](https://3x.ant.design/components/upload-cn/)

### Steps to reproduce
1.选一个5M的高清正立图片。
2.上传后会被自动旋转

### What is expected?
不会被自动旋转

### What is actually happening?
被旋转

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 15.6.2 |
| System | win10 |
| Browser | IE11 |

**Comment by afc163** [comment]
https://github.com/youzan/vant/issues/2332#issuecomment-449026450
