### ISSUE TITLE
Select suffixIcon click unable to open panel

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#27917]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daisousuokuang-antd484-forked-nxw9k)

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| Browser | chrome |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/27479
https://github.com/vueComponent/ant-design-vue/issues/3217

**Comment by afc163** [comment]
See #23263
