### ISSUE TITLE
The value selected in the Select component does not appear

### ISSUE THREAD

**Issue by issei1213** [ant-design/ant-design#27916]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-d6kl7?file=/index.js 　)

### Steps to reproduce
First of all there is a parent component and a child component.
In the parent component, we hide the modal component. Then, when you click on a button in the parent component, we make the child component appear and send the saved values as props.
Then I want to make the Select component in the child component display the saved value.

### What is expected?
I want to display the selected values in the Select component after setting the form.setFieldsValue

### What is actually happening?
Select component does not display the selected value

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.12.0 |
| System |    |
| Browser | chrome 86.0.4240.198 |

---
Please forgive me for not being able to show you all the code for security reasons

**Comment by afc163** [comment]
Your codesandbox is broken.

**Comment by issei1213** [comment]
Sorry. Self-resolved. Thank you for your he
