### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode when using <Modal /> and <Form.List/>

### ISSUE THREAD

**Issue by shadigaafar** [ant-design/ant-design#27921]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s7lh9)

### Steps to reproduce
Use <Modal/> component in strict mode and set it's attribute "visible" to "true"

### What is expected?
No warnings should be displayed.

### What is actually happening?
A warning message will appear in console.log stating: "findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node"

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.14.0 |
| System | Windows 10 pro 1909 |
| Browser | Edge  86.0.622.69 |

note: i have found this issue in other components such as <Form.List>

**Comment by shadigaafar** [comment]
I found out the <Form.List/> cause the same issue in strict mode...

**Comment by itsazzad** [comment]
https://github.com/ant-design/ant-design/issues/22493#issuecomment-764955421

**Comment by douglasjunior** [comment]
`<Layout.Sider/>` cause the same issue in strict mode.

![image](https://user-images.githubusercontent.com/1512341/107272819-067f2300-6a2d-11eb-8fcf-7a7e4a630efb.png)

**Comment by mukhtorov** [comment]
That's issue can be reproduced when custom React component is passed to styled() factory. In this case styled-components create className and pass it as prop to that custom React component. If component is not supposed of supporting className prop, warn of incorrect usage should be thrown.
So, in styled-components code, we need to find DOM node with generated className.

**Comment by masterbd** [comment]
I have the same issue with **Modal** component.

**Comment by lethanhan97** [comment]
Having the same issue for Form Validation. On version 4.13.1

**Comment by Shu-Ji** [comment]
Having the same issue for <Image>. When click to preview .

**Comment by alceuscardoso** [comment]
> 
> 
> `<Menu.SubMenu/>` cause the same issue in strict mode.
> 
> ![image](https://user-images.githubusercontent.com/1512341/107272819-067f2300-6a2d-11eb-8fcf-7a7e4a630efb.png)
> 
> Perhaps related to the same problem as `<Modal />`.

Same here.

**Comment by alceuscardoso** [comment]
<Menu.SubMenu/>

![image](https://user-images.githubusercontent.com/19271750/113601197-67833b80-9617-11eb-9cc8-24512088c7a9.png)

**Comment by jellohouse** [comment]
I'm getting this too on slider component. This needs to be fixed!

Whoever is working on this repo please fix it - I feel like this should be an easy fix.

**Comment by fzxiao233** [comment]
Same issue with modal

**Comment by goulkreek** [comment]
Same issue with modal on my side too.
Really annoying error logs since months...
Please fix it. ;-)

**Comment by mcntai** [comment]
same issue with Badge component....
![image](https://user-images.githubusercontent.com/68130217/115967419-35d90280-a53b-11eb-8df0-5042a54224cd.png)

**Comment by SylannBin** [comment]
This issue should be closed I think.

See https://github.com/ant-design/ant-design/issues/26136.

**Comment by sakib412** [comment]
Same issue in **v4.13.0**. why they are not fixing this?

**Comment by martin-luo** [comment]
Same issue in **v4.15.6** for `Popover`

**Comment by LuisValgoi** [comment]
my goodness. why? just why? this problem exists?

**Comment by weei-jiang** [comment]
![image](https://user-images.githubusercontent.com/85597996/121285287-b51a6e00-c910-11eb-847a-92f1b69c2ef3.png)
使用antd,Menu.Item组件,这是为什么

**Comment by yoyo837** [comment]
See #26136.

**Comment by yoyo837** [comment]
i'll lock this.
