### ISSUE TITLE
DatePicker 是否支持在初始化时就自动展开日期选择？

### ISSUE THREAD

**Issue by huanglei252** [ant-design/ant-design#2792]
#### 本地环境

- antd 版本:最新版
- 操作系统及其版本：mac
- 浏览器及其版本:谷歌

**Comment by afc163** [comment]
确实没有，后续可以暴露出来。

`popupVisible`

**Comment by huanglei252** [comment]
@afc163 谢谢您的回复

**Comment by afc163** [comment]
哦，支持的，看这个例子。http://ant.design/components/date-picker/#components-date-picker-demo-start-end

有一个 `open` 属性。
