### ISSUE TITLE
Carousel throwing error - "Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by mohammadwali** [ant-design/ant-design#27927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://localhost:3000/](https://localhost:3000/)

### Steps to reproduce
- Render 
```
<Carousel speed={800} effect="scrollx" autoplay>
<div>1<div>
<div>2<div>
<div>3<div>
 </Carousel>
```

- Swipe through or click the dots.

### What is expected?
No error

### What is actually happening?
Unable to preventDefault inside passive event listener invocation

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 17.0.1 |
| System | MacOs |
| Browser | Chrome 86.0.4240.198 |

**Comment by afc163** [comment]
trace https://github.com/akiran/react-slick/issues/1650
