### ISSUE TITLE
Table 能支持双击事件吗

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2793]
行事件只发现onRowClick这个事件，没发现onRowDblClick,双击弹出编辑的场景还是蛮多的

**Comment by dai875939260** [comment]
还有onRowClick，onRowDblClick 还是要把原始的event对象或者列的key 传进来，有时候需要判断是点击了哪一列

**Comment by afc163** [comment]
感觉你需要的不是 onRowClick，而是这样的：

```jsx
render: () => {
  return <div onClick={} onDoubleClick={}></div>;
}
```

**Comment by dai875939260** [comment]
不是的 ，双击某行，弹出编辑。因为之前用的jqgrid，很多功能用ant table实现起来比较困难。还有选中没有高亮是设计如此么(不是hover的样式)

**Comment by afc163** [comment]
antd 里是按设计规范走的，目前只实现规范里的东西。

`onRowDoubleClick` 这个接口如果有需求的话，欢迎去给 [rc-table](https://github.com/react-component/table) 提 PR ~
