### ISSUE TITLE
AntAffix.displayName is undefined

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#27936]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sxiwk?file=/index.js)

### Steps to reproduce
```ts
import {Affix} from 'antd';

const name = Affix.displayName;
```

### What is expected?
Affix.displayName should be present

### What is actually happening?
Affix.displayName is no available

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.13.1 |
| System | macOs |
| Browser | Safari |

**Comment by afc163** [comment]
It is not antd issue, React Component don't expose displayName defaultly, just don't dep on it: https://codesandbox.io/s/antd-reproduction-template-forked-rjcy9

**Comment by monolithed** [comment]
@afc163 , I know that, but pay attention to other components like Button:

https://codesandbox.io/s/antd-reproduction-template-forked-ixth7

```ts
import {Button} from 'antd';

Button.displayName; // Button
```

This can be useful for custom wrappers: 

```ts
import React, {ComponentProps, FunctionComponent} from 'react';
import AntButton from 'antd/lib/button';

type Props = ComponentProps<typeof AntButton>;

const Button: FunctionComponent<Props> = ({...props}) => {
    return <AntButton data-test={AntButton.displayName} {...props} />;
};

export {Button};
export type {Props as ButtonProps};
```

**Comment by afc163** [comment]
You can try `Affix.name`, see https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging

**Comment by monolithed** [comment]
@afc163, yep, I can, but `Affix.displayName` is better than `Affix.displayName || Affix.name || 'Affix'`.
Furthermore `displayName` is a standard property to describe React's components, why not to use it?

**Comment by afc163** [comment]
It is better way to get displayName by https://github.com/jurassix/react-display-name

**Comment by monolithed** [comment]
@afc163 first of all, the displayName property is [already present in other components](https://github.com/ant-design/ant-design/search?q=displayName).
Also, that property is very [useful for debugging](https://reactjs.org/docs/react-component.html#displayname). 

> It is better way to get displayName by https://github.com/jurassix/react-display-name
There is a problem-solving principle — entities should not be multiplied without necessity (Occam's razor). it's one. 
I really don't understand why you are against obvious things. it's a bug and this issue should be reopened as well.
