### ISSUE TITLE
Form design and code generator 表单设计及代码生成器

### ISSUE THREAD

**Issue by zsl1549** [ant-design/ant-design#27939]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
方便开发

### What does the proposed API look like?
https://mrhj.gitee.io/form-generator/#/ 这个是Element ui 我希望AntDesign 也应该有 这样方便用户方便开发

**Comment by afc163** [comment]
目前没有精力做，社区做这个的不少，建议自行搜索。
