### ISSUE TITLE
table设置自定义expandIcon图标和expandRowByClick:true会导致展开无法收拢（数据带children版）

### ISSUE THREAD

**Issue by daisycyt** [ant-design/ant-design#27937]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shuxingshujuzhanshi-antd484-forked-0b6ty?file=/index.js)

### Steps to reproduce
自定义icon，设置了expandRowByClick:true，当数据中有 children 字段时

### What is expected?
正常收拢

### What is actually happening?
无法收拢

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/shuxingshujuzhanshi-antd484-forked-95pvi?file=/index.js
