### ISSUE TITLE
table with fixed table-layout. enable className for col in colgroup 

### ISSUE THREAD

**Issue by alissaVrk** [ant-design/ant-design#27933]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
hiding a column (without re-rendering the whole table)
I'm trying to hide a column, but can't use `display:none` on the td/th without adding display none to the <col>.
<col> with width:0px  also doesn't behave nicely 

### What does the proposed API look like?
actually putting the column className on the <col> will be good enough

**Comment by afc163** [comment]
```diff
columns={[{
  title: 'xxx',
+ className: 'hide',
}]}
```

**Comment by alissaVrk** [comment]
this will add the class to the <td>s and the <th>s but not the <col>
so won't solve the problem

**Comment by alissaVrk** [comment]
just realized that all the \<col\>s from the original message weren't visible, fixed now.. sorry

**Comment by alissaVrk** [comment]
@afc163, what you suggested won't solve the issue. what I'm missing is the ability to add a class/style to the /<col/> element (since the className is applied to the td and th only)

thanks
