### ISSUE TITLE
How to render Radio in a table column antd

### ISSUE THREAD

**Issue by jovanimal** [ant-design/ant-design#27947]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-hertz-rt0h3?file=/index.js)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/54385240/99928834-d1e0c100-2d85-11eb-855c-9277bc21b6ec.png)

Click on Wednesday column and the Radio buttons are not mutually exclusive

### What is expected?
Only able to select 1 option under each column when using Radio.

### What is actually happening?
When I use Input (under column "Mon") instead of Radio with the property "name", it works fine. But not when I use it with Radio or Radio.Group. 
I also aware that we can use property "name" in Radio.Group, but how can I render it in a table as shown in my code? 

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/wizardly-solomon-xqz5h?file=/index.js

**Comment by aseph8083** [comment]
> https://codesandbox.io/s/wizardly-solomon-xqz5h?file=/index.js

how to change with useState?
const [checked, setChecked] = useState()
