### ISSUE TITLE
We can define the content of small icons used in components, such as download and delete of upload.

### ISSUE THREAD

**Issue by Jerry-GitHub-123** [ant-design/ant-design#27943]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.The product has its own language model, not only including Chinese and English.
2.Small icons have custom title content.

### What does the proposed API look like?
The content and function of each small icon can be put forward as a API.

**Comment by afc163** [comment]
`showUploadList={{ ... }}`
