### ISSUE TITLE
Different trigger event show different dropdown overlay

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design#27941]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不同触发行为，展示不同的内容，以满足更复杂应用场景。比如：点击用户头像展示该用户信息卡片，右键展示对该用户操作的菜单。

### What does the proposed API look like?
`<Dropdown
    trigger={['click', 'contextMenu']}
    overlay={e => {
       if (e.type === 'click') {
           return <div>用户卡片</div>
       }
       if (e.type === 'contextMenu') {
          return <div>跟他聊天</div>
       }
    }
/>
   <Button>用户A</Button>
</Dropdown>
`

**Comment by afc163** [comment]
套多层 Dropdown 即可。
