### ISSUE TITLE
How to use table API expandedRowRender to expand a subtable 

### ISSUE THREAD

**Issue by Vikci** [ant-design/ant-design#2794]
#### 本地环境

- antd 版本：V1.8.0
- 操作系统及其版本：Mac OS X 10.11.6
- 浏览器及其版本：Google Chrome Version 52.0.2743.116 (64-bit) 

#### 你做了什么？

我想用table这个组件的API，expandedRowRender，来展开一个子表格

#### 你期待的结果是：

子表格的格式，不会影响到原有表格

#### 实际上的结果：

子表格的格式，会影响下面的表格

#### 可重现的在线演示

<img width="1158" alt="screen shot 2016-08-21 at 23 33 17" src="https://cloud.githubusercontent.com/assets/19770777/17838130/b199a20c-67f7-11e6-9094-92720e53bf8f.png">

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
try `1.10.0`

**Comment by LiboliboLibolibo** [comment]
你是怎么控制子表格的展开的我期望点击父表格展开子表格，点击另一个父表格前面的子表格收起该如何处理？

**Comment by whiteblueblack** [comment]
手风琴的展开方式，我也在探索中，希望有答案的诸位指点一二！
