### ISSUE TITLE
ellipsis don't work in the table header, when we using sorting, filters, search in the table header

### ISSUE THREAD

**Issue by cybersunt** [ant-design/ant-design#27959]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ellipsis-column-antd485-forked-ynwee)

### Steps to reproduce
`ellipsis` don't work in the table header, when we using sorting, filters, search in the table header

### What is expected?
`ellipsis` work in the table header, when we using sorting, filters, search in the table header

### What is actually happening?
ellipsis styles are not thrown into child divs and spans

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | 16.12 |
| System | Windows 10 |
| Browser | Chrome 86 |

**Comment by MohitGevaria** [comment]
This issue still persists. Is there any way-around for this??
