### ISSUE TITLE
[RangePicker] showTime doesn't work when format exists

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#27951]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/riqigeshi-antd485-forked-3izv6)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/14918822/99942176-2a29ba00-2daa-11eb-97e6-7edd2e0ce30d.png)

### What is expected?
- `showTime` should work when `format` exists.

### What is actually happening?
- `showTime` doesn't work when `format` exists.

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.14.0 |
| System | MacOS 10.15.5 |
| Browser | Chrome 81.0.4044.138 |

**Comment by xrkffgg** [comment]
similar to https://github.com/ant-design/ant-design/issues/27812

**Comment by afc163** [comment]
It is intented, please fill complete format with `HH:mm:ss`.
