### ISSUE TITLE
maxlength in select search

### ISSUE THREAD

**Issue by Airkro** [ant-design/ant-design#27954]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Just like input maxlength, for keyword length control.

### What does the proposed API look like?

```js
<Select maxLength={16} showSearch />
```

**Comment by zombieJ** [comment]
What's `maxLength` works for?

**Comment by Airkro** [comment]
![image](https://user-images.githubusercontent.com/12206891/100299212-0fd02600-2fce-11eb-825b-2a21efb7e0a0.png)

**Comment by zombieJ** [comment]
Select is not input. This should be added in AutoComplete instead.

**Comment by Airkro** [comment]
@zombieJ 

您好，我的需求场景是：

限制 Select 的搜索词（例如序列号）长度，以免误输入过长的搜索词，导致搜不到结果。目的并不是限制最终选择的内容长度。
这与 AutoComplete 似乎不太符合。搜索框的 props 穿透是不是更为合适？

---

Hello, my demand scenario is:

Limit the length of the search keyword (serial number etc) of select, to avoid mistakenly entering the too long search term, resulting in no search results. The goal is not to limit the length of the final selection.
This doesn't seem to fit in with autocomplete. Is props penetration of search box more appropriate?

**Comment by zombieJ** [comment]
Use `onSearch` &  `searchValue` to control user input text length instead.

**Comment by promotion-xu** [comment]
onSearch & searchValue not work for me

**Comment by promotion-xu** [comment]
It's not work for me. Do you solve the problem. @Airkro

**Comment by hesetiema** [comment]
> Unfortunately, antd v3 select doesn't have the searchValue props, can someone provide an example? 🧐

I find the solution.😶
`const inputEle = ()=>{
  return <input maxLength={10} autoComplete={'off'} />
};`
` <Select getInputElement={inputEle} mode="tags" >
    {children}
  </Select>`

**Comment by wanderowski** [comment]
Hello, in my project it is required to set the maximum length to the search field. Using searchValue and onSearch is not a solution in my case since this component is used in different modules. Only in some of the modules it is required to limit the maximum length. Is there any solution so far?

**Comment by RafaelCss** [comment]
How do I control the input length in the select with showSeach?

**Comment by ferneybaron** [comment]
This is not the better approach, but it is something
`
/* start selectMaxLength */
  const selectMaxLength = 10
  const [selectValue, setSelectValue] = useState('');
  const options = [
    {
      value: '1',
      label: 'Not Identified',
    },
    {
      value: '2',
      label: 'Closed',
    },
    {
      value: '3',
      label: 'Communicated',
    }
  ]
  const onInputKeyDown = (e) => {
    const { keyCode, key } = e
    console.log('keyCode: ', keyCode);
    if (keyCode === 8) {
      const value = selectValue.substring(0, selectValue.length - 1)
      setSelectValue(value)
    }
    console.log('key: ', key);
    if (selectValue.length > selectMaxLength - 1) return
    if (keyCode === 32 || (keyCode > 64 && keyCode < 166)) {
      setSelectValue(selectValue + key)
    }
  }
`

And the Select:

`<Select
    style={{ width: 465 }}
    searchValue={selectValue}
    onInputKeyDown={onInputKeyDown}
    showSearch
    placeholder=""
    optionFilterProp="children"
    filterOption={(input, option) => {
      return (option?.label.toLocaleLowerCase() ?? '').includes(input.toLocaleLowerCase())
    }
    }
    filterSort={(optionA, optionB) =>
      (optionA?.label ?? '').toLowerCase().localeCompare((optionB?.label ?? '').toLowerCase())
    }
    options={options}
  />
`

**Comment by MaxCarmonaG** [comment]
Hello, here is a solution that worked for me.

```
const App = () => {
  const handleChange = (value) => console.log("selected " + ${value});
  const maxLength = 10;
  const [search, setSearch] = useState("");
  const handleSearch = (value) => setSearch(value.substring(0, maxLength));
  
  return (
    <Select
    mode="tags"
    style={{ width: "100%" }}
    onChange={handleChange}
    options={options}
    searchValue={search}
    onSearch={handleSearch}
  />
)};
```

**Comment by Lynne42** [comment]
`import { Select } from 'antd';
import React, { useEffect, useRef } from 'react';

interface Props {
    [x: string]: any
}
const ChatSearchAt: React.FC<Props> = () => {
    const ref = useRef<any>(null);
    useEffect(() => {
        if (ref?.current) {
            const input = ref?.current?.nativeElement.querySelector('input');
            input.setAttribute('maxlength', '10');
        }
    }, [])
    return (
        <Select
            showSearch
            ref={ref} />
    );
};
export default ChatSearchAt;`
这样是ok的

**Comment by rohitvishwakarma-sf** [comment]
My solution

```
import type { SelectProps } from 'antd';
import { Select } from 'antd';
import { DefaultOptionType } from 'antd/es/select';
import { useState } from 'react';

type SearchLimitedSelectProps<T> = SelectProps<T> & {
  maxSearchLength: number;
};

function SearchLimitedSelect<T extends string | number = string>({
  maxSearchLength,
  showSearch = true,
  onSearch,
  onChange,
  optionFilterProp = 'label',
  suffixIcon = null,
  ...props
}: SearchLimitedSelectProps<T>) {
  const [searchValue, setSearchValue] = useState('');

  const handleSearch = (value: string) => {
    const limitedValue = value.slice(0, maxSearchLength);
    setSearchValue(limitedValue);
    onSearch?.(limitedValue);
  };

  const handleChange = (
    value: T,
    option?: DefaultOptionType | DefaultOptionType[]
  ) => {
    setSearchValue(''); // clear search after selection
    onChange?.(value, option);
  };

  return (
    <Select<T>
      showSearch={showSearch}
      searchValue={searchValue}
      onSearch={handleSearch}
      onChange={handleChange}
      optionFilterProp={optionFilterProp}
      suffixIcon={suffixIcon}
      {...props}
    />
  );
}

export default SearchLimitedSelect;

```
