### ISSUE TITLE
ant-design pro 主页预览功能失效，全部404

### ISSUE THREAD

**Issue by rydensun** [ant-design/ant-design#27952]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/dashboard/analysis](https://preview.pro.ant.design/dashboard/analysis)

### Steps to reproduce
-

### What is expected?
能够正常访问

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | - |
| System | macbook pro  catalina |
| Browser | Chrome  |

**Comment by zombieJ** [comment]
我这边看起来是好的， @chenshuai2144  确认一下

**Comment by chenshuai2144** [comment]
也是好的，检查一下你的网络。ping 是可以通的
