### ISSUE TITLE
Input组件addonBefore属性添加Select组件样式问题

### ISSUE THREAD

**Issue by lixiaomeng1988** [ant-design/ant-design#27969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-shamir-5gzd0?file=/src/App.js:305-316)

### Steps to reproduce
样式问题

### What is expected?
表格对齐

### What is actually happening?
没有对齐

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
这样如何？https://codesandbox.io/s/priceless-banzai-wdrui?file=/src/App.js
