### ISSUE TITLE
Wrong handling of the tabIndex prop in Select component

### ISSUE THREAD

**Issue by dennismorello** [ant-design/ant-design#27964]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sizes-antd485-forked-xqn5w?file=/index.js)

### Steps to reproduce
1. Add a `<Select>` component
2. Set the `tabIndex` property

### What is expected?
The `tabindex` HTML attribute should be set only on the `<input>` rendered element.

### What is actually happening?
The `tabindex` HTML property is set both on the wrapper `<div>` and on the `<input>` element.

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17.0.1 |
| System | macOS 11 Big Sur |
| Browser | Chrome 87.0.4280.67 |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/pull/577
