### ISSUE TITLE
Clicking outside of a Select component clears input element before firing blur event

### ISSUE THREAD

**Issue by rvinzent** [ant-design/ant-design#27967]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-component-inconsistent-blur-fb8l5?file=/index.js)

### Steps to reproduce
1. start typing into the box
2. press Tab to fire blur event
3. observe that the value in the box has been logged to the console as expected
----
1. type into the box again
2. now click outside of the box to fire the blur event
3. observe that an empty string has been logged to the console instead of the value typed into the box

### What is expected?
I expect the `input` target of the blur event to consistently emit the value typed into the box

### What is actually happening?
The value of the `input` element is empty when a blur event is fired by _clicking_ outside of the box. The value is retained when using the `Tab` key to fire the blur event. It should consistently emit the value from the input element

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.13.1 |
| System | macOS 10.15.4 (19E287) |
| Browser | Version 87.0.4280.67 (Official Build) (x86_64) |

---
I am trying to make forms behave consistently for the users, and it does not exhibit the same behavior when using `Tab` to blur versus clicking to blur

**Comment by zombieJ** [comment]
Do not deps on `onBlur` to get the value of input. Use `onSearch` instead. We do not promise any value returns from the event.target of `onBlur`. You should only get value with:
* Select Value: `onChange`
* Select Search Input Value: `onSearch`

**Comment by marufMunshi** [comment]
This issue is still happening on the latest version of antd

**Comment by YehuditGrinwald** [comment]
Add 2 props to  _select component_:  
 `autoClearSearchValue={false} `  `mode="multiple"` works for me.  
see [antd doc](https://ant.design/components/select/#Select-props)
