### ISSUE TITLE
应该给readonly input一个不一样的style。

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#27968]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在从外观上区分不出是不是readonly的。
readonly应该呈现出不能修改，但是能选择复制的状态。

我还希望readonly的input能显示出输入光标。
这点不知道在浏览器上能不能实现，因为我发觉浏览器上的readonly input就是不显示光标的。但是其实是有的，点一下鼠标按shift+左右键就能感知到光标的存在。而且windows的readonly edit控件是有光标的。

最后，还是只要能和普通状态和disabled状态有区分就可以了。

### What does the proposed API look like?
`<Input readOnly={true}/>`

**Comment by afc163** [comment]
原生 input 的 readonly 和默认状态从视觉上就是无法区分的，Ant Design 暂时也不会进行区分。
