### ISSUE TITLE
Bug in copy link text

### ISSUE THREAD

**Issue by endophasie** [ant-design/ant-design#27966]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-q8z7j?file=/index.js)

### Steps to reproduce
Click the "copy" icon (it's part of the link) 

### What is expected?
If you click link text, you should be sent to the address. If you click the copy icon, the text should be copied, you won't be sent to the link address.

### What is actually happening?
The text has been copied and then you have been sent to the link address (I added a target to make it clearer).

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | react 17.0.1 |
| System | MacOS Catalina 10.15.7 |
| Browser | Firefox 83.0 |

**Comment by BaileyMillerSSI** [comment]
Was this released already?
