### ISSUE TITLE
Tree节点上能否绑定数据

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2796]
想在树节点上绑定额外的数据，有办法吗？

**Comment by benjycui** [comment]
<del>多喝热水，重启试试</del>

空泛的问题不可能得到具体的回复，麻烦详细描述你的诉求。

**Comment by dai875939260** [comment]
之前所有的东西都是jquey做的，树用的是ztree的，现在用antd，有些实现还是之前的习惯,比如ztree会把整个data对象放到node对象了。所以也希望能提供一个属性放额外的数据：
```
<TreeNode key={item.id} title={item.name} data={{extra:'11'}}>
      {childrenNext}
</TreeNode>
```
onSelect node对象包含了data对象
自己去做这个数据管理有点一波三折

**Comment by benjycui** [comment]
不要不要不要把额外的数据放到 DOM node 上面，就算是 Virtual DOM 也不建议这么做。

我不认为这有多复杂：

```jsx
{
  [id]: extraData,
}
```

**Comment by encorehe** [comment]
{
  [id]: extraData,
}

你好，请问一下
这个是什么意思啊？

我这也遇到这个问题了。。。 点击树节点 要把节点数据放到form 里面去 进行编辑 但是不知道怎么获得节点数据。。。 需要发请求获取？

**Comment by yesmeck** [comment]
@encorehe 使用问题建议到 https://segmentfault.com/t/antd 上问吧。
