### ISSUE TITLE
I want to add a Tooltip for Typography.Text after the ellipsis appeared

### ISSUE THREAD

**Issue by MrHeer** [ant-design/ant-design#27976]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
After the ellipsis appeared, I want display full text when pointer hover it.

### What does the proposed API look like?
I'm not clear.

**Comment by afc163** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/507615/100071621-37ac7600-2e76-11eb-8e95-19b25488a044.png">

**Comment by afc163** [comment]
Try `ellipsis={{ symbol: <Tooltip title="content">...</Tooltip> }}`

**Comment by MrHeer** [comment]
> Try `ellipsis={{ symbol: <Tooltip title="content">...</Tooltip> }}`

@afc163 But the ellipsis of Typography.Text only support boolean type for.

**Comment by afc163** [comment]
Text 目前是单行的，用的是原生的 css 能力。

可以直接 `<Tooltip title="content"><Text>content</Text></Tooltip>` 或者 `<Text title="title">content</Text>`，不支持在 `...` 上单独添加 Tooltip。

**Comment by MrHeer** [comment]
我希望的是如果空间不足出现了`...`，我才提供 Tooltip 或者 title，如果空间足够大，就不需要

**Comment by MrHeer** [comment]
https://stackoverflow.com/questions/5474871/html-how-can-i-show-tooltip-only-when-ellipsis-is-activated
