### ISSUE TITLE
zero-width trigger for sider does not work

### ISSUE THREAD

**Issue by jasan-s** [ant-design/ant-design#27975]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-sider-fixed-solved-forked-zw5od?file=/src/index.js)

### Steps to reproduce
open reproduction demo in smaller screen device

### What is expected?
since 0 width for collapse is set i expect when i click on the trigger, the sider to expand and show. 

### What is actually happening?
the sider remains hidden  at trigger click.

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17.0.1 |
| System | MAC OSX |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/react-component/menu/pull/351

**Comment by jasan-s** [comment]
@afc163 what is the fix?

**Comment by afc163** [comment]
https://procomponents.ant.design/components/layout cannot collapse either.

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/27719/files#diff-c58876b8810c9f329249ebe0da66a0b3bc0953591d3fec9125ee7de20e9cf2cdR108
