### ISSUE TITLE
Loading will only appear when the theme is modified for the first time

### ISSUE THREAD

**Issue by MrHeer** [ant-design/ant-design#27971]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
1. Change the theme color on the footer(loading will appear)
2. Change again(no loading)

### What is expected?
Loading will appear when the theme is modified for every time.

By the way, I feel very stuck when I drag and choose the color.

### What is actually happening?
Loading will only appear when the theme is modified for the first time

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | ^16.9.0 |
| System | MacOS Big Sur version 11.1 Beta |
| Browser | Firefox 84.0b4 (64-bit) |

**Comment by afc163** [comment]
第一次 loading 是为了加载 less.min.js，第二次没了加载过程，直接调用了同步的 less.modifyVars 方法导致 loading 卡住没出来就直接修改成功了。看上去没什么好办法，暂时不动了。
