### ISSUE TITLE
quankun框架下Select点击 整个网页卡主崩溃

### ISSUE THREAD

**Issue by JaniceLian** [ant-design/ant-design#27978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
qiankun框架下，搭建一个使用antd组件的react子项目

### What is expected?
点击select出现下拉框

### What is actually happening?
点击select后，整个页面卡主崩溃；
类似组件datePicker没有出现问题；
单独跑子项目也不会出现问题。

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | react17.0.1 |
| System | MacOS |
| Browser | chrome87.0.4280.67 |

**Comment by afc163** [comment]
Please report it to https://github.com/umijs/qiankun/issues with reproduce demo.
