### ISSUE TITLE
Standalone badge jumps after initial load from top right to its position

### ISSUE THREAD

**Issue by gitter-me** [ant-design/ant-design#27979]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g7pwd?file=/index.js)

### Steps to reproduce
Load the sample (its the original from the documentation)
Refresh the example browser

### What is expected?
The badge should not jump around

### What is actually happening?
The badge jumps after initial load from top right to its position

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.14.0 |
| System | Does not matter |
| Browser | Does not matter |

---
It worked correctly in version 4.8.0 
But I haven't tested the versions between 4.8.0 and 4.8.5.

**Comment by gitter-me** [comment]
Addition: 4.8.4 apparently also did not have this issue

**Comment by zombieJ** [comment]
Initial Badge should not show the motion: https://codesandbox.io/s/standalone-antd485-forked-jd6ye?file=/index.js

**Comment by gitter-me** [comment]
@zombieJ I just tested 4.9.0 in my production app and the issue is still there.

But its a special case now, you can test it here by clicking the button in the codesandbox example:
https://codesandbox.io/s/standalone-antd491-trjmo?file=/index.js

The issue condition is:
If the value is 0 (and showZero is not set) and the value changes later, the badge jumps.

In my case this happens when I load the data via an api.
