### ISSUE TITLE
Button as Input addon doesn't style properly

### ISSUE THREAD

**Issue by n0ruSh** [ant-design/ant-design#27972]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/button-as-input-addonafter-73g1f?file=/index.js)

### Steps to reproduce
1. Click the demo link
2. Check out the buttons' style. 

### What is expected?
Buttons should be aligned with input properly.

### What is actually happening?
Buttons are't aligned with input properly.

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.14.0 |
| System | Mac |
| Browser | Chrome |

---
I checked the demos on official website which uses Selects as addon. Selects work properly as they are adapted to the scenario with additional `margin` and `border` style. Therefore, the similar operation can be applied to Buttons to fix the problem: 

```
.ant-input-group-addon {
  .ant-btn {
    // fix
    // margin: -5px -11px;
    // border-left-color: transparent;
    // border-right-color: transparent;
  }
}
```

I'm happy to submit a PR for this if maintainers think this needs to be resolved.

**Comment by afc163** [comment]
We don't support style of Button inside Input addon.

**Comment by n0ruSh** [comment]
> We don't support style of Button inside Input addon.

@afc163 Could you please explain the reason behind the decision? I think it's a common scenario where users would want to have an `input` which is followed with a `button`, just like the `captcha verification` case in the demo (I came across this problem in my project). It's true that users can implement this, with separate <Input\/> and <Button\/> elements and styling. E.g.

```
<div style={{ display: 'flex', flexDirection: 'row'}}>
  <Input/>
  <Button/>
</div>
```

However, the solution gets complicated if it's wrapped inside Form.Item. The following code just doesn't work. Users have to wrap the code into a `customized form controls`.

```
<Form.Item name='captacha'>
  <div style={{ display: 'flex', flexDirection: 'row'}}>
    <Input/>
    <Button/>
  </div>
</Form.Item>
```

**Comment by afc163** [comment]
In our design system, Captcha verification would be look like this way:


<img width="425" alt="image" src="https://user-images.githubusercontent.com/507615/100071380-f320da80-2e75-11eb-90bb-4b5f47b58323.png">
