### ISSUE TITLE
默认情况下InputNumber应该和Input有一样的宽度

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#27970]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
类似下面代码。这时候InputNumber和Input宽度是不同的。
虽然Input和InputNumber底层实现完全不一样，但是它们都姓Input所以在类似的使用方式下应该有差不多的表现。

不知道为什么要给InputNumber加上`width:90px`

### What does the proposed API look like?
```jsx
    <Row>
      <Col span={5}>
        <Input/>
      </Col>
      <Col span={5}>
        <InputNumber/>
      </Col>
    </Row>
```

**Comment by afc163** [comment]
最初的设计稿上是这样要求的，暂时不动了，解决方案见下方。

https://github.com/ant-design/ant-design/issues/10906
https://github.com/ant-design/ant-design/issues/1612#issuecomment-217823714
