### ISSUE TITLE
升级了atoolbuild 发现打包出来的文件超大

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2797]
"atool-build": "^0.7.1",
"antd": "^1.1.0",

打包出来的文件超大，恢复"atool-build": "^0.6.x", 会小很多

打包文件配置如下：
webpackConfig.entry = {
    portal : './src/framework/entry.jsx',
    common : ['react', 'react-dom', 'react-router','antd', 'redux', 'react-redux', 'react-router-redux']
  }

webpackConfig.babel.plugins.push('antd');

  // Fix ie8 compatibility
  webpackConfig.module.loaders.unshift({
    test: /\.jsx?$/,
    loader: 'es3ify-loader',
  });

  webpack.optimize.CommonsChunkPlugin('common', '[name].[hash].js');

  //排除构建的库
  webpackConfig.externals = {
      "jquery": "jQuery"
  };

**Comment by pigcan** [comment]
![image](https://cloud.githubusercontent.com/assets/848515/17844974/217c364c-6871-11e6-8599-fd8e4866a86f.png)
![image](https://cloud.githubusercontent.com/assets/848515/17844988/3a2fbede-6871-11e6-8a9c-ee8b5ed3b8c4.png)

测试项目由 antd-init 初始化出来的项目。

对比后并无差异。 

如有必要请提供案例。

**Comment by wuhaih** [comment]
你做了代码拆分麽，react-router 每个chunck文件比升级之后的大小大很多

**Comment by wuhaih** [comment]
能让我看下你 的webpark配置麽，我将antd react抽到commonjs，但是发现atoolbuild在打包时候 jqeury没抽出来

**Comment by afc163** [comment]
你应该提供有问题的案例仓库。

**Comment by wuhaih** [comment]
由于是公司的项目，不允许开源哦，能给我看看你们的webpark配置麽

**Comment by afc163** [comment]
你应该提供**整理过的**有问题的案例仓库。

另外，我们的 webpack 配置一直就在文档中写明了：http://ant.design/docs/react/getting-started#%E8%87%AA%E8%A1%8C%E6%9E%84%E5%BB%BA

**Comment by afc163** [comment]
非组件问题，也建议提到 https://github.com/ant-tool/atool-build 那里去。
