### ISSUE TITLE
Upload 组件accept 设置成 image/* 后文件选择框打开延迟

### ISSUE THREAD

**Issue by nodeman777** [ant-design/ant-design#2798]
#### 本地环境

- antd 版本:1.9.1
- 操作系统及其版本：windows 10.0.10240
- 浏览器及其版本: chrome 52.0.2743.116 m

#### 你做了什么？

引入antd的upload组件 设置accep属性为‘image/*’
#### 你期待的结果是：

像官网一样正常显示
#### 实际上的结果：
点击之后文件选择框填出非常缓慢

#### 可重现的在线演示

http://codepen.io/ea7son/pen/VjRwrW?editors=1010

**Comment by afc163** [comment]
https://github.com/fex-team/webuploader/issues/1908

应该是 chrome 的 bug 。

**Comment by afc163** [comment]
http://www.cnblogs.com/liangjiang/p/5799984.html

**Comment by afc163** [comment]
https://zhuanlan.zhihu.com/p/27946188
