### ISSUE TITLE
Missing/inconsistent translations for a date-picker component

### ISSUE THREAD

**Issue by Frontmaster** [ant-design/ant-design#27988]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd485-forked-0311h?file=/index.js)

### Steps to reproduce
1. Enter the link.
2. Comment line 7
3. Uncomment line 8
4. Wait till the environment is refreshed
    

### What is expected?
Placeholder text matches it's  picker type date/week/month/quarter/year.

### What is actually happening?
All placeholders have the same text 'Select date'. 
![Placeholder](https://i.ibb.co/fMQfPNZ/123.png)

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | ^16.14.0 |
| System | Win 10 Enterprise ver.1909 build 18363.1198 |
| Browser | Google Chrome Version 87.0.4280.66 (Official Build) (64-bit) |

---
The issue remains for translations other than 'en_GB' as well.

**Comment by abz53378** [comment]
Hi, all.
I will improve the en_GB and zh_TW local these days. 😄
