### ISSUE TITLE
Vertical step is broken in RTL

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#27989]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-i54dr?file=/index.js)

### Steps to reproduce
check codesandbox

### What is expected?
it was OK in the previous versions of antd

### What is actually happening?
steps should look ok in RTL

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17 |
| System | windows 10 |
| Browser | chrome 87 |

---
thanks😊

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/27514
