### ISSUE TITLE
Menu 受控模式已展开菜单的折叠动画和非受控不一致

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#27995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cebianbuju-antd485-forked-qkuyp?file=/index.js)

### Steps to reproduce
点击收缩按钮折叠菜单

### What is expected?
已展开菜单的折叠动画和非受控模式一致

### What is actually happening?
已展开菜单没有收缩动画

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | React 17 |
| System | WIN10 |
| Browser | Chrome 87 |

---

![menu](https://user-images.githubusercontent.com/1730277/100182677-26b44100-2f18-11eb-9139-d4944d73edc0.gif)
![menu2](https://user-images.githubusercontent.com/1730277/100182680-29169b00-2f18-11eb-8d71-0ff8c16b6cef.gif)

另外示例中多次折叠时有弹出菜单闪屏

**Comment by afc163** [comment]
https://github.com/react-component/menu/pull/351

cc @zombieJ

**Comment by nuintun** [comment]
@afc163 @zombieJ 问题依旧存在

**Comment by alienzhangyw** [comment]
openKeys为受控模式就会出现此问题

**Comment by afc163** [comment]
在 antd@4.16.1 中已修复：https://codesandbox.io/s/cebianbuju-antd4161-forked-lekb9

**Comment by windyzoe** [comment]
> Fixed in `antd@4.16.1`：https://codesandbox.io/s/cebianbuju-antd4161-forked-lekb9

打开看还是有这个问题

**Comment by windyzoe** [comment]
> 
> 
> > Fixed in `antd@4.16.1`：https://codesandbox.io/s/cebianbuju-antd4161-forked-lekb9
> 
> 打开看还是有这个问题

初步判断是Sider控制了menu的inlineCollapsed参数导致的,把sider替换成aside解决问题.
