### ISSUE TITLE
改进Table的DataIndex的类型

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#27997]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在DataIndex的定义是这样的：
```ts
type DataIndex = string | number | (string | number)[]; 
```
我建议改成
```ts
type DataIndex<RecordType> = keyof RecordType | number | (string | number)[]; 
```
那样在定义columns的时候，输入`{ dataIndex:'`立刻就有智能提示了。当然后面的`number | (string | number)[]`要改成强类型的话，写起来就比较复杂了。
像上面这样改是最常用的情况，是最简单的，效果也能立竿见影。

你们一开始写成这样，大概是因为以前版本支持`'user.age'`这种写法吧。现在不支持了。

类似其它的Form里的NameList，Table的rowKey，以及其它我还没用到过的等等等等，也一并这样建议。

### What does the proposed API look like?
type DataIndex<RecordType> = keyof RecordType | number | (string | number)[];

**Comment by zombieJ** [comment]
`string` 还是需要保留的，否则对于留存的自定义 `Cell.render` ts 编译就挂了。但是 keyof 这个想法很不错，欢迎 PR~

**Comment by heroboy** [comment]
@zombieJ `keyof X|string` 就直接变成 `string`了，相当于没有写。

**Comment by heroboy** [comment]
我再补充2点。
1. 当`RecordType`是数组的时候`keyof RecordType`已经包含了number，以及数组的一系列成员函数名字字符串。tuple的时候类似。
2. 严格来说`DataIndex`类型应该还是支持`symbol`的。

**Comment by zombieJ** [comment]
`dateIndex` 本身会对应出 `onChange` 事件里 column 的 `field` 字段。有种用法就是在  `dataIndex`  中写一个不存在的字段，然后在 `onChange` 里通过 `field` 做额外处理。所以如果是直接 `keyof` 那么这种用法就 break 掉了。

**Comment by heroboy** [comment]
没完全看懂你(@zombieJ)在说什么。
不过你的意思大概是指表格的某一列不对应数据里的字段吧，例如，显示的是操作按钮之类的。是这样吗？
我觉得这时候不应该写`dataIndex`, 应该写`key`。
写`dataIndex`是不是因为你不知道默认的情况下用`dataIndex`作为key的。
有时候key还是要写的，例如，两列同时对应同一个`dataIndex`, 一列显示id，一列显示id对应的名字。

**Comment by zombieJ** [comment]
大部分场景下，`dataIndex` 和 `key` 都是相同的，Table 里为此做了简化。另外，推断类型是 string 不影响提示：
<img width="221" alt="截屏2020-11-27 下午1 52 39" src="https://user-images.githubusercontent.com/5378891/100415816-f73c3a80-30b7-11eb-95a5-00a5b2b71937.png">


ref https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDkBzA9mgJkgPgZ2ACcBLAOxQG4AoKgYzVIKgCMAuORVJIA

**Comment by heroboy** [comment]
不是啊。只是当列表是空的时候，提示所有当前页面出现过的字符串而已。
![图片](https://user-images.githubusercontent.com/54468/100417156-33bd6580-30bb-11eb-8252-f96b37d40822.png)

**Comment by zombieJ** [comment]
噗，我想当然了。sorry
