### ISSUE TITLE
Requesting more modifications to the text area associated with TreeSelect

### ISSUE THREAD

**Issue by yalfers** [ant-design/ant-design#27990]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Current TreeSelect text areas continually grow with each element added. This creates some unwanted design issues for massive selections (80 ). It would be ideal to set the maximum number of rows for the text area of populated selections and allow scrolling on the text area.

### What does the proposed API look like?
<TreeSelect {...tProps} rows={4} />

**Comment by afc163** [comment]
See `maxTagCount`
