### ISSUE TITLE
Spin 组件的视觉效果：在启用 tip 后有必要隐藏 dot 吗？

### ISSUE THREAD

**Issue by jerrybendy** [ant-design/ant-design#2799]
最新版本的 Spin 组件， 在使用 tip 属性后会显示一段文本取代原来的 dot 动画效果，我觉得显示文本后保留动画效果应该会更好。

相关代码：
https://github.com/ant-design/ant-design/blob/master/components/spin/style/index.less#L111

效果演示：
http://codepen.io/jerrybendy/pen/YWbXbz?editors=0110

（CSS 中还原了 .ant-spin-dot 的 display 属性）

**Comment by afc163** [comment]
🎅  来个 PR ~

**Comment by jerrybendy** [comment]
好的

**Comment by jerrybendy** [comment]
已发 PR

#2801
