### ISSUE TITLE
table设置可编辑单元格，表格头设置ellipsis: true以后，导致表格hover上去的title不显示

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#28001]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kebianjidanyuange-antd485-forked-whf9l?file=/index.js)

### Steps to reproduce
查看已上链接

### What is expected?
希望表格hover的时候title能正常显示出来

### What is actually happening?
表格hover的时候title显示不出来

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.13.1 |
| System | window 10 |
| Browser | chrome 83.0.4103.61 |

**Comment by afc163** [comment]
https://codesandbox.io/s/kebianjidanyuange-antd485-forked-h5l6n?file=/index.js

**Comment by bihongbin3027** [comment]
要手动设置，多谢 @afc163
