### ISSUE TITLE
如何在 FUNCTION里调用 弹窗

### ISSUE THREAD

**Issue by wxhm1120** [ant-design/ant-design#2800]
```jsx
function changeEditState(type, obj, index) {
    switch (type) {
      case 'edit':   
        ref.orderByChild("plant").equalTo(obj.plant).once("child_added", function (edi) {
          var editRef = ref.child(edi.key());
          console.log(edi.val());     
        });
/
/
/
/
render(){
      title: '编辑',
      dataIndex:'edit',
      key: 'edit',
      width: '5%',
      render: (text,record,index) => (
        <a onClick={()=>changeEditState('edit',record,index)} ><Icon type="edit"/></a> 
      ),                
}
/
/
/
```

想实现的效果是 点击 EDIT 按钮， 取到当前数据，并 弹出 弹窗，

        <Button type="primary" onClick={this.showModal}>添加植物</Button>

此弹窗 在其他地方也用了，如上。

我现在要么 只弹窗，取不到当前条 数据， 要么 取到 数据了，无法弹窗。
问题就是 ， 如何在 上面的 FUNCTION里  调用 THIS.SHOWMODAL.

**Comment by benjycui** [comment]
帮你格式化了，麻烦阅读 https://guides.github.com/features/mastering-markdown/

然后看不懂你的问题。

**Comment by afc163** [comment]
It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).
