### ISSUE TITLE
Unable to render tabs contained in another file

### ISSUE THREAD

**Issue by mistre83** [ant-design/ant-design#28002]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g7qdt?file=/index.js)

### Steps to reproduce
Change the variable isWorking from true (see working example) and false (to see not working example)

### What is expected?
Tabs are rendered

### What is actually happening?
Tabs not rendered

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17.0.1 |
| System | All |
| Browser | All |

---
If the TabPanes are contained in another file, the Tabs are not rendered. All works fine if Tabs and TabsPane are in the same file. I created an external file tab-container who contains just the TabPane

**Comment by zombieJ** [comment]
TabPane is Syntactic sugar which means it do not support HOC.
