### ISSUE TITLE
[Bug]: antd@4.4.2，table.props.pagination.current can not be controlled

### ISSUE THREAD

**Issue by JhonXY** [ant-design/ant-design#28013]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bug-762lh?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/bug-762lh?file=/index.js

### What is expected?
能够受控

### What is actually happening?
无法受控，切换 pageSize 会重置页码为 1

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | * |
| System | * |
| Browser | * |

---
https://github.com/ant-design/ant-design/pull/25520/files
该次修改导致

**Comment by JhonXY** [comment]
pageSize 操作后，会触发一次多余的，将 current 置为1 的错误操作

**Comment by JhonXY** [comment]
详细对比 4.4.1 与 4.4.3 之间的差异，4.4.2则比较混乱

**Comment by JhonXY** [comment]
或者说能否给一个解释，为什么这样子更改

**Comment by zombieJ** [comment]
ref #24501
