### ISSUE TITLE
新创建的modal没有从鼠标点击位置缩放

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#28014]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/test-o4bd2?file=/index.js)

### Steps to reproduce
按照我示例代码中的模式使用Modal。
点击的时候创建，消失的时候销毁。

### What is expected?
Modal transition from the click point every time

### What is actually happening?
Modal transition from the middle of the page instead of from the click point

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 17.0.1 |
| System | window 10 |
| Browser | firefox |

---
https://github.com/ant-design/ant-design/issues/15795

**Comment by afc163** [comment]
为啥要这样创建？destoryOnClose 不能解决销毁的问题么？

**Comment by heroboy** [comment]
@afc163

那样我可以这样写：
```jsx
function App() {
    const [editor,setEditor] = useState(null);
    const [data,setData] = useState({somedata})
    function handleClickA() {
        function handleSave() { ... }
        function handleExit() { ...}
        setEditor(<EditorA data={data} afterClose={handleExit} onSave={handleSave} />);
    }
    return <>
        <button onClick={handleClickA}>A</button>
        {editor}
    </>
}
```
如果有多个`handleClickA`,`handleClickB`等等函数要弹出多种不同模态对话框。
按照你们示例的写法需要把所有可能出现的模态对话框都列在最后，然后还要在`App`函数这一层次来维护它们的各种visible等状态。这样岂不是很混乱，当种类比较多，增加一种的时候也需要在多个地方修改。更加麻烦的是，关闭按钮在`EditorA`里面，但是它关闭自己竟然还要修改`App`里的state。

我这样写就由`EditorA`自己来维护visible等状态了。所有`App`和`EditorA`通信交互的内容都在`handleClickA`中了。`App`只需要最后留一个`{editor}`这样的入口就可以了。而且毕竟是模态对话框，`App`同时只能有弹出一个模态对话框`{editor}`不需要是个数组。

最后，还有个好处是每次`EditorA`弹出来的时候，都是全新的一个实例。如果复用同一个`EditorA`，然后检测`props.data`变化，会使得`EditorA`的实现变得复杂一点。（这里data类似于一般input的`defaultValue`吧，只用一次。）

希望你能理解。

最后的最后，是不是可以扩展一下`Modal.info`系列函数，让它能弹出一个完全自定义的modal呢？也能解决我的问题呢。

**Comment by zombieJ** [comment]
点击之后创建的 Modal 是不知道你鼠标点击位置的。

**Comment by heroboy** [comment]
@zombieJ 
https://github.com/ant-design/ant-design/pull/16144/files

点击位置不是一个全局变量吗。
你们都写成这样了，不惜监听window上的事件了，这不能修一下吗？
虽然我觉得动画从中间开始也挺好。
