### ISSUE TITLE
Have custom validation only occur when you click submit

### ISSUE THREAD

**Issue by jimmy-e** [ant-design/ant-design#28025]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-snowflake-0v3qo?file=/index.js)

### Steps to reproduce
Start typing in the word "test" into the input

### What is expected?
Validation only occurs when you click submit

### What is actually happening?
The input gets validated every time you enter another key stroke

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 17.0.1 |
| System | Mac |
| Browser | Chrome |

---
Please see the codesandbox. I have an input with a custom validator rule. I only want this validation rule to occur when I click the "submit" button and not on every keystroke. Currently, you get an error message for every keystroke when typing in the input, even when you start typing in the word "test". How can I instead have this validation only occur when you click the submit button? Thanks.

**Comment by afc163** [comment]
```
validateTrigger: '',
```

**Comment by GastonVidart** [comment]
Hi, if its useful for anyone. I made it in antd v5.18.0 with validateTrigger={["onSubmit"]}

**Comment by berkgulmus** [comment]
> Hi, if its useful for anyone. I made it in antd v5.18.0 with validateTrigger={["onSubmit"]}

Just an fyi to the future readers: When using "" as the trigger, validation first occurs when the user submits but the moment user enters an input it re-validates, even without clicking submit. When using "onSubmit" however the user has to click submit again to re-validate & get rid of the error. 

Although these all should be better documented imo.
