### ISSUE TITLE
表格固定列重复渲染问题

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#2802]
表格列设置 fixed 属性后，对应列的 render 函数就会运行两遍。
这样会使固定列里面的组件重复创建。

**Comment by afc163** [comment]
目前是这样实现的，不然布局没法处理。有好的方式欢迎 PR ~

**Comment by xutou12** [comment]
被覆盖的部分可以不用渲染的，锁定的列只要宽度定死就不会有什么问题，当然实际使用时不定宽度基本也不可能，我们以前写的表格就是这样做的，一直很好用。

现在重复渲染两边是有问题的，比如在使用popover组件是如果是受控模式，点击一次会出现两个popover

**Comment by afc163** [comment]
宽度可以不定死的。

给个重现看看。

**Comment by xutou12** [comment]
代码例子
http://codepen.io/anon/pen/akgyNz?editors=1010

为了能看清楚两个气泡重叠，我设置了不同的内容，实际项目中内容相同气泡会完全重叠在一起不容易发现。
