### ISSUE TITLE
The tree can only be checked, not radio mode.

### ISSUE THREAD

**Issue by czf0321** [ant-design/ant-design#28026]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the system selects personnel and organizations, it often uses single selection or check

### What does the proposed API look like?
Add a selection attribute, such as selectType, which can be radio or chekbox

**Comment by czf0321** [comment]
hooks,异步加载时设置成radio模式
Hooks, set to radio mode when loading asynchronously
![image](https://user-images.githubusercontent.com/30063100/100401401-525c3600-3094-11eb-81cd-b6e8cc7be9ae.png)

**Comment by afc163** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/507615/100401476-8c2d3c80-3094-11eb-9209-1fa7e00c96f7.png">

Tree is selectable defaultly.

**Comment by afc163** [comment]
不带 checkbox 时，默认就是单选的。

**Comment by czf0321** [comment]
是否可以设置成将radio 显示出来呢？

**Comment by afc163** [comment]
暂时不支持，你也可以用 Checkbox 来做单选 https://github.com/ant-design/ant-design/issues/1562

**Comment by czf0321** [comment]
好的，谢谢
