### ISSUE TITLE
Antd Column Fixed Issue in IE 

### ISSUE THREAD

**Issue by mohitborse** [ant-design/ant-design#28020]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-fixed-columns](https://ant.design/components/table/#components-table-demo-fixed-columns)

### Steps to reproduce
The number of rows is needed in the table.
The left side column should be fixed in the IE browser.
The action column needs to be fixed while using horizontal scrolling.

### What is expected?
The number of rows is needed in the table.
The left side column should be fixed in the IE browser.
The action column needs to be fixed while using horizontal scrolling.

### What is actually happening?
Column fixed is not working in IE v11 browser

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | React |
| System | windows 10 |
| Browser | IE11 |

---
The number of rows is needed in the table.
The left side column should be fixed in the IE browser.
The action column needs to be fixed while using horizontal scrolling.

**Comment by zombieJ** [comment]
We do not support fixed column in IE:

<img width="1208" alt="截屏2020-11-27 下午2 04 40" src="https://user-images.githubusercontent.com/5378891/100416462-7f6f0f80-30b9-11eb-90b4-24301073f19a.png">


ref https://ant.design/components/table/#components-table-demo-fixed-columns
