### ISSUE TITLE
<input name="nodeName" value="" /> in <Form> will cause ERROR "Uncaught TypeError: element.nodeName.toLowerCase is not a function"

### ISSUE THREAD

**Issue by mmmy** [ant-design/ant-design#28023]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rmbd0?file=/index.js)

### Steps to reproduce
    <Form>
      {/* <Form.Item>
        <input name="nodeName" value=""/>
      </Form.Item> */}
      <Form.Item>
        <Select
        placeholder="select this you will see error(触发这个就可以看到bug)"
        >
          <Select.Option>
            A
          </Select.Option>
        </Select>
      </Form.Item>
      <Form.Item>
        <Table
          columns={[{title: 'name', dataIndex: 'name'}]}
          // 数据源中出现了nodeName关键字
          dataSource={[{name: 'nodeName'}]}
          rowSelection={{getCheckboxProps: (record) => ({name: record.name})}}
        />
      </Form.Item>
    </Form>

### What is expected?
dataSource={[{name: 'nodeName'}]} Form 组件不崩溃

### What is actually happening?
Form 崩溃 报错

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome  87.0.4280.66 |

---
这个bug出现在一个关键字有nodeName数据 渲染在 Form中的table中, 而table开启了行选择rowSelection

**Comment by afc163** [comment]
See https://github.com/facebook/react/issues/6284

**Comment by afc163** [comment]
It is a React issue: https://github.com/ant-design/ant-design/issues/2950#issuecomment-245852795
