### ISSUE TITLE
Select 中 Option 的 value 设成对象提示 key 重复

### ISSUE THREAD

**Issue by wengcd** [ant-design/ant-design#2803]
#### 本地环境

- antd 版本: 1.8.1
- 操作系统及其版本：macOS 10.11.6
- 浏览器及其版本: Chrome v52

#### 你做了什么？
将 Option 的 Value 值设成了对象，打算取对象中包含的index值来修改数组状态（即有多个`Select`）
Options遍历结果
```
const attributes = [{
    "attribute_id": 1,
    "spec_id": 3,
    "attribute_name": "红色"
  }, {
    "attribute_id": 2,
    "spec_id": 3,
    "attribute_name": "蓝色"
  }]
```
```
{attributes.map(attr =>
  <Option
    key={`attr-${attr.attribute_id}`}
    value={attr}
  >{attr.attribute_name}</Option>
)}
```

#### 你期待的结果是：
-- SELECT
  -- [OBJECT]（红色）
  -- [OBJECT]（蓝色）
#### 实际上的结果：
-- SELECT
  -- [OBJECT]（红色）

**Comment by wengcd** [comment]
PS. 即使我将它设置为
```
value={{
  key: attr.attribute_id.toString(),
  label: attr.attribute_name,
}}
```
也一样

**Comment by benjycui** [comment]
只支持 String

http://ant.design/components/select/#Option-props

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
