### ISSUE TITLE
tooltip添加disabled字段

### ISSUE THREAD

**Issue by XiaohuaDuo** [ant-design/ant-design#28036]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tootltip在字段长度不固定，超出后隐藏并显示tooltip，不超出不展示tooltip，目前只能重新写一个不包含tooltip的jsx，希望可以控制

### What does the proposed API look like?
添加一个disabled字段，默认为false，为true时，不展示tooltip

**Comment by xrkffgg** [comment]
`visible | 用于手动控制浮层显隐 | boolean | false`

这个就可以吧

**Comment by afc163** [comment]
`tooltip=""` 即可。
