### ISSUE TITLE
[Calendar日历]: 日期面板变化误触单元格onSelect

### ISSUE THREAD

**Issue by Roson99** [ant-design/ant-design#28046]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/roson99/pen/wvzvxLJ?editors=001](https://codepen.io/roson99/pen/wvzvxLJ?editors=001)

### Steps to reproduce
选择日期面板内容

### What is expected?
不会误触

### What is actually happening?
触发onSelect

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0.1 |
| System | macOS |
| Browser | Google Chrome 86.0.4240.198 |

**Comment by kingport** [comment]
请问问题解决了吗 这个bug 还没有修复

**Comment by zombieJ** [comment]
antd 里的 `onSelect` 行为是一致，点击相同选项会重复触发。不需要重复触发，请使用 `onChange`。

**Comment by kingport** [comment]
> antd 里的 `onSelect` 行为是一致，点击相同选项会重复触发。不需要重复触发，请使用 `onChange`。

点击单日需要出现弹窗，点选月年不需要弹窗，这种场景 只用onChange 不能满足业务 onchange的时候都会触发这个2个回调

**Comment by zombieJ** [comment]
点击月份面板，日期也是变化的。不是只点日期面板才变化。弹窗需求应该用 `dateCellRender` 来做。

**Comment by trunks1993** [comment]
解决了吗
