### ISSUE TITLE
modal框的maskClosable属性能否全局配置

### ISSUE THREAD

**Issue by KellenHe** [ant-design/ant-design#28042]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
modal的maskClosable默认是true的，希望可以全部改为false。

### What does the proposed API look like?
Modal.config({
  maskClosable: false,
});

**Comment by afc163** [comment]
建议封装上层组件 Modal 。
