### ISSUE TITLE
Anchor 能够提供字段控制是否需要左侧线条吗，点击的样式是否可以清除。现在发现一个树状里面应用后，点击中部的便签。会级联选择上面的标签。效果不好

### ISSUE THREAD

**Issue by Lcj-space** [ant-design/ant-design#28047]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
达到 a 标签的效果，应用场景能够够广泛一些。

### What does the proposed API look like?
isShowLine , isShowDefaultLinkAction

**Comment by afc163** [comment]
> isShowDefaultLinkAction

这是啥？

**Comment by afc163** [comment]
> 点击中部的便签。会级联选择上面的标签

不是很理解是啥意思。

**Comment by afc163** [comment]
> 达到 a 标签的效果

想象不出来是什么样子。

**Comment by Lcj-space** [comment]
就是不想要左侧那根线
![Uploading image.png…]()

**Comment by xrkffgg** [comment]
圆点呢？

**Comment by Lcj-space** [comment]
还有就是选中的时候

> 圆点呢？

圆点也不想要，我看文档没有控制字段

**Comment by Lcj-space** [comment]
![image](https://user-images.githubusercontent.com/22415092/100565548-de719600-32fe-11eb-9946-0aaed869e2fa.png)
其实是想放在树里面，点击的时候在右侧一个区域固定的地方显示对于文件

**Comment by xrkffgg** [comment]
如果只是单纯的想要隐藏样式。可以通过 className 修改 `.ant-anchor-ink`
`visibility:hidden;`

**Comment by Lcj-space** [comment]
后续会支持吗，目前我也是这样打算用css 屏蔽掉

**Comment by xrkffgg** [comment]
应该不会
