### ISSUE TITLE
select 搜索和远程数据结合，input输入值的时候，onchange事件没有触发

### ISSUE THREAD

**Issue by sophiehui99** [ant-design/ant-design#28048]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#components-select-demo-search-box](https://ant.design/components/select-cn/#components-select-demo-search-box)

### Steps to reproduce
官方文档示例：select 搜索框示例：https://ant.design/components/select-cn/#components-select-demo-search-box，input值发生变化的时候，onchang事件没有触发，只触发了onsearch事件。代码如下：
<Select
      showSearch
      showArrow={true}
      filterOption={false}
      style={{width:200}}
      defaultActiveFirstOption={false}
      onSearch={()=>{
        console.log('-----')
      }}
      onChange={(value)=>{
        console.log("搜索关键字" value)
      }}
      allowClear = {true}
      notFoundContent={"没有数据"}
    >
      {options}
    </Select>

### What is expected?
输入搜索的关键字，onchange事件触发，拿到输入的value值

### What is actually happening?
实际onchang事件没有执行

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
`<Select showSearch />` 只有选择时才会触发 onChange，输入行为是放在 onSearch 里的。
