### ISSUE TITLE
table with checkbox, border-spacing issue

### ISSUE THREAD

**Issue by aboveyunhai** [ant-design/ant-design#28059]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/solitary-glade-ziph4?file=/index.css)

### Steps to reproduce
add style to existing table
`className={"example-table"}`

```javacript
.example-table table {
  border-spacing: 1em;
}
```

### What is expected?
space between cell is changed.
No side effect

### What is actually happening?
space between cell is changed as expected.
but the checkbox style is changed also
the `√` is becoming so large. 
![image](https://user-images.githubusercontent.com/35160613/100495073-d571a080-3115-11eb-80cf-e4ec3296ea15.png)
comparing to the regular check mark
![image](https://user-images.githubusercontent.com/35160613/100495081-e7534380-3115-11eb-938e-ae38b14edb8e.png)

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 17.0.1 |
| System | No applicable |
| Browser | CodeSandBox |

**Comment by afc163** [comment]
如果覆盖的样式影响了 antd 自身的样式，建议自行针对性处理。
