### ISSUE TITLE
About antd icon. 关于antd的图标.

### ISSUE THREAD

**Issue by 13554599576** [ant-design/ant-design#28055]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In previous versions, You can easily to set the type attribute by string to get the icon.
But in the new version, multiple icon components have been replaced <Icon/>. If the back end stores an icon string, It will be hard to use string to get icon.
在以前的版本中, 可以很轻松的通过一个字符串去设置Icon组件的type属性从而获得自己想要的图标.
但是在新版本中, 图标的组件替换了各种不同的组件. 如果我后端存储的是图标的字符串, 它将难以通过使用字符串来获取想要的图标.

### What does the proposed API look like?
I would like to add <Icon/> to the new version.
我期望把Icon组件重新添加回来.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20668
