### ISSUE TITLE
Tree add dblclick

### ISSUE THREAD

**Issue by xiaofengqqcom123** [ant-design/ant-design#28052]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求一： Tree 支持双击事件
需求二： 双击事件可以绕开单击事件（可配置，此需求可不支持）
![WechatIMG20835](https://user-images.githubusercontent.com/29247931/100443880-772cc980-30e5-11eb-9217-005e953e0c0c.png)

### What does the proposed API look like?
dbclick：function(selectedKeys, e:{selected: bool, selectedNodes, node, event})

**Comment by afc163** [comment]
`<Tree onDoubleClick />`

https://github.com/react-component/tree/blob/7c85e61f3a5df521d52586a341c4d6b605f34873/src/Tree.tsx#L102-L103
