### ISSUE TITLE
Global locale setting override language-specific setting for a single component

### ISSUE THREAD

**Issue by engmsilva** [ant-design/ant-design#28050]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reproduce-local-and-global-locale-configuration-m0zku?file=/src/App.js)

### Steps to reproduce
Set the Location property of the DatePicker component other than the Location property of the ConfigProvider component

### What is expected?
The locale property of a specific DatePicker component should take precedence over the global locale setting

### What is actually happening?
The global locale setting overrides the locale property for a specific DatePicker component

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | React 16.13.1 |
| System | Elementary OS 5.1.7 Hera |
| Browser | Chrome Versão 87.0.4280.66 64 bits |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/30380

https://codesandbox.io/s/reproduce-local-and-global-locale-configuration-forked-hoe74?file=/src/App.js
