### ISSUE TITLE
NumberInput 无法正确格式化以色列等国家的负数值

### ISSUE THREAD

**Issue by xuqiang1227** [ant-design/ant-design#28057]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/geshihuazhanshi-antd486-forked-3sc5e)

### Steps to reproduce
以色列等国家的负数格式显示为：`-x.xxx.xxx,xxx`

也就是千分位分隔符为 `.`， 小数点为： `,`

当输入值为 `-88888888888.88` 应该格式化为： `-88.888.888.888,88` ，但实体上显示为： `-88,888.888.888,88`

格式化正则表达式为：`/\B(?=(\d{3}) (?!\d))/g`

### What is expected?
当输入值为 `-88888888888.88` 应该格式化为： `-88.888.888.888,88`

### What is actually happening?
实际上显示的为: `-88,888.888.888,88`

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.14.0 |
| System | window 10 |
| Browser | chrome 87 |

**Comment by afc163** [comment]
formatter 和 parser 完全是开发者自定义的，建议根据自己的需求定制修改。

**Comment by xuqiang1227** [comment]
@afc163  偏右，我查了一下代码，这个问题的原因是: 设置了 ` decimalSeparator = ',' `，`formatter`函数将千位分隔符设置为 ` .`。
rc-input-number 代码中，直接使用 
```
inputDisplayValueFormat = inputDisplayValueFormat
        .toString()
        .replace('.', this.props.decimalSeparator);
```
直接将格式化后的第一个位 `.`，替换成 `decimalSeparator` 。
所以这个地方，能否改为 
```
inputDisplayValueFormat = inputDisplayValueFormat
        .toString()
        .replace(/(.*)\./, `$1${this.props.decimalSeparator}`);
```

**Comment by yoyo837** [comment]
那只是个demo，或者你可以来PR帮忙改进一下demo

**Comment by afc163** [comment]
来个 PR 吧。

@xuqiang1227
