### ISSUE TITLE
Could you please add source folder to NPM package?

### ISSUE THREAD

**Issue by pahaz** [ant-design/ant-design#28065]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
From time to time I want to use IDE "goToCodeDeffinition" feature and watch some code details. Currently, I can see only type definitions or transpiled js code.

### What does the proposed API look like?
I want to have ts source inside the NPM package. It helps me to develop locally without internet and documentation.
It's also increased my performance.

**Comment by afc163** [comment]
It will increase npm pakcage size which affect install speed.

**Comment by pahaz** [comment]
Ok, but in my opinion, the development experience means matter than the install speed. 
Although, I can write my own utility that downloads the corresponding version of the source code and configures the IDE.

Thanks
