### ISSUE TITLE
Submenu inside separate component is not working

### ISSUE THREAD

**Issue by mk48** [ant-design/ant-design#28061]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/top-navigation-antd486-forked-xmfmy?file=/index.js)

### Steps to reproduce
1. Create a simple menu in a class
2. Create one more class and render only SubMenu
3. Use the new class into the 1st class

Kindly open and see the code sandbox repo
https://codesandbox.io/s/top-navigation-antd486-forked-xmfmy?file=/index.js 

```javascript

const { SubMenu } = Menu;

class SubMenuInClass extends React.Component {
  render() {
    return (
      <SubMenu key="SubMenuInClass" title="Two in Class">
        <Menu.Item key="setting:11">Option 1</Menu.Item>
        <Menu.Item key="setting:22">Option 2</Menu.Item>
      </SubMenu>
    );
  }
}

class App extends React.Component {
  render() {
    return (
      <>
      <Menu mode="horizontal">
        <Menu.Item key="mail">One</Menu.Item>
        <SubMenu key="SubMenu" title="Two">
          <Menu.Item key="setting:1">Option 1</Menu.Item>
          <Menu.Item key="setting:2">Option 2</Menu.Item>
        </SubMenu>
        <SubMenuInClass />
      </Menu>
      <h3>Just move the mouse on top of menubar</h3>
      </>
    );
  }
}
```

### What is expected?
SubMenu should be rendered properly

### What is actually happening?
Submenu's title display below the menu and while moving mouse on the menubar getting more errors on console.

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome 87.0.4280.66 (Official Build) (64-bit) |

---
This error is simple and can be reproducible easily. Please open my code sandbox https://codesandbox.io/s/top-navigation-antd486-forked-xmfmy?file=/index.js
this code sandbox is forked from Menu example.

**Comment by afc163** [comment]
https://codesandbox.io/s/top-navigation-antd486-forked-bj9ns?file=/index.js
