### ISSUE TITLE
Select选择器有没有明确的方法限制多选的option的数量

### ISSUE THREAD

**Issue by Qureo** [ant-design/ant-design#2806]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：Windows10
- 浏览器及其版本:Chrome 52

#### 你做了什么？
引入了Select选择器

**Comment by afc163** [comment]
自行用受控模式实现，选项超过 n 项时，把其他选项的 Option 设为 disabled。

**Comment by fubobing126** [comment]
其他项设置成disable之后 select不能回删了

**Comment by 965782379** [comment]
我自己的解决办法：超过n项时，将未选中的option设为disabled
实现代码
  // 当sprint选择框变化
  function SelectChange(value: any, option: any){
    if (option) {
      if (value.length >= sprintSelectMaxAmount) {
        // 设置其他选项为不可选
        setDisabledSprint(true)
        message.destroy()
        message.warn('最多选择'+sprintSelectMaxAmount.toString()+'个标签')
        return
      }
      else{
        // 设置其他选项为可选
        setDisabledSprint(false)
      }
      console.log('选择的', value, value.join(','))
      // this.setState({zclxbq: value})  // 更新value
      // await this.setState({lxbq: value.join(';')})
    }
  }
  
  // sprint选择框中的选项
  function selectOption(v: any){
    // 已选项,一直显示可选状态
    if(sprintData.toString().indexOf(v) >= 0){
      return (<Select.Option key={`${v}`} value={`${v}`} selected>
        {v}
      </Select.Option>)
    }
    // 未选项,如果已经选择了限制数量,则显示为不可选,否则显示为可选
    else{
      return (<Select.Option key={`${v}`} value={`${v}`} selected disabled = {disabledSprint}>
        {v}
      </Select.Option>)
    }
  }
