### ISSUE TITLE
官网访问为什么一直很慢？

### ISSUE THREAD

**Issue by codetown** [ant-design/ant-design#28064]
官网访问为什么一直很慢？

**Comment by yoyo837** [comment]
因为 https://ant.design 用的境外的云服务，你可以访问国内镜像

![image](https://user-images.githubusercontent.com/6134547/100546482-84d87f80-329c-11eb-8d29-e08bdeff7744.png)

https://github.com/ant-design/ant-design/issues/25661

**Comment by codetown** [comment]
谢谢@yoyo837
