### ISSUE TITLE
关于menu组件中openKeys的问题，官网上也有相同bug

### ISSUE THREAD

**Issue by 786049212** [ant-design/ant-design#2807]
#### 线上/本地

- antd 版本: ^1.6.4
- 操作系统及其版本：macos
- 浏览器及其版本: chrome

#### 你做了什么？
我希望能在路由跳转之后保存menu的选中状态，但是defaultOpenKeys的值会在路由跳转后被清空，于是我将状态存在openKeys中，这时候出现了和官网一样的状况，点击SubMenu之后，展开/隐藏的动作在mouseout时才发生

#### 你期待的结果是：
希望在没有指定openKeys的时候，defaultOpenKeys不会被强制清空，或者，用了openKeys的时候能够在点击以后立即隐藏/展开

#### 实际上的结果：
同上

#### 可重现的在线演示
[http://ant.design/docs/react/introduce](http://ant.design/docs/react/introduce)

**Comment by afc163** [comment]
duplicate https://github.com/ant-design/ant-design/issues/2701
