### ISSUE TITLE
Input.TextArea组件ref中无真实dom节点

### ISSUE THREAD

**Issue by zhaobosky** [ant-design/ant-design#28072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5pvmz?file=/test.js)

### Steps to reproduce
直接使用Input.TextArea组件，console组件中的ref就能看到

### What is expected?
可以获取真实dom

### What is actually happening?
无法获取真实dom

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.8.6 |
| System | macos 10.15.7 |
| Browser | chrome 87.0.4280.67 |

**Comment by afc163** [comment]
这种写法原生也不支持的：https://codesandbox.io/s/antd-reproduction-template-forked-luzix?file=/test.js

**Comment by zhaobosky** [comment]
> 这种写法原生也不支持的：https://codesandbox.io/s/antd-reproduction-template-forked-luzix?file=/test.js

我的意思是Input.TextArea中的ref中无法找到真实dom
![image](https://user-images.githubusercontent.com/22151144/100596143-c9b0f480-3336-11eb-89f3-9051bb730d31.png)

但是在Input的组件中可以找到真实到 在Input组件中可以使用ref.input
![image](https://user-images.githubusercontent.com/22151144/100596096-bbfb6f00-3336-11eb-8dd2-ecd646c818b2.png)

**Comment by yasikovsky** [comment]
There's a breaking TextArea ref change. 

Previously ```const myRef = useRef<TextArea>(null);``` has worked, now it throws:

```'TextArea' refers to a value, but is being used as a type here. Did you mean 'typeof TextArea'?  TS2749```

Using TextAreaRef instead allows you to get rid of this error, but that no longer contains the "setValue" method, that alters the TextArea's text contents using its internal state. In fact it doesn't allow you to change the text contents at all. The TextArea's ref property also expects ```string | ((instance: (TextArea | null)) => void) | React.RefObject<TextArea> | null | undefined``` so you can't pass a TextAreaRef object to it.

**Comment by HuaileiW** [comment]
Same thing with Input.Search
you can access dom through `this.inputRef.current?.input.input` and a warning from typescript "Property 'input' is private and only accessible within class 'Search'."

is there other way to get dom?

**Comment by hardmanhong** [comment]
ref.current.resizableTextArea.textArea

**Comment by dmwin72015** [comment]
+1, ref not a dom
