### ISSUE TITLE
Tree组件在节点拖拽的同时鼠标滚轮无法滚动列表

### ISSUE THREAD

**Issue by sRect** [ant-design/ant-design#28078]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuodongshili-antd486-forked-5u3ef?file=/index.js)

### Steps to reproduce
鼠标左键选中tree某节点，此时进行鼠标滚轮向上/向下滚动列表，列表无法滚动，只有松开鼠标后，才可以进行滚动列表。

### What is expected?
鼠标左键选中节点的同时进行鼠标滚轮滚动列表，此时列表可以进行滚动。

### What is actually happening?
鼠标左键选中节点的同时进行鼠标滚轮滚动列表，此时列表无法滚动。

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.13.1 |
| System | windows7 |
| Browser | chrome_63 |

**Comment by sRect** [comment]
![GIF](https://user-images.githubusercontent.com/23310700/100590375-48099880-332f-11eb-8726-ab568b372a36.gif)

如上图所示，鼠标左键任意选中节点，此时进行鼠标滚轮滚动列表，列表无法滚动，只有等鼠标左键松开，鼠标滚轮才可以滚动列表。

**Comment by afc163** [comment]
@sRect 试试最新的 antd 版本。

**Comment by abearxiong** [comment]
现在可以吗，感觉也不行呀，4.16 的版本 @afc163

**Comment by sRect** [comment]
@afc163 4.17.2的版本还是不行

**Comment by afc163** [comment]
Duplicate of #31057
