### ISSUE TITLE
TreeSelect组件开启多选搜索功能会导致下拉面板自动关闭

### ISSUE THREAD

**Issue by zxj963577494** [ant-design/ant-design#28071]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kegouxuan-antd486-forked-gy94q?fontsize=14&hidenavigation=1&theme=dark&file=/index.js)

### Steps to reproduce
在下拉框中输入关键字后，焦点离开下拉框，再次点击下拉框会出现 **自动关闭下拉面板** 的情况

### What is expected?
正确展示下拉面板

### What is actually happening?
自动关闭下拉面板

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.8.6 |
| System | mac v10.14.4 |
| Browser | chrome v87 |

---
autoClearSearchValue 置为false时，正常展示；

autoClearSearchValue 置为true时，焦点离开，当鼠标再次点击下拉框最左侧时是可以正常展示的，点击下拉框其他区域会重复上述的错误

**Comment by zxj963577494** [comment]
![Kapture 2020-11-30 at 14 03 31](https://user-images.githubusercontent.com/6766515/100574651-6e223f00-3315-11eb-9229-9bb50a8aed6d.gif)

**Comment by zongwenjian** [comment]
请问一下更新到哪个版本可以修复这个问题
