### ISSUE TITLE
Footer property of Transfer component can be received value as an array of node

### ISSUE THREAD

**Issue by tuansong** [ant-design/ant-design#28082]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am making a feature for changing the order of each item in `targetKeys` before saving the data, and the UI is two buttons on the footer. But seems like the left list of transfer component does not need those button for any reasons

### What does the proposed API look like?
Property: footer     
Description: A set of footers that are sorted from left to right	
Type: `ReactNode[]`

Or making a separate API for leftFooter & rightFooter

Regards, 
Song

**Comment by Eating-Eating** [comment]
let me try,i wonder i could making a separate API for leftFooter & rightFooter.

**Comment by xlei1123** [comment]
OK, I'll send a PR for it as soon as possible.
