### ISSUE TITLE
Collapse组件动态生成defaultActiveKey不生效

### ISSUE THREAD

**Issue by MadDonkey** [ant-design/ant-design#28087]
在render里面根据后台返回的一个list动态的生成了defaultActiveKey，但是发现最后并没有生效，如果直接把返回的数据写死放到Collapse的defaultActiveKey属性里面又能生效，请问这是为什么？看log第一次渲染的时候defaultActiveKey的确是空的，但是后面已经有数据了，难道这个defaultActiveKey只能第一次渲染生效哇？

**Comment by afc163** [comment]
> 难道这个defaultActiveKey只能第一次渲染生效哇？

对。

https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by MadDonkey** [comment]
为了默认展开我把activeKey设置为我想要设置的值，这时候能够默认展开，但是问题又来了，展开的又不能折叠了。。。请问我这种情况该怎么处理

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-Input/Select-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86%E3%80%82

**Comment by MadDonkey** [comment]
如果我在componentWillMount里面去调用后台数据先生成好我需要的keyList，再render，是不是也是可以的？
