### ISSUE TITLE
Table分页组件的样式问题

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design#2808]
分页组件样式想要简单自定义。比如设置margin和border等等。
发现style没有作用：
```
pagination={
          {
            style: { margin: '8px' },
            showTotal: total => `共 ${total} 条`,
            showQuickJumper: true,
          }
        }
```

**Comment by afc163** [comment]
rc-pagination 现在还没支持 style 属性，去 https://github.com/react-component/pagination/  来个 PR 怎么样？

**Comment by afc163** [comment]
@WhatAKitty 意下如何？

**Comment by WhatAKitty** [comment]
@afc163 可以，不过可能没那么快做这个，还有其他事情忙= =。

**Comment by afc163** [comment]
嗯，不急，也是你的需求~ 😄

**Comment by afc163** [comment]
@WhatAKitty

**Comment by WhatAKitty** [comment]
汗颜啊，最近忙的完全忘记了。

**Comment by WhatAKitty** [comment]
@afc163 已提交

**Comment by afc163** [comment]
Fixed in `rc-pagination@1.5.7` :+1:

重装 antd 即可。

**Comment by WhatAKitty** [comment]
OK


在2016年10月12日 00:19，偏右 写道:

Fixed in rc-pagination@1.5.7👍

重装 antd 即可。
