### ISSUE TITLE
Antd Carousel swipeToSlide API doesn't work.

### ISSUE THREAD

**Issue by berabulut** [ant-design/ant-design#28086]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[stackblitz](https://stackblitz.com/edit/react-jzfnxf-ky8wuj?file=index.js)

### Steps to reproduce
Just add this to Carousel 
 swipeToSlide={true}

### What is expected?
You should be able to scroll with mouse or touching to the screen without using dots or arrows.

### What is actually happening?
Swiping function doesn't work.

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by berabulut** [comment]
@afc163 it should be fixed now.

**Comment by afc163** [comment]
We turn off draggable by default, try `<Carousel swipeToSlide draggable>`

https://stackblitz.com/edit/react-jzfnxf-ablugw?file=index.js

**Comment by rfgonzalezweb** [comment]
hi, the swipeToSlide was removed in V5 ?

If so, is there any suggestion on how to implement it back? thanks
