### ISSUE TITLE
select组件enter事件

### ISSUE THREAD

**Issue by mylesshie** [ant-design/ant-design#2809]
#### 本地环境

- antd 版本:1.7
- 操作系统及其版本：windows
- 浏览器及其版本:chrome 53

select自动补全搜索框是否可以绑定enter按钮事件
既可以自动补全又可以模糊搜索这样？

**Comment by ddcat1115** [comment]
需求就是按enter的时候默认选中模糊搜索出来的第一个吧？

http://ant.design/components/select/#components-select-demo-search-box   这个demo去掉这一句试试

```javascript
defaultActiveFirstOption={false}
```

**Comment by mylesshie** [comment]
不是，是把关键词拿出来进行模糊搜索，不选下拉列表

**Comment by benjycui** [comment]
表示看不懂这个 issue，问题就不能清楚一点？

http://doc.zengrong.net/smart-questions/cn.html

**Comment by mylesshie** [comment]
期望：使用select的combobox模式时，在输入框中输入文字，按回车键，能触发一个事件
目前没有类似的事件绑定

**Comment by benjycui** [comment]
http://ant.design/components/select/#components-select-demo-search-box

**Comment by benjycui** [comment]
> 既可以自动补全又可以模糊搜索这样？

这交互有点奇怪。

或者在输入的同时，就搜索就可以了，用 throttle 控制下请求频率就好。
