### ISSUE TITLE
Horizontal scroll shadow in Table not showing on header without fixed right column

### ISSUE THREAD

**Issue by EvertEt** [ant-design/ant-design#28096]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-and-scroll-bar-with-the-page-antd486-forked-i6unf)

### Steps to reproduce
- Open demo at https://ant.design/components/table/#components-table-demo-sticky
- See right shadow covers header as well
- Remove last column in code
- Shadow only covers the contents, not the header

### What is expected?
- Shadow should continue over header

### What is actually happening?
The header is on top of the shadow making it not show

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.13.1 |
| System | Mac 10.15 |
| Browser | Chrome 86.0.4240.198 |

**Comment by marianayap** [comment]
@EvertEt I wasn't able to see the issue, could you add more details please?

**Comment by EvertEt** [comment]
For sure @marianayap !

The issue is visible here: (the sandbox above)
![image](https://user-images.githubusercontent.com/9197891/101132192-d79c9900-3606-11eb-9dbf-8e78342e8fa7.png)


Adding `fixed: "right"` to the last column:
![image](https://user-images.githubusercontent.com/9197891/101132258-f8fd8500-3606-11eb-9a77-572d06e98546.png)

**Comment by marianayap** [comment]
@EvertEt I can see the issue when I add `fixed: "right"` but I still don't have very clear what should happen

**Comment by EvertEt** [comment]
![image](https://user-images.githubusercontent.com/9197891/101196678-5a524200-3661-11eb-9c74-9acbdb01c9de.png)
should become
![image](https://user-images.githubusercontent.com/9197891/101196739-6b9b4e80-3661-11eb-8b7e-da35e05030c6.png)

**Comment by UxieVerity** [comment]
> @EvertEt I can see the issue when I add `fixed: "right"` but I still don't have very clear what should happen

he just want the effect of the overflow table-right show like the fixed:right at the column header.i guess

**Comment by sweetliquid** [comment]
Can I take it?

**Comment by sweetliquid** [comment]
It looks like that the z-index of `.ant-table-container::after` is too small.

**Comment by yoyo837** [comment]
PR welcome!

**Comment by marianayap** [comment]
@EvertEt Hello! it seems that if you add this line of code 
`{
    title: 'Action',
    key: 'operation',
    fixed: 'right',
    width: 100,
    render: () => <a>action</a>,
  },`

after `{ title: "Column 8", dataIndex: "address", key: "8" }` in line 64 it works

**Comment by EvertEt** [comment]
Yes, that's indeed what is explained in the first message. The bug is visible when there is no fixed: right column

**Comment by DaoxingHuang** [comment]
@EvertEt @marianayap The issue caused the ''[sticky](https://github.com/ant-design/ant-design/blob/master/components/table/demo/sticky.md)" property for Table.  if you use it , the class 'ant-table-sticky-header' is added table header. The css as below:
`.ant-table-sticky-header {
    position: -webkit-sticky;
    position: sticky;
    z-index: calc(2 + 1);
}`
why is 2+1? 'cause the siblings  ant-table-body is 2.
@EvertEt  the shadow you mentioned ,the css like this:
`.ant-table-ping-right:not(.ant-table-has-fix-right) .ant-table-container::after {
    -webkit-box-shadow: inset -10px 0 8px -8px rgba(0, 0, 0, 0.15);
    box-shadow: inset -10px 0 8px -8px rgba(0, 0, 0, 0.15);
}`
if use default z-index ,the value is 0, so if you want to fix this ,try set z-index is bigger than 3 ,for example 4.
`.ant-table-ping-right:not(.ant-table-has-fix-right) .ant-table-container::after {
    -webkit-box-shadow: inset -10px 0 8px -8px rgba(0, 0, 0, 0.15);
    box-shadow: inset -10px 0 8px -8px rgba(0, 0, 0, 0.15);
    z-index: 4; 
}`

**Comment by OmriGM** [comment]
I think this bug can be fixed in react-components/table: https://github.com/react-component/table/tree/master/src

**Comment by DaoxingHuang** [comment]
I will research more ,and PR will be pulled in next days.

**Comment by perfocal-tech** [comment]
Following 👍👍

**Comment by SachinCoder1** [comment]
Hi, is anyone working on it? i am new to open source, how do i get started?

**Comment by shoaibshebi** [comment]
Hi maintainers, please assign me the issue I have a solution to it
Thanks

**Comment by edc-pl** [comment]
This issues is still existing in 4.22.6.

The sticky header overlapped table shadow when the `fixed: right` removed.

Reproduced in
https://codesandbox.io/s/fixed-header-and-scroll-bar-with-the-page-antd-4-22-6-forked-rikgks?file=/demo.js

**Comment by liuycy** [comment]
anyone working on it ? I will try fix it.
