### ISSUE TITLE
Drawer autoFocus 

### ISSUE THREAD

**Issue by gschattenhofer** [ant-design/ant-design#28097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When drawer opens, focusing on the element generates unexpected and/or unwanted UI behaviour. Specially if Drawer is positioned absolute in a specific container.

### What does the proposed API look like?
Have a prop to disable autoFocus when drawer opens:
`autoFocus={false}`

```
<Drawer
  visible={this.state.visible}
  getContainer="#drawer-container-selector"
  style={{ position: "absolute" }}
  autoFocus={false}
>
  <p>Drawer Content</p>
</Drawer>
```

**Comment by baxtergu** [comment]
Not familiar how to test dom focus state properly. Anyone have some ideas?

**Comment by baxtergu** [comment]
Is there anyone can help with reviewing the [related PR🚀](https://github.com/ant-design/ant-design/issues/28097) in rc-drawer repsitory first?

**Comment by ulion** [comment]
ant-design still using v4.3 but until v4.4.0 this is fixed in rc-drawer.

**Comment by baxtergu** [comment]
> 4.17 is ready to be released, it will contain that fix.

it might need some sync update in ant-design docs either?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/31987#discussion_r700687847

**Comment by baxtergu** [comment]
fixed in https://github.com/react-component/drawer/pull/202

> [#31987 (comment)](https://github.com/ant-design/ant-design/pull/31987#discussion_r700687847)

**Comment by tommasini** [comment]
Hello, for who doesn't want to upgrade for the 4.17 alpha, can get the fix of the drawer here: 
- https://github.com/tommasini/ant-design/tree/Drawer-fix

Antd Version: 4.015 with the drawer auto focus

LYALL <3
