### ISSUE TITLE
Steps 组件宽度计算不准确

### ISSUE THREAD

**Issue by dian533** [ant-design/ant-design#281]
在使用过程中发现下面两个问题，请看下，谢谢~

1. 当Steps的父级元素也是动态渲染的(React中的元素)时，step的宽度计算不出来
2. 当step只有两个时，计算出来的宽度不准确

**Comment by zhujun24** [comment]
举个例子或者截图看看

**Comment by YuhangGe** [comment]
@dian533 第1点能给个具体例子不

**Comment by dian533** [comment]
已经线下沟通给例子哈~

**Comment by yiminghe** [comment]
fixed 0.9.1
