### ISSUE TITLE
Select component example: default value a10 cannot be removed

### ISSUE THREAD

**Issue by lfpkkk** [ant-design/ant-design#28100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/85uij?file=/index.js:216-248)

### Steps to reproduce
in line 10, change `i < 100000` to `i < 10000`

### What is expected?
selection of a10 should have a cross icon to click to remove like other selections.

### What is actually happening?
selection of a10 doesn't have a cross icon to click to remove like other selections.

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | react@16.14.0 |
| System | windows 10 |
| Browser | chrome 87.0.4280.66 (Official Build) (64-bit) |

**Comment by afc163** [comment]
You cannot remove a disabled option, it is by designed.
