### ISSUE TITLE
Official Demo tsx compile support

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#28103]
We should make tsx compile work with Demos to find out ts definition error quickly.

cc @ant-design/ant-design-collaborators

**Comment by paranoidjk** [comment]
+1
https://github.com/ant-design/ant-design/pull/28304#pullrequestreview-552092214

**Comment by paranoidjk** [comment]
another bug case https://github.com/ant-design/ant-design/pull/28102
