### ISSUE TITLE
RangePicker 中使用showTime后体验问题

### ISSUE THREAD

**Issue by Trible-ccb** [ant-design/ant-design#2810]
#### 本地环境
- antd 版本:1.10.0
- 操作系统及其版本： win32 x64 6.1.7601
- 浏览器及其版本: chrome 51.0.2704.106 
#### 你做了什么？

1、使用RangePicker发现已经选择好日期和时间，但是点击了日期框外围区域后日期框隐藏了，而已经选好的日期没有被填到框框中。
2、在RangePicker中如果本来就有开始结束时间，再次点击时间时候结束时间被清空。
3、RangePicker中使用disabledDate属性，对时分秒无效。
#### 你期待的结果是：

1、点击日期框外面区域效果等同于点击确定按钮。
2、按顺序覆盖选择的时间。
3、时分秒的禁用效果同日期禁用效果一样生效。

**Comment by afc163** [comment]
1. 目前的逻辑是点击确定才会更新。
2. 目前的逻辑确实是这样，暂时不改了。
3. 2.x 上现在支持 RangePicker[disabledTime]。
