### ISSUE TITLE
Layout.Sider增强拖拽宽度

### ISSUE THREAD

**Issue by gametheworld** [ant-design/ant-design#28101]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
drawer在弹出后，可以任意拖动宽度，在ui上更的为项目交互和使用场景更加宽广

### What does the proposed API look like?
drawer可以加入配置是否开启随意拖动宽度

**Comment by theprimone** [comment]
这样的话，不应该能调整宽高和位置才行吗？不过这样的场景我都想不出来，一般来说直接给定宽高就行了。

**Comment by gametheworld** [comment]
> 这样的话，不应该能调整宽高和位置才行吗？不过这样的场景我都想不出来，一般来说直接给定宽高就行了。

我写错了，。。。。应该是Layout.Sider 这个组件能拖拽宽度

**Comment by theprimone** [comment]
绝了，我当成 Modal 了 :joy: 不过这个需求我觉得也没太大必要啊，不然还得根据宽度适配。

**Comment by afc163** [comment]
这个需求比较小众，应该不会支持。

**Comment by boringtu** [comment]
@afc163 这不是小众不小众的问题，有需要就要支持啊，你可以不做这个功能，但要支持需要这个功能的人自己做啊。。
你直接给`ant-layout-sider`这个元素写死了行内样式：`flex: 0 0 200px; max-width: 200px; min-width: 200px; width: 200px;`，这别人怎么玩儿。。切忌写行内样式啊，你这么一来，我改都改不了了。。
