### ISSUE TITLE
Form组件labelCol适配

### ISSUE THREAD

**Issue by jzyzxx** [ant-design/ant-design#28109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不同分辨率下Form-item label长度适配

### What does the proposed API look like?
labelWidth:200px,宽度固定

**Comment by afc163** [comment]
labelCol 支持响应式布局配置。

**Comment by jzyzxx** [comment]
> labelCol 支持响应式布局配置。

正因为自适应宽度,导致低屏幕分辨率下部分文字被隐藏

**Comment by jzyzxx** [comment]
> labelCol 支持响应式布局配置。

希望能灵活些,也能设置固定宽度,余下部分瓜分宽度,类似flex;

**Comment by afc163** [comment]
应该是支持的，这里就是透传到 Col 组件：https://ant.design/components/grid-cn/#components-grid-demo-flex-stretch

**Comment by jzyzxx** [comment]
> 应该是支持的，这里就是透传到 Col 组件：https://ant.design/components/grid-cn/#components-grid-demo-flex-stretch
确实支持flex,但是布局效果达不到想要的效果
```
 layout="horizontal"
 labelCol={{ flex: "100px" }}
wrapperCol={{ flex: 1 }}
```
![1606807235(1)](https://user-images.githubusercontent.com/24405119/100709350-e6a60000-33e8-11eb-99e1-4984154bc8eb.jpg)
希望是水平布局,可以实现吗?

**Comment by whateveryoudo** [comment]
手动设置form-item       display: flex 吧  好像没有flex模式
