### ISSUE TITLE
RangePicker有初始值或者二次选择交互问题

### ISSUE THREAD

**Issue by Leemin0311** [ant-design/ant-design#28104]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有初始值或者二次选择的情况下，选择开始（结束）日期之后，面板会自动跳转到结束（开始）日期所在的月份。比如初始值是2020.11.01-2020.11.30，二次选择想要选择2020.08.01-2020.08.31，但开始日期选择为2020.08.01之后，结束日期的面板会自动跳转到11月，需要调整才能选到8月的日期。

### What does the proposed API look like?
二次选择的时候，不要自动跳转面板到上一次的月份

**Comment by yoyo837** [comment]
请按issue模版反馈问题

**Comment by afc163** [comment]
Duplicate of #27898

**Comment by qing-zhi** [comment]
我也碰到了这个问题，目前的临时的解决办法是：
function onCalendarChange(date) {
    // 待选日期发生变化的回调
    // 如果起始日期选了，将前一次表单的数据清掉，变成这次的起始
    if (date[0] && !date[1]) {
      form.setFieldsValue({
        date: [date[0], ""]
      });
    }
}

Form表单里：
<Form.Item name="date">
        <RangePicker onCalendarChange={onCalendarChange} />
</Form.Item>
