### ISSUE TITLE
antd table 选中行如何取消高亮

### ISSUE THREAD

**Issue by minicloudsky** [ant-design/ant-design#28110]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)
table选中行之后不高亮显示(产品经理提的需求，我看了下antd table文档后没看到如何取消高亮的部门)

### What does the proposed API look like?
期望用户在选中行之后，是否高亮可以实现自定义设置

**Comment by afc163** [comment]
通过全局样式覆盖或者修改对应的 less 变量。

**Comment by xrkffgg** [comment]
可以用过样式修改 selected 的 background 就行。
