### ISSUE TITLE
Tree组件在未来的版本中能否将子节点的checkbox的选中状态对外暴露一个受控属性

### ISSUE THREAD

**Issue by poordagandhercat** [ant-design/ant-design#28115]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如子节点的checkbox可以实现单选

### What does the proposed API look like?
你们都是大哥，你们看着办

**Comment by afc163** [comment]
使用 checkedKeys 进行控制即可，比如单选的话，控制 checkedKeys 的长度不超过 1。

**Comment by poordagandhercat** [comment]
谢谢，提这个问题的时候没想到怎么弄，上了个厕所回来捣鼓了几分钟就弄出来了😂，丝丝的尴尬

发自我的iPhone
