### ISSUE TITLE
[Image] placeholder 的 demo 点击后会出现嵌套显示

### ISSUE THREAD

**Issue by stygian-desolator** [ant-design/ant-design#28111]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-mbldrp?file=index.js](https://stackblitz.com/edit/react-mbldrp?file=index.js)

### Steps to reproduce
step1. 点击 reload 按钮

step2. 点击 placeholder 元素

### What is expected?
1. 点击 `placeholder` 时是否应该禁止`Image` 元素自身的点击事件触发？
2. 或者文档站中更换 `placeholder` 为 `<img src={} />`

### What is actually happening?
出现嵌套的 Image 元素
![image](https://user-images.githubusercontent.com/73412177/100711037-a98f3d00-33eb-11eb-9b9a-a93d9899c965.png)

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | ^16.9.44 |
| System | Mac OS |
| Browser | Chrome |

**Comment by shaodahong** [comment]
嗯，可以优化下，关闭文档 `Placeholder` 的 preview
