### ISSUE TITLE
Сonfirmation of selection in Select component by "Tab"(or others) button.

### ISSUE THREAD

**Issue by german-st** [ant-design/ant-design#28118]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?  
Hello.

Often for quick filling of the form and convenience of work, it is required that after a search in the list (Select) by clicking on the "Tab" button, the selected value is confirmed and immediately transition to the next field on the form.

At the current moment, confirmation occurs only by the "Enter" button. Is it possible to somehow bind to the "Tab" button or implement a new props to indicate the buttons array by which the selection will be confirmed in the <Select> component.

Thanks in advance and many thanks for the great library.

### What does the proposed API look like?  
I propose to make a new props for the Select component of the array type, indicating the names or codes of the buttons.  
Example:   
New prop: **confirmButtonKeys: string[]**  
Example usage:   
```<Select
      confirmButtonKeys: ['Enter', 'Tab']      //or ['13', '9']
      loading={loadUserList}
      allowClear
      showSearch
      style={{ width: '100%', minWidth: 400 }}
      optionFilterProp="children"
      onClear={clearContact}
      onSelect={(sel) => selectedContact(sel)}
      filterOption={(input, option) =>
        option.children.toLowerCase().indexOf(input.toLowerCase()) > -1}
    >
        {contactsList}
</Select>
```

**Comment by afc163** [comment]
That is a side requirement we may not provide support in official way.

**Comment by german-st** [comment]
****

> That is a side requirement we may not provide support in official way.

Thanks. Excuse me, but could you suggest somehow you can solve this for me myself? I would be grateful for the help.
