### ISSUE TITLE
set className in cascader, but classname disappeared after compilation

### ISSUE THREAD

**Issue by free-leaves** [ant-design/ant-design#28113]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
<Cascader
    className='colContent'
   ...
...
</Cascader>

### What is expected?
classname will appear after compilation

### What is actually happening?
classname disappeared after compilation

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | "react": "^16.13.1", |
| System | mac os catalina |
| Browser | google |

**Comment by free-leaves** [comment]
![image](https://user-images.githubusercontent.com/23214175/100718772-afd6e680-33f6-11eb-84cf-fb224accace1.png)

**Comment by yoyo837** [comment]
https://codesandbox.io/s/jiben-antd491-forked-0h2tt?file=/index.js

It works.

**Comment by free-leaves** [comment]
It may be that I didn’t describe it clearly. It’s no problem to edit locally or online, but the classname disappears after I package it with the packaging tool. @yoyo837

**Comment by free-leaves** [comment]
I also discovered this problem after packaging and publishing

**Comment by yoyo837** [comment]
Could you provide a reproduction demo repo?

**Comment by free-leaves** [comment]
My general structure is like this, and then I use the packaging tool to package and release, and then the classname disappears，I think this should be related to typing, not to specific examples.I don’t know why it is filtered out when packing
<Form.Item
    name="name"
    rules={}
>   
      <Cascader
          options={data}
          onChange={() => {}}
          className='colContent'                    
      >
         <Input />
    </Cascader>
<Form.Item/>

**Comment by free-leaves** [comment]
It should be judged to use the example you just showed me to package and release

**Comment by yoyo837** [comment]
The compilation result is affected by compilation tools such as `webpack` and their configuration. If no reproduction repo or more information, we can't do anything.

**Comment by free-leaves** [comment]
Okay, thanks for your help
