### ISSUE TITLE
[需求]下拉框、级联等类似组件希望能够提供复制功能

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#28114]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们的表单提供了很多下拉列表，客户很希望能够将下拉列表的内容复制出来
应用到其他地方，
参见
https://chu1204505056.gitee.io/vue-admin-beautiful-pro/#/vab/form/comprehensiveForm
他的下拉列表内容是可以复制的

### What does the proposed API look like?
下拉列表内容可以复制

**Comment by afc163** [comment]
Duplicate of #28989
