### ISSUE TITLE
TabPane tab渲染为Input时 无法输入空格

### ISSUE THREAD

**Issue by chris-paul** [ant-design/ant-design#28119]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xinzengheguanbiyeqian-antd491-forked-2qdyg?file=/index.js)

### Steps to reproduce
输入框输入空格

### What is expected?
输入框可以输入空格

### What is actually happening?
输入框不可以输入空格

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 16.1.1 |
| System | window 7 |
| Browser | chrom 86.0.4240.198 |

**Comment by afc163** [comment]
https://codesandbox.io/s/xinzengheguanbiyeqian-antd491-forked-9l22x
