### ISSUE TITLE
Is possible Table loading display spinning only one Row

### ISSUE THREAD

**Issue by Korn704** [ant-design/ant-design#28116]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am finding at Table API
I am not found loading on one row

### What does the proposed API look like?
onRow with remote display spinner on specific row

```
onRow={(record) => {
  return record.id === itemId ? <Spinner /> : record
}}
```

or

```
<Table rowLoading={rowId} />
```

**Comment by afc163** [comment]
目测可以用 components 覆盖 body.row 来实现。

**Comment by Korn704** [comment]
Show example in my context, plz

```
component={{
  body: {
    row: record.id === itemId ? <Spinner> : record
  }
}}
```

Where can I get `record` prop to read data row by row

**Comment by afc163** [comment]
```jsx
const CustomRow = (props) => {
  console.log(props.children); // see it
  return <div />;
};

ReactDOM.render(
  <Table
    columns={columns}
    components={{ body: { row: CustomRow } }}
    dataSource={data}
  />,
  mountNode,
);
```
