### ISSUE TITLE
Upload component select file without dialogbox

### ISSUE THREAD

**Issue by genc6541** [ant-design/ant-design#28128]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7vury)

### Steps to reproduce
I want to give file to upload component without selcting from dialogbox. How can I achive giving file from folder automatically not opening dialogbox?

### What is expected?
It should choose and get file from folder giving path without opening and selecting dialogbox.

### What is actually happening?
I cannot achive giving file or blob with path to upload component. 

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser |  Chrome 86.0.4240.198 |

**Comment by afc163** [comment]
> I want to give file to upload component without selcting from dialogbox. How can I achive giving file from folder automatically not opening dialogbox?

It can't be done due to browser limit.
