### ISSUE TITLE
Textarea showCount style improvement while using Form validator

### ISSUE THREAD

**Issue by yangjunhan** [ant-design/ant-design#28123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-powsmd?file=index.js](https://stackblitz.com/edit/react-powsmd?file=index.js)

### Steps to reproduce
NA

### What is expected?
Maybe error help should be right at the bottom of the textarea, followed by character count.

### What is actually happening?
Error help is pushed down by the character count.
![image](https://user-images.githubusercontent.com/50307523/100737375-0fd98700-340f-11eb-807f-3063fe1363ad.png)

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.0 |
| System | mac v10.15.7 |
| Browser | v86 |

**Comment by afc163** [comment]
Fixed in #28130
