### ISSUE TITLE
"normalize" prop of Form.item not support async method

### ISSUE THREAD

**Issue by newketom** [ant-design/ant-design#28129]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-moon-dusb2?file=/src/App.tsx)

### Steps to reproduce
**I want to get base64 string when upload img use "Form.item", so i call an promise method to get file content with base64 encode, but i also get an Promise rather than string with onFinish method**

such as:

```
imgBase64: Promise {<fulfilled>: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAArsA…sAgCQltgFACAtsQsAQFp/A"}
```
![image](https://user-images.githubusercontent.com/56467036/100757714-a9159700-3429-11eb-828a-c65c4568cbda.png)

### What is expected?
string encode by base64

### What is actually happening?
Promise

| Environment | Info |
|---|---|
| antd | undefined |
| React | 18 |
| System | Win10 |
| Browser | chrome87 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26451#issuecomment-697410283
https://github.com/ant-design/ant-design/issues/20542#issuecomment-569629427

**Comment by zombieJ** [comment]
`normalize` should not be async since user will be not able to update value since in controlled. We should doc for this.
