### ISSUE TITLE
数据为空时Table固定列出现重复提示

### ISSUE THREAD

**Issue by ericshao** [ant-design/ant-design#2812]
#### 本地环境

- antd 版本:1.10.0
- 操作系统及其版本:OS X 10.11.6
- 浏览器及其版本:Chrome52

#### 你做了什么？

引入了antd Table，并将第一列设置为fixed: 'left'

#### 你期待的结果是：

当没有数据时，固定列中无需显示任何提示

#### 实际上的结果：

没有数据时，固定列中重复显示了“暂无数据”提示
<img width="1314" alt="2016-08-23 1 25 22" src="https://cloud.githubusercontent.com/assets/2464931/17875754/6da33b4c-6907-11e6-9bc7-034c34bd36f8.png">

**Comment by ericshao** [comment]
“暂无数据”提示信息横向位置偏移，未居中

**Comment by benjycui** [comment]
@ddcat1115 其实我觉得暂无数据这个提示可以用 div 实现，而不是用 td。

**Comment by ericshao** [comment]
暂无数据的提示信息：图标+文案最好能自定义。某些场景下没有数据是“好事”，一副哭脸不太应景；也有些场景下没有数据的话要给用户更多的指向性提示，比如提示用户应该“新建...”

**Comment by afc163** [comment]
@ericshao 可以自定义的。

**Comment by juanpengke** [comment]
@afc163  重复出现的没有数据提示，可以修改？
