### ISSUE TITLE
table 表格rowClassName的使用方式

### ISSUE THREAD

**Issue by atonesapple** [ant-design/ant-design#28135]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
无法解决问题，文档表述不清不楚，怎么设置都没效果

### What does the proposed API look like?
一个页面多个表格，设置单独的rowClassName样式

**Comment by atonesapple** [comment]
什么玩意，什么问题都不回，摆明就是机器人设置。。。。

**Comment by atonesapple** [comment]
没人了么，官方的人，真垃圾，什么都搞个机器人。。。鄙视

**Comment by HuaRin** [comment]
![](https://user-images.githubusercontent.com/75078646/100826304-fed35900-3494-11eb-9fd0-ecd551b09dcd.gif)

**Comment by yoyo837** [comment]
大部都不是全职维护，精力有限，希望能提供更多信息来减少沟通成本，而不是你丢一句话，大家都想着法的来追着你问你要什么样的结果。

比如：什么问题无法解决问题，哪里文档表述不清不楚，做了什么设置都没效果？

“一个页面多个表格，设置单独的rowClassName样式”太抽象了。

**Comment by yoyo837** [comment]
至少个人使用`rowClassName`是有效果的，你那边到底为什么没效果，只有你提供更多信息才能判断，不然只能凭空想象。

**Comment by suwu150** [comment]
文档中没找到关于rowClassName具体该怎么用，只是在文档中说明是行类设置，希望给出具体的一个示例代码

**Comment by yoyo837** [comment]
`function(record, index): string` 这样用的。

**Comment by yoyo837** [comment]
```jsx
rowClassName={(record, index) => {
  // record 当前行，index 行索引
  return 'xxx'; // xxx 会附加到tr上
}}
````

**Comment by suwu150** [comment]
@yoyo837  非常感谢，我在其他的issue里边找到了，谢谢，希望能够在官网文档中添加一个演示案例
