### ISSUE TITLE
Provide `labelRender` for <Select>

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#28138]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
完全自定义`<Select>`中label的渲染。现在已经有`tagRender`了，但是还不够。
1. 只能在tag和multiple下起作用
2. 只渲染input框中的内容

我希望有`labelRender`做到一下几点：
1. 区分 input框和下拉列表框 甚至 搜索中变灰的label的内容的渲染。
2. 渲染不在options中的value

对于第二点：
当前实现，如果在options中找不到`value`，则直接渲染`value`本身了。
比如：我希望能渲染成 `<未知: ${value}>`。我不希望根据`value`，动态的增加options选项，因为我不希望用户能选择这一项，也不希望增加一些累赘的项目在下列列表框中。我也不希望程序自动更正`value`本身，因为虽然`value`不在`options`中，它本身确实是有效的内容，我希望用户不动`value`就保持不变。

关于实现：
就我所了解的，`labelRender`主要负责value转换成文本，虽然实际返回类型可以是ReactNode。
`tagRender`还是保持，负责加上`<Tag>`。类似这样调用, 
```
var lable = labelRender(value);
var tag = tagRender({label});
```

### What does the proposed API look like?
```tsx
function lableRender(value:any, where: 'input'|'list'|'zzz')
{
    return value + '';
}

return <Select labelRender={labelRender}/>
```

**Comment by afc163** [comment]
你可以看看 optionLabelProp，能做到第一点。

第二点合并到 https://github.com/ant-design/ant-design/issues/27678
