### ISSUE TITLE
Please add onClick to Message component

### ISSUE THREAD

**Issue by bkiggen** [ant-design/ant-design#28131]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The Notification has an onClick property in the API but the Message component does not. I would like to be able to run a function on click of the message (e.g. closing the message). 

### What does the proposed API look like?
I'm not sure what the code for Message looks like, but I assume adding a click handler would be pretty straightforward.

**Comment by afc163** [comment]
supported in https://github.com/ant-design/ant-design/pull/28148
