### ISSUE TITLE
关于列表里面 Image组件fallback属性使用后出现的错误

### ISSUE THREAD

**Issue by mannymu** [ant-design/ant-design#28137]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mannymu/mannymu.git](https://github.com/mannymu/mannymu.git)

### Steps to reproduce
项目启动后，点击  “默认图”  的删除按钮， 发现删除以后，后面的图变为了默认图。

### What is expected?
后面的图正常显示

### What is actually happening?
删除后，后面的图变为了，默认图

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | win10 |
| Browser | chrome最新版 |

---
预计是react的 diff 算法，通过key重复使用了前面的组件，只改变了  props。需要 componentWillReceiveProps 对比变化。更新 state

**Comment by afc163** [comment]
动态增删的列表最好不要使用 index 做 key，你的例子里建议用 src 作为 key。
