### ISSUE TITLE
使用upload上传文件时如何获取文件数据

### ISSUE THREAD

**Issue by sunzd116** [ant-design/ant-design#2813]
#### 本地环境

- antd 版本:
0.14.8
- 操作系统及其版本：
ubuntu16.04
- 浏览器及其版本:
chrome52
#### 你做了什么？

项目里要做一个导入excel的功能，在excel导入时想要将该excel处理成json再发送，请问在beforeUpload获取文件的内容

**Comment by benjycui** [comment]
为何不尝试把 beforeUpload 的参数 console.log 出来看看？

**Comment by sunzd116** [comment]
参数是File对象，使用FileReader读取，设置onload 。解决啦 谢谢
