### ISSUE TITLE
table 组件种的onFilter和selectedRows需完善

### ISSUE THREAD

**Issue by heavenlian** [ant-design/ant-design#28142]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了，我先全选，或者选择了一部分列表选项时，使用过滤表格，比如失效，生效的表格时，获取的选择了数据，仍然是之前全选的的数据。可以获取新的数据。

### What does the proposed API look like?
onFilterDropdownVisibleChange 不仅给visible的状态，还需要filters，选中了的状态返回了或者直接触发rowSelection的onChnage事件。

**Comment by afc163** [comment]
filters 可以通过受控组件自行通过 state 获取。
