### ISSUE TITLE
table的selection的columnWidth不起作用

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#28146]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-shadow-y2l7q?file=/src/App.js)

### Steps to reproduce
链接中的代码已经设置columnWidth为20，但是selection的checkbox依然是32的宽度

### What is expected?
希望可以改小table的selection的checkbox的宽度

### What is actually happening?
设置20，未生效

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.0 |
| System | mac |
| Browser | chrome  86.0.4240.111 |

**Comment by afc163** [comment]
checkbox 16px 宽度加上两个 padding 8px 最小已经是 32px 了，如果还需要更小需要手动覆盖 padding 了。
