### ISSUE TITLE
Antd Checkbox.Group 增加垂直方向

### ISSUE THREAD

**Issue by FontEndArt** [ant-design/ant-design#28149]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前需要一个checkbox的垂直列表

但是antd的Checkbox.Group仅提供了横向的，垂直需要搭配Row和Col实现，或者改变其class的样式

主要问题在于一个样式
.ant-checkbox-wrapper   .ant-checkbox-wrapper {
    margin-left: 8px;
}

希望增加一个api用于调整其排列方式

### What does the proposed API look like?
类似Radio.Group即可
```js
···
const radioStyle = {
      display: 'block',
      height: '30px',
      lineHeight: '30px',
    };
···
<Radio.Group>
        <Radio style={radioStyle} value={1}>
          Option A
        </Radio>
</Radio.Group>
···
```

**Comment by xrkffgg** [comment]
```css
display: grid;
```

改下这个就可以了吧

**Comment by FontEndArt** [comment]
@xrkffgg  谢谢，可以用，需要加在 Checkbox.Group 上。如下：
```html
<Checkbox.Group style={{ display: 'grid' }}>
    <Checkbox value={1}>A</Checkbox>
    <Checkbox value={2}>B</Checkbox>
    <Checkbox value={3}>C</Checkbox>
</Checkbox.Group>
```

**Comment by qingdi** [comment]
`<a-checkbox-group
                    name="checkboxgroup"
                    :options="checkBoxOption"
                    style="display:grid"
                  />`
