### ISSUE TITLE
Table filters convert the values to string by default.

### ISSUE THREAD

**Issue by Meowu** [ant-design/ant-design#28144]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kekongdeshaixuanhepaixu-antd491-forked-bix26?file=/index.js)

### Steps to reproduce
1. define [{ text: 'London', value: 1 }, { text: 'New York', value: 2 ]} as filters in the last column.
3. listen to the onChange event
2. filter table data by London
4. inside the handleChange callback, check the 'filters' parameter, value of filters.address should be [1] instead of ['1]

### What is expected?
The type of filter value should be number.

### What is actually happening?
The type of filter value converted to string.

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 16.8 |
| System | macOS 10.14.6 |
| Browser | Chrome Version 85.0.4183.83 (Official Build) (64-bit) |

---

I have explored the source code and found that all filter values were convert to string and then passed as prop key to MenuItem.

https://github.com/ant-design/ant-design/blob/a3aec7b057234eb15962429b8410adff41dca7ba/components/table/hooks/useFilter/FilterDropdown.tsx#L56

Why we need to convert it to string here.

Prop key of MenuItem does not have to be string.

**Comment by Meowu** [comment]
I will send a PR to fix this.

**Comment by asadcode123** [comment]
@Meowu i would love to submit the PR for this issue.

**Comment by asadcode123** [comment]
@Meowu @afc163 I've fix this issue and created the PR as well.

**Comment by Meowu** [comment]
> @Meowu @afc163 I've fix this issue and created the PR as well.

I appreciate that.
But it seems that the pr won't fix the problem I have met.

Beside, I have found another issue when I tried to fix this problem.

We need to add more test cases.

**Comment by asadcode123** [comment]
@Meowu  and what was that issue ??

**Comment by Meowu** [comment]
@asadcode123 If we pass prop `filtered` to a column, the related filters don't get checked. I am working on fixing both of the issues.They are related in a way.

**Comment by Meowu** [comment]
@afc163 I have send a PR to fix the problems I found.Please review.
