### ISSUE TITLE
babel-runtime?

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#2814]
使用 babel-runtime 如何。。这样就不用 polyfill 了，而且用 ES2015 的 API 写起来也比较舒服。

**Comment by afc163** [comment]
搞之。不过是不是应该直接加到 atool-build 中去？

**Comment by benjycui** [comment]
See: https://github.com/dora-js/dora/issues/56

@pigcan 不放进 atool-build 的原因是？

**Comment by pigcan** [comment]
会放进去的 下个版本

**Comment by afc163** [comment]
@pigcan

**Comment by afc163** [comment]
https://github.com/ant-tool/atool-build/issues/191
