### ISSUE TITLE
Variable @btn-padding-base is undefined

### ISSUE THREAD

**Issue by sirkeng** [ant-design/ant-design#28141]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/migration-v4](https://ant.design/docs/react/migration-v4)

### Steps to reproduce
I update from ant v.3.26.6 to 4.9.1 follow this step

npx -p @ant-design/codemod-v4 antd4-codemod src

antd4-codemod src

then update antd v.4.9.1

then npm start 

then get error

### What is expected?
Successful compile

### What is actually happening?
Failed to compile.

./src/styles/wieldy.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-7-3!./src/styles/wieldy.less)

  line-height: @btn-line-height;
  .btn;
^
Variable @btn-padding-base is undefined
      in /Users/my_name/workspace/my_project_name/node_modules/antd/lib/button/style/index.less (line 23, column 2)

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
It should be documented, thx.

https://github.com/ant-design/ant-design/commit/39122bd3d61fc2b289d5eb3e9aa178e24b0d9d73

**Comment by sirkeng** [comment]
> It should be documented, thx.
> 
> [39122bd](https://github.com/ant-design/ant-design/commit/39122bd3d61fc2b289d5eb3e9aa178e24b0d9d73)

Thank you so much, I resolved this just declare @btn-padding-base in my template project.
