### ISSUE TITLE
Select选择器的maxTagTextLength无效

### ISSUE THREAD

**Issue by 97Yates05** [ant-design/ant-design#28152]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/select-cn/](https://3x.ant.design/components/select-cn/)

### Steps to reproduce
select选择器maxTagTextLength

### What is expected?
期望maxTagTextLength有效

### What is actually happening?
无效

| Environment | Info |
|---|---|
| antd | 3.26.19 |
| React | 16.8.4 |
| System | mac |
| Browser | 谷歌87.0.4280.67 |

**Comment by afc163** [comment]
see https://github.com/ant-design/ant-design/pull/19868
