### ISSUE TITLE
DatePicker bug

### ISSUE THREAD

**Issue by gongfuxiaocai** [ant-design/ant-design#28155]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
点击picker的header，切换到range-year，然后选择今天之前的年份，就会出现输入框有日期，且input的value有值

### What is expected?
期望年份不可选择

### What is actually happening?
年份可以选择

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/20085964/100871493-585e7680-34db-11eb-96fd-1c06b4338c36.png)

![image](https://user-images.githubusercontent.com/20085964/100871605-7fb54380-34db-11eb-83a9-d114d6259d2b.png)

目前年是可以选择的，既然禁止之前日期，为什么还要可以选？

**Comment by kerm1it** [comment]
给个复现的链接，不明白为什么不能选择之前的日期?

**Comment by gongfuxiaocai** [comment]
https://codepen.io/pen/?&editors=001 可复线，假如我禁止今天之前的日期不可选择，就会出现上述情况

**Comment by gongfuxiaocai** [comment]
https://codepen.io/sorryxc/pen/NWRGoRw?editors=001 这个地址可复现；
我在描述下问题：当我禁止今天之前的日期不可选的时候，我点击header的年，选择1900-1909的时候，默认会把19901203带进去，且value=19901203

**Comment by kerm1it** [comment]
复现了，是个 bug，没有在选年份区间的时候，禁用不能选择的年份区间
