### ISSUE TITLE
table的选择列header不能有效居中

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#28169]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuanzehecaozuo-antd491-forked-0ih0y?file=/index.js)

### Steps to reproduce
官文选择列样例
将列都设置宽度后

### What is expected?
table的选择列header居中

### What is actually happening?
不居中

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 16.12 |
| System | Windows 10 |
| Browser | QQ浏览器10.4.2 |

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-row-selection-custom

这里也对不齐了，两个问题可以一起修。

<img width="308" alt="图片" src="https://user-images.githubusercontent.com/507615/100980964-0a03b300-3581-11eb-8cce-8223cacfd299.png">
