### ISSUE TITLE
select组件virtual虚拟滚动样式不一致

### ISSUE THREAD

**Issue by tianxing0923** [ant-design/ant-design#28166]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pk80t)

### Steps to reproduce
开启虚拟滚动后，滚动条的样式与原生默认样式不一致

### What is expected?
样式保持一致

### What is actually happening?
样式不一致

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | chrome 87.0.4280.66 |

**Comment by afc163** [comment]
> 样式不一致

这样反馈信息不太够，具体哪里不一致，最好提供截图和期望样式的描述。

**Comment by tianxing0923** [comment]
![image](https://user-images.githubusercontent.com/4628543/100976665-d1f97180-357a-11eb-972b-43b1bc0de66d.png)

**Comment by afc163** [comment]
现在滚动条是 antd 自己照着 macos 的滚动条实现的，对各个平台做兼容样式感觉不太划算。

https://github.com/react-component/virtual-list/blob/f1d3c574749128640e967436458e596be11b48cb/src/ScrollBar.tsx#L217-L227

@zombieJ 来看看有没有必要做兼容。

**Comment by tianxing0923** [comment]
![image](https://user-images.githubusercontent.com/4628543/100977367-d83c1d80-357b-11eb-82eb-c18bec4eba64.png)
![image](https://user-images.githubusercontent.com/4628543/100977702-500a4800-357c-11eb-8476-4c42c5340b29.png)
看dom结构，开启虚拟滚动后把overflow-y: auto改成了hidden，我尝试着改成overflow-y: auto后，原生滚动条出现，并且是可以正常使用的，不知为何要做成假的scrollbar

**Comment by afc163** [comment]
虚拟滚动有很多特殊情况要处理。

**Comment by zombieJ** [comment]
原生滚动事件先于渲染触发，所以会有滚动白屏的问题。使用模拟滚动条让渲染保持同步。具体可以看看这篇文章：
https://zhuanlan.zhihu.com/p/237996796
