### ISSUE TITLE
atoolBuild打包之后的路由拆分的CHUNCK文件，发现注释没有去除

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2816]
antd版本：1.9.1
"react": "^15.0.2",
"react-dom": "^15.0.2",

atoolbuild版本0.7.x 请问组件注释打包之后没有被去除，官方是否提供了类似插件，去除注释

**Comment by afc163** [comment]
atool-build 问题，建议去 atool-build 的 issue 提问。
若是 webpack 问题，建议去 webpack 等论坛提问。
