### ISSUE TITLE
antd Select组件 Option里的值前后有空格则会出现崩溃现象，希望官方可以加入去除空格的操作

### ISSUE THREAD

**Issue by 521guyu** [ant-design/ant-design#28163]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
默认option.props.children的类型是string,使用indexOf,toLowerCase字符串的方法都没问题。但是一旦Option标签里显示值的前后有空格则option.props.children的类型则会成为array类型。这时如果使用了string的方法则会报错导致页面崩溃。
例如:
`
    const name="maz";
    <Otion>  {name}  </Option> //<Otion>{name}</Option>这样就没问题
`
这时option.props.children就会变为数组类型['','maz',''];
最小可复现代码
https://codesandbox.io/s/enqcp?file=/index.js

### What does the proposed API look like?
正则自动匹配当前筛选项是否包含空格自动去除。考虑到有的需求需要保留空格，可以给filterOption加一个属性是否去除空格。

**Comment by 521guyu** [comment]
> 你好@ 521guyu。请通过分叉此链接https://u.ant.design/codesandbox-repro或最小的GitHub存储库来提供在线复制。`Need Reproduce`如果在7天内没有任何活动，则带有标记的问题将被关闭。
> 
> 你好@ 521guyu，我们需要你提供一个在线的重现实例煞于我们帮你排查问题。你可以通过单击[此处](https://u.ant.design/codesandbox-repro)创建一个codeandbox或提供一个最小化的GitHub仓库。7期限未跟进的issue将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/enqcp?file=/index.js

**Comment by 521guyu** [comment]
> 你好@ 521guyu。请通过分叉此链接https://u.ant.design/codesandbox-repro或最小的GitHub存储库来提供在线复制。`Need Reproduce`如果在7天内没有任何活动，则带有标记的问题将被关闭。
> 
> 你好@ 521guyu，我们需要你提供一个在线的重现实例煞于我们帮你排查问题。你可以通过单击[此处](https://u.ant.design/codesandbox-repro)创建一个codeandbox或提供一个最小化的GitHub仓库。7期限未跟进的issue将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
https://codesandbox.io/s/enqcp?file=/index.js

**Comment by afc163** [comment]
还是判断一下好了，不做太多特殊处理。

```jsx
(Array.isArray(option.props.children) ? option.props.children.join('') : option.props.children).toLowerCase()
```
