### ISSUE TITLE
Select 下拉，在输入框有值以后，不能复制

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#28175]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
无法选中输入框中文字来复制

### What is expected?
希望可以选中输入框中文字来复制文本

### What is actually happening?
不能选中输入框的中文字并复制

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 16.13.1 |
| System | Win7 64位 |
| Browser | 版本 81.0.4044.69（正式版本）beta （64 位） |

---
有些客户希望复制该文本去其他的地方查询，希望能够提供这样的支持，或者有没有什么样式能够支持

**Comment by Catsbe** [comment]
![image](https://user-images.githubusercontent.com/25682800/100991919-7e911e80-358e-11eb-8fcd-94d2dc93aef1.png)
希望能够像这个图一样的方式，就聚焦时，输入框的值还在而不是无法选中

**Comment by xrkffgg** [comment]
我看 rc-select 有一个 combobox mode 可以，antd 的 select  没有引入个 mode

**Comment by xrkffgg** [comment]
same like https://github.com/ant-design/ant-design/issues/28114

**Comment by Catsbe** [comment]
我觉得这个用户体验真的不太好，希望官方能够支持这个功能，毕竟有时候客户就是需要选中的值去查询东西，如果这个不能复制，就真的有点反人类了。希望尽快支持

**Comment by timelessover** [comment]
可以尝试一下将 `.ant-select-single .ant-select-selector .ant-select-selection-item` 样式下的 `user-select:none`覆盖掉。

**Comment by zombieJ** [comment]
merge into #28114

**Comment by afc163** [comment]
Duplicate of #28989

**Comment by german-st** [comment]
> 可以尝试一下将 `.ant-select-single .ant-select-selector .ant-select-selection-item` 样式下的 `user-select:none`覆盖掉。

Hello. Unfortunately this does not work (
Tried to watch a lot of places. But putting **user-select: text;** doesn't help either. Cannot select text (

Here's my example:
![image](https://user-images.githubusercontent.com/30233260/105683079-4958db00-5f04-11eb-90a3-450c5fd94ef1.png)

@afc163 @zombieJ @timelessover 
Please reopen the issue or give an exact example. 
Thank you very much in advance and thanks for the library!

**Comment by Haru1990** [comment]
@german-st Have your find method to solve this problem?

**Comment by jun58** [comment]
[a simple demo](https://stackblitz.com/edit/antd-design-select-copy-demo?file=demo.js)
@slcyyy

**Comment by ahuiahui** [comment]
> [a simple demo](https://stackblitz.com/edit/antd-design-select-copy-demo?file=demo.js) @slcyyy

This method works, but options cannot be selected again

**Comment by ahuiahui** [comment]
> > [a simple demo](https://stackblitz.com/edit/antd-design-select-copy-demo?file=demo.js) @slcyyy
> 
> This method works, but options cannot be selected again, searchValue cannot be modified

filterOption={(input, option) => option.children.includes(input)}
change to
**filterOption={() => true}**

**Comment by wxzhhh** [comment]
> > [a simple demo](https://stackblitz.com/edit/antd-design-select-copy-demo?file=demo.js) @slcyyy
> 
> This method works, but options cannot be selected again, searchValue cannot be modified

In the demo we do not have to filter for options that have the same value as searchValue to show
**Modify filteroption in demo code**：filterOption={(input, option) => option.children}
on this way, searchValue can be modified and options can be selected again
