### ISSUE TITLE
Table with rowSelection error，it should be more strong。带选择框的 Table 应该更健壮。

### ISSUE THREAD

**Issue by yanguoyu** [ant-design/ant-design#28174]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ivroes?file=index.js](https://stackblitz.com/edit/react-ivroes?file=index.js)

### Steps to reproduce
1：随便勾选几个
2：点击清空
3:  再次勾选会报错 js crash

### What is expected?
再次勾选不会报错

### What is actually happening?
js crash

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.0 |
| System | mac os |
| Browser | chrome |

**Comment by yanguoyu** [comment]
const [mergedSelectedKeys, setMergedSelectedKeys] = useMergedState(selectedRowKeys || [], {

**Comment by afc163** [comment]
👍 来个 PR 吧，再补充一个测试用例。

**Comment by yanguoyu** [comment]
ok

**Comment by yanguoyu** [comment]
[https://github.com/ant-design/ant-design/pull/28193](url)
