### ISSUE TITLE
Upload.Dragger在结合Form表单使用时，如果讲文件拖拽出Upload区域，拖拽文件回自动通过浏览器下载

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design#28170]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
拖拽文件到整个表单区域（除了Upload.Dragger区域），该文件会变成浏览器下载

### What is expected?
应该是没有任何的效果

### What is actually happening?
下载文件

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.12.0 |
| System | MacOs |
| Browser | 70.0 |

**Comment by afc163** [comment]
这个和 antd 没关系，浏览器的默认行为，换任意一个网页都是这样。
