### ISSUE TITLE
Allow both custom tag render and custom selection render in the same Select

### ISSUE THREAD

**Issue by nabramow** [ant-design/ant-design#28179]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Right now I can either customize my selected items using the tagRender prop, which requires I use the options prop, OR I can customize the options in the Select via Select.Option. For example, I want to combine these two features:

<img width="473" alt="Screenshot 2020-12-03 at 11 17 16" src="https://user-images.githubusercontent.com/18261566/100996555-79fe4300-3559-11eb-9da7-5eacfa4338e5.png">
<img width="456" alt="Screenshot 2020-12-03 at 11 16 59" src="https://user-images.githubusercontent.com/18261566/100996632-9306f400-3559-11eb-8911-e1e6c9840ca0.png">

I want each selected item to have a different background color, but I also want each option in the dropdown to have a custom icon next to it. Right now it's only possible with hardcoded CSS adjustments. 

I can do something like this with the CSS:

```javascript
  .ant-select-selection-item {
    &:nth-child(1) {
      background-color: #f9cc37;
    }
  }
```

But then I have to add a TON of code for each selected item, not realistic if there are a lot.

### What does the proposed API look like?
Similar to how tagRender works, but for the options. Alternatively, could add a key to the existing options prop that allows me to add a React element instead of a string?

**Comment by afc163** [comment]
It could be done in this way: https://codesandbox.io/s/dingzhihuitianneirong-antd491-forked-y6j6g?file=/index.js
