### ISSUE TITLE
使用 Carousel走马灯 报错

### ISSUE THREAD

**Issue by Gaopengyi** [ant-design/ant-design#28183]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel-cn/](https://ant.design/components/carousel-cn/)

### Steps to reproduce
import { Component } from "react";
import { Calendar, Carousel } from "antd";
import "antd/dist/antd.css"
const contentStyle = {
  height: '160px',
  color: '#fff',
  lineHeight: '160px',
  textAlign: 'center',
  background: '#364d79',
};
export default class AntdCpt extends Component {

  render() {
    return (
      <div>
        <Calendar/>
        <Carousel autoplay>
          <div>
            <h3 style={contentStyle}>1</h3>
          </div>
          <div>
            <h3 style={contentStyle}>2</h3>
          </div>
          <div>
            <h3 style={contentStyle}>3</h3>
          </div>
          <div>
            <h3 style={contentStyle}>4</h3>
          </div>
        </Carousel>
      </div>
    )
  }
}

### What is expected?
正常没有报错

### What is actually happening?
一旦滑动走马灯组件，就会出现这个错误 Unable to preventDefault inside passive event listener invocation. 

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | macos11.0.1 |
| Browser | chrome |

---
一旦滑动走马灯组件，就会出现这个错误 Unable to preventDefault inside passive event listener invocation.

**Comment by Gaopengyi** [comment]
import { Component } from "react";
import { Calendar, Carousel } from "antd";
import "antd/dist/antd.css"
const contentStyle = {
  height: '160px',
  color: '#fff',
  lineHeight: '160px',
  textAlign: 'center',
  background: '#364d79',
};
export default class AntdCpt extends Component {

  render() {
    return (
      <div>
        <Calendar/>
        <Carousel autoplay>
          <div>
            <h3 style={contentStyle}>1</h3>
          </div>
          <div>
            <h3 style={contentStyle}>2</h3>
          </div>
          <div>
            <h3 style={contentStyle}>3</h3>
          </div>
          <div>
            <h3 style={contentStyle}>4</h3>
          </div>
        </Carousel>
      </div>
    )
  }
}

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/27957
