### ISSUE TITLE
default time of DatePicker in version 4 should also sync millisecond

### ISSUE THREAD

**Issue by mcshaman** [ant-design/ant-design#28188]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0qbfy)

### Steps to reproduce
pick a time, the console will print the millisecond

### What is expected?
my default time is moment("00:00:00.000", "HH:mm:ss.SSS") so I expect the millisecond to be 0

### What is actually happening?
millisecond is a random number

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | ubuntu 20.04 |
| Browser | Firefox 83.0 |

---
This bug was reported and fixed in version 3 (https://github.com/ant-design/ant-design/issues/16660) but appears to have returned with the release of version 4.

**Comment by asadcode123** [comment]
Can i pick this issue and fix this ? @afc163

**Comment by afc163** [comment]
trace #28591
