### ISSUE TITLE
Filter options should only be derived from the data present in the current page 

### ISSUE THREAD

**Issue by jzhao62** [ant-design/ant-design#28184]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j1ti3?file=/index.js)

### Steps to reproduce
- in address column, filter on "London"
- Try to apply another filter on Name column

### What is expected?
- 应该不允许你去filter on Joe，因为没有意义
- 第二个filter显示的option 应该是基于当前这个page，if any filters applied，展示给用户的数据，不仅仅是当前page的data

### What is actually happening?
The "Name" column is allowing you to filter on a value that is not observable to User in current page
- 如果current page 没有给用户显示数据，就不应该提供相应的filter

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.01 |
| System | Ubuntu 20.04 |
| Browser | Chrome: 87.0.4280.66 |

**Comment by jzhao62** [comment]
i dont know if this should be a bug, or an expected behavior. This is sometimes a little bit confusing for users

**Comment by afc163** [comment]
It should be control at app code side, not at antd's side.
