### ISSUE TITLE
Not expected values ​​in onValuesChange method.

### ISSUE THREAD

**Issue by tippillow** [ant-design/ant-design#28185]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-izdsz3-ubydjz?file=index.js](https://stackblitz.com/edit/react-izdsz3-ubydjz?file=index.js)

### Steps to reproduce
1) Open console.
2) Click button "Add field"
3) Clcik button "Add nickname"
4) Delete field.
5) Click button "Submit"
6) Check the differences

### What is expected?
Same values as recieved from onFinish.
users: [];

### What is actually happening?
Not deletes all fields.
users: [nicknames: undefined]
![](https://user-images.githubusercontent.com/55249470/101021017-01f34580-3578-11eb-8ca2-fbbd09fb4ad3.png)

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | Chrome  86 |

---
I am using Form.List inside Form.List and when removing the inner formList onValuesChange() is giving away an unexpected second argument.
form.getFieldsValue() returns the same. But if you call the onFinish() method, then it is correct the value I expected.

![UnFtFxyKMM](https://user-images.githubusercontent.com/55249470/101025640-88128a80-357e-11eb-9427-c458dd4d38be.gif)

**Comment by marianayap** [comment]
@tippillow hello! are you going to work in the issue? and if not @afc163 I would like to work on it

**Comment by afc163** [comment]
@marianayap sure.

**Comment by marianayap** [comment]
@afc163 Is this a issue from this repository? The contribution it will be for Ant-desing?

**Comment by zombieJ** [comment]
@marianayap  https://github.com/react-component/field-form

**Comment by tippillow** [comment]
@marianayap hello! I will not fix the issue.

**Comment by zhaobosky** [comment]
这个问题什么时候可以修复啊

**Comment by AliasT** [comment]
未修复之前可使用：
```ts
// 返回值未经过克隆
form.getFieldsValue(true)
```
获取最新值
https://github.com/react-component/field-form/blob/4fab2919ab87eb7181f4ddeb84facfa0f1daedbf/src/useForm.ts#L727-L732
https://github.com/react-component/field-form/blob/4fab2919ab87eb7181f4ddeb84facfa0f1daedbf/src/useForm.ts#L270-L272

**Comment by zombieJ** [comment]
Close since already fixed in latest version.
