### ISSUE TITLE
如何改变DatePicker输入框里默认文字的颜色

### ISSUE THREAD

**Issue by aNameHere** [ant-design/ant-design#2818]
#### 本地环境

- antd 版本: 1.0.1
- 操作系统及其版本：windows8 
- 浏览器及其版本: chrome  52.0.2743.116 (正式版本) m （32 位）

#### 你做了什么？

引入 antd 的 DatePicker,并将其style设置为 {color:"red"}

#### 你期待的结果是：

- 日期输入框里的字体是红色

#### 实际上的结果：

日期输入框里的日期 颜色不变

#### 可重现的在线演示

http://codepen.io/flowerEatTheGirl/pen/EyzQJZ?editors=0011

**Comment by benjycui** [comment]
用 CSS Selector 去覆盖吧，话说这需求。。
