### ISSUE TITLE
DatePicker / RangePicker with custom date / date-time format not fully displayed on frontend - width issue

### ISSUE THREAD

**Issue by matinfo** [ant-design/ant-design#28186]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/matinfo/pen/ZEpQObz](https://codepen.io/matinfo/pen/ZEpQObz)

### Steps to reproduce
Set format='DD MMMM YYYY HH:mm' or format='DD MMMM YYYY'; for example.

### What is expected?
To see fully the start and end date.

### What is actually happening?
Part of the date is not displayed, auto width of the input field not correct.

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | react 16.14.0 |
| System | Mac |
| Browser | Chrome 87.0.4280.67 |

**Comment by afc163** [comment]
You can set width by `style={{ width: xxx }}`.

**Comment by matinfo** [comment]
I know that but my app allow user to change the date format dynamically and also in deferent language! Result I need also to set the width dynamically base on chosen format and language. Is not normal to do that just because the components not auto adjust fields width base on content. 🤨

**Comment by afc163** [comment]
You can dynamically set width by format length.
