### ISSUE TITLE
InputNumber在win10系统自带输入法中文下输入金额超过3位后每次输入会出现两个数字

### ISSUE THREAD

**Issue by ji-ShiQi** [ant-design/ant-design#28191]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/input-number-cn/](https://3x.ant.design/components/input-number-cn/)

### Steps to reproduce
在win10系统下，使用win10自带的输入法中文输入，在InputNumber组件使用（formatter={value => `$ ${value}`.replace(/\B(?=(\d{3}) (?!\d))/g, ',')}）格式化数字时，输入超过3个数字之后每次再输入都会出现两个重复数字

### What is expected?
尽快解决此问题

### What is actually happening?
只要使用win10再带输入法中文输入数字时，就会出错

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 任何版本 |
| System | win10 |
| Browser | chrome |

---
填写金额时会用到这个功能

**Comment by yoyo837** [comment]
Duplicate of #27748
