### ISSUE TITLE
Table如何给某个tr(某行数据)单独设定样式？

### ISSUE THREAD

**Issue by huzion** [ant-design/ant-design#2819]
如题，举个栗子：

><table>
>  <tbody>
>    <tr><td>普通</td></tr>
>    <tr className="special"><td>特殊的数据行</td></tr>
>    <tr><td>普通</td></tr>
>    <tr><td>普通</td></tr>
>  </tbody>
></table>

**Comment by afc163** [comment]
rowClassName

**Comment by huzion** [comment]
好快！问题都没编辑好！

**Comment by huzion** [comment]
可否详情解释下

```
Function(record, index):string
```
record, index分别指什么？

我使用如下代码，所有tr都加了class
```
                <Table
                columns={columns}
                dataSource={data}
                indentSize={0}
                rowClassName={(record)=>'sub-title'}
                size="middle"
                ref="offerTable" />
```


使用如下代码，编译器报错（给第0条数据加class）
```
                <Table
                columns={columns}
                dataSource={data}
                indentSize={0}
                rowClassName={(record, 0)=>'sub-title'}
                size="middle"
                ref="offerTable" />
```

**Comment by afc163** [comment]
`rowClassName={(record, index) => index === 0}`

**Comment by afc163** [comment]
属性是一个函数，返回值是 className。

**Comment by huzion** [comment]
成功了！不过发现另一个问题，我的数据有children，这么做以后，children也会被加上样式，是设计如此么？

不过可以通过选择 .ant-table-row-level-0 来单独给父行设置样式，所以不是大问题。

**Comment by afc163** [comment]
确实有这个问题，我给 rowClassName 加了第三个参数 `indent`，你可以据此判断一下。

重新安装 antd 即可。

**Comment by hbrls** [comment]
有办法发现当前行是选中行吗？除了自己 indexOf

**Comment by geekpeng** [comment]
有办法给单元格自定意样式吗

**Comment by chairy11** [comment]
在多级树表格中，即使indent能提供层级信息，也还是没法确定就是「当前行」。
比如点击一个index为2的三级子节点，触发onRowClick，记录选中行的index，再通过rowClassName比对，那所有index为2的三级子节点都会得到相同的class。而不是仅仅被点击那行。

有能确定「当前行」的方法吗？

**Comment by alexandrduduka** [comment]
Hey  guys, not sure if topic is related to this, but could you give me a hand with this: can't make indentSize work for me.
```
    rows = [
      {
        id: 1,
        title: 'Bank statement',
        children: [
          {
            id: 2,
            title: 'Bank statement',
          },
        ],
      },
    ];
```
```
          <Table
            rowKey="id"
            indentSize={20}
            rowSelection={{}}
            dataSource={rows}
            pagination={false}
            columns={columns}
            expandRowByClick
          />
```

**Comment by alexandrduduka** [comment]
@afc163

**Comment by dengfuping** [comment]
@alexandrduduka Please refer to the demo https://codesandbox.io/s/l52026zojq.

**Comment by alexandrduduka** [comment]
@dengfuping for a pity it works right before you set "expandRowByClick" property, then now indentation is applied. The problem is I am implementing file-folder system ui, so it would be quite unnatural in case you should click "plus" to expand it. Could you advise anything better then removing "plus" button with styles and writing whole expanding logic from scratch just to not use "expandRowByClick" prop?

And one more question: am I right thinking that there is no predefined way to implement logic of selection of all children when parent was selected?

**Comment by dengfuping** [comment]
@alecklandgraf Maybe `Tree` component would be better for your demands. Please refer to https://ant.design/components/tree

**Comment by alexandrduduka** [comment]
Thank you @dengfuping, it is helpful advise. Though, I have ui looking completely as ant table, so I think I will try to adjust Table to my needs. I am just curious if behavior with indents while having expandRowByClick property is expected.

**Comment by liu93ri** [comment]
你好，我想请问下为什么我设置了rowClassName之后css的效果显示不出来呢，不知道这样implement是否存在一些问题。能否帮忙看一下，感谢。 
<Table
      rowClassName={(record, index) => 'rowDistinction'}
      bordered
      scroll={{ y: window.innerHeight - 228 - 20 }}
      onChange={onTableChange}
      columns={columns}
      simple
      className={styles.table}
      rowKey={(record, i) => i}
      locale={{ emptyText: 'No Result', filterTitle: 'Search' }}
    />

css file： 
.rowDistinction {
  background: #b3d9ff;
}

**Comment by thisissami** [comment]
How do you pass a `className` to the header?

**Comment by wustzhaohui** [comment]
请问下可以给某行添加行内样式么 因为想做进度条那种效果 要让背景的长度随着上传进度来变长

**Comment by yoyo837** [comment]
class不也一样吗
