### ISSUE TITLE
排序的上下箭头能拥有自己的方法吗/The sorting up or down arrows can have its own function ？

### ISSUE THREAD

**Issue by ccloveak** [ant-design/ant-design#28196]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前有个需求：点击每一列的上下箭头，单独向服务器发送获取数据的请求/There is currently a requirement to send a separate request to the server for data by clicking on the up and down arrows in each column.

### What does the proposed API look like?
1. `sortTop：function(column.key, sortTop) {}`
2. `sortBottom：function(column.key, sortBottom) {}`

**Comment by afc163** [comment]
暂时不支持，建议统一通过 onChange 向服务器进行交互。
