### ISSUE TITLE
[Image] 拥有相同 url 的图片包裹在组内时，点击后预览不会显示在预览组内

### ISSUE THREAD

**Issue by stygian-desolator** [ant-design/ant-design#28190]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-k2kw8f?file=index.js](https://stackblitz.com/edit/react-k2kw8f?file=index.js)

### Steps to reproduce
点击第三张图片，预览显示的是从第一张开始，并且第三张被去重了。

### What is expected?
正常展示所有的图片

### What is actually happening?
预览显示的是从第一张开始，并且第三张被去重了。

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | ^16.9.44 |
| System | Mac OS |
| Browser | Chrome |

---
预览结果应该与实际展示行为保持一致，不应主动去重相同 url 的图片，并且应该从正确的索引开始。

**Comment by zombieJ** [comment]
看起来得加个 key 标记一下= =

**Comment by shaodahong** [comment]
我看之前的 pr 是以 `url` 为粒度的，所以如果是一样的 `url` 确实会出现这个情况，可以优化下

**Comment by stygian-desolator** [comment]
另外似乎不会将 preview 为 false 的图片过滤掉
