### ISSUE TITLE
异步树勾选父节点后展开，虽然子节点都勾选了，但是不会触发change事件，无法获取勾选的子节点

### ISSUE THREAD

**Issue by lianchao1** [ant-design/ant-design#28199]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/compassionate-thunder-sl1u9?file=/src/index.js](https://codesandbox.io/s/compassionate-thunder-sl1u9?file=/src/index.js)

### Steps to reproduce
先勾选异步树父节点，然后展开父节点

### What is expected?
反馈问题

### What is actually happening?
数据与展示不一致

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.0 |
| System | windows |
| Browser | chrome |

**Comment by lianchao1** [comment]
在线的重现实例已更新

**Comment by lianchao1** [comment]
在线的重现实例

**Comment by afc163** [comment]
具体怎么操作，预期结果是什么？

> 先勾选异步树父节点，然后展开父节点

这句话太模糊了，看不太明白。
