### ISSUE TITLE
日期控件的结构和样式优化建议

### ISSUE THREAD

**Issue by xufei** [ant-design/ant-design#282]
- ant-calendar下面的tbody被命名为ant-calendartbody，感觉没有必要。
- 用于表达“上个月的日期”的样式是“ant-calendar-cell ant-calendar-last-month-cell”，这类复合的东西，特例部分名称可简化。
- ant-calendar-year-panel等结构不合理，合理的结构应当是：

	- 日历有外围容器，内部三个元素，分别是：日期选择表格，月份选择表格，年份选择表格。
	- 三个元素各自是独立的，始终只有一个显示
	- 三者的内部结构也应当是一致的，包括各自的header，body，footer，或者可以考虑header和footer的共用（有些麻烦，而且意义不大）
	- 现在的官网版本中，ant-calendar-year-panel位于ant-calendar-header中，这个很不合适，虽然说它是从这里的年份上面点击出来的，但不代表就应当放在这里。现在的结构看上去比较乱。

**Comment by xufei** [comment]
“今天”的class里面有一个undefined，现在是“ant-calendar-today-btn undefined”，这个可能有问题

**Comment by xufei** [comment]
datepicker的弹出层放在全局的位置，是基于怎样的考虑？感觉在这个控件里，弹出层是作为控件的附属，结构上跟随控件自身会比较好一些。

比如：http://getbootstrap.com/components/#dropdowns，这个是bootstrap的下拉框，我建议也做成类似这种结构，在现有的span外面再来一层wrap，然后里面是现有结构和浮动层两个部分。

**Comment by yiminghe** [comment]
1. 所有的弹层都是在 body 上，防止受父层元素/继承影响.
2. 结构问题是为了写组件方便以及减少状态变化时的重绘范围，确实不那么好看....
https://github.com/react-component/calendar/blob/master/src/calendar/CalendarHeader.jsx

**Comment by xufei** [comment]
这个重绘的代价应该不算大啊，为了这个把结构搞得不好看，感觉不划算。年月和日历的选择，只要用display: none就可以了，切换数据的时候把内容重绘，像现在这样每点一次选择月份都重新创建整个月份面板的结构，感觉这样的代价才大……

弹层的问题，像日历这种受父元素影响应该是可以避免的，因为它的所有样式都有上级限定了。并且，这类东西从逻辑上讲，是某个组件内部的，比如我们考虑做一个日期选择的Web Component，弹出层当然应该是shadow dom才对啊，怎么会创建到这个结构外面去？

另外一些弹出的东西，比如对话框，通用提示等等，这些我支持放在外面。

关于组件结构方面的考虑，之前写过[一篇东西](https://github.com/xufei/ng-control/issues/2)，现在回头看，里面有些地方考虑不当，主要是组件参数和事件的运用，类似React里面的props和flux的选择。

**Comment by yiminghe** [comment]
感谢建议，后续会考虑优化 https://github.com/react-component/calendar

也欢迎 pr ...
