### ISSUE TITLE
Select and dropdown components are being rendered to a different window

### ISSUE THREAD

**Issue by aszlacheta** [ant-design/ant-design#28200]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-43jlg?file=/index.js)

### Steps to reproduce
1. Use react-new-window library to load part of the React application in a different window.
2. Use any AntDesign component that renders in <body> section of the HTML page like a select, dropdown, tooltip.
3. Open part of React application in a different window and click on AntDesign component (for example Select - to see Options)

### What is expected?
1. AntDesign components will be loaded in <body> section of that new window.

### What is actually happening?
1. AntDesign components are loaded in other <body> section. 

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 86.0 |

---
Please open the provided codesandbox in a new window (https://43jlg.csb.app/) because react-new-window fails to load in inline codesandbox (because of cross-origin-errors)

**Comment by afc163** [comment]
Fixed in #28165
