### ISSUE TITLE
Dropdown组件的overlay使用react组件时样式不对

### ISSUE THREAD

**Issue by vincentshow** [ant-design/ant-design#2820]
直接在overlay里使用Menu组件是没有问题的，但是如果把Menu封装到自定义的React组件中，然后再加载这个组件到overlay中，显示的样式和直接用Menu的不一样

可重现的代码
http://codepen.io/anon/pen/WxBzqK?editors=0010#anon-login

使用Menu作为overlay时渲染出来的ul都是类似ant-dropdown-menu-item这种classname，使用React封装后的组件，渲染出来的classname是ant-menu-item

**Comment by afc163** [comment]
http://codepen.io/anon/pen/WxBJpP?editors=0010#anon-login

**Comment by vincentshow** [comment]
赞，好评
// 要把上层 props 传递下来
<Menu {...this.props} />
