### ISSUE TITLE
switch初始值设置不进去，不操作switch，form表单获取值为undefined

### ISSUE THREAD

**Issue by ryjwalker** [ant-design/ant-design#28202]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http:no](http:no)

### Steps to reproduce
1

### What is expected?
1

### What is actually happening?
1

| Environment | Info |
|4.9.1|
| antd | undefined |
| React | 16.13.1 |
| System | office |
| Browser | 1 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27415#issuecomment-717658931
https://github.com/ant-design/ant-design/issues/21999
https://github.com/ant-design/ant-design/issues/25091#issuecomment-646387384
