### ISSUE TITLE
table组件的loading效果不在屏幕中间

### ISSUE THREAD

**Issue by yimi8126** [ant-design/ant-design#2821]
现在table的loading效果的原点是在整个table的中间，如果table数据过多，效果不是很明显，能不能将loading效果始终显示在屏幕中间，而不是table的中间

**Comment by afc163** [comment]
屏幕中间只能你自己业务中写了，组件不可能做一些超越组件范畴的事。

**Comment by yimi8126** [comment]
我的意思是table组件的可见范围的中间，而不是整个table组件的中间，如果table太长了哪个点会看不到

**Comment by afc163** [comment]
如果是空数据，怎么会太长？

**Comment by yimi8126** [comment]
纵向太长，那个loading的效果会在屏幕的不可见的地方

**Comment by afc163** [comment]
这个不好判断的，屏幕可见部分不是稳定的，放在上面，拖动下去一样看不到的。表格 loading 时都有模糊效果。
