### ISSUE TITLE
async-validator表单验证触发了两次

### ISSUE THREAD

**Issue by narniaera** [ant-design/ant-design#28213]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bbkdb?file=/index.js)

### Steps to reproduce
使用表单验证设置rules后，当表单验证会重复验证两次

### What is expected?
提交表单验证的时候,只触发一次

### What is actually happening?
提交表单验证的时候,会触发两次验证
util.js:18 async-validator: ["Please input your username!"]
util.js:18 async-validator: ["Please input your username!"]

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
你给的例子无法重现。


<img width="708" alt="图片" src="https://user-images.githubusercontent.com/507615/101246567-25241d80-374f-11eb-85f0-6530d779c448.png">

**Comment by narniaera** [comment]
谢谢，已经解决！
我重新创了个项目 重装了antd就好了..目前还不知道什么原因导致的
