### ISSUE TITLE
Statistic组件升级4.9.1后出现字体大小问题，是否可以自定义prefix、suffix样式

### ISSUE THREAD

**Issue by shaojava** [ant-design/ant-design#28216]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/4945550/101238315-677f3780-371a-11eb-997c-72ef9b42532a.png)
![image](https://user-images.githubusercontent.com/4945550/101238321-6ea64580-371a-11eb-9fdf-9b84c7ebf06c.png)

### What problem does this feature solve?
Statistic处理对于单纯字符前后缀样式控制

### What does the proposed API look like?
prefixStyle、suffixStyle

**Comment by shaojava** [comment]
网络不行只能使用gitee地址
https://gitee.com/esoft/antd-test

![image](https://user-images.githubusercontent.com/4945550/101274618-a7a5ef00-37da-11eb-8400-e56ea2eec593.png)

**Comment by shaojava** [comment]
[https://codesandbox.io/s/antd-reproduction-template-forked-8gbp1?file=/index.js](url)
codesandbox 地址

`import React from "react";
import ReactDOM from "react-dom";
import { Button, DatePicker, version, Statistic } from "antd";
import "antd/dist/antd.css";
import "./index.css";

ReactDOM.render(
  <div className="App">
    <h1>antd version: {version}</h1>
    <DatePicker />
    <Button type="primary" style={{ marginLeft: 8 }}>
      Primary Button
    </Button>
    <Statistic
      value={2.0}
      precision={2}
      suffix="%"
      valueStyle={{ fontSize: "16px" }}
    />
  </div>,
  document.getElementById("root")
);`

![image](https://user-images.githubusercontent.com/4945550/101274767-b0e38b80-37db-11eb-8c15-4966544c5ac1.png)

**Comment by rdmclin2** [comment]
诉求其实是希望value 和prefix 以及 suffix 的字体大小一样。实际上最近做的调整也是将这几个值的字体大小调整为一样，只不过写死了，后续可以调整成继承字体大小。这样就可以统一字体了。

**Comment by shaojava** [comment]
嗯都可以吧 我看 suffix的样式字体大小 一直都是 24px 继承value style可以最快达到效果
