### ISSUE TITLE
需要可编辑的联动组件：就像点击cascader后出现的级联组件（Cascader的问题是要先点击选择框才会有级联组件，需求是直接展示级联组件）

### ISSUE THREAD

**Issue by kothing** [ant-design/ant-design#28210]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
cascader只是选择框，需要先点击下选择框然后才会显示级联组件，需要的功能是直接展示级联组件，并且可以编辑，功能如图
![image](https://user-images.githubusercontent.com/39289309/101173918-26394a00-367e-11eb-9e06-d99ef00858c7.png)

### What does the proposed API look like?
满足需求功能即可

**Comment by afc163** [comment]
看上去已经是很复杂的业务组件了，建议自行封装。
