### ISSUE TITLE
Table component default sort defaultSortOrder is invalid（Table 默认排序defaultSortOrder无效）

### ISSUE THREAD

**Issue by gwh113** [ant-design/ant-design#28215]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

我有一个需求，需要根据ajax获取的数据去设置Table表头，现在发现一个问题，最开始我在componentDidMount里面获取数据
设置columns，设置“score”列defaultSortOrder: "descend"倒序排列，渲染后发现页面没有设置默认排序，后来使用ComponentWillMount发现默认排序又生效了，是否可以得出结论Tabel的defaultSortOrder只有在第一次渲染前设置的columns里面才会生效，后续通过setState设置的不会生效？

### Reproduction link
[https://stackblitz.com/edit/react-tx4kan](https://stackblitz.com/edit/react-tx4kan)

### Steps to reproduce
View the page's "流程评分" column (dataIndex: 'score')   查看页面“流程评分”列（dataIndex: 'score'）

### What is expected?
Order by setting defaultSortOrder: "descend"   按照设置的 defaultSortOrder: "descend" 排序

### What is actually happening?
There is no default sort, so I need to click sort 没有默认排序，需要点击排序列

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17 |
| System | win10 |
| Browser | google 87.0.4280.66、Firefox83.0、EDGE84.0.522.52、IE11 |

**Comment by afc163** [comment]
defaultSortOrder 和 defaultValue 一样，只在第一次渲染时生效。

**Comment by 15938265525** [comment]
如何解决的呢
