### ISSUE TITLE
table伸缩列性能比较差

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#28214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keshensuolie-antd491-forked-19uou?file=/protable.js)

### Steps to reproduce
拖拽调整列宽的时候，由于是触发onResize来修改列宽；会频繁修改列宽度表格数据多的时候会卡顿

### What is expected?
拖拽列的时候不实时调整列宽，鼠标松开的时候再调整列宽

### What is actually happening?
会实时调整，页面会卡顿 鼠标会错位(鼠标已经在后面了 列位置还在鼠标前面)

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | Chrome |

---
看到很多比较不错的实现
1.鼠标拖拽结束后再变动列宽
2.或者是不是可以在onResize上做防抖处理

**Comment by xiexingen** [comment]
![image](https://user-images.githubusercontent.com/7939085/102047426-34266200-3e18-11eb-9cc1-4e45d26d8b3d.png)
想法是这样在components:header:wrapper上处理，但是需要获取到实际th到dom上的宽度；这个地方有没办法可以获取到

**Comment by alexchen1875** [comment]
** 鼠标拖拽结束后再变动列宽 ** 是个不错的办法
现在再有复杂操作列的时候尤其会非常慢,目前暂时只能借助`shouldCellUpdate` 来做一些优化

**Comment by kerm1it** [comment]
@xiexingen @alexchen1875   通过自定义组件用 `react-resizable` 后时，`onReize` 已经完全在 `Reizable` 中由自己控制了，加个节流就好了，效果好很多:

https://codesandbox.io/s/keshensuolie-antd491-forked-1jt5f?file=/protable.js

**Comment by alexchen1875** [comment]
> @xiexingen @alexchen1875 通过自定义组件用 `react-resizable` 后时，`onReize` 已经完全在 `Reizable` 中由自己控制了，加个节流就好了，效果好很多:
> 
> https://codesandbox.io/s/keshensuolie-antd491-forked-1jt5f?file=/protable.js
是的,当前是以这种方式来勉强处理的,当行数多了的时候时,流畅度上还是太差,目前能想到的就只有这两种方式来处理

**Comment by kerm1it** [comment]
嗯嗯，这个时候 resize 的能力其实已经外放了，内部并不能去做一些优化，这个问题我就暂时先关闭了。

**Comment by hemengke1997** [comment]
https://github.com/hemengke1997/useATRH
表头拖拽hook
