### ISSUE TITLE
autoClearSearchValue not work when searchValue is UnderControl

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design#28229]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/25bf6605](https://riddle.alibaba-inc.com/riddles/25bf6605)

### Steps to reproduce
- click tree select, input 1
- select ant node

### What is expected?
- my input keyword should be clear, since autoClearSearchValue is set

### What is actually happening?
- input search keyword still keep

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | any |
| System | any |
| Browser | any |

---
- looks like the reason is https://github.com/react-component/select/blob/master/src/generate.tsx#L607 just change inner state, forget to trigger props onChange
- this behavior do not obey what UnderControl means

**Comment by paranoidjk** [comment]
cc/ @zombieJ

**Comment by zombieJ** [comment]
User can wrap `onSelect` to clean `searchValue` when controlled. Since `autoClearSearchValue` is default `true`, we may not modify current behavior to avoid user can not tell the clear `searchValue` is from selection or user input.
