### ISSUE TITLE
onClick listeners on Image components also trigger in preview 

### ISSUE THREAD

**Issue by tracyhenry** [ant-design/ant-design#28222]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wp2xw?file=/index.js)

### Steps to reproduce
1. Click on the image. You will see an alert, this is expected.
2. Dismiss the alert generated in step 1.
3. Now click on the image or one of the rotation buttons in the preview. An alert is generated again. This is not expected. 

### What is expected?
clicking on things in the preview should not trigger the custom onclick listener

### What is actually happening?
clicking on things in the preview triggers the custom onclick listener

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 17.0.1 |
| System | Mac OS 10.13.6 |
| Browser | Chrome/Safari/Firefox |

---
would be great if work-around solutions can be provided if this can't be fixed quickly. I can add `pointer-events:none` to the image body/rotation buttons but that's suboptimal.

**Comment by afc163** [comment]
It is expected behavior, you can stop event bubble like this: https://codesandbox.io/s/antd-reproduction-template-forked-sv9s8?file=/index.js

**Comment by tracyhenry** [comment]
> It is expected behavior, you can stop event bubble like this: https://codesandbox.io/s/antd-reproduction-template-forked-sv9s8?file=/index.js

Hi, my intended behavior is to trigger the listener on the original image, NOT in the preview. How can I achieve that?

**Comment by tracyhenry** [comment]
nvm: I worked it around by checking if `event.target` is the outer div in the listener. 

To be honest this default behavior is quite counter intuitive - clicking on a rotation button should only rotate the image, and do nothing else.
