### ISSUE TITLE
select组件在多选模式下，鼠标移上去可以看到所有选中项，或者可以提供一个渲染方法(textRender)，而不用点击打开下拉框再滚动到具体的某一项去查看

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#28234]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
提升用户体验

### What does the proposed API look like?
textRender: (props) => ReactNode

**Comment by zombieJ** [comment]
没明白，你要的是什么样子的？来个图

**Comment by fengyun2** [comment]
[https://codesandbox.io/s/duoxuan-antd492-forked-6sx5l?file=/index.js](https://codesandbox.io/s/duoxuan-antd492-forked-6sx5l?file=/index.js)

鼠标移到输入框上方的效果如下：
![image](https://user-images.githubusercontent.com/8147202/101364321-65b1a180-38dd-11eb-8bfa-989f7288c257.png)

**Comment by afc163** [comment]
现在 ... 上确实没办法看到更多的信息，UI 上可以优化一下。
