### ISSUE TITLE
"Select" Component原生气泡反应慢且不美观

### ISSUE THREAD

**Issue by enjoy-wind** [ant-design/ant-design#28230]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户体验。
尽管自己可以通过dom修改，但是对于项目代码总有点不满意。

### What does the proposed API look like?
废弃原生的灰色气泡，鼠标触及立马显示全文，采用和antd流行的小清新色调。

**Comment by afc163** [comment]
建议自行对需要的地方包裹 Tooltip。
