### ISSUE TITLE
a-input-number和table冲突

### ISSUE THREAD

**Issue by hdtopku** [ant-design/ant-design#28239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
表格中固定一栏，并在单元格中添加a-input-number，鼠标悬浮在固定栏时，就会出现input的加减按钮。

### What is expected?
鼠标悬浮至fix栏目的删除按钮上，a-input-number的加减按钮不应该显示出来

### What is actually happening?
鼠标悬浮至fix栏目的删除按钮上，a-input-number的加减按钮就显示出来，高度覆盖了fix栏的删除按钮，并且可以点击计数加减按钮，影响了删除按钮的点击。
![](https://user-images.githubusercontent.com/14859466/101332335-1d2fbf00-38b0-11eb-8436-363a7a2ea215.png)

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | react |
| System | macos |
| Browser | chrome  86.0.4240.183 |

---
图片地址：https://user-images.githubusercontent.com/14859466/101332335-1d2fbf00-38b0-11eb-8436-363a7a2ea215.png

**Comment by zombieJ** [comment]
试了一下是好的，给个重现看看： https://codesandbox.io/s/gudinglie-antd492-forked-07qef

**Comment by hdtopku** [comment]
> 试了一下是好的，给个重现看看： https://codesandbox.io/s/gudinglie-antd492-forked-07qef

试了一下，能复现了。
在table外嵌套，<a-form><a-form-item>就会出现问题。
[并且Form的layout 是inline ，导致select样式问题](https://github.com/ant-design/ant-design/issues/9777)
这个冲突好像是a-form和a-input、a-input-number、a-select之间的

村里网不好，打不开codesandbox，将就一下。框架是`antdv`

```
<template>
  <a-form>
    <a-form-item>
      <a-table :columns="columns" :data-source="data" :scroll="{ x: 1300 }">
        <template #input>
          <a-input-number></a-input-number>
        </template>
        <template #action="{ text }">
          <a>action</a>
        </template>
      </a-table>
    </a-form-item>
  </a-form>
</template>
<script>
  const columns = [
    { title: 'Full Name', width: 100, dataIndex: 'name', key: 'name', fixed: 'left' },
    { title: 'Age', width: 100, dataIndex: 'age', key: 'age', fixed: 'left' },
    { title: 'Column 1', dataIndex: 'address', key: '1' },
    { title: 'Column 2', dataIndex: 'address', key: '2' },
    { title: 'Column 3', dataIndex: 'address', key: '3' },
    { title: 'Column 4', dataIndex: 'address', key: '4' },
    { title: 'Column 5', dataIndex: 'address', key: '5', slots: { customRender: 'input' } },
    { title: 'Column 6', dataIndex: 'address', key: '6' },
    { title: 'Column 7', dataIndex: 'address', key: '7' },
    { title: 'Column 8', dataIndex: 'address', key: '8' },
    {
      title: 'Action',
      key: 'operation',
      fixed: 'right',
      width: 100,
      slots: { customRender: 'action' },
    },
  ]

  const data = [
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      address: 'New York Park',
    },
    {
      key: '2',
      name: 'Jim Green',
      age: 40,
      address: 'London Park',
    },
  ]

  export default {
    data() {
      return {
        data,
        columns,
      }
    },
  }
</script>

```

**Comment by afc163** [comment]
报错地方了，这里是 React 的库。

**Comment by hdtopku** [comment]
> 报错地方了，这里是 React 的库。

由于，[antdv](https://github.com/vueComponent/ant-design-vue/)的[newIssue](
https://vuecomponent.github.io/issue-helper/)一直无法访问，没办法联系到antdv那边
原以为antd和antdv库是共享的，所以才过来提问。打扰了
