### ISSUE TITLE
【求助】直接基于ant design的组件开发一套移动端系统

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#28236]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
直接基于ant design的组件开发一套移动端系统

### What does the proposed API look like?
各位好，我们web端使用ant design开发了一套系统，现在想将部分常用功能在移动端进行实现
比如适配钉钉、微信小程序
我看有ant-design-mobile
但是更新频率好像有点慢
我如果不使用ant-design-mobile，能否直接基于ant design的组件开发一套移动端系统啊。

**Comment by phoema** [comment]
补充：我们团队现在移动端开发经验等于0.

**Comment by yoyo837** [comment]
建议团队里至少有个有移动端经验的，你想问的都能知道，在这里问，响应慢不说，还不一定是你要的。

**Comment by xrkffgg** [comment]
小程序可以试试 [Remax](https://remaxjs.org/)

**Comment by afc163** [comment]
Ant Design 目前专注于 PC 端，不建议直出。

**Comment by phoema** [comment]
感谢热心的朋友。

**Comment by yoyo837** [comment]
> 感谢热心的朋友。

想用，就直接硬上，只有极个别场景移动端不够友好。

**Comment by phoema** [comment]
> > 感谢热心的朋友。
> 
> 想用，就直接硬上，只有极个别场景移动端不够友好。

是有这么用的场景吗？
我们是之前一直用design，然后看咱们这边是比移动端mobile那边响应和更新比较及时
所以，如果确实有可能，是想直接上design的。
