### ISSUE TITLE
Is that possible set Table pagination prop as React component

### ISSUE THREAD

**Issue by yuxuan** [ant-design/ant-design#28248]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We can pass customized pagination component to Table. It could ask for required props of the customized pagination. 

The background of this requirement was: We want to have Pagination with customized page jumper and page size info. Currently it seems not possible to customize those on Pagination as well. But, even if we recreate Pagination base on RcPagination, Table component will still use the original Pagination. 

### What does the proposed API look like?
```
<Table ... pagniation={<CustomPagination .../>} />
```

**Comment by afc163** [comment]
```jsx
<>
  <Table ... pagniation={false} />
  <CustomPagination .../>
</>
```

**Comment by yuxuan** [comment]
Thanks

**Comment by yuxuan** [comment]
It's kind of inconvenient, as there lots of inner logic around Table pagination. Such as  position, default page data, etc..
