### ISSUE TITLE
Tree设置checkedKeys树节点选择无效

### ISSUE THREAD

**Issue by bamboott** [ant-design/ant-design#2824]
#### 本地环境

- antd 版本:1.10
- 操作系统及其版本：win7 64位旗舰版
- 浏览器及其版本: 谷歌 版本 51.0.2704.63 (64-bit)

#### 你做了什么？
使用Tree组件

#### 你期待的结果是：
希望能够通过点击按钮设置checkedKeys树节点选择或取消选择

#### 实际上的结果：
首次加载完成直接点击按钮设置checkedKeys没有效果，通过鼠标点击树节点选择之后再次点击按钮设置checkedKeys可以选择当前节点，但父节点联动无效

#### 可重现的在线演示
http://codepen.io/anon/pen/rLgVqp?editors=1011

**Comment by warmhug** [comment]
![snip20160824_3](https://cloud.githubusercontent.com/assets/2011119/17916647/c5b186fa-69e7-11e6-9e6b-f90d29551e5d.png)
改为 `const checkedKeys = [...this.state.checkedKeys];` 
注意 react 怎么改变state。
