### ISSUE TITLE
[Table] Unexpected border appear when dynamically changing bordered property

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#28241]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/dynamic-settings-antd491-forked-dljq4

### Steps to reproduce

Toggle `bordered` button.

### What is expected?
There is no unexpected border appear.

### What is actually happening?
Unexpected border appear(pointed in the GIF). I'm not sure whether it is a bug.

![Kapture 2020-12-07 at 18 56 37](https://user-images.githubusercontent.com/50612752/101343379-e3b28000-38be-11eb-83cb-1775135c1d87.gif)

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | react 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
It is not perfect but I think no one will dynamically changing bordered style in real application. So it is OK.
