### ISSUE TITLE
Input组件输入内容后无法正常的删除，而且也不能输入数字

### ISSUE THREAD

**Issue by dwyr** [ant-design/ant-design#28255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pm.bocspace.cn/#/./joinelement/Z9ULYY8M9T7YP74Y](https://pm.bocspace.cn/#/./joinelement/Z9ULYY8M9T7YP74Y)

### Steps to reproduce
点击修改属性值

### What is expected?
操作正常

### What is actually happening?
操作不正常

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by yoyo837** [comment]
demo用不了，请提供个新的
