### ISSUE TITLE
InputNumber组件在百分比的情况下，用较低版本的微软拼音输入法输入一个数字，会出来两个数字，例如输入1显示11，官网亦是这样。

### ISSUE THREAD

**Issue by liuwade35** [ant-design/ant-design#28251]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
打开antd4.0的官网，找到InputNumber组件的百分比模式下，将微软输入法(较低版本的)切换到拼音模式，输入1，显示了11

### What is expected?
输入1，显示1

### What is actually happening?
输入1，显示11

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | react 16.9.0 |
| System | windows10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
Duplicate of #27748

**Comment by Dolov** [comment]
> Duplicate of #27748

@yoyo837 你好，这个问题存在很长时间了，也看到有很多开发者都有提出这个问题。但是没有看到有相应的反馈，不知道这个问题计划什么时候修复，能不能提供一个临时的解决方案，谢谢
