### ISSUE TITLE
InputNumber onDoubleClick

### ISSUE THREAD

**Issue by superchenwb** [ant-design/ant-design#28257]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
在官网上即可重现，双击增加或减少按钮时报错

Uncaught TypeError: (event.target.className || "").indexOf is not a function
    at onDoubleClick (eval at success (kernel.js:1), <anonymous>:62:48)
    at dispatch (jquery.js:5237)
    at elemData.handle (jquery.js:5044)

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.12.0 |
| System | macOS 10.15.7 |
| Browser | chrome 86.0.4240.198 |

**Comment by afc163** [comment]
看上去和 antd 没关系，请检查浏览器插件。

**Comment by ItProgerUA** [comment]
![image](https://github.com/user-attachments/assets/80f9f666-2050-4ab5-93c4-08c46194abaf)
No, this is not related to the browser plugin. If you click here with both mouse buttons simultaneously, you will see the issue.
