### ISSUE TITLE
日期选择RangePicker的问题

### ISSUE THREAD

**Issue by eijil** [ant-design/ant-design#28259]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.范围选择必须设置showTime才能出现确定按钮，期望是不设置ShowTime也可以展示确定。
2.由于上面问题，自己在页脚扩展内容添加一个确定按钮，但是选择完日期后面板隐藏。
3.onBlur事件在选了第一个日期后面板没关闭的情况下也会触发

### What does the proposed API look like?
1.范围选择必须设置showTime才能出现确定按钮，期望是不设置ShowTime也可以展示确定。
2.由于上面问题，自己在页脚扩展内容添加一个确定按钮，但是选择完日期后面板隐藏。
3.onBlur事件在选了第一个日期后面板没关闭的情况下也会触发

**Comment by afc163** [comment]
Duplicate of #22966

**Comment by rohit-sourcefuse** [comment]
We are also facing a similar issue, can you please share any alternative.
