### ISSUE TITLE
Descriptions描述列表嵌入子组件变成空白的问题

### ISSUE THREAD

**Issue by vVvlife** [ant-design/ant-design#28254]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daibiankuangde-antd492-forked-nse03)

### Steps to reproduce
1.新建一个子组件
2.子组件包含Descriptions.Item
3.Descriptions中引用子组件

### What is expected?
可以显示出来

### What is actually happening?
为空

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | React 17.0.1 |
| System | Linux Ubuntu 18.0.4 |
| Browser | Firefox 83.0 (64-bit) |

**Comment by vVvlife** [comment]
今天下午抽空看了下Descriptions组件的源码
发现子组件会被变成数组然后进行遍历循环，再push进新的数组再显示出来的
所以写子组件的方式就会显示为空
后面我采用了render的方式进行业务逻辑的判断，然后实现了DescriptionsItem的动态显示
这个也确实不能算个BUG，因为还是有更好的实现方式的
在想，在文档上需不需要进行一些提示 @afc163

**Comment by afc163** [comment]
最好尝试修复一下，这应该要支持的。

**Comment by afc163** [comment]
试试类似 https://github.com/react-component/menu/commit/bd93019b0816da44024efa7a38c8ff931897a16e#diff-57556e2d6d1d1e2ca1ac3da581d463efe8b62234687c8609b3f62925af89b49fR464 的方案

**Comment by vVvlife** [comment]
> 最好尝试修复一下，这应该要支持的。

好的，有空会尝试进行一下修复

**Comment by liuchao233** [comment]
> 试试类似 [react-component/menu@bd93019#diff-57556e2d6d1d1e2ca1ac3da581d463efe8b62234687c8609b3f62925af89b49fR464](https://github.com/react-component/menu/commit/bd93019b0816da44024efa7a38c8ff931897a16e#diff-57556e2d6d1d1e2ca1ac3da581d463efe8b62234687c8609b3f62925af89b49fR464) 的方案

是不是应该使用类似Menu的mini-store的方案来处理这个问题呢？Descriptions 源代码里面其实是有使用toArray对children进行处理的，toArray方法只能处理数组和Fragment，但并不能获取函数组件中children的props。

**Comment by vVvlife** [comment]
发现这个问题确实不止在Descriptions组件上存在，应该来说用了toArray方法去处理函数组件都会出现这个问题，Menu组件上还直接报错了，确实是拿不到return 组件的属性
[![Edit on CodeSandbox](https://codesandbox.io/s/neiqiancaidan-antd492-forked-0gxq0)

**Comment by afc163** [comment]
Menu 这样就行了：https://codesandbox.io/s/neiqiancaidan-antd492-forked-bfeqj

**Comment by vVvlife** [comment]
> Menu 这样就行了：https://codesandbox.io/s/neiqiancaidan-antd492-forked-bfeqj

确实是，把属性继续下沉，尝试下Descriptions组件的改进

**Comment by kerm1it** [comment]
ref: https://github.com/ant-design/ant-design/issues/4853
