### ISSUE TITLE
 How to do we mock the form instance passed as props?

### ISSUE THREAD

**Issue by huseyingoztok** [ant-design/ant-design#28252]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
***

### What is expected?
****

### What is actually happening?
****

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome |

---
I would be very happy if you can show how to mock the form instance in functional components.

**Comment by anapanadero** [comment]
@huseyingoztok, did you find the solution?

**Comment by huseyingoztok** [comment]
@anapanadero  no i didn't

**Comment by anapanadero** [comment]
I got with this workaround, but it's not a perfect solucion due to type checking with typescript doesn't match.

`const createFormMock = () => {
  const formInstance = {};
  const FakeComponent = () => {
    const [form] = Form.useForm();
    Object.assign(formInstance, form);
    return null;
  };
  render(<FakeComponent />);
  return formInstance;
};
<Component form={mockForm} />,
`

**Comment by antony2025** [comment]
I created a wrapper component to pass the form prop to the component under test. This was good enough for my use case.

Suppose I want to test the following component.
```tsx
const MyComponent = ({ form }) => {
  return (<Form form={form}>
    <Form.Item name="title" label="Title">
      <Input />
    </Form.Item>
  </Form>)  
};
```
The following would be an example test.

```tsx
import { render, screen } from '@testing-library/react';
import { Form } from 'antd';

const FormWrapper = (props) => {
  const [form] = Form.useForm();

  return <MyComponent form={form} {...props} />;
};

describe('My component', () => {
  it('should render', () => {
    render(<FormWrapper />);
    expect(screen.getByLabelText('Title')).toBeInTheDocument();
  });
});

```
