### ISSUE TITLE
[Help] how can i Hide verification text

### ISSUE THREAD

**Issue by alexchen1875** [ant-design/ant-design#28261]
i want to hide the form verification error message,just keep the Verified status ,  what should i do ?

- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd492-forked-j9euo?file=/index.js)

### Steps to reproduce
.

### What is expected?
.

### What is actually happening?
.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | windows |
| Browser | chrome  latest |

**Comment by xrkffgg** [comment]
```css
.ant-form-item-explain { 
    display: none;
}
```

**Comment by xrkffgg** [comment]
@afc163 
现在 discussions 开放了。是不是可以引导用户将问题转移到 discussions 里。

这里面可以回答问题，选择答案，也方便以后查阅。

issue 可以直接转移到 discussions 里

**Comment by afc163** [comment]
@xrkffgg 应该的，how to 类问题可以引导到 discussions 里。
