### ISSUE TITLE
Table中字段是否可以增加一个可编辑的功能？

### ISSUE THREAD

**Issue by tianyacsdn** [ant-design/ant-design#2826]
遇到一个需求，需要对Table中的数据进行编辑，我现在的处理方式是在Table中需要编辑的字段嵌入一个Input，对Input的value值设置一个变量，通过变量来获取修改后的值。但是这样处理有一个问题，必须对每一条数据增加一个变量才能实现，非常的麻烦。是否可以加一个编辑功能或者其他解决办法？
代码如下：
let columns = [{
title: '账户',
    dataIndex: 'accno',
    render(text) {
      return <span className="blue">{text}</span>;
    }
  },{
    title: '名称',
    dataIndex: 'accname',
    render(text) {
      return <span className="blue">{text}</span>;
    }
  }];
export default class test extends Component {
  state={
    targetpercent0:'',
    targetpercent1:''
  }
componentDidMount() {
let opt1 ={
        title:'目标比例 (%)',
        dataIndex:'premPercent',
        render:this.renderFn1.bind(this)
      }
      columns.push(opt1);
}
renderFn1(text,record,index){
    switch (index) {
      case 0:
        return (
          <Input name={index} className="targetpercent_input" placeholder="目标比例" value={this.state.targetpercent0} onChange={this.onTargetPercentChange.bind(this)}/>
        );
        break;
      case 1:
        return (
          <Input name={index} className="targetpercent_input" placeholder="目标比例" value={this.state.targetpercent1} onChange={this.onTargetPercentChange.bind(this)}/>
        );
        break;
}
}
}
现在有2条数据，所以目标比例字段就设置了2个变量targetpercent0和targetpercent1，如果有多个就需要设置多个，有什么好的解决办法吗？

**Comment by afc163** [comment]
不支持，业务自行实现。

https://github.com/ant-design/ant-design/search?q=Table++%E5%8F%AF%E7%BC%96%E8%BE%91&type=Issues&utf8=%E2%9C%93
