### ISSUE TITLE
statistic with value(decimal number) set valueStyle(fontSize) bug, decimal part does not applies custom styles

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design#28268]
### 使用 Statistic组件，value 是带小数的，设置 valueStyle 的字体大小（字体大小不是默认值24时），小数部分未应用样式

- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd492-forked-9oeq3?file=/index.js)

### Steps to reproduce
use Statistic, value is a decimal number, set valueStyle fontSize=18(or otherwise, not equal to 24)
使用 Statistic组件，value 是带小数的，设置 valueStyle 的字体大小（字体大小不是默认值24时），小数部分未应用自定义样式。

![image](https://user-images.githubusercontent.com/7055008/101591786-365b7b80-3a28-11eb-8b64-5f064845c9c0.png)

### What is expected?
The decimal part also applies custom styles
小数部分也应用自定义样式

### What is actually happening?
decimal part does not applies custom styles
小数部分未应用自定义样式

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | Edge 87 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/28223
