### ISSUE TITLE
[Feature Request] ConfigProvider supports to set global placeholder for some components

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#28266]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Set global placeholder for some components below:
- Input、InputNumber、AutoComplete、Mentions
- Select、Cascader、TreeSelect
![image](https://user-images.githubusercontent.com/14918822/101568778-377faf00-3a0e-11eb-8d81-8f77e93d6e2c.png)

### What does the proposed API look like?
- `inputPlaceholder`
- `selectPlaceholder`

**Comment by afc163** [comment]
不推荐完全统一文案，更好的方式是『请选择xx』这样更具体的内容。
