### ISSUE TITLE
代码生成放在nginx服务器上报错

### ISSUE THREAD

**Issue by cnv587** [ant-design/ant-design#2827]
#### 本地环境

- antd 版本:
- 操作系统及其版本：windows 10
- 浏览器及其版本:       chrome 52

#### 你做了什么？
最终生成打包代码的时候放在nginx服务器上报错;
![1](https://cloud.githubusercontent.com/assets/13713580/17924175/20cbe788-6a1a-11e6-9660-922f1849e970.jpg)

**Comment by benjycui** [comment]
antd 版本
