### ISSUE TITLE
3.x版本文档连接错误

### ISSUE THREAD

**Issue by lxfljw** [ant-design/ant-design#28279]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://3x.ant.design/docs/react/introduce-cn](http://3x.ant.design/docs/react/introduce-cn)

### Steps to reproduce
查看3.x文档

### What is expected?
期望能打开

### What is actually happening?
实际无法打开链接

| Environment | Info |
|---|---|
| antd | 3.26.1 |
| React | 16.3 |
| System | windows |
| Browser | chrome |

**Comment by xrkffgg** [comment]
可以打开。

Gitee 3.x 地址：https://ant-design-3x.gitee.io/
