### ISSUE TITLE
Input.Search allowClear 触发onSearch事件，通过form 获取Input的值依然是上一次的值

### ISSUE THREAD

**Issue by hubingkang** [ant-design/ant-design#28276]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1er91?file=/index.js:232-272)

### Steps to reproduce
1. 输入任意内容, 点击clear 图标
2. onSeach 的方法的值为空，但是通过表单获取的值是清除前的值

### What is expected?
清除后，form获取的值应该为空

### What is actually happening?
清除后，form获取的值为清空前的值

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 17.0.1 |
| System | MacOS |
| Browser | Chrome  87.0.4280.88 |

**Comment by afc163** [comment]
Try: https://codesandbox.io/s/antd-reproduction-template-forked-xdlug?file=/index.js
