### ISSUE TITLE
Select maxTagCount responsive support

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#28271]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
云凤蝶用户反馈多 Tag 下折行的布局问题，需要支持响应式支持。

### What does the proposed API look like?
```tsx
<Select maxTagCount="responsive" />
```

ref #28234

**Comment by zombieJ** [comment]
先抽一个比较通用的组件出来，未来可以给 `rc-menu` 一同使用:
https://github.com/react-component/overflow

**Comment by afc163** [comment]
是不是和 Tabs 的那个也一样。

**Comment by zombieJ** [comment]
Tabs 是 overflow 滚动，不需要裁剪多余 Item。这个 `rc-overflow` 和 Tabs 初版非滚动的裁剪是一致的。
