### ISSUE TITLE
火狐浏览器，使用带feedback的表单进行校验，中文输入法无法进行输入

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#2828]
## 场景
可使用官网demo测试：
http://ant.design/components/form/
![image](https://cloud.githubusercontent.com/assets/17123400/17925027/d5599684-6a1d-11e6-917f-5669dc20e8dd.png)
使用**中文输入法**，如：![image](https://cloud.githubusercontent.com/assets/17123400/17925124/45d79be0-6a1e-11e6-852d-d7e587a42131.png)，输入表单内容
发现无法输入表单内容（英文输入法可输入）

## 版本
antd@1.10.0

## 环境
windows
firefox@46.0.1

**Comment by afc163** [comment]
我在 Mac 下的 Firefox 50.0a2 的搜狗输入法，以及 Windows 下的  Firefox 47.0.1 的微软拼音输入法测试，均没有重现，楼主先试试升级 Firefox 版本到最新？

**Comment by hhhyaaon** [comment]
问题依然复现，麻烦再次测试：
firefox 47.0.1
windows 8
搜狗中文输入法
![image](https://cloud.githubusercontent.com/assets/17123400/17954171/a968cee4-6aab-11e6-9ffd-3d04b70648cf.png)

**Comment by infeng** [comment]
我也发现这个问题，firefox的版本是48.0.2，出这个问题是因为windows10的微软拼音在输入中文的时候，字母会出现在input里面，在firefox里面会响应onChange事件，导致进行了检验，检验之后刷新了界面，中断了输入中文的过程 @afc163

**Comment by afc163** [comment]
升级到 2.0 如何呢？

**Comment by infeng** [comment]
试了一下，2.0没有这个问题

**Comment by afc163** [comment]
赞，@infeng

那关了。
