### ISSUE TITLE
Select 组件中提供搜索filterOption属性，function(inputValue, option)这个option中获取不到label和options的值，这是否是bug

### ISSUE THREAD

**Issue by burning110-lab** [ant-design/ant-design#28285]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What is expected?
期望结果是能够获取到label和value的值

### What is actually happening?
实际只能获取到value的值，其他提供的属性获取不到

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.8.6 |
| System | Mac |
| Browser | chorm |

---
我的需求是能够根据value和lable同时都能搜索，当用户输入匹配的value或者label都能搜索到

**Comment by burning110-lab** [comment]
[https://ant-design.gitee.io/components/select-cn/ ]第二个案例

**Comment by afc163** [comment]
可以读到 https://codesandbox.io/s/m0my3?file=/index.js
