### ISSUE TITLE
手动的方式触发 Mentions @ 功能无效时，采用插入@并发送键盘事件给TextArea仍然无效

### ISSUE THREAD

**Issue by maxcong** [ant-design/ant-design#28288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost/](http://localhost/)

### Steps to reproduce
1. Mentions 使用 createRef() 持有引用
2. let ev = new KeyboardEvent('keydown', {
      keyCode: 96
      });
      mentions.current.textarea.dispatchEvent(ev)

### What is expected?
能够触发 @ 后弹出 @人搜索并展示列表

### What is actually happening?
无法手动触发@功能，也无法在 TextArea 中发送键盘事件

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 最新 |
| System | mac os 11.1 |
| Browser | chrome 87.0.4280 |

`

import React, {createRef} from 'react'
const mentions = createRef()
export default class CommentBar extends React.Component {
  atUser = () => {
    let {displayText} = this.state
    displayText += '@ '
    this.setState({displayText})

    mentions.current.focus()
    let ev = new KeyboardEvent('keydown', {
         keyCode: 96
    });
    mentions.current.textarea.dispatchEvent(ev)
 }

render() {
  const {displayText} = this.state
  return <>
        <Mentions  ref={mentions} value={displayText} />
           <Option value='user0' key=0}>
         </Mentions>
        <Button title="@人" onClick={this.atUser}/>
       </>
 }
}
`

**Comment by maxcong** [comment]
> Hello @maxcong. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @maxcong, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)


我已经写了一个最简单的例子在下面链接：
《通过手动按钮触发Mentions @功能无效》
https://codesandbox.io/s/antd-reproduction-template-forked-yygqc?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-u021w?file=/index.js
