### ISSUE TITLE
Steps自定义icon和原来的Progress重合了

### ISSUE THREAD

**Issue by wood3n** [ant-design/ant-design#28292]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9rqp1?file=/index.js)

### Steps to reproduce
打开页面

### What is expected?
Steps.Step自定义icon能够支持传入的ReactNode

### What is actually happening?
传入的Progress和原有的Progress重合了

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.14 |
| System | window10 1909 |
| Browser | Chrome 87 |

**Comment by afc163** [comment]
最好不要这么用，progress 里嵌了一个  progress，本身就是很诡异的。

**Comment by wood3n** [comment]
> 最好不要这么用，progress 里嵌了一个 progress，本身就是很诡异的。

@afc163 不是，是原有的Progress无法满足我的需求，想通过icon自定义Progress

**Comment by afc163** [comment]
去掉 Steps 上的 percent 。

**Comment by wood3n** [comment]
@afc163 多谢，不过这样`percent`就失效了，我还得再自定义一个`Progress`达到`Step`内置的`Progress`这种效果😥😥：
![image](https://user-images.githubusercontent.com/31716713/101740071-5a3fbf80-3b03-11eb-90a5-1adc6fc22472.png)
`Steps`的`percent`我感觉是不是放到单个`Step`上要好点呢？

**Comment by afc163** [comment]
你的诉求是啥呢？多个 steps 上都有 percent 么？

**Comment by wood3n** [comment]
我希望是能支持多个`Step`处于`process`状态，且能分别控制各自不同的`percent`

![image](https://user-images.githubusercontent.com/31716713/101744533-f1a61200-3b05-11eb-83f9-51787f304499.png)

**Comment by afc163** [comment]
这个确实有点奇怪，理论上前面的没完成后面不应该开始的。

**Comment by wood3n** [comment]
@afc163 🤣实际上多个`Step`之间没啥关联，就这样一个展示效果

**Comment by yoyo837** [comment]
偏具体业务化，建议自行实现。

**Comment by afc163** [comment]
目前只能按你的方式在各个 icon 里单独维护 progress 的 percent 了。

**Comment by wood3n** [comment]
@afc163 OK
