### ISSUE TITLE
表格中下拉菜单被分页中页码切换器遮挡住

### ISSUE THREAD

**Issue by se7en00** [ant-design/ant-design#28297]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudingtouhelie-antd492-forked-s649w?file=/index.js)

### Steps to reproduce
在表格中Dropdown中设置浮层的父类渲染节点
```javascript
getPopupContainer={node => node.parentNode}
```
在点击下拉菜单时，分页中页码切换器会遮挡浮层

### What is expected?
在点击下拉菜单时，分页中页码切换器会不遮挡浮层

### What is actually happening?
在点击下拉菜单时，分页中页码切换器会遮挡浮层

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | react latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/commit/3d8b076b834a9ab7ffbd461cf70c4d53d5328e99

@zombieJ

**Comment by zombieJ** [comment]
之前是为了解决穿透问题，现在看 Dropdown 本身的 zIndex 的确是不该覆盖掉。应该用户侧去覆盖。

https://codesandbox.io/s/gudingtouhelie-antd492-forked-j00ky?file=/index.css

**Comment by se7en00** [comment]
@zombieJ 
如果用户侧这边去覆盖， 要重写哪个类？
我试一下重写dropdown的z-index， 也是无用

**Comment by se7en00** [comment]
已解决， 重写了table的zindex

**Comment by hyl1374961656** [comment]
Dropdown加上getPopupContainer={triggerNode => triggerNode.parentNode}    放在Table  fixed: 'right'列里，Table设置scroll={{ x: 1130 }}y轴的溢出会被隐藏掉，导致Dropdown的内容被裁剪
