### ISSUE TITLE
需求是checkbox不是必填项，上传文件是必填的。但是表单项中切换checkbox会触发校验，希望可以给表单元素增加一个不触发校验的属性。

### ISSUE THREAD

**Issue by potatoCC** [ant-design/ant-design#28290]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shijianleikongjian-antd492-forked-3gwlm?file=/index.js)

### Steps to reproduce
在必填项导入文件中，切换checkbox 会触发校验。
![image](https://user-images.githubusercontent.com/28758664/101715547-9dd00480-3ad6-11eb-8ef0-d714c94058b3.png)

### What is expected?
切换checkbox不触发校验。

### What is actually happening?
切换checkbox触发了校验。

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.14 |
| System | mac os  |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://codesandbox.io/s/shijianleikongjian-antd492-forked-gkrce?file=/index.js
