### ISSUE TITLE
.ant-picker.ant-picker-borderless{background-color: transparent!important;}

### ISSUE THREAD

**Issue by wuhao930406** [ant-design/ant-design#28293]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
设置bordered：false时 无法添加背景色

### What does the proposed API look like?
样式不要添加important

**Comment by afc163** [comment]
bordered={false} 设计上也是背景透明的。不如不加这个属性，自行覆盖背景色和边框色？

**Comment by wuhao930406** [comment]
> bordered={false} 设计上就是背景透明的。不如不加这个属性，自行覆盖背景色和边框色？

感谢回答 因为其他组件 例如Input设置之后依然可以通过css添加背景色

**Comment by afc163** [comment]
picker 样式比较复杂，当时抄近路加了 !important 。
