### ISSUE TITLE
Table组件，设置sticky后，如果dataSource为空数组，tbody里面td的rowspan=9, thead里面的th也会随之合并

### ISSUE THREAD

**Issue by favourLi** [ant-design/ant-design#28298]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/favourli/pen/xxEEMvQ?editors=001](https://codepen.io/favourli/pen/xxEEMvQ?editors=001)

### Steps to reproduce
Table组件，设置sticky后，如果dataSource为空数组，tbody里面td的rowspan=9, thead里面的th也会随之合并

### What is expected?
Table组件，设置sticky后，如果dataSource为空数组，tbody里面td的rowspan=9, thead里面的th也是原有的格式

### What is actually happening?
Table组件，设置sticky后，如果dataSource为空数组，tbody里面td的rowspan=9, thead里面的th也会随之合并

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.9.0 |
| System | window10 |
| Browser | google |

**Comment by shaodahong** [comment]
给 `column` 个宽度试试

**Comment by favourLi** [comment]
> 给 `column` 个宽度试试

ok了  谢谢
