### ISSUE TITLE
antd 示例 拼写错误

### ISSUE THREAD

**Issue by SanpiC** [ant-design/ant-design#28305]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/image-cn/](https://ant.design/components/image-cn/)

### Steps to reproduce
图片渐进加载代码示例中，placeholder 里的Image 的api preview 拼写错误，原文是preivew

### What is expected?
，，

### What is actually happening?
，，

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | 系统版本 |
| Browser | 浏览器版本 |

**Comment by xrkffgg** [comment]
fixed in https://github.com/ant-design/ant-design/pull/28242
