### ISSUE TITLE
Redundant calls of expandedRowRender

### ISSUE THREAD

**Issue by Webbrother** [ant-design/ant-design#28307]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/expandable-row-antd492-forked-ferpj)

### Steps to reproduce
Click on the expand plus button and see to the console.

### What is expected?
expandedRowRender called once.

### What is actually happening?
expandedRowRender called multiple times

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | Mac OS 11.0.1 (20B29) |
| Browser | Chrome 87.0.4280.88  |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/22901#issuecomment-608972325

**Comment by Webbrother** [comment]
@afc163 I've read the comment, but I didn't find any explanation of the mentioned behavior, also I still don't understand either this behavior bug or not.

**Comment by thelaurelyy** [comment]
hope for some suggestion
