### ISSUE TITLE
[Form]: I got a fake path when using Form and Grid and Upload 

### ISSUE THREAD

**Issue by LeonHardtll** [ant-design/ant-design#28306]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-fpr94?file=/index.js)

### Steps to reproduce
After uploading the file, click the button

### What is expected?
Get the file upload address

### What is actually happening?
A fake path

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.12.0 |
| System | macOS CataLina 10.15.7 |
| Browser | Chrome 版本 87.0.4280.88（正式版本） (x86_64) |

**Comment by huntdream** [comment]
表单控件应该要被Form.Item直接包裹

**Comment by afc163** [comment]
@huntdream is correct.
