### ISSUE TITLE
Sticky table pagination is not sticky

### ISSUE THREAD

**Issue by cnt-null** [ant-design/ant-design#28308]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-antd492-forked-94jwg)

### Steps to reproduce
Open the example and don't scroll. You will not see pagination.

### What is expected?
The pagination remains visible regardless of the scroll position.

### What is actually happening?
The pagination component is not visible. You need to scroll down the table to see the pagination.

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.13.1 |
| System | Mac 10.15.1 |
| Browser | Chrome 87.0.4280.88 |

**Comment by shaodahong** [comment]
yep, set `sticky` not contain `pagination`
