### ISSUE TITLE
Menu组件垂直显示，子菜单弹出被遮挡问题如何解决？

### ISSUE THREAD

**Issue by liujhfly** [ant-design/ant-design#2830]
#### 本地环境
- antd 版本: 1.9.0
- 操作系统及其版本：mac
- 浏览器及其版本: chrome
#### 你做了什么？

引入 antd 了 Menu 
#### 你期待的结果是：

左侧导航一级菜单内容较多时，弹出的二级子菜单正常显示，在最下面的导航二级菜单不会被遮挡
#### 实际上的结果：

左侧导航最下面的菜单弹出的二级子菜单会被浏览器遮挡，显示不全

**Comment by liujhfly** [comment]
二级菜单弹出时，在Menu上用onOpen如何获取其子节点ant-menu-sub元素呢？如果可以获取就可以改弹出子菜单的样式中top:0的值了。请教答案，谢谢！

**Comment by benjycui** [comment]
你说的垂直显示是 `inline` 还是 `vertical`，不一样的好么。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by liujhfly** [comment]
不好意思，我没有描述清楚是mode="vertical"
![2016-08-24 5 29 03](https://cloud.githubusercontent.com/assets/19344517/17954052/d76d395c-6aaa-11e6-8792-22307f257a02.png)

**Comment by liujhfly** [comment]
效果是最后一个弹出的子菜单被遮挡，如图：
![2016-08-25 10 09 49](https://cloud.githubusercontent.com/assets/19344517/17954243/22dd4598-6aac-11e6-9ee6-8725a6ee4618.png)

在http://codepen.io/anon/pen/wGOWGW?editors=001


`const { Menu, Icon } = antd;`
`const SubMenu = Menu.SubMenu;`
`const MenuItemGroup = Menu.ItemGroup;`

`function handleClick(e) {`
`  console.log('click', e);`
`}`

`const App = React.createClass({`
 `render() {`
`    return (`
`     <Menu onClick={handleClick} style={{ width: 240 }} mode="vertical">`
`    <SubMenu key="sub1" title={<span><Icon type="mail" /><span>导航一</span></span>}>`
`      <MenuItemGroup title="分组1">`
`        <Menu.Item key="1">选项1</Menu.Item>`
`        <Menu.Item key="2">选项2</Menu.Item>`
`      </MenuItemGroup>`
`      <MenuItemGroup title="分组2">`
`        <Menu.Item key="3">选项3</Menu.Item>`
`        <Menu.Item key="4">选项4</Menu.Item>`
`      </MenuItemGroup>`
`    </SubMenu>`
`    <SubMenu key="sub2" title={<span><Icon type="appstore" /><span>导航二</span></span>}>`
`      <Menu.Item key="5">选项5</Menu.Item>`
`        <Menu.Item key="6">选项6</Menu.Item>`
`        <SubMenu key="sub3" title="三级导航">`
`        <Menu.Item key="7">选项7</Menu.Item>`
`        <Menu.Item key="8">选项8</Menu.Item>`
`      </SubMenu>`
`    </SubMenu>`
`    <SubMenu key="sub4" title={<span><icon type="setting" /><span>导航三</span></span>}>`
`      <Menu.Item key="9">选项9</Menu.Item>`
`      <Menu.Item key="10">选项10</Menu.Item>`
`      <Menu.Item key="11">选项11</Menu.Item>`
`      <Menu.Item key="12">选项12</Menu.Item>`
`      <Menu.Item key="13">选项13</Menu.Item>`
`      <Menu.Item key="14">选项14</Menu.Item>`
`      <Menu.Item key="15">选项15</Menu.Item>`
`      <Menu.Item key="16">选项16</Menu.Item>`
`      <Menu.Item key="17">选项17</Menu.Item>`
`      <Menu.Item key="18">选项18</Menu.Item>`
`      <Menu.Item key="19">选项19</Menu.Item>`
`    </SubMenu>`
`  </Menu>`
`    );`
`  }`
`});`

ReactDOM.render(<App />, document.getElementById('container'));`

**Comment by benjycui** [comment]
trace: https://github.com/react-component/menu/issues/19

**Comment by liujhfly** [comment]
@benjycui  这里使用的是import {Menu} form 'antd',

**Comment by liujhfly** [comment]
试了几方法，还是不会用，请教如何将rc-trigger与import {Menu} form 'antd'中的menu结合使用呢？

**Comment by benjycui** [comment]
额。。这个要内部重构，不过这段时间在赶 antd@2.0 的 breaking changes，这个重构还没排期做。

**Comment by jzoe** [comment]
antd@2.10.0  同样有这个 bug

**Comment by benjycui** [comment]
开始重构 rc-menu，加个锁，省的又撞车了。。

**Comment by wwwqw1028** [comment]
```
.ant-menu-vertical.ant-menu-sub, .ant-menu-vertical-left.ant-menu-sub, .ant-menu-vertical-right.ant-menu-sub{
  position: relative;
  top: auto;
  left: auto;
}
```

加入这个样式可以解决，亲测有效

**Comment by seeleyz** [comment]
v9.1.2还有这个问题，有谁知道如何解决吗？
