### ISSUE TITLE
Table组件 rowClassName在fixed时不起作用

### ISSUE THREAD

**Issue by nqsjd178559344** [ant-design/ant-design#28300]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-v29pl)

### Steps to reproduce
无

### What is expected?
同以前一样，rowClassName支持滚动列和非滚动列

### What is actually happening?
rowClassName仅支持非滚动列

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.12.0 |
| System | Win32 |
| Browser | 87.0.4280.88（正式版本） （32 位） |

**Comment by afc163** [comment]
建议这么用 https://codesandbox.io/s/antd-reproduction-template-forked-60cu4

**Comment by nqsjd178559344** [comment]
> 建议这么用 https://codesandbox.io/s/antd-reproduction-template-forked-60cu4

麻烦大大指点一下...我没看出来区别呀
