### ISSUE TITLE
inputnumber设置最小值后，当失焦的时候，如果真实值小于最小值，会自动变为最小值，希望提供配置项，不自动变为最小值。

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#28313]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户设置了小于最小值的一个值，会自动变为最小值，会觉得很诧异，希望还保持原值，然后提示用户修改。为了保持原先逻辑，希望加一个配置项，用于区别。

### What does the proposed API look like?
autoChange:true/false  默认为true，之前的逻辑；为false则不自动改为最大或者最小值

代码
https://codesandbox.io/s/antd-inputnumberzuixiaozhihezhenshizhi-yfjkz

**Comment by afc163** [comment]
> 希望还保持原值，然后提示用户修改

可以不设 min 和 max，然后用 Form 的校验规则去做提示。

**Comment by yoyo837** [comment]
换个思路的事2儿...
