### ISSUE TITLE
Table表格不要结合Pagination分页

### ISSUE THREAD

**Issue by 134355** [ant-design/ant-design#28317]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
从设计理念来说Table应该是单纯的，不应该结合Pagination，这样属于过渡封装，把复杂业务逻辑柔和进来了，或者可以提供一个单纯的Table

### What does the proposed API look like?
可以提供一个单纯的Table

**Comment by 134355** [comment]
loading也是，应该让组件做各自的事情，我们应该需要基本组件，不是一个柔和一定的业务逻辑在里面，组件应该像积木一样，我们爱怎么搭建就怎么搭建，而不是一开始就使用搭建一定程度的组件

**Comment by afc163** [comment]
`pagination={false}` 就行了。

**Comment by 134355** [comment]
我要的是一个基础组件，不是一个业务组件，或者官方能提供一个基础组件
