### ISSUE TITLE
Drawer宽度是否可以支持栅格

### ISSUE THREAD

**Issue by JTenacity** [ant-design/ant-design#28319]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
小屏的时候可以有更大的宽度来显示内容，宽屏时相应以较小的宽度来展示

### What does the proposed API look like?
无

**Comment by afc163** [comment]
可以用相应的 hooks 去控制 width。
