### ISSUE TITLE
[需求]穿梭框穿到右边可设置在最下方

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#28328]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
近期几个客户提到穿梭框的用法，用户会分次数将选中项移动过来，从思维的角度来看
应当是往下放放置的

### What does the proposed API look like?
希望增加一个属性，能够制定穿梭框移动过来后是放置在上方还是下方

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/d372028476a8348bbae794ca0c25535d27803a93/components/transfer/index.tsx#L192

**Comment by afc163** [comment]
https://codesandbox.io/s/nice-pike-r4s6o?file=/index.js
