### ISSUE TITLE
Image 的预览功能期望可以独立成函数，类似 Modal.info()

### ISSUE THREAD

**Issue by dyb881** [ant-design/ant-design#28321]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
很多情况下，需要预览的内容和预览前的内容是不同的

### What does the proposed API look like?
 Img.preview()

**Comment by shaodahong** [comment]
哪些情况下 **需要预览的内容和预览前的内容是不同的**

**Comment by dyb881** [comment]
我在列表上只显示图组的第一张图片，但是点开后需要看到所有图片，详情看附件


| |
15118995517
|
|
15118995517@163.com
|
签名由网易邮箱大师定制


在2020年12月11日 15:38，骗你是小猫咪<notifications@github.com> 写道：

哪些情况下 需要预览的内容和预览前的内容是不同的

**Comment by Zexoius** [comment]
我觉得你需要的只是一个backdrop，而不是只局限于当前需求
