### ISSUE TITLE
Table无数据时sticky表头样式错乱

### ISSUE THREAD

**Issue by CaanDoll** [ant-design/ant-design#28323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-antd492-forked-ho3yo?file=/index.js)

### Steps to reproduce
看有数据和无数据的时候

### What is expected?
表头展现一致

### What is actually happening?
表头样式错乱

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome85 |

**Comment by afc163** [comment]
没看出明显问题，我错过什么了？

<img width="1053" alt="图片" src="https://user-images.githubusercontent.com/507615/101878539-b6214b80-3bca-11eb-8c2e-1361ae422351.png">

**Comment by CaanDoll** [comment]
![image](https://user-images.githubusercontent.com/23540471/101878714-000a3180-3bcb-11eb-9b93-d95321cb4841.png)
不是这样的吗

**Comment by shaodahong** [comment]
@CaanDoll 先试试这个 https://github.com/ant-design/ant-design/issues/28298#issuecomment-742301160

看了下不少人提了这个，我要看下
