### ISSUE TITLE
Upload cause an issue when working with immutable data

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#28325]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/other-form-controls-antd492-forked-zxmde?file=/index.js)

### Steps to reproduce
try to delete an image

### What is expected?
should be deleted 

### What is actually happening?
Upload tries to add image status property to the deleted object itself, so this is causing an error.

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | latest |
| System | Mac Os Catalina |
| Browser | Chrome latest |

**Comment by mumiao** [comment]
i will mention pr
