### ISSUE TITLE
Form表单中的元素的状态

### ISSUE THREAD

**Issue by gy0801151351** [ant-design/ant-design#28334]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
处理表单联动问题

### What does the proposed API look like?

        根据官方文档上面提供的Form的API, 有相关的如 setFieldsValue, resetFields 等等这些API方法. 
但是, 我却没有找到任何获取表单元素状态的API. 如果我要做表单联动(比如: 表单中有两个元素A、B,
 其中A是Select选择框, B是Input输入框, 元素B默认是隐藏的, 只有当A选择某些特定选项时元素B才
显示).  一般情况下, 我需要用useState定义好状态变量, 然后给元素A绑定onChange事件, 同时在B元
素上的hidden参数设置状态绑定. 现实开发中, 这种情况遇到非常多. 然而每次都得用诸如useState
这种钩子函数来实现, 感觉太麻烦了.大家都知道, 既然Form的setFieldsValue、resetFields这些API能
够触发Dom的重新渲染, 那么, 在Form的API中, 能否提供相关的获取表单元素状态的API呢?(Form的getFieldValue方法不一定管用)这样的
话, 就比如刚才的问题, 只需要将B元素的hidden参数绑定到Form的A元素的状态上就行了.

**Comment by gy0801151351** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 处理表单联动问题
> 
> ### What does the proposed API look like?
> ```
>     根据官方文档上面提供的Form的API, 有相关的如 setFieldsValue, resetFields 等等这些API方法. 
> ```
> 
> 但是, 我却没有找到任何获取表单元素状态的API. 如果我要做表单联动(比如: 表单中有两个元素A、B,
> 其中A是Select选择框, B是Input输入框, 元素B默认是隐藏的, 只有当A选择某些特定选项时元素B才
> 显示). 一般情况下, 我需要用useState定义好状态变量, 然后给元素A绑定onChange事件, 同时在B元
> 素上的hidden参数设置状态绑定. 现实开发中, 这种情况遇到非常多. 然而每次都得用诸如useState
> 这种钩子函数来实现, 感觉太麻烦了.大家都知道, 既然Form的setFieldsValue、resetFields这些API能
> 够触发Dom的重新渲染, 那么, 在Form的API中, 能否提供相关的获取表单元素状态的API呢?(Form的getFieldValue方法不一定管用)这样的
> 话, 就比如刚才的问题, 只需要将B元素的hidden参数绑定到Form的A元素的状态上就行了.

**Comment by yjunli** [comment]
这个找到解决办法了吗，你是如何处理到呢
