### ISSUE TITLE
TextAreaRef extends HTMLTextAreaElement but doesn't provide its properties

### ISSUE THREAD

**Issue by bluenote10** [ant-design/ant-design#28332]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository. There is https://github.com/ant-design/ant-design/issues/28072 but I'm not sure if it is a duplicate because I don't understand the Chinese explanation why it has been closed. Also the other issue doesn't touch the aspect of wrong TypeScript types.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kj4w2?file=/index.js)

Since this is partly a TypeScript issue, and I couldn't figure out to configure codesandbox to properly use TypeScript, here is the full TypeScript code:

<details>
<summary>TypeScript version</summary>

```ts
import React, { useRef } from "react";
import ReactDOM from "react-dom";

import { Input } from "antd";
import { TextAreaRef } from "antd/lib/input/TextArea";
const { TextArea } = Input;

const Component = () => {
  const textAreaRef1 = useRef<HTMLTextAreaElement>(null);
  const textAreaRef2 = useRef<TextAreaRef>(null);

  const onClick = () => {
    console.log(textAreaRef1.current);
    console.log(textAreaRef1.current?.value);
    console.log(textAreaRef2.current);
    console.log(textAreaRef2.current?.value);
  };

  return (
    <div>
      <div>
        <textarea ref={textAreaRef1} />
      </div>
      <div>
        <TextArea ref={textAreaRef2} defaultValue="defaultValue" />
      </div>
      <div>
        <button onClick={onClick}>Click me</button>
      </div>
    </div>
  );
};

ReactDOM.render(
  <React.StrictMode>
    <Component />
  </React.StrictMode>,
  document.getElementById("root")
);
```

</details>

### Steps to reproduce
Use a `ref` on a `TextArea`.

### What is expected?

The last `console.log` should print `"defaultValue"`. This is because the type `TextAreaRef` is defined as:
```ts
export interface TextAreaRef extends HTMLTextAreaElement {
    resizableTextArea: any;
}
```
I.e., it should have the same properties as an `HTMLTextAreaElement` with the additional `resizableTextArea` property.

### What is actually happening?
The object has a completely different type. In particular important properties like `value` are missing -- I also don't see how they are accessible from the available properties. The console log looks like:

![image](https://user-images.githubusercontent.com/3620703/101980234-5d05f600-3c64-11eb-89f9-28c229fe8d80.png)

Note that `textAreaRef1` indeed gives an `HTMLTextAreaElement` instance, but `textAreaRef2` is something that does not match the `TextAreaRef` type.

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | Ubuntu 18.04 |
| Browser | Firefox 83.0 |

**Comment by bluenote10** [comment]
For the record, I have noticed that the `value` field is accessible via `(textAreaRef2.current as any)?.state?.value`, i.e., it is "there" but obviously not with the right type annotation. Also, `state` basically only provides `value`, so that does not cover the use case of a user really needing a reference to the native HTML element -- which is really what a ref should be for, right?

**Comment by zombieJ** [comment]
TextArea provides wrong types. It should only contains `focus` & `blur` instead.

fixed in another PR: https://github.com/ant-design/ant-design/pull/28602/files#diff-e38236283d4b2ff8417dfed931e619e2652dffcf55a9d22125fc8d2c8c16e089R24
