### ISSUE TITLE
Inconsistent Selected Tags with Same Value when Using TreeSelect with SHOW_PARENT Strategy and maxTagCount

### ISSUE THREAD

**Issue by xianshenglu** [ant-design/ant-design#28335]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/xianshenglu/pen/VwKPpdp?editors=0010](https://codepen.io/xianshenglu/pen/VwKPpdp?editors=0010)

### Steps to reproduce
1. open the link, you will see the selected tags are `Child Node4` and ` 1...`
2. deselect `Child Node4`
3. select `Child Node4`, the selected tags become `Node2` and ` 1...`

### What is expected?
After select `Child Node4` back, the selected tags are `Child Node4` and ` 1...`

### What is actually happening?
the selected tags become `Node2` and ` 1...`

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.x |
| System | window7/window10 |
| Browser | Chrome 86 |

---
In this case, `Node2` and ` 1...`  tags are misleading because it tells the user that two top-level nodes are selected though it's not.

**Comment by zombieJ** [comment]
It's not a bug. values shows as order and omit. There are 2 different values:
* `Child Node4`, `Node2` -> `Child Node4` +1...
* `Node2`, `Child Node4` -> `Node2` +1...

If you want to keep the order, pls use controlled and sort it instead.
