### ISSUE TITLE
RangePicker的onChange事件里面拿到的Moment对象的时分秒是莫名其妙的

### ISSUE THREAD

**Issue by liubin595338764** [ant-design/ant-design#28331]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.******.com](https://www.******.com)

### Steps to reproduce
<RangePicker onChange={onChange} />

比如RangePicker选择的日期范围是[2020-12-08, 2020-12-13]，在onChange回调函数里面的第一个参数Moment对象的日期不是2020-12-08 00:00:00，而是2020-12-08 14:15:36。

正常情况下用户选择一个时间范围，格式是YYYY-MM-DD的话，精确时间应该是开始日期的 00:00:00，到结束日期的 23:59:59，这种情况吧？
但是RangePicker不知道是怎么弄的，而且从api来看还无法实现这种需求。

### What is expected?
RangePicker格式是YYYY-MM-DD的话，onChange回调函数里面拿到的第一个Moment日期的时分秒应该是 00:00:00，第二个Moment日期的时分秒应该是 23:59:59

### What is actually happening?
现在的RangePicker的onChange回调函数里面的Moment日期的时分秒是随机的

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.8.6 |
| System | windows |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.57 |

**Comment by HelloAny** [comment]
RangPicker里有提供相应的api，`showTime`设置成`format: 'HH:mm' `就可以实现选择时间的功能，文档里提供的例子就有相关的实现方案。
此外，选取的时间不是随机的，是根据你点击列表当时的时间来确定的。

**Comment by liubin595338764** [comment]
![image](https://user-images.githubusercontent.com/5274428/102031161-16dd9d80-3df0-11eb-8a84-ac1174cb727e.png)

@HelloAny hi, 设置`showTime={{format: 'HH:mm'}}` 后就会必然出现时分的选择器，就多了一些非必要的交互了。   
比如说用户要导出一段时间范围的数据，选择某一天到某一天，那时间范围应该就是开始日期的 00:00:00，到结束日期的 23:59:59。   
或者买火车票时选择日期也是一样的交互场景吧。我不太明白要如何设置参数；

此外，选取的时间不是点击列表当时的时间，是第一次点击列表当时的时间，比如说我选择了多次时间，但返回的都是第一次选择的时间。

**Comment by kerm1it** [comment]
@liubin595338764 那个时分秒不是随机的，是选择的时候，当前时间的时分秒。

当选择日期的时候，大家对时分秒的值需求有可能是不一样的，你可能需要的是 00:00:00 到 23:59:59，有的用户可能是 00:00:00 到 00:00:00，所以可以通过受控模式自己去设置值

参考这个:

https://codesandbox.io/s/antd-reproduction-template-forked-gixrw?file=/index.js
