### ISSUE TITLE
index.js is missing in antd\es\modal\useModal'

### ISSUE THREAD

**Issue by mleister97** [ant-design/ant-design#28338]
### Steps to reproduce
- Create a fresh project
- Add antd as dependency
- Import antd anywhere

### What is expected?
No error

### What is actually happening?

I am getting the following error:

**"Module not found: Can't resolve './useModal' in '<project-path\my-app\node_modules\antd\es\modal'".**
It seems like index.js file is now missing here: node_modules\antd\es\modal\useModal
When copying the file from a previous project everything works fine again. Why is the file missing? Am I doing something wrong? I am using create-react-app v4

The folder looks like this:
![image](https://user-images.githubusercontent.com/16700053/102010397-108ee900-3d3e-11eb-8ac8-23240a7a1d99.png)

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 17.0.1 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
It is existed: https://unpkg.com/browse/antd@4.9.2/es/modal/useModal/index.js

Please try reinstall node_modules.
