### ISSUE TITLE
Selected Tags Is Not Right When showCheckedStrategy is SHOW_PARENT and Child Node Is Disabled

### ISSUE THREAD

**Issue by xianshenglu** [ant-design/ant-design#28333]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/xianshenglu/pen/qBaRrxZ?editors=0010](https://codepen.io/xianshenglu/pen/qBaRrxZ?editors=0010)

### Steps to reproduce
1. open the demo link
2. click the input and confirm if the dropdown and the selected tags make sense

### What is expected?
selected tags should be  `Child Node4`, `Child Node5`

### What is actually happening?
selected tags are `Node2`

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.x |
| System | window7/window10 |
| Browser | Chrome 86 |

---
Current behavior would mislead users. For example, if the user only has the permission of `Child Node4`, `Child Node5`, and we set them as the default value. So the selected tags are `Node2`. The user might think that he can see the data of `Child Node3` too. However, the fact is that he can't. So, the selected tags mislead the user.

**Comment by zombieJ** [comment]
It's by design. Disabled tree node should not count into statistic.

ref: [What does disabled node work logic in the tree?](https://ant.design/components/tree/#What-does-disabled-node-work-logic-in-the-tree)

**Comment by xianshenglu** [comment]
Maybe I didn't make it clear. The values and conduction logic are correct. Only the way you render selected tags is misleading. To be honest, I think `Child Node4`, `Child Node5` makes more sense. Don't you think so?
