### ISSUE TITLE
After @ctrl/color update to v3.3.0, break all antd.

### ISSUE THREAD

**Issue by illusi03** [ant-design/ant-design#28337]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/scttcper/tinycolor/releases/tag/v3.3.0](https://github.com/scttcper/tinycolor/releases/tag/v3.3.0)

### Steps to reproduce
https://github.com/scttcper/tinycolor/releases/tag/v3.3.0

### What is expected?
https://github.com/scttcper/tinycolor/releases/tag/v3.3.0

### What is actually happening?
When build antd, show error dependencies error.
Because tinycolor has updated to 3.3.0

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.13.1 |
| System | Ubuntu 20.04 |
| Browser | Chrome  |

**Comment by illusi03** [comment]
![Update @ctrl_tinycolor2](https://user-images.githubusercontent.com/52351532/102009938-5dd67f00-3d6d-11eb-9afb-17e0730083c9.PNG)

Downgrading into @ctrl/tintycolor2 to 3.1.6 in lock file has solved. But how about installing a new package ?

**Comment by Nzent** [comment]
## I have the same issue
![image](https://user-images.githubusercontent.com/26079832/102018806-912d0400-3d95-11eb-969a-3697a12efb84.png)

**Comment by seungwon2** [comment]
I have the same issue too......🥺😢
<img width="582" alt="스크린샷 2020-12-14 오전 9 48 28" src="https://user-images.githubusercontent.com/48855293/102029353-8738ee80-3df1-11eb-9cd7-391a306e2ee3.png">

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/102030440-c5ccaa00-3ded-11eb-85af-4372d714c1d8.png)

---

master  打包正常的啊

**Comment by afc163** [comment]
Fixed in https://github.com/scttcper/tinycolor/issues/208#issuecomment-744041372
