### ISSUE TITLE
在create-react-app中如何动态切换主题

### ISSUE THREAD

**Issue by lichnow** [ant-design/ant-design#28330]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需要在CRA/webpack中提供动态切换主题(暗黑模式,紧凑模式)的能力,而不是在`umi`中,因为目前的大量项目没有采用Umi

### What does the proposed API look like?
例如提供`useTheme()`这个hook

**Comment by afc163** [comment]
这个和 antd 框架本身无关，你可能需要自行探索。

官方动态主题能力暂不支持，可以追踪 #5656 。
