### ISSUE TITLE
onChange should always dispatch (event, value) pair (at least event)

### ISSUE THREAD

**Issue by vadeneev** [ant-design/ant-design#28344]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There are inconsistency among different components which causes issues during integration with other libs.
As example: Input (during onChange dispatches event) and InputNumber(dispatches only value), select (same, only value).
It makes antd hard to integrate with other libs without workarounds. 

### What does the proposed API look like?
function(event: object, value: number | string)

**Comment by afc163** [comment]
Input/Checkbox is designed to same as native input component, please use `e.target.value` instead.
