### ISSUE TITLE
Image.PreviewGroup的placeholder是Image，预览会出现重复

### ISSUE THREAD

**Issue by zyxbb** [ant-design/ant-design#28348]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-napier-e5bez)

### Steps to reproduce
1.点击图片进行预览
2.左右切换图片

### What is expected?
1.不出现placeholder里的占位图片

### What is actually happening?
1.出现了占位的图

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 17.0.0 |
| System | macOS Big Sur 11.0.1 |
| Browser | Chrome 87.0.4280.88 (x86_64) |

**Comment by shaodahong** [comment]
Known issue, will resolve in https://github.com/react-component/image/pull/48
