### ISSUE TITLE
How do I control the input length on Select tag mode?

### ISSUE THREAD

**Issue by promotion-xu** [ant-design/ant-design#28359]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
control realtime input length.

### What does the proposed API look like?
I hope it has maxInputTagLength API.   just like maxLength on Input

**Comment by afc163** [comment]
Duplicate of #15244

**Comment by promotion-xu** [comment]
![image](https://user-images.githubusercontent.com/36992764/102174819-3e5c6500-3ed9-11eb-8ef5-25e44dde1e4b.png)

**Comment by promotion-xu** [comment]
Just Input length, not tag ength

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27954#issuecomment-734627711
