### ISSUE TITLE
Antd markdown support

### ISSUE THREAD

**Issue by Magnuscake** [ant-design/ant-design#28357]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am not sure if this feature exists, but I will put it here anyways. I can confirm that this has neither been asked nor been addressed anywhere. I have also put this up on stackoverflow, but so far haven't received any responses.
I am currently working on a website using Gatsby, Strapi and Antd for the design. When I try to display markdown content on the webpage, there is not styling applied to the elements. It makes because the content uses normal HTML elements like `<h1>` and `<p>` instead of the antd components like `<Title>` or `<Text>`.

So I did some researches and found that Antd has a [markdown.less](https://github.com/ant-design/ant-design/blob/master/site/theme/static/markdown.less) in the repo source, which I figure is used to style the markdown in the documentation. I haven't found the same after scouring the source code inside the node modules folder. Does this mean that Antd does not support styling for markdown or am I missing something here?

Also, I am using [react-markdown](https://github.com/remarkjs/react-markdown) for displaying the markdown content.

### What does the proposed API look like?
Since the markdown.less allows us to set a class of markdown to a `div` as per the stylesheet, maybe include that.

**Comment by afc163** [comment]
> Antd does not support styling for markdown

Yes, we don't provide markdown styles, please use react-markdown or other solutions.
