### ISSUE TITLE
List renderItem使用异步函数返回报错

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design#28352]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiazaigengduo-antd492-forked-w0kzn?file=/index.js)

### Steps to reproduce
无

### What is expected?
能正常渲染item节点

### What is actually happening?
报错，信息如下
Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.14.0 |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment]
renderItem 和 React render 方法是一样的，不支持异步。
