### ISSUE TITLE
Hover style delay with icon and text in Menu Component

### ISSUE THREAD

**Issue by Indomi** [ant-design/ant-design#28361]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd492-forked-bph1v)

### Steps to reproduce
hover on any menu item which is not active

### What is expected?
hover style appear with underline in the same time

### What is actually happening?
Hover style has been delayed with icon and text

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.13.0 |
| System | macos10.15.5  |
| Browser | chrome84.0.4147.105 |

**Comment by Indomi** [comment]
I doubt whether it's due to the dependency of rc-tirgger

**Comment by Indomi** [comment]
on the other hand, I find a bug issue but can't recurrent, I have found it appears from version 4.6.3 since you update dependency rc-trigger
![Kapture 2020-12-11 at 16.55.51.gif](https://i.loli.net/2020/12/15/39WgSIvY2yBGuOR.gif)

**Comment by Indomi** [comment]
this is the screenshot
![110910.png](https://i.loli.net/2020/12/15/Gp3RSbM1Q2Vs4JU.png)

**Comment by afc163** [comment]
Please remove yarn.lock and package-lock.json, then reinstall node_modules.

**Comment by Indomi** [comment]
> > on the other hand, I find a bug issue but can't recurrent, I have found it appears from version 4.6.4 since you update dependency rc-trigger
> 
> Please remove yarn.lock and package-lock.json, then reinstall node_modules.

I have tried, but it exists, also in runtime code build by CI tool, hope for anyone who can recurrent it. :)
