### ISSUE TITLE
Render Props cannot be used in Table

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design#28377]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-dpigb5?file=index.js](https://stackblitz.com/edit/react-dpigb5?file=index.js)

### Steps to reproduce
1，单击Open Modal，正常打开Modal，鼠标移入移出；
2，单击“直接使用Render Props"按钮，正常打开Modal，鼠标移入移出；
3，单击”表格中使用Render Props"按钮，正常打开Modal，鼠标移入移出；

1. Click the "Open Modal" button to open Modal normally, move the mouse in and out;
2. Click the "Directly use Render Props" button to open Modal normally, and move the mouse in and out;
3. Click the "Use Render Props in the form" button to open Modal normally, and move the mouse in and out;

### What is expected?
1,2,3中的Modal应该不发生任何变化

Modal in 1, 2, 3 should not change

### What is actually happening?
1和2正常，3中的Modal随着鼠标的移入移出不停的打开关闭。

1 and 2 are normal, but the Modal in 3 keeps opening and closing as the mouse moves in and out.

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.14.0 |
| System | windows 10 1909 |
| Browser | 87.0.664.60 (官方内部版本) (64 位) |

**Comment by yoyo837** [comment]
Modal不要这样用，render会重新渲染他，影响其生命周期和动画

**Comment by yoyo837** [comment]
错误的用法

**Comment by hankaibo** [comment]
@yoyo837 但是4.x版本一切正常。
不能这么用是只针对3.x还是所有版本？

**Comment by yoyo837** [comment]
上个4.0版本的demo看看？个人认为如果4.0没这个问题，纯属巧合。

**Comment by hankaibo** [comment]
@yoyo837 
https://stackblitz.com/edit/react-dpigb5-tsqn5p?file=package.json
这个是4.0版本的。没有问题。
是因为4.0是function组件dmj3.0是class组件吗？

是不推荐在render方法中使用，还是所有情况下？比如第2个按钮的情况。这种情况会影响吗？
如果所有情况下都影响，那react 推出的render props的意义何在呢？

**Comment by yoyo837** [comment]
你这个链接我这边看存在同样的问题。

**Comment by hankaibo** [comment]
我的链接有问题，4.0版本确实没问题。
你可以自己修改依赖版本号查看。
https://stackblitz.com/edit/react-dpigb5-tsqn5p?file=package.json

**Comment by hankaibo** [comment]
是不推荐在render方法中使用，还是所有情况下？比如第2个按钮的情况。这种情况会影响吗？
如果所有情况下都影响，那react 推出的render props的意义何在呢？

**Comment by yoyo837** [comment]
这和render props没关系把，是antd的Modal不应这样用

**Comment by hankaibo** [comment]
@yoyo837 
是不可以在render props中使用antd Modal吗？但是版本4可以，版本3不可以，主要原因是什么呢？我司框架是基于4，然后render props中使用了Modal。如果有问题，是什么问题啊？
在hoc中可以使用Modal吗？我翻issue好象版本3可以了，是吗？

**Comment by yoyo837** [comment]
我不理解你说的哪个可以哪个不可以，总的来说应该Modal应该放外面，render里渲染的按钮去控制一些数据比如state去影响Modal。
