### ISSUE TITLE
TreeSelect loadData事件不触发

### ISSUE THREAD

**Issue by Mamba-working** [ant-design/ant-design#28385]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-lake-4z1tw?file=/src/App.js:1632-1640)

### Steps to reproduce
触发TreeSelect的onSearch事件，set一个新的TreeData后，点击节点的展开按钮不会触发loadData事件

### What is expected?
期望点击节点展开按钮触发LoadData事件

### What is actually happening?
没有触发LoadData事件

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.0 |
| System | macos |
| Browser | Microsoft Edge 87.0.664.60  |

---
业务情况是TreeSelect展示公司的服务树，在用户search之后会根据服务端的数据setTreeData，并且使用了treeLoaded keys来控制loadedKeys。但是在节点没有loaded的时候展开仍然不能触发loadData。但是在点击该节点后就可以触发loadData了。。

**Comment by Mamba-working** [comment]
目前怀疑是在TreeSelect在onSearch的时候错误的判断节点已经展开

**Comment by liveever** [comment]
我这边有同样的问题 ，  Steps to reproduce：
触发TreeSelect的onSearch事件，set一个新的TreeData后，点击节点的展开按钮不会触发loadData事件

**Comment by zombieJ** [comment]
这是预期行为，搜索状态中不会触发异步加载以防止展开过多层导致的请求卡死。

**Comment by q862526436** [comment]
想问一个问题，为什么会有treeLoadedKeys属性？我看官网上没有
