### ISSUE TITLE
table set fixed=right ,colSpan=2

### ISSUE THREAD

**Issue by RaijinBai** [ant-design/ant-design#28388]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://fyrfdq--run.stackblitz.io](https://fyrfdq--run.stackblitz.io)

### Steps to reproduce
table fixed=right ,set children ,props:{colSpan=2},then fixed will not match 

### What is expected?
same with fixed=left .

### What is actually happening?
not match in layout 

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 16.14.2 |
| System | win10 |
| Browser | google Chrome  87.0.4280.88 |

**Comment by afc163** [comment]
> https://fyrfdq--run.stackblitz.io/

Cannot open.

**Comment by RaijinBai** [comment]
![image](https://user-images.githubusercontent.com/31680184/102421635-d70cf500-403f-11eb-8e54-8c176669d25c.png)
