### ISSUE TITLE
是否能提供一个下拉table的选择组件 ,目前的下拉select太单调,不能显示更多的内容 

### ISSUE THREAD

**Issue by yangxiaobao** [ant-design/ant-design#28380]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的下拉select太单调,不能显示更多的内容 ,下拉table可以很好解决这个问题

### What does the proposed API look like?
新增组件

**Comment by afc163** [comment]
建议结合 Popover 和 Table 自行封装业务组件。
