### ISSUE TITLE
Implement onVisibleChange prop for Modal component

### ISSUE THREAD

**Issue by sagar7993** [ant-design/ant-design#28394]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Modal currently has an `afterClose` prop which can be used to call a function when a modal is closed, but there's no obvious way currently to execute a function when a modal is opened. Implementing an `onVisibleChange` prop can help with this and improve API consistency with other components

### What does the proposed API look like?
<Modal {...modalProps} onVisibieChange={(visible: boolean) => {  }}>Content</Modal>

**Comment by afc163** [comment]
There is no way to open a modal beside set `visible` to true.
