### ISSUE TITLE
Unclear logic on max and min props in InputNumber 

### ISSUE THREAD

**Issue by glemiron** [ant-design/ant-design#28393]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-silence-tr9bz?file=/src/App.js)

### Steps to reproduce
Set value with value props grater than max on InputNumber

### What is expected?
When I use component as controlled I expect that value props will ignore max and min props

### What is actually happening?
Passed value just silently cut and become equal to max

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome |

---
We can receive value bigger than max from backed, but we don't aware it because InputNumber show max value

I think it much better apply max and min only to user input

**Comment by afc163** [comment]
It is by designed to limit displayed value between min and max.
