### ISSUE TITLE
Table的排序对于树形子数据是无效的吗？

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#2839]
#### 本地环境

- antd 版本: 1.8.0
- 操作系统及其版本：Mac
- 浏览器及其版本: Chrome

#### 你做了什么？

在包含children的Table中指定了sorter

#### 你期待的结果是：

children中的数据按照sorter排序

#### 实际上的结果：

children中的数据没有按照sorter排序

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/2845

https://github.com/ant-design/ant-design/commit/96c9c11b5570fc12fa8dbaa580a630c2df279e24
