### ISSUE TITLE
layout need  overflow scroll

### ISSUE THREAD

**Issue by chilingling** [ant-design/ant-design#28398]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dingbu-cebianbuju-tonglan-antd494-forked-gsfiv?file=/index.js)

### Steps to reproduce
now the content is 110vh，but  layout Component didn't overflow scroll
链接中的codesandbox，content的内容是很长的，我希望layout能溢出显示滚动条（低版本就可以，比如4.9.1）

### What is expected?
Layout should overflow scroll

### What is actually happening?
最新版本的 .antd-layout 的 `overflow-x:hidden` 被删除了，导致content的内容不能溢出滚动

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Layout 本身不应该出现滚动条，之前的代码产生的滚动条是预期外的，会引发别的问题。

- 要么交给 body 做滚动：https://codesandbox.io/s/dingbu-cebianbuju-tonglan-antd494-forked-hbkwy?file=/index.js
- 要么给对应的内部容器添加滚动样式代码：https://codesandbox.io/s/dingbu-cebianbuju-tonglan-antd494-forked-wh0bu?file=/index.js

**Comment by chilingling** [comment]
> Layout 本身不应该出现滚动条，之前的代码产生的滚动条是预期外的，会引发别的问题。
> 
> * 要么交给 body 做滚动：[codesandbox.io/s/dingbu-cebianbuju-tonglan-antd494-forked-hbkwy?file=/index.js](https://codesandbox.io/s/dingbu-cebianbuju-tonglan-antd494-forked-hbkwy?file=/index.js)
> * 要么给对应的内部容器添加滚动样式代码：[codesandbox.io/s/dingbu-cebianbuju-tonglan-antd494-forked-wh0bu?file=/index.js](https://codesandbox.io/s/dingbu-cebianbuju-tonglan-antd494-forked-wh0bu?file=/index.js)

- 交给body做滚动不符合需求，这样左边的菜单栏就会跟着滚动
- 给内部容器加了滚动样式代码，可行
thx
