### ISSUE TITLE
drawer影响body的滚动条

### ISSUE THREAD

**Issue by JadeDruid** [ant-design/ant-design#28392]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd494-forked-opfpl?file=/index.js)

### Steps to reproduce
1. open drawer
2. 鼠标放在drawer上，滑动滚轮

### What is expected?
body页面不会滚动

### What is actually happening?
body页面出现滚动条，并且会上下滚动

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16 |
| System | macos bigsur |
| Browser | Chrome 87.0.4280.88 |

---
https://ant.design/components/drawer/，官网例子也可复现

**Comment by JadeDruid** [comment]
Duplicate of #28391

**Comment by yoole5699** [comment]
官网的例子里打开多层抽屉，然后关闭全部抽屉，最后页面的纵向滚动条会消失（因为body的样式没清除）
https://ant.design/components/drawer-cn/#components-drawer-demo-multi-level-drawer
