### ISSUE TITLE
How to add sticky header to Table?

### ISSUE THREAD

**Issue by sambhav2612** [ant-design/ant-design#28390]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/iq2ku?file=/App.tsx:3377-3385)

### Steps to reproduce
https://table.react-component.now.sh/demo/sticky-header

### What is expected?
https://table.react-component.now.sh/demo/sticky-header

### What is actually happening?
The table is not sticky despite adding the sticky prop

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Microsoft Edge |

**Comment by sambhav2612** [comment]
Another reproduction link: https://codesandbox.io/s/friendly-colden-3420j?file=/src/table.js

**Comment by afc163** [comment]
It is antd's repo, you should report this to rc-table.

**Comment by sambhav2612** [comment]
> It is antd's repo, you should report this to rc-table.

@afc163 the same `sticky` prop has been exported to antd Table component and the rc-table is used internally to implement it, I think it relevant to address a missing example for a prop described in your docs. If the same prop is working in the internal component the same should work with antd Table unless it is not supported.
