### ISSUE TITLE
When Drawer is open you can scroll the body of main content.

### ISSUE THREAD

**Issue by PavelEfimenko** [ant-design/ant-design#28391]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-microservice-whi1d?file=/src/App.js)

### Steps to reproduce
Just open the Drawer and scroll down. 

### What is expected?
overflow for `body` must be hidden

### What is actually happening?
The main content under mask is scrolled.

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | Win 10 |
| Browser | Google Chrome 87.0.4280.88 |

**Comment by afc163** [comment]
Broken by https://github.com/react-component/util/pull/174

**Comment by ouzhou** [comment]
![image](https://user-images.githubusercontent.com/7693866/103184031-e23e0b80-48f0-11eb-997f-15251f5b58a9.png)
这是修复了还是没有修复？
@afc163

**Comment by ouzhou** [comment]
![image](https://user-images.githubusercontent.com/7693866/103184080-29c49780-48f1-11eb-99ba-e9eb2f8d5ea3.png)
4.9.4仍然有这个错误
4.9.5修复吗

**Comment by yoyo837** [comment]
等待升级依赖。

**Comment by 123456wjw** [comment]
> ![image](https://user-images.githubusercontent.com/7693866/103184080-29c49780-48f1-11eb-99ba-e9eb2f8d5ea3.png)
> 4.9.4仍然有这个错误
> 4.9.5修复吗

请问解决drawer遮挡不住body的滚动条 并且有打开drawer有scrollLocker这个waring的问题了嘛？

**Comment by yoyo837** [comment]
没有，等发布

**Comment by topseczbw** [comment]
这个问题解决了吗？

**Comment by lidakai** [comment]
这个问题解决了吗？

**Comment by mvshvets** [comment]
> 没有，等发布

In what release will there be a solution?
