### ISSUE TITLE
Select  "onDropdownVisibleChange" 回调调用时机不正确

### ISSUE THREAD

**Issue by bigbigDreamer** [ant-design/ant-design#28408]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://react-hl77tr.stackblitz.io/](https://react-hl77tr.stackblitz.io/)

### Steps to reproduce
执行聚焦/失焦操作，查看控制台

### What is expected?
这个回调函数出现的本意应该是dropdown下拉框渲染后再出现，但是这只适用于“死”数据，而检测时机也是在聚焦事件与失焦事件之后。
但是针对于远程获取数据的情况，一开始并无输入内容，所以聚焦后，这个回调也执行了，感觉不妥。

### What is actually happening?
远程搜索数据后，并且下拉回调出现再执行，而不是把回调放在聚焦或者失焦后再执行。

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.9.0 |
| System | windows |
| Browser | 版本 87.0.4280.88（正式版本） （64 位） |

---
远程未搜索数据，但是聚焦，执行回调后，visible应该为false

**Comment by fireairforce** [comment]
I will fix this~

**Comment by bigbigDreamer** [comment]
> I will fix this~

Thank u，if you have time welcome.

If you have other questions you can ask here.

**Comment by fireairforce** [comment]
我觉这个 api 有些奇怪，正如： “这个回调函数出现的本意应该是dropdown下拉框渲染后再出现，但是这只适用于“死”数据，而检测时机也是在聚焦事件与失焦事件之后。” 应该是在下拉框渲染出现的时候调用，那这个 api 为啥还要设计一个 open 的参数来表示 visible 呢(这样这个 visible 参数不永远都是 true 了吗QuQ)

**Comment by appleshell** [comment]
这其实不是bug，而是因为设置了`notFoundContent={null}`。可以通过在远程调用的回调中动态设置`notFoundContent`。此外，触发`onDropdownVisibleChange`的事件是`mousedown`，不是`focus/blur`. @afc163 @bigbigDreamer

**Comment by bigbigDreamer** [comment]
> 这其实不是bug，而是因为设置了`notFoundContent={null}`。可以通过在远程调用的回调中动态设置`notFoundContent`。此外，触发`onDropdownVisibleChange`的事件是`mousedown`，不是`focus/blur`. @afc163 @bigbigDreamer

![image](https://user-images.githubusercontent.com/39019913/115019797-401c5080-9eec-11eb-8a0b-3e1b9daf05f3.png)

讲话一定要拿出依据，这是rc-select的源码！
@appleshell 
@afc163 日前正在准备提 pr

**Comment by appleshell** [comment]
不好意思，是我代码没看仔细，说的不严谨。mousedown触发的下拉框显示的[源码](https://github.com/react-component/select/blob/master/src/Selector/index.tsx#L225)。下拉框消失的源码[L846](https://github.com/react-component/select/blob/master/src/generate.tsx#L846)和[L668](https://github.com/react-component/select/blob/master/src/generate.tsx#L668)。不过这只限于用鼠标操作的情况，select组件的触发情况有点复杂。

**Comment by appleshell** [comment]
因为设置了`notFoundContent={null}`，所以鼠标点击时没有显示下拉框，其实`open`属性已经为true。如果不设置`notFoundContent`，那么下拉框就会显示，只不过显示的是“暂无数据”，基于此我说这不是bug。但是体验上确实有优化的空间。 @afc163 @bigbigDreamer

**Comment by bigbigDreamer** [comment]
> 因为设置了`notFoundContent={null}`，所以鼠标点击时没有显示下拉框，其实`open`属性已经为true。如果不设置`notFoundContent`，那么下拉框就会显示，只不过显示的是“暂无数据”，基于此我说这不是bug。但是体验上确实有优化的空间。 @afc163 @bigbigDreamer

这其实跟体验没有任何关系，只是对于`onDropdownVisibleChange `这个函数的处理有一些缺漏，正如你所说的，因为设置了`notFoundContent={null}`，所以没有显示下拉框，但是函数的返回值却是`true`。往上注意这个`bug`，我的描述，这个函数的**本意**是用来处理什么的。少了`case by case`的处理。

而我这里有业务场景恰好就是需要这个返回值做一些事，并且**还不需要展示暂无数据的样式**。

所以这种小`bug`只有在不同的业务场景下才能体现，而这也是开源的目的。

**Comment by afc163** [comment]
Trace #30624
