### ISSUE TITLE
希望table组件的onRow-onClick 与其他事件（例：点击鼠标拖拽选中数据）不会冲突

### ISSUE THREAD

**Issue by xiaodiqaq** [ant-design/ant-design#28403]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
击鼠标拖拽选中table里的数据，也会触发onRow-onClick 事件

### What does the proposed API look like?
希望table组件的onRow-onClick 与其他事件（例：点击鼠标拖拽选中数据）不会冲突

**Comment by afc163** [comment]
这个是浏览器的事件机制，和 antd 关系不大。

**Comment by BEE-JN** [comment]
我也碰到了此类问题，onRow方法的单击事件与单元格中的按钮点击出现冲突，还没有发现比较好解决方法

**Comment by BEE-JN** [comment]
见此issue: https://github.com/ant-design/ant-design/issues/27492
单元格中包含冲突事件的event可以阻止冒泡，避免执行table onRow中的事件。
