### ISSUE TITLE
升级antd版本，最后build出来的文件很大，chunck文件没有按需打包

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2841]
antd版本：1.9.1
react版本:0.14.x
将antd版本切换到0.12.x 打出来的chunck文件就正常

官方能给个方案优化麽

**Comment by wuhaih** [comment]
经定位 打包出来的chunck文件，有着大量重复的代码，为什么新版ANTD组件没有按需加载打包

**Comment by afc163** [comment]
给一个可重现的 git repository。并按模板描述问题：https://github.com/ant-design/ant-design/issues/new

语焉不详的提问，没人能帮助到你。

---

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by wuhaih** [comment]
问题已经解决，我使用自己写的webpark配置搞定了，atoolbuild不知道问题在哪里，公共的没有抽出来

**Comment by afc163** [comment]
你可以把解决方案放一放，以帮助碰到相同问题的其他人。

**Comment by hbrls** [comment]
@wuhaih 是指那个 babel-plugin 吗？
