### ISSUE TITLE
antd 4.9.1版本，message toast提示报警告

### ISSUE THREAD

**Issue by wangchen9074** [ant-design/ant-design#28416]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
react-dom.development.js?7f13:507 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in CSSMotion (created by CSSMotionList)

### What is expected?
message.success('操作成功')   调用该组件后不会报警告。

### What is actually happening?
首次调用会报 重现链接中的警告

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 16.8.6 |
| System | mac os |
| Browser | 谷歌浏览器 版本 87.0.4280.88（正式版本） (x86_64) |

![image](https://user-images.githubusercontent.com/23378127/102591563-2db42500-414d-11eb-983d-2c29ac77c15a.png)
首次调用message组件的时候，会报该警告

**Comment by Stupidism** [comment]
看起来跟你调用这个的代码触发的时间有关（即跟写法有关，建议贴一下局部代码

**Comment by wangchen9074** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-izg4b?file=/index.js
是因为react版本的原因吗？比如这个例子中，react和react-dom的版本是16.8.6
加上message的toast以后，控制台就会警告。

**Comment by afc163** [comment]
看上去是 React 版本的问题，我升级到 16.14.0 后警告就消失了：https://codesandbox.io/s/antd-reproduction-template-forked-yh0jp?file=/index.js
