### ISSUE TITLE
[Table] Not taking up full width when combining with Row

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#28419]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0h73z?file=/index.js)

### Steps to reproduce
Enter the Reproduction link.

### What is expected?
Table should take up full width.

### What is actually happening?
Table didn't take up full width.
![image](https://user-images.githubusercontent.com/50612752/102593536-f3985280-414f-11eb-9404-a8bfa665eb90.png)

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react 17.0.1 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by shaodahong** [comment]
Yep, but in [doc](https://ant.design/components/grid/)

> Your content elements should be placed directly in the col, and only col should be placed directly in row.

because row use flex layout, and `flex-grow` default 0, so if contain content can't reach full maybe as shown above

so we can write this

```jsx
<Row>
  <Col span={24}>
    <Table />
  </Col>
</Row>
```

**Comment by AlanCutFlim** [comment]
Thanks, i get it 😄
