### ISSUE TITLE
Primary Text color should be 65% black, not 85%

### ISSUE THREAD

**Issue by dahmc** [ant-design/ant-design#28411]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/typography/](https://ant.design/components/typography/)

### Steps to reproduce
The color guidelines at https://ant.design/docs/spec/colors#Neutral-Color state that the primary text color should be a 65% black.

However, across all components, the primary text color seems to be the title color of 85% black.

At https://ant.design/components/typography/ the default color is 85%, but there is not even a primary color option.

### What is expected?
The primary color of all text should be 65% black.

### What is actually happening?
The primary color is 85% black

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | MacOS 10.15.7 |
| Browser | Chrome 87 |

---
Is this intended? And if so, why is the 65% left out? Primary color seems to be the most important one.

For example, in my Figma design system components all the text is designed with the 65% black primary color and it looks much better, that's how I spotted the difference.

**Comment by afc163** [comment]
It is intended change, see https://ant.design/changelog#4.6.0

**Comment by dahmc** [comment]
Thanks @afc163 for clearing that up.

Maybe the documentation should reflect that change then on https://ant.design/docs/spec/colors#Neutral-Color to avoid confusion in the future.

**Comment by afc163** [comment]
I will update it later.
