### ISSUE TITLE
Form中自定义的表单控件setFieldsValue没有作用

### ISSUE THREAD

**Issue by wj0101** [ant-design/ant-design#28423]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5seex?file=/index.js:1594-1608)

### Steps to reproduce
setFieldsValue设置值

### What is expected?
setFieldsValue可以设置值

### What is actually happening?
setFieldsValue不可以设置值

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.8.6 |
| System | mac |
| Browser | Chrome版本 87.0.4280.67（正式版本） (x86_64) |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-14he2?file=/index.js
