### ISSUE TITLE
With the transfer component: Unable to handle the order of the target keys using a custom child

### ISSUE THREAD

**Issue by bnau** [ant-design/ant-design#28420]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
With the transfer component, I need to let the user reorder the target keys by using a custom child component on the right side. 
However, when using custom children components, I only can pass a limited set of props from the "Transfer" to the childre,, and I need more of them to let the children component edit the parent state.

### What does the proposed API look like?
The only props the Transfer component can pass to the children are direction, disabled, filteredItems, selectedKeys, onItemSelect and onItemSelectAll. Adding onChange helped me solving it.

**Comment by bnau** [comment]
#28422

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/28422#issuecomment-758824903
