### ISSUE TITLE
Image.PreviewGroup 动态删除或替换图片，预览状态下还可以显示删除图片

### ISSUE THREAD

**Issue by luchaoqun125** [ant-design/ant-design#28429]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/image-cn/](https://ant.design/components/image-cn/)

### Steps to reproduce
原来一张图片，中间动态替换该图片，当点击预览仍然可以看到替换前后两张图片

### What is expected?
当点击预览仅可以看到替换后展示的图片

### What is actually happening?
预览状态下图片是一个数组，当数组数据进行替换后，预览状态下还可以点击出替换的图片信息。

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 17.0.1 |
| System | mac |
| Browser | 谷歌，版本 87.0.4280.88（正式版本） |

---
列表中预览图片一个，弹框上传图片保存成功刷新列表，列表数据更新，预览切换可以看到原来的图片数据

**Comment by luchaoqun125** [comment]
codesandbox地址： https://codesandbox.io/s/antd-reproduction-template-forked-pcdnr?file=/index.js

代码code如下：

`import React from "react";
import ReactDOM from "react-dom";
import { useState } from "react";
import { Button, Image, version } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const defaultImages = [
  {
    width: 100,
    src: "https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg"
  }
];

function ImagePreview() {
  const [images, setImages] = useState(defaultImages);
  const imagesHandle = () => {
    setImages([
      {
        width: 100,
        src:
          "https://gw.alipayobjects.com/zos/antfincdn/aPkFc8Sj7n/method-draw-image.svg"
      }
    ]);
  };
  return (
    <div>
      <Image.PreviewGroup>
        {images.map((image) => (
          <Image key={image.src} width={image.width} src={image.src} />
        ))}
      </Image.PreviewGroup>
      <Button onClick={imagesHandle}>点击按钮，再点击图片预览出异常</Button>
    </div>
  );
}

ReactDOM.render(
  <div className="App">
    <h1>antd version: {version}</h1>
    <ImagePreview />
  </div>,
  document.getElementById("root")
);
`

**Comment by shaodahong** [comment]
It's resolved in `feature` branch, waiting for the minor release
