### ISSUE TITLE
RangePicker 怎么禁止 单独选择结束和开始时间

### ISSUE THREAD

**Issue by stewingeded** [ant-design/ant-design#28428]
升级了4版本，RangePicker发现，产品和用户经常日期选错，一般用户的交互方式  就是先选择开始时间  在选择结束时间，但是用户经常会点击到结束时间   RangePicker4版本  弹起来了以后  就会先选择结束时间  在选择开始时间，好不容易培养起来的用户  交互行为准则，用户选择日期都不会选择了。

**Comment by stewingeded** [comment]
![image](https://user-images.githubusercontent.com/47906505/102679798-64417c80-41ed-11eb-9c22-96df0a77780a.png)
遇到这种  左右都有禁止选择的日期的时候，用户  不知道他点击  展开日期筛选的时候，他不知道此时 是需要选择结束时间，他以为是开始时间（因为之前的交互行为准则，都是默认是开始时间），所以选择了一个9号  ，结果  他就啥都不能选择。

**Comment by sym900728** [comment]
@stewingeded 找到解决方案了吗？
