### ISSUE TITLE
表格的单选和双选

### ISSUE THREAD

**Issue by 134355** [ant-design/ant-design#28431]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决一个表格即需要双选和单选

### What does the proposed API look like?
const columns = [
  {
    type: 'checkbox',
    key: 'name',
  },
  {
    type: 'radio',
    key: 'age',
  },
  {
    title: '住址',
    dataIndex: 'address',
    key: 'address',
  },
];

**Comment by afc163** [comment]
建议使用 column render 自行处理。

**Comment by 134355** [comment]
自行处理，也不能是随意放置多选和单选啊，它总是在第一，而且，要么是单选要么是多选，不能同时存在
