### ISSUE TITLE
Datepicker支持每月，每日，上周，本周，上月，下月，最近一周，最近一个月选项

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#28436]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
快捷选择日期，虽然现在有这种扩展功能，最好组件内置一些。可以参考Element-ui的DatePicker。参考别人的长处，并不可耻。

### What does the proposed API look like?
快捷选择日期，虽然现在有这种扩展功能，最好组件内置一些。

**Comment by afc163** [comment]
https://ant.design/components/date-picker-cn/#components-date-picker-demo-presetted-ranges

看了下 element，shortcuts 也是需要用户自行指定的。https://element.eleme.io/#/zh-CN/component/date-picker#xuan-ze-yue-fen-fan-wei

**Comment by IFMaggie** [comment]
> 需要用户

这个确实没有ivew 人家的好用方便，最后还是放弃这种的操作
