### ISSUE TITLE
从父组件调用Form组件中的用户自定义函数

### ISSUE THREAD

**Issue by strommmm** [ant-design/ant-design#2843]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：osx ei caption 10.11.6
- 浏览器及其版本: nwjs 51.0.2704.106 

#### 你做了什么？

引入了antd的Modal和Form,
自己构建的一个基于Modal的Component，用Form.create({withRef: true})(Modal)包裹
在其父组件中用ref找到对应的组件， 无法在该组件里找到原Component中的用户自定义的函数
在之前的版本中(1.6.5)，可以在ref中的wrappedComponent中找到对应函数
#### 你期待的结果是：

可以找到 用Form创建的组件中的用户自定义的函数
#### 实际上的结果：

找不到用户自定义的函数

**Comment by EvilsZero** [comment]
也遇到了同样的问题，现在只能通过._reactInternalInstance._renderedComponent._instance方式来获取
业务模拟的在线代码：
http://codepen.io/coldSun/pen/RRXYZg

**Comment by benjycui** [comment]
@EvilsZero 可以给个能反映出问题的 demo 么。。还有步骤。

**Comment by EvilsZero** [comment]
抱歉哈，您看这个可以吗？
#### 本地环境
* codePen配置：同antd官网codePen配置

#### 做的处理
* 创建两个组件Dialog和App，
* Dialog包含了基础组件Modal，
* 其中App包括了子组件Dialog和两个按钮，按钮用以触发打开Dialog里的Modal

#### 期待的结果：
通过App的函数打开Dialog里的Modal

#### 实际上的结果：
只有第一个按钮可以，第二个无法打开

#### 在线演示
[http://codepen.io/coldSun/pen/jrNApm](http://codepen.io/coldSun/pen/jrNApm)

**Comment by benjycui** [comment]
`withRef` ? https://github.com/react-component/form#formoptionwithref-boolean

**Comment by EvilsZero** [comment]
#### 其余条件不变，做了withRef的补充，仍然出现问题
#### 在线地址：
[http://codepen.io/coldSun/pen/xExxqp](http://codepen.io/coldSun/pen/xExxqp)

**Comment by benjycui** [comment]
这儿改坏了 https://github.com/ant-design/ant-design/pull/2534
