### ISSUE TITLE
进一步优化组件在新窗口的显示

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#28435]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://deepmess.com/antd-popup-test/](http://deepmess.com/antd-popup-test/)

这是https://github.com/ant-design/ant-design/issues/28165 的后续

经过上次的修改后，antd在新窗口内基本可用，但是仍有一些小问题。

### Steps to reproduce
点击顶部switch，将components移动到新窗口

正确运行的组件：dropdown，tooltip，select，popconfirm，notification

不正确运行的组件： 
slider：移动时的tootip出现在主窗口

有疑问的组件：
model：model窗口出现在主窗口， 个人感觉model也应该出现在新窗口
现在我的解决方法是，仍然让model出现在主窗口，但是通过代码将新窗口遮挡起来，防止操作，直到model被关闭。实现比较麻烦。

| Environment | Info |
|---|---|
| antd | 4.9.4|
| React | 17.0 |
| System | windows 10 |
| Browser | chrome 80 |

**Comment by rinick** [comment]
我创建了rc-new-window包提供了一些辅助功能来控制窗口位置。
长期的目标是让rc-new-window同时支持浏览器和electron。

**Comment by afc163** [comment]
ping @rinick
