### ISSUE TITLE
table的单选/多选列的宽度固定一个值

### ISSUE THREAD

**Issue by jinbear** [ant-design/ant-design#28446]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
样式统一问题

### What does the proposed API look like?
columnWidth可以是直接固定宽度，或其他属性也可。不要让单选/多选的宽度自适应

**Comment by afc163** [comment]
设置 rowSelection.columnWidth 即可。

**Comment by jinbear** [comment]
> 设置 rowSelection.columnWidth 即可。

这个只会去自动分配宽度，不能直接定死一个宽度

**Comment by afc163** [comment]
> 这个只会去自动分配宽度，不能直接定死一个宽度

最好后面留一列不设宽度以适应自适应布局，否则原生 table 就是这样的，所有列都写死但是表格本身不定宽的话，列设置了宽度也会被拉宽。
