### ISSUE TITLE
表格的单选和双选同时存在或者不是总是在第一列（单选不能取消）

### ISSUE THREAD

**Issue by 134355** [ant-design/ant-design#28442]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能解决单选和双选同时存在
可以根据下面的配置，选项可以在随意位置

### What does the proposed API look like?
const columns = [
{
type: 'checkbox',
key: 'name',
},
{
type: 'radio',
key: 'age',
},
{
title: '住址',
dataIndex: 'address',
key: 'address',
},
];

我认为table的选项设计，根本就是错误的

**Comment by 134355** [comment]
![image](https://user-images.githubusercontent.com/38032758/102732537-ec528e00-4375-11eb-9394-bf61751a66ba.png)
zhe这里应该有取消的按钮

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/28431

自带的选择如果无法满足需求，可以不使用 rowSelection，自行渲染需要的列。
