### ISSUE TITLE
RangePicker 自动切换问题

### ISSUE THREAD

**Issue by hellobq** [ant-design/ant-design#28448]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户体验问题。现在有这么个情况：

假设用户已经选择了起始时间，现在要修改结束时间，当修改完结束时间后，光标又移动到开始时间处了，此时用户还得手动点击一下“确定”按钮。

https://codesandbox.io/s/15lw4?file=/index.js

### What does the proposed API look like?
如果开始时间合法（在结束时间之前），选择完结束时间后，不需要再重新选择开始时间。同样的，如果结束时间合法（在开始时间之后），选择完开始时间后，也不需要重新选择结束时间。

**Comment by afc163** [comment]
这是刻意这么做的，原来的交互也是 `如果开始时间合法（在结束时间之前），选择完结束时间后，不需要再重新选择开始时间`。

原因是为了保证任何情况下的交互一致性，避免开始时间空的时候会跳回第一个，有开始时间的时候不跳，用户在快速操作时很依赖使用习惯，出现不同交互容易误操作。
