### ISSUE TITLE
Table的expandRowByClick属性没效果

### ISSUE THREAD

**Issue by hezhirong** [ant-design/ant-design#2844]
本地环境

antd 版本: 1.8.0
操作系统及其版本：Mac
浏览器及其版本: Chrome
你做了什么？

使用Table的expandRowByClick属性

你期待的结果是：

单击行后展开详情
使用原生rc-table有效果

实际上的结果：

没有展开效果

rc-table example http://react-component.github.io/table/examples/expandedRowRender.html

**Comment by juanpengke** [comment]
设置  expandedRowKeys 和onExpandedRowsChange 可以解决这个问题

**Comment by afc163** [comment]
你都给出文档地址了，文档里是有效的，请按文档书写代码。

**Comment by afc163** [comment]
antd@1.10 目前依赖的 rc-table 是 4.4。

expandRowByClicky 是在 rc-table@4.5 加入的特性，功能以 antd 里的 changelog 为准。
