### ISSUE TITLE
Select TagRender Property not open dropdown when click

### ISSUE THREAD

**Issue by anan953** [ant-design/ant-design#28449]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5um5o?file=/index.js)

### Steps to reproduce
Using tagRender Props to custom tag value. Click Tag -> Not show dropdown 

### What is expected?
Show Dropdown when click custom tagRender 

### What is actually happening?
Not show dropdown when click custom tagRender props 

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.8.6 |
| System | macOS |
| Browser | chrome v87.0.4280.88 |

**Comment by mumiao** [comment]
i mention pr
