### ISSUE TITLE
上传组件PWA安卓不能上传

### ISSUE THREAD

**Issue by focalhot** [ant-design/ant-design#28443]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.iconify.pro](https://www.iconify.pro)

### Steps to reproduce
1. 使用安卓自带浏览器访问https://www.iconify.pro 安装PWA到桌面
2. 从桌面打开iconify.pro程序，点击上传，没有任何反应

### What is expected?
安卓能正常上传图片

### What is actually happening?
MacOS Chrome应用能正常上传，Web版也可以正常上传图片，但安卓不能正常上传图片，

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.13.1 |
| System | Android |
| Browser | Chrome |

---
  ```
// Handle Change
  const handleChange = (info: UploadChangeParam<UploadFile<any>>) => {
    const reader = new FileReader();
    reader.addEventListener('load', () => {
      setImageUrl(reader.result as string);
      setLoading(false);
    });
    reader.readAsDataURL(info.file.originFileObj as Blob);
  };
```

**Comment by afc163** [comment]
请注意 https://caniuse.com/?search=FileReader 的兼容性问题，这不是 antd 的问题，我们也不提供针对移动端的官方支持。欢迎排查后给我们发 PR。
