### ISSUE TITLE
对table设置components，column.shouldCellUpdate 无效

### ISSUE THREAD

**Issue by treasureDouDou** [ant-design/ant-design#28453]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)

### Steps to reproduce
官网示例文档拖拽table，加上column.shouldCellUpdate，column.shouldCellUpdate不执行，若不加components，则正常 

### What is expected?
无

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react |
| System | mac |
| Browser | 谷歌 |

**Comment by treasureDouDou** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-1spku

**Comment by treasureDouDou** [comment]
劳烦解决~

**Comment by treasureDouDou** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-1spku?file=/index.js
劳烦解决

**Comment by zombieJ** [comment]
重现里看起来有 console，不执行指的是？

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-dfjl7?file=/index.js
