### ISSUE TITLE
Warning: [antd: Upload] `transformFile` is deprecated. Please use `beforeUpload` directly.

### ISSUE THREAD

**Issue by YanYuanFE** [ant-design/ant-design#28454]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
```
<Upload
              name="avatar"
              listType="picture-card"
              className={styles.testUploader}
              style={{ width: '100%' }}
              showUploadList={false}
              beforeUpload={(file) => {
                console.log(file);
                const isJpg = file.type === 'image/jpeg';
                if (!isJpg) {
                  message.error('只能上传JPG格式的图片!');
                } else {
                  getBase64(file, (url) => {
                    const img = new Image();
                    img.src = url;
                    img.onload = () => {
                      console.log(img.width, img.height);
                      setSize([img.width, img.height]);
                    };
                    setUrl(url);
                    setFiles(file);
                  });
                }
                return false;
              }}
            >
              {imgUrl ? <img src={imgUrl} alt="avatar" style={{ width: '100%' }} /> : uploadButton}
            </Upload>
```

### Steps to reproduce
Upload组件

### What is expected?
无warning

### What is actually happening?
出现warning

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17 |
| System | mac |
| Browser | chrome87 |

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/102745927-22a10500-4398-11eb-976e-a3c016361468.png)
![image](https://user-images.githubusercontent.com/17774285/102745963-38162f00-4398-11eb-9cb5-47b39adb771c.png)

**Comment by afc163** [comment]
It is intented, check https://github.com/ant-design/ant-design/pull/28365

**Comment by yangmingshan** [comment]
> It is intented, check #28365

@afc163 警告条件写反了，这是个 Bug

**Comment by lovewinders** [comment]
> 警告条件写反了，这是个 Bug

yes,you are right

**Comment by wangweiwg** [comment]
这个问题有解决办法吗？看着控制台报这个好心烦呀

**Comment by afc163** [comment]
@wangweiwg 升级即可修复。
