### ISSUE TITLE
AutoComplete breaking behavior when the options are scrolled over

### ISSUE THREAD

**Issue by tracyhenry** [ant-design/ant-design#28468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/jibenshiyong-antd4102-forked-7xj8s?file=/index.js

### Steps to reproduce
1. Click on the input box, you will see that apple corresponds to options 1, 2, 3, 4
2. Click on the "Pear" radio button. 
3. Click on the input box, you will see that pear corresponds to options 1 to 18.
4. Scroll over the options and leave the scrollbar somewhere in the middle
5. Click on the "Apple" radio button.
6. Click on the input box, you will see options 1-4, which is normal. 
7. Click on the "Pear" radio button.
8. Click on the input box. Now instead of seeing options 1-18, you see only a subset of the options, which is unexpected. 
9. Now start scrolling over the options, you get to see all options 1-18 again. 

### What is expected?
see "Steps to reproduce"

### What is actually happening?
see "Steps to reproduce"

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.14.0 |
| System | Mac OS |
| Browser | Chrome/Safari/Firefox |

---
I tried using dataSource/children / appending options directly as children of AutoComplete. They all reproduced the same bug. There might be some bug deep down in the Select component.

**Comment by tracyhenry** [comment]
Hi, when will this be included in a latest release?

**Comment by tracyhenry** [comment]
@zombieJ @afc163 

ok I just checked - the changes are already in the latest release. However, this problem isn't fixed. The codepen included in the issue body still breaks. Can someone reopen this?

Thanks!

**Comment by HarveyZgit** [comment]
@zombieJ 
The same problem can be reproduced by using the Select.

https://codesandbox.io/s/jibenshiyong-antd4102-forked-oni7g?file=/index.js

**Comment by tracyhenry** [comment]
@afc163  This issue is not fixed. Please reopen it.

**Comment by yoyo837** [comment]
Have you ever tried to delete node_modules and lock files than reinstall?

**Comment by tracyhenry** [comment]
> Have you ever tried to delete node_modules and lock files than reinstall?

I'm not sure what you mean by "lock files". Can you explain?

I can see the changes made by @zombieJ in my reinstall. It's still broken on my machine. It's broken on CodePen too. Are you saying there is a way that works for you? @yoyo837 

Thanks!

**Comment by yoyo837** [comment]
`lock files`: `package-lock.json` or `yarn.lock`.

If there are still problems, please feel free to open a new issue.

**Comment by HarveyZgit** [comment]
> @zombieJ
> The same problem can be reproduced by using the Select.
> 
> https://codesandbox.io/s/jibenshiyong-antd4102-forked-oni7g?file=/index.js

I found a **temporary solution**. Just set `virtual={false}`. However, this will lose part of the performance. It is only recommended to solve this problem **temporarily** when there is **no large amount of data**.

https://codesandbox.io/s/jibenshiyong-antd4102-forked-sbcoo?file=/index.js:1219-1231
