### ISSUE TITLE
antd 3.x 中Modal不可以在render函数中使用，antd 4.x中可以。

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design#28462]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://stackblitz.com/edit/react-dpigb5?file=index.js)

### Steps to reproduce
无法在Table 的columns的render函数中传递封装Modal后的render props

### What is expected?
无法使用。

### What is actually happening?
正常使用。

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | leatest |
| System | windows 10 |
| Browser | edge 86 |

**Comment by afc163** [comment]
1. 你给的例子在 Chrome/Firefox 下看上去都没有问题。
2. 4.0 的例子看上去也没有问题 https://github.com/ant-design/ant-design/issues/28377#issuecomment-746060745
3. antd 3.x 已经不再维护了，建议升级。

**Comment by yoyo837** [comment]
鼠标在右侧iframe与左侧代码范围来回移动，能看到。

**Comment by hankaibo** [comment]
好吧，可惜我们还要在版本3里维护。😂
