### ISSUE TITLE
请问ts编译“Button”不能用作 JSX 组件。这个是什么问题？

### ISSUE THREAD

**Issue by insistenceZHUO** [ant-design/ant-design#28461]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### 错误提示
> ```tsx
> “Button”不能用作 JSX 组件。
>  其返回类型 "ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => >Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)>" 不是有效的 JSX 元素。
>    类型“ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, > any, any>)>) | (new (props: any) => Component<any, any, any>)>”缺少类型“Element”中的以下属性: nodeName, attributes, childrents(2786)
> ```

> ```tsx
>import { Button, message } from 'antd';
>import React, { useState } from 'react';
>
>import { Iprops } from './type.t';
>
>
>const LdBuatton:React.FC<Iprops> = props => {
>  const { onClick, loadingText ='修改中...', successText = '修改成功', loading = false, showMsg=false } = props;
>
> const [laloading, setLaloading] = useState(false);
>
> const handleClick = () => {
>    let hide = null;
>      if (typeof loading === 'undefined' || loading === true) setLaloading(true);
>
>      if (typeof showMsg === 'undefined')
 >       hide = message.loading(loadingText, 0);
>
>
>    onClick((success: any) => {
>      setTimeout(hide, 0);
>      if (typeof loading === 'undefined' || loading === true) setLaloading(false);
>
>      if (success) {
>        if (typeof showMsg === 'undefined')
>          message.success({ content: successText, key: 1, duration: 1 });
>      } else {
>        setTimeout(hide, 0);
>      }
>    });
>  };
>
>  return (
>    <Button {...props} loading={laloading}  onClick={() => handleClick()}>
>        {laloading ? '提交中...' : props.children}
>      </Button>
>
>  );
>};
>export default LdBuatton;
>
> ```
| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.8.6 |
| System | mac os10.15.3 |
| Browser | 版本 81.0.4044.138（正式版本） （64 位） |

**Comment by jiangJade** [comment]
@insistenceZHUO 请问你这个问题解决了吗

**Comment by 969319036** [comment]
??

**Comment by shenzhongkang** [comment]
@jiangJade @insistenceZHUO 
Check your `tsconfig.json` file, set `allowSyntheticDefaultImports` to `true`.
```json
{
  "compilerOptions": {
    "target": "es6",
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["./node_modules/@types"]
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
```

**Comment by jeryqwq** [comment]
一样遇到了这个问题，项目是umi初始化的， 所有从antd引入的组件全部报这个， 但是昨天都好好的，有点郁闷了，给我整不会了

**Comment by letica** [comment]
> 

请问解决了吗？也遇到了

**Comment by jeryqwq** [comment]
@letica  我是因为react项目需要编译.vue文件代码， 所以单独引入了vue依赖， 可能有些东西冲突了， 然后我把vue放cdn引入可以了

**Comment by Juster5** [comment]
> 

我也遇到了一样的问题, 也是umi初始化的项目, 请问你解决了吗?

**Comment by jeryqwq** [comment]
第二次遇到这问题了，终于搞清楚了， 因为你的其他库依赖了@types/react 或者@types/react-dom ，尝试在package.json里面添加这个:  版本改为你指定的版本就好，我的是因为react-router 这个库又安装了18版本的@types/react， 导致双方的ts校验不通过。
@Juster5 @letica 
```
  "resolutions": {
    "@types/react": "17.0.2",
    "@types/react-dom": "^17.0.2"
  },
```

**Comment by florida0723** [comment]
> resolutions

这个确实解决了问题。赞👍

**Comment by duleigiser** [comment]
{
  "compilerOptions": {
    "paths": {
      "react": [ "./node_modules/@types/react" ]
    }
  }
}

modify tsconfig.json

It is telling the typescript compiler that when it encounters a reference to the "react" module, it should look for the actual implementation in the "./node_modules/@types/react" directory.

**Comment by yaderick** [comment]
"typeRoots": ["/xxx/node_modules/@types"] 指定 注解位置解决的

**Comment by leeinn** [comment]
提供一个方向，vscode 使用的 ts 插件可能和项目的 ts 版本不一致，cmd / ctrl + p ->「选择 Typescript 的版本」->「使用工作区版本」

![Image](https://github.com/user-attachments/assets/f8108b8a-a879-4c52-a531-f9652e83bf09)
