### ISSUE TITLE
Upload.tsx bug

### ISSUE THREAD

**Issue by Wtianliang** [ant-design/ant-design#28467]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx](https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx)

### Steps to reproduce
Upload.tsx

### What is expected?
'transformFile' in props

### What is actually happening?
 !('transformFile' in props)

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
Fixed in #28455
