### ISSUE TITLE
在 Table 组件中修改 Paragraph 外层容器字体大小，导致 ellipsis 显示出错

### ISSUE THREAD

**Issue by Lpmvb** [ant-design/ant-design#28460]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-conditional-tooltip-forked-cc9r2?file=/src/index.tsx)

### Steps to reproduce
具体参考重现链接中

### What is expected?
ellipsis 正常显示

### What is actually happening?
ellipsis 显示不正常

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | latest |
| System | Mac OS |
| Browser | Google Chrome 78.0.3904.108（正式版本） （64 位） |

**Comment by Lpmvb** [comment]
仅当字体设置为小于 14px 时出现

**Comment by Lpmvb** [comment]
<img width="1299" alt="0D5C226E-59B3-4844-81B7-82928A149F32" src="https://user-images.githubusercontent.com/34727913/103255527-92307900-49c4-11eb-97f6-66fe134a7de9.png">

在这个例子里，line-heigh 是 18.858px，使用 line-height * row 来计算出来的 maxHeight 会比真实情况要大

https://github.com/ant-design/ant-design/blob/6417e0819b2d6543dc88073287e3da6bf06ff15d/components/typography/util.tsx#L112

在计算 inRange 时就会出错导致多一行

**Comment by yoyo837** [comment]
Trace in #19219
