### ISSUE TITLE
如何扩展icon

### ISSUE THREAD

**Issue by letyougo** [ant-design/ant-design#2846]
#### 本地环境

- antd 版本:1.9.0
- 操作系统及其版本：MACOS
- 浏览器及其版本: chrome

#### 你做了什么？
请问除了修改源码以外，有没有更优雅的方式扩展icon？

**Comment by afc163** [comment]
HOC 方式进行扩展，增加新的 type。

**Comment by letyougo** [comment]
说人话！啥是HOC,HOC又是个啥？

**Comment by afc163** [comment]
https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775

上层扩展组件。
