### ISSUE TITLE
可编辑单元格表格rowSelection清除selectedKeys后，表格勾选未清除，官方demo可复现

### ISSUE THREAD

**Issue by wangtiegang** [ant-design/ant-design#28477]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kebianjidanyuange-antd494-forked-mz7su?file=/index.js)

### Steps to reproduce
1.勾选一行数据
2.点击 Clear Selected，界面勾选未清除，点击 Alert Selected 显示 selectedKeys 已为空数组
3.再勾选一行数据，点击 Alert Selected 显示 selectedKeys 包含两条勾选数据

### What is expected?
点击 Clear Selected 之后，勾选清除，selectedKeys 完全可控

### What is actually happening?
点击 Clear Selected 之后，勾选未清除，selectedKeys 不完全可控

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.14.0 |
| System | windows |
| Browser | 87.0.4280.66 |

**Comment by huangkairan** [comment]
`rowSelection={{
            selectedKeys, //这里应该为selectedRowKeys: selectedKeys
            onChange: (keys) => {
              this.setState({
                selectedKeys: keys
              });
            },
            columnWidth: 60
          }}`

**Comment by huangkairan** [comment]
`rowSelection={{
            selectedKeys,
            onChange: (keys) => {
              this.setState({
                selectedKeys: keys
              });
            },
            columnWidth: 60
          }}`
selectedKeys应该为selectedRowKeys 改为 selectedRowKeys:selectedKeys 即可

**Comment by wangtiegang** [comment]
> `rowSelection={{ selectedKeys, onChange: (keys) => { this.setState({ selectedKeys: keys }); }, columnWidth: 60 }}`
> selectedKeys应该为selectedRowKeys 改为 selectedRowKeys:selectedKeys 即可

尴尬，竟然名称搞错了，没看出来，打扰了，谢谢
