### ISSUE TITLE
`Menu.SubMenu` is different than `SubMenu` from 'antd/lib/menu/SubMenu' in dark theme

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#28474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dingbudaohang-antd494-forked-msk9n?file=/index.js:216-237)

### Steps to reproduce
鼠标移上这2个不同的submenu。

### What is expected?
下拉菜单应该是同样的theme

### What is actually happening?
不同的theme

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome |

---
看其中的一个classname是'ant-menu-undefined' 应该是 'ant-menu-dark'

**Comment by afc163** [comment]
```diff
- import SubMenu2 from "antd/lib/menu/SubMenu";
+ import SubMenu2 from "antd/es/menu/SubMenu";
```

另外强烈不建议从路径引用，应该统一从 Menu.Submenu 引。
