### ISSUE TITLE
Modal closes when clicking popover items 

### ISSUE THREAD

**Issue by lmtNoLimit** [ant-design/ant-design#28470]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate. 
- Old issue [closed]: https://github.com/ant-design/ant-design/issues/27080

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-close-onclick-popover-items-2jhtv)

### Steps to reproduce
1. Create a modal
2. Create a popover button as content of the Modal
3. Open popover and click on an item

### What is expected?
Modal should stay visible

### What is actually happening?
When click on an item of the Popover, the modal close suddenly

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/dialog/pull/218, please upgrade rc-dialog to 8.4.6

https://codesandbox.io/s/modal-close-onclick-popover-items-forked-57s8k?file=/package.json
