### ISSUE TITLE
antd Carousel item节点是实际item节点数量的2倍多

### ISSUE THREAD

**Issue by greenPeppers** [ant-design/ant-design#28471]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5z6bd)

### Steps to reproduce
直接看dom结构

### What is expected?
实现无限轮播增加节点，不应该翻一倍把，我是用这个做监控设备轮播，一页就是128个节点，不超过一页还好，一旦超过一页，页数翻倍，我的监控设备节点也翻倍

### What is actually happening?
轮播页数翻倍，不明白问什么这么做

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | macOS 11.0.1 |
| Browser | chorme  86.0.4240.198 |

**Comment by afc163** [comment]
这是预期的，开启 infinite 后，从最后一个滚动到第一个需要无缝衔接。如果不需要这个效果，可以用 infinite={false} 关闭。
