### ISSUE TITLE
文本输入框希望可以支持emoji表情

### ISSUE THREAD

**Issue by birdOS1** [ant-design/ant-design#2847]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/YICkTEImOIFHSSP.png)

**Comment by birdOS1** [comment]
怎么做到的啊？？？

**Comment by afc163** [comment]
直接输入的。。。。
