### ISSUE TITLE
Tree组件的titleRender属性的参数与文档没有对应

### ISSUE THREAD

**Issue by LiHaoGit** [ant-design/ant-design#28485]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-x5rwx?file=/index.js)

### Steps to reproduce
打开  [codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-x5rwx?file=/index.js) 即可看到

### What is expected?
在 https://ant.design/components/tree-cn/#API 文档中描述的  titleRender 的方法签名是 `(nodeData) => ReactNode` 其中 `nodeData` 的类型是 `DataNode`。  
 查看项目生成的 d.ts文件，详细内容如下  
```
export interface DataNode {
    checkable?: boolean;
    children?: DataNode[];
    disabled?: boolean;
    disableCheckbox?: boolean;
    icon?: IconType;
    isLeaf?: boolean;
    key: string | number;
    title?: React.ReactNode;
    selectable?: boolean;
    switcherIcon?: IconType;
    /** Set style of TreeNode. This is not recommend if you don't have any force requirement */
    className?: string;
    style?: React.CSSProperties;
}
```
`titleRender`的参数应该是`DataNode `类型的

### What is actually happening?
实际是 treeData

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | v17.0.1 |
| System | Windows 10  |
| Browser | Chrome 85.0.4183.102 |

**Comment by LiHaoGit** [comment]
看了下[react-component/tree](https://github.com/react-component/tree/blob/master/src/TreeNode.tsx#L426-L433)，貌似这里没有调用类似`convertNodePropsToEventData`这样的方法

**Comment by LiHaoGit** [comment]
这个不是ant-design的问题，我去给react-component/tree提pr

**Comment by afc163** [comment]
@LiHaoGit ping
