### ISSUE TITLE
form 中的 initialValues 初始值对封装过 select 失效

### ISSUE THREAD

**Issue by zhengAnBin** [ant-design/ant-design#28481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3rq6u?file=/index.js:1262-1275)

### Steps to reproduce
在连接中有详细的步骤和场景

### What is expected?
对封过的select组件设置initialValues可以生效

### What is actually happening?
不生效

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 17.0.0 |
| System | window |
| Browser | chrome84 |

**Comment by haledc** [comment]
我也遇到了同样的问题，求解。

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ubmyn?file=/index.js

**Comment by zhengAnBin** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-ubmyn?file=/index.js

解决了，谢谢您
