### ISSUE TITLE
[Table] Cursor should not change when dragging over other row's handler in Drag sorting with handler demo

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#28480]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuozhuaishoubinglie-antd494-forked-qibmi?file=/index.js)

### Steps to reproduce
Drag a row over other row's sorting handler as shown in the GIF.
![Kapture 2020-12-22 at 17 34 36](https://user-images.githubusercontent.com/50612752/102873361-feb6ef80-447b-11eb-8686-d958a5955512.gif)

### What is expected?
Cursor should not change.

### What is actually happening?
Cursor changed.

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react 17.0.1 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
https://github.com/clauderic/react-sortable-hoc/issues/328#issuecomment-524101055

**Comment by bflemi3** [comment]
The solution in your link doesn't solve @AlanCutFlim's problem. I'm still seeing the cursor flash.
