### ISSUE TITLE
antd表单问题

### ISSUE THREAD

**Issue by wzx997** [ant-design/ant-design#28494]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/wzx997/antd_v4/blob/dev/src/pages/user/userUpdateForm.jsx](https://github.com/wzx997/antd_v4/blob/dev/src/pages/user/userUpdateForm.jsx)

### Steps to reproduce
父组件调用子组件的更新表单，父组件将需要更新的数据传到子组件表单，表单读取this.props时，数据读取正常，但是在模态框表单中显示时却是上一次的值。
<UserUpdateForm
             setForm={(form) => {this.UserUpdateForm = form}}
             user={this.user}
/>
上述是父组件

render() {
        const {user} = this.props;
        console.log(user);
        return (

            <Form {...layout} name="normal_login" ref={this.formRef}>
                <Input value={user.username} />
                <Form.Item
                    name="username"
                    label='用户名'
                    initialValue={user.username}
                >
                    <Input  disabled/>
                </Form.Item>

                <Form.Item
                    label="手机"
                    name="mobile"
                    // initialValue={user.mobile} hasFeedback
                    rules={[{pattern: /^1[3|4|5|7|8][0-9]\d{8}$/, message: '请输入正确的手机号'},]}
                >
                    <Input />
                </Form.Item>

                <Form.Item
                    label='邮箱'
                    name="email"
                    // initialValue={user.email}
                    hasFeedback
                    rules={[{type: 'email', message: '邮箱地址格式不正确！'}]}
                >
                    <Input placeholder="请输入邮箱地址"/>
                </Form.Item>

                <Form.Item
                    name="create_time"
                    label='注册时间'
                    // initialValue={user.create_time}
                >
                    <Input disabled/>
                </Form.Item>

            </Form>
        );
    }
子组件接收到值后打印是正确值，未被Form.Item包裹的输入框也是正确值，但是被包裹的组件设置初始值时却一直维持上一次操作的值，即使在关闭更新模态框时清空表单该情况还是会发生。

### What is expected?
表单初始值结果与this.props收到的一致

### What is actually happening?
表单初始值结果与this.props收到的不一致，而是上一次的值。

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | "react": "^17.0.1", |
| System | win10 |
| Browser | 360极速浏览器 |

**Comment by yoyo837** [comment]
github克隆太慢了，方便的话，能不能提供个online demo?可以修改的那种？

**Comment by wzx997** [comment]
暂时没法提供，因为这是前后端分类的，提供了也改不了，前后端均部署在本地

**Comment by yoyo837** [comment]
不是要完整的项目代码，能交流有问题的那部分即可，demo即可。

**Comment by wzx997** [comment]
<Modal
                    title="更新用户信息"
                    visible={visible}
                    confirmLoading={confirmLoading}
                    onOk={this.userUpdateSubmit}
                    onCancel={()=>{
                        this.UserUpdateForm.current.resetFields();
                        this.setState({
                            visible: false,
                        });
                    }}
                >
                    <UserUpdateForm
                        setForm={(form) => {this.UserUpdateForm = form}}
                        user={this.user}
                    />
</Modal> 
这是父组件，我想把user这个值传到UserUpdateForm这个子组件中。

下面是UserUpdateForm组件部分：
render() {
        const {user} = this.props;
        console.log(user);
        return (
            <Form {...layout} name="normal_login" ref={this.formRef}>
                <Input value={user.username} disabled/>
                <Form.Item
                    name="username"
                    label='用户名'
                    initialValue={user.username}
                >
                    <Input disabled/>
                </Form.Item>

                <Form.Item
                    label="手机"
                    name="mobile"
                    initialValue={user.mobile} hasFeedback
                    rules={[{pattern: /^1[3|4|5|7|8][0-9]\d{8}$/, message: '请输入正确的手机号'},]}
                >
                    <Input />
                </Form.Item>

                <Form.Item
                    label='邮箱'
                    name="email"
                    initialValue={user.email}
                    hasFeedback
                    rules={[{type: 'email', message: '邮箱地址格式不正确！'}]}
                >
                    <Input placeholder="请输入邮箱地址"/>
                </Form.Item>

                <Form.Item
                    name="create_time"
                    label='注册时间'
                    initialValue={user.create_time}
                >
                    <Input disabled/>
                </Form.Item>

            </Form>
        );
    }
打印user这个对象没问题，单独用输入框也没问题，被包裹后就有问题了。

**Comment by yoyo837** [comment]
是什么问题，不是很明白

**Comment by wzx997** [comment]
可否提供邮箱，我上次运行结果，这里没法上传图片

**Comment by yoyo837** [comment]
请基于 https://codesandbox.io/s/antd-reproduction-template-6e93z 修改一个demo

**Comment by wzx997** [comment]
有很多代码，负责部分编译没法通过。这个问题在antd3里面确实没有，使用姿势一样，但就是不正确

**Comment by wzx997** [comment]
复制部分

**Comment by yoyo837** [comment]
有问题的那部分单独组织一个demo即可
