### ISSUE TITLE
Select的options更新不会触发选择框内容更新

### ISSUE THREAD

**Issue by janryWang** [ant-design/ant-design#28495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd494-forked-rj9j7)

### Steps to reproduce
点击修改Label，再点击恢复Label

### What is expected?
选择框内容更新

### What is actually happening?
并未更新

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.x |
| System | osx |
| Browser | chrome |

**Comment by jameslahm** [comment]
Hi, I try your reproduce demo and it's expected. The options have been updated when clicking the labels.

**Comment by janryWang** [comment]
> Hi, I try your reproduce demo and it's expected. The options have been updated when clicking the labels.

https://codesandbox.io/s/jibenshiyong-antd494-forked-mezyz?file=/index.js look this demo

**Comment by jameslahm** [comment]
Hi, I am working on this. The problem should be caused by that the true label is replaced by `cacheLabel` when the label equals the value in options.
