### ISSUE TITLE
antd表单问题

### ISSUE THREAD

**Issue by wzx997** [ant-design/ant-design#28493]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/wzx997/antd_v4/blob/dev/src/pages/user/userUpdateForm.jsx](https://github.com/wzx997/antd_v4/blob/dev/src/pages/user/userUpdateForm.jsx)

### Steps to reproduce
const {user} = this.props;

        console.log(user);
        return (

            <Form {...layout} name="normal_login" ref={this.formRef}>
                <Input value={user.username} />
                <Form.Item
                    name="username"
                    label='用户名'
                    initialValue={user.username}
                >
                    <Input  />
                </Form.Item>

                <Form.Item
                    label="手机"
                    name="mobile"
                    // initialValue={user.mobile} hasFeedback
                    rules={[{pattern: /^1[3|4|5|7|8][0-9]\d{8}$/, message: '请输入正确的手机号'},]}
                >
                    <Input />
                </Form.Item>

                <Form.Item
                    label='邮箱'
                    name="email"
                    // initialValue={user.email}
                    hasFeedback
                    rules={[{type: 'email', message: '邮箱地址格式不正确！'}]}
                >
                    <Input placeholder="请输入邮箱地址"/>
                </Form.Item>

                <Form.Item
                    name="create_time"
                    label='注册时间'
                    // initialValue={user.create_time}
                >
                    <Input disabled/>
                </Form.Item>

            </Form>
        );

### What is expected?
被Form.Item包裹的输入框与没有被包裹的输入框值一样

### What is actually happening?
被Form.Item包裹的输入框的值是上一次的值，而不会实时更新，但是没有被包裹的则会

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | "react": "^17.0.1", |
| System | win10 |
| Browser | 360极速浏览器 |

**Comment by yoyo837** [comment]
React不是Vue，表单自行维护数据，要回写到别的地方请通过onChange等回调刷新值

**Comment by yoyo837** [comment]
Form不支持受控模式。

**Comment by yoyo837** [comment]
想要受控，可以去掉Form.Item的name属性，直接Input等表单控件受控

**Comment by wzx997** [comment]
那这样需要获取该值岂不是又麻烦了，antd3的版本也这样用，但是没这个问题

**Comment by yoyo837** [comment]
antd3也不支持表单受控的呀

**Comment by wzx997** [comment]
但是在antd3里面这样更新是没有问题的，再复述一下我遇到的问题，父组件有个表格，表格数据操作项有个更新操作按钮，点击后打开模态框，模块框中就是上述表单，表单在另外一个组件中，父组件将需要更新的数据传到子组件，子组件通过this.props接收，对于接收到的数据，在控制台打印都是正确的，但是在表单里面想要显示初始值时，那个初始值就是上一次的值，而不是最新的值，如果不容Form.Item包裹，是正确的，包裹后就不正确。

**Comment by yoyo837** [comment]
光靠文字还是太抽象了点，用 https://codesandbox.io/s/antd-reproduction-template-6e93z 创建个demo来交流吧？

**Comment by wzx997** [comment]
我这边已经可以创建demo了，你那边方便看一下吗

**Comment by yoyo837** [comment]
demo链接发一下

**Comment by wzx997** [comment]
稍等，编译没通过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 中午11:10
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"冰河、狂舞"<1181659294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] antd表单问题 (#28493)





 
demo链接发一下

**Comment by wzx997** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-7wldw?file=/index.js
这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 中午11:10
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"冰河、狂舞"<1181659294@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] antd表单问题 (#28493)





 
demo链接发一下

**Comment by wzx997** [comment]
但是好像没有样式了，不知道怎么弄

**Comment by yoyo837** [comment]
不要删除下面两行就有样式了
```js
import "antd/dist/antd.css";
import "./index.css";
```

但是你的链接是个表格，和你说的表单不是一回事

**Comment by wzx997** [comment]
那你可以复现我说的那个问题吗

**Comment by yoyo837** [comment]
你的代码我还没看到呢，你代码在哪里，链接里是个表格，不是你说的表单。

**Comment by wzx997** [comment]
点击更新按钮，模态框中的表单值是上一次的值

**Comment by wzx997** [comment]
点击更新按钮会弹出模态框，表单在模态框中

**Comment by yoyo837** [comment]
看到了，你再附属一下问题？我看着代码来理解

**Comment by yoyo837** [comment]
Form初始化值只在第一次有效，你这里的问题是因为Form在多次打开Modal的工程中就第一次有初始化动作。

**Comment by yoyo837** [comment]
你可以在Modal关闭时销毁Form，使Form每次在Modal打开时都重新初始化

**Comment by wzx997** [comment]
就是点击更新按钮，我会把点击的这条数据传到模态框中的表单中，第一次点击模态框中的表单数据是正确的，但是当我点击下一条数据是，例如你第一次点击第一条数据的更新，第二次点击第二条数据的更新，你会发现第二次的数据是第一次的

**Comment by yoyo837** [comment]
或者是使用form.setFieldsValue来重新设置新值

**Comment by wzx997** [comment]
但是antd3没有这个问题

**Comment by wzx997** [comment]
按道理我关闭modal的时候我已经重置表单数据了

**Comment by yoyo837** [comment]
那你再写个3.x的demo看看？

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-r4334?file=/userList.jsx

看看这个，能解决你的问题吗

**Comment by wzx997** [comment]
只是在关闭的时候加上destroyOnClose这个吗，这确实可以解决，但是antd3不用啊

**Comment by yoyo837** [comment]
那你给个3.x的在线demo我看看

**Comment by voidzlfan** [comment]
赞

**Comment by lhsaq2009** [comment]
```Javascript
import React, {useState} from 'react';
import {Form, Input, Select} from "antd";

export const PlaPerformanceForm: React.FC<any> = (props) => {

    const [abc, setABC] = useState<string>("222222222");

    return (
        <Form>
            <Form.Item name={abc}>
                <Input value={abc}/> {/* 这个值不能跟着变 */}
            </Form.Item>

            <Form.Item name="lsin">
                <Input value={abc}/> {/* 这个值可以跟着变 */}

                <Select onChange={(value: any) => {
                    setABC("fuck123" + value);
                }}>
                    <Select.Option value="1">LITB</Select.Option>
                    <Select.Option value="7">MINI</Select.Option>
                    <Select.Option value="140">ADOR</Select.Option>
                </Select>
            </Form.Item>
        </Form>
    );
};

```
