### ISSUE TITLE
大神您好，请教一下，使用antd上传组件无法显示进度条的问题

### ISSUE THREAD

**Issue by yuan1995913** [ant-design/ant-design#2849]
本地环境：mac pro

- antd 版本: 1.8
- 操作系统及其版本：os
- 浏览器及其版本:chrome

做了什么？

 引入 antd 了 Upload组件 

#### 你期待的结果是：

像官网一样正常显示 ，实现进度条的效果

#### 实际上的结果：

缺少进度条的效果，但是文件可以正常上传，使用的为 fetch

代码：
`render: function () {

    let AudioUploadData = null;
    if (this.props.project != null) {
        if (this.props.project.audioFile != null && typeof this.props.project.audioFile.audioId !== 'undefined') {
            AudioUploadData = {
                projectId: this.props.project._id,
                audioId: this.props.project.audioFile.audioId
            };
        }
        else {
            AudioUploadData = {projectId: this.props.project._id, audioId: null};
        }
    }
    const audioProps = {
        name: 'file',
        showUploadList: false,
        data:AudioUploadData,
        action: '/api/project/saveProjectAudioFile',
        accept: 'audio/mp3',
        beforeUpload(){
            if (AudioUploadData == null) {
                showErrMsg(1, '请先录入项目名称');
                return false;
            }
            else {
                return true
            }
        },
        headers: {
            authorization: 'authorization-text',
        },
        audioHandleChange(info) {
            if(info.file.status !== 'uploading') {
                if(info.file.status === 'done' && info.file.response.errCode == 0) {
                    showErrMsg(0, `${info.file.name} 上传成功。`);
                    //console.log(info.file);
                    //同步store
                    this.props.uploadAudioSyncState(info.file.originFileObj);
                    this.props.uploadChangeState(info.file.response.data.result);
                } else if(info.file.status === 'error') {
                    showErrMsg(-1, `${info.file.name} 上传失败。`);
                } else if(info.file.status === 'done' && info.file.response.errCode != 0) {
                    showErrMsg(-1, `${info.file.name} 上传失败。`);
                }
            }
        },
    };

    return (
        <div>
            <Row>
                <Col>
                    <Upload {...audioProps}>
                        <Button type="ghost">
                            <Icon type="upload"/> 上传音频
                        </Button>
                    </Upload>
                </Col>
    {/*            <Col>
                    <Upload>
                        <Button type="ghost">
                            <Icon type="upload"/> 上传图片
                        </Button>
                    </Upload>
                </Col>*/}
            </Row>
        </div>

    )
}
`

**Comment by yuan1995913** [comment]
`var UploadComponent = React.createClass({

    render: function () {

        let AudioUploadData = null;
        if (this.props.project != null) {
            if (this.props.project.audioFile != null && typeof this.props.project.audioFile.audioId !== 'undefined') {
                AudioUploadData = {
                    projectId: this.props.project._id,
                    audioId: this.props.project.audioFile.audioId
                };
            }
            else {
                AudioUploadData = {projectId: this.props.project._id, audioId: null};
            }
        }
        const audioProps = {
            name: 'file',
            showUploadList: false,
            data:AudioUploadData,
            action: '/api/project/saveProjectAudioFile',
            accept: 'audio/mp3',
            beforeUpload(){
                if (AudioUploadData == null) {
                    showErrMsg(1, '请先录入项目名称');
                    return false;
                }
                else {
                    return true
                }
            },
            headers: {
                authorization: 'authorization-text',
            },
            audioHandleChange(info) {
                if(info.file.status !== 'uploading') {
                    if(info.file.status === 'done' && info.file.response.errCode == 0) {
                        showErrMsg(0, `${info.file.name} 上传成功。`);
                        //console.log(info.file);
                        //同步store
                        this.props.uploadAudioSyncState(info.file.originFileObj);
                        this.props.uploadChangeState(info.file.response.data.result);
                    } else if(info.file.status === 'error') {
                        showErrMsg(-1, `${info.file.name} 上传失败。`);
                    } else if(info.file.status === 'done' && info.file.response.errCode != 0) {
                        showErrMsg(-1, `${info.file.name} 上传失败。`);
                    }
                }
            },
        };

        return (
            <div>
                <Row>
                    <Col>
                        <Upload {...audioProps}>
                            <Button type="ghost">
                                <Icon type="upload"/> 上传音频
                            </Button>
                        </Upload>
                    </Col>
        {/*            <Col>
                        <Upload>
                            <Button type="ghost">
                                <Icon type="upload"/> 上传图片
                            </Button>
                        </Upload>
                    </Col>*/}
                </Row>
            </div>


        )
    }
});
`




不好意思 刚刚代码乱了 请看这里

**Comment by afc163** [comment]
请按模板报告问题。

**Comment by yuan1995913** [comment]
@afc163   抱歉 刚刚太着急了没注意 我重新编辑的一下

**Comment by yuan1995913** [comment]
@afc163  刚刚又研究了下 问题解决了，因为设置了showUploadList: false 打扰了抱歉 :)

**Comment by afc163** [comment]
请自行关闭 issue。
