### ISSUE TITLE
validation 与 datepicker 和 input number 配合使用失败

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#285]

**Comment by afc163** [comment]
可以放到演示里。

**Comment by transtone** [comment]
validation没有正则的例子，不知道怎么用，这样不生效：
rules={[{ type:"regexp", pattern:"^(1[3-8]\d{9})$", required: true }]}

**Comment by YuhangGe** [comment]
已解决，[pull375](https://github.com/ant-design/ant-design/pull/375)。
使用示例见[Validation组件的演示](http://ant.design/components/validation/)
