### ISSUE TITLE
Drawer与DatePicker联合使用时，上下滑动Drawer，DatePicker的日历不会滑动

### ISSUE THREAD

**Issue by wq1997** [ant-design/ant-design#28505]
https://codesandbox.io/s/antd4-datepicker-drawer-2u8r0?file=/src/App.js

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F
