### ISSUE TITLE
请教项目内部图片打包时应该怎样处理

### ISSUE THREAD

**Issue by styushao** [ant-design/ant-design#2850]
#### 本地环境

- antd 版本:1.1.2
- 操作系统及其版本：win7
- 浏览器及其版本:chorome

#### 你做了什么？

引入了一个div，想添加背景,在组件的<div style={styleObj}>
然后styleObje: { 
...
backgroundImage: "url('......jpg')", 
'''
}

非网络图片，项目内有一个assets的文件夹存图片

webpack.config.js:
添加如下：
  webpackConfig.output.publicPath = '/assets/';
  webpackConfig.module.loaders.push({ test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'});

目前在npm start 的时候引用图片失败，请教一下，我的做法是不是欠缺了，什么？
O(∩_∩)O谢谢

**Comment by nowui** [comment]
backgroundImage: 'url(' + require('......jpg') + ')'

**Comment by afc163** [comment]
非 antd 问题，请到 webpack 或其他相关论坛进行提问。

**Comment by styushao** [comment]
@nowui 多谢啦，搞定！

@afc163 叨扰了，谢谢！

**Comment by wboykron** [comment]
@styushao 请问你是如何解决的？
