### ISSUE TITLE
How do I use splitchunks to package ant.design separately? 我如何使用SplitChunks对ant.design进行打包？

### ISSUE THREAD

**Issue by 23cicada** [ant-design/ant-design#28509]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In actual development, with the introduction of unused components, the final package will cause cache invalidation. In this case, I want to package ant.design separately so as not to affect the overall cache of dependent packages. But in the final packaging result, I found that there are lodash, antd, @ant-design, rc-xxx and other packages. How do I use splitchunks to package ant.design separately?

在实际开发中，随着引入未使用过的组件，最终的包会导致缓存失效。在这种情况下，我想把ant.design进行单独打包从而不会影响整体依赖包的缓存。但是在最终的打包结果中，我发现有lodash, antd, @ant-design, rc-xxx 等包，我该如何使用splitchunks对ant.design进行单独打包？

### What does the proposed API look like?
How to package ant.design separately without affecting the overall package cache

能够对ant.design进行单独打包，进而不会影响整体包的缓存

**Comment by yoyo837** [comment]
请查看你使用的打包工具

**Comment by 23cicada** [comment]
> 请查看你使用的打包工具文档



> 请查看你使用的打包工具文档

意思是使用cacheGroups把ant.design相关的包打在一起吗，类似这样  test: /[\\/]node_modules[\\/](antd|@ant-design)[\\/]/ ？

**Comment by 23cicada** [comment]
> 请查看你使用的打包工具文档

但是我不能确定ant.design 相关的包有哪些

**Comment by yoyo837** [comment]
依赖的依赖可能还依赖了别的东西，请根据你需要做打包配置，你这问题我不知道你要干嘛，也不知道怎么回答，也不属于antd范畴。

**Comment by 23cicada** [comment]
> 依赖的依赖可能还依赖了别的东西，请根据你需要做打包配置，你这问题我不知道你要干嘛，也不知道怎么回答，也不属于antd范畴。

我想知道ant.design具体的依赖有那些，我的目的是想把ant.design相关的依赖进行单独打包

**Comment by yoyo837** [comment]
package.json里有写哦。
