### ISSUE TITLE
Form item dynamic rule error message not reset

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#28506]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd494-forked-yrvlu)

### Steps to reproduce
1. Click submit button
2. Click 切换 button
3. Error msg exist

### What is expected?
 Error msg not exist

### What is actually happening?
 Error msg exist

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by zombieJ** [comment]
校验是惰性的，只有满足 `validateTrigger` or `submit` 才会触发校验。动态修改 rule 时需要手工调用 `validateFields` 触发。
