### ISSUE TITLE
Form.List added functionality for new fields

### ISSUE THREAD

**Issue by izrobin** [ant-design/ant-design#28516]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I really want to set autofocus on the newly added dynamic field, in my <Form.List> component.
Perhaps as a configuration object passed into the add() method?

The problems that this would solve is when you have a "list input". Basically one item input per input field. (Maybe in a "Todo" app, or "Groceries" app). You type and item, and can trigger the `add()` method via `onPressEnter`. With focus configured, the cursor/focus would be in the newly added field, and you can continue typing.

### What does the proposed API look like?
```
<Form.List>
  {(fields, {add, remove})} => (
    <>
      {fields.map((field, index) => (
        <Form.Item>
          <Input />
        </Form.Item>
        <Button onClick={() => add('hello hello', {focus: true})}></Button>
      )}
    </>
  )
</Form.List>
```

If the button is clicked, a new field is added, with the initial value of "hello hello", and is also FOCUSED by the browser.

A more practical example is to have an `onPressEnter` even instead:

```
<Form.List>
  {(fields, {add, remove})} => (
    <>
      {fields.map((field, index) => (
        <Form.Item>
          <Input onPressEnter={() => add('hello hello', {focus: true})} />
        </Form.Item>
      )}
    </>
  )
</Form.List>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26834#issuecomment-695941736

**Comment by izrobin** [comment]
I'm sorry, but that linked issue has nothing to do with my feature suggestion.

**Comment by afc163** [comment]
Try `<Input autoFocus />`.

**Comment by izrobin** [comment]
That works... hackishly. 
If I already have some default fields in my `Form.List`, they will steal focus from the entire page. I only want to add focus to the field, after it has been added via the "add" functionality.
