### ISSUE TITLE
Form.List > Space > div > Form.Item - generate error: Warning: Encountered two children with the same key, `0`

### ISSUE THREAD

**Issue by smitroshin** [ant-design/ant-design#28512]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-item-space-issue-bk4kw)

### Steps to reproduce
It is reproduce when we wrap `Form.Item` components with something else instead of `Space` component.

### What is expected?
1) I want to implement any layout inside `Form.List`.
2) Clean console.

### What is actually happening?
All works fine but, in console appear: 
```Warning: Encountered two children with the same key, `0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.```

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | Windows 10 Pro |
| Browser | Google Chrome v87.0.4280.88 |

---
I fix that by replacing `<div>` with `<Space direction="vertical" size={0}>`.
Seems like `Form.Item` components can be wrapped only with `Space` component.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26834#issuecomment-695941736
