### ISSUE TITLE
多选的选择器默认值修改问题

### ISSUE THREAD

**Issue by sunzd116** [ant-design/ant-design#2851]
#### 本地环境

- antd 版本:1.7.0
- 操作系统及其版本：ubuntu16.04
- 浏览器及其版本: chrome 52

#### 你做了什么？
我将多选的selector放入一个Modal，同时它的defaultValue指向了state的一个数组，第一次渲染selector的时候，defalutValues按照state中指定的那个数据显示，但是当修改state那个数组的时，selector的默认值没有发生变化

**Comment by afc163** [comment]
为什么不按模板报告问题呢？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2681

自行研习受控组件概念：

http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by sunzd116** [comment]
已修改为模板样式，谢谢你的解答:)
