### ISSUE TITLE
Direction=RTL, doc search box alignment problem.

### ISSUE THREAD

**Issue by lsky-walt** [ant-design/ant-design#28511]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
1. click RTL button
2. you will find that the placeholder of the search input box is left aligned
3. focus search input box and blur 
4. the placeholder will be right aligned

### What is expected?
all right aligned

### What is actually happening?
align left first, then right

### Image
![image](https://user-images.githubusercontent.com/20224722/102991902-2332ca80-4555-11eb-949c-923052eeea9f.png)

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | all |
| System | macos 10.15.7 |
| Browser | chrome 87.0.4280.88 |

**Comment by xrkffgg** [comment]
嗯，这个问题 我之前就注意到过，其实是 algolia 搜索插件不支持。不过不碍事。

RTL 主要是用于组件的。
