### ISSUE TITLE
table的scroll x 在指定宽度的同时设置列 fix 为left，在超出scroll.x时漏出fix的部分

### ISSUE THREAD

**Issue by zhangwilling** [ant-design/ant-design#2852]
#### 本地环境  

- antd 版本: 1.10
- 操作系统及其版本：mac
- 浏览器及其版本: chrome最新版

#### 你做了什么？
      已经设置每一列的宽度。
      在设置 scroll={{x: 850,y:300}}，同时将前两列column的fix 设置为 true，在屏幕足够大的情况下会漏出fix的列部分。

      上图吧：
      
![image](https://cloud.githubusercontent.com/assets/20391734/17995400/fa647e7c-6b93-11e6-8858-fd51d3b4c9fd.png)

![image](https://cloud.githubusercontent.com/assets/20391734/17995423/353e29a8-6b94-11e6-8ba9-3b96bfe0443c.png)

      

#### 原因分析：
  fix的那部分确实是和我们在column设置的宽度一致的，但是由于屏幕变大了，似乎table就是占父容器的100%宽度，每列的宽度也就变了。也就是说，我们设置的column 的width 没有用啦，而fix的那部分依然是我们设置之前的宽度。

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by zhangwilling** [comment]
http://codepen.io/zhangweilin/pen/mEkYWz
你好，以上是演示地址，用的官网的例子。试着resize浏览器窗口，让浏览器的宽度超过1200px，总之比较大就对了。你会发现，被fix的列，会显示出来

**Comment by afc163** [comment]
http://codepen.io/afc163/pen/ZpEzrb

你需要留一列自动拉伸，否则所有列都不是 `100px`。

**Comment by afc163** [comment]
另一个问题没有重现，给重现了再 reopen 吧。
