### ISSUE TITLE
When using multi-level drawers, the attribute overflow-y: hidden; appears on the body after all are closed.

### ISSUE THREAD

**Issue by wellssu0** [ant-design/ant-design#28528]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce
点击 Multi-level drawer 示例 的 open drawer 按钮 ，弹出后再点击 two-level drawer 按钮，弹出后将两层抽屉关闭，body上会出现overflow-y: hidden; 此时页面不能滚动.

### What is expected?
body上没有overflow-y属性

### What is actually happening?
body上加了overflow-y: hidden属性

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.8.6 |
| System | macos 11.1 |
| Browser | chrome Version 87.0.4280.88  |

---
我自己的项目里出现了这个问题，又查看了官网的示例，发现官网的示例也存在这个问题

**Comment by wellssu0** [comment]
请问多久可以修复这个问题呢？

**Comment by shaodahong** [comment]
> 请问多久可以修复这个问题呢？

预计这个月的 minor

**Comment by demonskp** [comment]
遇到了相同的问题。貌似是rc-util的引用不同 引起的

**Comment by shaodahong** [comment]
> 遇到了相同的问题。貌似是rc-util的引用不同 引起的

这个确实可能会，但是 `rc-util` 是没有锁 minor 版本的，按理说不应该会有多版本的问题

**Comment by demonskp** [comment]
> > 遇到了相同的问题。貌似是rc-util的引用不同 引起的
> 
> 这个确实可能会，但是 `rc-util` 是没有锁 minor 版本的，按理说不应该会有多版本的问题

遇到问题的项目，如果用npm安装 不会有问题最外层rc-util的版本是4.21.1 然后如果用yarn安装会有问题，是5.6.1 如果在项目里主动加一个rc-util 4.21.1的依赖 就没这个问题了

**Comment by shaodahong** [comment]
`rc-util` 4.21.1？，antd 3 么

**Comment by demonskp** [comment]
> `rc-util` 4.21.1？，antd 3 么

是4.X 但是不是具体的版本不确定了。 可能是其他引用的组件库 有antd3的内容

**Comment by shaodahong** [comment]
如果是多版本有点无解，就和 React 多版本一样，也是跑不起来的，只能有一个实例，因为底层实现就是计数器，多版本多个计数肯定有问题

**Comment by demonskp** [comment]
好的 谢谢

**Comment by wellssu0** [comment]
> > > 遇到了相同的问题。貌似是rc-util的引用不同 引起的
> > 
> > 
> > 这个确实可能会，但是 `rc-util` 是没有锁 minor 版本的，按理说不应该会有多版本的问题
> 
> 遇到问题的项目，如果用npm安装 不会有问题最外层rc-util的版本是4.21.1 然后如果用yarn安装会有问题，是5.6.1 如果在项目里主动加一个rc-util 4.21.1的依赖 就没这个问题了

今天项目本地测试是好的，我又在用yarn和npm分别重新装了`node_modules`，测试也都可以滚动，body上只有`style`了。但重新发到测试站上测试还是依然存在问题。

**Comment by shaodahong** [comment]
jenkins 构建的么，jenkins 的话删除下工作空间试试

**Comment by wellssu0** [comment]
> jenkins 构建的么，jenkins 的话删除下工作空间试试
构建项目使用的阿里云的云效Flow

**Comment by wellssu0** [comment]
> jenkins 构建的么，jenkins 的话删除下工作空间试试

构建项目使用的是阿里云的云效Flow

**Comment by shaodahong** [comment]
……没用过，本地好的线上不行听起来很像是缓存的问题

**Comment by wellssu0** [comment]
> ……没用过，本地好的线上不行听起来很像是缓存的问题

上面有清理工作区  ![截图](https://ibb.co/92hbhmN)

**Comment by wellssu0** [comment]
> ……没用过，本地好的线上不行听起来很像是缓存的问题

构建的时候有清理工作区这一步。 官网示例上的这个问题还没解决吗

**Comment by ISBN9527** [comment]
+1今天刚碰到这个问题，查了老一会😓

**Comment by ISBN9527** [comment]
希望早点发版本😭😿

**Comment by ouzhou** [comment]
我的报错了，也是关闭后无法滚动，并且dom节点上有明显的错误
devScripts.js:5836 Warning: React does not recognize the `scrollLocker` prop on a DOM element.
![image](https://user-images.githubusercontent.com/7693866/103183949-6ba10e00-48f0-11eb-975e-41083643b26e.png)

**Comment by ISBN9527** [comment]
还没解决吗？

**Comment by afc163** [comment]
@zombieJ 看看要不要回滚 https://github.com/react-component/util/pull/174

**Comment by wellssu0** [comment]
> ……没用过，本地好的线上不行听起来很像是缓存的问题

今天仔细看了一下云效flow的设置  果然有缓存，把缓存选项去掉重新构建了一遍就正常了，现在测试站用的4.7.3版本。我本地测试过4.7.3，4.8.5，4.9.4都没有问题

**Comment by wellssu0** [comment]
> > ……没用过，本地好的线上不行听起来很像是缓存的问题
> 
> 今天仔细看了一下云效flow的设置 果然有缓存，把缓存选项去掉重新构建了一遍就正常了，现在测试站用的4.7.3版本。我本地测试过4.7.3，4.8.5，4.9.4都没有问题

还有云效flow构建默认使用的cnpm改回了npm 不知道跟这个有没有关系

**Comment by shaodahong** [comment]
> cnpm改回了npm

没关系，当然了 `yarn` 就不好说，摊平方式不一样可能摊成多版本说不定，下次可以 `yarn/npm list rc-util` 看看本地依赖，如果本地有问题的话

**Comment by wellssu0** [comment]
> > cnpm改回了npm
> 
> 没关系，当然了 `yarn` 就不好说，摊平方式不一样可能摊成多版本说不定，下次可以 `yarn/npm list rc-util` 看看本地依赖，如果本地有问题的话

好的
