### ISSUE TITLE
[Select] Option's title prop is not working

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#28525]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd494-forked-kxbiq?file=/index.js)

### Steps to reproduce
Select option `Jack` and hover your mouse over the Select component till tooltip came out.

### What is expected?
According to the [doc](https://ant.design/components/select/#Option-props), Select title should change to the value we set. 

### What is actually happening?
Select title didn't change.

![image](https://user-images.githubusercontent.com/50612752/103072962-a3166e80-4601-11eb-875a-b35f5063d382.png)

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react 17.0.1 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
Try this method as workaround: https://codesandbox.io/s/jibenshiyong-antd494-forked-5f2ym?file=/index.js
