### ISSUE TITLE
InputNumber使用格式化在中文状态下按键会触发两次

### ISSUE THREAD

**Issue by peakandyuri** [ant-design/ant-design#28524]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/#components-input-number-demo-formatter](https://ant.design/components/input-number-cn/#components-input-number-demo-formatter)

### Steps to reproduce
使用官网提供的格式化展示demo，第一个$符格式化的录入框为demo1，第二个%符的格式化为demo2，确保当前输入法状态为中文录入，demo1只要当标在$符号前，或demo2只要光标在%符号后，再在录入框中按字母键盘上的数字键，就会重复触发录入
![GIF](https://user-images.githubusercontent.com/26075324/103072513-aceba200-4600-11eb-9d12-64c4898c0b2f.gif)

### What is expected?
不要录入两次

### What is actually happening?
按一个键会触发两次录入

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.* |
| System | windows |
| Browser | chrome87 |

**Comment by yoyo837** [comment]
Maybe duplicate of #27748

**Comment by afc163** [comment]
Duplicate of #27748

**Comment by verybeautyTang** [comment]
目前还是有这个问题，现在的问题是无论是中文还是英文，%或者其他都会触发两次
