### ISSUE TITLE
多选下拉选择使用搜索功能优化

### ISSUE THREAD

**Issue by FE-zj** [ant-design/ant-design#28531]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
场景：多选下拉选择选项很多，使用搜索功能搜索选项。需要选择多个选项。 然而输入搜索值搜索然后选择一个选项后，搜索值被清空了 又需要输入搜索值，这就很不方便。希望能不清空搜索值

### What does the proposed API look like?
输入搜索值搜索，然后选择选项后保留搜索值

**Comment by afc163** [comment]
`autoClearSearchValue={false}`
