### ISSUE TITLE
Select组件：在ie11浏览器点击Select，下拉框不能弹出。mode=“multiple”时无法输入任何值。

### ISSUE THREAD

**Issue by wills7297** [ant-design/ant-design#28538]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-pond-9o10t)

### Steps to reproduce
codesandbox不支持IE，重现链接没用，在IE11环境下点击Select下拉框不弹出，mode=“multiple”时无法输入任何值。

### What is expected?
在IE11环境下点击Select下拉框弹出，mode=“multiple”时可以输入值。

### What is actually happening?
rc-select的MultipleSelector是通过onChange去setValue的，但是在IE 11上onChange事件不会被触发（onKeyUp可以但是没有写onKeyUp方法），所以表象就是无法输入任何值。

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.13.1 |
| System | Windows |
| Browser | IE 11 |

**Comment by zombieJ** [comment]
Duplicate of #28035

**Comment by Nomad-lau** [comment]
遇到同样的问题在谷歌浏览器，请问是怎么处理的呢
