### ISSUE TITLE
<Select> is closing immediately on mobile (touch devices) when using react-dnd with multi backend

### ISSUE THREAD

**Issue by swashata** [ant-design/ant-design#28532]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dnd-touch-forked-vz71r?file=/src/example.jsx)

### Steps to reproduce
Open the sandbox output https://vz71r.csb.app/ on mobile or with Responsive DevTool mode in Google Chrome.
Click on the Select Dropdown component.

### What is expected?
The dropdown should stay open after clicking.

### What is actually happening?
It is getting closed immediately.

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | MacOS 10.15.6 |
| Browser | Google Chrome Version 87.0.4280.88  |

---
This is happening only with the Touch backend of react-dnd. When in desktop, it is using HTML5 backend and it works perfectly fine.

**Comment by afc163** [comment]
I think it is a react-dnd backend problem.

**Comment by swashata** [comment]
No worries, I will take a look.

**Comment by lukasgjetting** [comment]
@swashata Did you find a solution to this? We are running into the same thing.

Thanks!
