### ISSUE TITLE
time-picker's index.css is missing styles

### ISSUE THREAD

**Issue by SenTisso** [ant-design/ant-design#28536]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ud5bn?file=/index.js)

### Steps to reproduce
1. Simply install antd via `npm i antd`
2. Then import TimePicker via `import { TimePicker } from 'antd'`
3. Then import CSS **only** for the TimePicker component via `import "antd/lib/time-picker/style/index.css"`
4. Then render the TimePicker component in any way (see here https://ant.design/components/time-picker/)
5. Load the page and then you can see that the TimePicker has no styles.
6. Optionally navigato to `node_modules/antd/lib/time-picker/styles/` and open `index.css`. There you can see that the file is missing styles...

### What is expected?
That there are styles for the time-picker and that you don't have to import the whole BIG css file, that can override your global styles.

### What is actually happening?
The css file for the time-picker is missing styles and when rendering the component, it gets rendered without any CSS.

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react 17.0.0 |
| System | Windows 10 |
| Browser | Chrome/87.0.4280.88 |

---
When you try those same steps as described in "Steps to reproduced" for example with a component Button, it works perfectly.

**Comment by SenTisso** [comment]
Just now I've accidentaly found a solution, but the TimePicker remains kinda broken.

When you import css for DatePicker `import "antd/lib/date-picker/style/index.css"`, then the TimePicker looks okay but the css transitions aren't there and the TimePicker doesn't close for some reason and it's just buggy...

**Comment by afc163** [comment]
```diff
- import 'antd/lib/date-picker/style/index.css';
+ import 'antd/lib/date-picker/style';
```

**Comment by SenTisso** [comment]
> ```diff
> - import 'antd/lib/date-picker/style/index.css';
> + import 'antd/lib/date-picker/style';
> ```

@afc163 this does not fix absolutely anything...
see [codesandbox.io](https://codesandbox.io/s/antd-reproduction-template-forked-ud5bn?file=/index.js)

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ykjlc

```css
import 'antd/lib/date-picker/style/index.css'; // don't use it
import 'antd/lib/date-picker/style'; // use less
import 'antd/lib/date-picker/style/css'; // use css
```
