### ISSUE TITLE
【需求】关于Form的Required Mark属性是否可以更灵活一些

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#28546]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Form的Required Mark目前支持boolean | optional
是否可以更灵活一些，我希望必选的是红色字，可选的是蓝色字

### What does the proposed API look like?
boolean | optional | custom

附下图效果说明
![image](https://user-images.githubusercontent.com/8730272/103130643-89942600-46d8-11eb-807e-7bc808dee5f5.png)

**Comment by afc163** [comment]
个性化的设计只能靠自定义样式去实现了。
