### ISSUE TITLE
ProTable column 同时设置 ellipsis,copyable, 在浏览器或系统放大125%时ellipsis失效，这个bug ProTable的开发者要求在ant这边提

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#28547]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://procomponents.ant.design/components/table/](https://procomponents.ant.design/components/table/)

### Steps to reproduce
进入ProTable官网第一个示例，将浏览器缩放调整至125%，可以发现ellipsis失效

### What is expected?
ellipsis生效，内容不能换行

### What is actually happening?
ellipsis失效

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome |

---
https://github.com/ant-design/pro-components/issues/1405

**Comment by afc163** [comment]
same as #28460

**Comment by afc163** [comment]
Duplicate of #19219
