### ISSUE TITLE
Table 行内定义点击事件后，会同时触发onRowClick事件，阻止冒泡都不好使

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design#2854]
我把问题还原在这里了：[点击查查看](http://codepen.io/minooo/pen/rLEPRm?editors=0010)
![image](https://cloud.githubusercontent.com/assets/9410091/18000983/56d7677c-6bb3-11e6-9628-1e12bbda3151.png)

**Comment by afc163** [comment]
这是合理的冒泡行为吧，在业务代码里可以自行决定是否禁止冒泡。

**Comment by minooo** [comment]
@afc163  这样啊，多谢！
