### ISSUE TITLE
Table组件的column中的filterIcon方法存在不能拿到正确的filtered值的情况。

### ISSUE THREAD

**Issue by caiyangL** [ant-design/ant-design#28558]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1kdtj?file=/index.js)

### Steps to reproduce
column.filtered传入受控值时，filterIcon不能拿到这个受控的值。

### What is expected?
我理解上，在传入了受控的filtered后，应该无需判断selectedKeys得到filtered，而是直接拿到传入的column.filtered传给filterIcon即可。

### What is actually happening?
filterIcon方法的实参filtered是判断selectedKeys来得到的。

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | react |
| System | Mac 10.15 |
| Browser | Chrome 87.0.4280.88 |

**Comment by caiyangL** [comment]
第一次pr，请问为何bot留言：PR 的分支已经过了维护期，并自动关闭PR？👀

**Comment by zombieJ** [comment]
如 bot 所述，v3 已经不再维护。

**Comment by caiyangL** [comment]
了解。
