### ISSUE TITLE
Input.search: the enterButton display wrong

### ISSUE THREAD

**Issue by HomyeeKing** [ant-design/ant-design#28557]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tprjv?file=/index.js)

### Steps to reproduce
xx

### What is expected?
show normal

### What is actually happening?
display wrong

| Environment | Info |
|---|---|
| antd | 3.26.19 |
| React | ^16.12.0 |
| System | mac |
| Browser | chrome |

**Comment by HomyeeKing** [comment]
the sandbox show well, but in the project, it shows just like :
![image](https://user-images.githubusercontent.com/49113249/103148246-af80ff80-4798-11eb-8034-24d53e2a17cb.png)


I have not idea why, I've check the whole file, nowhere to modify the class style

**Comment by HomyeeKing** [comment]
@afc163 any idea about it? I know it kind of old version, but it's an old project, so  I need to find where goes wrong since it shows normal in reproduction

**Comment by afc163** [comment]
Your codesandbox works well: https://codesandbox.io/s/antd-reproduction-template-forked-tprjv?file=/index.js

**Comment by HomyeeKing** [comment]
@afc163  I know, but it did display wrong here
![image](https://user-images.githubusercontent.com/49113249/103194277-1974e280-491a-11eb-9469-09063a40921c.png)

do you have any idea about it so I can locate the problem
