### ISSUE TITLE
Form.List with preserve={false} won't re-render when Modal with destroyOnClose={true} re-opens

### ISSUE THREAD

**Issue by EricKim987** [ant-design/ant-design#28561]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/immutable-bird-mwq48?file=/src/App.js:2014-2030)

### Steps to reproduce
点击第三个‘Modal Form List Not Preserved’按钮，再重新打开，里面用Form.List渲染的form不见了

### What is expected?
根据文档，在Modal里的Form关闭时，如果preserve={false}会自动销毁表单数据。https://ant.design/components/modal-cn/#%E6%B3%A8%E6%84%8F

### What is actually happening?
可能是key的问题

| Environment | Info |
|---|---|
| antd | undefined |
| React | react 16.13.1 |
| System | wsl2 - debian buster |
| Browser | chrome |

---
也许是我代码有问题。如果不是的话，我想解决这个bug（以后会提交pr的）

**Comment by zombieJ** [comment]
`destroyOnClose` 表示关闭窗体后不再保留其内容，这使得 Form 内部的字段 `[emails, 0]` 和 `[emails, 1]` 在关闭后被清理。所以下次打开后，列表为空。这是符合预期的行为。
