### ISSUE TITLE
【强烈建议】关于时间范围选择控件的再次优化

### ISSUE THREAD

**Issue by xzf123456** [ant-design/ant-design#28565]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
感觉时间范围选择控件比较难用，现在都是将日期时间拆成两个输入框给用户，因为反馈说有点难用，自己反复体验了之后发现确实很难用。

### What does the proposed API look like?
感觉还是像element 这种比较容易接受一点吧
https://element.eleme.cn/#/zh-CN/component/datetime-picker#ri-qi-he-shi-jian-fan-wei

**Comment by afc163** [comment]
日期范围选择器经过多次优化，目前交互已经比较稳定，除非有比较合理的渐进式优化，暂时不会重构。

**Comment by xiantuteng** [comment]
建议取消这种时间范围控件，太容易引导前端开发用这种控件， 其实大家都不喜欢用。
