### ISSUE TITLE
Select组件 tokenSeparators 对于中文字符无法很好的支持

### ISSUE THREAD

**Issue by JesonSirius** [ant-design/ant-design#28564]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/JesonSirius/pen/YzGYXdK?editors=001](https://codepen.io/JesonSirius/pen/YzGYXdK?editors=001)

### Steps to reproduce
正常输入，用中文逗号分割

### What is expected?
能正常分割成tags

### What is actually happening?
windows下chrome无法实现， mac下支持。

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.7 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
windows 下是什么表现？能来个 gif 不？

**Comment by JesonSirius** [comment]
> windows 下是什么表现？能来个 gif 不？

刚到单位，没带windows的电脑。。。 简单描述下，就是 按了中文的逗号 没有生成tag，  输入框里面就是    XXXX， 
![image](https://user-images.githubusercontent.com/35722299/103186251-bcb5ff80-48fa-11eb-9a2b-33930cd7eb21.png)

**Comment by afc163** [comment]
感觉是微软输入法这个问题 https://github.com/ant-design/ant-design/issues/27748#issuecomment-751561574

**Comment by afc163** [comment]
```
- tokenSeparators={[',', ' ']}
+ tokenSeparators={[',', '，']}
```

加上中文逗号就可以了。

https://codepen.io/afc163/pen/VwKyegd?editors=001

**Comment by JesonSirius** [comment]
> ```
> - tokenSeparators={[',', ' ']}
> + tokenSeparators={[',', '，']}
> ```
> 
> 加上中文逗号就可以了。
> 
> https://codepen.io/afc163/pen/VwKyegd?editors=001

你又在windows下的chrome环境试过吗 ，我的还不行。。。mac上面没有任何问题。。

**Comment by afc163** [comment]
没测试过，我是看你的例子里没加 `，`。

**Comment by yoyo837** [comment]
这边Windows测试正常，可以分割，@JesonSirius 你如何测试的？

**Comment by yoyo837** [comment]
我知道了，是输入拼音不按空格直接按逗号 @zombieJ @afc163

**Comment by yoyo837** [comment]
但是，Mac也一样啊，需要光标blur一下，就能分割了

**Comment by yoyo837** [comment]
![Dec-28-2020 15-03-15](https://user-images.githubusercontent.com/6134547/103195753-dc125400-491d-11eb-891c-b875da1e2ccc.gif)

**Comment by zombieJ** [comment]
神奇，`onSearch` 事件里是什么能打印一下看看不？

**Comment by yoyo837** [comment]
拼音打字键入：`nihaoa，`，`a`后面没有按空格键在预选里选择它（空格就是默认从预选里选第一个）

**Comment by yoyo837** [comment]
> onSearch


并不是Windows特有，mac看就行。
![image](https://user-images.githubusercontent.com/6134547/103196309-eb45d180-491e-11eb-8525-cdbcd3fff4aa.png)

**Comment by JesonSirius** [comment]
其实我定位到了问题，但实在想不通原理。  在rc-select组件里面 ，generate.js 文件454行，triggerSearch方法。
![image](https://user-images.githubusercontent.com/35722299/103197026-3b716380-4920-11eb-8ee1-ddadda3d936c.png)   每次触发方法， isCompositing都是false，但唯独 windows下 chrome里面，中文输入法， 按逗号，isCompositing始终为true，就很奇怪

**Comment by yoyo837** [comment]
是我的操作方法有什么不一样吗？我这里实验的是没有平台的区别。

**Comment by JesonSirius** [comment]
> 是我的操作方法有什么不一样吗？我这里实验的是没有平台的区别。

我的问题，demo里面忘记加中文逗号了。。。。 现在加了， mac下正常 ，windows不行

**Comment by yoyo837** [comment]
我也加了的，两个系统下表现和gif一样

**Comment by yoyo837** [comment]
说说你的案件顺序

**Comment by JesonSirius** [comment]
> 说说你的案件顺序
切到中文输入法，随便打两个字，然后按逗号。  在汉字已经打出来的情况下 按逗号

https://user-images.githubusercontent.com/35722299/103198586-a6706980-4923-11eb-8ada-b962f3e7cae8.mov

**Comment by zombieJ** [comment]
我试了一下搜狗输入法，输入拼音后直接按逗号然后继续输入再回车就可以重现出来：
![截屏2020-12-28 下午3 47 38](https://user-images.githubusercontent.com/5378891/103198726-0535e300-4924-11eb-9e88-40ab852afcba.png)

**Comment by yoyo837** [comment]
@zombieJ 可是他的录屏是先打好字，再按，看不出啥问题。
