### ISSUE TITLE
Radio 设置 validateTrigger 为 submit 的时候，值为 true 和 false，校验不通过

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#28569]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd494-forked-4s5ts?file=/index.js:602-617)

### Steps to reproduce
选择一个单选，点击提交，出现错误

### What is expected?
我想在提交的时候再验证，校验正确

### What is actually happening?
出现错误

| Environment | Info |
|---|---|
| antd | undefined |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/jibenshiyong-antd494-forked-9ujyq
