### ISSUE TITLE
Tooltip  在 Safari中 会出现两种显示， 默认的 html title 属性提示也会显示出来。我看了 表格 Table component 在 定义单元格自定义省略显示时候，也有同样的问题 

### ISSUE THREAD

**Issue by pubdreamcc** [ant-design/ant-design#28566]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-ellipsis-custom-tooltip](https://ant.design/components/table-cn/#components-table-demo-ellipsis-custom-tooltip)

### Steps to reproduce
表格单元格自定义省略 在Safari 中会出现两个 提示 （默认的 html title 属性也会显示出来）

### What is expected?
只显示 一种，ToolTip， 和Chrome 显示 一致

### What is actually happening?
表格单元格自定义省略 在Safari 中会出现两个 提示 （默认的 html title 属性也会显示出来）

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.13.1 |
| System | Mac OS  |
| Browser | Safari  |

**Comment by afc163** [comment]
这是 Safari 的特性，`text-overflow: ellipsis` 会自动加上 title。好像没什么办法。

**Comment by yoyo837** [comment]
可以考虑下Safari时不给title属性，但是否必要就见仁见智了。

**Comment by pubdreamcc** [comment]
> 这是 Safari 的特性，`text-overflow: ellipsis` 会自动加上 title。好像没什么办法。
刚google 找到了一方法，给 text-overflow: ellipsis 的元素内部包裹一个空 的块元素即可解决。
要不你们下个版本解决下。

**Comment by yoyo837** [comment]
来个PR看看效果？

**Comment by pubdreamcc** [comment]
好，我看下

**Comment by pubdreamcc** [comment]
刚刚试了下，这个 不需要 改版本代码，如果不想  Safari 中出现差异性，将 Tooltip 里面包裹一个 空 div 即可

**Comment by Lliuxs** [comment]
@afc163  这个是不是组件库解决下会比较好。 业务为了一个兼容性的问题给tooltip都包一层空的div是否合理
