### ISSUE TITLE
Ref attribute not available on many components (Card, Collapse)

### ISSUE THREAD

**Issue by Tmilly** [ant-design/ant-design#28582]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Why is it not possible to bind to ref attribute on components such as Card. I ran into this while making content cards that are draggable from react-beautiful-dnd. It is required to send an innerRef to the component you are using. Has anyone run into this? Is there an alternative solution?

### What does the proposed API look like?
Pass ref as a property on components like Card and Collapse.

**Comment by afc163** [comment]
Duplicate of #19764
