### ISSUE TITLE
关于表格头左右拖拽的问题

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#28588]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
请问表格头左右拖拽必须设置宽度吗
https://codesandbox.io/s/keshensuolie-antd494-forked-84zjv?file=/index.js
不设置宽度拖拽不起作用

### What does the proposed API look like?
怎么不添加宽度就可以实现表格头左右拖拽呢

**Comment by afc163** [comment]
https://www.npmjs.com/package/react-resizable 目前是需要指定宽度的。
