### ISSUE TITLE
form.resetFields() 没用重置 Checkbox 的勾选状态

### ISSUE THREAD

**Issue by teddy1004** [ant-design/ant-design#2858]
#### 本地环境

- antd 版本: 1.8.0
- 操作系统及其版本: macOS Sierra Public Beta 6
- 浏览器及其版本: Chrome 52.0.2743.116

#### 你做了什么？

在 form 表单提交后，调用 form.resetFields()

#### 你期待的结果是：

Checkbox 的值是未勾选，浏览器看到的样式也是未勾选

#### 实际上的结果：

Checkbox 的值确实是未勾选，但是浏览器里看到的还是处于勾选状态的

#### 可重现的在线演示

http://lucifier129.github.io/ant-design/components/form/#demo-validate-other

官网的 Demo 就可以重现这个问题，先勾选选项，再按重置按钮，这时看到的还是勾选的，但是值已经清掉了

**Comment by afc163** [comment]
请查看官方站点：http://ant.design/components/form/#components-form-demo-validate-other

**Comment by wangxiaofeid** [comment]
有一样的问题

**Comment by teddy1004** [comment]
@wangxiaofeid 要在 getFieldDecorator 里加上 `valuePropName: 'checked'` 就可以了
