### ISSUE TITLE
 antd release3.x  can be  code-autocomplete but release4.x cannot.

### ISSUE THREAD

**Issue by ivyqingcheng** [ant-design/ant-design#28584]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/users/ivyqingcheng/projects/1   //nothing](https://github.com/users/ivyqingcheng/projects/1   //nothing)

### Steps to reproduce
举例子就是之前采用antd3.x版本，工具是idea，在<Table>标签中，输入col即可提示出columns ，并且ctrl 鼠标左键可以找到定义文件，但是新项目antd4.9就不可以了，对比2个版本 发现 /antd/lib/table/interface.d.ts中的定义内容不一样了，感觉上可能是这个原因造成的无代码提示，这是新版本本身就如此吗，还是可以调整出来？
For example， as antd-release3x when I use  <Table> ，the complete property name appears  after writing "col"  .But in the new project I use antd4x it,the code autocomplete didn`t work . Comparing 2 realease ,I find the typedefine file " /antd/lib/table/interface.dts" is different 。How I can get  code autocomplete in antd-release4.X

### What is expected?
存在代码提示

### What is actually happening?
无代码提示，ctrl单击属性无法找到定义文件

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17 |
| System | win 10 |
| Browser | chrome |

**Comment by afc163** [comment]
你可以用 vscode 测试一下，如果可以，那么可能是 IDEA 或者 IDEA 配置的问题。

**Comment by ivyqingcheng** [comment]
https://segmentfault.com/q/1010000021933799

**Comment by ivyqingcheng** [comment]
> Since the issue was labeled with `needs-more-info`, but no response in 3 days. This issue will be closed. If you have any questions, you can comment and reply.
> 
> 由于该 issue 被标记为需要更多信息，却 3 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

https://segmentfault.com/q/1010000021933799   可以看看这个链接，这应该不是我一个人的问题，百度上也有别人出现过。
