### ISSUE TITLE
Table提供鼠标双击选中(鼠标选中移动)某个columns的item，目前会和onRow的onClick冲突

### ISSUE THREAD

**Issue by Time-erhu** [ant-design/ant-design#28590]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在多页面报表场景时，需要进行多个报表数据比对，查看，当使用了onRow的onClick事件时，复制某个数据就变的异常艰难，会和onClick产生冲突
1-：可单击或者双击选中某行，
2-：未选中和选中某行数据时，点击item的文本区域，可双击复制，同时，选中的item,可进行CSS定制

### What does the proposed API look like?
<Table 
 canCopyColumns
/>

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27492
