### ISSUE TITLE
使用Modal 组件的modalRender属性创建的元素无法点击

### ISSUE THREAD

**Issue by Liu7i** [ant-design/ant-design#28598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/antd-reproduction-template-forked-53smw

### Steps to reproduce
见CodePen 连接

export default UpdataPlan;

### What is expected?
点击按钮出现模态框，点击模态框的按钮控制台输出123并alert()字符串

### What is actually happening?
没有反应，点击模态框按钮后模态框直接关闭了

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React |   "react": "^16.8.6" |
| System | win10 |
| Browser | Chrome版本 87.0.4280.66（正式版本） （64 位） |

---
一开始以为是z-index的问题，测试了一下发现并不是

**Comment by Liu7i** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-53smw

**Comment by xrkffgg** [comment]
其实是因为 `.ant-modal` 默认加了样式 `pointer-events: none`

你只需要在你想要交互的组件上 加个 `style={{pointer-events: auto}}` 就行了

**Comment by Liu7i** [comment]
> 其实是因为`.ant-modal`预设加了样式`pointer-events: none`
> 
> 你只需要在你想要互动的组件上加个`style={{pointer-events: auto}}`就行了

谢谢，问题已解决

**Comment by xrkffgg** [comment]
是 style={{ pointerEvents: 'auto'}}

**Comment by xrkffgg** [comment]
😂😂 顺手了，语法应该是这样

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-p3210?file=/index.js

**Comment by Liu7i** [comment]
谢谢各位帮助，学习了

**Comment by wtl1019** [comment]
如何做到点击蒙层关闭啊？？？

**Comment by suiboyu** [comment]
> 



> 如何做到点击蒙层关闭啊？？？

https://github.com/ant-design/ant-design/issues/35512

或许可以参考一下这个
