### ISSUE TITLE
IE11 Select组件无法弹出下拉选择框

### ISSUE THREAD

**Issue by neitherzhu** [ant-design/ant-design#28593]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
官网页面顶部切换版本的选择框在IE11上无法出现

### What is expected?
能够正常弹出选择框

### What is actually happening?
选择框在IE11上无法出现

| Environment | Info |
|---|---|
| antd | undefined |
| React | 15.6.2 |
| System | windows |
| Browser | IE11 |

**Comment by yoyo837** [comment]
网页还没完全打开把？试试国内镜像。

**Comment by neitherzhu** [comment]
> 网页还没完全打开把？试试国内镜像。

要用IE11 你那边进入Select组件里面，Select组件能正常使用？

**Comment by xrkffgg** [comment]
@neitherzhu https://github.com/ant-design/ant-design/issues/21039 看看有帮助没
