### ISSUE TITLE
Collapse中使用checkbox，form提交发现值不对

### ISSUE THREAD

**Issue by jpdan** [ant-design/ant-design#2859]
- antd 版本: 1.10
- 操作系统及其版本：
- 浏览器及其版本: chrome

刚接触到antd，有个问题请教下
步骤1：选中Collapse中北京，下面panle会全选:
步骤2：点击"东城“会取消选中，上面“北京“也取消选中了
步骤3：点击提交按钮，发现“p_北京“的值还是true，除非手动点击Collapse中北京checkbox，p_北京的值才会为false，外观上都勾中或取消了，但是value不对，不解？

在线演示
http://codepen.io/jpdan/pen/NAQRrL?editors=0010

**Comment by leopardoooo** [comment]
这个是个问题，我也遇到了，后来改成原生checkbox自己实现了！

**Comment by benjycui** [comment]
因为你把 `getFieldProps` 返回的 `checked` 覆盖了，然后如果你需要手动修改 `header` 里面那个 `Checkbox` 的值，请用 `setFieldsValue`。

**Comment by jpdan** [comment]
多谢指点，按你的指点修改了下，发现还是不行，由于刚开始学习react、antd，求具体指点，修改的代码附上http://codepen.io/jpdan/pen/NAQLaY?editors=0011
还有几个问题求解：
1、这样给p_北京、c_北京附初始值，直接点击header中checkbox，c_北京的值是undefined
2、cityOptions值很多个省数据，放在state中，当点击很多个省checkbox时，会有点延迟卡顿选中的感觉
![image](https://cloud.githubusercontent.com/assets/3361732/18039771/839626dc-6dd8-11e6-8fd3-2961cc177860.png)

**Comment by benjycui** [comment]
`CityPanel` 试着加 `shouldComponentUpdate`，性能优化是强绑定于业务场景的，所以给不了你具体建议。
