### ISSUE TITLE
Select "multiple" mode: dynamically created options don't show up

### ISSUE THREAD

**Issue by StefanoSega** [ant-design/ant-design#28600]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ts-r1gg5b?file=DurationPicker.tsx](https://stackblitz.com/edit/react-ts-r1gg5b?file=DurationPicker.tsx)

### Steps to reproduce
Type in the Select something in the format "AMOUNT UNIT_OF_TIME"
e,g,: "1 second", "5 minutes", "10 days", "33 hours"

### What is expected?
when e.g. typing "1" it should show as available options ["1 second", "1 minute", "1 hour", "1 day"]
when typing "2 s" it should show as available option only "2 seconds"

### What is actually happening?
when typing "1" it shows only "1 second"
when typing "2" it shows all the correct options
when typing "2 s" it shows no options

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | MacOs Catalina v10.15.7 |
| Browser | Chrome v87 |

---
logging on console the array of values to be rendered as options (`optionsValues`) it contains the correct values

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-ts-llc9jh?file=DurationPicker.tsx

```diff
+ filterOption={false}
```

**Comment by StefanoSega** [comment]
Thanks a lot 👍
