### ISSUE TITLE
Found 2 elements with non-unique id #rc_select_0 (updated)

### ISSUE THREAD

**Issue by gmoniava** [ant-design/ant-design#28609]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd494-forked-byc32?file=/index.js)

### Steps to reproduce
For both Select and TreeSelect manually inspect id of `input` located under `span` with class `ant-select-selection-search` and see they are same. 

### What is expected?
Different Selects should have different id.

### What is actually happening?
inputs of Select and TreeSelect have same id and I get this warning on my project (on Sandbox link you might not see this warning maybe because it is in Sandbox, but ids are same anyway): 

![103300938-90dd6b80-4a19-11eb-9fd3-0fc70cd3c5e2](https://user-images.githubusercontent.com/76407133/103307745-4b756a00-4a2a-11eb-9657-37ac0317bb25.png)

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.14 |
| System | Unknown |
| Browser | Chrome 87.0 |

---

**Initially I thought that moving antd to version 4.9.4 fixed the issue, because on my sandbox link the ids became different when I switched to latest version, but I still think they became different for 4.9.4 because of accident on the code sandbox link (and one needs different reproduction example for 4.9.4), because in my project changing version to 4.9.4 doesn't help. So please consider this issue carefully.**

btw This is not duplicate of some similar issues here which suggest to use different `name` on `Form`, because I don't use `Form` here, just `Form.Item`s.

**Comment by afc163** [comment]
Problem gone when upgrade to antd 4.9.4: https://codesandbox.io/s/basic-antd494-forked-vlgdj?file=/package.json

**Comment by gmoniava** [comment]
@afc163 **Like I said above, please check carefully, in my project, moving to antd 4.8.4 doesn't solve the problem. Why?** I even deleted node_modules folder.
That is why I think for 4.9.4 it needs different reproduction example (more Select components).

**Comment by afc163** [comment]
Could you try to remove your yarn.lock and package-lock.json, then reinstall node_modules again?

**Comment by gmoniava** [comment]
@afc163  Deleting yarn.lock solved the issue!
