### ISSUE TITLE
<Input /> style is not working when i using 'prefix'

### ISSUE THREAD

**Issue by wygkzqa** [ant-design/ant-design#28615]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qianzhuihehouzhui-antd494-forked-pn070?file=/index.js)

### Steps to reproduce
1. enter text to first <Input />, you can see the text color is 'red'
2. enter text to second <Input />, you can see the text color is no change

### What is expected?
the second <Input /> will be render 'red' text

### What is actually happening?
the second text color is no change

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.14.0 |
| System | macOS 11.1 |
| Browser | Chrome 87 |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/eb01bee6beb045f72f5d4ce9645fb0ce98102eb1/components/input/ClearableLabeledInput.tsx#L137

**Comment by xrkffgg** [comment]
不确定是设计还是 bug，也可以用 className

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/26642#issuecomment-688875216

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6877#issuecomment-315957736

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9941#issuecomment-379516030

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14902#issuecomment-465453189

**Comment by wygkzqa** [comment]
> 不确定是设计还是 bug，也可以用 className

https://codesandbox.io/s/qianzhuihehouzhui-antd494-forked-pn070?file=/index.js

我试了一下 className 也不生效

**Comment by xrkffgg** [comment]
class 是加到最外层的，你可以点开 F12 看看 div 结构，然后在对应的 模块上添加样式

**Comment by wygkzqa** [comment]
> class 是加到最外层的，你可以点开 F12 看看 div 结构，然后在对应的 模块上添加样式

刚看到了，谢谢
