### ISSUE TITLE
RangePicker组件的onChange方法Type 'RangeValue<Moment>' is not assignable to type '[Moment, Moment]'

### ISSUE THREAD

**Issue by Leconomy** [ant-design/ant-design#28618]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/immutable-glade-2z2qc?file=/src/App.tsx)

### Steps to reproduce
使用RangePicker组件时配置onChange属性，第一个参数dates报类型兼容错误

### What is expected?
参数兼容正确

### What is actually happening?
Types of parameters 'dates' and 'values' are incompatible.
    Type 'RangeValue<Moment>' is not assignable to type '[Moment, Moment]'.

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.0 |
| System | Mac |
| Browser | chrome |

---
官网上给定的onChange类型是 function(dates: [moment, moment], dateStrings: [string, string])。
dates是[moment, moment]，所以指定类型是正确的，为什么会报兼容性错误。

**Comment by jameslahm** [comment]
因为`dates`有可能是`null`，所以函数类型定义不兼容，把`dates`后面的类型声明删去就好~ https://codesandbox.io/s/fast-cloud-qnpgo?file=/src/App.tsx

**Comment by Leconomy** [comment]
> 因为`dates`有可能是`null`，所以函数类型定义不兼容，把`dates`后面的类型声明删去就好~ https://codesandbox.io/s/fast-cloud-qnpgo?file=/src/App.tsx

根据你说的，我有以下两个观点：
第一：不能这么干，直接删掉类型定义，TS就失去意义了。
第二：dates可能是null，那应该使用联合类型，写成 dates: null | [moment.Moment, moment.Moment] 而不是直接删掉
第三：真实项目中，可能是封装一个方法，作用在不同表单的onChange上，只是传递对参数不同，参考 [https://codesandbox.io/s/boring-heyrovsky-7xytd?file=/src/App.tsx](https://codesandbox.io/s/boring-heyrovsky-7xytd?file=/src/App.tsx)

**Comment by jameslahm** [comment]
其实不加后面的类型声明就可以，`ts`会自动推导`dates`应该为`null | [EventValue<moment.Moment>, EventValue<moment.Moment>]`类型

**Comment by Leconomy** [comment]
> 其实不加后面的类型声明就可以，`ts`会自动推导`dates`应该为`null | [EventValue<moment.Moment>, EventValue<moment.Moment>]`类型

不加后面的类型声明，在不对dates进行处理时是有效的，但是只要对dates做处理，就会报类型不匹配的错误。
参考： https://codesandbox.io/s/boring-heyrovsky-7xytd?file=/src/App.tsx
我在里面以及标注了 【第一处此处不行】和【第二处此处是可以的】。
在业务里肯定使用的是【第一处此处不行】的方式

**Comment by jameslahm** [comment]
第一处不行是因为类型声明不对吧 `EventValue<moment.Moment>`有可能是空

**Comment by lcoder** [comment]
我的问题貌似很好理解：
```txt
Type 'import("projectA/node_modules/moment/moment").Moment | null | undefined' is not assignable to type 'moment.Moment | null | undefined'.
  Property 'isoWeeksInISOWeekYear' is missing in type 'import("projectA/node_modules/moment/moment").Moment' but required in type 'moment.Moment'.ts(2322)
moment.d.ts(549, 5): 'isoWeeksInISOWeekYear' is declared here.
PickerPanel.d.ts(22, 5): The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & TimePickerProps & RefAttributes<any>'
```
就是moment类型不一致导致的。
node_modules/moment/moment.d.ts

node_modules/antd/node_modules/moment/ts3.1-typings/moment.d.ts

共用一个moment应该可以解决

**Comment by Leconomy** [comment]
> 我的问题貌似很好理解：
> 
> ```
> Type 'import("projectA/node_modules/moment/moment").Moment | null | undefined' is not assignable to type 'moment.Moment | null | undefined'.
>   Property 'isoWeeksInISOWeekYear' is missing in type 'import("projectA/node_modules/moment/moment").Moment' but required in type 'moment.Moment'.ts(2322)
> moment.d.ts(549, 5): 'isoWeeksInISOWeekYear' is declared here.
> PickerPanel.d.ts(22, 5): The expected type comes from property 'value' which is declared here on type 'IntrinsicAttributes & TimePickerProps & RefAttributes<any>'
> ```
> 
> 就是moment类型不一致导致的。
> node_modules/moment/moment.d.ts
> 
> node_modules/antd/node_modules/moment/ts3.1-typings/moment.d.ts
> 
> 共用一个moment应该可以解决

一句点醒梦中人啊！
查看里一下业务中用到到moment是2.19.2的版本，antd4里用的是2.25.3的版本。
这两个版本的Moment是有差异的，升级到2.25.3后解决里。
赞！赞！赞！

**Comment by ShadowWalker627** [comment]
import { RangeValue } from 'rc-picker/lib/interface.d';
import moment, { Moment } from 'moment';

const validatePeriodRangeDates = useMemo(() => {
  if (_.every([curRole.startTime, curRole.endTime])) {
    return [moment(curRole.startTime), moment(curRole.endTime)] as RangeValue<Moment>;
  }
  return [moment(), moment()] as RangeValue<Moment>;
}, [curRole.startTime, curRole.endTime]);

<RangePicker
    onChange={onRangePickerChange}
    disabled={rangePickerDisabled}
    disabledDate={disabledDate}
    value={validatePeriodRangeDates}
  />

**Comment by zoffyzhang** [comment]
需要结合上面两层楼才能解决问题

先固定moment版本
```js
"moment": "2.25.3",
```

再引入RangeValue 
```js
import React, { useState } from "react";
import { DatePicker } from 'antd';
import type { Moment } from "moment";
import type { RangeValue } from "rc-picker/lib/interface.d";

export default () => {
  const [dateRange, setDateRange] = useState<RangeValue<Moment>>(null);

  return <DatePicker.RangePicker value={dateRange} onChange={setDateRange} />;
};

```

**Comment by UILKUNP** [comment]
![image](https://user-images.githubusercontent.com/48908684/131510452-be6bf3a6-0037-4cf9-b8d5-5d681be3999b.png)
![image](https://user-images.githubusercontent.com/48908684/131510475-f7ea302b-e956-4814-86bb-642b4cf4ed8a.png)
![image](https://user-images.githubusercontent.com/48908684/131510508-6116b3c1-f08f-4954-a403-9e34dae9b50e.png)
我这样指定类型，然后事情就解决了

**Comment by mixj93** [comment]
前来考古 升级一下moment的版本一致即可

**Comment by AnteeHub** [comment]
> 前来考古 升级一下moment的版本一致即可

保持你的`moment`版本和 `antd` 中依赖的 `moment` 版本一样即可避免这类 TypeScript 报错

你可以使用 `npm list moment` 或者 `yarn list moment` 查看版本：

```shell
yarn list moment 
```

如果你跟我一样用了 `umijs`，那么看到的结果类似于：
![image](https://user-images.githubusercontent.com/55703989/185857634-8d2163cc-f83b-4eee-8fc6-a9b82bcdc4f1.png)



---

Make sure the vesion of `moment` same with the `moment` which  `antd` dependency on,then it is help for this TypeScript Error.

You can use `npm list moment` or `yarn list moment`  to check it:

```shell
yarn list moment 
```


If you use `umijs` also, you will see the result like:
![image](https://user-images.githubusercontent.com/55703989/185857634-8d2163cc-f83b-4eee-8fc6-a9b82bcdc4f1.png)
