### ISSUE TITLE
Modal Children not destory when use ({visible && <Content />})

### ISSUE THREAD

**Issue by cxyxc** [ant-design/ant-design#28612]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gmxw7?file=/index.js:582-612)

### Steps to reproduce
When 4.9.1 I can use (visible && `<ChildrenContent/>`) in Modal, but 4.9.2 is useless. I should use `destoryOnClose`  but too many code to transform.

I think this commit have an impact on this issue. Please help me. Thanks very much.

优化 Modal useModal 性能，避免元素渲染导致组件渲染。[#28122](https://github.com/ant-design/ant-design/pull/28122) @TotooriaHyperion

### What is expected?
I can use (visible && `<ChilerenContent />`) to destory my component.

### What is actually happening?
I can not

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 16.x/17.x |
| System | mac |
| Browser | chrome |

**Comment by singleBuck** [comment]
I have the same problem

**Comment by shaodahong** [comment]
It's cause by https://github.com/react-component/dialog/pull/212, @zombieJ

**Comment by TotooriaHyperion** [comment]
@cxyxc 
#28122 only affects usage of
```
const modal = useModal();
return <button onClick={() => modal.confirm(...)}>Confirm</button>
```
check
https://github.com/react-component/dialog/pull/212
this wraps content into a MemoChildren, and prevent any update when the update is triggered by visible change.

**Comment by shangyilim** [comment]
@cxyxc  you could use the `forceRender` to rerender the child:
```
<Dialog forceRender >
{visible && <ChildrenContent/>}
</Dialog>
```

**Comment by gmoniava** [comment]
@zombieJ I have same problem, https://github.com/react-component/dialog/pull/212, was a **breaking** change,
it broke some my apps where I used to rely that 

`visible && <ChildrenComponent/>
`

would **unmount** `<ChildrenComponent/>`, but now it doesn't anymore. So it broke my apps where I had that assumption.

**Comment by afc163** [comment]
Sorry, you should use `destoryOnClose` in this situation.
