### ISSUE TITLE
Table的columns.width属性不支持calc复合计算

### ISSUE THREAD

**Issue by junjie-lean** [ant-design/ant-design#28610]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/divine-silence-icfdy?file=/src/App.js](https://codesandbox.io/s/divine-silence-icfdy?file=/src/App.js)

### Steps to reproduce
const column   = [
{
width:"calc( ( 100%  - 250px ) / 5 )" // 不生效
}
]

### What is expected?
期望和css设置宽度的表现一致

### What is actually happening?
复合计算不生效，简单计算，比如calc(100% / 5 )可生效

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.x |
| System | macOs 10.15.6 |
| Browser | 87.0.4280.88 |

**Comment by junjie-lean** [comment]
添加codesandbox代码

**Comment by sellardoor** [comment]
`antd Table`扩展于`rc-table`

翻看源码，发现`width`样式最终是挂在`html col`标签上的

直接写了个`html`的表格，发现`calc`表现很诡异

查了相关资料，其实`MDN`也讲了
>Math expressions involving percentages for widths and heights on table columns, table column groups, table rows, table row groups, and table cells in both auto and fixed layout tables may be treated as if auto had been specified.

涉及到百分号的运算，请谨慎处理，可能会给你处理成自动，比如50% + 100px, 50% - 100px, 实际表现为 `auto`，类似的比如栅格布局，我猜测也会有这样的问题。

[MDN calc()](https://developer.mozilla.org/en-US/docs/Web/CSS/calc())

**Comment by junjie-lean** [comment]
@sellardoor  
业务场景中，遇到了动态表格的需求，需要在渲染时来计算`column`的`width`，
查看了`antd Table`最终渲染出来的结果，确实`width`属性是挂载在`html col`标签上，我觉得是`rc-table`采用了落后的封装方式来实现相关功能。 
我查看了[MND](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col)中，对于`col`元素的描述，发现`col`的 `width`属性是即将弃用的属性，所以我猜想这和`calc()`的表现不一致并无太大关系。因为在上面的[demo](https://codesandbox.io/s/divine-silence-icfdy?file=/src/App.js)中，`calc(100% - 200px)`这类异单位换算是可以实现的，但是在`calc(  ( 100% - 200px ) / 2 )`这样的复合运算中的表现确有些异常。

**Comment by sellardoor** [comment]
@junjie-lean 
table上涉及百分号的加减都是无效的，你可以再试试
直接解貌似也没办法，stackoverflow上看了下，貌似没得解
但是避免table上的百分号加减运算就行，比如100%是table的宽，假如table的id是itable，itable.clientWidth是等价于100%的，用itable.clientWidth的值进行复合calc()运算，讲道理是没问题的
