### ISSUE TITLE
在表单中为Select设置初始值

### ISSUE THREAD

**Issue by tangsj** [ant-design/ant-design#2861]
在表单中为Select设置初始值。 通过表单提供的  setFieldsValue  和  getFieldProps 中的initialValue参数设置，比如｛ 1：‘xx’, 2: ‘aa’ ｝， setFieldsValue({id: 1}) ，   希望Select中显示的是 xx 字符串，  实际显示的是  1.  initialValue  表现出来也是这样， 不知道是哪里出了问题！

**Comment by tangsj** [comment]
结果 ， Select只支持string 类型。解决～

**Comment by jormin** [comment]
手动点赞，真真是 `String` 类型的问题~

**Comment by zacksleo** [comment]
这 Bug 真是无力吐槽了
