### ISSUE TITLE
Tree控件在数据变更（添加新数据）后无法check新数据。

### ISSUE THREAD

**Issue by chrisptang** [ant-design/ant-design#2862]
#### 本地环境
antd:1.10.0
Mac OS: 10.11.6
chrome: 52.0.2743.116

#### 你做了什么？

使用了Antd的Tree控件，仿照‘受控操作示例’做了一个动态数据的Tree。
先使用一个Array初始化Tree控件，选中都没有问题；然后改变数据Array：删除一个二级节点的部分叶子节点，同时再在另一个二级节点增加一个叶子节点。

#### 你期待的结果是：

新增的叶子节点能够正常地被选中(checked)；
新增的叶子节点所在的父二级节点选中的时候，它也能被选中。

#### 实际上的结果：

新增的叶子节点无法被选中；
新增的叶子节点所在的二级节点选中时，这个新增的叶子节点没有被选中，而其他叶子节点正常被选中。

#### 可重现的在线演示

http://codepen.io/anon/pen/RRXjKX?editors=001

**Comment by codering** [comment]
貌似copy的例子中就有 `disableCheckbox={item.key === '0-0-0'}` ，你把这个去掉试试？？

**Comment by chrisptang** [comment]
并不是的，我在另外一个项目里面是没有这个语句的，但也遇到了这个问题。
不过最终我改成以下形式就好了：
const checkedKeys = [...this.state.checkedKeys];
    return (
      <div>
        <Button type="primary" onClick={this.handleClick}>Change the data.</Button>
        <div className={"hello"}>
          <Tree
            checkable
            onExpand={this.onExpand} expandedKeys={this.state.expandedKeys}
            autoExpandParent={this.state.autoExpandParent}
            onCheck={this.onCheck} checkedKeys={checkedKeys}
            onSelect={this.onSelect} selectedKeys={this.state.selectedKeys}
          >
            {loop(this.state.gData)}
          </Tree>
        </div>
      </div>
    );

同时在改变数据的地方把checkedKeys和selectedKeys都重置：
this.setState({checkedKeys:[],
      selectedKeys:[],gData:[...]});

**Comment by codering** [comment]
恩，既然是受控的，这2个状态理应由你控制改变才行
