### ISSUE TITLE
Card 组件 cover 添加 video 展示的时候点击 controls 不会出现下载

### ISSUE THREAD

**Issue by linchengzzz** [ant-design/ant-design#28622]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-yonath-2jn42)

### Steps to reproduce
1. 点击 video 的 controls 最右边 的更多应该会展示 浮框 -- 下载 和 画中画 ，但是现在并没有展示
2. 问题已经定位到是 .ant-card-cover 这个类下面 的 transform: translateY(-1px); 导致的
3. 尝试在 index.css 修改为 transform: none !important; 然后问题解决
4. 不太确定这样修改 样式 会不会造成其他的影响，所以没有提PR

### What is expected?
可以弹出浮框 -- 下载 和 画中画 

### What is actually happening?
无法弹出浮框 -- 下载 和 画中画 

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | window10 |
| Browser | Microsoft Edge |

**Comment by xrkffgg** [comment]
这个地方加上的 https://github.com/ant-design/ant-design/pull/26659

可以来个PR
