### ISSUE TITLE
Page Header Breadcrumbs should include the item renderer config

### ISSUE THREAD

**Issue by nicholasgriffintn** [ant-design/ant-design#28638]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By default Breadcrumbs have a hashtag appended to the path provided:

https://ant.design/components/breadcrumb/#Use-with-browserHistory

There doesn't seem to be a way to make this work for something like React Router from the Page Header component, at least not what I can find here:

https://ant.design/components/page-header/

### What does the proposed API look like?
There should be a method of using Breadcrumbs with item renderer.

**Comment by afc163** [comment]
There is no PageHeader component in antd 5.x now.
