### ISSUE TITLE
Table组件当数据源为空时 空字符图像不为空

### ISSUE THREAD

**Issue by WJB3** [ant-design/ant-design#28630]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-frost-jcx95?file=/src/App.js)

### Steps to reproduce
直接展示就错误

### What is expected?
空图片水平居中

### What is actually happening?
空图片向左对齐

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | win10旗舰版 |
| Browser |  87.0.4280.88 |

**Comment by xrkffgg** [comment]
我用官网表头分组的例子测试了下 是正常的。

https://codesandbox.io/s/biaotoufenzu-antd494-forked-u2v0f?file=/index.js

**Comment by xrkffgg** [comment]
你可以尝试下升级 antd 的版本
