### ISSUE TITLE
Table的onChange回调中增加对于filters的描述字段

### ISSUE THREAD

**Issue by Qinmei** [ant-design/ant-design#28639]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table的onChange的参数中，sorter带有field以及columnKey， 而filters的结构为{ [columnKey]:value }, 希望能够统一下，都带上field以及columnKey，这样在后续做组件统一处理的时候也比较方便

### What does the proposed API look like?
[{ field:value, columnKey:value,value:value }]

**Comment by zombieJ** [comment]
We may not apply this since it's a breaking change. Since `columns` is user passed prop, you can get these info with additional code.
