### ISSUE TITLE
Upload component triggers "transformFile" is deprecated

### ISSUE THREAD

**Issue by GerjonM** [ant-design/ant-design#28632]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-frog-2mt69?file=/src/index.js)

### Steps to reproduce
Use an Upload widget without passing the prop "transformFile"

### What is expected?
No warning if you do not pass the prop "transformFile"

### What is actually happening?
A warning is shown

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.0 |
| System | Ubuntu 18.04.2 LTS |
| Browser | Chrome version 70.0.3538.67 |

**Comment by afc163** [comment]
Fixed in #28455
