### ISSUE TITLE
Icon组件如何自定义样式?

### ISSUE THREAD

**Issue by gutenye** [ant-design/ant-design#2863]
除了HOC方法外, 希望能提供这样的快捷方式: `<Icon type="edit" style={{color: "green"}} />`

**Comment by afc163** [comment]
http://codepen.io/anon/pen/AXZbwJ?editors=001

**Comment by gutenye** [comment]
好吧, 我错了, 我是看了ant-design-mobile的Icon代码没有, 然后去看了ant-design的文档也没说, 就以为没有, 发到了这里.... 
我还是发到ant-design-mobile上面去
