### ISSUE TITLE
Scroll to row of virtual table

### ISSUE THREAD

**Issue by dcfranca** [ant-design/ant-design#28647]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm running Ant Design 3.xxx and using the VirtualTable with virtualizedtableforantd setComponents/VTComponents

However, when using it I cannot scroll to a specific row of the table that is not visible on the screen:
```
element.scrollIntoView();
```

A workaround that I'm doing is to make the Table temporarily non-virtual, scroll to the row, and then return it back to a virtual one
However, this approach introduces a few issues, sometimes the Table rendering gets blank while switching from one mode to another and it doesn't occur smoothly 

It would be nice if using the table API we could scroll to an specific element without having to do this workaround even while using a virtual table

### What does the proposed API look like?
tableRef.scrollToRow(row)

**Comment by shaodahong** [comment]
If row height stable, example `50px`, maybe can try `table.scrollTo(50 * 100)`, now problem is find `100`, need remember some index or cache it

**Comment by dcfranca** [comment]
@shaodahong Thanks for the reply, I do have the index, that is fine... I've tried using `table.current.scrollTo()`, being table a reference to a Table component, but it fails as it doesn't find the scrollTo method on it.
Is it available only on Antd4 or am I doing something wrong?


```javascript
    const tableRef = useRef();
   ...
    <Button
        onClick={() => {
          tableRef.current.scrollTo(lastIndex * 100)
        }}
      >
        Jump to End
      </Button>

      <Table
      components={VT}
      ref={tableRef}
      ...
     >
```

**Comment by shaodahong** [comment]
emm, Table not support `ref`, but can you try `document.querySelector('div.ant-table-body').scrollTop = lastIndex * 100`?

**Comment by dcfranca** [comment]
@shaodahong It works! you are my hero :D

**Comment by h1nson** [comment]
> emm, Table not support `ref`, but can you try `document.querySelector('div.ant-table-body').scrollTop = lastIndex * 100`?

you saved my day!

**Comment by ayzzanity** [comment]
> emm, Table not support `ref`, but can you try `document.querySelector('div.ant-table-body').scrollTop = lastIndex * 100`?

i was actually looking for this, thanks!!

**Comment by istvan73** [comment]
Thank you for the idea! For me, I had to say `document.querySelector('.ant-table-tbody-virtual-holder')!.scrollTop = 1 * 100;`. Maybe somedays we will also get this feature out of the box :)
