### ISSUE TITLE
Tabs with Sticky and custom TabBar

### ISSUE THREAD

**Issue by bralemili** [ant-design/ant-design#28646]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-leftpad-zyb1s?file=/src/App.js)

### Steps to reproduce
When too many tabs (more than can fit into screen) are listed, the 'moreIcon' is displayed and the Tabs are inline.
But, when rendering with a custom TabBar (renderTabBar) with Sticky, the Tabs are not inline anymore, and the 'moreIcon' is not displayed

### What is expected?
When rendering TabBars using renderTabBar, the DefaultTabBar given from the function should be the same TabBar you get originally (without customizing)
The wanted result is this [example](https://codesandbox.io/s/tgewv), but working with Sticky

### What is actually happening?
The TabBar lists Tabs in multiple rows without the moreIcon button

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.14 |
| System | Windows 10 x64 |
| Browser | Chrome 87.0.4280.88 |

**Comment by afc163** [comment]
trace #24775

**Comment by bralemili** [comment]
This issue is not fixed, why is it closed?
