### ISSUE TITLE
useForm and Input.Group setFieldsValue value has not changed

### ISSUE THREAD

**Issue by wdaglb** [ant-design/ant-design#28659]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-49bbp?file=/index.js)

### Steps to reproduce
click maker1 button
click maker2 button

### What is expected?
name1 marker success
or there are other solutions?

### What is actually happening?
name1 value has not changed
name2 value change

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | windows10 |
| Browser | chrome 87 |

**Comment by afc163** [comment]
https://codesandbox.io/s/dreamy-sun-cluoj?file=/index.js

**Comment by gRoberts84** [comment]
For clarify, as the solution provided by @afc163  isn't particularly clear.

https://codepen.io/gRoberts84/pen/OJRKzmJ?editors=0010

The <Form.Item> must wrap the form control and not the <Input.Group>.

I had to use two <Form.Items> to place the label correctly but also wrap the select.
