### ISSUE TITLE
Do filter after click Table's filter menu item immediately

### ISSUE THREAD

**Issue by alekye** [ant-design/ant-design#28652]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now, When i use Table component,  if i want to do filter, i should click the filter menu's item, and then click the OK or Reset button.
So, Is there a way to only click the filter menu's item to do filter without close the menu?

目前Table组件的筛选，只有调用confirm和clearFilters后才会触发筛选，但是用户更希望在点击筛选菜单的项目后，可以立即进行筛选，并且不要关闭当前的筛选菜单，confirm和clearFilters都会关闭当前菜单。
目前我们在使用antd做一些医疗信息系统，医生特别需要这样的交互需求，谢谢。

### What does the proposed API look like?
给confirm增加不关闭当前筛选器菜单的参数，或者
在filterDropdown中暴露triggerFilter函数，谢谢！

**Comment by afc163** [comment]
```
    filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters }) => (
```

这个 confirm 就是你需要的吧？

**Comment by alekye** [comment]
> ```
>     filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters }) => (
> ```
> 
> 这个 confirm 就是你需要的吧？

不好意思，是我没有描述清楚，因为confirm会关闭过滤器菜单，
需要在不关闭过滤器菜单的条件下，选择过滤器菜单项后，执行筛选

**Comment by afc163** [comment]
了解了，感觉可加，来个 PR 如何？

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/28688
