### ISSUE TITLE
npm run bulid 报错

### ISSUE THREAD

**Issue by lengkaixin** [ant-design/ant-design#28655]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
clone antd 项目下来
本地运行 npm run build 进行打包，打包报错。

### What is expected?
打包成功

### What is actually happening?
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  uid: 0,
  name: '<anonymous>',
  branch: false,
  error: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
   - configuration[2].entry should be an non-empty object.
     -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
   - configuration[3].entry should be an non-empty object.
     -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
   - configuration[4].entry should be an non-empty object.
     -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
   - configuration[5].entry should be an non-empty object.
     -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | react |
| System | macOS Big Sur11.1 |
| Browser | Chrome 版本 87.0.4280.88 |

**Comment by afc163** [comment]
It works on my machine.

**Comment by lengkaixin** [comment]
> It works on my machine.
Can you check your node version?

**Comment by lengkaixin** [comment]
> It works on my machine.

可以看下您的 node 版本吗？万分感激！

**Comment by xrkffgg** [comment]
PR 和 push 的 CI 都有 build 的校验，如果有错，会直接看出来的。你可以检查下你的环境。

**Comment by afc163** [comment]
```
🌈  ant-design@4.10.0 git:❨fix-notification-style❩ node -v  
v15.3.0
```

**Comment by lengkaixin** [comment]
已解决，分支没有在主分支上报错。感谢大佬们。

**Comment by lengkaixin** [comment]
已解决，分支没有在主分支上报错。感谢大佬们。

**Comment by Gao-pw** [comment]
> 已解决，分支没有在主分支上报错。感谢大佬们。

I encountered the same problem on the 4.x-stable branch. Do I need to switch to the master branch?
