### ISSUE TITLE
TreeSelect onChange事件 如何只获取子节点的value值

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design#28653]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
后台只需要所有子节点的数据就可以，目前是如果全选了父节点，onchange拿到的就是一个父节点的value值
需求是，如何拿到所有子节点的value值，不需要父节点

### What does the proposed API look like?
后台只需要所有子节点的数据就可以，目前是如果全选了父节点，onchange拿到的就是一个父节点的value值
需求是，如何拿到所有子节点的value值，不需要父节点

**Comment by XSmarter** [comment]
https://codesandbox.io/s/4dpve

**Comment by afc163** [comment]
https://codesandbox.io/s/kegouxuan-antd494-forked-zf0jz?file=/index.js

**Comment by sunqicn** [comment]
> https://codesandbox.io/s/kegouxuan-antd494-forked-zf0jz?file=/index.js

请问, 这个问题如何解决呢?
