### ISSUE TITLE
npm run dev 调试模式，为什么启动完之后提示Error: socket hang up  

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2866]
antd版本：1.9.1
"react": "^15.0.2",
"react-dom": "^15.0.2",
暂时不能提供git仓库哦，由于是公司的项目，大神们帮我分析下这是什么情况，虽然不影响功能使用
webpack: bundle build is now finished.
err with request :Error: socket hang up  /sockjs-node/info?t=1472438735349
err with request :Error: socket hang up  /sockjs-node/info?t=1472438745360
err with request :Error: socket hang up  /sockjs-node/info?t=1472438755348

**Comment by afc163** [comment]
和 antd 没关系，请检查网络。

**Comment by wuhaih** [comment]
和网络啥关系，大神？
