### ISSUE TITLE
Drawer当mask为false的时候ant-drawer-content-wrapper的style的width没有，导致定位出现问题

### ISSUE THREAD

**Issue by liuzeyang** [ant-design/ant-design#28663]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jichuchouti-antd494-forked-34hg7)

### Steps to reproduce
打开codesandbox

### What is expected?
mask为false，handler定位能正常

### What is actually happening?
mask为false，handler定位不正常

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16  |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
antd 里的 Drawer 没有 handler 这个属性，请参考 API 文档：https://ant.design/components/drawer-cn/

**Comment by terminalqo** [comment]
![image](https://user-images.githubusercontent.com/20705423/157819253-5bc04628-02b5-4204-a266-90393e94e0f7.png)
