### ISSUE TITLE
升级最新版组件之后，调试模式，出现内存溢出，大神们帮忙看看

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2867]
antd版本：1.9.1
"react": "^15.0.2",
"react-dom": "^15.0.2",

<--- JS stacktrace --->
一、内存溢出
==== JS stack trace =========================================

Security context: 000000AB44EE3AD1 <JS Object>
    1: replace(aka replace) [native string.js:~152] [pc=000003D8046EA5F9] (this
000002D5014B1309 <Very long string[18623]>,P=0000024CA55191B1 <JS RegExp>,Q=000
024CA55191F9 <String[4]\: \n\x09$1>)
    2: 000000BDBA03F9C9 <Symbol: 660511486 <String[14]: Symbol.replace>> [D:\xx
xxxxx\xxxx\node_modules\babel-polyfill\node_modules\core-js\modu

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

2、页面出现错误
Uncaught SyntaxError: Unexpected token <
blockpage.cgi?ws-session=18446744072410955597:1 Uncaught SyntaxError: Unexpected token <

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> 这句话报错

**Comment by benjycui** [comment]
1. 工具问题 cc @pigcan ，antd 本地调试偶尔也会碰到这种情况。
2. 语法问题，自行解决，你用的应该不是 antd-init 出来的模板。

**Comment by afc163** [comment]
我也遇到过 1。

**Comment by pigcan** [comment]
下次发生内存泄漏的时候可以截个完整的图.

**Comment by afc163** [comment]
有进一步的信息可以继续回复，先关了。
