### ISSUE TITLE
[Security] Vulnerability report

### ISSUE THREAD

**Issue by Ry0taK** [ant-design/ant-design#28679]
I'm a security researcher who is working on OSS security.  
I noticed that there is a potential vulnerability in ant-design/ant-design, however, I couldn't find proper contact information to ask permission to test it/report it.  
As [SECURITY.md](https://github.com/ant-design/ant-design/blob/0822ac618f875ee0aaf4e96de6b9bb9f9d2ff2ce/SECURITY.md) is just a copy-pasted template, I don't think there is much contact information.  
Where can I ask permission to test it?

**Comment by zombieJ** [comment]
Hi @Ry0taK ,
You can mail to afc163+ant-design@gmail.com : )

**Comment by Ry0taK** [comment]
Hello @zombieJ 
Okay, I sent an email to that address!
