### ISSUE TITLE
support drawer content wrapper style

### ISSUE THREAD

**Issue by fkocovski** [ant-design/ant-design#28683]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This would allow to add CSS properties to the wrapper itself, like the option to use CSS resize 

![image](https://user-images.githubusercontent.com/9000611/103557025-e353d780-4eb2-11eb-854c-d9877513bcd0.png)

### What does the proposed API look like?
wrapperStyle to be consistent with the other style attributes such as bodyStyle, maskStyle, drawerStyle

**Comment by candy18** [comment]
🤔

**Comment by BooYeu** [comment]
有相同的需求，因为想实现移动端适配width，设置width:auto后希望再价格minWidth:40%,保证电脑端浏览没问题

**Comment by BooYeu** [comment]
@afc163 不知道什么时候能修复这个问题？等了好几个版本~~辛苦了！！

**Comment by kerm1it** [comment]
这个我来加吧

**Comment by BooYeu** [comment]
@kerm1it 好像最新版4.12.3还是不支持？

**Comment by kerm1it** [comment]
这个是新功能，得到2月底的，4.13.0发布，每周周末发的都是bug修复版本
