### ISSUE TITLE
升级ANTD组件，操作form表单，出现很多wanging

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2868]
antd版本：1.9.1
谷歌浏览器提示Warning: It is unnecessary to pass `form` to `Form` after antd@1.7.0.

**Comment by afc163** [comment]
`Warning: It is unnecessary to pass form to Form after antd@1.7.0.`

请阅读提示，去掉 form 属性即可。

阅读 1.70  changelog 。

**Comment by wuhaih** [comment]
谢谢，搞定
