### ISSUE TITLE
严格受控模式下，Form.Item包裹的Radio单选框，rules里的validator接收的参数不对

### ISSUE THREAD

**Issue by DearGaz** [ant-design/ant-design#28696]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sv11z?file=/demo.jsx)

### Steps to reproduce
1、用Form.Item包裹Radio.Group
2、给FormItem添加自定义校验方法validator和无效的valuePropName
3、选择Radio，validator接收到的值是RadioChangeEvent对象
4、点击提交按钮，validator接收到的值是RadioChangeEvent对象

### What is expected?
validator接收到的是Radio.Group实际的值（就像Select表现的那样）

### What is actually happening?
validator接收到的是RadioChangeEvent对象

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.9.43 |
| System | win10 |
| Browser | Google Chrome v87.0.4280.88（正式版本） |

**Comment by DearGaz** [comment]
具体是指哪儿啊，图片被公网墙了...

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#Form.Item 的表格后面一段话。

**Comment by DearGaz** [comment]
表单规模比较大的情况下，复现链接里的使用方式在渲染性能上有点捉急；出于性能考虑，后来还是先改成完全由Form托管的形式了。但是这也能强行算作一个bug吧O(∩_∩)O

**Comment by zombieJ** [comment]
去掉 `valuePropName`
