### ISSUE TITLE
Input 原生的属性的设置

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2869]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：win10
- 浏览器及其版本: chrome

#### 你做了什么？

主页面引入的Modal，Modal含有Input控件

#### 你期待的结果是：

Modal显示之后，同时focus到某一个Input
```
componentDidUpdate() {
   this.refs.codeNo.refs.input.focus()
}
```
```
<Input ref='codeNo'>
```

#### 实际上的结果：

实际上componentDidUpdate，元素仍然不可见，所以参照react的issue的一个解决办法
https://github.com/facebook/react/issues/1791
```    
 setTimeout(function (){
        this.refs.codeNo.refs.input.focus();
}.bind(this), 10);
```
但是这个componentDidUpdate到Modal visible的过程应该是不固定的吧,会出现无法获取焦点的情况吗？
本人项目这个逻辑比较简单不需要其他的判断，想直接通过html5的autoFocus属性,但是好像Input并没有放开一些属性的设置？

**Comment by tindytian** [comment]
需要用 
```
ReactDOM.findDOMNode(this.refs.codeNo).childNodes[0].focus()
```

**Comment by afc163** [comment]
Input 的所有属性都是透传支持的：http://codepen.io/anon/pen/RRXvKr?editors=001

**Comment by afc163** [comment]
另外，Modal 的 visible 是受控的，你应该在 visible 变化的时候调用。

**Comment by dai875939260** [comment]
3q

**Comment by jianfenkezhan** [comment]
我在项目中也用到了，是在Modal 里面，套了个from ，这个form有一个FromItem，里面就是Input了。但是没有用，`this.refs.xx.refs.input.focus()` 这种方式，直接报错，找不到input 的ref属性，该怎么解决？？？

**Comment by baixiaoji** [comment]
试试这样的方式
···
ref={(input) => this.Nameinput = input}
this.Nameinput.focus()
···
