### ISSUE TITLE
Form.List删除字段之后，onValuesChange(changedValues, allValues)中的allValues值还是删除前的值，应该是删除之后剩下的值吧

### ISSUE THREAD

**Issue by kothing** [ant-design/ant-design#28698]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdformlistdemo-efz8t)

### Steps to reproduce
删除时候断点onValuesChange方法，发现allValues还是删除之前的值

### What is expected?
Form.List删除字段之后，onValuesChange(changedValues, allValues)中的allValues应该是删除之后剩下的值吧

### What is actually happening?
Form.List删除字段之后，onValuesChange(changedValues, allValues)中的allValues还是删除前的值

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
你给的例子貌似没问题。

<img width="714" alt="图片" src="https://user-images.githubusercontent.com/507615/103630113-2fb71a00-4f7c-11eb-87d2-5f24e23f4f67.png">
