### ISSUE TITLE
antd如何在vite@2.x中按需引入组件？

### ISSUE THREAD

**Issue by Vibing** [ant-design/ant-design#28697]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Vibing/vite-react](https://github.com/Vibing/vite-react)

### Steps to reproduce
1. git clone https://github.com/Vibing/vite-react.git
2. yarn
3. yarn dev

### What is expected?
antd组件能够在vite环境下按需引入组件

### What is actually happening?
没有按需引入，而是整个antd打包成一个文件，该文件很大

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | macOS 11.1 |
| Browser | Chrome 87 |

**Comment by jameslahm** [comment]
![image](https://user-images.githubusercontent.com/43805318/103649146-efb26000-4f98-11eb-8648-9ead696f0a50.png)
You can try `rollup-plugin-visualizer` or `rollup-plugin-analyzer`. After `yarn build`, it shows that tree-shaking works as expected

**Comment by Vibing** [comment]
@jameslahm Can you give me a demo, or modify it in [vite-react](https://github.com/Vibing/vite-react)

thank you very much

**Comment by jameslahm** [comment]
Hi, add `rollup-plugin-visualizer` in your `vite-react` https://github.com/jameslahm/vite-react.
After `yarn build`, you can open `stats.html` to see the bundle analysis.

**Comment by Vibing** [comment]
@jameslahm nice, tks
