### ISSUE TITLE
<Table />左侧固定时且数据为空时，左侧也会展示文案

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#2870]
如题，见下图：
![1](https://cloud.githubusercontent.com/assets/2840462/18043736/6695da90-6dfc-11e6-8b2c-f7518891f6d1.png)

[查看demo](http://codepen.io/ystarlongzi/pen/oLKQba)

期待结果：应该只有一个展示文案且居中在可视区域内（就像加载提示一样）

**Comment by afc163** [comment]
duplicate https://github.com/ant-design/ant-design/issues/2812
