### ISSUE TITLE
tree有没有类似elementui那种映射，好多人反映这个问题

### ISSUE THREAD

**Issue by bj-white** [ant-design/ant-design#28705]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.请看补充.com](http://www.请看补充.com)

### Steps to reproduce
请看补充说明

### What is expected?
请看补充说明

### What is actually happening?
请看补充说明

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | web |
| Browser | 谷歌 |

---
比如后台返回的格式是[{id: 1, name: '首页', children: []}] 。 treeData就不能满足了，不要说前台转化一下格式，因为这个tree有可能是无限级的，还要递归，多一次递归，效率奇慢无比

**Comment by afc163** [comment]
Duplicate of #24282

**Comment by bj-white** [comment]
什么意思 引过来引过去    到底解决了没有    如果解决了  你说下怎么解决的呀

**Comment by lennokiki** [comment]
> 什么意思 引过来引过去 到底解决了没有 如果解决了 你说下怎么解决的呀

哈哈，就是不给你解决。确实很麻烦，哎，所有组件都有这个问题
