### ISSUE TITLE
modal.method方法里按钮无法去掉空格

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#28708]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xinxitishi-antd4100-forked-52vju?file=/index.js)

### Steps to reproduce
1. 点击按钮
2. 出现弹窗. 弹窗的底部按钮有空格

### What is expected?
弹窗的底部按钮没有空格

### What is actually happening?
无法去掉空格

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.14.0 |
| System | windows 10 |
| Browser | chrome  79.0.3945.88 |

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/103726502-0649cd00-5014-11eb-925d-3a92bf3f5c65.png)

https://ant.design/components/button-cn/#FAQ
