### ISSUE TITLE
<InputNumber value={2} /> is uncontrolled when input using keyboard, is this intended(feature) or a bug?

### ISSUE THREAD

**Issue by xieranmaya** [ant-design/ant-design#28700]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-mestorf-6vvt5?file=/src/App.js)

### Steps to reproduce
Input is not editable, it is correct.
But InputNumber is editable by keyboard(not by click) and revert back when lose focus, it is a controlled component and should not be editable, is this a feature or a bug?

### What is expected?
InputNumber should not editable when it is a controlled component.

### What is actually happening?
InputNumber can be edit.

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.0 |
| System | any |
| Browser | any |

**Comment by jameslahm** [comment]
The reason maybe here: https://github.com/react-component/input-number/blob/9f1c759afd31cdc31809fb21214249dadd07b75b/src/InputNumber.tsx#L256-L265. `rc-input-number` invokes `onChange` using a `proxy onChange`. And when lose focus, `onBlur` will restore original value in `props`. And it‘s not recommended that mixing uncontrolled components with value `prop`.
