### ISSUE TITLE
Type(Upload): RcCustomRequestOptions in Upload component no longer exported

### ISSUE THREAD

**Issue by jarretmoses** [ant-design/ant-design#28713]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Use the `Dragger` component from `Upload` (with Typescript) and pass a custom function to the `customRequest` prop (as in don't pass an inline arrow function). If you want to use `RcCustomRequestOptions` which the prop requires it is no longer being exported. Exact error is `/antd/lib/upload/interface"' declares 'RcCustomRequestOptions' locally, but it is not exported.`

### What is expected?
I'd expect to still have access to the interface needed to satisfy the prop

### What is actually happening?
The interface is no longer exported from antd

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Mac osx 11.0.1 |
| Browser | Chrome 87.0.4280.88 |

---
I don't know if this was intentional or not and I can't find the commit that changed this but I don't believe it should be enforced to use an inline arrow function to satisfy typescript in this scenario. I see the change was that the interface is being pulled from the actual `rc-upload` library instead of being manually defined in antd, but would prefer not to have install that just to have access to this 1 interface

**Comment by ngrok-sarid** [comment]
@jarretmoses Here's a workaround:

```typescript
import { UploadProps } from 'antd/lib/upload/interface';

export type RcCustomRequestOptions<T = any> = Parameters<
  Exclude<UploadProps<T>['customRequest'], undefined>
>[0];
```

The final type is:
```typescript
type RcCustomRequestOptions<T = any> = UploadRequestOption<any>
```
which comes from
```typescript
import { UploadRequestOption as RcCustomRequestOptions } from 'rc-upload/lib/interface';
```
in `node_modules/antd/lib/upload/interface.d.ts`

**Comment by jarretmoses** [comment]
@ngrok-sarid thanks. I'll leave this open for the time being.

**Comment by junpengc** [comment]
RcCustomerRequestOption interface is quiet useful, please continue export it.

**Comment by bawas** [comment]
any updates on this?

**Comment by sagar-gavhane** [comment]
This issue occurred after merging #28389 PR.

**Comment by sayjeyhi** [comment]
for now I solved this with: `import { UploadRequestOption as RcCustomRequestOptions } from 'rc-upload/lib/interface';`

**Comment by zombieJ** [comment]
`RcCustomRequestOptions` is internal type define that we do not want to open to the public. We may not maintain the interface with `RC` prefix since it's all from the `rc-component` that we only rename not to conflict with internal define.

This may not fix since it may leave too many legacy interface define in interface file.

Sorry about that.

**Comment by duskmoon314** [comment]
Could you please export something like this so developers can use when using `Upload` in typescript?

**Comment by ahouck** [comment]
Ditto to what @duskmoon314 said, we use this type definition, we can create the type ourselves but then it would eventually become out of sync with `antd`

**Comment by it-one-mm** [comment]
Any project example available?
Thank you for your help.

**Comment by ahouck** [comment]
@zombieJ Should this issue be closed? It seems like people want this?

**Comment by tulies** [comment]
I also want to

**Comment by behroodrzdr** [comment]
It is not acceptable that we can't use other interfaces except the UploadProps, I think It will be useful for us if we can use internal interfaces and types.

**Comment by nerdess** [comment]
Any news regarding this issue?

**Comment by ShanRonaldson** [comment]
why is this closed? we need a version for typescript prop handling.
