### ISSUE TITLE
treeSelect异步加载树节点，下拉选择框宽度不能自适应

### ISSUE THREAD

**Issue by scyuanhui** [ant-design/ant-design#28717]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/tree-select-cn/](https://ant-design.gitee.io/components/tree-select-cn/)

### Steps to reproduce
一直点击treeSelect子节点

### What is expected?
当数据比较多时，treeSelect下拉选择框宽度能自适应，子节点能展现且可点击加载

### What is actually happening?
点击treeSelect异步加载树节点，当数据比较多时，下拉选择框宽度是固定的，后面的子节点无法显示，不能继续点击加载

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | win10 |
| Browser |  87.0.4280.88 |

---
3.X版本无此问题

**Comment by zombieJ** [comment]
`dropdownMatchSelectWidth={false}`
