### ISSUE TITLE
更新到最新版本以后Menu报错

### ISSUE THREAD

**Issue by shen1986** [ant-design/ant-design#28714]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/shen1986/antd-menu](https://github.com/shen1986/antd-menu)

### Steps to reproduce
更新到最新antd版本

### What is expected?
希望同一个大版本更新。不要影响之前的代码，我们要排查要测试。

### What is actually happening?
更新版本后画面无法打开

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | React 16.4.1 |
| System | win10 |
| Browser | chrome  |

**Comment by shen1986** [comment]
> Hello @shen1986. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @shen1986, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-forked-0y8yc?file=/index.js 是这个吗，第一次用

**Comment by afc163** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-0y8yc?file=/index.js 

之前哪一个版本是好的呢？

**Comment by shen1986** [comment]
> > https://codesandbox.io/s/antd-reproduction-template-forked-0y8yc?file=/index.js
> 
> 之前哪一个版本是好的呢？

我晚上回家看下。我现在本地是最新的。

**Comment by shen1986** [comment]
> > https://codesandbox.io/s/antd-reproduction-template-forked-0y8yc?file=/index.js
> 
> 之前哪一个版本是好的呢？

https://codesandbox.io/s/antd-reproduction-template-forked-9pdqr?file=/index.js 4.1.0这个版本是好的

**Comment by shen1986** [comment]
> > > https://codesandbox.io/s/antd-reproduction-template-forked-0y8yc?file=/index.js
> > 
> > 
> > 之前哪一个版本是好的呢？
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-9pdqr?file=/index.js 4.1.0这个版本是好的

我们是去年开始做的。这个月交给客户。客户把代码拉到本地 npm 安装好就不能用了。

**Comment by xrkffgg** [comment]
试了一下 4.8.3 坏了，可能因为这个 https://github.com/ant-design/ant-design/pull/27663

**Comment by xrkffgg** [comment]
rc-menu 从 8.8.2 升到 8.10.0

**Comment by kerm1it** [comment]
找到原因了，我来修复.

**Comment by afc163** [comment]
> 我们是去年开始做的。这个月交给客户。客户把代码拉到本地 npm 安装好就不能用了。

也建议你们交给客户的版本带上 package-lock.json 或 yarn.lock。

**Comment by kerm1it** [comment]
https://github.com/react-component/menu/pull/360

**Comment by shen1986** [comment]
> > 我们是去年开始做的。这个月交给客户。客户把代码拉到本地 npm 安装好就不能用了。
> 
> 也建议你们交给客户的版本带上 package-lock.json 或 yarn.lock。

好的，谢谢
