### ISSUE TITLE
不同语言环境下的跨年周计数规则不一致

### ISSUE THREAD

**Issue by JanecineJohn** [ant-design/ant-design#28729]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
使用ant design提供的DatePicker控件，设置选择器类型为week。观察各个跨年周的计数规则。

### What is expected?
以2018、2019、2020、2021、2022中间的4个跨度为例，希望中英环境下的跨年周计数规则一致。
如2018-2019的跨年周算作2019年的第一周、2019-2020的跨年周算作2020年的第一周、2020-2021的跨年周算作2021年的第一周、2021-2022的跨年周算作2022年的第一周

### What is actually happening?
英文环境下2018-2019的跨年周算作2019年的第一周、2019-2020的跨年周算作2020年的第一周、2020-2021的跨年周算作2021年的第一周、2021-2022的跨年周算作2022年的第一周
中文环境下2018-2019的跨年周算作2019年的第一周、2019-2020的跨年周算作2020年的第一周、2020-2021的跨年周算作2020年的最后一周、2021-2022的跨年周算作2021年的最后一周

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8.6 |
| System | windows |
| Browser | Chrome |

---
业务上有以周为唯一键保存用户数据的需求。用户使用Chrome浏览器输入并保存数据时，会因浏览器所用语言的不同导致跨年周不一样，使得不同用户在同一周产生的数据存储在两个不同的周里。

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/27879#issuecomment-730283287

**Comment by JanecineJohn** [comment]
ant design的周控件和ISO周日历上面描述的还是有一点区别的：
ISO周日历表示，当1月1日是星期五，当周算去年的第53周
![image](https://user-images.githubusercontent.com/30497765/103971315-2bba1080-51a5-11eb-85d7-357f326ae7fe.png)
而ant design英文环境下，2027年1月1日是星期五，仍然被算为2027年的第一周
![image](https://user-images.githubusercontent.com/30497765/103971472-a1be7780-51a5-11eb-9fe6-5f8195a05e01.png)
中文环境下与ISO周日历的描述相符
![image](https://user-images.githubusercontent.com/30497765/103971520-c4e92700-51a5-11eb-8540-368f252f504d.png)

**Comment by JanecineJohn** [comment]
不同环境下跨年周计算规则不同应该是正常的ant design的日历控件用的是moment.js这个日期处理类库，而
![image](https://user-images.githubusercontent.com/30497765/104154672-74313280-5420-11eb-8419-edf34412d41a.png)

**Comment by JanecineJohn** [comment]
**问题产生：**
不同语言环境下跨年周计算规则不同应该是正常的
ant design的日历控件用了moment.js这个日期处理类库，而moment.js的官方文档表示，周的计算取决于语言环境(https://momentjs.com/docs/)：
![image](https://user-images.githubusercontent.com/30497765/104155292-d8082b00-5421-11eb-922b-70a920de9af8.png)

**解决问题：**
要统一不同浏览器语言环境下用户所看到的datepicker中的周，在项目里使用datepicker控件时设置一下locale即可。设置以后，不管用户的浏览器用哪种语言，在显示日历的时候都会按照设置的locale对应的规则来计算跨年周：
![image](https://user-images.githubusercontent.com/30497765/104155622-90ce6a00-5422-11eb-8365-e3a99fac6fb9.png)
附：[datepicker的官方文档](https://ant.design/components/date-picker/)

**Comment by iambool** [comment]
@xrkffgg ，你好，请问对于这种情况，该如何处理呢：
我们期望的周计数比较细，对于跨年时的**第一周是从1月1日**开始，并不是按“周一”或“周日”作为判断条件的，此时是否有处理方法呢？
![image](https://user-images.githubusercontent.com/30134533/104428825-e12efe80-55bf-11eb-97a6-15d8f4cea12e.png)

**Comment by xrkffgg** [comment]
这个是 ISO 标准的，你的期望其实不符合标准。。。

**Comment by iambool** [comment]
好吧，谢谢，但我还是觉得这样的计算方式更合适，就是细了点-------- 原始邮件 --------发件人： xrkffgg <notifications@github.com>日期： 2021年1月13日周三 傍晚5:30收件人： ant-design/ant-design <ant-design@noreply.github.com>抄送： iambool <iambool@163.com>, Comment <comment@noreply.github.com>主    题： Re: [ant-design/ant-design] 不同语言环境下的跨年周计数规则不一致 (#28729)

这个是 ISO 标准的，你的期望其实不符合标准。。。

**Comment by xrkffgg** [comment]
@iambool datepicker 底层引用 rc-picker 使用的 monent.js 、dayjs 之类的 时间工具，其实是需要这些工具支持才行。目测是不可能的。

还有一种办法，就是自己重新封装 rc-picker 。

**Comment by 1Lin1** [comment]
在en-us环境下，怎么让date-picker符合iso标准 显示53周呢

**Comment by yoyo837** [comment]
浏览器语言相关
