### ISSUE TITLE
多层抽屉关闭以后，页面无法滚动

### ISSUE THREAD

**Issue by without-yy** [ant-design/ant-design#28726]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duocengchouti-antd4100-forked-um2nf)

### Steps to reproduce
打开多层抽屉，然后关闭，官网多层抽屉demo即可复现

### What is expected?
页面可以正常滚动

### What is actually happening?
页面无法滚动

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.14 |
| System | MacOS 11.1 |
| Browser | Chrome  87.0.4280.88（正式版本） (x86_64) |

**Comment by yoyo837** [comment]
#28687

**Comment by afc163** [comment]
Fixed in #28687
