### ISSUE TITLE
mac的chrome下使用网页引用的第二个上传控件打开很慢

### ISSUE THREAD

**Issue by yuan1995913** [ant-design/ant-design#2872]
本地环境：mac 

- antd 版本: 1.8
- 操作系统及其版本： os x
- 浏览器及其版本: chrome

#### 你做了什么？

引入 antd 的Upload组件

期待的结果是：

像官网一样正常显示

#### 实际上的结果：
一张网页两个地方使用了Upload组件 第一个正常，第二个点击上传按钮出现选择文件对话框要等5-10秒。
之前1.4正常 升级为1.8后出现此情况
mac下测试safari和firefox正常，windows下chrome和w10自带的浏览器均正常，只有mac下的chrome下不正常

可重现的在线演示：与官网demo的代码一致

**Comment by benjycui** [comment]
官网正常 http://ant.design/components/upload/#components-upload-demo-drag

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2798
