### ISSUE TITLE
图标在window系统下有锯齿

### ISSUE THREAD

**Issue by PnaQnai** [ant-design/ant-design#28720]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What is expected?
之前是没有锯齿的,不知道为什么会存在锯齿,参考了使用react-antd其他平台的也存在此问题

### What is actually happening?
所有的图标存在锯齿,引用https://www.iconfont.cn/上面的图标,也存在锯齿,很影响美观,不想一个图标就使用图片,希望尽快解决.

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | 15.4.0 |
| System | window |
| Browser | 谷歌/360 |

---
建议提交issue可以提交图片,对于一些链接打不开的怎么描述问题呢

**Comment by PnaQnai** [comment]
![image](https://user-images.githubusercontent.com/45838177/103743495-38b8f180-5037-11eb-9cbe-21429e115035.png)

**Comment by PnaQnai** [comment]
![Uploading image.png…]()

**Comment by PnaQnai** [comment]
![image](https://user-images.githubusercontent.com/45838177/103743675-89304f00-5037-11eb-9808-ba6ed48d6de1.png)

**Comment by yoyo837** [comment]
换个电脑看看？没遇到过
