### ISSUE TITLE
Transfer comp's initialTargetKeys cant catch by Form

### ISSUE THREAD

**Issue by qunzi0214** [ant-design/ant-design#28725]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hy57f?file=/index.js)

### Steps to reproduce
1. Without any ` Transfer Comp ` operate, click the submit button

> The ` onFinish event` only catch value ` undefined ` of ` transferData ` field even if the ` initialTargetKeys ` is given

2. Do some ` Transfer Comp ` operate(add or remove) and click the submit button

> The ` onFinish event` now can catch the correct value` string[] ` of ` transferData ` field

### What is expected?
Transfer comp's initialTargetKeys can catch by Form

### What is actually happening?
Transfer comp's initialTargetKeys cant catch by Form

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | macOS 10.15.3 |
| Browser | Chrome 87.0.4280.88 |

**Comment by afc163** [comment]
Check `valuePropName` in Form API

**Comment by qunzi0214** [comment]
> Check `valuePropName` in Form API

thx. Its my mistake.
