### ISSUE TITLE
Wrap Input (type="password") in AutoComplete should act like a password input

### ISSUE THREAD

**Issue by zxdong262** [ant-design/ant-design#28721]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customize-input-component-antd4100-forked-p6wt1)

### Steps to reproduce
Just wrap Input type='password' in AutoComplete
```js
    <AutoComplete
      options={options}
      style={{
        width: 200,
      }}
      onSelect={onSelect}
      onSearch={handleSearch}
    >
      <Input
        placeholder="input here"
        className="custom"
        style={{
          height: 50,
        }}
        type="password"
        onKeyPress={handleKeyPress}
      />
    </AutoComplete>
```
### What is expected?
When wrap password input, should act like password input instead of text input

### What is actually happening?
When wrap password input,  act like text input

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Mac OS 10.5.6 |
| Browser | Electron 9.4(Chrome 85) |

**Comment by OmriGM** [comment]
Should use it like this:
```
.
.
return (
    <AutoComplete
      options={options}
      style={{
        width: 200
      }}
      onSelect={onSelect}
      onSearch={handleSearch}
    >
      <Input.Password
        placeholder="input here"
        className="custom"
        style={{
          height: 50
        }}
        onKeyPress={handleKeyPress}
      />
    </AutoComplete>
  );
```
https://ant.design/components/input/#Input.Password

**Comment by zxdong262** [comment]
Got thank you @OmriGM
