### ISSUE TITLE
yarn start 启动超级慢

### ISSUE THREAD

**Issue by mengfei0053** [ant-design/ant-design#28722]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能不能改进下，这启动一次，我这里得有5分钟以上了。

### What does the proposed API look like?
能不能提取个dll包，不用每次启动时，都build一次啊

**Comment by mengfei0053** [comment]
补充一下，主要是bisheng start -c ./site/bisheng.config.js慢

**Comment by afc163** [comment]
欢迎帮忙提升速度。

**Comment by mengfei0053** [comment]
目前关于启动速度提高的方法，不知道你们是如何考虑的，我的一些想法在这个 issues里https://github.com/benjycui/bisheng/issues/232

**Comment by afc163** [comment]
到 https://github.com/benjycui/bisheng/issues/232 里跟踪讨论，欢迎各位 PR。
