### ISSUE TITLE
Tabs prop to make the tab content full height 

### ISSUE THREAD

**Issue by NZepeda** [ant-design/ant-design#28735]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes, you want the content of the tabs to take up the full height of the screen instead of being the height of the content.

See  this [pen](https://codepen.io/NZepeda/pen/gOwKMNb) 

The content in red should be expandable to full height. 

### What does the proposed API look like?
Perhaps a prop like `tabContentHeight: "full | "content"` with "content" being the default?

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/NWRzvXv

**Comment by AStaroverov** [comment]
@afc163 it's incorrect example, you make tab content with absolute height. But for content not exist way make hime with relative height by parent. For example Card has prop bodyStyle for resolve this issue
