### ISSUE TITLE
Input: maxLength  can't constraint the value set by script

### ISSUE THREAD

**Issue by HomyeeKing** [ant-design/ant-design#28733]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/input-maxlength-msh6i)

### Steps to reproduce
- refresh the frame
- wait 1s 

### What is expected?
value.length can not greater than maxlength

### What is actually happening?
the Input is set over the maxLength value by default,  textarea has been constrainted by hand
the origin element also has the same problem, but it's designed 
we must constraint it by hand since the maxLength only detect the user input(opposed to the way set by script )

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.3.1 |
| System | mac |
| Browser | chrome |

**Comment by HomyeeKing** [comment]
[the related issue can be found here](https://github.com/whatwg/html/issues/6264)

**Comment by afc163** [comment]
I think we should follow same behavior as the native element.

**Comment by HomyeeKing** [comment]
@afc163  I don't think so, 
> that is as designed and not something that can be changed as it would break existing web content.

but as a UI frame, we need to prevent this which can violate the constraint

also the `Input.Textarea` has done it before while the origin `textarea` have the same problem

you can see it from the repo above

**Comment by HomyeeKing** [comment]
@afc163  @zombieJ  
also there's a question:
[look at **emoji**  part ](https://codesandbox.io/s/input-maxlength-msh6i?file=/app.jsx)

when we set a emoji value, it shows count is 1 with maxlength is 2, but we can't input anything

so is that expected?

**Comment by zombieJ** [comment]
Since we already handle the [special case](https://github.com/ant-design/ant-design/blob/6bcb9ba7c4561b5b1b2c1c874961475f9e141166/components/input/TextArea.tsx#L114), I think we may handle this all?

cc @afc163

**Comment by HomyeeKing** [comment]
FYI , it act same with the origin element
 so I think the problem is how we display the `showCount`
should  we regard the emoji as **length  2**  while the current solution takes it as **length 1**?

**Comment by zombieJ** [comment]
We find another case. When InputNumber provides `min` but `value` out of range. It shows the `min` value but when submit the form, server get wrong number. We may keep `value` even it exceed the range.

Input should show as what `value` provides.
