### ISSUE TITLE
@import antd.less文件后，menu导航鼠标移入不会弹出

### ISSUE THREAD

**Issue by bj-white** [ant-design/ant-design#28738]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.重现步骤.com](http://www.重现步骤.com)

### 我的效果，没有弹出框
![image](https://user-images.githubusercontent.com/26987622/103841706-27bbbf00-50cf-11eb-95ef-f8a2080098af.png)
### 官方效果
![image](https://user-images.githubusercontent.com/26987622/103841742-428e3380-50cf-11eb-81b0-948b6345ef65.png)

### What is expected?
重现步骤

### What is actually happening?
重现步骤

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | web |
| Browser | 谷歌 |

**Comment by bj-white** [comment]
@afc163   
https://github.com/bj-white/react-admin-web/tree/v0.0.1

**Comment by bj-white** [comment]
@ant-design-bot 
https://github.com/bj-white/react-admin-web/tree/v0.0.1

**Comment by wang3620** [comment]
+1 encountered the same problem here

**Comment by wang3620** [comment]
I raised the same issue https://github.com/ant-design/ant-design/issues/28820#issue-783811617

**Comment by afc163** [comment]
<img width="599" alt="图片" src="https://user-images.githubusercontent.com/507615/104432113-a29b4300-55c3-11eb-8dd8-5dca013d15ce.png">

你的例子找不到 menu item。

**Comment by afc163** [comment]
升级 less 到 3.x 或者 4.x 即可。

我这里也兼容一下 less 2.x 。
