### ISSUE TITLE
Table的sticky在官方文demo中不生效

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#28737]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-sticky](https://ant.design/components/table-cn/#components-table-demo-sticky)

### Steps to reproduce
官方的demo中无效https://ant.design/components/table-cn/#components-table-demo-sticky
sandbox中的链接是正常的：https://codesandbox.io/s/puhej?file=/index.js:1410-1416

### What is expected?
官方的demo跟codesandbox中效果一致

### What is actually happening?
官方的demo中无效

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | ^17.0.1 |
| System | windows 10 |
| Browser |  80.0.3987.132（正式版本） （64 位） |

---
可能是dumi的bug

**Comment by shaodahong** [comment]
@afc163 https://github.com/ant-design/ant-design/pull/27715/commits/3031a7e6b20f912bfabcbf8e2db592e0164e212a

加了个 overflow 的原因，这个是必须的么

**Comment by afc163** [comment]
为了解决 https://github.com/ant-design/ant-design/issues/27623，按葫芦起了瓢...
