### ISSUE TITLE
Box Shadows

### ISSUE THREAD

**Issue by anubra266** [ant-design/ant-design#28746]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We should be able to get deeper box-shadows for cards in our applications

### What does the proposed API look like?
```
import { Card } from 'antd';

ReactDOM.render(
  <Card style={{ width: 300 }} shadow={3}>
    <p>Card content</p>
    <p>Card content</p>
    <p>Card content</p>
  </Card>,
  mountNode,
);
```

**Comment by afc163** [comment]
```
  <Card style={{ width: 300, boxShadow: 'xxx' }}>
    <p>Card content</p>
    <p>Card content</p>
    <p>Card content</p>
  </Card>
```
