### ISSUE TITLE
请问一下最新版4.10.0里Upload的interface改动是否正确

### ISSUE THREAD

**Issue by CaanDoll** [ant-design/ant-design#28744]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://nourl.com](https://nourl.com)

### Steps to reproduce
upload的customRequest方法第一个参数option的type使用

### What is expected?
正确的typescript提示

### What is actually happening?
type改动较大，无法明白

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome87 |

**Comment by CaanDoll** [comment]
![image](https://user-images.githubusercontent.com/23540471/103858244-f654ea80-50f2-11eb-8348-0a8511daf2da.png)
这里是改动地方

**Comment by CaanDoll** [comment]
![image](https://user-images.githubusercontent.com/23540471/103858313-0d93d800-50f3-11eb-9842-3b847a7932c3.png)
这个是rc-upload的UploadRequestOption的类型，两者对比有一些差异，甚至这里还要传个xhr对象

**Comment by CaanDoll** [comment]
[改动commit的url](https://github.com/ant-design/ant-design/commit/55e0d13234bbb750b5b978b19bea316831a5d69e#diff-15f89439652a2abdff4246641259805043f69e3312189bc6fd87a1a9cb3851fc)

**Comment by afc163** [comment]
看上去 #28680 也是类似的问题。

**Comment by zombieJ** [comment]
看了一下，是 rc 里定义问题。我修一下。

ref: https://github.com/react-component/upload/pull/268

**Comment by zombieJ** [comment]
确认了一下，`rc-upload` 定义是正确的。是 antd 的定义问题：



<img width="380" alt="截屏2021-01-11 下午5 56 00" src="https://user-images.githubusercontent.com/5378891/104166793-4656e880-5436-11eb-8999-f258475d260a.png">

ref: https://codesandbox.io/s/dianjishangchuan-antd4102-forked-yvxen?file=/index.js

**Comment by CaanDoll** [comment]
请问大佬们这个修复了吗，好像几个版本都没有发这个

**Comment by farzer** [comment]
同求啊

**Comment by CaanDoll** [comment]
@zombieJ 大佬麻烦看一下~

**Comment by zombieJ** [comment]
> 确认了一下，`rc-upload` 定义是正确的。是 antd 的定义问题：
> 
> <img alt="截屏2021-01-11 下午5 56 00" width="380" src="https://user-images.githubusercontent.com/5378891/104166793-4656e880-5436-11eb-8999-f258475d260a.png">
> 
> ref: https://codesandbox.io/s/dianjishangchuan-antd4102-forked-yvxen?file=/index.js

见上

**Comment by lulidd01** [comment]
既然都已经是customRequest，为什么onSuccess 还必需要传 XHR。

**Comment by genshen** [comment]
Any new progress here? How can I use the new customRequest api (examples)?

**Comment by leohxj** [comment]
rc-upload 官方的示例:

https://upload-react-component.vercel.app/demo/custom-request

```js
customRequest({
    action,
    data,
    file,
    filename,
    headers,
    onError,
    onProgress,
    onSuccess,
    withCredentials,
  }) {
    // EXAMPLE: post form-data with 'axios'
    // eslint-disable-next-line no-undef
    const formData = new FormData();
    if (data) {
      Object.keys(data).forEach(key => {
        formData.append(key, data[key]);
      });
    }
    formData.append(filename, file);

    axios
      .post(action, formData, {
        withCredentials,
        headers,
        onUploadProgress: ({ total, loaded }) => {
          onProgress({ percent: Math.round((loaded / total) * 100).toFixed(2) }, file);
        },
      })
      .then(({ data: response }) => {
        onSuccess(response, file);
      })
      .catch(onError);

    return {
      abort() {
        console.log('upload progress is aborted.');
      },
    };
  },
```

接口类型: https://github.com/react-component/upload/blob/master/src/interface.tsx#L56


看下 onSuccess 的使用, 和接口定义对应不上啊

@zombieJ 你的这个示例,打开报错了.
codesandbox.io/s/dianjishangchuan-antd4102-forked-yvxen?file=/index.js

**Comment by mleister97** [comment]
Why is this issue closed? Problem still exists.

**Comment by yzw7489757** [comment]
放弃了 Upload 组件

**Comment by HuifangYeo** [comment]
```
    axios
      .post(action, formData, {
        withCredentials,
        headers,
        onUploadProgress: ({ total, loaded }) => {
          onProgress?.({ percent: Math.round((loaded / total) * 100).toFixed(2) }, file);
        },
      })
      .then(({ data: response }) => {
        onSuccess?.(response, response.request);
      })
      .catch(onError);
```

For the second parameter, I passed in `response.request`
