### ISSUE TITLE
官网 Drawer 示例 多层抽屉，点开第二层导致浏览器滚动条消失

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#28745]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/#components-drawer-demo-multi-level-drawer](https://ant.design/components/drawer-cn/#components-drawer-demo-multi-level-drawer)

### Steps to reproduce
进入链接 
点击多层抽屉 示例 中的 Open drawer
继续点击 Two-level drawer 

### What is expected?
页面整体滚动条保持不变

### What is actually happening?
页面整体滚动条消失

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome  87.0.4280.141 |

**Comment by yoyo837** [comment]
#28687

**Comment by jumpingFinger** [comment]
解决了吗，这bug线上已经10天了~~~，昨天看还没发正式包

**Comment by afc163** [comment]
Fixed in #28687
