### ISSUE TITLE
Tree组件的展开收起是否可以实现类似于折叠面板的手风琴效果(单个展开)

### ISSUE THREAD

**Issue by BovineBoy** [ant-design/ant-design#28747]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实现类似于折叠面板的手风琴效果 (单个展开)

### What does the proposed API look like?
onlyExpandOneLeaf={boolean}

**Comment by afc163** [comment]
控制 expandKeys 长度最多不超过 1 即可。
