### ISSUE TITLE
TreeSelect 受控且没有初始值的情况下，点击任意节点但没有改变传入value，节点内容还是会被回填到输入框中

### ISSUE THREAD

**Issue by 2018mjy** [ant-design/ant-design#28752]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4100-forked-mwjh4?file=/index.js)

### Steps to reproduce
1.清空输入框
2.点击任意节点

### What is expected?
输入框内不出现任何内容

### What is actually happening?
输入框中出现被点击节点内容

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 16.12.0 |
| System | mac  |
| Browser | 87.0.4280.67 |

**Comment by zombieJ** [comment]
React 规范里 `undefined` 就是非受控，要空值用 `null`。

ref: https://codesandbox.io/s/jiben-antd4100-forked-sz4zo
