### ISSUE TITLE
InputNumber组件在失焦的情况下会触发onChange, 如果此时输入的值为空, 则onChange的value会传递一个null, 但并未在onChange的类型中标注有null类型

### ISSUE THREAD

**Issue by lengfangbing** [ant-design/ant-design#28759]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/s8e5j?file=/index.js)

### Steps to reproduce
将InputNumber的输入框清空, 然后失焦, 会看到控制台打出的onChange的value是null

### What is expected?
为空字符串或者undefined比较好

### What is actually happening?
null

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.13.1 |
| System | MacOS Catalina 10.15.5 |
| Browser | Google Chrome 版本 87.0.4280.88（正式版本） (x86_64) |

---
我在非undefined状态下调用了toString(), 因为错误返回了null, 导致页面报错

**Comment by afc163** [comment]
可以来个 PR 修复一下 TS 定义。

**Comment by lengfangbing** [comment]
> 可以来个 PR 修复一下 TS 定义。

行, 我今天找时间搞一下

**Comment by Dolov** [comment]
大佬 antd 有官方的开发交流群么 @afc
