### ISSUE TITLE
Multi-level drawer bug

### ISSUE THREAD

**Issue by RaijinBai** [ant-design/ant-design#28750]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer/#components-drawer-demo-multi-level-drawer](https://ant.design/components/drawer/#components-drawer-demo-multi-level-drawer)

### Steps to reproduce
Open two-level-drawer then close all drawer,then the scroll bar will miss and we can't scroll the page any more

### What is expected?
we can use the scroll bar .

### What is actually happening?
we can't

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.04 |
| System | win10 |
| Browser | google chrome 87.0.4288 |

**Comment by yoyo837** [comment]
Fixed in #28687 #28749
