### ISSUE TITLE
Different Styles getting applied for Dropdown menu when overlay menu is getting rendered from separate component

### ISSUE THREAD

**Issue by dhruv-shipmnts** [ant-design/ant-design#28753]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/dhruvsaraiya-the-typescripter/pen/ExgREVW?editors=0010](https://codepen.io/dhruvsaraiya-the-typescripter/pen/ExgREVW?editors=0010)

### Steps to reproduce
Instead of putting \<Menu\> as overlay, put some other component like \<Some\>, which at the end returns Menu only.

### What is expected?
Same Styles in direct menu vs menu returned from other component.

### What is actually happening?
Different styles gettting applied.

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/KKgBPEj?editors=0010
