### ISSUE TITLE
TS: Input, Input.Search, DatePicker and RangePicker components cannot use ref

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#28765]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-nightingale-3x96q?file=/App.tsx:0-380)

### Steps to reproduce

```ts
import * as React from "react";
import { ComponentProps } from "react";
import Input from "antd/lib/input";

type Props = ComponentProps<typeof Input>;

const TextField = React.forwardRef<HTMLInputElement, Props>(({ children, ...props }, ref) => (
    <Input ref={ref} {...props}>
      {children}
    </Input>
));

export {TextField};
```

### What is expected?
No errors

### What is actually happening?

<img width="796" alt="Снимок экрана 2021-01-07 в 20 32 56" src="https://user-images.githubusercontent.com/803674/103925111-1a7eee80-5128-11eb-8c02-502f84d61047.png">

```
TS2322: Type 'ForwardedRef<HTMLElement>' is not assignable to type 'string | ((instance: Input | null) => void) | RefObject<Input> | null | undefined'.
```

### Components

**Input**, **Input.Search**, **DatePicker**, **RangePicker** 

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | macOS |
| Browser | Safari |

**Comment by jameslahm** [comment]
Hi, just change `HTMLInputElement` to `Input` https://codesandbox.io/s/elegant-cori-e9t05?file=/App.tsx

**Comment by monolithed** [comment]
@jameslahm, thanks for you answer, but how to create a wrapper around the Input component?

```ts
import * as React from "react";
import {ComponentProps} from "react";
import Input from "antd/lib/input";

type Props = ComponentProps<typeof Input>;

const TextField = React.forwardRef<Input, Props>(({ children, ...props }, ref) => (
    <Input ref={ref} {...props}>
      {children}
    </Input>
));

const inputRef = React.useRef<typeof AntTextField>(null);

const foo = <TextField ref={inputRef} />;
                        ^
TS2322: Type 'RefObject<ForwardRefExoticComponent<InputProps & RefAttributes<Input>>>' is not assignable to type '((instance: Input | null) => void) | RefObject<Input> | null | undefined'.   Type 'RefObject<ForwardRefExoticComponent<InputProps & RefAttributes<Input>>>' is not assignable to type 'RefObject<Input>'.     Type 'ForwardRefExoticComponent<InputProps & RefAttributes<Input>>' is missing the following properties from type 'Input': input, clearableInput, removePasswordTimeout, direction, and 26 more.
```

**Comment by acomito** [comment]
@monolithed Did you get this? I'm having the same issue trying to register inputs with react-hook-form without using their controller wrapper.

**Comment by bodokaiser** [comment]
@acomito for me changing `Input` to `InputRef`, i.e.,

```typescript
import { useRef } from 'react'
import { InputRef } from 'antd'

useRef<InputRef>(null)
```

worked (`antd@4.19.*`).
