### ISSUE TITLE
TS中使用RangePicker时Moment类型兼容

### ISSUE THREAD

**Issue by fguizc** [ant-design/ant-design#28763]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
```
import ... from 'antd'
import * as moment from 'moment' // package.json 无显示安装moment

interface State {
  rangeDateValue: moment.Moment[]
}

export default class Demo extends React.Component<any, State> {

state = {
  rangeDateValue: []
} as State

<RangePicker
    ranges={{
      本周: [moment().startOf('weeks'), moment()],
      最近七天: [moment().subtract(6, 'days'), moment()],
      本月: [moment().startOf('month'), moment()]
     }}
    onChange={this.onChange}
    disabledDate={this.disabledDate}
    value={this.state.rangeDateValue}
 />

}
```

### What is expected?
使用同一个moment声明文件

### What is actually happening?
onChange事件Error：

不能将类型“(dates: moment.Moment[], dateString: [string, string]) => void”分配给类型“(values: RangeValue<Moment>, formatString: [string, string]) => void”。

---

ranges={...}

(method) Moment.startOf(unitOfTime: moment.unitOfTime.StartOf): moment.Moment
类型 "import("/Users/weiczeng/code/forchange/future-railway/node_modules/moment/moment").Moment" 中缺少属性 "isoWeeksInISOWeekYear"，但类型 "moment.Moment" 中需要该属性。ts(2741)
moment.d.ts(565, 5): 在此处声明了 "isoWeeksInISOWeekYear"。

原因：moment自带了d.ts，而antd的moment声明文件指向了 node_modules/antd/node_modules/moment/ts3.1-typings/moment.d.ts 导致类型不兼容

---

value: [moment.Moment, moment.Moment]

不能将类型“[Moment, Moment]”分配给类型“[EventValue<Moment>, EventValue<Moment>]”。
  不能将类型“Moment”分配给类型“EventValue<Moment>”。

且 EventValue 是从 `rc-picker/lib/interface.d.ts` 中提供，开发者不应该这样越过层级去使用底包提供的类型

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Mac 10.14.6  |
| Browser | Chrome 87.0.4280.88 (正式版本) (x86_64) |

**Comment by kerm1it** [comment]
可以用这个模版写个复现的例子看看么？
https://codesandbox.io/s/antd-reproduction-template-ts-tips3

这样不太好理解。

**Comment by afc163** [comment]
Duplicate of #28618
