### ISSUE TITLE
When remove the Tag component, the next one will be automatically set to hide 

### ISSUE THREAD

**Issue by qunzi0214** [ant-design/ant-design#28768]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rrmcl?file=/index.js)

### Steps to reproduce
1. just click and remove the first tag or second tag. the next tag disappeared because its html element got classname `ant-tag-hidden`
2. see the comment of line 23. if the attribute `visible` is set explicit, this problem will not reproduce

### What is expected?
When remove the Tag component, the next one will not be automatically set to hide 

### What is actually happening?
When remove the Tag component, the next one will be automatically set to hide 

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | macOS 10.15.3 |
| Browser | Chrome 87.0.4280.88 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-d84t6?file=/index.js

**Comment by qunzi0214** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-d84t6?file=/index.js

it works. but i got confused here. why the `e.preventDefault` is necessary?

**Comment by DebbiesSun** [comment]
You need to set a 'key' for each Tag，just like a key in Table columns.
