### ISSUE TITLE
Table使用了sticky并设置了offsetHeader的情况，loading的时候表格会往下掉，loading完成后又上去了

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#28762]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-rhodes-ip4sj)

### Steps to reproduce
1.设置了Table的 sticky中offsetHeader的值
2.让 Table的loading状态为true

### What is expected?
表格不会往下掉

### What is actually happening?
表格往下掉了，loading结束后又回去了，会产生表格抖动感

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | Chrome |

---
附上了codesandbox例子，点 "刷新数据" 按钮 可以看到结果
第一次进来效果：
![image](https://user-images.githubusercontent.com/7939085/103895149-e78a2a00-512a-11eb-8d31-f05f740ec9a8.png)
点"刷新数据"按钮loading状态的效果
![image](https://user-images.githubusercontent.com/7939085/103895253-11dbe780-512b-11eb-8a00-f4b72da01376.png)

**Comment by xiexingen** [comment]
![image](https://user-images.githubusercontent.com/7939085/103895935-25d41900-512c-11eb-80e2-f1d67862912c.png)
我pa排查发现的情况是这样，表格loading的时候， .ant-spin-blur 样式上有一个overflow:hidden  这个会影响.ant-table-sticky-header这个样式的节点，由于这个节点上有内敛的top,所以变成了头部往下了

**Comment by shaodahong** [comment]
暂时没有什么好的解决方案，不过临时方案可以使用 `offsetHeader: loading? 16: 48` 修复下

**Comment by xiexingen** [comment]
是的咯，这个bug先放着；看后期有没啥好点的方案；我暂时没用到 只是测试发现这个情况提了个bug

**Comment by shaodahong** [comment]
原生 `sticky` 的限制，看后期有没有好的方案可以替换，这个暂时先关了
