### ISSUE TITLE
The TreeSelect dropdown tree node displays text newlines when the content is too long

### ISSUE THREAD

**Issue by scyuanhui** [ant-design/ant-design#28772]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yibujiazai-antd4100-forked-owbo7?file=/index.js)

### Steps to reproduce
Click on the child node to load data asynchronously

### What is expected?
The TreeSelect dropdown tree node dose not display a  newlines when the content is too long

### What is actually happening?
The TreeSelect dropdown tree node displays text newlines when the content is too long

| Environment | Info |
|---|---|
| antd | 4.9.1 |
| React | 17.0.1 |
| System | win10 |
| Browser |  谷歌：87.0.4280.88 |

**Comment by afc163** [comment]
Duplicate of #23267
