### ISSUE TITLE
升级antd组件，rowcol布局有些改动，导致原有布局比较乱了

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2877]
antd版本：1.9.1
代码：
< row >
< Col span="12">
         < FormItem label="配置项名称">
              < Input maxLength={80} {...getFieldProps("name")}
         < /FormItem>
     < /Col >
     < Col span="12" >
            <  FormItem label="配置项代码">
                  < Input maxLength={50} {...getFieldProps('kind')}/>
             < /FormItem>
  <  /Col >
< /row >
升级之前：
页面渲染后结果
class="col-12"

升级之后：
页面渲染结果
class="ant-col-12"

升级之后结果：
2个input输入框紧挨在一起，2个col中间的空隙没了，请问大神，我该怎么弄全局覆盖？

**Comment by benjycui** [comment]
你样式是怎么引入的。

**Comment by afc163** [comment]
直接样式覆盖。
