### ISSUE TITLE
Image 增加一个 图片数组属性 方便多张图片预览

### ISSUE THREAD

**Issue by yunuo-tech** [ant-design/ant-design#28779]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如一组图片，在列表中显示一张封面，预览封面的时候可以点翻页预览这组图片中的其他图片。

### What does the proposed API look like?
新增 urlList属性

**Comment by shaodahong** [comment]
Try `Image.PreviewGroup`

https://ant.design/components/image/#components-image-demo-previewGroup

**Comment by yunuo-tech** [comment]
> Try `Image.PreviewGroup`
> 
> https://ant.design/components/image/#components-image-demo-previewGroup

这个会在列表把所有图片都显示出来，而我只是想显示一张封面，点开后才进行分页

**Comment by alvin0216** [comment]
+1
