### ISSUE TITLE
输入框、下拉框、Radio、CheckBox等数据录入类组件支持只读属性

### ISSUE THREAD

**Issue by DearGaz** [ant-design/ant-design#28773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在想实现只读的行为，只能通过严格受控模式，同时阻拦组件的onChange事件（下拉类的组件，依然会弹出下拉框，给人一种可选择的感觉）。

另外。这在Form包裹的场景里又会给人造成一种能修改的假象（因为组件的onChange事件被Form接管了，但是Form包裹的组件又不建议使用严格受控的模式）。

我们是不是可以支持一下呢

### What does the proposed API look like?
以下只是个人设想：

1、添加一个readonly的布尔属性即可（类似原生HTML标签的readonly）；

2、只读状态下的onChange回调事件一律失效；

3、Select等选择类的下拉框不再弹出。

**Comment by afc163** [comment]
建议用 disabled 属性，readOnly 很难和默认状态有区分。

如果不希望 disabled 的样式，建议用只读模式渲染方式和修改模式的渲染方式完全用两套，比如 text 对应 input。

**Comment by DearGaz** [comment]
其实这两种方式都有考虑，也都用过。效果不是很好。

`readOnly 很难和默认状态有区分`  是指即便加了只读属性，也不好区分出组件是只读还是可编辑么；就像禁用，通过变灰标识，只读则难以找到直观的方式来标识？

**Comment by afc163** [comment]
> 也不好区分出组件是只读还是可编辑么

对的。

**Comment by DearGaz** [comment]
可是介个问题总是有解决方案的，不论是从颜色上还是从交互上，总能设计出一套主题区分出来。
倒是也可以自己套个壳子重新禁用的样式，但是很累赘。 怎么办，还是想争取下呀

**Comment by codingbycat** [comment]
禁用状态给人感觉阅读性会比较弱一些，只读模式是不是可以设计成可阅读性更高的UI样式且无法交互的主题？

**Comment by qiaodaima** [comment]
@afc163 
[antd pro 表单有提供可读的属性，以及样式上有一些区分](https://codesandbox.io/s/jibenshiyong-forked-9kbei?file=/App.tsx)

有时候写后台经常`antd `和 一起混用，现在`pro `支持` readonly`，而`antd 却不支持`，
感觉会有点奇怪

**Comment by AnteeHub** [comment]
Select 单选的只读状态勉强可以通过属性 `**open** : false`  来控制，但实际上应该有更好的语义化使用。

**Comment by kaichii** [comment]
怎么就 close 了？
