### ISSUE TITLE
High CPU usage when using tooltipVisible on Slider

### ISSUE THREAD

**Issue by karniv00l** [ant-design/ant-design#28788]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ws3dw)

https://slider-antd.vercel.app/

### Steps to reproduce
Render one or more <Slider> with tooltipVisible attribute set to true. Check the CPU usage at idle.

### What is expected?
Not to use much CPU at idle.

### What is actually happening?
When single <Slider> is rendered with tooltipVisible CPU usage stays around 10% at idle and between 80-90% when 15 sliders with visible tooltips are rendered.

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | macOS Catalina 10.15.1 |
| Browser | Chrome 87 |

---

**Comment by karniv00l** [comment]
This also happens with `tooltipVisible = false` and hovering over slider handle - when tooltips shows up.

**Comment by karniv00l** [comment]
I believe this is caused by the recursion here: https://github.com/ant-design/ant-design/blob/master/components/slider/SliderTooltip.tsx#L22

**Comment by jqweryjson** [comment]
Same issue too

**Comment by alienzhangyw** [comment]
Yes, it may freeze the page when dragging fast, losing frames.
