### ISSUE TITLE
Drawer throwing error - "Unable to preventDefault inside passive event listener invocation."

### ISSUE THREAD

**Issue by felipepsq** [ant-design/ant-design#28787]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce
Open the drawer page and simulate a mobile device (Chrome DevTools > Toggle decide toolbar), then slide to close the drawer.

### What is expected?
First, no error.
Second, close the drawer.

### What is actually happening?
Error: Unable to preventDefault inside passive event listener invocation.

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Ubuntu 20.04.1 LTS |
| Browser |  Google Chrome 87.0.4280.88 |

---
Is the close drawer action (push) working on iOS Safari?

**Comment by Chameleon45** [comment]
Want to add that Slider component throws "Unable to preventDefault" error on each touch in mobile device simulation. Also if to add Slider in Drawer component it starts to throw this error on each change of value.

**Comment by mortenmo** [comment]
This issue seems related to this issue #25870

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/drawer/pull/153

**Comment by Affrit** [comment]
I'm having the same issue

**Comment by monolithed** [comment]
<img width="1130" alt="Screenshot 2023-08-29 at 14 58 02" src="https://github.com/ant-design/ant-design/assets/803674/a48fa272-f4dd-4781-8d58-b80a888b6279">
<img width="1052" alt="Screenshot 2023-08-29 at 14 58 20" src="https://github.com/ant-design/ant-design/assets/803674/cb15f2a2-eb74-43cd-9a75-7ee53d8b6486">
