### ISSUE TITLE
 this.props.form.resetFields() 对 <Input  type="text" />  无法重置

### ISSUE THREAD

**Issue by lanxingshou** [ant-design/ant-design#2878]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

#### 你期待的结果是：

http://ant.design/components/form/#components-form-demo-validate-static
官网的例子重置没有input类型，是不是重置不支持input啊

**Comment by lanxingshou** [comment]
我调试了1天了
这个问题

**Comment by lanxingshou** [comment]
官网的例子在我这里本地都正常，就Input挂了为啥

**Comment by afc163** [comment]
http://ant.design/components/form/#components-form-demo-validate-basic

这些例子不都是 Input 么？

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by lanxingshou** [comment]
好的，没想到回复如此神速，赞！我马上弄个例子来，谢谢~

**Comment by dai875939260** [comment]
需要双向绑定才能重置

**Comment by lanxingshou** [comment]
![image](https://cloud.githubusercontent.com/assets/12092274/18078965/e76fcb52-6ec0-11e6-9d82-8f6f81cc1cb6.png)  可能是这个问题导致的。我本地 火狐下可以成功重置，但是chrome不行，chrome版本不支持Object.assign

pen可以重置
http://codepen.io/lanxingshou/pen/VjoNOb?editors=0010

**Comment by afc163** [comment]
添加 es6-shim 或升级 chrome 。

**Comment by afc163** [comment]
react-slick 里有个 bug：https://github.com/akiran/react-slick/pull/414

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/pull/447
