### ISSUE TITLE
select组件想要禁止默认键盘行为

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#28780]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有一个场景: 一个包含select的form表单.  实现了 键盘回车提交行为功能.   但是在select聚焦状态下.  键盘回车既触发表单提交功能也触发了select的选择功能.
而禁止键盘事件. 就能解决在slect聚焦状态下. 键盘回车只触发form表单提交行为

### What does the proposed API look like?
我期望一个API  keybordEnable: boolean  可以控制select键盘行为

**Comment by afc163** [comment]
你需要的是 AutoComplete 而不是 Select。
