### ISSUE TITLE
InputNumber 在 focus 状态下被卸载不会触发 onBlur

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#28789]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-wphcng?file=index.js](https://stackblitz.com/edit/react-wphcng?file=index.js)

### Steps to reproduce
focs 状态下输入非法字符，然后将 InputNumber 卸载

### What is expected?
正常触发格式化

### What is actually happening?
没有格式化

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | MAC |
| Browser | CHROME |

**Comment by kerm1it** [comment]
这是符合预期的，销毁的时候本来就不应该触发格式化，组件都已经消失了为什么还有触发？

**Comment by Dolov** [comment]
> 这是符合预期的，销毁的时候本来就不应该触发格式化，组件都已经消失了为什么还有触发？

组件虽然被销毁了，但是组件产生的值需要被消费。
比如有这样的场景，单元格内有可编辑和查看状态，查看状态的值就是由编辑状态下的 InputNumber 生产的。

**Comment by kerm1it** [comment]
明白了，但是其实你这个是根据特殊的业务场景来决定的，正常情况下就是等用户输入完触发了 blur 事件，然后触发格式化。

现在如果满足了你这种需求，可能以后又有另外一种业务场景需要，销毁后不需要触发格式化

例如，有个表单，最开始渲染了 number 组件，还没有输入值，这时触发了一个业务联动逻辑，这个 number 组件消失卸载了，此时提交表单时很明显不应该提交 number 组件的值（用户还没有输入），按照你的逻辑，提交表单时会把格式化后的 number 组件默认值提交上去。

**Comment by Dolov** [comment]
> 明白了，但是其实你这个是根据特殊的业务场景来决定的，正常情况下就是等用户输入完触发了 blur 事件，然后触发格式化。
> 
> 现在如果满足了你这种需求，可能以后又有另外一种业务场景需要，销毁后不需要触发格式化
> 
> 例如，有个表单，最开始渲染了 number 组件，还没有输入值，这时触发了一个业务联动逻辑，这个 number 组件消失卸载了，此时提交表单时很明显不应该提交 number 组件的值（用户还没有输入），按照你的逻辑，提交表单时会把格式化后的 number 组件默认值提交上去。

那有没有必要设置一个属性开关呢？
我现在是封装了一层，组件卸载时调用实例上面的 onBlur 方法。
但是我担心你们那天升级 InputNumber 为函数式组件后就不再暴露这个方法了。

**Comment by kerm1it** [comment]
组件设计需要考虑它的普遍适用性，你这个需求比较少见，可能到时做了就你一个人用到了。

如果 onBlur 方法是 API 文档上的，那就一半不会改变，即使变了也会提前有废弃警告，如果是内部用到的方法，可能会在重构时有所改变。
