### ISSUE TITLE
Table sorter function is not work probably

### ISSUE THREAD

**Issue by futurouz** [ant-design/ant-design#28798]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-keldysh-p80pz?file=/src/App.js)

### Steps to reproduce
Start with 

``` javascript
const lists = [
  {
    date: null
  },
  {
    date: "2021-01-01T14:31:33.234Z"
  },
  {
    date: null
  },
  {
    date: null
  },
  {
    date: "2021-01-02T14:31:33.234Z"
  },
  {
    date: "2021-01-03T14:31:33.234Z"
  },
  {
    date: null
  },
  {
    date: null
  },
  {
    date: "2021-01-04T14:31:33.234Z"
  }
];
```

and with the custom sorter function

```javascript
function sorterDate(a, b, option) {
  if (a.date === b.date) {
    return 0;
  } else if (a.date === null) {
    return 1;
  } else if (b.date === null) {
    return -1;
  } else if (option === "ascend") {
    return a.date < b.date ? -1 : 1;
  } else {
    return a.date < b.date ? 1 : -1;
  }
}
```

### What is expected?
Sort in the **desc** case
```
[
 "2021-01-04T14:31:33.234Z",
 "2021-01-03T14:31:33.234Z",
 "2021-01-02T14:31:33.234Z",
 "2021-01-01T14:31:33.234Z",
 null,
 null,
 null,
 null,
 null
]
```

### What is actually happening?
```
[
 null,
 null,
 null,
 null,
 null
 "2021-01-01T14:31:33.234Z",
 "2021-01-02T14:31:33.234Z",
 "2021-01-03T14:31:33.234Z",
 "2021-01-04T14:31:33.234Z",
]
```

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | MacOS bigsur 11.0.1 |
| Browser | Google chrome 87.0.4280.141 (Official Build) (x86_64) |

---
You can check in the `sorterDate2` function that in the code sandbox and it's work fine.

**Comment by afc163** [comment]
https://codesandbox.io/s/purple-pine-vzztd?file=/src/App.js

**Comment by dadazhouRenee** [comment]
我看默认是设置为0 如果数据不是时间类型 希望没有数据的项排在最后 有负数的话这边怎么处理啊  @afc163
