### ISSUE TITLE
升级antd版本从0.12.x到1.6.x，在npm start的时候遇到问题

### ISSUE THREAD

**Issue by pushingmyway** [ant-design/ant-design#2879]
#### 本地环境
mac

- antd 版本: 0.12.x
- 操作系统及其版本：
- 浏览器及其版本:

#### 你做了什么？
升级版本到1.6.x

#### 你期待的结果是：
npm start之后可以通过 http://127.0.0.1:8989访问到页面

#### 实际上的结果：
在npm start的时候出现这个问题
ERROR in ./src/common/lib.js
Module not found: Error: Cannot resolve module 'antd/lib/index.css' in $CWD/src/common
 @ ./src/common/lib.js 3:0-29

#### 可重现的在线演示
1.修改package.json中的antd版本为1.6.x
2.rm -rf node_modules && cnpm install
3.删除本地/Users/Xinglei/node_modules ,不知道这个文件夹是干什么的
4.npm start

**Comment by afc163** [comment]
请认真阅读 changelog。
