### ISSUE TITLE
After Dayjs Update To 1.10.3, error. Please lock the package

### ISSUE THREAD

**Issue by illusi03** [ant-design/ant-design#28806]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/iamkun/dayjs/releases/tag/v1.10.3](https://github.com/iamkun/dayjs/releases/tag/v1.10.3)

### Steps to reproduce
https://github.com/iamkun/dayjs/releases/tag/v1.10.3

### What is expected?
Maybe from dayjs still bug in week

### What is actually happening?
from dayjs, t.week show is not a function.

| Environment | Info |
|---|---|
| antd | 4.10.1 |
| React | 16.13.1 |
| System | Windows 10 64bit |
| Browser | Chrome  |

---
I downgrade dayjs to 1.8.30, and remove dayjs from antd installed, has solved. 
Please lock the dayjs into version ~1.8.0,

**Comment by illusi03** [comment]
<img width="1210" alt="Screen Shot 2021-01-11 at 11 31 19" src="https://user-images.githubusercontent.com/52351532/104148356-8b622700-5404-11eb-9213-3b7dd8e168f9.png">

There the error.

I downgrade dayjs to 1.8.30, and remove dayjs from antd installed, **has solved**.
Please lock the dayjs into version ~1.8.0, or maybe dayjs wanna to solve this problem.

Thanks in advice ...

**Comment by afc163** [comment]
Please report it to dayjs or use yarn.lock in your project.
