### ISSUE TITLE
4.10.0 table多级筛选无法筛选

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#28801]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![微信截图_20210110150841](https://user-images.githubusercontent.com/3166799/104121512-c8cda280-5379-11eb-9b91-5327933c5937.png)

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome 89 |

**Comment by hihuangwei** [comment]
多级分类的筛选 接收到的是空数组
https://github.com/ant-design/ant-design/pull/28627

**Comment by afc163** [comment]
@Meowu

**Comment by Meowu** [comment]
I will fix it.
