### ISSUE TITLE
Table组件数据显示错乱

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#2880]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：windows10
- 浏览器及其版本: chrome 54.0.2832.2 dev-m (64-bit)

#### 你做了什么？

使用Table，dataSource中有一个字段的值为“？？！。。，，！！？！。，，！！！，，！？？！。，。！！？？。，？？，！？？！。~，~！！！。。。。”

#### 你期待的结果是：

特殊字段值的那一格会换行

#### 实际上的结果：

特殊字段值的那一格没有换行

#### 可重现的在线演示

http://codepen.io/infeng/pen/wWVREj?editors=0010

**Comment by ddcat1115** [comment]
自己在render中加样式控制折行吧，table也不知道具体内容的折行策略啊

**Comment by infeng** [comment]
@ddcat1115 那为什么其他的内容可以自动换行，就这个值不行

**Comment by benjycui** [comment]
浏览器机制问题，不是组件的事。
