### ISSUE TITLE
Select showSearch as false does not work with filterOption

### ISSUE THREAD

**Issue by dilizarov** [ant-design/ant-design#28802]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nb9xl)

### Steps to reproduce
1. Type into the input box
2. Open your console and notice filterOption is not called.

### What is expected?
filterOption should be called so that I can filter out options (namely, I don't want to show selected options in the dropdown).

### What is actually happening?
filterOption is not called, so I cannot stop the menu from showing selected items.

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 16.13.1 |
| System | macOS Big Sur 11.1 |
| Browser | Google Chrome 87.0.4280.88 |

---
The reason I use showSearch={false} is because without this, the tag is shown in the dropdown of options, which I also don't want.

I want dropdown items to simply be what I pass into options, but it seems Ant Design gets clever behind the scenes.

**Comment by kerm1it** [comment]
`filterOption` will only work when `showSearch` is true.
