### ISSUE TITLE
In nzpaginationmodule, if I set both [nzsimple] and [nzshowsizechanger], then [nzshowsizechanger] is invalid

### ISSUE THREAD

**Issue by MatchaCutie** [ant-design/ant-design#28809]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In nzpaginationmodule, if I set both [nzsimple] and [nzshowsizechanger], then [nzshowsizechanger] is invalid

### What does the proposed API look like?
In nzpaginationmodule, if I set [nzsimple] and [nzshowsizechanger] at the same time, [nzshowsizechanger] is still valid

**Comment by kerm1it** [comment]
Would you like to submit issue in https://github.com/NG-ZORRO/ng-zorro-antd?

**Comment by MatchaCutie** [comment]
I'm sorry.
