### ISSUE TITLE
The new release 4.10.1 is unable to build on nodejs v12 with nextjs

### ISSUE THREAD

**Issue by nevestuan** [ant-design/ant-design#28804]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nevestuan/with-ant-design](https://github.com/nevestuan/with-ant-design)

### Steps to reproduce
Run "npm run build" with nodejs version v12.20.1
or
Deploy to vercel

It throws error:
          Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /vercel/workpath0/node_modules/@babel/runtime/helpers/esm/extends.js

          require() of /vercel/workpath0/node_modules/@babel/runtime/helpers/esm/extends.js from /vercel/workpath0/node_modules/antd/lib/affix/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

### What is expected?
It should build successfully.

### What is actually happening?
Updated from antd v4.10.0 to v4.10.1

| Environment | Info |
|---|---|
| antd | 4.10.1 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome |

**Comment by ranbena** [comment]
Reproducible in https://github.com/vercel/next.js/tree/canary/examples/with-ant-design when upgrading `antd` from `4.10.0` to `4.10.1`.

**Comment by afbarbaro** [comment]
Having the same problem on one of our apps 😞 .  Would love to get a fix soon as this is breaking our CI/CD pipeline for this project.  Thank you!

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/xyz/git/myproject/node_modules/@babel/runtime/helpers/esm/extends.js
require() of ES modules is not supported.
require() of /Users/xyz/git/myproject/node_modules/@babel/runtime/helpers/esm/extends.js from /Users/xyz/git/myproject/node_modules/antd/lib/grid/row.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename extends.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/xyz/git/myproject/node_modules/@babel/runtime/helpers/esm/package.json.
```

**Comment by shaodahong** [comment]
@afc163 https://github.com/ant-design/antd-tools/commit/e4551ddc8fc85f783c7061ec7ab111c158267cf6
