### ISSUE TITLE
TreeSelect 'allowClear' icon and Dropdown icon need to show at the same time

### ISSUE THREAD

**Issue by xianghongai** [ant-design/ant-design#28805]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The AllowClear Icon is displayed only when the mouse is moved up. The user cannot know that there is an operation that can be cleared by default. Of course, our computer professionals know this operation.

In addition, the drop-down indicates that the Icon should not overlap with the clear Icon. Non-computer professional users will really click the drop-down Icon to expand the drop-down box. The two overlapped, how did the user operate? Of course, computer professionals know that clicking the Select blank area can bring up the drop-down panel.

--- 

AllowClear Icon 是鼠标挪上才显示 ，用户没法在默认常规情况下知道有可以清除的操作。当然，我们计算机专业的知道这个操作。

另外，下拉指示Icon不应该和清除 Icon 重叠，非计算机专业用户真的会点击 Dropdown Icon 去展开下拉框。两个重叠在一起了，用户怎么操作了？当然，计算机专业知道点击 Select 空白区域能出来下拉面板。

### What does the proposed API look like?
Separate display of'allowClear' icon and Dropdown icon.

---

将'allowClear' icon 和 Dropdown icon 分开显示

![TreeSelect-allowClear-Dropdown](https://user-images.githubusercontent.com/2075006/104143449-6e285b00-53fa-11eb-9826-6273bd6a38b8.png)

**Comment by zombieJ** [comment]
设计上不会改变，但是你可以通过 HOC 自行实现相关设计。
