### ISSUE TITLE
给表单控件设置rules属性后 后面再绑定onchange就没用了

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#2881]
#### 本地环境

- antd 版本:
- 操作系统及其版本：1.10.0
- 浏览器及其版本:chrome

#### 你做了什么？

给表单控件设置rules属性后 后面再绑定onchange就没用了

#### 你期待的结果是：

正确实现rules验证和onchange事件

#### 实际上的结果：

这两个不能共存

#### 可重现的在线演示
const group_id = getFieldProps('group_id', {
        rules: [{
          required: true,
          type: 'array',
          message: '请选择分组'
        }]
      }, {
        onChange: this.groupChange.bind(this)
      }),

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1353

**Comment by ChenQiWen** [comment]
打开你发的链接 翻了好多 还是没找到答案 您能给写个例子吗  getFieldProps()里面该怎么写

**Comment by afc163** [comment]
```jsx
const group_id = getFieldProps('group_id', {
        rules: [{
          required: true,
          type: 'array',
          message: '请选择分组'
        }],
        onChange: this.groupChange,
      });
```
