### ISSUE TITLE
<Table/> Set custom props for columns / header columns (typescript)

### ISSUE THREAD

**Issue by pabloimrik17** [ant-design/ant-design#28817]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lkl8t?file=/index.js)

### Steps to reproduce
Just open the example and check the console

### What is expected?
In the docs the prop onHeaderCell says: "Set props on per header cell" and on many examples on internet, even on your docs is used to set custom props for the render methods:

https://ant.design/components/table/#components-table-demo-resizable-column
https://codesandbox.io/s/tp4lt

This is ok for Javascript users, but i expected to work also on Typescript

### What is actually happening?
Everything "works" for Javascript users, because all the props you set on onHeaderCell are passed to the expected custom render method, but for Typescript users like me there is a catch, because the object returned in onHeaderCell is typed like this:

"GetComponentProps<ColumnsType<RecordType>[number]>;" that later is  "React.HTMLAttributes<HTMLElement>;"

So for the compiler is limited to HTML Attributes only. 

Is this a mistake or is intended? If is intended, how i can set custom props and read then in for example a custom render method for any part of the table? (header cell, row cell, row itself)

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome (latest) |

**Comment by afc163** [comment]
Could you provide a Typescript codesandbox?

**Comment by pabloimrik17** [comment]
Hi, sorry this is the codesandbox example with TS

https://codesandbox.io/s/antd-reproduction-template-forked-txt2s?file=/index.tsx

**Comment by zombieJ** [comment]
It's by design. `HTMLAttributes` is aim to avoid miss typing of props since it will fully provides to the `th` element when you don't customize the component. But you can still cast it with your business logic instead:
https://codesandbox.io/s/antd-reproduction-template-forked-lehkp?file=/index.tsx

We may not adjust this since current definition is more common usage.
