### ISSUE TITLE
Refactor rc-drawer

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#28812]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
use react hook and [rc-motion](https://github.com/react-component/motion) refactor [rc-drawer](https://github.com/react-component/drawer)

**Comment by jljsj33** [comment]
建义 modal 也一起重构，我在以前的 issue 里说过，不然还是会有问题的。。这种弹出的抽个统一的，，再各个组件里管样式就行了。。

**Comment by jljsj33** [comment]
直接搞成  hooks 。。。

**Comment by shaodahong** [comment]
这个内容区块以前为啥会设计成点开跟着右移

https://user-images.githubusercontent.com/14831261/104165971-08a59000-5435-11eb-8765-1f9ffe174199.mp4

**Comment by jljsj33** [comment]
无线端的很多抽屉都是这样的，，我理解的这个概念是抽屉跟界面是平级的，那拉出来肯定将当前的元素往右移，拟物的模式吧。。。

**Comment by wendellhu95** [comment]
我看 rc-drawer 到现在还没有开始重构, 打算开搞了

**Comment by afc163** [comment]
Done: https://github.com/react-component/drawer/commits/master
