### ISSUE TITLE
Drawer, React does not recognize the `switchScrollingEffect` prop on a DOM element

### ISSUE THREAD

**Issue by magiclee203** [ant-design/ant-design#28818]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/drawer-cn/](https://ant-design.gitee.io/components/drawer-cn/)

### Steps to reproduce
antd 官网"基础抽屉"例子即可复现

### What is expected?
无warning

### What is actually happening?
show drawer 有 warning

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 17.0.1 |
| System | macOS Big Sur 11.1 |
| Browser | Chrome |

**Comment by yoyo837** [comment]
我没看到这个

**Comment by magiclee203** [comment]
随意 npx create-react-app 一个项目，粘贴上官网 Drawer 部分的基础使用代码，即可复现该 warning

**Comment by hdwong** [comment]
同样的问题

使用 `getContainer` 返回指定 DOMElement 时，会提示

> Warning: React does not recognize the `switchScrollingEffect` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `switchscrollingeffect` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by shaodahong** [comment]
@hdwong `yarn upgrade antd`

**Comment by hdwong** [comment]
> @hdwong `yarn upgrade antd`

Yup, work in antd@4.10.2.

**Comment by ccloveak** [comment]
@shaodahong 
the same issue
version  antd@4.12.2.
![image](https://user-images.githubusercontent.com/38686314/107480565-22ff9480-6bc0-11eb-8c30-76b5ca236419.png)

**Comment by yoyo837** [comment]
来个复现。

**Comment by ccloveak** [comment]
> 来个复现。

咦 。。。好了  删包 改版本后 重新 yarn install 不管用 
`yarn upgrade antd` 管用。。。
辛辛苦苦剥离业务代码，提交的时候想试一下来着。。。小丑竟是我自己

**Comment by yoyo837** [comment]
其实是yarn.lock文件的原因，删了再install就行。

**Comment by qizhou-tommy** [comment]
> 其实是yarn.lock文件的原因，删了再install就行。

确实是，ant 3.X
