### ISSUE TITLE
Closing dropdowns with ESC cancels Modal

### ISSUE THREAD

**Issue by MalteHartwig** [ant-design/ant-design#28815]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-l7tul)

### Steps to reproduce
- open modal
- click in select to open the dropdown
- press ESC

### What is expected?
When the focused input has an open drowdown, ESC should close the dropdown but the modal should not be cancelled. This is working for ANT 3.26.20

### What is actually happening?
ESC cancels the modal even though there is an open dropdown on the active input ever since 4.0.0

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome 86 |

---
Found it due too failing cypress test after updating from 3.x to 4.10.0

**Comment by kerm1it** [comment]
![Jan-11-2021 21-25-25](https://user-images.githubusercontent.com/33770367/104188014-92645600-5453-11eb-95e3-ce0dd43ec29f.gif)

It works correctly when I try it.

**Comment by MalteHartwig** [comment]
Hi Kermit, thanks for the response. 
I accidentally saved the sandbox when it was set to 3.26.20. Now I set it back to 4.10.0 and the modal closes when pressing ESC in the open select. Can you try again?
