### ISSUE TITLE
Modal弹出会使window滚动到最顶端

### ISSUE THREAD

**Issue by zhangmaliang** [ant-design/ant-design#28814]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/zhangmaliang/ModalBugTest](https://github.com/zhangmaliang/ModalBugTest)

### Steps to reproduce
运行项目后点击 “查询表格”， 下拉， 点击最后一行的 “配置”按钮弹出modal框， 会发现背后的window滚动到了最顶端

### What is expected?
弹出modal时背后window不滚动

### What is actually happening?
弹出modal时背后window滚动到最顶部

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | macOS Big Sur |
| Browser | chrome |

**Comment by afc163** [comment]
> html { overflow-y: scroll; }

为啥要加这个。

**Comment by zhangmaliang** [comment]
> > html { overflow-y: scroll; }
> 
> 为啥要加这个。

我项目是gatsby脚手架搭建的，在里面使用Modal发现了这个问题。最终定位到是默认配置中有 overflow-y: scroll 导致

**Comment by zombieJ** [comment]
@shaodahong  这个可以优化不？

**Comment by shaodahong** [comment]
> @shaodahong 这个可以优化不？

配置下就行，getContainer 默认是 `body`，如果你容器是 html 要写成这样 `getContainer={document.documentElement}`
