### ISSUE TITLE
<Menu.Item> doesn't show when using less import

### ISSUE THREAD

**Issue by wang3620** [ant-design/ant-design#28820]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sider-antd4102-forked-d3dvi?file=/index.js)

### Steps to reproduce
if we change this to import 'antd/dist/antd.less'; and collapse side, hover on User, the items doesn't show up

### What is expected?
<Menu.Item> should show up

### What is actually happening?
<Menu.Item> is not showing up

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.13.1 |
| System | macOS Mojave Version 10.14.6 |
| Browser | Google Chrome (Version 87.0.4280.141) |

---
I need to add less loader properly in my sandbox in order to make `import 'antd/dist/antd.less';` work. It's added on my machine, but not in the sandbox link.

**Comment by zombieJ** [comment]
We may not update codesandbox template since additional less loader will slow down the load speed. Reproduce template is used for user quick report issue which is not design for full dev env. If you have any less related reproduce issue, welcome to add less-loader in your codesandbox demo instead.
