### ISSUE TITLE
[Select] searchValue cover the placeholder

### ISSUE THREAD

**Issue by liuyiliuyi** [ant-design/ant-design#28828]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daisousuokuang-antd4102-forked-li0eo?file=/index.js)

### Steps to reproduce
```jsx
  <Select
    showSearch
    style={{ width: 200 }}
    placeholder="Select a person"
    searchValue="jack"
  >
    <Option value="jack">Jack</Option>
    <Option value="lucy">Lucy</Option>
    <Option value="tom">Tom</Option>
  </Select>
```

### What is expected?
show searchValue Only(show [Jack] Only).

### What is actually happening?
SearchValue cover the placeholder([Jack] cover the [Select a person]).

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.14.0 |
| System | MacOS |
| Browser | Chrome 87 |

**Comment by afc163** [comment]
You should use `defaultValue` instead of `searchValue` to show prefilled value.
