### ISSUE TITLE
model初始化form表单域，修改某个input提交后使用另外的model初始化，表单域初始值不更新

### ISSUE THREAD

**Issue by vincentshow** [ant-design/ant-design#2882]
项目中某个面板，左侧显示modelList，右侧使用form显示当前选中model的详情，支持修改和提交，想要实现切换左边的model，右侧的表单域可即时更新，操作下来有以下现象
1. 不修改input的值，表单域随左边选中model的变化而变化
2. 一旦修改某个input，再切换左边的model，该input初始值不再响应变化

我的使用方式有什么不妥么，在线重现
http://codepen.io/anon/pen/YGKyZb?editors=001#anon-login

**Comment by ddcat1115** [comment]
initialValue只是初始值，用setFeildsValue去控制value变化，仔细看下API

http://codepen.io/ddcat1115/pen/RGbAZV?editors=001#anon-login

**Comment by vincentshow** [comment]
感谢，setFieldsValue的确解决了问题

但还是有一点想不通，你的意思是initialValue只在form初始化时调用一次么，那为何我之前的demo中只要不修改input值form表单域的初始化没有问题呢

**Comment by vincentshow** [comment]
@ddcat1115 问题又来了，Radio组件我看官方的demo中都是设置initialValue或者defaultValue，我尝试了使用setFieldsValue自动赋值，但失败了，值绑不上，求指点

http://codepen.io/anon/pen/jrNqXE?editors=001#anon-login

**Comment by afc163** [comment]
确认下 initialValue 是否应该接收二次赋值。@benjycui

**Comment by benjycui** [comment]
cc @yiminghe

**Comment by yiminghe** [comment]
initialValue === defaultValue

**Comment by afc163** [comment]
那第一个例子里不应该变化的。

**Comment by benjycui** [comment]
现在的 initialValue 更贴近 placeholder，在没有用户输入的值时显示，而不是 defaultValue。

**Comment by 275287902** [comment]
@yiminghe 请问这个bug目前有没有好的方法可以解决，我在项目中用了dva，我看dva examples/user-dashboard这个项目，里面解决的办法是
`// 解决 Form.create initialValue 的问题
  // 每次创建一个全新的组件, 而不做diff
  // 如果你使用了redux, 请移步 http://react-component.github.io/form/examples/redux.html
  const UserModalGen = () =>
    <UserModal {...userModalProps} />;`
但是，如果userModalProps这个组件里有同步更改的state话，就会出现Modal再次打开的动画。

**Comment by benjycui** [comment]
个人认为，这并不是 bug，因为 Form 是具有数据收集、存储的功能，既然三个 modal 分别代表三份数据，那么也应当有三个 Form 实例分别收集。

**Comment by vincentshow** [comment]
@benjycui 好吧，这样理解也能讲的通，要么render new form，要么使用setFieldsValue，个人建议在官方文档中加上这么一个注意事项，感谢各位

**Comment by EdenLiang** [comment]
同问题，这个问题看到很多人提问，想必很多人也在此遇坑
1、在使用render new form的时候，修改state，则会“就会出现Modal再次打开的动画”
2、在把form当成无状态的子组件的时候，父组件无法获取到子组件的form，也就无法form.resetFields()
有办法是不把form当成子组件，而是直接插到父组件中（或者该子组件有自己的状态）
这样太不优雅，有更好的办法么
@benjycui

**Comment by EdenLiang** [comment]
dva examples/user-dashboard，这个项目在form提交的时候，并没有设置form的按钮loading，所以可能没有发现这个问题

**Comment by benjycui** [comment]
> 在使用render new form的时候，修改state，则会“就会出现Modal再次打开的动画”

要不是你没看懂这个 issue 就是我没看懂你的回复。。

只要 `Modal[visible]` 没有发生变化，就不会有动画，见：https://ant.design/components/form/#components-form-demo-form-in-modal

> 在把form当成无状态的子组件的时候，父组件无法获取到子组件的form，也就无法form.resetFields()
> 有办法是不把form当成子组件，而是直接插到父组件中（或者该子组件有自己的状态）

要把 `Form` 变成无状态就是完全受控的模式，就跟与 Redux 一起使用的用法一致了 http://react-component.github.io/form/examples/redux.html

**Comment by benjycui** [comment]
@sorrycc (dva creator) 推荐的是把 UI state 也放进 model。

**Comment by EdenLiang** [comment]
因为有强迫症要把model当成无状态组件，就是UI state存在父级，get了，我看到好几个issue都在说类似的form问题
thx

**Comment by Kaijun** [comment]
@benjycui 
我觉得这个issue的场景太常见了，是否可以给 modal 加一个 onOpen 的事件（prevProps.visible===false && nextProps.visibl===true），这样的话 onOpen 的时候就可以对 fields 进行 reset 或者其他操作。

不知道这个 issue 解决办法的最佳实践是怎样的？

**Comment by benjycui** [comment]
@Kaijun Modal 的 open 状态是通过 visible 属性控制的，你可以在 visible 变为 true 时执行 reset 逻辑。

**Comment by benjycui** [comment]
Modal 关闭又打开，这个场景是否需要清空表单数据，应该由业务决定，而现在组件的设计足以满足两种业务场景的需要。

**Comment by lcgyh** [comment]
Input一开始进来设置有defaultValue默认值，修改后setState，之后不更新，因为defaultValue只执行一次，但是我设置value又不能修改
`<Input defaultValue={text} **placeholder="采购数量"/>`**，求帮助

**Comment by lcgyh** [comment]
Input一开始进来设置有defaultValue默认值，修改后setState，之后不更新，因为defaultValue只执行一次，但是我设置value又不能修改
`<Input defaultValue={text} **placeholder="采购数量"/>`**，求帮助
@benjycui

**Comment by StevenWung** [comment]
The same issue here
