### ISSUE TITLE
Missing Translations for Transfer Component

### ISSUE THREAD

**Issue by aequi42** [ant-design/ant-design#28825]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-b1zo9?file=/index.js)

### Steps to reproduce
* Create a transfer component
* Wrap it in a ConfigProvider and set a other locale than english/chinese
* Open the menu for batched selection (arrow next to number of selected items)
* Witness the english strings instead of their translation (e.g. "Select all data" or "Invert current page")

### What is expected?
The strings should be localized
![image](https://user-images.githubusercontent.com/15265105/104281050-23b3e680-54ad-11eb-9d1d-ccfe91f39fb2.png)

### What is actually happening?
The strings are displayed in english

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 17.0.1 |
| System | any |
| Browser | any |

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/104282182-9ba00200-54e9-11eb-8e36-351100e27280.png)

We need help from contributors in different languages.

**Comment by aequi42** [comment]
Okay, i'll look into the german translation :)
