### ISSUE TITLE
Table组件rowSelection的columnWidth默认值无效

### ISSUE THREAD

**Issue by PeiTianHuang** [ant-design/ant-design#28837]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/55vwx)

### Steps to reproduce
直接查看选择框所在列的宽度

### What is expected?
选择框所在列的宽度应默认是60px

### What is actually happening?
当前默认宽度无效，此时为32px

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome80 |

![image](https://user-images.githubusercontent.com/17986764/104414159-b8e8d500-55aa-11eb-9fe1-f3170a38e3e8.png)

**Comment by afc163** [comment]
文档忘了改：https://github.com/ant-design/ant-design/pull/28073
