### ISSUE TITLE
Image 组件展示不正确

### ISSUE THREAD

**Issue by Pzx1997** [ant-design/ant-design#28830]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Pzx1997/antd_Image_bug](https://github.com/Pzx1997/antd_Image_bug)

### Steps to reproduce
引入Image组件展示不正常

### What is expected?
Image组件正常显示

### What is actually happening?
Image组件鼠标上移时的遮罩层没有 

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.0 |
| System | window10 |
| Browser | Google |

---
检查发现遮罩层的div没有了

**Comment by Pzx1997** [comment]
Importing the Image component is not displaying properly

**Comment by Pzx1997** [comment]
Mask layer for Image component mouse up is not available

**Comment by Pzx1997** [comment]
https://github.com/Pzx1997/antd_Image_bug

**Comment by afc163** [comment]
升级到最新版本 4.10.1 即可修复。

**Comment by Pzx1997** [comment]
好的 Thanks

**Comment by Pzx1997** [comment]
> 升级到最新版本 4.10.1 即可修复。
好的 Thanks
