### ISSUE TITLE
Textarea 组件设置 autoFocus ，光标出现在值前面

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#28840]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-msiqjs?file=index.js](https://stackblitz.com/edit/react-msiqjs?file=index.js)

### Steps to reproduce
Textarea 设置  autoFocus

### What is expected?
光标出现在值后面，可以直接输入

### What is actually happening?
光标出现在值前面，需要手动将光标移动至后面

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by MrHeer** [comment]
是不是可以做个这样的 API, 设置为 true 的时候默认 focus 到文末，也可通过 InputFocusOptions 来配置 autoFocus 的行为
```typescript
autoFocus: boolean | InputFocusOptions
```

**Comment by mumiao** [comment]
TextArea原生标签 ```autofocus```是光标出现在值前面,目前这个是要处理默认聚焦 聚焦到文末？ @afc163

**Comment by afc163** [comment]
@mumiao 我测试了一下，原生 textarea 光标是在后面的。

**Comment by mumiao** [comment]
> @mumiao 我测试了一下，原生 textarea 光标是在后面的。

看一下这个demo第二个聚焦效果：http://www.xuandaima.com/Test/index.php/index?canshu=HTML_textarea_autofocus
我测试了两个demo 都是光标在前面

**Comment by mumiao** [comment]
> @mumiao 我测试了一下，原生 textarea 光标是在后面的。

![image](https://user-images.githubusercontent.com/22880945/104537852-b3949480-5655-11eb-8e31-f516bd117c4f.png)

**Comment by afc163** [comment]
@mumiao 还真是，我刚才测试成 `<input type="textarea" />` 了。

@Dolov 既然是原生行为，这里不做多余处理，可以自行调用 textarea 的方法去控制光标位置。

**Comment by Dolov** [comment]
不考虑做一个开关么，个人觉得原生的这个行为有点不符合用户的操作认知。autoFocus 就是为了让用户更快速的输入内容，结果却需要先移动光标 @afc163

**Comment by hellobq** [comment]
element.setSelectionRange(-1, -1)
