### ISSUE TITLE
关于表格内编辑，优化方法！

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#2884]
看到这个界面不知道大家有什么优化方法，目前增加到20行就变成幻灯片了。
每一个控件都绑定了Form验证，后面还有6个文本框各种有互算操作。

![3ee2890e-ce1f-4b4d-bcb1-a06c7b2a0a5c](https://cloud.githubusercontent.com/assets/2884665/18075591/af2dbbcc-6ea8-11e6-9c2e-fdc6468608e2.png)

我目前有个优化方案，想想会比较费时间就没去弄，先来问问可不可行：
为每个单元格的组件在封装一个组件，自己写逻辑去验证，不绑定Form，暴露setState方法供外部调用。
尽量避免表格整体的渲染。

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/2029#issuecomment-233841928

是不是可以增加一个`renderRow`的 props，可以让使用者自己控制 row 的渲染。

```javascript
<Table columns={columns} dataSource={data} renderRow={TableRow => pureRender(TableRow)} />
```

**Comment by benjycui** [comment]
可以不用 `Form.create` 的，只是这样就要自己完成校验和数据收集。

**Comment by xutou12** [comment]
在 增加 / 删除 行时性能还是低。
最好有个什么方法可以阻止 row 的内部渲染

提供一个rowRender属性确实可行。但是表格内部有自己的row的渲染算法，这个rowRender要做到兼容一定很麻烦吧？
表格的话我觉得还是整体封装比较好。

是不是可以这样做，我觉得比较通用的做法
表格学表单那样另做一个HOC，命名为 Table.create()，提供一个 props.Table 对象提供一些方法
比如 用key做键值 添加 / 删除 行、过滤、setRowState( key, state ) / getRowState( key, state )/getTableState/setTableState方法、RowForm 对象 等等。

columns 中的render 可以取到每一行的 state 或者 Form 做一些 数据 / 表单 操作。

这样就可以避免表格的整体渲染还能做很多事情。

当然我知道这样实现估计会很有难度 ^ _ ^

当然我不知道

**Comment by yesmeck** [comment]
> 提供一个rowRender属性确实可行。但是表格内部有自己的row的渲染算法，这个rowRender要做到兼容一定很麻烦吧？

好像没什么要兼容的吧？把现在的`TableRow`作为参数传给`rowRender`，然后可以让使用者对`TableRow`自己进行一些封装再返回（如我上面 pureRender 的例子）。

刚发现，现在`TableRow`里写了[shouldComponentUpdate](https://github.com/react-component/table/blob/master/src/TableRow.jsx#L42-L44)，感觉这样其实是留了坑的。

`FormItem`里也有一个[shouldComponentUpdate](https://github.com/ant-design/ant-design/blob/master/components/form/FormItem.tsx#L61-L63)，但是我们项目里有个用在`FormItem`里的组件用了`context`，`FormItem` 的`sCU`导致上层组件的`context`变化了，`FormItem`不会重新渲染。然后我们自己要封装了下`FormItem`把`sCU`去掉。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2484#issuecomment-234860010

**Comment by yesmeck** [comment]
还有一点，像这个 https://github.com/react-component/table/issues/83，如果 TableRow 能通过 rowRender  暴露出来的话，就可以用  react-dnd 来实现拖拽了。

**Comment by whx76** [comment]
我也在做这个表格编辑，我觉得，行数多了任何输入都会导致整个页面render(),而页面上所有antd组件没有实现shouldcomponentupdate，所以都要重新绘制，非常慢。我在input.js中加入     _this.shouldComponentUpdate = function (nextProps, nextState) {       
      return (  this.props.value !== nextProps.value ); 
    }
性能提高非常多。所以一方面我们缩小刷新范围，另外是否antd组件也进行优化避免render

**Comment by jzlxiaohei** [comment]
@yesmeck `TableRow`暴露了，有些地方也不好实现，比如用react-dnd 设置整行可拖拽，那么这行的文字就不能复制了。这里就希望`TableRow`的某个cell是可拖拽的，整行跟着动，这样要把`TableCell`也暴露?感觉不现实。column based的table，在处理row的时候，感觉灵活性很差，很难设计。

**Comment by yesmeck** [comment]
> 那么这行的文字就不能复制了

为什么会不能复制？

> 这样要把TableCell也暴露?

现在 column 里的 render 其实就是 cell， cell 拖动应该可以通过这个实现吧（猜想）。

> column based的table，在处理row的时候，感觉灵活性很差，很难设计。

这个我也想过，虽然灵活性差，但是要提供高级的功能（filter 之类）这么设计实现起来更方便。

**Comment by yesmeck** [comment]
> 那么这行的文字就不能复制了

明白你说的了，不要把整行都设为 DragSource 就可以了。

**Comment by jzlxiaohei** [comment]
你把这个网页上，任意下面有文字的`div`，设置成`draggable='true'`后，里面的字用鼠标都不能复制

我今天的初步实现，是 在 columns里的某一项 里的 render，加draggble, 然后再找到上层最近的tr，然后去实现拖拽，感觉很ugly

**Comment by xutou12** [comment]
目前我们的排序实现是这样的
![image](https://cloud.githubusercontent.com/assets/2884665/18336241/1e1d87ea-75b8-11e6-99b8-e342bbcc5d6f.png)

我以前也是在表格上实现排序拖动的，后来列数越来越多，内容也越来越复杂，锁定啊编辑框啊什么的，后来为了避免复杂度增加就用这个方法了设置主键名称就行。

**Comment by xutou12** [comment]
感觉想太多了，拖拽这样的功能由官方封装比较好，毕竟变化的情况不多，官方放出接口兼容性会更好。

**Comment by yeliex** [comment]
可以封装一个Form组件,使用Table的样式

**Comment by Midqiu** [comment]
我想问一下你每行最后的附件和删除功能是怎么做的，就是怎么获取到用户操作的当前行的数据？

**Comment by whx76** [comment]
https://github.com/ant-design/ant-design/blob/design-pattern/docs/pattern/table/demo/edit-hover.md
参考这个例子，写表格的columns的render事件生成组件

**Comment by afc163** [comment]
给 @yesmeck 加了 rc-table 的管理员权限。

**Comment by ruizhengyun** [comment]
有表格编辑的案例me @afc163

**Comment by yesmeck** [comment]
这几天给 `Table` 做了些优化，说下我现在的一些想法：

首先是碰到一个问题，就是当 `columns` 里的 `render` 依赖当前组件的状态时，`TableRow` 就不是一个  Pure Component 了，没法用 `shouldComponentUpdate` 去优化（见：https://github.com/react-component/table/pull/98）。

那有没有办法让 `render` 不依赖当前组件的状态来实现类似表格内编辑的功能呢，以 @whx76 贴的那个 edit-hover 的例子为基础，我把它改成了[这样](https://gist.github.com/yesmeck/9203a86c08734877d226e89951b2b1ca)，我把 `EditableTable` 的 `visible`  去掉，把 `dataSource` 作为 `EditableTable` 的状态，然后把编辑中（editing）的状态直接写到 `data` 上，这样在 `render` 里就可以通过读取 `record` 参数拿到编辑状态，避免了在 `render` 中直接依赖 `EditableTable` 的 `state`。我想这个可以写到文档或者 wiki 里。

那如果非要有人在 `render` 里访问当前组件的状态怎么办？我觉得可以给 `Table` 加一个 `optimize` 的 `prop`，`optimize` 为 `true` 的时候就在 `TableRow` 启用 `shouldComponentUpdate`，反之就关闭。

**Comment by afc163** [comment]
这样的话，把

```jsx
class EditableTable extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      innerState: 1,
    };
    this.columns = [{ ... }];
  }
  render() {
    return <Table columns={this.columns} />
  }
```

改成下面这样，应该是更好的实践，这样把 columns.render 变成一个纯函数式的渲染（把事件用参数传递给 columns.render），也避免直接访问 this.state。

```jsx
const getColumns = (innerState, onVisibleChange) => {
  return [{ ... }] // columns objects
};

class EditableTable extends React.Component {
  render() {
    return <Table columns={getColumns(this.state.innerState, this.onVisibleChange)} />;
  }
}
```

然后利用 [memorize](https://gist.github.com/creamidea/8145035) 防止每次返回不同的 columns。

**Comment by yesmeck** [comment]
```javascript
const getColumns = (innerState, onVisibleChange) => {
  return [{ ... }] // columns objects
};

class EditableTable extends React.Component {
  render() {
    return <Table columns={getColumns(this.state.innerState, this.onVisibleChange)} />;
  }
}
```

这样不行的，当 `this.state.innerState` 发生变化的时候，`getColumns` 就会返回新的`columns`，`TableRow`里的 `shouldComponentUpdate ` 就会返回 `false` 呀。

**Comment by yesmeck** [comment]
把 `columns` 的 `render` 看成一个组件，这个组件通过闭包依赖了除了 `props`  和 `state`（`context` 比较特殊，另算）以外的的数据，它就是一个 Impure Component 了。

**Comment by xiaoqqchen** [comment]
可不可以采用Immutable对Table组件进行优化？不过这样基本要对Table组件进行大改了。
```js
import Immutable from 'immutable';

const is = Immutable.is.bind(Immutable);

export default function shallowEqualImmutable(objA, objB) {
  if (objA === objB || is(objA, objB)) {
    return true;
  }

  if (typeof objA !== 'object' || objA === null ||
      typeof objB !== 'object' || objB === null) {
    return false;
  }

  const keysA = Object.keys(objA);
  const keysB = Object.keys(objB);

  if (keysA.length !== keysB.length) {
    return false;
  }

  // Test for A's keys different from B.
  const bHasOwnProperty = Object.prototype.hasOwnProperty.bind(objB);
  for (let i = 0; i < keysA.length; i++) {
    if (!bHasOwnProperty(keysA[i]) || !is(objA[keysA[i]], objB[keysA[i]])) {
      return false;
    }
  }

  return true;
}

shouldComponentUpdate(nextProps, nextState) {
  return !shallowEqualImmutable(this.props, nextProps) || !shallowEqualImmutable(this.state, nextState);
}

```

**Comment by yesmeck** [comment]
@xiaoqqchen 问题不这里，现在主要是 columns 支持自定义的 render 导致 TableRow 不是一个 pure component，不能简单地用 shouldComponentUpdate 优化。

**Comment by xiaoqqchen** [comment]
@yesmeck 抛开这个问题，有没有必要使用Immutable对整个Table做性能优化？如果做的话，是不是改动会比较大？

**Comment by yesmeck** [comment]
@xiaoqqchen 没有必要，瓶颈不在这里，改动比较大。

**Comment by xiaoqqchen** [comment]
你的意思是不用Immutable，而是采用`shallowequal`做优化吗？
我做了一个实验，详见：https://www.zybuluo.com/xiaoqq/note/566436#四表格性能优化
发现单元格超过3000个时，优化还是很有必要的。

**Comment by yesmeck** [comment]
@xiaoqqchen 明天研究下你测试。

**Comment by yesmeck** [comment]
> 对于PlainObject，浅比较的优化之后的Table性能非常之好，即使对于10000个单元格也没有丝毫的卡顿，性能优化效果非常棒，反观对于不做性能的优化的Table就非常卡顿了；而Immutable的表现有点差强人意

@xiaofan2406 可是你的结论是在这样啊。。。

**Comment by jzlxiaohei** [comment]
个人认为可以来个简单版的 `Table`,提供最基本的`renderRow`啥的就行。
Table这个组件众口难调，各种需求都有。那么多功能下，优化很难做吧

**Comment by shann09** [comment]
table的瓶颈在于：
columns的render函数中，如果返回的数据包含react组件，性能马上下降，比如为一列数据增加“操作”列，包含“增加”、“删除”等Button，且Button外还包含Popconfirm和Tooltip，这时候，100行就能够造成300ms的延迟，因为table每次调用render，“操作”列的所有组件都重新生成并渲染。
100行 x (3个Button + 3个Popconfirm + 3个Tooltip)，计算量陡增。

解决方法在于：
提前生成“操作”列数据，即传入table的dataSource已经包含这些数据，render的时候只是抓取已经生成的数据，而不是生成和渲染。

低性能代码：
```
var rawData = [];
const Conf = React.createClass({
  render(){
    var _this = this;
    var columns = [{
      title: "名称",
      dataIndex: 'name',
      key: 'name',
    },{
      title:"操作",
      dataIndex: 'x',
      key: 'x',
      render(text, record, index){
        return (
          <Tooltip placement="top" title="删除">
            <Popconfirm title="确定删除？" placement="left" 
                onConfirm={_this.handleConfirmDelete.bind(null,record.sn)} 
                okText="删除" 
                cancelText="取消">
              <Button type="primary" icon="delete" />
            </Popconfirm>
         </Tooltip>
        );
      },
    }];
    return (
      <Table columns={columns} dataSource={rawData}/>
    );
  }
});
```

高性能代码：
```
var rawData = [];
const Conf = React.createClass({
  statics:{
    columns:[{
      title: "名称",
      dataIndex: 'name',
      key: 'name',
    },{
      title:"操作",
      dataIndex: 'x',
      key: 'x',
      render(text, record, index){
        return text;
      },
    }],
    genOperColData(record, _this){
      return (
          <Tooltip placement="top" title="删除">
            <Popconfirm title="确定删除？" placement="left" 
                onConfirm={_this.handleConfirmDelete.bind(null,record.sn)} 
                okText="删除" 
                cancelText="取消">
              <Button type="primary" icon="delete" />
            </Popconfirm>
         </Tooltip>
      );
    },
  },
  getInitialState() {
    var _this = this;
    rawData = _.map(rawData,function(record){
        return Object.assign(record,{x: Conf.genOperColData(record, _this)});
    });
    return {};
  },
  render(){
    return (
      <Table columns={Conf.columns} dataSource={rawData}/>
    );
  }
});
```

经过实测，降到80ms左右，另外，记得给webpack.config.js加上这段，性能差3倍哦
```
plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                //NODE_ENV: JSON.stringify('development'), //10秒编译时间，1/1运行时间
                NODE_ENV: JSON.stringify('production'), //10秒编译时间，1/3运行时间
            }
        }),
]
```

希望对大家有帮助

**Comment by benjycui** [comment]
@shann09 你的方案算是黑魔法了，不建议缓存 JSX 部分，数据就是数据。下面这样好点。

```jsx
class Operation {
  shouldComponentUpdate() {
    ...
  }
}

const columns = [{
  title: 'Operation',
  render() {
    return <Operation />;
  }
}]
```

**Comment by shann09** [comment]
@benjycui 对的，非常感谢！！
马上测试了，
“操作”按钮只需要生成一次，所以shouldComponentUpdate直接返回false，代码速度飞起
