### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by silverlovesl** [ant-design/ant-design#28851]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/overview-cn/](https://ant.design/components/overview-cn/)

### Steps to reproduce
Failed to compile
/Users/silver/Documents/workspace/BeeCombGrid/grid-ai/gridai_auth_frontend/node_modules/antd/lib/image/PreviewGroup.d.ts
TypeScript error in /Users/silver/Documents/workspace/BeeCombGrid/grid-ai/gridai_auth_frontend/node_modules/antd/lib/image/PreviewGroup.d.ts(2,13):
'=' expected.  TS1005

    1 | import * as React from 'react';
  > 2 | import type { GroupConsumerProps } from 'rc-image/lib/PreviewGroup';
      |             ^
    3 | export declare const icons: {
    4 |     rotateLeft: JSX.Element;
    5 |     rotateRight: JSX.Element;

### What is expected?
Fix it

### What is actually happening?
Get compile error when I run yarn start

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome 87 |

**Comment by afc163** [comment]
Fixed in #28819

Or you can upgrade TypeScript to 4.x.

**Comment by silverlovesl** [comment]
@afc163  Thanks, solved it by upgrading typescript to 4.x.

**Comment by deshanm** [comment]
In my case, I had to upgrade following versions to fix it.
```
"antd": "^4.7.2"  =>  "4.17",
"typescript": "~3.7.2"  =>   "3.8",
"@types/react": "^16.9.0"  => "^16.14.25",
```
