### ISSUE TITLE
In antd table ,when we give width at column css of table breaks, width of column in header is not same as width of column in body.

### ISSUE THREAD

**Issue by SrivathsaRaoI** [ant-design/ant-design#28852]
![Screenshot 2021-01-13 222222222](https://user-images.githubusercontent.com/23190460/104481167-74c9f480-55eb-11eb-9dec-b469974a49da.png)
![Screenshot 2021-01-13 1111111](https://user-images.githubusercontent.com/23190460/104481176-7693b800-55eb-11eb-9db3-c79bc1699322.png)
![Screenshot 2021-01-13 200828222](https://user-images.githubusercontent.com/23190460/104481178-77c4e500-55eb-11eb-9a5b-4579efcb55f1.png)

- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd4102-forked-vgyg6)

### Steps to reproduce
code can be seen in above code sandbox

### What is expected?
When we set width of column , the width in some header part of the column  is 1px less than width of the column in body. breaking CSS as seen the above three images.

### What is actually happening?
Css is breaking

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.5.0 |
| System | Windows 10 |
| Browser | google chrome |

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-fixed-header

<img width="1171" alt="图片" src="https://user-images.githubusercontent.com/507615/104537983-fce4e400-5655-11eb-9095-fd9cbfedb304.png">

**Comment by SrivathsaRaoI** [comment]
@afc163 , hi I left one column without width but still there was same error. Only when I removed " scroll = { y: 400 }" from the table the Css issue solved.When I put the scroll parameter the issue still exists. Please resolve this issue.

**Comment by afc163** [comment]
```diff
- x: "100%"
+ x: 'max-content'
```

**Comment by SrivathsaRaoI** [comment]
@afc163 ,I have put this 
scroll = { y: 400, scrollToFirstRowOnChange:true, x: 'max-content' };
Still the issue exists.

**Comment by afc163** [comment]
@SrivathsaRaoI Could you provide codesandbox with above changes.

**Comment by SrivathsaRaoI** [comment]
@afc163 ,when I put my code in codesandbox ,it is not happening, maybe I don't know how to use it. But the code I wrote is as follows.Please put this code on codesandbox and check.Please resolve this issue

import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Table, Tag, Space } from "antd";

const columns = [
  {
    title: "Name",
    dataIndex: "name",
    width: 50,
    render: (text) => <a>{text}</a>
  },
  {
    title: "Age",
    dataIndex: "age",
    width: 95
  },
  {
    title: "Address",
    dataIndex: "address",
    width: 120
  },
  {
    title: "Address1234567",
    dataIndex: "address1234567",
    width: 145
  },
  {
    title: "Tags",
    key: "tags",
    dataIndex: "tags",
    width: 200,
    render: (tags) => (
      <>
        {tags.map((tag) => {
          let color = tag.length > 5 ? "geekblue" : "green";
          if (tag === "loser") {
            color = "volcano";
          }
          return (
            <Tag color={color} key={tag}>
              {tag.toUpperCase()}
            </Tag>
          );
        })}
      </>
    )
  },
  {
    title: "Action",
    width: 130,
    render: (text, record) => (
      <Space size="middle">
        <a>Invite {record.name}</a>
        <a>Delete</a>
      </Space>
    )
  }
];

const data = [
  {
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
    address1234567: "i am testing whether it is working properly",
    tags: ["nice", "developer"]
  },
  {
    name: "Jim Green",
    age: 42,
    address: "London No. 1 Lake Park",
    tags: ["loser"],
    address1234567: "i am testing whether it is working properly"
  },
  {
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    tags: ["cool", "teacher"],
    address1234567: "i am testing whether it is working properly"
  }
];

ReactDOM.render(
  <Table bordered={true}  tableLayout="fixed"  size="large" scroll= {{ y: 400, scrollToFirstRowOnChange:true, x:"100%" }} 
  columns={columns} dataSource={data} />,
  document.getElementById("container")
);

**Comment by SrivathsaRaoI** [comment]
@afc163 ,please help to solve the issue.

**Comment by SrivathsaRaoI** [comment]
@afc163 ,following is the link for sandbox,please help to solve issue.please reply in english.
https://codesandbox.io/s/basic-usage-antd4102-forked-pquxz

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-usage-antd4102-forked-p0k9v?file=/index.js

**Comment by SrivathsaRaoI** [comment]
Hi @afc163 ,
I can see the issue still in your above codesandbox code. So what is the solution? how to solve the bug?

**Comment by afc163** [comment]
<img width="654" alt="图片" src="https://user-images.githubusercontent.com/507615/105142317-6a50b300-5b35-11eb-9038-cfc7299e7901.png">

I can't see problem in my codesandbox, anything I miss?

**Comment by SrivathsaRaoI** [comment]
@afc163 ,please tell me how you solved the issue?
You just changed width of some columns and changed scroll={{ y: 400, scrollToFirstRowOnChange: true, x: "100%" }} to scroll={{ y: 400, scrollToFirstRowOnChange: true, x: "max-content" }} and it works well. How come it solved the issue? Is there any criteria to solve the issue?
