### ISSUE TITLE
Collapse.Panel封装成组件后，panel内容消失不见。

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#28856]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhediemianban-antd4102-forked-639u8?file=/index.js:164-172)

### Steps to reproduce
见链接内容

### What is expected?
我希望能够灵活的封装自己想要的组件

### What is actually happening?
实际不能

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.14.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by ISBN9527** [comment]
求大神指点，挺急的。

**Comment by afc163** [comment]
目前还不支持，可以持续关注 https://github.com/ant-design/ant-design/issues/4853

**Comment by afc163** [comment]
https://github.com/react-component/collapse/issues/73#issuecomment-323626120 可以作为临时解决方案。
