### ISSUE TITLE
typescript使用antd Form组件问题

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#2885]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本： windows10
- 浏览器及其版本: crhome 54.0.2832.2 dev-m (64-bit)

#### 你做了什么？

使用typescript去写react，用到了antd的Form组件
经过 Form.create 包装了一个组件，在其他组件里面使用这个组件

#### 你期待的结果是：

没有提示错误

#### 实际上的结果：

如果组件属性定义的form是可选，Form.create()会提示错误；
如果组件属性定义的form是必须，Form.create()不会提示错误，但是使用这个组件的时候，会提示没有设置form属性

#### 可重现的在线演示

http://codepen.io/infeng/pen/qaWbpE?editors=0010

**Comment by benjycui** [comment]
console 无任何报错信息。

**Comment by infeng** [comment]
是typescript的语法检查会提示错误

**Comment by nick-ChenZe** [comment]
通过`typings install`安装的依旧存在这个问题，改有官方npm包里`index.d.ts`后通过。
