### ISSUE TITLE
select 元件在依賴 rc-virtual-list 3.2.5 時會發生滾動異常

### ISSUE THREAD

**Issue by kudorori** [ant-design/ant-design#28861]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-qiik3?file=/src/App.js)

### Steps to reproduce
1. Scroll To bottom

### What is expected?
Scroll 到底部正常

### What is actually happening?
Scroll 到最下面後, Scroll Bar會超出容器

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 7.0.1 |
| System | macos |
| Browser | chrome |

**Comment by Clago** [comment]
[ant-design-pro#7951](https://github.com/ant-design/ant-design-pro/issues/7951)
我在ant-design-pro下也出现了虚拟滚动问题，是同一个问题吗？

**Comment by nuintun** [comment]
https://github.com/react-component/virtual-list/issues/102
