### ISSUE TITLE
scrollToFirstError for Upload input

### ISSUE THREAD

**Issue by nanaker** [ant-design/ant-design#28869]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/scroll-to-the-first-error-with-upload-antd-00edf)

### Steps to reproduce
when i test with the upload item it doesn't scroll 
but when i hide it the scroll work 
event i'have added the id

### What is expected?
to scroll to the first error ( the upload input)

### What is actually happening?
it doesn't scroll

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.8.6 |
| System | Mac OS |
| Browser | Chrome |

**Comment by zgoby** [comment]
1

**Comment by hotanlam** [comment]
please fix this bug!

**Comment by forever-me** [comment]
希望可以修复它
否则,目前我只能这样做
  [https://stackblitz.com/edit/react-ha3uuj?file=index.js](url)

**Comment by forever-me** [comment]
希望可以修复它
我目前只能这样做
[https://stackblitz.com/edit/react-ha3uuj?file=index.js](https://stackblitz.com/edit/react-ha3uuj?file=index.js)

**Comment by shaoshenchen** [comment]
> 希望可以修复它 我目前只能这样做 https://stackblitz.com/edit/react-ha3uuj?file=index.js

你这也没起作用啊，第二个 upload 组件只能跳一半

**Comment by forever-me** [comment]
> > 希望可以修复它 我目前只能这样做 https://stackblitz.com/edit/react-ha3uuj?file=index.js
> 
> 你这也没起作用啊，第二个 upload 组件只能跳一半

我承认这个demo写的很粗糙,如果你打开检查看一下就会知道是span高度没撑起来

**Comment by qiphon** [comment]
scrollToFirstError={{
              behavior: 'smooth',
              block: 'center',
              inline: 'center',
            }}

**Comment by AdvMaple** [comment]
I'm having the same problem
CodeSandBox: [here](https://codesandbox.io/s/antd-reproduction-template-forked-994duf)

**Comment by sambhav2612** [comment]
any updates on this?

**Comment by merabtenei** [comment]
Why is this issue not getting any attention ?

**Comment by milanpoudel1** [comment]
Any updates on this problem please?

**Comment by Wxh16144** [comment]
It's time to fix it. I'll follow up.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/48211
