### ISSUE TITLE
Tree组件 filterTreeNode回调函数中返回ture并不回使该节点高亮显示

### ISSUE THREAD

**Issue by 123456wjw** [ant-design/ant-design#28864]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4102-forked-n7z3n?file=/index.js)

### Steps to reproduce
在tree组件上设置filterTreeNode，并在回调中返回true无效

### What is expected?
返回ture可以高点节点

### What is actually happening?
返回true不会高亮

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | react 16.8.6 |
| System | windows 64 |
| Browser | 谷歌 87.0.4280.88 |

**Comment by afc163** [comment]
Styles lost...

https://github.com/ant-design/ant-design/blob/58cc8d1038a945fc4130075235eae9a552d9788c/components/tree/style/index.less#L68-L73

**Comment by 123456wjw** [comment]
> Styles lost...
> 
> https://github.com/ant-design/ant-design/blob/58cc8d1038a945fc4130075235eae9a552d9788c/components/tree/style/index.less#L68-L73
> 
> https://github.com/ant-design/ant-design/blob/58cc8d1038a945fc4130075235eae9a552d9788c/components/tree-select/style/index.less#L23-L27

在node-modules目录下面吗?node-modules不会提交，antd会发布新版本吗？

**Comment by 123456wjw** [comment]
> Styles lost...
> 
> https://github.com/ant-design/ant-design/blob/58cc8d1038a945fc4130075235eae9a552d9788c/components/tree/style/index.less#L68-L73
> 
> https://github.com/ant-design/ant-design/blob/58cc8d1038a945fc4130075235eae9a552d9788c/components/tree-select/style/index.less#L23-L27

![image](https://user-images.githubusercontent.com/37201576/104574495-0c355300-5691-11eb-835e-c8313a0ec373.png)
