### ISSUE TITLE
Non compatibility of dynamic rowSpan with react-dom 17.0.1

### ISSUE THREAD

**Issue by Trovidan** [ant-design/ant-design#28867]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/grouped-data-5k491?file=/src/App.js)

### Steps to reproduce
When rowSpan is dynamically set inside column renderer the rowSpan of all elements is set as per most common rowSpan, The issue is only seen when react-dom@17.0.1 is used,
With react-dom@16.14.0 the renderer renders column as expected

### What is expected?
the column is supposed to have rows with different rowSpans

### What is actually happening?
the column's rows are showing the most common rowSpan in the column instead in my implementation atleast.

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | React 17.0.1 |
| System | Windows 10 Home, Build 19041.685 |
| Browser | Google Chrome Version 87.0.4280.141 |

---
Every thing works fine with react-dom@16.14.0

**Comment by afc163** [comment]
You can remove StrictMode for workaround: https://codesandbox.io/s/grouped-data-forked-uu3lq?file=/src/index.js

Trace #26136 for further fix.

**Comment by Trovidan** [comment]
Thanx for help @afc163, didn't tried that  out.
