### ISSUE TITLE
Collapse.Panel的extra填充Checkbox时，点击复选框（非文字）时会点透。Panel会叠起。

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#28876]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ewaijiedian-antd4102-forked-3wfkf)

### Steps to reproduce
点击复选框和文字情况不一。已经在代码设置  event.stopPropagation();

### What is expected?
希望点击复选框和文字情况一致。

### What is actually happening?
实际不理想

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.14.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by ISBN9527** [comment]
项目紧，请大佬指点。

**Comment by yoyo837** [comment]
自行阻止一下事件传播看看

**Comment by ISBN9527** [comment]
而且在手风琴模式下，也会有点问题。
譬如：

1. 第一行默认展开，点击第二行的checkbox为什么会触发第一行的叠起呢？

**Comment by ISBN9527** [comment]
@yoyo837 已经阻止了，没什么用

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/104677464-692e1900-5724-11eb-9bb7-116cac2f52ce.png)

**Comment by ISBN9527** [comment]
感谢大佬们，问题解决了
