### ISSUE TITLE
关于select功能需求

### ISSUE THREAD

**Issue by ShawDanon** [ant-design/ant-design#28879]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
主要是想解决一个选项支持带出多个值的问题和默认筛选好用的问题。

### What does the proposed API look like?
value支持对象值，默认筛选为children的文本且忽略大小写

**Comment by ShawDanon** [comment]
目前处理方式每次都把对象转成json字符串出去，回显也是转成json回来，一般情况value值和option的显示都是不一样的，默认value其实意义不大，每次都会去写个搜索规则，当然这些是收敛到了二次封装的组件里了

**Comment by yoyo837** [comment]
或者搞一个API叫`compare: Function => Boolean`？

**Comment by yoyo837** [comment]
和直接二次封装好像区别也不大，这比较偏僻具体业务。

**Comment by afc163** [comment]
`labelInValue`

**Comment by ShawDanon** [comment]
> `labelInValue`

这个只能拿到children节点的值，实际诉求可能是一个下拉框里面有很多值要传给后端，这些值不只是显示出来的，所以我封装了个select来解决这个，提这个需求是应为现在有几个项目都需要用同样的，我就考虑是自己弄个组件库还是说antd能不能底层支持这个功能。

**Comment by ShawDanon** [comment]
> 和直接二次封装好像区别也不大，这比较偏僻具体业务。

是基于使用情况考虑的，我想antd默认好用的背景下是否需要考虑这个场景~

**Comment by ShawDanon** [comment]
![image](https://user-images.githubusercontent.com/9554297/104695743-28e09200-5748-11eb-9aff-fb0341b05777.png)
顺便提下这个设计，在loading的时候还能去进行选择和操作，在联动的时候除了loading我还需要加个disable，就感觉很奇怪，我也封装过在外面套一层spin来覆盖select的组件
