### ISSUE TITLE
Select多选自动分词bug

### ISSUE THREAD

**Issue by ppxu** [ant-design/ant-design#28873]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6qbox)

### Steps to reproduce
设置 `tokenSeparators={['\n']}`，对于下面的内容
```
aaa
bbb
ccc
```

如果鼠标只拖到ccc后面复制进来是能分词的，如果鼠标拖到下面一行，也就是最后多一个换行符，复制进去就不能分词了

### What is expected?
正常分词

### What is actually happening?
未分词

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.14.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
确实。

**Comment by mumiao** [comment]
![image](https://user-images.githubusercontent.com/22880945/104997405-7f114600-5a64-11eb-8363-e1b3a3ff12e9.png)
@afc163 @ppxu 属于第一种，需要使用空格+换行来分词

**Comment by ppxu** [comment]
@mumiao `[' ', '\n']`可以解决上面的case，不过我这边的实际情况是每行内部可能也有空格，这个不能分割，只能根据换行来分
