### ISSUE TITLE
希望给drawer增加wrapperStyle属性

### ISSUE THREAD

**Issue by BooYeu** [ant-design/ant-design#28878]
### What problem does this feature solve?
移动端的适配问题，因为想实现移动端适配width，设置width:auto后希望再价格minWidth:40%,保证电脑端和移动端浏览没问题

### What does the proposed API look like?
类似bodyStyle,drawerStyle之类的，现在只能通过width属性设置wrapperStyle

**Comment by afc163** [comment]
Duplicate of #28683
