### ISSUE TITLE
[Select mode="tags"] Add the ability to use the Enter key as a tokenSeparator 

### ISSUE THREAD

**Issue by geoffrey** [ant-design/ant-design#28872]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will allow adding a tag to the Select input after pressing the Enter key

### What does the proposed API look like?
adding `tokenSeparators` support for  `&#13;` or `&#10;`

**Comment by chillyistkult** [comment]
It already works like that

[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

`tokenSeparators` is meant to parse the value as tags. For example if comma separated string is passed as a value.

**Comment by geoffrey** [comment]
Do you mind sending an example where we can add a tag to the list by pressing the enter key?

**Comment by gsavit** [comment]
A year later, in case you didn't figure this out and still have a use case... found this thread and discovered that adding newline (i.e. '\n') to your `tokenSeparators` should get you the behaviour you're looking for!
