### ISSUE TITLE
make some useful components in the documentation site available in ant design

### ISSUE THREAD

**Issue by tc-imba** [ant-design/ant-design#28887]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

There are several useful features in the documentation site:
+ In the "code-box" for the example code, there is a title inside the border, which can not be achieved simply with any component.
+ The table of contents on the right, which is useful when displaying stuff in markdown format.

### What does the proposed API look like?
For the title inside the border, maybe it's possible to add an boolean attribute to the "Card" component.

For the table of contents, I suggest a new navigation component.

**Comment by afc163** [comment]
1. Divder
2. Anchore
