### ISSUE TITLE
add param to dropdownRender prop for Select to close Select Menu

### ISSUE THREAD

**Issue by Sglavin85** [ant-design/ant-design#28889]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a dropdown component which utilized the dropdownRender prop to add a button at the bottom of the select menu. This button should close the menu and render a new form elsewhere on the page... I cannot close the menu when this button is clicked, even with a useRef using the blur method.

### What does the proposed API look like?
a second param on the dropdown render which can pass in access to the onBlur method on the select menu.

**Comment by afc163** [comment]
Try `visible` to control dropdown visibility.

**Comment by Sglavin85** [comment]
this is for the Select component not a dropdown component

**Comment by afc163** [comment]
There is `open` and `onOpenChange` for Select.
