### ISSUE TITLE
antd里许多组件生成的html代码里经常会有<span><div></div></span>这样的结构

### ISSUE THREAD

**Issue by broadliyn** [ant-design/ant-design#2888]
在Table等组件里经常可以看到这样的结构。
我的意思是，在SPA里，这样的内联元素嵌套快级元素是不是不符合语义或者规范呢？

**Comment by benjycui** [comment]
是不符合，可以把这些情况整理出来，有时间会改的。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by broadliyn** [comment]
感谢抽空回复。我这里先close了，等我整理下，发个新的issue上来

**Comment by afc163** [comment]
请自行关闭。这种没有关系的，有影响的内嵌，react 会提示。
