### ISSUE TITLE
Modal.method() functions, They won't callback again when return true in onOk function

### ISSUE THREAD

**Issue by haua** [ant-design/ant-design#28882]
- [*] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-gagarin-mxnn2?file=/src/App.js)

### Steps to reproduce
使用Modal.method()生成的弹窗，在onOk函数内return true，多次点击点击ok，只有第一次会回调。

When returns true in the onOk function in a Modal.method() . If you click OK button many times, only the first time you call back.

### What is expected?
Call back every time

### What is actually happening?
Only the first time you call back.

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 17.0 |
| System | mac os 10.14.4 |
| Browser | chrome 87.0.4280.141 |

**Comment by afc163** [comment]
https://codesandbox.io/s/dreamy-wing-qshnf

**Comment by haua** [comment]
就为了点击ok按钮不关闭弹窗要返回一个Promise，那还不如声明close函数省事。
