### ISSUE TITLE
CSP nonce is not applied even after creating a ConfigProvider

### ISSUE THREAD

**Issue by luis-carlos-campos** [ant-design/ant-design#28888]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/lccampos/pen/ExgGPBw](https://codepen.io/lccampos/pen/ExgGPBw)

### Steps to reproduce
1- Create ant.d icons.
1- Wrap icons with ConfigProvider with csp configuration.
3- Style tag is added to the DOM with no nonce.

### What is expected?
Style tag has a nonce value.

### What is actually happening?
nonce attribute is not displayed

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | react 16.x |
| System | MacOS Mojave |
| Browser | Chrome Version 85.0.4183.102 |

![Screen Shot 2021-01-15 at 11 47 03 AM](https://user-images.githubusercontent.com/13797951/104741468-0474bd80-5728-11eb-9a90-a5fac949adfb.png)

https://github.com/ant-design/ant-design/issues/28883 was closed, however the example had the ConfigProvider as described in https://ant.design/components/config-provider/#Content-Security-Policy.

Thanks in advance.

**Comment by zombieJ** [comment]
`@ant-design/icons` not read `antd` ConfigProvider props. Seems `@ant-design/icons` should also add a provider.

**Comment by zombieJ** [comment]
Update. These style in your snapshot is generate by css-loader which is not control by antd. Which mean CSP not work on this. You should config related loader instead.

**Comment by liangz2** [comment]
Hi @zombieJ , I am not sure it's a webpack loader that does the insert. From the debug console on Chrome, I find that the error is coming from `insert-css` package:
![image](https://user-images.githubusercontent.com/1062595/107709880-f5841b00-6c93-11eb-94f4-7150ef4fd66c.png)
and it is being called from the `@ant-design` package as part of the `util` function:
![image](https://user-images.githubusercontent.com/1062595/107710082-4dbb1d00-6c94-11eb-908a-82cc4af37191.png)

Could you look into it please?

**Comment by dannydtk** [comment]
@zombieJ @liangz2 is correct. `@ant-design/icons` doesn't use nonce from `antd`'s `<ConfigProvider />`. It injects some `<style>` tags as it is shown in the screenshots and it's not related to the `style-loader` or any other `webpack` loader (I've adjusted the `style-loader` config locally to add `nonce` but it doesn't affect custom injections made by `@ant-design/icons`).

This prevents configuring CSP header properly which is a security gap.

**Comment by craigmiller160** [comment]
Is there going to be any movement on fixing this? I'm currently experiencing this issue:

"antd": "^4.18.3",
"@ant-design/icons": "^4.7.0",
    "@ant-design/plots": "^1.0.7",

**Comment by rhu25** [comment]
i have same issue with 
"@ant-design/icons": "^4.7.0",
"antd": "^4.18.9",

```
<ConfigProvider csp={{ nonce: '12345' }}>
                  <Select ></Select>
</ConfigProvider>
```
select still add 
```
.anticon {
  display: inline-block;
  color: inherit;
  font-style: normal;
  line-height: 0;
  text-align: center;
  text-transform: none;
  vertical-align: -0.125em;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.anticon > * {
  line-height: 1;
}

.anticon svg {
  display: inline-block;
}

.anticon::before {
  display: none;
}

.anticon .anticon-icon {
  display: block;
}

.anticon[tabindex] {
  cursor: pointer;
}

.anticon-spin::before,
.anticon-spin {
  display: inline-block;
  -webkit-animation: loadingCircle 1s infinite linear;
  animation: loadingCircle 1s infinite linear;
}

@-webkit-keyframes loadingCircle {
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}

@keyframes loadingCircle {
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}```
in header
