### ISSUE TITLE
CSP is not being applied to inline style tags

### ISSUE THREAD

**Issue by luis-carlos-campos** [ant-design/ant-design#28883]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/lccampos/pen/ExgGPBw](https://codepen.io/lccampos/pen/ExgGPBw)

### Steps to reproduce
Inspect HTML generated

### What is expected?
<styles> tags are generated with nonce attribute

### What is actually happening?
nonce attribute is not displayed

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | react 16.x |
| System | MacOS Mojave |
| Browser | Chrome Version 85.0.4183.102 |

![Screen Shot 2021-01-15 at 11 47 03 AM](https://user-images.githubusercontent.com/13797951/104741468-0474bd80-5728-11eb-9a90-a5fac949adfb.png)

Am I doing anything wrong?

Thanks in advance.

**Comment by afc163** [comment]
https://ant.design/components/config-provider/#Content-Security-Policy

**Comment by luis-carlos-campos** [comment]
> https://ant.design/components/config-provider/#Content-Security-Policy

CSP was configured according to the link provided. Check above
