### ISSUE TITLE
为什么表格的onRowClick事件的event参数不传了？

### ISSUE THREAD

**Issue by lanxingshou** [ant-design/ant-design#2889]
#### 本地环境

V1.10.0版本吧表格的onRowClick事件去掉了，但是V1.6.4的时候可以

导致行点击的时候无法通过event.target.id判断是哪个标签点击的。

![image](https://cloud.githubusercontent.com/assets/12092274/18079199/ff5a150a-6ec1-11e6-9fe7-0dcf2699ae34.png)

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by lanxingshou** [comment]
![image](https://cloud.githubusercontent.com/assets/12092274/18080366/d9f974b2-6ec7-11e6-9001-d38a6ecd6de5.png)

为啥去掉这个event啊，头疼~~~

**Comment by lanxingshou** [comment]
![image](https://cloud.githubusercontent.com/assets/12092274/18082893/5c04b15a-6ed3-11e6-97a1-dd231b6fbe96.png)
绑定在元素的onclick上解决。

**Comment by afc163** [comment]
Reinstall antd

**Comment by chj-damon** [comment]
我需要在点击某一行数据时弹出一个对话框，对话框的位置要刚好在这一行数据的下面，现在onRowClick里面没有event参数，我怎么定位left 和top?

**Comment by yesmeck** [comment]
@chj-damon This issue has been fixed.
