### ISSUE TITLE
antd layout sider should have a bottom version 

### ISSUE THREAD

**Issue by mx2323** [ant-design/ant-design#28890]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i would like to use the antd.layout.sider functionality in my app - however, i would like it to slide up from the bottom instead of from the left or right. 

this is not the same as the antd drawer component. with the drawer component, it does not resize content when the drawer slides in.

i would like to have antd.layout.sider’s ability to resize content but be able to have a resizable footer instead of requiring the sider come in from the sides. 

### What does the proposed API look like?
i’m not sure. is it possible to create a sider that works from the bottom? 

for situations where users may want to enlarge or collapse a footer component - this would be really useful

**Comment by afc163** [comment]
I don't think `<Sider />` component should be placed at bottom of page, it would be very weired.
