### ISSUE TITLE
IE版本最低兼容到几？

### ISSUE THREAD

**Issue by CN-Sean** [ant-design/ant-design#289]
看这动效，起码也要IE10吧，IE9肯定不行吗，如果不考虑动效？

**Comment by zhujun24** [comment]
8

**Comment by afc163** [comment]
动效和其他 CSS3 的小广告进行不优雅的降级。

**Comment by GREENPEANS** [comment]
我想说我的IE9就不可以  正在尝试IE10版本

**Comment by afc163** [comment]
@GREENPEANS IE9 有问题的话可以提 issue。

**Comment by GREENPEANS** [comment]
这位大神，谢谢你的回复喲！



在 2017-08-31 14:08:40，"偏右" <notifications@github.com> 写道：


@GREENPEANS IE9 有问题的话可以提 issue。

**Comment by fantasy-wc** [comment]
IE10下报错：
报错信息为：
The above error occurred in the <DynamicComponent> component:
    in DynamicComponent (created by Context.Consumer)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by RouterWrapper)
    in Switch (created by RouterWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by RouterWrapper)
    in sfc (created by LocaleWrapper)
    in IntlProvider (created by LocaleWrapper)
    in LocaleProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by LocaleWrapper)
    in LocaleWrapper (created by RouterWrapper)
    in RouterWrapper
    in Provider (created by _DvaContainer)
    in _DvaContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. 
Unhandled promise rejectionundefined 
求教该如何解决
