### ISSUE TITLE
atool-build -w -o ./bundle 出的代码界面显示不出，控制台报错“Cannot read property 'apply' of undefined”

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design#2890]
原先好的代码，后来突然发现存在这样的问题
用 atool-build 第一次编译出的代码可以渲染界面，没有问题
因为加了“-w” 会识别到文件变化，重新build的文件，界面就渲染不出，控制台报common.js有这个错误
`“common.js:1` Uncaught TypeError: Cannot read property 'apply' of undefined”`

因为源文件已经比较大，查不出哪里出现这个问题

**Comment by afc163** [comment]
请提到 atool-build 的 issues。
