### ISSUE TITLE
Modal 弹框希望支持按住头部拖拽移动位置

### ISSUE THREAD

**Issue by zhuyuanmin** [ant-design/ant-design#28909]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
防止弹框位置挡住关键信息

### What does the proposed API look like?
enableDrag: (true | false)

**Comment by AlanCutFlim** [comment]
https://ant.design/components/modal-cn/#components-modal-demo-modal-render
