### ISSUE TITLE
如何在Summary中继承columns的render函数

### ISSUE THREAD

**Issue by alexchen1875** [ant-design/ant-design#28905]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决需要在汇总列中再处理一遍列的自定义render

### What does the proposed API look like?
与columns保持一致

**Comment by zombieJ** [comment]
`columns` 是你自己传入的，直接拿来用就行了。内部再转一遍交出来没有必要。

**Comment by alexchen1875** [comment]
@zombieJ 

我会在column的render函数中返回其它的组件,
调用render时得到的是这这样的数据,我应该如何渲染出来呢请问;


![image](https://user-images.githubusercontent.com/3668637/104902047-289afd80-59b9-11eb-8996-205a12059199.png)

**Comment by yoyo837** [comment]
渲染到哪里？dom? ReactDom.render

**Comment by alexchen1875** [comment]
> 渲染到哪里？dom? ReactDom.render

渲染到Table.Summary.Cell中 伪代码:

明白意思了,如下这样处理就好,只是需要汇总的地方都要处理一下,这样处理就好了伪代码,如果Summary.Cell默认支持的话就更简洁一点, 谢谢啦

````

const PaseSummaryCell = ({clm, data}) => {
    if (clm.render) {
        return clm.render(data[clm.dataIndex], data);
    }
    return <span>{data[clm.dataIndex]}</span>;
};

````



````
....
 <Table.Summary.Cell
              key={clm.dataIndex}
              align={clm.align}
  >
       <PaseSummaryCell column={column} data={data}/>
</Table.Summary.Cell>

....
```
