### ISSUE TITLE
Is that possible to expose Pagination selectComponentClass prop?

### ISSUE THREAD

**Issue by yuxuan** [ant-design/ant-design#28912]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To expose `selectComponentClass`, user can pass in custom select component. The prop name seems miss leading. Maybe `selectComponent` is good enough. 

### What does the proposed API look like?
<Pagination selectComponent={<MySelect />} />

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/32132
