### ISSUE TITLE
In Date Range Picker, If today selected in footer, time automatically sets to current time rather than 00:00:00 23:59:59

### ISSUE THREAD

**Issue by avconstruct** [ant-design/ant-design#28913]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Steps to reproduce
* On Date Range Picker, If today selected in footer, the date sets to today but the time sticks to current time rather than 00:00:00 23:59:59, which is wrong..
* And not allowing to select time too.

### What is expected?
* On Today selected on Date range picker, should reset to 00:00:00 23:59:59.

### What is actually happening?
* Currently Sets to current time.

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.14.0 |
| System | Ubuntu 20.1 |
| Browser | Edge Dev |

---
Yesterday, I raised the issue, with 3x version, but rejected due to unsupported version, but now i updated the framework to current version, but still facing the same problem.

**Comment by afc163** [comment]
```jsx
<DatePicker
  onChange={(value) => {
    console.log(value.startOfDay()); // click today
  }}
/>
```

**Comment by afc163** [comment]
```diff
- .startOfDay()
+ .startOf('day')
```

**Comment by avconstruct** [comment]
well, thanks @afc163! we got the solution... but for Range Picker.. to be more precise... it would be..

```

onChange={(evt) => {
    evt[0] = evt[0].startOf('day')
    evt[1] = evt[1].startOf('day')
  }
}

```
