### ISSUE TITLE
Cannot open Select component by clicking on suffixIcon

### ISSUE THREAD

**Issue by LaZmigouille** [ant-design/ant-design#28914]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-select-with-suffix-icon-gym4v)

### Steps to reproduce
Add a suffixIcon prop to antdesign Select component

### What is expected?
To show select options by clicking the component and dropdown icon

### What is actually happening?
Nothing happens when we click on the custom select icon

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | React@latest |
| System | Mac OS |
| Browser | Chrome@latest |

**Comment by afc163** [comment]
It is a conflicted behavior with #23263
