### ISSUE TITLE
请问一下使用了antd的项目怎么做单元测试呢?

### ISSUE THREAD

**Issue by laolu87** [ant-design/ant-design#2891]
比如一个登陆组件,里面有antd的Form组件,当测试运行到`const FormItem = Form.Item`这一行时就会报语法错误.
```
> mocha --compilers js:babel-core/register --require ./test/setup.js -wG


SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] 
```
我测试使用的插件是:mocha+chai+enzyme+jsdom+react-addons-test-utils+babel-core这几个插件搭配使用.第一次写测试,求大神指点下迷津.

**Comment by afc163** [comment]
非 antd 问题请自行探索或去专业论坛提问，请谅解。

**Comment by laolu87** [comment]
@afc163 哦哦,好的,谢谢了!

**Comment by oeddyo** [comment]
我也遇到同样的问题，用了babel-plugin-antd之后出现


/Users/exie/workspace/wise-web/node_modules/antd/lib/style/index.css:6
html {
     ^

**Comment by oeddyo** [comment]
Can we re-open this please?

**Comment by oeddyo** [comment]
Never mind, change your mocha test command to: 


"test": "mocha --compilers js:babel-register --recursive --require ignore-styles"

solves the problem

**Comment by oeddyo** [comment]
see: http://stackoverflow.com/questions/32236443/mocha-testing-failed-due-to-css-in-webpack
