### ISSUE TITLE
Image 添加去掉"预览"字样的功能

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design#28910]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在小图上,"预览"字样会被挤掉一部分,

### What does the proposed API look like?
removePreviewText

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/blob/9af8226e2153783d9ad887d44804482f51fc28c8/components/locale/zh_CN.tsx#L129

**Comment by scyx** [comment]
怎么改还是没说啊。。

**Comment by Litao21** [comment]
怎么修改预览文字啊

**Comment by m430** [comment]
+1 为什么关掉？

**Comment by brucelwayne** [comment]
+1

**Comment by hechenting** [comment]
修改Image的preview属性里的mask，mask可以返回个ReactNode，在mask里重新定义你想要的内容，比如不要文字，那就只返回个眼睛icon即可

**Comment by messi0087** [comment]
> 修改Image的preview属性里的mask，mask可以返回个ReactNode，在mask里重新定义你想要的内容，比如不要文字，那就只返回个眼睛icon即可

可以的兄弟，你真棒

**Comment by afc163** [comment]
通过 `locale` 来去掉 Ant Design `Image` 组件的“预览”字样，可以通过配置全局的国际化设置来实现。具体方法如下：

1. **设置全局 `locale`**: 你可以通过 `ConfigProvider` 组件来全局配置 `locale`。在 `locale` 配置中，将 `Image` 组件的 `preview` 属性设置为空字符串或自定义文字来替换“预览”字样。

```jsx
import React from 'react';
import { ConfigProvider, Image } from 'antd';
import zhCN from 'antd/es/locale/zh_CN'; // 引入中文 locale

const customLocale = {
  ...zhCN,
  Image: {
    preview: '',  // 设置为空字符串，去掉“预览”字样
  },
};

const Example = () => (
  <ConfigProvider locale={customLocale}>
    <Image
      src="https://example.com/your-image.jpg"
    />
  </ConfigProvider>
);

export default Example;
```

2. **说明**:
   - 在这个例子中，我们通过扩展 `zhCN`（或你正在使用的其他 `locale`），将 `Image` 组件的 `preview` 设置为 `''`（空字符串）。这样，图片预览功能依然存在，但“预览”字样将被移除。
   - 如果你想显示其他文字，也可以将 `preview` 设置为你需要的字符串。

**Comment by puxiaoshuai** [comment]
<Image
    ....
     preview={{mask: <span style={{ color: '#fff' }}>预览</span> }}
/>
