### ISSUE TITLE
设置dropdownMatchSelectWidth={false}，当item文本较长，会超出视图窗口

### ISSUE THREAD

**Issue by ZaneJie** [ant-design/ant-design#28926]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daisousuokuang-antd4103-forked-suzpl?file=/index.js)

### Steps to reproduce
Select组件，Option标签的展示内容设置超长

### What is expected?
使用dropdownMatchSelectWidth={false}，dropdown的宽度，最大到视图窗口边界处，不能超出视图窗口

### What is actually happening?
dropdown的宽度超出了视图窗口，超出视窗的内容不能查看

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.14.0 |
| System | windows 10 |
| Browser | Google Chrome 版本 87.0.4280.141（正式版本）64 |

**Comment by afc163** [comment]
这是预期的，相当于你设定了一个卡片内容过宽，自然会超出屏幕，需要横向滚动才能阅读所有内容。

**Comment by ZaneJie** [comment]
> 这是预期的，相当于你设定了一个卡片内容过宽，自然会超出屏幕，需要横向滚动才能阅读所有内容。

让页面横向滚动，交互不现实。本身是dropdown在根据option内文本长度撑开时，没有做宽度限制，所以会出现超出屏幕；为什么不能适应宽度，"..."展示呢。
dropdownMatchSelectWidth={300}设置一个定宽，倒是会出现超长后，"..."展示。

**Comment by afc163** [comment]
你可以试试 https://codesandbox.io/s/daisousuokuang-antd4103-forked-ftwzw

**Comment by ZaneJie** [comment]
> 你可以试试 https://codesandbox.io/s/daisousuokuang-antd4103-forked-ftwzw

也是一种可行的方法，但如果select组件不是单行展示或者页面响应式布局，设置maxWidth的方法就不太适用了。

不知道ant-design团队，会不会考虑优化dropdown组件---自适应时撑开的宽度问题。

**Comment by afc163** [comment]
很难自适应，dropdown 的位置是不确定的。

**Comment by ZaneJie** [comment]
> 很难自适应，dropdown 的位置是不确定的。

我看TreeSelect组件，dropdownMatchSelectWidth={false}，当超长时会换行展示，https://codesandbox.io/s/daizishutishidewenbenyu-antd4103-forked-invjq?file=/index.js:295-302。
这个2个组件，在此处的交互，怎么没有保持统一呢？
