### ISSUE TITLE
Upload的multiple属性开启，onChange回调返回的 file 应该是数组

### ISSUE THREAD

**Issue by thewei** [ant-design/ant-design#2892]
#### 本地环境

Mac

- antd 版本: 1.10.0
- 操作系统及其版本：Mac
- 浏览器及其版本: Chrome 52

#### 你做了什么？

开启 Upload的multiple属性，多文件上传

#### 你期待的结果是：

应该如文档所说，onChange回调返回的 file 应该是数组

#### 实际上的结果：

不是一个数组

**Comment by ddcat1115** [comment]
抱歉，这里是文档未更新，1.9.0开始 file 只会是一个文件维度(Object)，多选模式下会多次调用

**Comment by thewei** [comment]
@ddcat1115 有没有途径获取当前一次多选的文件列表

**Comment by afc163** [comment]
还有一个 fileList `onChange({ file, fileList })`。

**Comment by thewei** [comment]
fileList 是所有上传列表，如果上传，删除重复几次，很难区别是当次上传的文件列表 @afc163
