### ISSUE TITLE
[4.x 表格]columns只要有个字段添加fixed, 其他字段的ellipsis就会失效.

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#28927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-darkness-1b927?file=/index.js)

### Steps to reproduce
去除'序号'字段的fixed, ellipsis正常运行. 
加上fixed, 其他字段的ellipsis失效.

### What is expected?
不管是否有fixed, ellipsis都能正常运行

### What is actually happening?
有fixed, 其他字段的ellipsis失效

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome 87 |

---
这个原因也限制了拖拽列宽的宽度大小. （打开例子的components, 有ellipsis的列宽调整不了.）

**Comment by crawler-django** [comment]
不换行还是生效了的, 但是不会出现...

**Comment by edc-hui** [comment]
antd升级到4.10.3之后，拖拽改变列宽很卡，你有没有这种感觉

**Comment by crawler-django** [comment]
是比以前卡一些. @afifd/next 的拖拽列宽也卡.

金蝶云星空的拖拽列宽就流畅很多.

**Comment by afc163** [comment]
`scroll={{ x: 'max-content' }}` 表示横向空间根据内容尽可能延长，和 ellipsis 是冲突的，建议使用省略的场景都用定宽或百分比宽度。

https://codesandbox.io/s/practical-hugle-b1wlr?file=/index.js

**Comment by powerfulyang** [comment]
> `scroll={{ x: 'max-content' }}` 表示横向空间根据内容尽可能延长，和 ellipsis 是冲突的，建议使用省略的场景都用定宽或百分比宽度。
> 
> https://codesandbox.io/s/practical-hugle-b1wlr?file=/index.js

虽然 table scroll { x: 'max-content' } 但是 我给 column 设置了 width 和 ellipsis 啊，这个时候我希望能有 css ellipsis 的效果，而不是完全无效。

**Comment by JackDan9** [comment]
我目前也遇到了，如果是给它了固定宽度width, 再给它ellipsis就存在几种情况需要去自定义了，目前如果不支持的话。

**Comment by amsterdam-littlehill** [comment]
可以尝试使用 render 函数来自定义表格单元格的渲染方式，以便按照固定宽度渲染
```
{
    title: '项目名称',
    align: 'center',
    dataIndex: 'ProjectName',
    ellipsis: true,
    width: 200,
    fixed: 'left',
    render: (text) => <div style={{ width: '200px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{text}</div>,
  }
```

**Comment by amsterdam-littlehill** [comment]
> `scroll={{ x: 'max-content' }}` 表示横向空间根据内容尽可能延长，和 ellipsis 是冲突的，建议使用省略的场景都用定宽或百分比宽度。
> 
> https://codesandbox.io/s/practical-hugle-b1wlr?file=/index.js

如果将Date这一列，也设置为fixed，该列宽度也是失效
[https://codesandbox.io/s/hopeful-morning-mdprpj?file=/index.js:2609-2617](https://codesandbox.io/s/hopeful-morning-mdprpj?file=/index.js:2609-2617)
