### ISSUE TITLE
ie9下 Table组件报错，提示“无法获取未定义或 null 引用的属性columns”

### ISSUE THREAD

**Issue by linqiangsheng** [ant-design/ant-design#2893]
#### Win10

- antd 版本: 1.0.0-beta.3
- 操作系统及其版本：win10
- 浏览器及其版本: ie9

#### 你做了什么？

使用Table组件，声明columns和dataSource两个属性，ie9下打开提示“无法获取未定义或null引用的属性columns”。

#### 你期待的结果是：

ie9下正常显示

#### 实际上的结果：

显示异常 “无法获取未定义或null引用的属性columns”

#### 可重现的在线演示

any stuff

**Comment by afc163** [comment]
为什么要用 1.0.0-beta.3 这么奇怪的版本。
