### ISSUE TITLE
form label 里使用 switch，点击label其他内容会触发Switch状态的改变

### ISSUE THREAD

**Issue by TreeNewBeeing** [ant-design/ant-design#28935]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-elion-slhj4?file=/src/App.js)

### Steps to reproduce
点击【fsfffs】可以看到switch的状态改变了

### What is expected?
点击【fsfffs】不会改变switch的状态

### What is actually happening?
点击【fsfffs】可以看到switch的状态改变了

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.0 |
| System | MacOS |
| Browser | Chrome |

---
感谢～～～

**Comment by yoyo837** [comment]
因为label 绑了id，for-id那种
