### ISSUE TITLE
problems with selecting filtered dataSource

### ISSUE THREAD

**Issue by bibblebabl** [ant-design/ant-design#28930]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blazing-sound-9w70o?file=/src/App.tsx)

### Steps to reproduce
Filter table and select at least one row. Select rows are not correct.

### What is expected?
Expect to filter table but do not lose selected rows data after searching/filtering. Also on selecting all rows become selected on filtered dataSource

### What is actually happening?
All rows become selected after filtering. Selecting doesn't work on filtered data

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.13.1 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/brave-ives-z3n64?file=/src/App.tsx:2048-2081

```diff
      <Table
        rowSelection={{
          selectedRowKeys,
          onChange: onSelectChange,
          preserveSelectedRowKeys: true
        }}
        dataSource={dataSource}
        columns={tableColumns}
        scroll={{ y: 600 }}
        pagination={false}
+       rowKey={item => item.id}
      />
```

**Comment by bibblebabl** [comment]
> https://codesandbox.io/s/brave-ives-z3n64?file=/src/App.tsx:2048-2081
> 
> ```diff
>       <Table
>         rowSelection={{
>           selectedRowKeys,
>           onChange: onSelectChange,
>           preserveSelectedRowKeys: true
>         }}
>         dataSource={dataSource}
>         columns={tableColumns}
>         scroll={{ y: 600 }}
>         pagination={false}
> +       rowKey={item => item.id}
>       />
> ```

Thanks. It wasn't obvious. Can you please help me: is there any way to hide checkbox in header to select all elements?

**Comment by AlanCutFlim** [comment]
> > https://codesandbox.io/s/brave-ives-z3n64?file=/src/App.tsx:2048-2081
> > ```diff
> >       <Table
> >         rowSelection={{
> >           selectedRowKeys,
> >           onChange: onSelectChange,
> >           preserveSelectedRowKeys: true
> >         }}
> >         dataSource={dataSource}
> >         columns={tableColumns}
> >         scroll={{ y: 600 }}
> >         pagination={false}
> > +       rowKey={item => item.id}
> >       />
> > ```
> 
> Thanks. It wasn't obvious. Can you please help me: is there any way to hide checkbox in header for selecting all elements?

```css
.ant-table-thead .ant-table-selection {
  display: none;
}
```
