### ISSUE TITLE
Form Preserve not working

### ISSUE THREAD

**Issue by jeggy** [ant-design/ant-design#28938]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1p1b2?file=/index.js)

### Steps to reproduce
Use Form.Item alongside something like {showItem && <Form.Item name={....

### What is expected?
Not to lose the value within form values

### What is actually happening?
All values that are not displayed within Form.Item are being removed

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.1 |
| System | Ubuntu |
| Browser | Chrome |

---
I created a minimal reproduction, and it shows the issue perfectly

**Comment by zombieJ** [comment]
```
--- form.getFieldsValue()
+++ form.getFieldsValue(true)
```

**Comment by BlameFelix** [comment]
form.getFieldsValue(true) is working. But in the values variable of the submit method still only the rendered form values appear.

```
const handleSubmit = (values) => {
  // values only includes rendered form.item values
}
```

**Comment by GeorgeFlorian** [comment]
> ```diff
> form.getFieldsValue
> ```

How does this even work ? Can we get a working example ?
