### ISSUE TITLE
notifaction 没有拿到 provide 里面的 prefix，用的是 default

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#28932]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/775d1800bb6e1f101b8d0fc02eb144b9bf0de2be/components/notification/index.tsx#L119](https://github.com/ant-design/ant-design/blob/775d1800bb6e1f101b8d0fc02eb144b9bf0de2be/components/notification/index.tsx#L119)

### Steps to reproduce
修改 ant 前缀，就可以发现

### What is expected?
可以拿到 ant，hook 语法的通知是 ok 的

### What is actually happening?
没有

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.8 |
| System | macOS Mojave 10.14.6 |
| Browser | 83.0.4103.116 |

**Comment by yoyo837** [comment]
方法调起的不支持，目前就是如此

**Comment by tolerance-go** [comment]
那 prefix 的全局修改是否需要支持一个全局方法

**Comment by afc163** [comment]
https://ant.design/components/notification-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-notification-%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-%E7%9A%84-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F

**Comment by afc163** [comment]
> 那 prefix 的全局修改是否需要支持一个全局方法

https://github.com/ant-design/ant-design/pull/24295

**Comment by ubheamar** [comment]
Hello, I am still facing the same issue. I am using the root prefix "web" in the config context still its generating with ant prefix.

Sandbox URL for code:

https://codesandbox.io/embed/notification-with-icon-antd4155-forked-4nuxr?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/10156281/118644444-6f7bf100-b7fb-11eb-8831-05f533f8b8da.png)

**Comment by ubheamar** [comment]
sorry, it's there in documents we just need add this.


```
ConfigProvider.config({
    prefixCls: rootPrefix,
});
```
