### ISSUE TITLE
是否自动展开父节点：autoExpandParent属性不能生效

### ISSUE THREAD

**Issue by Claira-tech** [ant-design/ant-design#28933]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/cnLGMing/pen/WNrBVww](https://codepen.io/cnLGMing/pen/WNrBVww)

### Steps to reproduce
先收起父级，然后使用代码将子级选中，父级是否自动展开

### What is expected?
先收起父级，然后使用代码将子级选中，父级可以自动展开

### What is actually happening?
先收起父级，然后使用代码将子级选中，父级不可以自动展开

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.9.23 |
| System | Window7 |
| Browser | Google Chrome 版本 75.0.3770.54（正式版本） （64 位） |

**Comment by zombieJ** [comment]
`autoExpandParent` 和 `selectedKeys` 没有关系，它是和 `expandedKeys` 相关的。
