### ISSUE TITLE
Spin组件wrapperClassName属性在没有children的时候无效

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#28931]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rongqi-antd4103-forked-w8sju?file=/index.js:230-246)

### Steps to reproduce
打开重现链接，有children的Spin外层增加了对应的class, 无children的Spin没有对应的class

### What is expected?
不管有无children，都增加wrapperClassName中的class

### What is actually happening?
没有children时，wrapperClassName无效

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome  87.0.4280.141 |

---
className的渲染也有点奇怪，也是一个有一个没有，不太确定算不算bug

**Comment by afc163** [comment]
`wrapperClassName` 的意义是当 Spin 用作为一个 wrapper 时的 `className`。
