### ISSUE TITLE
Table column fixed:left 且 shouldCellUpdate不渲染时，和左侧selections列不能正常固定

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#28941]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuanzehecaozuo-antd4103-forked-v485y?file=/index.js)

### Steps to reproduce
打开重现链接，在表格中向右滚动

### What is expected?
selections列 和 第一列正常固定

### What is actually happening?
第一列跑到了 selections列 位置

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome  87.0.4280.141 |

---
shouldCellUpdate 感觉不应该会影响到固定列

**Comment by zombieJ** [comment]
close since not an issue in v5 anymore: https://codesandbox.io/s/xuan-ze-he-cao-zuo-antd-4-10-3-forked-fg6xj2?file=/index.js
