### ISSUE TITLE
Popconfirm 里有Table和任意一个其他元素的时候，Table的全选和取消全选被劫持

### ISSUE THREAD

**Issue by visaWang** [ant-design/ant-design#28948]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kexuanze-antd4103-forked-qhbqw?file=/index.js)

### Steps to reproduce
列头点击全选，再取消全选事件被劫持

### What is expected?
table事件不被劫持

### What is actually happening?
table事件被劫持

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
为啥 Popconfirm 里面嵌 Table 这么奇怪？

**Comment by afc163** [comment]
Closing for no response.
