### ISSUE TITLE
Input.TextArea组件，当输入的字符长度等于maxLength，继续输入（中文输入法）时，会出现英文替换字符后几位

### ISSUE THREAD

**Issue by ZaneJie** [ant-design/ant-design#28940]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daizishutishidewenbenyu-antd4103-forked-invjq?file=/index.js:295-302)

### Steps to reproduce
1.maxLength={20}  defaultValue="11111111112222222222"，文本长度为20；
2.Input.TextArea获取焦点进行输入，切换到拼音输入法，反复点击英文，会发现“22”被替换成了英文

### What is expected?
value文本长度等于maxLength时，之后无论怎么输入，都不应该修改value值，应保持“11111111112222222222”，而不是类似“111111111122222222ad”等替换。

### What is actually happening?
value文本长度等于maxLength时，之后输入中文，“11111111112222222222”会被替换成“111111111122222222ad”之类。

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.14.0 |
| System | windows 10 |
| Browser | Google Chrome 版本 87.0.4280.141（正式版本）64 |

**Comment by ZaneJie** [comment]
[demo.zip](https://github.com/ant-design/ant-design/files/5839919/demo.zip)
### 此处是录屏复现的demo！！！

**Comment by HomyeeKing** [comment]
can not reproduce on Mac @afc163  cc 👀

**Comment by HomyeeKing** [comment]
@ZaneJie  have you  tried it on native element `textarea`? I guess it will work same

**Comment by ZaneJie** [comment]
Fix/maxlength #28734 是已经发布到最新antd了吗，与我遇到的问题有相似处。
我现在访问的最新版的antd，请问有什么解决方案吗？

**Comment by HomyeeKing** [comment]
@ZaneJie  试试[这个](https://codesandbox.io/s/fix-show-9o82k?file=/index.js)，下面的两个是原生的组件，上面的是经过fix的ant组件

在ant的上面用你的步骤复现一下，你会看到ant的组件的值没有变化  原生的上会复现你出现的问题

**Comment by zombieJ** [comment]
![Kapture 2021-01-20 at 14 19 49](https://user-images.githubusercontent.com/5378891/105135213-9dda1000-5b2a-11eb-8c7e-c3908ff6f62c.gif)

**Comment by ZaneJie** [comment]
> @ZaneJie 试试[这个](https://codesandbox.io/s/fix-show-9o82k?file=/index.js)，下面的两个是原生的组件，上面的是经过fix的ant组件
> 
> 在ant的上面用你的步骤复现一下，你会看到ant的组件的值没有变化 原生的上会复现你出现的问题

**Comment by ZaneJie** [comment]
不小心把你的留言删除了  @HomyeeKing 
我看了你的demo，我发现原生和ant的组件，onChange时打印e.target.value都会有点不对，但简单情况下，在光标离开时都会重新根据maxLength截取有效值。

但我的问题比较特殊，你可以在ant的组件下试试，保持中文输入法，然后一顿连续按键盘 (字母键)，会发现value被替换了。

**Comment by zombieJ** [comment]
留一个 open issue 好让 #28734 ref 到。

**Comment by Luoziqiong** [comment]
我也发现了这个问题，到最后一个字，输中文只能输入一个首字母然后找，交互体验上不太友好，希望可以尽快修复一下

**Comment by wingsico** [comment]
这个在修复中吗？或者说有没有临时的 hack 方案
