### ISSUE TITLE
为什么select多选组件  只要加上value  多选就不行了

### ISSUE THREAD

**Issue by wqzwh** [ant-design/ant-design#2894]
import { Select } from 'antd';
const Option = Select.Option;

let children = [];
for (let i = 10; i < 36; i++) {
  children.push(<Option key={i.toString(36) + i}>{i.toString(36) + i}</Option>);
}

function handleChange(value) {
  console.log(`selected ${value}`);
}

ReactDOM.render(
  <Select
    multiple
    labelInValue
    style={{ width: '100%' }}
    placeholder="Please select"
    value={[]}
   defaultValue={[]}
    onChange={handleChange}
  >
    {children}
  </Select>
, mountNode);

官方例子，只要加上value这个参数就不能多选了，这是什么原因

**Comment by yesmeck** [comment]
加上 value 说明这个组件是受控组件，你要自己去控制 value  的变化，参考 https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by wqzwh** [comment]
谢谢，我把handleChange事件里面的内容写错了，现在好了
