### ISSUE TITLE
antd  版本 4.10.3 中依赖rc-picker 报错

### ISSUE THREAD

**Issue by YangJ0605** [ant-design/ant-design#28947]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/YangJ0605/test-antd.git](https://github.com/YangJ0605/test-antd.git)

### Steps to reproduce
- git clone https://github.com/YangJ0605/test-antd.git
- yarn 
- yarn start

### What is expected?
正常启动项目

### What is actually happening?
实际报错如下:

```
TypeScript error in D:/project/test/test-antd@4.10.3/node_modules/@ant-design/icons/lib/components/AntdIcon.d.ts(2,13):
'=' expected.  TS1005

    1 | import * as React from 'react';
  > 2 | import type { IconDefinition } from '@ant-design/icons-svg/lib/types';
      |             ^
    3 | import type { IconBaseProps } from './Icon';
    4 | import { getTwoToneColor, TwoToneColor, setTwoToneColor } from './twoTonePrimaryColor';
    5 | export interface AntdIconProps extends IconBaseProps {
```

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.14 |
| System | win 10 |
| Browser | Microsoft Edge 版本 87.0.664.75 (官方内部版本) (64 位) |

---
现在已经将antd的版本降为4.8.6,，可以正常启动

**Comment by afc163** [comment]
TypeScript 版本升级到 3.9 以上。
