### ISSUE TITLE
I have problem with Form.List nested

### ISSUE THREAD

**Issue by scripzero** [ant-design/ant-design#28954]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-t2k4x?file=/index.js)

### Steps to reproduce
Click add medicine then click 'add melt' then add the other medicine then add melt of the new one after that delete the first one (click red button at front of the row)

### What is expected?
delete only 1 row without delete other melt rows

### What is actually happening?
after delete the first all melt rows from the other row also deleted

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
```diff
--- <Form.List name={[field.key, "melts"]}>
+++ <Form.List name={[field.name, "melts"]}>
```
