### ISSUE TITLE
how to built css

### ISSUE THREAD

**Issue by dunhuang** [ant-design/ant-design#2895]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：osx
- 浏览器及其版本: chrome

#### 你做了什么？

因某些原因，项目只能引入prebuild版本的css和js文件，如何自己进行build？
无论是git版本还是npm包，npm run dist都只能对js进行build，dist下css是没有的。

#### 你期待的结果是：

可以在dist目录下生成css文件（或less文件）就如同npm包里dist目录里已有的prebuild文件一样

**Comment by benjycui** [comment]
不懂你的意思，npm 包内有未压缩的 `dist/antd.css`

**Comment by dunhuang** [comment]
@benjycui css我要做本地化修改，需要编译，不用npm包里的那个，并没有方法去编译。

**Comment by benjycui** [comment]
不要修改，直接覆盖样式。

**Comment by afc163** [comment]
Try 1.x-stable 分支。

@benjycui master 分支确实编译不出 css 文件，要修复下。

**Comment by benjycui** [comment]
fixed in https://github.com/ant-design/ant-design/commit/78af105d971eee273e1375b90fae56b9d3d11cb3
