### ISSUE TITLE
lerna 项目使用 ConfigProvider 失效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#28951]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/crazyair/antd-config-lerna](https://github.com/crazyair/antd-config-lerna)

### Steps to reproduce
git clone https://github.com/crazyair/antd-config-lerna
yarn
yarn start

### What is expected?
中文显示

### What is actually happening?
英文显示

![image](https://user-images.githubusercontent.com/7971419/105186389-a0f5f000-5b6c-11eb-81ba-0578ee832c57.png)

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.x |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
在不开启 workspace 情况下，antd-demo 的 react 跟 dumi 的 react 不是一个的原因吗？

**Comment by afc163** [comment]
我实测没有问题，请移除 yarn.lock 后重试。

<img width="339" alt="图片" src="https://user-images.githubusercontent.com/507615/105810586-2dc60100-5fe6-11eb-8f27-8632074fe4ef.png">

**Comment by crazyair** [comment]
问题应该是2个 node_modules react 的 事情，我把 workspace 打开，立马好了，关上立马不行的。

**Comment by webel** [comment]
I think I have the same problem; antd components imported from a lerna library don't pick up the ConfigProvider settings in the main project. I've checked that react resolves to the main projects react, and I've removed yarn.lock, tips on something else to try?

**Comment by mybedhome** [comment]
> I think I have the same problem; antd components imported from a lerna library don't pick up the ConfigProvider settings in the main project. I've checked that react resolves to the main projects react, and I've removed yarn.lock, tips on something else to try?
```javascript
resolve: {
  alias: {
     antd: path.resolve(__dirname, "node_modules/antd")
  }
}
```

**Comment by webel** [comment]
@mybedhome I do that too!

**Comment by mybedhome** [comment]
> @mybedhome I do that too!
Has your problem been solved?

**Comment by webel** [comment]
Hi again, apologies for the long time to reply, my issue has still not been solved. Atm I am adding locale to each and every component.
We have a CRA setup, with craco config to add some things to webpack:
```
module.exports = function({ env }) {
	return {
		webpack: {
			alias: {
				'styled-components': path.resolve(
					__dirname,
					'./node_modules/styled-components'
				),
				react: path.resolve(__dirname, './node_modules/react'),
				'react-dom': path.resolve(
					__dirname,
					'./node_modules/react-dom'
				),
				antd: path.resolve(__dirname, './node_modules/antd'),
			},
		},
		plugins: [
			{
				plugin: CracoAntDesignPlugin,
				options: {
					customizeTheme: antd_overrides,
				},
			},
		],
	};
};
```

```
// index.js
// imports for providers
import { ConfigProvider } from 'antd';
import svSE from 'antd/lib/locale/sv_SE';

const render = () => {
	ReactDOM.render(
		<ApolloProvider client={client}>
			<Provider store={store}>
				<ConfigProvider locale={svSE}>
					<ThemeProvider theme={theme}>
						<AppContext.Provider value={fileServiceContextValue}>
							<App />
						</AppContext.Provider>
					</ThemeProvider>
				</ConfigProvider>
			</Provider>
		</ApolloProvider>,
		document.getElementById('root')
	);
};

```
I'm not sure how to provide reproducible as our library isn't on an open npm.
