### ISSUE TITLE
iOS | Datepicker inside Modal page refreshes

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#28952]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-kepler-206vn)

### Steps to reproduce
1. Click on Open Modal button
2. Click on Date Picker within the modal
3. With calendar open, click inside the modal e.g. click at text "Some contents..."
4. Page crashes and refreshes.

### What is expected?
Calendar should close

### What is actually happening?
1. With calendar open, click inside the modal e.g. click at text "Some contents..."
2. Page crashes and refreshes.

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | iOS |
| Browser | Safari, Chrome |

---
At this point, we cannot upgrade to V4.0.0. Please provide us a fix on v3.x.x.

**Comment by mendoncanorma** [comment]
@afc163 , 

This is a blocker for our project. Kindly look into this ticket.
Please let me know if you need any more inputs.

Regards
Norma

**Comment by mendoncanorma** [comment]
@afc163 ,
I understand that the version (3.x) is off the maintenance period, we are in a phase of project where we can't upgrade to 4.x. Hence I request you to please look into this issue.

**Comment by xrkffgg** [comment]
When I test react 16.x, the page not crash. When set react 17.x, it crash.

Maybe you can try 16.x

**Comment by mendoncanorma** [comment]
@xrkffgg , I am on react 16.13.1

**Comment by xrkffgg** [comment]
Try 16.14.0

**Comment by mendoncanorma** [comment]
@xrkffgg , I tried 16.14.0, no luck. You may try on the sandbox link above.

**Comment by xrkffgg** [comment]
![1234](https://user-images.githubusercontent.com/29775873/106904602-58c2fa00-6736-11eb-95b6-d4700068c55b.gif)

**Comment by bipashant** [comment]
Having the same issue "react": "^16.4.0" and "antd": "^3.19.8",

**Comment by ZiYuEdward** [comment]
it seems like the css property "transition" in latest version of safari cause the page refreshes, try cover the css in datepicker component where use transition property, refer blow

https://stackoverflow.com/questions/21767037/css-transitions-not-working-in-safari

**Comment by mendoncanorma** [comment]
@xrkffgg , Sorry for the deployed response, the page crash issue is seen on iOS alone.

**Comment by mendoncanorma** [comment]
@xrkffgg , @afc163 , 
Do you have any updates on this. A fix for this would really help.
~Norma
