### ISSUE TITLE
input输入框上限后用中文输入法继续输入将超出字数限制

### ISSUE THREAD

**Issue by Qmlg** [ant-design/ant-design#28965]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/e3g1d)

### Steps to reproduce
1.在限制100字的文本输入框输入一百个字
2.在100字中任意位置，快速的继续输入内容

### What is expected?
到达上限后不能输入

### What is actually happening?
输入新的内容，顶掉最后一个字。并且传参时会多传一个字符

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 4.10.3 |
| System | win10 |
| Browser | Chrome 87.0.4280.141 |

---
后台限制文本说明不能超过250字，数据库限制了250字。但是此文本框输入过快传参传了251个字，导致报错

**Comment by kerm1it** [comment]
我试了试没有复现，最多只能输入250个。

**Comment by start59205** [comment]
> 我试了试没有复现，最多只能输入250个。

> 


> 我试了试没有复现，最多只能输入250个。

**Comment by start59205** [comment]
> 我试了试没有复现，最多只能输入250个。



> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/e3g1d)
> 
> ### Steps to reproduce
> 1.在限制100字的文本输入框输入一百个字
> 2.在100字中任意位置，快速的继续输入内容
> 
> ### What is expected?
> 到达上限后不能输入
> 
> ### What is actually happening?
> 输入新的内容，顶掉最后一个字。并且传参时会多传一个字符
> 
> Environment	Info
> antd	4.10.3
> React	4.10.3
> System	win10
> Browser	Chrome 87.0.4280.141
> 后台限制文本说明不能超过250字，数据库限制了250字。但是此文本框输入过快传参传了251个字，导致报错

**Comment by start59205** [comment]
> 我试了试没有复现，最多只能输入250个。

![image](https://user-images.githubusercontent.com/34729984/105670967-e9226300-5f1c-11eb-9f25-d667ce8f2477.png)

![image](https://user-images.githubusercontent.com/34729984/105671001-fa6b6f80-5f1c-11eb-9726-9c5711ab07e4.png)

![image](https://user-images.githubusercontent.com/34729984/105671029-05be9b00-5f1d-11eb-9a62-c034a7ef4c94.png)

不知道这三个图能看到么。第一个图是前端给的代码。第二个是我在用了这个组件的输入框输入了250字后。用中文输入法在中间多按了几下。这个时候会顶掉最后一位数。第三个图是点了发送之后的传参。就多了一位了。

**Comment by kerm1it** [comment]
试试英文输入法可以复现么？

**Comment by Qmlg** [comment]
> 试试英文输入法可以复现么？

英文输入法好像不会出现这种情况。中文还有下边这种情况
![image](https://user-images.githubusercontent.com/34729984/105676664-ccd6f400-5f25-11eb-9f44-a462100925cc.png)

![image](https://user-images.githubusercontent.com/34729984/105676700-dc563d00-5f25-11eb-8615-4481a264fc93.png)

输入八个字之后九的拼音有jiu三个，空格选择之后就会把八顶掉

**Comment by HomyeeKing** [comment]
already working on it  https://github.com/ant-design/ant-design/pull/28734

**Comment by kerm1it** [comment]
Trace in https://github.com/ant-design/ant-design/pull/28734

**Comment by zombieJ** [comment]
ref #28940
