### ISSUE TITLE
Form.List does not supports dependencies to control updating logic with render props children.

### ISSUE THREAD

**Issue by MariiieP** [ant-design/ant-design#28969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-almeida-ljhi9?file=/src/App.js)

### Steps to reproduce
1 Create a form using Form. List
2. Adding Dependencies
AR: The dependency does not re-validate the field
ER: The dependency triggers a re-validation of the field

### What is expected?
Used when there are dependencies between fields. If a field has the dependencies prop, this field will automatically trigger updates and validations when upstream is updated. 

### What is actually happening?
The dependency does not re-validate the field

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 17.0.1/0.63.4 |
| System |  Edition	Windows 10 Pro, Version	20H2, Installed on	‎8/‎13/‎2020, OS build	19042.685  |
| Browser | Version 87.0.4280.141 (Official Build) (64-bit) |

**Comment by MariiieP** [comment]
Major

**Comment by zombieJ** [comment]
```diff
--- dependencies={["users", 0, "name"]}
+++ dependencies={[["users", 0, "name"]]}
```

**Comment by EgoPingvina** [comment]
@zombieJ can you help, please? I tried to use `dependencies` as you show, but it still did not update the `Checkbox.disabled` after `Select` changed.

                                <FormItem
                                    label="Сотрудники"
                                >
                                    <AntdForm.List
                                        errors={errors["Employees[0]"] ?? []}
                                        name="employees"
                                        onChange={() => onChange("Employees[0]")}
                                    >
                                        {(fields, { add, remove }, { errors }) =>
                                            <>
                                                {
                                                    fields.map((field, index) =>
                                                    {
                                                        const entityId = formRef.current.getFieldValue(["employees", field.name, "Id"]);

                                                        return <Space
                                                            align="baseline"
                                                            className="d-flex"
                                                            key={field.key}
                                                            style={{ marginBottom: 20 }}
                                                        >
                                                            <FormItem
                                                                dependencies={[["employees", field.name, "Id"]]}
                                                                name={[index, "IsManager"]}
                                                                valuePropName="checked"
                                                            >
                                                                <Checkbox
                                                                    className="prefix"
                                                                    disabled={entityId === undefined}
                                                                    employeeId={entityId}
                                                                />
                                                            </FormItem>
                                                            <FormItem name={[index, "Id"]}>
                                                                <Select
                                                                    placeholder="Выберите сотрудника"
                                                                >
                                                                    {
                                                                        Object.keys(employeesCatalog)
                                                                            .filter(key => entityId === employeesCatalog[key].Id
                                                                                || employees.every(x => x.Id !== employeesCatalog[key].Id))
                                                                            .map(key =>
                                                                                <Select.Option
                                                                                    key={key}
                                                                                    value={employeesCatalog[key].Id}
                                                                                >
                                                                                    {employeesCatalog[key].Name}
                                                                                </Select.Option>)
                                                                    }
                                                                </Select>
                                                            </FormItem>
                                                            <Button
                                                                danger
                                                                icon={<MinusCircleOutlined />}
                                                                onClick={() => remove(field.name)}
                                                                size="small"
                                                                type="link"
                                                            />
                                                        </Space>;
                                                    }
                                                    )
                                                }
                                                <Button
                                                    icon={<PlusOutlined />}
                                                    onClick={() => add({ IsManager: false, Id: undefined })}
                                                    size="small"
                                                    type="dashed"
                                                >
                                                    Добавить
                                                </Button>
                                                <AntdForm.ErrorList errors={errors} />
                                            </>
                                        }
                                    </AntdForm.List>
                                </FormItem>`
