### ISSUE TITLE
[Badge] Animation direction changes unexpectedly when count moves forward one digit

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#28968]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/badge-animaiton-problem-jof3h?file=/index.js)

### Steps to reproduce
Enter the reproduction link and click the add button to make `count` moves forward one digit
进入链接并点击加号按钮，使 `count` 进一位

### What is expected?
![屏幕录制2021-01-18 上午10 18 14](https://user-images.githubusercontent.com/50612752/105269792-9a4c9480-5bcf-11eb-8e9e-c9cecfdfbdea.gif)

When `count` moves forward one digit, animation should stay clockwise direction, and switch from 9 to 0 directly
当 `count` 进一位时，动画应保持顺时针方向，并从 9 直接切换到 0

### What is actually happening?
![屏幕录制2021-01-18 上午10 18 14_1](https://user-images.githubusercontent.com/50612752/105269818-a5072980-5bcf-11eb-91be-dca0b1148e53.gif)

When `count`moves forward one digit, animation changes to anticlockwise direction, instead of switching from 9 to 0 directly, it becomes more complicated and unnatural
当 `count` 进一位时，动画变为逆时针方向，没有从 9 直接切换到 0，使得动画效果变得复杂、不自然了

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | react 17.0.1 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
@zombieJ 应该是替换 rc-animate 的时候改挂了，动画效果应参考 https://3x.ant.design/components/badge-cn/#components-badge-demo-change
