### ISSUE TITLE
Mismatch between the type of TableProps::onChange::filters and ColumnType:filteredValue

### ISSUE THREAD

**Issue by popadi** [ant-design/ant-design#28971]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
The TableProps has an optional function `onChange` and the param filters can be `Record<string, (Key | boolean)[] | null>`, where `Key` is `string | number`.
```
export interface TableProps<RecordType> extends Omit<RcTableProps<RecordType>, 'transformColumns' | 'internalHooks' | 'internalRefs' | 'data' | 'columns' | 'scroll' | 'emptyText'> {
   [...]
    onChange?: (pagination: TablePaginationConfig, filters: Record<string, (Key | boolean)[] | null>
```

However, the field `filteredValue` in the interface `ColumnType` can only be `Key`, `string | number`. 
```
export interface ColumnType<RecordType> extends RcColumnType<RecordType> {
    filteredValue?: Key[] | null;
```

### What is expected?
In my old code, I used to get the filters from `onChange` and just assign them to `filteredValue`. I don't understand how can they have different types if they are tied together, one is generated by the other. I expected this to still work after the update.

### What is actually happening?
They have different types so you can't assign the result of one as a parameter to the other, because `filters` not also allows `boolean`, but `filteredValue` doesn't. 

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 88.0.4324.96 |

---
I didn't add a codepen URL, I wasn't able to properly use antd there (I keep getting the error that antd is not defined). Let me know is this is really needed.

**Comment by mumiao** [comment]
i mention pr
