### ISSUE TITLE
In typescript Use Icon component  to load the custom SVG file failed 

### ISSUE THREAD

**Issue by BenLampson** [ant-design/ant-design#28970]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/BenLampson/antdIconIssue](https://github.com/BenLampson/antdIconIssue)

### Steps to reproduce
1. clone the github  repository : [repository](https://github.com/BenLampson/antdIconIssue)
2. npm install
3. npm test
4. http://127.0.0.1:8001

### What is expected?
open the website.

### What is actually happening?
react-dom.development.js?61bb:23275 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('http://127.0.0.1:8081/efd77a51166373660379da8929b989d9.svg') is not a valid name.

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.1 |
| System | Win10 |
| Browser | Edge version 87.0.664.75 |

**Comment by zombieJ** [comment]
`component` accept React component type not svg.

**Comment by BenLampson** [comment]
??? just the URL's extends is SVG, the content is the React component with typescript.
I learn this way from ant. design home page.
