### ISSUE TITLE
Layout problem when you combine Layout.Sider and Layout.Content inside a Layout component

### ISSUE THREAD

**Issue by popadi** [ant-design/ant-design#28979]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/adrianpop/pen/rNMbqzO](https://codepen.io/adrianpop/pen/rNMbqzO)

### Steps to reproduce
Visit https://codepen.io/adrianpop/pen/rNMbqzO and scroll down. You'll see that the collapse button and the menu will separate (because the collapse button is fixed). If you uncomment the `style={{ overflowX: "hidden" }}` section in `Layout.Content`, it works as expected. 

### What is expected?
It's expected to be able to scroll in the `Layout.Content` area and the menu to be stable. If you uncomment the `style={{ overflowX: "hidden" }}` section in `Layout.Content`, it works as expected. 

### What is actually happening?
When you scroll, there's some kind of gap appearing. The menu doesn't stay fixed.

The problem was introduced after the removal of `overflow-x: hidden` in this commit: https://github.com/ant-design/ant-design/commit/ebb6fcf6c5422998f9a212faf878cda2c42cf3d5#diff-66ac06b967d541570a396a645f995f96004d497d3937461cda5e5881777dabd6.

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 88.0.4324.96 |

---
90% of the code is from an official example ("Collapsed inline menu" from the Menu component). All I did was to surround everything by `Layout` and split it in two: `Layout.Sider` and `Layout.Content` (as per official documentation, this should be a valid way to have a fixed side menu and a y-axis scrollable content).

**Comment by afc163** [comment]
In this case, we should set right content area to be a scrollable container precisely. The original `overflow-x: hidden` simply make it works by accident.

See https://codepen.io/afc163/pen/OJRYPKz
