### ISSUE TITLE
Table组件固定表头，table-header和table-body默认的overflow为scroll

### ISSUE THREAD

**Issue by alwayalive** [ant-design/ant-design#2897]
#### 本地环境

- antd 版本:1.10.0
- 操作系统及其版本：win10 64
- 浏览器及其版本:chrome 52.0.2743.116

#### 你做了什么？

按需加载组件方式引入Table组件

#### 可重现的在线演示
http://ant.design/components/table/#components-table-demo-fixed-header

**Comment by benjycui** [comment]
是有这个问题

![image](https://cloud.githubusercontent.com/assets/3580607/18121796/cd6eec46-6f98-11e6-9b8a-19c6fe712d0f.png)

直接来个 PR 如何 😄

**Comment by afc163** [comment]
滚动条是解决列对齐问题的。

https://github.com/ant-design/ant-design/issues/2227

https://github.com/ant-design/ant-design/issues/1740
