### ISSUE TITLE
webpark打包出来的构建文件，访问页面时候提示我要使用babel-plugin-antd

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2899]
You are using prebuilt antd,
please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.

请问官方大神，如何使用babel-plugin-antd插件做代码按需，我的webpark配置是自己写的，没用官方的atoolbuild

**Comment by afc163** [comment]
http://ant.design/docs/react/getting-started#%E8%87%AA%E8%A1%8C%E6%9E%84%E5%BB%BA
