### ISSUE TITLE
[Form & InputNumber] If you enter a value that doesn't conform to the rule in the InputNumber and hit enter, the form doesn't validate, it just submits

### ISSUE THREAD

**Issue by yingpengsha** [ant-design/ant-design#29000]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-txv8q?file=/index.js)

### Steps to reproduce
1. Problem one
  - input the values that do not conform to the rule
  - just hit Enter
  - verification passed

2. Problem two
  - input the values that do not conform to the rule, like 'asdfasdfasd'
  - just hit Enter
  - InputNumber will disable
  - time over, InputNumber remains in the error state unless the value is changed

### What is expected?
InputNumber provides the correct value to the form

### What is actually happening?
InputNumber provides the wrong value to the form

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome 87.0.4280.141 |

**Comment by afc163** [comment]
1. Problem one

```diff
-       <Form.Item name="number" rules={[{ required: true }]}>
+       <Form.Item name="number" rules={[{ required: true, type: 'number' }]}>
          <InputNumber style={{ width: 200 }} />
        </Form.Item>
···
