### ISSUE TITLE
Carousel组件能实时提供当前图片的索引或者相关信息

### ISSUE THREAD

**Issue by Liuhongwei3** [ant-design/ant-design#29001]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如我现在想要先获取当前播放的图片，然后根据图片提取主色调再同步到组件外框的背景色，这里只是一个使用场景（我们也可能拿到当前播放图片的信息去做更多的事情）。

### What does the proposed API look like?
目前我只是能手动拿到slide中state.currentSlide，但是我想要图片一切换我能获取最新的这个值（能提供一个onSlideChange回调再好不过了）。
非常感谢！

**Comment by afc163** [comment]
https://react-slick.neostack.com/docs/api#afterChange

**Comment by Liuhongwei3** [comment]
> https://react-slick.neostack.com/docs/api#afterChange

emmm，不好意思，还是文档看的不够仔细，谢谢解答。
