### ISSUE TITLE
PreviewGroup包裹下的<Image> 无法通过preview主动调用

### ISSUE THREAD

**Issue by xiaoxiaofan123** [ant-design/ant-design#29016]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duozhangtupianyulan-antd4111-forked-dc5ox?file=/index.js)

### Steps to reproduce
<Image>通过preview={visible}实现主动预览，点击button后visible变为true。
无PreviewGroup包裹下 点击button可正常预览图片。
加上PreviewGroup后点击button无法预览图片。

### What is expected?
PreviewGroup包裹下正常展示图片预览

### What is actually happening?
未正常展示图片预览

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 16.9.17 |
| System | mac 11.0.1 |
| Browser | chrome 88.0 |

**Comment by shaodahong** [comment]
如果用了 `PreviewGroup` 那么 `Image` 就不会受控了，想要受控可以给 `PreviewGroup` 加个 `preview`

**Comment by xiaoxiaofan123** [comment]
> 如果用了 `PreviewGroup` 那么 `Image` 就不会受控了，想要受控可以给 `PreviewGroup` 加个 `preview`
我有试过给PreviewGroup加preview 好像也不行诶？
function ImageDemo() {
  const [show, setShow] = useState(false);
  return (
    <div>
      <button
        onClick={() => {
          setShow(true);
        }}
      >
        show
      </button>
      <Image.PreviewGroup
        preview={{
          visible: show
        }}
      >
        <Image
          width={200}
          src="https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg"
        />
        <Image
          width={200}
          src="https://gw.alipayobjects.com/zos/antfincdn/aPkFc8Sj7n/method-draw-image.svg"
        />
      </Image.PreviewGroup>
    </div>
  );
}

**Comment by shaodahong** [comment]
嗯，还没实现，因为如果收集底层 Image 受控状态传到上层可能会冲突

**Comment by xiaoxiaofan123** [comment]
> 嗯，还没实现，因为如果收集底层 Image 受控状态传到上层可能会冲突

哦哦这样 感谢回复 那如果我想实现受控的多图浏览 目前还做不到么

**Comment by shaodahong** [comment]
> > 嗯，还没实现，因为如果收集底层 Image 受控状态传到上层可能会冲突
> 
> 哦哦这样 感谢回复 那如果我想实现受控的多图浏览 目前还做不到么

是的

**Comment by xiaoxiaofan123** [comment]
> > > 嗯，还没实现，因为如果收集底层 Image 受控状态传到上层可能会冲突
> > 
> > 
> > 哦哦这样 感谢回复 那如果我想实现受控的多图浏览 目前还做不到么
> 
> 是的

你好 麻烦再问一下 最近有规划实现这个feature么 我这边需要受控主要是配合upload的fileList使用 短期没有的话我就先自定义fileList

**Comment by shaodahong** [comment]
想了一下，暂时的想法还是通过 Image 的受控来解决，最近工作有点忙，预期月底前完成

**Comment by xiaoxiaofan123** [comment]
谢谢带佬 辛苦啦

**Comment by jovana** [comment]
> > 如果用了 `PreviewGroup` 那么 `Image` 就不会受控了，想要受控可以给 `PreviewGroup` 加个 `preview`
> 
> 我有试过给PreviewGroup加preview 好像也不行诶？
> 
> ```
>   const [show, setShow] = useState(false);
>   return (
>     <div>
>       <button
>         onClick={() => {
>           setShow(true);
>         }}
>       >
>         show
>       </button>
>       <Image.PreviewGroup
>         preview={{
>           visible: show
>         }}
>       >
>         <Image src=""/>
>       </Image.PreviewGroup>
>     </div>
>   );
> }
> ```

This is still working in version 5.3.2. But it has been removed from the documentation on: https://ant.design/components/image.
