### ISSUE TITLE
horizental

### ISSUE THREAD

**Issue by mohammadtaghian** [ant-design/ant-design#29017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mohammadtaghian/antdesign.git](https://github.com/mohammadtaghian/antdesign.git)

### Steps to reproduce
..................

### What is expected?
...........

### What is actually happening?
when running the code said : TypeError: Cannot read property 'eventKey' of undefined

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 17 |
| System | windows(10) |
| Browser | latest |

**Comment by mohammadtaghian** [comment]
![image](https://user-images.githubusercontent.com/56147396/105679345-8b355180-5f03-11eb-91ab-4d8f8809bcc7.png)

**Comment by mohammadtaghian** [comment]
horizental mode have problem.
i checked and used other mode all working well instead of horizental one.
please open and work with pc , then you will undrestand

**Comment by afc163** [comment]
<img width="527" alt="图片" src="https://user-images.githubusercontent.com/507615/105694796-4da0ea80-5f3c-11eb-8dea-fa44a1596486.png">

**Comment by afc163** [comment]
see https://github.com/ant-design/ant-design/issues/15724#issuecomment-477846616
