### ISSUE TITLE
Carousel 不能按压滑动

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#29018]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我看 react-slick官网的demo, 在PC模式下，按住滑块是可以滑动的，但是 Carousel却不可以。

### What does the proposed API look like?
希望按压滑动可以生效，目前是只能点击 dots 才可以切换，操作区域有点小

**Comment by xrkffgg** [comment]
Similar like https://github.com/ant-design/ant-design/issues/28384

**Comment by qiaodaima** [comment]
> Similar like #28384

和这个有点不太一样，他是要改 dots的样式，
我这个是希望 按压 滑块能拖拽滑动

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/jiben-antd4111-forked-ukwgy
