### ISSUE TITLE
请问是否能提供最新的d.ts文件？用于在TypeScript中使用antd?

### ISSUE THREAD

**Issue by niss2000** [ant-design/ant-design#2901]
网上提供的antd.d.ts太旧了，很多组件都没有及时更新，用过TypeScript之后，觉得比es6的语法要更容易理解和上手，唯一的缺点就是要引入d.ts，由于ts未成为标准，目前只有在GitHub上找，但是antd更新太慢，目前最新的都是5个月前的

**Comment by afc163** [comment]
1. https://github.com/ant-design/ant-design/blob/1.x-stable/index.d.ts
2. https://github.com/ant-design/ant-design/issues/1846 wait for 2.0
