### ISSUE TITLE
Typescript compile error regression in 4.11.1

### ISSUE THREAD

**Issue by nrayburn-tech** [ant-design/ant-design#29015]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nrayburn-tech/antd-ts-error ](https://github.com/nrayburn-tech/antd-ts-error )

### Steps to reproduce
1. Clone repo
2. Run `npx tsc`.

### What is expected?
No compile error.

### What is actually happening?
Error when compiling.

```
node_modules/antd/lib/tooltip/placements.d.ts:16:73 - error TS2307: Cannot find module '_rc-trigger@5.2.1@rc-trigger' or its corresponding type declarations.

16 export default function getPlacements(config: PlacementsConfig): import("_rc-trigger@5.2.1@rc-trigger").BuildInPlacements;
```

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 17 |
| System | macOS Big Sur |
| Browser | Chromium 88 |

---
This comes from using `skipLibChecks: false` in the tsconfig file.  I don't really know what it does, but I believe it was the default from `vite` and is how I ran into this issue.  `skipLibChecks: true` can be used to avoid the error, if necessary.

**Comment by waiwaiku** [comment]
## same issue.
npm package file of antd/lib/placements.d.ts
![image](https://user-images.githubusercontent.com/16569491/105678496-322be480-5f28-11eb-8d32-7f6a3aa6928c.png)

**Comment by waiwaiku** [comment]
[fix](https://github.com/ant-design/ant-design/pull/29029#issue-560937465)
