### ISSUE TITLE
Carousel change when mouse hover dot

### ISSUE THREAD

**Issue by Xie-Jay** [ant-design/ant-design#29022]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Carousel change when mouse hover dot

### What does the proposed API look like?
dotTrigger

**Comment by xrkffgg** [comment]
啥意思？

**Comment by Xie-Jay** [comment]
> 啥意思？

![image](https://user-images.githubusercontent.com/64340763/105678444-204a4180-5f28-11eb-92a8-e8c40a4b1bbc.png)
现在只能点击切换, 能不能实现鼠标hover就可以切换

**Comment by xrkffgg** [comment]
原生的不支持，你可以试试 自定义 https://react-slick.neostack.com/docs/example/append-dots

然后监控鼠标 hover 进行切换

**Comment by wenjiewu** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> Carousel change when mouse hover dot
> 
> ### What does the proposed API look like?
> dotTrigger

dotTrigger有这个API吗  没看到啊 值是啥啊 我也想hover的时候可以切换
