### ISSUE TITLE
Button support  disabled style can use  loading style

### ISSUE THREAD

**Issue by Xie-Jay** [ant-design/ant-design#29021]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
sometimes using loading style would be pretty more than default
![image](https://user-images.githubusercontent.com/64340763/105675803-9482e600-5f24-11eb-8206-2543845cf71d.png)

### What does the proposed API look like?
disabledType

**Comment by xrkffgg** [comment]
这应该不符合预期。disabled 是不能进行任何操作的。不过你可以自行添加这个样式。

**Comment by afc163** [comment]
可以用中文描述一下么，看不太懂。

**Comment by Xie-Jay** [comment]
> 可以用中文描述一下么，看不太懂。

希望 button 禁用的样式可以选择加载中的样式

很多场景下，希望使用loading的效果`.${prefixCls}-loading`代替`[disabled]`

![IMG_20210125_204849](https://user-images.githubusercontent.com/64340763/105708096-e50f3900-5f4e-11eb-81d0-cc052cdef11a.jpg)
![IMG_20210125_204941](https://user-images.githubusercontent.com/64340763/105708130-f0626480-5f4e-11eb-9ea0-d7aab5f4a2b7.jpg)

**Comment by xrkffgg** [comment]
loading 套个 disabled 样式就行

**Comment by Xie-Jay** [comment]
> loading 套个 disabled 样式就行

loading样式匹配的是`:before`伪元素, 直接loading 套个 disabled 样式不能得到这种效果

默认效果:
![image](https://user-images.githubusercontent.com/64340763/105785776-b331bd00-5fb6-11eb-9c37-d43e997ab8b4.png)

期望效果:
![image](https://user-images.githubusercontent.com/64340763/105785424-cc863980-5fb5-11eb-9a6b-b8588ef390c5.png)

套用样式结果:
![image](https://user-images.githubusercontent.com/64340763/105785689-78c82000-5fb6-11eb-9e70-ba20a161981b.png)

**Comment by xrkffgg** [comment]
我的意思是 loading 保持默认，然后 className 新增一个自定义的，加上你想要的 一些背景啊，颜色啊之类的样式

**Comment by Xie-Jay** [comment]
> 我的意思是 loading 保持默认，然后 className 新增一个自定义的，加上你想要的 一些背景啊，颜色啊之类的样式

的确可以, 但是有选择的余地可能更好:blush:
