### ISSUE TITLE
Ant select dropdown width issue #28661

### ISSUE THREAD

**Issue by truonghoit** [ant-design/ant-design#29031]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-puqwl?file=/index.css)

### Steps to reproduce
set the border of select input and dropdown to 2 pixels
See the ui of selection input and the dropdown in the reproduction link
![Image of selectbox issue](https://lh3.googleusercontent.com/SH6xXdz9lXI9P_8AGxHxjdiWNwQBsskqVD25tliR2QIKXQ-VdroufAMqU2rRLkVOQvUorjT0POytbfFm12sTn4n3m4B3U90lFIiGzByW-bF1GIlQo72FPbUpbMshlvwRk0PnSlZf8ENcRr3DF45b3gJLX2jXRv7GOvJa2KFx7rAnKIhtewOHQ8HxeslaikACQ38FHWfVhx7OZ47Fm9W736oUpKXeHp8Cr_q9V6tvBPxyiIZksx1B3RthbDwb7UYrukEAX20aoYjywfvDspXaCOsZX99MGhzqIEE7D7EQ9rNJ4Onxbk_OGyPuhKZRFfmb-VPBOwudca2ErMlVcJzz5VgQsvzgJ1cLkhOZphqnrrDFbpL3vr8gUF828W3q0Kg0ym_TZ9I-P47XP8FaIgRAWuG724j7wX6kwajmoIHVuiCH8gFShsZdMbYzCFSOwbYzfP60jDOaOU7IagFYb6Qppyz0fCfuYEoXT9sd-OYkyKZEfeuvRwGllnT3Ct7mzqNADFvuSxN4jQ6Zmps0eDMeVGF-LckWOyP4umlFh_EbJ4Zx7FzBHZmX2VE1I2LuVPFhnFuXOa5WPRTdpShVtbbG8qWEinPXXQpWlUWnQHQvgR_pfJJU3KSEO7BlrYXOaUfKrHLxLc2_smpYGplZTnNDw5otwtrnMAIsTcHeqhzqAOJHCBPOBjWHsanXrzne1Q=w415-h168-no?authuser=0)

### What is expected?
the width of the dropdown and the input are the same

### What is actually happening?
the width of the dropdown and the input are different from each other

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Windows 10 Enterprise version 20H2 |
| Browser | google chrome Version 87.0.4280.141 |

**Comment by afc163** [comment]
If you override the default styles of antd, you need to resolve the styling issue by yourself.
