### ISSUE TITLE
How to achieve less modules 

### ISSUE THREAD

**Issue by Wykyoyo** [ant-design/ant-design#29035]
![0](https://user-images.githubusercontent.com/32306550/105727949-92417b80-5f66-11eb-9b58-5adc94ff87e5.png)
![1](https://user-images.githubusercontent.com/32306550/105727964-97062f80-5f66-11eb-9103-6af2edcb5fee.png)

- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm going to build a React app,Less is used.I'm trying to use className={styles.app}，But I didn't get the results I wanted，How can I do that？

In craco.config.js:
const CracoAntDesignPlugin = require("craco-antd");
module.exports = {
  plugins: [
    { 
      plugin: CracoAntDesignPlugin ,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: { '@primary-color': '#1DA57A' },
            javascriptEnabled: true,
          }
        },
      },
    },
  ],
};

in index.tsx:
import { Button } from 'antd';
import React from 'react';
import logo from '../logo.svg';
import styles from './index.less';

function App() {
  return (
    <div **className={styles.app}**>
      <header className={styles.app_header}>
        <Button type="primary">按钮</Button>
        <img src={logo} className={styles.app_logo} alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className={styles.app_link}
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}
export default App;

### What does the proposed API look like?
I can achieve use className={styles.app}

**Comment by afc163** [comment]
It is not antd issue, you should seek help in craco issues.
