### ISSUE TITLE
In v4.11.1 ConfigProvider import all icons dramatically increasing bundle size

### ISSUE THREAD

**Issue by xrutayisire** [ant-design/ant-design#29038]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-expgo?file=/index.js)

### Steps to reproduce
1. Install antd version 4.11.1
1. Install source-map-explorer
1. Import and use ConfigProvider component
1. Run source-map-explorer command on your build

Note: If you are using an antd component that internally use the ConfigProvider, it will create the same result 
(e.g: ConfirmDialog, ...)

### What is expected?
⇒ No icons are automatically imported if not needed

![No icons imported](https://i.ibb.co/xXx9vS3/Screenshot-2021-01-26-at-00-15-13.png)

### What is actually happening?
⇒ The generated bundle import all icons

![All icons imported](https://i.ibb.co/yX5ghR9/Screenshot-2021-01-26-at-00-15-36.png)

### Additional information

I think the problem is coming from this MR: https://github.com/ant-design/ant-design/pull/28924 
Exactly this line is causing the problem for me: https://github.com/ant-design/ant-design/pull/28924/files#diff-0a9895a32672ec55a084aa7165fc8666008942903b8e51e30b662e9e1ecffb56R2

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | React 17.0.0 |
| System | OSX |
| Browser | Chrome |

**Comment by zombieJ** [comment]
ref #21744

**Comment by xrutayisire** [comment]
> ref #21744

Thanks a lot @zombieJ !

It's just strange since I'm following official documentation to have this tree shaking problem. I'm using Craco : https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides

Is there also a problem with tree shaking not being done with it?
