### ISSUE TITLE
[form]form.list initial value in add function does not work when row and col nested in form.item

### ISSUE THREAD

**Issue by storageChu** [ant-design/ant-design#29039]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/test-u9rvv)

### Steps to reproduce
https://codesandbox.io/s/test-u9rvv

### What is expected?
initial value in add function work well

### What is actually happening?
initial value in add function does not work

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 16.13..1 |
| System | windows10 |
| Browser | chrome |

**Comment by storageChu** [comment]
I found that initial value in add function are effected when every div nested in Form.Item not only Row or Col

**Comment by afc163** [comment]
> <Form.Item name="field" /> 只会对它的直接子元素绑定表单功能

https://ant.design/components/form-cn/#components-form-demo-complex-form-control
