### ISSUE TITLE
tree title上添加了onMouseLeave事件，hover后弹出modal对话框，选择form表单中input记忆项时，modal弹框消失

### ISSUE THREAD

**Issue by superw-123** [ant-design/ant-design#29032]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f7buj.csb.app/](https://f7buj.csb.app/)

### Steps to reproduce
见demol， https://codesandbox.io/s/f7buj?file=/TreeNodeItem/index.js

### What is expected?
选择表单中input的记忆项时，modal弹框不消失

### What is actually happening?
选择表单中input的记忆项时，modal弹框不消失

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.12.0 |
| System | mac catalina 10.15.5 |
| Browser | 87.0.4280.141（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-v7db8?file=/TreeNodeItem/index.js

**Comment by superw-123** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-v7db8?file=/TreeNodeItem/index.js

非常感谢
