### ISSUE TITLE
calendar 有bug 选九月出来十月

### ISSUE THREAD

**Issue by wangjinghui-cn** [ant-design/ant-design#2903]
- 问题描述                   // 请尽量结合截图详细描述，
   - 1. http://ant.design/components/calendar/ 进calendar 选择时间
![image](https://zos.alipayobjects.com/rmsportal/jwHsNMibTgZpFfC.png)
                           
   - 2. 选择九月
![image](https://zos.alipayobjects.com/rmsportal/KqLzShTsdZkXSQh.png)
   
   - 3. 出来十月
![image](https://zos.alipayobjects.com/rmsportal/PhkaQMYNpROvWsk.png)

**Comment by benjycui** [comment]
本地改了日期也无法重现，不知道是不是和时区相关，所以能提供更多信息么?

**Comment by afc163** [comment]
我可以重现。改到 8 月 31 日就行。

**Comment by benjycui** [comment]
我在这边 debug 好像是 `gregorian-calendar` 里面的问题，在换成 moment 的分支里面就没事了。

**Comment by benjycui** [comment]
2.0 里面修复，`antd@2.0-beta.x` 下周发。
