### ISSUE TITLE
Dropdown放在表格固定列里超出会被裁剪

### ISSUE THREAD

**Issue by hyl1374961656** [ant-design/ant-design#29044]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-znxb5o?file=src%2FApp.js](https://stackblitz.com/edit/react-znxb5o?file=src%2FApp.js)

### Steps to reproduce
鼠标划过Dropdown内容超出被裁剪

### What is expected?
Dropdown能正常显示

### What is actually happening?
Dropdown显示问题

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
浮层渲染在滚动区域是一定会被滚动条限制的，这个目前没有完美的办法，建议删除 getPopupContainer（当然删掉很可能浮层就没办法随着 trigger 一起移动了）。
