### ISSUE TITLE
树形控件拖拽节点，在拖拽有效区域外松开鼠标放弃拖拽，选中状态无法取消

### ISSUE THREAD

**Issue by WendyFDU** [ant-design/ant-design#2904]
本地环境

antd 版本: 1.8
浏览器及其版本: safari
你做了什么？

点击选中节点开始拖拽，鼠标移到拖拽有效区域外松开，放弃拖拽

你期待的结果是：

拖拽放弃后取消选中状态（取消蓝色）

实际上的结果：

<img width="154" alt="2016-08-31 8 06 52" src="https://cloud.githubusercontent.com/assets/15245525/18128068/8d52b322-6fb6-11e6-8a5c-6f72be7894c1.png">

可重现的在线演示

官网拖动实例demo

**Comment by WendyFDU** [comment]
选中节点A开始拖拽，如果在onDrop()中增加判断逻辑，在某些情况下用return终止操作的话，下一次拖拽操作节点B时，节点A的颜色也会改变
比如：
`onDrop(info) {
    if (xxx === true) {
      message.warning('不能移入');
      return;
    } 
  }`

<img width="298" alt="2016-09-01 1 47 16" src="https://cloud.githubusercontent.com/assets/15245525/18156730/fd863ef4-704a-11e6-9d29-aec61815b2d7.png">

**Comment by warmhug** [comment]
return 之前 setState，重新生成 TreeNodes
