### ISSUE TITLE
Can not change the default Left to Right behavior of switching the DatePicker date

### ISSUE THREAD

**Issue by nichitapasecinic** [ant-design/ant-design#29048]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd4103-forked-2pl30?file=/index.js)

### Steps to reproduce
The locale atribut for antd datepicker is not changing this behavior nor locale atribut for ConfigProvider or direction atribut. So is there a way that the "right" arrow for the  datepicker will decrease the month/year date value ?

### What is expected?
locale/ direction atribute (for configProvider) to change the behavior for datepicker 

### What is actually happening?
direction atribut does nothing and the locale atribut only changes the language for datepicker

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | react ^16.0 |
| System | Windows 10 Pro |
| Browser | Chrome |

**Comment by liviu-ganea** [comment]
What about the error icon placement on the input?

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-usage-antd4103-forked-fmr69?file=/index.js

**Comment by nichitapasecinic** [comment]
@afc163  what about older version of antd ??
thx

**Comment by afc163** [comment]
3.x is not maintained anymore.

**Comment by nichitapasecinic** [comment]
@afc163 but is there a way to overwrite this behavior, mb wtth css ?
