### ISSUE TITLE
TextArea with autoSize Scroll visible inside Form.Item

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#29052]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lsky3?file=/index.js)

### Steps to reproduce
open link

### What is expected?
autoSized TextArea without borders

### What is actually happening?
scroll visible with only one row of a text

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | latest |
| System | Mac Os Catalina |
| Browser | Chrome latest |

**Comment by vorlov** [comment]
try to comment/uncomment bordered property

**Comment by zombieJ** [comment]
codesandbox use HMR to dynamic update component. comment and reload demo instead.
