### ISSUE TITLE
https://ant-design.gitee.io  404

### ISSUE THREAD

**Issue by fajiaopaopao** [ant-design/ant-design#29064]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io](https://ant-design.gitee.io)

### Steps to reproduce
浏览器输入网址

### What is expected?
能够正常展示

### What is actually happening?
404

| Environment | Info |
|---|---|
| antd | undefined |
| React | 无 |
| System | 无 |
| Browser | 无 |

**Comment by shaodahong** [comment]
哪个区域的，上海是 OK 的

**Comment by yoyo837** [comment]
目前似乎已经好了

**Comment by fajiaopaopao** [comment]
> 哪个区域的，上海是 OK 的

北京，这个点已经好了
