### ISSUE TITLE
在 table 组件中，如果其中一个 column 设置了 filteredValue，会导致其他 uncontrolled column 的 filter 失效，onFilter 不触发

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#29060]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-antd4112-forked-4je0c?file=/index.js)

### Steps to reproduce
1. 点击 age filter，选中 32，确定，会发现没有反应
2. 注释掉代码112行的`filteredValue: [],`
3. 点击 age filter，选中 32，确定，会发现 filter 起作用了

### What is expected?
一个 column 的 onFilter，在其他 column 设置了 filteredValue 的情况下，也应该生效

### What is actually happening?
一个 column 的 onFilter，因为其他 column 设置了 filteredValue 而失效

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.14.0 |
| System | all |
| Browser | all |

---
感觉 table/hooks/userFilter/index.tsx 中的 mergedFilterStates，用 collectedStates.every(({ filteredKeys }) => filteredKeys === undefined) 去判断是否 controlled 不太合适，最好是用 column 有没有传 filteredValue 作为判断的依据，那么应该就不会有这个问题了
https://github.com/ant-design/ant-design/blob/57d37247df34268988ef883a9e141d1a3bc570dc/components/table/hooks/useFilter/index.tsx#L207

**Comment by zombieJ** [comment]
特意的，要受控就全受控。半受控很容易写出神奇代码，也不方便人理解。

**Comment by zation** [comment]
@zombieJ 主要是这个感觉就像一个 form 中，某个 input 受控了，其他 input 也必须受控一样，还是有点奇怪

**Comment by zombieJ** [comment]
和 form 还是有些区别，过滤是一套的。过滤里再分半受控，状态管理就稀烂了。
