### ISSUE TITLE
Select组件的mode=“multiple” & Options以属性的方式传递给组件，然后搜索失效了。

### ISSUE THREAD

**Issue by Surenjun** [ant-design/ant-design#29077]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/live/vziv9n8)

### Steps to reproduce
在Select中输入搜索项

### What is expected?
能搜索出结果

### What is actually happening?
未搜索到结果

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome 84.0.4147.105（正式版本） （64 位） |

**Comment by AlanCutFlim** [comment]
> https://ant.design/components/select-cn/#API
搜索时过滤对应的 option 属性，如设置为 children 表示对内嵌内容进行搜索。若通过 options 属性配置选项内容，建议设置 optionFilterProp="label" 来对内容进行搜索。

```diff
   <Select
      mode="multiple"
      showSearch={true}
-     optionFilterProp="children"
+     optionFilterProp="label"
      style={{ width: "100%" }}
      placeholder="这个搜索就失效了"
      options={[
        { label: "测试数据1", value: 1 },
        { label: "测试数据2", value: 2 },
        { label: "测试数据3", value: 3 }
      ]}
      onChange={handleChange}
   />
```
