### ISSUE TITLE
form表单校验

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2907]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本： win10
- 浏览器及其版本: chrome

#### 你做了什么？

使用了表单的校验

#### 你期待的结果是：

隐藏元素不需要校验

#### 实际上的结果：

所有的校验都生效了,希望可以提供一个选项忽略隐藏元素的校验。

#### 可重现的在线演示

http://codepen.io/anon/pen/EgYqwr?editors=0010#anon-login

**Comment by juanpengke** [comment]
rc-form 提供了一个hidden 的属性，我试了可以

**Comment by benjycui** [comment]
more: http://react-component.github.io/form/examples/dynamic.html
