### ISSUE TITLE
message组件

### ISSUE THREAD

**Issue by billinfo** [ant-design/ant-design#29072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
message组件的内容只能是文本吗？

### What does the proposed API look like?
能不能弹出一个组件？例如国际化的FormattedMessage

**Comment by zombieJ** [comment]
<img width="128" alt="截屏2021-01-27 下午5 51 30" src="https://user-images.githubusercontent.com/5378891/105973942-4c9cc400-60c8-11eb-92d1-424131875918.png">
