### ISSUE TITLE
Form表单，在触发多次参数校验后，两个Form.Item间的间距会消失，导致两个Form.Item紧挨在一起

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#29071]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4112-forked-qv39p)

### Steps to reproduce
1. 设置input输入最小长度为4，触发校验为默认
2. 在input中输入内容，在此过程中会触发长度小于4的校验，继续输入到长度大于四个字符即可
3. 鼠标选中所有输入的文本
4. 重新执行上述2的步骤
5. 重复执行上述2、3、4的步骤。
6. 反复几次操作后就会出现两个两个Form.Item的间距小时，紧挨在一起的现象 
详见代码重现示例中的 antd-Form.gif 图片
### What is expected?
按照重现步骤操作，能够保持排版正常。

### What is actually happening?
按照重现步骤操作，会出现两个Form.Item紧挨在一起，影响排版美观。

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome87 |

**Comment by zombieJ** [comment]
Duplicate of #28938

**Comment by zombieJ** [comment]
Duplicate of #27746
