### ISSUE TITLE
Skeleton组件和Table组件，使用table组件的sticky属性时，会报错 Cannot read property 'scrollLeft' of null

### ISSUE THREAD

**Issue by xiaoblack163** [ant-design/ant-design#29078]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-xsajw5?file=index.js](https://stackblitz.com/edit/react-xsajw5?file=index.js)

### Steps to reproduce
使用Skeleton和Table组件时，使用Table组件的 sticky属性，在componentDidMount去改变loading状态

### What is expected?
不要报错 

### What is actually happening?
使用Skeleton和Table组件时，使用Table组件的 sticky属性，在componentDidMount去改变loading状态的时候， 会报错，错误信息为 Cannot read property 'scrollLeft' of null 

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome 88 |

**Comment by afc163** [comment]
<img width="623" alt="图片" src="https://user-images.githubusercontent.com/507615/105989632-5c260800-60dc-11eb-84c5-aa57b9a840f5.png">

No errors in your demo.

**Comment by xiaoblack163** [comment]
@afc163 打开更多工具里面的开发者工具会有这个报错信息 
![image](https://user-images.githubusercontent.com/6647266/106081184-6a633b00-6153-11eb-9a4e-5aa7be88c944.png)

**Comment by xiaoblack163** [comment]
> <img alt="图片" width="623" src="https://user-images.githubusercontent.com/507615/105989632-5c260800-60dc-11eb-84c5-aa57b9a840f5.png">
> 
> No errors in your demo.
打开 chrome里面的开发者工具 会有这个报错 @afc163 
![image](https://user-images.githubusercontent.com/6647266/106081389-c5952d80-6153-11eb-8e2e-12af414c3a15.png)

**Comment by xiaoblack163** [comment]
@afc163 打开chrome 的开发者工具会有这个报错
![image](https://user-images.githubusercontent.com/6647266/106081488-f07f8180-6153-11eb-98ef-d288709fe629.png)

**Comment by xiaoblack163** [comment]
https://react-xsajw5.stackblitz.io/ 这个例子里面，打开调试工具，会报错 @afc163

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/table/releases/tag/v7.13.1
