### ISSUE TITLE
抽屉中打开对话框关闭后页面 body 无法滚动

### ISSUE THREAD

**Issue by jakeyFan** [ant-design/ant-design#29070]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-snowflake-u6uxh?file=/index.js)

### Steps to reproduce
1. 打开抽屉
2. 打开 m1模态框（打开同时关闭抽屉）
3. 关闭m1模态框
4. 页面 body 不滚动了

### What is expected?
关闭 m1 后，页面 body 要能滚动

### What is actually happening?
关闭 m1 后，页面 body 不能滚动，body的overflow为hidden

| Environment | Info |
|---|---|
| antd | 3.26.19 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome Version 87.0.4280.88 (Official Build) (64-bit) |

---
这个bug3.x的版本请问什么时候修复

**Comment by hhxsv5** [comment]
我也遇到了😂
