### ISSUE TITLE
`Selections` arrow overlap borders in bordered tables

### ISSUE THREAD

**Issue by artplan1** [ant-design/ant-design#29083]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://hmzhe.csb.app/](https://codesandbox.io/s/ghfl4?file=/index.js)

### Steps to reproduce
1. enable selection actions in table
2. add border to table

### What is expected?
no overlap, wider paddings

### What is actually happening?
arrow overlaps border

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17 |
| System | mac os |
| Browser | chrome 88 |

![image](https://user-images.githubusercontent.com/9060346/106015702-cab09900-60cf-11eb-8805-5c448861b2bd.png)

**Comment by afc163** [comment]
reproduce: https://codesandbox.io/s/custom-selection-antd4112-forked-zkyqx
