### ISSUE TITLE
使用iconPrefixCls 修改图标前缀，message 里的icon 样式名未生效

### ISSUE THREAD

**Issue by jpy920718** [ant-design/ant-design#29085]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jpy920718/demo-message-icon](https://github.com/jpy920718/demo-message-icon)

### Steps to reproduce
1. umi 创建项目
2. .umirc 里的 lessLoader 和 antd 分别配置prefixCls 和 iconPrefixCls
3. 其他使用到icon 的正常，现发现message 里使用icon 未生效

### What is expected?
iconPrefixCls 设置 在message 里一样生效

### What is actually happening?
iconPrefixCls 修改图标前缀，message 里的icon 样式名未生效

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.1 |
| System | macOS 11.1 |
| Browser | 88 |

**Comment by afc163** [comment]
https://ant.design/components/message-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-message-%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-%E7%9A%84-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F
