### ISSUE TITLE
Radio.Button，Radio.Group 组件 打包前后label标签的class不一致

### ISSUE THREAD

**Issue by xiebin2014** [ant-design/ant-design#2908]
- antd 版本: 1.6.2
- 操作系统及其版本：win10
- 浏览器及其版本: chrome 52.0.2743.82 m

使用 Radio.Button，Radio.Group。
调试的时候 label标签上的className 是 ant-radio-button-wrapper，
webpack打包完成，label标签的className变成了 ant-radio-button

**Comment by benjycui** [comment]
能提供更多信息？

**Comment by xiebin2014** [comment]
可以，需要什么信息

**Comment by afc163** [comment]
傻瓜式的重现步骤。。。

**Comment by xiebin2014** [comment]
找到问题了，测试跟正式打包的antdesign版本不一样，组件样式不一样了

**Comment by xiebin2014** [comment]
![comc3 kc0jwi j 5ne6 9 q](https://cloud.githubusercontent.com/assets/6446527/18154968/a868851c-703b-11e6-8bd6-9095cbc63d22.png)
![rrrna58e0bb d6_xkvx45 j](https://cloud.githubusercontent.com/assets/6446527/18154969/a86ce30a-703b-11e6-91d8-9fddd89136c4.png)

**Comment by afc163** [comment]
对，做了更新。:smile:
