### ISSUE TITLE
Background style elements on ant-col do not get set

### ISSUE THREAD

**Issue by dkindler** [ant-design/ant-design#29081]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/dnkr/pen/JjbPPQY?editors=0011](https://codepen.io/dnkr/pen/JjbPPQY?editors=0011)

### Steps to reproduce
N/A, just render the page.

### What is expected?
Setting the following style on Col:
```
                    <Col span={12}
                         style={
                             {
                                 height: "100%",
                                 backgroundRepeat: "none !important",
                                 backgroundSize: "cover !important",
                                 backgroundPosition: "center !important",
                                 background: "url(https://images.unsplash.com/photo-1592085198739-ffcad7f36b54?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1275&q=80)"}
                         }
                    />
```
Should set the following on the Col in css:
```
backgroundRepeat: "none !important",
backgroundSize: "cover !important",
backgroundPosition: "center !important",
```

### What is actually happening?
These are not set. Only background and height.
![Screen Shot 2021-01-27 at 9 22 27 AM](https://user-images.githubusercontent.com/26625/106004535-4fc09180-6081-11eb-95ae-7d76c1999ec0.png)

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | ^17.0.1 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/facebook/react/issues/1881#issuecomment-542656865

https://codepen.io/afc163/pen/NWbKaya?editors=0011
