### ISSUE TITLE
Table component title adds scrollbar or popover menu.

### ISSUE THREAD

**Issue by yelaisi** [ant-design/ant-design#29087]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It solves the problem that when placing multiple buttons in the header of the table component, the width of the page shrinks and the other buttons will not be hidden.
Like the tabs component, tabpane can be dragged when the page is shrunk

在查询页面中，解决了表格组件标题中放置多个按钮时，页面宽度缩小时不会隐藏其他按钮.
像 Tabs 组件一样.页面缩小时 子组件TabPane可以拖拉

### What does the proposed API look like?
Add the title type, which is text or buttons.
增加标题类型，类型为文本或按钮.

**Comment by afc163** [comment]
title 可以是 ReactNode。
