### ISSUE TITLE
Unable to set field value for structured form

### ISSUE THREAD

**Issue by Abhikumar98** [ant-design/ant-design#29097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-methods-antd4112-forked-8629f?file=/index.js)

### Steps to reproduce
Change the Gender

### What is expected?
The behavior should be exactly like how it is shown in this example
https://ant.design/components/form/#components-form-demo-control-hooks

### What is actually happening?
The form fields aren't changing.

| Environment | Info |
|---|---|
| antd | 4.8.4 |
| React | 16.13.1 |
| System | mac OS: 10.14.6 |
| Browser | Chrome 86.0.4240.111 |

**Comment by zombieJ** [comment]
https://ant.design/components/form/#How-does-name-fill-value-when-it's-array

**Comment by Abhikumar98** [comment]
@zombieJ I've tried those as well.
https://codesandbox.io/s/form-methods-antd4112-forked-8629f?file=/index.js
still the fields aren't getting updated

**Comment by Abhikumar98** [comment]
got the solution, 
Similarly using setFieldsValue has changed from:

// antd v3
```
this.formRef.current.setFieldsValue({
  'user.0.firstname': 'John',
});

```
To

// antd v4
```
this.formRef.current.setFieldsValue({
  user: [
    {
      firstname: 'John',
    },
  ],
});
```
