### ISSUE TITLE
走马灯（initialSlide-slickGoTo）

### ISSUE THREAD

**Issue by yzflhez** [ant-design/ant-design#2909]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

#### 你做了什么？
走马灯

#### 你期待的结果是：
设置initialSlide={this.state.initNumber}设置不为0时，设置slickGoTo={this.state.number}操作走马灯

#### 实际上的结果：
当初始值initialSlide={this.state.initNumber}设置不为0时，设置slickGoTo={this.state.number}为0时无动作

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by yzflhez** [comment]
import React from 'react';
import './index.less';
import { Carousel, Modal, Icon} from 'antd';

let changNumber = 0;
let onoff = false;

export default class CreateCarousel extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      number: 0, // 控制跳到某一图片
      visible: true, // 是否可见
      imgData: [1, 2, 3], // 图片数据
      initNumber: 1, // 初始图片展示-测试更改下
      width: 500, // 图片的宽
      height: 300, // 图片的高
    };
  }
  componentWillMount() {
    changNumber = this.state.initNumber;
    if (this.state.initNumber !== 0) {
      onoff = true;
    }
  }
  cancel() {
    this.setState({
      visible: false,
    });
  }
  afterChange(current) {
    changNumber = current;
  }
  button( e ) { // 测试初始设置为零-bug
    this.setState({
      number: e,
    });
    setTimeout(() => {
      this.setState({
        number: 0,
      });
    }, 100);
  }
  buttonLeft() {
    const nowLeftLength = this.state.imgData.length;
    if (onoff && changNumber === 1) {
      this.button( changNumber );
    } else {
      setTimeout(() => {
        if (changNumber === 0) {
          this.setState({
            number: nowLeftLength - 1,
          });
          changNumber = nowLeftLength - 1;
        } else {
          this.setState({
            number: changNumber - 1,
          });
          changNumber = changNumber - 1;
        }
      }, 200);
    }
    onoff = false;
  }
  buttonRight() {
    const nowRighttLength = this.state.imgData.length;
    if (onoff && changNumber === nowRighttLength - 1) {
      this.button( changNumber );
    } else {
      setTimeout(() => {
        if (changNumber === nowRighttLength - 1) {
          this.setState({
            number: 0,
          });
          changNumber = 0;
        } else {
          this.setState({
            number: changNumber + 1,
          });
          changNumber = changNumber + 1;
        }
      }, 200);
    }
    onoff = false;
  }
  styleFn( h, w ) {
    let style = {};
    const top = h / 2;
    if (w) {
      style = {
        height: h,
        width: w,
      };
    } else {
      style = {
        top: top,
      };
    }
    return style;
  }
  render() {
    const imgStyle = this.styleFn( this.state.height, this.state.width);
    const styleTop = this.styleFn(this.state.height);
    return (<div className="contentMain">
      <Modal
        visible={this.state.visible}
        onCancel={this.cancel.bind(this)}
        footer={null}
        className="modalClass"
        width={this.state.width}
      >
        <div className="modalContent">
          <div className="modalContentArrow" style={styleTop}>
            <div onClick={this.buttonLeft.bind(this)}>
              <Icon type="left" className="modalContentArrowLeft"/>
            </div>
            <div onClick={this.buttonRight.bind(this)}>
              <Icon type="right" className="modalContentArrowRight"/>
            </div>
          </div>
          <Carousel
            beforeChange={this.beforechange}
            afterChange={this.afterChange}
            slickGoTo={this.state.number}
            initialSlide={this.state.initNumber}
            style={{background: 'rgb(255,255,255)'}}
          >
            {this.state.imgData.map(( i ) => {
              return (
                <div key={i} style={imgStyle} className="modalClassCarouselImg">
                  <img src={i} className="modalClassCarouselImgContent"/>
                </div>
              );
            })}
          </Carousel>
        </div>
      </Modal>
    </div>);
  }
}

**Comment by benjycui** [comment]
在线 demo 和重现步骤，谢谢。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by jljsj33** [comment]
slickGoTo 是要被废弃的。。。用 `this.refs[youSlickRef].slickGoTo(number)`；

**Comment by jljsj33** [comment]
https://github.com/akiran/react-slick#methods
