### ISSUE TITLE
Parent is not disabled when all children are disabled

### ISSUE THREAD

**Issue by habeebahmed** [ant-design/ant-design#29109]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elziy?file=/index.js)

### Steps to reproduce
add disable in all children in treeData
after disable all children, still parent is enabled

### What is expected?
I think we need to disable parent if all it's children are disabled

### What is actually happening?
parent node is not disabled

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.3.1 |
| System | latest |
| Browser | latest |

**Comment by afc163** [comment]
You can control it by youself.

**Comment by habeebahmed** [comment]
how ?
