### ISSUE TITLE
JSX cant recongnize components imported from antd in .tsx file(initialized using create-react-app xxx --typescript) ts项目中无法识别引入的antd组件

### ISSUE THREAD

**Issue by coderlastxuan** [ant-design/ant-design#29102]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
按antd官网ts初始化项目 引入组件后jsx里无法识别
following instructions in antd homepage， wroto <Button> in .tsx but can not compile.

import React, {FC} from 'react';
import { Button } from 'antd';

const App: FC = () => (
    <div className="App">
      <Button type="primary">Button</Button>
    </div>
);

export default App;

got: TS2604: JSX element type 'Button' does not have any construct or call signatures

### What is expected?
compiled

### What is actually happening?
TS2604: JSX element type 'Button' does not have any construct or call signatures

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | react@17.0.1 |
| System | win10 |
| Browser | chrome88 |

**Comment by coderlastxuan** [comment]
![image](https://user-images.githubusercontent.com/59820027/106167067-cb2c5b00-61c7-11eb-9c04-b6f12b7b61f2.png)

**Comment by coderlastxuan** [comment]
![image](https://user-images.githubusercontent.com/59820027/106167226-f4e58200-61c7-11eb-9f99-7adef7167460.png)

**Comment by goldenjayr** [comment]
I am getting the same issue..

**Comment by JesseCHN** [comment]
I also have the same issue!
JSX element type 'Dropdown.Button' does not have any construct or call signatures.  TS2604
  > 15 |             <Dropdown.Button style={{ marginLeft: 15 }}>
  
 JSX 元素类型“Button”不具有任何构造签名或调用签名。ts(2604)
 
When I use // @ts-nocheck, the project runs successfully

**Comment by yihuaiahi** [comment]
我也遇到了这个问题，怎么解决的啊

**Comment by chuliang014** [comment]
any update on this?

**Comment by stargazerkiyoshi** [comment]
同样的问题，只是按照官网教程做，并没有自定义什么
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/42559607/155270567-6758cfaf-d482-4922-be6c-fa3e960d923c.png">

**Comment by TONYbad123** [comment]
同问，尝试更新react-dom版本，以及其它方法，都没有效果
