### ISSUE TITLE
Affix 在左右可滚动的容器内fixed时left位置原dom位置不一致

### ISSUE THREAD

**Issue by chocking** [ant-design/ant-design#29108]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-affix-left-position-tqsmg)

### Steps to reproduce
把容器滚动到最右边，然后往下滚动使Affix变为fixed状态，原dom的left应该在视野之外，但Affix会使用默认的left:0展示在视野内。
如果Affix只关注offsetTop和offsetBottom的话，应该在监听滚动时和原dom的left位置保持一致

### What is expected?
left位置和原dom保持一致

### What is actually happening?
left位置和原dom不一致

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | react latest |
| System | macOS 10.15.7 |
| Browser | chrome 88.0.4324.96 |

---
左右滚动的页面使用Affix组件作为footer，Affix组件fixed时left位置会与原位置不对齐

**Comment by Eating-Eating** [comment]
这个affix好像不止这个bug，官网上容器案例里滚动容器affix吸顶之后滚动window，那个affix就跑到外面去了

**Comment by afc163** [comment]
@chocking 看看交互是什么样的比较合适。https://github.com/ant-design/ant-design/pull/30528#issuecomment-842048962

**Comment by chocking** [comment]
> @chocking 看看交互是什么样的比较合适。[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528#issuecomment-842048962)

呃，我的直观感觉是上下滚动时只影响是否fixed，左右滚动时left和placeholder.getBoundingClientRect().left保持一致，所以对于[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528)，左右滚动应该是不取消fixed的

**Comment by zyxbb** [comment]
> > @chocking 看看交互是什么样的比较合适。[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528#issuecomment-842048962)
> 
> 呃，我的直观感觉是上下滚动时只影响是否fixed，左右滚动时left和placeholder.getBoundingClientRect().left保持一致，所以对于[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528)，左右滚动应该是不取消fixed的

你好，上下滚动处于`fixed`时，再水平滚动，如果不移除`fixed`，即使left一致，也会显示在容器上面，不能隐藏呢

**Comment by chocking** [comment]
> > > @chocking 看看交互是什么样的比较合适。[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528#issuecomment-842048962)
> > 
> > 
> > 呃，我的直观感觉是上下滚动时只影响是否fixed，左右滚动时left和placeholder.getBoundingClientRect().left保持一致，所以对于[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528)，左右滚动应该是不取消fixed的
> 
> 你好，上下滚动处于`fixed`时，再水平滚动，如果不移除`fixed`，即使left一致，也会显示在容器上面，不能隐藏呢

em，确实，就算不移除fixed，上下滚动触发fixed交替也会有闪烁覆盖容器的现象。这样看来只能提示用户不要用在横向滚动的容器里，或者自己用sticky实现了(不过当初我们是因为父级上的某些样式影响了导致sticky不生效才使用Affix的。。)

**Comment by zyxbb** [comment]
> > > > @chocking 看看交互是什么样的比较合适。[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528#issuecomment-842048962)
> > > 
> > > 
> > > 呃，我的直观感觉是上下滚动时只影响是否fixed，左右滚动时left和placeholder.getBoundingClientRect().left保持一致，所以对于[#30528 (comment)](https://github.com/ant-design/ant-design/pull/30528)，左右滚动应该是不取消fixed的
> > 
> > 
> > 你好，上下滚动处于`fixed`时，再水平滚动，如果不移除`fixed`，即使left一致，也会显示在容器上面，不能隐藏呢
> 
> em，确实，就算不移除fixed，上下滚动触发fixed交替也会有闪烁覆盖容器的现象。这样看来只能提示用户不要用在横向滚动的容器里，或者自己用sticky实现了(不过当初我们是因为父级上的某些样式影响了导致sticky不生效才使用Affix的。。)

@afc163 要更新文档给用户提示吗？

**Comment by afc163** [comment]
可以。Affix 一般也只适用于单向滚动的区域。

**Comment by afc163** [comment]
close by https://github.com/ant-design/ant-design/pull/30775
