### ISSUE TITLE
更新表单项验证规则 (update form rules)

### ISSUE THREAD

**Issue by tvrcgo** [ant-design/ant-design#2910]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：windows 10
- 浏览器及其版本: chrome 52.0.2743.116

#### 你做了什么？

render 方法中有个表单项，设置了双向绑定和校验规则
```js
<Select multiple {...getFieldProps('more_list', { initialValue: items.more_list, rules: [{ required: moreListRequired, type: 'array', min: 1 }] })} />
```

其中 required 必填校验通过变量 moreListRequired 设置，默认为 false。moreListRequired 在 render 方法中设置的。

#### 你期待的结果是：

当用户调整表单中的选项，将 moreListRequired 设为 true，more list 变为必填。

#### 实际上的结果：

moreListRequired 的值已经变了，通过 getFieldProps('more_list') 获取到的值也已经变了，但是呈现出来的控件的 required 状态没变化。

![image](https://cloud.githubusercontent.com/assets/237062/18156611/02c1a36e-704a-11e6-94ba-911209d7aa96.png)

#### 可重现的在线演示

暂无

**Comment by benjycui** [comment]
。。。。。略抽象。。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by tvrcgo** [comment]
```js
const { Select } = antd;

const Option = Select.Option

const App = React.createClass({
  
  render() {
    const { getFieldProps } = this.props.form
    
    const moreListRequired = getFieldProps('list_type').value === 1
    
    return (
      <div>
        <Select {...getFieldProps('list_type', {})} >
          <Option value={1}>1</Option>
          <Option value={2}>2</Option>
        </Select>
        <Select multiple {...getFieldProps('more_list', { initialValue: items.more_list, rules: [{ required: moreListRequired, type: 'array', min: 1 }] })} />
      </div>
    );
  }
});

ReactDOM.render(<App />, document.getElementById('container'));
```

**Comment by benjycui** [comment]
实测动态修改校验规则是可行的，如果你还有问题，麻烦提供可重现的在线 demo

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
