### ISSUE TITLE
AutoComplete 输入中文 onChange 触发两次

### ISSUE THREAD

**Issue by Pedestrian93** [ant-design/ant-design#29101]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyixuanxiang-antd4112-forked-2uefs?file=/index.js)

### Steps to reproduce
中文输入法录入拼音后按空格键

### What is expected?
onChange 触发一次

### What is actually happening?
onChange 触发一次

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Mac OS BigSur |
| Browser | Chrome87 |

---
测试版本 4.10.0 开始出现这个问题

**Comment by zombieJ** [comment]
你的重现里没有看到 `onChange`

**Comment by Pedestrian93** [comment]
> 你的重现里没有看到 `onChange`

链接放错了，已更新

**Comment by jueinin** [comment]
这个问题[https://github.com/ant-design/ant-design/issues/28564](url)似乎跟这个issue相关，原因是在onInputCompositionEnd中调用了triggerOnSearch @zombieJ
