### ISSUE TITLE
DatePicker打开选择年份的面板以后，此刻按钮点了没用呢？

### ISSUE THREAD

**Issue by wood3n** [ant-design/ant-design#29119]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bukexuanzeriqiheshijian-antd4112-forked-3yg66)

### Steps to reproduce
打开DatePicker的年份面板，点击此刻按钮，无反应

![image](https://user-images.githubusercontent.com/31716713/106255580-2b1d1300-6255-11eb-90f5-23db7be583d2.png)

### What is expected?
打开DatePicker的年份面板，点击此刻按钮，应该选择当前时间

### What is actually happening?
打开DatePicker的年份面板，点击此刻按钮，无反应

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.14 |
| System | window10 1909 |
| Browser | Chrome 88 latest |

**Comment by yoyo837** [comment]
now只对时间选择面板出现时有用，对年和月面板无效，看是不是应该在年月面板时禁用呢？🤔

**Comment by wood3n** [comment]
> now只对时间选择面板出现时有用，对年和月面板无效，看是不是应该在年月面板时禁用呢？🤔

这个能通过props禁用吗？

**Comment by yoyo837** [comment]
`showToday`

**Comment by wood3n** [comment]
> `showToday`

也没用啊 🤣

**Comment by wood3n** [comment]
此刻还在

**Comment by yoyo837** [comment]
`showToday={false}` 不行？来个链接

**Comment by wood3n** [comment]
@yoyo837  https://codesandbox.io/s/bukexuanzeriqiheshijian-antd4112-forked-tdn2m

**Comment by wood3n** [comment]
是不是 `showNow` 啊

**Comment by wood3n** [comment]
`showNow` 全都干掉了

**Comment by yoyo837** [comment]
我搞错了，showToday 是控制日期的Today的

**Comment by yoyo837** [comment]
showNow 满足你吗？

**Comment by yoyo837** [comment]
你再组合一下 onPanelChange 控制一下showNow

**Comment by wood3n** [comment]
@yoyo837 还阔以

```
  onPanelChange={(_, mode) => {
    if (mode !== 'date') {
      setShowNow(false);
    } else {
      setShowNow(true);
    }
  }}
```

**Comment by wood3n** [comment]
@yoyo837 还阔以

```
  showNow={showNow}
  onPanelChange={(_, mode) => {
    setShowNow(mode === 'date')
  }}
```

**Comment by yoyo837** [comment]
有新问题另开，先关了。
