### ISSUE TITLE
antd4.x table ColumnProps type error，ColumnProps ts类型错误

### ISSUE THREAD

**Issue by ElsaOOo** [ant-design/ant-design#29114]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/table/Column.tsx](https://github.com/ant-design/ant-design/blob/master/components/table/Column.tsx)

### Steps to reproduce
ts error: The expected type comes from property 'children' which is declared here on type 'ColumnProps<DataSource>'

### What is expected?
export interface ColumnProps<RecordType> extends ColumnType<RecordType> {
    children?: ColumnProps<RecordType>[];
}

### What is actually happening?
export interface ColumnProps<RecordType> extends ColumnType<RecordType> {
    children?: null;
}

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome 86 |

**Comment by zombieJ** [comment]
Use [`ColumnsType`](https://github.com/ant-design/ant-design/blob/f1568a656ae41a96689da54b153e0dafc4ce67fb/components/table/index.tsx#L4) instead. Table.Column do not have `children`.
