### ISSUE TITLE
menu mode 改变，openkeys无效

### ISSUE THREAD

**Issue by juanpengke** [ant-design/ant-design#2911]
#### 本地环境 

- antd 版本: 1.10.0
- 操作系统及其版本： mac 10.11.6
- 浏览器及其版本: chrome 50

#### 你做了什么？
menu 在同时设置了defaultOpenkeys 和 openkeys  后 设置mode="inline" 不会弹出子菜单

#### 你期待的结果是：
设置了defaultOpenkeys 和 openkeys  后 设置mode="inline" 弹出子菜单

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by juanpengke** [comment]
http://codepen.io/anon/pen/ambwgj?editors=0011   
mode=vertical 时，点击submenu 需要鼠标移出才能触发展开/收起 子菜单
mode="inline"  不点击，移出子菜单  子菜单不隐藏

**Comment by afc163** [comment]
1. 见 https://github.com/ant-design/ant-design/issues/2701
2. defaultXxx 和 Xxx 不能混用，自行研习 react 受控组件概念。http://facebook.github.io/react/docs/forms.html#controlled-components
