### ISSUE TITLE
在TreeSelect 组件中使用dropdownRender，dropdownRender里受控Input的值的改变会触发TreeSelect 的onChange事件，而onChange的参数value值会减少

### ISSUE THREAD

**Issue by yutian0414** [ant-design/ant-design#29128]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
<TreeSelect
                ref={treeSelectRef}
                dropdownClassName={styles.componentsSelect}
                labelInValue
                allowClear
                treeCheckable
                multiple
                treeIcon
                treeNodeLabelProp="label"
                maxTagCount={10}
                loadData={onLoadData}
                onChange={e=>{console.log('onChange',e); onChange(e);}}
                value={value}
                placeholder='请选择或搜索安装组件'
                onFocus={getSelectOptions}
                dropdownRender={menu => (
                    <div>
                        <div onClick={e => e.stopPropagation()}>
                            <Input.Group compact>
                                <Select style={{ width:'88px' }} onChange={searchCategoryChange} value={searchCategory} id='categorySelect' size='small'>
                                    <Select.Option value="component" id="categorySelect_component">搜组件</Select.Option>
                                    <Select.Option value="product" id="categorySelect_product">搜产品</Select.Option>
                                </Select>
                                <Input style={{ width: 'calc(100% - 88px)', height:'24px' }} value={searchKey} onChange={searchKeyChange} size='small'/>
                            </Input.Group>
                        </div>
                        {menu}
                    </div>
                )}
            >
                {searchCategory === 'product' && ProductTreeNodes}
                {searchCategory === 'component' && ComponentTreeNodes}
            </TreeSelect>

当Input的值发生改变的时候，会触发TreeSelect 的onChange事件，而打印出来的onChange事件的值，会比初始值减少一个

### What is expected?
dropdownRender内部的非TreeSelect.TreeNode 节点不触发onChange事件，如果触发，值也不应该发生变化

### What is actually happening?
dropdownRender内添加的受控Input的value发生变更后，触发了TreeSelect的onChange事件，而且值发生了变更，原来多个值，每次变更后都会少一个值（TreeSelect为多选模式）

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.14.0 |
| System | window |
| Browser | chrome  88.0.4324.104 |

**Comment by yutian0414** [comment]
可以看一下这个里面的，[https://github.com/yutian0414/issue_reproduce](https://github.com/yutian0414/issue_reproduce)

当退格逐个删除dropdownRender 下的input里的值时，出发了TreeSelect的onchange事件，而默认的TreeSelect的值，每次减少一个

**Comment by Frame777777** [comment]
我遇到同样的情况，dropdownRender里面的Input删除字符，会出发Select的onChange，每次删除Select的一个值，我的mode是multiple

**Comment by keepwe** [comment]
我在官网https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu下的扩展菜单下也遇到了相同的问题。 设置mode为多选时，选中多个的情况下再在input框中输入字符 删除字符首先会触发删除选中项的现象。调试发现，dropdownRender 中的input输入框在多选模式 会首先触发select的onchange事件，删除字符也会触发onDeselect事件，删完之后 input的onchange事件才会继续执行。

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/28694#issuecomment-754471826
