### ISSUE TITLE
Modal.xxxx (eg. warning) 按钮的处理事件中, 如何根据 onOk 根据处理结果选择关闭或不关闭窗口?

### ISSUE THREAD

**Issue by LaPoPvLe** [ant-design/ant-design#2912]
#### 本地环境

- antd 版本: antd@1.10.0
- 操作系统及其版本：Windows 10
- 浏览器及其版本: chrome 52.0.2743.116 m (64-bit)

#### 你做了什么？

在 Modal.warning 的 onOk 中返回了一个 promise 调用服务器, 当正常时候 resolve, 如果未成功, 则 reject.

#### 你期待的结果是：

根据文档 [对话框](http://ant.design/components/modal/) 中 `onOk` 的说明, 返回 resolve 时, 窗口关闭.  出错时 reject, 窗口不关闭.
#### 可重现的在线演示
尝试使用 reject 后, 浏览器会提示 uncaught(in promise). 在查看源码时发现, 只有 then 处理, 并没有 catch. 不太清楚是否是这个引起的.

**Comment by afc163** [comment]
是否这个问题？https://github.com/ant-design/ant-design/issues/2684

@benjycui

**Comment by LaPoPvLe** [comment]
不完全是, 不过 都是 因为 Modal 与 Modal.xxxx 方法间的使用的差异引起的混乱
在 Modal 中我能控制按钮点击后的 Modal 状态: 如 loading 状态, 以及通过 父组件的 state 状态来维护 Modal 的显示状态(我碰到的问题主要是显示的控制方面).

我又看了下源码, 感觉 Modal.xxxx 更加符合的场景应该是类似 源生 alert 一样, 仅仅是提示作用吧. 确认在 onOk 的事件中, 如果reject 在 Modal.xxxx 中并没有处理, 将会关闭窗口并抛出异常.

**Comment by benjycui** [comment]
组件不需要改，在返回 Promise 之前，开发都自行处理异常即可，无论 resolve 还是 reject，Modal 都会关闭。
