### ISSUE TITLE
Select多选模式，当组件位置变化后，下拉框未跟随

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#29124]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhaopianqiang-antd4112-forked-rshqc?file=/index.js)

### Steps to reproduce
多选里面随便选一个

### What is expected?
下拉框跟随

### What is actually happening?
下拉框未跟随

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.12 |
| System | Windows 10 |
| Browser | 谷歌浏览器、QQ浏览器 |

**Comment by phoema** [comment]
![image](https://user-images.githubusercontent.com/8730272/106346005-d037fa00-62ee-11eb-9694-0dc69b3a88fe.png)

**Comment by afc163** [comment]
外部变化 Select 很难感知，这种情况只能直接跟随内部容器了。

https://codesandbox.io/s/zhaopianqiang-antd4112-forked-73c37?file=/index.js

**Comment by phoema** [comment]
好用，抱歉，文档还是没看全。
