### ISSUE TITLE
new branch trigger gitee

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#29120]
每次新建分支都触发 Gitee，可以优化一下~

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/master/.github/workflows/mirror.yml

**Comment by xrkffgg** [comment]
@afc163 是不是改成特定的一些分支 比较好？

**Comment by afc163** [comment]
可以，gh-pages/master/feature/2.x-stable/3.x-stable 等分支就够了。
