### ISSUE TITLE
checkbox获取是否选中

### ISSUE THREAD

**Issue by jingxiawl** [ant-design/ant-design#2913]
我用了` <Checkbox    {...getFieldProps('YI',{trigger:'onChange',valuePropName:"checked",onChange:this.onToggleShow.bind(this)})}/>`
                             结果在onToggleShow里面获取getFieldProps('YI').value打印出来是undefined，然后我在render里面也有一个打印getFieldProps('YI').value是true.到底checkbox如何获取值？

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by jingxiawl** [comment]
@benjycui
 `const { DatePicker,Checkbox,Form} = antd;

let App = React.createClass({
  getInitialState() {
    return {
      test: true,
    };
  },
  onToggleShow(){
     const { getFieldProps } = this.props.form;
    console.log(getFieldProps("hobby").value);
    this.setState({test:!this.state.test})
  },
  render() {
    const { getFieldProps } = this.props.form;
     console.log("***"+getFieldProps("hobby").value);
    return (
      <div style={{margin: 10}}>
        
        <Checkbox {...getFieldProps('hobby',{trigger:"onChange",valuePropName:"checked",onChange:this.onToggleShow})}/>lsssl
      </div>
    );
  }
});
App = Form.create()(App);
ReactDOM.render(<App />, document.getElementById('container'));`
示例地址：http://codepen.io/wLing/pen/zKYvWp?editors=001

**Comment by benjycui** [comment]
> 结果在onToggleShow里面获取getFieldProps('YI').value打印出来是undefined

年轻人，你怎么会有这种想法，太可怕了。因为 React state 的原因，所以你会拿到之前的值。

既然你已经监听了 onChange 事件，就直接从 onChange 的参数 e.target.checked 里面拿就是。

最后建议学习下 Markdown 的格式。
