### ISSUE TITLE
"Select" component in "tags" mode should permit suppression of already-selected tags from the dropdown

### ISSUE THREAD

**Issue by mxye** [ant-design/ant-design#29135]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
With "tags" mode of the Select component, currently as you select/create multiple items, these items are not removed from the dropdown list; it just marks those items as 'selected'.

This creates visual clutter: if a tag is already displayed in the search/tags input, then why does it need to be displayed again in the dropdown? It's aesthetically displeasing, if in your use case you prefer to have a cleaner look. Most of the other websites with the tags search/create function don't seem to display already-selected tags in the dropdown, only in the input box; so this isn't an unusual preference. There is currently no way to remove these from the dropdown list. If there exists a way to do it without adding a feature, please provide a mini example. I've looked everywhere and can't find that in the documentation. 

### What does the proposed API look like?
Provide the following as an option: when tags are selected, they are displayed in the input box, but not in the dropdown list again.

**Comment by afc163** [comment]
A simple trick is hiding the selected option: https://codesandbox.io/s/biaoqian-antd4112-forked-f82f4?file=/index.css

**Comment by mxye** [comment]
I confirm this works (in my code I also had to add "!important" to override the default in css). Thank you!!
