### ISSUE TITLE
Table 在设置了 scroll 属性后，如果每一列都设置了列宽，这时 resize 表格宽度，会明显卡顿

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design#29138]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/chairui2001/pen/BaQyRrj](https://codepen.io/chairui2001/pen/BaQyRrj)

### Steps to reproduce
见 codepen，将浏览器窗口化，拖动改变浏览器宽度。
当出现横向滚动条时，卡顿不明显；而当不出现横向滚动条时，卡顿明显。
猜测是因为 resize 过程中不断计算调整每列的列宽导致（因为全部列都设了宽度时，是按比例分配列宽）
如果去掉 scroll 属性或者至少有一列未设置宽度，则不卡顿。

### What is expected?
Table 在全部列都设了宽度（为了在不同尺寸屏幕下能按比例显示各列宽），且使用了 scroll 属性时，resize 表格宽度不至于太卡顿。

### What is actually happening?
Table 在全部列都设了宽度，且使用了 scroll 属性时，resize 表格宽度会明显卡顿。

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.1 |
| System | win7 |
| Browser | Chrome 86.0.4240.183 |

---
在常见布局中，左侧菜单折叠展开，引起右侧表格（每一列都设了宽度，且使用了 scroll 属性）宽度改变时，就会出现如上性能问题。

**Comment by edc-hui** [comment]
我也遇到了这个问题，尤其是当表格的列数和行数多的时候，页面就卡成ppt了。找了之前的issue都没找到解决方案。

**Comment by afc163** [comment]
see https://github.com/ant-design/ant-design/issues/28214

**Comment by afc163** [comment]
Duplicate of #27775

**Comment by Azir1** [comment]
遇到了同样的问题……
