### ISSUE TITLE
Missing Russian localization for Image component

### ISSUE THREAD

**Issue by kirilllyalin** [ant-design/ant-design#29145]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4wwd5?file=/index.js)

### Steps to reproduce
- Create an Image component
- Wrap it in a ConfigProvider and set a Russian locale 
- Hover over Image component

It is necessary to translate the "Preview" text into a similar one in Russian (as an example, "Превью")

### What is expected?
"Preview" should be localized to the Russian word

### What is actually happening?
The string is only translated into Chinese and English

| Environment | Info |
|---|---|
| antd | 4.8.6 |
| React | 16.8.6 |
| System | Windown 10 Pro 2004 |
| Browser | Google Chrome 88.0.4324.104 |

**Comment by qramilq** [comment]
work on it
