### ISSUE TITLE
noticeable delay when making the visibility of a Collapse hidden

### ISSUE THREAD

**Issue by tracyhenry** [ant-design/ant-design#29146]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/noticeable-delay-when-setting-a-collapse-to-invisible-8my5b?file=/index.js)

### Steps to reproduce
Expand all three panels. Then hit "Click me" to hide the collapse (by setting css visibility to hidden)

### What is expected?
The collapse disappear immediately. There is no noticeable delay. 

### What is actually happening?
The body of the collapse and the panel texts disappear first, before the panel titles disappear. There is a noticeable delay in between. 

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.14.0 |
| System | Mac OS |
| Browser | Chrome |

**Comment by xrkffgg** [comment]
See https://codesandbox.io/s/noticeable-delay-when-setting-a-collapse-to-invisible-forked-8tvbd?file=/index.js

**Comment by tracyhenry** [comment]
> See https://codesandbox.io/s/noticeable-delay-when-setting-a-collapse-to-invisible-forked-8tvbd?file=/index.js

Thanks, great workaround. IMHO the default behavior should be without the transition though.

**Comment by xrkffgg** [comment]
@zombieJ The default `transition` is necessary?
