### ISSUE TITLE
功能不起作用

### ISSUE THREAD

**Issue by flows1314** [ant-design/ant-design#29143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel](https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel)

### Steps to reproduce
table中的自定义筛选菜单功能中的 confirm({ closeDropdown: false })没有起作用

### What is expected?
解决这个bug

### What is actually happening?
无论加还是不加这行 confirm({ closeDropdown: false })代码都没有用

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | react |
| System | win10 |
| Browser | 谷歌 |

**Comment by yoyo837** [comment]
是具体什么功能没起作用？

**Comment by xrkffgg** [comment]
Filter 按钮加了这个功能，并且起作用的。

**Comment by flows1314** [comment]
给函数&nbsp;confirm&nbsp;添加&nbsp;boolean&nbsp;类型参数&nbsp;closeDropdown，是否关闭筛选菜单，默认为&nbsp;true。
我这边拉取相同代码测试发现没有作用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 上午10:59
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"lamer"<1778238738@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 功能不起作用 (#29143)





 
是具体什么功能没起作用？

**Comment by flows1314** [comment]
给函数 confirm&nbsp;添加 boolean&nbsp;类型参数 closeDropdown，是否关闭筛选菜单，默认为 true。
我这边拉取相同代码测试发现没有作用







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 上午10:59
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"lamer"<1778238738@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 功能不起作用 (#29143)





 
是具体什么功能没起作用？

**Comment by flows1314** [comment]
我把react和react-dom更新到最新版本以后，问题就解决了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 中午11:08
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"lamer"<1778238738@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 功能不起作用 (#29143)





 
Hello @flows1314. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 3 days.
 
你好 @flows1314, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
