### ISSUE TITLE
Image组件优化图片缩放逻辑

### ISSUE THREAD

**Issue by HEJIN2016** [ant-design/ant-design#29156]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.通过参数配置，是否需要在Image点开的时候，拖拽的时候停留在拖拽的位置，而不是弹回原来的位置。在后台管理系统中，部分需求需要将当前预览的图片拖移动到页面边缘位置

2.预览的图片支持缩小。当前的预览图片组件的缩小功能，只有在将原有图片放大时才可用，建议去除此限制。即便图片是原有像素，也应该支持缩小。

### What does the proposed API look like?
1.通过参数，配置拖拽时是否需要弹回原来的位置

2.图片缩小功能不应该只在图片大于原有尺寸时开放

**Comment by shaodahong** [comment]
触发弹回的点是图片长宽小于视口，移动到边缘位置不弹回的需求原因是什么呢

**Comment by HEJIN2016** [comment]
> 触发弹回的点是图片长宽小于视口，移动到边缘位置不弹回的需求原因是什么呢

在后台管理的系统，在审核用户信息的页面中有用户上传的身份图片，可能需要放大图片，然后拖拽到边缘位置，以便对比图片中的信息与原页面中显示的用户的信息是否一致

**Comment by shaodahong** [comment]
嗯，1 我看了下是个 bug

**Comment by shaodahong** [comment]
@HEJIN2016 https://github.com/react-component/image/pull/70 1 看下是不是这个情况，我修复了下

**Comment by HEJIN2016** [comment]
> @HEJIN2016 [react-component/image#70](https://github.com/react-component/image/pull/70) 1 看下是不是这个情况，我修复了下

是的，就是这种效果

**Comment by HEJIN2016** [comment]
hello，这个问题还没修复吗 @shaodahong

**Comment by shaodahong** [comment]
> hello，这个问题还没修复吗 @shaodahong

已经修复了

**Comment by HEJIN2016** [comment]
> > hello，这个问题还没修复吗 @shaodahong
> 
> 已经修复了

https://ant.design/components/image-cn/，我看官网的例子，拖拽的时候还是会弹回去？

**Comment by HEJIN2016** [comment]
@shaodahong 我用的最新版ant4.13.0，还是有这个问题，官网的例子也是一样有这个问题

**Comment by xrkffgg** [comment]
修复的是 弹回边界问题，不是说不弹回

**Comment by xrkffgg** [comment]
修复的是 弹回边界问题，不是说不弹回

**Comment by xrkffgg** [comment]
修复的是 弹回边界问题，不是说不弹回

**Comment by HEJIN2016** [comment]
> 修复的是 弹回边界问题，不是说不弹回

如果每次拖拽都自动弹回中心位置的话，那你们做这个拖拽功能的作用是什么？

**Comment by shaodahong** [comment]
> > 修复的是 弹回边界问题，不是说不弹回
> 
> 如果每次拖拽都自动弹回中心位置的话，那你们做这个拖拽功能的作用是什么？

嗯，这是我设计的，我的想法是图片尺寸小于视口没有必要做位移，可以拖拽是大于的情况下，因为正中心位置是最佳的，当然有业务需求我可以看看
