### ISSUE TITLE
iOS | Datepicker inside Modal page refreshes

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#29151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-kepler-206vn)

### Steps to reproduce
1. Click on Open Modal button
2. Click on Date Picker within the modal
3. With calendar open, click inside the modal e.g. click at text "Some contents..."
4. Page crashes and refreshes.

### What is expected?
Calendar should close

### What is actually happening?
1. With calendar open, click inside the modal e.g. click at text "Some contents..."
2. Page crashes and refreshes.

I understand that the version (3.x) is off the maintenance period, we are in a phase of project where we can't upgrade to 4.x. Hence I request you to please look into this issue.

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | iOS |
| Browser | Safari, Chrome |

---
I understand that the version (3.x) is off the maintenance period, we are in a phase of project where we can't upgrade to 4.x. Hence I request you to please look into this issue.

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/28952

see https://github.com/ant-design/ant-design/issues/28952#issuecomment-770611096
