### ISSUE TITLE
Rangepicker rendering out of view when passing custom div in getPopupContainer

### ISSUE THREAD

**Issue by aditya-lw** [ant-design/ant-design#29152]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-hertz-49osy?file=/src/App.js)

### Steps to reproduce
Open the link and click on the date range multiple times. once in a while it won't render. This issues occurred after I upgrade and from 4.1.2 to 4.11.2 couple of days ago.

### What is expected?
Should render datepicker in the viewport on every click.

### What is actually happening?
Date picker is rendered out of viewport. 

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16 |
| System | linux 18 |
| Browser | chrome latest |

---
I checked in inspect elements and div with class 'ant-picker-dropdown ant-picker-dropdown-range' is setting inline style incorrectly which is making it render out of view.

**Comment by afc163** [comment]
https://github.com/react-component/trigger/pull/227

cc @rinick

**Comment by rinick** [comment]
@afc163  I've spent several hours on this, but still can't figure out.

CodeSandbax showing error in rc-trigger, because it has this
```html
<div onClick={() => handlePopup()} hasValue={selectedDate && selectedDate.length === 2} >
```
after removing the invalid `hasValue` attribute from div, there is no console error. So the issue might not be related to my change

@aditya-lw  could you narrow down the versions to figure out why version of antd starts to break that?  also is it possible for you provide a simpler test case

**Comment by aditya-lw** [comment]
@rinick Thanks for your efforts. I have figured out that it is working till 4.8.0 and breaks in 4.8.1. And this is the simplest possible reproducible test case. I don't know how I can simplify it any more. Thanks

cc @afc163

**Comment by rinick** [comment]
@afc163 4.8.0 and 4.8.1 both depend on rc-trigger 5.0.3, and my change was added in 5.2.0  
so it should be unrelated

@aditya-lw 
do you have a comparation of yarn.lock or package-locks file for those 2 cases(4.8.0 vs 4.8.1)? so we can see for sure which package broke it?

**Comment by afc163** [comment]
@aditya-lw Could you help to check whether this issue exists in `4.16.7`?

**Comment by zombieJ** [comment]
close since no more response.
