### ISSUE TITLE
IE特别卡的问题

### ISSUE THREAD

**Issue by haisapan** [ant-design/ant-design#2915]
#### 本地环境
Win10+IE11下Table等组件特别特别卡，基本没法使用，Chrome下没有问题。官网组件示例同样。可以使用[(http://ant.design/components/table/)] 测试

**Comment by kairi1227** [comment]
@afc163 请解决一下该问题。我们在使用Collapse组件中，同时展开多个panel时，有时候也会出现无法全部展开的问题。
图中红色区域其实是列表，当刷新后会展开，这种问题偶现。
![image](https://cloud.githubusercontent.com/assets/4525647/18301450/09f047ee-7504-11e6-8d74-d06cd4e942ea.png)

**Comment by afc163** [comment]
@kairi1227 建议单独开贴并给出在线的可重现演示。

**Comment by afc163** [comment]
@haisapan trace in #3096
