### ISSUE TITLE
可以开源antd官网的代码吗，想学习下文档、组件那个页面的写法

### ISSUE THREAD

**Issue by j5465** [ant-design/ant-design#29164]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如题，想学习官网的写法

### What does the proposed API look like?
无

**Comment by yoyo837** [comment]
在仓库里一起

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/tree/master/site
