### ISSUE TITLE
Slider - How to change the text in tooltip ?

### ISSUE THREAD

**Issue by denbalestri** [ant-design/ant-design#29165]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to change the text in tooltip to add, for example: Age: 30 years and so on. my idea is just add a text in tooltip with the number of the range.

The next picture shows how is slider now
![image](https://user-images.githubusercontent.com/26679851/106490395-88eb6e00-6494-11eb-84ee-01ee4439bb74.png)

I want something like the next picture
![image](https://user-images.githubusercontent.com/26679851/106490450-999be400-6494-11eb-9f95-e3988221d606.png)

### What does the proposed API look like?
Slider only show the number of the range that is clicked.

**Comment by afc163** [comment]
`tipFormatter`
