### ISSUE TITLE
Collapse title doesn't align vertically with button-based extra

### ISSUE THREAD

**Issue by tracyhenry** [ant-design/ant-design#29168]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/extra-node-antd4112-forked-1zrtw?file=/index.js)

### Steps to reproduce
Open the sandbox link. Make the browser panel narrower so you can compare the altitude of the titles and the buttons. 

### What is expected?
The button extra should be vertically aligned with the collapse title.

### What is actually happening?
The button extra is not vertically aligned with the collapse title. The collapse title is higher. This issue should exist with all button types. 

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.14.0 |
| System | Mac OS |
| Browser | Chrome/Safari |

**Comment by zombieJ** [comment]
It's by design. Arrow & Title is always take at the first paragraph line. But I think we may improve this.

ref #28507

**Comment by tracyhenry** [comment]
> It's by design. Arrow & Title is always take at the first paragraph line. But I think we may improve this.
> 
> ref #28507

but if an extra is an icon, it's vertically aligned with the title...

**Comment by Jeffmagma** [comment]
I have the same issue, even if this is by design, is there a way to manually adjust it so that it's aligned at the middle?

**Comment by monolithed** [comment]
Ran into the same problem

**Comment by afc163** [comment]
You could try Typograhpy.Link: https://codesandbox.io/s/extra-node-antd-4-11-2-forked-958kh2?file=/index.js
