### ISSUE TITLE
pageSize改变后，页码（pageIndex）会切换到第一页

### ISSUE THREAD

**Issue by Kang127** [ant-design/ant-design#29175]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/run](https://stackblitz.com/run)

### Steps to reproduce
1、将页码切换至第2页
2、将pageSize随意改变一个数字。此时pageIndex会变成1
3、Pagination组件中没有这个问题。
4、此测试过程是在官方实例中测试的 https://stackblitz.com/run

### What is expected?
pageSize改变后 pageIndex的值保持不变，该第几页就是第几页，如果pageIndx不够，则pageIndex为最后一页。

### What is actually happening?
pageSize改变后 pageIndex会变成第一页

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.0 |
| System | windows 10 |
| Browser | Google Chrome版本 86.0.4240.111（正式版本） （64 位） |

**Comment by afc163** [comment]
3.x 的表现是对的，我修正一下。
