### ISSUE TITLE
TreeSelect 多选状态下，如何只显示选中的数量而不是具体选中的内容？

### ISSUE THREAD

**Issue by rfox00** [ant-design/ant-design#2917]
#### 本地环境
- antd 版本: 1.10.0
- 操作系统及其版本：win7企业版 64位 SP1
- 浏览器及其版本: chrome 52.0.2743.116 m

#### 你做了什么？

TreeSelect组件在多选状态下，由于UI的限制无法有足够的高度显示选中项。有没有办法只显示选中的数量，而不是把所有选中的内容显示出来？

#### 你期待的结果是：

![1](https://cloud.githubusercontent.com/assets/2088595/18161755/e24194b6-7065-11e6-8b4f-3ca2e04564ad.png)

**Comment by afc163** [comment]
这个不支持的，太特殊的交互了。
