### ISSUE TITLE
RangePicker中使用了showTime和disabledRangeTime属性的情况下，直接选择不符合disabledRangeTime规则的起始时间被错误的设置成功

### ISSUE THREAD

**Issue by pangxiaolong** [ant-design/ant-design#29179]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7bn1y?file=/index.js:1482-1499)

### Steps to reproduce
使用场景：使用RangePicker选择器，同时为改选择器配置属性showtime和disabledRangeTime，假设disabledRangeTime设置规则为1至10点不可选

操作：点开选择器的开始时间，选中6点，此时确定按钮为置灰，便是不可设置。但是此时可以直接将鼠标置入结束时间选择框，此时开始时间已经被设置为错误的6点，同时可以正常设置结束时间并保存。

### What is expected?
希望 RangePicker的disabledRangeTime能起到严格的设置作用

### What is actually happening?
disabledRangeTime规则中的不可选时间段的起始时间被错误的设置

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by kerm1it** [comment]
我看了看最下面的例子，禁用了 4 点之后的所有小时，因此只有0，1，2，3 可以选。

你的描述中说设置1-10点不可选，那么选时间的小时列表里面应该是没有1-10点，所以你的6点是怎么选中的？

**Comment by pangxiaolong** [comment]
> 我看了看最下面的例子，禁用了 4 点之后的所有小时，因此只有0，1，2，3 可以选。
> 
> 你的描述中说设置1-10点不可选，那么选时间的小时列表里面应该是没有1-10点，所以你的6点是怎么选中的？




https://codesandbox.io/s/inspiring-swanson-3w7nx?file=/index.js

也许是我描述有误，我使用了一个更简单的例子，主要是想实现在RangePicker中禁用当前时间之前的时间，但是现在我无法做到。

**Comment by kerm1it** [comment]
你给的这个例子中，禁用的日期是符合预期的（今天及今天之前不可选）。

你的意思是不是开始时间禁用了1-10点，然后结束时间没有禁用，然后在开始时间选择了10点以后，然后在结束时间选择了1-10点，由于结束时间比开始时间小，所以点OK的时候，两个时间会颠倒过来，因此导致开始时间选择了1-10点？

https://codesandbox.io/s/naughty-wood-cb42t?file=/index.js

**Comment by pangxiaolong** [comment]
> 你给的这个例子中，禁用的日期是符合预期的（今天及今天之前不可选）。
> 
> 你的意思是不是开始时间禁用了1-10点，结束时间没有禁用
> 1、在开始时间选择了10点以后的一个小时
> 2、在结束时间选择了1-10点
> 3、由于结束时间比开始时间小，所以点OK的时候，两个时间会颠倒过来，因此导致开始时间选择了1-10点？
> 
> https://codesandbox.io/s/naughty-wood-cb42t?file=/index.js

与10点这个条件无关，请忽略第一个我错误的评论，我只是单纯想实现开始时间不能选择为当前时间之前的时间，而不是10点之前的时间，但是没有使用disabledTime的情况下无法办到，导致我可以选中一个错误的时间，如图：[https://s3.ax1x.com/2021/02/03/yKGZSe.png](url)

所以时候有什么设置办法可以让我实现在RangePicker中限制开始时间不能选中为当前时间之前的时间

**Comment by pangxiaolong** [comment]
> @kerm1it
> ![](https://camo.githubusercontent.com/6a040b7912aa7085fd01c65238b3697ccf1fa56ab17f1eefcc2bba3f41aa2400/68747470733a2f2f73332e617831782e636f6d2f323032312f30322f30332f794b4a6f45712e706e67)

![](https://s3.ax1x.com/2021/02/03/yKJoEq.png)

**Comment by kerm1it** [comment]
明白你的意思了。

disableDate 只能设置禁用的日期，不能设置禁用的时间。

禁用时间需要配合 disableTime 使用，在这里面根据传进来的时间去判断与小时、分钟与当前时间的小时、分钟的大小，最后动态返回禁用的小时、分钟、秒。

**Comment by huanghanyue** [comment]
> 你给的这个例子中，禁用的日期是符合预期的（今天及今天之前不可选）。
> 
> 你的意思是不是开始时间禁用了1-10点，结束时间没有禁用
> 1、在开始时间选择了10点以后的一个小时
> 2、在结束时间选择了1-10点
> 3、由于结束时间比开始时间小，所以点OK的时候，两个时间会颠倒过来，因此导致开始时间选择了1-10点？
> 
> https://codesandbox.io/s/naughty-wood-cb42t?file=/index.js

我有遇到这个问题，请问下有什么方法可以解决吗

**Comment by bingzhe-er** [comment]
https://github.com/ant-design/ant-design/issues/33362
我也遇到这个问题, 请问有什么方法解决吗

**Comment by lilonghe** [comment]
同遇到 DatePicker.RangePicker 设置 minuteStep 后，选择日期后会自动选中小时，但不会自动选中可用分钟项的第一个，而是自动设置了系统当前时间  

四年前有人反馈过被驳回了：https://github.com/ant-design/ant-design/issues/9906

我希望是要不自动选中第一项，要不不要自动设置为系统当前时间，要求必须手动选到分钟。
<img width="375" alt="截屏2022-01-05 15 16 51" src="https://user-images.githubusercontent.com/12867278/148175994-534bdacd-2e27-4ba2-8a29-2919007053bc.png">

**Comment by lilonghe** [comment]
临时解决方案是在 onChange 里纠正，但是右上角自动设置的时间无法处理  
```
onChange={date => {
    if (date[0]) {
        if (date[0].get('minute') !== 0 && date[0].get('minute') !== 30) {
        date[0] = date[0].set('minute', 0);
        }
    }
    if (date[1]) {
        if (date[1].get('minute') !== 0 && date[1].get('minute') !== 30) {
        date[1] = date[1].set('minute', 0);
        }
    }
    form.setFieldsValue({ timeline: date });
}}
```

**Comment by bingzhe-er** [comment]
@lilonghe 如果我没记错的话, 可以给RangePicker中disabledTime属性绑定的函数的第一个参数, 假如说是取名current, 给current赋值来更改右上角自动设置的时间, 我没用moment, 直接current.d = xxx(一个Date对象), 然后右上角的时间就变了

**Comment by lilonghe** [comment]
> @lilonghe 如果我没记错的话, 可以给RangePicker中disabledTime属性绑定的函数的第一个参数, 假如说是取名current, 给current赋值来更改右上角自动设置的时间, 我没用moment, 直接current.d = xxx(一个Date对象), 然后右上角的时间就变了

可以 很强 👍，这个有效的, `current.set('minute', 0)`

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
