### ISSUE TITLE
Select.Option中把value的值当成了react所需的key

### ISSUE THREAD

**Issue by xieyihao** [ant-design/ant-design#2918]
#### 本地环境
Node版本：v4.4.7
npm版本：3.10.5

- antd 版本:v1.10.0
- 操作系统及其版本：Microsoft Windows [版本 10.0.10586]
- 浏览器及其版本:Chrome 版本 52.0.2743.82 m

#### 你做了什么？
给Option设置了key和value，我已经提供的key了，antd把value的值当成了react需要的key值，怎么不用key。

#### 可重现的在线演示
[再现演示](http://codepen.io/xieyihao/pen/xExbJv/)  **请查看console**

**Comment by ddcat1115** [comment]
有点没看懂，所有 Option 的 value 都一样的？

如果 Option 是动态生成的，直接给 key（===value），不用给 value 了

**Comment by Javascript-Ninja** [comment]
例如
```javascript
var arr = [
  { id: 1, name: 'jack' },
  { id: 2, name: 'jack' },
  { id: 3, name: 'lucy' },
  { id: 4, name: 'lucy' },
];

<Select>
  {arr.map(obj, index) =>
    <Select.Option key={obj.id} value={obj.name}>{obj.name}</Select.Option>
  }
</Select>
```
option中的key并没有重复,只是有相同的value, react会提示`Encountered two children with the same key,.$jack. Child keys must be unique; when two children share a key, only the first child will be used`,并且只会渲染一个jack和一个lucy.

**Comment by xieyihao** [comment]
@Javascript-Ninja  对，就是这个意思，举的例子比我写的好 。

**Comment by ddcat1115** [comment]
我的意思是，select里为什么会有多个value相同的选项，这点本来就不合理吧，和react，key...没有关系

**Comment by xieyihao** [comment]
@ddcat1115  由于业务上会出现这种情况，所以发现了这个问题。

**Comment by ddcat1115** [comment]
@yiminghe @afc163  看下需要支持这种情况不，规范里确实也没有说 value 要唯一

**Comment by afc163** [comment]
value 需要唯一。

**Comment by Javascript-Ninja** [comment]
我认为ant组件不应该帮用户过滤掉重复的value，就算要过滤也是让用户自己过滤，只要key不重复就行了

**Comment by benjycui** [comment]
重复的 value 没有意义，你应该把 id 设为 value，name 设为 children 就可以满足业务需求了。

**Comment by xieyihao** [comment]
@benjycui  没有看清我的问题，"Select.Option把value的值当成了react所需的key"，为什么会把value当成key来使用呢？文档中也没有说明这个问题，还是解决下？

对于我所遇到的问题，我用了另一个方法来避免了，受控组件 有兴趣的人可以看看。[Demo](http://codepen.io/xieyihao/pen/ZpbzwP?editors=0010)

**Comment by liuchaofeng1230** [comment]
我也遇到这个问题，在我的业务场景里，相同的value是有意义的。比如value都是"lessThan"，有2个option，一个label是“小于”，另一个label是“早于”。

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#Option-props

**Comment by mikexfreeze** [comment]
@xieyihao 请问你解决这个问题了吗？我也遇到同样的业务需求，option 当中有重复的 value，没想到这么长时间这个问题仍然存在

**Comment by mikexfreeze** [comment]
@xieyihao 请问你解决这个问题了吗？我也遇到同样的业务需求，option 当中有重复的 value，没想到这么长时间这个问题仍然存在

**Comment by xieyihao** [comment]
@mikexfreeze  这个问题过去很久了，参考Option的属性是不支持的了，https://ant.design/components/select-cn/#Option-props。

记得是取巧把id设为props.value，把value设在props.name上，因为显示的内容是children。

**Comment by mikexfreeze** [comment]
> @mikexfreeze 这个问题过去很久了，参考Option的属性是不支持的了，[https://ant.design/components/select-cn/#Option-props。](https://ant.design/components/select-cn/#Option-props%E3%80%82)
> 
> 记得是取巧把id设为props.value，把value设在props.name上，因为显示的内容是children。

谢谢，目前也只能用这种绕路的方法了
