### ISSUE TITLE
Image能否提供直接打开图片预览的API

### ISSUE THREAD

**Issue by GitKou** [ant-design/ant-design#29187]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
点击“预览”按钮，
调用API，
打开图片预览

### What does the proposed API look like?
Image.preview({
     url: '.....'
      .....
});
![image](https://user-images.githubusercontent.com/7437397/106583298-e8727800-657f-11eb-9abf-3ecb204fe6f8.png)

**Comment by shaodahong** [comment]
先用声明式的 API 解决吧，命令式的 PR 见 https://github.com/react-component/image/pull/55

**Comment by afc163** [comment]
Duplicate of #28321

**Comment by GitKou** [comment]
> 先用声明式的 API 解决吧，命令式的 PR 见 [react-component/image#55](https://github.com/react-component/image/pull/55)

大佬这个PR是没有合进去吗？现在是不是不能用？

**Comment by yoyo837** [comment]
react-component/image#56

**Comment by GitKou** [comment]
> [react-component/image#56](https://github.com/react-component/image/pull/56)

您说的是previrew-src吗？我需要的是文字展示”预览“按钮，这里的preview-src也只能是图片地址吧。这个解决的是预览前图片和预览后图片不一样的问题，我需要的是手动调用图片预览。

**Comment by shaodahong** [comment]
> > [react-component/image#56](https://github.com/react-component/image/pull/56)
> 
> 您说的是previrew-src吗？我需要的是文字展示”预览“按钮，这里的preview-src也只能是图片地址吧。这个解决的是预览前图片和预览后图片不一样的问题，我需要的是手动调用图片预览。

https://image-sepia.vercel.app/?path=/story/rc-image--controlled

**Comment by GitKou** [comment]
Thanks a lot
