### ISSUE TITLE
Type 'RangeValue<Moment>' is not an array type or does not have a '[Symbol.iterator]()' method that returns an iterator

### ISSUE THREAD

**Issue by ElsaOOo** [ant-design/ant-design#29197]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)]( https://codesandbox.io/s/festive-mestorf-2xy8q?file=/src/App.tsx)

### Steps to reproduce
 https://codesandbox.io/s/festive-mestorf-2xy8q?file=/src/App.tsx

### What is expected?
RangeValue<DateType> 可以支持数组结构类型没有报错

### What is actually happening?
类型报错 Type 'RangeValue<Moment>' must have a '[Symbol.iterator]()' method that returns an iterator.

| Environment | Info |
|---|---|
| antd | 4.12.0 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome 86 |

**Comment by afc163** [comment]
`value` could be `null` in some situation: https://github.com/react-component/picker/blob/26726d25a031275375b8cbf92f960e9594efa45c/src/interface.ts#L95

https://codesandbox.io/s/tender-clarke-cyvp8?file=/src/App.tsx
