### ISSUE TITLE
InputNumber strange behavior in form

### ISSUE THREAD

**Issue by PainKKKiller** [ant-design/ant-design#29192]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-typescript-form-number-validator-forked-5oe0w?file=/src/index.tsx)

### Steps to reproduce
Just enter absolutly valid value ( 190 for example) in InputNumber and hit save button. 

### What is expected?
Correct work of the form, values in onFinish function.

### What is actually happening?
I am getting validation error and validation message. onFinishFailed function was called. In FireFox developer edition 86.0b3 I never got console.log from onFinishFailed and onFinish functions. 

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | Chrome 88.0.4324.104 |

---
This is really strange, why there is no issue about this. If I am doing something wrong please clarify it in documentation

**Comment by afc163** [comment]
See https://ant.design/components/form/#components-form-demo-complex-form-control
