### ISSUE TITLE
Form表单在设置Input的defaultValue后的初次校验出错

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#29199]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dongtaixiaoyanguize-antd4120-forked-pmsgp?file=/index.js)

### Steps to reproduce
1、为Input设置defaultValue
2、初次进入时校验表单
3、表单报错

### What is expected?
设置defaultValue并在初次进入时不报错

### What is actually happening?
设置defaultValue并在初次进入时报错

| Environment | Info |
|---|---|
| antd | 4.12.0 |
| React | 16.14.0 |
| System | Window10 |
| Browser | chrome |

**Comment by afc163** [comment]
Please use `<Form initialValues />` to set default value of fields.
