### ISSUE TITLE
Antd Table data not available to other components on load or after modifying filters through state

### ISSUE THREAD

**Issue by Chematronix** [ant-design/ant-design#29195]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-table-data-not-available-to-other-components-fiwjc?file=/index.js)

### Steps to reproduce
Let's say I want to show some graphs based on the data being displayed in an Ant Table.  But seems there's no way to access the table's data from other components:
1. On first load.
2. On using state to modify the filters.

In the example, I'm trying to display the number of rows in a Table in other components, and in the Table's title().  When you load it, you'll notice the count is undefined or wrong in the other components.  And if you click in the filter-changing buttons ("See Jims", "See Joes"), the other components won't update.

### What is expected?
1. On first load, one should be able to display data from the table in other components (v.g. `Displaying 3 persons` instead of `Displaying undefined persons`).  

2. On modifying the filters' state (clicking the "See Jims" or "See Joes" buttons in the table's title()) onChange should be called so the other components should update accordingly.

### What is actually happening?
1. On first load, there's no way to check the data of the table, so the other components will show `Displaying undefined persons`.  I can initialize state with the originalData, as I do with `[localData] = useState(originalData)`, but since I'm also using initial filters, then the count is wrong on Load (`localData: Displaying 4 persons` instead of 2).

2. On clicking the "See Jims" or "See Joes" buttons, the other components won't update.  onChange is only triggered when modifying filters or ordering with the table's controls (v.g. click Name's filter and Reset).

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.14.0 |
| System | Windows 10 WSL Debian 10 (buster) |
| Browser | 87.0.4280.141 |

---
Note that the table's title and footer *are* correctly updated on load and on directly modifying filters (`Displaying x persons in Table Title` is always correct).  But one should be able to place the graphs outside the table's title.

There's a workaround for #1: since title() gets passed the current data, it can be used to initialize state (uncomment the if block in title() to try it).  This is probably not the right place to do it, but it works, with a warning: setGlobalData() produces `Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.`, which makes sense, but for some reason setLocalData() and setLiftedData don't produce a warning.

BTW, I'm trying with different kinds of state (local, global and lifted) because I found different behaviours when using  MobX, but it seems they all behave the same without it, except for the setGlobalData() warning (which I also get with MobX).

**Comment by zombieJ** [comment]
`onChange` only trigger when no-controlled change. So you should not deps on the `onChange` for initial value & controlled change. But you still can use `components` to customize a injection component to get row info.
