### ISSUE TITLE
Expand button on expandable row expands every row at once

### ISSUE THREAD

**Issue by Satorlous** [ant-design/ant-design#29194]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-inu45?file=/index.js)

### Steps to reproduce
Replace "key" property name with "id" in objects from dataSource at https://codesandbox.io/s/w4nh6 (link from Expandable Row example https://ant.design/components/table/)

### What is expected?
Expand button should expand only one row

### What is actually happening?
Expand button expands all rows

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 17.0.1 |
| System | Windows 10 64-bit |
| Browser | Google Chrome v88.0.4324.104 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-dx2nb?file=/index.js
