### ISSUE TITLE
关于上传组件Upload的问题

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#292]
需求：我有一个表单
< form action="/upload" method="post" encType="multipart/form-data">
  < input type="text" />
  < input type="file" />
  < input type="submit" value="提交" />
</ form >
我希望在点击提交按钮的时候，把input输入框和待上传的文件一起上传，该怎么使用 upload 组件？
据我目前看到的都是点击文件上传按钮，就直接上传了。

**Comment by zccst** [comment]
请版主关闭吧，我自己使用通过其它方式实现了，没使用upload组件，还是谢谢了。

**Comment by yiminghe** [comment]
data 属性

**Comment by doublelduob** [comment]
请问upload如何和form表单的Form.Item组合起来呢，或者Form里面怎么组合一个upload的组件呢？

**Comment by qwlong** [comment]
@zccst 如何通过其他的方式实现呢，能说一下吗

**Comment by TRUEJASONFANS** [comment]
@qwlong 参见https://github.com/ant-design/ant-design/issues/830
