### ISSUE TITLE
2个微前端重叠打开 Modal 在关闭后 overflow 没有清空

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#29206]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/crazyair/webpack-2/tree/modal](https://github.com/crazyair/webpack-2/tree/modal)

### Steps to reproduce
host、remote 执行 `yarn ; yarn install ; yarn start` 
打开 http://localhost:8083/
打开弹框后再打开弹框，然后全部关闭，body 上 overflow 没有清空

### What is expected?
清空

### What is actually happening?
未清空

| Environment | Info |
|---|---|
| antd | 4.12.0 |
| React | 17 |
| System | mac |
| Browser | chrome |

---
antd v4 是 host (主项目) 去打开 remote( 子项目 ) 的 Modal，关闭后浏览器就失去滚动，不知道有什么比较好的解决办法。

**Comment by crazyair** [comment]
@shaodahong 帮忙看下

**Comment by shaodahong** [comment]
一个 v3 一个 v4 实现逻辑不一样没法在一个视图内公用

**Comment by crazyair** [comment]
> 一个 v3 一个 v4 实现逻辑不一样没法在一个视图内公用

恩，想着是怎么能暂时解决这个问题，10 个微前端 是 antdv3 ，现在是一个一个微前端迁移 v4，要不没法迁移啊

**Comment by yoyo837** [comment]
看看能不能从v5开始改进，首当其冲的就是global style了。

**Comment by crazyair** [comment]
> 看看能不能从v5开始改进，首当其冲的就是global style了。

antd 有 v5？样式冲突还能用 less 变量解决，这个还好，Modal 则是把 overflow 设置到 body 的。

**Comment by shaodahong** [comment]
临时解决方案是设置 v4 modal 的 getContainer 不是 body 就行，再套个壳和 body 同长宽就行

**Comment by shaodahong** [comment]
和 react 17 一样，事件不委托给 body 就行，委托给各自的 root contanier

**Comment by crazyair** [comment]
> 临时解决方案是设置 v4 modal 的 getContainer 不是 body 就行，再套个壳和 body 同长宽就行

棒棒的，全局设置 container 给 div 就行了吧 ，ConfigProvider 的 container 有多少个组件用的？

**Comment by yoyo837** [comment]
感觉还是会有别组件的别的问题出现，@crazyair 认死不能混用版本就对了。

**Comment by crazyair** [comment]
> 感觉还是会有别组件的别的问题出现，@crazyair 认死不能混用版本就对了。

各个项目可以互相隔离，样式也加前缀区分，但是现在是共用的一个 body，这个改了，应该隔离完了吧

**Comment by shaodahong** [comment]
很难说，比如 reset css 行高就不一样，表单可能错位等

**Comment by crazyair** [comment]
> 很难说，比如 reset css 行高就不一样，表单可能错位等

```  
<ConfigProvider
    getPopupContainer={(triggerNode) => {
      return document.querySelector("#host");
    }}
  >
    <div style={{ height: "100vh" }} id="container">
      <App />
    </div>
  </ConfigProvider>

```

**Comment by crazyair** [comment]
@shaodahong 还有问题，如果再第三个子项目打开 host 的 Modal ，则在 host 加的 id container 未加载。

**Comment by shaodahong** [comment]
> @shaodahong 还有问题，如果再第三个子项目打开 host 的 Modal ，则在 host 加的 id container 未加载。

因为你 ConfigProvider 没有包含在代码里，把 ConfigProvider 放到 modal 文件中

**Comment by crazyair** [comment]
> 因为你 ConfigProvider 没有包含在代码里，把 ConfigProvider 放到 modal 文件中

在 main 项目上显示 host，则他的大小只有按钮大小，那 container 就不能设置 100vh，需要在 main 上加这个 div。

**Comment by shaodahong** [comment]
> > 因为你 ConfigProvider 没有包含在代码里，把 ConfigProvider 放到 modal 文件中
> 
> 在 main 项目上显示 host，则他的大小只有按钮大小，那 container 就不能设置 100vh，需要在 main 上加这个 div。

升级到 V4

**Comment by crazyair** [comment]
> 升级到 V4

main 还不能用 v4，因为 9 个 v3 子项目依赖他
