### ISSUE TITLE
FormList 里的动态增减 FormItem 项与返回的字段项不对应

### ISSUE THREAD

**Issue by LunaGod** [ant-design/ant-design#29215]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fuzadedongtaizengjianbiaodanxiang-antd4113-forked-z0dlu?file=/index.js:419-429)

### Steps to reproduce
Area 选择Beijing
点击 Add sights 添加一项
Sight 选择 Tiananmen 在 other 输入6
将 Sight 更换为 Great Wall 在 Price 输入 7
提交表单
查看控制台 sights的第一项

### What is expected?
```javascript
{
  area: "Beijing",
  sights: [{sight: "Great Wall",price: "7"}]
}

```

### What is actually happening?
```javascript

{
  area: "Beijing",
  sights: [{sight: "Great Wall",other: "6",price: "7"}]
}

```

| Environment | Info |
|---|---|
| antd | 4.12.1 |
| React | 17.0.1 |
| System | macOS Mojave 10.14.6 |
| Browser | chrome 88.0.4324.96 |

**Comment by zombieJ** [comment]
`Form.List` 本身是一个字段，所以获取的值是来自于 List 本身。我看看怎么优化一下。
