### ISSUE TITLE
Cant use BackTop in wechat (BackTop在微信浏览器中不正常)

### ISSUE THREAD

**Issue by demonskp** [ant-design/ant-design#29216]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/back-top-cn/](https://ant.design/components/back-top-cn/)

### Steps to reproduce
用微信打开antd官网BackTop组件即可
（Use WeChat to open the BackTop component of the antd official website）

![image](https://user-images.githubusercontent.com/25999019/106744987-78392480-665b-11eb-92e6-04e0534eed25.png)

### What is expected?
能正常显示该组件

### What is actually happening?
在visible为false时 在微信和钉钉都无法正常显示 回到顶部按钮(完全消失)

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | Android |
| Browser | 微信浏览器 |

**Comment by afc163** [comment]
实测可以出现。

![图片](https://user-images.githubusercontent.com/507615/106762593-efc57e80-6670-11eb-9e93-b00909ec52fb.png)

**Comment by demonskp** [comment]
> 实测可以出现。
> 
> ![图片](https://user-images.githubusercontent.com/507615/106762593-efc57e80-6670-11eb-9e93-b00909ec52fb.png)

你这是IOS吧，我说的Android。

**Comment by afc163** [comment]
@demonskp 可以帮忙排查一下问题呢，我们暂时不会对移动端做适配。

**Comment by demonskp** [comment]
> @demonskp 可以帮忙排查一下问题呢，我们暂时不会对移动端做适配。

好的  谢谢
