### ISSUE TITLE
form.getFieldsValue without field name always empty on first render when using initial values on form

### ISSUE THREAD

**Issue by topched** [ant-design/ant-design#29221]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bufep)

### Steps to reproduce
Just run the the codesandbox and watch the console.

### What is expected?
getFieldsValue and getFieldValue should return the same values at all times

### What is actually happening?
 Notice that getFieldValue properly returns the initial value but getFieldsValue is always empty on the first render. Using getFieldsValue with the field name also properly works on the first render. After every subsequent render everything works as expected

| Environment | Info |
|---|---|
| antd | 4.12.1 |
| React | 17.0.1 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`getFieldsValue` only return value which fields register. When you first render, the Field node is not render yet.

**Comment by bombillazo** [comment]
Hello, how can one overcome this limitation? Having an intermediary first render with the form values empty even when an initial values has been passed to the form is not intuitive at all. I would expect this if the value of initialValues is async or not immediately declared, but this is happening even when the initial values are hardcoded on the prop.
