### ISSUE TITLE
Uncontrolled <Select /> not set field value when not direct child of Form.Item

### ISSUE THREAD

**Issue by lindomar-oliveira** [ant-design/ant-design#29220]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cs468)

### Steps to reproduce
Submit form of the reproduction in codesandbox.

### What is expected?
The even behavior that the Input on similar scenario.

### What is actually happening?
Fails in validation required even when user select an option.

| Environment | Info |
|---|---|
| antd | 4.12.1 |
| React | React 17.0.1 |
| System | Linux Mint 20 |
| Browser | Google Chrome 87.0.4280.88 (64 bits) |

**Comment by zombieJ** [comment]
Controlled component must be children of Form.Item.
