### ISSUE TITLE
ant-design怎么实现bootstrap的`.container`里那样的固定宽度布局？

### ISSUE THREAD

**Issue by smilingpoplar** [ant-design/ant-design#2922]
我用`<Row>`和`<Col>`布局，相当于bootstrap里在`.container-fluid`下的`row`和`col`。怎么才能像bootstrap的`.container`类那样固定宽度并把内容居中呢？如果用`Row`的`flex`属性可以的话，它在`ie8`下能正常显示吗？

**Comment by afc163** [comment]
未提供，可以自行探索。

其实我们写了推荐组件的：http://ant.design/components/layout/#API

另外 flex 方案， IE8 肯定是不支持的。
