### ISSUE TITLE
Upload - uid is set even if provided - issue when fileList is immutable from ReduxToolkit selector | Cannot assign to read only property 'uid' of object '#<Object>'

### ISSUE THREAD

**Issue by sowka1995** [ant-design/ant-design#29233]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8juv9)

### Steps to reproduce
Check reproduction link - there is my explanation of the problem.
The problem exists because I am using ReduxToolkit and getting attachements from the store (I am setting uid property) but this object is frozen (I want only show attached attachements (read-only))

### What is expected?
There is react effect to set uid on each file if not provided

```file.uid = (_a = file.uid) !== null && _a !== void 0 ? _a : "__AUTO__".concat(timestamp, "_").concat(index, "__");```

should be sth like this

```
if (!file.uid)
   file.uid = "__AUTO__".concat(timestamp, "_").concat(index, "__");
```

### What is actually happening?
Cannot assign to read only property 'uid' of object '#<Object>'

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 16.3.1 |
| System | Windows |
| Browser | Chrome/Edge chromium/Firefox |

**Comment by jamie-box** [comment]
Can confirm this issue on React 17.0.1 as well.

**Comment by jamie-box** [comment]
_^bumping..._

Hi Ant team, this is a **blocking issue for my application**. Please fix.

**Comment by remberi** [comment]
I'm having the same problem, but downscaling to version 4.7.0 can fix it

**Comment by remberi** [comment]
我的fileList是从父组件传递过来的，如果直接放到upload属性里面会报uid read only,可以从新赋值解决
```
componentDidMount() {
    if (this.props.fileList) {
      this.setState({
        fileList: this.props.fileList.map((item, index) => {
          return { uid: item.uid, name: item.name, status: item.status, url: item.url };
        }),
      });
    }
  }
```

**Comment by Guo-dalu** [comment]
I've met the same problem. When upgrading antd to v4.13.1,  the problem disappeared. All works fine.

Maybe v4.12 has this problem and v4.13 has already fixed it?

升个级试试。
