### ISSUE TITLE
Open patreon account

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#2923]
看看有没有慷慨的企业用户支持。

https://www.patreon.com/

**Comment by benjycui** [comment]
这个需要申请个公司账号吧。

**Comment by afc163** [comment]
https://twitter.com/konnect_ua/status/824275711871553539

先用个人账户搞起如何，公司太拖效率了。@benjycui

**Comment by benjycui** [comment]
主要是担心违规。。

**Comment by afc163** [comment]
违什么规，收入一律充公。
