### ISSUE TITLE
Table pagination overrides setting top and bottom position to 'none'

### ISSUE THREAD

**Issue by zachfedor** [ant-design/ant-design#29235]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-dynamic-settings](https://ant.design/components/table/#components-table-demo-dynamic-settings)

### Steps to reproduce
Pagination config option for the Table component allows setting position for top and bottom pagination component like so:

```<Table pagination={{ position: ['topLeft', 'bottomLeft']}} />```

This position array is painfully confusing. It can contain up to two strings prefixed with `top` or `bottom`, placing up to two pagination components for the top and bottom according to the first two valid positions it sees.

In the documentation, it offers the choice to turn off pagination completely by replacing the config object with `false`. But it also shows the option of setting these positions to `'none'`, which works for one of the positions but is disregarded when set to _both_.

### What is expected?
```<Table pagination={{ position: ['none', 'none']}} />```

Should disable pagination component.

### What is actually happening?
Pagination component is displayed at the default position of bottom right of the table.

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17.0.1 |
| System | macOS 10.15.7 |
| Browser | Chrome 88.0 / Firefox 85.0 |

**Comment by mumiao** [comment]
i mention pr
