### ISSUE TITLE
Cannot use the "Avatar" function from "Upload" 

### ISSUE THREAD

**Issue by Lucas-Pan-Wang** [ant-design/ant-design#29239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#components-upload-demo-avatar](https://ant.design/components/upload-cn/#components-upload-demo-avatar)

### Steps to reproduce
No matter what photo I uploaded from my computer, the Upload component continues to show "loading" instead of showing the picture. It seems like something's wrong with action="https://www.mocky.io/v2/5cc8019d300000980a055e76"

### What is expected?
I hope to see this avatar upload component able to be used.

### What is actually happening?
It cannot be used.  No matter what photo I uploaded from my computer, the Upload component continues to show "loading" instead of showing the picture.

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | react |
| System | windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Try a small png file, it works in my machine.

**Comment by Lucas-Pan-Wang** [comment]
@afc163 Yes, I've tried that. a 5kb png file can be uploaded, but a 180kb png file cannot. This component used to be suitable for regular pictures, but it doesn't now.
I strongly suggest you fix this problem, or it will not be a practical component at all because no one likes to upload pictures so small.
Thank you!

**Comment by afc163** [comment]
```
function getBase64(img, callback) {
  const reader = new FileReader();
  reader.addEventListener('load', () => callback(reader.result));
  reader.readAsDataURL(img);
}
```

Don't use `FileReader` for large file, it is laggy.

**Comment by Lucas-Pan-Wang** [comment]
@afc163 Okay, I got it, sir. Could you tell me another uploading way instead of **FileReader**?

**Comment by afc163** [comment]
It is better to handle it by service side and return a screenshot url to client.

**Comment by Lucas-Pan-Wang** [comment]
@afc163 Okay, I'll try that. Thank you so much!

**Comment by ahmetkuslular** [comment]
you can use this
```
  const handleUploadChange = info => {
    if (info.file.status === 'uploading') {
      setUploadLoading(true);
      return;
    }
    setImage(info.file.originFileObj);
    setPreviewImage(URL.createObjectURL(info.file.originFileObj));
  };
```

**Comment by elmouden-imane** [comment]
> It is better to handle it by service side and return a screenshot url to client.

how can i do it?
