### ISSUE TITLE
Menu crushes when forceSubMenuRender prop active and inlineCollapsed prop changes

### ISSUE THREAD

**Issue by qramilq** [ant-design/ant-design#29230]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapsed-inline-menu-antd4122-forked-5dqvk)

### Steps to reproduce
Click to collapse button multiple times

### What is expected?
Menu collapse and uncollapse normaly on every collapse button click

### What is actually happening?
After some clicks error occurs: Cannot read property '1' of undefined in `getElFuturePos` function from `dom-align` library

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Google Chrome 88 |

---
Used default menu example (Menu component -> Collapsed inline menu) and added forceSubMenuRender

**Comment by afc163** [comment]
Fixed in antd@4.16.1: https://codesandbox.io/s/collapsed-inline-menu-antd4122-forked-ew9kv?file=/index.js
