### ISSUE TITLE
Button id is not passed to onClick event

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#29246]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sh1fu)

### Steps to reproduce
click on button and check console.log

### What is expected?
id is present on target prop

### What is actually happening?
id is empty string

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | latest |
| System | Mac Os Catalina |
| Browser | Chrome latest |

**Comment by iqingting** [comment]
You need to use the `currentTarget` to get the event listener element.

https://stackoverflow.com/questions/10086427/what-is-the-exact-difference-between-currenttarget-property-and-target-property
