### ISSUE TITLE
使用shouldCellUpdate后，修改cell值时，会使上次修改的其他cell值重置

### ISSUE THREAD

**Issue by ZeroCodeLin** [ant-design/ant-design#29243]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/affectionate-sky-gxzfv?file=/index.js

### Steps to reproduce
先修改第一个cell的值，在修改第二个

### What is expected?
不重置第一个值

### What is actually happening?
重置第一个值

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome |

**Comment by kerm1it** [comment]
这个是用法问题，由于闭包，onChange 里面的用的 data 一直是初始化的值，因此修改另外一个 cell 的时候就会导致之前的修改失效。

**Comment by ZeroCodeLin** [comment]
> 这个是用法问题，由于闭包，onChange 里面的用的 data 一直是初始化的值，因此修改另外一个 cell 的时候就会导致之前的修改失效。

不使用shouldCellUpdate是正常的

**Comment by ZeroCodeLin** [comment]
我现在遇到的问题是，table里面有很多Input，输入时会有很明显卡顿，别的Issues里面说是shouldCellUpdate优化。使用了这个就出现了上面的问题，是我的用法不对么？

**Comment by kerm1it** [comment]
是的，不使用 shouldCellUpdate 的时候，编辑一个单元格的时候，setData 调用后，组件会重新渲染，另外一个单元格也会重新渲染，那时候的 onChange 用的 data 是 setData 之后的。

如果用了 shouldCellUpdate，编辑一个单元格的时候，setData 调用后，由于不满足另一组件的 shouldCellUpdate 条件，另一个cell 用的 onChange 还是 之前的（用的之前的data）。

这的确是个问题。

**Comment by ZeroCodeLin** [comment]
> 是的，不使用 shouldCellUpdate 的时候，编辑一个单元格的时候，setData 调用后，组件会重新渲染，另外一个单元格也会重新渲染，那时候的 onChange 用的 data 是 setData 之后的。
> 
> 如果用了 shouldCellUpdate，编辑一个单元格的时候，setData 调用后，由于不满足另一组件的 shouldCellUpdate 条件，另一个cell 用的 onChange 还是 之前的（用的之前的data）。
> 
> 这的确是个问题。

请问这个问题会修复吗？修复话预计会是什么时候？

**Comment by zombieJ** [comment]
https://codesandbox.io/s/romantic-noether-kessz?file=/index.js

Hooks  `setState` 的 function update 就是用来处理闭包问题的……

**Comment by jeffrey-fu** [comment]
这跟闭包没关系吧，个人理解为React的数据不可变性导致，[MemoCell](https://github.com/react-component/table/blob/master/src/Cell/index.tsx#L312) 被 [React.memo](https://reactjs.org/docs/react-api.html#reactmemo)包裹，用`shouldCellUpdate`判断是否更新，导致引用的`onChange`依旧是之前阶段的

**Comment by zhangqp5-leaf** [comment]
你好，请问这个问题解决了吗

**Comment by yang-xianzhu** [comment]
> 你好，请问这个问题解决了吗

上面不是说了吗，react的闭包陷阱导致的

**Comment by bxb100** [comment]
> 这跟闭包没关系吧，个人理解为React的数据不可变性导致，[MemoCell](https://github.com/react-component/table/blob/master/src/Cell/index.tsx?rgh-link-date=2022-05-12T06%3A19%3A30.000Z#L312) 被 [React.memo](https://reactjs.org/docs/react-api.html#reactmemo)包裹，用`shouldCellUpdate`判断是否更新，导致引用的`onChange`依旧是之前阶段的

看了一下 https://github.com/react-component/util/blob/master/src/hooks/useMemo.ts 代码, 归根结底还是由于闭包导致的问题, 复用的 returnCellProps 导致 onChange stale value
