### ISSUE TITLE
onChange is called when bluring an InputNumber with decimal input

### ISSUE THREAD

**Issue by martis347** [ant-design/ant-design#29254]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/t4p2i)

### Steps to reproduce
1. Type a decimal value to the input (for example "3.1")
2. Blur input by clicking somewhere else

### What is expected?
"onChange" should not trigger when the value is not actually changed.

### What is actually happening?
"onChange" is triggered even if value of the input does not change, but a blur event occurs.

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Google Chrome 88.0.4324.104 (Official Build) (64-bit) |

---
As I have found, only InputNumber component with a decimal value has this issue. If the value is an integer blur event does not cause "onChange".

![DrawerClose](https://user-images.githubusercontent.com/10206279/107029811-573a1600-67b8-11eb-902f-8c9929d733ce.gif)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15140#issuecomment-468879144
