### ISSUE TITLE
Tree 勾选疑问

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2925]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：win10
- 浏览器及其版本: chrome

#### 你做了什么？

使用Tree控件

#### 你期待的结果是：

像ztree一样可以设置父子节点的影响( http://www.treejs.cn/v3/demo.php#_201)
有一种场景：比如后台的授权: 勾选父节点时影响子节点，勾选子节点影响父节点，取消勾选子节点不影响父节点，如何实现啊?
是要开启checkStrictly，自己实现onCheck里的逻辑吗,有更简单的实现方案吗

**Comment by afc163** [comment]
对，checkStrictly。
