### ISSUE TITLE
@select-item-selected-color in Default Variables not working

### ISSUE THREAD

**Issue by robertsamarji** [ant-design/ant-design#29255]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce
Theme Ant Design using the Default Variables for a Less integration and change the selector: @select-item-selected-color.

Link to Default Variables here: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

### What is expected?
The text colour of the Select component should change.

### What is actually happening?
The text colour of the Select component does not change.

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 16.14.0 |
| System | macOS 10.15 |
| Browser | Chrome 88 |

**Comment by robertsamarji** [comment]
Don't know how to reproduce it by importing defaults.less on CodeSandbox.

**Comment by afc163** [comment]
You can provide a github repo.
