### ISSUE TITLE
关于暗黑模式下字体颜色

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#29265]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
建议将暗黑模式下(即dark.less中)@text-color变量从fade(@white, 85%)变成fade(@white, 65%)

1.相关修改：#25923 #25630
2.目前dark.less中默认@text-color的值为fade(@white, 85%)，但是官网在处理暗黑模式的时候替换变量替换成了fade(@white, 65%)，如果单独用dark-theme.js中变量替换的话字体颜色会和官网不一致
3.如果采用目前的fade(@white, 85%)，暗黑模式下部分组件，比如datepicker中对比度有些过高，字体颜色有些刺眼
4.即使换回fade(@white, 65%)，和默认的component-background变量测试下，其对比度依然符合WCAG2.0标准
![image](https://user-images.githubusercontent.com/8555127/107113610-fd5e4c80-689a-11eb-8222-bf433be50159.png)

### What does the proposed API look like?
x

**Comment by yingxirz** [comment]
不建议改成 65%.虽然在页面背景上勉强达到 AAA，但在空间位置更高的容器上，背景更浅，例如 modal，对比度就不够了。
![image](https://user-images.githubusercontent.com/24960043/112099516-a27c7c80-8bde-11eb-90fb-73c48c726e9f.png)
而且直接降档到 65%，会丢掉一个文本色的梯度，在小字号和复杂场景中难以建立清晰的视觉层次。

**Comment by yingxirz** [comment]
文本色的梯度和用法我们正在处理，想必到时候会有一个更完善的解决方案。
