### ISSUE TITLE
希望提供一个新的talbe组件天然支持大数据量，无需自己扩展配置

### ISSUE THREAD

**Issue by Yaowen-Pan** [ant-design/ant-design#29262]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
提供一个新的talbe组件天然支持大数据量，无需自己扩展配置，解决不仅是行多,还有列多的问题。

### What does the proposed API look like?
比如 <virualTable dataSource={data} />

**Comment by afc163** [comment]
Trace #20339
