### ISSUE TITLE
如何修改，覆盖掉addonBefore这个属性生成的元素的css样式

### ISSUE THREAD

**Issue by musicWind** [ant-design/ant-design#2926]
#### 本地环境

- antd 版本:1.10.0
- 操作系统及其版本：window
- 浏览器及其版本:chrome

#### 你做了什么？
引入前置后置标签，但是想修改标签里面嵌套的组件的样式，尝试过很多都覆盖不了样式，通过addonBefore在页面生成的span标签找不见，修改不了，怎么处理

#### 你期待的结果是：
将前置/后置标签里面灰色的部分修改成白色，或者修改其他样式也行

**Comment by afc163** [comment]
自己覆盖样式。
