### ISSUE TITLE
Calendar控件的年度显示不全

### ISSUE THREAD

**Issue by styushao** [ant-design/ant-design#2927]
#### 本地环境

- antd 版本:  "antd": "^1.11.0"
- 操作系统及其版本：win7
- 浏览器及其版本: chrome 52.0.2743.116 m

#### 你做了什么？

`ReactDOM.render(<Calendar />, document.getElementById('root'));`

#### 你期待的结果是：

让年度能够完全显示，比如ant-select-dropdown-menu-item这个的padding-left和padding-right减小到7px，要不操作不方便
#### 实际上的结果：
出来之后的年度下拉列表显示不全。

**Comment by benjycui** [comment]
因为 Windows 的滚动条比较宽。

![image](https://cloud.githubusercontent.com/assets/3580607/18468677/905e19fa-79d7-11e6-808a-2238d4d418a9.png)

和设计相关的问题 cc @Chinglik

**Comment by afc163** [comment]
这是我这里改挂了。https://github.com/ant-design/ant-design/commit/6ba30bc485b7570ee1140c3818f836ab04100d41

**Comment by Chinglik** [comment]
~\(≧▽≦)/~
