### ISSUE TITLE
当表单的layout设置为vertical时，选择框中的宽度会根据placeholder的长度而改变，placeholder不会省略，会一直增长

### ISSUE THREAD

**Issue by 3470013633** [ant-design/ant-design#29276]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当placeholde太长时，出现样式错误问题

### What does the proposed API look like?
期望placeholder太长时会自动省略

**Comment by phoema** [comment]
4.12.0有问题
https://codesandbox.io/s/biaodanfangfadiaoyong-antd4122-forked-9uo4h?file=/index.js

4.12.2好了

**Comment by afc163** [comment]
请升级到 4.12.2
