### ISSUE TITLE
表格组件component属性和 expandable属性同时使用出错 

### ISSUE THREAD

**Issue by j5465** [ant-design/ant-design#29279]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuozhuaishoubinglie-antd4122-forked-7y64v?file=/index.js)

### Steps to reproduce
当table中含有comoponents属性时，expandable属性会出错，单击加好会展开，但再点击减号不会折叠。而且使用expandedRowKeys指定哪些行展开也出错，同样是只出现加号变减号动画却不缩回。
注释掉component属性就会正常。expandedRowKeys指定哪些行展开或折叠也会正常。

### What is expected?
同时含有components和expandable属性时可以使用expandedRowKeys控制哪些行展开/折叠。

### What is actually happening?
同复现步骤

| Environment | Info |
|---|---|
| antd | 4.11.2 |
| React | 16.8.6 |
| System | ubuntu 18.04 |
| Browser | chrome  88.0.4324.146 |

**Comment by zangmx2020** [comment]
请问 除了使用expandedRowKeys 代替 expandable 属性之外 还有什么其他的解决方法吗？

**Comment by afc163** [comment]
see https://codesandbox.io/s/tuozhuaishoubinglie-antd4122-forked-nxovz?file=/index.js
