### ISSUE TITLE
v4.12-Table-鼠标移动到行没有高亮

### ISSUE THREAD

**Issue by snowINsummer** [ant-design/ant-design#29272]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
告知用户鼠标当前悬停的数据，方便后续对行数据的操作

### What does the proposed API look like?
鼠标移动到行高亮显示，参考ant-design 3.x版本

**Comment by snowINsummer** [comment]
> Hello @snowINsummer. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @snowINsummer, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://8en46.csb.app/

**Comment by xrkffgg** [comment]
4.x 交互背景改成了淡灰色。

如果你要亮色的，可以自行修改 css

```css
.ant-table-tbody > tr.ant-table-row:hover > td { 
    background: #xxxxx;
}
```
