### ISSUE TITLE
如何修改table的整个单元格颜色？

### ISSUE THREAD

**Issue by bodian520** [ant-design/ant-design#29278]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues?q=is%3Aissue is%3Aopen table](https://github.com/ant-design/ant-design/issues?q=is%3Aissue is%3Aopen table)

### Steps to reproduce
1.创建table
2.colums的redener中实现：
`<div style={{backgroupcolor:blue}}>1234</div>`
3.单元格部分为蓝色，td中有padding，修改div的width和high也无法改变整个单元格颜色

### What is expected?
改变整个单元格颜色

### What is actually happening?
只能修改部分单元格颜色

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | Mac |
| Browser | chrome |

现在的效果是：
![image](https://user-images.githubusercontent.com/62273402/107148812-40e6b280-6990-11eb-9e65-09f02dad521c.png)

怎么改可以实现修改整个单元格的颜色？

![image](https://user-images.githubusercontent.com/62273402/107148821-50fe9200-6990-11eb-8177-923f9fb46d4e.png)

**Comment by zkwolf** [comment]
https://codesandbox.io/s/xuanzehecaozuo-antd4122-forked-8cdhr?file=/index.js 大概这样
