### ISSUE TITLE
希望浮层 可以实现 ng-zorro 那样的可以根据 popupContainer 的边界调整方向以及吸附的功能

### ISSUE THREAD

**Issue by ElderJames** [ant-design/ant-design#29281]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
避免浮层被遮挡，或撑开布局。

- 需要显示浮层（tooltip、dropdown、menu）时，根据trigger所在位置，如果原设定的位置超出边界，便自动修改为可展示的方向。
- 当浮层正在展开时，如果trigger滚动到边界并部分在边界内时，浮层应该吸附在边界上，直到trigger滚动出边界。

### What does the proposed API look like?
除了ngzorro，还可以参考popper https://popper.js.org/

**Comment by afc163** [comment]
1. popupContainer 的边界调整方向

目前是有的，细节做过调整：https://github.com/ant-design/ant-design/issues/12153#issuecomment-420874541

2. 当浮层正在展开时，如果trigger滚动到边界并部分在边界内时，浮层应该吸附在边界上，直到trigger滚动出边界。

这个有点不太理解。

**Comment by yoyo837** [comment]
贴边的意思应该是指的是自动贴边，就像微信中没看完的文章的那个悬浮窗。
但他这里的表示感觉就是之前改过的不要拖出屏幕之外的意思。

**Comment by ElderJames** [comment]
![image](https://user-images.githubusercontent.com/7550366/107203318-3ed72f00-6a36-11eb-882a-59bee24e0fef.png)

就是弹出之后，再滚动到边界时，不会超出边界，直到trigger整个元素滚动出边界，才随着滚动。

https://popper.js.org/ 里面的第二个demo，OVERFLOW PREVENTION

**Comment by afc163** [comment]
这个特性挺酷的，类似的实现：https://github.com/react-component/tooltip/pull/166

**Comment by ElderJames** [comment]
😂那只能等合并了

**Comment by afc163** [comment]
react-component/tooltip#166 还是不太一样的，这个没有处理滚动，而且看上去 PR 已经年久失修。

@ElderJames 欢迎另请 PR。

**Comment by afc163** [comment]
Auto arrow position has been supported in antd 5.x now! https://github.com/ant-design/ant-design/pull/40632

See https://ant.design/components/tooltip#components-tooltip-demo-shift
