### ISSUE TITLE
responsive top navbar (top menu)

### ISSUE THREAD

**Issue by mayinghan** [ant-design/ant-design#29280]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A responsive top navbar will make it easier to handle different screen size for a navbar on the top rather than a sidebar

### What does the proposed API look like?
Similar to the Sidebar, using the breakpoint to control if the menu collapse into a hamburger menu.

**Comment by afc163** [comment]
Try https://ant.design/components/menu-cn

**Comment by hafizglasswall** [comment]
i dont understand, isnt having mobile responsive navbar very useful feature?

a simple header with navbar menus turn to hamburger menu in responsive screen size
