### ISSUE TITLE
Modal.confirm button props do not update dynamically

### ISSUE THREAD

**Issue by jaylonez** [ant-design/ant-design#29291]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-archimedes-5o914)

### Steps to reproduce
1. Create isDisabled in state, defaulted to `false`
2. Call Modal.confirm() with `cancelButtonProps={{ disabled: isDisabled }}` and `onOk: async () => {
              setIsDisabled(true);
              return new Promise((resolve) =>
                setTimeout(() => resolve(setIsDisabled(false)), 3000)
              );
            },`
3. Click OK button

### What is expected?
Setting `isDisabled = true` should set the Cancel button's disabled status to `true`

### What is actually happening?
cancelButtonProps ignores the change to isDisabled and the button stays active.

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17.0.1 |
| System | MacOS 11.1 |
| Browser | Chrome 88, Firefox 85 |

**Comment by afc163** [comment]
Modal.confirm is not a React Component which will rerender in React render phase. Please use `<Modal />` instead.

**Comment by nmcanhh** [comment]
```
const confirm = () => {
    Modal.confirm({
      title: "Thông báo",
      icon: <ExclamationCircleOutlined />,
      content: "Bạn có thực sự muốn xóa?",
      centered: true,
      maskClosable: true,
      onOk() {
        console.log("Đã xóa");
      },
      okText: "Xóa",
      cancelText: "Hủy bỏ",
    });
  };
```

**Comment by nmcanhh** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/happy-archimedes-5o914)
> 
> ### Steps to reproduce
> 1. Create isDisabled in state, defaulted to `false`
> 2. Call Modal.confirm() with `cancelButtonProps={{ disabled: isDisabled }}` and `onOk: async () => { setIsDisabled(true); return new Promise((resolve) => setTimeout(() => resolve(setIsDisabled(false)), 3000) ); },`
> 3. Click OK button
> 
> ### What is expected?
> Setting `isDisabled = true` should set the Cancel button's disabled status to `true`
> 
> ### What is actually happening?
> cancelButtonProps ignores the change to isDisabled and the button stays active.
> 
> Environment	Info
> antd	4.12.2
> React	17.0.1
> System	MacOS 11.1
> Browser	Chrome 88, Firefox 85

```
const confirm = () => {
    Modal.confirm({
      title: "Thông báo",
      icon: <ExclamationCircleOutlined />,
      content: "Bạn có thực sự muốn xóa?",
      centered: true,
      maskClosable: true,
      onOk() {
        console.log("Đã xóa");
      },
      okText: "Xóa",
      cancelText: "Hủy bỏ",
    });
  };
```

**Comment by victorlitvinenko** [comment]
@afc163 was right. If you need to change something from the `Modal.confirm` content, you should only use variables, not React state.
```
let someVariable;

const modal = Modal.confirm({
    content: <SomeComponent onChange((data) => {
        someVariable = data;
        modal.update({ okButtonProps: { disabled: data === undefined }});
      }) />,
    onOk() {
      // You have access to someVariable here
      console.log(someVariable);
    },
  });
```
