### ISSUE TITLE
Tag.CheckableTag 期望可以继承 Tag 的 props

### ISSUE THREAD

**Issue by dyb881** [ant-design/ant-design#29296]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
设置颜色

### What does the proposed API look like?
直接继承 tag

**Comment by afc163** [comment]
CheckableTag 设计上是有固定颜色的，目前不支持自定义别的颜色。

**Comment by frank-liu** [comment]
> CheckableTag 设计上是有固定颜色的，目前不支持自定义别的颜色。

可以传入style呀：
<CheckableTag **style={{ backgroundColor: 'red' }}**   key={tag} checked={true}  onChange={checked => onRoleTagChanged(tag, checked)} >  </CheckableTag>
