### ISSUE TITLE
table组件中 如果DataSource数据源里面的数据里有chlidren属性，会自动展开为树形结构的表格。如果我数据源中有children属性但是并不需要树形结构要怎么设置呢

### ISSUE THREAD

**Issue by smallfishr** [ant-design/ant-design#29299]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table中DataSource数据源有children但并不需要树形结构。

### What does the proposed API look like?
不要过度设计默认值。

**Comment by afc163** [comment]
Please search issues and read FAQ before create new issue.

**Comment by afc163** [comment]
Try rename `childrenColumnName`

https://github.com/ant-design/ant-design/issues/9035
https://github.com/ant-design/ant-design/issues/13116

**Comment by smallfishr** [comment]
而且我也并不需要row是expandable的，rename childrenColumnName 以后row还是默认展开的。如何在数据结构有children的基础上，去除expandable

**Comment by afc163** [comment]
> 而且我也并不需要row是expandable的，rename childrenColumnName 以后row还是默认展开的。如何在数据结构有children的基础上，去除expandable

给个重现看看。
