### ISSUE TITLE
Input组件，无法添加最外层className

### ISSUE THREAD

**Issue by meikidd** [ant-design/ant-design#2930]
#### 我的代码：
```
<Input className="order-search-ipt" placeholder="请输入手机号"  />
```

#### 你期待的结果是：
```
<span class="ant-input-wrapper order-search-ipt">
    <input type="text" class="ant-input" placeholder="请输入手机号" value="" />
</span>
```
#### 实际上的结果：
```
<span class="ant-input-wrapper">
    <input type="text" class="ant-input order-search-ipt" placeholder="请输入手机号" value="" />
</span>
```
![image](https://cloud.githubusercontent.com/assets/376338/18195643/2cf24c62-711f-11e6-8fd6-e77b2a19eed9.png)

给组件添加的样式，并没有添加到最外层的容器，而是添加到内层的input元素上了

**Comment by 275287902** [comment]
@meikidd 
1、从理解上看，className加到input上是正确。
2、我看了下，input外层的ant-input-wrapper这个类并没有样式，你可以直接用这个class
3、如果你局部使用你的class的，目前建议在Input组件外再加上一个标签，类似：
  ‘<div style={{margin: 10}}>
    <Input className="order-search-ipt" placeholder="请输入手机号"  />
  </div>’
或者用<Input.Group>
