### ISSUE TITLE
intialValues are non effective on referenced input

### ISSUE THREAD

**Issue by dman777** [ant-design/ant-design#29305]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/initialvalues-with-ref-keftp?file=/index.js)

### Steps to reproduce
use initialValues to set initialValues on form with input - input is a referenced component. All ant design components. 

### What is expected?
intialValues are set. ie: username from ant input should show 'foobar' 

### What is actually happening?
input has no initial values

| Environment | Info |
|---|---|
| antd | 4.12.1 |
| React | 4.12.1 |
| System | ? |
| Browser | Chrome |

---
Please tell me how to work around this and still use the referenced component.

**Comment by afc163** [comment]
https://codesandbox.io/s/initialvalues-with-ref-forked-dn6lj
