### ISSUE TITLE
Make a Collapse Panel draggable

### ISSUE THREAD

**Issue by chuikoffru** [ant-design/ant-design#29302]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hey! I'd like to sort Panels at Collapse component by react-dnd, but Panel doesn't have ref attribute.

### What does the proposed API look like?
add ref attribute to Collapse.Panel

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/19764#issuecomment-751946135

**Comment by umagon** [comment]
@afc163 Hello! Any plans for adding ref to Collapse and Panel? I wanted to implement a drag and drop feature for my collapsible panels.
