### ISSUE TITLE
Call normalize function when Form put initialValues on Inputs

### ISSUE THREAD

**Issue by juliohenriquerocha** [ant-design/ant-design#29304]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need that Input value been formatted, using normalize function from Form.Item, when the value been set by Form#initialValues props. Is possible that normalize function be called  after Form put values on Input?

### What is solution?
The value in Input must be formatted by the normalize function of the Form.Item component;

### Reprodution link
https://codesandbox.io/s/youthful-napier-v7tte?file=/src/App.js

### What does the proposed API look like?
No need API update. Just flex the lifecycle of normalize function of the Form.Item component

**Comment by afc163** [comment]
Noop, initialValues should be normalized, value is the result of `normalize` function, not a input data.
