### ISSUE TITLE
Unwanted side effects in Select when using custom dropdown menu demo with multiple mode

### ISSUE THREAD

**Issue by nabramow** [ant-design/ant-design#29318]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Issue is also mentioned [here](https://github.com/ant-design/ant-design/issues/15392), but there is no solution yet.

### Reproduction link
[https://codepen.io/nabramow/pen/ZEBBbQd](https://codepen.io/nabramow/pen/ZEBBbQd)

### Steps to reproduce
This is using the antd custom dropdown render demo from [here](https://ant.design/components/select/#components-select-demo-custom-dropdown-menu), but in multiple mode:

1. Select some items, so the tags populate in the select input
2. Click in the input within the dropdown
3. Type something
4. Hit backspace to delete some of what you typed
5. You will see the selected tags also get deleted

### What is expected?
When I am focused in the input within the dropdown, backspace does not affect the select input field

### What is actually happening?
My tags are getting deleted when I only meant to delete text in the inner input

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Mac OS 11.1 |
| Browser | Chrome 88.0.4324.150 |

**Comment by afc163** [comment]
See https://codepen.io/afc163/pen/WNooqBW

**Comment by nabramow** [comment]
Thank you!

**Comment by devchen13** [comment]
![image](https://github.com/user-attachments/assets/9372e0dc-5c37-4376-8744-dfde5cbc3ad4)
红色箭头是通过options的label:<div>{i.label}{<Input/></div>实现的
绿色箭头是通过dropdownRender:(content)=><div>{content}<Input/></div>实现的

红色箭头的鼠标选中文本无法选中，无法切换光标位置
绿色的可以，请问是什么原因，要怎么修复@ @

@afc163

**Comment by devchen13** [comment]
![image](https://github.com/user-attachments/assets/9372e0dc-5c37-4376-8744-dfde5cbc3ad4)
![image](https://github.com/user-attachments/assets/f331b641-7617-4759-9a69-9b6e0d2c1574)

@afc163

**Comment by devchen13** [comment]
> ![image](https://private-user-images.githubusercontent.com/30109901/401894424-9372e0dc-5c37-4376-8744-dfde5cbc3ad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTg2OTQsIm5iZiI6MTczNjQ5ODM5NCwicGF0aCI6Ii8zMDEwOTkwMS80MDE4OTQ0MjQtOTM3MmUwZGMtNWMzNy00Mzc2LTg3NDQtZGZkZTVjYmMzYWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDA4Mzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkODFiNmE0YWE5ZWMxMGU5ZDJhZjZhZGI5NzIxMTgyOWUyMTYyZTAxODUyM2RiNWNjZmM5MDNjNjFiNzkwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rmxrXEdWA5p0zaIBTjyFZm1Dsm_E9HM9MZ03ngu_IMY) ![image](https://private-user-images.githubusercontent.com/30109901/401896656-f331b641-7617-4759-9a69-9b6e0d2c1574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTg2OTQsIm5iZiI6MTczNjQ5ODM5NCwicGF0aCI6Ii8zMDEwOTkwMS80MDE4OTY2NTYtZjMzMWI2NDEtNzYxNy00NzU5LTlhNjktOWI2ZTBkMmMxNTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDA4Mzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYThmMzkxNDkwNDYzOWJiODI3YWZhNjAyOWIwOTg5YjkyNDk3ZjA5MTYyMGI0Mzg5NTgwMDMyYWZiYWU1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TtmKXsqPMtizBSO_P1igtW48v-ZcUxmikmrcoNF_lvY)
> 
> @afc163

antd: 4.24.10
