### ISSUE TITLE
Modal Confirm onOk can't access state

### ISSUE THREAD

**Issue by philipduiqmetrix** [ant-design/ant-design#29317]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rx01k?file=/index.js)

### Steps to reproduce
1. Open console
2. Click on the button
3. Enter random text in the input field
4. Press Ok 

### What is expected?
handleMondalOk, text: {{randomText}}

### What is actually happening?
handleMondalOk, text: ""

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome |

---
In the console, we can see that the state is updating because the useEffect is logging the text state changes and it's shown in the console. Also the button text also changes on key press. So that proves that the state updates properly but the onOk of the Modal confirm method can see it

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/29291#issuecomment-775869367

**Comment by nmcanhh** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-rx01k?file=/index.js)
> 
> ### Steps to reproduce
> 1. Open console
> 2. Click on the button
> 3. Enter random text in the input field
> 4. Press Ok
> 
> ### What is expected?
> handleMondalOk, text: {{randomText}}
> 
> ### What is actually happening?
> handleMondalOk, text: ""
> 
> Environment	Info
> antd	4.12.3
> React	17.0.1
> System	Windows 10
> Browser	Chrome
> In the console, we can see that the state is updating because the useEffect is logging the text state changes and it's shown in the console. Also the button text also changes on key press. So that proves that the state updates properly but the onOk of the Modal confirm method can see it

```
const confirm = () => {
    Modal.confirm({
      title: "Thông báo",
      icon: <ExclamationCircleOutlined />,
      content: "Bạn có thực sự muốn xóa?",
      centered: true,
      maskClosable: true,
      onOk() {
        console.log("Đã xóa");
      },
      okText: "Xóa",
      cancelText: "Hủy bỏ",
    });
  };
```
