### ISSUE TITLE
使用getFieldProps在任何form控件中输入都将render()整个页面

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#2932]
本地环境

antd 版本: "antd": "^1.10.0"
操作系统及其版本：win10
浏览器及其版本: chrome 52.0.2743.116 m
你做了什么？
使用getFieldProps在任何form控件中输入都将render()整个页面

import 'antd/dist/antd.css';
import React from 'react';
import ReactDOM from 'react-dom';
import { Form, Input, Select, InputNumber, DatePicker, TimePicker, Switch, Radio,
    Cascader, Slider, Button, Col, Upload, Icon } from 'antd';
class Demo extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        console.log('render');
        const { getFieldProps } = this.props.form;
        return (
            <div>
                <Input placeholder="请输入"     {...getFieldProps('userName') }/>
            </div>
        );
    }
}
Demo = Form.create()(Demo);
ReactDOM.render(<Demo />, mountNode);
 

你期待的结果是：

 在输入框中输入时不执行render() ，使整个页面刷新

实际上的结果：
![image](https://cloud.githubusercontent.com/assets/19165238/18198448/ae03ad28-712e-11e6-81ca-d39b460d2b4e.png)

在输入框输入会执行render() 每输入一次就会render()一次页面
 
可重现的在线演示:无

**Comment by afc163** [comment]
对，受控模式就是这样。https://facebook.github.io/react/docs/forms.html#controlled-components
