### ISSUE TITLE
Dropdown在vite中无法正常工作

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design#29320]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown-cn/?a=触发简单，无需提供](https://ant.design/components/dropdown-cn/?a=触发简单，无需提供)

### Steps to reproduce
使用vite构建react应用，引入Dropdown既可

### What is expected?
Dropdown可以正常工作

### What is actually happening?
Dropdown可以展示，但是无法消失，设置visible=false也无效，onVisibleChange可以正常触发

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0  |
| System | mac os |
| Browser | chrome 88 |

**Comment by random-yang** [comment]
@afc163 可以把你的代码段贴出来看看，我试了一下，用vite也没什么问题。

**Comment by xieyezi** [comment]
@faner11  请问解决了吗？遇到了同样的问题

**Comment by huxianghe** [comment]
@faner11 @xieyezi 尝试在入口文件 `import 'antd/dist/antd.less'` ，全量引入样式文件试试？

**Comment by PeiXueYang** [comment]
vite中没有问题啊  
 <Dropdown overlay={menu} visible={false}>
          <a className="ant-dropdown-link" onClick={e => e.preventDefault()}>
          Hover me <DownOutlined />
          </a>
   </Dropdown>

**Comment by lake2** [comment]
same issue + 1

**Comment by theprimone** [comment]
[discussions#29660 - Vite 2.x 下如何使用 antd ?](https://github.com/ant-design/ant-design/discussions/29660)
@xieyezi @lake2

**Comment by GuichiZhao** [comment]
> 我的场景是修改配置文件里的 `lib` 为 `es` 解决的：
> 
> ```ts
> // vite.config.ts
>     importPlugin({
>       libList: [
>         {
>           libName: 'antd',
>          // style: (name) => `antd/lib/${name}/style`
>           style: (name) => `antd/es/${name}/style`
>         }
>       ]
>     })
> ```

真的是这样，这是什么奇怪的bug，我看lib和es下的代码一样的啊
不过还真是谢谢你，否则这种bug我做梦也想不到

**Comment by yunsii** [comment]
我的理解是因为按需加载的样式代码是运行时的代码了，运行时 lib 下是使用的 require 的语法，如果要支持就需要配置 vite 支持 commonjs 的写法，使用 @rollup/plugin-commonjs 或许能解决，但是在 antd 提供 esm 的情况下，duck 不必了
