### ISSUE TITLE
flex gap feature detection causes style prop mismatch warning with server-side rendering

### ISSUE THREAD

**Issue by brandonbloom** [ant-design/ant-design#29327]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
- enable gutters > 0
- use a framework with server-side rendering like Next.js
- create a Row or Col component

### What is expected?
no warnings in console

### What is actually happening?
```
Warning: Prop `style` did not match. Server: "null" Client: "--column-gap:0px;--row-gap:0px"
    at div
    at Row 
```

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.13.1 |
| System | n/a |
| Browser | any with flex-gap support |

---
This appears to be caused by the feature detection function detectFlexGapSupported in _util/styleChecker. It returns false when running during server-side rendering, but returns true in modern browsers on the client side.

**Comment by theahmadzai** [comment]
Have the same issue using antd with next.js

**Comment by MarcioBarrientos** [comment]
> Have the same issue using antd with next.js

Me too, I just downgrade antd to 4.11.2 and the warning is gone 
I'm using nextjs 10.0.7 and react 17.0.1 with next-plugin-antd-less 0.3.0

**Comment by yohaneslumentut** [comment]
This might be nextjs issue. Please check [https://github.com/vercel/next.js/issues/12863](url)

**Comment by yohaneslumentut** [comment]
This might be nextjs issue. Please check [https://github.com/vercel/next.js/issues/12863](https://github.com/vercel/next.js/issues/12863)

**Comment by nadam131** [comment]
I guess it's should to be reopen. 

`"antd": "^4.13.0",`
`"next": "^10.0.7",`

Vertical gutter works fine in dev now, but not in production. I have static prerender pages (getStaticPaths + getStaticProps) in Next.js and after build there is no vertical space.

**Comment by crazyshakalaka** [comment]
> 在next.js中使用antd也会遇到相同的问题
请问你解决了吗 可以说一下怎么解决的吗

**Comment by crazyshakalaka** [comment]
> > Have the same issue using antd with next.js
> 
> Me too, I just downgrade antd to 4.11.2 and the warning is gone
> I'm using nextjs 10.0.7 and react 17.0.1 with next-plugin-antd-less 0.3.0

···
Yes the rollback version to 4.11.2 will fix this problem
···

**Comment by sagars01** [comment]
> I guess it's should to be reopen.
> 
> `"antd": "^4.13.0",`
> `"next": "^10.0.7",`
> 
> Vertical gutter works fine in dev now, but not in production. I have static prerender pages (getStaticPaths + getStaticProps) in Next.js and after build there is no vertical space.
> 
> Also error `Warning: Prop style did not match. Server: "null" Client: "row-gap:0" at div` still in development mode

Got fixed for me here.
```
"antd": "^4.15.0",
"next": "10.0.7",
```
