### ISSUE TITLE
迷你型table标题与内容未对齐

### ISSUE THREAD

**Issue by PeteLuo** [ant-design/ant-design#2933]
#### 本地环境

- antd 版本: 1.11.0
- 操作系统及其版本：win7 64旗舰
- 浏览器及其版本: chrome 52.0.2743.116 m

#### 你做了什么？
使用一个table组件

#### 你期待的结果是：
size为small的时候正常显示（备注：size为default可以正常显示，为small时不能）

#### 实际上的结果：
表格标题与内容未对齐
![default](https://cloud.githubusercontent.com/assets/18900661/18202274/b21434d8-7141-11e6-85d0-593142c8aad2.jpg)

#### 可重现的在线演示
http://codepen.io/PeteLuo/pen/XKgVaW

**Comment by ddcat1115** [comment]
重现条件：

- size="small" 且无fixed: 'left'或fixed: 'right'
- 或 size="small"且bordered
