### ISSUE TITLE
IE11下selecet组建设置value的值不存在于渲染option的值里时导致报错 阻止页面渲染

### ISSUE THREAD

**Issue by jianghaoran116** [ant-design/ant-design#29333]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js)

### Steps to reproduce
1. select组建的值为一个默认的值 比如为1
2. 渲染option的值为异步返回[{value: 2, name: 'test'}]
3. IE11会报错对象不支持属性find... ，从而阻止页面渲染

### What is expected?
若组建的值不在渲染的值里时不应导致报错

### What is actually happening?
谷歌下没问题
我这是IE11下刷新页面出现的问题（不刷新的时候数据会由其他组件取回来） 刷新时数据异步获取，然后Select的值(value字段)和渲染option的值匹配不上，IE11会报错
我页面里去掉selecet组件没有问题～

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16  |
| System | windows |
| Browser | IE11 |

**Comment by afc163** [comment]
你需要 Array.prototype.find 等的 polyfill。
