### ISSUE TITLE
Typography.Paragraph ellipsis not rescale after space is free

### ISSUE THREAD

**Issue by huyennbl** [ant-design/ant-design#29344]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/typography-not-scaling-2qc8p)

### Steps to reproduce
Select some options in the Select component then remove the options

### What is expected?
Paragraph component should rescale to fill the empty space between itself and Select component

### What is actually happening?
Paragraph component is not rescaling, leaving spaces between itself and Select component

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Firefox 85, Chrome 88 |

**Comment by huyennbl** [comment]
I've figured out the workaround for this problem, setting `.ant-typography.ant-typography-ellipsis ` with css `flex: 1`
So I'm not sure if this is expected behaviour because I put the components inside a flex container or a bug 👀

**Comment by afc163** [comment]
https://codesandbox.io/s/typography-not-scaling-forked-8zdh7?file=/src/App.js

You are right, `flex: 1` is a correct way. I believe it is not a bug, flex container without `flex` will not fill the existed space.
