### ISSUE TITLE
The time format pasted by the user does not match the format setting, the paste cannot succeed(当datepicker设置的format属性为YYYY:mm:DD HH:mm 时,粘贴YYYY:mm:DD HH:mm:ss 格式的日期,组件的确定按钮不可点击)

### ISSUE THREAD

**Issue by lian8306** [ant-design/ant-design#29356]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-hawking-5tmno?file=/src/index.js)

### Steps to reproduce
Time to paste 19:02:2021 15:36:23 format

### What is expected?
When the format of datepicker is set to "DD: mm: yyyy HH: mm" and showTime, the time of pasting the format of 19:02:2021 15:36:23 will automatically discard seconds, or the response interface can be provided for self modification, such as Keyup event or onChange, which does not need to be triggered after onOk
---------
(当datepicker的format是 YYYY:mm:DD HH:mm 时,并且配置了显示时间,用户粘贴的时间格式为YYYY:mm:DD HH:mm:ss时,可以自动省略秒.或者提供响应的接口或者onChange时间的触发时机可以不关联onOk,以打到自定义行为的目的)

### What is actually happening?
When the format of datepicker is set to "DD: mm: yyyy HH: mm", pasting time of 19:02:2021 15:36:23 format fails
--------
(当datepicker设置的format属性为YYYY:mm:DD HH:mm 时,粘贴YYYY:mm:DD HH:mm:ss 格式的日期,组件的确定按钮不可点击)
| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17.0.1 |
| System | ubuntu |
| Browser | chrome |

---
The time format pasted by the user does not match the format setting

**Comment by zombieJ** [comment]
It's not bug. Paste should validate as format. Or you can set multiple format instead.
