### ISSUE TITLE
Table with sticky header: filter dropdown positions incorrectly on scroll

### ISSUE THREAD

**Issue by nekitk** [ant-design/ant-design#29366]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-table-with-sticky-header-and-filter-issue-8pvph)

### Steps to reproduce
1. Create table with sticky header and a filter in one of the columns
1. Click on filter icon in the column with filter
2. Without closing filter dropdown scroll page down so header becomes sticked to the top

### What is expected?
Filter dropdown shoud be positioned under column's header

### What is actually happening?
Filter dropdown moves up and away from the screen:
![](https://s.csssr.ru/U07B23NE8/2021-02-17-17-21-59-VQt4S.gif)

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser |  88.0.4324.150 |

---
I tried to add getPopupContainer={trigger => trigger.parentElement} to the Table, but that way filter dropdown is shown cropped inside header:
![](http://s.csssr.ru/U07B23NE8/2021-02-17-17-24-14-55i3T.jpg)

I found that adding getPopupContainer={trigger => trigger.parentElement} and setting overflow to visible on .ant-table-header is fixing it, but it breaks horizontal scrolling:
![](https://s.csssr.ru/U07B23NE8/2021-02-17-17-26-20-chl75.gif)

**Comment by afc163** [comment]
https://github.com/react-component/table/pull/410/files#diff-5136c989c296c26b5ee1d8662fbfd58d269e40e67a6f02b35f55442ab4835c3bR535

@shaodahong Could we remove `overflow: hidden` when no horizontal scroll bar in table header?

**Comment by nekitk** [comment]
It would be great to have ability to use sticky header and dropdown filter together with horizontal scroll if possible. We use all of these features together on mobile.

**Comment by shaodahong** [comment]
> https://github.com/react-component/table/pull/410/files#diff-5136c989c296c26b5ee1d8662fbfd58d269e40e67a6f02b35f55442ab4835c3bR535
> 
> Could we remove `overflow: hidden` when there is no horizontal scroll bar in table header?

It's broken when set scroll `x` and `y`, https://table.react-component.now.sh/demo/scroll-xy

**Comment by ZLester** [comment]
Also noticing the same issue when a dropdown appears in an open drawer and you scroll the page down

**Comment by desoss** [comment]
@ZLester There's another issue for the drawer [here](https://github.com/ant-design/ant-design/issues/29894)

**Comment by afc163** [comment]
5.x is good now: https://codesandbox.io/s/ant-table-with-sticky-header-and-filter-issue-forked-jj2jjg?file=/index.js

**Comment by wjj5728** [comment]
用了一个hack的方式解决了 [https://codesandbox.io/s/ant-table-with-sticky-header-and-filter-issue-forked-gcdpjw?file=/index.js](url)
