### ISSUE TITLE
ANTD TABLE: Row borders disappear when hover over rows from top to bottom and property 'bordered' is used.

### ISSUE THREAD

**Issue by zhulien-ivanov** [ant-design/ant-design#29362]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-brook-0g4uo)

### Steps to reproduce
Hover over the table rows from top to bottom(downwards).

### What is expected?
The table row borders should stay intact.

### What is actually happening?
Table row borders disappear until the row gets hovered again but this time upwards.

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react 17.0.1 |
| System | Windows 10 |
| Browser | Chrome 88.0.4324.150 / Edge |

---
As I thought this is a really peculiar and strange issue, I first checked if it is not actually some kind of "feature" but couldn't find any evidence backing that up.

**Comment by zombieJ** [comment]
Could you provide gif for this? Seems I can not reproduce it. Maybe I miss something.

**Comment by afc163** [comment]
<img width="709" alt="图片" src="https://user-images.githubusercontent.com/507615/108481652-6b5f3680-72d3-11eb-8c0e-ee619046e61b.png">

Codesandbox looks fine.

**Comment by zhulien-ivanov** [comment]
Here is what happens:

![demo](https://user-images.githubusercontent.com/16573678/108483461-6da99c80-72a3-11eb-9e5a-0865e3fff830.gif)

It is peculiar, because I just noticed it doesn't happen if I zoom the window. I am using a 4K screen so I suppose it should be related to resolution/graphical drivers if it is not reproducible elsewhere.

**Comment by afc163** [comment]
It should be render issue of Chrome in large screen, nothing we can do about it.

**Comment by zhulien-ivanov** [comment]
Yes, I understand. I was curious why I'm the first one encountering this issue, now I know. It can be closed. Thank you.
