### ISSUE TITLE
Filter the table data after it is empty. Current equals 0

### ISSUE THREAD

**Issue by SSW-imp** [ant-design/ant-design#29364]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/74ygx)

### Steps to reproduce
使用筛选条件过滤表格数据为空之后 在进行筛选current 为 0

### What is expected?
current 为 1

### What is actually happening?
current 为 0

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
给一下具体的操作步骤哈，我这边看 current 好像是 1：

<img width="612" alt="截屏2021-02-19 下午4 37 42" src="https://user-images.githubusercontent.com/5378891/108479510-cb081280-72d0-11eb-818f-048bbe2f3489.png">

**Comment by SSW-imp** [comment]
![image](https://user-images.githubusercontent.com/55080561/108481911-bc6f2a80-72d3-11eb-8ad6-47f11d97419d.png)
![image](https://user-images.githubusercontent.com/55080561/108481933-c2650b80-72d3-11eb-8cca-cfb8105b6abd.png)
先选择一个没有数据的xuanxiang选项 然后再继续进行筛选或者重置就会变成0 @zombieJ

**Comment by jinchaofs** [comment]
我来修复这个问题，稍后会提pull request

**Comment by kerm1it** [comment]
Fix in https://github.com/ant-design/ant-design/pull/29386
