### ISSUE TITLE
Available item count 0 on right when using tree within Transfer

### ISSUE THREAD

**Issue by gRoberts84** [ant-design/ant-design#29375]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1zo2o?file=/index.js)

### Steps to reproduce
Create a Tree Transfer with the Tree on both sides.

### What is expected?
Available items should reflect the number of keys passed via `targetKeys`.

### What is actually happening?
Available item count is 0 regardless of how many items are displayed on the right.

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17.0.1 |
| System | N/A |
| Browser | N/A |

---
The [Tree Transfer](https://ant.design/components/transfer/#components-transfer-demo-tree-transfer) example seems incomplete as most would expect the tree to appear on both sides.

In an attempt to rectify this for my use, I have found that whilst the Selected/Available counts on the left Tree are correct, the Available count on the right is always 0.

Shouldn't the Transfer take the Available numbers from the `transferKeys` property on Transfer?

<img width="524" alt="Screenshot 2021-02-19 at 17 02 42" src="https://user-images.githubusercontent.com/348184/108536397-58009b00-72d4-11eb-88f8-034af65ec04c.png">

The above should say `1/4 - 1/2` not `1/4 - 1/0`

**Comment by zombieJ** [comment]
Hi @gRoberts84,
Tree Transfer example is a demo provides the customize selection ability of Transfer. If you want to show different interactive of it, you should realize right part logic instead. And why not just use single tree when both left & right is a tree?

Besides the interactive. `selectedKeys` is checked keys on the left part. And `targetKeys` is the checked keys on the right part and that's what `transferKeys` you want. You can check the [Basic Demo](https://ant.design/components/transfer/#components-transfer-demo-basic) to check the difference.

Thanks

**Comment by gRoberts84** [comment]
Hi @zombieJ,

Apologies, either I have confused the situation or you have misunderstood.

To clarify, the issue is in relation to the headers, i.e. `1/4 Permissions` and `1/0 Permissions` shown in my screenshot.

The left (source) is working as expected, however the right is not. Instead of showing `1/2 Permissions` based on the 2 keys passed to `targetKeys` it's showing 0. 

If this is not possible, can you advise on how to hide it?
