### ISSUE TITLE
Typography editable on cancel event

### ISSUE THREAD

**Issue by Acidic9** [ant-design/ant-design#29371]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Typography editable has two events: `onStart`, `onChange`, but in my situation, I need an `onCancel`/`onEnd` event too.

This is so I can keep track of whether the element is being edited or not.
In my specific use case, I am replacing `\n` with `<br />` **only** when the text is **not** being edited. And when it **is** being edited, I will not replace the `\n` characters.

### What does the proposed API look like?
An example of editable paragraph:
```js
<Typography.Paragraph
  editable={{
    onStart={() => setIsEditing(true)}
    onEnd={() => setIsEditing(false)} // <- This is the new prop
    onChange={() => setIsEditing(false)}
  }}
>
```

With `onEnd` property will fire when the user ends the editing of the field. It could also be `onCancel` which would only fire when they cancel editing.

**Comment by jueinin** [comment]
I will provide a PR for this feature @zombieJ

**Comment by wc-matteo** [comment]
@jueinin the blur event is missing from onEnd (it also modifies the value)
https://github.com/ant-design/ant-design/blob/13a829d20c8a1a83c3bfa1f9d7c30d95659f5b57/components/typography/Editable.tsx#L104
