### ISSUE TITLE
Suppress the tree-shaking warning on development builds

### ISSUE THREAD

**Issue by cuibonobo** [ant-design/ant-design#29378]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This pertains to developer experience. Often the development tools with live-reloading do not enable tree-shaking so that rebuilds can happen quickly, but it is not useful to see the `You are using a whole package of antd, please use...` warning in the console with every rebuild. It would be better to only show this warning on production builds (i.e. where `process.env.NODE_ENV === 'production'`).

### What does the proposed API look like?
This would not be an API change. It would only affect when the tree-shaking warning is displayed in the console.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/antd-tools/pull/230, next version will carry this fix.
