### ISSUE TITLE
DatePicker默认值设置失败

### ISSUE THREAD

**Issue by KidneyFlower** [ant-design/ant-design#2938]
#### 本地环境

- antd 版本:最新版本
- 操作系统及其版本：Mac OS X 10.11.6
- 浏览器及其版本: Chrome 52.0.2743.116 (64-bit)

#### 你做了什么？

引入了DatePicker组件，设置了defaultValue如下
  defaultDate:  () => {
      let date = new Date()
      let str = date.getFullYear()+"-"+(date.getMonth()+1)+"-"+date.getDate();
      return str
    }
但是抛出了异常："calendar must be type of GregorianCalendar"

#### 你期待的结果是：

可以让默认值显示为当天日期

#### 实际上的结果：
"calendar must be type of GregorianCalendar"

**Comment by ddcat1115** [comment]
未能重现，并且如果要默认显示当天日期，可以直接传 Date 对象：

```javascript
<DatePicker defaultValue={new Date()}  />
```
