### ISSUE TITLE
Menu是否可以增加实现向左折叠的功能

### ISSUE THREAD

**Issue by k3cloudqxy** [ant-design/ant-design#2939]
#### 本地环境

- antd 版本:1.9.0
- 操作系统及其版本：Window7  64位
- 浏览器及其版本: Firfox 48.0.2

#### 你做了什么？
引入菜单  添加菜单项

#### 你期待的结果是：菜单向左折叠，以节省页面空间
[希望的效果](http://222.198.128.203:80/group1/M00/00/03/3saAy1fNC-SAJFDLAACYVf7NUnA558.png)

#### 实际上的结果：
不能实现向左折叠

**Comment by codering** [comment]
http://ant.design/docs/spec/layout#docs-spec-layout-demo-aside-collapse

**Comment by k3cloudqxy** [comment]
好的  感谢  原来没找到地方
