### ISSUE TITLE
Table组件设置scroll可以横向滚动，dataSource数据为空，table表头样式异常问题

### ISSUE THREAD

**Issue by 224137748** [ant-design/ant-design#29395]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-matsumoto-qn71l)

### Steps to reproduce
需求是展现一个表格，Table设置scroll 横向纵向滚动范围时，期望出现横向的滚动条，当鼠标拖动横向滚动条的时候期望表头跟着一起滚动。

scroll参数x，可以定义百分比，true 和 'max-content'，也希望官网补充说明一下 true和百分比的区别。

我的Table组件配置参数如下：
```javascript
<div className="App">
      <Table
        className="table-demo"
        // dataSource={dataSource}
        dataSource={[]}
        columns={columns}
        scroll={{ x: true, y: 100, scrollToFirstRowOnChange: true }}
      />
      ;
    </div>
```
问题1：

// 步骤：当 scroll 设置 x为true，dataSource不为空时，表现正常，但是dataSource为空数组[]，此时表头会出现样式错误

问题2：

// 步骤：当 scroll 设置x为‘100%’或者其他值时，表头不跟随横向滚动

我尝试定位一下问题，发现将 scroll={{y:100}} 纵向滚动的参数y删除后，就不会有问题了。

### What is expected?
Table设置scroll 横向纵向滚动范围时，期望出现横向的滚动条，当鼠标拖动横向滚动条的时候期望表头跟着一起滚动。

### What is actually happening?
实现不了或者 Table表头样式出现异常

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 17.01 |
| System | window 10 |
| Browser | chrome  88.0.4324.182 |

**Comment by FateTestrossa** [comment]
3.x早期版本设置为true时：表格列宽会自适应并出现滚动条。
3.x后期版本值4.x版本设置为true时：列宽不会自适应了，也不会出现滚动条。
我也很好奇true到底代表啥意思。

**Comment by FateTestrossa** [comment]
3.x早期版本设置为true时：表格列宽会自适应并出现滚动条。
3.x后期版本至4.x版本设置为true时：列宽不会自适应了，也不会出现滚动条。
我也很好奇true到底代表啥意思。
