### ISSUE TITLE
table的render里面使用form.item 不能使用动态渲染问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#29400]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaogekuanduwuxiao-cmydb?file=/index.js)

### Steps to reproduce
根据代码实例，我的本意是出入test名字的时候。age 的input 就disabled 掉，但是无效。但是现在发现渲染都渲染不出来。

### What is expected?
应该name 输入 test的时候，disabled无效，

### What is actually happening?
1：无法渲染。
2：让shouldupdate 可以影响到局部刷新。

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
columns={函数()} 从一个函数获得

**Comment by zombieJ** [comment]
<img width="697" alt="截屏2021-02-22 上午11 16 49" src="https://user-images.githubusercontent.com/5378891/108652581-77c7d700-74ff-11eb-915a-4bbbabf63a91.png">

`renderProps` 没有 `name`，参考一下官方例子。

**Comment by xgj1988** [comment]
> <img alt="截屏2021-02-22 上午11 16 49" width="697" src="https://user-images.githubusercontent.com/5378891/108652581-77c7d700-74ff-11eb-915a-4bbbabf63a91.png">
> 
> `renderProps` 没有 `name`，参考一下官方例子。

你说的官方例子是哪个？？
