### ISSUE TITLE
Menu组件收起的时候，会闪烁，很急，还希望快速回复一下

### ISSUE THREAD

**Issue by lgf196** [ant-design/ant-design#29401]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sider-antd4102-forked-6192e?file=/compent/slider.jshttps://codesandbox.io/s/sider-antd4102-forked-6192e?file=/compent/slider.js)

### Steps to reproduce
当选中之后，点击收起按钮之后，menu组件收起，收起过程中会出现二级菜单收起闪烁，多点击几下收起按钮，就会出现这个bug

### What is expected?
我不希望，多次点击收起按钮，出现子菜单收起的情况

### What is actually happening?
我不希望，多次点击收起按钮，出现子菜单收起的情况

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | window |
| Browser | 谷歌 |

**Comment by afc163** [comment]
升级到 4.12.3 试试：https://codesandbox.io/s/sider-antd4102-forked-7468b?file=/index.js

**Comment by lgf196** [comment]
> 升级到 4.12.3 试试：https://codesandbox.io/s/sider-antd4102-forked-7468b?file=/index.js

我升级到4.12.3版本还是出现了如上的问题

**Comment by afc163** [comment]
给个重现，我上面的 codesandbox 里貌似没问题了。

**Comment by lgf196** [comment]
> 给个重现，我上面的 codesandbox 里貌似没问题了。
![20210218_184646](https://user-images.githubusercontent.com/29600558/108649534-8068df00-74f8-11eb-982e-7f2b75e0b42c.gif)
codesandbox地址：https://codesandbox.io/s/sider-antd4102-forked-7468b?file=/index.js

**Comment by darkerk** [comment]
遇到同样的问题，但是官方demo没有问题，https://codesandbox.io/s/wh2t9

**Comment by zombieJ** [comment]
嗯，更新到最新的版本也有这个问题 https://codesandbox.io/s/sider-antd4102-forked-uzllx

`rc-menu` 里动画触发阶段不是全受控，用了 raf 修了闪动问题。但是因为不是同步的还是会有漏，特别蛋疼。

**Comment by darkerk** [comment]
如果自己实现menu的openKeys就会出现这个问题

**Comment by afc163** [comment]
是这个问题：https://github.com/ant-design/ant-design/issues/27995

https://github.com/react-component/menu/pull/351#issuecomment-733499503 的修改引起的。

**Comment by afc163** [comment]
合并至 #27995 ，各位可以去这里继续讨论和跟踪。

**Comment by lgf196** [comment]
> 嗯，更新到最新的版本也有这个问题 https://codesandbox.io/s/sider-antd4102-forked-uzllx
> 
> `rc-menu` 里动画触发阶段不是全受控，用了 raf 修了闪动问题。但是因为不是同步的还是会有漏，特别蛋疼。

官方大概什么时候可以修复一下这个bug
