### ISSUE TITLE
Upload组件在chrome 88上无法打开本地文件选择对话框

### ISSUE THREAD

**Issue by quicklearning123** [ant-design/ant-design#29409]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
必现

### What is expected?
可以打开本地文件选择框

### What is actually happening?
点击上传按钮无响应

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16 |
| System | mac |
| Browser | chrome 88 |

**Comment by afc163** [comment]
我这里测试能打开。

**Comment by afc163** [comment]
看看是不是这个问题 https://github.com/ant-design/ant-design/issues/11787#issuecomment-414583013

**Comment by quicklearning123** [comment]
> 看看是不是这个问题 [#11787 (comment)](https://github.com/ant-design/ant-design/issues/11787#issuecomment-414583013)

不是这个问题。看他描述是选择完文件路径后无响应卡住
我这边的现象是，点按钮无响应，无法打开选择文件框。控制台没看到异常日志

**Comment by quicklearning123** [comment]
![image](https://user-images.githubusercontent.com/70048681/108868699-6f6fb900-7631-11eb-9d97-faa7305e33a6.png)

**Comment by afc163** [comment]
检查一下浏览器扩展，挨个打开关闭排查一下。

**Comment by xrkffgg** [comment]
你是一直这样 还是最近才有的？

检查下 设置的 隐私 看看

其他浏览器呢？

**Comment by SharkBaby** [comment]
> ![image](https://user-images.githubusercontent.com/70048681/108868699-6f6fb900-7631-11eb-9d97-faa7305e33a6.png)

@quicklearning123 请问你们排查出来是什么问题造成的了吗？我们这边偶尔也会出现类似的问题，但是是极小概率会发生，不知道是不是和用户使用的浏览器设置有关系，麻烦有相关方案可以回复一下
