### ISSUE TITLE
table组件设置scroll={{ x: 'max-content'}}时，固定列（如fixed:'left'）的宽度设置失效

### ISSUE THREAD

**Issue by oldturkey** [ant-design/ant-design#29406]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-antd4123-forked-p3xv8)

### Steps to reproduce
见链接

### What is expected?
宽度可以控制

### What is actually happening?
宽度不可控，完全显示最大宽度

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8 |
| System | 10.15.7  |
| Browser | chrome |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/jibenyongfa-antd4123-forked-ksvdw?file=/index.js

`column.ellipsis` 是通过 `nowrap` + `overflow` 实现，所以 `max-content` 会按照 `nowrap` 计算宽度。可以使用 Typography 的 `ellipsis` 来实现限定宽度的自适应。

**Comment by oldturkey** [comment]
> https://codesandbox.io/s/jibenyongfa-antd4123-forked-ksvdw?file=/index.js
> 
> `column.ellipsis` 是通过 `nowrap` + `overflow` 实现，所以 `max-content` 会按照 `nowrap` 计算宽度。可以使用 Typography 的 `ellipsis` 来实现限定宽度的自适应。

谢谢！我的实际使用场景里，列宽是动态的，希望能根据宽度自适应显示内容多少。我看看能不能用Typography去实现。。

**Comment by oldturkey** [comment]
> https://codesandbox.io/s/jibenyongfa-antd4123-forked-ksvdw?file=/index.js
> 
> `column.ellipsis` 是通过 `nowrap` + `overflow` 实现，所以 `max-content` 会按照 `nowrap` 计算宽度。可以使用 Typography 的 `ellipsis` 来实现限定宽度的自适应。

这个例子还有个问题，我发的例子里面，fixed的第一列宽度失效，但是后面几列没fixed宽度是可以调整的。。
