### ISSUE TITLE
Inconsistent behaviour on <Table> if a dataIndex is named "children"

### ISSUE THREAD

**Issue by andres-dc** [ant-design/ant-design#29402]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-sinoussi-mfi4w?file=/src/App.js)

### Steps to reproduce
When creating the table columns, one of the dataIndex must be named "children". This causes the page to not render and throw errors in some cases.

If the incoming data for the "children" column contains truthy values (1, "hello", true, etc), the page doesn't render.

If the incoming data for the "children" column contains falsy values (0, null, false), the page renders.

### What is expected?
The page should render no matter what value is available for the column called "children".

### What is actually happening?
Multiple errors

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Arch Linux x86_64 Kernel: 5.10.17-1-lts |
| Browser | Firefox 85 / Vivaldi 3.6 |

**Comment by afc163** [comment]
`children` is a reserved key in dataSource for tree structure: https://ant.design/components/table/#components-table-demo-tree-data

You can disable this feature by setting `childrenColumnName` to another value.
