### ISSUE TITLE
When the 'showTime' property of DatePicker is 'true', hover date options, placeholder is wrong

### ISSUE THREAD

**Issue by WayneGongCN** [ant-design/ant-design#29412]
当 DatePicker 的 showTime 属性为 true时，hover 日期选项 placeholder 显示错误。

---
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/otem2)

### Steps to reproduce
- DatePicker 的 showTime 属性为 true；
- 点击时间选择器；
- hover 到任一日期选项，placeholder 中出现当前 hover 日期，且时间为系统时间；
- hover 到其他日期选项，placeholder 中日期变动，且时间也会变动；
- 切换月份；
- 此时 hover 到任一日期选项，placeholder 的时间不会更新；

### What is expected?
在最后一步中，hover 到任一日期选项，placeholder 的时间依然更新。

### What is actually happening?
切换月份后，placeholder 的时间不会更新；

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome 88.0.4324.182 |

**Comment by afc163** [comment]
好细节的体验问题。@kerm1it 看看能怎么优化一下。

**Comment by kerm1it** [comment]
可以录个 gif 看看么？我试了试，没明白什么意思? @WayneGongCN

**Comment by WayneGongCN** [comment]
> 可以录个 gif 看看么？我试了试，没明白什么意思? @WayneGongCN

![image](https://user-images.githubusercontent.com/20236883/108690924-df991480-7535-11eb-8d1b-44486ca34811.png)

简单来讲，就是在切换月份后，再次 hover 日期时，placeholder 的 time 不会更新了；

**Comment by kerm1it** [comment]
明白了，其实这个更新是个意外情况，预期应该是不更新的😂，我有时间看看
