### ISSUE TITLE
form-label 长度自适应

### ISSUE THREAD

**Issue by Xie-Jay** [ant-design/ant-design#29413]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
根据 `<label>` 元素中 `textContent` 字符串长度(max)调整 `.ant-form-item-label` 元素长度

### What does the proposed API look like?
autoLabel: boolean

**Comment by zombieJ** [comment]
`label` 不配置的时候本身就是自适应的。我猜测你需要估计是多个 Form.Item 之间的 label 宽度同步。这个从 antd 层其实是不知道开发者怎么组合页面的：

```text
| Form.Item | Form.Item |
|       Form.Item       |  （和 3 行应该相同）
|       Form.Item       |  （和 2 行应该相同）
```

我推荐你可以使用 ResizeObserver 封装一个同步宽度的 Label 组件。
