### ISSUE TITLE
How to set warning styles for form.item after it's values was modified, if there are no required: true rule ?

### ISSUE THREAD

**Issue by nichitapasecinic** [ant-design/ant-design#29419]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd4103-forked-2pl30?file=/index.js)

### Steps to reproduce
DUMMY URL

### What is expected?
validateStatus is should trigger when the value from inside it its modified

### What is actually happening?
its not 

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react ^16.0 |
| System | Windows 10 Pro |
| Browser | Chrome |

---
I have a conditional operator for validateStatus = { isTouched ? "warning" : ""}
and isTouched is either true/false, in dependence if the field is touched, so how do I get it to work and to trigger validateStatus and apply warning styles ?
THX

**Comment by nichitapasecinic** [comment]
Just how to dynamically change validateStatus property from "" to warning ?

**Comment by nichitapasecinic** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-5t696?file=/index.js

**Comment by nichitapasecinic** [comment]
> Just how to dynamically change validateStatus property from "" to warning ?

https://codesandbox.io/s/antd-reproduction-template-forked-5t696?file=/index.js

**Comment by afc163** [comment]
You should use React state, please learn from https://reactjs.org/docs/state-and-lifecycle.html
