### ISSUE TITLE
Antd Tree selectedKeys and defaultSelectedKey don't highlight more than 1 items

### ISSUE THREAD

**Issue by kissa1001** [ant-design/ant-design#29415]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/draggable-antd4123-forked-htdr0?file=/index.js)

### Steps to reproduce
Either specifying defaultSelectedKeys or selectedKeys array just have one tree item highlighted. 

### What is expected?
Expected all keys specified in selectedKeys/defaultSelectedKeys to be highlighted.

### What is actually happening?
Only highlights the first item in selectedKeys/defaultSelectedKeys array

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react |
| System | MAC OS |
| Browser | Chrome |

---
I'm working on the application where I need to do multiple items select on shift key hold. So I need to control over the selectedKeys array. However, when I pass the array to selectedKeys, it highlights only the first item.

**Comment by afc163** [comment]
You need `multiple`: https://codesandbox.io/s/draggable-antd4123-forked-ii3e5?file=/index.js
