### ISSUE TITLE
form.resetFields() cause Form.Item.children re-mount

### ISSUE THREAD

**Issue by jeeeez** [ant-design/ant-design#29423]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-imm0c?file=/index.js)

### Steps to reproduce
在上述 codesandbox 链接的控制台中我们能看到因为执行了 form.resetFields() 导致 FormChild 组件被销毁并重新装载了。

In the above codesandbox link, the FormChild component was `unmounted` and `re-mount` due to the execution of form.resetFields().

### What is expected?
The FormChild component just `mount` once

### What is actually happening?
The FormChild component just `mount` twice

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | MAC OS |
| Browser | Chrome 88.0.4324.182 |

**Comment by zombieJ** [comment]
It's by design: https://ant.design/components/form-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-resetFields-%E4%BC%9A%E9%87%8D%E6%96%B0-mount-%E7%BB%84%E4%BB%B6%EF%BC%9F
