### ISSUE TITLE
menu selected key duplicated css status

### ISSUE THREAD

**Issue by stormrise** [ant-design/ant-design#29429]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/stormrise/pen/BaQmyed](https://codepen.io/stormrise/pen/BaQmyed)

### Steps to reproduce
使用selectedKeys时，如果两个menuitem key值 前缀相同，一个更长，如key='item1' key='item11'，当没有传入数组给selectedKeys，而是直接传入了字符串（因为我只需要选择一个，虽然不知道我这个用法合不合理），就会出现两个都被选择的css样式

### What is expected?
只有一个选择高亮

### What is actually happening?
两个选择高亮

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.9.0 |
| System | win10 |
| Browser | chrome88 |

---
改为传入数组[string]而不是string 可以解决，但是我觉得这个可能不太合理，因为我的menu只需要选择一个

**Comment by afc163** [comment]
selectedKeys 的类型就是数组，不支持字符串，目前的选中应该是巧合。

**Comment by stormrise** [comment]
> selectedKeys 的类型就是数组，不支持字符串，目前的选中应该是巧合。

OK， 我看了下源码。发现是rc-menu就是这么定义的，不过我字符串传进去了也是很奇怪，还用了很久

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/menu/releases/tag/v8.10.6
