### ISSUE TITLE
Badge count digits disappearing in Firefox

### ISSUE THREAD

**Issue by EliasHjelm** [ant-design/ant-design#29420]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-badge-firefox-bug-hx472?file=/index.js)

### Steps to reproduce

Visit reproduction link in Firefox browser (I use version 85.0.1)

Hover over the menu item with the badge - the 5 will disappear.

Refresh and click in the space between the menu and the heading below - both 5's will disappear.

### What is expected?
Badge count digits do not disappear.

### What is actually happening?
Badge count digits disappear from view.

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Ubuntu 20.04.2 |
| Browser | Firefox 85.0.1 |

---
I was only able to reproduce this bug in the Firefox browser.

**Comment by afc163** [comment]
I can't reproduce, could you provide a gif or video?

**Comment by EliasHjelm** [comment]
[Here](https://webmshare.com/6VxPz) is a screen capture of the interaction.

**Comment by afc163** [comment]
I can't reproduce it Firefox of MacOS, it should be a rendering issue of Ubuntu Firefox.

Nothing we can do about it.

**Comment by EliasHjelm** [comment]
Allright, thank you for taking the time to investigate this. I will close the issue
