### ISSUE TITLE
Tooltips on parent page not closing when modal is opened

### ISSUE THREAD

**Issue by rahulthewall** [ant-design/ant-design#29443]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd4123-forked-drh9l)

### Steps to reproduce
1. Create a Modal that renders on a button
2. Export the Modal as a component
3. Wrap the component with a Tooltip
4. When you open the Modal the Tooltip remains

### What is expected?
The Tooltip disappears (it disappears in the Modal.confirm implementation)

### What is actually happening?
The tooltip remains

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react-17.0.1 |
| System | OS X 10.15.7 |
| Browser | Chrome 88.0.4324.192 |

**Comment by afc163** [comment]
```tsx
      <Tooltip title="title">
        <Button type="primary" onClick={showModal}>
          Open Modal
        </Button>
      </Tooltip>
      <Modal
        title="Basic Modal"
        visible={isModalVisible}
        onOk={handleOk}
        onCancel={handleCancel}
      >
        <p>Some contents...</p>
        <p>Some contents...</p>
        <p>Some contents...</p>
      </Modal>
```

**Comment by rahulthewall** [comment]
Thank you @afc163!

**Comment by pppp606** [comment]
Thank you, @afc163! Your code helped me resolve an issue I was facing. It turns out that having the Modal inside the Tooltip was the root cause.

```jsx
// Code that caused the issue
<Tooltip>
  <Modal />
</Tooltip>

// Adjusted code that resolved the issue
<Tooltip></Tooltip>
<Modal />
```

I was puzzled for a while as I couldn't figure out what was wrong, so I thought I'd leave a comment here for anyone else who might encounter the same issue. Thank you for maintaining such a useful library!
