### ISSUE TITLE
Transfer, filterOption only applies when search contains text

### ISSUE THREAD

**Issue by xseman** [ant-design/ant-design#29440]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-yq524)

### Steps to reproduce
`Transfer` component, `filterOption` filter by any condition

### What is expected?
`filterOption` should filter items without the required input search

### What is actually happening?
`filterOption` doesn't apply the filter, only if `showSearch={true}` and search `Input` contains atleast one character

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17 |
| System | Linux debian 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux |
| Browser | Firefox 86 |

**Comment by afc163** [comment]
It is by designed, filterOption works only when search text.

**Comment by xseman** [comment]
So there isn't any way to force filter when using external conditions?

**Comment by mihaineghinbend** [comment]
Why this is closed ? Is there a way to filter using external conditions ?

**Comment by mihaineghinbend** [comment]
> So there isn't any way to force filter when using external conditions?

Have you managed to do it ?

**Comment by xseman** [comment]
@mihaineghinbend 
unfortunately not, but I managed to do what I wanted by handling `dataSource` of `<Transfer/>` in another component.
