### ISSUE TITLE
border-color-split vs border-color-base

### ISSUE THREAD

**Issue by almassapargali** [ant-design/ant-design#29447]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://github.com/ant-design/ant-design/blob/f7a36de6988943a065a0454624610f8d482083ac/components/style/themes/default.less#L134-L135

### Steps to reproduce
Use `@border-color-split` variable for `split border inside a component`, and `@border-color-base` for `base border outline a component` as stated in the comments.

### What is expected?
Table's and Card's outer border colored by `@border-color-base`, and inner borders colored by `@border-color-split`.

### What is actually happening?
Everything colored using `@border-color-split`.

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | macOS 10.15 |
| Browser | Chrome Version 88.0.4324.182 (Official Build) (x86_64) |

---
I'd like to have darker color for outer borders, and subtle color for inner borders, but currently I can't achieve that through variables, despite the comments stating otherwise.

Link to the `@table-border-color` definition:
https://github.com/ant-design/ant-design/blob/f7a36de6988943a065a0454624610f8d482083ac/components/style/themes/default.less#L604

It's used as the only border color in `table/bordered.less`: https://github.com/ant-design/ant-design/blob/master/components/table/style/bordered.less

Link to the Card bordered style:
https://github.com/ant-design/ant-design/blob/f7a36de6988943a065a0454624610f8d482083ac/components/card/style/index.less#L32-L34

**Comment by yingxirz** [comment]
We’re working on this issue recently. Our recommendation is that "border-color-base" the darker one is use for smaller elements such as “button””input field”or “”checkbox” ,the lighter one "border-color-split" for background area which takes larger places and you don’t want to emphasize them, such as “card border””divider” “table grids”etc~~

**Comment by almassapargali** [comment]
@yingxirz @afc163 how can I set the outer borders of table to be darker, while keeping inner borders (split) light? Currently there is no way, as table uses split color for any borders.

**Comment by almassapargali** [comment]
?
