### ISSUE TITLE
modal.update() doesn't work when called immediately after opening the modal via hook

### ISSUE THREAD

**Issue by haggen** [ant-design/ant-design#29441]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modalupdate-not-working-n5okh)

### Steps to reproduce
1. Call the hook to get a contextualized helper `const [modal] = Modal.useModal()`
2. Call a modal method, like modal.info() and save the returning instance `const m = modal.info({ title: "Original" })`
3. Immediately call the update method on the instance `m.update({ title: "Changed" })`

### What is expected?
I would expect the modal to have its title changed to "Changed"

### What is actually happening?
The title stays "Original"

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.14.0 |
| System | Window 10 |
| Browser | Chrome 88 |

---
I needed to trigger a context accessible modal, fetch some data and then conditionally update the modal content, which did not work due to this bug. The bug doesn't happen when you call `Modal.info()` directly instead of using the hook. Also, if you delay the execution of `modal.update()`, be it via setTimeout or a promise, it works.

**Comment by haggen** [comment]
If anyone come here looking for a solution, mine was to change the modal config (which is a state) in one useEffect and executing `modal.update(config)` in another. Also the modal instance is stored in a ref so I can access the same one in across renders.

**Comment by zombieJ** [comment]
> If anyone come here looking for a solution, mine was to change the modal config (which is a state) in one useEffect and executing `modal.update(config)` in another, effectively causing an extra re-render. Also the modal instance is stored in a ref so I can access the same one across re-render.

Yes. `update` is trigger when Modal mounted.
