### ISSUE TITLE
不支持windows ie11

### ISSUE THREAD

**Issue by wangtong12138** [ant-design/ant-design#29453]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://weiqidemo.yuyidata.com/](http://weiqidemo.yuyidata.com/)

### Steps to reproduce
打开之后log就报错了

### What is expected?
兼容ie11

### What is actually happening?
不兼容ie11

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 17.0.1 |
| System | win10 |
| Browser | ie11 |

**Comment by afc163** [comment]
You need polyfill and set correct target of @babel/preset-env.

**Comment by wangtong12138** [comment]
有没有example或者guidence




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 晚上6:52
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"若殇"<942578344@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 不支持windows ie11 (#29453)





 
You need polyfill and set correct target of @babel/preset-env.

**Comment by yoyo837** [comment]
看Babel 文档即可。
