### ISSUE TITLE
Uncaught (in promise) Error: Objects are not valid as a React child (found: Error: 手机号已被注册,请换一个重试). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons

### ISSUE THREAD

**Issue by oeddyo** [ant-design/ant-design#2945]
#### 本地环境

- antd 版本:

- 操作系统及其版本：Mac OS
- 浏览器及其版本: Chrome 版本 53.0.2785.89 (64-bit)

#### 你做了什么？

当用一个已经被注册的手机号注册时，期望用message.error(e)提示用户错误信息。但是报错如下：

Uncaught (in promise) Error: Objects are not valid as a React child (found: Error: 手机号已被注册,请换一个重试). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.(…)invariant @ invariant.js:38traverseAllChildrenImpl @ traverseAllChildren.js:136traverseAllChildren @ traverseAllChildren.js:164instantiateChildren @ ReactChildReconciler.js:71_reconcilerInstantiateChildren @ ReactMultiChild.js:189mountChildren @ ReactMultiChild.js:228_createInitialChildren @ ReactDOMComponent.js:698mountComponent @ ReactDOMComponent.js:523mountComponent @ ReactReconciler.js:47mountChildren @ ReactMultiChild.js:240_createInitialChildren @ ReactDOMComponent.js:698mountComponent @ ReactDOMComponent.js:523mountComponent @ ReactReconciler.js:47mountChildren @ ReactMultiChild.js:240_createInitialChildren @ ReactDOMComponent.js:698mountComponent @ ReactDOMComponent.js:523mountComponent @ ReactReconciler.js:47mountChildren @ ReactMultiChild.js:240_createInitialChildren @ ReactDOMComponent.js:698mountComponent @ ReactDOMComponent.js:523mountComponent @ ReactReconciler.js:47performInitialMount @ ReactCompositeComponent.js:385mountComponent @ ReactCompositeComponent.js:260mountComponent @ ReactReconciler.js:47performInitialMount @ ReactCompositeComponent.js:385mountComponent @ ReactCompositeComponent.js:260mountComponent @ ReactReconciler.js:47updateChildren @ ReactChildReconciler.js:122_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:941updateComponent @ ReactDOMComponent.js:759receiveComponent @ ReactDOMComponent.js:717receiveComponent @ ReactReconciler.js:126_updateRenderedComponent @ ReactCompositeComponent.js:761_performComponentUpdate @ ReactCompositeComponent.js:739updateComponent @ ReactCompositeComponent.js:658receiveComponent @ ReactCompositeComponent.js:552receiveComponent @ ReactReconciler.js:126updateChildren @ ReactChildReconciler.js:110_reconcilerUpdateChildren @ ReactMultiChild.js:210_updateChildren @ ReactMultiChild.js:314updateChildren @ ReactMultiChild.js:301_updateDOMChildren @ ReactDOMComponent.js:941updateComponent @ ReactDOMComponent.js:759receiveComponent @ ReactDOMComponent.js:717receiveComponent @ ReactReconciler.js:126_updateRenderedComponent @ ReactCompositeComponent.js:761_performComponentUpdate @ ReactCompositeComponent.js:739updateComponent @ ReactCompositeComponent.js:658performUpdateIfNecessary @ ReactCompositeComponent.js:566performUpdateIfNecessary @ ReactReconciler.js:158runBatchedUpdates @ ReactUpdates.js:151perform @ Transaction.js:138perform @ Transaction.js:138perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:173closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:201enqueueUpdate @ ReactUpdateQueue.js:25enqueueSetState @ ReactUpdateQueue.js:210ReactComponent.setState @ ReactComponent.js:64add @ antd.js:35048notice @ antd.js:35105notice @ antd.js:19310error @ antd.js:19342(anonymous function) @ index.js:77

#### 你期待的结果是：

代码：
 handleSubmit(e) {
        e.preventDefault();
        let inputs = this.props.form.getFieldsValue()

        if(inputs.invitationCodeApplied){
            return this.props.dispatch(validateInvitation(inputs.invitationCodeApplied))
                .then(
                    (({value, action}) => {
                            if(value.results.length != 0){
                                return false
                            }
                        }
                    )
                ).then(() => {
                let fields = this.props.form.getFieldsValue()
                // These shall be on server side but no we don't have a server...
                fields['username'] = fields['mobilePhoneNumber'] // Use phoneNumber as their login name
                fields['profileImageUrl'] = "avatar.png"
                return this.props.dispatch(createUser(fields))
            }).then(({value, action}) => {
                    const user = value
                    console.log(value)
                    if (user.hasOwnProperty('error')){
                        if(user.code === 214) {
                            throw new Error("手机号已被注册,请换一个重试")
                        } else {
                            throw new Error("注册时错误,请联系我们,错误代码:user.error")
                        }
                    }
                    // TODO(exie): handle error
                    let token = user.sessionToken
                    return localforage.setItem(
                        "token",
                        token
                    ).then(
                        (val, err) => {
                            console.log("and val = ", val)
                            return user
                        }
                    )
                }
            ).then( user => {
                    this.props.dispatch(createInvitations(user.objectId))
                        .then((invites) => {
                                console.log("invites are ", invites)
                                message.success("欢迎来到Wise!")
                                browserHistory.push('/')
                            }
                        )
                }
            ).catch(e => {
                    console.log(e)
                    message.error(e)
            })
        } else {
            message.error("验证码不能为空")
        }

    

package.json:
{
  "name": "wise-web",
  "version": "0.1.0",
  "main": "server.js",
  "keywords": [
    "express",
    "webpack",
    "node"
  ],
  "scripts": {
    "test": "mocha --compilers js:babel-register --recursive",
    "test:watch": "npm test -- --watch",
    "start": "node server",
    "build": "rimraf dist && cross-env NODE_ENV=production webpack --config ./webpack.production.config.js --progress --profile --colors",
    "eslint": "eslint .",
    "jscs": "jscs ."
  },
  "dependencies": {
    "antd": "^1.7.0",
    "autoprefixer": "^6.4.0",
    "babel-cli": "^6.4.0",
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-polyfill": "^6.9.1",
    "babel-preset-airbnb": "^2.0.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "babelify": "^7.3.0",
    "bluebird": "^3.4.2",
    "chai": "^3.5.0",
    "css-loader": "^0.24.0",
    "draft-js": "^0.7.0",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "html-webpack-plugin": "^2.22.0",
    "immutable": "^3.8.1",
    "leancloud-storage": "^1.3.2",
    "leanengine": "^1.2.1",
    "localforage": "^1.4.2",
    "prosemirror": "^0.7.0",
    "radium": "^0.17.1",
    "react": "^15.1.0",
    "react-addons-css-transition-group": "^15.2.1",
    "react-addons-test-utils": "^15.1.0",
    "react-avatar-editor": "^4.1.3",
    "react-dom": "^15.1.0",
    "react-dropzone": "^3.5.3",
    "react-headroom": "^2.1.2",
    "react-image-panel": "^1.0.2",
    "react-images": "^0.4.10",
    "react-modal": "^1.3.0",
    "react-native-storage": "^0.1.3",
    "react-notification": "^6.0.0",
    "react-prosemirror": "^0.2.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.1",
    "react-router-redux": "^4.0.5",
    "react-sticky": "^5.0.3",
    "react-user-avatar": "^1.8.0",
    "redux": "^3.5.2",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.0.11",
    "redux-logger": "^2.6.1",
    "redux-promise-middleware": "^4.0.0",
    "redux-thunk": "^2.1.0",
    "stats-webpack-plugin": "^0.4.2",
    "style-loader": "^0.13.1",
    "watchify": "^3.7.0",
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-hot-middleware": "^2.12.2",
    "whatwg-fetch": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^4.1.6",
    "babel-jscs": "^2.0.5",
    "babel-preset-react-hmre": "^1.1.0",
    "babel-register": "^6.14.0",
    "chai": "^3.2.0",
    "cross-env": "^1.0.7",
    "enzyme": "^2.4.1",
    "eslint": "^1.5.0",
    "eslint-plugin-react": "^3.4.2",
    "jscs": "^2.1.1",
    "jsdom": "^6.5.1",
    "json-loader": "^0.5.3",
    "mocha": "^2.5.3",
    "mocha-jsdom": "^1.0.0",
    "nock": "^8.0.0",
    "postcss-loader": "^0.6.0",
    "react-transform-hmr": "^1.0.0",
    "redux-devtools": "^3.3.1",
    "redux-mock-store": "^1.1.4",
    "rimraf": "^2.4.3",
    "sass-loader": "^3.2.0",
    "sinon": "^1.17.5",
    "sinon-chai": "^2.8.0"
  }
}

**Comment by ddcat1115** [comment]
报错的好像不是 message.error() 吧......

**Comment by oeddyo** [comment]
@ddcat1115 去掉message.error()这行是可以的

**Comment by afc163** [comment]
`message.error(e)` 不能接受这种参数。
