### ISSUE TITLE
DatePicker设置inputReadOnly后还可以响应onFocus

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#29451]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
```
<DatePicker inputReadOnly onFocus={() => console.log("onfocus")} />
  
```

### What is expected?
设置了inputReadOnly后，onFocus不响应

### What is actually happening?
设置了inputReadOnly后，onFocus依然响应。

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 17.0.0 |
| System | mac |
| Browser | chrome |

---
业务需求是点击做其他的事情，不需要响应focus。

**Comment by afc163** [comment]
inputReadOnly 只是不能手动输入日期，和能不能 focus 关系不大。

相似的，Select 开启 `showSearch` 或者 `mode="tags"` 后可以搜索和输入，关闭后只能选择，但是依然应该可以触发 onFocus，表示控件被键盘选中。

**Comment by qingfengmy** [comment]
那怎么实现不focus，除了disable。

或者只能disable，然后改disable时的样式。
