### ISSUE TITLE
官方实例拖拽TABS，控制台报错

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#29461]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j0qt8)

### Steps to reproduce
控制台报错。报错信息看下图，

### What is expected?
控制台不报错。

### What is actually happening?
控制台报错。 

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/8272614/108997623-c7162f00-76da-11eb-8503-82b7a3767b98.png)
![image](https://user-images.githubusercontent.com/8272614/108997669-d5644b00-76da-11eb-8f53-9fc8403206ad.png)

**Comment by afc163** [comment]
I can't see any console error in https://ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar-node or https://codesandbox.io/s/j0qt8

**Comment by xgj1988** [comment]
@afc163  额。是google 插件导致的。。找到原因了。我想问一下，有没有可拖动表格 每一列宽度 的 示例呢？

**Comment by yoyo837** [comment]
有，组合react-resizable
