### ISSUE TITLE
form.setFieldsValue( { rowKey:{列名:'修改值'}}) rowKey被默认为属性名，可否将其拆成2个参数一个传rowKey另一个传修改的对象？

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/ant-design#29464]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
EditableProTable中 form.setFieldsValue( { rowKey:{列名:'修改值'}}) rowKey被默认为属性名！，可否将其拆成2个参数一个传rowKey另一个传修改的对象？目前只能自己重新组装这个对象，虽然可以实现，但每次写很麻烦。

// 目前变通的解决方案：采用关联数组的写法
const columns = [
{
title: '活动名称',
dataIndex: 'title',
fieldProps:{
onChange:()=>{
// 如果写为：form.setFieldsValue( { rowKey:{state:'close'}}) -----rowKey 会被认为是对象的属性，如果写为一个数值 则正常

//以下是目前变通写法，自己组装对象：
const rowKey = 624748504 1.---有个rowKey
const obj = {} 2-------建空对象
obj[rowKey]={state:'close'} 3--组装----把修改的对象放到rowKey中 变成{624748504:{state:'close'}
form.setFieldsValue(obj) // 4----组装好后给form-----虽然可以实现但比较麻烦
},
},

🧐 解决方案
将setFieldsValue参数拆成2个,避免 rowKey被认为是属性名
form.setFieldsValue( { rowKey:id},{state:'close'})

### What does the proposed API look like?
form.setFieldsValue( { rowKey:id},{state:'close'})

**Comment by afc163** [comment]
```diff
- form.setFieldsValue( { rowKey:{state:'close'}}) 
+ form.setFieldsValue( { [rowKey]:{state:'close'}}) 
```
