### ISSUE TITLE
Expand all rows button

### ISSUE THREAD

**Issue by MihaiWill** [ant-design/ant-design#29462]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Expand all [expandable rows](https://ant.design/components/table/#components-table-demo-expand) from a click.

Is there a workaround? Please I need this option in my project

### What does the proposed API look like?
`expandAllRows={true || false}` defaut `false`

**Comment by afc163** [comment]
You can add a button with click handler to control `expandKeys`.

**Comment by MihaiWill** [comment]
> You can add a button with click handler to control `expandKeys`.

Yes this is what i want

> You can add a button with click handler to control `expandKeys`.

I don't understand, can you provide an example please?

**Comment by MihaiWill** [comment]
please @afc163

**Comment by xrkffgg** [comment]
Use `expandedRowKeys`
