### ISSUE TITLE
dora报错。

### ISSUE THREAD

**Issue by ITtong** [ant-design/ant-design#2946]
![image](https://cloud.githubusercontent.com/assets/19646825/18264587/b9bb88d0-7443-11e6-9d48-adf94e28019a.png)
ant design作为框架的项目，用mac上传到git的，我用win7的本吧代码从git上拉下来，就会报错，求大神解决。依赖已经安装好。

**Comment by silentcloud** [comment]
`webpack not found`  依赖没装全？

**Comment by ddcat1115** [comment]
看下这个   https://github.com/ant-design/ant-design/issues/1790

**Comment by ITtong** [comment]
@silentcloud 安装全了，droa-plugin-webpack安装了呀。

**Comment by afc163** [comment]
try `rm -rf node_modules && npm install`
