### ISSUE TITLE
关于table组件的expandedRow相关参数

### ISSUE THREAD

**Issue by zuiidea** [ant-design/ant-design#2947]
场景：需要使table的expandedRow默认展开，点击收拢按钮可收拢。

一：设置expandedRowKeys参数后，默认展开，点击收拢按钮无反应。
    
![image](https://cloud.githubusercontent.com/assets/16070518/18265509/add6568a-7448-11e6-823f-cd317ec9f37b.png)

二：设置defaultExpandedRowKeys参数后，默认不展开，点击收拢按钮可收拢。

![image](https://cloud.githubusercontent.com/assets/16070518/18265469/7cbd01d4-7448-11e6-8e72-2d1c6f085c6c.png)

三：设置expandedRowKeys，defaultExpandedRowKeys参数，同一

**Comment by ddcat1115** [comment]
如果只是需要有默认展开设定，用 `defaultExpandedRowKeys ` 就可以，经测试可以默认展开，如果发现还有问题，需要给个可重现的demo   

http://codepen.io/anon/pen/wGOWGW?editors=001

`expandedRowKeys ` 是受控模式，需要自己设定展开项，参考 http://react-component.github.io/table/examples/expandedRowRender.html

**Comment by zuiidea** [comment]
已解决，用onExpandedRowsChange手动设置expandedRowKeys，defaultExpandedRowKeys没生效可能是异步产生的

**Comment by 349989153** [comment]
@zuiidea 请问用onExpandedRowsChange手动设置expandedRowKeys解决的是场景一还是场景二？
