### ISSUE TITLE
non-coexistence of column.children & expandable. expandedRowRender?

### ISSUE THREAD

**Issue by xyuanbuilds** [ant-design/ant-design#29476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
expandable. expandedRowRender render an independent Row from customFunction;
column.children render more Rows from dataSource;

why can not use both of them?
expandable for column (e.g.: indentSize) should related to column.

### What does the proposed API look like?
separate them

**Comment by afc163** [comment]
These two interactions will conflict if both existed.
