### ISSUE TITLE
穿梭框底部渲染

### ISSUE THREAD

**Issue by Miss-huanlove** [ant-design/ant-design#29475]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/transfer-cn/](https://ant-design.gitee.io/components/transfer-cn/)

### Steps to reproduce
穿梭框底部渲染函数没有return

### What is expected?
renderFooter = () => {
        return <Button size="small" style={{ float: 'right', margin: 5 }} onClick={this.getclear}>
            清空
        </Button>
    }

### What is actually happening?
renderFooter = () => (
    <Button size="small" style={{ float: 'right', margin: 5 }} onClick={this.getMock}>
      reload
    </Button>
  );

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react |
| System | win7 |
| Browser | 谷歌 |

---
渲染一个标签 需要return

**Comment by yoyo837** [comment]
```jsx
() => {
  return <Comp />;
}
```

可以简写成
```jsx
() => <Comp />
```

or

```jsx
() => (<Comp />);
```

**Comment by Miss-huanlove** [comment]
是的是的 我上面多写了表达式，所以没有渲染



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2021年2月25日(星期四) 中午11:35
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "余温"<1161092963@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 穿梭框底部渲染 (#29475)





 () =&gt; {   return <Comp /&gt;; }
 
可以简写成
 () =&gt; <Comp /&gt;
 
or
 () =&gt; (<Comp /&gt;);
