### ISSUE TITLE
访问React项目，GPU加速导致CPU使用率100%,导致操作延迟

### ISSUE THREAD

**Issue by enjoy-wind** [ant-design/ant-design#29478]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
访问一个React项目，然后进入一个列表页面，打开chrome任务管理器，点击“搜索”按钮，这个时候GPU进程里面的CPU为90.4,导致动作延迟几十S。
条件：
1.在性能低的机器，比如:电脑配置：1核2G。
2.chrome version: 87.0.4280.88、72.0.3626.109、80.0.3987.132. 但是 71.0.3578.98是正常的CPU，用户动作无延迟。

### What is expected?
期望用户操作动作无卡顿

### What is actually happening?
用户操作动作有卡顿

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 15.6.2 |
| System | win10 |
| Browser | chrome 87.0.4280.88 |

---
期望给出原因或者思路，最好有解决方案。谢谢

**Comment by afc163** [comment]
先自行排查是否和 antd 有关系吧，如果确实有关系可以再建一个新 issue 并提供最小化的重现 demo。

另外 antd 3.x 已经不维护了，建议升级。
