### ISSUE TITLE
tsc 类型检查错误

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#29487]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
执行 yarn  lint

### What is expected?
lint 检查通过

### What is actually happening?
类型报错

![image](https://user-images.githubusercontent.com/37258382/109129100-38adb600-778b-11eb-8db1-4874cba981e0.png)

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by tolerance-go** [comment]
![Uploading image.png…]()

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/29383
