### ISSUE TITLE
RangePicker组件使用form表单取到的值，被修改会影响RangePicker组件

### ISSUE THREAD

**Issue by ewqazxc** [ant-design/ant-design#29485]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rangepickerzujianshiyongformbiaodanqudaodezhibeixiugaihuiyingxiangrangepickerzujian-antd4123-z94dd?file=/index.js)

### Steps to reproduce
1. 改变RangePicker值，表单方法改变RangePicker的值为 字符串
2. 再次点击RangePicker 组件

### What is expected?
不影响RangePicker 组件使用

### What is actually happening?
RangePicker 组件的值被修改，导致组件使用异常

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | win10 |
| Browser | "5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3861.400 QQBrowser/10.7.4313.400" |

---
虽然使用深拷贝可以避免类似场景，但DatePicker 既然没影响，应该保持一致

**Comment by afc163** [comment]
不建议这么使用，DatePicker 没影响也只是运气好。

**Comment by ewqazxc** [comment]
> 不建议这么使用，DatePicker 没影响也只是运气好。

可是取到的值，会反向传给组件内部这也不太对吧

**Comment by afc163** [comment]
我试着修改了一下 rc-picker，不只是 date.isAfter 会报错，后续还有 date.clone 等一系列操作，很难改到 RangePicker 能正常工作。

另外如你所说，修改的方式不应该是修改引用，DatePicker 的 value 是直接替换，RangePicker 是一个数组，修改 value[0]、value[1] 相当于把原对象直接修改了。最后，RangePicker 的值是 moment 对象，手动修改也不应该是 string。

**Comment by ewqazxc** [comment]
> 我试着修改了一下 rc-picker，不只是 date.isAfter 会报错，后续还有 date.clone 等一系列操作，很难改到 RangePicker 能正常工作。
> 
> 另外如你所说，修改的方式不应该是修改引用，DatePicker 的 value 是直接替换，RangePicker 是一个数组，修改 value[0]、value[1] 相当于把原对象直接修改了。最后，RangePicker 的值是 moment 对象，手动修改也不应该是 string。

那是不是该考虑下，获取值的这个方法不应该把组件内部的原对象返回

**Comment by afc163** [comment]
虽然不知道你这样改有什么用，但是参考 DatePicker 的写法，RangePicker 是否应该这么写？

```diff
- values.RangePicker[0] = "2021-02-26";
- values.RangePicker[1] = "2021-02-26";
+ values.RangePicker = ["2021-02-26", "2021-02-26"];
```

**Comment by afc163** [comment]
除了 onChange，还有 value 和 defaultValue 的赋值过程，上面的例子里其实是 initialValues 给 DatePicker 的 value 赋值，有一定的改造成本。@ewqazxc 有空给 rc-picker 发个 PR尝试一下。

**Comment by ewqazxc** [comment]
> 除了 onChange，还有 value 和 defaultValue 的赋值过程，上面的例子里其实是 initialValues 给 DatePicker 的 value 赋值，有一定的改造成本。@ewqazxc 有空给 rc-picker 发个 PR尝试一下。

其实不用initialValues  ，手动选择也是有这个问题，只是设了方便复现而已。
主要还是返回的值，修改到引用地址的数据了吧，直接对表单返回值做一次深拷贝不行吗？
