### ISSUE TITLE
虚拟列表Table的dataIndex不支持数组嵌套路径

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#29486]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-akedr3-ezkthj?file=index.js](https://stackblitz.com/edit/react-akedr3-ezkthj?file=index.js)

### Steps to reproduce
可点击链接查看

### What is expected?
demo

### What is actually happening?
希望路径嵌套

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17.0.1 |
| System | mac |
| Browser | 谷歌 |

**Comment by ISBN9527** [comment]
还有一个问题，用了虚拟类表后，column属性ellipsis失效，我本身需求是不需要横向滑动的

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-akedr3-csd59c?file=index.js

**Comment by afc163** [comment]
Virual List Table 目前依然是一个外接 react-window 的示例（而非内建属性），和很多属性不兼容或需要自行调通。

**Comment by ISBN9527** [comment]
@afc163 想亲请问下怎么给某一列加上特定的css样式啊，因为我在column上render后的class全被覆盖了

**Comment by Chasen-Zhang** [comment]
@ISBN9527 我发现render都不支持，能否指导一下
