### ISSUE TITLE
希冀：希望能有个无限扩展的开源组件库社区

### ISSUE THREAD

**Issue by llqgit** [ant-design/ant-design#2948]
希望能有一个社区，提供自己上传的组件。就像 [iconfont.cn](http://www.iconfont.cn) 的那种能够上传自己的，并且能够分享和搜索公共的。

希望能有一个无限扩展的开源组件库，我觉得一定会大大提高开发效率的。
不知这个提议怎么样 :P

**Comment by ddcat1115** [comment]
npm? 但是这个跟 AntD 有什么关系呢? 不明白你的意图...😢

**Comment by KidneyFlower** [comment]
我也希望啊，有一个平台能让大家共享自己的组件就好了。

**Comment by llqgit** [comment]
我的意思是 分享 自己的 react components 不是 packages，就像[官方的](http://ant.design/docs/react/introduce) 那种 @ddcat1115

**Comment by afc163** [comment]
https://react.rocks/
https://react.parts/web

开源的够用了。
