### ISSUE TITLE
Can TreeSelect provide prop “checkedKeys” like Tree Component does?

### ISSUE THREAD

**Issue by Trigg3rZY** [ant-design/ant-design#29496]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I wonder if tree nodes' checked state could be controlled manually when set prop treeCheckStrictly to true.

### What does the proposed API look like?
Same API as Tree Component's "checkedKeys" will be fine.

**Comment by afc163** [comment]
`value` is what you need.

**Comment by Trigg3rZY** [comment]
> `value` is what you need.

thanks!
`halfChecked` prop in type LabledValue does help
