### ISSUE TITLE
<Select /> in tags mode renders empty tag after pressing enter

### ISSUE THREAD

**Issue by chillyistkult** [ant-design/ant-design#29493]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/chillyistkult/pen/WNodyYK](https://codepen.io/chillyistkult/pen/WNodyYK)

### Steps to reproduce
Define a Select with `mode="tags"` and `open={false}` and focus and press enter. This is a valid use case, because a user may just want to paste or type previously unknown values and the dropdown would give no benefit.

### What is expected?
onChange is fired with value = undefined

### What is actually happening?
onChange is fired with an array that consists of an empty string and therefore an empty tag is rendered.

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.2 |
| System | Big Sure 11.2.1 |
| Browser | Chrome 88.0.4324.182 |

**Comment by zombieJ** [comment]
Could you provide detail reproduce step?

**Comment by afc163** [comment]
1. Focus into search input
2. Press <kbd>Enter</kbd>

expected: no change
happend: created a empty node in select
