### ISSUE TITLE
Form.Item rule transform not working

### ISSUE THREAD

**Issue by Orgil** [ant-design/ant-design#29490]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tf2yq?file=/index.js)

### Steps to reproduce
submit form with white space and see the console.

### What is expected?
form item value is trimmed before validation

### What is actually happening?
value is not trimmed.

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Mac OS |
| Browser | Chrome |

**Comment by Orgil** [comment]
sorry. attach wrong link. use below sandbox

https://codesandbox.io/s/antd-reproduction-template-forked-tf2yq?file=/index.js

**Comment by afc163** [comment]
`transform` is for value validation, what you are looking for is `<Form.Item normalize={...} />`

**Comment by oosswwaalldd** [comment]
> `transform` is for value validation, what you are looking for is `<Form.Item normalize={...} />`

You just saved my life! Thanks

**Comment by bombillazo** [comment]
Wow, `normalize` is such a weird term to use to modify the field value... I was looking for a way to do this, even reading the docs multiple times but I simply did not make the connection to that prop... Thanks @afc163
