### ISSUE TITLE
Tooltip still visible after click on MenuFoldOutlined/MenuUnfoldOutlined

### ISSUE THREAD

**Issue by Ronashah** [ant-design/ant-design#29502]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tooltip/](https://ant.design/components/tooltip/)

### Steps to reproduce

  const toggleCollapsed = () => {
    setCollapsed(collapsed => !collapsed);
  };

{collapsed ? (
                      <Tooltip title={'Expand panel'}>
                        <MenuUnfoldOutlined onClick={toggleCollapsed} />
                      </Tooltip>
                    ) : (
                      <Tooltip title={'Collapse panel'}>
                        <MenuFoldOutlined onClick={toggleCollapsed} />
                      </Tooltip>
                    )}

### What is expected?
Tooltip should not visible if mouse cursor is not there.

### What is actually happening?
Tooltip still visible after click on MenuFoldOutlined/MenuUnfoldOutlined antd component even though mouse cursor is not there.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | 88.0.4324.182 |

**Comment by Ronashah** [comment]
Hi I have added code in below link.

Step to reproduce: 
1. Click on MenuFoldOutlined.
2. Move cursor slight down to white screen, now you can see tooltip is still visible after mouse out.
3. If not produce please do 2 step 2-3 times.
Here I am attaching screenshot as well, please check

https://codesandbox.io/s/antd-reproduction-template-forked-f8vs8?file=/Tooltip/index.js

![image](https://user-images.githubusercontent.com/79636937/109305815-484cfd80-7864-11eb-9e7b-636d5529892a.png)

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/antd-reproduction-template-forked-5by9n?file=/Tooltip/index.js

**Comment by afc163** [comment]
Or: https://codesandbox.io/s/antd-reproduction-template-forked-qhl05?file=/Tooltip/index.js

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-syd6v?file=/Tooltip/index.js

This one is better!
