### ISSUE TITLE
建议<Select> 控件的options中可以扩展自定义的属性值用作查询过滤字段(如：query:'xjfs')，再设置这个query为optionFilterProp字段

### ISSUE THREAD

**Issue by ibryanwu** [ant-design/ant-design#29506]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
为了提升用户体验，有时要根据下拉框options中label的【拼音大写字母或其他助记符】作为搜索依据，过滤出想要的options。
现在只能通过optionFilterProp：'label' 搜索label信息太不灵活了，这个optionFilterProp就显得没发挥它最大的作用，可否支持在options[]中添加其他字段，根据这个字段进行搜索。
场景：如果下拉存在一个商品：澳大利亚大龙虾，想通过输入’adlydlx‘ 或商品编号’au009‘ 进行模糊搜索就无法实现
 因为options中这个商品：{value: '5', label: '澳大利亚大龙虾'} 只能搜：澳大利亚大龙虾'中的字

### What does the proposed API look like?
options中支持{value,label,query,等等....}[]  value和laber是保留属性，其余给到开发者用做过滤或其他用途（其他用途指的是：可以拿到所有的返回值，set到表格中，这种对于table中的下拉返回值去更新其他字段很有帮助）
所以刚才的商品可以这样设置 {value: '5', label: '澳大利亚大龙虾'，query:'adlydlx'}，再配合optionFilterProp :'query' 就可实现

**Comment by afc163** [comment]
目前就能这么实现，optionFilterProp 的值可以是任意属性。

**Comment by cuijiudai** [comment]
> 

设置options不好用，使用request 才可以呢
