### ISSUE TITLE
做表单校验时，getFieldProps 第一个参数如果填写 'nodeName'，就会报错。

### ISSUE THREAD

**Issue by zhangbody** [ant-design/ant-design#2950]
#### 本地环境

- antd 版本: 1.11.0
- 操作系统及其版本：Mac OS 10.11.6
- 浏览器及其版本: Chrome 53.0.2785.89 (64-bit)

#### 你做了什么？

使用表单验证时，getFieldProps 第一个参数填写 'nodeName'。

                const props = getFieldProps('nodeName', {
                    rules: [
                        { required: true}
                    ]
                });

#### 你期待的结果是：

能正常校验。

#### 实际上的结果：

console 中不断报出错误。

                Uncaught TypeError: elem.nodeName.toLowerCase is not a function

只要 ID 不用 'nodeName'，就没有问题。

**Comment by benjycui** [comment]
React 的问题 https://github.com/facebook/react/issues/6284

**Comment by shaozj** [comment]
好像是浏览器 bug：

```javascript
var form = document.createElement('form');
var input = document.createElement('input');
input.setAttribute('id', 'nodeName');
form.appendChild(input);
console.log(form);
```
在 chrome 中输出：
TypeError: (var).nodeName.toLowerCase is not a function
at :5:9
