### ISSUE TITLE
Cascader 省市区三级连动，懒加载数据的实现方式？

### ISSUE THREAD

**Issue by jackiealex** [ant-design/ant-design#2951]
- antd 版本:1.10.0

Cascader 有没有懒加载省市区的实现方式，比如点击某个省，异步获取数据后放进options , 但是每次render都会收起下拉。。。

**Comment by afc163** [comment]
http://react-component.github.io/cascader/examples/dynamic-options.html

**Comment by thbgh** [comment]
这只有两级的，请问有三级的实现方式吗?

**Comment by thbgh** [comment]
@jackiealex @afc163
