### ISSUE TITLE
Does the And4 version table have no ant-table-row-hover class name?

### ISSUE THREAD

**Issue by mtxue97** [ant-design/ant-design#29515]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/migration-v4-cn](https://ant.design/docs/react/migration-v4-cn)

### Steps to reproduce
没有呢

### What is expected?
没有呢

### What is actually happening?
没有呢

| Environment | Info |
|---|---|
| antd | 4.12.0 |
| React | ^17.0.1 |
| System | windows |
| Browser | chorme |

v4版本表格hover之后没有ant-table-row-hover这个类名了吗？

**Comment by afc163** [comment]
可以用 `.ant-table-row:hover { ... }`
