### ISSUE TITLE
关于更新时间显示错误和UI样式问题

### ISSUE THREAD

**Issue by jiangqidu** [ant-design/ant-design#29516]
![pro](https://user-images.githubusercontent.com/55723376/109267575-be416c80-7844-11eb-8b66-f75409721375.png)
![putong](https://user-images.githubusercontent.com/55723376/109267578-beda0300-7844-11eb-8835-979e29b24aba.png)
如图，更新时间显示错误

**Comment by jiangqidu** [comment]
另外，希望高级表单的滚动条不用自定义，和antd的一样就好了

**Comment by xrkffgg** [comment]
提到 https://github.com/ant-design/pro-components
