### ISSUE TITLE
使用分页器的时候会出现连续跳页两次的情况

### ISSUE THREAD

**Issue by NinthMonee** [ant-design/ant-design#29511]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination-cn/#components-pagination-demo-jump](https://ant.design/components/pagination-cn/#components-pagination-demo-jump)

### Steps to reproduce
1、首先点击选种当前页码(任何一个都可以，包括第一页和最后一页)
2、然后点击快速跳页，输入一个除了当前页码的任何一个页码，同时保证不要使快速跳页失去焦点
3、这时候可以点击除了当前页码以及快速跳页之外的任何一个页码，包括上一页与下一页(即便此时上一页和下一页处于禁用状态)，会发生连续跳页两次的情况

### What is expected?
期望在当前点击的页码或者上一页、下一页的时候，快速跳页不生效

### What is actually happening?
快速跳页会生效，当前点击的页码或者上一页、下一页也会生效

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react |
| System | macOS 10.15.7 |
| Browser | Google Chrome 88.0.4324.192 |

---
在antd 3.x和antd 4.x均有此种情况出现，且antd分页器引用的rc-pagination也有这种情况出现

**Comment by shaodahong** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/29512
