### ISSUE TITLE
【Bug】Firefox 下圆角按钮显示异常（hover 时跳动）

### ISSUE THREAD

**Issue by Q-Qplus1s** [ant-design/ant-design#29527]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/buttons](https://ant.design/components/buttons)

### Steps to reproduce
代码：<Button shape='round' type='primary'>添加</Button>

### What is expected?
正常显示圆角，没有跳动

### What is actually happening?
hover 时圆角变化为直角又变化为圆角，肉眼可见的变化过程

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.0 |
| System | Centos 7 |
| Browser | Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 |

正常显示：
![Screenshot_2021-02-27 创作中心](https://user-images.githubusercontent.com/50064165/109378814-7851da80-7910-11eb-99e0-eb7a1a11ef8e.png)

hover 时显示（短暂显示后恢复正常）
![Screenshot from 2021-02-27 15-28-25](https://user-images.githubusercontent.com/50064165/109378815-7d168e80-7910-11eb-9dca-f4fde2a53893.png)

**Comment by Q-Qplus1s** [comment]
这个bug可能是浏览器版本特定的，测试了更老的 firefox 版本或者最新的 firefox 版本都没有这个 bug

**Comment by Q-Qplus1s** [comment]
不用创建了，刚好有个按钮，直接在 https://u.ant.design/codesandbox-repro 上面修改一行代码：
```jsx
<Button shape="round" type="primary" style={{ marginLeft: 8 }}>
      Primary Button
</Button>
```

添加 shape="round"  就可以复现该问题，最新版本 antd 同样存在此问题，记得使用上述的 firefox 版本

**Comment by xrkffgg** [comment]
我这里测试了 Firefox  没发现，可能就是特定浏览器版本的原因

**Comment by zombieJ** [comment]
特定版本 bug 做 patch 性价比很低，还会增大打包尺寸。如果不是大面积用户锁在这个版本，不会去做额外修复。

**Comment by Q-Qplus1s** [comment]
@zombieJ 不能这么说，这个说不定是内部逻辑错误，最好定位一下，避免在其他场景复现，这样关闭不好
