### ISSUE TITLE
如何让Input组件自动获得焦点？

### ISSUE THREAD

**Issue by KidneyFlower** [ant-design/ant-design#2952]
想让组件渲染出来时，input自动获得焦点，但是不知道应该怎么做。。。

**Comment by benjycui** [comment]
`autoFocus`.

**Comment by benjycui** [comment]
more: http://stackoverflow.com/questions/28889826/react-set-focus-on-input-after-render

**Comment by djllhs** [comment]
ref={function(input) {
        if (input != null) {
          input.focus();
        }
      }}

**Comment by pengliheng** [comment]
我的子组件是一个textarea的编辑器，我想让他在我点击弹出来的时候自动聚焦，假如我的textarea组件是子组件，如何触发自动聚焦，，每次我让toggle切换的时候，让他自动聚焦

**Comment by pengliheng** [comment]
`ref={ (c)=> this._textArea = c }`
我有这样写，但是好像不行，试了一些方法都不行
