### ISSUE TITLE
Strange behavior of displaying label of Select when using Array.filter when render options

### ISSUE THREAD

**Issue by huyennbl** [ant-design/ant-design#29520]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gynrr?file=/index.js)

### Steps to reproduce
Here are 2 Select components, their options are rendered based on the same "inputs" array.
The first one uses inputs.filter() to skip some inputs element before rendering.
The second one pass the inputs directly to render

Try choosing some options, those 2 Select behave differently
The first one uses option's value as option label.
The second one uses option's label as option label.

### What is expected?
The first one should use option's label as option label.

### What is actually happening?
The first Select use option's value as option label.

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Firefox 85, Chrome 88 |

**Comment by afc163** [comment]
Select will lost label data in selected item if you remove it from options.

You can use css trick to implement: https://codesandbox.io/s/antd-reproduction-template-forked-qdvze?file=/index.css

**Comment by huyennbl** [comment]
Thanks a lot for the solution, but I think this question should go to a note of Select docs, because as an end user, what I described is how I expected the component to work, not using an css trick as work around solution :D
