### ISSUE TITLE
webpack生成的antd过大，有没有办法继续压缩?

### ISSUE THREAD

**Issue by oeddyo** [ant-design/ant-design#2953]
# webpack --json | webpack-bundle-size-analyzer

antd: 2.08 MB (56.0%)

有没有办法继续压缩呢？

webpack.config.js:

var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var StatsPlugin = require('stats-webpack-plugin');

module.exports = {
    entry: [
        path.join(__dirname, 'src/index.js'),
        path.join(__dirname, 'public/css/base.css'),
        path.join(__dirname, 'public/css/rich.editor.css')
    ],
    devtool: 'source-map',
    output: {
        path: path.join(__dirname, '/dist/'),
        filename: '[name]-[hash].min.js',
        publicPath: '/'
    },
    plugins: [
        new webpack.optimize.OccurenceOrderPlugin(),
        new HtmlWebpackPlugin({
            template: 'index.html',
            inject: 'body',
            filename: 'index.html'
        }),
        new ExtractTextPlugin('[name]-[hash].min.css'),
        new StatsPlugin('webpack.stats.json', {
            source: false,
            modules: false
        }),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
        }),
        new webpack.optimize.DedupePlugin()
    ],
    module: {
        loaders: [{
            test: /\.js?$/,
            exclude: /node_modules/,
            loader: 'babel',
            query: {
                "presets": ["es2015", "stage-0", "react"]
            }
        }, {
            test: /\.json?$/,
            loader: 'json'
        }, {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract('style', 'css')
        }]
    },
    postcss: [
        require('autoprefixer')
    ]
};

**Comment by oeddyo** [comment]
btw: 又加上了

    "babel-plugin-antd": "^0.5.1",


现在: 
压缩后加载是680K，还是略大...有没有办法继续压缩呢

**Comment by oeddyo** [comment]
sorry我搞错了，现在大小是3.5M...

**Comment by imac8t** [comment]
分割代码 按需加载吧?

**Comment by afc163** [comment]
参照 https://github.com/ant-design/babel-plugin-antd 加到 babel 的配置中。

**Comment by oeddyo** [comment]
加了，减小了很多 @afc163 

关键是npm install 这个包，以及在.babelrc里加上
  3    "plugins": [["antd", { style: "css" }]] // this shrink size to 700k
