### ISSUE TITLE
Tabs position shift on selection change

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#29532]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs/#components-tabs-demo-slide](https://ant.design/components/tabs/#components-tabs-demo-slide)

### Steps to reproduce
Click on different tabs, and observe the style change causing the positional shift.

### What is expected?
No positional shift when changing tab selection.

### What is actually happening?
Tabs position shift on selection change. See example in the provided animation: ![image](https://i.imgur.com/CAV2Hy7.gif)

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | React |
| System | Windows 10 |
| Browser | Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Similar as #27557
