### ISSUE TITLE
Select控件选择一个选项后，多触发一次`onSearch('')`

### ISSUE THREAD

**Issue by zero2lin** [ant-design/ant-design#2954]
#### 环境
- antd 版本: 1.10 / codepen 1.11
- 浏览器及其版本: 各浏览器都能重现

#### 做了什么&结果
Select 控件单选，ajax后台筛选数据。当选择一个选项后，会触发一次`onSearch('')`，后台查询回的选项就被清除了。原来在v1.2.1没有问题。

请看codepen，fetchData简化了，选择一个值后，console输出又会做一次onSearch并render
http://codepen.io/anon/pen/vXOEmr?editors=0011

**Comment by zero2lin** [comment]
https://github.com/react-component/select/issues/100

**Comment by wangking873** [comment]
react-component/select#100  这个行为在内部定死了 有点不好  公布一个回调方法 会更灵活点吧
