### ISSUE TITLE
Codesandbox examples fail: TypeError _typeof is not a function

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#29545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/irp9w)

### Steps to reproduce
Open any code sandbox example from AntD documentation. For example: https://codesandbox.io/s/irp9w.

### What is expected?
No error.

### What is actually happening?
TypeError _typeof is not a function error is being reported.

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | - |
| System | Windows 10 |
| Browser | Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
Seems codesandbox wrong cache the `@babel/runtime`. Manually install will work: https://codesandbox.io/s/type-antd4130-forked-m6hov

**Comment by zombieJ** [comment]
Create Codesandbox issue for this. https://github.com/codesandbox/codesandbox-client/issues/5541

**Comment by mjfwebb** [comment]
This has now been fixed by codesandbox.
