### ISSUE TITLE
图片上传列表拖拽排序例子无法运行

### ISSUE THREAD

**Issue by a982564562** [ant-design/ant-design#29544]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g7u9v?file=/index.js)

### Steps to reproduce
点击Upload组件中的上传列表拖拽排序例子在CodeSandbox中打开

### What is expected?
正常运行

### What is actually happening?
例子中使用到的createDndContext方法不存在，运行报错

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.14.0 |
| System | window10 |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/29418
