### ISSUE TITLE
antd 4.13.0 version: Module not found: Error: Can't resolve 'rc-util/es/isMobile'

### ISSUE THREAD

**Issue by SystemLight** [ant-design/ant-design#29546]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/SystemLight/create-kiva/tree/master/packages/react-huge-kiva/template](https://github.com/SystemLight/create-kiva/tree/master/packages/react-huge-kiva/template)

### Steps to reproduce
npm install & npm run start

### What is expected?
It can be packed normally.【可以正常打包】

### What is actually happening?
Unable to pack normally.【无法正常打包】

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | Windows10 |
| Browser | ChromeV88 |

**Comment by vVvlife** [comment]
通过yarn命令升级就会出现这个问题，npm可以正常运行

**Comment by yoyo837** [comment]
镜像未同步？

**Comment by SystemLight** [comment]
确实是镜像问题，将淘宝源更换回 https://registry.npmjs.org 就可以正常使用了。

**Comment by pdavid0** [comment]
Still happening for me with `4.13.1` and `yarn`, any resolution ?

**Comment by SystemLight** [comment]
> Still happening for me with `4.13.1` and `yarn`, any resolution ?

Wait for mirror synchronization or use NPM

**Comment by toxsick** [comment]
This is still happening in a gatsby project with version `4.14.0` for me. Version `4.12.3` works without problems.

**Comment by shanben7** [comment]
This is also happening for me, versions 4.13.1 through 4.14.1. I am using npm, not yarn.

**Comment by TuiKiken** [comment]
@toxsick, @shanben7, if you uses `yarn` add to `package.json`:
```
  "resolutions": {
    "antd/rc-util": "5.8.0"
  },
```
and run `yarn install`.
If you uses  npm – manually downgrade `rc-util` to 5.8.0 in lock file.

**Comment by jhclaura** [comment]
For me, delete the `yarn.lock` file and do `yarn install` again fix the error.

**Comment by nhevia** [comment]
Problem still persists with antd 4.14
Using npm and tried:
- deleting lock
- manually downgrading rc-util to 5.8.0

**Comment by yaronya** [comment]
Still happens with `yarn` and `v4.14.1`. Any news on that one? this issue is closed 🙄 

Tried [this](https://github.com/ant-design/ant-design/issues/29546#issuecomment-800642468) but it didn't help. Would like to avoid re-creating the `yarn.lock`

**Comment by yoyo837** [comment]
Please provide an online reproduction demo.

**Comment by afc163** [comment]
Please remove yarn.lock and reinstall node_modules.

**Comment by mathieu-anderson** [comment]
Have the same issue on version 4.14.1, deleted `node_modules` and `yarn.lock`, run `yarn install` and still getting

```
ERROR in ./node_modules/rc-select/es/generate.js
Module not found: Error: Can't resolve 'rc-util/es/isMobile' in '[app path]/node_modules/rc-select/es'
```

antd 4.14.1
yarn 1.22.10

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/112281343-eb0c6680-8cc0-11eb-9521-b45d51787ac3.png)

Did you run `npm install` with any npm mirrors?

**Comment by mathieu-anderson** [comment]
Running `npm install` seems to work, but we do not use `npm` usually. It generated a `yarn.lock` (surprisingly) but completely rewrote it as the formatting is different. I'm interested to know why `yarn` behaves differently than `npm` in this instance (not installing the correct dependencies, I assume?).

**Comment by afc163** [comment]
```
rm -rf yarn.lock
yarn cache clean
yarn
```

**Comment by mathieu-anderson** [comment]
These commands actually broke my build extremely hard. Still don't understand the npm/yarn disconnect.

**Comment by niexq** [comment]
```bash
npm install rc-util
```
