### ISSUE TITLE
安装脚手架antd-init后生成一个 Todo 应用实例，这个实例中脚手架是怎么部署的？没有任何comment和README文件来说明，完全是一个黑盒子，出现问题无法下手解决。

### ISSUE THREAD

**Issue by shitianjie** [ant-design/ant-design#2955]
#### 本地环境

- antd 版本:
- 操作系统及其版本：1.11.0
- 浏览器及其版本:Chrome, 52.0.2743.116 (64-bit)

**Comment by afc163** [comment]
http://ant-tool.github.io/quick-start.html

可以到这里进一步了解。

https://github.com/ant-design/antd-init/ antd-init 本身也是开源的。
