### ISSUE TITLE
InputNumber do not allow exceeding min and max.

### ISSUE THREAD

**Issue by alex20044** [ant-design/ant-design#29550]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Many current implementations depend on this behavior, we should consider adding it as an option, instead of completely changing the control.

### What does the proposed API look like?
The same as the versions before 4.13.0

**Comment by zombieJ** [comment]
Could you provide a sample of this requirement?

**Comment by alex20044** [comment]
A sample was the exact way that it used to work before. Currently if the max={100} and a user enters 200, the component will keep the 200 value and change it's color to red. The old behavior would make the value 100.

**Comment by nrayburn-tech** [comment]
Using current, https://ant.design/components/input-number/#components-input-number-demo-out-of-range
If you type in 50, it resets to 10.
If you click the button which directly sets the state, then the value is set to 99 and turned red.  It does not reset to 10.

Using 4.12, https://codesandbox.io/s/antd-reproduction-template-forked-otrb9?file=/index.js
If you type in 50, it resets to 10.
If you click the button which directly sets the state, then the value is set to 10 and does not turn red.

**Comment by zombieJ** [comment]
It's by design. Prev behavior makes state not sync with display value which causing bug of posting data. We follow the native control of input instead. It may not back to the bug interactive.


ref: https://ant.design/components/input-number/#Why-value-can-exceed-min-or-max-in-control
