### ISSUE TITLE
`getFieldProps` 忽略现有值，返回默认值

### ISSUE THREAD

**Issue by angelathewebdev** [ant-design/ant-design#2956]
#### 你做了什么？

引入 antd 的 `Form`，基于 `state` 里的数组去生成相对应的输入框。

#### 可重现的在线演示

http://codepen.io/angelathewebdev/pen/VKLYBJ?editors=0011

添加两个新的输入框，输入一些值，然后删除前两个输入框

#### 你期待的结果是：

最后一个输入框应该保留现有的值

#### 实际上的结果：

最后一个输入框的值被清空

**Comment by benjycui** [comment]
研究下 demo 和你代码的差异如何？http://ant.design/components/form/#components-form-demo-dynamic-form-item
