### ISSUE TITLE
Add possibility to disable enter behavior in select

### ISSUE THREAD

**Issue by ops1ops** [ant-design/ant-design#29564]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This is needed when u dont want to use this behavior (for example pressing enter does something else)

### What does the proposed API look like?
Consider adding prop to component

**Comment by afc163** [comment]
Duplicate of #20198
