### ISSUE TITLE
InputNumber value being null when blurred

### ISSUE THREAD

**Issue by ops1ops** [ant-design/ant-design#29560]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inputnumber-null-bug-9dlig?file=/index.js)

### Steps to reproduce
1. Type some numbers in input
2. Delete them
3. Unfocus input
4. See in console that value becomes null

### What is expected?
Value should not be null, it should be either empty string, either undefined
([React source](https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/react-dom/src/shared/ReactDOMNullInputValuePropHook.js))

### What is actually happening?
Probably wrong default value was set in blur handler

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | latest |
| System | Ubuntu 18.4 |
| Browser | Chrome latest |

**Comment by afc163** [comment]
It is by designed, see https://github.com/react-component/input-number/pull/134
