### ISSUE TITLE
[Table] Table sort icon support click up / down arrow directly 

### ISSUE THREAD

**Issue by wensonsmith** [ant-design/ant-design#29578]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
it makes user efficiency

### What does the proposed API look like?
Sort icon behavior like Element Table will be better

click up: sort asc, click again: cancel sort

click down: sort desc, click again: cancel sort

click not at icon: sort asc, sort desc, cancel sort

**Comment by zombieJ** [comment]
It's by design. Sort icon is too small to click that we extends the click region:

https://2x.ant.design/components/table/#components-table-demo-reset-filter
