### ISSUE TITLE
Incorrect update of records in an editable table with shouldCellUpdate api

### ISSUE THREAD

**Issue by Sec-ant** [ant-design/ant-design#29573]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kebianjidanyuange-antd4130-forked-gczp6)

### Steps to reproduce
This [CodeSandBox demo](https://codesandbox.io/s/kebianjidanyuange-antd4130-forked-gczp6) is a fork of **[Editable Cells](https://ant.design/components/table/#components-table-demo-edit-cell)** demo in the [official components page of Ant Design](https://ant.design/components/table/). I only modified the code so that **name** and **age** are both editable and used the `shouldCellUpdate` api for both.

- open the [demo](https://codesandbox.io/s/kebianjidanyuange-antd4130-forked-gczp6)
- edit the **age** of any record
- click to save
- edit the **name** of that record
- click to save
- the **age** changes back to a stale value
- incorrect behaviors keeps appearing when editing the cells arbitrarily

![](https://images2.imgbox.com/8f/ca/CvvZ2Khm_o.gif)

### What is expected?
Save the edited value and keep other values unchanged.

### What is actually happening?
Other values changes back to stale values.

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | Windows 10 Pro 20H2 19042.804 |
| Browser | Microsoft Edge 88.0.705.81 |

---
When I remove the `shouldCellUpdate` option in the columns definition, the behavior becomes normal. However it means all the table cells will be re-rendered in each render, which is unacceptable.

When I set `shouldCellUpdate` to return `true` when any of the editable column/dataIndex of a record is different from its previous value, the behavior becomes normal.
```javascript
{
    shouldCellUpdate: (record, prevRecord) => record.name !== prevRecord.name || record.age !== prevRecord.age,
}
```
I'm settled with this solution for now because I have much more rows than columns in my project. Yet it doesn't solve the problem.

The problem seems to have something to do with the `onCell` implementation in the [Column api](https://ant.design/components/table/#Column). It looks as though the callback function is passed with an incorrect record, but I'm not sure.

**Comment by Sec-ant** [comment]
A similar issue is discussed in #29243, and I believe this is also caused by closures. But how to fix the problem in this demo?

**Comment by Sec-ant** [comment]
OK I find a solution:

Pass the argument **rowIndex** to cell, then to `handleSave()` within the cell. And combine the old record and new value inside `handleSave()`

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kebianjidanyuange-antd4130-forked-c0tq6)

If this is not a bug, it still can be misleading because it's from the official examples. Any thoughts on update the **[Editable Cells](https://ant.design/components/table/#components-table-demo-edit-cell)** demo?

**Comment by xrkffgg** [comment]
官网 Demo 测试没问题呀

**Comment by Sec-ant** [comment]
> 官网 Demo 测试没问题呀

加上 shouldCellUpdate 后会有问题，就是 1 楼给的那个例子

**Comment by xrkffgg** [comment]
Demo 可以更新一下~ PR welcome

**Comment by zombieJ** [comment]
官网加个 FAQ 好了

**Comment by Sec-ant** [comment]
> 官网加个 FAQ 好了

我认为可编辑表格 demo 的问题和 #29243 还是有些区别的，#29243 是用户使用方法的问题。因为是函数组件，而且回调内部逻辑就是 setState，所以可以用 `setState` 的 function update 解决。

但可编辑表格 demo 的问题没办法用这个方法解决，我认为把 #29243 放到可编辑表格的 FAQ 并不合适。这个 onCell 传进来的 record 就是不正确的，用户侧没有什么很好的办法在自定义的 Editable Cell 里面获取到上一次的 record。但事实上 Editable Cell 里面无需知道整个 record 的全部信息，因此，所以我是通过传进来 rowIndex 再传回 Table 组件，最后在 Table 的 handleSave 函数里获取上一次的 record 信息来解决这个问题的。

**Comment by Sec-ant** [comment]
如果列表开启排序或筛选，使用 `shouldCellUpdate` 时，用 `rowIndex` 也无法获得最新的行列值。最后我的处理方法是在 `<EditableCell />` 组件内，每当用户触发单元格编辑状态时，保存该单元格所在行的 “data-row-key” 属性，并将其传入 `handleSave` 内，因为 key 是唯一不会出问题的值。

我知道这种方法很不 react，但除此之外对于一个可编辑、排序、删除的列表，我无法解决 `onCell + shouldCellUpdate` 同时使用时所产生的问题。

e.g.

```javascript
// <EditableCell/> 组件定义内部
// ...
// 使用 useRef 保存变量
const rowKeyRef = useRef();
// ...
// 获取最新的 rowKey
const toggleEdit = () => {
  rowKeyRef.current = parseInt(
    e.currentTarget.parentElement.parentElement.getAttribute("data-row-key")
  );
  setEditing(!editing);
  form.setFieldsValue({
    [dataIndex]: record[dataIndex]
  });
};
// ...
// 将 rowKey 传递给 <EditableTable/> 组件中定义的回调函数 handleSave
const save = async () => {
  try {
    const values = await form.validateFields();
    toggleEdit();
    handleSave(values, rowIndex);
  } catch (errInfo) {
    console.log("Save failed:", errInfo);
  }
};
//...

//...
// <EditableTable/> 组件定义内部
handleSave = (values, rowKey) => {
  const newData = [...this.state.dataSource];
  const rowIndex = newData.findIndex(e => e.key === rowKey);
  const item = newData[rowIndex];
  newData.splice(rowIndex, 1, { ...item, ...values });
  this.setState({
    dataSource: newData
  });
};
```

**Comment by PavelEfimenko** [comment]
@Sec-ant Hello! Thank you for your example. I have some issue now. Can you please update your sandbox?
