### ISSUE TITLE
StrictMode  findDOMNode Warning

### ISSUE THREAD

**Issue by Doduo** [ant-design/ant-design#29576]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
严格模式下，form表单提交验证的时候会出现此警告

### What is expected?
不要使用findDOMNode 

### What is actually happening?
在严格模式下 form提交会有Warning：
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
div

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17.0.1 |
| System | win10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
trace in #26136
