### ISSUE TITLE
Table data 有children情况，rowKey问题

### ISSUE THREAD

**Issue by jsrider** [ant-design/ant-design#2957]
table 用 rowKey={(record, index) => index)} ，
children 会报错。

这种情况必须要给每个数据加个uid 吗？能不能组件内部解决？

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by jsrider** [comment]
No children demo : https://codepen.io/jsrider/pen/ALWrLZ?editors=0011
Error demo: http://codepen.io/jsrider/pen/bwVRBK?editors=0011

**Comment by afc163** [comment]
index 是同级数据的顺序，会重复。

```
0 
   0
   1
1
  0
  1
  2
2
3
```

你数据应该给一个主键的，用不稳定的 index 做 key 本身就不好。

**Comment by jsrider** [comment]
嗯，让后端给每条数据加个 id 了

**Comment by benjycui** [comment]
@jsrider 要养成问题解决后就自行关闭 issue 的好习惯。
