### ISSUE TITLE
Input组件onPressEnter回调event的类型有误

### ISSUE THREAD

**Issue by richard-li-next** [ant-design/ant-design#29577]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-field-fz1q7?file=/src/App.tsx)

### Steps to reproduce
在onPressEnter回调event对象上取target.value时提示`Property 'value' does not exist on type 'EventTarget'.`

### What is expected?
类型正确

### What is actually happening?
`Property 'value' does not exist on type 'EventTarget'.`

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17 |
| System | mac |
| Browser | Chrome |

**Comment by huangkairan** [comment]
try using `event.persist()` before `event.target.value`

**Comment by zombieJ** [comment]
It's not antd issue. `@types/react` define the target as `EventTarget`. You can use `currentTarget` to get the `value` or convert EventTarget type instead.
