### ISSUE TITLE
dotPosition make pauseOnHover not working

### ISSUE THREAD

**Issue by Symous** [ant-design/ant-design#29572]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ynkecf?file=index.js](https://stackblitz.com/edit/react-ynkecf?file=index.js)

### Steps to reproduce
1. add dotPosition="top" prop;
2. hover mouse on carousel;

### What is expected?
the carousel pause

### What is actually happening?
still autopaly

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17 |
| System | Windows 64 bit |
| Browser | Chrome 88.0.4324.190 |

**Comment by zgoby** [comment]
1
