### ISSUE TITLE
select组件打开编辑报错

### ISSUE THREAD

**Issue by wang-neng-de-ha-shi** [ant-design/ant-design#29598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/55efw?file=/index.js)

### Steps to reproduce
打开即可发现报错，for (let i = 0; i < 100000; i  ) {
  const value = `${i.toString(36)}${i}`;
  options.push({
    value,
    disabled: i === 10,
  });
}；

当for循环i<100000时，报错

### What is expected?
不要报错，导致运行加载不出来

### What is actually happening?
100000的时候报错，

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 16.14.0 |
| System | Windows10 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
```
Potential infinite loop: exceeded 10001 iterations. You can disable this check by creating a sandbox.config.json file.
```

codesandbox 的沙盒保护限制，可以参考 warning 自行 fork 修复。
