### ISSUE TITLE
4.13.0 compile issue

### ISSUE THREAD

**Issue by godspeed20** [ant-design/ant-design#29597]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/godspeed20/antd-4-13-not-working]

### Steps to reproduce
followed the basic steps in https://ant.design/docs/react/use-with-create-react-app
1. yarn create react-app antd-demo
2. yarn start - all good
3. yarn add antd
4. yarn start - all good
5. replaced app.js as per instructions to render single primary button
6. get this error
./node_modules/antd/lib/table/hooks/useSelection.js
Module not found: Can't resolve '../../_util/devWarning' in 'C:\dev\antd-demo\node_modules\antd\lib\table\hooks'

### What is expected?
a working page with a button

### What is actually happening?
./node_modules/antd/lib/table/hooks/useSelection.js
Module not found: Can't resolve '../../_util/devWarning' in 'C:\dev\antd-demo\node_modules\antd\lib\table\hooks'

| Environment | Info |
|---|---|
| antd | ^4.13.0 |
| React | ^17.0.1 |
| System | windows |
| Browser | chrome |

---
if i revert to 4.10.2 it works fine. i haven't tried other versions yet

**Comment by yoyo837** [comment]
Please provide a mini repo to reproduce it.

**Comment by godspeed20** [comment]
https://github.com/godspeed20/antd-4-13-not-working is a minimal example following the above steps off the main docs

**Comment by yoyo837** [comment]
I can't see any errors, please update your repo.

**Comment by godspeed20** [comment]
also verified 4.12.3 works

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/109738980-cf52fa80-7c03-11eb-8acc-0056c14451f2.png)


![image](https://user-images.githubusercontent.com/6134547/109738999-d548db80-7c03-11eb-8553-0e5b86569753.png)

**Comment by godspeed20** [comment]
huh, i get 
![image](https://user-images.githubusercontent.com/14360136/109739131-1345ff80-7c04-11eb-9bc4-3fdbce58b98c.png)

now that's weird....

**Comment by yoyo837** [comment]
Could you try to delete node_modules and reinstall?

**Comment by godspeed20** [comment]
tried, same thing. attached my yarn.lock file in case that's pointing to anything.  maybe it's a yarn version thing? what yarn version are you using?

**Comment by godspeed20** [comment]
[Uploading yarn.zip…]()

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/109740501-51442300-7c06-11eb-966c-ec381439db36.png)

**Comment by yoyo837** [comment]
[difference-report.html.zip](https://github.com/ant-design/ant-design/files/6073116/difference-report.html.zip)

**Comment by godspeed20** [comment]
hmm same. ok i've no idea then. i've updated node locally though that shouldn't come into play here (now using 14.16.0), and i updated the package.json on the demo repo to use fixed versions rather than ^ so there's no confusion around us using different versions somehow

**Comment by godspeed20** [comment]
ah interesting, quite a few diffs there. let me see if i can fix those on my end and retry

**Comment by yoyo837** [comment]
Maybe it is related to `registry` setting.

**Comment by godspeed20** [comment]
> Maybe it is related to `registry` setting.

going to play dumb here, care to elaborate sorry?

**Comment by yoyo837** [comment]
yarn and npm config:

`registry: 'https://registry.npm.taobao.org'`

**Comment by yoyo837** [comment]
What about you?

**Comment by godspeed20** [comment]
registry: 'https://registry.yarnpkg.com',

**Comment by yoyo837** [comment]
Let me have a try.

**Comment by yoyo837** [comment]
Still working fine.

**Comment by godspeed20** [comment]
trying with the taobao one, i see a looooot more warnings during yarn install (including a bunch of deprecated warnings)

that said, i still get the same error so maybe it's not related. attached new yarn lock using taobao registry
[yarn.zip](https://github.com/ant-design/ant-design/files/6073154/yarn.zip)

**Comment by yoyo837** [comment]
II did not delete the `yarn.lock` in the repo, then run `yarn install`. So the lock file is provided by your repo.

**Comment by godspeed20** [comment]
ok got it. jesus that was magical. tried the same steps on a new pc that had no yarn/node/anything js related and got one other error, applied that fix to my current pc and after a few kicks got it working, looks like that fix never got traction
https://github.com/eslint/eslint/issues/13283

specifically this step
https://github.com/eslint/eslint/issues/13283#issuecomment-627166354

ultimately looks like some oddness around setting up the create react app via yarn vs npm. i also had to update yarn to 2.x but all is working now

thanks for the help, apologies for the confusion!
