### ISSUE TITLE
拖拽手柄列导致Input输入值之后组件焦点丢失

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#29594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuozhuaishoubingliedaozhiinputshuruzhizhihouzujianjiaodiandiushi-49guu)

### Steps to reproduce
1：这个是根据官网的拖动列的案列修改的。
2：在输入框输入内容，会发现焦点丢失，感觉是组件重回了。
3：注释掉 table 的   components={{  body: {    wrapper: DraggableContainer,      row: DraggableBodyRow,        },      }}，就没这个问题了。
4：怀疑是是用函数组件的问题。因为用官网的例子增加render里面用onchange 修改然后同步state，不会出现这个问题

### What is expected?
1：应该焦点不会丢失，不会卡顿（数据多了会，我这里就一个组件，实际我们项目一个一行table有很多个这种组件）
2：应该可以连续输入值。

### What is actually happening?
1：焦点丢失，而且有卡顿。
2：不能连续输入值。

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | lastest |
| System | widonws |
| Browser | chrome |

**Comment by zombieJ** [comment]
你的 DraggableContainer 和 DraggableBodyRow 每次 render 都重新生成，导致 React 重渲染。

**Comment by Sec-ant** [comment]
原代码问题有点多，我这边改了一版你参考：
https://codesandbox.io/s/table-demo-tuozhuaishoubinginputshuru-sz72k

**Comment by linxianxi** [comment]
> 你的 DraggableContainer 和 DraggableBodyRow 每次 render 都重新生成，导致 React 重渲染。Cache 掉它们。

怎么 cache 呢。我用官网的事例，然后加了 <Image />，拖拽的时候每个图片都会重渲染，会闪一下，会重新加载图片。怎么办
