### ISSUE TITLE
form使用redux关联时，设置的hasFeedback处理不正常

### ISSUE THREAD

**Issue by PeteLuo** [ant-design/ant-design#2959]
#### 本地环境

- antd 版本:1.11.0
- 操作系统及其版本：win7 64位旗舰
- 浏览器及其版本: chrome 52.0.2743.116 m

#### 你做了什么？
使用一个Input组件，并且添加hasFeedback属性为true，表单与redux关联

#### 你期待的结果是：
在文本框内容为空时，不应该出现验证通过的提示图标

#### 实际上的结果：
![image](https://cloud.githubusercontent.com/assets/18900661/18304198/9fc43a0a-7513-11e6-86ab-84a11960f1a7.png)

#### 可重现的在线演示
http://codepen.io/PeteLuo/pen/zKGvBA?editors=0010

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/18407735/385706b4-774c-11e6-9203-aac0b8e8eb7c.png)

如果一个值不存在，设为 `undefined`。

默认只会在 `validateTrigger`(`onChange` 之类) 触发时才会进行校验，所以第二个输入框需要在 `componentDidMount` 时触发校验。

```jsx
componentDidMount() {
  this.props.form.validateFields();
}
```

**Comment by PeteLuo** [comment]
- redux的state的from信息，由后台直接请求得到，我后台用的php，无法直接响应undefined属性，这样就需要前端单独加一层处理才行。能否调整value为null时候，也能不显示图标
- 第2点没有问题
