### ISSUE TITLE
Importing `generatePicker` from `lib` does not respect locale

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design#29595]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z9puu?file=/index.js)

### Steps to reproduce
follow [replace moment.js](https://ant.design/docs/react/replace-moment)
then try to change the locale.

### What is expected?
DatePicker locale to change.

### What is actually happening?
DatePicker locale does not change

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | win 10 |
| Browser | edge 88 |

---
Importing from `es` (`antd/es/date-picker/generatePicker`) works, but I'm using next.js, and server-side rendering throws module error (`Cannot use import statement outside a module`), but on hot-refresh (client-side) it works.

**Comment by afc163** [comment]
You can import all modules from 'antd/lib/xxx': https://codesandbox.io/s/antd-reproduction-template-forked-wsy4t

**Comment by jamalabo1** [comment]
@afc163 I know I can import modules from `lib`, problem is that `lib` is not doing what its supposed to do, 
https://codesandbox.io/s/antd-reproduction-template-forked-e975o

Updated link comparing both, 
This example shows that I can import from `es`, but I can't do this in my project because I'm using next.js and I don't want to mess with the webpack configurations.

**Comment by jamalabo1** [comment]
@afc163 any response?

**Comment by chemicalkosek** [comment]
Hey @jamalabo1 , have you fixed this issue? I'm still fighting, having similar problem here: https://github.com/ant-design/ant-design/issues/29907

**Comment by quyctd** [comment]
For some who still encounter this problem, you can try fix it by updating the import statement like this. Hope this help

```diff
- import { ConfigProvider } from 'antd'
+ import ConfigProvider from 'antd/lib/config-provider'
```
