### ISSUE TITLE
TreeSelect 删除Tag不会改变TreeSelect的check状态

### ISSUE THREAD

**Issue by xfcdxg** [ant-design/ant-design#2960]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：mac os
- 浏览器及其版本: chrome

#### 你做了什么？

引用了TreeSelect

#### 你期待的结果是：

删除tags会更新tree

#### 实际上的结果：

删除tags不会更新tree

#### 可重现的在线演示
http://codepen.io/xfcdxg/pen/JRYPbV?editors=001

**Comment by warmhug** [comment]
按照 demo 来做，给出可运行示例

**Comment by xfcdxg** [comment]
修改了~。

**Comment by xfcdxg** [comment]
如果SHOW_PARENT话，tags就删不掉了。

以下为示例：
http://codepen.io/xfcdxg/pen/amvopX?editors=001

**Comment by warmhug** [comment]
fixed https://github.com/react-component/tree-select/commit/10557c9de16247fbcd10081f3d141e66eec9d787
