### ISSUE TITLE
Remove 'keyboard' property from Tabs API definitions

### ISSUE THREAD

**Issue by cyates42** [ant-design/ant-design#29607]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Incorrect for docs to support the 'keyboard' property when rc-tabs stopped supporting the property.
https://github.com/react-component/tabs

### What does the proposed API look like?
https://github.com/ant-design/ant-design/pull/29606

**Comment by cyates42** [comment]
[https://github.com/ant-design/ant-design/pull/29606](url)

**Comment by afc163** [comment]
@zombieJ Is it a missing prop when refactor rc-tabs?

**Comment by cyates42** [comment]
It was intentionally removed when they refactored: 
<img width="448" alt="Screen Shot 2021-03-04 at 9 28 46 AM" src="https://user-images.githubusercontent.com/47337728/110004284-1dcbcc00-7ccc-11eb-8efa-f6dffcae9a54.png">

**Comment by zombieJ** [comment]
> @zombieJ Is it a missing prop when refactor rc-tabs?

Origin `keyboard` will conflict with user customize keyboard events. New Tabs follow accessibility rule for keyboard support which do not care about this anymore.
