### ISSUE TITLE
Form.Item validation issue with InputNumber wrapped in div

### ISSUE THREAD

**Issue by jarretmoses** [ant-design/ant-design#29605]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jarretmoses/antd-form-item-input-issue](https://github.com/jarretmoses/antd-form-item-input-issue)

### Steps to reproduce
Create a form with a Form.Item wrapper around a div with the InputNumber component inside and a pass a `rule` to the Form.Item. Pass in a custom formatter that prefixes the value with something like `$` to the Input number and a prdwr that removes all formatting.

### What is expected?
The value passed as the secondary value to the validation function to be the number value or a string with no non digit characters as was the case in 4.12

### What is actually happening?
Value passed to validation has prepended `$` presumably from my custom formatter. However it is not exactly the formatted value which for example 1000 would have been `$1,000` but the value being passed now is `$1000` which means it is not simply passing my formatted value to the validation. In 4.12 the value being passed in was the completely parsed Number.

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.2 |
| System | macOS 11.2.1 Big Sur |
| Browser | Brave Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64) |

---
I have isolated the issue to be that my InputNumber component is wrapped in a `div`. in 4.12.x this worked fine and I expected the value in my validator to be a raw number but now it is not.

**Comment by yoyo837** [comment]
See https://ant.design/components/form/#components-form-demo-customized-form-controls

**Comment by jarretmoses** [comment]
Don't understand why this issue was closed. Is this expected behavior? Do the release notes not explain a functional change to how components work? My setup worked in 4.12.x but nothing in the release notes mentions a breaking change.
