### ISSUE TITLE
关于input组件，带有搜索按钮和移除按钮功能

### ISSUE THREAD

**Issue by luckyGTL** [ant-design/ant-design#29604]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
关于input组件，带有搜索按钮和移除按钮功能。

### What does the proposed API look like?
但是当点击清除输入框内容（点击移除按钮时），应该添加一个事件，来操作清空输入框按钮时的逻辑。

**Comment by afc163** [comment]
可以用 onChange

**Comment by luckyGTL** [comment]
不行，搜索用的onSearch事件。再添加一个可清空的功能是如果再用onChange，会导致在输入内容的时候onchange也会触发。我现在只想在清空数据的时候去刷新接口。
&nbsp;




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "afc163"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 下午4:29
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "耿同良"<653945712@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 关于input组件，带有搜索按钮和移除按钮功能 (#29604)





 
可以用 onChange

**Comment by luckyGTL** [comment]
> 可以用 onChange

我描述的这个场景能理解嘛

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16862#issuecomment-507616942

**Comment by li-jia-nan** [comment]
Support in #49905
