### ISSUE TITLE
Capture attribute for Upload Component

### ISSUE THREAD

**Issue by ChinmayNaphade** [ant-design/ant-design#29608]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This attribute opens up the camera directly rather than opening a menu that asks the user to select between gallery and camera to upload an image. This behavior occurs only when the device is mobile. When the html input element's type attribute is file upload and the accept attribute is specified, we are able to set the capture attribute. Currently, there is no provision to set the capture attribute in the Upload component.

### What does the proposed API look like?
The API should be able to provide an attribute `capture` with values `users` or `environment` for front facing and rear facing camera respectively.

**Comment by MichalPodeszwa** [comment]
@afc163 This ticket has been closed from rc-upload repository. However to my knowledge - the Capture prop isn't supported in Upload Component in Ant itself (https://github.com/ant-design/ant-design/blob/master/components/upload/interface.tsx#L86).

**Comment by afc163** [comment]
@MichalPodeszwa PR is welcome~

**Comment by qiutian00** [comment]
But Capture props not show in the [document](https://ant.design/components/upload/#header)
