### ISSUE TITLE
InputNumber will add the decimal place in as the user type when using the precision property. 

### ISSUE THREAD

**Issue by lc-serenajia** [ant-design/ant-design#29609]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9itef)

### Steps to reproduce
Pass precision props into InputNumber, say precision = '2'.

### What is expected?
Do not auto add decimal place when user typing, see the right behavior from the previous version 4.12.3.

### What is actually happening?
When typing, the component will add decimal place and stop user typing.

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | macOS 11.0.1 Big Sur |
| Browser | Chrome |

**Comment by Sec-ant** [comment]
Behaves normally when used as a controlled component
```javascript
const ControlledInputNumber = () => {
  const [value, setValue] = useState("");
  return (
    <InputNumber min={0} precision={2} value={value} onChange={setValue} />
  );
};
```

**Comment by afc163** [comment]
- ✅ 4.12.3: https://codesandbox.io/s/antd-reproduction-template-forked-43m4m?file=/index.js
- ❌ 4.13.0: https://codesandbox.io/s/antd-reproduction-template-forked-9itef
