### ISSUE TITLE
Upload does not works anymore since 4.13.0

### ISSUE THREAD

**Issue by sgarnotel** [ant-design/ant-design#29616]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/sgarnotel/upload-example](https://github.com/sgarnotel/upload-example)

### Steps to reproduce
Start using `yarn && yarn dev` and try to upload an image (jpg, png)

### What is expected?
The file sould be read by the `FileReader`

### What is actually happening?
The object `info.file.originFileObj` is in a wrong type: `TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.`

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | react 16.13.1   next |
| System | Arch linux |
| Browser | Chromium Version 88.0.4324.182 |

---
That works correctly using antd 4.12.3

**Comment by kerm1it** [comment]
fixed in https://github.com/ant-design/ant-design/pull/29614
