### ISSUE TITLE
Long value <Select> is not work good with horizontal <Form.Item> or flexbox

### ISSUE THREAD

**Issue by heroboy** [ant-design/ant-design#29611]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gbeoh)

这个示例只是看布局，不需要操作。内容有点多，我来解释一下。

一句话解释就是，`<Select>`不能很好的在flexbox中保持父元素给它指定的大小。

首先，在`<div style="width:200px">`这样直接指定大小的元素中，`<Select>`是正常的。

接着，我用`<Row>` `<Col>` 来布局，也很好。但是太简单了。

用`flex`来实现3等分的子元素，就不行了。`<Select>`会撑大元素，使得示例中的内容不能3等分。但是`<DatePicker>`就很好。
我用`<DatePicker>`对比是因为和`<Select>`比较像，有一个类似于文本框的东西，和点击有下拉菜单之类的。

最后就是`<Form>`中的问题了。
`<Select>`要么自动换行了。加了`flexWrap:'nowrap'`之后，就大小超出范围了。
但是`<DatePicker>`依然是能正常显示的。`<CheckBox>`虽然不能直接正常显示，但是经过调试加了各种`style`也能正常。
但是`<Select>`本身太复杂，层次太多`style`加不到里面，自身水平有限，我试着加了各种`width`,`min-width`等等，都不能如愿以偿。

### Steps to reproduce
看示例

### What is expected?
在水平的`<Form.Item>`中像`<DatePicker>`一样，不发生换行和超出。

### What is actually happening?
看示例

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | firefox, chrome |

**Comment by zombieJ** [comment]
Flex 布局根据内容设置宽度，复合元素需要指定 `min-width` 强制 flex 计算布局：

https://codesandbox.io/s/antd-reproduction-template-forked-smmkw?file=/index.css

**Comment by heroboy** [comment]
解决了，其实不用修改全局的`.ant-col`
`<Form.Item wrapperCol={{style:{minWidth:0}}}>`就可以了
