### ISSUE TITLE
Table 标题为中文时没有强调效果

### ISSUE THREAD

**Issue by initialdmg** [ant-design/ant-design#29610]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-basic](https://ant.design/components/table-cn/#components-table-demo-basic)

### Steps to reproduce
在codepen中打开，将任意title改为中文

### What is expected?
默认的列标题样式对于中文和英文应该拥有同样的效果

### What is actually happening?
只有英文有强调效果（更黑）

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | latest |
| System | all |
| Browser | chrome 88 |

**Comment by xrkffgg** [comment]
`font-weight` 是一样的，看字体的表现情况

**Comment by afc163** [comment]
```
font-weight: 500;
```

字重目前应该是一样的。
