### ISSUE TITLE
accept attribute is ignored when directory selected

### ISSUE THREAD

**Issue by maksnester** [ant-design/ant-design#29619]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drag-and-drop-antd4130-forked-pds3h?file=/index.js)

### Steps to reproduce
Select folder with some files that are not listed in the accept attribute

### What is expected?
The same behaviour as for drag&drop of a folder. Accept attribute is respected and unacceptable files are filtered out from the list.

### What is actually happening?
Every file from the select folder appears in the list.

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 16.14.10 |
| System | Macos big sur 11.2.1  |
| Browser | Chrome Version 88.0.4324.192 (Official Build) (x86_64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24826#issuecomment-640439096

**Comment by kerm1it** [comment]
@afc163 这个是个 bug，当选择目录的时候，accept 传的是 `.jpg`，目录里面的 `.png` 也会被上传，onChange 事件的 files 没有使用 accept 过滤。

**Comment by zpc7** [comment]
请问这个issues是在那个版本中, 优先被修复的呢?
