### ISSUE TITLE
Table组件可否在columns属性的render方法中提供一下当前record的序号信息

### ISSUE THREAD

**Issue by aiyun1010** [ant-design/ant-design#29629]
render方法中只有一个当前页的index信息，在分页情况下，每页的index都是从0开始的，如果要根据当前页显示序号，则需要根据当前页以及每页条数才能正确获取。
Table组件其实已经知道total，当前页，当前数据项的index，所以是可以很方便的返回一个当前数据项在整个datasource中的绝对序号的。想请问下大佬，为啥不顺便多返回一个参数
（There is only one index information of the current page in the render method. In the case of paging, the index of each page starts from 0. If you want to display the serial number according to the current page, you need to get it correctly according to the current page and the number of pages per page.
The Table component already knows the total, the current page, and the index of the current data item, so it can easily return the absolute number of the current data item in the entire DataSource.Would like to ask the next big guy, why not incidentally return a parameter）

**Comment by smilealgernon** [comment]
遇到同样的困扰，table在多个tab里，每个table都分页，需要序号列

**Comment by shady-xia** [comment]
这是个很常见的需求，希望能够封一下

**Comment by 544751779** [comment]
+1
