### ISSUE TITLE
Button always got <span>

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design#29622]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js)

### Steps to reproduce
all ant button got <span>, how to remove it?

### What is expected?
remove <span> for the button

### What is actually happening?
button got <span> , which is not required.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
`span` tag is a useful for stable dom structure when loading state changes.
