### ISSUE TITLE
Upload组件可否提供设置缩略图宽、高的属性

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#2962]
因为我的项目中，图片显示的宽、高是用户设置的，目前我不知道怎么通过设置样式能实现这样的效果。

**Comment by afc163** [comment]
覆盖样式。

**Comment by zhulichao** [comment]
对不起，我不明白怎么能设置，我在组件定义的jsx里可以获取用户设置的宽度、高度，我怎么能在样式表里获取这些数据设置样式呢。

**Comment by benjycui** [comment]
> 图片显示的宽、高是用户设置的

其实我不理解这个场景。

**Comment by zhulichao** [comment]
大概的意思是：有一个单独的文件配置了用户想要的宽度、高度，每次我在渲染Upload组件时，先要去这个配置文件读取这些配置信息，然后再渲染。比如用户配置了上传图片的缩略图的宽度、高度了，我就要按照这个宽度、高度进行显示。

**Comment by benjycui** [comment]
动态的宽高的确无法用样式覆盖，所以要自己实现缩略图预览了。

使用场景多了再考虑。

**Comment by benjycui** [comment]
好吧，其实是可以通过动态插 `<style />` 实现覆盖的。

**Comment by zhulichao** [comment]
我昨天看了下源码，也试过了，可以传给Upload组件宽度、高度属性，Upload组件在调用UploadList组件时将这两个属性传入，在UploadList组件render方法的this.props.items遍历中return的最外层div标签添加style属性就可以实现。我想看一下官方会不会实现这个功能，如果不打算实现我就自己改了。
