### ISSUE TITLE
<DatePicker picker="quarter" /> can't customize panel

### ISSUE THREAD

**Issue by vivianus-chan** [ant-design/ant-design#29625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/vivianus/pen/ZEBjogY?editors=0010](https://codepen.io/vivianus/pen/ZEBjogY?editors=0010)

### Steps to reproduce
I want to change Q1 and Q2 in the panel to Chinese. I don't know how to deal with it

### What is expected?
customize panel, change Q1 into Chinese

### What is actually happening?
dateRender doesn't work

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 16^ |
| System | windows |
| Browser | 版本 88.0.4324.190（正式版本） （64 位） |

**Comment by genternava** [comment]
@vivianus-chan have you found a fix for this?

**Comment by wangzongming** [comment]
@vivianus-chan have you found a fix for this?

**Comment by wangzongming** [comment]
hi! @vivianus-chan  @genternava 

I found a solution:
Source components about formatting see here: https://github.com/react-component/picker/blob/master/src/panels/QuarterPanel/QuarterBody.tsx#L51

This lets you know that a quarterFormat configuration was previously supported。🤔

The usage is as follows:

import React from "react";
import { render } from "react-dom";
import App from "../App"; // Here is your entry component
import zh_CN from "antd/lib/locale-provider/zh_CN";
import { ConfigProvider } from "antd";

const quarterFormatFn = (date) => {
	const q = date.format("Q") + "";
	return {
		"1": "一季度",
		"2": "二季度",
		"3": "三季度",
		"4": "四季度",
	}[q];
};
zh_CN.DatePicker.lang.quarterFormat = (date) => { 
	return quarterFormatFn(date);
}; 

const rootDom = document.getElementById("root");
const RootReactRender = (
<ConfigProvider locale={zh_CN}>
	<App />
</ConfigProvider>);

render(RootReactRender, rootDom);

ps: ConfigProvider  For usage, see https://ant-design.gitee.io/components/config-provider-cn/

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
