### ISSUE TITLE
Modal弹框设置transitionName后无法关闭

### ISSUE THREAD

**Issue by YagamiNewLight** [ant-design/ant-design#29626]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-lf37fo-vdcr1u?file=index.js](https://stackblitz.com/edit/react-lf37fo-vdcr1u?file=index.js)

### Steps to reproduce
弹出modal的时候（无论是JSX还是modal.method等形式）添加transitionName为任意值("move-down" | "move-up")

### What is expected?
modal正常弹出或者关闭，并且加上transitionName指定的动画效果

### What is actually happening?
modal弹出时没有动画效果，且无法关闭

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | 88.0.4324.190 |

**Comment by zombieJ** [comment]
@crazyair

**Comment by crazyair** [comment]
1

**Comment by crazyair** [comment]
move-down  move-up 在 4.13.0 之前在 antd less 中有，所以可以关闭，demo 中改为其他样式名，也关闭不了的，而是在 4.13.0 添加了 ant 前缀变更了 ant-move-down ant-mov-up。

https://codesandbox.io/s/anniuleixing-antd4123-forked-87zo6?file=/index.js
antd 4.12.3 版本

**Comment by zombieJ** [comment]
@YagamiNewLight 你 demo 里没有写`move-down`

**Comment by YagamiNewLight** [comment]
@zombieJ 不是有么，Modal.success的传参就是transitionName:"move-down".
https://stackblitz.com/edit/react-lf37fo-jpwviu?file=index.js

**Comment by zombieJ** [comment]
这个 transitionName 没有对应的 css

**Comment by YagamiNewLight** [comment]
请问在哪儿引入对应的css呢？我看4.12.3版本也只是引入了`import "antd/dist/antd.css";`并没有额外引入其他css呢
demo：https://codesandbox.io/s/basic-antd4131-forked-snt49?file=/index.js

**Comment by YagamiNewLight** [comment]
懂了，要加一个ant前缀是吧

**Comment by zombieJ** [comment]
`4.13.0` 给所有动画 css 添加了前缀，防止和用户自定义以及 v3 版本混用冲突。一般不推荐直接复用 antd 的动画样式，如果用户了就跟着改名字哈

**Comment by zhangyu0218** [comment]
antd v5.2.1 版本 使用transitionName="ant-move-down" 又出现了这个问题

**Comment by lxiiiixi** [comment]
> antd v5.2.1 版本 使用transitionName="ant-move-down" 又出现了这个问题

貌似下面这一系列中除了 fade 和 zoom 这两个其他的用起来都会有这个问题

fade
zoom
zoom-big
zoom-big-fast
zoom-up
zoom-down
zoom-left
zoom-right
slide-up
slide-down
slide-left
slide-right
move-up
move-down
move-left
move-right

**Comment by 0xfullex** [comment]
这个问题解决了吗？
