### ISSUE TITLE
inlineCollapsed={true} not hiding the outer container of Menu on react 17.0.1

### ISSUE THREAD

**Issue by kiranlm** [ant-design/ant-design#29621]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapsed-inline-menu-antd4130-forked-l8z17?file=/index.js:881-896)

### Steps to reproduce
While toggling the `inlineCollapsed` attribute, menu is getting collapsed but the container remains same

### What is expected?
While changing `inlineCollapsed` to true, the entire menu will should collapse including the container

### What is actually happening?
While changing `inlineCollapsed` to true , the outer container is not hiding

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/collapsed-inline-menu-antd4130-forked-pl55v?file=/index.js:331-357
