### ISSUE TITLE
upload lodash.cloneDeep flielist bug

### ISSUE THREAD

**Issue by LeoHuiyi** [ant-design/ant-design#29624]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upload-lodashclonedeep-flielist-bug-uf6xo?file=/index.js)

### Steps to reproduce
点击上传文件

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | chrome89 |

**Comment by zombieJ** [comment]
https://github.com/lodash/lodash/issues/3389

**Comment by LeoHuiyi** [comment]
@zombieJ 之前的版本可以用的 file改成Proxy  应该算不兼容更改把，升级上去都不能用了。

**Comment by zombieJ** [comment]
之前是对定义的错误实现，也有 mutable 的问题。更新后应该不需要这个 deepClone 了。
