### ISSUE TITLE
Selecting multiple dates with Calendar and/or DatePicker. 

### ISSUE THREAD

**Issue by iamricky** [ant-design/ant-design#29635]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The ability pick pick multiple times/dates.

### What does the proposed API look like?
Extend DatePicker to include MultiplePicker; The Calendar component would just have a `multiple` boolean attribute

**Comment by afc163** [comment]
Duplicate of #4447
