### ISSUE TITLE
Table组件的过滤按钮在频繁点击后无法正常出现下拉菜单

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design#29631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
在线演示：[http://139.198.178.100:10881/](http://139.198.178.100:10881/)
代码地址：[https://github.com/Mileworks/ria-table-bug](https://github.com/Mileworks/ria-table-bug)

### Steps to reproduce
在 create-react-app 中使用 Table 组件，频繁多次点击 table 列头的筛选按钮后，再点击会弹不出下拉菜单，或者闪一下立即收起。

问题重现步骤：
1. 访问在线演示地址，或启动本地开发环境
2. 页面中存在一个表格，其中第一列可筛选
3. 快速多次点击该筛选按钮（就行玩游戏那样快速点击），筛选菜单会正常反复下拉/收起
4. 稍作停顿，点击筛选按钮，问题来了：筛选菜单可能无法弹出，或只出现收起动画
5. 问题较容易重现，也可重复步骤 3 和 4 多试几次。

在线演示地址：http://139.198.178.100:10881/

开发调试步骤：
1. 请从 https://github.com/Mileworks/ria-table-bug 拉取代码
2. 执行 yarn 安装依赖
3. 执行 yarn start 启动开发环境

### What is expected?
Table的筛选菜单总是能正常弹出

### What is actually happening?
Table的筛选菜单，在频繁多次点击后，无法弹出或弹出后又立即收起（可能是频繁点击引起了下拉/收起的动画错乱）

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.1 |
| System | Win7 |
| Browser | Chrome 89.0.4389.72 （64位） |

---
在产品开发中，最初出现的现象是开发者在Win系统中 build 出的版本正常，但是通过CI（github的Actions）打包出来不正常。
后又制作了 https://github.com/Mileworks/ria-table-bug 这个demo用于测试，发现开发者在Win系统 yarn start 也不正常。

**Comment by afc163** [comment]
先试试删了 yarn.lock 再重装 node_modules。

**Comment by chairui2001** [comment]
你好，经测试删除yarn.lock后重装依赖确实正常了。请问是否在上一个小版本无意间修复了？

**Comment by afc163** [comment]
不确定。
