### ISSUE TITLE
Drag Sorting Table with Sticky columns

### ISSUE THREAD

**Issue by FrozenIce0617** [ant-design/ant-design#29632]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drag-sorting-with-handler-antd4130-forked-wh3z8)

### Steps to reproduce
Scroll horizontally a bit and try reordering the rows by using a drag handle.

### What is expected?
The draggable row width should be the visible width of the table.

### What is actually happening?
It has some whitespace in the left part.

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 16.12.0 |
| System | macOS Big Sur 11.1 |
| Browser | Chrome v88.0.4324.182  |

---
https://prnt.sc/10dray4

**Comment by afc163** [comment]
Draggable Table is not compatible with sticky columns now.
