### ISSUE TITLE
upload 初始化设置的filelist 在onChange中的filelist的数据格式不统一

### ISSUE THREAD

**Issue by LeoHuiyi** [ant-design/ant-design#29646]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yonghutouxiang-antd4131-forked-2eclr?file=/index.js)

### Steps to reproduce
上传图片 看console面板 
![image](https://user-images.githubusercontent.com/8001457/110265376-58987180-7ff6-11eb-9688-dad4fffa7e19.png)

### What is expected?
数据格式统一

### What is actually happening?
数据格式不统一

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | chrome89 |

**Comment by afc163** [comment]
使用起来有什么问题呢？

**Comment by LeoHuiyi** [comment]
@afc163  前面服务端拉下来的初始化数据使用lodash.cloneDeep不报错 。后面的file是Proxy用lodash.cloneDeep就会报错 还是统一下格式比较好。用起来也比较奇怪。这个file改成proxy，对之前代码也不兼容，之前代码有使用lodash.cloneDeep，升级都会报错。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29624

**Comment by XinYueXiao** [comment]
> #29624

所以是怎么解决的，proxy 怎么获取文件的状态和接口返回的数据

**Comment by zombieJ** [comment]
@XinYueXiao , Proxy 里的内容是一样的

**Comment by afc163** [comment]
@zombieJ 还是 cloneDeep 会报错的问题。

**Comment by zombieJ** [comment]
嗯

**Comment by zombieJ** [comment]
lodash 的 `cloneDeep` 不支持 Proxy。走了一圈，感觉针对 lodash hack 性价比不高。

**Comment by XinYueXiao** [comment]
> @XinYueXiao , Proxy 里的内容是一样的

![image](https://user-images.githubusercontent.com/31272499/110775834-56eed800-829a-11eb-9ba3-eccb0a11fb76.png)
在浏览器里是proxy的格式

**Comment by zombieJ** [comment]
Proxy 里的数据就是你 console 里的数据，直接拿就行了。
