### ISSUE TITLE
Tab bar prevents swipe up/down on mobile browser

### ISSUE THREAD

**Issue by irvanherz** [ant-design/ant-design#29645]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w7i44)

### Steps to reproduce
From any mobile browser, try to swipe view up or down by starting finger touching **Tabs' bar**.

### What is expected?
It should scrolling view up/down as I swipe.

### What is actually happening?
It does nothing.

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | Android 7.1.2; Redmi 5A Build/N2G47H |
| Browser | Chrome Version 88.0.4324.181 |

---
My project using many tabs at home page. This bug oftenly brings problem for any users who open the page from mobile browser.

**Comment by nrayburn-tech** [comment]
Sandbox reproduces on iPhone Safari as well.

**Comment by irvanherz** [comment]
> Sandbox reproduces on iPhone Safari as well.

So, I think this issues should be persists on many touchscreen device. As chrome an webkit are the engines that widely used in such kind of devices. This isn't a big issue, but it really annoys the UX.

**Comment by irvanherz** [comment]
Actually, I just doing some inspection. And found the problem comes from `rc-tabs`

**Comment by afc163** [comment]
@irvanherz PR welcomes

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/tabs/pull/622
