### ISSUE TITLE
antd@4.13.0 我也遇到同样的问题/

### ISSUE THREAD

**Issue by jefferyssy** [ant-design/ant-design#29659]
antd@4.13.0 我也遇到同样的问题/

let pickerRef: any = useRef(null)

pickerRef.current?.focus()

<RangePicker
          ref={pickerRef}
          allowClear={false}
          value={isArray(dateFilterVal) ? dateFilterVal : []}
          onChange={onChange}
          renderExtraFooter={renderExtraFooter}
        />

_Originally posted by @jefferyssy in https://github.com/ant-design/ant-design/issues/26516#issuecomment-792651936_

**Comment by jefferyssy** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-swv26

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-3f9hy?file=/index.js
