### ISSUE TITLE
typescript中使用antd4，import { IconProps } from 'antd/lib/icon';找不到IconProps了，不知道该怎么使用

### ISSUE THREAD

**Issue by daiyamin** [ant-design/ant-design#29657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-in-typescript-cn](https://ant.design/docs/react/use-in-typescript-cn)

### Steps to reproduce
无

### What is expected?
可以正常使用interface IconProps

### What is actually happening?
使用import { IconProps } from 'antd/lib/icon';报错

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 16.13.1 |
| System | 所有 |
| Browser | 所有 |

**Comment by yoyo837** [comment]
你是3.x升级4.x吧？建议看看迁移文档吧，4.x里没有Icon组件。

**Comment by daiyamin** [comment]
> 你是3.x升级4.x吧？建议看看迁移文档吧，4.x里没有Icon组件。

嗯，3.x升级4.x，typescript老项目中使用了很多IconProps，这个还有提供吗，怎么可以引用到？

**Comment by yoyo837** [comment]
https://ant.design/docs/react/migration-v4-cn 看看文档，如果没有提供相关的迁移，可能需要重写。

**Comment by yoyo837** [comment]
4.x的 icon 是独立包，里面肯定有ts的类型可用。

**Comment by daiyamin** [comment]
> 4.x的 icon 是独立包，里面肯定有ts的类型可用。

嗯，在这个地方找到了，@ant-design/icons/lib/components/Icon
