### ISSUE TITLE
[Issues]getFieldProps的第一个参数id能否自动匹配数组每一项并且正确返回？

### ISSUE THREAD

**Issue by V-Tom** [ant-design/ant-design#2965]
#### 本地环境

- antd 版本:latest
- 操作系统及其版本：Mac
- 浏览器及其版本:chrome latest
#### 你做了什么？

我有一个数组需要去遍历，然后每一项都需要进行input form 验证。

``` javascript
{
  qoptions.map((item,index)=>{
    return (
       <Input {...getFieldProps(`qoptions[${index}].url`, {}}/>
    )
  })
}
```

如果我按照上述方式来写,`this.props.form.validateFields`会自动返回下面结构:

``` javascript
{
  qoptions[0]:{
    url:'xxx',
    //或者其他fields
  }
}
```

所以，我需要在提交数据的时候再次遍历一次得到正确的数据

#### 你期待的结果是：

有一种简洁的方法，可以有这样的返回结果

``` javascript
{
  qoptions:[
    {
      url:'xxx',
       //或者其他fields
    }
  ]
}
```

#### 实际上的结果：

RT

#### 可重现的在线演示

无

**Comment by benjycui** [comment]
`getFieldProps(`qoptions.${index}.url`, {}}` 如何？

**Comment by V-Tom** [comment]
@benjycui 这样写的话，返回数据结构为
```javascript
{
  qoptions:{
    0.url:'xxx',
    1.url:'xxx'
    //或者其他fields
  }
}
```
之前我写自己的组件的时候也遇到过这个问题，我是用的`.`来区分对象，但是数组没有很好的解决。

`input`遍历是经常用到的，这个有好的解决方法吗？或者未来会支持？

**Comment by V-Tom** [comment]
[rf-form-input-array](http://react-component.github.io/form/examples/input-array.html)

在`rc-form` 上找到一个实例，按照这个例子，但是返回的数据结构为
```javascript
{
  keys:[1,2,3],
  url1:'xxx',
  url2:'xxx',
  url3:'xxx'
}
```
如果数组内部的这个url字段和外部重复就难办了

**Comment by benjycui** [comment]
@yiminghe rc-form 的点号支持多层嵌套如何？

**Comment by yiminghe** [comment]
多层嵌套似乎复杂很多，可以试下

**Comment by afc163** [comment]
https://github.com/mariocasciaro/object-path

**Comment by benjycui** [comment]
@V-Tom 人手不足，暂时没时间做，可以尝试 PR 到 rc-form 或者先写个工具函数处理。

**Comment by V-Tom** [comment]
>先说下我现在的问题和一些理解，可能有些错误，麻烦指正，谢谢：

`rf-form` 内部实现了` visual data ` 进行了 双向绑定，绑定入口是

```javascript
{...getFieldProps(key,{})}
```

如果不能在`rf-form`内部实现上述 **点号支持多层嵌套** 会出现下面的问题：

- 当我去删除一个 **数组 input** 的时候，我需要计算`index`然后反复的进行 `setFieldsValue ` 和 
`resetFields` 设置为下一个**数组 input**的数据，这个很麻烦，不好控制，而且**数组 input**的长度也需要额外进行控制
- 某些情况进行`resetFields`的时候 **rf-form 数据** 不正常 ，这个后面我如果重现的话会提供demo
- 并不能很方便的去控制 `form`

嗯，有空的话我会尝试PR，多谢回复

**Comment by williamkhshea** [comment]
我刚刚PR 到 rc-form。

https://github.com/react-component/form/pull/48

**Comment by afc163** [comment]
supported in `2.6.0`
