### ISSUE TITLE
Ant-Design Read-only props 

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#29653]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi can we add  a props for checkbox that has readonly? Needed to support some checkbox that needed to be disabled but still retains their styles. I hope we could add this feature.

### What does the proposed API look like?
<Checkbox readOnly={true} />

**Comment by afc163** [comment]
Use controlled mode: `<Checkbox checked={true} />`

**Comment by tempoeric** [comment]
for uncontrolled? because we are using react hook forms plus antd component

**Comment by noszone** [comment]
> Use controlled mode: `<Checkbox checked={true} />`

Could you please advise from which version this can be used? I've tried to use a boolean state or Form.Item boolean value, But still doesn't work in disabled mode. Even if set directly to true, does not help.

Code example:

```
<Form.Item
name="islunchtimecount"
valuePropName="checked"
rules={[{
type: 'boolean',
required: false,
},]}
shouldUpdate>
<Checkbox disabled={props.disabled} checked={true}> Использовать обед? </Checkbox>
</Form.Item>
```

**Comment by yoyo837** [comment]
Online demo pls.

**Comment by noszone** [comment]
@yoyo837 , however it's not working in demo please check it out here: 
https://codesandbox.io/s/exciting-chaum-dyfc6?file=/src/App.js
Only working with state (commented).

I've updated nodejs Antd to latest: npm install antd@latest (14.15.2). Then In my code above here on page I have to take out the piece - disabled={props.disabled} and only in this case checkbox is showing to me his value, But in demo this functionality is working. What I can miss?

**Comment by mellis481** [comment]
> @afc163 Use controlled mode: `<Checkbox checked={true} />`

I'm very confused why Checkbox, CheckboxGroup, Radio, and RadioGroup weren't just developed to have standard `readonly` functionality, because the convention above is not accessible at all.  You need `readonly` or `aria-readonly="true"` for a screen reader to announce the field is read-only.

Given how frequently a read-only Checkbox, CheckboxGroup, Radio, and RadioGroup exists in forms, it should be a high priority to fix this.
