### ISSUE TITLE
使用 upload 组件时 webpack 打包报错

### ISSUE THREAD

**Issue by tedpenk** [ant-design/ant-design#2966]
#### 

- antd 版本: 15.3.1
- 操作系统及其版本：OSX 10.11.6
- 浏览器及其版本: chrome 52

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：
在 webpack 打包时 less 报错：

![image](https://cloud.githubusercontent.com/assets/7235487/18311207/a51d8606-7535-11e6-9c31-4d6faf999563.png)

**Comment by afc163** [comment]
提问太随意了，antd 没有 15.3.1 版本，官网示例我测试是好的。

另外，官网示例没有用到 gulp，你应该说谎了。

**Comment by tedpenk** [comment]
我并没有说谎。。看图片就知道了，但是图片里面涉及公司信息，我就删除了。其实就是这一行报错：
![image](https://cloud.githubusercontent.com/assets/7235487/18311991/02bc2b88-753a-11e6-91ee-356b15060115.png)
希望有时间看一下。。。
没时间的话也是非常感谢！

**Comment by afc163** [comment]
你肯定不是使用 antd-init 呀，按照这个配置自己看看吧。https://github.com/ant-tool/atool-build/blob/master/src/getBabelCommonConfig.js 我重现不了就没有办法修复。

**Comment by tedpenk** [comment]
好的，我再看看，感谢！

**Comment by tedpenk** [comment]
找到原因了，是因为我在 webpack 的 less-loader 配置中加了这么一个参数：
![image](https://cloud.githubusercontent.com/assets/7235487/18377514/48f4df3a-769a-11e6-9186-8b075de1bf23.png)
删掉就行了

**Comment by afc163** [comment]
标题不要改掉，方便搜索。

**Comment by tedpenk** [comment]
好的
