### ISSUE TITLE
Is the table-prefix-cls variable in modal.less redundant?

### ISSUE THREAD

**Issue by n0ruSh** [ant-design/ant-design#29663]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/modal/style/modal.less#L2](https://github.com/ant-design/ant-design/blob/master/components/modal/style/modal.less#L2)

### Steps to reproduce
I just came across this [file](https://github.com/ant-design/ant-design/blob/master/components/modal/style/modal.less#L2) and I believe the `@table-prefix-cls` variable is redundant as it's NOT referenced in the file as far as I can see. Just want to double check :-

### What is expected?
No `@table-prefix-cls`

### What is actually happening?
`@table-prefix-cls` exists.

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 16.14.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/ef31697d26e74e9b1742790c921e7cb02ff0333e#diff-dbba730b2603ac426f23dcd2bcb5d9a2da5d92915b7742a06bcfa1b14049bf1dR2

It is useless, I believe we can remove it.
