### ISSUE TITLE
Please update example code

### ISSUE THREAD

**Issue by nichitapasecinic** [ant-design/ant-design#29677]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-bird-nuzpr?file=/index.js)

### Steps to reproduce
-

### What is expected?
the example code to work

### What is actually happening?
the error is thrown

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | react ^16.0 |
| System | Windows 10 Pro |
| Browser | Chrome |

**Comment by afc163** [comment]
Codesanbox have wrong cache, you can fix @babel/runtime as workaround, nothing we can do until codesanbox.io resolve it.

https://codesandbox.io/s/delicate-fire-djdkq?file=/package.json:134-166
