### ISSUE TITLE
TreeSelect为多选的时候默认可输入搜索？能否有控制不搜索呢？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2967]

**Comment by benjycui** [comment]
该行为与 `Select` 的统一，不知道你的使用场景是什么？

**Comment by aw6658913** [comment]
下拉树异步取的数据，我要搜索的全国省市区的话没有取回数据也是取不到的搜索没有意义，这对于客户来说客户不会知道什么叫异步数据，只会感觉怎么会没有这个地区~我看官网demo单选的可以不搜索，但是复选的就必须搜索~

**Comment by warmhug** [comment]
想要禁止掉，正常做法需要加个 api ，但目前没多少必要。变通做法，见此：https://github.com/react-component/tree-select/commit/a74b0b21632358c5221c0d4b36e04a5fe04dac44
