### ISSUE TITLE
antd3升级到4之后，Select等组件的类名和结构都发生了变化，自定义覆盖的默认样式需要重新测试？有没有官方提供的解决方案

### ISSUE THREAD

**Issue by daiyamin** [ant-design/ant-design#29676]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
无

### What is expected?
antd3升级4后不需要对自定义样式做调整

### What is actually happening?
antd3升级4后不需要对自定义样式自己适配

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 16.13.1 |
| System | 所有 |
| Browser | 所有 |

**Comment by afc163** [comment]
Select 组件重写了，DOM 结构变化很多，如果有自定义覆盖样式，需要仔细重新测试。目前没有好办法。
