### ISSUE TITLE
[Select]多选模式下传递的 value 数组内部的 id 是相同时，会出现诡异的问题

### ISSUE THREAD

**Issue by lilywang711** [ant-design/ant-design#29685]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sanchongdaxiao-antd4123-forked-n5zgr?file=/package.json:380-387)

### Steps to reproduce
点开上面的 codesandbox 链接，即可观察到

### What is expected?
下拉框显示为 测试1、普通员工

### What is actually happening?
显示为 普通员工、测试 1、普通员工

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome 88 |

---
当传递的 value 数组里有相同值时，下次再 setValue，就会出现上面链接的情况。

**Comment by xrkffgg** [comment]
Use `const [value, setValue] = React.useState(["普通员工"]);`
