### ISSUE TITLE
Upload 组件使用 css 取消动画引发 bug；

### ISSUE THREAD

**Issue by maquannene** [ant-design/ant-design#29684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/maquannene/upload-bug](https://github.com/maquannene/upload-bug)

### Steps to reproduce
yarn start 直接启动，Foo/index.md 里面的 demo 重现。

看了一下应该是只要受控方式设置 fileList ，设置 animation-duration: 0s !important; 就会导致问题

### What is expected?
增加 api 可以关闭 upload 组件的动画效果

### What is actually happening?
增加 api 可以关闭 upload 组件的动画效果

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 16.14.0 |
| System | mac os |
| Browser | chrome Version 88.0.4324.192 (Official Build) (x86_64) |

**Comment by zombieJ** [comment]
内部监听动画事件，0 就没有动画了。可以做一个兜底。
