### ISSUE TITLE
Transfer组件能不能在选中数据的时候进行删除、批量删除或其他功能呢？选中数据的时候能否暴露出这几条数据的key值？

### ISSUE THREAD

**Issue by zllcc** [ant-design/ant-design#2968]
![img](https://cloud.githubusercontent.com/assets/16065801/18339614/2465753e-75d3-11e6-8e83-a628bfe47205.jpg)

**Comment by benjycui** [comment]
`Transfer` 可以暴露 `onSelect` 事件。

**Comment by zllcc** [comment]
能否更新一版暴露onSelect事件的版本？

**Comment by benjycui** [comment]
增加事件：

* onSelectChange(sourceSelectedKeys: string[], targetSelectedKeys: string[]): void

和两个受控属性：

* sourceSelectedKeys: string[]
* targetSelectedKeys: string[]

**Comment by zllcc** [comment]
onSelectChange(selectedKeys: string[]): void做在哪个版本了？如果现在要用应该怎么办？

**Comment by benjycui** [comment]
2.0.0-beta

**Comment by zllcc** [comment]
还有我想请问下
1.左右两边的数据能不能分开操作选中的数据？
2.如图，单条数据滑过的时候，后面的转移和删除是不是还实现不了？
