### ISSUE TITLE
AntD Pro 在线预览的主题色怎么调？

### ISSUE THREAD

**Issue by scj960529** [ant-design/ant-design#29682]
在本地npm运行后，点击设置按钮只有一个主题色，如图
![2](https://user-images.githubusercontent.com/53296612/110468969-fafa4700-8113-11eb-9c6d-17244a2f2a57.png)，但是通过官网的在线预览模式，点击设置是这样子的，如图
![微信图片_20210309192746](https://user-images.githubusercontent.com/53296612/110469025-106f7100-8114-11eb-8c54-75a0c55f32d7.png)，如图，如果我本地运行也想做到这样，是我该下载插件还是怎么做？ 求大佬告知。

**Comment by xrkffgg** [comment]
可以去 https://github.com/ant-design/ant-design-pro 提
