### ISSUE TITLE
Select pop-up window cannot be closed, reopen after closing

### ISSUE THREAD

**Issue by weiliang903** [ant-design/ant-design#29696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s0hw4?file=/index.js)

### Steps to reproduce
Select the drop-down option, try to select different options

![1](https://user-images.githubusercontent.com/20644345/110587002-fedaa780-81ad-11eb-89f1-ca28df284fae.gif)

### What is expected?
Should be closed after selection

### What is actually happening?
Repeatedly opened

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | react@17.0.1 |
| System | mac os 10.15.5 |
| Browser | chrome 88.0.4324.192 |

**Comment by afc163** [comment]
Cannot reproduce in your codesandbox.

Chrome: 88.0.4324.192

**Comment by weiliang903** [comment]
![2](https://user-images.githubusercontent.com/20644345/110590319-980bbd00-81b2-11eb-9df3-a133b60a5a46.gif)

I found the reason. It was a problem with my computer. The mac(MacBook Pro 13-­inch, 2017) keyboard was triggered multiple times. This is a common problem and I need to fix it.
🤝Thanks for replying, you save my life.
This is a ridiculous question, so much time was wasted
