### ISSUE TITLE
Modal can't close and the animation don't work

### ISSUE THREAD

**Issue by MrHGinko** [ant-design/ant-design#29699]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://example.com](https://example.com)

### Steps to reproduce
1. 引入 Modal 
2. 正常使用
3. Modal弹出无动画效果, 且无法关闭, visible修改为false也无效

[![6JPLEd.png](https://s3.ax1x.com/2021/03/10/6JPLEd.png)](https://imgtu.com/i/6JPLEd)
此为 error情况下引入的lib Modal.js

[![6JPf41.png](https://s3.ax1x.com/2021/03/10/6JPf41.png)](https://imgtu.com/i/6JPf41)
此为 success情况引入的lib Modal.js

本地通过手动修改 node_modules/antd/lib/modal/Modal.js 可恢复正常

### What is expected?
Modal的正常使用

### What is actually happening?
Modal异常, 无法关闭

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | Win10 1909 |
| Browser | Chrome: 83.0.4103.97 |

---
可能是这两周? 首先发现是在4.9.1 一开始以为是版本问题.
后面与同事排查了系统, 浏览器问题后, 比对正常情况下的Modal源码后发现了该问题.
transitionName 与 maskTransitionName 于 createElement 中初始化时导致该问题
而在defaultProps中则为正常使用.

**Comment by MrHGinko** [comment]
in my opinion
在 antd/es 下查看Modal.js  code中defaultProps未定义 transitionName 与maskTransitionName, 在调用 _utils/getTransitionName 方法时 传入的 props.transitionName, props.maskTransitionName 均为undefined. 可能经此导致Modal未绑定动画

**Comment by nnecec** [comment]
解决了吗。我升级4.13之后也遇到类似问题。但别的项目升级是好的，只有一个项目也是关不掉。。

**Comment by crazyair** [comment]
提供复现

**Comment by vinceve** [comment]
I had the same issue, but it was a combination of create react app and ant design. we generate the stylesheets for ant design in our public folder, and I didn't do this locally. The behaviour was like this:

1. open a modal
2. Click a button to close the modal
3. Nothing happens (escape or nothing else even works)

After regenerating the css file for ant design it worked flawlessly.

**Comment by MrHGinko** [comment]
@vinceve Oops, thank you very much, that's a blind spot for me.
my project Antd styleSheets version is v4.6.5, ( I also use generated stylesheet file )
 So when I upgraded the version ( 4.13.0+ ), it caused this problem.

**Comment by vinceve** [comment]
Yes, I had the same problem. I eegenerated the css file and it was solved. Did it fix tour problem?

**Comment by coopercoder** [comment]
4.15.2 又出现了

**Comment by crazyair** [comment]
> 4.15.2 又出现了

https://github.com/ant-design/ant-design/compare/4.15.2...master  没看到有影响 modal 样式问题，你是遇到什么问题，能否提供复现

**Comment by LeoooY** [comment]
遇到类似的问题，原因是我（错误的）将antd库中的css抽出来单独加载，导致antd版本和引入的antd css版本不一致...

**Comment by crazyair** [comment]
> 遇到类似的问题，原因是我（错误的）将antd库中的css抽出来单独加载，导致antd版本和引入的antd css版本不一致...

![image](https://user-images.githubusercontent.com/7971419/115647558-922efd00-a356-11eb-89d1-316e36ad7afb.png)
