### ISSUE TITLE
antd v4.13.1 upload 自定义上传，会执行2次

### ISSUE THREAD

**Issue by soguagirl** [ant-design/ant-design#29707]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/e169534a](https://riddle.alibaba-inc.com/riddles/e169534a)

### Steps to reproduce
antd v4.13.1 Upload组件 自定义上传方法，会执行2次

### What is expected?
执行一次

### What is actually happening?
执行两次

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 16.14.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
实测 4.12.3 版本只会触发一次，@zombieJ 看看是否重构后符合预期。

**Comment by zombieJ** [comment]
符合预期的，第一次是全列表。第二次是单个组件的 start。
