### ISSUE TITLE
Tag onClose 回调里取消关闭

### ISSUE THREAD

**Issue by 275287902** [ant-design/ant-design#2970]
#### 本地环境

- antd 版本:1.11.0
- 操作系统及其版本：mac os 10.11.6
- 浏览器及其版本:chrome 53.0.2785.89 (64-bit)

#### 你做了什么？

引入 antd 了 Tag,并添加了onClose回调

#### 你期待的结果是：

在onClose回调里return false,会取消关闭

#### 实际上的结果：

在onClose回调里没有办法阻止Tag关闭

**Comment by afc163** [comment]
`onClose={e => e.preventDefault()}`

**Comment by 275287902** [comment]
@afc163 非常感谢这么快的回答了我，解决了我的问题，谢谢你。

**Comment by afc163** [comment]
请关闭 issue

**Comment by afc163** [comment]
。。。
