### ISSUE TITLE
Select component set open=true in modal, select downdrop don't display when reopen modal

### ISSUE THREAD

**Issue by TeresaZhang7517** [ant-design/ant-design#29704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ttzgz)

### Steps to reproduce
1. open the modal, select some options, click submit button to close the modal
2. duplicate step 1 sometimes
3. select dropdown list will not be displayed sometimes. But if you drag your browser, the dropdown list will display

### What is expected?
dropdown list will always display

### What is actually happening?
dropdown list display sometimes

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | react 16.8.6 |
| System | windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
<img width="1025" alt="图片" src="https://user-images.githubusercontent.com/507615/110620660-3bb99500-81d4-11eb-8432-db3f01097d73.png">

**Comment by TeresaZhang7517** [comment]
@afc163 I don't know how to create a really codesandbox url. I just click fork and copy the latest url. And update it as below.
https://codesandbox.io/s/antd-reproduction-template-forked-ttzgz

**Comment by TeresaZhang7517** [comment]
Resolved this issue to add destroyOnClose={true} in modal, select open property can work fine
