### ISSUE TITLE
能否将rc-dock添加到社区精选组件的推荐页面？

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#29719]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ticlo/rc-dock

rc-dock是一个可拖动 窗口/面板 的组件（dock panel)
基于rc-tabs和rc-trigger，发布两年多，60多个npm版本，在同类组件中肯定是与antd兼容最好的。

![](https://camo.githubusercontent.com/d6a6742f2128aec7a90f712156598c241efdfb28093d74394ac37cf83dab95b4/68747470733a2f2f7469636c6f2e6769746875622e696f2f72632d646f636b2f696d616765732f64656d6f2e676966)

![](https://camo.githubusercontent.com/e4d09bb48dfe28da6cbb77646ad3bb909093eee5ffc0aabffcba50a9e58ccc52/68747470733a2f2f7469636c6f2e6769746875622e696f2f72632d646f636b2f696d616765732f6e65772d77696e646f772e676966)

### What does the proposed API look like?
希望能添加到以下推荐页
https://ant.design/docs/react/recommendation
https://ant.design/docs/react/recommendation-cn

**Comment by afc163** [comment]
来个 PR
