### ISSUE TITLE
upload onchange返回的proxy的file里没有response

### ISSUE THREAD

**Issue by lsai2270** [ant-design/ant-design#29715]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
点击上传 onchange 方法中info.file没有response

### What is expected?
info.file中有接口返回的response数据

### What is actually happening?
info.file中没有response字段

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.0 |
| System | mac |
| Browser | chrome 88.0.4324.192 |

**Comment by feifeitu** [comment]
我也有同样的问题 且在组件库官网的例子里面试了 上传后onchange返回的仍然是proxy对象

**Comment by lsai2270** [comment]
> Hello @lsai2270. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @lsai2270, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

谢谢您 ,我又看了,返回的proxy里确实会有reponse ,不过如果动态控制fileList ,同时使用 info.status 在onchange 最外面打印info的话就得不到reponse,不知道为什么

**Comment by lsai2270** [comment]
> 我也有同样的问题 且在组件库官网的例子里面试了 上传后onchange返回的仍然是proxy对象

我之前是手动控制的fileList 这次更新之后,上传后接口通了,但是onchange就拿不到info.status了 ,把fileList去掉就行了, 之前是在info.status 下面控制的fileList,更新后导致,上传list出不来,

**Comment by wuyf123** [comment]
你好，我文件上传接口是通的，但是onchange返回里拿不到response 请问你是怎么获取的，antd 版本号4.13.1

**Comment by zombieJ** [comment]
Proxy 里有 response，给一下在线重现

**Comment by gantrylau** [comment]
升级4.13.1后有相同的问题，回退到4.12.3就正常了，代码没变

**Comment by alvin0216** [comment]
无意更新 antd，发现 file 是个 proxy 对象了，然后 FileReader 就报错了

**Comment by kerm1it** [comment]
> 无意更新 antd，发现 file 是个 proxy 对象了，然后 FileReader 就报错了

最新版已经去掉 Proxy 了。

**Comment by zombieJ** [comment]
`4.14.0` 已经恢复成 object，close。

**Comment by codedart2018** [comment]
4.18同样接管fileList后没有response

**Comment by jwping** [comment]
同样 response 是 undefined
