### ISSUE TITLE
Image.PreviewGroup组件未能按照正确的图片预览顺序排序

### ISSUE THREAD

**Issue by fengyuyizai** [ant-design/ant-design#29723]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/fengyu_xu/pen/oNYJZjP](https://codepen.io/fengyu_xu/pen/oNYJZjP)

### Steps to reproduce
点击重现链接
点击图片进入预览， 左右切换图片即可复现

### What is expected?
Image.PreviewGroup组件按照正确的图片排列顺序排序

### What is actually happening?
Image.PreviewGroup组件按照图片src更新的顺序排序

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | react |
| System | mac os Big Sur 11.2.2 |
| Browser | Chrome (88.0.4324.192) |

---
业务：在聊天室中，因为图片服务返回的图片数据是加密的id，需要再根据加密id取出图片，这就是一个异步的过程。

问题原因：在antd Image组件中， 由于存储格式是Map，对src的监听过程中，  src发生变化，触发组件的unRegister方法， 导致其删除原有位置上的图片，重新压栈变更的新图，导致该问题

**Comment by kerm1it** [comment]
有点没有明白你的意思？正确的排列顺序难道不是提供列表的顺序么？

**Comment by zombieJ** [comment]
> 问题原因：在antd Image组件中， 由于存储格式是Map，对src的监听过程中， src发生变化，触发组件的unRegister方法， 导致其删除原有位置上的图片，重新压栈变更的新图，导致该问题

感觉是你说的原因

**Comment by shaodahong** [comment]
嗯，因为图片 src 一开始是空属于不可预览图片，触发了 `unRegister` 导致的

**Comment by xymbem-josvu5-Cesxyp** [comment]
Why ants?
My answer of hypothesis would include:  the small size, the bruit and never give up attitude.
Up to and including; they always get to March by two’s.
I know my grandchildren love the matching ant song, we do sing and try to match.

Have a great day.

Ps: how many coders have adhd or add?
It’s just not possible, unless medication intervened.
I do hope the ants are not any any  

Sent from my iPhone

On Mar 18, 2021, at 2:36 AM, 骗你是小猫咪 ***@***.***> wrote:

﻿
Closed #29723 via react-component/image#81.
