### ISSUE TITLE
关于换肤

### ISSUE THREAD

**Issue by qinyahua** [ant-design/ant-design#29726]
既然可以为当前的页码换肤：@pagination-item-bg-active: ***
但为什么不能给当前页码的文字换肤呢？
我希望第5页是白色字，彩色底。
![image](https://user-images.githubusercontent.com/8790307/110771393-67e91a80-8295-11eb-89df-bf8f8a9688ec.png)

**Comment by yoyo837** [comment]
请考虑PR创建变量
