### ISSUE TITLE
关于换肤的分页Pagination的效果

### ISSUE THREAD

**Issue by qinyahua** [ant-design/ant-design#29728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
既然可以为当前的页码的背景色换肤：@pagination-item-bg-active
但为什么不能给当前页码的文字换肤呢？
现在换了背景色，跟文字容为一体了

### What does the proposed API look like?
增加 @pagination-item-color-active 和 @pagination-item-color-hover 类似这样的。

**Comment by qinyahua** [comment]
例图：
![image](https://user-images.githubusercontent.com/8790307/110790856-80b0fa80-82ac-11eb-8994-ac7a890682cd.png)

**Comment by xrkffgg** [comment]
应该是你设的背景 color 和 primary color 重叠了，其实我觉得最好是直接修改 className。

因为分页还有简洁模式、翻页按钮，定义变量的话，分开定义还是一起定义不好区分。
