### ISSUE TITLE
When use tooltip in modal, tooltip's visible prop is controled by modal's visible prop, tooltip didn't disappear as expected.

### ISSUE THREAD

**Issue by liuxinqiong** [ant-design/ant-design#29735]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4131-forked-nhywd)

### Steps to reproduce
Just click "Open Modal" button, then close the modal.

### What is expected?
when the modal disapeared, the tooltip disappeared too

### What is actually happening?
modal disapeared, but tooltip not

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | macOS |
| Browser | chrome 88 |

---
degrade antd version to 4.3.5, it works as expected.

**Comment by chornos13** [comment]
For quick fix, you can use prop destoryOnClose in Modal, but the drawback is that it will always re-render (componentDidMount) the Modal Body everytime you open that Modal

**Comment by liuxinqiong** [comment]
> For quick fix, you can use prop destoryOnClose in Modal, but the drawback is that it will always re-render (componentDidMount) the Modal Body everytime you open that Modal

Thanks for you reply, I will try it at once!

**Comment by kerm1it** [comment]
@liuxinqiong Try it: https://codesandbox.io/s/jiben-antd4131-forked-41jb0?file=/index.js

Because modal won't rerender when it is closed unless using `forceRender` in https://github.com/ant-design/ant-design/issues/27372
