### ISSUE TITLE
CheckBox not able to be checked by default when Wrapped by CheckBox.Group

### ISSUE THREAD

**Issue by jzhao62** [ant-design/ant-design#29740]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/old-voice-4vpd6?file=/src/App.tsx)

### Steps to reproduce
N.A

### What is expected?
All checkBoxs should be initially checked

### What is actually happening?
CheckBoxes inside CheckBox.Group is not being checked

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.01 |
| System | Ubuntu 20.04 |
| Browser | Chrome: 87.0.4280.66 |

**Comment by afc163** [comment]
It is intented, you should use `value` in Check.Group.
