### ISSUE TITLE
Modal.method中onOkProps配置loading属性无效

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design#29747]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce
```
  Modal.confirm({
            okButtonProps: { loading: true },
})```

### What is expected?
button按钮loading状态

### What is actually happening?
没有显示

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.0 |
| System | win |
| Browser | chrome |


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by mtiger95** [comment]
遇到同样的问题。重现地址：
https://codesandbox.io/s/antd-reproduction-template-forked-2k51ns?file=/src/App.js
