### ISSUE TITLE
IE8环境下，Menu的一级导航的箭头在点击的时候无法上下翻转。Table的加载数据过程中模糊效果有问题。Table的数据在加载前，整体会偏移一下，加载完成后又恢复偏移的位置。

### ISSUE THREAD

**Issue by dingzhang** [ant-design/ant-design#2974]
#### 本地环境

- antd 版本: 1.11
- 操作系统及其版本：win7
- 浏览器及其版本: IE8

#### 你做了什么？
1 创建Menu组件
2 创建Table组件，并且加载数据
3 创建Table组件，加载数据
#### 你期待的结果是：
1 Menu在点击时候，箭头正常上下翻转
2 加载过程中，有一层模糊遮罩层
3 像在chrome中一样

#### 实际上的结果：
1 箭头始终向下
2 无遮罩模糊层，后来自己加了一个zindex，临时解决此问题
3 Table加载数据前，始终会移动一下，加载结束后又恢复

#### 可重现的在线演示

![menu](https://cloud.githubusercontent.com/assets/4969756/18344078/76b43130-75e8-11e6-868a-897ba66f44e4.png)

**Comment by dingzhang** [comment]
IE8下，无遮罩模糊层的时候，加载数据的时候就不会有偏移现象

**Comment by benjycui** [comment]
一个问题一个 issue 比较好。。。

1. 箭头翻转是用 CSS3 实现的，这样实现动画也方便，不想为了兼容 IE8 而增加代码，所以不会修改。

2, 3 可以提供重现 demo 和步骤？

**Comment by dingzhang** [comment]
你好，
问题1 箭头翻转，并不是要IE8下的css动画效果。我看了箭头的css，是写了兼容IE8的写法，用的progid:DXImageTransform.Microsoft.xxx，可是没有生效，我觉得这是bug。还有您的意思是antd不打算兼容IE8了吗？
问题2 和 问题3 demo就是官网里的那个获取随机姓名的例子
import { Table } from 'antd';
import reqwest from 'reqwest';

const columns = [{
  title: '姓名',
  dataIndex: 'name',
  sorter: true,
  render: name => `${name.first} ${name.last}`,
  width: '20%',
}, {
  title: '性别',
  dataIndex: 'gender',
  filters: [
    { text: 'Male', value: 'male' },
    { text: 'Female', value: 'female' },
  ],
  width: '20%',
}, {
  title: '邮箱',
  dataIndex: 'email',
}];

const Test = React.createClass({
  getInitialState() {
    return {
      data: [],
      pagination: {},
      loading: false,
    };
  },
  handleTableChange(pagination, filters, sorter) {
    const pager = this.state.pagination;
    pager.current = pagination.current;
    this.setState({
      pagination: pager,
    });
    this.fetch({
      results: pagination.pageSize,
      page: pagination.current,
      sortField: sorter.field,
      sortOrder: sorter.order,
      ...filters,
    });
  },
  fetch(params = {}) {
    console.log('请求参数：', params);
    this.setState({ loading: true });
    reqwest({
      url: 'http://api.randomuser.me',
      method: 'get',
      data: {
        results: 10,
        ...params,
      },
      type: 'json',
    }).then(data => {
      const pagination = this.state.pagination;
      // Read total count from server
      // pagination.total = data.totalCount;
      pagination.total = 200;
      this.setState({
        loading: false,
        data: data.results,
        pagination,
      });
    });
  },
  componentDidMount() {
    this.fetch();
  },
  render() {
    return (
      <Table columns={columns}
        rowKey={record => record.registered}
        dataSource={this.state.data}
        pagination={this.state.pagination}
        loading={this.state.loading}
        onChange={this.handleTableChange}
      />
    );
  },
});

ReactDOM.render(<Test />, mountNode);

 在IE8下就会有这两个问题，第一是给 css类 .ant-spin-container覆盖样式progid:DXImageTransform.Microsoft. xxx ; z-index:1
第二个就不知道怎么改了，总是先偏移，且遮罩出现的时候，表格还是可以mouseover的

**Comment by benjycui** [comment]
Online demo, 需要花费较多时间精力才能重现的 issue，优先级也会较低。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by dingzhang** [comment]
这个很好重现的啊，只要用IE8立马重现呀

在 2016年9月10日，14:37，Benjy Cui <notifications@github.com<mailto:notifications@github.com>> 写道：


Online demo, 需要花费较多时间精力才能重现的 issue，优先级也会较低。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

―

**Comment by benjycui** [comment]
> 官网用的是 React@15，所以 IE8 的问题测不了

**Comment by dingzhang** [comment]
我的意思是官网的例子，放到react0.14的环境中，就可以看到我描述的效果了啊。
难道antd是彻底放弃IE8吗？

**Comment by afc163** [comment]
由于 react 本身已经不支持 IE8，antd 也只提供有限度的支持。IE8 下目前只做基本的可用兼容，样式细节不再花时间调了，有需求可以直接 PR ~

**Comment by dingzhang** [comment]
。。。
基本的可用兼容指的是哪些方面啊？
在IE8下table在load过程中，遮罩层没有遮住table，以及莫名其妙的偏移一下下，这些问题如果不解决，
那么基本的兼容的意义又何在呢？
