### ISSUE TITLE
InputNumber 在Form表单中使用，设置 precision 属性后，输入操作有很多问题

### ISSUE THREAD

**Issue by didi5683** [ant-design/ant-design#29754]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
1、InputNumber 在Form表单中通过 Form.Item 包裹使用
2、设置 precision属性为2，<InputNumber min={0} precision={2} />
3、当用户输入第一个数字时，系统自动添加了两位小数位，同时光标移动到最末尾，影响用户的连续输入。
4、同时，无法将输入框清空，删除所有数值后，当焦点离开输入框，自动变为 0.00（无法设置为 null ）

### What is expected?
1、用户可以在输入框中连续输入数字，当焦点离开输入框时再进行检查并添加小数位
2、允许输入框清空，而不是始终设置为 0.00

在 antd 4.12 版本中没有以上的这些问题，升级到 4.13.0 后，出现该问题，更新到 4.13.1 问题依然存在。

### What is actually happening?
希望尽快处理该问题

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
没看到你说的问题，重现给一个：https://codesandbox.io/s/jibenshiyong-antd4140-forked-6nzrt?file=/index.js

**Comment by didi5683** [comment]
刚才又检查了一遍，似乎输入时焦点定位的问题已经解决。  同时查询到一个相似的问题报告：https://github.com/ant-design/ant-design/issues/29609

但是 InputNumber 输入框清空的问题，依然存在。设置了 precision 属性后，一旦输入数字，或焦点进入输入框，就无法再清空了。删除输入框中的内容，焦点离开输入框，会自动设置为 0

希望得到 null 而不是 0

**Comment by didi5683** [comment]
> 没看到你说的问题，重现给一个：https://codesandbox.io/s/jibenshiyong-antd4140-forked-6nzrt?file=/index.js

刚才又检查了一遍，似乎输入时焦点定位的问题已经解决。 同时查询到一个相似的问题报告：#29609

但是 InputNumber 输入框清空的问题，依然存在。设置了 precision 属性后，一旦输入数字，或焦点进入输入框，就无法再清空了。删除输入框中的内容，焦点离开输入框，会自动设置为 0

希望得到 null 而不是 0

**Comment by haledc** [comment]
遇到相同的问题，刚想提一个 issue，发现有人遇到类似的问题并提了一个 issue。

https://codesandbox.io/s/inputnumber-cannot-clear-zn4o7?file=/index.js

现阶段，我把 precision 属性去掉后，有没有什么好的方法去管控值为 2 位小数呢？不胜感激！

**Comment by yoyo837** [comment]
为啥要去掉本就设计来控制小数位的precision又还是要求能控制小数位？

**Comment by haledc** [comment]
@yoyo837 你好。
因为现在使用了 precision 后无法清空值，在删掉值后，等输入框失焦后会自动设置值为`0.00`。
但是现在有使用场景要求：在删掉值后，不应该去自动设置一个`0.00`的值，因为这个`0.00`有时并不能满足要求。
在目前这个 issue 没解决之前，只能暂时先舍弃 precision 这个属性，看能否用别的方法来管控小数精度。

**Comment by yoyo837** [comment]
自己做成受控能否解决问题？

**Comment by haledc** [comment]
- 回退到 antd v4.12.0 版本，设置 precision 后可以清空值，不会自动生成`0.00`
- 使用`<Form.Item>`的 `normalize` 属性可以解决部分问题

**Comment by didi5683** [comment]
InputNumber 设置 precision 属性后，无法清空输入框内容，明显就是一个 BUG
希望能尽快修复

**Comment by alvin0216** [comment]
InputNumber 在设置 precision=0 后，changed 的数据和格式化的数据不一致。这是否就是 `BUG` 呢？

我的目的是只想让用户输入整数

@afc163 @zombieJ

https://user-images.githubusercontent.com/34113677/113100362-e817f580-922d-11eb-949b-adedd5b6e436.mov
