### ISSUE TITLE
Table使用components属性每次更新数据源会导致子组件重新加载。

### ISSUE THREAD

**Issue by SmartWrh** [ant-design/ant-design#29750]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/SmartWrh/antd-sort-issue](https://github.com/SmartWrh/antd-sort-issue)

### Steps to reproduce
提供了两个标签页，一个使用了 `components` 一个没有使用，点击按钮可以观察到一个有进度动画一个没有

### What is expected?
都应该有进度动画

### What is actually happening?
一个没有进度动画

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | win |
| Browser | chrome |

---
这是简化过后的代码，项目需求是使用了 ` react-sortable-hoc` 发现的问题
```
DraggableContainer = props => (
    <SortableContainer
      useDragHandle
      disableAutoscroll
      helperClass="row-dragging"
      onSortEnd={this.onSortEnd}
      {...props}
    />
  );

  DraggableBodyRow = ({ className, style, ...restProps }) => {
    const { dataSource } = this.state;
    // function findIndex base on Table rowKey props and should always be a right array index
    const index = dataSource.findIndex(x => x.index === restProps['data-row-key']);
    return <SortableItem index={index} {...restProps} />;
  };

  render() {
    const { dataSource } = this.state;

    return (
      <Table
        pagination={false}
        dataSource={dataSource}
        columns={columns}
        rowKey="index"
        components={{
          body: {
            wrapper: this.DraggableContainer,
            row: this.DraggableBodyRow,
          },
        }}
      />
    );
  }
```

**Comment by SmartWrh** [comment]
后经过研究改为`class`组件写法解决。

**Comment by BoBoooooo** [comment]
> 后经过研究改为`class`组件写法解决。

你好 也遇到这个问题了 请问是怎么解决的
