### ISSUE TITLE
如何通过ref获取到Input组件中的input标签

### ISSUE THREAD

**Issue by wjw760306378** [ant-design/ant-design#29765]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4131-forked-hjqdb?file=/test.js)

### Steps to reproduce
无重现步骤

### What is expected?
期望能获取到底层的input dom元素

### What is actually happening?
无法通过api直接获取

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.14.0 |
| System | win10 |
| Browser | chrome 83.0.4103.116 |

**Comment by yoyo837** [comment]
【这里如何不通过input获取到input这个dom元素】具体是什么意思？

`findDOMNode` ? 可是已经弃用了
