### ISSUE TITLE
On demand import doesn't work on destructuring components

### ISSUE THREAD

**Issue by VasudevHarshal-123** [ant-design/ant-design#29767]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/66635027/how-to-import-ant-design-on-demand-to-work-with-components-which-does-destructur](https://stackoverflow.com/questions/66635027/how-to-import-ant-design-on-demand-to-work-with-components-which-does-destructur)

### Steps to reproduce
Import antd components on-demand with the following syntax:
import { Tabs } from "antd/lib/tabs";
import 'antd/lib/tabs/style/css';
import { Collapse } from "antd/lib/collapse";
import 'antd/lib/collapse/style/css';
import { Select } from "antd/lib/select";
import 'antd/lib/select/style/css';

const { Panel } = Collapse;
const { TabPane } = Tabs;
const { Option } = Select;

### What is expected?
It is expected for the Panel, TabPane, Option components to be destructured properly.

### What is actually happening?
Getting error: TypeError: Cannot destructure property 'Panel' of 'antd_lib_collapse__WEBPACK_IMPORTED_MODULE_3__.Collapse' as it is undefined.

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
```diff
- import { Tabs } from "antd/lib/tabs";
+ import Tabs from "antd/lib/tabs";
```

or

```diff
- import { Tabs } from "antd/lib/tabs";
+ import Tabs from "antd/es/tabs";
```
