### ISSUE TITLE
1.7.0 的Popconfirm 组件

### ISSUE THREAD

**Issue by dodospace** [ant-design/ant-design#2976]
我在用1.7.0版本的Popconfirm组件的时候，渲染的时候报错
`warning.js:45 Warning: Failed propType: Invalid prop `popup` supplied to `Trigger`, expected a ReactNode. Check the render method of `Tooltip`.`

然后点击按钮的时候提示
`invariant.js:39 Uncaught Invariant Violation: onlyChild must be passed a children with exactly one child.`

请问这是啥问题导致的？

**Comment by afc163** [comment]
你又不给重现或代码，又要解决问题，这让我们很难办。

**Comment by dodospace** [comment]
不好意思
`import { Popconfirm, message, Button } from 'antd'`
`<Popconfirm placement="right" title={'是否删除？'} onConfirm={this.handleDelete}>
                    <a href="javascript:void(0)">删除</a>
  </Popconfirm> `
我就简单的引用了你们demo的例子，之前没啥问题，今天就这样，渲染的时候就warning了

**Comment by afc163** [comment]
http://codepen.io/afc163/pen/kkWRJG?editors=001

**Comment by dodospace** [comment]
我找到问题了，用了babel-plugin-antd之后，根目录添加了.babelrc文件导致的
```javascript
{
  "presets": [
    "es2015",
    "react"
  ],
  "plugins": [["antd"]]
}
```
是我配置文件写错了吗？

**Comment by afc163** [comment]
试试

```
// .babelrc
{
  "presets": [
    "es2015",
    "react"
  ],
  "plugins": ["antd"]
}
```
