### ISSUE TITLE
当Select options里出现相同的key，且存在指定notFoundContent或者notFoundContent=undefined，连续点击Select会出现重复的options

### ISSUE THREAD

**Issue by kiki1027** [ant-design/ant-design#29769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-gauss-3btfh?file=/index.js)

### Steps to reproduce
连续点击Select

### What is expected?
正确显示options

### What is actually happening?
对于重复key值的options，重复展示了

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome 89 |

---
重现链接：https://codesandbox.io/s/nice-gauss-3btfh?file=/index.js
问题描述如题，当存在指定 `notFoundContent = null` 时，不会出现该问题，求指教。

![复现图](https://user-images.githubusercontent.com/27715728/111137687-0dfc9380-85ba-11eb-9d98-4b5be7ff4d3b.png)

**Comment by yoyo837** [comment]
React 依赖key做render，key重复会导致渲染异常

**Comment by kiki1027** [comment]
> React 依赖key做render，key重复会导致渲染异常，与antd无关

react 本身出现key重复貌似也不会出现这样的现象，v3的select会有该现象，v4不会。

**Comment by crazyair** [comment]
不推荐重复，如果重复了，还是修复比较好。
