### ISSUE TITLE
Sider组件默认收起时，子菜单会悬浮出来，且此时切换收起状态，会导致二级菜单收起

### ISSUE THREAD

**Issue by izhouteng** [ant-design/ant-design#29770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bggnq?file=/index.js)

### Steps to reproduce
问题1：如果默认收起Sider，且设置了defaultOpenKeys，二级菜单会悬浮出来（如何不悬浮出来？）。
![QQ截图20210316153206.png](https://i.loli.net/2021/03/16/EKHCMwDPY7eLscW.png)

默认收起，且collapsedWidth设为0，首次打开二级菜单会闪烁（如何不闪烁？）。  
![GIF11.gif](https://i.loli.net/2021/03/16/DwNoIjklnReYtpV.gif)

问题2：Sider默认收起时，点展开，会导致defaultOpenKeys打开的二级菜单收起（如何不让二级菜单收起？）。
![99.gif](https://i.loli.net/2021/03/16/vE4wXVc2pnCZFSg.gif)

### What is expected?
Sider默认收起时，二级菜单不应该悬浮出来（我看过Ant Design Pro、ivew Pro都不会悬浮出来）
Sider默认收起时，且收起宽度为0时，首次打开不应该改出现莫名闪烁。（Ant Design Pro、ivew Pro无此问题）

### What is actually happening?
Sider默认收起时，首次打开，二级菜单莫名悬浮出来了。（如上图所示）

Sider默认收起 + 收起宽度为0时，首次打开会出现莫名闪烁。（如上图所示）

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chorme 89 |

---
我尝试升级到最新的 antd 4.14.0 问题任然存在。

**Comment by izhouteng** [comment]
#27995 #29401 闪烁问题在这两个issue均有被提到，但我发现目前还未被修复，望尽快修复此bug。 @afc163

**Comment by izhouteng** [comment]
@afc163 大佬看看这个问题8，发帖8天了都，窝每隔1小时窝都看看宁回复没有。 这问题这么明显难道就不解决了吗？

**Comment by afc163** [comment]
不好解决。。

**Comment by afc163** [comment]
Fixed in antd@4.16.1
