### ISSUE TITLE
为什么beforeUpload 返回false图片还是上传成功？

### ISSUE THREAD

**Issue by CenturyJi** [ant-design/ant-design#29778]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhishangchuan-png-tupian-antd4140-forked-5oc5s?file=/index.js)

### Steps to reproduce
import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { Upload, Button, message } from 'antd';
import { UploadOutlined } from '@ant-design/icons';

const Uploader = () => {
  const props = {
    beforeUpload: file => {
      if (file.type !== 'image/png') {
        message.error(`${file.name} is not a png file`);
      }
      return file.type === 'image/png' ? true : false;
    },
    onChange: info => {
      console.log(info.fileList);
    },
  };
  return (
    <Upload {...props}>
      <Button icon={<UploadOutlined />}>Upload png only</Button>
    </Upload>
  );
};

ReactDOM.render(<Uploader />, document.getElementById('container'));

### What is expected?
beforeUpload 上传文件之前的钩子，参数为上传的文件，若返回 false 则停止上传。 

### What is actually happening?
beforeUpload 上传文件之前的钩子，参数为上传的文件，若返回 false 还是上传成功

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | react |
| System | windows |
| Browser | Chrome |

---
看了下官网代码（只支持PNG格式），里面写的是 Upload.LIST_IGNORE，这个代替 false了吗？ 如果代替的话文档也应该更新下吧

**Comment by poozhu** [comment]
仔细看看文档，返回 false 是阻止了文件的上传请求，返回 Upload.LIST_IGNORE 可以阻止请求且取消在文件列表的展示，你也可以使用受控的 fileList
