### ISSUE TITLE
升级到4.14.0版本后，SELECT失效，无法选择

### ISSUE THREAD

**Issue by xubitao** [ant-design/ant-design#29774]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://alibaba-inc.com](http://alibaba-inc.com)

### Steps to reproduce
今天构建时，ANTD的包升级到了4.14.0，结果导致用户反馈下拉框无法使用。立即回滚到4.12.0后恢复正常

### What is expected?
4.14.0能正常使用。

### What is actually happening?
无法使用。

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^16.13.1 |
| System | MAC |
| Browser | Chrome |

**Comment by sjw441500** [comment]
我也碰到了一样的问题
