### ISSUE TITLE
DatePicker onBlur event issue with forms

### ISSUE THREAD

**Issue by sagge** [ant-design/ant-design#29775]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rbtii)

### Steps to reproduce
Hi,

I am trying to implement onBlur and onKeyDown functionalities for DatePicker that would use moment to format the user input to correct format for DatePicker. However, the event passed to onBlur callback of DatePicker seems to be getting the previous DatePicker value within its target value rather than the value that is inputted to the input field when the onBlur is called. The issue arises with Antd version greater than 4.9.4. With version 4.9.4 or lower, the provided implementation works fine for the onBlur functionality. This applies to TypeScript environments. When reproduced in codesandbox in JavaScript, version 4.12.2 and lower seem to be working and version 4.12.3 seems to be the first version affected.

The problem is that I would like to have also similar implementation for the onKeyDown callback, where user could confirm their input by pressing 'Enter' button and DatePicker would accept the date as long as moment is able to form a valid date from the input. The provided implementation works fine with Antd version >= 4.10.0 but with version greater than 4.9.4, the onBlur callback won't receive the correct target value on the focus event on TypeScript environments. I can't use version 4.9.4 as the onKeyDown was introduced on version 4.10.0 and on the other hand, I can't use version greater than 4.9.4 as the onBlur won't work with the newer versions.

DatePicker with onBlur and onKeyDown implementations:
```
import React from 'react';

import { DatePicker } from 'antd';
import { PickerProps } from 'antd/lib/date-picker/generatePicker';
import { Moment } from 'moment';
import moment from 'moment-timezone';

export type DatePickerProps = PickerProps<Moment> & {
  moment: typeof moment;
};

export class DatePickerAutoaccept extends React.Component<DatePickerProps> {
  private inputRef: any;
  constructor(props: DatePickerProps) {
    super(props);
    this.inputRef = React.createRef();
  }
  render() {
    const onBlur = (elem: React.FocusEvent<HTMLInputElement>) => {
      if (elem.target.value === '' && this.props.onChange) {
        this.props.onChange(null, elem.target.value);
        return;
      }
      const value = this.props.moment(elem.target.value, this.props.format as string);
      if (value && value.isValid() && this.props.onChange) {
        this.props.onChange(value, elem.target.value);
      }
    };
    const onKeyDown = (elem: React.KeyboardEvent<HTMLInputElement>) => {
      if (elem.code === 'Enter') {
        if (this.inputRef && this.inputRef.current) {
          this.inputRef.current.blur();
        }
      }
    };
    return <DatePicker {...this.props} ref={this.inputRef} onBlur={onBlur} onKeyDown={onKeyDown} />;
  }
}
```

How the component is being used:
```
<Form
  initialValues={initialValues}
  onFinish={onFinish}
  onFinishFailed={onFinishFailed}
  form={form}
  layout="vertical"
>
  <Form.Item
    name={['birthdate']}
    label="Syntymäaika"
    validateTrigger={['onSubmit', 'onBlur', 'onChange']}
    rules={[dateRequireRule]}
  >
    <DatePickerAutoaccept
      placeholder="pp.kk.vvvv"
      className="datePicker"
      size="large"
      format={dateFormat}
      defaultPickerValue={moment(new Date()).subtract(60, 'years')}
      disabledDate={disabledDate}
      moment={moment}
    />
  </Form.Item>
</Form>
```

### What is expected?
Expecting onBlur to receive the current input value of the DatePicker input rather than the previous selected DatePicker value. Functionality has changed since version 4.9.4. Version 4.9.4 and lower are working as expected when working in TypeScript environment. In JavaScript environment (codesandbox), the first affected version seems to be 4.12.3.

Expected behaviour would be as follows. User inputs a date as `1.1.1991` or `1 1 1991` to the DatePicker input field and clicks away from the field. `01.01.1991` would be selected as DatePicker value.

### What is actually happening?
DatePicker onBlur event receives older target value than is expected

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 17.0.1 |
| System | macOS 11.2.2 |
| Browser | Google Chrome Version 89.0.4389.82 |

**Comment by sagge** [comment]
Simplified reproduction codesandbox code can be found here: https://codesandbox.io/s/antd-reproduction-template-forked-q6xwe

With Antd version 4.12.2 the event.target.value that onBlur receives seems to be correct. With version 4.12.3 or newer, the onBlur receives the last DatePicker value as event.target.value rather than the value in the DatePicker input.

**Comment by zombieJ** [comment]
Do not rely on `event.target.value`. This is not what real value by DatePicker. You should always get correct `value` by `onChange` event.

**Comment by sagge** [comment]
onChange won't help in this case as I am trying to accomplish an onBlur functionality using onBlur callback of the DatePicker component. The problem is that the event that onBlur receives is incorrect from antd version 4.12.3 upwards.

onChange triggers when the new value is selected from DatePicker by clicking the date and onBlur when the focus is lost from the DatePicker input field. I am trying to implement a functionality where the date would be selected when correct date is inputted to the input field and the user clicks away from the DatePicker, so that the user wouldn't have to know that they need to confirm the date by clicking the date from the calendar.

At the current state the DatePicker is very hard to use as the value clears after the focus is lost even though the user inputted the correct date to the input field. The fact that user has to confirm the date by clicking on the correct date from the calendar makes the whole component very non intuitive to use. Setting the date on onBlur callback would solve this issue and that is what I am trying to accomplish. onChange won't trigger until the user confirms the date from the calendar so I have to rely on onBlur and to the event that onBlur receives.

Please reopen.

**Comment by sagge** [comment]
@brandudno Unfortunately I was unable to solve the issue using antd components. Ended up using react-datepicker (https://reactdatepicker.com/) and styled it to match the rest of components. React-datepicker seems to be working really well in our use case and although it is little extra work to make the ui look seamless with antd components, I would definitely recommend checking it out.

**Comment by brandudno** [comment]
Thanks @sagge, having issues with react-datepicker too unfortunately, trying to import into a functional component and get the following `JSX element type 'DatePicker' does not have any construct or call signatures.`. Don't suppose you encountered anything like this?

**Comment by sagge** [comment]
@yimity That seems to be a viable workaround, thanks! I would still like to see the "onBlur" functionality embedded to the standard antd DatePicker to improve its usability.
