### ISSUE TITLE
RangeDate （DatePicker） 组件建议 

### ISSUE THREAD

**Issue by jsrider** [ant-design/ant-design#2977]
- 给RangeDate组件传初始值  ["08:53 09/09/2016","09:53 09/09/2016"] 提交表单，值为 ["08:53 09/09/2016","09:53 09/09/2016"]，format  HH:mm MM/dd/yy

- 选择任意区间，提交表单，值为 ["2016-09-15T00:53:00.000Z","2016-09-16T00:53:00.000Z"]

两种数据格式不一样了，第一种是配合  format 传递的格式，传其他格式，会报错。

提交两种格式，这显然不合理，能不能针对这个问题优化一下~ 非常感谢!

**Comment by benjycui** [comment]
2.0 会改成 moment，可以自定义提交的格式。
