### ISSUE TITLE
关于表格组件树状属性问题

### ISSUE THREAD

**Issue by txp1035** [ant-design/ant-design#29782]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一般后端数据模型都是定好了，所有返回的对象里面都会有children，没有数据就是个空数组，我希望如果children是空数组的情况不要显示 ，因为这样没有意义

### What does the proposed API look like?
已有api

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13002#issuecomment-775865374

**Comment by afc163** [comment]
你可以需要提前处理一下数据：https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941

**Comment by txp1035** [comment]
@chenshuai2144 

> 你可以需要提前处理一下数据：[#1365 (comment)](https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941)

我也想过自己处理，但是感觉这个底层能给与支持能更好用，拿到数据去递归一次还是有点难受的，如果有其他场景是不是可以考虑增加api区分之类的，或者有更好的方案~

**Comment by m430** [comment]
@afc163 这个问题表格希望通过children的数据来默认逻辑去展示不展示展开的icon，感觉可能实际的业务场景要复杂的多，所以希望出一个api： showExpandIcon : (record) => Boolean; 用户至少可以自定义渲染逻辑，我觉得更合适一些。
