### ISSUE TITLE
Unused javascript from peer dependency @ant-design.

### ISSUE THREAD

**Issue by VasudevHarshal-123** [ant-design/ant-design#29785]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/66638486/remove-unused-javascript-from-ant-design](https://stackoverflow.com/questions/66638486/remove-unused-javascript-from-ant-design)

### Steps to reproduce
I'm using the "Menu" component of antd in my create-react-app project. When I go to chrome developer tool->source->coverage. I see a huge chunk on unused javascript by @ant-design. I read that the latest version will resolve this issue but it didn't.

### What is expected?
A negligible amount of unused javascript is expected.

### What is actually happening?
A large amount of unused javascript is seen from peer dependency @ant-design.

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Unused code exist in 2 part.

#### Unused Component

Enable TreeShaking of webpack to remove unused code.

#### Component Logic code

Component logic code is the key logic to handle `props` interactive. For example, Button component provides `loading` props but your app do not use this. It's full ability provided by antd. If you do not want these part, you need fork antd to remove related for to reduce the bundle size.

**Comment by VasudevHarshal-123** [comment]
@zombieJ I'm already importing components on demand like:
`import Tabs from "antd/lib/tabs";`
I even tried lazy loading `const Tabs = React.lazy(() => import("antd/lib/tabs"));` but throws error `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`
I'm using create-react-app and cannot configure webpack as I want to avoid ejecting.
