### ISSUE TITLE
关于在组件中“import styles from './***.css';”引用同目录下的外部CSS文件

### ISSUE THREAD

**Issue by shitianjie** [ant-design/ant-design#2978]
#### 本地环境

- antd 版本: 1.11.0
- 操作系统及其版本：Windows 10
- 浏览器及其版本: Chrome 版本 52.0.2743.116 (64-bit)

### 在组件中`import styles from './***.css';`引用同目录下的外部CSS文件
1、`return (<div className={styles.***} ></div>)`时样式无法加载，在浏览器端调试时发现虚拟div不能显示class。最终的解决办法是直接`import './***.css';`；
2、给出的Todo应用实例中如Todo.jsx文件中`import styles from './Todo.less';`，在编辑器Webstorm中styles一直有波浪线提示“Default export is not declared in imported module”。而且，同目录下的Todo.less文件没有写.text样式，为什么Todo.jsx文件中可以引用`<div className={styles.text}> {text} </div>？`

#### 你期待的结果是：
像官网给出的Todo应用实例一样正常显示。

#### 实际上的结果：
无法显示引用的外部CSS样式，在浏览器端调试时发现虚拟div不能显示class。

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/blob/1.1.0/boilerplates/plain-react/webpack.config.js#L21-L29
