### ISSUE TITLE
chrome 89版本下，因为table的ellipsis以来Typography，但是white-space: nowrap的效果和之前版本不一致了

### ISSUE THREAD

**Issue by oldturkey** [ant-design/ant-design#29783]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-antd4131-forked-oq1t1?file=/index.css)

### Steps to reproduce
如链接所示，表格列给定的width不生效，拖拽无法改变最小列宽

### What is expected?
89以下版本的效果，单元格可以动态伸缩，white-space: nowrap不会让文本尽可能的展示出来。

### What is actually happening?
表格列给定的width不生效，拖拽无法改变最小列宽

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.14 |
| System | macos 10.15.7  |
| Browser | chrome 89之后的版本 |

---
使用text-overflow: ellipsis;
      display: -webkit-box;
      -webkit-box-orient: vertical;
      -webkit-line-clamp: 1;
      overflow: hidden;
可以修复该问题。

**Comment by yoyo837** [comment]
`.ant-table-fixed` 有没有使用`width: max-content` ?

**Comment by oldturkey** [comment]
> `.ant-table-fixed` 有没有使用`width: max-content` ?

是的，width: max-content是计算的nowrap的宽度所以才会撑大div么？  试了一下指定scroll：x为具体数值确实是可以的。 这样的话是需要我动态计算出scroll.x的值就不会有问题了嘛

**Comment by yoyo837** [comment]
去掉即可

**Comment by yoyo837** [comment]
@afc163 看看要不要更新文档呢

**Comment by zombieJ** [comment]
可以加个 FAQ

**Comment by afc163** [comment]
合并到 #29795
