### ISSUE TITLE
TypeError undefined is not an object (evaluating 'r.startPos.x') 

### ISSUE THREAD

**Issue by ilabsgerry** [ant-design/ant-design#29794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drawerdemo-z66dd)

### Steps to reproduce
TypeError undefined is not an object (evaluating 'r.startPos.x') 
    ../node_modules/rc-drawer/es/DrawerChild.js:176 
    ../node_modules/@bugsnag/browser/dist/bugsnag.js:2709 

### What is expected?
no crash

### What is actually happening?
only some users crash

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.14.0 |
| System | ios 14.x |
| Browser | Mobile Safari UI/WKWebView |

---
TypeError undefined is not an object (evaluating 'r.startPos.x') 
    ../node_modules/rc-drawer/es/DrawerChild.js:176 
    ../node_modules/@bugsnag/browser/dist/bugsnag.js:2709

**Comment by OleksiiKachan** [comment]
still happening on antd 4.16.13
