### ISSUE TITLE
需要拖拽同时支持上传文件夹和文件上传

### ISSUE THREAD

**Issue by 4-1-1** [ant-design/ant-design#29793]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户可以选择多个文件上传，也可以拖动文件夹进行上传

### What does the proposed API look like?
无变化

**Comment by 4-1-1** [comment]
在上传组件也提了issue
#https://github.com/react-component/upload/issues/305

**Comment by afc163** [comment]
https://codesandbox.io/s/tuozhuaishangchuan-antd4140-forked-opx6d?file=/index.js

**Comment by 4-1-1** [comment]
@afc163 现在选择支持文件夹上传的时候，的确可以拖拽文件夹，但是支持文件夹上传，用户无法选择上传单个文件了。
所以现在想要的是支持上传的时候选择单个文件，但是拖拽支持文件夹和文件

**Comment by afc163** [comment]
不太好处理，文件夹上传目前是直接用的原生 input 的 directory 属性。

**Comment by t634146397** [comment]
> @afc163现在选择支持文件夹上传的时候，确实可以拖拽文件夹，但是支持文件夹上传，用户无法选择上传单个文件了。所以现在想要的是支持上传的时候选择单个文件，但是拖拽支持文件 夹和文件

可以的

**Comment by Aric-sky** [comment]
> > @afc163现在选择支持文件夹上传的时候，确实可以拖拽文件夹，但是支持文件夹上传，用户无法选择上传单个文件了。所以现在想要的是支持上传的时候选择单个文件，但是拖拽支持文件 夹和文件
> 
> 用骚操作实现

怎么个骚操作法？

**Comment by wianleo** [comment]
> > > @afc163现在选择支持文件夹上传的时候，确实可以拖拽文件夹，但是支持文件夹上传，用户无法选择上传单个文件了。所以现在想要的是支持上传的时候选择单个文件，但是拖拽支持文件夹和文件
> > 
> > 
> > 使用骚操作实现
> 
> 怎么个骚操作法？

实现了吗

**Comment by wianleo** [comment]
> > > @afc163现在选择支持文件夹上传的时候，确实可以拖拽文件夹，但是支持文件夹上传，用户无法选择上传单个文件了。所以现在想要的是支持上传的时候选择单个文件，但是拖拽支持文件夹和文件
> > 
> > 
> > 使用骚操作实现
> 
> 怎么个骚操作法？

实现了吗

**Comment by zhengminhui** [comment]
any update on this?

**Comment by t634146397** [comment]
> > > @afc163现在选择支持文件夹上传的时候，确实可以拖拽文件夹，但是支持文件夹上传，用户无法选择上传单个文件了。所以现在想要的是支持上传的时候选择单个文件，但是拖拽支持文件 夹和文件
> > 
> > 
> > 用骚操作实现
> 
> 怎么个骚操作法？

![image](https://github.com/user-attachments/assets/8103e489-43e1-45d5-969a-c3d3a34c45d6)
