### ISSUE TITLE
table设置scroll.x = true下，设置column.width和column.ellipsis属性无效

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#29795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表格字段过多，如果不加scroll，表格列会都挤在一起。但是加了scroll，字段内容长的，又会把某一个表格列撑的很大。

### What does the proposed API look like?
在scroll.x = true的场景下，可以通过设置column.width对个别表格忽略自适应计算，配合column.ellipsis，对有过长的表格列内容部分文字省略。
如果有其他的解决方案也可以。

**Comment by zmbxy95** [comment]
例子Demo：https://codesandbox.io/s/jibenyongfa-antd4140-forked-hhhcj?file=/index.js

**Comment by lxow456** [comment]
x: max-content 且 ellipsis: true的时候 超过宽度自动省略似乎失效了
