### ISSUE TITLE
关于Cascader选中之后不反显问题

### ISSUE THREAD

**Issue by luckyGTL** [ant-design/ant-design#29790]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我有一个标签列表，点击修改，弹框中展示对应的标签所属的父级标签名。（父级标签名可以取到）
弹框中Cascader中标签名为空（选择一级和二级的时候可以正常显示，但是选择三级标签时，其对应的二级标签名可以取到，但是展示为空）

### What does the proposed API look like?
弹框中Cascader中正常展示
具体参见这个地址：https://github.com/ant-design/ant-design/issues/29789

**Comment by xrkffgg** [comment]
提供下具体代码复现吧，光图片的话，不好定位。
