### ISSUE TITLE
v-model.trim doesn't work

### ISSUE THREAD

**Issue by Huanghaiting** [ant-design/ant-design#29803]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
ant-design-vue 

### What is expected?
fix the v-model.trim bug

### What is actually happening?
在 <a-input
            v-model.trim="name"
            placeholder="请输入名称"
          >
          </a-input>前后去空格不起效

| Environment | Info |
|---|---|
| antd | undefined |
| React | vue |
| System | window |
| Browser | 版本 89.0.4389.82（正式版本） |

**Comment by yoyo837** [comment]
提错地方了吧？

**Comment by yoyo837** [comment]
移步 https://github.com/vueComponent/ant-design-vue

**Comment by Huanghaiting** [comment]
好的~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] v-model.trim doesn&#39;t work (#29803)





 
移步 https://github.com/vueComponent/ant-design-vue
