### ISSUE TITLE
Form有方法可以获取指定key的Form.Item吗？

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#2980]

**Comment by benjycui** [comment]
`ref` 不可以？然后目的是什么？

**Comment by zhulichao** [comment]
ref我试了，不知道是我的组件结构不对还是怎么的，我的Form组件上有ref属性，Form.Item上也有ref属性，可以取到this.refs.form，但是this.refs.form.refs里面没有东西。
目的主要是针对：当前页面的样式都是读取用户自定义文件生成的，比如有一个配置文件，定义了Form里有什么按钮，有什么表单项；然后用户还会在另一个文件中定义按钮的事件，考虑到多种可能，可能存在在点击一个按钮时，需要获得指定key的表单项的label和value，现在我知道获取value的方法是用form.getFieldValue()方法，我想知道有没有类似可以获取表单项lebel及其他信息的方法。

**Comment by benjycui** [comment]
直接用 `getFieldValue`，然后 `ref` 是 owner 引用 ownee。
