### ISSUE TITLE
Context parameter issue in pnp-PropertyFieldFilePicker

### ISSUE THREAD

**Issue by AditiGoyal81091** [ant-design/ant-design#29813]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
import * as React from 'react';
import * as ReactDom from 'react-dom';
import { Version } from '@microsoft/sp-core-library';
import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField,
  PropertyPaneDropdown,
  PropertyPaneButton,
  IPropertyPaneDropdownOption,
  PropertyPaneButtonType
} from '@microsoft/sp-property-pane';
import { BaseClientSideWebPart, WebPartContext } from '@microsoft/sp-webpart-base';
import { IEventRegistrationProps } from './components/IEventRegistrationProps';
import { PropertyFieldFilePicker, IPropertyFieldFilePickerProps, IFilePickerResult } from "@pnp/spfx-property-controls/lib/PropertyFieldFilePicker";

export interface IEventRegistrationWebPartProps {
  context: WebPartContext;
  filePickerResult: IFilePickerResult;
  filePickerProps:IPropertyFieldFilePickerProps;
}

export default class EventRegistrationWebPart extends BaseClientSideWebPart <IEventRegistrationWebPartProps> { 

  public render(): void {
    const element: React.ReactElement<IEventRegistrationProps> = React.createElement(
      EventRegistration,
      {
        context: this.context
      }
    );
protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
  //  let filepickercontext = this.properties.filePickerProps.context;
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [  
                PropertyFieldFilePicker('filePicker', {
                  context: this.properties.context,
                  filePickerResult: this.properties.filePickerResult,
                  onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
                  properties: this.properties,
                  onSave: (e: IFilePickerResult) => { console.log(e); this.properties.filePickerResult = e;  },
                  onChanged: (e: IFilePickerResult) => { console.log(e); this.properties.filePickerResult = e; },
                  key: "filePickerId",
                  buttonLabel: "File Picker",
                  label: "File Picker",                  
              })
                
              ]
            }
          ]
        }
      ]
    };
  }
}

### What is expected?
No errors

### What is actually happening?
Type 'import("E:/C3GIT/EventRegistration/node_modules/@microsoft/sp-webpart-base/dist/index-internal").WebPartContext' is not assignable to type 'import("E:/C3GIT/EventRegistration/node_modules/@pnp/spfx-property-controls/node_modules/@microsoft/sp-webpart-base/dist/index-internal").WebPartContext'.
  Types have separate declarations of a private property '_domElement'.ts(2322)
IPropertyFieldFilePicker.d.ts(106, 5): The expected type comes from property 'context' which is declared here on type 'IPropertyFieldFilePickerProps'

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.5 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
It is not a problem of antd.
