### ISSUE TITLE
form组件的setFieldsVaule，设置給switch组件的值true, 但展示的还是false

### ISSUE THREAD

**Issue by jianhuifan** [ant-design/ant-design#2981]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by benjycui** [comment]
Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by benjycui** [comment]
http://ant.design/components/form/#this.props.form.getFieldProps(id,-options)
