### ISSUE TITLE
当修改antd主题中的@font-size-base改大（使用中为20px），transfer的操作按钮上的>和<符号未居中显示

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#29826]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
项目实际使用过程中，通过antd提供的主题修改，将font-size-base大小置为20px，transfer的数据穿梭按钮中的>和<符合无法居中显示，影响排版显示。
![image](https://user-images.githubusercontent.com/50108232/111754572-1c58f100-88d3-11eb-98cc-710a3a555529.png)

### What does the proposed API look like?
可以提供自定义操作按钮的API或者是组件内部可自行解决自定义font-size-base后带来的央视问题

**Comment by zmbxy95** [comment]
Button按钮组件也有类似的问题，在small下，样式异常。目前通过指定@btn-font-size-sm解决

**Comment by afc163** [comment]
来个 PR

**Comment by jacklee814** [comment]
> 来个 PR

目前在 Operation 裡面的 Button 都是用 sm 的 size，所以不管怎樣 font-size 在超過一定大小後還是會有破版的問題

我可以幫忙，但想要先確認方向

@afc163 這邊有想法嗎？

**Comment by SyMind** [comment]
![image](https://user-images.githubusercontent.com/19852293/112250728-ddd98280-8c94-11eb-972f-c11883eb1632.png)
![image](https://user-images.githubusercontent.com/19852293/112250755-edf16200-8c94-11eb-9e23-b4b087cca05b.png)
貌似并不相同，如上所示。

**Comment by afc163** [comment]
<img width="433" alt="图片" src="https://user-images.githubusercontent.com/507615/130600116-ec5b255a-7822-450b-ae01-5a95d359645e.png">

本地测试了一下，最新版本 4.16.13 应该已经不存在这个问题。
