### ISSUE TITLE
The tooltip appears in the table even with the showSorterTooltip set to false.

### ISSUE THREAD

**Issue by JosueFunez** [ant-design/ant-design#29833]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-29ki3?fontsize=14&hidenavigation=1&theme=dark&file=/index.js)

### Steps to reproduce
Just set the mouse over the sort section in the header of the table

### What is expected?
The tooltip should not appear, because I set the showSorterTooltip to false.

### What is actually happening?
The tooltip appear.

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome 89 |

---
I tried to change the tooltip that appears but since I couldn't, I wanted to hide it and I couldn't either.

**Comment by afc163** [comment]
```diff
- showSorterToolTip
+ showSorterTooltip
```
