### ISSUE TITLE
After Deployment Tree structure component Showing "---"

### ISSUE THREAD

**Issue by mohitborse** [ant-design/ant-design#29834]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://4j5rn3--run.stackblitz.io](https://4j5rn3--run.stackblitz.io)

### Steps to reproduce
 Tree Component with titleRender  Customize tree node title render

I am passing treeData = [{contract:"Contract 1", key:"contract1"},{contract:"Contract 2", key:"contract2"}]
and using 
 titleRender={item => {
                                            return (
                                                <div title={item.contract}>
                                                    <span>
                                                        {item.contract}
                                                    </span>{' '}
                                                    <span className="spend">
                                                        200
                                                    </span>
                                                </div>
                                            );
                                        }}

### What is expected?
I am expected like I want to see contract name in the title section 
Ex    Contract 1
        Contract 2

### What is actually happening?
The tree is rendering but I just seeing "---"

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | React |
| System | windows 10 |
| Browser | Chrome |

**Comment by mohitborse** [comment]
Hi Team 
I am using Antd 4.0.3 version. Using that version I used the Tree React component with titleRender.
so after deploying my projects node title is visible as "---" only.

**Comment by mohitborse** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ww1bo

**Comment by afc163** [comment]
titleRender is added in antd 4.5.0, please upgrade to latest version: https://codesandbox.io/s/antd-reproduction-template-forked-zio9d?file=/index.js
