### ISSUE TITLE
form加上onFieldsChange后工作不正常

### ISSUE THREAD

**Issue by sgdba** [ant-design/ant-design#2983]
ant design1.11.0, 项目采用ant+redux.
一个普通的新建对象的表单, 要求输入一些内容后点击保存按钮进行保存. 在未加入onFieldsChange的情况下表单一切正常：点保存按钮的时候如果验证没通过就在组件的下方显示出错误提示信息。
后来给表单加上了onFieldsChange, 在这个函数中更新redux中的内容，奇怪的是别的功能一切正常，可是本来应该显示在组件下方的验证提示信息显示不出来了。如果把onFieldsChange中更新redux的代码去掉就一切正常，是不是用法有问题？下面是我的onFieldsChange代码，很简单，就是更新redux

`function onFieldsChange( props, fields ) {
  const keys = Object.keys(fields)
  let name
  keys.forEach(e => {
    let o = fields[e]
    if(o.name == 'abc') {
       name = o.value
    }
    
  })
  props.actions.setCommonObject(name)
}
`

其实这就是保留用户输入的内容,因为这个页面有个跳转（不是真的跳转，只是redux-router跳转）, 跳转回来后用户希望刚才输入的内容还能保留, 那么验证的状态能否保留下来呢?如果能保留的话应该怎么做(我的理解是也要在redux中记录一下，可是要记录什么不太了解)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
没 demo，只能靠猜。

http://react-component.github.io/form/examples/redux.html

**Comment by andy380743909** [comment]
onFieldsChange 保存form的状态时，必须把校验状态也存起来。只存field的value的话，一旦刷新页面，form重新渲染时，只能拿到value的话，校验信息就都丢失了。
