### ISSUE TITLE
Table 可编辑状态，单元格里的<Input />每输入一个字符就会失去焦点

### ISSUE THREAD

**Issue by dumbbell0720** [ant-design/ant-design#29830]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaodanfangfadiaoyongclass-component-antd4140-forked-mhvv7?file=/index.js)

### Steps to reproduce
点击编辑单元格，每输入一个字符，输入框都会失去焦点

### What is expected?
期望不会失焦可以一直输入

### What is actually happening?
input失去焦点

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | ^17.0.1 |
| System | mac |
| Browser | chrome |

---
业务场景：需要监听表格是否变化

**Comment by afc163** [comment]
https://codesandbox.io/s/-antd4140tablekebianji-forked-trqvm?file=/index.js

EditableCell 组件不应该每次 render 时重新定义。
