### ISSUE TITLE
Select组件带移除图标的无法清空内容

### ISSUE THREAD

**Issue by a982564562** [ant-design/ant-design#29843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daipaixudesousuo-antd4140-forked-bkjrg)

### Steps to reproduce
在输入框中输入若干字符，然后调用document.querySelector(".ant-select-clear").click()清空内容

### What is expected?
调用document.querySelector(".ant-select-clear").click() 能清空内容

### What is actually happening?
调用document.querySelector(".ant-select-clear").click() 无法清空内容

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.14.0 |
| System | window10 |
| Browser | chrome |

**Comment by xrkffgg** [comment]
https://github.com/react-component/select/blob/45856a82538f3baba9f49209dbf8cf1008a6d8a5/src/generate.tsx#L986

**Comment by a982564562** [comment]
> https://github.com/react-component/select/blob/45856a82538f3baba9f49209dbf8cf1008a6d8a5/src/generate.tsx#L986

不行啊，用js触发不了

**Comment by afc163** [comment]
React 应用中不应该操作 dom，请使用受控模式控制 value 属性。
