### ISSUE TITLE
Tooltip will close on mouse enter to datalist

### ISSUE THREAD

**Issue by zWingz** [ant-design/ant-design#29854]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4140-forked-8s4sj?file=/index.js:618-650)

### Steps to reproduce
open tooltip and click the input, mouse on datalist
![image](https://user-images.githubusercontent.com/13031838/111954586-4c96ce80-8b23-11eb-9a82-910f27f30411.png)

### What is expected?
no close the tooltip

### What is actually happening?
tooltip will close

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | latest |
| System | macOS |
| Browser | Chrome |

**Comment by kiinlam** [comment]
这都不是focus的问题，是你没有主动控制弹出层的显示跟隐藏。

把datalist去掉，再试试，离开tooltip范围，一样消失，不管你有没有focus到input。

此issue可以关了

**Comment by afc163** [comment]
原生的 datalist 提示元素不是真实的 dom，hover 上去也是离开了 tooltip 浮层，目前没有简单的好办法。

**Comment by zWingz** [comment]
@afc163 了解, 希望会有解决办法, 目前只能主动关闭autocomplete
