### ISSUE TITLE
upload accept 设置为*/* 或者 * 失效

### ISSUE THREAD

**Issue by LeoHuiyi** [ant-design/ant-design#29852]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dianjishangchuan-antd4140-forked-5edlt?file=/index.js)

### Steps to reproduce
点击上传

### What is expected?
可以上传

### What is actually happening?
不能上传

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 17.0.1 |
| System | win10 |
| Browser | chrome89 |

---
之前版本可以上传的

**Comment by afc163** [comment]
哪个版本可以上传？

**Comment by LeoHuiyi** [comment]
4.13.0可以上传,

**Comment by afc163** [comment]
确实 4.13.0 可以: https://codesandbox.io/s/dianjishangchuan-antd4130-forked-bi4n8

**Comment by lihqi** [comment]
[302](https://github.com/react-component/upload/pull/302)
修复bug改没的，单独处理下 '*' ?

**Comment by xrkffgg** [comment]
cc @kerm1it

**Comment by kerm1it** [comment]
我来处理

**Comment by kerm1it** [comment]
这是一直存在的 bug

https://codesandbox.io/s/tuozhuaishangchuan-antd4141-forked-km9c7 4.13.0 使用拖拽也不好使

之前之所以好使，因为 onChange 没有使用 accept 过滤，只是将 accept 的值传给了 input，让系统的文件选择器让其值生效。
