### ISSUE TITLE
themes/default.less 没有完整的写入官网文档中的阴影规范

### ISSUE THREAD

**Issue by LinkPlanet** [ant-design/ant-design#29851]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望默认样式，完全对照antdesign的官网，因为这里的阴影只有shadow-1-xx的标准，而官网有shadow-2和shadow-3的标准。如果不写上的话对新手不友好，我自己一开始还以为引入的方式错误。

### What does the proposed API look like?
加入官方文档中声明的规范阴影变量。

**Comment by afc163** [comment]
5.0 的文档已经包括了阴影。
