### ISSUE TITLE
Failed to execute 'observe' on 'ResizeObserver' when SELECT component is clicked

### ISSUE THREAD

**Issue by suser2000** [ant-design/ant-design#29866]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce
When the Select component is clicked

### What is expected?
Normal run of component

### What is actually happening?
Gives an error in console. Application stops. Error is : " Failed to execute 'observe' on 'ResizeObserver'. Parameter 1 is not of type 'Element' ". (We tried a lot but unfortunately we could not reproduce the error in internet environment. )

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | chrome 79.0.3945.117 |

---
The problem appeared after Ant Design library upgrade.

**Comment by diedu89** [comment]
Here's a reproduction of a similar issue with RangePicker https://codesandbox.io/s/antd-reproduction-template-forked-z1wq4?file=/index.test.js
