### ISSUE TITLE
Weird behavior of <Space wrap> when size of the children have a specific configuration.

### ISSUE THREAD

**Issue by itsfarseen** [ant-design/ant-design#29868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-b4qkm)

### Steps to reproduce
Make `(2*child-width + space/2) < Spacer width < (2*child-width + space)`

### What is expected?
Space changes from two columns mode to one column mode when two columns don't fit.

### What is actually happening?
Space changes to L shape for a brief while, then after a while changes to one column mode.

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | Linux 5.11.8 |
| Browser | Firefox 86.0.1 |

**Comment by zombieJ** [comment]
Last Space child node do not have margin right which makes it to be `L`. Seems can be use flex gap instead. Need additional research since Row of changing cause many issue on horizontal gap.

cc @afc163
