### ISSUE TITLE
能否给进度条组件Progress提供颜色API

### ISSUE THREAD

**Issue by liuhongyi** [ant-design/ant-design#2986]
#### 本地环境

- antd 版本: 1.10.0
- 操作系统及其版本：MAC 10.11.4
- 浏览器及其版本: :Google Chrome 50.0.2661.49 beta (64-bit)

#### 你做了什么？

引入了 antd 的 Progress

#### 你期待的结果是：

能否对Progress组件提供一些颜色的api，发现颜色是写在javascript里面的，无法改到颜色，有点纠结

**Comment by afc163** [comment]
https://github.com/react-component/progress#props
