### ISSUE TITLE
[Bug]select组件当清除选中项时，不会触发request，并且当label为tag时无法进行搜索

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design#29873]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce

```
        showSearch
        options={tagsRes?.data?.list?.map((item) => ({
          label: <Tag color={item.color}>{item.name}</Tag>,
          value: item.id || 0,
        }))}
        fieldProps={{ filterOption: false }}
        onSearch={()=>getTags()}
```

### What is expected?
两个问题。
第一个，当select组件清除选中项时，不会触发request，也就是如果是远程请求配置的话，除非用户重新输入，否则没有内容

第二个，当options label为reactnode时，使用showsearch，尝试在options添加text，配置optionFilterProp:"text"也无效，renderTag又无法从options获取颜色。。。

### What is actually happening?
select清除选中项，触发request，renderTag支持从options项获取值

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17.0.0 |
| System | win |
| Browser | chrome |

**Comment by daoying007** [comment]
加微信群交流互助吧，加我微信好友（备注antd），拉你进ant-design微信群

更多各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

![ant-design微信群](https://user-images.githubusercontent.com/39725475/112411174-720c1e00-8d57-11eb-96f0-050bf531fc1b.jpg)
