### ISSUE TITLE
当把Input放到select下拉面板时，select为multiple时删除Input的文字同样也会删除Select的选择项

### ISSUE THREAD

**Issue by paddingC** [ant-design/ant-design#29881]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当把Input放到select下拉面板

### What does the proposed API look like?
删除Input的文字不影响Select的选择项

**Comment by afc163** [comment]
阻止事件冒泡。
