### ISSUE TITLE
Input 服务端渲染问题

### ISSUE THREAD

**Issue by forthedamn** [ant-design/ant-design#2988]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：OS X 10.10.5 
- 浏览器及其版本: chrome 52.0.2743.116

#### 你做了什么？

```
  render() {
    // domain先用一个固定值
    const domain = 'test';
    return (
      <div>
        <InputGroup className="add-domain-group">
          <Input value={domain} onChange={this.changeHandler} className="domain-input" />
        </InputGroup>
      </div>
    );
  }

```
#### 你期待的结果是：

正常渲染

#### 实际上的结果：

控制台报warning，服务端渲染和客户端渲染不一致

![Uploading DingTalk20160909201046.png…](https://zos.alipayobjects.com/rmsportal/OGDaSCjXamNctuF.png)

当不使用 *Input* 的 *value* 属性时，warning就没了，客户端和服务端渲染一致

**Comment by benjycui** [comment]
试下把 `value` 去掉，再加上 `onBlur`，应该也会报错。

**Comment by forthedamn** [comment]
额，如下方式试了下onBlur 木有出现类似情况

但是加value属性确实会出现warning


```
       // 无warning
        <InputGroup className="test">
          <Input onChange={handler} onBlur={handler} className="test"/>
        </InputGroup>

       // 有warning
        <InputGroup className="test">
          <Input onChange={handler} value="test" className="test"/>
        </InputGroup>
```

**Comment by benjycui** [comment]
`object-omit` & `object.omit` 无法保证 SSR 与浏览器渲染的结果一致。

考虑到 `antd` 和 `antd-mobile` 都需要这个方法，所以单独写个模块来替换上面两个模块吧。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/pull/2994

先忽略，等 antd@2.0

**Comment by forthedamn** [comment]
antd@2.0 会修复这个哇？可不可以给个大概的时间点呢

**Comment by benjycui** [comment]
今天再发个 beta，稳定版再等一两周。

注意 2.0 有不兼容升级。
