### ISSUE TITLE
table分页之后如何能够获取全表数据？

### ISSUE THREAD

**Issue by francisZC** [ant-design/ant-design#29880]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
把table分页之后，用jquery获取table的数据，只能获取当前分页的数据，如何获取全部表格的数据呢？

### What is expected?
获取全部表格的数据

### What is actually happening?
只能获取当前分页的数据

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome Version 88.0.4324.182 (Official Build) (64-bit) |

**Comment by yoyo837** [comment]
建议非必要不和jQuery混用，表格可以自己控制加载数据，手动分页
