### ISSUE TITLE
The confirm button of Modal's instance method has the wrong color

### ISSUE THREAD

**Issue by wxwqslsdsh** [ant-design/ant-design#29884]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/#components-modal-demo-info](https://ant.design/components/modal-cn/#components-modal-demo-info)

### Steps to reproduce
Click any button of the page given upon, then you'll see a modal open, but the confirm button of this modal has a wrong color.(the color seems more light)

### What is expected?
the button in open modal doesn't have any automatical behavior

### What is actually happening?
the button seems has a `hover` or `focus` behavior automatically

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | react |
| System | win 10 |
| Browser | chrome89 |

**Comment by afc163** [comment]
Try `autoFocusButton={false}`

**Comment by wxwqslsdsh** [comment]
Thanks for your reply @afc163, I still have a question about the `autoFocusButton` prop,  why its default value is `ok` not `null`, since this causes a UI problem: When I open a Modal, the confirm button's color is not normally. And I think in most scenes we don't need autoFocus any button
