### ISSUE TITLE
Back Top 能否自定义click事件，或者添加缓动效果

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#2989]
* 现在 **BackTop** 的默认动作是直接设置 scrollTop = 0 能不能添加自定义缓动效果

* 想做几个跟 **BackTop** 一起出现消失的工具按钮， 现在貌似不行，不管点哪个都有回到顶部的效果，不知道以后会不会添加自定义点击事件的功能

**Comment by benjycui** [comment]
@ddcat1115 [这行](https://github.com/ant-design/ant-design/blob/master/components/back-top/index.tsx#L56) 看不懂，`div` 的 onClick 有什么默认行为需要阻止？

**Comment by jljsj33** [comment]
早就提了做下滑动，，不鸟我。。别人来提了吧。。。。。

**Comment by ddcat1115** [comment]
@benjycui 确实没用，后面删掉

@xutou12 onClick事件现在就支持的呀

**Comment by afc163** [comment]
@jljsj33 你也是开发者，you can you u

**Comment by jljsj33** [comment]
我不是设计师嘛。。。哈哈。。。我会发ＰＲ的。。。

**Comment by xutou12** [comment]
@ddcat1115 我的意思是取消默认的click动作，换上我的自己的click动作

**Comment by benjycui** [comment]
> 想做几个跟 BackTop 一起出现消失的工具按钮， 现在貌似不行，不管点哪个都有回到顶部的效果，不知道以后会不会添加自定义点击事件的功能

其实用 BackTop 实现这个功能也很奇怪，或者我们需要的是一个 scroll 到某个位置才出现的组件，类似于 Affix。

**Comment by RaoHai** [comment]
其实只是想把几个组件跟 BackTop 的那个按钮放一块儿。。。

**Comment by xutou12** [comment]
@benjycui 恩这样思考是比较通用

@RaoHai 现在我的需求确实是这样

一开始我想法比较简单就是如果 **BackTop** 组件能够让我的替换他的默认动作，我就能完成我的需求了，如果从组件扩展性上来讲的话 @benjycui 的想法是合理的

**Comment by ddcat1115** [comment]
@benjycui 对，其实我觉得是另外的几个按钮不应该放 `BackTop` 里，需要自己实现『到一定scroll高度就展现/隐藏』，或者提供一个新组件

**Comment by benjycui** [comment]
@ddcat1115 @jljsj33 缓动效果需要加。

但下面这个场景暂时不做支持吧，至少我没见过这种用法，自行实现也不难。

> 想做几个跟 BackTop 一起出现消失的工具按钮
