### ISSUE TITLE
The column names of a Table cannot get the Display attribute of its model. The name of the variable is used instead. This feature works with forms, but not tables, as far as i can see.

### ISSUE THREAD

**Issue by Garfieldgzhh** [ant-design/ant-design#29899]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In a Table, each column will have a name as specified by the Display attribute. Currently the table columns uses the name of variable and ignores the display attribute.

### What does the proposed API look like?
In a Table, when I set 

[Display(Name="ColumnName")] 
public string column1; 

the column in the table should be named as "ColumnName" instead of "column1". I think this feature is probably easy to achieve by setting the displaying string of a Column to the string that's given by the display attribute.

**Comment by zombieJ** [comment]
Hi @Garfieldgzhh,
Do you mean the component of Ant Design Blazor?

**Comment by afc163** [comment]
https://github.com/ant-design-blazor/ant-design-blazor/issues

**Comment by Garfieldgzhh** [comment]
My apologies! It's meant for Ant Design Blazor.
