### ISSUE TITLE
Table组件rowSelection配置报错 TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design#29904]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/youmyin/pen/NWdGMzP?editors=0110](https://codepen.io/youmyin/pen/NWdGMzP?editors=0110)

### Steps to reproduce
当点击左侧穿梭框的全选按钮时，就会报错TypeError: Object(...) is not a function。

### What is expected?
能够正常全选

### What is actually happening?
不能正常全选

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 16.8.6 |
| System | Windows10 |
| Browser | chrome |

**Comment by Youmyin** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-4qrpc?file=/index.tsx

**Comment by afc163** [comment]
你给的 codesandbox 跑不起来。

**Comment by Youmyin** [comment]
啊，抱歉，这个codesandbox不怎么会配置。但是主要就是demo.tsx这个文件，这个文件就是官方文档中表格穿梭框的例子，不过我把jsx改成了tsx，基本就是加了一些类型定义，主要逻辑没有改，但是改完就出现了这个问题了

```
                    const diffKeys = selected
                        ? difference(treeSelectedKeys)
                        : difference(listSelectedKeys);
```
上面就是报错的那部分代码，原本difference这个函数只有一个参数，官网例子中却传了两个参数。并且onItemSelectAll的第一个参数是string[]类型的，但是传入的diffKeys确是number类型，并没有作转换，下面这部分代码就是官网的例子片段：
```
      const rowSelection = {
        getCheckboxProps: item => ({ disabled: listDisabled || item.disabled }),
        onSelectAll(selected, selectedRows) {
          const treeSelectedKeys = selectedRows
            .filter(item => !item.disabled)
            .map(({ key }) => key);
          const diffKeys = selected
            ? difference(treeSelectedKeys, listSelectedKeys)
            : difference(listSelectedKeys, treeSelectedKeys);
          onItemSelectAll(diffKeys, selected);
        },
        onSelect({ key }, selected) {
          onItemSelect(key, selected);
        },
        selectedRowKeys: listSelectedKeys,
      };
```

其他没有啥问题就是全选的列表的时候就报错TypeError: Object(...) is not a function。还有就是Transfer的listStyled单独设置左右两个框的宽度无效。

所以请问可以帮忙看看demo.tsx中到底哪里出了问题吗？

（PS：如果可以的话请问能提供表格穿梭框的typescript版本嘛？）
