### ISSUE TITLE
Set a min-height to table

### ISSUE THREAD

**Issue by blephy** [ant-design/ant-design#29909]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a lot of table with nzLoading properties and : 
- When no data is set / found, i would be able to set a min-height to print "no-data" state, and table height = min-height
- When new data is loading and no data was set, the loader is on the table header.

How can i fix the header please ? I try so many things.

### What does the proposed API look like?
maybe a new style property nzMinHeight ?

**Comment by afc163** [comment]
Wrong repository, check https://github.com/NG-ZORRO/ng-zorro-antd/issues
