### ISSUE TITLE
表格穿梭框TableTransfer分别设置左右区域样式listStyle不生效

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design#29903]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/youmyin/pen/NWdGMzP?editors=0110](https://codepen.io/youmyin/pen/NWdGMzP?editors=0110)

### Steps to reproduce
根据官方文档提供的方法对listStyle进行配置，但是并没有效果

### What is expected?
左右两个穿梭框大小不一样，坐标列表字段多宽度大，右边列表字段少宽度小

### What is actually happening?
listStyle的设置并没有起作用，左右两边任然一样宽

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 16.8.6 |
| System | Windows10 |
| Browser | chrome |

---
是我写的方式有什么问题吗？listStyle={({direction:left}) => ({width:'500px'})}

**Comment by afc163** [comment]
https://codesandbox.io/s/danxiangyangshi-antd4141-forked-hf6g9?file=/index.js
