### ISSUE TITLE
datepicker with showTime has wrong millisecond timestamp when convert by Date().valueOf()

### ISSUE THREAD

**Issue by SmoothJM** [ant-design/ant-design#29902]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sh9bo?file=/index.js)

### Steps to reproduce
Selected the range like from March 02 00:00:00 to March 03 00:00:00

### What is expected?
Two millisecond timestamps: 1614614400000, 1614700800000 means two day I select.

### What is actually happening?
Two millisecond timestamps with more millisenond: 1614614400862,1614700800862 (maybe the extra value is different)

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | win 10 |
| Browser | chrome 89 |

---
I would like to know why date has extra millisecond value?

**Comment by afc163** [comment]
```diff
- console.log(date[0].valueOf());
- console.log(date[1].valueOf());
+ console.log(date[0].startOf("second").valueOf());
+ console.log(date[1].startOf("second").valueOf());
```

**Comment by SmoothJM** [comment]
> ```diff
> - console.log(date[0].valueOf());
> - console.log(date[1].valueOf());
> + console.log(date[0].startOf("second").valueOf());
> + console.log(date[1].startOf("second").valueOf());
> ```

Could you please tell me why there are some extra millisecond values on date?

**Comment by afc163** [comment]
selected date is based on `Date.now()`.

**Comment by luckymore** [comment]
@afc163 Hi, afc. I know the picker's value is based on 
```js
var m = moment()
// when use select date 12
m.date(12)

``
when user choose `2022-06-13 00:00:00`, it's not actually `1655049600000`, but `1655049600000`
