### ISSUE TITLE
Dayjs DatePicker doesn't respect Day.js locale from Config Provider (nextjs)

### ISSUE THREAD

**Issue by chemicalkosek** [ant-design/ant-design#29907]
- [ v] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Related but doesn't work for me: https://github.com/ant-design/ant-design/issues/27815

### Reproduction link
[https://github.com/chemicalkosek/antd-dayjs-next](https://github.com/chemicalkosek/antd-dayjs-next)

### Steps to reproduce
1. Clone repository 
2. Launch with npm run dev
3. See that the Datepicker with inline locale setup works. The other one doesn't respect the ConfigProvider (or actually the days locale)
4. If without stopping the dev server I change `lib` to `es` in the line:
```
import generatePicker from "antd/lib/date-picker/generatePicker";
```
to:
```
import generatePicker from "antd/es/date-picker/generatePicker";
```
I can see now with hot refresh that it works! 
All the week names etc are in `pl` locale.
But If I refresh the page or stop the dev server and run again `npm run dev` (or build to production), I'l get the following error:
```
/home/maciek/Dokumenty/websites/antd-dayjs-next/node_modules/antd/es/date-picker/generatePicker/index.js:1
import _extends from "@babel/runtime/helpers/esm/extends";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///antd/es/date-picker/generatePicker:1:18)
    at Object.antd/es/date-picker/generatePicker (/home/maciek/Dokumenty/websites/antd-dayjs-next/.next/server/pages/index.js:149:1)
    at __webpack_require__ (/home/maciek/Dokumenty/websites/antd-dayjs-next/.next/server/pages/index.js:23:31)
    at eval (webpack-internal:///./components/DayjsDatePicker.js:4:92)
    at Module../components/DayjsDatePicker.js (/home/maciek/Dokumenty/websites/antd-dayjs-next/.next/server/pages/index.js:104:1)
    at __webpack_require__ (/home/maciek/Dokumenty/websites/antd-dayjs-next/.next/server/pages/index.js:23:31)
    at eval (webpack-internal:///./pages/index.js:9:85)
    at Module../pages/index.js (/home/maciek/Dokumenty/websites/antd-dayjs-next/.next/server/pages/index.js:127:1)
    at __webpack_require__ (/home/maciek/Dokumenty/websites/antd-dayjs-next/.next/server/pages/index.js:23:31)
```

### What is expected?
The dayjs locale works in dayjs Date Picker

### What is actually happening?
The default english dayjs locale is seen

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Chrome 89 |

**Comment by afc163** [comment]
Similar issues which may help

- https://github.com/ant-design/ant-design/issues/29595
- https://github.com/ant-design/ant-design/issues/29306
- https://github.com/ant-design/ant-design/issues/21094
- https://github.com/ant-design/ant-design/issues/26985
- https://github.com/ant-design/ant-design/issues/23365
- https://github.com/ant-design/ant-design/issues/22802
- https://github.com/ant-design/ant-design/issues/29595

**Comment by chemicalkosek** [comment]
Thanks. I'm aware of those issues, I have spent days (weeks :)) trying to get antd and nextjs working with treeshaking.
I think I've read all the issues at antd and nexjts github :)
The thing is I can get js treeshaking working (and dayjs locale working globally on pickers) with babel-plugin-import.
But then it generates `conflicting order between chunks` from `mini-css-extract-plugin`, which sometimes breaks dev styles.
While that is may not be a big issue it also generates 30kb (603kb -> 633kb) more first load on the app.
```
Page                                                                     Size     First Load JS
┌ λ /                                                                    56 kB           631 kB
```


As I have recently noticed you no longer recommend the `babel-plugin-import`, I have tested the project without it and everything looks great! 
The first load JS is now 603kb and there are no `conflicting-order` issues! 
It is the leanest build ever and I don't mind loading the whole less file. 

```
Page                                                           Size     First Load JS
┌ λ /                                                          712 B           603 kB
```

There's this one 'but` here. The issue I'm raising here is the only thing that doesn't work. 
Either the dayjs locale doesn't work on antd picker with `antd/lib/`  `generatePicker` import or it doesn't build with `antd/es` import  while creating the error: 
```
import _extends from "@babel/runtime/helpers/esm/extends";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Since everything runs smoothly apart of this dayjs picker, my question is if there's actually an issue with how the dayjs picker is imported and/or generated and if anything can be done with it? I would really like to ditch the `babel-plugin-import` as it's looking great now!

**Comment by GVanderLugt** [comment]
Any updates here?

**Comment by nbusuttil** [comment]
Up

**Comment by nbusuttil** [comment]
You can add support of daysJs and antd with nextjs Please ?

**Comment by vandercloak** [comment]
https://github.com/ant-design/ant-design/issues/23365#issuecomment-616062180 This comment here helped me get passed it

**Comment by mavcom12** [comment]
seems like this isn't just a problem with `generatePicker` I'm also experiencing this for `Button`. also looked at other solutions for it might the only thing I think of is that nextJS doesn't automatically support less.. but I could be wrong..

**Comment by ds1371dani** [comment]
I also had this problem in nextjs. the main problem was that i was importing `generatePicker` from `lib` but all other components including `ConfigProvider` were being imported from `es`, so all the config was being set in `es`
The solution was to import all components from `"antd/lib"` instead of `"antd"`.

**Comment by ds1371dani** [comment]
> Similar issues which may help
> 
>     * [Importing `generatePicker` from `lib` does not respect locale #29595](https://github.com/ant-design/ant-design/issues/29595)
> 
>     * [SyntaxError: Cannot use import statement outside a module #29306](https://github.com/ant-design/ant-design/issues/29306)
> 
>     * [Uncaught SyntaxError: Cannot use import statement outside a module #21094](https://github.com/ant-design/ant-design/issues/21094)
> 
>     * [Cannot test component wrapped with ConfigProvider #26985](https://github.com/ant-design/ant-design/issues/26985)
> 
>     * [using generatePicker, the test fails #23365](https://github.com/ant-design/ant-design/issues/23365)
> 
>     * [Followed steps of "Use modularized antd" and got an error #22802](https://github.com/ant-design/ant-design/issues/22802)
> 
>     * [Importing `generatePicker` from `lib` does not respect locale #29595](https://github.com/ant-design/ant-design/issues/29595)

I think this solution can help in some of these issues too

**Comment by 0fan** [comment]
+1 2022-11-06 19:20:49

**Comment by quyctd** [comment]
For some who still encounter this problem, you can try to fix it by updating the import statement like this. Hope this help

```diff
- import { ConfigProvider } from 'antd'
+ import ConfigProvider from 'antd/lib/config-provider'
```

**Comment by Jay-flow** [comment]
Any update?

**Comment by kjarekinovirtue** [comment]
any update ?

**Comment by kjarekinovirtue** [comment]
any update ? it's quite important to our project to have possibility to manipulate locale

**Comment by chemicalkosek** [comment]
I don't know what issues you guys still have. It was an issue in antd@4, but works perfectly in antd@5.
I'm gonna close this soon.

**Comment by yoyo837** [comment]
> Reproduction link
> https://github.com/chemicalkosek/antd-dayjs-next

Your ConfigProvider is exported from antd/es But your Dayjs DatePicker is imported from antd/lib, so the picker will consume antd/lib/ConfigProvider, which is another provider at runtime. I think.

**Comment by yoyo837** [comment]
If you still have issues about this, feel free to open a new issue with reproduction link.
