### ISSUE TITLE
not warking Popover component trigger="focus" in Firefox

### ISSUE THREAD

**Issue by takashimamorino** [ant-design/ant-design#29917]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-tdd-5uh2r?file=/src/index.js)

### Steps to reproduce
https://codesandbox.io/s/stupefied-tdd-5uh2r?file=/src/index.js

### What is expected?
display "content" when click Focus me

### What is actually happening?
no display "content"

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.0.1 |
| System | mac |
| Browser | Firefox |

**Comment by afc163** [comment]
`<span>Focus me</span>` is not a focusable element.

https://stackoverflow.com/a/1600194/3040605

**Comment by takashimamorino** [comment]
@afc163
Thank you for your comments.
But, this problem will also occur if you change to Button
