### ISSUE TITLE
Icon component not exported from antd

### ISSUE THREAD

**Issue by Ahmiii** [ant-design/ant-design#29919]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js:360-366)

### Steps to reproduce
import {Button,Icon} from 'ant'
const App=()=>{
         return(
                     <Button>
                             <Icon type='upload'
                     </Button>
}

### What is expected?
import {Icon} from 'ant'

### What is actually happening?
Attempted import error: 'Icon' is not exported from 'antd'.

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17.0.2 |
| System | Linux |
| Browser | Chrome: Version 80.0.3987.116 |

---
component is not being exported.

**Comment by afc163** [comment]
https://ant.design/docs/react/migration-v4#Icon-upgrade
