### ISSUE TITLE
数据层次较深时，Cascader组件不能回显value对应的label

### ISSUE THREAD

**Issue by ITyaoji** [ant-design/ant-design#29913]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4141-forked-8jsmg?file=/index.js)

### Steps to reproduce
1、点击“更换按钮”
2、显示的是7

### What is expected?
显示7a

### What is actually happening?
7

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17 |
| System | win10 professional |
| Browser | chrom latest |

**Comment by xrkffgg** [comment]
首先 value 是个数组，包含其父的 value。如果你要选择 7，正确的数组是 [1 ,4, 6, 7]

然后可以通过 `displayRender` 自定义显示内容，只显示 7 的 label

**Comment by ITyaoji** [comment]
**第一：什么鬼，组件当中已经将数据扁平化了，为社么不在组件当中处理呢？非要交给开发者去处理，且文档当中并未注明。
![image](https://user-images.githubusercontent.com/24262180/112618930-a9ff8800-8e61-11eb-96ba-49ae750632bb.png)
扁平化之后完全可以用map去快速索引，将多余的操作交给使用者是偷懒的行为
第二： 如果层级为第二层，为什么可以回显出value对应的label？**
**so！this is a bug**

**Comment by afc163** [comment]
value 是一个数组，Cascader 的设计允许不同层级的 value 重复，单靠叶节点的 value 没办法确定选中项的路径。
