### ISSUE TITLE
弹出层新建表单重新设置值不起作用？

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#29925]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/danchucengzhongdexinjianbiaodan-antd4141-forked-f8y7k?file=/index.js)

### Steps to reproduce
1，点击按钮1，弹出层input 值是 test 1
2,  点击按钮2，弹出层form 表单中的input 值 还是test2

### What is expected?
弹出层的form表单值变化

### What is actually happening?
弹出层的form表单值不变化

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 17.0.1 |
| System | mac os |
| Browser | chrome 最新版本 |

**Comment by zombieJ** [comment]
`resetFields` 重置表单，和弹窗展示与否没有关系。
