### ISSUE TITLE
表格 expandable 列可以像其它列一样配置 fixed: 'left' 固定在表格左边吗

### ISSUE THREAD

**Issue by dpyzo0o** [ant-design/ant-design#29924]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表格列过多时向右滑动就看不到展开行的按钮了

### What does the proposed API look like?
可进行列属性配置

**Comment by dpyzo0o** [comment]
不是bug呀, 是 feature request

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/kezhankai-antd4150-forked-c5tpf?file=/index.js

现在满足的呀

**Comment by xrkffgg** [comment]
先关了，有问题再说。

**Comment by dpyzo0o** [comment]
@xrkffgg 这个实际上是跟随第一列固定了，我的意思是，可以单独固定 expand icon 那一列吗。api 类似于在 expandable 属性里面传一个 fixed: 'left' 这样。

**Comment by dpyzo0o** [comment]
因为 expand icon本身其实是一个单独的列, 不应该和第一列强绑定在一起
