### ISSUE TITLE
DatePicker freezes whole browser when using React concurrent mode

### ISSUE THREAD

**Issue by flashspys** [ant-design/ant-design#29926]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/datepickerbug-9qbvs)

### Steps to reproduce
Just try to click into the DatePicker field / open the calendar

### What is expected?
The Calendar popup should be come up.

### What is actually happening?
The browser tab is freezing completely.

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 0.0.0-experimental-a77dd13ed |
| System | MacOS |
| Browser | latest Safari/Chrome/Firefox |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27552#issuecomment-721659515
