### ISSUE TITLE
https://procomponents.ant.design/ 文档404 

### ISSUE THREAD

**Issue by bingege12138** [ant-design/ant-design#29938]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://procomponents.ant.design/](https://procomponents.ant.design/)

### Steps to reproduce
搜索https://procomponents.ant.design/ 无法看文档

### What is expected?
能够访问这个链接

### What is actually happening?
能够访问这个链接

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 16 |
| System | window 10 |
| Browser | 谷歌 版本 88.0.4324.104 |

---
404！ 无法访问

**Comment by yoyo837** [comment]
你找这个吗？ https://pro.ant.design/

**Comment by yoyo837** [comment]
你这个链接哪来的？

**Comment by bingege12138** [comment]
> 你找这个吗？ https://pro.ant.design/
https://procomponents.ant.design/ 里面封装的组件文档  这个地址是官网里给出的组件文档 ，现在404 无法查看详细的组件文档

**Comment by ZeroJsus** [comment]
+1 我这里也是访问组件文档404了

**Comment by afc163** [comment]
目测已经恢复了。
