### ISSUE TITLE
服务端渲染测试方案

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#2993]
有问题的组件：

- [x] **Mention**  https://github.com/facebook/draft-js/issues/385
- [x] **Menu**  https://github.com/react-component/menu/issues/63
- [x] **Upload** https://github.com/react-component/upload/issues/55

**Comment by RifeWang** [comment]
where is the plan?

**Comment by afc163** [comment]
https://github.com/erikras/react-redux-universal-hot-example/

**Comment by benjycui** [comment]
@afc163 不是很懂你在这个 issue 贴这个链接的意思。。。

**Comment by afc163** [comment]
这个脚手架貌似支持 ssr 。

**Comment by afc163** [comment]
https://github.com/zeit/next.js

**Comment by yesmeck** [comment]
更新了描述

**Comment by yesmeck** [comment]
Trace https://github.com/facebook/draft-js/pull/796

**Comment by afc163** [comment]
#10613
