### ISSUE TITLE
tree组件的官方codesanbox示例卡死

### ISSUE THREAD

**Issue by jueinin** [ant-design/ant-design#29937]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4141-forked-drz27?file=/index.js)

### Steps to reproduce
进入codesanbox点击示例sss文本前的checkbox，然后再点一下，即可出现卡死现象

### What is expected?
不会卡死

### What is actually happening?
页面会直接卡死

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17 |
| System | windows10 |
| Browser | chrome 89 |

---
这个我觉得应该是codesanbox的问题，codepen等就没有问题，但是目前只发现这个组件有卡死现象，有人知道原因吗？

**Comment by afc163** [comment]
感觉是 codesandbox 缓存了某个底层依赖。

**Comment by afc163** [comment]
4.15.0 依然存在，感觉不是缓存问题。

**Comment by jueinin** [comment]
中午休息我看看，看看能不能找到源头。只发现这个组件的demo有这个问题

**Comment by jameslahm** [comment]
发现真相了，好像是因为打印`info`的时候，`codesandbox`使用的`console-feed`会将`info`序列化为一个超长的`Array`(`length`为7753)，会导致卡顿，不打印`info`应该就可以了，https://codesandbox.io/s/jiben-antd4141-forked-zqkbn?file=/index.js

**Comment by jueinin** [comment]
> 好像是因为打印`info`的时候，`codesandbox`使用的`console-feed`会将`info`序列化为一个超长的`Array`(`length`为7753)，会导致卡顿，不打印`info`应该就可以了，https://codesandbox.io/s/jiben-antd4141-forked-zqkbn?file=/index.js

7000多长度应该不至于卡死吧？我看了下performance似乎走了一个死循环，一直在调用那几个同样的方法，cpu吃满了。

**Comment by jameslahm** [comment]
那个应该是序列化info造成的，

**Comment by xrkffgg** [comment]
https://github.com/codesandbox/codesandbox-client/issues/5656

**Comment by afc163** [comment]
没啥好办法，等 codesandbox 修复。
