### ISSUE TITLE
关于Table的expandable配置的疑惑

### ISSUE THREAD

**Issue by alexchen1875** [ant-design/ant-design#29939]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/es4qj?file=/index.js:1249-1266)

### Steps to reproduce
正常点击展开或关闭,`expandedRowRender `被重复调用很多次

### What is expected?
只有展开时`expandedRowRender`才被调用

### What is actually happening?
无论展开还是收起,都会调用很多次`expandedRowRender`

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | last |
| System | win10 |
| Browser | chrome  |

---
需求上要求实现如图这样的展开功能,通过自定义列事件和受控的`expandedRowKeys`属性实现了展开逻辑,
但是发现,只要点击表格,就会出现展开行重新`render`多次的情况.因为自定义的展开内容里面有新的网络请求,这就导致了很多无效的重复请求.

![image](https://user-images.githubusercontent.com/3668637/112800017-afe3ac00-90a1-11eb-82ad-06737acd5ebb.png)

或者是否有其他的思路可以避免这个问题,我在官网上的展开demo里面console了`expandedRowRender`函数,也会出现这样的问题.

**Comment by alexchen1875** [comment]
现在暂时只能通过把展开内容的请求和数据放在主表所在组件上,让展开的表格为静态数据表格.

**Comment by zombieJ** [comment]
展开列渲染后关闭列是将列内容隐藏而非销毁，即便是维持展开的情况，Table 本身是无法确定这次 render 是否受到外部 state 影响而需要改变内容。你不应该在 `render` 里调用网络请求，而是应该封装一个 组件，在组件 mount 时调用网络请求。

ref https://ant.design/components/table-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-%E6%9B%B4%E6%96%B0-state-%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%85%A8%E8%A1%A8%E6%B8%B2%E6%9F%93%EF%BC%9F
