### ISSUE TITLE
Not all initialValues are passed to onFinish

### ISSUE THREAD

**Issue by vavdav** [ant-design/ant-design#29946]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-methods-antd4141-forked-4wdnb?file=/index.js)

### Steps to reproduce
Click submit, and you can see that there are not initialValues. 
When you hit toggle it is there, but after pressing toggle again it is not there on submit event with 'preserve' flag

### What is expected?
to pass all initialValues to onFinish

### What is actually happening?
only vlaues which are rendered with Form.Item are passed

### Comments
I have more complex form where I have multiple tabs (using antd Tabs) with table data. I am passing formRef to these tables and have it as one Form

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.3.1 |
| System | OSX |
| Browser | chrome |

**Comment by vavdav** [comment]
Oh `form.getFieldsValue(true)` did the trick. I missed this in the documentation.

**Comment by pumanitro** [comment]
Always we can do:

```
{
...initialValues,
...values
}
```

Still, I was expecting my initialValues to be visible in values in onFinish callback args.

**Comment by alienzhangyw** [comment]
> Oh `form.getFieldsValue(true)` did the trick. I missed this in the documentation.

How can I get all the fields like this in onFinish callback args?
希望表单的onFinish(values)回调也能获取到所有数据

**Comment by alnwangchi** [comment]
I have the same question too
