### ISSUE TITLE
Table没有设置footer时, 底部边框圆角不生效

### ISSUE THREAD

**Issue by VoliBearCat** [ant-design/ant-design#29958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-dynamic-settings](https://ant.design/components/table-cn/#components-table-demo-dynamic-settings)

### Steps to reproduce
关闭Footer开关, 打开Border开关, 观察表格底部边框圆角表现

### What is expected?
边框圆角表现与样式配置中的table-border-radius-base变量一致

### What is actually happening?
底部边框圆角表现为直角
![image](https://user-images.githubusercontent.com/11676384/112953052-b6d8f000-916f-11eb-8167-a3edba48acfe.png)

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17.x |
| System | macOS 11.2.3 |
| Browser | Chrome 89 |

**Comment by VoliBearCat** [comment]
另外还有个问题:
设置table-border-radius-base变量对.ant-table节点不生效
![image](https://user-images.githubusercontent.com/11676384/112954599-200d3300-9171-11eb-9741-7cc88d872a02.png)
![image](https://user-images.githubusercontent.com/11676384/112954699-3b783e00-9171-11eb-9a92-7be18e13d42f.png)

**Comment by afc163** [comment]
没有 footer 的时候，我们的组件设计稿上底部就是方的。这是预期样式。

**Comment by VoliBearCat** [comment]
> 没有 footer 的时候，我们的组件设计稿上底部就是方的。这是预期样式。

👌了解, 上面还提到个问题@table-border-radius-base变量没有应用到.ant-table节点上

**Comment by afc163** [comment]
@VoliBearCat 这个可以来个 PR

**Comment by VoliBearCat** [comment]
#29966
