### ISSUE TITLE
树节点的批量拖动如何实现

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design#29952]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
树节点的批量拖动如何实现，实现批量拖动节点功能

### What does the proposed API look like?
能够批量选中树节点，然后进行批量拖动，能自定义拖动时的样式

**Comment by afc163** [comment]
目前尚不支持。
