### ISSUE TITLE
Menu.Item 和 Menu.SubMenu 下的disabled属性true和false一样的效果

### ISSUE THREAD

**Issue by wangyongzhi** [ant-design/ant-design#2995]
#### 本地环境
脚手架工具自动安装的版本

- antd 版本:^1.11.0
- 操作系统及其版本：mac os 10.11.6
- 浏览器及其版本:chrome 53.0.2785.101 (64-bit)

#### 你做了什么？
Menu.Item 和 Menu.SubMenu 下的disabled属性true和false一样的效果
只能置空或者默认不写才显示

**Comment by benjycui** [comment]
我这边测试是好的。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
