### ISSUE TITLE
Tab组件垂直布局在safari下无法滑动

### ISSUE THREAD

**Issue by kevinpursuing** [ant-design/ant-design#29964]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-slide](https://ant.design/components/tabs-cn/#components-tabs-demo-slide)

### Steps to reproduce
1. 在滑动demo中切换至vertical
2. tabs无法滑动，且子tab高度有问题

### What is expected?
 tabs可滑动，子tab高度自适应内部组件

### What is actually happening?
tabs无法滑动，且子tab高度有问题

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.1 |
| System | macos Catalina 10.15.7 |
| Browser | Safari浏览器 13.1.3 |

**Comment by yoyo837** [comment]
能上个gif吗？14里看上去是OK的

**Comment by kevinpursuing** [comment]
![image](https://user-images.githubusercontent.com/20419163/113078245-4aa8cb80-9205-11eb-8421-31e94f47adb3.png)
这是在官网中的截图

**Comment by kevinpursuing** [comment]
这是必现的，不管在官网还是我自己的开发环境下

**Comment by yoyo837** [comment]
谁有Catalina和Safari 13来帮忙看看

**Comment by yoyo837** [comment]
@ant-design/ant-design-collaborators

**Comment by afc163** [comment]
确实有问题。

<img width="1436" alt="图片" src="https://user-images.githubusercontent.com/507615/113078698-30bbb880-9206-11eb-9f9e-006c642a0f2c.png">

**Comment by xrkffgg** [comment]
macos 11.2.3 (20D91)
Safari 版本14.0.3 (16610.4.3.1.7)

表示正常

**Comment by eijil** [comment]
12也有问题

**Comment by kevinpursuing** [comment]
@yoyo837 有解决方案了麻烦告知下哈

**Comment by kevinpursuing** [comment]
@yoyo837 @afc163 @xrkffgg @eijil 有解决方案了麻烦告知下哈，或者有临时解决方案也可以

**Comment by yoyo837** [comment]
没该版本的设备，没法看，等有该环境的设备来处理。

**Comment by hengkx** [comment]
正常

**Comment by zombieJ** [comment]
蛋疼。 。 。没有老版本的机器。

**Comment by AlanCutFlim** [comment]
无法滚动
macos Catalina 10.15.4
Safari 版本13.1.1 (15609.2.9.1.2)
![image](https://user-images.githubusercontent.com/50612752/113091813-4ee1e280-921f-11eb-837f-78f65cd5da8e.png)

**Comment by kerm1it** [comment]
我这边也不行，看起来像是 flex 布局的兼容问题，tab 项的高度没有了。


https://user-images.githubusercontent.com/33770367/113100398-f49c4e00-922d-11eb-85af-bb0f13e73d56.mp4

**Comment by yoyo837** [comment]
是哪个属性在该版本不生效吗？

**Comment by kerm1it** [comment]
像是 `inline-flex` ，但是 父级的 `display:flex` 好像也有问题。

**Comment by kevinpursuing** [comment]
@afc163 这个bug修复何时生效呢？

**Comment by kerm1it** [comment]
如果急着用，可以自己按照 https://github.com/ant-design/ant-design/pull/29983 这个里面的改动，加上样式。
