### ISSUE TITLE
Pagination Quick Jumper

### ISSUE THREAD

**Issue by Kuldeep-Chotrani** [ant-design/ant-design#29963]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://i.stack.imgur.com/HYape.png](https://i.stack.imgur.com/HYape.png)

### Steps to reproduce
This should remove "Go To" text and display "Your Text". But it appends "Your text after input box".

### What is expected?
This should remove "Go To" text and display "Your Text".

### What is actually happening?
 But it appends "Your text" after input box.

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | React |
| System | Ubuntu |
| Browser | Chrome |

---
While implementing QuickJumper in pagination. I want to use "Go to Page" instead of "Go to"

**Comment by Kuldeep-Chotrani** [comment]
Hi, thanks for your response
Here is the link
https://codesandbox.io/s/antd-reproduction-template-forked-3j252

**Comment by yoyo837** [comment]
Your reproduction link is not about pagination.

**Comment by Kuldeep-Chotrani** [comment]
`
![Screenshot from 2021-03-31 13-47-42](https://user-images.githubusercontent.com/49199229/113114664-337bd500-9229-11eb-8cb9-f0652a3fb48f.png)
![Screenshot from 2021-03-31 13-47-37](https://user-images.githubusercontent.com/49199229/113114675-35459880-9229-11eb-8339-0dd0c67a2e37.png)

`

**Comment by Kuldeep-Chotrani** [comment]
But then what is the use of this GoButton? I can simply add a span after input box
