### ISSUE TITLE
Radio单选组合，各个按钮之间的border线条粗细不一致

### ISSUE THREAD

**Issue by workermx** [ant-design/ant-design#29975]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/radio-cn/#header](https://ant-design.gitee.io/components/radio-cn/#header)

### Steps to reproduce
查看“按钮样式”或“填底的按钮样式”部分

### What is expected?
Radio按钮组中间的border线条粗细一致

### What is actually happening?
Radio按钮组中间的border线条粗细不一致

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | react |
| System | windows10 |
| Browser | Google Chrome 89.0.4389.90 |
![微信截图_20210331164531](https://user-images.githubusercontent.com/22365128/113117035-a93f6b00-9240-11eb-9b4f-d155027cd8be.png)

**Comment by xrkffgg** [comment]
没太明白，不都是 1px 么

**Comment by workermx** [comment]
> 没太明白，不都是 1px 么

追加了一个截图

**Comment by xrkffgg** [comment]
😂 没有 win 环境，我这看着是正常的

**Comment by afc163** [comment]
<kbd>ctrl</kbd> + <kbd>0</kbd> 即可修复。

**Comment by workermx** [comment]
> ctrl + 0 即可修复。

我这边也没有进行缩放操作

**Comment by afc163** [comment]
> 我这边也没有进行缩放操作

看看是不是 windows 系统设置中做了缩放设置。

**Comment by zombieJ** [comment]
windows 这侧只能 windows 修了
