### ISSUE TITLE
Button文字上下不居中

### ISSUE THREAD

**Issue by atom-shanghai** [ant-design/ant-design#29978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/button-cn/](https://ant-design.gitee.io/components/button-cn/)

### Steps to reproduce
<Button type="primary" size="large" shape="round" icon={<PaperClipOutlined />} href="https://ant.design/components/button-cn/">大按钮</Button>

### What is expected?
Button图标文字上下居中

### What is actually happening?
Button图标文字上下不能居中

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
截个图看看？

**Comment by atom-shanghai** [comment]
<img width="110" alt="7627330C-63A7-4716-B6F4-9227B9D48D6F" src="https://user-images.githubusercontent.com/63838572/113239873-2a990b00-92de-11eb-86f3-7a347d05afbc.png">

**Comment by afc163** [comment]
你这个不是 antd 官网的截图呀。

**Comment by atom-shanghai** [comment]
[https://codesandbox.io/s/antd-reproduction-template-forked-s9vmg?file=/index.js](url)

**Comment by atom-shanghai** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-s9vmg?file=/index.js

**Comment by strivelen** [comment]
这个和样式没关系，是字体设计特性问题，有些字体在设计时考虑更多的是 可读性 和 美观性，导致有些字体设计得偏上或偏下，看起来就不居中。不要用 Segoe UI / Arial 这种字体就没这种问题了。

**Comment by strivelen** [comment]
是字体设计特性问题，有些字体在设计时考虑更多的是 可读性 和 美观性，导致有些字体设计得偏上或偏下，看起来就不居中。不要用 Segoe UI / Arial 这种字体就没这种问题了。
