### ISSUE TITLE
table组件pagination属性的 showQuickJumper、 showSizeChanger属性配置失效

### ISSUE THREAD

**Issue by wangxiang1** [ant-design/ant-design#29977]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaotoufenzu-antd4150-forked-6p1o4?fontsize=14&hidenavigation=1&theme=dark&file=/index.js:2125-2140)

### Steps to reproduce
Table配置属性 pagination={{ showTotal: () => `共${1}条`, current: 2, showSizeChanger: true, showQuickJumper: true}} 
showSizeChanger、showQuickJumper未生效

### What is expected?
Table组件 pagination属性showSizeChanger、showQuickJumper生效

### What is actually happening?
Table配置属性 pagination={{ showTotal: () => `共${1}条`, current: 2, showSizeChanger: true, showQuickJumper: true}} 
showSizeChanger、showQuickJumper未生效

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.14.0 |
| System | apple m1 |
| Browser | Chrome 89.0.4389.90 |

**Comment by wangxiang1** [comment]
经过用两台不同系统的电脑的测试，我终于找到了为啥设置了showQuickJumper却不生效，因为只有在table页数2页以上才会现实，如果是1页数据，即使设置了这个属性页不会展示出来页面跳转的组件。其实这种配置应该说明一下吧。

**Comment by yoyo837** [comment]
请给我们来个PR修改一下文档。

**Comment by SmileLifeIven** [comment]
我也遇到了相同问题，但觉得不应该修改文档这种方式去做，就应该去支持pagination的所有配置项

**Comment by QiannanXu** [comment]
是的，文档说明table中的pagination参考组件Pagination的配置，但是实际表现并不一致
