### ISSUE TITLE
【upload】上传不被accept允许的文件，beforeUpload获取不到file信息

### ISSUE THREAD

**Issue by lch1677** [ant-design/ant-design#29973]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7zfw3?file=/index.js)

### Steps to reproduce
1. 使用upload组件设置accept为‘image/png’
2. 上传png文件可以正常获取file信息
3. 上传jpg文件获取不到file信息

### What is expected?
上传其它不被accept允许的文件，beforeUpload方法可以获取到file信息。

### What is actually happening?
上传其它不被accept允许的文件，没有执行beforeUpload方法。

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome |

---
4.13.0版本符合预期。

**Comment by yoyo837** [comment]
设置accept 后如何选到非 accept 允许的文件的？

**Comment by yoyo837** [comment]
https://github.com/react-component/upload/pull/302

**Comment by yoyo837** [comment]
之前的效果算bug吧

**Comment by yoyo837** [comment]
@kerm1it 是这样不？

**Comment by lch1677** [comment]
![image](https://user-images.githubusercontent.com/73467475/113112389-b4dc6300-923b-11eb-890a-6b431fba63b5.png)
window电脑可以实现，这里选择所有文件之后就可以看到不被允许的文件并上传

**Comment by kerm1it** [comment]
之前的行为是 bug，现在才是正常的行为。

原来的行为，onChange 的时候没有用 accept 过滤，导致直接选择目录的时候，目录下面不被 accept 的文件也会被选择上。

**Comment by lch1677** [comment]
> 之前的行为是bug，现在才是正常的行为。
> 
> 原来的行为，onChange的时候没有用accept过滤，导致直接选择目录的时候，目录下面不被accept的文件也会被选择上。

现在选择所有文件也可以选择accept不支持的文件。
之前还可以获取到不支持的文件，自定义提示用户上传格式错误，现在事件直接不触发，没办法做提示，感觉很不友好。

**Comment by kerm1it** [comment]
可以选择是系统的行为，没办法控制

但是 accept 的作用就是过滤上传的文件，之前 onChange 的时候没有过滤，导致如果用户选择目录，下面所有的文件都会被上传上来，此时 accept 就会失去作用，这个问题更严重。

你想实现的功能，你可以不要设置 accept，让所有文件都上传上来，然后在 beforeUpload 自己去做判断。

**Comment by lch1677** [comment]
如果单纯只是选择目录，可以当directory为true时再限制上传行为吗。

我这边还要实现选择文件时首先选择我需要的文件，所以accept还必须要限制。。。。

**Comment by yoyo837** [comment]
@lch1677 新版本重新适配一下吧。

**Comment by lch1677** [comment]
@kerm1it @yoyo837 好的，多谢讲解。

**Comment by keepwe** [comment]
@yoyo837 @lch1677 怎么适配的 解决了嘛？ 我也遇到了这个问题  @kerm1it 想用accept 的同时 执行beforeUpload 进行提示

**Comment by afc163** [comment]
Fixed in 4.15.6

**Comment by kerm1it** [comment]
这个没有修复，这个版本改的是无效的 accept 值会跳过，这个需要在 https://github.com/ant-design/ant-design/issues/30403 这里继续讨论，看新加API还是
