### ISSUE TITLE
【form】表单规则存在 required 和 其他 rules 时，required验证不通过后后续 rules 不会验证

### ISSUE THREAD

**Issue by xiefengnian** [ant-design/ant-design#29971]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-thunder-3trct?file=/src/App.js)

### Steps to reproduce
- 正常输入内容
- 删掉全部内容
- 触发 form 表单的 rules 验证

### What is expected?
全部规则都会被验证，而不仅 required 规则

### What is actually happening?
仅有 required 被验证

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | Mac OS X 11.2.3 |
| Browser | 89.0.4389.90 |

---
基于 Antd 的二次封装需要获取当前 form-item 的全部错误信息

**Comment by xiefengnian** [comment]
> https://codesandbox.io/s/sweet-rosalind-bz0n5 这样可以临时解决

这是一个 bug 吗，我可以提个PR修复这个问题

**Comment by zombieJ** [comment]
https://codesandbox.io/s/gallant-cdn-435fm

和 `required` 没有关系， `min` 本身就是有值时才会判断。这个设计初衷就是为了写两个规则时不需要额外写一个 `validateFirst`。如果需要无论多少都校验，可以自行实现一个 `validator`。
