### ISSUE TITLE
官网中的Select 选择器中api的dropdownMatchSelectWidth说明错误

### ISSUE THREAD

**Issue by 1291669609** [ant-design/ant-design#29979]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/](https://ant-design.gitee.io/components/select-cn/)

### Steps to reproduce
选中select选择器，查询·虚拟·，可以看到dropdownMatchSelectWidth说明错误

### What is expected?
说明应该是：下拉菜单和选择器同宽。默认将设置 min-width，当值小于选择框宽度时会被忽略。

### What is actually happening?
下拉菜单和选择器同宽。默认将设置 min-width，当值小于选择框宽度时会被忽略。false 时会关闭虚拟滚动

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 无需 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
没有问题，设置为 false 时会关闭虚拟滚动。
