### ISSUE TITLE
Dropdown 快速 hover 下拉消失问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#29988]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown-cn/](https://ant.design/components/dropdown-cn/)

### Steps to reproduce
例如去触发button 下拉，鼠标移动button地下，快速上下，菜单应该是hover又触发到空白热区，然后消失了。
v3版本似乎是没有这个问题的，日常使用正常快一点比较容易触发

### What is expected?
快速hover菜单正常显示

### What is actually happening?
快速hover菜单会消失

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.8.0 |
| System | win10 |
| Browser | chrome |

**Comment by theDoinb** [comment]
顺便问下用了 多层抽屉 Drawer，控制台打印 React does not recognize the `scrollLocker` prop on a DOM element  原因是？

**Comment by yoyo837** [comment]
> 顺便问下用了 多层抽屉 Drawer，控制台打印 React does not recognize the `scrollLocker` prop on a DOM element 原因是？

应该已经修复了，删除lock文件重新安装试试

**Comment by yoyo837** [comment]
没太明白主题贴的意思

**Comment by theDoinb** [comment]
emm，找那 Button - bottomCenter 测试

鼠标 快速进入 dropdown 然后 快速往下移

**Comment by theDoinb** [comment]
[https://github.com/theDoinb/ant-design-pro-blank/blob/master/public/yhfzs-4z4zc.gif](url)

**Comment by theDoinb** [comment]
![image](https://github.com/theDoinb/ant-design-pro-blank/blob/master/public/yhfzs-4z4zc.gif)

**Comment by theDoinb** [comment]
[](https://photo.baidu.com/photo/web/home)

**Comment by theDoinb** [comment]
额，不知道为什么这gif只轮播了一次，进来看不到，点击进去看看吧

**Comment by theDoinb** [comment]
在antd pro里面，那个右上角的dropdown就体验明显了，昨天我还在pro问了下：

https://github.com/ant-design/ant-design-pro/issues/8291

**Comment by roykolak** [comment]
Adding `pointer-events: visible;` to the component inside the `overlay` prop on the `<Dropdown>`  fixes this issue.
