### ISSUE TITLE
Type(InputNumber): Wrong return type in InputNumber parser

### ISSUE THREAD

**Issue by felipe-jm** [ant-design/ant-design#29986]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inputnumber-antd-14150-s71bs)

### Steps to reproduce
Use Ant Design InputNumber just like in the [docs example](https://ant.design/components/input-number/) to format numbers in input as percentage or currency.

### What is expected?
The parser prop is expected to receive a function that returns an integer.

### What is actually happening?
The parser prop accepts a function but its return type is not correct.

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 17.0.2 |
| System | Linux, Manjaro with KDE Plasma version 5.21.3 |
| Browser | Vivaldi 3.7.2218.49 / Chrome/89.0.4389.91 |

---
Isn't the parser prop expected to receive a function that returns a number so it can extract the value without the format specified in the format prop?

I have some inputs that I format the values as percentage for the user, when I updated to Ant Design version 4.15.0 I started to receive this typescript error.

**Comment by afc163** [comment]
```diff
- <InputNumber
+ <InputNumber<number>
     parser={(value) => Number(value.replace("%", ""))} // return number
   />
```
