### ISSUE TITLE
[Progress] Option to hide progress bar text

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ant-design/ant-design#29985]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When there is no text in a progress bar (`format`={() => ''}`), the left side of the progress bar and the right side of the progress bar should have equal margins / padding. Currently, there is still a div to the right of the progress bar with empty text, which makes the progress bar look off-centered.

### What does the proposed API look like?
Some ideas:
- `format={false}`
- `textVisible={false}`
- Or just automatically hide the text div when the text is `''`

**Comment by MrHeer** [comment]
Why not use `showInfo={false}`?

**Comment by ChocolateLoverRaj** [comment]
@MrHeer I didn't realize that you could do `showInfo={false}`. 

Since this feature is already there, this issue is not needed.
