### ISSUE TITLE
Select组件 自定义suffixIcon时 点击icon无法展开下拉框

### ISSUE THREAD

**Issue by 0408jiahuicao** [ant-design/ant-design#29996]
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Select, Tag } from "antd";
import { CaretDownOutlined } from "@ant-design/icons";

const options = [
  { value: "gold" },
  { value: "lime" },
  { value: "green" },
  { value: "cyan" }
];

function tagRender(props) {
  const { label, value, closable, onClose } = props;

  return (
    <Tag
      color={value}
      closable={closable}
      onClose={onClose}
      style={{ marginRight: 3 }}
    >
      {label}
    </Tag>
  );
}

ReactDOM.render(
  <Select
    mode="multiple"
    showArrow
    tagRender={tagRender}
    defaultValue={["gold", "cyan"]}
    style={{ width: "100%" }}
    options={options}
    // showSearch
    suffixIcon={  <CaretDownOutlined  /> }
  />,
  document.getElementById("container")
);

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/23263

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28914#issuecomment-762670998

**Comment by qq34347476** [comment]
给 Icon 加个样式 pointer-events: none 就能直接解决

**Comment by lmcgit1** [comment]
自定义的icon外面用span包一下 加上ant-select-suffix类就好了
<img width="497" alt="image" src="https://user-images.githubusercontent.com/54028047/191739250-557e32a0-1b92-47ef-ad24-6c5d26a21583.png">
