### ISSUE TITLE
chrome浏览器升级最新版本后Table错位

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#29993]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/table-cn/](https://3x.ant.design/components/table-cn/)

### Steps to reproduce
chrome浏览器升级最新版本后导致Table错位

### What is expected?
升级chrome浏览器Table不错位

### What is actually happening?
chrome浏览器升级最新版本后导致Table错位

| Environment | Info |
|---|---|
| antd | 3.26.1 |
| React | 15.3.0 |
| System | windows7 |
| Browser | google chrome 89.0.4389.90 |

**Comment by yoyo837** [comment]
3.x 已经不维护了。

可能相关的issue #29783
