### ISSUE TITLE
inputnumber，enter键的时候，受控组件数据不一致

### ISSUE THREAD

**Issue by mankeheaven** [ant-design/ant-design#29991]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6mrll?file=/inputnumber.js)

### Steps to reproduce
输入任意数值（不同于初始值1），比如5， 按enter,会回退，blur则正常

### What is expected?
enter键得到新值

### What is actually happening?
enter键，值未刷新

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 17.0.2 |
| System | windows10 |
| Browser |  chrome 89.0.4389.90（正式版本） （64 位） |

---
是由依赖的react-component/ inputnumber组件的bug引发的，https://github.com/react-component/input-number/issues/305 
  ， 我已在那边提了pr

**Comment by mankeheaven** [comment]
这个pr没人处理吗？

**Comment by yy923683900** [comment]
我这边也遇到了这个问题

**Comment by yeyeyehui** [comment]
我也遇到了这个问题，快快解决
