### ISSUE TITLE
Table 是否受控的判断条件不包含 `filtered`

### ISSUE THREAD

**Issue by Mongkii** [ant-design/ant-design#30003]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/HEAD/components/table/hooks/useFilter/index.tsx](https://github.com/ant-design/ant-design/blob/HEAD/components/table/hooks/useFilter/index.tsx)

### Steps to reproduce
搜索：`if (collectedStates.every(({ filteredKeys }) => filteredKeys === undefined)) {`

### What is expected?
`if (collectedStates.every(({ filteredKeys, forceFiltered }) => (filteredKeys === undefined && forceFiltered === undefined))) {`

### What is actually happening?
`if (collectedStates.every(({ filteredKeys }) => filteredKeys === undefined)) {`

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | macOS 10.14.5 |
| Browser | Chrome 89 |

---
Table 只通过 filteredKeys 判断是否受控，而不考虑 forceFiltered 字段，请问是有意为之吗？

**Comment by qinghua5453** [comment]
> 场景是：自行实现了一个筛选组件，该组件中的筛选状态能反映到表格中。即：通过直接设置 filtered 属性控制表格的「已筛选」状态
> 
> 示例代码：
> 
> ```ts
> const [isFiltered, setIsFiltered] = useState(false);
> 
> const columns = [
>   {
>     filtered: isFiltered,
>   },
> ];
> ```
> 
> 但由于 issue 中的判断逻辑，我还必须额外设置 filteredValue，才能达到目的
> 
> ```ts
> const columns = [
>   {
>     filtered: isFiltered,
>     filteredValue: [],
>   },
> ];
> ```
> 
> 比较好奇为什么不能仅仅设置 filtered，是出于什么设计的权衡吗
你简直救了我的命啊，我就是没写那个filteredValue: [], 筛选active 死活多出现不了。
