### ISSUE TITLE
Tooltip 不显示问题

### ISSUE THREAD

**Issue by liaoyubo** [ant-design/ant-design#30002]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4150-forked-9037f)

### Steps to reproduce
鼠标悬浮 button myBtn 上

### What is expected?
鼠标悬浮 myBtn 上显现 tooltip

### What is actually happening?
鼠标悬浮 myBtn 上未显现 tooltip

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 16.14 |
| System | mac |
| Browser | chorme   89.0.4389.90 |

---
import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { Tooltip, Button } from 'antd';

const MyButton = () => {
  return (
    <Button>myBtn</Button>
  )
}

ReactDOM.render(
  <div>
  <Tooltip title="antd button">
    <Button>button</Button>
  </Tooltip>
  <Tooltip title="custom button">
    <MyButton />
  </Tooltip>

  </div>,
  document.getElementById('container'),
);

**Comment by kerm1it** [comment]
试试这个：https://codesandbox.io/s/jiben-antd4150-forked-izlhz?file=/index.js

因为 tooltip 会监听子元素的鼠标事件，MyButton 需要把传入的监听器透传给 Button，这个 Button 的事件可以冒泡到 tooltip 上，否则中间就中断了。

**Comment by laochake** [comment]
> 试试这个：https://codesandbox.io/s/jiben-antd4150-forked-izlhz?file=/index.js
> 
> 因为 tooltip 会监听子元素的鼠标事件，MyButton 需要把传入的监听器透传给 Button，这个 Button 的事件可以冒泡到 tooltip 上，否则中间就中断了。

https://codesandbox.io/s/jiben-antd4150-forked-birg6?file=/index.js 试了下 透传props, 但是如果Button是disabled下又不可以了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9581#issuecomment-374113785
