### ISSUE TITLE
Tree has a <div role="tree"> with empty, hidden <input> element.

### ISSUE THREAD

**Issue by m-rv** [ant-design/ant-design#30008]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qxfyx?file=/index.js)

### Steps to reproduce
Render any tree and see that there's a div with role="tree" that only has an input element in it. The input is invisible. The actual tree container has no role.

### What is expected?
The div with tree items should have role="tree"

### What is actually happening?
This is breaking for example tests with RTL which use *ByRole("tree")

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.13 |
| System | Mac OS |
| Browser | Chrome |

**Comment by wwyx778** [comment]
I will fix it.
