### ISSUE TITLE
[Progress] Ref for div

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ant-design/ant-design#30009]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm trying to get the `offsetWidth` of the progress bar. I currently have the `<Progress />` wrapped in a `<div />` with a ref, but this creates an extra, unnecessary `div`.

### What does the proposed API look like?
A `defaultRef` prop.
```jsx
<Progress defaultRef={myRef} />
```

**Comment by afc163** [comment]
You can try these methods too: https://codesandbox.io/s/progress-bar-antd4150-forked-rrs48?file=/index.js

**Comment by ChocolateLoverRaj** [comment]
@afc163 Does `ref` work because `Progress` is a class component and `ref` does the outermost element it renders?
