### ISSUE TITLE
Color palette customization

### ISSUE THREAD

**Issue by emresandikci** [ant-design/ant-design#30004]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I research so many different ways and read the documentation but I didn't see any way to customize the color pallet of the ant design. There is just one thing it's customizing the primary, danger, etc. colors, should I override all of the stuff with custom CSS or classes or override current classes?

### What does the proposed API look like?
just overrides current color properties, not the color pallet, the color pallets generates automatically by the current color

**Comment by afc163** [comment]
Color palette is generated from primary color, but you can modify color variables by https://ant.design/docs/react/customize-theme

https://github.com/ant-design/ant-design/blob/master/components/style/color/colors.less
