### ISSUE TITLE
[Feature request] Provide props for justify of Space

### ISSUE THREAD

**Issue by zhixiaoqiang** [ant-design/ant-design#30000]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
no need to manually modify the style

### What does the proposed API look like?
like Row component

**Comment by afc163** [comment]
Space is UI component which adding even gutter bettween inline elements. You should use Grid instead.
