### ISSUE TITLE
Upload 上传多个文件时 onChange 调用不正确

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#3001]
#### 本地环境

- antd 版本: last
- 操作系统及其版本：mac 10.11.6
- 浏览器及其版本: chrome last

#### 你做了什么？

上传多个文件，自己实现了一份上传列表，要显示上传进度

#### 你期待的结果是：

上传多个文件验证通过的文件正常上传，不正确的文件不上传

#### 实际上的结果：

上传多个文件时，选的文件最后一个不通过验证（即**beforeUpload**返回**false**），之前验证通过的文件正常上传了，但是却没有调用 onChange 函数。

#### 可重现的在线演示

重现方法：
第一次选一个jpg文件和一个非jpg文件
第二次同样的两个文件顺序相反
看控制台，一次onChange调用了，一次没调用，应该是两种情况都要调用的

http://codepen.io/xutou12/pen/QKjrKw?editors=0010

**Comment by afc163** [comment]
感谢细致的反馈~

**Comment by xutou12** [comment]
p^.^q
