### ISSUE TITLE
inputNumber在mac样式问题怎么修改

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design#30011]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
inputNumber在mac样式问题

### What does the proposed API look like?
inputNumber在mac样式和windows一样

**Comment by huangzongming** [comment]
![Uploading 截屏2021-04-01_下午3.07.12.png…]()

**Comment by xrkffgg** [comment]
截图失败
