### ISSUE TITLE
inputNumber里使用precision限制保留两位小数，某些数值会被五舍六入，例如：2.155

### ISSUE THREAD

**Issue by githubchx12380** [ant-design/ant-design#30012]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
inputNumber组件设置precision=2， 失去焦点以后执行四舍五入，某些数值会被五舍六入,例如:2.155

### What is expected?
fix

### What is actually happening?
暂无

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome |

**Comment by xrkffgg** [comment]
有什么问题？

**Comment by drizzlesconsin** [comment]
@githubchx12380 https://github.com/ant-design/ant-design/blob/49162f98835c385df068c55ff5ec75a0b2197284/CHANGELOG.zh-CN.md#L89
