### ISSUE TITLE
Form Item Rules 里面的 message 不能使用 ${xxx} 这种形式，用了不会被 replace

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#30016]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-methods-antd4150-forked-15zf9?file=/index.js)

### Steps to reproduce
直接点击 submit 按钮

### What is expected?
Error message 应该显示 Name Label is required in message!

### What is actually happening?
Error message 显示 ${label} is required in message!

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.14.0 |
| System | all |
| Browser | all |

---
validateMessages 是可以工作的，但是为什么 rules 里面的就不行呢？

**Comment by afc163** [comment]
意义不大吧，单独给 rule 设置 message，你肯定知道 label 的值是啥，直接写出来就行了。

**Comment by zation** [comment]
> 意义不大吧，单独给 rule 设置 message，你肯定知道 label 的值是啥，直接写出来就行了。

太敬业了，这么晚了还回复，感谢~ 但是我觉得意义还是比较大的，有了这个功能才更好抽象和复用吧，比如针对一些 error message 是基本不变且仅依赖于 label 或 value 的情况，如果没有这个功能，那么我可能要连 Item 一起抽一个组件才能消除重复，如果有这个功能，我抽一个 error message template string const 或者抽一个 rule 就消除重复了

然后我们现在就是想把 validation 的逻辑和组件的逻辑分开，validation 这边就只有 validate 和 error message，但是实际操作的时候发现 error message 严重依赖于组件。。。如果我可以在 validator 里面拿到 messageVariables 或者让 rule 的 message 支持 template，那么 validation 的逻辑就容易独立开来然后去不同的组件复用了

**Comment by afc163** [comment]
label 属性肯定得写，做二次封装的吧，统一在 messsage 直接用 ` 内写变量应该也是可以的吧。

```diff
      <Form.Item
        name="name"
        label={label}
        required
        rules={[
          {
-           message: "${label} is required in message!",
+           message: `${label} is required in message!`,
            required: true
          }
        ]}
      >
        <Input />
      </Form.Item>
```

**Comment by zation** [comment]
这样 rule 的逻辑就跟组件逻辑分不开了，或者说得额外传一些参数给 rule creator
但是既然 Item 都有 messageVariables 这个 prop 了，然后这个 messageVariables 在 Item 的 rules 里面又不能用。。。只能在父级 Form 那边的 validateMessages 里面起效果，这个也很奇怪。。。

**Comment by afc163** [comment]
@zombieJ 可以来看看。

**Comment by zombieJ** [comment]
v4 为了兼容 v3 的 rules，所以在新写的 `rc-field-form` 里还是使用 v3 依赖的 `asnyc-validator`，而依赖的 `async-validator` 不支持注入。`validateMessages` 是由外部直接填充完错误模板后扔给了 `async-validator` 校验，错误信息相当于提前准备好了（嗯，这里其实有性能损耗）。而在 `rules` 里的 `message` 是不过模板填充的，导致两者行为不太一致。

从功能上看，一致性最好就是做一个支持变量模板的校验器。但是从重构成本上看，性价比就没那么高了。

我瞅瞅有没有简单的方式可以做到。

**Comment by zombieJ** [comment]
看了一下当时的写法，`async-validator` 返回的结果不包含原始 `rule` 信息，而一些错误提示需要填充诸如 `len` `enum` 等信息，所以是前置填充模板。而 rule 本身是支持返回 Error 和 Promise.reject 的，导致返回信息可能是动态的。因而和 `message` 一起没有去做这个事情。现在看来，不带着 `async-validator` 一起改，这个需求暂时实现不了。

ref: https://github.com/react-component/field-form/blob/e118381c2102b36c4ffe7e17a6415df091e772b7/src/utils/validateUtil.ts#L71

**Comment by zation** [comment]
可以给 rule 的 validator 增加 messageVariables 参数吗（跟 label 那些属性拼装好的那个，好像也是有 value 的，那样 validator 的 value 参数可以省了）？这样是不是成本低一点？

**Comment by zation** [comment]
或者说 formInstance 可以 getMessageVariables 也可以，我举一个实际的例子吧，比如说我现在要抽象一个 sameAsRule 的 creator，现在是这么实现的：
```
export const createSameAsRule = (
  message: string,
) => (targetNamePath: NamePath, targetLabel?: string) => ({ getFieldValue }: FormInstance) => ({
  async validator(rule: any, value: any) {
    if (value && getFieldValue(targetNamePath) !== value) {
      throw new Error(replaceMessage(message, { ...rule, value, label: targetLabel }));
    }
  },
});
```
如果可以给 validator 增加 messageVariables 的话：
```
export const createSameAsRule = (
  message: string,
) => (targetNamePath: NamePath) => ({ getFieldValue }: FormInstance) => ({
  async validator(rule: any, value: any, messageVariables: any) {
    if (value && getFieldValue(targetNamePath) !== value) {
      throw new Error(replaceMessage(message, messageVariables));
    }
  },
});
```
如果可以给 formInstance 增加 getMessageVariables 的话：
```
export const createSameAsRule = (
  message: string,
) => (targetNamePath: NamePath) => ({ getFieldValue, getMessageVariables }: FormInstance) => ({
  async validator(rule: any, value: any, messageVariables: any) {
    if (value && getFieldValue(targetNamePath) !== value) {
      throw new Error(replaceMessage(message, getMessageVariables));
    }
  },
});
```

**Comment by zombieJ** [comment]
> 看了一下当时的写法，`async-validator` 返回的结果不包含原始 `rule` 信息，而一些错误提示需要填充诸如 `len` `enum` 等信息，所以是前置填充模板。而 rule 本身是支持返回 Error 和 Promise.reject 的，导致返回信息可能是动态的。因而和 `message` 一起没有去做这个事情。现在看来，不带着 `async-validator` 一起改，这个需求暂时实现不了。
> 
> ref: https://github.com/react-component/field-form/blob/e118381c2102b36c4ffe7e17a6415df091e772b7/src/utils/validateUtil.ts#L71

最终的产物是 `async-validate` 异步聚合返回的，上层传递后结果里是对应不起来的。需要改造 `async-validator` 才行。

**Comment by zombieJ** [comment]
在做 warning，这个顺道一起了

**Comment by OnlyFlyer** [comment]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/19942622/211540494-d5d836ca-57cf-4581-ab30-f258c8c31cab.png">

<img width="381" alt="image" src="https://user-images.githubusercontent.com/19942622/211540525-fe86c301-c7d4-47d1-bf00-af587dcee41f.png">

message 支持 ReactElement，这样写不会被 replace 掉
