### ISSUE TITLE
we haven't cancelType for modal confirm

### ISSUE THREAD

**Issue by m-jch** [ant-design/ant-design#30017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
we have okType for modal confrim component, but there isn't cancelType for that

### What does the proposed API look like?
cancelType: LegacyButtonType

**Comment by m-jch** [comment]
for a workaround we can use this:
```
cancelButtonProps: {className: 'ant-btn-primary'},
```

**Comment by afc163** [comment]
`cancelButtonProps` is a correct choice.
