### ISSUE TITLE
Cascader 怎么可以设置选择二级三级，但是不能选择一级呢？

### ISSUE THREAD

**Issue by LullabyLY** [ant-design/ant-design#30026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求场景是有一个省市区的级联框，用户可以选择到市，也可以选择到区，但是不能选择省，请问这个应该怎么实现呢？

In the three-level cascade box of provinces and cities, how can I choose a city (for example, Shenzhen, Guangdong Province) or a district (for example, Baoan District, Shenzhen, Guangdong Province), instead of directly selecting the province

**Comment by xrkffgg** [comment]
不选择省，怎么选择市？
难道二级列出所有省份的市来选择？没太理解。。。

**Comment by yoyo837** [comment]
我感觉诉求就是这个意思，每一级可以多选，下一级的内容是上面所有已选内容的可选下级。

**Comment by afc163** [comment]
做一个市/区选择器就好了，省拿出去。

**Comment by LullabyLY** [comment]
需求是在省市的三级层叠框中，可以选择到市（例如，广东省深圳市）或地区（例如，广东省深圳市宝安区），但是不能直接选择省份（例如我只选择广东省），而且要求必须是省市区的级联

**Comment by believeZJP** [comment]
可以在`displayRender`里配置，如果选中的值长度是1，不展示内容，只有选中长度大于1才展示选中的
```js
displayRender: (val) => {
      console.log(val, '选中的');
      if (val?.length > 1) {
          return val[val.length - 1];
      }
  },
```
