### ISSUE TITLE
Upload组件accept为image/*时，文件选择窗口弹出很慢

### ISSUE THREAD

**Issue by zxyah** [ant-design/ant-design#3002]
Upload组件accept为image/*时，文件选择窗口弹出很慢
accept指定为具体图片格式时没有问题，如:accept="image/png,image/jpeg,image/jpg"

demo在这：http://codepen.io/zxyah/pen/PGPZPX

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2798#issuecomment-241308626

貌似是 chrome 的 bug，解决不了。

**Comment by leekang** [comment]
之前也遇到这个问题你可以这样写image/jpg,image/jpeg,image/png,image/gif

**Comment by afc163** [comment]
https://zhuanlan.zhihu.com/p/27946188
