### ISSUE TITLE
The direction of the icons of the menu elements should be manageable.

### ISSUE THREAD

**Issue by huseyingoztok** [ant-design/ant-design#30029]
![menu-items](https://user-images.githubusercontent.com/43777036/113662154-3145ca80-96b0-11eb-9aef-6e2866d0e330.png)

- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
---

### What does the proposed API look like?
---

**Comment by afc163** [comment]
This follows Ant Design Specification, you can change it by customizing `expandIcon`.

**Comment by huseyingoztok** [comment]
ReactNode | (props: SubMenuProps & { isSubMenu: boolean }) => ReactNode

I can't access isSubMenu property any way.
