### ISSUE TITLE
antd design离线版api怎么下载？

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design#30028]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
内网开发使用

### What does the proposed API look like?
和外网文档一样

**Comment by yoyo837** [comment]
clone 下来 启动即可

**Comment by huangzongming** [comment]
![{3Z$N{P)}AMVPX01M4JA_WD](https://user-images.githubusercontent.com/37889515/113676017-8b658080-96ee-11eb-9226-7112a1cc917f.png)

**Comment by yoyo837** [comment]
请为你的github添加ssh key
