### ISSUE TITLE
Columns slide out when scroll and sticky are used together

### ISSUE THREAD

**Issue by vraja-nayaka** [ant-design/ant-design#30035]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdesign-table-sticky-scroll-columns-slide-out-bag-7dl75)

### Steps to reproduce
- Create table with scroll and sticky props and 15 columns.
- Scroll right to see columns slide out.

The issue is reproduced in sandbox.
Window width: 1024 and other.

### What is expected?
Columns should not shift

### What is actually happening?
Header and columns are slide out

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.8.6 |
| System | MacOS 10.14.6 (18G8022) |
| Browser | Firefox 87.0 (64-bit) |

https://user-images.githubusercontent.com/52737608/113703555-a7175980-96e3-11eb-90e9-bc9604526e44.mov

**Comment by afc163** [comment]
https://codesandbox.io/s/antdesign-table-sticky-scroll-columns-slide-out-bag-forked-1i67l?file=/src/components/CustomTable.js

**Comment by vraja-nayaka** [comment]
It doesn't solve the issue. 
Columns slide out in sticky mode even without scroll.
Just try change window width in your sandbox

<img width="1419" alt="Снимок экрана 2021-04-07 в 13 10 53" src="https://user-images.githubusercontent.com/52737608/113850074-c1643c80-97a2-11eb-95f8-62befe159cb6.png">

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/113854252-41a19680-97d1-11eb-98b3-2038905d0686.png">

**Comment by afc163** [comment]
You can give every column a fixed width.
