### ISSUE TITLE
Checkbox.Group missing forwardRef

### ISSUE THREAD

**Issue by xzm920** [ant-design/ant-design#30036]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-b8673)

### Steps to reproduce
Open console, you can see one warning about Checkbox.Group

### What is expected?
No Warnings about Checkbox.Group

### What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `TestForm`.
    at CheckboxGroup (https://b8673.csb.app/node_modules/antd/es/checkbox/Group.js:36:25)
    at span
    at div
    at div
    at Col (https://b8673.csb.app/node_modules/antd/es/grid/col.js:40:33)
    at div
    at Row (https://b8673.csb.app/node_modules/antd/es/grid/row.js:39:34)
    at FormItem (https://b8673.csb.app/node_modules/@ant-design/compatible/es/form/FormItem.js:206:5)
    at form
    at Form (https://b8673.csb.app/node_modules/@ant-design/compatible/es/form/Form.js:176:5)
    at TestForm (https://b8673.csb.app/testForm.js:33:5)
    at Form(TestForm) (https://b8673.csb.app/node_modules/create-react-class/factory.js:823:37)
    at div

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.7 |
| Browser | Chrome 89.0.4389.90 |

---
There is no React.forwardRef in source code: https://github.com/ant-design/ant-design/blob/a1baecbd2f6996837d62fff0a1368fb30b452d14/components/checkbox/Group.tsx

**Comment by hengkx** [comment]
Group doesn't support ref. What scenarios need to be used?

**Comment by jameslahm** [comment]
It seems `Form` in `v3` will save ref for `CheckGroup`, which may be the reason. I am working on a pr to fix it.

**Comment by xzm920** [comment]
> Group doesn't support ref. What scenarios need to be used?

Part of our code is still using old v3 `Form` imported from `@ant-design/compatible`. There is a Checkbox.Group used in olde v3 `Form`.

**Comment by xzm920** [comment]
> It seems `Form` in `v3` will save ref for `CheckGroup`, which may be the reason. I am working on a pr to fix it.

Yes, this is the reason.
