### ISSUE TITLE
InputNumber 输入0，输入框自动填入0.01的问题

### ISSUE THREAD

**Issue by shalling0308** [ant-design/ant-design#30034]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
选择官网格式化展示InputNumber的demo代码，增加min最小值0.01，然后输入0，输入框自动填入0.01的问题

### What is expected?
输入0，失去焦点后输入框自动填入0.01，而不是立即自动填入0.01

### What is actually happening?
输入0，立即自动填入0.01，交互效果上有问题

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | react |
| System | mac |
| Browser | 谷歌 |

**Comment by jameslahm** [comment]
感觉这不是一个交互效果上的问题？因为在输入过程中应该要触发`input`的`onChange`的回调，回调参数应该传入的是经过校验修改后的值，如果输入框上仍然显示原始值，这会造成`onChange`的参数值与界面显示不一致的问题？

**Comment by jameslahm** [comment]
在受控模式下，会在`onBlur`之后修改显示为校验过的值，https://codesandbox.io/s/jiben-antd4150-forked-9nkgm?file=/index.js
官方文档：
![image](https://user-images.githubusercontent.com/43805318/113803015-45f89000-978e-11eb-9336-5d6ece0b52b9.png)

**Comment by hengkx** [comment]
@zombieJ  这个解决了 是不是 就没有 这个 问题了 https://github.com/react-component/input-number/pull/313

**Comment by zombieJ** [comment]
这个不是 bug，如果用户需要输入 `0.02` 在输入第一个 `0` 的时候它自动跳成 `0.01` 是不符合预期的。

ref #29609

**Comment by haledc** [comment]
请问这是一个 Bug 吗？现在应该还是没有解决这个问题吧？不明白为什么会把这个 Issue 关了。@zombieJ
