### ISSUE TITLE
table组件filterDropDown自定义筛选，怎么控制filter列表的显示和隐藏

### ISSUE THREAD

**Issue by elearic** [ant-design/ant-design#3003]
#### 本地环境
- antd 版本: ant last
- 操作系统及其版本：win 10
- 浏览器及其版本: google chrome last
#### 你做了什么？

使用table组件的filterDropDown属性做了类似于excel表头的自定义筛选，我想通过点击[确定]设置menu的visible为false,即筛选列表隐藏
#### 你期待的结果是：

下次点击漏斗menu可以通过点击漏斗触发一个事件，使我能将menu的visible更新为true，还能显示menu
#### 实际上的结果：

第一次做了筛选，设置了menu的visible为false后。第二次做筛选时没有一个触发点，可以使我将menu的state更新为true

**Comment by elearic** [comment]
![image](https://cloud.githubusercontent.com/assets/14890380/18416913/afb60f8a-7854-11e6-9480-aa383ee05a51.png)

**Comment by benjycui** [comment]
现在 FilterMenu 的 visible 是不可控的，cc @afc163

**Comment by elearic** [comment]
@benjycui 我昨天在issues翻看了很多问题，看到好几个关于filterMenu的问题，感觉这个功能很重要啊。

**Comment by bjwulin** [comment]
我也卡在这儿了。关不掉overlay。能不能把column传给filterDropdown，然后在column上做一个filterVisible状态？这样的话，我们的filterDropdown就可以控制overlay的显示和关闭了？

**Comment by afc163** [comment]
确实是的，等我有空细化一下使用场景，搞一个演示。

**Comment by elearic** [comment]
@afc163 @benjycui  谢谢了

**Comment by XUGAOBO** [comment]
@afc163 前辈,这个问题的演示稿现在有吗,我也是卡在这儿了

**Comment by lslvxy** [comment]
没有具体的解决方案啊

**Comment by ptlinyi** [comment]
这个现在怎么解决？是要等升级吗？

**Comment by ptlinyi** [comment]
@afc163 这个现在怎么解决？是要等升级吗？
