### ISSUE TITLE
InputNumber 设置 precision 为 0 时， 失焦后提交表单，输入框展示的值和实际提交的值不一致

### ISSUE THREAD

**Issue by haledc** [ant-design/ant-design#30045]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4150-forked-wnu45?file=/index.js:466-475)

### Steps to reproduce
打开重现链接，在输入框中输入 1.55，然后鼠标在输入框外单击一下触发失焦事件，此时输入框的值变成 2，然后再次点击 submit 按钮，查看 console 面板发现提交的值还是 1.55，和输入框展示的值：2 不一致。

### What is expected?
输入框失焦后，点击 submit 按钮，提交的值和输入框展示的值保持一致。

### What is actually happening?
输入框失焦后，点击 submit 按钮，提交的值和输入框展示的值不一致。

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.14.0 |
| System | macOS 11.2.3 |
| Browser | chrome |

---
设置 precision 为 1 或者 2 时，输入框失焦后，点击 submit 按钮，提交的值和输入框展示的值是一致的，没有问题。

**Comment by jameslahm** [comment]
The problem is here https://github.com/react-component/input-number/blob/4c53ce92f1194f18c7d6edace9f8b856670208fa/src/InputNumber.tsx#L288-L290
