### ISSUE TITLE
clicking on checkbox of single row leads to all checkboxes got checked.

### ISSUE THREAD

**Issue by YagamiNewLight** [ant-design/ant-design#30040]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuanzehecaozuo-antd4150-forked-hqwt9?file=/index.js)

### Steps to reproduce
1. open the interface for rowSelection.
2. Click the checkbox on each row.

### What is expected?
Only the current checkbox got checked.

### What is actually happening?
All the checkboxes got checked.

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | 88.0.4324.190 |

---
The reason is the missing prop `rowKey` on `Table` component, but there is no information to tell developers this prop is needed when using `rowSelection`. And it actually works in antd 3.x version without this prop.

Link for 3.x without `rowKey`: https://codesandbox.io/s/xuanzehecaozuo-antd4150-forked-tgwgt?file=/index.js:1591-1673

**Comment by zombieJ** [comment]
In v3 `rowKey` will fallback to `index` as tmp key but its not stable. You should not rely on it even it works on v3.

**Comment by YagamiNewLight** [comment]
@zombieJ 
So I think this `rule` should be part of the documentation, especially when its behavior changed over versions.

**Comment by zombieJ** [comment]
https://ant.design/components/table-cn/#%E6%B3%A8%E6%84%8F
