### ISSUE TITLE
Radio API介绍与实际使用结果不符

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#30044]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
API文档中的Radio的value标注类型为any，但是实际使用过程中，Radio的value为一个数组（[1, 2,]）给Radio.Group设置选中的value为[1, 2]。Radio无法选中。
这里仅是设置value时，Radio仍然是未选中状态。但是鼠标单击选中后，值可以正常获取到。

### What does the proposed API look like?
实际使用结果能够与API描述相符。

**Comment by zmbxy95** [comment]
[CodeSandbox demo](https://codesandbox.io/s/danxuanzuhe-antd4150-forked-rxc06)

**Comment by zmbxy95** [comment]
补充说明：在Form表单下可以通过鼠标操作设置选中状态并且正常取值，如果是单独使用Radio，并且设置为非基本类型，鼠标单击无法选中。

**Comment by afc163** [comment]
```jsx
console.log(1 === 1); // true
console.log([1, 2] === [1, 2]); // false
```

**Comment by zmbxy95** [comment]
虽说是这个道理，但是这样的话value类型为any，可以说没有任何意义，毕竟存在如图demo中的状况，如果使用非基本类型，组件一旦受控，就是无法正常使用。仍然建议将API中的value类型标注清楚的好。 或者更改值比较方式。
@afc163

**Comment by afc163** [comment]
虽然比较蛋疼，引用保持唯一数组也是能工作的：https://codesandbox.io/s/danxuanzuhe-antd4150-forked-4irrw?file=/index.js。

**Comment by hengkx** [comment]
如果 引入 `equals` 呢
