### ISSUE TITLE
Table 使用拖拽手柄时，如果有图片，例如 Image 组件，会重新加载图片，会闪一下

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#30049]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/tuozhuaishoubinglie-antd4150-forked-w6txo?file=/index.js](https://codesandbox.io/s/tuozhuaishoubinglie-antd4150-forked-w6txo?file=/index.js)

### Steps to reproduce
打开 codesandbox，打开 F12，勾选 Disable cache，查看 network，然后拖动行。会发现图片会闪烁，重新加载图片

### What is expected?
希望不会闪一下，体验不好

### What is actually happening?
控制台 network 中会重新加载图片资源，图片会闪一下

| Environment | Info |
|---|---|
| antd | lastest |
| React | lastest |
| System | mac |
| Browser | chrome |

---

在 codesandbox 中闪烁还不是很明显，在实际项目中很明显，例如在 antd-pro 中写个最小事例，闪烁都会很明显。

**Comment by linxianxi** [comment]
我发现了我控制台勾选了 Disabled cache。所以说勾选了的话一定会这样对吧。
![image](https://user-images.githubusercontent.com/47104575/113880797-635d4680-97ee-11eb-8b95-c85127ddb496.png)

**Comment by jameslahm** [comment]
这个应该不是`antd`的问题，是因为`react`在`reconcile`的时候会比较`child`的`type`，这里因为每次`render`的时候，`DraggableContainer`都不一样，所以会导致每次渲染的时候都要重新挂载`DraggableContainer`。

**Comment by linxianxi** [comment]
> 这个应该不是`antd`的问题，是因为`react`在`reconcile`的时候会比较`child`的`type`，这里因为每次`render`的时候，`DraggableContainer`都不一样，所以会导致每次渲染的时候都要重新挂载`DraggableContainer`。

那有办法么，体验很不好，不止会闪，每行的宽度也会跟着闪变化

**Comment by jameslahm** [comment]
宽度变化好像是`react-sortable-hoc`修改样式造成的，避免重新渲染可以使用`useCallback`或者`useMemo`将组件缓存，也可以考虑一下其他的拖拽的库，`react-sortable-hoc`作者已经不推荐使用了。

**Comment by zombieJ** [comment]
close since it seems not reproduce anymore:

https://codesandbox.io/s/tuo-zhuai-shou-bing-lie-antd-4-15-0-forked-yz3nj?file=/index.js
