### ISSUE TITLE
Disabled Button type="link" does not have `cursor: not-allowed` style

### ISSUE THREAD

**Issue by Nikolay-Borzov-EPAM** [ant-design/ant-design#30043]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ndjap4?file=index.js](https://stackblitz.com/edit/react-ndjap4?file=index.js)

### Steps to reproduce
1. Insert `Button` component a set props  `type="link"` and `href="http://google.com"`
2. Hover over the button

### What is expected?
Button type="link" must have `cursor: not-allowed` when `href` prop is set

### What is actually happening?
The button has a default cursor

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.14.0 |
| System | WIndows 10 |
| Browser | Chrome  89.0.4389.114 |

**Comment by jameslahm** [comment]
The reason should be that `pointer-events: none` will be applied to `<Button disabled type="link" href="http://google.com">
        Link Button w href set
      </Button>`, which will disable all mouse interactions with that element and thus `cursor` style will not work. You could add a wrapper for the button, and apply `cursor` style to the wrapper, here is a [demo](https://stackblitz.com/edit/react-ndjap4-bxhuub?file=index.js).

**Comment by Nikolay-Borzov-EPAM** [comment]
I see. Thanks for the clarification. But could it be handled by `antd` (adding a wrapper)?

**Comment by jameslahm** [comment]
I am not sure. I think it's better to control `cursor` style ourselves. But if the `antd` team think it's reasonable to add a wrapper internally, I'm very pleased to make a pr 😂.
