### ISSUE TITLE
The page size doesn't change when changing page size in pagination selector.

### ISSUE THREAD

**Issue by YagamiNewLight** [ant-design/ant-design#30059]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/yqjjh](https://codesandbox.io/s/yqjjh)

### Steps to reproduce
Select a different page size on the pagination selector.

### What is expected?
The table gets refreshed with a new page size.

### What is actually happening?
Nothing happens.

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | Chrome 88.0.4324.190 |

**Comment by afc163** [comment]
```diff
- pageSize: 50
+ defaultPageSize: 50
```

**Comment by YagamiNewLight** [comment]
Much thanks. But maybe you could update the usage in the doc~. The reproduce link was grabbed from the documentation.
