### ISSUE TITLE
How can I remove ::selection style settings

### ISSUE THREAD

**Issue by phaibin** [ant-design/ant-design#30054]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I just don't want custom ::selection style and want to use browser default style. How can I do it?

### What does the proposed API look like?
I just don't want custom ::selection style and want to use browser default style. How can I do it?

**Comment by afc163** [comment]
Duplicate of #26587
