### ISSUE TITLE
封装了 antd 的组件打包后无法 treeShaking

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#30063]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
团队内部的 ui 仓库有部分组件 antd 做了二次的封装，打包为 esm 后，对 antd 有引用的组件无法 treeShaking

### What is expected?
希望能够 treeShaking

### What is actually happening?
无法 treeShaking

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by yoyo837** [comment]
二次封装的时候也要支持treeShaking才行 和 antd本身无关了。

**Comment by yoyo837** [comment]
二次封装的lib是否支持treeShaking生效的4个条件？

**Comment by yoyo837** [comment]
https://webpack.js.org/guides/tree-shaking/#conclusion

**Comment by Dolov** [comment]
> 二次封装的lib是否支持treeShaking生效的4个条件？

大佬一句话胜我一天工，明白了，没有声明 sideEffects 
感谢大佬，膜拜

**Comment by yoyo837** [comment]
我也是踩过之后才记忆深刻的，经历总是那么相似且不可避免。😂

**Comment by yoyo837** [comment]
So, let's close this.
