### ISSUE TITLE
Upload组件中fileList中url为null时，页面会报错

### ISSUE THREAD

**Issue by Code-Zelin** [ant-design/ant-design#30062]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/upload/utils.tsx](https://github.com/ant-design/ant-design/blob/master/components/upload/utils.tsx)

### Steps to reproduce
Upload组件的fileList中url传null，页面直接崩溃。

### What is expected?
extname方法可以判断!url情况下，直接return '';避免报错。

### What is actually happening?
实际上传null，会页面崩溃

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome 86.0 |

**Comment by Code-Zelin** [comment]
`const extname = (url: string = '') => {
  // 此处直接判断url是否为不可用的值，如 null，undefined, 空字符串等，直接返回空字符串即可，不需要做后面的操作
  if (!url) return '';
  const temp = url.split('/');
  const filename = temp[temp.length - 1];
  const filenameWithoutSuffix = filename.split(/#|\?/)[0];
  return (/\.[^./\\]*$/.exec(filenameWithoutSuffix) || [''])[0];
};

const isImageFileType = (type: string): boolean => type.indexOf('image/') === 0;

export const isImageUrl = (file: UploadFile): boolean => {
  if (file.type && !file.thumbUrl) {
    return isImageFileType(file.type);
  }
  // 这里保险一些，给个默认值空字符串，保证url必定是字符串
  const url: string = (file.thumbUrl || file.url || '') as string;`

代码贴上去了，我新建了个分支，但是无法正常提交，说我没有权限~

**Comment by MrHeer** [comment]
@Code-Zelin 你先 `fork` 到自己的仓库，然后再给 `ant-design` PR。可以参考[贡献指南](https://ant.design/docs/react/contributing-cn)
