### ISSUE TITLE
Input.TextArea的maxLength和countFormatter失效

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#30066]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-drake-nvlj4?file=/src/App.js:368-379)

### Steps to reproduce
通过重现链接可以直接演示操作

### What is expected?
1. 可以限制输入框的输入长度，我应该怎么做？
2. countFormatter props如何正确的使用？

### What is actually happening?
1. 在受控模式下无法限制输入
2.countFormatter按照文档的调用方式不生效

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 17.0.2 |
| System | macOS 11.2.3 (20D91) |
| Browser | 版本 89.0.4389.114（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
`countFormatter` 是文档错误，应该是 `showCount.formatter`。受控问题我修一下。

**Comment by qiaodaima** [comment]
我看`master`已经有`commit`了，是需要等打一个`tag`发个版本才可以使用是么？

**Comment by yoyo837** [comment]
等周日或者周一
