### ISSUE TITLE
 antd还没更新依赖 rc-util, 导致IE浏览器访问不了

### ISSUE THREAD

**Issue by Quanzhitong** [ant-design/ant-design#30078]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
1、把antd clone到本地
2、启动项目
3、使用IE浏览器访问

### What is expected?
在IE正常访问

### What is actually happening?
控制台报错

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.12.0 |
| System | mac |
| Browser | ie11 |

**Comment by Quanzhitong** [comment]
IE抛错截图
![image](https://user-images.githubusercontent.com/41983846/114162706-f10a7480-995b-11eb-85ed-aabd6e18974e.png)

临时解决方案, 打补丁,
期望解决方案: 尽快将rc-util升级到5.9.8版本

**Comment by xrkffgg** [comment]
删了 lock ，重新安装
antd 周末发版 会自动读最新 rc-util 版本

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/30074

**Comment by Quanzhitong** [comment]
那下周升级再下掉补丁了
 #30074 也是我提的, 被机器人打invalid了, 所以又按规范提了个30078...

**Comment by yoyo837** [comment]
重新安装就解决了

**Comment by xrkffgg** [comment]
^ 这个符号 会同步到 最新的 5.x 版本，所以 5.9.x 不用更新，就算 5.100 都支持的

**Comment by Quanzhitong** [comment]
对对..是的. ☕️☕️
