### ISSUE TITLE
Table表头使用position: sticky悬浮时，当上方有文字时表头底部会露出黑线

### ISSUE THREAD

**Issue by workermx** [ant-design/ant-design#30079]
![问题截图](https://user-images.githubusercontent.com/22365128/114167825-071b3380-9962-11eb-82ba-38df4b3a1ce7.png)
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudinglie-antd4150-forked-5h9ft?file=/index.js)

### Steps to reproduce
刷新界面后会出现

### What is expected?
表头底部不带黑线

### What is actually happening?
表头底部有黑线

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | react |
| System | windows10 |
| Browser | Google Chrome 89.0.4389.90 |

**Comment by afc163** [comment]
Chrome 渲染问题，没啥好办法。
