### ISSUE TITLE
Unnecessary image FileList appearing 

### ISSUE THREAD

**Issue by NishargShah** [ant-design/ant-design#30080]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-jepsen-4o5ih?file=/src/App.js:1851-1857)

### Steps to reproduce
1. Open the codesandbox URL
2. You will see the unnecessary image file list

### What is expected?
Only coded input image URLs should appear

### What is actually happening?
Extra 2 images are appearing along with input images

![image](https://user-images.githubusercontent.com/35843261/114170938-41300980-9951-11eb-9650-78ed651f504e.png)

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 17 |
| System | Ubuntu 20.04 LTS |
| Browser | Chrome 89 |

**Comment by jameslahm** [comment]
This may be caused by that `file` in `fileList` does not get `uid` at first.

**Comment by jameslahm** [comment]
This may be caused by that the `file` in `fileList` does not get `uid` at first, which will cause key is undefined in CSSMotionList and other trouble in update.

**Comment by NishargShah** [comment]
I am glad that I found a small bug in `ant.design`.

can you please tell me that, after your pull request will merge, is it immediately available in `npm` or it will release after some time with the proper version?
