### ISSUE TITLE
Hiding a status badge (e.g. warning) shows in red before hiding

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ant-design/ant-design#30088]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-ant-design-demo-forked-9jvfj?file=/index.js)

### Steps to reproduce
Create a badge like this:
`<Badge status={this.state.show ? "warning" : undefined}>`

### What is expected?
The badge can be hidden and shown by changing this.state.show, without artifacts.

### What is actually happening?
The badge becomes red just before hiding

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome 89 |

---
![WqhL0uslPG](https://user-images.githubusercontent.com/5781692/114282293-a49e6200-9a4b-11eb-96d3-bf948ab18e00.gif)

Maybe there's another way to do that, if so, please tell me and document it. Thanks.

**Comment by yoyo837** [comment]
reopen by #30277
