### ISSUE TITLE
table虚拟列表能出一个整合在组件里面，像tree组件一样，省得用的人写一堆代码。

### ISSUE THREAD

**Issue by mar105** [ant-design/ant-design#30089]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table虚拟列表能出一个整合在组件里面，像tree组件一样，省得用的人写一堆代码。我们这种新手，又想要功能，又不怎么会写的怎么办。。。。
能整合在一起，来个属性是否开启即可，用了虚拟列表，其他功能展示头疼。

### What does the proposed API look like?
一个属性就能控制。或者最好直接渲染速度快了就行，本就是提升速度的方式。

**Comment by afc163** [comment]
Duplicate of #20339
