### ISSUE TITLE
antd4.0和3.0可以同时在项目中使用吗？

### ISSUE THREAD

**Issue by liushuai512** [ant-design/ant-design#30094]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd3.0中的日期和时间可以分开选择，但是在4.0中这个功能不支持是为什么呢？

### What does the proposed API look like?
现在项目中需要这样的一个功能，不知道这个功能在4.0中，我需要怎样做呢？在项目组件中也不能单独指定引入3.0，所以我想这个问题能不能帮忙解决一下呢？谢谢

**Comment by afc163** [comment]
不推荐这么使用。

**Comment by liushuai512** [comment]
https://segmentfault.com/img/bVcRbCm
那向这样的UI在4.0找不到，有什么备用方案吗？

**Comment by liushuai512** [comment]
> 不推荐这么使用。

https://segmentfault.com/img/bVcRbCm
那向这样的UI在4.0找到，有什么备用方案吗？
