### ISSUE TITLE
onChange not firing when InputNumber changes

### ISSUE THREAD

**Issue by steve-cahn** [ant-design/ant-design#30096]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-http-zq0ue?file=/src/App.js)

### Steps to reproduce
Type a number into the input and press the backspace button to remove it.

### What is expected?
The onChange method should get called when the input is empty due to a backspace

### What is actually happening?
The onchange method is not being called

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.2 |
| System | Mac os |
| Browser | Chrome |

**Comment by MinzChen** [comment]
Should I try to fix the InputNumber here in ant-design or the 'rc-input-number' from React-Component?

**Comment by jueinin** [comment]
> Should I try to fix the InputNumber here in ant-design or the 'rc-input-number' from React-Component?

maybe both.start with rc-input-number

**Comment by MinzChen** [comment]
#30309

**Comment by zombieJ** [comment]
Found that InputNumber is design to get `null` when `onBlur` for user keep empty string. Bump `rc-input-number` with minor version in case breaking change.

ref #13896
