### ISSUE TITLE
Table `expandIconColumnIndex` cannot be used alone

### ISSUE THREAD

**Issue by piecego** [ant-design/ant-design#30104]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shuxingshujuzhanshi-antd4151-forked-zdufj?file=/index.js:2597-2618)

### Steps to reproduce
when `Table` `rowSelection` is deleted, the table tree disappear

### What is expected?
Table `expandIconColumnIndex` is render normal without `rowSelection`

### What is actually happening?
table tree disappear.

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.1 |
| System | Windows10 |
| Browser | Edge90/Chrome90 |

**Comment by afc163** [comment]
https://codesandbox.io/s/shuxingshujuzhanshi-antd4151-forked-3b58n?file=/index.js

**Comment by piecego** [comment]
oh! so sorry about that, I overlooked this.
