### ISSUE TITLE
tabs center 无效

### ISSUE THREAD

**Issue by zj1024** [ant-design/ant-design#30102]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/4.15.1/components/tabs/style/index.less#L50](https://github.com/ant-design/ant-design/blob/4.15.1/components/tabs/style/index.less#L50)

### Steps to reproduce
新加了flex: 1,导致无法居中

### What is expected?
居中

### What is actually happening?
无法居中

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 16 |
| System | mac |
| Browser | chrome 最新版 |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/29983

**Comment by kerm1it** [comment]
@zj1024 给个复现链接，https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js

我试了官网的例子是居中的，不知道你说的没居中指的是？
