### ISSUE TITLE
Cascader onMouseEnter onMouseLeave fired incorrectly

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#30105]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-cascader-mouse-enter-leave-issue-0kpmg)

### Steps to reproduce
Move mouse onto the `Cascader`.

### What is expected?
Mouse enter event is fired once.

### What is actually happening?
Mouse enter event is fired twice, then leave event is fired once.

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17 |
| System | MacOS |
| Browser | Chrome 89 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-cascader-mouse-enter-leave-issue-forked-snduk?file=/src/index.js

**Comment by panlina** [comment]
> https://codesandbox.io/s/antd-cascader-mouse-enter-leave-issue-forked-snduk?file=/src/index.js

So it's also emitting mouse events of the input element? I think it's more reasonable to only emit events of the root element. Is it intended?
