### ISSUE TITLE
Modal component incorrect calculate scrollBarSize 

### ISSUE THREAD

**Issue by PavelRazumov** [ant-design/ant-design#30112]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal/#API](https://ant.design/components/modal/#API)

### Steps to reproduce
- Open modal component
- Clik open modal
- Open DevTool find body in DOM (on Desktop view)
- Incorrect width: calc(100% - some px)

### What is expected?
expected width = 100%, we use browser scroll, but we have got width: (100% - 15px)

### What is actually happening?
Actually width on body change on 15px

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React |  "react": "^17.0.1", |
| System | Windows |
| Browser |  any |

**Comment by afc163** [comment]
It is by designed.

**Comment by PavelRazumov** [comment]
I don’t understand, why body change width after open modal component?

**Comment by PavelRazumov** [comment]
Why scroll bar size have width 15px, if I use browser scroll? I expected scrollbar size 0px
