### ISSUE TITLE
Webpack build error after less package upgrade

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#30113]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
(Can't reproduce)

### Steps to reproduce
Upgrade less package to 4.0.0.
Webpack build throws error

### What is expected?
Build error should not happen

### What is actually happening?
I too have the same issue. Details below:
I was on less 3.11.1, after I upgraded to 4.x.x, ants build fails for less.

ERROR in ./node_modules/antd/lib/alert/style/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

```
position: absolute;
top: 8px   @font-size-base * @line-height-base / 2 - @font-size-base / 2;
^
```
Operation on an invalid type
Error in D:_Norma_Learning\r2-ui\node_modules\antd\lib\alert\style\index.less (line 29, column 4)
at processResult (D:_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:675:19)
at D:_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:777:5
at D:_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:399:11
at D:_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:251:18
at context.callback (D:_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
at Object.lessLoader (D:_Norma_Learning\r2-ui\node_modules\less-loader\dist\index.js:49:5)
@ ./node_modules/antd/lib/alert/style/index.js 5:0-23
@ ./dev/react/containers/BlueSnap/BlueSnap.js 7:0-30
@ ./dev/react/bundles/bluesnap/Bluesnap.js 26:0-58 43:46-54

ERROR in ./node_modules/antd/lib/dropdown/style/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

```
.@{ant-prefix}-btn > .@{iconfont-css-prefix}-down {
  .iconfont-size-under-12px(10px);
^
```
Error evaluating function unit: the first argument to unit must be a number. Have you forgotten parenthesis?
Error in D:_Norma_Learning\r2-ui\node_modules\antd\lib\dropdown\style\index.less (line 30, column 6)
at processResult (D:_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:675:19)
at D:_Norma_Learning\r2-ui\node_modules\webpack\lib\NormalModule.js:777:5
at D:_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:399:11
at D:_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:251:18
at context.callback (D:_Norma_Learning\r2-ui\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
at Object.lessLoader (D:_Norma_Learning\r2-ui\node_modules\less-loader\dist\index.js:49:5)
@ ./node_modules/antd/lib/dropdown/style/index.js 5:0-23
@ ./node_modules/antd/lib/table/style/index.js 13:0-31
@ ./dev/react/components/checkout/shipping/ShippingRestriction/ShippingRestriction.js 5:0-30
@ ./dev/react/components/checkout/shipping/Shipping.js 49:0-76 623:68-87
@ ./dev/react/containers/Checkout/Checkout.js 75:0-67 2832:42-50
@ ./dev/react/bundles/checkout/Checkout.js 27:0-58 44:46-54

@afc163 , I tried strictMath: false and no luck.

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.x.x |
| System | Windows 10 |
| Browser | All |

**Comment by wulv** [comment]
搞错了吧，说的是less 3.x升级，不是antd 3.x
