### ISSUE TITLE
TextArea controlled with Formik not working with antd 4.15.1

### ISSUE THREAD

**Issue by chemicalkosek** [ant-design/ant-design#30115]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-dirac-tlgjn?file=/src/App.js)

### Steps to reproduce
Write something in TextArea. See it's not working. Revert back to `antd` 4.15. It's working now.

### What is expected?
Can write in TextArea

### What is actually happening?
Can't write in TextArea

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Chrome 89 |

---
I have already posted an issue in `formik-antd` since I'm not sure on which side is the problem.
Looks like there was a change in TextArea in 4.15.1 so probably something in here. (?)
https://github.com/jannikbuschke/formik-antd/issues/182
The Input is imported from `formik-antd` but that's just a wrapper

**Comment by afc163** [comment]
same problem as #30117

**Comment by zombieJ** [comment]
Seems `name` props passed correctly. Could you provide an reproduce that not wrap with Formik?

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/30124
