### ISSUE TITLE
Ant团队能不能出个教程手摸手搭建React组件库文档造福社会

### ISSUE THREAD

**Issue by lizuncong** [ant-design/ant-design#30118]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
至少对bisheng的架构设计有个深入理解

### What does the proposed API look like?
让ant重度用户能够深入去理解antd优秀的文档构建过程，个人表示很有兴趣

**Comment by yoyo837** [comment]
bug一堆都处理不过来，怎会优先考虑这个事情？

**Comment by lizuncong** [comment]
@yoyo837 我可以帮忙改bug的，big brother

**Comment by yoyo837** [comment]
欢迎，目前500+

**Comment by lizuncong** [comment]
@yoyo837 改完能直接进antd吗

**Comment by yoyo837** [comment]
关于此，你自行和Owner沟通吧。

**Comment by lizuncong** [comment]
bug小问题，antd这个组件库文档感觉好灵活啊，比storybook好多了。bisheng一缺少文档，二缺少实现的思路文档，想学习参考的

**Comment by xrkffgg** [comment]
> @yoyo837 改完能直接进antd吗

500+ 都能改完，真强

**Comment by yoyo837** [comment]
> bug小问题，antd这个组件库文档感觉好灵活啊，比storybook好多了。bisheng一缺少文档，二缺少实现的思路文档，想学习参考的

https://github.com/benjycui/bisheng 也有几十+的bug，你可以去贡献下，在贡献中学习并最终获得你想要的。

**Comment by xrkffgg** [comment]
[dumi](https://github.com/umijs/dumi) 也不错哦~

**Comment by lizuncong** [comment]
@yoyo837 洒洒水的事情，下次一定

**Comment by lizuncong** [comment]
@xrkffgg 我觉得bisheng比较强

**Comment by afc163** [comment]
这个社区还挺多的，我们就不狗尾续貂了。另外，推荐用 https://d.umijs.org/ 。

https://juejin.cn/post/6844904068431740936
https://segmentfault.com/a/1190000021663334
