### ISSUE TITLE
Height of InputNumber inside Form.Item becomes 2px in mobile screen size

### ISSUE THREAD

**Issue by jeffsuto** [ant-design/ant-design#30123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kdz76?file=/index.js)

### Steps to reproduce
```javascript
<Form>
      <Form.Item name="creator_nik" label="NIK" rules={[ { required: true } ]}>
            <InputNumber /> // in mobile screen size on chrome, it shows input number with height 2px
      </Form.Item>
</Form>
```

### What is expected?
Input number run properly in every screen size

### What is actually happening?
When i open in chrome browser with mobile screen size, the height of InputNumber is 2px. I don't know why it could be happened. Because, if i open in dekstop screen size or with safari browser even though i use mobile screen size, it shows properly

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.1 |
| System | MacOs BigSur Version 11.2.3 (20D91) |
| Browser | Chrome Version 89.0.4389.114 |

**Comment by jeffsuto** [comment]
![image](https://user-images.githubusercontent.com/39300886/114504217-ba34a700-9c58-11eb-97db-73d72215dd4c.png)
This is the screenshot

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/114566118-8bdcb900-9ca4-11eb-8ca2-bcf022968f45.png">
