### ISSUE TITLE
Table expandedRowClassName not called

### ISSUE THREAD

**Issue by mboettcher** [ant-design/ant-design#30125]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-expandedrowclassname-not-called-vgzh5?file=/index.js)

### Steps to reproduce
Create table with `expandable` => `expandedRowClassName`.

```
 <Table
      dataSource={...}
      columns={...}
      expandable={{
        expandedRowClassName: (record, index, indent) => {
          console.log("call expandedRowClassName", record, index, indent);
          return "myspecialclassname";
        }
      }}
    />
```

### What is expected?
`expandedRowClassName` should be called and the returned string should be applied as classname of the `tr`

### What is actually happening?
`expandedRowClassName` is not called.

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.1 |
| System | mac os |
| Browser | Chrome 89 |

**Comment by afc163** [comment]
`expandedRowClassName` is used for `expandedRowRender`.

https://codesandbox.io/s/antd-expandedrowclassname-not-called-forked-7env4?file=/index.js

**Comment by mboettcher** [comment]
Thanks @afc163 for the fast reply. 

I think it's not clear in the documentation that it can only be used for `expandedRowRender` since others like `onExpand` or `expandIconColumnIndex` apply for tree data as well. Also, I do not see the reason, why it should be limited to `expandedRowRender`.

If you agree that this should not be limited to `expandedRowRender` I could create a feature request, or, if I have some spare time, try to create a pull request for it.

**Comment by afc163** [comment]
@mboettcher This feature request is welcome~

**Comment by afc163** [comment]
ping @mboettcher

**Comment by mboettcher** [comment]
Create a feature request https://github.com/ant-design/ant-design/issues/30180. hope this is the expected process.

**Comment by afc163** [comment]
trace #30180
