### ISSUE TITLE
版本 4.15.1 Tabs 居中出错

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#30131]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/juzhong-antd4151-forked-xm6pd?file=/index.js)

### Steps to reproduce
直接修改到 4.15.1 就能看到

### What is expected?
居中生效

### What is actually happening?
现在居中不生效

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/30106
