### ISSUE TITLE
RangePicker 的返回今天  按钮 没用啊

### ISSUE THREAD

**Issue by yuxuan1125** [ant-design/ant-design#3013]
#### 本地环境

- antd 版本:1.11.0
- 操作系统及其版本：windows7
- 浏览器及其版本 Chrome

#### 你做了什么？

正常 引用   官网上的例子  都不能实现

#### 你期待的结果是：

能够返回正常的日期 或者 去掉这个功能

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2650
