### ISSUE TITLE
TreeSelect disabled node doesn't show checkmark in checkbox even if it is one of the checked values

### ISSUE THREAD

**Issue by nora-white** [ant-design/ant-design#30143]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/checkable-antd4151-forked-41yoj)

### Steps to reproduce
1. Open the CodeSandbox for the TreeSelect Checkable example.
2. `Child Node 1` is the currently selected value. It has a checkmark in it to show that it is checked.
3. Add `disabled: true` to the `treeData` for `Child Node 1.
4. The checkbox is now disabled, but it no longer reflects that it is checked. There is now no way to visually represent a disabled & checked checkbox.

### What is expected?
That there is a checkmark inside of the disabled checkbox, just like in Ant Design v3.

### What is actually happening?
The checkbox is now disabled, but it no longer reflects that it is checked. There is now no way to visually represent a disabled & checked checkbox.

![image](https://user-images.githubusercontent.com/15168778/114787458-17098d80-9d3d-11eb-88a7-576f279a39a5.png)

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 16 |
| System | Mac OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
https://ant.design/components/tree/#What-does-disabled-node-work-logic-in-the-tree
