### ISSUE TITLE
Need more variables to style tables

### ISSUE THREAD

**Issue by JESii** [ant-design/ant-design#30141]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Certain aspects of antDesign Tables are not customizable via the existing less variables: header and some cell formatting is not available. For example, I need to style the "thead th" values for font-size, color, line-height, letter-spacing, text-transform. Same for the "tbody td" elements.

### What does the proposed API look like?
@table-header-color: #hhh;
@table-header-font-size: nnpx;
@table-header-line-height: nnpx;
@table-header-letter-spacing: nnpx;
@table-header-text-transform: uppercase;

@table-body-color: #hhh;
@table-body-font-size: nnpx;
@table-body-line-height: nnpx;
@table-body-letter-spacing: nnpx;
@table-body-text-transform: uppercase;

**Comment by afc163** [comment]
We move to CSS-in-JS in antd 5.x
