### ISSUE TITLE
When using the `components` prop for the Table, multiple fixed columns are no longer respected

### ISSUE THREAD

**Issue by nora-white** [ant-design/ant-design#30142]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd4151-forked-bi6mv?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Open the `virtual list` CodeSandbox example from Antd table
2. For column `A`, add `fixed: 'left'`. Attempt to scroll. The A column is fixed as expected.
3. For column `B`, add `fixed: 'left'`. Attempt to scroll. The A column stays fixed until scrolled to B, at which point column A is hidden and column B is now the only fixed column.

### What is expected?
Both columns A and B should remain fixed and visible at all times.
Both columns should have `position: sticky` applied, but column A should have `left: 0px`, and column B should have `left: 150px` (where 150px is the width of column A).

### What is actually happening?
Both columns have `position: sticky; left: 0px;` applied, so column B will always overlap column A once scrolled far enough.

As you can see in this screenshot, table-cell A and table-cell B both have the inline style of `left: 0px;` applied:
![image](https://user-images.githubusercontent.com/15168778/114754159-7d7ab580-9d15-11eb-8297-96cd7d31b7e6.png)

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 16 |
| System | Mac OSX |
| Browser | Chrome |

---
I'm creating a virtual table with row selection functionality (where this checkbox column is fixed), and one additional string column that is also fixed. The column headers of the table are rendered via Antd table, but the body is rendered with react-window like the Antd documentation suggests. When I add rowSelection, the checkbox column is added, but both the checkbox column and the fixed string column are given `left: 0px`, so the 2nd (or last) column always overlaps the checkbox column once I begin to scroll horizontally. I then tried to manually add the checkbox column not using the rowSelection prop, but I encountered the same issue where having more than one fixed column does not work as expected.

**Comment by afc163** [comment]
trace #20339
