### ISSUE TITLE
Select下拉框点开后1秒钟后，滚动条会消失。

### ISSUE THREAD

**Issue by TaurusWood** [ant-design/ant-design#30150]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/#API](https://ant-design.gitee.io/components/select-cn/#API)

### Steps to reproduce
antd 官网 组件库 select组件  大数据demo
1. 点开Ant Design 4.0 100000 Items 这个Select的option

### What is expected?
鼠标悬浮到下拉框上，滚动条出现，或者滚动条一直都在

### What is actually happening?
过一秒，下拉框滚动条消失了，鼠标即便悬浮在options上滚动条也不会出现。

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.8.6 |
| System | mac os 10.14.6 |
| Browser | chrome  79.0.3945.117 |

---
我们测试认为这样可能用户就不知道这个select框可以滚动，我们也不好改源码，所以给你们提一个issue，能不能在下个版本中设计优化下。

**Comment by afc163** [comment]
这是预期行为，一开始滚动条是不出现的，滚动条出现一下也是为了提醒用户有滚动条。
