### ISSUE TITLE
SubMenu can be configured for multiple selection, but closes whenever a single item is clicked.

### ISSUE THREAD

**Issue by reubengt** [ant-design/ant-design#30160]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A `<Menu>` with `<Submenu>` inside can be configured for multiple selection, but the submenu closes every time an item is selected. For multiple selection, this is not ideal, it would be nice to have the option to click and select multiple items at once. I am aware that an inline <Menu> solves this, but I would like to use the vertical menu mode.

### What does the proposed API look like?
```javascript=
<Menu><SubMenu closeOnClick={false}> //menu items</SubMenu></Menu>
```

**Comment by reubengt** [comment]
Attaching a video of what the behaviour is now. Instead of closing the submenu when a menu item is clicked, I would like to be able to select multiple menu items.
https://user-images.githubusercontent.com/42008435/114912810-5b1d9080-9e18-11eb-9e91-c40b5698ce26.mov

**Comment by afc163** [comment]
https://ant.design/components/tree/#What-does-disabled-node-work-logic-in-the-tree

**Comment by afc163** [comment]
SubMenu won't be closed now when has `multiple`. https://codesandbox.io/s/dingbudaohang-antd4161-forked-sj2wp?file=/index.js
