### ISSUE TITLE
The input box using Microsoft Pinyin FROM displays an error

### ISSUE THREAD

**Issue by xiaorunbao** [ant-design/ant-design#30164]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4151-forked-vek64?file=/index.js)

### Steps to reproduce
# 复现步骤
### What is expected?
和其他输入法一样，输入汉字确认后输入框显示输入的汉字

### What is actually happening?
会出现重复的拼音英文 

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.13.1 |
| System | Window |
| Browser | Chrome75 |

**Comment by yoyo837** [comment]
可能有关的 #27748

**Comment by afc163** [comment]
建议封装一个可以正确处理输入法和大写转换状态的 Input（处理 onCompositionEnd），不要直接使用 normlize。

**Comment by andybuibui** [comment]
> 建议封装一个可以正确处理输入法和大写转换状态的 Input（处理 onCompositionEnd），不要直接使用 normlize。

hi， 这种写法确实能解决拼音输入时候转成大写，但是将输入法改成英文模式直接输入的时候，字符又转不了大些了， 请教下如何保持这两种情况下都兼容
