### ISSUE TITLE
<select>modify searchValue not to search

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/ant-design#30168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
<select>modify searchValue, placeholder and searchValue text overlap, and do not open the dropdown, and do not perform the search. Hope to change the searchValue to perform the search directly.

### What does the proposed API look like?
 Hope to change the searchValue to perform the search directly.

![WX20210416-144714](https://user-images.githubusercontent.com/33448924/114983208-e8b5ba80-9ec2-11eb-9552-e338bc26effe.png)

**Comment by BabyFriedCake** [comment]
> Hello @BabyFriedCake. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @BabyFriedCake, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-forked-80roq?file=/index.js

**Comment by afc163** [comment]
Try to control `open` and `onOpenChange`.
