### ISSUE TITLE
FormInstance 期望增加一个获取某字段的初始值，目前只有 resetFields 重置一组字段到到初始值

### ISSUE THREAD

**Issue by SturdyCat** [ant-design/ant-design#30162]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为封装了统一的自定义校验规则，需要通过当字段的当前值是否和初始值相同做一些逻辑判断。

### What does the proposed API look like?
getFieldInitialValue

**Comment by yoyo837** [comment]
初始值有你提供，你为何不知道初始值？

**Comment by SturdyCat** [comment]
@yoyo837 当前操作的页面是可以很轻松的获取初始值，统一封装的自定义函数内就不太方便获取初始值。
```
(form: FormInstance) =>{
validator(rule, value, callback) => {
 // 这里 FormInstance 如果能获取到 初始值，可以很方便的处理某些逻辑
// 比如编辑某个表单，初始值和当前值相同就过滤掉校验
}
});
```

**Comment by yoyo837** [comment]
你可以设计一个回调，初始渲染后回调所有的初始值给上层。
