### ISSUE TITLE
It's not a bug, it's a puzzle for me

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#30161]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/affix/style/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/affix/style/index.tsx)

### Steps to reproduce
有一个小疑问，components 下的组件为什么不直接引用 style 下的样式呢

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by yoyo837** [comment]
可能因为bundle环境是用户自己的，决定不了，而且用户可以使用自定义前缀，那这样，自带的样式引入就毫无用处，只会占大小。

**Comment by Dolov** [comment]
> 可能因为bundle环境是用户自己的，决定不了，而且用户可以使用自定义前缀，那这样，自带的样式引入就毫无用处，只会占大小。

还有一个问题请教一下哈
我们团队内部也封装了一个内部使用的 ui 库，样式就是直接在组件中引用的。
```js
import './style'
```

现在要支持 treeShaking, 所以 package.json 中设置了 
```
"sideEffects": [
    "dist/*",
    "es/**/style/*",
    "lib/**/style/*",
    "*.less"
  ],
```
打包部署后发现样式并没有引入进来，如果样式引用改为
```
import './style/index.less'
```
就有样式了

烦请大佬解惑

**Comment by yoyo837** [comment]
情况一样呀，要么你lib引用了样式，下游项目替lib按自己需要引用了样式。 antd的组件每个都有style文件夹，很多人使用babel-plugin-import来引用less/css

**Comment by yoyo837** [comment]
sideEffects 应该不能帮你做import的行为吧，这个我个人没研究过。

**Comment by Dolov** [comment]
> sideEffects 应该不能帮你做import的行为吧，这个我个人没研究过。

好的，谢谢老哥，我再研究一下哈

**Comment by yoyo837** [comment]
还有就是，sideEffects 虽然不能帮你做import的行为，但是它的逻辑是和import有关的。压根没import的东西，应该是和sideEffects无关的。

**Comment by yoyo837** [comment]
个人见解。

**Comment by afc163** [comment]
引 css 还是 less 需要交由用户做决定。
