### ISSUE TITLE
table组件行hover事件

### ISSUE THREAD

**Issue by ajsdhf** [ant-design/ant-design#3016]
#### 使用table组件

需要实现一个table的column的hover事件和页面的其他元素做互动的交互。

但是看了API并没有发现有类似的功能，求支持

#### 本地环境

- antd 版本: 1.3.0
- 操作系统及其版本：mac os 10.11.6
- 浏览器及其版本: chrome

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/1303

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
