### ISSUE TITLE
Table hover style update

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#30177]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/5378891/115029497-9f805d80-9ef8-11eb-912c-11c3389f29f4.png)

**Comment by afc163** [comment]
https://codepen.io/chriscoyier/pen/wLGDz

**Comment by zombieJ** [comment]
等一等 https://github.com/react-component/table/pull/619 再启动

**Comment by afc163** [comment]
supported in https://github.com/react-component/table/pull/686
