### ISSUE TITLE
can scrollToFirstError trigger after validateFields ?

### ISSUE THREAD

**Issue by xyuanbuilds** [ant-design/ant-design#30174]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when i use validateFields to get values from form, i hope form can trigger scrollInToView.

but scrollToFirstError only trigger when use form.submit.

can add this feature: scrollToFirstError trigger after validateFields ?

or mark this behaviour in FAQ

### What does the proposed API look like?
```
{
    scrollAfterValidate?: boolean
}
```

**Comment by afc163** [comment]
You can use `form.scrollToField()` manually.
