### ISSUE TITLE
Descriptions 建议增加 value 对齐的样式

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#30170]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![QQ浏览器截图20210416151929](https://user-images.githubusercontent.com/3166799/114987506-d427f100-9ec7-11eb-8523-6ed9f87a17d8.png)

**Comment by afc163** [comment]
用 labelStyle 给一个统一固定宽度即可。
