### ISSUE TITLE
加上scroll后Table组件渲染数据出现第一行空白行 ant-table-measure-row

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#30173]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
https://ant.design/components/table-cn/

### What is expected?
不会出现空白行

### What is actually happening?
只要加上scroll={{x:true}}，渲染后表格第一行就会出现了以下空白行tr元素
<tbody>
  <tr aria-hidden="true" class="ant-table-measure-row" style="height:0px;font-size:0px">
      <td style="padding:0px;border:0px;height:0px">
         <div>&nbsp;</div>
      </td>
      .......
  </tr>
</tbody>

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.x |
| System | windows7 |
| Browser | google chrome 89.0.4389.90 |

**Comment by Mathround** [comment]
只要加上scroll={{x:true}}，渲染后表格第一行就会出现了以下空白行tr元素
`
<tbody>
  <tr aria-hidden="true" class="ant-table-measure-row" style="height:0px;font-size:0px">
      <td style="padding:0px;border:0px;height:0px">
         <div>&nbsp;</div>
      </td>
      .......
  </tr>
</tbody>`

**Comment by jameslahm** [comment]
可以提供一个`codesandbox`复现吗？

**Comment by Mathround** [comment]
> 可以提供一个`codesandbox`复现吗？

codesandbox里面的antd版本哪里改呢？直接在package.json里面改？

**Comment by jameslahm** [comment]
左下角依赖列表处应该可以改版本号？

**Comment by talent-go** [comment]
我从3.X的版本升级到4.x之后也出现了这个问题，空白行的class名为.ant-table-measure-row

**Comment by talent-go** [comment]
我设置了scroll{{ y: }},如果取消掉这个属性就不会新增一个空白行

**Comment by kuiGe11** [comment]
加上scroll y后，tbody里会出现一行空白tr，然后table的宽度改变不了了，不会随着页面而伸缩放大，这问题咋解决啊？

**Comment by heping6b** [comment]
先这样处理，后续等官方修复bug吧
.ant-table-tbody {
  position: relative;
  top: -7px; // 这里自己调下
}

**Comment by krcdxnh** [comment]
macos sonoma 14.0系统
Chrome版本 121.0.6167.139（正式版本） (arm64)
antd版本3.x
出现条件：以上版本以及当table设置fixed并且设置scroll y的时候就会在第一行出现间隔导致左右错位。官网页面就会出现bug.
<img width="1242" alt="3F89CA02-AFE4-4215-9F5F-E7E9393BB17A" src="https://github.com/ant-design/ant-design/assets/24219461/4b311cdd-f247-41f8-9dab-156d70ccb331">
