### ISSUE TITLE
[Select][Regression] rc-virtual-list-scrollbar is not removed from DOM (v 4.7.1 and later)

### ISSUE THREAD

**Issue by vict-shevchenko** [ant-design/ant-design#30175]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-471-scroll-susqc)

### Steps to reproduce
prerequisite:
In order for the virtual scrollbar is always displayed add this CSS:
```
/* Always show scroll bar in select dropdown menu */

.ant-select-dropdown:not(.ant-select-dropdown-hidden) .rc-virtual-list-scrollbar {
  display: block !important; /* important to overwrite inline style display: none */
  right: 2px !important; /* look more like native mac os scroll bar */
}
```

1. Have a Select with many elements, so there is a scroll bar
2. Start typing so that there are fewer search results, so (amount of resutls * height of result) is less than max-height of dropdown-list (rc-virtual-list-holder)  

### What is expected?
There are 2 possible solutions:

1. `.rc-virtual-list-scrollbar` element is removed from DOM so there is no scrollbar visible (like it was in Ant 4.7.0 and before)
2. `.rc-virtual-list-scrollbar-thumb` should get `0` height

### What is actually happening?
1. `.rc-virtual-list-scrollbar` element is kept in DOM
2. `.rc-virtual-list-scrollbar-thumb` gets `height` of `128px` which makes it bigger that total `.rc-virtual-list-holder` 

that looks quite confusing

| Environment | Info |
|---|---|
| antd | 4.7.1 |
| React | latest (^16.14.0) |
| System | Mac OS |
| Browser | Chrome |

---
The last version where this behavior worked correctly was 4.7.0 - [4.7.0 example](https://codesandbox.io/s/ant-470-scroll-93mfh)
After 4.7.1 `.rc-virtual-list-scrollbar` is no longer removed. [4.7.1 example](https://codesandbox.io/s/ant-471-scroll-susqc)

I know that there is a possibility to disable virtual scroll and use the native one, but the performance really matters in my case. My list are 2000  items and with virtual scroll, it works really smoothly!

I have tracked this down to `rc-select` that is used under the hood. And I see next behavior:
1. 11.3.3 - `.rc-virtual-list-scrollbar` element is removed from DOM
2. 11.4.0 - `.rc-virtual-list-scrollbar` element is kept in DOM

you can see this [example](https://codesandbox.io/s/rc-select-scroll-4vnzg) (sorry for the ugly layout, just play with library version). But based on [11.3.3 and 11.4.0 diff](https://github.com/react-component/select/compare/v11.3.3...v11.4.0) I can not understand what is causing it.

**Comment by zombieJ** [comment]
Thanks for report.
It's by design. Virtual scrollbar is always used to avoid small size data dynamic change to large size data which jump the scrollbar.

**Comment by vict-shevchenko** [comment]
Hello @zombieJ  and @afc163 , thanks a lot for looking into this ticket. I wonder is there any issue to track "small size data dynamic change to large size data which jump the scrollbar" case? would like to follow it or may be contributing.  

In any case, I think if this case is resolved, users of Antd can display scrollbars in selects.

**Comment by zombieJ** [comment]
Check again. Its bug. Reopen.

**Comment by vict-shevchenko** [comment]
Hello @zombieJ ! Thanks a lot for such a quick improvement for my requiest. 

As I understood, I can now apply custom css to:

```css
.rc-virtual-list-scrollbar-show {
    display: block !important;
}
```

So scrollbar is always visible, and if a number of rows goes less than list height, class is removed and the scrollbar becomes invisible due to inline `display: none`. Very elegant solution! I Will test it!

Thanks a lot!
