### ISSUE TITLE
hi , 使用了checkbox组件，结果出现了两个勾选框？

### ISSUE THREAD

**Issue by hust419** [ant-design/ant-design#3018]
![checkbox](https://cloud.githubusercontent.com/assets/3736029/18430638/f370642a-790b-11e6-87af-5be69ec09a4a.png)

**Comment by sean-lin** [comment]
最好贴出 JSX 代码

**Comment by benjycui** [comment]
样式问题。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
报告问题按格式来。
