### ISSUE TITLE
Table: Use expandedRowClassName also for tree data

### ISSUE THREAD

**Issue by mboettcher** [ant-design/ant-design#30180]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`expandedRowClassName` in `expandable` is currently only used for `expandedRowRender`. However, it would be great if it would be used for tree data as well since other props like `onExpand` or `expandIconColumnIndex` apply for tree data as well. 

### What does the proposed API look like?
API stays the same.

Example that should work AFTER the feature was implemented: https://codesandbox.io/s/antd-expandedrowclassname-not-called-vgzh5?file=/index.js

**Comment by afc163** [comment]
Closing for no response.

**Comment by igorMIA** [comment]
Still waiting for this feature :)

**Comment by lotfi-gamma** [comment]
this feature is really important and does not yet work in the latest version
