### ISSUE TITLE
File Selector does not appear when clicking on Upload component on macOS Big Sur (version 11.2.3) using Chrome

### ISSUE THREAD

**Issue by AdrianaQyL** [ant-design/ant-design#30193]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://nnh0z.csb.app/](https://nnh0z.csb.app/)

### Steps to reproduce
Click on the upload button, or click any Upload component in the examples at https://ant.design/components/upload/ in Chrome (version 90.0.4430.72), using a macOS Big Sur (version 11.2.3) computer.

### What is expected?
A file selector should pop up when the user clicks on the Upload component.

### What is actually happening?
Nothing happens after clicking on the component.

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.2 |
| System | macOS Big Sur (version 11.2.3) |
| Browser | Chrome (version 90.0.4430.72) |

---
It was ok when the system was macOS Catalina. It also works well on another computer with a different system but the same version Chrome. This issue doesn't happen in Safari. Restart the computer (or browser) does not solve the problem.

**Comment by AleksanderKoko** [comment]
I think this is a problem related to `rc-upload` package as `antd` is using that package to handle uploads. Tried the `rc-upload` demo on Firefox, it works, on Chrome Mac OS it doesn't. It seems to mirror the tests on `antd` as well.

**Comment by AleksanderKoko** [comment]
After some testing, on Chrome Mac OS intel works as expected. Chrome Dev Mac OS M1 works. I don't think this is related to `atnd` or `rc-upload` as other upload methods are broken on my Chrome installation as well.

**Comment by sweetyangtian** [comment]
+1

**Comment by sweetyangtian** [comment]
+1

**Comment by sweetyangtian** [comment]
+1

 macOS Big Sur (version 11.5.2)；Chrome (version 95.0.4638.69)；antd (4.16.13、3.26.16)

**Comment by afc163** [comment]
@sweetyangtian Could you try `<input type"file" />`.

**Comment by alexMotomtech** [comment]
I tried to do that. It wasn't a problem with ant or rc-upload. It was a specific version of Chrome on M1. After updating the browser to the latest version it worked. @afc163
