### ISSUE TITLE
Following Typescript setup instructions results in CSS error

### ISSUE THREAD

**Issue by minism** [ant-design/ant-design#30190]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-in-typescript](https://ant.design/docs/react/use-in-typescript)

### Steps to reproduce
Following the guide at https://ant.design/docs/react/use-in-typescript with a blank repository and the above Antd/React versions.

Once I get to the CSS import step:

Adding "@import '~antd/dist/antd.css';" to the top of App.css

I get a compilation error.

### What is expected?
CSS from tutorial should compile.

### What is actually happening?
Failed to compile error:

    ./src/App.tsx
    SyntaxError: /Users/josh/dev/web/gear/src/App.tsx: import can only be used in import() or import.meta (4:1)
    
      2 | import { Button } from "antd";
      3 | import "./App.css";
    > 4 | @import '~antd/dist/antd.css';

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.2 |
| System | OSX |
| Browser | Chrome |

**Comment by jameslahm** [comment]
![image](https://user-images.githubusercontent.com/43805318/115107459-88477b80-9f9d-11eb-8b2b-9476f95191ee.png)
Please add `@import '~antd/dist/antd.css'` in your `App.css` or add `import '~antd/dist/antd.css'` in your `App.tsx`.

**Comment by minism** [comment]
> ![image](https://user-images.githubusercontent.com/43805318/115107459-88477b80-9f9d-11eb-8b2b-9476f95191ee.png)
> Please add `@import '~antd/dist/antd.css'` in your `App.css` or add `import '~antd/dist/antd.css'` in your `App.tsx`.

*slinks away in embrassment*
