### ISSUE TITLE
当一个FormItem包含两个需要validate的组件时，如果后一个组件先校验，就会出现错误提示信息没有变成红色的问题，如果前面的一个先校验就没有问题

### ISSUE THREAD

**Issue by yichengjie** [ant-design/ant-design#3019]
#### 本地环境

- antd 版本: 最新版的antd 1.11.0
- 操作系统及其版本： win7
- 浏览器及其版本: chrome 52

#### 你做了什么？

引入 antd 了 Form ，FormItem

#### 你期待的结果是：

验证错误信息提示成红色的

#### 实际上的结果：

验证提示信息是灰色的

#### 可重现的在线演示

如果改变第一个输入框的值后，错误信息会变成红色，如果仅仅是第一个输入框验证则会出现以下bug，灰色错误提示信息出现。

![image](https://cloud.githubusercontent.com/assets/11714828/18431331/07b0d1ce-790f-11e6-92dd-7b5c3feae179.png)

![image](https://cloud.githubusercontent.com/assets/11714828/18431350/1d4b2462-790f-11e6-9dc6-601756975671.png)

**Comment by benjycui** [comment]
`Form.Item` 自动生成校验信息的行为在只有一个 child 时才是正常的，见：http://ant.design/components/form/#Form.Item

多个控件参考 http://ant.design/components/form/#components-form-demo-validate-static

**Comment by yichengjie** [comment]
非常感谢，问题按照你说的方式完美解决
