### ISSUE TITLE
Tooltip causes button to be misplaced

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ant-design/ant-design#30198]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-k195k)

### Steps to reproduce
Notice that in the example, the buttons are not aligned, but they become aligned if Tooltip is removed.
I could reproduce it if I use the following CSS:
```
.App {
  display: flex;
  font-size: 26px;
}
```

### What is expected?
Adding Tooltip doesn't affect layout and has no side effects until hovered.

### What is actually happening?
Adding Tooltip affects layout and has side effects.

![image](https://user-images.githubusercontent.com/5781692/115150952-67515a00-a073-11eb-8004-b1608d2ce34b.png)

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 89 |

**Comment by afc163** [comment]
You can use Space to align items in this case: https://codesandbox.io/s/antd-reproduction-template-forked-ip6gz?file=/index.js and

**Comment by justanotheranonymoususer** [comment]
But then it becomes different. I want it to be as if Tooltip doesn't exist.
