### ISSUE TITLE
Tooltip don't work on the disabled Input 

### ISSUE THREAD

**Issue by LullabyLY** [ant-design/ant-design#30191]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tooltip don't work on the disabled Input 

I want to add a prompt to a disabled input , but the tooltip does not support it. How do I do this?

**Comment by jameslahm** [comment]
Could you provide a `codesandbox` reproduce?

**Comment by LullabyLY** [comment]
@jameslahm
 https://codesandbox.io/s/shurushigeshihuazhanshi-antd4151-forked-8umtb?file=/index.js

**Comment by jameslahm** [comment]
You could wrap `input` with a element, such as `div`, [demo here](https://codesandbox.io/s/shurushigeshihuazhanshi-antd4151-forked-ozsqw?file=/index.js)

**Comment by afc163** [comment]
https://github.com/react-component/tooltip/issues/18#issuecomment-140078802

**Comment by LullabyLY** [comment]
@jameslahm thanks

**Comment by imbasri** [comment]
@jameslahm thanks solved 😸

**Comment by shirleying-jing** [comment]
> You could wrap `input` with a element, such as `div`, [demo here](https://codesandbox.io/s/shurushigeshihuazhanshi-antd4151-forked-ozsqw?file=/index.js)

thanks really helpful

**Comment by Prithviraj-kf** [comment]
> You could wrap `input` with a element, such as `div`, [demo here](https://codesandbox.io/s/shurushigeshihuazhanshi-antd4151-forked-ozsqw?file=/index.js)

Thanks for this. 🤝
