### ISSUE TITLE
基于Tab组件的TabPane二次封装，这个TabPane不会渲染出来，必现

### ISSUE THREAD

**Issue by wuzhong1030** [ant-design/ant-design#30201]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-chandrasekhar-hry3d)

### Steps to reproduce
对TabPane进行二次封装，但是这个二次封装后的TabPane不能渲染出来，提供了codesandbox，稳定复现。

### What is expected?
应该能够被正常渲染出来

### What is actually happening?
目前看来不会正常渲染出来

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | MacBook Pro 10.15.4  |
| Browser | Version 89.0.4389.114 (Official Build) (x86_64) |

**Comment by kerm1it** [comment]
ref: https://github.com/ant-design/ant-design/issues/4853
