### ISSUE TITLE
Image组件的style作用域在内层，外层控制不到

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#30208]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Image 的默认样式是行内的，但是有些场景是需要块级样式，
目前 
```js
<Image
   style={{
      // ....  这些样式只是处理 img标签自身， 包裹层没处理
    }}
>
```
虽然我有其他方式可以避免这个问题，
- 比如继承修改样式
- 自己外层包一个`div`
不知是否考虑增加`props`可以控制外层样式

### What does the proposed API look like?
像是 `Botton`组件 控制行内和块的 `props`   ` block`

```
<Image block /> 
```

**Comment by shaodahong** [comment]
Use `wrapperClassName` can be controll.

**Comment by qiaodaima** [comment]
@afc163 @shaodahong 
感觉这个不应该被关闭。

- 首先呢这个问题，如标题所述，因为组件的`style`一般是控制包裹层容器，但是Image有点特殊，是控制内层，难免有些误解。
- 其次这也是一个`help wanted`,  因为`Button`组件有提供行内和块，不知`Image`是否考虑

上述两点虽然都可以通过 `组件的类名`去修改来实现，
我的意思是是否考虑`props`的形式来提供

**Comment by shaodahong** [comment]
> @afc163 @shaodahong
> 感觉这个不应该被关闭。
> 
> * 首先呢这个问题，如标题所述，因为组件的`style`一般是控制包裹层容器，但是Image有点特殊，是控制内层，难免有些误解。
> * 其次这也是一个`help wanted`,  因为`Button`组件有提供行内和块，不知`Image`是否考虑
> 
> 上述两点虽然都可以通过 `组件的类名`去修改来实现，
> 我的意思是是否考虑`props`的形式来提供

`wrapperStyle` ?

**Comment by qiaodaima** [comment]
> > @afc163 @shaodahong
> > 感觉这个不应该被关闭。
> > 
> > * 首先呢这个问题，如标题所述，因为组件的`style`一般是控制包裹层容器，但是Image有点特殊，是控制内层，难免有些误解。
> > * 其次这也是一个`help wanted`,  因为`Button`组件有提供行内和块，不知`Image`是否考虑
> > 
> > 上述两点虽然都可以通过 `组件的类名`去修改来实现，
> > 我的意思是是否考虑`props`的形式来提供
> 
> `wrapperStyle` ?

说下我的个人看法：
- Image 的 style 控制内层，这种行为貌似没有和其他组件行为保持一致，感觉这是一个不好的地方，感觉文档最好是说明一下。
- 如果直接把style提升到外层，这样会影响已经在使用的用户。
- 行内和块 这个应该很好实现

**Comment by shaodahong** [comment]
这是一个层的概念，Image 组件虽然是包了一层，但是不想在设置 style 的有一个心理负担，比如 `objectFit` 属性，至于行为保持一致这个确实会造成一个误扰，之后在文档说明一下
