### ISSUE TITLE
Button 添加 href 被 disable 之后，依然可以跳转到新的 url

### ISSUE THREAD

**Issue by fubd** [ant-design/ant-design#30207]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/anniuleixing-antd4152-forked-87hil?file=/index.js)

### Steps to reproduce
1. Button 组件同时添加 disable 和 href 属性

### What is expected?
被禁止跳转

### What is actually happening?
跳转成功

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | mac os v11.1 |
| Browser | Chrome 88.0.4324.150 |

**Comment by afc163** [comment]
原来这行代码是有用的：https://github.com/ant-design/ant-design/pull/30197

**Comment by yoyo837** [comment]
换方案 😂

**Comment by jameslahm** [comment]
感觉可以revert #30197，`cursor`的样式交由用户控制？ :rofl:
