### ISSUE TITLE
ConfigProvider的prefixCls属性对Message组件不生效

### ISSUE THREAD

**Issue by jueinin** [ant-design/ant-design#30206]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/putongtishi-antd4152-forked-o8li8?file=/index.js)

### Steps to reproduce
点击按钮  f12查看message样式名字为ant-message而不是antd-message

### What is expected?
antd-message

### What is actually happening?
ant-message

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17 |
| System | windows10 |
| Browser | chrome 89 |

---
我们做single-spa微服务，需要用classPrefix去区分两套antd的子项目。遇到这个提示弹窗不会自动消失的问题。看了下类名不对。可能是className的问题，导致它没法自动消失

**Comment by afc163** [comment]
See https://ant.design/components/message-cn/#FAQ

**Comment by birdycn** [comment]
> See https://ant.design/components/message-cn/#FAQ

没看懂这个跟prefixCls怎么结合。。

**Comment by birdycn** [comment]
请问楼主解决了吗，我也是修改了全局配置的类名前缀然后弹窗不消失

**Comment by birdycn** [comment]
请问解决了吗？我的也是不会消失，但是会触发onClose，在onClose可以调用message.destroy()，但是不会自动消失，这是什么原因呢

**Comment by jueinin** [comment]
> 请问解决了吗？我的也是不会消失，但是会触发onClose，在onClose可以调用message.destroy()，但是不会自动消失，这是什么原因呢

解决了，调用ConfigProvider的静态方法就行了。详细代码我晚点贴出来

**Comment by haoyinag** [comment]
@jueinin 代码是啥  我也遇到类似问题在antd-pro

**Comment by jueinin** [comment]
@haoyinag 
```js
ConfigProvider.config({
  prefixCls: 'antd',
});
```
配合
```js
<ConfigProvider prefixCls="antd"></ConfigProvider>
```
就可以了，他们message估计不走这个context的prefixCls，要用上面的代码再配置一遍。

**Comment by swiftwind0405** [comment]
> @haoyinag
> 
> ```js
> ConfigProvider.config({
>   prefixCls: 'antd',
> });
> ```
> 
> 配合
> 
> ```js
> <ConfigProvider prefixCls="antd"></ConfigProvider>
> ```
> 
> 就可以了，他们message估计不走这个context的prefixCls，要用上面的代码再配置一遍。

感谢，官方文档没看懂一开始
