### ISSUE TITLE
Submenu padding wrong when inside of itemgroup

### ISSUE THREAD

**Issue by sebakerckhof** [ant-design/ant-design#30217]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dgs9k)

### Steps to reproduce
Have a submenu inside an itemgroup inside a menu on an element without specified width (and not within an element with default 100% width)

### What is expected?
Padding of the submenu title should be sufficient for it not to collapse with the arrow

### What is actually happening?
The padding of the submenu is overwritten by that of the itemgroup, which makes that the arrow collapses with the title of the submenu

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 16.14.0 |
| System | Ubuntu 20.10 |
| Browser | Chrome 89 |

**Comment by afc163** [comment]
Did you mean this?

<img width="632" alt="图片" src="https://user-images.githubusercontent.com/507615/115330677-24a09680-a1c7-11eb-9ac5-72a4fc5bbc3f.png">

**Comment by sebakerckhof** [comment]
@afc163 Seems like something went wrong in my example, I updated it.

This is what I mean (the arrow colliding with the labels)
![image](https://user-images.githubusercontent.com/88471/115359013-87416480-a1be-11eb-8d7f-c9efd72adaa7.png)
