### ISSUE TITLE
form.setFieldsValue not set empty object property field

### ISSUE THREAD

**Issue by Ragnaxander** [ant-design/ant-design#30212]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-luqxo)

### Steps to reproduce
* click button "user 2"
* click button "user 1"

### What is expected?
properties field in user 1 should be empty

### What is actually happening?
properties field from user 2 not changes when switch to user 1

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | react latest |
| System | mac os |
| Browser | chrome latest |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28314#issuecomment-744253708

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-mghsg?file=/App.jsx

**Comment by Ragnaxander** [comment]
thank u
