### ISSUE TITLE
The enterButton prop of Input.Search is invalid

### ISSUE THREAD

**Issue by 17forever** [ant-design/ant-design#30214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-glitter-213iu?file=/src/App.js)

### Steps to reproduce
enterButton 设置为 false

### What is expected?
enterButton 设置为 false 时隐藏

### What is actually happening?
enterButton 设置为 false 时依旧显示

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chrome latest |

**Comment by jameslahm** [comment]
> enterButton 设置为 false 时隐藏

这个指隐藏什么？

**Comment by 17forever** [comment]
> > enterButton 设置为 false 时隐藏
> 
> 这个指隐藏什么？

是我理解错了，我以为右边的搜索按钮是 enterButton
![image](https://user-images.githubusercontent.com/11835233/115227943-b8308380-a143-11eb-8525-79ceaf10c4cf.png)

**Comment by afc163** [comment]
```jsx
<Input.Search  enterButton />
```

<img width="246" alt="图片" src="https://user-images.githubusercontent.com/507615/115228662-a13e6100-a144-11eb-8b1a-4f01f879fed1.png">

```jsx
<Input.Search  enterButton={false} />
```

<img width="240" alt="图片" src="https://user-images.githubusercontent.com/507615/115228731-b915e500-a144-11eb-9ecc-ae13a2d0fb72.png">

```jsx
<Input />
```

<img width="240" alt="图片" src="https://user-images.githubusercontent.com/507615/115228808-cdf27880-a144-11eb-9c8c-2145665762cd.png">
