### ISSUE TITLE
Avatar image remove button

### ISSUE THREAD

**Issue by codetestmg** [ant-design/ant-design#30219]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0ilo7)

### Steps to reproduce
https://ant.design/components/upload/#components-upload-demo-avatar

### What is expected?
if Avatar image has remove icon image then it will be helpful if user doesn't want to upload selected image and wants keep no image .At present user need to refresh page

### What is actually happening?
Avatar image upload doesn't have  remove button or icon option .if we add showUploadList removeicon true then it will create a list .

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | ^17.0.2 |
| System | windows 8.1 |
| Browser | chrome |

---
thanks for the library. Great effort

**Comment by afc163** [comment]
```diff
{imageUrl ? (
- <img src={imageUrl} alt="avatar" style={{ width: '100%' }} />
+ <>
+   <img src={imageUrl} alt="avatar" style={{ width: '100%' }} />
+   <button onClick={setImageUrl(null)}>remove image</button>
+ </>
): uploadButton}
```

It is a demo, you can add remove button as you need.
