### ISSUE TITLE
Select Component Without Type hint in vscode using lowerer version(less than 3.8) of typescript

### ISSUE THREAD

**Issue by wfk007** [ant-design/ant-design#30225]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/select/blob/master/src/generate.tsx](https://github.com/react-component/select/blob/master/src/generate.tsx)

### Steps to reproduce
in line 16 of source code: https://github.com/react-component/select/blob/master/src/generate.tsx

it uses the grammar import type which can only be used in typescript version gte v3.8

It will become weird that And design Select Component can non HINT TYPE when your vscode uses typescript version lt 3.8

I hope you can write docs(Q&A) in And Design to emphasis it. causing the action is realllllly weird!

### What is expected?
Type hint in Select Component

### What is actually happening?
Type hint not in Select Component

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 16.14.0 |
| System | macOS Catalina 10.15.3 |
| Browser | 86.0.4240.193（正式版本） (x86_64) |

---
how to fix it?

1. install typescript globally with version gt 3.8
2. press F1 in your vscode
3. search workspace settings
4. search typescript.tsdk
5. click edit in settings.json
6. add your config in json file, for instance below：

```json
{
  "typescript.tsdk": "{your_global_npm_path}/typescript/lib"
}
```

in your teminal, input npm root -g to get your your_global_npm_path and replace it in above config

**Comment by afc163** [comment]
Please upgrade TypeScript to >=`3.9.0`.
