### ISSUE TITLE
select 组件 自定义tagRender 点击叉叉后打开了dropdown

### ISSUE THREAD

**Issue by storageChu** [ant-design/ant-design#30224]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/irtvo)

### Steps to reproduce
select 组件 自定义tagRender 

### What is expected?
点击叉叉后不打开dropdown

### What is actually happening?
点击叉叉后打开了dropdown

| Environment | Info |
|---|---|
| antd | 4.11.3 |
| React | 16.13..1 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/react-component/select/pull/617

@matanshavit Could you look into this?

**Comment by afc163** [comment]
https://codesandbox.io/s/zidingyixuanzebiaoqian-antd4152-forked-79xgt?file=/index.js

**Comment by storageChu** [comment]
OK, I get it, thanks
