### ISSUE TITLE
日期选择的，禁止选择已过的日期现在不能选择当天

### ISSUE THREAD

**Issue by willdreame** [ant-design/ant-design#30223]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
当前官网组件

### What is expected?
禁止选择过去的日期时间，不应该今天的还没到的日期时间都不能选

### What is actually happening?
应该是当前时间之后的都可以选择

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 16版本 |
| System | umi |
| Browser | 谷歌 |

**Comment by willdreame** [comment]
const disabledDate = (current) => {
    return current && current < moment().subtract(1, 'days').endOf('day')
  };

这样写就支持当前时间的前面时间禁止了

**Comment by jameslahm** [comment]
所以这个是你可以自定义的？

**Comment by kerm1it** [comment]
禁用逻辑是自己 通过 `disabledDate` 写的，觉得有 bug 是因为官网上的  `disabledDate` 逻辑和你理解的不一样，只要官网上的 `disabledDate` 和 视图一致就是正常的。

**Comment by willdreame** [comment]
是的 官网我觉得 那个例子不太好
