### ISSUE TITLE
不使用FormItem时,如何自己做验证设置组件样式

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#3022]
#### 本地环境

- antd 版本:1.10
- 操作系统及其版本：win10
- 浏览器及其版本: chrome52

#### 你做了什么？

 
class App extends React.Component {
  constructor(props) {
    super(props);

  }

  handleChange = (e) => {
    console.log(e.target.value);
    //长度不允许大于5
    if (e.target.value.length>5) {
       //设置Input 样式为验证 has-error
    }
  }

  render() {
    return <Input placeholder="验证使用"  onChange={this.handleChange}/>;
  }
}
const mountNode = document.getElementById('content');
ReactDOM.render(<App />, mountNode);

#### 你期待的结果是：
![image](https://cloud.githubusercontent.com/assets/19165238/18434770/abefcee0-7921-11e6-9302-73cf48494a78.png)

如何编码实现
#### 可重现的在线演示
无

**Comment by benjycui** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by benjycui** [comment]
对于如何实现这类问题，建议自行研究源码，谢谢。

**Comment by whx76** [comment]
@benjycui  是否我的问题提的太...,对mastering-markdown不了解，我的问题是不自己设置自己的样式用antd的样式如何做验证在不使用formitem时

**Comment by whx76** [comment]
@benjycui  好的
