### ISSUE TITLE
Upload picture always stays in file upload

### ISSUE THREAD

**Issue by chenleyiduo** [ant-design/ant-design#30235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/chenleyiduo/reactProblem/tree/master/react-upload-bug](https://github.com/chenleyiduo/reactProblem/tree/master/react-upload-bug)

### Steps to reproduce
click upload img ->choose img -> the page show that 'uploading...' and no other response (the page always stay in uploading...)

### What is expected?
click upload img -> choose img -> Show thumbnails

### What is actually happening?
the page show that 'uploading...' and no other response (the page always stay in uploading...)

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.12.0 |
| System | window 7 |
| Browser | chrome 89.0.4389.128  |

**Comment by kerm1it** [comment]
Can you provide reproduce example with https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js

**Comment by chenleyiduo** [comment]
this.setState({ fileList: fileList.slice() })
或者setFileList(fileList.silice())
感觉像是强制执行了
反正这样可以解决问题
