### ISSUE TITLE
Ability to use resizeable column width. Column resizeable parameter for table.

### ISSUE THREAD

**Issue by german-st** [ant-design/ant-design#30237]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Make a resizeable width of columns in the table, by mouse.
Currently there is no example in the documentation, and the old example does not work.

### What does the proposed API look like?
Parameter "resizeable":    (true/false)
Thanks to him and setting the value bordered: true,
we get the ability to change the width of the columns with the mouse. by grabbing the border and dragging to the sides.

**Comment by afc163** [comment]
See https://ant.design/components/table/#components-table-demo-resizable-column
