### ISSUE TITLE
Why fork count is greater than star count?

### ISSUE THREAD

**Issue by summer-wu** [ant-design/ant-design#30233]
Most repositories have more star count than fork count. But, ant-design repository has more fork count.Why?
![image](https://user-images.githubusercontent.com/2476434/115397337-8fc68900-a218-11eb-8530-cc010cf6750d.png)

**Comment by yoyo837** [comment]
因为仓库丢失过，star全掉了，这是重新star的

**Comment by summer-wu** [comment]
@yoyo837 谢谢回复，没想到被关闭了的问题也会有人关注。👍
