### ISSUE TITLE
ReactDom.render一个Modal，这个modal会跑到目标container的外面。

### ISSUE THREAD

**Issue by shenzhigang** [ant-design/ant-design#3023]
ReactDom.render一个Modal，这个modal会跑到目标container的外面。
也就是说当ReactDom.unmountComponentAtNode是会报错。

- antd 版本:1.11.0
- 操作系统及其版本：win 10
- 浏览器及其版本:chrome 52

**Comment by benjycui** [comment]
如有报错麻烦提供可重现 demo

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
对，就是这么实现的。https://github.com/react-component/util/blob/master/src/getContainerRenderMixin.jsx#L23
