### ISSUE TITLE
無法更改 Table Column Filter 的按鈕文字 reset 和 ok 

### ISSUE THREAD

**Issue by Bonnie8ni** [ant-design/ant-design#30244]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shaixuanhepaixu-antd4152-forked-lz8u5)

### Steps to reproduce
想更改 Table Column Filter（漏斗） 的按鈕文字，按鈕文字顯示 reset 和 ok，但沒有方式可以更改

### What is expected?
因為多國語言功能必須要修改文字

### What is actually happening?
沒有方法可以更改，網路上也找不到相關解答

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
`<Table locale={{ ... }} />`

https://ant.design/components/table-cn/#API

**Comment by yoyo837** [comment]
> `<Table locale={{ ... }} />`
> 
> https://ant.design/components/table-cn/#API

他可能需要的是这个 https://codesandbox.io/s/shaixuanhepaixu-antd4152-forked-1o5xn?file=/index.js  

https://ant.design/components/config-provider-cn/

**Comment by Bonnie8ni** [comment]
> > `<Table locale={{ ... }} />`
> > https://ant.design/components/table-cn/#API
> 
> 他可能需要的是这个 https://codesandbox.io/s/shaixuanhepaixu-antd4152-forked-1o5xn?file=/index.js
> 
> https://ant.design/components/config-provider-cn/

這個改得動，但我想要像另外一個 filter（放大鏡）
https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel
可以自己編輯 JSX，是不是沒有辦法？

**Comment by yoyo837** [comment]
不好意思，没太理解你的需求。

**Comment by Bonnie8ni** [comment]
> `<Table locale={{ ... }} />`
> 
> https://ant.design/components/table-cn/#API

找到了 filterConfirm  filterReset，謝謝

**Comment by Bonnie8ni** [comment]
> 不好意思，没太理解你的需求。

我原本是想像說他可以像 filter（放大鏡）這個一樣
https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel
在 filterDropdown 可以自己重新編寫 JSX

**Comment by Bonnie8ni** [comment]
@afc163 @yoyo837 
兩個方式都可以達到最後目的，謝謝兩位大大（鞠躬）
