### ISSUE TITLE
Nested light/dark mode

### ISSUE THREAD

**Issue by matthewkwong2** [ant-design/ant-design#30245]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This is my webpage https://mwskwong.com/, which is using another UI library. I'm planning to migrate to Ant Design, but one of the important features is missing which prevents me from doing so.

As you can see in my current design, some sections have dark backgrounds, which are essentially using dark mode. My current design is the default theme is using a light theme. In the corresponding sections, I applied a a dark theme that overrides the default light theme. This is something I find Ant Design to be missing.

### What does the proposed API look like?
I'm not quite experienced in Ant Design yet. Perhaps, people with better understanding and provide a better API.
```jsx
<ThemeProvider theme={lightTheme}>
    <SomeComponent/>
    <ThemeProvider theme={darkTheme}>
        <ComponentInDarkMode/>
    </ThemeProvider>
</ThemeProvider>
```

**Comment by afc163** [comment]
trace #5656
