### ISSUE TITLE
antd内置的icon，在Unbuntu 14.04下乱码

### ISSUE THREAD

**Issue by LeungManwei** [ant-design/ant-design#3025]
#### 本地环境

- antd 版本:1.11.0
- 操作系统及其版本：Ubuntu 14.04
- 浏览器及其版本:Electron

#### 实际上的结果：
antd内置的icon显示乱码，使用font-awensome并不会
![image](https://cloud.githubusercontent.com/assets/7599653/18462914/df302af6-79b8-11e6-82e6-b1bc71d7679b.png)

**Comment by benjycui** [comment]
Ubuntu....

这个可以麻烦你排查下原因再尝试 PR 么，毕竟 Ubuntu 不是我们考虑的平台 😅

**Comment by LeungManwei** [comment]
暂时我是用font-awesome中的字体来替换了，但是体验不算很好。我尝试下吧~

**Comment by codering** [comment]
我也用的ubuntu,没有问题

**Comment by LeungManwei** [comment]
@codering 你的环境也是electron吗

**Comment by codering** [comment]
我前2两天也尝试了下electron, 也没有发现乱码问题。
哦，我用的16.04

**Comment by benjycui** [comment]
@LeungManwei 确认下字体是否被成功加载？

**Comment by LeungManwei** [comment]
@benjycui 做了离线字体

**Comment by LeungManwei** [comment]
找到原因了，electron的相对路径问题。-.- 苦逼了。

**Comment by LeungManwei** [comment]
file:///iconfont/iconfont.woff
做离线字体后，加载的地址变成从根目录

**Comment by LeungManwei** [comment]
以解决，谢谢各位

**Comment by afc163** [comment]
请自行关闭 issue

**Comment by imkiven** [comment]
@manweil 您好，请问你怎么替换成font-awesome的

**Comment by manweil** [comment]
1.设置fa-css-prefix:anticon
2.用gulp编译font-awsome.less
3.设置样式
`.anticon:before {
    font-family: anticon, FontAwesome !important;
  }`
4.在首页引用编译后的.css文件
