### ISSUE TITLE
Popover is not passing down the className property

### ISSUE THREAD

**Issue by LukaszGrela** [ant-design/ant-design#30257]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/LukaszGrela/pen/RwKqKVP?editors=001](https://codepen.io/LukaszGrela/pen/RwKqKVP?editors=001)

### Steps to reproduce
apply `className` to the `Popover` and noticed it is not there

### What is expected?
given class name to be added to the class list e.g. `ant-popover my-popover`

### What is actually happening?
nothing being added

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | any |

**Comment by jameslahm** [comment]
`my-popover` will attached on `Button`. `Popover` will transfer `className` to `children`. Not sure it's intened or a bug.

**Comment by afc163** [comment]
It is intented behavior.
