### ISSUE TITLE
InputNumber types incorrect for onChange arg

### ISSUE THREAD

**Issue by dman777** [ant-design/ant-design#30256]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wn62c?file=/index.js:306-314)

### Steps to reproduce
Enter alpha character - onchange does not fire
Enter number - onchange fires

### What is expected?
Documentation is incorrect. Under API, it shows value as type number. For onChange, it shows the arg in onChange to be number, string, or null. String is incorrect. 

### What is actually happening?
This is breaking typescript because value is a number. Typescript complains that onChange conflicts with value because onChange can also be a string(which is wrong because InputNumber only accepts numbers from user input)

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17 |
| System | Linux |
| Browser | Chrome |

**Comment by afc163** [comment]
```diff
- <InputNumber min={1} max={10} defaultValue={3} onChange={onChange} />
- <InputNumber<number> min={1} max={10} defaultValue={3} onChange={onChange} />
```
