### ISSUE TITLE
Select Can't Automatic tokenization

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#30253]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-select-cant-automatic-tokenization-dmvds)

### Steps to reproduce
1. Open [reproduction link](https://codesandbox.io/s/antd-select-cant-automatic-tokenization-dmvds)
2. Click `SetValue` Button

### What is expected?
Automatic tokenization.

### What is actually happening?
Can't Automatic tokenization

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | latest |
| System | windows 10 |
| Browser | latest |

**Comment by afc163** [comment]
`<Select mode="tags" />` accepts `value` as array.

https://codesandbox.io/s/antd-select-cant-automatic-tokenization-dmvds?file=/index.js

**Comment by kaysonwu** [comment]
@afc163 我知道传递数组值可以实现，不过我有个疑问，既然手动输入能分词，为什么设置字段值的时候不能完成分词呢？ 因为我已经明确 逗号作为分割字符了，这就是规则，类似于 csv 文件的约定规则一样的

**Comment by afc163** [comment]
看看这个例子 https://codesandbox.io/s/antd-select-cant-automatic-tokenization-forked-f1sc2?file=/index.js

**Comment by kaysonwu** [comment]
那这算不算是一种不一致的表现？因为我明确了要以逗号分割字符串，我允许用户输入带逗号的字符串进行分词，那我就不能允许后端传递带逗号的字符串进行自动分词吗？

**Comment by afc163** [comment]
Automatic tokenization 是一个用户交互配置，不是一个值转化配置。

**Comment by kaysonwu** [comment]
前端除了跟用户交互，跟后端接口也是频繁交互，这两种交互真没有必要保持一致性么？
