### ISSUE TITLE
使用npm run site的ssr模式打包文档报错document is not defined

### ISSUE THREAD

**Issue by simon-yxl** [ant-design/ant-design#30251]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
clone仓库
打包文档 npm run site

### What is expected?
ssr模式下能打包通过

### What is actually happening?
ssr模式下一直document is not defined或者window is not defined

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | react |
| System | mac,windows |
| Browser | 任何环境 |

**Comment by afc163** [comment]
我本地试了一下没问题。建议更新的最新的 master，重新安装 node_modules。

<img width="1019" alt="图片" src="https://user-images.githubusercontent.com/507615/115648277-bd661c00-a357-11eb-9a8e-d4ada43e2ff1.png">

**Comment by simon-yxl** [comment]
bisheng build --ssr -c ./site/bisheng.config.js  这个会报错， bisheng build -c ./site/bisheng.config.js 这样非ssr打包就不会
