### ISSUE TITLE
scrollTo don't work well in Tree component

### ISSUE THREAD

**Issue by Kexin-Li** [ant-design/ant-design#30264]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-tu-8uvlt?file=/index.js)

### Steps to reproduce
Click "Scroll to" button, then see if the tree scrolls to the target place.

### What is expected?
The tree should scroll to the target place when clicking the "Scroll to" button

### What is actually happening?
The tree scroll to the target place in the second time click.

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | macOS 10.15.7 |
| Browser | Chrome 89 |

**Comment by zombieJ** [comment]
It's caused that trigger `scrollTo` after `expandedKeys` change, the motion is still in process. So the scroll position is not final position. Should wait a while and scroll:

https://codesandbox.io/s/spring-microservice-d8j5m?file=/index.js
