### ISSUE TITLE
Upload Component: 'beforeUpload' method wont execute with 'accept' attribute

### ISSUE THREAD

**Issue by qunzi0214** [ant-design/ant-design#30268]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-x2nnl?file=/index.js)

### Steps to reproduce
1. click upload button
2. chose system's all file option
3. then upload a file with illegal ext
4. the beforeUpload method wont execute

### What is expected?
in my case, i need to limit the ext of file by two ways:
1. interactive limitation by 'accept' attribute(it can be ignored)
2. javascript limitation by 'beforeUpload' method

### What is actually happening?
'beforeUpload' method wont execute with 'accept' attribute

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | macOS 10.15.3 |
| Browser | Chrome 87.0.4280.88 |

---
it works in antd@4.13.0 and break in antd@4.13.1

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/29973#issuecomment-810872198
