### ISSUE TITLE
table组件设置了scroll.y会导致宽度没有响应

### ISSUE THREAD

**Issue by ZhangJianChengZzz** [ant-design/ant-design#30266]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#API](https://ant.design/components/table-cn/#API)

### Steps to reproduce
在flex布局下，左侧固定宽，右侧flex:1的条件下  左侧动态更改宽度(如：点击一次左侧宽度变成50px，table组件拉伸,再点击一次，左侧宽度变为200px,table组件收缩)会导致table组件拉伸后无法还原，
不使用scroll.y属性则不会发生此问题，table组件可以正常根据flex:1自适应宽度

### What is expected?
table组件可以正常根据flex:1自适应宽度

### What is actually happening?
table组件拉伸后无法还原

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 16.8.6 |
| System | Mac os |
| Browser | Chrome |

**Comment by ZhangJianChengZzz** [comment]
我浏览了一下issue 和 #29503的问题是一模一样的

**Comment by afc163** [comment]
trace #29503

**Comment by iNeedToCopy** [comment]
+1
