### ISSUE TITLE
Modal onOk/onClose throw error Uncaught TypeError: onCancel is not a function

### ISSUE THREAD

**Issue by lripoche** [ant-design/ant-design#30278]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/aged-fog-hb6lm?file=/src/App.js)

### Steps to reproduce
Open a modal with onOk/onCancel function, open it and try to close the modal

### What is expected?
The modal close itself

### What is actually happening?
Modal throw an error Uncaught TypeError: onCancel is not a function

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | Debian GNU/Linux 9 (stretch) |
| Browser | Chrome 89.0.4389.128 (Build officiel) (64 bits) |

**Comment by afc163** [comment]
```diff
- function Login(visible, onClose) {
+ function Login({ visible, onClose }) {
}
