### ISSUE TITLE
Form支持disabled穿透

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#30270]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表单通常来说是为了录入数据，随之而来的另外一个需求是仅查看，
如果表单元素一个一个disabled，显得有点臃肿，不知是否考虑 `Form` 支持  `disabled` 来穿透

### What does the proposed API look like?
`<Form disabled /> ` 这样就禁用整个表单，
优先级以内层  `Form.Item`元素为准

**Comment by MrHeer** [comment]
disable 后，看起来不会很奇怪吗

**Comment by hengkx** [comment]
我直接也提过 有场景 需要   整个表单 只读

**Comment by qiaodaima** [comment]
> disable 后，看起来不会很奇怪吗

不会很奇怪，就是一个 只读页面（复用编辑页面），
不可能说编辑页面 和 查看页面是2个页面

所以如果能支持disabled 这个问题就可以很好的解决

**Comment by jueinin** [comment]
记得之前有这个pr吧，给form组件加个commonFormItemProps的props用来指定formitem的共有props

**Comment by qiaodaima** [comment]
#30270

**Comment by shaodahong** [comment]
需要注意的是，**disabled** 和 **只读** 是不一样的，disabled 是禁用，样式上的呈现就是置灰，但是只读是数据呈现文本，不同的概念

**Comment by qiaodaima** [comment]
#6083  #16949 #7766

**Comment by crazyair** [comment]
这种性质功能，推荐自己包一层 Form、FormItem，在 Form 添加 disabled 或者 view 或者其他，来控制 Form.Item props，来达到自己想要的效果。

**Comment by crazyair** [comment]
> 这种性质功能，推荐自己包一层 Form、FormItem，在 Form 添加 disabled 或者 view 或者其他，来控制 Form.Item props，来达到自己想要的效果。

在这里实现过一版，可作为参考 https://yforms.vercel.app/examples

**Comment by qiaodaima** [comment]
[这里有一片文章粗浅的介绍了disabled 和 只读的区别](https://dongdaima.com/article/46673)

我们觉得我们的所谓的只读场景有2种(我目前能想到的)：

- 需要展示只读的特性，然后要置灰提示，
   比方说你`编辑个人信息`，可以`修改手机号`，但是`姓名和身份号是不可以编辑的`，
   这个时候置灰的UI风格是可以体现出这一点的。

- 我们创建了一个用户信息，我们要进行对数据检查，即一般是做成 `预览效果`，
   这个时候我们仅仅是希望只读，但是`不希望有置灰的背景`，因为这样视觉上也比较丑陋，一片置灰,
   比如我们给`antd 提issues`时，也会有一个`预览操作`，但是数据并不是一片灰

**Comment by crazyair** [comment]
Input Textarea DatePicker 应该加个 view 展示，不显示 border、不能编辑这样页面显示可以是  https://ant-design.gitee.io/components/descriptions-cn/ 这这样展示 label value

**Comment by crazyair** [comment]
Input Textarea DatePicker 应该加个 view 展示，不显示 border、不能编辑这样页面显示可以是  https://ant-design.gitee.io/components/descriptions-cn/ 这这样展示 label value

**Comment by qiaodaima** [comment]
> Input Textarea DatePicker 应该加个 view 展示，不显示 border、不能编辑这样页面显示可以是 https://ant-design.gitee.io/components/descriptions-cn/ 这这样展示 label value

你这个重复了 要不删一条，看的怪难受的 😀

**Comment by AlanCutFlim** [comment]
期待这个新特性，在一个巨型表单里控制每个输入元素的 disabled 状态好麻烦

**Comment by CookyG** [comment]
我觉得自己搞样式解决会更快 功能通过pointer-events 禁用

**Comment by yunsii** [comment]
之前基于 Form 和输入组件自己封装过，有点麻烦，看起来得为所有输入组件加个 readonly 的渲染模式？

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/35210

**Comment by zhangchao828** [comment]
虽然穿透了，但是优先级没有以内层 Form.Item元素为准，内层Item中的表单元素设置disabled={false}是无效的，这样想让其中几个可以编辑就不支持了
