### ISSUE TITLE
ant.design sticky table only displays horizontal sticky scrollbar when the height of the table is greater than the window height

### ISSUE THREAD

**Issue by andrashatvani** [ant-design/ant-design#30271]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-oitl1?file=/index.js)

### Steps to reproduce
Start app, look

### What is expected?
The horizontal scrollbar is always visible 

### What is actually happening?
The horizontal scrollbar is only visible  when the height of the table is greater than the window height 

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | MacOS 11.3 Beta (20E5231a) |
| Browser | 90.0.4430.72 |

**Comment by afc163** [comment]
It is by designed.

**Comment by andrashatvani** [comment]
In the current project there are dozens of columns and regardless of the number of rows the customer wants the horizontal scrollbar always displayed. Please at least make it customisable or provide a workaround.
