### ISSUE TITLE
Upload action回调为umi-request的方法，会触发两次接口请求

### ISSUE THREAD

**Issue by America-first-melon** [ant-design/ant-design#30272]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-forked-yl78p?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-forked-yl78p?file=/index.js)

### Steps to reproduce
1.
```javascript
<Upload action={uploadFunc} accept={"image/*"} listType={"picture-card"} />
```
这个时候uploadFunc触发上传， 比如返回了个{url:xxx} 这个时候会再请求一次`http://${window.locaiton.href}/[object]` 
[object]为第一次的返回结果
2.
```javascript
<Upload customRequest={uploadFunc} accept={"image/*"} listType={"picture-card"} />
```
只有一次触发上传

### What is expected?
action行为只有一次请求

### What is actually happening?
action行为有两次请求， 第一次为上传动作，第二次请求了 winow.location.href   "/"   "上传动作返回的数据"

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome 88 |

**Comment by America-first-melon** [comment]
![image](https://user-images.githubusercontent.com/21686182/115730285-bb807500-a3b8-11eb-93ce-7b5f79fcac55.png)

**Comment by America-first-melon** [comment]
请问，这种情况是如何引起的？

**Comment by America-first-melon** [comment]
![image](https://user-images.githubusercontent.com/21686182/115730829-347fcc80-a3b9-11eb-95ea-5c1b9ea4a0e5.png)
第一步的上传 return了false 那么第二次就是 href + false

**Comment by America-first-melon** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-yl78p?file=/index.js

**Comment by America-first-melon** [comment]
![image](https://user-images.githubusercontent.com/21686182/115979213-33b48980-a5b7-11eb-9f2b-5e59403f5a63.png)

**Comment by afc163** [comment]
注意一下 action 的类型，不支持你的写法。

```
string | (file) => Promise<string>
```
