### ISSUE TITLE
Table fixed固定列在IE11版本浏览器上无效，变成了横向滚动条

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#30282]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
我看文档有写下面这句话，意思是不支持ie浏览器了？？
注意：v4 版本固定列通过 sticky 实现，IE 11 会降级成横向滚动。

### What is expected?
可以固定列

### What is actually happening?
固定列无效

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 17.x |
| System | windows7 |
| Browser | IE浏览器 11.0.9600 |

**Comment by Mathround** [comment]
这意思是不支持ie了吗

<img width="900" alt="11" src="https://user-images.githubusercontent.com/25702871/115839933-bc171b00-a44d-11eb-945d-af8c5f6ff548.png">

**Comment by afc163** [comment]
是的，IE11 不支持 sticky。
