### ISSUE TITLE
[Docs] Add an enum for `validateTrigger` props in Form component

### ISSUE THREAD

**Issue by Kexin-Li** [ant-design/ant-design#30288]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://ant.design/components/form/#API

![image](https://user-images.githubusercontent.com/21211353/115894462-e2f44200-a48b-11eb-9ace-4f1d44eafb38.png)

Currently, only `string` is specified for `validateTrigger` props on the document. I would like to know what kind of string can be passed? onChange, onBlur, onSubmit, anything else?

So I hope we can have an enum type for `validateTrigger` props. Thanks!

### What does the proposed API look like?
NA

**Comment by afc163** [comment]
Any string value could be valid, it is a prop name for field component.
