### ISSUE TITLE
Table 虚拟列表，排版显示异常

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#30284]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4tgc)

### Steps to reproduce
参考官方文档中的示例

### What is expected?
排版正常显示

### What is actually happening?
排版一场

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 16.14.0 |
| System | window |
| Browser | chrome |

**Comment by zmbxy95** [comment]
在线demo复现：
1. 通过官方文档打开codebox
2. 如图所示，在新页面打开
![image](https://user-images.githubusercontent.com/50108232/115846137-2af77280-a454-11eb-9dfd-cc7bc192ce02.png)
3. 结果如下：
![image](https://user-images.githubusercontent.com/50108232/115846209-3f3b6f80-a454-11eb-932a-fcda25cf23be.png)

**Comment by zmbxy95** [comment]
官网中的例子同样显示异常
![image](https://user-images.githubusercontent.com/50108232/115846488-8b86af80-a454-11eb-80cc-4e8027cf37a0.png)

**Comment by afc163** [comment]
shouldForceUpdate 设为 true 就行了。https://github.com/ant-design/ant-design/commit/a592dd897e6b86389400f039ed3611dda072a869
