### ISSUE TITLE
当 select 组件的 mode 为 multiple， 单元测试不通过

### ISSUE THREAD

**Issue by shidaying** [ant-design/ant-design#30296]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-brahmagupta-epye5?file=/src/Test.test.js)

### Steps to reproduce
run test

### What is expected?
测试通过

### What is actually happening?
 TypeError: Cannot read property 'scrollWidth' of null

<img width="666" alt="截屏2021-04-25 上午11 51 17" src="https://user-images.githubusercontent.com/5172892/115980097-99574480-a5bc-11eb-8751-f443db2317bb.png">

<img width="522" alt="截屏2021-04-25 上午11 49 35" src="https://user-images.githubusercontent.com/5172892/115980064-5a28f380-a5bc-11eb-8f42-029bcf0a8c62.png">

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.8.6 |
| System | mac os |
| Browser | chrome |

---
Select 组件测试失败

**Comment by shidaying** [comment]
> Hello @shidaying. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @shidaying, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/unruffled-brahmagupta-epye5?file=/src/Test.test.js

**Comment by xrkffgg** [comment]
目前仓库的 multiple 没问题

https://github.com/ant-design/ant-design/blob/a592dd897e6b86389400f039ed3611dda072a869/components/select/__tests__/__snapshots__/demo.test.js.snap#L1184

**Comment by shidaying** [comment]
> 目前仓库的 multiple 没问题
> 
> https://github.com/ant-design/ant-design/blob/a592dd897e6b86389400f039ed3611dda072a869/components/select/__tests__/__snapshots__/demo.test.js.snap#L1184

我也下载源码看了，确实没问题；但 [测试](https://codesandbox.io/s/unruffled-brahmagupta-epye5?file=/src/Test.test.js) 这种简单的又有问题，很奇怪；没看到源码里有啥特殊的配置

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/master/.jest.js

**Comment by afc163** [comment]
https://codesandbox.io/s/unruffled-brahmagupta-epye5?file=/src/Test.test.js

里貌似也没有出现 `TypeError: Cannot read property 'scrollWidth' of null` 的问题。

**Comment by shidaying** [comment]
> https://codesandbox.io/s/unruffled-brahmagupta-epye5?file=/src/Test.test.js
> 
> 里貌似也没有出现 `TypeError: Cannot read property 'scrollWidth' of null` 的问题。

ide 里会有的，sandbox 信息较少
