### ISSUE TITLE
Select 组件出发事件onChange后，不能立即从form 组件的getFieldsValue 获取到值

### ISSUE THREAD

**Issue by jackiealex** [ant-design/ant-design#3029]
原因是因为动画的过程比较慢吧加了一个setTimeout 才获取到。。。
render() {
return  <Form
    <Select onChange={someMethod} {...getFeildProps('id')}

}

someMethod(){
var data =   this.props.form.getFieldsValue()
//data.id undefined

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1353
