### ISSUE TITLE
input组件输入空格、input输入拦截

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#30295]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一般来说，`Input`组件在很多场景需要限制输入空格，比如首尾空格，中间空格问题。
而`Input`组件常结合 `Form`组件结合使用。对于这个问题有下面几个方法来处理

- `Form item` 可以 设置 `rules ` 来设置校验规则
  - 这么做并没有限制用户的输入，只是表单无法提交
- `Input` 有 `onchange`钩子来处理
    - `Form` 有一个优点，就是可以无需定义 `state`, 即可自动搜集表单数据，但这么做需要单独定义 `state`,  

### What does the proposed API look like?
```
<Input
   intercept={(value) => {
     // 这里做一些数据处理，
     // 类似http请求拦截处理一样,不管怎么处理，最后要记得return 出去
     return value;
   }}
/>
```

```
// 去除空格
<Input
   replace={{
    regExp:  /\s /g,
    to: ''
   }}
/>
```

**Comment by afc163** [comment]
建议自行封装一个 MyInput 来处理这些行为。
