### ISSUE TITLE
antdvue，popover组件，在点击列表最下方弹出popover时，页面滚动条会滚动到顶部

### ISSUE THREAD

**Issue by yunzhongbaihe** [ant-design/ant-design#30303]
<a-popover
  overlayClassName="week-report-popover"
  destroyTooltipOnHide
  trigger="click"
  :getPopupContainer="
    triggerNode => {
      return triggerNode.parentNode || document.body;
    }
  "
>
  <template slot="content">
    <a-textarea
      :value="record[col.dataIndex]"
      :maxLength="300"
      style="width: 450px;height: 180px;border: 1px solid #40a9ff;"
      autoFocus
      placeholder="请输入"
      @blur="
        e => handleInputBlur(e.target.value, record, col, e.target)
      "
    ></a-textarea>
  </template>
  `<a-textarea`
    readOnly
    :value="record[col.dataIndex]"
    :title="record[col.dataIndex]"
    class="edit-textarea"
  ></a-textarea>
</a-popover>

**Comment by xrkffgg** [comment]
@yunzhongbaihe vue 的来这里 https://github.com/vueComponent/ant-design-vue 提
