### ISSUE TITLE
Select 设置value 属性，在表单校验时无法读取值

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design#3030]
- antd 版本: 1.11.0
- 操作系统及其版本：MAC
- 浏览器及其版本: Google

我使用redux 管理Select 的value，在提交表单的时候，表单校验方法validateFieldsAndScroll没有读取到Select的value。导致表单校验失败。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Sean-Snow** [comment]
const { Select, Form, Button } = antd;
    const Option = Select.Option;
    let App = React.createClass({
    handleClick(){
        this.props.form.validateFieldsAndScroll((errors, values) => {
        if (errors) {
            console.error('Errors in form!!!', errors);
            return;
        }
        console.log(values);
        });
    },
    render() {
        const {getFieldProps} = this.props.form;
        return (
        <Form>
            <Form.Item>
            <Select {...getFieldProps('address',{rules: [{required: true}]})} value="china">
                <Option value="china">{'China'}</Option>
            </Select>
            </Form.Item>
            <Button onClick={this.handleClick.bind(this)}>{'Submit'}</Button>
        </Form>
        );
    }
    });
    App = Form.create()(App);
    ReactDOM.render(<App />, document.getElementById('container'));


@benjycui

**Comment by benjycui** [comment]
http://ant.design/components/form/#this.props.form.getFieldProps(id,-options)

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
