### ISSUE TITLE
Modal stops working if transitionName is used in antd >=4.13.0

### ISSUE THREAD

**Issue by negati-ve** [ant-design/ant-design#30307]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-brook-ddbfe?file=/SomeModalWrapper.js)

### Steps to reproduce
- Use antd >=4.13.0
- add transitionName prop to Modal 

### What is expected?
normal Modal transition and operation

### What is actually happening?
Modal freezes

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 16.4 |
| System | Mac OS |
| Browser | Mozilla Firefox |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29626#issuecomment-792423728

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29699#issuecomment-824495157
