### ISSUE TITLE
Menu置于多个flex元素内无法根据元素宽度自动缩略

### ISSUE THREAD

**Issue by MafuyuRyan** [ant-design/ant-design#30305]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-cerf-47ofc?file=/src/App.js)

### Steps to reproduce
https://github.com/ant-design/ant-design/issues/27240
将Menu（mode=horizontal）置于普通容器内在容器宽度不足时，Menu会自动缩略。将Menu置于单个flex容器的子元素内时，Menu会自动缩略。将Menu置于多个flex容器的子元素内时，无法根据其父元素的宽度自动缩略。

### What is expected?
Menu在多层flex元素内自动缩略

### What is actually happening?
缩略后无法再次展开

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | windows |
| Browser | chrome\edge |

**Comment by afc163** [comment]
https://codesandbox.io/s/festive-firefly-b6bmn

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/36604
