### ISSUE TITLE
modal下，点击select并滚动，列表内容和列表框被分离

### ISSUE THREAD

**Issue by yujian001** [ant-design/ant-design#30300]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6dcx8)

### Steps to reproduce
modal下，点击“ Open Modal with async logic”按钮，出现弹窗，滚动条滚动到 select下拉列表框位置，点击select下拉列表，列表select.option被展开，此时鼠标滚轮滚动，出现select和select.option分离，select.option固定在第一次出现的位置，而select框跟随滚轮滚动。

### What is expected?
滚动条滚动到 select下拉列表框位置，点击select下拉列表，列表select.option被展开，此时鼠标滚轮滚动，select和select.option任然为一个整体跟随滚动。

### What is actually happening?
滚动条滚动到 select下拉列表框位置，点击select下拉列表，列表select.option被展开，此时鼠标滚轮滚动，出现select和select.option分离，select.option固定在第一次出现的位置，而select框跟随滚轮滚动。

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 16.7.0 |
| System | win7 |
| Browser | google |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/29974#issuecomment-810871261

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F

**Comment by yujian001** [comment]
&nbsp;
  您的方很有效，已得到解决，感谢您！

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "ant-design/ant-design" ***@***.***&gt;;
 发送时间:&nbsp;2021年4月25日(星期天) 下午5:03
 ***@***.***&gt;;
 ***@***.******@***.***&gt;;
 主题:&nbsp;Re: [ant-design/ant-design] modal下，点击select并滚动，列表内容和列表框被分离 (#30300)

 

 

 
https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F
