### ISSUE TITLE
Switch inside FormItem works incorrectly

### ISSUE THREAD

**Issue by delphin92** [ant-design/ant-design#30316]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-feather-gd3z0?file=/src/App.js)

### Steps to reproduce
Just run app

### What is expected?
- Switch should be set on
- Console shouldn't contain warnings

### What is actually happening?
- Switch is set off
- Console contains warning:
Warning: [antd: Switch] `value` is not a valid prop, do you mean `checked`? 

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Google Chrome 89.0.4389.128 |

---
There is WA:

```
const SwitchWrapper = ({value, ...props}) =>
  <Switch checked={value} {...props}/>

<Form.Item label="switch" name="switch">
  <SwitchWrapper />
</Form.Item>
```

**Comment by afc163** [comment]
https://ant.design/components/form/

Search `valuePropName`

**Comment by ChristopherTrimboli** [comment]
This feels weird and highly confusing, I think this is a bad implementation of Form Switch default behavior, it should not error.
