### ISSUE TITLE
table的固定列 在火狐不生效

### ISSUE THREAD

**Issue by Liangaas** [ant-design/ant-design#30315]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
直接使用就可以发现

### What is expected?
火狐是支持sticky的，期待也可用sticky解决固定列效果

### What is actually happening?
火狐的固定列效果同IE 11，降级为横向滚动

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | react |
| System | windows10 |
| Browser | Firefox 39.0.3 |

**Comment by afc163** [comment]
Firefox 版本过低了，请升级到最新版本。
