### ISSUE TITLE
在Modal中DatePicker选择时间后，滚动页面时Modal固定，Button飘走

### ISSUE THREAD

**Issue by slertness** [ant-design/ant-design#3031]
#### 本地环境

- antd 版本: 1.11.0
- 操作系统及其版本：win10
- 浏览器及其版本: chrome 53

#### 你做了什么？

在Modal中使用DatePicker选择时间，然后滚动页面。

#### 你期待的结果是：

正常显示

#### 实际上的结果：

滚动时Button飘离原位置。直接看在线演示吧

#### 可重现的在线演示

http://codepen.io/slert/pen/gwPWOV?editors=001

#### 问题分析

我发现是因为.ant-btn这个class里的transform: translate3d(0, 0, 0)这个属性造成的，覆盖成none就好了。
但是不清楚一开始加transform: translate3d(0, 0, 0)的用意是什么，去掉是否会有其他影响。

**Comment by afc163** [comment]
Mac 下的 chrome 里没有重现。

去掉会影响点击的动画效果。

**Comment by slertness** [comment]
我这里测试了windows下的chrome的51以及53。51正常，53会出现上述bug。

**Comment by qq181621732** [comment]
mac下的53版本有这个问题。

**Comment by afc163** [comment]
windows 下的重现了，我看看吧。

**Comment by afc163** [comment]
去掉了，用 `position:relative` 代替 `transform: translate3d(0, 0, 0)` 就行了。
