### ISSUE TITLE
Table组件在渲染数据时，报错G.some is not a function，源码定位在components/table/Table.tsx170行

### ISSUE THREAD

**Issue by LittleSesame** [ant-design/ant-design#30329]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://code.sn-service.cn/gxz/my-app.git](http://code.sn-service.cn/gxz/my-app.git)

### Steps to reproduce
点击查询按钮后根据接口返回数据渲染table

### What is expected?
table数据正常展示

### What is actually happening?
报错G.some is not a function

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 17.0.2 |
| System | win7 64 |
| Browser | chrome 90.0.4430.93（正式版本） （64 位） |

---
纯内网环境

**Comment by this-summer** [comment]
> NULL
你好  请问这个问题怎么解决的呢
