### ISSUE TITLE
table multiselect 时，是否可设置不用加ant-table-row-selected

### ISSUE THREAD

**Issue by zhangqhzz** [ant-design/ant-design#30323]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在checkbox进行多勾选时，有时并不需要对勾选行加底色，而只是需要对当前行加底色即可，底色太多太花眼。

### What does the proposed API look like?
可否加设属性是否要启用ant-table-row-selected

**Comment by afc163** [comment]
可以自定义变量 `@table-selected-row-bg`：https://github.com/ant-design/ant-design/blob/4951b59d3288fca3fe8ce0cc9f400439aa6d77bb/components/style/themes/default.less#L594

**Comment by zhangqhzz** [comment]
> 可以自定义变量 `@table-selected-row-bg`：
> 
> https://github.com/ant-design/ant-design/blob/4951b59d3288fca3fe8ce0cc9f400439aa6d77bb/components/style/themes/default.less#L594

这样不是会对整体有影响？我只是在有部分模块中需要

**Comment by afc163** [comment]
那建议直接加一个 className，然后覆盖样式即可。

**Comment by zhangqhzz** [comment]
> 那建议直接加一个 className，然后覆盖样式即可。

好吧，加 className变通方式我知道，只是有点怪，能有设置多好
