### ISSUE TITLE
Table 的Pagination 上的下拉每页几条记录功能能否改成可同时输入？

### ISSUE THREAD

**Issue by zhangqhzz** [ant-design/ant-design#30324]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table 的Pagination ，每页几条的功能虽可以设定下拉显示记录数，但不够灵活，有时用户想要可输入，如：设定每页显示20，40，80或160等，用户有时想输入如50，300等时，就不好操作

### What does the proposed API look like?
希望将此每页几条的功能，改成下拉的同时也可以输入

**Comment by kerm1it** [comment]
设计每页显示几条的下拉框本身就是为了提供一个大概的范围，限制每页的显示数量，减少渲染和服务器的压力，太灵活了反而不好。

如果想实现，可以把分页 的 `showSizeChanger` 设为 `false` 然后自己在后面加一个输入框。

**Comment by zhangqhzz** [comment]
如果自己加入有何意义，本身就希望作为翻页功能的一部分，且又不需要增加空间，只是将原下拉控件改成可输入而已。
如果自己加入，干脆翻页条也不要提供，大家都自己写一下好了

**Comment by zhangqhzz** [comment]
> 设计每页显示几条的下拉框本身就是为了提供一个大概的范围，限制每页的显示数量，减少渲染和服务器的压力，太灵活了反而不好。
> 
> 如果想实现，可以把分页 的 `showSizeChanger` 设为 `false` 然后自己在后面加一个输入框。

我不这样认为，pagination为何不可改进一下呢，只是将原下拉改成可同时输入而已，既然原先只是提供一个大概范围，那不如不用，直接改成输入好了不是更好？

**Comment by kerm1it** [comment]
用输入框就会衍生其他问题，例如，是否需要限制最大、最小值，因为有的业务查询是有成本的，容易造成资源浪费或服务器压力大，是否需要禁用属性等等。

**Comment by zhangqhzz** [comment]
> 用输入框就会衍生其他问题，例如，是否需要限制最大、最小值，因为有的业务查询是有成本的，容易造成资源浪费或服务器压力大，是否需要禁用属性等等。

说的没错，限制最大最小好办，记录总记录数在，对于其他是开发者根据实际是否要使用此功能即可，此功能只是可选而已

**Comment by afc163** [comment]
可以留着，虽然目前没有计划支持。

**Comment by fayanLiao** [comment]
我现在想关闭这个输入，5以上的版本似乎默认就可以搜索了，但是没看见怎么关闭这个功能

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/42608

**Comment by afc163** [comment]
> 我现在想关闭这个输入，5以上的版本似乎默认就可以搜索了，但是没看见怎么关闭这个功能

为啥想关闭呢？有啥交互上的副作用么

**Comment by fayanLiao** [comment]
并没有啥副作用，只是由于在一些场景下就三个区间10/30/50一眼可以望过去，可以选择，不想开启给用户搜索功能

**Comment by fayanLiao** [comment]
是否能修改pagination的sizeChange的search功能是可以配置的，showSearch=false?

**Comment by jacklee814** [comment]
> 并没有啥副作用，只是由于在一些场景下就三个区间10/30/50一眼可以望过去，可以选择，不想开启给用户搜索功能

Hi @afc163 
認同，提供搜尋的情境大部分是為了更快速的找到需要的項目，但在 Page size 中普遍的選項都不多
在這邊提供可搜尋的輸入框我覺得還是不錯，但希望提供出來的是 optional 的能讓使用者來決定要不要提供搜尋的功能
我想像的也是在 pagination 中可以調控 showSearch 來決定要不要提供搜尋的功能
沒問題的話我可以來實作這個功能！

**Comment by afc163** [comment]
@jacklee814 欢迎

**Comment by fayanLiao** [comment]
> showSearch

🎉🎉🎉

**Comment by jacklee814** [comment]
@afc163 @fayanLiao 我發了，有空再麻煩幫忙看一下了

**Comment by chenzhihang950909** [comment]
showSearch这个提案是否通过？
