### ISSUE TITLE
defaultExpandAllRows does not work correctly.

### ISSUE THREAD

**Issue by huseyingoztok** [ant-design/ant-design#30334]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yuanchengjiazaishuju-ant-design-demo-forked-yb2dr?file=/index.js)

### Steps to reproduce
--------

### What is expected?
Expanding all rows

### What is actually happening?
------------

| Environment | Info |
|---|---|
| antd | 4.9.0 |
| React | 16.12.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
#11615
https://github.com/ant-design/ant-design/issues/10588#issuecomment-390542477
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

**Comment by alwaysmyz** [comment]
for the first render,the table's dataSource don't get any data;then you get data from network ,but this is not the first render,so defaultExpandAllRows doesn't work any more.So you can use the construct like this: data!==undefined?<Table></Table>:null.
