### ISSUE TITLE
RangePicker - Separator does not align to center when increasing width of picker

### ISSUE THREAD

**Issue by colbisaurusrex** [ant-design/ant-design#30333]
![image](https://user-images.githubusercontent.com/18058808/116284301-c84af300-a741-11eb-8c06-e156d8595fcd.png)

- [✅ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/a64gb1--run?file=index.js](https://stackblitz.com/edit/a64gb1--run?file=index.js)

### Steps to reproduce
Increase width beyond default (ex. 500 px)

### What is expected?
Separator will align in center

### What is actually happening?
Separator aligns to right

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | react |
| System | macOS Big Sur v 11.2.3 |
| Browser | Chrome Version 90.0.4430.85  |

**Comment by afc163** [comment]
It is by designed.
