### ISSUE TITLE
InputNumber新版本输入过程中，formatter与min、max产生的错乱

### ISSUE THREAD

**Issue by unfor** [ant-design/ant-design#30331]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bb3jo?file=/index.js)

### Steps to reproduce
当输入框内值为最大位数值时，全部选中value后，快速输入12，

### What is expected?
期望结果为12分钟

### What is actually happening?
最后值为152分钟

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 17.x |
| System | win10 |
| Browser | chrome |

---
InputNumber的代码中，由value的变化引起setValue的函数执行，同时监测到已经注册了formatter方法后，以及最小值限制，会直接执行formatter，导致输入的值，如上述demo中输入12， 仅检测到1被输入，就会自动设置为15分钟，接着处理2的输入

**Comment by zombieJ** [comment]
你的重现里没有设置  `onChange` 方法，是不是改过了？
