### ISSUE TITLE
How to allow only images in antd Upload component

### ISSUE THREAD

**Issue by jayanthbondi** [ant-design/ant-design#30346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upload-png-file-only-antd4153-forked-9bj77)

### Steps to reproduce
1) Upload any image which is not in png format.

### What is expected?
It should not allow to upload.

### What is actually happening?
it's showing the error message and uploading

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | 16.13.1 |
| System | windos10 |
| Browser | google |

**Comment by qiaodaima** [comment]
```
const props = {
   accept: '.png,.jpg',
};

<Upload {...props}>
  <Button>Upload png jpeg and only</ Button>
</Upload>
```

**Comment by jayanthbondi** [comment]
Hi @qiaodaima the fix which you provided is not working.

**Comment by qiaodaima** [comment]
> Hi @qiaodaima the fix which you provided is not working.
Try it
```
const props = {
   accept: '.png',
};

<Upload {...props}>
  <Button>Upload png jpeg and only</ Button>
</Upload>
```

**Comment by jayanthbondi** [comment]
Hi @qiaodaima ,
I tried it but it's not working.
I was able to upload text files also.

**Comment by qiaodaima** [comment]
@jayanthbondi 

What is your question?
Is it necessary to set up to only upload pictures in png format?
Am I right?

I am a Chinese developer, are you from India?

**Comment by qiaodaima** [comment]
@jayanthbondi  
The `accept `parameter in the document is used to limit the type of uploaded file
