### ISSUE TITLE
Sub Table is not render after new data is add 

### ISSUE THREAD

**Issue by r00t9** [ant-design/ant-design#30348]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bhe1d)

With react state
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lfx95?file=/index.js)

### Steps to reproduce
Try to add a new row in sub table, the data is correct but is not show on the table.

### What is expected?
To correct render the sub table if a new row is added

### What is actually happening?
The problem is only happening if i add a new row in the existing sub table but if you open sub table before. If don't open sub table before, you add the new row and open sub table after the render is ok.
If i add a new row in the table with sub row the rending is ok.  Probably something with expandedRowRender? 

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react 17.0.1 |
| System | Linux mint 19.3 |
| Browser | Firefox 88.0 |

---
This is not working also with setState. If i add new row in sub table and then run shorting, the new row it show with out any problem.

**Comment by afc163** [comment]
> This is not working also with setState

Need reproduce if you use setState.

**Comment by r00t9** [comment]
hello @afc163 thanks for the fast reply. I update the ticket with another example. I am a beginner in react , so probably I don't need setState to update :/

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-1865k?file=/index.js

`dataSource` should be new instance when `setState`.
