### ISSUE TITLE
form.getFieldsValue can not get correct values on initial render

### ISSUE THREAD

**Issue by weird94** [ant-design/ant-design#30344]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-sun-3bjot?file=/src/App.js)

### Steps to reproduce
checkout the json value render in dom

### What is expected?
 {a: 1}

### What is actually happening?
{}

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 17  |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29221#issuecomment-772973820
