### ISSUE TITLE
当表单布局layout = 'inline' 时， 选择框 select 内容会遮住label 部分内容

### ISSUE THREAD

**Issue by myloveGy** [ant-design/ant-design#30349]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/jinxing/pen/mdRYERX?editors=0010](https://codepen.io/jinxing/pen/mdRYERX?editors=0010)

### Steps to reproduce
当表单布局layout = 'inline' 时， 选择框 select 内容会遮住label 部分内容

### What is expected?
select 选择框不能遮住 label 标签里面内容

### What is actually happening?
select 选择框遮住了 label 部分内容

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | ^16.12.0 |
| System | macOS Big Sur |
| Browser | Google Chrome 90.0.4430.85 |

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/yLgWaGz?editors=0010 这样如何？

**Comment by afc163** [comment]
或者 https://codepen.io/afc163/pen/LYxoRMa?editors=0010
