### ISSUE TITLE
Cascader 组件的 label 为 ReactNode 时如何进行搜索，是否能加一个 Select 中的 optionFilterProp 属性? 

### ISSUE THREAD

**Issue by any1024** [ant-design/ant-design#30341]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sousuo-antd4153-forked-wtfgs?file=/index.js)

### Steps to reproduce
使用搜索直接报错，未找到 api 可以调整内部搜索对应的字段

### What is expected?
当 label 为 ReactNode 时也支持配置进行搜索

### What is actually happening?
无法搜索

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 16.9.0 |
| System | windows |
| Browser | chrome-87.0.4280.88 |

**Comment by afc163** [comment]
```diff
function filter(inputValue, path) {
- return path.some(option => option.label.toLowerCase().indexOf(inputValue.toLowerCase()) > -1;
+ return path.some(option => option.name.toLowerCase().indexOf(inputValue.toLowerCase()) > -1;
}

ReactDOM.render(
  <Cascader
    options={options}
    onChange={onChange}
    placeholder="Please select"
    showSearch={{ filter }}
  />,
  document.getElementById("container")
);
```

`filter` 里可以任意比较 option 下的任意属性，所以不需要 `optionFilterProp` 了。

**Comment by Overcase** [comment]
@afc163 默认返回 true 之后会报错，Cascader 组件中有使用 label 去做什么事请吗？
![image](https://user-images.githubusercontent.com/32009993/116496974-e139dc80-a8d8-11eb-8b77-8323875131f9.png)

**Comment by binghuis** [comment]
> @afc163 自定义 label 为 ReactNode 的情况下，filter 返回 true 之后会报错，Cascader 组件中有使用 label 去做什么事请吗？
> ![image](https://user-images.githubusercontent.com/32009993/116496974-e139dc80-a8d8-11eb-8b77-8323875131f9.png)
> ![image](https://user-images.githubusercontent.com/32009993/116497086-1e9e6a00-a8d9-11eb-82c2-8525a6c004d5.png)

我也遇到了这个问题，react 17，antd 4.17.6，label只要设置了节点属性，搜索就会报错，就算我不用label字段做对比

**Comment by nlx0201** [comment]
我也遇到了这个问题

**Comment by nlx0201** [comment]
4.0版本的支持太不给力了，好多问题提出来都没有解决

**Comment by nlx0201** [comment]
@afc163 麻烦解决一下，还有datepicker的问题
https://github.com/ant-design/ant-design/issues/31081

**Comment by Crystal2030** [comment]
同样遇到这个问题，请问有人解决吗

**Comment by any1024** [comment]
> 同样遇到这个问题，请问有人解决吗

看了下 5.0 中已经修复了
