### ISSUE TITLE
antd table  根据后台返回的 dataSource 去渲染不同的 filterDropdown 筛选项

### ISSUE THREAD

**Issue by wangcongyi** [ant-design/ant-design#30342]
### What problem does this feature solve?
filterDropdown 不能根据 dataSource  动态渲染，只能提前写死，

### What does the proposed API look like?
filterDropdown  能获取当前行数据

**Comment by afc163** [comment]
不太理解这个需求，具体描述一下？

**Comment by wangcongyi** [comment]
希望：table 的 columns 的  filterDropdown 是根据后台返回的数据来渲染筛选项的。

```js

dataSource = [
  { xxx: 'aaa', 
    filterItem: [1, 2, 3],
    ....
  }
 { xxx: 'bbb', 
   filterItem: [1, 2, 3],
    ....
  }
]

```

希望: 可以根据后台返回的  filterItem 字段去渲染筛选项。
查看文档发现 filterDropdown 是不能获得每行的数据的。

```js

filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters }) => {...}
filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters }, record) => {...}

```

**Comment by afc163** [comment]
可以参考 https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel 封装一个生成不同 filterDropdown 的函数。

**Comment by wangcongyi** [comment]
@afc163 是 OK 的，但想优雅一点。
希望和 columns 的 render 函数一样，可以拿到每行的数据。
