### ISSUE TITLE
Sider collapsedWidth not work in Menu

### ISSUE THREAD

**Issue by zhuwy** [ant-design/ant-design#30355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cebianbuju-antd4153-forked-svldm?file=/index.js)

### Steps to reproduce
set Sider prop collapsedWidth={60}
collapse the Sider

### What is expected?
Menu width is 60

### What is actually happening?
Menu width is 80 (which is the defaultValue of the collapsedWidth prop in Sider)

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 16.14.0 |
| System | macOS Catalina 10.15.7 |
| Browser | chrome 90.0.4430.85 |

---
notice that the .ant-menu-inline-collapsed class seem to has hardcode style：
width: 80px

**Comment by xrkffgg** [comment]
收起的时候 动态给 Menu 加一个 `style={{ width: 40 }}`
