### ISSUE TITLE
修改Table组件的垂直滚动条后，Table会无限变宽

### ISSUE THREAD

**Issue by CaptainJon** [ant-design/ant-design#30358]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/antd-reproduction-template-forked-q7hid?file=/index.js

### Steps to reproduce
项目整个页面是用flex布局的，分为左中右结构，分别占用flex的值为1，2，1，Table组件位于最右侧里面，宽度占用flex:1的空间。表格数据过多，当我尝试修改表格垂直滚动条的样式的时候，是设置给.ant-table-body的，样式是生效了，但是表格宽度变得无限长，而且一直在变长，往左边开始挤压，挤压不了了就往右变长，达到几万像素，这不知道是什么引起的，是不是和flex布局有关呢？但是只有我尝试修改这个滚动条样式的时候才会这样，不修改滚动条，一切都是正常的。

### What is expected?
解决问题

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17.0.2 |
| System | win10 |
| Browser | Google版本 90.0.4430.93（正式版本） |

---
样式写法如下：
.ant-table-body {
      &::-webkit-scrollbar {
        width: 6px; 
      }
      &::-webkit-scrollbar-thumb {
        border-radius: 5px;
        -webkit-box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.2);
        background: rgba(129, 129, 128, 0.85);
      }
      &::-webkit-scrollbar-track {
        -webkit-box-shadow: none;
        border-radius: 0;
        background: rgba(0, 4, 40, 0.06);
      }
}

**Comment by CaptainJon** [comment]
I have just updated the post, you can follow this link https://codesandbox.io/s/antd-reproduction-template-forked-q7hid?file=/index.js to review

**Comment by CaptainJon** [comment]
@xrkffgg updated

**Comment by xrkffgg** [comment]
我用的 mac 看不到 😅

**Comment by CaptainJon** [comment]
@xrkffgg 看不到是啥意思啊，打不开链接？我朋友都能打开呀

**Comment by xrkffgg** [comment]
能打开，看不到你描述的现象

**Comment by CaptainJon** [comment]
@xrkffgg 应该可以看到右侧展示的表格 在无限延长宽度呀  按理它只占右侧1份宽度  对了 你必须在谷歌浏览器下  因为是调用的谷歌浏览器滚动条样式

**Comment by xrkffgg** [comment]
我这里表格没有在延长。
是用的 Chrome

**Comment by huntdream** [comment]
![chrome-capture](https://user-images.githubusercontent.com/7903755/116656718-ba0a0a80-a9bf-11eb-91a5-d4bc5749c48a.gif)
windows下确实有这个问题

**Comment by CaptainJon** [comment]
@xrkffgg 看 你楼下有人截图了

**Comment by CaptainJon** [comment]
@huntdream 是吧，知道怎么解决不，项目中正在用

**Comment by xrkffgg** [comment]
windows 特有的

**Comment by CaptainJon** [comment]
@xrkffgg 大佬你看下吧，这个问题挺严重的，其实我觉得antd应该自己做一套自定义滚动条的

**Comment by afc163** [comment]
mac 下也能重新，把系统滚动条打开即可。

**Comment by zombieJ** [comment]
Table 获取滚动条是初始化时创建一个 div 测算。修改滚动条就匹配不到了。

**Comment by afc163** [comment]
目前的方式还是全局计算：https://github.com/react-component/util/blob/master/src/getScrollBarSize.js 这个和 rc-table 5.x 的逻辑一样。https://github.com/react-component/table/blame/5.x/src/utils.js

要把 dom 结构放到当前的 Table 位置（或者增加对应的 className），尽可能让 css 样式应用到计算 scrollbar 宽度的节点上。

参考 rc-table 6.x 的实现 https://github.com/react-component/table/pull/333/files

**Comment by kaioduarte** [comment]
I'm facing a similar issue :/ `scroll={{ x: 'max-content' }}` fixed that a while ago but it's not working either.


https://user-images.githubusercontent.com/11046907/116945043-a2a47900-ac6e-11eb-93e4-2a67886e088f.mp4

**Comment by wangpeng1994** [comment]
My situation:

MacOS chrome Version 90.0.4430.212 (Official Build) (x86_64)

Flex layout + antd Table + scroll={{ y: 240 }}

So I got the same problem. The width of the table increases indefinitely after I add scrollY prop to Table.

Then, I found a solution:
[https://www.cnblogs.com/joe235/p/13728398.html](https://www.cnblogs.com/joe235/p/13728398.html)

Use another div to wrap the Table, and add the css. No matter wheather reset the native chrome srollbar(I reset scrollbar):

```csss
      .tableWrap {
        position: relative;
        flex: 1;

        .myTable {
          position: absolute;
          width: 100%;
        }
      }
```

```html
     <div with flex layout>
          <div className={style.tableWrap}>
            <Table
              className={style.myTable}
              rowKey="id"
              scroll={{ y: 240 }}
              pagination={false}
              columns={columns}
              dataSource={tableData}
            />
          </div>
    </div>
```

**Comment by kaioduarte** [comment]
@wangpeng1994, it works but for my cases, I'll have to style too many layers

**Comment by CaptainJon** [comment]
@xrkffgg  大佬，我这个问题是在哪个版本中进行修复啊？最近的changelog里没找到

**Comment by yoyo837** [comment]
> @xrkffgg 大佬，我这个问题是在哪个版本中进行修复啊？最近的changelog里没找到

4.16.0

**Comment by peng307git** [comment]
4.16.13现在并没有修复这个问题啊！

**Comment by kangyana** [comment]
给有“flex: 1”的外层一个“position: 'relative'”就行了

**Comment by li9269391** [comment]
4.18.0 还是出现了

**Comment by zhangzhuang15** [comment]
我的项目也出现了这个问题，我只是给.antd-table-body 设置了 overflow-y: auto !important

**Comment by Onaffair** [comment]
.ant-table-wrapper{
flex:1;
width:0;
}
这样子可以解决
