### ISSUE TITLE
Table column 中 onFilter 的value参数，是否可以多提供几种类型或者返回的是所输入的查询参数的原内容，比如onFilter中的value为一个数组。

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#30368]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前来看，onFilter中的value属性是string | number | boolean类型的，但是有一个问题是如法进行一个范围型的筛选，比如一个时间的列进行筛选，通常来说做一个范围的筛选更好些。

### What does the proposed API look like?
自定义onFilter逻辑时，可以提供输入的查询参数原数据，而不是拆开后的每一个值。

**Comment by afc163** [comment]
这种需求建议用自定义筛选菜单来做。https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel

**Comment by zmbxy95** [comment]
一样的啊，使用自定义的筛选菜单，setSelectedKeys([])，最终在onFilter中的value，仍然是将数组中的每一个值取出来，分别调用onFilter啊。至少目前通过控制台打印看到的结果是这样的。 @afc163

**Comment by afc163** [comment]
> What does the proposed API look like?

你期望的 API 是什么样的呢？

**Comment by zmbxy95** [comment]
onFilter中的value值与setSelectedKeys的值是相同的。比如说setSelectedKeys([1,2])，onFilter中的value为[1,2] 。@afc163

**Comment by UnicornXU** [comment]
> onFilter中的value值与setSelectedKeys的值是相同的。比如说setSelectedKeys([1,2])，onFilter中的value为[1,2] 。@afc163

大佬 后面是怎么实现的
