### ISSUE TITLE
Tabs - Design consistency when tabPosition={"bottom"}

### ISSUE THREAD

**Issue by visvadw** [ant-design/ant-design#3036]
Hello everybody,

For design consistency reasons, when `Tabs` are positioned at the bottom using `tabPosition` prop, the highlight bar should be placed at the top.

For `left` and `right` options, this rules applies correctly.

Existing 'Position' demo of Tabs component illustrates it.

Thanks.

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/695

It's by designed.

But.. it is really confusing.

cc @afc163 @Chinglik
