### ISSUE TITLE
Spin组件中的最后一句话：Spin.setDefaultIndicator(indicator: ReactNode)你可以自定义全局默认 Spin 的元素。

### ISSUE THREAD

**Issue by IversonTian** [ant-design/ant-design#30360]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
无

### What is expected?
可以全局配置页面的加载动画

### What is actually happening?
Spin，且不知道Spin写在何处

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | Ant Design Pro V5.0 |
| System | Windows10 |
| Browser | Google Chrome |

**Comment by IversonTian** [comment]
![image](https://user-images.githubusercontent.com/38484790/116553333-977ae180-a92c-11eb-9d6d-55dc28019006.png)

**Comment by afc163** [comment]
静态方法，写在你应用的入口文件处即可。

**Comment by afc163** [comment]
app.tsx

**Comment by IversonTian** [comment]
> app.tsx
好了，谢谢你 ）：
@afc163
