### ISSUE TITLE
当Popover内包含Popconfirm时，点击Popconfirm的取消或者确定会关闭下层的Popover

### ISSUE THREAD

**Issue by zuiidea** [ant-design/ant-design#3037]
当Popover内包含Popconfirm时，点击Popconfirm的取消或者确定会关闭下层的Popover

使用场景如下图：

![image](https://cloud.githubusercontent.com/assets/16070518/18497721/5142ce00-7a63-11e6-9603-681e1cb5beaa.png)

在线演示：http://codepen.io/zuiidea/pen/ALEwNA?editors=001

**Comment by xutou12** [comment]
这个需要自己控制显示隐藏了，默认的动作肯定不行了

**Comment by zuiidea** [comment]
如上图，如果有多条记录，每条记录都有一个Popconfirm，不可能每条记录都用state控制显隐撒

**Comment by whphhg** [comment]
Same thing happens if you put AutoComplete inside of Popover. When you select an item in AutoComplete the Popover closes.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3438
