### ISSUE TITLE
InputNumber out range hover border color

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#30375]
![image](https://user-images.githubusercontent.com/29775873/116699586-53551300-a9f8-11eb-82af-206f57f65a08.png)

https://ant.design/components/input-number-cn/#components-input-number-demo-out-of-range

InputNumber 超出边界，字体颜色变红提示，hover 边框显蓝，是否将其与 字体颜色统一？

**Comment by afc163** [comment]
暂不修改，红色边框现在用在 Form 校验模式下。
