### ISSUE TITLE
table ellipsis: true  与 fixed 同时存在时, ellipsis 不生效问题

### ISSUE THREAD

**Issue by L924553229** [ant-design/ant-design#30371]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/table-cn/#components-table-demo-resizable-column](https://3x.ant.design/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
无

### What is expected?
ellipsis 生效

### What is actually happening?
ellipsis 不生效

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.8.4 |
| System | window 7 |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28927#issuecomment-767347086
