### ISSUE TITLE
Datepicker onClick Doesn't Apply To Panel

### ISSUE THREAD

**Issue by nrayburn-tech** [ant-design/ant-design#30384]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-os664?file=/index.js)

### Steps to reproduce
Using the example
1. Click the Datepicker input to display the datepicker panel
2. Click anywhere in the datepicker panel that displays
3. Observe that the table sort updates

### What is expected?
The event should stop propagation and the table sort should not update.

### What is actually happening?
The event isn't stopped, it is propagated and sorts the table still.

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17 |
| System | macOS Big Sur |
| Browser | Chromium 90 |

**Comment by kerm1it** [comment]
https://github.com/react-component/picker/pull/245 can't  solve problem fundamentally, becase other component might as well bubble click event.

You can wrap`picker` with `div` and stopPropagation in `div`.
