### ISSUE TITLE
Ant DropdownRender is closing when there is a click on ContextMenu

### ISSUE THREAD

**Issue by cbojaca** [ant-design/ant-design#30385]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/custom-dropdown-antd4152-forked-4lv9p?file=/index.js)

### Steps to reproduce
You create a select component and inside the dropdownRender you create a Tree that will contain the right context Menu on each Item. Once you right-click on the TreeItem you will e able to see that the dropdown will close 

### What is expected?
I'll expect that the menu will only close on clicking outside but it seems that other clicks are firing the unfocus behavior 

### What is actually happening?
The dropdown is closed , and you will have to reopen again 

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
I can't reproduce this problem in your codesandbox, it works well, TreeSelect does not close when right click on tree node.

https://codesandbox.io/s/custom-dropdown-antd4152-forked-4lv9p?file=/index.js:1607-1664

**Comment by cbojaca** [comment]
Hi @afc163 the issue is not on the right click on the TreeNode Item, is when you select an option on the Menu, here is a small GIF on the issue

https://i.stack.imgur.com/YJfe4.gif

**Comment by afc163** [comment]
See https://codesandbox.io/s/custom-dropdown-antd4152-forked-wrw73

**Comment by Drarig29** [comment]
One might think it works fine but we actually don't want to close the dropdown on click on a child element.

For example, I'd like to have a form in the dropdown, so the user needs to be able to click multiple times without the dropdown closing.

**Comment by Drarig29** [comment]
That's because of one of their dependencies. I tried removing this line in my node-modules and it works. But it's not a fix.

https://github.com/react-component/dropdown/blob/4c10f23b646b46f4928ac0bd0b863214da932576/src/Dropdown.tsx#L72

**Comment by Drarig29** [comment]
And... here is the solution: https://github.com/react-component/dropdown/issues/123#issuecomment-687365833
