### ISSUE TITLE
antd2.0 index.d.ts里面的组件不齐全

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#3039]
#### 发生问题的环境是：

- antd 版本: 2.0.0-beta.2
- 操作系统及其版本: window10
- 浏览器及其版本: chrome 54.0.2832.2 dev-m (64-bit)

#### 您做了什么？

使用typescript去写antd

#### 实际上的结果是：

antd的index.d.ts中，缺失了很多组件，例如Table，Form，而且有一些组件的d.ts文件中是空的，例如alert、card、message等

**Comment by benjycui** [comment]
Try `antd@2.0.0-beta.3`.

**Comment by benjycui** [comment]
`.d.ts` 文件应该都是有的，不过可能还不怎么完善，

**Comment by afc163** [comment]
随时给我们 PR ~

**Comment by infeng** [comment]
我看一下哪些组件的声明不全的，然后完善一下

**Comment by benjycui** [comment]
有问题随时 PR，issue 先关了。
