### ISSUE TITLE
DatePicker mask

### ISSUE THREAD

**Issue by steffany-cruz** [ant-design/ant-design#30394]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
currently, when user enters a date on datepicker field without / the date is not valid and just disappears, it should be automatically filled

### What does the proposed API look like?
i thought that the format we define in the component should also define the mask automatically (like MM/DD/YYYY or MM-DD-YYYY) and the user just enters the numbers

**Comment by afc163** [comment]
Sorry, we don't provide this feature due to no enough time.
