### ISSUE TITLE
Can't edit DatePicker cells for picker="Year || Quarter"

### ISSUE THREAD

**Issue by genternava** [ant-design/ant-design#30395]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

So i want to edit cell of date picker with type year and quarter same as for month which is monthCellRender, this is the url that i managed to do with type month and i want the same thing with year and quarter can someone tell me if this is possible? 

https://codesandbox.io/s/basic-antd4154-forked-8yhlv

**Comment by afc163** [comment]
Duplicate of #29625
