### ISSUE TITLE
Upload component crushes on file load if beforeUpload returns false.

### ISSUE THREAD

**Issue by OleksandrAntonenko1** [ant-design/ant-design#30390]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bo8ml)

### Steps to reproduce
Set beforeUpload property to false. And upload a picture.

### What is expected?
The picture will be handled on onChange function;

### What is actually happening?
The component throws an error: Unhandled promise rejection TypeError: Object doesn't support this action.

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | latest |
| System | Windows  |
| Browser | IE11 |

---
It is hard to reproduce this bug cause the proposed playgrounds don't support an IE11 and the main site don't work there too. But if you run it locally it is easy to do.
https://caniuse.com/fileapi

**Comment by kerm1it** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/30391
