### ISSUE TITLE
新增组件 calendar

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#304]
- 视觉稿：待定
- 交互要求：待定

**Comment by zhujun24** [comment]
先占个坑

**Comment by afc163** [comment]
1. 支持年/月切换。
2. 支持自定义日期格式展现。

类似

![](https://t.alipayobjects.com/images/rmsweb/T1FHpiXhFkXXXXXXXX.png)

**Comment by afc163** [comment]
可以尝试用 https://github.com/react-component/calendar/blob/2ab5bcd283ecd4c1e032be5aa9fb76149a083477/src/index.js#L6 封装实现，如果不能满足。fork 修改或给 @yiminghe 承玉提需求。

**Comment by afc163** [comment]
https://github.com/react-component/calendar 已经升级到 4.x 。@chentony

**Comment by Chinglik** [comment]
视觉稿已出。
![—](http://demo.alibaba-inc.com/categories/1977/projects/13137/vds/186946 )

**Comment by afc163** [comment]
:+1:

**Comment by okoala** [comment]
专业 +1

**Comment by popomore** [comment]
有代办事项详情么

**Comment by afc163** [comment]
事项属于业务范畴，组件里不实现。

**Comment by afc163** [comment]
wait for https://github.com/react-component/calendar/pull/78
