### ISSUE TITLE
Upload 上传非accept文件时，获取不到任何file信息

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#30403]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在历史issue中找了一下，该问题在 #29973 中有提及到，但这里还是想再提一次，个人看法，对于一个功能，对于禁止的型为（上传非accept文件），是否要选择忽略掉，应当是根据业务需求来的，而不是组件本身去选择性的忽略掉，这样未免有点一棒子打死的感觉。对于上传的accept过滤，有必要，但是相应的，例如在windows电脑下，仍然可以选择其他类型的文件，那么相应的提示甚至是用户反馈也是有必要的。
这个问题的解决，是否可以考虑下如下方案：
accept过滤是有必要的，对于选择的一些非accept，当然，如果说beforeUpload是对允许上传并且即将上传到服务端的文件的一个处理，那么是否可以考虑增加一个onError的函数，处理一些对非accept文件的处理，甚至是对于文件的maxSize的处理等。

### What does the proposed API look like?
期望在设定accept下，选择非accept文件时，有相应的反馈。

**Comment by kerm1it** [comment]
觉得可以在手动执行（选择目录、拖拽、windows 中选择了 非 accept 文件） accept 之前加一个类似于 onSelect 的 API，执行后再去让 accept 过滤。

这时如果是在 windows 上，当用户选择了非 accept 文件，可以在 onSelect 里面加一些错误提示逻辑，然后到 accept 处理时会过滤掉

**Comment by zombieJ** [comment]
> 觉得可以在手动执行（选择目录、拖拽、windows 中选择了 非 accept 文件） accept 之前加一个类似于 onSelect 的 API，执行后再去让 accept 过滤。
> 
> 这时如果是在 windows 上，当用户选择了非 accept 文件，可以在 onSelect 里面加一些错误提示逻辑，然后到 accept 处理时会过滤掉
> 
> 或者加一个类似 onUnaccept 的 API，在被过滤掉的时候执行。

分两点：
1. `accept` 本身就是过滤。用户把类型强制改成 `所有文件` 不接受后续事件是对的。
2. `accept` 接收非法类型时，不应该过滤。而是直接和原生一样放行即可。

**Comment by kerm1it** [comment]
第2点赞同，原生保持一致

第1点，这样处理本身是没有错的，但是就会有 windows 可以选择所有文件的这种意外情况，有的需求就希望这时候选择非 accept 文件能够给用户一个反馈，觉得这也是合理的，之前也有人有类似的需求。

**Comment by zombieJ** [comment]
👌，那 API 最好还是再斟酌一下。太多 API 也不是一个很好的设计。

**Comment by afc163** [comment]
> 2. accept 接收非法类型时，不应该过滤。而是直接和原生一样放行即可。

+1

**Comment by lch1677** [comment]
@kerm1it 
遇到了一个新的问题，accept限制文件格式，mac上传rar格式文件正常，但是windows上传相同的文件返回的type是空值，导致beforeUpload没有捕获到上传的文件。
@zombieJ 这是一个好的建议。
> 2. `accept` 接收非法类型时，不应该过滤。或者直接和原生一样放行即可。

**Comment by kerm1it** [comment]
看看这个，https://github.com/ant-design/ant-design/issues/19211

**Comment by afc163** [comment]
Fixed in 4.15.6

**Comment by kerm1it** [comment]
这个还没有修复，这个版本改的是无效的 accept 值会跳过，还需要讨论，怎么加 API，让用户在 window 上选择所有文件时选择了 非 accept 文件，通过一个钩子给用户一个反馈。

**Comment by afc163** [comment]
@zombieJ 有空看看

**Comment by zombieJ** [comment]
感觉从奥卡姆剃刀看，我们应该是如果上传文件夹就过滤一下，如果不是文件夹就都放行。这样也贴合原生行为，也避免额外的 API。

**Comment by kerm1it** [comment]
这样不解决 window 上的问题，当用户使用 accept 限制了类型，还是可以使用 '选择所有类型' 的选项，选择非 accept 的文件。

**Comment by kerm1it** [comment]
OK，那这个到时是不是得发个 minor？

**Comment by kerm1it** [comment]
@zmbxy95 

目前是这样修改的：

只有当选择目录的时候使用 accept 过滤，否则直接放行。

这样以来如果在 windows 上选择非 accept 文件，就会进入 beforeUpload，可以在里面加入自己的过滤逻辑（提示反馈），如果选择的目录中有非 accept 文件，使用 accept 过滤后不进入 beforeUpload 也是合理的。

**Comment by zmbxy95** [comment]
OK，谢谢！
