### ISSUE TITLE
路由前进、后退不能销毁Modal问题。

### ISSUE THREAD

**Issue by zhouchao1314** [ant-design/ant-design#30404]
使用 Modal.destroyAll() 可以销毁弹出的确认窗(Modal.info、Modal.success、Modal.error、Modal.warning、Modal.confirm)。通常用于路由监听当中，处理路由前进、后退不能销毁确认对话框的问题。

但是没办法销毁
![image](https://user-images.githubusercontent.com/56708943/117240703-0643c780-ae64-11eb-945e-f85a0413a362.png)
如下方式打开的表单 ，不知道有没有什么解决方案呢？

**Comment by yoyo837** [comment]
Modal在你路由的页面的话，说明是你路由页面没有销毁

**Comment by zhouchao1314** [comment]
> Modal在你路由的页面的话，说明是你切换路由时路由页面没有销毁

是的，我使用了 antd-pro-page-tabs 多页签的功能，在切换路由的时候路由页面没有销毁，不知道有啥解决方案不？
