### ISSUE TITLE
路由前进、后退不能销毁Modal问题。

### ISSUE THREAD

**Issue by zhouchao1314** [ant-design/ant-design#30405]
使用 Modal.destroyAll() 可以销毁弹出的确认窗(Modal.info、Modal.success、Modal.error、Modal.warning、Modal.confirm)。通常用于路由监听当中，处理路由前进、后退不能销毁确认对话框的问题。

我使用了 antd-pro-page-tabs 多页签功能，在后退，前进的时候 ，路由页面并没有销毁，但是我希望Modal 能像Modal.info、Modal.success、Modal.error、Modal.warning、Modal.confirm)这些一样它可以自动关闭掉。不知道是否有解决方案呢？

**Comment by yoyo837** [comment]
`antd-pro-page-tabs`, 不是由`antd`维护的，且多页形式页面路由必须不销毁，请自行从离开页面隐藏，回到页面显示等方向自行解决。

**Comment by zhouchao1314** [comment]
> `antd-pro-page-tabs`, 不是由`antd`维护的，且多页形式页面路由必须不销毁，请自行从离开页面隐藏，回到页面显示等方向自行解决。

非常感谢！
