### ISSUE TITLE
Upload的defaultFileList只能设置一次吗？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#3040]
#### 您做了什么？

我将一个upload控件包在modal控件里，当点开Modal的时候设置upload的defaultFileList属性，关闭的时候置空upload的defaultFileList属性

#### 您期待的结果是：

点开Modal的时候upload可以显示我设置的defaultFileList，关闭的时候能把defaultFileList置空，再次点开后Modal的时候可以看到upload的defaultFileList被重置了

#### 实际上的结果是：

第一次点开Modal能显示我设置的defaultFileList，再点开就无法改变defaultFileList了，显示的还是上次的

#### 可重现的在线演示

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
是，建议学习 React 受控组件的概念。

**Comment by Yhaojing** [comment]
怎么解决的这个问题，我也遇到一样的问题了
