### ISSUE TITLE
select 仅单选功能, 可手写新增option(非筛选),新增option后其余option禁用, 

### ISSUE THREAD

**Issue by simborgem** [ant-design/ant-design#30411]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用select选择内容, 但是需要手写新增option,  而不是使用dropdownRender (曾尝试使用拓展菜单的方式实现, 但是出现了select内的input无法输入内容, 点击input, select就自动失焦了,导致无法在input输入内容进行新增option), 因此需要一个可直接手写新增option的功能, 使用mode=tag方式多选了无法设置唯一选择

### What does the proposed API look like?
single

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu

**Comment by simborgem** [comment]
> https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu

尝试用过了, 但是里面的input无法输入内容, 直接复制demo上去的,点击input就直接失焦了

**Comment by afc163** [comment]
demo 是可以运行的，如果你的例子无法生效，请提供重现链接。

**Comment by simborgem** [comment]
> demo 是可以运行的，如果你的例子无法生效，请提供重现链接。
好奇怪, 在我项目里无法聚焦到input去, 但是在线编辑平台却又可以, 我已经想到其他的处理的方案了,但是需要一个清空内容的API, 请问一下有select里面有可以直接调用清空内容的API吗, <select allowClear />,  这个arrow的点击事件
