### ISSUE TITLE
Form.List 渲染表单相关操作函数，能否暴露到 Form.List 外面？

### ISSUE THREAD

**Issue by fubd** [ant-design/ant-design#30414]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望在 Form.List 外部 通过 add/remove/move 控制 Form.List 的渲染。

### What does the proposed API look like?
在 Form.List 外部获取到 add/remove/move 函数。

**Comment by afc163** [comment]
Try https://github.com/ant-design/ant-design/issues/27177#issuecomment-712592969

**Comment by fubd** [comment]
> Try [#27177 (comment)](https://github.com/ant-design/ant-design/issues/27177#issuecomment-712592969)

这里add的调用是在Form.List里面吧，和issue主题有什么关联吗

**Comment by crazyair** [comment]
可以用 setFields 改变该字段的值来实现

**Comment by zjy135** [comment]
我需要拖动排序Form.List 内的FormItem, 无法在Form.List外部调用move, 请问该如何解决啊 @afc163

**Comment by marlti7** [comment]
同样问题 有人解决了吗 如何外层拿到 相关操作函数
