### ISSUE TITLE
Calendar Selectable function

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3042]
calendar组件顶部的年份和月份的下拉选择框显示的都是点，选中了某一天后，也没有暴露的API响应事件

**Comment by afc163** [comment]
calendar 是日历，不是日期选择，没有选择行为。

**Comment by RifeWang** [comment]
我不想要DatePicker的下拉框，只想要一个日历，另外日历也可以有选择行为啊

**Comment by RifeWang** [comment]
@afc163 我还是觉得日历组件太过于简单，暴露的API太少

**Comment by afc163** [comment]
Calendar 还是需要相应的选中行为：http://react-component.github.io/calendar/examples/full-calendar.html

**Comment by jinmmd** [comment]
支持，我在使用日历组件时也有同样需求，需要能够在被点击的日期上获取值并操作。目前通过dateCellRender无法满足这一需求。
一种应用场景是，博客的日历，点击日期可以展示出对应的博文。

**Comment by benjycui** [comment]
如下调整可好？

* `value` `defaultValue` alias 为 `showDate` `defaultShowDate` 以明确含义。
* 新增 `selectedDate` `defaultSelectedDate` 与 `onSelect` 来满足选择功能。

**Comment by benjycui** [comment]
FYI 在 react-component 这一层 selectedValue 才是用户选中的值，value 意思是当前展示的面板。

概念和 antd 这一层混淆了。。
