### ISSUE TITLE
Typography的ellipsis在高分辨率屏下显示异常

### ISSUE THREAD

**Issue by huajiayi** [ant-design/ant-design#30426]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/typography-cn/#components-typography-demo-ellipsis](https://ant.design/components/typography-cn/#components-typography-demo-ellipsis)

### Steps to reproduce
在2k屏下，查看设置了ellipsis的Text部分（系统分辨率为2560*1440）

### What is expected?
Text只在一行显示，不换行

### What is actually happening?
Text显示了两行

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Chrome 89.0.4389.128（正式版本）（64 位） |

**Comment by xrkffgg** [comment]
第一个例子吗？

**Comment by huajiayi** [comment]
是的，省略号的Text部分

**Comment by huajiayi** [comment]
> 第一个例子吗？
是的，省略号的Text部分

**Comment by huajiayi** [comment]
> 第一个例子吗？

是的，省略号的Text部分

**Comment by xrkffgg** [comment]
我这里看着是正常的

**Comment by afc163** [comment]
Duplicate of #19219
