### ISSUE TITLE
ConfigProvider的prefixCls属性对Message组件里的icon不生效，前缀没有替换掉

### ISSUE THREAD

**Issue by zengqingzhuang** [ant-design/ant-design#30425]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)

### Steps to reproduce
ConfigProvider.config({
  prefixCls: 'fcn'
})
<ConfigProvider prefixCls='fcn' iconPrefixCls='fcn-anticon'></ConfigProvider>

### What is expected?
message组件里的icon前缀也替换掉，变成fcn-anticon fcn-anticon-check-circle

### What is actually happening?
message组件里的icon前缀没有替换掉，用的还是anticon anticon-check-circle

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17 |
| System | mac |
| Browser | chrome90.0.4430.93 |

**Comment by afc163** [comment]
https://ant.design/components/message-cn/#FAQ
