### ISSUE TITLE
Tree: disabled node is not counted for checked state of parent node (antd 4)

### ISSUE THREAD

**Issue by cnt-null** [ant-design/ant-design#30430]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-tree-checked-state-issue-sq7ny)

### Steps to reproduce
Just run the code.

### What is expected?
a is checked, and x is not checked.

### What is actually happening?
a is not checked, and x is checked.

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.2 |
| System | any |
| Browser | any |

---
The original issue for antd 3 was closed: https://github.com/ant-design/ant-design/issues/20299.
But it's still relevant for the latest version of antd.

Disabled-ness of nodes should not affect parent node state, because whether a node is disabled reflects a restriction of the operation, while the checked state reflects the current state.

In this demo, it just looks illogical that a node is not checked while its only child is checked, and another node is checked while obviously its 1st child is not checked.

**Comment by zombieJ** [comment]
https://ant.design/components/tree/#What-does-disabled-node-work-logic-in-the-tree
