### ISSUE TITLE
table组件中，总结栏如何放在表头下面一行？

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/ant-design#30431]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通常用户希望尽快看到总结数据，所以可以把总结栏放在第一行是有必要的

### What does the proposed API look like?
summary: {
  position: 'top' | 'bottom'
}

**Comment by hemengke1997** [comment]
跟这个需求类似 #25116 .. 且发现有同学pr过快一年了还没merge.. T>T

**Comment by afc163** [comment]
Duplicate of #23170

**Comment by F-happy** [comment]
现在在 antd 5.3.0版本上 top 不好使了
