### ISSUE TITLE
When change mode on button - default - disable - default, Tooltip invisible 

### ISSUE THREAD

**Issue by PavelRazumov** [ant-design/ant-design#30448]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/antd-calendar-tz-arr9qm?file=index.css](https://stackblitz.com/edit/antd-calendar-tz-arr9qm?file=index.css)

### Steps to reproduce
We use Tooltip and Button components (defaut button and tooltip (on hover tooltip visible)).
1. Button component in Sticky container (it's important !!)
2. If we use sticky container and scroll, then must use getPopupContainer() to set container for tooltip on button.
3. On Click button have disable mode and after some time change to default
4. On first render all work correct - execute -> getPopupContainer() and set data.
5. Click again on button, then tooltip invisible - not execute getPopupContainer() and not set new node for button after disable mode

### What is expected?
Expected see tooltip after disable mode

### What is actually happening?
On Next render tooltip invisiblee

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React |  "react": "^17.0.1", |
| System | Windows |
| Browser |  any |

**Comment by afc163** [comment]
See https://stackblitz.com/edit/antd-calendar-tz-f2ckv5?file=index.js

**Comment by PavelRazumov** [comment]
Thank you!!
