### ISSUE TITLE
Rate element: Remove hover effect when leaving with mouse

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ant-design/ant-design#30449]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It's strange that I have to click away to make the stars look with the standard size. See gif:
![](https://i.imgur.com/uqKF5LL.gif)

### What does the proposed API look like?
No API change, even though making the animation optional altogether will be nice.

**Comment by Sarper-Ekinci** [comment]
Can I take the issue ?

**Comment by sarpere** [comment]
Can I take the issue ?

**Comment by justanotheranonymoususer** [comment]
Yes please
