### ISSUE TITLE
form autocomplete not working

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/ant-design#30440]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-bash-b76jr?file=/src/App.tsx)

### Steps to reproduce
1. Input text in `autocomplete not working` 
2. Hit submit or hit enter
3. Delete text in text field, then click in the input

### What is expected?
It is expected that the browser autocomplete will show the previously entered value.

### What is actually happening?
There is no autocomplete

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome  90.0.4430.93 |

---
`Button` 组件的 onclick 中使用了 e.preventDefault() 导致 autocomplete 失效。

**Comment by afc163** [comment]
Button with `loading` is designed to be not clickable.
