### ISSUE TITLE
[Step-By-Step] instructions for synchronizing the latest upstream branch code

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#30441]
对于 Fork 的项目来说，如果你发起了一个 PR，但遇到需要同步最新的 upstream 分支最新代码时，经常需要同步出错，提交他人 commit 信息的情况。

最近 GitHub 新推出了一个功能，方便你在无代码冲突的情况下，**快捷、正确** 的同步最新上游代码分支。

---

For fork repo, if you create a PR, and when you need to synchronize the latest code of the latest upstream branch, may often need to synchronize errors and submit others' commit information.

Recently, GitHub has launched a new feature to facilitate you **quickly and correctly** synchronize the latest upstream code branches without code conflicts.

---

### Step 1

点击 PR 的提交 **分支名称** 进入自己 fork 项目的分支里。

Click the PR submission **Branch Name** to enter the branch of your fork project.

![](https://user-images.githubusercontent.com/29775873/117528115-23fb6300-b003-11eb-91f2-6edee7adb702.jpg)

### Step2

这里会列出自己 fork 项目的代码，相对于上游分支的改变。这里为5条超前，6条落后。点击 <kbd>Fetch and merge</kbd> 即可完成分支同步。

Here will list the code of your fork project, relative to the changes in the upstream branch. Here, 5 are ahead and 6 are behind. Click <kbd>Fetch and merge</kbd> to complete branch synchronization.

![](https://user-images.githubusercontent.com/29775873/117528152-5311d480-b003-11eb-8d86-d5ac9c4fe0f0.jpg)

**Comment by jueinin** [comment]
这个不太适合发issue吧
