### ISSUE TITLE
Table rowExpandable not work when table dataSource has Children attribute

### ISSUE THREAD

**Issue by akalittle** [ant-design/ant-design#30444]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shuxingshujuzhanshi-antd4154-forked-01n33?file=/index.js)

### Steps to reproduce
show in codesandbox reproduce link

### What is expected?
when children is a empty array, the expandable icon will not display.

### What is actually happening?
the icon display

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 16.14 |
| System | macos bis sur 11.2 |
| Browser | Chrome 90.0.4430.85 |

**Comment by akalittle** [comment]
But if I had my own `expandable.rowExpandable ` 
I can  decide  the expandable icon to show or not to show
@afc163

**Comment by Vsion** [comment]
i agree with u @akalittle
