### ISSUE TITLE
Upload.Dragger拖拽文件上传时，将文件拖拽到上传区域会打开一个新标签页

### ISSUE THREAD

**Issue by workermx** [ant-design/ant-design#30447]
![1620467051(1)](https://user-images.githubusercontent.com/22365128/117534684-1e167980-b025-11eb-801d-01ce0147cde4.jpg)
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuozhuaishangchuan-antd4154-forked-o7bri?file=/index.js)

### Steps to reproduce
拖拽文件至上传区

### What is expected?
仅将被拖拽的文件加入到等待上传队列

### What is actually happening?
将文件拖拽到上传区后，打开了一个新标签，新标签的URL是文件在本地的地址

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 16.14.0 |
| System | Windows10 |
| Browser | Firefox Browser 88.0.1(64位) |

**Comment by workermx** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-mmi96?file=/index.js

**Comment by afc163** [comment]
I can't reproduce in your codesandbox.

**Comment by kerm1it** [comment]
我这边也没有复现， @workermx 这种情况一般是将文件没有拖到上传区域导致的，你确认一下拖的时候上传区域有没有高亮（蓝色边框）
