### ISSUE TITLE
Upload 组件上传错误，hover提示信息可以自定义吗？

### ISSUE THREAD

**Issue by VanLee1212** [ant-design/ant-design#30459]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Upload 组件上传错误，hover提示信息可以自定义吗？

### What does the proposed API look like?
Upload 组件上传错误，hover提示信息可以自定义

**Comment by afc163** [comment]
https://ant.design/components/upload-cn/#components-upload-demo-defaultFileList

**Comment by afc163** [comment]
后端返回给 response 里加上需要的信息就行了。

**Comment by VanLee1212** [comment]
加个钉钉聊下？
钉钉：ko9oxih
