### ISSUE TITLE
Fixed table header like Confluence default（默认类似 Confluence 的 fix 形式固定表头）

### ISSUE THREAD

**Issue by LinWanCen** [ant-design/ant-design#30456]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The scroll bar is used to fix the header. The user experience is poor. The business asked me if I could be like Confluence.
（滚动条的方式固定表头体验不好，业务问我能不能像Confluence那样。）

### What does the proposed API look like?
Like Confluence, when scrolling down, the header automatically floats at the top.
（像 Confluence 那样，滚动下来时表头自动悬浮在顶端，我尝试过实现，但是做的不是很好，不知道怎么让表头和表的宽度一致，毕竟我是个后端工程师。）

**Comment by afc163** [comment]
See https://ant.design/components/table-cn/#components-table-demo-sticky

**Comment by LinWanCen** [comment]
> See https://ant.design/components/table-cn/#components-table-demo-sticky

I want it like this:

![Confluence fix](https://user-images.githubusercontent.com/14926671/117606872-63ee5180-b18d-11eb-85ad-09da5a32e10b.png)

but it use the scroll bar to achieve this effect

![components-table-demo-fixed-header](https://user-images.githubusercontent.com/14926671/117607000-a7e15680-b18d-11eb-9af7-7f8189a921ce.png)

View code in Confluence, it use `position: fixed`:
```html
<thead class="tableFloatingHeaderOriginal" style="position: fixed; margin-top: 0px; left: 290px; z-index: 3; width: 429px; top: 41px;"><tr role="row" class="tablesorter-headerRow">
```
