### ISSUE TITLE
Message 组件无法单独使用的问题

### ISSUE THREAD

**Issue by Q-Qplus1s** [ant-design/ant-design#30453]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cwfqq?file=/index.js)

### Steps to reproduce
导入组件样式后渲染后无法销毁，

复现链接：https://codesandbox.io/s/antd-reproduction-template-forked-cwfqq?file=/index.js

需要导入全局样式：@import "~antd/lib/style/index.css"; 才行，但这样样式体积过大了

### What is expected?
message 仅导入组件样式即可单独使用：
```css
@import "~antd/lib/message/style/index.css";
```

```js
import { message } from 'antd';
```

### What is actually happening?
message 显示后没有自动消失

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 16.13.0 |
| System | Centos 7 |
| Browser | Chrome Version 83.0.4103.97 (Official Build) (64-bit) |

**Comment by Q-Qplus1s** [comment]
发现应该是需要设置：

```js
message.config({
  top: 60,
  maxCount: 1,
  duration: 3,
  transitionName: 'move-up',
});
```

增加动画参数，这个不是默认的

**Comment by afc163** [comment]
```js
// in your js file
import "antd/lib/message/style";
```
