### ISSUE TITLE
Pass userTyping to custom formatter of InputNumber

### ISSUE THREAD

**Issue by delyanr** [ant-design/ant-design#30455]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Since the recent rewrite of `InputNumber`, which basically ignores the `precision` prop when there is a custom `formatter`, it is important to allow such custom `formatter` to fully replicate the `precision` logic. This requires that `userTyping` is passed down to said custom `formatter`. Whilst migrating to a new version of ant-design, one of my tests is breaking due to this change, and I cannot see any easy solution around it (apart from this feature request).

Reproduction: [codesandbox](https://codesandbox.io/s/antd-input-number-formatter-f7jet)

The reproduction very simply tries to imitate the `precision` prop functionality with a custom `formatter`. The moment a user types a value, the input automatically adds the precision and moves the cursor, making the input unusable. The custom `formatter` would need `userTyping` to prevent that from happening (+ some other situations).

### What does the proposed API look like?
Pass `userTyping` to any custom `formatter` of the `InputNumber` component.

**Comment by afc163** [comment]
>  which basically ignores the precision prop when there is a custom formatter

Could you please provide a reproduce about this problem?

**Comment by delyanr** [comment]
@afc163 I have edited the original post to add a simple reproduction, followed by a paragraph with a quick explanation.

**Comment by delyanr** [comment]
@afc163 Answers to your questions above:
1. Because after the `InputNumber` rewrite, `precision` no longer works together with a custom `formatter` (try in a sandbox to have both a `precision` and a custom `formatter` - precision does NOT work). My custom `formatter` is more complicated than the one in the code sandbox, but it needs to now handle the precision formatting as well, which cannot work without `userTyping`.
2. I want to migrate from v4.12.2 to the latest. Somewhere since that version the `InputNumber` component was rewritten.

**Comment by zombieJ** [comment]
`precision` works on `formatter` is a bug that removed in latest version. Agree with this requirement, `formatter` is more flexible that developer can act.

**Comment by zombieJ** [comment]
What's the best design of additional param?
`formatter(text: string, userTyping: boolean)` or `formatter(text: string, info: { userTyping: boolean })`

cc @ant-design/ant-design-collaborators

**Comment by shaodahong** [comment]
I like `formatter(text: string, info: { userTyping: boolean })`.

**Comment by 07akioni** [comment]
2

**Comment by xrkffgg** [comment]
1
