### ISSUE TITLE
TimePicker 时间段范围选择，如果结束时间小于开始时间会自动交换顺序

### ISSUE THREAD

**Issue by ghostjzf** [ant-design/ant-design#30469]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/time-picker-cn/](https://ant.design/components/time-picker-cn/)

### Steps to reproduce
选择时间结束时间小于开始时间

### What is expected?
期望可以支持不交换，因为有的时候上夜班的时间段就是结束时间小于开始时间

### What is actually happening?
会自动交换

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 16.13 |
| System | MacOS |
| Browser | chrome |

**Comment by kerm1it** [comment]
这个就是这样设计的，时间范围其实就是一个区间，都是从小到大的，你说的夜班的这个场景其实中间隐藏了跨天的逻辑，这个时间选择器的范围选择是在一天之内的24小时。

建议不要用这个范围选择器，拆开两个时间选择器。

**Comment by afc163** [comment]
https://ant.design/components/time-picker-cn/#RangePicker
