### ISSUE TITLE
checkboxgroup初始值设置提示错误

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#3046]
#### 发生问题的环境是：

- antd 版本:^2.0.0-beta.4
- 操作系统及其版本:wind10
- 浏览器及其版本:chrome

#### 您做了什么？
通过 getFieldDecorator('agreement', { initialValue: ['Pear', 'Apple'], valuePropName: 'checked' })
为checkboxgroup组件赋初值

 

#### 您期待的结果是：
成功设置
![image](https://cloud.githubusercontent.com/assets/19165238/18538798/4c8cf3b8-7b44-11e6-92c5-7e34fd99fe08.png)

#### 实际上的结果是：
 getFieldDecorator('agreement', { initialValue: ['Pear', 'Apple'])
![image](https://cloud.githubusercontent.com/assets/19165238/18523770/4b28d3ae-7ae8-11e6-9670-2aeef1ac631a.png)

通过 getFieldDecorator('agreement', { initialValue: ['Pear', 'Apple'], valuePropName: 'checked' })
![image](https://cloud.githubusercontent.com/assets/19165238/18538787/365400e6-7b44-11e6-9f2b-044f29c2dc34.png)

**Comment by benjycui** [comment]
2.0.0-beta.6
