### ISSUE TITLE
DatePicker manual typing incorrect behavior

### ISSUE THREAD

**Issue by pavolgolias** [ant-design/ant-design#30468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-datepicker-k7ipy?file=/index.js)

### Steps to reproduce
1. Open the reproduction link
2. Try to type date (e.g. 2021-10-05) - as you can see, the value in DatePicker panel is correctly highlighted
3. Do NOT press Enter and do NOT click on the DatePicker panel
4. Loose focus from the element - click somewhere outside of DatePicker
5. Input is cleared and value is not selected.

### What is expected?
After correctly typed date value should be stored within DatePicker and probably also onChange should be called. If not, there should be some mechanism (callback) which can be used to catch the typed value and use it.

### What is actually happening?
It is unable to store or use correctly typed value in DatePicker without explicit submit by pressing Enter or by click on the value in DatePicker panel.

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.2 |
| System | Win 10 |
| Browser | Chrome (latest) |

**Comment by pavolgolias** [comment]
Hi, any updates on this? Is there some mechanism (callback) which can be used to catch the typed value and use it?

**Comment by pavolgolias** [comment]
Hi, sorry for repetitive question, I just would like to know if there is some way to deal with the issue described above @afc163 @zombieJ. Thanks :)

**Comment by zombieJ** [comment]
Internal do some logic to handle the value parsing. But maybe can provide  `onInput` function?

**Comment by pavolgolias** [comment]
@zombieJ thanks for the answer. Do you think there is a possibility to add `onInput` callback?

**Comment by sanderdewilde** [comment]
Hi guys, we're struggling with the issue as well.

Our users often choose a value in the picker, and then edit the value manually. When they click away, the original value is retained. The behaviour is correct when pressing enter or tabbing through the form though.

I've tried working around the problem by evaluating `e.target.value` in the `onBlur` callback, but this also returns the original value.

**Comment by tomsimpkins** [comment]
Hi guys, we're also struggling with this.

We tracked this down to a behavior change in RC picker - see the issue raised in https://github.com/react-component/picker/issues/276 which includes a codesandbox.

We've worked around it by resolving to version 2.5.2 of rc picker, but are hoping it would get fixed at source if it is indeed unintended.  

+1 to the `onInput` recommendation too.

**Comment by verissimor** [comment]
+1

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
