### ISSUE TITLE
配置modal的rootPrefixCls提示Modal.config is deprecated. Please use ConfigProvider.config instead.

### ISSUE THREAD

**Issue by birdycn** [ant-design/ant-design#30466]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce

已配置ConfigProvider的prefixCls属性，但modal仍然无法更换antd类名前置，只有配置modal.config的rotPrefixCls才会生效，但是控制台会提示：
配置modal的rootPrefixCls提示Modal.config is deprecated. Please use ConfigProvider.config instead.

### What is expected?
configProvider的prefixCls配置生效，或者去掉提示

### What is actually happening?

已配置ConfigProvider的prefixCls属性，但modal仍然无法更换antd类名前置，只有配置modal.config的rotPrefixCls才会生效，但是控制台会提示：
配置modal的rootPrefixCls提示Modal.config is deprecated. Please use ConfigProvider.config instead.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Please use https://github.com/ant-design/ant-design/pull/29574/files#diff-29a9787b08878f4d453470fe1f780ed83a1864661b3df2f2b52604e7ea5a5dddR7-R9 instead.
