### ISSUE TITLE
打包后@ant-design/icons@4.4太大了，已经使用了tree shaking

### ISSUE THREAD

**Issue by Vibing** [ant-design/ant-design#30460]
![](https://tva1.sinaimg.cn/large/008i3skNly1gqddh527rmj31gz0q4dso.jpg)
---
关于tree shaking 的配置：

// .babelrc
```js
[
      "@babel/preset-env",
      {
        "modules": false
      }
],
```

webpack配置中 mode: 'production' 

是否配置有问题？如果有问题，麻烦大佬告诉我哪里出了问题，应该怎么配置
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Vibing/react-admin](https://github.com/Vibing/react-admin)

### Steps to reproduce
1. git clone https://github.com/Vibing/react-admin.git
2. cd react-admin && yarn
3. yarn dll && yarn build

### What is expected?
@ant-design/icons不要那么大

### What is actually happening?
@ant-design/icons打包后很大

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 17.0.1 |
| System | macOS BigSur11.3.1 |
| Browser | Chrome90 |

**Comment by yoyo837** [comment]
请使用webpack-bundle-analyzer分析开一下，tree shaking是否开启成功

**Comment by yoyo837** [comment]
注意tree shaking开启的4个必要条件 https://webpack.js.org/guides/tree-shaking/#conclusion

**Comment by afc163** [comment]
Remove this line: https://github.com/Vibing/react-admin/blob/94e103cf6dbfa63caab205dbbe223b2255655c53/webpack/webpack.common.js#L17
