### ISSUE TITLE
表格选中所有行且禁用时，表头未显示全选。 table rowSelection not show "check all" when all row "checked and disabled"

### ISSUE THREAD

**Issue by fbambi** [ant-design/ant-design#30476]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuanzehecaozuo-antd4154-forked-2uiov?file=/index.js)

### Steps to reproduce
1. 选中所有行，此时表头选中（全选）
![image](https://user-images.githubusercontent.com/16192754/117962380-be380f80-b351-11eb-88a7-5cf2d430fd7c.png)

2. 禁用所有行，此时表头未选中
![image](https://user-images.githubusercontent.com/16192754/117962415-c5f7b400-b351-11eb-92c0-75f929343964.png)

-----
1. select all row, now the head is checked
2. disabled all row checkbox, then the head is not checked , although all row actually checked

### What is expected?
禁用状态不影响表头的选中状态
disable status wont effect the head select change

### What is actually happening?
禁用状态事实上影响了表头的选中状态
disabled status change the head select

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.14.0 |
| System | windows 10 Home Edition |
| Browser | Chrome 92.0.4501.0 Canary |

---
这是引入BUG代码的PR：
the code was add in this pull:
https://github.com/ant-design/ant-design/pull/20968

这是造成BUG的表达式：
key boolean expression:
https://github.com/ant-design/ant-design/pull/20968/commits/61bfcbf462aa604362d06c4848a28a214e855670#diff-6c5f2b8a4a1061563259571e5203e5f69eac5c1a68f2f55cf100643d59738d25R297

**Comment by fbambi** [comment]
@afc163 @zombieJ 
please check this issue, and I can create PR for this

**Comment by kerm1it** [comment]
@fbambi Welcome to PR
