### ISSUE TITLE
InputNumber不能输入-1 ~ 0之间的小数，输入-0时会被转换为0，无法继续输入小数点及之后内容

### ISSUE THREAD

**Issue by QJerryxjh** [ant-design/ant-design#30478]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7lq1e?file=/index.js)

### Steps to reproduce
官网给的例子，输入-0，被转化为0

### What is expected?
可以直接输入-0.1

### What is actually happening?
0.1

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 17.0.2 |
| System | macos big sur 11.3 |
| Browser | chrome 90.0.4430.93 |

---
需要能输入-1 ~ 0 之间的小数，但是每次输入到-0时就会被转换为0，在输入后续内容会变为期望值的相反数

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/30096 添加了空是 `null` ，导致输入 `-0`  是一个变化值。我想想看。
