### ISSUE TITLE
upload组件批量上传问题

### ISSUE THREAD

**Issue by pxl0510** [ant-design/ant-design#30489]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
批量选择文件，新增列表获取完成后回调API

### What does the proposed API look like?
批量选择文件，新增列表获取完成后回调，在回调函数中实现读取完成后自动执行后续操作

**Comment by kerm1it** [comment]
有点没明白什么意思？是要在多个文件上传后给一个统一的回调么？

**Comment by afc163** [comment]
onChange 可以实现。
