### ISSUE TITLE
Input props value onChange use setTimeout change  value lead to input abnormal

### ISSUE THREAD

**Issue by ddcouples** [ant-design/ant-design#30486]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4155-forked-dktpz?file=/index.js:0-645)

### Steps to reproduce
16.14.0

### What is expected?
正常能使用input

### What is actually happening?
input 不可用

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.14.0 |
| System | * |
| Browser | * |

---
class App extends React.Component {
  state = {
    value: ""
  };
  render() {
    return (
      <Input
        placeholder="Basic usage"
        value={this.state.value}
        onChange={(e) => {
          console.log(e.target.value);
          const value = e.target.value;
          setTimeout(() => {
            this.setState({
              value: value
            });
          }, 1000);
        }}
      />
    );
  }
}

**Comment by ddcouples** [comment]
> 这是预期行为：https://codesandbox.io/s/jibenshiyong-antd4155-forked-r5rkl

遇到此类需求就不能用 antd的Input 了吗？

**Comment by afc163** [comment]
这个和 antd 无关系，原生 input 也是一样的行为。

**Comment by ddcouples** [comment]
> 这个和 antd 无关系，原生 input 也是一样的行为。

是因为Input render 直接使用了 props.value 传给了 input 的value， 如果使用componentDidUpdated 里 判断一层 props.value 和 preprops.value 然后再赋值给state.value 绑定给input value 就可以满足此类情况, 为何不使用此方式呢？
```
Input.prototype.componentDidUpdate = function (prevProps, prevState, snapshot) {
        var preValue = prevProps.value;
        var value = this.props.value;
        if (value !== preValue) {
            this.setState({
                _value: value
            });
        }
    };

<input value={state._value} />
```
