### ISSUE TITLE
set prefixCls without ConfigProvider

### ISSUE THREAD

**Issue by acfasj** [ant-design/ant-design#30497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
although antd is battery included, but there does have some scenarios that we need to encapsulate a basic ui library based on antd. in this case, we want our prefixCls,  but we  don‘t want our users have to import ConfigProvider explicitly

### What does the proposed API look like?
ConfigProvider.config({ predixCls: 'my-ant' }) works, it could change React context defaultValue (change properties reference like getPrefixCls), but it looks like some hack, maybe you could give some better sugestions

**Comment by afc163** [comment]
You should wrap `ConfigProvider` in entry of react app.
