### ISSUE TITLE
2.0的Notification通知提醒框无法自动关闭

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#3049]
#### 发生问题的环境是：

- antd 版本:^2.0.0-beta.4
- 操作系统及其版本:win10
- 浏览器及其版本:chrome 52

#### 您期待的结果是：
Notification 默认4.5s通知提醒自动关闭。

#### 实际上的结果是：
不关闭

#### 可重现的在线演示
官方演示文档可以重现：
http://beta.ant.design/components/notification/

**Comment by afc163** [comment]
不小心改挂了。
