### ISSUE TITLE
新增组件 Timepicker

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#305]
- 视觉稿：楼下

**Comment by wuzhao** [comment]
Timepicker 的 UI 形态有好几种呢，是不是会跟 Datepicker 保持统一？

**Comment by afc163** [comment]
等视觉稿出来再看，如果保持统一肯定是最好的。

**Comment by sinory** [comment]
视觉稿出来了吗

**Comment by afc163** [comment]
你可以先写实现，视觉稿预计下周才会出来。

**Comment by afc163** [comment]
预计大概会像这样：

![](https://t.alipayobjects.com/images/rmsweb/T18vpiXkRjXXXXXXXX.png)

**Comment by Chinglik** [comment]
... 赞楼上。。

**Comment by Chinglik** [comment]
![](https://t.alipayobjects.com/images/T1Nv4iXkpgXXXXXXXX.png)

**Comment by afc163** [comment]
1. 点击 trigger 后，面板是盖在 trigger 上的。
2. 面板上的头部区域里的日期是 input ，可手动修改。
3. 面板下方的选择区域，滚动条会默认滚动至当前选中项居中。

**Comment by wuzhao** [comment]
赞！青竾设计很快。我和天材遇到问题找两位。

**Comment by yiminghe** [comment]
库建到 https://github.com/react-component

**Comment by sinory** [comment]
@yiminghe  添加我到react-component中

**Comment by yiminghe** [comment]
@sinory  done

**Comment by afc163** [comment]
calendar 的浮层触发方式统一为 [rc-trigger](https://github.com/react-component/trigger) 了，timepicker 也注意下。 https://github.com/react-component/calendar/blob/c76ca48738cc80153550a6e474bc1526f7cd23bf/src/Picker.jsx#L168

**Comment by qiaolb** [comment]
应该考虑支持AM和PM的选择。

**Comment by afc163** [comment]
close by #555
