### ISSUE TITLE
Image组件开启preview怎么阻止冒泡，在表格中使用时点击图片预览无法阻止触发rowClick事件

### ISSUE THREAD

**Issue by hql7** [ant-design/ant-design#30502]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://无](http://无)

### Steps to reproduce
1在表格中使用image组件
2点击预览同时也触发了rowClick

### What is expected?
预览事件能阻止冒泡

### What is actually happening?
预览事件未阻止冒泡

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 最新 |
| System | ios |
| Browser | 谷歌 |

**Comment by afc163** [comment]
`onClick={e => e.stopPropagation()}`

**Comment by hql7** [comment]
@afc163 点预览图也会触发冒泡啊大佬

**Comment by afc163** [comment]
目前可以这样 https://codesandbox.io/s/jibenyongfa-antd4155-forked-xqhl5?file=/index.js

**Comment by hql7** [comment]
@afc163 大佬爱你么么哒
