### ISSUE TITLE
in macos,  upload component api beforeUpload has probloem

### ISSUE THREAD

**Issue by FKIRIN** [ant-design/ant-design#30508]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sr06q?file=/index.js)

### Steps to reproduce
上传文件是word模版时，返回file.type参数为''

### What is expected?
返回对应的文件类型

### What is actually happening?
''

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.9 |
| System | macos |
| Browser | chrome |

**Comment by kerm1it** [comment]
![image](https://user-images.githubusercontent.com/33770367/118124967-f1999d80-b428-11eb-9e40-d40583bf110e.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17549#issuecomment-509592577

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12838#issuecomment-541723714
