### ISSUE TITLE
Upload组件上传了被beforeUpload拦截的文件，列表中有被拦截的文件

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/ant-design#30505]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dianjishangchuan-antd4155-forked-jx1cd)

### Steps to reproduce
上传一个大于2M的文件

### What is expected?
列表中不应该出现

### What is actually happening?
列表中出现被beforeUpload拦截的文件

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | >=16.9.0 |
| System | MacOS Big Sur 11.1 |
| Browser | Chrome90.0.4430.93（正式版本） (x86_64) |

---
listType="picture-card"
这个情况是符合标准的。
但是"listType"和"picture-card"表现不一致。
我想知道哪种是对的，或者说都是对的，那他们的解释是什么样子的。
当然，可以通过动态控制fileList解决

**Comment by DerrickTel** [comment]
https://github.com/ant-design/pro-components/issues/2737

**Comment by kerm1it** [comment]
`beforeUpload`  返回 `false` 时，还是会加到列表中去，如果要在列表中忽略，返回 `Upload.LIST_IGNORE` .

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15561#issuecomment-475108235
