### ISSUE TITLE
Data attributes (e.g. data-testid) is not supported in Radio.Group

### ISSUE THREAD

**Issue by MiryksV** [ant-design/ant-design#30501]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/radio-style-antd4155-forked-p8c5n)

### Steps to reproduce
1. Press F12
2. In the Inspector/Elements tab, search for : `[data-testid="idRadioGroup"]`
3. Not results

You can't reach a the Radio.Group element through the data- attribute. 

### What is expected?
idRadioGroup data attribute should appear in the <span class="ant-radio-button ant-radio-button-checked">
- Search for _idRadioGroup_ data-testid attribute
![image](https://user-images.githubusercontent.com/45184594/118031484-96867e80-b334-11eb-82fd-915deadfad25.png)

### What is actually happening?
Only idRadioButton data attribute appears in the <input class="ant-radio-button-input" type="radio" ...> but for idRadioGroup, you can't reached the Radio.Group element through a data attribute :
- Search for _idRadioButton_ data-testid attribute
![image](https://user-images.githubusercontent.com/45184594/118031246-57582d80-b334-11eb-8e49-4d4db214d8a6.png)

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | Reac |
| System | Ubuntu |
| Browser | Mozilla Firefox |

**Comment by afc163** [comment]
https://github.com/react-component/checkbox/pull/33#issue-110900097

@natergj
