### ISSUE TITLE
InputNumber设置 min={20}时，不管第一个数字输入什么就会自动格式化为20，需要删除重新输入才能生效

### ISSUE THREAD

**Issue by Danihay** [ant-design/ant-design#30516]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
const {  InputNumber  } = antd;

function onChange(value) {
  console.log('changed', value);
}

ReactDOM.render(<InputNumber min={20} max={32768} onChange={onChange} />, mountNode);

### What is expected?
输入数字应该失去焦点时再校验，不能还在输入中就自动转换完了

### What is actually happening?
当输入数字时不管输入什么数字，（未失去焦点，仍在输入中）input框会立马变成20

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 17.0.1 |
| System | 不知道 |
| Browser | 谷歌 |

---
最新版本存在此问题，代码开发用的版本--- "antd": "4.10.3"也存在此问题，希望能一起修复

**Comment by afc163** [comment]
Duplicate of #30465
