### ISSUE TITLE
Page header component not usable on mobile

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design#30514]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-page-header-o387n?file=/index.js)

### Steps to reproduce
add page header with title and subtitle
shrink page to mobile size

### What is expected?
page header subtitle to break a line?

### What is actually happening?
page header title & subtitle on same line non usable

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.12.0 |
| System | Version	10.0.19042 Build 19042 |
| Browser | Version 90.0.4430.212 (Official Build) (64-bit) |

**Comment by afc163** [comment]
We move PageHeader to https://github.com/ant-design/pro-components now.
