### ISSUE TITLE
Tree组件loadData远端加载模式，受控情况下checkedKeys赋值回显，报警告

### ISSUE THREAD

**Issue by zhupp034** [ant-design/ant-design#30518]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
Tree组件loadData远端加载模式，受控情况下checkedKeys赋值回显，报警告

### What is expected?
控制台不报警告

### What is actually happening?
报警告

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.14.0 |
| System | window 10 |
| Browser | chrome 90.0.4430.212 |

**Comment by zhupp034** [comment]
![Uploading image.png…]()

**Comment by zhupp034** [comment]
![image](https://user-images.githubusercontent.com/33925263/118239221-1135d200-b4cc-11eb-9e01-19a67ebacae0.png)

**Comment by zhupp034** [comment]
> Hello @zhupp034. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @zhupp034, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/yibushujujiazai-antd4155-forked-hl90f?file=/index.js

**Comment by zhupp034** [comment]
默认选中了‘0-0’

**Comment by afc163** [comment]
这里合理的，远程数据未加载前，`0-0` 不存在在 Tree 节点中，因此会警告。

<img width="619" alt="图片" src="https://user-images.githubusercontent.com/507615/118479788-07b69f00-b744-11eb-8076-326f88ddc3fe.png">

**Comment by nabil-emad** [comment]
@afc163 I still get Warning: Tree missing follow keys:

**Comment by ZZZping** [comment]
I still have this warning,
I am using TreeSelect

**Comment by johanazhu** [comment]
I still have this warning too，
I am using TreeSelect

**Comment by bn-pshulga** [comment]
Hello @afc163 , still have warning when trying to filter data array on search query.
It would be great if you can delete this warning for example))))
