### ISSUE TITLE
当table中的columns的filters的value类型为number时，筛选没有效果

### ISSUE THREAD

**Issue by 734976581** [ant-design/ant-design#30517]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2fomv?file=/index.js)

### Steps to reproduce
点击table中性别的筛选，选择男做为筛选条件

### What is expected?
筛选出性别为1的数据

### What is actually happening?
没有反应

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.14.0 |
| System | windows10 |
| Browser | chrome 90.0.4430.93 |

---
filters中的value类型为string时可以筛选

**Comment by kerm1it** [comment]
需要加上 `onFilter` 自定义过滤逻辑： https://codesandbox.io/s/antd-reproduction-template-forked-vsmhk?file=/index.js

文档: https://ant.design/components/table-cn/#components-table-demo-head
