### ISSUE TITLE
antd组件示例中没有typescript版本的示例代码

### ISSUE THREAD

**Issue by KongLBiao** [ant-design/ant-design#30511]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一些类型能更快的在antd组件示例中找到

### What does the proposed API look like?
没有api

**Comment by xrkffgg** [comment]
-_- API 不是在各插件文档下面吗

**Comment by afc163** [comment]
Duplicate of #25125
