### ISSUE TITLE
是否有可见即所得的可视化编辑器

### ISSUE THREAD

**Issue by angelyouyou** [ant-design/ant-design#30515]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自动生成代码，降低开发难度和提高开发效率

### What does the proposed API look like?
根据页面拖动的元素和行为生成对应的校验和处理函数等框架代码。

**Comment by kerm1it** [comment]
不支持，antd 定位是基础组件库，现在市面上有很多这种类型的库

https://github.com/baidu/amis

https://github.com/LianjiaTech/hetu
