### ISSUE TITLE
Type Definition wrong for Child Renderer of Form.Item

### ISSUE THREAD

**Issue by wodka** [ant-design/ant-design#30529]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3sq0h)

### Steps to reproduce
```
<Form.Field shouldUpdate >
        {(form) => {
          // this is then undefined according to type definition but holds the item path to access the element!
          console.log(form.prefixName)

          // type should be from https://github.com/react-component/field-form/blob/e118381c2102b36c4ffe7e17a6415df091e772b7/src/interface.ts#L233
          
          return (
              <Form.Field name="fun" hidden={form.getFieldValue([...form.prefixName, 'other'])}>
                <Input />
              </Form.Field>
          )
        }}
      </Form.Field>
```

### What is expected?
the type for the passed form should include the prefixName property

### What is actually happening?
the prefixName property is accessible but not defined in the type

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 17.0.2 |
| System | OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
It is a internal property, I don't think we should expose it.

**Comment by wodka** [comment]
:/ question is how to approach this then, it is the only property I've found to not require the child form field know where it is beeing used.

I also created now an issue for the form.field itself: 

Also here the real world use case I have: https://github.com/react-component/field-form/issues/298https://github.com/ohmyform/ui/blob/logic/components/form/admin/types/slider.type.tsx

**Comment by zombieJ** [comment]
`prefixName` is [FieldContext](https://github.com/react-component/field-form/blob/e118381c2102b36c4ffe7e17a6415df091e772b7/src/FieldContext.ts#L12) props not Form props. You can not access it by `form`. You should access it by FieldContext instead.

**Comment by wodka** [comment]
@zombieJ how to get the field context then?

**Comment by wodka** [comment]
specifically I am using it here - https://github.com/ohmyform/ui/blob/logic/components/form/admin/logic.block.tsx#L60 how to access the field context there?

**Comment by zombieJ** [comment]
`import { xxx } from 'xxxx/lib/xxxx';`

**Comment by wodka** [comment]
https://github.com/react-component/field-form/blob/e118381c2102b36c4ffe7e17a6415df091e772b7/src/Field.tsx#L414 << here is as far as I can see where the context is passed. But in the Type definition it does not pass the prefixName

**Comment by zombieJ** [comment]
```tsx
const { xxx } = React.useContext(FieldContext);
```

**Comment by wodka** [comment]
^^ tricky to find.

it would be nice to export the context in the index as well - is this something that you would consider?

```tsx
import FormItemContext from 'rc-field-form/lib/FieldContext'

export const Something: React.FC = () => (
  <Form.Item>
    {() => {
      const context = React.useContext(FormItemContext)

      console.log(context.prefixName) // working now!
    }
  </Form.Item>
)
```

**Comment by zombieJ** [comment]
FieldContext is internal usage that we do not have plan to provide it in doc.

**Comment by wodka** [comment]
ok, thank you - started now a https://github.com/ant-design/ant-design/discussions/30768 if it is possible to work for me without the prefixName

**Comment by wodka** [comment]
by now it is no longer possible to get the context as in https://github.com/ant-design/ant-design/issues/30529#issuecomment-850272255.

Is there any other way to do this?
