### ISSUE TITLE
Typography.Text 能否提供中间 ellipsis 的情况

### ISSUE THREAD

**Issue by Overcase** [ant-design/ant-design#30522]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些场景下希望首尾字符能展示,省略中间一段的文字
![image](https://user-images.githubusercontent.com/32009993/118246078-1eef5580-b4d4-11eb-960d-ad420b591700.png)

### What does the proposed API look like?
ellipsis 中增加一个 position 之类的属性
![image](https://user-images.githubusercontent.com/32009993/118246233-49d9a980-b4d4-11eb-9714-4e5eaa4f5cfc.png)

**Comment by zombieJ** [comment]
https://codesandbox.io/s/shengluehao-antd4156-forked-8hpee?file=/index.js
