### ISSUE TITLE
Antd Table Virtual list with column render method will interrupt input cursor.

### ISSUE THREAD

**Issue by QiannanXu** [ant-design/ant-design#30521]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuniliebiao-antd4155-forked-6icts?file=/index.js)

### Steps to reproduce
Please refer codesandbox demo.

### What is expected?
1. Antd Table Virtual list can support column render function
2. render function support <Input /> <Textarea /> component etc.

### What is actually happening?
input is not continuous

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17 |
| System | macos |
| Browser | chrome |

---
CodeSandbox demo is update on https://codesandbox.io/s/magical-mayer-xmw99

https://github.com/ant-design/ant-design/issues/26941

**Comment by afc163** [comment]
Table Virtual list is a demo without good built-in features, trace #20339 for further progress.
