### ISSUE TITLE
antd2.0性能form组件的shouldcomponentupdate问题

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#3052]
#### 发生问题的环境是：

- antd 版本:2.0.0-beta.3
- 操作系统及其版本:win10
- 浏览器及其版本:chrom52

#### 您做了什么？
测试shouldcomponentupdate刷新，代码如下：

```jsx
import 'antd/dist/antd.css';
import React from 'react';
import ReactDOM from 'react-dom';
import { Form, Input, Select, InputNumber, DatePicker, TimePicker, Switch, Radio,
  Cascader, Slider, Button, Col, Upload, Icon, Checkbox } from 'antd';
const FormItem = Form.Item;
const mountNode = document.getElementById('content');
const CheckboxGroup = Checkbox.Group; 

class Demo extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    let getFieldDecorator = this.props.form.getFieldDecorator;
    return (
      <Form>
        <FormItem
          label={<span>cb1 </span>}
          >
          {getFieldDecorator('cb1', { initialValue: false, valuePropName: 'checked' })(
            <Checkbox>cb1</Checkbox>
          ) }
        </FormItem>
        <FormItem
          label={<span>cb2  </span>}
          >
          {getFieldDecorator('cb2', { initialValue: false, valuePropName: 'checked' })(
            <Checkbox>cb2</Checkbox>
          ) }
        </FormItem>
      </Form>
    )
  }
}
Demo = Form.create()(Demo);
ReactDOM.render(<Demo />, mountNode);
```

2、修改\node_modules\react\lib\ReactComponentWithPureRenderMixin.js 
```jsx
var ReactComponentWithPureRenderMixin = {
  shouldComponentUpdate: function (nextProps, nextState) {     
    console.log(nextProps, shallowCompare(this, nextProps, nextState));
    return shallowCompare(this, nextProps, nextState);
  }
};
```
插入控制台语句观察对象及shallowCompare返回值。

#### 您期待的结果是：
在点击cb1后，整个form包裹下会产生页面render，cb1内应该执行render其shouldComponentUpdate应返回true,cb2内未修改不应执行render其shouldComponentUpdate应返回false。

#### 实际上的结果是：
超出想象的8次，并且未属性发生变化的cb2的shouldComponentUpdate也返回true进行render。
 
![image](https://cloud.githubusercontent.com/assets/19165238/18605234/c2551cc6-7cbe-11e6-9520-be735c123929.png)

各个form组件应该都存在类似问题，shouldComponentUpdate里浅比较返回的一直是true，导致发生了不必要的render。

**Comment by benjycui** [comment]
把 `getFieldDecorator` 去掉或者先缓存起来应该就没这个问题了。可以的话麻烦测试下然后在这个 issue 里回复一下哈。

因为每次调用 `getFieldDecorator` 后，都会 [生成新的 meta 对象](https://github.com/react-component/form/blob/master/src/createBaseForm.js#L254-L264)，所以 `shallowCompare` 肯定是不等于的。

**Comment by whx76** [comment]
把 getFieldDecorator 去掉用，代码变化为
`import 'antd/dist/antd.css';
import React from 'react';
import ReactDOM from 'react-dom';
import { Form, Input, Select, InputNumber, DatePicker, TimePicker, Switch, Radio,
  Cascader, Slider, Button, Col, Upload, Icon, Checkbox } from 'antd';
const FormItem = Form.Item;
const mountNode = document.getElementById('content');
const CheckboxGroup = Checkbox.Group;


class Demo extends React.Component {
  constructor(props) {
    super(props);
    const getFieldDecorator = this.props.form.getFieldDecorator;
    this.cb1getFieldDecorator = getFieldDecorator('cb1', { initialValue: false, valuePropName: 'checked' });
    this.cb2getFieldDecorator = getFieldDecorator('cb2', { initialValue: false, valuePropName: 'checked' });
    this.iptgetFieldDecorator = getFieldDecorator('Input1', { initialValue: '1' });
  }

  getValue = () => {
    console.log(this.props.form.getFieldsValue());

  }
  render() {

    return (
      <div>
        <Form>
          <FormItem
            label={<span>cb1 </span>}
            >
            {
              <Checkbox id='cb1' key='cb1'>cb1</Checkbox>
            }
          </FormItem>
          <FormItem
            label={<span>cb2  </span>}
            >
            {
              <Checkbox id='cb2' key='cb2'>cb2</Checkbox>
            }
          </FormItem>

        </Form>

        <Button key='_btn_query'  type="primary"  onClick={this.getValue }>查询</Button>
      </div>

    )
  }
}
Demo = Form.create()(Demo);
ReactDOM.render(<Demo />, mountNode);
`

渲染情况如下图
![image](https://cloud.githubusercontent.com/assets/19165238/18612601/1b04dadc-7d91-11e6-91ef-fd34192baf62.png)

cb1有两次渲染，cb2 无渲染。

为何依然有两次渲染？

**Comment by whx76** [comment]
缓存getFieldDecorator 代码如下
 `import 'antd/dist/antd.css';
import React from 'react';
import ReactDOM from 'react-dom';
import { Form, Input, Select, InputNumber, DatePicker, TimePicker, Switch, Radio,
  Cascader, Slider, Button, Col, Upload, Icon, Checkbox } from 'antd';
const FormItem = Form.Item;
const mountNode = document.getElementById('content');
const CheckboxGroup = Checkbox.Group;


class Demo extends React.Component {
  constructor(props) {
    super(props);
    const getFieldDecorator = this.props.form.getFieldDecorator;
    this.cb1getFieldDecorator = getFieldDecorator('cb1', { initialValue: false, valuePropName: 'checked' });
    this.cb2getFieldDecorator = getFieldDecorator('cb2', { initialValue: false, valuePropName: 'checked' });
  }
 
  render() {
    return (
      <div>
        <Form>
          <FormItem
            label={<span>cb1 </span>}
            >
            {
              this.cb1getFieldDecorator(
                <Checkbox id='cb1'  >cb1</Checkbox>
              )
            }
          </FormItem>
          <FormItem
            label={<span>cb2  </span>}
            >
            {
              this.cb2getFieldDecorator(
                <Checkbox id='cb2' >cb2</Checkbox>
              )
            }
          </FormItem>

        </Form>        
      </div>

    )
  }
}
Demo = Form.create()(Demo);
ReactDOM.render(<Demo />, mountNode);`

渲染情况如下：
![image](https://cloud.githubusercontent.com/assets/19165238/18612657/578e217e-7d92-11e6-90ec-73dd7f8c7c6c.png)

渲染次数少了1次，并且cb2的shouldComponentUpdate返回false，shallowCompare 相等。

7次渲染过程是这样吗：
1 本身render
2 触发整个form的render ：两个子组件 FormItem
3 cb1的formitem的lable的render
4 cb1的render
5 cb1的再次render
6 cb2的formitem的lable的render
7 cb2的render --shouldComponentUpdate返回false结束

依然有疑问 cb2的formitem未变化逻辑上 第6次就该结束。另外4、5次为何连续触发？

**Comment by whx76** [comment]
@benjycui  如果解决formitem和连续触发问题，配合上缓存那性能提升非常巨大

**Comment by benjycui** [comment]
不要总是让 maintaner 帮你改格式。。

Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by whx76** [comment]
@benjycui  谢谢，学习下Markdown

**Comment by benjycui** [comment]
> cb1有两次渲染，cb2 无渲染。
> 
> 为何依然有两次渲染？

其实只有一次渲染，不过在 [antd.Checkbox](https://github.com/ant-design/ant-design/blob/master/components/checkbox/index.tsx#L29) 和 [rc-checkbox](https://github.com/react-component/checkbox/blob/master/src/Checkbox.jsx#L52) 里分别调用了一次而已。

**Comment by benjycui** [comment]
`Form.Item` re-render 是因为 `label={<span>cb1 </span>}` 每次都会 `React.createElement` 生成新的对象，这里用 `label="cb1"` 即可。

**Comment by benjycui** [comment]
对实现细节有兴趣，自行研究即可，如有优化建议，可以另提 issue 或者 PR。

**Comment by whx76** [comment]
@benjycui input select 等组件都没有shouldComponentUpdate  建议各个组件都加上shouldComponentUpdate
