### ISSUE TITLE
If we set 'open' property with DatePicker, we can't reselect the date range.

### ISSUE THREAD

**Issue by guguji5** [ant-design/ant-design#30525]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gi710?file=/index.js)

### Steps to reproduce
The RangePicker with open property could not reselect the range. When we open the RangePicker the second time, it could not work as expect.
e.g. Firstly we select the range from 5.1 to 5.7, then we want select from 5.2 to 5.4, but we failed.

如果我们使用open属性来控制RangePicker,重复选择时间的会有bug，第一次选择range符合预期，第二次就不能正常的选择了。
举个例子，第一次点击button，我们选择5.1到5.7，第二次我们想选择5.2到5.4的时候就不能正常选择。

### What is expected?
The second time we can select from 5.2 to 5.4
we can reselect range free. 

### What is actually happening?
From 5.2 to 5.7

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 17.0.2 |
| System | macOs |
| Browser | Chrome |

**Comment by rivaslive** [comment]
Same mistake here, hopefully someone fix this!

**Comment by rivaslive** [comment]
A temporary solution that a friend left me is to render the component again using the key, in this way every time the DatePicker is opened or closed it will change the component and let you set a new range, steps to reproduce:
* open RangeDatePicker with button
* select range
* close RangeDatePicker with button close
* open again RangeDatePicker and select new Range freely

you can see it in your Sandbox code

**Comment by guguji5** [comment]
https://github.com/y0c/react-datepicker works well for me. I give up the ant-design RangePicker.

**Comment by conviva-zyang** [comment]
@afc163  Any plans to fix this?

**Comment by tonthanhhung** [comment]
Another workaround that works from me 
https://codesandbox.io/s/damon-test-forked-245i9
What I did: 
- Remove `setOpen` inside `onChange`, RangePicker will handle closing the popup internal base on the value.
- Provide `setOpen` to `onOpenChange` will let RangePicker control the popup's visibility (on click outside case, onChange)
- Add last hack to make it work as expected in `onCalendarChange` and `key`

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)

**Comment by cscty** [comment]
> * close RangeDatePicker with button close



> A temporary solution that a friend left me is to render the component again using the key, in this way every time the DatePicker is opened or closed it will change the component and let you set a new range, steps to reproduce:
> 
> * open RangeDatePicker with button
> * select range
> * close RangeDatePicker with button close
> * open again RangeDatePicker and select new Range freely
> 
> ```js
> <RangePicker
>   key={open ? 1 : 2}
>   value={rangeValue}
>   open={open}
>   onChange={handleRangePickerChange}
> />
> ```
> 
> although the dates always go crazy

And you, my friend, are the true hero
