### ISSUE TITLE
The content of collapse panel will hide when set `activeKey` while hiding.

### ISSUE THREAD

**Issue by zjffun** [ant-design/ant-design#30527]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/1010543618/pen/ZEeWgJe?editors=0010](https://codepen.io/1010543618/pen/ZEeWgJe?editors=0010)

### Steps to reproduce
Open the reproduction, wait 1s.

### What is expected?
The first panel content display.

### What is actually happening?
The first panel content is 'hidden' (have the `height: 0px;` inline style).

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.x |
| System | macOS Big Sur |
| Browser | Google Chrome 90.0.4430.212 (Official Build) (arm64) |

**Comment by zjffun** [comment]
It looks like there https://github.com/ant-design/ant-design/blob/6e89866694d6e488bcfd4c703adebddd545b93cf/components/_util/motion.tsx#L5

**Comment by zjffun** [comment]
Thank you, I will try to fix it.

**Comment by cdqfeng** [comment]
Yes, I have found the same problem.

**Comment by zjffun** [comment]
I use the below CSS rule to temporary fix it.

```
.ant-collapse-content-active {
  height: auto !important;
}
```
