### ISSUE TITLE
Form.Item with function children does not receive form instance with initialValues on first render

### ISSUE THREAD

**Issue by 5argon** [ant-design/ant-design#30531]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tf90f?file=/EditForm.js)

### Steps to reproduce
Create a form with `initialValues` and form item in uncontrolled mode (no `name`, with function `children`, and either `shouldUpdate` or `dependencies`) to receive a form instance to render a React node.

### What is expected?
The `form` ref of `Form.Item` should have `username` and `disabled` as specified in `initialValues`. Therefore in the box it should have the string "Tony" and the box is **disabled**.

### What is actually happening?
It is an empty object instead (`{}`) so the box is just empty and enabled.

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Edge |

---
It suggests that in the first frame the `Form.Item` code may have run before the `Form` code that set the initial value to the ref form instance.

**Comment by afc163** [comment]
Try https://codesandbox.io/s/antd-reproduction-template-forked-s0r2j?file=/EditForm.js

See https://github.com/ant-design/ant-design/issues/29221#issuecomment-772973820
