### ISSUE TITLE
Table rowSelection 'onSelect' and 'onChange' not fired when setting 'selectedRowsKeys'

### ISSUE THREAD

**Issue by Tuhama** [ant-design/ant-design#30538]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)]( https://codesandbox.io/s/row-selection-events-not-firing-in-antd-table-zus9x)

### Steps to reproduce
When a row is clicked (any cell) I set the selectedRowKeys to this row key...the row's radio button looks selected

### What is expected?
'onSelect' and 'onChange'  should fire ... since the radio button is actually selected

### What is actually happening?
actions are not firing

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 17.0.1 |
| System | Win10 |
| Browser | Chrome: Version 90.0.4430.93 (Official Build) (64-bit) |

---
What I'm trying is to get focus to the radio button ... so 'onKeyDown' is fired...trying to navigate rows by keyboard...it works fine when a row is selected by direct radio button click...but not when selected by row click.

**Comment by afc163** [comment]
It is intented behavior:

```jsx
const [value, setValue] = useState('');

const onChange = e => {
  console.log('onChange')
  setValue(e.target.value);
};

useEffect(() => {
  setValue('afc163'); // it won't trigger onChange when set value of input too
}, []);

<input value={value} onChange={onChange} />
```
