### ISSUE TITLE
This repository might be a target of an attack (involuntarily receiving stars)

### ISSUE THREAD

**Issue by lynxnathan** [ant-design/ant-design#30530]
In the last hour or so I noticed an increasing number of people in my network, myself included, having this repository being starred involuntarily. I can say that for my case, I had done it months (if not years) ago and it seems a couple of people that have no connection with web technologies in my circle here also had it happen to them which seems very unlikely.

Stars numbers are growing sharply here so just wanted to let you know this is happening in case you were not aware, although by the looks of it seems like a CSRF-kinda of attack on Github itself or some other source (no idea yet).

**Comment by atulmy** [comment]
Yes, even I never clicked on star and it showed automatically in my recent starred repository. Definitely something fishy!

**Comment by atulmy** [comment]
Checked the OAuth apps I'd authorised:
Stackoverflow
Dogehouse (https://dogehouse.tv) @benawad

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/discussions/30537#discussioncomment-744106
