### ISSUE TITLE
select组件search功能能否支持大小写不敏感

### ISSUE THREAD

**Issue by asoqa** [ant-design/ant-design#3054]
#### 发生问题的环境是：

- antd 版本: 1.9.1
- 操作系统及其版本:OSX 10.11.5
- 浏览器及其版本:Firefox

#### 您做了什么？

```
            <Select showSearch
                placeholder="请选择部门"
                style={{ width: '100%' }}
                optionFilterProp="children"
                notFoundContent="无法找到"
                onSearch={this.handleSearch}
                >
                {this.state.options}
            </Select>
```

#### 您期待的结果是：

智能提示时，大小写不敏感

#### 实际上的结果是：

大小写敏感

**Comment by benjycui** [comment]
`filterOption`

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by JohnSmith0602** [comment]
我也碰到了这个需求，看了一下 filterOption 的文档说明，所以为了实现「大小写不敏感」需要自行用函数来实现筛选吗，而没有一个类似语法糖的值？
