### ISSUE TITLE
Standardize the Table sortOrder returned type 

### ISSUE THREAD

**Issue by segobrsm** [ant-design/ant-design#30550]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In the onChange function of the Table component, the sorter variable is 'descend' | 'ascend' | null while the type of sortOrder can take the values 'ascend' | 'descend' | false. As the checks between 'null' and 'false' are often sources of errors, is it possible to choose one or the other as value? Thank you in advance, Ségolène

### What does the proposed API look like?
I receive data from the back via my API that I want to display in a table and sort by dates. I want to store the sorting state in my local storage, and it's hard to get around the different types returned by Antdesign in addition to my API which are still different.

**Comment by afc163** [comment]
`ascend` `descend` `false` is the standard type of `sortOrder`, `null` is not.

**Comment by marcellosch** [comment]
The SortOrder Type does not reflect the standard type:

`export declare type SortOrder = 'descend' | 'ascend' | null;`
