### ISSUE TITLE
TextArea autoSize minRows / maxRows is off by -1 on Firefox

### ISSUE THREAD

**Issue by NineBerry** [ant-design/ant-design#30559]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tqwyh)

### Steps to reproduce

Look at the third textbox in the linked codepen on Firefox and Chrome, Enter text
The textbox uses autoSize={{ minRows: 3, maxRows: 5 }}

### What is expected?
Textbox should have 3 minimum rows and 5 maximum rows displayed when entering text in both browsers

### What is actually happening?
Works on Chrome. On Firefox, it shows 2 minimum row2 and 4 maximum rows instead

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.2 |
| System | Windows 10 20H2 Build 19042.985 |
| Browser | Firefox 88.0.1 |

**Comment by afc163** [comment]
<img width="667" alt="图片" src="https://user-images.githubusercontent.com/507615/118588979-0b910280-b7d2-11eb-84bd-3e8624dcc7df.png">

It works well In my Firefox.

**Comment by kerm1it** [comment]
Reproduce in my Firefox of mac.

Maybe height calculate incorrectly when typing.

**Comment by NineBerry** [comment]
Can reproduce on Firefox Mobile on Android. Firefox version 88.1.3

![Screenshot_20210518-115003](https://user-images.githubusercontent.com/42768755/118631022-6543fd80-b7cf-11eb-987c-1048b44716fc.png)
Five lines are entered but only for shown although maxRows is 5

**Comment by NineBerry** [comment]
It doesn't happen on Firefox 89beta, so it's a problem in the Firefox browser and will go away with the next major update. Closed
