### ISSUE TITLE
Table中支持expand时，不展示前面的加号

### ISSUE THREAD

**Issue by ottomao** [ant-design/ant-design#3055]
配置了expandedRowRender时，能不能加个参数，不默认展示前面的加号?

我期望把它当成受控组件来用，自己控制怎么展示。

p.s. 文档里没看到`onExpandedRowsChange`这个props，是故意的?

```jsx
  <Table
         {...otherProps}
          expandedRowRender={record => (
            <span>hello</span>
          )}
        />
```

![image](https://cloud.githubusercontent.com/assets/1622697/18608537/bd836f58-7d1e-11e6-80ac-286d632d4fd6.png)

**Comment by benjycui** [comment]
如果只是为了隐藏，可以用样式。

**Comment by ottomao** [comment]
现在就是用样式实现的，感觉有点hack...? 万一哪天ant.design升级了，这个样式我还得自己兼容。

设计上，感觉不应该把「支持展开」和「替用户增加一个加号」给绑定起来？

**Comment by afc163** [comment]
Will fixed in next `2.0.0-beta`

`expandIconAsCell={false} expandIconColumnIndex={-1}`

**Comment by vincentshow** [comment]
@afc163 请问下2.0.0-beta这个版本大概什么时候发布，可以手动触发expand行为吗

**Comment by benjycui** [comment]
beta 已经发布。

**Comment by neewbee** [comment]
expand 这个函数有暴露出来吗？ 比如说想实现点击某个cell触发 expand 方法

**Comment by superlbr** [comment]
there is no expandIconAsCell、expandIconColumnIndex in docs @afc163

**Comment by ShangcaoYuan** [comment]
@ottomao 弱弱的问一下，如何用样式选择性隐藏不同行的 expand icon 呢

**Comment by sinpor** [comment]
> Will fixed in next `2.0.0-beta`
> 
> `expandIconAsCell={false} expandIconColumnIndex={-1}`

请问v4如何隐藏呢？

使用样式隐藏掉之后，由于配置了`expandable`和固定列，会让固定列右侧有空白。

[示例](https://codesandbox.io/s/shy-thunder-g6ddz?file=/src/App.js)

**Comment by preservance717** [comment]
@sinpor 请问这个隐藏icon问题解决了吗

**Comment by sinpor** [comment]
> @sinpor 请问这个隐藏icon问题解决了吗 antd版本是v4.4

@preservance717 用样式隐藏了，不配置可展开没啥问题。

**Comment by preservance717** [comment]
> > @sinpor 请问这个隐藏icon问题解决了吗 antd版本是v4.4
> 
> @preservance717 用样式隐藏了，不配置可展开没啥问题。

哇赛这么快就回复啦，谢谢～
好吧，但是我需要配置展开功能...

**Comment by sinpor** [comment]
@preservance717 试试给表格加上
``` less
colgroup {
        col.ant-table-expand-icon-col {
            display: none;
        }
    }
```

**Comment by Tom-baby** [comment]
想问下 vue的版本 展开收缩图标支持替换吗？

**Comment by yoyo837** [comment]
> 想问下 vue的版本 展开收缩图标支持替换吗？

请到相应的仓库下提问，那边是社区维护的。

**Comment by wj100** [comment]
我也遇到了相同的问题 ，期望有子数据时出现+号，expandIconColumnIndex应该是一个有record参数的函数就好了

**Comment by SimpleLifecst** [comment]
![image](https://user-images.githubusercontent.com/83959029/202737702-db433ead-0e22-4d68-8940-6fbc1dbab614.png)
当没有展开数据时，应该取消加号的显示，这样用户可以很直观的看到哪些有子数据的
