### ISSUE TITLE
Uncaught Error: Cannot find module 'moment/locale/zh-cn' from 'antd/lib/date-picker/locale/zh_CN.js' (zh_CN.js:27)

### ISSUE THREAD

**Issue by williamkhshea** [ant-design/ant-design#3056]
#### 发生问题的环境是：

- antd 版本: 2.0.0-beta.4
- 操作系统及其版本: OS X 10.11.6
- 浏览器及其版本: Chrome 52.0.2743.116 (64-bit)

![screen shot 2016-09-17 at 11 01 16 pm](https://cloud.githubusercontent.com/assets/4775489/18609041/b4b1c058-7d2a-11e6-83d4-e2ae0f537c5a.png)

![screen shot 2016-09-17 at 11 00 54 pm](https://cloud.githubusercontent.com/assets/4775489/18609043/bbacaac6-7d2a-11e6-8de4-e9554e229beb.png)

**Comment by benjycui** [comment]
Try 2.0.0-beta.5

**Comment by benjycui** [comment]
然后其实最好可以给出例子。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by williamkhshea** [comment]
@benjycui 我在线上没办法重现错误，我怀疑是跟用了BABEL 有关。以下是我用了的BABEL PLUGINS：

    "babel-brunch": "^6.0.6",
    "babel-plugin-antd": "^0.5.1",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-preset-stage-2": "^6.13.0",

**Comment by williamkhshea** [comment]
@benjycui 在node_modules里面找不到区域设置的文件夹。

![screen shot 2016-09-18 at 2 52 57 pm](https://cloud.githubusercontent.com/assets/4775489/18613536/af0b5670-7daf-11e6-9a3d-d164132cf815.png)

**Comment by benjycui** [comment]
可以的话，在 GitHub 上开个 repo 重现问题，这样我们就可以 clone 下来测试。

**Comment by williamkhshea** [comment]
@benjycui 请问有beta.6的在线环境吗？

你给我这个是1.11.1：
http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
更新 JavaScript 链接为 https://unpkg.com/antd@2.0.0-beta.6/dist/antd.js

![image](https://cloud.githubusercontent.com/assets/3580607/18614199/f84ef80c-7dbc-11e6-9554-c9ef2c0d31ee.png)

**Comment by williamkhshea** [comment]
@benjycui  在线上没办法重现错误，因为它已经变成是webpack require，看来一定要在GITHUB 开REPO才可以重现。

![screen shot 2016-09-18 at 4 42 48 pm](https://cloud.githubusercontent.com/assets/4775489/18614331/fc5d523e-7dbe-11e6-94b0-8c19d130a657.png)

**Comment by benjycui** [comment]
所以可以提供 repo?

**Comment by williamkhshea** [comment]
@benjycui 给我一点时间准备一下REPO

**Comment by williamkhshea** [comment]
@benjycui REPO准备好了。https://github.com/williamkhshea/antd

**Comment by benjycui** [comment]
这个可以顺便给出重现步骤？

你好像没有使用 antd-init 或者 dva-cli 生成的目录结构，不排除是你的配置问题。

**Comment by afc163** [comment]
感觉是 npm2 的问题。在 #3203 里应该修复了。

**Comment by williamkhshea** [comment]
@benjycui @afc163 Confirmed working now. Thanks.

**Comment by andrewvmail** [comment]
```
ERROR in ./~/antd/lib/date-picker/locale/zh_CN.js
Module not found: Error: Can't resolve 'moment/locale/zh-cn' in '/Users/andrew/Desktop/lift-app/frontend/node_modules/antd/lib/date-picker/locale'
 @ ./~/antd/lib/date-picker/locale/zh_CN.js 23:0-30
 @ ./~/antd/lib/date-picker/wrapPicker.js
 @ ./~/antd/lib/date-picker/index.js
 @ ./~/antd/lib/index.js
 @ dll reactBoilerplateDeps
```

I'm getting similar issue to this does anyone know whats the fixed for it?
Is it a webpack issue?
