### ISSUE TITLE
nested table margin doesn't work when table use fixed columns

### ISSUE THREAD

**Issue by chasel34** [ant-design/ant-design#30564]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nested-tables-antd4155-forked-8itj1)

### Steps to reproduce
1. Open a new codepen of https://codesandbox.io/s/nested-tables-antd4155-forked-8itj1
2. Set fixed columns

### What is expected?
nested table margin work normally

### What is actually happening?
nested table margin doesn't work

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.8.6 |
| System | macOS Big Sur 11.3.1 |
| Browser | Microsoft Edge 90.0.818.56  |

**Comment by afc163** [comment]
What is the expected style of nested table margin?

**Comment by chasel34** [comment]
example:
![image](https://user-images.githubusercontent.com/23191158/118600286-6121db00-b7e3-11eb-97d6-06bcbe095968.png)

when use fixed columns
![image](https://user-images.githubusercontent.com/23191158/118600396-83b3f400-b7e3-11eb-804d-b6f60825bca2.png)

this rule not working
