### ISSUE TITLE
table filteredValue set  caused filters invalid

### ISSUE THREAD

**Issue by rachelichen** [ant-design/ant-design#30565]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kekongdeshaixuanhepaixu-antd4156-forked-uy71t?file=/index.js)

### Steps to reproduce
click first column filter cannot work

### What is expected?
The first column filter  work

### What is actually happening?
The first column filter cannot work

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | ios |
| Browser | web |

**Comment by afc163** [comment]
Your codesandbox works fine.
