### ISSUE TITLE
Antd table navigation broken with fixed columns.

### ISSUE THREAD

**Issue by linras** [ant-design/ant-design#30575]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nameless-lake-i8jjm?file=/src/App.js)

### Steps to reproduce
1. Set focus on any column input.
2. Move to the next row inputs with tab key until you reach the last visible before the fixed column (not the last column).
3. Try to move  with tab key one field more.

Alternative scenario:
1. Scroll table to the right.
2. Set focus on any column input.
2. Move to the previous row inputs with shift   tab key until you reach the last visible before the fixed column (not the first column).

### What is expected?
The table is scrolled automatically, so the focused field is visible.

### What is actually happening?
The field is "covered" by the fixed column. The user does not see the focused field. By the way it works correctly when the focus is set on the last column that is not fixed.

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by linras** [comment]
![image](https://user-images.githubusercontent.com/25079388/118660305-59b3ff00-b7ee-11eb-997a-832425cbf5ab.png)

**Comment by zombieJ** [comment]
Since cover calculation has perf cost. We may not apply auto scroll by focus element default. You can follow this code if needed:
https://codesandbox.io/s/antd-table-navigation-broken-with-fixed-columns-forked-qgrdq?file=/src/App.js
