### ISSUE TITLE
缺省（true) filterOption导致Seletor选项不刷新

### ISSUE THREAD

**Issue by IshiKura-a** [ant-design/ant-design#30589]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-mendel-hcjlq?file=/index.js)

### Steps to reproduce
运行提供的沙盒链接 J组件没有filterOption=false这行，导致无法更新

### What is expected?
filterOption按照我的理解，缺省不就是不筛选么，应该返回所有option

### What is actually happening?
所有选项都没出现

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | react 16.8.6 |
| System | macos 11.3.1 |
| Browser | chrome 90.0.4430.212 |

**Comment by afc163** [comment]
filterOption 默认值为 true。

**Comment by afc163** [comment]
1. filterOption 是和 showSearch 或者 tags/multiple 配合的，单独声明没意义。
2. 默认为 true 的意思是，缺省就是进行输入筛选的。
