### ISSUE TITLE
Anchor 无法设置默认高亮显示 Link

### ISSUE THREAD

**Issue by xiaoxiaotongzhi** [ant-design/ant-design#30584]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在进入页面初始化的时候没有滚动，无法触发高亮效果；设置默认值让初始化的时候能够显示高亮

### What does the proposed API look like?
设置一个defaultLink的属性传入对应的Id

**Comment by xiaoxiaotongzhi** [comment]
目前使用的方案是获取 Anchor 节点调用节点中的 setCurrentActiveLink 方法自己更新默认值

**Comment by afc163** [comment]
https://ant.design/components/anchor/#components-anchor-demo-customizeHighlight

这个可以么

**Comment by xiaoxiaotongzhi** [comment]
> https://ant.design/components/anchor/#components-anchor-demo-customizeHighlight
> 
> 这个可以么

设置了这个属性之后滚动无法触发高亮

**Comment by xiaoxiaotongzhi** [comment]
> > https://ant.design/components/anchor/#components-anchor-demo-customizeHighlight
> > 这个可以么
> 
> 设置了这个属性之后滚动无法触发对应id盒子高亮

**Comment by afc163** [comment]
> 设置了这个属性之后滚动无法触发对应id盒子高亮

确实有问题：
https://codesandbox.io/s/customize-the-anchor-highlight-antd4156-forked-5kndz?file=/index.js:382-399

**Comment by xiaoxiaotongzhi** [comment]
> > 设置了这个属性之后滚动无法触发对应id盒子高亮
> 
> 确实有问题：
> https://codesandbox.io/s/customize-the-anchor-highlight-antd4156-forked-5kndz?file=/index.js:382-399
