### ISSUE TITLE
Modal.method() please add a 'footer' property to toggle the show of footer

### ISSUE THREAD

**Issue by Serkey** [ant-design/ant-design#30581]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when adding a simple modal, I choose to use Modal.method(), but it means the modal always show the footer, but sometimes I don't want it, so add a footer property to the Modal.method() object parameter to control the show of the  footer

### What does the proposed API look like?
Modal.confirm() will show the footer
Modal.confirm({footer: null}) will hide the footer

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/29749#issuecomment-846825024
