### ISSUE TITLE
TreeSelect使用时选中的内容跟checkbox的选中状态不一致

### ISSUE THREAD

**Issue by yanxiaoqiang1993** [ant-design/ant-design#3059]
我使用TreeSelect时选中的内容跟checkbox的选中状态不一致 
![qq 20160918100346](https://cloud.githubusercontent.com/assets/16573945/18612271/f58673b4-7d87-11e6-8b96-3210472b63db.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by yanxiaoqiang1993** [comment]
@benjycui 我就是用的官网的多选例子，总感觉我的显示比我的点击慢一拍

**Comment by benjycui** [comment]
如果你说的是这个 [例子](http://ant.design/components/tree-select/#components-tree-select-demo-checkable) 的话，无法重现，麻烦提供重现步骤。
