### ISSUE TITLE
DatePicker default picker on open

### ISSUE THREAD

**Issue by GeorgeCodeHub** [ant-design/ant-design#30598]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Be able to set what picker the DatePicker will open by default. 

For instance, when a user sets the default picker to the "year" they will be able to start setting from that point.
In other words, they will start filling the date from year -> month -> day.

Common use cases for such a scenario are when a user wants to fill their date of birth or the establishment of their company in a form.

### What does the proposed API look like?
Have a property to set the picker when the panel opens. 
`defaultPickerOnOpen="year"|"month"|"week"|"date"`

```javascript
<DatePicker onChange={onChange} defaultPickerOnOpen="year" />
```

**Comment by afc163** [comment]
```
mode="year"
```

**Comment by GeorgeCodeHub** [comment]
Thank you for the quick reply. 

I would like to clarify that I'm using ant-design v.4+. I have tried your suggestion however it doesn't follow the behavior I want above.

The need is to be able to open the DatePicker as picker="date", start adding the date from the year, then transition to month and then to day.

Below an image of what I'm trying to describe:
![picker](https://user-images.githubusercontent.com/54906099/118952452-a4f01e00-b964-11eb-94ab-7e4dacbfefd2.png)
