### ISSUE TITLE
Some components cannot be completely hidden after using the hidden property

### ISSUE THREAD

**Issue by meitingshuoguo** [ant-design/ant-design#30597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/input/](https://3x.ant.design/components/input/)

### Steps to reproduce
Select the Search component, and then set the hidden property for it, you can see that only the input is hidden, the search icon is not. You can test it in any online editor.

### What is expected?
All search components are hidden

### What is actually happening?
Only the input of the search component is hidden.
![image](https://user-images.githubusercontent.com/16173962/118912882-0c08d500-b95b-11eb-8f0a-5477e6d5f538.png)

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.8 |
| System | mac 10.15.7 |
| Browser | chrome 90.0.4430.93 |

**Comment by afc163** [comment]
There is no `hidden` property for Search component.
