### ISSUE TITLE
process.env.TEST_IE 在浏览器跑报错了

### ISSUE THREAD

**Issue by whw583** [ant-design/ant-design#30591]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/pull/19062](https://github.com/ant-design/ant-design/pull/19062)

### Steps to reproduce
https://github.com/ant-design/ant-design/pull/19062

### What is expected?
不应该使用process 对象

### What is actually happening?
使用了process.env.TEST_IE,浏览器没有process对象，导致 cant not read property env of undefined 报错。

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | 90.0.4430.212 |

---
问题只在antd 3.x出现。 
代码位置 components/upload/Upload.tsx 101行，可以看这个review https://github.com/ant-design/ant-design/pull/19062 。
不影响上传组件的使用，但是报错了，影响体验。

**Comment by losgif** [comment]
可以自己定义下这个值，用webpack的DefinePlugin设置，只是解决了报错而已
```js
new DefinePlugin({
  'process.env.TEST_IE': false
})
```
