### ISSUE TITLE
cascader 渲染label文案的时候报错

### ISSUE THREAD

**Issue by leehomeok** [ant-design/ant-design#30594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[webpack://app-system-[name]/./node_modules/antd/es/cascader/index.js](webpack://app-system-[name]/./node_modules/antd/es/cascader/index.js)

### Steps to reproduce
点击编辑弹窗，modal会展示级联数据

### What is expected?
不报错 

### What is actually happening?
label.join is not a function
    at defaultDisplayRender (index.js:111)

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.12 |
| System | win10 |
| Browser | 90 |

**Comment by zengande** [comment]
你可以看看这个
https://stackoverflow.com/questions/62483820/setting-initialvalue-on-form-item-wrapping-a-cascader-throws-an-uncaught-typeer
