### ISSUE TITLE
button 组件化

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#306]
链接：http://ant.design/components/button

原写法：

```
<button className="ant-btn ant-btn-primary ant-btn-lg">按 钮</button>
```

变为：

```
import { Button } from 'antd';
...
<Button type="primary" size="large">按钮</Button>
```

> 当按钮文字为两个中文时，自动在中间加一个空格。

**Comment by benjycui** [comment]
过了一遍现在的 [Button 的 demo](http://ant.design/components/button/)，并参考了 [material ui](http://material-ui.com/#/components/buttons) 和 [Elemental UI](http://elemental-ui.com/buttons) 的 Button 设计。

`Button` 现在的设计如下：

Prop | Type | Default | Description
-------|---------|-----------|---------------
type | Enum | default | default/primary/ghost
size | Enum | default | default/small/large
circle | Bool | false | 存在为 `true`，不存在为 `false`
disabled | Bool | false | 存在为 `true`，不存在为 `false`
loading | Bool | false | 存在为 `true`，不存在为 `false`
submit | Bool | false | 存在为 `true`，不存在为 `false`；若 `true`，则 `type` 为 `submit`
href | String | 'javascript:;' | 若存在，则渲染为 `a` 标签，并设置 `a` 标签的 `href` 值
onClick | Function | `function() {}` | `click` 事件 handler

`ButtonGroup` 设计如下：

Prop | Type | Default | Description
-------|---------|-----------|---------------
size | Enum | default | default/small/large

然后组合 `ButtonGroup` 和 `Button`  使用：`<ButtonGroup><Button /><Button/></ButtonGroup>`

几个问题：
1. 在已经有 [`Dropdown`](http://ant.design/components/dropdown/) 的前提下，`Button` 还需要实现 [菜单按钮](http://ant.design/components/button/#demo-menu) 么？
1. [图标按钮](http://ant.design/components/button/#demo-icon) 应该不需要实现，只要允许用户这样 `<Button><Icon type="xxx"  />图标按钮</Button>` 使用就行了？ping @elrrrrrrr 
1. 默认使用 `button` 还是 `input` 标签渲染？还是说加个选项让用户自己选择？
1. `Button` 的样式是否需要增加？`success` `warning` `danger` 这些。

问题略多 XD

**Comment by afc163** [comment]
1. Dropdown 里的 trigger 是直接使用了 ant-btn-menu 的按钮样式的，按钮这里不需要实现下拉功能。
2. 对。
3. button，不推荐使用 input 。
4. 不需要。

另外，style、className 等原生属性需要传递给 button，方便用户自定义。

**Comment by benjycui** [comment]
略好奇， button 优于 input 的地方是？ @afc163

**Comment by afc163** [comment]
button 可以内嵌 html ，`input[type=button]` 怎么搞？

**Comment by benjycui** [comment]
一时没反应过来，THX!

**Comment by yiminghe** [comment]
最好不要用 button，用 display:inline-block 的 div

**Comment by afc163** [comment]
`type` 属性是否留给原生的 `type`。

那么就需要另外的命名用于 `primary` `ghost` `default`。看了下其他库的处理，大概有 `status="primary"`、`theme="primary"`、`bsStyle="primary"` 等等，感觉都不是特别清晰。

**Comment by afc163** [comment]
或者沿用 type ，原生的 type 统一设置为 `type="button"`。

**Comment by benjycui** [comment]
之前提到让用户自己用嵌套的方式实现 LinkButton，如： `<Button><a href="javascript:;" role="button">Link</a></Button>`。但是这样的话，按钮上的文字样式是由 `a` 标签决定的，效果如下：

![image](https://cloud.githubusercontent.com/assets/3580607/10063697/3c6df15e-62a3-11e5-9440-c797fdca714d.png)

这样用户就需要自己修改 `a` 标签的样式以兼容按钮的样式了。所以建议还是保留 `href` 属性？

不过，之前 @yiminghe 提到过可以让用户自己在 `onClick` 里触发 submit 事件，所以如果按这个思路的话，reset 以及 LinkButton 的功能都可以让用户在 `onClick` 内实现？这样也不需要纠结 `type` 属性该怎样处理了。

虽然乍看之下会觉得用 `onClick` 去实现这些功能不大好，不过考虑到按钮大多会绑定事件，所以应该也可以接受？

**Comment by afc163** [comment]
在 ant design 下 button 一般不会用来触发链接。特殊情况先不予处理吧。

**Comment by afc163** [comment]
好，type 就保持你写的版本。

**Comment by benjycui** [comment]
> 当按钮文字为两个中文时，自动在中间加一个空格。

这个考虑到嵌套的情况是无法预测的，实现起来难度比较大，先暂时让用户自己加个空格？

**Comment by afc163** [comment]
嵌套不考虑，解决 85% 的情况就好。

**Comment by afc163** [comment]
#345

**Comment by simaQ** [comment]
type 属性保留，增加个 btnName 来设置 primary/ghost 肿么样.....

**Comment by benjycui** [comment]
其实我们纠结的应该是这些属性的语义吧。不知道增加一个 `as` 属性怎样：

```xml
<Button type="primary" as="submit">提交</Button>
<Button type="primary" as="reset">重置</Button>
```

**Comment by afc163** [comment]
类型 htmlFor 搞一个 htmlType 算了。
