### ISSUE TITLE
'bottomRight' doesn't work for notification component placement

### ISSUE THREAD

**Issue by alanphunt** [ant-design/ant-design#30607]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://icantsharethecodebecauseitsaprivaterepo.com](https://icantsharethecodebecauseitsaprivaterepo.com)

### Steps to reproduce
    notification["success"]({
      message: "",
      placement: "bottomRight"
    });

### What is expected?
Toaster should appear at bottom right of corner.

### What is actually happening?
Nothing.

| Environment | Info |
|---|---|
| antd | 4.14.1 |
| React | 17.0.2 |
| System | Windows |
| Browser | Chrome |

---
Using "bottomright" instead of "bottomRight" works but documentation says it should be "bottomRight"

**Comment by afc163** [comment]
https://codesandbox.io/s/jiben-antd4156-forked-shzdd?file=/index.js
