### ISSUE TITLE
Popover与Collapse一起使用导致Collpase.Panel高度无法正常变化

### ISSUE THREAD

**Issue by leopold-zw** [ant-design/ant-design#30609]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

-- https://codesandbox.io/s/antd-reproduction-template-forked-prz4w?file=/index.js

### Steps to reproduce
注意步骤3
1. 打开Popover
2. 打开panel1
3. 多次点击按钮“点我”，直到Popover底部接触到浏览器底部，Popover明显开始向上增长
4. 关闭panel1
5. 打开panel1
6. 再多次点击按钮“点我”

### What is expected?
panel1的内容一直增高，显示正常

### What is actually happening?
panel1的内容增高后，整个panel的高度没有变化，所以内容被隐藏了，关闭后再打开才会恢复正常

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 17.0.2 |
| System | macOs |
| Browser | chrome 90.0.4430.212 |

**Comment by afc163** [comment]
这里是 GitHub，不要使用内网链接。

**Comment by zombieJ** [comment]
动画事件没有触发，估计哪里 prevent 了。我瞅瞅

**Comment by leopold-zw** [comment]
sandbox链接已更新

**Comment by zombieJ** [comment]
神奇，本地复现不出来。等 minor 发出来我再试试 codesanbox。

**Comment by afc163** [comment]
看看 https://github.com/ant-design/ant-design/pull/30555 是不是修复了。

**Comment by leopold-zw** [comment]
我这边本地和codesanbox都还能复现

**Comment by zombieJ** [comment]
感觉像

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-hr20n?file=/package.json

的确好了
