### ISSUE TITLE
Modal style API only works partially near the modal bottom.

### ISSUE THREAD

**Issue by cftan98** [ant-design/ant-design#30608]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/cftan98/antd_issues](https://github.com/cftan98/antd_issues)

### Steps to reproduce
1. Clone the repo
2. npm install
3. npm start
4. click open modal
5. notice that only bottom get styled as pink background color.

### What is expected?
Expect the style on the whole modal not partially on footer.

### What is actually happening?
Styled on footer instead. 

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome90.0.4430.212 |

**Comment by afc163** [comment]
Try className: https://codesandbox.io/s/jiben-antd4156-forked-wg886?file=/index.css
