### ISSUE TITLE
Other icon libraries do not work well with collapsible sider and submenu

### ISSUE THREAD

**Issue by Ozencb** [ant-design/ant-design#30605]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-swanson-0vk8d?file=/src/App.js)

### Steps to reproduce
Pass any react-icons component to Menu as an icon

### What is expected?
It should work the same way ant-design icons work

### What is actually happening?
Margins are ignored and when sider is collapsed, submenu titles remain visible

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 17 |
| System | Windows 10 |
| Browser | Chrome 90.0.4430.212 |

**Comment by kerm1it** [comment]
This example work correctly: https://codesandbox.io/s/serverless-cookies-yjerg?file=/src/App.js

you can add `anticon` className to other icon component.
