### ISSUE TITLE
When we remove the value of the Ant Design Select with the clear button set the value null without undefined.

### ISSUE THREAD

**Issue by ishan-nibaya** [ant-design/ant-design#30611]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I JSON stringify the Ant Design form data, the undefined value is removed.

### What does the proposed API look like?
When we remove the value of the Ant Design Select with the clear button set the value null or initialValue.

**Comment by afc163** [comment]
> When I JSON stringify the Ant Design form data, the undefined value is removed.

It is intented behavior.
