### ISSUE TITLE
setState 修改 ConfigProvider 的 prefixCls 内部组件 class 前缀未变化

### ISSUE THREAD

**Issue by xz8la8** [ant-design/ant-design#30612]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/2d1afd2f](https://riddle.alibaba-inc.com/riddles/2d1afd2f)

### Steps to reproduce
点击按钮设置 prefixCls 为 mymy 未生效

### What is expected?
ConfigProvider 包括的 antd 组件 className 前缀变成 mymy

### What is actually happening?
ConfigProvider 包括的 antd 组件 className 前缀依然是 ant

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 17.0.0 |
| System | MacOS |
| Browser | Chrome v90 |

---
需求场景，动态修改prefixCls，使用自己业务修改的 antd.min.css（这里的 prefixCls 是 mymy ）

**Comment by kerm1it** [comment]
这个目前只读一次传入的，不支持动态化，觉得可以加一下。
