### ISSUE TITLE
Date Picker And Time Picker Input Mask

### ISSUE THREAD

**Issue by coder054** [ant-design/ant-design#30613]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Add Input mask for picker help reduce some typing: for example: If I want 12h 30 min, I can type "12" then the input automatically add "/" or "-", then I can type "30". And can help people image what is the format of date picker
https://youtu.be/YVQabAuAfvM

### What does the proposed API look like?
<Datepicker mask={"__/__/____"} format={'MM/DD/YYYY'} />
<Datepicker mask={false} format={'MM/DD/YYYY'} /> // default

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/30394#issuecomment-832728139
