### ISSUE TITLE
自定义主题时，使用原生css变量导致报错，原因是内部变量使用了less函数，无法处理原生css变量

### ISSUE THREAD

**Issue by BingLee1994** [ant-design/ant-design#30615]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce
webpack的less配置如下
lessOptions: {
                javascriptEnabled: true,
                modifyVars: {
                  // antd主题定制
                  'primary-color': 'var(--accent-colot)', // 全局主色
                  'heading-color': 'var(--black-a8)', // 标题色
                  'text-color': 'var(--primary-text-color)', // 主文本色
                  'text-color-secondary': 'var(--secondary-text-color)', // 次文本色
                  'disabled-color': 'var(--disabled-text-color)', // 失效色
                },
              },

### What is expected?
正常编译通过

### What is actually happening?
错误：Error evaluating function `lighten`: Argument cannot be evaluated to a color

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16 |
| System | mac os |
| Browser | chrome |

**Comment by kerm1it** [comment]
这不是 antd 的问题，less 的用法问题，可以去查查 less 相关文档

https://lesscss.org/usage/#using-less-in-the-browser-modify-variables

**Comment by yy7054wyq5** [comment]
ant-desgin所使用的 [TinyColor](https://github.com/bgrins/TinyColor) ，不支持css变量。若有css变量的应用场景又想统一值可以这样，中间搭个桥。
```css

@main-color: red;
:root {
  --main-color: @main-color;
}
@primary-color: @main-color;

```

如果直接这样写，`@primary-color: var(--main-color);`则会报错，结果如下

在 [colorPalette.less](https://github.com/ant-design/ant-design/blob/13a829d20c8a1a83c3bfa1f9d7c30d95659f5b57/components/style/color/colorPalette.less) 调用函数的地方加上打印：

```js
this.colorPalette = function(color, index) {
    console.log(color); // 打印在这里
    var isLight = index <= 6;
    var hsv = tinycolor(color).toHsv();
    var i = isLight ? lightColorCount + 1 - index : index - lightColorCount - 1;
    return tinycolor({
      h: getHue(hsv, i, isLight),
      s: getSaturation(hsv, i, isLight),
      v: getValue(hsv, i, isLight),
    }).toHexString();
  };
```

打印结果:
```js
// 前后很多，此处省略
#f5222d
#f5222d
var(--main-color)
var(--main-color)
```

最终报错：
```js
Error: ./src/styles.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/less-loader/dist/cjs.js):


@picker-basic-cell-active-with-range-color: @primary-1;
@picker-basic-cell-hover-with-range-color: lighten(@primary-color, 35%);
                                         ^
Error evaluating function `lighten`: Argument cannot be evaluated to a color
      Error in /Users/admin/Desktop/www/web-client/node_modules/ng-zorro-antd/style/themes/default.less (line 637, column 43)
    at /Users/admin/Desktop/www/web-client/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/admin/Desktop/www/web-client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/admin/Desktop/www/web-client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/admin/Desktop/www/web-client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.lessLoader (/Users/admin/Desktop/www/web-client/node_modules/@angular-devkit/build-angular/node_modules/less-loader/dist/index.js:57:5)
```

**Comment by AHopes** [comment]
@BingLee1994 请问下问题解决了吗？
@yy7054wyq5 用:root搭桥，修改:root中的变量，ant的主题色不更新 这个有解决办法吗

**Comment by yy7054wyq5** [comment]
> @BingLee1994 请问下问题解决了吗？ @yy7054wyq5 用:root搭桥，修改:root中的变量，ant的主题色不更新 这个有解决办法吗
https://zhuanlan.zhihu.com/p/72178646 这个呢？
