### ISSUE TITLE
Form does not see the input value if using react context

### ISSUE THREAD

**Issue by eugenestepanyuk** [ant-design/ant-design#30616]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/eugenestepanyuk/react-context-form](https://github.com/eugenestepanyuk/react-context-form)

### Steps to reproduce
- start project
- click button '...' at Drawer Component 
- select row with data
- click button 'OK' at Drawer Component
- make sure that the value is in the input
- click button 'Submit' at Form Component

### What is expected?
Form should get the value from the imported input after selecting it from the table and click button 'Submit' using react context

### What is actually happening?
Form does not see the input value if using react context. Work onFinishFailed method

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 17.0.2 |
| System | Windows 10 Pro 1909 18363.1440 |
| Browser | Google Chrome v. 90.0.4430.212 |

**Comment by afc163** [comment]
Please see https://ant.design/components/form/#components-form-demo-customized-form-controls for custom form control usage.
