### ISSUE TITLE
想扩展下DateTable(rc-calendar)，增加接口：选多个day。

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#3062]
想使用DateTable做日历的日多选，就是可以选择多个天，目前的想法是照着写个DateTBody.jsx和DateTable.jsx，然后改下DateTbody的选择逻辑。

不知道后期会不会考虑加入日历控件的可多选接口？能否给些相关建议？多谢。
![image](https://cloud.githubusercontent.com/assets/1686808/18613944/424ff722-7db7-11e6-8e88-1c8cada7e19c.png)

**Comment by benjycui** [comment]
暂时没有这个需求，或者你可以  PR？

**Comment by afc163** [comment]
antd 这里应该目前不会支持。
