### ISSUE TITLE
Export TreeSelect DataNode Type

### ISSUE THREAD

**Issue by CoryBond** [ant-design/ant-design#30622]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This request is relevant for antd versions
* 4.15.6
* 4.12.2

Antd uses both rc-tree and rc-tree-select for various components under the hood. Both of these libraries export their own version of **DataNode** which are very similar to each other but have unique properties and shapes. In particular the rc-tree-select DataNode has additional properties used for custom filtering like **value** and also doubles as a dictionary. 

rc-tree :
![WhatPropProvides](https://user-images.githubusercontent.com/12073642/119160508-5acf7100-ba26-11eb-9cb1-86406091cedd.PNG)

 rc-tree-select:
![WhatTreeSelectActuallyAccepts](https://user-images.githubusercontent.com/12073642/119160509-5acf7100-ba26-11eb-806e-de15d9470465.PNG)
^ This particular type is what is used by 
```
<TreeSelect
              treeData={treeData}
              ---
```

However despite these differences it seems antd only exports the rc-tree DataNode. 

![WhatIsAvailableToImport2](https://user-images.githubusercontent.com/12073642/119160886-b699fa00-ba26-11eb-9436-ba626ba8ea2e.png)

This is problematic for users who need to build up rc-tree-select nodes using functions/hooks or if they need to pass them around in a typescript codebase. In particular if a user needs to use the **value** for filtering or just any custom property in their nodes typescript will complain if you import __import { DataNode } from "antd/lib/tree";__ and try to set those times.

It's entirely possible that the rc-tree-select DataNode is exposed from antd but as far as Visual Studio Code is concerned it can't find it. If an export actually is provided for the correct DataNode then we can close this ticket. However if it is not then I think its a valid request as right now we are surviving off of using our own custom DataNode type:

```
type TreeSpecificDataNodeProps = {
  value?: string | number;
  treeFilterValue?: string | number;
};

type FormDataNode = DataNode & TreeSpecificDataNodeProps;
```

But it would be better maintenance-wise if we can use direct types from the Antd API.

### What does the proposed API look like?
A TreeDataNode specific type is exported. It can either have a unique name or not as long as its importable / alias-able.

**Comment by CoryBond** [comment]
Hello Antd team, 

Its not exactly finished yet (I am still facing some eslint issues not understanding JSX types) but I was able to recreate the situation that drove me to make this original request.

In the following codesandbox: https://codesandbox.io/s/antd-reproduction-template-forked-sm987?file=/index.tsx I have imported DataNode from "antd/lib/tree" but it does not have the properties "value" or "treeFilterValue" that I need to get the behavior I want for TreeSelect.

To get around this I have unionized DataNode with my own custom type. I would rather be able to import a DataNode type like the TreeSelect actually consumes:

export interface DataNode {
    value?: RawValueType;
    title?: React.ReactNode;
    label?: React.ReactNode;
    key?: Key;
    disabled?: boolean;
    disableCheckbox?: boolean;
    checkable?: boolean;
    children?: DataNode[];
    /** Customize data info */
    [prop: string]: any;
}

Is this already possible with the latest release of antd or if not can it please be?

**Comment by alwaysloseall** [comment]
> Hello Antd team,
> 
> ~Its not exactly finished yet (I am still facing some eslint issues not understanding JSX types) but~ I was able to recreate the situation that drove me to make this original request.
> 
> In the following codesandbox: https://codesandbox.io/s/antd-reproduction-template-forked-sm987?file=/index.tsx I have imported DataNode from "antd/lib/tree" but it does not have the properties "value" or "treeFilterValue" that I need to get the behavior I want for TreeSelect.
> 
> To get around this I have unionized DataNode with my own custom type. I would rather be able to import a DataNode type like the TreeSelect actually consumes:
> 
> ```
> export interface DataNode {
>     value?: RawValueType;
>     title?: React.ReactNode;
>     label?: React.ReactNode;
>     key?: Key;
>     disabled?: boolean;
>     disableCheckbox?: boolean;
>     checkable?: boolean;
>     children?: DataNode[];
>     /** Customize data info */
>     [prop: string]: any;
> }
> ```
> 
> Is this already possible with the latest release of antd or if not can it please be?
> For Antd verisons:
> 
> * ```
>   4.15.6
>   ```
> * ```
>   4.12.2
>   ```
> 
> Is there an export which already exists?

need global export，
i did it

then you can use it like this:

```js
import { TreeDataNode } from "antd"
```

**Comment by CoryBond** [comment]
Hey alwaysloseall,

When I try to import the following:

`import { DataNode, TreeDataNode } from "antd";
`
The IDE (VSC and Codesandbox) flags both saying the import can't be found.

Are you referring to a particular version when you suggest using the global export? I am using 4.12.2 right now.

**Comment by CoryBond** [comment]
In fact when I try to upgrade the CodeSandbox package to use 4.16.0 (latest I believe) I still see the import errors:

![StillImportErrorsWith_4 16 0](https://user-images.githubusercontent.com/12073642/119830491-509bef80-beca-11eb-9c9f-c5d929bdc30a.gif)
