### ISSUE TITLE
CSS “*” 选择器导致的性能问题

### ISSUE THREAD

**Issue by renzhao1113** [ant-design/ant-design#30623]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-suyrte?file=src/App.js](https://stackblitz.com/edit/react-suyrte?file=src/App.js)

### 业务场景
我们是做在线文档协作的，页面DOM比较多且复杂，经常超过2万个DOM

### 重现步骤
* 引入``antd.css``或者``antd.less``后，动态修改页面样式造成页面卡顿（此现象出现在``4.3.0``及以上版本）
* 不引入样式文件时页面反应正常

### 原因排查
以下代码造成css性能瓶颈，删除代码即可恢复正常；
https://github.com/ant-design/ant-design/blob/9275866f24151072ef3feb9ece150ece0f04cf2a/components/style/core/base.less#L11-L16

同时，个人感觉下面这段代码，与上面的代码功能重复，仅需下面这段代码即可；
https://github.com/ant-design/ant-design/blob/9275866f24151072ef3feb9ece150ece0f04cf2a/components/style/core/global.less#L32-L36

### What is expected?
删除或者改造``base.less``文件的 11~16 行代码，改善css性能

### What is actually happening?
``base.less`` 文件的 ``11~16`` 行代码，造成css性能低下

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | 16.12.0 |
| System | mac-OS 10.15.6 |
| Browser | chrome 90 |

---
可通过在重现链接中，取消和导入antd.css文件，配合Performance观察rendering性能，差距非常明显

**Comment by afc163** [comment]
看上去可以删掉，来个 PR 试试

**Comment by zombieJ** [comment]
感觉可以看看之前说的打两个包，一个带全局的一个不带分一分。

ref #9363

**Comment by afc163** [comment]
> 感觉可以看看之前说的打两个包，一个带全局的一个不带分一分。

感觉解决不了，现在是不带全局的这个有样式性能问题。

https://github.com/ant-design/ant-design/blob/9275866f24151072ef3feb9ece150ece0f04cf2a/components/style/core/base.less#L12-L16

**Comment by zombieJ** [comment]
分两步走，base 这个去掉用 global 的。然后 antd 提供一个额外的 css 文件：
* antd.css
* antd-pure.css
* antd-reset.css

**Comment by zombieJ** [comment]
reset 让用户自己选择是否使用 global 的 css。

**Comment by afc163** [comment]
这三个分别代表什么？哪一个不含 https://github.com/ant-design/ant-design/blob/9275866f24151072ef3feb9ece150ece0f04cf2a/components/style/core/base.less#L12-L16 代码？

**Comment by zombieJ** [comment]
重置所有元素包含伪类的 `box-sizing`，用 global 的 * 就行了。

**Comment by renzhao1113** [comment]
> 重置所有元素包含伪类的`box-sizing`，用global的*就行了。

嗯，目前是把base文件重写了一下，删了包含*的那段代码

**Comment by renzhao1113** [comment]
> 重置所有元素包含伪类的`box-sizing`，用global的*就行了。

嗯，目前是把base文件重写了一下，删了包含*的那段代码

**Comment by renzhao1113** [comment]
我在本地重写了``base.less``文件，重新写了antd的样式入口文件，
重写`base.less`
```less
// Config global less under antd
[class^=~'@{ant-prefix}-'],
[class*=~' @{ant-prefix}-'] {
  // remove the clear button of a text input control in IE10+
  &::-ms-clear,
  input::-ms-clear,
  input::-ms-reveal {
    display: none;
  }
}

```
重写后的样式入口`my-antd.less`
```less
// themes
@import '~antd/lib/style/themes/index';

// core
@import '~antd/lib/style/mixins/index';
@import 'base';
@import '~antd/lib/style/core/global';
@import '~antd/lib/style/core/iconfont';
@import '~antd/lib/style/core/motion';

// components
@import '~antd/lib/style/components';
```

`App.less`
```less
// @import '~antd/lib/style/index.less'
@import './styles/my-antd.less'
```
