### ISSUE TITLE
Make possible to capture what mouse button was clicked on SubMenu item

### ISSUE THREAD

**Issue by eduardobalbo** [ant-design/ant-design#30621]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Just like `<Menu.Item>`, `<SubMenu>` should also have the same or some of the same mouse Events like `onMouseDown`, `onMouseUp `and `onClick`.
I dont know if i'm being mistaken but you cant get wich mouse button was pressed by the `onTitleClick` Event that the `<SubMenu>` component has right now.
We're implementing a menu that has some integrated functions, so right mouse click and middle mouse click handles different functions, but we can't achieve that on `<SubMenu>`, only on `<Menu.Item>`.

If it is possible to do this with 'onTitleClick' could you show how?
Thanks.

### What does the proposed API look like?
```
<SubMenu
   onMouseDown={(e) => console.log('You pressed mouse button:', e.button)}
>
```

**Comment by afc163** [comment]
It works.

https://codesandbox.io/s/dingbudaohang-antd4160-forked-xrdxt?file=/index.js

**Comment by eduardobalbo** [comment]
Thank you!
