### ISSUE TITLE
Cascader 的回显问题

### ISSUE THREAD

**Issue by wanglianjie91** [ant-design/ant-design#30632]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在Cascader中，后端数据库只保存了最后一级的id， 在回显的时候不能够正确显示。

### What does the proposed API look like?
通过参数控制，能够正确回显数据。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29913#issuecomment-808377737

**Comment by wanglianjie91** [comment]
感谢及时回复。
了解了组件的设计思路。
