### ISSUE TITLE
Bug when inputNumber enters period( 。)

### ISSUE THREAD

**Issue by wangzongming** [ant-design/ant-design#30639]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/input-number-cn/](https://ant-design.gitee.io/components/input-number-cn/)

### Steps to reproduce
Direct input of Chinese symbol (。)

### What is expected?
And other Chinese input can not be directly input

### What is actually happening?
input in two little dots

| Environment | Info |
|---|---|
| antd | 4.9.2 |
| React | 17.1 |
| System | window10 |
| Browser | Chrome 75.0.3770.80（正式版本） （64 位） |

**Comment by afc163** [comment]
为啥要输入句号？

**Comment by wangzongming** [comment]
> 为啥要输入句号？

尴尬了...。这个和输入其他的中文符号表现不一样，所以用户感觉是bug

**Comment by afc163** [comment]
这里是有意的优化：https://github.com/react-component/input-number/blob/8482ddac72f137db3b4134a0c17cc9016d950a0f/src/InputNumber.tsx#L354-L358

**Comment by wangzongming** [comment]
> 这里是有意的优化：https://github.com/react-component/input-number/blob/8482ddac72f137db3b4134a0c17cc9016d950a0f/src/InputNumber.tsx#L354-L358

谢谢老哥😊
