### ISSUE TITLE
下拉框选择时若带有span标签，鼠标滑至选中项，显示的title是object，有其他方式对option进行颜色回填吗？

### ISSUE THREAD

**Issue by qiannianv** [ant-design/ant-design#3063]
#### 发生问题的环境是：

- antd 版本:1.8
- 操作系统及其版本:win7
- 浏览器及其版本:谷歌
#### 可重现的在线演示

 Fork http://codepen.io/anon/pen/bwZyxN?editors=001

**Comment by benjycui** [comment]
选中后也需要颜色是么？

![image](https://cloud.githubusercontent.com/assets/3580607/18613664/d926d7d4-7db1-11e6-8d90-57a2ff99a054.png)

**Comment by qiannianv** [comment]
恩是的，下拉和选中都要

**Comment by afc163** [comment]
title 做下判断，是对象就不显示了。

**Comment by benjycui** [comment]
这种情况 `<Option key={i.toString(36) + i}>中文{i}</Option>`，JSX 会把 `中文{i}` 处理成数组 `['中文', i]`，但直觉上，应该是当成字符串？

所以只是屏蔽对象类型，可能会出现反直觉的情况。

还是说增加 `Option[title]`，直接让用户自行拼接 `title`？

**Comment by afc163** [comment]
`Option[title]` :+1:

**Comment by qiannianv** [comment]
不是很明白你的意思，是在option中加title属性？试了下还是显示object
Fork http://codepen.io/anon/pen/ALLpjE?editors=001

**Comment by qiannianv** [comment]
意思是后面option新增一个title属性吗？还是现在可以这样处理？

**Comment by benjycui** [comment]
需要新增属性。
