### ISSUE TITLE
Modal style API improvement

### ISSUE THREAD

**Issue by cftan98** [ant-design/ant-design#30630]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The style API will be used when the user wants to customize the styling of a modal.

I believe the style API already exists in the modal API, however, it seems not very useful under the scenario that when a user wants to customize the whole modal in-line because he or she still have to set the style in CSS file using className but not using the style API directly. 

e.g. a previous issue as a reference https://github.com/ant-design/ant-design/issues/30608

### What does the proposed API look like?
I hope the style API of Modal component can style the whole modal rather than using a className and style in CSS file.

    <Modal
        style={{backgroundColor: 'pink', borderRadius: '10px'}}
    >
        <p>Some contents...</p>
        <p>Some contents...</p>
        <p>Some contents...</p>
    </Modal>

**Comment by afc163** [comment]
Please use `className` if you need more styling costomization.
