### ISSUE TITLE
Menu设置mode="horizontal"宽度不够时候闪烁

### ISSUE THREAD

**Issue by 1412810457** [ant-design/ant-design#30645]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-bhaskara-okm46)

### Steps to reproduce
1、调整浏览器大小宽度有闪烁，调整浏览器大小时候，注意慢慢一点点调整，问题才明显过快看不见效果；
2、查看代码发现跳动 style=“display：none”，不停变动造成的，实际代码里面没有写入控制，怀疑是BUG。

### What is expected?
能支持浏览器调整大小后不闪烁

### What is actually happening?
宽度不够时候闪烁，调整浏览器大小到一定宽度就开始跳动。

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | windows |
| Browser | chrome\edge |

**Comment by afc163** [comment]
将在 https://github.com/ant-design/ant-design/pull/30382 里修复。

**Comment by yehoan** [comment]
我目前版本    "antd": "^4.17.3", 为什么还是发现了这个BUG啊

**Comment by yehoan** [comment]
当设置mode="horizontal" 就一直闪屏

**Comment by simple5960** [comment]
5.6.0还是有这个问题

**Comment by simple5960** [comment]
> 将在 #30382 里修复。

没有修复呀，5.6.0 还存在这个问题
