### ISSUE TITLE
新版 menu 的一些问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#30643]
- [ ] submenu 的高亮丢了，看一下 https://www.argos-ci.com/ant-design/ant-design/builds/919
- [ ] bundlesize 体积超出。
- [ ] snapshot 有点问题。https://github.com/ant-design/ant-design/pull/30646/checks?check_run_id=2655228845

**Comment by zombieJ** [comment]
* 高亮有的：https://preview-30646-ant-design.surge.sh/components/menu-cn/#components-menu-demo-style-debug
* bundle size #30646 解了
* snapshot 应该是 overflow 的 fix，我瞅瞅~

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/119444156-60e28c00-bd5d-11eb-8fbd-db302f4cfac1.png)
![image](https://user-images.githubusercontent.com/6937879/119444193-6d66e480-bd5d-11eb-84cd-a9c0024e2773.png)
![image](https://user-images.githubusercontent.com/6937879/119444242-7bb50080-bd5d-11eb-9472-eb8d7eccbfcf.png)
1、自动折叠有问题
2、hover时，多了个箭头
3、点击后没有自动关闭
