### ISSUE TITLE
Can't load font.

### ISSUE THREAD

**Issue by xueqingxiao** [ant-design/ant-design#3064]
<img width="1359" alt="screen shot 2016-09-18 at 2 43 12 pm" src="https://cloud.githubusercontent.com/assets/4010906/18613467/43ef7340-7dae-11e6-9f7c-34c734c0ebbf.png">
@benjycui Please Check.

**Comment by benjycui** [comment]
ant.design 和 beta.ant.design 都没有问题，麻烦提供重现方式。

**Comment by xueqingxiao** [comment]
@benjycui VPN  新加坡的机房

**Comment by benjycui** [comment]
这种自行部署 icon font 吧 https://github.com/ant-design/antd-init/tree/7c1a33cadb98f2fd8688fe527dd7f98215b9bced/examples/local-iconfont

**Comment by afc163** [comment]
这个是 ant.design 首页的字体样式，用的是 360 的代理服务：http://libs.useso.com/

确实不是很稳定。

**Comment by xueqingxiao** [comment]
@benjycui @afc163 确实是这个网址

**Comment by afc163** [comment]
去掉代理了，google 的服务貌似不用翻墙了。
