### ISSUE TITLE
Adding search field to dropdown filters.

### ISSUE THREAD

**Issue by lxtadhamnawito** [ant-design/ant-design#30654]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm using antd Table, and trying to add some filters to columns. But since the column's dropdown menu filter could have a very long options, 
I want to add a search field inside the filters to be able to access them easily from Filters, and select it.

[filters I have](https://files.fm/u/8jdtndjes#/view/pjmz2kzx7).  I want to add a search field inside this list to search among them. [like that](https://files.fm/u/ruf9ke7ya#/view/93maczqxh)

I see that there are two different things,

1- [filters](https://stackblitz.com/run) --> which it takes array and get displayed and act upon it. (this what i'm using) 

2- [filterDropdown](https://stackblitz.com/run) --> which allow search among the table's column itself.

### What does the proposed API look like?
What I'm proposing is a mix between both, where I can set a dropdown menu containing all the filters I have, and in the same time 
it has a search filed to search among the filters not the column to allow ease accessibility for long or various filters options.

**Comment by lxtadhamnawito** [comment]
@afc163  any updates ?

**Comment by afc163** [comment]
supported in https://github.com/ant-design/ant-design/pull/31809
