### ISSUE TITLE
新版 Collapse 参数配置 expandIconPosition:right失效

### ISSUE THREAD

**Issue by hongdeyuan** [ant-design/ant-design#30668]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/278irv)

### Steps to reproduce
 将 expandIconPosition设置为right失效

### What is expected?
图标应该去到右侧

### What is actually happening?
依然没去到右侧，只是一个空白 显示区域

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React |  react |
| System | Mac os |
| Browser | 谷歌 90.0.4430.212 |

![image](https://user-images.githubusercontent.com/37143703/119454093-b7a29280-bd6a-11eb-916d-efd6f82a38be.png)

**Comment by hongdeyuan** [comment]
I raised a PR, maybe it can meet expectations: https://github.com/ant-design/ant-design/pull/30680

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/30680
