### ISSUE TITLE
4.16版本Drawer组件在移动端触发 touchmove事件 报错：Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by Big-fishing** [ant-design/ant-design#30669]
### 官网可复现
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### 问题详情
mask为true的时候才会报错，内容超出有滚动条的话竖划不会报错，但横划报错。如果内容没有超出没有滚动条只要划动就会报错

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | react 17.0.2 |
| System | win 10 |
| Browser | Google Chrome  90.0.4430.212 |

**Comment by jljsj33** [comment]
真机上有报错吗。。。 chrome 的模拟有问题的

**Comment by afc163** [comment]
Duplicate of #28787
