### ISSUE TITLE
新版 Menu 的一些问题

### ISSUE THREAD

**Issue by tangjinzhou** [ant-design/ant-design#30665]
1、自动折叠有问题
2、hover时，多了个箭头
3、点击后没有自动关闭

官网可复现

![image](https://user-images.githubusercontent.com/6937879/119444156-60e28c00-bd5d-11eb-8fbd-db302f4cfac1.png)
![image](https://user-images.githubusercontent.com/6937879/119444193-6d66e480-bd5d-11eb-84cd-a9c0024e2773.png)
![image](https://user-images.githubusercontent.com/6937879/119444242-7bb50080-bd5d-11eb-9472-eb8d7eccbfcf.png)

**Comment by afc163** [comment]
问题 1 更多可见 https://github.com/ant-design/ant-design/issues/30662

**Comment by zombieJ** [comment]
@tangjinzhou  点击后没有关闭这个复现步骤是？
