### ISSUE TITLE
Menu overflow item width in antd@4.16.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#30662]
- [ ] 水平菜单最后有一个带宽度的占位符，是否不应该占据空间。

<img width="1087" alt="图片" src="https://user-images.githubusercontent.com/507615/119434440-c8dba700-bd4a-11eb-88c0-3b690e938e43.png">

- [ ] 缩小宽度后无法正确的缩略，出现了换行。

<img width="876" alt="图片" src="https://user-images.githubusercontent.com/507615/119434492-dbee7700-bd4a-11eb-9176-ce589411d123.png">

- [ ] 网站顶部菜单右侧也有这个占位符，导致菜单右侧多了一块空白。而且这个占位符有 `.ant-menu-submenu` 的 className，导致被现有的覆盖样式命中。是否可以不加上这些 className，极易被污染。正确的效果可以对比一下 https://preview-30549-ant-design.surge.sh/index-cn

<img width="806" alt="图片" src="https://user-images.githubusercontent.com/507615/119434546-ffb1bd00-bd4a-11eb-8c02-f7350eb789f3.png">

**Comment by zombieJ** [comment]
最后一个是用于测量 extra size 的 hidden 占位，我想想办法。

**Comment by zombieJ** [comment]
- [x] 水平菜单最后有一个带宽度的占位符，是否不应该占据空间。
* Ref：https://github.com/react-component/overflow/pull/11

  - [ ] 网站顶部菜单右侧也有这个占位符，导致菜单右侧多了一块空白。而且这个占位符有 `.ant-menu-submenu` 的 className，导致被现有的覆盖样式命中。是否可以不加上这些 className，极易被污染。正确的效果可以对比一下 https://preview-30549-ant-design.surge.sh/index-cn
  * 多出来的这部分需要被 className 影响，否则测量尺寸就不对了。这个和原本的 className 是保持一致的。


- [ ] 缩小宽度后无法正确的缩略，出现了换行。
* Ref: #30672
