### ISSUE TITLE
use Form.List then Removing one item in the Form.List item Row, the Form value didn't remove the value 

### ISSUE THREAD

**Issue by nikomal** [ant-design/ant-design#30676]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fuzadedongtaizengjianbiaodanxiang-antd4160-forked-kpq5g?file=/index.js)

### Steps to reproduce
first add sights, then fill in "Sight" and "Price";
change "Area" to "Beijing", the "Price" is removed;
but when Submit , the Form value is still has the "Price".

### What is expected?
then "Price" item removed, the "Price" removed too,

### What is actually happening?
the "Price" value still alive

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.14.0 |
| System | mac  |
| Browser | chrome 80 |

**Comment by zombieJ** [comment]
Use `preserve={false}`:
https://codesandbox.io/s/fuzadedongtaizengjianbiaodanxiang-antd4160-forked-otn0f?file=/index.js:3039-3055

**Comment by charminghiker** [comment]
我在Form.List中使用了ProFormText也会导致删不掉，改用<Form.Item><Input/></Form.Item>就可以了。 
请问From.List不支持Pro组件吗？
@zombieJ
