### ISSUE TITLE
TextArea(input) want “getCount” function

### ISSUE THREAD

**Issue by NnnLillian** [ant-design/ant-design#30671]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前，showCount 只能出现在TextArea的【外侧，右下角】。（Now, showCount appeared in a fixed position as below pic）
![image](https://user-images.githubusercontent.com/38904256/119457119-e8d09200-bd6d-11eb-8499-69104eb8bbba.png)

1. 有的场景下需要在内部的右下角或者作为toast弹出告诉用户。（showCount can display by other way, which includes on other position and in a toast）
2. 不仅仅只有TextArea需要，有时普通的input也需要计数。(showCount could not only be used in TextArea)
3. 如下所示（as shown below）
![image](https://user-images.githubusercontent.com/38904256/119457319-20d7d500-bd6e-11eb-9a9a-d5fce4a96a57.png)

### What does the proposed API look like?
just like or something better ```getCount = (e) => { console.log(e.count) }```

### Why not use value.length
通过 onChange 获得的 value，无法将emoji计算成一个字符。
```
// value = '😀'
const onChange = (e) => {
   e.target.value.length; // 2
};
```

**Comment by zombieJ** [comment]
You should not depends on component internal state. Just copy this func in you code instead: https://github.com/ant-design/ant-design/blob/0a0fa61cb5febe5ecdf6c0f4e2bb9aa268472766/components/input/TextArea.tsx#L16
