### ISSUE TITLE
Long strings in menu aren't ellipsed

### ISSUE THREAD

**Issue by artplan1** [ant-design/ant-design#30679]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-iyhwb?file=/index.js)

### Steps to reproduce
1st issue: use long string in menu options
2nd issue: use long string in submenu title without icon

### What is expected?
ellipsis like in 4.15.6

![image](https://user-images.githubusercontent.com/9060346/119486079-88872380-bd60-11eb-9b88-a39f7365dcae.png)

### What is actually happening?
no ellipsis in 4.16.0

![image](https://user-images.githubusercontent.com/9060346/119485958-5ecdfc80-bd60-11eb-8049-680b281a4fd9.png)

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17 |
| System | mac os |
| Browser | chrome 90 |

**Comment by yoyo837** [comment]
Maybe fixed by #30672
