### ISSUE TITLE
Unhelpful "MenuItem or SubMenu should not leave undefined `key`."

### ISSUE THREAD

**Issue by openscript** [ant-design/ant-design#30677]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2pqd1)

### Steps to reproduce
1. Create a menu component with a divider
2. Don't give the divider a key and run

### What is expected?
The warning in the console should mention, that also dividers need a key attribute.

### What is actually happening?
A warning is displayed which is hard to understand.

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | React 17.0.2 |
| System | Linux ed1dd2f32e1c 5.12.6-arch1-1 #1 SMP PREEMPT Sun, 23 May 2021 00:45:50  0000 x86_64 GNU/Linux |
| Browser | Firefox 88.0.1 (64-bit) for Arch Linux |

**Comment by birdycn** [comment]
您好解决了吗

**Comment by openscript** [comment]
Yes it's solved in 4.16.1.

**Comment by cike8899** [comment]
> Yes it's solved in 4.16.1.

4.16.2 依然报错

![image](https://user-images.githubusercontent.com/8089971/121486233-8a5d1200-ca03-11eb-81c7-85f0de7a0e10.png)

**Comment by yoyo837** [comment]
> > Yes it's solved in 4.16.1.
> 
> 4.16.2 依然报错
> 
> ![image](https://user-images.githubusercontent.com/8089971/121486233-8a5d1200-ca03-11eb-81c7-85f0de7a0e10.png)

npm list rc-menu 看看是什么版本

**Comment by openscript** [comment]
Check out the code sandbox above. It's on 4.16.2 and the issue doesn't appear. Maybe you run into another issue?

**Comment by iscmcloud** [comment]
4.16.3依然存在这个问题

**Comment by openscript** [comment]
@iscmcloud Can you open a new ticket with a code sandbox which reproduces the issue and link this issue? I'm not sure if exactly this issue still exists. I don't have the problem anymore.

**Comment by alexeychirkov** [comment]
Issue still actual on 4.16.7

**Comment by kiana-god** [comment]
问题在 4.16.13 上仍然存在

**Comment by openscript** [comment]
@alexeychirkov @kiana-god @iscmcloud 
I cannot reproduce it anymore: https://codesandbox.io/s/antd-reproduction-template-forked-hv5pk

Can you add a sandbox which reproduces it?

**Comment by alexeychirkov** [comment]
> @alexeychirkov @kiana-god @iscmcloud 
> 
> I cannot reproduce it anymore: https://codesandbox.io/s/antd-reproduction-template-forked-hv5pk
> 
> 
> 
> Can you add a sandbox which reproduces it?

Hello.
Just add `<Menu.Item>item1</Menu.Item>` next to divider...

**Comment by openscript** [comment]
You can fix it with `<Menu.Item key="item1">item1</Menu.Item>`. I think this is intended, because it should be possible to identify menu items on the same hierarchy.

**Comment by kiana-god** [comment]
我升级了ant 版本。antd": "4.16.13，依旧有这个问题，直到我升级了 pro-layout 的最新版本就没这个问题

**Comment by imloren** [comment]
4.17.4依旧存在这个问题
