### ISSUE TITLE
Custom filtering of the table data

### ISSUE THREAD

**Issue by LukaszGrela** [ant-design/ant-design#30683]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to use custom filtering on the table data. I would envisage this as a prop `filters` function that when applied to the table will filter the data. Of course I could do filtering on data source if that's how the it should work, e.g. search on all columns.

### What does the proposed API look like?
On the table prop
```
filter: (record:RecordType) => boolean;
```
returning `true` means there is a match.

**Comment by afc163** [comment]
You can filter dataSource before pass to Table.
