### ISSUE TITLE
所有组建对触摸的需求

### ISSUE THREAD

**Issue by WinterWoods** [ant-design/ant-design#30688]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
触摸平板设备逐渐在增多，我们系统也需要去适配，但是现有组建只适合在pc上使用，希望开发组考虑基于触摸板本的5.0版本，比如表格的滑动翻页，日历的滑动翻页，比如tabs的滑动，图片的滑动放大缩小，关闭等。

### What does the proposed API look like?
期望能有对触摸设备的支持考虑在5.0版本中。

**Comment by afc163** [comment]
antd 目前还是专注在 PC 端，移动端只会做有限度的适配。

类似 tabs 的支持可以跟踪 https://github.com/ant-design/ant-design/issues/25543
