### ISSUE TITLE
Cascader能否在ref上主动触发浮层的显示

### ISSUE THREAD

**Issue by LanJamRom** [ant-design/ant-design#30687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们的需求就是像table的可编辑单元格一样，处于编辑状态时，通过ref使他自动聚焦弹出浮层。

### What does the proposed API look like?
期望跟Select中的一样 ref中有一个selectRef能让我手动focus

**Comment by afc163** [comment]
建议用 popupVisible 控制显示隐藏状态。
