### ISSUE TITLE
有考虑下个大版本去掉moment么？

### ISSUE THREAD

**Issue by ayiaq1** [ant-design/ant-design#30695]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前moment没有维护了，而且大多数项目都用的其他第三方库

### What does the proposed API look like?
整个UI库去掉moment

**Comment by zombieJ** [comment]
merge into #26759
