### ISSUE TITLE
Collapsed Sider not hiding Menu.Item children

### ISSUE THREAD

**Issue by alextrastero** [ant-design/ant-design#30698]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapse-sider-not-hiding-text-z43i0)

### Steps to reproduce
Create a Sider with Menu and Menu.Item with icon, when collapsed the text doesn't disappear, this happened when updating from 4.15 to 4.16

### What is expected?
menu.item content hidden when collapsed

### What is actually happening?
menu.item content has an ellipsis

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.x |
| System | mac os |
| Browser | chrome |

**Comment by alextrastero** [comment]
![image](https://user-images.githubusercontent.com/4152819/119625180-3569ab00-be0a-11eb-80d4-597603ac5302.png)

**Comment by afc163** [comment]
- ✅ 4.15.6 https://codesandbox.io/s/collapse-sider-not-hiding-text-forked-tjj9s?file=/index.js
- ❌ 4.16.0 https://codesandbox.io/s/collapse-sider-not-hiding-text-z43i0

**Comment by binyellow** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/collapse-sider-not-hiding-text-z43i0)
> 
> ### Steps to reproduce
> Create a Sider with Menu and Menu.Item with icon, when collapsed the text doesn't disappear, this happened when updating from 4.15 to 4.16
> 
> ### What is expected?
> menu.item content hidden when collapsed
> 
> ### What is actually happening?
> menu.item content has an ellipsis
> 
> Environment	Info
> antd	4.16.0
> React	16.x
> System	mac os
> Browser	chrome

`<Menu inline>{children}<Menu/>`
设置Menu inline模式
