### ISSUE TITLE
Form表单问题请教

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3069]
请问，在Form表单中如何获取DatePicker和TimePicker选择的值，我要把数据通过ajax传到服务端去。

我是这样写的：
const { getFieldProps } = this.props.form;
const dateSelect = getFieldProps('dateSelect');
const timeSelect = getFieldProps('timeSelect');

<Form horizontal onSubmit={this.handleSubmit}>
     <FormItem {...formItemLayout} label="日期" >
               <DatePicker {...dateSelect}/>
     </FormItem>
     <FormItem {...formItemLayout} label="时间">
                <TimePicker {...timeSelect}/>
     </FormItem>
</Form>

打印语句：
console.log('收到表单值：', this.props.form.getFieldsValue());
但是打印的数据都是完整的日期加时间，这里要用到属性或者状态？

**Comment by RifeWang** [comment]
打印的数据是这样的：dateSelect: Thu Sep 01 2016 22:31:29 GMT+0800 (中国标准时间), timeSelect: Sun Sep 18 2016 22:36:29 GMT+0800 (中国标准时间)
不论是DatePicker还是TimePicker，最后都是完整的日期加时间

**Comment by infeng** [comment]
new Date(this.props.form.getFieldValue('dateSelect'))不就可以获取Date对象

**Comment by benjycui** [comment]
因为返回的是一个日期对象，而日期对象必然包含完整的日期和时间，自行截取所需部分即可。
