### ISSUE TITLE
选择器Select的menuItemSelectedIcon属性在单选模式下生效了

### ISSUE THREAD

**Issue by YogaZheng** [ant-design/ant-design#30702]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-dawn-cjwxy)

### Steps to reproduce
```
<Select menuItemSelectedIcon={<span>yes</span>}>
        <Option value="jack">Jack</Option>
        <Option value="lucy">Lucy</Option>
        <Option value="Yiminghe">yiminghe</Option>
</Select>
```
运行上述代码，确认该选择器下拉框已选择项的样式。

### What is expected?
Select选择器即便是使用了menuItemSelectedIcon自定义勾选图标，在单选模式下也不应该显示勾选样式。

### What is actually happening?
单选模式下的Select下拉菜单勾选项出现了自定义的勾选样式。

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.13.1 |
| System | windows10 x64 |
| Browser | Google Chrome 90.0.4430.212 |

**Comment by afc163** [comment]
单选模式 menuItemSelectedIcon 默认是空，但是设置上也会有效，有些场景可能需要强调选中状态。
