### ISSUE TITLE
Table表头每一列的线条能不能改成可以动态去掉的

### ISSUE THREAD

**Issue by hyj228** [ant-design/ant-design#30704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
官网的table

### What is expected?
希望表格列的线条可以动态去除  因为一些需求中是不需要这个线的

### What is actually happening?
现在是不能去除的只能通过重新css的方式去除

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17 |
| System | macOS Big Sur |
| Browser | Google Chrome |

**Comment by afc163** [comment]
目前只能通过覆盖 css 样式做到。
