### ISSUE TITLE
table组件没有全局导出ColumnsType类型

### ISSUE THREAD

**Issue by qqabcv520** [ant-design/ant-design#30711]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table组件全局导出了ColumnType类型，却没有导出ColumnsType类型，导致在bigfish中使用的时候，无法使用@alipay/bigfish/antd引入，需要从antd/table/interface下引入

### What does the proposed API look like?
table组件全局导出ColumnsType类型

**Comment by alwaysloseall** [comment]
#21321
这个 PR 解决了这个问题的呀

**Comment by alwaysloseall** [comment]
I did it
