### ISSUE TITLE
in Dropdown menu , open Modal  that subMenu dont' close

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design#30710]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4160-forked-f1e1z?file=/index.js)

### Steps to reproduce
请看链接 https://codesandbox.io/s/jiben-antd4160-forked-f1e1z?file=/index.js

### What is expected?
点击 SubMenu 中的 MenuItem 后，出现弹窗， SubMenu 将被隐藏

### What is actually happening?
点击 SubMenu 中的 MenuItem 后，出现弹窗， SubMenu 未能隐藏

![image](https://user-images.githubusercontent.com/28672197/119675733-e0f91680-be6f-11eb-8e0a-7c0016bad9a8.png)

![image](https://user-images.githubusercontent.com/28672197/119675772-e9e9e800-be6f-11eb-9120-e9c96d1b07e8.png)

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.1 |
| System | mac 11.1 |
| Browser | chmore 88 |

**Comment by JoeCMorgan** [comment]
We've got a similar issue, although an `eventKey` prop is being added to our SubMenu containers - `<div eventkey="tmp_key-notifications-0">`, which is causing a React error:

```
 React does not recognize the `eventKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `eventkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Possibly related?

**Comment by zombieJ** [comment]
Worked in 4.15.x https://codesandbox.io/s/jiben-antd4160-forked-tbgt3

**Comment by zombieJ** [comment]
follow up of https://github.com/react-component/menu/pull/396

**Comment by JoeCMorgan** [comment]
This is still an issue in `v.4.16.0` https://github.com/ant-design/ant-design/issues/30710#issuecomment-849532520

**Comment by yoyo837** [comment]
remove node_modules and reinstaill

**Comment by zombieJ** [comment]
@JoeCMorgan ,
`npm ls rc-menu` what's the version?

**Comment by pgejgalis-codilime** [comment]
@zombieJ  I've the same issue. Here you have result of `npm ls rc-menu`:
```
`-- antd@4.16.2
  +-- rc-mentions@1.6.1
  | `-- rc-menu@9.0.11  deduped
  +-- rc-menu@9.0.11
  `-- rc-tabs@11.9.1
    `-- rc-menu@9.0.11  deduped
```
