### ISSUE TITLE
仅仅引入一个官网的DatePicker, message组件，火狐下挂了，其他浏览器是好的

### ISSUE THREAD

**Issue by mankeheaven** [ant-design/ant-design#3071]
火狐下 报错
	SyntaxError: JSON.parse: missing digits after decimal point at line 1 column 3 of the JSON data 
断点定位Array.from(riter, function(){ throw 2; });
我自己配置的webpack.config.js，模块就是正常的react生态圈模块，加上antd。完全走的官网的流程。
操作系统32位win7
antd1.11.1
浏览器谷歌和搜狗都是正常，火狐挂了，报错打不开

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
我用的就是 Firefox，没有问题。

> 不给重现方式的报告都是耍流氓。
