### ISSUE TITLE
任意类型的message不会自动消失，手动也关闭不了

### ISSUE THREAD

**Issue by Miiskye** [ant-design/ant-design#30717]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/t4lsd?file=/package.json)

### Steps to reproduce
随便引入一个message就可以看到

### What is expected?
message会自动消失

### What is actually happening?
message不会自动消失

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.14.0 |
| System | macOs / windows |
| Browser | 任意浏览器 |

---
升级之后message就不会自动消失了

**Comment by xrkffgg** [comment]
我这里看着可以自动关闭

**Comment by Miiskye** [comment]
用create-react-app重新创建了一个项目引入antd也是可以消失的，但是在项目中antd4.16.0的版本就是消失不了，4.8.5版本的可以

**Comment by xrkffgg** [comment]
重新安装下 node_modules 看看

**Comment by Miiskye** [comment]
安装了很多遍都是一样的，windows和mac的都试过了，4.16.0的不能关闭，而且弹出来没有动画效果

**Comment by zombieJ** [comment]
@Miiskye  给个 github 重现地址看看

**Comment by yoyo837** [comment]
看 https://github.com/ant-design/ant-design/issues/30742

**Comment by Miiskye** [comment]
> @Miiskye 给个 github 重现地址看看

就很奇怪，我重新新建个项目安装和另一个项目一样的依赖也复现不了

**Comment by Miiskye** [comment]
> @Miiskye 给个 github 重现地址看看

感觉应该是按需引入的样式问题

**Comment by zombieJ** [comment]
Duplicate of #30742
