### ISSUE TITLE
ie11 官网demo select dropdown menu 下拉框均无法打开

### ISSUE THREAD

**Issue by ZhangXY-Magic** [ant-design/ant-design#30728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/](https://ant-design.gitee.io/components/select-cn/)

### Steps to reproduce
点击下拉选择框无响应

### What is expected?
出现下拉框

### What is actually happening?
点击无效果

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.0 |
| System | windows10 |
| Browser | ie11 |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/21039

看看这个 有木有帮助

**Comment by afc163** [comment]
Duplicate of #31283
