### ISSUE TITLE
Calendar 切换月份的时候，能否不要自动执行 onSelect 选中该月和今天相同的日期

### ISSUE THREAD

**Issue by lishangwu** [ant-design/ant-design#30739]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
没有

### What does the proposed API look like?
增加一个开关，可以控制是否要自动选中 面板切换后和今天相同的那个日期

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28046#issuecomment-759176541
