### ISSUE TITLE
Dropdown, Date picker, Modal open but not closing

### ISSUE THREAD

**Issue by jeganswiz** [ant-design/ant-design#30738]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://appdev.hitasoft.in/idemand_server/](https://appdev.hitasoft.in/idemand_server/)

### Steps to reproduce
null

### What is expected?
Dropdown, Date picker, Modal Not closing, and i can't able get values from those elements, initially it's all working fine but, unexpectedly when i run npm start on a new day to start my project it's not working properly, i need work those elements are normally

### What is actually happening?
some elements are not working properly, drop down, datepicker, modal are open but not closing and can't able to pass any values, initially it all working finely, but one day morning, i just normally run a npm start command to start my work, those elements are working ubnormally,

here i attach my package.json file

{
  "name": "ondemand",
  "version": "0.1.0",
  "private": true,
  "homepage": "https://appdev.hitasoft.in/idemand_server/",
  "dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "antd": "^4.16.0",
    "axios": "^0.21.1",
    "bootstrap3": "^3.3.5",
    "firebase": "^8.4.3",
    "history": "^5.0.0",
    "jquery": "^3.6.0",
    "node-sass": "^4.14.1",
    "react": "^16.13.1",
    "react-autosuggest": "^10.0.3",
    "react-dom": "^16.13.1",
    "react-firebaseui": "^5.0.2",
    "react-helmet": "^6.1.0",
    "react-id-swiper": "^4.0.0",
    "react-loading-skeleton": "^2.1.1",
    "react-photo-gallery": "^8.0.0",
    "react-router-dom": "^5.2.0",
    "react-router-hash-link": "^2.1.0",
    "react-scripts": "^4.0.3",
    "react-slick": "^0.27.10",
    "react-sticky-header": "^0.2.0",
    "react-tabs": "^3.1.1",
    "recharts": "^1.8.5",
    "simple-react-lightbox": "^3.3.4-1",
    "simplebar-react": "^3.0.0-beta.4",
    "slick-carousel": "^1.8.1",
    "sweetalert2": "^10.16.7",
    "universal-cookie": "^4.0.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "dotenv": "^8.2.0"
  }
}

i'm really disappointed, because i almost complete my project, i already search alot about this issue, no one have the same

so finally i'm here please find any solution for me 

thank you : - )

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.13.1 |
| System | ubuntu 20.04 |
| Browser | chrome 90.0.4430.93 |

**Comment by xurshid29** [comment]
Same problem. Works with 4.10.0 version, but after 4.11 not

Node - 14.16.1
npm - 6.14.12
