### ISSUE TITLE
InputNumber组件defaultValue设置初始值无效

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3073]
- antd 版本:latest
- 操作系统及其版本:Windows
- 浏览器及其版本:chrome

我定义了一个表单组件，在表单域中使用了InputNumber组件，并用defaultValue设置初始值了，但是无效，代码如下：
        let AddForm = React.createClass({

            handleSubmit(e) {
                e.preventDefault();
                console.log('收到表单值：', this.props.form.getFieldsValue());
            },

            render() {
                const formItemLayout = {
                    labelCol: { span: 7 },
                    wrapperCol: { span: 12 },
                };
                const { getFieldProps } = this.props.form;
           
                return (
                        <Form horizontal onSubmit={this.handleSubmit}>
                            <FormItem {...formItemLayout} label="工位">
                                <InputNumber
                                        defaultValue={3}
                                        min={0}
                                        {...getFieldProps('surplus')}
                                />
                            </FormItem>
                            <FormItem {...formItemLayout} label="折扣">
                                <InputNumber
                                        defaultValue={9}
                                        min={0} max={10} step={0.5}
                                        {...getFieldProps('discount')}
                                />
                            </FormItem>
                            <FormItem wrapperCol={{ span: 12, offset: 7 }} style={{ marginTop: 10 }} >
                                <Button type="primary" htmlType="submit">确定</Button>
                            </FormItem>
                        </Form>
                );
            }
        });

        AddForm = Form.create()(AddForm);

        ReactDOM.render(<AddForm />, document.getElementById('container'));

**Comment by benjycui** [comment]
http://ant.design/components/form/#特别注意

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1353
