### ISSUE TITLE
Tree树里的checkBox如何开启多个？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design#30731]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前Tree里的checkBox只有1个；我用每个节点对应的checkBox控制对应物体的显示隐藏；但是我还想要一个checkBox来控制对应物体的透明度等信息；物体和tree里的节点一一对应；所以我想每个节点前开启多个checkBox；

目前我通过title添加了多个icon按钮，但是我不知道如何快速的模拟 组件原来的checkBox的所有事件功能，
![image](https://user-images.githubusercontent.com/5111701/119813061-6c7bb180-bf1b-11eb-93ea-6de225b80167.png)

### What does the proposed API look like?
CheckboxList=[] or CheckNumber=2 ？

**Comment by afc163** [comment]
TreeNode 支持传入 ReactNode。
