### ISSUE TITLE
Collapse expandIconPosition prop not working

### ISSUE THREAD

**Issue by Markus-ipse** [ant-design/ant-design#30734]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kzeql?file=/index.js)

### Steps to reproduce
Add a Collapse with expandIconPosition prop set to right  `<Collapse expandIconPosition="right">`

### What is expected?
That the expand icons is positioned to the right

### What is actually happening?
It is positioned to the left

### Additional info
I think it was this PR that introduced the bug https://github.com/ant-design/ant-design/pull/30586/files

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | react 17.0.2 |
| System | MacOS |
| Browser | Chrome Version 90.0.4430.93 (Official Build) (x86_64) |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/30680
