### ISSUE TITLE
4.15.6与4.16.0 Menu组件点击事件e返回的 keyPath数组索引1，2 位置错位

### ISSUE THREAD

**Issue by 18730237578** [ant-design/ant-design#30733]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/neiqiancaidan-antd4160-forked-lndlc?file=/index.js)

### Steps to reproduce
分别打开两个版本的Menu组件，触发点击事件后，会发现两个版本的keyPath索引1和2的位置是完全相反的，这在项目部署时会出现一些列的问题

### What is expected?
keyPath数组索引位置保持一致即可

### What is actually happening?
两个版本的keyPath索引1和2的位置是完全相反的

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 16.4.0 |
| System | Windows 10 |
| Browser | Chrome 90.0.4430.212 |

**Comment by pgsteven** [comment]
same issue, 4.16.0 Menu component is totally broken

**Comment by pgsteven** [comment]
In addition to this issue:

In v4.16.0 if you place custom element other than <Menu.Item> or <Menu.SubMenu>, e.g. <div>
It will be rendered duplicated among the <Menu>

example code:
```js
<Menu>
    <img src="logo.omg">
    <Menu.Item>test</Menu.Item>
</Menu>
```

Actual output:
```html
<ul>
   <img>
   <li>
</ul>
<img>
```

**Comment by zombieJ** [comment]
Do not use invalidate component in Menu:
```tsx
<div>
  <img src="logo.omg" />
  <Menu>
    <Menu.Item>test</Menu.Item>
  </Menu>
</div>

// or

<Menu>
     <Menu.Item>
      <img src="logo.omg">
    </Menu.Item>
    <Menu.Item>test</Menu.Item>
</Menu>
```
