### ISSUE TITLE
<Breadcrumb.Separator /> can't be customized when creating a component on top of <Breadcrumb.Item />

### ISSUE THREAD

**Issue by artrn-nt** [ant-design/ant-design#30743]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd4160-forked-4j6rr?file=/index.js)

### Steps to reproduce
Open the link, script runs to show the problem.

### What is expected?
Hello * Cherry * House * Tree

### What is actually happening?
Hello / * Cherry / * House / * Tree / *

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.2 |
| System | macOS |
| Browser | Chrome Version 90.0.4430.212 |

---
Saw this in the documentation: "When using Breadcrumb.Separator,its parent component must be set to separator="", otherwise the default separator of the parent component will appear." 

But it has no effect.

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/4853
