### ISSUE TITLE
Modal visible document.body scrollLacker not working

### ISSUE THREAD

**Issue by WeiRu1016** [ant-design/ant-design#30749]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-wing-qyc8e?file=/src/App.js)

### Steps to reproduce
click button, modal visible, body can scroll

### What is expected?
modal visible, body can't scroll

### What is actually happening?
modal visible, body can scroll

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 17.0.2 |
| System | Mac |
| Browser | chrome 91 |

**Comment by huntdream** [comment]
Try updating to latest version
