### ISSUE TITLE
[Table] Table width render different under Chrome 90 and Chrome 91

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#30755]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/green-sunset-hity9)

### Steps to reproduce
- Set wrapper div attribute `max-width` and `overflow`: `hidden`
- Set columns width
- Visit under Chrome 90
- Visit under Chorme 91

### What is expected?
Same result

### What is actually happening?

![AA3BF3F3-91A0-4A20-B804-C1ED56821B93](https://user-images.githubusercontent.com/29817353/119976373-969ba500-bfe9-11eb-8bb2-f6030107026a.png)

Chrome 90

![90p](https://user-images.githubusercontent.com/29817353/119950288-49a9d580-bfcd-11eb-8c81-a001e3b1e082.jpg)
![90](https://user-images.githubusercontent.com/29817353/119950328-52021080-bfcd-11eb-868c-2a53cb0a3be6.gif)

Chrome 91

![91p](https://user-images.githubusercontent.com/29817353/119950405-634b1d00-bfcd-11eb-98fc-22ecea954609.jpg)
![91](https://user-images.githubusercontent.com/29817353/119950385-5e866900-bfcd-11eb-8bbb-ef90836cca8c.gif)

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | latest |
| System | Mac OS |
| Browser | Chrome 90/91 |

**Comment by flute** [comment]
+1

**Comment by jinmmd** [comment]
I guess it's because chrome 91: <COL><COLGROUP> supports min-width.
before 91 version, colgroup min-width is not effect, I suggest you can set a shorter col width.

**Comment by itibbers** [comment]
+1, this global css may temporarily solve the problem.

```css
colgroup {
  display: table-column;
}
```

**Comment by hunter2009** [comment]
More detail in this issue: [https://bugs.chromium.org/p/chromium/issues/detail?id=1214190&q=table%20width&can=2](https://bugs.chromium.org/p/chromium/issues/detail?id=1214190&q=table%20width&can=2)
> This is what standards had to say:

> 1) Originally, in CSS2 standard, 'min-width' for COL elements was 
> explicitly undefined in CSS2 standard.

> "In CSS 2, the effect of min-width and max-width on tables, inline tables, table cells, table columns, and column groups is > undefined."
> https://drafts.csswg.org/css2/#propdef-min-width

> 2) Later, in CSS Box Sizing v3, 'min-width' was defined for all elements.

> "Applies to: all elements that accept width or height"
> https://drafts.csswg.org/css-sizing-3/#min-size-properties

**Comment by atotic** [comment]
I am the Chrome developer that implemented the new tables. This is the problem I saw reported:
```
 <Table
  columns={ [
   {...
     width: 200
   } ] }
```

generates following CSS:
```
<col style="width: 200px; min-width: 200px;">
```
The problem is `min-width` CSS property. 
Before Chrome 91, min-width was ignored on `COL` elements. 91 no longer ignores it.

Is there a reason why  framework is generating both width and min-width CSS properties?
Can you fix it so it only generates width?

Until this is fixed, this global CSS will force Chrome 91 to ignore min-width on table columns:
```css
colgroup { min-width: auto !important;}
col { min-width: auto !important; }
```

I think the fix suggested above is incorrect. It makes `COLGROUP` behave as if it was a `COL`
```
colgroup {
  display: table-column;
}
```

**Comment by zombieJ** [comment]
Let me check if we could remove `min-width`.

**Comment by zombieJ** [comment]
Seems `min-width` is design to force column get configured width. But this code never work as expect, let's remove it first.

**Comment by zombieJ** [comment]
`+ rc-table@7.15.2`

**Comment by smithyj** [comment]
这个Bug是我反馈给Chrome的😂

**Comment by vclau-1996** [comment]
+1
