### ISSUE TITLE
Collapse expandIconPosition not working anymore

### ISSUE THREAD

**Issue by ivolvebe** [ant-design/ant-design#30758]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nuxkq)

### Steps to reproduce
Just pick the basic example from the docs, and add the property expandIconPosition="right". It does not work, while it did in previous versions.

### What is expected?
The expand icon should position on the right side of the pane

### What is actually happening?
The expand icon positions on the left (default) side of the pane

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.2 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
Fixed in #30680
