### ISSUE TITLE
建议tabs可以不使用TabPanel，只使用Tab展示导航

### ISSUE THREAD

**Issue by miaojinsing** [ant-design/ant-design#30759]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
每次强求带panel 很多场景是仅需要Tab 导航展示而已，希望采纳 ， 不要说用菜单 因为中意tab 轻量 动画更满意

### What does the proposed API look like?
当TabPanel不存在children 不渲染 panel

**Comment by yoyo837** [comment]
可以留空的方式来做，如果还有缝隙，再加点样式

**Comment by zombieJ** [comment]
见 @yoyo837  回复，TabPane 不填内容就行了。

**Comment by miaojinsing** [comment]
能别这样敷衍吗？不是第一天使用antd 不填内容都是要渲染tabPanel  每次都要修改样式

**Comment by miaojinsing** [comment]
> 见 @yoyo837 回复，TabPane 不填内容就行了。

能别这样敷衍吗？不是第一天使用antd 不填内容都是要渲染tabPanel 每次都要修改样式

**Comment by yoyo837** [comment]
> > 见 @yoyo837 回复，TabPane 不填内容就行了。
> 
> 能别这样敷衍吗？不是第一天使用antd 不填内容都是要渲染tabPanel 每次都要修改样式

没明白你的意思，问题是什么？

**Comment by yoyo837** [comment]
我的回复可能没有解决你的问题，但我是很认真抽时间来答复你的，按我对你issue的描述我认为我的回答没有问题，你要说是敷衍，那就是敷衍吧！
