### ISSUE TITLE
DatePicker 弹框位置错误

### ISSUE THREAD

**Issue by YaoKaiPeng** [ant-design/ant-design#30756]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-curie-om1sq?file=/src/App.js:317-327)

### Steps to reproduce
点击选择日期，发现日期确定按钮超出屏幕，滚动页面，触发Affix效果，日期选择框依然被挡

### What is expected?
日期选择框可以根据屏幕显示位置来自动呈现位置

### What is actually happening?
目前的日期选择框是根据页面高度来处理位置的，当页面底部有滚动条时，日期框会一直是从下方弹出。

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in antd 5.x: https://codesandbox.io/s/vigilant-pine-lbbifx?file=/package.json

<img width="1784" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/3fd9088d-c768-4602-9c0f-00053ee2d7d0">
