### ISSUE TITLE
Form表单，React hooks 组件，initialValues初始化数据时候，第二次、第三次……传递新值，表单没有更新，永远显示第一次数据

### ISSUE THREAD

**Issue by Venn532010** [ant-design/ant-design#30762]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
1、详情表单， 通过Form.useForm对表单数据域进行交互 <Form form={form} initialValues={data} >；  
2、查看数据详情，点击查看弹出一个表单，正确显示数据；  
3、点击另外一条数据传参过去，接参显示正确，表单显示永远是第一次取到的数据；

### What is expected?
每次点击查看，应当正确显示传过去的数据

### What is actually happening?
每次点击查看，表单显示永远是第一次传过去的数据；

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | react |
| System | win10 |
| Browser | chrome91 |

---
普通的列表，查看详情

**Comment by zombieJ** [comment]
> 注意 initialValues 不能被 setState 动态更新，你需要用 setFieldsValue 来更新。

ref https://ant.design/components/form-cn

**Comment by Venn532010** [comment]
阿里内部有验证过？有做过真实的增删改查？

**Comment by babizhu** [comment]
> > 注意 initialValues 不能被 setState 动态更新，你需要用 setFieldsValue 来更新。
> 
> ref https://ant.design/components/form-cn

这个没法用啊，测试过吗

**Comment by yoyo837** [comment]
initialValues 只有首次有效，就是这样设计的

**Comment by yoyo837** [comment]
可以上个demo看看，或许互相理解有偏差。

**Comment by Venn532010** [comment]
已经解决了，在hooks里面使用，不能用 initialValues 绑定，
可以在 useEffect 里面form.setFieldsValue(data) 赋值，
如果还显示上一个的值，可以先清除再赋值 form.resetFields()

**Comment by Chasen-Zhang** [comment]
这设计真够挫的

**Comment by NicolaCage** [comment]
估计拿结果走了
