### ISSUE TITLE
是否可以考虑将组件的interface全部导出？

### ISSUE THREAD

**Issue by qqabcv520** [ant-design/ant-design#30765]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

类似 issue #30711

### What problem does this feature solve?
在使用typescript的项目中，当需要定义一个复杂的props或者回调函数时，如果不能获取到组件props中的对应类型，只能使用any代替，这会大大降低ts的使用体验。是否可以考虑将组件的interface全部导出？

### What does the proposed API look like?
比如：

components/upload/index.tsx
```
export * from './interface';
```
components/index.tsx
```
export * from './upload';
export { default as Upload } from './upload';
```

使用时：
```
import { Upload, UploadChangeParam, UploadFile } from 'antd'

const onChange = (info: UploadChangeParam) => {
  // TODO
}

const onDownload = (file: UploadFile) => {
  // TODO
}

<Upload onChange={onChange} onDownload={onDownload}/>
```

**Comment by afc163** [comment]
可以从 `antd/lib/upload` 中导出使用。
