### ISSUE TITLE
Table scroll property triggers non-passive event listener to a scroll-blocking 'wheel' event warning 

### ISSUE THREAD

**Issue by Leafgard** [ant-design/ant-design#30764]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-440th)

### Steps to reproduce
1. Create a sample table
2. Pass Y scroll options to the table
3. Open F12 and see the Violation warning

Please open your own browser developer tools (F12) to see the error, it isn't displayed on codesandbox.io directly !

### What is expected?
No warning should be displayed.

### What is actually happening?
The following warning is displayed:

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Electron 12.0.0 (Chromium) |

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/120092813-a1b91700-c148-11eb-8e50-6b33357e9099.png">

I can't reproduce it on Mac Chrome `91.0.4472.77`
`

**Comment by Leafgard** [comment]
@afc163 As I said, for no reason the error is ONLY displayed when opening your host developer tools by pressing F12.

Try it with and without, you will see !

**Comment by alienzhangyw** [comment]
Similar messages are shown when using List or Tabs.
I tried to use [default-passive-events](https://github.com/zzarcon/default-passive-events) to prevent these warnings, but it sometimes would cause other errors as described in the [Q&A](https://github.com/zzarcon/default-passive-events#qa).

**Comment by Leafgard** [comment]
> Similar messages are shown when using List or Tabs.
> I tried to use [default-passive-events](https://github.com/zzarcon/default-passive-events) to prevent these warnings, but it sometimes would cause other errors as described in the [Q&A](https://github.com/zzarcon/default-passive-events#qa).

Does it mean this should be considered as a wont-fix issue ?

**Comment by alienzhangyw** [comment]
> > Similar messages are shown when using List or Tabs.
> > I tried to use [default-passive-events](https://github.com/zzarcon/default-passive-events) to prevent these warnings, but it sometimes would cause other errors as described in the [Q&A](https://github.com/zzarcon/default-passive-events#qa).
> 
> Does it mean this should be considered as a wont-fix issue ?

I'd like it been fixed since there would be dozens of warning messages after many scrolls on page.

**Comment by Leafgard** [comment]
Yeah that's the exact point of my issue. Whenever I come back on the page containing this list, exceptions are throwing on me.
I think you don't need reproduction case anymore now, right ?

**Comment by mayrsascha** [comment]
I don't think this should be closed, I am still getting a big warning on my Chrome Lighthouse score because of this.

**Comment by gregor-mueller** [comment]
I just created an issue on `rc-table` as it needs to be fixed there:

https://github.com/react-component/table/issues/996

**Comment by monolithed** [comment]
The fix is available, but package.json hasn't been updated yet
