### ISSUE TITLE
v4.16.1 Menu的改动，由于改了class name,使下拉中是a标签的都变成@primery-color

### ISSUE THREAD

**Issue by luokebi** [ant-design/ant-design#30786]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown-cn/](https://ant.design/components/dropdown-cn/)

### Steps to reproduce
点开dropdown

### What is expected?
颜色应该是@text-color

### What is actually happening?
颜色是@primary-color

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | v16.14 |
| System | macos |
| Browser | chrome 91 |

**Comment by xrkffgg** [comment]
4.16.1 多了一层 ant-dropdown-menu-title-content 的 span 

样式不起作用了
https://github.com/ant-design/ant-design/blob/133bf530aafb855324a6459145f1d06f47431a87/components/dropdown/style/index.less#L183
