### ISSUE TITLE
官网加个移动链接

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#3079]
加个 tab 跳到： http://mobile.ant.design

**Comment by benjycui** [comment]
设计那边会先事理已有文档的结构，会腾出显眼的位置放 Ant Design Mobile 的链接 cc @Chinglik

**Comment by yiminghe** [comment]
这个是解决了么

**Comment by paranoidjk** [comment]
这个好像还没加，@benjycui  可以加了，英文版主页已经有了，虽然内容还未完全翻译完

**Comment by benjycui** [comment]
在等设计那边调整。。之前说过是把 pattern 下掉，然后在 header 里面加链接。

其实 footer 的链接已经有了，只是不明显而已。
