### ISSUE TITLE
Typography ellipsis should support view less

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#30795]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently Typography component only supports expand button with ellipsis but on clicking expand there is no option to go back to compressed state.

### What does the proposed API look like?

![Screen Recording 2021-05-31 at 6 33 19 PM (1)](https://user-images.githubusercontent.com/41179062/120198704-086d2c00-c240-11eb-94db-07fc387bddaa.gif)

**Comment by zombieJ** [comment]
Since it's not match our design. It may not support currently. You can use `suffix` for HOC.
