### ISSUE TITLE
Ellipsis doesn't work 

### ISSUE THREAD

**Issue by endophasie** [ant-design/ant-design#30797]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-eh8o7)

### Steps to reproduce
The text does not truncate

### What is expected?
The text has to be truncated

### What is actually happening?
The text does not truncate

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 17.0.2 |
| System | MacOS Big Sur 11.2.3 |
| Browser | Google Chrome 90.0.4430.212 (Official Build) (x86_64) |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/30777

**Comment by zombieJ** [comment]
Link is `display: inline`. You need set the `width`: https://codesandbox.io/s/antd-reproduction-template-forked-kfg4t?file=/index.js
