### ISSUE TITLE
table 未设置fixed 存在留白

### ISSUE THREAD

**Issue by yzy2857895027** [ant-design/ant-design#30805]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
一列不设置width，其中两列受变量控制通过classname改变使其display:none

### What is expected?
正常平铺，无留白

### What is actually happening?
table留白

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | react |
| System | macOS Big Sur 11.0 Beta版 |
| Browser | Chrome  91.0.4472.77 |

**Comment by yoyo837** [comment]
使用state 管理columns,而不是直接使用css让其隐藏。
