### ISSUE TITLE
Message OnClick Functioning Incorrectly

### ISSUE THREAD

**Issue by crimsonpython24** [ant-design/ant-design#30800]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-style-antd4161-forked-umj3y?file=/index.js)

### Steps to reproduce
The code is already provided in the sandbox above. Simply add an "onClick" configuration to the message, as in line 14 of the demo.

Codesandbox 示範裏面已經有程式碼了，其中出問題的是第 14 行。

### What is expected?
Whenever I click the message, the console logs "hi".

當我點擊 message 的時候，console 要印出 "hi".

### What is actually happening?
Console logs "hi" only on the trigger of the message. When I clicked the message, nothing happened.

只有我在點擊觸動 message 按鈕的時候，console 才會 log。當我點 message 本身的時候，沒有事發生。

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | React 16.14.0 |
| System | CodeSandbox |
| Browser | Microsoft Edge 91.0.864.37 (Official build) (64-bit) |

---
The message trigger (aka the "Customized Style" button) should not log anything. Stressing here that I'd like the console to print "hi" when I click on the "This is a prompt message with custom className and style" message.

觸動按鈕（"Customized Style"）不應該印任何東西，但是 "This is a prompt message..." 的 message 要。

**Comment by Pzx1997** [comment]
onClick is a function type , Please make it a function

**Comment by Pzx1997** [comment]
onClick is a function type , Please make it a function

**Comment by crimsonpython24** [comment]
is console.log not counted as a function?

**Comment by Pzx1997** [comment]
https://codesandbox.io/s/customized-style-antd4161-forked-umj3y?file=/index.js

**Comment by Pzx1997** [comment]
https://codesandbox.io/s/customized-style-antd4161-forked-c1grn?file=/index.js

**Comment by Pzx1997** [comment]
If you want to know why, you might want to look at the source code

**Comment by crimsonpython24** [comment]
As a side question, are there animation properties for `message.destroy()`?

**Comment by afc163** [comment]
```diff
- onClick: console.log("hi")
+ onClick: () => {
+   console.log("hi")
+ }
```
