### ISSUE TITLE
Modal has no exit animation

### ISSUE THREAD

**Issue by crimsonpython24** [ant-design/ant-design#30807]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-yalow-xunfs?file=/src/App.js)

### Steps to reproduce
The code is provided above.

程式碼已在上面提供。

### What is expected?
I am expecting something from [the other sandbox](https://codesandbox.io/s/form-in-modal-to-create-antd4161-forked-lvm5q?file=/index.js), where there is clearly an exit animation when you click on the cancel, proceed, "X", and anywhere around the modal.

我想要（上面有鏈接）的退出效果：當你按到任何一個退出 modal 的部件的時候，會有一個退出的效果。

### What is actually happening?
In the minimal reproduction, however, the exit animation was not evident. When I clicked any of the four places, the modal just disappears without transition.

在 reproduction 裏面，這個效果并沒有出現：點開 modal 的時候會 fade 進來，但是點出 modal 的時候并沒有特效。

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 17.0.2 |
| System | Codesandbox |
| Browser | Microsoft Edge 91.0.864.37 (Official build) (64-bit) |

**Comment by afc163** [comment]
CollectionCreateForm will recreate every time when Profile rerender in your codesandbox.

See https://codesandbox.io/s/condescending-haibt-eqef5?file=/src/App.js
