### ISSUE TITLE
希望官网文档增加一个搜索快捷键，类 cmd K这种

### ISSUE THREAD

**Issue by WLyKan** [ant-design/ant-design#30812]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
随着框架的完善，内容丰富，很多地方需要查询，有的页面很长，要滚动好久才能找到对应组件。希望可以提供一个呼出快捷搜索框的功能。

### What does the proposed API look like?
希望官网文档增加一个搜索快捷键，类 cmd K这种。具体情况，可以看redux[官网这种形式](https://redux.js.org/faq/general#when-should-i-use-redux)

**Comment by WLyKan** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 随着框架的完善，内容丰富，很多地方需要查询，有的页面很长，要滚动好久才能找到对应组件。希望可以提供一个呼出快捷搜索框的功能。
> 
> ### What does the proposed API look like?
> 希望官网文档增加一个搜索快捷键，类 cmd K这种。具体情况，可以看redux[官网这种形式](https://redux.js.org/faq/general#when-should-i-use-redux)

redux官网的右上角搜索框，可以用 cmd + K 唤出

**Comment by vagusX** [comment]
https://ant.design/components/overview-cn/ 这里的搜索能满足你的需求不？

**Comment by afc163** [comment]
谁有兴趣来个 PR？

**Comment by vagusX** [comment]
我

**Comment by vagusX** [comment]
me

**Comment by vagusX** [comment]
计划将目前的搜索框：
* 增加一个快捷键绑定及对应文案提示
* 将顶部搜索框做成一个 modal 弹出的效果，类似 Docusaurus  search-algolia

![image](https://user-images.githubusercontent.com/6828924/120753821-52a32580-c53e-11eb-9d8e-f4ec75d37008.png)

![image](https://user-images.githubusercontent.com/6828924/120753866-677fb900-c53e-11eb-8524-25e466d307a8.png)

**Comment by vagusX** [comment]
Maybe you can try this preview site https://github.com/ant-design/ant-design/pull/30942#issuecomment-857828792 @WLyKan
