### ISSUE TITLE
menu水平状态下溢出显示不正确

### ISSUE THREAD

**Issue by wsz7777** [ant-design/ant-design#30819]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudingtoubu-antd4161-forked-1np9v?file=/index.js)

### Steps to reproduce
上述链接直接可见

### What is expected?
显示在一行，不会折行

### What is actually happening?
显示两行

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | >=16.12.0 |
| System | mac 10.15 |
| Browser | chrome 90 |

**Comment by wsz7777** [comment]
还有一些宽度计算问题：
1. 如果给item设置了margin，也会折行。这种情况是开放api进行设置呢还是不计划支持？
2. 计算最后空间的时候请把 "···" 的这一块宽度也计算在内。不然的话是有问题的

**Comment by zombieJ** [comment]
Menu 水平漏了一个 `display: flex`，我加一下~

1. 测验 margin 性能消耗略多，不准备支持。
2. 本来就计算的，这里的问题是 logo `float` 把空间占掉了。

**Comment by shanlan-L** [comment]
> Menu 水平漏了一个 `display: flex`，我加一下~
> 
> 1. 测验 margin 性能消耗略多，不准备支持。
> 2. 本来就计算的，这里的问题是 logo `float` 把空间占掉了。

当前 antd 5.16.0 还不支持 margin，请问后续有计划支持吗？
