### ISSUE TITLE
Modal Component- change size over the full space of the browser window

### ISSUE THREAD

**Issue by RoniFinTech** [ant-design/ant-design#30818]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal/](https://ant.design/components/modal/)

### Steps to reproduce
```
<Modal
                title={data.posts_by_pk.title}
                // centered
                visible={visible}
                onOk={() => setVisible(false)}
                onCancel={() => setVisible(false)}
                afterClose={() => history.goBack()}
                // width={100000}
                style={{
                    // maxWidth: '100%',
                    // margin: 0,
                    // marginLeft: 0,
                    // overflow: 'hidden',
                    top: 0,
                    bottom: 0,
                    left: 0,
                    right: 0,
                    // width:'100%',
                    // height: '100%',
                    // height: '100vh',
                    // width: '100vh',
                    // display: 'flex',
                    position: 'fixed'
                }}
            >
                <p>{data.posts_by_pk.id}</p>
            </Modal>
```

This is my Modal component and I'm trying to get it to be over the full space of the beowser window (a good example is how modals work on Facebook).
But it won't work with any of the combination of styles shown above.

### What is expected?
the model to be the full size of the Chrome page size.

### What is actually happening?
model size won't change

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0 |
| System | Windows 10 |
| Browser | Chrome Version 90.0.4430.212 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Try `wrapClassName`
