### ISSUE TITLE
DatePicker will reopen when click none input area

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#30810]
<img width="634" alt="截屏2021-06-01 下午7 51 03" src="https://user-images.githubusercontent.com/507615/120318827-e55f7c80-c312-11eb-960b-41df3dc243f5.png">

1. Open DatePicker
2. Click these areas
3. DatePicker panel will reopen and flush

**Comment by Akashdeep98** [comment]
Hey @afc163 I have fixed this issue here is the PR:
https://github.com/ant-design/ant-design/issues/30810
There was a minor change we were missing `containerRef.current` while detecting click outside.
`
isClickOutside: (target: EventTarget | null) =>
      !elementsContains(
        [
          panelDivRef.current,
          startInputDivRef.current,
          endInputDivRef.current,
          containerRef.current,
        ],
        target as HTMLElement,
      ),
`
