### ISSUE TITLE
Image 图片底部空白

### ISSUE THREAD

**Issue by meijuji202** [ant-design/ant-design#30825]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-yhw2r?file=/index.js)

### Steps to reproduce
如莲见，将Image放入Card ，Image的底边与Card的底边有几像素的空

### What is expected?
去掉Image的底边空白

| Environment | Info |
|---|---|
| antd | undefined |
| React | All |
| System | All |
| Browser | All |

**Comment by shaodahong** [comment]
> @shaodahong `ant-image-img` 可以换`inline-block`么？🤔

貌似可以

**Comment by afc163** [comment]
来个 PR
