### ISSUE TITLE
用空标签包裹SubMenu或者Menu.item的时候，功能和样式全错乱了

### ISSUE THREAD

**Issue by XingXiaoWu** [ant-design/ant-design#30828]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/xingxiaowu/pen/YzZeWJN?editors=0011](https://codepen.io/xingxiaowu/pen/YzZeWJN?editors=0011)

### Steps to reproduce
用空标签包裹SubMenu或者Menu.item的时候，一切正常
当抽出一个组件来包裹SubMenu或者Menu.item的时候，样式和功能就全不对了

### What is expected?
当使用组件包裹SubMenu或者Menu.item的时候，样式和功能正常

### What is actually happening?
当使用组件包裹SubMenu或者Menu.item的时候，样式和功能不正常

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 17.0.2 |
| System | macos 11.3.1 (20E241) |
| Browser | Edge 11.3.1 (20E241) |

**Comment by yoyo837** [comment]
好像新的menu现在不支持包裹了，前面有印象有个issue,一时半会没找到

**Comment by XingXiaoWu** [comment]
> 好像新的menu现在不支持包裹了，前面有印象有个issue,一时半会没找到

这个很离谱啊，就算不允许包裹，我实际上是个空标签，本质在dom中不会渲染，这也能出问题。

而且不给包裹这还怎么做去中心化的路由鉴权。。。

**Comment by yoyo837** [comment]
没权限的不应该直接不要出现吗？之前没有用这个特征，一样能做到鉴权。 

回到主题的问题，我不太确定, 我还没升上来。

**Comment by yoyo837** [comment]
你可能需要重新适配新版本。

**Comment by XingXiaoWu** [comment]
> 你可能需要重新适配新版本。

我更倾向于这是个bug。。不给嵌套，这很不自由

**Comment by kerm1it** [comment]
ref: https://github.com/ant-design/ant-design/issues/4853

Menu 之前一直都不支持自定义 HOC 嵌套，Fragment 是专门做了处理过滤。

可以先尝试使用 renderProps 解决

**Comment by XingXiaoWu** [comment]
> ref: #4853
> 
> Menu 之前一直都不支持自定义 HOC 嵌套，Fragment 是专门做了处理过滤。
> 
> 可以先尝试使用 renderProps 解决

了解，但是点开我的复现链接看一下，我嵌套的也是Fragment，还是说你们甚至不允许Fragment单独抽离

**Comment by XingXiaoWu** [comment]
实际上我就是在做类似这样的操作
https://github.com/ant-design/ant-design/issues/4853#issuecomment-623412543

**Comment by kerm1it** [comment]
``` jsx
<>
  <Menu.Item key="1" icon={<PieChartOutlined />}>
    Option 1
  </Menu.Item>
</>
```

直接在 Menu 下面这样使用是被允许的，因为读取 Menu 的 子元素的时候会过滤掉 Fragment

``` jsx
<Tmp>
  <Menu.Item key="2" icon={<DesktopOutlined />}>
    Option 2
  </Menu.Item>
</Tmp>
```

但是这样是不被允许的，尽管 Tmp 组件里面是 Fragment （它属于 Tmp 的子元素），目前并没有去读取 Tmp 的子元素中的 `Menu.Item` 或 `Menu.SubMenu`，只会把它当作是 `Menu.Item` 或 `Menu.SubMenu`，就会出错。

**Comment by XingXiaoWu** [comment]
好的吧，只好在Menu里直接做判断了

**Comment by hengkx** [comment]
我记得 这个 @zombieJ 是不是 处理了
![image](https://user-images.githubusercontent.com/8358236/120597492-b7477d00-c477-11eb-8f6c-8f9fb1dc8bb7.png)

**Comment by zombieJ** [comment]
这个和测量没啥关系，过去版本本来就不支持 HOC，新版反而是支持的。你需要的就是把 `key` 换成 `eventKey`：
* 4.15.x: https://codesandbox.io/s/neiqiancaidan-antd4161-forked-w1lm1?file=/index.js
* 4.16.x: https://codesandbox.io/s/neiqiancaidan-antd4161-forked-17fgo?file=/index.js

**Comment by XingXiaoWu** [comment]
> 这个和测量没啥关系，过去版本本来就不支持 HOC，新版反而是支持的。你需要的就是把 `key` 换成 `eventKey`：
> 
> * 4.15.x: https://codesandbox.io/s/neiqiancaidan-antd4161-forked-w1lm1?file=/index.js
> * 4.16.x: https://codesandbox.io/s/neiqiancaidan-antd4161-forked-17fgo?file=/index.js
> 
> ref https://zhuanlan.zhihu.com/p/373180973

了解，Thx
