### ISSUE TITLE
tree 组件 loadData，若当前层级是全选状态，那么被加载的新层级会默认展开，并且被默认选中，但未触发oncheck事件。

### ISSUE THREAD

**Issue by jimmyrogue** [ant-design/ant-design#30827]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-g7gxn?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1、展开root
2、依次选中123的checkbox，触发3次 oncheck。
3、任意展开其中一个
4、触发loadData
5、新增的元素被选中，但未触发oncheck

### What is expected?
希望新增的被选中的元素也能触发oncheck

### What is actually happening?
没有触发oncheck，导致最后被选中的数据并不完整

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | macOS 11.2.3 |
| Browser | chrome 90 |

**Comment by imhxc** [comment]
其实我觉得正确的业务处理逻辑应该是通过监听父级节点是否选中，如果父级节点选中了，那么子节点肯定就是选中的；如果子节点点击触发了 oncheck ，那么就可以相应的去处理当前节点的选中状态。

如果说勾选父节点的时候，子节点也触发 oncheck，这个显然无论从性能、还是一致性上都不太合理。

**Comment by jimmyrogue** [comment]
@imhxc 感谢解答
