### ISSUE TITLE
Table 组件 rowSpan 传 '0' 时未正常渲染

### ISSUE THREAD

**Issue by xdyushenli** [ant-design/ant-design#30831]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaogexingliehebing-antd4161-forked-y0qjc)

### Steps to reproduce
第一行的 rowSpan 设为 2，第二行的 rowSpan 设置为 '0'，即可看到问题

### What is expected?
rowSpan 设为为 '0' 的格子不要展示出来

### What is actually happening?
rowSpan 设为为 '0' 的格子展示出来了，并将后面的内容都向后挤了一格

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 17.0.2 |
| System | ios |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/biaogexingliehebing-antd4161-forked-qwkrj
