### ISSUE TITLE
Have block as a prop for Skeleton Button

### ISSUE THREAD

**Issue by aashayamballi** [ant-design/ant-design#30832]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In the loading screen, I want to display a loading block button. for example, if I have a column that takes 5 span space and if there is a button inside it then I want to take the full space of the column. Currently, there is no prop that I can define for it nor there is a style prop where I can specify the width as 100%

Even if I can define width as 100% then the loading button skeleton is not being shown inside a Col

### What does the proposed API look like?
<Skeleton.Button active={true} shape="round" block />

**Comment by wwyx778** [comment]
我来完成这个。

**Comment by wwyx778** [comment]
有个 .less 文件的写法是：
```
@keyframes ~"@{skeleton-prefix-cls}-loading" {
    ...
}
```
文件报语法错误并且无法通过 commit，我应该怎么处理？@afc163 

File：https://github.com/ant-design/ant-design/blob/master/components/skeleton/style/index.less

**Comment by afc163** [comment]
报什么错？

**Comment by wwyx778** [comment]
> 报什么错？

![image](https://user-images.githubusercontent.com/28632663/120784837-19c77880-c55f-11eb-9c5d-ac931620d8d7.png)
![image](https://user-images.githubusercontent.com/28632663/120784960-36fc4700-c55f-11eb-81c8-6d9fdc139633.png)

**Comment by wwyx778** [comment]
@afc163

**Comment by afc163** [comment]
```
rm -rf node_modules package-lock.json yarn.lock
npm install
```
