### ISSUE TITLE
Custom Icon for finished step at Steps component.

### ISSUE THREAD

**Issue by chuikoffru** [ant-design/ant-design#30830]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hello! I'd like to change default icon for the finished step in the Steps component.

### What does the proposed API look like?
<Steps finishIcon={<LikeOutlined />}>
  <Step title={1} status="finish" />
  <Step title={2} status="process" />
</Steps>

**Comment by afc163** [comment]
`icons={{ finish: ReactNode }}`
