### ISSUE TITLE
<Table /> 分页后，如何自动滚动到顶部？

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#3084]
如题，比如我在第 1 页将滚动条滚动到中间位置，那么我在点击第 2 页后，如何将滚动条自动回到顶部？
[点击查看demo](http://codepen.io/ystarlongzi/pen/ORRdZK)

**Comment by benjycui** [comment]
在翻页事件里面使用 https://github.com/yiminghe/dom-scroll-into-view

**Comment by ystarlongzi** [comment]
@benjycui 谢谢！

不过在切换页码、切换每页显示条数后，<Tbale /> 组件自身滚动到顶部，这样是否更加友好些？

**Comment by benjycui** [comment]
组件无法知道顶部在哪里，因为业务里面可能在 Table 上面加了按钮，按理解那也可以是顶部。
