### ISSUE TITLE
当Tree设置display:none时, 修改expandedKeys失效问题

### ISSUE THREAD

**Issue by progerchai** [ant-design/ant-design#30843]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-liskov-3ve10?file=/index.js:2280-2292)

### Steps to reproduce
1. 点击`Display树`按钮,会给Tree组件包一层display:none
2. 点击`展开0-1`按钮,修改state中的expandedKeys
3. 点击`恢复树`,将Tree组件的display:none 再恢复为block

### What is expected?
点击`恢复树`按钮后, `0-1` 树节点 可以展开

### What is actually happening?
点击`恢复树`按钮后,在state.expandedKeys 数据发生变化时,左侧箭头有发生变化,但是`0-1`树节点并未展开
如图效果:
![20210603204543.png](https://i.loli.net/2021/06/03/eTS2EMjh6K1cYVk.png)

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome |

---
测试过,在antd@3.2.3版本中,并没有这个问题,即使display:none , expandedKeys数据发生变化后恢复display依旧可以展开树,以达到目的

**Comment by progerchai** [comment]
项目中无法对antd从3.x升级到4.x ,所以这里考虑了两种解决方案代替:
1. 在使用到的地方安装一个低版本的antd 
2. 或者将display:none. 修改为visibility:hidden

**Comment by yoyo837** [comment]
升级的时候需要重新适配上游很正常的，适配一下就好了，项目其他原因不能升级的话，那就不会有这个问题。所以，你这不是问题吧？

**Comment by progerchai** [comment]
> 升级的时候需要重新适配上游很正常的，适配一下就好了，项目其他原因不能升级的话，那就不会有这个问题。所以，你这不是问题吧？

嗯嗯 , 只是单纯不会因为这个小问题去做大版本的升级,不是不升级就顶不住的情况

不过还是希望能有3.x版本对这个问题有一定的优化

**Comment by yoyo837** [comment]
目前team已经放弃了3.x的任何问题解答和修复。

**Comment by progerchai** [comment]
> 目前team已经放弃了3.x的任何问题解答和修复。

好的 ,感谢回复👌
