### ISSUE TITLE
No animation on message.destroy()

### ISSUE THREAD

**Issue by crimsonpython24** [ant-design/ant-design#30845]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/normal-prompt-antd4161-forked-mmqgp?file=/index.js)

### Steps to reproduce
Click on the "display normal message" button. When the message prompts out, click on the message. The message should disappear.

點擊 “display normal message” 按鍵。等到訊息跳出的時候，點在訊息上面。訊息應該會不見。

### What is expected?
When the message exits, it should have a slide-out animation like how it slides in on open.

當訊息跳出的時候，他應該會有一個（像點開的時候）拉進，出的效果
注：我不知道這是我的問題還是沒有這個功能，所以我沒歸類成 feature request

### What is actually happening?
When clicked on the message, it just disappears without transitions.

點到 message 的時候，它消失的時候不會有任何特效。

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | React v16.14.0 |
| System | CodeSandbox |
| Browser | Edge 91.0.864.37 (Official build) (64-bit) |

**Comment by afc163** [comment]
You can close it by `hide` callback: https://codesandbox.io/s/normal-prompt-antd4161-forked-lgejn?file=/index.js

`message.destroy` means that it will destroy a message, not close it.

**Comment by crimsonpython24** [comment]
Just for posterity, the `hide` callback can be provided a message's `key` prop so that messages won't be hidden altogether. [Sandbox](https://codesandbox.io/s/normal-prompt-antd4161-forked-rnhmy?file=/index.js)
