### ISSUE TITLE
input组件输入句号"。" 会连续触发两次onChange事件

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#30846]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4161-forked-l5r8u?file=/index.js)

### Steps to reproduce
1.  input双向受控写法里.   onChange里有正则写法
2. 校验特殊符号会禁止输入
3. 按键句号"。"  触发了两次onChange事件

### What is expected?
输入句号"。"  只触发一次onChange事件

### What is actually happening?
输入句号"。"  触发了两次onChange事件

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  79.0.3945.88 |

---
nput onchange事件里输入按键句号'。' 触发return
onchange事件会触发两次

**Comment by afc163** [comment]
1. 我这里无法重现，只触发了一次
2. 你可以测试一下原生 input https://codesandbox.io/s/jibenshiyong-antd4161-forked-l5r8u?file=/index.js ，如果也是这个表现，则和 antd Input 无关。

**Comment by guiyu1230** [comment]
![image](https://user-images.githubusercontent.com/33077436/120760942-42437880-c547-11eb-9aeb-ec0b187f345f.png)

**Comment by guiyu1230** [comment]
> 1. 我这里无法重现，只触发了一次
> 2. 你可以测试一下原生 input https://codesandbox.io/s/jibenshiyong-antd4161-forked-l5r8u?file=/index.js ，如果也是这个表现，则和 antd Input 无关。

**Comment by guiyu1230** [comment]
如图: 关键是 
1. 输入中文标点句号"。"触发  
2. 执行过程 触发了return

**但是好像在原生input也复现了这个问题. 对于这个问题不知道有什么好的解决办法**

**Comment by afc163** [comment]
如果原生也有这个问题，可能和浏览器版本/浏览器插件/React/输入法相关，我这里无能为力哈。
