### ISSUE TITLE
Select 的选项在 hover 之后离开下拉框，hover 样式还在，试了下3.x版本正常

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#30856]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
hover 一个选项，然后鼠标离开弹出框

### What is expected?
hover 样式消失

### What is actually happening?
hover 样式还在

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
hover样式指的是？

**Comment by xrkffgg** [comment]
那个不是 hover 的样式，有一个 active

**Comment by linxianxi** [comment]
> 那个不是 hover 的样式，有一个 active

active是选中吧。比如现在选中的是1，然后你把鼠标放在2上，然后把鼠标往左或者右移出下拉框，2上面还会有hover的样式。3.x不会，移开就没效果了。

**Comment by xrkffgg** [comment]
目测应该是 设计了

**Comment by linxianxi** [comment]
> 目测应该是 设计了

我一开始也以为就是设计，但是我看3.x不会，就不知道是不是 bug 了。按理说离开了那个区域应该移除交互才对。

**Comment by zombieJ** [comment]
是个设计，激活态总是高亮。v3 的时候其实也有，只是实现有点问题……2333
