### ISSUE TITLE
Drawer抽屉,有没有loading属性,可以把右上角按钮，页脚按钮，都囊括当中

### ISSUE THREAD

**Issue by ztg-zlu** [ant-design/ant-design#30859]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Drawer抽屉,有其他需要等待的返回数据，这时，不能操作，包括右上角关闭，页脚的关闭和确定。等待返回数据，再操作。

### What does the proposed API look like?
Drawer抽屉,有没有loading属性,可以把右上角按钮，页脚按钮，都囊括当中

**Comment by getatny** [comment]
1. closeable 可以控制是否显示关闭按钮；
2. onClose 可以控制关闭按钮点击逻辑；
------------ 以上两个稍微加一点逻辑就能控制在数据没返回之前不能点击 X 
3. Drawer 没有页脚，如果你指的是用 Button 写的确定和取消，这两个按钮都可以通过 disable 控制其是否可点击。

**Comment by afc163** [comment]
目前还不支持，但是感觉可以加个 drawerRender 来支持。

**Comment by afc163** [comment]
@getatny 也是个办法，就是要多写几个地方，可以封装一个自己的 Drawer 出来。

**Comment by afc163** [comment]
```jsx
const MyDrawer = ({ loading, footer, children, ...props }) => {
  return <Drawer {...props} closable={!loading} footer={<Spin spinning={loading}>{footer}</Spin>}><Spin spinning={loading}>{children}</Spin></Drawer>
}
```
