### ISSUE TITLE
Improve demo code style

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#30853]
```js
import xxx from 'xxx';

const Xxx = () => { ... }

ReactDOM.render(<Xxx />, mountNode);
```

to

```js
import xxx from 'xxx';

const Xxx = () => { ... }

export default Xxx;
```

No more `ReactDOM.render`.

**Comment by alwaysloseall** [comment]
需要一次性修改完提交PR还是逐步进行修改

**Comment by yoyo837** [comment]
相对独立的单个工作，在同一个PR内即可。认为是为同一件事而做出的修改，就写一起。

**Comment by afc163** [comment]
逐步修改就行，这是一个大工程，第一步要改 bisheng。

**Comment by afc163** [comment]
先把 class component 都换掉先，还有 115 个 demo。

<img width="359" alt="图片" src="https://user-images.githubusercontent.com/507615/139847370-1547a76a-4371-426c-b9aa-1f68a14a9e87.png">

**Comment by afc163** [comment]
- [ ] 外链打开 demo 上针对 React 18 的支持

**Comment by MadCcc** [comment]
Done
