### ISSUE TITLE
renderTabBar是否可以仅固定第一个tab（点击右键出现下拉菜单），其它标签点击右键出现下拉菜单，tba过多时出现滚动条？

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design#30858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
renderTabBar可以固定第一个（点击右键出现下拉菜单），其它标签点击右键出现下拉菜单，tba过多时出现滚动条

### What does the proposed API look like?
renderTabBar可以固定第一个（点击右键出现下拉菜单），其它标签点击右键出现下拉菜单，tba过多时出现滚动条

**Comment by afc163** [comment]
Duplicate of #18782
