### ISSUE TITLE
Button组件里面嵌套Icon，在火狐下点击Icon会冒泡到Button

### ISSUE THREAD

**Issue by leesx** [ant-design/ant-design#3085]
#### 发生问题的环境是：

<Button>组件里面嵌套了一个Icon组件，把点击事件click绑定到Icon在火狐下不起作用，而会触发button的点击事件，取消冒泡也不起作用。看了渲染出来的代码是button标签里面 嵌套里面了其他标签。我感觉使用button标签，在里面再嵌入其他标签，有些不合适。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by leesx** [comment]
this is a demo  http://codepen.io/leesx/pen/KggLwL?editors=1111

**Comment by leesx** [comment]
//这是我使用其他标签模拟的button
//模拟Button
// ant中的Button组件，有一个bug,不应该直接使用button标签
class MockButton extends Component {
    constructor(props, context) {
        super(props, context)
        this.state = {

        }

    }
    render(){
        const btnClass = this.props.type == 'ghost' ? 'ant-btn-ghost' : 'ant-btn-primary'
        return (
            <span className={`ant-btn ${btnClass}`}  onClick={ this.props.onClick }>
                {this.props.children}
            </span>
        )
    }
}

**Comment by afc163** [comment]
感觉你应该用 http://ant.design/components/tag

Button 是有语义的，内嵌其他可点击元素不合理。

**Comment by leesx** [comment]
Button虽然有语义，但是 <button><span>X</span></button> 这样写感觉很蹩脚de。  我也尝试了Tag 标签，在使用redux的情况下  afterClose方法  总是 先render 后执行anction .导致很诡异的bug .(感觉你Tag内部执行了删除方法，)

**Comment by leesx** [comment]
@Button 是有语义的，内嵌其他可点击元素不合理。   关键是在火狐下有问题。点击里面的，会触发button本身的click。Chrome下就表现的很好

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2970
