### ISSUE TITLE
table 组件 title 设为 0 不能显示出来

### ISSUE THREAD

**Issue by Go7hic** [ant-design/ant-design#30863]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/Go7hic/pen/yLMKREV?editors=001](https://codepen.io/Go7hic/pen/yLMKREV?editors=001)

### Steps to reproduce
直接看 

### What is expected?
title 设为0 ，界面也能正常显示出来

### What is actually happening?
现在就是 title 设为0，界面不会显示

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome |

---
因为我们表头是动态的 有些值是后端返回的 有0 也有空  所以这个0 不显示的话还得前端这边转成字符串形式 '0'

**Comment by wendellhu95** [comment]
Started working on it.

**Comment by wendellhu95** [comment]
https://github.com/react-component/table/blob/3742d4dc074eba33d2783c51ae5ef004908c6f06/src/Cell/index.tsx#L100-L102

Root problem is here/
