### ISSUE TITLE
项目更新了最新版本的antd，使用Table.Summary报错

### ISSUE THREAD

**Issue by CQBoyBrand** [ant-design/ant-design#30860]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is t a duplicate.

### Steps to reproduce
no
![image](https://user-images.githubusercontent.com/20539402/120789210-e804e080-c563-11eb-8a6e-c3bac45fca0d.png)

### What is expected?
不报错

### What is actually happening?
antd.dll.js:95038 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

![image](https://user-images.githubusercontent.com/20539402/120789171-d7ed0100-c563-11eb-8a57-05db0f73a1a5.png)

Check the render method of `Table`.

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 16.13.0 |
| System | MacOS 10.14.6 |
| Browser | Chrome 91 |

**Comment by aLIEzsss4** [comment]
https://codesandbox.io/s/zongjielan-antd4163-forked-2g8y4?file=/index.js
