### ISSUE TITLE
Table 组件的标题头部为何会突然多出分割线，如何去掉

### ISSUE THREAD

**Issue by cyanwin** [ant-design/ant-design#30867]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
即使需要默认显示分割线也希望通过api关闭

### What does the proposed API look like?
{ divider: boolean }

**Comment by afc163** [comment]
设计规范有更新：https://github.com/ant-design/ant-design/pull/30651

**Comment by xingqiwu55555** [comment]
想去掉这个分割线

**Comment by hinego** [comment]
.ant-table-thead >tr>th::before {
  display: none;
}
