### ISSUE TITLE
Table在sticky和固定某些列的情况下，当触发吸顶效果时，会出现双滚动条

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#30868]
<img width="1160" alt="图片" src="https://user-images.githubusercontent.com/4978379/120870312-2bdf0080-c5cb-11eb-95aa-bd606ca2191b.png">
```
<Table
        scroll={{ x: 'max-content' }}
        columns={columns}
        dataSource={data}
        pagination={pagination}
        rowKey="id"
        onChange={onTableChange}
        sticky={{offset:1}}
      />
```

**Comment by letsoon** [comment]
> <img alt="图片" width="1160" src="https://user-images.githubusercontent.com/4978379/120870312-2bdf0080-c5cb-11eb-95aa-bd606ca2191b.png">
> 
> ``` ```

你好，请问你解决了嘛？

**Comment by hbxks18** [comment]
这个问题应该是滚动容器不是默认的window的原因，可以传入getContainer修改滚动容器的元素来解决。
![image](https://user-images.githubusercontent.com/23228604/132441890-b6076e67-5cdb-48dc-96b2-4e887a7f828b.png)

**Comment by hdd1995** [comment]
我是横线滚动条点击就消失？？？

**Comment by chen-jh-github** [comment]
useEffect(() => {
    // 由于表格设置了sticky,所以当表格数据变化时候，会出现双横向滚动条的场景
    // 问题场景：https://github.com/ant-design/ant-design/issues/30868
    document.documentElement.scrollTop += 1;
    document.documentElement.scrollTop -= 1;
  }, [dataSource]);

**Comment by chen-jh-github** [comment]
可以通过监听表格数据变化，触发hook滚动页面解决该问题
  useEffect(() => {
    document.documentElement.scrollTop += 1;
    document.documentElement.scrollTop -= 1;
  }, [dataSource]);

**Comment by Yugle** [comment]
合理设置getContainer()解决该问题
sticky={{getContainer: () => document.getElementById('root') as HTMLElement}}

**Comment by hejinguo** [comment]
> 我是横线滚动条点击就消失？？？

横线滚动条点击消失的问题解决了吗？

**Comment by GalaxySystem** [comment]
> 我是横线滚动条点击就消失？？？

+1

**Comment by PatrickkZhao** [comment]
> 我是横线滚动条点击就消失？？？

我在移除了 `node_modules/rc-table/es/stickyScrollBar.js/onContainerScroll` 中设置 `isHiddenScrollBar` 为 `true` 的一个判断后修复了这个问题。

```
// Line 99
-    if (tableBottomOffset - getScrollBarSize() <= currentClientOffset || tableOffsetTop >= currentClientOffset - offsetScroll) {
+    if (tableOffsetTop >= currentClientOffset - offsetScroll) {
```
并且隐藏了 antd Table 的滚动条。
```
.ant-table-body::-webkit-scrollbar {
    display: none !important;
}
```

**Comment by Y80** [comment]
当 `<Table>` 设置 sticky 属性时，会出现一个 `<div>` 创建的横向滚动条，它有别于 table body 容器内的横向滚动条，`<div>` 创建的滚动条会在 table 滚动到底部时消失，这个时候应该用 table body 的滚动条操作。

上面是**正常的表现**，横向滚动条点一下就消失，大概率是因为 `<Table>` 的容器（或容器的 parentElement）为弹性布局，如 Flex、Grid，同时没有正确设置 `getContainer()` 导致的。

### 🔧 解决方案：
设置正确的 `getContainer()` ，如果不确定是哪一个，可以从 `<Table>` 所在的容器、所在容器的parentElement、parentElement.parentElement 一个个试过去。

[🔗 react-component/table/stickyScrollBar.tsx 相关源码](https://github.com/react-component/table/blob/master/src/stickyScrollBar.tsx)
