### ISSUE TITLE
[InputNumber] defaultValue overrided value property

### ISSUE THREAD

**Issue by sieuvb** [ant-design/ant-design#30873]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nrdxp?file=/index.js)

### Steps to reproduce
Observe the value in the InputNumber component

### What is expected?
The **defaultValue** property should not override **value** property while **value** is presented. The value of InputNumber should be 1.

### What is actually happening?
The value of InputNumber is 0.

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 17.0.2 |
| System | MacOS Mojave 10.14.6 |
| Browser | Chrome 91.0.4472.77 (Official Build) (x86_64) |

**Comment by neotan** [comment]
let me take a look at it
