### ISSUE TITLE
onVisibleChange点击后隐藏无返回值

### ISSUE THREAD

**Issue by iera2yy** [ant-design/ant-design#30872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown-cn/](https://ant.design/components/dropdown-cn/)

### Steps to reproduce
1、显示dropdown；
2、点击其中内容；
3、dropdown隐藏

### What is expected?
onVisibleChange返回false

### What is actually happening?
无返回值

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | react |
| System | mac |
| Browser | Version 91.0.4472.77 (Official Build) (arm64) |

**Comment by afc163** [comment]
see #4994
