### ISSUE TITLE
ability to set the fields disabled on from Ref  

### ISSUE THREAD

**Issue by EssamEid614** [ant-design/ant-design#30876]
- [yes] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As an example , I am currently using the `antd-form-builder `to build json forms however, i am faced with an issue while trying to set a fields disabled property since the form ref API does not contain a set disabled prop on the form items. Basically what i would like to achieve is have a checkbox disable or enable another field in the form which is a very common use case but through the form ref. 
I know I can just switch to building the form manually however the json builder really helps when you have alot of forms since i build it with JSONs and accessing the onChange of any of the fields to manipulate another field is a pretty good feature to have.

### What does the proposed API look like?
through the `setFields() `function we can pass the `disabled `property and it in turn be applied to the input

**Comment by afc163** [comment]
You should use React state in this case.
