### ISSUE TITLE
Dropdown组件当前下方空间不足时，下拉框往上偏的动画方向不对。

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design#30889]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
无

### What is expected?
动画方向由下至上

### What is actually happening?
由上至下

| Environment | Info |
|---|---|
| antd | 4.16.1|
| React | react 16.13.1 |
| System | win10 x64 |
| Browser | chrome 90 |

**Comment by afc163** [comment]
- ❌ 4.16.2：https://codesandbox.io/s/jiben-antd4162-forked-wzofx?file=/index.js

不知道从哪个版本开始失效的。

**Comment by semdy** [comment]
还有一个问题：如果下拉框里的MenuItem个数是动态的，位置的检测也没那么及时。比如，一开始是一个，下方空间是足够的，后续通过请求接口，动态填充MenuItem的个数，这时下方空间不足，下拉框会先显示在下方，紧接着才往上偏。这个在4.0以前的版本是没有问题。

**Comment by afc163** [comment]
Select/Tooltip 等组件也都出问题了。

**Comment by afc163** [comment]
4.12.3 is good: https://codesandbox.io/s/jiben-antd4123-forked-edqz9

Problem was introduced by https://github.com/ant-design/ant-design/pull/29268

**Comment by semdy** [comment]
请教一下，有没有全局关闭所有Dropdown的方法。

**Comment by semdy** [comment]
> 还有一个问题：如果下拉框里的MenuItem个数是动态的，位置的检测也没那么及时。比如，一开始是一个，下方空间是足够的，后续通过请求接口，动态填充MenuItem的个数，这时下方空间不足，下拉框会先显示在下方，紧接着才往上偏。这个在4.0以前的版本是没有问题。

#29268 有解决这个问题吗
