### ISSUE TITLE
动画transform与fixed兼容问题

### ISSUE THREAD

**Issue by broadliyn** [ant-design/ant-design#3088]
```
<QueueAnim>
<div id="a" key="1"><div style={{position:'fixed'}}></div>
<div id="b" key="2"></div>
</QueueAnim>
```

对于这样一段带有动画效果的jsx，在动画之行完成之后，a和b两个div的style上会保留一些动画结束以后的css样式信息，比如style="opacity: 1; visibility: visible; transform: translateX(0px);"

由于chrome css3 transform和fixed不兼容，fixed定位的元素无法以浏览器窗口为基准进行定位，而是以被设置了transform样式的div为基准进行定位。

具体表现为，编辑器全屏是用的fixed定位，如果在编辑器上的某个父级元素被设置transform的样式，那么编辑器只能覆盖满这个元素而无法覆盖全屏。

可不可以在动画结束以后清空style里动画相关的css样式呢？

https://jsfiddle.net/qpsx84qp/  这个是transform、fixed的具体演示。去掉parent的transform样式，显示就正常了。

**Comment by benjycui** [comment]
@jljsj33 这个好像是在 velocity 那儿加上的？

**Comment by broadliyn** [comment]
修正一下，transform影响fixed定位应该不算是一个bug

**Comment by jljsj33** [comment]
用 transform 后 fixed 本来就是依照，transform 来定位的。。。所以在动画结束后最后把 transform 设为 none。。。。我是这样搞的，，，https://github.com/ant-design/ant-motion/blob/1.2.0/src/theme/template/Layout/index.jsx#L18

**Comment by jljsj33** [comment]
额。。发现 queue-anim 没有结束回调。。。。

**Comment by jljsj33** [comment]
我去增加个回调

**Comment by afc163** [comment]
建议提到 http://github.com/react-component/queue-anim

**Comment by wangyess** [comment]
> 修正一下，transform影响fixed定位应该不算是一个bug
> 
> http://stackoverflow.com/questions/35596475/position-fixed-not-woking-when-parent-has-the-transform-css-property
How to solve the problem of mobile terminal
