### ISSUE TITLE
I have to stop the application and rebuild it to reflect the changes when customizing theme

### ISSUE THREAD

**Issue by abdallanayer** [ant-design/ant-design#30880]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/customize-theme#How-to-do-it](https://ant.design/docs/react/customize-theme#How-to-do-it)

### Steps to reproduce
1- open craco.config.js
2- follow the steps as mentioned in the documentation https://ant.design/docs/react/use-in-typescript#Customize-Theme
3- start the application
4- open craco.config and modify any variable u added
5- you have to stop the application and rebuild it so the changes are reflected

### What is expected?
changes should be reflected via hot reloading without having to stop and start the application

### What is actually happening?
changes are not reflected unless you stop and start the applciation

| Environment | Info |
|---|---|
| antd | 4.15.3 |
| React | 17.0.1 |
| System | macOS Catalina 10.15.7 |
| Browser | All |

**Comment by afc163** [comment]
That you can report it to https://github.com/gsoft-inc/craco/issues
