### ISSUE TITLE
Typography.Text will not change automatically

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/ant-design#30894]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shengluehao-antd4162-forked-3h0yj?file=/index.js)

### Steps to reproduce
Change window width. Typography.Paragraph can be changed automatically. Typography.Text will not change automatically

### What is expected?
Typography.Text can be changed automatically.

### What is actually happening?
Typography.Text will not change automatically

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | >=16.9.0 |
| System | MacOS Big Sur 11.1 |
| Browser | Chrome90.0.4430.93（正式版本） (x86_64) |

**Comment by DerrickTel** [comment]
https://github.com/ant-design/pro-components/issues/2948

**Comment by DerrickTel** [comment]
![Jun-07-2021 16-28-22](https://user-images.githubusercontent.com/24643779/120984639-6f916000-c7ad-11eb-9655-6deb31c2639f.gif)

**Comment by afc163** [comment]
https://codesandbox.io/s/shengluehao-antd4162-forked-ltc67?file=/index.js

```diff
      <Text
-       style={{ maxWidth: "100%" }}
+       style={{ width: "100%" }}
        ellipsis={{
          tooltip:
            "Ant Design, a design language for background applications, is refined by Ant UED Team. Ant"
        }}
      >
```
