### ISSUE TITLE
Select valueRender

### ISSUE THREAD

**Issue by theprimone** [ant-design/ant-design#30903]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可渲染 `label` 到输入框中。类似如下的效果：
![image](https://user-images.githubusercontent.com/18096089/121118679-de71c600-c84c-11eb-8a5f-a76fa4c9a9de.png)

看了一下 ProTable 中的源码，看起来实现很麻烦的样子，如果支持这个特性的话就很简单了。

### What does the proposed API look like?
`valueRender`， 与 `tagRender` 和 `dropdownRender` 类似

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#components-select-demo-option-label-prop

**Comment by theprimone** [comment]
大意了，一心只想着在 Select.Option 中使用 `optionLabelProp` 属性，options 也同样阔以 😂 看来对 antd 还不够熟练 \_(:з」∠)\_

**Comment by theprimone** [comment]
不过还是有个小问题，如果没有值的时候不能直接渲染预期的 label，通过 `placeholder` 来绕过的话需要在没有值的时候重写一下样式才行。

**Comment by theprimone** [comment]
@afc163 大佬，如果多选模式想渲染成如下格式呢？

> 帐号: aaa,bbb,ccc

已知现在只有 tagRender 的属性去定制每一项的渲染。此外如果按我上面所说的通过 placeholder 去绕过的时候输入框是不会自适应宽度的，只能再加个 min-width 去绕过。看起来现在这个需求的实现还是太魔幻了。
