### ISSUE TITLE
Table组件在列宽很大的情况下在谷歌下无法进行自适应

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#30904]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/f5sth?file=/index.js:955-1344)

### Steps to reproduce
谷歌静默升级到了最新版，突出出现此问题

### What is expected?
这种现象和Issue #22780 火狐下显示一样了

### What is actually happening?
未设置scroll的情况下能够自适应窗口
以前因为火狐问题，我们都是要求用谷歌，现在谷歌也这样了。

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 16.12 |
| System | Windows 10 |
| Browser | 谷歌浏览器 |

---
复制一批column出来
    <Column title="Address" dataIndex="address" key="address" />
    <Column title="Address" dataIndex="address" key="address" />
    <Column title="Address" dataIndex="address" key="address" />
    <Column title="Address" dataIndex="address" key="address" />
    <Column title="Address" dataIndex="address" key="address" />
    <Column title="Address" dataIndex="address" key="address" />

**Comment by xyy94813** [comment]
Got same problem in Chrome Version 91.0.4472.77.

And work well in chrome v90.

**Comment by just-myself** [comment]
https://user-images.githubusercontent.com/29473501/121282206-ada49600-c90b-11eb-94da-45d81bc1f580.png

**Comment by xyy94813** [comment]
https://codesandbox.io/s/jsx-fenggede-api-antd4162-forked-ihb4b?file=/index.js
https://ihb4b.csb.app/

**Comment by xyy94813** [comment]
My project work well in latest version of antd(v4.16.2)

**Comment by fnll** [comment]
> My project work well in latest version of antd(v4.16.2)
> 
> Example work well in latest version too.
> https://codesandbox.io/s/jsx-fenggede-api-antd4162-forked-3n6u1?file=/index.js
> https://3n6u1.csb.app/

Table would set min-width to colgroup element in all conditions, that may break the layout and have been fixed [here](https://github.com/react-component/table/pull/626)

**Comment by phoema** [comment]
4.14升级到4.16.2，显示正常了。

**Comment by pbwei** [comment]
.ant-table-layout-fixed table {
        table-layout:auto !important;
      }
