### ISSUE TITLE
onClear attribute in AntD Timepicker

### ISSUE THREAD

**Issue by arslanalidev** [ant-design/ant-design#30901]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
While we are customizing the antd in our system and removing the ok button. 
At this time we are managing the time values externally. But when we click on the clear button it throws the error of invalidate value while we are using it with formik.  
So I would suggest you please also expose the clear attribute in and. So that we can reset our own value.

### What does the proposed API look like?
While we will provide this onClear attribute it will provide the user more flexibility in our ant d componenent. So it will be very beneficial for each of us.

**Comment by afc163** [comment]
Try `onChange`.

**Comment by arslanalidev** [comment]
It's not working yet
