### ISSUE TITLE
Expose setClosed prop to programmatically open and close Alert component

### ISSUE THREAD

**Issue by caseywoolley** [ant-design/ant-design#30917]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The only way to close the Alert component is by user action.  Add setClosed prop to programmatically change the Alert close state.

### What does the proposed API look like?
```<Alert setClosed={true} />```

**Comment by afc163** [comment]
`visible && <Alert />`

**Comment by caseywoolley** [comment]
<Alert setClosed={true} />   -->  Smooth closing animation
visible && <Alert />  -->  Abruptly disappears

There might as well not be a nice closing animation if it can't be consistently applied.

**Comment by penguin-io** [comment]
Yes, It would be nice if there's a smooth opening animation solution rather than just trying to show and hide with `visible && <Alert />`.
