### ISSUE TITLE
Tooltip for icons is never displayed

### ISSUE THREAD

**Issue by DrDiman** [ant-design/ant-design#30915]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-bug-icon-1lc8f?file=/index.js)

### Steps to reproduce
take a look at the sandbox https://codesandbox.io/s/tooltip-bug-icon-1lc8f?file=/index.js

### What is expected?
tooltip should be shown

### What is actually happening?
tooltip isn't shown

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.2 |
| System | Windows |
| Browser | Chrome |

---
take a look at the sandbox https://codesandbox.io/s/tooltip-bug-icon-1lc8f?file=/index.js

**Comment by afc163** [comment]
https://codesandbox.io/s/tooltip-bug-icon-forked-yxt1m?file=/index.js
