### ISSUE TITLE
文档问题-在typescript中使用

### ISSUE THREAD

**Issue by candy4290** [ant-design/ant-design#30913]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-in-typescript-cn](https://ant.design/docs/react/use-in-typescript-cn)

### Steps to reproduce
npx create-react-app antd-demo-ts --typescript 运行后并没有出现tsx文件

### What is expected?
出现tsx文件

### What is actually happening?
没有出现tsx文件

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | windows |
| Browser | chrome80 |

---
应该使用npx create-react-app antd-demo-ts --template typescript

**Comment by afc163** [comment]
来个 PR

**Comment by candy4290** [comment]
> 来个 PR
ok,it's here
https://github.com/ant-design/ant-design/pull/30918
