### ISSUE TITLE
Badge HTML markup is not passing markup validation

### ISSUE THREAD

**Issue by niksajanjic** [ant-design/ant-design#30916]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-f8gg6?file=/index.js)

### Steps to reproduce
By inspecting the HTML of the basic `Badge` component code example from Ant documentation we can see it would be something like this:

```JS
<span class="ant-badge">
  <a href="#" class="head-example"></a>
    <sup data-show="true" class="ant-scroll-number ant-badge-count" title="5">
      <span class="ant-scroll-number-only" style="transition: none 0s ease 0s;">
        <p class="ant-scroll-number-only-unit current">5</p>
      </span>
    </sup>
</span>
```

Having `p` tag as a child of `span` tag or any other inline tag is not allowed. Block elements are not allowed inside inline elements.

Here is more on the issue: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content

### What is expected?
`p` tag is not allowed to be inside `span` tag. We should use `span` tag instead.

### What is actually happening?
`p` tag is inside `span` tag which is breaking markup validation.

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.2 |
| System | OSX 11.4 |
| Browser | Chrome |

---
This should be a really quick fix, just replace `p` tag with a `span`. Having to pass `span` tag as a `count` property instead of a number loses the default styling so that is not an option.

**Comment by PeachScript** [comment]
PR welcome :D
