### ISSUE TITLE
if i create a form.list inside a form.list i get unexpected values ​​when removing item

### ISSUE THREAD

**Issue by Pequem** [ant-design/ant-design#30929]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-m3y9hm?file=src/App.js](https://stackblitz.com/edit/react-m3y9hm?file=src/App.js)

### Steps to reproduce
1 - Add a 'Area', fill the 'Nome' field
2 - Add a 'Atributo'. fill the 'Aderencia' field
3 - Remove Area

### What is expected?
The area and the nested attributes are full removed from data retorned by onValuesChange

### What is actually happening?
The area is removed but the attribute remains undefined

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | reactjs 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by Pequem** [comment]
before and after remove area (parent Form.List item)
![image](https://user-images.githubusercontent.com/11294736/121313944-4839b080-c8dd-11eb-9c20-daf29566b2b8.png)

**Comment by PeachScript** [comment]
`L100 - L101` in your reproduce link:
> _f.name = [currentField.name, _f.name];
> _f.fieldKey = [currentField.fieldKey, _f.name];

But `name` and `fieldKey` must be `string`, you can join array items with `'-'` to fix it.

**Comment by Pequem** [comment]
I fixed it in the example, but the problem remains

**Comment by zombieJ** [comment]
Too many warning in your demo. You should fix this first since React need correct key to map node fo render.
