### ISSUE TITLE
表格在有展开行的情况下，表头的列和内容区域的列没有对其

### ISSUE THREAD

**Issue by shenzhigang** [ant-design/ant-design#3092]
表格在有展开行的情况下，表头的列和内容区域的列没有对齐
如果设置了列宽，偏移会好一些，但也没有对齐。
- antd 版本:1.11.0
- 操作系统及其版本:windows 10
- 浏览器及其版本:chrome 53

**Comment by RifeWang** [comment]
样式的原因可以自己微调。。

**Comment by ddcat1115** [comment]
请升级到1.11.2试试，如果还是不行请提供下可重现demo

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
确实有问题：http://codepen.io/anon/pen/wzEEXL?editors=001

**Comment by afc163** [comment]
知道了，这个和 https://github.com/ant-design/ant-design/issues/2739#issuecomment-240325043 应该是同一个问题，总长度不够了。
