### ISSUE TITLE
Tooltip component doesn't work as expected when children wrapped with ConfigProvider 

### ISSUE THREAD

**Issue by YagamiNewLight** [ant-design/ant-design#30924]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ftcqkw](https://stackblitz.com/edit/react-ftcqkw)

### Steps to reproduce
Hover the button

### What is expected?
The Tooltip text should show

### What is actually happening?
Nothing show

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.0 |
| System | Win10 |
| Browser | Chrome  91.0.4472.77 |

---
If the button is not wrapped by ConfigProvider, then the Tooltip will work properly

**Comment by YagamiNewLight** [comment]
By the way, I have tried the way of setting getPopupContainer on both Tooltip and ConfigProdiver components but doesn't work as well.

**Comment by zombieJ** [comment]
ConfigProvider do not pass props to child node. Change to:
```
<ConfigProvider>
    <Tooltip title="prompt text">
        <Button>按钮</Button>
    </Tooltip>
</ConfigProvider>
```

instead.

**Comment by afc163** [comment]
Tooltip will add `onMouseEnter` and `onMouseLeave` to it's children, `ConfigProvider` in this case which cannot accept this events.

**Comment by YagamiNewLight** [comment]
Totally make sense. Cheers.
