### ISSUE TITLE
input输入框禁止切换中文输入法

### ISSUE THREAD

**Issue by peng-oss** [ant-design/ant-design#30923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
输入密码的时候禁止切换到中文输入法，方便用户体验感

### What does the proposed API look like?
比如一个属性设置了就禁止切换中文

**Comment by afc163** [comment]
Chrome 下目前没什么好办法：https://stackoverflow.com/a/32214271/3040605
