### ISSUE TITLE
table column width is useless 

### ISSUE THREAD

**Issue by manzxiao** [ant-design/ant-design#30931]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s6hgl)

### Steps to reproduce
1. set a column attribute  width: 80.

### What is expected?
current column should wrap and width should be 80

### What is actually happening?
current column will not wrap.

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.2 |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-s6hgl?file=/index.js

**Comment by manzxiao** [comment]
Nothing has changed?
