### ISSUE TITLE
Option to provide crossorigin for avatar/image 

### ISSUE THREAD

**Issue by SarathSantoshDamaraju** [ant-design/ant-design#30932]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When an external plugin is used with Antd, for export. the avatar component doesn't provide an option to add crossorigin to the image tag. This is needed by buckets like s3 to download and export the Images by the js plugin. Else the CORS error is thrown. 

### What does the proposed API look like?
<Avatar crossOrigin="" | "null" | "anonymous" | "use-credentials" {...other props} />

**Comment by spencer741** [comment]
Tagging @afc163 @SarathSantoshDamaraju 

All should already be doable with current antd lib. I am not sure what 3rd party plugin you are referring to, but here is what I would do to keep it simple:

```js
<Avatar
  src={
    <Image />
  }
  size={164}
/>
```

Note that ANTD's [Image](https://ant.design/components/image/) also inherits properties from HTML's [img tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attributes) 

Go to ANTD Image docs [here](https://ant.design/components/image/) and scroll to the bottom. You will see that Image (antd) is a wrapper for img (html). 

You should be able to pass img (html) props to the <Image /> component to use 'cross-origin' , 'use-credentials', etc...

**Alternatively**, you could retrieve the image asynchronously via an http request, where you could use a library like axios (or whatever) to customize however many headers or http request flags you need.

```js 
const [profilePicture, setProfilePicture] = useState(null);
```
...
```js

someajaxpromise
      .then((values)=>{
        console.log(values.data);
        setProfilePicture(values.data);
      })
      .catch((err) => {
        console.log(err);
      });
```
...
```js
<Avatar
  icon={<UserOutlined />} 
  src={
    profilePicture === null ? null : <Image src={"data:image/png;base64," + profilePicture} />
  }
  size={164}
/>
```
