### ISSUE TITLE
If you remove a field, 'form' doesn't forget the field.

### ISSUE THREAD

**Issue by Pequem** [ant-design/ant-design#30936]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ubjejl?file=src/App.js](https://stackblitz.com/edit/react-ubjejl?file=src/App.js)

### Steps to reproduce
1 - Select 'Escolha de atributo' in 'Estagio' seletc
2 - type something in anywhere field that appeared
3 - Change 'Escolha de atributo' to another option

### What is expected?
onValuesChange give something like this
stages: Array[1]
       0: Object
             name: ""
             type: "FORWARD-BLOCK-STAGE"

without areaAttributesQuantities object, 
because it should only appear when the select is in 'Escolha de atributo'

### What is actually happening?
onValueChange give me this
stages: Array[1]
  0: Object
       areaAttributesQuantities: Array[2]
            0: Object
           1: Object
                id: 2
               quantity: ""
       name: ""
       operation: ""
      type: "FORWARD-BLOCK-STAGE"

the areaAttributesQuantities shouldn't be there.

if you change the selection again, the areaAttributesQuantities  disappears as expected and in onFinish it never appears where it shouldn't, so apparent onValuesChange is returning the values ​​before all the work is done

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | reactjs 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

---

I have a similar problem in Form.List, if I put every app returning in a List, but in this case onFinish also returning wrong values ​​and areaAttributesQuantities never disappears

https://stackblitz.com/edit/react-4scar3

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/121451626-8368dc00-c9d0-11eb-98e8-621b831d469c.png)
https://ant.design/components/form/#API
