### ISSUE TITLE
表单组件数据的传递

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3094]
<script type="text/babel">
        const { Form, DatePicker, InputNumber, Button } = antd;
        const FormItem = Form.Item;

        var MyTime = React.createClass({
            render: function () {
                return (
                        <div>
                            <div>
                                <h1>{this.props.time}</h1>
                            </div>
                            <div>
                                <p>工位: </p>
                                <InputNumber
                                        placeholder="工位"
                                        min={0}
                                        defaultValue={2}
                                />
                            </div>
                            <div>
                                <p>折扣: </p>
                                <InputNumber
                                        label="折扣"
                                        placeholder="折扣"
                                        min={0} max={10} step={0.5}
                                        defaultValue={9}
                                />
                            </div>
                        </div>
                );
            }
        });

        var TimeSelect = React.createClass({
            render: function () {
                return (
                    <table>
                        <tbody>
                            <tr>
                                <th><MyTime time='08:30'/></th>
                                <th><MyTime time='09:00'/></th>
                                <th><MyTime time='09:30'/></th>
                                <th><MyTime time='10:00'/></th>
                                <th><MyTime time='10:30'/></th>
                                <th><MyTime time='13:00'/></th>
                                <th><MyTime time='13:30'/></th>
                            </tr>
                            <tr>
                                <th><MyTime time='14:00'/></th>
                                <th><MyTime time='14:30'/></th>
                                <th><MyTime time='15:00'/></th>
                                <th><MyTime time='15:30'/></th>
                                <th><MyTime time='16:00'/></th>
                                <th><MyTime time='16:30'/></th>
                            </tr>
                        </tbody>
                    </table>
                );
            }
        });

        var Appoint = React.createClass({
            handleSubmit(e) {
                e.preventDefault();
                console.log('收到表单值：', this.props.form.getFieldsValue());
                console.log(this.refs.test1.getInputDOMNode().value);
            },

            render: function () {
                const { getFieldProps } = this.props.form;

                return (
                        <Form onSubmit={this.handleSubmit}>
                            <FormItem>
                                <TimeSelect ref='test1' {...getFieldProps('tem')}/>
                            </FormItem>
                            <FormItem>
                                <DatePicker ref='myDate'
                                            style={{margin:10}} size="large"
                                            {...getFieldProps('val')}
                                />
                            </FormItem>
                            <FormItem>
                                <Button style={{margin:10}} size="large"
                                        type="primary" htmlType="submit">确定</Button>
                            </FormItem>
                        </Form>
                );
            }
        });
        Appoint = Form.create()(Appoint);

        ReactDOM.render(<Appoint/>, document.getElementById('time'));

    </script>
MyTime 组件封装了一个时间属性和两个数字输入框，
TimeSelect 组件按表格的形式封装了多个MyTime 组件，
Appoint 组件则是一个表单组件，封装了TimeSelect 组件和一个DatePicker组件加一个按钮
请问怎样通过按钮点击能一次获取到TimeSelect 组件中封装的所有MyTime 组件的数据？

**Comment by benjycui** [comment]
自定义组件暴露 `onChange` 事件后，就可以用 `getFieldProps` 来搜集数据，具体如何实现，可以研究下 antd 的表单组件，如 Checkbox。
