### ISSUE TITLE
Select  use "showSearch "  Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by test7748** [ant-design/ant-design#30947]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://127.0.0.1:8001/webroot_new/users/list](http://127.0.0.1:8001/webroot_new/users/list)

### Steps to reproduce
<Select placeholder="请选择" style={{width: '150px'}}
	labelInValue={true}
	options={schoolItem}
	showSearch
	optionFilterProp="children"
	filterOption={(input, option) =>
    option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0
  }
>
</Select>

当按键之后，直接报错：
TypeError: Cannot read property 'toLowerCase' of undefined

### What is expected?
希望按键输入后，能匹配出相关选项。

### What is actually happening?
按键直接报错。。。

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.0 |
| System | windows10 |
| Browser | chrome 91.0.4472.77 |

**Comment by test7748** [comment]
已搞定。。。。因为用了 options={schoolItem} 的原因，跟踪找到原因了。
改成下面这样就可以了：
filterOption={(input, schoolItem) =>
     schoolItem.label.toLowerCase().indexOf(input.toLowerCase()) >= 0
}

**Comment by Junaid300** [comment]
I am not sure about your issue. I faced this issue when i was try to use `toLowerCase()` for a null value.  For some reason `schoolItem.label` is null or `input` is `null`
