### ISSUE TITLE
When I use the collapse to show a html page ,the picture in the html page will look very small.我用collapse的Panel显示一个html页面时，里面包含视频和图片，但是图片显示的非常小。 

### ISSUE THREAD

**Issue by Flyooofly** [ant-design/ant-design#30944]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了在Panel中显示html页面，其中图片显示很小的问题

### What does the proposed API look like?
希望在显示html时，对于其中的图片显示大一些，目前的太小了
![image](https://user-images.githubusercontent.com/31236750/121412174-fce3d880-c996-11eb-8b84-0025e59d8ecc.png)

**Comment by Flyooofly** [comment]
就只是在collapse的panel中显示html啊。。。
很普通的html构成
'<div ><img  height="200" width="200" src="'+img_res[j]+'"/></div><p></p>'
'<div ><video width="300" height="200" src="'+video_res[j]+'" controls=" "></video></div><p></p>'
视频的显示大小正常，但是图片显示过小

**Comment by yoyo837** [comment]
请带复现提交issue,而不是使用feature模版

**Comment by Flyooofly** [comment]
> 请带复现提交issue,而不是使用feature模版

但是不用他那个他不是说会被立即关闭吗。
这是使用panel的的代码
![image](https://user-images.githubusercontent.com/31236750/121623208-deb6cf00-caa1-11eb-9213-6ad6ea84b2ba.png)
html就是包含上边发的那个，img和video标签，但是img显示太小了
