### ISSUE TITLE
When modal is added the style on the body is updated narrowing the body content width

### ISSUE THREAD

**Issue by LukaszGrela** [ant-design/ant-design#30945]
- [X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/LukaszGrela/pen/WNpgQNW](https://codepen.io/LukaszGrela/pen/WNpgQNW)

### Steps to reproduce
Open modal
See the style on the body to be `<body class="ant-scrolling-effect" style="width: calc(100% - 17px); overflow: hidden;">`

### What is expected?
dont put inline styles on non react tags! I see the class name was applied and there the new style should be added, anyways, this is not needed when modal fits the screen e.g. when content has it's own overflow rules preventing content to spill. Especially that scrolling doesnt have to be on the body.

Ideally the solution would be to opt-out of that behaviour, so how to turn it off?

### What is actually happening?
redundant offset of the body content

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | any |

**Comment by nrayburn-tech** [comment]
See https://ant.design/docs/react/faq#antd-overrides-my-global-styles for some information.

**Comment by afc163** [comment]
It is intented feature to avoid modal jumping when open it.
