### ISSUE TITLE
官网左侧菜单有时候鼠标放上去滚动没反应

### ISSUE THREAD

**Issue by hwlv** [ant-design/ant-design#30958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
影响体验

### What does the proposed API look like?
官网左侧菜单鼠标放上能正常滚动

**Comment by afc163** [comment]
我这里没问题。

**Comment by afc163** [comment]
感觉是网络问题，建议 FQ 或者访问国内镜像：https://ant-design.gitee.io/index-cn
