### ISSUE TITLE
<Table /> 横向滚动条在最左、右测时，固定列滚动不流畅

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#3096]
如题，当 <Table /> 组件左侧有固定列时，如果滚动条在最左侧、或最右侧时，此时，滚动纵向滚动条，会出现卡顿、不流畅现象。[点击查看demo](http://codepen.io/ystarlongzi/pen/ozzVOK)，效果见下图：

![111](https://cloud.githubusercontent.com/assets/2840462/18660281/2d709e60-7f42-11e6-8ed9-654c164560c6.gif)

**Comment by yesmeck** [comment]
@ystarlongzi  做了优化，升到 antd@2.2.0 试试。

**Comment by ystarlongzi** [comment]
@yesmeck 
升级后项目里还是存在这个现象，并且 codepen 给的 demo 也扔存在这个现象。

**Comment by yesmeck** [comment]
@ystarlongzi 看看你项目的 rc-table 的版本 `npm list rc-table`。

**Comment by ystarlongzi** [comment]
不好意思，昨天没注意留言。版本如下
```
└─┬ antd@2.2.0
  └── rc-table@5.0.4 
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/3397

没有使用 babel-plugin-import ？

**Comment by yesmeck** [comment]
确实还有问题，Chrome 下我这里是可以了，Firefox 貌似没对 hover 事件做优化，滚动的时候会一直触发 hover。

**Comment by ystarlongzi** [comment]
@afc163 没有使用`babel-plugin-import`，直接引入打包后的文件

**Comment by afc163** [comment]
那现在没办法享受依赖模块更新。具体见 #3397

**Comment by ystarlongzi** [comment]
@afc163 
好的，谢谢！
