### ISSUE TITLE
[Table][Header] The fixed column's name is overlapped after scrolling

### ISSUE THREAD

**Issue by tommyspot** [ant-design/ant-design#30969]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-columns-antd4162-forked-w3u9y?file=/index.js)

### Steps to reproduce
1. Scrolling a table from right to left side.
2. Hover fixed column which has a sorting.
3. Column name was overlapped.

### What is expected?
The column name is not overlapped after scrolling

### What is actually happening?
The column name of the fixed column (sorted) is overlapped

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 16.14.0 and later |
| System | MacOS |
| Browser | Chrome, Firefox, Safari |

**Comment by PeachScript** [comment]
The head item's background color will become `rgba` value when we `hover` it, so we can see other items behind.

I think it is a style bug, and it would be better if you could create a pull request to fix it :P

**Comment by tommyspot** [comment]
> The head item's background color will become `rgba` value when we `hover` it, so we can see other items behind.
> 
> I think it is a style bug, and it would be better if you could create a pull request to fix it :P
