### ISSUE TITLE
Popover will not open on trigger

### ISSUE THREAD

**Issue by ryanbrwr** [ant-design/ant-design#30975]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ryanbrwr/ant-popover-bug](https://github.com/ryanbrwr/ant-popover-bug)

### Steps to reproduce
1. run npm start
2. click the "Help me please" button

### What is expected?
It is expected that the popover would open, and display the component that is given in the content field. 

### What is actually happening?
The popover class is being added, but the popover is not visible on the page.

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.2 |
| System | MacOs Catalina 11.1 |
| Browser | Chrome Version 91.0.4472.77 (Official Build) (x86_64) |

---
Popovers have always worked for me in other projects, all other components are working fine in this setup. 

Link to view said bug
https://www.loom.com/share/be2f28261a0648c49301b729b1467467

**Comment by ryanbrwr** [comment]
Also, selections will not open

**Comment by afc163** [comment]
Please remove these lines: https://github.com/ryanbrwr/ant-popover-bug/blob/21934969177cb2878bd41c5e34f3c1f70ac38e7d/src/App.less#L7-L10

**Comment by ryanbrwr** [comment]
I was just going to write that it seems to be the overflow giving me this issue, I appreciate it!
