### ISSUE TITLE
make List Items focus on by pressing tab key 

### ISSUE THREAD

**Issue by mrzslr** [ant-design/ant-design#30974]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
with this feature use can focus on list items by press TAB key on the keyboard and hit the enter to select.

### What does the proposed API look like?
```
<List
    focusable={true}
    />
```

**Comment by afc163** [comment]
Sorry, seletable list item is not out plan.
