### ISSUE TITLE
Skypack CDN is unable to build `antd` package

### ISSUE THREAD

**Issue by Manish3323** [ant-design/ant-design#30981]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://cdn.skypack.dev/antd](https://cdn.skypack.dev/antd)

### Steps to reproduce
please go to this link : https://cdn.skypack.dev/antd, it will trigger the skypack's build workflow for antd package.
as it fails currently, it provides a link to build error, you need to attach that build error link at the end of `https://cdn.skypack.dev/{link to build error}` to see what actually failed.

for ex : this link `https://cdn.skypack.dev/error/build:antd@v4.16.2-87q2GuBydiL1PXDHVMhg`
it says it cannot build `rc-utils/es/dom package` 
 
```typescript 
/*
 * [Package Error] "antd@v4.16.2" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   [3/5] Building package using esinstall…
 *   Running esinstall...
 *   Could not resolve "rc-util/es/Dom/dynamicCSS".
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */
```

### What is expected?
skypack should be able to build it

### What is actually happening?
skyapck is not able to find `rc-util/es/dom` package could be because of some incorrect imports internally.

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 17.0.2 |
| System | Mac os 10.14.6 |
| Browser | chrome |

---
Side-Note: skypack is cdn for npm packages which supports esm modules. we are using antd & snowpack in our project & it would be nice if we were able to load antd directly from skypack cdn which is supported by snowpack.

**Comment by afc163** [comment]
You could report it to Skypack https://github.com/skypackjs/skypack-cdn/issues
