### ISSUE TITLE
Error using imgCrop on oss upload

### ISSUE THREAD

**Issue by Sunnyjson** [ant-design/ant-design#30988]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-urvf3?file=/index.js)

### Steps to reproduce
1. using imgCrop
2. data callback => file not has url

### What is expected?
has url

### What is actually happening?
not has url

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.x |
| System | mac |
| Browser | chrome |

**Comment by Sunnyjson** [comment]
把antd 降到4.6.1, antd-img-crop 降到3.9.0 解决了这个问题， 应该是在之后的版本出现了这个bug， 希望能得到解决

**Comment by afc163** [comment]
三方库的问题建议提到对应仓库的 issues 去。

**Comment by afc163** [comment]
另外你这个感觉可以在 data 内直接给 file 赋值：https://codesandbox.io/s/antd-reproduction-template-forked-ozw99

**Comment by Sunnyjson** [comment]
> 另外你这个感觉可以在 data 内直接给 file 赋值：https://codesandbox.io/s/antd-reproduction-template-forked-ozw99

 把antd 降到4.6.1没有问题， 因为oss上传案例是在beforeUpload时加上的url， 后续尝试一下直接在data赋值。感谢回复

**Comment by baibaibai455** [comment]
"antd": "^4.19.5",    依然存在这个问题

**Comment by 2449847346** [comment]
"antd":"4.20.3",依然存在该问题，未修复
