### ISSUE TITLE
Line is missing in Tree

### ISSUE THREAD

**Issue by darikar** [ant-design/ant-design#30992]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/66exw)

### Steps to reproduce
Open folder parent 1-2

### What is expected?
The folder "parent 1" and "parent 1-2" should also contain the line like folder parent 1-0

### What is actually happening?
The line is not visible

| Environment | Info |
|---|---|
| antd | 4.10.1 |
| React | ^16.14.0 |
| System | macOS, Windows |
| Browser | Chrome |

---
What should i do to make a line visible?

**Comment by afc163** [comment]
It is by design, last parent node will not show connect line.

**Comment by fsjobeck** [comment]
Any chance this can be changed to allow for the line to show? It would make more sense to be able to have a consitent look and UX through the entire component?
