### ISSUE TITLE
Pagination size changer type

### ISSUE THREAD

**Issue by kenazs** [ant-design/ant-design#30991]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to use pagination with buttons as size changer control, but it's not possible

### What does the proposed API look like?
PaginationProps shoud extends by adding new property "sizeChangerType": "select" | "buttons"

**Comment by kenazs** [comment]
Example: ![image](https://user-images.githubusercontent.com/10974148/122046177-42653300-cde7-11eb-899d-6b678d3bc7e8.png)

**Comment by afc163** [comment]
Sorry, it will not fit our design specification.
