### ISSUE TITLE
dependencies not work in FormItem with initialValue

### ISSUE THREAD

**Issue by xiaofengqqcom123** [ant-design/ant-design#30995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhucexinyonghu-antd4163-forked-7vmvv?file=/index.js)

### Steps to reproduce
含有初始值的表单项A，B。B依赖于A，用于表单校验，当修改A时，未触发 B 的校验

### What is expected?
当修改A时，触发 B 的校验

### What is actually happening?
当修改A时，未触发 B 的校验

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 18.0.0-a |
| System | mac |
| Browser |  86.0.4240.75 |

**Comment by zombieJ** [comment]
奇怪……为啥每次收入它都会弹一下…………
