### ISSUE TITLE
Antd Step has uneven step tail length between the items

### ISSUE THREAD

**Issue by jayanthbondi** [ant-design/ant-design#30993]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mini-version-antd4163-forked-u7is4?file=/index.js)

### Steps to reproduce
1) Create a step component which has 3 steps of different titles.
2) Give width to steps.

### What is expected?
Even line should be present between 2 step items

### What is actually happening?
Uneven line is present between 2 step items
![image](https://user-images.githubusercontent.com/35721161/122101263-b5939700-ce31-11eb-9e26-c61b349ff66f.png)

| Environment | Info |
|---|---|
| antd | 3.26.10 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
It is by designed.

**Comment by chervinvananaz** [comment]
I also want to happen like even lines ,, can it be possible?

**Comment by shiwanjun1995** [comment]
When i have multiple steps, the title with icon would be distort. @afc163

**Comment by shiwanjun1995** [comment]
![Uploading 截屏2024-03-21 下午8.52.09.png…]()
