### ISSUE TITLE
打包后没有 treeShaking

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#30998]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Dolov/myapp](https://github.com/Dolov/myapp)

### Steps to reproduce
https://github.com/Dolov/myapp  这个仓库工程中是我简单搭建的一个工程，只在入口文件中引入了 Button 组件，查看打包后的产物发现，所有的组件都被引入了

### What is expected?
期望只引入必要的组件

### What is actually happening?
所有组件都引入了

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | MAC |
| Browser | CHROME |

**Comment by afc163** [comment]
https://github.com/Dolov/myapp/pull/1
