### ISSUE TITLE
编译合并后的 js css 发到 npm

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#31]
参考 react react-router，方便使用， 需要配置 webpack output 为 umd

**Comment by afc163** [comment]
如果依赖组件小版本号更新的话，编译后的文件就会变化，这个不好搞。

**Comment by yiminghe** [comment]
那把 css 放上去吧，less 源码没必要放 npm

2015-07-07 19:50 GMT+08:00 偏右 <notifications@github.com>:
