### ISSUE TITLE
datepicker 增加时间范围选择功能

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#310]
简单的增加一个范例。

---

或者可以封装成一个双日历组件。

```
<Datepicker range={true} />
```

![](https://t.alipayobjects.com/images/rmsweb/T15FliXhpkXXXXXXXX.png)

**Comment by yiminghe** [comment]
我打算支持双日历

**Comment by afc163** [comment]
讨论后得到以下结论：

1. 双日历面板中需要两个 input 用于标识状态和手动输入。
2. 为了保持实现统一，单日历面板中也将加入 input ，并且支持手动输入。
3. 由于页面上的 trigger 一般也是 input，为了保持页面简洁，视觉上采用类似 https://material.angularjs.org/latest/#/demo/material.components.datepicker 的遮挡方案。

**Comment by yiminghe** [comment]
https://github.com/react-component/calendar/tree/range-calendar

**Comment by afc163** [comment]
https://github.com/react-component/calendar 已经升级到 4.x 。@lifesinger

**Comment by lifesinger** [comment]
好

**Comment by afc163** [comment]
## 0.10.0 版本，日期/时间选择类组件的日历浮层内的输入框的交互逻辑

- 输入框和当前选择日期实时绑定。
- 当输入框内容发生合法变化，浮层消失后（例如点击空白处），数值反馈到触发器上。
- **只有以下行为**可以触发输入框内容合法变化。
  * 日期选择控件点击日期。
  * 年月日期选择控件点击月。
  * 手动修改日期为合法值。
  * 手动清空输入框（清空功能）。
  * 时间选择和范围选择浮层上的`确定`按钮。
  * `今天` 等快捷选择链接。
- 对于不合法的手动修改，日期将返回上一个合法值。

**Comment by xiao-hai** [comment]
关注
