### ISSUE TITLE
How to change checkbox disabled style (eg: color)

### ISSUE THREAD

**Issue by LuoShiXi** [ant-design/ant-design#31009]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义修改复选框disabled时的样式？

### What does the proposed API look like?
可以自定义修改复选框的disabled样式，如：disabled时，并不是灰色，更想要一种高亮的颜色，只不过不可编辑！！！

**Comment by zombieJ** [comment]
HOC 包一下，搞个 `className` 自行覆盖。

**Comment by LuoShiXi** [comment]
Ok, I will try.
