### ISSUE TITLE
列固定如果顺序不对，将会出现样式错乱

### ISSUE THREAD

**Issue by zhaodeezhu** [ant-design/ant-design#31010]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zhanchujiang/pen/eYvxmOY](https://codepen.io/zhanchujiang/pen/eYvxmOY)

### Steps to reproduce
列的配置固定列不是放在最前面
[
{
    title: 'Full Name',
    width: 100,
    dataIndex: 'name',
    key: 'name',
    fixed: 'left',
  },
  {
    title: 'Column 1',
    dataIndex: 'address',
    key: '1',
    width: 150,
  },
    {
    title: 'Age',
    width: 100,
    dataIndex: 'age',
    key: 'age',
    fixed: 'left',
  },
]

### What is expected?
和antd@3.x一样的效果，设置了固定列会自动排序在前面或者后面，例如：https://codesandbox.io/s/gallant-wildflower-er5wi?file=/index.js

### What is actually happening?
会样式错乱，会按照列配置的位置去固定

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | react@17.0.1 |
| System | Mac |
| Browser | chrome@91.0.4472.106 |

---
antd@4.x的效果：https://codepen.io/zhanchujiang/pen/eYvxmOY
antd@3.x的效果：https://codesandbox.io/s/gallant-wildflower-er5wi?file=/index.js

**Comment by afc163** [comment]
3.x 这样做是因为用了三个表格，需要把所有 fix: left 的列移到前面来才能实现固定效果。

4.x 用了 sticky，理论上已经可以实现中间列固定的效果（虽然诡异但是符合预期），现在再做列的移动意义不大。
