### ISSUE TITLE
[Form & InputNumber] Wrong formatter value when trying to insert negative fraction number

### ISSUE THREAD

**Issue by jmatelowski** [ant-design/ant-design#31015]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/c9e5af93-09f2-421d-a8c1-3bbfeb1416fe-forked-twwo4?file=/Component.jsx)

### Steps to reproduce
Try to type negative fraction number e.g. -0.5

### What is expected?
The input value is -0.5

### What is actually happening?
When user type '-0', the value changes to '0'. It should work like the second form item (without name prop).

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.14.0 |
| System | macOS Mojave 10.14.6 |
| Browser | Chrome Version 91.0.4472.77 (Official Build) |

**Comment by zombieJ** [comment]
Merge into #30455
