### ISSUE TITLE
BackTop 增加target属性

### ISSUE THREAD

**Issue by fwh1990** [ant-design/ant-design#3101]
- antd 版本: 1.11.1
- 操作系统及其版本: macos 10.11
- 浏览器及其版本:   firefox 最新版本

组件默认是根据body的scroll来判断滚动条的高度，对于局部滚动的网页无效，因为是div在滚动，div设置了overflow:auto。

希望能像 固钉 组件一样，加个target属性

**Comment by benjycui** [comment]
已经有了 https://github.com/ant-design/ant-design/blob/master/components/back-top/index.tsx#L53

**Comment by benjycui** [comment]
有这方面需求的场景多了再写进文档吧。
