### ISSUE TITLE
TypeError: Cannot read property 'scrollTop' of undefined

### ISSUE THREAD

**Issue by nimahkh** [ant-design/ant-design#31014]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[  https://u.ant.design/codesandbox-repro](  https://u.ant.design/codesandbox-repro)

### What is actually happening?
After filtering with custom input filter, I faced with an error that said: "TypeError: Cannot read property 'scrollTop' of undefined", when I am using normal filtering, there is no error, also I am using react-window beside of this. the custom input is exactly what is in document and I am using UMI.js too. after calling "confirm()" function , this error faced up. 

This is not about react-window, because normal filter is working , just functional filter has error after confirm()

```js
const handleSearch = (selectedKeys, confirm, dataIndex) => {
    confirm({ closeDropdown: false });
    setSearchText(selectedKeys[0]);
    setSearchColumn(dataIndex);
  };

const getColumnSearchProps = (dataIndex) => ({
    filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters }) => (
      <div style={{ padding: 8 }}>
        <Input
          placeholder={`Search ${dataIndex}`}
          value={selectedKeys[0]}
          onChange={(e) => setSelectedKeys(e.target.value ? [e.target.value] : [])}
          onPressEnter={() => handleSearch(selectedKeys, confirm, dataIndex)}
          style={{ width: 188, marginBottom: 8, display: 'block' }}
        />
        <Space>
          <Button
            type="primary"
            onClick={() => handleSearch(selectedKeys, confirm, dataIndex)}
            icon={<SearchOutlined />}
            size="small"
            style={{ width: 90 }}
          >
            Search
          </Button>
          <Button onClick={() => handleReset(clearFilters)} size="small" style={{ width: 90 }}>
            Reset
          </Button>
        </Space>
      </div>
    ),
    filterIcon: (filtered) => (
      <SearchOutlined style={{ color: filtered ? '#1890ff' : undefined }} />
    ),
    onFilter: (value, record) =>{
      console.log(dataIndex,record[dataIndex],value);
     },
  });

const columns = [
   {
      title: 'sample',
      key:'rect',
      dataIndex: 'rect',
      defaultSortOrder: 'descend',
      align: 'left',
      width: 110,
      ...getColumnSearchProps('rect'),
    },
]
```

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | React |
| System | Linux Ubuntu  |
| Browser | Chrome |

**Comment by afc163** [comment]
react-window cannot work with custom filterDropdown now.

**Comment by nimahkh** [comment]
> react-window cannot work with custom filterDropdown now.

what about react-virtualized ?
