### ISSUE TITLE
Antd Upgrade to 4.16.3 version, the size increased by 800kb after packaging 

### ISSUE THREAD

**Issue by mizhousoft** [ant-design/ant-design#31019]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mizhousoft/mizhousoft-bmc/tree/main/bmc-nodejs](https://github.com/mizhousoft/mizhousoft-bmc/tree/main/bmc-nodejs)

### Steps to reproduce
execute the command: npm run build

### What is expected?
I hope that Output bundle size is 900kb 

### What is actually happening?
Output bundle size: 296-e5d9aeaab5.js (1.67 MiB)

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 17.0.2 |
| System | nodejs v12.18.3 |
| Browser | edge |

---
I upgraded react antd from 4.15.1 to the latest version 4.16.3. After packaging, I found that bunlde.js increased by 800Kb. I found that it was caused by @ant-design/icons, but I did not upgrade @ant-design/icons

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/pull/31011

**Comment by afc163** [comment]
Fixed in #31011
