### ISSUE TITLE
form表单调用setFieldsValue方法不能为TextArea组件设置false值

### ISSUE THREAD

**Issue by wwwxy80s** [ant-design/ant-design#31020]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaodanfangfadiaoyong-antd4163-forked-4ceqp?file=/index.js)

### Steps to reproduce
点击Fill form 

### What is expected?
textArea2组件能够将false的value设置进去

### What is actually happening?
textArea2组件赋值false失败

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.14.0 |
| System | macOS |
| Browser | chrome 91.0.4472.106 |

---
项目中使用v3表单调用setFields函数设置一个变值（包含false值）到v4的TextArea组件里，v4.9.4版本可以设置进去，升级到v4.16.3不能设置成功

**Comment by imhxc** [comment]
按照文档规范，Input 接收的 value 应该是一个 stirng 类型的。

**Comment by afc163** [comment]
测试了原生组件，应该也不支持 boolean 类型，建议转成 string。

**Comment by wwwxy80s** [comment]
ok，了解了

> 测试了原生组件也不支持 boolean 类型，建议转成 string。

**Comment by wwwxy80s** [comment]
简单补个文档，应该是这个吧🤔
[HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#properties)
![image](https://user-images.githubusercontent.com/12374094/122376366-abd77400-cf96-11eb-8bc3-ce263f3b2aa4.png)
