### ISSUE TITLE
InputNumber 输入框最大值和最小值的限制

### ISSUE THREAD

**Issue by weborockfeller** [ant-design/ant-design#31021]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
InputNumber 输入框 在设置最大值后还是可以输入超过最大值，在失焦之后才会把值置为最大值，能不能在onChange事件监听，直接堵住输入超过最大值的这个入口

### What does the proposed API look like?
onblur事件改为onChange 或者 onInput

**Comment by afc163** [comment]
可以用受控模式自行封装这个逻辑。
