### ISSUE TITLE
表单问题

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3102]
this.props.form.getFieldsValue()方法必须要Form.create之后才能获取到表单数据，但是使用了Form.create之后，给子组件ref，父组件通过ref调用子组件的方法这种做法失效，控制台报错的是把要调用的子组件方法当成了一个表单属性无法识别。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by RifeWang** [comment]
http://codepen.io/RifeWang/pen/PGbQdx

**Comment by benjycui** [comment]
这个演示有语法问题。

**Comment by RifeWang** [comment]
能否具体指出。。我是想在最外层组件中通过ref调用到最里层组件返回数据的方法。

**Comment by RifeWang** [comment]
@benjycui 那个getFieldProps和ref冲突的刚刚改了一下，可以从最外层组件进入下一层了，但还是无法进入最里层，请问连续调用this.refs访问里层方法时，this的指向是怎么样的，我用了组件名称替代了this也是有问题的

**Comment by RifeWang** [comment]
http://codepen.io/RifeWang/pen/VKmQGQ  Form.create与this.refs冲突了，无法使用this.props.form.getFieldsValue()方法，请问该怎么取到最里层组件的值？

**Comment by benjycui** [comment]
http://beta.ant.design/components/table/#components-table-demo-grouping-columns

**Comment by RifeWang** [comment]
antd的组件虽好，但并不能完美契合个人的业务需求，某些时候只能重复造轮子
