### ISSUE TITLE
日期、时间选择器初始会置中

### ISSUE THREAD

**Issue by crimsonpython24** [ant-design/ant-design#31026]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-multi-step-form-forked-6hm7t?file=/src/components/Step1.js)

### Steps to reproduce
1. 点开 CSB 链接，去 Step1.js 第 69 行
2. 旁边的显示器里面 Event Date 的日期选择器会置中（请确认标题是 “test title” 后面没有任何数字）

### What is expected?
日期选择器会靠左，跟其他的输入格一样。

### What is actually happening?
日期选择器会置中（所以左边会有一点间距）。

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | React 16.8.6 |
| System | CodeSandbox |
| Browser | Edge |

**Comment by afc163** [comment]
```diff
.App {
  font-family: sans-serif;
- text-align: center;
}
body {
  margin: 0 auto;
}
```

https://codesandbox.io/s/react-multi-step-form-forked-6hm7t?file=/src/styles.css:34-56

**Comment by crimsonpython24** [comment]
附加一个问题：
![image](https://user-images.githubusercontent.com/76871022/122374070-a37e3980-cf94-11eb-863c-545af7bcb657.png)

请问要怎么把后面的空间补足？

希望能跟上面两个输入个一样，而不是直接给 width=100px 之类的

**Comment by yoyo837** [comment]
`Form` 和 `Form.Item`的
`wrapperCol`
`labelCol`

**Comment by afc163** [comment]
加上 `style={{ width: '100%' }}`。
