### ISSUE TITLE
Collapse 组件在 collapsible='header' 模式下点击图标无法收起展开

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#31039]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/collapse-cn/#components-collapse-demo-collapsible](https://ant.design/components/collapse-cn/#components-collapse-demo-collapsible)

### Steps to reproduce
https://ant.design/components/collapse-cn/#components-collapse-demo-collapsible

### What is expected?
点击图标能够收起展开

### What is actually happening?
点击图标不能收起展开

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | MAC |
| Browser | CHROME |

**Comment by xrkffgg** [comment]
看起来像是设计

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26752#issuecomment-692757260

@Dolov 回答一下

**Comment by afc163** [comment]
诶，这个 https://github.com/react-component/collapse/pull/164 最早就是楼主加的，好像点击区域不包括 arrow。

**Comment by xrkffgg** [comment]
https://github.com/react-component/collapse/pull/167

**Comment by Dolov** [comment]
> 诶，这个 [react-component/collapse#164](https://github.com/react-component/collapse/pull/164) 最早就是楼主加的，好像点击区域不包括 arrow。

嗯嗯 之前是提过这个pr 在点击文本的时候收起展开，前几天产品那边提要求认为点击图标也应该收起展开，我能提个 pr 么，从设计上图标应该不应该能够触发收起展开呢

**Comment by xrkffgg** [comment]
那直接去掉 `collapsible='header'` 就好了啊

**Comment by Dolov** [comment]
> 那直接去掉 `collapsible='header'` 就好了啊

可能是我没表达清楚，我是想实现的是 collapsible=header 时文字和 arrow 可以响应收起展开，如图
![image](https://user-images.githubusercontent.com/19704420/122695521-2a703200-d273-11eb-80e5-54821248ae0a.png)
不知道这样可以不 😊

**Comment by xrkffgg** [comment]
。。。你为啥要加上 collapsible='header' 呢？

**Comment by Dolov** [comment]
> 。。。你为啥要加上 collapsible='header' 呢？

如果不加的话，用户点击到空白区域也会触发收起展开，很容易误操作。
![image](https://user-images.githubusercontent.com/19704420/122698485-fb10f380-d279-11eb-869e-31e2b07db56d.png)

**Comment by xrkffgg** [comment]
噢噢，你的想法是 点击区域 除了 head 再加上前面的 按钮啊

**Comment by Dolov** [comment]
> 噢噢，你的想法是 点击区域 除了 head 再加上前面的 按钮啊

嗯啊

**Comment by Dolov** [comment]
@xrkffgg 提交了一个 https://github.com/react-component/collapse/pull/215  😁

**Comment by afc163** [comment]
@Dolov 可以再加个 `collapsible="icon"`：https://github.com/ant-design/ant-design/issues/31969

**Comment by edrmsgl** [comment]
You wrote that you support collapsible="icon", but in the version I am using "export declare type CollapsibleType = 'header' | 'disabled';" allows use. I am using the below version. Do I need to upgrade?

Version => "antd": "^4.9.2",

**Comment by smithyj** [comment]
@afc163 `antd:4.17.2 ` 并没有看到这个 `collapsible` 支持 `icon`

**Comment by theDoinb** [comment]
collapsible 能支持 Icon吗？ 有时需要在header加些操作，例如点击name出现input修改name之类的，不希望它能点击header触发收缩，类似这种需求比较常见
