### ISSUE TITLE
renderExtraFooter breaks input elements

### ISSUE THREAD

**Issue by denisk20** [ant-design/ant-design#31032]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/extra-footer-antd4162-forked-mvz3h)

### Steps to reproduce
Put an `<input />` inside a `renderExtraFooter` of a `DatePicker` or a `RangePicker`. Open a picker and try to focus the input and write something

### What is expected?
Input is responsive (you can type there)

### What is actually happening?
Input not responsive.

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.14.0 |
| System | MacOS |
| Browser | Chrome |

---
If you right-click on the input you can focus on it and type, but you can't unfocus.

**Comment by denisk20** [comment]
Is this a joke? There's a link to the sandbox in the ticket.

**Comment by afc163** [comment]
There is no `<input />` found in your sandbox.

**Comment by afc163** [comment]
Focusing input will blur picker input, cause panel disappear. I can't find property way to handle this situation.

cc @zombieJ

**Comment by denisk20** [comment]
@afc163 I can control the visibility of the panel myself with `open` property, it shouldn't disappear in this case.

**Comment by afc163** [comment]
In that case you can try `renderExtraFooter={<div onMouseDown={e => e.stopPropagation()}><input /></div>}` for focus thing.

**Comment by denisk20** [comment]
@afc163 this works! Thank you very much!
