### ISSUE TITLE
Addition of disabled video svg icon

### ISSUE THREAD

**Issue by sanketshevkar** [ant-design/ant-design#31033]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For video conferencing apps the icon for disabled video is useful similar to muted audio.

### What does the proposed API look like?
A new icon component is to be developed

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/issues/71#issuecomment-863735956
