### ISSUE TITLE
Menu.ItemGroup when divided into component mounts more than once

### ISSUE THREAD

**Issue by dibyn** [ant-design/ant-design#31041]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd4163-forked-6c3ib)

### Steps to reproduce
Open react-dev-tools and inspects into menu component.
also on console, log placed in React.useEffect of Child Component of Menu ItemGroup is called multiple times when menu is toggled.

### What is expected?
I should be able to divided the Menu ItemGroup into separate component and expect to work normally as it should. 
Mounting demounting should work properly. 
React UseEffect should be called only once.  

### What is actually happening?
Here ChildMenuGroup_key is mounted twice.

Context.Provider
▾ InheritableContextProvider ✓ Context.Provider
✓ Context.Provider
Overflow ForwardRef
Context.Provider key="0"
▸ ChildMenuGroup_key="tmp_key ▸ Context. Provider key="1"
▸ Context.Provider key="2"
- Context.Provider
▸ ChildMenuGroup_key="tmp_key-0"
▸ MenuItem key="tmp_key-1"
▸ MenuItem key="tmp_key-2"

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.14.0 |
| System | MacOS |
| Browser | Brave: Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (x86_64) |

**Comment by riten7** [comment]
any update on this issue ?  I have also came across this issue after updating ant design yo latest version.. Menu component is rendered twice on the screen..

**Comment by zombieJ** [comment]
To support HOC of Menu. sub component will render twice to collect structure. It's by design:

https://github.com/react-component/menu/blob/f4684514096d6b7123339cbe72e7b0f68db0bce2/src/Menu.tsx#L542

**Comment by dibyn** [comment]
Is there other ways to resolve this?
