### ISSUE TITLE
单选按钮组如何实现确认按钮？

### ISSUE THREAD

**Issue by Witee** [ant-design/ant-design#3104]
以下是确认的实现：
import { Popconfirm, message } from 'antd';

function confirm() {
  message.success('点击了确定');
}

function cancel() {
  message.error('点击了取消');
}

ReactDOM.render(
  <Popconfirm title="确定要删除这个任务吗？" onConfirm={confirm} onCancel={cancel}>
    <a href="#">删除</a>
  </Popconfirm>
, mountNode);

=================
如果想在单选按钮组中实现这个？如何做？
<RadioGroup onChange={this.onChange} value={this.state.value}>
        <Radio key="a" value={1}>A</Radio>
        <Radio key="b" value={2}>B</Radio>
        <Radio key="c" value={3}>C</Radio>
        <Radio key="d" value={4}>D</Radio>
</RadioGroup>
也就是点击每个 Radio 时出现“确认”按钮

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.
