### ISSUE TITLE
新的搜索功能   弹框问题

### ISSUE THREAD

**Issue by Super-XXX** [ant-design/ant-design#31040]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
唤起搜索框  点击上键  页面崩溃   url undefined

### What is expected?
不崩呗

### What is actually happening?
页面崩溃

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | react16.12.0 |
| System | win10 |
| Browser | Google Chrome91.0.4472.101 |

**Comment by vagusX** [comment]
看了下主要是因为使用的外部组件 `@docsearch/react/modal` 内部有一个函数调用报错了

![image](https://user-images.githubusercontent.com/6828924/122872471-14419f00-d363-11eb-9386-d7e893747979.png)

![image](https://user-images.githubusercontent.com/6828924/122872490-199ee980-d363-11eb-87aa-b020e847b553.png)

**Comment by vagusX** [comment]
https://github.com/ant-design/ant-design/issues/31040

**Comment by vagusX** [comment]
https://github.com/facebook/docusaurus/issues/5031

**Comment by afc163** [comment]
@vagusX 貌似已经发版了。

**Comment by vagusX** [comment]
并没有真的修复，还要等这个 PR 合并，https://github.com/algolia/autocomplete/pull/623/files

据说本周会发版本

**Comment by vagusX** [comment]
上游已发版本，下午PR修复
