### ISSUE TITLE
Enable to select year, month, and day in this order.

### ISSUE THREAD

**Issue by tatane616** [ant-design/ant-design#31058]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Improve user experience.
On DatePicker, most of users would want to select the *year* first, then the *month*, and finally the *day*.
But for now, they come back to the day panel after they select the year, so they need to open month panel by clicking month in header.

### What does the proposed API look like?
Add new mode or flag to DatePicker's props.
If it's enabled, users can select year, month, and day in this order.

**Comment by afc163** [comment]
You may have to customize it by youself.

**Comment by martinlistiak** [comment]
I would love to see this feature too.
