### ISSUE TITLE
show useLayoutEffect console warning when using with nextjs ssr

### ISSUE THREAD

**Issue by SreenathMP** [ant-design/ant-design#31050]
![image](https://user-images.githubusercontent.com/40138285/122555425-eb19c980-d057-11eb-8560-67a15e3bf12a.png)
antd with nextjs ssr
show useLayoutEffect console warning when using with nextjs, I am using antd Layout component, I think issue is with layout component. Any way to get rid of this warning.

Version
 "antd": "^4.16.3",
"next": "10.2.3",
"react": "17.0.2",
"react-dom": "17.0.2",

**Comment by yoyo837** [comment]
ant-design/ant-design#30396
