### ISSUE TITLE
Tree树型控件拖动的时候总是打开新窗口

### ISSUE THREAD

**Issue by mylesshie** [ant-design/ant-design#3105]
#### 发生问题的环境是：

官网treeDemo拖动

- antd 版本:官网例子
- 操作系统及其版本:win7
- 浏览器及其版本:chrome52

#### 您做了什么？

拖动节点排序
#### 您期待的结果是：
不打开新标签页

#### 实际上的结果是：

拖动节点排序时浏览器总会打开新的标签页，怎么阻止？
![image](https://cloud.githubusercontent.com/assets/4142212/18700947/92255754-800c-11e6-9b0a-f4535c4195ea.png)

#### 可重现的在线演示

http://ant.design/components/tree/

**Comment by warmhug** [comment]
chrome 升级到 53
