### ISSUE TITLE
Can no longer have <img> inside a Menu starting with antd 4.16.0

### ISSUE THREAD

**Issue by Karin-Basis** [ant-design/ant-design#31055]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Karin-Basis/antd-menu-img-bug](https://github.com/Karin-Basis/antd-menu-img-bug)

### Steps to reproduce
yarn install
yarn start

### What is expected?
Menu items "Item1", "Item2", "Item3" should appear

### What is actually happening?
Only the logo shows up.  

The console log displays
"Warning: React does not recognize the `eventKey` prop on a DOM element...." and
"Warning: React does not recognize the `warnKey` prop on a DOM element....."

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.2 |
| System | macOS High Sierra |
| Browser | Chrome 91.0.4472.106 |

---
Downgrading to antd 4.15.5 will make the app work.

**Comment by zombieJ** [comment]
Menu only accept Menu.* or HOC of them as children node. img is not a validate children element.

ref: https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element

**Comment by jailsonpaca** [comment]
I fix with this:

https://github.com/ant-design/ant-design/issues/31025#issuecomment-893674980

**Comment by Mihai-github** [comment]
> Menu only accept Menu.* or HOC of them as children node. img is not a validate children element.
> 
> ref: https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element


Hi,

     I only use the Menu.Item with <a /> tag as it's children and I am still getting the warning "Warning: React does not recognize the `warnKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `warnkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element."

Has anyone found another way to fix this issue?
