### ISSUE TITLE
Remove non-clickable areas (vertical margins) between menu items in vertical menu

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#31056]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There's a certain space between menu items in a vertical menu. Sometimes it can be really annoying when you've clicked a link but nothing happened because you click right in this small area. My suggestion is to rework styles (remove margins) so that wouldn't happen.

### What does the proposed API look like?
No API changes suggested

**Comment by afc163** [comment]
It is by designed.
