### ISSUE TITLE
Should not put React Element in state

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3106]
Demo: http://beta.ant.design/components/auto-complete/#components-auto-complete-demo-options

> https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#what-should-go-in-state

And `AutoComponent.Option` should be placed as AutoComponent's children

**Comment by afc163** [comment]
```
<AutoComplete>
   <Option />
   <Option />
   <Option />
</AutoComplete>
```

这样是不是更合理一点。

**Comment by benjycui** [comment]
也对。。
