### ISSUE TITLE
【v4.16.3】menu 组件子菜单项鼠标悬停变色样式丢失

### ISSUE THREAD

**Issue by liyupi** [ant-design/ant-design#31069]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu](https://ant.design/components/menu)

### Steps to reproduce
鼠标悬停到子菜单项

### What is expected?
变色

### What is actually happening?
未变色

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome |

---
经验证，v4.16.2 是正常的，应该是 4.16.3 fix menu 高亮样式冲突时搞崩了？
💄 修复 Menu 暗色模式下，部分样式被亮色模式污染的问题。#30907

**Comment by afc163** [comment]
> 变色

变色指的是什么意思？

我只发现一个问题，hover 变色时 transition 渐变动画没了。

**Comment by hoho2017** [comment]
> 这次 commit 的 components/menu/style/index.less 文件，删除了默认主题的菜单 Active 样式
> https://github.com/ant-design/ant-design/pull/30907/files
