### ISSUE TITLE
using Collapse with datasource 折叠面板增加datasource属性

### ISSUE THREAD

**Issue by KillingMeNow** [ant-design/ant-design#31062]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
根据datasource生成折叠面板

### What does the proposed API look like?
使用场景为 类似Q&A页面，希望直接提供datasource给组件

**Comment by afc163** [comment]
暂不提供，建议自行封装上层组件。
