### ISSUE TITLE
treeselect限定高度出现2个滚动条

### ISSUE THREAD

**Issue by nlx0201** [ant-design/ant-design#31065]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jwl2m?file=/index.js)

### Steps to reproduce
1. 官网使用说明中找到最后treeselect的组件的实例
2. 设置treeselect的max-height

### What is expected?
只出现一个滚动条，并且一直可见

### What is actually happening?
滚动鼠标时出现一个滚动条ant-select-tree-list-scrollbar-thumb

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 17.2 |
| System | windows 10 |
| Browser | Chrome 91 |

**Comment by nlx0201** [comment]
特别注意的是，在触摸屏电脑上面这种滚动条是无效的

**Comment by nlx0201** [comment]
> Hello @nlx0201. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @nlx0201, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

reproduction as below link:
https://codesandbox.io/s/antd-reproduction-template-forked-jwl2m?file=/index.js

**Comment by afc163** [comment]
```
-       dropdownStyle={{ maxHeight: 200, overflow: "auto" }}
+       height={200}
```

**Comment by nlx0201** [comment]
> ```diff
> -       dropdownStyle={{ maxHeight: 200, overflow: "auto" }}
> +       height={200}
> ```

如果高度不足200，限定200的话，空白区域就冗余了

**Comment by afc163** [comment]
@zombieJ 是否有 maxHeight 的支持？
