### ISSUE TITLE
TreeSelect数据更新的时候，dom没有更新。

### ISSUE THREAD

**Issue by xueqingxiao** [ant-design/ant-design#3107]
我在[codepen](http://codepen.io/xueqingxiao/pen/zKoWJj)中重现了这个bug，请帮忙看下为什么。

**Comment by xueqingxiao** [comment]
@afc163 @benjycui Take a look, Please.

**Comment by afc163** [comment]
http://codepen.io/afc163/pen/BLQVLP?editors=0010

http://www.bennadel.com/blog/2903-why-should-i-care-about-immutable-data-in-reactjs.htm

**Comment by xueqingxiao** [comment]
@afc163 Thank you very much.

**Comment by aw6658913** [comment]
添加完新的数据，treeData数据更新了，操作状态怎么没更新，理论上来说，数据重新渲染了，状态不是也应该更新，不然这样要是换全新的一组数据不是会有问题？
