### ISSUE TITLE
In depth documentation on dropdown customization using dropdownRender for <Select> tag, especially when using mode="tags"

### ISSUE THREAD

**Issue by sweetphilosophy** [ant-design/ant-design#31074]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In my application I need to do something similar to this: https://imgur.com/a/CsyygCz , basically to add a helper text next to the new option created from the input when the Select mode="tags"
The dropdownRender handler is the close that I got to customize this, however I can't wrap my head around how to use it. All the examples I have found are showing only how to add more after the already given dropdown (which comes as param). Unfortunately I couldn't find more info about customizing further. I have tried editing and messing with the menu param which I get in that function, but nothing seems to work and I'm also getting errors such as not being able to edit read-only objects (which is expected). In this function the menu param comes with the newly added option in the dropdown so I think I should be able to edit its label before returning it.

I just feel like I'm really close but can't really touch the solution.

### What does the proposed API look like?
More documentation specifically on this.

### Reproduction link
https://codesandbox.io/s/antd-reproduction-template-forked-4oowy?file=/index.js

**Comment by sweetphilosophy** [comment]
> Hello @sweetphilosophy. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @sweetphilosophy, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

Hello,
I have added the reproduction in the link below: https://codesandbox.io/s/antd-reproduction-template-forked-4oowy?file=/index.js

**Comment by afc163** [comment]
We could add a `createTagRender` to https://github.com/react-component/select , could you help to create a PR for that?
