### ISSUE TITLE
Support the ability to get dataIndex in the form render function(在表格render函数中支持获取dataIndex的能力)

### ISSUE THREAD

**Issue by flyingCrp** [ant-design/ant-design#31079]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决动态表头自定义渲染时需要显示相同dataIndex的嵌套对象的属性值的场景:
Solve the scenario where the attribute value of the nested object of the same dataIndex needs to be displayed when the dynamic header is customized

eg:

```
const dataRow={name:"skirt",orignalSize:"{S:2,M:5,L:10}",adoptSize:"{S:1,M:0}"}

render:

name  |  S   |  M  |      L  |  
------------------------------------
skirt | 2/1  | 5/0 |  10/0   |

```

### What does the proposed API look like?
{
   render:(value,recort,index,column)=>{}
}

**Comment by afc163** [comment]
声明 column 的时候已经知道是哪一列了，这个属性是多余的。
