### ISSUE TITLE
antd table 多选异步分页，preserveSelectedRowKeys也为true，但是selectedRowKeys与selectedRows却不同步

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design#31075]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/zealous-gates-nocwy?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1、设置preserveSelectedRowKeys=true
2、表格复选框：第1页有一条默认选中；点击第2页，单击选中一条数据。
3、打开控制台，观察demo中selectedRowKeys与selectedRows中的数据

### What is expected?
希望selectedRowKeys与selectedRows同步，且上一页的数据在selectedRows中不丢失

### What is actually happening?
selectedRowKeys与selectedRows不同步，但selectedRowKeys是对的。

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | latest |
| System | win10 |
| Browser | Chrome80.0.3987.132 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2764#issuecomment-241686288

**Comment by wooxyz** [comment]
请问，您认真的试过了吗？
```
rowSelection: {
  selectedRowKeys,
  preserveSelectedRowKeys: true,
  onChange: (keys,rows) => {
    // 即使是异步模式，keys与rows不能保持一致？？？
    this.setState({
      selectedRows: rows,
      selectedRowKeys: keys,
    })
  },
},
```
step1：去掉表格默认选中项：将提供的例子(src/App.js下第37行由`<List selectedIds={["001"]} />`改为`<List selectedIds={[]} />`)
step2:：在第一页选中1个，再在第二页选中1个，为何`rowSelection的onChange函数中，其参数keys与rows却出奇的保持一致？`。真实项目中，异步模式下，设置preserveSelectedRowKeys为true，selectedRows与selectedRowKeys也是同步的。

难道就是因为默认选中了一条，就不行了？我想不通。。。 @afc163

**Comment by afc163** [comment]
@wooxyz 看上去和 https://github.com/ant-design/ant-design/issues/30482#issuecomment-845611573 是同一个问题？

**Comment by wooxyz** [comment]
> @wooxyz 看上去和 [#30482 (comment)](https://github.com/ant-design/ant-design/issues/30482#issuecomment-845611573) 是同一个问题？

 显然不大像，我的不是树形数据，且只与 preserveSelectedRowKeys 设为 true相关，应该是个 bug。

**Comment by afc163** [comment]
先 reopen 吧，最近没太多时间细看。

**Comment by webLion200** [comment]
> 先 reopen 吧，最近没太多时间细看，欢迎来 PR。

我也遇到了，请静快修复吧

**Comment by baibaibai455** [comment]
这个问题好像又出现了，我之前是可以的 ，最近升级        "antd": "^4.24.3",
又出现这个问题

**Comment by liangskyli** [comment]
这个问题又出现了, 版本4.24.13

**Comment by zhenghuanhuan** [comment]
"@ant-design/pro-components": "^2.8.2",  "antd": "^5.4.0", 这个问题又出了
