### ISSUE TITLE
Drawer抽屉   使用 touch 报错

### ISSUE THREAD

**Issue by dataangel** [ant-design/ant-design#31076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce
点击 open F12 打开设备仿真 然后拖动打开的区域 开始报：Unable to preventDefault inside passive event listener invocation.

### What is expected?
拖动打开的区域没有报错

### What is actually happening?
报错：Unable to preventDefault inside passive event listener invocation.

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 7.0.3 |
| System | win 10  |
| Browser | Chrome |

![image](https://user-images.githubusercontent.com/587849/122853199-6a531a00-d344-11eb-8dcc-ecb4741b00b1.png)

**Comment by kerm1it** [comment]
https://developers.google.cn/web/updates/2017/01/scrolling-intervention 看看这个博客

移动端默认设置了 passive event，此时 preventDefault 是无效的，目前 antd 专注于 PC 端，没有针对移动端做这方面的处理。
