### ISSUE TITLE
Initially, no vertical scroll bar is visible, even if data doesn't fit in dropdown

### ISSUE THREAD

**Issue by gmoniava** [ant-design/ant-design#31073]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-gghei6](https://stackblitz.com/edit/react-gghei6)

### Steps to reproduce
Just click tree select and look at dropdown

### What is expected?
Initially if content doesn't fit, vertical scroll should be visible

### What is actually happening?
Initially, no vertical scroll bar is visible, even if data doesn't fit in dropdown. If I manually click scroll btn on mouse, then the scroll bar appears. 

| Environment | Info |
|---|---|
| antd | 4.16.3|
| React | 16 |
| System | Windows |
| Browser | Chrome |

---
This is bad because when user initially won't see scroll, she may think there is no more data. Screenshot https://ibb.co/921RPQk

**Comment by afc163** [comment]
It is by designed, trace #28074 for further feature about it.
