### ISSUE TITLE
InputNumber input bug

### ISSUE THREAD

**Issue by jixindong** [ant-design/ant-design#31084]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4163-forked-2f2p1)

### Steps to reproduce
切换输入法为中文
按下句号键

### What is expected?
输入中文句号就显示一个英文的.

### What is actually happening?
输入中文句号就显示两个英文的.

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chrome  88.0.4324.96 |

**Comment by afc163** [comment]
微软输入法么，应该是这个问题 https://github.com/ant-design/ant-design/issues/27748。
