### ISSUE TITLE
table组件的表头能够定制吗

### ISSUE THREAD

**Issue by asoqa** [ant-design/ant-design#3108]
#### 发生问题的环境是：

- antd 版本:1.9.1
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？
能否对表头也能进行合并，如下图

[
![2016-09-21 4 41 32](https://cloud.githubusercontent.com/assets/2541822/18703877/61136f9e-801a-11e6-9cf2-eb777e093f27.png)
](url)

**Comment by benjycui** [comment]
Try antd@2.0.0-beta

http://beta.ant.design/components/table/#components-table-demo-grouping-columns

**Comment by asoqa** [comment]
回复好快！👍

**Comment by ystarlongzi** [comment]
@benjycui 
2.0 现在用到生产环境中去，问题应该不大吧。我这里项目也需要到表格头自定义的功能

**Comment by benjycui** [comment]
明天发正式版，然后其实社区已经有几个项目提前使用了。

**Comment by ystarlongzi** [comment]
大写的👍
