### ISSUE TITLE
穿梭框如何自定义左右footer？

### ISSUE THREAD

**Issue by yatingFeng** [ant-design/ant-design#31089]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不太通用哦

### What does the proposed API look like?
穿梭框可以支持同时设置左右footer，而不是一个footer同时作用在

**Comment by afc163** [comment]
Duplicate of #28082
