### ISSUE TITLE
tree以及treeSelect 返回格式为树

### ISSUE THREAD

**Issue by smallbaoo** [ant-design/ant-design#31082]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的tree中返回的格式，如果有复选框的情况，选中了全选了子集，就会选中父级，获取的值也是父级的，而不包含子集的

### What does the proposed API look like?
初始化tree数据是一棵树状结构的，那么我们勾选后，返回的也希望提供一个和传入的时候一样的数据格式，同时筛选出已经勾选的数据
![image](https://user-images.githubusercontent.com/34156483/122900362-33e6c080-d37f-11eb-98db-a99f97527170.png)
正如官网例子，我们希望返回的是一个树状结构：
[{
    title: 'Node2',
    value: '0-1',
    key: '0-1',
    children: [
      {
        title: 'Child Node3',
        value: '0-1-0',
        key: '0-1-0',
      },
      {
        title: 'Child Node4',
        value: '0-1-1',
        key: '0-1-1',
      },
      {
        title: 'Child Node5',
        value: '0-1-2',
        key: '0-1-2',
      },
    ],
  }]

而不是单单的一个简单的数组
![image](https://user-images.githubusercontent.com/34156483/122900656-75776b80-d37f-11eb-95bf-b1a31a3dce03.png)

**Comment by afc163** [comment]
你需要自行从数据中筛选出所需的结构。
