### ISSUE TITLE
DatePicker不能受控

### ISSUE THREAD

**Issue by eightHundreds** [ant-design/ant-design#31099]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-hypatia-5u1vx?file=/index.js)

### Steps to reproduce
选择日期

### What is expected?
期望两个时间范围都没有分,秒

### What is actually happening?
两个时间范围都带上当前时间的分,秒

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.14.0 |
| System | mac 2020 m1 |
| Browser | edge最新 |

**Comment by afc163** [comment]
https://codesandbox.io/s/priceless-tree-06puw

**Comment by eightHundreds** [comment]
不错的障眼法
