### ISSUE TITLE
Popover里面包Badge导致Popover不可用

### ISSUE THREAD

**Issue by yimi8126** [ant-design/ant-design#3109]
用popover做了一个购物车，按钮可以显示购物车里面的数量，所以使用了badge，之前用的好好的，这次升级了antd的版本，就不可用了，点击popover后不能弹出框了。

http://codepen.io/yimi8126/pen/YGpjqJ

去掉Badge后可以用

**Comment by benjycui** [comment]
先交换两者的位置解决。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/45db4cab504468cdc893ead66eeb6a903c79aa5f

1.7.0 里改挂了。

**Comment by afc163** [comment]
会在 1.11.2 和 2.x 上进行修复。

建议报告问题详细一些，按照[模板](https://github.com/ant-design/ant-design/issues/new)来回答问题，提供版本信息和重现步骤，这样我们排查起来会快很多。

**Comment by yimi8126** [comment]
交换位置OK了

**Comment by and80506** [comment]
同遇到该问题，Tooltip也有这个问题，只要包的是react组件就有问题，纯DOM节点没问题。
