### ISSUE TITLE
Ant has an undocumented peer dependency on dayjs

### ISSUE THREAD

**Issue by kaiyoma** [ant-design/ant-design#31096]
### Steps to reproduce
This issue was originally reported here: https://github.com/ant-design/ant-design/issues/23435

However, it was closed and never actually fixed. I'm running into this problem again, so I'm opening a new issue.

If I try to install the latest version of Ant with pnpm, I get an error and package installation fails:

```
ERROR  antd: rc-picker@2.5.12 requires a peer of dayjs@^1.8.30 but none was installed.
```

Adding `dayjs` to my package.json fixes the issue, but this requirement isn't documented in Ant's peer dependencies:

```
  "peerDependencies": {
    "react": ">=16.9.0",
    "react-dom": ">=16.9.0"
  },
```

### What is expected?
The `dayjs` package should be provided internally by Ant, or the peer dependency should be documented in package.json.

### What is actually happening?
An unexpected peer dependency is appearing, causing package installation to fail.

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 17.0.2 |
| System | Any |
| Browser | Any |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/23435#issuecomment-775643355

**Comment by kaiyoma** [comment]
I don't see how this answers the question. dayjs is not listed as a peer dependency: https://github.com/ant-design/ant-design/blob/master/package.json#L284
