### ISSUE TITLE
Keyboard accessible drawer regions

### ISSUE THREAD

**Issue by timgrant-philly** [ant-design/ant-design#31094]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, when a drawer region (typically, the body) has a scrollbar, the scrollbar can only be accessed with the mouse, not the keyboard. Scrollable regions need to be able to acquire keyboard focus.
https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/#:~:text=When%20a%20page%20includes%20content,associated%20with%20the%20scrollable%20element.&text=(An%20element%20is%20focusable%20if,mousing%2C%20or%20keyboard%20tabbing.)

### What does the proposed API look like?
Render a `tabindex="0"` to the `ant-drawer-body` element -- and to other scrollable regions. (Having the option to set a tabindex would solve the immediate problem, as well.)

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/200220103-91948e1f-3bde-4b3c-8269-882c978132ce.png">

Supported.
