### ISSUE TITLE
Ant Table Fixed header scrolling animation was not sync when scrolling on IOS safari 14.4

### ISSUE THREAD

**Issue by trinhthinh388** [ant-design/ant-design#31098]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fjkj4?file=/index.js:0-1913)

### Steps to reproduce
Just scroll!

### What is expected?
The header scrolling animation is sync perfectly with the body.

### What is actually happening?
The header scrolling animation was not sync with the body.
[https://streamable.com/63zd49](url)

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.13.1 |
| System | IOS 14.4 |
| Browser | Safari 14.4 |

---
Please let me know if you guys know what the problem is. Thank u!

**Comment by long-zhuge** [comment]
same problem

**Comment by cassedy27** [comment]
I believe this is due to [this](https://github.com/react-component/table/issues/525) performance issue

**Comment by afc163** [comment]
@trinhthinh388 Could you check out the latest antd version?

**Comment by trinhthinh388** [comment]
> @trinhthinh388 Could you check out the latest antd version?

Hi!
it works perfectly now
