### ISSUE TITLE
Menu item cannot be right aligned after upgrade to 4.16.3

### ISSUE THREAD

**Issue by xpenxpen** [ant-design/ant-design#31097]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lkihq?file=/index.js)

### Steps to reproduce
style={{ float: "right" }} is applied, however, menu item is not right aligned.
It is OK in antdesign 4.16.0
On the left, change version to 4.16.0, it is correctly right aligned.

### What is expected?
menu item is right aligned

### What is actually happening?
Version 4.16.0 is OK.
4.16.3 not OK.

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | FireFox 89 |

**Comment by afc163** [comment]
See https://stackoverflow.com/a/39194668/3040605
