### ISSUE TITLE
message不能显示React Intl FormattedMessage的内容

### ISSUE THREAD

**Issue by nie-xin** [ant-design/ant-design#3110]
antd 版本: 1.11.0
操作系统及其版本: mac os
浏览器及其版本: chrome & firefox

 使用[react intl](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage)进行翻译：

```
 const msg = <FormattedMessage id={'messages.mandateDetails.revoke.success'} />
 message.success(msg)
```

结果无法触发message，尝试直接传递string和简单react element都可以正常触发。

FormattedMessage返回的也是一个React element:

![capture d ecran 2016-09-21 a 10 42 42](https://cloud.githubusercontent.com/assets/3535692/18703912/300cf64a-7fe8-11e6-9760-8678ff9f4339.png)

做了个小实验：http://codepen.io/niexin/pen/dpOKmk

应该是antd的组件没有被IntlProvider wrap, 所以无法顺利完成组件：

```
VM2070 react-intl.min.js:2 Uncaught Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
```

请问该如何配合整合antd和react intl呢？如何传递IntlProvider给所有antd组件？

**Comment by benjycui** [comment]
See: https://github.com/yahoo/react-intl/issues/157

**Comment by benjycui** [comment]
Simple one: https://github.com/ant-design/intl-example/blob/master/docs/react-intl-corner-cases.md

**Comment by nie-xin** [comment]
非常感谢！
