### ISSUE TITLE
Antd not compatible with @testing-library/userEvents@13

### ISSUE THREAD

**Issue by fragsalat** [ant-design/ant-design#31105]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-pointer-events-cgqy0?file=/index.js)

### Steps to reproduce
1. Having a test setup with @testing-library
2. Render a Select component (or any other using rc-trigger)
3. Open the select by firing a mouseDown event
4. Try to select the option using userEvent.click
5. This fails as the latest version of userEvent.click throws an error when the element is not clickable because of pointer-events

### What is expected?
The components are rendered without pointer-events even when transitions / animations are not fully supported like it is the case for JSDom.

### What is actually happening?
The ant select component is rendered which uses rc-select which then uses rc-trigger under the hood. The rc-trigger module adds pointerEvents: none to the div.ant-select-dropdown while it is not animated to the end. Because JSDom is not fully supporting animations and transitions the status never becomes "stable" and therefore pointerEvents are never removed. This breaks with the latest userEvent version as this throws when an element is not clickable because of pointer-events.

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.13.1 |
| System | Win 10 |
| Browser | Chrome latest |

---
There is already a logic in rc-motion which checks whether animation and transitions are supported but I guess this logic should directly jump to the final state instead of aborting https://github.com/react-component/motion/blob/master/src/hooks/useStatus.ts#L173
Thus the callbacks in the rc-trigger could be called and the pointerEvents will be removed again.

Related release of @testing-library/user-event https://github.com/testing-library/user-event/releases/tag/v13.1.3

**Comment by afc163** [comment]
You can try https://codesandbox.io/s/antd-pointer-events-cgqy0?file=/index.js

**Comment by fragsalat** [comment]
I wonder if such a ugly workaround is better than fixing the issue.
Using 
```
document.getElementsByClassName("ant-select-dropdown")[0].style[
    "pointer-events"
  ] = "auto";
```
For all components using rc-trigger is not just against testing-library approach not using the DOM but also makes the tests ugly and adds unnecessary code which might go away in future.

**Comment by fragsalat** [comment]
Wanted to ping on that as I believe this should work out of the box or there should be a valid reason to not fix this.

**Comment by samkahchiin** [comment]
@fragsalat  any updates on this issue?
I also faced the same issues and I agree with you that hardcoded the pointer-events style in the test is an appropriate fix.

**Comment by fragsalat** [comment]
No updates. I downgraded the version of user-events below 13.1 (before they added the error on clicking on pointer-events none) and hope the team behind ANT will somehow recognize this is a true bug and they have to fix it. May it's worth to open another issue and someone else from the team reads this^^

**Comment by balavishnu-hme** [comment]
#31595

**Comment by mdbenjam** [comment]
Agreed that a permanent fix that enables us to use these components in JSDOM environments would be incredibly helpful.

In the meantime, I addressed this in our tests by using `fireEvent.click` to select the option in the select menu since `fireEvent` doesn't check for `pointer-events: none`. Not a very robust solution, and I'd rather use the more accurately simulated `userEvent.click` but it felt less hacky than trying to modify the `pointer-events` attribute of the element we wanted to click on.

**Comment by JPM709** [comment]
One tedious solution I've been using is to change up the selectors used in tests. For Select/Dropdown instead of things like `placeholderText, data-testid, labelText` etc. I've been using *AllByRole('combobox')[index] to great effect. Its an absolute pain when I have 4000 unit tests and 900 of them stop working when I updated Ant, but hey it works!

**Comment by awx-shaun-huang** [comment]
This is really an issue that needs attention. I've been racking my brain trying to find effective ways to test the Select Component, but I haven't found an ideal solution.

**Comment by PotatoEater0127** [comment]
Anyone got an ideal workaound? 🥲

**Comment by mcshaman** [comment]
I would also like to see some work done on this. The Ant D library does not play very nicely with React Testing Library which is one of the industry standard testing tools and it would be good see some of the issues looked at.
