### ISSUE TITLE
table thead tr th 在IE浏览器字体加粗不管用

### ISSUE THREAD

**Issue by kuiGe11** [ant-design/ant-design#31107]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/table-cn/#API](https://ant-design.gitee.io/components/table-cn/#API)

### Steps to reproduce
渲染字体不加粗

### What is expected?
加粗

### What is actually happening?
加粗

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.8.6 |
| System | windows 和 mac |
| Browser | 谷歌极速浏览器 |

---
table组件 thead tr th 在IE浏览器字体加粗不管用

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29610#issuecomment-790263358
https://github.com/ant-design/ant-design/issues/29610

目前没有好的办法。

**Comment by afc163** [comment]
IE 下只能用 font-weight bold 表示加粗，但是实际效果和设计上差异过于显著，保持现状 fallback 到 normal 反而更合理。
