### ISSUE TITLE
分页控件的选中置灰样式和单选按钮的置灰样式为何不一样，在3.X时他们样式一致

### ISSUE THREAD

**Issue by wwn2018** [ant-design/ant-design#31103]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决组件源样式保持一致的问题，他们源头都是按钮延伸

### What does the proposed API look like?
希望分页控件选中置灰样式变成现在的单选按钮选中置灰样式。更加希望主要按钮也有置灰的样式（当前不可用的样式，可以参考加载中样式）

**Comment by afc163** [comment]
截个图？

**Comment by wwn2018** [comment]
![image](https://user-images.githubusercontent.com/39756041/123209345-0ae73c80-d4f3-11eb-9386-af976d11bef1.png)
原因：既然都是按钮的形式延展，应该保持一致，例如以后的radio card、check card都可用这种处理逻辑，选中置灰的文字色是应该是单独的颜色，既不是disables text、secondary text。

**Comment by afc163** [comment]
可行。

**Comment by wwn2018** [comment]
设计师无能为力呀
