### ISSUE TITLE
Tree component(4.x) - hide file icon when use showLine

### ISSUE THREAD

**Issue by abhishekahuja87** [ant-design/ant-design#31111]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-paper-e7nl7)

### Steps to reproduce
File Icon visible on the codesandbox link

### What is expected?
the icon should not appear

### What is actually happening?
Icon apprears

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | Latest |
| System | Any |
| Browser | Any |

---
Same issue; but closed without fix- https://github.com/ant-design/ant-design/issues/23261

Got the link to https://codesandbox.io/s/883vo47xp8 from https://ant.design/components/tree/
The example in https://codesandbox.io/s/883vo47xp8 works for antd 3.26.15

**Comment by afc163** [comment]
https://codesandbox.io/s/thirsty-fog-gkn8l?file=/index.js

**Comment by abhishekahuja87** [comment]
Thanks
