### ISSUE TITLE
Modal button locale is cleared

### ISSUE THREAD

**Issue by jymsy** [ant-design/ant-design#31118]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/modal-locale-clear-nh1df?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. click show cofirm button, and button locale is Chinese.
2. close the modal and click show home button.
3. click hide home button.
4. click show confirm button again and button locale change to English.

### What is expected?
Modal button locale do not change

### What is actually happening?
Modal button locale change to English

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chome 88.0.4324.150 |

---
we use form render https://github.com/alibaba/x-render

**Comment by jymsy** [comment]
Before:
![image](https://user-images.githubusercontent.com/2777671/123233191-6eca2f00-d50c-11eb-9d2a-33831ba414fd.png)

After:
![image](https://user-images.githubusercontent.com/2777671/123233263-7e497800-d50c-11eb-98ad-bae99543be52.png)

**Comment by PeachScript** [comment]
Why do you need a nested `ConfigProvider` instead of the top one

**Comment by PeachScript** [comment]
refer: https://github.com/ant-design/ant-design/blob/master/components/locale-provider/index.tsx#L77

**Comment by afc163** [comment]
https://codesandbox.io/s/modal-locale-clear-forked-q18rz

https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux%E3%80%81%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F

**Comment by jymsy** [comment]
@PeachScript we use form render https://github.com/alibaba/x-render
