### ISSUE TITLE
TreeSelect(treeCheckable, treeCheckStrictly) wrapped with Item(normalize, getValueProps) is not working properly with initialValue

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#31132]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tumf2?file=/index.js)

### Steps to reproduce
Wrap TreeSelect (that has `treeCheckable` and `treeCheckStrictly` props) with Item that has `normalize` and `getValueProps` and provide initialValue

### What is expected?
should work properly with initialValue and no errors in console

### What is actually happening?
errors in console about a wrong format and no selection for initial value

| Environment | Info |
|---|---|
| antd | 4.16+ |
| React | 16 |
| System | any |
| Browser | any |

**Comment by plandem** [comment]
@afc163 updated link

**Comment by afc163** [comment]
initialValue will be passed to field component directly which don't trigger normalize and getValueProps, it is intented behavior.

**Comment by plandem** [comment]
why everything is working properly when  its not treeCheckStrictly?
