### ISSUE TITLE
2.0 Upload 已上传文件只显示第一个

### ISSUE THREAD

**Issue by aarryy** [ant-design/ant-design#3113]
由于问题直接在[V2](http://beta.ant.design/components/upload/)官网上可以重现我就略去提问格式了，Upload第二个代码演示中defaultFileList有两个文件但是只显示了第一个，作为对比，[V1](http://ant.design/components/upload/)中是两个都显示的，请问这个变化是有意为之吗？如果是的话要怎样显示全部？谢谢 
V2
![image](https://cloud.githubusercontent.com/assets/11393402/18727036/fa49d47e-8014-11e6-8ef3-e0a1124ea526.png)

V1
![image](https://cloud.githubusercontent.com/assets/11393402/18727040/fd8e39e0-8014-11e6-994e-7edce8ec1d1b.png)

**Comment by benjycui** [comment]
然而是个 bug...

**Comment by benjycui** [comment]
感谢反馈 👍
