### ISSUE TITLE
Warning from TreeSelect

### ISSUE THREAD

**Issue by gmoniava** [ant-design/ant-design#31140]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j13yn)

### Steps to reproduce
Click expand icon inside tree

### What is expected?
No warning

### What is actually happening?
I get warning: 
> Warning: Second param return from event is node data instead of TreeNode instance. Please read value directly instead of reading from props.

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 16.5 |
| System | Windows |
| Browser | Chrome |

---
This line causes the warning:       
`const { id } = treeNode.props;
`How to read `id` without warning?

For some reasons you can't see warning on StackBlitz.

**Comment by PeachScript** [comment]
`const { id } = treeNode`
