### ISSUE TITLE
使用Table表格的selectedRowKeys，会使得点击行能够选中，但是点击radio失效

### ISSUE THREAD

**Issue by qq1120637483** [ant-design/ant-design#31149]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
import React, { Component } from 'react'
import { Card, Button, Table } from 'antd'
import {reqRoles} from '../../api/index.js'
// 这是角色管理路由
export default class Role extends Component {
    state = {
        roles: [], 
        role: []    //选中的role
    }
    initColumn = () => {
        this.columns = [
            {
                title: '角色',
                dataIndex: 'name'
            },
            {
                title: '创建时间',
                dataIndex: 'create_time'
            },
            {
                title: '授权时间',
                dataIndex: 'auth_time'
            },
            {
                title: '授权人',
                dataIndex: 'auth_name'
            }
        ]
    }
    onRow = (role) => {
        return {
            onClick: event => {
                console.log(`检测到点击事件${role}`);
                this.setState({role})
            }
        }
    }
    getRoles = async() => {
        const result = await reqRoles();
        if (result.status === 0) {
            const roles = result.data;
            this.setState({roles})
        }
    }
    checkRows = (selectedRowKeys, selectedRows) => {
        selectedRows._id = selectedRowKeys
        this.setState({
            role: selectedRows
        })
    }
    componentWillMount() {
        this.initColumn()
    }
    componentDidMount() {
        this.getRoles()
    }
    render() {
        
        const { roles,role } = this.state;
        const title = (
            <span>
                <Button type='primary'>创建角色</Button> &nbsp;&nbsp;
                <Button type='primary' disabled={!role._id}>设置角色权限</Button>
            </span>
        )
        return (
            <Card title={title}>
                <Table
                    rowSelection={{
                        type: 'radio',
                        selectedRowKeys: [role._id],
                        // onChange: this.checkRows
                    }}
                    bordered
                    rowKey='_id'
                    dataSource={roles}
                    columns={this.columns}
                    pagination={{ defaultPageSize: 5}}
                    onRow = {this.onRow}
                />
            </Card>
        )
    }
}

### What is expected?
点击表格的某一行和点击某一个radio都能够选中该行

### What is actually happening?
点击行能够选中，但是点击radio竟然不行

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 17.0.2 |
| System | win10 |
| Browser | Chrome |

---
Bug的出现就是因为增加了SelectedRows

**Comment by qq1120637483** [comment]
> Hello @qq1120637483. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @qq1120637483, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/goofy-fast-728cr?file=/index.js  换成radio之后，点击行第一次能选中，第二次就不行了

**Comment by qq1120637483** [comment]
> Hello @qq1120637483. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @qq1120637483, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/goofy-fast-728cr?file=/index.js   第一次点击行能选中，第二次就不行了

**Comment by afc163** [comment]
https://codesandbox.io/s/async-sky-vbuu2

**Comment by qq1120637483** [comment]
> https://codesandbox.io/s/async-sky-vbuu2

大佬太强了，我想加下你的微信可以吗？
