### ISSUE TITLE
Tree 异步加载数据(loadData)失败后loading状态未重置

### ISSUE THREAD

**Issue by bailinx** [ant-design/ant-design#31141]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yibushujujiazai-antd4165-forked-msu1b?file=/index.js:858-882)

### Steps to reproduce
点击小箭头，加载数据，关闭错误弹窗，发现节点loading状态未重置

### What is expected?
失败后取消loading状态

### What is actually happening?
一直loading，并且外部无法改变loading状态

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | react 17.0.1 |
| System | mac os |
| Browser | chrome |

**Comment by PeachScript** [comment]
请求错误应该在 `loadData` 里 catch 住吧，UI 框架不应该做业务逻辑的错误捕获，会阻碍开发者实现自己的逻辑，比如前端监控

**Comment by bailinx** [comment]
UI是不应该做业务逻辑的错误捕获，ISSUE的意思是Tree组件需要在Promise.reject的时候重置loading状态
