### ISSUE TITLE
想问下textarea中showCount属性后面的{ formatter: ({ count: number, maxLength?: number }) => string }是要怎么设置？

### ISSUE THREAD

**Issue by suifen1994** [ant-design/ant-design#31150]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我这边需要自定一textarea右下角的文字描述以及展示文字描述的位置，请问该怎么处理

### What does the proposed API look like?
textarea加一个属性设置字数展示的位置，例如position表示字数位置，分分别为topLeft,toprRght,bottomLeft,bottomRight表示字数在左上方，右上方，左下方，右下方四个位置

**Comment by afc163** [comment]
抱歉，暂时不支持。

**Comment by suifen1994** [comment]
> 抱歉，暂时不支持。
那 showCount属性后面的{ formatter: ({ count: number, maxLength?: number }) => string }是要怎么设置，这种格式没有见过呢。麻烦指点一下
