### ISSUE TITLE
Form component doesn't pass initialValues which contains (defaultFileList) to Upload component

### ISSUE THREAD

**Issue by Gherciu** [ant-design/ant-design#31159]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pictures-wall-antd4165-forked-d1yuu?file=/index.js)

### Steps to reproduce
Pass a property to Form initialValues which contains defaultFileList and have the same name as Upload Form.item name prop

### What is expected?
I expect that property which contains initialValues (and is declared in Form.Item as name prop) to be passed to Upload component as defaultFileList

### What is actually happening?
Form doesn't pass property which contains initialValues (and is declared in Form.Item as name prop) to Upload component as defaultFileList

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 16.8 |
| System | MAC OS Catalina |
| Browser | Chrome, Safari |

---
Also antd throw this error
"Warning: [antd: Upload] `value` is not a valid prop, do you mean `fileList`? "
It happens because Upload doesn't have any value prop only defaultFileList and fileList
And I expect that antd to pass correct prop ant Upload to be populated with images

**Comment by afc163** [comment]
```
valuePropName="fileList"
```

https://ant.design/components/form-cn/#components-form-demo-validate-other
