### ISSUE TITLE
Typography.Text 组件的 ellipsis，在Tree组件中可以使用但报错: [antd: Typography] `ellipsis` should use string as children only.

### ISSUE THREAD

**Issue by hocko333** [ant-design/ant-design#31178]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5ohso?file=/index.js)

### Steps to reproduce
打开该重现连接，再打开控制台，即可看到一条报错信息：Warning: [antd: Typography] `ellipsis` should use string as children only.

### What is expected?
期望不要报错

### What is actually happening?
按照文档使用，但是却报错

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.14.0 |
| System | macOS Big Sur V11.4 |
| Browser | Chrome 91.0.4472.114 |

---
只有在Tree组件中使用 Typography.Text 组件的 ellipsis 才会报错，但在其他地方使用就不会报错

**Comment by afc163** [comment]
ellipsis should use string as children only.

https://codesandbox.io/s/antd-reproduction-template-forked-9esm0
