### ISSUE TITLE
Antd select popover not sticking to select box on scroll

### ISSUE THREAD

**Issue by bspatil0001** [ant-design/ant-design#31172]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-sid-yge5j)

### Steps to reproduce
On scroll the popover is not sticking with the select box

### What is expected?
on scroll the popover should stick to select box

### What is actually happening?
Popover getting separating and getting fixed relative to screen

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | 17.0.2 |
| System | macOS Catalina |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/intelligent-feather-4iqd9
