### ISSUE TITLE
Tree load async data  and checkedKeys contains not expand node, the error:  Tree missing follow keys: '***' 

### ISSUE THREAD

**Issue by silence717** [ant-design/ant-design#31173]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yibushujujiazai-antd4165-forked-97f7e?file=/index.js)

### Steps to reproduce
1. have a three level mutiple tree
2. set checkedKeys is a lead node, such as " 0-0-1"
3. reload tree, but not expand all node

### What is expected?
checkedKeys contains not expand node no error 

### What is actually happening?
Tree missing follow keys: '0-0-1' 

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome  91.0.4472.114  |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/30518#issuecomment-842238610
