### ISSUE TITLE
双层Modal下，下层Modal中的Tooltip提示不会消失

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#31179]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4165-forked-3qqv0?file=/index.js:1013-1020)

### Steps to reproduce
打开下层Modal，点击“ ”icon，鼠标保持，不移动。
当上层Modal打开时，下层的Modal中的Tooltip提示不会消失。

### What is expected?
上层Modal出现时，如何让下层的Tooltip提示消失，或者规避。

### What is actually happening?
上层Modal出现时，下层的Tooltip提示不会消失
![image](https://user-images.githubusercontent.com/50108232/123748244-8a578000-d8e6-11eb-921f-7ce1adc225c0.png)

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 16.14.0 |
| System | window |
| Browser | chrome |

**Comment by liuxing95** [comment]
这个是咋解决的？

**Comment by zmbxy95** [comment]
@liuxing95
> 这个是咋解决的？

我觉得这个可能是使用上的问题吧，我是改变了下用法。
按照如下写法，会出现上述问题：
```javascript
<Tooltip title="some contents" placement="topLeft">
    {loading ? (
        <LoadingOutlined spin style={{ fontSize: 20, cursor: "pointer" }} />
    ) : (
        <PlusSquareOutlined
            onClick={() => {
                setLoading(true);
                setTimeout(() => {
                    setLoading(false);
                    setIsModalVisible2(true);
                }, 3000);
            }}
        />
    )}
</Tooltip>
```
后面我将其修改了一下（如下），就可以避免上述的问题了。
```javascript
{loading ? (
        <LoadingOutlined spin style={{ fontSize: 20, cursor: "pointer" }} />
    ) : (
        <Tooltip title="some contents" placement="topLeft">
            <PlusSquareOutlined
                onClick={() => {
                    setLoading(true);
                    setTimeout(() => {
                        setLoading(false);
                        setIsModalVisible2(true);
                    }, 3000);
                }}
            />
        </Tooltip>
    )
}
```

希望会对你有帮助。
