### ISSUE TITLE
Avatar fallback does not work with server-side rendering

### ISSUE THREAD

**Issue by delyanr** [ant-design/ant-design#31171]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ssr-antd-avatar-issue-7x6hn)

### Steps to reproduce
Follow the minimal reproduction link. If at first the fallback works, refresh the page. It stops working thereafter.

### What is expected?
The `Avatar` component falls back to (renders) its `children` when the `src` errors out in server-side rendering (SSR).

### What is actually happening?
The `Avatar` component shows a broken image in server-side rendering (SSR).

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome latest |

**Comment by delyanr** [comment]
Hey @afc163, @zombieJ. Any thoughts on this issue? Am I doing something wrong here?

**Comment by afc163** [comment]
Is is same as #39962 ？

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/39962#issuecomment-1374984870
