### ISSUE TITLE
官网加载速度慢

### ISSUE THREAD

**Issue by xiehurricane** [ant-design/ant-design#3118]
#### 您做了什么？

访问

#### 您期待的结果是：
快速显示

#### 实际上的结果是：

![image](https://cloud.githubusercontent.com/assets/5900460/18736021/56422a6a-80b5-11e6-98cf-4b59fe735769.png)

这个东西国内加载不了 影响速度
#### 可重现的在线演示
官网

**Comment by benjycui** [comment]
需要翻墙。。。

**Comment by afc163** [comment]
加了一层代理优化了一下，现在应该快多了。

**Comment by xiehurricane** [comment]
感谢

**Comment by Alex1990** [comment]
我需要 250 ~ 500 ms，因为经常需要查看文档所以这速度还是挺慢的，还有开头动画加载就好好几秒

**Comment by afc163** [comment]
@Alex1990 可以期待一下 https://github.com/ant-design/ant-design/issues/4364
