### ISSUE TITLE
哥，ant.design官网出bug了，赶紧修复下

### ISSUE THREAD

**Issue by ctq123** [ant-design/ant-design#31180]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce
随便点击弹窗，打开控制台查看
ant.design/:307 GET https://ant.design/index-9424a71a.js 
net::ERR_ABORTED 404

### What is expected?
正常弹出

### What is actually happening?
没有弹出

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | v1.0 |
| System | mac |
| Browser | chrome,safari |

**Comment by ctq123** [comment]
![image](https://user-images.githubusercontent.com/12124169/123752357-4b77f900-d8eb-11eb-8e5c-3f18f227efcb.png)
其他的弹窗也是一样

**Comment by xrkffgg** [comment]
我这里好着的啊

**Comment by qinjialei24** [comment]
我也是

**Comment by afc163** [comment]
貌似已经好了。
