### ISSUE TITLE
主站的查看code 不起作用了

### ISSUE THREAD

**Issue by ZxBee** [ant-design/ant-design#31182]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce
点击查看code 按钮

### What is expected?
查看代码

### What is actually happening?
不能打开

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment]
我这里好着的 没发现问题

**Comment by ctq123** [comment]
+1

**Comment by ctq123** [comment]
同样，出bug了

**Comment by afc163** [comment]
貌似已经好了。
