### ISSUE TITLE
Modal destroyAll() not working when using contextHolder

### ISSUE THREAD

**Issue by ds1371dani** [ant-design/ant-design#31190]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/use-hooks-to-get-context-antd4166-forked-7qizm)

### Steps to reproduce
When opening modal from Modal.useModal(), destroyAll function won't work.

### What is expected?
destroyAll function should close all opened modals

### What is actually happening?
nothing

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14.0 |
| System | Ubuntu 20.04 |
| Browser | 89.0.2 |

**Comment by mbushpilot2b** [comment]
I am having this same issue when using context holder.

**Comment by joshweb371** [comment]
I am having this same issue when using context holder, help me
