### ISSUE TITLE
Col component padding issue

### ISSUE THREAD

**Issue by arianafrancof** [ant-design/ant-design#31199]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

https://codesandbox.io/s/antd-reproduction-template-forked-sr9bo?file=/index.js

### Steps to reproduce
Having two Rows and using Cols with Cards inside them. The Cards in the first Row are joining with the Cards of the second Row.
In previous versions this feature was working fine (Cols had a padding at 7.5).

Having the following structure:

```
<Row gutter={[15, 15]}>
  <Col span={'5'}>
    <Card>
      <Statistic title='Total' value={20} />
    </Card>
  </Col>
  <Col span={'5'}>
    <Card>
      <Statistic title='Passed' value={12} />
    </Card>
  </Col>
</Row>
<Row gutter={[15, 15]}>
  <Col span={'5'}>
    <Card>
      <Statistic title='Total' value={20} />
    </Card>
  </Col>
  <Col span={'5'}>
    <Card>
      <Statistic title='Failed' value={8} />
    </Card>
  </Col>
</Row>
```

### What is expected?
When using the Col component, the cards have a padding between each other when they are in different Rows.

![image](https://user-images.githubusercontent.com/75339687/123862596-26d15080-d8ee-11eb-84d9-2741abd8aa71.png)

### What is actually happening?
The cards components join each other using the Card component.

![image](https://user-images.githubusercontent.com/75339687/123862214-b1658000-d8ed-11eb-9b16-817b067f265e.png)

| Environment | Info |
|---|---|
| antd | 4.11.3 |
| React | ^16.12.0 |
| System | Ubuntu 20.04 |
| Browser | Chrome 90.0.4430.212, Firefox 89.0.1 |

---
This issue happens since version 4.11.3 and upper.
The cards components join each other because the currently library version only sets the padding-left and padding-right to 7.5px when previously the library style was padding:7.5px for Cols in general.

**Comment by arianafrancof** [comment]
Link provided! Thanks!

**Comment by afc163** [comment]
It is intented behavior, gutter works bettween Col inside Row. Here is one solution: https://codesandbox.io/s/antd-reproduction-template-forked-b4z0q?file=/index.js
