### ISSUE TITLE
Checkbox.group 使用 Checkbox 做 children label 文字过长时 margin 间距问题

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#31196]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/bGWGZba?editors=0010](https://codepen.io/mraiguo/pen/bGWGZba?editors=0010)

### Steps to reproduce
可以看到红框内第二个checkbox 有个 margin-left

### What is expected?
第二个 Checkbox 和第一个对齐

### What is actually happening?
没有对齐

![image](https://user-images.githubusercontent.com/22299421/123793517-5e52f380-d914-11eb-9a9b-651de8773538.png)
找到个 commit,但是不知道这个具体修复的是什么问题

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.x |
| System | win10 |
| Browser | chrome |

**Comment by xrkffgg** [comment]
相邻间距是正常的，只不过碰到这种很长的情况，我觉得自己处理下样式 或者 设计比较好

**Comment by afc163** [comment]
解决过一次，看上去后面哪里又改挂了。https://github.com/ant-design/ant-design/commit/463a5db9baad36c6605a99b60c69fdab6d6a35bb#commitcomment-25021344

**Comment by afc163** [comment]
这样写就行了，参考官方 demo https://codepen.io/afc163/pen/gOWbGLb?editors=0010
