### ISSUE TITLE
RangePicker设置了showTime属性，当组件在已经设置了时间的情况下，将开始时间修改为大于结束时间，会自动将开始时间和结束时间进行对调

### ISSUE THREAD

**Issue by Leo233** [ant-design/ant-design#31203]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5sgup)

### Steps to reproduce
1.使用一个RangePicker组件，设置showTime属性
2.将开始时间和结束时间分别设置为 2021/06/28 10:00 ~ 2021/06/28 11:00
3.修改开始时间为 2021/06/28 12:00
4.点击确定之后，会发现时间变成了 2021/06/28 11:00 ~ 2021/06/28 12:00

### What is expected?
期望结果是，修改开始时间为 2021/06/28 12:00 之后，开始时间变成 2021/06/28 12:00，结束时间清空

### What is actually happening?
实际结果是时间变成了 2021/06/28 11:00 ~ 2021/06/28 12:00，修改的开始时间变成了结束时间，而原来的结束时间变成了新的开始时间

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.13.1 |
| System | macOs 10.14.6 |
| Browser | chrome 87.0.4280.67 |

**Comment by kerm1it** [comment]
这就是这样设计的，时间范围必须后面大于前面，如果不是会自动进行调换。
