### ISSUE TITLE
Hide a column conditionally in antd Table

### ISSUE THREAD

**Issue by arslanalidev** [ant-design/ant-design#31204]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When we are using the table, If we are implementing the same table for two separate entities. Then sometimes we want to show or hide some columns based on their roles. So if we do it in our project it will make the code more reusable and it will also effect to make the performance point of view. 

### What does the proposed API look like?
When we are defining the columns array in ant design. We can add one extra prop on that with the name of visibility. That default prop will have a true value. and the user can set it by himself as well.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28243#issuecomment-740303597
