### ISSUE TITLE
Antd 4.x Tree component has Accessibility issue using Axe Accessibility tool: "Certain ARIA roles must contain particular children"

### ISSUE THREAD

**Issue by abhishekahuja87** [ant-design/ant-design#31215]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/customize-collapseexpand-icon-antd4166-f3my8?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
- Install Axe Accessibility Tool on Chrome browser
- Run the tool against the app in codesandbox link, find the accessibility warnings

### What is expected?
- No Serious accessibility warnings

### What is actually happening?
- Serious warning present

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | Latest |
| System | Any |
| Browser | Any |

**Comment by afc163** [comment]
Trace #31012
