### ISSUE TITLE
Support RangePicker array show format

### ISSUE THREAD

**Issue by LeeRayno** [ant-design/ant-design#31211]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- support RangePicker array show format
- I set the format props `['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59']`
- and wish the picker show is `[2021-06-30 00:00:00, 2021-06-30 23:59:59]`，
- but the picker show is the first format `[2021-06-30 00:00:00, 2021-06-30 00:00:00]`
- the second format is‘t take effect
- [codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-v5nq1?file=/index.js)

### What does the proposed API look like?
```js
<RangePicker
     // support array format
     format={['YYYY-MM-DD 00:00:00', 'YYYY-MM-DD 23:59:59']}
/>
```

**Comment by huntdream** [comment]
I suppose it is by design, according to the documentation

> When an array is provided, all values are used for parsing and first value is used for formatting

and related pr https://github.com/react-component/picker/pull/84, issue https://github.com/ant-design/ant-design/issues/24934
The mainly purpose of `format` is to parse user inputed date string rather then display different format in one `RangePicker`

**Comment by zombieJ** [comment]
> I suppose it is by design, according to the documentation
> 
> > When an array is provided, all values are used for parsing and first value is used for formatting
> 
> and related pr [react-component/picker#84](https://github.com/react-component/picker/pull/84), issue #24934 The mainly purpose of `format` is to parse user inputed date string rather then display different format in one `RangePicker`

Here is the answer. It's design for parser not for different input.
