### ISSUE TITLE
Form.Item可否支持在子组件为输入元素和非输入元素时，自动将value注入表单输入元素，而非手动控制

### ISSUE THREAD

**Issue by baiziyu-fe** [ant-design/ant-design#31214]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在下面这种情况可否支持在给`Form.Item` value属性的同时能默认将value传入`Input`, 而不需要手动再去注入
或者希望可以开放一个关于 `mergeValue`的`hooks`或者方法
```JavaScript
<Form.Item
        name="note"
        label="Note"
        rules={[
          {
            required: true,
          },
        ]}
      >
        <Input />
        <span>123</span>
  </Form.Item>
```

---

In the following situation, can it be supported to pass the value to the` Input `by default while giving the `Form.Item` value attribute, instead of manually injecting it?
Or hope to open a hook or method about mergeValue
```JavaScript
<Form.Item
         name="note"
         label="Note"
         rules={[
           {
             required: true,
           },
         ]}
       >
         <Input />
         <span>123</span>
   </Form.Item>
```

### What does the proposed API look like?
1. 期望可以自动注入`value`
2. 暴露出的`mergeValue`满足 
```
const [value, onChange] = Form.useMergeValue(value, onChange)
```
---
1. Expect `value` to be injected automatically
2. The exposed `mergeValue` satisfies
```
const [value, onChange] = Form.useMergeValue(value, onChange)
```

**Comment by afc163** [comment]
这个做不到的，Form.Item 无法猜测出哪个是输入元素。
