### ISSUE TITLE
安装babel-plugin-import按需加载antd组件后，引入自定义css/less会引发警告

### ISSUE THREAD

**Issue by koen301** [ant-design/ant-design#3121]
#### 发生问题的环境是：
win 10,
npm 3.8.9
node 6.2.0

- antd 版本:1.11.1
- 操作系统及其版本:win 10
- 浏览器及其版本:chrome最新

#### 您做了什么？

安装 babel-plugin-import 按需加载 antd 组件后
webpack 中 babel 设置为：plugins: [["import", { "libraryName": "antd", "style": true }]]
然后页面中入口文件引入css：import 'ASSETS/css/style.css';
运行，antd 组件一切正常，但 cmd 和浏览器一起报告 WARNING：

WARNING in 
./~/.0.13.1@style-loader/addStyles.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

client:68 G:/git/financing_project_default_v3.8/~/.0.13.1@style-loader/addStyles.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

client:68 ./~/.0.25.0@css-loader/lib/css-base.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

client:68 G:/git/financing_project_default_v3.8/~/.0.25.0@css-loader/lib/css-base.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
#### 您期待的结果是：
去掉 WARNING 

#### 实际上的结果是：
样式正常加载，但报告了 WARNING 

#### 可重现的在线演示
暂无

**Comment by sorrycc** [comment]
给个可重现的 repo 。

**Comment by koen301** [comment]
@sorrycc 现在发现和 babel-plugin-import 插件是没关的，只要是用到antd组件，然后在页面中import一个自定义的样式，都会引发这个警告。难道你们都不会？

**Comment by sorrycc** [comment]
我没有遇到这个问题。

**Comment by benjycui** [comment]
> `There is another module with an equal name when case is ignored.`

**Comment by koen301** [comment]
@benjycui @sorrycc 目前找到了一个解决的办法，就是用 extract-text-webpack-plugin 插件把 css/less 独立抽取出来，就不会引发这个警告，不过这样 css 的 hot-reload 功能就用不了了，虽然还是可以 auto-reload。个人觉得应该是用 style-loader 引用了 modules 的 css/less 有关。

**Comment by afc163** [comment]
还是给个可重现的 repo 吧。

**Comment by koen301** [comment]
@afc163 现在找不到 repo 了。。。closed 掉吧
