### ISSUE TITLE
menu 和 table 重构成 func component 能否加 forwardRef？

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#31227]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
menu 的 subMenu 和 item 和 table 不能使用 ref。。。

### What does the proposed API look like?
function component 加上 ref

**Comment by afc163** [comment]
需要 ref 做什么？

**Comment by jljsj33** [comment]
https://github.com/react-component/tween-one/issues/126

**Comment by jljsj33** [comment]
<SubMenu ref={xxx} />, 这也是组件基本的使用啊，，你不能不让用啊。。

**Comment by afc163** [comment]
@jljsj33 来个 PR

**Comment by ernesto-reify** [comment]
> @jljsj33 来个 PR

Hi. How could I follow the progress on this?

Thanks

**Comment by jljsj33** [comment]
> @jljsj33 来个 PR

老铁，，我有时间搞的话我会给你提 issuse 的吗？？？我哪来时间搞，，等豆酱吧。。。

**Comment by afc163** [comment]
Duplicate of #36117
