### ISSUE TITLE
希望tree组件设置height后，出现横向滚动条

### ISSUE THREAD

**Issue by Jeggery** [ant-design/ant-design#31226]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
树形结构有很多层的时候，可以更方便展示

### What does the proposed API look like?
应该自动加上，元素超出宽度的时候自动加上横向滚动
[示例：](https://codesandbox.io/s/zidingyitubiao-antd4166-forked-ohlej?file=/index.js)

**Comment by PeachScript** [comment]
`height` 属性会开启虚拟滚动，目前应该不支持横向滚动，cc @zombieJ 

如果希望限制 tree 高度的同时横向滚动，可以把 height 属性去掉，通过给 tree 添加外层容器限制宽高 + `overflow: auto` 来实现

**Comment by Jeggery** [comment]
> `height`属性会开启虚拟滚动，目前应该不支持横向滚动，cc @zombieJ
> 
> 如果希望限制树高度的同时横向高滚动，可以把高度属性降低，通过给树添加外层容器限制宽`overflow: auto`来实现

是可以通过浏览器来实现，但是对于tree的方法scrollTo, 并不能跳到对应视图，这是否是一个bug?

**Comment by PeachScript** [comment]
`scrollTo` 仅用于虚拟滚动开启的情况，我理解上面的解法是禁用虚拟滚动 + 利用外层容器实现内容滚动，外层容器不在 tree 的控制范围，需要手动获取目标元素的位置、并设置外层容器的 scrollTop

**Comment by Jeggery** [comment]
> `scrollTo` 仅用于虚拟滚动开启的情况，我理解上面的解法是禁用虚拟滚动 + 利用外层容器实现内容滚动，外层容器不在 tree 的控制范围，需要手动获取目标元素的位置、并设置外层容器的 scrollTop

了解了，也就是需要自己去实现

**Comment by Jeggery** [comment]
> 如果希望限制 tree 高度的同时横向滚动，可以把 height 属性去掉，通过给 tree 添加外层容器限制宽高 + `overflow: auto` 来实现

如果不使用虚拟滚动，tree节点数量多的情况下会很卡

**Comment by Jeggery** [comment]
> 意思是想要允许横向滚动就不能开启虚拟滚动吗？

大概是的

**Comment by DPGZl** [comment]
> `height` 属性会开启虚拟滚动，目前应该不支持横向滚动，cc @zombieJ
@PeachScript 请问开启虚拟滚动之后，为什么不支持横向滚动？会有计划在之后版本中支持吗

**Comment by mianmalife** [comment]
同问 楼上的问题

**Comment by afc163** [comment]
@cong1223 不妨把改动发个 PR 到 rc-tree 来？

**Comment by zombieJ** [comment]
@cong1223 +1，欢迎给 `rc-tree` PR 哈~

**Comment by jydeng0724** [comment]
// 开启虚拟滚动时滚动条的样式
  .ant-tree-list-holder {
    /* 滚动槽 */
    &::-webkit-scrollbar {
      width: 8px !important;
      height: 8px !important;
    }
    &::-webkit-scrollbar-track {
      background: transparent;
      border-radius: 8px;
      -webkit-box-shadow: none;
    }
    /* 滚动条滑块 */
    &::-webkit-scrollbar-thumb {
      background: rgba(0, 0, 0, 0.5);
      border-radius: 4px;
      -webkit-box-shadow: none;
    }

    // 开启虚拟滚动时，适配横向滚动
    & > div {
      overflow: visible !important;
    }
  }

强制开启滚动条，实测 虚拟滚动+横向滚动条可以并存。

**Comment by jydeng** [comment]
```
 // 开启虚拟滚动时滚动条的样式
  .indicator-ant-tree-list-holder {
    /* 滚动槽 */
    &::-webkit-scrollbar {
      width: 8px !important;
      height: 8px !important;
    }
    &::-webkit-scrollbar-track {
      background: transparent;
      border-radius: 8px;
      -webkit-box-shadow: none;
    }
    /* 滚动条滑块 */
    &::-webkit-scrollbar-thumb {
      background: rgba(0, 0, 0, 0.5);
      border-radius: 4px;
      -webkit-box-shadow: none;
    }

    // 开启虚拟滚动时，适配横向滚动
    & > div {
      overflow: visible !important;
    }
  }

```
可以用CSS强制出现横向滚动
