### ISSUE TITLE
Range Picker locale format not working

### ISSUE THREAD

**Issue by Harukisatoh** [ant-design/ant-design#31220]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/range-picker-locale-bug-nzndl?file=/index.js)

### Steps to reproduce
After importing a moment locale and loading it with `moment().locale()`, you should pass RangePicker's format prop as "L".

### What is expected?
It's expected that RangePicker format his dates according to current locale.

### What is actually happening?
RangePicker's format property passed as "L" does nothing.

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | Ubuntu 20.04.2 LTS |
| Browser | Chrome 91.0.4472.114 |

**Comment by afc163** [comment]
You need https://ant.design/components/config-provider/ as well.
