### ISSUE TITLE
修改组件的正确姿势

### ISSUE THREAD

**Issue by kolf** [ant-design/ant-design#3122]
#### 发生问题的环境是：本地环境

- antd 版本: 1.10.0
- 操作系统及其版本: windows 10
- 浏览器及其版本: chrome 53

#### 您做了什么？
引用Upload, 使用图片列表样式，修改样式
#### 您期待的结果是：
可以修改Upload组件，点击预览改为旋转图片，点击图片可切换选中状态。

#### 实际上的结果是：
样式不好改，组件也不好改，我是应该改lib/upload 文件，再build一次。还是应该基本upload再写个组件

**Comment by benjycui** [comment]
在 Upload 上面再包装一层吧。
