### ISSUE TITLE
国际化翻译-日语-DatePicker日期组件星期几翻译不正确

### ISSUE THREAD

**Issue by ZhangXDong** [ant-design/ant-design#31221]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/dashboard/analysis?primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false](https://preview.pro.ant.design/dashboard/analysis?primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false)

### Steps to reproduce
ant-design-pro中首页的日期组件有相同的问题

### What is expected?
正确翻译日文

### What is actually happening?
将一二三四五六翻译成了金木水火土

### ant-design-pro中的表现
![image](https://user-images.githubusercontent.com/28100344/124055196-0cb28200-da56-11eb-8a1a-d0dda7944539.png)

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 17.0.2 |
| System | macOS  11.2.3 |
| Browser | 89.xxx |

**Comment by yoyo837** [comment]
moment里的，问问身边懂日文的看看是不是预期的？

**Comment by yoyo837** [comment]
ref: https://github.com/moment/moment/pull/4413

**Comment by afc163** [comment]
这是正确的 https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/locale/ja.js#L81-L82
