### ISSUE TITLE
tree组件属性菜单元素的文字未展示到一行

### ISSUE THREAD

**Issue by Jeggery** [ant-design/ant-design#31223]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyitubiao-antd4166-forked-26jmh?file=/index.js)

### Steps to reproduce
打开上述链接就能看到文字挤压

### What is expected?
树形菜单能出现横向滚动条，里面元素有多少出现多少，文字能展示到一行

### What is actually happening?
文字被挤压换行了

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14 |
| System | win10 |
| Browser | chrome 89版本 |

---
当树形结构嵌套很深的时候，就会出现这种问题

**Comment by PeachScript** [comment]
看你的复现链接已经修复了，每个项目的对排版的需求不一样，加 `white-space: nowrap` 是正解
