### ISSUE TITLE
Select在tags模式下，当allowClear设为true，点击清除后无法再输入任何文字

### ISSUE THREAD

**Issue by xjb258** [ant-design/ant-design#31232]
如题。

<Select
            label='test'
            allowClear
            valueEnum={{'[test]': '[test]'}}
           mode='tags'
           filterOption={ false}
/>

### Reproduction link
[http://暂无](http://暂无)

### Steps to reproduce
必现

### What is expected?
点右侧清除按钮后仍可正常输入标签

### What is actually happening?
点清除按钮后无法输入

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.0 |
| System | win10 20H2 |
| Browser | edge |

**Comment by paopaolee** [comment]
这个问题并非Antd Select的Bug,而是ProComponents造成的
