### ISSUE TITLE
Form validate required not work with upload

### ISSUE THREAD

**Issue by damdauvaotran** [ant-design/ant-design#31235]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jekgx)

### Steps to reproduce
- Build a Form with Upload and add required validate
- Upload a file 
- Delete file in upload list
- Submit form

### What is expected?
Validate fail, display validate message error

### What is actually happening?
Validate success

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Chorome 91.0.4472.114 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31159#issuecomment-869293842
