### ISSUE TITLE
No props for the Expand Icon used in expandable in tables available

### ISSUE THREAD

**Issue by Vanluren** [ant-design/ant-design#31230]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At the moment there is no type exported for the props of the Expand Icon used in the "expandable" prop on the tables. 

### What does the proposed API look like?
Export the expand icon props from `ant/lib/table/interface`

**Comment by nsqnsq** [comment]
![Image](https://github.com/user-attachments/assets/96c36ac0-fe59-467c-84c3-4da4b5954894)
