### ISSUE TITLE
Table 组件，固定第一列，有rowSelection情况，水平滚动宽度计算不对。

### ISSUE THREAD

**Issue by jsrider** [ant-design/ant-design#3124]
如题，固定列和 非固定列 （年龄和列1 直接距离少了，推测是受 rowSelection影响。没有没问题。）
http://codepen.io/jsrider/pen/bwVRBK?editors=0011

**Comment by afc163** [comment]
总宽度要考虑选择列的宽度：`x: 1500` => `x: 1560`。

或者留至少一个自适应列（不设宽度）。
