### ISSUE TITLE
DatePicker - Using a DatePicker in combination with a Form with initial values - OnChange methods always return the initial value instead of selected. 

### ISSUE THREAD

**Issue by frsc** [ant-design/ant-design#31249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-pslde?file=/index.js)

### Steps to reproduce
DatePicker onChange is not updating correctly if used within a Form with initial values. When changing dates in the picker both the onChange function for the picker and the onValuesChange for the form always shows the initial value instead of the newly selected on. If no initial value is set it works as expected. 

### What is expected?
When selecting a new date in the picker the expected behaviour is to get that new value in the onChange method (and the forms onValuesChange method). 

### What is actually happening?
When using Form initial values in combination with DatePickers the onChange methods is not working, they always return the initial value instead of the selected on. 

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.1 |
| System | MacOs Big Sur - 11.4 |
| Browser | Brave - Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64) |

**Comment by afc163** [comment]
It works fine, please see https://codesandbox.io/s/antd-reproduction-template-forked-5tvjo?file=/index.js
