### ISSUE TITLE
DatePicker - DisableDate and DateRender style conflicts and renders disabled dates as "blank" without visible numbers 

### ISSUE THREAD

**Issue by frsc** [ant-design/ant-design#31248]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8bg2v?file=/index.js)

### Steps to reproduce
For a DatePicker, using both the disableDate function in combination with dateRender renders all disabled date as "blank" without visible numbers. 
The numbers are in the DOM just the styling is incorrect. 

### What is expected?
In this example (see link to reproduce) I would expect to be able to view the dates that are disabled. 

### What is actually happening?
All disabled dates are rendered as "blank" without the numbers being visible.

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | ^17.0.1 |
| System | macOS - 11.4 Big Sur |
| Browser | Brave - Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64) |

**Comment by PeachScript** [comment]
`dateRender` means customize single date cell fully, so you should handle disabled style manually, but it is recommend wrap the date via `<div className="ant-picker-cell-inner"></div>`, check out this demo: https://ant.design/components/date-picker/#components-date-picker-demo-date-render

**Comment by Markus-ipse** [comment]
Isn't it a bit brittle (prone to breaking) having to explicitly add an internal antD className, or are classNames guaranteed to stay the same across versions of antD?

**Comment by PeachScript** [comment]
Usually, the `className` always be stabled in the same major version, but different major versions may not
