### ISSUE TITLE
select 下拉框闪烁

### ISSUE THREAD

**Issue by wed1760617** [ant-design/ant-design#31247]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.antdv.com/components/select-cn/](https://www.antdv.com/components/select-cn/)

### Steps to reproduce
websocket 推送消息后点击下拉框 下面部分会闪烁两下

### What is expected?
不闪烁

### What is actually happening?
闪烁

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | vue |
| System | win |
| Browser | 谷歌 |

**Comment by yoyo837** [comment]
vue版本的请提交到 这 https://github.com/vueComponent/ant-design-vue

**Comment by yoyo837** [comment]
制作复现时，把websocket的换成任何异步形式，如setTimeout

**Comment by afc163** [comment]
Ant Design Vue 不是官方维护的，请到对应仓库进行反馈。

@xrkffgg 又可以写个 action 自动回复关闭了。
