### ISSUE TITLE
modal组件为什么有afterClose的回调api 却没有afterOpen的api，如果想要实现打开窗口后执行怎么做最合理

### ISSUE THREAD

**Issue by storageChu** [ant-design/ant-design#31242]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
modal窗口 visible=true后 执行指定的回调

### What is expected?
增加afterOpen的回调函数

### What is actually happening?
无打开窗口回调函数

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.13..1 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
在 Model children 元素里的 componentDidMount 或者 useEffect 里写逻辑。

**Comment by chzng** [comment]
好牵强！！！那干嘛提供afterClose方法呢？也能通过其他方式实现呀！要搞就搞全部，要不搞就都不搞，afterClose也取消了呗，像是一个半成品
