### ISSUE TITLE
popover的ref属性bug

### ISSUE THREAD

**Issue by xpcode** [ant-design/ant-design#3125]
`<Popover ref="popover" ... >
   <div id="popoverInner">
       <Button type="primary">点击弹出卡片</Button>
   </div>
</Popover>`

const ele = ReactDOM.findDOMNode(this.refs.popover)
// 目前：ele 是 #popoverInner 节点
// 应该：ele 是 #popover 对应的DOM节点

**Comment by benjycui** [comment]
你想要拿到弹层的 dom 节点的话，应该在 overlay 里面那个元素上加 `ref`。

Popover 是个行为容器，本身没有对应的 dom。

**Comment by xpcode** [comment]
如果在 overlay 里面那个元素上加ref，则拿不到弹层的 dom 节点，所以像是个bug




原始邮件
发件人:Benjy Cuinotifications@github.com
收件人:ant-design/ant-designant-design@noreply.github.com
抄送:C.4019980@qq.com; Authorauthor@noreply.github.com
发送时间:2016年9月22日(周四) 16:52
主题:Re: [ant-design/ant-design] popover的ref属性bug (#3125)


你想要拿到弹层的 dom 节点的话，应该在 overlay 里面那个元素上加 ref。
Popover 是个行为容器，本身没有对应的 dom。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by xpcode** [comment]
here http://codepen.io/xpcode/pen/PGWVLB?editors=001


原始邮件
发件人:Benjy Cuinotifications@github.com
收件人:ant-design/ant-designant-design@noreply.github.com
抄送:C.4019980@qq.com; Authorauthor@noreply.github.com
发送时间:2016年9月23日(周五) 10:41
主题:Re: [ant-design/ant-design] popover的ref属性bug (#3125)


Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
```jsx
const { DatePicker, Popover, Form, Button, Icon } = antd;

const App = React.createClass({
  render() {
    const FormItem = Form.Item
    const filterFormItemLayout = {
      labelCol: { span: 6 },
      wrapperCol: { span: 14 },
    };
    const getCalendarContainer = () => {
      // 这种写法可以
      // return document.querySelector('.messagecenter-overlay');
      
      // 这种写法错误
      // return ReactDOM.findDOMNode(this.refs.overlayInner);
      console.log(ReactDOM.findDOMNode(this.refs.overlayInner));
      console.log(ReactDOM.findDOMNode(this.refs.overlay));
      // 这种写法错误
      return ReactDOM.findDOMNode(this.refs.overlay);
    }
    const filterForm = (
      <Form horizontal ref="overlay">
        <FormItem {...filterFormItemLayout} label="开始日期：">
          <DatePicker getCalendarContainer={getCalendarContainer}/>
        </FormItem>
        <div style={{padding: 40}}>
          ...
        </div>
        <FormItem>
          <Button type="primary" htmlType="submit">确认</Button>
        </FormItem>
      </Form>
    );
    
    return (
      <div style={{margin: 10}}>
        <div className="message-filter">
          <Popover placement="bottomLeft" 
            content={filterForm} 
            overlayClassName="messagecenter-overlay"
            trigger="click">
            <div ref="overlayInner">
              <Icon type="filter" />
              <a href="#">&nbsp;过滤</a>
            </div>
          </Popover>
        </div>
      </div>
    );
  }
});

ReactDOM.render(<App />, document.getElementById('container'));
```
