### ISSUE TITLE
Component BackTop Need to Destroy when Fade Leave

### ISSUE THREAD

**Issue by idrisonehub** [ant-design/ant-design#31253]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/back-top/](https://ant.design/components/back-top/)

### Steps to reproduce
1. Scroll down until the BackTop button appears
2. Scroll up, and you still have the BackTop box that is not visible but covers the cursor

### What is expected?
Like ant.design version 3.*, we need to destroy the element when no need.

### What is actually happening?
BackTop covers the cursor

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | react 17.0.1 |
| System | Windows 10 |
| Browser | Chrome Version 91.0.4472.124 (Official Build) (64-bit) |

**Comment by betochf** [comment]
Hey, I would like to try to solve it... It's labeled but no one is assigned to it and there's no PR. If someone is working on it, just tell me, so I don't make a PR

**Comment by idrisonehub** [comment]
Is there someone who can help me?
I can't fix it

**Comment by betochf** [comment]
@idrisonehub I have a solution but still needs some work, the component is destroyed but it destroys it without any animation and looks kind of bad

**Comment by idrisonehub** [comment]
Thanks @betochf 
Can you make a PR, please? Because I have no idea to provide animation.

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/pull/27840
