### ISSUE TITLE
Dropdown - When used inside Fixed Column Table behaves unexpectedly. 

### ISSUE THREAD

**Issue by jayeshchoudhary** [ant-design/ant-design#31266]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-columns-antd4166-forked-ufthi)

### Steps to reproduce
1. Click on the 3 dots icon in the last column.
2. This Opens a dropdown which is partially visible.
![alt text](https://i.ibb.co/WgzNJKB/Screenshot-from-2021-07-05-15-19-57.png)

### What is expected?
Dropdown should be fully visible

### What is actually happening?
Dropdown is partially visible 

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | Ubuntu |
| Browser | Chrome Version 89.0.4389.128 (Official Build) (64-bit) |

**Comment by afc163** [comment]
You could remove `getPopupContainer={(trigger) => trigger.parentNode}` either add `zIndex` prop for Dropdown.
