### ISSUE TITLE
设置  'ant-prefix' 不方便

### ISSUE THREAD

**Issue by Lcj-space** [ant-design/ant-design#31263]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
针对 hook形式调用的组件不生效，列如 message.erro() ,  Modal.confirm()

### What does the proposed API look like?
加在全局上的 prefix 能够直接生效，不需要再去用什么 useConfrom ,useMessage() 再去拿一遍，针对复杂页面设置成本有点大。

**Comment by Lcj-space** [comment]
![image](https://user-images.githubusercontent.com/22415092/124423513-e5cab780-dd97-11eb-89f8-1cbae4c7cea5.png)
就算 context 不共享为何不设置在window 上这样不就解决拿不到的问题了吗

**Comment by PeachScript** [comment]
`window` 是脱离 React 生命周期的，并且工程上也不优雅；除了 `ContextProvider`，也可以通过 `message.config` 全局配置：https://ant.design/components/message-cn/#message.config

**Comment by afc163** [comment]
https://ant.design/components/config-provider-cn/#ConfigProvider.config()-4.13.0+

**Comment by sipuyouhe** [comment]
> https://ant.design/components/message-cn/#message.config

message.config 这段代码应该写在哪呢？我写在根文件（app.tsx）下并没有生效，还是写在 util 里面，return 出一个设置了 prefixCla 的 message 呢，求大佬赐教- -
