### ISSUE TITLE
Is there any way to make TD highly adaptive, only two or three data will auto occupy table, and larges data will be scrolled

### ISSUE THREAD

**Issue by Homebrew1** [ant-design/ant-design#31260]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is there any way to make TD highly adaptive, only two or three data will occupy table, and larges data will be scrolled

### What does the proposed API look like?
<a-table autoContentHeight />

**Comment by Homebrew1** [comment]
I proposed API : <a-table autoContentHeight />

**Comment by afc163** [comment]
Duplicate of #29082
