### ISSUE TITLE
Cascader级联控件异步加载数据的时候有“加载中”的状态吗？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#3126]
#### 您做了什么？

引入Cascader控件，数据使用异步加载

#### 您期待的结果是：

点击父节点请求数据的时候应该告诉客户端处于加载数据的状态

#### 实际上的结果是：

页面没有处于加载状态也，当请求慢的时候给人的感觉就是点了没反应

#### 可重现的在线演示

http://codepen.io/anon/pen/rrjjqw?editors=0010

**Comment by benjycui** [comment]
`loadData` https://github.com/react-component/cascader

**Comment by aw6658913** [comment]
我那个在线演示就是看的这个demo写的，demo上也是木有加载状态的，而且如果下拉选择的某个选项内容一长右边的箭号就不见了，这个我在线演示也有展现出来
