### ISSUE TITLE
[Form]Form.Item的render props形式在通过form.setFieldsValues设置初始值的时候会丢失部分表单值

### ISSUE THREAD

**Issue by wood3n** [ant-design/ant-design#31265]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/biaodanfangfadiaoyong-antd4166-forked-c5h5c?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
在demo页面中，首先点击类型为 type1 的表格行编辑打开抽屉表单，此时会展示租户和集群的初始值；然后关闭抽屉表单，再次点击 type1 的表格行编辑按钮，此时打开抽屉表单以后，租户和集群初始值就没有了...

### What is expected?
在多次打开抽屉表单以后，通过 form.setFieldsValues 设置表单初始值，不应该丢失部分初始值

### What is actually happening?
在多次打开抽屉表单以后，通过 form.setFieldsValues 设置表单初始值以后丢失了部分值

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14 |
| System | window10 1809 |
| Browser | Chrome 91 |

**Comment by wood3n** [comment]
没人帮帮可怜的孩子吗😭

**Comment by afc163** [comment]
看上去数据被意外修改了。@zombieJ

**Comment by zombieJ** [comment]
从性能角度考虑内部赋值是 mutable 的，我感觉文档需要加一下：
https://codesandbox.io/s/biao-dan-fang-fa-diao-yong-antd-4-16-6-forked-ide20?file=/FormDrawer.tsx
