### ISSUE TITLE
There is a hidden 'div' outside the body when you select a part text of textarea. This will cause height anomalies. 当鼠标选中多行文本框中的部分文字时，body外会出现一个不可见的div，这会导致页面高度异常。

### ISSUE THREAD

**Issue by CheneyH** [ant-design/ant-design#31272]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-puvhq?file=/index.js)

### Steps to reproduce
The mouse selects the first part of the text in the input box
用鼠标选中输入框终的前面一部分文字

### What is expected?
There is a scroll bar in the bottom part.
期望只有bottom内部有滚动条

### What is actually happening?
There are a scroll bar in the bottom part and another one out the bottom part.
bottom内部和外部都出现滚动条

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | lastest |
| System | windows 10 |
| Browser | chrome 91.0.4472.124 |

---
我希望固定顶部，且滚动条出现在底部而不是整个页面，所以选用了这样的布局，而不是固定定位。这里选中文字后出现一个额外的div，会导致页面高度异常，而且这个异常的高度是根据你选中文字所在位置变化的，这就导致滚动条很混乱。
目前在Microsoft Edge  91.0.864.64 和 Firefox 2021.6都没有发现这个额外的div，只有 chrome 91.0.4472.124 出现了

**Comment by PeachScript** [comment]
Chrome 91.0.4472.114 隐身模式无法复现，这种情况大概率是某个 Chrome 浏览器扩展导致的，可以排查下

**Comment by CheneyH** [comment]
> Chrome 91.0.4472.114 隐身模式无法复现，这种情况大概率是某个 Chrome 浏览器扩展导致的，可以排查下

排查到了，是划词翻译插件导致的。谢谢
