### ISSUE TITLE
2.0Tabs是否可以加入动画结束后的回调

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#3127]
#### 发生问题的环境是：

- antd 版本: 2.0.0-beta.10
- 操作系统及其版本: windows10
- 浏览器及其版本: 54.0.2832.2 dev-m (64-bit)

#### 问题：

2.0的Tabs，ant-tabs-content的div会有transform属性，导致一些用到fixed实现全屏覆盖的控件无法使用（例如浏览图片的控件），希望能加入动画结束后的回调，这样就可以在动画结束后去掉transform

**Comment by benjycui** [comment]
Ref: https://github.com/ant-design/ant-design/issues/3088

**Comment by yiminghe** [comment]
fixed 的东西渲染到 body

**Comment by infeng** [comment]
我现在的解决方法就是fixed的东西渲染到body
