### ISSUE TITLE
ant-design-pro为啥没有V5了？

### ISSUE THREAD

**Issue by kevinpursuing** [ant-design/ant-design#31275]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
V5在配置性上灵活性更高

### What does the proposed API look like?
官网上明确写了可以选v4,v5,但是在运行命令的时候，没有这个选项了，是什么原因呢？ 安装v5版本的antd pro

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/8656

最新的 create-umi 默认已经是 V5 了。
