### ISSUE TITLE
tree组件disabled状态下，默认勾选一个叶子结点，其父节点没有标志选中的方块

### ISSUE THREAD

**Issue by Mulberry-Leaf** [ant-design/ant-design#31278]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ytwjv)

### Steps to reproduce
demo里设置defaultCheckedKeys={['0-0-0']} 

### What is expected?
父节点能与非disabled状态下一样，有方块表示其下级有选中节点

### What is actually happening?
父节点无任何效果表示其有选中子节点

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | react |
| System | macOS Mojave 10.14.6 |
| Browser | chrome 91.0.4472.114 |

**Comment by afc163** [comment]
https://ant.design/components/tree-cn/#disabled-%E8%8A%82%E7%82%B9%E5%9C%A8%E6%A0%91%E4%B8%AD%E7%9A%84%E5%85%B3%E7%B3%BB%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F
