### ISSUE TITLE
Is there any chance to do a callback after select both dates in RangePicker?

### ISSUE THREAD

**Issue by minatoyukina** [ant-design/ant-design#31285]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
sorry for my bad English but onChange and onOpenChange work no good

### What does the proposed API look like?
after select both dates then I can setState and fetch data

**Comment by afc163** [comment]
Use `onChange` in any situation.
