### ISSUE TITLE
被Form.Item包裹的Select组件中Option的value属性为number类型时，选择某一项后会触发whitespace校验导致不通过

### ISSUE THREAD

**Issue by Freedom555** [ant-design/ant-design#31287]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-gtmtdj?file=index.js](https://stackblitz.com/edit/react-gtmtdj?file=index.js)

### Steps to reproduce
1. 将字段“Gender”的3个Option的value分别设置为number类型的11、22、33。
2. 在字段“Gender”的rules中添加以下代码：
         {
            whitespace: true,
            message: 'nonstandard input!'
          }
3. 保存并进行Gender的选择。

### What is expected?
选择了某一项后不会触发whitespace校验。

### What is actually happening?
选择了某一项后触发了whitespace校验，不通过。whitespace的文字描述是：“如果字段仅包含空格则校验不通过”。所以这里出现了逻辑混乱。

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Chrome 85.0.4183.83 |

**Comment by afc163** [comment]
https://github.com/yiminghe/async-validator/#whitespace

https://github.com/ant-design/ant-design/issues/31325#issuecomment-876573668
