### ISSUE TITLE
RangePickerProps引不到

### ISSUE THREAD

**Issue by Zardddddd60** [ant-design/ant-design#31280]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`import { DatePicker, RangePickerProps } from 'antd';` 
时会报错：“"antd"”没有导出的成员“RangePickerProps”。你是否指的是“DatePickerProps”?

### What does the proposed API look like?
import { DatePicker, RangePickerProps } from 'antd';
不报错

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/20900/files#diff-9ae4ee6e3913b577b3f8ff8a9bd5346975f505edd6953b8a0d7b36127de69fd8R12

**Comment by ahmedali5530** [comment]
```ts
import {RangePickerProps} from "antd/lib/date-picker";

//Error:(8, 41) TS2312: An interface can only extend an object type or intersection of object types with statically known members.
interface LocalRangePickerProps extends RangePickerProps {
  someProp?: number;
}
```
I am getting this error while extending this type with my interface
