### ISSUE TITLE
when use upload component upload java compiled file with window 10, file.type is empty string. but macOs is ok

### ISSUE THREAD

**Issue by pipijoe** [ant-design/ant-design#31281]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
with window can get file type when use upload component to uplaod file like application.jar 

### What does the proposed API look like?
file.type=application/java-archive with window

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12838#issuecomment-541723714
https://github.com/ant-design/ant-design/issues/17549#issuecomment-509592577
