### ISSUE TITLE
table columns width not working when text is long（表格列宽设置在文本过长时会失效）

### ISSUE THREAD

**Issue by stanzah** [ant-design/ant-design#31290]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ju9j0)

### Steps to reproduce
scroll={{ x: true }}
scroll={{ x: '100%' }}

以上设置都不能正常展示。

只有设置了 scroll={{ x: 'max-content' / 60000 }} 可以正常展示

### What is expected?
表格正常展示。

### What is actually happening?
表格列挤在了一起

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | Chrome/91.0.4472.124 |

**Comment by afc163** [comment]
对，这种情况建议用 `max-content`，尽可能显示全。
