### ISSUE TITLE
Form.Item shouldUpdate拿不到其他【已销毁】表单项的最新值

### ISSUE THREAD

**Issue by yanhaijing** [ant-design/ant-design#31297]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4166-forked-qo6k7?file=/index.js)

### Steps to reproduce
1. 点击flag为展示字段
2. 输入name2的值
3. 输入name3的值
4. 点击flag为隐藏字段
5. 此时name3还会展示（再次修改表单时才会隐藏）

### What is expected?
5. name3隐藏

### What is actually happening?
5. 此时name3还会展示（再次修改表单时才会隐藏）

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17 |
| System | Mac |
| Browser | Chrome |

---
name3里面拿不到name2的最新值，要再次编辑表单才能拿到

**Comment by afc163** [comment]
name2 和 name3 的值是在同一个 render phase 中更新的，name3 内获得 name2 的值时，name2 的 Form.Item 还未完成销毁（渲染结束才会更新）。

**Comment by afc163** [comment]
需要 @zombieJ 来看看这类级联的联动如何才是最佳写法。

**Comment by yanhaijing** [comment]
@afc163 感恩，目前看 只有多级 依赖联动才会有问题，问了同事，其他人也遇到过类似问题，他们感觉是个antd的bug
希望能够 官方解决，如果我们自己在flag的onchange里面 做setFields的话，复杂的表单会很脏 

比较希望 的效果就是不展示的组件form中就没有值了，而不是下次才更新

**Comment by afc163** [comment]
不一定是 bug，看代码是预期的。
可能是个问题，这类需求还蛮多且合理的，要找到最佳实践。

**Comment by afc163** [comment]
> 比较希望 的效果就是不展示的组件form中就没有值了，而不是下次才更新

这样实现的话，有可能变成无限渲染循环。（表单项销毁触发值改变，值改变触发销毁，再次触发值改变）

**Comment by yanhaijing** [comment]
嗯嗯，感觉这个UI不一致会很难受，还需要我自己处理很多reset逻辑，其他表单方案也有类似问题吗？

**Comment by yanhaijing** [comment]
一般稍微复杂表单 都会 存在各种复杂的联动，噩梦 o(╥﹏╥)o

**Comment by afc163** [comment]
一个比较合理的方式是切换到隐藏时清空 name2 的值：https://codesandbox.io/s/jibenshiyong-antd4166-forked-7x7jb?file=/index.js

**Comment by yanhaijing** [comment]
> 一个比较合理的方式是切换到隐藏时清空 name2 的值：https://codesandbox.io/s/jibenshiyong-antd4166-forked-7x7jb?file=/index.js

@afc163 是的 ，这是直观 的方式 ，但是 这种方式其实是把复杂逻辑 推给 业务了，组件库在 偷懒，复杂的 联动的表单，这样维护起来会很麻烦 ，维护很多reset关系 ，且联动变化时，很容易 出 bug，还是希望组件库 层面能 解决 会好一些

还有个思路是把name2  name3 下沉一级组件

**Comment by yanhaijing** [comment]
> 需要 @zombieJ 来看看这类级联的联动如何才是最佳写法。

@zombieJ 这个能能快给个最佳写法吗？

**Comment by zombieJ** [comment]
感觉可以拓展一下 `dependencies`，如果字段消失再触发一次。

**Comment by yanhaijing** [comment]
@zombieJ 那这个大概多久能支持吗？

> 感觉可以拓展一下 `dependencies`，如果字段消失再触发一次。

**Comment by zombieJ** [comment]
@yanhaijing，有兴趣给 `rc-field-form` 来个 PR 不？~

**Comment by yanhaijing** [comment]
@zombieJ 那可以描述下怎么改的 思路吗 ？这句话，我其实没太看懂要怎么改呢

> 感觉可以拓展一下 `dependencies`，如果字段消失再触发一次。

**Comment by zombieJ** [comment]
现在的逻辑是 `dependencies` 值变化会触发 renderProps 模式的 Field 更新，添加的逻辑是指如果 `dependencies` 字段消失时也触发一次更新

**Comment by baiziyu-fe** [comment]
@yanhaijing 我觉得可以在name2的FormItem那里对于shouldUpdate传入callBack的逻辑验证中加入对于flag这一字段的验证，
因为你的name3出现的满足条件是 `values.flag === true && values.name2 !== ''`。
https://codesandbox.io/s/jibenshiyong-antd4166-forked-erpog

**Comment by yanhaijing** [comment]
> @yanhaijing 我觉得可以在name2的FormItem那里对于shouldUpdate传入callBack的逻辑验证中加入对于flag这一字段的验证，
> 因为你的name3出现的满足条件是 `values.flag === true && values.name2 !== ''`。
> https://codesandbox.io/s/jibenshiyong-antd4166-forked-erpog

@baiziyu-fe 你这个demo的效果 也是不对的啊

**Comment by baiziyu-fe** [comment]
> > @yanhaijing 我觉得可以在name2的FormItem那里对于shouldUpdate传入callBack的逻辑验证中加入对于flag这一字段的验证，
> > 因为你的name3出现的满足条件是 `values.flag === true && values.name2 !== ''`。
> > https://codesandbox.io/s/jibenshiyong-antd4166-forked-erpog
> 
> @baiziyu-fe 你这个demo的效果 也是不对的啊

@yanhaijing 我看了下是因为我在codebox上的代码没有更新
```JavaScript
<Form.Item
          shouldUpdate={(prev, curr) => {
            return prev.name2 !== curr.name2 || prev.flag !== curr.flag;
          }}
          noStyle
        >
          {({ getFieldValue }) => {
            console.log("name3", getFieldValue("name2"));
            return getFieldValue("name2") && getFieldValue("flag") ? (
              <Form.Item label="name3" name="name3">
                <Input />
              </Form.Item>
            ) : null;
          }}
        </Form.Item>
```

把form.item修改成这样就可以达到你想要的效果了

**Comment by baiziyu-fe** [comment]
可以看看这个 
https://codesandbox.io/s/jibenshiyong-antd4166-forked-fk6zt?file=/index.js

**Comment by yanhaijing** [comment]
> @yanhaijing，有兴趣给 `rc-field-form` 来个 PR 不？~

https://github.com/react-component/field-form/pull/329
@afc163 @zombieJ 看看呢
