### ISSUE TITLE
Timepicker range component need defaultOpenValue

### ISSUE THREAD

**Issue by wandongming** [ant-design/ant-design#31291]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If I need to select shop opening hours, it is better to show the default time 8am to 10pm. Now it does not work on Timepicker defaultOpenValue.

### What does the proposed API look like?
defaultOpenValue: [moment("08:00", format), moment("18:00", format)]

**Comment by PeachScript** [comment]
> Same props from RangePicker of DatePicker.

You can use `defaultValue={[moment('08:00', 'HH:mm'), moment('18:00', 'HH:mm')]}`

**Comment by afc163** [comment]
Is it supported already? https://github.com/ant-design/ant-design/issues/21153
