### ISSUE TITLE
Progress with undetermined status

### ISSUE THREAD

**Issue by filoucrackeur** [ant-design/ant-design#31295]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i need a loader where the end is not defined.
so i propose to add undetermined={true} as new argument the loader is an infinite animation bar.

### What does the proposed API look like?
<Progress undetermined={true}/>

**Comment by afc163** [comment]
You can try https://ant.design/components/spin/ instead of Progress.
