### ISSUE TITLE
Horizontal Form.Item using flex layout should be "nowrap" on Row style

### ISSUE THREAD

**Issue by Artoria-0x04** [ant-design/ant-design#31296]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jbpjq?file=/index.js)

### Steps to reproduce
Already shown in the example, to see the desired style, uncomment line 20.

### What is expected?
Form using layout "horizontal" shouldn't let form-control zone wrap, which currently uses `flex-flow: row wrap;`. Each horizontal row should contain its controls in the `.ant-form-item-control` container, which means changing style to `flex-flow: row nowrap;`.

### What is actually happening?
See the example.

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14.0 |
| System | macOS 11.4 |
| Browser | Chrome Version 91.0.4472.114 (Official Build) (x86_64) |

---
Only apply wrap in vertical layout.

**Comment by afc163** [comment]
see https://codesandbox.io/s/antd-reproduction-template-forked-jbpjq?file=/index.js

**Comment by Artoria-0x04** [comment]
> see https://codesandbox.io/s/antd-reproduction-template-forked-jbpjq?file=/index.js

It's the same sandbox I've provided and I froze it before so I don't see any changes. Could you elaborate more?

**Comment by Artoria-0x04** [comment]
Will not closed issues be seen anymore? Then I have to open a new one. @afc163

**Comment by afc163** [comment]
See https://codesandbox.io/s/antd-reproduction-template-forked-d8k4m

Sorry, I forgot to save my codesandbox.

**Comment by Artoria-0x04** [comment]
@afc163 It's just the workaround I provided and I am using it now, and the problem won't show when the form has enough width. But I think the `nowrap` override is redundant on the horizontal layout, which should always make labels on the left side and controls on the right, even the controls wrap.

**Comment by xseman** [comment]
I have the same problem, why is this closed? The answer feels like a hack.
