### ISSUE TITLE
Modal可否提供函数式的调用方式

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design#31309]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- 目前看文档好像只有特殊状态的弹窗提供函数式的调用方式，
- 普通的弹窗需要提前在render声明DOM结构，感觉不是很灵活

### What does the proposed API look like?
`Modal.open()`

**Comment by yoyo837** [comment]
https://ant.design/components/modal-cn/#Modal.method()

有的，多翻一下下面

**Comment by PeterChen1997** [comment]
> https://ant.design/components/modal-cn/#Modal.method()
> 
> 有的，多翻一下下面

好像没有.open() 的 API 貌似？
