### ISSUE TITLE
Popover  在 Button disabled 的时候也会触发

### ISSUE THREAD

**Issue by Hucy** [ant-design/ant-design#31305]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sanchonghongfafangshi-antd4166-forked-mlfjw?file=/index.js:331-339)

### Steps to reproduce
点击禁用按钮

### What is expected?
Popover  不应该触发

### What is actually happening?
Popover  触发

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.1 |
| System | Windows |
| Browser | Chrome 91.0.4472.124 |

**Comment by PeachScript** [comment]
Duplicated with #25318, closed
