### ISSUE TITLE
Icon 使用的相关资源支持开启 cross-origin isolation 的页面使用

### ISSUE THREAD

**Issue by everywill** [ant-design/ant-design#31310]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
SharedArrayBuffer 将只能在 cross-origin isolation 环境中被使用，页面开启 cross-origin isolation 要求跨域资源有指定响应头 Cross-Origin-Resource-Policy: cross-origin，Icon 使用的相关资源可否添加此响应头？

### What does the proposed API look like?
Icon 使用的相关静态资源添加响应头 Cross-Origin-Resource-Policy: cross-origin

**Comment by afc163** [comment]
@
