### ISSUE TITLE
使用message.config的getContainer进行不同页面多次配置，导致message有时不提示或在其他页面提示

### ISSUE THREAD

**Issue by huangzongming** [ant-design/ant-design#31315]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
getContainer	配置渲染节点的输出位置。希望可以正确渲染节点，
例如：message.config({
  getContainer: () => document.getElementsByClassName(‘test’)[0],
});
则每次进入此页面，message可以做到正常提示。

### What does the proposed API look like?
getContainer	配置渲染节点的输出位置。

**Comment by yoyo837** [comment]
不是全局的为什么要用全局配置来实现呢！

**Comment by huangzongming** [comment]
> 不是全局的为什么要用全局配置来实现呢！

message可以每个页面单独配置吗？

**Comment by yoyo837** [comment]
不可以，他就是全局的，除非你是单页的。

**Comment by huangzongming** [comment]
主要是解决proTable全屏后message不提示的问题，所以才挂载到了每个ProTable上。

> 不可以，他就是全局的，除非你是单页的。

主要是解决proTable全屏后message不提示的问题，所以才挂载到了每个ProTable上。我试下挂载到一个统一的dom节点上

**Comment by huangzongming** [comment]
@afc163  https://github.com/ant-design/ant-design-pro/issues/8692 可以看下这个问题

**Comment by solitia7125** [comment]
如果是要在全屏下有任何气泡组件的话，建议在最顶级加上ConfigProvider组件传入getPopupContainer方法:
`<ConfigProvider getPopupContainer={(node) => document.fullscreenElement ? document.fullscreenElement : document.body}>{chidren}</ConfigProvider>`

当然上面的方法只对hook生成的context有效，对于动态生成的，如Modal.success也可以直接传入getContainer方法

不过额外还需要考虑另外两点
1. 有些组件生成的时候会带有父标签，即使指定了getContainer，生成的位置还是会在父标签中，如Notification和Popover。
    当然只要销毁父标签即可，具体如何销毁父标签可以查阅文档
2. 全屏化方法会有兼容性问题，具体请查阅mdn。

希望能对你有帮助 ; )

**Comment by towertop** [comment]
@solitia7125 意思是这方法没法解决Modal不弹出的问题，所有Modal地方都要显式设置getContainer方法？
