### ISSUE TITLE
Form.Item rules validateTrigger "onBlur" 不工作

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#31318]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4166-forked-y30vc?file=/index.js)

### Steps to reproduce
在第一个输入框输入值，删掉，然后点击其他地方失去焦点

### What is expected?
触发校验显示错误信息

### What is actually happening?
没有触发校验

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome  87.0.4280.141 |

---
官网描述`设置触发验证时机，必须是 Form.Item 的 validateTrigger 的子集`, 但是没有找到`validateTrigger`可以设置哪些值的说明.. 所以不确定是本来就不支持`onBlur` 还是 bug

**Comment by afc163** [comment]
It is a bug, trace #28378

**Comment by mtiger95** [comment]
同问
