### ISSUE TITLE
incorrect menu width calculation 

### ISSUE THREAD

**Issue by akaguny** [ant-design/ant-design#31323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antd-menu-4-16-vj77r2.stackblitz.io](https://antd-menu-4-16-vj77r2.stackblitz.io)
https://stackblitz.com/edit/antd-menu-4-16-vj77r2

### Steps to reproduce
![image](https://user-images.githubusercontent.com/3505959/124932090-72c97700-e00b-11eb-82a2-da9bee637780.png)
# show header
![image](https://user-images.githubusercontent.com/3505959/124932291-a0aebb80-e00b-11eb-867e-b91467713a27.png)
# show menu items
![image](https://user-images.githubusercontent.com/3505959/124932352-ac01e700-e00b-11eb-8013-6c0eb7033e8a.png)
# hide menu items
![image](https://user-images.githubusercontent.com/3505959/124932530-d3f14a80-e00b-11eb-891c-b5b69ce750b1.png)
# show menu items
![image](https://user-images.githubusercontent.com/3505959/124932591-e075a300-e00b-11eb-978d-e818910659fc.png)

### What is expected?
# items showed correctly
![image](https://user-images.githubusercontent.com/3505959/124932642-ebc8ce80-e00b-11eb-97e8-52bfcd9a3f28.png)
In antd was work as expected, reproduction https://antd-menu-4-10.stackblitz.io
https://stackblitz.com/edit/antd-menu-4-10

### What is actually happening?
# items collapsed
![image](https://user-images.githubusercontent.com/3505959/124933066-419d7680-e00c-11eb-87cf-f2d7b110054a.png)

Maybe relatest to #30879 #30907 #31043 #30672 

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Version 91.0.4472.124 (Official Build) (64-bit) |

**Comment by Yunfly** [comment]
when hide menu elements ,menu'whdth change to 0 px ;so You need to reserve enough width for the menu, for example, set <Menu> style flex:1 ;

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/30813#issuecomment-854625752

**Comment by akaguny** [comment]
resolved with flex: auto.
in reproduce:
```
<Menu
              theme={this.state.theme}
              onClick={this.handleClick}
              style={{ flex: 'auto' }}
```
