### ISSUE TITLE
想给Input.TextArea传入ref，然后监听ref.current，但是发现源码上没有将ref传递给children

### ISSUE THREAD

**Issue by binyellow** [ant-design/ant-design#31320]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiangyaonadaotextareaderefdanshiyuanmashangmeiyoujiangrefchuangeichildren-antd4166-forked-ixvn0?file=/package.json:385-392)

### Steps to reproduce
进入页面报Argument appears to not be a ReactComponent. Keys: resizableTextArea,focus,blur

### What is expected?
不报错

### What is actually happening?
报错Argument appears to not be a ReactComponent. Keys: resizableTextArea,focus,blur

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14.0 |
| System | macOS |
| Browser | chrome 91.0.4472.114 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13277#issuecomment-873875488
