### ISSUE TITLE
tree组件点击标题折叠或展开

### ISSUE THREAD

**Issue by lxg-design** [ant-design/ant-design#31328]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tree组件点击标题折叠或展开

### What does the proposed API look like?
tree组件点击标题折叠或展开

**Comment by afc163** [comment]
https://ant.design/components/tree-cn/#components-tree-demo-directory
