### ISSUE TITLE
Select virtual scroll last item not visible

### ISSUE THREAD

**Issue by Mohamed-Ghanem** [ant-design/ant-design#31321]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/option-group-antd4166-forked-8ii0u?file=/index.js)

### Steps to reproduce
1. Scroll down to the end of the select dropdown.
2. Look for the last item, it will be invisible.

### What is expected?
When scrolling down, find the last item in the list.

### What is actually happening?
When scrolling down, last 1 or 2 items are hidden.

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14 |
| System | macOS Big Sur 11.2.3 |
| Browser | Version 90.0.4430.93 (Official Build) (x86_64) |

---
I tried listItemHeight found in FAQ but it did't fix the problem.
https://ant.design/components/select/#Why-sometime-customize-Option-cause-scroll-break

Is there a way or workaround to style or add margins to list item without messing with the scroll?
Or is it a must to have the same height for all items including paddings and margins?

I also tried with normal select without grouping and it had the same issue:
https://codesandbox.io/s/select-with-search-field-antd4166-forked-pjzl8?file=/index.js

**Comment by afc163** [comment]
<img width="269" alt="图片" src="https://user-images.githubusercontent.com/507615/125017097-08fdab80-e0a5-11eb-82ae-f02cd8685bfd.png">

I can see last item in my machine.

**Comment by zombieJ** [comment]
<img width="329" alt="截屏2021-07-13 下午12 34 21" src="https://user-images.githubusercontent.com/5378891/125391216-a7a44800-e3d6-11eb-92f0-d282f1169330.png">

Your list item height is less than `41`. Remove `listItemHeight={41}`.

**Comment by Mohamed-Ghanem** [comment]
@zombieJ list item height is not the source of the issue, it was a trial of me to fix the issue (a solution if worked wont be my ultimate one) but it did not.
I forked the issue, removed list item height, and the issue still exists.
Here is the link of the newly forked one: https://codesandbox.io/s/option-group-antd4166-forked-qn65e
And here is a screenshots of hidden item 'garply'
<img width="930" alt="Screen Shot 2021-07-14 at 11 25 36 AM" src="https://user-images.githubusercontent.com/20539096/125598555-999ddefa-17f6-4d11-baac-f5b6f656d6b0.png">
<img width="901" alt="Screen Shot 2021-07-14 at 11 25 21 AM" src="https://user-images.githubusercontent.com/20539096/125598576-1a946652-d4f6-4777-9a81-e70b463e75ea.png">

Also in my humble opinion, the main issue here is the margins around 'ant-select-item-group', the item group height is 26px and margin top is 15px, here is a screenshot for it:
<img width="334" alt="Screen Shot 2021-07-14 at 11 28 26 AM" src="https://user-images.githubusercontent.com/20539096/125598849-db8fb7a0-16ac-482c-aa83-60369db35567.png">

**Comment by Mohamed-Ghanem** [comment]
@afc163 @zombieJ can we reopen this as it is not fixed yet?

**Comment by LonHon** [comment]
遇到了同样问题， 第一次打开能正常滚动， 选择一次之后  再次打开下拉菜单，无法滚动&无滚动条，DOM上能看到是存在数据的

I have the same problem, the first time I open it, I can scroll normally, after I select it once, I open the select dropdown again, I can't scroll & no scroll bar, we can see that there is select-item on the DOM


![image](https://user-images.githubusercontent.com/19330620/126302266-af859362-e25d-4fdb-9658-f8b2ad291d24.png)

**Comment by liuhaijundegithub** [comment]
+ 1

**Comment by liuhaijundegithub** [comment]
i face the same problem too, we should reopen this as not fixed

**Comment by Mohamed-Ghanem** [comment]
@afc163 @zombieJ any updates about this or shall I open a new one?

**Comment by heying517** [comment]
> i face the same problem too, we should reopen this as not fixed

me too

**Comment by Mohamed-Ghanem** [comment]
Refer to this comment to find the solution.
https://github.com/ant-design/ant-design/issues/32071#issuecomment-914854632
