### ISSUE TITLE
whitespace validation rule does not work with objects

### ISSUE THREAD

**Issue by fgblomqvist** [ant-design/ant-design#31325]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd4166-forked-0371h?file=/index.js)

### Steps to reproduce
Set `rules` for a field that returns an object to `{[{ whitespace: true, message: "required" }]}` and see how it always fails.

### What is expected?
An object != whitespace if the object != undefined.

### What is actually happening?
The validation fails.

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17 |
| System | N/A |
| Browser | N/A |

---
Check the browser console, looks like the async validation lib is throwing an error.

**Comment by fgblomqvist** [comment]
Either this needs to be fixed or the docs need to be updated to specify that `whitespace` is not compatible with all types.

**Comment by afc163** [comment]
`whitespace` is used for string type, PR is welcome to update documentation.
