### ISSUE TITLE
TimePicker 4.x交互和3.x比起来复杂难用

### ISSUE THREAD

**Issue by chua1989** [ant-design/ant-design#31331]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/time-picker-cn/](https://ant.design/components/time-picker-cn/)

### Steps to reproduce
点击时间选择框，弹出时间选择，点击选择时间

### What is expected?
期望和3.x一样，点击时间就更改当前的时间

### What is actually happening?
实际结果是需要点击确定才更改选中时间

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by chua1989** [comment]
很想知道4.x基于什么原因考虑将TimePicker改成这样的交互方式

**Comment by x1mrdonut1x** [comment]
I would love to have an event fired when selecting a new time without having to click "OK"

**Comment by zombieJ** [comment]
merge into #21189
