### ISSUE TITLE
请问下组件里面的源码在哪里？看见组件里面直接引入了 Rc-组件名。  这个Rc-组件  在哪里呢

### ISSUE THREAD

**Issue by livelyPeng** [ant-design/ant-design#31332]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
请问下组件里面的源码在哪里？看见组件里面直接引入了 Rc-组件名。  这个Rc-组件  在哪里呢

### What does the proposed API look like?
请问下组件里面的源码在哪里？看见组件里面直接引入了 Rc-组件名。  这个Rc-组件  在哪里呢

**Comment by afc163** [comment]
https://github.com/react-component/

**Comment by livelyPeng** [comment]
@afc163 谢谢！

**Comment by livelyPeng** [comment]
@afc163 不对，大哥，package.json里面很多Rc-组件

**Comment by livelyPeng** [comment]
"rc-cascader": "~1.4.0",
    "rc-checkbox": "~2.3.0",
    "rc-collapse": "~3.1.0",
    "rc-dialog": "~8.5.1",
    "rc-drawer": "~4.3.0",
    "rc-dropdown": "~3.2.0",
    "rc-field-form": "~1.20.0",
    "rc-image": "~5.2.4",
    "rc-input-number": "~7.1.0",
    "rc-mentions": "~1.6.1",
    "rc-menu": "~9.0.12",
    "rc-motion": "^2.4.0",
    "rc-notification": "~4.5.7",
    "rc-pagination": "~3.1.6",



这些在react-component/ 好像没找到

**Comment by yoyo837** [comment]
删评论了？

**Comment by livelyPeng** [comment]
谢谢 我知道了。我看明白了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月9日(星期五) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] 请问下组件里面的源码在哪里？看见组件里面直接引入了 Rc-组件名。  这个Rc-组件  在哪里呢 (#31332)





 
删评论了？
