### ISSUE TITLE
FormLabelAlign 在 TS 项目中，无法在外部被引用，导致 TS 报错

### ISSUE THREAD

**Issue by PeterChen1997** [ant-design/ant-design#31335]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/21072589/125059104-8e9d4d80-e0dd-11eb-80df-91ff92f570c2.png](https://user-images.githubusercontent.com/21072589/125059104-8e9d4d80-e0dd-11eb-80df-91ff92f570c2.png)

### Steps to reproduce
https://user-images.githubusercontent.com/21072589/125059104-8e9d4d80-e0dd-11eb-80df-91ff92f570c2.png

### What is expected?
export 出来，让外部 ts 正常解析

### What is actually happening?
无法解析，提示类型不符

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by PeterChen1997** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-bh4tu?file=/index.js

**Comment by afc163** [comment]
为啥需要 FormLabelAlign ，给一个没有这个会出错的例子。

**Comment by PeterChen1997** [comment]
> 为啥需要 FormLabelAlign ，给一个没有这个会出错的例子。

可能是 vscode 关联 ts 变量的时候存在问题，目前重启 ide 就可以了，感谢
