### ISSUE TITLE
在 Form 內的 Table，無法驗證 Table 裡的 rowSelection

### ISSUE THREAD

**Issue by Bonnie8ni** [ant-design/ant-design#31347]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-mountain-l5hu0?file=/src/App.js)

### Steps to reproduce
想要判定 rowSelection (Checkbox) 為必填

### What is expected?
可以判定 rowSelection (Checkbox) 為必填

### What is actually happening?
在專案內實際上會判定到 pagination 的原件上，codesandbox 實現不出來

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | mac os |
| Browser | chrome |

---
在Form裡的Table驗證是不是不支援，要自己寫在 column render 做驗證呢？

**Comment by zombieJ** [comment]
参考自定义表单空间，将 Table 的 rowSelection 封装一下：
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by Bonnie8ni** [comment]
@zombieJ 
照你提供的方式可以成功判斷 Table 內的 Checkbox
但是未選擇的時候紅框會顯示在 pagination 上，不知道為什麼?

![2021-07-12 14_23_16-Window](https://user-images.githubusercontent.com/15052151/125241613-3f922b00-e31e-11eb-9296-c931119b4be8.png)

**Comment by AlanCutFlim** [comment]
> @zombieJ
> 照你提供的方式可以成功判斷 Table 內的 Checkbox
> 但是未選擇的時候紅框會顯示在 pagination 上，不知道為什麼?
> 
> ![2021-07-12 14_23_16-Window](https://user-images.githubusercontent.com/15052151/125241613-3f922b00-e31e-11eb-9296-c931119b4be8.png)

这里有个 [issue](https://github.com/ant-design/ant-design/issues/11903) 和它相关，目前我是覆盖样式解决的，不过这样感觉不太好

**Comment by zombieJ** [comment]
嗯，现在 Form 状态变更会覆盖一些组件的样式。实现不太好
