### ISSUE TITLE
表头在配置sort且在内容为空字符串时展示异常

### ISSUE THREAD

**Issue by dryqiao** [ant-design/ant-design#31341]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-and-scroll-bar-with-the-page-antd4163-forked-gln8e?file=/index.js)

### Steps to reproduce
见codesandbox链接

### What is expected?
表头能有类似max-content的配置，根据内容撑开，不像现在这样表头宽度由表格内容撑开，导致表头重叠

### What is actually happening?
在配置了排序时，当单元格数据长度小于表头数据长度时，表头宽度是根据内容宽度算的，导致表头重叠

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | latest |
| System | mac big sur |
| Browser | chrome latest |

**Comment by afc163** [comment]
建议指定列宽度。

**Comment by dryqiao** [comment]
Hi, 还有几个问题：
1. 表格配置：scroll={{x:true}} sticky，列宽200  结果：列宽无效，左右滑动无效
2.表格配置：scroll={{x:true}} sticky, data为[],不设置列宽  结果：表头异常，第一列撑满，其他列全部重叠
3.表格配置：scroll={{x:true}}, data为[] ，列宽200 结果：列宽无效

可以在链接里复现：https://codesandbox.io/s/table-bug-review-mhqij?file=/src/index.js

另一个兼容性问题：
columns里设置sorter，无列宽，table设置sticky scroll={{ x: 'max-content', y: "100vh" }}，在safari上展示错乱

@afc163 col的宽度计算有问题，并且以上几个属性互相之间有问题，麻烦看下，谢谢~

**Comment by afc163** [comment]
https://codesandbox.io/s/table-bug-review-forked-6n0rl 建议加列宽配合 `x: 'max-content'`。
