### ISSUE TITLE
@ant-design/compatible的Form，validateFieldsAndScroll检验TextArea 不走回调方法，导致无法进行操作

### ISSUE THREAD

**Issue by shijunwen** [ant-design/ant-design#31354]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-wescoff-j4qog?file=/src/index.js)

### Steps to reproduce
1、多行文本不填
2、点击保存
3、不打印

### What is expected?
正确执行回调

### What is actually happening?
不执行回调方法

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.1 |
| System | Windows |
| Browser | Google Chrome 88.0.4324.182（正式版本） （64 位） |

---
去掉await 还是不会打印，且多行文本报错，也不会跳到正确位置

**Comment by afc163** [comment]
看上去和 https://github.com/ant-design/ant-design/issues/31320 是一个问题，欢迎来个 PR 帮我们修复。

**Comment by afc163** [comment]
Trace #30939

**Comment by pengli2075** [comment]
请问以上问题是如何修复的？还没有解决办法。antd v4.16.3 也不会执行 @ant-design/compatible的Form 的validateFieldsAndScroll

**Comment by Bierxiensi** [comment]
antd v4.21.6 版本 中 form的validateFieldsAndScroll方法也没有返回信息，validateFields正常 
![image](https://user-images.githubusercontent.com/40264423/190112693-8d33dc08-3c63-49cc-a2ec-566bd78b6937.png)
![image](https://user-images.githubusercontent.com/40264423/190112923-b9bca563-ed3e-465f-a7f6-3210a57fab39.png)

**Comment by Lin-Min** [comment]
请问这个问题 没人解决吗？ 4.20.2版本也还是直接跳过校验
