### ISSUE TITLE
antd expandable 展示不正确

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/ant-design#31351]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qiantaozibiaoge-antd4167-forked-yhvcp?file=/index.js)

### Steps to reproduce
1. 点击管理员模块的展开，下方显示展开嵌套的子表格
2. 子表格显示有多个重复模块

### What is expected?
1. 期望展开时就仅显示record.children的一张子表格

### What is actually happening?
目前不仅仅显示子表格，还显示了多次"管理员模块" 重复的，而且展开下面的内容为空

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.9 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-tree-data

<img width="1049" alt="图片" src="https://user-images.githubusercontent.com/507615/125243860-33f43380-e321-11eb-957e-dde2110eaca6.png">

**Comment by wangwufan** [comment]
> https://ant.design/components/table-cn/#components-table-demo-tree-data
> 
> <img alt="图片" width="1049" src="https://user-images.githubusercontent.com/507615/125243860-33f43380-e321-11eb-957e-dde2110eaca6.png">
> 
> > 表格支持树形数据的展示，当数据中有 children 字段时会自动展示为树形表格，如果不需要或配置为其他字段可以用 childrenColumnName 进行配置。

这里提的问题可是嵌套表格啊，父子结构不一样的，跟树形数据展示有什么关系

**Comment by afc163** [comment]
当你数据里有 children 字段，就默认会被当成树形表格进行展示，因此无法按照你预期的嵌套表格来渲染。
