### ISSUE TITLE
卡片标题过长时，在手机端不能显示完整内容 The title cannot be fully displayed on the mobile view

### ISSUE THREAD

**Issue by ZidiHu** [ant-design/ant-design#31353]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
组件：Card/卡片
描述：当卡片标题过长时，在手机端会自动将剩余内容变为省略号。请问是否有可能在标题过长的情况下，在手机端仍旧显示全部内容？When the card title is too long, the remaining content will be automatically changed to ellipsis on the mobile phone. Is it possible to display the entire content on the mobile phone when the title is too long?

### What does the proposed API look like?
希望有一个API可以让用户可以选择，在标题过长的情况下，自动显示省略号还是仍旧显示全部内容。It would be great if there is an API that allows users to choose whether to automatically display the ellipsis or still display the entire content when the title is too long.

**Comment by afc163** [comment]
```css
.ant-card-head-title {
  white-space: normal;
}
````

可以针对性覆盖一下样式。
