### ISSUE TITLE
当 Table 组件的 dataSource 中存在 children 字段时出错， (data || []).forEach is not a function

### ISSUE THREAD

**Issue by archx** [ant-design/ant-design#31358]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-oewno?file=/index.js)

### Steps to reproduce
当 Table 组件的 `dataSource` 中存在 `children`  字段时出错

```javascript
const columns = [
  { title: "ID", dataIndex: "id", key: "id", width: 80, ellipsis: true },
  { title: "Name", dataIndex: "name", width: 120 },
  { title: "Children", dataIndex: "children", width: 120 }
];
const dataSource = [{ id: "001", name: "admin" }];

// const dataSource = [{ id: "001", name: "admin", children: 1 }];
// TypeError
// (data || []).forEach is not a function
ReactDOM.render(
  <div className="App">
    <Table columns={columns} dataSource={dataSource} />
  </div>,
  document.getElementById("root")
);
```

>flattenData
> node_modules/antd/lib/table/hooks/useSelection.js:63
```javascript
  60 | 
  61 | function flattenData(data, childrenColumnName) {
  62 |   var list = [];
> 63 |   (data || []).forEach(function (record) {
  64 |     list.push(record);
  65 | 
  66 |     if (record && (0, _typeof2["default"])(record) === 'object' && childrenColumnName in record) {
```

### What is expected?
正常渲染

### What is actually happening?
TypeError
 (data || []).forEach is not a function

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31351#issuecomment-878021021
