### ISSUE TITLE
feat: add api to change visibility of popup overlay when finishing cascader select

### ISSUE THREAD

**Issue by zhengshuai1001** [ant-design/ant-design#31355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
添加 api 以在完成级联选择时更改弹窗的可见性

弹窗默认在选中最后一级后自动关闭。这一逻辑导致级联选择不能实现多选的功能。

想增加一个api: popupVisibleAfterSelect，如果为true，handleChange 后不会默认关闭。点击弹窗之外依然会关闭

给 rc-cascader 提交了 Pull Request：[#176](https://github.com/react-component/cascader/pull/176)

点击最后一级后自动关闭示意图：

![动画](https://user-images.githubusercontent.com/9513530/125263234-70318f00-e335-11eb-87ea-8c5fafca50e8.gif)

rc-cascader 代码：

![Snipaste_2021-07-12_17-22-28](https://user-images.githubusercontent.com/9513530/125263666-cc94ae80-e335-11eb-9e3a-534f56dff8ce.png)

### What does the proposed API look like?
popupVisibleAfterSelect

**Comment by zhengshuai1001** [comment]
rc-cascader 已修改，添加了api: hidePopupOnSelect

**Comment by afc163** [comment]
antd 这边也需要升级，补充文档。
