### ISSUE TITLE
Table组件设置勾选默认值失效

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design#31369]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js)

### Steps to reproduce
 const rowSelection = {
    onChange: (selectedRowKeys: React.Key[], selectedRows: RoleTable.RoleDataList[]) => {
      console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
      setselectSubmitKey(selectedRowKeys);
      console.log('key========', selectSubmitKey);
    },
    selectedRowKeys: selectSubmitKey,
    defaultSelectedRowKeys: selectRoleKeys,
  };
设置默认值失效，该怎么解决

### What is expected?
有没有具体案例，在设置key数组时无效

### What is actually happening?
如何解决渲染时默认勾选

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.1 |
| System | windows10 |
| Browser | 谷歌 |

**Comment by PeachScript** [comment]
请提供和问题匹配的重现链接
