### ISSUE TITLE
Transparent background for sticky header on hover

### ISSUE THREAD

**Issue by CHERiPP** [ant-design/ant-design#31362]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9374n)

### Steps to reproduce
Scroll down on table until header got sticked and hover on column in header

### What is expected?
When hovering over the sticked column header, the table data should not be visible

### What is actually happening?
Now, when you hover over the sticked column header, the column data is visible and they overlap the column name

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Google chrome |

**Comment by afc163** [comment]
Similar to https://github.com/ant-design/ant-design/pull/30972, let me check it later.

**Comment by CHERiPP** [comment]
I made a mistake in the name of the issue. It's about a fixed header and not about column (like in #30972)
![image](https://user-images.githubusercontent.com/16335994/125299084-76be0780-e331-11eb-8baa-3c411ec9b16a.png)
