### ISSUE TITLE
数字输入框InputNumber中文输入小数点显示2个点

### ISSUE THREAD

**Issue by Greatwallycc** [ant-design/ant-design#31370]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
1、antd数字输入框已经有值，输入法切换到中文
2、光标定位到输入框，输入小数点“.”，此时输入框显示两个小数点
3、接着再输入其他数字，因为校验失败小数点和小数点后的数字都没了

### What is expected?
可以正常输入

### What is actually happening?
需要手动删除小数点之后才能正常输入小数点之后的数字

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.2 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31084#issuecomment-866061796
