### ISSUE TITLE
TOOLTIP FOR MULTIPLE SELECT (MODE MULTIPLE)

### ISSUE THREAD

**Issue by VINCENGUYEN-JS** [ant-design/ant-design#31376]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
- [ ] Code sample : https://codesandbox.io/s/m8lyq

### What problem does this feature solve?
Allows see more details in tooltip ( if options words is too long )

### What does the proposed API look like?
I suppose it would support out of the box but it doesn't :)

**Comment by afc163** [comment]
Check https://ant.design/components/select-cn/#components-select-demo-custom-tag-render for custom tag.
