### ISSUE TITLE
Transfer component when change language, then drop menu not change with zh_HK, but en_US and zh_CN are ok

### ISSUE THREAD

**Issue by lin0123** [ant-design/ant-design#31394]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ri4m7?file=/index.js)

### Steps to reproduce
when use zh_HK, drop menu language is en_US, use en_US and zh_CN are ok

### What is expected?
when use zh_HK, drop menu item show zh_HK

### What is actually happening?
use zh_HK, drop menu item show en_US

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.1 |
| System | mac pro and window |
| Browser | Chrome/91.0.4472.124 |

---
chinese:  穿梭框，使用繁体字的时候其他的都是繁体字，但是箭头处的下拉菜单的全选和反选是英文了，没有变成对应的繁体，还是英文，不过配置成中文或者英文显示是对的，并且这个下拉菜单貌似不支持自定义。详见链接demo

**Comment by lin0123** [comment]
![image](https://user-images.githubusercontent.com/25197900/125476369-6c052dd3-1307-471a-b651-221dbf83bdc3.png)

**the position view up picture please**

**Comment by yoyo837** [comment]
Fixed in #31404
