### ISSUE TITLE
Segmented Control

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#31399]
<img width="589" alt="图片" src="https://user-images.githubusercontent.com/507615/125560345-ef451e9c-e4e0-4241-8e04-9c50607c43b3.png">

<img width="170" alt="图片" src="https://user-images.githubusercontent.com/507615/125560381-ac082471-158d-41f8-b9f5-ccb43defa2e2.png">

<img width="511" alt="图片" src="https://user-images.githubusercontent.com/507615/125560457-338ffd37-1e4a-4ab2-a09e-f786b43b7cb9.png">

<img width="375" alt="图片" src="https://user-images.githubusercontent.com/507615/125560593-095d1189-d4e9-4faf-aa06-4ef18bd5fa22.png">

**Comment by zombieJ** [comment]
更贴近 Tabs 还是 Radio？

**Comment by afc163** [comment]
Tabs，这个样式几乎没见过作为表单控件，一般都是区域切换用。

```jsx
<Tabs type="segmented" />
```

**Comment by hengkx** [comment]
觉得 `<Segmented />` 好点

**Comment by wendellhu95** [comment]
`<Segmented />`

**Comment by DreamPWJ** [comment]
希望文字前可以添加图标  如
![image](https://user-images.githubusercontent.com/16730031/144783790-ad415f61-ca7e-499e-9df4-cd84e839a832.png)

**Comment by DreamPWJ** [comment]
Segmented  独立出来更好

**Comment by daud9** [comment]
Implicate buttonstyle
