### ISSUE TITLE
menu 视觉优化

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#314]
根据项目中的使用情况进行视觉优化，主要有去除默认边框，改进动画，增加用例场景为主。

视觉稿：待制作。

原来：http://ant.design/components/menu

**Comment by qiuyuntao** [comment]
什么时候会出视觉稿

**Comment by afc163** [comment]
别着急，我问问设计师。

**Comment by afc163** [comment]
项目中的实例：

![](https://t.alipayobjects.com/images/rmsweb/T1nH8iXiFfXXXXXXXX.png)

![](https://t.alipayobjects.com/images/rmsweb/T1CINiXeJXXXXXXXXX.png)

**Comment by afc163** [comment]
## 修改点如下：

1. http://ant.design/components/menu/ 纵向导航，去掉上下左边框，增加竖向的蓝色高亮条和右边框。
2. 增加暗色主题 `theme="dark"` 样式，方便开发者直接取用。
3. 在 http://ant.design/components/layout 下开设常用导航布局演示，利用 menu 和 layout 组件把视觉稿上的例子都实现为 demo。

**Comment by afc163** [comment]
@qiuyuntao 先搞前两个，我去挖第三个的坑。

**Comment by afc163** [comment]
常用布局的坑在此：https://github.com/ant-design/ant-design/tree/common-layout/spec/layout

**Comment by afc163** [comment]
基本的三种布局已搞好，@qiuyuntao 把 menu 加进去。

**Comment by afc163** [comment]
- http://ant.design/components/menu/
- http://ant.design/spec/layout/

完成。
