### ISSUE TITLE
Tabs组件自定义tab内容，当tab为输入框时，输入空格、回车时无效

### ISSUE THREAD

**Issue by fly-sheep** [ant-design/ant-design#31403]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4167-forked-5sth0?file=/index.js:251-289)

### Steps to reproduce
直接上述demo有体现

### What is expected?
Input输入框输入空格和回车能输出正确结果

### What is actually happening?
输入回车空格时事件被阻止

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.14.0 |
| System | 无 |
| Browser | chrome 版本 91.0.4472.114（正式版本） (arm64) |

**Comment by fly-sheep** [comment]
![image](https://user-images.githubusercontent.com/30622989/125590391-9a350236-bba1-4927-ae63-604844d12c66.png)

我看了下rc-tab源码，这里确实拦截了这两个键盘事件，不知道为什么要这样设计？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15610#issuecomment-475951448

See https://codesandbox.io/s/jiben-antd4167-forked-291qv
