### ISSUE TITLE
Suggesting use SCSS instead of LESS

### ISSUE THREAD

**Issue by KyleBing** [ant-design/ant-design#31409]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Serve larger project scale

### What does the proposed API look like?
Less is very similar to SCSS, so it is doable.

**Comment by PeachScript** [comment]
Duplicate of #18611

**Comment by LinboLen** [comment]
related #38406
