### ISSUE TITLE
menu 默认展开第一个submenu

### ISSUE THREAD

**Issue by aliencyl7** [ant-design/ant-design#3140]
**问题描述**

menu 设置openkeys 之后，想默认总是打开第一个submenu，但无法toggle submenu

**发生环境**

- antd 版本：0.12
- 操作系统及版本： mac
- 浏览器及版本：chrome
- 在线演示地址：

**重现步骤**

使用menu组件，设置openKeys 属性，就没法toggle submenu

**Comment by benjycui** [comment]
`defaultOpenKeys` 

请自行学习受控组件概念。
