### ISSUE TITLE
Form.List, add(initValue,insertIndex)  有问题

### ISSUE THREAD

**Issue by daring123** [ant-design/ant-design#31401]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dongtaizengjianqiantaoziduan-antd4167-forked-qc007?file=/index.js)

### Steps to reproduce
用 add(initValue,insertIndex)  方法新增一列，感觉会导致剩下的组件，先卸载再渲染。
在我给的代码中，比如我第一列选择单位是 "usa"。当我使用 add({firstName:'', lastName:''},0) 增加一列时，第一列的单位会重置到“china”，也就是我的处始态，但是使用 add()方法就没有。

### What is expected?
如上

### What is actually happening?
如上

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 最新版本 |
| System | mac |
| Browser | chrome 90.0.4430.212 |

**Comment by zombieJ** [comment]
第二个 FormItem 漏了 `{...restField}`
