### ISSUE TITLE
希望能给InputNumber增加一个属性：controls

### ISSUE THREAD

**Issue by ace0109** [ant-design/ant-design#31411]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
类似element-ui的InputNumber，拥有一个controls属性，表示控制按钮的显示和隐藏。
因为大部分场景下，输入数字的输入框应该都不需要这个控制按钮，并且很占位置。

### What does the proposed API look like?
<InputNumber controls: false />

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19168

隐藏掉按钮后，是不是就和 Input 没什么区别了？

**Comment by ace0109** [comment]
> #19168
> 
> 隐藏掉按钮后，是不是就和 Input 没什么区别了？

不是吧。InputNumber只能输入数字啊。

**Comment by afc163** [comment]
@ace0109 来个 PR
