### ISSUE TITLE
[Tabs] tabs 内存泄漏

### ISSUE THREAD

**Issue by HSunboy** [ant-design/ant-design#31416]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mgu17?file=/index.js)

### Steps to reproduce
1. 关闭tab1。tab2
2. 查看内存快照
3. tab2 dom 未销毁
![image](https://user-images.githubusercontent.com/14886044/125790192-59102366-9c38-46b7-a6fb-26804d961a0e.png)

### What is expected?
tab2 dom 销毁

### What is actually happening?
tab2 dom 未销毁

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.14.0 |
| System | macos 10.15.5 |
| Browser |  91.0.4472.114（正式版本） (x86_64) |

**Comment by HSunboy** [comment]
更新：
链接：https://codesandbox.io/s/xinzengheguanbiyeqian-antd4167-forked-cjbcr?file=/index.js

这个例子比较直观，创建了一堆 CustomData 实例，关闭 tab 后，customdata 还在内存中

![image](https://user-images.githubusercontent.com/14886044/125886735-791dbacc-b3fb-4c48-8f85-adb6053c904f.png)

**Comment by zombieJ** [comment]
Chrome 的 BUG，点击过的 DOM 元素被缓存了。不要点击等 5 秒让它自己消失再看一下：https://codesandbox.io/s/xinzengheguanbiyeqian-antd4167-forked-y7ohw?file=/index.js:278-288

ref：https://bugs.chromium.org/p/chromium/issues/detail?id=1177010
