### ISSUE TITLE
Tooltip component doesn't work as expected when children button has a disabled attribute

### ISSUE THREAD

**Issue by YagamiNewLight** [ant-design/ant-design#31412]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-mgs5mj](https://stackblitz.com/edit/react-mgs5mj)

### Steps to reproduce
hover on the button

### What is expected?
The tooltips text should show

### What is actually happening?
No tooltips show

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.0 |
| System | Win10 |
| Browser | Chrome  91.0.4472.77 |

---
Remove the disabled attribute of the button, the tooltip will work as expected.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9581#issuecomment-374113785

**Comment by feyzullahyildiz** [comment]
I recognized some interesting thing. Tooltip sends extra props to child components. In most case we pass these props to Button component with spread operator. But the props has onClick, onMouseEnter functions in it. It might override your own props if you pass your own onClick function before the spreated props.
```jsx
// it was like this and onClick was not working if this button is inside Tooltip
<Button onClick={handleButtonClick} {...buttonProps}>
    {children}
</Button>

```

```jsx
// Now the onClick is working in Tooltip even it pass onClick function in it.
<Button {...buttonProps} onClick={handleButtonClick}>
    {children}
</Button>
```
