### ISSUE TITLE
Hidden component

### ISSUE THREAD

**Issue by nasreddineskandrani** [ant-design/ant-design#31419]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We want to be able to not render a component in react by wrapping it with a `Hidden` component that handle responsive breakpoints props.

### What does the proposed API look like?
Same as: https://material-ui.com/components/hidden/

**Comment by afc163** [comment]
You can try `<Col span={{ sm: 0 }} />`.

https://ant.design/components/grid/

**Comment by nasreddineskandrani** [comment]
Thank you for the quick answer.

The `Hidden` component do not `display: none` but it does not render at all the children. So `<Col span={{ sm: 0 }} /` does not do the wanted behavior by this feature request.
