### ISSUE TITLE
Switch initialValue 值无法初始化初始值

### ISSUE THREAD

**Issue by Superman-wc** [ant-design/ant-design#3142]
#### 发生问题的环境是：

- antd 版本:1.8.0
- 操作系统及其版本:macOS
- 浏览器及其版本:Chrome 版本 52.0.2743.116 (64-bit)

#### 您做了什么？

<Switch checkedChildren="是" unCheckedChildren="关"
                                        {...getFieldProps('status', {
                                            initialValue: !!item.status //// 初始值没法设置
                                        })}
                                        disabled={!isEdit}
                                   // 初始值没法要用
                                    defaultChecked={!!item.status}
                                />

**Comment by benjycui** [comment]
http://ant.design/components/form/#getFieldProps-options

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by afc163** [comment]
这类问题统一关联一下：https://github.com/ant-design/ant-design/issues/1353

**Comment by wuyunjiang** [comment]
加上第二行内容
```js
{getFieldDecorator('state',{
  valuePropName: 'checked',
  initialValue:!!item.status
})(
  <Switch
    checkedChildren={<Icon type="check" />} 
    unCheckedChildren={<Icon type="cross" />} />
)}
```
