### ISSUE TITLE
Customize the style of the selected Option, it will not take effect immediately

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design#31428]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daisousuokuang-antd4167-forked-j6bbk?file=/index.js)

### Steps to reproduce
Randomly select a pending option

### What is expected?
Custom selected styles can take effect immediately

### What is actually happening?
The custom selected style will take effect the next time the drop-down box is opened

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.2 |
| System | MacOs |
| Browser |  chrome 91.0 |

---
custom selected option in single mode

### video

https://user-images.githubusercontent.com/36301924/125904505-1bdae479-8b36-4351-a134-4db29840defb.mp4

**Comment by afc163** [comment]
Try this https://codesandbox.io/s/daisousuokuang-antd4167-forked-vs0j1?file=/index.js

**Comment by XiaoJiuDYS** [comment]
Thanks
