### ISSUE TITLE
已经设定pageSize的情况pagination可以修改每页条数

### ISSUE THREAD

**Issue by didihaha** [ant-design/ant-design#31424]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design](https://github.com/ant-design)

### Steps to reproduce
table数据给500条，每页10条数据

### What is expected?
期望每页正常10条数据

### What is actually happening?
每页确实是10条，但是每页条数可以修改，实际我已经表明了就10条，怎么可以修改呢

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.2 |
| System | mac  |
| Browser | chrome 91.0.4472.114 |

---
我内部管理平台你要我给你链接吗？给你你能看吗？如果我是机密项目，给你你敢看吗

**Comment by yoyo837** [comment]
没太理解是什么问题，不用一模一样提供项目代码，提供可复现问题的那部分就可以了，请从 https://u.ant.design/codesandbox-repro 修改一个复现。
