### ISSUE TITLE
TreeSelect maxTagCount Props set ‘responsive’，style width set small，treeselect always focus

### ISSUE THREAD

**Issue by Dunn-liu** [ant-design/ant-design#31423]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kegouxuan-antd4167-forked-xq6xe?file=/index.js:1071-1081)

### Steps to reproduce
TreeSelect maxTagCount Props set ‘responsive’，style width set small，treeselect always focus

### What is expected?
Click elsewhere to cancel getting focus

### What is actually happening?
Always get the focus state

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
How to reproduce it?
