### ISSUE TITLE
antd table 表头有时自动设置成  visibility: hidden （非人为修改，详情看截图）

### ISSUE THREAD

**Issue by chenjiajing23** [ant-design/ant-design#31427]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/e8slx?file=/index.js)
<img width="1023" alt="截屏2021-07-16 11 57 55" src="https://user-images.githubusercontent.com/41351722/125903503-03117d3c-9c7f-40de-933a-5a76593fddc5.png">

### Steps to reproduce
在浏览器每隔2s刷新一次，会有几率表格表头被隐藏

### What is expected?
表格表头在任何都不改被隐藏

### What is actually happening?
在浏览器每隔2s刷新一次，会有几率表格表头被隐藏（火狐，谷歌浏览器都会出现）

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 17.0.1 |
| System | mac os |
| Browser | chrome / 91.0.4472.114  |

**Comment by sunshine541** [comment]
我也遇到了同样的问题，最后怎么解决的

**Comment by clydee-geng** [comment]
插个眼等待解决

**Comment by 18561752746** [comment]
插眼,待解决

**Comment by gdl1412** [comment]
待解决眼

**Comment by gdl1412** [comment]
为什么会出现这个问题?
![image](https://github.com/ant-design/ant-design/assets/72334817/16f22f7c-c724-482f-a19b-96ba43262aa9)

**Comment by erTongWang** [comment]
我也遇到这个问题了 
我的情况是 columns 里面的 key 是一个数组 : string[] 里面有2项(接受的之前别人的代码)
把key改成唯一的字符串之后这个问题结局

还有另外一种情况 之前没有排查到key这里来 我在table上新增了 virtual 虚拟滚动 也可以解决表头自动设置visibility: hidden，但是当table中的数据为空时，表头会显示不完整 只会显示出当前显示的内容，也不支持x轴横向滚动。

ps: 在排查问题的时候我在控制台把visibility: hidden去掉表头确实出来了 但是样式是乱的。 我猜测可能是组件为了防止样式乱的这种情况自动隐藏掉了

以上是针对我当前情况的一个解决方案 希望能够帮助到各位

**Comment by gdl1412** [comment]
我的问题大同小异叭，解答有问题的话请指出

这里从源码看
rc-table库 这里初始是undefined

<img width="881" height="803" alt="Image" src="https://github.com/user-attachments/assets/06254d76-ea26-42f0-90fd-73f779d56fa5" />

而FixedHolder这里visibility有两个变量的判断

<img width="1034" height="321" alt="Image" src="https://github.com/user-attachments/assets/2e6e831a-445d-4b5d-b677-28aae46d667b" />

<img width="1169" height="573" alt="Image" src="https://github.com/user-attachments/assets/53f26c71-2270-4e6a-8977-26f4e1fe0f73" />

修改的不多而且我这里使用的版本固定，我就通过patch-package 打了个patch解决的，不知道对大家的问题有没有帮助
<img width="653" height="595" alt="Image" src="https://github.com/user-attachments/assets/4eb46fe3-bb3f-453e-9bb7-eb55d4d38600" />
这里100改成 0，要不然右侧固定有问题
