### ISSUE TITLE
antd源码无法调试

### ISSUE THREAD

**Issue by twisger** [ant-design/ant-design#3143]
#### 发生问题的环境是：

- antd 版本: 1.11.0
- 操作系统及其版本: win7
- 浏览器及其版本: chrome 50

#### 您做了什么？

下载1.11.0的源码并安装依赖，起初安装时会报错，和这个问题一样，https://github.com/cnpm/npminstall/issues/121
更新了cnpm 不会报错，但npm run start仍然失败，npm run dist 会出现和上面的issue一样的错误。
#### 您期待的结果是：

能够正常编译部署

#### 实际上的结果是：

报错

#### 可重现的在线演示

无

**Comment by benjycui** [comment]
还是先用回老版本的 cnpm 吧。

**Comment by fengmk2** [comment]
我使用 cnpm -v 的版本是

```bash
cnpm@4.5.0 (/Users/mk2/npm-global/lib/node_modules/cnpm/parse_argv.js)
npm@3.10.10 (/Users/mk2/npm-global/lib/node_modules/cnpm/node_modules/.3.10.10@npm/lib/npm.js)
node@6.9.5 (/Users/mk2/git/github.com/jasongin/nvs/node/6.9.5/x64/bin/node)
npminstall@2.24.0 (/Users/mk2/npm-global/lib/node_modules/cnpm/node_modules/.2.24.0@npminstall/lib/index.js)
prefix=/Users/mk2/npm-global 
darwin x64 16.3.0 
registry=https://registry.npm.taobao.org
```

最新的 master 分支，运行 `cnpm i && npm run start` 是正常的啊。。。

![image](https://cloud.githubusercontent.com/assets/156269/22915522/f5336d5e-f2b2-11e6-8c69-d805a5a6b315.png)

![image](https://cloud.githubusercontent.com/assets/156269/22915525/f9613726-f2b2-11e6-9902-1909cbcbf1eb.png)

@twisger @benjycui 请排查清楚再将锅推给 cnpm 。。。
