### ISSUE TITLE
Dropdown contextmenu don't work on any React component children

### ISSUE THREAD

**Issue by alienzhangyw** [ant-design/ant-design#31435]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youjiancaidan-antd4167-forked-vxqr2?file=/index.js)

### Steps to reproduce
Use Dropdowm with trigger={['contextMenu']} and contextMenu overlay，wrap any react component directly.

### What is expected?
Context menu shows when right-click the child component.

### What is actually happening?
Context menu don't show.

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.14.0 |
| System | Windows 10 2004 |
| Browser | Edge 91 |

---
It works when wrapping child component with a div.

**Comment by afc163** [comment]
https://codesandbox.io/s/youjiancaidan-antd4167-forked-33jpp?file=/index.js
