### ISSUE TITLE
InputNumber 动态设置 formatter 不生效

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#31431]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-antd-input?file=index.js](https://stackblitz.com/edit/react-antd-input?file=index.js)

### Steps to reproduce
https://stackblitz.com/edit/react-antd-input?file=index.js

### What is expected?
动态设置 formatter 生效

### What is actually happening?
动态设置不生效

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by g7i** [comment]
I'm working on this issue.

**Comment by kanweiwei** [comment]
https://github.com/react-component/input-number/blob/1ac9b7e17c8af53bcdf732930c4e16d6fad8c0d4/src/InputNumber.tsx#L458-L463
```
 // Input by precision & formatter
    useUpdateEffect(() => {
      if (!decimalValue.isInvalidate()) {
        setInputValue(decimalValue, false);
      }
    }, [precision, formatter]);
```

**Comment by g7i** [comment]
> https://github.com/react-component/input-number/blob/1ac9b7e17c8af53bcdf732930c4e16d6fad8c0d4/src/InputNumber.tsx#L458-L463
> 
> ```
>  // Input by precision & formatter
>     useUpdateEffect(() => {
>       if (!decimalValue.isInvalidate()) {
>         setInputValue(decimalValue, false);
>       }
>     }, [precision, formatter]);
> ```

Thanks a lot @kanweiwei for helping me out

**Comment by IgorStetsiuk** [comment]
@Dolov @kanweiwei @g7i  Hello guys! 

Can you help me out, please? I have face the same issue as described here. And I see that there is a PR open to fix this one. 
What can we do to get it merged?

**Comment by shinenic** [comment]
@IgorStetsiuk you can just pass the dependencies state/prop into `NumberInput` as `key`

https://stackblitz.com/edit/react-antd-input?file=index.js
for example:
```diff
    <InputNumber
        style={{ width: 300 }}
        defaultValue={1000}
        formatter={value =>
          `${pvalue} ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')
        }
        parser={value => value.replace(/\$\s?|(,*)/g, '')}
        onChange={onChange}
+      key={pvalue}
      />
```
