### ISSUE TITLE
table 组件支持纯前端排序

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#31444]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
本页数据支持排序且不触发后端查询，切换分页和排序等都会触发 onChange 方法

### What does the proposed API look like?
onlyClientSorter: Boolean

**Comment by afc163** [comment]
默认就是纯前端排序，onChange 内不要带着排序参数去请求后端就行。

**Comment by fengyun2** [comment]
> 默认就是纯前端排序，onChange 内不要带着排序参数去请求后端就行。

@afc163 切换分页也是触发了 onChange 事件，只要点击了一次排序箭头，参数与主动触发排序的参数完全一致

**Comment by fengyun2** [comment]
> 默认就是纯前端排序，onChange 内不要带着排序参数去请求后端就行。

@afc163 @zombieJ 期望是前端自行实现排序，不能触发后端请求接口，由于业务原因，后端接口查询速度很慢（涉及性能问题），体验很差
