### ISSUE TITLE
Dropdown 下的 Menu 项被选择时  onSelect 事件不被触发

### ISSUE THREAD

**Issue by nuancheng** [ant-design/ant-design#31441]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-antd4167-forked-gpf9y?file=/index.js)

### Steps to reproduce
直接点击可选项

### What is expected?
onSelect被触发，console被打印

### What is actually happening?
onSelect没有被触发，console没有被打印

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.1 |
| System | macOS 10.15.7 (19H2) |
| Browser | chrome  版本 86.0.4240.111（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11743#issuecomment-464428730

You can make Menu selectable by adding prop.

https://codesandbox.io/s/jiben-antd4167-forked-p34lb?file=/index.js
