### ISSUE TITLE
a标签赋予了disabled属性还是能执行点击事件

### ISSUE THREAD

**Issue by MrsYangyang** [ant-design/ant-design#31445]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rok51?file=/index.js:0-309)

### Steps to reproduce
在a标签上写了 disabled={true},但是a标签依然能被点击

### What is expected?
在a标签上写了 disabled={true},不能继续执行点击事件

### What is actually happening?
在a标签上写了 disabled={true}

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Google Chrome  91.0.4472.77 |

**Comment by afc163** [comment]
这和 antd 无关。

**Comment by MrsYangyang** [comment]
a[disabled] {
    color: #777;
    cursor: not-allowed;
    pointer-events: none;
}
