### ISSUE TITLE
add `ref` to <Image />

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design#31442]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js)

### Steps to reproduce
use react `useRef` hook, and pass it to the `<Image />` Component.

### What is expected?
The ref to contain a reference to the underling `<img />`

### What is actually happening?
The ref is being used for something else in `rc-image`.
#### From [`rc-image`](https://github.com/react-component/image/blob/8bddb472d0818725ccb9038842bfaa6bb96736f4/src/Image.tsx#L161)
```
<img
    {...imgCommonProps}
     ref={getImgRef}
     ... 
/>
``` 
#### `getImgRef` :
```
const getImgRef = (img?: HTMLImageElement) => {
    isLoaded.current = false;
    if (status !== 'loading') return;
    if (img?.complete && (img.naturalWidth || img.naturalHeight)) {
      isLoaded.current = true;
      onLoad();
    }
  };
```

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.14.0 |
| System | MacOS Big sur |
| Browser | Chrome 91.0 |

**Comment by jljsj33** [comment]
这需求点还是有的，，，重构成 func component 用 forwardRef，，不能摸杀这功能。。。

**Comment by QiuMing** [comment]
请教下，在<Image>支持 ref 之前，有什么办法自行获取到 ref  了

**Comment by afc163** [comment]
trace #36117
