### ISSUE TITLE
DatePicker  无法阻止冒泡事件

### ISSUE THREAD

**Issue by marlti7** [ant-design/ant-design#31457]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#header](https://ant.design/components/date-picker-cn/#header)

### Steps to reproduce
DatePicker  无法阻止冒泡事件   无e 无e.stopPropagation()

### What is expected?
DatePicker  可以阻止冒泡事件

### What is actually happening?
https://ant.design/components/date-picker-cn/#header

| Environment | Info |
|---|---|
| antd | undefined |
| React | 最新 |
| System | 最新 |
| Browser | chrome |

**Comment by afc163** [comment]
外面包一个 span 或 div 再阻止传播w。

**Comment by pear794** [comment]
> 外面包一个 span 或 div 再阻止传播。

十分感谢，有用
