### ISSUE TITLE
Form.getFieldsValue() doesn't return all form data

### ISSUE THREAD

**Issue by nrayburn-tech** [ant-design/ant-design#31450]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ufcht?file=/index.js)

### Steps to reproduce
1. Open Sandbox.
2. Open Console.
3. Click `Log Form Values`.
4. See that `form.getFieldsValue()` only logs the data for currently rendered fields.
5. Click `Toggle Render`.
6. Click `Log Form Values`.
7. See that `form.getFieldsValue()` logs nested object data.
8. Click `Toggle Render`.
9. Click `Log Form Values`.
10. See that `form.getFieldsValue()` again does not log nested object data.

### What is expected?
Calling `form.getFieldsValue()` should return all form data, not just currently rendered `Form.Item` components data.

### What is actually happening?
Only currently rendered `Form.Item` components are returned.

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17.0.2 |
| System | macOS |
| Browser | Brave (Chromium 91) |

---
`form.getFieldValue('user')` and `form.getFieldValue('password')` do show the correct data at all times, so it is available to the form.  It just isn't returned unless the `Form.Item` component is currently being rendered.

The `Form.getFieldsValue()` issue also happens with `Form.validateFields()`, where only currently rendered `Form.Item` data is returned.

**Comment by nrayburn-tech** [comment]
Found the note in the docs to pass in `true` for `form.getFieldsValue`, but this doesn't work for `form.validateFields`.  It throws an error.

**Comment by afc163** [comment]
Check https://ant.design/components/form/#FormInstance

<img width="1218" alt="图片" src="https://user-images.githubusercontent.com/507615/126255792-69ca0f05-7856-4fce-bf18-d4b23fce8f8f.png">
