### ISSUE TITLE
表单组件的边框如何改成直角

### ISSUE THREAD

**Issue by shitianjie** [ant-design/ant-design#3145]
#### 发生问题的环境是：

- antd 版本:1.11.1
- 操作系统及其版本:windows10
- 浏览器及其版本:Chrome 52.0.2743.116 (64-bit)

#### 您做了什么？
引用了antd的<input/>和<form/>组件

#### 您期待的结果是：
边框为直角而不是圆角

#### 实际上的结果是：
边框无法修改成直角

**Comment by afc163** [comment]
自行覆盖样式或变量。
