### ISSUE TITLE
qiankun 框架下使用 antd4 select 组件点击后卡死

### ISSUE THREAD

**Issue by bhan614** [ant-design/ant-design#31455]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/umijs/qiankun](https://github.com/umijs/qiankun)

### Steps to reproduce
1. 把 qiankun 官方 example 中 react 16子项目的 antd 版本改成4，然后npm run examples:install && examples:start
2. 在 react 16子项目中加入 select 组件，点击 select 组件后页面崩溃

### What is expected?
页面不崩溃

### What is actually happening?
点击select组件后页面崩溃

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
建议提到 qiankun 的 issues 去。

**Comment by bhan614** [comment]
qiankun 让我找 antd，我试过antd 4.3.1 版本就是好的，所以还是后边antd升级出的问题。

**Comment by bhan614** [comment]
> 建议提到 qiankun 的 issues 去。

qiankun 让我找 antd，我试过antd 4.3.1 版本就是好的，所以还是后边antd升级出的问题。

**Comment by afc163** [comment]
可以帮忙看看具体是哪个改动出现的问题，或者提供重现。

**Comment by afc163** [comment]
<img width="452" alt="图片" src="https://user-images.githubusercontent.com/507615/130731664-b3bd1141-4f46-4b2b-a46e-d1368ac4d71b.png">

实测没发现问题。

**Comment by bhan614** [comment]
> <img alt="图片" width="452" src="https://user-images.githubusercontent.com/507615/130731664-b3bd1141-4f46-4b2b-a46e-d1368ac4d71b.png">
> 
> 实测没发现问题。

好奇怪。。我的就会卡死。问下你是运行的qiankun 最新2.4.9的demo么？

**Comment by wmlzjb** [comment]
我也出现了同样的问题，用4.6.4和以前版本的select都没问题，但是4.6.5和以后的版本就会卡死

**Comment by wmlzjb** [comment]
> <img alt="图片" width="452" src="https://user-images.githubusercontent.com/507615/130731664-b3bd1141-4f46-4b2b-a46e-d1368ac4d71b.png">
> 
> 实测没发现问题。

我也出现了同样的问题，用4.6.4和以前版本的select都没问题，但是4.6.5和以后的版本就会卡死
