### ISSUE TITLE
Unable to use Anchor to open link in new tab

### ISSUE THREAD

**Issue by nitin-rachabathuni** [ant-design/ant-design#31453]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/anchor/#API](https://ant.design/components/anchor/#API)

### What is expected?
Need _target blank kind of prop

### What is actually happening?
Not able to open link in new tab

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17 |
| System | BigSur |
| Browser | Chrome |

**Comment by chilingling** [comment]
use `target="_blank"` works for me
example: `<Link href="yourtargetsite" title="Link Props" target="_blank" />`

**Comment by nitin-rachabathuni** [comment]
> use `target="_blank"` works for me
> example: `<Link href="yourtargetsite" title="Link Props" target="_blank" />`

ThankYou

**Comment by nitin-rachabathuni** [comment]
> Hello @nitin-rachabathuni. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @nitin-rachabathuni, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

It's not reproducing, my bad. Ty
