### ISSUE TITLE
`div` in Modal interferes in tab-order

### ISSUE THREAD

**Issue by ernesto-reify** [ant-design/ant-design#31468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal/](https://ant.design/components/modal/)

### Steps to reproduce
In Chrome DevTools, create a live expression "document.activeElement".
Navigate to https://ant.design/components/modal/
In the first example "Basic", click on "Open Modal".
Begin tabbing, and you will notice that a div will also take focus at some point. In Chrome DevTools, if you mouse-hover over the result of "document.activeElement", you will see that a zero-sized div element is getting focus, which I think shouldn't.

![image](https://user-images.githubusercontent.com/73124087/126473446-b6726b71-20eb-4dfc-b3a2-0ed09ac0de1f.png)

### What is expected?
The zero-sized div element created by the Modal AntD element should not obtain focus when tabbing.

### What is actually happening?
The zero-sized div element created by the Modal AntD element is getting focus when tabbing.

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17.0.1 |
| System | MacOS Big Sur 11.2.3 |
| Browser | Chrome 91.0.4472.114 |

**Comment by zombieJ** [comment]
It's by design.

When Modal open, it will create sentinel element before & after modal content. Which helps to prevent key tab out of modal.

**Comment by ernesto-reify** [comment]
> It's by design.
> 
> When Modal open, it will create sentinel element before & after modal content. Which helps to prevent key tab out of modal.

Thanks for taken a look. I understand there is no way to prevent this without adding an idle tabbable element.
