### ISSUE TITLE
Form 中使用Switch ,设置valuePropName后，点击label可以控制切换Swtich的状态

### ISSUE THREAD

**Issue by shirleyYing** [ant-design/ant-design#31467]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-validate-other](https://ant.design/components/form-cn/#components-form-demo-validate-other)

### Steps to reproduce
点击label Switch ,开关组件的的值会变化

### What is expected?
不会变化

### What is actually happening?
会变化

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
这是预期行为，label 应该和控件联动。
