### ISSUE TITLE
tree控件 连线不对齐

### ISSUE THREAD

**Issue by ArthurBZhou** [ant-design/ant-design#31471]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/20474](https://github.com/ant-design/ant-design/issues/20474)

### Steps to reproduce
显示器的缩放调到150%

### What is expected?
对齐

### What is actually happening?
不对齐

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | win10 |
| Browser | Electron 11.4.7 |

**Comment by ArthurBZhou** [comment]
![image](https://user-images.githubusercontent.com/4514193/126478144-8f9f2b29-bb54-46e0-a921-9966b9f98df7.png)

**Comment by ArthurBZhou** [comment]
还有一个小问题，能不能只显示竖线，不显示转角和横线？如果用showLine={{showLeafIcon: true}} 那个leaficon有点丑也不知道怎么替换掉
![image](https://user-images.githubusercontent.com/4514193/126478588-8668b0a1-467c-4bcf-b9c1-c741de8cbbfe.png)

**Comment by ArthurBZhou** [comment]
![image](https://user-images.githubusercontent.com/4514193/126479045-b6cf3a3d-ab60-4439-814d-00d87857b8b6.png)
![image](https://user-images.githubusercontent.com/4514193/126479071-9c9a5078-17d0-4a9f-a0b7-3ecbf8232207.png)
应该是展开没对牢，差了0.5像素🧐

**Comment by ArthurBZhou** [comment]
朋友，您好，
 您的意思要我帮着改掉这个BUG？

**Comment by DaoxingHuang** [comment]
> 朋友，您好，
> 您的意思要我帮着改掉这个BUG？
是的

**Comment by ArthurBZhou** [comment]
> > 朋友，您好，
> > 您的意思要我帮着改掉这个BUG？
> > 是的

真是很不好意思的要说声抱歉，做为一个独立开发者，尝试在用Antd打造一个Electron的可视化脚手架应用，个人大部份精力投入在架构文件结构、数据结构及功能，没有太多精力研究组件的具体实现机理，非常感谢阿里的工程师无私伟大的付出，架构出AntD这个非常优秀的组件库。
关于RC-Tree还有这么一个关健的问题，这也导至有关Tree正在改用M家TreeView控件,这个问题别人也有报，https://github.com/ant-design/ant-design/issues/11254， 我这边这个问题的上下文是这样，我自已有一个可层层展开观察的树形树据结构，为了使用AntD的RC-Tree,把这个可层层观察的树形数据又转成了一整块TreeData，然后每改一个叶子如标题，又需要这个流程走一遍，这越写越觉的不可接受。
有看RC-Tree的源码，里面的数据和渲染完全扁平化了，本来想自己重写一个 支持 TreeNode 封装在其他组件中的AntD Tree控件，因无法评估开发时间而做罢。想想Tree组件的开发成本是高的，做为AntD,如果分成两种Tree组件(扁平化和非扁平化）来维护也许是真心没必要。再次至歉和感谢!

**Comment by afc163** [comment]
<img width="466" alt="图片" src="https://user-images.githubusercontent.com/507615/130549885-8bc4944d-65f1-4f0c-a6ca-705d5d64b530.png">

在我这里发现没问题。

**Comment by afc163** [comment]
合并到 #31884 讨论。

**Comment by ArthurBZhou** [comment]
收到，谢谢
