### ISSUE TITLE
Dropdown is not opening after the 10 results

### ISSUE THREAD

**Issue by NishargShah** [ant-design/ant-design#31476]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mutable-sea-34uhy?file=/src/App.js)

### Steps to reproduce
1. Add CSS in styles.css
2. Check the demo

### What is expected?
Dropdown needs to open

### What is actually happening?
Dropdown is not opening

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17 |
| System | Ubuntu 20.04 LTS |
| Browser | Chrome 92 |

---
I want to get the full width of my options, so I added the CSS on the `ant-select-dropdown` and I am finding that issue

**Comment by afc163** [comment]
Try `dropdownMatchSelectWidth={false}`

**Comment by NishargShah** [comment]
I read the docs but I did not found something like that, that is why I posted, I don't know how I missed that one prop, anyways Thank you so much :)
