### ISSUE TITLE
Switch - onChange / onClick event bug

### ISSUE THREAD

**Issue by ericpierlot** [ant-design/ant-design#31478]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ts-ushkcq?file=index.tsx](https://stackblitz.com/edit/react-ts-ushkcq?file=index.tsx)

### Steps to reproduce
Click on the switch component by Mouse, see the logs for title.
Now use your keyboard to focus the Switch, spam enter -> see the logs.

### What is expected?
Both method never fail to show title in the logs.

### What is actually happening?
Clicking the component with the mouse make sometimes Title be empty string.

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | React v17 |
| System | Window |
| Browser | Google chrome |

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-ts-d338dq?file=index.tsx
