### ISSUE TITLE
在antd-pro v5中使用Popover、Tag、Rate时报错

### ISSUE THREAD

**Issue by liyunying** [ant-design/ant-design#31472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wynwc?file=/index.js)

### Steps to reproduce
在antd-pro v5中引入Tag并使用，页面一致处在加载状态，打开控制台发现报错。（所附链接无法复现，需在antd pro v5中）

### What is expected?
能正常使用

### What is actually happening?
报错信息：Uncaught (in promise) Error: Module "./antd/es/rate/style" does not exist in container.
while loading "./antd/es/rate/style" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:750

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17.0.0 |
| System | MacOS |
| Browser | chrome |

**Comment by naas1d513215** [comment]
大哥解决了吗？
