### ISSUE TITLE
Text of buttons doesn't perfectly aligned vertically in center

### ISSUE THREAD

**Issue by EminQasimov** [ant-design/ant-design#31477]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-dkisqq?file=src/App.js](https://stackblitz.com/edit/react-dkisqq?file=src/App.js)

### Steps to reproduce
go to https://stackblitz.com
created app from react template
installed antd

### What is expected?
text of buttons must be vertically centered 

### What is actually happening?
Text of buttons doesn't perfectly aligned vertically in center

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | react |
| System | windows 10  |
| Browser | chrome |

---
some fonts needs margin clipping trick to center pixel perfectly.

**Comment by afc163** [comment]
It works fine in my machine.

<img width="374" alt="图片" src="https://user-images.githubusercontent.com/507615/126636107-e6c4c81f-d396-452b-b3e4-03fdfa4ce4ca.png">

**Comment by afc163** [comment]
Aligne issue works in different way among browsers and OS. Your workaround may not work in every situation.

**Comment by EminQasimov** [comment]
![image](https://user-images.githubusercontent.com/37242869/126643485-3d713e40-1822-4f46-b2db-4330a46afa85.png)
