### ISSUE TITLE
at.alicdn.com CDN 百度域名无法访问

### ISSUE THREAD

**Issue by tedpenk** [ant-design/ant-design#3147]
在请求字体文件 https://at.alicdn.com/t/font_1463992151_360388.woff 的时候报错：
![image](https://cloud.githubusercontent.com/assets/7235487/18777511/14482414-81a2-11e6-8cdf-8839273ba656.png)
请问是因为百度的域名都无法访问吗？除了修改源码有什么解决方法吗？

**Comment by benjycui** [comment]
这个问题之前已经有 issue 并且解决了。

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont
