### ISSUE TITLE
使用antd 组件，打包出来的业务文件体积太大

### ISSUE THREAD

**Issue by jimStyle88** [ant-design/ant-design#31484]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce
antd pro 5 项目。使用antd 的组件。比如input 

### What is expected?
按需打包 ，减少包体积

### What is actually happening?
每个打包文件里，只要用到antd  的组件。都打包了  @ant-design/icons/es  压缩后的体积。也有152.16kb

| Environment | Info |
|---|---|
| antd | 4.15.4 |
| React | 17.0.2 |
| System | window 10 |
| Browser | Google Chrome  91.0.4472.164 |

**Comment by jimStyle88** [comment]
![image](https://user-images.githubusercontent.com/20588608/126596333-02c38b61-2e09-4c13-a212-34a00d9fbb5b.png)
  打包后，文件如图所示

**Comment by yoyo837** [comment]
检查一下tree shaking 是否正常

**Comment by jimStyle88** [comment]
> 检查一下tree shaking 是否正常

大佬，请指点一下，我看了一下其他的issue 提到原因是 我们按需加载的antd 组件，内部没有按需加载icons 导致的 ，但是目前没有解决方案

**Comment by yoyo837** [comment]
上复现，靠脑补不知道你的问题。

**Comment by jimStyle88** [comment]
> 上复现，靠脑补不知道你的问题。

公司项目，不方便提供，提供2张我验证对比的图片，图片区别在于，是否引用了antd  input  的组件。
![image](https://user-images.githubusercontent.com/20588608/126599327-5efbe636-cbee-4073-955f-b56994fd03ba.png)
![image](https://user-images.githubusercontent.com/20588608/126599462-854e9bc2-a38d-4c3e-b124-11e2dcb0dd77.png)

**Comment by yoyo837** [comment]
不用复制粘贴公司项目，你照办写法，能复现即可，组件是死的，公司业务是抽象的。

**Comment by zhangchao828** [comment]
antd4已经将icon单独放另外的包了，按理不会这样，可能是你们项目的配置有误，比如是不是在webpack的cacheGroups中加了啥单独抽离的配置，建议用其他的脚手架创建一个新的工程，再引入antd的组件看看是否还是这样，不是的话就是你们项目配置有问题

**Comment by jimStyle88** [comment]
> 不用复制粘贴公司项目，你照搬写法，能复现即可，组件是死的，公司业务是抽象的。
我用新建的antd pro 5  是基于 umi3.5.x ，无法复现，修改起来工作量有点大，降版本报错较多。尴尬了

**Comment by jimStyle88** [comment]
> cacheGroups

目前我用的是antd pro 5  umi  3.4.3   antd 4.14.0    配置方面  cacheGroups  没有改动过，用的是框架默认的，externals   配置了CDN ，我们2月份用了同一个模板新建项目，都出现同样的问题。大佬指点一下，可能出问题的地方有哪些？

**Comment by yoyo837** [comment]
检查你的webpack配置是否支持tree shaking

**Comment by jimStyle88** [comment]
> 检查你的webpack配置和代码写法是否支持tree shaking

检查过，没问题的

**Comment by yoyo837** [comment]
文字交流帮不了你, 搞不清楚你什么情况.

**Comment by jimStyle88** [comment]
> 文字交流帮不了你, 搞不清楚你什么情况.
![image](https://user-images.githubusercontent.com/20588608/126634051-c7f1b9eb-819d-4c5a-a3a5-6de73993ec7a.png)
大佬，加一个钉钉
