### ISSUE TITLE
antd  table   最新版本  rowClassName  奇偶颜色,  对fixed列不生效

### ISSUE THREAD

**Issue by ywww** [ant-design/ant-design#31483]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
#########################css

.table-row-even {
  background-color: gainsboro;
  /*font-size: 12px;*/
}

.table-row-odd {
  /*font-size: 12px;*/
}

########################js

import React from "react";
import ReactDOM from "react-dom";
import { Button, DatePicker, version } from "antd";
import "antd/dist/antd.css";
import "./index.css";

import { Table } from 'antd';

const columns = [
  {
    title: 'Full Name',
    width: 100,
    dataIndex: 'name',
    key: 'name',
    fixed: 'left',
  },
  {
    title: 'Age',
    width: 100,
    dataIndex: 'age',
    key: 'age',
    fixed: 'left',
  },
  {
    title: 'Column 1',
    dataIndex: 'address',
    key: '1',
    width: 150,
  },
  {
    title: 'Column 2',
    dataIndex: 'address',
    key: '2',
    width: 150,
  },
  {
    title: 'Column 3',
    dataIndex: 'address',
    key: '3',
    width: 150,
  },
  {
    title: 'Column 4',
    dataIndex: 'address',
    key: '4',
    width: 150,
  },
  {
    title: 'Column 5',
    dataIndex: 'address',
    key: '5',
    width: 150,
  },
  {
    title: 'Column 6',
    dataIndex: 'address',
    key: '6',
    width: 150,
  },
  {
    title: 'Column 7',
    dataIndex: 'address',
    key: '7',
    width: 150,
  },
  { title: 'Column 8', dataIndex: 'address', key: '8' },
  {
    title: 'Action',
    key: 'operation',
    fixed: 'right',
    width: 100,
    render: () => <a>action</a>,
  },
];

const data = [];
for (let i = 0; i < 100; i  ) {
  data.push({
    key: i,
    name: `Edrward ${i}`,
    age: 32,
    address: `London Park no. ${i}`,
  });
}

function onRowClassName(record, index) {
  return index % 2 === 0 ? 'table-row-odd' : 'table-row-even';
};

ReactDOM.render(
  <Table columns={columns} 
  dataSource={data}
  rowClassName={onRowClassName}
  scroll={{ x: 1500, y: 300 }} />,
  document.getElementById("root")
);

### What is expected?
fixed 列 也实现奇偶不同颜色

### What is actually happening?
fixed 列 没有实现奇偶不同颜色

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17.0.1 |
| System | win10 |
| Browser | chrome 91.0.4472.124 |

**Comment by ywww** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-e0uff

**Comment by ywww** [comment]
> Hello @ywww. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @ywww, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-forked-e0uff

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/antd-reproduction-template-forked-5z1ex?file=/index.css

**Comment by ywww** [comment]
.table-row-even td {
  background-color: gainsboro;
  /*font-size: 12px;*/
}

.table-row-odd td {
  /*font-size: 12px;*/
}

谢谢, 可以
