### ISSUE TITLE
The suggestion about adding a new function

### ISSUE THREAD

**Issue by Kouweijia** [ant-design/ant-design#31487]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the user want to use a new API in his/her code, then go to the API area to find the one , but there only the description ,name, type and version ,and that may not friendly enough for the fresh people cuz they may not clear about the description and its not easy to find the example in so many examples, so if there is a function in the api area which is a button  to each api , users just click it then switch it to the corresponding api example , that may friendly to users.

### What does the proposed API look like?
not clear.

**Comment by afc163** [comment]
It is a huge project, welcome to give us PR.
