### ISSUE TITLE
Can't undo changes in a TextArea with autoSize on Firefox

### ISSUE THREAD

**Issue by felipelpmelo** [ant-design/ant-design#31480]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ht7re)

### Steps to reproduce
On Firefox, type something and try to undo using the context menu option or using Ctrl Z

### What is expected?
Undo the changes

### What is actually happening?
The "Undo" option in the context menu is always disabled, and the Ctrl Z shortcut does nothing

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17.0.2 |
| System | Linux, Windows, MacOS |
| Browser | Firefox 90.0.1 |

**Comment by g7i** [comment]
@afc163 I would like to work on this issue.

**Comment by afc163** [comment]
<img width="534" alt="图片" src="https://user-images.githubusercontent.com/507615/167291938-b2b9410e-a3ae-446e-9330-55bd9263b341.png">

**Comment by felipelpmelo** [comment]
Hi, I can no longer reproduce it. Most likely, the issue has been resolved somehow during the time period since I reported it. I'm closing this issue. Thanks!
