### ISSUE TITLE
Expandable table issue in Safari 14.1.1 (16611.2.7.1.4)

### ISSUE THREAD

**Issue by slaughterbaby** [ant-design/ant-design#31489]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
1.create a table with expanded columns
2.make sure your browser fullscreen
3.set scale to min (cmd   " - ")

### What is expected?
good looking table

### What is actually happening?
cursed template

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | React 17.0.1 |
| System | Mac OS BigSur 11.4 |
| Browser | Safari 14.1.1 (16611.2.7.1.4) |

---
fix pls

**Comment by afc163** [comment]
What does it looks like? Could you provide a screenshot of it?
