### ISSUE TITLE
Type error reported due to no omit getRawInputElement for select component type

### ISSUE THREAD

**Issue by aoilti** [ant-design/ant-design#31491]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/alibaba/formily/issues/1838](https://github.com/alibaba/formily/issues/1838)

### Steps to reproduce
[Refer to an issue of formily](https://github.com/alibaba/formily/issues/1838)
getRawInputElement type error

### What is expected?
omit getRawInputElement

### What is actually happening?
getRawInputElement type error
![image](https://user-images.githubusercontent.com/19969080/126616027-461946db-9b74-4a73-920f-24fb09b30b92.png)

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 16 |
| System | mac |
| Browser | chrome |

---
The select component of RC component is marked with 'getRawInputElement' and 'getInputElement' as props for internal use, but only 'getInputElement' is omitted in ant design`

**Comment by afc163** [comment]
Looks like it had been fixed in https://github.com/alibaba/formily/pull/1844

**Comment by aoilti** [comment]
> Looks like it had been fixed in [alibaba/formily#1844](https://github.com/alibaba/formily/pull/1844)

No, and it's really a potential bug in select. Referring to the compiled type, you can see that `Partial` is wrapped by `Pick`, and `getRawInputElement` is still stored in the type as a required field, so the bug has not been fixed.
![code](https://user-images.githubusercontent.com/19969080/126734050-95ee9b5d-cfa0-4ea7-a9fe-19b982be4f9f.png)
