### ISSUE TITLE
form表单触发校验错误后，内部组件的样式出现异常

### ISSUE THREAD

**Issue by situ-wang** [ant-design/ant-design#31493]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lt0nm)

### Steps to reproduce
1. 点击submit
2. 鼠标focus到password的input框上，此时input框的内部出现红色border

如下操作
![rect](https://user-images.githubusercontent.com/84897913/126616160-0eca9000-1d97-407f-8afb-0b094567c9b5.gif)

### What is expected?
样式正常，input不应该出现border

### What is actually happening?
样式错误，focus input后出现红色border

| Environment | Info |
|---|---|
| antd | undefined |
| React | react 17 |
| System | mac bigSur |
| Browser | chorme 90 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/31456
