### ISSUE TITLE
DatePicker is not adaptive in IE 11

### ISSUE THREAD

**Issue by hollton** [ant-design/ant-design#31503]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-size](https://ant.design/components/date-picker-cn/#components-date-picker-demo-size)

### Steps to reproduce
Create a DatePicker and then reduce the browser width.
![](https://raw.githubusercontent.com/hollton/hollton.github.io/hexo/source/img/antdDatePicker.png)

### What is expected?
The width of the DatePicker follows the browser width.

### What is actually happening?
The width of the DatePicker has not changed.

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 17.0.2 |
| System | window7 |
| Browser | IE11 |

**Comment by afc163** [comment]
Try 

```
<DatePicker style={{ maxWidth: '100%' }} />
```
