### ISSUE TITLE
4.16.8 select 组件 卡死

### ISSUE THREAD

**Issue by DavidYuanX** [ant-design/ant-design#31509]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/DavidYuanX/select_problem_feedback.git](https://github.com/DavidYuanX/select_problem_feedback.git)

### Steps to reproduce
qiankun 安装 ant 4.16.8 引入 select 组件

### What is expected?
正常运行

### What is actually happening?
卡死浏览器

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 16.9 |
| System | mac |
| Browser | Google Chrome Google Chrome is up to date Version 92.0.4515.107 |

---
ant 框架 很棒，希望越来越棒。

**Comment by afc163** [comment]
看上去是 qiankun 相关问题，建议提到 https://github.com/umijs/qiankun/issues
