### ISSUE TITLE
Modal overlay z-index is not high enough

### ISSUE THREAD

**Issue by mellis481** [ant-design/ant-design#31513]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd4168-forked-itw0e?file=/index.js)

### Steps to reproduce
To reproduce in the supplied codesandbox, simply click the drop down.  This will open the list of options as well as open a modal.

### What is expected?
The modal overlay to be above (higher z-index) than the select options.

### What is actually happening?
The modal overlay to be below (lower z-index) than the select options.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | Windows |
| Browser | Chrome |

---
The issue of ant components appearing above the modal overlay also applies to Tooltip, Notification, and likely others.

**Comment by afc163** [comment]
You can customize Modal zIndex prop in this case: https://codesandbox.io/s/basic-usage-antd4168-forked-jp0t6?file=/index.js

**Comment by mellis481** [comment]
@afc163 I understand you can customize it, but the default ant z-indexes should not be bad.  You're essentially saying that all consumers of ant will have to apply z-index changes to not see issues.

**Comment by dgreene1** [comment]
@afc163 our team would take on the work of fixing default z-index values. I'd request that this issue be reopened since the `antd` library is not internally consistent. As @mellis481described, a modal should always appear on top of the select and tooltip.

If you reopen the ticket, our team will do the work.
