### ISSUE TITLE
Table的components属性中无法直接覆盖body，data是只读属性

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design#31510]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-virtual-list](https://ant.design/components/table-cn/#components-table-demo-virtual-list)

### Steps to reproduce
以重现链接中的虚拟列表为例，在使用
                components={{
                    body:renderVirtualList
                }}
时会报错，body的CustomizeScrollBody中的data是只读的，无法修改

<font color=red>备注：使用的是typescript版本，并且官方文档中typescript版本中使用sandbox打开时显示的其实是js文件，所以typescript版本是有问题的！！！</font>

### What is expected?
Table的body可以被修改

### What is actually happening?
Table的body无法被覆盖

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.14.0 |
| System | windows10 |
| Browser | chrome91 |

**Comment by afc163** [comment]
你可以用 https://codesandbox.io/s/ecstatic-tharp-578qr 搞一个 TSX 的重现出来。

**Comment by Youmyin** [comment]
https://codesandbox.io/s/ecstatic-jackson-iw40j?file=/src/components/virtualTable.tsx

**Comment by Youmyin** [comment]
这个是复现链接，不过复现的时候还出现了一个问题，restAfterIndicies报错，但是主要的问题还是body的问题

**Comment by afc163** [comment]
这样是不是就行了？https://codesandbox.io/s/dreamy-perlman-gi51s?file=/src/components/virtualTable.tsx

**Comment by Youmyin** [comment]
感谢感谢！不过我很好奇为什么restAfterIndicies会报错，这是react-window的问题吗？

**Comment by zmhweb** [comment]
@afc163 我发现本地开发还是有这个问题
