### ISSUE TITLE
table组件设置排序的时候，排序按钮无法使用tab和tab shift进行选择

### ISSUE THREAD

**Issue by cYang2030** [ant-design/ant-design#31516]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
进行无障碍开发的时候需要使用tab或者tab shift进行按钮切换，此时无法切换到排序按钮

### What does the proposed API look like?
期望能够使用tab或者tab shift进行切换，或者排序按钮模块可以自定义编码。

**Comment by cYang2030** [comment]
title貌似可以自定义，所以可以自定义title来进行操作，可以实现我的需求。不过我先不关了吧，开发者大佬们评估下需不需要在排序上进行增加Accessibility特性。

**Comment by afc163** [comment]
需要的，Tab 到达是基础需求。
