### ISSUE TITLE
【Cascader】异步加载支持默认值

### ISSUE THREAD

**Issue by snowchenlei** [ant-design/ant-design#31511]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前版本：2.2.2
1、Cascader使用异步加载数据(并默认加载了第一层)。设置defaultValue后只能默认加载第一层，不会触发change事件也无法异步加载默认值，希望可以支持异步数据默认值。
2、支持选项改变时触发事件。change仅在selected或整个值变化是才触发，设置了第一层值并不会触发
change在选项改变时应该触发

### What does the proposed API look like?
https://ng.ant.design/components/cascader/zh#components-cascader-demo-default-value-and-lazyload

**Comment by afc163** [comment]
Maybe you should report it to https://github.com/NG-ZORRO/ng-zorro-antd/issues ?

**Comment by afc163** [comment]
>  1、Cascader使用异步加载数据(并默认加载了第一层)。设置defaultValue后只能默认加载第一层，不会触发change事件也无法异步加载默认值，希望可以支持异步数据默认值。

来个重现看看？

>  2、支持选项改变时触发事件。change仅在selected或整个值变化是才触发，设置了第一层值并不会触发

`changeOnSelect`

**Comment by snowchenlei** [comment]
1、https://stackblitz.com/edit/vue-urjsjw?file=src/App.vue
2、
当前文档未提供通过方法设置选中项的方式。change()在手动点击选项时会触发，通过js方法设置是否会触发，如果不会希望增加js设置也会触发的回调方法。

**Comment by snowchenlei** [comment]
> Maybe you should report it to https://github.com/NG-ZORRO/ng-zorro-antd/issues ?

`What does the proposed API look like?` 这是你们issue模板中的，这个英语你也是能看懂的。但是你这个回答使我晕头转向。
![image](https://user-images.githubusercontent.com/26211283/126922435-7ba453b0-f837-4403-a85b-e4bf11c27dfe.png)
