### ISSUE TITLE
上传控件的上传目录场景增加携带路径信息功能

### ISSUE THREAD

**Issue by LY1806620741** [ant-design/ant-design#31518]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
上传控件目录上传保持目录结构的问题

昨天我朋友找我帮忙看ant design的upload控件上传文件怎么携带路径的问题，她的需求是上传一个目录的文件并携带完整的目录结构信息。
我通过以下操作解决了这个问题，但这只是hook，应该将其沉淀为通用能力，而这个能力在文档里没有体现
```typescript

import { Upload, Button } from 'antd';
import { UploadOutlined } from '@ant-design/icons';

const props = {
  action: './v1/upload',
  directory: true,
  beforeUpload(file) {
    return new Promise(resolve => {
      try{
        Object.defineProperty(file, 'name',  {
          value: file.webkitRelativePath,
          writable: false,
          configurable: true,
          enumerable: true,
        });//修改只读属性
      }catch(e){
        console.log(e);
      }

      resolve(file);
    });
  }
};

export default function IndexPage() {
  return (
    <div>
      <Upload {...props}>
        <Button icon={<UploadOutlined />}>Upload</Button>
      </Upload>
    </div>
  );
}
```

### What does the proposed API look like?
期望有一个开关或者默认上传目录时携带目录结构
```typescript
<Upload directory=true directoryType= "with_path"></Upload>
```
可以看到如下上传可以告诉服务端这个文件在目录结构的哪个位置
![image](https://user-images.githubusercontent.com/25952861/126931543-5f3c7d74-a4f6-420b-a263-ec6a0a3ca58c.png)

**Comment by afc163** [comment]
先描述你遇到的问题，提供重现步骤。

ref https://github.com/ant-design/ant-design/issues/16426

**Comment by LY1806620741** [comment]
> Hello @LY1806620741. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @LY1806620741, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)


我是说可否增加一个功能，这不是bug报告@afc163 

描述问题: 上传目录功能无法携带目录结构信息
重现：我的hook方式解决方案，但我觉得这应该沉淀为组件自有能力

codesandbox链接
https://codesandbox.io/embed/antd-reproduction-template-forked-h8jxk?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
直接读取 file.webkitRelativePath 就行了。
