### ISSUE TITLE
2.0以后Transfer目的列表内容的顺序不受控制

### ISSUE THREAD

**Issue by aarryy** [ant-design/ant-design#3152]
#### 发生问题的环境是：

- antd 版本:2.0.0-beta.11
- 操作系统及其版本: mac os
- 浏览器及其版本: chrome, firefox

#### 您做了什么？

引入 antd Transfer

#### 您期待的结果是：

目的列表内容的顺序由targetKeys决定

#### 实际上的结果是：

目的列表内容的顺序总是由内容在dataSource中的顺序决定的，在附上的在线演示中尽管我手动将targetKeys设置成由content20到content11倒序排列，但是显示的目的列表却还是顺序的，从源列表新移动到目的列表的内容也不是如期待的那样添加在最后， 已确认如果把antd换成V1版本的话显示是正常的

#### 可重现的在线演示

V2：
http://codepen.io/aarryy/pen/LRWxNj?editors=001
V1：
http://codepen.io/aarryy/pen/YGkNWa?editors=001

**Comment by benjycui** [comment]
2.0.0-beta.12
