### ISSUE TITLE
Tabs 自定义新增按钮 新增时 onEdit 事件不触发

### ISSUE THREAD

**Issue by solin2035** [ant-design/ant-design#31527]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://hj2us.csb.app/](https://hj2us.csb.app/)

### Steps to reproduce
https://hj2us.csb.app/

### What is expected?
自定义的新增按钮触发 onEdit事件

### What is actually happening?

默认的新增按钮可以触发onEdit事件，自定义的新增按钮 无法触发onEdit事件

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | window10 |
| Browser | Chrome  90.0.4430.93（正式版本） （64 位） |

**Comment by afc163** [comment]
```
          <Button onClick={this.add}>自定义新增按钮</Button>
```

这个 this.add 完全是由你自定义的，里面自行调用一下你需要的逻辑就行，和 Tabs 看上去关系不大。
