### ISSUE TITLE
BackTop: Module not found: Error: Cannot resolve module 'antd/lib/back-top/style/css'

### ISSUE THREAD

**Issue by asoqa** [ant-design/ant-design#3153]
#### 发生问题的环境是：

- antd 版本: 2.0.0 beta.10
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？
使用了BackTop组件，最简单的用饭，参照官方用例：
```
import { BackTop } from 'antd';

ReactDOM.render(
  <div>
    <BackTop />
    Scroll down to see the bottom right gray button.
  </div>
, mountNode);
```
编译失败：
Module not found: Error: Cannot resolve module 'antd/lib/back-top/style/css'

**Comment by benjycui** [comment]
2.0.0-beta.12
