### ISSUE TITLE
table 固定列IE11降级处理，td错位，但是antd官网的案例打开就不会？

### ISSUE THREAD

**Issue by woleicom** [ant-design/ant-design#31532]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/31531](https://github.com/ant-design/ant-design/issues/31531)

### Steps to reproduce
create-react-app创建新项目，然后引入Table官网案例，IE11打开会错位，但是antd的官网用IE打开就不会
示例仓库地址：https://github.com/woleicom/antd-table-IE11-issue
### What is expected?
重现步骤：create-react-app创建新项目，然后引入Table官网案例，IE11打开会错位，但是antd的官网用IE打开就不会
如图：
antd官网
![image](https://user-images.githubusercontent.com/9603048/126997585-3b4f4bad-efa1-42da-9380-054cedf6399c.png)
本地新建项目引入的antd官网案例
![image](https://user-images.githubusercontent.com/9603048/126997206-286ea9f3-8cb5-48ba-96be-9888c059457f.png)

不知道为什么我本地起来的服务table 降级处理fixed后不会清除td的left css属性值，官网的就可以，请问是我使用的版本有问题，还是官网做了hack处理？

### What is actually happening?
想跟官网一样在IE降级处理的时候style的left值也是0px，而不是td本身的width

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | react |
| System | mac 10.15.7 |
| Browser | IE 11 |

**Comment by woleicom** [comment]
> Hello @woleicom. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @woleicom, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

因为是IE11的问题，用codesandbox等无法打开，这里提供了仓库地址，麻烦了
示例仓库地址：https://github.com/woleicom/antd-table-IE11-issue

**Comment by afc163** [comment]
有 bug，IE 下不应该给 age 列加上 `left: 100px`。

<img width="1210" alt="图片" src="https://user-images.githubusercontent.com/507615/127133135-6a5c1f53-873a-44d0-8996-529bc4528a38.png">

对于 antd 官网显示正常的问题，经测试，antd 官网的 dom 结构和样式和 cra 出来的是一样的。显示正常感觉是 IE11 的渲染问题。

<img width="1234" alt="图片" src="https://user-images.githubusercontent.com/507615/127133313-a28eb0d5-89d8-45b4-8a24-b8c4b448799e.png">

下图是取消 `left: 100px` 后再勾选上的效果，样式应该和上图一样，但是渲染结果完全不一样。

<img width="1225" alt="图片" src="https://user-images.githubusercontent.com/507615/127133434-1ac009d3-49a1-48bc-b01e-796a806e899f.png">

---

解法是这里不应该加上 left 值，需要针对不支持 sticky 的浏览器进行处理。

**Comment by alienzhangyw** [comment]
希望早日解决这个问题

**Comment by Niofh** [comment]
最后怎么解决这个问题

**Comment by alienzhangyw** [comment]
> 最后怎么解决这个问题

我现在是代码里对浏览器做识别，如果是IE就不用固定列。

**Comment by GTuooa** [comment]
请问大佬，mac上怎么打开ie浏览器的？

**Comment by yoyo837** [comment]
找Windows呀.

**Comment by zombieJ** [comment]
有点蛋疼，ssr 要不一致了。
