### ISSUE TITLE
[Space] Spacing changed when setting one of the elements hidden

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#31544]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-antd4168-forked-46ttm?file=/index.js)

### Steps to reproduce
Enter the reproduction link.

### What is expected?
Spacing won't change when setting one of the elements hidden.

### What is actually happening?
Spacing changed when setting one of the elements hidden.
![image](https://user-images.githubusercontent.com/50612752/127123837-f5385ca1-5ed1-4ec3-9ca2-7f4676cb04be.png)

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 91.0.4472.114(x86_64) |

**Comment by afc163** [comment]
目前没有好的办法，对 Space 来说无法探测子节点是否是显示状态。

See https://github.com/ant-design/ant-design/issues/29816#issuecomment-802529304

**Comment by KAROTT7** [comment]
@afc163 不可以在渲染时过滤掉属性值 hidden=true 的元素吗？
