### ISSUE TITLE
Table 列头 如何居中？

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#3154]
className 只是设置列的内容居中。如何坐到Table 列头居中？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2465

---

Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).
