### ISSUE TITLE
Menu: Request to listen to the API of the status change of the submenu

### ISSUE THREAD

**Issue by ntscshen** [ant-design/ant-design#31556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Menu: Request to listen to the API of the status change of the submenu
Menu导航菜单: 请求监听子菜单状态变化的API

In the vertical menu, when moving into the second level dishes, to trigger a series of operations, I can't monitor them.
Although I can use the "onOpenChange" api, it will also be triggered when it is removed, and I can’t judge whether it’s open or closed in the parameters thrown.
在垂直菜单中，移入二级菜单时( 只在移入时 )，去触发一系列操作，我没办法监听它。
虽然我可以使用 “onOpenChange”这个api ，但是它在移出时也会被触发，并且我在抛出的参数中，没办法判断是打开还是关闭

### What does the proposed API look like?
Menu: Request to listen to the API of the status change of the submenu

Looking forward to a new monitoring method, which will only be triggered when the submenu is opened
期待一个新的监听方法，只有打开子菜单时被触发

### codesandbox
https://codesandbox.io/s/chuizhicaidan-antd4168-forked-80jhl?file=/index.js:1264-1805

**Comment by afc163** [comment]
onOpenChange 的第一个参数，可以存下来和前面的值进行比较，增加了某个 key 时表示打开了这个 submenu。

**Comment by ntscshen** [comment]
感谢~ 通过您说的方式可以实现获取hover展开的元素。Thanks♪(･ω･)ﾉ
不过我使用了jq on去监听，因为需求又改了，在点击根节点、submenu、末端节点时获取点击元素相对应的数据~
