### ISSUE TITLE
antd tree拖拽在节点挪到组件外时未清空指示器

### ISSUE THREAD

**Issue by bailinx** [ant-design/ant-design#31555]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)
直接官网demo可复现

### Steps to reproduce
在tree组件上拖拽节点，将节点挪到组件外，指示器未消失，对用户造成歧义

![image](https://user-images.githubusercontent.com/9367897/127154762-0e7eb54e-3233-43af-a4ef-07ed87a29b10.png)

### What is expected?
不能放置的时候清除指示器

### What is actually happening?
不能防止的时候指示器未消失

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | react 16 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
来个 PR 吧，不一定有时间修。

**Comment by 574495412** [comment]
请问这个问题是否被修复，需要pr吗？
