### ISSUE TITLE
Bug with Drawer on mobile view when scroll

### ISSUE THREAD

**Issue by WilferCiro** [ant-design/ant-design#31557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/72sde)

### Steps to reproduce
Press F12 in browser, enable mobile view (Ctrl   Shift   M), open the drawer with the button, and try to scroll in the drawer, in the console should appear an error

### What is expected?
The error showing in the console doesn't appear

### What is actually happening?
an error is occurring when scroll in drawer when mobile view is enabled

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.2 |
| System | Manjaro Linux; Build ID: rolling |
| Browser | Chrome 91.0.4472.77 (Official Build) (64-bit) |

---
Love antd <3

**Comment by Chimaa123** [comment]
I have faced same issue. Did you find a solution?
