### ISSUE TITLE
input allowclear style

### ISSUE THREAD

**Issue by sunxia628** [ant-design/ant-design#31550]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:3000/supplier/evaluation/index](http://localhost:3000/supplier/evaluation/index)

### Steps to reproduce
使用form包裹input，校验必填项，触发focus

### What is expected?
    box-shadow: 0 0 0 2px rgb(255 77 79 / 20%);样式与输入框重叠

### What is actually happening?
    box-shadow: 0 0 0 2px rgb(255 77 79 / 20%);样式加载在内容区域，没有和输入框重叠

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | win7 |
| Browser | chrome版本 91.0.4472.106（正式版本） （64 位） |

---
检查代码发现allowclear 的input外层会包裹一个span，后面也会添加一个span，这两个dom节点造成.ant-inputr的尺寸和.ant-form-item-control-input-content无法保持一致， 影响了box-shadow: 0 0 0 2px rgb(255 77 79 / 20%);样式效果！

<div class="ant-form-item-control-input-content"><span class="ant-input-affix-wrapper"><input placeholder="请输入" maxlength="128" type="text" id="nest-messages_idxName" class="ant-input" value=""><span class="ant-input-suffix"><span role="button" aria-label="close-circle" tabindex="-1" class="anticon anticon-close-circle ant-input-clear-icon-hidden ant-input-clear-icon"><svg viewBox="64 64 896 896" focusable="false" data-icon="close-circle" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm165.4 618.2l-66-.3L512 563.4l-99.3 118.4-66.1.3c-4.4 0-8-3.5-8-8 0-1.9.7-3.7 1.9-5.2l130.1-155L340.5 359a8.32 8.32 0 01-1.9-5.2c0-4.4 3.6-8 8-8l66.1.3L512 464.6l99.3-118.4 66-.3c4.4 0 8 3.5 8 8 0 1.9-.7 3.7-1.9 5.2L553.5 514l130 155c1.2 1.5 1.9 3.3 1.9 5.2 0 4.4-3.6 8-8 8z"></path></svg></span></span></span></div>

![QQ图片20210727184725](https://user-images.githubusercontent.com/26341016/127141760-e365c6a9-e6c4-43ce-b780-cf6bd607777a.png)

**Comment by sunxia628** [comment]
codesandbox实例： https://codesandbox.io/s/antd-reproduction-template-forked-rss5k?file=/index.js:188-196
 这个实例无法浮现我的问题，因为有样式代码：
 .ant-form-item-has-error .ant-input-affix-wrapper input:focus {
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}
覆盖了问题样式，我调整了react和antd版本但还是无法复现，以上样式我本地并未加载出来！

**Comment by afc163** [comment]
请升级到 antd@4.16.9

**Comment by Erchoc** [comment]
> 请升级到 antd@4.16.9

出现同样的问题，升级到 v4.16.13 依旧存在。

表现为添加 allowClear 后 ant-input-affix-wrapper 自动加了 display: block 属性，导致样式发生变更
