### ISSUE TITLE
Select can't be clicked and closed when don't import global css

### ISSUE THREAD

**Issue by gengxuelei** [ant-design/ant-design#31568]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-antd4169-forked-9neq9?file=/index.js)

### Steps to reproduce
only use the css of select  
```  
// import 'antd/dist/antd.css';  
import "antd/lib/select/style/index.css";  
```

The associated issue：  
https://github.com/ant-design/ant-design/issues/9363#issuecomment-490545432

### What is expected?
normal

### What is actually happening?
Select can't be clicked and closed when don't import global css

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | latest |
| System | mac  Catalina |
| Browser | chrome |

**Comment by afc163** [comment]
```diff
- import "antd/lib/select/style/index.css";  
+ import "antd/lib/select/style";  
```

**Comment by gengxuelei** [comment]
@afc163 thanks for your reply. But it seems that you don't get my point.
I don't want to be affected by the global css, so I just import component css instead of antd css.
But that css.js not just import button's styles, also import general styles, this is it's content:
```
"use strict";

// General styling (body, h1, h2..)
require("../../style/index.css");

// Button styles
require("./index.css");

```

Other component is ok when only import index css. 
Select is not ok.

The associated issue：
https://github.com/ant-design/ant-design/issues/9363#issuecomment-490545432

Watting for your answer……

**Comment by gengxuelei** [comment]
Select component rely on the `motion.less`

```
@import "~antd/lib/style/core/motion.less";
```
so `import "antd/lib/select/style/index.css";` can not work alone.

---
So there two ways to solve this issue:  
1. bundle the `motion.less` to `antd/lib/select/style/index.css` to make this componet can work alone;
2. offer `motion.css` so the user can import both `component.css` and `dependent.css(sush as motion.css)`.

I know that the ant team has thier consideration with including `global.css`.
But there is really some cases that the develeper cannot import other `global.css`.
Best wishes !
