### ISSUE TITLE
Form能否支持托管Upload?

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#31560]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuozhuaishangchuan-antd4169-forked-xkn19?file=/index.js)

### Steps to reproduce
上传文件后会直接报错.

### What is expected?
托管后, 可以让Form里的Upload不用再写onChange和fileList等等的逻辑.
比如我用Upload和七牛云结合上传文件, 我只要写好data里的token和key就行了, 不用每个都写onchange, 就能在form.validate()里拿到相应的file数据.

### What is actually happening?
上传文件报错

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome 92 |

**Comment by yoyo837** [comment]
可以的, 参考 自定义表单控件

https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
