### ISSUE TITLE
babel-plugin-import引入后控制台报推荐安装babel-plugin-antd警告

### ISSUE THREAD

**Issue by zhangolve** [ant-design/ant-design#3156]
#### 发生问题的环境是：

- antd 版本:antd@1.11.1
- 操作系统及其版本: windows 7 旗舰版 64位操作系统
- 浏览器及其版本:chrome 51 64bit

#### 您做了什么？
使用 npm install antd 命令下载了最新的ant design 包，在项目的package.json中添加了依赖："antd":"^1.x.x", 也添加了babel-plugin-import 这个包，项目在本地chrome浏览器下打开控制台，显示警告信息:
>You are using prebuilt antd,
>please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.

锁定警告位置在antd.js文件(24584行左右)

    if (true) {
    if (typeof console !== 'undefined' && console.warn) {
    console.warn('You are using prebuilt antd,\nplease use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.');
	  }
	}

这个antd.js文件太大，我没有看全，但这个上面的链接给出的是已经失效的babel-plugin-antd包，尽管这个链接会自动跳转到https://github.com/ant-design/babel-plugin-import 

我明明已经通过npm install babel-plugin-import 引入了这个包，为什么还会出现警告提示。

#### 您期待的结果是：

在控制台上不会出现上面那样的警告信息，即便是有警告信息，也应该给出正确的链接。

#### 实际上的结果是：

在控制台上出现的警告信息有误导，让人想要安装一个babel-plugin-antd的包，但事实上这个包已经更名了，变成了babel-plugin-import

#### 可重现的在线演示

暂无

**Comment by afc163** [comment]
babel-plugin-antd 没有失效，只是后来改名为 babel-plugin-import 了。原来的文档可以看：https://github.com/ant-design/babel-plugin-import/tree/0.5.1

@benjycui 可以在 1.11.2 里把这个链接也改掉。
