### ISSUE TITLE
编辑table中单元格的时候，控件InputNumber输入超级长的值的时候，加减是无效得，展示得值和输入得值也不一致

### ISSUE THREAD

**Issue by luoxuemei123** [ant-design/ant-design#31577]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-edit-row](https://ant.design/components/table-cn/#components-table-demo-edit-row)

### Steps to reproduce
在table中编辑数据，InputNumber控件中输入超长的数字

### What is expected?
 输展示的数字和输入的一致，并且可以正常使用加减功能

### What is actually happening?
展示和输入不一致，不能使用加减功能

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | react |
| System | Windows 10 专业版 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
You should use `stringMode` for big number.

https://ant.design/components/input-number-cn/#components-input-number-demo-digit
