### ISSUE TITLE
Custom tag render with array of objects in Select throwing two children with the same key error in the console

### ISSUE THREAD

**Issue by aashayamballi** [ant-design/ant-design#31570]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/custom-tag-render-antd4169-forked-9ndys?file=/index.js)

### Steps to reproduce
Create an array of objects (in the minimal reproduction I've created with the name options)
Pass that options to Select's option prop
Create a function for tag render 

### What is expected?
In the console, we should not get any errors.

### What is actually happening?
Even though I have given the key for Tag in the custom tag render function, in the console it is displaying the below error 

encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.2 |
| System | Windows 10 Pro |
| Browser | Google Chrome Version 84.0.4147.89 (Official Build) (64-bit) |

**Comment by afc163** [comment]
`defaultValue` only accept `string[] | number[]` when `mode="multiple"`.
