### ISSUE TITLE
[Bug] The hidden column hold the space still when ellipsis is true and dataSource is empty

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#31572]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-antd4169-forked-5rd0c)

### Steps to reproduce
See the reproducible demo.
![image](https://user-images.githubusercontent.com/14918822/127430271-c015dd5e-7eee-4c82-9ecc-7a641a52ee05.png)

### What is expected?
The hidden column should not hold space.

### What is actually happening?
The hidden column hold the space still.

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 16.14.0 |
| System | MacOS 10.15.5 |
| Browser | Chrome 91.0.4472.114 |

**Comment by afc163** [comment]
1. You can remove column item instead of using `hide` className.
2. You can set `tableLayout="auto"` as workaround, but it may affect `ellipsis` function. https://codesandbox.io/s/jibenyongfa-antd4169-forked-lnktb?file=/index.js:437-445

**Comment by dengfuping** [comment]
> 1. You can remove column item instead of using `hide` className.
> 2. You can set `tableLayout="auto"` as workaround, but it may affect `ellipsis` function. https://codesandbox.io/s/jibenyongfa-antd4169-forked-lnktb?file=/index.js:437-445

- If handle it inside the Table by adjusting `tableLayout` value automatically, upper project will reduce many duplicated `if/else` logic. Hopefully, column supports for `visible` prop maybe better solution as #28243 mentioned.
