### ISSUE TITLE
InputNumber 在表单里验证不通过

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#3157]
#### 发生问题的是：
校验：
` const duration = getFieldProps('duration', {
      rules: [
        {validator : (rule, value, callback)=>this.onDurationChange(rule, value, callback)}
      ],
      initialValue: 1,
    });`

赋值的时候：
`setFieldsValue({
        duration:moment(time).diff(startTime, 'hours')
      })`

表面上看值赋过去了而且getFieldValue('duration')得到的也是正常的
但是会提示错误'duration need to revalidate!'
然后InputNumber的值变为1，此时再提交就可以通过了！！

- antd 版本:最新

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
是最新 1.x 还是 2.0-beta？

**Comment by dreamcatcher081210** [comment]
不是beta

**Comment by benjycui** [comment]
demo

**Comment by dreamcatcher081210** [comment]
正在搬，稍等

**Comment by benjycui** [comment]
ping~

**Comment by dreamcatcher081210** [comment]
@benjycui 麻烦问下，一般都是什么情况才会报need to revalidate？

**Comment by afc163** [comment]
https://github.com/react-component/form/blob/2fc992ad1771c993a89b498c268e5ec7e91614a9/src/createBaseForm.js#L532-L541

想办法给出重现才好解决，很多细节我们也要去源码里挖才能确定是 bug 还是别的问题。

**Comment by afc163** [comment]
看下这里：https://github.com/ant-design/ant-design/issues/3313

**Comment by dreamcatcher081210** [comment]
@afc163 谢谢，但不是这个原因，最近有时间查看了下源码，再对比下local code 发现我在表单里用到了onChange事件，由于onChange事件和getFieldProps相冲突（当时是1.X version，可以更改trigger,但是由于业务需求，而不能这么做）所以我就把onChange用验证里的validator所代替，注意，此处是重点！当我进入修改页面点击submit时，会触发validator，而恰恰在validator函数里有存在导致报出 need to revalidate的code，鉴于已将项目升级到2.X，所以全部替换掉validator而使用onChange，问题解决~
