### ISSUE TITLE
in Progress component the success.strokeColor prop does not work for circle and dashboard types

### ISSUE THREAD

**Issue by Rnb1189** [ant-design/ant-design#31587]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/progress-bar-with-success-segment-antd4169-forked-n2dn6)

### Steps to reproduce
Just set the success.strokeColor to something. type should be 'circle' or 'dashboard'

      <Progress
        percent={60}
        success={{ percent: 30, strokeColor: "red" }}
        type="circle"
      />

### What is expected?
The stroke color of success section should be red

### What is actually happening?
The stroke color of success section is default green color

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 16.14 |
| System | Windows 10 64 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/24655 漏了 Circle。
