### ISSUE TITLE
Checkbox with nested Input component not checkable when input value is set to initial value

### ISSUE THREAD

**Issue by goonerholic** [ant-design/ant-design#31583]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-moon-9oz15?file=/src/App.tsx)

### Steps to reproduce
After change the value of InputNumber component and change it back to initial value(let's say 0) then the checkbox is not checkable

### What is expected?
Should be checked regardless of the value inside of the InputNumber component

### What is actually happening?
Can't check the checkbox when InputNumber component's value is set to initial value(initial state)

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17 |
| System | Mac m1 bigsur |
| Browser | chrome |

I'm implementing some kind of filter component and basically it's a set of checkbox.
I want to let user change the value of checkbox so I placed a `InputNumber` component inside of the Checkbox.
It works fine except when I change the value of InputNumber component to the initially set value.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20922#issuecomment-574563526

**Comment by goonerholic** [comment]
In that example, `onChange={e => e.target.value}` returns `undefined`.
How do I get value from checkbox?
