### ISSUE TITLE
树形控件的受控操作实例的TypeScript代码无法运行

### ISSUE THREAD

**Issue by Wingsky6** [ant-design/ant-design#31584]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Wingsky6/bug/tree/main/my-app](https://github.com/Wingsky6/bug/tree/main/my-app)

### Steps to reproduce
`cd my-app`

`npm install`

`yarn start`

### What is expected?
启动项目

### What is actually happening?
启动失败，onCheck标红报错！显示错误：
(JSX attribute) onCheck?: ((checked: Key[] | {
    checked: Key[];
    halfChecked: Key[];
}, info: CheckInfo) => void) | undefined
不能将类型“(checkedKeysValue: React.Key[]) => void”分配给类型“(checked: Key[] | { checked: Key[]; halfChecked: Key[]; }, info: CheckInfo) => void”。
  参数“checkedKeysValue”和“checked” 的类型不兼容。
    不能将类型“Key[] | { checked: Key[]; halfChecked: Key[]; }”分配给类型“Key[]”。
      类型“{ checked: Key[]; halfChecked: Key[]; }”缺少类型“Key[]”的以下属性: length, pop, push, concat 及其他 28 项。ts(2322)

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 17.0.2 |
| System | win10 |
| Browser | Edge |

---
onCheck不管怎么改都没用！直接改Tree.d.ts里面的onCheck接口属性也不起作用

**Comment by afc163** [comment]
https://github.com/Wingsky6/bug/pull/1

**Comment by floki2020** [comment]
不是已经修复了嘛？怎么还是 不好用 version 4.20.0 还是同样的错误
