### ISSUE TITLE
InputNumber 收集的值 如果是undefined 为什么要转为null, null 作为请求参数不会被过滤掉

### ISSUE THREAD

**Issue by hugo1o1** [ant-design/ant-design#31588]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ https://hugo1o1.github.com(无)]( https://hugo1o1.github.com(无))

### Steps to reproduce
https://hugo1o1.github.com（无）

### What is expected?
返回undefined

### What is actually happening?
返回null

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
历史原因，原因见 https://github.com/ant-design/ant-design/issues/13896#issuecomment-449888620
