### ISSUE TITLE
Not Testable: Lot of AntD component doesn't work well with testing-library

### ISSUE THREAD

**Issue by balavishnuvj** [ant-design/ant-design#31595]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tender-ishizaka-c3s6s )

### Steps to reproduce
There aren't any NON-HACKY way to test Select. Though this issue not only with Select, other components like Menu, Tabs etc are also affected.

### What is expected?
To be able to test component without having to add hacky logic suggested here https://github.com/ant-design/ant-design/issues/31105#issuecomment-866947884

### What is actually happening?
Tests fail without hacks

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.0 |
| System | Mac |
| Browser | Chrome latest |

---
AntD has great set awesome components. But they are very difficult to test. If the team aligned to fix these issues, I am more than happy to help.

**Comment by sleepyArpan** [comment]
happy to help on the same, hacks are easy to introduce but difficult to maintain across versions

**Comment by afc163** [comment]
https://stackoverflow.com/a/61115234/3040605
https://github.com/ant-design/ant-design/issues/23009

**Comment by balavishnuvj** [comment]
@afc163, the solution in stackoverflow is just a hack. it doesn't address the underlying problem :(

**Comment by hannadrehman** [comment]
hack is never a solution @afc163  is there a plan to fix the actual problem ?

**Comment by Harukisatoh** [comment]
Why is this still closed? The problem is still there

**Comment by lewisloofis** [comment]
Hello, can you reopen this issue, this problem is not done yet

**Comment by ChristopherChudzicki** [comment]
Until this is fixed, passing `{ pointerEventsCheck: 0 }` to `click` seems like the best workaround: `user.click(element, { pointerEventsCheck: 0 });`

**Comment by dagadbm** [comment]
This is still happening. Its just makes testing completely messy at this point.

**Comment by OleksiiKachan** [comment]
if landed here looking on how to trigger `onChange` when you do `fireEvent.change()` on date picker. this what finally worked for me

```
      act(() => {
        fireEvent.mouseDown(getByTestId(`expiresAt`));
      });

      act(() => {
        fireEvent.click(screen.getByTitle(date.format(`YYYY-MM-DD`)));
      });
```
