### ISSUE TITLE
select-onSelect-无法更新下拉框视图

### ISSUE THREAD

**Issue by FoSuCloud** [ant-design/ant-design#31594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-glade-gw2vh)

### Steps to reproduce
1、选中3
2、可以看到搜索框中会增加3，但是下拉框中没有增加3

### What is expected?
搜索框和下拉框结果一致

### What is actually happening?
搜索框和下拉框结果不一致

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | react |
| System | mac 10.15.7 |
| Browser | chrome 92 |

---
解决方案：对value的值进行深拷贝可以解决。value="yAxis.slice()"
为什么需要做深拷贝？

**Comment by afc163** [comment]
是不是搞复杂了，直接 onChange 可否？https://codesandbox.io/s/romantic-black-zzm0y?file=/src/index.js

**Comment by FoSuCloud** [comment]
> 是不是搞复杂了，直接 onChange 可否？https://codesandbox.io/s/romantic-black-zzm0y?file=/src/index.js

可以使用onChange完成我的需求。但是我想要使用onSelect和deSelect实现该功能的话该如何做？
