### ISSUE TITLE
select  不使用onChange的值去更改value-无法更新下拉框视图

### ISSUE THREAD

**Issue by FoSuCloud** [ant-design/ant-design#31599]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-voice-uwzxw?file=/src/index.js)

### Steps to reproduce
1、选中3

2、可以看到搜索框中会增加3，但是下拉框中没有增加3

### What is expected?
搜索框和下拉框结果一致

### What is actually happening?
搜索框和下拉框结果不一致

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | react |
| System | mac 10.15.7 |
| Browser | chrome 92 |

---
解决方案：
1、对value的值进行深拷贝可以解决。value="yAxis.slice()"；

2、使用onChange传递的新的值；

但是为什么传递之前的value数组就不可以？一定要改变引用地址？

**Comment by afc163** [comment]
https://github.com/react-component/select/blob/6b3dda770e68d71a717d695adc04cea38691b225/src/generate.tsx#L414-L415

4.x 视 value 为 immutable 对象，对同一个引用的内容做了 useMemo，对性能有明显提升。

**Comment by FoSuCloud** [comment]
> https://github.com/react-component/select/blob/6b3dda770e68d71a717d695adc04cea38691b225/src/generate.tsx#L414-L415
> 
> 4.x 视 value 为 immutable 对象，对同一个引用的内容做了 useMemo，对性能有明显提升。

建议写在文档说明中，我想了好久才想到用深拷贝解决，对开发会造成一些困扰

**Comment by afc163** [comment]
可以来个 PR 优化一下文档。@FoSuCloud
