### ISSUE TITLE
使用了ConfigProvider指定locale, 再用ReactDOM.render再次渲染一个ConfigProvider之后并销毁, 原app中的Modal.confirm方法locale会重置为default(en)

### ISSUE THREAD

**Issue by MobsMao** [ant-design/ant-design#31597]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-lamarr-svb86?file=/src/App.js)

### Steps to reproduce
步骤在重现链接中有详细描述:

1. 使用ConfigProvider locale={zhCN} 渲染一个应用, 并在其中查看Modal.confirm, locale是zhCN
2. 使用ReactDOM.render 再次渲染一个ConfigProvider locale={zhCN} locale是znCN没问题
3. unmount第二步渲染的ConfigProvider
4. 查看Modal.confirm, locale变回了默认值

### What is expected?
Modal.confirm的locale不要随着另外渲染的ConfigProvider变化

### What is actually happening?
Modal.confirm会随着另外渲染的ConfigProvider而变化

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.2 |
| System | win10 21H1 |
| Browser | edge 92.0.902.55 |

---
业务上用了ReactDOM.render 去渲染一些别的组件, 因为涉及到locale context不能传递的问题, 在其中再次渲染了一次ConfigProvider.
发现是 在LocaleProvider 中 willUnmount会调用 changeConfirmLocale()  重置为了default.

**Comment by afc163** [comment]
- 最好不要嵌套多个 ConfigProvider `locale`。
- 或者不使用静态方法，而是换成 https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux%E3%80%81%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F

**Comment by darknessjs** [comment]
https://github.com/ant-design/pro-components/blob/master/packages/provider/src/index.tsx
所以要参照这个，不要封装ConfigProvider local
但是用这种形式就可以了？

能解释下为什么要这么设计吗？
不然这个ConfigProviderWrapper看起来就是个为了规避configprovider不合理问题的hack组件
