### ISSUE TITLE
onDropdownVisibleChange监听不准

### ISSUE THREAD

**Issue by qiang-chen** [ant-design/ant-design#31598]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
select的监听下拉菜单是否展开的onDropdownVisibleChange触发不准。mac全屏状态从显示器拖到小电脑他自己关闭了下拉菜单但是不触发onDropdownVisibleChange   意思就是改变窗口大小的时候下拉菜单关闭 但是onDropdownVisibleChange不会触发。 另外测试说静止很长时间后下拉菜单也会自动关闭onDropdownVisibleChange同样不会触发

### What is expected?
onDropdownVisibleChange正常触发

### What is actually happening?
onDropdownVisibleChange监听不准

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.2 |
| System | mac |
| Browser | 谷歌最新版 Google's latest version |

**Comment by afc163** [comment]
> 意思就是改变窗口大小的时候下拉菜单关闭

没有重现出来，单独拖动改变浏览器窗口大小的时候下拉菜单没有关闭。

**Comment by afc163** [comment]
> mac全屏状态从显示器拖到小电脑他自己关闭了下拉菜单但是不触发onDropdownVisibleChange

这个的重现步骤是什么，能拍个视频看看么？
