### ISSUE TITLE
希望 Image 组件，支持展示一个封面图，打开后可以预览多张图片

### ISSUE THREAD

**Issue by alvin0216** [ant-design/ant-design#31605]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
只是想显示一张封面，点开后才进行翻页显示

### What does the proposed API look like?
list

**Comment by afc163** [comment]
可以试试 https://github.com/react-component/image/pull/65/files#diff-c265d8cca1b787c9c67d0c8cc6507b2a549eeed6402219d9b513c6d1382b6447
