### ISSUE TITLE
ant-design-pro v5 容器中不存在模块“/antd/es/tree select/style”

### ISSUE THREAD

**Issue by zxm-hh** [ant-design/ant-design#31603]
devScripts.js:6523 [@umijs/runtime] load component failed 
Error: Module "./antd/es/tree-select/style" does not exist in container.
while loading "./antd/es/tree-select/style" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:813

请问这个问题是怎么引起的，该怎么解决

**Comment by naas1d513215** [comment]
老哥解决了吗？

**Comment by vosonwang** [comment]
fix:
https://github.com/ant-design/ant-design-pro/issues/8842

**Comment by reesezxf** [comment]
删除 .umi 目录,重新启动 就好了
