### ISSUE TITLE
[Select:Tags mode]: do not convert text into tags

### ISSUE THREAD

**Issue by truedrug** [ant-design/ant-design#31604]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=0010](https://codepen.io/benjycui/pen/KgPZrE?editors=0010)

### Steps to reproduce
- I am using select tag with mode as "tags"
- Upon entering a text and pressing "enter" button on the keyboard, I want to validate whether entered text is a valid email-id or not, if it is not then I don't want the text to be converted into tags
- Right now I have used tagRender, but that is only the visual part of it (the text still gets converted into tags), I really do not have control on the conversion part (to convert into tags or not)

### What is expected?
If the entered text is not valid email-id, then on pressing enter button, it should not get converted into tags

### What is actually happening?
When, I am entering text with invalid email-id, and pressing enter button, it gets converted into tags

| Environment | Info |
|---|---|
| antd | 4.10.2 |
| React | 16.14.0 |
| System | macos |
| Browser | Chrome |

---
Sorry, but I wasn't able to make the codepen work

**Comment by truedrug** [comment]
Can someone help please? And let me know, if this is even doable

**Comment by afc163** [comment]
You may need https://ant.design/components/auto-complete/ instead of Select mode tags.
