### ISSUE TITLE
引用React方式改变的疑惑

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#3160]
看到现在引用react的方式改回import React from 'react'，因为react的d.ts文件中也没有default export，所以会报Module '"react"' has no default export的错误，不知道是出于什么考虑会导致这样的改动？

**Comment by benjycui** [comment]
加上 [这行](https://github.com/ant-design/ant-design/blob/master/tsconfig.json#L4) 就不会报错了。

然后对于类似 `moment` 这样的包，必须 `import moment from 'moment'`，所以统一一下。
