### ISSUE TITLE
antd table  rowSelection getCheckboxProps 无法同时设置 disabled 和 defaultChecked

### ISSUE THREAD

**Issue by wangcongyi** [ant-design/ant-design#31601]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-951ue)

### Steps to reproduce
设置了disabled 和 defaultChecked  
disable 功能ok，但 checkbox 的 样式 没有勾选上

### What is expected?
checkbox 也能勾选上，样式正确

### What is actually happening?
checkbox 不能默认勾选上，样式不正确

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.14.0 |
| System | win |
| Browser | chrome |

**Comment by wangcongyi** [comment]
使用 selectedRowKeys 也不行

**Comment by afc163** [comment]
selectedRowKeys 生效的。

https://codesandbox.io/s/antd-reproduction-template-forked-2mekq?file=/index.js
