### ISSUE TITLE
Tabs 组件的 activeKey 支持正则或自定义方法

### ISSUE THREAD

**Issue by zzjin23** [ant-design/ant-design#31614]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
碰到一个场景会把 tabs 当成二级导航来使用，active 如果是跟一组 url 关联的时候，就无法通过单个 key 去判断了。

### What does the proposed API look like?
```
interface TabProps {
  ...
  activeKeyRule: RegExp | (key: string) => void;
}
```

**Comment by afc163** [comment]
UI 组件库不应该做过多事情，保持简单比较好。

**Comment by zzjin23** [comment]
> UI 组件库不应该做过多事情，保持简单比较好。

认同这个原则。但是这个 case 需要的是开放 API，是不是可以考虑支持自定义方法，或者 active 状态支持完全受控

**Comment by afc163** [comment]
activeKey 是完全受控的。
