### ISSUE TITLE
initalValues为数字类型，modal弹框显示，点击校验时无法通过，获取不到值

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/ant-design#31610]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/danchucengzhongdexinjianbiaodan-antd4169-forked-y7wgo?file=/index.js)

### Steps to reproduce
1. 点击打开弹框
2. 点击提交create，触发校验，发现报错

### What is expected?
1. 打开弹框
2. 点击create，触发校验就能直接通过提交

### What is actually happening?
1. 点击打开弹框
2. 点击提交create，触发校验，发现报错

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.9 |
| System | mac |
| Browser | chrome |

---
1. 找到这个bug的问题是因为发现，如果是数字类型就会出现，如果改为string类型就不会

1.
        initialValues={{
          modifier: "public",
          title: "2"
        }}
2.
        initialValues={{
          modifier: "public",
          title: 2
        }}

**Comment by afc163** [comment]
你已经找到问题所在了，Input 接收的是 string 不是 number。
