### ISSUE TITLE
Progress和Statistic 数据增减动效

### ISSUE THREAD

**Issue by johnsonz** [ant-design/ant-design#31616]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Progress和Statistic 数据增减动效

### What does the proposed API look like?
Progress和Statistic组件有没有可能添加数据增减的动画效果，比如要显示100，动效是从1增加到100，而不是直接显示100

**Comment by afc163** [comment]
需要自行控制给 Progress/Statistic 传递的 percent/value 变化。
