### ISSUE TITLE
table Prop bordered 设置 false 对header cells 不生效吗

### ISSUE THREAD

**Issue by dadazhouRenee** [ant-design/ant-design#31623]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mwqml?file=/index.js)

### Steps to reproduce
1. 官方示例链接 
2. 当前antd版本是最新版本 `4.16.9`，bordered  默认是false
3. change antd version `4.15.6`

### What is expected?
希望 border 为false 时 , table header celle 没有右侧边框

### What is actually happening?
现在有border， 代码一样，效果不一样
![1627895960(1)](https://user-images.githubusercontent.com/31841446/127837214-0b830a11-a4b1-4468-8985-0c1e2299e646.png)

最新版本：
![1627896031(1)](https://user-images.githubusercontent.com/31841446/127837377-c50f382e-bf3b-474e-9edd-71b2c1650f78.png)

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 16.14.0 |
| System | 10 |
| Browser | chrome |

---
官方api描述:   ` bordered 是否展示外边框和列边框 `

4.16.0以前的版本好像不是这样的，是样式的调整吗？在changelog 中没有找到。

**Comment by afc163** [comment]
https://ant.design/changelog-cn#4.16.0

https://github.com/ant-design/ant-design/pull/30651
