### ISSUE TITLE
如何根据table单元格不同的值去渲染不同的背景色

### ISSUE THREAD

**Issue by NorthwesternDirector** [ant-design/ant-design#31625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-antd4169-forked-0zclh?file=/index.js:367-389)

### Steps to reproduce
如代码所示

### What is expected?
整个单元格都被设置为指定背景色

### What is actually happening?
无法选中单元格元素，导致单元格的padding无法整个被填充背景色

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | Chrome 85.0.4183.83 |

**Comment by afc163** [comment]
https://codesandbox.io/s/jibenyongfa-antd4169-forked-t0kxb?file=/index.js
