### ISSUE TITLE
TreeSelect Searching - If parent matches, all children are shown even when they dont match

### ISSUE THREAD

**Issue by Vlieg83** [ant-design/ant-design#31628]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/c6s9j)

### Steps to reproduce
filter the antd example using "parent 1-0"

### What is expected?
Only display the matching results.
Example:
Search Value = "parent 1-0"
Tree:
![image](https://user-images.githubusercontent.com/37828967/127894857-986fb7a7-c73c-4494-b5da-643353f69e5d.png)

Results:
parent 1-0

### What is actually happening?
When searching, elements / children are showing in the results that do not match the original search value.
Seems like if the parent matched, all the children are always displayed.
Example:
Search Value = "parent 1-0"
Tree:
![image](https://user-images.githubusercontent.com/37828967/127894857-986fb7a7-c73c-4494-b5da-643353f69e5d.png)

Results:
![image](https://user-images.githubusercontent.com/37828967/127894623-824d0da7-6ba2-424a-94e5-b1959e77abe6.png)

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 16.11.0 |
| System | Windows |
| Browser | Chrome |

---
The same behaviour can be seen on the ant-d treeselect Basic example on V4.16.10.
On Antd 3.x this behaviour is not there and behaves as expected and described above.
![image](https://user-images.githubusercontent.com/37828967/127894701-eabffd0d-4770-46b1-bdc7-e261c2f206ba.png)

**Comment by afc163** [comment]
It is intented behavior, there is common need that find children by searching parent keyword.

**Comment by Vlieg83** [comment]
I understand that there are usecases for the current behaviour, but the usecase for the old behaviour also exists (which we have).

Can we not have an additional property to handle how strict the filtering should be?
strict = true: "display unmatched children"
strict = false (default): "do not display children that do not match the required filter"
