### ISSUE TITLE
TreeSelect如何实现：点击TreeNode的title可以展开子节点

### ISSUE THREAD

**Issue by zhoudalang** [ant-design/ant-design#31621]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前TreeSelect子节点的展开是通过点击父节点左边的三角形实现，点击父节点的title不会展开。

### What does the proposed API look like?
设置api属性为true后，点击父节点的title可以展开

**Comment by afc163** [comment]
选择和展开交互会有冲突，目前不会原生实现在 antd 中。

**Comment by javaJackfeng** [comment]
当点击title 的时候使用jquery 触发switcher 的 click 事件

**Comment by aaronxdd** [comment]
1、首先treeExpandedKeys受控
2、改写父节点的title属性，自定义组件，添加点击事件，控制treeExpandedKeys
