### ISSUE TITLE
antd Select mode='tags'  删除dropdownRender中Input中的文字内容，会把 Select输入框中的tag一并删除

### ISSUE THREAD

**Issue by 00qiu00** [ant-design/ant-design#31633]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuozhancaidan-antd4169-forked-fzm2s?file=/index.js)

### Steps to reproduce
点开Select下拉框，聚焦Input，点击键盘删除Backspace按键，Input中文字被删除一个，Select中的 Tag 也会被删除一个

### What is expected?
Select中的 Tag 应该不被删除状态应该独立

### What is actually happening?
Select中的 Tag 被删除

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | reacr17 |
| System | win10 |
| Browser | Google Chrome 87.0.4280.66 |

---
官网上 Select 中扩展菜单 这个事例 ，把Select中的mode改为tags，直接就会出现这个问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28694#issuecomment-754471826
