### ISSUE TITLE
本地 component/badge单测失败

### ISSUE THREAD

**Issue by Dreamerryao** [ant-design/ant-design#31644]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ https://github.com/ant-design/ant-design.git]( https://github.com/ant-design/ant-design.git)

### Steps to reproduce
- yarn install
- npm run test components/badge

### What is expected?
单测成功

### What is actually happening?
单测失败

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome92.0.4515.107 |

**Comment by afc163** [comment]
<img width="803" alt="图片" src="https://user-images.githubusercontent.com/507615/128118495-cc3f0791-4c3b-463f-83fc-48da658bdbad.png">

It works in my machine.

**Comment by Dreamerryao** [comment]
是由于做出了修改后Snapshots发生变化，抱歉 :(
