### ISSUE TITLE
Carousel 走马灯的内容区域动态获取时，会空白一段时间

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design#3164]
antd 的版本是1.11.1
Carousel 的内容是异步动态获取的图片，效果具体是这样的：
先展示了一张图片，一秒中后直接变空白，大概过了2秒会切换图片，这时图片又能显示了，之后一直显示正常。

**Comment by small752** [comment]
来个人帮忙看下哦

**Comment by benjycui** [comment]
这个是正常的吧，异步获取就会面临网络问题。

**Comment by benjycui** [comment]
没有明显性能问题之前，不需要搞什么异步。。

**Comment by afc163** [comment]
不给 demo 怎么看？

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by small752** [comment]
我换个问题，我用的Carousel组件，但是我想调用react-slick的方法，如何能调到，比如slickNext();函数

**Comment by benjycui** [comment]
补充了 `ref`。
