### ISSUE TITLE
<Select>组件maxTagCount在responsive类型下没有提供方法获取截断展示的那些具体选项

### ISSUE THREAD

**Issue by gaomigithub** [ant-design/ant-design#31651]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我希望可以提供去获取被截断的选项数组（ x ...）内容的接口&方法；知道被responsive的options。在有需要的时候可以直观展示被省略的内容；例如结合Tooltip或直接输出而不是点开下拉框去翻看option哪些被勾选。

![image](https://user-images.githubusercontent.com/27126195/128134977-0f8849e6-0042-48d6-b7fd-422f92eba413.png)

### What does the proposed API look like?
responsiveValue: function(value, option:Option | Array<Option>)

**Comment by hga97** [comment]
这个功能是不是还没有出呀，刚好产品想要这种效果。

**Comment by zombieJ** [comment]
> 这个功能是不是还没有出呀，刚好产品想要这种效果。

这个 issue 老了，有 `maxTagPlaceholder` 可以自定义了：
https://codesandbox.io/s/xiang-ying-shi-maxtagcount-antd-5-10-0-forked-c6zkq4?file=/demo.tsx
