### ISSUE TITLE
layouts 文件夹怎么不见了

### ISSUE THREAD

**Issue by jdfrozen** [ant-design/ant-design#31652]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
layouts 文件夹怎么不见了

### What does the proposed API look like?
layouts 文件夹怎么不见了

**Comment by xgAnd** [comment]
> Cannot understand your question.

现在antd-pro 没有生成layouts文件夹了
Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🚀 Do you need all the blocks or a simple scaffold? simple
和文档中的文件夹解构不相符 是做了修改了嘛 我看demo中加载直接加载的库文件
 import { PageContainer } from '@ant-design/pro-layout';
https://pro.ant.design/zh-CN/docs/folder
