### ISSUE TITLE
TreeSelect（多选）在做数据回显时，部分treeData的节点为禁用，数据中有这些禁用节点的value，出现的问题是节点能匹配，但是节点前面的多选框为未选中状态！

### ISSUE THREAD

**Issue by tpc-ht** [ant-design/ant-design#31658]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-cnfhkm?file=src/index.js](https://stackblitz.com/edit/react-cnfhkm?file=src/index.js)

### Steps to reproduce
https://stackblitz.com/edit/react-cnfhkm?file=src/index.js

### What is expected?
禁用的节点显示选中状态

### What is actually happening?
禁用的节点显示选中状态

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 17.x |
| System | w10 |
| Browser | Google |

**Comment by afc163** [comment]
#30143 

@zombieJ

**Comment by z27fang** [comment]
请问这个issue还需要修复嘛，我有兴趣参与！

**Comment by yoyo837** [comment]
PR welcom.

**Comment by z27fang** [comment]
update:
目前查到的原因是由于`tree-select`使用`value`作为数据源，同样这也是`rc-tree-select`的数据源，然而`rc-tree-select`使用的`rc-tree`则将`key`作为数据源，所以在数据最终传到`rc-tree`组件中需要将value改成key。

`rc-tree-select`用以下function来进行这个转换，但是由于node被disable而导致被选中的`value`的`key`为`null`，最终导致无法被勾选。
https://github.com/react-component/tree-select/blob/c51317d9213add27d84384a479153c3a9f8a1906/src/hooks/useKeyValueMapping.ts#L43-L54

```
  const getEntityByValue = React.useCallback(
    (value: RawValueType, skipType: SkipType = 'select', ignoreDisabledCheck?: boolean) => {
      const dataNode = cacheValueMap.get(value);


      if (!ignoreDisabledCheck && isDisabled(dataNode, skipType)) {
        return null;
      }


      return dataNode;
    },
    [cacheValueMap],
  );
```

在`rc-tree`中对这类值可以通过设定`defaultCheckedKeys`来使得这些被禁用的keys绕过检测来维持勾选状态(https://github.com/react-component/tree/blob/d2da30c9ae832c20495fd59c02374cd36449c77a/src/Tree.tsx#L377-L399)。

目前我想到的是添加一个`defaultCheckedValues`？
或者将`rc-tree-select`第一次接收到的values转换成keys，传入`rc-tree`的`defaultCheckedKeys`？

理解不对的地方欢迎指正！
