### ISSUE TITLE
Mega Menu

### ISSUE THREAD

**Issue by chesterheng** [ant-design/ant-design#31667]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
How to create mega menu with ant design Menu or SubMenu

### What does the proposed API look like?
Is it possible to style SubMenu with display flex mode to make a mega menu? I tried but it cannot work.

**Comment by afc163** [comment]
Sorry, we don't support mega menu right now.
