### ISSUE TITLE
Higher Active Tabs.Pane to increase UI/UX

### ISSUE THREAD

**Issue by simo54** [ant-design/ant-design#31664]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature resolve a visual issue with the active tab selected.

Mostly, I am talking about the card tabs https://ant.design/components/tabs/#components-tabs-demo-card. Is it very convenient for user to check quickly which tab is open and which not, this will generally resolve some visual issues. 

### What does the proposed API look like?
Creating a new API within the TabPane with the following name:
**heightActive**
and assign a number where it is considered as px. The input will create a top margin of the TabPane and when a tab is activated it will stretch on top taking the space declared.

Talking about the code this will become: `<TabPane tab={TEXT} key="1" heightActive={5}>`

**Comment by afc163** [comment]
You can customize style to get it.
