### ISSUE TITLE
Requesting new icons

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#31665]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I don't know if this is the right place to ask, and I'm sorry in advance.
I'm using only the Icons available on Antd, and I really wish there was a 'truck' icon, for representing my Logistics Menu-Item, but i don't now where to request new icons to be added to the package, and I also don't know if that's a thing. I dont want to use "custom icons" because they may differ from the Antd design Icon pattern, and may have mixed visuals. 

### What does the proposed API look like?
A place where we could suggest new icons to be added to the package?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/issues/71
