### ISSUE TITLE
Upload上传组件，官网用户头像示例，第一次上传时一直处于loading状态

### ISSUE THREAD

**Issue by paddingC** [ant-design/ant-design#31678]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/03x7w)

### Steps to reproduce
第一次进入页面，点击上传，info.file.status一直处于uploading状态

### What is expected?
onChange回调可以正常执行

### What is actually happening?
onChange阻塞，info.file.status一直是uploading

| Environment | Info |
|---|---|
| antd | 4.8.2 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
无法重现。

<img width="1127" alt="图片" src="https://user-images.githubusercontent.com/507615/128329105-3f7855c4-595b-4afb-893d-1b87dfca1d99.png">

**Comment by paddingC** [comment]
> 无法重现。
> 
> <img alt="图片" width="1127" src="https://user-images.githubusercontent.com/507615/128329105-3f7855c4-595b-4afb-893d-1b87dfca1d99.png">

刚才试了一下，进入官网或者演示链接，刷新浏览器之后（或刷新几次）再点击上传就会出现这样的情况
![image](https://user-images.githubusercontent.com/28521120/128330678-0903128c-f17c-4c0c-a285-eda7e160c8c2.png)

**Comment by afc163** [comment]
是不是上传的图片太大了。

**Comment by afc163** [comment]
看一下控制台，检查一下 https://www.mocky.io/v2/5cc8019d300000980a055e76 这个请求是什么情况，另外打一下 `console.log(info.file.status)` 看看。

**Comment by paddingC** [comment]
> 看一下控制台，检查一下 https://www.mocky.io/v2/5cc8019d300000980a055e76 这个请求是什么情况，另外打一下 `console.log(info.file.status)` 看看。

![image](https://user-images.githubusercontent.com/28521120/128333855-ae4492a8-3053-4a4b-8b1f-8b748c0466b1.png)
刷新之后这个地址有时候回出现跨域，不知道是不是这个原因导致的。
