### ISSUE TITLE
AutoComplete组件options渲染存在问题

### ISSUE THREAD

**Issue by ONEGISER** [ant-design/ant-design#31672]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-autocomplete-l5nt3?file=/src/home.tsx)

### Steps to reproduce
输入框先输入a，删除，再输入b

### What is expected?
只显示当前options里的数据

### What is actually happening?
显示的结果还有前面的查询结果

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | react |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
value 重复了，请注意控制台的 React key 重复警告。

https://codesandbox.io/s/antd-autocomplete-forked-jcwe7?file=/src/home.tsx

**Comment by ONEGISER** [comment]
> value 重复了，请注意控制台的 React key 重复警告。
> 
> https://codesandbox.io/s/antd-autocomplete-forked-jcwe7?file=/src/home.tsx

thank  you!
