### ISSUE TITLE
Keyboard navigation for tree component

### ISSUE THREAD

**Issue by dgwyer** [ant-design/ant-design#31677]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to navigate the tree via keyboard controls (arrow keys), and also move items around (e.g. Alt Up to move an item up).

### What does the proposed API look like?
I'm not familiar with the API.

**Comment by afc163** [comment]
Use <kbd>Tab</kbd> to focus Tree component, then press <kbd>↓</kbd> and <kbd>↑</kbd>

**Comment by dgwyer** [comment]
None of the examples seem to work with this, hence why I opened the ticket. Is there a working example anywhere?

**Comment by afc163** [comment]
![Kapture 2021-08-05 at 17 36 27](https://user-images.githubusercontent.com/507615/128328469-7258b0dc-dace-4f81-8bfd-9b40e30f4f21.gif)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21684#issuecomment-592514568
