### ISSUE TITLE
Can't close DatePicker panel when click in DatePicker’s border

### ISSUE THREAD

**Issue by Kinco4TC** [ant-design/ant-design#31673]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#API](https://ant.design/components/date-picker-cn/#API)

### Steps to reproduce
1. click any DatePicker to open the panel
2. click the border/suffixIcon of the DatePicker you clicked before
3. then you find that the opened panel close and reopen instantly

### What is expected?
without any response as the click action in any opened DatePicker or close normally

### What is actually happening?
the opened panel close and reopen instantly

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | latest |
| System | MacOS |
| Browser | chrome 92.0.4515.107 |

---
Maybe it's blur action cause this bug as I found the onBlur api trigger when bug happened

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/30810

This issue still happens on border and suffixIcon area. @Akashdeep98

**Comment by g7i** [comment]
> #30810
> 
> This issue still happens on border and suffixIcon area. @Akashdeep98

@afc163 The fix was added only for `range pickers`. Have added for `picker` as well. Thanks
