### ISSUE TITLE
StrictMode 模式下 Tree 组件 loadData 会调用两次

### ISSUE THREAD

**Issue by MinJieLiu** [ant-design/ant-design#31683]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-16-10-forked-pu0m3?file=/index.js)

### Steps to reproduce
点击展开节点， 查看控制台

### What is expected?
输出一次

### What is actually happening?
输出两次

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 17 |
| System | mac |
| Browser | chrome |
![企业微信截图_1284e6e3-7c36-4d89-8515-553abf142c64](https://user-images.githubusercontent.com/6167727/128354374-2ce24abd-d45d-4eaa-90d7-937414837d35.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26136

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25504#issuecomment-655574850

**Comment by afc163** [comment]
https://github.com/facebook/react/issues/15074#issuecomment-471197572
