### ISSUE TITLE
Pagination组件，total为0时，current 不是1

### ISSUE THREAD

**Issue by erlei22** [ant-design/ant-design#31684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-16-10-forked-g74s1?file=/index.js)

### Steps to reproduce
链接可见

### What is expected?
Pagination组件，total为0时，current 为1

### What is actually happening?
Pagination组件，total为0时，current 为0，

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 16.8 |
| System | mac |
| Browser | Google Chrome 92.0.4515.131 |

**Comment by xrkffgg** [comment]
当前1页，第1页个数为 0

**Comment by afc163** [comment]
`total` 为 0 时是显示这样合适？

<img width="109" alt="图片" src="https://user-images.githubusercontent.com/507615/128452056-364e134e-16f2-48b8-a91f-7660f30448e9.png">

还是这样更合适？

<img width="145" alt="图片" src="https://user-images.githubusercontent.com/507615/128452308-92f420ad-325b-4323-8fc3-3e59fa3d234c.png">

**Comment by yoyo837** [comment]
个人观点支持下面这种.
