### ISSUE TITLE
AutoComplete onSelect Provides Wrong Option Item

### ISSUE THREAD

**Issue by jonioni** [ant-design/ant-design#31686]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate. Related:
  - #11909
  - #21882
  - #9297

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cu8sz?file=/index.js)

### Steps to reproduce

Options:
- Options of finite categories. 
- Option `value` are different within same category, but same `value` may appear in different categories.

Steps(CodeSandbox):
1. Select an item in **the first category**.
2. It can be seen that the item of **the second category** (which has the same `value`) is returned by `onSelect`.

### What is expected?
`onSelect` returns the selected item.

### What is actually happening?
The last item of the selected value is returned, not necessarily the selected item.

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 17.0.1 |
| System | macOS Big Sur 11.5.1  |
| Browser | Chrome 92.0.4515 |

---
There should be a better support for `value` and `categories`. Especially if we don't want to add category info to the `value` field as `value` is what's shown in the input box.

(The current solution is to add category info to make `value` unique. But upon selection this artificially generated `value` is shown in the box which is undesired. So we have to use a special string pattern to construct the `value` and process it again on selection).

If `labelInValue` is allowed then user may set `value` with unique identifier. But currently it's not possible.

Any suggestion?

**Comment by afc163** [comment]
I think we should stick to `value should be unique`, it is simple and magicless.

**Comment by little-brave-troops** [comment]
I think `key should be unique` , value can repeat

**Comment by mleister97** [comment]
Wow, that can be really frustrating...

**Comment by deleteme007-2cores** [comment]
我也被坑到了，如果后端传过来的值有重复的，就会出现非常奇怪的行为，排查了半天。 `value should be unique` 这种设计哲学是哪来的，有任何文章讨论过这种事情吗？

为什么不用自增的 key ，而是要把 value 这种不可控的东西当作 key ？

I also got burned by this issue. If the backend sends duplicate values, it leads to very strange behavior, and I spent half a day debugging it. Where does this design philosophy of ​​"value should be unique"​​ come from? Are there any articles discussing this?

Why not use an auto-incremented key instead of relying on value, which is unpredictable, as the key?
