### ISSUE TITLE
chrome下modal中datepicker选择日期后bug

### ISSUE THREAD

**Issue by xinxiongy** [ant-design/ant-design#3168]
#### 发生问题的环境是：

- antd 版本: 1.11.0
- 操作系统及其版本: win8
- 浏览器及其版本: chrome 54.0.2840.14

#### 您做了什么？
modal中引入datepicker

#### 实际上的结果是：
选择日期后，滑动右侧进度条，对话框只有下部会移动。

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/3031
