### ISSUE TITLE
Modal attaching to dom twice when nested in Menu

### ISSUE THREAD

**Issue by patrickomeara** [ant-design/ant-design#31687]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4k1bu)

### Steps to reproduce
* Nest a Modal within a Menu
* Show modal

### What is expected?
Previous to 4.16 this worked fine, the modal attached to the dom at document.body only once

Repro using 4.15

https://codesandbox.io/s/antd-reproduction-template-forked-3vpd7

### What is actually happening?
Since 4.16, the modal is attached twice to the DOM at document.body

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 17.0.2 |
| System | any |
| Browser | all |

---
We use this structure to keep a long list of filters together, most of which produce modals.

react-component/menu#419
react-component/menu#385

**Comment by zombieJ** [comment]
As document mentioned. `ul` only accept `li` as its children. You should wrap it in Menu.Item:
https://codesandbox.io/s/antd-reproduction-template-forked-rxqzu?file=/index.js

ref: https://ant.design/components/menu/#Notes-for-developers
