### ISSUE TITLE
react-warning-keys之TabPane中的key绑定疑惑？

### ISSUE THREAD

**Issue by sunxia628** [ant-design/ant-design#31689]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hua-dong-antd-4-16-10-forked-in19b?file=/index.js:1016-1019)

### Steps to reproduce
初始化渲染Warning: Each child in a list should have a unique "key" prop.

### What is expected?
期望和注释的两位两种写法一样，不报Warning: Each child in a list should have a unique "key" prop.

### What is actually happening?
Warning: Each child in a list should have a unique "key" prop.

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 16.14.0 |
| System | window7 |
| Browser | 版本 91.0.4472.106（正式版本） （64 位） |

截图预览：
![T9UWNMVSN{)`$ 82)96DRH](https://user-images.githubusercontent.com/26341016/128443956-58aa9287-b178-4cb5-8cd2-e315c77dedf3.png)

**Comment by afc163** [comment]
`key={item.key}` 对于最后一项相当于 `key={undefined}` 相当于没写 key。
key={`${item.key}`} 对于最后一项相当于 `key="undefined"`，这样算是声明了一个字符串 key。

**Comment by sunxia628** [comment]
@afc163 所以这个原因是什么呢？TabPane的props：key和关键字重复，这个需要怎么传值，而且我看官方的例子是 
 ```
<TabPane tab={`Tab-${i}`} key={i} disabled={i === 28}>
    Content of tab {i}
  </TabPane>
```
我调整了顺序：
```
<TabPane key={item.key} tab={`${item.tab}`}>
      {item.component}
</TabPane>
```
然而还是得到Warning: Each child in a list should have a unique "key" prop.
只有当key={`${item.key}`}时才能避免得到Warning，和是否为最后一个属性也并没有关系啊？
而且这个key应当是绑定成功了，编译代码如下：
`<div class="ant-tabs-nav-list" style="transform: translate(0px, 0px);"><div class="ant-tabs-tab ant-tabs-tab-active"><div role="tab" aria-selected="true" id="rc-tabs-0-tab-1" class="ant-tabs-tab-btn" aria-controls="rc-tabs-0-panel-1" tabindex="0">综合考核指数</div></div><div class="ant-tabs-tab"><div role="tab" aria-selected="false" id="rc-tabs-0-tab-2" class="ant-tabs-tab-btn" aria-controls="rc-tabs-0-panel-2" tabindex="0">法人信用认证</div></div><div class="ant-tabs-tab"><div role="tab" aria-selected="false" id="rc-tabs-0-tab-3" class="ant-tabs-tab-btn" aria-controls="rc-tabs-0-panel-3" tabindex="0">产品质量评价</div></div><div class="ant-tabs-tab"><div role="tab" aria-selected="false" id="rc-tabs-0-tab-4" class="ant-tabs-tab-btn" aria-controls="rc-tabs-0-panel-4" tabindex="0">履约动态考评</div></div><div class="ant-tabs-tab"><div role="tab" aria-selected="false" id="rc-tabs-0-tab-5" class="ant-tabs-tab-btn" aria-controls="rc-tabs-0-panel-5" tabindex="0">市场业绩表现</div></div><div class="ant-tabs-tab"><div role="tab" aria-selected="false" id="rc-tabs-0-tab-undefined" class="ant-tabs-tab-btn" aria-controls="rc-tabs-0-panel-undefined" tabindex="0">数据协同指数</div></div><div class="ant-tabs-ink-bar ant-tabs-ink-bar-animated" style="left: 0px; width: 84px;"></div></div>`

**Comment by afc163** [comment]
```
      tabs: [
        { tab: "综合考核指数", key: "1" },
        { tab: "法人信用认证", key: "2" },
        { tab: "产品质量评价", key: "3" },
        { tab: "履约动态考评", key: "4" },
        { tab: "市场业绩表现", key: "5" },
        { tab: "数据协同指数", code: "6" }
      ]
```

tab 6 里没 key。

**Comment by sunxia628** [comment]
嗯，手动改的漏了！
