### ISSUE TITLE
源码分析：新功能弹窗infoNewVersion方法根本不会执行。

### ISSUE THREAD

**Issue by itwanggj** [ant-design/ant-design#31685]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
ant-design代码仓库
代码路径：site/theme/template/Layout/Footer.tsx

### What is expected?
成功调用

### What is actually happening?
Date.now() < new Date('2017/12/20').getTime() === false

| Environment | Info |
|---|---|
| antd | undefined |
| React | React |
| System | MacOS |
| Browser | Chrome 最新版 |

**Comment by afc163** [comment]
对，大版本发布的时候专用的弹窗代码，目前没有用了。

可以来个 PR 删了。

**Comment by itwanggj** [comment]
您好，PR已提交，辛苦您帮忙Merge下。

https://github.com/ant-design/ant-design/pull/31699

**Comment by itwanggj** [comment]
您好，https://github.com/ant-design/ant-design/pull/31718，fix ci errors，辛苦再Check下代码。
