### ISSUE TITLE
onBlur and onFocus methods on Dropdowns and PopUp

### ISSUE THREAD

**Issue by lakshyabatman** [ant-design/ant-design#31697]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In scenarios where we require to manually handle visibility, there are some cases when we need to handle it via onBlur or onFocus but these attributes are not on these components and wrapping another component on it won't work as  expected.

### What does the proposed API look like?
`<Dropdown onBlur={handleVisibilty} onFocus={handleVisibilty} ><Content></Dropdown>`

**Comment by afc163** [comment]
`onVisibleChange` and `visible`

**Comment by lakshyabatman** [comment]
@afc163 onVisibileChange gets trigger when visibility changes, but I've been into cases where the user opens another drawer from a dropdown and this dropdown doesn't go away, for these cases what you can suggest.

**Comment by kbhutani0001** [comment]
@afc163 the problem occurs, when i have a popover opened (triggered through hover) and on top of that i open a drawer (from popover). When i close the drawer, the popover doesn't close automatically unless we hover back on it.

https://codesandbox.io/s/basic-antd-4-16-11-forked-1653d
