### ISSUE TITLE
Select Option Api 『Title』 not working.

### ISSUE THREAD

**Issue by RexHung0302** [ant-design/ant-design#31694]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#Option-props](https://ant.design/components/select-cn/#Option-props)

### Steps to reproduce
I use Select like:

```
<Select defaultValue="1" className="tw-w-full tw-text-center">
    <Select.Option value="1" title="Hello World">
         <span>Welcome</span>
    </Select.Option>
    <Select.Option value="2" title="banana">
         <span>Favorite Fruit</span>
    </Select.Option>
</Select>
```

but Title not work.

### What is expected?
I want to show title text when I selected the option.

### What is actually happening?
When I selected the option, not show title text, it show option text.

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome |

**Comment by RexHung0302** [comment]
Hello, I created a codesandbox. The link on here https://codesandbox.io/s/antd-reproduction-template-forked-sn2iu?file=/index.js, Thx.

**Comment by afc163** [comment]
See https://ant.design/components/select/#components-select-demo-option-label-prop

**Comment by RexHung0302** [comment]
@afc163 Thank for reply, but it only can use on <select mode="multiple"> ?
