### ISSUE TITLE
tree component support check single  in checkable mode. 

### ISSUE THREAD

**Issue by 963542298** [ant-design/ant-design#31690]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tree component support check single  in checkable mode. 

### What does the proposed API look like?
add a attribute like 'multiple' attribute

**Comment by afc163** [comment]
You can controll `checkedKeys`, make sure it's length <= 1.

**Comment by 963542298** [comment]
我知道可以使用checkedKeys，但是就行tree组件通过传一个属性，然后让tree去控制只能check一个，就像multiple可以控制select一样。
