### ISSUE TITLE
Pagination的参数showSizeChanger设置为true后，有回调函数吗？我希望重新刷新表格

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#317]
Pagination设置参数showSizeChanger为true后，则会出现一个下拉选框，选择每页展示条数，有
10条/页
20条/页
30条/页
40条/页
问题是：我从10条/页切换到20条/页后，分页自身重新渲染了，但是表格没有对应渲染？
比如原来表格展示10条，期望切换后表格重新刷新后展示20条。

我希望从10条/页切换到20条/页，有一个回调函数（比如叫onShowSizeChange），这样我可以在回调函数里获取到最新的pageSize为20，和pageNum，然后再拿这两个参数自己刷新表格。这样刷新后表格就是每页展示20条了。

but目前从10条/页切换到20条/页后，仅分页自身变化，而且没有回调函数，表格保持原样，致使无法使用该功能。
@afc163

**Comment by afc163** [comment]
确实是个问题，0.9.1 前要修复。

**Comment by afc163** [comment]
`onShowSizeChange`

**Comment by zccst** [comment]
@afc163 先谢谢，这个功能我非常需要。不过我还得等最新稳定版发布才能使用吧

**Comment by afc163** [comment]
可以先 `npm install antd@beta`。
