### ISSUE TITLE
文本框错误状态情况下，获取焦点时，内部出现红色的小框，是什么原因？

### ISSUE THREAD

**Issue by xzzor** [ant-design/ant-design#31705]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/xzzor/my/blob/main/a.png](https://github.com/xzzor/my/blob/main/a.png)

### Steps to reproduce
文本框错误状态情况下，获取焦点时，各浏览器都试过，都有这种情况：
![](https://github.com/xzzor/my/blob/main/a.png?raw=true)

### What is expected?
正常显示，不出现内部小红框。

### What is actually happening?
![](https://github.com/xzzor/my/blob/main/a.png?raw=true)

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 16 |
| System | macos |
| Browser | edge / chrome |

---
望各们大佬指点迷津，感谢！

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/31562
