### ISSUE TITLE
Modal RTL Problem

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#31715]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/internationalization-antd-4-16-10-forked-vhjx3?file=/index.js)

### Steps to reproduce
*

### What is expected?
modal.confirm most RTL support

### What is actually happening?
*

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Chrome 90 |

**Comment by afc163** [comment]
See https://ant.design/components/modal/#Why-I-can-not-access-context,-redux,-ConfigProvider-locale/prefixCls-in-Modal.xxx

**Comment by hmz22** [comment]
I change like link and use useModal but form still is LTR and no RTL.
you can see this link?

[https://codesandbox.io/s/internationalization-antd-4-16-10-forked-vhjx3?file=/index.js](url)
