### ISSUE TITLE
官网/文档平台 uploader demo无法正常演示

### ISSUE THREAD

**Issue by johnnychen** [ant-design/ant-design#3171]
页面：http://ant.design/components/upload/

原因：http://ant.design/upload.do 接口挂了

**Comment by benjycui** [comment]
用的是 GitHub Pages，没有服务端功能的，所以那个 demo 只是测试和展示一下代码而已。

**Comment by johnnychen** [comment]
http://ant.design/upload.do 服务端的实现方式、返回的数据接口没有找到。

另外，upload只支持异步提交是吗？

**Comment by afc163** [comment]
参照这个即可：https://github.com/blueimp/jQuery-File-Upload/wiki

@benjycui 可以补充到文档里。
