### ISSUE TITLE
阿里破冰是真的吗？

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design#31716]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了提出问题的人。

### What does the proposed API look like?
我期望它正义。

你们阿里真如新闻所说如此不堪吗？
你们的破冰如何无耻吗？
你们上午刚否认，下午6000人就承认了，这是怎么回事？
亏我还star了你们，我眼瞎啊！

**Comment by GG4mida** [comment]
犹记得当年百阿过后的饭局...

**Comment by yoyo837** [comment]
该事件与此项目无关, 社交媒体应该比github能更好更有效提供给大家表达看法.
