### ISSUE TITLE
Popover placement改变时组件表现没有变化

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design#31717]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想用Popover组件做新手引导，修改相关属性后，虽然位置和内容发生了变化，placement的表现没有变化。

### What does the proposed API look like?
placement可以动态修改组件的位置表现形式

**Comment by semdy** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-yj9n3?file=/index.js

**Comment by semdy** [comment]
请问下这个bug何时可以更新至ant-design。

**Comment by semdy** [comment]
是最新版，检测过了，而且缓存也清理了。
![微信截图_20210811153619](https://user-images.githubusercontent.com/9401913/128988904-a8a01c8c-021b-47c8-9ad0-6ac4483416c3.png)

**Comment by afc163** [comment]
来个可重现的 github repo 看看？

**Comment by afc163** [comment]
最终包括三个改动，重装 node_modules 即可。

- rc-align@4.0.11
  - [x] https://github.com/react-component/align/pull/133
  - [x] https://github.com/react-component/align/commit/70a87ee43ecaf38d5c6198f654a0c54804347d84
- rc-trigger@5.2.10
  - [x] https://github.com/react-component/trigger/pull/279

**Comment by semdy** [comment]
我在项目里分别装了rc-align、rc-trigger最新版，但是依然有bug，但是demo是好的，不知道为什么。demo里的各依赖版本跟我项目里一模一样。
demo地址：https://codesandbox.io/s/antd-reproduction-template-forked-yj9n3?file=/package.json

**Comment by semdy** [comment]
把rc-align和rc-trigger复制到项目里，然后通过webpack alias指向本地是好的
