### ISSUE TITLE
Can the head of the component Transfer be hidden

### ISSUE THREAD

**Issue by dcycurry** [ant-design/ant-design#31728]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In the case of asynchronous loading of data, the select all function is abnormal

https://codesandbox.io/s/objective-wing-6iqbx?file=/index.js
![image](https://user-images.githubusercontent.com/45750720/128683601-05343c9a-6898-4f56-8278-d694e1a42bb1.png)

### What does the proposed API look like?
Add an attribute, customize the header

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by dcycurry** [comment]
> What does the proposed API look like?

I don’t need the "select all" attribute.
But when I set "showSelectAll=false", the drop-down box can still select all.
I hope to add an attribute，like 'header', so that I can hide or customize the header.

**Comment by afc163** [comment]
Check https://github.com/ant-design/ant-design/pull/31746
