### ISSUE TITLE
Select扩展内容中Button组件点击不能关闭下拉

### ISSUE THREAD

**Issue by islikai** [ant-design/ant-design#31729]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-16-11-forked-53or4?file=/index.js)

### Steps to reproduce
选择Select扩展内容中Button组件点击后不能关闭下拉

### What is expected?
点击Button组件关闭下拉

### What is actually happening?
点击Button组件不能关闭下拉

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | mac |
| Browser |  90.0.4430.212 |

**Comment by afc163** [comment]
Please control `open` property.
