### ISSUE TITLE
add colon for layout="vertical" in Form

### ISSUE THREAD

**Issue by GuanJianSayWeee** [ant-design/ant-design#31723]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want show colon when layout="vertical", why not leave the decision to users.
Of course,  I can add   ":" in label, but default required message in rules will show ":" too

### What does the proposed API look like?
colon = {true} is useful when layout="vertical"

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18719#issuecomment-528887957
