### ISSUE TITLE
Input，TextArea文本输入框maxLength支持字节计数和限制输入

### ISSUE THREAD

**Issue by luchaoqun125** [ant-design/ant-design#31725]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、输入框可以支持汉字，字母，数字，特殊符号等
2、不区分全角半角功能；字母，数字，特殊符号是1个字符，汉字2个字符
3、超过最大长度时，限制输入
4、其他类型，按照实际字符长度计算即可
例如：需求为：限制输入10个字符，5个汉字

### What does the proposed API look like?
在Input， TextArea上添加属性支持

**Comment by afc163** [comment]
https://ant.design/components/input-cn/#components-input-demo-textarea-show-count

>  4、其他类型，按照实际字符长度计算即可。例如：需求为：限制输入10个字符，5个汉字

这类需求很难形成统一标准，建议自行封装。
