### ISSUE TITLE
Modal RTL Form Problem 

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#31727]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/internationalization-antd-4-16-10-forked-vhjx3?file=/index.js)

### Steps to reproduce
*

### What is expected?
Form content of modal most RTL 

### What is actually happening?
*

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Chrome 90 |

---
I asked before this problem:
[https://github.com/ant-design/ant-design/issues/31715](https://github.com/ant-design/ant-design/issues/31715)

and send me a link and I try say in link and work but Form content in modal RTL not work

**Comment by xrkffgg** [comment]
Can you take a screenshot to identify it?

**Comment by hmz22** [comment]
this is confirm Modal with hook modal:
![Screenshot 2021-08-17 181553](https://user-images.githubusercontent.com/36853974/129737308-17fcf192-c659-415b-b407-cd092f91c187.png)

this is regular modal:
![Screenshot 2021-08-17 181618](https://user-images.githubusercontent.com/36853974/129737375-e73dab7c-e45d-4d79-a371-ae063c4e89e4.png)

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/129747943-66ac44b3-f960-4e36-92d2-6e3279ef85bd.png)

Is this right?

**Comment by xrkffgg** [comment]
Try

![image](https://user-images.githubusercontent.com/29775873/129749314-4f8ba3fc-a9a3-4f3a-9df5-c4a75f822533.png)

**Comment by hmz22** [comment]
You can see the Link of first post.
I try this but not work

**Comment by hmz22** [comment]
you mean add ConfigProvider in content?

**Comment by xrkffgg** [comment]
> you mean add ConfigProvider in content?

yes

**Comment by hmz22** [comment]
it's worked.
but can't fix this because I add ConfigProvider in index.js?

**Comment by xrkffgg** [comment]
I'll fix it.

**Comment by hmz22** [comment]
thx.
when release?

**Comment by xrkffgg** [comment]
This week

**Comment by hmz22** [comment]
I Check last post and check antd 4.16.12 but form still problem rtl.

**Comment by xrkffgg** [comment]
waiting release

**Comment by hmz22** [comment]
thx🙏
