### ISSUE TITLE
DatePicker的API--panelRender中，使用Input(InputNumber)组件无法点击获取焦点

### ISSUE THREAD

**Issue by Dalegac** [ant-design/ant-design#31734]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8jod0?file=/src/App.js)

### Steps to reproduce
1. Open the panel of DatePicker（open={true}）
2. Click Input or InputNumber
3. Can't get focus，except clicking keyboard【Tab】

### What is expected?
Click Input or InputNumber，then get focus

### What is actually happening?
Can't get focus or enter

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | ^16.14.0 |
| System | window 10 |
| Browser | Chrome 版本 91.0.4472.124（正式版本） （64 位） |

**Comment by afc163** [comment]
https://codesandbox.io/s/confident-shape-y6u5t?file=/src/App.js
