### ISSUE TITLE
表格内置分页样式无效

### ISSUE THREAD

**Issue by liushuhui** [ant-design/ant-design#31737]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/liushuhui/react-admin.git](https://github.com/liushuhui/react-admin.git)

### Steps to reproduce
引入table表格，内置的分页样式无效

### What is expected?
表格内置的样式正常

### What is actually happening?
样式无效

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | hooks |
| System | win10 |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/26155477/128802589-dfbad79d-9a98-4b01-a91a-5bc57a5e2ec0.png)
![image](https://user-images.githubusercontent.com/26155477/128802678-bc78b05a-c861-416a-bec4-72b7dae9542b.png)

**Comment by liushuhui** [comment]
![image](https://user-images.githubusercontent.com/26155477/128802556-fe67db2f-9f8b-44d8-9e3d-85734955b57e.png)

**Comment by afc163** [comment]
https://github.com/liushuhui/react-admin/pull/1

**Comment by liushuhui** [comment]
> [liushuhui/react-admin#1](https://github.com/liushuhui/react-admin/pull/1)

为啥这样就可以了

**Comment by liushuhui** [comment]
> [liushuhui/react-admin#1](https://github.com/liushuhui/react-admin/pull/1)

@afc163 为啥这样就可以了

**Comment by afc163** [comment]
`import 'antd/es/table/style';` 应该的正确模块是 `import 'antd/es/table/style/index.js';`。加了 .less 后变成了 `import 'antd/es/table/style/index.less';`，丢了全局样式和样式依赖。

**Comment by liushuhui** [comment]
> `import 'antd/es/table/style';` 对应的正确模块完整路径是 `import 'antd/es/table/style/index.js';`。
> 
> 加了 .less 后变成了 `import 'antd/es/table/style/index.less';`，丢了全局样式和样式依赖。



> `import 'antd/es/table/style';` 对应的正确模块完整路径是 `import 'antd/es/table/style/index.js';`。
> 
> 加了 .less 后变成了 `import 'antd/es/table/style/index.less';`，丢了全局样式和样式依赖。

**Comment by liushuhui** [comment]
@afc163 谢谢解惑

**Comment by zjjjjjjjjjjd** [comment]
请问antd是如何利用esmodule让依赖找到这个路径的 antd/es/table/style
