### ISSUE TITLE
tab里面的内容滚动，tab仍然被撑开

### ISSUE THREAD

**Issue by SmoothJM** [ant-design/ant-design#31731]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ij2h2?file=/index.js)

### Steps to reproduce
直接可以看到

### What is expected?
希望tab的高度能够随着内容变化而变化

### What is actually happening?
tab内容限制高度并设置滚动，但是tab仍然被撑开

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | react: 17.0.0 |
| System | Win10 |
| Browser | Chrome 92 |

**Comment by afc163** [comment]
最好用绝对高度，内嵌结构比较深，40% 并不能保证合适的高度。

https://codesandbox.io/s/antd-reproduction-template-forked-03gzg?file=/index.js
