### ISSUE TITLE
Set className or inline styles to override Image component className.

### ISSUE THREAD

**Issue by josh231101** [ant-design/ant-design#31736]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shy-haze-pkt6e?file=/src/index.js&resolutionWidth=320&resolutionHeight=675)

### Steps to reproduce
Just try to add a className or inline style inside an Image component. I wanted to use width to be auto but it just not works.

### What is expected?
To apply specific style to component

### What is actually happening?
Is forcing the class 

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Linux Pop Os |
| Browser | Chrome |

**Comment by afc163** [comment]
Please upgrade to antd@4.16.11

https://codesandbox.io/s/restless-silence-lx4ie?file=/src/index.js
