### ISSUE TITLE
怎么自定义表单验证中的 type

### ISSUE THREAD

**Issue by koen301** [ant-design/ant-design#3173]
#### 发生问题的环境是：

- antd 版本:1.11.1
- 操作系统及其版本:win10
- 浏览器及其版本:chrome50

#### 您期待的结果是：

Ant Form 组件中的表单验证，即 rules 中的 type 可不可以自定义？怎么自定义？
例如项目中常见的中文/英文，希望自定一个type='cn'/'en'分别表示它们

**Comment by benjycui** [comment]
http://ant.design/components/form/#components-form-demo-validate-customized

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by koen301** [comment]
@benjycui 回答不在点子上啊，我想要的是自定义 rules 中的 type 字段，不是问你自定义验证怎么实现

**Comment by benjycui** [comment]
不支持，但是自定义校验可以满足需求。

**Comment by yesmeck** [comment]
@benjycui http://ant.design/components/form/#components-form-demo-validate-customized 这个例子没有了？

**Comment by afc163** [comment]
感觉应该支持一下，业务开发中会有需求定义一些全局自定义规则，也方便不同页面的复用。

**Comment by afc163** [comment]
感觉应该支持一下，业务开发中会有需求定义一些全局自定义规则，也方便不同页面的复用。

**Comment by benjycui** [comment]
Update: https://ant.design/components/form/#components-form-demo-register

Password uses customized validation rule.

**Comment by afc163** [comment]
是否能支持自定义校验 type，这样在业务线可以梳理自己的规则集，方便复用。

**Comment by benjycui** [comment]
> 是否能支持自定义校验 type，这样在业务线可以梳理自己的规则集，方便复用。

和自定义一堆校验函数没区别吧。。

**Comment by afc163** [comment]
用起来统一和方便一点。

**Comment by afc163** [comment]
诉求是这样的，开发者在使用的时候，对预设的 rules 会有很强的依赖，能找到合适的就不会自己去写 validator。现在的 [rules](https://github.com/yiminghe/async-validator/tree/master/src/rule) 类型有点少，如果能全局配置，也可以激发一些`第三方规则库/业务规则库`的产生。
