### ISSUE TITLE
Select .blur() event on touch devices

### ISSUE THREAD

**Issue by PaulPCIO** [ant-design/ant-design#31744]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/multiple-selection-antd-4-16-11-forked-bp57k?file=/index.js)

### Steps to reproduce
On google chrome, open dev tools and view the page as a touch device.

If you try to use the `.blur()` on a select it will not blur, unless you add a timeout on the blur event.

### What is expected?
It should blur without the need for a timeout
> `ref.current.blur()`  should also blur the select component on a touch device

### What is actually happening?
It is not blurring the select component on touch devices
> `setTimeout(() => ref.current.blur(), 10)` you need a timeout to blur on a touch device

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.2 |
| System | WIndows |
| Browser | Chrome |

**Comment by afc163** [comment]
See https://codesandbox.io/s/multiple-selection-antd-4-16-11-forked-9bywf?file=/index.js 

`.blur()` is not a reliable way to hide select dropdown.
