### ISSUE TITLE
DatePicker component day names are not localized

### ISSUE THREAD

**Issue by gugol2** [ant-design/ant-design#31748]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/locale-antd-4-16-11-forked-days-short-non-translated-r6wn6?file=/index.js)

### Steps to reproduce
Just change the locale and see that the words "Month" and "Year" are translated but not the abbreviations for the day of the week, it keeps saying:

"Su Mo Tu We Th Fr Sa" 

When it should translate them to German and say instead:

"Mo. Di. Mi. Do. Fr. Sa. So."

Right?

### What is expected?
Abbreviation names for the week days as:

Mo. Di. Mi. Do. Fr. Sa. So.

### What is actually happening?
It is not translating the week day short names to German, it keeps them in English:

Su Mo Tu We Th Fr Sa

| Environment | Info |
|---|---|
| antd | 4.15.6 |
| React | React "17.0.2" with Create React App |
| System | Ubuntu 20.04.2 LTS |
| Browser | Chrome Version 92.0.4515.131 (Official Build) (64-bit) |

---
I saw in the demo with other languages that the weekdays short name was changed:

https://codesandbox.io/s/locale-antd-4-16-11-forked-2go6t?file=/index.js:3371-3375

**Comment by afc163** [comment]
https://codesandbox.io/s/locale-antd-4-16-11-forked-days-short-non-translated-2moj1?file=/index.js

```diff
+ import "moment/locale/de";
```

**Comment by gugol2** [comment]
Ok... so not all translations are picked from antd/lib/locale
Thanks!!
