### ISSUE TITLE
Can the required mark position be configurable

### ISSUE THREAD

**Issue by jswale** [ant-design/ant-design#31743]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The required mark is always before the label.

The idea is to allow the users to choose between displaying the required mark before or after the label.

### What does the proposed API look like?
Inside [components/form/style/index.less](https://github.com/ant-design/ant-design/blob/c671b4e3f16ec9d264e7ff1a37cafc401235edc5/components/form/style/index.less#L105) the following rule is defined to be *before*:
`&.@{form-item-prefix-cls}-required:not(.@{form-item-prefix-cls}-required-mark-optional)::before {`

By adding a variable it could be possible to change the *before* to *after*

**ie.**
`&.@{form-item-prefix-cls}-required:not(.@{form-item-prefix-cls}-required-mark-optional)::@{form-item-required-mark-position} {`

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-16-11-forked-kvee3?file=/index.css

**Comment by jswale** [comment]
I've already found by my self this workaround, but having a variable to configure that would be nicer than overriding the style. Avoiding issues if ant design change the style or naming, etc...

**Comment by Tuhama** [comment]
![image](https://user-images.githubusercontent.com/7550042/150780762-84bd0222-46e2-481c-abc9-860be30a87d9.png)
It would be nicer when the label alignment is to the left (doesn't break text alignment)
