### ISSUE TITLE
请教 API 文档

### ISSUE THREAD

**Issue by chaishi** [ant-design/ant-design#31747]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/blob/master/components/table/index.zh-CN.md
想请问下这个里面的 API 文档是人工维护的吗？

### What does the proposed API look like?
只是想了解下，没有特别期望

**Comment by xrkffgg** [comment]
是的
