### ISSUE TITLE
Tree dropdown allows only upto 6 levels - Please check the screenshot attached.

### ISSUE THREAD

**Issue by ranopriyo-neogy** [ant-design/ant-design#31749]
[-](url) [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-fvsyes](https://stackblitz.com/edit/react-fvsyes)

### Steps to reproduce
https://stackblitz.com/edit/react-fvsyes
You will see only 6 elements in TreeNode are displayed instead of 9.

Code:

import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { TreeSelect } from 'antd';

const { TreeNode } = TreeSelect;

const Demo = () => {
  const [value, setValue] = useState(undefined);
  const onChange = () => {
    setValue(value);
  };
  return (
    <TreeSelect
      showSearch
      style={{ width: '100%' }}
      value={value}
      dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
      placeholder="Please select"
      allowClear
      treeDefaultExpandAll
      onChange={onChange}
    >
     <TreeNode value="rmx" title="rmx (Production Org)">
        <TreeNode value="ou-e3dj" title="(Primary Root OU)">
           <TreeNode value="ou-nk8" title="(Contentserv)" /> 
           <TreeNode value="ou--pt0" title="(Enterworks)" /> 
           <TreeNode value="ou-rxl4" title="(EPCC)" /> 
           <TreeNode value="ou-b3xs" title="(GMS)" /> 
           <TreeNode value="ou-mmqb" title="(Internal-use)" /> 
           <TreeNode value="ou-ax2fi" title="(Oracle-Commerce)" /> 
           <TreeNode value="ou-4zd" title="(Stibo)" /> 
           <TreeNode value="ou-0j9" title="(Intershop)" /> 
           <TreeNode value="ou-bc4e" title="(Magento)" /> 
         </TreeNode>
      </TreeNode>
    </TreeSelect>
  );
};

ReactDOM.render(<Demo />, document.getElementById('container'));

### What is expected?
Expecting 9 Dropdowns in Tree as mentioned in the below code.

import React, { useState } from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { TreeSelect } from 'antd';

const { TreeNode } = TreeSelect;

const Demo = () => {
  const [value, setValue] = useState(undefined);
  const onChange = () => {
    setValue(value);
  };
  return (
    <TreeSelect
      showSearch
      style={{ width: '100%' }}
      value={value}
      dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
      placeholder="Please select"
      allowClear
      treeDefaultExpandAll
      onChange={onChange}
    >
     <TreeNode value="rmx" title="rmx (Production Org)">
        <TreeNode value="ou-e3dj" title="(Primary Root OU)">
           <TreeNode value="ou-nk8" title="(Contentserv)" /> 
           <TreeNode value="ou--pt0" title="(Enterworks)" /> 
           <TreeNode value="ou-rxl4" title="(EPCC)" /> 
           <TreeNode value="ou-b3xs" title="(GMS)" /> 
           <TreeNode value="ou-mmqb" title="(Internal-use)" /> 
           <TreeNode value="ou-ax2fi" title="(Oracle-Commerce)" /> 
           <TreeNode value="ou-4zd" title="(Stibo)" /> 
           <TreeNode value="ou-0j9" title="(Intershop)" /> 
           <TreeNode value="ou-bc4e" title="(Magento)" /> 
         </TreeNode>
      </TreeNode>
    </TreeSelect>
  );
};

ReactDOM.render(<Demo />, document.getElementById('container'));

Screenshot of Issue: ( TreeNode dropdown should have 9 levels as mentioned in code - however just have 6 ) 

![Screen Shot 2021-08-10 at 1 45 58 PM](https://user-images.githubusercontent.com/68603179/128911682-ce59cdf8-86ff-438c-a5bd-b6377904c4bf.png)

### What is actually happening?
Getting only 6 Options till Oracle-Commerce 

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 17.0.2 |
| System | MacOS BigSure 11.5 |
| Browser | Chrome , Safari |

---
Please fix this issue. I am trying to implement this feature but running into this issue.

**Comment by afc163** [comment]
<img width="449" alt="图片" src="https://user-images.githubusercontent.com/507615/128961648-4bc88713-86d0-4a90-922a-3cfae591655f.png">

You could scroll down to see full list.
