### ISSUE TITLE
Input props has suffix and allow Clear simultaneously, clear icon or suffix  space will be missing

### ISSUE THREAD

**Issue by cwjTerrace** [ant-design/ant-design#31741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-butterfly-pzhv7?file=/index.js)

### Steps to reproduce
```
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Input, Icon } from "antd";

ReactDOM.render(
  <div>
    <Input
      defaultValue="jack ma"
      placeholder="Enter your username"
      allowClear
      prefix={<Icon type="user" style={{ color: "rgba(0,0,0,.25)" }} />}
      suffix={<Icon type="info-circle" style={{ color: "rgba(0,0,0,.45)" }} />}
    />

    <br />
    <br />

    <Input defaultValue="200" prefix="￥" allowClear suffix="RMB" />
  </div>,
  document.getElementById("container")
);
```
![image](https://user-images.githubusercontent.com/29698222/128818614-4b9fc8f7-4bf4-49c4-bb89-3df76e1ad74f.png)

### What is actually happening?
clear icon or suffix  space is missing

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 16.8.0 |
| System | MacOS Big Sur |
| Browser | Microsoft Edge 92.0.902.67 |

**Comment by afc163** [comment]
antd 4.16.11 reproduce: https://codesandbox.io/s/quirky-swanson-ndop6?file=/index.js
