### ISSUE TITLE
火狐浏览器版本53.x版本中antd4.x版本中Table表格不显示出现报错

### ISSUE THREAD

**Issue by huifeidekaola** [ant-design/ant-design#31740]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/44389022/128815176-060404a3-1816-498d-9355-deb009eebd7b.png](https://user-images.githubusercontent.com/44389022/128815176-060404a3-1816-498d-9355-deb009eebd7b.png)

### Steps to reproduce
ant design4.x版本在低版本火狐浏览器 火狐浏览器版本53.x版本中Table表格不显示出现报错，
(https://user-images.githubusercontent.com/44389022/128815176-060404a3-1816-498d-9355-deb009eebd7b.png)
不知道该怎么解决。
并且在低版本火狐浏览器中打开antd官网4.x版本中表格Table同样报错。

### What is expected?
求解决方案

### What is actually happening?
求解决方案

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | 52.9 |
| Browser | 火狐 |

**Comment by afc163** [comment]
这个版本太老了，不支持了。
