### ISSUE TITLE
input 组件设置为无边框时在表单校验失败后样式问题

### ISSUE THREAD

**Issue by lwQin** [ant-design/ant-design#31752]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pro-form-validate-style-errorantd-latest-f6d49)

### Steps to reproduce
这个 https://github.com/ant-design/ant-design/issues/31558 好像没修复

### What is expected?
 
<img width="503" alt="Xnip2021-08-11_09-39-18" src="https://user-images.githubusercontent.com/11586662/128956862-440f036d-2635-479e-a818-2c19bf1413e0.png">

### What is actually happening?
 

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.2 |
| System | macOS 11.4 |
| Browser | chrome 92 |

**Comment by afc163** [comment]
确实。
