### ISSUE TITLE
Select 组件设置下拉框对齐方式

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#31753]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当设置 dropdownStyle 的宽度大于 select 的宽度，并且 Select 组件在页面的右侧边栏时，下拉框有一部分被屏幕遮挡，这种情况下左对齐就能完全展示。希望能够添加一个 api 可以设置下拉框对齐的方式。

https://stackblitz.com/edit/react-9kt762?file=index.js

### What does the proposed API look like?
placement="left"|"right"

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6624#issuecomment-374851334

**Comment by afc163** [comment]
感觉应该支持一下。

**Comment by afc163** [comment]
- [ ] Select
- [ ] TreeSelect
- [ ] Cascader

**Comment by ONLY-yours** [comment]
https://select-react-component.vercel.app/demo/single

**Comment by ONLY-yours** [comment]
https://select-react-component.vercel.app/demo/single

原生的rc-select里面有个direction有这个属性，可以做到左右对齐的效果。

![image](https://user-images.githubusercontent.com/52664827/147629738-565d7690-bf0f-4f18-ab48-c0b1980c1a22.png)

**Comment by afc163** [comment]
这个属性是用来做 RTL 的，不适合这个场景。
