### ISSUE TITLE
Cascader 和 Mentions 使用键盘上下选择时，滚动条无法滚动

### ISSUE THREAD

**Issue by Cecilxx** [ant-design/ant-design#31756]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Cascader数据过多时，使用键盘上下选择时，滚动条不会自动滚动

### What does the proposed API look like?
Cascader数据过多时，使用键盘上下选择时，滚动条可以自动滚动到所选项位置

 [调试代码链接](https://codesandbox.io/s/ji-ben-antd-4-16-11-forked-3ud76?file=/index.js)

**Comment by wangshaozhi** [comment]
我也碰到了这个问题，不过我碰到的是Mentions组件 也是使用键盘上下选择时，滚动条不会自动滚动，但是我查看了3.x版本是可以跟随滚动的

**Comment by iitodo** [comment]
This feature is removed from the issue, [\[Menu\] 建议提供关闭 scrollIntoView 功能的 prop](https://github.com/ant-design/ant-design/issues/23936).

**Comment by afc163** [comment]
- [ ] Mentions: https://github.com/ant-design/ant-design/issues/31836

**Comment by ygxw** [comment]
这个bug依旧存在，不知道官方有没有要解决？如果不打算解决，或者解决时间太旧，也请给个准信。谢谢。

**Comment by afc163** [comment]
@ygxw 有时间来帮忙 PR 一个不？

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/41651
