### ISSUE TITLE
官方网站无法访问

### ISSUE THREAD

**Issue by mengkeys** [ant-design/ant-design#3175]

**Comment by afc163** [comment]
现在再试试？

**Comment by JrIdeA** [comment]
现在依然无法访问

**Comment by benjycui** [comment]
@JrIdeA 网络环境？我在不翻墙的前提下，用手机也可以正常访问。

**Comment by JrIdeA** [comment]
@benjycui 试了下翻墙后404了，不翻可以访问

**Comment by afc163** [comment]
@JrIdeA  我遇到同样的问题。

@fengmk2

**Comment by fengmk2** [comment]
是阿里内网的 vpn 翻墙的？如果是，就是还是那个问题，内网的翻墙服务器 dns cache 还没清除，还是走了原来 github page 的 ip。

**Comment by zaxlct** [comment]
官网 404 ，怎么回事啊

**Comment by zaxlct** [comment]
![](http://ww4.sinaimg.cn/large/006y8lVagw1f89dwfqpkdj30yu0jmjt0.jpg)

**Comment by afc163** [comment]
dns 没有刷新的问题。可以暂时绑定本地 hosts

```
47.88.240.14 ant.design
```

**Comment by burning0xb** [comment]
是啊 打不开了现在 加拿大的网络也不行

**Comment by afc163** [comment]
trace #7895

**Comment by burning0xb** [comment]
I can open it tks

**Comment by perany** [comment]
https://ng.ant.design/无法访问
