### ISSUE TITLE
table组件固定列fixed字段问题

### ISSUE THREAD

**Issue by sarufarr** [ant-design/ant-design#31757]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sui-ye-mian-gun-dong-de-gu-ding-biao-tou-he-gun-dong-tiao-antd-4-16-11-forked-ewdvq)

### Steps to reproduce
在 ts 环境中
使用 columns 中的 fixed 字段如果填写 ‘left’/‘right’ 会提示类型定义出错`Types of property 'fixed' are incompatible.Type 'string' is not assignable to type 'FixedType'`
将 fixed 依据类型定义改成 boolean 值后表格绘制出错

### What is expected?
fixed 可以接收 boolean | ‘left’ | ‘right’
fixed 接收 boolean 时绘制正确

### What is actually happening?
fixed 只接收 boolean
fixed 接收 boolean 时绘制出错

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 18.0.0-alpha-ed6c091fe-20210701 |
| System | macOS Big Sur 11.5.1 |
| Browser | 92.0.4515.131（正式版本） (x86_64) |

**Comment by afc163** [comment]
```diff
-   fixed: 'left',
+   fixed: 'left' as const,
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7965#issuecomment-453914697
