### ISSUE TITLE
Upload组件onChange为什么只调用一次？

### ISSUE THREAD

**Issue by xueqingxiao** [ant-design/ant-design#3176]
按照文档去理解的话，文件上传中，失败， 成功都会调用一次onChange。
但是在[demo](http://codepen.io/xueqingxiao/pen/dpWgLp)中却只调用了一次。

**Comment by afc163** [comment]
有问题，先搜索。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2423
