### ISSUE TITLE
请教下ant-design对于前台系统是否适合？

### ISSUE THREAD

**Issue by ihaolin** [ant-design/ant-design#3177]
你好 ，想请教下一个问题：

像对于**ant-design**这类基于react的库，发现打包压缩后的文件似乎都比较大(大于>1M)，这种情况若放在前台系统(用户端)，是否会有高并发请求时的性能问题呢？或者**ant-design**有用于一些前台应用吗？

谢谢。

**Comment by benjycui** [comment]
目前没有刻意优化。

* 已经有前台系统在使用了 https://github.com/ant-design/ant-design/issues/477#issuecomment-249460016
* 可以用 babel-plugin-import 减小打包后的体积。

**Comment by ubibi** [comment]
你听说过有个东西叫做缓存吗？静态资源。。又不像以前那种php生成的大页面，每次都去服务器下载。

**Comment by ihaolin** [comment]
1m一个文件，10w并发，缓存又能怎样，你觉得带宽就妥妥的了？

**Comment by flyinghail** [comment]
@ihaolin #2656 正好刚刚回复，可以参考 :)
