### ISSUE TITLE
Anchor不能定位跳转

### ISSUE THREAD

**Issue by sisterGG** [ant-design/ant-design#31775]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://ng.ant.design/components/anchor/zh#ng-content
### Steps to reproduce
点击通讯录，然后点击右侧的锚点当导航栏无效

### What is expected?
能够跳转当前页面的对应的位置

### What is actually happening?
没有反应，绑定点击事件点击后也没有反应。但是有时候会变色，但是没有任何跳转。

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 3.0.0 |
| System | win10 |
| Browser | chrome 67.0.3396.99 |

---
怀疑是项目的导航栏使用了定位position, 但是取消后，也是没有效果

**Comment by afc163** [comment]
是否反馈错地方了？angular 的在这里 https://github.com/NG-ZORRO/ng-zorro-antd/issues
