### ISSUE TITLE
Carousel 组件autoplay属性动态的从true改为false，会停止轮播，这时候再由false变为true时 无法自动轮播。

### ISSUE THREAD

**Issue by smallfishr** [ant-design/ant-design#31776]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[htpps:1233wwww33.com](htpps:1233wwww33.com)

### Steps to reproduce
动态的将autoplay属性由false改成true。

### What is expected?
期望组件的行为随着数据的改动而变动

### What is actually happening?
不变

| Environment | Info |
|---|---|
| antd | 4.16.8 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by smallfishr** [comment]
https://codesandbox.io/s/antd-reproduction-template-jus3j?file=/index.js

**Comment by afc163** [comment]
```
+ @ant-design/react-slick@0.28.4
```
