### ISSUE TITLE
使用拖拽上传组件时，定义了accept属性吼，拖拽上传功能失效

### ISSUE THREAD

**Issue by maimai123** [ant-design/ant-design#31770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/maimai123/pen/JjNxqbQ?editors=0010](https://codepen.io/maimai123/pen/JjNxqbQ?editors=0010)

### Steps to reproduce
给官方例子中添加accept属性后，报错Uncaught TypeError: this._drop is not a function

```
const {  Upload, message  } = antd;
const {  InboxOutlined  } = icons;

const { Dragger } = Upload;

const props = {
  name: 'file',
  accept: '*',
  multiple: true,
  action: 'https://www.mocky.io/v2/5cc8019d300000980a055e76',
  onChange(info) {
    const { status } = info.file;
    if (status !== 'uploading') {
      console.log(info.file, info.fileList);
    }
    if (status === 'done') {
      message.success(`${info.file.name} file uploaded successfully.`);
    } else if (status === 'error') {
      message.error(`${info.file.name} file upload failed.`);
    }
  },
  onDrop(e) {
    console.log('Dropped files', e.dataTransfer.files);
  },
};

ReactDOM.render(
  <Dragger {...props}>
    <p className="ant-upload-drag-icon">
      <InboxOutlined />
    </p>
    <p className="ant-upload-text">Click or drag file to this area to upload</p>
    <p className="ant-upload-hint">
      Support for a single or bulk upload. Strictly prohibit from uploading company data or other
      band files
    </p>
  </Dragger>,
  mountNode,
);
```

### What is expected?
能够正常实现拖拽上传

### What is actually happening?
报错，无法实现正常拖拽上传

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | 16.12.0 |
| System | 10.15.6 |
| Browser | 版本 87.0.4280.88 |

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/129159028-9e192aad-6047-46e4-8fd1-225e744f9128.png">

没有重现。

**Comment by maimai123** [comment]
虽然很奇怪，但是确实是在我本地项目中会报错的，
且我打开这个链接上传也是会报错的
也有别的同学也有发现这个问题 
https://segmentfault.com/q/1010000018014261
![image](https://user-images.githubusercontent.com/15125340/129160729-b02ee34f-9ad5-4910-8eaa-dad46b941b6a.png)

**Comment by afc163** [comment]
https://github.com/react-dnd/react-dnd/issues/3132#issuecomment-797163612
