### ISSUE TITLE
Button style error

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#31777]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/an-niu-lei-xing-antd-4-16-11-forked-h0rc8)

### Steps to reproduce
Open & See

### What is expected?
Work as 4.16.10

### What is actually happening?
All in Red

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="647" alt="图片" src="https://user-images.githubusercontent.com/507615/129285487-6fe9dffa-fe16-4998-bc70-e2017cadf860.png">
