### ISSUE TITLE
use Typography.Paragraph in Select.Option get some error

### ISSUE THREAD

**Issue by CharlesMoone** [ant-design/ant-design#31781]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/typography-not-scaling-forked-e06sg?file=/src/App.js)

### Steps to reproduce
1. choose Select -> Option
2. Typography.Paragraph's ellipsis is useless

### What is expected?
Typography.Paragraph rows:2 should be useful

### What is actually happening?
Typography.Paragraph's ellipsis is useless

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.1 |
| System | macOS Catalina 10.15.7 (19H15) |
| Browser | Chrome 92.0.4515.131 |

**Comment by afc163** [comment]
https://codesandbox.io/s/typography-not-scaling-forked-s7405?file=/src/App.js
