### ISSUE TITLE
Slider tooltips position bug

### ISSUE THREAD

**Issue by deepansh946** [ant-design/ant-design#31784]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tvfbi)

### Steps to reproduce
1. Create a text area 
2. Create a slider below that
3. Resize the text area, now you'll see the slider tooltips' position isn't changed.

### What is expected?
The tooltips position should change.

### What is actually happening?
The tooltip's position isn't changing.

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.2 |
| System | Mac OS Big Sur |
| Browser | Chrome 92.0.4515.131 (Official Build) (x86_64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31475#issuecomment-884857288
