### ISSUE TITLE
[RangePicker] The date selected in the pannel is not equal to the same date manually entered in input

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#31783]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-typescript-template-1ezl1?file=/App.tsx)

### Steps to reproduce
1. Select the same date as start date and end date in the RangePicker pannel then check the console.
2. Change the end date to match the start date manually in input and press enter then check the console.
![picker bug](https://user-images.githubusercontent.com/50612752/129297938-ba78a06d-bce3-4e34-9ae4-95c157988cda.gif)

### What is expected?
The start date and end date should be same.

### What is actually happening?
The start date and end date are not same.

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.1 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 91.0.4472.114(x86_64) |

**Comment by afc163** [comment]
```dif
- startDate.isSame(endDate);
+ startDate.isSame(endDate, 'day');
```

**Comment by yoyo837** [comment]
@AlanCutFlim Excuse me, what screen recording software is this?

**Comment by AlanCutFlim** [comment]
> @AlanCutFlim Excuse me, what screen recording software is this?

ScreenFlow
