### ISSUE TITLE
使用TreeSelect的搜索时能不能把关键词给去除

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#3178]
![a](https://cloud.githubusercontent.com/assets/11780264/18869081/4ac9afc4-84dd-11e6-8717-f484e65b6d10.png)
- antd 版本: 1.11.1
- 操作系统及其版本:  win8.1
- 浏览器及其版本: chrome 52.0.2743.82

#### 您做了什么？

我使用了antd的TreeSelect组件做了一个多选的下拉框

问题:
当搜索的时候能不能去掉遗留的关键词

**Comment by warmhug** [comment]
描述不清楚。另外先搜索下其他 TreeSelect 相关 issue，看看有没有你要的答案

**Comment by XUGAOBO** [comment]
问题:
       当在使用搜索关键词的功能时,输入关键词,获取到了相应的搜素结果,但是关键词仍然存留在
![a](https://cloud.githubusercontent.com/assets/11780264/18940273/402843c0-8639-11e6-8a9b-e5a03844f1bc.png)


我搜索了与TreeSelect相关的issue,没有我想要的答案

**Comment by warmhug** [comment]
设置`inputValue={null}` #2716

**Comment by XUGAOBO** [comment]
希望完善下API
