### ISSUE TITLE
Possible to change value for Datepicker picker="week"?

### ISSUE THREAD

**Issue by truedrug** [ant-design/ant-design#31789]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://user-images.githubusercontent.com/19340495/129373563-fb997542-b5df-4042-b762-d38f8c405555.png

### Steps to reproduce
The selected value in the datepicker with picker="week" is like `2021-32nd`, Is it possible to format it?

### What is expected?
Should be able to format

### What is actually happening?
Coming as `2021-32nd`

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.14.0 |
| System | macos |
| Browser | Chrome |

**Comment by truedrug** [comment]
Can someone help here please?

**Comment by gokulthehunter** [comment]
Hi @truedrug, It's there in ANTD documentation week picker, sharing code sandbox link https://codesandbox.io/s/vwtnu, please refer 2nd Datepicker in it.

**Comment by truedrug** [comment]
@gokulthehunter I am already using the weekpicker, but upon selection, the value is in the format `YYYY - nth`, like 2021 - 35th. But my requirement is that, I want that value in a different format

**Comment by gokulthehunter** [comment]
@truedrug What format are you expecting in a week picker ? if you expecting the exact start date and end date of the selected week better to use a range picker with custom validation rules.

**Comment by truedrug** [comment]
I see, would try that out. Do you have any working example of that? Would definitely reduce my efforts on that

**Comment by huntdream** [comment]
Use `format`, [example](https://ant.design/components/date-picker/#components-date-picker-demo-format)

**Comment by truedrug** [comment]
Will I be able to get the selected week range in below format?

MM-DD-YYYY - MM-DD-YYYY ( Start date to end date)

**Comment by huntdream** [comment]
> Will I be able to get the selected week range in below format?
> 
> MM-DD-YYYY - MM-DD-YYYY ( Start date to end date)

Yes, it supports custom format `(value: moment) => string)`, you can return a string whatever you want
