### ISSUE TITLE
Dropdown下拉在placement为bottomRight时展示错误

### ISSUE THREAD

**Issue by U1in** [ant-design/ant-design#31798]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/dan-chu-wei-zhi-antd-4-16-11-forked-5ksfo?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
上述配置下，鼠标hover到按钮上即可

### What is expected?
下拉的内容贴着按钮的右边

### What is actually happening?
下拉的内容贴着按钮的左边

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Google Chrome 已是最新版本 版本 92.0.4515.131（正式版本） （64 位） |

**Comment by afc163** [comment]
需要把 `minOverlayWidthMatchTrigger={false}` 关了。https://codesandbox.io/embed/dan-chu-wei-zhi-antd-4-16-11-forked-5ksfo?fontsize=14&hidenavigation=1&theme=dark

**Comment by U1in** [comment]
> 需要把 `minOverlayWidthMatchTrigger={false}` 关了。
> 
> https://codesandbox.io/s/dan-chu-wei-zhi-antd-4-16-11-forked-ngh7r?file=/index.js
> 
> <img alt="图片" width="564" src="https://user-images.githubusercontent.com/507615/129515257-b952696a-f263-478c-9564-e565f3e72c88.png">
> 
> 虽然定义了 Menu 的宽度，浮层实际的宽度还是撑满的。
> 
> 或者用 overlayStyle 来覆盖样式：
> 
> https://codesandbox.io/s/dan-chu-wei-zhi-antd-4-16-11-forked-5lg6u?file=/index.js

感谢回复，建议将minOverlayWidthMatchTrigger更新到文档或者FAQ

**Comment by afc163** [comment]
@U1in 来个 PR 吧
