### ISSUE TITLE
表单更新，Form.Item的shouldUpdate函数返回false ，表单域也会更新

### ISSUE THREAD

**Issue by fubd** [ant-design/ant-design#31794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antd-l96tw?file=/src/index.js)

### Steps to reproduce
https://codesandbox.io/s/react-antd-l96tw?file=/src/index.js

### What is expected?
表单更新，Form.Item的shouldUpdate函数返回false ，表单域不更新

### What is actually happening?
表单更新，Form.Item的shouldUpdate函数返回false ，表单域也会更新

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.2 |
| System | mac os v11.1 |
| Browser | Chrome 88.0.4324.150 |

**Comment by afc163** [comment]
Form 的 shouldUpdate 只针对表单值有用，不会影响 React state 的状态更新。

**Comment by astudentat** [comment]
我也遇到这个问题

**Comment by cao-lianhui** [comment]
这个咋处理的。。

**Comment by cao-lianhui** [comment]
> Form 的 shouldUpdate 只针对表单值有用，不会影响 React state 的状态更新。

要咋处理不更新，没看懂

**Comment by cao-lianhui** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/react-antd-l96tw?file=/src/index.js)
> 
> ### Steps to reproduce
> https://codesandbox.io/s/react-antd-l96tw?file=/src/index.js
> 
> ### What is expected?
> 表单更新，Form.Item的shouldUpdate函数返回false ，表单域不更新
> 
> ### What is actually happening?
> 表单更新，Form.Item的shouldUpdate函数返回false ，表单域也会更新
> 
> Environment	Info
> antd	4.16.11
> React	17.0.2
> System	mac os v11.1
> Browser	Chrome 88.0.4324.150

解决了吗，咋处理的
