### ISSUE TITLE
Modal的延时关闭功能，为啥5s之后关闭之后，还会弹出一个新的modal

### ISSUE THREAD

**Issue by wuqiren** [ant-design/ant-design#31797]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
选择 open Modal to close in 5s  点击之后会出现一个倒计时modal，5s之后，关闭之后又出现了一个modal，卡在0s的地方

### What is expected?
5s之后关闭就别在弹出来

### What is actually happening?
5s之后关闭又弹出一个modal，而且需要手动去关闭

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
没看见你说的现象

**Comment by afc163** [comment]
确实有，有时候好有时候不好。只有 Chrome 下有这个问题。

**Comment by yoyo837** [comment]
嗷, 要第二次打点开

**Comment by wuqiren** [comment]
> 确实有，有时候好有时候不好。只有 Chrome 下有这个问题。

**Comment by wuqiren** [comment]
抱歉 点错了，   之前没注意，antd3 是没有这个问题的 这次升级4之后就发现了  目前确实只有chrome有这个问题
