### ISSUE TITLE
Form和Table结合处理动态表单的问题

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#3179]
#### 发生问题的环境是：

- antd 版本: 1.11.2
- 操作系统及其版本: 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
- 浏览器及其版本: 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

#### 您做了什么？
如下图，在table中动态增加和删除数据
![image](https://cloud.githubusercontent.com/assets/2271825/18869384/bc8b3aaa-84de-11e6-9194-23524db5a0d4.png)

#### 您期待的结果是：

删除行后，Table数据渲染正确

#### 实际上的结果是：

新增是没问题的，假设新增了好几行，当删除新增的非最后一行时，table的数据就不对了。

#### 可重现的在线演示

http://codepen.io/coderingz/pen/qamQGV?editors=001

**Comment by benjycui** [comment]
对比下你的代码与 demo 的不同如何？http://ant.design/components/form/#components-form-demo-dynamic-form-item

**Comment by codering** [comment]
一定要在form中维护一个数据的索引？？

**Comment by codering** [comment]
感觉和demo还是有些不一样的，demo里是能直接生成表单元素的，而我的场景还要把数据给Table处理。

**Comment by codering** [comment]
恩，通过keys可以处理。

**Comment by Younguser** [comment]
最后怎么获取table里面的数据
