### ISSUE TITLE
Form Upload Error(TypeError: items.map is not a function)

### ISSUE THREAD

**Issue by player1on3** [ant-design/ant-design#31791]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://catalyst-ecommerce.herokuapp.com/seller/product/add-new](https://catalyst-ecommerce.herokuapp.com/seller/product/add-new)

### Steps to reproduce
1.Clone the repo:https://github.com/sagarkharbe/Amazona-Ecommerce
2.add the env variables
3. cd server : $ npm run dev
4. register yourself and then as seller then try to create product

### What is expected?
×
TypeError: items.map is not a function
InternalUploadList
node_modules/antd/es/upload/UploadList/index.js:164
  161 | var prefixCls = getPrefixCls('upload', customizePrefixCls);
  162 | var listClassNames = classNames((_classNames = {}, _defineProperty(_classNames, "".concat(prefixCls, "-list"), true), _defineProperty(_classNames, "".concat(prefixCls, "-list-").concat(listType), true), _defineProperty(_classNames, "".concat(prefixCls, "-list-rtl"), direction === 'rtl'), _classNames)); // >>> Motion config
  163 | 
> 164 | var motionKeyList = _toConsumableArray(items.map(function (file) {
      | ^  165 |   return {
  166 |     key: file.uid,
  167 |     file: file
View compiled
renderWithHooks

### What is actually happening?
something is wrong in here    <Form.Item
          name="image"
          label="Upload"
          valuePropName="fileList"
          getValueFromEvent={normFile}
          hasFeedback
          rules={[{ type: 'array', len: 1, message: 'Upload 1 image!' }]}
        >
          <Upload
            name="image"
            action={process.env.CLOUDINARY_UPLOAD_URL}
            listType="picture"
            beforeUpload={() => false}
          >
            <Button>
              <UploadOutlined /> Click to upload
            </Button>
          </Upload>
        </Form.Item>
name

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | React |
| System | Mac OS |
| Browser | Chrome |

**Comment by player1on3** [comment]
@edd @afc163

**Comment by afc163** [comment]
Please provide a codesandbox.

**Comment by hengshanMWC** [comment]
同样的问题现在还有
