### ISSUE TITLE
antd Modal.confirm 的 ButtonProps 使用 danger:属性，背景颜色被覆盖成红色

### ISSUE THREAD

**Issue by Qiuhang817385** [ant-design/ant-design#31804]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/shi-yong-hooks-huo-de-shang-xia-wen-antd-4-16-11-forked-6cmec

### Steps to reproduce
官网 Modal 的 codePen 即可重现

### What is expected?
白底红字

### What is actually happening?
背景颜色也改成红色

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8 |
| System | windows |
| Browser | chorm 88 |

**Comment by Qiuhang817385** [comment]
![image](https://user-images.githubusercontent.com/38211706/129538217-24d79520-4a36-4121-977a-1668f7c4f7ca.png)

**Comment by afc163** [comment]
Fixed in https://yuque.antfin.com/docs/share/cfdd813d-b0bf-410d-8e3d-01f0980d88dd?#
Waiting for https://github.com/ant-design/ant-design/pull/31796
