### ISSUE TITLE
Table表格取值问题

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3180]
Table表格每行数据render了两个按钮，请问按钮的点击事件如何取到每行数据？

    <Table
                                    columns={[
                                        {title: '时间', dataIndex: 'time', key: 'time',},
                                        {title: '工位', dataIndex: 'surplus', key: 'surplus',},
                                        {title: '折扣', dataIndex: 'discount', key: 'discount',},
                                        {title: '网点', dataIndex: 'netId', key: 'netId',},
                                        {title: '操作', key: 'operation',
                                            render: (record) => (
                                                   <ButtonGroup>
                                                        <Button onClick={this.test}><Icon type="cross" /></Button>
                                                        <Button onClick={this.test}><Icon type="edit" /></Button>
                                                    </ButtonGroup>
                                            ),
                                    }]}
                                    dataSource={this.state.data}
                     />

**Comment by RifeWang** [comment]
能否提供一个基本的增删改查数据的demo

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/1184

https://github.com/ant-design/ant-design/issues/1154

https://github.com/ant-design/ant-design/issues/1388

**Comment by RifeWang** [comment]
貌似找到问题的原因了，render下面的button点击事件需要修改：
render: (record) => (
       <ButtonGroup>
             //此处es6写法没问题，通过点击事件可以正常调用deleteForm方法，并且每行record数据可以传递
           <Button onClick={()=>this.deleteForm(record)}><Icon type="cross" /></Button>
                        
           //此处写法错误，页面加载时会自动调用updateForm方法，然后点击事件失效
           <Button onClick={this.updateForm(record)}><Icon type="edit" /></Button>
      </ButtonGroup>

 ),
