### ISSUE TITLE
antd vue select可搜索组件在使用focus获取焦点时，希望增加光标焦点闪烁

### ISSUE THREAD

**Issue by star-devil** [ant-design/ant-design#31801]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使select搜索组件类似input,获取焦点时光标自动获取，可直接输入搜索内容

### What does the proposed API look like?
无需单独的api,直接修改现有的focus方法即可

**Comment by afc163** [comment]
> antd vue select

提错地方了，官方仓库是 React 实现。
