### ISSUE TITLE
当 Form.Item 的 validator 返回 Promise.reject(new Error('')) 时页面将崩溃

### ISSUE THREAD

**Issue by ladjzero** [ant-design/ant-design#31803]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-17g83)

### Steps to reproduce
在「姓名1」中录入文字

### What is expected?
页面不崩溃，输入框被标红，无错误文案信息。如输入「姓名3」一样。

### What is actually happening?
页面崩溃

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 16.14.0 |
| System | MacOS |
| Browser | 91.0.4472.101 |

---
业务代码早期采用的「姓名3」的写法，后来引入了 lint 规则，要求 Promise.reject(string) 改为 Promise.reject(new Error(string))。经过回归，大部分功能正常。
后来出现线上问题，经排查是 Promise.reject('') 改写为 Promise.reject(new Error('')) 导致的。

错误信息
```
Uncaught Error: Objects are not valid as a React child (found: Error). If you meant to render a collection of children, use an array instead.
    in div (created by CSSMotion)
    in div (created by CSSMotion)
    in CSSMotion (created by ForwardRef)
    in ForwardRef (created by FormItemInput)
    in div (created by Context.Consumer)
    in Col (created by FormItemInput)
    in FormItemInput (created by Field)
    in div (created by Context.Consumer)
    in Row (created by Field)
    in Field (created by WrapperField)
    in WrapperField (created by FormItem)
```

**Comment by yoyo837** [comment]
从你贴的错误来看, 和Promise应该没关系

**Comment by yoyo837** [comment]
可以先改为

```diff
-Promise.reject(new Error(''))
+Promise.reject(new Error('有字符串'))
```

临时解决

**Comment by afc163** [comment]
https://github.com/react-component/field-form/pull/88

**Comment by zombieJ** [comment]
看了一下，是底层问题。就不在 field-form 里再包一层了。

https://github.com/yiminghe/async-validator/pull/285

**Comment by afc163** [comment]
@zombieJ rc-field-form 需要升级一下依赖。
