### ISSUE TITLE
Upload post

### ISSUE THREAD

**Issue by zjx0917** [ant-design/ant-design#31811]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://ceshi/test.com](http://ceshi/test.com)

### Steps to reproduce
点击上传文件，打开选择文件弹框，选择文件后，点击打开，会发送post网络请求，如果action没有配置，发送的请求是网站的地址。

### What is expected?
选择文件后，不发送请求，怎么配置？

### What is actually happening?
选择文件后，始终会发送请求。

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

---
内网环境，不能填正确的网址。

**Comment by afc163** [comment]
https://ant.design/components/upload-cn/#components-upload-demo-upload-manually
