### ISSUE TITLE
Divider分割线 建议增加 @divider-orientation-margin; API，以方便设置边缘距离

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#31834]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

````
&-horizontal&-with-text-left {
    &::before {
      top: 50%;
      width: @divider-orientation-margin;
    }
    &::after {
      top: 50%;
      width: 100% - @divider-orientation-margin;
    }
  }

  &-horizontal&-with-text-right {
    &::before {
      top: 50%;
      width: 100% - @divider-orientation-margin;
    }
    &::after {
      top: 50%;
      width: @divider-orientation-margin;
    }
  }
````

**Comment by afc163** [comment]
来个 PR。

**Comment by hihuangwei** [comment]
若@divider-orientation-margin为0，左对齐padding-left应为0，右对齐padding-right应为0
![QQ浏览器截图20210818173316](https://user-images.githubusercontent.com/3166799/129875279-f7a06557-f7a1-4997-a38c-c884a7e5038c.png)

**Comment by afc163** [comment]
貌似现在就有 `@divider-orientation-margin` 变量。

**Comment by hihuangwei** [comment]
> 貌似现在就有 `@divider-orientation-margin` 变量。
> 
> #24877

能否添加到组件API，全局theme 可能不大灵活

**Comment by afc163** [comment]
感觉可以，来个 PR 吧。

**Comment by neotan** [comment]
Hello @hihuangwei, let me know if no one is working on it, I'll love to raise a PR for it ;)

**Comment by hihuangwei** [comment]
Hope to get your PR @neotan

**Comment by neotan** [comment]
To make the code clean, just leveraging the  `paddingLeft/Right` of Title for making spaces against the border, rather than using `marginLeft/Right`. Hope this is clarified. Thanks.

**Comment by neotan** [comment]
@afc163  Kindly let me know if any comment;), thanks
