### ISSUE TITLE
The Pagination SizeChanger  is blocked ( 分页下拉框被遮挡)

### ISSUE THREAD

**Issue by yjw0628** [ant-design/ant-design#31837]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-webut?file=/index.js)

### Steps to reproduce
Pagination SizeChanger  is blocked
分页下拉框被遮挡

### What is expected?
Don't be blocked
下拉框不被遮挡
希望能适用全局getPopupContainer属性

### What is actually happening?
Pagination SizeChanger is blocked

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | all |
| System | all |
| Browser | all |

---
all

**Comment by afc163** [comment]
把 `transform: "translate(0, 0)"` 去掉就好，translate 会影响元素的 z 轴。

**Comment by yjw0628** [comment]
业务场景是 多个模块可以拖拽排版的. 必须用translate来做


![image](https://user-images.githubusercontent.com/15664734/129876359-2ce53c9f-f38a-4c56-9158-9ad0a122fe1f.png)
为啥分页的Select 不适用这个配置项

**Comment by yjw0628** [comment]
@afc163

**Comment by afc163** [comment]
目前是写死的，可以开个 API 出来，欢迎 PR。

https://github.com/react-component/pagination/blob/b8a5442451a06459728cc680143026459596e1fc/src/Options.jsx#L125

**Comment by afc163** [comment]
或者你可以给带浮层的组件统一加一个 `zIndex`：https://codesandbox.io/s/antd-reproduction-template-forked-gen32?file=/index.js

**Comment by yjw0628** [comment]
感谢,已经用zIndex解决, 之后我看看提个PR
