### ISSUE TITLE
Mentions组件 也是使用键盘上下选择时，滚动条不会自动滚动

### ISSUE THREAD

**Issue by wangshaozhi** [ant-design/ant-design#31836]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/mentions-cn/#components-mentions-demo-form](https://ant.design/components/mentions-cn/#components-mentions-demo-form)

### Steps to reproduce
当Option数据比较多的时候

### What is expected?
鼠标滚轮和上下键盘都可以控制滚动条的滚动

### What is actually happening?
鼠标滚轮可以控制滚动条滚动，上下键盘无法滚动，导致使用向下键盘时无法看到当前选中了哪一项

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | react |
| System | mac |
| Browser | google |

**Comment by afc163** [comment]
合并到 https://github.com/ant-design/ant-design/issues/31756
