### ISSUE TITLE
If form item label too long, string was truncated

### ISSUE THREAD

**Issue by acfasj** [ant-design/ant-design#31835]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9wmpc?file=/package.json:59-65)

### Steps to reproduce
as the demo

### What is expected?
wrap to display whole label content, no truncated

### What is actually happening?
label was truncated

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 18.0.0-alpha-e3b76a85c-20210802 |
| System | macOS Catalina 10.15.7 |
| Browser | chrome 86.0.4240.80（正式版本） (x86_64) |

**Comment by afc163** [comment]
What is the expected behavior? wrap or show ellipsis symbol?

**Comment by acfasj** [comment]
> What is the expected behavior? wrap or show ellipsis symbol?

wrap, to display all content is expected. show the complete information is more important in admin system, I think

**Comment by afc163** [comment]
My suggestion is that using `layout="vertical"` in this case. Horizontal layout cannot have enough space to show whole long content.

https://codesandbox.io/s/antd-reproduction-template-forked-cojxf?file=/index.js

**Comment by acfasj** [comment]
> My suggestion is that using `layout="vertical"` in this case. Horizontal layout cannot have enough space to show whole long content.
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-cojxf?file=/index.js

ok, actually it is a design choice in antd, and a decision in developers, I choose to override the CSS currently
