### ISSUE TITLE
当Layout.Sider和Table一同使用时，渲染效率极低导致卡顿或浏览器崩溃

### ISSUE THREAD

**Issue by johnsen-zhang** [ant-design/ant-design#31848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://antd](http://antd)

### Steps to reproduce
创建Layout布局
左侧使用Layout.Sider, 右侧使用Layout.Content
右侧内容为一个响应式的表格，内容超过50上，表格列在5列以上
用按钮控制左侧Layout.Sider的 collapsed 属性
切换时会出现卡顿

### What is expected?
能够流畅，不卡顿或者浏览器崩溃

### What is actually happening?
卡顿，严重时浏览器崩溃

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | react |
| System | macOS Big Sur |
| Browser | Chrome 92.0.4515.131 |

---
代码如下:
<Layout>
                <Layout.Sider collapsed={coll}>
                    <Button onClick={() => {this.setState({ coll: !coll });}}>111</Button>
                </Layout.Sider>
                <Layout.Content>
                    <Table
                        {...tableProps}
                        dataSource={dataSource}
                        rowKey="tableName"
                        size="small"
                        pagination={{
                            pageNo,
                            pageSize,
                            total
                        }}
                        scroll={{ x: '100%' }}
                        onChange={this.handleTableChange}
                    />
                </Layout.Content>
            </Layout>

**Comment by afc163** [comment]
Duplicate of #27775

**Comment by Azir1** [comment]
遇到了同样的问题，最后咋解决的？
