### ISSUE TITLE
TreeSelect: After expanding the node, enter the content search and then clear it, you cannot expand the node again

### ISSUE THREAD

**Issue by rumunanfeng** [ant-design/ant-design#31845]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/rumunanfeng/pen/KKmjrWy?editors=0010](https://codepen.io/rumunanfeng/pen/KKmjrWy?editors=0010)

### Steps to reproduce
1. Expand the parent node
2. Enter any value in the search box and clear it

### What is expected?
The tree can still be expanded and data can be obtained using loadData

### What is actually happening?
The tree does not have an expand icon and cannot be expanded

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 16.x |
| System | win10 |
| Browser | Chrome - 92.0.4515.107 |

---
1. Setting isLeaf to false will make the icon appear, however it will not get the data either
2. If the node is not expanded, there is no problem

**Comment by zombieJ** [comment]
Could you provide gif for this? I can not reproduce.

**Comment by zombieJ** [comment]
TreeSelect will record loading status. When you change the `treeData` and remove `children`, TreeSelect will trade it as expect:

<img width="608" alt="截屏2021-09-13 下午5 43 48" src="https://user-images.githubusercontent.com/5378891/133062543-10fb30c7-237f-4c77-a2d2-599490632c73.png">

**Comment by jingdd-boop** [comment]
请问这个怎么解决的啊

**Comment by rumunanfeng** [comment]
> TreeSelect will record loading status. When you change the `treeData` and remove `children`, TreeSelect will trade it as expect:

![treeSelect](https://user-images.githubusercontent.com/37805363/134302360-451e5b34-6ecc-42e0-a862-0bd6ff2d51d4.gif)
Please see the gif demonstration, after the search is completed and then cleared, the icon of the expand tree node disappears and the expand operation cannot be

**Comment by ding991** [comment]
> remove

这个解决方案不是很懂，还是交互就是这样的？

**Comment by crystalwm** [comment]
@zombieJ  tree-select 组件可以暴露“ loadedKeys” 属性和“ onLoad” 方法，让它和tree组件一样，异步加载的时候可以受控吗？

**Comment by crystalwm** [comment]
试试 treeExpandedKeys, treeLoadedKeys , onTreeLoad, onTreeExpand 
在(https://github.com/react-component/tree-select/blob/master/src/generate.tsx) 在这里找到了treeLoadedKeys 属性和 onTreeLoad 方法
@zombieJ  大佬晒时候有空把ant-design 的tree-select 文档（https://github.com/ant-design/ant-design/blob/master/components/tree-select/index.zh-CN.md）补充一下，我在文档里面没有找到treeLoadedKeys 属性和 onTreeLoad 方法
