### ISSUE TITLE
2.0.0版本新引入的Mention组件能不能修改@符号为其他自定义符号

### ISSUE THREAD

**Issue by ThinkCats** [ant-design/ant-design#3184]
#### 发生问题的环境是：

- antd 版本: 2.0.0

#### 您做了什么？
使用Mention 组件

#### 您期待的结果是：
可以使用自定义的符号触发mention回调，而不是使用@符号。

#### 实际上的结果是：
当前版本貌似只有@符号才可以触发回调

#### 可重现的在线演示
暂无

**Comment by benjycui** [comment]
有个 `prefix` 属性 https://github.com/react-component/editor-mention/blob/master/src/Mention.jsx#L126

但是习惯都是 `@`，应该没有修改的必要？

**Comment by ThinkCats** [comment]
@benjycui  个人的想法是Mention不只是可以做社交功能里面的@圈人功能，还可以做一些其他的。比如，我要做一个关键字检索的话，自定义一个#符号（类似微博的话题），那我打算输入#，就可以检索出关键字。如果只能用@，给人的感觉怪怪的。

**Comment by RaoHai** [comment]
确实是可以传 prefix 来更改这个 `@` 符号的。

**Comment by woodccc** [comment]
prefix 中如果使用“$“不能正常工作。

**Comment by RaoHai** [comment]
确实有这个问题，好诡异……

**Comment by RaoHai** [comment]
已经修正。重新 npm install 即可。

**Comment by woodccc** [comment]
@RaoHai 请问是2.1.0吗，我已经升级到2.1.0了，试了“$”还是不工作哦。

**Comment by afc163** [comment]
用 babel-plugin-import。https://github.com/ant-design/ant-design/pull/3397
