### ISSUE TITLE
SubMenu causes warning in Next.js

### ISSUE THREAD

**Issue by aprisniak** [ant-design/ant-design#31842]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/aprisniak/next-bug](https://github.com/aprisniak/next-bug)

### Steps to reproduce
just run in dev mode and open chrome dev tools

### What is expected?
no warnings

### What is actually happening?
Warning: Prop `className` did not match. Server: "ant-menu-title-content" Client: "-title-content"

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | MacOS 11.5.2 |
| Browser | Chrome Version 92.0.4515.131 (Official Build) (x86_64) |

---
If you remove or comment SubMenu then warning disapears.

**Comment by zombieJ** [comment]
Next.js using es module but you import from es. Which do not share the same context:

```diff
    import { Menu } from 'antd';
--  import SubMenu from 'antd/lib/menu/SubMenu';
++  const { SubMenu } = Menu;

const Home = () => {
```
