### ISSUE TITLE
Pass referrerpolicy to Avatar element

### ISSUE THREAD

**Issue by byan** [ant-design/ant-design#31840]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd’s Avatar element does not pass referrer policy and other attributes to the underlying img element. Please add it.

### What does the proposed API look like?
<Avatar refererpolicy=“noreferrer “ />

**Comment by afc163** [comment]
```jsx
    <Avatar
      src={
        <Image
          refererPolicy="noreferrer"
          src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png"
        />
      }
    />
```

**Comment by byan** [comment]
It works! thank you!

**Comment by Xiaochena** [comment]
> ```js
>     <Avatar
>       src={
>         <Image
>           refererPolicy="noreferrer"
>           src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png"
>         />
>       }
>     />
> ```
这样做之后  图片加载错误 的 icon 将失效
