### ISSUE TITLE
4.16.12menu相关组件（SubMenu、Item）使用key报错，要是用eventKey，但文档中没有写

### ISSUE THREAD

**Issue by alwaysRemember** [ant-design/ant-design#31849]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/#API](https://ant.design/components/menu-cn/#API)

### Steps to reproduce
Menu相关组件使用key报错，需要使用eventKey，但是文档中没有写出来。

### What is expected?
修改文档

### What is actually happening?
。。。。

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 17 |
| System | macos |
| Browser |  92.0.4515.131 |

---
Warning: Duplicated key 'undefined' used in Menu by path [dataKanban] 
    at MenuItem (http://localhost:8000/vendors-node_modules___ant-design_icons_4_6_3_ant-design_icons_es_icons_UserOutlined_js-node_-241a94.js:25836:24)

以下为log代码
function MenuItem(props) {
  var eventKey = props.eventKey; // ==================== Record KeyPath ====================

**Comment by afc163** [comment]
@zombieJ 文档可以补一下。
