### ISSUE TITLE
select选单在具有滚动条的时候上下移动鼠标会出现滚动条消失的情况

### ISSUE THREAD

**Issue by Minfee** [ant-design/ant-design#31853]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ehcst)

### Steps to reproduce
![复现图片](https://cloud.lmfup.com/CleanShot%202021-08-19%20at%2016.09.16.gif)

### What is expected?
移动时不会消失滚动条

### What is actually happening?
滚动条会消失

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8 |
| System | macos |
| Browser | chrome 92.0.4515.159（正式版本） (x86_64) |

**Comment by PeachScript** [comment]
『移动时不会消失滚动条』的基准是来源于 macOS 系统控件的交互吗？

试了下交互型控件（例如一个内容足以出现滚动条的 `textarea`），在 macOS 下先滚动、再鼠标在控件范围内随意移动，滚动条不会消失

但非交互型控件（例如一个有滚动条的 `div`），在上述同样操作后，滚动条会在滚动停止后的一段时间内消失

**Comment by Minfee** [comment]
哦哦  那这个可以理解为在select的option中 已经定义为了非交互性控件？

**Comment by PeachScript** [comment]
倒不是，只是想了解下你提这个 issue 的原始背景，之前没有注意过这个交互细节

回到问题本身，Option 列表之所以不响应鼠标移动来保留滚动条显示，是因为虚拟滚动的模拟滚动条在交互细节上和系统控件不完全一致导致的，把虚拟滚动关闭就符合期望了

**Comment by Minfee** [comment]
OK， 本质上是觉得作为一个可以滚动的内容应该一直显示滚动条，上面提到的div的场景确实没有注意过

**Comment by zombieJ** [comment]
这个是根据展示信息设计的，滚动条由于是内嵌样式。初次打开如果是可滚动的，不展示滚动条会让人以为它无法滚动。但是如果长时间显示滚动条，又会使一些在 Option 右侧加了额外信息的部分被滚动条挡住。所以设计上，下拉窗打开时会故意显示一下滚动条提醒用户当前选项较多可以滚动。同时过一会儿消失不阻碍完整的信息展示。
