### ISSUE TITLE
Add Khmer localization 

### ISSUE THREAD

**Issue by ponleukea** [ant-design/ant-design#31855]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I can not change language to Khmer because don't have khmer language in locales list.
And unable to pull request .

### What does the proposed API look like?
- km_KH.d.ts
- km_KH.js

**Comment by afc163** [comment]
Added in https://github.com/ant-design/ant-design/pull/32853

**Comment by rfgonzalezweb** [comment]
I dont know if this helps someone but I needed khmer support for InputNumber components.
So I ended up adapting this component.

https://stackblitz.com/edit/vitejs-vite-qgsrnwtt?file=src%2FApp.jsx

(will delete the comment if this is not the place for it 👌 )
