### ISSUE TITLE
AutoComplete with multiple choice (like Select)

### ISSUE THREAD

**Issue by MichaelSavin** [ant-design/ant-design#31858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To implement the logic of an open list of values (i.e. a list in which the user can add new positions), I would like to use the autocomplete component with the ability to select multiple values (enter values separated by commas) now I cannot do this. 
The functionality of the Select component allows me only to select from a closed list, not add a new element.

### What does the proposed API look like?
mode="multiple"

**Comment by afc163** [comment]
https://ant.design/components/select/#components-select-demo-tags
