### ISSUE TITLE
select component include showsearch's bug / select 组件 ,当使用showsearch 功能的时候有bug

### ISSUE THREAD

**Issue by RaijinBai** [ant-design/ant-design#31850]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#components-select-demo-search](https://ant.design/components/select-cn/#components-select-demo-search)

### Steps to reproduce
1. input "a", then drop-down list display "Jack", then click "enter" keyboard , will select Jack .
2. then input "t",then drop-down list display "Tom", then click "enter" keyboard, is still select "Jack"
Please try  several times about these 2 step.  until the drop-down list won't highlight the text in drop-down list, it will happen.
----------------------------------------------
1. 在输入框输入"a",然后下拉框会显示"Jack",然后点击"回车"键, 组件会选择"Jack" 
2.然后继续在输入框输入"t",然后下拉框会显示"Tom",然后点击"回车"键, 组件依然会选择"Jack" ,
请多尝试以上的步骤, 直到输入完后,下拉框没有高亮选择文本,就会出现上面的情况.

### What is expected?
it's will select first item after click enter.

### What is actually happening?
it's won't select.

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 16.13 |
| System | windows |
| Browser | google chrome  92.0.4515.159 |

**Comment by afc163** [comment]
重现了，偶发。

**Comment by zombieJ** [comment]
看起来是 activeKey 没刷新上的问题

**Comment by RaijinBai** [comment]
请问.什么时候会在新版本上修复?

**Comment by RaijinBai** [comment]
> 看起来是 activeKey 没刷新上的问题

请问.什么时候会在新版本上修复?

**Comment by RaijinBai** [comment]
> 看起来是 activeKey 没刷新上的问题

请问.什么时候会在新版本上修复?
