### ISSUE TITLE
Form.Item rules are not working with Form from ant-design/compatible

### ISSUE THREAD

**Issue by IskraAtanasova** [ant-design/ant-design#31851]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-fvuxc?file=/index.js)

### Steps to reproduce
Import {Form} from "@ant-design/compatible"

    Create
    Create <Form.Item>
    Create input

Add rules to Form.Item

< Form.Item
name="email"
rules={[
{
type: "email",
message: "Please enter a valid email address."
}
]}
>

### What is expected?
Validate input field

### What is actually happening?
Property 'rules' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 16.14.0 |
| System | latest |
| Browser | latest |

---
I know it works well if Form is imported from "antd" , but I need ant-design/compatible, because I am using Form.create() and I can't rewrite that.

**Comment by afc163** [comment]
<img width="1074" alt="图片" src="https://user-images.githubusercontent.com/507615/130033761-435ed7b8-b700-479c-b38e-acd35daa037f.png">

Your codesandbox doesn't contain any TS and form code.

**Comment by IskraAtanasova** [comment]
> 
> 
> <img alt="图片" width="1074" src="https://user-images.githubusercontent.com/507615/130033761-435ed7b8-b700-479c-b38e-acd35daa037f.png">
> 
> Your codesandbox doesn't contain any TS and form code.

https://codesandbox.io/s/antd-reproduction-template-forked-fvuxc?file=/index.js

**Comment by afc163** [comment]
Cannot reproduce `Property 'rules' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes` in your codesandbox which is a javascript sample.

**Comment by IskraAtanasova** [comment]
> 
> 
> Cannot reproduce `Property 'rules' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes` in your codesandbox which is a javascript sample.

The validation is just not working, nothing is happening.

**Comment by IskraAtanasova** [comment]
> 
> 
> Cannot reproduce `Property 'rules' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes` in your codesandbox which is a javascript sample.

Can you check this 
https://codesandbox.io/s/antd-reproduction-template-forked-9g2cv

**Comment by afc163** [comment]
Form in `@ant-design/compatible` has same usage as https://3x.ant.design/components/form/

**Comment by IskraAtanasova** [comment]
Okay, but how to use the rules? in antd V4 you can use rules without getFieldDecorator


<Form>
      <Form.Item 
      label="Username"
      hasFeedback
      name="inputField"
      rules={[
      {
      type: "email",
      message: "Please enter a valid email address"
       }
       ]}
       >
       <Input></Input>
      </Form.Item>
    </Form>
