### ISSUE TITLE
Select Option 加了Popover后，在Popover上点击鼠标，功能异常

### ISSUE THREAD

**Issue by mx560** [ant-design/ant-design#31856]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-53qlv?file=/index.js)

### Steps to reproduce
1. 在Select中选择一项后，鼠标经过Select框显示Popover后，在Popover中点击鼠标；
2. 展开下拉框，显示Popover后，在Popover点击鼠标，下拉框异常收起;

### What is expected?
Select下拉框不闪烁

### What is actually happening?
Select下拉框闪烁

| Environment | Info |
|---|---|
| antd | undefined |
| React | 4.16.12 |
| System | macos windows |
| Browser | chrome  |

---
下拉框的中Option套用的Popover，在Popover中点击鼠标，下拉框收起，Popover不关闭，期望下拉框不收起

**Comment by zombieJ** [comment]
因为点击 Popover 事件冒泡给了 Option 导致你其实是点击了选项，给 Popover 的元素加一个 stopPropagation 即可

**Comment by laochake** [comment]
> 
https://codesandbox.io/s/antd-reproduction-template-forked-5711u8 试了下加stopPropagation也不行
