### ISSUE TITLE
`!important` for Button padding breaks custom styles

### ISSUE THREAD

**Issue by berdyshev** [ant-design/ant-design#31862]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

This was introduced by PR #30006

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mzuqc?file=/index.css)

### Steps to reproduce
set custom padding and line height for the button with `href`

### What is expected?
properly aligned text with paddings

### What is actually happening?
text aligned to the top of the button

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 17.0.2 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
Try https://codesandbox.io/s/antd-reproduction-template-forked-wfxv9

**Comment by berdyshev** [comment]
> Try https://codesandbox.io/s/antd-reproduction-template-forked-wfxv9

yes, you don't use paddings. In my case I want to control button size with paddings (horizontal and vertical)

**Comment by disguised-uchiha** [comment]
Please remove the *!important* from this PR: https://github.com/ant-design/ant-design/pull/30006.
Our legacy custom implementation failed when updated the antd. For now we are rolling back to previous version. Please fix it as soon as possible. Thank you.

**Comment by afc163** [comment]
There is no `!important` in antd 5.x now.

**Comment by orlandovallejos** [comment]
@berdyshev Were you able to do it?
I want to update the padding of my buttons and I can't find a proper way to do it!
