### ISSUE TITLE
使用Space组件包裹Table组件会导致Table组件的scroll属性失效

### ISSUE THREAD

**Issue by shend** [ant-design/ant-design#31867]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/shend/antd-issue-space](https://github.com/shend/antd-issue-space)

### Steps to reproduce
如下情况，scroll属性将失效。
```
<Space direction="vertical">
    <div>这是一个自定义组件</div>
    <Table
        columns={columns}
        dataSource={data}
        scroll={{x: 1500}}
    />
</Space>
```

### What is expected?
Table组件可以通过scroll水平滚动

### What is actually happening?
Table组件的scroll属性失效并导致Table超出父容器

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 16.12.0 |
| System | Darwin pvg-mac 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64 |
| Browser | 版本 92.0.902.62 (官方内部版本) (x86_64) |

**Comment by afc163** [comment]
```diff
- <Space direction="vertical">
+ <Space direction="vertical" style={{ maxWidth: '100%' }}>
```
