### ISSUE TITLE
Forgot title prop on switch page

### ISSUE THREAD

**Issue by tippillow** [ant-design/ant-design#31868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/switch/#API](https://ant.design/components/switch/#API)

### Steps to reproduce
https://ant.design/components/switch/#API

### What is expected?
Title prop in api section

### What is actually happening?
No prop title

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | Chrome  86 |

**Comment by PeachScript** [comment]
The `title` property is a [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) from HTML Spec rather than `antd` special, it can be used on any element, so I think we donot need to documented it anymore?

**Comment by tippillow** [comment]
yeah, sorry my bad
