### ISSUE TITLE
父级display为flex下的input输入框宽度超出范围

### ISSUE THREAD

**Issue by shuangovo** [ant-design/ant-design#31865]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-c4o4q?file=/index.js)

### Steps to reproduce
input输入框宽度为100%时

### What is expected?
input不占用其他节点的宽度

### What is actually happening?
input占用了其他节点的宽度

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome92 |

**Comment by afc163** [comment]
给 Input 设置一个宽度就行：https://codesandbox.io/s/antd-reproduction-template-forked-ni71f
