### ISSUE TITLE
当给Tree设置padding或者margin,ant-tree-switcher-leaf-line会出现1px偏差

### ISSUE THREAD

**Issue by Kido-200** [ant-design/ant-design#31884]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-rgb-hptf4?file=/index.js)

### Steps to reproduce
打开codesandbox

### What is expected?
problemg行没有偏差

### What is actually happening?
problemg行出现1px偏差

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | window10 |
| Browser | chrome |

---
打开index.css里注释内容即正常

**Comment by afc163** [comment]
<img width="920" alt="图片" src="https://user-images.githubusercontent.com/507615/130571048-a96dc6e9-4370-483f-a4c0-189710d117dd.png">

<img width="942" alt="图片" src="https://user-images.githubusercontent.com/507615/130571096-39d78611-ccee-4f27-8b3a-469f015a0113.png">

好像没发现有啥不同。

**Comment by Kido-200** [comment]
可能跟电脑显示器有关，我缩放一下也会正常




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 当给Tree设置padding或者margin,ant-tree-switcher-leaf-line会出现1px偏差 (#31884)





 

 

 
好像没发现有啥不同。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by afc163** [comment]
是不是同一个问题 https://github.com/ant-design/ant-design/issues/31471

**Comment by Kido-200** [comment]
嗯 用我index.css可能可以解决？我这里看的话是可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 当给Tree设置padding或者margin,ant-tree-switcher-leaf-line会出现1px偏差 (#31884)





 
是不是同一个问题 #31471
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by afc163** [comment]
因为我这里重现不了，没法测试有没有别的副作用。

**Comment by afc163** [comment]
<img width="1091" alt="图片" src="https://user-images.githubusercontent.com/507615/130590682-7a47674e-372c-4ebe-8fb5-53a6fa1f4b8e.png">

加上你的 fix 后，放大时的偏差行了，缩放 90% 会出问题。

**Comment by Kido-200** [comment]
确实。。我这里缩小到50%以下也会有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 当给Tree设置padding或者margin,ant-tree-switcher-leaf-line会出现1px偏差 (#31884)





 

 
加上你的 fix 后，放大时的偏差行了，缩放 90% 会出问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by afc163** [comment]
https://codesandbox.io/s/cranky-rhodes-t3rvz?file=/index.css

这样就好了。

**Comment by Kido-200** [comment]
感谢！以后版本的antd会修改吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 当给Tree设置padding或者margin,ant-tree-switcher-leaf-line会出现1px偏差 (#31884)





 
https://codesandbox.io/s/cranky-rhodes-t3rvz?file=/index.css
 
这样就好了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by afc163** [comment]
@Kido-200 来个 PR 如何？
