### ISSUE TITLE
select 组件中的dropdownRender 包含DatePicker，选择时间日期后自动关闭，没有执行DatePicker的方法

### ISSUE THREAD

**Issue by JacksonSunn** [ant-design/ant-design#31881]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-16-13-forked-wqnl9)

### Steps to reproduce
点击select 框 再点击datepicker 选择时间日期，就会自动关闭，没用执行datepicker中onOK的方法。

### What is expected?
点击onOk 之后在select 中的dropdownRender 显示datepicker的值

### What is actually happening?
点击选择时间后就直接关闭

| Environment | Info |
|---|---|
| antd | 4.15.2 |
| React | 17.0.1 |
| System | win10 |
| Browser | Chrome 92.0.4515.159 |

**Comment by afc163** [comment]
https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-16-13-forked-jyltw?file=/index.js
