### ISSUE TITLE
列表过长时，radio 组合，在手机响应上非常卡顿，从点击到响应onchange中间有好几秒时间，和样式计算有关系

### ISSUE THREAD

**Issue by loveProgrammingRedWolf** [ant-design/ant-design#31889]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-lichterman-b7wiz?file=/src/App.js)

### Steps to reproduce
.

### What is expected?
.

### What is actually happening?
.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | lates |
| System | any |
| Browser | any |

**Comment by xrkffgg** [comment]
建议采用动态加载
