### ISSUE TITLE
For defaultOpenValue prop in TimePicker component, get warning: "`defaultOpenValue` may confuse user for the current value status. Please use `defaultValue` instead. "

### ISSUE THREAD

**Issue by devluked** [ant-design/ant-design#31892]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://vm2bx.csb.app/](https://vm2bx.csb.app/)

### Steps to reproduce
I couldn't get it to fully reproduce, but clicking the time selector should automatically go to 06:00 on the time selector. 

### What is expected?
The time selector goes to 06:00 when opened up, but gives this warning: '"`defaultOpenValue` may confuse user for the current value status. Please use `defaultValue` instead. "'

### What is actually happening?
NA

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.14 |
| System | macOS 11.3.1 (20E241) |
| Browser | Chrome |

---
The defaultOpenValue works great on my app, (when I click the time selector it opens the time selector to the defaultvalue), but it gives me this warning and I don't know how to fix it.

"`defaultOpenValue` may confuse user for the current value status. Please use `defaultValue` instead. "

**Comment by afc163** [comment]
We don't recommand this property now: https://github.com/ant-design/ant-design/pull/21198
