### ISSUE TITLE
Cascader 的触发器设置为 Input，可以输入，无法删除输入框字符

### ISSUE THREAD

**Issue by jianghai** [ant-design/ant-design#31890]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-yi-zi-ding-yi-xian-shi-antd-4-16-12-forked-ld66g?file=/index.js)

### Steps to reproduce
点击 Input，输入，删除

### What is expected?
可以删除字符

### What is actually happening?
Input 输入正常，无法删除字符

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment]
竟然还有这么奇葩的用法

cascader 监控了键盘事件

https://github.com/react-component/cascader/blob/04c46557779b8da8eca18beebbcb5617bd06791f/src/Cascader.tsx#L320

你把 input 放外面 或者 使用 showSearch

**Comment by jianghai** [comment]
... 需求就是放里面啊，使用场景是代码编辑器，focus 后可以级联选择一些内置的表达式

**Comment by xrkffgg** [comment]
可以试试 给 Input 加自己的 键盘事件 看看
