### ISSUE TITLE
antd 4 Form 设置 preserve={false} 和 initialValues ，关闭抽屉之后再打开，Form.List 的值被初始化成空对象数组 

### ISSUE THREAD

**Issue by Qiuhang817385** [ant-design/ant-design#31897]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-zeng-jian-qian-tao-zi-duan-antd-4-16-13-forked-q3o3i?file=/index.js)

### Steps to reproduce
表单这是 preserve={false} 属性
点击按钮打开抽屉，再关闭，再打开，发现值被清成空对象

### What is expected?
每次打开抽屉都是 initialValue

### What is actually happening?
第二次打开抽屉之后值是空对象

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.8 |
| System | windows |
| Browser | chorm 88 |

---
4.11.x 的版本没有这个问题

**Comment by Qiuhang817385** [comment]
import React, { useState } from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Form, Input, Button, Space, Drawer } from "antd";
import { MinusCircleOutlined, PlusOutlined } from "@ant-design/icons";

const FLComponent = ({ form, user }) => {
  const { getFieldValue } = form;
  const value = getFieldValue(["users"]);

  console.log(value, user);

  return (
    <Form.List name="users">
      {(fields, { add, remove }) => (
        <>
          {fields.map(({ key, name, fieldKey, ...restField }) => (
            <Space
              key={key}
              style={{ display: "flex", marginBottom: 8 }}
              align="baseline"
            >
              <Form.Item
                {...restField}
                name={[name, "first"]}
                fieldKey={[fieldKey, "first"]}
                rules={[{ required: true, message: "Missing first name" }]}
              >
                <Input placeholder="First Name" />
              </Form.Item>
              <Form.Item
                {...restField}
                name={[name, "last"]}
                fieldKey={[fieldKey, "last"]}
                rules={[{ required: true, message: "Missing last name" }]}
              >
                <Input placeholder="Last Name" />
              </Form.Item>
              <MinusCircleOutlined onClick={() => remove(name)} />
            </Space>
          ))}
          <Form.Item>
            <Button
              type="dashed"
              onClick={() => add()}
              block
              icon={<PlusOutlined />}
            >
              Add field
            </Button>
          </Form.Item>
        </>
      )}
    </Form.List>
  );
};

const FormDemo = () => {
  const [visible, setVisible] = useState(false);
  const [form] = Form.useForm();
  const [user, setUser] = useState([]);
  return (
    <>
      <Button
        onClick={() => {
          setUser([
            {
              first: "张",
              last: "三"
            }
          ]);
          setVisible(true);
        }}
      >
        点击
      </Button>
      <Drawer
        title="Basic Drawer"
        placement="right"
        closable={false}
        onClose={() => {
          setVisible(false);
        }}
        visible={visible}
        destroyOnClose={true}
      >
        <Form
          preserve={false}
          name="dynamic_form_nest_item"
          form={form}
          initialValues={{
            users: user || [
              {
                first: undefined,
                last: undefined
              }
            ]
          }}
        >
          <FLComponent user={user} form={form} />
        </Form>
      </Drawer>
    </>
  );
};

ReactDOM.render(<FormDemo />, document.getElementById("container"));

**Comment by Qiuhang817385** [comment]
![image](https://user-images.githubusercontent.com/38211706/130736865-bde69223-ea11-4b6c-928c-caa1dafff73c.png)
![image](https://user-images.githubusercontent.com/38211706/130736882-f3d306d1-51b5-4456-9a56-95b4d6f06f10.png)

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/28561

**Comment by zombieJ** [comment]
你的示例看起来是好的？
