### ISSUE TITLE
TableTransfer

### ISSUE THREAD

**Issue by IgorM-Oliveira** [ant-design/ant-design#31891]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[TableTransfer](https://codesandbox.io/s/table-transfer-antd-4-16-13-forked-h2xjo?file=/index.js)

### Steps to reproduce
- The problem is in searching other columns than the name
When I search for the description no results come up 

### What is expected?
As far as I understand, the general search field has to fit all columns and rows of a table regardless of how many columns and rows there are

### What is actually happening?
When I do the search nothing comes back

### Any additional comments? (optional)
could do the search regardless of whether or not there are uppercase or lowercase letters

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Linux Kubunto |
| Browser | Chrome 92.0.4515.159 |

**Comment by afc163** [comment]
It is a example, you can improve it as your need.

https://codesandbox.io/s/table-transfer-antd-4-16-13-forked-rknkt
