### ISSUE TITLE
Ability to get column title on render and onCell methods

### ISSUE THREAD

**Issue by ArcSecant** [ant-design/ant-design#31893]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I require an editable table with dynamic columns based on weeks. Some cells might need to be not editable but if they are before a certain date, so I need the column title for that.

### What does the proposed API look like?
`render` and `onCell` takes in a new parameter which gives column details, i.e.
onCell: function(record, rowIndex, column)

**Comment by afc163** [comment]
`render` and `onCell` is properties of column, you can use specified column info in column.onCell for each column.
