### ISSUE TITLE
Accessibility: Modal组件切换title到时候不能重新读title

### ISSUE THREAD

**Issue by cYang2030** [ant-design/ant-design#31894]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当我使用Modal处理流程逻辑的时候，Modal中会有几个步骤，比如步骤一是一个弹窗，步骤二是一个弹窗，但是现在更好的体验是放在一个弹窗中，去修改弹窗的内容，比如title和content以及button这些东西，但是弹第一个弹窗的时候会读title的内容，但是我们希望第一步切换到第二步的时候，title也能读出来。

### What does the proposed API look like?
满足Accessibility需求

**Comment by afc163** [comment]
能给个重现的例子么，关于『希望第一步切换到第二步的时候』现在是如何读不出来？

**Comment by cYang2030** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-wxx7c

当我点击show modal的时候屏幕阅读器会读“basic modal dialog”，这里是没问题的

当我点击modal上面的next按钮的时候，我modal切换到下一个场景，同时title改成了next modal，但是此时屏幕阅读器没有读“next modal dialog”

当然现在没有读其实也是合理的，毕竟目前还是在同一个modal里面。不过如果能够读出来会不会更好呢

**Comment by afc163** [comment]
你可能需要手动重现 focus 到 title 元素上，让阅读器重读一遍 title。

**Comment by cYang2030** [comment]
这个一般事如何进行focus的啊，可以帮忙demo上添一点么，感谢
