### ISSUE TITLE
DatePicker 在 iPhoneX，iPhone12 中点开日期面板，再点空白处，会导致页面刷新

### ISSUE THREAD

**Issue by lyggxd** [ant-design/ant-design#31895]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/date-picker-cn/](https://3x.ant.design/components/date-picker-cn/)

### Steps to reproduce
iPhoneX 打开 ant design 的 demo，点开 DatePicker ，打开日期面板，点击空白处

### What is expected?
点开 DatePicker ，打开日期面板，点击空白处可以正常收起面板，页面不刷新

### What is actually happening?
点开 DatePicker ，打开日期面板，点击空白处，页面就会刷新，多试几次会因为重复报错崩溃

| Environment | Info |
|---|---|
| antd | 3.26.19 |
| React | 16.13.1, 16.2.0 |
| System | iOS 14 |
| Browser | Safari |

---
React 16.13.1 和 16.2.0 是我在项目中用的版本，不确定 antd 的 Demo 页用的是什么版本的 React

**Comment by dyyliao123** [comment]
有解决吗
