### ISSUE TITLE
固定列阴影显示问题

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#31898]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
仍然是#31319类似的问题，我的场景是可以动态设置显示的列，当显示的列减少至不需要横向滚动条时，仍然存在与#31319一样的阴影显示问题。
![image](https://user-images.githubusercontent.com/50108232/130753616-6a382c46-9714-4b87-8069-d32428ebfbdb.png)

我是用的antd版本为4.16.13。确认下该问题在哪个版本中解决了。如果未解决，在这里再次提及一下。

### What does the proposed API look like?
正常显示

**Comment by adaex** [comment]
I found this problem should belong to the upstream library `rc-table`.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/table/pull/663
