### ISSUE TITLE
表单中的Upload.Dragger设置了rules，但是label中不出现红色必填星号*

### ISSUE THREAD

**Issue by hello991107** [ant-design/ant-design#31896]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
      <FormItem label={label}>
        <FormItem name={dataIndex} valuePropName="fileList"  noStyle rules={rules}>
          <Upload.Dragger name="files" action="/upload.do">
            <p className="ant-upload-drag-icon">
              <img src=""/>
            </p>
            <p className="ant-upload-text">{uploadText}</p>
            <p className="ant-upload-hint">{requireText}</p>
          </Upload.Dragger>
        </FormItem>
      </FormItem>

### What is expected?
label出现必填标志

### What is actually happening?
label缺少红色必填星号标志

| Environment | Info |
|---|---|
| antd | 4.10.1 |
| React | 16.14.0 |
| System | ios |
| Browser | google |

**Comment by afc163** [comment]
rules 和 label 在同一级才会生效，不在同一级则需要手动指定 required 属性。
