### ISSUE TITLE
Select 没有重置已选的api

### ISSUE THREAD

**Issue by xujihui1985** [ant-design/ant-design#319]
没有重置select的api
当我想通过api的方式重置已选内容时，不知改如何重置

**Comment by afc163** [comment]
用 value 。

**Comment by wjx8382** [comment]
@afc163 
```
<Select value={this.state.value} style={{ width: 120 }}>
    <Option value="jack">Jack</Option>
    <Option value="lucy">Lucy</Option>
    <Option value="disabled" disabled>Disabled</Option>
    <Option value="yiminghe">yiminghe</Option>
</Select>
```
```
_handleClick() {
    this.setState({
        value: ''
    })
}
```
#### 我点击按钮重置以后，选择的就不能显示了，value一直是''了
![image](https://cloud.githubusercontent.com/assets/6300935/14626766/fffae354-0620-11e6-9916-e6ece6464ffe.png)

**Comment by benjycui** [comment]
@wjx8382 认真学习受控组件的概念 https://facebook.github.io/react/docs/forms.html#controlled-components
