### ISSUE TITLE
官网示例bug

### ISSUE THREAD

**Issue by wznonstop** [ant-design/ant-design#3190]
#### 发生问题的环境是：

- antd 版本:
![image](https://cloud.githubusercontent.com/assets/9294582/18908221/5bb2790a-85a1-11e6-8e54-a6322d4ffe17.png)

- 操作系统及其版本:
  
![image](https://cloud.githubusercontent.com/assets/9294582/18907993/7320e74e-85a0-11e6-86c0-a31cb6e21963.png)

- 浏览器及其版本:
![image](https://cloud.githubusercontent.com/assets/9294582/18908031/99bac938-85a0-11e6-95b8-8a3eb90968d7.png)

#### 您做了什么？

查看官网示例

#### 您期待的结果是：

应该看不到下面那层的滚动条
![image](https://cloud.githubusercontent.com/assets/9294582/18908111/f082cf54-85a0-11e6-9a2c-ecdcd4d1c7d0.png)

#### 实际上的结果是：

![image](https://cloud.githubusercontent.com/assets/9294582/18908153/17050bf6-85a1-11e6-9841-211eb3e68167.png)

#### 可重现的在线演示

http://ant.design/components/table/#components-table-demo-grouping-columns

**Comment by benjycui** [comment]
一样的环境，没有重现。

是 100% 可重现的么？

**Comment by afc163** [comment]
呃，感觉是楼主的屏幕很宽，没有出现横向滚动条的缘故。@benjycui 可以减少中间的列数来重现。

**Comment by wznonstop** [comment]
又发现了一个新的问题，在下面框选的部分滚动的时候，滚到最下面会错位：
![image](https://cloud.githubusercontent.com/assets/9294582/18910550/0ee966ba-85ab-11e6-98f7-ffed2451b8d2.png)
错位了：
![image](https://cloud.githubusercontent.com/assets/9294582/18910593/494272ca-85ab-11e6-8f78-eb24382e52ed.png)

**Comment by wznonstop** [comment]
我的电脑上不进行滚动时滚动条还在，拿同事电脑看了一下，他的是不进行滚动时滚动条就不会出现，结果又看到了一个应该是bug的情形，就是有两个横向滚动条：
![image](https://cloud.githubusercontent.com/assets/9294582/18910738/f092441a-85ab-11e6-9962-60a9e22b7b12.png)

这个情况应该普遍存在，两个同事电脑上都出现了。

**Comment by benjycui** [comment]
像固定表头那样默认展示滚动条对齐？ cc @afc163 

![image](https://cloud.githubusercontent.com/assets/3580607/18944647/379e89ba-8659-11e6-97da-7e6e2560aa59.png)

**Comment by afc163** [comment]
对，只能这样。

**Comment by wznonstop** [comment]
还看到了几个偶发性bug：
http://note.youdao.com/noteshare?id=debc3cda00d5a3572b4b52f8a00b60fd

**Comment by benjycui** [comment]
@wznonstop 我们这儿是打不开有道的。。

**Comment by agoni1212** [comment]
![image](https://cloud.githubusercontent.com/assets/22545824/18994968/cb12da8a-875c-11e6-8909-e84807c040ef.png)

![image](https://cloud.githubusercontent.com/assets/22545824/18995010/ea27d966-875c-11e6-986f-b942046bb8cd.png)


IE 10 上更离谱

![image](https://cloud.githubusercontent.com/assets/22545824/18995044/16dce46a-875d-11e6-9d44-d8b4a1051cc8.png)

**Comment by wznonstop** [comment]
我把有道的内容复制过来了：
    1. 偶发性bug1:
![image](https://cloud.githubusercontent.com/assets/9294582/19210050/559959b6-8d4a-11e6-948b-f2ff2ee37efa.png)
有时横向滚动时，固定列的阴影没有加上。这个bug的复现率很高。

   2. 偶发性bug2:
![image](https://cloud.githubusercontent.com/assets/9294582/19210055/779d54b8-8d4a-11e6-9fbe-9a2b6e6d8e91.png)
进行上下或左右滚动时，固定列头的列未跟随内部的内容滚动：
[不跟随滚动bug.zip](https://github.com/ant-design/ant-design/files/517412/bug.zip)

这个bug的出现需要契机。。。

   3. 技术实现方案导致的冲突问题：折叠展开和固定列头不可并存:
![image](https://cloud.githubusercontent.com/assets/9294582/19210063/ce8d3f9a-8d4a-11e6-8f73-a88d04965599.png)

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

---

能重现出来才好解决，否则我们就像盲人摸象。

**Comment by ddcat1115** [comment]
@agoni1212 你的第一个图是因为横向距离足够，不用出滚动条，但又配置了scroll-x和fixed left/right，去掉scroll相关的应该就对了。。。。其他的没法重现~

**Comment by afc163** [comment]
@ddcat1115 :+1:
