### ISSUE TITLE
Enhance Pagination onChange API

### ISSUE THREAD

**Issue by Maikel-Nait** [ant-design/ant-design#31912]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, *Pagination* **onChange** API gets only triggered when the page number or *pageSize* changes. 
However, it does not get triggered when the number of total pages gets updated. 

In my use case, users can **manually add** rows to a table. So far, when the number of rows reaches the current *pageSize+1*, a new page is displayed on the *Pagination* component. That's fine. However, the table itself does not automatically **advance** to the newly created page number, so newly added rows cannot be seen, unless users manually click on the new page link. or change the page size. 

The enhacement would be to improve / add a *Pagination* **onChange** API that would be triggered when the total number of pages gets updated, (for example when the number of pages gets increased from 1 to 2), so that we could read what is the newest page available, and update the **current** page property to the newly created one, in a controlled manner.

### What does the proposed API look like?
```onChange(page, pageSize, pagesCount)```   
```onPagesCountChange(pagesCount)```

**Comment by PeachScript** [comment]
I think the parent component should handle the total size changes and update `pagination.total` config for the `Pagination` component.

For the `pagination` config, the parent component is a provider and the `Pagination` component is a consumer, we cannot make `Pagination` component mange an internal `pagination.total` then reverse pass, it voilates [React’s **one-way data flow** principle](https://reactjs.org/docs/thinking-in-react.html).

**Comment by Maikel-Nait** [comment]
Ok I got it... I've managed to do it. But we need to keep state of total/pageSize/currentPage and change it in several places to keep it consistent. Looks like a lot of work, just to "auto-advance" the page when adding/removing table rows manually. Maybe the Table or Pagination component could have a simple option like "autoAdvancePage" that could save us some work.
