### ISSUE TITLE
Upload上传图片成功后，再删除报错

### ISSUE THREAD

**Issue by cherylxiao** [ant-design/ant-design#3191]
#### 发生问题的环境是：

- antd 版本: 2.0.0
- 操作系统及其版本: Windows 7
- 浏览器及其版本: Chrome 53.0.2785.116 m

#### 您做了什么？
引入了antd的Upload , listType为'picture-card'，使用Upload组件上传图片成功后，再执行删除操作

#### 您期待的结果是：

正常删除图片
#### 实际上的结果是：

报异常：Uncaught TypeError: Cannot read property 'abort' of undefined

**Comment by benjycui** [comment]
在本地试这个例子，没有重现 http://ant.design/components/upload/#components-upload-demo-picture-card

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
