### ISSUE TITLE
Tree组件 loadData加载数据，手动设置默认展开项，会执行两次loadData

### ISSUE THREAD

**Issue by zhupp034** [ant-design/ant-design#31935]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-16-13-forked-r39zv)

### Steps to reproduce
页面加载完成，看loadData输出次数

### What is expected?
展开每一级，只执行一次loadData

### What is actually happening?
展开每一级，执行了2次loadData

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | window 10 |
| Browser | chrome 90.0.4430.212 |

![image](https://user-images.githubusercontent.com/33925263/131068742-a2d96edb-0cb1-424d-a91f-8aabfd5e8972.png)

**Comment by PeachScript** [comment]
> ### Reproduction link
> 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-16-13-forked-r39zv)

macOS 11.2.3 + Chrome 92/Firefox 91 使用复现链接无法复现

**Comment by zhupp034** [comment]
> > ### Reproduction link
> > [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-16-13-forked-r39zv)
> 
> macOS 11.2.3 + Chrome 92/Firefox 91 使用复现链接无法复现
> <img alt="图片" width="571" src="https://user-images.githubusercontent.com/5035925/131207913-7084cab4-140c-4046-b4d9-14781f6b94ba.png">

![image](https://user-images.githubusercontent.com/33925263/131317360-9b2926ce-2f1b-43cf-9904-0ba92503b8ef.png)

代码后面动了，现在复原了，你再看下

**Comment by fissssssh** [comment]
same problem. 
`console.log` can not log anything at second call, and I used another way to reappear it.
<iframe src="https://codesandbox.io/embed/yi-bu-shu-ju-jia-zai-antd-4-17-0-alpha-0-forked-c29s3?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="异步数据加载 - antd@4.17.0-alpha.0 (forked)"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

when u expand the node, and throw an error.

**Comment by fissssssh** [comment]
anyone here?

**Comment by zombieJ** [comment]
> same problem.
> `console.log` can not log anything at second call, and I used another way to reappear it.
> 
> [![Edit 异步数据加载 - antd@4.17.0-alpha.0 (forked)](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-17-0-alpha-0-forked-c29s3?fontsize=14&hidenavigation=1&theme=dark)
> 
> when u expand the node, and throw an error.
> 
> Chrome 92.0.4515.159
> @zhupp034

Your promise forget to return:
https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-17-0-alpha-0-forked-2cmt1?file=/index.js

**Comment by fissssssh** [comment]
> > same problem.
> > `console.log` can not log anything at second call, and I used another way to reappear it.
> > [![Edit 异步数据加载 - antd@4.17.0-alpha.0 (forked)](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-17-0-alpha-0-forked-c29s3?fontsize=14&hidenavigation=1&theme=dark)
> > when u expand the node, and throw an error.
> > Chrome 92.0.4515.159
> > @zhupp034
> 
> Your promise forget to return:
> https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-17-0-alpha-0-forked-2cmt1?file=/index.js
thanks, solved!
