### ISSUE TITLE
2.0版本 使用 DatePicker 提示 Cannot find module "antd/lib/DatePicker/style/css"

### ISSUE THREAD

**Issue by tyua07** [ant-design/ant-design#3195]
#### 发生问题的环境是：

- antd 版本: 2.0.0
- 操作系统及其版本:macOS
- 浏览器及其版本:chrome  53.0.2785.116 (64-bit)

#### 您做了什么？

```

import { Form, Input, Row, Col, Button, DatePicker } from 'antd';

```

#### 您期待的结果是：

和官网演示的一样！

#### 实际上的结果是：

我使用 ``` DatePicker ``` 组件的时候，就爆出这个错误！

```

Cannot find module "antd/lib/DatePicker/style/css"

```

**Comment by afc163** [comment]
`https://unpkg.com/antd@2.0.0/lib/date-picker/style/css.js` 文件路径是这个。

babel-plugin-import 的配置是怎么写的？

**Comment by tyua07** [comment]
你好，这个是我 ``` .babelrc ``` 的配置


```

"plugins": [["import", {
		"style": 'css',
		"libraryDirectory": "lib",  // default: lib
		"libraryName": "antd",
		"camel2DashComponentName": false, // default: true
	}]]

```

**Comment by afc163** [comment]
你为啥要设这个：`camel2DashComponentName`？

去掉即可。

**Comment by tyua07** [comment]
好了，非常感谢！

我按照 [babel-plugin-import](https://github.com/ant-design/babel-plugin-import) 配置来的，没有注意到这个参数，抱歉！

**Comment by afc163** [comment]
我把误导你的演示代码改掉了：https://github.com/ant-design/babel-plugin-import/commit/dbe17bbcc99201af5dd5adf40b3a16c2c2fba4d6
