### ISSUE TITLE
Tab to Complete - Mentions Component

### ISSUE THREAD

**Issue by thekennysong** [ant-design/ant-design#31953]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently a user must press enter or click an option to autocomplete.

### What does the proposed API look like?
OnKeyPress tab event must be captured and then trigger the autocomplete function.

**Comment by PeachScript** [comment]
Maybe the [`backfill`](https://ant.design/components/auto-complete-cn/#API) property is what you want, it same as the native autocomplete logic of most browsers

**Comment by zombieJ** [comment]
Close since no more info.
