### ISSUE TITLE
Upload component is short of generic declaration

### ISSUE THREAD

**Issue by EugeneJao** [ant-design/ant-design#31960]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-uovvo?file=/index.tsx)

### Steps to reproduce
compile the txs file

### What is expected?
compile successfully

### What is actually happening?
get a compile error "Expected 0 type arguments, but got 1.  TS2558"

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macos |
| Browser | chrome |

---
use Upload component with typescript

**Comment by EugeneJao** [comment]
Upload.d.ts line 9 
```typescript
declare const Upload: CompoundedComponent
```

**Comment by zombieJ** [comment]
Generic is meaningless for Upload since browser do not support extend File object. Could you provide more about your use case?

**Comment by zombieJ** [comment]
Close since not more response
