### ISSUE TITLE
collapse-demo-collapsible

### ISSUE THREAD

**Issue by edrmsgl** [ant-design/ant-design#31969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hello there,

Do you have a feature for the https://ant.design/components/collapse/#components-collapse-demo-collapsible component that can expand and collapse just by clicking the "DownOutlined" icon?

The version we are using is 4.9.2. If we upgrade, can we use the feature we want?

### What does the proposed API look like?
---

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/31039#issuecomment-908298432
