### ISSUE TITLE
Image 组件预览点击图片或右上角的旋转放大会触发 Table 的 onRow 的 onClick

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#31963]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-16-13-forked-dpymk)

### Steps to reproduce
1、点击图片预览
2、点击图片或者右上角旋转、放大缩小。
3、查看控制台打印

### What is expected?
不应该触发 Table 的事件

### What is actually happening?
触发了 Table onRow 的 onClick

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/30502#issuecomment-840441056
