### ISSUE TITLE
 scrollto function of antd4.x can not  scroll to the target place

### ISSUE THREAD

**Issue by NBB96** [ant-design/ant-design#31968]
### What problem does this feature solve?
 scrollto function of antd4.x can  scroll to the target place

### What does the proposed API look like?
in the case , when i search the city , i hope the tree scrolls to the target place  (scrollto already after expandedKeys)

![image](https://user-images.githubusercontent.com/50286829/131316915-3a33470d-517a-4bde-b388-b5ffcebcbb9d.png)
<img width="881" alt="BD3CAC2F-7FA7-41C1-AA49-0CA988B4F717" src="https://user-images.githubusercontent.com/50286829/131317241-263cfaf6-e404-4151-90dc-1a17ec46f081.png">

**Comment by NBB96** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-h0xsf?file=/index.js

**Comment by afc163** [comment]
你的例子搜索时直接卡死了。

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/30264#issuecomment-844791307

**Comment by NBB96** [comment]
> 你的例子搜索时直接卡死了。

https://codesandbox.io/s/antd-reproduction-template-forked-h0xsf?file=/index.js:114038-114043

**Comment by NBB96** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-h0xsf?file=/index.js  我优化了下 现在不会卡死了

**Comment by NBB96** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-h0xsf?file=/index.js 我优化了下 现在不会卡死了

@afc163
