### ISSUE TITLE
官网中Form表单/多表单联动 onFinish方法中获取不到users的值，只能用form.getFieldValue('users')获取

### ISSUE THREAD

**Issue by busyzz-1994** [ant-design/ant-design#31967]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/form-cn/#components-form-demo-form-context](https://ant-design.gitee.io/components/form-cn/#components-form-demo-form-context)

### Steps to reproduce
1.点击AddUser按钮添加用户
2.点击Submit按钮提交
3.在onFinish方法拿到的values中没有users这个字段，只能通过form.getFieldValue('users')获取

### What is expected?
可以在onFinish方法中将users字段合并到values当中

### What is actually happening?
onFinish方法中返回的values里面拿不到users字段

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome 78  |

**Comment by afc163** [comment]
这是两个表单，a 表单的值和 b 表单不会混在一起。
