### ISSUE TITLE
Unable to customize hover/active text colors in .ant-btn-link component

### ISSUE THREAD

**Issue by a-revan** [ant-design/ant-design#31962]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Unable to customize hover/active text color in .ant-btn-link component

### What does the proposed API look like?
Please add the following less variables:
@btn-link-hover-color
@btn-link-active-color

**Comment by afc163** [comment]
See https://codesandbox.io/s/an-niu-lei-xing-antd-5-6-2-forked-jk4zsd?file=/demo.tsx
