### ISSUE TITLE
Select组件使用maxTagCount和allowClear时，会换行

### ISSUE THREAD

**Issue by Nuibia** [ant-design/ant-design#31972]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/xiang-ying-shi-maxtagcount-antd-4-16-13-forked-k55vl?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
开启allowClear，使用maxTagCount，选择select的两个option，select内部换行，不使用allowClear样式没有问题
![在这里插入图片描述](https://img-blog.csdnimg.cn/750779f0bcf440e4ab65a56c3bc80526.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBASG9uZ2ZlaUFu,size_11,color_FFFFFF,t_70,g_se,x_16#pic_center)

### What is expected?
固定了选择器的宽度，选择了两个option，不换行，出现响应式 maxTagCount 样式

### What is actually happening?
当选择其中两个属性时，select中的内容发生了换行

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | mac 11.4 |
| Browser | chrome 92.0.4515.159 |

**Comment by afc163** [comment]
计算上应该有问题。

**Comment by zombieJ** [comment]
右边那个空白是 `allowClear` 的删除按钮区域：
<img width="255" alt="截屏2021-09-02 上午11 06 06" src="https://user-images.githubusercontent.com/5378891/131775218-f0d08f25-617e-487a-879d-13da5fcf73e3.png">

选项 和 搜索之间的 margin 把它顶了下去。
<img width="264" alt="截屏2021-09-02 上午11 07 23" src="https://user-images.githubusercontent.com/5378891/131775325-aaaeb726-db61-4936-8d0d-b43db79c8cf6.png">
