### ISSUE TITLE
scrollto function of antd4.x can not scroll to the target place

### ISSUE THREAD

**Issue by NBB96** [ant-design/ant-design#31975]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
scrollto function of antd4.x can scroll to the target place

### What does the proposed API look like?
in the case , when i search the city , i hope the tree scrolls to the target place (scrollto already after expandedKeys)
code url https://codesandbox.io/s/antd-reproduction-template-forked-h0xsf?file=/index.js
![image](https://user-images.githubusercontent.com/50286829/131452865-9108e9b1-2e6a-4cb8-9f81-7962df0dd5c5.png)
![image](https://user-images.githubusercontent.com/50286829/131452889-caa263cf-682f-4461-9fc3-ebbdb9224a1f.png)

**Comment by zombieJ** [comment]
It's harder than I tought. Need more time to resolve this.

**Comment by zombieJ** [comment]
`+ rc-tree@5.0.3`

**Comment by NBB96** [comment]
> `+ rc-tree@5.0.4`
has the antd been updated?
