### ISSUE TITLE
congrats with release of 2.0!

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3197]
I remember your answer when (this winter) i asked about english version :) And now we finally have it! 

It's superb! Congrats all and everyone! :)

**Comment by afc163** [comment]
🍻

**Comment by afc163** [comment]
Here is your issue https://github.com/ant-design/ant-design/issues/1033 about 8 months ago. 😃

**Comment by plandem** [comment]
yep! actually i still can't believe :) because right now we have english docs + typescript! and it takes only 8 months to get here :)

**Comment by kvetoslavnovak** [comment]
Big congratulation to all!!!

The residual issues are here https://github.com/ant-design/ant-design/issues/3200

(form closed https://github.com/ant-design/ant-design/issues/1471)
