### ISSUE TITLE
Able to not closing overlay when clicking on Menu.Item in Dropdown.Button

### ISSUE THREAD

**Issue by Kulakoff1988** [ant-design/ant-design#31971]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If i provide, for example, a toggler, I want to toggle it without overlay component closing in Dropdown. All is awesome in Dropdown.Button component, but only this limitation doesn't give me a chance to use it instead making own component.

### What does the proposed API look like?
For example, it could be optional property in Dropdown.Button (may be in Dropdown too) `closeOnItemClick`, which will `true` by default

**Comment by afc163** [comment]
https://ant.design/components/dropdown-cn/#components-dropdown-demo-overlay-visible

**Comment by Kulakoff1988** [comment]
> https://ant.design/components/dropdown-cn/#components-dropdown-demo-overlay-visible

Thanks!!))))

**Comment by Kulakoff1988** [comment]
> https://ant.design/components/dropdown-cn/#components-dropdown-demo-overlay-visible

but it's not what I want> I want to keep closing overlay on outside click, but in your example it's impossible.
