### ISSUE TITLE
Form submit useEffect run twice

### ISSUE THREAD

**Issue by xiaohuoz** [ant-design/ant-design#31973]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-biao-dan-lian-dong-antd-4-16-13-forked-umnh9?file=/index.js:626-632)

### Steps to reproduce
第一次点击提交按钮onFinish执行一次，useEffect却执行了两次，之后再点击就正常都执行一次了

### What is expected?
都应该只执行一次

### What is actually happening?
可以看下log里的执行情况

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 18.0.0-a |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
第一次点击 submit

```js
    setVisible1(values);  // 有变化，从 1 变成 values，触发 useEffect
    setVisible12(values + 1);  // 有变化，从 1 变成 "[object Object]1"，触发 useEffect
```

第二次点击 submit

```js
    setVisible1(values);  // 有变化，从老的 values 变成新的 values，触发 useEffect
    setVisible12(values + 1);  // 无变化，依然是 "[object Object]1"，不触发 useEffect
```

这个结果是合理的。

**Comment by xiaohuoz** [comment]
> 第一次点击 submit
> 
> ```js
>     setVisible1(values);  // 有变化，从 1 变成 values，触发 useEffect
>     setVisible12(values + 1);  // 有变化，从 1 变成 "[object Object]1"，触发 useEffect
> ```
> 
> 第二次点击 submit
> 
> ```js
>     setVisible1(values);  // 有变化，从老的 values 变成新的 values，触发 useEffect
>     setVisible12(values + 1);  // 无变化，依然是 "[object Object]1"，不触发 useEffect
> ```
> 
> 这个结果是合理的。

感谢解答
但是触发两次使用上太糟糕了，目前项目中只能不使用onFinish，直接绑定在Button的onClick上了。详见

https://codesandbox.io/s/duo-biao-dan-lian-dong-antd-4-16-13-forked-umnh9?file=/index.js
