### ISSUE TITLE
this.getOptions is not a function

### ISSUE THREAD

**Issue by GeorGeWzw** [ant-design/ant-design#31976]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/GeorGeWzw/Sukt.ETLDataFlow.Dashboard](https://github.com/GeorGeWzw/Sukt.ETLDataFlow.Dashboard)

### Steps to reproduce
yarn install 
yarn start 启动就报错

### What is expected?
解决报错

### What is actually happening?
TypeError: this.getOptions is not a function

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | win10 |
| Browser | edge |

---
./node_modules/antd/dist/antd.less (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-8-3!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-8-4!./node_modules/style-resources-loader/lib??ref--5-oneOf-8-5!./node_modules/antd/dist/antd.less)
TypeError: this.getOptions is not a function

**Comment by afc163** [comment]
https://segmentfault.com/a/1190000039190699
https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function
https://blog.csdn.net/qq_42430948/article/details/113552673

It is not a antd issue.
