### ISSUE TITLE
DatePicker ref typing is wrong

### ISSUE THREAD

**Issue by acfasj** [ant-design/ant-design#31985]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://github.com/acfasj/antd-date-picker-ref-type

### Steps to reproduce
1. clone the repo and install deps `git clone git@github.com:acfasj/antd-date-picker-ref-type.git && cd antd-date-picker-ref-type && yarn`
2. go to the `src/App.tsx` file
3. assign a callback ref to ref attribute, the parameter of the callback called `picker`
4. wanna get intellisense type hint like `picker.focus()` as document describes, but we got `any` type here

### What is expected?
can get intellisense type hint on ref like `picker.focus()`  as  https://ant.design/components/date-picker/#Common-Methods describes

### What is actually happening?
no type hint for ref instance methos

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS Catalina 10.15.7 |
| Browser | chrome 86.0.4240.80（正式版本） (x86_64) |

**Comment by afc163** [comment]
Your codesandbox is not a TypeScript project.

**Comment by acfasj** [comment]
> Your codesandbox is not a TypeScript project.

already provided the [git repo](https://github.com/acfasj/antd-date-picker-ref-type) and updated the issue. 

however, the result is the same as codesandbox. although I dont know how codesandbox typescript projects work online, but it seems to be a valid typescript project
