### ISSUE TITLE
FormItem value with hidden attribute are not available in onFinnish 

### ISSUE THREAD

**Issue by hassam7** [ant-design/ant-design#31986]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-x53vt?file=/index.js)

### Steps to reproduce
1. Visit the page
2. Open the browser's console.
3. Type something in the input box.
4. Hit on Submit button

### What is expected?
I should be able to see the following in console:
{username: "hello", hiddenToken: "someHiddenValue"}

### What is actually happening?
The value for hidden field is undefined whereas it should be "someHiddenValue" instead of undefined.
{username: "hello", hiddenToken: undefined}

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | latest/17 |
| System | MacOS Big Sur |
| Browser | Chrome 91 |

---
hidden input fields are used to pass data to backend sometimes they contain XSRF token. According to document https://ant.design/components/form/#Form.Item the values of hidden should be validate and should be present when submitting the form

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-2z4c2?file=/index.js

**Comment by hassam7** [comment]
Thanks for the solution. it would be great if we could an example for hidden field in the documentation
