### ISSUE TITLE
提供关闭tooltip、popover、dropdown组件的全局方法

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design#31981]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果页面上有iframe，点击iframe里面的页面无法关闭外层的dropdown、popover、tooltip等组件。只能通过点击iframe页面向外发事件去查找.ant-dropdown-open的dom节点去触发click事件来关闭，但是这种做法有一些局限性，希望ant-design能提供一个全局方法关闭所有已经显示的dropdown等组件。

### What does the proposed API look like?
未想好

**Comment by PeachScript** [comment]
这个逻辑很奇怪…两种建议解法：

1. 用 [qiankun](https://github.com/umijs/qiankun) 替代 iframe
2. 点 iframe 的时候把事件手动触发到外层的 window 上

**Comment by semdy** [comment]
我目前就是使用的第二种方法，但是有很大的局限性。iframe里是一个第三方应用不太好使用qiankun代替。
