### ISSUE TITLE
能否在treeSelect中添加滚动定位功能

### ISSUE THREAD

**Issue by linzhaoyang** [ant-design/ant-design#31983]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在tree结构中，经常会有比较多的部门与人，当有审核类的需求需要选择审批人不能选择部门却要显示部门树时，列表会很长。默认展开了所在部门后，为了方便（审批人可以在本部门也可以在其他部门，没有固定的审批流），在点击输入框的时候，需要滚动定位到所在部门的位置，但是不选中某个人，方便快速看到审批人去选中。

### What does the proposed API look like?
像类似scrollTo这样的方法，可以调用滚动到想要的位置。期望可以通过useRef/Form.useForm这类方法去调用组件内部实例的方法。

**Comment by PeachScript** [comment]
个人认为在数据层面默认把审批人所在的部门放在第一条比 `scrollTo` 更合理

**Comment by afc163** [comment]
https://github.com/react-component/tree-select/pull/298
