### ISSUE TITLE
Menu item will be automatically active highlighted When used with popover or tooltip or popconfirm (Menu Item 在和 popover 或者 popconfirm 之类的东西一起使用的时候会自动高亮)

### ISSUE THREAD

**Issue by y805939188** [ant-design/ant-design#31984]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nei-qian-cai-dan-antd-4-16-13-forked-3rg82?file=/index.js)

### Steps to reproduce
menu 组件中使用 menuitem，然后 item 外边包一层 popover 或 popconfirm 或 tooltip

### What is expected?
item 不会自动高亮

### What is actually happening?
item 会自动高亮

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
不指定 eventKey 相当于 `eventKey={undefined}`，这样和 Menu 上的 defaultSelectedKeys={undefined} 就匹配上了。建议始终指定 eventKey。https://codesandbox.io/s/nei-qian-cai-dan-antd-4-16-13-forked-8vonr?file=/index.js
