### ISSUE TITLE
文档中 DatePicker不支持clearIcon参数 但是实际是支持的

### ISSUE THREAD

**Issue by wxj0102** [ant-design/ant-design#31992]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5enb8?file=/index.js)

### Steps to reproduce
文档没有关于clearIcon的描述但是实际是支持的

### What is expected?
修复文档

### What is actually happening?
实际程序支持clearIcon属性

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 18.0.0 |
| System | windows10 |
| Browser | chrome |

---
这是文档的链接
https://ant-design.gitee.io/components/date-picker-cn/

**Comment by wxj0102** [comment]
冒昧问一下 是考虑到不想让大版本号变化所以才有这种操作吗

**Comment by zombieJ** [comment]
倒不是大版本，是每个版本都需要考虑 API Naming Standard。

antd 底层是 rc 组件，和用户隔离，所以 API 可以根据设计需求一直变化，但是到了顶层 antd 透出就需要严格按照 [Naming Standard](https://github.com/ant-design/ant-design/wiki/API-Naming-rules) 来走。以防止错误的接口放出去收不回来。

虽然可以做兼容，但是在重构的时候就会遇到为了兼容导致一些原本可以提升性能的改动无法实施。

**Comment by zombieJ** [comment]
嗯，对的。只是现在 rc 也换成了 TS 后有些上层没有 Omit 干净结果就在自动提示里漏出来了。

**Comment by zombieJ** [comment]
先 close 了~
