### ISSUE TITLE
Swtich component bug

### ISSUE THREAD

**Issue by AlgoLovers** [ant-design/ant-design#31999]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/switch/](https://ant.design/components/switch/)

### Steps to reproduce
When you click on a white round part in Text & Icon Example, it will not be normal operation.

The representation as the GUI is normal operation, but 'onChange' is an abnormal.

If you want to confirm, do console.log(event.target.innertext)

### What is expected?
When you click the round part and the stick, I would like to receive the same event.

### What is actually happening?
If you select a round part, an unusual event is passed.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.8.6 |
| System | ubuntu 20.04 |
| Browser | chrome(92.0.4515.159) |

**Comment by xiaohuoni** [comment]
Swtich 的 onChange 事件返回的是当前的 value 值，而不是 event ，所以打印 `console.log(event.target.innertext)` 会报错，是正常行为吧？
