### ISSUE TITLE
组件中的HTML结构是 React.render 出来的

### ISSUE THREAD

**Issue by zlart** [ant-design/ant-design#32]
您们好！
问题：
如果我再写好的html结构中，如何在引用antd-0.1.0-beta1.js后，可以使用ant.design提供的组件？我发现组件中的HTML结构是 React.render 出来的。

说明：
之前一直用你们的kissy，如今发现很多demo页面链接错误了。
发现了你们这个新的框架。非常感谢！
我的问题时很弱智，由于我乐视网是做设计的，但会写点HTML做些专题页面。引用你们的kissy库就可以使用一些组件。现在ant框架没有html结构的组件实例。

**Comment by yiminghe** [comment]
```js
 <script src="https://a.alipayobjects.com/??es5-shim/4.0.5/es5-shim.js,es5-shim/4.0.5/es5-sham.js,html5shiv/3.7.2/src/html5shiv.js,react/0.13.3/react.js,react/0.13.3/JSXTransformer.js"></script>

<div id="container"></div>
<script type="text/jsx">
    // Your code here
</script>
```

将 html 结构写在 React.render 参数上
