### ISSUE TITLE
validate 在 chrome/ie 下报错

### ISSUE THREAD

**Issue by transtone** [ant-design/ant-design#320]
http://ant.design/components/validation/ 这里的例子复制出来测试，firefox下可以，但在chrome和ie下跑不通。

https://gist.github.com/transtone/ff4db7749a682d492945

**Comment by transtone** [comment]
是不是bug，有朋友帮忙确认一下的吗？

**Comment by afc163** [comment]
https://gist.github.com/transtone/ff4db7749a682d492945#file-test-html-L67
https://gist.github.com/transtone/ff4db7749a682d492945#file-test-html-L107

并不是 bug，这里使用了 ES6 语法，浏览器兼容性不一，建议使用 babel 进行打包后使用。
