### ISSUE TITLE
2.0 English Translation Residual Issues

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#3200]
Here is the list of residual issues:
### Local Provider 
LocalProvider en_US (http://ant.design/components/locale-provider/ ) probably not used correctly  to render English components especially in 
-  [x]  <del>Pagination Changer, Jumper, Mini size, Total numner http://ant.design/components/pagination/</del>
-  [x]  <del>DatePicker http://ant.design/components/date-picker/</del>
-  [x]  <del>TimePicker http://ant.design/components/time-picker/</del>
-  [x]  <del>Calendar http://ant.design/components/calendar/</del>
-  [x]  <del>Popconfirm http://ant.design/components/popconfirm/</del>
-  [x]  <del>Table http://ant.design/components/table/</del>
-  [x]  <del>Modal http://ant.design/components/modal/</del>
-  [x]  <del>Transfer http://ant.design/components/transfer/</del>

### Example Code texts
-  [x]  <del>Calendar Custom Render, Demo of Notice http://ant.design/components/calendar/<\del>
-  [ ]  <del>Transfer en_US Local Provider uses  源列表 and 目的列表 instead of "Source list" and "Target list" http://ant.design/components/transfer/</del>
-  [x]  <del>http://ant.design/components/dropdown/ - all examples</del>
-  [x]  <del>http://ant.design/components/mention/ - Controlled example</del>
-  [x] <del>http://ant.design/components/modal/ - Basic, Asynchronously close, Confirmation modal dialog, Manual to destroy and To customize the position of modal
 examples</del>
-  [x] <del> http://ant.design/components/popconfirm/ - Basic, Placement, Conditional trigger examples</del>
-  [x] <del> http://ant.design/components/popover/ - all examples</del>
-  [x]  <del>http://ant.design/components/table/ - data in all examples<\del>
-  [x]  <del>http://ant.design/components/timeline/ - all examples</del>
-  [x] <del>http://ant.design/components/steps/ - all examples</del>

Original Translation Project https://github.com/ant-design/ant-design/issues/1471

**Comment by xueqingxiao** [comment]
@kvetoslavnovak Popconfirm's localProvider & demo's has been  translated.

**Comment by xueqingxiao** [comment]
@kvetoslavnovak 
Popover #3211

**Comment by kvetoslavnovak** [comment]
I hope to finish the Table and Calendar tommorrow.

**Comment by kvetoslavnovak** [comment]
Closing, the last issue has its own PR https://github.com/ant-design/ant-design/pull/3264
