### ISSUE TITLE
when input component add the allowClear attribute, hoping to monitor the clear event

### ISSUE THREAD

**Issue by lihaixing** [ant-design/ant-design#32008]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When searching in the search box, I only want to trigger the search by clicking the search button or the clear button

### What does the proposed API look like?
add the onClear event

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16862#issuecomment-507616942

**Comment by li-jia-nan** [comment]
Support in #49905
