### ISSUE TITLE
Input does not accept spaces when used in TabPane's "tab" prop

### ISSUE THREAD

**Issue by xiaoyic-juniper** [ant-design/ant-design#32002]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-17-0-alpha-0-forked-k45zk?file=/index.js)

### Steps to reproduce
Type space in the input box in the tab title, the space is not shown

### What is expected?
The input should accept spaces

### What is actually happening?
Space is not added to the input field, and it has some strange behavior like typing more than one space will add the spaces but the cursor does not move. BTW this issue is not seen in antd version 3

| Environment | Info |
|---|---|
| antd | 4.8.5 |
| React | 16.13.1 |
| System | MacOS Big Sur 11.5.2 |
| Browser | Chrome Version 92.0.4515.159 (Official Build) (x86_64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31403#issuecomment-880550940
