### ISSUE TITLE
Select labelInValue属性在Option内容中有空格的情况下会返回数组. 比如<Option> {'lucy'}</Option>

### ISSUE THREAD

**Issue by cc20140820** [ant-design/ant-design#32009]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-wn6lkt?file=index.js](https://stackblitz.com/edit/react-wn6lkt?file=index.js)

### Steps to reproduce
分别选中select 的第一个和第二个option，发现console打印出的label属性一个是array 一个是string

### What is expected?
期望空格不会导致label属性返回数组，而是字符串。

### What is actually happening?
空格会导致label属性返回数组

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome |

---
只有{}情况下才会出现，比如<Option> {'lucy'}</Option>情况下，label属性会返回[" ", "lucy"] ，在<Option> lucy</Option>情况下，label属性能正常返回“ lucy”

**Comment by afc163** [comment]
这是预期行为，会把 children 原样返回，不会做多余隐式转换。
