### ISSUE TITLE
ant.design offline?

### ISSUE THREAD

**Issue by ddispaltro** [ant-design/ant-design#3201]
It appears ant.design github pages publish failed...

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/3175 It seems that some DNS cache the old IP for ant.design 

You can try to modify you hosts file until DNS update cache:

```bash
47.88.240.14 ant.design
```

**Comment by ddispaltro** [comment]
Great. works, thanks.  Yeah I can't read #3175 =)
