### ISSUE TITLE
Table within Modal coming out of the modal

### ISSUE THREAD

**Issue by rashmimh** [ant-design/ant-design#32010]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-antd-4-17-0-alpha-0-forked-vhxz2?file=/index.js)

### Steps to reproduce
1. Add modal
2. Add Table in modal
(refer codesandbox for code)

### What is expected?
Table should not be coming out of the modal width

### What is actually happening?
Table content is coming out of the modal

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | Mac |
| Browser | Chrome 92.0.4515.131 (Official Build) (x86_64) |

![css_fix](https://user-images.githubusercontent.com/53742137/131821440-7f77b778-1e8d-4054-ac20-b34c351fe09a.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/customized-filter-panel-antd-4-17-0-alpha-0-forked-rfv3b?file=/index.js
