### ISSUE TITLE
Table固定列阴影显示错误

### ISSUE THREAD

**Issue by kkkisme** [ant-design/ant-design#32014]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-zhan-kai-antd-4-17-0-alpha-0-forked-lf1qn?file=/index.js)

### Steps to reproduce
1、调整页面宽度，保证表格右固定列没有阴影 
2、保证页面纵向不出现滚动条
3、点击展开行按钮，使页面出现纵向滚动条（如果高度不够，可以多展开几行）
4、右固定列出现了多余的阴影

### What is expected?
右固定列没有阴影

### What is actually happening?
右固定列出现了多余的阴影

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16 |
| System | win 7 |
| Browser |  92.0.4515.159 |

**Comment by kkkisme** [comment]
#31319 与这个问题类似，但最新版（4.17.0-alpha.2）依旧存在问题

**Comment by afc163** [comment]
这是一个特殊情况，需要系统开启始终滚动条才能重现。

1. 一开始页面没有垂直滚动条，表格宽度撑开到 100%。
2. 点击展开，表格超过一屏，页面出现垂直滚动条。
3. 由于垂直滚动条会占据位置（大概 15px 到 20px 不等），会使表格宽度被挤压。
4. 表格宽度不足，自适应出现 scroll 横向滚动条，同时阴影出现。

因为 3 的情况，浏览器内容宽度被改变，但是这种情况不会触发 window resize 事件，因此 table 无法感知。

这个情况比较特殊，而且没有好的解法，从逻辑上其实也是对的（横向空间不够出现滚动条），就不修了。

**Comment by mytharcher** [comment]
另外一个 typo，css 的类名应该是 `pin-left`/`pin-right` 吧。

**Comment by afc163** [comment]
@mytharcher 确实是 typo
