### ISSUE TITLE
React peer dependency issues

### ISSUE THREAD

**Issue by aaronbalthaser** [ant-design/ant-design#32017]
I tried to follow the developer instructions to run the project and I get peer dependency issues. Is this going to be fixed?

### Reproduction link
[http://no-link-its-just-a-question-about-npm-install](http://no-link-its-just-a-question-about-npm-install)

### Steps to reproduce
clone project and do npm install

### What is expected?
it to work

### What is actually happening?
it doesn't work

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | React Ant Design |
| Browser | None |

---
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: antd@4.16.13
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR! dev react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from @ant-design/hitu@0.0.0-alpha.16
npm ERR! node_modules/@ant-design/hitu
npm ERR! dev @ant-design/hitu@"^0.0.0-alpha.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/aaron/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/aaron/.npm/_logs/2021-09-02T11_48_37_217Z-debug.log

**Comment by afc163** [comment]
@zombieJ Need a release of @ant-design/hitu

**Comment by Rain120** [comment]
@afc163 
It makes me cannot install at local, so fail the test in local.
![image](https://user-images.githubusercontent.com/20939839/131963748-66caa153-4466-4133-88eb-8ebbe551f7f6.png)
