### ISSUE TITLE
InputNumber 组件 addonBefore、addonAfter ts报错

### ISSUE THREAD

**Issue by transitiongo** [ant-design/ant-design#32025]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
随便找个ts项目都可以

### What is expected?
ts类型修复正确

### What is actually happening?
ts报错

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | "react": "^17.0.2", |
| System | mac os  |
| Browser | chrome |

---
 <InputNumber addonBefore=" " addonAfter="$" defaultValue={100} />

**Comment by transitiongo** [comment]
![image](https://user-images.githubusercontent.com/26265969/131966329-14cdbbbf-5bce-4cc4-9408-20dc643e9a7c.png)

**Comment by transitiongo** [comment]
![image](https://user-images.githubusercontent.com/26265969/131969542-99525f34-a752-4581-bf4e-ca24c14e00ed.png)

查到原因了 4.17.0-alpha.0 才支持的能力
https://www.npmjs.com/package/antd/v/4.17.0-alpha.0

**Comment by zombieJ** [comment]
文档里有写版本号哈~~

**Comment by stonyme** [comment]
![image](https://user-images.githubusercontent.com/21095021/132473254-e37f37af-5766-4c33-8970-89627347ee2f.png)
请把文档补充完整

**Comment by afc163** [comment]
@stonyme 欢迎来个 PR~
