### ISSUE TITLE
config menu component to not fold

### ISSUE THREAD

**Issue by kevinwang89** [ant-design/ant-design#32029]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The default submenu is folded, you click it, it unfolds. I want the sub menu unfold by default, I can not find this kind of setting in the current menu api

### What does the proposed API look like?
add a `foldSubMenu` config  so user can set `true` or `false`

**Comment by kevinwang89** [comment]
`menu.itemGroup` will suit this case better

**Comment by afc163** [comment]
See `openKeys`.
