### ISSUE TITLE
点击Dropdown里的MenuItem未触发onVisibleChange事件

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design#32024]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/chu-fa-fang-shi-antd-4-17-0-alpha-0-forked-l7dqh?file=/index.js)

### What is expected?
点击Dropdown内部也可触发visibleChange事件

### What is actually happening?
未触发

| Environment | Info |
|---|---|
| antd | undefined |
| React | react 16.13.1 |
| System | win10 x64 |
| Browser | chrome 90 |

**Comment by zombieJ** [comment]
设计如此。因为通过 `onMenuItemClick` 可以区分出这次消失是点击导致，反之一并触发就无法推断出消失原因。我文档里加一下。
