### ISSUE TITLE
Performance between click and response

### ISSUE THREAD

**Issue by 3amathia** [ant-design/ant-design#32023]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/estebanmathia42/CloudPrice](https://github.com/estebanmathia42/CloudPrice)

### Steps to reproduce
Create any dropbox

### What is expected?
Reactive button

### What is actually happening?
Button very slow to react

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 0.65 |
| System | Blazor |
| Browser | 78.0.4093.184 (opera) |

---
Hello, I have a performance problem: I use antDesign in my blazor application and locally no problem the buttons are very reactive but with the site deployed on the internet the buttons are not as reactive. At first I thought it was the latency between the server and me but when I changed the NuGet package to another I could see that the buttons of the new package were just as responsive locally as online. Can you please tell me when it is possible to have a difference between the 2 packages?

**Comment by afc163** [comment]
Wrong place to report issue.
