### ISSUE TITLE
Time Range Picker dropdown misalign

### ISSUE THREAD

**Issue by marklai1998** [ant-design/ant-design#32026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/18364699/131973300-50d3ac53-1ff0-4467-9568-bbdafae6647f.png)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/time-range-picker-antd-4-17-0-alpha-0-forked-v90w2?file=/index.js)

### Steps to reproduce
click the end time slot with format='HH:mm'

### What is expected?
the dropdown should move with the tooltip pointer

### What is actually happening?
tooltip pointer moved, but the dropdown does not

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Mac 11.2.3 |
| Browser | chrome 92.0.4515.159 |

**Comment by zombieJ** [comment]
Keep Dropdown stable is by design. But the arrow position is not correct which should fix.

**Comment by HelloBojack** [comment]
> Keep Dropdown stable is by design. But the arrow position is not correct which should fix. @zombieJ 

HH:mm:ss
![image](https://user-images.githubusercontent.com/39325783/132004291-b2aea3aa-1d55-4e77-bb64-9bd8323832e9.png)
HH:mm
![image](https://user-images.githubusercontent.com/39325783/132004355-97991339-7b29-4eca-ae72-316c67c5e4df.png)
HH
![image](https://user-images.githubusercontent.com/39325783/132004382-2f52e5ff-6e25-44aa-96d1-a780a35cb39c.png)

请问 HH:mm 的样式应该如何修改？

**Comment by marklai1998** [comment]
> > Keep Dropdown stable is by design. But the arrow position is not correct which should fix. @zombieJ
> 
> HH:mm:ss
> ![image](https://user-images.githubusercontent.com/39325783/132004291-b2aea3aa-1d55-4e77-bb64-9bd8323832e9.png)
> HH:mm
> ![image](https://user-images.githubusercontent.com/39325783/132004355-97991339-7b29-4eca-ae72-316c67c5e4df.png)
> HH
> ![image](https://user-images.githubusercontent.com/39325783/132004382-2f52e5ff-6e25-44aa-96d1-a780a35cb39c.png)
> 
> 请问 HH:mm 的样式应该如何修改？

個人認為應該跟HH吧
根本不夠闊

**Comment by marklai1998** [comment]
any follow up??

**Comment by Sadman211** [comment]
Is there any update on this issue?

**Comment by afc163** [comment]
<img width="428" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/59022327-bca4-4794-b0ca-6a85865a3d09">

https://codesandbox.io/s/time-range-picker-antd-4-17-0-alpha-0-forked-q4l6rq?file=/index.js
