### ISSUE TITLE
[Question] Setting className with ref on Select

### ISSUE THREAD

**Issue by x1mrdonut1x** [ant-design/ant-design#32030]
### What problem does this feature solve?
I would like to programatically add/remove a class to `<Select />` via a React.useRef hook.

Is this possible?

### What does the proposed API look like?

```
// JSX
<Select ref={ref}>
  <Select.Option value="1">Hello</Select.Option>
</Select>

// JS
const onClick = () => {
  ref.current.className = 'goodbye';
}

```

**Comment by afc163** [comment]
You could set className to Select as a property.
