### ISSUE TITLE
Tree组件 loadData加载数据，手动设置默认展开项，会执行两次loadData

### ISSUE THREAD

**Issue by zhupp034** [ant-design/ant-design#32037]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-16-13-forked-r39zv)

### Steps to reproduce
页面加载完成，看loadData输出次数

### What is expected?
展开每一级，只执行一次loadData

### What is actually happening?
展开每一级，执行了2次loadData

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | window 10 |
| Browser | chrome 90.0.4430.212 |

![image](https://user-images.githubusercontent.com/33925263/131068742-a2d96edb-0cb1-424d-a91f-8aabfd5e8972.png)

上个问题被错误关闭了，又重新提了这个

**Comment by afc163** [comment]
Is it this comment resolve your question?

https://github.com/ant-design/ant-design/issues/31935#issuecomment-912466634

**Comment by zhupp034** [comment]
> Is it this comment resolve your question?
> 
> [#31935 (comment)](https://github.com/ant-design/ant-design/issues/31935#issuecomment-912466634)

没有解决，和下面那个不是同一个问题，被错误关闭了
