### ISSUE TITLE
Select 组件选项分组 OptGroup 支持 Tabs 视图？

### ISSUE THREAD

**Issue by theprimone** [ant-design/ant-design#32046]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
增强易用性，当存在多个分组或者分组内选项过多时，用户在可见区域内不清楚有多少分组。

当前展示效果

![image](https://user-images.githubusercontent.com/18096089/132201362-5e28c2a6-7481-42f5-8c20-a372b08dab75.png)

期望下拉弹窗支持如下类似的效果

![image](https://user-images.githubusercontent.com/18096089/132201463-e57a75ed-6189-4e42-881c-c1047ca4103a.png)

### What does the proposed API look like?
`groupType: "list" | "tabs"  // default: "list"`

**Comment by zombieJ** [comment]
感谢你的建议，但是 Select 这块交互暂时不会更改。建议自行实现对应设计。

**Comment by theprimone** [comment]
自定义 dropdownRender，使用 rc-select 中的 OptionList 组件再结合 antd Select 组件源码，实现了如下效果：
![image](https://user-images.githubusercontent.com/18096089/132787257-a612c80b-3136-4e58-82c3-5fbd7470824c.png)

才发现了 Select 组件内部逻辑有点复杂，另外 Select 组件源码中关于 type="combobox" 没有移除。
