### ISSUE TITLE
webpack 合并文件时出现警告错误: Cannot resolve 'file' or 'directory' ./locale

### ISSUE THREAD

**Issue by zhangchen2397** [ant-design/ant-design#3204]
- antd 版本: 2.0.0
- 操作系统及其版本: OS X 10.11.6
- 浏览器及其版本: chrome 53.0.2785.116

引入 `antd` 通过 `webpack` 打包合并文件时，控制台出现警告：

```
WARNING in ./~/antd/dist/antd.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in /Users/samzhang/work/monitor/node_modules/antd/dist
 @ ./~/antd/dist/antd.js 14479:17-44
```

倒是不影响使用，看了下原因，引入 `monent` 模块所致，`require('./locale/' + name);`

```javascript
function loadLocale(name) {
  var oldLocale = null;
  // TODO: Find a better way to register and load all the locales in Node
  if (!locales[name] && (typeof module !== 'undefined') &&
    module && module.exports) {
    try {
      oldLocale = globalLocale._abbr;
      require('./locale/' + name);
      // because defineLocale currently also sets the global locale, we
      // want to undo that for lazy loaded locales
      locale_locales__getSetGlobalLocale(oldLocale);
    } catch (e) {}
  }
  return locales[name];
}
```

**Comment by benjycui** [comment]
可以把整个 trace 贴出来？

**Comment by benjycui** [comment]
就是这个 error 的完整版：

```bash
WARNING in ./~/antd/dist/antd.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in /Users/samzhang/work/monitor/node_modules/antd/dist
 @ ./~/antd/dist/antd.js 14479:17-44
```

**Comment by benjycui** [comment]
然后使用 `babel-plugin-import` 后应该就没这个问题了。

**Comment by afc163** [comment]
https://github.com/webpack/webpack/issues/198#issuecomment-104688430

**Comment by pillys** [comment]
我也遇到同样的问题，请问解决了吗？ @benjycui

**Comment by zhangchen2397** [comment]
@afc163 done
thanks

**Comment by Morphexe** [comment]
I am still having this issue using babel-import-module, or using the @afc163  solution, am I missing something obvious?

This is only happening on my release config, I can debug it fine.

**Comment by afc163** [comment]
感觉已构建文件应该提前处理掉这个问题。

**Comment by afc163** [comment]
总结一下，此问题出现在 `antd@2.0.0` 和 `antd@2.0.1` 中。

https://github.com/ant-design/ant-design/commit/d063ed4dca501efcd0c313eab385d84015e83cd2 里修复了 `antd/dist/antd.js` 里的 require ，antd@2.0.1 之后的一个版本将解决这个问题。

在新版本发布之前，解决方案有两个：

1.  正确使用 [babel-plugin-import](https://github.com/ant-design/babel-plugin-import) 可以避免这个问题。
2. 使用 [noParse](https://webpack.github.io/docs/configuration.html#module-noparse) 避免 webpack 解析 `antd/dist/antd.js`也可以。

**Comment by webliving** [comment]
有同样的问题(已经解决),  另外还有个问题 antd 已经分离到 dll 文件中了, 但打包时不能依然打包了 antd ? 有谁知道吗? (webpack 3.x)
