### ISSUE TITLE
form 组件点击提交后，然后点击 reset 出现抖动

### ISSUE THREAD

**Issue by Eviwang** [ant-design/ant-design#32060]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-control-hooks](https://ant.design/components/form-cn/#components-form-demo-control-hooks)

### Steps to reproduce
https://ant.design/components/form-cn/#components-form-demo-control-hooks

### What is expected?
期望不抖动

### What is actually happening?
出现抖动

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | windows |
| Browser | 93.0.4577.63 |

**Comment by Eviwang** [comment]
![form 抖动](https://user-images.githubusercontent.com/9146097/132295213-b10566fd-803a-4448-8b3a-9bb4dd16ef04.gif)

**Comment by Dreamcreative** [comment]
这是ant故意这么做的还是确实是个bug ? 我调试了之后，发现form-item 刚开始 是有一个 margin-bottom：24px; ,但是当 红色的提示文字出现后， form-item的 margin-bottom 就变成了 提示文字容器的height。当 reset后，提示文字消失，这里就有一个 由height到margin-bottom属性的一个转变，而ant 在这里使用了一个 0.3s的 过渡 transition: margin-bottom 0.3s 0.017s linear; ，用来转变。
如果确定这是一个bug，而不是特意这么做的，请回复。
谢谢！

**Comment by afc163** [comment]
看上去是同一个问题：#27746

**Comment by zombieJ** [comment]
css 动画过渡和 js 过渡有 1 frame 的时间差，已经用了一些小数点 px 来减少抖动。感觉在下个大版本也可以考虑一下是否还是要继续支持 `margin-bottom: 0` 的用法，否则一直都会遇到它。

**Comment by yakushstanislav** [comment]
A very annoying bug on long forms. Is there a quick fix?

**Comment by afc163** [comment]
Duplicate of #27746
