### ISSUE TITLE
建议 Collapse 能增加 panelStyle 属性

### ISSUE THREAD

**Issue by chenxiaochun** [ant-design/ant-design#32061]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以更灵活的控制 Collapse 组件的 Panel 样式。就像类似于 Card 和 Modal 组件中的 bodyStyle 属性一样

### What does the proposed API look like?
```tsx
<Collapse.Panel key="1" header="test" panelStyle={{ padding: 0 }}>
  content
</Collapse.Panel>
```

**Comment by chenxiaochun** [comment]
原来 rc-collapse 中也没有暴露出来这个属性。我给那边提 PR 了

**Comment by xrkffgg** [comment]
@chenxiaochun 关联的 PR 写一下~

**Comment by chenxiaochun** [comment]
https://github.com/react-component/collapse/pull/223。是不是有哪些检查没有过去？

**Comment by afc163** [comment]
为啥不是 style？

**Comment by chenxiaochun** [comment]
是应该写成 style 更好一些

**Comment by afc163** [comment]
style 现在貌似已经是支持的，你看看能不能满足需求？
