### ISSUE TITLE
Reopening - Select virtual scroll last item not visible #31321

### ISSUE THREAD

**Issue by Mohamed-Ghanem** [ant-design/ant-design#32071]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/option-group-antd-4-16-6-forked-fbx05?file=/index.js)

### Steps to reproduce
1. Scroll down to the end of the select dropdown.
2. Look for the last item 'mag', it will be invisible.

### What is expected?
When scrolling down, last item 'mag' should be visible at the end of the list.

### What is actually happening?
When scrolling down, last 1 or 2 items are hidden, **even without adding listItemHeight**.

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14 |
| System | 16.14 |
| Browser | Version 90.0.4430.93 (Official Build) (x86_64) |

---
Link to closed issue which need to be reopened and reinvestigated as many users mentioned it was not fixed and still need to be readdressed:
https://github.com/ant-design/ant-design/issues/31321

I tried listItemHeight found in FAQ but it did't fix the problem.
https://ant.design/components/select/#Why-sometime-customize-Option-cause-scroll-break

Is there a way or workaround to style or add margins to list item without messing with the scroll?
Or is it a must to have the same height for all items including paddings and margins?

I also tried with normal select without grouping and it had the same issue:
https://codesandbox.io/s/select-with-search-field-antd4166-forked-pjzl8?file=/index.js

**Comment by zombieJ** [comment]
`rc-virtual-list` do not include `margin` as part of item size for the perf consideration.  In your case, label can use ReactNode instead:

https://codesandbox.io/s/option-group-antd-4-16-6-forked-y9693?file=/index.js

**Comment by Mohamed-Ghanem** [comment]
Hi @zombieJ, Thank you for your prompt response.

I will check your example and try to implement it and get back to you with the result.
In the meantime, kindly let the issue open till we verify it.

**Comment by zombieJ** [comment]
@Mohamed-Ghanem , is that ok?

**Comment by Mohamed-Ghanem** [comment]
Works like a charm.
Thank you @zombieJ.
