### ISSUE TITLE
Button groups

### ISSUE THREAD

**Issue by CPPtrueCoder** [ant-design/ant-design#32077]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A found documentation for using [button groups](https://ant.design/docs/spec/buttons#Button-Group). And then i go to the components , there you change size of buttons supported radio buttons , you use Radio.Group, but this is contrary to what is written in the documentation. There aren't spacing between radio-buttons.

### What does the proposed API look like?
Maybe you can fix this problem ?

**Comment by CPPtrueCoder** [comment]
Also , when i try using Radio.Group with RadioButtons , i have two buttons with class ant-design-button-checked , but i need only one button
```
<Radio.Group >
          <Radio.Button >Все</Radio.Button>
          <Radio.Button >Понравившиеся</Radio.Button>
 </Radio.Group>

```

**Comment by afc163** [comment]
There is no Button Groups in ant design specification, don't use it.

**Comment by CPPtrueCoder** [comment]
What ? I open Components => Radio , there are Radio.Group . It's official documentation !

**Comment by CPPtrueCoder** [comment]
I hope , that you don't understand my question . But also in radio buttons doesn't work checking parameter, all buttons rendering with "checked" but it isn't true

**Comment by afc163** [comment]
Radio.Group is not Button Group, it is different UI component.

**Comment by CPPtrueCoder** [comment]
Okay, my mistake, but it doesn't change that Radio.Group isn't working now. All buttons checked , but only one need to check default. I used all parameters from specification, and all button checked.

**Comment by CPPtrueCoder** [comment]
Okay, i fixed it, but toogle class according the value -- i think it's unintuitive
