### ISSUE TITLE
tagRender和maxTagCount同时使用时 ` +2...` tag 无法 使用 tagRender 

### ISSUE THREAD

**Issue by chen-jingjie** [ant-design/ant-design#32072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-xuan-ze-biao-qian-antd-4-17-0-alpha-0-forked-1m0iy?file=/index.js)

### Steps to reproduce
如上
![image](https://user-images.githubusercontent.com/35401187/132332212-34f42b5a-e685-4dfe-a496-7c7ce7b71017.png)

### What is expected?
tagRender和maxTagCount同时使用时 ` 2...` tag 能够使用 tagRender 

### What is actually happening?
tagRender和maxTagCount同时使用时 ` 2...` tag 无法 使用 tagRender 

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | macOS Big Sur 版本 11.2.1 |
| Browser | 92.0.4515.131（正式版本） (x86_64) |

**Comment by chen-jingjie** [comment]
是的，将它作为新的需求也说的通。我核心诉求是 select 里面的 tag 都能被自定义，这样才能使风格统一。至于他以何种颜色来渲染这属于业务逻辑，组件提供自定义渲染能力就行了。辛苦了。

**Comment by zombieJ** [comment]
嗯，看了一下的确两个 render 也不太好复用。
