### ISSUE TITLE
样式修改后，宽度动态无限延伸

### ISSUE THREAD

**Issue by helen123456** [ant-design/ant-design#32087]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/29134290/132456114-99ec8445-2cff-44df-bc71-13a83ff4a57e.png)

**Comment by helen123456** [comment]
看到有同样问题的同仁的动态图片，借用一下
![2](https://user-images.githubusercontent.com/29134290/132457373-656ed1c2-9ed9-418f-b017-88ebdaa2f710.gif)

**Comment by zombieJ** [comment]
@helen123456 提供一下重现哈~
