### ISSUE TITLE
Table sort buttons are not accessible

### ISSUE THREAD

**Issue by kpustakhod** [ant-design/ant-design#32092]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Try to use the keyboard to navigate to a sort column header in a table and trigger the sorting.

### What is expected?
You should be able to use the keyboard key to navigate to the sort column header and use the spacebar or key to toggle the sorting.

### What is actually happening?
Icons up and down are svg icons wrapped with spans without tabindex, that is why they are not accessible

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | Mac |
| Browser | Chrome |

**Comment by timgrant-philly** [comment]
The company I work for has a team of platform developers who have the time, ability, and, budget to develop a fix for this issue, and can create a pull request, if this issue is accepted.

**Comment by afc163** [comment]
Duplicate of #31516

**Comment by lallmaier** [comment]
Why is this issue closed, it still does not work?
