### ISSUE TITLE
antd的Checkbox和RadioGroup在IE11中一些问题

### ISSUE THREAD

**Issue by strongwan** [ant-design/ant-design#3209]
#### 发生问题的环境是：

- antd 版本:
antd是1.X版本
- 操作系统及其版本:
win7 64位
- 浏览器及其版本:
IE11 64位

#### 您做了什么？
引入了antd的Checkbox和RadioGroup

#### 您期待的结果是：
像官网一样正常显示

#### 实际上的结果是：
Checkbox选中时勾选样式错位了，而Radio选中没效果

**Comment by benjycui** [comment]
样式没引入吧，排查一下。

**Comment by benjycui** [comment]
别一个可能是你样式覆盖了 antd 的样式。

**Comment by strongwan** [comment]
可是在IE10及火狐谷歌都没问题呢？

**Comment by benjycui** [comment]
Checkbox 是不居中。。

![image](https://cloud.githubusercontent.com/assets/3580607/18942379/27aeacc8-864b-11e6-9b2c-5f17e1d6ebad.png)

不过 Radio.Group 没有问题：

![image](https://cloud.githubusercontent.com/assets/3580607/18942401/56979c02-864b-11e6-9d07-fbd573fed881.png)

**Comment by afc163** [comment]
无法重现楼主的问题，有进一步截图或重现方式再开吧。

**Comment by wxqGitHub** [comment]
html 页面忘了添加声明了吧？  <!DOCTYPE html>

**Comment by wxqGitHub** [comment]
```<!DOCTYPE html>```
