### ISSUE TITLE
升级 antd 版本到 4.17.0-alpha.2，之后，组件库覆盖的antd主题色等变量失效了

### ISSUE THREAD

**Issue by aYangLi** [ant-design/ant-design#32091]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/32090](https://github.com/ant-design/ant-design/issues/32090)

### Steps to reproduce
// 覆盖 antd themes 所有变量写在这里
@import './color.less';

@primary-color: @blue-base;
@border-radius-base: 4px;
@height-base: 32px;
@input-hover-border-color: @blue-base;
@text-color: @black-90;

@table-header-bg: @bgColor-10;
@table-row-hover-bg: @bgColor-10;
@table-header-color: @black-70;
@table-footer-bg: @bgColor-10;

// Tooltip
// ---
// Tooltip max width
@tooltip-max-width: 350px;
@tooltip-bg: @black-90;

// Form
@form-item-margin-bottom: 20px;

### What is expected?
期望我们复写的全局样式生效

### What is actually happening?
复写的变量不生效，

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | mac |
| Browser | Chrome |

---
怀疑是不是 4.17.0-alpha.2 版本 增加 ant-design/components/style/themes/variable.less 功能影响的。麻烦跟进解决下，

**Comment by aYangLi** [comment]
之前使用的 4.16.3 版本是正常的，升级 4.17.0-alpha.2 版本出问题了

**Comment by aYangLi** [comment]
这个问题找出来了。我这边覆盖 @primary-color 的时候，用的是从另一个 less 引入的变量 @blue-base。换成 正常值 "#2a6df5"，就可以了。 试问，是不是不支持变量替换，只能准确值覆盖？

**Comment by zombieJ** [comment]
@aYangLi ，你是替换了入口样式文件还是什么？能提供一个 重现看看么？

**Comment by aYangLi** [comment]
> @aYangLi ，你是替换了入口样式文件还是什么？能提供一个 重现看看么？

这个是公司内部的组件库，没有demo。。项目本身是基于 antd 计划改一下，所以会设置一些 @primary-color @height-base 等less 变量覆盖 antd 原有的，但是现在4.17.0-alpha.2不生效了。。 原来 4.16.3 版本是可以的。

**Comment by aYangLi** [comment]
> @aYangLi ，你是替换了入口样式文件还是什么？能提供一个 重现看看么？

问题找出来了。这次把 覆盖样式的变量放到了 导出 less 文件 最末尾。 原来是放在 antd less 之后就可以。升级 4.17版本就出现了这个情况。 通过排查定位到：antd/es/descriptions/style/index.less 这个less ，你们可以看下这个里面有没有什么特殊操作，这个 issue 就关闭了
