### ISSUE TITLE
ConfigProvider.config({theme: mergedNextColor,}); Not Working!!

### ISSUE THREAD

**Issue by tolgayildizz** [ant-design/ant-design#32096]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5wcyh)

### Steps to reproduce
While the theme change can be done with config.provider() on the official site, it doesn't work anywhere else.

### What is expected?

While the theme change can be done with config.provider() on the official site, it doesn't work anywhere else. It doesn't work anywhere except the example on the official site I tried changing the react version and changing the antd version but it didn't work

### What is actually happening?

While we should be able to set theme settings with config.provider() this doesn't work at all

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/global-theme-antd-4-17-0-alpha-0-forked-5o1zo?file=/index.js
