### ISSUE TITLE
Badge is not getting rerendered for last item in the cart

### ISSUE THREAD

**Issue by Gogulaanand** [ant-design/ant-design#32099]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://website-cadppzp8p-gogulaanand.vercel.app](https://website-cadppzp8p-gogulaanand.vercel.app)

### Steps to reproduce
1. Goto https://website-cadppzp8p-gogulaanand.vercel.app/products
2. Add couple of items to cart
3. Goto https://website-cadppzp8p-gogulaanand.vercel.app/cart
4. Remove the items from cart
5. The badge count is not updated for final remove action

### What is expected?
The badge count should be set to 0

### What is actually happening?
It is showing the value that was there before we removed the last item

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS 11.5.2 (20G95) |
| Browser | Firefox v92 |

**Comment by zombieJ** [comment]
Pls provide simple code reproduce instead: https://u.ant.design/codesandbox

**Comment by Gogulaanand** [comment]
@zombieJ I was trying to reproduce it : https://codesandbox.io/s/antd-reproduction-template-forked-7u2qn?file=/badge.js
it is working fine in sandbox. working fine in my local as well.
**But**, not working after deploying to vercel !

I am aware it is not a bug exactly, but needed the help of people with expertise in antd to identify the issue :)

**Comment by Gogulaanand** [comment]
@zombieJ Sorry to bother, but any thoughts on this ? :)

**Comment by zombieJ** [comment]
@Gogulaanand, I'm not good at build tools. Maybe you can fire issue with next. Seems it's bundle issue.
