### ISSUE TITLE
Tooltip not hidding when used with trigger element

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#32105]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-trigger-114pq?file=/src/App.js)

### Steps to reproduce
Tooltip is working correctly when antd icons are used in button but it is not working correctly when using fontawesome icons (or maybe `<Icon />` element of `ant-design/icons`

**Correct Case**
  * Click on first button => Modal will open and tootip hides => Close Modal
 
**Wrong Case**
  * Click on second button => Modal will open and tootip doesn't hides => Close Modal

### What is expected?
Tooltip should hide

### What is actually happening?
Tooltip remains visible until I again hover on button after closing modal

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.1 |
| System | MacOS v10.15.7 |
| Browser | Firefox v91.0.2 |

---
Same issue is occurring when tooltip is used with `Popconfirm` or `Popover`

**Comment by zombieJ** [comment]
Icon `component` prop request Component but your code return as new FC each render which means `onMouseLeave` event will never fired since React Node is replace every time:

https://codesandbox.io/s/tooltip-trigger-forked-1zf6g?file=/src/FaIcon.js
