### ISSUE TITLE
The tooltip remains displayed when the loading property of a button with an icon and no text is set to true

### ISSUE THREAD

**Issue by vincentv** [ant-design/ant-design#32109]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loading-antd-4-17-0-alpha-0-forked-e8vvj?file=/index.js)

### Steps to reproduce
1. Hover the button to display the tooltip
2. Click on the button

### What is expected?
the loading should make the tooltip disappear

### What is actually happening?
the tooltip is still displayed

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | Arch Linux x86_64 (5.13.13-zen1-1-zen) |
| Browser | firefox-developer-edition 93.0b2-1 |

---
In a Tabs component, we have a button without text in a tab that opens another tab. The tooltip is still displayed above the new tab.

**Comment by zombieJ** [comment]
Tooltip support disabled button. It should support loading also. Seems a bug:

https://codesandbox.io/s/loading-antd-4-17-0-alpha-0-forked-p8krm?file=/index.js
