### ISSUE TITLE
defaultValue内部封装缓存了？

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3210]
用了多个InputNumber组件，defaultValue的值都是从state获取，但是发现更改一个InputNumber组件的值之后，所有组件的defaultValue的值都成了更改后的值，并没有从state获取

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by RifeWang** [comment]
因为跟数据都是连接到后台获取的，所以在线演示有点麻烦。。问题是这样的：
   <InputNumber   defaultValue={this.state.dataUpdate.data1}/>
   <InputNumber   defaultValue={this.state.dataUpdate.data2}/>
多个输入框组件，默认值是外层容器组件定义的state，改变了第一个输入框的值之后，第二个输入框的默认值变成了第一个输入框更改之后的值。。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by afc163** [comment]
不给重现无法定位问题，你的任务是把问题代码独立拆解出来。

**Comment by RifeWang** [comment]
好吧   不过我已经找到问题所在了
