### ISSUE TITLE
Documentation improvement - Form.Item messageVariables

### ISSUE THREAD

**Issue by Smoovsky** [ant-design/ant-design#32115]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To make the documentation less confusing

### What does the proposed API look like?
The current doc states [here](https://ant.design/components/form/#messageVariables) :
```jsx
<Form>
  <Form.Item messageVariables={{ another: 'good' }} label="user">
    <Input />
  </Form.Item>
  <Form.Item messageVariables={{ label: 'good' }} label={<span>user</span>}>
    <Input />
  </Form.Item>
</Form>
```

Something like:
```jsx
<Form>
  <Form.Item messageVariables={{ another: 'good' }} label="user" rules={[{required: true, message: '${another} is required'}]}>
    <Input />
  </Form.Item>
  <Form.Item messageVariables={{ label: 'good' }} label={<span>user</span>} rules={[{required: true, message: '${label} is required'}]}>
    <Input />
  </Form.Item>
</Form>
```
would make more sense

**Comment by DaoxingHuang** [comment]
@afc163  这个messageVariables 我没有get他的使用点,我自己也没有使用过 ，我简单的看了下源码，更觉得他是修改原message的模板变量，一旦你自定义的message，刚会失效；
例如：`   <Form>
          <Form.Item name="userName" messageVariables={{ name: 'good' }} label="user" rules={[{required: true ,}]}>
            <Input />
          </Form.Item>
          <Form.Item name="password" messageVariables={{ label: 'good' }} label={<span>user</span>} rules={[{required: true, message: '${label} is required'}]}>
            <Input />
          </Form.Item>
          <Form.Item >
            <Button type="primary" htmlType="submit">
              Submit
            </Button>
          </Form.Item>
        </Form>`
上面userName事例中，因为 rules中 required 没有设置message ,则使用默认的模板 '${name} is required' ,其中的模块 name 会被 item的属性 name 替换，则整个提示消息就是 userName is required, 又因为这里我设置messageVariables={{ name: 'good' }} ，即模板里面的 name, 刚 userName 会被 messageVariables替换，错误信息即变为  good is  required;   不知道 这样理解对不对；

当然 如果你自定义了 validateMessages ，效果也是一样的 ，例如这位同学的例子：
`       <Form validateMessages= {
            {  required: "'${another}' 是必选字段",
           }}>
          <Form.Item name="userName" messageVariables={{ another: 'good' }} label="user" rules={[{required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="password" messageVariables={{ label: 'good' }} label={<span>user</span>} rules={[{required: true, message: '${label} is required'}]}>
            <Input />
          </Form.Item>
          <Form.Item >
            <Button type="primary" htmlType="submit">
            Submit
            </Button>
          </Form.Item>
        </Form>`

因为这里的模板改成了 another  ，所以 自定义messageVariables变量名也要改成another，提示的信息就是  good is  required。

**Comment by DaoxingHuang** [comment]
![image](https://user-images.githubusercontent.com/19969260/133354189-6cfc45d4-aa3f-488f-8771-b52f3acf952b.png)

**Comment by 729993031** [comment]
这个是因为有些Form.Item是没有label的 但是做表单校验的时候需要使用label 通过这个属性我就可以免去自己写校验的麻烦了

**Comment by DaoxingHuang** [comment]
@729993031 可否提供一些比较详细的使用场景

**Comment by DaoxingHuang** [comment]
![image](https://user-images.githubusercontent.com/19969260/134760200-31e188ab-5079-46e5-9e7e-fa625c0e11f6.png)

**Comment by DaoxingHuang** [comment]
以上我是我个人认为 可用的场景

**Comment by 729993031** [comment]
![1632552762(1)](https://user-images.githubusercontent.com/13050361/134761980-dd78edce-64c6-47ef-82f3-8b7479866ec5.png)

**Comment by 729993031** [comment]
因为很多情况下产品要求是不能展示label这个属性给用户的，而antd需要使用到这个属性作为校验的提示， 通过传入messageVariables 可以避免我自己去写校验提示

**Comment by DaoxingHuang** [comment]
我看了你的例子，我想我跟你的理解是 一致的 ，即这个messageVariables 主要用于校验信息的验证；比如使用已经默认 name 或是重写vilidatemessage 重新设置验证模板

**Comment by DaoxingHuang** [comment]
@729993031

**Comment by 729993031** [comment]
嗯 是的 @DaoxingHuang

**Comment by DaoxingHuang** [comment]
@729993031 有个问题，你的第一个国家能取到label的信息？ 逻辑上 rule中存在message会被覆盖
![image](https://user-images.githubusercontent.com/19969260/134790731-eb7305c5-16c5-4fb7-bcb4-77f8d6ec7db2.png)
![image](https://user-images.githubusercontent.com/19969260/134790736-068fb792-a93e-421e-83c5-8ae9f994a294.png)

**Comment by 729993031** [comment]
我把label传到了messageVariables 里面去了 因为这里的国家是不允许显示label给用户的 我只是传递给rule做校验用

**Comment by 729993031** [comment]
我到现在才知道message是支持 "'${name}' 是必选字段" 这个语法的 我之前一直以为他只支持静态的语法， 我觉得这个可以通过在文档中注明或者引导一下用户

**Comment by DaoxingHuang** [comment]
> 我到现在才知道message是支持 "'${name}' 是必选字段" 这个语法的 我之前一直以为他只支持静态的语法， 我觉得这个可以通过在文档中注明或者引导一下用户

对的，支持 ，本质 就是代换内部的defaultValidateMessages 模板，不仅仅name,所以 默认message 中的模板值都可以替换
[默认的英语模板](https://github.com/ant-design/ant-design/blob/47d28e8f7003568592a480b1b3ce962a85075ece/components/locale/default.tsx#L81)

![image](https://user-images.githubusercontent.com/19969260/134801161-fe1c0e71-09ae-4fc7-8293-059802beda3c.png)

但现在对你这个例子的问题是 如果一定在 rules 里设置了 message ，其实 messageVariables里面的变量是不生效的 ，所以你的例子里的那个"国家" 是说message的，所以按现在的逻辑应该验证信息应该显示的是：”请选择‘${label}’“，而不是你例子里显示的 "请选择国家"，所以麻烦你再辛苦确认下。

或是托管下代码 ，我看下

**Comment by 729993031** [comment]
@DaoxingHuang https://codesandbox.io/s/cool-sea-f5xpg?file=/src/index.js

![1632666160(1)](https://user-images.githubusercontent.com/13050361/134811846-cb79c10e-1f7d-4475-81ad-9fe232efb003.png)
意思是说这个 请选择国家 这个提示语是错误的？

**Comment by DaoxingHuang** [comment]
> @DaoxingHuang https://codesandbox.io/s/cool-sea-f5xpg?file=/src/index.js
> 
> ![1632666160(1)](https://user-images.githubusercontent.com/13050361/134811846-cb79c10e-1f7d-4475-81ad-9fe232efb003.png)
> 意思是说这个 请选择国家 这个提示语是错误的？

好的 多谢。我看 下，主要是版本问题，我的是 4.16.13 ，这个版本是不正常的 ，最新的4.17.0-alpha.3是OK的

**Comment by DaoxingHuang** [comment]
![image](https://user-images.githubusercontent.com/19969260/134852625-cd5dbcf6-0b6e-45df-9205-608f41f93287.png)
你可以通过 `messageVariables` 修改 Form.Item 的验证信息，除了用户自定义 rule message 外，也可参考 [validateMessages](#validateMessages) 修改默认的配置信息。

```jsx
<Form>
  <Form.Item messageVariables={{ myVar: 'Cumstom Msg' }} name='userName' label="User Name" rules={[{required: true, message: '${myVar} is required'}]}>
    <Input />
  </Form.Item>
  <Form.Item messageVariables={{ label: 'Name' }} name='userName' label="User Name" rules={[{required: true, message: '${label} is required'}]}>
    <Input />
  </Form.Item>
  <Form.Item name='userName' label="User Name" rules={[{required: true, message: '${label} is required'}]}>
    <Input />
  </Form.Item>
  <Form.Item name='userName' rules={[{required: true, message: '${label} is required'}]}>
    <Input />
  </Form.Item>
  <Form.Item name='nickName' label={<span>Nickname</span>} rules={[{required: true, message: '${label} is required'}]}>
    <Input />
  </Form.Item>
  <Form.Item name='nickName' label={'Nickname'} rules={[{required: true, message: '${label} is required'}]}>
    <Input />
  </Form.Item>
  <Form.Item>
    <Button type="primary" htmlType="submit">
      Submit
    </Button>
  </Form.Item>
</Form>
```
> 注意: 请谨慎使用[错误提示信息](https://github.com/react-component/field-form/blob/master/src/utils/messages.ts)中模板占位符字符串作为 `变量名` 如上面例子中的 `${label}`, 默认情况下优先使用 `messageVariables ` 定义的 `label`，如果不存在则使用 `Form Item` 属性 `label`(`label`是字符串,如不是，则跳过，如 `label={<span>Nickname</span>}`),如果属性label也不存在，则使用 `Form Item` 属性 `name` ,

如果设置了 `Config-Provider` 的 `locale`, [默认的错误提示信息](https://github.com/react-component/field-form/blob/master/src/utils/messages.ts) 会使用 `locale` 下定义的 [defaultValidateMessages](https://github.com/ant-design/ant-design/blob/268bdf2faab9cd3cecb055cd203f4efafe53c771/components/locale/default.tsx#L83)，之所以提出这个问题，是因为当前版本两者提供的模板字符串占位符名称不一致，会影响  `messageVariables` 的默认行为。

**Comment by DaoxingHuang** [comment]
如果想常规用的要么就该实现方式，要么就提示用户 哪些不能用作变量名；这样一句话就可以避免。

**Comment by DaoxingHuang** [comment]
4.16.13 之前的版本还好一点，当然也有一点BUG，4.17 这个我就不知道咋解释了

**Comment by guan404ming** [comment]
I would try to summarize the result and put them in the doc !
