### ISSUE TITLE
Collapse.Panel 的 key 如果是 number 类型，onChange 的 value 都会变成 string 类型

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#32114]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhe-die-mian-ban-antd-4-17-0-alpha-0-forked-jgk6s?file=/index.js:558-563)

### Steps to reproduce
展开折叠面板，查看控制台

### What is expected?
string 和 number 类型正确，不应该都变成 string 类型。

### What is actually happening?
都变成了 string 类型

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
运行时获取到的值已经被 React 转译成 `string` 类型了，上层做不了什么：

<img width="205" alt="截屏2021-09-13 下午5 08 51" src="https://user-images.githubusercontent.com/5378891/133056746-611be07b-1547-4577-a0f4-3045c8e73a0e.png">

**Comment by linxianxi** [comment]
> 运行时获取到的值已经被 React 转译成 `string` 类型了，上层做不了什么：
> 
> <img alt="截屏2021-09-13 下午5 08 51" width="205" src="https://user-images.githubusercontent.com/5378891/133056746-611be07b-1547-4577-a0f4-3045c8e73a0e.png">

什么意思。我看源码是在 rc-collaple 里 String() 转换的
