### ISSUE TITLE
请问 select 的下拉框渐显动画在哪修改？

### ISSUE THREAD

**Issue by xjb258** [ant-design/ant-design#32117]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select 在自定义呈现菜单时，如果下拉菜单尺寸比较大，比较复杂，那个显示与隐藏的动画会很卡顿，尝试在ant-select-dropdown及其它所有div上都加上 transition: none;  仍然会动画。

### What does the proposed API look like?
可以关闭或者修改动画。

**Comment by afc163** [comment]
`transitionName=""`
