### ISSUE TITLE
Tooltips are not Completely displayed on Safari 14.0.3

### ISSUE THREAD

**Issue by boomler** [ant-design/ant-design#32122]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s7ll2?file=/index.js)

### Steps to reproduce
It seems that only happens on certain Safari versions. Like Safari 14.0.3

### What is expected?
We expect tooltip can be shown completely

### What is actually happening?
Some text are overflow from tooltip.
![image](https://user-images.githubusercontent.com/17810913/132893327-3ab76fde-f497-4502-a86f-2140f0072fd4.png)

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Safari 14.0.3 |

**Comment by afc163** [comment]
<img width="317" alt="图片" src="https://user-images.githubusercontent.com/507615/132949899-c9204123-c7b8-441a-984e-19899fc85bec.png">

<img width="396" alt="图片" src="https://user-images.githubusercontent.com/507615/132949905-63902b2d-61d7-4326-8f20-e1ee307c7a8a.png">

It works on Safari 14.1.2, I think it should be safari's problem.
