### ISSUE TITLE
InputGroup验证样式失效

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design#3212]
```
<FormItem
        {...formItemLayout}
        label="领取二维码"
        hasFeedback
        help={isFieldValidating('qrCode') ? '校验中...' : (getFieldError('qrCode') || []).join(', ')}
      >
        <InputGroup className="ant-search-input">
          <Input {...qrCodeProps} disabled={ agentDistributions.submiting } />
          <div className="ant-input-group-wrap">
            <Button icon="scan" className="ant-search-btn"/>
          </div>
        </InputGroup>
      </FormItem>
```

样式失效，无法正确显示，如下是显示效果：
![image](https://cloud.githubusercontent.com/assets/4178729/18941729/07f5012a-8646-11e6-9e43-db263f6bb8eb.png)

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by taditang** [comment]
getFieldProps的上级必须是FormItem, 所有可以使用嵌套FormItem的方式解决, 刚刚也是碰到你这问题, 还好解决了.代码如图
![qq 20161014001154](https://cloud.githubusercontent.com/assets/2277906/19357344/d30f4f42-91a3-11e6-8dbd-6a21f91d04bf.png)

**Comment by benjycui** [comment]
如果 `Form.Item` 与表单域不是直接父子关系，则 `validateStatus` 不会自动生成 https://ant.design/components/form/#Form.Item

但还是可以手动设置的。

**Comment by WhatAKitty** [comment]
@taditang 发现并不行。

代码：
```
<FormItem
            hasFeedback
            help={isFieldValidating('telephone') ? '校验中...' : (getFieldError('telephone') || []).join(', ')}
          >
            <InputGroup>
              <FormItem>
                <Input {...telephoneProps} onPressEnter={ this.onSearch } />
                <div className="input-icon-btn">
                  <Button icon="search" className="ant-search-btn" onClick={ this.onSearch }/>
                </div>
              </FormItem>
            </InputGroup>
          </FormItem>
```

效果图：
![image](https://cloud.githubusercontent.com/assets/4178729/19374101/fa104f62-91fb-11e6-81fc-e8239874e272.png)

**Comment by WhatAKitty** [comment]
@benjycui 手动设置的话，会不会太麻烦？为何在InputGroup上，验证样式会出现该种问题。

**Comment by benjycui** [comment]
其实最早就是手动设置的，自动生成是一个优化。

**Comment by benjycui** [comment]
多层嵌套的问题应该可以解决，毕竟表单域已经被 `getFieldDecorator` 标记了。

但是 `Form.Item` 内有多个表单域的问题还没想到办法。

**Comment by WhatAKitty** [comment]
@benjycui getFieldDecorator 还是2.x的版本，也就是1.x没有办法解决了？只能用手动？

**Comment by benjycui** [comment]
1.x 只会做 bugfix

**Comment by taditang** [comment]
@WhatAKitty 说了Input的上级要是FormItem才有效,意思就是说help  hasFeedback都是在Input的上级FormInput上, 最外层的FormItem只用做显示label和样式.
![qq 20161014153939](https://cloud.githubusercontent.com/assets/2277906/19379482/c2dcef7c-9224-11e6-931d-14dc0c4221a7.png)

**Comment by WhatAKitty** [comment]
@taditang 不知道你怎么做到的，我这里不管放哪里都是有问题的。

代码：
```
          <FormItem>
            <InputGroup>
              <FormItem
                hasFeedback
                help={isFieldValidating('telephone') ? '校验中...' : (getFieldError('telephone') || []).join(', ')}
              >
                <Input {...telephoneProps} onPressEnter={ this.onSearch } />
                <div className="input-icon-btn">
                  <Button icon="search" onClick={ this.onSearch }/>
                </div>
              </FormItem>
            </InputGroup>
          </FormItem>
```

效果图：
![image](https://cloud.githubusercontent.com/assets/4178729/19379635/8e2a65d8-9225-11e6-8705-759ddd2a9cb5.png)

**Comment by taditang** [comment]
@WhatAKitty 如果你是说search 按钮位置的问题, 那确实没办法, 因为这个按钮的CSS是我自己另外写的, 不是用的ant-design自己的ant-input-group-wrap, 所以我是为了能够自动提示GROUP表单错误信息, 另外写了对应的CSS, 将按钮绝对定位在输入框右边.

**Comment by benjycui** [comment]
优化：

- [ ] 出现多个表单域时，报 warning。
- [ ] 支持深层嵌套的表单域。

**Comment by anlia260** [comment]
![image](https://cloud.githubusercontent.com/assets/11311553/20336913/aaace3fa-ac08-11e6-85f3-4383323bc5b4.png)
![image](https://cloud.githubusercontent.com/assets/11311553/20336933/cf43229c-ac08-11e6-96ca-06970363e527.png)
我想在Form.Item下面装两个child，能否给一个demo，文档不是很明白。谢谢了。

**Comment by benjycui** [comment]
@anlia260 https://ant.design/components/form/#components-form-demo-validate-static
