### ISSUE TITLE
Fixed column shadow is not visible, if columns prop changed dynamically

### ISSUE THREAD

**Issue by alex-golubtsov** [ant-design/ant-design#32125]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-columns-antd-4-17-0-alpha-0-forked-lxrdb)

### Steps to reproduce
- Create a Table with small number of columns (with fixed one on the right)
- Dynamically increase columns number (and keep fixed one)
- Shadow is not visible

### What is expected?
Shadow is visible

### What is actually happening?
Shadow is not visible

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | MacOS Big Sur |
| Browser | Chrome |

**Comment by zombieJ** [comment]
You are not using Table scroll. You are using web native scroll instead. Add `scroll` prop to enable Table scroll:

https://codesandbox.io/s/fixed-columns-antd-4-17-0-alpha-0-forked-fc9t7?file=/index.js

**Comment by alex-golubtsov** [comment]
@zombieJ what about this? https://codesandbox.io/s/fixed-columns-antd-4-17-0-alpha-0-forked-qy3to?file=/index.js
Instead of exactly value for x scroll, I use `max-content` (or `true`). But this has no effect

**Comment by alex-golubtsov** [comment]
@zombieJ any comments?
