### ISSUE TITLE
InputNumber stepping is not working consistently for big numbers

### ISSUE THREAD

**Issue by Chevindu** [ant-design/ant-design#32120]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inputnumber-arrow-buttons-not-working-for-big-numbers-eco73)

### Steps to reproduce
- Set the `max` prop of `<InputNumber>` to "100,000,000,000,000" (15 digits)
- Enter the value "99,999,999,999,999" (14 digits) inside the input.
- Click up or down arrow button (or press arrow keys in keyboard).

### What is expected?
Value should increase or decrease, not violating the max limit and the maximum safe integer of JavaScript.

### What is actually happening?
Value is neither increasing or decreasing

| Environment | Info |
|---|---|
| antd | 4.9.3 |
| React | 17.0.2 |
| System | Ubuntu 20.04 and Windows 10 |
| Browser | Chrome 93.0.4577.63 |

---
Number input is also not stepping up or down consistently when we enter "90,000,000,000,000" (14 digits) and press up/down arrows.

**Comment by afc163** [comment]
https://ant.design/components/input-number/#components-input-number-demo-digit

**Comment by DjVreditel** [comment]
I found a solution by adding `stringMode` to the `InputNumber` :

```TSX

<Form.Item name="test">
  <InputNumber stringMode />
</Form.Item>

```
