### ISSUE TITLE
Cascader级联选择 md api 错误

### ISSUE THREAD

**Issue by aYangLi** [ant-design/ant-design#32127]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader-cn/#API](https://ant.design/components/cascader-cn/#API)

### Steps to reproduce
<Cascader
              dropdownClassName={styles.tableCascader}
              style={{ width: '200px' }}
              placeholder="请选择"
              loadData={loadAttrValueData}
              options={specialAttrFilter}
              displayRender={attrValueRender}
              dropdownRender={dropdownRender}
            />

### What is expected?
md api 层编写正确

### What is actually happening?
md api 没有提供 dropdownClassName ，并且提供的 popupClassName 不可用

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | mac |
| Browser | Chrome |

**Comment by afc163** [comment]
@zombieJ `popupClassName` 是不是在重构的时候丢了？

**Comment by Dreamcreative** [comment]
我发现你们重构的时候，之前好几个属性都没了，加的属性，文档中也没有添上

**Comment by aYangLi** [comment]
> @zombieJ `popupClassName`是不是在某个时候丢了？

麻烦你们重构把 api 层再过一遍，这个问题 我是去看 Cascader 的源码时候发现的，毕竟不能每个组件都去看源码找 api 层参数，还是比较依赖文档。

**Comment by zombieJ** [comment]
用例没 cover 到，我加个兼容。

**Comment by zombieJ** [comment]
@Dreamcreative ，我这边过了一遍有 `popupClassName` 和 `popupPlacement`。还有需要补充的属性么？

**Comment by Dreamcreative** [comment]
> @Dreamcreative ，我这边过了一遍有 `popupClassName` 和 `popupPlacement`。还有需要补充的属性么？

 
@zombieJ  getPopupContainer 这个属性看了吗。我也没尝试太多的属性，只是看了 rc-cascader 组件的 typescript 定义。

**Comment by zombieJ** [comment]
> @zombieJ getPopupContainer 这个属性看了吗。我也没尝试太多的属性，只是看了 rc-cascader 组件的 typescript 定义。

有的，这个是继承自 `rc-select` 的定义：

https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-0-forked-s14qx?file=/index.js
