### ISSUE TITLE
DatePicker切换时间会自动切换日历

### ISSUE THREAD

**Issue by checkhout** [ant-design/ant-design#32138]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
> 当组件受控且value不为空且目标时间段不在近两个月内时，选择目标开始时间后会自动切换日历

例如：
1.  默认时间2021/09/01-2021/09/30
2. 目标时间2019/05/01-2019/05/15，选择第一个时间2019/05/01后，日历自动跳转到了2021/09/30，需要再次切换到2019年五月份选择目标结束时间

### What does the proposed API look like?
期望能有个字段控制是否自动切换日历

**Comment by q1950086900** [comment]
有一个解决方式，参考：https://ant.design/components/date-picker-cn/#components-date-picker-demo-select-in-range

结果过程如：默认时间2021/09/01-2021/09/30，当打开窗口时（onOpenChange）将hackValue设置为空数组，这时开始时间和结束时间是空的，所以再选择开始时间后结束时间不会再跳到9月30日，onChange事件将值保存到value中，当关闭窗口时将 hackValue设置为undefined，因为hackValue是undefined所以会显示value的值。

标签处： <RangePicker value={hackValue || value}/>
