### ISSUE TITLE
Upload should be able to configure uploadMethod (multipart VS binary in HTTP body)

### ISSUE THREAD

**Issue by benedictjohannes** [ant-design/ant-design#32139]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A lot of HTTP servers are supporting direct HTTP binary uploads.

The current way only support uploading to a server that can handle `Content-Type=multipart/form-data` (this is not stated in the docs). While there's a lot of server that can directly accept HTTP binary body (with appropriate headers like `Content-Type=image/jpeg`), such as AWS S3 or Alibaba Cloud Storage bucket.

Instead of having to code the `Upload` component's  `action` as a function, it would be better how the uploaded file(s) are to be uploaded between these two common method via separate props

### What does the proposed API look like?
Add the prop `uploadMethod={ 'multipart' | 'binary' }` to the `Upload` component
- Defaults to the current method (`multipart`)
- will be ignored if `action` prop is not set to an upload URL (i.e. set to a `function(File) => Promise` )

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11616#issuecomment-412015018
