### ISSUE TITLE
range picker 受控 open 后，需要三次点击选择行为关闭弹窗

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#32134]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ri-qi-shi-jian-xuan-ze-antd-4-17-0-alpha-0-forked-5lz9b?file=/index.js)

### Steps to reproduce
点击 open 选择左边，再选择右边，无法自动关闭

### What is expected?
受控 open 下，onOpenChange 在选择完毕后触发

### What is actually happening?
需要再点击一次触发

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.8.13 |
| System | macOS |
| Browser | chrome latest |

**Comment by lvvlan** [comment]
遇到了同样的问题，现在有什么解决办法吗？我尝试在onChange的时候手动关闭，但在后续选择时间的时候还是会碰到些问题（比如当你修改时间的时候，有时候会点第一次之后就关闭了）

**Comment by DaoxingHuang** [comment]
@afc163  这个如果是bug ,Select open属性同样存在这样的问题

**Comment by DaoxingHuang** [comment]
个人不太认为这是一个BUG，我简单的看下，组件内部不应该改变外部属性；
控制关闭的时机应该逻辑代码控制，@tolerance-go ，例如 可能通过 onCalendarChange 的回调事件自行控制

![image](https://user-images.githubusercontent.com/19969260/133576280-1f1efae0-02dc-4501-a782-5c50ac92c6b1.png)

**Comment by tolerance-go** [comment]
@DaoxingHuang  该方案尚有如下问题
1. 首次选择后，焦点不应居左
2. 再次修改，无法范围选择

**Comment by DaoxingHuang** [comment]
> @DaoxingHuang 该方案尚有如下问题
> 
> 1. 首次选择后，焦点不应居左
> 2. 再次修改，无法范围选择

@tolerance-go 可否提供下具体的现象 ，我这边无法重现
> 1. 首次选择后，焦点不应居左 ---  再次打开 ，无焦点，需要通过选择左右才有
> 2. 再次修改，无法范围选择  -- 正常选择，没有类似问题

**Comment by xingxiulaoxian** [comment]
时间范围设置为受控之后导致内部逻辑出现混乱，应该将这个逻辑设置为可以启用或者不启用，这样在设置不启用的时候就可以自由的设置受控组件

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
