### ISSUE TITLE
antd 更新到4.17.0-alpha.0后运行报错

### ISSUE THREAD

**Issue by ChenYu29** [ant-design/ant-design#32146]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
@import './index';
^
Variable @import is undefined
      Error in F:\data\droneImageManage\drone-image-manage-js\node_modules\antd\lib\alert\style\index-default.less (line 3, column 0)
 @ ./node_modules/antd/lib/alert/style/index-default.less 47:4-60:5 2:12-221 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./node_modules/antd/lib/alert/style/index.js 5:0-31
 @ ./src/components/imageRetrieval/RetrievalImageSelect.tsx 26:0-39
 @ ./src/components/index.ts 27:0-98 27:0-98
 @ ./src/index.tsx 8:0-50 35:44-57 39:44-57
 @ ./src/app.tsx 9:0-26 16:24-27

ERROR in ./node_modules/antd/lib/avatar/style/index-default.less (./node_modules/css-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[1].use[3]!./node_modules/antd/lib/avatar/style/index-default.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

@import './index';
^
Variable @import is undefined
      Error in F:\data\droneImageManage\drone-image-manage-js\node_modules\antd\lib\avatar\style\index-default.less (line 3, column 0)
 @ ./node_modules/antd/lib/avatar/style/index-default.less 47:4-60:5 2:12-221 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./node_modules/antd/lib/avatar/style/index.js 5:0-31
 @ ./src/components/home/Header.tsx 11:0-40
 @ ./src/components/index.ts 7:0-60 7:0-60
 @ ./src/index.tsx 8:0-50 35:44-57 39:44-57
 @ ./src/app.tsx 9:0-26 16:24-27

### What is actually happening?
 

| Environment | Info |
|---|---|
| antd | undefined |
| React | 4.17.0-alpha.0 |
| System | window |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
升级一下 antd 版本
