### ISSUE TITLE
关于Pagination中onChange和onShowSizeChange的行为的疑问

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#32148]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

现在有个不算需求的小期望，我在切换pageSize时，这个时候的也数据可能都已经发生了变化，按照我的理解，能够重置currentPage，是最好的。

但是在使用时，发现onShowSizeChange触发后，又触发了一次onChange，我就有点迷惑了（当然，也可以通过做一个标记同样可以实现），所以，能否对onShowSizeChange的行为进行一些解答呢？

我记得之前好像看过一个issue，说的是切换个页大小，然后保留currentPage，具体是不是这个问题已经记不清了，只是当时看了一眼，貌似是一个待讨论的问题，如果有这个issue，我想看下讨论，了解一下。谢谢

### What does the proposed API look like?
无

**Comment by zombieJ** [comment]
没看懂你说的迷惑是啥意思，如果说问为什么会触发 `onChange` 那是因为 pagination 变化也是 `onChange` 的参数之一。

**Comment by zmbxy95** [comment]
sorry，我理解到一个误区了。

**Comment by lovelyJason** [comment]
我发现5.x的这个pagination又点问题

**Comment by RedJue** [comment]
> 我发现5.x的这个pagination又点问题

开个 issue 看看

**Comment by lovelyJason** [comment]
> > 我发现5.x的这个pagination又点问题
> 
> 开个 issue 看看

与其说问题，可能更多的是设计层面原因，所以没有提issue

我用5.x的pagination版本，按照文档定义，onChange事件是在页码变化或者pageSize变化时会触发， onShowSizeChange事件在pageSize变化后触发。但是3.x版本的onChange是仅在页码变化执行的，这就意味着

如果我使用5.x的pagination，如果我要实现切换pageSize的同时将当前页面置换为1是无法做到的，3.x版本可以像这样

```javascript
    onChange(current) {
      self.setState({ currentPage: current, sortKey, sortType, isPageChange: true }, () => {
        self.getSource()
      })
    },
    showTotal(total) {
      return `共有${total}条`
    },
    onShowSizeChange(current, pageSize) {
      self.pageSize = pageSize
      self.setState({ currentPage: 1, sortKey, sortType, isPageChange: true }, () => {
        self.getSource()
      })
    }
```

为什么要这么做。因为如果之前分页不是停留在第一页，此时如果切换pageSize， 基本准则是要把当前页码重置为1的，不然如果total数量不够会出现bug的。

但是5.x版本的onChange会在两个节点触发，咋解决这个问题呢？

**Comment by RedJue** [comment]
> > > 我发现5.x的这个pagination又点问题
> 
> > 
> 
> > 开个 issue 看看
> 
> 
> 
> 与其说问题，可能更多的是设计层面原因，所以没有提issue
> 
> 
> 
> 我用5.x的pagination版本，按照文档定义，onChange事件是在页码变化或者pageSize变化时会触发， onShowSizeChange事件在pageSize变化后触发。但是3.x版本的onChange是仅在页码变化执行的，这就意味着
> 
> 
> 
> 如果我使用5.x的pagination，如果我要实现切换pageSize的同时将当前页码置换为1是无法做到的，3.x版本可以像这样
> 
> 
> 
> ```javascript
> 
>     onChange(current) {
> 
>       self.setState({ currentPage: current, sortKey, sortType, isPageChange: true }, () => {
> 
>         self.getSource()
> 
>       })
> 
>     },
> 
>     showTotal(total) {
> 
>       return `共有${total}条`
> 
>     },
> 
>     onShowSizeChange(current, pageSize) {
> 
>       self.pageSize = pageSize
> 
>       self.setState({ currentPage: 1, sortKey, sortType, isPageChange: true }, () => {
> 
>         self.getSource()
> 
>       })
> 
>     }
> 
> ```
> 
> 
> 
> 为什么要这么做。因为如果之前分页不是停留在第一页，此时如果切换pageSize， 基本准则是要把当前页码重置为1的，不然如果total数量不够会出现bug的。
> 
> 
> 
> 但是5.x版本的onChange会在两个节点触发，咋解决这个问题呢？

直接用 onChange 就可以了，第二个参数就是 pageSize，判断如果 pageSize 不一样 直接把 current 置为1就行了

**Comment by CorgiTT** [comment]
这个页码设计真的有点反人类，size变了肯定要重置current为1啊，为什么还要两个方法同时触发。。。不理解
