### ISSUE TITLE
Warning: `info.item` is deprecated since we will move to function component that not provides React Node instance in future.

### ISSUE THREAD

**Issue by Zero-Xiong** [ant-design/ant-design#32145]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://u.ant.design/codesandbox-repro](https://u.ant.design/codesandbox-repro)

### Steps to reproduce
import "antd/dist/antd.css";
import { Menu, Tooltip } from "antd";

const handleMenuOnClick = ({ item, key, keyPath, domEvent }) => {
        console.log(item, key, keyPath, domEvent); <---- here will got:   Warning: `info.item` is deprecated since we will move to function component that not provides React Node instance in future.
    };

<Menu
                defaultSelectedKeys={["10"]}
                mode="inline"
                theme="light"
                inlineCollapsed={foldedAndClosed}
                style={{ margin: 0, padding: 0, width: foldedAndClosed ? "64px" : "100%", backgroundColor: "inherit" }}
                forceSubMenuRender
                onClick={handleMenuOnClick}
            >
                {renderMenu(props.navigation)}
            </Menu>

then you will see inside Console:

Warning: `info.item` is deprecated since we will move to function component that not provides React Node instance in future.

### What is expected?
what should we use to replace 'info.item'?

### What is actually happening?
no idea

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Win10 |
| Browser | Chrome: Version 93.0.4577.63 (Official Build) (64-bit) |

---
pls provide the alternative parameter(s)

**Comment by zombieJ** [comment]
As described. It will be replace with FC and no more instance exist in future. What do you want to get from `item`?

**Comment by Zero-Xiong** [comment]
never mind! For me the info.item is not important, close it now.

**Comment by kwantdev** [comment]
Hi, I want to be able to know which item is fired, all its attributes. How is that possible without the item parameter?
