### ISSUE TITLE
InputNumber 设置 precision 后，onPressEnter() 时未做格式化

### ISSUE THREAD

**Issue by Artoria-0x04** [ant-design/ant-design#32140]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/input-number-onenter-t9obe?file=/App.tsx)

### Steps to reproduce
输入任意小数回车，输出的值为小数

### What is expected?
回车提交表单后输出格式化后的值

### What is actually happening?
输出了未格式化的值

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | latest |
| System | macOS |
| Browser | Chrome v93 |

### Additional Info

考虑了一下，不能算是 InputNumber 的问题，但是在 Form 中组合使用时会出现问题，可能需要 Form 进行适配

**Comment by zombieJ** [comment]
分几件事情：
1. 因为 InputNumber 受控状态，所以输入都会触发 `onChange`
2. 一旦触发 Enter 或者 Blur 事件，InputNumber 会将数据进行规整再次触发 `onChange`
3. InputNumber 不修改原生 dom 值，只通过 `onChange` 提供正确值
4. Form 默认也只从 `onChange` 收集值
5. HTML Form 回车会触发 form submit 导致收集的值是 InputNumber 中间值

在业务中，enter to submit 大部分场景都没有意义所以这边就不做额外处理了。对此有两种方式，一个是如果需要 Enter 提交，可以拦截自行做异步处理。另一种就是拦截掉就行了：

https://codesandbox.io/s/input-number-onenter-forked-9z6lr?file=/App.tsx

**Comment by Artoria-0x04** [comment]
@zombieJ 对于你提供的两种解决方案：
1. 自行拦截提交，但需要自行处理数据，那么 precision 功能相当于不可用
2. 拦截掉 enter，在部分场景下可行，但 enter 提交已经是 UI 上的一个高频直觉操作了，而且 form 其他的控件 enter 提交工作正常，这样相当于令部分情况下 form 的 enter 提交不可用。

我认为既然 InputNumber 提供了该功能，那么应该在 onChange 时就对数据进行处理，希望考虑一下。

**Comment by Artoria-0x04** [comment]
@zombieJ Issue 关的也未免太快了吧，我是不是要重开一个
