### ISSUE TITLE
Table Row Selection By Click

### ISSUE THREAD

**Issue by surajc07** [ant-design/ant-design#32151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Whether to select a row by clicking anywhere in the whole row. This feature is already on expandable which means this also should be on rowSelection too.

### What does the proposed API look like?
rowSelectionByClick - Whether to select a row by clicking anywhere in the whole row - boolean - default set to false

**Comment by zombieJ** [comment]
Row selection by click is conflict interactive with expandable logic. You can wrap this with `onRow` if needed.

**Comment by surajc07** [comment]
How can I do it with onRow? @zombieJ
