### ISSUE TITLE
文档链接有误。

### ISSUE THREAD

**Issue by xueqingxiao** [ant-design/ant-design#3215]
<img width="1471" alt="screen shot 2016-09-29 at 2 53 57 pm" src="https://cloud.githubusercontent.com/assets/4010906/18943870/c9ea9660-8654-11e6-85f7-bafa4dab7471.png">
是不是应该去除host？

**Comment by xueqingxiao** [comment]
@benjycui @afc163

**Comment by benjycui** [comment]
是的，我删除下。。
