### ISSUE TITLE
Missing antd.variable.min.css

### ISSUE THREAD

**Issue by cedrouck** [ant-design/ant-design#32152]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bg8u5)

### Steps to reproduce
Just follow theses instructions about global theme customization : 
https://ant.design/docs/react/customize-theme-variable
It's not working, the file is missing, maybe this doc have mistake ?

### What is expected?
Should find the file `antd/dist/antd.variable.min.css`

### What is actually happening?
File not found
![Screenshot 2021-09-13 at 16 31 59](https://user-images.githubusercontent.com/10866953/133102919-d107c74a-8970-4581-9f1b-a520af14fc06.png)

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Mac os |
| Browser | Chrome |

**Comment by kaysonwu** [comment]
@cedrouck  This is an error caused by a low version and recommended to upgrade `antd` to '4.17.0-alpha. 2' or not use this feature.  #31496

**Comment by zombieJ** [comment]
As @kaysonwu said. Upgrade to `4.17.0-alpha.2` instead.

**Comment by cedrouck** [comment]
Great, thank you for your help guys.

**Comment by mzvast** [comment]
the document version should update to 4.17.0-alpha. 2, or users will be confused.
