### ISSUE TITLE
DatePicker组件切换年和月没有触发onChange

### ISSUE THREAD

**Issue by 104gogo** [ant-design/ant-design#32159]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
打开官方网站的DatePicker组件页面，使用下面的demo，点击确定按钮，尝试切换年或月，发现没有反应
![image](https://user-images.githubusercontent.com/8522646/133219941-cab4da47-67d7-4f6a-ba82-21fae78e1d75.png)

### What is expected?
希望能正常切换

### What is actually happening?
希望能正常切换

| Environment | Info |
|---|---|
| antd | undefined |
| React | 最新 |
| System | mac |
| Browser | 谷歌 |

**Comment by afc163** [comment]
这是预期的，需要点击具体日才会完成选择，切换年月只是切换选择面板，不会修改已选择的值。

**Comment by 104gogo** [comment]
意思先选了日，再去修改年就不会生效？这不太合理吧
