### ISSUE TITLE
Ships very large CSS File to production

### ISSUE THREAD

**Issue by siamekanto19** [ant-design/ant-design#32164]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce
- Create a React Project
- Add Ant Design with Yarn or NPM
- Import any component inside the app
- Build the Application for Production
- Check the size of the CSS File in the bundle. (500kb )

### What is expected?
As I am using only one component, the CSS File shouldn't be 500 kb in size

### What is actually happening?
The generated CSS File is 500kb  in size while it should be way less than that

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.0.0 |
| System | Windows 10 |
| Browser | Google Chrome, Firefox and all other Chromium Browsers |

**Comment by afc163** [comment]
You can try https://github.com/ant-design/babel-plugin-import
