### ISSUE TITLE
Carousel 的设置过于简单，不能满足需求

### ISSUE THREAD

**Issue by gaohongwei** [ant-design/ant-design#32171]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望增加常用的设置，例如，时间频率， 前后箭头

### What does the proposed API look like?
时间频率， 前后箭头可以定制化

**Comment by afc163** [comment]
更多 API 可参考：https://react-slick.neostack.com/docs/api
