### ISSUE TITLE
2.0<Spin/>标签如何去除加载动画

### ISSUE THREAD

**Issue by GlacierXX** [ant-design/ant-design#3217]
- antd 版本: 2.0.0
- 操作系统及其版本: mac OS X 10.11.4
- 浏览器及其版本: chrome 52.0.2743.116

使用<Spin/>标签作为某些区域遮罩层又不想展示圆点，tip属性设置为空字符串即可，2.0以后加载中的圆点无法取消，能不能将加载中的原点也设置成可选的

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2799

@jerrybendy 你们俩先讨论一下~

**Comment by benjycui** [comment]
遮罩用 Spin 也不对吧。。自己用 `div` 做个就好。

**Comment by jerrybendy** [comment]
只是想遮罩感觉用 Spin 真心不太合适。。还是自己简单写一个遮罩来的简单快捷些，或者自己写一个样式，把圆点那块 `display:none`  😁

**Comment by GlacierXX** [comment]
好哒~
