### ISSUE TITLE
Table show expand icon without the need of children on dataSource

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#32170]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would allow you to have control of the "onExpand" event and load data programatically on the expandedRow by external means.

The data that i have doesn't return a children, since i will set it dinamically after clicking the expand icon, it would be nice to be able to show the expand icon even if there is no "children" property on the table dataSource.

I tried using: 

```
<Table
     size='small'
     bordered
     loading={isLoading}
     pagination={false}
     expandable={{
      rowExpandable: () => true,
      onExpand: handleRowExpand
    }}
    dataSource={productFatherStructureData}
    scroll={{ y: 400 }}
    rowKey='code'
>
```

But it still only shows the Expand Icon if i add a children to the dataSource.
Is there a way to force the expand icon to appear on all rows? Even if there is no children in the dataSource?

For my case, i want to load the data that will be shown on the expandedRow from my API only when I click the expand Icon, with that i will set the new data on the record/row that "onExpand" event on the table returns.

This way i can make the requests happen only when i click the expand icon.

### What does the proposed API look like?
Something like a forceExpandable prop? If it receives true, it doesnt matter if the dataSource has a children or not, it will allways have the expandIcon.

**Comment by afc163** [comment]
You can add a empty children attribute at beginning, it will show a expand icon for this record.

```diff
dataSource={[
  {
    name: 'xxx',
    data: 'yyy',
+   children: [],
  },
]}
```

Then load data programatically when user click expand icon.

https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941

**Comment by balboFK** [comment]
@afc163 as i said on the issue, i want to have the expand icon, without having to add a children to the dataSource. 
That's the question:

`Is there a way to force the expand icon to appear on all rows? Even if there is no children in the dataSource?`

I'm using a initial data which also comes from a API, and this data has no childrens.
By your method I would have to run a map on the data coming from the server, add a empty array to each record, and them pass it to the table. I was wondering if there is a way of achieving it without having to do this.
