### ISSUE TITLE
Cascader 组件设置 multiple 多选之后，使用 loadData 动态加载数据，第一次直接选中一级，二级不会全部选中，因为数据请求完成渲染的问题；并且希望 Cascader 组件 multiple 模式下 增加全选按钮，以及增加  suffixIcon 属性和自带下拉的选择图标

### ISSUE THREAD

**Issue by aYangLi** [ant-design/ant-design#32184]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/32176](https://github.com/ant-design/ant-design/issues/32176)

### Steps to reproduce
<Cascader multiple options={options} loadData={loadData} onChange={onChange} changeOnSelect />

### What is expected?
1：loadData 的 multiple 状态下 的 Cascader 第一次选中一级数据，二级数据没有默认全部选中，希望可以全部选中；
2：multiple 状态下 的 Cascader 支持配置 suffixIcon 和自动有下拉的提示图标；
3：multiple 状态下 的 Cascader 支持是否展示 全部按钮 的
4：multiple 状态下 的 Cascader 支持配置 onChange  回调的 value函数支持配置返回的数据，比如：返回所有选中的value，或者选中的末级value，或者选中的根级 value

### What is actually happening?
以上都无，无法满足各种业务场景

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | mac |
| Browser | Chrome |

**Comment by aYangLi** [comment]
> Hello @aYangLi. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @aYangLi, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

![image](https://user-images.githubusercontent.com/32217369/133579901-6fd4bc3f-19a2-43f9-9fc9-1b7453009341.png)
https://codesandbox.io/s/antd-reproduction-template-forked-tpqje?file=/index.js

**Comment by aYangLi** [comment]
> Hello @aYangLi. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @aYangLi, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

还有以下需求是否可以支持：
2：multiple 状态下 的 Cascader 支持配置 suffixIcon 或者 配置下箭头的提示图标；
3：multiple 状态下 的 Cascader 支持配置是否展示 全部选中按钮
4：multiple 状态下 的 Cascader 支持配置 onChange 回调的 value函数支持配置返回的数据，比如：返回所有选中的value，或者选中的末级value，或者选中的根级 value

**Comment by zombieJ** [comment]
选中全部合并到 #32176，suffixIcon 是可以的文档需要更新。issue 提得太碎不好处理，这个 issue 我先修 `loadData` 的问题。其他的有需要另开 issue 吧。

**Comment by zombieJ** [comment]
![截屏2021-09-28 下午2 39 04](https://user-images.githubusercontent.com/5378891/135035888-ad1b3faf-1bea-4ca1-a456-1c6d6ac1f3e2.png)

Tree 结构变化时会创建容器做动画过渡，`:not(:first-of-type):not(:last-of-type)` 不是稳定结构。
