### ISSUE TITLE
Icons in menu items don't have spacing (anymore)

### ISSUE THREAD

**Issue by IonelLupu** [ant-design/ant-design#32183]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
|Current version (V4)|Previous version (V3)|
|--------|--|
| [![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://stackblitz.com/edit/react-s9byc8?file=index.js) | [![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://stackblitz.com/edit/react-cfqbgv) |

### Steps to reproduce
Create a Menu with a few items. Add icons before the text of the menu items.

### What is expected?
It is expected to have a space between the icons and the text similar to Ant Design V3 example above

### What is actually happening?
There is not space between the icons and the text

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | * |
| System | * |
| Browser | * |

---
Have there been any changes to Ant Design V4 that removed the spaces for icons? This is the second issue I find on this matter ([first one here](https://github.com/ant-design/ant-design/issues/32165))

**Comment by afc163** [comment]
Try https://stackblitz.com/edit/react-s9byc8-bgldvw?file=index.js
