### ISSUE TITLE
2.0Tabs组件的出现的问题

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#3218]
antd版本：2.0.0
现象：两个TabPane,第一个中放一张echart的图，第二个中放其他东西，当切换到第二个tab，这个时候缩小游览器窗口，则第一个tab中的图会出现在视野中，如下图:缩小窗口时活动数据中的图出现在了TOP汇总中
![qq 20160929170234](https://cloud.githubusercontent.com/assets/15683846/18947813/26edbab0-8667-11e6-9b2d-a1498fae74de.png)
我覆盖antd的样式就好了:
.ant-tabs-tabpane{
  overflow: hidden;
}

**Comment by benjycui** [comment]
`ant-tabs-tabpane` 其实是并排排成一行的，然后 `ant-tabs` 也自带了 `overflow: hidden`，所以应该不会出现这个情况。

麻烦提供可重现 demo

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zhangchao828** [comment]
@benjycui [http://codepen.io/anon/pen/vXJyGq](url)

**Comment by zhangchao828** [comment]
@benjycui 我把第一个tab中的div的宽度写死，在第二个tab中能看见第一个tab中的内容，缩小窗口看的更清楚http://codepen.io/anon/pen/vXJyGq

**Comment by benjycui** [comment]
你把 TabPane 里面的内容设得比 TabPane 还大，当然溢出了啊。。。。

TabPane 的宽度不能小于里面的内容，不然把里面的内容截断了也不对吧。

**Comment by benjycui** [comment]
控制内容的宽度。
