### ISSUE TITLE
Table 组件 Column 中的 align api 类型报错

### ISSUE THREAD

**Issue by Handpear** [ant-design/ant-design#32194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-fecbh?file=/index.tsx)

### Steps to reproduce
导入 Table 组件，添加 columns 属性，设置 align 

### What is expected?
没有类型报错

### What is actually happening?
属性生效，但类型报错

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Windows |
| Browser | Google Chrome 93.0.4577.82 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ey5xb?file=/index.tsx
