### ISSUE TITLE
less样式中有’-‘字符

### ISSUE THREAD

**Issue by wboykron** [ant-design/ant-design#3219]
#### 发生问题的环境是：

- antd 版本:1.1.0
- 操作系统及其版本:windows10
- 浏览器及其版本:chrome

#### 您做了什么？
在jsx中引入less，在className中不能直接使用，必须用变量.XXX形式来使用

#### 您期待的结果是：
less引用只能能用变量，也能直接使用！

#### 实际上的结果是：
less编译之后会在每个类后面添加一串随机字符，直接使用找不到类！

**Comment by benjycui** [comment]
css-modules 的问题，建议查阅他们的文档或者到对应社区提问，谢谢。

https://github.com/css-modules/css-modules

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
