### ISSUE TITLE
请给Modal框的“确定”按钮暴露confirmLoading:false的设置

### ISSUE THREAD

**Issue by dian533** [ant-design/ant-design#322]
在单击“确定”后，发现modal框的某些内容没有填对，允许修正后再次单击“确定”的情况需要对confirmLoading可以设置false

**Comment by afc163** [comment]
http://ant.design/components/modal/#demo-basic

**Comment by dian533** [comment]
帮助文档中是有这个参数，但实际不生效
看了源码，也确实没有从props中取值然后赋值的
