### ISSUE TITLE
Table 展开行和固定列一起使用的问题

### ISSUE THREAD

**Issue by zyycode** [ant-design/ant-design#32208]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
展开行无法被固定列遮挡

https://stackblitz.com/edit/react-djvw9e?file=index.js

### What does the proposed API look like?
希望提供一个属性让开发者选择是否需要被遮挡

**Comment by afc163** [comment]
展开行不应该被固定列遮挡，会造成信息缺失，我们的规范还是推荐内容优先。目前不会支持可配，感谢理解。
