### ISSUE TITLE
menu 的defaultOpenKeys 和 defaultSelectedKeys 动态改变之后不更新dom

### ISSUE THREAD

**Issue by caojide** [ant-design/ant-design#32207]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-6bwrpa?file=index.js](https://stackblitz.com/edit/react-6bwrpa?file=index.js)

### Steps to reproduce
将defaultSelectedKeys或者defaultOpenKeys 放在state中，然后在页面加载完成或者菜单初始化完成之后，根据条件自动改变默认展开和选择项

### What is expected?
动态改变defaultSelectedKeys和defaultOpenKeys， 组件能及时更新

### What is actually happening?
动态改变defaultSelectedKeys和defaultOpenKeys， 组件没有无变化

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | ^17.0.0 |
| System | mac |
| Browser | 所有浏览器 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
