### ISSUE TITLE
Switch component in typescript throws error for 'id' attribute

### ISSUE THREAD

**Issue by M-ZubairAhmed** [ant-design/ant-design#32203]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-pike-6p54e?file=/src/App.tsx)

### Steps to reproduce
- Add switch component in ts file
- Add id to the component

### What is expected?
id attribute to switch should not throw error

### What is actually happening?
although id is being passed through the component, its ts counterpart is throwing unknown property

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.9.0 |
| System | MacOS |
| Browser | Firefox |

**Comment by M-ZubairAhmed** [comment]
@afc163 sure let me work on this on the weekend

**Comment by 1084350607** [comment]
Hello, I'm a colleage student, Can i join in this? Hope to contribute

**Comment by 1084350607** [comment]
what‘s the meaning of 'Add switch component in ts file', I'm sorry that I can't understand

**Comment by M-ZubairAhmed** [comment]
@1084350607 hey sorry it means to add Switch component to a type script file
