### ISSUE TITLE
AutoComplete 设置值为 undefined 不生效

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#32217]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://stackblitz.com/edit/react-kiu8nr?file=index.js

### Steps to reproduce
https://stackblitz.com/edit/react-kiu8nr?file=index.js
AutoComplete 组价输入内容，然后点击清除按钮

### What is expected?
undefined 应该生效

### What is actually happening?
undefined 不生效

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by Dolov** [comment]
https://stackblitz.com/edit/react-kiu8nr?file=index.js

**Comment by afc163** [comment]
Please set value to `''` instead of `undefined`.

**Comment by Dolov** [comment]
> Please set value to `''` instead of `undefined`.

已经用 '' 替代了 undefined  但是我觉得组件的这个行为有点怪异
