### ISSUE TITLE
如何实现动态异步添加select multiple时的option

### ISSUE THREAD

**Issue by chengandpeng** [ant-design/ant-design#3221]
### 9/30 Update

是我搞错了，select multiple是通过Option的key来匹配的，但是我给option的key赋值了数字id，所以输内容无法正常显示匹配。

#### 发生问题的环境是：

- antd 版本: 2.0.0
- 操作系统及其版本: macOS Sierra
- 浏览器及其版本: Chrome 53

#### 您做了什么？

对select multiple动态添加option选项。
``` javascript
<Form >
  <FormItem	label='标签'	labelCol={{ span: 4 }}	wrapperCol={{ span: 10 }}>
    <Select multiple onSearch={this.handleSearchTags} >
      {this.renderOptions()}
    </Select>
  </FormItem>
</Form>

handleSearchTags(value) {
 //根据value去服务端请求
}

renderOptions() {
  return this.state.tagOptions.map(tag => <Option key={tag.id}>{tag.name}</Option>);
}
```

#### 您期待的结果是：

使用场景: 服务端有很多tag，无法一次性全部拿过来，打算在input中输入值时，实时从服务端拿到匹配的数据，在input中输入内容的同时动态更新select的option.

#### 实际上的结果是：

在input中输入东西从后台获得数据后，下拉的选项并没有实时更新。
unfocus input，再次focus input后，下拉选项中出现了上次得到的数据。

#### 可重现的在线演示

https://codepen.io/chengandpeng/pen/kkorgm
演示中用了state，实际项目中是redux维护数据

**Comment by infeng** [comment]
http://ant.design/components/select/#components-select-demo-search-box 参考下官网的例子？

**Comment by infeng** [comment]
试了下你的演示，并没有问题啊

**Comment by benjycui** [comment]
没问题，只是你输入的内容和随机生成的数据不匹配而已。
