### ISSUE TITLE
switch组件loading效果不对

### ISSUE THREAD

**Issue by HypnosNova** [ant-design/ant-design#32215]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/switch-cn/](https://ant.design/components/switch-cn/)

### Steps to reproduce
官网demo直接看

### What is expected?
转圈圈的元素在switch按钮圆圈中间

### What is actually happening?
转圈圈的元素位置错了，往下偏了好几个像素
![image](https://user-images.githubusercontent.com/7953802/133758690-b1d601c9-be5d-4734-8b86-1d8a36175bf3.png)

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 最新 |
| System | mac |
| Browser | chrome最新 |

**Comment by KiritoXF** [comment]
看起来可以把 `.action` 的 `vertical-align` 从 `-.125em` 改成 `0.875em`

**Comment by PeachScript** [comment]
试了下是官网样式污染导致的，单独使用没有问题：https://codesandbox.io/s/oi0fl

**Comment by Dreamcreative** [comment]
这个问题我看了一下 ，是 .anticon 这个 class 中的 vertical-align 把 .ant-switch-loading-icon 这个类中的 vertical-align 覆盖掉了，
