### ISSUE TITLE
关于 table sortDirections 的疑惑

### ISSUE THREAD

**Issue by chenxiaochun** [ant-design/ant-design#32229]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-lie-pai-xu-antd-4-17-0-alpha-0-forked-m4bhx)

### Steps to reproduce
1、Table 组件上添加自定义`sortDirections`，例如：`sortDirections={['up', 'down']}`
2、在 Table 的`onChange`回调中，是获取到自定义之后的排序参数的
3、但是，相应的排序列如何与其进行关联呢？

### What is expected?
我理解 Table 组件以及 columns 上的`sortDirections`应该是用来自定义排序标识的。但从你们的类型定义上看，并不是

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/duo-lie-pai-xu-antd-4-17-0-alpha-0-forked-ity4i?file=/index.js

https://ant.design/components/table-cn/#components-table-demo-head

**Comment by chenxiaochun** [comment]
我的意思是：`sortDirections`是不是可以支持自定义排序值，例如可以设置成`sortDirections={['asc', 'desc']}`。因为实际业务中使用的排序可能跟 antd 中的默认值是不一样的。所以，每次都需要进行转换

**Comment by afc163** [comment]
可以支持，这个属性就是用来自定义排序值的。

**Comment by chenxiaochun** [comment]
但是：

1. 通过从`sortDirections`的类型定义来看，确实不支持定义成`sortDirections={['asc', 'desc']}`啊

```js
export declare type SortOrder = 'descend' | 'ascend' | null;

export interface TableProps {
  sortDirections?: SortOrder[];
}
```

2. 我上面提供了在线 demo，即使忽视类型错误，直接定义成`sortDirections={['asc', 'desc']}`，也是有问题的

**Comment by afc163** [comment]
是 `sortDirections: ["ascend", "descend"]`，请看我提供的 codesandbox。

**Comment by chenxiaochun** [comment]
您说的是 column 上的使用方式吧？我说的是 table 上的

**Comment by afc163** [comment]
Table 上目前不支持全局定义 `sortDirections`。

**Comment by chenxiaochun** [comment]
不支持吗？Table 上有这个参数啊？https://ant.design/components/table-cn/#Table

**Comment by afc163** [comment]
哦，支持的，请见 codesandbox： https://codesandbox.io/s/duo-lie-pai-xu-antd-4-17-0-alpha-0-forked-7k6sd?file=/index.js

**Comment by chenxiaochun** [comment]
```js
<Table
  sortDirections={["descend", "ascend"]}
  columns={columns}
  dataSource={data}
  onChange={onChange}
/>
```

`sortDirections`的默认值就是这个。我改成其它自定义值`sortDirections={["desc", "asc"]}`是不支持吗？

**Comment by yurentle** [comment]
这个问题为啥closed了，使用sortDirections={["desc", "asc"]}自定义后有两个问题：
1.列头上的排序按钮都不见了
2.会报类型错误

**Comment by chenxiaochun** [comment]
因为我当时好像放弃解决了。车轱辘话，说不明白😂
