### ISSUE TITLE
[4.17.0-alpha.3] I got some error tip when use npm/yarn build my application for node_modules/antd/lib/pagination/Pagination.d.ts

### ISSUE THREAD

**Issue by conero** [ant-design/ant-design#32222]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
yarn/npm build, dev is ok.
```
node_modules/antd/lib/pagination/Pagination.d.ts:3:18 - error TS2430: Interface 'import("~/node_modules/antd/lib/pagination/Pagination").PaginationProps' incorrectly extends interface 'import("rc-pagination").PaginationProps'.
  Types of property 'itemRender' are incompatible.
    Type '((page: number, type: "next" | "prev" | "page" | "jump-prev" | "jump-next", originalElement: ReactElement<HTMLElement, string | JSXElementConstructor<any>>) => ReactNode) | undefined' is not assignable to type '((page: number, type: string, element: ReactNode) => ReactNode) | undefined'.
      Type '(page: number, type: "next" | "prev" | "page" | "jump-prev" | "jump-next", originalElement: ReactElement<HTMLElement, string | JSXElementConstructor<any>>) => ReactNode' is not assignable to type '(page: number, type: string, element: ReactNode) => ReactNode'.
        Types of parameters 'type' and 'type' are incompatible.
          Type 'string' is not assignable to type '"next" | "prev" | "page" | "jump-prev" | "jump-next"'.

3 export interface PaginationProps extends RcPaginationProps {
```

**Comment by conero** [comment]
您好，这个是 typescript 在 vitejs 环境下的编译错误。即 `node_modules/antd/lib/pagination/Pagination.d.ts` 库的 **PaginationProps** 继承 **RcPaginationProps** 申明错误。https://codesandbox.io/ 暂时未发现创建此例子的方法。

![image](https://user-images.githubusercontent.com/19564821/133910282-332b6439-d526-46e1-a25a-7ed52583dce3.png)

调整如下，无异常提示。

![image](https://user-images.githubusercontent.com/19564821/133910299-05209cd9-bbc7-4239-8f49-1787ede1d72c.png)

**Comment by conero** [comment]
**v4.16.13 是这样的**
![image](https://user-images.githubusercontent.com/19564821/133910790-66b42c68-5a3e-495e-a39b-4ddcc4700948.png)

**Comment by mfka** [comment]
Looks like someone forget to bump up the rc-pagination version to 3.1.12 https://github.com/react-component/pagination/blob/v3.1.12/rc-pagination.d.ts 🤦‍♀️
