### ISSUE TITLE
Ghost hover style is broken

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ant-design/ant-design#32236]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ghost-button-antd-4-17-0-alpha-0-forked-es6vu?file=/index.js)

### Steps to reproduce
Hover over a ghost link and see that there's no hover effect.

### What is expected?
hover effect

### What is actually happening?
no hover effect

| Environment | Info |
|---|---|
| antd | 4.16.12 |
| React | 16.14 |
| System | Windows 10 |
| Browser | Chrome 93 |

---
Maybe caused by https://github.com/ant-design/ant-design/commit/ccf14fce682af9193da45302161cd86a98e98cef
hover OK in 4.16.11: https://codesandbox.io/s/ghost-button-antd-4-17-0-alpha-0-forked-5e114?file=/index.js

**Comment by zombieJ** [comment]
Your reproduce seems work as expect?

**Comment by justanotheranonymoususer** [comment]
Please try again. Broken example:
![image](https://user-images.githubusercontent.com/5781692/134294571-ec8162b9-64f5-48be-acd2-8221d89ae5ee.png)

Working example:
![image](https://user-images.githubusercontent.com/5781692/134294620-2f58cdc9-deb1-4415-b4b6-c91f4e27ebeb.png)

See the hover effect where the mouse is.

**Comment by justanotheranonymoususer** [comment]
Thank you, possible to backport to `4.16.x`?
