### ISSUE TITLE
Sometimes, `Typography` component render svg exception occurred in Safari.

### ISSUE THREAD

**Issue by hoboy0313** [ant-design/ant-design#32239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-typography-ofwgj?file=/src/App.tsx:9-19)

### Steps to reproduce
1. open the Codesandbox Project.
2. using the Safari to open that url.
3. Click any Title that it will open a new tab, and go back the project url.

### What is expected?
The svg can normal display.

[normal.jpg](https://postimg.cc/HJN8hN0H)

### What is actually happening?
The svg render Exception.

[exception.jpg](https://postimg.cc/phVcspB3)

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | MacOS Big Sur 11.1 |
| Browser | Safari version14.0.2 (16610.3.7.1.9) |

---
If it's no appear, please multiple attempt, because it's accidental appearance.

**Comment by zombieJ** [comment]
`ellipsis` with `suffix` will create a shadow DOM to get the width of text. Seems Safari refer to wrong id as path fill url. You can modify SVG to inline fill instead or not use `suffix`.

We can help less on this since it's Safari engine bug.
