### ISSUE TITLE
When you need to use a secondary table, set the table size to be small, and the style will not be centered

### ISSUE THREAD

**Issue by xingzhuJ** [ant-design/ant-design#32247]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-zhan-kai-antd-4-17-0-alpha-3-forked-vnxjl?file=/index.js)

### Steps to reproduce
Set the size to small

### What is expected?
Button centered

### What is actually happening?
Set the size to small, the style is the same as the normal table

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | mac |
| Browser |  93.0.4577.82（Google Chrome） |

![image](https://user-images.githubusercontent.com/40931443/134290354-60887a01-9a23-4cea-9b1c-7f56969d75f7.png)
![image](https://user-images.githubusercontent.com/40931443/134290395-1bbee7cb-8646-4b3d-8799-ea4aa7cc1cf5.png)

**Comment by DaoxingHuang** [comment]
![image](https://user-images.githubusercontent.com/19969260/134449503-f88b4573-acaa-46c8-8e69-06b91c367a30.png)
@zombieJ `float: left;` 的初衷是为了解决什么问题？感觉没有太大必要，当然也可以解决这个问题，请帮忙确认下。

**Comment by huytq085** [comment]
Same problem.
I manually add a class and set the float to 'none'.

**Comment by DaoxingHuang** [comment]
> Same problem. I manually add a class and set the float to 'none'. Hope it can be resolved.

remove float:left ,it is OK

**Comment by huytq085** [comment]
> > Same problem. I manually add a class and set the float to 'none'. Hope it can be resolved.
> 
> remove float:left ,it is OK

Yup. Thank you!

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/36215
