### ISSUE TITLE
Space align not working

### ISSUE THREAD

**Issue by volkans80** [ant-design/ant-design#32243]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/volkans80/pen/NWgzvrN?editors=001](https://codepen.io/volkans80/pen/NWgzvrN?editors=001)

### Steps to reproduce
Buttons not aligned to end.

### What is expected?
Buttons aligned to end.

### What is actually happening?
Buttons not aligned to end.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.x |
| System | Win 10 Last |
| Browser | Chrome last version |

**Comment by zombieJ** [comment]
Pls refer doc. It's use flex align and work as expect.

**Comment by volkans80** [comment]
I read documents but can't find it. Can you send a link?
Thanks,
