### ISSUE TITLE
Form.create包装的组件不能从外部调用函数

### ISSUE THREAD

**Issue by Phantom0i** [ant-design/ant-design#3224]
#### 发生问题的环境是：

- antd 版本: 1.11.0
- 操作系统及其版本: windows 7
- 浏览器及其版本: Chrome 48

#### 您做了什么？

使用Form.create包装了一个组件，并在外部调用自己实现的组件方法。
````js
class A extends React.Component {
  get value() {
    const value = 'I\'m value!';
    console.log('in: ', value);
    return value;
  }
  render() {
    return <span>A</span>
  }
}

A = Form.create()(A);

class B extends React.Component {
  render() {
    return (
      <div>
        <A ref="a" />
        <Button onClick={() => { console.log('out: ', this.refs.a.value) }}>Click me</Button>
      </div>
    );
  }
}
````
#### 您期待的结果是：

> in: i'm value!
> out: i'm value! 

#### 实际上的结果是：

> out:  undefined

#### 可重现的在线演示

[Link](http://codepen.io/Phantom01/pen/vXJKxg)

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/pull/2992

包装的层次太深了现在。。。

然后尽量别用 `ref`，因为这样会违反 React 的 functional paradigm：

https://facebook.github.io/react/blog/2016/09/28/our-first-50000-stars.html#archeology

> This was relevant for legacy interoperability and incremental adoption, and while React would eventually strive to be a lot more functional, `refs` proved to be a very useful way to break out of the functional paradigm when the need arose.
