### ISSUE TITLE
Incorrect type in docs for Typography.Text ellipsis prop

### ISSUE THREAD

**Issue by fgblomqvist** [ant-design/ant-design#32255]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/typography/#Typography.Text](https://ant.design/components/typography/#Typography.Text)

### Steps to reproduce
Check the ellipsis prop, it says it is a boolean. However that is not true. It can be a boolean or a limited version of the EllipsisConfig:
```
ellipsis?: boolean | Omit<EllipsisConfig, 'expandable' | 'rows' | 'onExpand'>;
```
The limited version is equivalent to:
```
export interface EllipsisConfig {
    suffix?: string;
    symbol?: React.ReactNode;
    onEllipsis?: (ellipsis: boolean) => void;
    tooltip?: React.ReactNode;
}
```

### What is expected?
The docs should be correct.

### What is actually happening?
They are incorrect.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | N/A |
| System | N/A |
| Browser | N/A |

**Comment by 1084350607** [comment]
I'll fix the doc tonight.
