### ISSUE TITLE
ant designer的LocaleProvider组件和react-router组件不兼容

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3225]
#### 发生问题的环境是：
windows 7 旗舰版64位 测试浏览器Chrome、使用nodejs 6.x+webpack构建
开发语言为es6

- antd 版本:2.0.0
- 操作系统及其版本:windows7旗舰版
- 浏览器及其版本:chrome

#### 您做了什么？

引入了LocaleProvider和例子中的程序，进行多国语言切换、配合react-router nested页面
#### 您期待的结果是：
页面的组件翻译跟随语言切换而切换

#### 实际上的结果是：
在react-router 的 嵌套的子页面 无法 根据 LocaleProvider的语言切换而切换，非子嵌套页面正常

#### 可重现的在线演示
内部项目无法提供演示 但是我的电话 15152238812

**Comment by eddyzhang1986** [comment]
我目前的解决办法为 调用react-router的push方法刷新一下当前页面，多国语言才会切换完毕, 但是我不知道这样的做法是否有问题

**Comment by eddyzhang1986** [comment]
似乎和这个问题类似
https://github.com/yahoo/react-intl/issues/365
这个是目前的解决办法
https://www.adibsaad.com/blog/integrating-react-intl-with-react-router
请问这样就可以了吗

**Comment by benjycui** [comment]
其实我们推荐的是不同语言使用不同的 HTML 文件作为入口，所以语言切换必然是刷新页面 [intl-example](https://github.com/ant-design/intl-example)。
