### ISSUE TITLE
最新的less-loader已弃用javascriptEnabled配置，现在应该如何使用如何modifyVars来自定义主题功能？

### ISSUE THREAD

**Issue by 01super** [ant-design/ant-design#32256]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/docs/react/customize-theme-cn](https://ant-design.gitee.io/docs/react/customize-theme-cn)

### Steps to reproduce
webpack: 5，less: 4.1.1，less-loader: 10.0.1

### What is expected?
能够继续使用定制主题功能

### What is actually happening?
定制主题无效

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | Windows |
| Browser | Chrome latest |

**Comment by afc163** [comment]
> 定制主题无效

请提供重现 repo 仓库。

**Comment by OlyLis1005** [comment]
你可能缺少了在 App.less 里引入 `@import '~antd/dist/antd.less';`
