### ISSUE TITLE
多个Cascader，若options相同，只要选择了其中一个Cascader，触发loadData，剩余所有的Cascader的loadData就和第一个完全一样

### ISSUE THREAD

**Issue by YU-zhao-jun** [ant-design/ant-design#32254]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-d4rvv?file=/app.jsx)

### Steps to reproduce
1.运行项目
2.选择左侧的Cascader
3.发现右侧的Cascader没有请求数据，直接使用左侧的Cascader

### What is expected?
右侧的Cascader应当请求数据，和左侧的Cascader数据结果不一样

### What is actually happening?
右侧的Cascader没有请求数据，和左侧的Cascader数据结果一样

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | windows |
| Browser | chrome |

---
在项目中，选择库区的时候，起始库区和目标库区是两个Cascader，起始库区选择了某个库区后，会加载特定状态的库位，而目标库区选择了同样的库区后，应该加载另外一种状态的库位，但是仍然加载了起始库区的库位

**Comment by afc163** [comment]
不应该复用同一个 fromCascaderOption，建议将数据隔离开。

**Comment by YU-zhao-jun** [comment]
项目中没有复用，从后端取得数据后，将数据通过slice方法深拷贝，结果仍然有这个bug, demo地址：&nbsp;https://codesandbox.io/s/antd-reproduction-template-forked-946gx?file=/app.jsx






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 多个Cascader，若options相同，只要选择了其中一个Cascader，触发loadData，剩余所有的Cascader的loadData就和第一个完全一样 (#32254)





 
不应该复用同一个 fromCascaderOption，建议将数据隔离开。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
