### ISSUE TITLE
日期控件里面的确认按钮"Ok"改成"OK"

### ISSUE THREAD

**Issue by ff148513** [ant-design/ant-design#32250]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-n06lu?file=/index.js)

### Steps to reproduce
随便拉个分支，加个日期范围控件

### What is expected?
OK两个字母大写

### What is actually happening?
O大写了，k是小写的

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | Mac 10.14.6 |
| Browser | Chrome Version 93.0.4577.63  |

---
海外的业务方很关注这些细节

**Comment by vnues** [comment]
其实官方提供了文案修改的接口，可以对其修改就行了

**Comment by xrkffgg** [comment]
@ff148513 @vnues 改下语言，很简单，欢迎 PR

**Comment by ff148513** [comment]
> @ff148513 @vnues 改下语言，很简单，欢迎 PR
英文拼写就是错的，怎么改语言

**Comment by yoyo837** [comment]
你俩沟通的没到同一个点上😂.

**Comment by xrkffgg** [comment]
> > @ff148513 @vnues 改下语言，很简单，欢迎 PR
> > 英文拼写就是错的，怎么改语言

组件国际化语言
