### ISSUE TITLE
2.0Metion缺少select回调

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#3226]
Metion组件缺少选择suggestion时的回调接口

**Comment by RaoHai** [comment]
可以添加这个回调。

仅仅是需要这样一个回调么？还是希望在这个回调里能做什么事情？

**Comment by qiaoyixuan** [comment]
仅仅需要这样一个会回调，我需要回调做一些自己的事情
case:选择完毕清空mentions=》onSearchChange=》fatch mentions from back end
