### ISSUE TITLE
Typography 组件基本示例英文排版错误

### ISSUE THREAD

**Issue by KAROTT7** [ant-design/ant-design#32261]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/typography-cn/#components-typography-demo-basic](https://ant.design/components/typography-cn/#components-typography-demo-basic)

### Steps to reproduce
基本示例英文标题下第二段文本 which aims touniform the user interface....

### What is expected?
英文单词之间应该有空格，所以应该是 which aims to uniform the user interface....

### What is actually happening?
which aims touniform the user interface....

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | N/A |
| System | win10 |
| Browser | chrome |

**Comment by 1084350607** [comment]
I'd like to fix it after 18:00.

**Comment by afc163** [comment]
Fixed in 87849a9
