### ISSUE TITLE
Antd Table with row select option with some actions, the dropdown arrow is partly visible when a column is left fixed

### ISSUE THREAD

**Issue by varsha675** [ant-design/ant-design#32268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/custom-selection-antd-4-17-0-alpha-3-forked-m1m0e?file=/index.js](https://codesandbox.io/s/custom-selection-antd-4-17-0-alpha-3-forked-m1m0e?file=/index.js)

### Steps to reproduce
- To the table add the Row select option.
- To the row selection add a custom select dropdown.
- Then make a column left fixed.

### What is expected?
Tables row select dropdown fully visible

### What is actually happening?
Tables row select dropdown is partly visible.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.8.2 |
| System | 1909 |
| Browser | 94.0.4606.54 |

**Comment by varsha675** [comment]
Link to reproduce the [issue ](https://codesandbox.io/s/custom-selection-antd-4-17-0-alpha-3-forked-m1m0e?file=/index.js)

**Comment by 1084350607** [comment]
1
