### ISSUE TITLE
About adding focus style after clicking button component

### ISSUE THREAD

**Issue by Kaiynn** [ant-design/ant-design#32260]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Clicking on the button component will add a focus style. Without doing anything, the style will remain until you click on other elements of the page. I try to modify the focus style, but it will conflict with the hover style (when the mouse clicks and does not move away).

### What does the proposed API look like?
Add an API to remove the foucs style.

**Comment by zombieJ** [comment]
Could you provide a reproduce about this conflict? Why it will conflict with hover style.
