### ISSUE TITLE
Class needs to be removed in <Popover/>

### ISSUE THREAD

**Issue by spencer741** [ant-design/ant-design#32275]
✅ I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
N/A

### Steps to reproduce
Simply render a normal popover component.

### What is expected?
I expect to be able to completely customize the entirety of the popover inner content.

### What is actually happening?
There is padding that is inserted via a child class of ant-popover-inner (which is provided by overlayInnerStyle prop) called ant-popover-inner-content. This class ant-popover-inner applies redundant padding and styling that does not need to exist.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | React 17 |
| System | Latest MacOSX |
| Browser | Latest Chrome |

---
There are multiple comments in issues that mention this and are completely valid. We need to be able to remove padding, or it doesn't need to be there at all. There is 0 use for it. The styling cannot be locally overridden since the class is sub-rendered by the popover component.

See this comment, which has some support: https://github.com/ant-design/ant-design/issues/11364#issuecomment-722771445

Below is what the DOM looks like. See comments below.

```html
<div class="ant-popover ant-popover-placement-bottom ">
  <div class="ant-popover-content">
    <div class="ant-popover-arrow">
      <span class="ant-popover-arrow-content"></span>
    </div>
    <div class="ant-popover-inner" role="tooltip" style="margin: 0px; padding: 0px; border: none;"> <!-- overlayInnerStyle -->
    <div class="ant-popover-inner-content"> 
    <!-- This class is adding unnecessary styling and prevents us from overriding locally. It needs to be removed.
      .ant-popover-inner-content {
            padding: 12px 16px;
            color: rgba(0, 0, 0, 0.85);
        } 
    -->
      <!-- Inner Content Goes Here-->
    </div>
  </div>
</div>

```

**Comment by afc163** [comment]
You can use `overlayInnerStyle` to remove default padding.

**Comment by spencer741** [comment]
@afc163 you actually cannot.

**Comment by JBotwina** [comment]
Same issue here. I have to incorporate this padding into my calculations

**Comment by spencer741** [comment]
@afc163 In the code block of the issue, OverlayInnerStyle applies 
To any-popover-inner, not to ant-popover-inner-content. 
OverlayInnerStyle needs to apply to ant-popover-inner-content, which is the direct wrapper of the inner popover. It does not need to apply to any-popover-inner (the parent of ant-popover-inner-content).

<div class="ant-popover-inner" role="tooltip" style="margin: 0px; padding: 0px; border: none;"> 
    <div class="ant-popover-inner-content">

**Comment by snrs-art** [comment]
we are using it in our design system and it seems this has been fixed in `4.9.2` https://ant.design/changelog#4.9.2
related pr: #27682

**Comment by Xxxdxs** [comment]
> we are using it in our design system and it seems this has been fixed in `4.9.2` https://ant.design/changelog#4.9.2 related pr: #27682

it works in tooltip, but seems like not work in popover.

**Comment by frei-x** [comment]
遇到同样的问题, 改用 Tooltip 了

**Comment by alexandebryakin** [comment]
Was able to address `ant-popover-inner-content` via `overlayClassName` property.

`Component.tsx`:
```tsx
import styles from './Component.module.scss'

<Popover
  // ...
  overlayClassName={styles.popoverNoPadding}
>
```

`Component.module.scss`:
```scss
.popoverNoPadding {
  :global(.ant-popover-inner-content) {
    padding: 0;
  }
}
```

**Comment by david7378** [comment]
> Thank you very much! I helped me a lot!

**Comment by amowu** [comment]
You can use the `getPopupContainer` props, which is inherited by **Tooltip**, **Popover**, and **Popconfirm**. Below is an example using styled components:

```jsx
import { useRef } from 'react';
import { Popover } from 'antd';
import styled from 'styled-components';

const Wrapper = styled.div`
  .ant-popover-inner {
    padding: 16px;
  }
`;

const App = () => {
  const popupContainerRef = useRef(null);

  return (
    <Wrapper ref={popupContainerRef}>
      <Popover
        getPopupContainer={() => popupContainerRef.current}
      />
    </Wrapper>
  );
}
```
