### ISSUE TITLE
Menu component show overflow indicator when Menu has enough space

### ISSUE THREAD

**Issue by antaiSlasify** [ant-design/ant-design#32277]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/runtime-silence-hpyjs)

### Steps to reproduce
1. Select the English option
2. reload the page
3. You can see the overflow indicator
4. But select the Chinese option and reload it works fine.

### What is expected?
Select the English option and reload the page, It should show all the menu items, not show the overflow indicator.

### What is actually happening?
Select the English option and reload the page, it cannot show all the menu items but show the overflow indicator.
The space of the Menu bar is enough.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Windows 10 Pro 21H1 |
| Browser | Chrome 94.0.4606.61 |

**Comment by sp4cecadet** [comment]
+1

**Comment by sp4cecadet** [comment]
Setting `overflowedIndicator={false}` as an attribute of the Menu wrapper worked as a temporary solution.

**Comment by antaiSlasify** [comment]
> Setting `overflowedIndicator={false}` as an attribute of the Menu wrapper worked as a temporary solution.

Thank you. But this solution doesn't work for me. 
The menu shows nothing when I set overflowedIndicator attribute as false.
I set the disabledOverflow attribute which is a private attribute to disable the overflow calculation.
This is my temporary solution to workaround.

**Comment by afc163** [comment]
```diff
.appHeader_menuContainer {
+ min-width: 100%;
}
```

```diff
.ant-menu-dark.ant-menu-horizontal {
+ flex: 1;
}
```

**Comment by bigbean17** [comment]
Hi @antaiSlasify , did you add `disabledOverflow={true}` for `<Menu>`? I add that to Menu tag but it seems messed up the layout of menu. Thanks
<img width="170" alt="image" src="https://github.com/ant-design/ant-design/assets/69971426/8df39f31-4f3a-4888-84a1-7d4af04ff144">

**Comment by smy329** [comment]
> > Setting `overflowedIndicator={false}` as an attribute of the Menu wrapper worked as a temporary solution.
> 
> Thank you. But this solution doesn't work for me. The menu shows nothing when I set overflowedIndicator attribute as false. I set the [disabledOverflow attribute](https://github.com/react-component/menu/blob/master/src/Menu.tsx#L56-L57) which is a private attribute to disable the overflow calculation. This is my temporary solution to workaround, but I think it's not a good way.

Thank you. This solution worked for me.
