### ISSUE TITLE
url-loader配置问题

### ISSUE THREAD

**Issue by wboykron** [ant-design/ant-design#3227]
#### 发生问题的环境是：

- antd 版本:1.1
- 操作系统及其版本:window10
- 浏览器及其版本:chrome 53.0.2785.116

#### 您做了什么？
在webpack.config.js中引入url-loader配置，配置如下：
webpackConfig.module.loaders.unshift({
    test: /\.(gif|jpg|png|woff|svg|eot|ttf)\??.*$/,
    loader: 'url-loader?limit=500000&name=[path][name].[ext]'
  });

#### 您期待的结果是：
能够编码图片而且能够正常显示

#### 实际上的结果是：
能够编码，但是不会显示，编码出现问题。同一张图片使用不同编码方式（在线编码能够正确显示）：
url-loader编码：data:image/png;base64,bW9kdWxlLmV4cG9ydHMgPSAiZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFIVUFBQUFtQ0FZQUFBRDZIdFRsQUFBR0swbEVRVlI0MnUyYlcyd1ZSUmpIRHhTTFJhQlVpNEJndFZxUktuMUFpR0FFTlFUVEI1V2JJT0lsUE5RWUlsRkxWV3BDQ0FvaE5FMlVFaFdEaVZxTlJLTUpNVXFhSU1WYnRaQ1VlcWxSRTJpUlJrQUVxYldVZ29WMi9ZLzVOdmt5ek96TW50MXp6bGIzNGZleSs4MTJkMzVuYnQ5TUU0N2pKS0xJdGVOYS9USUlsSU4yY0FxOEIwWWJ5bVNCb1g3L1ZsVHJ6Q1h4SDVLNkRqZ1NQNERobWg5QUJUZ0p6b0kzUUc0c05WcFNyd2ZuRkZJZGtpM0hiMUhFZlF1R3hWS2pJN1ZLSTFUd0c3Vk1OM2FaUit5bVdHcDBwSDdsSVVwUVJIRTU0SGVQdUI1TmR4MUx6WURVZ3dhcHQxSGNJa01jajQybFpsanFmb09vV3p3bVV6SjN4bEtqSWJYT0lNcGQybXcweEowSGw4WlMweXQxREhXUDQ2VHJGUjZpbWxuY0tvUFVUK09KVW5xbHJtSExsajd3RnB2VWpBTEhOYUtXc21mTThCRGFEMmJIVXRNbnRjeWpaUTJobUZKd1JycGZLeTFuQkxzMXo2cU9rdy9wa3pvWUhQWm9ZU3RaN0dUd0NuZ0hQS2dRbXFETVVTMWxraHhxNFUreTJBbmdVZXFxNzFXbEVXT3B3YVhPTW95REI1SklLUXF5d1pXVS8rV0ppVjdwK2VJSE5UV1dHcTdVTlJiTGtKd2t4WExHSzdwdmx5TThLUkZMRFM3MU5RdXBZMEtRK3JUaGIxUU1HS250MllNaUNhdnNGeTJrcWhMeCtlQlpVQS8yZ25mQlhacHhWckROOERlK2NHT2pXbWN1QTBIcUVrTmwvNm9RVkVyYmFxcjRlazJDNFJQRDN6bVVRYWtqUVNWalJsaFNoNExjRkw3NGVMQ1ZRNVY0aWNjYVZMV3pVa3FaSVM5QmV4V3QrMHREbVlNQnBHYUJQQVU1aG5MREthNEVPSXpuTmMvN2w0UVViRU1YMkFubWhpeFZmbkdIVmZnRG1vcHVsMDQzaUV6VENZdnVXckJWa3JyREVOOU1RcDBRMlVqZkh1WXpuYUFQM0p3bXFZTDcyVzVNRjNnYlhDR2RadGhwS2RSbEVTdGZZNGg5L2Y4aVZUQXJUVkpkUm1pdXIyWUNqb0ZkaHIxVFFTY29wdkxUS1ZXb2k3MmRTVDBGT3NBeDBFWTBnMzJnVmZxT2RyQkxRNWxDcWxzZm84QWNZcWFtenZKWnpEUStwc3FTaGxIZlhBZ21nNXVwMEVLd2tsNHlGYTMxZ25ISHgzTGtNVWxBQTd2bldDUXZMcWZZU3NWNDNDOGZpVEY4eDNhcGZwWllmTHNzdFFEY3g2NGRBZGNvS0dNeFRlNTFsVlRUWkdpaEZQOVJpbWUvSnA1U3REQS9VdDBEYXU3WVhBZ2VvYVRIQ3RhU3VkUnlVS1ZnRStpWDZ1ZGxUV3lWaDlUMnNMdmZDWVlLbnkvRmYrRHhxMU54Qm53TkZodCtzWTdGa2RCcWpTUy9VZ1hmZ2N0c2ZraDR0NWFReHIrMFNiM09RK2dJOExrVVgrbFRLcWZHVUZaWHNTSXR1RjNSVFhZUWRVbElGWHhQQ1gyZFRKZFVTdzI5KzkyakdkVHJ3UWxGcXlzSUlGVndqMCtwdWRRU1hSRmlqM1dEUjZyUW9jUkNNVTJ5dU1SV2NDTVlLU1V6U254STlUdTAyRWhOME9TSVQ3WlV6M3FJeFRSNFRaUnM2UVVQKy95ZzBhQldlazZURDZsWk5LdmxyWE8rb2J0MEtBV29hcmt0bXV1ZHFnTm9HWlRhUjdOdG1WNFc4MWtZVXI4aFNYNC9hclppeW04cjlYR1BCSUpvWGV2cERQQnlTNmx0SHQzMFNkcWFpNEpVRTZkNU1pam9PdlVuR21mOXR0WmtwSXBXZWxTcStDbHMyK3kweDBSSko3WGRNUGErbEtFeFZhdy9KNEtwbGt4azQreFlWVVV1OWlpOGdFVHkrT2NrYWVJWDFnak9XMzZZcmRUcGlrclBaOWttSndtcEhRYXBYWHdUUFkxU3R3UjQ1ZzVWUlJZWVd0cFZVdnpQN0Y0aGRRVitYc0pXNmxKRnBidmQ0N3drcFhaYXpKS0xCcGpVR2xWRjVobWtEZ0huV1B6ZjdONW1SVjhmbHRTNWlncGZRUGN1cGttUGpWUTVQMnlTV3B5Qk1YVVNyVGprVmNrZDFNWGVBRjRBM2V4K216dXVxaW95MitPRnJnYnJwZmcrZG4rUGRHK1N4WWZaU2kxV1ZIZ2pIUTlOMEFFeE1XT2RBNlpKc2hvc2tnbzZxWGtabWlnbGFMZzd3TzcxME9yaHFIUnRMZC9HQ3lPaGY0aTlSQ083M2syL3FqemFpdzBxVldTUWZ0R2NIM3FHZDVNYVdlK0RtM3hLM1ovQjJhK0xrTFZhV3I2NGZFeEQzZ1diNUVHbGJtQVBYSlZFZVQ5TG1pZDhab2lDc2k1RHM5OFNOam1kQno3VWxEOE1YZ1Vyd04xVUxqZW8xTjIwcStPK25PaTY2MUlvOVNJNnRaQU9vY2ZaN0RvVlVudVN5UDMyMHdaS1M1ajdxWDIwaHloT1Bpd0RnelVUcVhKcExBaExhb0tTN25XV1lqcHBBclVQL0FqK3NpejNCNWlad3R6dldlcFNiYVgrQ2Q0RVUxampXYTU3ajhpZmpQTVlBMjhGYXltcjVGSk5lNnZpZjJMR2Fzb1YwZGJhTmhMZVFTSzdRUk4xdWZtRzNHK2srUWNKUUtkM1FidGxDUUFBQUFCSlJVNUVya0pnZ2c9PSI=
在线base64编码：
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHUAAAAmCAYAAAD6HtTlAAAGK0lEQVR42u2bW2wVRRjHDxSLRaBUi4BgtVqRKn1AiGAENQTTB5WbIOIlPNQYIlFLVWpCCAohNE2UEhWDiVqNRKMJMUqaIMVbtZCUeqlRE2iRRkAEqbWUgoV2/Y/5NvkyzOzMnt1zzlb34fey+812d35nbt9ME47jJKLIteNa/TIIlIN2cAq8B0YbymSBoX7/VlTrzCXxH5K6DjgSP4Dhmh9ABTgJzoI3QG4sNVpSrwfnFFIdki3Hb1HEfQuGxVKjI7VKI1TwG7VMN3aZR+ymWGp0pH7lIUpQRHE54HePuB5Ndx1LzYDUgwapt1HcIkMcj42lZljqfoOoWzwmUzJ3xlKjIbXOIMpd2mw0xJ0Hl8ZS0yt1DHWP46TrFR6imlncKoPUT+OJUnqlrmHLlj7wFpvUjALHNaKWsmfM8BDaD2bHUtMntcyjZQ2hmFJwRrpfKy1nBLs1z6qOkw/pkzoYHPZoYStZ7GTwCngHPKgQmqDMUS1lkhxq4U+y2AngUeqq71WlEWOpwaXOMoyDB5JIKQqywZWU/+WJiV7p+eIHNTWWGq7UNRbLkJwkxXLGK7pvlyM8KRFLDS71NQupY0KQ+rThb1QMGKnt2YMiCavsFy2kqhLx+eBZUA/2gnfBXZpxVrDN8De+cGOjWmcuA0HqEkNl/6oQVErbaqr4ek2C4RPD3zmUQakjQSVjRlhSh4LcFL74eLCVQ5V4iccaVLWzUkqZIS9BexWt+0tDmYMBpGaBPAU5hnLDKa4EOIznNc/7l4QUbEMX2AnmhixVfnGHVfgDmopul043iEzTCYvuWrBVkrrDEN9MQp0Q2UjfHuYznaAP3JwmqYL72W5MF3gbXCGdZthpKdRlEStfY4h9/f8iVTArTVJdRmiur2YCjoFdhr1TQScopvLTKVWoi72dST0FOsAx0EY0g32gVfqOdrBLQ5lCqlsfo8AcYqamzvJZzDQ+psqShlHfXAgmg5up0EKwkl4yFa31gnHHx3LkMUlAA7vnWCQvLqfYSsV43C8fiTF8x3apfpZYfLsstQDcx64dAdcoKGMxTe51lVTTZGihFP9Rime/Jp5StDA/Ut0Dau7YXAgeoaTHCtaSudRyUKVgE+iX6udlTWyVh9T2sLvfCYYKny/Ff+Dxq1NxBnwNFht+sY7FkdBqjSS/UgXfgctsfkh4t5aQxr+0Sb3OQ+gI8LkUX+lTKqfGUFZXsSItuF3RTXYQdUlIFXxPCX2dTJdUSw29+92jGdTrwQlFqysIIFVwj0+pudQSXRFij3WDR6rQocRCMU2yuMRWcCMYKSUzSnxI9Tu02EhN0OSIT7ZUz3qIxTR4TZRs6QUP+/yg0aBWek6TD6lZNKvlrXO+obt0KAWoarktmuudqgNoGZTaR7NtmV4W81kYUr8hSX4/arZiym8r9XGPBIJoXevpDPByS6ltHt30Sdqai4JUE6d5MijoOvUnGmf9ttZkpIpWelSq+Cls2+y0x0RJJ7XdMPa+lKExVaw/J4Kplkxk4+xYVUUu9ii8gETy+OckaeIX1gjOW36YrdTpikrPZ9kmJwmpHQapXXwTPY1StwR45g5VRRYYWtpVUvzP7F4hdQV+XsJW6lJFpbvd47wkpXZazJKLBpjUGlVF5hmkDgHnWPzf7N5mRV8fltS5igpfQPcupkmPjVQ5P2ySWpyBMXUSrTjkVckd1MXeAF4A3ex+mzuuqioy2+OFrgbrpfg+dn+PdG+SxYfZSi1WVHgjHQ9N0AExMWOdA6ZJshoskgo6qXkZmiglaLg7wO710OrhqHRtLd/GCyOhf4i9RCO73k2/qjzaiw0qVWSQftGcH3qGd5MaWe+Dm3xK3Z/B2a+LkLVaWr64fExD3gWb5EGlbmAPXJVEeT9Lmid8ZoiCsi5Ds98SNjmdBz7UlD8MXgUrwN1ULjeo1N20q+O+nOi661Io9SI6tZAOocfZ7DoVUnuSyP320wZKS5j7qX20hyhOPiwDgzUTqXJpLAhLaoKS7nWWYjppArUP/Aj+siz3B5iZwtzvWepSbaX+Cd4EU1jjWa57j8ifjPMYA28Faymr5FJNe6vif2LGasoV0dbaNhLeQSK7QRN1ufmG3G+k+QcJQKd3QbtlCQAAAABJRU5ErkJggg==

**Comment by afc163** [comment]
和 antd 无关，建议去 webpack 相关论坛进行提问。

**Comment by wboykron** [comment]
我用非antd-init新建的项目，url-loader正常打包且可以显示，這应该不是webpack的问题吧？wepback配置如下：
var webpack = require('webpack');
var path = require('path');
var ExtractTextPlugin = require('extract-text-webpack-plugin'); //抽取CSS文件插件
var OpenBrowserPlugin = require('open-browser-webpack-plugin'); //自动打开浏览器插件

module.exports = {

    // 配置服务器
    devServer: {
        historyApiFallback: true,
        hot: true,
        inline: true,
        progress: true,
        contentBase: "./app", //最好写上，否则报错，难道这里是一个坑？
        port: 8080
    },

    // 配置入口
    entry: [
        path.resolve(__dirname, 'app/src/main.jsx')
    ],
    output: {
        // path: 'dist',  //不写居然也没事，由于有服务器，生成不了静态文件，这也是一个坑
        publicPath: 'dist',
        filename: '[name].bundle.js'
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') }, //坑：不能用叹号链接，必须写成这种格式
            { test: /\.less$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader', 'less-loader') },
            { test: /\.js[x]?$/, include: path.resolve(__dirname, 'app'), exclude: /node_modules/, loader: 'babel-loader' },
            { test: /\.(png|jpg)$/, loader: 'url?limit=81920' },
            { test: /\.(woff|woff2|eot|ttf|svg)(\?.*$|$)/, loader: 'url' }
        ]
    },
    resolve: {
        extensions: ['', '.js', '.jsx'],
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin('common.js'),
        new ExtractTextPlugin("style.css"),
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        }),
        new webpack.HotModuleReplacementPlugin(),
        new OpenBrowserPlugin({ url: 'http://localhost:8080' })
    ]
};
