### ISSUE TITLE
InputNumber框，聚焦时，setState设置值，数字框内的内容没渲染正确

### ISSUE THREAD

**Issue by Jeggery** [ant-design/ant-design#32274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-3-forked-zx02x?file=/index.js)

### Steps to reproduce
一、bug步骤
1. 点击上下箭头进行设置数字
2. 设置数字后，可按ctrl z进行撤销数字(此时鼠标焦点在输入框内)
3. 撤销时，会对原本设置过的数字复原，进行setState
4. 此时输入框内的显示未进行变化

二、非bug
1. 点击上下箭头进行设置数字
2. 鼠标点击空白处，让输入框失去焦点
3. 撤销时，会对原本设置过的数字复原，进行setState
4. 此时输入框内的显示会正常按照复原数字显示

补充：撤销功能逻辑写在componentDidMount函数里

### What is expected?
点击上下箭头修改数字时，焦点聚焦在输入框，也要能进行正常的setState UI渲染，并使输入框内容发生变化

### What is actually happening?
输入框内容未发生变化

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14 |
| System | win10 |
| Browser | chrome 93版本 |

---
正在做一个撤销回退功能，设置InputNumber数字后，也要能正常撤销回退数字

**Comment by DaoxingHuang** [comment]
@Jeggery  这个建议使用keyup事件，对于 keydown事件，一般认为是用户正在做什么，代表事件尚没有输入完成；
InputNumber 内部有防守策略 
![image](https://user-images.githubusercontent.com/19969260/134799219-269e4457-40f5-45d5-b78d-9a8e5f4744b9.png)
或是添加 formatter :
![image](https://user-images.githubusercontent.com/19969260/134799272-f9c4f87d-b5eb-4784-9f2a-5428a06e175b.png)

@zombieJ @afc163 [代码位置](https://github.com/react-component/input-number/blob/83e3c22002edfb9f57eab38d1a7b2210293e1da0/src/InputNumber.tsx#L482)
加外 逻辑 判断 `newValue.isNaN()` 意欲何为 ，我咋老觉得这个应该 return ，类似于：
![image](https://user-images.githubusercontent.com/19969260/134800795-64683bb3-375e-416f-95dc-df8e3c71e3f2.png)
求指教

**Comment by zombieJ** [comment]
上面注释写了，如果受控 `1.2` 变成 `1.` 时不能直接变成 `1`，而是需要等用户继续输入。

**Comment by Jeggery** [comment]
> @Jeggery 这个建议使用keyup事件，对于 keydown事件，一般认为是用户正在做什么，代表事件尚没有输入完成；
> InputNumber 内部有防守策略
> ![image](https://user-images.githubusercontent.com/19969260/134799219-269e4457-40f5-45d5-b78d-9a8e5f4744b9.png)
> 或是添加 formatter :
> ![image](https://user-images.githubusercontent.com/19969260/134799272-f9c4f87d-b5eb-4784-9f2a-5428a06e175b.png)
> 
> @zombieJ @afc163 [代码位置](https://github.com/react-component/input-number/blob/83e3c22002edfb9f57eab38d1a7b2210293e1da0/src/InputNumber.tsx#L482)
> 另外 逻辑 判断 `newValue.isNaN()` 意欲何为 ，我咋老觉得这个应该 return ，类似于：
> ![image](https://user-images.githubusercontent.com/19969260/134800795-64683bb3-375e-416f-95dc-df8e3c71e3f2.png)
> 求指教
的确，改成keyup事件就ok了.但对于撤销来说，长按ctrl+z能撤销很多步

**Comment by zombieJ** [comment]
嗯，更新逻辑这块我看看怎么优化优化。`isNaN` 的确遇到这种输入态的调整有限。

**Comment by Jeggery** [comment]
> 嗯，更新逻辑这块我看看怎么优化优化。`isNaN` 的确遇到这种输入态的调整有限。

ok
