### ISSUE TITLE
component Mention传入value死循环

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#3228]
#### 发生问题的环境是：react 15.3.1

- antd 版本:2.0.0
- 操作系统及其版本:mac 10.11.6
- 浏览器及其版本:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

引入了 Mention并传入prop value={toEditorState('@qia')}

#### 您期待的结果是：

显示@qia

#### 实际上的结果是：

console出现死循环输出，浏览器卡死

**Comment by RaoHai** [comment]
http://codepen.io/RaoHai/pen/ozZdWo?editors=001 
挺正常的啊。。。

**Comment by woodccc** [comment]
出现了同样的问题，使用Mention组件，onChnage时把mentionValue放在state管理，mention的value值用存在state中的mentionValue，输入后始终显示为空。

```
<Mention
            suggestions={suggestions}
            onChange={this.handleChange}
            value={toEditorState(mentionValue)}
          />
```

```
 handleChange(value) {
    this.setstate({mentionValue: toString(subjectEditorState)})
  }
```
 
```
this.state = {mentionValue: ''}
```

**Comment by RaoHai** [comment]
```
handleChange(editorState) {
  this.setstate({mentionValue: toString(editorState)})
}
```

**Comment by RaoHai** [comment]
参考一下这个 

https://github.com/RaoHai/ant-design/blob/b010ba55196584f6bb5574dbe9ba82b606115fb0/components/mention/demo/controllder-simple.md

**Comment by woodccc** [comment]
@RaoHai 谢谢，我明白您的意思了。但是其实我的目的不是这个。
建议：将mentionTrigger和mentionPrefix区分开，效果如同[draft-js](https://www.draft-js-plugins.com/plugin/mention)

在项目里会遇到这样子的问题，实际上并不需要‘@’，但是现在不能将prefix置空，因为prefix已经和trigger绑定在一起了。

希望能解决，谢谢！

**Comment by RaoHai** [comment]
mentionPrefix 和 mentionTrigger 分开意味着 @mention 的内容一旦选定，则不可更改，只能全部删除。而现在 antd 的 mention 是被设计成可以任意时刻更改的。

**Comment by RaoHai** [comment]
不过你这个建议挺好的。我看看能不能做下改进。

**Comment by woodccc** [comment]
@RaoHai 非常感谢。
