### ISSUE TITLE
InputNumber step 格式化未处理精度导致的问题

### ISSUE THREAD

**Issue by decision4fr** [ant-design/ant-design#32284]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stepchu-li-wei-shu-obd43)

### Steps to reproduce
Click step up twice
点击step的向上箭头两次

### What is expected?
输入框应该是502

### What is actually happening?
实际上是502.00000000000006
![image](https://user-images.githubusercontent.com/48681930/134644294-9d73ecad-94e2-450b-936c-a400d9e28f6a.png)

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 18.0.0 |
| System | win10 |
| Browser | Chrome 93.0.4577.82 |

**Comment by afc163** [comment]
这是 JS 计算精度问题：

<img width="349" alt="图片" src="https://user-images.githubusercontent.com/507615/134648184-98a77942-0fe4-4a65-a716-d8cec865d5ec.png">

建议自行做一下取整：https://codesandbox.io/s/stepchu-li-wei-shu-forked-05eqn?file=/index.js

**Comment by decision4fr** [comment]
这的确是精度问题，但是默认情况下都会根据step格式化数据，精度问题导致的怎么不格式化呢

**Comment by afc163** [comment]
有 precision 属性来处理精度。

https://codesandbox.io/s/stepchu-li-wei-shu-forked-n95dh?file=/index.js

**Comment by decision4fr** [comment]
> 有 precision 属性来处理精度。
> 
> https://codesandbox.io/s/stepchu-li-wei-shu-forked-n95dh?file=/index.js

虽然要额外传属性，不过也能解决问题
