### ISSUE TITLE
Carousel GoTo is ignored if animation is in progress

### ISSUE THREAD

**Issue by theGOTOguy** [ant-design/ant-design#32293]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reproduce-issue-whereby-calling-carousel-goto-during-animation-ignores-the-command-49o45?file=/index.js)

### Steps to reproduce
Create an antd Carousel component with multiple pages.  Send multiple goTo commands (without setting dontAnimate=true) to it in quick succession, and you will find that any goTo commands that reach the component while an animation in progress will be ignored.  

### What is expected?
Each goTo command should be processed, even if an animation is in progress.

### What is actually happening?
goTo commands that reach the component during animation are ignored.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Ubuntu 21.04 |
| Browser | Version 92.0.4515.131 (Official Build) (64-bit) |

**Comment by theGOTOguy** [comment]
I found that this issue can be worked around by setting the waitForAnimate parameter:

`<Carousel waitForAnimate={false} ...>`

What is clear is that the underlying issue lives in [react-slick](https://github.com/akiran/react-slick/blob/master/src/inner-slider.js) and not in antd proper.  Since `react-slick` has not been updated in a long time, it may be correct to address this issue in antd's Carousel in one of two ways:

1. Document waitForAnimate, alerting end-users that any instructions to change the slide may be ignored during animation unless waitForAnimate is set to false, or
2. Set waitForAnimate equal to false by default in Carousel and document it.  It [has been reported](https://github.com/akiran/react-slick/pull/1779) that setting waitForAnimate to false leads to jumpy animations.

If the maintainers have a preferred approach, I can submit a PR.

**Comment by afc163** [comment]
The second option seems to be better.

**Comment by theGOTOguy** [comment]
As I worked on validating a PR, I realized that `waitForAnimate={false}` greatly reduces the frequency with which the bugged behavior occurs, but it's still flaky.  I believe that to resolve this issue completely will require a fix to be implemented in react-slick.

**Comment by guan404ming** [comment]
I think if the component with ```waitForAnimate={false}``` would prevent more bugged behavior. Could I open a PR to add it ?

**Comment by guan404ming** [comment]
I think if Carousel with ```waitForAnimate={false}``` would prevent more bugged behavior. Could I open a PR to add it ?
