### ISSUE TITLE
slider 增加双滑块功能

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#323]
方便选择区间值。

![](https://t.alipayobjects.com/images/rmsweb/T1faNiXlpbXXXXXXXX.png)

**Comment by simaQ** [comment]
那个，放着我来

**Comment by afc163** [comment]
另外，拖拽时是有外描边的。

**Comment by afc163** [comment]
另外，`-active` 样式好像不起作用。

**Comment by simaQ** [comment]
恩，好的，我都一并写了。

**Comment by benjycui** [comment]
参考：https://jqueryui.com/slider/#range 实现
