### ISSUE TITLE
upload组件onChange只调用一次并且返回参数值只有uploading

### ISSUE THREAD

**Issue by mdzxy** [ant-design/ant-design#32305]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-burnell-quvte?file=/src/upload.jsx)

### Steps to reproduce
封装Upload组件，在其他地方调用，文件上传成功后，onChange无法获取上传更新后的状态

### What is expected?
能够正常监听file的状态并且返回file.status

### What is actually happening?
只会返回一次file，并且file.status一直都是uploading

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Mac OS X Big Sur 11.5.2 |
| Browser | Chrome 93.0.4577.82 |

**Comment by afc163** [comment]
你给的例子我没有重现出来。

**Comment by gokulthehunter** [comment]
![git](https://user-images.githubusercontent.com/29730696/134810520-0fa633b8-b463-405d-95e1-e2c30174006b.png)
@mdzxy am able to get `error` status from your example itself,  attached screenshot for the same
