### ISSUE TITLE
关于Input的一点疑问？

### ISSUE THREAD

**Issue by dodospace** [ant-design/ant-design#3230]
#### 发生问题的环境是：

- antd 版本: 1.7.0
- 操作系统及其版本: 各系统
- 浏览器及其版本: 各版本

#### 您做了什么？

引入了antd的Input组件，设置了defaultValue
`<Input defaultValue={this.state.name} onChange={this.onChange} />`

#### 您期待的结果是：

这个state的name根据父组件或者按钮其他事件变更当前name值，从而改变Input的defaultValue

#### 实际上的结果是：

组件只会在第一次初始化的时候设置一次defaultValue，后面除非卸载组件，否则组件被初始化后，是无法变更defaultValue的值。也就是说Input的值只能通过自身的输入来改变。

请问是我用法不对，还是Input就是这么被设定成这样的？

**Comment by codering** [comment]
defaultValue只是一个初始值，后面就不会变更。如果要绑定某个状态，用value属性

**Comment by dodospace** [comment]
懂了

**Comment by joyran** [comment]
@benjycui @codering 可是用了value 属性后是可以二次渲染了，但浏览器端却输入不了了，浏览器Google Chrome，版本 55.0.2883.95 (64-bit)
