### ISSUE TITLE
Switch设置了defaultChecked，触发页面刷新后，Switch状态值如何更新呢？

### ISSUE THREAD

**Issue by YingJian-hu** [ant-design/ant-design#32300]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-dh344?file=/index.js:754-768)

### Steps to reproduce
点击第二行中switch的。
注：本身想实现的功能是，点击switch，调用接口触发状态更新后，重新查询表格，刷新dataSource值，这里demo去掉更新动作，直接刷新dataSource的值

### What is expected?
table中的两行switch均变为关闭状态

### What is actually happening?
第二行中的Switch变为开启状态（setData触发刷新后，Switch默认值没变动）

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17  |
| System | mac |
| Browser | chrome 93.0.4577.82 |

**Comment by KAROTT7** [comment]
defaultChecked 表示的是初始状态，后续状态变更不会改变，除非 DOM 重建
如果要绑定变更请用 checked 属性

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
