### ISSUE TITLE
Select clear contents triggers both events onChange and onClear

### ISSUE THREAD

**Issue by kevinwang930** [ant-design/ant-design#32319]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-17-0-alpha-3-forked-dhs7k?file=/index.js)

### Steps to reproduce
see reproduction

### What is expected?
if onClear is defined, clear contents in select should only trigger onClear event

### What is actually happening?
clear contents triggers both events onclear and onChange

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | latest |
| System | win10  |
| Browser | firefox and chrome |

**Comment by afc163** [comment]
It is intented behavior, onChange event should be triggered when value is cleared.

**Comment by kevinwang930** [comment]
if so in common cases, onClear is not needed.
