### ISSUE TITLE
Tree - Style jitter [树形控件，样式抖动]

### ISSUE THREAD

**Issue by HkOri** [ant-design/ant-design#32310]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-3-forked-yz1io?file=/index.js)

### Steps to reproduce
just click switcher
点击开关

### What is expected?
style normal, indentation fixed.
样式不抖动

### What is actually happening?
the treenode style isn't fixed, its indentation has changed。
树形节点的缩进发生了变化

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS Catalina 10.15.7 |
| Browser | Chrome 91.0.4472.101 |

**Comment by zombieJ** [comment]
额。。。好像没看到 Switcher 。。。

**Comment by afc163** [comment]
就是点击小三角做展开收起，观察子节点。

**Comment by HkOri** [comment]
> Hello @HkOri. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @HkOri, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

demo: https://codesandbox.io/s/antd-reproduction-template-forked-h9xx4

**Comment by zombieJ** [comment]
![截屏2021-09-28 下午2 39 04](https://user-images.githubusercontent.com/5378891/135035888-ad1b3faf-1bea-4ca1-a456-1c6d6ac1f3e2.png)

Tree 结构变化时会创建容器做动画过渡，`:not(:first-of-type):not(:last-of-type)` 不是稳定结构。

**Comment by HkOri** [comment]
> ![截屏2021-09-28 下午2 39 04](https://user-images.githubusercontent.com/5378891/135035888-ad1b3faf-1bea-4ca1-a456-1c6d6ac1f3e2.png)
> 
> Tree 结构变化时会创建容器做动画过渡，`:not(:first-of-type):not(:last-of-type)` 不是稳定结构。

谢谢解答，不过我发现当我去掉ts的依赖之后，这个问题将不会发生，这算不算一个问题

**Comment by zombieJ** [comment]
两个应该没关系……ts 也不会影响已经编译的代码咧
