### ISSUE TITLE
Optimize Drawer animation

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#32317]
https://ant.design/components/drawer-cn/

现在的动画比较生硬，不太舒服，希望更顺滑敏捷。

**Comment by afc163** [comment]
@jljsj33 有空看看不？

**Comment by jljsj33** [comment]
为啥不用 base 了？？

**Comment by jljsj33** [comment]
感觉名字错了，，哈哈，，，你把 base-in 的属性改成 base-out 吧，，然后再看看？？
