### ISSUE TITLE
DirectoryTree loadData属性方法  获取数据接口请求失败时 reject, 没有取消loading效果

### ISSUE THREAD

**Issue by NgChiKin** [ant-design/ant-design#32313]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
使用DirectoryTree 去懒加载节点, loadData 是返回一个 promise, 但是在 promise里面去 reject 没有任何效果, 没有取消loading

### What is expected?
在loadData 函数里面去 reject 应该取消 loading 效果

### What is actually happening?
在loadData 函数里面去 reject 没有 取消 loading 效果

| Environment | Info |
|---|---|
| antd | 4.13.1 |
| React | 16.9.0 |
| System | window10 |
| Browser | chrome 94.0.4606.61 |

**Comment by NgChiKin** [comment]
> 你好@NgChiKin。请通过分叉此链接https://u.ant.design/codesandbox-repro或最小的 GitHub 存储库来提供在线复制。`Need Reproduce`如果 3 天内没有活动，则标记为 的问题将被关闭。
> 
> 你好@NgChiKin，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。可以你点击通过[此处](https://u.ant.design/codesandbox-repro)创建³³一个codesandbox或者提供一个最小化的GitHub的仓库0.3天内未跟进此问题将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

@afc163 demo: https://codesandbox.io/s/antd-reproduction-template-forked-jlgxq

**Comment by NgChiKin** [comment]
看了这个版本的代码, 竟然promise 没有 catch

**Comment by zombieJ** [comment]
没啥关系，看了一下是因为 `loadData` 失败后会重新尝试，往复失败就看起来一直是 loading 状态。

**Comment by simpleAndElegant** [comment]
我正在解决这个问题

**Comment by zombieJ** [comment]
@simpleAndElegant ，撞车了。那我这边不搞了

**Comment by simpleAndElegant** [comment]
还是大佬你来吧。
