### ISSUE TITLE
自定义控件数据验证不通过后，验证不通过的样式传递到了控件内部的对话框

### ISSUE THREAD

**Issue by hxynet** [ant-design/ant-design#32327]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我有一个自定义控件，内部包含了一个Input和一个图标，点击图标弹出对话框，对话框上方有两个文本框，用于输入搜索信息，点搜索按钮后，在下方显示一个列表，选择一个列表项后，关闭对话框并将选中的值写入到自定义控件的Input里，当将这个控件放在Form中后，因为无值引发验证不通过，Input出现红框，当点击图标弹出对话框后，对话框中的文本框也有红框，希望能够去除这个红框样式。

### What does the proposed API look like?
Model组件阻断验证错误样式的传递

**Comment by zombieJ** [comment]
Duplicate of #25880

**Comment by qazhub** [comment]
But #25880 does not provide any solution or guidance on this topic.
