### ISSUE TITLE
antd Table拖拽表格失效，报错

### ISSUE THREAD

**Issue by chao325** [ant-design/ant-design#32329]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)

### Steps to reproduce
拖拽表格报错

TypeError: (0 , N.arrayMoveImmutable) is not a function

### What is expected?
解决

### What is actually happening?
为解决

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 无 |
| System | Windows10 |
| Browser | 91.0.4472.114 |

**Comment by xrkffgg** [comment]
Mac 没报错。。。

有 Win 测试下呢？

**Comment by chao325** [comment]
我就是Windows10 啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月28日(星期二) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] antd Table拖拽表格失效，报错 (#32329)





 
Mac 没报错。。。
 
有 Win 测试下呢？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chao325** [comment]
对了，antd官网版本是 4.17.0

**Comment by zombieJ** [comment]
windows 下也是好的，升级一下游览器试试？
