### ISSUE TITLE
Using Autocomplete with InputNumber

### ISSUE THREAD

**Issue by jahshatta** [ant-design/ant-design#32326]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-l4gb9p](https://stackblitz.com/edit/react-l4gb9p)

### Steps to reproduce
Create AutoComplete with custom input with InputNumber

### What is expected?
Autocomplete field with only digits input

### What is actually happening?
1. Error when typing in input  
TypeError: Cannot read properties of undefined (reading 'value')
2. type="number" don't work as in single "InputNumber"

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Ubuntu 20.04.3 |
| Browser | Google Chrome 93.0.4577.63 |

---
Is there any way to use AutoComplete with InputNumber? I need a field with only digits

**Comment by zombieJ** [comment]
InputNumber `onChange` not return event object. You need HOC of InputNumber to give `onChange` event which provide `event.target.value`:

<img width="395" alt="截屏2021-09-28 下午5 41 36" src="https://user-images.githubusercontent.com/5378891/135063524-2844e6f1-54ab-40e2-807e-4a9653c589ce.png">

**Comment by jahshatta** [comment]
> InputNumber `onChange` not return event object. You need HOC of InputNumber to give `onChange` event which provide `event.target.value`:
> 
> <img alt="截屏2021-09-28 下午5 41 36" width="395" src="https://user-images.githubusercontent.com/5378891/135063524-2844e6f1-54ab-40e2-807e-4a9653c589ce.png">

Thank for answering.
And what about type="number"? How to pass it to input?

**Comment by zombieJ** [comment]
AutoComplete will replace sub component `type` props. When you HOC InputNumber, you can also ignore this.

**Comment by jahshatta** [comment]
Thanks you!

**Comment by swqeaaa** [comment]
@zombieJ hi could you please illustrate more about how to HOC InputNumber? thanks a lot!
