### ISSUE TITLE
Anchor(Affix) component is in the wrong position in a certain scenario（锚点，固钉组件在某种场景下位置不正确）

### ISSUE THREAD

**Issue by y805939188** [ant-design/ant-design#32336]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-16-11-forked-yej5n?file=/index.js)

### Steps to reproduce
1. 给 Anchor 组件一个 container，container 有自己的固定 height
2. 然后 container 之上还有一层 parent，这个 parent 也有一个固定的 height，但是这个 parent 的 height 小于 Anchor 组件的 container 的 height
3. 往下滑，会先触发 container 的滚动事件
4. 等 container 滑到低之后，由于 container 的 height 大于 parent 的 height，所以有一部分看不到
5. 再继续往下滑，就会触发 parent 的滚动事件
6. 此时 Anchor 组件的位置不再相对于 container 进行定位，因为不再触发 container 的滚动事件了，所以此时 Anchor 一直相对于浏览器进行 fixed
7. 等 parent 也完全滑到底之后，再往上滑，Anchor 的定位就飞了

### What is expected?
Anchor 定位正确

### What is actually happening?
Anchor 定位不正确

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16125/files
