### ISSUE TITLE
table ie10 报script1047 错误

### ISSUE THREAD

**Issue by lixiaolongxl** [ant-design/ant-design#32346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/19991767/80782191-adce5000-8ba7-11ea-91f7-41962c83fe8a.png](https://user-images.githubusercontent.com/19991767/80782191-adce5000-8ba7-11ea-91f7-41962c83fe8a.png)

### Steps to reproduce
打包至后再ie10上报script1047: 在 strict 模式下，函数声明无法嵌套在语句或块内。

### What is expected?
能正常显示

### What is actually happening?
打包至后再ie10上报script1047: 在 strict 模式下，函数声明无法嵌套在语句或块内。

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | window |
| Browser | ie10 |

---
可在hooks 文件加下找到useLazyKVMap.js  将dig 函数提出来调用

**Comment by xrkffgg** [comment]
IE 10 。。。

**Comment by lixiaolongxl** [comment]
Brother, other components are compatible with ie10, but only some are incompatible. This is one of them! My project needs to be compatible with ie10

**Comment by zombieJ** [comment]
v4 do not support IE10:

https://ant.design/docs/react/introduce#Environment-Support

**Comment by lixiaolongxl** [comment]
thank you
