### ISSUE TITLE
ant-message box alignment

### ISSUE THREAD

**Issue by Hashim1995** [ant-design/ant-design#32349]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I can't align the message box to the bottom left of the page. It would be nice if there was both horizontal and vertical alignment.

### What does the proposed API look like?
no any idea

**Comment by zombieJ** [comment]
Thanks for feedback. Currently we may not adjust the design of message since it's design to show on the top. You can  use notification instead : )
