### ISSUE TITLE
ant-select-dropdown-placement-bottomLeft changing min-width freeze Chrome if width is bigger than Field

### ISSUE THREAD

**Issue by fstn** [ant-design/ant-design#32340]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-with-search-field-antd-4-17-0-alpha-3-forked-5f605?file=/index.css:0-75)

### Steps to reproduce
Just set a css and click in the select field

### What is expected?
Chrome is not freezing

### What is actually happening?
Chrome is freezing

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14 |
| System | ALL |
| Browser | Chrome |

---
Same with last version and React 17

**Comment by zombieJ** [comment]
You can not only apply `min-width` on single of placement class. It makes align move `bottomLeft` to `bottomRight` and then find current width is well enough for origin placement which makes back to `bottomLeft`:

```diff
--  .ant-select-dropdown.ant-select-dropdown-placement-bottomLeft {
++  .ant-select-dropdown.ant-select-dropdown-placement-bottomLeft,
++  .ant-select-dropdown.ant-select-dropdown-placement-bottomRight {
      min-width: 1400px !important;
    }
```

https://codesandbox.io/s/select-with-search-field-antd-4-17-0-alpha-3-forked-p91r5?file=/index.css
