### ISSUE TITLE
layout 组件中 Content/Footer/Header组件根本未处理 hasSilder 属性，文档书写有误

### ISSUE THREAD

**Issue by MrLK123** [ant-design/ant-design#32352]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce
文档错误

### What is expected?
更正文档

### What is actually happening?
Layout.Header Layout.Footer Layout.Content API 与 Layout 相同 描述是错误的

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
嗯，去掉 `hasSider` 也就是普通的元素了。下面这个话的确用不着。
