### ISSUE TITLE
DatePicker日期选择框 BUG反馈

### ISSUE THREAD

**Issue by GuanJunMa** [ant-design/ant-design#32357]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
1. 点击区间选择时间
2. 点击上方日期
3. 进入到月份呢或者年份选择
4. hover出现1中选择区间时间的虚线框

### What is expected?
修复这个虚线框

### What is actually happening?
存在虚线框

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | windows |
| Browser |  Chrome 94.0.4606.61（正式版本） （64 位） |

**Comment by zombieJ** [comment]
哪个示例？

**Comment by GuanJunMa** [comment]
先选择9.2-9.3号。
