### ISSUE TITLE
notification 的 closeIcon 不要被覆盖了

### ISSUE THREAD

**Issue by wangcongyi** [ant-design/ant-design#32351]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
产品现在有个需求， 调用两次 notification.open  但 closeIcon 为不同

```js

const aaa = () => {
    notification.open({
      key: '1111',
      closeIcon: '11',
      message: '1',
      description: '111',
    })

    notification.open({
      key: '222',
      closeIcon: '22',
      message: '22',
      description: '22',
    })
  }

```

实际上 第二个之后的 notification 的 closeIcon 都会被 第一个 notification  覆盖了

### What does the proposed API look like?
调用 notification.open 都是单独的示例，除非调用 notification.config

**Comment by wangcongyi** [comment]
![企业微信截图_16329023758489](https://user-images.githubusercontent.com/13843979/135228796-0921aa3b-62d0-499a-b576-316672c377e3.png)

**Comment by kkkisme** [comment]
[![Edit 基本 - antd@4.17.0-alpha.3 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-3-forked-0cwr9?fontsize=14&hidenavigation=1&theme=dark)

**Comment by wangcongyi** [comment]
@zombieJ  https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-3-forked-0cwr9?fontsize=14&hidenavigation=1&theme=dark
