### ISSUE TITLE
date picker return TypeError: Cannot read properties of null (reading 'isBefore' | 'isAfter'| ...), 

### ISSUE THREAD

**Issue by miloudbelaabed** [ant-design/ant-design#32366]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-bwjuql?file=src%2FApp.js](https://stackblitz.com/edit/react-bwjuql?file=src%2FApp.js)

### Steps to reproduce
Just type (not pick) a date that not allowed to chose (disabled) in the range of disabled date and hit enter

### What is expected?
I expect to clear the datepicker input

### What is actually happening?
When i tape a date that i disable it, i got i problem d.before cannot read properties of null when i submit, d is null

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | React 17.0.2 |
| System | windows 10 Pro 64-bit (10.0,Build 19043) |
| Browser | google chrome 93.0.4577.82 (Official Build) (32-bit) |

---
You have a DatePicker and you have disabledDate={(d) =d.isBefore(Date.now())},
so when you put (write not pick a date that it is disabled using disabledDate it will crash and show your an error, "TypeError: Cannot read properties of null (reading 'isBefore')",

**Comment by anishkargaonkar** [comment]
@afc163 would like to pick this up. Can you give some pointers on getting started?

**Comment by miloudbelaabed** [comment]
the solution is to add validation of null before call isBefore function or ..., like disabledDate={d=>d&&d.isBefore(Date.now())}, it works
