### ISSUE TITLE
preferred way by design to get input value from ref

### ISSUE THREAD

**Issue by kevinwang930** [ant-design/ant-design#32368]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
use ref to get the value from input,
```
<Input ref={myRef} />
```
 one way is to use  `myRef.current.state.value`, I wander if that is the preferred way by design

### What does the proposed API look like?
a standard way to get value from input by ref

**Comment by afc163** [comment]
Please use `onChange` which is react way.

**Comment by kevinwang930** [comment]
@afc163  use `onChange`  in parent component to get value from `Input`, thanks !

**Comment by kevinwang930** [comment]
@afc163  `onChange` pass info from Input to its parent components, how to pass info from parent component to Input ?  to give an example : I use Input to set a path,  then at some point I want to reset the path, I need a method to set the Input to certain value after the Input component was mounted.  For now I can only use `ref.current.state.value`, is there a better way ?
