### ISSUE TITLE
<Mentions /> component does not show red border on error

### ISSUE THREAD

**Issue by amed** [ant-design/ant-design#32364]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-t2ueob?file=index.js](https://stackblitz.com/edit/react-t2ueob?file=index.js)

### Steps to reproduce
Setting validateStatus="error" of `Form.Item` has no visual effect

Check **Reproduction link** (which is stackblitz example based on the provided example **With Form** from [Mention documentations](https://ant.design/components/mentions/#components-mentions-demo-form)
In the example all fields has validateStatus="error". 

### What is expected?
Setting `validateStatus` for `<Form.Item />` should effect `<Mention />` component

### What is actually happening?
No red border is being set

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Mac/Linux |
| Browser | Firefox/Chrome - latest |

**Comment by dominikspiertz** [comment]
We actually have the same problem in our ui

**Comment by maciag-dev** [comment]
It seems like we also have a similar problem.
