### ISSUE TITLE
Add hideOnNoData to TablePaginationConfig

### ISSUE THREAD

**Issue by Camble** [ant-design/ant-design#32379]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/issues/32378

### What does the proposed API look like?
https://github.com/react-component/pagination/commit/e4b20a1ae4469d68f691c58f7cd68d5eaee038ae

**Comment by afc163** [comment]
`hideOnNoData` prop was not accepted: https://github.com/react-component/pagination/pull/183#issuecomment-506967392
