### ISSUE TITLE
How to control <Input.Password /> visibilty?

### ISSUE THREAD

**Issue by Mukhametvaleev** [ant-design/ant-design#32370]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
That gives us a possibility to control password **visible** state outside of **Input.Password** component

### What does the proposed API look like?
```jsx
<Input.Password visible={true || false} />
```

I am trying to create a Button to toggle all password fields visibility by one click.

**Comment by afc163** [comment]
```
visible ? <Input /> : <Input.Password  />
```

**Comment by Mukhametvaleev** [comment]
I want to toggle input's value visibility, not ReactElement itself.

https://github.com/ant-design/ant-design/blob/master/components/input/Password.tsx#L24
For now, there is no chance to get `visible` state value outside Input.Password?
