### ISSUE TITLE
React peer dependency issue (react-infinite-scroller@1.2.4)

### ISSUE THREAD

**Issue by jermyn626** [ant-design/ant-design#32388]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://no-link-its-just-a-question-about-npm-install](http://no-link-its-just-a-question-about-npm-install)

### Steps to reproduce
clone repo and do npm install

### What is expected?
It work

### What is actually happening?
It doesn't work

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | mac |
| Browser | none |

---
another react peer dependency issue:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: antd@4.17.0-alpha.5
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0" from react-infinite-scroller@1.2.4
npm ERR! node_modules/react-infinite-scroller
npm ERR!   dev react-infinite-scroller@"^1.2.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Comment by afc163** [comment]
trace https://github.com/danbovey/react-infinite-scroller/pull/284
