### ISSUE TITLE
table CheckBox 选中卡顿

### ISSUE THREAD

**Issue by YC725968** [ant-design/ant-design#32387]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在table select时，当数据大于200，选中速度变慢，出现卡顿，这个该怎么优化

### What does the proposed API look like?
如何优化表格的选中卡顿功能

**Comment by afc163** [comment]
See #25698
