### ISSUE TITLE
hideOnSinglePage: false does not work for count = 0

### ISSUE THREAD

**Issue by Camble** [ant-design/ant-design#32380]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hideonsinglepage-false-xb789)

### Steps to reproduce
Set hideOnSinglePage to false in pagination prop of Table component with no data

### What is expected?
When the table has no data, the pagination controls should remain visible, as per this comment https://github.com/ant-design/ant-design/issues/17348#issuecomment-506967318

### What is actually happening?
The pagination controls are hidden

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Sorry, there is no way to show the built-in pagination in Table when no data: https://github.com/ant-design/ant-design/issues/17348#issuecomment-520828191
