### ISSUE TITLE
InputNumber 建议添加【滚轮】增减数字，还有自动翻滚问题

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#3239]
有些有点年纪的用户都是手残党，键盘不溜，怎么说呢，为了操作更加简便吧。

还有个问题，不知道是不是这样设计的
描述：焦点在 InputNumber 上按一次上/下键松开键盘，隔一秒数字会自动翻滚，同时鼠标点其他地方焦点取消不掉，估计是bug吧

官网例子就是这样

**Comment by benjycui** [comment]
Bug 的问题等 rc-input-number 修复 https://github.com/react-component/input-number/pull/21

滚轮事件有需要的话，可以来个 PR。
