### ISSUE TITLE
关于ant-design 搭建的静态资源路径

### ISSUE THREAD

**Issue by nodestorm** [ant-design/ant-design#324]
ant-design 搭建的静态资源路径，里引用了ant-desgin中构建出来的地址如`<link rel="stylesheet" href="./dist/antd-0.9.1-beta11.min.css">` 文件，是否将这个资源也移至static中， 如果需要更新新的版本， 更新重新编译 static里的文件即可。 
好处， 其它人想使用ant-design搭建自己风格的网站的时候 比较方便的切换。

**Comment by bluemsn** [comment]
确实~

**Comment by yiminghe** [comment]
antd/lib/index.css
