### ISSUE TITLE
Tree Select 搜索框 如何去重标签

### ISSUE THREAD

**Issue by deerLoves** [ant-design/ant-design#32408]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例如自定义分组筛选国家的时候 Group1里面有China Group2 里面也有China 但是筛选框期望是只显示一个，同时Tree Node里面两个都进行勾选

### What does the proposed API look like?
Tree Select 搜索框可以去重标签

**Comment by zombieJ** [comment]
使用问题请移步 SO、SF 或者 Discussions
