### ISSUE TITLE
Yarn add antd has issues  /node_modules/antd/.yarn-metadata.json

### ISSUE THREAD

**Issue by suprim12** [ant-design/ant-design#32415]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/suprim12/redux-toolkit-saga__saas_app_client](https://github.com/suprim12/redux-toolkit-saga__saas_app_client)

### Steps to reproduce
Install react with yarn try to add package antd (yarn add antd)

### What is expected?
error

### What is actually happening?
don't know, stupid push

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | Linux |
| Browser | Chrome |

---
remove .yarn-metadata.json

**Comment by zombieJ** [comment]
Clean up yarn cache and reinstall. It's not antd file.
