### ISSUE TITLE
Pagination分页在QQ浏览器中的兼容问题

### ISSUE THREAD

**Issue by GuanJunMa** [ant-design/ant-design#32411]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
查看有调整每页展示数量一栏，内容无法全部展示，出现省略号

### What is expected?
完整展示“xx条/页”

### What is actually happening?
展示“xx条/...”

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | windows |
| Browser | QQ浏览器 v10.8.2 |

**Comment by GuanJunMa** [comment]
![image](https://user-images.githubusercontent.com/26791776/136642299-d6837d94-9a91-4185-9e22-490a64c42477.png)

**Comment by afc163** [comment]
QQ 浏览器内核停在 Chrome 70 不更新了，我们无法保持对老版本 Chrome 的支持。

https://github.com/ant-design/ant-design/issues/25195#issuecomment-667057314
