### ISSUE TITLE
TreeSelect树选择线性样式和图标不显示

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/ant-design#32419]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cong-shu-ju-zhi-jie-sheng-cheng-antd-4-17-0-alpha-5-forked-bx87o?file=/index.js)

### Steps to reproduce
1.设置 treeLine={true} 没有线；
2.treeIcon 设置后没有图片，设置 false 叶子节点 icon 也依然存在；

### What is expected?
1.设置 treeLine 可以和 Tree 一样有连接线；
2.可以和 Tree 一样 设置每个节点的 icon 。 
例如： 
`<Tree`
`          height={400}`
`          className={styles.typeTree}`
 `         showIcon`
 `         icon={<img src={type} />}`
 `         showLine={{ showLeafIcon: false }}`
 `         onSelect={onSelect}`
 `         treeData={treeData}`
 `       />
`
![image](https://user-images.githubusercontent.com/33448924/136651636-a70a7a1a-eff3-472a-b42e-484d7ef88e07.png)

### What is actually happening?
1.设置 treeLine={true} 没有线；
2.treeIcon 设置后没有 icon，设置 false 叶子节点的 icon 也依然存在。
`<TreeSelect`
  `                      placeholder="选择分类"`
   `                     treeLine={true}`
  `                      treeIcon={<img src={type} />}`
   `                     treeData={treeData}`
   `                     onChange={onChange}`
   `                     defaultValue={data?.sparesTypeName as number | undefined}`
     `                 />`
![image](https://user-images.githubusercontent.com/33448924/136651737-bf0098bf-ed88-4202-980c-ada5aa69a90e.png)

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | macOS Mojave |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/30705 4.17.0 还没有正式发布。
