### ISSUE TITLE
建议Menu的onOpenChange回调函数添加keyPath参数？

### ISSUE THREAD

**Issue by CrisLi** [ant-design/ant-design#3241]
现在Menu的onOpenChange回调函只返回了点击后的openKeys，可否将所点击的SubMenu的keyPath也返回回来，这样方便关闭其他未展开的菜单，不用像Demo中那样自己去算SubMenu的keyPath了。

修改后的API可能是如下格式：

onOpenChange	SubMenu 展开/关闭的回调	Function(openKeys: string[], keyPath: string[])

**Comment by benjycui** [comment]
`onOpenChange` 触发时，可能有多个子菜单的展开状态都发生了变化。

需要 `keyPath` 的场景参考这个 [例子](http://ant.design/components/menu/#components-menu-demo-sider-current)
