### ISSUE TITLE
日期范围组件支持选择单个日期

### ISSUE THREAD

**Issue by jinxiangqiang** [ant-design/ant-design#32445]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
筛选时可以选择开始日期不选结束日期，选择结束日期不选开始日期

### What does the proposed API look like?
[infinity]="true"

**Comment by afc163** [comment]
`allowEmpty`
