### ISSUE TITLE
Menu组件onOpenChange的回调参数类型与openKeys不兼容

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [ant-design/ant-design#32453]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-yfdme?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
openKeys?: string[];
onOpenChange?: (openKeys: React.Key[]) => void;

### What is expected?
openKeys?: React.Key[];
onOpenChange?: (openKeys: React.Key[]) => void;

### What is actually happening?
openKeys?: string[];
onOpenChange?: (openKeys: React.Key[]) => void;

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome正常版本 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/31343
https://github.com/ant-design/ant-design/issues/22851#issuecomment-609037631
