### ISSUE TITLE
Antd组件官网示例自定义筛选Reset没反应  4.17.0-alpha.5版本

### ISSUE THREAD

**Issue by wr404274848** [ant-design/ant-design#32454]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel](https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel)

### Steps to reproduce
点放大镜，输入内容点Search，再点Reset没反应

### What is expected?
点Reset显示所有记录

### What is actually happening?
点Reset没反应

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | Windows 10 家庭中文版 |
| Browser | Google Chrome 94.0.4606.71 |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/31809
