### ISSUE TITLE
[2.0.0]开发环境打印很多warn antd.js:28961,Warning: React.createElement(...): 

### ISSUE THREAD

**Issue by bestv2** [ant-design/ant-design#3245]
#### 发生问题的环境是：
chrome中 antd2.0.0版本，开发环境下控制台打印很多warn警告：

`antd.js:28961 Warning: React.createElement(...): Expected props argument to be a plain object. Properties defined in its prototype chain will be ignored.`

- antd 版本:
2.0.0
- 操作系统及其版本:
mac os 10.12
- 浏览器及其版本:
chrome 版本 53.0.2785.116

**Comment by afc163** [comment]
升级 react 版本到 `15.3.2`。

https://github.com/facebook/react/releases/tag/v15.3.2

https://github.com/facebook/react/pull/7724
