### ISSUE TITLE
垂直的 Radio.Group，配合更多输入框选项 ---- 当配合select组件时，当选择过一次值再次选择值时下拉框有问题

### ISSUE THREAD

**Issue by lovesunshine** [ant-design/ant-design#32477]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox]
(https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/radio-group-chui-zhi-antd-4-17-0-alpha-5-forked-w3inm?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1、点击 第四个选项 More
2、先选择一个值
3、更换选择，再次点击select框，此时会发现select下拉框会展开后立马收缩消失，导致无法再次选择值

### What is expected?
期望radio搭配 select下拉框可以多次正常选择选项

### What is actually happening?
仅当select首次选择时正常，非首次都会出现select下拉框出现又立马消失，导致无法选择的情况

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | ^16.14.0 |
| System | windows10 |
| Browser | 版本 94.0.4606.81（正式版本） （64 位） |

**Comment by afc163** [comment]
Duplicate of #25959

**Comment by lovesunshine** [comment]
Thank you so much~~~
