### ISSUE TITLE
v3升到v4 Tree组件中的dataRef属性没有了

### ISSUE THREAD

**Issue by liangshen001** [ant-design/ant-design#32476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
<TreeNode dataRef={node} />

### What is expected?
可以使用dataRef以为升级v4不需要改代码 实际改的挺多的 有没有现成可复用的hooks

### What is actually happening?
TS2322: Type '{ title: Element; key: string; dataRef: IRenderTreeItem; }' is not assignable to type 'IntrinsicAttributes & TreeNodeProps & { children?: ReactNode; }'.   Property 'dataRef' does not exist on type 'IntrinsicAttributes & TreeNodeProps & { children?: ReactNode; }'

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.9.0 |
| System | MacOS |
| Browser | safari |

**Comment by zombieJ** [comment]
`dataRef` 不是 Tree 的属性，是给 node 加了个 Tree 不消费的 props，然后自己又从 props 里取出来而已。迁移方案请参考现行的 v4 对应示例哈~
