### ISSUE TITLE
2.0.0 Select中defaultValue 不能选中

### ISSUE THREAD

**Issue by 393799203** [ant-design/ant-design#3248]
#### 发生问题的环境是：

- antd 版本:2.0.0
- 操作系统及其版本:MAC
- 浏览器及其版本:chrome 52.0.2743.116

#### 您做了什么？

<Select defaultValue="1101" onChange = {(value) => {this.state.formData.currency = value; this.setState(this.state);}}>
							    	<For each = "item" of = {this.state.currencyList || []} index = "index">
										<SelectOption key = {index} value = {item.itemKey}>{item.itemValue}</SelectOption>
									</For>
								</Select>

引入 antd 了 Input  发现升级2.0.0以后的defaultValue中传入相应的value之后，选中是选中了，但是上面显示的只是传进去得value 而不是这个value 对应的相应的项显示。。。

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

https://ant.design/components/select/#components-select-demo-basic

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by afc163** [comment]
不提供重现无法解决问题。
