### ISSUE TITLE
upload 如何捕捉错误

### ISSUE THREAD

**Issue by nodeman777** [ant-design/ant-design#3249]
#### 发生问题的环境是：

- antd 版本:2.0.0
- 操作系统及其版本: Microsoft Windows [版本 10.0.14393]
- 浏览器及其版本: 53.0.2785.116 m (64-bit)

#### 可重现的在线演示
http://codepen.io/ea7son/pen/kkoRKB

onChange 回调里面 file 的error 和status 都判断不?

**Comment by benjycui** [comment]
https://ant.design/components/upload/#components-upload-demo-basic

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
