### ISSUE TITLE
Popover中<video>标签全屏后出现样式错误

### ISSUE THREAD

**Issue by peterpuppy** [ant-design/ant-design#3250]
#### 发生问题的环境是：

antd 版本:2.0.0
操作系统及其版本: win7
浏览器及其版本: chorme

#### 您做了什么？

```
<video src={video_url} controls autoPlay></video>
<Popover
      content={content}
       title="视频播放">
       <Button type="primary">播放视频</Button>
</Popover>
```
全屏video操作，然后还原

#### 您期待的结果是：
再显示video的时候不全屏

#### 实际上的结果是：
Popover的宽度变成100%

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by peterpuppy** [comment]
sorry ,busy recently.
>http://codepen.io/peterpuppy/pen/qaybGL

Full screen this video

**Comment by GrayChoi** [comment]
The Popover self should be set width to 100% too.
```javascript
        //css
         .fullscreen {
           width: 100%
         }
         //jsx
          <Popover
              overlayClassName="fullscreen"
              content={content}
               title="视频播放">
               <Button type="primary" style={{width:'100%'}}>播放视频</Button>
          </Popover>
```

**Comment by afc163** [comment]
看到了，好诡异的问题。

**Comment by afc163** [comment]
chrome 下有这个问题，感觉是浏览器的实现机制导致的。

目前只能用 popupStyle 去限定弹出层的宽度。

http://codepen.io/anon/pen/QKVkGG
