### ISSUE TITLE
Abilty to customize the showTotal positioning on table pagination

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#32517]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hello everybody!

In my case, I would like to be able to change the pagination "showTotal" positioning to the right side of the screen. 
Is it possible to get the values and render some component freely?
I also tried to use the footer prop, but if you have pagination it ends up rendering before the pagination itself.

What I'm trying to achive is "represented" by the bellow image, keeping the paging itself on the left, and only moving the "totals" to the right.:

![antdImage](https://user-images.githubusercontent.com/87539237/137387081-cd24ea10-27c9-413f-96eb-6e737f523f0a.png)

### What does the proposed API look like?
Some props that would let us render something on the pagination container? Since we are using it in a table context. 
Or maybe a "paginationExtraContent", or a even simpler way, just a paginationTotalPosition, and use the existing position API.

Would be closer to a object notation: 

```ts
pagination={{
  onChange: handlePaginationChange,
  defaultPageSize: 30,
  current: 1,
  pageSizeOptions: ['10', '30', '50'],
  position: ['bottomLeft'],
  showTotal: {
    total: (total, range) => `${total}`,
    position: ['bottomRight']
    }
}}
```

**Comment by anjantalatam** [comment]
Hi @balboFK 
Did you find a solution for this? I would be glad to know.

**Comment by balboFK** [comment]
Hello @anjantalatam! 
I managed to do what I was trying just with styling the pagination component and using the "position" prop.

```ts
pagination={{
  size: 'small',
  position: ['bottomCenter'],
  defaultPageSize: 30,
  style: { marginTop: '18px', border: '1px solid #cdc1ff', borderRadius: '6px', padding: '4px' },
  pageSizeOptions: ['30', '60', '90', '120'],
  current: productionOrdersData?.currentPage,
  total: productionOrdersData?.totalRecordsCount,
  showTotal: handleTotal,
  onChange: (page, pageSize) => setPagination({ page, pageSize })
}}

const handleTotal = (total: number, range: [number, number]): JSX.Element => (
  <Text>Exibindo de <Text strong>{range[0].toLocaleString()}</Text> ao <Text strong>{range[1].toLocaleString()}</Text> de <Text strong>{total.toLocaleString()}</Text> Ordens de Produção</Text>
)
```
The results looks like this:

![Screenshot_2](https://user-images.githubusercontent.com/87539237/163805334-5f05e726-e14f-4fab-8987-6e7385aae658.png)

Does it help you?

**Comment by anjantalatam** [comment]
Yes.
Thank you @balboFK 

In my code, I used positioning to align it to the right.


```javascript
pagination = {{
...rest,
showTotal: (total, range) => (
      <span style={{ right: 0, position: "absolute" }}>
        Showing {range[0]}-{range[1]} of {total}
      </span>
    ),

}}
```

**Comment by balboFK** [comment]
@anjantalatam glad it helped!
Good job!
