### ISSUE TITLE
Tree 组件 loadData 加载数据，如果 loadData 方法里面有执行异步操作就会出现重复调用的情况

### ISSUE THREAD

**Issue by yanthink** [ant-design/ant-design#32519]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-x6otl?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
展开节点，执行 onLoadData 方法，onLoadData 方法里的 setTimeout 或其他异步函数会执行两次

### What is expected?
异步不要重复调用，不然会造成重复远程请求获取数据。

### What is actually happening?
重复调用异步函数

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS Big Sur 11.3.1 |
| Browser | chrome 94 |

---
loadData 方法里的 运行异步函数会调用两次，异步外面 console 打印会输出一次，如果用 alert 弹窗也会弹两次。

**Comment by zdJOJO** [comment]
怎么解决的a ?
