### ISSUE TITLE
antd.variable.css 包含多份 html css variable

### ISSUE THREAD

**Issue by maqi1520** [ant-design/ant-design#32529]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
 https://ant.design/ 官网也包含多分css variable

### What is expected?
移除冗余的 css variable

### What is actually happening?
antd.variable.css 包含多份 html css variable

![image](https://user-images.githubusercontent.com/9312044/137473068-1ba95f35-a31c-478e-adaf-a50f2e522da5.png)

| Environment | Info |
|---|---|
| antd |4.17.0-alpha.6 |
| React | 16.8 |
| System | mac |
| Browser | chrome 92.0.4515.159（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
`babel-plugin-import` 的用户需要保留每份 less import 的 html 副本，看起来不适合改成 reference。由于 `antd.varaible.min.css` 里是会去重的，这里优先级看起来不高。
