### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by jaitaiwan** [ant-design/ant-design#3252]
I apologize I don't speak another language other than english. It looks like http://ant.design is down.

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/3201

**Comment by benjycui** [comment]
Keep this issue open until DNS becomes stable.

**Comment by afc163** [comment]
@fengmk2 It seems not a proxy problems..

**Comment by fengmk2** [comment]
从nginx的日志看，内网vpn翻墙的时候根本没有任何请求进来，我还另外一个代理就有流量进来。

**Comment by afc163** [comment]
Seems ok now.
