### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by maryamrmz** [ant-design/ant-design#32531]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
https://codesandbox.io/s/dreamy-meadow-5c6qc?file=/src/index.js

### What is expected?
I expect to two submenu that were handled in the *filter* property of *table* component to work well.

### What is actually happening?
Two submenu that handled in the *filter* property of *table* component conflict with each other and the table does not work well.

| Environment | Info |
|---|---|
| antd | 4.12.0 |
| React | 17.0.1 |
| System | Ubuntu 20.04 |
| Browser | Chrome, version 94.0.4606.81 (Official Build) snap (64-bit) |

**Comment by afc163** [comment]
Your codesandbox cannot run.
