### ISSUE TITLE
[2.0.0]Form 新增 getFieldDecorator 作为 getFieldProps 的替代，是否还可以通过 this.props.form.getFieldInstance 获取实例

### ISSUE THREAD

**Issue by bestv2** [ant-design/ant-design#3253]
发生问题的环境是：
chrome中 antd2.0.0版本

antd 版本: 2.0.0
操作系统及其版本: mac os 10.12
浏览器及其版本: chrome 版本 53.0.2785.116

问题描述：
Form 新增 getFieldDecorator 作为 getFieldProps 的替代，是否还可以通过 this.props.form.getFieldInstance 获取Input？  
测试了一下，返回值为 undefined， 请问如何解决，需要调用该方法获取 Upload的实例
测试地址  https://codepen.io/bestv2/pen/YGxJzd  点击提交按钮，打开console 看 log  使用 getFeildsProps的 name属性可以getFieldInstance，而使用getFieldDecorator的属性image无法通过getFieldInstance获取实例

**Comment by benjycui** [comment]
哥，看下 change log 可好。

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by bestv2** [comment]
@benjycui 不好意思，change log只看到 新增 getFieldDecorator 作为 getFieldProps 的替代 ， 我想问的问题是 曾经 form.geFieldInstance 方法能获取实例现在使用getFieldDecorator后不能通过getFieldInstance方法获取了， change log中好像没有 getFieldInstance方法的说明，不好意思，麻烦了

**Comment by benjycui** [comment]
```diff
-  <Input placeholder="text" {...getFieldProps('userName', { ... })} />
+  {getFieldDecorator('userName', { ... })(
+    <Input placeholder="text" />
+  )}
```

**Comment by bestv2** [comment]
@benjycui 谢谢，明白了，我的问题，changlog 没仔细看。 只是建议一下，这样改造可读性好像没有以前那么直观。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/1353  #1533
