### ISSUE TITLE
Date组件选择年份的时候固定为YYYY，而不是locale设置的yearFormat

### ISSUE THREAD

**Issue by kei0502** [ant-design/ant-design#32539]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/kei0502/pen/gOxrmLO](https://codepen.io/kei0502/pen/gOxrmLO)

### Steps to reproduce
click date input to open date picker
click year to year picker and check year format

### What is expected?
show era according to yearFormat in locale prop config

### What is actually happening?
show year with fixed YYYY format

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | latest |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
Your reproduce work as expect:
<img width="336" alt="截屏2021-10-19 下午4 35 54" src="https://user-images.githubusercontent.com/5378891/137874018-16962923-ffbb-43d4-976b-ff8f9c39bc71.png">

**Comment by zombieJ** [comment]
Just use `format` props:
https://codesandbox.io/s/antd-reproduction-template-forked-igwjv
