### ISSUE TITLE
关于4.17.0-alpha.6-7中Cascader的value值的问题

### ISSUE THREAD

**Issue by Xiaochena** [ant-design/ant-design#32556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-5-forked-5dbv6?file=/index.js)

### Steps to reproduce
当级联选择器的options的value类型为number时无法展示对应的label、但是当value为string时可以展示对应的label

### What is expected?
展示对应的正确的label

### What is actually happening?
展示了输入的value

| Environment | Info |
|---|---|
| antd | 4.17.0-alpha.7|
| React | 17 |
| System | Windows NT 10.0; Win64; x64 |
| Browser | Chrome/94 |

**Comment by Xiaochena** [comment]
> 多选直接说了， ![图片](https://user-images.githubusercontent.com/22151961/137875798-2863a565-70f9-4f6f-8508-c11656bc7ed6.png)

你这样是不对的、多选你的value应该是[[1],[2]]

**Comment by gitzhaochen** [comment]
> > > 你这样是不对的、多选你的值应该是[[1],[2]]
> > 
> > 
> > 文档中值的类型是 string[] | 数字[]
> 
> 确实在多选时与文档描述有出入、但是这里感觉也没有更好的结构表达多选了、好在多选与单选时的value与onChange回调中的value是保持一致的

defaultValue也有同样的问题

**Comment by andysongsca** [comment]
全选时， 直接返回父节点的值， 想得到被选择的子节点的值数组做不到么
