### ISSUE TITLE
Error: "Cannot resolve module 'antd/lib/locale-provider/style/css'"

### ISSUE THREAD

**Issue by schlan** [ant-design/ant-design#3255]
#### Environment：
- antd version: 2.0.0
- OS: os-x 10.11.6
- Browser: Chrome Version 53.0.2785.116 (64-bit)

#### What did you do？

I upgraded a working setup from ant design v1.11.1 to v2.0.0

package.json:
```
-    "antd": "^1.11.1",
+    "antd": "^2.0.0",
```

#### Actual outcome：
Seeing the following error message in my build:

```
ERROR in ./src/js/index.js
Module not found: Error: Cannot resolve module 'antd/lib/locale-provider/style/css' in /Users/user/git/project/src/js
 @ ./src/js/index.js 7:11-56
```

#### Expected outcome：

A working build :)

**Comment by benjycui** [comment]
2.0.1
