### ISSUE TITLE
V3升到V4 Table组件 的onCell、onHeaderCell  V3 是可以自定义参数的 V4 不可以了

### ISSUE THREAD

**Issue by liangshen001** [ant-design/ant-design#32564]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#API](https://ant.design/components/table-cn/#API)

### Steps to reproduce
V3升到V4 Table组件 的onCell、onHeaderCell  V3 是可以自定义参数的 V4 不可以了 并且components属性中的header cell   body cell 回调中也取不到自定义的参数了 提前感谢

### What is expected?
onCell、onHeaderCell 可以自定义参数并且   components 回调中可以获取到自定义的参数

### What is actually happening?
onCell、onHeaderCell 不能自定义参数  components 回调不能获取到自定义的参数

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.9.0 |
| System | MacOS |
| Browser | google |

**Comment by liangshen001** [comment]
[https://codesandbox.io/s/antd-reproduction-template-forked-p4l90](https://codesandbox.io/s/antd-reproduction-template-forked-p4l90)

sorry 回调可以获取到自定义的参数(custom)
但我使用的ts在onHeaderCell方法不能定义返回自定义字段(custom) 看返回的类型React.HTMLAttributes<HTMLElement>

**Comment by zombieJ** [comment]
嗯，v3 兜底是 [key: any]。这使得写错了 TS 也不报错。到 v4 就收敛成 HTMLAttr 了，你如果有非 spec 属性，就 as 一下哈~

**Comment by zhaomenglu** [comment]
> 嗯，v3 兜底是 [key: any]。这使得写错了 TS 也不报错。到 v4 就收敛成 HTMLAttr 了，你如果有非 spec 属性，就 as 一下哈~

请问具体是怎么写啊
