### ISSUE TITLE
antd  4.16.13版本使用DatePicker相关组件报错

### ISSUE THREAD

**Issue by xjc-github** [ant-design/ant-design#32579]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://xujianchen.gitee.io/r-admin](https://xujianchen.gitee.io/r-admin)

### Steps to reproduce
使用DatePicker组件点击的时候会报一个错误：index.js:1 TypeError: rs(...) is not a function
    at Object.getNow (moment.js:6)
    at postState (PickerPanel.js:123)
    at qt (useMergedState.js:28)
    at mu (PickerPanel.js:119)

### What is expected?
能否弹出时间选择器，并且选择时间

### What is actually happening?
控制台报错index.js:1 TypeError: rs(...) is not a function
    at Object.getNow (moment.js:6)
    at postState (PickerPanel.js:123)
    at qt (useMergedState.js:28)
    at mu (PickerPanel.js:119)
并且页面空白

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | windows10 |
| Browser | 谷歌浏览器94.0.4606.81（正式版本） （64 位） |

---
复制重现链接中的地址，到商城--》带图列表，点击Select Date后，打开控制台会发现报错
（账号：admin，密码：123）

**Comment by yuhuiyolanda** [comment]
遇到了同样的问题，请问最后是怎么解决的

**Comment by liusheng-zhainanya** [comment]
Encountered a similar problem, how was it finally solved?
