### ISSUE TITLE
在使用 qiankun 框架作为微前端的实现方式中。以 Angular 项目作为基座，React 项目作为子应用。在使用 Select 组件时，点击会出现页面卡死行为。

### ISSUE THREAD

**Issue by ZHONG-heart** [ant-design/ant-design#32571]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/kind-allen-i0xl2?file=/src/index.js](https://codesandbox.io/s/kind-allen-i0xl2?file=/src/index.js)

### Steps to reproduce
代码仓库：[https://github.com/umijs/qiankun](https://github.com/umijs/qiankun)
1.把 qiankun 官方 example 中 react 16子项目的 antd 版本改成4，然后npm run examples:install && examples:start
2.在react 16子项目中加入select组件，点击select组件复现

更多信息请查阅：https://github.com/umijs/qiankun/issues/1468

### What is expected?
Select 组件点击之后正常使用，而不是页面卡死

### What is actually happening?
Select 组件点击之后页面卡死

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.1 |
| System | Mac |
| Browser | Chrome |

---
在以 Angular 项目作为基座，React 项目作为微应用的开发中。Select 组件点击后出现页面卡死行为 。（微前端实现方式使用 qiankun 框架）

**Comment by ZHONG-heart** [comment]
复现仓库：https://github.com/umijs/qiankun 
进入 example 目录下，执行上述复现步骤即可。

**Comment by olivewind** [comment]
这个问题和 qiankun 没有关系，在非 Angular 非 qiankun 环境中手动引入 zonejs 也会出现这个问题。应该是 zonejs 和 rc-trigger 在一起工作有一些问题，但是比较奇怪的是，不少组件都依赖了 rc-trigger，唯独 Select 组件有问题，猜测应该是 rc-select 或 rc-trigger 的写法本身有问题，而非 zonejs。 @zombieJ @afc163 @kuitos

**Comment by zombieJ** [comment]
https://github.com/angular/angular/issues/41506
