### ISSUE TITLE
Return a promise when submitting a form

### ISSUE THREAD

**Issue by chris335** [ant-design/ant-design#32606]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Usually asynchronous requests are made within the onFinish of a form. When calling .submit() there is no way to find out if these requests have been completed because this function is void. 

### What does the proposed API look like?
Possibility to return a Promise in the onFinish method which is then also returned over the .submit() function.

**Comment by zombieJ** [comment]
By design. We wish user not care the process of `submit => validate` and only care about `onFinish` event. Could you provide more info about this why need wait for the `submit`.

**Comment by chris335** [comment]
We often have several form on one side. Now, when a user presses a global safe button, for example, all forms must be submitted. It happens that these different forms have dependencies. One must first finish its server requests and depending on what the result is (Success/Failed) the second form should do an action or not.
Currently we have to keep separate states to synchronize this. Therefore it would be very helpful to know exactly what the result is when a form is submitted.

I can imagine that this can also be used in other ways.
For example, if a page needs to be closed after a form has been submitted, it would also make sense to make this code in a Promise on the submit() function. This way the code can be structured in a more meaningful way.

**Comment by zombieJ** [comment]
Use `validateFields`:
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-0-alpha-9-forked-31vhu?file=/index.js

**Comment by chris335** [comment]
I am not talking about validation. Imagine that you have a form that will create an entry in the database. After this is done, you still need to save related entries to the first one. 
If the first request now causes problems on the backend then your approach with the form validation doesn't help either.
We simply want a similar functionality that you have for the validation also when submitting the forms. Why should this not work by design?

**Comment by zombieJ** [comment]
`submit` is called `validateFields` internal and then trigger `onFinish`. So you can just wrap a function with `validateFields` to do the work as `submit`. And also, create DB relation entity should use transition flush at same time which should not deps on the font end.
