### ISSUE TITLE
table组件复制文字时偶尔会出现粘贴后，文字前面携带空格的情况

### ISSUE THREAD

**Issue by wanjiea** [ant-design/ant-design#32617]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://eijnaw.cn:1377/down/5WksBkXijo1k](http://eijnaw.cn:1377/down/5WksBkXijo1k)

### Steps to reproduce
视频里体现了

### What is expected?
复制文字后不会出现携带空格的情况

### What is actually happening?
复制文字后偶尔会出现携带空格的情况

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.1 |
| System | windows |
| Browser | chrome  92.0.4515.107 |

---
场景：用的是官方的demo

**Comment by Leo7991** [comment]
我也遇到了这个问题，这个“不可见空格”是在table中所选字段的前面
