### ISSUE TITLE
按照文档给TimePicker替换momentjs成dayjs，但是没法用TimePicker. RangePicker了呢

### ISSUE THREAD

**Issue by Umua** [ant-design/ant-design#32616]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/replace-moment-cn#antd-dayjs-webpack-plugin](https://ant.design/docs/react/replace-moment-cn#antd-dayjs-webpack-plugin)

### Steps to reproduce
编写TimePicker

### What is expected?
可以使用TimePicker.RangePicker

### What is actually happening?
报错：类型“ForwardRefExoticComponent<TimePickerProps & RefAttributes<any>>”上不存在属性“RangePicker”

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | 17.0.0 |
| System | macOS Big Sur  v11.5.2 |
| Browser | 94.0.4606.81（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
通过 generatePicker 生成的 Picker 有 RangePicker，是你自己包了一层把它丢掉了：
```tsx
// DatePicker.RangePicker

const BTimePicker = React.forwardRef<any, TimePickerProps>((props, ref) => {
  return <DatePicker {...props} picker="time" mode={undefined} ref={ref} />;
});

BTimePicker.displayName = "TimePicker";
```
