### ISSUE TITLE
tabBarGutter不再能控制tab之前的空间

### ISSUE THREAD

**Issue by Canight** [ant-design/ant-design#32635]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://直接引入4.16.8和4.16.9的tab就能重现，使用tabBarGutter(这不是链接).com](https://直接引入4.16.8和4.16.9的tab就能重现，使用tabBarGutter(这不是链接).com)

### Steps to reproduce
修改tabBarGutter的值

### What is expected?
tab之间和tab之前的空间可控

### What is actually happening?
16.9之前的空间变成不可控，导致出现ui bug，也没有更新提示

| Environment | Info |
|---|---|
| antd | 4.16.9 |
| React | 17.0.2 |
| System | m1 big sur 11.5.1 |
| Browser | 版本 94.0.4606.81（正式版本） (arm64) |

---
或许有更好的控制方式

**Comment by kkkisme** [comment]
这个是feature不是bug。之前的被看作是bug，在这里被修复了： https://github.com/ant-design/ant-design/issues/31462
