### ISSUE TITLE
simple Pagination 修改页码后失焦无法触发onChange

### ISSUE THREAD

**Issue by 2018mjy** [ant-design/ant-design#32659]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jian-ji-antd-4-17-0-alpha-7-forked-lrqhf?file=/index.js)

### Steps to reproduce
修改页码，失焦

### What is expected?
失焦后可以触发onChange,返回修改后的页码等信息

### What is actually happening?
没有触发onChange

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.12.0 |
| System | mac  |
| Browser | 87.0.4280.67 |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/pagination/releases/tag/v3.1.10
