### ISSUE TITLE
带tab页的对话框

### ISSUE THREAD

**Issue by zhangwei900808** [ant-design/ant-design#32682]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了tab页面显示在对话框的标题栏中

### What does the proposed API look like?
应功能要求

类似这样：
![image](https://user-images.githubusercontent.com/4385154/139370688-05e217bb-1b82-4f35-9d4a-4a3ae344256c.png)

**Comment by rdmclin2** [comment]
@zhangwei900808 https://procomponents.ant.design/components/card/#%E9%A1%B5%E7%AD%BE 参考这里。

**Comment by afc163** [comment]
这样组件会变得异常复杂，我倾向于保持现有的使用方法。

**Comment by afc163** [comment]
你这个截图实现的挺好的，不妨分享成 codesandbox 到这里。

**Comment by longa30** [comment]
modal当不使用title时会隐藏头部。但是drawer不使用ttile还是会显示头部
