### ISSUE TITLE
Pagination showTotal not rendering on simple type

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#32696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-mirzakhani-rxnm0?file=/index.js)

### Steps to reproduce
Remove comment on //simple

### What is expected?
Pagination showTotal to appear

### What is actually happening?
Pagination show total is not shown

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react: 17.0.2 |
| System | Windows 10 |
| Browser | Brave |

---
Is this proposital?

**Comment by afc163** [comment]
It is intented behavior.

**Comment by balboFK** [comment]
@afc163, i see, any idea on how to make a workaround for it? Thanks.
