### ISSUE TITLE
antd.variable.css [dark version]

### ISSUE THREAD

**Issue by kamilml** [ant-design/ant-design#32707]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently I am importing the `antd.variable.css` file in my app.js (I am using nextjs that doesnt support less).

All is fine, but When I want to change to the dark theme I have to use the `antd.dark.css` file, where I have not variables.

### What does the proposed API look like?
I have not the css code, this is just a request.

**Comment by zombieJ** [comment]
merge into #32807
