### ISSUE TITLE
InputNumber 组件受控且设置了 formatter 后，从最后一位小数开始删除会将所有的小数位数都删除

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#32706]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-gtei9d?file=index.js](https://stackblitz.com/edit/react-gtei9d?file=index.js)

### Steps to reproduce
https://stackblitz.com/edit/react-gtei9d?file=index.js

### What is expected?
正常删除

### What is actually happening?
删除异常

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | MAC |
| Browser | CHROME |

**Comment by hydraZty** [comment]
@Dolov 不是个 bug。
0.0000001，删除最后一位再经过你的`format`方法就是 0。
换个用例: 0.1111111

**Comment by Dolov** [comment]
> @Dolov 不是个 bug。 0.0000001，删除最后一位再经过你的`format`方法就是 0。 换个用例: 0.1111111

我明白产生这个的原因，从技术实现的方面来讲确实是符合程序预期的。
但是从 ui 合理性方面来讲感觉不是太合适。或者能不能提供一直这种场景下的解决方案呢。

**Comment by hydraZty** [comment]
InputNumber 确实输入值为 0 的数时有些问题，但相关逻辑不在此项目下。
期待修复的话，可以去这个 [repo](https://github.com/react-component/input-number/issues) 提 issue。

[另一种展示格式的例子](https://ant.design/components/input-cn/#components-input-demo-tooltip)

**Comment by zombieJ** [comment]
https://stackblitz.com/edit/react-gtei9d-jj4a5d?file=index.js

**Comment by afc163** [comment]
> https://stackblitz.com/edit/react-gtei9d-jj4a5d?file=index.js

@zombieJ 👍，学习了。
