### ISSUE TITLE
Custom attribute for input

### ISSUE THREAD

**Issue by softshape** [ant-design/ant-design#32712]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We're trying to add "autocomplete=none" attribute to an Ant styled text input. No luck yet. How to add a custom attribute to the input?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10104#issuecomment-381821473

**Comment by softshape** [comment]
`<Input autoComplete="new-password" />`

seems to work, thank you!
