### ISSUE TITLE
Input focused style should be cleared 

### ISSUE THREAD

**Issue by boomler** [ant-design/ant-design#32715]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ph4s3?file=/index.js)

### Steps to reproduce
1. input something
2. press Enter
3. wait for  5 seconds
4. click other places

### What is expected?
input should not have focused styles

### What is actually happening?
input  still have a highlight border

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome Latest |

**Comment by afc163** [comment]
![Kapture 2021-11-02 at 15 38 24](https://user-images.githubusercontent.com/507615/139805012-eb6221e9-6673-43d6-9578-588e6ecdc1e4.gif)

I can't reproduce in my machine.

**Comment by boomler** [comment]
@afc163  I've updated the reproduction demo.

> ![Kapture 2021-11-02 at 15 38 24](https://user-images.githubusercontent.com/507615/139805012-eb6221e9-6673-43d6-9578-588e6ecdc1e4.gif)
> 
> I can't reproduce in my machine.
