### ISSUE TITLE
Sub menus collapse if enter during open transition

### ISSUE THREAD

**Issue by IsaacClem** [ant-design/ant-design#32718]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu/](https://ant.design/components/menu/)

### Steps to reproduce
Scroll over navigation 3 and while the menu is opening scroll over it

### What is expected?
it should run the full animation if the mouse is hovered on the menu item or over the submenu and not collapse again

### What is actually happening?
The sub menu immediately collapses again

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | react |
| System | Windows 10 |
| Browser | Chrome 95.0.4638.54 |

**Comment by afc163** [comment]
Could you provide a screen record?

**Comment by IsaacClem** [comment]
![Menu hover](https://user-images.githubusercontent.com/14201180/139834871-e9a8e86e-10d5-48ed-a037-c87892d42dfe.gif)

**Comment by KennyMacheka** [comment]
I can take this up if someone hasn't already

**Comment by feibi** [comment]
if only remove transitionName, you can set menu prop 'motion',
```jsx
<Menu motion={{}}></Menu>
```

**Comment by afc163** [comment]
Fixed in antd 5.x
