### ISSUE TITLE
穿梭框能否支持选中一项后直接穿梭不需要点击”>“或"<"

### ISSUE THREAD

**Issue by eijil** [ant-design/ant-design#32714]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
提供另一种交互形式，简化操作。

### What does the proposed API look like?
或许添加一个配置项开启这个模式。

**Comment by zombieJ** [comment]
设计交互要求勾选批量添加，如果是点击直接添加可以通过 `render` 自定义点击逻辑来实现哈~
