### ISSUE TITLE
Tree组件 expandedKeys设置展开的节点后，点击三角不能收起

### ISSUE THREAD

**Issue by zhouYji** [ant-design/ant-design#32717]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://21312312.com](http://21312312.com)

### Steps to reproduce
Tree组件，通过expandedKeys 手动展开指定节点，并自动展开父组件后，当前设置的展开节点的左侧小三角无法收起节点

### What is expected?
Tree组件，通过expandedKeys 手动展开指定节点，并自动展开父组件后，当前设置的展开节点的左侧小三角收起节点

### What is actually happening?
Tree组件，通过expandedKeys 手动展开指定节点，并自动展开父组件后，当前设置的展开节点的左侧小三角无法收起节点

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.0 |
| System | windows |
| Browser | Google Chrome 95.0.4638.54（正式版本） |

**Comment by afc163** [comment]
See https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-Input/Select-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86%E3%80%82
