### ISSUE TITLE
TreeSelect 多选过滤问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#32726]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-gou-xuan-antd-4-17-0-alpha-9-forked-ekofk?file=/index.js)

### Steps to reproduce
1：在TreeSelect输入5，然后可以过滤出含有5的数据。
2：因为是多选的情况，我就想把包含5 的都选中。
3：结果选中其中一个，马上TreeSelect就变了。
4：感觉像过滤条件被选中的数据“吞”了。
5：如下图所示。
![90afcd98a30788f35c0f7ce4a81f9b3](https://user-images.githubusercontent.com/8272614/140006745-ef0dad47-cc88-475e-8654-32943a6b1226.png)
![d29e820e2af26a6406027c4cb0f3736](https://user-images.githubusercontent.com/8272614/140006751-62d82b76-8fc9-4125-812f-4c11991fdaba.png)

### What is expected?
应该保留我过滤的数据，而不能因为我我选中一个之后，过滤条件就没有了。

### What is actually happening?
过滤条件被选中的条目吞了。

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | windows 10  |
| Browser | chrome 95.0.4638.54（正式版本） （64 位） |

**Comment by afc163** [comment]
autoClearSearchValue={false}
