### ISSUE TITLE
antd3.0 upload customRequest 使用了onProgress方法，上传进度条不显示

### ISSUE THREAD

**Issue by 17628368021** [ant-design/ant-design#32729]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/upload-cn/](https://3x.ant.design/components/upload-cn/)

### Steps to reproduce
```javascript
customRequest = (options) => {
    const { onSuccess, onError, file, onProgress, withCredentials } = options;
    console.log("自定义上传options", options);
    this.setState({
      fileList: [file],
    });

    let media = new FormData();
    media.append("file", file);

    Axios.post("api/datagets/import", media, {
      headers: { "content-type": "multipart/form-data" },
      withCredentials,
      onUploadProgress: ({ total, loaded }) => {
        console.log("total, loaded ", total, loaded);
        onProgress(
          { percent: parseFloat(Math.round((loaded / total) * 100)) },
          file
        );
      },
    })
      .then(({ data: response }) => {
        const _response = { ...response, name: file.name, status: "done" };
        onSuccess(_response, file);
      })
      .catch(onError);
  }

 const uoloadProps = {
      fileList: fileList,
      onChange: this.handleChange,
      beforeUpload: this.handleBeforeUpload,
      customRequest: this.customRequest,
      multiple: false,
    };

<Upload {...uoloadProps} className={styles.fileUpload}>
            <Button className={styles.fileBtn}>
              <i className={styles.fileIcon}></i> 选择文件夹
            </Button>
          </Upload>

### What is expected?
期望通过自定义上传可以正常显示上传进度条

### What is actually happening?
实际上调用了onPregross不能显示上传进度条

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | react |
| System | windows |
| Browser | chrome94.x |


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by mengbimao** [comment]
目前我也使用了自定义上传,调用了onProgress方法,同样不现实进度条,有好的方案吗?大佬们

**Comment by tzwtmll** [comment]
现在还没有人回答吗

**Comment by dinglino1** [comment]
> 
![image](https://github.com/ant-design/ant-design/assets/25605948/93d4fc73-da58-4924-9b92-7bd0f1860b9b)

不需要手动去控制fileList,如果是受控用onchange去控制就好了

**Comment by dinglino1** [comment]
const props = {
    accept:fileType[rowData.resourceType]?.join(','),
    multiple:true,
    fileList,
    onChange:(info)=>setFileList(info.fileList),
    customRequest: async options => {
      const onSuccess = path => {
        options.onSuccess(path);
      };
      const onProgress=(percent)=>{
        options.onProgress({ percent:percent});
      }
      pieceUpload(options, '/backend/part', '/backend/merge', onProgress, onSuccess, 'course');
    },
  };
受控上传列表，用onchange就好了。不要说你自定义上传是添加file
