### ISSUE TITLE
[Bug] Steps title and dot not aligned

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#32737]
### 重现链接

https://codesandbox.io/s/x13k2

### antd 版本

4.17.0-alpha.9

### 重现步骤

1. 访问重现链接
2. 观察垂直的步骤条

### 期望的结果是什么？

标题和圆点居中对齐。

### 实际的结果是什么？

并没有对齐，特别是下面几个步骤。

<img width="367" alt="图片" src="https://user-images.githubusercontent.com/507615/140274696-1d23cfd0-57c8-493c-a719-c9a1a70c4904.png">

### 浏览器

Chrome

### 操作系统

MacOS

**Comment by zombieJ** [comment]
原点分别 8*8 和 10*10，线条宽 1。要对齐得做成奇数了。

**Comment by afc163** [comment]
是横向没对齐，标题和点。
