### ISSUE TITLE
ConfigProvider提供更多的css变量进行使用

### ISSUE THREAD

**Issue by dashaowang** [ant-design/ant-design#32730]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/dashaowang/antd-themes](https://gitee.com/dashaowang/antd-themes)

### Steps to reproduce
使用ConfigProvider进行换肤，无法对表格的边框，背景等颜色进行更换

### What is expected?
使用ConfigProvider进行换肤，能够对antd所有的颜色变量进行替换，方便开发者自定义

### What is actually happening?
使用ConfigProvider.config进行换肤，无法对表格的边框颜色、背景色等进行改变

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17 |
| System | windows 10 |
| Browser | Microsoft Edge 版本 95.0.1020.40 |

---
antd4.17.0-alpha.9 使用ConfigProvider.config进行换肤，无法对表格的边框颜色、背景色等进行改变

**Comment by zombieJ** [comment]
merge into #32807
