### ISSUE TITLE
全选时希望可以设置是否在onchange方法里传子元素的值，现在默认传父元素的值

### ISSUE THREAD

**Issue by andysongsca** [ant-design/ant-design#32741]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当选择产品分类时， A - a1, a2, a3 当全选A类时，其实是想得到 a1, a2, a3值， 而不是A

### What does the proposed API look like?
```jsx
       <Cascader
          options={data}
          multiple={true}
          showCheckedStrategy="SHOW_CHILD"
      />
```
[源码](https://github.com/react-component/cascader/blob/master/src/Cascader.tsx#L372) 可以看这里

**Comment by zombieJ** [comment]
merge into #34193
