### ISSUE TITLE
强烈建议Spin组件或者table中的loading可以加入是否全屏的props

### ISSUE THREAD

**Issue by xjc-github** [ant-design/ant-design#32755]
### 这个功能解决了什么问题？

有些时候希望loading是全屏来给用户展示一些不同的效果

### 你期望的 API 是怎样的？

<Spin fullscreen={true/false}>加载文案<Spin>，同样，在Table组件中也希望加入可以满足一些定制化较高的需求

**Comment by afc163** [comment]
暂不支持，设计规范中没有全屏 loading 这样的交互方式。

**Comment by luoluogh** [comment]
为了转圈的时候防止用户跳转路由导致的一些不可控
