### ISSUE TITLE
【Tree】can the connecting line render again when checkable tree hide the unmatched node 

### ISSUE THREAD

**Issue by hanyyy5** [ant-design/ant-design#32758]
### 这个功能解决了什么问题？

searchable  checkable tree( showline open), hide the unmatched node, and keep the connecting line style right
带搜索的树（showline开启），可勾选时，使用下图的方法隐藏掉不匹配的节点，同时保持连接线的样式正常
![tree methods](https://user-images.githubusercontent.com/28339364/140468373-03df28ab-47da-45c9-b13a-96c7484562af.png)

now the abnormal style like this
有问题的效果如下，连接线是未开始搜索前的样式
![tree_style](https://user-images.githubusercontent.com/28339364/140468730-3fb53486-befe-4fea-bad9-47bbc1a897b9.jpg)

### 你期望的 API 是怎样的？

give some methods to keep the line style normal

**Comment by afc163** [comment]
Duplicate of #27197

**Comment by hanyyy5** [comment]
可做到下拉树搜索那样的效果吗？看了下下拉树不匹配的节点不渲染，而不是display为none, 但是搜索后仍然可以保持住原来的父子关系，不影响勾选的效果

**Comment by hanyyy5** [comment]
这个问题无法解决吗

**Comment by hanyyy5** [comment]
救救孩子吧

**Comment by afc163** [comment]
https://ant.design/components/tree-cn/#components-tree-demo-search 这个能满足需求么？

**Comment by hanyyy5** [comment]
不是很能，主要需要隐藏掉未匹配的节点，就想ztree那样

**Comment by hanyyy5** [comment]
看了rc-tree-select，也是使用rc-tree, 搜索就能做到只渲染匹配到的节点而且搜索结果勾选时，半选，全选都没问题；
ztree中的hidenode方法是使未匹配的结果为display：none的，但是很神奇，它再渲染搜索结果，连接线就是正常的

**Comment by afc163** [comment]
那就是 #27197 的需求，欢迎按这里的 API 来个 PR。
