### ISSUE TITLE
[Bug] Select 点击选项后，立刻将 `disabled` 设置为 `true` 导致失焦样式异常

### ISSUE THREAD

**Issue by SCWR** [ant-design/ant-design#32753]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/disabled-dao-zhi-shi-jiao-yi-chang-5mxcy)

### Steps to reproduce
- 点开
- 选中
- 然后等待 2 s
- foucs 样式不点击Select的话，再也不会消失

### What is expected?
foucs 样式正常处理

### What is actually happening?
foucs 样式不点击Select的话，再也不会消失

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Mac 12 |
| Browser | Chrome 95 |

---
业务场景是需要在选中值后去校验所选择值 同时需要禁止切换

**Comment by afc163** [comment]
看上去和 https://github.com/ant-design/ant-design/issues/32715 类似。

**Comment by SCWR** [comment]
类似 就是 disabled 后没有主动 input 触发 foucs 事件导致样式类名没有按流程移除
![wecom-temp-4c486741bee757992f5722c3595022ae](https://user-images.githubusercontent.com/8925282/140484724-210bff43-8cf2-4773-9d75-17f47b928799.png)
rc只做了关闭下拉菜单的操作 可能没有触发关闭的一些其他操作

**Comment by SCWR** [comment]
> 看上去和 #32715 类似。

可以试下在 disabled 后 鼠标移到 input 外面，应该就能复现

**Comment by Y-qwq** [comment]
如果是聚焦时传入disabled，是不是应该触发onBlur更合理些呢？从表现上来看它确实是从聚焦态转换到了失焦态

**Comment by zombieJ** [comment]
嗯，React 的合成事件在一些边界上有 BUG。组件层应该尽量避免做一些 hack 的事情，防止之后框架修复了导致不同版本的 React 会出现触发多的情况。

* https://codesandbox.io/s/funny-banzai-72mf5?file=/src/index.ts
* https://github.com/facebook/react/issues/9142
