### ISSUE TITLE
Page becomes unresponsive when we use the rule type 'url' for a Form item

### ISSUE THREAD

**Issue by samuellawerentz** [ant-design/ant-design#32760]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-warning-only](https://ant.design/components/form/#components-form-demo-warning-only)

### Steps to reproduce
1. Visit [https://ant.design/components/form/#components-form-demo-warning-only](https://ant.design/components/form/#components-form-demo-warning-only)
2. Paste this URL on the URL input field - http://8987-2405-201-300f-c7f-54cf-6371-7673-f562.ngrok.io/
3. Delete the last two letters
4. The page becomes unresponsive

### What is expected?
The character should get removed immediately and the page should not hang.

### What is actually happening?
The page becomes unresponsive.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.13.1 |
| System | MacOS Big Sur 11.6.1 |
| Browser | Chrome Version 95.0.4638.69 (Official Build) (arm64) |

---
This occurs only when the rules is set to "type: url" and for this particular URL.
```
rules={[
            {
              type: 'url'
            }
          ]}
```

This actually happened in an app where we were doing some validation on input urls and the page got struck.

**Comment by afc163** [comment]
https://github.com/yiminghe/async-validator/issues/263
https://github.com/yiminghe/async-validator/issues/50

**Comment by afc163** [comment]
You can try custom pattern: https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url

```diff
          rules={[
            { required: true },
-           { type: 'url', warningOnly: true },
+           { pattern: new RegExp('https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)'), warningOnly: true },
            { type: 'string', min: 6 },
          ]}
```
