### ISSUE TITLE
[Bug] Table does not need to scroll to appear scrollbar  Table无需滚动出现滚动条

### ISSUE THREAD

**Issue by cwjTerrace** [ant-design/ant-design#32764]
### 重现链接

https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-17-0-alpha-9-forked-3frdu

### antd 版本

4.16.13

### 重现步骤

当使用scroll={{ x: 1500, y: 300 }} 当内容不足的也会强制出现纵向滚动条，样式会比较丑，特别是在没有横向滚动条的情况下，我看了下，ant-table-body给了overflow: auto scroll，纵向强制scroll，我想知道为什么？
![image](https://user-images.githubusercontent.com/29698222/140481621-d6f0db58-3f58-4e6c-8620-9710d5d3398f.png)

### 期望的结果是什么？

overflowY也是auto

### 实际的结果是什么？

overflowY是scroll

### 浏览器

Edge

### 操作系统

MacOS

**Comment by zombieJ** [comment]
不同系统对于滚动条展示是否占位会有所不同，检测滚动条是否滚动会有额外的性能消耗。因而滚动使用固定样式。

**Comment by afc163** [comment]
Duplicate of #29082
