### ISSUE TITLE
[Feature Request] Drawer /Modal 头部提供Tabs

### ISSUE THREAD

**Issue by longa30** [ant-design/ant-design#32772]
### 这个功能解决了什么问题？

  ![微信图片_20211106220430](https://user-images.githubusercontent.com/17867961/140612484-4439c972-eda4-4717-97e9-2e102ee0b325.png)

如图是Drawer 插入tabs ，觉得目前这样并不是很合理。

### 你期望的 API 是怎样的？

 <Drawer tabProps={} />

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32682#issuecomment-955664043
