### ISSUE TITLE
Form.Item initialValue does not work for Checkbox.Group

### ISSUE THREAD

**Issue by redapollos** [ant-design/ant-design#32776]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/checkbox-group-antd-4-17-0-alpha-9-forked-4egl9)

### Steps to reproduce
When passing in an array to either the Form initialValues or Form.Item initialValue for a Checkbox.Group, the values are not pre-selected.  If I add defaultValue to the Checkbox.Group, then it works, but gives a JS error.

### What is expected?
Using Either initialValues or initialValue should preselect the items in Checkbox.Group

### What is actually happening?
Nothing is being pre-selected.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | windows 10 |
| Browser | chrome 95.0.4638.69 |

**Comment by zombieJ** [comment]
Checkbox.Group do not need `valuePropName`:

https://codesandbox.io/s/checkbox-group-antd-4-17-0-alpha-9-forked-ix7lf?file=/index.js
