### ISSUE TITLE
[Feature Request] ConfigProvider配置Form全局colon

### ISSUE THREAD

**Issue by YagamiNewLight** [ant-design/ant-design#32780]
### 这个功能解决了什么问题？

可以通过ConfigProvider的form属性设置colon:false全局默认取消Form组件默认带有的冒号

### 你期望的 API 是怎样的？

```jsx
<ConfigProvider form={{colon:false}}/>
```

**Comment by seaSuper** [comment]
我想做这个issue，:-)，这是我第一次贡献代码。

**Comment by seaSuper** [comment]
@zombieJ 我刚rebase错了😭
