### ISSUE TITLE
Tree的title内嵌Checkbox.Group时，checked状态更新有问题

### ISSUE THREAD

**Issue by Gllidan** [ant-design/ant-design#32790]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-eudgzm?file=index.js](https://stackblitz.com/edit/react-eudgzm?file=index.js)

### Steps to reproduce
1. 勾选Checkbox.Group，成功变更为勾选状态
2. 直接取消之前勾选Checkbox.Group会出现勾选失败问题，需重新勾选其他checkbox再回点，才能更新checked状态

### What is expected?
内部checkbox状态合理更新

### What is actually happening?
需手动配置selectable或是手动添加checkbox的停止冒泡。

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | react |
| System | window |
| Browser | chrome 95.0.4638.69 |

---
查看了内部代码，onSelect是通过点击模拟(内部会触发selectkey的状态更新)，当Checkbox.Group点击时，会触发两次冒泡至onSelect。
不能理解内部机制，为什么状态的更新会导致checkbox的状态错误？麻烦大佬抽空回答下

**Comment by zombieJ** [comment]
内部带交互逻辑的推荐做法都是 stopPop，不过这个现象着实有趣。..

**Comment by Gllidan** [comment]
> 内部带交互逻辑的推荐做法都是 stopPop，不过这个现象着实有趣...
> 
> * React: https://codesandbox.io/s/frosty-sky-nd0y2?file=/src/App.js
> * Vanilla: https://codesandbox.io/s/polished-frost-or002?file=/src/index.ts

     是指e.preventDefault()阻止了勾选？可是第一次点击又是生效的 。这个要怎么理解哈

**Comment by zombieJ** [comment]
看了一下是一个复合问题。原生 Input 在 `onClick` 时，它的节点信息已经被改成了 `checked: true`。之后调用 `preventDefault` 后，重置并不再触发 `onChange` 事件：
https://codesandbox.io/s/dazzling-swartz-ygo7z?file=/src/index.ts

这使得 React 的 `onClick` 里拿到的也是 `checked: true`:
https://codesandbox.io/s/vigilant-sanne-rj7kd?file=/src/App.js

而在 React 中，顶层有一个点击模拟触发 `onChange` 事件的逻辑：
https://github.com/facebook/react/blob/main/packages/react-dom/src/events/plugins/ChangeEventPlugin.js#L234

这时，对比的就是没有被重置回去的状态：
https://github.com/facebook/react/blob/main/packages/react-dom/src/client/inputValueTracking.js#L139

最终就触发了一次模拟 `onChange` 事件（原生则不会触发）。而点击过后再次点击，由于 React 的 tracker 缓存已经记录了它的原始状态为 `true`，所以再次遇到 `true` 则不会再次触发。

再次点击因为 tracker 里的 `checked` 被缓存成 `true` 而拿到的又是 `true` 所以不再能改变，反之亦然。

至于点击外部再点击回来又可以了，是因为点击其他节点导致重新渲染，使得 React 把 Input 的 `checked` 刷新到了正确的状态，于是又能了。

**Comment by zombieJ** [comment]
Checkbox 相关行为：
* 内部存储 checkedness，用于同步 checked 状态
* 点击事件触发时，更新 checkedness 状态
* 触发 preventDefault 后，标记 canceled flag：https://dom.spec.whatwg.org/#set-the-canceled-flag
* Checkbox 检查 canceled flag，发现标记后重置 checkedness 状态：https://html.spec.whatwg.org/multipage/input.html#the-input-element

总结：取消 Checkbox 的 checked 状态是于 click 事件之后，所以通过 click 事件检测是否需要模拟 change 的 React 会有此 BUG。

**Comment by zombieJ** [comment]
从组件库角度，不适合做太 Hack 的事情。鉴于这是一个框架问题，先 close 了。

**Comment by Gllidan** [comment]
大佬这个排错逻辑，专业！学习了~感谢回复哈

**Comment by chenyulun** [comment]
官方的BUG从17年挂到现在，都没有关闭，还是从用户的角度，可以考虑做上hack吧，
tree的事件能不能改成onClickCapture或者使用原生事件进行阻止，
具体得看您是阻止意图和场景确定
