### ISSUE TITLE
[Bug] Calendar 使用 locale=[locale from 'antd/lib/calendar/locale/zh_CN'] 无效

### ISSUE THREAD

**Issue by NgChiKin** [ant-design/ant-design#32791]
### 重现链接

https://codesandbox.io/s/qia-pian-mo-shi-antd-4-17-0-alpha-9-forked-up3eu?file=/index.js

### antd 版本

4.16.10

### 重现步骤

import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { Calendar } from 'antd';
import locale from 'antd/es/calendar/locale/zh_CN';

function onPanelChange(value, mode) {
  console.log(value, mode);
}

ReactDOM.render(
  <div className="site-calendar-demo-card">
    <Calendar locale={locale} fullscreen={false} onPanelChange={onPanelChange} />
  </div>,
  document.getElementById('container'),
);

### 期望的结果是什么？

日历的 有关日期显示都应该为中文

### 实际的结果是什么？

只有 年份显示为中文

### 浏览器

Chrome

### 浏览器版本

95.0.4638.69

### 操作系统

Windows

**Comment by afc163** [comment]
需要把 moment locale 也设置为中文：https://codesandbox.io/s/qia-pian-mo-shi-antd-4-17-0-alpha-9-forked-997xs?file=/index.js
