### ISSUE TITLE
How to change tabindex in Collapse.Panel header?

### ISSUE THREAD

**Issue by YegorDovydenko** [ant-design/ant-design#32792]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What is actually happening?
I can't change tabindex here:
<div class="ant-collapse-header" role="button" tabindex="0" aria-expanded="true"></div>

Component "Collapse".

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 6.14.15 |
| System | 10 |
| Browser | all |

**Comment by YegorDovydenko** [comment]
`<div class="ant-collapse-header" role="button" **tabindex="0"** aria-expanded="true"></div>`

**Comment by monolithed** [comment]
@zombieJ, please add the label 'Accessibility.' Without tabindex, navigation is not possible.

**Comment by aojunhao123** [comment]
WIP
