### ISSUE TITLE
Cascader不支持多选

### ISSUE THREAD

**Issue by shannon1312** [ant-design/ant-design#32801]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader-cn/#API](https://ant.design/components/cascader-cn/#API)

### Steps to reproduce
vscode  在Cascader组件加上multiple出现波浪线

### What is expected?
根据API提供的，Cascader组件支持多选

### What is actually happening?
API提供多选API，实际不支持

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17.0.2 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
Try `4.17.0-alpha.10`
