### ISSUE TITLE
Border radius for middle input element is not 0 when "allowClear"

### ISSUE THREAD

**Issue by erendabanlioglu** [ant-design/ant-design#32808]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/erendabanlioglu/pen/ExvRzRm](https://codepen.io/erendabanlioglu/pen/ExvRzRm)

### Steps to reproduce
If you add `allowClear` to the Input `<Search>` item that has `addonBefore` defined then middle input fields left border has a radius.

<Search addonBefore={selectBefore} size="large" allowClear/>

### What is expected?
Don't have a radius

### What is actually happening?
Having radius

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | React |
| System | Mac |
| Browser | Chrome |

**Comment by DaoxingHuang** [comment]
![image](https://user-images.githubusercontent.com/19969260/141313179-c23e2667-48f4-4db5-9eca-857e79a20661.png)
Change default search style
`  &:not(:last-child) {
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
      .@{ant-prefix}-input-search & {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
      }
    }`
