### ISSUE TITLE
[Feature Request] 请在官网增加最新正式版本的API文档

### ISSUE THREAD

**Issue by Chaos0221** [ant-design/ant-design#32802]
### 这个功能解决了什么问题？

官网 antd4 只有 alpha 版本的文档，目前在项目中无法使用。我已经遇到两次 copy 代码到项目中结果无法使用的情况了。

### 你期望的 API 是怎样的？

右上角版本列表增加最新的正式版本文档

**Comment by zombieJ** [comment]
你好，能说一下哪些 API 版本信息问题吗？我补充一下到文档里。

**Comment by afc163** [comment]
估计是 demo，可以给 demo 设计一个 version 字段，演示卡片上用特殊的样式标记出来。
