### ISSUE TITLE
[Bug] Message 组件的 duration 参数类型应该是 number | undefined 而非 number | null

### ISSUE THREAD

**Issue by amazing416** [ant-design/ant-design#32815]
### 重现链接

无

### antd 版本

4.13.0

### 重现步骤

https://github.com/ant-design/ant-design/blob/4.16.x/components/message/index.tsx

![image](https://user-images.githubusercontent.com/62798363/141251825-2f7071a1-dc3c-42d5-ba4b-c0b4021c44d5.png)

### 期望的结果是什么？

原因：
如果未配置时是 null，将无法获得默认值
![image](https://user-images.githubusercontent.com/62798363/141252082-e1300760-92f6-45f1-a66f-365aed25364f.png)

### 实际的结果是什么？

无

**Comment by KAROTT7** [comment]
@zombieJ 看了下，master 最新代码已修复

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/32524
