### ISSUE TITLE
[Bug] 在IE11下Pagination组件选择分页数量会导致页面整个闪烁

### ISSUE THREAD

**Issue by taogqj** [ant-design/ant-design#32816]
### 重现链接

https://ant.design/components/pagination-cn/

### antd 版本

4.3.4

### 重现步骤

import { Pagination } from 'antd';

ReactDOM.render(
  <>
    <Pagination
      total={85}
      showSizeChanger
      showQuickJumper
      showTotal={total => `Total ${total} items`}
    />
  </>,
  mountNode,
);

### 期望的结果是什么？

页面不闪烁

### 实际的结果是什么？

弹出每页可以显示多少条每次都会导致页面刷新

### 浏览器

Internet Explorer

### 浏览器版本

11

### 操作系统

Windows

**Comment by afc163** [comment]
给个录屏？

**Comment by taogqj** [comment]
https://user-images.githubusercontent.com/53935696/141255894-2891e8c0-8a31-40dc-b0f9-c6083cd7f9fa.mp4
