### ISSUE TITLE
[Bug] treeselect data after update onload not working

### ISSUE THREAD

**Issue by artsztu27** [ant-design/ant-design#32817]
### 重现链接

https://codesandbox.io/s/asynchronous-loading-antd-4-17-0-alpha-9-forked-ye0vs?file=/index.js

### antd 版本

4.16.13

### 重现步骤

1. After expanding the onload node, select
2. Re-update treeselect data
3. onload data is invalid
4. icon disappears

### 期望的结果是什么？

onload data function can work

### 实际的结果是什么？

onload data is invalid
icon disappears

### 浏览器

Chrome

### 浏览器版本

版本 95.0.4638.69 (正式版本) (64 位元)

### 操作系统

Windows

**Comment by zombieJ** [comment]
https://codesandbox.io/s/asynchronous-loading-antd-4-17-0-alpha-9-forked-iu98y?file=/index.js

TreeSelect can not tell remove is by design or not. You need reset loadedKey if need it force reload.
