### ISSUE TITLE
[Feature Request] Can Drawer component add destoryAll() method

### ISSUE THREAD

**Issue by LynTss** [ant-design/ant-design#32828]
### 这个功能解决了什么问题？

Because of some business scenarios, we need to close all Drawers in a unified place. 
Can we provide the destroyAll method to destroy all Drawers like Modal?

### 你期望的 API 是怎样的？

Drawer.destoryAll()

**Comment by afc163** [comment]
You should use React state instead of a extra static method.

**Comment by LynTss** [comment]
You did not understand what I mean.
Of course I can use React State to control within a single component

But if I want to uninstall Drawer globally, do I need to maintain a state in redux to control all Drawer?

Doesn't Modal provide this method? 
I expect Drawer to provide a global destruction method
like Modal.destoryAll()
