### ISSUE TITLE
[Feature Request] introduce additional CSS variables for 4.17.0

### ISSUE THREAD

**Issue by leifdejong** [ant-design/ant-design#32827]
### 这个功能解决了什么问题？

This feature request relates to improving `dynamic theming` with the upcoming `antd v4.17.0` release.

Experimenting with the new `CSS variables`, I noticed that there are some missing relating to `colors` and `background colors`.

This prevents the ability to create a truly custom theme with dynamic switching by omitting those `variables`.

Adding additional `CSS variables` gives developers much more flexibility to create themes that align with their brand and mission while avoiding having to override `less variables` and produce two separate stylesheets bundles.

### 你期望的 API 是怎样的？

Proposal:

Introduce the following CSS Variables in [variables.less](https://github.com/ant-design/ant-design/blob/master/components/style/themes/variable.less): 

```less
@body-background: ~'var(--@{ant-prefix}-body-background)';
@component-background: ~'var(--@{ant-prefix}-component-background)';
@popover-backgorund: ~'var(--@{ant-prefix}-popover-background)';
@text-color ~'var(--@{ant-prefix}-text-color)';
@text-color-secondary: ~'var(--@{ant-prefix}-text-color-secondary)';
@heading-color:  ~'var(--@{ant-prefix}-heading-color)';
@border-color-base: ~'var(--@{ant-prefix}-border-color-base)';
@border-color-split:  ~'var(--@{ant-prefix}-border-color-split)';
@background-color-light:  ~'var(--@{ant-prefix}-background-color-light)';
@background-color-base:  ~'var(--@{ant-prefix}-background-color-base)';
@disabled-color:  ~'var(--@{ant-prefix}-disabled-color)';
@disabled-bg:  ~'var(--@{ant-prefix}-disabled-bg)';
@shadow-color:  ~'var(--@{ant-prefix}-shadow-color)';
@shadow-2:  ~'var(--@{ant-prefix}-shadow-2)';
```

**Comment by zombieJ** [comment]
Thx for feedback. Since antd color deps on less calculation, we may need additional work to split this out.

Merge into #32807
