### ISSUE TITLE
Upload 组件默认上传文件为什么会有一个请求？在我本地是路由的路径

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#32829]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dian-ji-shang-chuan-antd-4-17-0-alpha-9-forked-vibdt?file=/index.js)

### Steps to reproduce
1、点击上传一个文件
2、查看控制台，会发现发出了一个请求，还带文件参数 FormData

### What is expected?
没有这个多的请求

### What is actually happening?
多了一个跟当前路由有关的请求

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome |

---
这个还是测试提的，我都没发现。本地试了下，会发出跟当前路由路径一样的请求地址。
当前地址是 http://localhost:8000/admin/products/list
![image](https://user-images.githubusercontent.com/47104575/141393301-4a6e93c6-7ae6-4623-ad42-9452ac513ed8.png)

**Comment by linxianxi** [comment]
@afc163 不是有 codesandbox 吗

**Comment by lihansir** [comment]
Upload 组件使用时需要指定 action 参数或者指定 customRequest 自定义请求处理方式。如果未指定任何参数，请求会基于现有页面的 url 发起请求，就会出现上文描述的请求路径异常问题

**Comment by linxianxi** [comment]
> Upload 组件使用时需要指定 action 参数或者指定 customRequest 自定义请求处理方式。如果未指定任何参数，请求会基于现有页面的 url 发起请求，就会出现上文描述的请求路径异常问题

也是会有这两个参数都不需要的情况啊。比如这 action 和 customRequest 都不传，然后上传一个文件，把这个 fileList 等到保存的时候再传。

**Comment by afc163** [comment]
你可能需要 https://ant.design/components/upload-cn/#components-upload-demo-upload-manually

**Comment by CodeHuai** [comment]
需要在beforeUpload里面写return false

**Comment by pxim** [comment]
> 
确实存在这个问题

**Comment by yzh990918** [comment]
> > 
> 
> 确实存在这个问题，action 和 customRequest 都不使用，有自己的传输方式，直接return false也不好用，会搞乱其他的业务逻辑

怎么解决的

**Comment by itmier** [comment]
![image](https://github.com/ant-design/ant-design/assets/59595216/cf531d49-e2ad-4aa5-9fb7-9c0038e8da2c)

**Comment by SoftwareEngineerPalace** [comment]
> ![image](https://private-user-images.githubusercontent.com/59595216/288445457-cf531d49-e2ad-4aa5-9fb7-9c0038e8da2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjQ2OTYsIm5iZiI6MTczMzMyNDM5NiwicGF0aCI6Ii81OTU5NTIxNi8yODg0NDU0NTctY2Y1MzFkNDktZTJhZC00YWE1LTlmYjctOWMwMDM4ZThkYTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE0NTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTg5MTUwOTFlZGViMzU3ZjY4ZjYxZjBhMGNkZjE0NTQ5YjVhNTBhZDcyYzI0ZTc2YmYzMmMxNjFlMDkwNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JoNIfBTkHWYFS8tji7xEhutGNihrqQxS12uvJi3i05Y)

这好使吗
