### ISSUE TITLE
createFromIconfontCN 引入iconfont  改变颜色不生效

### ISSUE THREAD

**Issue by livelyPeng** [ant-design/ant-design#32833]
### 重现链接

无

### antd 版本

4.16.13

### 重现步骤

![image](https://user-images.githubusercontent.com/32978177/141417196-8c7c88f3-676c-4818-ae77-5e8784c9b5d2.png)
![image](https://user-images.githubusercontent.com/32978177/141417421-54cbb028-db21-4d0e-8b5b-47a081c16736.png)

### 期望的结果是什么？

为啥我不可以改变样式 颜色呢？
font-size都可以生效

### 实际的结果是什么？

为啥我不可以改变样式 颜色呢？
font-size都可以生效

### 浏览器

Chrome

**Comment by afc163** [comment]
See #13137
