### ISSUE TITLE
安装后运行报错

### ISSUE THREAD

**Issue by YueJingGe** [ant-design/ant-design#32835]
### 重现链接

无

### antd 版本

4.17.0-alpha.9

### 重现步骤

cnpm i --save-dev antd@4.17.0-alpha.9

Error: ENOENT: no such file or directory, open '/Users/jinggeyue/Documents/wotu/career_fe_open/node_modules/antd/lib/style/themes/@{root-entry-name}.less'

### 期望的结果是什么？

运行报错
Error: ENOENT: no such file or directory, open '/Users/jinggeyue/Documents/wotu/career_fe_open/node_modules/antd/lib/style/themes/@{root-entry-name}.less'

### 实际的结果是什么？

Error: ENOENT: no such file or directory, open '/Users/jinggeyue/Documents/wotu/career_fe_open/node_modules/antd/lib/style/themes/@{root-entry-name}.less'

**Comment by psybor** [comment]
用这个暂时解决
[升级了antd后，报错 Variable @root-entry-name is undefined](https://github.com/ant-design/ant-design-pro/issues/9082#issuecomment-925609753)

**Comment by afc163** [comment]
@psybor 4.17.0-alpha.10 也有问题么？

**Comment by psybor** [comment]
> @psybor 4.17.0-alpha.10 也有问题么？

我的是 4.17.0-alpha.9， 没试过 4.17.0-alpha.10

**Comment by afc163** [comment]
试试

**Comment by zcSkr** [comment]
怪了，之前也是阿尔法版本出问题，今天升级4.17.0正版还有这个{root-entry-name}
然后边看很多issues，边把node_modules删除了重新yarn。然后在我打这个评论的时候，我已经正常跑起来了
