### ISSUE TITLE
[Bug] Mention component: can not be filtered with Chinese or Jpanese characters （使用汉字时不能检索）

### ISSUE THREAD

**Issue by zheng-l** [ant-design/ant-design#32832]
### 重现链接

https://codepen.io/daydayuptei/pen/LYjJbdW?editors=0010

### antd 版本

4.16.13

### 重现步骤

＠后面输入汉字“北” 

### 期望的结果是什么？

＠后面输入汉字“北” , 显示'北京你好'

### 实际的结果是什么？

显示'No Data'

### 浏览器

Firefox, Safari

### 操作系统

iOS, Mac, Linux

**Comment by afc163** [comment]
<img width="181" alt="图片" src="https://user-images.githubusercontent.com/507615/141415863-2309a3a0-a2a1-4372-b366-d3f96fd5b02f.png">

Firefox 无法重现。

**Comment by zheng-l** [comment]
Thank you for your quick answer.

we reproduced this issue using the following link with Mac, iOS and linux,  while windows and android are OK.
https://codepen.io/daydayuptei/pen/LYjJbdW?editors=0010

at least, the following OS and browers can reproduce the issue:

- MacBook Pro(13-inch, 2017, Two Thunderbolt 3 ports):  Chrome version: 95.0.4638.69（Official Build） （x86_64）
- Linux Manjaro  21.1.5 : 
→ Firefox Version 93.0 (64-bit)
→ Chromium Version 94.0.4606.81 (Official Build) Arch Linux (64-bit)
- iphone  7: iOS(14.7.1): Safari, Goolge Chrome,

Could you please let me know if you still can not reproduce.

Regards

**Comment by afc163** [comment]
Could you record a video?

**Comment by zheng-l** [comment]
the following is from iphone

https://user-images.githubusercontent.com/53927478/141431049-befcafbf-1879-4bdc-8349-d5b014ada1b1.MOV

**Comment by zheng-l** [comment]
and this is from Mac: 

https://user-images.githubusercontent.com/53927478/141432476-6d79dc43-4f14-448e-a728-6ab5afc82368.mp4

:

**Comment by zheng-l** [comment]
we found:
for iphone:
- neithor chinese nor japanese input method can work when input one chinese or japanese character 
- when input '北京' , no option is selected. but delete the '京', it works.
- it can be reproduced in almose all browsers

for linux:
-  if using 'pinying' input method, it works. while it dosen' t work when using japanese input method , such as mozc

**Comment by KaihatsuOnline** [comment]
We have the same problem. Can not use Japanese input correctly. Many users have Kanji name, and can not use the mention functionality properly.  Big problem for iPhone users.
We would really appreciate a fast fix.

**Comment by KaihatsuOnline** [comment]
@afc163  Could you please re-open this issue? Also the "need reproduce" label can be removed, since there is video to show how to reproduce. Thank you.
