### ISSUE TITLE
[Bug] A big bug which select component worked wrong by multiple mode with labeledValue for antd

### ISSUE THREAD

**Issue by guoenyue** [ant-design/ant-design#32836]
### 重现链接

https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-0-alpha-9-forked-or23b?file=/index.js

### antd 版本

4.16.13

### 重现步骤

see the codesandbox code

<Select
      mode="multiple"
      value={[
        {
          key: "jack",
          label: "杰克"
        }
      ]}
      // value={['jack']}
      style={{ width: 120 }}
      onChange={handleChange}
      options={[
        {
          label: "jack",
          value: "jack"
        },
        {
          label: "lucy",
          value: "lucy"
        },
        {
          label: "disabled",
          value: "disabled",
          disabled: true
        },
        {
          label: "Yiminghe",
          value: "Yiminghe"
        }
      ]}
    ></Select>

### 期望的结果是什么？

work well

### 实际的结果是什么？

error

-------

react-dom.development.js:13413 Uncaught Error: Objects are not valid as a React child (found: object with keys {key, value, label}). If you meant to render a collection of children, use an array instead.
    in span (created by Item)
    in span (created by Item)
    in div (created by Item)
    in Item (created by Overflow)
    in div (created by Overflow)
    in Overflow (created by SelectSelector)
    in SelectSelector (created by Selector)
    in div (created by Selector)
    in Selector (created by Trigger)
    in Trigger (created by SelectTrigger)
    in SelectTrigger (created by ForwardRef(Select))
    in div (created by ForwardRef(Select))
    in ForwardRef(Select) (created by Select)
    in Select (created by

### 浏览器

Firefox, Chrome

### 操作系统

MacOS

**Comment by afc163** [comment]
The solution you are looking for is `labelInValue` prop: https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-0-alpha-9-forked-04csx?file=/index.js
