### ISSUE TITLE
Not able to add space in Input fields used in Tabs

### ISSUE THREAD

**Issue by vaasu070** [ant-design/ant-design#32843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-trigger-of-new-tab-antd-4-17-0-alpha-9-forked-upzo9?file=/index.js)

### Steps to reproduce
Enter text with spaces in the input fields

### What is expected?
Should take white spaces

### What is actually happening?
No able to enter white spaces

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.12.0 |
| System | Windows |
| Browser | Latest chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15610#issuecomment-475951448

See https://codesandbox.io/s/jiben-antd4167-forked-291qv

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31403
