### ISSUE TITLE
Drawer onClose not being called

### ISSUE THREAD

**Issue by Willjay90** [ant-design/ant-design#32845]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-17-0-alpha-3-forked-972g0)

### Steps to reproduce
1. Open the code sandbox link
2. Open the console
3. Click the open button
4. Click `ESC` keyboard event and you will see message in the console
5. Click the open button again
6. Click close button and not message is shown in the console

### What is expected?
The drawer should be closed

### What is actually happening?
The drawer is hidden but not closed

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.13.1 |
| System | MacOS Monterey 12.0.1  |
| Browser | Chrome  95.0.4638.69  |

---
I also notice that `onClose` can only be triggered by 
- clicking on  background mask (if enabled)
- X icon (close button) (if `closable={false}`)
- `ESC` keyboard event

**Comment by Orivoir** [comment]
Hi, i've test your code at your codesandbox but i've not this bug at my browser (Edge 95.0.1020.44)
But during a set state with react if you have need current state you should use function as parameter for read current state,
the current state is give by react during upgrade state.

```js
  const showDrawer = () => {
    // setVisible(!visible);
    setVisible(currentVisible => (
      !currentVisible
    ));
  };
```

[Stackoverflow - set state in react based on current state](https://stackoverflow.com/questions/42494985/setstate-in-react-based-on-current-state)

**Comment by Willjay90** [comment]
@Orivoir my bad, the code in sandbox i forget to get rid of the mask (`mask={false}`)
I tried with your code in `CodeSandbox`, it is still not working from my test

**Comment by afc163** [comment]
I can't reproduce in my chrome.

**Comment by Willjay90** [comment]
@afc163 this is the reproduce link - [CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-bfpul?file=/index.js)

<strong>STEP</strong>
- Open the code sandbox link
- Open the console
- Click the open button
- Click ESC keyboard event and you will see <strong>BYE</strong> in the console
- Click the open button again
- Click close button and no message is shown in the console, which mean that `onClose` function is not called. only `visible` is set to `false`. Accordingly, visually you see the drawer hidden

**Comment by afc163** [comment]
> Click close button and no message is shown in the console neither a notification. In other words,onClose function is not called by the button, only visible is set to false. (Visually you see the drawer is hidden)

I can't reproduce this step, it show BYE in the console and a notification in my machine.

**Comment by shivamnamdeo0101** [comment]
![image](https://user-images.githubusercontent.com/52598179/141929833-f99aed87-d6ab-48b4-828a-ecd47f889679.png)

Your code is fine, message in the console if same then it counted as numbers as you see in the screenshot counted as 2 if this once more then it will counted as 3, I think you got it.
