### ISSUE TITLE
TreeSelect下拉列表左侧的三角形符号不展示

### ISSUE THREAD

**Issue by LeesonD** [ant-design/ant-design#32841]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-0-alpha-9-forked-wn1rw?file=/index.js)

### Steps to reproduce
左侧Dependencies下antd版本选择2.12.3后，刷新右侧展示内容，发现TreeSelect中左侧标识展开/隐藏的三角形消失

### What is expected?
TreeSelect中左侧标识展开/隐藏的三角形正常显示

### What is actually happening?
TreeSelect中左侧标识展开/隐藏的三角形消失不见了，但有点击事件

| Environment | Info |
|---|---|
| antd | undefined |
| React | 15.5.0 |
| System | windows |
| Browser | 搜狗10 |

---
没有展开/隐藏标识，用户无法清晰知道某条数据下是否有子节点，且showLine不生效

**Comment by afc163** [comment]
2.x 老版本不维护了。
