### ISSUE TITLE
Input.Search allowClear点击清空叉叉后会触发onSearch

### ISSUE THREAD

**Issue by iera2yy** [ant-design/ant-design#32848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/input-cn/](https://ant-design.gitee.io/components/input-cn/)

### Steps to reproduce
搜索框内输入内容，点击清空小叉叉，浏览器会触发一次onSearch打印空log

### What is expected?
不触发onSearch函数

### What is actually happening?
触发onSearch函数

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | MacOS 10.15.7 intel |
| Browser | Chrome Version 93.0.4577.63 |

**Comment by KAROTT7** [comment]
正常，这是为了更新状态

**Comment by ChiruMori** [comment]
看起来需要在 onSearch 的函数中加上空串的判定
