### ISSUE TITLE
[Feature Request] 希望Drawer组件提供 destoryAll() 方法用于全局卸载

### ISSUE THREAD

**Issue by LynTss** [ant-design/ant-design#32842]
### 这个功能解决了什么问题？

我需要在全局中对所有Drawer弹窗进行销毁。

目前Modal提供了  Modal.destoryAll() 方法。

期望Drawer可以实现此功能

针对这个issue下的回复我认为没有理解。和使用state的场景是不同的。

https://github.com/ant-design/ant-design/issues/32828

### 你期望的 API 是怎样的？

Drawer.destoryAll()

**Comment by LynTss** [comment]
![image](https://user-images.githubusercontent.com/31870706/141437060-d84542a9-9a7f-47d5-a810-267a3c52885e.png)

**Comment by afc163** [comment]
Drawer 没有 message.info 这样的特殊用法，都在 React 生命周期内，不需要额外的静态方法来销毁。
