### ISSUE TITLE
antd 【Tree】组件，默认设置showLine=true时，并没有连接线条显示

### ISSUE THREAD

**Issue by aidening** [ant-design/ant-design#32858]
### 重现链接

https://stackblitz.com/edit/react-rwjn7h?file=index.js

### antd 版本

4.17.0-alpha.10

### 重现步骤

在使用 Tree 组件时，直接设置 showLine={true} ，连接线定没有显示

为什么在 文档 示例当中显示出了 连接线，是因为 切换了 showLeftIcon，导致组件重新渲染了，这个时候连接线就能显示出来

![image](https://user-images.githubusercontent.com/45580373/141728589-c56553f8-09bd-422e-b532-52b167c0ba86.png)

可以尝试用 sandbox 打开，然后默认把 showLeftIcon 置为 false，showLine 置为 true， 这个时候，连接线并不能正常显示

### 期望的结果是什么？

初始时，直接将 showLine 设置为 true，能够正常显示 连接线

### 实际的结果是什么？

showLine 设置为 true，并没有连接线显示出来，只有组件重新渲染之后，才会显示出来。

**Comment by afc163** [comment]
`showLine={true}` 等效于 `showLine={{ showLeafIcon: true }}`

目前在设计上，showLeafIcon 展示时，末级父子之间是没有连接线的，所以上面的 demo 是符合预期的。

**Comment by aidening** [comment]
showLine 必须这么指定，才能显示出连接线：showLine: { showLeftIcon: false } ，如果不手动将 leftIcon 置为false的话，那 连接线就不会正常显示
