### ISSUE TITLE
[Feature Request] 希望 message, notification, Modal 的全局配置方法能够修改 iconPrefixCls

### ISSUE THREAD

**Issue by psybor** [ant-design/ant-design#32857]
### 这个功能解决了什么问题？

场景：
antd 4.x ，antd 3.x 之间的兼容，比如 qiankun 微前端。
为了兼容 4.x , 3.x，一般会覆盖 `@ant-prefix`, `@iconfont-css-prefix`, 这两个 less 变量，然后通过`ConfigProvider.config` 或者 @ant-design/icons 的 IconProvider 配置全局的上下文。
随后，在调用 Modal, notification, message 静态方法的地方，使用 Modal.useModal, notification.useNotification, message.useMessage, 来获取配置的全局上下文。
这可以解决大部分问题。

但是，很多时候，我们会在请求函数的错误处理中，调用 notification 的静态方法，这里拿不到 上下文。也会在 代码的 model 层（src/models/login.ts）调用 message 的静态方法，这里同样拿不到之前配置的上下文。

### 你期望的 API 是怎样的？

```jsx
Modal.config({ iconPrefixCls: 'anticon' });
notification.config({ iconPrefixCls: 'anticon' });
message.config({ iconPrefixCls: 'anticon' });
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/30925
