### ISSUE TITLE
RangePicker: showing pre-defined date range label instead of a date range

### ISSUE THREAD

**Issue by tomaszcoding** [ant-design/ant-design#32864]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In many cases it is reasonable to support the user by choosing a date range with pre-defined date-ranges like "Last month", "Last quarter", "Next week" etc. This can be achieved today by setting RangePicker's ranges property. However, when user selects one, or selects a date range which corresponds to one of them, the picker still shows the date range as "date from ~ date to". I would like to propose a new property which would make the picker display, say "Last month" instead, when user clicks "Last month". This would improve readability.

### What does the proposed API look like?
```
<RangePicker<Moment>
            ranges={{
              Today: [moment(), moment()],
              'This Month': [moment().startOf('month'), moment()],
              'Last Month': [
                moment()
                  .month(moment().month() - 1)
                  .startOf('month'),
                moment()
                  .month(moment().month() - 1)
                  .endOf('month'),
              ],
              'This Year': [moment().startOf('year'), moment()],
            }}
            displayRangeLabelAsValue={true}
            {...otherProps}
          />
```

https://user-images.githubusercontent.com/50199114/143213320-574a6599-b22e-4051-8aef-dca8bfa56ac1.mov

I am happy to create a PR with a demo for this.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)

**Comment by tomaszcoding** [comment]
Awesome. Thank you!
