### ISSUE TITLE
在阅读官方设计文档时发现了迷惑描述和错误

### ISSUE THREAD

**Issue by dylan-tao** [ant-design/ant-design#32865]
### 这个功能解决了什么问题？

修正官方设计文档中，两处中性色彩模糊描述，给UI设计提供中性色版与（产品级色彩体系-中性色）的对照参考关系，方便进行色彩搭配。并且能完善设计文档的中性色与Admin Pro的对照关系。

### 你期望的 API 是怎样的？

期望官网菜单，
1. 设计-全局样式-[色彩菜单](https://ant.design/docs/spec/colors-cn)下，提供中性色板# 与 产品级色彩体系#-中性色#的对照关系，并能与菜单 设计-全局样式-[字体菜单](https://ant.design/docs/spec/font-cn)下，字体颜色#中Primary Color保持一致，到底是85%还是65%，对照不一，另外设计文档中百分比色差与官方的Admin Pro模版无法找到中性色的对照参考关系，内部比较清楚但是开发或设计者无法知晓。

**Comment by afc163** [comment]
1. 85%
2. 预设中性色和字体色板目前确实对不上，因为字体颜色需要有透明度。
3. Admin Pro 是啥不清楚，指的是 https://pro.ant.design/ 么？

**Comment by dylan-tao** [comment]
> 1. 85%
> 2. 预设中性色和字体色板目前确实对不上，因为字体颜色需要有透明度。
> 3. Admin Pro 是啥不清楚，指的是 https://pro.ant.design/ 么？

3是的，在这个基础上想调整下色彩
