### ISSUE TITLE
allowClear in TextArea collides with scroll bar

### ISSUE THREAD

**Issue by deg** [ant-design/ant-design#32869]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4hpsr)

### Steps to reproduce
This link is a sandbox from the Ant Design documentation at https://ant.design/components/input/ (section: "With clear icon")

Paste this text (or any long text) into the textarea:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget leo luctus, porta quam ac, dictum elit. In porta erat eget tellus eleifend, eget lobortis nisi rutrum. Vivamus egestas arcu vel euismod porta. Nulla efficitur sollicitudin augue, dignissim fringilla magna ullamcorper vitae. Ut quis mauris non nunc semper vestibulum. Ut interdum vitae dolor vitae vestibulum. Phasellus euismod feugiat felis ac congue. Sed a ornare sem."

### What is expected?
The clear button should be between the text and the scrollbar

### What is actually happening?
The clear button (the "x") overlaps the scroll bar.

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 17.0.2 |
| System | Mac 11.6; |
| Browser | Chrome 95.0 |

---
Reproduced on both Mac and Windows.

**Comment by deg** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/90383/141783868-5839f109-1e2d-4d9b-a025-67cd658de215.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26688

**Comment by afc163** [comment]
It is hard to find perfect solution of detecting exist of scrollbar.

**Comment by iamabbar** [comment]
Any workaround?
Thank you.
