### ISSUE TITLE
Modal 的 getContainer 指定了未生效

### ISSUE THREAD

**Issue by fongfai** [ant-design/ant-design#32867]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-b6vxuk](https://stackblitz.com/edit/react-b6vxuk)

### Steps to reproduce
点击 open modal 按钮

### What is expected?
弹窗应该居中出现在getContainer 绑定的id为abc的容器内

### What is actually happening?
实际上是出现在了document的中间位置

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | mac os |
| Browser | chrome 90 |

**Comment by afc163** [comment]
```diff
-         getContainer={document.getElementById('abc')}
+         getContainer={() => document.getElementById('abc')}
```

**Comment by fongfai** [comment]
> ```diff
> getContainer={() => document.getElementById('abc')}
> ```

一样的； 试过了  况且文档里这两种都是Ok的写法
