### ISSUE TITLE
Modal’s getContainer not work, use cakkback still not work 

### ISSUE THREAD

**Issue by fongfai** [ant-design/ant-design#32873]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-b6vxuk](https://stackblitz.com/edit/react-b6vxuk)

### Steps to reproduce
click the button

### What is expected?
Modal show in the center of the  div#abc

### What is actually happening?
show in the center  of  document

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | mac os |
| Browser | chrome 90 |

---
ref:   https://github.com/ant-design/ant-design/issues/32867

**Comment by afc163** [comment]
你对这个属性的理解有误，这个属性只会调整 modal 元素在 dom 树里的渲染位置，而不会影响 UI 表现。
