### ISSUE TITLE
Cascader 支持多选以后 changeOnSelect属性不再生效

### ISSUE THREAD

**Issue by mengbo-ji** [ant-design/ant-design#32886]
### 重现链接

https://stackblitz.com/edit/react-qp5wr3

### antd 版本

4.17.0

### 重现步骤

https://ant.design/components/cascader-cn/#components-cascader-demo-multiple

### 期望的结果是什么？

期望Cascader在支持多选的情况下，支持changeOnSelect属性

### 实际的结果是什么？

Cascader 支持多选以后 changeOnSelect属性不再生效

**Comment by afc163** [comment]
目前两者交互上是不一致的（多选是靠勾 Checkbox 来选择，单选是 Select），可能不好解决。

**Comment by Veveue** [comment]
`popupVisible` 这个属性也被是删了 @afc163

**Comment by zombieJ** [comment]
`changeOnSelect` 在多选下和展开会有冲突，这个我到文档里补充一下。

> `popupVisible` 这个属性也被是删了 @afc163

https://codesandbox.io/s/ji-ben-antd-4-17-0-forked-5ewl9?file=/index.js   没删呀

**Comment by mengbo-ji** [comment]
@zombieJ
级联多选情况下，能否像tree那样 支持可以点选父级的功能
