### ISSUE TITLE
Removing Menu Items

### ISSUE THREAD

**Issue by Morphexe** [ant-design/ant-design#3288]
Hello, sorry I only speak english, and I am not sure if I am missing something, or if it's in fact a bug.

Whenever I use a Menu I want to be able to dynamically add and remove MenuItems based on permissions.

But when doing it like this :
`
   {showCreate & <Menu.Item key="clinicCreate">Create</Menu.Item>}`

Library ends up throwing a error , is there a way to do this, or is it currently not supported? Is there any other way to achieve this?

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
`Menu` expects its children to be `Menu.Item`.
