### ISSUE TITLE
[Bug] Form 中自定义Input 输入无效

### ISSUE THREAD

**Issue by wybiubiu1012** [ant-design/ant-design#32890]
### 重现链接

https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-0-forked-rvkii?file=/index.js

### antd 版本

4.7.0

### 重现步骤

自定义过滤只可输入数字的Input 组件， 配合Form表单使用首次输入时候，输入字母有效，当删除后再次输入才可过滤

### 期望的结果是什么？

首次输入字母即可拦截

### 实际的结果是什么？

首次输入字母可以输入

### 浏览器

Chrome

### 浏览器版本

95.0.4638.69

### 操作系统

MacOS

**Comment by afc163** [comment]
你的写法有问题，我建议这么写 https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-0-forked-j39mw?file=/Phone.js

**Comment by wybiubiu1012** [comment]
谢谢 明白了
