### ISSUE TITLE
[Bug] Table 组件column 的className 可以和render 一样暴露对应的text，record吗

### ISSUE THREAD

**Issue by dadazhouRenee** [ant-design/ant-design#32891]
### 重现链接

https://codepen.io/dadazhouRenee1012/pen/RwZqYov

### antd 版本

4.17.0

### 重现步骤

如上链接

### 期望的结果是什么？

希望数据中状态 status为1的背景色是 黄色

### 实际的结果是什么？

直接配置column里面的className 不能根据状态判断

而且目前的table的padding是统一配置的 直接render里面包裹的容器加背景就会有padding

### 操作系统

Windows

**Comment by dadazhouRenee** [comment]
不好意思 没看清文档 可以在 render return 里返回className

**Comment by kaichii** [comment]
> 不好意思 没看清文档 可以在 render return 里返回className

您好，`render` 方法已经返回要渲染的节点，还怎么返回 `className`?

**Comment by dadazhouRenee** [comment]
@kaichii 不知道是不是这个意思呢
```
render: (text, row, index) => {
    return {
      children: <a>{text}</a>,
      props: {
        className: 'selfClassName',
        colSpan: 2,
        // some props...
      },
    };
},
```

**Comment by kaichii** [comment]
> @kaichii 不知道是不是这个意思呢
> 
> ```
> render: (text, row, index) => {
>     return {
>       children: <a>{text}</a>,
>       props: {
>         className: 'selfClassName',
>         colSpan: 2,
>         // some props...
>       },
>     };
> },
> ```

谢谢，文档没有 `render` 方法具体的返回值，以为只能返回 `ReactNode`。
