### ISSUE TITLE
Documentation improvement - Update Pagination API

### ISSUE THREAD

**Issue by prjanja** [ant-design/ant-design#32901]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The Pagination component takes two properties that are not specified in the API: locale and selectComponentClass

### What does the proposed API look like?
You need to specify these properties in the documentation and describe what they are for or indicate that Pagination can accept all properties of the rc-pagination component

**Comment by afc163** [comment]
1. `locale`, please use ConfigProvider.
2. `selectComponentClass`, we don't expect people using it.
