### ISSUE TITLE
Submenu creates a menuitem whose parent has invalid aria role

### ISSUE THREAD

**Issue by DrewHoo** [ant-design/ant-design#32902]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-submenu-role-parent-mre-i56vk)

### Steps to reproduce
1) Create a Menu with mode="inline"
2) Put a Submenu inside the Menu

### What is expected?
The SubMenu element with the "menuitem" role is owned by the ul "menu":
```
<ul role="menu"> // menu
    <li role="menuitem">
       <div role="button"> // submenu
```

### What is actually happening?
In the DOM, we get an element that has role="menuitem" inside an element with role="none", breaking the relationship between "menuitem" and "menu":
```
<ul role="menu"> // menu
    <li role="none">
       <div role="menuitem"> // submenu
```

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS Big Sur 11.6 |
| Browser | Chrome Version 95.0.4638.69 (Official Build) (x86_64) |

---
the npm package axe-core exposed this issue via this rule: https://dequeuniversity.com/rules/axe/4.2/aria-required-parent?application=axeAPI

**Comment by zombieJ** [comment]
Thx for feedback. I've checked the spec and it not require that `menuitem` must be the direct children of `menu`. And current dom structure is readable by screen read. Pls feel free if need more to discuss.

ref:
* https://www.w3.org/TR/wai-aria-1.2/#menuitem
* https://www.w3.org/TR/wai-aria-1.2/#menu

**Comment by afc163** [comment]
Closing for no response, feel free to reply at any time.
