### ISSUE TITLE
[Bug] Cascader 使用 loadData 添加到三级菜单时报错

### ISSUE THREAD

**Issue by Soulwail** [ant-design/ant-design#32905]
### 重现链接

https://codesandbox.io/s/dong-tai-jia-zai-xuan-xiang-antd-4-17-0-forked-u40x7?file=/index.js

### antd 版本

4.17.0

### 重现步骤

1. 点击一级菜单
2. 点击二级菜单

### 期望的结果是什么？

点击二级菜单后正常加载三级菜单

### 实际的结果是什么？

←→1 of 2 errors on the page
TypeError
Cannot read properties of undefined (reading 'data')
eval
https://codesandbox.io/static/js/sandbox.0c325b8f3.js:1:100726
eval
https://codesandbox.io/static/js/sandbox.0c325b8f3.js:1:100726
commitHookEffectListMount
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19731:26
commitPassiveHookEffects
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19769:11
HTMLUnknownElement.callCallback
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:188:14
Object.invokeGuardedCallbackDev
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:237:16
invokeGuardedCallback
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:292:31
flushPassiveEffectsImpl
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22853:9
unstable_runWithPriority
https://u40x7.csb.app/node_modules/scheduler/cjs/scheduler.development.js:653:12
runWithPriority$1
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11039:10
flushPassiveEffects
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22820:12
eval
https://u40x7.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22699:11
workLoop
https://u40x7.csb.app/node_modules/scheduler/cjs/scheduler.development.js:597:34
flushWork
https://u40x7.csb.app/node_modules/scheduler/cjs/scheduler.development.js:552:16
MessagePort.performWorkUntilDeadline
https://u40x7.csb.app/node_modules/scheduler/cjs/scheduler.development.js:164:27
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.

**Comment by Ivyjin** [comment]
这个bug更新了吗？在哪个版本上呢？
