### ISSUE TITLE
[Bug] multiple theme menu component background not use css variable

### ISSUE THREAD

**Issue by zj1024** [ant-design/ant-design#32908]
### 重现链接

https://codesandbox.io/s/antd-reproduction-template-forked-72zwd?file=/index.js

### antd 版本

4.17.0

### 重现步骤

open the codesandbox link

### 期望的结果是什么？

All the themeConfig properties that can be configured through the build-plugin-antd plugin should support variable configuration

### 实际的结果是什么？

menu component bakckground not change

**Comment by afc163** [comment]
It is not a bug, we only support `primaryColor` now, please trace #32807
