### ISSUE TITLE
[Feature Request] 希望多行文本溢出省略展开后支持收起

### ISSUE THREAD

**Issue by Coco-rq** [ant-design/ant-design#32911]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前展开后不能收起

### What does the proposed API look like?
ellipsis#
{
  ...
  collapseable: boolean,
  onCollapse:function(event),
}

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20639#issuecomment-759251717
