### ISSUE TITLE
[Bug] typescript Cascader组件 options定义 与 fieldNames自定义 存在冲突

### ISSUE THREAD

**Issue by world56** [ant-design/ant-design#32912]
### 重现链接
https://codesandbox.io/s/antd-reproduction-template-forked-vo205?file=/index.tsx

### antd 版本

4.17.0

### 重现步骤

如图所示，Cascader组件 options参数定义的是 DataNode[] ; 
![image](https://user-images.githubusercontent.com/37354312/142168054-cb4f967e-dcef-47c8-bdb1-59787b4ff434.png)

但是该组件可以通过 fieldNames 自定义定义key、value。
![image](https://user-images.githubusercontent.com/37354312/142168172-a2795d64-605c-47dc-b1af-40ae603d1aa2.png)

实际开发中，如果fieldNames自定义了参数，Cascader还是会按照DataNode interface进行校验，是否不合理？
![image](https://user-images.githubusercontent.com/37354312/142168860-08b0bb23-bab6-4475-86a0-49085e144d6f.png)

### 期望的结果是什么？

能否解决 Cascader组件 自定义fieldNames导致typescript提示错误的问题？例如 <T = any>方案等。

非常感谢antd团队付出。

### 实际的结果是什么？

Cascader组件 options定义 与 fieldNames自定义 存在冲突

### 浏览器

Chrome

### 浏览器版本

95.0.4638.69

### 操作系统

MacOS

**Comment by world56** [comment]
已经补充代码例子
https://codesandbox.io/s/antd-reproduction-template-forked-vo205?file=/index.tsx

**Comment by zombieJ** [comment]
- [ ] Tree
- [ ] Select
- [ ] TreeSelect
- [ ] Cascader

**Comment by zombieJ** [comment]
不太好搞，Select 的 Generic 是 `valueType` 而不是 `OptionData` 导致不能推断类型。以至于基于它封装的 `rc-tree-select` 到 `rc-cascader` 都会有推导问题。感觉需要切断一下，全部都换成 OptionData。

**Comment by zombieJ** [comment]
Cascader 做了 const 来解，先关了。

**Comment by tulies** [comment]
> Cascader 做了 const 来解，先关了。

你好，， 请问这个解决里吗 4.17.2版本上还是这样子

**Comment by joker77877** [comment]
这个问题还是没修复啊.

**Comment by world56** [comment]
4.17.3确实还没有解决。

临时解决方案：
![image](https://user-images.githubusercontent.com/37354312/145603742-1c9a715e-5fd5-4478-b8ce-23d3e4a5ee73.png)

**Comment by tearf001** [comment]
在自动推断之前, 

```ts
export interface MyDataNode extends BasicDataNode {
  children?: MyDataNode[];
  id: string | number;
  name?: React.ReactNode;
}
```
```jsx
<div className="w-full w-full">
      <Card title="应用导航" size="small" className="w-full h-full">
        <Tree<MyDataNode>
          className="w-full"
          treeData={mountedTree}
          fieldNames={{ key: 'id', title: 'name', children: 'children' }}
          autoExpandParent={autoExpandParent}
          expandedKeys={expandedKeys}
          onExpand={onExpand}
        />
      </Card>
</div>
```
