### ISSUE TITLE
Upload组件在2020款M1处理器mac的Chrome浏览器不能调起文件选择窗口，2021款M1 pro处理器版本mac的Chrome浏览器没有问题

### ISSUE THREAD

**Issue by huagnshiren2014** [ant-design/ant-design#32913]
### 重现链接

https://ant.design/components/upload-cn/

### antd 版本

4.17.0

### 重现步骤

mac电脑型号：
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/22445536/142169442-8e06f121-01ac-43fd-aad6-bad10befffd8.png">
chrome浏览器型号：版本 95.0.4638.69（正式版本） (arm64)

### 期望的结果是什么？

Upload组件可以正常调起文件选择窗口

### 实际的结果是什么？

Upload组件不能调起文件选择窗口

### 浏览器

Chrome

### 浏览器版本

版本 95.0.4638.69（正式版本） (arm64)

### 操作系统

MacOS

**Comment by afc163** [comment]
请测试一下原生 `<input type="file" />` 能否调起文件选择窗口。

**Comment by liulunsheng** [comment]
实践证明，重启就好了

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/32672#issuecomment-953655354
