### ISSUE TITLE
【建议】InputNumber是否可以限定不让输入非数字内容，而不是输入后，失去焦点后清空

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#32916]
### 这个功能解决了什么问题？

个人看法，既然对number输入，抽离出来一个InputNumber组件，那么是onChange时就将非数字允许的输入过滤掉会更好些，而不是在输入过程中没有任何影响，在输入完成后，失去焦点时，清空非数字输入的内容。如果是处于组件更新频率问题来考虑，提供一个校验时机自定义也未尝不可。

### 你期望的 API 是怎样的？

无

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9421#issuecomment-368721852
