### ISSUE TITLE
Modal.method() not trigger focus after close.

### ISSUE THREAD

**Issue by joseAAlexandre** [ant-design/ant-design#32923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-eomv6?file=/index.js)

### Steps to reproduce
Close the modal.method() not return to its previous focus.
Close the Modal return to the previous focus.

### What is expected?
Both should return to its previous focus

### What is actually happening?
Modal.method() is not focus after close.

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Windows 7 |
| Browser | Microsoft Edge Versão 95.0.1020.53 (Compilação oficial) (64 bits) |

---
To prevent default behavior changes add focusTriggerAfterClose on the Modal.method() is a good option.

**Comment by ElvisUpUp** [comment]
@afc163 我在尝试解决该issue时，发现该问题源自于ActionButton里的autofocus与rc-dialog里自动聚焦的逻辑相冲突，不知道是要从这两者中的哪一方去做兼容呢？

**Comment by joseAAlexandre** [comment]
Any news?
