### ISSUE TITLE
[Bug] 驗證表格中的 checkbox 無正確反應

### ISSUE THREAD

**Issue by Bonnie8ni** [ant-design/ant-design#32926]
### 重现链接

https://codesandbox.io/embed/youthful-hoover-fbes1?fontsize=14&hidenavigation=1&theme=dark

### antd 版本

4.6.5

### 重现步骤

送出時驗證 table 裡的 checkbox 是否為空

### 期望的结果是什么？

若為空則顯示此項目為必填

### 实际的结果是什么？

有選擇項目仍顯示錯誤訊息

### 浏览器

Chrome

### 浏览器版本

版本 95.0.4638.69 (正式版本) (x86_64)

### 操作系统

MacOS

**Comment by afc163** [comment]
Please see this demo https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by Bonnie8ni** [comment]
> Please see this demo https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

@afc163 

checkCheckbox = (_, value) => {
    // value 沒有值
}
