### ISSUE TITLE
antd 更新到 4.16.13 版本后 点击Paginations 组件页码和左右箭头按钮 onChange 事件不触发

### ISSUE THREAD

**Issue by zjx0917** [ant-design/ant-design#32921]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://ceshi/test.com](http://ceshi/test.com)

### Steps to reproduce
1. 将antd由4.16.6更新到4.16.13
2. 组件页码和左右箭头按钮 onChange 事件不触发

### What is expected?
组件页码和左右箭头按钮 onChange 正常触发

### What is actually happening?
组件页码和左右箭头按钮 onChange 事件不触发

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.0 |
| System | mac |
| Browser | chrome |

**Comment by zjx0917** [comment]
代码片段使用如下：
 <Pagination
                size="small"
                total={total}
                pageSize={pageSize}
                defaultCurrent={current}
                showSizeChanger
                pageSizeOptions={pageSizeOptions}
                showTotal={showTotal}
                onChange={(...props) => handleChange(...props)}
            />


  const handleChange = (...props) => {
        if (onChange && typeof onChange === 'function') {
            onChange(...props);
            if (total % pageSize === 1) {
                setGoPage(1);
            } else {
                setGoPage(props[0]);
            }
        }
    };

**Comment by boyrunhuo** [comment]
遇到一样的问题，你解决了吗？

**Comment by kerm1it** [comment]
@zjx0917 @boyrunhuo 麻烦用这个链接写一个复现的例子，https://u.ant.design/codesandbox-repro

**Comment by ZhanL** [comment]
pagination中total传入的数据类型是string而不是number  antd中pagination依赖的rc_pagination最近升级到了3.1.11版本

**Comment by MrZhouChiBang** [comment]
total 改为 number 就好了
如果是 string 类型就会有这个bug，控制台也没有报错信息

**Comment by cwjTerrace** [comment]
https://codesandbox.io/s/winter-platform-q4rqd?file=/index.jsx

rc-pagination 3.1.9 => 3.1.10出的问题

**Comment by cwjTerrace** [comment]
https://github.com/react-component/pagination/pull/357

**Comment by cwjTerrace** [comment]
https://github.com/react-component/pagination/pull/347
除了判断total>0 多加了一个判断 isInteger(total)

**Comment by afc163** [comment]
之前居然 total 传 string 还能跑。。

**Comment by zjx0917** [comment]
解决了 将组件传入的total类型，由字符串转为number就可以

**Comment by cwjTerrace** [comment]
> 之前居然 total 传 string 还能跑。。

服务原来返回的数据是number， 服务为了前端统一处理了long类型，2个月前把long转成了string，一直都好好的，昨天前端发了一个版本线上分页切换全挂了。
