### ISSUE TITLE
Modal demo打不开没法使用

### ISSUE THREAD

**Issue by dynicyan** [ant-design/ant-design#32929]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
点击无法打开

### What is expected?
可以打开

### What is actually happening?
无法打开

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8 |
| System | mac |
| Browser | google |

**Comment by kerm1it** [comment]
我这试了试是可以打开的，可以截个图或者录个视频看看

**Comment by afc163** [comment]
<img width="917" alt="图片" src="https://user-images.githubusercontent.com/507615/142361747-e70b81f6-2c4f-45c1-89df-15983a5d466d.png">

可以打开。
