### ISSUE TITLE
Failed  npm install on master branch

### ISSUE THREAD

**Issue by YadaYuki** [ant-design/ant-design#32927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
clone this repository to local and move to target dir by:
```
$ git clone git@github.com:ant-design/ant-design.git
$ cd ant-design
```
then, install dependencies by running:
```
$ npm install
```

### What is expected?
Error occured. message is below:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: antd@4.17.0-alpha.10
npm ERR! Found: eslint@8.2.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb@18.2.1
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^18.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/yadayuki/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yadayuki/.npm/_logs/2021-11-18T01_02_16_555Z-debug.log
```

### What is actually happening?
Failed `npm install` and `npm start` on master branch

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | macOS Big Sur 11.5.2 |
| Browser | Chrome 95 |

---

## Additional Comment

`npm install` & `npm start` on 4.16.x branch worked.

When running locally, do we have to clone not master branch but stable version branch ? If so, I will fix development docs and contributing docs !

**Comment by afc163** [comment]
wait for https://github.com/ant-design/ant-design/pull/32824
