### ISSUE TITLE
[Input / Form Input]: 希望支持一个Input的Value变更的触发机制

### ISSUE THREAD

**Issue by baiziyu-fe** [ant-design/ant-design#32938]
### 这个功能解决了什么问题？

# 在不同情况下希望Input/Select/TreeSelect这一类组件的触发机制

## 1. 多个互相关联需要实时更新的输入框
  当存在多个需要实时关联的表单项时，输入的内容实时变化来获取一些最新的内容，比如：搜索指定内容
## 2. 多个互相关联不需要实时更新的输入框
  当存在多个互不关联的表单项时，其中的Input我只希望通过指定blur或者change的方式来变更他的value触发方式，其中在指定了方式后我希望Form的onValueChange和onChange也能同步这样的方式

> 我承认只是因为我比较懒，但是基于Form去做更好的联动,我希望是一个官方的处理方案

### 你期望的 API 是怎样的？

```JSX
<Form.Item
   blurChange={true}
   debounceChange={true}
>
  <Input />
</Form.Item>
```

**Comment by afc163** [comment]
建议封装自定义组件来完成此类功能。
