### ISSUE TITLE
[Bug] Form表单中，Cascader组件， 点击 allowClear图标清空数据，不能显示 placeholder 。

### ISSUE THREAD

**Issue by world56** [ant-design/ant-design#32939]
### 重现链接

https://codesandbox.io/s/antd-reproduction-template-forked-ntmx3?file=/index.js

### antd 版本

4.17.0

### 重现步骤

一：Form组件中，包含Cascader组件。

二：点击清空图标后，不会展示 placeholder 字段设定的字符。

🔍 个人判断，点击清空图标后，Cascader返回给Form组件Value的是"[]"，空数组。 
     但是实际上应该返回的是undefined，只有对应值是undefined的情况下，才会显示对应的placeholder。

### 期望的结果是什么？

能否修复此类问题。

### 实际的结果是什么？

Form表单中，Cascader组件。点击该组件清空图标后，不能展示 placeholder 字段设定的字符。

### 浏览器

Chrome

### 浏览器版本

95.0.4638.69

### 操作系统

MacOS

**Comment by D-liszt** [comment]
测试后， "antd": "4.16.13", 可以显示placeholder
 "antd": "4.17.*"，dev下  可以显示placeholder， build下 不用使用defaultValue或者value，可以显示placeholder

**Comment by world56** [comment]
> 测试后， "antd": "4.16.13", 可以显示placeholder "antd": "4.17.*"，dev下可以显示placeholder，build下不用使用或者defaultValuevalue，可以显示placeholder

可以通过我的在线地址测试，https://codesandbox.io/s/antd-reproduction-template-forked-ntmx3?file=/index.js

**Comment by world56** [comment]
> > 测试后， "antd": "4.16.13", 显示placeholder "antd": "4.17.*"，dev下显示placeholder，build下可以不用或者defaultValuevalue，可以显示placeholder
> 
> 可以通过我的在线地址测试，https://codesandbox.io/s/antd-reproduction-template-forked-ntmx3?file=/index.js

关键是要点击组件最右边的 “清空” 按钮，也就是该组件的allowClear属性。

**Comment by Artoria-0x04** [comment]
催一下修复 👻

**Comment by mozkoe** [comment]
Same issue here. 👻

**Comment by afc163** [comment]
@zombieJ 重构的时候顺手修一波 Cascader 的遗留问题。

**Comment by xieyezi** [comment]
请问解决这个bug了吗？

**Comment by xieyezi** [comment]
这里我给出一个解决思路：
 直接找到 clear 图标的 dom元素，通过 `addEventListener` 绑定原生 `click事件`：

``` js
const handleMouseEnter = (e) => {
e.persist()
const targetNode = e.target.parentElement.lastChild
if (targetNode.className === 'ant-select-clear') {
	targetNode.addEventListener('click', function clear(this: any) {
          onChange?.(undefined)
          this.removeEventListener('click', clear)
	})
  }
}
......
<Cascader
  placeholder={placeholder ? placeholder : null}
  options={options}
  value={value?.length ? value : undefined}
  changeOnSelect
  loadData={loadData}
  onChange={selectChange}
  className={className}
  allowClear={allowClear}
  onMouseEnter={handleMouseEnter}
/>
```

**Comment by D-liszt** [comment]
@world56 https://codesandbox.io/s/antd-reproduction-template-forked-7umxn?file=/package.json
写的很清楚啊，切到 "antd": "4.16.13",版本就没有问题，为什么仔细看呢

**Comment by afc163** [comment]
4.18.3 已修复：https://codesandbox.io/s/antd-reproduction-template-forked-og4gs?file=/index.js
