### ISSUE TITLE
在 layout 上加载 menu 出错。

### ISSUE THREAD

**Issue by lincolnge** [ant-design/ant-design#3293]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？

在 layout 上加载 menu。

#### 实际上的结果是：

warning.js?0260*:36Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) aria-owns="1475427628144_0" aria-haspopu
 (server) aria-owns="1475427627467_0" aria-haspopu

**Comment by benjycui** [comment]
server render 的问题，最好能提供一个重现的 repo

**Comment by afc163** [comment]
给重现或尝试 PR @lincolnge

**Comment by afc163** [comment]
closed in https://github.com/react-component/menu/issues/55
