### ISSUE TITLE
Pagination的showQuickJumper，是否支持自定义配置

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#32936]
### 这个功能解决了什么问题？

是否可以像Element-UI那样的，showQuickJumper的输入框内与当前页面一致，而不是跳转页码后showQuickJumper输入框内的内容清空。

### 你期望的 API 是怎样的？

无

**Comment by afc163** [comment]
暂不支持，如有需要可以自行实现 Input 封装跳转逻辑
