### ISSUE TITLE
DatePicker输入框的格式问题

### ISSUE THREAD

**Issue by lslvxy** [ant-design/ant-design#3294]
建议加上输入框是否可见的配置项，
默认的date格式是yyyy-mm-dd，但是输入框的格式却不是，显示的是国际化后的文本

**Comment by lslvxy** [comment]
timePicker选择时间的时候也会报错，`warning.js:36 Warning: Failed prop type: Invalid prop `value` supplied to `Picker`.`  ```warning.js:36 Warning: Failed prop type: Invalid prop `selectedValue` of type `string` supplied to `Calendar`, expected `object`.```

**Comment by wuzeru** [comment]
好像是强制使用moment.js，要用moment类型。你用了moment.js吗？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/master/CHANGELOG.zh-CN.md#2x-%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%94%B9%E5%8A%A8

**Comment by lslvxy** [comment]
好像是的，我在initialValue里面加上了momnet可以了
```
 {getFieldDecorator('releaseTime', {
                                initialValue: currentEditItem.releaseTime && moment(currentEditItem.releaseTime, 'YYYY-MM-DD'),
```

**Comment by lslvxy** [comment]
加上moment了，但是选择日期的时候会报错，
```
date.js:28 Uncaught TypeError: value.getTime is not a function
```

但是不影响程序运行

**Comment by benjycui** [comment]
> 时间类组件的 onChange 和 onPanelChange 及其他回调函数中为 Date/GregorianCalendar 类型的参数，均修改为 moment 类型，两者 API 有所不同，但功能基本一致，请对照 moment 的 API 文档 和 gregorian-calendar 的文档 进行修改。

升级请看 [Change Log](https://ant.design/changelog)

**Comment by janjon** [comment]
@benjycui 1.X 版本也有这问题
