### ISSUE TITLE
[Bug] Drawer未打开时遮盖其他元素

### ISSUE THREAD

**Issue by NorthwesternDirector** [ant-design/ant-design#32949]
### 重现链接

https://codesandbox.io/s/xuan-ran-zai-dang-qian-dom-antd-4-17-1-alpha-0-forked-tvcj8?file=/index.js

### antd 版本

4.17.1

### 重现步骤

1 点击open
2 被遮盖的元素出现

### 期望的结果是什么？

1 其他元素初始时未被遮盖

### 实际的结果是什么？

1 其他元素初始时被遮盖

### 浏览器

Chrome

**Comment by afc163** [comment]
别把 overflow: hidden 删了呀：https://codesandbox.io/s/xuan-ran-zai-dang-qian-dom-antd-4-17-1-alpha-0-forked-pr14d
