### ISSUE TITLE
[Bug] upload组件点击无效

### ISSUE THREAD

**Issue by lujiewei521** [ant-design/ant-design#32948]
### 重现链接

https://ant.design/components/upload-cn/

### antd 版本

4.17.1

### 重现步骤

https://ant.design/components/upload-cn/

### 期望的结果是什么？

正常上传

### 实际的结果是什么？

https://ant.design/components/upload-cn/

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/32672#issuecomment-953655354

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32672#issuecomment-953655354
