### ISSUE TITLE
Tee组件切换子级disabled状态会导致父级全选

### ISSUE THREAD

**Issue by Rebornnn** [ant-design/ant-design#32944]
### 重现链接

https://stackblitz.com/edit/react-n63u4s?file=index.js

### antd 版本

@4.17.1-alpha.0

### 重现步骤

1. 初始状态时，`parent1-1`及其子节点处于disabled态
2. 选中`parent1-0`节点，同时解除`parent1-1`及其子节点disabled态
3. 观察tree组件状态

### 期望的结果是什么？

`parent1-1`及其子节点可点击且不是选中态

### 实际的结果是什么？

`parent1-1`及其子节点可点击且是选中态

### 浏览器

Chrome

### 操作系统

Windows

**Comment by zombieJ** [comment]
`parent 1` 在 `checkedKeys` 中，取消 `disabled` 自然会传导下去。这是预期行为。

ref: [`disabled` 节点在树中的关系是什么？](https://ant.design/components/tree-cn/#disabled-%E8%8A%82%E7%82%B9%E5%9C%A8%E6%A0%91%E4%B8%AD%E7%9A%84%E5%85%B3%E7%B3%BB%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F)
