### ISSUE TITLE
[Bug] Edge浏览器下表格设置右侧固定列会导致表头显示错误

### ISSUE THREAD

**Issue by Thanks62** [ant-design/ant-design#32945]
### 重现链接

https://ant.design/components/table-cn/#components-table-demo-fixed-columns

### antd 版本

4.16.6

### 重现步骤

1. 表格设置了右侧固定列 fixed: 'right'，同时设定高度滚动限制 scroll={{ x: 1200, y: 800 }}
2. 会导致在edge浏览器中表头显示错误，一片空白，元素节点是存在的，但被.ant-table-cell.ant-table-cell-fix-right.ant-table-cell-scrollbar这个类的th元素遮挡了。
官方组件页面打开也有这个问题。

### 期望的结果是什么？

表格表头正常显示

### 实际的结果是什么？

表格表头显示错误

### 浏览器

Edge

### 浏览器版本

Microsoft Edge 44.18362.449.0

### 操作系统

Windows

**Comment by Thanks62** [comment]
<img width="918" alt="截图" src="https://user-images.githubusercontent.com/62629775/142577435-44cad055-d774-4ccf-95e0-d23cb38c96ca.png">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32598#issuecomment-949204429
