### ISSUE TITLE
add to  collapse component collapseAll and expandAll event

### ISSUE THREAD

**Issue by zeden** [ant-design/ant-design#32942]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
playing with defaultActiveKey as array with all keys to expand all and expand and defaultActiveKey  empty to collapse all, it's not a good practise and accordion propertie will broken.

### What does the proposed API look like?
expandAll ={false or true}

**Comment by afc163** [comment]
Please use `activeKey` to control  collapse component.
