### ISSUE TITLE
Button with icon styling issue.

### ISSUE THREAD

**Issue by shaaandi** [ant-design/ant-design#32952]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/https-github-com-ant-design-ant-design-issues-32952-44whe)

### Steps to reproduce
1. Visit the link and preview the code.

### What is expected?
There should be 8px margin between the icon and the content.

### What is actually happening?
There is no spacing between. 

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | ^16.14.0 |
| System | Code sandbox.  |
| Browser | Version 96.0.4664.45 (Official Build) (64-bit) |

---
This happens when we started using @transifex/react `T` tag for our translations. 
The styling no longer applies.

I see we have following styling being applied to button when it has icon:
```
.ant-btn > .anticon   span, .ant-btn > span   .anticon {
    margin-left: 8px;
}
```
However, there are cases where the button doesn't wrap the children inside a span. 
For example if you do this:
```
  <Button type="primary" icon={<SearchOutlined />}>
      <b>Search</b>
    </Button>
```
In the above case, preview included in the sandbox linked provided, the children are no longer inside the span thus no spacing being applied there.

The same thing happens when you do something like this:
```
import { T } from '@transifex/react` 
  <Button type="primary" icon={<SearchOutlined />}>
      <T  _str="Search"  />
    </Button>
```

**Comment by shaaandi** [comment]
**UPDATE:**
The simple solution is to wrap these kind of cases inside `React.Fragment` .

**Comment by afc163** [comment]
reproduce https://codesandbox.io/s/https-github-com-ant-design-ant-design-issues-32952-forked-kdo2f?file=/index.js

**Comment by shaaandi** [comment]
@afc163  Didn't get your previous comment. Is the provided link not working for you ? 
Let me know. Thanks.

**Comment by tiagocastro070** [comment]
Wouldn't it be better to make use of the `inline-flex` for buttons? I think it would also make the design of it more consistent and developers could add tags according to their needs.

```
display: inline-flex;
align-items: center;
gap: 8px;
```

**Comment by afc163** [comment]
Fixed in antd 5.x：https://codesandbox.io/s/https-github-com-ant-design-ant-design-issues-32952-forked-43f24f?file=/index.js

<img width="348" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/239d241f-eae1-4cbf-a399-a84ace15cb2c">

**Comment by Khaalid-oh** [comment]
How do you make the F icon come after the Label and before?
