### ISSUE TITLE
[Feature Request] 希望增加表格列表可以拖拽列宽

### ISSUE THREAD

**Issue by axiaorong** [ant-design/ant-design#32955]
### 这个功能解决了什么问题？

表格列表可以拖拽列宽，和excel的效果一致，可随意拖动

### 你期望的 API 是怎样的？

const columns: ProColumns<API.DeptPlanListItem>[] = [
    // 配置列表每列的信息
    // 操作列
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      // hideInSearch: true,
      valueType: 'textarea',
      hideInSearch: true,
      width: 100,
      align: 'center',
      canDraw: true
    },
    ]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32594

**Comment by hemengke1997** [comment]
可以试试
https://github.com/hemengke1997/use-antd-resizable-header

**Comment by yongchaozeng** [comment]
> 可以试试 https://github.com/hemengke1997/use-antd-resizable-header

YYDS，产品刚想加这个功能
