### ISSUE TITLE
AutoComplete 组件onChange事件

### ISSUE THREAD

**Issue by lslvxy** [ant-design/ant-design#3295]
AutoComplete 组件onChange事件怎么区分是input的值变化还是选择option触发的事件，文档上写的是`选中 option，或 input 的 value 变化（combobox 模式下）时，调用此函数`  `combobox 模式`是什么模式，我想的是选择option触发但是input输入不触发，暂时实现不了

现在只能通过在onchange事件里面对比value和datasource里面的值是否匹配作为暂时的解决方案

**Comment by benjycui** [comment]
更新了下文档，AutoComplete 是没有 combobox 模式的。

**Comment by benjycui** [comment]
可以暴露 `onSelect` 这个回调。
