### ISSUE TITLE
table表格内容不能根据内容的长短，然后进行单元格省略

### ISSUE THREAD

**Issue by yxkt** [ant-design/ant-design#32965]
### 这个功能解决了什么问题？

当鼠标hover当前列时，如果当前列内容超过宽度，则进行自动省略，然后显示内容。如果当前列内容没有超过宽度，则鼠标hover当前列时，不显示省略提示。需求就相当于ProComponents里面的高级表格。可以自动根据内容的多少，判断当前列是否进行省略。

### 你期望的 API 是怎样的？

![image](https://user-images.githubusercontent.com/72731590/142793285-ede06771-0c7e-4287-b59f-a07da53a9307.png)
![image](https://user-images.githubusercontent.com/72731590/142793321-e6f3f9be-0372-41f1-ab16-62b640597677.png)

**Comment by afc163** [comment]
给 column.width 指定宽度即可。
