### ISSUE TITLE
popover触发事件监听参数问题

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#32967]
### 重现链接

https://codesandbox.io/s/antd-popover-qk561?file=/src/index.js:286-294

### antd 版本

4.16.13

### 重现步骤

1，点击左边的按钮，第一个popover弹窗出现
2，点击右边的按钮，第二个popover弹窗出行，但第一个弹窗未关闭

//应该是react17的事件机制改变造成的，希望能有配置项支持配置事件监听{ capture: true }

### 期望的结果是什么？

第二个按钮点击时，第一个popover关闭

### 实际的结果是什么？

第二个按钮点击时，第一个popover未关闭

### 浏览器

Chrome

### 浏览器版本

latest

### 操作系统

MacOS

**Comment by afc163** [comment]
看上去是预期行为，`onMouseDown={(e) => e.stopPropagation()}` 会使点击事件无法冒泡到 document，导致无法触发隐藏。

**Comment by gonenoob** [comment]
> 看上去是预期行为，`onMouseDown={(e) => e.stopPropagation()}` 会使点击事件无法冒泡到 document，导致无法触发隐藏。

但是这属于业务里的操作，比如说我有拖拽事件，是需要阻止的。这在react 16 是可以的。是因为react 17改变事件的监听。希望对popover的触发能增加下{ capture: true }，或者允许用户配置

**Comment by afc163** [comment]
来个 PR 吧。

**Comment by gonenoob** [comment]
> 来个 PR 吧。

太多依赖库要处理了。不知道内部可以修复下吗？毕竟也可以算是组件bug了。业务数据的阻止冒泡事件不应该影响到组件的显隐了。 已经给rc-trigger提了个pr，但是还要走rc-tooltip才能到ant-desight..太慢了。
这样导致要版本回退到react 16 + 了

**Comment by gonenoob** [comment]
https://github.com/react-component/trigger/pull/283
