### ISSUE TITLE
[Bug] Storybook中 `Layout` 布局中，颜色和位置不对（没有动过theme默认配置）

### ISSUE THREAD

**Issue by codthing** [ant-design/ant-design#32963]
### 重现链接

[codesandbox](https://codesandbox.io/s/gifted-yonath-jgk70)

[storybook](https://619a9ba671e2c0003af50e28-fmmltzxrqj.chromatic.com/?path=/story/layouts--default-layout)

### antd 版本

4.16.13

### 重现步骤

1. 这个整体布局和antd文档上的差距也太大了。
3. 比如 Button 中选项icon放置图标的时候，没有垂直居中，
但是这个不影响整体的视觉效果和真正的组件，也不影响开发，请查看链接中的Button。

```base
import React from 'react';
import { Layout, Affix } from 'antd';
const { Header, Footer, Content } = Layout;

function LayoutComponent() {
  return (
    <Layout>
      <Affix>
        <Header>Header</Header>
      </Affix>
      <Content>Content</Content>
      <Footer>Footer</Footer>
    </Layout>
  );
}

export default LayoutComponent;
```

### 期望的结果是什么？

![image](https://user-images.githubusercontent.com/16655229/142776225-54933625-2f39-445d-8348-78c9f044b445.png)

### 实际的结果是什么？

![image](https://user-images.githubusercontent.com/16655229/142776238-9e62c6bf-f75c-4ed3-9ce3-0e1e9449c4a8.png)

### 浏览器

Chrome

### 浏览器版本

98.0.4710.4

### 操作系统

Windows

**Comment by afc163** [comment]
Please provide a codesandbox instead of your own storybook.

**Comment by codthing** [comment]
@afc163 
https://github.com/cothing-demo/umi-antd-storybook-themebug

**Comment by afc163** [comment]
https://raw.githubusercontent.com/ant-design/ant-design/master/components/layout/demo/basic.md

最后有一些 demo 样式的帮助展示布局，你可以看看。

**Comment by afc163** [comment]
另外，最好 fork https://u.ant.design/codesandbox-repro 给重现，避免其他干扰信息。

**Comment by codthing** [comment]
其实，这个Layout组件，不单是在storybook中显示有问题，在真实组件中显示也是同样的问题。
