### ISSUE TITLE
[Bug] 集成 rax提示 getPrefixCls is not a function，是因为Context的问题吗？

### ISSUE THREAD

**Issue by yuchonghua** [ant-design/ant-design#32969]
### 重现链接

https://github.com/alibaba/rax/issues/2286

### antd 版本

4.17.0

### 重现步骤

1、使用标准[raxjs](https://github.com/alibaba/rax/issues/2286)手脚架初始化模板，然后集成antd
2、使用 <DatePicker /> 插件

### 期望的结果是什么？

期待不提示 getPrefixCls is not a function

### 实际的结果是什么？

一直提示：getPrefixCls is not a function

### 浏览器

Firefox, Chrome, Safari, Edge

### 操作系统

Windows

**Comment by afc163** [comment]
不了解 rax，建议在 rax 社区跟踪。
