### ISSUE TITLE
Slow row hover behaviour and row styling when table have >700 rows

### ISSUE THREAD

**Issue by gabrielgodoy** [ant-design/ant-design#32960]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-17-1-alpha-0-forked-r0913?file=/index.js)

### Steps to reproduce
Hover over the rows on the table

### What is expected?
The row hover styling should be responsive without lag

### What is actually happening?
When the user hover over a row it is slow to remove the hovered style and slow to apply the hover style on the new row.

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome |

---
I think it is slow because the classname `ant-table-cell-row-hover` is being applied to every `td` of the hovered row.

It would be good to be allowed to disable that classname insertion behaviour, so the developers can style the hover on CSS which is more responsive.

**Comment by gabrielgodoy** [comment]
I was able to improve hover performance by setting `shouldCellUpdate` on each column since my content is static

```js
const columns = [
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
    render: (text, _, i) => `${i} - ${text}`,
    shouldCellUpdate: (prevRecord, nextRecord) => false
  },
  {
    title: "Age",
    dataIndex: "age",
    key: "age",
    shouldCellUpdate: (prevRecord, nextRecord) => false
  },
  {
    title: "Address",
    dataIndex: "address",
    key: "address",
    shouldCellUpdate: (prevRecord, nextRecord) => false
  }
];
```

**Comment by balboFK** [comment]
Hello @gabrielgodoy, did you find any other way to optimize this? 
For my case the slowdown is even worse since I have a image column on the table, I tried lazy loading them, but it didnt help at all, the problem is in the table hover itself.
Like you said, there should be a prop to opt-in to this behaviour, something like  'allowHover' and controls by a boolean value.
