### ISSUE TITLE
Table - sticky API => getContainer() not working

### ISSUE THREAD

**Issue by simo54** [ant-design/ant-design#32976]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-17-1-alpha-0-forked-11ky5?file=/index.js)

### Steps to reproduce
- Provide sticky API to Table component
- Create object with getContainer() 
- Assign Refenced HtmlElement

### What is expected?
Sticky HtmlElement with table sticky header 

### What is actually happening?
HtmlElement not sticky

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome |

---

**Comment by afc163** [comment]
`getContainer` should return a scrollable area which contains sticky Table.

**Comment by simo54** [comment]
@afc163  is possible to have an example? I did the following but does not work, I wanted to follow the docs but there is not mention of usage, can you please tell me how should be used?

```
   <div ref={titleRef}>
      <header>This is my header</header>
      <div>
        <Table
          columns={columns}
          dataSource={data}
          sticky={{ getContainer: () => titleRef.current }}
        />
      </div>
    </div>
```

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-usage-antd-4-17-1-alpha-0-forked-w0q3w?file=/index.js
