### ISSUE TITLE
Badge 动态值某些情况下显示有问题

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#32970]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-1-alpha-0-forked-t9xbm)

### Steps to reproduce
按钮从左到右执行

### What is expected?
数值显示正常

### What is actually happening?
会闪一下

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment]
看着没啥问题呀

**Comment by linxianxi** [comment]
> 看着没啥问题呀

从左到右依次点击按钮，点到第三个按钮的时候，会闪一下2。你再试试，不行的话的我录个 gif 发在这里

**Comment by xrkffgg** [comment]
我测试是 没有的，要不 你录制一下

**Comment by linxianxi** [comment]
> 我测试是 没有的，要不 你录制一下

你再试一下，刚才莫名少了一个样式。
![Kapture 2021-11-22 at 17 23 42](https://user-images.githubusercontent.com/47104575/142835784-d3e12eb5-1976-4834-a5d7-556536557450.gif)

**Comment by afc163** [comment]
你给的例子里点击三个按钮我都看不到。

**Comment by songlinn** [comment]
我稍微改了一下他的代码复现了这个问题 [code](https://codesandbox.io/s/ji-ben-antd-4-17-1-alpha-0-forked-0ln7o?file=/index.js:159-1107)

**Comment by afc163** [comment]
和 https://github.com/ant-design/ant-design/blob/285fa6e407d33b14f90c14d7e682e59824d852ba/components/badge/index.tsx#L178 有关系。
