### ISSUE TITLE
Modifying ant less variables on runtime

### ISSUE THREAD

**Issue by Ankzy** [ant-design/ant-design#32978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
...

### What is expected?
Hi! I'm using create-react-app with antd. I'm using craco-less to customize theme (as it written there https://ant.design/docs/react/customize-theme). It works fine. But I need to be able to change less variables on runtime to switch custom themes (maybe from components). Is it possible with CRA and craco? Something like this: 
window.less.modifyVars({"@primary-color": "#52c41a"}) 

### What is actually happening?
Can't modify ant less vars on runtime

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | ubuntu 20.04 |
| Browser | Firefox 94.0 |

**Comment by afc163** [comment]
Try https://ant.design/docs/react/customize-theme-variable
