### ISSUE TITLE
css bundle v1 vs v2?!

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3297]
before upgrade to v2, my final css was 386Kb, now it's 597Kb. It's very strange. I suppose that 'babel-import' is not working and i have full bundle as result. Or maybe i miss something?!

my webpack.config.js is:
```
var webpack = require('webpack');

module.exports = function(webpackConfig) {
  webpackConfig.babel.plugins.push(['import',
    { libraryName: 'antd', style: true },
  ]);

  // Fix ie8 compatibility
  webpackConfig.module.loaders.unshift({
    test: /\.jsx?$/,
    loader: 'es3ify-loader'
  });

  return webpackConfig;
```

**Comment by plandem** [comment]
fixed. my fault (https://www.npmjs.com/package/babel-plugin-import):
```
{ libraryName: 'antd', style: 'css' }
```

need to change with:
```
{ libraryName: 'antd', style: true }
```

**Comment by plandem** [comment]
well,

**Comment by benjycui** [comment]
I am not sure if you can provide a repo.

**Comment by sorrycc** [comment]
@pigcan seems to have encountered similar problem.

**Comment by afc163** [comment]
Give us a reproducable repo

**Comment by benjycui** [comment]
Close now.

If you can provide an re-producible repo, just post here and re-open.
