### ISSUE TITLE
[Bug] Table组件hover每一行时会触发Table的重渲染

### ISSUE THREAD

**Issue by vclau-1996** [ant-design/ant-design#32979]
### 重现链接

https://codesandbox.io/s/antd4-17-x-tablezu-jian-hoverxing-hui-chu-fa-chong-xuan-ran-wen-ti-fu-xian-slykl?file=/src/App.js

### antd 版本

4.17.0

### 重现步骤

1. 打开控制台
2. 鼠标移入表格中的某一行观察控制台输出

### 期望的结果是什么？

1. 鼠标移入表格并不会触发行中任何组件的重渲染，控制台无任何输出

### 实际的结果是什么？

1. 会发现每一行的组件都会触发rerender输出"重渲染"，即我移入某一行重渲染了当前表格页的所有row
2. 相同代码antd 4.16.13无此问题
3. 怀疑是rc-table 7.19版本更新引入的问题，本次更新引入了一个hoverContext，支持表格的hoverstyle，更新的代码链接https://github.com/react-component/table/commit/2d0d403642263fdfe41e0dae3cda8d16f665eb35

### 浏览器

Chrome

### 浏览器版本

96.0.4664.45

### 操作系统

Windows

**Comment by vclau-1996** [comment]
好像并不仅仅只是columns被重新渲染了，而是Table被重新渲染了，可以看看这个例子，每次hover到table中的某一行时都重新触发Table组件上的rowKey方法。
https://codesandbox.io/s/antd-tablezu-jian-hoverhui-chong-xuan-ran-zheng-ge-tablezu-jian-de-wen-ti-ejipm

**Comment by zombieJ** [comment]
嗯，为了解决 Table 合并行 hover 样式做了渲染更新。现行的数据结构有点问题导致在渲染之前无法确定哪些节点被影响到，比较蛋疼。

**Comment by vclau-1996** [comment]
> 

暂时没有解决办法吗？感觉数据量起来了的话性能还是存在问题的

**Comment by zombieJ** [comment]
嗯，需要将 column.render 拆分。

**Comment by DVSoftware** [comment]
This is really annoying and a huge performance hit.

**Comment by chillyistkult** [comment]
You can mitigate it a bit by implementing `shouldCellUpdate`.

**Comment by DVSoftware** [comment]
> You can mitigate it a bit by implementing `shouldCellUpdate`.

This would probably remove the ability to update the cells on MobX state change, unless i change all render methods to return the components that observe the values themselves, which would be a huge amount of work. I'm not sure why this change is implemented, as there is a perfectly functioning :hover state in CSS?

**Comment by chillyistkult** [comment]
> > You can mitigate it a bit by implementing `shouldCellUpdate`.
> 
> This would probably remove the ability to update the cells on MobX state change, unless i change all render methods to return the components that observe the values themselves, which would be a huge amount of work. I'm not sure why this change is implemented, as there is a perfectly functioning :hover state in CSS?

The issue has already been fixed in [rc-table](https://github.com/react-component/table/commits/render-split).

We do have a wrapper for antd table that just adds a `shouldCellUpdate` to every column, but depending on how you pass dataSource to table it might or might not help. We generally memoize everything so for us it was even enough to just check of reference equality between `prevRecord` and `record` in `shouldCellUpdate`.

**Comment by DVSoftware** [comment]
Oh, cool, so the fix will probably land in ant in the upcoming weeks

**Comment by tychenjiajun** [comment]
related https://github.com/react-component/table/pull/686

**Comment by tychenjiajun** [comment]
Temporary solution: if you're using `yarn`, add 
```
    "resolutions": {
        "rc-table": "7.18.1"
    },
```
to your `package.json`.

**Comment by tychenjiajun** [comment]
> > You can mitigate it a bit by implementing `shouldCellUpdate`.
> 
> This would probably remove the ability to update the cells on MobX state change, unless i change all render methods to return the components that observe the values themselves, which would be a huge amount of work. I'm not sure why this change is implemented, as there is a perfectly functioning :hover state in CSS?

I think `:hover` doesn't fit grouping rows well.

**Comment by vclau-1996** [comment]
> Temporary solution: if you're using `yarn`, add
> 
> ```
>     "resolutions": {
>         "rc-table": "7.18.1"
>     },
> ```
> 
> to your `package.json` if you don't need the hover style.
> 
> Related [react-component/table#686](https://github.com/react-component/table/pull/686) . And actually there's comment pointing the issue in the original PR

这个倒是临时解决此类问题的好方法，学习了

**Comment by DVSoftware** [comment]
> I think `:hover` doesn't fit grouping rows well.
That's right, but that case can be detected and this feature can only be applied to these rows.

**Comment by alexeychirkov** [comment]
I think this is still active bug even in 4.18.3

**Comment by toSayNothing** [comment]
in `rc-table` package:
```js
  Body(
    BodyRow(
      Cell(
        {props:hovering} // [`${cellPrefixCls}-row-hover`]: !cellProps && hovering,
      )
    )
  )
```
hover cell(onMouseEnter) => rerender all the cells to get the newest `hovering` props;  

---
Instead of passing props to get a new classname, can we use web API eg `document.querySelector` in `Body` component to control those cells' class ? 
In `Body`, first we store the row-cell relationship,
then create a `function` which use web API to add or remove hover class,
In `Cell`, onMouseEnter/Leave to execute that `function` to control the hover class.

I have done some local tests, using web API to control the element can improve the performance(prevent `Cell` re-rendering...).

@afc163 @zombieJ what do you think ?

**Comment by p-efimenko** [comment]
Any update about this issue? How to fix re-renrer on row hover?
Tables which have more then 10 rows lagging so much

**Comment by DVSoftware** [comment]
@p-efimenko for now, i solved it by pinning rc-table component version.

https://github.com/ant-design/ant-design/issues/32979#issuecomment-981328968

**Comment by Madejczyk** [comment]
@DVSoftware and what if someone use node v14 without yarn? so you can use overwrites from npm. Only decrease version?

**Comment by p-efimenko** [comment]
@DVSoftware thanks, I have seen this comment but, I don't use yarn :(
Google say do this trick with npm is complicated

**Comment by DVSoftware** [comment]
> @DVSoftware thanks, I have seen this comment but, I don't use yarn :( Google say do this trick with npm is complicated

You can use https://www.npmjs.com/package/npm-force-resolutions

**Comment by linxianxi** [comment]
any update?

**Comment by vclau-1996** [comment]
4.18.8 seems to have solved this problem in my project.
https://codesandbox.io/s/antd4-17-x-tablezu-jian-hoverxing-hui-chu-fa-chong-xuan-ran-wen-ti-fu-xian-slykl?file=/src/App.js

**Comment by tomriddly** [comment]
已收到您发的邮件。

**Comment by chillyistkult** [comment]
> 4.18.8 seems to have solved this problem in my project.
> https://codesandbox.io/s/antd4-17-x-tablezu-jian-hoverxing-hui-chu-fa-chong-xuan-ran-wen-ti-fu-xian-slykl?file=/src/App.js

How do you think it solves any issue? The whole table is still rerendered on hover?

**Comment by fangqibin** [comment]
> rc-table

这个会不会影响到antd表格功能

**Comment by fangqibin** [comment]
这个最终有什么好的解决方案呢

**Comment by martin-luo** [comment]
This issue still exists in antd@5.9.2: if I pass custom `footer` props in, and hover over the table row, the `footer` component will be re-rendered

**Comment by amBunkowski** [comment]
@afc163 what about antd 5.x?

**Comment by reinaldo-teixeira** [comment]
Hi folks, I was facing the same problem, but I did a workaround and I could solve, this using the `components` props
![Screenshot 2024-07-16 at 19 13 07](https://github.com/user-attachments/assets/0b3eff28-f535-4f1d-a4a9-58ac180c38b1)

Rewriting the cell with a raw `td` prevents the ant behavior from changing my current table with the `hover` event

```
components={{
        body: {
          cell: ({ children }) => (
            <td>
              {children}
            </td>
          ),
        },
      }}
```

**Comment by ryanuo** [comment]
> Hi folks, I was facing the same problem, but I did a workaround and I could solve, this using the `components` props大家好，我面临着同样的问题，但我做了一个解决方法，我可以解决，这使用`components`道具 ![Screenshot 2024-07-16 at 19 13 07](https://private-user-images.githubusercontent.com/101361154/349290454-0b3eff28-f535-4f1d-a4a9-58ac180c38b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjkxMzEsIm5iZiI6MTczMTU2ODgzMSwicGF0aCI6Ii8xMDEzNjExNTQvMzQ5MjkwNDU0LTBiM2VmZjI4LWY1MzUtNGYxZC1hNGE5LTU4YWMxODBjMzhiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNzIwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzNiMjFmMjA0ZjlkYjZlZjVmNGFhOWE1OWQ3Y2IxYzE5MjBlMjFlNWQ0OGQ3YWRmODQ3OWE2NDI5ODM5ODdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J-4Oq6Ep8gty15D2sU_6HJpww2uBmN465XLbWDCLbcc)
> 
> Rewriting the cell with a raw `td` prevents the ant behavior from changing my current table with the `hover` event使用原始`td`重写单元格可以防止 ant 行为通过`hover`事件更改我当前的表格
> 
> ```
> components={{
>         body: {
>           cell: ({ children }) => (
>             <td>
>               {children}
>             </td>
>           ),
>         },
>       }}
> ```


In editable state, the input will lose focus.

**Comment by lyq23** [comment]
@afc163 3版本固定列的可编辑表格也会有这个问题，有什么好的解决办法吗
