### ISSUE TITLE
4.x中，rangepicker的交互如何回到3.x版本的交互

### ISSUE THREAD

**Issue by chenmeng617** [ant-design/ant-design#32982]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/00wkl?file=/index.js)

### Steps to reproduce
4.x中，rangepicker的交互如何回到3.x版本的交互

### What is expected?
达到3.x的交互

### What is actually happening?
不想要的4.x的交互

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.14.0 |
| System | mac windows |
| Browser | chrome |

---
1003419376@qq.com 如果有反馈的可以这个邮箱联系我~比较急用，麻烦了~

**Comment by afc163** [comment]
Duplicate of #30082

目前没有办法。

**Comment by chenmeng617** [comment]
那请问可以做到其他组件仍是4.x版本，单独引入将3.x的datepicker组件么？会引起冲突么？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: afc163 ***@***.***&gt;
发送时间: 2021年11月23日 13:14
收件人: ant-design/ant-design ***@***.***&gt;
抄送: chenmeng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ant-design/ant-design] 4.x中，rangepicker的交互如何回到3.x版本的交互 (Issue #32982)





 
Duplicate of #30082
 
目前没有办法。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
