### ISSUE TITLE
可以做到antd全局仍是4.x版本，单独引入3.x版本的datepicker组件么？想使用3.x的rangePicker的交互。如果可以的话，是否有相关文档可以借鉴？

### ISSUE THREAD

**Issue by chenmeng617** [ant-design/ant-design#32985]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有想要的新版没有兼容的旧版本组件时，可以灵活引入

### What does the proposed API look like?
可以灵活引入即可

**Comment by afc163** [comment]
目前也不支持。
