### ISSUE TITLE
antd2, DatePicker invalid format

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3298]
Looks like DatePicker is not using provided format in some cases:
```
<DatePicker
	disabledDate={this.disabledToDate}
	format={periodFormat}
	value={moment(item.date_to, periodFormat)}
	placeholder={formatMessage(messages.labelPeriodTo)}
	onChange={ (_, date_to) => this.handleChanges({ date_to }) }
/>
```
where periodFormat is **'YYYY-MM-DD'**. Here is result:

(A) - ok:
https://www.dropbox.com/s/s4tfy9ycwlhcaad/Screenshot%202016-10-03%2017.04.37.png?dl=0

(B) - **wrong**:
https://www.dropbox.com/s/7wkl73d5ez6j6vy/Screenshot%202016-10-03%2017.05.24.png?dl=0

p.s.: my locale is RU, so by default we have (B) format, but in my case i want always to use (A) variant.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
