### ISSUE TITLE
在Shopify-Polaris里面引入Antd的组件, Antd样式遭到破坏,SemiUI不会

### ISSUE THREAD

**Issue by quanscheng** [ant-design/ant-design#32986]
### 重现链接

https://codesandbox.io/s/yin-ru-qi-ta-kuang-jia-chu-xian-de-yang-shi-zao-dao-po-pi-wen-ti-xi-wang-antdgeng-jian-zhuang-hutf5?file=/App.js

### antd 版本

4.17.1

### 重现步骤

在shopify-Polaris 引入了antd的datepicker

### 期望的结果是什么？

样式不被破坏

### 实际的结果是什么？

样式完全破坏,无法使用

### 浏览器

Chrome

### 浏览器版本

版本 96.0.4664.55（正式版本） (x86_64)

### 操作系统

MacOS

**Comment by afc163** [comment]
忘了引 antd 的样式么？https://codesandbox.io/s/yin-ru-qi-ta-kuang-jia-chu-xian-de-yang-shi-zao-dao-po-pi-wen-ti-xi-wang-antdgeng-jian-zhuang-forked-81es0

**Comment by quanscheng** [comment]
非常感谢,  我应该找个地方把自己埋了 T.T
