### ISSUE TITLE
antd table children过多时页面卡顿严重

### ISSUE THREAD

**Issue by afc164** [ant-design/ant-design#32987]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd table children过多时页面卡顿严重，当children超过两百多个时，页面卡顿很久

### What does the proposed API look like?
期望有解决办法

**Comment by afc164** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-jjllg?file=/index.js 由于实际项目的每一行都有很复杂的render，无法完全复现，所以例子里把children数量增加到了两千多条...

**Comment by afc163** [comment]
需要把 #20339 内建了才能解，目前没什么好办法。

**Comment by afc163** [comment]
合并到 #20339 里跟踪。

**Comment by lz-59** [comment]
这个问题解决了么  我也出现了这个问题
