### ISSUE TITLE
calendar组件选择日期

### ISSUE THREAD

**Issue by d2913360** [ant-design/ant-design#32996]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar-cn/](https://ant.design/components/calendar-cn/)

### Steps to reproduce
一个示范onSelect事件的例子中，点击右上角日期切换的控件，当你用鼠标点击某一个日期时，这个日期控件下方的日历格也会被点中同时触发其onSelect事件。

### What is expected?
不会点击到某个控件下层的位置

### What is actually happening?
日期控件下方的日历格也会被点中同时触发其onSelect事件

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 16.8.6 |
| System | windows10 |
| Browser | 谷歌版本 95.0.4638.54（正式版本）（64 位） |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28046#issuecomment-759176541
