### ISSUE TITLE
[Bug] Select showSearch API invalid

### ISSUE THREAD

**Issue by 2018mjy** [ant-design/ant-design#32998]
### 重现链接

https://codesandbox.io/s/sou-suo-yong-hu-antd-4-17-1-alpha-0-forked-mz447?file=/index.tsx

### antd 版本

4.16.13

### 重现步骤

输入搜索项

### 期望的结果是什么？

1.可正常输入搜索项
2.拿到onSearch回调

### 实际的结果是什么？

1.无法输入搜索项
2.onSearch回调无反应

注：之前是好的，具体哪个版本不清楚了

### 浏览器

Chrome

### 操作系统

MacOS

**Comment by 2018mjy** [comment]
急，望快回复

**Comment by afc163** [comment]
```diff
- onKeyDown={(e) => {
- e.preventDefault();
- }}
```

**Comment by 2018mjy** [comment]
我的锅锅锅。。。。
