### ISSUE TITLE
antd table分页显示 jumper配置后自动消失

### ISSUE THREAD

**Issue by liujiangping** [ant-design/ant-design#32991]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
antd table在pagination 里面设置showQuickJumper:true 后列表数据在只有一页的情况下没有显示出 jumper来

### What is expected?
这是showQuickJumper一直显示,就像单独使用Pagination 组件一样

### What is actually happening?
在多页的情况下才显示

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.12.0 |
| System | Linux  |
| Browser | Chrome 95.0.4638.69 |

**Comment by afc163** [comment]
https://github.com/react-component/pagination/blob/dbddb763b24b8ce02c17acc664b042897bf73202/src/Pagination.jsx#L189-L191

这里导致逻辑不统一，我来改改。

**Comment by afc163** [comment]
只有一页时，QuickJumper 默认不展示是预期行为，因为没有需要跳的页面。
