### ISSUE TITLE
ie8 问题

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#33]
1. 首页不能正常展示
http://ant.design/

2. breadcrumb react-router 不能结合

http://ant.design/components/breadcrumb/#/

**Comment by ssssssssssss** [comment]
有没有一个完整的浏览器兼容性列表？

**Comment by afc163** [comment]
1. 首页效果对 IE8 不做支持了。
2. router 的问题，@yiminghe 之前用的 https://a.alipayobjects.com/react-router/0.13.3/ReactRouter.js 已经修复了 https://github.com/rackt/react-router/pull/1143 提到的问题。但是依然报错类似的错误，在升级了 es-shim 到最新版本后就好了。

等我找人发布下 4.1.10 的 es-shim 到 cdn 上。

- https://raw.githubusercontent.com/es-shims/es5-shim/v4.1.10/es5-shim.js
- https://raw.githubusercontent.com/es-shims/es5-shim/v4.1.10/es5-sham.js
