### ISSUE TITLE
Sometimes (Navigation) Menu collapse to Cascading Dropdown menu 

### ISSUE THREAD

**Issue by AsasinCree** [ant-design/ant-design#33004]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
无法稳定重现，通过chrome devtool可以间接重现这个过程
1. 打开上述重现链接，通过chrome devtool查看第一个demo，找到 <ul class="ant-menu..." 这一层，将其两个样式 "ant-menu-horizontal" 和 "ant-menu-overflow" 取消勾选(应用)，此时导航menu变成dropdown形式的级联menu
![image](https://user-images.githubusercontent.com/18276301/143189402-1cea1043-712f-4836-b9f9-d316fb0f4ab3.png)

2. 将"ant-menu-horizontal" 和 "ant-menu-overflow"重新勾上，也无法还原成导航menu，是由于 <li class="ant-menu-item..." 元素本身style多了以下属性造成（我也想知道这些样式是从哪里来的，我通过查看源代码并没有发现这是在哪里应用上去的）
![image](https://user-images.githubusercontent.com/18276301/143189186-5514bea1-ce76-443c-9535-41ebe21dd9fb.png)

### What is expected?
导航menu永远不会变成dropdown形式的级联menu

### What is actually happening?
导航menu偶尔会变成dropdown形式的级联menu

| Environment | Info |
|---|---|
| antd | 4.16.5 |
| React | 16.14.8 |
| System | win 10专业版1909 |
| Browser | chrome 版本 96.0.4664.45（正式版本） |

**Comment by afc163** [comment]
> 通过chrome devtool可以间接重现这个过程

这不是可调试的重现过程，最好还是能找到重现方式，或者录个屏。
