### ISSUE TITLE
直接引用~antd/lib/style/themes/default.less 报Variable @root-entry-name is undefined

### ISSUE THREAD

**Issue by jackIsZlg** [ant-design/ant-design#33007]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
在umi框架下面，版本升级成"antd": "4.17.1",
全局less文件引用： @import '~antd/lib/style/themes/default.less';
直接报错@root-entry-name is undefined

### What is expected?
不报错

### What is actually happening?
报错 @import './@{root-entry-name}.less'; 未定义

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | 16.13.1 |
| System | mac |
| Browser | 谷歌版本 96.0.4664.55（正式版本） (x86_64) |

**Comment by xiezhuo0513** [comment]
遇到相同问题

**Comment by xiezhuo0513** [comment]
react相同版本    run build 的时候报相同的错误

**Comment by malmo-east** [comment]
I tried to downgrade dependency version, it didn't help.

**Comment by xiezhuo0513** [comment]
>bu
You can try version 4.4.2,i can build successfully,don't add ^

**Comment by airbreak** [comment]
遇到一样的问题。原来使用 "antd": "^4.16.13", 今天换成4.17.1 后，本地yarn start就报这个错误。

**Comment by xiezhuo0513** [comment]
> 

建议不使用4.17.1   我本地也报错

**Comment by jackIsZlg** [comment]
> Hello @jackIsZlg. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @jackIsZlg, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

这个你们自己随便跑一下就有问题的，不要我们提供重现实例

**Comment by jackIsZlg** [comment]
> > 
> 
> 建议不使用4.17.1 我本地也报错

哎，版本已经回退了4.16了

**Comment by xiezhuo0513** [comment]
> 

是的   而且也无法重新  又不能build

**Comment by TimbokY** [comment]
先自己解决，可以改一下webpack配置 [9082]( https://github.com/ant-design/ant-design-pro/issues/9082)

**Comment by afc163** [comment]
@TimbokY @xiezhuo0513 @jackIsZlg 我们本地没有重新这个问题，能否协助提供重现 repo？

**Comment by xiezhuo0513** [comment]
> @TimbokY @xiezhuo0513 @jackIsZlg @airbreak 我们本地没有重现这个问题，能否协助提供重现 repo？

你要俺们肿么协助

**Comment by afc163** [comment]
提供一个 github repo 以及重现步骤。

**Comment by flashtony2005** [comment]
// @import './variable.less';
@import './@{root-entry-name}.less';
      ^
Variable @root-entry-name is undefined
      Error in E:\antdFront\node_modules\antd\lib\style\themes\index.less (line 7, column 8)

**Comment by amed** [comment]
Same issue here on the latest `antd-4.17.1`

We use `antd-theme-webpack-plugin 1.3.9` and cannot declare the `root-entry-name` less variable globally.

**Comment by Simone-cm** [comment]
> Same issue here on the `antd-4.17.1`
> 
> We use `antd-theme-webpack-plugin 1.3.9` and cannot declare the `root-entry-name` less variable globally.

I am having the exact same issue with the exact same `antd-theme-webpack-plugin 1.3.9`. Seems like `@root-entry-name` doesn't get read correctly.

**Comment by amed** [comment]
@Simone-cm we had to write a post-npm-install to manipulate less files inside node_modules.

```
// package.json

{
  "scripts": {
    "postinstall": "./antd_fix.sh"
  }
}
    
```

Obviously it's not the ultimate solution.

**Comment by shabri-arrahim** [comment]
I am having the exact same issue,  I roll back the version from  4.17.1 to 4.16.9 and Everything goes well.

**Comment by jackIsZlg** [comment]
![image](https://user-images.githubusercontent.com/25714655/144363975-b5175db4-985c-4727-900c-a315ff76f207.png)

在umi下配置lessloader就行

**Comment by afc163** [comment]
@jackIsZlg 能否提供一下重现？

**Comment by Codennnn** [comment]
> 

这个方法管用！

**Comment by rafaelncarvalho** [comment]
Anyone got this working with antd-theme-webpack-plugin?

**Comment by jackIsZlg** [comment]
你好~你发送的邮件我已经收到，会早点收看到的~周栗刚

**Comment by rafaelncarvalho** [comment]
@amed your is the best solution, after some debug I found that antd-theme-webpack-plugin read the LESS imports as files, so the new theme/index.less with a import using a less variable will not work

**Comment by sklinov** [comment]
Solution by @jackIsZlg works fine for me on Webpack 4.
```
{
  loader: "less-loader",
  options: {
    modifyVars: {
      "root-entry-name": "default"
    }
  }
}
```

**Comment by pkaq** [comment]
4.20.1也有此问题

**Comment by portalZYT** [comment]
Same issue here on the ng-zorro-antd-16.2.2

We use @angular-builders/custom-webpack 16.0.0 and cannot declare the root-entry-name less variable globally.

I am having the exact same issue with the exact same @angular-builders/custom-webpack 16.0.0. Seems like @root-entry-name doesn't get read correctly.

**Comment by jackIsZlg** [comment]
你好~你发送的邮件我已经收到，会早点收看到的~周栗刚
