### ISSUE TITLE
<Input type="number" />校验的Bug。

### ISSUE THREAD

**Issue by Midqiu** [ant-design/ant-design#3300]
#### 发生问题的环境是：

`<Input type="number" />`未进行编辑，直接点提交，校验不通过。

http://codepen.io/Midqiu/pen/rrJXZd?editors=1011

 不要编辑，直接点“确定”。通不过校验。

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i` 试下先吧，没有重现例子也无法 debug

**Comment by Midqiu** [comment]
更新了可重现的demo 。

**Comment by infeng** [comment]
`<Input type="number" />`的getFieldDecorator的rules增加`type: 'number'`即可

**Comment by Midqiu** [comment]
增加`type: 'number'`的话，编辑的时候校验失败。

**Comment by infeng** [comment]
@Midqiu

**Comment by infeng** [comment]
```javascript
getValueFromEvent: (e) => {
  if(!e || !e.target) {
    return e;
  }
  const { target } = e;
  if(target.value === '') {
    return undefined;
  }
  return parseInt(target.value); 
}
```
@Midqiu  我的解决方法是在getFieldDecorator的options增加getValueFromEvent将string转为number，这样设置`type: 'number'`编辑的时候就不会有问题

**Comment by ddcat1115** [comment]
这个和 `type=number` 的原生设置好像没有关系，把 initialValue 改为string类型demo就没有问题了。

`Input` 的 `type: number` 的校验好像有点问题，我再看看

**Comment by ddcat1115** [comment]
@yiminghe  https://github.com/yiminghe/async-validator/blob/master/src/rule/type.js#L41  现在设置了`type:number` 会校验 typeof value 是否是number，而Input默认校验string，输入之后也会变成string，有点冲突，这里是不是可以不校验 typeof ？

**Comment by yiminghe** [comment]
不要用 type  number 用 pattern:/\d+/
