### ISSUE TITLE
当form组件变化时，希望能拿到该组件的校验结果

### ISSUE THREAD

**Issue by jelly-shang** [ant-design/ant-design#33006]
### 这个功能解决了什么问题？

在组件之间相互依赖的场景中，当其中一个组件值变化的时候，拿到该组件的校验结果，根据校验结果，再去联动其他的组件。

### 你期望的 API 是怎样的？

`
<SelfComponent onChange={this.onItemChange}/>
`

**Comment by afc163** [comment]
手动调用 form.validateFields

https://ant.design/components/form-cn/#FormInstance

**Comment by jelly-shang** [comment]
> 手动调用 form.validateFields
> 
> https://ant.design/components/form-cn/#FormInstance

监听onChange的时候 当前组件的value，还没写到form里面，这时候通过form实例拿不到最新的值也校验不了

**Comment by afc163** [comment]
统一在 Form 上的 `onValuesChange` 里取。

**Comment by jelly-shang** [comment]
倒是能取到所有的值 但是想拿到校验结果

**Comment by afc163** [comment]
在 onValuesChange 里调用 form.validateFields

**Comment by afc163** [comment]
或者在 onFieldsChange 里取校验状态。

**Comment by jelly-shang** [comment]
onValuesChange里form也取不到控件的最新值 自然也校验不了

**Comment by jelly-shang** [comment]
但是无法在自定义组件里传递其他值给onFieldsChange

**Comment by kaichii** [comment]
> 但是无法在自定义组件里传递其他值给onFieldsChange

最后怎么处理的？怎么就关了

**Comment by nhfgCSSA** [comment]
希望 reopen 这个 issue。
现在确实存在问题：
- 如果在 onValuesChange 中去调用 validateFields()，此时用的是旧数据，这种方式无效。
- 如果使用 setTimeout() 来进行 validateFields()，依然不合适，输入会卡顿，如果输入很快，会丢失部分输入。
