### ISSUE TITLE
[Bug] 为什么Table组件的伸缩表头列宽度示例不见了？

### ISSUE THREAD

**Issue by vivianus-chan** [ant-design/ant-design#33010]
### 重现链接

https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler

### antd 版本

4.8.0

### 重现步骤

就文档没有拖动表头宽度的demo了，以前有的。

### 期望的结果是什么？

想看看示例

### 实际的结果是什么？

示例不见了

### 浏览器

Chrome

**Comment by afc163** [comment]
bug 太多，不推荐使用了。

**Comment by vivianus-chan** [comment]
无语凝噎
