### ISSUE TITLE
[Bug] cascader 组件从 3.x 升级到 4.x后 渲染阻塞严重

### ISSUE THREAD

**Issue by udbbbn** [ant-design/ant-design#33016]
### 重现链接

[codeSandBox](https://codesandbox.io/s/antd-reproduction-template-forked-osu87?file=/index.js)

### antd 版本

4.17.0-alpha.10

### 重现步骤

codeSandBox 项目地址默认为 4.x版本，点击 show 按钮可以感受到明显卡顿，再切换antd版本至 3.x 再进行测试，可感受到比4.x流畅

antd3.x cascader 具体代码目录 https://github.com/react-component/cascader/blob/4c6e7f6184c0319afc91873ba5db16a255950224/src/Menus.jsx#L141
antd4.x cascader DFS具体代码 https://github.com/react-component/tree-select/blob/c29020400cd0990cd443501e325579adec3af351/src/hooks/useTreeData.ts#L64

导致页面阻塞的主要原因就是 4.x 会走一次DFS

因为要支持 cascader 的 search ，所以直接把(城市数据)大量json数据塞入组件。但是同样的代码 在 4.x 因为会走一次DFS导致页面阻塞很严重。并且现在能解决的方案就是将组件中的搜索给去除换成动态加载。
(formatTreeData)格式化数据的操作为什么不开放给开发者是否格式化 或者 开发者在业务代码中将数据格式化好。

### 期望的结果是什么？

将格式化数据操作 开放给开发者 或者 优化DFS导致的渲染阻塞问题

### 实际的结果是什么？

渲染阻塞

### 浏览器

Chrome

### 操作系统

Windows

**Comment by udbbbn** [comment]
这个是4.x版本![image](https://user-images.githubusercontent.com/24448345/143387092-7e28a124-5d34-464e-8ed5-4060b3fcfcaa.png)

这个是3.x版本
![image](https://user-images.githubusercontent.com/24448345/143387736-b029ac79-cd69-4a2c-ac3b-4cc65c2df7be.png)

项目地址默认为 4.x版本，点击 show 按钮可以感受到明显卡顿，再切换antd版本至 3.x 再进行测试，可感受到比4.x流畅

**Comment by udbbbn** [comment]
@afc163 已添加在线示例

**Comment by afc163** [comment]
这个预取确实伤性能。

**Comment by zombieJ** [comment]
类 Select 组件合并底层组件是为了更方便的维护，但是的确是为 TreeSelect 做的历史债没必要让 Cascader 承担。

**Comment by dalaoque** [comment]
我这卡的严重影响客户体验了，现在有哪个4.+ 版本可以保证性能可用呢？

**Comment by gwsbhqt** [comment]
I also have this problem

**Comment by Wtianliang** [comment]
@udbbbn 老哥，现在你是怎么处理这个问题的，是降级3.x了嘛？

**Comment by dalaoque** [comment]
I downgrade to version 4.15.5 with acceptable performance.

cc： @Wtianliang

**Comment by Wtianliang** [comment]
> I downgrade to version 4.15.5 with acceptable performance.
> 
> cc： @Wtianliang

Thank you！I solved it！

**Comment by afc163** [comment]
@zombieJ 解决了么？

**Comment by kliuj** [comment]
> > I downgrade to version 4.15.5 with acceptable performance.
> > cc： @Wtianliang
> 
> Thank you！I solved it！

hi 你这边 4.15.5 版本，大概有多少数据啊，我这边5000条数据，大概要卡20s才能展示。

**Comment by afc163** [comment]
测试了一下 antd@4.18.9，速度很快了：https://codesandbox.io/s/antd-reproduction-template-forked-s9sdku?file=/index.js

**Comment by niuniuaikeji** [comment]
看起来4.23.0版本还是很卡
