### ISSUE TITLE
Align prop is missing in col

### ISSUE THREAD

**Issue by GastonKhouri** [ant-design/ant-design#33015]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-b3p9k?file=/index.js)

### Steps to reproduce
Putting the align property in a col throws an error in typescript because Property 'align' does not exist on type 'IntrinsicAttributes & ColProps & RefAttributes <HTMLDivElement>'

### What is expected?
Allow me to set the align property without getting an error

### What is actually happening?
Error when placing the align property in a column, if it works but since it is not defined, it marks a type error

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | React ^17.0.2 |
| System | Windows 10 |
| Browser | Opera |

---
Thanks for the library!

**Comment by afc163** [comment]
Your codesandbox is not a TypeScript project.

**Comment by GastonKhouri** [comment]
Hello! Sorry, here it is with typescript

https://codesandbox.io/s/nifty-chatterjee-1gr2s?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/68894611/143509568-a2c5b9cf-a521-48db-a4bf-ab6d9ab4a636.png)

Greetings and thanks.

**Comment by afc163** [comment]
There is no `align` prop on Col in antd. See documentation: https://ant.design/components/grid/
