### ISSUE TITLE
Table使用固定表头、边框线、页头及页脚功能后样式出现的问题

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#3301]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:win7
- 浏览器及其版本:chrome最新

#### 您做了什么？

使用antd Table组件进行效果展示，功能有固定表头及添加表格边框线，页头和页脚。

#### 您期待的结果是：

正常显示数据，UI正常

#### 实际上的结果是：

在页头、页脚部分和table边框线有重合的现象，比较明显

#### 可重现的在线演示

http://codepen.io/wytheliang/pen/kkxZZB?editors=0010

**Comment by dreamcatcher081210** [comment]
这么多天没人回复，想必小蚂蚁们都休国庆了......静等10月8日小蚂蚁表情沮丧的打开这个issues....

**Comment by benjycui** [comment]
实在是难以遍历表格的各种组合。。。。

**Comment by ddcat1115** [comment]
我这儿压了几个table样式的问题了，我一起看下 😢
