### ISSUE TITLE
如何实现一个自定义表单组件？

### ISSUE THREAD

**Issue by Midqiu** [ant-design/ant-design#3302]
比如我自己封装了一个自定义的Input组件，那么我要实现哪些接口和方法才能让 `Form.create`化之后的表单获取到我的组件的属性呢？

比如我想要这样使用：
```
<FormItem label="用户" hasFeedback >
          {getFieldDecorator('person', {
            rules: [  { required: true} ]
          })(<MyInput  /> )}
</FormItem>
```
我这个MyInput  的value是一个对象。我要如何实现MyInput呢？

**Comment by benjycui** [comment]
See: https://github.com/react-component/form/issues/32

**Comment by afc163** [comment]
写一个简单的文档（如何接入自定义表单组件）专门说这个事。

**Comment by peterpuppy** [comment]
自定义这个行为能给个方案吗，我写的控件是上传图片到oss。
获取的是这个的文件名。
```
 <Input type='file' onChange={this.onChange}/>
```
目前我的解决方案是再放置一个display:'none' 的input。
上传aliyun后onChange事件里面修改这个input的value，getFieldsValue可以获取到地址。

setFieldsValue这些就没辙了。

控件代码：
```
render() {
        return (
            <div>
                <input id={this.props.id} type="text" value={this.state.image_url} style={{display:'none'}}/>
                <Input type='file' onChange={this.onChange}/>
                <img src={this.state.image_url} id="show_img" style={{width:100}}/>
            </div>
        );
    },
```

**Comment by afc163** [comment]
http://react-component.github.io/form/examples/overview.html

简单的说就是要实现 `value` 和 `onChange(value|event) {}` 这两个接口。类似原生的控件。

**Comment by ohmyauthentic** [comment]
如何接入自定义表单组件 这个文档哪有 @afc163

**Comment by afc163** [comment]
可以关注：https://github.com/ant-design/ant-design/issues/3594
