### ISSUE TITLE
Table 树型自定义展开按钮的列顺序问题

### ISSUE THREAD

**Issue by zhangqhzz** [ant-design/ant-design#33023]
### 重现链接

https://codesandbox.io/s/xel0q?file=/src/App.js

### antd 版本

4.17.1

### 重现步骤

通过修改App中Tabel组件dataSource, 在data1和data2之间切换，比较两次显示出来的展开按钮的位置有差别

data2时，展开按钮在checkbox的右侧
data1时，展开按钮在checkbox的左侧

简单说明:例子是经过精简，难免有很多BUG,但不影响测试结果。
我的测试例子是通过expandedRowRender 生成子表，在data1的表现是因为主表中没有子项（children为null)
，而data2的表现是因为主表中有一级子项(children)，我的子表数据dataSub是挂在主表的子项children下

### 期望的结果是什么？

dataSource不管是data1还是data2都应该默认在checkbox的同一侧，目前是可以expandIconColumnIndex通过设定，但在我这个测试数据data2时，且checkbox时有点问题，

### 实际的结果是什么？

data2时，展开按钮在checkbox的右侧
data1时，展开按钮在checkbox的左侧

### 浏览器

Firefox, Chrome, Edge

### 操作系统

Windows

**Comment by afc163** [comment]
两者的展开按钮位置不同，树形数据里展开按钮是放在单元格内的，并非独占一列，因此没办法放在最左边。

**Comment by zhangqhzz** [comment]
但是data1从页面展现来看也是树型，父一层，子一层（虽然这层是另外获取数据产生），给用户的感觉还是树，展开按钮却在左边
而data2，虽然父多了一层，却在右边，用户不会管这些的


那能不能父一层时，也放在右边？


我这个就没解了吗？ 想要放在左边的永远都是一个梦？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月25日(星期四) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Table 树型自定义展开按钮的列顺序问题 (Issue #33023)





 
两者的展开按钮位置不同，树形数据里展开按钮是放在单元格内的，并非独占一列，因此没办法放在最左边。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
