### ISSUE TITLE
Radio组件在浏览器缩放后变形

### ISSUE THREAD

**Issue by zhouhuan327** [ant-design/ant-design#33036]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/radio/](https://ant.design/components/radio/)

### Steps to reproduce
在antd官网就能重现

将浏览器缩放调整到110%

缩放前:
![image](https://user-images.githubusercontent.com/24819600/143513976-df5fd4fc-5603-4de4-95b4-a1cc13ffb6fc.png)

缩放后:
![image](https://user-images.githubusercontent.com/24819600/143514001-5ac0ae9f-2317-4ef3-9987-8263bc2c9ab7.png)

### What is expected?
缩放不影响组件

### What is actually happening?
Radio组件会有一定的变形

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | React17 |
| System | macoss |
| Browser | 95.0.4638.69（正式版本） (arm64) |

**Comment by zhouhuan327** [comment]
缩放到80%的情况下,中间的蓝点不居中了

![image](https://user-images.githubusercontent.com/24819600/143514173-b3e239f5-4c80-4d56-9ef0-d78ebcbdfc21.png)

**Comment by afc163** [comment]
这个没啥好办法，变型的很随机，而且随着 Chrome 版本更新时有时无。

**Comment by hydraZty** [comment]
换个定位方式可能有效，我会试试，稍后 pr
