### ISSUE TITLE
点击select下拉选项 箭头不反转

### ISSUE THREAD

**Issue by AkuuGuo** [ant-design/ant-design#33046]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
点击select下拉选项 箭头不反转

### What is expected?
select下拉选项出现 箭头出现反转

### What is actually happening?
点击select下拉选项 箭头不反转

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | react |
| System | macOS 11.6 |
| Browser | Chrome |

**Comment by xrkffgg** [comment]
en ，设计就是这样
