### ISSUE TITLE
Search input onSearch is fired when allowClear icon is clicked

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#33059]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/search-box-antd-4-17-1-forked-3h8kl?file=/index.js)

### Steps to reproduce
Type on the first input and click on the search icon or press enter, onSearch should fire.
Type on the second input and click on the search icon or press enter, on search should fire.
Type on the second input and click on the clear icon, on search will also fire.

### What is expected?
onSearch to not fire when user is clearing the value of the input.

### What is actually happening?
onSearch is firing.

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Brave |

---
If this is not a bug and intended design, maybe make this optional?

**Comment by afc163** [comment]
It is intended design

**Comment by balboFK** [comment]
@afc163 what use case does it make sense tough?
IMO when the user clears the search, he is going to type another value, there is no need to fire what is on the "search", he is not really "searching" for anything yet, just clearing what was on the input.

If I don't want it to fire when the user clears the search, how would I achieve that?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18729#issuecomment-529502936
