### ISSUE TITLE
Table 没有表单功能

### ISSUE THREAD

**Issue by cike8899** [ant-design/ant-design#3305]
看了下table的文档，貌似里面没有提供插入表单的功能，如textbox,dropdown等，还有就是没有dbclick可见，失去焦点的时候隐藏表单。

**Comment by ouzhou** [comment]
可以使用Model代替吧

**Comment by benjycui** [comment]
https://ant.design/components/table/#Column

`columns[n].render`

**Comment by benjycui** [comment]
Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by cike8899** [comment]
render  可以return 一个React.Element吗？
