### ISSUE TITLE
能否开放CheckBo.Group onChange回调中是否sort的配置

### ISSUE THREAD

**Issue by ICEPepsiCola** [ant-design/ant-design#33054]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
CheckBo.Group onChange回调中加入了sort函数，导致无法感知用户最后一次选中的值

### What does the proposed API look like?
CheckBo.Group onChange回调中的sort可以被忽略

code path: /antd/es/checkbox/Group.js

source code
```tsx
    var opts = getOptions();
    onChange === null || onChange === void 0 ? void 0 : onChange(newValue.filter(function (val) {
      return registeredValues.indexOf(val) !== -1;
    }).sort(function (a, b) {
      var indexA = opts.findIndex(function (opt) {
        return opt.value === a;
      });
      var indexB = opts.findIndex(function (opt) {
        return opt.value === b;
      });
      return indexA - indexB;
    }));
  };
`tsx


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
建议存储选中值，前后比较一下。CheckGroup 是顺序无关的，value 里不应该带顺序。
