### ISSUE TITLE
ant-design Virtual Table Does not support render prop

### ISSUE THREAD

**Issue by Chasen-Zhang** [ant-design/ant-design#33050]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
support render prop

### What does the proposed API look like?
 render: (text: any, record: any, index: any) => `do something}`,

### Need Reproduce
https://codesandbox.io/s/xu-ni-lie-biao-antd-4-17-1-forked-0wn04?file=/index.js

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/143555827-69cc21e2-a2c2-425a-99b2-7fa334557254.png)

**Comment by Chasen-Zhang** [comment]
https://codesandbox.io/s/xu-ni-lie-biao-antd-4-17-1-forked-0wn04?file=/index.js

**Comment by DVSoftware** [comment]
@Chasen-Zhang  Ant does not support virtualized table out of the box, this is just an example how you can override the components to achieve that. You will need to implement that yourself on line 78 (call render if it exists).

**Comment by Chasen-Zhang** [comment]
thank you!

**Comment by DVSoftware** [comment]
@Chasen-Zhang https://github.com/wubostc/virtualized-table-for-antd works pretty well, i just added it to my project.

**Comment by Chasen-Zhang** [comment]
@DVSoftware  Does it support fixed columns?
