### ISSUE TITLE
Table组件树形数据展示时，列配置中render函数内拿到的行数据索引不正确

### ISSUE THREAD

**Issue by wuyongde** [ant-design/ant-design#33056]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/shu-xing-shu-ju-zhan-shi-antd-4-17-1-forked-migqw?file=/index.js)
### Steps to reproduce
树形表格数据（父级行中有children字段）经过Table组件渲染后，在列配置中render函数内拿到的索引不正确。
比如下面这个树形数据：
`
[
{key:'row0',children:[
{key:'row0-0'},
{key:'row0-1'}
]},
{key:'row1',children:[
{key:'row1-0'},
{key:'row1-1'}
]}
]
`

### What is expected?
在列配置的render函数中拿到的索引（即第三个参数）应该如下：
 0
    0
    1
1
    0
    1

### What is actually happening?
在列配置的render函数中拿到的索引（即第三个参数）实际如下：
 0
    1
    2
3
    4
    5

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | 16.14.21 |
| System | macOS Big Sur |
| Browser | chrome 96.0.4664.55 x64 |

---
旧版本（测试4.16.13,其他未测）是正确的，新版本4.17.1上拿到的索引不对

**Comment by akira0912** [comment]
我用的"antd": "^4.23.4",index的结果还是不对哎？
![image](https://user-images.githubusercontent.com/68734384/205559070-aa0f66df-46a5-4847-a953-ada3d63ca59b.png)
