### ISSUE TITLE
DatePicker.RangePicker activeBar 宽度计算错误

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#33052]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-shadow-tj3jw?file=/App.tsx:4363-4385)

### Steps to reproduce
点击展开

### What is expected?
不出现滚动条

### What is actually happening?
出现滚动条

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | 17 |
| System | windows |
| Browser | chrome |

---
activeBar 宽度计算错误

**Comment by afc163** [comment]
来个 PR？
