### ISSUE TITLE
Select的value支持对象

### ISSUE THREAD

**Issue by acfasj** [ant-design/ant-design#33069]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. 我知道有labelInValue, 虽然可以让value变成对象, 但是在onChange的时候,  onChange类型为`function(value, option:Option | Array<Option>)`,  需要的额外数据只会在`option`里传递, 不会在`value`里传递. 对应到这个codesandbox的例子, https://codesandbox.io/s/huo-de-xuan-xiang-de-wen-ben-antd-4-17-1-forked-97ngu?file=/index.js,  `extra`这个额外的属性只存在于`option`, 在`value`里不会有

2. 在上述的表述里, 我们知道,  Select的onChange的参数有两个, 为value和option. 结合`Form`使用的时候,  `Form.Item`会劫持`onChange`函数, 但是当我们需要使用在option里的关联的数据的时候, 现阶段往往还是需要加多一个变量,  再在Select的onChange来保存当前选中的value对应的option, 如以下codesandbox, https://codesandbox.io/s/huo-de-xuan-xiang-de-wen-ben-antd-4-17-1-forked-twgch?file=/index.js:445-451

抑或者再根据value来做一次遍历. 这样Form + Select使用起来真的很麻烦

搜索过有以下相关类似的issue:
- https://github.com/ant-design/ant-design/issues/15578
- https://github.com/ant-design/ant-design/issues/28879
...
但是我觉得都没有实际的解决这个问题

### What does the proposed API look like?
labelInValue为true的时候, `onChange`里回调的`value`, 会有除了`LabelInValue`接口以外的属性(即把`option`的数据也丢进去).

即: 
```tsx
 <Select
    labelInValue
    defaultValue={{ value: "1" }}
    style={{ width: 120 }}
    options={[
      { label: "lable1", value: "1", extra: "extra1" },
      { label: "lable2", value: "2", extra: "extra2" }
    ]}
    // v的数据结构为: { label: "lable1", value: "1", key: "1", extra: "extra1" }, 注意, 有`extra`
    onChange={v => console.log(v)}
  ></Select>
```

这样相对来说改动较小, 较符合现有接口使用情况, 最主要的是, 结合`Form`来使用的时候, 不用再额外监听`Select`的`onChange`了

**Comment by afc163** [comment]
设置 labelInValue 后，value 的内容是转换过的语义，和 options 可能对不上。例如定义了 `optionLabelProp` 的场景 https://codesandbox.io/s/huo-de-xuan-xiang-de-wen-ben-antd-4-17-1-forked-jiw5k?file=/index.js

这也是为什么会单独提供第二个 option 参数。

**Comment by acfasj** [comment]
可以理解, 但是我在日常开发已经碰到太多次这样的场景了, 希望可以在以后的版本考虑一下

此外对于 「 例如定义了 optionLabelProp 的场景」这个例子, 我没有get到, 既然用户自己设置了`optionLabelProp `, 那就是用户自己的选择, 不觉得有什么问题.....

**Comment by afc163** [comment]
你可以看看上面的例子，加了 optionLabelProp ，转化出来的 label 就不是原始数据里的 label 了。

**Comment by acfasj** [comment]
> 你可以看看上面的例子，加了 optionLabelProp ，转化出来的 label 就不是原始数据里的 label 了。

![image](https://user-images.githubusercontent.com/20757983/144161894-a06bddbc-f198-4e1f-95c9-18ab562504d0.png)

👌

**Comment by 98DE9E1F** [comment]
好好跟 element 学一学 ，还差得远呢
