### ISSUE TITLE
Prevent focusing other fields when Select dropdown is closed (mode=multiple)

### ISSUE THREAD

**Issue by Bosseskompis** [ant-design/ant-design#33065]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When closing a multi select field by pressing outside of it, I don't want another field to be inadvertently pressed, I just want the dropdown to be closed. This issue is particularly prominent on mobile when there often isn't much empty space for the user to press.

### What does the proposed API look like?
The design would be similar to how a modal backdrop functions (but without any visual styling)

| Props             | Description | Type | Default |
| ----------------- | ----------------- | ----------------- | ----------------- |
| useBackdrop | Adds an invisible backdrop that prevents clicking on elements outside of Select. | boolean | false |

There's probably a better name and description for this property.

**Comment by afc163** [comment]
Sorry, antd components is not designed for mobile device situation.
