### ISSUE TITLE
Image.PreviewGroup 没有onCurrentChange回调事件

### ISSUE THREAD

**Issue by Hanyuhuang** [ant-design/ant-design#33062]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
鼠标点击左右切换图片时，能获取最新current的值

### What does the proposed API look like?
onCurrentChange?: (current, prevCurrent) => void;

**Comment by afc163** [comment]
Duplicate of #38298
