### ISSUE TITLE
form's dependencies is valid

### ISSUE THREAD

**Issue by HkOri** [ant-design/ant-design#33068]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ce-shi-dependence-0gmv0?file=/index.tsx)

### Steps to reproduce
1、dont change the second value at first
2、just change the value of password

1、先不要动确认密码的值
2、更改密码的值

### What is expected?
confirm's validator func run

确认密码的校验函数触发执行

### What is actually happening?
nothing happened

什么也没有发生

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.2 |
| System | macOS Catalina 10.15.7 |
| Browser | Chrome 96.0.4664.55 |

**Comment by afc163** [comment]
依赖是单向的，字段变动时回去拿 dependencies 里的其他字段值，反之则不会监听。

**Comment by afc163** [comment]
但是修改过一次就会始终校验，确实行为不对齐。

**Comment by afc163** [comment]
和 #31271 应该是同一个问题，合并追踪。

**Comment by HkOri** [comment]
> 和 #31271 应该是同一个问题，合并追踪。

好的，谢谢解答
