### ISSUE TITLE
[Menu] 反复展开收起菜单时，动画效果偶尔会丢失

### ISSUE THREAD

**Issue by kkkisme** [ant-design/ant-design#33060]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/#:~:text=%E9%A1%B6%E9%83%A8%E5%AF%BC%E8%88%AA-,%E6%B0%B4%E5%B9%B3%E7%9A%84%E9%A1%B6%E9%83%A8%E5%AF%BC%E8%88%AA%E8%8F%9C%E5%8D%95%E3%80%82,-Navigation%20One](https://ant.design/components/menu-cn/#:~:text=%E9%A1%B6%E9%83%A8%E5%AF%BC%E8%88%AA-,%E6%B0%B4%E5%B9%B3%E7%9A%84%E9%A1%B6%E9%83%A8%E5%AF%BC%E8%88%AA%E8%8F%9C%E5%8D%95%E3%80%82,-Navigation%20One)

### Steps to reproduce
1、按视频中操作，反复点击菜单展开收起，会发现倒数第二次展开菜单的动画丢失了

### What is expected?
展开收起动画正常

### What is actually happening?
展开收起动画不正常

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17 |
| System | windows 11 |
| Browser | Chrome 96 |

**Comment by kkkisme** [comment]
https://user-images.githubusercontent.com/18638401/143601115-188fa207-ffea-400c-8064-cc9b6846e4c4.mp4

**Comment by afc163** [comment]
可以试试 5.x 中是否还存在这个问题，如果还存在，欢迎再开一个 issue。
