### ISSUE TITLE
tree组件异步加载 第一次点击之后 后面就无法在继续请求数据  参考之前 loadkeys移除的办法也没有实现

### ISSUE THREAD

**Issue by 596121109** [ant-design/ant-design#33071]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
  const onExpand = (keys, info) => {

        setTreeData({ currentKey: info.node.key || "" });
        let newLoadKeys = loadedKeys
        if (expandedKeys.length > keys.length) {
            newLoadKeys = loadedKeys.filter((i) => keys.includes(i))
            info.node.loading = false;
            info.node.loaded = false
            onLoadData({key:info.node.key})
        }

        setQuery({
            expandedKeys: keys,
            autoExpandParent: false,
        })
        setTreeData({ loadedKeys:newLoadKeys})
    };

### What is expected?
希望 每点一次 tree的那个加号按钮 都能够进行数据请求或者联动其他的效果

### What is actually happening?
探索中

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16 |
| System | win 11 |
| Browser | google |

**Comment by 596121109** [comment]
@afc163  我的意思是 我在issue里面寻找到和我类似的问题 他的版本是 3.0  然后 他说可以通过 移除loadkeys来 达到效果 但是我 这里移除 loadkeys无效           <Tree
                                titleRender={(d: any) => {
                                    return <span>
                                        <span>{d.title}</span>
                                        {d.haveSite && d.key == treeData.currentKey &&
                                            <>
                                                <div style={{ display: "inline-block" }}>
                                                    <Dropdown overlay={menu(d)} trigger={['click']} placement="bottomRight">
                                                        <span className={styles.acts}></span>
                                                    </Dropdown>
                                                </div>
                                            </>
                                        }
                                    </span>
                                }}
                                showLine
                                showIcon
                                height={500}
                                loadData={onLoadData}
                                onLoad={(loadedKeys) => {
                                    setTreeData({ loadedKeys })
                                }}
                                autoExpandParent={autoExpandParent}
                                defaultExpandedKeys={[currentKey]}
                                selectedKeys={[String(currentKey)]}
                                onSelect={onSelect}
                                onExpand={onExpand}
                                expandedKeys={expandedKeys}
                                loadedKeys={loadedKeys}  //异步加载的key
                            >
                                {renderTreeNode(treeData.list)}
                            </Tree>


 const onExpand = (keys, info) => {

        setTreeData({ currentKey: info.node.key || "" });
        let newLoadKeys = loadedKeys
        if (expandedKeys.length > keys.length) {
            newLoadKeys = loadedKeys.filter((i) => keys.includes(i))  移除loadkey
            info.node.loading = false;
            info.node.loaded = false
            //onLoadData({key:info.node.key})
        }

        setQuery({
            expandedKeys: keys,
            autoExpandParent: false,
        })
        setTreeData({ loadedKeys:newLoadKeys})  设置移除后的key 已经为空 移除了 但第二次点击还是无法请求
    };

**Comment by caojwaqzh** [comment]
解决了吗？我也遇到了

**Comment by woshixixi** [comment]
why is this issue closed?
