### ISSUE TITLE
同时引入date-picker与time-picker时，样式有冲突

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#3307]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- less 版本: 2.7.1
- less-loader 版本: 2.2.3
- 操作系统及其版本: Mac OS

#### 您做了什么？

引入了所有ant的less文件
```less
@import "~antd/lib/style/themes/default.less";
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";
```

#### 您期待的结果是：

当使用DatePicker的时间选择功能时，样式显示正常

#### 实际上的结果是：

时间选择功能没有样式，完全没有。

#### 问题产生的可能原因：

我看了一下代码，`@timepicker-prefix-cls`这个变量在两个地方有声明：`date-picker/style/index.less`以及`time-picker/style/index.less`，我现在输出的css里面，两个地方都输出了`.ant-time-picker`。当我把`time-picker/style/index.less`里面的变量名换个名字并且把使用的地方也相应改了以后（`@timepicker-prefix-cls` => `@timepicker-prefix-class`），就是让这两个地方的变量名不同，我发现date picker的时间选择功能的样式就有了，显示也正常了。

不太清楚为什么这两个地方的变量会冲突，我用的应该是最新的 less 和 less-loader了。

**Comment by afc163** [comment]
感谢反馈，fixed in #3312
