### ISSUE TITLE
If the InputNumber is placed in a form and the formItem is set name, when the value too large it will be confusing

### ISSUE THREAD

**Issue by coldice945** [ant-design/ant-design#33079]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-chi-cun-antd-4-17-1-forked-ibhzn?file=/index.js)

### Steps to reproduce
```
    <Form
      initialValues={{ inputNumber: 12222222222222222222222 }}
    >
      <Form.Item label="InputNumber" name="inputNumber">
        <InputNumber style={{ width: "100%" }} />
      </Form.Item>
    </Form>
```

### What is expected?
Show values as they are

### What is actually happening?
The value is wrong

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | macOS |
| Browser | Chrome 96.0.4664.55 |

**Comment by afc163** [comment]
Try `<InputNumber stringMode />`, InputNumber cannot handle big number by default.
