### ISSUE TITLE
没有 label 的 FormItem 自适应显示错位

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#33074]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bg3lv)

### Steps to reproduce
拖动浏览器宽度，切换窄屏。

### What is expected?
显示不错位，和前面带 label 的 filed 对齐

### What is actually happening?
错位

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | React 17 |
| System | WIN11 |
| Browser | Chrome |

![企业微信截图_20211129145458](https://user-images.githubusercontent.com/1730277/143821826-9be791b7-b44d-4bd0-90ab-d43280981d78.png)

**Comment by afc163** [comment]
期望的效果是什么？

**Comment by nuintun** [comment]
@afc163 和左边 Field 对齐

![image](https://user-images.githubusercontent.com/1730277/143847086-4c86e372-fc75-4e6e-9020-725366bc39b3.png)

**Comment by onlyscv** [comment]
这个自己调整CSS就可以了吧。
