### ISSUE TITLE
作为Tooltip直接子元素的Input组件，在disabled时无法触发Tooltip展示

### ISSUE THREAD

**Issue by wyh369352887** [ant-design/ant-design#33076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-1-forked-cmjk2?file=/index.js)

### Steps to reproduce
tooltip中直接放置一个disabled的input，无法触发tooltip显示

### What is expected?
显示tooptip

### What is actually happening?
tooltip没有显示

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | 18.0.0-beta |
| System | macOS BigSur 11.5.2 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-antd-4-17-1-forked-rstmh?file=/index.js

https://github.com/react-component/tooltip/issues/18#issuecomment-140078802

**Comment by boomler** [comment]
@afc163  注意到 tooltip 会给 button/switch 等几个组件加一个 wrapper， 解决无法 mouse 事件无法触发的问题。
感觉对于 input/switch 等组件而言，自身的外部结构改造一下就能充当这个 wrapper， tooltip 那里无需处理。
避免额外加 wrapper 引起的布局、样式问题，以及各种无法覆盖的 case.
