### ISSUE TITLE
AntTreeNodeCheckedEvent does not match with rc-tree CheckInfo

### ISSUE THREAD

**Issue by chris335** [ant-design/ant-design#33080]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I was looking for an interface to declare the type of the "info" parameter of the onCheck function of the AntTree.
I saw that there is an interface called AntTreeNodeCheckedEvent for this purpose. Unfortunately, it does not match the "CheckInfo" interface of the rc-tree.
There is also no typed onCheck function in your example, so I don't think I missed any interface in the library:
https://codesandbox.io/s/vqd3e?file=/index.js

### What does the proposed API look like?
Provide an interface to represent the "CheckInfo" interface used in the onCheck function of the rc-tree.

**Comment by chris335** [comment]
```javascript
export interface AntTreeNodeCheckedEvent {
    event: 'check';
    node: EventDataNode;
    checked: boolean;
    nativeEvent: MouseEvent;
    checkedNodes: DataNode[];
    checkedNodesPositions?: {
        node: DataNode;
        pos: string;
    }[];
    halfCheckedKeys?: Key[];
}
```

**Comment by chris335** [comment]
Why closed?

**Comment by kangodyan** [comment]
I have the same problem, Why closed @afc163
