### ISSUE TITLE
Modal有destroyAll方法，Drawer是否也可新增一个这样的方法，或者有其他替代方法？

### ISSUE THREAD

**Issue by Zex158** [ant-design/ant-design#33089]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当某个事件触发路由跳转，当前drawer不会被关闭（期望关闭）

### What does the proposed API look like?
Drawer.destroyAll

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32828#issuecomment-966749701

**Comment by Zex158** [comment]
> 

是这样的场景，用户在drawer处理一些表单，然后某个时刻触发异地登录或超时下线，此时跳转到登录界面，但是当前的drawer没有被关闭，如果用state控制，难道要每个drawer都写段代码去监听路由跳转事件么

**Comment by Zex158** [comment]
> [#32828 (comment)](https://github.com/ant-design/ant-design/issues/32828#issuecomment-966749701)

是这样的场景，用户在drawer处理一些表单，然后某个时刻触发异地登录或超时下线，此时跳转到登录界面，但是当前的drawer没有被关闭，如果用state控制，难道要每个drawer都写段代码去监听路由跳转事件么
