### ISSUE TITLE
position="left" closable Drawers have their close buttons on the left, not the right

### ISSUE THREAD

**Issue by ZLester** [ant-design/ant-design#33081]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3xny1)

### Steps to reproduce
Open any closable position=left drawer

### What is expected?
Drawers positioned on the left should have their close buttons on the right

### What is actually happening?
Drawers positioned on the left have their close buttons on the left

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16.14.0 |
| System | OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
It is by designed: https://github.com/ant-design/ant-design/pull/30908

Right corner leave to action buttons.

**Comment by BH-M87** [comment]
.ant-drawer-header-title {
    flex-direction: row-reverse;
  }

遇到一样的问题，加了个样式可以解决
