### ISSUE TITLE
Firefox浏览器拖拽上传会打开新的标签页

### ISSUE THREAD

**Issue by slmev** [ant-design/ant-design#33082]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
拖拽文件到拖拽到文件上传区域，成功后会打开一个新的标签页
![image](https://user-images.githubusercontent.com/18041237/143979030-22cb7ca9-3153-454a-a826-05dce0c84d7a.png)

### What is expected?
不打开标签页

### What is actually happening?
打开了新的标签页

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.1 |
| System | Win10 |
| Browser | Firefox 94.0.2(64位) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26938#issuecomment-700680974
