### ISSUE TITLE
Issue running tests when include ant components

### ISSUE THREAD

**Issue by Danjavia** [ant-design/ant-design#3308]
Pls, can you helpme?

Your project includes the enquirejs dependency. But I have issues when try to run tests into my project because 

```
matchMedia not present, legacy browsers require a polyfill
```

I don't know how to solve this issue.

this is my code

```
import React from 'react';
import { shallow } from 'enzyme';
import { expect } from 'chai';

// Import components for testing here
import NavbarCrm from '../NavbarCrmComponent';

describe('<NavbarCrm />', function () {

  if (typeof window !== 'undefined') {
    var matchMediaPolyfill = function matchMediaPolyfill(mediaQuery) {
      return {
        media: mediaQuery,
        matches: false,
        addListener: function addListener() {},
        removeListener: function removeListener() {}
      };
    };
    window.matchMedia = window.matchMedia || matchMediaPolyfill;
  }

  it('should have props for heading and children', function (done) {
    const wrapper = shallow(<Menu />);
    expect(wrapper.props().classes).to.be.defined;
    expect(wrapper.props().children).to.be.defined;
    done();
  });
});

```

I tried in all methods. Above, below but the same error ever. 

Can U help me?

I cant to solve the issue putting 

```
if (typeof window !== 'undefined') {
    var matchMediaPolyfill = function matchMediaPolyfill(mediaQuery) {
      return {
        media: mediaQuery,
        matches: false,
        addListener: function addListener() {},
        removeListener: function removeListener() {}
      };
    };
    window.matchMedia = window.matchMedia || matchMediaPolyfill;
  }
```

I include the above code in the line 49826 located at andt.js file into my node_modules And the problem is over. but this is not a good solution.

into **enquirejs/src/include/wrap.js** into the dist file for npm installed module. But it isn't a pretty solution.

**Comment by benjycui** [comment]
It curious for `enquire.js` is just used in site.

How do you use `antd` in your project?

Did you use our scaffold? `dva-cli` or `antd-init`(deprecated).

**Comment by Danjavia** [comment]
Is relative to enquire but under ant libraries.

The process for my app is.

```
npm install -S antd
import { Modal, Button } from 'antd' within react component
<Modal />... 
```

after this, when running the tests code wrote above.

```
matchMedia not present, legacy browsers require a polyfill
```

I know that is from enquire.js  but you have this library include into your npm package.

I don't know how to solve this issue. without touch the finally compiled code.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/38962e19f205a6a7b433dcc41eefd3d8ada40a4a/tests/index.test.js#L13-L25 did resolve our problems in js-dom

You could keep looking up https://github.com/WickyNilliams/enquire.js/issues/82 or https://github.com/weblinc/media-match , and you have to dig the solution by yourself~

**Comment by kushniro** [comment]
to save some people time in the future: 
it seems to be solved inside antd by adding a polyfill before the react-slick import but babel moves it after the requires in the compiled code in the npm package.
see: https://github.com/babel/babel/issues/2061

so to get around this you can is 'require' instead of 'import' for your component in your test code. 

any ideas for a better solution?

**Comment by benjycui** [comment]
Try to upgrade to the latest `antd`, for we had add [polyfill](https://github.com/ant-design/ant-design/blob/cebf3a4c9eea91b49f25604e485e1cad3a206cfa/components/carousel/index.tsx#L1-L16) for `react-slick`

**Comment by Danjavia** [comment]
Is good for me now. The test under latest version run without trouble.

**Comment by eranimo** [comment]
This doesn't appear to be fixed with the latest antd version

**Comment by fancymo** [comment]
I try to update to the latest version, but it is still an error, crying~

**Comment by aliyanno** [comment]
This is still throwing this error when working with react-snapshot. have to move to a new UI library :(

**Comment by sourcesoft** [comment]
I still have the problem using the latest version

**Comment by benjycui** [comment]
> I still have the problem using the latest version

@sourcesoft  re-producible repo?

**Comment by ctingwai** [comment]
On my site, we have to import individual component instead of importing the entire antd components e.g. `import Form from 'antd/lib/form'` instead of `import Form from 'antd'`, maybe it has something to do with the `Carousel` component since it's the only component that require polyfill?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6560

**Comment by afc163** [comment]
Hey guys, found a solution in #7344 thanks to #6560.

Just make sure our matchMedia is called before importing react-slick.
