### ISSUE TITLE
[input-number]  get an invalid value when `max`'s precision don't match component's precision

### ISSUE THREAD

**Issue by boomler** [ant-design/ant-design#33084]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-2-forked-noqz5)

### Steps to reproduce
focus each input-number,  then blur

### What is expected?
all input-number's value change to  9

### What is actually happening?
the second input-number's value not changed

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | All |
| Browser | All |

**Comment by boomler** [comment]
i will take this.

**Comment by tangjinzhou** [comment]
@boomler @afc163 
when we set `min={1} max={10}  precision={0}`,  we can not input min value
