### ISSUE TITLE
setFieldsValue not working in RangePicker onCalendarChange

### ISSUE THREAD

**Issue by stanzah** [ant-design/ant-design#33094]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qsrzi)

### Steps to reproduce
在默认设置了 `RangePicker` 时间范围的情况下。

首先点击起始时间进行时间设置，点击确认后，在 `onCalendarChange` 方法中想要清除结束时间的时间设置。

### What is expected?
结束时间清除，是未选中的状态

### What is actually happening?
结束时间未清除，仍是之前设置的默认值

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | Chrome/91.0.4472.124 |

**Comment by afc163** [comment]
You can add setTimeout for it: https://codesandbox.io/s/antd-reproduction-template-forked-oz6qr

**Comment by EmilyLike** [comment]
> You can add setTimeout for it: https://codesandbox.io/s/antd-reproduction-template-forked-oz6qr
同样遇到这个问题了。我是通过 onfocus 解决的。在onfocus中判断，如果当前 focus 的值是结束日期，就置空。
