### ISSUE TITLE
table的列头中是否可以加入输入框

### ISSUE THREAD

**Issue by luckyyang** [ant-design/ant-design#3309]
目前table的列头有排序和过滤，我想加入一个input，对table的数据进行搜索。目前是否可以做到？

#2033 中有讨论，但是没有后续了

**Comment by ouzhou** [comment]
你可以在外面写一个input + button,然后search啊，返回的数据 修改state的list[]就好了
https://github.com/dvajs/dva/tree/master/examples/user-dashboard
可以参考这个

**Comment by luckyyang** [comment]
谢谢，我知道那样可以实现。如果要搜索多个字段的话，需要多个搜索框，那样很乱

我只是想要嵌入式的那种

**Comment by benjycui** [comment]
`columns[n].title` 可以是一个 JSX 元素。

**Comment by ystarlongzi** [comment]
![image](https://cloud.githubusercontent.com/assets/2840462/19474835/fff5c3ec-9563-11e6-948b-a47a04218066.png)

基于业务实现了这样的效果 😊

**Comment by luckyyang** [comment]
👍
