### ISSUE TITLE
Select多选，会出现临界值问题，导致页面不停闪动， 往早日修复

### ISSUE THREAD

**Issue by chenyingqiao** [ant-design/ant-design#33092]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#components-select-demo-search](https://ant.design/components/select-cn/#components-select-demo-search)

### Steps to reproduce
Select 多选的maxTagCount配置了"responsive"时，当选项宽度达到某个临界值，会把输入框高度撑开

### What is expected?
输入框高度没有改变，最后一个标签被收起不直接展示

### What is actually happening?
输入框高度撑开

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | react@^16.13.1 |
| System | windows |
| Browser | 谷歌浏览器 |

**Comment by chenyingqiao** [comment]
> Hello @chenyingqiao. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @chenyingqiao, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

复现版本
复现demo : https://codesandbox.io/s/antd-reproduction-template-forked-hx7td?file=/index.js
macos Big Sur
chrome  版本 95.0.4638.69（正式版本） (x86_64)

**Comment by afc163** [comment]
@chenyingqiao 看看最新的 4.19.5 和 Chrome 浏览器上还存在这个问题么？

**Comment by wogaozhixu** [comment]
有解决吗？

**Comment by dxtbrave** [comment]
请问有解决吗

**Comment by xiaojingyuaner** [comment]
我也是这个问题
