### ISSUE TITLE
antd3.X版本过渡到ant4.X版本过程中碰到 ant4.X的样式无法按需引入

### ISSUE THREAD

**Issue by meicy** [ant-design/ant-design#33101]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
1、package.json   
     "antd": "^3.26.7",
    "antd4": "npm:antd@^4.17.2",
    "babel-loader": "^7.1.4",
    "babel-plugin-import": "^1.11.0",
2、 .babelrc 文件配置"plugins": [
    "react-hot-loader/babel",
    [
      "import",
      {
        "libraryName": "antd",
        "style": true
      }
    ],
    [
      "import",
      {
        "libraryName": "antd4", 
        "style": true
      }
    ],
    "transform-decorators-legacy",
    "transform-runtime"
  ]
3、业务引入import { Cascader } from 'antd4'

antd 是3 的版本，3的版本正常运行，但是antd4里面的样式无法按需引入，目前解决import 'antd4/es/cascader/style/index' 这种方式

### What is expected?
import { Cascader } from 'antd4'  可以直接实现样式的按需引入

### What is actually happening?
需要单独引入      import 'antd4/es/cascader/style/index'    

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | react |
| System | window 10 |
| Browser | chrome无关版本 |

**Comment by afc163** [comment]
不建议 antd3 和 antd4 进行混用。

**Comment by lorcannn** [comment]
试试 `.babelrc` -> `bable.config.js`？
