### ISSUE TITLE
When the table in modal, two scrollbar will show up when set sticky

### ISSUE THREAD

**Issue by cwjTerrace** [ant-design/ant-design#33104]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sui-ye-mian-gun-dong-de-gu-ding-biao-tou-he-gun-dong-tiao-antd-4-17-2-forked-w3fmt?file=/index.js)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/29698222/144180198-d3987933-dd25-43a3-863c-4860e5d37f09.png)
打开链接

### What is expected?
only one scrollbar 

### What is actually happening?
two scrollbar

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.0 |
| System | mac |
| Browser | edge |

**Comment by WaterHong** [comment]
I got the same question with antd 4.16.13 when 'sticky' and 'scroll' are used at the same time

**Comment by cwjTerrace** [comment]
@shaodahong

**Comment by shaodahong** [comment]
Can resolve by
```tsx
sticky={{
  getContainer: () => document.querySelector('.ant-modal-body')
}}
```

**Comment by pisyell** [comment]
设置getContainer 在某些情况下并没有用
