### ISSUE TITLE
mentions组件需求建议：1.增加一个保存"提及用户"的数组变量；2.@的用户颜色变链接色；3.删除时是整体删除@的用户名

### ISSUE THREAD

**Issue by yuan-ze** [ant-design/ant-design#33103]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.个人觉得方便后端处理@到的用户，做信息提醒
2.颜色变成链接色用户明显
3.删除时整体删除可以避免删掉了空格、多打或少打导致@信息不准确

### What does the proposed API look like?
和现在用法差不多吧，就是多一个变量绑定@的用户列表

**Comment by afc163** [comment]
1. 增加一个保存"提及用户"的数组变量

可以在 onChange 中用正则做一下匹配，拿到 @xx 的列表。

> 2.颜色变成链接色用户明显
> 3.删除时整体删除可以避免删掉了空格、多打或少打导致@信息不准确

需要引入 contenteditable，目前的技术方案无法支持，暂时没有改动的计划。
