### ISSUE TITLE
最新4.17.2版本有兼容性问题

### ISSUE THREAD

**Issue by Amyuan23** [ant-design/ant-design#33115]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
随便找个低版本的浏览器就能重现了

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 无 |
| System | 无 |
| Browser | 低版本 |

---
4..17.2 打包出的代码有Object.values代码，并且没有用babel corejs 3 处理，导致低版本浏览器（es5）不兼容（控制台报错&白屏）。
希望处理一下！

**Comment by Amyuan23** [comment]
![image](https://user-images.githubusercontent.com/25892910/144224926-61316eb4-4369-43fe-82f9-2d9f95333425.png)

**Comment by afc163** [comment]
https://github.com/react-component/select/pull/641/files#diff-72ec48c7788c5c428904bee5501e48f2f6ddcd678eb89dc03788715c14452860R254

@zombieJ 来改改。
