### ISSUE TITLE
New global theming doesn't work

### ISSUE THREAD

**Issue by FouMez** [ant-design/ant-design#33119]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/FouMez/antd-global-theme-bug-reproduction](https://github.com/FouMez/antd-global-theme-bug-reproduction)

### Steps to reproduce
1) Run the app
2) According to the example shown on the configProvider documentaion (global theming) the primary button color should change but it doesn't..

### What is expected?
According to the example shown on the configProvider documentaion (global theming) the primary button color should change but it doesn't..

### What is actually happening?
The color remain the same.

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Firefox latest |

---
tried in codeSandBox and in codePen and in StackBlitz but it didn't work, I also changed to chrome and it didn't work

**Comment by afc163** [comment]
https://ant.design/docs/react/customize-theme-variable#Import-antd.variable.min.css
