### ISSUE TITLE
Transfer组件中嵌套Radio组件，选中radio会同时勾选transfer的选项

### ISSUE THREAD

**Issue by yldtc** [ant-design/ant-design#33110]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-k29f6)

### Steps to reproduce
点击radio组件的圆圈，会同时勾选transfer组件

### What is expected?
点击radio组件，不要勾选transfer组件

### What is actually happening?
点击radio组件，会同时勾选transfer组件

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | macOS 12.0.1 |
| Browser | chrome  96 |

**Comment by afc163** [comment]
看上去类似 https://zhuanlan.zhihu.com/p/431268270

阻止冒泡吧 https://codesandbox.io/s/antd-reproduction-template-forked-i9ce9?file=/index.js
