### ISSUE TITLE
使用getFieldDecorator 和Model配合时，向input输入值后关闭再打开并不会是initialValue

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#3311]
antd recently
在Model组件中使用了Form，并用getFieldDecorator 设置了initialValue，，我期望打开这个Model后input框内会有初始值，当我修改input框的内容后关闭这个Model再打开这个Model仍然是initialValue ，但实际情况是我输入input框，关闭Model再打开，这个Model的值仍然是我刚才输入的值而不是initialValue 

场景：
![image](https://cloud.githubusercontent.com/assets/7693866/19158456/60db5e12-8c1b-11e6-861d-6a6018ab3f64.png)
点击编辑会出现这个Model框

**Comment by afc163** [comment]
initialValue 和 defaultValue 一样，只有首次生效，后续建议使用 `this.props.form.setFieldValue` 控制对应的值。

**Comment by aizigao** [comment]
@afc163 resetFields 是用设置到 initialValue的，可是initialValue只有首次生效，如何才能用resetFields设置到默认的数据状态呢
