### ISSUE TITLE
How to disable every wednesday of every week

### ISSUE THREAD

**Issue by devluked** [ant-design/ant-design#33122]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xbzbp?file=/index.js)

### Steps to reproduce
Click on date picker
All dates are disabled

### What is expected?
Want to try an disable the 3rd day (wednesday) of every week

### What is actually happening?
Every date is disabled

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | macOS 11.3.1 (20E241) |
| Browser | Chrome |

**Comment by afc163** [comment]
Please check https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date
