### ISSUE TITLE
[4.0] 操作DatePicker.RangePicker的renderExtraFooter上定义的控件时，面板会关闭

### ISSUE THREAD

**Issue by Hitotsubashi** [ant-design/ant-design#33125]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-benji-qx391?file=/src/App.js)

### Steps to reproduce
点开日期选择器，然后点击renderExtraFooter中定义的Radio.Group中任意一项，弹出面板会关闭

### What is expected?
面板不应该关闭

### What is actually happening?
面板会关闭

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome 96.0.4664.45 |

**Comment by afc163** [comment]
阻止一下冒泡：https://codesandbox.io/s/sharp-robinson-8i664?file=/src/App.js

**Comment by Hitotsubashi** [comment]
https://codesandbox.io/s/sharp-robinson-8i664?file=/src/App.js
你好，你这个加了stopPropagation也没效果。

**Comment by Hitotsubashi** [comment]
> 阻止一下冒泡：https://codesandbox.io/s/sharp-robinson-8i664?file=/src/App.js

https://codesandbox.io/s/sharp-robinson-8i664?file=/src/App.js
你好，你这个加了stopPropagation也没效果。

**Comment by afc163** [comment]
https://codesandbox.io/s/eloquent-pond-kygbw?file=/src/App.js

这样，避免焦点丢失。

**Comment by Hitotsubashi** [comment]
> https://codesandbox.io/s/eloquent-pond-kygbw?file=/src/App.js
> 
> 这样，避免焦点丢失。

还是达不到效果

**Comment by afc163** [comment]
晚点再看看，有空也可以帮我们排查一下。

**Comment by hydraZty** [comment]
原因感觉没那么简单，试了下默认样式的 Radio，点击⚪中就不会触发日期面板关闭。点击单选其他位置还是会触发关闭。
@Hitotsubashi 业务上先用 `Button` 实现单选避开 `Radio` 吧。

**Comment by haungxinyan** [comment]
今天加了个Select也遇到了这个问题
点击Select还没来得及展开日历就关闭了

**Comment by kaocong** [comment]
1

**Comment by kaocong** [comment]
dsff

**Comment by frankzhangc** [comment]
😳input也无法聚焦

**Comment by standbyoneself** [comment]
Same...

**Comment by Rachel-Shen** [comment]
不加 stopPropagation input也无法聚焦，加了 stopPropagation 一聚焦面板就关闭了😳 请问还有什么解决方案嘛

**Comment by xjhjzxh** [comment]
same problem, 暂时用主动控制open的方法解决了, 但感觉不是个好方案

**Comment by Yuiai01** [comment]
我来尝试解决一下。

**Comment by crazyair** [comment]
> 我来尝试解决一下。

这个问题是 4.0 的，解决需要在 4.0 解决吗

**Comment by Yuiai01** [comment]
> > 我来尝试解决一下。
> 
> 这个问题是 4.0 的，解决需要在 4.0 解决吗

需要的，本来是想着到时候 copy 过去的。

**Comment by standbyoneself** [comment]
wtf

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
