### ISSUE TITLE
[4.0] DatePicker.RangePicker设置picker为“week”后，选择开始和结束时间还是会根据点击到日期来赋值

### ISSUE THREAD

**Issue by Hitotsubashi** [ant-design/ant-design#33123]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-glade-2p51x?file=/src/App.js:130-141)

### Steps to reproduce
就正常地选择吧

### What is expected?
开始时间应该是当周的第一天，
结束时间应该是当周的最后一天

### What is actually happening?
开始时间和结束时间都是你点击到的那个日期。

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome 96.0.4664.45 |

---
把picker设置成“month”、“quarter”、“year”也有这种情况。
给人感觉就是你好像选择查询9月和10月的记录，其实你查询范围是9月3日～10月3日之前的记录。

**Comment by afc163** [comment]
https://codesandbox.io/s/cocky-curie-hw3e5?file=/src/App.js

自行处理一下吧，选 week 时，具体日期已经不重要了，这里交互上也未作特殊处理。
