### ISSUE TITLE
ellipsis Suffix lost React Context

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design#33126]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-2-forked-o03us?file=/index.js)

### Steps to reproduce
- open codesandbox

### What is expected?
no error

### What is actually happening?
lost context

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | any |
| System | any |
| Browser | any |

---
https://github.com/ant-design/ant-design/blob/441eb649bd7c7609fffd960c29e1b999361f1e4e/components/typography/util.tsx#L110

ellipsis suffix create a clone element but not in original component tree, so react context is lost, suggest change to React Portal

**Comment by paranoidjk** [comment]
cc/ @zombieJ

**Comment by gpetrioli** [comment]
I think this is an issue with accessing the prop before it has been set.

If you change your suffix to "guard" against incomplete context values, it will work and will eventually get access to the value in the context

```
class Suffix extends React.Component {
  static contextType = FooContext;
  foo = this.context.userInfo.scores?.a; // added a ? before the last . to handle missing scores property
  render() {
    return "xx" + this.foo;
  }
}
```

So the initial render get the initial value, but once it gets updated the `Suffix` will rerender as expected.
