### ISSUE TITLE
官网4.17.2版本，步骤条，ui错位

### ISSUE THREAD

**Issue by 15673442540** [ant-design/ant-design#33127]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/steps-cn/](https://ant.design/components/steps-cn/)

### Steps to reproduce
打开你们的官方文档，步骤条组件，有个地方的ui错位了，pangding有问题

### What is expected?
期望正常

### What is actually happening?
实际错误

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | react |
| System | windows |
| Browser | 12 |

---
希望你们补充个富文本编辑器  能让我截图

**Comment by PeachScript** [comment]
没找到错位的 demo，请提供具体位置和截图，issue 编辑器可以直接直接粘贴、拖拽图片进编辑区域或点击下方附件区域来添加图片

**Comment by afc163** [comment]
> 希望你们补充个富文本编辑器 能让我截图

这是 GitHub issue，并不是我们在维护的网站功能，你可以直接贴图。

**Comment by mode365Dong** [comment]
![image](https://user-images.githubusercontent.com/88695831/144540693-ea2acdcf-f0cb-4ada-b60c-269f59a5b7c1.png)
贴个图也不难啊
