### ISSUE TITLE
react的onRow的click点击事件似乎有点问题

### ISSUE THREAD

**Issue by fni26316** [ant-design/ant-design#33120]
表格组件的行点击事件和文本选中有冲突,比如说表格的行加了onRow事件,然后你在想选中改行单元格的文本时也会同事触发点击事件,如果点击事件是页面跳转,就没办法执行选中复制文本操作,
这个不知道大佬们是否可以优化一下
建议点击事件中如果有鼠标移动(mousemove) 那就默认不触发click事件 只做文本选择操作

**Comment by a798032825** [comment]
> 表格组件的行点击事件和文本选中有冲突,比如说表格的行加了onRow事件,然后你在想选中改行单元格的文本时也会同事触发点击事件,如果点击事件是页面跳转,就没办法执行选中复制文本操作, 这个不知道大佬们是否可以优化一下 建议点击事件中如果有鼠标移动(mousemove) 那就默认不触发click事件 只做文本选择操作

我也遇到了这个问题，想请教下是如何解决的呢。

**Comment by 13832198312** [comment]
> > 表格组件的行点击事件和文本选中有冲突,比如说表格的行加了onRow事件,然后你在想选中改行单元格的文本时也会同事触发点击事件,如果点击事件是页面跳转,就没办法执行选中复制文本操作, 这个不知道大佬们是否可以优化一下 建议点击事件中如果有鼠标移动(mousemove) 那就默认不触发click事件 只做文本选择操作
> 
> 我也遇到了这个问题，想请教下是如何解决的呢。

请问解决了吗
