### ISSUE TITLE
Popover elements remain in DOM after being closed.

### ISSUE THREAD

**Issue by mtadams007** [ant-design/ant-design#33137]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://zvrmw.csb.app/)](https://codepen.io/mtadams007/full/BawNQVp

### Steps to reproduce
Open any popover example in the ant design documentation. Open it in a new window and inspect the elements. Open and close the popover. You can see that the popovers are not removed from the DOM

### What is expected?
I would expect the popovers to be removed from the DOM when closed.

### What is actually happening?
The popovers remain in the DOM although they are hidden.

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.0 |
| System | Ubuntu |
| Browser | Chrome |

---

Here's a gif showing the context menus in the DOM based on the example linked above:

![antDesignContextMenus](https://user-images.githubusercontent.com/36059111/144428745-17fd6496-1a36-48a2-b17c-6f652e199608.gif)

This may be related to https://github.com/ant-design/ant-design/issues/26071

**Comment by afc163** [comment]
`destroyTooltipOnHide`
