### ISSUE TITLE
按钮在仅有图标时不会垂直居中

### ISSUE THREAD

**Issue by meesii** [ant-design/ant-design#33139]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/20596](https://github.com/ant-design/ant-design/issues/20596)

### Steps to reproduce
```
<a-button class="filter-button" size="small" shape="circle">
    <template #icon>
        <SettingFilled style="color:#B8B8B8" />
    </template>
</a-button>
```

### What is expected?
图标居中

### What is actually happening?
图标偏下

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 1 |
| System | Win10 |
| Browser | 1 |

**Comment by afc163** [comment]
You should report it to https://github.com/vueComponent/ant-design-vue/issues
