### ISSUE TITLE
Ellipsis-state and text size for Typography.Text not restored after resize when tooltip or onEllipsis props set

### ISSUE THREAD

**Issue by gerald24** [ant-design/ant-design#33132]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-e9lh2?file=/index.js:0-2968)

### Steps to reproduce
Use either property tooltip or onEllipsis for Typography.Text. Eg. ellipsis={{tooltip: true}} or ellipsis={{onEllipsis: () => {} }}

### What is expected?
Text-size and ellipsis state will be restored (synced) after resize

### What is actually happening?
After shrinking and than expand the width - text will stay in shrinked state

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | node 16.13.0 |
| Browser | all green browsers (safari, firefox, chrome) |

---
Typography.Paragraph works fine

**Comment by gerald24** [comment]
might be duplicate of [#32899](https://github.com/ant-design/ant-design/issues/32899)

**Comment by afc163** [comment]
trace #32899
