### ISSUE TITLE
InputNumber验证问题

### ISSUE THREAD

**Issue by lslvxy** [ant-design/ant-design#3313]
输入的是number，但是验证不通过，提示` is not a number`

代码重现

[http://codepen.io/lslvxy/pen/NRyvaX?editors=1011](http://codepen.io/lslvxy/pen/NRyvaX?editors=1011)

InputNumber 或者Input type=‘number’ 都存在此问题

**Comment by afc163** [comment]
trigger 不用设置，或保持默认的 onChange 即可。

http://codepen.io/anon/pen/VKQzJp?editors=1011

**Comment by lslvxy** [comment]
我看官方文档上有`validate`配置项
```
 {getFieldDecorator('email', {
            validate: [{
              rules: [
                { required: true },
              ],
              trigger: 'onBlur',
            }, {
              rules: [
                { type: 'email', message: 'Please input the correct email' },
              ],
              trigger: ['onBlur', 'onChange'],
            }],
          })(
            <Input type="email" placeholder="This control uses onBlur and onChange" />
          )}
```

但是加上这个配置项，
又测试了下，不加`validate`配置项的话InputNumber组件是没问题的，可以验证，
但是 Input type=number 还是无法验证
`validate`配置 是不是不需要的，文档后面的API中没有这个配置项，但是实例代码中有

**Comment by benjycui** [comment]
配置应该是根据自己的业务决定，demo 只是用来展示功能。

**Comment by Midqiu** [comment]
还是有问题：
在 @afc163 给出的Demo中，修改年龄字段还是提示不正确。
但如果把第19行的`type:'number',`给删掉的话，输入的时候就能正确提示了，这里是不是处理type的时候有问题？


此外：
<Input type="number" />里面可以输入字母“e”，但不能输入其他字母。

**Comment by benjycui** [comment]
> 但如果把第19行的type:'number',给删掉的话，输入的时候就能正确提示了，这里是不是处理type的时候有问题？

`input[type=number]` 是 HTML5 新增的类型，在低版本浏览器相当于 `input[type=text]`，所以如果要兼容低版本浏览器，不建议使用 `type=number` 进行校验，而应该用正则。

> 里面可以输入字母“e”，但不能输入其他字母。

这个是原生 `input[type=number]` 的行为吧。。

**Comment by ddcat1115** [comment]
InputNumber 没有问题，Input 的问题参考这里的回复：

https://github.com/ant-design/ant-design/issues/3300#issuecomment-253196126
