### ISSUE TITLE
升级2.0版本后getValueFromEvent废弃了么？

### ISSUE THREAD

**Issue by PeteLuo** [ant-design/ant-design#3314]
#### 发生问题的环境是：

- antd 版本:v2.0.1
- 操作系统及其版本:win7 64
- 浏览器及其版本:chrome52

#### 您做了什么？
在表单使用一个DatePicker组件，并且使用了getValueFormEvent设置

#### 您期待的结果是：
正常显示

#### 实际上的结果是：
升级到版本2.0后报错，报错信息如下：
![image](https://cloud.githubusercontent.com/assets/18900661/19187582/cbc80b0a-8cbe-11e6-8d40-b830fc8193db.png)

#### 可重现的在线演示
http://codepen.io/PeteLuo/pen/VKQAmV?editors=0010

**Comment by benjycui** [comment]
没废弃，真正的问题在于 DatePicker 之类的时间组件现在只支持 `moment` 类型，你返回一个 `string` 必然是会报错的。

**Comment by PeteLuo** [comment]
解决办法是在handleSubmit针对Moment格式的信息进行format么？感觉以前的返回string的挺好用的@benjycui

**Comment by benjycui** [comment]
> 解决办法是在handleSubmit针对Moment格式的信息进行format么

是。

**Comment by djllhs** [comment]
` getFieldDecorator('reportDate', {
                                    getValueFromEvent: (value, dateString) => {
                                        return moment(dateString, "YYYY-MM-DD")
                                    },
                                    rules: [
                                        {required: true, message: '请选择一个日期'},
                                    ],
                                })(
                                    <DatePicker format="YYYY-MM-DD" style={{ width: 'inherit'}} name="reportDate"/>
                                )`
