### ISSUE TITLE
Upload上传文件后 预览有一串html代码

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design#33149]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/skb3i?file=/package.json:382-389)

### Steps to reproduce
上面链接是antd官方示例，也有这个问题，Upload上传文件后 预览有一串html代码，Upload项上传一个excel

### What is expected?
怎么去掉hover出现的信息

### What is actually happening?
去不掉
https://user-images.githubusercontent.com/33312508/144560928-46c83fe8-8904-4c1a-9519-ac829b764480.png

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16.14.0 |
| System | == |
| Browser | chrome |

---
Upload hover信息如下：
<html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx/1.16.1</center> </body> </html>

**Comment by afc163** [comment]
这是读的 file.response ，因为示例里的 mock api 不支持定制这个内容。

业务中可以用这个字段访问你想显示的内容：https://ant.design/components/upload-cn/#components-upload-demo-upload-custom-action-icon

**Comment by xiaoshui222** [comment]
> 这是读的 file.response ，因为示例里的 mock api 不支持定制这个内容。
> 
> 业务中可以用这个字段访问你想显示的内容：https://ant.design/components/upload-cn/#components-upload-demo-upload-custom-action-icon

我是上传excel，不需要hover信息，怎么把这个hover内容去掉 showUploadList不行吧

**Comment by xiaoshui222** [comment]
咋直接closed了？ 我现在发还能看到吗

**Comment by afc163** [comment]
请在服务端设置好 file.response，如果做不到，可以在 onChange 里把 file.response 覆写掉。
