### ISSUE TITLE
Upload组件使用阿里云 OSS 上传文件进度条会从0直接过渡到100%

### ISSUE THREAD

**Issue by mengtiantang** [ant-design/ant-design#33143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gb90g)

### Steps to reproduce
点击上传选择大点的文件，上传进度不是实时的

### What is expected?
文件上传进度是正确的

### What is actually happening?
文件上传完成时进度条直接从0到100

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | window10 |
| Browser | chrome |

**Comment by afc163** [comment]
可以参考 https://www.jianshu.com/p/1ea2e5964b10 和 https://github.com/ant-design/ant-design/issues/15546 和 https://juejin.cn/post/6899748543834259470 和 https://www.crazyming.com/note/2306/ 和 https://www.cxyzjd.com/article/qq_40593656/112555287

**Comment by mengtiantang** [comment]
不需要自定义请求了，找到解决办法了。
![image](https://user-images.githubusercontent.com/25972399/144577849-cd5fc800-bfc9-4f6f-a3b4-8e1f05b7a1df.png)
需要加format，percent设置默认值，上传时进度条才会实时变化，不然会等上传完成。接口出现状态响应，进度条会从开始直接过渡到结束

**Comment by afc163** [comment]
来个 PR？
