### ISSUE TITLE
Dropdown 菜单中使用 Modal   Input 时，input 中的光标无法通过键盘方向键移动

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design#33142]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-17-2-forked-jicrv)

### Steps to reproduce
点击菜单，输入文本，使用键盘移动光标

### What is expected?
使用键盘可移动光标

### What is actually happening?
使用键盘无法移动光标

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | react@16.14.0 |
| System | window10 |
| Browser | chrome  96.0.4664.45（正式版本） （64 位） |

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-antd-4-17-2-forked-d2s4p?file=/index.js

**Comment by echoyl** [comment]
> https://codesandbox.io/s/ji-ben-antd-4-17-2-forked-d2s4p?file=/index.js

按照这个方法嵌套一层div后 键盘可以移动了
为啥只在dropdown 的items中点击弹层后 才会使方向键盘建失效？antd版本5.12

**Comment by afc163** [comment]
```diff
      <Modal
        title="Basic Modal"
        visible={isModalVisible}
        onOk={handleOk}
        onCancel={handleCancel}
      >
        <div
+         onKeyDown={(e) => {
+           e.stopPropagation();
+         }}
        >
          <Input />
        </div>
      </Modal>
```

通过包括一层 div 并阻止 Modal 内的键盘交互冒泡到 Dropdown 上面，从而避免被 Dropdown 内的快键键逻辑监听到。比如 Dropdown 监听了上下左右用于多级菜单之间的键盘导航。
