### ISSUE TITLE
Typing a valid date into DateField then clicking elsewhere reverts date to previous value

### ISSUE THREAD

**Issue by jasongi-alliance** [ant-design/ant-design#33155]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3g1gn)

### Steps to reproduce
Type "2021-01-01" in the DatePicker and then CLICK anywhere else on the page

### What is expected?
It should keep the value you entered - this is what it does when you tab out of the field or press enter.

### What is actually happening?
It reverts to the last value in the box

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17 |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
It is by designed.
