### ISSUE TITLE
Cascader的onChange ts类型错误

### ISSUE THREAD

**Issue by 1123612483** [ant-design/ant-design#33153]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/whswt?file=/index.js)

### Steps to reproduce
`multiple`设为true，查看`onChange`的类型。
不设置`multiple`或者`multiple`设置为false，查看`onChange`的类型。

### What is expected?
`multiple`不设置或者`multiple`设置为false，`onChange`的类型为rc-cascader的`onSingleChange`类型。
`multiple`设置为true，`onChange`的类型为rc-cascader的`onMultipleChange`类型。

### What is actually happening?
无论`multiple`怎么设置，`onChange`始终为`onSingleChange | onMultiple`，需要`as`断言。

![image](https://user-images.githubusercontent.com/20741541/144573031-a00a1375-e95e-453c-a885-7f813b3b7d95.png)

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | Win10 |
| Browser | Chrome 96.0.4664.45 |

**Comment by ZzGGitter** [comment]
@afc163 close it?
