### ISSUE TITLE
Transfer组件有没有考虑过更新成hooks ts的版本

### ISSUE THREAD

**Issue by ziwosan** [ant-design/ant-design#33158]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在react基本上都是拥抱hooks进行开发,更改为hooks方式可以直接使用

### What does the proposed API look like?
使用hooks ts方式重写Transfer组件

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/projects/6

PR is welcome~
