### ISSUE TITLE
npm start 失败

### ISSUE THREAD

**Issue by fzypzl** [ant-design/ant-design#3315]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:win10 64位
- 浏览器及其版本:所有浏览器

#### 您做了什么？
用dva new project后，进入project目录，npm start

#### 实际上的结果是：
无法启动
err with request:Error:socket hang up /
err with request Error:socket hang up /favicon.ico
http://localhost:8989/空白

**Comment by afc163** [comment]
建议到 http://github.com/dvajs/dva-cli 提问，会获得更有效的帮助。
