### ISSUE TITLE
合并表头 且 有纵向滚动条 会有空隙 问题

### ISSUE THREAD

**Issue by dadazhouRenee** [ant-design/ant-design#33154]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/he-bing-biao-tou-gun-dong-tiao-antd-4-17-0-forked-xib64?file=/index.js)

### Steps to reproduce
1. 合并表头
2. 最右侧的单元格的边框会有空隙

### What is expected?
请问有空隙是属于正常的情况吗
希望没有空隙
### What is actually happening?
有空隙
![image](https://user-images.githubusercontent.com/31841446/144575843-01c57095-692a-4ddb-9ed2-430eb1055c8a.png)

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome |

---
尝试将`ant-table-cell ant-table-cell-scrollbar`元素 `visibility: hidden`但是上方的有一段边框控制不了
![1638522490(1)](https://user-images.githubusercontent.com/31841446/144576165-3667406c-89a8-4904-b9b1-996a34a3e1ab.png)

**Comment by afc163** [comment]
这已经是目前能实现最合适的方案了 https://github.com/ant-design/ant-design/issues/4637#issuecomment-498568464
