### ISSUE TITLE
Overriding less variables with craco crashes the app.

### ISSUE THREAD

**Issue by Terminatt** [ant-design/ant-design#33168]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Terminatt/antd-ovverride-bug](https://github.com/Terminatt/antd-ovverride-bug)

### Steps to reproduce
I believe it may have something to do with CLRF on Windows
1. Add some variables in modifyVars in CracoLessPlugin less options.
2. Run `npm start`

### What is expected?
The application should not crash

### What is actually happening?
The application crashes with this error
```
./src/App.less (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-8-3!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-8-4!./src/App.less)
Error: resolve-url-loader: CSS error
  file://D:/web/praca_licencjacka/praca/front/node_modules/antd/lib/style/core/global.less:212:2: Double colon
You tried to parse Less with the standard CSS parser; try again with the postcss-less parser
  You tried to parse Less with the standard CSS parser; try again with the postcss-less parser
```

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 96.0.4664.45 |

---
It works fine if I am overriding the variables in .less file

**Comment by amish-patel** [comment]
`'@border-color-base:': '#C9CAD9',` - remove the extra colon after `base` - https://github.com/Terminatt/antd-ovverride-bug/blob/main/craco.config.js#L20  - That should fix it I think

**Comment by afc163** [comment]
```diff
- '@border-color-base:': '#C9CAD9',
+ '@border-color-base': '#C9CAD9',
```
