### ISSUE TITLE
upload图片卡片样式 上传成功后 图片预览图会往下增加外边距

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#3316]
1.样式有点吃藕，然后点击事件是绑定在upload跟+号上面了？应该是整个框点击都应该有效吧
![image](https://cloud.githubusercontent.com/assets/7693866/19191555/9960369e-8cd5-11e6-9c13-9189916410e3.png)

2点击上传成功后 会有个预览，然后会神奇的往下多个外边距

**Comment by benjycui** [comment]
> 点击上传成功后 会有个预览，然后会神奇的往下多个外边距

不懂，麻烦详细描述。

**Comment by benjycui** [comment]
> 样式有点吃藕，然后点击事件是绑定在upload跟+号上面了？应该是整个框点击都应该有效吧

这个是得把中间的 `span` 搞大点。。
