### ISSUE TITLE
Dropdown希望触底后可以自动识别方向

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design#33169]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这样就不用去滚动滚动条了

![image](https://user-images.githubusercontent.com/12706830/144752262-10ec1f6c-f877-466f-b2f5-30b54337a94a.png)

### What does the proposed API look like?
可以加个参数自动识别方向

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16046#issuecomment-482466445
