### ISSUE TITLE
TreeSelect onSearch的问题。

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#33161]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-17-2-forked-o8oc4?file=/index.js)

### Steps to reproduce
使用onSearch后，onChange, onSelect 就不起作用了。而且按下回车确认后所得的值并不是显示的值。

### What is expected?
使用onSearch后，onChange, onSelect 起作用。按下回车确认后所得的值是显示的值。

### What is actually happening?
使用onSearch后，onChange, onSelect 就不起作用了。而且按下回车确认后所得的值并不是显示的值。

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16.14.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by afc163** [comment]
> 使用onSearch后，onChange, onSelect 就不起作用了

貌似没有问题。

> 而且按下回车确认后所得的值并不是显示的值

这个确实有问题，按下回车后选中的是原始值的第一个。

**Comment by meseme** [comment]
> > 使用onSearch后，onChange, onSelect 就不起作用了
> 
> 貌似没有问题。
> 
> > 而且按下回车确认后所得的值并不是显示的值
> 
> 这个确实有问题，按下回车后选中的是原始值的第一个。

感谢！第一个问题确实是我的粗心（拼写错误）。第二个，感觉问题好像出现在高亮条和选中值上，即选中了值但高亮条还是在默认位置，如果能控制高亮条就完美了。

**Comment by MadCcc** [comment]
Trace https://github.com/ant-design/ant-design/issues/34029
