### ISSUE TITLE
Tree - collapse ALL

### ISSUE THREAD

**Issue by JohannesNylund** [ant-design/ant-design#33177]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If you have many levels that needs to be collapsed its very time consuming for the user. Allowing a "collapse all" button for tree views lets the user more quickly browse trees with a big heirarchy. Clicking the "collapse all" could collapse ALL levels of the tree, including children, grandchildren, etc. This saves alot of time when browing complex trees with many child objects

### What does the proposed API look like?
I don't have any proposed solution for how to implement this.

**Comment by afc163** [comment]
Try control `expandedKeys`
