### ISSUE TITLE
Failed to resolve import "antd/es/col/style/index.less"

### ISSUE THREAD

**Issue by nos-nart** [ant-design/ant-design#33170]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nos-nart/nos-react-vite-ts](https://github.com/nos-nart/nos-react-vite-ts)

### Steps to reproduce
- yarn install
- yarn dev

### What is expected?
Able to use Col component as we imported

### What is actually happening?
[plugin:vite:import-analysis] Failed to resolve import "antd/es/row/style/index.less" from "src\pages\CounterPage.tsx". Does the file exist?

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | Windows 10 Pro 19043.1348 |
| Browser | Chome 96.0.4664.45 -  Node v16.13.0 |

---
I'm using `vite` by adding package `vite-plugin-imp` and config to use antd  like below
```js
vitePluginImp({
   libList: [
      {
         libName: 'antd',
         style: (name) => `antd/es/${name}/style/index.less`,
      },
   ],
 }),
```
I inspect the **node_modules/antd/es** folder, inside each style folder of others component have **index.less** file except col and row.

**Comment by nos-nart** [comment]
![antd](https://user-images.githubusercontent.com/37862200/144757355-c0cbc4f6-d642-470f-bebb-88bf16cb71ad.png)

**Comment by afc163** [comment]
Don't use `vitePluginImp`, please import `antd/dist/antd.less` instead.

**Comment by theprimone** [comment]
> Don't use `vitePluginImp`, please import `antd/dist/antd.less` instead.

Not exactly, you can try:

```ts
import vitePluginImp from 'vite-plugin-imp';

export default defineConfig({
  plugins: [
    vitePluginImp({
      libList: [
        {
          libName: 'antd',
          style: (name) => `antd/es/${name}/style`,
        },
      ],
    }),
  ],
  css: {
    preprocessorOptions: {
      less: {
        // modifyVars: { 'primary-color': '#13c2c2' },
        javascriptEnabled: true,
      },
    },
  },
});
```

more over: https://github.com/ant-design/ant-design/discussions/29660
