### ISSUE TITLE
upload的onRemove这个钩子应该怎么使用，为什么我写东西会覆盖掉原有的事件？

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#3317]
如题 onRemove={()=>{//do something}}  会把原有的事件覆盖掉 那如何既保持原有的事件又运行一些我自己的逻辑呢？

还有一个小问题
![image](https://cloud.githubusercontent.com/assets/7693866/19196637/e3c86b8a-8ce8-11e6-98e2-96437e4249b6.png)
我想关闭弹窗同时把upload的预览图也关掉，能不能做到？

**Comment by benjycui** [comment]
看不懂。。。不要假设我们对你们的业务场景有所了解。

提供的信息越详细越好。

**Comment by ouzhou** [comment]
是这样的 Upload的文档里面只是说了onRemove这个是一个钩子，我以为是点击预览那个叉叉，就会去调用onRemove里面的逻辑，（确实是这样的）但是我发现我写的逻辑会把原生的取消预览的功能覆盖掉了，那这个onRemove好像就没有什么作用了啊。  还有 如何去trigger 触发onRemove事件呢？

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/commit/d584b20dd89aca1568cac69417f8972960e17f46

@joesonw 这样设计的原因是？

**Comment by joesonw** [comment]
@benjycui 当初添加这个的时候, 想的是可以让使用者决定点击之后发生什么事情, 例如弹出`PopConfirm`, 确认后, 改变`fileList`的state达到删除的目的.
@ouzhou 原生的取消预览, 是指移除文件吗?

**Comment by afc163** [comment]
现在的确实有问题。应该是指定了 `fileList` 时，才不去调用正常的 remove 逻辑。

**Comment by ouzhou** [comment]
@joesonw 是的， 移除文件，  
而且我感觉 upload 这个组件跟表单校验的配合不太好，我的实现方式是写了一个隐藏的input，把upload的校验放到校验这个input是否传入值
希望提供一个trigger 触发移除文件事件

**Comment by wangyazhen** [comment]
@joesonw `点击删除的时候 弹出PopConfirm`  这个应该怎么来实现 
我想要这样的效果-- >


![upload-pop](https://user-images.githubusercontent.com/5687531/27170593-0b68463e-51e1-11e7-85db-eb27ae747e55.png)

没有研究出来以上效果， 目前采用`Modal.confirm`的方式  -_-
