### ISSUE TITLE
<AutoComplete> Overrides Child <Input> type

### ISSUE THREAD

**Issue by WilliamPriorielloGarda** [ant-design/ant-design#33180]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-grass-lwgql?file=/src/App.js)

### Steps to reproduce
There are two Input fields and I set type="email" for BOTH input fields.
Use Chrome Inspector tool on both input fields. 

### What is expected?
Both html input fields should have type='email' in chrome inspector

### What is actually happening?
In case 1, where we wrap the Input in an AutoComplete, the input type has been overwritten to type="search".
In case 2, where we do not wrap the Input, it is working as expected (the type="email").

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | Not Sure |
| Browser | Chrome 96.0.4664.45 (Official Build) (64-bit) |

**Comment by ZZITE** [comment]
The `RcSelect` will overrides your Input Element by `React.cloneElement`
[You can see it here](https://github.com/react-component/select/blob/a77be9b456c94a8c13bf6ea1986fbd2ebd8b0c9e/src/Selector/Input.tsx)
