### ISSUE TITLE
Cascader - Warning: Encountered two children with the same key, 'seperator'

### ISSUE THREAD

**Issue by dimbslmh** [ant-design/ant-design#33183]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-swme3)

### Steps to reproduce
Use the search box to search for "o". Open Console to see errors.

### What is expected?
No errors.

### What is actually happening?
Warning: Encountered two children with the same key, 'seperator'. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | Manjaro Linux 5.23.3 |
| Browser | Chromium Version 96.0.4664.45 (Official Build) snap (64-bit) |

**Comment by dimbslmh** [comment]
https://github.com/ant-design/ant-design/blob/d4b4edf8efdb4ef5544a36ccb5c855574c189d69/components/cascader/index.tsx#L43

**Comment by dimbslmh** [comment]
@afc163 thank you

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/33649
