### ISSUE TITLE
Use `class-validator` as form rules

### ISSUE THREAD

**Issue by michal-miler** [ant-design/ant-design#33197]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have created a DTO object in API with class-validator:

```
export class CreateItemDto {
  @IsString()
  @Length(2, 63)
  readonly name: string;
}
```

It would be great if I could use the DTO in Form as following.

```
const [form] = Form.useForm<CreateItemDto>();
```

Currently I have to specify rules on my own:

```
<Form form={form}>
  <Form.Item
    label="Name"
    name="name"
    rules={[{
      required: true,
      message: t('Please enter correct name'),
      min: 2,
      max: 63,
    }]}
  >
    <Input />
  </Form.Item>
</Form>
```

### What does the proposed API look like?
as above

**Comment by afc163** [comment]
You can create a upper form comoponent for this feature.
