### ISSUE TITLE
Table - Components API not working

### ISSUE THREAD

**Issue by simo54** [ant-design/ant-design#33194]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-17-2-forked-wv7pj?file=/index.js)

### Steps to reproduce
- Import Table
- Insert components API
- Setup custom row for the table

### What is expected?
In the example I expect that row becomes an Accordion along all the columns with data

### What is actually happening?
The custom component stops only on the first column and no data is shown

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome |

---
https://ant.design/components/table/#API - no more additional comments provided

**Comment by afc163** [comment]
https://codesandbox.io/s/j8qk3?file=/index.js
