### ISSUE TITLE
Feature: Dragger 支持上传单张图片，上传后在原位置显示缩略图。

### ISSUE THREAD

**Issue by sandwich99** [ant-design/ant-design#3319]
感觉 Dragger 支持上传单张图片，上传后在原位置显示缩略图 应该是一个很常见的场景, 不知道为什么 Upload 组件还没有支持.

**Comment by afc163** [comment]
并没有人手支持，而且我们目前没有类似的需求。有强烈需求的话，建议直接给我们 PR~

**Comment by benjycui** [comment]
业务上碰到这种场景了。。

**Comment by benjycui** [comment]
P.S. 这种场景的另外一个变式是上传前先裁剪，然后再上传，这个需求应该可以结合 `beforeUpload` 实现。

**Comment by benjycui** [comment]
增加了一个 demo。
