### ISSUE TITLE
the autoSize property of Input.TextArea  not support dynamic modify (Textarea 的 autoSize 不支持动态修改)

### ISSUE THREAD

**Issue by renyuns** [ant-design/ant-design#33202]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-xotk4v?file=index.js](https://stackblitz.com/edit/react-xotk4v?file=index.js)

### Steps to reproduce
main code (主要代码)
```
  const [autoSize, setAutoSize] = useState({ minRows: 3, maxRows: 8 });
  const handlePlus1 = useCallback(() => {
    setAutoSize({ minRows: 3, maxRows: 15 });
  }, []);

 <TextArea
      placeholder="test2"
      value={value}
      autoSize={autoSize}
      onChange={handleChage}
 />
```

### What is expected?
Expect the modified autosize property to take effect (期望修改后的 autoSize 属性生效)

### What is actually happening?
The modified autosize property does not take effect (修改后的 autoSize 属性不生效)

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | macOS Big Sur 11.0.1 |
| Browser | 96.0.4664.55 |

---
使用 TextArea, 根据网页窗口高度来动态修改 autoSize 的 maxRows 进行高度适配

**Comment by hydraZty** [comment]
在 TextArea 上加个动态 key
```
<TextArea
  placeholder="test2"
  value={value}
  key={maxRows}
  autoSize={{
    minRows,
    maxRows,
  }}
  onChange={handleChage}
/>
```

**Comment by losgif** [comment]
I'd like to support it. @afc163
