### ISSUE TITLE
Table  不能显示boolean类型值

### ISSUE THREAD

**Issue by x6988312** [ant-design/ant-design#33208]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5ym8r?file=/index.js)

### Steps to reproduce
直接拿官网的Table组件的第一个例子，下载下来或者在codesandbox中运行，把data中的任一个属性改true或false，就能重现。true或false在Table中对应的单元格中显示为空白.

### What is expected?
如果是bug，则尽快修一下

### What is actually happening?
boolean类型在Table显示为空白

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | react 17.0.2 |
| System | windows 10 |
| Browser | edge |

**Comment by afc163** [comment]
这是 React 的渲染逻辑，你可以测试一下直接渲染 `<div>{true}</div>` 和 `<div>{false}</div>`

**Comment by kaocong** [comment]
1231
