### ISSUE TITLE
tag dark mode

### ISSUE THREAD

**Issue by s77rt** [ant-design/ant-design#33219]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tag/?theme=dark](https://ant.design/components/tag/?theme=dark)

### Steps to reproduce
scroll down to status tag and make sure the theme is dark

### What is expected?
tags to be dark mode compatible

### What is actually happening?
they are not. the background is light...

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Linux |
| Browser | Chrome |

---
This issue started with 4.17.0.
Tested with 4.16.13 and works fine

**Comment by PeachScript** [comment]
demo with 4.16.13: https://codesandbox.io/s/status-tag-antd-4-17-3-forked-7tzkf?file=/index.js

**Comment by afc163** [comment]
@zombieJ 需要一个调试 dark theme 的方式。
