### ISSUE TITLE
Ant Design Table Component - column search input not resetting after clicking the reset button

### ISSUE THREAD

**Issue by alexeidinca-ro** [ant-design/ant-design#33215]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/antd-reproduction-template-forked-jmr47?file=/userTable.js

### Steps to reproduce
1. Use antd Table Component 2. Create a table with search feature using filterDropdown 3. Populate table with data 4. Type the desired text to be searched 5. Click to search 6. Go back to search dropdown and click the reset button

### What is expected?
Reset the input text in the search dropdown

### What is actually happening?
Implementing the column search feature using filtreDropdown, when you click the RESET button in the search dropdown, the search input is cleared, but when you reopen the dropdown the text searched is still there.

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by alexeidinca-ro** [comment]
@afc163 Update: Reproduction link > https://codesandbox.io/s/antd-reproduction-template-forked-jmr47?file=/userTable.js

**Comment by afc163** [comment]
It is intented change in https://ant.design/changelog-cn#4.17.0, please check https://github.com/ant-design/ant-design/pull/31809
