### ISSUE TITLE
Button with icon and the content vertical-align issue

### ISSUE THREAD

**Issue by obilous** [ant-design/ant-design#33216]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-vertical-icon-align-2hb3y)

### Steps to reproduce
Visit the link and preview the code.

### What is expected?
Icon should be vertical align with the content in buttons.

### What is actually happening?
Icon and the content are not vertical align in buttons

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Code sandbox. |
| Browser | Version 95.0.4638.69 (Official Build) (64-bit) |

---
Since antd offers to use fontawesome as recommendation, we would like to see vertical align icon with the content in buttons.

**Comment by afc163** [comment]
Try https://codesandbox.io/s/antd-vertical-icon-align-forked-s540gt?file=/src/App.js
