### ISSUE TITLE
antd Select嵌套DataPicker组件,能选中天/一点击上一年 上一个月 Select组件就消失了 无法选择

### ISSUE THREAD

**Issue by git997-small** [ant-design/ant-design#33217]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://react-t5rnkv.stackblitz.io/](https://react-t5rnkv.stackblitz.io/)

### Steps to reproduce
antd Select嵌套DataPicker组件,能选中天/一点击上一年 上一个月 Select组件就消失了 无法选择

### What is expected?
期望：选择年月日之后再消失

### What is actually happening?
能选中天/一点击上一年 上一个月 Select组件就消失了 无法选择

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | react 16.8 |
| System | win10 64 |
| Browser | chrome 96 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E7%82%B9%E5%87%BB-Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E5%86%85%E7%9A%84%E5%8F%A6%E4%B8%80%E4%B8%AA-popup-%E7%BB%84%E4%BB%B6%E6%97%B6%E5%AE%83%E4%BC%9A%E6%B6%88%E5%A4%B1%EF%BC%8C%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F

**Comment by xgqfrms** [comment]
# typo: <del>Popconfirm</del> => <key>PopConfirm</key>

https://github.com/ant-design/ant-design/blob/master/components/popconfirm/index.tsx

**Comment by git997-small** [comment]
> https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E7%82%B9%E5%87%BB-Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E5%86%85%E7%9A%84%E5%8F%A6%E4%B8%80%E4%B8%AA-popup-%E7%BB%84%E4%BB%B6%E6%97%B6%E5%AE%83%E4%BC%9A%E6%B6%88%E5%A4%B1%EF%BC%8C%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F

![image](https://user-images.githubusercontent.com/79562689/145776670-173193b9-cfd6-460f-983d-309b872c104b.png)
麻烦看一下 样式还是有问题

**Comment by git997-small** [comment]
@afc163
