### ISSUE TITLE
beforeUpload参数问题

### ISSUE THREAD

**Issue by azl397985856** [ant-design/ant-design#3321]
使用antd版本1.2.0    操作系统win7
如下使用ant upload 组件的 beforeUpload 接口 参数file 特定情况下type为空字符串。
重现过程：  上传一个后缀为xls或者xlsx的excel文件。（目前我的电脑无法重现，客户电脑可以重现，所以我想知道type为空可能是什么问题）

import { Upload, Button, Icon, message } from 'antd';

const props = {
  action: '/upload.do',
  multiple: true,
  beforeUpload(file) {
    const isJPG = file.type === 'image/jpeg';// 就是这个isJPG可能为""
    if (!isJPG) {
      message.error('you can only upload JPG file~');
    }
    return isJPG;
  },
};

ReactDOM.render(
  <Upload {...props}>
    <Button type="ghost">
      <Icon type="upload" /> upload
    </Button>
  </Upload>
, mountNode);

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by benjycui** [comment]
这个 file 是直接浏览器给的。

你试着联系客户获取更多信息吧，无法重现的话，我们也没办法处理。

**Comment by azl397985856** [comment]
好的~

**Comment by walking11** [comment]
mac 下 chrome浏览器重现了该问题，同样的代码safari没有该问题，window下也是正常的

**Comment by caowenkai** [comment]
遇到了同样的问题，在mac下面，打印出来type为空
onChange(info) {
    console.log(info)
}
