### ISSUE TITLE
Table rowClassName not wornking on fixed columns

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#33218]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/misty-bush-mcrt9?file=/index.js)

### Steps to reproduce
Select any row via click.

### What is expected?
Whole row to receive classname.

### What is actually happening?
The columns with fixed prop are not receiving className.

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | react: 17.0.2 |
| System | Windows 10 |
| Browser | Brave |

---
In this case, I am using the default example of rowSelection with click to achieve what I need.
Since Antd does not support removing the default checkbox or radio for rowSelection type. 
If that was possible i could just simply use the default controlled mode and hide the radio or checkbox.
Maybe the rowSelectionType should be remade to a new and more dynamic API, perhaps something like bellow:
```ts
   type rowSelectionType = 'multiple' | 'single' | 'none'
```
multiple = renders a checkbox on the first column like the default behaviour
single = renders a radio on the first column like the default behaviour
none = does not render a default first column and uses selection by clicking on the rows.

Just a sugestion, for now fixing this issue solves my problem.
Thanks.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31483#issuecomment-884847331
