### ISSUE TITLE
在 Table 里使用 Popover，数据比较少时高度没有 Popover 高时，使用 scroll，placement 没有到预期的位置且会显示不全

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#33227]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-17-3-forked-0c24x)

### Steps to reproduce
1、点击弹出框
2、滚动表格

### What is expected?
能显示到想要的位置，且显示完全

### What is actually happening?
位置不对，且没有显示完全，因为 scroll 的原因，表格 overflow。我知道是因为空间不够显示了，所以会显示到这个位置。

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | lastest |
| System | mac |
| Browser | chrome |

---
1、如果不用 getPopupContainer，都可以，但是不会跟随表格滚动而滚动。
2、如果想要跟随表格而滚动，就会出现位置不是想要的，客户看着很不舒服

有没有比较好的解决方案？

**Comment by afc163** [comment]
目前没有完美的解决方案，只能业务上取舍。
