### ISSUE TITLE
希望改进RangePicker的禁用日期

### ISSUE THREAD

**Issue by peakandyuri** [ant-design/ant-design#33237]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我看了官网API的例子，对于RangePicker，如果要禁用结束日期的区间，需要额外定义一个变量来标识，这种方式能满足部分场景。但是如果我开始时间要小于当天，结束时间必须要大于当天。按照官网的例子在使用上总是会存在点问题，根据曝露出来的回调事件无法完美的标记的当前的日期面板处于什么样的状态，当前是设置起始时间还是结束时间无法正确判断

### What does the proposed API look like?
增加一个参数
disableDate(current, type){
      //type为start或end
      return current < dayjs();
}

**Comment by FloaJa** [comment]
发现一个方法可以暂时解决问题, 通过监听起止期Input框获取焦点事件, 使用不同的禁用
```javascript
const [currentFocus, setCurrentFocus] = useState<'start' | 'end' | null>(null);

  const startFocus = useCallback(() => {
    console.log('起期获得焦点');
    setCurrentFocus('start');
  }, []);
  const endFocus = useCallback(() => {
    console.log('止期获得焦点');
    setCurrentFocus('end');
  }, []);

  useEffect(() => {
    const input = document.getElementsByClassName('rangePicker')[0].getElementsByTagName('input');
    const startEle = input[0];
    const endEle = input[1];
    startEle?.addEventListener('focus', startFocus);
    endEle?.addEventListener('focus', endFocus);
    return () => {
      startEle.removeEventListener('focus', startFocus);
      startEle.removeEventListener('focus', endFocus);
    };
  }, []);

  const disabledDate = (current: Moment) => {
    if (currentFocus === 'start') {
      return current && current > moment().startOf('day');
    }
    return false;
  };
```

**Comment by FloaJa** [comment]
顺便报个BUG, RangePicker传入的`id`会被传到起期的input元素上, 而不是外层的div @afc163

**Comment by afc163** [comment]
Duplicate of #33236
