### ISSUE TITLE
The tooltip of a button (with an icon) in a tab remains displayed when changing tabs

### ISSUE THREAD

**Issue by vincentv** [ant-design/ant-design#33239]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-fogb5e?file=index.js](https://stackblitz.com/edit/react-fogb5e?file=index.js)

### Steps to reproduce
* Hover over a button (tab 2 or tab3) to display the tooltip
* Click on the button icon
* Stay on the button until the tab is changed

### What is expected?
the tooltip should disappear after the tab change

### What is actually happening?
the tooltip of the button remains displayed above the new tab although the button is no longer visible

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Arch Linux x86_64 (5.13.13-zen1-1-zen) |
| Browser | firefox-developer-edition 95.0b12 |

---
In a Tabs.TabPane, we have a button with an icon that opens another tab. The "loadings" property of this button is used to indicate the loading of the tab data to be opened. 
When the icon is clicked, the button wheel appears, then the tab is changed but the button's tooltip remains displayed above the new tab, although the button is no longer visible.

**Comment by afc163** [comment]
Try `destroyInactiveTabPane`

**Comment by vincentv** [comment]
> Try `destroyInactiveTabPane`

Thanks, that's a good idea. Like execute `sudo rm -rf /*` when you run out of disk space.

more seriously, with `destroyInactiveTabPane` you lose the state of the tab content, it's not a solution, it's a misery cache

**Comment by vincentv** [comment]
> Try `destroyInactiveTabPane`

Thanks, that's a good idea. Like execute `sudo rm -rf /*` when you run out of disk space.

more seriously, with `destroyInactiveTabPane` you lose the state of the tab content, it's not a solution,
