### ISSUE TITLE
Tabs是否可以提供在onChange之前的拦截

### ISSUE THREAD

**Issue by shenzhigang** [ant-design/ant-design#3323]
比如说，在切换Tabs前当前Tab编辑内容未保存，需要提示是否真的要切换。
版本:1.11

**Comment by afc163** [comment]
受控模式 activeKey + onChange 自行拦截。

**Comment by lydiafork** [comment]
请问解决了 (ノへ￣、)捂脸  刚好也碰到这个问题 ，没有头绪
