### ISSUE TITLE
希望改进时间面板的禁用时间区间

### ISSUE THREAD

**Issue by peakandyuri** [ant-design/ant-design#33236]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前是禁用时/分/秒的区间，对于需要禁用固定的区间比较方便，但是对于动态时间范围，判断就很麻烦，比如说只禁用某个（当前）时间之前或之后的时间；或者是禁用4点半之前的时间，当选择小时为5的时候，分和秒就不应该被禁用。

### What does the proposed API look like?
希望像支持date方式一样直接返回一个true和false，或者再新增一个禁用时间的API
disableTime(current){
      return current < dayjs();
}

**Comment by zombieJ** [comment]
现在已支持额外参数判断：https://ant-design.antgroup.com/components/time-picker-cn#disabledtime
