### ISSUE TITLE
Table使用 react-sortable-hoc 实现拖拽的同时设置expandable，列展开后无法被收起

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#33231]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuo-zhuai-shou-bing-lie-antd-4-17-2-forked-52584)

### Steps to reproduce
1. 点击 展开按钮
2. 点击-收起，但无法被收起

### What is expected?
能正常展开和收起

### What is actually happening?
行展开后无法被收起
![GIF 2021-12-9 16-11-01](https://user-images.githubusercontent.com/6482819/145358732-becaac89-c2cb-429d-ac6e-05a7db7c089b.gif)

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16.14.0 |
| System | windows 10 19044.1348 |
| Browser | chrome 96.0.4664.45 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29279#issuecomment-810102061
