### ISSUE TITLE
Modal.confirm使用 getContainer参数为 false 时，无法使用

### ISSUE THREAD

**Issue by ewqazxc** [ant-design/ant-design#33249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-confirm-getcontainer-antd-4-17-3-forked-0jyk6?file=/index.js:1086-1105)

### Steps to reproduce
1. 重现连接里是 getContainer: false 时，按官网文档  false 为挂载在当前 dom，实际无效
2. 官网文档，里的Modal 在QQ浏览器里，没一个能正常点开的，直接卡死， https://ant.design/components/modal-cn/#API

### What is expected?
正常弹出Modal

### What is actually happening?
报错卡死

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.1 |
| System | win10 |
| Browser | "5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3861.400 QQBrowser/10.7.4313.400" |

**Comment by afc163** [comment]
QQ浏览器内核锁在Chrome 70了，不再支持。

**Comment by ewqazxc** [comment]
> QQ浏览器内核锁在Chrome 70了，不再支持。

。。。标题是 getContainer参数为 false 时，无法使用，
示例在谷歌浏览器最新版也是不行的
https://codesandbox.io/s/modal-confirm-getcontainer-antd-4-17-3-forked-0jyk6?file=/index.js:1086-1105

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33359#issuecomment-997569927
