### ISSUE TITLE
使用vite2创建的react应用，配置了中文，date-picker组件月份和星期依旧是英文，配置的中文不生效

### ISSUE THREAD

**Issue by PeiXueYang** [ant-design/ant-design#33244]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://git.weixin.qq.com/PeiXueYang/vite-pro.git](https://git.weixin.qq.com/PeiXueYang/vite-pro.git)

### Steps to reproduce
import moment from 'moment'
import zhCN from 'antd/lib/locale/zh_CN'; // 引入中文包
import 'moment/locale/zh-cn';
moment.locale('zh-cn');

ReactDOM.render(
    < ConfigProvider locale={zhCN}>
        <Router>
            <App />
        </Router>
    </ConfigProvider>
    ,
    document.getElementById('root')
)
//具体组件使用
import locale from 'antd/lib/date-picker/locale/zh_CN';
  <DatePicker  locale={locale}/>
// 即使这样配置也不生效

### What is expected?
配置了中文后，组件语言能是中文

### What is actually happening?
配置了中文不生效

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.0 |
| System | macos 12.0.1 |
| Browser |  96.0.4664.93 |

**Comment by afc163** [comment]
你的重现不是公网可访问的仓库。

**Comment by PeiXueYang** [comment]
https://git.weixin.qq.com/PeiXueYang/vite-pro.git

**Comment by yoyo837** [comment]
> https://git.weixin.qq.com/PeiXueYang/vite-pro.git

https://github.com/ant-design/ant-design/issues/33244#issuecomment-990564523

**Comment by PeiXueYang** [comment]
https://github.com/PeiXueYang/my-vite

**Comment by PeiXueYang** [comment]
> 你的重现不是公网可访问的仓库。

https://github.com/PeiXueYang/my-vite

**Comment by PeiXueYang** [comment]
> > 你的重现不是公网可访问的仓库。
> 
> https://github.com/PeiXueYang/my-vite

这个是小demo地址     麻烦看下 ~

**Comment by muzea** [comment]
`rc-picker` 使用的是 `node_modules/moment/dist/moment.js`，项目里面使用的是 `node_modules/moment/moment.js`，导致展示了英文。

**Comment by muzea** [comment]
可以考虑使用 `import moment from "moment/dist/moment";` 事实。
`rc-picker` 中加载 `node_modules/moment/dist/moment.js` 是一个正常的行为，[按照 vite 的文档 ](node_modules/moment/dist/moment.js)，这里使用 `jsnext:main` 是一个正常的行为。

反而是项目里面的 `moment` 被解析到 `node_modules/moment/moment.js` 是不符合预期的，应该是 vite 的一个 bug。

**Comment by PeiXueYang** [comment]
> 按照 vite 的文档

好的，感谢，这样确实可以了 。 @muzea

**Comment by 1247748612** [comment]
vite加载的也是node_modules/moment/dist/moment.js
只要调整导入的locale文件即可
```typescript
// 无需改动
import moment from "moment";
// 引入dist下的locale
import "moment/dist/locale/zh-cn";
```

**Comment by zhangshichuan** [comment]
thx
