### ISSUE TITLE
步骤条 Steps 组件当 title 为空字符串时，显示异常

### ISSUE THREAD

**Issue by wanghui94** [ant-design/ant-design#33247]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qm0tm?file=/index.js)

### Steps to reproduce
第一个 step 显示样式异常

### What is expected?
description 的内容显示保持原样

### What is actually happening?
description 的内容显示移动到原来 title 的位置

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | react@17.0.2 |
| System | macOS 12.0.1 |
| Browser | Chrome 96.0.4664.93 |

**Comment by afc163** [comment]
想了一下，https://github.com/ant-design/ant-design/pull/33277 能解决这个问题，但是由于写死了 min-height，如果用户做了一些样式定制或者 title 内插入了其他内容，这样改会有影响。

另外默认样式下 description 是可省略的，title 是不应该省略的，这样做兼容比较 hack，也不好看。

因此还是不特别修改了。
