### ISSUE TITLE
The tooltip of a button remains displayed when the button is hidden by clicking on the icon and the loading property is used.

### ISSUE THREAD

**Issue by vincentv** [ant-design/ant-design#33242]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-fogb5e-vtqj3y?file=index.js](https://stackblitz.com/edit/react-fogb5e-vtqj3y?file=index.js)

### Steps to reproduce
* Hover the button to display the tooltip
* Click on the button icon

### What is expected?
the tooltip should disappear when the button is hidden

### What is actually happening?
the tooltip remains displayed

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Arch Linux x86_64 (5.15.6-zen2-1-zen) |
| Browser | firefox-developer-edition 95.0b12 and chromium 96 |

**Comment by hydraZty** [comment]
There is an attribute `visible` in Tooltips, You should probably use this attribute to make the Tooltip continuous display after the button is hidden. Because there may be opposite expected in the case of other users.

**Comment by vincentv** [comment]
> There is an attribute `visible` in Tooltips, You should probably use this attribute to make the Tooltip continuous display after the button is hidden. Because there may be opposite expected in the case of other users.

I think you misunderstood my ticket :relaxed:

**Comment by DaoxingHuang** [comment]
This bug should case by icon click ,that stop pop event.

**Comment by hydraZty** [comment]
> > There is an attribute `visible` in Tooltips, You should probably use this attribute to make the Tooltip continuous display after the button is hidden. Because there may be opposite expected in the case of other users.
> 
> I think you misunderstood my ticket ☺️


My fault, I missed the icon 😓

**Comment by afc163** [comment]
Fixed in antd 5.x: https://stackblitz.com/edit/react-fogb5e-8hr8ag?file=package.json
