### ISSUE TITLE
Typography.Paragraph 可否增加一个展开后可收起的功能

### ISSUE THREAD

**Issue by VanLee1212** [ant-design/ant-design#33246]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Paragraph 展开后可收起的功能，恢复到省略的状态

### What does the proposed API look like?
与展开类似

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20639#issuecomment-759251717

**Comment by VanLee1212** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by drdevelop** [comment]
@VanLee1212 you can try @typgraphy-org/react

**Comment by VanLee1212** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
