### ISSUE TITLE
Table的onFilter API 可以改进下，可以把values也传入

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#33248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义筛选数值区间段时，发现value 只是取values的第一个值，如果能传入values的话，就能更好的解决自定义筛选 数值区间段

### What does the proposed API look like?
 onFilter: (value, record,values) => {
            if (values[0] && values[0] <= record[dataIndex]) {
                return true;
            } else if (values[1] && values[1] >= record[dataIndex]) {
                return true;
            } else return false;
        },

**Comment by Catsbe** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()

**Comment by Catsbe** [comment]
![1](https://user-images.githubusercontent.com/25682800/145550635-5b8aa889-2b4d-4041-b353-16786b04445b.png)
![2](https://user-images.githubusercontent.com/25682800/145550640-2564614a-81e2-4ed1-a1ed-b2bfc239ddd2.png)
![3](https://user-images.githubusercontent.com/25682800/145550642-b59c1096-f2df-4e08-9cfe-06580a810747.png)

**Comment by Catsbe** [comment]
@afc163  这个小改动可以看看能不能实现嘛

**Comment by Simons-Maddy** [comment]
我觉得value是可以传入数组，但是onFilter是循环读取的。我也被这个困扰了很久，你这个拼接字符确实可以实现数值区间段的filter

**Comment by Simons-Maddy** [comment]
<img width="1000" alt="截屏2022-07-24 21 15 32" src="https://user-images.githubusercontent.com/84006231/180648715-54c85910-7941-4487-b7fb-9c69d78d28e9.png">
源代码里面是filterValues.map
