### ISSUE TITLE
Form Item中使用dependencies，在render children函数中使用了setFieldsValue，报错Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by naoxiaozhi** [ant-design/ant-design#33245]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-39lo6?file=/index.js)

### Steps to reproduce
在4.17.2中运行codesandbox中的代码，控制台会报错Maximum update depth exceeded；但是在4.16.3版本上述代码运行是正常的。

### What is expected?
期望是input1输入任何值，input2的值能联动变化。例如input1输入123，input2变成123test

### What is actually happening?
antd 4.16.3 运行正常；4.16.3之后更新的版本，有报错；

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 16.14.0 |
| System | MAC |
| Browser | Chrome 96.0.4664.55（正式版本） |

**Comment by afc163** [comment]
符合预期，这和 React 中 render 下不要调用 setState 是一样的道理。
