### ISSUE TITLE
Add the ability to disable tooltip/popover keyboard commands

### ISSUE THREAD

**Issue by JoeVanGundy** [ant-design/ant-design#33256]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have an Input component in a popover, and when the 'spacebar' is clicked, the popover is closed. It seems that `event.stopPropogation()` doesn't stop this from happening.

The Popover/Tooltip does handles everything perfectly, I just need a way to disable the spacebar from closing it.

### What does the proposed API look like?
Potentially add a prop to control what keys like "enter" and "spacebar" do.

**Comment by JoeVanGundy** [comment]
Here's the reproduction link: https://codesandbox.io/s/antd-reproduction-template-forked-w1jke?file=/PopoverForm.jsx

**Comment by afc163** [comment]
We cannot resolve this problem due to browser behavior: https://bugzilla.mozilla.org/show_bug.cgi?id=1552419

You can try this as workaround.

```jsx
- getPopupContainer={(triggerNode) => triggerNode}
+ getPopupContainer={(triggerNode) => triggerNode.parentNode}
```
