### ISSUE TITLE
Tree组件，异步获取值（treeData），defaultExpandAll（展开全部子集）属性无效

### ISSUE THREAD

**Issue by world56** [ant-design/ant-design#33255]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

###  重现链接
https://codesandbox.io/s/antd-reproduction-template-forked-7vb1e?file=/index.js:1166-1173

### Steps to reproduce
一：异步获取Tree组件的treeData 参数，然后setState。
二：defaultExpandAll属性（展开所有树节点），不能生效，节点的UI状态是全部闭合的。

### What is expected?
能否解决异步赋值，导致Tree组件 defaultExpandAll属性失效的问题。

### What is actually happening?
Tree组件，defaultExpandAll属性在异步赋值treeData状态下无效。

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Macos Monterey 12.0.1 |
| Browser | Google Chrome 96.0.4664.93（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
