### ISSUE TITLE
Tooltip 结合Select使用时，无法复制其中内容。同时点击会穿透。

### ISSUE THREAD

**Issue by thinkingc** [ant-design/ant-design#33250]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-4-tooltip-select-wu-fa-fu-zhi-tooltipnei-rong-ppmmn?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/antd-4-tooltip-select-wu-fa-fu-zhi-tooltipnei-rong-ppmmn?file=/index.js

### What is expected?
在结合Select组件使用时，希望能复制Tooltip内容。同时，点击Tooltip不要关闭Select下拉。

### What is actually happening?
不能复制Tooltip，点击Tooltip会关闭Select。

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 18 |
| System | mac |
| Browser | chrome 96 |

---
Tooltip结合Cascader组件使用会出现同样的问题。

**Comment by afc163** [comment]
Tooltip 放在 Option 内也保持 Option 的行为是合理的，这就是 Select 组件的预设行为。

如果一定要改，可以用这样的方式：https://codesandbox.io/s/antd-4-tooltip-select-wu-fa-fu-zhi-tooltipnei-rong-forked-5bnhl
