### ISSUE TITLE
theme.dark.less select background-color and border-color

### ISSUE THREAD

**Issue by wkylin** [ant-design/ant-design#33269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://wkylin.github.io/promotion-web/#/basis](https://wkylin.github.io/promotion-web/#/basis)

### Steps to reproduce
https://wkylin.github.io/promotion-web/#/basis

### What is expected?
完美展示

### What is actually happening?
背景色是白色的，无法展示内容

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/1208330/145707375-f7a77513-320a-4959-a548-3df8ac507f65.png)

**Comment by PeachScript** [comment]
提供的测试链接是白色主题，无法复现 issue 描述的问题
