### ISSUE TITLE
Menu demo style problem

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3327]
<img width="85" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19211417/1decd76c-8d6e-11e6-8636-b6b7114a204a.png">

https://ant.design/components/menu/#components-menu-demo-theme

**Comment by kvetoslavnovak** [comment]
Maybe <Icon type="eye" /> for dark  and <Icon type="eye-o" /> for light one instead of texts?
