### ISSUE TITLE
Tree组件 没有childen的节点 无法拖入其他childen

### ISSUE THREAD

**Issue by WuZhaogang** [ant-design/ant-design#33278]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-draggable](https://ant.design/components/tree-cn/#components-tree-demo-draggable)

### Steps to reproduce
拖动官网示例就可以

### What is expected?
像3.x版本一样

### What is actually happening?
没有child的节点 无法把别的元素拖入

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Mac os big  |
| Browser | chrome |

**Comment by PeachScript** [comment]
链接指向的 demo 经测试可以工作：
![Kapture 2021-12-14 at 20 47 27](https://user-images.githubusercontent.com/5035925/146001240-78e9bde7-0227-4880-a2c8-a6d92c396469.gif)

**Comment by WuZhaogang** [comment]
好的

**Comment by WuZhaogang** [comment]
原来和3.x拖动方式不同 谢谢了
