### ISSUE TITLE
Table column 排序 sorter 属性， sorter.columnKey 值获取

### ISSUE THREAD

**Issue by Qiuhang817385** [ant-design/ant-design#33279]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/c506bc5](https://riddle.alibaba-inc.com/riddles/c506bc5)

### Steps to reproduce
注释 key

### What is expected?
不设置key值，设置 dataIndex，sorter.columnKey 默认用 dataIndex 兜底

### What is actually happening?
不设置key值，设置 dataIndex，sorter.columnKey 为 undefined
antd4
![image](https://user-images.githubusercontent.com/38211706/145776435-c6213eae-8332-409d-9311-63c58eab7448.png)

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.8 |
| System | windows |
| Browser | chorm 88 |

---
我看 antd3 的版本好像是默认兜底的，这个为什么去掉了呢
antd3
![image](https://user-images.githubusercontent.com/38211706/145776377-85e2d54e-3095-4309-b6c8-1713bd1453bd.png)

**Comment by afc163** [comment]
columnKey 是指向 key 属性的，兜底并不合理，建议用 field 属性。

**Comment by Qiuhang817385** [comment]
> columnKey 是指向 key 属性的，兜底并不合理，建议用 field 属性。

OK
