### ISSUE TITLE
点击按钮打开 modal，在 modal 中点击 cancel or ok 之后弹框关闭，此时打开弹框的按钮的状态是 focus（样式是蓝色的）

### ISSUE THREAD

**Issue by irenetang1993** [ant-design/ant-design#33270]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-guan-bi-antd-4-17-3-forked-xnxwl?file=/index.js)

### Steps to reproduce
点击按钮打开弹框，点击弹框中的cancel or ok 弹框会关闭，此时按钮的样式是focus状态（蓝色的）

### What is expected?
弹框关闭后，按钮的样式恢复成未触发的样式

### What is actually happening?
弹框关闭后，按钮的样式变成focus的样式

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 18.0.0-a |
| System | macOS Catalina 10.15.4 |
| Browser | 92.0.4515.107 |

---
其实我不太确定这是否本就是这么设计的

**Comment by afc163** [comment]
是预期的，看文档的 focusTriggerAfterClose 属性。

**Comment by irenetang1993** [comment]
想再多问句，为啥 Modal.confirm({}) 的形式弹出弹框，关闭弹框后按钮不是 focus 的状态呢？另外 focusTriggerAfterClose 默认是 true，这样设置的原因是？

**Comment by afc163** [comment]
为了键盘可访问性。
