### ISSUE TITLE
ConfigProvider getPopupContainer  ts error

### ISSUE THREAD

**Issue by cwjTerrace** [ant-design/ant-design#33274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/guo-ji-hua-antd-4-17-3-forked-txepp?file=/index.tsx)

### Steps to reproduce
打开链接

### What is expected?
triggerNode?.parentNode 不报错

### What is actually happening?
triggerNode?.parentNode 报错

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.0 |
| System | mac |
| Browser | edge |

**Comment by afc163** [comment]
https://codesandbox.io/s/guo-ji-hua-antd-4-17-3-forked-wy6jh?file=/index.tsx
