### ISSUE TITLE
Table title 'area' still appear and has a border when the control function returns null, but not when null is passed directly

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#33289]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-17-3-forked-4d3p3?file=/index.js)

### Steps to reproduce
Change the value of the const 'testValue', see how the table still renders the title area even if the function returns null.

### What is expected?
The table to not render the title area when the control function returns null.

### What is actually happening?
The table renders the title area even if the control function returns null.

![image](https://user-images.githubusercontent.com/87539237/145984923-80871a9b-4663-4afc-87ab-5b797c6169ab.png)

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | react: 17.0.2 |
| System | Windows 10 |
| Browser | Brave |

---
If you pass the 'title' prop directly as null, it works as expected, but for my case, I have checks that handles different titles.

**Comment by UsamaMahboob** [comment]
I can work on this!

**Comment by afc163** [comment]
```diff
- title={handleTitle}
+ title={handleTitle()}
```

**Comment by balboFK** [comment]
@afc163 how do I type the handle function with your usage?
Check the sandbox, I updated it and now I'm getting a Type error.
If you ignore it, it works just fine.
