### ISSUE TITLE
Dropdown Select Windows Button

### ISSUE THREAD

**Issue by burakmantas** [ant-design/ant-design#33281]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select/](https://ant.design/components/select/)

### Steps to reproduce
Someone is selecting one item from dropdown box , after that closes the dropdown select and lastly you are pressing to windows button and select combobox will be open . Combobox should not be open by pressing windows button on keyboard

### What is expected?
pressing windows button only opens windows menu

### What is actually happening?
pressing windows button opens dropdown select combobox

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | I dont know react version |
| System | Windows 10 |
| Browser | Google Chrome  |

**Comment by ZzGGitter** [comment]
I can solve it, but I have a problem about the expected result for it
I have a question about the expected result.
What key do you want the "Select" to open when you press it.
Now it will open when  you press any key.
我可以解决它，但我对它的预期结果有疑问。
我对预期结果有疑问。
希望在按下什么键的时候Select框会打开。
现在，当您按任意键时它会打开。

**Comment by burakmantas** [comment]
Hello,

Expected result could be; when you press windows button on keyboard it
shouldn't open select combobox it should only open a windows start menu..

**Comment by ZzGGitter** [comment]
[I soleve it in the the rc-select #693](https://github.com/react-component/select/pull/693)
Thanks for your comments，finally I decided to block some system buttons, like commal ctrl alt window, f1 - f12.
Merry Christmas.

**Comment by burakmantas** [comment]
Awesome, thanks!
