### ISSUE TITLE
Select下拉框dropdownRender中渲染DatePicker组件 选择年的时候Select下拉框自动失去焦点 无法选择年

### ISSUE THREAD

**Issue by git997-small** [ant-design/ant-design#33282]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xn78n?file=/index.js)

### Steps to reproduce
选中下拉框中的日期组件,切换日期面板 下拉框消失

### What is expected?
可以选中年份 选中后下拉框再隐藏

### What is actually happening?
只能选中到天不能选择年份

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16.8 |
| System | mac 12.0 |
| Browser | chrome 96.00 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-jjs8g?file=/index.js
