### ISSUE TITLE
The popup of components such as Popover and Tooltip cannot be flipped normally（类似 Popover 或者 Tooltip 之类的组件的 popup 无法正常翻转）

### ISSUE THREAD

**Issue by y805939188** [ant-design/ant-design#33283]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1mzf7?file=/index.js)

### Steps to reproduce
1. hover 上去
2. 弹出来的 popup 没有正常翻转到 bottom

### What is expected?
上方距离不足时，popup 可以正常翻转到 bottom

### What is actually happening?
popup 弹出方向不对

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17 |
| System | mac |
| Browser | chrome |

---
大概率是底层用的 rc-trigger 在做翻转的时候有问题。
不过出现这个问题一定要同时满足三个条件：
1. 最外层容器有 overflow 属性（无论是 auto 还是 hidden）
2. 最外层容器有 position: relative 属性
3. trigger 的父容器有 position：fixed 属性
这仨属性少任何一个都复现不出来的

**Comment by afc163** [comment]
Duplicate of #26474

**Comment by y805939188** [comment]
> Duplicate of #26474

请问这个 bug 有计划修复么，或者是否知道是 rc-trigger 中哪里导致的？
