### ISSUE TITLE
Modal component doesn't work cross frame

### ISSUE THREAD

**Issue by victoragnez** [ant-design/ant-design#33285]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-17-3-forked-395r6?file=/index.js:865-877)

### Steps to reproduce
Render a Modal with `getContainer={anotherFrame.document.body}`

### What is expected?
To render the modal and the overlay within the iframe

### What is actually happening?
The same thing as if `getContainer` prop wasn't set

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Linux |
| Browser | Chrome |

**Comment by afc163** [comment]
There is no styles in this iframe.

**Comment by victoragnez** [comment]
Hi @afc163. the issue happens even if the iframe has styles from `antd/dist/antd.css`.
The modal is not mounting in the iframe, but rather in the parent document.

We can see we get a different behavior if we replace `getContainer={anotherFrame.document.body}` by `getContainer={() => 
anotherFrame.document.body}`: the latter does render in the iframe (mounting at the correct node), but it never unmounts even after closing the Modal
