### ISSUE TITLE
IM聊天组件

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design#33290]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
即时消息在企业应用中比较常见，希望antd能提供IM组件，方便集成聊天的功能。
基本的功能：
1. 接/发送文字
2. 接/发送图片
3. 接/发语音

### What does the proposed API look like?
<ChatList .../>
<MessageBox .../>

**Comment by afc163** [comment]
暂无计划。
