### ISSUE TITLE
希望 CheckboxGroup 支持栅格化排列

### ISSUE THREAD

**Issue by lyk248** [ant-design/ant-design#3329]
#### 发生问题的环境是：

- antd 版本: 1x
- 操作系统及其版本: Mac
- 浏览器及其版本: Chrome

#### 您做了什么？

引入了 antd 的 CheckboxGroup

#### 您期待的结果是：

checkbox 元素呈栅格化、垂直排列

**Comment by wjljack** [comment]
求样式

**Comment by lyk248** [comment]
> 求样式

没研究垂直排列的..比较懒..栅格你就给 .ant-checkbox-group label 写个百分比宽度调一下 margin 就好了吖..
