### ISSUE TITLE
Allow modifying the "transitionName" prop of the slider tooltip without overriding the "rootPrefixCls" in the config provider

### ISSUE THREAD

**Issue by MorisR** [ant-design/ant-design#33298]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The ability to manually override the antd prefix (using less   changing the "prefixCls" prop on each component)  without the use of the **ConfigProvider** component.

The current issue I'm facing is that by modifying the "@ant-prefix" in Less and manually setting the "prefixCls" prop on specific components,
it causes the prefix of the motions (animations) to change as well, which in return requires updating the appropriate props (transitionName, maskTransitionName, etc.. ) in each of the components.

but when it comes to the **Slider** component, there's no way to modify the **SliderTooltip** props or specifically modifying the **transitionName** to adjust the prefix change accordingly.

### What does the proposed API look like?
Expose a **tooltipTransitionName** prop in the [slider component](https://github.com/ant-design/ant-design/blob/678cf4948beec6fb2fadec7f930035c78ade51e2/components/slider/index.tsx#L118), and use the [getTransitionName](https://github.com/ant-design/ant-design/blob/13a829d20c8a1a83c3bfa1f9d7c30d95659f5b57/components/_util/motion.tsx#L24) function to construct the value.

**Comment by MorisR** [comment]
The closest open issue to this one is [#18016](https://github.com/ant-design/ant-design/issues/18016)

**Comment by afc163** [comment]
Trace #18016, and PR is welcome for `tooltipProps`~
