### ISSUE TITLE
Table 不支持麒麟系统火狐浏览器

### ISSUE THREAD

**Issue by rabbitbiubiubiu** [ant-design/ant-design#33308]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/table-cn/](https://ant-design.gitee.io/components/table-cn/)

### Steps to reproduce
使用麒麟系统访问官网

### What is expected?
table支持麒麟系统

### What is actually happening?
table不支持麒麟系统，

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.13.1 |
| System | 麒麟系统 |
| Browser | 火狐浏览器 52.3 .0 |

**Comment by afc163** [comment]
版本太老了，可以看下 README 里的浏览器支持范围。

**Comment by rabbitbiubiubiu** [comment]
> 版本太老了，可以看下README里的浏览器支持范围。

麒麟系统火狐浏览器最高版本就是这个

**Comment by rabbitbiubiubiu** [comment]
> 版本太老了，可以看下README里的浏览器支持范围。

麒麟系统火狐浏览器最高版本就是这个

**Comment by hanxzi** [comment]
@rabbitbiubiubiu 有没有解决方案
