### ISSUE TITLE
 如何访问Modal里面的Form元素？

### ISSUE THREAD

**Issue by Midqiu** [ant-design/ant-design#3330]
#### 发生问题的环境是：
```
return (
      <div>
        <Button type="primary" onClick={this.showModal}>Surprise</Button>
        <Modal  title="login" visible={this.state.visible} onOk={this.handleSubmit} onCancel={this.hideModal}>
          <FormDemo ref='form' />
        </Modal>
      </div>
    );
```
当用户点击Modal的确定按钮时候，我想调用Modal里面的那个Form的校验方法。
本来我可以这样来调用：
```
this.refs['form'].handleSubmit()
```
但是，如果这个Form经过`FormDemo = createForm()(FormDemo)`处理后，上面的方法就不好使了。
#### 可重现的在线演示
http://codepen.io/Midqiu/pen/LRdPOy?editors=1111

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/search?q=form+ref&type=Issues&utf8=%E2%9C%93

---

https://github.com/ant-design/ant-design/issues/3224
https://github.com/ant-design/ant-design/issues/2843
https://github.com/ant-design/ant-design/issues/2153
https://github.com/ant-design/ant-design/issues/2238
https://github.com/ant-design/ant-design/issues/2980
