### ISSUE TITLE
Select 组件使用扩展菜单，下拉框和输入框会同时聚焦

### ISSUE THREAD

**Issue by shibinwang1204** [ant-design/ant-design#33309]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#API](https://ant.design/components/select-cn/#API)

### Steps to reproduce
Select 组件使用扩展菜单，当设置为多选模式时，在扩展菜单的输入框输入内容，按下backspace回退键删除输入框文字时，下拉菜单已经选择的元素会被同时删除

### What is expected?
删除输入框内容时，下拉框选择的内容不应该被删掉

### What is actually happening?
删除输入框内容时，下拉框选择的内容同时被删掉

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16 |
| System | win10 |
| Browser | chrome |

---
目测是因为下拉框和其内部的输入框同时聚焦导致

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28694#issuecomment-754471826
