### ISSUE TITLE
Prop `getContainer` from Modal doesn't support cross-frame elements

### ISSUE THREAD

**Issue by victoragnez** [ant-design/ant-design#33315]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bhs6y?file=/index.js:1684-1696)

### Steps to reproduce
Click on Open Modal

### What is expected?
The modal should render inside the iframe

### What is actually happening?
The modal is not using the element passed in `getContainer`

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Linux |
| Browser | Chrome |

---
It seems to happen because the checks for HTML elements don't work cross-frame. I found two examples while trying to make it work (not sure if there are more occurrences):

[`nodeRoot instanceof Document`](https://github.com/ant-design/ant-design/blob/9324e953e3b203dfcc0f96c1c20d9a99a1a23783/components/_util/wave.tsx#L100)

[`getContainer instanceof window.HTMLElement`](https://github.com/react-component/util/blob/c809254249c00215c4463aaf735467f775f7d518/src/PortalWrapper.tsx#L35) (The link to minimal reproduction project is hitting this one)

Maybe those checks could be replaced by the following, respectively:

`nodeRoot instanceof deriveWindow(nodeRoot)?.Document`

`getContainer instanceof deriveWindow(getContainer)?.HTMLElement`

(assuming `deriveWindow` works with both `HTMLElement` and `Document` to find their respective `Window`)

For reference: [https://stackoverflow.com/questions/20526689/is-there-a-cross-browser-and-cross-frame-way-to-check-if-an-object-is-an-html-el](https://stackoverflow.com/questions/20526689/is-there-a-cross-browser-and-cross-frame-way-to-check-if-an-object-is-an-html-el)

**Comment by PeachScript** [comment]
This UI logic sounds very weird😓...but you still can use function to implement it:

```tsx
getContainer={() => ref.contentWindow.document.body}
```

**Comment by victoragnez** [comment]
Hi @PeachScript, thanks for your response!
Indeed passing the argument as a function works in the minimal reproduction project, which was only hitting the [second check](https://github.com/react-component/util/blob/c809254249c00215c4463aaf735467f775f7d518/src/PortalWrapper.tsx#L35) I mentioned.

However it's still possible to hit the [first one](https://github.com/ant-design/ant-design/blob/9324e953e3b203dfcc0f96c1c20d9a99a1a23783/components/_util/wave.tsx#L100) even using the function approach. It happens when I try to use the Modal in a large real project, failing with the following error:
![image](https://user-images.githubusercontent.com/12224153/146926042-932a51b3-8d62-4039-99a6-b09ff852cec9.png)

**Comment by xylinq** [comment]
![image](https://user-images.githubusercontent.com/1905319/148729310-ae8d7327-fba7-4651-a45c-b2e2acfd0020.png)
我认为可能是这里的问题，这里判断了 nodeRoot 是否是 Document 的实例，因为 getContainer 设置的是 iframe 里的元素，所以结果为 false，attachTo 就设置为了 nodeRoot，也就导致了下图的 appendChild 失败
![image](https://user-images.githubusercontent.com/1905319/148729811-e0453d5b-8b33-464e-8110-84090f9dab83.png)

**Comment by xylinq** [comment]
看起来是 wave 动画效果引起的，看了下源码，className 中包含 -leave 的话会直接 return，所以暂时使用这种方法避免异常抛出了。
