### ISSUE TITLE
Tab组件，在TabBar的折叠列表中关闭所有Tab页时列表容器有残留

### ISSUE THREAD

**Issue by Malerei** [ant-design/ant-design#33311]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-editable-card](https://ant.design/components/tabs-cn/#components-tabs-demo-editable-card)

### Steps to reproduce
1.打开重现链接（官方Demo，同样存在问题）
2.点击新增Tab页直至出现折叠图标
3.在折叠列表中逐个关闭Tab页直至折叠图标消失

### What is expected?
折叠图标消失，折叠列表消失

### What is actually happening?
折叠图标消失，列表内容清除，但空的列表容器会出现再左上角（很小一块，大致在第一二个Tab页签下方）一直存在，鼠标移入移出后消失

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Win10 家庭版 |
| Browser | Chrome 96.0.4664.93 Firefox 86.0 (64 位) |

**Comment by afc163** [comment]
来个截图或者录屏？

**Comment by JX-Zhuang** [comment]
@afc163 @PeachScript 
已经有其他人的[pr](https://github.com/react-component/tabs/pull/461)，但是一直没review。还要修复吗

**Comment by blueiky** [comment]
今天用到的时候发现这个问题，还没有修复嘛？

**Comment by afc163** [comment]
@MadCcc 再看看 https://github.com/react-component/tabs/pull/461

**Comment by zhulichaoZW** [comment]
antd@4.22.3 引用 rc-tabs 是 ~11.16.0
