### ISSUE TITLE
How to scrollToFirstError scroll look better

### ISSUE THREAD

**Issue by votien1235** [ant-design/ant-design#33329]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When i click submit, it has moved to the error location, but its appearing position is not so great, how to fix it to the center of the screen

### Reproduction link
https://codesandbox.io/s/scroll-to-the-first-error-with-upload-antd-forked-yfqx7?file=/src/App.js

**Comment by afc163** [comment]
```
scrollToField(name: NamePath, options: ScrollOptions)
```

Check ScrollOptions
