### ISSUE TITLE
Input组件onFocus问题

### ISSUE THREAD

**Issue by reiken** [ant-design/ant-design#33326]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-3-forked-z55kb?file=/package.json)

### Steps to reproduce
input获得焦点，点击弹窗的取消关闭弹窗

### What is expected?
正常关闭

### What is actually happening?
input自动获得焦点，弹窗关闭失败

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16.14.21 |
| System | MACOS |
| Browser | chrome |

**Comment by boomler** [comment]
应该是 dialog 关闭之后，自动 focus 回上一个 activeElement 导致的。 感觉只能自己想办法避免这种逻辑冲突了。

**Comment by afc163** [comment]
`focusTriggerAfterClose`
