### ISSUE TITLE
Table - Type error with column property align

### ISSUE THREAD

**Issue by cehenriques** [ant-design/ant-design#33328]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2becx?file=/index.tsx)

### Steps to reproduce
Use typescript and add the align property to columns object

### What is expected?
Align property values should be recognized

### What is actually happening?
Doesn't recognized value "right" or "left" even though in the docs they are used as strings

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | 12.1 |
| Browser | 96.0.4664.110 |

**Comment by afc163** [comment]
```jsx
align: 'right' as const
```
