### ISSUE TITLE
Failed to parse source map: 'webpack://antd/./components/config-provider/style/index.less' URL is not supported

### ISSUE THREAD

**Issue by sauldeleon** [ant-design/ant-design#33327]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/sauldeleon/antd-webpack5-repro](https://github.com/sauldeleon/antd-webpack5-repro)

### Steps to reproduce
- clone this repo
- run `npm i`
- run `npm start`
- check the logs in the console

### What is expected?
React start the application with no warning issues. In certain environments, warning issues are not supported and will crash the build for production environments

### What is actually happening?
Webpack 5 throws errors due to loading URL for less files
Edit: as @YouWillBe said, this is due to using `react-scripts 5.0.0` which uses `webpack 5`

Failed to parse source map: 'webpack://antd/./components/config-provider/style/index.less' URL is not supported
Failed to parse source map: 'webpack://antd/./components/icon/style/index.less' URL is not supported
Failed to parse source map: 'webpack://antd/./components/locale-provider/style/index.less' URL is not supported
Failed to parse source map: 'webpack://antd/./components/time-picker/style/index.less' URL is not supported

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | All systems |
| Browser | Chrome 96.0.4664.110 |

**Comment by YouWillBe** [comment]
`react-script` 升级到`5.0.0`之后出现此问题，也就是说从14号开始，所有通过`npx create-react-app` 创建的项目，引入`antd.css` 之后都会看到这个警告

**Comment by sauldeleon** [comment]
Sorry mate, I do not understand chineese! what do you mean?

**Comment by YouWillBe** [comment]
Don’t be nervous, I just clarified the problem, I believe the antd team members will give a solution soon

**Comment by ThalesMR** [comment]
Same issue here...

**Comment by PetrVasilev** [comment]
Same issue...

**Comment by sauldeleon** [comment]
As a temporal workarround for me, knowing it is something far from a fix, I have managed to hide the warnings messages modifying the webpack configuration using the `ignoreWarnings` parameter.

In my specific scenario, I am using `craco` to overload the webpack configuration provided by CRA, so adding this will do the trick:

```js
//craco.config.js

module.exports = {
  plugins: [ ... ],
  webpack: {
    configure: webpackConfig => {
      // other stuff with webpackConfig
      return {
        ...webpackConfig,
        ignoreWarnings: [/Failed to parse source map/],
      }
    },
  },
}
```

**Comment by solvanny** [comment]
Same issue. Hopefully, the ANTD team will fix it as soon as possible.

**Comment by ppegu** [comment]
Solution : 

`- import 'antd/dist/antd.css`
replace with 
`+ import 'antd/dist/antd.min.css`

**Comment by PlayWithSanLei** [comment]
> 解决方案 ：
> 
> `- import 'antd/dist/antd.css` 用。。。来代替 `+ import 'antd/dist/antd.min.css`


**这个解决方案很有效，谢谢大佬！**

**Comment by sauldeleon** [comment]
The solution given by @ppegu worked for me. If the dev team thinks this is enough to close the issue, this can be closed imho, despite I guess it would be better to allow import both files without seeing the warnings.

Thanks @ppegu !

**Comment by dadadadaben123** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

thank you for your solution

**Comment by vladimirevstratov** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Didn't help, temporarily omit warnings using @sauldeleon approach.
Any thoughts guys?

**Comment by sauldeleon** [comment]
Have you check if you are importing antd css files in more than one location?

The `antd.min.css` approach worked for me.

Maybe another library is importing antd css non-minified file?

**Comment by pzppzz** [comment]
This error also occurred when I introduced the Ant Design Echarts component in the React project.
Does  anyone know the solution?

**Comment by TranHuuTrung** [comment]
> 

It's working perfect!

**Comment by wo4558771** [comment]
> 这个错误也是我在 React 项目中引入 Ant Design Echarts 组件的时候出现的。 有谁知道解决方案？
把react-scripts版本替换成4.0.0就可以了

**Comment by alanwhy** [comment]
> antd/dist/antd.min.css

thanks~

**Comment by BenDev12** [comment]
@ppegu 's solution worked for me.
Thanks mate `import 'antd/dist/antd.min.css`

**Comment by ArbazAhmedKirmani** [comment]
`antd.min.css` this worked for me too..
Thanks @ppegu

**Comment by mmdzov** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thanks. It worked for me

**Comment by saad696** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

this is not working for me!!!!

**Comment by ArbazAhmedKirmani** [comment]
What is basically your problem.. Pleass elaborate it so i can better
understand and try to help.

**Comment by kabirpokharel** [comment]
> What is basically your problem.. Pleass elaborate i



> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Help !!!! where should I replace this ????

**Comment by koitoror** [comment]
Thanks @ppegu ! Worked !

**Comment by ppegu** [comment]
> > Solution :
> > `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`
> 
> Help !!!! where should I replace this in a react project ????

Yes in react project. Replace where you have imported the antd.css file followed by doc.

**Comment by fdhouse** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

genius!

**Comment by Arifuzzaman-Nishan** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thank bro

**Comment by M-Mubashir674** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

It worked for me. Thanks ....

**Comment by sakattack** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

worked fome as well, thank u

**Comment by rjtbst** [comment]
> 
yest it worked thankksss

**Comment by BreakUps** [comment]
@ppegu Thanks a lot, btw Could you please help explain how that works?

**Comment by PlaceboJoe** [comment]
import 'antd/dist/antd.min.css' it`s work for me

**Comment by sefaun** [comment]
`'antd/dist/antd.min.css'` tremendous solution

**Comment by zhubei1998** [comment]
Write `@import '~antd/dist/antd.css';` in App.css, then import it in `App.js`.
Instead of importing `antd/dist/antd.css` in the entrance `index.js`.
That works for me. You can find it in the [Antd docs](https://ant.design/docs/react/use-with-create-react-app#Import-antd).
<img width="445" alt="image" src="https://user-images.githubusercontent.com/61346370/154877581-d520e6e7-161c-46e2-a356-493e0cc3423e.png">

**Comment by LiXiaoRan** [comment]
@zhubei1998 good ideas

**Comment by jmndao** [comment]
That's really awesome. Thank you @ppegu

**Comment by shelinz1** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thanks alot...works!!!

**Comment by howardding2000** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thank you for the solution !
It should be mentioned in docs

**Comment by DCTriDev** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

It's worked. Thank you very much 👯

**Comment by satyambnsal** [comment]
@ppegu Rocks . Thanks mate ❤️

**Comment by zelalemgetahun9374** [comment]
> Write `@import '~antd/dist/antd.css';` in `App.css`, then import it in `App.js`. Instead of importing `antd/dist/antd.css` in the entrance `index.js`. That works for me. You can find it in the [Antd docs](https://ant.design/docs/react/use-with-create-react-app#Import-antd). <img alt="image" width="445" src="https://user-images.githubusercontent.com/61346370/154877581-d520e6e7-161c-46e2-a356-493e0cc3423e.png">

Thank you!

**Comment by tohidshabanloo** [comment]
none of them are worked for me, still get the same error;

**Comment by deivyrene** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thanks @ppegu GG

**Comment by ArielMolho** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

@ppegu you are a star!

**Comment by medjamiaanes** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Worked like a charm ! , Thanks !

**Comment by marshalyordanos** [comment]
ppegu tnx so much

**Comment by prakashks22** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thank you. This is working fine for me

**Comment by webbysrv** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

This worked for me, thanks mate @ppegu

**Comment by SkyzcYou** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`



> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thanks ^_^

**Comment by ycchong9** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Thanksss

**Comment by vbiker-39** [comment]
is the only solution:

- import 'antd/dist/antd.css replace with + import 'antd/dist/antd.min.css

Thanks

**Comment by AmrAhmedA** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

works for me, pretty much thanks

**Comment by hqlovely** [comment]
The  solution:

import 'antd/dist/antd.css replace with + import 'antd/dist/antd.min.css
works fine thanks

**Comment by DongHY1** [comment]
> Solution：
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`

Tanks

**Comment by mskarimi** [comment]
> Solution :
> 
> `- import 'antd/dist/antd.css` replace with `+ import 'antd/dist/antd.min.css`
> 
> Thanks for all your love. Please follow me on GitHub

thank you
it's working ...

**Comment by techport-dev** [comment]
> Write `@import '~antd/dist/antd.css';` in `App.css`, then import it in `App.js`. Instead of importing `antd/dist/antd.css` in the entrance `index.js`. That works for me. You can find it in the [Antd docs](https://ant.design/docs/react/use-with-create-react-app#Import-antd). <img alt="image" width="445" src="https://user-images.githubusercontent.com/61346370/154877581-d520e6e7-161c-46e2-a356-493e0cc3423e.png">

thanks
