### ISSUE TITLE
Select 的 Option 中设置驼峰命名的属性时，控制台会报错

### ISSUE THREAD

**Issue by zmbxy95** [ant-design/ant-design#33330]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-4-17-3-forked-tf5i6?file=/index.js)

### Steps to reproduce
如下图所示，当在Select Option属性中添加自定义属性，并且自定义属性为驼峰命名时，点击选择框时就会触发控制台报错。从结果来看，貌似把属性传递到了DOM节点身上，但其实DOM attribute要求是全小写属性报错。
![image](https://user-images.githubusercontent.com/50108232/146366765-cff3a863-eba2-4a16-aa92-b9abfaade40c.png)

同样的的如果自定义属性为布尔值，控制台会报错要求属性值为字符串

### What is expected?
可以正常设置驼峰命名的自定义属性

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16.14.10 |
| System | windows |
| Browser | chrome96 |

**Comment by afc163** [comment]
这是合理的，目前会把其他属性直接传给 dom 元素，如果不希望看到 React 的 ⚠️，可以使用 `data-xxx="xxx"` 来做属性名。

**Comment by zmbxy95** [comment]
@afc163  后续会考虑这方面吗，在组件内部做一些处理，对于组件本身来说，就是给什么数据，可以返回什么数据，而不是需要再去关心些DOM上的问题。毕竟对于Select组件的onSelect和onChange方法中的option参数，取一些其他的数据，再去关联做一些处理等应该是个常见操作。

**Comment by afc163** [comment]
目前不太好判断哪些应该放 dom 上，哪些不放。

**Comment by zmbxy95** [comment]
了解了
