### ISSUE TITLE
Site - Components re-render with Show Code click

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#3333]
https://ant.design/components/transfer/

If you click on Show Code button or Expand All Code icon the components seem to re-render, the example lists change due to Math.random function.

**Comment by kvetoslavnovak** [comment]
https://ant.design/components/table/
Table examples ( at least)
- Selection and operation
- Reser filters and sorters
- Ajax
- Loading
- Grouping table head
have the same problem

**Comment by kvetoslavnovak** [comment]
I have examined iit. It seems that all demo components using state have this problem.

**Comment by benjycui** [comment]
2333
