### ISSUE TITLE
兼容动态主题和动态主题色，并且可以灵活配置

### ISSUE THREAD

**Issue by lixinkit** [ant-design/ant-design#33338]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
让用户可以灵活的配置主题、主题色

### What does the proposed API look like?
1、目前官方主题：默认主题（亮色）、 暗黑主题（4.0.0  支持）、紧凑主题（4.1.0  支持）、 阿里云控制台主题（Beta）。

2、此外还提供了 CSS Variable 以支持动态切换主题色的能力。

诉求：

1、用户扩展主题：能否增加用户自定义主题的能力？在基础的样式上，用户可以选择搭配色，根据搭配色，生成一份新的主题。

2、动态主题、动态主题色兼容问题：CSS Variable动态切换主题色的能力，只支持默认主题（亮色），能否兼容其他的主题？（暗黑、紧凑、用户自定义等）。

最终效果：

开发者可以扩展主题；用户可以动态的切换主题：亮色、暗黑、紧凑、自定义等，并且在主题的基础上，动态切换主题色。例如：https://preview.pro.ant.design/dashboard/workplace/?fixSiderbar=true&navTheme=realDark&layout=mix&title=Ant Design Pro

**Comment by afc163** [comment]
Duplicate of #32807
