### ISSUE TITLE
AntD Tabs Does Not Expand After Window Resize

### ISSUE THREAD

**Issue by charles-otto** [ant-design/ant-design#33333]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4q054?file=/index.js)

### Steps to reproduce
1) Create an array of 10 Tabs
2) Open up the browser dev tools and set the code sandbox browser preview window to 680px width.  All the Tabs should be fully visible without any overflowing.  The ellipsis (...) menu should not appear at this width.
3) Resize the window width down slowly until the Tabs cannot fill the viewport (For example, at 670px width).  The ellipsis (...) menu appears and shows the overflowed tabs when clicked on.  This bevhaiour is as expected.
4) Resize the window width up slowly to 680px width.  Observe that instead of fully showing all Tabs as in Step 2, the ellipsis (...) menu is still rendered.  This behaviour is not expected.

### What is expected?
The ellipsis (...) menu should be hidden when the window width is slowly resized up to to the original width where all Tabs fit in the window without overflowing.  

### What is actually happening?
The ellipsis (...) menu continues to display on the screen after resizing window width up to fit all Tabs (For example, at 680px width).  The ellipsis (...) menu eventually hides from view at around 725px width, but we expect it to be hidden at 680px width.

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 16.13.1 |
| System | Ubuntu 20.04.2 LTS |
| Browser | 92.0.4515.131 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Can not reproduce the problem, could you provide a video?
