### ISSUE TITLE
Select with search, mode=multiple and custom dropdown renderer reset search value when button in renderer clicked

### ISSUE THREAD

**Issue by MichalNovotnyCZ** [ant-design/ant-design#33345]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/michal-novotn-/pen/JjrNJzb](https://codepen.io/michal-novotn-/pen/JjrNJzb)

### Steps to reproduce
- click to selectbox
- write "ja" or "lu" (without quotes)
- click to input or link in custom renderer

OR

- click to selectbox
- write "ja" or "lu" (without quotes)
- press Tab on keyboard

### What is expected?
- search value and filtering stay as are
- new item can be created in filtered list

### What is actually happening?
- search value and filtering are reseted
- if you click on link, new item wasn't created and can be created on second click

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 96.0.4664.110 |

**Comment by afc163** [comment]
It is by designed, blurring the search box will reset it.
