### ISSUE TITLE
Switching Themes leaves the old stylesheet imported causing conflicts with the UI

### ISSUE THREAD

**Issue by radesai21** [ant-design/ant-design#33347]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-imdsy)

### Steps to reproduce
Steps:
1. Switch theme from light to dark
2. Notice that the input box on the Cron component is not styled correctly for dark mode - the background on the input is still white
3. Switch from dark to light
4. Notice that the input box is not styles correctly again - the font color is white when it should be black

Dark Theme component - used to conditionally import the dark mode css file:
```javascript
import React from 'react';
import 'antd/dist/antd.dark.css';

const ThemeDark = () => (<div />);
export default ThemeDark;
```
---------------------------------------------------------------------------------------------------------
Light Theme Component - used to conditionally import the light mode css file:
```javascript
import React from 'react';
import 'antd/dist/antd.css';

const ThemeLight = () => (<div />);
export default ThemeLight;
```
---------------------------------------------------------------------------------------------------------
Input Component:
```javascript
import React, { useState } from 'react';
import Cron from 'react-js-cron';
import './cron-scheduler.scss';

const LightTheme = React.lazy(() => import('./theme-light'));
const DarkTheme = React.lazy(() => import('./theme-dark'));

const Scheduler = ({ initialValue, onChange }: any) => {
  const { isLight, setTheme } = useState(true);

  return (
    <React.Suspense fallback={<div />}>
        <Button type="primary"onClick={() => setTheme(!isLight)} >
              Change Theme
        </Button>
        { isLight ? <LightTheme /> : <DarkTheme /> }
        <Cron  />
    </React.Suspense>
  );
};

export default Scheduler;
```

### What is expected?
The Theme should be switched without having the styles from the old theme still applied. 

### What is actually happening?
In the example provided you can see that when switching from dark to light the styles conflict and have colors from dark and light theme still applied. IN Our specific application we're seeing the background on the input box stays white when switching from light to dark. Then when switching from dark to light theme the font color doesn't get updated to the dark theme's font color. On the forked sandbox you can see that one the theme is switched from light to dark - it won't switch back even though the components are successfully swapped. The stylesheet stays present in the app and gets stuck in dark theme. 

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Windows & Mac |
| Browser | Chrome/Firefox/Safari |

---
The issue is coming from having to conditionally import the CSS files using React.lazy & suspense. The main issue stems from when having both stylesheets imported at once causing the UI's styles to conflict with one another. When the component is unmounted the css that it imported is not getting cleaned up - it lingers on the session until the user refreshes the page and only one stylesheet for either dark or light mode is present.

**Comment by afc163** [comment]
I don't think it is a antd issue, you should check your project config.
