### ISSUE TITLE
Theming does not work

### ISSUE THREAD

**Issue by raph90** [ant-design/ant-design#33344]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/raph90/ex](https://github.com/raph90/ex)

### Steps to reproduce
Simply clone, install and run 'yarn start'

### What is expected?
The primary button that is rendered should be green, as per the documentation. 

### What is actually happening?
None of the antd styles are being loaded. I am importing with .less as specified in the documentation, and in babel-import plugin I have set style to true

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
Don't enable css-modules on antd less files.

**Comment by raph90** [comment]
Unfortunately disabling CSS modules still doesn't resolve this issue.

**Comment by raph90** [comment]
I managed to get it working by getting rid of CSS modules for less files and using scss for my modules. It's not ideal but not the end of the world either.
