### ISSUE TITLE
unpkg上有乱码

### ISSUE THREAD

**Issue by allces** [ant-design/ant-design#3335]
https://unpkg.com/antd@1.11.1/dist/antd.js

![image](https://cloud.githubusercontent.com/assets/7076712/19217475/5f624178-8e0e-11e6-951d-bb25151f87d2.png)

**Comment by afc163** [comment]
<img width="474" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19217496/d839a85c-8e0e-11e6-9610-c328423b5622.png">
