### ISSUE TITLE
InputNumber not working in mobile screen

### ISSUE THREAD

**Issue by Pacheco95** [ant-design/ant-design#33351]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Pacheco95/antd-input-number-mobile-bug-report](https://github.com/Pacheco95/antd-input-number-mobile-bug-report)

### Steps to reproduce
* `npx create-next-app@latest --ts`
* `npm i antd`
* replace `index.tsx` content with
```tsx
import type { NextPage } from 'next'

import {InputNumber} from 'antd'

const Home: NextPage = () => {
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      height: '100vh'
    }}>
      <InputNumber style={{ width: '150px'}} placeholder='Type something'/>
    </div>
  )
}

export default Home
```
* `npm run dev`
* Activate mobile view in chrome devtools
* Reload the page

### What is expected?
The InputNumber to be shown as the same when in desktop mode

### What is actually happening?
The component appears flattened

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Ubuntu 20.04.3 LTS |
| Browser | Version 95.0.4638.69 (Official Build) (64-bit) |

---
I'm using Next.js with Typescript template. Maybe it's related with SSR
I never saw this bug happen in my CRA apps

**Comment by Pacheco95** [comment]
I have tested and the bug was introduced in `v4.13.0`

**Comment by PeachScript** [comment]
cc @zombieJ

**Comment by joweecaquicla** [comment]
This seems to be a similar issue with this https://github.com/ant-design/ant-design/issues/31908.
A fix was introduced, however, it seems to be working only when the page is still loading and the elements are still present. The inputNumber handler elements disappear on a mobile screen, that's why the applied changes in the previously mentioned issue are not working as expected.

See video attached:

https://user-images.githubusercontent.com/23549533/146813162-5c926802-3deb-492e-91ee-5afcaac6b271.mp4

**Comment by Pacheco95** [comment]
@zombieJ any updates here?

**Comment by afc163** [comment]
It seems be intented: https://github.com/react-component/input-number/blob/d3de1472f23b4978d74a221e4b11db5408900ef9/src/StepHandler.tsx#L62

**Comment by Pacheco95** [comment]
But this error is causing the component to be unusable. I think the problem is not with the step handler, but with the input component render itself

**Comment by Pacheco95** [comment]
Have you executed the reproduction link? https://codesandbox.io/s/vigilant-roentgen-xdlto?file=/pages/index.tsx&resolutionWidth=320&resolutionHeight=675
Steps:
1. Run the sandbox.
2. Open it in a separate browser
3. Toggle mobile mode
4. Refresh page

It looks as a div margin
![image](https://user-images.githubusercontent.com/12385467/148545613-806836e1-61b0-40d9-9737-d42c430e37c0.png)

**Comment by Josemanki** [comment]
Hey, @Pacheco95 ! I was wondering if you got to solve this issue somehow? I have found myself with a similar one and input on the topic would be appreciated.

**Comment by Pacheco95** [comment]
Hi, @Josemanki. I implemented it by myself using the default Input component. But it has some limitations, e.g., it does not allow negative numbers
https://gist.github.com/Pacheco95/1dd18368de7c91420eceff52ea8a967d
You can use the idea to address your specific problem

**Comment by Josemanki** [comment]
Much, much appreciated. I initially thought about indeed just having an input working just with numbers but really wanted to keep the spinner, haha. Cheers and thank you very much!

**Comment by skyyuxuan** [comment]
> Hey, @Pacheco95 ! I was wondering if you got to solve this issue somehow? I have found myself with a similar one and input on the topic would be appreciated.

you can try set controls value
