### ISSUE TITLE
Modal静态方法参数中若getContainer={false}则调用失效，且无错误提示

### ISSUE THREAD

**Issue by zhouzongren** [ant-design/ant-design#33359]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/RickChou/pen/poWwVao?editors=0010](https://codepen.io/RickChou/pen/poWwVao?editors=0010)

### Steps to reproduce
依次点击按钮，第一个无法正常弹出

### What is expected?
getContainer是false modal能正常弹出，但是因为modal静态方法没有上下文dom，所以应该自动挂载到document.body上然后报一个warning?
组件方式的调用因为有react上下文，设为false是能获取到当前dom的位置的。

### What is actually happening?
getContainer是false 点击调用modal静态方法无反应

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | @16.x |
| System | mac |
| Browser | Google Chrome 96.0.4664.110 |

---
也许这个是设计就如此？

**Comment by afc163** [comment]
对的，静态方法因为没有 React 上下文，`getContainer={false}` 其实没有意义。
