### ISSUE TITLE
Select 组件设置 listHeight 属性之后，滚动到最下面，很难再往回滚。

### ISSUE THREAD

**Issue by zm8** [ant-design/ant-design#33357]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-dong-fen-ci-antd-4-17-3-forked-egh4m)

### Steps to reproduce
直接滚动条 滚动到最底部。

### What is expected?
滚动到最底部，可以往回滚动。

### What is actually happening?
滚动到最底部，不能往回滚。

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | MacOS Mojave |
| Browser | Chrome 96.0.4664.110 |

---
发现和虚拟滚动的设置有关系，当 virtual 设置为 false 就是好的，这个问题在 window10 和 mac 都会有。

**Comment by PeachScript** [comment]
`listHeight` 写法不对导致的，类型应该是数值。使用数值效果正常：https://codesandbox.io/s/zi-dong-fen-ci-antd-4-17-3-forked-gg8np

**Comment by zm8** [comment]
> `listHeight` 写法不对导致的，类型应该是数值。使用数值效果正常：https://codesandbox.io/s/zi-dong-fen-ci-antd-4-17-3-forked-gg8np

但是如果我要传的单位是rem, 那要怎么处理? 比如  listHeight: '100rem'

**Comment by PeachScript** [comment]
目前不支持其他尺寸单位，虚拟滚动依赖 px 数值做计算
