### ISSUE TITLE
table可选择功能分页后有缓存

### ISSUE THREAD

**Issue by mjn1154477982** [ant-design/ant-design#33366]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/xuan-ze-he-cao-zuo-antd-4-17-4-forked-jg03z?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
随便展开两个可展开行，点击第二页分页，在回到原来的页码

### What is expected?
期望分页后，在返回原来的页码，之前已经展开的行是关闭状态，不缓存

### What is actually happening?
实际结果缓存了之前已经展开的expandedRowKeys

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | mac |
| Browser | chrome新版 |

**Comment by afc163** [comment]
建议自行控制 expandedRowKeys。
