### ISSUE TITLE
Typography.Paragraph组件的省略属性，在页面右键--翻译成中文，点击展开按钮，页面会奔溃

### ISSUE THREAD

**Issue by BelieverAz** [ant-design/ant-design#33360]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/typography-cn/#components-typography-demo-suffix](https://ant.design/components/typography-cn/#components-typography-demo-suffix)

### Steps to reproduce
1.右键--翻译成中文
2.点击展开按钮

### What is expected?
页面不会奔溃

### What is actually happening?
页面奔溃

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome 96.0.4664.110 |

---
业务使用中发现这个问题，同样的官网中例子也存在这个问题

**Comment by afc163** [comment]
这是 Chrome 的机制和 React 有冲突，antd 没什么好办法能解。
