### ISSUE TITLE
table远程拉取数据 rowSelection 翻页后记忆状态不保存

### ISSUE THREAD

**Issue by pxl0510** [ant-design/ant-design#33365]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
https://ant.design/components/table-cn/

### What is expected?
记忆状态保存

### What is actually happening?
记忆状态不保存

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 16 |
| System | table |
| Browser | Chrome |

**Comment by afc163** [comment]
<img width="1068" alt="图片" src="https://user-images.githubusercontent.com/507615/146891561-73e7eb49-d9f1-4a65-a72e-e4344e7229a6.png">
