### ISSUE TITLE
select搜索功能体验优化建议

### ISSUE THREAD

**Issue by wdaglb** [ant-design/ant-design#33376]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
让小白客户更能清晰的使用搜索功能

### What does the proposed API look like?
搜索框不要在input里直接输入，可以在弹出的下拉框顶部输入搜索内容，同时增加搜索按钮，这样客户就不会迷路，我相信很多客户使用上都不知道那有个搜索？

**Comment by PeachScript** [comment]
这是一个比较通用的交互，可以键入文本的时候也会有光标闪烁。

如果担心用户不知道，可以使用 `placeholder` 提示用户；如果你想要的是类似 Select2 的传统交互，可以通过 [`dropdownRender`](https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu) 自定义展开的面板，实现想要的效果。
