### ISSUE TITLE
Tree组件怎么隐藏HTML中默认的title属性

### ISSUE THREAD

**Issue by fidelyiu** [ant-design/ant-design#33375]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为HTML默认的title显示的tooltip显示总是会延迟一段时间，是否可以将默认的title属性可控去掉，然后自己实现tooltip

### What does the proposed API look like?
showTitle: false

**Comment by afc163** [comment]
目前没有办法。

**Comment by jydeng** [comment]
自定义子节点的方式，可以解决默认title属性的问题，不过console会提示。
