### ISSUE TITLE
Tabs 结合 Iframe 使用

### ISSUE THREAD

**Issue by github-gage** [ant-design/ant-design#3337]
请问大家有没有用tabs 结合 iframe 使用的，能否分享下示例！谢谢！

**Comment by afc163** [comment]
尽量不要在这里问这么泛的问题，也不建议做伸手党，这里是来报告问题的地方。

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by github-gage** [comment]
@afc163 

是这样的，以前的管理平台用的是easyui,在easyui 的tabs 里，打开tab 可以传href 地址，这应该也是很多管理系统都这么用。就想了解下在ant 里有没有人这么实现过，或者是实现思路。找了些资料也没有，就只能来这里咨询了！

**Comment by AlbertZheng** [comment]
@github-gage 自己内部搞个状态，当tab切换时触发状态值的变化，在render里根据状态值从某个配置项获得对应的href

**Comment by github-gage** [comment]
@AlbertZheng 主要是需要打开一个新tab 时，如果传入一个url 属性，能在打开的tab 里面渲染url 的页面！
