### ISSUE TITLE
Table分页组件，如果最后一页有1条数据，删除这条数据后组件UI显示当前页为上一页的页码，但没有回调通知开发者及时更新当前页码

### ISSUE THREAD

**Issue by wyjie** [ant-design/ant-design#33374]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-edison-6uq3e?file=/src/App.js)

### Steps to reproduce
1：点击分页切换到第二页， 显示一条数据
2：点击最后一条数据的删除按钮
3：删除成功后，数据-1，页码显示当前页码为1， 但页面无数据

原因：因为setPage未更新，page仍=2， pagination的  【onChange】方法未执行

### What is expected?
期望：onChange应该执行 用于在此时更新正确的页码

### What is actually happening?
 pagination的  【onChange】方法未执行

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.0.2 |
| System | mac 11.6 |
| Browser | chrome  (96.0.4664.110) |

**Comment by afc163** [comment]
应该没修完整，onChange 应该触发一下 https://github.com/ant-design/ant-design/pull/29184

**Comment by 2724635499** [comment]
我来改的试试

**Comment by monologue-web** [comment]
> 看上去 #29184 没修完整，onChange 应该触发一下。
3.X 版本好像也有这问题

**Comment by giscafer** [comment]
v4.22.8 版本源码里边的onChange 去掉了呀

**Comment by ningshunqiang** [comment]
你好，v4.20.7 版本会存在同样问题

**Comment by giscafer** [comment]
> 



> 你好，v4.20.7 版本会存在同样问题

自己代码hack 刷新
