### ISSUE TITLE
menu 组件在边缘情况下的预料外的行为

### ISSUE THREAD

**Issue by WeiShengv99** [ant-design/ant-design#33371]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-17-4-forked-57876?file=/router.tsx)

### Steps to reproduce
1. 折叠侧边栏
2. 切换项目对比和 项目概览。在切换后鼠标移到menu上，子menu open事件不再触发， 不再展开

需要你在切换的时候注意时机，这里使用了动画，大概是在动画中间的时候 移动过去

我不知道发生了什么，以及是否是我使用了错误的打开方式，期待你的回复。🤔

### What is expected?
鼠标移动过去后submenu正常展示出来

### What is actually happening?
submenu并没有展示

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17 |
| System | macos |
| Browser | chrome 96.0.4664.110 |

---
之所以让menu受控，是因为想要在url变化的时候，menu同时变化
采用这种写法是因为  如果不这么判断的话  ，折叠中的menu 会闪烁，因为折叠的时候点击会自动将openKeys置为空
```
 if (collapsed === false) {
      setOpenKeys((oldVal) =>
        uniq([
          ...oldVal,
          ...(routerMatch ?? []).map(
            (matchRoute) => matchRoute.route.path as string
          ),
        ])
      );
    }
```

https://user-images.githubusercontent.com/35689628/146910879-fcbb5d38-64ca-423a-9d08-248e356fb6de.mov

**Comment by PeachScript** [comment]
原因：过渡动画过程中内容区域遮盖 Menu 导致 hover 事件不触发
解法：Menu 加上 z-index，在你的 demo 基础上做了修改：https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-17-4-forked-kvswv

**Comment by WeiShengv99** [comment]
@PeachScript    非常感谢你的解惑，这解决了我的问题。

**Comment by WeiShengv99** [comment]
@PeachScript  但是我这这个demo 里，还是可以复现这个问题。而且又了另外的行为。

**Comment by PeachScript** [comment]
> 展示后指到submenu上还是会消失

看视频的操作，快速移入父级项再快速移入子项会被判定为误触，正常用户不会这么操作；如果觉得不合适可以自行修改 `subMenuCloseDelay` 及 `subMenuOpenDelay` 达到想要的效果，参考 Menu API：https://ant.design/components/menu-cn/#Menu

**Comment by WeiShengv99** [comment]
@PeachScript  但是在视频2里    不展示子菜单的问题还是会出现。在后面 几秒

**Comment by PeachScript** [comment]
@WeiShengv99 无法重现，请提供稳定复现

**Comment by WeiShengv99** [comment]
> @WeiShengv99 无法重现，请提供稳定复现

我修改了我的demo。当你发生case1的误触事件后，很容易复现这个问题

https://user-images.githubusercontent.com/35689628/146921629-7883fc3c-016b-46a4-a967-2f21e84286c2.mov

**Comment by WeiShengv99** [comment]
@PeachScript   和 误触没有关系，

这是你修改后的 demo的 在线网址，你只需要在点击后 用一种适中的速度（不要太快），就可以稳定复现
https://kvswv.csb.app/project-analysis/project-contrast

**Comment by PeachScript** [comment]
> 我修改了我的demo。当你发生case1的误触事件后，很容易复现这个问题

新 demo 链接 + 按照视频的操作仍然无法复现


> 和 误触没有关系，
> 这是你修改后的 demo的 在线网址，你只需要在点击后 用一种适中的速度（不要太快），就可以稳定复现

先利用提到的 API 做调整，例如把 `subMenuCloseDelay` 设置得更长一些

**Comment by WeiShengv99** [comment]
@PeachScript   好吧 ，复现的方式在于点击后用一种比较慢的速度移过去，谢谢大佬的解惑，可能是我打开方式有些问题。

**Comment by WeiShengv99** [comment]
@PeachScript 

我确实不知道应该如何描述这个问题。。。 只能给大佬提供点录像

https://user-images.githubusercontent.com/35689628/146926015-f9392f35-7811-43ac-97b3-1c4a6e7c6d04.mov

**Comment by WeiShengv99** [comment]
@PeachScript   我修改了 路由对应的组件， 增加路由组件的渲染成本后，复现变得更加简单

1. 你需要手动去折叠 menu
2. 然后再去操作这个 demo

很抱歉我有点执着于这个边界case
[demo](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-17-4-forked-57876?file=/router.tsx)

**Comment by PeachScript** [comment]
仍然无法复现，macOS Big Sur + Chrome 96
![cannot_reproduce](https://user-images.githubusercontent.com/5035925/146941077-47761d90-e9d9-4253-806b-f433a6a410b0.gif)

**Comment by WeiShengv99** [comment]
@PeachScript    当路由组件的渲染成本足够大的情况下，我这边基本是必现了。你可以稍微放缓下鼠标移动过去的速度或者再加几个虚拟表格试一试？
