### ISSUE TITLE
react-addons-pure-render-mixin 会导致 antd 对 react 的版本有依赖

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#3338]
现在因为 antd 依赖了 `"react-addons-pure-render-mixin": "^15.0.0"`，然后`react-addons-pure-render-mixin`里写的对 react 的 peerDependencies 是跟它本身一样的版本号。

这样的话目前安装 antd 的时候，npm 默认会安装`react-addons-pure-render-mixin@15.3.2`，也就是说这时候 peerDependencies 里 react 的版本也是 15.3.2。这样如果先前项目使用的 react 低于 15.3.2 的版本的话 npm 就会报错说 “peer invalid”，不过这时候代码是可以跑的。但是因为我们现在项目里需要`npm shrinkwrap`，这个时候因为之前的错误，npm 就不让你锁定依赖了。

### 为什么不把 react 升到最新版？

因为 react@15.2.0 有个[不兼容的改动](https://github.com/facebook/react/pull/6800)，所以暂时不能把 react 升到最新版。

### 为什么不自己在项目的 package.json 写一个低版本的 `react-addons-pure-render-mixin`依赖？

因为 antd 本身是没有依赖特定的 react 版本的，如果需要使用低版本 react 的用户自己去写`react-addons-pure-render-mixin`的依赖话，这算是一个坑。

@benjycui @afc163 有什么想法吗？

**Comment by afc163** [comment]
老问题了，用 npm3 即可：https://github.com/ant-design/ant-design/issues/2030

**Comment by yesmeck** [comment]
我用的是 npm3，其实不管 npm2 还是 npm3 都会有问题，npm2 会默认安装 peerDependencies 导致装两个不同版本的 react，npm3 默认不安装 peerDependencies 会导致版本不匹配 “peer invalid”。

按[这里的说法](https://github.com/ant-design/ant-design/issues/2030#issuecomment-226483471) , 一种是升级 react，一种是用 npm3，但是因为 antd 现在是没有特点依赖的 react 的版本的，如果需要依赖最新版本的 react 的话我觉得应该在 peerDependencies 写清楚，但是我觉得只为了`react-addons-pure-render-mixin`就要求依赖最新版本的 react 的话不值得。

**Comment by afc163** [comment]
确实没考虑 npm shrinkwrap，要不把 react-addons-pure-render-mixin 换成其他实现好了。例如：http://npmjs.com/shallowequal

**Comment by yesmeck** [comment]
另外有个点就是我觉得如果组件接受 `children` 的话不应该用 `shouldComponentUpdate` 去优化，因为我们并不知道传进来的 `children` 是不是 `pure` 的，而如果 `children` 用了 `context` 的话，也会让 `context` 变化的时候 `children` 无法重新 `render`。

**Comment by benjycui** [comment]
`shouldComponentUpdate` 会接收 `nextContext` 的： https://github.com/facebook/react/blob/84f8df1f891285b8ff85880631d7882c30b2ced3/src/isomorphic/classic/class/ReactClass.js#L223-L243

**Comment by benjycui** [comment]
然后之前好像是使用过 shallowEqual 的，cc @superRaytin 

不过如果真的要性能优化，就要自己很认真的梳理 shouldComponentUdpate 了。。。

**Comment by yesmeck** [comment]
> shouldComponentUpdate 会接收 nextContext 的

是的，但是因为 antd 的组件没有`contextProps`的，`shouldComponentUpdate`的第三个参数会是空的。https://github.com/facebook/react/issues/2517。

**Comment by yesmeck** [comment]
现在就有依赖 `shallowequal` https://github.com/ant-design/ant-design/blob/master/package.json#L76

**Comment by yesmeck** [comment]
react-component 那边也有一些依赖 react-addons-pure-render-mixin 的 😢

**Comment by yesmeck** [comment]
原来之前处理过这样的问题 https://github.com/react-component/util/issues/5 ，不过又被移除了 https://github.com/react-component/util/commit/0ccfd3d492bbcc04edc8f20c41f6c3c59913a386

**Comment by benjycui** [comment]
> 然后之前好像是使用过 shallowEqual 的，cc @superRaytin

说的就是这事，细节我忘了。

**Comment by yesmeck** [comment]
是这个原因 https://github.com/ant-design/ant-design/issues/2030#issuecomment-225789368 吧？

**Comment by benjycui** [comment]
这个问题或者可以通过把版本依赖改成这样解决？

```json
"react-addons-pure-render-mixin": "^15.0.0 || ^0.14.0",
```

See: https://github.com/react-component/select/blob/master/package.json#L59

**Comment by benjycui** [comment]
`2.1.0` 不急着解决这个问题，先测试已有的方法，省的来来回回的改。。

解决后如果急用，可以发个 patch。

**Comment by yesmeck** [comment]
> "react-addons-pure-render-mixin": "^15.0.0 || ^0.14.0",

这样写没用的，npm 会安装最新的符合依赖要求的版本。现在的问题不是有版本冲突，而是依赖 `react-addons-pure-render-mixin` 导致 `antd` 对 `react` 的版本也有依赖。

**Comment by benjycui** [comment]
这样写的话，可以先安装 `react-addons-pure-render-mixin` 再安装 `antd`。。。就没这个问题了。

**Comment by yesmeck** [comment]
@benjycui 见我上面第二个问题。。。。

**Comment by superRaytin** [comment]
可以用 shallowEqual，之前没有使用是因为看到 rc-util 提供了这个方法  @benjycui

**Comment by yesmeck** [comment]
是不是把 rc-util 里的 PureRenderMixin revert 回来呢？

**Comment by benjycui** [comment]
还是 revert 回来比较好吧，毕竟 `PureRenderMixin` 并没有多大的代码

**Comment by yesmeck** [comment]
Close as 2.2.0 has released.
