### ISSUE TITLE
Show Notification on demand

### ISSUE THREAD

**Issue by Angelfire** [ant-design/ant-design#33389]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be possible to show the Notification component on demand not only when a specific button is clicked 

### What does the proposed API look like?
```js
 <Notification
    description={message}
    type={type}
    key='key-lol'
    message={...}
    placement={...}
/>

```

**Comment by afc163** [comment]
Just bind onClick event to the specificed button.
