### ISSUE TITLE
虚拟列表typescript版本报错：  Type '(rawData: object[], { scrollbarSize, ref, onScroll }: any) => JSX.Element' is not assignable to type '{ wrapper?: CustomizeComponent | undefined; row?: CustomizeComponent | undefined; cell?: CustomizeComponent | undefined; } | CustomizeScrollBody<...> | undefined'

### ISSUE THREAD

**Issue by zmhweb** [ant-design/ant-design#33385]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/zmhweb/antd-demo-ts.git](https://github.com/zmhweb/antd-demo-ts.git)

### Steps to reproduce
启动后就报错了

### What is expected?
正常呈现虚拟列表

### What is actually happening?
无法正常使用虚拟列表

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

**Comment by resatyildiz** [comment]
Hi, I had this error too. I did look my project's package versions and dependencies. I changed my project's package versions and it is fix.. I could't start your project's packages because I haven't got pc now, make sure your project's packages versions are correct until I can look into it, and try again.

Happy Codes

**Comment by Ondersahinn** [comment]
can you upgrade version 5.0.0  of react-scripts

**Comment by zmhweb** [comment]
> can you upgrade version 5.0.0 of react-scripts
I upgrade react-scripts，An error：
![image](https://user-images.githubusercontent.com/16442336/147172767-81b194dc-028a-4543-8c1e-1d57e90e6c97.png)

**Comment by zmhweb** [comment]
> Hi, I had this error too. I did look my project's package versions and dependencies. I changed my project's package versions and it is fix.. I could't start your project's packages because I haven't got pc now, make sure your project's packages versions are correct until I can look into it, and try again.
> 
> Happy Codes

Thanks，waiting...

**Comment by zmhweb** [comment]
> Hi, I had this error too. I did look my project's package versions and dependencies. I changed my project's package versions and it is fix.. I could't start your project's packages because I haven't got pc now, make sure your project's packages versions are correct until I can look into it, and try again.
> 
> Happy Codes

I upgrade @types/react and @types/react-dom,an error change :
![image](https://user-images.githubusercontent.com/16442336/147182780-fb1e4fc8-9b6c-44b8-a3d9-d970520c35cb.png)

**Comment by Ondersahinn** [comment]
You can follow https://ant.design/docs/react/use-in-typescript document to make antd customize theme but you need to downgrade to react-scripts version 4. Apart from that, it says on its page that you can set it with craco, and if the craco version is not 5 craco-less 1.17, you will get the same error. These documents are not up-to-date, I am changing the colors as below, I cannot use other less variables.

import {ConfigProvider } from 'antd';

  const customColors = {
     primaryColor: '#ff18ba',
     errorColor: '#ff4d4f',
     warningColor: '#faad14',
     successColor: '#52c41a',
     infoColor: '#1890ff',
   };
     ConfigProvider.config({
       theme: customColors,
     });

**Comment by zmhweb** [comment]
> You can follow https://ant.design/docs/react/use-in-typescript document to make antd customize theme but you need to downgrade to react-scripts version 4. Apart from that, it says on its page that you can set it with craco, and if the craco version is not 5 craco-less 1.17, you will get the same error. These documents are not up-to-date, I am changing the colors as below, I cannot use other less variables.
> 
> import {ConfigProvider } from 'antd';
> 
> const customColors = { primaryColor: '#ff18ba', errorColor: '#ff4d4f', warningColor: '#faad14', successColor: '#52c41a', infoColor: '#1890ff', }; ConfigProvider.config({ theme: customColors, });

I have solved。
add “readonly“ before the function renderVirtualList‘s  rawData
![image](https://user-images.githubusercontent.com/16442336/147199505-2f690a49-e325-42d1-97f7-e0f365ac6d05.png)
