### ISSUE TITLE
Upgrade from 3 to 4   'Select' Behavior problem

### ISSUE THREAD

**Issue by liangshen001** [ant-design/ant-design#33386]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
Select A text in ‘https://ant.design/components/select-cn/’ and click on any select 
在https://ant.design/components/select-cn/页面中任意选择一段文字，然后点页面中的一个select例子  （这在v3的官网中是没问题的）

### What is expected?
选择的文本还在选择状态

### What is actually happening?
选择的文本已经不在选择状态

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 16.9.0 |
| System | OS X |
| Browser | google 96 |

**Comment by afc163** [comment]
『选择的文本还在选择状态』这个行为很奇怪，焦点已经切换，不应该还被选中。

**Comment by liangshen001** [comment]
但是v3中是这样的行为   在v4版本中我该如何适配那

**Comment by liangshen001** [comment]
> 『选择的文本还在选择状态』这个行为很奇怪，焦点已经切换，不应该还被选中。

因为这会导致开发的富文本编辑器配置项失效

**Comment by liangshen001** [comment]
> 『选择的文本还在选择状态』这个行为很奇怪，焦点已经切换，不应该还被选中。

请问有办法可以解决 这个问题吗
