### ISSUE TITLE
Popover 组件 包裹 Button 组件的时候，placement 无效

### ISSUE THREAD

**Issue by yangxiang-dxl** [ant-design/ant-design#33398]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-mahavira-7m5j9?file=/src/App.js)

### Steps to reproduce
正常使用

### What is expected?
placement生效

### What is actually happening?
placement无效

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome 96.0.4664.110 |

---
        getPopupContainer={(triggerNode) => triggerNode} 把挂载的 node 一下可以了，目前只发现Popover 组件 包裹antd Button 组件的时候会有这个问题，换成其他的就没问题

**Comment by yangxiang-dxl** [comment]
getPopupContainer={(triggerNode) => triggerNode.parentNode} 更改挂载节点后正常

**Comment by afc163** [comment]
如何重现？你给的例子看上去符合预期，删除 `getPopupContainer={(triggerNode) => triggerNode.parentNode}` 也没啥区别。

**Comment by yangxiang-dxl** [comment]
> 如何重现？你给的例子看上去符合预期，删除 `getPopupContainer={(triggerNode) => triggerNode.parentNode}` 也没啥区别。

你仔细看我写的placement = 'topRight',而显示的位置却是 bottomRight

**Comment by afc163** [comment]
上面空间不够了，会自动换到下方。

**Comment by yangxiang-dxl** [comment]
> 上面空间不够了，会自动换到下方。

好的了解了，谢谢您了
