### ISSUE TITLE
ant table: column render function invoked when hover table row

### ISSUE THREAD

**Issue by tungphien** [ant-design/ant-design#33393]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-antd-4-17-4-forked-xwfhl)

### Steps to reproduce
add console.log to render function, open console log and mouse move on table row, we will see data logged

### What is expected?
no re-render column data when hover

### What is actually happening?
re-render data of column

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 16.12.0 |
| System | windows |
| Browser | google chrome |

**Comment by afc163** [comment]
Duplicate of #33342

**Comment by afc163** [comment]
Still exists in antd 4.18.0 https://github.com/ant-design/ant-design/issues/33342#issuecomment-1002369248

**Comment by Madejczyk** [comment]
Issue has been added by: https://github.com/react-component/table/commit/2d0d403642263fdfe41e0dae3cda8d16f665eb35

**Comment by afc163** [comment]
Trace #32979
