### ISSUE TITLE
Tree & SelectTree should add defaultProps

### ISSUE THREAD

**Issue by lkmodules** [ant-design/ant-design#33396]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
like this: defaultProps: { children: 'children', label: 'label' }. so we should not construct data recursively every time.
现在每次使用树组件，必须去递归构造数据，组件才可以使用。因为内部调用的key是写死的。如果数据量较大，对前端性能也有比较大的挑战。

### What does the proposed API look like?
defaultProps: { children: 'children', label: 'label' , disabled: (treeData, node) => { return ... }}
like ElementUI Tree props.

**Comment by afc163** [comment]
Try `fieldNames`
