### ISSUE TITLE
antd  RangePicker在mode为['month', 'month']时存在bug，无法选择日期

### ISSUE THREAD

**Issue by HEJIN2016** [ant-design/ant-design#33391]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/HEJIN2016/antd-bug](https://github.com/HEJIN2016/antd-bug)

### Steps to reproduce
```
<RangePicker style={{ width: 600 }} format='YYYY-MM' mode={['month', 'month']} size='small' />
```

### What is expected?
可以正确选择日期

### What is actually happening?
mode={['month', 'month']} 时，无法选择日期，选择了日期但是并没有生效
![image](https://user-images.githubusercontent.com/25821307/147198166-bd88491a-f8a9-4fb3-9b60-fe383a8996f9.png)

| Environment | Info |
|---|---|
| antd | 4.16.13 |
| React | 17.0.1 |
| System | macos |
| Browser | 版本 96.0.4664.110（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E6%8C%87%E5%AE%9A%E4%BA%86-DatePicker/RangePicker-%E7%9A%84-mode-%E5%B1%9E%E6%80%A7%E5%90%8E%EF%BC%8C%E7%82%B9%E5%87%BB%E5%90%8E%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E5%B9%B4%E4%BB%BD/%E6%9C%88%E4%BB%BD%EF%BC%9F
