### ISSUE TITLE
Tabs 组件关闭TabPane到最后一个时不能显示最后一个TabPane

### ISSUE THREAD

**Issue by yimi8126** [ant-design/ant-design#3339]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:mac
- 浏览器及其版本:

#### 您做了什么？

使用可关闭的editable-card，其中一个TabPane为固定的，其他为动态的，当关闭所有动态的TabPane时不能跳转到固定的哪个Tabpane上
#### 您期待的结果是：
跳转到最后一个固定的TabPane上

#### 实际上的结果是：
显示空白页面

#### 可重现的在线演示
http://codepen.io/yimi8126/pen/zKWoVN?editors=0011

点击动态TabPane，关闭动态TabPane，页面显示空白

**Comment by ddcat1115** [comment]
需要用受控模式，增加 onChange 及 activeKey 属性，在 remove 函数中判断设置 activeKey，仔细看下 

https://ant.design/components/tabs/#components-tabs-demo-editable-card
