### ISSUE TITLE
修改 pageSize 当前页最大值问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#334]
假设当前 100 条数据分十页，当前页为 第 10 页。

设置 showSizeChanger，修改 pageSize 为 40，变为 3 页，当前页（10）失效。

在溢出时，应该修正为最后一页。

**Comment by ibigbug** [comment]
https://github.com/react-component/pagination/commit/9b14a6e571fee4c6519c99a93c830e24dd3e1064
