### ISSUE TITLE
antd官网 upload组件的例子消失不显示

### ISSUE THREAD

**Issue by nudlen** [ant-design/ant-design#33403]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
在看官网教程的upload组件中关于根据上传文件格式改变icon的例子，并上传了本地一些不重要的文件测试了一下，然后不小心后退了网页，等回到网页时，该例子就消失了

### What is expected?
该例子重新显示

### What is actually happening?
例子消失

| Environment | Info |
|---|---|
| antd | undefined |
| React | / |
| System | macox |
| Browser | chrome |

**Comment by MadCcc** [comment]
根据格式修改icon的是一个调试用例，是不是操作之后调试用例关闭了？
可以的话提供一下录屏是最好的

**Comment by nudlen** [comment]
确实，点击了调试用例之后忘记了，所以当时刷新以后找不到，已解决
