### ISSUE TITLE
validator校验和required校验会冲突

### ISSUE THREAD

**Issue by poyiding** [ant-design/ant-design#33409]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-4-forked-xq0t6?file=/index.js)

### Steps to reproduce
1. 直接点提交：不会触发 required校验
2. 触发validator 校验时，提示的是 message信息，而不是reject(error)

### What is expected?
1. 直接点提会触发 required 必填校验
2. 触发validator 校验时提示 reject(error) 信息

### What is actually happening?
1. 直接点提交：不会触发 required校验
2. 触发validator 校验时，提示的是 message信息，而不是reject(error)

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.14 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-4-forked-kgnyw?file=/index.js
建议按照文档里的，将 required 和 validator 分开可以解决这个问题
