### ISSUE TITLE
Table组件在chrome正常在firefox下报错

### ISSUE THREAD

**Issue by safeblood** [ant-design/ant-design#33413]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
直接访问示例链接即可

### What is expected?
正常显示

### What is actually happening?
显示空白

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.0.2 |
| System | win10 |
| Browser | firefox 52.9.0 |

**Comment by afc163** [comment]
Firefox 版本太老了，不再支持，请更新。
