### ISSUE TITLE
TreeSelect中fieldNames文档有误

### ISSUE THREAD

**Issue by TomatoesMan** [ant-design/ant-design#33412]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
无

### What is expected?
fieldNames中定义的类型为{
    value?: string;
    label?: string;
    children?: string;
}

### What is actually happening?
文档中标注的是{ label: label, key: key, children: children }

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 16.14.0 |
| System | macos |
| Browser | 谷歌 |

**Comment by 1247748612** [comment]
还没合并 https://github.com/ant-design/ant-design/pull/33241#issue-1075591960
