### ISSUE TITLE
Incorrect types for DatePicker

### ISSUE THREAD

**Issue by artiii** [ant-design/ant-design#33417]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0oj2e?file=/index.tsx)

### Steps to reproduce
import React, { forwardRef } from 'react'
import { DatePicker as AntDatePicker, DatePickerProps as AntDatePickerProps } from 'antd'
import cl from 'classnames'

import styles from './styles.module.scss'

type DatePickerProps = AntDatePickerProps

const DatePicker = forwardRef<AntDatePicker, DatePickerProps>(({ className, ...props }, ref) => {
	return <AntDatePicker {...props} className={cl(styles.datePicker, className)} ref={ref} />
})

export default DatePicker

### What is expected?
no any TS errors 

### What is actually happening?
typescript(4.1.2)  return the error: TS2749: 'AntDatePicker' refers to a value, but is being used as a type here. Did you mean 'typeof AntDatePicker'?

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 17.0.2 |
| System | - |
| Browser | - |

**Comment by afc163** [comment]
Did you mean 'typeof AntDatePicker'?

**Comment by afc163** [comment]
```diff
- const DatePicker = forwardRef<AntDatePicker, DatePickerProps>(
+ const DatePicker = forwardRef<typeof AntDatePicker, DatePickerProps>(
```

**Comment by artiii** [comment]
@afc163 
![Uploading Screenshot 2021-12-27 at 12.17.30.png…]()

**Comment by afc163** [comment]
PR is welcome~
