### ISSUE TITLE
TimePicker.RangePicker  disabledRangeTime不会被执行，无法做到区分disabled开始和结束时间

### ISSUE THREAD

**Issue by nuancheng** [ant-design/ant-design#33425]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bu-ke-xuan-ze-ri-qi-he-shi-jian-antd-4-17-2-forked-fublu?file=/index.js)

### Steps to reproduce
选择时间

### What is expected?
disabledRangeTime会被执行，或者提供额外的能够区分disabled开始和结束时间的方法

### What is actually happening?
disabledRangeTime不会被执行，无法做到区分disabled开始和结束时间

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.0.1 |
| System | macOS 10.15.7 (19H2) |
| Browser | chrome  版本 86.0.4240.111（正式版本） (x86_64) |

---
disabledHours disabledMinutes disabledSeconds 三个方法无法获取当前是开始时间还是结束时间！

**Comment by afc163** [comment]
确实没支持，这个 API 需要重新看看怎么设计比较好，https://github.com/ant-design/ant-design/issues/22937 可能是一个方案。

**Comment by zombieJ** [comment]
> 确实没支持，这个 API 需要重新看看怎么设计比较好，#22937 可能是一个方案。

看了一圈 RangePicker 的 API，这个应该是合理的。

**Comment by afc163** [comment]
> 看了一圈 RangePicker 的 API，这个应该是合理的。

这个需求也是合理的。

**Comment by zombieJ** [comment]
下个版本废弃零散的 `disabledHours` `disabledMinutes` `disabledSeconds`，将 TimePicker API 改由 `disabledTime` 统一处理。接口同 RangePicker。
