### ISSUE TITLE
table列宽只配置一部分的时候，缩小浏览器可视区，未配置列宽的列会消失不可见

### ISSUE THREAD

**Issue by dqlpm163** [ant-design/ant-design#33426]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gl33t?file=/index.js)

### Steps to reproduce
一共有五列，收窄左侧代码编辑栏可见前两列未配置列宽的列，
拉宽左侧代码栏，右侧宽度小时，前两列消失不可见

### What is expected?
显示全部列，无论配没配置宽度

### What is actually happening?
没配置宽度的列在可视区很窄时消失了

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 16.13.1 |
| System | window 10 |
| Browser | chrome 96.0.4664.93 |

**Comment by afc163** [comment]
这是预期行为，宽度写死的时候，会优先缩小未配置宽度的列。

当然也可以配置 `tableLayout="auto"`，不过这样会让 ellipsis 失效。
