### ISSUE TITLE
Cascader级联选择下拉时，无法自动计算左右位置，导致出现临界位置时，部分内容被隐藏，页面出现滚动条

### ISSUE THREAD

**Issue by codeManage** [ant-design/ant-design#33439]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mo-ren-zhi-antd-4-18-0-forked-pgsn4?file=/index.js)

### Steps to reproduce
拖拽下位置

### What is expected?
自动计算下拉位置，左边出现临界时，靠左对齐，右边出现临界时靠右对齐

### What is actually happening?
没有自动计算，导致页面出现滚动条，部分下拉内容被隐藏

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome版本 96.0.4664.110（正式版本） (x86_64) |

---
历史版本是有这个功能的，4.16版本还是可以计算的

**Comment by afc163** [comment]
Duplicate of #33273
