### ISSUE TITLE
Dropdown button destroyPopupOnHide prop not working

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#33433]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/button-with-dropdown-menu-antd-4-18-0-forked-43lys?file=/index.js)

### Steps to reproduce
Click the popup to open and click again to close, look up the dom tree, the div created by popup will no be cleared.
Also the browser shows a console warning for the prop.

Warning: React does not recognize the `destroyPopupOnHide` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `destroypopuponhide` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### What is expected?
The div created by the popup to be cleared and the browser to not throw any warnings.

### What is actually happening?
The div is not being cleared and the browser is throwing warnings.

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | react: 17.0.2 |
| System | Windows 10 |
| Browser | Brave |

**Comment by ZzGGitter** [comment]
@afc163 Dropdown.Button 并未提供destroyPopupOnHide这个API功能是否当作一个feature而不是一个Bug来做
Dropdown.Button does not provide the destroyPopupOnHide API function. Do you treat this issue as a feature instead of a bug?
