### ISSUE TITLE
tree-select 组件，可勾选状态下，勾选框消失

### ISSUE THREAD

**Issue by nuancheng** [ant-design/ant-design#33447]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/htd24)

### Steps to reproduce
点开看

### What is expected?
有勾选框

### What is actually happening?
无勾选框

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.1 |
| System | macOS 10.15.7 (19H2) |
| Browser | chrome  版本 86.0.4240.111（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
重装一下依赖哈~
