### ISSUE TITLE
vite build 报错

### ISSUE THREAD

**Issue by Lym-007** [ant-design/ant-design#33449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://vitejs.cn/plugins/#official-plugins](https://vitejs.cn/plugins/#official-plugins)

### Steps to reproduce
vite build

### What is expected?
打包成功

### What is actually happening?
node_modules/@ant-design/pro-field/lib/components/Select/index.d.ts:39:51 - error TS2694: Namespace '"C:/Users/Administrator/Desktop/workspace/\u4EFB\u52A1\u7BA1\u7406/vite-project/node_modules/rc-select/lib/interface"' has no exported member 'OptionsType'.

39 }) => [boolean, import("rc-select/lib/interface").OptionsType | undefined, (keyWord?: string | undefined) => void, () => void];
                                                     ~~~~~~~~~~~

node_modules/rc-cascader/lib/Cascader.d.ts:66:18 - error TS2430: Interface 'SingleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.
  Types of property 'onChange' are incompatible.
    Type 'OnSingleChange<OptionType> | undefined' is not assignable to type '((value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void) | undefined'.
      Type 'OnSingleChange<OptionType>' is not assignable to type '(value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ValueType' is not assignable to type 'SingleValueType'.
            Type 'SingleValueType[]' is not assignable to type '(string | number)[]'.
              Type 'SingleValueType' is not assignable to type 'string | number'.
                Type '(string | number)[]' is not assignable to type 'string'.

66 export interface SingleCascaderProps<OptionType extends BaseOptionType = DefaultOptionType> extends BaseCascaderProps<OptionType> {
                    ~~~~~~~~~~~~~~~~~~~

node_modules/rc-cascader/lib/Cascader.d.ts:70:18 - error TS2430: Interface 'MultipleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.
  Types of property 'onChange' are incompatible.
    Type 'OnMultipleChange<OptionType> | undefined' is not assignable to type '((value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void) | undefined'.
      Type 'OnMultipleChange<OptionType>' is not assignable to type '(value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ValueType' is not assignable to type 'SingleValueType[]'.
            Type 'SingleValueType' is not assignable to type 'SingleValueType[]'.
              Type 'string | number' is not assignable to type 'SingleValueType'.
                Type 'string' is not assignable to type '(string | number)[]'.

70 export interface MultipleCascaderProps<OptionType extends BaseOptionType = DefaultOptionType> extends BaseCascaderProps<OptionType> {

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.0 |
| System | windows 10 |
| Browser | google |

**Comment by nos-nart** [comment]
I'm encountering the same issue when trying to deploy vite + antd to vercel
Errors show after run `tsc & vite build`

**Comment by jordansexton** [comment]
Having the same issue

**4.16.13** building the project with `tsc` works

**4.17.4** has this error when running `tsc`:
```
../../../node_modules/rc-cascader/lib/Cascader.d.ts:3:32 - error TS2307: Cannot find module 'rc-select/lib/generate' or its corresponding type declarations.

3 import type { Placement } from 'rc-select/lib/generate';
```

4.18.0 has this error when running `tsc`:
```
../../../node_modules/rc-cascader/lib/Cascader.d.ts:66:18 - error TS2430: Interface 'SingleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.
  Types of property 'onChange' are incompatible.
    Type 'OnSingleChange<OptionType> | undefined' is not assignable to type '((value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void) | undefined'.
      Type 'OnSingleChange<OptionType>' is not assignable to type '(value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ValueType' is not assignable to type 'SingleValueType'.
            Type 'SingleValueType[]' is not assignable to type '(string | number)[]'.
              Type 'SingleValueType' is not assignable to type 'string | number'.
                Type '(string | number)[]' is not assignable to type 'string'.

66 export interface SingleCascaderProps<OptionType extends BaseOptionType = DefaultOptionType> extends BaseCascaderProps<OptionType> {
                    ~~~~~~~~~~~~~~~~~~~

../../../node_modules/rc-cascader/lib/Cascader.d.ts:70:18 - error TS2430: Interface 'MultipleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.
  Types of property 'onChange' are incompatible.
    Type 'OnMultipleChange<OptionType> | undefined' is not assignable to type '((value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void) | undefined'.
      Type 'OnMultipleChange<OptionType>' is not assignable to type '(value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ValueType' is not assignable to type 'SingleValueType[]'.
            Type 'SingleValueType' is not assignable to type 'SingleValueType[]'.
              Type 'string | number' is not assignable to type 'SingleValueType'.
                Type 'string' is not assignable to type '(string | number)[]'.

70 export interface MultipleCascaderProps<OptionType extends BaseOptionType = DefaultOptionType> extends BaseCascaderProps<OptionType> {
                    ~~~~~~~~~~~~~~~~~~~~~
```

Looks like the issue is broken types for a dependency: https://github.com/ant-design/ant-design/blob/c6188fd388cf9c08a1ac4c0944a7c8cb6fe7c2b2/package.json#L124

Related: https://github.com/ant-design/ant-design/pull/33188, https://github.com/ant-design/ant-design/issues/33153, https://github.com/ant-design/ant-design/issues/33203

**Comment by tibic** [comment]
node_modules/rc-cascader/lib/Cascader.d.ts:66:18 - error TS2430: Interface 'SingleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.

**Comment by dreammaker7** [comment]
我在4.17.2使用yarn build的时候也抛出了上面的Cascader类型继承错误，回滚到4.17.1的时候构建成功了，是否跟这笔修改有关系？[#33008 ](url)

**Comment by devcui** [comment]
```
node_modules/rc-cascader/lib/Cascader.d.ts:66:18 - error TS2430: Interface 'SingleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.
  Types of property 'onChange' are incompatible.
    Type 'OnSingleChange<OptionType> | undefined' is not assignable to type '((value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void) | undefined'.
      Type 'OnSingleChange<OptionType>' is not assignable to type '(value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ValueType' is not assignable to type 'SingleValueType'.
            Type 'SingleValueType[]' is not assignable to type '(string | number)[]'.
              Type 'SingleValueType' is not assignable to type 'string | number'.
                Type '(string | number)[]' is not assignable to type 'string'.

66 export interface SingleCascaderProps<OptionType extends BaseOptionType = DefaultOptionType> extends BaseCascaderProps<OptionType> {
                    ~~~~~~~~~~~~~~~~~~~

node_modules/rc-cascader/lib/Cascader.d.ts:70:18 - error TS2430: Interface 'MultipleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.
  Types of property 'onChange' are incompatible.
    Type 'OnMultipleChange<OptionType> | undefined' is not assignable to type '((value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void) | undefined'.
      Type 'OnMultipleChange<OptionType>' is not assignable to type '(value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ValueType' is not assignable to type 'SingleValueType[]'.
            Type 'SingleValueType' is not assignable to type 'SingleValueType[]'.
              Type 'string | number' is not assignable to type 'SingleValueType'.
                Type 'string' is not assignable to type '(string | number)[]'.

70 export interface MultipleCascaderProps<OptionType extends BaseOptionType = DefaultOptionType> extends BaseCascaderProps<OptionType> {
                    ~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by devcui** [comment]
多半是 rc-cascader 的 typing.d 没改好，我看3.0.0-alpha.6 last publish 是 21 hours ago https://github.com/ant-design/ant-design/issues/33449#issuecomment-1002456760 降级可以搞定，降级以后 rc-cascader 的依赖为2.1.5

**Comment by delaprada** [comment]
同遇到这个问题，是 rc-cascader 的版本问题，希望能尽快修复～

**Comment by afc163** [comment]
麻烦各位给个重现，我们本地没有重现出问题。https://codesandbox.io/

**Comment by gafish** [comment]
在4.17.4版本时，build成功，升到4.18.2就报跟他们一样的错误

**Comment by GongJS** [comment]
> 4.17.4

请问 node 版本是多少？

**Comment by 2516734343** [comment]
我升级到了4.18.0后报同样的错误，又降级到4.17.4，发现树拖拽图标无效了，还会报错，降级到4.17.1，依然是这样的问题。
ERROR in /xxx/node_modules/rc-cascader/lib/Cascader.d.ts(3,15):
TS2614: Module '"/xxx/node_modules/rc-select/lib/generate"' has no exported member 'Placement'. Did you mean to use 'import Placement from ".xxx/node_modules/rc-select/lib/generate"' instead?

**Comment by zjfjiayou** [comment]
4.18.2依然存在问题 和@devcui一样

**Comment by abdeldjalilhachimi** [comment]
Just install the latest version of `antd`  `^4.18.5,`  it works for me
