### ISSUE TITLE
TextArea 设置 autoSize 抖动

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#33450]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-qgbdd4](https://stackblitz.com/edit/react-qgbdd4)

### Steps to reproduce
-

### What is expected?
不抖动

### What is actually happening?
抖动

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
没重现出来。

**Comment by crazyair** [comment]
> 没重现出来。

更新了下 demo，加了刷新按钮，点击刷新，Textarea 高度会闪一下

**Comment by afc163** [comment]
看看是不是和 https://github.com/react-component/textarea/pull/13 有关。

**Comment by losgif** [comment]
测试过，这个问题在0.3.6版本就已经有了 @afc163 
我试着定位下问题先。

[0.3.5](https://codesandbox.io/s/rc-textarea-0-3-5-khuzs)
[0.3.6](https://codesandbox.io/s/rc-textarea-0-3-6-efk1b)
[0.3.7](https://codesandbox.io/s/rc-textarea-0-3-7-d90tw)
