### ISSUE TITLE
从 4.17.0 升级到 4.18.0 后，树形数据展示 hover 高亮异常

### ISSUE THREAD

**Issue by wyx1818** [ant-design/ant-design#33453]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/table-cn/#components-table-demo-tree-data](https://ant-design.gitee.io/components/table-cn/#components-table-demo-tree-data)

### Steps to reproduce
切换到树形展示，展开树，鼠标移到红色上，绿色也高亮
![image](https://user-images.githubusercontent.com/31715036/147557277-a159bb9b-08d6-422d-a06e-08fa768d99f2.png)

### What is expected?
只高亮选中行

### What is actually happening?
从 4.17.0 升级到 4.18.0 后出现的，树展开的时候

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17 |
| System | macOS 12 |
| Browser | Chrome 96 |

**Comment by tulies** [comment]
我也出现里 的确有问题。

**Comment by ZzGGitter** [comment]
选择第一个子元素的hover特效和第三个也有差别

**Comment by ZzGGitter** [comment]
大概知道怎么做了，因为数据拍平的时候renderIndex导致子表中的Cell index分配有问题，需要时间找个好方案。占个坑hh

**Comment by LongHaoo** [comment]
@zombieJ 现在有个问题，如果把index 从“record所在的index”修改成 ”当前拍平数组的index“，此时可以解决hover问题，但是colum - render(value, record, index) 中的index就会取到”当前拍平数组的index“，需要增加新的key去承载着个hover Index吗？

**Comment by LongHaoo** [comment]
solve it in the [react-component/selct issue#729](https://github.com/react-component/table/pull/729)
