### ISSUE TITLE
使用了jss 的项目，该如何使用antd？现在引入页面就加载不出来

### ISSUE THREAD

**Issue by LiangLuDeng** [ant-design/ant-design#33468]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-jss-playground-forked-jzezr)

### Steps to reproduce
引入antd

### What is actually happening?
是否可以在jss写法中，兼容使用

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 16.3.2 |
| System | 10 |
| Browser | Google Chrome95.0.4638.54 |

**Comment by afc163** [comment]
需要引入 antd.css 或者 antd.less 才有样式。
