### ISSUE TITLE
Input设置value=0，使用suffix会报错

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#33467]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-18-0-forked-icoqm?file=/index.js)

### Steps to reproduce
Input设置value=0，使用suffix会报错

### What is expected?
Input设置value=0，可以正常使用suffix参数

### What is actually happening?
Input设置value=0，使用suffix会报错

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.2 |
| System | window 10 |
| Browser | chrome 94.0.4606.81 |

**Comment by WenQiang47199** [comment]
value类型改成 string就好了
` <Input
    value={'0'}
    type="number"
    placeholder="Basic usage"
    suffix={<span>111</span>}
  />`
```

**Comment by bihongbin3027** [comment]
> 值类型改成字符串就好了 ` <Input value={'0'} type="number" placeholder="Basic usage" suffix={<span>111</span>} />`

我目前也是暂时改为stirng类型了，不过这个应该是一个问题吧，通过改值的类型，感觉没有解决根本问题

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/releases/tag/4.18.1

**Comment by JuSanZhi** [comment]
![image](https://user-images.githubusercontent.com/24559368/148210142-69c8d4ea-ad10-45ec-8eca-788add84bf6b.png)
同样遇到这样的问题，请问几时修复好
![image](https://user-images.githubusercontent.com/24559368/148210216-b37fdfef-efe7-4a58-8a67-214b64cf3a1f.png)

**Comment by bihongbin3027** [comment]
> 

已经修复了

**Comment by bihongbin3027** [comment]
@JuSanZhi 已经修复了

**Comment by JuSanZhi** [comment]
> 

是需要更新最新版本么

**Comment by bihongbin3027** [comment]
@JuSanZhi 是的 更新一下就好

**Comment by JuSanZhi** [comment]
> @JuSanZhi 已经修复了

是需要更新最新版本么，而不是把value 改成string 哦
