### ISSUE TITLE
魅族和oppo手机不显示返回顶部

### ISSUE THREAD

**Issue by fivefog** [ant-design/ant-design#33461]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/back-top-cn/](https://ant.design/components/back-top-cn/)

### Steps to reproduce
<BackTop />

### What is expected?
期待大众手机能返回顶部

### What is actually happening?
魅族X8 、oppo 不出现返回顶部按钮，pc端和其他手机能显示

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.1 |
| System | 安卓 |
| Browser | qq浏览器 |

**Comment by yoyo837** [comment]
antd 没有专门针对移动端优化，如果发现问题，欢迎来PR帮助修改。

**Comment by afc163** [comment]
可以帮忙排查，antd 暂时不会抽精力专门对特别机型做适配。
