### ISSUE TITLE
input suffix broken

### ISSUE THREAD

**Issue by zoozalp** [ant-design/ant-design#33465]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-37hmu?file=/index.js)

### Steps to reproduce
add an input with suffix

### What is expected?
work without issues

### What is actually happening?
TypeError
Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.2 |
| System | macos |
| Browser | chrome |

---
Any of the following changes will make the code work again

1. remove suffix
2. change value={value} to value={[value]}
3. downgrade to antd@4.17.2

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/33462
