### ISSUE TITLE
[Input] showCount 

### ISSUE THREAD

**Issue by forever-me** [ant-design/ant-design#33463]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-mhqy6t](https://stackblitz.com/edit/react-mhqy6t)

### Steps to reproduce
较早前inputNumber组件还没有前/后置标签， 我使用input组件并设置type="number"及suffix 属性，当form.setFieldsValue该字段时我赋值一个数字值程序正常运行，而这部分代码在新的4.18.0 接到一个number类型值时，会产生类型错误，可否继续兼容一下？

### What is expected?
保持低版本效果

### What is actually happening?
类型错误

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.2 |
| System | mac 10.15.6 |
| Browser | chrome 96 |

---
~4.17.3      https://stackblitz.com/edit/react-mjfpdn

^4.18.0      https://stackblitz.com/edit/react-mhqy6t

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/33462
