### ISSUE TITLE
当table设置scroll.x时候给表头设置背景色

### ISSUE THREAD

**Issue by Iwouldliketobeapig** [ant-design/ant-design#33479]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-18-1-forked-glq70)

### Steps to reproduce
.ant-table-thead > tr > th {
  background: red;
}
在有scroll.x的情况下设置th样式，最后两个th之间会有空隙

### What is expected?
不应该有空隙

### What is actually happening?
有空隙

| Environment | Info |
|---|---|
| antd | 4.18.1 |
| React | 17.0.2 |
| System | windows |
| Browser | 版本 96.0.4664.110（正式版本） （64 位） |

**Comment by afc163** [comment]
如果自行覆盖样式，需要找到显示空隙的dom样式再覆盖。
