### ISSUE TITLE
DatePicker添加验证报错

### ISSUE THREAD

**Issue by lslvxy** [ant-design/ant-design#3347]
FotmItem中添加DatePicker的时候选择日期控制台会报错

`date.js:28 Uncaught TypeError: value.getTime is not a function`
示例代码请看
[https://codepen.io/lslvxy/pen/bwozjp?editors=0011](https://codepen.io/lslvxy/pen/bwozjp?editors=0011)
查看时请打开F12开发者工具,控制台会抛出异常信息

示例中第一个没有验证不会抛出异常,第二个需要验证则报错

`value`取出来的是Moment对象

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3294

可以参照一下这里的写法：https://ant.design/components/form/#components-form-demo-validate-other

@benjycui 这块 changelog 文档还是要补上：`时间类组件的 Form 写法发生了那些变化？代码怎么改`

**Comment by dreamcatcher081210** [comment]
type: 'object',现在日期控件仅支持moment类型的了so....

**Comment by benjycui** [comment]
这个 API 差异列不完的。。只能碰到一个就更新一个了。
