### ISSUE TITLE
Table组件总结栏render报警告

### ISSUE THREAD

**Issue by vVvlife** [ant-design/ant-design#33488]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0011](https://codepen.io/pen/?editors=0011)

### Steps to reproduce
第一次渲染成功后，打开控制台会报warning

### What is expected?
没有问题

### What is actually happening?
控制台报错

| Environment | Info |
|---|---|
| antd | 4.18.1 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Microsoft Edge 版本 98.0.1100.3 (官方内部版本) dev (64 位) |

---
应该是跟rc-table的更新有关，columns那边 了onCell方法，优化了渲染，但是总结栏还是老方法

**Comment by vVvlife** [comment]
Table.Summary.Cell只要加了colSpan&rowSpan的属性，就会报错
查看报错的地方，这两个参数还是在render里
![image](https://user-images.githubusercontent.com/20148964/147726512-bdc99c0b-20d0-46bd-851f-91b0d21e3847.png)

**Comment by vVvlife** [comment]
https://codesandbox.io/s/unh3g
![image](https://user-images.githubusercontent.com/20148964/147728972-5e1192ce-16cf-48e4-b0c4-7954a8f38d75.png)

**Comment by afc163** [comment]
@zombieJ 误伤了 Summary
