### ISSUE TITLE
filterDropdown如何触发table的onChange事件

### ISSUE THREAD

**Issue by asoqa** [ant-design/ant-design#3348]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: 
- 浏览器及其版本:

#### 您做了什么？
我自定义了表格某一列的filter，里面是一个搜索框。但是现在问题是，我不清楚这个自定义的filter怎么触发table的onChange事件，并在table的filter中传入自定义的内容，最后统一调用服务器端的筛选或排序功能
```
                    filterDropdown: <SearchInput placeholder="input search text"
                        onSearch={this.onSearch} style={{ width: 200 }}
                        />
```
![2016-10-10 10 57 06](https://cloud.githubusercontent.com/assets/2541822/19226026/55d66a60-8ed8-11e6-8052-28a604a7f204.png)

**Comment by afc163** [comment]
你可以自行在 `this.onSearch` 的逻辑里来触发。

```
onSearch() {
   //...this.fetch()
}
```

**Comment by asoqa** [comment]
本来是这样做的，但是没有找到办法拿到其它列的筛选条件。

**Comment by afc163** [comment]
通过 state 或者 redux 保存到父级。

**Comment by chj-damon** [comment]
同问，如何在筛选的时候拿到分页和排序的信息？table的onChange事件中有filters字段，有没有手段可以在自定义的筛选方法中触发table的onChange呢？

**Comment by chj-damon** [comment]
@asoqa 你最后这个问题成功解决了吗？
