### ISSUE TITLE
Table 组件 pagination 不设置 total 的情况下，onChange 死循环调用

### ISSUE THREAD

**Issue by linkHe12** [ant-design/ant-design#33487]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-chatterjee-y60q6?file=/src/App.js)

### Steps to reproduce
使用 Table 组件的分页配置，且使用了 onChange，不设置 pagination 的 total 或 total 设置为 0，会导致 onChange 被执行，如果使用 Table 组件的组件调用了 setState，重新 render 后会导致死循环

Using the pagination configuration of the Table component and using onChange without setting the total of pagination or total to 0 will cause onChange to be executed, and if the component using the Table component calls setState, re-rendering will result in a infinity loop.

### What is expected?
未设置 total 或 total 为 0 不会执行 onChange

### What is actually happening?
未 total 或 total 为 0 执行了 onChange

| Environment | Info |
|---|---|
| antd | 4.18.1 |
| React | 16.14.0 |
| System | macOS 12.0.1 |
| Browser | Chrome 96 |

---
问题产生是因为修复这个问题：https://github.com/ant-design/ant-design/pull/33411
在此处判断 current !> maxPage 就执行 onChange 导致的 https://github.com/ant-design/ant-design/blob/3913fd51fbd18eeab1c8f6a724bfb4c7e1396e99/components/table/hooks/usePagination.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L76

**Comment by afc163** [comment]
@2724635499 看看

**Comment by 2724635499** [comment]
> @2724635499 看看

ok

**Comment by Xiaochena** [comment]
https://codesandbox.io/embed/ji-ben-yong-fa-antd-4-18-1-forked-cyl16?fontsize=14&hidenavigation=1&theme=dark

是的、升级了18.1之后我也遇到了这个问题、不设置分页总数或者total为0都会发生这个问题
