### ISSUE TITLE
TreeSelect 无法选中子节点全为disabled的节点

### ISSUE THREAD

**Issue by kkkisme** [ant-design/ant-design#33493]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cong-shu-ju-zhi-jie-sheng-cheng-antd-4-18-2-forked-8i6rk?file=/index.js)

### Steps to reproduce
1、打开重现链接

2、尝试选择【Node1】节点

3、无法选中

### What is expected?
可以选中【Node1】节点

### What is actually happening?
不能选中【Node1】节点

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17 |
| System | windows 11 |
| Browser | Chrome 96 |

---
4.17.x版本的操作是正常的

**Comment by MadCcc** [comment]
这里回填似乎有些问题，默认 `TreeSelect.SHOW_CHILD` 模式下不应该回填 parent 节点。
所以这里的问题其实是反的。。选不中 Node1 是对的，能选中其他 parent 节点才是有问题。
如果需要选择 parent 节点，请添加 `showCheckedStrategy={TreeSelect.SHOW_ALL}` 或者 `showCheckedStrategy={TreeSelect.SHOW_PARENT}`，详见 https://ant.design/components/tree-select-cn/#API

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cong-shu-ju-zhi-jie-sheng-cheng-antd-4-18-2-forked-mc8lm?file=/index.js:917-967)

**Comment by MadCcc** [comment]
看了下确实是个 bug，计划修复
