### ISSUE TITLE
Card with tabs has strange interactions with tab props

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#33497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/with-tabs-antd-4-17-0-alpha-7-forked-mlogn?file=/index.js)

### Steps to reproduce
Add these to the card properties:
tabPosition: 'left',
type: 'card'

### What is expected?
Card should render the content on the space by it's side as shown by the image bellow, also card should not leave any padding/margin on left side, since the tabs are now the start of the component phasing.

![image](https://user-images.githubusercontent.com/87539237/147748293-97c52ba0-c116-491f-b834-741550c80426.png)

### What is actually happening?
Card is leaving space on the left and rendering the content bellow itself insted of on the area on the tab itself.

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | react: 17.0.2 |
| System | Windows 10 |
| Browser | Brave |

---
If we provide a API to Card component to use with Tabs, it should be compatible with all or most of Tab props.
Also the design of Card with tabs should take in consideration the properties it receives from "tabProps"

**Comment by afc163** [comment]
There is no design for this usage in first place.

**Comment by balboFK** [comment]
@afc163 thanks for the reply.
Any plans to create a design for it? 
I don't see the case where the actual design can be used, hence the white box on top of the content.
If you have multiple tabs, the content of the card will go down even more.

**Comment by afc163** [comment]
Yeah, closing it.
