### ISSUE TITLE
Select dropdownMatchSelectWidth={false} cannot disable virtual prop after 4.18.x

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#33495]
4.18.x ❌: https://codesandbox.io/s/ji-ben-shi-yong-antd-4-18-2-forked-dpozd?file=/index.js
4.17.x ✅: https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-4-forked-p6e2t?file=/index.js

**Comment by vonyoki** [comment]
TreeSelect 也有相同问题

**Comment by tangjinzhou** [comment]
@afc163

**Comment by sysunal** [comment]
The same problem still exists in TreeSelect in latest version
4.18.9 ❌: https://codesandbox.io/s/generate-from-tree-data-antd-4-18-9-forked-01ow00?file=/index.js

**Comment by afc163** [comment]
TreeSelect 依赖了 BaseSelect，里面缺少这段逻辑 https://github.com/react-component/select/pull/460/files#diff-0b4261de12d101b3cdd2e17d299d34ae6c5053f3fcefc449ea04ceb3af3e2d26R932

cc @MadCcc 有空看看

**Comment by zombieJ** [comment]
Seems not a question in latest version: https://codesandbox.io/s/ji-ben-shi-yong-antd-4-17-4-forked-p6e2t?file=/index.js

**Comment by sysunal** [comment]
**TreeSelect** still not work in 4.19.x also.
4.18.9 ❌, 4.19.1 ❌: https://codesandbox.io/s/generate-from-tree-data-antd-4-18-9-forked-01ow00?file=/index.js
