### ISSUE TITLE
范围日期选择器样式异常

### ISSUE THREAD

**Issue by broadliyn** [ant-design/ant-design#3349]
版本是最新的2.0.1

![2016-10-10 11 14 10](https://cloud.githubusercontent.com/assets/12005965/19226196/b6957eac-8eda-11e6-892e-c45cbd009af2.png)

看了官网发现样式倒是正常的，在我的环境上就缺少了相关的class样式。
查看了我本地的环境，我有对less进行覆写(从1.x直接升级到的2.x)：
```less
@import "~antd/lib/style/themes/default.less";
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";

@body-background: #eee;
//@icon-url: "https://at.alicdn.com/t/font_1463992151_360388";

@primary-color          : #5992d4;
@info-color             : #5992d4;
@link-color             : #5992d4;
```

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/3312 

还未发布。
