### ISSUE TITLE
virtual-list 里对 wheel 禁用，导致不能横向滚动 

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#33500]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tree 在大数据时可以横向滚动，，

### What does the proposed API look like?
这个地方改成可控的或删了。。。https://github.com/react-component/virtual-list/blob/master/src/hooks/useFrameWheel.ts#L41

https://codesandbox.io/s/antd-reproduction-template-forked-19h38?file=/index.js

**Comment by jljsj33** [comment]
这组件坑很多。。。
1. 即然支持 component，componentProps 是不是应该加上。。。
2. onScroll 都被你包了一层，，为啥不把  offsetTop 或 scrollTop 带上？？

**Comment by jljsj33** [comment]
还有个需求，，拆叠面板里是否考虑加入虚拟滚动，，或者 collapse 直接套 virtual-list。。。
这样可用：
```jsx
<VirtualList component={Collapse} componentProps={collapseProps}>
  <Collapse.Panel></Collapse.Panel>
</VirtualList>
```

**Comment by jljsj33** [comment]
还有个建议啊，，虚拟滚动应该是个独立组件，，，不能直接嵌 tree 里啊，，，用法应该跟我上面 Collapse 写的一样，，

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/issues/33849
这是同一个问题吗

**Comment by afc163** [comment]
Duplicate of #33849

**Comment by jljsj33** [comment]
你这货不应该关后面的，，链到这问题吗？？

**Comment by afc163** [comment]
那个描述的更完整。

**Comment by jljsj33** [comment]
随便你，，扔个我的黑科技解决方案。。。。
```jsx
const bodyHolder = dom.getElementsByClassName(
        'ant-tree-list-holder',
      )[0] as HTMLDivElement;
      bodyHolder.addEventListener('wheel', e => {
        // 横向滚动被拦
        // 去掉 virtual-list 里的 preventDefault: https://github.com/react-component/virtual-list/blob/master/src/hooks/useFrameWheel.ts#L41
        e.preventDefault = () => {};
      });
```

**Comment by manooog** [comment]
> 随便你，，扔个我的黑科技解决方案。。。。
> 
> ```js
> const bodyHolder = dom.getElementsByClassName(
>   'ant-tree-list-holder',
> )[0] as HTMLDivElement;
> bodyHolder.addEventListener('wheel', e => {
>   // 横向滚动被拦
>   // 去掉 virtual-list 里的 preventDefault: https://github.com/react-component/virtual-list/blob/master/src/hooks/useFrameWheel.ts#L41
>   e.preventDefault = () => {};
> });
> ```

bodyHolder.addEventListener('wheel', e => {
  // xxx
}, true)

试过了，addEventListener 这个方法还需要将第三个参数设置为 true，否则不能保证在 useFrameWhell 之前替换 e.preventDefault 方法。

**Comment by cong1223** [comment]
> 随便你，，扔个我的黑科技解决方案。。。。
> 
> ```js
> const bodyHolder = dom.getElementsByClassName(
>   'ant-tree-list-holder',
> )[0] as HTMLDivElement;
> bodyHolder.addEventListener('wheel', e => {
>   // 横向滚动被拦
>   // 去掉 virtual-list 里的 preventDefault: https://github.com/react-component/virtual-list/blob/master/src/hooks/useFrameWheel.ts#L41
>   e.preventDefault = () => {};
> });
> ```

树的宽度还是没撑开，需要手动设置吗

**Comment by cong1223** [comment]
> > 随便你，，扔个我的黑科技解决方案。。。。
> > ```js
> > const bodyHolder = dom.getElementsByClassName(
> >   'ant-tree-list-holder',
> > )[0] as HTMLDivElement;
> > bodyHolder.addEventListener('wheel', e => {
> >   // 横向滚动被拦
> >   // 去掉 virtual-list 里的 preventDefault: https://github.com/react-component/virtual-list/blob/master/src/hooks/useFrameWheel.ts#L41
> >   e.preventDefault = () => {};
> > });
> > ```
> 
> 树的宽度还是没撑开，需要手动设置吗

因为里面那个列表是绝对定位的。宽度怎么撑开？

**Comment by cong1223** [comment]
> useFrameWhell

你这样设置会让树的上下滚动事件跟外层页面滚动事件冲突。有解决办法吗？

**Comment by javanoclaw** [comment]
改下这个样式看看,会出现横向滚动：
```css
	.ant-tree {
		.ant-tree-list-holder {
			> div {
				overflow: unset !important;
				width: max-content;
			}
		}
```

**Comment by Flcwl** [comment]
没懂里面为什么要 onWheelX 触发列表滚动，哪个交互规范定的。。 要不新增个API支持关闭这个能力吧
https://github.com/react-component/virtual-list/blob/22effd42cc10357d5d52057f945f674222b84e9a/src/hooks/useFrameWheel.ts#L100
