### ISSUE TITLE
antd的dropdown组件好像不适用于icon组件点击打开菜单的场景

### ISSUE THREAD

**Issue by SmilingIdiot** [ant-design/ant-design#33507]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce
在dropdown组件（带arrow）内放置一个icon组件触发打开菜单，打开后arrow偏离了触发打开的icon组件（已在antd钉钉答疑群贴出复现链接，公网不便贴出riddle链接）

### What is expected?
arrow对齐到icon组件上

### What is actually happening?
arrow偏离了icon组件

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.14.21 |
| System | macos |
| Browser | chrome 90.0.4430.212 |

**Comment by afc163** [comment]
```jsx
<Dropdown arrow={{ pointAtCenter: boolean }} />
```

We need to add this.
