### ISSUE TITLE
升级到最新版本Table组件分页的onChange事件内更新page和pageSize就报错 版本4.16.13无问题

### ISSUE THREAD

**Issue by ngwszsd** [ant-design/ant-design#33508]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
升级最新版antd后Table组件的pagenation属性的onChange事件当我想改变pageSize和page更新列表时报错  
```ts
const onChange = (size: number, pageSize: number) => {
// setPage时报错 最新版报错 版本4.16.13无问题
    setPage({
      pageSize,
      size,
    });
};
  useEffect(() => {
    const payload = {
      page: page.size,
      pageSize: page.pageSize,
      ...formData,
    };
    dispatch({
      type: 'workbench/list',
      payload
    })
  }, [formData,  page])
```

### What is expected?
和版本4.16.13一样不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17 |
| System | mac bigsur |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in https://ant.design/changelog-cn#4.18.2
