### ISSUE TITLE
cascader  showSearch放在form使用时双击或者搜索时会显示浏览器的提示字符

### ISSUE THREAD

**Issue by lanll** [ant-design/ant-design#3350]
`const { Form,Cascader,Roe,Col } = antd;
const FormItem = Form.Item;

const options = [{
  value: 'zhejiang',
  label: 'Zhejiang',
  children: [{
    value: 'hangzhou',
    label: 'Hangzhou',
    children: [{
      value: 'xihu',
      label: 'West Lake',
    }],
  }],
}, {
  value: 'jiangsu',
  label: 'Jiangsu',
  children: [{
    value: 'nanjing',
    label: 'Nanjing',
    children: [{
      value: 'zhonghuamen',
      label: 'Zhong Hua men',
    }],
  }],
}];

class App extends React.Component {
  render() {
    const {getFieldDecorator}= this.props.form;
    return (
      <div>
       <Form horizontal>
        <FormItem
             label="级联">
             {getFieldDecorator('cantonIds', {
             })(
               <Cascader expandTrigger="hover" options={options} showSearch/>
             )}

        </FormItem>
          
        </Form>
        <Cascader expandTrigger="hover" options={options} showSearch/>
        </div>
    );
  }
}

App = Form.create()(App);
ReactDOM.render(<App />, document.getElementById('container'));`

上述为演示代码，

现象：
![image](https://cloud.githubusercontent.com/assets/9207241/19226447/070dfe10-8ede-11e6-9810-477b16fa543a.png)
预期：
![image](https://cloud.githubusercontent.com/assets/9207241/19226454/19409764-8ede-11e6-9a33-652d6ead27c9.png)

**Comment by afc163** [comment]
貌似是 autoComplete 没关，来个 PR 如何？

**Comment by lanll** [comment]
最糟糕的情况是自动提示的掩盖了数据。autoComplete如何关闭
![image](https://cloud.githubusercontent.com/assets/9207241/19227002/ee56e762-8ee5-11e6-9de8-e555459d8624.png)
