### ISSUE TITLE
Suggest <Space /> support 'block' and 'justify'

### ISSUE THREAD

**Issue by littleLane** [ant-design/ant-design#33519]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now it seems that <Space /> can only be displayed as inline, but there are many block scenarios in daily development, which can only be achieved by setting styles ( like: { width: 100% or display: flex }). It is recommended to support block attribute settings and justify (for alias: justify-content ) settings (such as align attributes), just same as using flex!

### What does the proposed API look like?
Empty!

**Comment by afc163** [comment]
https://ant.design/components/space/#components-space-demo-align

https://ant.design/components/grid/#components-grid-demo-flex
