### ISSUE TITLE
PageHeader sometimes throws a state update error

### ISSUE THREAD

**Issue by wuifdesign** [ant-design/ant-design#33513]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2pi3y?file=/app.js)

May not happen every time on refresh, but sometimes it happens

![bug](https://user-images.githubusercontent.com/5678318/147841650-1e4debe4-b6bf-4482-b6c3-78c13cacf353.png)

### Steps to reproduce
Trigger Suspense while a PageHeader is rendered on the page, like in the CodeSandbox example.

### What is expected?
Not throwing an error

### What is actually happening?
Throws an error

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | Windows |
| Browser | Chrome 96.0.4664.110 |

### Additional Information

As `PageHeader` uses `ResizeObserver` and this is fired on resize, somtimes the onResize is triggered with `{width: 0, height: 0, offsetWidth: 0, offsetHeight: 0}`, but element was already removed. 

```
const onResize = ({ width }: { width: number }) => {
  updateCompact(width < 768);
};
```

This results in following error:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

I think this happens because of this code inside the `SingleObserver` (rc-resize-observer):

```
 if (onResize) {
  // defer the callback but not defer to next frame
  Promise.resolve().then(() => {
    onResize(sizeInfo, target);
  });
}
```

**Comment by seki2020** [comment]
I am trying to find a solution, @wuifdesign valueable findings. Lol:

**Comment by wuifdesign** [comment]
@afc163 i added a pull requests
