### ISSUE TITLE
Adding navigation arrows to overflown tabs 

### ISSUE THREAD

**Issue by Mood-al** [ant-design/ant-design#33516]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
the problem is the new tabs drowpdown navigation isn't user friendly as using navigation arrows like you were using at rc-tabs v10.
so if we had an overflown tabs the user wont know if there are other tabs he will just see the shown tabs but if we added arrows he will know that there is content hidden in the left or the right and he will navigate to it using the arrows.
![image](https://user-images.githubusercontent.com/63562308/147852644-ad6b603e-e490-4bcb-bdeb-f06f9fdcb96a.png)

![image](https://user-images.githubusercontent.com/63562308/147852634-5c18c396-0d76-492e-ae8d-1705e1648fbf.png)

### What does the proposed API look like?
same API as rc-tabs v10

**Comment by afc163** [comment]
Sorry, it is by designed, we have to plan to go back old version.

**Comment by Mood-al** [comment]
The old version is working fine but the issue with it that in mobile the tabs can't be touchable like v11 you are forced to navigate by clicking on arrows to navigate between tabs in mobile and this isnt user friendly..

Do you have any solution for this?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29645#issuecomment-792619400

**Comment by Mood-al** [comment]
> [#29645 (comment)](https://github.com/ant-design/ant-design/issues/29645#issuecomment-792619400)

Currently I'm using 10v i couldnt find any of these custom hook inside rc-tabs@10.0.0 how i can make the tabs touchable on mobile??

**Comment by Mood-al** [comment]
> [#29645 (comment)](https://github.com/ant-design/ant-design/issues/29645#issuecomment-792619400)

the example you gave me is on rc-tabs v11 what i want is to add arrows like you did in the v10 the dropdown isnt user friendly at all
![image](https://user-images.githubusercontent.com/63562308/148277031-b049a73b-2072-496d-8ed4-9eea18352ced.png)
I just want a way to add navigation arrows
like this 
![image](https://user-images.githubusercontent.com/63562308/148277126-f5db9d18-ec0d-4650-be7e-da4a89d8e6eb.png)
