### ISSUE TITLE
select不支持单选并且自主输入

### ISSUE THREAD

**Issue by hackor-hho** [ant-design/ant-design#33517]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select筛选不在列表的时候，支持自主输入，目前支持多选，希望可以只支持单选，有些场景是需要的

### What does the proposed API look like?
select既可以自主输入，也可以选择模式，只进行单选

**Comment by afc163** [comment]
https://ant.design/components/auto-complete/
