### ISSUE TITLE
validateFields(nameList?: NamePath[]) 传入['name', "username"]后执行异常，校验规则被忽略

### ISSUE THREAD

**Issue by ywy739** [ant-design/ant-design#33522]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-pike-8x22i?file=/src/App.js)

### Steps to reproduce
点击check 按钮
code说明：
表单中使用嵌套结构name=['name', "username"]
validateFields(nameList?: NamePath[]) 传入['name', "username"]期待定位校验

### What is expected?
定位校验['name', "username"]表单项

### What is actually happening?
执行异常，所有校验规则被忽略

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 18 |
| System | win10、Mac os12.0.1  |
| Browser | Chrome 、Safari15.1 |

**Comment by afc163** [comment]
```diff
- const values = await form.validateFields(["name", "nickname"]);
+ const values = await form.validateFields([["name", "nickname"]]);
```

**Comment by shaoshenchen** [comment]
bth

> ```diff
> - const values = await form.validateFields(["name", "nickname"]);
> + const values = await form.validateFields([["name", "nickname"]]);
> ```

BTW，namepath 之所以支持 string、number 和 string[]、number[] ，我想跟对象的取值有关。

比如要拿到数组中的某个对象的属性，你就得这么写 namepath

`form.validateFields(['arr', 1, 'handsome'])`

```js
const arr = [
    {
        name: 'shuan',
        hobby: 'coding'
    },
    {
        name: 'afc163',
        handsome: true,
    }
]
```

我的背景是在 <Form.List> 中使用 <Form.Item>
