### ISSUE TITLE
Add prop for Progress to have square ends with `'line'` type.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ant-design/ant-design#33524]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using the progress bar to show the progress in a video player. The rounded ends in the progress bar makes it look weird. I expected `strokeLinecap='square'` to solve this, but it only changes the stroke linecap of the inner progress bar. Here is a sandbox to show that: https://codesandbox.io/s/antd-progress-sdcwb?file=/src/App.js.

## Change behavior of `strokeLinecap` prop
Also make the `ant-progress-inner` div have a border radius of 0.

## Add `innerStyle` and `innerClassName` props
These would be applied to `ant-progress-inner`. Then I could do:
```jsx
<Progress innerStyle={{ borderRadius: 0 }} />
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25181#issuecomment-648544342

**Comment by ChocolateLoverRaj** [comment]
@afc163 But even when using that prop, the main rectangle (the one that is 100% width regardless of `percent`) still has rounded corners. I even said it in the issue:
> I expected `strokeLinecap='square'` to solve this, but it only changes the stroke linecap of the inner progress bar.

Here is a screenshot circling the rounded part:
![image](https://user-images.githubusercontent.com/52586855/148140875-1a6a23e5-e89e-41fa-bcfd-9a70aa529cc9.png)

**Comment by afc163** [comment]
@blatinier

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/35822
