### ISSUE TITLE
Access div ref of Progress component

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ant-design/ant-design#33526]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use [`getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) on the parent html element that `Progress` renders.

### What does the proposed API look like?
A prop called something like `wrapperDivRef` or `elementRef` which passes the ref to the underlying `div` element.

```jsx
import { Progress } from 'antd'
import { useRef, useEffect } from 'react'

const Component = () => {
  const ref = useRef(null)

  useEffect(() => {
    console.log(ref.getBoundingClientRect())
  }, [])

  return <Progress elementRef={ref} />
}
```

**Comment by afc163** [comment]
Use `id="xxx"` and `document.getElementById('xx')`

**Comment by ChocolateLoverRaj** [comment]
@afc163 That would not work with multiple elements, since there can only be a single element with a certain id. You are suggesting a *workaround* to this problem, not a *solution*. Using `document.getElementById()` will be less performant than using a ref.
