### ISSUE TITLE
Messages are not cleared between tests

### ISSUE THREAD

**Issue by ecumene** [ant-design/ant-design#33521]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-testing-library-demo-4i62c?from-embed)

### Steps to reproduce
Create a component that creates a message as a side effect, then write 2 unit tests via react-testing-library

### What is expected?
Messages should not persist in the react-testing-library DOM over tests

### What is actually happening?
The second test fails because the message is also in the react-testing-library DOM

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | react |
| System | MacOS |
| Browser | None |

---
Maybe there should be a way to clear all messages?

**Comment by afc163** [comment]
Try `message.destroy()`.
