### ISSUE TITLE
Affix inside a container snaps out of its parent container

### ISSUE THREAD

**Issue by mnts-i** [ant-design/ant-design#33529]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/affix/](https://ant.design/components/affix/)

### Steps to reproduce
Just open the current documentation page for the Affix component. Go to the Container to Scroll example and scroll a little bit so the Affix gets pinned at the top of the container. Then just scroll down the whole page and the Affix snaps out of the container. In order to re-pin it inside its parent container, you have to scroll the container

### What is expected?
The Affix inside the container stay inside the container (at least I think that is what it supposes to be doing)

### What is actually happening?
The Affix snaps out the container when the window (browser) scrolls

| Environment | Info |
|---|---|
| antd | undefined |
| React | React |
| System | Windows |
| Browser | Chrome |

**Comment by yangzheli** [comment]
Duplicate [#3938](https://github.com/ant-design/ant-design/issues/3938).
As explained in the [FAQ](https://ant.design/components/affix/#FAQ).
