### ISSUE TITLE
如果Component被createForm()(XXX)后，那么外层就不能通过refs.aa.bb()的方式调用该子组件的方法了

### ISSUE THREAD

**Issue by shenzhigang** [ant-design/ant-design#3352]
如果Component被createForm()(XXX)后，那么外层就不能通过refs.aa.bb()的方式调用该子组件的方法了。
- antd 版本:1.11

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3330

**Comment by benjycui** [comment]
其实我比较好奇有哪些场景是非使用 `ref` 引用 `Form` 不可的，有碰到这种场景的同学麻烦贴下在线 demo 和场景的描述，谢谢。

**Comment by shenzhigang** [comment]
@benjycui  比如说需要在Form外重置Form。

**Comment by benjycui** [comment]
除了这个之外，`resetFields` 这个可以提升，但是如果有用户自定义的 method 就没办法了，会有冲突。

**Comment by muxuehen** [comment]
我需要用antd的Steps写不同的form,点击下一步时，引用每个form的校验，如果用了creatform，就没法用ref。有没有好的办法呢？

**Comment by benjycui** [comment]
如果只是为了用 `resetFields` `validateFields` 之类的方法，只要：

```jsx
const CustomizedForm = Form.create()(xxx);

<CustomizedForm ref="hello" />

this.refs.hello.resetFields // do this.
```
