### ISSUE TITLE
Select选择器 suffixIcon自定义的选择框后缀图标点击不能展开下拉框

### ISSUE THREAD

**Issue by axiang12** [ant-design/ant-design#33538]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.baidu.com/](https://www.baidu.com/)

### Steps to reproduce
如标题

### What is expected?
suffixIcon自定义的选择框后缀图标点击展开下拉框

### What is actually happening?
suffixIcon自定义的选择框后缀图标点击未展开下拉框

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.x |
| System | macOS |
| Browser | chrome版本 96.0.4664.110 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27479#issuecomment-719903848
