### ISSUE TITLE
DatePicker 如何设置空值（清空）？

### ISSUE THREAD

**Issue by Midqiu** [ant-design/ant-design#3353]
一个场景：
列表上好几条记录，当用户编辑完其中一条后，点击新建，这时候DatePicker显示的是上一次的时间，我想这个时候给清空掉DatePicker的值，要如何做？

**Comment by ddcat1115** [comment]
如果是用在form里面，请用 resetFields，参考 https://ant.design/components/form/#components-form-demo-validate-other

如果不是，就直接修改DatePicker 的 value

**Comment by Midqiu** [comment]
> 直接修改DatePicker 的 value
修改成什么为空呢？`null` `undefined` ？

**Comment by ddcat1115** [comment]
null

**Comment by 940259** [comment]
@Midqiu 直接修改DatePicker 的 value的话，会出现 “Invalid date” ， 所有的日期都显示 NaN

**Comment by leadream** [comment]
@ddcat1115 最近也遇到了这个场景，想要日期范围只有截止日期没有开始日期。如果设置`value={null}`是可以清空的，但是清空了两个日期。如果设置`value={[null,moment()]}`则会出现`Invalid date`。请问只想置空一个日期该怎么设置呢？

**Comment by benjycui** [comment]
@leadream 你这种场景直接使用一个 DatePicker 不就可以了么、。

**Comment by leadream** [comment]
@benjycui 但它是一个范围啊，比如想用`[null,moment()]`表示今天以前。我知道了，我可以用两个DatePicker来实现。

**Comment by benjycui** [comment]
Use: http://react-component.github.io/calendar/examples/start-end-range.html
