### ISSUE TITLE
table column 更改宽度不同步

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/ant-design#33545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yuan-cheng-jia-zai-shu-ju-antd-4-18-2-forked-497qo?file=/index.js)

### Steps to reproduce
点击按钮

### What is expected?
更改表格宽度表头、表body同步

### What is actually happening?
宽度更改不同步

### preview
![动画7](https://user-images.githubusercontent.com/49073282/148040497-885a7f3c-7d77-4469-b7ea-0fb878413e6a.gif)

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.0 |
| System | windows |
| Browser | edge最新版 |

**Comment by afc163** [comment]
Duplicate of #31098

**Comment by hemengke1997** [comment]
v4.17.4没有这个问题， 4.18.0出现的，应该不是重复的issue吧 🤭

**Comment by hemengke1997** [comment]
看起来像是 https://github.com/react-component/table/commit/170a87d3c2fa4be50631eca94d64ae97f57533a7

**Comment by afc163** [comment]
例子的按钮好像没了。

**Comment by hemengke1997** [comment]
例子恢复了 @afc163

**Comment by afc163** [comment]
4.17.4 确实没有这个问题 https://codesandbox.io/s/yuan-cheng-jia-zai-shu-ju-antd-4-18-2-forked-2nxez?file=/package.json
看上去和 https://github.com/react-component/table/pull/706 有关系。

**Comment by hemengke1997** [comment]
我尝试着修一下
