### ISSUE TITLE
getFieldDecorator 建议增加setValueFromEvent

### ISSUE THREAD

**Issue by Midqiu** [ant-design/ant-design#3354]
表单的`getFieldDecorator` 参数有一个`getValueFromEvent`方法，却没有`setValueFromEvent`方法，感觉不是很合理。建议增加`setValueFromEvent`方法。
（我现在的处理方法是在`mapPropsToFields`里面做处理。）

**Comment by yiminghe** [comment]
不懂什么意思，set value 自己完全可控， get value 因为从组件中来是不可控的

**Comment by Midqiu** [comment]
就比如说我有个字段叫time吧，格式是一个时间戳数字类型，但现在ant里面date都是moment()类型，我绑定的时候我得先把数字类型转化为moment()类型吧。

**Comment by benjycui** [comment]
`setValueFromEvent` 这个 API 没意义，你 `getValueFromEvent` 的返回值就会被传回给时间组件，而时间组件在事件里给你的就是 `moment` 类型了。

**Comment by Midqiu** [comment]
一个字段，数据库里面保存的数字类型（时间戳），和组件绑定的时候，组件的value是moment类型，那怎么把这两个绑定起来，是不是得有个set get方法去转化。

**Comment by benjycui** [comment]
`mapPropsToFields`

**Comment by Midqiu** [comment]
是，我现在也是用`mapPropsToFields`去处理的，把所有的字段都在这个地方处理。但是一个组件只有get方法没有set方法说不过去呀，为了一致性建议加上这个set方法。
