### ISSUE TITLE
Form表单Form.Item的rules中pattern校验项对InputNumber组件无效

### ISSUE THREAD

**Issue by wuang1992** [ant-design/ant-design#33549]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/currying-cherry-pwj6g)

### Steps to reproduce
见链接

### What is expected?
校验成功

### What is actually happening?
校验无效

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 16.13.0 |
| System | mac os |
| Browser | 96.0.4664.93 |

**Comment by afc163** [comment]
Try InputNumber stringMode, pattern is not working with `type: 'number'`.

https://codesandbox.io/s/great-river-l3wfs?file=/src/App.js
