### ISSUE TITLE
DatePicker[picker=week]中文环境下选择2021年最后一周（2021-12-27[周一]这周），在加入format后，显示的年为2022年

### ISSUE THREAD

**Issue by veryfine** [ant-design/ant-design#33547]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://6e93z.csb.app)

### Steps to reproduce
组件：<DatePicker picker="week" format="YYYY年第WW周"/>
操作：选择2021-12-27至2022-01-02这周，即2021年最后一周，当鼠标悬停在弹出的选择面板的这周的日历日期上时，输入框同步显示为”2021年第52周“，但当点击后（真正选择此周后），输入框的值变成错误的显示值”2022年第52周“。

### What is expected?
当选择2021年第52周时，正确显示值：2021年第52周，而非：2022年第52周

### What is actually happening?
实现显示：2022年第52周

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.8.6 |
| System | window 10 中文版 |
| Browser | chrome  96.0.4664.45 中文 |

---
需在中文语言环境下测试，英文环境下当选择2021-12-26至2022-01-01，以及选择2022-01-02至2022-01-08时，在指定format="YYYY年第WW周"时也会显示错误

**Comment by afc163** [comment]
<img width="336" alt="图片" src="https://user-images.githubusercontent.com/507615/148068580-84dd6981-4391-4dbf-b5fb-2e0d353f5258.png">

**Comment by yangzheli** [comment]
[codesandbox](https://codesandbox.io/s/ri-qi-ge-shi-antd-4-18-2-forked-1pyru?file=/index.js)
这似乎是个 edge case: 上一年的最后一周有几天落在这一年。
<img width="332" alt="截屏2022-01-05 上午12 23 57" src="https://user-images.githubusercontent.com/43645580/148091135-44683d0b-98b0-4b4f-99e6-16cf73672e86.png">

**Comment by afc163** [comment]
对，需要改成 GGGG。antd 内建的 format 也是 gggg

https://github.com/react-component/picker/blob/8bc4cce34d2d53e8017e2d8b7a59c4f7db613d0c/src/utils/uiUtil.ts#L161

**Comment by liutian** [comment]
这个问题好像还没解决，最新4.18.5版本还有问题
