### ISSUE TITLE
Select自定义suffixIcon为CaretDownOutlined，点击小三角下拉框不显示，不自定义suffixIcon无此问题

### ISSUE THREAD

**Issue by webVictor** [ant-design/ant-design#33550]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-m6kre?file=/index.js)

### Steps to reproduce
点击小三角，下拉框不显示

### What is expected?
点击小三角显示下拉框

### What is actually happening?
点击小三角不显示下拉框

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.2 |
| System | mac 12.1 |
| Browser | chrome版本 96.0.4664.110（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27479#issuecomment-719574357
