### ISSUE TITLE
Cascader级联选择中多选模式，现在选中二级目录，输入框中没有展示对应的一级目录

### ISSUE THREAD

**Issue by yuanziyao** [ant-design/ant-design#33556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
在Cascader级联选择中多选模式，点击一级目录light，选中二级目录number0

### What is expected?
选中之后在输入框中展示light/number0

### What is actually happening?
实际结果在输入框中只有number0

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17 |
| System | windows |
| Browser | google |

**Comment by afc163** [comment]
这是符合预期的，因为是多选，不太适合展示完整路径。

**Comment by yuanziyao** [comment]
> 这是符合预期的，因为是多选，不太适合展示完整路径。



> 这是符合预期的，因为是多选，不太适合展示完整路径。

如果我多个二级目录名称相同，通过一级目录进行区分，而数据回显输入框中只展示二级目录，输入框就会存在多个相同的二级目录名称，不就对用户很不友好了

**Comment by afc163** [comment]
可用 tagRender 进行定制。

**Comment by footya** [comment]
遇到相同的需求，tagRender在选中一级和二级时回调函数里的数据也没有包含3级的数据
这边也是期望能实现3级平行展示 1/2/3.1; 1/2/3.2;

**Comment by yuanziyao** [comment]
> 遇到相同的需求，tagRender在选中一级和二级时回调函数里的数据也没有包含3级的数据 这边也是期望能实现3级平行展示 1/2/3.1; 1/2/3.2;

之前4.18.0版本是展示完整路径的，这次更新之后就只展示末级数据了，对用户挺不友好的，可以给其提问题需求
