### ISSUE TITLE
Cascader displayRender Bug

### ISSUE THREAD

**Issue by 553082694** [ant-design/ant-design#33557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/553082694/CascaderDisplayBugDemo.git](https://github.com/553082694/CascaderDisplayBugDemo.git)

### Steps to reproduce
请自行拷贝git项目中的Demo组件
切换选择选项

### What is expected?
显示正确

### What is actually happening?
选择选项，显示内容为上一次选择的选项

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | mac |
| Browser | Chrome 版本 96.0.4664.110（正式版本） (x86_64) |

---
代码修改：options={[...this.options]} 或者 onChange回调去掉异步就正常了

**Comment by MadCcc** [comment]
我用 codesandbox 跑了下你的 demo，似乎没什么问题？
https://codesandbox.io/s/ji-ben-antd-4-18-2-forked-tjizn?file=/index.js
如果有问题的话麻烦提供一个 codesandbox

**Comment by 553082694** [comment]
> 我用 codesandbox 跑了下你的 demo，似乎没什么问题？ https://codesandbox.io/s/ji-ben-antd-4-18-2-forked-tjizn?file=/index.js 如果有问题的话麻烦提供一个 codesandbox

antd 4.17.3

用你的codesandbox，跑的是4.18.2，估计中间迭代修掉了，但是没看到更新日志中有针对cascader的更新

**Comment by MadCcc** [comment]
> 用你的codesandbox，跑的是4.18.2，估计中间迭代修掉了，但是没看到更新日志中有针对cascader的更新

那先考虑升级一下依赖版本吧
