### ISSUE TITLE
Cascader级联选择中多选模式中，如果不同一级目录下存在相同的二级目录名称，选中这些相同名称的二级目录，输入框中没展示对应一级目录的完整路径

### ISSUE THREAD

**Issue by yuanziyao** [ant-design/ant-design#33559]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
在不同一级目录下存在相同的二级目录名称，选中这些相同名称的二级目录，在输入框中只展示了二级目录名称，没有展示对应的一级目录名称，对用户不友好。

### What is expected?
期望结果：light0/number0;  light1/number0; light2/number0

### What is actually happening?
实际结果：输入框中只是展示 number0 ; number0; number0  没有对应的一级目录完整路径，数据回显很不友好

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17 |
| System | windows |
| Browser | google |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33556#issuecomment-1005397286
