### ISSUE TITLE
table 设置scroll后，500条数据使用滚轮会明细卡顿

### ISSUE THREAD

**Issue by YANGZHIQIANG1211** [ant-design/ant-design#33564]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/88ci1)

### Steps to reproduce
使用table组件，增加配置scroll={{ x: 500, y: 300 }},通过鼠标滑轮滑动数据明显卡顿，一般超过200条数据时出现卡顿现象，数据量越大越明显。需要对表头进行分组，表格数据render、勾选等操作，无法使用虚拟列表

### What is expected?
大数据量、设置scroll={{ x: 500, y: 300 }}后使用鼠标滑轮滑动时不卡顿

### What is actually happening?
鼠标滑轮滑动时卡顿

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.0.0 |
| System | windows10 |
| Browser | chrome |

**Comment by PeachScript** [comment]
数据量较大时可以走虚拟滚动：https://ant.design/components/table-cn/#components-table-demo-virtual-list

**Comment by YANGZHIQIANG1211** [comment]
> 数据量预测时可以走虚拟滚动：https://ant.design/components/table-cn/#components-table-demo-virtual-list

表头需要进行分组，数据要重新渲染，对数据进行勾选，虚拟表格使用不了

**Comment by boylonghui** [comment]
> 数据量较大时可以走虚拟滚动：https://ant.design/components/table-cn/#components-table-demo-virtual-list

虚拟滚动啥都要自己写，没有固定列，没有排序

**Comment by afc163** [comment]
Trace #20339

**Comment by strongyc** [comment]
同样，数据量超过500，勾选框严重卡顿

**Comment by hsddu** [comment]
> Trace #20339

请问antd table支持同时使用表头合并和虚拟列表吗？
