### ISSUE TITLE
select组件右键无法粘贴，且右键后缺失焦点 需要点击其它区域再点击select组件

### ISSUE THREAD

**Issue by feiyu1995** [ant-design/ant-design#33560]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#API](https://ant.design/components/select-cn/#API)

### Steps to reproduce
点击select右键缺少粘贴 右键点击后点击select组件无法聚焦

### What is expected?
右键有粘贴选项，右键后能够继续聚焦

### What is actually happening?
点击select右键缺少粘贴 右键点击后点击select组件无法聚焦

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.14 |
| System | mac |
| Browser | 谷歌96.0.4664.110 |

**Comment by MadCcc** [comment]
select 组件里的 input 宽度目前不是占满的，所以右键没有粘贴之类的选项，因为没有点到 input 上。

**Comment by zombieJ** [comment]
不好解，暂时不会动 dom 结构和布局。
