### ISSUE TITLE
在formitem下使用upload组件，formitem刷新导致upload正在上传的图片状态被清除

### ISSUE THREAD

**Issue by jilei6** [ant-design/ant-design#33577]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
upload组件依赖formitem中的某个值（包含imageurl）。在上传upload图片的过程中，由于上传的imageurl未生成，而此时formitem的某个属性值改变导致重新渲染了upload组件，upload组件的状态即被清空。

### What does the proposed API look like?
期待可以控制upload组件可以在某种条件下不被formitem的值影响和刷新

**Comment by jilei6** [comment]
已经创建 codesandbox 链接为此： https://codesandbox.io/s/antd-reproduction-template-forked-nzkqq?file=/index.js

**Comment by jilei6** [comment]
> Hello @jilei6. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @jilei6, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

链接：https://codesandbox.io/s/antd-reproduction-template-forked-nzkqq?file=/index.js

**Comment by afc163** [comment]
如何重现？给个步骤和 gif 录屏？

**Comment by jilei6** [comment]
步骤：
1.上传图片（模拟上传时间10s）
2.切换test选项
3.正在上传中的图片被清空

**Comment by afc163** [comment]
你的例子对 Form 和 state 的使用比较混乱，受控和非受控状态混杂；二次封装的 FileUpload 也没有满足约定，Upload 也没有使用 valuePropName 去绑定控件的值；Upload 也没有始终把 fileList 回传。不建议这样写，可以参考 https://codesandbox.io/s/antd-reproduction-template-forked-49krj?file=/file-upload.js

<img width="1226" alt="图片" src="https://user-images.githubusercontent.com/507615/148374975-1854f0a1-47cf-409c-9124-0111080fe5f2.png">

<img width="742" alt="图片" src="https://user-images.githubusercontent.com/507615/148375069-2f608b34-cb97-4d4a-ba08-22027532b680.png">

**Comment by afc163** [comment]
> formitem刷新导致upload正在上传的图片状态被清除

这个本质上是你例子中的 state.defaultData 一直没被更新，数据还是初始状态。

**Comment by jilei6** [comment]
> > formitem刷新导致upload正在上传的图片状态被清除
> 
> 这个本质上是你例子中的 state.defaultData 一直没被更新，数据还是初始状态。

问题就在于，state.defaultData的值在等待上传完成后的url，然后此时更新其他的属性导致了form更新，导致uplaod被重新渲染，此时上传并没有那到Url。请问此种情况先，我应该如何处理Upload的状态和值呢？有好的建议和方案吗？谢谢

**Comment by jilei6** [comment]
> > formitem刷新导致upload正在上传的图片状态被清除
> 
> 这个本质上是你例子中的 state.defaultData 一直没被更新，数据还是初始状态。

了解了，非常感谢！

**Comment by nmsn** [comment]
受控使用的情况下，Form.Item 的 rule.validiator 会持续触发

使用场景上希望《上传过程中》和《上传完成后点击表单提交》的校验逻辑不同，有办法实现这样的逻辑么
