### ISSUE TITLE
Input的TextArea组件的showCount字段居然不支持ReactNode

### ISSUE THREAD

**Issue by w602542704** [ant-design/ant-design#33578]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/api/v1/sandboxes/define（这是无效的地址）)

### Steps to reproduce
Input的TextArea组件的showCount字段支持接受string值
interface ShowCountProps {
    formatter: (args: {
        count: number;
        maxLength?: number;
    }) => string;
}

### What is expected?
期望接收ReactNode的值，方便自定义样式

### What is actually happening?
没有支持，看了input是支持ReactNode，TextArea不支持

| Environment | Info |
|---|---|
| antd | 4.18.1 |
| React | 16.8.6 |
| System | windows |
| Browser | 谷歌 |

**Comment by afc163** [comment]
现在是用 `div:after { attr: 'data-content'; }` 的方式实现的，故不支持 ReactNode。

**Comment by w602542704** [comment]
> 现在是用`div:after { attr: 'data-content'; }`的方式实现的，故不支持 ReactNode。
那我现在怎么改样式，需要改count实时计数的颜色（**5**/30），自己写样式定位覆盖上去？

**Comment by w602542704** [comment]
> 现在是用`div:after { attr: 'data-content'; }`的方式实现的，故不支持 ReactNode。

那我现在怎么改样式，需要改count实时计数的颜色（5/30），自己写样式定位覆盖上去？

**Comment by afc163** [comment]
目前只能这样。

**Comment by w602542704** [comment]
> 目前只能这样。
ok,那就这样了
