### ISSUE TITLE
destoryOnClose导致内存泄漏

### ISSUE THREAD

**Issue by akon0076** [ant-design/ant-design#33576]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/akon0076/antd-destoryOnClose-bug](https://github.com/akon0076/antd-destoryOnClose-bug)

### Steps to reproduce
cd example
yarn 
yarn start
打开页面
每重复打开弹窗10次，memory快照一次

### What is expected?
期望内存不随着打开次数增长

### What is actually happening?
随着打开次数增多，内存增大

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 17.0.1 |
| System | macOS Big Sur 11.6.2 |
| Browser | 版本 96.0.4664.110（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
关掉 React Developer Tools or 使用无痕模式再试试。

**Comment by akon0076** [comment]
> 关掉 React Developer Tools or 使用无痕模式再试试。

关掉就没问题了👍👍赞

另外我发现：如果开启了React Developer Tools，就算不打开控制台也会内存增加，应该也是缓存了节点信息

**Comment by afc163** [comment]
学会了
