### ISSUE TITLE
Add size variable for Drawer component

### ISSUE THREAD

**Issue by dnbastos** [ant-design/ant-design#33570]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The Drawer component has the `size` prop with presetted sizes, when `default` is 378px and `large` is 736px, but I would like to customize these sizes with less variables.

### What does the proposed API look like?
```less
// style/themes/default.less

@drawer-width-base: 378px;
@drawer-width-lg: 736px;
```

**Comment by MadCcc** [comment]
Try to override it with your own style？

**Comment by MadCcc** [comment]
https://codesandbox.io/s/ji-chu-chou-ti-antd-4-18-1-forked-knttj?file=/index.js
Maybe this can help you :)
