### ISSUE TITLE
DatePicker，RangePicker在picker="date"时，onChange拿到的moment对象日期后的精度是否应该为所选择日期的0点或24点而不是渲染组件的时刻

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design#33581]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#API](https://ant.design/components/date-picker-cn/#API)

### Steps to reproduce
官网示例即可重现

### What is expected?
DatePicker，RangePicker在picker="date"时，onChange拿到的moment对象日期后的精度是否应该为所选择日期的0点或24点

### What is actually happening?
DatePicker，RangePicker在picker="date"时，onChange拿到的moment对象日期后的精度是渲染组件的时刻

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16  |
| System | windows |
| Browser | chrome |

---
在业务中使用RangePicker选择时间范围筛选数据时通常需要拿到开始日期的0点和结束日期的24点

**Comment by afc163** [comment]
不会做特别处理，有些业务场景可能需要准确时刻，可以在 onChange 内自行用 startOf('day') 转化一下。

**Comment by DaJianWu** [comment]
好吧
