### ISSUE TITLE
水平Menu能否支持像Tabs一样左右滚动

### ISSUE THREAD

**Issue by 553082694** [ant-design/ant-design#33585]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rhsy0?file=/index.js)

### Steps to reproduce
Menu子项超出布局

### What is expected?
支持左右滚动

### What is actually happening?
无法滚动，收纳到省略号中去了

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | mac |
| Browser | Chrome 版本 96.0.4664.110（正式版本） (x86_64) |

**Comment by afc163** [comment]
不支持，Menu 和 Tabs 在交互上会有区别。
