### ISSUE TITLE
Form无法通过getFieldInstance获取select类型字段实例

### ISSUE THREAD

**Issue by zangnan** [ant-design/ant-design#33596]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jqkg1)

### Steps to reproduce
更新antd版本为4.18.2， 通过getFieldInstance无法获取select对象实例，目前获取到信息是
{focus: ?, blur: ?, scrollTo: ?}
另外，AutoComplete，Cascader也无法获取。
antd版本4.17.4无此问题，获取到的是：
Select?{props: {…}, context: {…}, refs: {…}, updater: {…}, selectRef: {…},?…}

### What is expected?
通过getFieldInstance可以获取select对象实例。和版本4.17.4一致：
Select?{props: {…}, context: {…}, refs: {…}, updater: {…}, selectRef: {…},?…}

### What is actually happening?
通过getFieldInstance获取select对象实例，目前获取到信息是
{focus: ?, blur: ?, scrollTo: ?}

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.0 |
| System | win10 |
| Browser | Chrome90 |

**Comment by zangnan** [comment]
> 类 Select 组件只透传 `focus` `blur` 和 `scrollTo` ，4.18.0 从 class component 改成了 function component。不要依赖内部实现，你需要访问什么数据？

比如自行添加的业务标识熟悉，希望通过props获取到

**Comment by afc163** [comment]
属性是上层组件传进来的，Form 这层应该就能拿到，不应该再通过表单控件内部再去取。

**Comment by shaoshenchen** [comment]
> 属性是上层组件传进来的，Form 这层应该就能拿到，不应该再通过表单控件内部再去取。

@afc163 有这么种情况，在表单中有 Select 组件，我希望校验失败的时候通过 scrollToFirstError 定位到 Select 组件。实际情况下定位后会有偏差。我希望通过 Select 组件这个实例，哪怕是最外层的 wrap，然后用 element.scrollIntoView() 方法实现定位

**Comment by cyw0626** [comment]
加1，validateFieldsAndScroll时报错
