### ISSUE TITLE
A horizontal scrollbar will appear by setting `overflow: auto;` on antd Menu

### ISSUE THREAD

**Issue by GhazalehEslamifard** [ant-design/ant-design#33597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/qazaaalak/pen/zYEagaw?editors=0010](https://codepen.io/qazaaalak/pen/zYEagaw?editors=0010)

### Steps to reproduce
Add a `height` and `overflow: auto` on antd Menu component which has several menu items

### What is expected?
The horizontal scrollbar should not appear until the elements inside a menu item overflow

### What is actually happening?
While the elements inside the menu item and the menu aren't overflowing, a horizontal scrollbar will appear when I set `overflow: auto;` on antd Menu

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | Ubuntu 18.04.1 LTS |
| Browser | chrome 96.0.4664.45 |

---
https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less#L519
I think by changing `width: ~'calc(100%   1px)';` to `width: 100%;` the problem will be solved

**Comment by afc163** [comment]
Your codepen is not working.

<img width="1240" alt="图片" src="https://user-images.githubusercontent.com/507615/148477521-2d7b85d2-17d6-4013-8419-99a432f2b2bd.png">

**Comment by afc163** [comment]
```diff
     <Menu
        onClick={this.handleClick}
-       style={{ width: 256, height: 300, overflow: 'auto' }}
+       style={{ width: 256, height: 300, overflowX: 'hidden', overflowY: 'auto' }}
        defaultSelectedKeys={['1']}
        defaultOpenKeys={['sub1']}
        mode="inline"
      >
```

**Comment by GhazalehEslamifard** [comment]
My bad, I provided a new codeSandBox please check it again. I think sometimes scrollbars can be a good guide to show that there is an issue like this issue that we expect the Menu to fit completely into the Sidebar without overflowing! 
@afc163
