### ISSUE TITLE
Tabel 组件 固定头和列 会导致表头无法显示 【chrome 60】

### ISSUE THREAD

**Issue by Nicesunqi** [ant-design/ant-design#33595]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header](https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header)

### Steps to reproduce
官方示例就能重现这个问题。

### What is expected?
期望解决这个问题

### What is actually happening?
Tabel 组件 固定头和列 会导致表头无法显示

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | window |
| Browser | chrome 60版本 |

---
官方示例就能重现这个问题。

**Comment by yoyo837** [comment]
60 有点太老了

**Comment by MadCcc** [comment]
> 60 有点太老了

确实，考虑升级下 chrome 版本？现在已经 90 版本了 @Nicesunqi

**Comment by Nicesunqi** [comment]
@MadCcc 特殊原因，有些客户那边只能用60版本的chrome,  表头不显示的主要原因是  最后一列加fixed就会有问题

**Comment by afc163** [comment]
不再对老版本 Chrome 做支持，如果有需求，也欢迎排查后来给我们 PR。
