### ISSUE TITLE
Ant Upload should added unwrap result after submitted Form

### ISSUE THREAD

**Issue by tinhthatbonglai** [ant-design/ant-design#33594]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I suggest Ant Design added feature unwrap result for Upload component when file was uploaded and set value for Form.Item if Form finish to submitted as response from server instead of full response. Thanks! 

### What does the proposed API look like?
Like this:
`<Upload unwrapResult={true} />`

**Comment by afc163** [comment]
I don't realy understand it.

**Comment by tinhthatbonglai** [comment]
> I don't realy understand it.

![8f3ef](https://user-images.githubusercontent.com/97222866/148372845-69e5f7e2-bc8e-47d5-bdc2-a65523b1d456.png)

Here's value of Upload Form.Item after submitted, it should be return response field from server

**Comment by DaJianWu** [comment]
@tinhthatbonglai 
https://ant.design/components/upload-cn/#components-upload-demo-upload-manually

I think you can use this manual upload to only get the response results of the service.
