### ISSUE TITLE
antd支持横向表格吗？

### ISSUE THREAD

**Issue by SuperZero1** [ant-design/ant-design#33598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例如一个统计数据表 第一列是 2021年1月1日可以无限往后延伸，第一行是 早饭，午饭，晚饭这种，表格是 三列无限行。
如果反之，第一列是早中午，第一行是 日期。表格则会三列无限宽。所以这种统计数据横向表格比较方便。

### What does the proposed API look like?
同上。

**Comment by afc163** [comment]
不支持，可以看看 Descriptions 或者 https://s2.antv.vision/
