### ISSUE TITLE
列表组件，在固定表头情况下（使用sticky），无法做到列头筛选固定到表头，列头筛选会随滚动条滚动。如果使用getPopupContainer属性，又无法完整显示筛选条件，因为表头区域有overflow: hidden

### ISSUE THREAD

**Issue by YANGZHIQIANG1211** [ant-design/ant-design#33608]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nian-xing-tou-bu-zeng-jia-biao-tou-shai-xuan-cc93l?file=/index.js)

### Steps to reproduce
只有sticky属性，点击列头筛选后，滚动条滚动后，列头筛选页面会跟随滚动；使用sticky、getPopupContainer两个属性（将注释内容打开），点击列头筛选显示筛选页面，筛选条件显示不全

### What is expected?
在固定表头情况下（使用sticky），可以做到列头筛选固定在表头，不随滚动条滚动；或者使用getPopupContainer属性时，能够显示完整的筛选条件

### What is actually happening?
在固定表头情况下（无法设置纵向滚动条，需要处理的内容太多无法适用大部分场景，所以使用sticky），列头筛选会随滚动条一起滚动；使用getPopupContainer属性后，不会随滚动条滚动，但显示不全筛选条件

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.0 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
Duplicate of #29366
