### ISSUE TITLE
Would be nice to have a property which will remove the "OK" button for TimePiker and fire the onChange event on every click or on blur but not on "OK" btn click

### ISSUE THREAD

**Issue by Gherciu** [ant-design/ant-design#33600]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It resolves a big UX problem..Even if I'm using ant design for about 3years ...every time when I'm setting a date in TimePicker I just click on an hour and minute and then somewhere outside and I forget that "OK" button also should be clicked and in such cases, my date RESET to initial value...and I need again to set time and now to click this OK button......... It would be nice to have a property to control that...Or like in DatePicker...when we click on the date the onChange is triggered and we don't need to click on any useless OK button to confirm

### What does the proposed API look like?
The proposal is to remove this OK button from TimePicker or to add a property "confirmOnBlur" or  "confirmOnCLickOutside" or other maybe better-named property) which will hide this OK button and automatically confirm the value under the hood and trigger all needed events

**Comment by afc163** [comment]
I think we can improve it by trigger onChange when blur TimePicker, trace https://github.com/ant-design/ant-design/issues/21189

**Comment by opike** [comment]
Please provide a time picker that can behave like these date pickers where there is no OK button:
https://ant.design/components/date-picker#components-date-picker-demo-basic

Requiring the user to click OK and then reverting back to the original value if they close the picker without clicking OK is poor UX.

**Comment by standbyoneself** [comment]
I can't understand why maintainers are not involved to make the RangePicker with time selection more usable? How many issues or likes you need to make it just work as hundreds developers and thousands users asking for? Antd is surely one of the best UI Component Library, but requirement of clicking "OK" button in DatePicker is very annoying. Moreover, values don't save on blur, there is no programmatic way to set the value. Your explanations about your sight about UX/UI are very subjective. In result developers have to look for alternatives and adopt it for existing design. It's very sad

**Comment by ShiftcodeDream** [comment]
Hi, we need this functionnality too. UX/UI is very boring and ugly when you have several fields like this one in a formula. Specifications are very clear : when the user clicks on minutes, trigger onChange and hide the overlay. That's all we ask you. I do agree with other people. Another thing : every other UI (for example : `https://primereact.org/calendar/#time` ) uses "onBlur" to validate the time.

**Comment by therealnlee** [comment]
How is this feature going?

**Comment by kkx64** [comment]
It seems there is now a `changeOnBlur` prop on DatePicker and RangePicker which works exactly like this!

**Comment by ShiftcodeDream** [comment]
Great ! I just tested now (sorry for beeing so long to test). It works fine
!
Will be greatly appreciated by our users ! Thanks a lot :-)


Le mer. 17 mai 2023 à 15:07, Kiril Krsteski ***@***.***> a
écrit :

**Comment by imismailpe** [comment]
use the props
onSelect={handleTimeChange}
popupClassName="noFooterTimePick"
and on css:
.noFooterTimePick .ant-picker-footer{
    display: none;
 }
 This will remove footer with ok button and save the selected value on clicking outside.

**Comment by medmoudou** [comment]
Is anyone found a good solution ?

**Comment by dharam1890** [comment]
Here **antd** have some great props for **TimePicker.RangePicker**
`needConfirm={false}`  ==> Will remove ok button
`onPickerValueChange={(value)=> console.log(value)}`==> will give the value of time
