### ISSUE TITLE
  <Cascader />  嵌套 antd <Input /> 页面崩溃 

### ISSUE THREAD

**Issue by lk19940215** [ant-design/ant-design#33618]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
打开官方示例，自定义显示 CodeOpen链接。

从 antd 引入 Input 组件

```
<Cascader options={options} onChange={this.onChange}>
          <a href="#">Change city</a>
</Cascader>
```  
 替换为如下
```
<Cascader options={options} onChange={this.onChange}>
           <Input />
</Cascader> 
```
点击输入框，聚焦。 页面白屏

### What is expected?
页面不崩溃

### What is actually happening?
页面崩溃

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.0  |
| System | macos、windows |
| Browser | chrome |

**Comment by JX-Zhuang** [comment]
链接贴错了吧

**Comment by lk19940215** [comment]
> 链接贴错了吧
链接没错，复现步骤已修正。

**Comment by lk19940215** [comment]
> 链接贴错了吧

链接就是使用官方的CodeOpen链接即可。 复现步骤，已经重写，应该可以复现。   查看代码，是聚焦的时候， 有如下代码抛错
```
_this.getContainer = function () {
        var getDocument = _this.props.getDocument;
        var popupContainer = getDocument(_this.getRootDomNode()).createElement('div')
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'createElement')
    at Trigger._this.getContainer (index.js?0efc:356)
    at eval (Portal.js?5258:17)
```
```

**Comment by afc163** [comment]
目前官方文档里应该没有这种用法。

https://ant.design/components/cascader-cn

**Comment by lk19940215** [comment]
> 目前官方文档里应该没有这种用法。
> 
> https://ant.design/components/cascader-cn

v3 升级 v4 发现的BUG。 v3是可以这样用的。

**Comment by afc163** [comment]
看了一下，v3 的文档应该也没支持过这种用法 https://3x.ant.design/components/cascader-cn/

**Comment by lk19940215** [comment]
> 看了一下，v3 的文档应该也没支持过这种用法 https://3x.ant.design/components/cascader-cn/

` https://codesandbox.io/s/polished-dream-f0e9g?file=/index.js `
v3可用的链接

`https://codesandbox.io/s/custom-trigger-antd-4-18-2-forked-uimk6?file=/index.js`
v4构建显示无问题，聚焦后出现BUG链接。

以上。
虽然是非推荐的使用方法，但目的，只是反馈BUG。
毕竟不会闲着没事v3 升级 v4。

**Comment by JuSanZhi** [comment]
我也是遇到这个问题，请问解决了么

**Comment by Diluka** [comment]
> 最近更新到了4.18.0 版本，我也是遇到这个问题，请问解决了么。更新之前正常使用，更新之后报错 ![image](https://user-images.githubusercontent.com/24559368/149127895-9cef2dbf-d87a-415c-a8cb-ef8ec40a9d77.png) ![image](https://user-images.githubusercontent.com/24559368/149127965-3f483b34-71d6-4825-a905-79d3b8981b0f.png)

https://github.com/ant-design/ant-design/issues/35001#issuecomment-1223762766
简直笑死
