### ISSUE TITLE
Table组件的Table.EXPAND_COLUMN设置对树形数据的支持

### ISSUE THREAD

**Issue by perfylee** [ant-design/ant-design#33626]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
很高兴可以有`Table.EXPAND_COLUMN`的功能对展开列位置进行自定义，但是目前好像不支持对Table中树形数据的展开列，树形数据同样需要这样的功能，例如我做了一个支持拖拽手柄排序的树形Table，放在第一列的手柄受到展开按钮的影响很严重，想通过`Table.EXPAND_COLUMN`让展开按钮放到后面的列，不生效，会提示``` `expandable` is not config but there exist `EXPAND_COLUMN` in `columns`. ```

### What does the proposed API look like?
不需要增加额外的API

**Comment by afc163** [comment]
按目前的设计方案，树形数据的展开目前必须放在第一列。

**Comment by UnderMountain96** [comment]
> 你可以使用`expandIconColumnIndex`这个属性指定树形数据的展开列位置，但是官方在类型文件中提示应该使用`Table.EXPAND_COLUMN`替换这个属性，所以我不确定使用`expandIconColumnIndex`这个属性来指定树形数据的展开列位置是否会有什么不确定的bug，也不清楚官方为何要禁用此属性 @afc163 @perfylee


What to display Table.EXPAND_COLUMN in children column?

This sample is not working, it displays expandIconColumnIndex=0 and creates an empty column in the desired position:

```js
 const columns = [
        // here display expand column
        {
            title: 'ID',
            dataIndex: 'id',
            key: 'id',
        },
        {
            title: 'Created_at',
            dataIndex: 'created_at',
            key: 'created_at',
        },
        {
            title: 'Publication',
            children: [
                {
                    title: 'Title',
                    dataIndex: 'title',
                    key: 'title',
                },
                {
                    title: 'Author',
                    dataIndex: 'author',
                    key: 'author',
                },
                Table.EXPAND_COLUMN, // here display  empty column
            ],
        },
        {
            title: 'Note',
            dataIndex: 'note],
            key: 'note',
        },
       ]
```

**Comment by JamesFiitWork** [comment]
我也遇到了相同的问题。因此我被迫使用过时的 expandIconColumnIndex。

> 按目前的设计方案，树形数据的展开目前必须放在第一列。

问题是这不符合我开发的产品的设计。我需要把展开按钮放到其它列。
