### ISSUE TITLE
select mode=tag 输入内容在第一项，可以调整到最后一项吗

### ISSUE THREAD

**Issue by zyxbest** [ant-design/ant-design#33620]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
直接回车会导致选择一些未输入完的选项，可有办法将输入的内容放在队尾？
1. 如果搜索出来的话，可以优先选择搜索出来的；
2. 如果没搜到，也可以直接用输入内容作为新的tag

### What does the proposed API look like?
```jsx
last:True
```

**Comment by zombieJ** [comment]
`tag` 模式的设计就是用户输入优先，你的这个需求看起来就是标准的 Select。直接受控 `onSearch` 和 `onKeyDown` 事件来动态插入即可。
