### ISSUE TITLE
npm run build 报错！

### ISSUE THREAD

**Issue by ITtong** [ant-design/ant-design#3362]
![image](https://cloud.githubusercontent.com/assets/19646825/19233500/672e18fe-8f18-11e6-8bb3-4f1c40368117.png)
我的电脑上打包命令是这样的：
![image](https://cloud.githubusercontent.com/assets/19646825/19233514/7f810312-8f18-11e6-8309-1be2da7f0c36.png)
node_modules包.bin文件夹中的atool-build文件是这样的：
![image](https://cloud.githubusercontent.com/assets/19646825/19233551/ba3da50a-8f18-11e6-94b9-e17c757977ea.png)
求大神告知什么原因？
npm -v :3.10.6,
node -v :v4.4.5

**Comment by afc163** [comment]
删掉 node_modules 重新安装，国内建议使用 https://github.com/cnpm/cnpm

**Comment by ITtong** [comment]
@afc163 有没有更好的解决办法，node_modules应该是没有问题的，因为我把package.json文件中的启动命令改掉了，npm start命令是能跑的起来的。
![image](https://cloud.githubusercontent.com/assets/19646825/19261723/a6898b66-8fc5-11e6-9008-cd21d3a004f6.png)
那这么说有没有办法改一下package.json中的build命令。然后能正常云行的办法？

**Comment by ITtong** [comment]
@afc163 
![image](https://cloud.githubusercontent.com/assets/19646825/19264003/9115e516-8fd1-11e6-960a-b20947e828f0.png)
安装会出现这样的情况？是不是报错了。

**Comment by benjycui** [comment]
学会看 log 

红色只是 deprecated
