### ISSUE TITLE
ConfigProvider not working 

### ISSUE THREAD

**Issue by jabdon00** [ant-design/ant-design#33627]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/global-theme-antd-4-18-2-forked-ibymf)

### Steps to reproduce
change color 

### What is expected?
primary theme color change

### What is actually happening?
primary color not change 

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17 |
| System | 4.18.2 |
| Browser | Chrome |

---
its official sample for configprovider

**Comment by afc163** [comment]
See https://ant.design/docs/react/customize-theme-variable

```diff
-- import 'antd/dist/antd.min.css';
++ import 'antd/dist/antd.variable.min.css';
```
