### ISSUE TITLE
Create onTabAuxClick

### ISSUE THREAD

**Issue by lucasMarioza** [ant-design/ant-design#33621]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
On some newer browser, [middle click doesn't trigger `onClick` anymore, only `onAuxClick`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onauxclick). In that case, checking for `e.button === 1` in `Tabs.onTabClick` doesn't work.

### What does the proposed API look like?
It should follow the same types as we current have for `onTabClick`. Ideally it should be triggered on both, `onAuxClick` and on `onClick` if `button === 1` to support all browsers.
```jsx
<Tabs {...otherProps} onTabAuxClick={(key, e) => closeTab(key)}>
  <Tabs.TabPane closable tab="tab name" key={1}>tab content</Tabs.TabPane>
</Tabs>
```

**Comment by afc163** [comment]
```jsx
onTabClick={e => {
  if (e.button === 1) {
    // on middle click
  }
}}
```

Is it enough?
