### ISSUE TITLE
antd2.0.1国际化组件出错

### ISSUE THREAD

**Issue by zhangchunyin** [ant-design/ant-design#3363]
发生问题的环境是：LocaleProvider组件

antd 版本:V2.0.1
操作系统及其版本:Mac
浏览器及其版本:Chrome
您做了什么？

import { LocaleProvider } from 'antd';
import enUS from 'antd/lib/locale-provider/en_US';

您期待的结果是：正常运行

实际上的结果是：浏览器控制台报错
![image](https://cloud.githubusercontent.com/assets/9319388/19234078/f8a9a55c-8f1b-11e6-90d7-5444b8105d70.png)

替换成2.0.0能正常运行

**Comment by dreamcatcher081210** [comment]
这个没人理会吗？而且2.0.0的国际化（en）后，日期选择控件里除“Today”按钮国际化成功外，其余依旧是中文的。
@afc163 
@benjycui 
@yiminghe

**Comment by afc163** [comment]
这个阶段人手暂时不太够，别着急。

**Comment by yesmeck** [comment]
@zhangchunyin 提供下能重现的 demo?

**Comment by yiminghe** [comment]
看文档，moment 要单独设置下

**Comment by afc163** [comment]
第二个问题见：https://github.com/ant-design/ant-design/issues/3412#issuecomment-253406312

**Comment by benjycui** [comment]
在项目中测试没有问题，请确认你的 moment 正确依赖了，不知道你使用的 npm 版本是？

还有你使用 antd 是全量引入还是 babel-plugin-import|antd

**Comment by afc163** [comment]
没进一步反馈就关了。

**Comment by DefunctExodus** [comment]
Sorry English only.

I am actually seeing the same issue in chrome on Fedora 24

**Comment by afc163** [comment]
@DefunctExodus Try `2.1.0`.

**Comment by DefunctExodus** [comment]
Sorry I am answering via phone,  I am actually on 2.1.0

I started with a clean build yesterday and had the same issue. 2.0.0 works
because moment is not being defined in the en_us language file.

**Comment by afc163** [comment]
Could u give a reproducible repo for this?

**Comment by DefunctExodus** [comment]
Should be able to, not sure if I will get to it this morning but I will try.

essentially

`_moment2["default"].locale('en');` does not actually exist, when I looked at `_moment2["default"]` it would have actually needed to be `_moment2["default"].default().locale('en')` for it to work.

I assume it's related the `_interopRequireDefault` function

**Comment by DefunctExodus** [comment]
@afc163 

This should be a fairly basic repo showing the issue when trying to include the `Datepicker` module, Same base issue when using the `LocaleProvider` module.

It's possible I missed something when setting up `antd` , if so i apologize.

https://github.com/DefunctExodus/reimagined-spork

**Comment by benjycui** [comment]
@DefunctExodus it seems that you didn't use `antd-init` or `dva-cli`?

**Comment by DefunctExodus** [comment]
@benjycui 

That's correct.
 Sorry it was my understanding from the documentation that doing that would not be an issue so long as I was using the importer, I don't have any trouble with other components thus far with the exception of DatePicker & LocaleProvider  both which reference moment.

**Comment by benjycui** [comment]
It seems that we need some special webpack config for `moment.js`, for it has not been optimized for browser..

**Comment by DefunctExodus** [comment]
@benjycui 
That's what it appears to be. I have not had more time to dig into this though :/

**Comment by yesmeck** [comment]
@DefunctExodus After a few hours digging, I found that you are setting [es2015.module](https://github.com/DefunctExodus/reimagined-spork/blob/master/package.json#L60-L64) to false which  leads to the error you post.

And if you remove that config, you will encounter to another error `Uncaught TypeError: (0 , _reduxSaga2.default) is not a function(…)`, that because you are using webpack2, and webpack2 don't add `__es6module` flag to the es6 module currently (see https://github.com/webpack/webpack/issues/3168) which leads to babel will treat that es6 module as CommonJS module.

**Comment by DefunctExodus** [comment]
@yesmeck 

Thanks for the link to the webpack issue, I appreciate you looking into this. I am not sure where the really leaves me though.

I am new to the whole webpack setup however I would assume setting modules to `false` would prevent it from trying to use the commonjs loader (which was the suggested work around I believe?)

**Comment by yesmeck** [comment]
I'd recommend you to not use webpack2 as it's not officially released yet.

**Comment by benjycui** [comment]
@DefunctExodus you should close your issue after the problem is solved, thanks.

**Comment by benjycui** [comment]
@zhangchunyin try solution which is provided in this issue, or provide an re-producible repo, then you can re-open this issue.
