### ISSUE TITLE
how to replace the font to 'open sans' in antd?

### ISSUE THREAD

**Issue by skywalker2013** [ant-design/ant-design#33635]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.google.com.hk/search?q=how to change  the font in antd&newwindow=1&sxsrf=AOaemvJehTOAnTaBI7Cv_VXsr_jNTF0BEQ%3A1641713637886&ei=5Y_aYbfPNbHCmAXVg4vwBg&ved=0ahUKEwj31dXxk6T1AhUxIaYKHdXBAm4Q4dUDCA4&uact=5&oq=how to change  the font in antd&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsAM6BAgAEEM6CwguEIAEEMcBEKMCOgUIABCABDoFCC4QgAQ6BAgAEB46BAgAEBM6BQghEKABSgQIQRgASgQIRhgAUKsOWNk_YPFDaARwAngAgAG-A4gB4keSAQgyLTIzLjcuM5gBAKABAcgBCsABAQ&sclient=gws-wiz](https://www.google.com.hk/search?q=how to change  the font in antd&newwindow=1&sxsrf=AOaemvJehTOAnTaBI7Cv_VXsr_jNTF0BEQ%3A1641713637886&ei=5Y_aYbfPNbHCmAXVg4vwBg&ved=0ahUKEwj31dXxk6T1AhUxIaYKHdXBAm4Q4dUDCA4&uact=5&oq=how to change  the font in antd&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsAM6BAgAEEM6CwguEIAEEMcBEKMCOgUIABCABDoFCC4QgAQ6BAgAEB46BAgAEBM6BQghEKABSgQIQRgASgQIRhgAUKsOWNk_YPFDaARwAngAgAG-A4gB4keSAQgyLTIzLjcuM5gBAKABAcgBCsABAQ&sclient=gws-wiz)

### Steps to reproduce
如题

### What is expected?
replace the font

### What is actually happening?
it's hard to replace the font

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome, firefox, Edge |

**Comment by curly210102** [comment]
As I know, There are two ways to replace the font:
1. Customize Theme and set the `@font-family` variable, you can follow this guide [How to customize theme in antd](https://ant.design/docs/react/customize-theme)
2. Override css, add css declaration `body { font-family: open sans }` after import antd.css
