### ISSUE TITLE
hideOnSinglePage支持函数动态控制

### ISSUE THREAD

**Issue by sunxia628** [ant-design/ant-design#33648]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决分页pageSize切换时，hideOnSinglePage无法动态展示分页器；total<指定条数（默认pageSizeOptions中的最小值）且只有一页时隐藏（这个逻辑貌似多余，但开发者传入的pageSizeOptions不知道你们如何处理），避免pageSize设置过大时，无法切换分页！

### What does the proposed API look like?
pagination的hideOnSinglePage接受function类型，并能获取total,pageSize,current等分页参数，以动态返回hideOnSinglePage的值，控制分页器渲染

**Comment by afc163** [comment]
没看明白这个业务逻辑，当 pageSize 设置过大时切 hideOnSinglePage 为 true 时，总页数只有一页，此时分页隐藏，这种情况下不会有切换分页的需要。

**Comment by sunxia628** [comment]
比如我的示例里面列表有30条数据，pageSizeOptions:[10,20,50,100]；切换pageSize到50或100时，分页隐藏，我再想切换分页到10/20时没有入口了；这个hideOnSinglePage的判断逻辑不应该是只有一页，应该是pageSizeOptions中的最小值更合适。而且用户自定义的pageSize如果是5，是不会自动添加到pageSizeOptions中的，这个如果可以自动加入到pageSizeOptions更合理一些，因为没必要手动去修改pageSizeOptions配置，这个pageSize：5应该是用户想要的pageSizeOptions配置！

**Comment by afc163** [comment]
理解了，这个情况确实比较特殊。

不过这样的场景是否关闭 `hideOnSinglePage` 更合适呢？

**Comment by sunxia628** [comment]
关闭的话，只有一页还显示分页这个可能渲染多余DOM；所以希望pageSizeOptions可以自动带入用户设置的pageSize，并且hideOnSinglePage不再局限于只有一页就隐藏，而是最小pageSize且只有一页，用户不可能切换出多页的场景时隐藏，或者通过一个hideOnMinSinglePage的新属性实现上述功能；最简单的扩展为可接收function类型，这个给用户自定义且对系统的破坏性最小化！

**Comment by afc163** [comment]
hideOnSinglePage 的语义就是单页隐藏，通过 function 去改变其语义并不合理。如果有别的隐藏逻辑，建议自行封装状态。

```jsx
const hide = xx && yy;
return hide ? <Pagination /> : false;
```
