### ISSUE TITLE
inputNumber可否支持自定义上下icon

### ISSUE THREAD

**Issue by chenhongzhu1997** [ant-design/ant-design#33641]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前inputNumber的上下箭头和ued规则不同，需要适配，希望支持

### What does the proposed API look like?
支持icon适配

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/33914
