### ISSUE TITLE
defaultCheckedKeys In Tree Component not Working

### ISSUE THREAD

**Issue by jabdon00** [ant-design/ant-design#33659]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-18-2-forked-ixm9w?file=/index.js:1363-1381)

### Steps to reproduce
i want get node data from api and set it to tree with default checked node . i use fake data in reproduction and set them with useEffect but in tree the specified node not checked.

### What is expected?
default node checked.

### What is actually happening?
default node not checked

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 17 |
| System | 4.18.3 |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Change `defaultCheckedKeys` won't trigger component change. Use `checkedKeys` instead.
