### ISSUE TITLE
CheckboxGroup 验证问题

### ISSUE THREAD

**Issue by yhhwpp** [ant-design/ant-design#3365]
代码如下
```
<FormItem label="权限" >
  {getFieldDecorator('operation_list',{ initialValue: defaultOperationValue, rules:[{ required: true, message: '请选择权限' }]})(
                        <CheckboxGroup options={operationOptions} />
   )}
</FormItem>
```
![image](https://cloud.githubusercontent.com/assets/7929656/19235896/fc37a9a2-8f26-11e6-84aa-0e2c4c9de8cb.png)

结果为何是 Checkbox 全部选择 才验证通过
还有文档的getFieldDecorator参数的api没有  validate 说明
![image](https://cloud.githubusercontent.com/assets/7929656/19236041/ca1dd472-8f27-11e6-886e-a288cb4dce97.png)

**Comment by yhhwpp** [comment]
已经解决 需要加上 type: 'array' 为什么必须加上这个？

**Comment by afc163** [comment]
因为 value 的类型是 array ，默认不设是 string 。

**Comment by yhhwpp** [comment]
原来如此
