### ISSUE TITLE
Github issue reply netiquette 

### ISSUE THREAD

**Issue by aaarichter** [ant-design/ant-design#33651]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Well it would be great if this repo could establish a netiquette for issues and replies to be in English when the issue is stated in English. Right now most of the replies are in Chinese. Locking for answers or possible solutions is not possible and raises frustration. 

### What does the proposed API look like?
-

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4897#issuecomment-280265819
