### ISSUE TITLE
RangePicker onClick event not working

### ISSUE THREAD

**Issue by jtheberge** [ant-design/ant-design#33662]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-rangepicker-bug-no-onclick-control-nnd0r?file=/index.js:287-324)

### Steps to reproduce
Add onClick handler to RangePicker and check that it's not firing.

### What is expected?
Clicking anywhere on the RangePicker should fire click event handler.

### What is actually happening?
No call handler is set for onClick.

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome |

**Comment by JX-Zhuang** [comment]
@MadCcc Let me try
