### ISSUE TITLE
Checkbox.Group值value如果为数字会报错。

### ISSUE THREAD

**Issue by ayiaq1** [ant-design/ant-design#33663]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ayiaq1/pen/vYeVZNq?editors=001](https://codepen.io/ayiaq1/pen/vYeVZNq?editors=001)

### Steps to reproduce
value的值为数字

### What is expected?
正常显示

### What is actually happening?
报错。
components/checkbox/Group.tsx

checked={value.indexOf(option.value) !== -1}

value如果为数字报错

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | react |
| System | mac |
| Browser | Google Chrome 96 |

**Comment by MadCcc** [comment]
你给的 codepen 样例跑不起来

**Comment by ayiaq1** [comment]
不是跑步起来，  是value 为1 报错了。  如果value 为字符串就ok的。
