### ISSUE TITLE
BackTop target属性的使用问题

### ISSUE THREAD

**Issue by zds2015** [ant-design/ant-design#3366]
#### 发生问题的环境是：back-top组件

- antd 版本: 2.0.1
- 操作系统及其版本: win10
- 浏览器及其版本: chrome 49

#### 您做了什么？

  `<div>
    <div style={header}>固定头部</div>
    <div style={body} id='test'>
      <BackTop target={() => document.getElementById('test')} />
    </div>
    <div style={footer}>固定尾部</div>
    Scroll down to see the bottom right gray button.
  </div>`

用target来指定容器:  `<BackTop target={() => document.getElementById('test')} />`

#### 您期待的结果是：
  
能指定容器出现返回顶部的图标，并且图标的位置要正确

#### 实际上的结果是：
报错： getScroll.js:14   Uncaught TypeError: Cannot read property 'scrollTop' of null
看了源码，这应该是个bug，不知道什么时候能修复呢？

**Comment by afc163** [comment]
来个 PR 如何？

**Comment by zds2015** [comment]
问题主要是出在：BackTop target指定的元素和BackTop在同一个组件里一起渲染的话，就会有这个问题。另外，文档里BackTop也没有关于target的说明，能否补充完整？

**Comment by benjycui** [comment]
不知道你的业务场景是怎样？就是为什么滚动的主体不是 `window` 而是某个元素？

**Comment by zds2015** [comment]
@benjycui 头部和底部固定，中间body是根据内容来显示滚动条，这种场景应该也是比较常见的吧

**Comment by benjycui** [comment]
这种情况只要用 Affix 把头部和底部固定就可以了。

这个 bug 会修复，不过建议还是让 window 滚动，毕竟在刷新页面时，浏览器会记住 window 滚动的高度而不会记住里面某个元素的高度。
