### ISSUE TITLE
Cascader enable multiple, showSearch not working

### ISSUE THREAD

**Issue by B-sirius** [ant-design/ant-design#33671]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-lian-multiplepei-he-showsearch-jvlwf?file=/index.js)

### Steps to reproduce
1. 在级联输入框内输入搜索的值
2. 级联输入框出现下拉框，出现搜索出的备选项
3. 点击备选项或点击备选项的checkbox

### What is expected?
1. 触发onChange
2. 清空搜索值，选项被设置到输入框内
3. 下拉框关闭

### What is actually happening?
1. 没有触发onChange
2. 搜索值被清空，选项没有被设置到输入框内
3. 下拉框内容变为点击输入框出现的全量可选项

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.14.0 |
| System | macOs 11.0.1 |
| Browser | Chrome 97.0.4692.71 |

---
业务需要能够支持级联输入框同时支持多选与搜索的能力

**Comment by gitzhaochen** [comment]
same issue
