### ISSUE TITLE
Table表格设置rowSelection后，点击全选框，checkbox的选中态样式不对

### ISSUE THREAD

**Issue by binnerlee** [ant-design/ant-design#33676]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
1. 找到一个带选择框的示例；
2. 点击选择框；
3. 选中态样式错误，选中的行单元格背景色不一样。

### What is expected?
能正确选择，选中行的背景色不乱；

### What is actually happening?
目前在官方示例代码中，就能复现这个问题。
选中态样式错误，选中行单元格背景色不一致；
使用鼠标选择单元格内容时，单元格的内容会一直闪，有时候单元格的内容变成白色了。

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.14.0 |
| System | MAC 10.15.7 |
| Browser | Google Chrome 96.0.4664.110 |

**Comment by afc163** [comment]
没有发现你描述的问题，能否提供录屏或者截图？

**Comment by binnerlee** [comment]
> 没有发现你描述的问题，能否提供录屏或者截图？


https://user-images.githubusercontent.com/9876563/148903414-260a65c9-4921-4ba5-8477-7bade2278bec.mov

**Comment by binnerlee** [comment]
@afc163   google chrome 升级到97.0.4692.71版本没问题了。。。
谢谢回复。
