### ISSUE TITLE
vite build时rc-cascader报错

### ISSUE THREAD

**Issue by 314857493** [ant-design/ant-design#33689]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/314857493/react-ts](https://github.com/314857493/react-ts)

### Steps to reproduce
使用`yarn`安装后
使用`yarn build`进行构建

### What is expected?
正常构建

### What is actually happening?
构建失败 报
```
node_modules/rc-cascader/lib/Cascader.d.ts:66:18 - error TS2430: Interface 'SingleCascaderProps<OptionType>' incorrectly extends interface 'BaseCascaderProps<OptionType>'.
  Types of property 'onChange' are incompatible.
    Type 'OnSingleChange<OptionType> | undefined' is not assignable to type '((value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void) | undefined'.
      Type 'OnSingleChange<OptionType>' is not assignable to type '(value: ValueType, selectedOptions?: OptionType[] | OptionType[][] | undefined) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'ValueType' is not assignable to type 'SingleValueType'.
            Type 'SingleValueType[]' is not assignable to type '(string | number)[]'.
              Type 'SingleValueType' is not assignable to type 'string | number'.
                Type '(string | number)[]' is not assignable to type 'string'.
```

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | MacOS bigsur |
| Browser | chrome96.0.4664.110 |

**Comment by MadCcc** [comment]
ts strict 配置下的问题

**Comment by 314857493** [comment]
> ts strict 配置下的问题

需要将tsconfig的strist改成false吗？

**Comment by MadCcc** [comment]
> 需要将tsconfig的strist改成false吗？

应该是 `strictFunctionTypes` 规则，暂时支持还不完全，可以先 ignore 掉

**Comment by 314857493** [comment]
> 

好的谢谢  
目前情况直接执行vite build不执行tsc的话也是可以正常编译通过，但是感觉不是很好，希望后续可以解决

**Comment by 314857493** [comment]
> > 需要将tsconfig的strist改成false吗？
> 
> 应该是 `strictFunctionTypes` 规则，暂时支持还不完全，可以先 ignore 掉

好的谢谢
目前情况直接执行vite build不执行tsc的话也是可以正常编译通过，但是感觉不是很好，希望后续可以解决

**Comment by MadCcc** [comment]
fixed https://github.com/react-component/cascader/pull/236
