### ISSUE TITLE
升级最新版本之后，Drawer 的关闭按钮都去到左上角了，能否一键配置全 右上角

### ISSUE THREAD

**Issue by JuSanZhi** [ant-design/ant-design#33687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
主要是旧项目的升级，一下子突然都去到左边，产品要抓狂

### What does the proposed API look like?
一键配置全 右上角

**Comment by zhangliying0325** [comment]
同样遇到了这个问题，目前我采取解决的办法是：全局调整DrawerForm左上角x的样式——  .ant-drawer-close{position:absolute;right:0}
如果有更好的，欢迎大家提供！
