### ISSUE TITLE
Cascader级联选择多选模式下，选中次级目录，选择框中没有展示完整路径，通过tagRander进行定制，回调函数也无法获取完整路径信息

### ISSUE THREAD

**Issue by zffstruggling** [ant-design/ant-design#33683]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
1.多选模式下，选中次级目录，选择框无法展示完整路径
2.选中之后输入框展示numbe0，number0

### What is expected?
选中次级目录输入框展示：light0/number0，light1/number0

### What is actually happening?
number0，number0，number0

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16 |
| System | windows |
| Browser | google |

---
之前的4.18.0版本是展示完整路径的，更新之后就没了，如果输入框出现多个相同的次级目录名称，很容易混淆，很不友好

**Comment by yuanziyao** [comment]
遇到同样的问题，之前版本都是展示完整路径了，最近升级新版本后，选择框不展示完整路径，导致选择框中出现多个重名的选项，难以区分。
https://codesandbox.io/s/duo-xuan-antd-4-18-3-forked-jglwf?file=/index.js

**Comment by afc163** [comment]
如果之前版本是完整路径，那么可能是一个 bug， @zombieJ 来看看。

**Comment by afc163** [comment]
4.17.0 第一个支持 Cascader 多选的版本就没有支持完整路径：https://codesandbox.io/s/duo-xuan-antd-4-18-3-forked-s1ikz?file=/index.js

@yzy185

**Comment by yzy185** [comment]
> 4.17.0 第一个支持 Cascader 多选的版本就没有支持完整路径：https://codesandbox.io/s/duo-xuan-antd-4-18-3-forked-s1ikz?file=/index.js
> 
> @yzy185

4.17.0这个版本我不太清楚，我们是12月底升级到4.18.0版本。当时就是为了使用这个多选功能，官方文档也是展示完整路径的，之后大概一个星期后，这个多选就不展示完整路径了，我看更新日志也没提到关于多选功能变更的地方，就很差异

**Comment by zombieJ** [comment]
完整路径是 `rc-cascader` 重构 alpha 版本的 BUG

**Comment by yzy185** [comment]
> 

至少tagRander也应该能拿到选中节点完整路径信息吧 @zombieJ

**Comment by zombieJ** [comment]
> 至少tagRander也应该能拿到选中节点完整路径信息吧 @zombieJ

嗯，我这个这个需求是合理的

**Comment by yumengjuan1** [comment]
我用的4.18.3版本，多选时，给多个初始值，只会选中最后一个，有遇到的吗
<Cascader
style={{ width: 250 }}
placeholder="请选择"
options={[
{ label: '西安001', value: 'OU=西安001', children: null },
{ label: '杭州测试部', value: 'OU=杭州测试部', children: null },
{ label: '西安002', value: 'OU=西安002', children: null },
{ label: '杨戈部门', value: 'OU=杨戈部门', children: null },
]}
onChange={values => changeCascaderSelect(values, indexs)}
value={['OU=西安001', 'OU=杭州测试部']}
multiple
maxTagCount="responsive"
/>

**Comment by zombieJ** [comment]
> 我用的4.18.3版本，多选时，给多个初始值，只会选中最后一个，有遇到的吗

新开一个 issue

**Comment by yumengjuan1** [comment]
> > 我用的4.18.3版本，多选时，给多个初始值，只会选中最后一个，有遇到的吗
> 
> 新开一个 issue
中午开了一个，被关了，说和这个问题重复了，但是我把版本降到了4.17.0之后，加上多个默认值，页面直接报错了(value || []).join is not a function，更新到最新版本后，只会选中最后一个

**Comment by zombieJ** [comment]
> > > 我用的4.18.3版本，多选时，给多个初始值，只会选中最后一个，有遇到的吗
> > 
> > 
> > 新开一个 issue
> 
> 中午开了一个 #33778，被关了，说和这个问题重复了，但是我把版本降到了4.17.0之后，加上多个默认值，页面直接报错了(value || []).join is not a function，更新到最新版本后，只会选中最后一个

#33778 的重现 `value` 只有一个值

**Comment by yumengjuan1** [comment]
> > > > 我用的4.18.3版本，多选时，给多个初始值，只会选中最后一个，有遇到的吗
> > > 
> > > 
> > > 新开一个 issue
> > 
> > 
> > 中午开了一个 #33778，被关了，说和这个问题重复了，但是我把版本降到了4.17.0之后，加上多个默认值，页面直接报错了(value || []).join is not a function，更新到最新版本后，只会选中最后一个
> 
> #33778 的重现 `value` 只有一个值

麻烦你打开这个链接：https://codepen.io/meeenenengeng/pen/JjrqeyY?editors=001
或者复制代码试一下
<Cascader
          style={{ width: 250 }}
          placeholder="请选择"
          options={[
            { label: '西安001', value: 'OU=西安001', children: null },
            { label: '杭州测试部', value: 'OU=杭州测试部', children: null },
            { label: '西安002', value: 'OU=西安002', children: null },
            { label: '杨戈部门', value: 'OU=杨戈部门', children: null },
          ]}
          value={['OU=西安001', 'OU=杭州测试部']}
          multiple
          maxTagCount="responsive"
        />

**Comment by icodinglee** [comment]
请问这个问题最后解决了吗？

**Comment by icodinglee** [comment]
(value || []).join is not a function 这错误有人看吗？

**Comment by zombieJ** [comment]
`displayRender` 重构后支持了，这个我更新一下文档：https://codesandbox.io/s/duo-xuan-antd-4-18-7-forked-rs33kt?file=/index.js

**Comment by zombieJ** [comment]
另外，有其他问题的新开 issue 哈
