### ISSUE TITLE
Steps 中 labelPlacement="vertical" 且 type="navigation" 时的显示问题

### ISSUE THREAD

**Issue by sueja** [ant-design/ant-design#33681]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/s3mqy](https://codesandbox.io/s/s3mqy)

### Steps to reproduce
直接在官网提供的示例中修改，
在 Steps 中增加 labelPlacement="vertical" 属性

### What is expected?
不会出现横线在贯穿图标

### What is actually happening?
会出现横线在贯穿图标

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.14 |
| System | mac |
| Browser | Chrome 96.0 |

![2022-01-12_00-13-25](https://user-images.githubusercontent.com/3689199/148979548-eb896ed9-d1f5-4a9e-9a8d-4805a60219bf.jpg)

**Comment by afc163** [comment]
Your codepen is empty.

**Comment by sueja** [comment]
这个是官网的示例代码  https://codesandbox.io/s/s3mqy，然后在 Steps 中增加 labelPlacement="vertical" 属性

**Comment by afc163** [comment]
Reproduce: https://codesandbox.io/s/dao-hang-bu-zou-antd-4-18-2-forked-z9is6

**Comment by toSayNothing** [comment]
looks like a `style` problem, let me have a try? 🤣

**Comment by MadCcc** [comment]
> looks like a `style` problem, let me have a try? 🤣

pr welcome~
