### ISSUE TITLE
升级最新版本之后，Drawer 的关闭按钮都去到左上角了

### ISSUE THREAD

**Issue by JuSanZhi** [ant-design/ant-design#33688]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/#API](https://ant.design/components/drawer-cn/#API)

### Steps to reproduce
无

### What is expected?
抽屉组件 关闭按钮一键配置 右上角

### What is actually happening?
Drawer 的关闭按钮都去到左上角了

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | ^17.0.2 |
| System | window |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33081#issuecomment-982231383
