### ISSUE TITLE
嵌套 ConfigProvider 继承失效

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#33691]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-18-2-forked-xuzdc?file=/index.js:426-440)

### Steps to reproduce
ConfigProvider 嵌套使用

### What is expected?
子节点配置继承父节点配置

### What is actually happening?
子节点配置没有继承父节点配置

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | React 17 |
| System | WIN11 |
| Browser | Chrome 97 |

---
以前版本子节点配置会继承父节点配置

**Comment by afc163** [comment]
哪个版本是对的？

**Comment by nuintun** [comment]
@afc163 4.18.3 以前版本都对

![image](https://user-images.githubusercontent.com/1730277/149252144-ffde4329-8679-4aa0-b4a5-20f5b68d2a8d.png)
