### ISSUE TITLE
更新版本后 Cascader 无法使用

### ISSUE THREAD

**Issue by JuSanZhi** [ant-design/ant-design#33696]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
组件无法使用，直接拷贝官方文档的demo 下来允许，点击没有任何反应

### What is expected?
正常使用

### What is actually happening?
没有选择弹窗

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | ^16.8.6 |
| System | mac |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/24559368/149129662-448e6326-cf92-498f-877e-a8f4d55acc44.png)

**Comment by MadCcc** [comment]
没有复现你说的问题，刚开始 js 没加载完会点不开。

**Comment by zkcpps** [comment]
> 我昨天也更新组件库，Cascader点击无法反应，只有获得焦点，没有显示弹框

请问解决了吗

**Comment by JuSanZhi** [comment]
> 没有复现你说的问题，刚开始 js 没加载完会点不开。

我看下了dom， 发现组件渲染出来的时候.没有加载这个css ，导致点击无法反应，只有聚焦功能，并没有弹窗
![image](https://user-images.githubusercontent.com/24559368/149446670-015b2aff-3d57-4cde-81f5-35ac95b923bb.png)
然后我把 msfu 关闭 了。上面图片的css 就加载出来了，点击也都正常了，不过关于Cascader 嵌套Input使用导致页面崩溃的问题还是没有解决

**Comment by MadCcc** [comment]
> 然后我把 msfu 关闭 了。
听起来是 msfu 的缓存问题

> 不过关于Cascader 嵌套Input使用导致页面崩溃的问题还是没有解决
这个问题是指？如果没有相关 issue 的话可以新开一个 issue 讨论

**Comment by JuSanZhi** [comment]
> > 然后我把 msfu 关闭 了。
> 
> 听起来像是 mfsu 的缓存问题
> 
> > 不过关于Cascader 嵌套Input使用导致页面崩溃的问题还是没有解决
> 
> 这个问题是指？如果没有相关 issue 的话可以新开一个 issue 讨论

![image](https://user-images.githubusercontent.com/24559368/149447531-9756aaae-3c13-4290-afec-8a9fadb79e88.png)
![image](https://user-images.githubusercontent.com/24559368/149447552-737fb91b-a47b-48f5-a8e4-b107d1256d49.png)
点击组件的时候导致页面崩溃

**Comment by afc163** [comment]
> 不过关于Cascader 嵌套Input使用导致页面崩溃的问题还是没有解决

antd 的文档和演示没有提供过这种用法。

**Comment by JuSanZhi** [comment]
> mfsu

我看组件就是支持嵌套ReactNode，然后我尝试使用原生的input ，页面就没有报错，但是用antd 的Input 就不行

**Comment by JuSanZhi** [comment]
> mfsu

开启mfsu  导致 Cascader 默认宽度不加载，这个有解决方案么。因为项目比较大，不开启mfsu有点呛

**Comment by afc163** [comment]
可以反馈到 umi 仓库。

**Comment by ChenYu29** [comment]
请问有解决吗，遇到相同的问题
