### ISSUE TITLE
有前缀图标Input的hidden为true时，输入框不能正常消失

### ISSUE THREAD

**Issue by veryfine** [ant-design/ant-design#33692]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/san-zhong-da-xiao-antd-4-18-2-forked-uxf5v?file=/index.js)

### Steps to reproduce
将Input设置prefix和hidden={true}

### What is expected?
输入框正常消失

### What is actually happening?
输入框未消失（未隐藏）

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 16.8.6 |
| System | window 10 中文版 |
| Browser | chrome 96.0.4664.45 中文 |

**Comment by hydraZty** [comment]
有`prefix` 或 `suffix` 的情况会在`<input>`外创建一层 `<span>`，而 `hidden` 属性一直加在 `<input>` 上

**Comment by hydraZty** [comment]
I'll fix it

**Comment by boomler** [comment]
是否能永远给 input 加一个 span 这样还顺带解决了 disabled 态 tooltip 无法触发的问题？ @MadCcc @hydraZty

**Comment by hydraZty** [comment]
> 是否能永远给 input 加一个 span 这样还顺带解决了 disabled 态 tooltip 无法触发的问题？ @MadCcc @hydraZty

这个问题听着耳熟，最近好像有人提过 `disabled` Button 和 Tootip 冲突

需要谨慎的 tradeoff，毕竟大多数情况 span 是无意义的。

**Comment by boomler** [comment]
> 
相关bug: 
https://github.com/ant-design/ant-design/issues/33076
tooltip 会给 button等加一层 wrapper， input 如果加 span的话，span 可以用作这层 wrapper。tooltip 就不用处理了：
https://github.com/ant-design/ant-design/blob/2d484bbe474dc2058af8267cab0c9818292bafb5/components/tooltip/index.tsx#L106
但这样肯定也会带来 breaking change. 可以一起讨论一下。

**Comment by MadCcc** [comment]
> 但这样肯定也会带来 breaking change. 可以一起讨论一下。

dom 结构会变化。
disabled 和 tooltip 的冲突应该是 `pointer-events: none` 带来的，加一层 span 可能不是一个好办法，我理解这算是个 feature 了。
