### ISSUE TITLE
表格列固定，列比较多的时候，拖拽的时候，行的宽度不随着表格的宽度，定位错乱

### ISSUE THREAD

**Issue by heningyuan6256** [ant-design/ant-design#33697]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler](https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler)

### Steps to reproduce
react-sortable-hoc   ant-table   column fixed

### What is expected?
拖拽的时候，行的宽度随着表格的宽度，定位不变

### What is actually happening?
拖拽行的宽度会显示不固定的宽度，并且定位有问题

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
> 并且定位有问题

这个指的是？

**Comment by lihansir** [comment]
![image](https://user-images.githubusercontent.com/44010674/149291937-37c4e721-84a8-4348-bfe5-f7911699d29a.png)
应该说的是这两行列宽不一致吧。拖动的时候列宽失效了，全缩在一块

**Comment by afc163** [comment]
看了一下这和 https://github.com/clauderic/react-sortable-hoc 的实现方式有关，目前没什么好办法。
