### ISSUE TITLE
代码组建如何加载

### ISSUE THREAD

**Issue by falltodis** [ant-design/ant-design#337]
看了下git上代码，一直没看明白 nico怎么加载每个组建下面的index.jsx。index.jsx中也没有看到如何渲染组建。 demo中的*.md中 
![image](https://cloud.githubusercontent.com/assets/7006864/10065427/717fe2f2-62b8-11e5-8082-491f70dd039e.png) 似乎是在这边做了，但是不懂 components-carousel-demo-vertical 这种id的element在哪里创建的。 求释疑。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/ecafaa5bdb682234f9e99c50e4039a73ae4d2b87/site/templates/code.html#L1

**Comment by falltodis** [comment]
这边看到了，post.meta.id 这个id是如何生成的呢？ 另外index.jsx是什么地方配置的生成js的呢
