### ISSUE TITLE
Cascader在多选的模式下进行模糊搜索，不能选中值，没有触发onchange

### ISSUE THREAD

**Issue by guofen** [ant-design/ant-design#33704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sou-suo-antd-4-18-2-forked-m12ff?file=/index.js)

### Steps to reproduce
1. 输入一个关键字比如：'zhe'
2. 勾选模糊的下拉结果
3. 勾选不上，调试没有触发onchange

### What is expected?
输入关键字后出现结果，并能勾选上，触发onChange

### What is actually happening?
输入关键字后出现结果，不能勾选上，没有触发onChange

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 17.0.2 |
| System | macOS 11.4 |
| Browser | 90.0 |

**Comment by MadCcc** [comment]
duplicated https://github.com/ant-design/ant-design/issues/33671

**Comment by guofen** [comment]
> duplicated #33671

请问这个功能预计什么时候会发布上线呢？

**Comment by brother-forteen** [comment]
我也遇到了，什么时候能修复啊
