### ISSUE TITLE
Tabs 浏览器缩小 闪烁

### ISSUE THREAD

**Issue by Rangocold** [ant-design/ant-design#33702]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-18-2-forked-6ppjj?file=/index.js)

### Steps to reproduce
缩小浏览器至80%，然后拖拽浏览器以调整页面尺寸

### What is expected?
正常显示

### What is actually happening?
tabs闪烁

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | ^16.14.0 |
| System | macOs |
| Browser | 97.0.4692.71 |

**Comment by afc163** [comment]
你貌似覆盖了 tabs 的样式，这种情况我们没有办法保证在所有场景下没有问题，建议先自行查看覆盖样式的可能造成的影响，或提供不覆盖样式场景下的重现。
