### ISSUE TITLE
Tree element showing draggable icon even if element isn't draggable

### ISSUE THREAD

**Issue by belarusaed** [ant-design/ant-design#33708]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jviny)

### Steps to reproduce
1. Make draggable tree
2. Filter draggable items

### What is expected?
Expected that only draggable items will have draggable icon

### What is actually happening?
Every item have draggable icon, even if I actually can't drag element

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 17.0.2 |
| System | Linux fedora 5.15.12-200.fc35.x86_64 |
| Browser | Firefox 95.0.2 |

---
IDK is it actually bug, or it's just never been implemented, but it's UX problem in my mind

**Comment by Linhf163** [comment]
@MadCcc Let me try

**Comment by aliciasteiman** [comment]
I'm having the opposite issue... I have a Tree with draggable but the drag handler icons are not showing. The Tree is an overlay for a Dropdown, but even when I render it on its own the icons do not show. Any ideas?
