### ISSUE TITLE
使用 Icon   component 的方式去展示图标时，图标位置会发生偏移

### ISSUE THREAD

**Issue by Linhf163** [ant-design/ant-design#33703]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

- 原因为 line-height 引起的宽高不一致
![image](https://user-images.githubusercontent.com/32009993/149258581-984be322-4e51-4e29-96e5-81e45fd35bd5.png)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-2-forked-9xhp9?file=/index.js:227-236)

### Steps to reproduce
无

### What is expected?
图标旋转时不会抖动

### What is actually happening?
图标旋转时会抖动

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.9.0 |
| System | windows |
| Browser | chrome-87.0.4280.88 |

**Comment by afc163** [comment]
不加 `spin` 也有对齐问题：https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-2-forked-eiz1q

**Comment by Linhf163** [comment]
@afc163 `vertical-align: 0;` 能修复对齐问题，但是旋转抖动问题是因为 svg 与它的 box 宽高不一致导致的。不一致的原因可能是 `line-height: 1` 导致的。
![image](https://user-images.githubusercontent.com/32009993/149435210-20e3808e-f021-4871-83dc-1775dd62561c.png)
![image](https://user-images.githubusercontent.com/32009993/149435335-285c13d9-9a86-494b-a4af-d085915014e1.png)

**Comment by JX-Zhuang** [comment]
@afc163 能让我尝试修复一下吗

**Comment by afc163** [comment]
@JX-Zhuang sure.

**Comment by JX-Zhuang** [comment]
@afc163 fixed https://github.com/ant-design/ant-design/pull/33726
