### ISSUE TITLE
表单组件交互不一致，不符合设计规范

### ISSUE THREAD

**Issue by xiayue888** [ant-design/ant-design#33713]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
问题背景：
- 每个组件的间距不一致，导致视觉上体验不一致，开发使用开源组件时调试成本较大，导致开发效率降低。
- 如 https://ant.design/components/form-cn/ 中表单的间隔距离不一致

### What does the proposed API look like?
交互优化（无API示例）

**Comment by MadCcc** [comment]
哪里不一致呢

**Comment by sunxia628** [comment]
@xiayue888 你这样提问题没人看的懂啊，起码截两张图
![image](https://user-images.githubusercontent.com/26341016/149612763-6543d2ae-bb92-4cc2-984a-da937d08054c.png)
