### ISSUE TITLE
希望级联选择增加一个选择任意一级选项的功能

### ISSUE THREAD

**Issue by lx815** [ant-design/ant-design#33718]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在实际的业务场景中，有时候会遇到我只想选择父节点，并不想选中下面的子节点的情况。比如在做一个权限系统，我有页面权限和按钮权限，我在级联选择的时候，就只想选中这个页面，而这个页面下的按钮我都不选。这种场景，目前是没有办法实现的。

### What does the proposed API look like?
请参考elementui的级联选择，选择任意一级选项功能。https://element.eleme.cn/#/zh-CN/component/cascader#cascader-ji-lian-xuan-ze-qi

**Comment by afc163** [comment]
https://ant.design/components/cascader-cn/#components-cascader-demo-change-on-select
