### ISSUE TITLE
Divider能否提供draggable属性

### ISSUE THREAD

**Issue by xclw2000** [ant-design/ant-design#33719]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Divider能否提供draggable属性，实现可拖动功能

### What does the proposed API look like?
加个属性draggable

**Comment by MadCcc** [comment]
`draggable` 是原生的属性，可以直接添加
https://codesandbox.io/s/shui-ping-fen-ge-xian-antd-4-18-3-forked-npq8r
