### ISSUE TITLE
breadcrumb documentation not loading

### ISSUE THREAD

**Issue by xiaofan2406** [ant-design/ant-design#3371]
URL:
[https://ant.design/components/breadcrumb/](https://ant.design/components/breadcrumb/)

Console Error: 
`Uncaught SyntaxError: Unexpected token )                         demo.js:2`

I am using chrome 53.0.2785.143 m (64-bit). Is it just me or is the website itself having an error?

**Comment by afc163** [comment]
不知道什么原因，重新部署了就好了。感谢反馈~
