### ISSUE TITLE
table 配置scroll={{ x: "max-content", y: 240 }}，只有设置y的值，会导致表头换行，max-content失效

### ISSUE THREAD

**Issue by penglittlebai** [ant-design/ant-design#33721]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yxv7u?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/yxv7u?file=/index.js
![image](https://user-images.githubusercontent.com/87426994/149444841-3129459d-2bdf-496a-acac-14a656ef2caf.png)

### What is expected?
columns不设置宽度，设置scroll={{ x: "max-content", y: 240 }}，表头不换行

### What is actually happening?
设置scroll={{ x: "max-content", y: 240 }}，表头换行了

| Environment | Info |
|---|---|
| antd | 4.18.3 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31917#issuecomment-906259520
