### ISSUE TITLE
Image组件能否提供一个调用api触发图片预览显示

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design#33720]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
。

### What does the proposed API look like?
<Image trigger={ '<Button>预览按钮<Button/>'  } >

**Comment by MadCcc** [comment]
详细描述下你的场景？以及你想要的 API 有点难以理解

**Comment by lovesL** [comment]
> 详细描述下你的场景？以及你想要的 API 有点难以理解
场景：当只需要显示一张图片的时候 ，页面上又不太适合放当前图片需要通过按钮来触发

![image](https://user-images.githubusercontent.com/27960630/149444343-ac3913b6-a171-4d5c-9417-72da5762e5c7.png)

**Comment by MadCcc** [comment]
> 场景：当只需要显示一张图片的时候 ，页面上又不太适合放当前图片需要通过按钮来触发

通过点击按钮来预览图片是吧

**Comment by lovesL** [comment]
> > 场景：当只需要显示一张图片的时候 ，页面上又不太适合放当前图片需要通过按钮来触发
> 
> 通过点击按钮来预览图片是吧

对

**Comment by afc163** [comment]
控制 preview.visible: https://ant.design/components/image-cn/#previewType

**Comment by afc163** [comment]
https://codesandbox.io/s/zi-ding-yi-yu-lan-tu-pian-antd-4-18-3-forked-fjhff?file=/index.js

@MadCcc 可以补一个 demo。

**Comment by lovesL** [comment]
> https://codesandbox.io/s/zi-ding-yi-yu-lan-tu-pian-antd-4-18-3-forked-fjhff?file=/index.js
> 
> @MadCcc 可以补一个 demo。

谢谢
