### ISSUE TITLE
Table 组件在windows 微信pc浏览器打开，固定表头多列横向滚动时没有横向滚动条

### ISSUE THREAD

**Issue by BigBossTang** [ant-design/ant-design#33728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
在windows pc微信消息点开， 进入固定表头表格位置滚动

### What is expected?
显示滚动条

### What is actually happening?
没有滚动条

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 16.9.0 |
| System | windows |
| Browser | 微信浏览器 |

---
没有滚动条的显示对于用户来说不太友好， mac pc微信是有的

**Comment by afc163** [comment]
antd 目前支持的浏览器范围：https://github.com/ant-design/ant-design#-environment-support
