### ISSUE TITLE
Select 时 showSearch 模式下拉箭头可配置是否显示

### ISSUE THREAD

**Issue by lizzie** [ant-design/ant-design#3372]
![image](https://cloud.githubusercontent.com/assets/36899/19260500/a1c224de-8fbc-11e6-9fb4-dc1af14a883d.png)

其实这种模式交互上应该是类似于这种

![image](https://cloud.githubusercontent.com/assets/36899/19260531/e24a9dce-8fbc-11e6-81c0-80564826d20f.png)

以前记得搜索框是在下面菜单中的，不知道为什么现在挪到了输入框位置。感觉有点歧义。

**Comment by afc163** [comment]
不支持，可以自行覆盖。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1390
