### ISSUE TITLE
Pagination新增hideOnMinSinglePage属性通过函数控制total <= pageSizeOptions中的最小值时隐藏分页器

### ISSUE THREAD

**Issue by sunxia628** [ant-design/ant-design#33733]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[CodeSandbox查询列表demo](https://codesandbox.io/s/cha-xun-biao-ge-forked-w75h3?file=/App.tsx)
[hideOnSinglePage支持函数动态控制#33648](https://github.com/ant-design/ant-design/issues/33648)
比如我的示例里面列表有30条数据，pageSizeOptions:[10,20,50,100]；切换pageSize到50或100时，分页隐藏，我再想切换分页到10/20时没有入口了；这个hideOnSinglePage的判断逻辑是只有一页时隐藏分页器，hideOnMinSinglePage是total <= pageSizeOptions中的最小值时隐藏分页器。而且用户自定义的pageSize如果是5，是不会自动添加到pageSizeOptions中的，这个如果可以自动加入到pageSizeOptions更合理一些，因为没必要手动去修改pageSizeOptions配置，这个pageSize：5应该是用户想要的pageSizeOptions配置！
新增hideOnMinSinglePage功能可以有更多接口暴露给使用者，开发者基于此进行封装时，hideOnMinSinglePage判断逻辑和页面逻辑剥离，避免相同的判断逻辑在不同页面重复编写，提高开发者的效率和使用体验！

### What does the proposed API look like?
hideOnMinSinglePage默认为true，即total <= pageSizeOptions中的最小值时隐藏分页器;
另外hideOnMinSinglePage支持传入函数，`hideOnMinSinglePage: (total, pageSizeOptions) => total <= Math.min(...pageSizeOptions);
`

**Comment by afc163** [comment]
建议用这种方式解决：https://github.com/ant-design/ant-design/issues/33648#issuecomment-1010541421
