### ISSUE TITLE
When the InputNumber step is clicked, the decimal number over 6 decimal becomes scientific notation

### ISSUE THREAD

**Issue by mattfixme** [ant-design/ant-design#33731]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/polished-river-ohly2?file=/src/App.js)

### Steps to reproduce
when input number, the content of InputNumber will show scientific notation, content will become normal when lose focus

### What is expected?
always show number without scientific notation

### What is actually happening?
show number with scientific notation

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome |

---
the bug has been fixed by this merge request. see [this link](https://github.com/ant-design/ant-design/issues/24206). but now it's reproduce

**Comment by afc163** [comment]
Try `stringMode` in big number case.
