### ISSUE TITLE
Tooltip在自定义组件不能触发，即使用了forwardRef

### ISSUE THREAD

**Issue by ngolin** [ant-design/ant-design#33741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-18-3-forked-nc868)

### Steps to reproduce
hover上去不能出现tooltip, 去掉Span组件是可以的

### What is expected?
都能出现tooltip

### What is actually happening?
hover上去不能出现tooltip, 去掉Span组件是可以的

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | macos |
| Browser | chrome |

**Comment by linxianxi** [comment]
![image](https://user-images.githubusercontent.com/47104575/149854408-cf013ada-b2c0-42c8-b234-a50f9c697c04.png)
这样就行了
