### ISSUE TITLE
Typography组件

### ISSUE THREAD

**Issue by 1093722532** [ant-design/ant-design#33747]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/typography-cn/#header](https://ant.design/components/typography-cn/#header)

### Steps to reproduce
在排版组件中打开控制台，查看元素，会发现有一个拷贝出来的元素没有销毁

### What is expected?
是否应该销毁此copy出来计算容器的元素

### What is actually happening?
没有销毁元素

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 14.17.0 |
| System | mac |
| Browser | Chrome |

**Comment by afc163** [comment]
> 在排版组件中打开控制台，查看元素，会发现有一个拷贝出来的元素没有销毁

哪个元素？
