### ISSUE TITLE
Spin包裹div容器导致 包裹内的div容器宽高不一致？

### ISSUE THREAD

**Issue by strongyc** [ant-design/ant-design#33746]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Spin包裹div容器导致 包裹内的div容器宽高不一致，该如何解决？

### What does the proposed API look like?
Spin包裹div容器导致 包裹内的div容器宽高不一致，该如何解决？

**Comment by afc163** [comment]
Please use bug report template instead of a feature request template.
