### ISSUE TITLE
[Help Wanted] Antd Select single tag

### ISSUE THREAD

**Issue by ImmaxvelSolbeg** [ant-design/ant-design#33740]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have Select with 3 options. I choose option one => it's now active and then i open select again how can i tag only one option?  it is possible?

### What does the proposed API look like?
idk

**Comment by fameoflight** [comment]
@ImmaxvelSolbeg what was the solution?
