### ISSUE TITLE
[2.x] “Form 废弃 getFieldProps，请使用 getFieldDecorator”，快速升级？

### ISSUE THREAD

**Issue by zuiidea** [ant-design/ant-design#3374]
> - Form 废弃 getFieldProps，请使用 getFieldDecorator：
> 
> ```
> -  <Input placeholder="text" {...getFieldProps('userName', { ... })} />
> +  {getFieldDecorator('userName', { ... })(
> +    <Input placeholder="text" />
> +  )}
> 
> ```

项目中Form以前使用的getFieldProps，现在更换为getFieldDecorator，但是项目中多达几十个Form，Form.Item就更多了，这样的变化无法用全局替换来改，请问有没有什么办法可以快速升级？

**Comment by afc163** [comment]
可以不升级，不影响实际功能。新的页面和项目建议用 getFieldDecorator 。

**Comment by wjwu** [comment]
换成getFieldDecorator 一些控件验证功能无效 如Select、TreeSelect，我只是换了方法名，参数还是不变。

**Comment by benjycui** [comment]
@wjwu 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
