### ISSUE TITLE
a-checkbox-group的a-checkbox数据太多会导致卡顿，请问怎么优化呢？

### ISSUE THREAD

**Issue by xuxiaoman123** [ant-design/ant-design#33743]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
<a-checkbox-group
                v-model="checkedKeys"
                @change="onChange"
              >
                <a-row v-if="groupTree.length>0">
                  <a-col
                    :span="24"
                    v-for="value in groupTree"
                    :key="value.id"
                  >
                    <a-checkbox
                      :value="value.id"
                      class="Plancheckbox"
                      @change="SomeClick"
                    >
                      {{value.entityName}}
                    </a-checkbox>
                  </a-col>
                </a-row>
              </a-checkbox-group>

### What is expected?
checkbox点击反应快一些

### What is actually happening?
checkbox点击反应太慢

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | vue |
| System |  96.0.4664.93 |
| Browser | 谷歌 |

---
我这边条数超过1000，数据少还好，数据过多就会导致checkbox点击反应太慢

**Comment by afc163** [comment]
看上去反馈错地方了。
