### ISSUE TITLE
Show two x scrollbars in table after sticky

### ISSUE THREAD

**Issue by irenetang1993** [ant-design/ant-design#33762]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-lie-antd-4-18-4-forked-zuz53?file=/index.js)

### Steps to reproduce
一开始如果 table 出现 sticky 的话，点击搜索，横向滚动条只有一个；
打开控制台使 table 出现 sticky 的滚动条，点击搜素，横向滚动条有两个，一个是 sticky 的，一个是设置 scroll: { x: 'max-content' } 导致在 ant-table-body 上添加了 { overflow: auto hidden } 而产生的；

### What is expected?
sticky 之后，点击 Search 横向滚动条只有一个

### What is actually happening?
sticky 之后，点击 Search 横向滚动条有两个

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 18.0.0-a |
| System | macOS Catalina 10.15.4 |
| Browser | 92.0.4515.107 |

**Comment by busyzz-1994** [comment]
解决了吗@irenetang1993

**Comment by irenetang1993** [comment]
> 解决了吗@irenetang1993

等着官方解决呢😂

**Comment by chen-jh-github** [comment]
可以通过监听表格数据变化，触发hook滚动页面解决该问题
useEffect(() => {
  document.documentElement.scrollTop += 1;
  document.documentElement.scrollTop -= 1;
}, [dataSource]);

**Comment by chillyistkult** [comment]
Got the same issue any viable fix?

**Comment by Yugle** [comment]
合理设置getContainer()解决了该问题
sticky={{getContainer: () => document.getElementById('root') as HTMLElement}}

**Comment by edrmsgl** [comment]
Is there a practical example of the solution?

**Comment by Raloch** [comment]
useEffect(() => {
    const e = new Event('resize')
    window.dispatchEvent(e)
  }, [tableState.data])
  
 In the absence of a vertical scroll bar, triggering the scrollTop event cannot cause the rc-table scroll bar to recalculate; however, the resize event can trigger the calculation. This solved the problem in my scenario.

**Comment by doiya46** [comment]
> Reasonable setting of getContainer() solves the problem sticky={{getContainer: () => document.getElementById('root') as HTMLElement}}

If table inside a `scroll y` element like `main-layout`. Change to `document.getElementById('main-layout') `

**Comment by katoto** [comment]
+1 处理了吗

**Comment by coderboyQ** [comment]
@Yugle 我也遇到同样的问题，可以给个例子吗？

**Comment by goblin2018** [comment]
> 合理设置getContainer()解决了该问题 sticky={{getContainer: () => document.getElementById('root') as HTMLElement}}

这样设置的后果是，底部的滚动条没了。

**Comment by shaibam** [comment]
I saw that this issue still exists in antd 4 & 5.
I've fixed it by using:
```
.ant-table-sticky-scroll {  
  display: none;
}
```

**Comment by KresimirJurkovic** [comment]
> I saw that this issue still exists in antd 4 & 5. I've fixed it by using:
> 
> ```
> .ant-table-sticky-scroll {  
>   display: none;
> }
> ```

Tried this one, seemed reasonable, but unfortunately did not work. What did work was:
```
.ant-table-sticky-scroll-bar {  
	display: none;
}
```

**Comment by york-chen** [comment]
> 合理设置getContainer()解决了该问题 sticky={{getContainer: () => document.getElementById('root') as HTMLElement}}

应当是返回Table组件的第一个滚动父元素，然后再调整offsetScroll参数，因为滚动父元素可能设置了pading或者其它属性导致并不在最下方

**Comment by lizongxiao** [comment]
This is my current solution and works out of the box

```
<template>
  <div ref="wrapperRef" class="app-table-wrapper" :class="{ 'app-table-sticky': hasSticky }">
    <a-table v-bind="resolvedTableAttrs">
      <template v-for="(_, name) in $slots" #[name]="slotProps">
        <slot :name="name" v-bind="slotProps" />
      </template>
    </a-table>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useAttrs } from 'vue';

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  scrollResizeDelay?: number;
  stickyContainerId?: string;
}>();

const attrs = useAttrs();
const tableAttrs = computed(() => attrs);
const delay = computed(() => props.scrollResizeDelay ?? 100);
const hasSticky = computed(() => !!(attrs as Record<string, unknown>).sticky);
const stickyContainerId = computed(() => props.stickyContainerId ?? 'root');

let resizeTimer: number | undefined;
const wrapperRef = ref<HTMLElement | null>(null);
let scrollTarget: HTMLElement | Window = window;
let stickyContainer: HTMLElement | null = null;

const resolvedTableAttrs = computed(() => {
  const baseAttrs = tableAttrs.value as Record<string, unknown>;
  const sticky = baseAttrs.sticky;
  if (!sticky) {
    return baseAttrs;
  }
  const stickyConfig = typeof sticky === 'object' && sticky !== null ? sticky : {};
  if ('getContainer' in stickyConfig) {
    return baseAttrs;
  }
  return {
    ...baseAttrs,
    sticky: {
      ...stickyConfig,
      getContainer: () => stickyContainer || document.getElementById(stickyContainerId.value) || document.body,
    },
  };
});

const triggerResize = () => {
  window.dispatchEvent(new Event('resize'));
};

const handleScroll = () => {
  const sticky = (attrs as Record<string, unknown>).sticky;
  if (!sticky) {
    return;
  }
  if (isAtScrollBottom(scrollTarget)) {
    return;
  }
  if (resizeTimer) {
    window.clearTimeout(resizeTimer);
  }
  resizeTimer = window.setTimeout(() => {
    triggerResize();
  }, delay.value);
};

onMounted(() => {
  if (wrapperRef.value) {
    scrollTarget = getScrollParent(wrapperRef.value);
    stickyContainer = scrollTarget instanceof Window ? document.documentElement : scrollTarget;
  }
  scrollTarget.addEventListener('scroll', handleScroll, { passive: true });
});

onBeforeUnmount(() => {
  scrollTarget.removeEventListener('scroll', handleScroll);
  if (resizeTimer) {
    window.clearTimeout(resizeTimer);
  }
});

const getScrollParent = (node: HTMLElement) => {
  let current: HTMLElement | null = node.parentElement;
  while (current) {
    const style = window.getComputedStyle(current);
    const overflowX = style.overflowX;
    const overflowY = style.overflowY;
    if (/(auto|scroll|overlay)/.test(`${overflowX}${overflowY}`)) {
      return current;
    }
    current = current.parentElement;
  }
  return window;
};

const isAtScrollBottom = (target: HTMLElement | Window) => {
  const tolerance = 1;
  if (target instanceof Window) {
    const doc = document.documentElement;
    const scrollTop = doc.scrollTop || document.body.scrollTop;
    const clientHeight = doc.clientHeight || window.innerHeight;
    const scrollHeight = doc.scrollHeight || document.body.scrollHeight;
    return scrollTop + clientHeight >= scrollHeight - tolerance;
  }
  return target.scrollTop + target.clientHeight >= target.scrollHeight - tolerance;
};
</script>

<style scoped>
.app-table-wrapper {
  width: 100%;
}
</style>

```
