### ISSUE TITLE
TreeSelect 高亮条与设置值不同步

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#33767]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/treeselect-o8oc4)

### Steps to reproduce
用方向键通过高亮条选中后，再用onSearch设置值失效，默认还是高亮选中的值。

### What is expected?
设置值与高亮条同步

### What is actually happening?
设置值与高亮条不同步

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 17.0.2 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by MadCcc** [comment]
Duplicated https://github.com/ant-design/ant-design/issues/33161
