### ISSUE TITLE
<DatePicker /> 时间为 12 小时制，及设置 showTime 后，会触发两次 onChange

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#3376]
如题，[查看demo](http://codepen.io/ystarlongzi/pen/ORkWaK)

![111](https://cloud.githubusercontent.com/assets/2840462/19266123/aec9db68-8fda-11e6-83e1-dc53de44e388.gif)

**Comment by RaoHai** [comment]
https://github.com/ant-design/ant-design/commit/d8e9fff5ba37c23f8ef83aa4cb56a573988ca204#diff-34c1c9d6622f2b32f87f4de9a64f099bR75

这里改坏的，手动额外触发了一次。
