### ISSUE TITLE
2.0Tabs 是否可以支持根据TabPane的内容自动缩放

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#3377]
- antd 版本: 2.0.0
- 操作系统及其版本: WIN7
- 浏览器及其版本: Chrome V52

**Comment by afc163** [comment]
确实是 bug 。

**Comment by yesmeck** [comment]
https://github.com/react-component/tabs/issues/35

**Comment by abbish** [comment]
+1

**Comment by dreamcatcher081210** [comment]
+1，顺带提一句，楼主的codeopen，点了三四下，果断致盲，好了，不说了，我去看医生了。

**Comment by zhonggithub** [comment]
sorry, 我应该换个背景色

**Comment by plandem** [comment]
probably connected with #3304
