### ISSUE TITLE
using Typography.Link in history mode causes page to re-render

### ISSUE THREAD

**Issue by 1247748612** [ant-design/ant-design#33770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-jasper-2b5gb?file=/src/App.tsx)

### Steps to reproduce
cc codesandbox

### What is expected?
在history模式下期望与react-router-dom的link达到同样的效果

### What is actually happening?
在history模式下使用了Typography.Link会导致页面re-render

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 17 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/26737/files#r488769888

**Comment by 1247748612** [comment]
> See https://github.com/ant-design/ant-design/pull/26737/files#r488769888

这块[文档](https://ant.design/components/typography-cn/#Typography.Link-%E5%A6%82%E4%BD%95%E4%B8%8E-react-router-%E5%BA%93%E9%9B%86%E6%88%90%EF%BC%9F)容易误导人，让我误以为是执行完全等价的逻辑

**Comment by 1247748612** [comment]
基于Typography.Link封装一个提供于react-router的link的组件，提供相同的逻辑

```ts

/**
 * @see https://ant.design/components/typography-cn/#Typography.Link-%E5%A6%82%E4%BD%95%E4%B8%8E-react-router-%E5%BA%93%E9%9B%86%E6%88%90%EF%BC%9F
 * @see https://github.com/ant-design/ant-design/issues/33770
 */
export const RouterLink = ({
  navigate,
  onClick,
  target,
  ...args
}: LinkProps & {
  navigate?: () => any;
  onClick?: (event: React.MouseEvent<HTMLAnchorElement>) => any;
}) => {
  const props = {
    ...args,
    target,
    onClick(event: React.MouseEvent<HTMLAnchorElement, MouseEvent>) {
      try {
        if (onClick) {
          onClick(event);
        }
      } catch (ex) {
        event.preventDefault();
        throw ex;
      }

      if (
        navigate && // react-router-dom Link
        !event.defaultPrevented && // onClick prevented default
        event.button === 0 && // ignore everything but left clicks
        (!target || target === '_self') && // let browser handle "target=_blank" etc.
        !isModifiedEvent(event) // ignore clicks with modifier keys
      ) {
        event.preventDefault();
        navigate();
      }
    },
  };
  return <Typography.Link {...(props as any)} />;
};

```

**Comment by thomastvedt** [comment]
`<Breadcrumb.Item href={'/internal-url}>link</Breadcrumb.Item>` also causes a page reload? 🤔
