### ISSUE TITLE
SubMenu太几把卡了 能不能优化下 动画效果和si一样 阿里这么多人是不是天天划水不干活

### ISSUE THREAD

**Issue by 865086862** [ant-design/ant-design#33786]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
没解决

### What does the proposed API look like?
请参考elementui

**Comment by yoyo837** [comment]
开源项目请社区成员有意向的一起来完善它。
