### ISSUE TITLE
 Hide the message line in case of validation error.

### ISSUE THREAD

**Issue by yuki2006** [ant-design/ant-design#33780]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/nest-antd-4-18-4-forked-jc6t9?file=/index.js

Follow the link to the text box,When you erase the letters, an empty space appears.

The space is intentionally erased in terms of layout.

We want to use `getFieldsError()` , so we want to use this validation mechanism.

### What does the proposed API look like?
We want an option that does not show the message line.

**Comment by afc163** [comment]
```diff
      <Form.Item
        name={["user", "name"]}
        label="Name"
        style={{ marginBottom: 0 }}
        validateFirst
        initialValue="a"
+       help=""
        rules={[
          {
            validator(_, value) {
              if (value.length === 0) {
                return Promise.reject();
              }
              return Promise.resolve();
            }
          }
        ]}
      >
        <Input />
      </Form.Item>
```

**Comment by yuki2006** [comment]
Thank you comment.

If we put this on, there will be a gap, 

![image](https://user-images.githubusercontent.com/1004620/150304165-964f5d3c-b233-4b6d-a3e1-83852152482d.png)


![image](https://user-images.githubusercontent.com/1004620/150304364-b7842825-2152-4b4e-a27a-7f22d090c7e5.png)

**Comment by afc163** [comment]
```
help={null}
```

**Comment by yuki2006** [comment]
In that case, there will be a gap in case of validation error.

![image](https://user-images.githubusercontent.com/1004620/150306505-902d1191-6647-48d1-b27a-57bd370af088.png)

**Comment by german-st** [comment]
> In that case, there will be a gap in case of validation error.
> 
> ![image](https://user-images.githubusercontent.com/1004620/150306505-902d1191-6647-48d1-b27a-57bd370af088.png)

Same problem. Waiting for a decision

**Comment by xzedx** [comment]
+1
