### ISSUE TITLE
How I can focus Select and auto drop down select.options.

### ISSUE THREAD

**Issue by manzxiao** [ant-design/ant-design#33787]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/manzxiao/pen/BawebBZ?editors=001](https://codepen.io/manzxiao/pen/BawebBZ?editors=001)

### Steps to reproduce
I have many Select components. I need autofocus them when users click `Tabs key`. Now, I use React.useRef  to get Select instance, and use ref.current.focus(). It autofocus now, but the drop down options are not appeared  

### What is expected?
the drop down options are auto appeared  

### What is actually happening?
the drop down options are not appeared  

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.2 |
| System | all |
| Browser | chrom |

**Comment by afc163** [comment]
Use `open` and `onOpenChange` to control Select.
