### ISSUE TITLE
DatePicker locale doesn't update.

### ISSUE THREAD

**Issue by dcruz1990** [ant-design/ant-design#33797]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hkdd2?file=/App.tsx)

### Steps to reproduce
Configure dynamic locale change via ConfigProvider

### What is expected?
All components gets locale updated.

### What is actually happening?
All components gets locale updates but DatePicker that keeps in en_US

| Environment | Info |
|---|---|
| antd | 4.10.0 |
| React | 17.0.1 |
| System | Linux |
| Browser | Chrome 95 |

**Comment by julianklumpers** [comment]
You need to update the underlying date library (standard Moment).

**Comment by afc163** [comment]
See https://ant.design/components/config-provider/#components-config-provider-demo-locale
