### ISSUE TITLE
table列排序影响鼠标事件，点击按钮会触发排序

### ISSUE THREAD

**Issue by KellenHe** [ant-design/ant-design#33791]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

https://codesandbox.io/embed/shai-xuan-he-pai-xu-antd-4-18-4-forked-bkwmb?fontsize=14&hidenavigation=1&theme=dark

### What problem does this feature solve?
例如table列头中加了按钮，并设置该列支持排序，这时候点击按钮会触发排序

### What does the proposed API look like?
期望点击按钮不会触发排序

**Comment by KellenHe** [comment]
@afc163 不好意思，没有描述清楚，不是不能触发按钮，是点击了按钮之后也会触发排序。

https://codesandbox.io/embed/shai-xuan-he-pai-xu-antd-4-18-4-forked-bkwmb?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
https://codesandbox.io/s/shai-xuan-he-pai-xu-antd-4-18-4-forked-l1ml4
