### ISSUE TITLE
AntD-Icon library dropdown arrow in Select component cannot be clicked on

### ISSUE THREAD

**Issue by charles-otto** [ant-design/ant-design#33796]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-yjwqn?file=/index.js)

### Steps to reproduce
1) Add an AntD <Select /> component
2) Specify a suffixIcon attribute for the <Select /> component.  In this case, the <CaretDownOutlined /> component from the ant-design/icons library was used.
3) In the browser, click on the dropdown arrow

### What is expected?
The dropdown menu should expand when the dropdown arrow was clicked.

### What is actually happening?
The dropdown menu does not expand.  Nothing occurs.

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 16.13.1 |
| System | Ubuntu 20.04.2 LTS |
| Browser | 92.0.4515.131 (Official Build) (64-bit) |

---
Not specifying the suffixIcon attribute for the <Select /> component resolves this issue and allows the dropdown arrow to expand the dropdown menu.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27479#issuecomment-719903848
