### ISSUE TITLE
Table.EXPAND_COLUMN, Table.SELECTION_COLUMN 展示顺序有问题

### ISSUE THREAD

**Issue by yuxuan** [ant-design/ant-design#33793]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-kong-zhi-biao-ge-shu-xing-antd-4-18-4-forked-svj3m?file=/index.js)

### Steps to reproduce
在动态控制表格属性示例中，添加Table.EXPAND_COLUMN, Table.SELECTION_COLUMN，顺序错误

### What is expected?
顺序与传入的columns顺序保持一直

### What is actually happening?
顺序错误

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | React |
| System | Mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
```
const tableColumns = columns.map((item) => ({
      ...item,
      ellipsis: state.ellipsis
    }));
```
这里，column 被 map 过了，Table.EXPAND_COLUMN 和 Table.SELECTION_COLUMN 自然就判断不了了
