### ISSUE TITLE
switch的宽度无法自动调整吗

### ISSUE THREAD

**Issue by asoqa** [ant-design/ant-design#3380]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？
```
<Switch checkedChildren={'有效'} unCheckedChildren={'无效'} />
```
当有两个以上字符时，没有办法显示完整。看api的文档，没有找到相关属性可以进行调整的。
难道必须进行样式的覆盖？

**Comment by afc163** [comment]
来个 PR 如何？
