### ISSUE TITLE
动态加载的Cascader有children的时候点击父级还是会执行loadData

### ISSUE THREAD

**Issue by jayt1001** [ant-design/ant-design#33803]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9pmz9?file=/index.js:0-1247)

### Steps to reproduce
# 描述
有子级的级联选择数据时，点击父级就直接进行loadData了

---

# 代码如下
```
import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { Cascader } from 'antd';

const optionLists =[
  {
    value: 'zhejiang',
    label: 'Zhejiang',
    // isLeaf: true,
    children: [
      {
        value: 'hangzhou',
        label: 'Hangzhou',
        isLeaf: false,
      },
    ],
  },
]

const LazyOptions = () => {
  const [options, setOptions] = React.useState(optionLists);

  const onChange = (value, selectedOptions) => {
    console.log(value, selectedOptions);
  };

  const loadData = selectedOptions => {
    const targetOption = selectedOptions[selectedOptions.length - 1];
    targetOption.loading = true;

    // load options lazily
    setTimeout(() => {
      targetOption.loading = false;
      targetOption.children = [
        {
          label: `${targetOption.label} Dynamic 1`,
          value: 'dynamic1',
        },
        {
          label: `${targetOption.label} Dynamic 2`,
          value: 'dynamic2',
        },
      ];
      setOptions([...options]);
    }, 1000);
  };

  return <Cascader options={options} loadData={loadData} onChange={onChange} changeOnSelect />;
};

ReactDOM.render(<LazyOptions />, document.getElementById('container'));
```

### What is expected?
有子级的级联选择数据时，点击最后一层的子级才进行loaddata

### What is actually happening?
有子级的级联选择数据时，点击父级就直接进行loadData了

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 17 |
| System | Windows |
| Browser | chrome |

**Comment by MadCcc** [comment]
https://codesandbox.io/s/dong-tai-jia-zai-xuan-xiang-antd-4-18-4-forked-390td?file=/index.js
You can control when to load data yourself.

**Comment by jayt1001** [comment]
谢谢

**Comment by jayt1001** [comment]
> https://codesandbox.io/s/dong-tai-jia-zai-xuan-xiang-antd-4-18-4-forked-390td?file=/index.js 你可以自己控制何时加载数据。

谢谢
