### ISSUE TITLE
Antd version 4 is not working from Shared component, But v3 is working fine from Shared Project.

### ISSUE THREAD

**Issue by prabhat-gc** [ant-design/ant-design#33807]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/vigorous-minsky-12b5k
![image](https://user-images.githubusercontent.com/87984498/150495262-2fcc1d9a-14d1-4ba9-9f24-62c658868f51.png)

### Steps to reproduce
If you try to reuse antd v4 component like Password, Button, Tooltip, Icons etc.. it will through error of like `The above error occurred in the <Button>` component:`

### What is expected?
It should not through any error as of now antd v3 is working fine with shared component.

### What is actually happening?
Not able to analysis the reason. but antd v4 is not working with shared component.

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 16.14.0 |
| System | Any |
| Browser | Any |

---
If it works,Pls suggest a step how can we reuse antd v4 components from shared project

**Comment by prabhat-gc** [comment]
Here, it is
https://codesandbox.io/s/vigorous-minsky-12b5k

**Comment by prabhat-gc** [comment]
We have made separate react project as component library named shared and reusing the components in other projects.
it was working fine until we were using antd version 3  but issues are coming when we are moving to antd version 4.

**Comment by MadCcc** [comment]
Your CodeSandbox is not working now.  :(
BYW, your project seems not complete, did you use monorepo?

**Comment by prabhat-gc** [comment]
here is the git repo 
https://github.com/prabhat-gc/shared-lib-example
Pls clone & run. you will understand the issue.

**Comment by prabhat-gc** [comment]
@MadCcc did you check this git repo link.

**Comment by MadCcc** [comment]
Have you check your react version?

**Comment by prabhat-gc** [comment]
yes, checked with latest version `react` , `react-dom` & `react-scripts` all, not worked.

**Comment by MadCcc** [comment]
Emm... I don't think this is an issue of antd. Antd v4 has migrated most of its components to react hook API.
Since you are using shared project, please follow the instruction of this warning. Maybe your project has more than one react versions, you can check it with `npm ls react`.
Or you may need monorepo to help you organize your project, such as lerna or yarn workspaces.

**Comment by prabhat-gc** [comment]
same version of react present in project. still not working. i have tried it multiple way to resolve. like using `resolution` to `package.json` also.  nothing worked for me. pls help !!

![image](https://user-images.githubusercontent.com/87984498/151510932-777fa515-ef67-4da0-b473-6a0722a25f1e.png)
