### ISSUE TITLE
Dropdown and similar components not working without motion styles

### ISSUE THREAD

**Issue by geuarg1y** [ant-design/ant-design#33808]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-dropdown-not-working-without-motion-styles-mzw1t)

### Steps to reproduce
1. Import dropdown or similar component (autocomplete, select, etc) from 'es' or 'lib' folder.
2. Import appropriate .css file from same folder (not .less).
3. Without motion styles component doesn't work.

### What is expected?
Dropdown component opens and closes by clicking on the control element.

### What is actually happening?
Component opens but does not close by clicking on the control element

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | Chrome 97.0.4692.99 |

---
In My Humble Opinion:
 - Motion styles are just decorates the components.
 - The functionality of components should not depend on animation styles.
 - Dropdown or select should opens and closes without any styles.

**Comment by afc163** [comment]
```diff
- import "antd/es/dropdown/style/index.css";
+ import "antd/es/dropdown/style";
```

**Comment by geuarg1y** [comment]
Thanks for solution, but both paths includes global styles.
In my project, I solved it like this:
```less
@import '~antd/es/style/themes/variable.less';
@import '~antd/es/style/mixins';
@import '~antd/es/style/core/motion';

```

The original message was not how to connect styles, but the logic of the component should not depend on decorative styles.
