### ISSUE TITLE
Upload组件为picture-card类型时，由隐藏上传按钮改为显示后，上传按钮有时会闪烁

### ISSUE THREAD

**Issue by credred** [ant-design/ant-design#33819]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-hodgkin-jhhos?file=/src/App.tsx)

### Steps to reproduce
删除任何一张图片

### What is expected?
上传按钮直接在第一行显示

### What is actually happening?
上传按钮先在第二行显示，在要删除的图片动画结束后，上传按钮又跳到第一行

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 17.0.2 |
| System | windows |
| Browser | Chrome 97.0.4692.71 |

**Comment by codedart2018** [comment]
官方示例还有抖动，没处理？？？

**Comment by codedart2018** [comment]
把动画去掉吧，这个动画又丑，又抖动
