### ISSUE TITLE
[Input] assemble focus behavior to  `focus` property

### ISSUE THREAD

**Issue by HomyeeKing** [ant-design/ant-design#33824]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
handle focus behavior by just one focus `property` not invoking focus `method` within useEffect

### What does the proposed API look like?

`<Input   focus="start | end | all | auto| preventScroll"  /> ` and can work with autofocus

exmaple:
```jsx
<Input  autoFocus  focus="start"  /> //  autofocus --> cursor start
<Input  autoFocus  focus="auto"  /> //  same with autofocus
```

**Comment by afc163** [comment]
Please use `node.focus()` `node.setSelectionRange()`

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLInputElement/setSelectionRange

**Comment by HomyeeKing** [comment]
@afc163  I know that, but what I want is just invoke foucs behavior by property, no need to combine the useEffect and the focus methods
