### ISSUE TITLE
Table组件 filterMode='tree' 且使用 filterSearch 开启筛选项的搜索时，节点高亮时仅能使英文数字高亮，中文高亮异常（本质上是 Tree组件 使用 filterSearch 时的节点高亮问题）

### ISSUE THREAD

**Issue by Gylllll** [ant-design/ant-design#33827]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shu-xing-shai-xuan-cai-dan-antd-4-18-5-forked-thlfd)

### Steps to reproduce
1. 点击 Name 列的筛选，在搜索框输入 `joe`
2. 观察高亮的节点，第一个搜索项只有 `joe1` 正常高亮，中文部分无法正常高亮
![image](https://user-images.githubusercontent.com/52419853/150776312-c031c791-3dcd-4ce5-9a77-59d912f4596d.png)

### What is expected?
中文也正常高亮

### What is actually happening?
中文没有高亮

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.1 |
| System | window10 |
| Browser | Chrome 97.0.4692.71 |

---
建议将下列样式代码中的  `font-weight: 500`  改为 `font-weight: 600` 来修复问题：
https://github.com/ant-design/ant-design/blob/master/components/tree/style/mixin.less#L118

![image](https://user-images.githubusercontent.com/52419853/150776191-d98ccd40-c0b7-4424-a59c-8073c1255122.png)

**Comment by afc163** [comment]
<img width="309" alt="图片" src="https://user-images.githubusercontent.com/507615/150901046-69d3d55e-db56-4c82-8011-c461c8115ab5.png">

可以支持，这和具体的中文字体有关，antd 默认都走 `font-weight: 500`，不做特别对待。

**Comment by DuFangY** [comment]
Now antd's css has been imported from Js by default (CSS-in-JS), how should it be modified?
