### ISSUE TITLE
Checkbox Group mark interval using shift key

### ISSUE THREAD

**Issue by herbertpimentel** [ant-design/ant-design#33828]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Checkbox Group defines a set of checkbox that are related to each other. I was expecting this to be able to check for example the first item in this set and then the N item, while holding down the shift key, and it checks all the checkbox in the interval. 

Just like the Table component does. 

From my point of view, It will help to keep the behaviour consistence across all the components.
A easily allow you se select a range of values to act on.

### What does the proposed API look like?
we may can enable disable that feature using the CheckboxGroup component, but as I see it as expected it may should be available out of the box just like in the Table component

<CheckboxGroup checkInterval={true} />

**Comment by afc163** [comment]
There is no same interaction in native input checkbox or other UI libraries. I may have to pass it.
