### ISSUE TITLE
table 嵌套子表格，宽度不够的情况下，内容溢出

### ISSUE THREAD

**Issue by ace0109** [ant-design/ant-design#33834]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-nested-table](https://ant.design/components/table-cn/#components-table-demo-nested-table)

### Steps to reproduce
查看antd官网的嵌套子表格例子，浏览器宽度调整小一点

### What is expected?
正常显示子表格

### What is actually happening?
子表格内容溢出
![image](https://user-images.githubusercontent.com/18433582/150919463-17f4f553-e510-430f-8d6c-c19b69ecf721.png)

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 16.9.43 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
可以给子表格也加上 scroll.x 属性，使其可以横向滚动。
