### ISSUE TITLE
多Popover时，点击气泡非close区域，气泡会无故消失

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design#33839]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-ride-tukuh?file=/src/App.js)

### Steps to reproduce
点击气泡（非close区域），气泡会消失

### What is expected?
希望是官方的效果（从浮层内关闭，https://codesandbox.io/s/bk6r8）

### What is actually happening?
多个气泡，无故消失，还不好控制

| Environment | Info |
|---|---|
| antd | 4.14.0 |
| React | react17.0.2 |
| System | win10 |
| Browser | 谷歌97.0.4692.99 |

**Comment by wooxyz** [comment]
![image](https://user-images.githubusercontent.com/33221294/150959021-f894258b-b28c-4fbf-b719-43bdfcff7cdd.png)

**Comment by afc163** [comment]
你的真实场景是啥，我感觉应该有更好的交互方案。

**Comment by wooxyz** [comment]
真是场景：一组卡片，每个卡片中有操作功能（弹出气泡卡片，选用气泡的原因是，位置友好）对应的close是文本框，回车后关闭气泡。我现在只要一点击气泡任何区域，就会消失，连输入都不能。即使我界面交互不好，就用这种方式，那如何解决？

**Comment by MadCcc** [comment]
```diff
const handleVisibleChange = (visible, id) => {
    if (visible) {
      setState({ visible, show: id });
-    } else {
-      setState({ visible: true, show: -1 });
    }
  };
```

**Comment by wooxyz** [comment]
> ```diff
> const handleVisibleChange = (visible, id) => {
>     if (visible) {
>       setState({ visible, show: id });
> -    } else {
> -      setState({ visible, show: -1 });
>     }
>   };
> ```

这种方式我也试过，我点击非气泡卡片区域时，为啥气泡不消失（输入框中，同样回车消失），官网示例是可以的

**Comment by wooxyz** [comment]
![image](https://user-images.githubusercontent.com/33221294/151085556-b8300edd-e4d0-4d4c-83cd-12ac51dd1c63.png)
 把文本框去掉，就显示读取的内容。为啥不能像官网示例那样，还是点击图中非红色框中，不能实现让气泡关闭？参考https://codesandbox.io/s/bk6r8。@MadCcc

**Comment by MadCcc** [comment]
你的使用方法比较诡异。。原本的 feature 是点击 popover 不会关闭的，在你的用例中实际上触发了 onVisibleChange。
我的建议是换一个交互方式，比如使用 Modal 代替 Popover。

**Comment by wooxyz** [comment]
popover弹的位置好点。虽然奇怪，但也是一种场景吧，如果能换成其他的（还要控制显示位置），我就不来提问了。。。
