### ISSUE TITLE
Antd SubMenu key attribute not setting the value showing "undefined" in DOM. Collapse not working

### ISSUE THREAD

**Issue by Umar-Farooq-Shafi** [ant-design/ant-design#33830]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/umarfarooqshafi/pen/rNYBrWd](https://codepen.io/umarfarooqshafi/pen/rNYBrWd)

### Steps to reproduce
design the submenu tab in the sidebar using react

### What is expected?
show the clicked sub-tab(s) in the sidebar

### What is actually happening?
all of the sub-tab un-collapsed

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 16.13.1 |
| System | window 10 21390.2025 |
| Browser | MS Edge 97.0.1072.69 (x64) |

**Comment by Umar-Farooq-Shafi** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-gtrpl?file=/index.js

**Comment by Umar-Farooq-Shafi** [comment]
![image](https://user-images.githubusercontent.com/62417503/150916001-5179c7cb-4388-40b0-930b-93231bf7f6ea.png)

**Comment by phuctran2901** [comment]
I have the same problem, is there any way to fix it?
