### ISSUE TITLE
Support custom icon for Button loading state

### ISSUE THREAD

**Issue by florianMo** [ant-design/ant-design#33842]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
User may need to modify the default loading state icon in Button (LoadingOutlined), for example if he wants to use the Spin component. For now it is not possible to modify the loading state icon for Button.

### What does the proposed API look like?
We could have a `loadingIcon: ReactNode` props on Button, Select, and any other interactive component supporting the `loading` props, pretty much like the `icon` props on Button.

**Comment by MadCcc** [comment]
We may not introduce this feature. You can custom loading icon with HOC, adding icon in children.

**Comment by heiyu4585** [comment]
这样吗
https://codesandbox.io/s/elegant-breeze-um04i?file=/src/App.js

**Comment by WarnerHooh** [comment]
请问modal里面的ok button loading如何自定义呢？
<img width="675" alt="image" src="https://github.com/ant-design/ant-design/assets/12759641/11b7e056-91bd-4f2b-acbd-49d500d86db0">
