### ISSUE TITLE
Table组件能否提供一个属性  屏蔽鼠标移入表格时 不触发自定义的render 

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design#33850]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当对表格合并行列时,初始加载表格正常,但是鼠标移入表格后，表格合并行列 出现错乱问题

### 初始加载正常的表格
![image](https://user-images.githubusercontent.com/27960630/151086114-82845163-e831-48c1-9bf3-070dc1231123.png)

### 鼠标移入表格后表格出现错乱，鼠标移出也无法恢复原貌
![image](https://user-images.githubusercontent.com/27960630/151086220-73b97b39-e0cc-47c2-9dd4-4f45abf8f561.png)

### 一下是我的代码
![image](https://user-images.githubusercontent.com/27960630/151086482-b8330094-6314-432c-a226-21a27f3453b1.png)

### What does the proposed API look like?
这个看你们怎么设计吧  只希望能达到预期效果就行了

"antd": "^4.18.5",

**Comment by MadCcc** [comment]
不是很明白你的问题产生的原因，另外 ProTable 的问题可以去 ant-design-pro 求帮助

**Comment by lovesL** [comment]
> 不是很明白你的问题产生的原因，另外 ProTable 的问题可以去 ant-design-pro 寻求帮助，如果是 table 的问题请提供复现
我弄个复现

**Comment by lovesL** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-627ui?file=/App.jsx
@MadCcc  已复现

**Comment by MadCcc** [comment]
建议换一个稳定的 render 方法
参考：https://codesandbox.io/s/antd-reproduction-template-forked-zi5gq?file=/App.jsx

**Comment by lovesL** [comment]
> 建议换一个稳定的 render 方法 参考：https://codesandbox.io/s/antd-reproduction-template-forked-zi5gq?file=/App.jsx

。。。。。哎呀 ,  丢人了,  谢谢老哥了
