### ISSUE TITLE
[Compile Error] "Variable @root-entry-name is undefined" Error on antd:4.18.5

### ISSUE THREAD

**Issue by AxiosLeo** [ant-design/ant-design#33853]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/AxiosLeo/antd-less-import-error-repo](https://github.com/AxiosLeo/antd-less-import-error-repo)

### Steps to reproduce
cd reproduction

yarn install

yarn build   # or yarn start

### What is expected?
Compile without any errors

### What is actually happening?
Compile Error ：“Variable @root-entry-name is undefined”

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | macos 12.1 |
| Browser | Google Chrome Version 97.0.4692.99 (Official Build) (x86_64) |

**Comment by zombieJ** [comment]
https://github.com/umijs/plugin-layout/blob/master/src/layout/style.less  这个看起来 `@umi/plugin-layout` 自己还有额外样式？

@PeachScript 能确认一下这个插件还需要不？

**Comment by phuthien007** [comment]
I have met issue and this is my solution.
First you must update new version of less, react, react-dom, antd.
Next you replace by code "~antd/dist/antd.less" and done.
![image](https://user-images.githubusercontent.com/62065030/165278510-80c8db4b-8e3f-4451-8ef8-eb03a953a783.png)

**Comment by ahmadalibaloch** [comment]
any update?

**Comment by ahmadalibaloch** [comment]
The issue not found on an older version `"antd": "4.9.4"`.

**Comment by PeachScript** [comment]
> The issue not found on an older version `"antd": "4.9.4"`.

Yep, `antd@4.17.0` updated the way to use Less variables, but `@umijs/plugin-layout` did not.

**Comment by PeachScript** [comment]
This bug has been fixed in `@umijs/plugin-layout@0.18.3`.
