### ISSUE TITLE
分页器能提供支持自定义上下页按钮的图标吗？

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/ant-design#33868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如想用的按钮的图标并不是默认的，想更换下按钮图标

### What does the proposed API look like?
可以传组件icon

**Comment by afc163** [comment]
暂不支持。
