### ISSUE TITLE
You cannot nest <Dropdown /> components

### ISSUE THREAD

**Issue by etanb** [ant-design/ant-design#33865]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-fdvx5?file=/index.js) 

### Steps to reproduce
Right click on the parent area, and then right click on the child area. You'll see both context menus appear. We're using the `trigger={['contextMenu']}` variation.

### What is expected?
It would be great if the Dropdown furthest down the chain took precedent OR at least if there was someway to tap into that event to change it's default behavior. Instead, both are appearing when just the Dropdown on the child element should appear. Maybe there's a way to stopPropigation on the child Dropdown?

### What is actually happening?
Both context menus are showing up.

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 16.13.0 |
| System | macOS Big Sur 11.6.1 |
| Browser | Firefox 96.0.2 |

**Comment by afc163** [comment]
See https://codesandbox.io/s/antd-reproduction-template-forked-yvs64

**Comment by etanb** [comment]
@afc163 thank you -- is this worth adding to the docs? didn't see anything related to "nested dropdowns".

**Comment by etanb** [comment]
Seems like if you open the parent one, then right click on the child one, the parent one remains open because the event bubbling has been cancelled.

![testDropDown](https://user-images.githubusercontent.com/516877/151317349-539ab0a3-35fb-4e28-b603-13a8fd1432b7.gif)
