### ISSUE TITLE
当select为多选时,值为null会出现空白的tag

### ISSUE THREAD

**Issue by rollYouth** [ant-design/ant-design#33863]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-q5u9qy?file=index.js](https://stackblitz.com/edit/react-q5u9qy?file=index.js)

### Steps to reproduce
将select选择框设置为多选,value={null}

### What is expected?
不应该出现tag

### What is actually happening?
出现了一个空白的tag

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 17 |
| System | win |
| Browser | chrome-97 |

**Comment by afc163** [comment]
多选的空值不建议用 null，请使用 `[]`。
