### ISSUE TITLE
Select with search demo does not expand

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#3386]
Select with search code example does not expand, selectable options are not shown. https://ant.design/components/select/#components-select-demo-search

Tested with Chrome Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/3ac6532577333ce8c03bb9c8f7bcf9e5ad3e1ca4 break it..
