### ISSUE TITLE
中英文语言下设计模式概览内容不一致

### ISSUE THREAD

**Issue by Sira-chen** [ant-design/ant-design#33867]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/spec/overview-cn](https://ant.design/docs/spec/overview-cn)

### Steps to reproduce
切换中英文

### What is expected?
内容一致

### What is actually happening?
不一致

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | macOS  version 11.6 |
| Browser | google |

**Comment by c0dedance** [comment]
https://github.com/ant-design/ant-design/pull/35055 本次pr解决了该issues
