### ISSUE TITLE
修改样子的方式能提供好的解决方法吗？现在都是在浏览器中找到对应的节点，css类名，然后进行覆盖修改。总感觉这样很麻烦，有什么好的方式来支持自定义样式吗？

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/ant-design#33870]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
修改样子的方式能提供好的解决方法吗？现在都是在浏览器中找到对应的节点，css类名，然后进行覆盖修改。总感觉这样很麻烦，有什么好的方式来支持自定义样式吗？

### What does the proposed API look like?
有更快捷和方便的方式就行

**Comment by MadCcc** [comment]
其实是不希望用户自己魔改的，所以不太会提供你说的这种功能

**Comment by MadCcc** [comment]
https://ant.design/docs/react/customize-theme-cn
v4 可以利用 webpack 配置来修改 less 变量

**Comment by wangyuan0108** [comment]
> https://ant.design/docs/react/customize-theme-cn v4 可以利用 webpack 配置来修改 less 变量

那就是自定义主题了

**Comment by MadCcc** [comment]
魔改是没有边界的，提供再好的工具也会有人去覆盖 class 提供的样式。
不知道你是不是想要 MUI 的 classes 这种 API，这个在我看来也没有减少学习成本。
