### ISSUE TITLE
textarea 设置maxLength 的时候，在前面输入内容会替换掉最后一个字符

### ISSUE THREAD

**Issue by darknessjs** [ant-design/ant-design#33872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wen-ben-yu-antd-4-18-5-forked-m2w5w?file=/index.js)

### Steps to reproduce
输入内容到maxLength的时候，光标移到前面再输入

### What is expected?
无法输入新字符

### What is actually happening?
最后一个字符被清掉了

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | 16.14.0 |
| System | MACOS |
| Browser | Chrome 97 |

**Comment by chenyizhongx** [comment]
好像是因为统一用maxlength截取导致的问题，我尝试解决下

**Comment by jiaozitang** [comment]
认领issue

**Comment by chenyizhongx** [comment]
> 认领issue

老兄，你这样不是很礼貌
