### ISSUE TITLE
Table rowExpandable不可展开时，自定义expandIcon没有隐藏

### ISSUE THREAD

**Issue by BoBoooooo** [ant-design/ant-design#33881]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-star-qxtw8?file=/index.js)

### Steps to reproduce
见codesandbox demo

### What is expected?
行不可展开时隐藏自定义折叠Icon

### What is actually happening?
行不可展开时没有隐藏自定义折叠Icon

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.2 |
| System | MacOS 12.1 |
| Browser | Chrome 97.0 |

**Comment by MadCcc** [comment]
我们为 expandIcon 提供了 expandable 参数：
https://codesandbox.io/s/kind-joliot-sbu0y?file=/index.js
