### ISSUE TITLE
Card: can title not be wrapped with h3?

### ISSUE THREAD

**Issue by xiaofan2406** [ant-design/ant-design#3388]
#### versions
2.0.1

For Card component, `title` accepts an `React.Element`, but it is wrapped with an `h3` regardless. It can cause many styling issues.

In my own case, I got an warning `warning.js:36 Warning: validateDOMNesting(...): <h3> cannot appear as a child of <h3>.`, because my `title` element contains an h3 element.

Is it possible to change the logic so that it is wrapped with `h3` if title is a string, and with `div` if title is an element?

**Comment by afc163** [comment]
👌 Give us a PR~

**Comment by afc163** [comment]
@xiaofan2406 ping~

**Comment by xiaofan2406** [comment]
@afc163  sure. will work on it.
