### ISSUE TITLE
全局样式配置下进度条展示问题

### ISSUE THREAD

**Issue by ssh1-del** [ant-design/ant-design#33884]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/#components-config-provider-demo-theme](https://ant.design/components/config-provider-cn/#components-config-provider-demo-theme)

### Steps to reproduce
- 上面链接下滑至步骤条
- 第一个步骤条的第2步的环展示问题

### What is expected?
步骤条的第2步的没有外环

### What is actually happening?
步骤条的第2步的有外环

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | react |
| System | macOS Monterey 12.2  |
| Browser | 版本 97.0.4692.71（正式版本） (x86_64) |

**Comment by ssh1-del** [comment]
![image](https://user-images.githubusercontent.com/66853043/151507395-673cb792-9a04-4b83-8155-6e1bd4eddbeb.png)

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/151508979-ccb2a399-d57c-4952-b4ba-3ba620124c5f.png)
我这里显示正常的，动了什么配置吗

**Comment by ssh1-del** [comment]
> ![image](https://user-images.githubusercontent.com/27722486/151508979-ccb2a399-d57c-4952-b4ba-3ba620124c5f.png) 我这里显示正常的，动了什么配置吗

我重新打开一下，现在正常的
