### ISSUE TITLE
Tabs animated property does not work

### ISSUE THREAD

**Issue by jinli** [ant-design/ant-design#3390]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: Windows 7 Professional
- 浏览器及其版本: Chrome 53.0.2785.143 m

#### 您做了什么？

            <Tabs type="card" animated={false}>
                <TabPane tab="我的待办" key="myToDo" animated={false}>我的待办</TabPane>
                <TabPane tab="待审" key="toReview" animated={false}>待审</TabPane>
                <TabPane tab="待审" key="reviewed" animated={false}>待审</TabPane>
                <TabPane tab="待审" key="done" animated={false}>待审</TabPane>
            </Tabs>

#### 您期待的结果是：

TabPanel 显示时的 animation 会被关掉

#### 实际上的结果是：

Animation 还在，"animated" property 根本不起作用

**Comment by afc163** [comment]
还未发布。https://github.com/ant-design/ant-design/issues/3324
