### ISSUE TITLE
Conditional rendering of modal footer buttons cause closing issue on "ESC" key pressed

### ISSUE THREAD

**Issue by maciag-dev** [ant-design/ant-design#33917]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-lucy-6ckpo?file=/src/App.js)

### Steps to reproduce
Open modal, cklick on  "Submit 1" button, press "ESC" button

### What is expected?
Modal closes after pressing the  "ESC" button

### What is actually happening?
Modal remains open

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | Linux |
| Browser | Chrome, Firefox |

**Comment by jrr997** [comment]
I have done some researches.

Only when the focus is in the Modal, the Modal can listen to the event that the ESC is pressed. In your example, when the Submit1 button is clicked, the button gains focus and is subsequently destroyed. At this time, the focus defaults to the Body 
element, and clicking the ESC key at this time does not trigger the Modal keyboard event.

The easiest solution is to remove the key from the two buttons in the example. In this case, when one of the buttons is clicked to trigger the view update, react will not destroy the element (this is related to react's diff), but modify the properties of the button. At this time, the focus is still in Modal, and keyboard events can be monitored.

**Comment by amed** [comment]
Any news on this one?

**Comment by afc163** [comment]
You should focus it after button is rendred in first time: https://codesandbox.io/s/dreamy-kate-gx8f4r?file=/src/App.js
