### ISSUE TITLE
Modal.confirm removes autoFocus from Input component

### ISSUE THREAD

**Issue by GuentherK** [ant-design/ant-design#33918]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/internationalization-antd-4-18-5-forked-20f46?file=/index.js)

### Steps to reproduce
use Modal.confirm({...}) and add a <Input autoFocus /> element as content

### What is expected?
The Input component will be rendered with autoFocus

### What is actually happening?
The Input component is not rendered with autoFocus

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | latest |
| System | Windows 10.0.19042 Build 19042 |
| Browser | Microsoft Edge Version 97.0.1072.76 |

---
I know this is a missuse of the modal.confirm albeit it should not remove properties of react nodes which are used as content node

**Comment by afc163** [comment]
```diff
+ autoFocusButton: false,
```

**Comment by AGPX** [comment]
@afc163  This bug must be reopened, because it doesn't work anymore with latest version (AntD=5.3.2, React=18.2.0). You can test it quickly by updating the versions of libraries in the sandbox you provided.
