### ISSUE TITLE
Bug in Upload control

### ISSUE THREAD

**Issue by ronniejoseph** [ant-design/ant-design#33926]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/upload](https://2x.ant.design/components/upload)

### Steps to reproduce
Please try uploading the attached file of below url in any of the demo Upload controls to reproduce the error on your website.

https://favpng.com/png_view/eagle-logo-image-download-eagle-logo-clip-art-png/xtRYiNdH

### What is expected?
Image uploads without any error.

### What is actually happening?
The Upload component shows "Upload error" for some specific files even after successful uploads.

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 16.13.1 |
| System | Wndows 10 Pro |
| Browser | Google Chrome Version 97.0.4692.99 (Official Build) (64-bit) |

**Comment by mrnonz** [comment]
Can you try with update your Chrome to Version 98.0.4758.80 ?

**Comment by MadCcc** [comment]
2.x version is not maintained now.
Please provide reproduction if there's still problem with 4.x.

**Comment by perany** [comment]
I also found it there is bug at chrome 97.xx.xx.xx, and it words after I update chrome to 98.xx.xx.xx

**Comment by ronniejoseph** [comment]
issue could not be fixed even after trying chrome update, used this attribute customRequest={asyncRequest} in the upload component instead and seems to be working fine

const asyncRequest=async({file,onSuccess})=>{
setTimeout(()=>{
onSuccess("ok");
},0);
}
