### ISSUE TITLE
"Show code"-icon not available on antd webside

### ISSUE THREAD

**Issue by SimBig** [ant-design/ant-design#33925]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tooltip/#header](https://ant.design/components/tooltip/#header)

### Steps to reproduce
open link with dev tools

### What is expected?
"Show code"-icon should be visible to toggle the show code.

### What is actually happening?
Right now the toogle show code is possible but the user does not see the icon and multiple timeouts are visible in the devtools:

Connection timeout from gw.alipayobjects.com for requested svg's

![image](https://user-images.githubusercontent.com/26680884/152312650-9be0dddb-e481-457f-91c1-dec820c4b234.png)

gw.alipayobjects.com/zos/basement_prod/43d010fa-71ac-44e3-8475-bb77d95c331c.svg:1 GET https://gw.alipayobjects.com/zos/basement_prod/43d010fa-71ac-44e3-8475-bb77d95c331c.svg net::ERR_CONNECTION_TIMED_OUT

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | react |
| System | win10 |
| Browser | chrome, firefox |

**Comment by MadCcc** [comment]
Is it working now?
