### ISSUE TITLE
Export interface in Button and Collapse

### ISSUE THREAD

**Issue by Sckmdg** [ant-design/ant-design#33929]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our project we use the following styled components https://www.npmjs.com/package/@types/styled-components

We try to override styles for "Button" and "Collapse"  in your library, 
but keep getting the following error:

```Exported variable 'StyledActionsButton' has or is using name 'CompoundedComponent' from external```

This feature could allow to reuse your components (2 actually, only those that was mentioned had the error above)

### What does the proposed API look like?
could you, pls, export the following

```
export interface ButtonInterface
  extends React.ForwardRefExoticComponent<ButtonProps & React.RefAttributes<HTMLElement>> {
  Group: typeof ButtonGroup;
  __ANT_BUTTON: boolean;
}

export interface CollapseInterface extends React.FC<CollapseProps> {
  Panel: typeof CollapsePanel;
}
```

**Comment by zombieJ** [comment]
Is `typeof` help?

https://codesandbox.io/s/silly-framework-u5bhu6?file=/src/App.tsx
