### ISSUE TITLE
Cascader Can no longer handle quotes (")

### ISSUE THREAD

**Issue by N00nDay** [ant-design/ant-design#33928]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5rgk0?file=/index.js)

### Steps to reproduce
Use a double quote in the value using version 4.18.5. This was allowed in all previous versions.

### What is expected?
I can use a double quote in my value.

### What is actually happening?
I receive the following error when selecting a value with a double quote -DOMException: Failed to execute 'querySelector' on 'Element': 'li[data-path-key="Mastic__RC_CASCADER_SPLIT__Carvedwood Double 4""]' is not a valid selector.

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | macOS Big Sur 11.6.2 |
| Browser | Chrome 97.0.4692.99 |

**Comment by ppanthony** [comment]
Fwiw, you can escape this manually in the JSON and it works. 

` 'Carvedwood Double 4\\"',`

**Comment by MadCcc** [comment]
Maybe a bug since 4.18.4 is working
