### ISSUE TITLE
Custom colors not applied to Timeline with Icons

### ISSUE THREAD

**Issue by ALF3run** [ant-design/ant-design#33932]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/timeline-with-icon-color-issue-antd-4-18-5-isejx)

### Steps to reproduce
1. Create a new Timeline component.
2. Customize the dot property of a Timeline.Item with any of AntD Icon components
3. Customize the color property of the previous Timeline.Item with a custom color other than `blue`, `green`, `red` and `gray`

### What is expected?
The custom color should be applied to the icon in the Timeline.Item

### What is actually happening?
The icon is colored black

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | Windows 10.0.19042 |
| Browser | Google Chrome 97.0.4692.99 (64-bit) |

**Comment by MadCcc** [comment]
Customize the color of icon instead?

**Comment by ALF3run** [comment]
@MadCcc That's the workaround I'm using. Still, it's quite an inconsistent behaviour for the Timeline.Item API, since it works as expected using `blue`, `green`, `red` or `gray` as value
