### ISSUE TITLE
antd升级到1.0.0版本后Modal无法显示

### ISSUE THREAD

**Issue by Glita** [ant-design/ant-design#3393]
#### 发生问题的环境是：

- antd 版本:1.0.0
- 操作系统及其版本:OS X Yosemite 版本10.10.5
- 浏览器及其版本: Chorme52.0.2785.116(64-bit)

#### 您做了什么？
1.为了引入Rate升级antd版本0.12.17到1.0.0
2.升级后刷新页面console出现错误提示
`"You are using prebuilt antd,`
`please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size."`
3.按照[#Issue26](https://github.com/ant-design/babel-plugin-import/issues/26)在webpack.config.js中添加样式配置解决问题2
4.解决报错问题后使用antd的Modal组件对话框无法显示

#### 您期待的结果是：
这是antd 0.12.17的结果
![default](https://cloud.githubusercontent.com/assets/3782307/19299568/a5218b80-9087-11e6-858e-38a8d12da861.png)

#### 实际上的结果是：
这是antd 1.0.0的结果，只出现蒙层而对话框无法展示
![default](https://cloud.githubusercontent.com/assets/3782307/19299444/e9d5c88c-9086-11e6-897e-f820ecb40b65.png)

#### 可重现的在线演示
[在线代码](http://codepen.io/Glita/pen/dpZEGo?editors=0011)

**Comment by yesmeck** [comment]
提供下可重现的在线演示吧。

**Comment by Glita** [comment]
[在线代码](http://codepen.io/Glita/pen/dpZEGo?editors=0011)

**Comment by afc163** [comment]
直接升级到 1.11.2 试试。

**Comment by Glita** [comment]
升级到1.11.2已验证，依然无法解决这个问题，只出现蒙层，对话框无法展示。

**Comment by afc163** [comment]
看看样式是否正确加载了？

**Comment by afc163** [comment]
你的在线代码是跑不起来的，希望你能帮助我们重现你的问题，否则无法帮助到你。

能重现再 reopen 吧。
