### ISSUE TITLE
In light theme drawer getting dark component by default in next js

### ISSUE THREAD

**Issue by prachijain2996** [ant-design/ant-design#33937]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://bitbucket.org/hemantds/ybm-ant-design/src/main/](https://bitbucket.org/hemantds/ybm-ant-design/src/main/)

### Steps to reproduce
# Dependencies
  "@ant-design/pro-card": "^1.18.26",
    "@ant-design/pro-layout": "^6.32.7",
    "@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.7.1",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.6.0",
    "@mui/styles": "^5.3.0",
    "antd": "^4.18.4",
    "axios": "^0.25.0",
    "country-state-city": "^3.0.1",
    "moment": "^2.29.1",
    "next": "12.0.8",
    "next-plugin-antd-less": "^1.8.0",
    "prop-types": "^15.8.1",
    "rc-resize-observer": "^1.2.0",
    "react": "17.0.2",
    "react-cookie": "^4.1.1",
    "react-css-theme-switcher": "^0.3.0",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "17.0.2",
    "react-highlight-words": "^0.17.0",
    "react-icons": "^4.3.1",
    "react-number-format": "^4.9.1"

# devDependencies
 "autoprefixer": "^10.4.2",
    "eslint": "7",
    "eslint-config-next": "12.0.8",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "gulp": "^4.0.2",
    "gulp-csso": "^4.0.1",
    "gulp-debug": "^4.0.0",
    "gulp-less": "^5.0.0",
    "gulp-postcss": "^9.0.1",
    "husky": "^7.0.4",
    "less-plugin-npm-import": "^2.1.0"

# issue
Using light theme in our project as default theme. Rest of the project is working properly but when adding antd drawer then all of its inside component is taking dark theme css by default.

# Expected output

All components of antd should be light if theme is defined as light.

# code
     <Drawer
        title=" View Absence Request History "
        placement="right"
        onClose={onDrawerClose}
        visible={DrawerVisible?.AddDrawer}
        size="large"
        width="calc(100% - 225px)"
      >
        {<LeaveRequestHistroy />}
      </Drawer>

    import { Calendar } from "antd";
    import React from "react";
    
    const LeaveRequestHistroy = () => {
     function onPanelChange(value, mode) {
    console.log(value.format("YYYY-MM-DD"), mode);
    }
     return <Calendar onPanelChange={onPanelChange} />;
    };
    export default LeaveRequestHistroy;

### What is expected?
# Expected output

All components of antd should be light if theme is defined as light.

### What is actually happening?
# issue
Using light theme in our project as default theme. Rest of the project is working properly but when adding antd drawer then all of its inside component is taking dark theme css by default.

| Environment | Info |
|---|---|
| antd | 4.18.4 |
| React | "next": "12.0.8",    "react": "17.0.2" |
| System | windows 10 |
| Browser | chrome @latest |

**Comment by MadCcc** [comment]
We have no access to your link.
