### ISSUE TITLE
Filter menu in table columns filters by text instead of value

### ISSUE THREAD

**Issue by keitharm** [ant-design/ant-design#33935]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-curvl)

### Steps to reproduce
Click on the filter for the "Favorite Fruit (filter search broken)" column and do a search for "apple" or any of the other listed fruits. The filter does not work because I am using the Avatar component as part of the text property for the apple filter.

Now click on the filter for the "Favorite Fruit (filter search working)" column and search for "apple". Since I have a plaintext value for both the text and value properties (apple), the filter is able to properly filter the items.

### What is expected?
Filtering by value instead of text for filter menu in table columns.

### What is actually happening?
The filter compares the input text to the filter's text property instead of the filter's value property.
https://github.com/ant-design/ant-design/blob/master/components/table/hooks/useFilter/FilterDropdown.tsx#L75

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | React 17.0.2 |
| System | Windows 10 Enterprise 20H2 |
| Browser | Chrome 97.0.4692.99 |

**Comment by afc163** [comment]
We should support `filterSearch={(input, record) => record.value.indexOf(input) > 0}`
