### ISSUE TITLE
table expand row 在table部分列可滚动的情况下高度无法统一 

### ISSUE THREAD

**Issue by DavidSuns** [ant-design/ant-design#3394]
#### 发生问题的环境是：

- antd 版本: 1.6.5
- 操作系统及其版本: OSX 1.11.6
- 浏览器及其版本: chrome  53.0.2785.116 (64-bit)

#### 您做了什么？

使用了antd 的table组件，并加入了expand row 与 固定前后列，中间列可以横向滚动的特性。
出现的问题在于，expand row 同table row一样被分为了三份，因为expand row 内容显示的不同, 每份展开的高度不一致。

#### 您期待的结果是：

expand row的高度要统一，取三个区域的最大高度。

#### 实际上的结果是：

因为显示排版的问题，高度不统一。

**Comment by afc163** [comment]
这个 1.6.5 应该是支持的 https://github.com/ant-design/ant-design/issues/2132。

你先升级到 1.11.2 试试，不行就给个重现看看。

**Comment by afc163** [comment]
没反馈就关了。
