### ISSUE TITLE
关于FormItem的validator时机

### ISSUE THREAD

**Issue by zmm2tysu** [ant-design/ant-design#33944]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-methods-antd-4-15-0-forked-kjbnv?file=/index.js)

### Steps to reproduce
三个表单依次输入不同的值

### What is expected?
期望第一个表单校验通过

### What is actually happening?
校验已经通过，但是错误提示还是有

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 16.4 |
| System | macOS Big Sur 11.4 |
| Browser | Chrome  93.0.4577.63 |

---
请问这种场景我该怎么处理校验

**Comment by yoyo837** [comment]
手动触发 validateFields ， 注意避免死循环

可以先试用 getFieldError 获取如果有错误才触发

**Comment by yoyo837** [comment]
https://ant.design/components/form-cn/#FormInstance

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/152716489-ec205961-31df-46ce-8722-4bcea0a677fd.png)


这有个3.x类似的，将就看

**Comment by zmm2tysu** [comment]
> 根据时机手动触发 validateFields , 可选只校验部分字段， 注意避免死循环
> 
> 可以先试用 getFieldError 获取如果有错误才触发，使其恢复。

👌 我先瞅瞅

**Comment by yoyo837** [comment]
【关于FormItem的validator时机】：用户修改标单项才会触发

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/34044#issuecomment-1040017242
