### ISSUE TITLE
antd@2.0.1(table组件中要实现行的置顶功能),有好好思路吗？

### ISSUE THREAD

**Issue by jeffycai** [ant-design/ant-design#3395]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:任何
- 浏览器及其版本:任何

**Comment by yesmeck** [comment]
你指的置顶是指固定一条数据显示在第一行，还是需要在页面滚动的时候置顶的行能固定在屏幕上？

**Comment by jeffycai** [comment]
是指固定一条数据显示在第一行，支持多个置顶，类似微信

**Comment by benjycui** [comment]
> 是指固定一条数据显示在第一行，支持多个置顶，类似微信 

这个通过控制 `dataSource` 不就可以了？

**Comment by afc163** [comment]
@benjycui 👍 

控制数据即可。

**Comment by CeceWall** [comment]
如果需要有分页功能，并且分页可以选择每页行数的时候，这个问题该怎么实现呢。

现在的的需求如下
<img width="980" alt="2017-08-30 5 25 51" src="https://user-images.githubusercontent.com/26295849/29865563-6d0f0762-8da8-11e7-8e99-2a773e4ac547.png">
table的最后一行固定，每页显示30行数据，由DataSource添加最后一行数据的时候，必须将pageSize也跟着+1，这样显示出来的pageSize就和用户选择的不符

另外，最后这一行也有固定在滚动时固定在列表最后的需求，不知能否实现
