### ISSUE TITLE
umi4.0.0-rc.1上跑ant design pro报错：AssertionError [ERR_ASSERTION]: Invalid config values: fastRefresh

### ISSUE THREAD

**Issue by nicky132** [ant-design/ant-design#33957]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nicky132/umi4-antDesignProTest.git](https://github.com/nicky132/umi4-antDesignProTest.git)

### Steps to reproduce
yarn

### What is expected?
正常

### What is actually happening?
error - AssertionError [ERR_ASSERTION]: Invalid config values: fastRefresh
Invalid value for fastRefresh:
"value" must be a boolean
    at Function.validateConfig (D:\HEZHENGQUAN\umi4Test\node_modules\@umijs\core\dist\config\config.js:154:30)
    at Config.getConfig (D:\HEZHENGQUAN\umi4Test\node_modules\@umijs\core\dist\config\config.js:38:16)
    at Service.<anonymous> (D:\HEZHENGQUAN\umi4Test\node_modules\@umijs\core\dist\service\service.js:219:70)
    at Generator.next (<anonymous>)
    at fulfilled (D:\HEZHENGQUAN\umi4Test\node_modules\@umijs\core\dist\service\service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^17.0.0 |
| System | windows |
| Browser | google |

**Comment by MadCcc** [comment]
Umi 相关的问题去 umi 那边问吧

**Comment by jiangxiaoqiang** [comment]
貌似不能调整fastRefresh为true

**Comment by jiangxiaoqiang** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> https://github.com/nicky132/umi4-antDesignProTest.git
> 
> ### Steps to reproduce
> yarn
> 
> ### What is expected?
> 正常
> 
> ### What is actually happening?
> error - AssertionError [ERR_ASSERTION]: Invalid config values: fastRefresh Invalid value for fastRefresh: "value" must be a boolean at Function.validateConfig (D:\HEZHENGQUAN\umi4Test\node_modules@umijs\core\dist\config\config.js:154:30) at Config.getConfig (D:\HEZHENGQUAN\umi4Test\node_modules@umijs\core\dist\config\config.js:38:16) at Service. (D:\HEZHENGQUAN\umi4Test\node_modules@umijs\core\dist\service\service.js:219:70) at Generator.next () at fulfilled (D:\HEZHENGQUAN\umi4Test\node_modules@umijs\core\dist\service\service.js:5:58) at processTicksAndRejections (internal/process/task_queues.js:95:5) { generatedMessage: false, code: 'ERR_ASSERTION', actual: false, expected: true, operator: '==' }
> 
> Environment	Info
> antd	undefined
> React	^17.0.0
> System	windows
> Browser	google

问题解决了吗

**Comment by pilgrim803** [comment]
问题解决了嘛
