### ISSUE TITLE
Layout点击多层路由切换会出现出现报错

### ISSUE THREAD

**Issue by is-cool** [ant-design/ant-design#33958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-volhard-tyth4?file=/src/App.js)

### Steps to reproduce
点击多层路由切换会出现

### What is expected?
无报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | Mac 12.0.1 |
| Browser | 97.0.4692.99 |

---![截屏2022-02-08 11 41 58](https://user-images.githubusercontent.com/78067806/152914550-0e7448c8-f87d-40c4-bfe3-3a02a25aec45.png)
![截屏2022-02-08 11 41 38](https://user-images.githubusercontent.com/78067806/152914543-8b458822-c653-4a31-a79d-08fbeba9f172.png)

**Comment by yoyo837** [comment]
Trace in #26136

**Comment by yoyo837** [comment]
可以先 不开启 StrictMode

**Comment by alliYuai** [comment]
Please forgive me. I have to go out at 5:00pm that why I have to make a little sleep.. bec  I lost all my Bitcoin I cried a lot and I am not young.. I just can't read anymore that's why I closed my eyes 🙇‍♀️
