### ISSUE TITLE
可否支持全局监听Modal开启或关闭

### ISSUE THREAD

**Issue by ida-fe** [ant-design/ant-design#33964]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
页面支持快捷键操作，当显示Modal时，需要禁用快捷键功能，当Modal关闭，恢复快捷键
希望对以上场景进行集中监听和处理

### What does the proposed API look like?
Modal.config({onOpen: () => {}, onClose: () => {}})

**Comment by afc163** [comment]
暂不支持。
