### ISSUE TITLE
Table's filterDropdown clearFilter wont trigger table onChange

### ISSUE THREAD

**Issue by georgesofianosgr** [ant-design/ant-design#33962]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-czvxp?file=/index.js)

### Steps to reproduce
* Create a table and add a console.log to onChange prop
* Create a controlled column with filterDropdown
* Clear filter via clearFilter()

### What is expected?
Table onChange to be called with changes

### What is actually happening?
Table onChange is not firing

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 17.x |
| System | macOS 12 Monterey |
| Browser | Google Chrome 97.0.4692.71 |

---
Table onChange was firing in 4.16.13. From 4.17 and beyond does not.

**Comment by MadCcc** [comment]
There's no change in your example. Plz follow docs: https://ant.design/components/table/#components-table-demo-custom-filter-panel

**Comment by georgesofianosgr** [comment]
I created a very simple reproduction code just to show that clearFilter was not firing onChange. 
Even if there was no change in filters, in previous versions when you called the clearFilter onChange was firing so we knew that a filter was empty.

Anyway, I updated the code, you can apply a text filter on name and then when you run the clearFilter onChange still not firing.

**Comment by awesomeWay** [comment]
me too
