### ISSUE TITLE
 mac chrome 上传组件不能使用了，windows不受影响

### ISSUE THREAD

**Issue by Topgt** [ant-design/ant-design#33966]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
，点击不能调出文件选择

### What is expected?
能正常弹出文件选择

### What is actually happening?
点击上传没有反应

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17 |
| System | 11.3.1 (20E241) |
| Browser | chrome |

**Comment by lavyun** [comment]
+1，好多组件库都出现了这个问题   

macOS Big Sur 11.4
chrome 版本：97.0.4692.99

**Comment by lavyun** [comment]
> > 好多组件库都出现了这个问题
> 
> 好多组件库是指？

业务上有运营同学反馈了，我试了下 element-ui、iviewui等组件库，均无法弹出文件选择，猜测是 chrome 自身问题

**Comment by kuanglinfeng** [comment]
> 

把 chrome 升级到最新版就好了，应该是 chrome 某个版本有点问题

**Comment by zhuman1993** [comment]
的确，把Chrome升级到98版本后可以使用了，Chrome97版本都还是有问题

**Comment by progerchai** [comment]
105.0.5195.125（正式版本） (arm64) 同样出现了这个问题

**Comment by qlniu** [comment]
Mac   Chrome107.0.5304.110（正式版本） (x86_64)  有时候也无法弹出文件选择框
