### ISSUE TITLE
"showNow" prop on RangePicker not displaying anything

### ISSUE THREAD

**Issue by jtheberge** [ant-design/ant-design#33974]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s8pnp)

### Steps to reproduce
Add "showNow" to RangePicker.

### What is expected?
Expect to see similar behavior to DatePicker where "Today" is a button on bottom option to choose.

### What is actually happening?
No button to select Today is shown.

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Currently there's no "showNow" prop in RangePicker
Reference: https://ant.design/components/date-picker-cn/#API

**Comment by jtheberge** [comment]
Hey @MadCcc , this seems to be part of the TS definition for RangePicker. If it's not supported, should it be added to Omit? 

<img width="457" alt="Screen Shot 2022-02-09 at 10 54 23 AM" src="https://user-images.githubusercontent.com/13157499/153270238-fc6f0bd5-95ed-450e-98b0-f0e4180e94eb.png">

https://github.com/react-component/picker/blob/master/src/PickerPanel.tsx#L92
