### ISSUE TITLE
 Table 组件 columns设置 第一列和第四列的fixed="left"时，横向滚动时希望紧贴

### ISSUE THREAD

**Issue by kamu1** [ant-design/ant-design#33977]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决第1列和第4列之间列在横向滚动时空白的问题，还解决了交叉列固定的需求。

### What does the proposed API look like?
例如：存在列为  序号(left) | 姓名(left) | 身份证 | 姓别 | 项目名称(left) | 项目地址 | 项目状态 | ...... | 操作(right)
在横向滚动时，项目名称跟着被滚动，滚动值超出项目名称的位置的情况下，项目名称是贴合在姓名后面的。这种交互是在一个Kendo react UI项目中的表格组件看到的。它还支持了行的磁贴固定。

**Comment by MadCcc** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-columns
支持固定列
