### ISSUE TITLE
upload组件在Chrome88以上的版本无法打开本地文件询问框

### ISSUE THREAD

**Issue by zhuman1993** [ant-design/ant-design#33988]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#UploadFile](https://ant.design/components/upload-cn/#UploadFile)

### Steps to reproduce
打开官网的upload组件文档，点击官方提供的案例均无法打开文件询问框，即点击后没有任何反应

### What is expected?
能打开文件询问框

### What is actually happening?
没有任何反应

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | 17.0.2 |
| System | mac os 11.2.1 |
| Browser | chrome |

**Comment by huanghaiyang** [comment]
+1

**Comment by hexiaolong24** [comment]
+1

**Comment by zhadongmin** [comment]
+1 本来是可以的，我也没升级chrome 突然就这样
