### ISSUE TITLE
官方文档走马灯参数说明缺失

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#33982]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
官方文档走马灯页的autoplaySpeed等参数缺失说明信息
![image](https://user-images.githubusercontent.com/49147660/153141985-f01a5af3-ecb6-4b74-90e0-d2db472e0c4a.png)

### What does the proposed API look like?
希望可以完善缺失的相关参数说明

**Comment by MadCcc** [comment]
> 更多 API 可参考：https://react-slick.neostack.com/docs/api
