### ISSUE TITLE
popover气泡卡片不设置onVisibleChange多次开关会在显示状态下无法点击

### ISSUE THREAD

**Issue by JehChenxx** [ant-design/ant-design#33983]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cong-fu-ceng-nei-guan-bi-antd-4-18-6-forked-g9un2?file=/index.js)

### Steps to reproduce
反复开启关闭，基本30次内即可复现。

### What is expected?
任意开启关闭后仍能正常开关

### What is actually happening?
无法点击，鼠标会定位下层元素。

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 16.14.0 |
| System | Win10 |
| Browser | Chrome 版本 97.0.4692.71（正式版本） （64 位） |

---
popover元素在不可见时存在css属性point-event: none，反复点击有可能会出现popover在可见时仍具有该属性，导致无法点击进行关闭动作。设置onVisibleChange仍会有该现象，但会因为点击到下层元素触发onVisibleChange导致popover关闭，从而避免卡死。
目前业务上是popover内存在表单输入，不设置onVisibleChange时类似于Drawer、Modal的禁用蒙版关闭，比较符合场景，但会出现popover多次开关后无法点击完全卡死；设置onVisibleChange一定程度上避免了完全卡死，但是对表单输入不是很友好，容易误关闭，而且出现无法点击的情况时，popover会直接关闭，需要手动重新打开，也不是很合适。

**Comment by JehChenxx** [comment]
![image](https://user-images.githubusercontent.com/47981336/153161255-cecfa582-d6b0-4753-95a9-dcec5f963ccb.png)

**Comment by JehChenxx** [comment]
![image](https://user-images.githubusercontent.com/47981336/153161717-cec2847d-4139-471e-ab32-2ff0e36a0590.png)

**Comment by JehChenxx** [comment]
![image](https://user-images.githubusercontent.com/47981336/153162007-0883aa22-c9be-4055-afdd-e1d904d461a8.png)

**Comment by MadCcc** [comment]
没有点出来你说的情况。
xx次就可以复现一般不靠谱，需要更明确的复现场景。提供个录屏看看？

**Comment by JehChenxx** [comment]
确实不太容易复现，有的时候十几次就会出现，有时候要点两三分钟都不一定

https://user-images.githubusercontent.com/47981336/153167767-441f4b4c-5349-496b-8433-2b10bbc39e0b.mp4

**Comment by MadCcc** [comment]
选中情况下点 close 之后就没反应了

**Comment by MadCcc** [comment]
刚复现了一次，后面又不行了

**Comment by JehChenxx** [comment]
https://codesandbox.io/s/cong-fu-ceng-nei-guan-bi-antd-4-18-6-forked-g9un2?file=/index.js

https://user-images.githubusercontent.com/47981336/153172238-3ed25449-3f20-450c-8265-c8911c04e6bb.mp4

与选中没关系的，这个时把a标签换为按钮复现的例子和截取视频，就是频繁点击偶然触发visible为true时point-event属性没有清除，之前还考虑过z-index和点击事件冒泡，但似乎没啥关联。

**Comment by JehChenxx** [comment]
> 刚复现了一次，后面又不行了

**Comment by zombieJ** [comment]
Trigger 重构了，应该是好了。有问题就再开新的 issue 吧~

**Comment by CHANCCCZQ** [comment]
> Trigger 重构了，应该是好了。有问题就再开新的 issue 吧~

什么版本修好了呢，antd4.20.3一样有这个问题

**Comment by Tangjj1996** [comment]
> > Trigger 重构了，应该是好了。有问题就再开新的 issue 吧~
> 
> 什么版本修好了呢，antd4.20.3一样有这个问题

"antd": "^4.20.7" 也有一样的问题
