### ISSUE TITLE
[2.x]升级后关于css打包的规则

### ISSUE THREAD

**Issue by zuiidea** [ant-design/ant-design#3398]
### 描述
单个页面所引用的组件的样式会打包到页面的css文件(page.css)，多个页面公用的样式打包到common.css，在html中样式文件引入顺序是common.css，page.css

### 场景
如果我想对antd的一些样式做全局的覆盖，比如Table相关的样式，那么这些样式讲道理应该合到common.css，现在我在页面A中引入了Table组件。
那么问题来了，pageA.css中包涵了antd的table相关样式，我在common.css文件对table的样式覆盖就不起作用了

可能与babel-plugin-import有关

**Comment by benjycui** [comment]
通过选择器优先级解决。

然后哪些依赖要打进 common 是可以配置的，请参考 webpack 相关的文档。
