### ISSUE TITLE
table展开嵌套表格并且父table使用了fixed固定列，点击展开会错位

### ISSUE THREAD

**Issue by LongYue9608** [ant-design/ant-design#33984]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/polished-mountain-s6f97?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
点击表格展开

### What is expected?
fixed列随着表格展开撑开

### What is actually happening?
错位

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 17 |
| System | windows |
| Browser | 谷歌97版本 |

**Comment by MadCcc** [comment]
3.x 版本已经不再维护了。

**Comment by LongYue9608** [comment]
![image](https://user-images.githubusercontent.com/25579482/153163704-e461c2fb-d68b-4a2c-8fe7-46c5d5ceda8d.png)

**Comment by LongYue9608** [comment]
![image](https://user-images.githubusercontent.com/25579482/153163794-c93a1d31-7793-45a4-9a9f-5163aa46a201.png)
