### ISSUE TITLE
Button: 4.17.0版本以上的button, type设置为default之后, 最终没有ant-btn-default的class

### ISSUE THREAD

**Issue by mayuanying** [ant-design/ant-design#33996]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
4.17.0版本以上的button, type设置为default之后, 最终没有ant-btn-default的class

### What is expected?
最终的button有default这个class

### What is actually happening?
没有default

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 17.0.1 |
| System | mac |
| Browser | Chrome 98 |

---
我们需要对default的button单独设置样式, 但目前配置了default的button只有通用样式ant-btn, 那我要针对default定制样式&不影响其他primary按钮样式, 就只能写一堆not(), 且项目使用场景很复杂, 依赖了很多库, 之前default的按钮样式写了important

**Comment by afc163** [comment]
建议用 https://ant.design/docs/react/customize-theme-cn 的方式做主题修改。

**Comment by mayuanying** [comment]
我们有用主题修改, 但default button的样式比较复杂, 没法只通过配置来修改
我看button组件的type还是支持default的, 为什么要从class里面去掉呢? 当时有什么顾虑吗

**Comment by zombieJ** [comment]
> 我们有用主题修改, 但default button的样式比较复杂, 没法只通过配置来修改 我看button组件的type还是支持default的, 为什么要从class里面去掉呢? 当时有什么顾虑吗

`-default` 是漏进去的，shape 也有个 `default`。是可以做成 type only 的

https://github.com/ant-design/ant-design/commit/008242b35ee604f77f2bface62805fec73ea00c9#r63784420

**Comment by mayuanying** [comment]
4.17.0以上的版本 -default 并没有传到class上, 即便改成shape=default也没有, 我现在需要一个default button单独的class来添加某些样式, 但是不希望写一个.ant-btn, 然后通过not过滤所有primary/dash等类

https://codesandbox.io/s/an-niu-lei-xing-antd-4-18-6-forked-0pvx3?file=/index.js

![image](https://user-images.githubusercontent.com/7044545/153356828-1e335279-f5a8-432c-b444-1cafd6d37122.png)

**Comment by zombieJ** [comment]
我的意思是 shape 和 type 都有 default 字段，内部没有取名叫做 `ant-btn-type-default` 和 `ant-btn-shape-default`。所以有命名冲突。然后说可以加的意思就是 `default` 可以给 `type`

**Comment by zombieJ** [comment]
意思就是 Button type='default' 可以加上 `ant-btn-default` 的意思……

**Comment by mayuanying** [comment]
但问题是没有加上....我前面贴了好多链接和截图, 就是在问为什么没有加上, 所以这个是bug么

**Comment by afc163** [comment]
看上去当初是有意去掉的 https://github.com/ant-design/ant-design/pull/32004
