### ISSUE TITLE
Table设置服务端排序时点击排序按钮时没有获得预期值

### ISSUE THREAD

**Issue by cityvoice** [ant-design/ant-design#33997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new](https://github.com/ant-design/ant-design/issues/new)

### Steps to reproduce
服务端排序，前端设置了列的排序属性
```
const columns=[
{
title:'成本',
dataIndex:'cost',
sorter:true,
sortDirections: ['ascend', 'descend'],
},
{
title:'更新时间',
dataIndex:'updateTime',
sorter:true,
sortDirections: ['ascend', 'descend'],
},
...
]
```
默认排序字段为更新时间，当用户按照成本排序时，不管用户点击的是升序还是降序按钮，Table上的onChange这个API里第一次拿到的排序结果总是升序（也就是按照sortDirections定义的第一个值）。如果用户继续点击按照成本排序，后续拿到的值则正常。同理，如果此时用户点击按更新时间排序，也会出现同样的问题。

### What is expected?
用户第一次点击排序时，排序结果由用户点击的是升序还是降序按钮来决定

### What is actually happening?
用户第一次点击排序时，排序结果由sortDirections定义的第一个值所决定

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.12 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
新的排序按钮交互不再区分升序按钮和降序按钮，而是改成点击整体列头后默认先降序再降序。
