### ISSUE TITLE
在火狐浏览器 menu 在 theme 为 dark 的情况下 丑爆了 55555555555555

### ISSUE THREAD

**Issue by wansuiasdn** [ant-design/ant-design#34005]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn](https://ant.design/components/menu-cn)

### Steps to reproduce
用火狐浏览器打开官网的menu demo 设置为 dark 然后单击子元素会出现巨大的灰色块
定位到样式 ：.ant-menu-item:focus-visible, .ant-menu-submenu-title:focus-visible 下的 box-shadow

### What is expected?
去掉这个样式

### What is actually happening?
没有白块

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 16 |
| System | windows 10  |
| Browser | firefox  |

![图片](https://user-images.githubusercontent.com/47979542/153387972-b5b22c1c-b0f7-40c2-9aa1-ce6be7134f41.png)
![图片](https://user-images.githubusercontent.com/47979542/153388012-e195031f-c19b-4b41-a2a7-5e6c336bed94.png)

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/153388251-66d14f0a-67d5-495e-873b-1fea43a95e53.png">

无法重现，请问你的 Firefox 的版本是多少？

**Comment by wansuiasdn** [comment]
@afc163  谢谢你的回复 
![图片](https://user-images.githubusercontent.com/47979542/153388528-74549395-f099-44b4-80bf-4160eb745d59.png)

**Comment by wansuiasdn** [comment]
@afc163  谢谢您的答复

您说您那里没有复现，可能跟我设置浏览器主题有关，我这个问题就先关闭了，如果在多台电脑能复现，我再打开

![图片](https://user-images.githubusercontent.com/47979542/153388870-5723f0d6-30f2-455e-ba40-63c707e2c8e3.png)

**Comment by afc163** [comment]
我无法重现，但是这个 box-shadow 的样式确实有问题。
