### ISSUE TITLE
Ant Design Vue 1.7.8 Select组件，使用搜索和远程数据结合时，输入的搜索内容值绑定需求。

### ISSUE THREAD

**Issue by mr-chk** [ant-design/ant-design#34000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、目前用户在输入框输入的内容无法被限制，如果提供一些api并且提供与该输入绑定的属性，那么开发可以有更大的发挥空间。
2、注意到与之类似的组件有AutoComplete，但两者使用有区别，依然具有局限性。

### What does the proposed API look like?
最重要的是提供与该输入值绑定的属性。

**Comment by yoyo837** [comment]
请移步 https://github.com/vueComponent/ant-design-vue

**Comment by mr-chk** [comment]
Thank you
