### ISSUE TITLE
Virtual table with set scroll properties and empty dataSource does not display No Result

### ISSUE THREAD

**Issue by daises** [ant-design/ant-design#34019]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-4-18-6-forked-0iheg)

### Steps to reproduce
The data source set as empty and property scroll set as {x:5,y:0}

### What is expected?
The table shows no results.

### What is actually happening?
The table is empty in the place when it is data.

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 16.14.0 |
| System | macOs Big Sure |
| Browser | Google Chrome 97.0.4692.99  |

**Comment by afc163** [comment]
Trace #20339
