### ISSUE TITLE
Cascader 级联选择多选模式下使用tagRender定制之后，关闭非最后一个Tag的时候会删除多个Tag

### ISSUE THREAD

**Issue by dabanheiji** [ant-design/ant-design#34018]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-pasteur-8ic1q?file=/src/index.js)

### Steps to reproduce
选择多个选项之后点击tag后的叉号删除非最后一个选项，会删除两个Tag，注释调tagRender属性之后正常

### What is expected?
使用tagRender属性后点击删除只删除当前tag

### What is actually happening?
使用tagRender属性后点击删除显示框中会被删除两个tag

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome 98.0.4758.80 |

---
使用tagRender自定义tag内容时，交互出现问题

**Comment by Schooling-Chan** [comment]
Tag加上key，用来区别多个选项就可以了

**Comment by dabanheiji** [comment]
ok，问题解决了，非常感谢
