### ISSUE TITLE
form表单自定义校验时，添加Promise.resolve返回信息。

### ISSUE THREAD

**Issue by lxz0510** [ant-design/ant-design#34010]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
就像reject(new Error(""))那样，希望resolve ("")也可以展示一段信息到页面上

### What does the proposed API look like?
Promise.resolve("一段成功返回的文字") or callback("")

**Comment by afc163** [comment]
成功信息一般不做展示，如果有需要可以用 help/extra 自行处理。
