### ISSUE TITLE
Menu组件的overflowedIndicator属性在mode设置为vertical或inline时不生效

### ISSUE THREAD

**Issue by OWRIG** [ant-design/ant-design#34016]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0010](https://codepen.io/pen/?editors=0010)

### Steps to reproduce
点击折叠/展开图标观察图标变化

### What is expected?
可以正常自定义Menu组件折叠图标

### What is actually happening?
设置overflowedIndicator后未产生变化

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17.0.2 |
| System | macOS monterey |
| Browser | 98.0.4758.80 |

---
经测试发现该属性仅在mode为horizontal时生效，希望能同时作用在菜单内嵌模式，或者在文档中进行补充说明。

**Comment by OWRIG** [comment]
打扰了，我误以为这个属性是与expandIcon相对应的。或许可以把overflowedIndicator描述为“自定义 Menu 水平折叠时的图标” ？

**Comment by afc163** [comment]
可以改成『用于自定义 Menu 水平空间不足时的省略收缩的图标』
