### ISSUE TITLE
InputNumber does not update its value when calling Form's setFieldsValue

### ISSUE THREAD

**Issue by pobch** [ant-design/ant-design#34023]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-jasper-4e2vd?file=/src/App.js)

#### Case 1
1. Go to this codesandbox https://codesandbox.io/s/great-jasper-4e2vd?file=/src/App.js
2. Click the input
3. Put any number more than 5, e.g. type `8`
4. (Expected) `setFieldsValue` is called and the value is changed to `0`
5. Without blur, continue typing another number, e.g. `9`
6. (Bug) Now the value is `09`. It should actually behave the same as bullet 4. and show `0` instead of `09` 

#### Case 2
1. Refresh codesandbox
2. Click the input
3. Type `8`
4. (Expected) `setFieldsValue` is called and the value is changed to `0`
5. Click outside of the input to blur
6. Double-click the input to highlight `0`
7. Type `8`
8. (Bug) This time the value is `8`. It does not behave the same as bullet 4.

### What is expected?
Both step 6 in Case 1 and step 8 in Case 2 above should show `0` in the input field.

### What is actually happening?
See step 6 in Case 1 and step 8 in Case 2 above

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17.0.2 |
| System | Mac OS 12.1 |
| Browser | Firefox 96 |

**Comment by afc163** [comment]
You need `normalize` instead of setFieldsValue in field's onChange.

**Comment by pobch** [comment]
@afc163 `normalize` does not fix the issue.
I've updated the codesandbox https://codesandbox.io/s/ancient-dawn-fgwk0?file=/src/App.js
And the issue still there.
