### ISSUE TITLE
TreeSelect onSearch 无法选取

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#34029]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-18-6-forked-jx83z?file=/index.js)

### Steps to reproduce
输入值后按回车没有反应

### What is expected?
输入值后按回车完成取值。

### What is actually happening?
4.18.6版本存在此问题，以前的版本正常。

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 16.14.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by MadCcc** [comment]
TreeSelect 特殊一点，像 Select 会默认 active 筛选后的第一项，但是 TreeSelect 的树形结构下第一项（有可能是 parent）可能并不是包含筛选内容的。
目前可以在筛选后通过键盘方向键去选择 active 项，这里的交互是没有问题的。至于筛选后的默认选项我们暂时可能不会提供或者在有好的方案后才会提供。
