### ISSUE TITLE
Sticky table headers do not work while used inside a tab

### ISSUE THREAD

**Issue by johnjiang** [ant-design/ant-design#34021]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-and-scroll-bar-with-the-page-antd-4-18-6-forked-9svd5?file=/index.js)

### Steps to reproduce
Put a sticky table inside a tabpane

### What is expected?
The header should be sticky

### What is actually happening?
The header is not sticky

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | >16.* |
| System | Mac |
| Browser | Chrome |

**Comment by shaodahong** [comment]
Because Tab has `overflow: hidden`

![image](https://user-images.githubusercontent.com/14831261/153690075-35e6e707-a3b0-4c7a-b53e-352a974a0a7d.png)

**Comment by afc163** [comment]
不太好办。

**Comment by find456789** [comment]
被这个bug ，给困了好长时间，  只能 把table 放在tab之外， 然后用一个状态控制 组件的展示，隐藏

**Comment by SlahserZ** [comment]
```less
:global {
    .ant-tabs {
        overflow: inherit;
    }
}
```

**Comment by hobin2017** [comment]
does version `4.24.8` solve this issue? If not, which version have it solved?
