### ISSUE TITLE
一个页面中能不能放两个form组件

### ISSUE THREAD

**Issue by zdxxxxxx** [ant-design/ant-design#3402]
#### 发生问题的环境是：

- antd 版本:^2.0
- 操作系统及其版本:win10 
- 浏览器及其版本:chrome 最新

#### 您做了什么？

引入antd/lib/form
```
<div>
      <div><Form id="a"></Form></div>
      <div><Form id="b"></Form></div>
</div>
```

####问题：
form.resetFields （）

**Comment by afc163** [comment]
先搜再问。

https://github.com/ant-design/ant-design/issues/2294
