### ISSUE TITLE
Slider not working correctly when min prop has decimals

### ISSUE THREAD

**Issue by aleksey-10** [ant-design/ant-design#34020]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-leavitt-wk3s0?file=/src/App.js)

### Steps to reproduce
1. Create a slider component with props ```min={0.05} max={2} step={1}```
2. Try moving the slider

### What is expected?
It should be possible to reach the max value while dragging

### What is actually happening?
- Impossible to set the value to the max, it doesn't move further than 1
- The minimum value sets to 0, should be 0.05.

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome/98.0.4758.82 |

**Comment by dotamir** [comment]
@aleksey-10 Well this is because you set the `step` property to `1`. That is the cause it doesn't work properly. If you expect the value to be 0.05 you need to set `step` to `0.05` not `1`.
