### ISSUE TITLE
InputNumber customize increase/decrease button by ref

### ISSUE THREAD

**Issue by phatify** [ant-design/ant-design#34035]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By added this option we can customize the buttons Increase/Decrease easier and more flexible.

Example code i suggested: 

```
const ref = useRef(null);

const descrease = () => {
  ref.current.descrease();
}

const increase= () => {
  ref.current.increase();
}

return (
<>
  <Button onClick={descrease}>Decrease</Button>
  <InputNumber ref={ref} controls={false} />
  <Button onClick={increase}>Increase</Button>
</>
)
```

### What does the proposed API look like?
it looks like above

**Comment by afc163** [comment]
You can control `value` of InputNumber.

**Comment by phatify** [comment]
> You can control `value` of InputNumber.

it also works on `Form.Item` ? And how validating with `min` and `max` ?

**Comment by yoyo837** [comment]
Control it with `setFieldsValue` in `Form.Item`.

**Comment by phatify** [comment]
> Control it with `setFieldsValue` in `Form.Item`.

@yoyo837 thanks!
