### ISSUE TITLE
日期查询range safari bug

### ISSUE THREAD

**Issue by SlimJason** [ant-design/ant-design#3403]
#### 发生问题的环境是：

-  antd版本：1.1.0
- 操作系统及其版本：safari 10.0
- 浏览器及其版本：mac os 10.12

#### 您做了什么？
日期查询range，选了开始、结束日期时候，占位符和所选日期重叠，而且，传到后台的是undefied

#### 实际上的结果是：

![image](https://cloud.githubusercontent.com/assets/5801796/19317055/50495a6c-90d6-11e6-812d-0aea3bbf3732.png)

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
ping~

**Comment by RaoHai** [comment]
@SlimJason 可以提供一个可重现的演示么？

**Comment by RaoHai** [comment]
如果没有 demo 先 close 了。

**Comment by qq645381995** [comment]
#4782
