### ISSUE TITLE
dropdown组件的destroyPopupOnHide不生效

### ISSUE THREAD

**Issue by wittech** [ant-design/ant-design#34039]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决dropdown组件的弹出菜单重绘

### What does the proposed API look like?
期望隐藏后菜单被销毁

**Comment by wittech** [comment]
看了dropdown里面的源码，没有实现destroyPopupOnHide相关的逻辑，引用的rc-dropdown里面也没有呢？

**Comment by wittech** [comment]
@MadCcc

**Comment by MadCcc** [comment]
如果有问题的话给个重现，目前都是 work 的

**Comment by wittech** [comment]
依赖版本问题，最新的没有问题了
