### ISSUE TITLE
Warning: `label` of `value` is not same as `label` in Select options.

### ISSUE THREAD

**Issue by 2362446788** [ant-design/ant-design#34048]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2je09?file=/package.json:381-389)

### Steps to reproduce
选中其他option，就触发错误：Warning: `label` of `value` is not same as `label` in Select options.

### What is expected?
期望不触发这个错误

### What is actually happening?
触发错误：Warning: `label` of `value` is not same as `label` in Select options.

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | ^16.14.0 |
| System | window10 |
| Browser | Microsoft Edge 98.0.1108.50 |

**Comment by 2362446788** [comment]
需要重新npm install吗

**Comment by 2362446788** [comment]
@zombieJ

**Comment by s464446877** [comment]
这个目前好像还有警告，情景就是如果label是reactNode，不是string，并且在onchange事件里更新state，就会出现这个警告

**Comment by HuanxinHu** [comment]
> 这个目前好像还有警告，情景就是如果label是reactNode，不是string，并且在onchange事件里更新state，就会出现这个警告

碰到相同的问题

**Comment by REND42** [comment]
Same

**Comment by ta9yu** [comment]
I ran into the same problem.
I fixed it by specifying `optionLabelProp="children"` in the Select component.

**Comment by m430** [comment]
@ta9yu thanks, It works for me.

**Comment by annyhira414** [comment]
@ta9yu  Thanks its works

**Comment by dolfbarr** [comment]
Any ideas how to fix it for combobox selects? They do not support `optionLabelProp`.

**Comment by Hassan-bai** [comment]
I ran into the same problem.
I fixed it by specifying optionLabelProp="label" in the Select component.
