### ISSUE TITLE
Datepicker multiple formats

### ISSUE THREAD

**Issue by ButuzGOL** [ant-design/ant-design#34049]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
User can write any format with specific characters or without for example
user can write 2022-31-12 or 20223112

### What does the proposed API look like?
format={["YYYY-DD-MM", "YYYYDDMM"]}

**Comment by afc163** [comment]
It is weird to support multiple formats in one DatePicker, I will pass it.
