### ISSUE TITLE
Tooltip trigger=focus does not work well with Input inside Form

### ISSUE THREAD

**Issue by pobch** [ant-design/ant-design#34043]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-sanne-im43w?file=/src/App.js)

### Steps to reproduce
1. Go to https://codesandbox.io/s/naughty-sanne-im43w?file=/src/App.js
2. Click the input to focus
3. Type `a`
4. Type `backspace` to remove `a`
5. {BUG} Tooltip does not show up even though the input is in focus state and there is `trigger="focus"` prop in Tooltip.
6. Click outside the input to blur
7. Click the input again and type `a`
8. Type `backspace` to remove all characters
9. (Expected) This time the Tooltip works correctly. There is an error message as Tooltip.

### What is expected?
At step 5, the Tooltip should show up with an error message, i.e. "Required field", similar to step 9.

### What is actually happening?
Tooltip is disappeared at step 5 even though:
1. The input is in `focus` state
2. There is `trigger="focus"` prop in Tooltip
3. There is `title="Required field"` prop in Tooltip (by calling `getFieldError('foo')`)

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 17.0.2 |
| System | mac os 12.1 |
| Browser | Firefox 96 |

**Comment by zombieJ** [comment]
Tooltip will not show when `title` is empty. When you call `getFieldError`, it's no error for the FormItem so tooltip will not show.

**Comment by pobch** [comment]
@zombieJ At step 5, the Tooltip **does** receive `title="Required field"` as a prop. It's not empty.
You can see from the `console.log()` at App.js-line11 in the codesandbox link.
