### ISSUE TITLE
form 组件在rules.validator中调用 form.validateFields会导致onFinish无法触发

### ISSUE THREAD

**Issue by nuancheng** [ant-design/ant-design#34044]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-18-6-forked-n9z1v)

### Steps to reproduce
在Warning字段中输入，点击确定

### What is expected?
onFinish触发

### What is actually happening?
onFinishFailed触发，onFinish没有触发

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | macOS 10.15.7 (19H2) |
| Browser | chrome  版本 86.0.4240.111（正式版本） (x86_64) |

---
最新版可复现

**Comment by zombieJ** [comment]
不能在 `validator` 中调用 `validateFields`，你这循环了。触发其他表单项校验用 `dependencies`

ref: https://ant.design/components/form-cn/#components-form-demo-register
