### ISSUE TITLE
表单内无法获取FormContext值

### ISSUE THREAD

**Issue by zjb19970804** [ant-design/ant-design#34051]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-yevoex?file=index.js](https://stackblitz.com/edit/react-yevoex?file=index.js)

### Steps to reproduce
创建表单，并在表单内根据Context获取值

### What is expected?
能得到正确的context值

### What is actually happening?
获取的是context默认初始值

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | Chrome 94.0.4606.81 |

**Comment by MadCcc** [comment]
你的真实场景是什么？文档里没有推荐这种用法。

**Comment by zjb19970804** [comment]
> 你的真实场景是什么？文档里没有推荐这种用法。

我需要在同一个表单内使用多种labelCol、wrapCol布局。我想到的最简单的方法是获取到父级表单的context值，然后在需要另一种布局的节点上使用FormContext.Provider包裹并传递父级的其他属性值和要使用的布局属性。
``` javascript
  <FormContext.Provider value={{ ...context, labelCol: xxx, wrapCol: xxx }}>
    <OtherLayoutFormFragment />
  </FormContext.Provider>
```

**Comment by MadCcc** [comment]
既然如此你应该自己提供 provider。
不过不推荐这种做法。

**Comment by zjb19970804** [comment]
> 既然如此你应该自己提供 provider，比如这样： https://stackblitz.com/edit/react-yevoex-vl2syc?file=index.js 不过不推荐这种做法。

这样会丢失父级表单的其他的context属性，比如colon、requiredMark等，其实我更想知道为什么无法获取到context，我看源码中的[FormItemLabel](https://github.com/ant-design/ant-design/blob/master/components/form/FormItemLabel.tsx#L58)和[FormItemInput](https://github.com/ant-design/ant-design/blob/master/components/form/FormItemInput.tsx#L64)都能成功获取到值，我不确定是否有其他东西破坏掉了context传递。

![image](https://user-images.githubusercontent.com/37135411/154009201-9b298aa5-6fd5-4c6d-bb59-34f762c9d771.png)

**Comment by MadCcc** [comment]
所以这是一个不推荐的用法，我们不保证这样做能按照预期运行。
