### ISSUE TITLE
Inconsistent DatePicker format

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#3405]
DatePicker does not respect defined format when user is picking the date:

![oie_0w4ftdjrzdet](https://cloud.githubusercontent.com/assets/5719547/19321855/f6207594-90b6-11e6-819d-663a3ab5d686.jpg)

![oie_chd6y3bbat7p](https://cloud.githubusercontent.com/assets/5719547/19321897/1f679d1a-90b7-11e6-87eb-72a39fe829f2.jpg)

**Comment by plandem** [comment]
#3298
