### ISSUE TITLE
clone项目代码本地运行设置theme无效

### ISSUE THREAD

**Issue by dyk98** [ant-design/ant-design#34059]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
npm install
npm run start
进组件页面，点击右下角切换成暗黑

### What is expected?
和线上官网一样表现

### What is actually happening?
页面滚动条变黑了，其余没变化

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^17.0.1 |
| System | macos 11.5 |
| Browser | 最新稳定版chrome |
![企业微信截图_408a828c-2ae5-4df3-856d-b51fa4328b0d](https://user-images.githubusercontent.com/34772565/154012529-47c83805-95e3-4b83-97c1-b75861494c73.png)

**Comment by zombieJ** [comment]
> 在启动时，设置需要执行的主题：
>
> DEV_THEME=dark npm start

ref https://ant.design/docs/react/contributing-cn#%E5%88%87%E6%8D%A2%E4%B8%BB%E9%A2%98
