### ISSUE TITLE
Input组件onCompositionEnd事件未响应

### ISSUE THREAD

**Issue by Zane0816** [ant-design/ant-design#34053]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-joana-3uy8u)

### Steps to reproduce
当输入中文时onCompositionEnd事件无法触发

### What is expected?
onCompositionEnd事件可以触发

### What is actually happening?
onCompositionEnd事件未触发

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17.0.39 |
| System | window10 |
| Browser | chrome |

---
我们在记录用户输入内容时,希望不记录用户输入中文时会记录'w'm'类似这样的内容;所以我们希望通过onComposition相关事件来解决这个问题.但使用时发现onCompositionEnd事件无法触发

**Comment by zombieJ** [comment]
和 antd 没有关系，这个是受控问题。React 本身受控逻辑 `value` 和 `onChange` 是成对出现。`'w'm'` 是输入法和系统行为，在 onComposition 里控制是不对的。antd 侧做不了什么。
