### ISSUE TITLE
Bug: Can't resolve 'rc-util/es/hooks/useLayoutEffect

### ISSUE THREAD

**Issue by svitlana-snappy** [ant-design/ant-design#34065]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce
Try to install latest version or any version of atd 4 this error pops up:
./node_modules/antd4/es/typography/Base/index.js
Module not found: Can't resolve 'rc-util/es/hooks/useLayoutEffect' in '/Users/sshymko/Documents/JOB/snappy-client-dashboard/node_modules/antd4/es/typography/Base'

### What is expected?
no error is expected

### What is actually happening?
The application crashes because of antd library

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | React |
| System | reeact |
| Browser | All |

**Comment by ftong2010** [comment]
Antd 4.18.7 depends on rc-util 5.14.0, and useLayoutEffect method is added in version 5.15.0. You can explicitly add dependency of rc-util with version greater than 5.15.0 to bypass this issue.

**Comment by dnapayments** [comment]
Thank you, I had the same error, so I installed rc-util and it worked.

**Comment by yoyo837** [comment]
@svitlana-snappy Could you try to delete `node_modules` and lock files (`package-lock.json` or `yarn.lock`) then reinstall it?

**Comment by MadCcc** [comment]
The dependency is `"rc-util": "^5.14.0"` , which will support intalling higher minor version.
