### ISSUE TITLE
Form doesn't validate initialValues

### ISSUE THREAD

**Issue by li4man0v** [ant-design/ant-design#34069]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://nq1lxf.csb.app/](https://nq1lxf.csb.app/)

### Steps to reproduce
Pass initialValues that contains data of invalid format. For example, make a form with InputNumber and set its initial value to "foo". Submit the form w/o touching the input.

### What is expected?
The form should validate the input value and either display an error message or follow the default InputNumber behavior and remove the invalid value.

### What is actually happening?
Form submits successfully.

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | react 17.0.2 |
| System | macOS Monterey 12.1 |
| Browser | Google Chrome version 98.0.4758.102 |

---
Sometimes, initialValues come with API requests and it's not guaranteed that the passed object is valid. Form validation should try to catch all invalid values (not just some touched inputs) on form submit.

**Comment by afc163** [comment]
It is intented behavior, you have to make sure default value of form items is valid by yourself. Form validation only works in user interaction.

**Comment by rpelorosso** [comment]
> It is intented behavior, you have to make sure default value of form items is valid by yourself. Form validation only works in user interaction.

Is there a way to get the validator from the form? If not we would have to write our own validation code when the form already has one.

**Comment by Sajeerks** [comment]
how  can we fix that issue  and running validator on intialvalues

**Comment by raymondKelly** [comment]
> It is intented behavior, you have to make sure default value of form items is valid by yourself. Form validation only works in user interaction.

Why would that ever be the intended behaviour?
