### ISSUE TITLE
shouldUpdate 回调对于数组节点删除操作，没有传入正确参数

### ISSUE THREAD

**Issue by git-pwn** [ant-design/ant-design#34077]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-sybjkt?file=src/App.js](https://stackblitz.com/edit/react-sybjkt?file=src/App.js)

### Steps to reproduce
- 首先打开 console
- 点击一下 delete 按钮
- 可以看到，`shouldUpdate` 里的 `prev` 和 `current` 参数，返回的都是**最新的**值，所以在删除时，计算没法更新

### What is expected?
`shouldUpdate` 的 `prev` 参数，对于数组节点，应该返回**老的**值。

### What is actually happening?
`shouldUpdate` 的 `prev` 参数，对于数组节点，返回了**最新的**值。

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17.0.2 |
| System | macOS Big Sur 11.4 (20F71) |
| Browser | Chrome |

---
删除场景可以重现。如果值修改数组元素的属性，则没有这个问题。

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-imner2?file=src/App.js

value.splice 会修改原值，需要改成 immutable 的写法。
