### ISSUE TITLE
Not able to use ANTD with latest typescript react definitions.

### ISSUE THREAD

**Issue by delaneyj** [ant-design/ant-design#3408]
Sorry English speaker,

Trying to get a working up to date version of antd setup with the rest of my project.  `npm install -D antd @types\react @types\react-dom` gives a host of errors.  Narrowed down to mostly updates in the .d.ts.  It appears the latest [react type definitions](https://www.npmjs.com/package/@types/react) added generics to things such as MouseEvent (now MouseEvent<T>).  I added the `<T>` changes locally but not familiar enough with codebase to know if this causes break changes for more than a simple hello world app.

Also its looking for a module `rc-select`, had to `npm i -D @types/rc-select` to remove that issue as well.

**Comment by afc163** [comment]
same problem? https://github.com/ant-design/ant-design/issues/3358

**Comment by delaneyj** [comment]
Yeah, looks like exactly the same issue.  Will close so other takes precedence.  Sorry for the duplicate issue.

**Comment by AlbertZheng** [comment]
@delaneyj I am working in progress for antd 2.0.1 supporting TypeScript 2.0.3 today. Please wait a moment.

**Comment by AlbertZheng** [comment]
@delaneyj I have finished the fixes and created a pull request #3439 for review.

**Comment by delaneyj** [comment]
@AlbertZheng your changes look much better than the stuff I did locally.  Thanks!

**Comment by AlbertZheng** [comment]
@delaneyj You are welcome:)
