### ISSUE TITLE
How to make Input Field autogrow based on length of its value?

### ISSUE THREAD

**Issue by piyushchauhan** [ant-design/ant-design#34083]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want the Input field to autogrow in width when I start typing in more characters. This should also parallely shift the suffix icon of the Input Box according to the length.
Currently the 

### What does the proposed API look like?
`<Input grow={direction: 'right', max: 100} />`
`<Input grow={direction: 'center', max: 100} />`
`<Input grow={direction: 'left', max: 100} />`

**Comment by afc163** [comment]
Try control htmlSize by your input value's length.

**Comment by piyushchauhan** [comment]
> Try control `<Input htmlSize={value.length} value={value} />` by your input value's length.

Doesn't work. Tested here https://codesandbox.io/s/basic-usage-antd-4-18-7-forked-zuso0f?file=/index.js
