### ISSUE TITLE
Form.Item的label出现在Input后方

### ISSUE THREAD

**Issue by niitlxr** [ant-design/ant-design#3409]
#### 发生问题的环境是：

- antd 版本:"antd": "^2.0.1",
- 操作系统及其版本:windows7
- 浏览器及其版本:firefox 49.0.1

#### 您做了什么？
定义了一个form

function IndexPage() {
  return (
      <Form horizontal>
		<Form.Item label="用户名" lableCol={{span:2}} wrapperCol={{span:2}}>
			<Input defaultValue="" id="username"/>
		</Form.Item>
		<Form.Item label="密码" lableCol={{span:2}} wrapperCol={{span:2}}>
			<Input defaultValue="" id="password"/>
		</Form.Item>
		<Button type="primary">登录</Button>
	  </Form>
  );
}

#### 您期待的结果是：

像官网一样正常显示，label在左边，input在右边

#### 实际上的结果是：

label在右边，input在左边，错位

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by afc163** [comment]
ping~

**Comment by benjycui** [comment]
。。。。。。。。。。。。。。。。。。。。。

完全没有提供有效信息么。。。
