### ISSUE TITLE
希望 Menu 导航菜单能增加 mode="vertical" 和  mode="inline" 两个模式之间无刷新切换

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#341]
常常有这种需求， 在已开始载入的时候使用 mode="inline" 方案，在用户操作过程中，遇到表格字段较多时，希望使用更多的屏宽，此时希望左侧菜单能够折叠，就是类似  mode="vertical"  的效果。
即用很小的宽度展示一级菜单，二级菜单用浮层的方式展示。

但现在的问题是，如果我在一个页面内想同时使用这两种效果时，在切换时需要刷新页面，体验特别不好，只能放弃使用，改用自己实现了。

**Comment by yiminghe** [comment]
没办法，要么写两个 menu 组件
