### ISSUE TITLE
List 组件包裹的 Line图，SVG渲染的时候会出现打印预览和导出PDF没图空白

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#34104]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/rawbin-/chrome-webkit-svg-print-debug](https://github.com/rawbin-/chrome-webkit-svg-print-debug)

### Steps to reproduce
yarn && yarn dev 跑起来
用Chrome访问 http://localhost:8001/index 然后打印预览

### What is expected?
期望List包裹的图打印预览和导出PDF能正常出图，
<img width="496" alt="image" src="https://user-images.githubusercontent.com/8169783/154443188-37c0a21c-96c0-43f4-bec4-b5155b791816.png">

### What is actually happening?
<img width="1645" alt="iShot2022-02-17 15 57 33" src="https://user-images.githubusercontent.com/8169783/154442816-72ea9ac8-63d6-41fb-aef8-b3ea76311f61.png">

实际结果是使用List包裹的图打印预览出不来
在如下浏览器均可复现
Chrome Canray 100.0.4881.2
Chrome 98.0.4758.80
Edge dev 99.0.1150.7
Edge 98.0.1108.55 

在Opera，Firefox和Safari当前最新版本中正常

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17.0.2 |
| System | masOS Monterey 12.1 |
| Browser | 98.0.4758.80 |

**Comment by rawbin-** [comment]
同时也提issue给 [chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1298795) 了，puppeteer跟chromium是一回事

**Comment by afc163** [comment]
可以给 LineChart config 里加个 `animation: false`，我本地测试就可以渲染出数据了。

**Comment by rawbin-** [comment]
@afc163  妥妥的，这个方法很赞，刚好注释还能写一起
```
  const config = {
    renderer: 'svg', // 这样导出PDF报表才清晰
    animation: false, // 解决当前最新 Chrome,Edge，Opera各个版本打印预览（导出PDF）svg图出不来的问题 参考 https://bugs.chromium.org/p/chromium/issues/detail?id=1298795
}
```

**Comment by afc163** [comment]
先关了，感觉还是需要 Chrome 解决。
