### ISSUE TITLE
Dynamic Theme breakes on SSR

### ISSUE THREAD

**Issue by wuifdesign** [ant-design/ant-design#34100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
`npx create-next-app@latest --ts`
`npm i antd`

Then change `_app.tsx` and add 
```
import { ConfigProvider } from 'antd'

ConfigProvider.config({
  theme: {
    primaryColor: '#f00'
  }
})
```

### What is expected?
Build successfull

### What is actually happening?
Build fails with:

```
ReferenceError: document is not defined
  at getContainer (./node_modules/rc-util/lib/Dom/dynamicCSS.js:32:14)
  at updateCSS (./node_modules/rc-util/lib/Dom/dynamicCSS.js:90:19)
  at registerTheme (./node_modules/antd/lib/config-provider/cssVariables.js:96:29)
  at Function.setGlobalConfig [as config] (./node_modules/antd/lib/config-provider/index.js:87:37)
  at eval (webpack-internal:///./pages/_app.tsx:14:50)
  at Object../pages/_app.tsx (./.next/server/pages/_app.js:22:1)
  at __webpack_require__ (./.next/server/webpack-runtime.js:33:42)
  at __webpack_exec__ (./.next/server/pages/_app.js:64:39)
  at ./.next/server/pages/_app.js:65:28
  at Object.<anonymous> (./.next/server/pages/_app.js:68:3)
```

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17 |
| System | Mac OS |
| Browser | - |

**Comment by johnmagbag1995** [comment]
Try wrapping it with `if (typeof window === 'object')`

**Comment by zombieJ** [comment]
We can patch warning for call this on server side. But flash need another way like `display: none` and back to visible after react render.

**Comment by wuifdesign** [comment]
but this is not the optimal way, maybe you can expose a funtion that generates the required CSS Styles. So we can run this at SSR and inject the styles ourself?

something that we can get this on SSR:
```
:root {
    ${cssList.join('\n')}
  }
```

**Comment by wuifdesign** [comment]
@zombieJ

**Comment by IRediTOTO** [comment]
> but this is not the optimal way, maybe you can expose a funtion that generates the required CSS Styles. So we can run this at SSR and inject the styles ourself?
> 
> something that we can get this on SSR:
> 
> ```
> :root {
>     ${cssList.join('\n')}
>   }
> ```
> 
> so we can pass them as props and inject it via:
> 
> ```
> <style>{props.themeStyles}</style>
> ```

I love this way, can you please share the code to do that ?

**Comment by bombillazo** [comment]
@wuifdesign Were you able to solve this issue?
