### ISSUE TITLE
升级2.0.1后编译项目出现 “Module not found: ./locale”警告

### ISSUE THREAD

**Issue by SXCYF** [ant-design/ant-design#3411]
升级2.0.1后，编译项目报下面的警告：

Compiled with warnings.

Warning in ./~/.2.0.1@antd/dist/antd.js
Module not found: ./locale in ***\node_modules\.2.0.1@antd\dist
 @ ./~/.2.0.1@antd/dist/antd.js 8289:17-44

“***”好为路径前缀，这里做了处理。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/3204

**Comment by benjycui** [comment]
这个应该是因为 parse 了构建后的文件？

试下 https://webpack.github.io/docs/configuration.html#module-noparse

**Comment by afc163** [comment]
总结方案：https://github.com/ant-design/ant-design/issues/3204#issuecomment-253436125
