### ISSUE TITLE
Tree 使用 titleRender，右侧使用了 Dropdown 组件，点击 Menu 时候，会触发Tree onSelect事件

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design#34119]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

使用体验问题，左Tree，右Table场景，有时候我只是想对这个Tree进行操作，并不想触发onSelect 并触发Table查询功能。

<img width="260" alt="image" src="https://user-images.githubusercontent.com/30397655/154643400-89bbe13f-cc1a-4d70-a1f7-6d7ee1987c91.png">

### What does the proposed API look like?

点击 Menu，不触发Tree onSelect事件，只有点击主体时，才会触发。

**Comment by MadCcc** [comment]
给个复现。
不过你这种情况多半 `stopPropagation` 就能解决。

**Comment by leshalv** [comment]
使用 stopPropagation 确实不会 触发onselect 事件了，同样也会造成 Dropdown无法关闭

<img width="740" alt="image" src="https://user-images.githubusercontent.com/30397655/154644336-f7a58f65-1c99-416c-b3af-6217beecc4fe.png">

**Comment by MadCcc** [comment]
@leshalv 给个复现

**Comment by leshalv** [comment]
`import { Dropdown, Menu, Tree } from 'antd';
import { PageContainer } from '@ant-design/pro-layout';
import { MoreOutlined } from '@ant-design/icons';
const treeData = [
  {
    title: 'parent 1',
    key: '0-0',
    children: [
      {
        title: 'parent 1-0',
        key: '0-0-0',
        disabled: true,
        children: [
          {
            title: 'leaf',
            key: '0-0-0-0',
            disableCheckbox: true,
          },
          {
            title: 'leaf',
            key: '0-0-0-1',
          },
        ],
      },
      {
        title: 'parent 1-1',
        key: '0-0-1',
        children: [
          {
            title: (
              <span
                style={{
                  color: '#1890ff',
                }}
              >
                sss
              </span>
            ),
            key: '0-0-1-0',
          },
        ],
      },
    ],
  },
];

const Demo = () => {
  const onSelect = (selectedKeys: any, info: any) => {
    console.log('selected', selectedKeys, info);
  };

  const onCheck = (checkedKeys: any, info: any) => {
    console.log('onCheck', checkedKeys, info);
  };
  const menu = (
    <Menu>
      <Menu.Item>
        <a
          onClick={(e) => {
            e.stopPropagation();
          }}
        >
          新增
        </a>
      </Menu.Item>
    </Menu>
  );
  return (
    <PageContainer>
      <Tree
        defaultExpandedKeys={['0-0-0', '0-0-1']}
        defaultSelectedKeys={['0-0-0', '0-0-1']}
        defaultCheckedKeys={['0-0-0', '0-0-1']}
        onSelect={onSelect}
        onCheck={onCheck}
        treeData={treeData}
        blockNode
        titleRender={(node) => {
          return (
            <div>
              <span style={{ paddingRight: '10px' }}>{node.title}</span>
              <Dropdown overlay={menu}>
                <MoreOutlined />
              </Dropdown>
            </div>
          );
        }}
      />
    </PageContainer>
  );
};
export default Demo;
`

**Comment by leshalv** [comment]
``` tsx
import { Dropdown, Menu, Tree } from 'antd';
import { PageContainer } from '@ant-design/pro-layout';
import { MoreOutlined } from '@ant-design/icons';
const treeData = [
  {
    title: 'parent 1',
    key: '0-0',
    children: [
      {
        title: 'parent 1-0',
        key: '0-0-0',
        disabled: true,
        children: [
          {
            title: 'leaf',
            key: '0-0-0-0',
            disableCheckbox: true,
          },
          {
            title: 'leaf',
            key: '0-0-0-1',
          },
        ],
      },
      {
        title: 'parent 1-1',
        key: '0-0-1',
        children: [
          {
            title: (
              <span
                style={{
                  color: '#1890ff',
                }}
              >
                sss
              </span>
            ),
            key: '0-0-1-0',
          },
        ],
      },
    ],
  },
];

const Demo = () => {
  const onSelect = (selectedKeys: any, info: any) => {
    console.log('selected', selectedKeys, info);
  };

  const onCheck = (checkedKeys: any, info: any) => {
    console.log('onCheck', checkedKeys, info);
  };
  const menu = (
    <Menu>
      <Menu.Item>
        <a
          onClick={(e) => {
            e.stopPropagation();
          }}
        >
          新增
        </a>
      </Menu.Item>
    </Menu>
  );
  return (
    <PageContainer>
      <Tree
        defaultExpandedKeys={['0-0-0', '0-0-1']}
        defaultSelectedKeys={['0-0-0', '0-0-1']}
        defaultCheckedKeys={['0-0-0', '0-0-1']}
        onSelect={onSelect}
        onCheck={onCheck}
        treeData={treeData}
        blockNode
        titleRender={(node) => {
          return (
            <div>
              <span style={{ paddingRight: '10px' }}>{node.title}</span>
              <Dropdown overlay={menu}>
                <MoreOutlined />
              </Dropdown>
            </div>
          );
        }}
      />
    </PageContainer>
  );
};
export default Demo;

```

**Comment by MadCcc** [comment]
给 `<MoreOutlined />` 添加 `stopPropagation `

**Comment by leshalv** [comment]
https://codesandbox.io/s/festive-zeh-w0h1gk

**Comment by leshalv** [comment]
<MoreOutlined /> 添加 stopPropagation 会造成点击失效

**Comment by MadCcc** [comment]
good luck~

**Comment by Tss-16** [comment]
> 我想我解决了，应该给 `<Menu>` 组件添加 `stopPropagation `

你的弹出的model能正常关闭吗？我点击无效：（
![image](https://github.com/ant-design/ant-design/assets/75489410/ec191509-b8fe-4aa3-8247-f21caf820620)
