### ISSUE TITLE
validateTrigger doesn't work

### ISSUE THREAD

**Issue by pangao66** [ant-design/ant-design#34114]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-18-7-forked-9f1td9?file=/index.js:817-832)

### Steps to reproduce
无论使用onBlur还是onCompositionEnd 都不能触发 校验

### What is expected?
validateTrigger 能够正常工作

### What is actually happening?
用不了

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | mac 12 |
| Browser | chrome |

https://github.com/ant-design/ant-design/issues/27516

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-18-7-forked-5hy9sl

<img width="1129" alt="图片" src="https://user-images.githubusercontent.com/507615/154622157-1be43021-e48c-4335-ad6f-657a4f1a15e9.png">

**Comment by pangao66** [comment]
@afc163 请看看上面的问题？  单独给rules设置validateTrigger: 'onCompositionEnd' 不生效，你上面的是把validateTrigger写在Form.Item上了
