### ISSUE TITLE
LocaleProvider国际化 官方示例BUG[bug]

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3412]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:window 7旗舰版
- 浏览器及其版本:chrome 最新版

#### 您做了什么？

LocaleProvider国际化官方示例的BUG

打开页面

https://ant.design/components/locale-provider/

注意看下面的中英文切换示例

默认的状态是英文状态，执行以下操作

1,点击DatePicker  控件
2,随意选择一个年月日
3,切换英文状态到中文状态
4,再次点击DatePicker 进行日期选择
5,发现日期选择的中英文翻译出现错误

注意：若不进行第2步的日期选择，则选择框翻译为正常的，若进行选择后则不正常

#### 您期待的结果是：

本应该整个选择框里的翻译都为英文

#### 实际上的结果是：

DatePicker 的选择框中的部分翻译仍未中文，只有部分翻译切换为英文

#### 可重现的在线演示

我的联系方式15152238812
![01](https://cloud.githubusercontent.com/assets/6470398/19334908/f5c7f40c-9131-11e6-9a46-c2ac1fe444fd.png)
![02](https://cloud.githubusercontent.com/assets/6470398/19334912/f63ec46a-9131-11e6-918d-e64094f824e4.png)
![03](https://cloud.githubusercontent.com/assets/6470398/19334909/f5cb8e0a-9131-11e6-8a4f-144c154fd88f.png)
![04](https://cloud.githubusercontent.com/assets/6470398/19334910/f5d4fb0c-9131-11e6-88aa-6bd1935bfa0b.png)
![05](https://cloud.githubusercontent.com/assets/6470398/19334911/f5f8895a-9131-11e6-9e71-d5df16f8ff3f.png)

**Comment by eddyzhang1986** [comment]
注意：
若文本框中的日期是空白
也就是没填写值的话则 翻译是正常的
一旦DatePicker的文本框中有值的话，则翻译就会错误。

**Comment by benjycui** [comment]
It's OK. It's just a demo, and that the recommended way to change language in real world is refresh the whole page, see: https://github.com/ant-design/intl-example
