### ISSUE TITLE
antd[tree]: checkable TreeNode gets toggled by clicking anywhere on the title

### ISSUE THREAD

**Issue by abhi40308** [ant-design/ant-design#34136]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-1phxyx?file=index.js](https://stackblitz.com/edit/react-1phxyx?file=index.js)

### Steps to reproduce
Create a tree with `selectable={false}`
Add a node with a checkbox and an HTML `input` element in title.
Try entering some value to the node, it will toggle the checkbox.

[Screencast](https://www.loom.com/share/19836a838e1349f88f0b29e4433d9694)

### What is expected?
Checkbox should only be toggled on click of the checkbox, rather than the whole title value.

### What is actually happening?
Checkbox gets toggled by clicking anywhere on title, due to which I'm not able to add a form to the title. As if i click the title, checkbox will get toggled.

| Environment | Info |
|---|---|
| antd | 4.18.6 |
| React | 16.13.1 |
| System | macOS Monterey 12.2.1 |
| Browser | Google chrome: Version 98.0.4758.80 (Official Build) (x86_64) |

---
The 2 workarounds i can think of are:
1. Adding the form as an extra node as children to the checkbox node, but that's not what i need.
2. Using `selectable={true}` so that onSelect event gets triggered instead of onCheck, but it shows selected area on the node.

[Screencast of workaround 2](https://www.loom.com/share/c51ff6f040aa41048c57fb0862e13ee0)

Update: Was able to move forward with workaround 2, by globally changing the select color to transparent using this:
```
:global(.ant-tree .ant-tree-node-content-wrapper.ant-tree-node-selected) {
  background-color: transparent;
}

:global(.ant-tree .ant-tree-node-content-wrapper:hover) {
  background-color: transparent;
}
```

**Comment by MadCcc** [comment]
https://stackblitz.com/edit/react-1phxyx-qv1phv?file=index.js
Can this solution resolve your problem?

**Comment by abhi40308** [comment]
Hey @MadCcc thanks for this. This could be a possible solution although for my particular use case, checking checkbox will remove the form as shown in this [screencast](https://www.loom.com/share/f4251a87e7844c979169066fb67d6f8a). That could be an issue if the user accidentally clicks on anywhere except the form fields, the form will go away. Could be frustrating for users.

**Comment by MadCcc** [comment]
It is by design, we probably won't support it.

**Comment by abhi40308** [comment]
Thanks for your solution anyways, at the end, I'm using a modified version of your solution, much cleaner!
