### ISSUE TITLE
Select样式问题以及key属性的bug

### ISSUE THREAD

**Issue by lslvxy** [ant-design/ant-design#3413]
示例代码:

[http://codepen.io/lslvxy/pen/qaKVPm?editors=1011](http://codepen.io/lslvxy/pen/qaKVPm?editors=1011)

说明:

select在table组件里面,加上了`showSearch`配置后下拉框展示后宽度变宽

给select设置一个固定宽度的话table的列宽度也会变宽

给`Option`设置key属性无效,生成的key还是value值

**Comment by benjycui** [comment]
> 给Option设置key属性无效,生成的key还是value值

这个是 by designed 的。

**Comment by benjycui** [comment]
同时使用 `showSearch` 并把 `Select` 的宽度设为百分比时会有这个问题。。

先直接使用固定宽度来规避这个问题。
