### ISSUE TITLE
Cascader 支持 选择任意一级选项

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#34140]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些场景下可以选择层级中的任意一层，类似element plus中的
https://element-plus.gitee.io/zh-CN/component/cascader.html#%E9%80%89%E6%8B%A9%E4%BB%BB%E6%84%8F%E4%B8%80%E7%BA%A7%E9%80%89%E9%A1%B9

### What does the proposed API look like?
<Cascader checkStrictly="true" ...>

**Comment by MadCcc** [comment]
https://ant.design/components/cascader-cn/#components-cascader-demo-change-on-select
你要的应该是这个。

**Comment by Lume98** [comment]
他要的不是这个，他想要的是任意层级的任意一层
