### ISSUE TITLE
Form.Item possibility to set trigger to `false`

### ISSUE THREAD

**Issue by IovlevYuliy** [ant-design/ant-design#34148]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Problem: do not trigger onFieldsChange on Form when using FormInstance to control fields of form.
I tried to set non existing event to "trigger" but it leads to warning from React. See [example](https://codesandbox.io/s/antd-form-trigger-ucgszk?file=/index.js)

### What does the proposed API look like?
Add `false` to values of trigger for Form.Item

**Comment by MadCcc** [comment]
Then how to trigger validation?

**Comment by IovlevYuliy** [comment]
> Then how to trigger validation?
There are 2 options:
1. Use "validateTrigger" prop for validation events.
2. Do the validation manually via call validateFields().
I do not have problems with validation, in my case I have complex structure of components inside `Form.Item` and I want to forbid collecting values from nested Inputs by `onChange` events.

**Comment by MadCcc** [comment]
I don't understand. If you do not need validation, just ignore that prop, or you can customize validation status with `validateStatus`.
Or did you have problem with performance?

**Comment by IovlevYuliy** [comment]
I can not just ignore prop `trigger` because its default value is `onChange`. I have created an [example](https://codesandbox.io/s/antd-form-trigger-issue-289enl?file=/index.js) of described problem, there is `List` with inputs inside, you can see what happens when you change the inputs (`Form.Item` triggers on input changing and try to extract new value of `listData` from `onChange` event). But I want to handle `onChange` manually and update `listData` as well.

**Comment by zombieJ** [comment]
That's no magic on `trigger`. You can customize this as the same way as customize component (but omit the prop you want):
https://codesandbox.io/s/antd-form-trigger-forked-lyej3i?file=/index.js

**Comment by IovlevYuliy** [comment]
@zombieJ Sure it works but as for me it looks like a workaround. If you use different components inside list you have to customize each of them.
I think possibility to set `trigger` to `false` seems clearer. Interesting that `validateTrigger` supports `false` value, but why do not implement the same behavior for `trigger`?
![image](https://user-images.githubusercontent.com/14806291/157431280-f9a5cede-cdcb-4c9c-90d6-4e47e46bd9d6.png)

**Comment by zombieJ** [comment]
Form is strong control mode which means `value` & `change trigger` is pare work. So when set `trigger` to `false` or any other not exist event to skip the control circle is DO A WORKAROUND for escape the Form control. It's also you can see trigger def is a string type or 'onChange' if `undefined`. It's by design.
