### ISSUE TITLE
建议将Table增加下拉刷新和列定制功能

### ISSUE THREAD

**Issue by jindada** [ant-design/ant-design#3414]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: win 7
- 浏览器及其版本: google 53.0

**Comment by benjycui** [comment]
`antd` 是 for PC 的，对手势操作没有做优化，请用 `antd-mobile`。

**Comment by benjycui** [comment]
> 列定制功能

这个应该已经支持了吧，`columns[n].title` `columns[n].render` 。

https://ant.design/components/table/#Column

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
