### ISSUE TITLE
Divider component: change 'orientation' prop values to start/center/end (instead of left/center/right)

### ISSUE THREAD

**Issue by boazr-neosec** [ant-design/ant-design#34147]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/u95kp)

### Steps to reproduce
put a 'direction: rtl' on 'body' element in the CSS file and see that the 'left' value of 'orientation' prop actually becomes 'right', therefore a better value for the prop will be 'start'

### What is expected?
In right-to-left languages, like Hebrew and Arabic, when the container has 'direction: rtl;' css property, everything works fine but the semantic meaning of the 'orientation' prop is wrong: 'left' value actually means 'start' and indeed sends the divider's title to the right of the screen (where the text starts from - right to left...). Same goes with 'right' value - it actually means 'end', just like in flex layout model.

### What is actually happening?
Everything works as expected but the values of the props look bad as 'left' is actually right

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 16,17 |
| System | OS X |
| Browser | Chrome (latest) |

**Comment by MadCcc** [comment]
Currently 'left'/'right' is used a lot in antd's placement, so it's hard to make such a breaking change. 
But we will take your advice into consider if there's chance to refactor it.
Thx~
