### ISSUE TITLE
如何根据table数据，动态计算合并单元格( rowSpan)

### ISSUE THREAD

**Issue by lmymoonsky** [ant-design/ant-design#34144]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
根据返回数据，动态合并单元格

### What does the proposed API look like?
在 column 中给出配置项

**Comment by MadCcc** [comment]
建议使用 `column` 中的 `render` 属性。

**Comment by lmymoonsky** [comment]
> 建议使用 `column` 中的 `render` 属性。

你好，render 只是控制当前渲染项，但如何控制表格 合并呢？如果渲染空单依旧会有 border 存在呀？

**Comment by lmymoonsky** [comment]
合并单元格 建议用 onCell 中的 rowSpan 和 colSpan的吧，现在是用的最新版，用 render 会有其他问题吗？

**Comment by MadCcc** [comment]
用 onCell 会比较好



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 二月 ***@***.***&gt;
发送时间: 2022年2月21日 11:51
收件人: ant-design/ant-design ***@***.***&gt;
抄送: MadCcc ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [ant-design/ant-design] 如何根据table数据，动态计算合并单元格( rowSpan) (Issue #34144)





 
合并单元格 建议用 onCell 中的 rowSpan 和 colSpan的吧，现在是用的最新版，用 render 会有其他问题吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lmymoonsky** [comment]
但 onCell 也一样，如何根据值是否相等来 动态计算 rowSpan呢？

**Comment by yoyo837** [comment]
你是希望根据值相同来决定是否合并？我自己项目就有基于antd实现这个功能，完全不需要额外新增什么AP I。

**Comment by lmymoonsky** [comment]
是根据值 是否相同来计算 rowSpan ，决定是否合并。
我看当前 只有固定 的判断模式，比如事先就知道要合并哪几行，根据 index 来 设置 rowSpan .
请问 你自己项目  是如何 判断的呢？

**Comment by lmymoonsky** [comment]
是可以在渲染前，拿到table 数据，然后递归遍历，把 rowSpan 计算出来，不过这样很占内存，渲染表格过于慢。

**Comment by yoyo837** [comment]
我甚至自己二次封装了一个 rowSpanByValue 传入，相邻的若干行，通过这个方法传入record计算出一样的值就合并对应的列。

也是纯粹基于render props  rowSpan colspan

**Comment by yoyo837** [comment]
antd 只给出API实现跨行跨列没问题，其他的需要自己业务封装。

**Comment by lmymoonsky** [comment]
好的，了解了，感谢！

**Comment by yoyo837** [comment]
如果需要，可以私下联系我交流一下

**Comment by lmymoonsky** [comment]
> 如果需要，可以私下联系我交流一下

好的，如何联系您呢？

**Comment by yoyo837** [comment]
邮箱联系我给你钉钉或者微信号

**Comment by lmymoonsky** [comment]
> lmymoonsky

已发至 [yoyo837@hotmail.com] 邮箱

**Comment by Zexoius** [comment]
> 是根据值 是否相同来计算 rowSpan ，决定是否合并。 我看当前 只有固定 的判断模式，比如事先就知道要合并哪几行，根据 index 来 设置 rowSpan . 请问 你自己项目 是如何 判断的呢？

`onSuccess: ({ data }) => {
      if (data.returnCode === StatusCode.success) {
        // 首先分组
        const grouped = groupBy(data.list, v => v.type);
        // 其次合并，第一项占行，后续为0
        const result = Object.keys(grouped)
          .map(k => grouped[k].map((v, i, arr) => ({ ...v, rowSpan: i === 0 ? arr.length : 0 })))
          .flatMap(v => v);
        setDataSource(result);
      }
    },`

columns 配置中这么用
`  {
    title: '类别',
    dataIndex: 'type',
    onCell: (record, index) => ({ rowSpan: record.rowSpan }),
  },`

可以实现，但是遇到个棘手的问题：如果组的第一项残留在第一页末尾，翻到第二页的时候会出现该列丢失，但是其他的组占行没问题，不知道是不是 table 的渲染问题，**仅在一次性加载全部数据时遇到过**。

**Comment by LeeRayno** [comment]
我这边基于 antd5.X实现一个，但是复杂度有点高，有没有大佬来优化一下

[codesandbox-demo](https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-undefined-forked-medins?file=/demo.tsx)

```tsx
import React from "react";
import { Table } from "antd";

const convertDataToRowSpan = (data = [], columns = []) => {
  const keys = columns.map((item) => item.dataIndex);
  for (const key of keys) {
    for (let i = 0; i < data.length; i++) {
      let count = 1;
      let r = i;

      for (let j = i + 1; j < data.length; j++) {
        if (data[i][key] === data[j][key]) {
          count++;
          i = j;
          if (!data[j].row_span_map) {
            data[j].row_span_map = {};
          }
          data[j].row_span_map[key] = 0;
        } else {
          break;
        }
      }

      if (!data[r].row_span_map) {
        data[r].row_span_map = {};
      }

      data[r].row_span_map[key] = count;
    }
  }

  return data;
};

const data = [
  { name: 1, age: 19, sex: 1 },
  { name: 1, age: 17, sex: 2 },
  { name: 2, age: 18, sex: 3 },
  { name: 2, age: 18, sex: 4 },
  { name: 2, age: 19, sex: 5 },
  { name: 2, age: 18, sex: 5 },
  { name: 1, age: 19, sex: 7 },
  { name: 2, age: 19, sex: 8 },
  { name: 1, age: 19, sex: 1 },
  { name: 1, age: 19, sex: 2 }
];

const columns = [
  {
    title: "name",
    dataIndex: "name"
  },
  {
    title: "age",
    dataIndex: "age"
  },
  {
    title: "sex",
    dataIndex: "sex"
  }
];

const ProTable = (props) => {
  const {
    columns = [],
    dataSource = [],
    autoMerge = false,
    ...restProps
  } = props;

  const proColumns = autoMerge
    ? columns.map(({ dataIndex, ...restCol }) => ({
        dataIndex,
        onCell: (record) => ({ rowSpan: record.row_span_map[dataIndex] }),
        ...restCol
      }))
    : columns;

  const proData = autoMerge
    ? convertDataToRowSpan(dataSource, columns)
    : dataSource;

  console.log("---- covertDataToRowSpan(data) ----", proData);

  return <Table columns={proColumns} dataSource={proData} {...restProps} />;
};

const App: React.FC = () => (
  <>
    <h2>merged</h2>
    <ProTable columns={columns} dataSource={data} autoMerge={true} bordered />

    <h2>not merged</h2>
    <ProTable columns={columns} dataSource={data} autoMerge={false} bordered />
  </>
);

export default App;


```

**Comment by duoluodexiaoxiaoyuan** [comment]
https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-4-24-10-forked-lnnhs7?file=/demo.tsx

假如antd的版本是4.15.6的话 rowSpan会失效，想问下大佬们有没有解决方法

**Comment by yoyo837** [comment]
> https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-4-24-10-forked-lnnhs7?file=/demo.tsx
> 
> 假如antd的版本是4.15.6的话 rowSpan会失效，想问下大佬们有没有解决方法

我怎么看见你用的不对

**Comment by yoyo837** [comment]
不应该是这样吗:
```js
render: () => {
  return {
    children: xxx,
    proprs: {
        rowSpan: x,
        colSpan: x,
    }
  }
}
```

**Comment by duoluodexiaoxiaoyuan** [comment]
> 不应该是这样吗:
> 
> ```js
> render: () => {
>   return {
>     children: xxx,
>     proprs: {
>         rowSpan: x,
>         colSpan: x,
>     }
>   }
> }
> ```

是的，感谢解答。我在别的issue里面找到了解决方法，比较好奇因为现在antd-design官方文档已经没有写这种写法了，不知道遇到类似的问题都来github的 issue找答案吗

**Comment by yoyo837** [comment]
文档也是人维护的, 有时候有遗漏, 或者错误, 欢迎PR帮助完善, 无论是代码还是文档.

**Comment by duoluodexiaoxiaoyuan** [comment]
> 文档也是人维护的, 有时候有遗漏, 或者错误, 欢迎PR帮助完善, 无论是代码还是文档.

感谢大佬解答。确实版本老了，也不知道写到文档哪个位置

**Comment by 15238381693** [comment]
> 不应该是这样吗:
> 
> ```js
> render: () => {
>   return {
>     children: xxx,
>     proprs: {
>         rowSpan: x,
>         colSpan: x,
>     }
>   }
> }
> ```

@yoyo837  请教大佬一个问题，我使用上述格式替换了我的render函数，但是现在render函数内的内容会执行多次，例如鼠标滑动到列表页面的某一项就会触发一次。我发现如果render返回的是个node就不会存在这种情况，返回的是对象就会存在。
[demo](https://codesandbox.io/s/cha-xun-biao-ge-forked-fvww4t?file=/App.tsx)

**Comment by arronf2e** [comment]
@yoyo837 求教下，合并单元格的 rowSpan可以根据树型数据的展开收起动态计算吗？类似下图，左侧的高度根据右侧的展开收起动态计算？
<img width="760" alt="image" src="https://github.com/ant-design/ant-design/assets/15780058/9e8e45bc-82fb-4ab0-8eef-b9a25a6d3a19">

**Comment by yoyo837** [comment]
> @yoyo837 求教下，合并单元格的 rowSpan可以根据树型数据的展开收起动态计算吗？类似下图，左侧的高度根据右侧的展开收起动态计算？ <img alt="image" width="760" src="https://private-user-images.githubusercontent.com/15780058/295218444-9e8e45bc-82fb-4ab0-8eef-b9a25a6d3a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDgwMzYsIm5iZiI6MTcwNDgwNzczNiwicGF0aCI6Ii8xNTc4MDA1OC8yOTUyMTg0NDQtOWU4ZTQ1YmMtODJmYi00YWIwLThlZWYtYjlhMjVhNmQzYTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzNDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0ODA0MWM3MzdkNjc4OTMxZDdlNDFmZTRhZGM0YTQwYTZiOGI4YmQ2YmY5MjBmOTBiY2Q4YmJmZDBkMDg0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ce5Aw1TkLSv9PbzkX8Sr-mOnQ2CUuNADPhHr0yxh1_Q">

理论上可以的，按逻辑给对跨行列的值就好了。

**Comment by yoyo837** [comment]
> > 不应该是这样吗:
> > ```js
> > render: () => {
> >   return {
> >     children: xxx,
> >     proprs: {
> >         rowSpan: x,
> >         colSpan: x,
> >     }
> >   }
> > }
> > ```
> 
> @yoyo837 请教大佬一个问题，我使用上述格式替换了我的render函数，但是现在render函数内的内容会执行多次，例如鼠标滑动到列表页面的某一项就会触发一次。我发现如果render返回的是个node就不会存在这种情况，返回的是对象就会存在。 [demo](https://codesandbox.io/s/cha-xun-biao-ge-forked-fvww4t?file=/App.tsx)

听上去是正常的，rerender有关。
