### ISSUE TITLE
Safari 访问antd主页卡顿

### ISSUE THREAD

**Issue by TinyStorm** [ant-design/ant-design#34151]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
使用Safari访问antd主页

### What is expected?
不卡

### What is actually happening?
鼠标左、右键，单双击，滑动等操作均有卡顿

| Environment | Info |
|---|---|
| antd | undefined |
| React | null |
| System | osx 12.2.1 |
| Browser | Safari |

---
使用chrome访问无卡顿；
当我把浏览器拖到扩展屏（2K）时候，也不卡顿，似乎只有在内置的屏幕使用safari才会卡顿；
另外使用safari访问antd的其他页面均正常，只有主页才会卡顿。

**Comment by MadCcc** [comment]
录屏看看？

**Comment by TinyStorm** [comment]
https://user-images.githubusercontent.com/29775804/155076381-6298756f-2b49-4c98-a6af-b42a67a9ed0d.mov
原分辨率，进行了压缩。应该能看出来明显的卡顿吧

**Comment by MadCcc** [comment]
还真是。。我电脑上也有明显卡顿

**Comment by MadCcc** [comment]
先关了，感觉是 safari 问题。
