### ISSUE TITLE
ant里的Menu和树形表格组件，新增功能

### ISSUE THREAD

**Issue by mickeyzhou** [ant-design/ant-design#3415]
可不可以提供一个接口，比如curKey,用于选中当前项，并展开其所有父级,我觉得这个应用场景还挺多的

**Comment by afc163** [comment]
openKeys

**Comment by mickeyzhou** [comment]
使用这两个接口确实可以实现该功能，但是，业务开发需要写很多代码，如果组件内部能添加一个接口，如传一个key，就能展开所有父级，并选中当前项，会简化很多业务开发重复的代码

**Comment by afc163** [comment]
建议上层二次封装一下，currentKey 是更加高级的属性，直接实现在底层容易和现有属性造成概念混淆。
