### ISSUE TITLE
Tooltip is not triggered when `title` prop has value

### ISSUE THREAD

**Issue by pobch** [ant-design/ant-design#34163]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-tesla-1ugd31?file=/src/App.js)

### Steps to reproduce
1. Go to https://codesandbox.io/s/vigorous-tesla-1ugd31?file=/src/App.js
2. Type "x"
3. You can see from the `console.log()` that the current `title` prop is `undefined`
4. Type `backspace` to remove "x"
5. From the `console.log()`, now the current `title` prop is `"Required field"`

### What is expected?
The Tooltip should be displayed with the message `Required field` since at step 5 there are `trigger="focus"` and `title="Required field"` props on Tooltip.

### What is actually happening?
Tooltip is not displayed

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17.0.2 |
| System | Mac OS 12.1 |
| Browser | Firefox 96 |

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/155252933-305be97e-35d4-4bd0-8a2f-2125eb699f36.png)
It works.

**Comment by pobch** [comment]
@MadCcc It will work once you "blur" the input, then "focus" it again.
To reproduce the bug:
1. Refresh the page
2. Do all steps **without blurring the input**

**Comment by kanweiwei** [comment]
@pobch  It only works when the 'onFocus' can be trigger. If the input is being editing, it won't trigger 'focus' event. 
You can do like this: https://codesandbox.io/s/proud-shadow-t08b2b?file=/src/App.js

**Comment by zombieJ** [comment]
@kanweiwei answer the question. trigger is trigger, dynamic change `title` do not trigger `focus` again since `focus` is only fire once when get focused.
