### ISSUE TITLE
Select tag mode ignore enter key to add new entry

### ISSUE THREAD

**Issue by fstn** [ant-design/ant-design#34164]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/automatic-tokenization-antd-4-18-8-forked-l9z4hi)

### Steps to reproduce
Type a value in the select and type enter

### What is expected?
element must be selected

### What is actually happening?
nothing happened

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 16.8.6 |
| System | ALL |
| Browser | Chrome |

**Comment by fstn** [comment]
Works with "react": "^17.0.2"

**Comment by MadCcc** [comment]
Could you upgrade your react version to v16 latest? v16.14.x here works.

**Comment by fstn** [comment]
Yes I can, do you have any explanation of this bug?

**Comment by MadCcc** [comment]
Not clear, maybe something wrong with `KeyboardEvent`. I will dig into it later.
