### ISSUE TITLE
Form's `normalize` does not work correctly with InputNumber

### ISSUE THREAD

**Issue by pobch** [ant-design/ant-design#34162]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ancient-dawn-fgwk0?file=/src/App.js)

### Steps to reproduce
1. Go to https://codesandbox.io/s/ancient-dawn-fgwk0?file=/src/App.js
2. Type "987" in the input

### What is expected?
Without blurring the input, it should display "0"

### What is actually happening?
The input display "087"

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17.0.2 |
| System | Mac OS 12.1 |
| Browser | Firefox 96 |

**Comment by pobch** [comment]
Same bug in the case of using `setFieldsValue` inside `onChange`
https://github.com/ant-design/ant-design/issues/34023

**Comment by afc163** [comment]
It is not a bug, InputNumber will show `0` when you are typing `9` which is start of `987`.

**Comment by pobch** [comment]
@afc163 If the same logic applied, it should behave like this:
1. Start to type `9` -> `normalize` is triggered -> output `0`
2. Continue to type `8`(now it's `08`) -> `normalize` is triggered -> output `0`
But, right now 1. and 2. are behave differently.

Moreover, if I switch from `InputNumber` to `Input`, this bug does not occur.

**Comment by afc163** [comment]
Try `<InputNumber stringMode />` in this case.

**Comment by pobch** [comment]
Using `stringMode` does **not** solve the issue. @afc163

**Comment by afc163** [comment]
I suggest that creating a `<InputNumberLessThen5 />` instead of using `normalize`: https://codesandbox.io/s/goofy-silence-1cpwkc?file=/src/App.js

**Comment by pobch** [comment]
> I suggest that creating a `<InputNumberLessThen5 />` instead of using `normalize`: https://codesandbox.io/s/goofy-silence-1cpwkc?file=/src/App.js

Your approach in codesandbox still does **NOT** resolve the issue. If I type `987`(3 keystrokes), the logic inside `onChange` will NOT be applied on 2nd and 3rd keystroke. @afc163

**Comment by rfgonzalezweb** [comment]
it won't work well with <DatePicker/> either :crying_cat_face: 
https://stackblitz.com/edit/react-ydr6fz?file=demo.js
