### ISSUE TITLE
Auto complete 能够回填 ReactNode

### ISSUE THREAD

**Issue by sxlwar** [ant-design/ant-design#34160]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义回填的内容，丰富显示信息
目前只能回填 value 值，显示字符串

### What does the proposed API look like?
无需要另外 api，直接回填Autocomplete.Option （使用 children） 或者 {label： xxx， value： yyy} 中的 label 值（使用options prop}

**Comment by MadCcc** [comment]
https://ant.design/components/auto-complete-cn/#v3-%E7%9A%84%E9%83%A8%E5%88%86%E5%B1%9E%E6%80%A7%E4%B8%BA%E4%BD%95%E5%9C%A8-v4-%E4%B8%AD%E6%B2%A1%E6%9C%89%E4%BA%86%EF%BC%9F
暂不支持。
