### ISSUE TITLE
Calendar - Disable keyboard shortcut `Cmd+Shift+leftarrow` that switches to previous year.

### ISSUE THREAD

**Issue by balraaz15** [ant-design/ant-design#34168]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar/#components-calendar-demo-basic](https://ant.design/components/calendar/#components-calendar-demo-basic)

### Steps to reproduce
1. Go the the link
2. Click on any date and now click `Cmd   Shift   left arrow` or `Cmd   Shift   right arrow`
3. Notice that Year is switched to previous year or next year.

### What is expected?
For the application I am working on, I have a text field inside date display. So, when I try to select the text using keyboard shortcut `Cmd   Shift   left arrow` or `Cmd   Shift   right arrow`, the year changes and text fields and data are removed from current UI. This should be prevented in Calendar but the keyboard shotcut for text should work.

### What is actually happening?
The year is changing and data are removed from the UI.

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17.0.2 |
| System | macOS Monterey 12.1 |
| Browser | Chrome, Firefox |

**Comment by MadCcc** [comment]
Why not `stopPropagation` ?

**Comment by UjjwolKayastha** [comment]
@MadCcc, your suggestion worked. Thanks. 🎉
