### ISSUE TITLE
Radio options and Dropdown option are not responsive if text is more

### ISSUE THREAD

**Issue by natheeshkumar-tw** [ant-design/ant-design#34176]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/the-way-of-hiding-menu-antd-4-18-8-forked-pj4rbu?file=/index.js)

### Steps to reproduce
Just add more than 200 word of text in <Menu.Item>dfghjkjhg....200 lines<Menu.Item>

### What is expected?
Expected 200 word of text in several line one by one.

### What is actually happening?
Actually 200 word of text in several line in one line.

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17 |
| System | Mac |
| Browser | Chrome and all |

Picture reference: [https://stackoverflow.com/questions/71237813/radio-options-and-dropdown-option-are-not-responsive-if-text-is-more-in-antd-des](url)

Stackoverflow link : https://stackoverflow.com/questions/71237813/radio-options-and-dropdown-option-are-not-responsive-if-text-is-more-in-antd-des

**Comment by afc163** [comment]
We don't handle the long one word situation in radio demo by default. But we should fix dropdown item wrapping issue.
