### ISSUE TITLE
树选择搜索时,点击选项外的元素会清空搜索值

### ISSUE THREAD

**Issue by JS-an** [ant-design/ant-design#34170]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sxgp46?file=/test.tsx)

### Steps to reproduce
除点击选项外,点击其他地方会清空搜索值( 包括 Select All 区域 )
![3EE9343F-2FA1-4de8-9145-8049C9354865](https://user-images.githubusercontent.com/25688878/155280650-b0953ec3-8f24-43a1-92cc-8764312c8ff4.png)

### What is expected?
至少点击 dropdownRender 下的区域不会清空搜索值

### What is actually happening?
除点击选项外,点击其他地方会清空搜索值( 包括 Select All 区域 )

| Environment | Info |
|---|---|
| antd | 4.18.3 |
| React | react  |
| System | win10 |
| Browser | 版本 98.0.4758.102（正式版本） （64 位） |

**Comment by MadCcc** [comment]
You can try adding `onMouseDown` to your customized dropdown with `e.preventDefault()` as workaround.

**Comment by JS-an** [comment]
@MadCcc 能解决一部分问题, 但这需要适配每一个 dropdownRender 下的元素

**Comment by zombieJ** [comment]
不会默认处理 preventDefault，因为用户可能就是需要在 dropdownRender 里面做可以获取焦点的元素。如果直接 prevent 掉，就无法获取焦点了。这个不是 bug，特意不拦的。
