### ISSUE TITLE
Allow menu selectedKeys to be of type React.Key

### ISSUE THREAD

**Issue by sdt-jchau** [ant-design/ant-design#34179]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Right now, menu only accepts keys as String.  There are many cases where a number is preferred.  React standard is to use React.Key which is string | number.  Menu should do the same.

### What does the proposed API look like?
Change selectedKeys prop and other keys prop to be of type React.Key

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/22851#issuecomment-609037631
