### ISSUE TITLE
component in Table column render function trigger componentDidMount for every row

### ISSUE THREAD

**Issue by Bulala-liu** [ant-design/ant-design#34186]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-8-forked-phc25x?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-8-forked-phc25x?file=/index.js

### What is expected?
Comp in table column should trigger componentDidMount only once.

### What is actually happening?
comp render for every table row data

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | mac 10.15.4 |
| Browser | chrome 91.0.4472.114 |

**Comment by afc163** [comment]
It is correct hehavior, there are three `<Edit />` components.
