### ISSUE TITLE
DatePicker inside of a Form.List second select causing TypeError date.clone is not a function

### ISSUE THREAD

**Issue by ergomesh** [ant-design/ant-design#34183]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-form-item-antd-4-18-8-forked-n7ldlm)

### Steps to reproduce
select first date then goto second row and select date

### What is expected?
can select second date

### What is actually happening?
TypeError
date.clone is not a function. (In 'date.clone()', 'date.clone' is undefined)

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 18 |
| System | OS X  |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Is your CodeSandbox related to this issue?

**Comment by ergomesh** [comment]
Yes the code sandbox shows a working example of the issue. It is a direct modification of an example of the forms page.

**Comment by afc163** [comment]
https://codesandbox.io/s/dynamic-form-item-antd-4-18-8-forked-fn3bo3?file=/index.js
