### ISSUE TITLE
Select组件mode为multiple并且设置labelInValue，主动添加的key会默认转换为string类型

### ISSUE THREAD

**Issue by 2362446788** [ant-design/ant-design#34192]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/huo-de-xuan-xiang-de-wen-ben-antd-4-18-8-forked-71j7ng?file=/index.js:0-621)

### Steps to reproduce
选中第一个option，然后查看log日志

### What is expected?
key应该和value保持一致

### What is actually happening?
打印出来的结果中key是一个字符串

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | 16.14.0 |
| System | mac |
| Browser | Chrome 版本 98.0.4758.102（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
React 会把 key 内部转化为 string 类型，所以你应该以 value 为准。
