### ISSUE TITLE
menu mode 为vertical模式时，设置openkeys，没有弹出子菜单栏

### ISSUE THREAD

**Issue by juanpengke** [ant-design/ant-design#3419]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:mac 10.16
- 浏览器及其版本:
chrome 53
#### 您做了什么？
menu 设置mode 为vertical模式时，设置openkeys，没有弹出子菜单栏
openkeys 为动态值，可能改变。所以没有用defaultOpenkeys

#### 您期待的结果是：
menu 设置mode 为vertical模式时，设置openkeys，弹出子菜单栏

#### 可重现的在线演示

http://codepen.io/anon/pen/ambwgj?editors=0011

**Comment by afc163** [comment]
对，暂不支持 vertical 菜单的受控模式。

**Comment by afc163** [comment]
如有强烈需求，欢迎直接 PR~
