### ISSUE TITLE
级联选择器的二级或三级中只有一个选项没有被禁用时，选择这个没有被禁用的选项，级联选择器展示的是上一级的内容

### ISSUE THREAD

**Issue by iDestin** [ant-design/ant-design#34193]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-antd-4-18-8-forked-0eb51s?file=/index.js)

### Steps to reproduce
如果一个级联选择器的二级或三级中只有一个选项没有被禁用时，选择这个没有被禁用的选项，级联选择器展示的是上一级的内容，如图
![](https://i.bmp.ovh/imgs/2022/02/a943778b635c2994.png)

图片连接：https://i.bmp.ovh/imgs/2022/02/a943778b635c2994.png

### What is expected?
展示选择的内容，而不是上一级内容

### What is actually happening?
展示的是上一级的内容，不是选中的内容

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 16.14.0 |
| System | MacOS 12.2.1 |
| Browser |  97.0.4692.99（正式版本） (x86_64) |

---
比如省市区三级级联时，一个省只有一个市可以被允许选中时，选择这个市显示的却是省的名称，提交到后端的code也是省的编码，这样会有问题！希望能够解决一下谢谢

**Comment by hanx316** [comment]
i believe this issue is same to https://github.com/ant-design/ant-design/issues/34221, which is bug labeled.

**Comment by zombieJ** [comment]
这个看起来也不对，如果所有子节点只有一个是 disabled，那选中 parent 明显更合理。感觉这一块没有一个特别适合的逻辑。

**Comment by zombieJ** [comment]
可以也搞个 `showCheckedStrategy` 要么全父节点，要么全子节点

**Comment by iven35** [comment]
> 比如省市区三级级联时，一个省只有一个市可以被允许选中时，选择这个市显示的却是省的名称，提交到后端的code也是省的编码，这样会有问题！希望能够解决一下谢谢

但是大佬，在这个场景下会有问题的：比如省市区三级级联时，一个省只有一个市可以被允许选中时（其他的市被禁选了），选择这个市之后，显示的却是省的名称，提交到后端的code也是省的编码，这样对用户来说肯定很费解，对于代码逻辑来说也会有bug

**Comment by iven35** [comment]
> 可以也搞个 `showCheckedStrategy` 要么全父节点，要么全子节点

似乎 @hax316

**Comment by MadCcc** [comment]
建议先自己加点逻辑判断，后续再添加 `showCheckedStrategy` 处理这个 case

**Comment by iven35** [comment]
> 建议先自己加点逻辑判断，后续再添加 `showCheckedStrategy` 处理这个 case

好的，问题暂时得到了 [@hanx316](https://github.com/hanx316) 同学的解决，希望后期官方可以支持一下这个

**Comment by hanx316** [comment]
> 这个看起来也不对，如果所有子节点只有一个是 disabled，那选中 parent 明显更合理。感觉这一块没有一个特别适合的逻辑。

这里其实有两种逻辑，看具体使用场景吧。
一种逻辑是 antd 目前这种：全选无视 disabled，所有可选的子项 checked 以后视为 parent 全选了。另一种是有 disabled 的未选项则其 parent 不可能 allCheked，感觉这种在业务使用上更合理一些，因为 disabled 的选项也有 checked 和 uncheked 两种状态其实。
不过细想一下，其实两种逻辑都能说得通。

目前我们改了下 rc-tree 按第二种逻辑去实现，重新单独编译了一份组件来解决我们的问题。
不过我也认为就像上面说的，加上 `showCheckedStrategy` 可能会更好一些。
加这个 api 的话牵扯到底层 rc-components 的改动，这个可 pr 吗？

**Comment by MadCcc** [comment]
PR welcome~

**Comment by chenxianfei** [comment]
> > 建议先自己加点逻辑判断，后续再添加 `showCheckedStrategy` 处理这个 case
> 
> 好的，问题暂时得到了 [@hanx316](https://github.com/hanx316) 同学的解决，希望后期官方可以支持一下这个

如何解决的

**Comment by iven35** [comment]
> > > 建议先自己加点逻辑判断，后续再添加 `showCheckedStrategy` 处理这个 case
> > 
> > 
> > 好的，问题暂时得到了 [@hanx316](https://github.com/hanx316) 同学的解决，希望后期官方可以支持一下这个
> 
> 如何解决的

我们只是针对有禁用的场景做了处理

**Comment by NotFound403** [comment]
这个全选逻辑是不正常的现在，全选和点击应该是两个概念  全选包含了所有的子节点    点击是从父节点到当前节点为止
