### ISSUE TITLE
there is no more config in ConfigProvider such as Pagination's prop `pageSizeOptions`

### ISSUE THREAD

**Issue by microJ** [ant-design/ant-design#34190]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when i want to set global table `pageSizeOptions` config，i find `ConfigProvider` is not support.

easily, i can make a global component name `MyTable` with `() => <Table pageSizeOptions={props.pageSizeOptions}  children={props.children}/>`. it's work.

however, it's confused about `ConfigProvider` has a prop `pageHeader` that `PageHeader`'s prop. 

so, why there is prop `pageHeader` but not prop `pageSizeOptions` and [so on](https://github.com/ant-design/ant-design/issues/19480)?
is there possible have some customer port to support any antd component props ?

### What does the proposed API look like?
maybe:

```js
<ConfigProvider table={pageSizeOptions: ['50', '100']} popover={mouseEnterDelay:0}>
    <App />
</ConfigProvider>
```

**Comment by afc163** [comment]
It is better to customized your owner Table component based on antd's comoponent.
