### ISSUE TITLE
[Feature Request][TreeSelect]Support `tagRender` prop for non-multiple case.

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#34200]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At now, the `tagRender` only works when `multiple` is `true`, but even `multiple` is `false`, there is still some cases need `tagRender`, like displaying different element after selected.

### What does the proposed API look like?
Keep current behavior, just makes passing `tagRender` works.

`<TreeSelect tagRender={ props => ... } multiple={ false }` />

**Comment by NE-SmallTown** [comment]
@afc163 大哥哥，很急，可以的话我这就提个 PR 冲冲冲

**Comment by afc163** [comment]
单选直接用 TreeNode 里的 title 或者 treeNodeLabelProp 属性应该就行了。

**Comment by NE-SmallTown** [comment]
`title` 貌似不行，因为要下拉的时候和选中之后搜索框里展示的不同。`treeNodeLabelProp` 完美，居然还可以这么弄。。我试了一串骚操作都无疾而终，本来都打算用 Select 组件来做了，然后发现 Select 不支持 Group 的嵌套。

那个..，想问个不相干的哈，https://github.com/ant-design/ant-design/issues/20462 ，这个，目前即便某个父节点的 `selectable` 为 `false` 也只能点 icon 才能展开，没法点文字展开，但是从用户体验来讲其实 `selectable` 为 `false` 的时候点文字也可以展开会比较虚服


这个我试了骚操作 * 20 貌似没办法解决。。可以的话我试着提个 PR 哈，谢谢大哥! @afc163

**Comment by afc163** [comment]
你可能需要的是 https://ant.design/components/tree-cn/#components-tree-demo-directory

**Comment by NE-SmallTown** [comment]
因为想要的限制用户只能选择 TreeSelect 的最深的那一级的节点，所以目前是把非最后一级的节点的 `selectable` 设置为 `false` 来实现，但是这样会有上面说的非最后一级的节点必须点 icon 才能展开的问题，体验不是那么那么完美，因为本身 `selectable` 为 `false` 说明这个节点无法被选中了，所以不会出现  https://github.com/ant-design/ant-design/issues/20462 里面的「交互不统一」的问题，因为在这种场景下，点击文字也可以展开对用户比较友好，也不会存在误导


https://ant.design/components/tree-cn/#components-tree-demo-directory 这个的话，是用这个配合 TreeSelect 的 `dropdownRender` 嘛？（单独只用 Tree 或者 Tree + Select 的话可能不太适合需求，还是希望是 TreeSelect 那样的），感觉会有点麻烦，样式上也和 TreeSelect 不太统一 😂，因为我们目前是一个页面里用多个 TreeSelect，多选的时候是 TreeSelect，单选的时候换成这种话用户可能会觉得有点点奇怪，因为对他来说都是 select，怎么一会长这样一会长那样交互也不太统一 @afc163

**Comment by NE-SmallTown** [comment]
@afc163    大佬，上一条说的这个可以嘛，我的 PR 已经按耐不住了！

**Comment by yoyo837** [comment]
先提上来看看呗

**Comment by afc163** [comment]
`selectable={false}` 和点击文本展开是两个行为，不建议混在一起。

TreeSelect 的行为是选择，点击节点文本展开会导致父节点无法选中，只有叶子节点是可选的，这个和 TreeSelect 的本义不太一致。

**Comment by NE-SmallTown** [comment]
@afc163  行为上来说，的确是两个行为，从逻辑或者代码的角度来看可能关联不大，但是从交互和用户体验的角度来看，它们确实是紧密联系的。。

能让我和美丽的 UX 姐姐谈一下吗，我觉得她一定会支持这样的交互！（不支持我也一定能说服她）不然太反人类啦。另外主要是目前没有任何的方式能够自己实现这样的需求，因为 `selectable` 为 `false` 时没法监听点击父节点，也不会触发任何事件，总不能根据 class 去监听 DOM 元素呀，害怕

**Comment by NE-SmallTown** [comment]
@afc163 可以嘛，这个功能真的炒鸡有意义！（不然需求实现不了下午茶都跑路啦，哭泣

**Comment by NE-SmallTown** [comment]
@afc163     带头大哥😭😭

**Comment by afc163** [comment]
@NE-SmallTown 看看你的真实业务需求是啥样的？

**Comment by NE-SmallTown** [comment]
@afc163    就是真实的业务场景 😭

页面里有两个表单项，比如一个是填品类，一个是填分类，后端传过来一个树结构的 JSON，然后前端展示给运营选，但是这里有个业务或者说运营提出的要求，就是只允许选择最后一级分类，比如 JSON 里是 

```js
{ 
  value: 'foo',  
  children: [ 
    { value: 'bar', children: [] },
    { value: 'baz', children: [] }
 ] 
}
```


现在希望点击 `foo`  的文字的时候能够展开，以便运营能够看到 `bar` 和 `baz` 以及他们属于哪个父级从而进行选择

但是并不希望或者本身逻辑上就不允许选择 `foo`，而是只允许选择 `bar` 和 `baz` 

所以目前是把 `foo` 的 `selectable` 设置为 `false` 来避免他们选择到 `foo`，但是这样一来他们在选择的时候，只能点左边的小 icon 来展开，操作次数多了之后真的很暴躁。。。因为 `foo` 本身不可选，但是这里又是一个展示树形结构的 UI，每一行里 icon 只占 5 px，而文字占 50px，所以每次操作时都得通过点击一行里宽度不到 10% 的那么一个小小区域去达到展开的效果，但是在他们眼里这一行本身就是一个整体（因为这一行本身除了展开并不具备其它任何功能），所以从运营或者普通用户的视角来看，确实很不合理很容易拉血压。。

**Comment by afc163** [comment]
`selectable: false` 配合一个 `titleExpandable: true`，这个我能接受。

**Comment by NE-SmallTown** [comment]
@afc163    no problem！ 我争取明天就搞下提个 PR，谢谢大大大哥

**Comment by NE-SmallTown** [comment]
see https://github.com/react-component/tree/pull/542

**Comment by NE-SmallTown** [comment]
大哥，PR is ready  @afc163

**Comment by NE-SmallTown** [comment]
https://github.com/react-component/tree/pull/542#issuecomment-1081776736

@afc163    大哥哥，看看，球球了 😭
