### ISSUE TITLE
Tooltips for disabled text buttons stay visible after moving mouse

### ISSUE THREAD

**Issue by mtadams007** [ant-design/ant-design#34202]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mtadams007/pen/mdqjXwR](https://codepen.io/mtadams007/pen/mdqjXwR)

### Steps to reproduce
Add a tooltip to a disabled text button. Hover over the text button and then move the cursor off of the button. The tooltip lingers and remains visible.

### What is expected?
I would expect the tooltip to disappear after moving the cursor. The behavior should be the same whether the button is enabled or disabled.

### What is actually happening?
For disabled text buttons the tooltip does not disappear right away. For enabled text buttons it disappears almost immediately.

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17.0.0 |
| System | Ubuntu |
| Browser | Chrome |

---
I have an application where I would like to have a tooltip that lets the user know why a button is disabled. This is annoying where the tooltip does not disappear.
![tooltipForAntD](https://user-images.githubusercontent.com/36059111/155573235-c0493f87-eb84-4622-a8ce-40698f9f5f25.gif)

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/1816

**Comment by mtadams007** [comment]
@xrkffgg , the linked ticket is closed. Is there any action that will be taken on this bug?

**Comment by kanweiwei** [comment]
@xrkffgg  Sorry, it's not a bug. I regard it as an imposition. You should tell  to the `tootip` about the states of its children. If you want the tooltip be invisible, maybe you shoud't use tooltip. You shoud do like this code:
```javascript
if(disabled) {
 return <Button disabled={disabled}>xxx</Button>
}
return (
 <Tooltip title="xxx">
   <Button>xxx</Button>
</Tooltip>
)
```

**Comment by kanweiwei** [comment]
https://github.com/facebook/react/issues/4251

**Comment by kanweiwei** [comment]
https://codesandbox.io/s/stupefied-microservice-jizt49?file=/src/App.js

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/1816

**Comment by uazure** [comment]
I have a workaround. Idea is to wrap button in a container that intercepts all mouse events, so that mousein and mouseout events are not blocked for disabled button.

Example:
```
<Tooltip title="This feature is disabled">
  <div style={{position: 'relative', display: 'inline-block', cursor: 'not-allowed'}}>
    <div style={{ position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, zIndex: 1}} />
    <Button disabled>text</Button>
  </div>
</Tooltip>
```

**Comment by anjantalatam** [comment]
Here is a workaround

```JSX
<Tooltip title={!disabled ? "Tooltip" : null}> 
    <Button
         type="primary"
         disabled={disabled}
     >
         Tooltip Button
     </Button>
</Tooltip>
```

[Open in Codesandbox](https://codesandbox.io/s/antd-tooltip-on-disabled-button-tg2mk7?file=/demo.tsx:219-478)

**Comment by zeelmodi-simform** [comment]
@anjantalatam Thanks for a workaround!

**Comment by ArtemKurtiak** [comment]
You can just wrap button into div:
```
<Tooltip title={disabled ? null : "Tooltip"}> 
    <div>
         <Button
             type="primary"
             disabled={disabled}
         >
             Tooltip Button
         </Button>
    </div>
</Tooltip>
```

**Comment by saumyaborwankar** [comment]
> Here is a workaround
> 
> ```js
> <Tooltip title={!disabled ? "Tooltip" : null}> 
>     <Button
>          type="primary"
>          disabled={disabled}
>      >
>          Tooltip Button
>      </Button>
> </Tooltip>
> ```
> 
> [Open in Codesandbox](https://codesandbox.io/s/antd-tooltip-on-disabled-button-tg2mk7?file=/demo.tsx:219-478)

Unfortunately this messes up the spacing if there was just a button without a tooltip. Anyone who what might be the issue
