### ISSUE TITLE
使用useState定义变量columns,赋值于ant-table的columns参数，当使用align、fixed时，ts类型报错

### ISSUE THREAD

**Issue by MirUac1e** [ant-design/ant-design#34207]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-szp2f3?file=/index.tsx)

### Steps to reproduce
sandbo内能直接看到类型报错
但不影响使用

### What is expected?
1:此类（align，fixed等）不报错
2：官方ant-table的文档中columns的fixed参数的类型写的是boolean | string
但在源码中引用文件的FixedType是"left" | "right" | boolean  ，修复文档

### What is actually happening?
ts类型报错
官方文档写的类型有歧义

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | macOS Monterey 12.1 |
| Browser | Chrome 98.0.4758.102（正式版本） (arm64) |

---
官方ant-table的文档中columns的fixed参数的类型写的是boolean | string
但在源码中引用文件的FixedType是"left" | "right" | boolean

**Comment by afc163** [comment]
`align: "center" as const` 这样就行了。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33328#issuecomment-996403917

**Comment by MirUac1e** [comment]
> [#33328 (comment)](https://github.com/ant-design/ant-design/issues/33328#issuecomment-996403917)

请问，能不能说明一下为什么使用useState的时候就会出现这种情况，以后的版本会修复吗？

**Comment by wangcch** [comment]
@MirUac1e 感觉这种情况不是应该申明类型么？

```ts
import type { ColumnsType } from 'antd';

const [columns, setColumns] = useState<ColumnsType<T>>([]);
```

**Comment by MirUac1e** [comment]
@wangcch 确实..之前没+申明类型 看他会自动获取就以为是获取到正确了的

**Comment by ChenKun1997** [comment]
> @MirUac1e 感觉这种情况不是应该申明类型么？
> 
> ```ts
> import type { ColumnsType } from 'antd';
> 
> const [columns, setColumns] = useState<ColumnsType<T>>([]);
> ```

我看上他的codeSandBox不是显示没有到处这个类型吗
![image](https://user-images.githubusercontent.com/24249578/156113512-c905b978-898b-4736-94f5-db6e9c0f333f.png)

**Comment by MirUac1e** [comment]
@ChenKun1997 `import type {ColumnsType} from 'antd/es/table'`
这个是文档上的路径
可能是他回复的时候写错了 但是道理还是那个道理 所以我就没指出来

**Comment by wangcch** [comment]
> @ChenKun1997 `import type {ColumnsType} from 'antd/es/table'` 这个是文档上的路径 可能是他回复的时候写错了 但是道理还是那个道理 所以我就没指出来

抱歉, 我更新一下
antd 对外直接暴露的应该是 `TableColumnsType` or `TableColumnType`[]

**Comment by MirUac1e** [comment]
> > @ChenKun1997 `import type {ColumnsType} from 'antd/es/table'` 这个是文档上的路径 可能是他回复的时候写错了 但是道理还是那个道理 所以我就没指出来
> 
> 抱歉, 我更新一下 antd 对外直接暴露的应该是 `TableColumnsType` or `TableColumnType`[]

sandbox里好像拿不到这个值 在项目里面可以指向到 ant/lib/table里面的ColumnsType 
总之我这个问题应该就是没有给正确的类型给他
并且useState自动获取的类型 不太对 
对吧？

**Comment by ChenKun1997** [comment]
@wangcch ok明白了，

> 

上面大佬不是说用as const吗，不使用as const 的话TS默认推断为string类型,使用as const的话类型就是“center”类型，使用内部定义好的类型也可以解决，应该都可以

**Comment by MirUac1e** [comment]
> @wangcch
> 
> > 
> 
> 上面大佬不是说用as const吗，不使用as const 的话TS默认推断为string类型,使用as const的话类型就是“center”类型，使用内部定义好的类型也可以解决，应该都可以

明白了 谢谢～

**Comment by afc163** [comment]
先关了，目前可以用这两种方式来解决，如果有更好的 TS 写法也可以来给 antd PR。

**Comment by wangcch** [comment]
@MirUac1e 
是的, 没有申明类型前. `align` 默认合并为`string` 类型, 无法适配 `align` 的枚举值. 
`string` 可以向上兼容 `align` 的string枚举值, 但是`align` 不可以项下兼容 `string`类型.
具体上面问题, 解决方法也都是 处理`align`类型匹配问题. 都可以

**Comment by MirUac1e** [comment]
@wangcch 明白～谢谢～
