### ISSUE TITLE
寻Table组件悬浮层编辑的案例

### ISSUE THREAD

**Issue by yhhwpp** [ant-design/ant-design#3420]
最近在搞复杂的table 需要 点击单元格 悬浮层编辑 有没有相应的案例。支持text radio checkbox 等

**Comment by yesmeck** [comment]
悬浮层编辑是什么意思？

**Comment by whx76** [comment]
#1449
https://github.com/ant-design/ant-design/pull/1449/files

**Comment by benjycui** [comment]
Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
