### ISSUE TITLE
antd form.list 内部组件getFieldValue 无法正确触发校验以及加上requireMask

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/ant-design#34218]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-zeng-jian-qian-tao-zi-duan-antd-4-18-8-forked-j7q10o?file=/index.js)

### Steps to reproduce
1.在表单外的上方的getFiledValue是生效的，选中true，b相关的rules会变为必填

2.在form,list里面先增加add filed，再选中true，后方的input未生效规则必填

### What is expected?
希望form，list的效果跟表单外的一直，选中true会使得后续的依赖也变为必填加上requiredmask

### What is actually happening?
未生效规则，也没加上requiredmask

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 16.9 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
See https://codesandbox.io/s/dong-tai-zeng-jian-qian-tao-zi-duan-antd-4-18-8-forked-jrqune?file=/index.js
