### ISSUE TITLE
Table组件，小屏情况下，表格内容和表头会超出外层包裹

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#34210]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

<img width="854" alt="image" src="https://user-images.githubusercontent.com/8169783/155684147-4c0ac9fe-9479-41f2-a193-0d2f1d841968.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/8169783/155684317-cd9e79df-e4b5-46ec-8627-107591bbc9d0.png">

### Steps to reproduce
打开官方文档，将浏览器拉小一些，900px 左右即可复现，然后从上往下看，有些Table内容是溢出的

### What is expected?
期望表格内容始终在外框内，及时溢出并出滚动条了

### What is actually happening?
实际结果是有些情况下表格内容飘出去了

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17.0.2 |
| System | masOS Monterey 12.1 |
| Browser | 98.0.4758.80 |

**Comment by afc163** [comment]
这种情况需要单独设置 scroll.x 以支持横向滚动。默认的表格确实会溢出。

**Comment by rawbin-** [comment]
为什么不默认滚动呢，https://procomponents.ant.design/components/table/?current=1&pageSize=5
ProTable 全页面基本都没加 scroll.x
