### ISSUE TITLE
Handling ConfigProvider Theme for SSR

### ISSUE THREAD

**Issue by wuifdesign** [ant-design/ant-design#34217]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What is expected?

Also add the config property to the `ConfigProvider` to render on SSR instead of using `updateCSS`. 

Maybe something like this:

```js
const ConfigProvider: React.FC<ConfigProviderProps> & {
  ConfigContext: typeof ConfigContext;
  SizeContext: typeof SizeContext;
  config: typeof setGlobalConfig;
} = props => {
  React.useEffect(() => {
    if (props.direction) {
      message.config({
        rtl: props.direction === 'rtl',
      });
      notification.config({
        rtl: props.direction === 'rtl',
      });
    }
  }, [props.direction]);
  
  // getThemeVariables() -> return ':root { --primary-color: #00a; ... }
  const variables = props.config.theme ? getThemeVariables(getGlobalPrefixCls(), props.theme) : null

  return (
    <>
      {variables && <style>{variables}</style>}
      <LocaleReceiver>
        {(_, __, legacyLocale) => (
          <ConfigConsumer>
            {context => (
              <ProviderChildren
                parentContext={context}
                legacyLocale={legacyLocale as Locale}
                {...props}
              />
            )}
          </ConfigConsumer>
        )}
      </LocaleReceiver>
    </>
  );
};
```

If this is not possible, at least export a function where we can get the colors object created in `./components/config-provider/cssVariables.tsx` to manually add it to the code on SSR.

https://github.com/ant-design/ant-design/blob/5903f4072457a6375ac43a17fbe01877e20fdaf7/components/config-provider/cssVariables.tsx#L87-L89

### What is actually happening?

Cant use it and on SSR the colors will not be added.

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17 |
| System | Mac OS |
| Browser | - |

Connected to issue: https://github.com/ant-design/ant-design/issues/34100

**Comment by zombieJ** [comment]
@wuifdesign Let me export the calculation func. Since we want to move to cssinjs in v5, this func will not doc i  official site but you can safe to use in v4.

ref #34436
