### ISSUE TITLE
菜单menu组件的onOpenChange接口是哪个版本添加的

### ISSUE THREAD

**Issue by mickeyzhou** [ant-design/ant-design#3422]
我在npm包1.11.2里使用，感觉没有这个接口

**Comment by bo2337285** [comment]
同找不到,翻了源码发现只有onOpen,然后返回参数是一个对象,里面就有openKeys,估计是官方文档没有更新

**Comment by afc163** [comment]
https://ant.design/changelog#2.x-不兼容改动

别这样问问题啊，翻翻 changelog 就能找到的信息。
