### ISSUE TITLE
TreeSelect TreeSelect.SHOW_CHILD模式能否不选择最外层父级的值 

### ISSUE THREAD

**Issue by woshichenxu2016** [ant-design/ant-design#34221]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-o6jr7t?file=/index.js)

### Steps to reproduce
在sandbox中选中 Child Child Node1 和 Child Child Node2 两个子项

### What is expected?
在sandbox中选中 Child Child Node1 和 Child Child Node2 两个子项后，  Child Child Node1  和  Child Child Node2 父级的父级的值Node1 不被选中

### What is actually happening?
在sandbox中选中 Child Child Node1 和 Child Child Node2 两个子项后，  Child Child Node1  和  Child Child Node2 父级的父级的值Node1也被选中。

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome/98.0.4758.102 |

**Comment by MadCcc** [comment]
https://github.com/react-component/tree-select/pull/395/files
这个 PR 后出现的问题
