### ISSUE TITLE
select showSearch如果传入defaultValue ios 手机端则不会唤起软键盘

### ISSUE THREAD

**Issue by zhangyu0218** [ant-design/ant-design#34239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-glitter-pr9hos?file=/index.js)

### Steps to reproduce
直接在苹果手机上打开链接就会复现

### What is expected?
可以唤起软键盘

### What is actually happening?
没有唤起软键盘

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 17.0.1 |
| System | 15.1 |
| Browser | safari |

---
安卓浏览器可以唤起软键盘

**Comment by yoyo837** [comment]
Duplicate of #34238
