### ISSUE TITLE
select showSearch如果传入defaultValue ios 手机端则不会唤起软键盘

### ISSUE THREAD

**Issue by zhangyu0218** [ant-design/ant-design#34238]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-glitter-pr9hos)

### Steps to reproduce
直接在苹果手机上打开链接就会复现

### What is expected?
可以唤起软键盘

### What is actually happening?
没有唤起软键盘

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 17.0.1 |
| System | 15.1 |
| Browser | safari |

---
安卓浏览器可以唤起软键盘

**Comment by zhangyu0218** [comment]
是4.5.1

**Comment by afc163** [comment]
预期行为是进页面就会直接唤起软键盘么，还是要点一下才唤起软键盘？

**Comment by afc163** [comment]
有没有录屏什么的，看看核心区别是啥

**Comment by afc163** [comment]
是否和 https://github.com/ant-design/ant-design/issues/25482 描述的问题是一样的？

**Comment by zhangyu0218** [comment]
和 #25482 不是一个问题
![WechatIMG1336](https://user-images.githubusercontent.com/33249149/156116303-074355f9-bb4e-474e-966f-cf246f389283.jpeg)
我这里有个截屏，当设置defaultValue 时 你可以发现当我点击输入框的时候 手机上的软键盘没有被唤起  这个问题只发生在ios上 安卓机上是可以唤起软键盘的

**Comment by afc163** [comment]
和 https://github.com/ant-design/ant-design/issues/25482 所描述的问题区别在哪，看上去是一样的。

**Comment by afc163** [comment]
我测了一下，最新版本已经不存在这个问题了：https://codesandbox.io/s/stoic-frost-1z4on5?file=/package.json

![图片](https://user-images.githubusercontent.com/507615/200217906-18d1dfb4-ccb1-4638-81a9-8781641fd809.png)
