### ISSUE TITLE
Warning: `columns.render` return cell props is deprecated with perf issue, please use `onCell` instead.sb?

### ISSUE THREAD

**Issue by axiaorong** [ant-design/ant-design#34241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
sb?

### What is expected?
sb?

### What is actually happening?
sb?

| Environment | Info |
|---|---|
| antd | undefined |
| React | sb? |
| System | sb? |
| Browser | sb? |

**Comment by MadCcc** [comment]
Any problems?
