### ISSUE TITLE
Documentation typescript examples

### ISSUE THREAD

**Issue by sarpere** [ant-design/ant-design#34245]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Better understanding of what are the types of the elements, functions and variables.

### What does the proposed API look like?
There need to be a switch that allow to toggle js to ts example.

Here is an example image:

<img width="822" alt="Screen Shot 2022-03-01 at 12 59 02" src="https://user-images.githubusercontent.com/29937197/156147623-c657ee27-61ae-4bf2-98fe-f53139c15fc0.png">

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-row-selection

<img width="1128" alt="图片" src="https://user-images.githubusercontent.com/507615/156159240-c3e7396d-b1fb-4dff-9d56-392667949980.png">

We support using TypeScript to write demo and show tabs in demo card. Welcome to give us PR rewriting demo from JavaScript to TypeScript~
