### ISSUE TITLE
RangePicker怎么获取当前面板展开的是开始时间还是结束时间

### ISSUE THREAD

**Issue by zhangguimei** [ant-design/ant-design#34259]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
disabledDate判断中，开始时间结束时间的禁业务不一样，需要知道当前面板是在开始时间还是结束时间

### What does the proposed API look like?
提供当前激活的是开始时间还是结束时间方法；
onActivePickerIndexChange?:(type?: 'start', 'end') => void;

**Comment by zhangguimei** [comment]
或者能够在disabledDate中增加参数，是开始时间还是结束时间的面板

**Comment by afc163** [comment]
和 onCalendarChange 配合 https://ant.design/components/date-picker-cn/#components-date-picker-demo-select-in-range

**Comment by a747097587** [comment]
> @afc163 展开面板、切换开始结束时间，不会触发onCalendarChange

我也遇到了这个问题，请问一下，你后面是怎么解决的
