### ISSUE TITLE
Image component preview overrides global `body` width

### ISSUE THREAD

**Issue by saberworks** [ant-design/ant-design#34250]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-n6ecg6?file=/index.js)

### Steps to reproduce
Use css to set your body width to `120ch;`  Include an Image with preview.  Include enough content on the page so that a vertical scroll bar exists on the right hand side.  When click the image, the entire body stretches out from `120ch` to `100%-12px` (basically from a column in the center to almost full-width).  It's very jarring when preview an image and behind the darkened shade you can see the whole page get wider.

### What is expected?
The body behind the image preview stays the same, and does not stretch.

### What is actually happening?
The body stretches out from `120ch` to `100%-12px`

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Firefox 97 |

---
To repro this you must have enough content on the page to create a vertical scroll bar.  When the content is not long enough to have a scroll bar, the `body` width is not modified.

![body_with_image_preview_open](https://user-images.githubusercontent.com/584773/156256138-ba58f1c8-94df-4910-b5f7-5f6c5db17c2e.png)
![body_default](https://user-images.githubusercontent.com/584773/156256141-3f16e12f-f1f2-414c-aae0-f162e9906b63.png)

**Comment by saberworks** [comment]
Here is a video showing the problem.  Notice that once the vertical scrollbar is introduced, the body behind the image preview grows to full width when image is clicked.

https://forums.massassi.net/cinnamon-20220301-2.webm

**Comment by afc163** [comment]
It is better to add width in #root instead of document.body IMO: https://codesandbox.io/s/antd-reproduction-template-forked-iswntw

**Comment by saberworks** [comment]
That seems to be working perfectly, thank you!
