### ISSUE TITLE
集成到qt中的iconfont斜体问题

### ISSUE THREAD

**Issue by imkiven** [ant-design/ant-design#3425]
#### 发生问题的环境是：

- antd 版本: 所有版本都试过
- 操作系统及其版本:所有操作系统
- 浏览器及其版本:qtwebkit内核

#### 您做了什么？
将antd开发的网页集成在qt开发的exe中，即在qt开发的exe中，使用qtwebkit打开使用antd开发的网页，所有图标都是斜体的。

#### 您期待的结果是：

图标正常显示

#### 实际上的结果是：

图标是斜体的

#### 可重现的在线演示
无

**Comment by benjycui** [comment]
不排除和环境的默认样式影响了，尝试用高优先级的规则设置 Icon 的样式。

**Comment by imkiven** [comment]
@benjycui 你好，我加了font-family:"iconfont" !important;没用，是设置的方式不对吗

**Comment by imkiven** [comment]
@benjycui 使用其他字体放置在qt中没有倾斜的情况，有没有方法可以替换antd的字体

**Comment by afc163** [comment]
try style `i.anticon { font-style: normal !important; }`

**Comment by imkiven** [comment]
@benjycui @afc163 不知道是不是优先级的问题，使用了行内style="font-style: normal !important;" 也是倾斜的

**Comment by benjycui** [comment]
试下这个 https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

毕竟不是 `antd` 考虑的平台，就要麻烦你自己折腾了，找到解决方案可以 post 到这里。

先关了。

**Comment by afc163** [comment]
优先对比下其他字体和 antd 字体有什么不同的设置。
