### ISSUE TITLE
modal嵌套会有一些问题，当关闭内部modal时，外部modal会出现重新打开的动画

### ISSUE THREAD

**Issue by minzhang2** [ant-design/ant-design#3426]
当在modal1中打开modal2，当关闭modal2时，modal1会出现重新打开的动画，给人体验不是很好

- antd 版本:
- 操作系统及其版本:window
- 浏览器及其版本:chrome

![image](https://cloud.githubusercontent.com/assets/15793061/19373091/e088ddb4-91f3-11e6-8ad3-564d4c0e1ab3.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by minzhang2** [comment]
用的dva的脚手架，在modal里面用了tree的组件，每次勾选树时，更新树的checkedKeys时树进行勾选渲染时，modal会重新打开
![a](https://cloud.githubusercontent.com/assets/15793061/19463595/fe260266-9527-11e6-844c-777874a2ca7d.gif)
![image](https://cloud.githubusercontent.com/assets/15793061/19463985/115963de-952b-11e6-9c25-3885ad5bb795.png)
![image](https://cloud.githubusercontent.com/assets/15793061/19463994/31d9eda4-952b-11e6-86bd-e2d8adfc4542.png)
![image](https://cloud.githubusercontent.com/assets/15793061/19464004/42ffae66-952b-11e6-9c12-972b075cccf7.png)

**Comment by minzhang2** [comment]
找到问题的原因了，dva官方提供的例子说表单要这么处理，然后每次修改modal的state就会导致modal重新打开
![image](https://cloud.githubusercontent.com/assets/15793061/19467096/e2888fbe-9541-11e6-8ef1-d9cc0ce708b8.png)

**Comment by benjycui** [comment]
@minzhang2 最好能把链接帖上来，方便后面的人看相关的代码，谢谢。

**Comment by huyansheng3** [comment]
我也有了这个问题，但是解决办法没有看的特别懂，方便讲讲？ @minzhang2 
创建一个全新的组件不是特别懂。。。。

**Comment by minzhang2** [comment]
@huyansheng3 你是用的user-dashboard里面的代码改造的么，
![image](https://cloud.githubusercontent.com/assets/15793061/23786811/f7d6fa62-05a9-11e7-8466-8381bf06574b.png)

**Comment by huyansheng3** [comment]
@minzhang2 已解决，是我自己犯傻了，给 modal 设置 key = {guid()}，每次修改 modal 的 state 会导致重新打开，因为每次生成了新的 modal
