### ISSUE TITLE
form的受控写法，切换的时候，cascader报错

### ISSUE THREAD

**Issue by lth707** [ant-design/ant-design#34268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-18-9-forked-sg5mg2?file=/index.js)

### Steps to reproduce
进入页面切换这个姓名的选项，页面报错

### What is expected?
切换不应该报错

### What is actually happening?
页面报错

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | ^16.14.0 |
| System | Mac |
| Browser | 最新chrome |

---
可能是切换瞬间的form的value还是上一次的值，导致cascader渲染报错

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/156487521-7ae0a7d4-fecb-4581-968b-8805342a8043.png)
看上去 Form 的更新慢一步

**Comment by MadCcc** [comment]
可以先试试 `form` 和 `setFieldsValue` 受控，文档中 `fields` 受控的用法时不推荐的

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/28212

**Comment by HankWang1999** [comment]
> 可以先试试 `form` 和 `setFieldsValue` 受控，文档中 `fields` 受控的用法时不推荐的
你好，想问一下，如果表单受控在我们的业务场景下是需要的，那么是否可以用fields、onFieldsChange这一对api去实现呢？
