### ISSUE TITLE
Form.Item组件中的getValueProps创建的属性对象会缓存，不会实时更新

### ISSUE THREAD

**Issue by sunWoodsen** [ant-design/ant-design#34265]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-b01x3c?file=/index.js)

### Steps to reproduce
输入内容时，suffix属性获取input当前值不生效

### What is expected?
期望能随依赖值动态变化而变化

### What is actually happening?
实际一直保持初始化状态

| Environment | Info |
|---|---|
| antd | 4.16.2 |
| React | 16.14.0 |
| System | macOS 10.15.7 |
| Browser | Google Chrome 89.0.4389.90 (正式版本) (x86_64) |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-2mdqj4?file=/FormTest.jsx

这个场景应该用 shouldUpdate，为了性能，默认是不会 rerender 的。

**Comment by cielu** [comment]
@afc163  我打印了一下，shouldUpdate ,发现里面不执行了，是不是更新出了bug了。。。

```
              <Form.Item
                noStyle
                shouldUpdate={(prevValues, currentValues) => {
                  console.log("dsafwjdoisafjodisajf")
                  return prevValues.failedRetry !== currentValues.failedRetry
                }}
              >
```

**Comment by John251314** [comment]
同问，的确没有执行，getValueProps有执行，但是UI没有变化
