### ISSUE TITLE
TextArea repeat

### ISSUE THREAD

**Issue by xiaosu12138** [ant-design/ant-design#34264]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-wdd8xb?file=index.js](https://stackblitz.com/edit/react-wdd8xb?file=index.js)

### Steps to reproduce
在设置了 autoSize 属性后 TextArea 重复了，且 html 中使用 CSP 后（http-equiv="Content-Security-Policy"）界面上有两个文本域
![image](https://user-images.githubusercontent.com/42687259/156338412-97f1fb23-18ba-4ad6-91a7-a35567f327ca.png)

### What is expected?
多出来的 TextArea 对用户不可见

### What is actually happening?
出现两个 TextArea

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | ^17.0.2 |
| System | macOS Catalina 10.15.5 |
| Browser | Chrome Version: 98.0.4758.109 |

**Comment by afc163** [comment]
```
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; font-src 'self' data:; script-src 'self' 'sha256-{HASHED_INLINE_SCRIPT}' 'unsafe-eval';base-uri 'none'"
    />
```

这行代码会导致 style 标签失效，所有的样式都无法加载，需要你自行排查和解决了。
