### ISSUE TITLE
form 输入组件 错误提示消失时抖动

### ISSUE THREAD

**Issue by psybor** [ant-design/ant-design#34267]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jkt8qe)

### Steps to reproduce
1. 输入文字
2. 删除文字
3. 快速删除与输入重复

### What is expected?
不抖动

### What is actually happening?
抖动

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 16.14.0 |
| System | win 10 |
| Browser | chrome 98.0.4758.102 |

---
首先说明，这个问题被提出了很多次，被随意关闭了很多次，可能也修复了很多次，但是到目前还是有问题。

当错误提示出现时，.ant-form-item 设置的 transition 被 .ant-form-item-with-help 设置的 transition: none; 覆盖，这时不会抖动。
当错误提示消失时，.ant-form-item 设置的 transition: margin-bottom 与 错误提示上 .ant-show-help 设置的 transition 互相抵消。
理想情况下，transition 都是 0.3s linear ，可以完美的衔接，但是，实际情况却会出现抖动。

**Comment by psybor** [comment]
![错误提示消失时抖动](https://user-images.githubusercontent.com/74579438/156368533-78199db5-b613-4e99-929c-6bd742aa1102.gif)

**Comment by afc163** [comment]
看上去 https://github.com/ant-design/ant-design/pull/33644 还没有修好，#34233 有个 fix 看看能不能解决。

**Comment by psybor** [comment]
> 看上去 #33644 还没有修好，#34233 有个 fix 看看能不能解决。

是能解决我这个问题（因为他取消了错误提示的动画），但是好像引入了新的问题：https://github.com/ant-design/ant-design/pull/34233#issuecomment-1053808722

**Comment by beeant** [comment]
I just noticed this issue too!

**Comment by bharatn** [comment]
I see it too even with latest version. Any update on this fix?

**Comment by zhenzhenChange** [comment]
same issue

**Comment by laosandegudai** [comment]
暂时这样处理掉了。
![L{33X@3KA 7@T@7X6ILB`SA](https://user-images.githubusercontent.com/17979159/183414629-63cf053a-568f-4a62-8648-b4c56bbbfab7.png)

**Comment by laosandegudai** [comment]
> 各位看看最新版本 antd 是否已经修复。

我的问题是，处罚验证错误时，两个item会紧贴在一起，查看后发现ant-form-item-with-help  把ant-form-item 的margin-bottom重置为0了，但是我看沙盒的案例是没问题的。

**Comment by afc163** [comment]
@laosandegudai 升级一下最新版本再试呢。

**Comment by laosandegudai** [comment]
> @laosandegudai 升级一下最新版本再试呢。

就是最新版本，但是是react17,沙盒的例子是react18的。

**Comment by afc163** [comment]
看下 rc-overflow 的版本，是否是 1.2.8

**Comment by laosandegudai** [comment]
> 看下 rc-overflow 的版本，是否是 1.2.8

是的。

**Comment by afc163** [comment]
@laosandegudai 能给个重现么

**Comment by laosandegudai** [comment]
> @laosandegudai 能给个重现么

我用最新的antpro 初始化了一个干净的例子木有出现我的问题，可能是我的问题，我在仔细查找下我的环境。

**Comment by Joyeuxman** [comment]
有什么解决方案吗？

**Comment by Joyeuxman** [comment]
> > 各位看看最新版本 antd 是否已经修复。
> 
> 
> 
> 我的问题是，处罚验证错误时，两个item会紧贴在一起，查看后发现ant-form-item-with-help  把ant-form-item 的margin-bottom重置为0了，但是我看沙盒的案例是没问题的。

我也出现了该问题

**Comment by laosandegudai** [comment]
> > > 各位看看最新版本 antd 是否已经修复。
> > 
> > 
> > 我的问题是，处罚验证错误时，两个item会紧贴在一起，查看后发现ant-form-item-with-help  把ant-form-item 的margin-bottom重置为0了，但是我看沙盒的案例是没问题的。
> 
> 我也出现了该问题

使用css覆盖。

**Comment by Joyeuxman** [comment]
> > > > 各位看看最新版本 antd 是否已经修复。
> 
> > > 
> 
> > > 
> 
> > > 我的问题是，处罚验证错误时，两个item会紧贴在一起，查看后发现ant-form-item-with-help  把ant-form-item 的margin-bottom重置为0了，但是我看沙盒的案例是没问题的。
> 
> > 
> 
> > 我也出现了该问题
> 
> 
> 
> 使用css覆盖。

我使用如下方式，会存在闪动

// 添加会闪动
    .ant-form-item.ant-form-item-has-success.ant-form-item-with-help{
      margin-bottom: 24px;
    }

**Comment by laosandegudai** [comment]
不是这个，是  ` .ant-form-item-has-error`

**Comment by Joyeuxman** [comment]
> 不是这个，是 ` .ant-form-item-has-error`

![image](https://user-images.githubusercontent.com/21262781/186367176-581a0a5a-fc27-438e-9933-1bc398cc0980.png)
你看，我这个是同时出现了.ant-form-item-has-error .ant-form-item-with-help 两个类型

**Comment by laosandegudai** [comment]
你截图这个怎么会都正常，按道理会有个不起作用，看盒子模型里面到底是哪个最后起作用了。

**Comment by Joyeuxman** [comment]
> 你截图这个怎么会都正常，按道理会有个不起作用，看盒子模型里面到底是哪个最后起作用了。

我在bug 28542找到了同样的问题
margin-bottom:0起作用了

**Comment by afc163** [comment]
@psybor 看看最新 antd 版本是否已经解决了这个问题？

**Comment by ceyhanbekiroglu** [comment]
Change the min-height on ".ant-form-item-control-input" from 34px to 35px. It solved my issue.

**Comment by afc163** [comment]
各位这个问题帮忙看看是否还存在

**Comment by psybor** [comment]
> @psybor 看看最新 antd 版本是否已经解决了这个问题？

不好意思，没及时回复。
我看 4.24 和 5.0 都没有这个问题了。
