### ISSUE TITLE
`DatePicker` works buggy in `week` with `dayjs` 

### ISSUE THREAD

**Issue by susiwen8** [ant-design/ant-design#34270]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-frog-wrdv29?file=/src/App.js)

### Steps to reproduce
Open like, you will see `DatePicker` show `gggg-wo`

### What is expected?
https://codesandbox.io/s/ji-ben-antd-4-18-9-forked-xejng3?file=/index.js
Work like `moment`

### What is actually happening?
`gggg-wo`

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 17.0.2 |
| System | MacOs |
| Browser | Chrome latest |

**Comment by faradaytrs** [comment]
Same here

**Comment by MadCcc** [comment]
https://ant.design/docs/react/replace-moment-cn#header
Please check it.

**Comment by MadCcc** [comment]
And we will replace momentjs with dayjs in V5.
https://github.com/ant-design/ant-design/issues/33862

**Comment by JunniL** [comment]
Same here
