### ISSUE TITLE
4.18.9 Table自定义行组件后，在render方法内，使用useContext不能触发重新渲染

### ISSUE THREAD

**Issue by MoYuM** [ant-design/ant-design#34274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-antd-4-18-9-forked-gjn4qg)

### Steps to reproduce
点击最后一列的 toggle 按钮

### What is expected?
能在render内正常使用useContext

### What is actually happening?
render方法内useContext 不能触发重新渲染

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 最新 |
| System | mac |
| Browser | Chrome |

**Comment by afc163** [comment]
Class 组件内不能用 hooks，类似问题可以参看 https://github.com/react-component/table/issues/756#issuecomment-1047613144
