### ISSUE TITLE
希望Form增加formatter与parser

### ISSUE THREAD

**Issue by Phyzait** [ant-design/ant-design#34281]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
与`Upload`组件封装结合时，传入的初始值往往是`string`或`string[]`，此时需要转换为`UploadFile[]`，而输出时需要从`UploadFile[]`转换为`string`或`string[]`。
而现有的`normalize`等方法似乎难以实现，因为`UploadFile`中也包含了文件的当前状态（上传中、上传失败等）等信息，由多转少（UploadFile转string）容易，而由少转多难（string转UploadFile）
若每次都在`onFinish`方法中处理请求会产生很多冗余代码。
希望可以给出解决方案或建议~

### What does the proposed API look like?
`formatter`方法在传入初始值时，转为指定类型。
`parser`方法在Form表单提交时，转为指定类型。

**Comment by Phyzait** [comment]
已阅读 #19727 等 issue~ 感觉没有这两个属性还是很难搞的~

**Comment by afc163** [comment]
建议自行封装一个高阶组件，这个在 Form.Item 上加属性会更复杂。

**Comment by Phyzait** [comment]
> 建议自行封装一个高阶组件，这个在 Form.Item 上加属性会更复杂。

目前是的，忽略了`value`的更新，把`fileList`的处理都在内部消化了
