### ISSUE TITLE
Table控件列筛选bug,1、设置columns的filterMode:'tree'，未选择全部筛选数据，全选按钮却为选中状态。2、设置默认筛选值，点击重置，不应该清除所有值，而应该恢复默认筛选值

### ISSUE THREAD

**Issue by Ryang-H** [ant-design/ant-design#34280]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shu-xing-shai-xuan-cai-dan-antd-4-18-9-forked-nb7n8k?file=/index.js)

### Steps to reproduce
1、columns列筛选设置defaultFilteredValue，过滤时点击重置按钮，不应该清除所有选中筛选值，而应该恢复为默认筛选值。
2、columns列筛选设置filterMode:'tree'，先点击列筛选全选按钮，在取消选择下方某个筛选数据，此时并未选择全部筛选数据，而筛选的全选按钮却为选中状态

### What is expected?
1、如果表格列筛选中设置了默认筛选值，点击筛选的重置按钮时，不应该清除所有筛选值的选中状态，而应该恢复为默认筛选值为选中
2、设置指定筛选菜单的用户界面filterMode:'tree'，列筛选中没有选择全部筛选数据时，全选按钮不应该为选中状态

### What is actually happening?
1、表格列中设置了默认的筛选值，点击筛选的重置按钮，清空了所有选中数据，应该重置为初始的默认筛选数据
2、表格列筛选中，设置columns的filterMode:'tree'，没有选择全部筛选数据，而筛选框的全选按钮却为选中状态

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | 17.0.1 |
| System | window10 |
| Browser | Microsoft  Edge  98.0.1108.62  |

![image](https://user-images.githubusercontent.com/79308283/156526139-5c4b8e76-81d0-420a-af01-0d9bbeb1aaee.png)

**Comment by afc163** [comment]
1、设置columns的filterMode:'tree'，未选择全部筛选数据，全选按钮却为选中状态

https://github.com/ant-design/ant-design/pull/34295 已修复。

2、设置默认筛选值，点击重置，不应该清除所有值，而应该恢复默认筛选值

和 form 里的 reset button 类似，确实应该恢复初始值。不过这里用户心智已形成，为避免交互上的 break change，而且 defaultFilteredValue 和受控模式下的 filteredValue 的初始值无法从 UI 上区分，故不做修改了。
