### ISSUE TITLE
$ tsc --noEmit throws error on datepicker interface

### ISSUE THREAD

**Issue by RiteshMakan** [ant-design/ant-design#34289]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sew74o)

### Steps to reproduce
run tsc --noEmit on your project

```
yarn run v1.22.15
$ tsc --noEmit
node_modules/antd/lib/date-picker/generatePicker/interface.d.ts:1:31 - error TS2724: '"react"' has no exported member named 'ForwardedRef'. Did you mean 'forwardRef'?

1 import type { ComponentClass, ForwardedRef, Component } from 'react';
                                ~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:801:14
    801     function forwardRef<T, P = {}>(render: ForwardRefRenderFunction<T, P>): ForwardRefExoticComponent<PropsWithoutRef<P> & RefAttributes<T>>;
                     ~~~~~~~~~~
    'forwardRef' is declared here.


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
### What is expected?
No errors

### What is actually happening?
Checking Typescript with `tsc --noEmit` throws an error

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | React: ^16.8.0 |
| System | Node v14.16.1 or v16.0.0 |
| Browser | Google Chrome Latest |

**Comment by afc163** [comment]
What version of @types/react are you using?

**Comment by afc163** [comment]
Try:

```
rm -rf node_modules yarn.lock package-lock.json
npm install
tsc --noEmit
```
