### ISSUE TITLE
Customizing antd in nextjs slows down the project in dev mode

### ISSUE THREAD

**Issue by moghani81** [ant-design/ant-design#34287]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/34286](https://github.com/ant-design/ant-design/issues/34286)

### Steps to reproduce
i've followed this guide for customize antd in nextjs

‍‍‍‍antd is properly customized, but when I run my project with the yarn dev command, the project speed drops sharply. The nodejs program takes up all of RAM, so I need to restart the system.

But if I do not customize the antd, I will not have this problem
Please add a guide to personalizing antd in the antd document

### What is expected?
fix problem

### What is actually happening?
Customizing antd in nextjs slows down the project in dev mode

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | ubuntu |
| Browser | chrome |

**Comment by afc163** [comment]
Theme customizition depends on on less and less-loader which will slow down devlopment environment. There is nothing we can do but we can wait for antd v5 which will drop less.js. https://github.com/ant-design/ant-design/issues/33862
