### ISSUE TITLE
Typography.Text and Link to allow the need for `small` and `xsmall` text sizes

### ISSUE THREAD

**Issue by RiteshMakan** [ant-design/ant-design#34291]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will provide the ability to provide smaller text sizes that will be useful for footnotes, or smaller font sizes. Current workaround is passing in a className and adding in the prop ` className={"text-size-small" | "text-size-xsmall"}, This does land with a caveat where I get the warning in the console:
`Warning: React does not recognize the `toString` prop on a DOM element....` as it tries to parse 'className' as a prop

### What does the proposed API look like?
this occurs when wrapping the Ant Typography component
```import React from 'react';
import { Typography as AntTypography } from 'antd';
import TypographyProps from './TypographyProps';

import './Typography.style.less';

const { Text, Title, Paragraph, Link } = AntTypography;

const Typography = ({ textSize='default', ...props }: TypographyProps) => {
  return <AntTypography textSize={`${className}`} {...props} />;
};

Typography.Text = Text;
Typography.Title = Title;
Typography.Paragraph = Paragraph;
Typography.Link = Link;

export default Typography;
```

**Comment by afc163** [comment]
Try `<Typography style={{ fontSize: 12 }}>`.
