### ISSUE TITLE
Table的expandedRowRender函数 当dataSource数据中没有key字段时无法展开

### ISSUE THREAD

**Issue by jindada** [ant-design/ant-design#3430]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: win7
- 浏览器及其版本: Google Chrome 53.0.2785

#### 您做了什么？

import React, { PropTypes } from 'react'
import { Table, Tag, Icon, Button } from 'antd'

const TableList = ({ loading }) => {

	const columns = [
	    { title: '姓名', dataIndex: 'name', key: 'name' },
	    { title: '年龄', dataIndex: 'age', key: 'age' },
	    { title: '住址', dataIndex: 'address', key: 'address' },
	    { title: '操作', dataIndex: '', key: 'x', render: () => <a href="#">删除</a> },
	];

	const data = [
	    { name: '胡彦斌', age: 32, address: '西湖区湖底公园1号', description: '我是胡彦斌，今年32岁，住在西湖区湖底公园1号。' },
	    { name: '吴彦祖', age: 42, address: '西湖区湖底公园2号', description: '我是吴彦祖，今年42岁，住在西湖区湖底公园2号。' },
	    { name: '李大嘴', age: 32, address: '西湖区湖底公园3号', description: '我是李大嘴，今年32岁，住在西湖区湖底公园3号。' },
	];

	const openRow = (record) => {
		console.log(record)
		return  <p>{record.url}</p>
	}

	return (
		<Table columns={ columns } dataSource={ data } loading={ loading }  expandedRowRender={ openRow }/>
	)
}

export default TableList
export default TableList

#### 您期待的结果是：

像官网一样正常显示 

#### 实际上的结果是：
展开按钮出现 但是点击无反应 官网中给的数据有key的字段 去掉之后 就出现这种情况 但是官网没有给出说明指出key为必须字段

**Comment by ddcat1115** [comment]
https://ant.design/components/table/#注意
