### ISSUE TITLE
"Show code"-icon not available on antd webside with adblocker activated

### ISSUE THREAD

**Issue by SimBig** [ant-design/ant-design#34309]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tooltip/#header](https://ant.design/components/tooltip/#header)

### Steps to reproduce
open link with dev tools

### What is expected?
Show code"-icon should be visible to toggle the show code.

### What is actually happening?
The icon is not visible and toogle show code does not work if the adblocker is activated
![image](https://user-images.githubusercontent.com/26680884/156789242-1bc90ac0-db2b-48a8-8574-e1e8f80bb6b7.png)

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | react |
| System | win10 |
| Browser | chrome, firefox |

---
Similar to https://github.com/ant-design/ant-design/issues/33925
Additionally I found out that it seems to be connected with the adblocker "AdGuard". But also with deactivated adblocker, it displays an error in the console and does not display the icon correctly

**Comment by afc163** [comment]
There is nothing we can do about it, I suggest turning off AdGuard on https://ant.design
