### ISSUE TITLE
官网基本上所有涉及pupup的组件在ie11上都无法正常显示

### ISSUE THREAD

**Issue by HAM2506** [ant-design/ant-design#34303]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
打开官网，点击任意涉及popup的组件比如menu、select、timepicker、tooltip等。

### What is expected?
期望和chrome一样正常显示

### What is actually happening?
在ie1均无法正常显示。

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | react |
| System | windows10 |
| Browser | ie11 |

**Comment by yoyo837** [comment]
@xrkffgg 看看action是不是不太对？

**Comment by HAM2506** [comment]
> @xrkffgg 看看action是不是不太对？

貌似这个issue也被自动关闭了 #33609

**Comment by afc163** [comment]
机器人有问题。这个可以合并到 https://github.com/ant-design/ant-design/issues/31283 里讨论。

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/31283

**Comment by xrkffgg** [comment]
恩，我瞅瞅
