### ISSUE TITLE
Money Text Component

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design#34311]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As with the Input Number component, only a text-format component is needed. For example, I want to add the decimal separator along with the money symbol to the end of monetary values.

It can be defined in Typography and derived from the Text component.

### What does the proposed API look like?

```
<Money decimalSeperator="," locale="en-En" value={25} />
<Money decimalSeperator="," thousandSeparator="." value={25} customSymbol="$" />
```

**Comment by zombieJ** [comment]
It's too heavy for maintains...

**Comment by xXAvoraXx** [comment]
> It's too heavy for maintains...

It can also be added to the Text component.

```
<Text type="money" decimalSeperator="," thousandSeparator="." customSymbol="$" value={25} />
<Text type="digit" value={25} />
```

**Comment by xXAvoraXx** [comment]
> That you can try https://ant.design/components/statistic/

```
![likethis2](https://user-images.githubusercontent.com/6988989/157228265-6dc0a1f2-7b02-42c8-bbb8-a899c8a6d90f.png)

          <Tag color="volcano">
            <Statistic value={totalPrice.total.toFixed(2)} valueStyle={undefined} />
          </Tag>
```
The font and color do not inherit from the previous component.

Normal
![taglikethis](https://user-images.githubusercontent.com/6988989/157228323-606406ba-172b-45ac-bc83-d0c5d29c4066.png)

`<Tag color="volcano">{totalPrice.total.toFixed(2)}</Tag>`

**Comment by afc163** [comment]
See https://www.npmjs.com/package/react-number-format
