### ISSUE TITLE
Table设置columns的filterMode:'tree'，未选择全部筛选数据，全选按钮却为选中状态

### ISSUE THREAD

**Issue by Ryang-H** [ant-design/ant-design#34318]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shu-xing-shai-xuan-cai-dan-antd-4-18-9-forked-nb7n8k?file=/index.js)

### Steps to reproduce
设置cloumns的filterMode:'tree'，先点击全选所有筛选数据，在取消选择下方某个删选数据

### What is expected?
没有选择全部筛选数据时，筛选框中的全选按钮不应该为选中状态

### What is actually happening?
没有选择全部筛选数据，筛选框却为选中状态。
而且提另外一个问题，设置了默认筛选值，点重置，不应该恢复为初始的默认筛选值吗，如果是用户习惯方面，那不可以开放一个重置事件的api帮助开发者自定义赋值吗

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 17.0.2 |
| System | window10 |
| Browser | Microsoft  Edge  98.0.1108.62  |

---
![image](https://user-images.githubusercontent.com/79308283/156922692-511e2eb3-14b9-4dd9-a691-ac5ccc1d417e.png)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!这个bug我更新到最新版本了，没有被修复啊，官网上的bug还是依然存在的，为什么还回信说在#34280里给修复了？这随意关闭有点糊弄人啊

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/34295 已合并，等下个 patch 发布。

**Comment by afc163** [comment]
>  如果是用户习惯方面，那不可以开放一个重置事件的api帮助开发者自定义赋值吗

你的建议加一个什么样的 API 方便描述一下么？

**Comment by Ryang-H** [comment]
table表格的列筛选，如果设置了默认筛选值，点击重置的时候，认为应该是恢复默认筛选值的，而不是清空所有筛选值。&nbsp; 可不可以开放一个表格列筛选重置事件，可以让有这方面需求的开发者自定义赋值这一重置事件呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Table设置columns的filterMode:'tree'，未选择全部筛选数据，全选按钮却为选中状态 (Issue #34318)





  
如果是用户习惯方面，那不可以开放一个重置事件的api帮助开发者自定义赋值吗
  
你的建议加一个什么样的 API 方便描述一下么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by afc163** [comment]
看上去可以加个 `filterResetToDefaultFilteredValue: boolean`
