### ISSUE TITLE
antd2.0.1版本中在Tabs中加入Table，但是Table中数据不显示

### ISSUE THREAD

**Issue by strongwan** [ant-design/ant-design#3431]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:win7 x64
- 浏览器及其版本:火狐谷歌

#### 您做了什么？
引入了antd的Tabs，并在Tabs中加入Table

#### 您期待的结果是：
正常显示

#### 实际上的结果是：
Table中数据没显示，实际上在antd1.10.0的版本中这是可以的，完全没问题，升级之后就出错了。去掉Tabs，单独用Table也没问题

**Comment by ddcat1115** [comment]
试了下没能重现，请提供可重现demo：

http://codepen.io/anon/pen/wGOWGW?editors=001

并注意升级时是否有不兼容情况：

https://ant.design/changelog#2.x-不兼容改动

**Comment by strongwan** [comment]
找到原因了，是我在tabs中添加了一些自己的样式，可能这些样式导致的一些问题，谢谢
