### ISSUE TITLE
在npm run build 后，icon打包过大

### ISSUE THREAD

**Issue by rabbitbiubiubiu** [ant-design/ant-design#34320]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/icon-cn/](https://ant-design.gitee.io/components/icon-cn/)

### Steps to reproduce
使用icon，npm run build包过大

### What is expected?
按需引用icon

### What is actually happening?
全部引用

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 16.13.1 |
| System | window |
| Browser | chrome |

**Comment by lucaslz2020** [comment]
`components/config-provider/index.tsx` 这个文件中引入的字体组件路径是不是有问题？`import IconContext from '@ant-design/icons/lib/components/Context';
` 其他的地方又是使用es方式。导致打包的时候会有lib、es都存在

**Comment by afc163** [comment]
@lucaslz2020 看上去都是 es：https://unpkg.com/browse/antd@4.19.1/es/config-provider/index.js

**Comment by lucaslz2020** [comment]
@afc163 antd使用es，在cra配置中，`@ant-design/icons` 默认引用的是lib。 有什么方式配置@ant-design/icons使用es吗？

**Comment by afc163** [comment]
发一下 github 仓库看看，cra 默认应该是走 es module 的。

**Comment by lucaslz2020** [comment]
@afc163 是我搞错了，是自己组件库的问题
