### ISSUE TITLE
Cascasder在搜索后敲击回车选中对象，只能得到children的value

### ISSUE THREAD

**Issue by mayu1942** [ant-design/ant-design#34329]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sou-suo-antd-4-18-9-forked-su76po?file=/index.js)

### Steps to reproduce
1、点击组件，使用搜索    
2、搜索“zhe”    
3、在出来的结果中，使用键盘下选中“Zhejiang/ Hangzhou/ West Lake”    
4、从onchange获取到选中的value

### What is expected?
value包含级联的各级的value，如此时的value该为：
["zhejiang","hangzhou","xihu"]

### What is actually happening?
1. 用回车选中时，只返回了children的value：["xihu"]
2. 用鼠标点击时，返回了期望的结果：["zhejiang","hangzhou","xihu"]

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 17.0.2 |
| System | Centos 7.5 |
| Browser | chrome(97.0.4692.71) |

---
我们的业务场景：    
1、级联的多个value都是有意义的，比如一个为服务的类型，一个为服务的版本，选中之后，要根据服务的类型 版本查询其他信息。    
2、在使用搜索功能时，需要用键盘输入，这时使用回车去选中是更符合用户习惯的做法。但是因为这个问题，需要用户在输入搜索条件后，再切换使用鼠标点击选中。

**Comment by afc163** [comment]
看上去和 #34312 一样。
