### ISSUE TITLE
一个组件内有多个Form表单怎么区分呢？

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design#3432]
- antd 版本: 2.0.1
- 操作系统及其版本: ubunut 16
- 浏览器及其版本: google  53.0.2785.116 m

一个组件(UserProfile)有A Form 和 B Form ， 
组件UserProfile 整体 Form.create(UserProfile),
当我提交或者填充表单的时候怎么区分。
两个表单在不同的Modal中

基础代码：

    <div>
        <Modal onCancel={() => this.setState({baseOpen: false})}
               title={lang.updateBaseInfo}
               visible={this.state.baseOpen}
        >
          <Form>
            {this.renderBaseForm()}
          </Form>
        </Modal>
        <Modal onCancel={() => this.setState({settleOpen: false})}
               title={lang.updateSettle}
               visible={this.state.settleOpen}
        >
          <Form>
            {this.renderSettleForm()}
          </Form>
        </Modal>
     </div>

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3402
