### ISSUE TITLE
List.Item.Meta 的 description 在中英文混合 手机浏览器上，没有正常换行

### ISSUE THREAD

**Issue by SongLingPu** [ant-design/ant-design#34327]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-chu-lie-biao-antd-4-18-9-forked-bxrbb4?resolutionWidth=320&resolutionHeight=675&file=/index.js)

### Steps to reproduce
设置 List.Item.Meta 的 description 等于“神器0介绍ewfefwfdwedwedwedewdwdwedwedfweferfewferwfewfe”。然后将浏览器调整为手机模式。

### What is expected?
期望能正常换行。

### What is actually happening?
没有正常换行，且超出了屏幕。

| Environment | Info |
|---|---|
| antd | 4.17.0 |
| React | 17.0.0 |
| System | macOS big sur 11.4 |
| Browser | 版本 96.0.4664.110（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
长单词不会自动截断。
