### ISSUE TITLE
TreeSelect placeholder not work

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3433]
https://ant.design/components/tree-select/

**Comment by afc163** [comment]
2.1.0 之前修复掉。

**Comment by afc163** [comment]
只是演示有问题。

**Comment by Fairyshi** [comment]
当前版本V2.5.0，placeholder仍然不能显示：
        const jsxTreeSelect = (
            <TreeSelect
            placeholder='请选择'
            value={value}
            treeData={treeData}
            style={{width}}
            dropdownStyle={{ maxHeight: 600, overflow: 'auto' }}
            allowClear
            treeDefaultExpandAll
            onChange={::this.handleSelectTree}
            />
        );
        return (
            <div className='tree-select-wrap' style={{width}}>
                {jsxTreeSelect}
            </div>
        )

**Comment by benjycui** [comment]
@Fairyshi 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by vito24** [comment]
@Fairyshi 试试将value设置为undefined

**Comment by fritx** [comment]
@vito24 确实是这样，我目前版本为 antd `^3.1.0`
