### ISSUE TITLE
OpenAPI不支持header参数

### ISSUE THREAD

**Issue by parvaterram** [ant-design/ant-design#34331]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
生成的接口文件具备请求头token校验

### What does the proposed API look like?
"paths": {
    "/api/currentUser": {
      "get": {
        "tags": ["api"],
        "description": "获取当前的用户",
        "operationId": "currentUser",
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentUser"
                }
              }
            }
          },
          "401": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "x-swagger-router-controller": "api"
    }
}

目前生成：
// @ts-ignore
/* eslint-disable */
import { request } from 'umi'

/** 获取当前的用户 GET /api/currentUser */
export async function currentUser(
  // 叠加生成的Param类型 (非body参数swagger默认没有生成对象)
  params: API.currentUserParams
    // header
    'token'?: string;
    
  ,
  options ?: {[key: string]: any}
) {
  return request<API.CurrentUser>('/api/currentUser', {
  method: 'GET',
    headers: {
    },
    params: {...params,},
    ...(options || {}),
  });
}

期望生成的接口文件：
// @ts-ignore
/* eslint-disable */
import { request } from 'umi'

/** 获取当前的用户 GET /api/currentUser */
export async function currentUser(
  // 叠加生成的Param类型 (非body参数swagger默认没有生成对象)
  params: API.currentUserParams,
  headers: {
   token: string
 }
  options ?:  {[key: string]: any}
) {
  return request<API.CurrentUser>('/api/currentUser', {
  method: 'GET',
    headers: {
     ...(headers || {})
    },
    params: {...params,},
    ...(options || {}),
  });
}

**Comment by afc163** [comment]
提错地方了吧。

**Comment by parvaterram** [comment]
> 提错地方了吧。
"parameters": [
{
"name": "token",
"in": "header",
"schema": {
"type": "string"
}
}
],


https://editor.swagger.io，swagger3.0的文档是这样格式的
