### ISSUE TITLE
Cascader作为一个单独的组件import引入到Form中使用， form.setFieldsValue填充值Cascader未选中

### ISSUE THREAD

**Issue by AliyaLiu** [ant-design/ant-design#34335]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-pateu-ko2i0o?file=/src/App.js)

### Steps to reproduce
1. 如demo所示，点击外部赋值，赋值无效，Cascader默认值未选中；
2. 如demo所示，选择一个值，点击确定，value值为undefined；

### What is expected?
1. 如demo所示，点击外部赋值，赋值有效，Cascader值选中；
2. 如demo所示，选择一个值，点击确定，value值为选择的值；

### What is actually happening?
1. 如demo所示，点击外部赋值，赋值无效，Cascader默认值未选中；
2. 如demo所示，选择一个值，点击确定，value值为undefined；

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/infallible-shockley-018env?file=/src/Cascader.js

https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
