### ISSUE TITLE
关于文档中，表格组件里部分示例未能显示的问题

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#34333]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/?theme=dark#components-table-demo-resizable-column](https://ant.design/components/table-cn/?theme=dark#components-table-demo-resizable-column)

### Steps to reproduce
1. 直接打开 https://ant.design/components/table-cn/?theme=dark#components-table-demo-basic 没有`可伸缩列`的示例

![image](https://user-images.githubusercontent.com/51586637/157004497-c8ca705d-5fb0-4c49-ba83-08074d53307e.png)

3. 打开 https://ant.design/components/table-cn/?theme=dark#components-table-demo-resizable-column 却有

![image](https://user-images.githubusercontent.com/51586637/157004558-410af727-e24f-4719-a2d8-f96c89a67c24.png)

### What is expected?
示例完整

### What is actually happening?
示例不完整

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 16 |
| System | Windows 10 x64 |
| Browser | Edge 最新版 |

**Comment by afc163** [comment]
对，这个例子 bug 太多，默认隐藏了，不推荐使用。

<img width="926" alt="图片" src="https://user-images.githubusercontent.com/507615/157006804-297a61af-ce91-491c-94ae-7e92c1d160bc.png">

可以点击这个图标切换显示。
