### ISSUE TITLE
select在mode为multiple时，无法删除searchValue的值

### ISSUE THREAD

**Issue by 2470589018** [ant-design/ant-design#34330]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nwdet5?file=/index.js)

### Steps to reproduce
步骤：1、输入关键词模糊查找，2、选中任意项，3、按键盘backspace删除关键词，也就是searchValue。

### What is expected?
希望关键词searchValue能清空

### What is actually happening?
在有选中项的情况下，searchValue无法清空

| Environment | Info |
|---|---|
| antd | 4.16.7 |
| React | 4.2.2 |
| System | win64 |
| Browser | 谷歌98.0.4758.102 |

---
在没有选中项的情况下，searchValue可以清空

**Comment by afc163** [comment]
貌似没问题：https://codesandbox.io/s/antd-reproduction-template-forked-igk63n?file=/index.js

你的例子里写死了 searchValue，这是一个受控属性，所以无法输入了。

**Comment by 2470589018** [comment]
> 貌似没问题：https://codesandbox.io/s/antd-reproduction-template-forked-igk63n?file=/index.js
> 
> 你的例子里写死了 searchValue，这是一个受控属性，所以无法输入了。

我想通过searchValue控制输入的值，没办法做到吗？或者有没有其他方式控制输入值？为什么急着把问题关了
