### ISSUE TITLE
在react的严格模式下使用antd的menu会产生警告

### ISSUE THREAD

**Issue by fssh** [ant-design/ant-design#34345]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fssh/react-simple.git](https://github.com/fssh/react-simple.git)

### Steps to reproduce
点击导航按钮Navigation Three，然后查看控制台，会发现warning。

### What is expected?
点击导航按钮Navigation Three，然后查看控制台，没有warning。

### What is actually happening?
点击导航按钮Navigation Three，然后查看控制台，会发现warning。

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome  99.0.4844.51 |

**Comment by yoyo837** [comment]
Trace in #26136.
