### ISSUE TITLE
 css variables 开放更多变量支持，如背景色变量

### ISSUE THREAD

**Issue by guoyong** [ant-design/ant-design#34349]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
支持背景色的css变量，可以更加灵活的支持动态换肤功能

### What does the proposed API look like?
html {
...
--ant-body-background: #fff;
--ant-component-background: #fff;
}

popover-background: var(--ant-component-background);

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/33862, we will move to CSS in JS.

**Comment by yuxuan** [comment]
尝试了一下把所有颜色相关的less变量转换成css variables。
<img width="600" alt="CleanShot 2022-03-09 at 13 49 43@2x" src="https://user-images.githubusercontent.com/2955214/157380612-20833032-540b-4d20-8f28-bacef70ac7f3.png">

然后再根据需要调整css variables，比如加一层主题变量之类，但是调试这些token其实也挺头疼的。

<img width="621" alt="CleanShot 2022-03-09 at 13 50 16@2x" src="https://user-images.githubusercontent.com/2955214/157380714-42982147-7169-4284-b7cc-7b3af7712851.png">

想问一下，有更多css in js的示例吗？

**Comment by qingfengmy** [comment]
就现在基于antd4.22，有没有好的换肤方案，支持的全一些的。
