### ISSUE TITLE
Table组件添加fixed属性后可滚动时固定列样式错误

### ISSUE THREAD

**Issue by conan2lv** [ant-design/ant-design#34347]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-9-forked-je5t7m?file=/index.js)

### Steps to reproduce
当页面缩小至表格可横向滚动时，固定列无box-shadow样式，这与v3版本的表现不一致

### What is expected?
当表格可横向滚动时，固定列同v3版本一样有box-shadow的样式而不是和其他列的内容混合在一起

### What is actually happening?
表格可横向滚动时，固定列并无box-shadow样式，导致列与列之间内容交错，看起来很糟糕

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | react |
| System | mac 11.2.3 |
| Browser | chrome98 |

**Comment by afc163** [comment]
3.x 也没有阴影：https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-9-forked-onethf?file=/index.js

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-4-18-9-forked-nk547q?file=/index.js

1. 不要自定义 ant-table-content 宽度
2. 使用 scroll.x 配合固定列使用

详情看 https://ant.design/components/table-cn/#components-table-demo-fixed-columns
