### ISSUE TITLE
表单会影响到组件之间的方法调用

### ISSUE THREAD

**Issue by 405go** [ant-design/ant-design#3434]
#### 发生问题的环境是：

- antd 版本:2.0.0
- 操作系统及其版本:w7 64
- 浏览器及其版本:谷歌 53.0.2785.143 m

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/pull/2992

**Comment by benjycui** [comment]
麻烦描述下你的业务场景，绝大多数情况下 `ref` 都被误用了。

**Comment by 405go** [comment]
我试了使用this.refs.xxx.refs.wrappedComponent.refs.formWrappedComponent来用，可是在this.refs.xxx.refs.wrappedComponent就已经是未定义了，调试看了一下this.refs.xxx.refs是一个空的object

**Comment by afc163** [comment]
withRef
