### ISSUE TITLE
Image->show image preview show redundant image-mask-info

### ISSUE THREAD

**Issue by MrLKduyu** [ant-design/ant-design#34360]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/image/](https://ant.design/components/image/)

### Steps to reproduce
show image preview's elements can seen a out of bounds ant-image-mask-info--icon add text "Preview"

### What is expected?
don't out of bounds ant-image-mask-info--icon add text "Preview"

### What is actually happening?
out of bounds ant-image-mask-info--icon add text "Preview"

| Environment | Info |
|---|---|
| antd | 4.19.0 |
| React | all |
| System | all |
| Browser | all |

---
don't show more black and don't show text and icon when mouse hover

**Comment by afc163** [comment]
I don't realy get the problem, could you post a screenshot?

**Comment by baibaibai455** [comment]
> 没看懂，能发个截图吗？


![image](https://user-images.githubusercontent.com/47173675/157415177-65d4f1fc-4d1d-466d-9d8b-c07412233ae4.png)

![image](https://user-images.githubusercontent.com/47173675/157415306-e53c62e1-e1c2-4134-a95d-a11bb4359dc7.png)



他应该是说的这里    不希望Image标签过小时显示...      并且怎么将Preview 全局设置成中文
