### ISSUE TITLE
ProTable ellipsis属性在大于2k分辨率的屏幕下会不停闪烁

### ISSUE THREAD

**Issue by hjc0930** [ant-design/ant-design#34363]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/pro-components/issues/4758](https://github.com/ant-design/pro-components/issues/4758)

### Steps to reproduce
使用ProTable开发表格，默认不设置ellipsis属性，在2K以上屏幕中会出现字体闪烁，观察Element发现是ant-typography-ellipsis属性不断切换导致

### What is expected?
表格不再闪烁

### What is actually happening?
https://user-images.githubusercontent.com/70308058/156358969-62368e02-a755-4ad1-8765-e621da320ccf.gif
https://user-images.githubusercontent.com/70308058/156359442-e1de1572-c62f-4eeb-9efb-fde099cca144.png

| Environment | Info |
|---|---|
| antd | 4.17.1 |
| React | 17.X |
| System | win10 |
| Browser | chrome |

---
在ProComponents下有提过，那边说是antd的问题，让我来这边提下
https://github.com/ant-design/pro-components/issues/4758

**Comment by zombieJ** [comment]
windows 有设置屏幕缩放么？

**Comment by hjc0930** [comment]
> windows 有设置屏幕缩放么？

首次发现是在同事的MAC笔记本上，2880*1800

**Comment by zombieJ** [comment]
@hjc0930，
看起来空间有剩余不应该变省略号，给个 antd Table 的 reproduce 看看？

**Comment by whaleluo** [comment]
这个问题没人跟进吗
