### ISSUE TITLE
Table的dataSource中数据类型有bool类型时，不显示

### ISSUE THREAD

**Issue by lush-99** [ant-design/ant-design#34370]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com/真的没有代码示例，因为例子很容易复现](http://www.baidu.com/真的没有代码示例，因为例子很容易复现)

### Steps to reproduce
```
import { Button, Table as AntTable, } from 'antd'
const requestBodyTableColumns = [
    {
        title: '名称',
        dataIndex: 'name',
    },
    {
        title: '类型',
        dataIndex: 'type',
    },
    {
        title: '是否必填',
        dataIndex: 'isRequreid',
    },
    {
        title: '示例值',
        dataIndex: 'example',
    }
]
const requestBodyTableData = [
    {
        name: 'type',
        type: 'int',
        isRequreid: false,
        example: 308193,
        key: 1
    }
]
<AntTable columns={requestBodyTableColumns} dataSource={requestBodyTableData} pagination={false} />
```

### What is expected?
显示bool类型的数值

### What is actually happening?
不显示

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | win10 |
| Browser | 火狐 |

---
codeopen上使用不显示；
重现步骤：只需把随意的dataSource的值传为bool类型

**Comment by lush-99** [comment]
![image](https://user-images.githubusercontent.com/77112588/157241556-6d0df254-1b22-47c7-8b0b-b6dd4e94028e.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33208#issuecomment-988644736
