### ISSUE TITLE
Popover and Select

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3438]
Is it possible to prevent the changing of visibility of popover after interaction with Select?

Here is demo:
http://codepen.io/anon/pen/XjBVbp?editors=0011

**Comment by afc163** [comment]
http://codepen.io/anon/pen/amjEpL?editors=0011

You can make Select dropdown menu rendering inside the Popover content.

**Comment by plandem** [comment]
Works! i would add this to official examples. Thanks.

**Comment by guohuihuiguo** [comment]
hello
  我试着用上面的方法 `												getPopupContainer={(triggerNode: any) => triggerNode.parentNode}
`结果 

![1556620903631-image](https://user-images.githubusercontent.com/32259179/56956777-b268be80-6b77-11e9-9cdb-91ecbd87ffbf.png)

**Comment by mix0000** [comment]
> `getPopupContainer` https://ant.design/components/select/#Select-props
> 
> https://codepen.io/anon/pen/NaMbVg?editors=0011
> 
> You can use `getPopupContainer={triggerNode => triggerNode.parentNode}` to make select dropdown menu rendering inside the Popover content.
> 
> https://github.com/ant-design/ant-design/wiki/FAQ#select-dropdown-datepicker-timepicker-popover-popconfirm-will-scroll-with-page
> 
> #3487

Thats not work for Ant Date Pickers.

**Comment by lwh795** [comment]
Use getpopupcontainer = {triggernode = > triggernode. Parentnode} in the select in the modal. When the focus is obtained in IE 11,the whole modal will flash.

**Comment by lwh795** [comment]
> 使用 getpopupcontainer = {triggernode = > triggernode. Parentnode} 在模态中的选择中。在 IE 11 中获得焦点时，整个 modal 会闪烁。

For the same problem as this bug(https://github.com/ant-design/ant-design/issues/21039), I found a temporary solution from the comments

**Comment by chandpratik** [comment]
> > `getPopupContainer` https://ant.design/components/select/#Select-props
> > https://codepen.io/anon/pen/NaMbVg?editors=0011
> > You can use `getPopupContainer={triggerNode => triggerNode.parentNode}` to make select dropdown menu rendering inside the Popover content.
> > https://github.com/ant-design/ant-design/wiki/FAQ#select-dropdown-datepicker-timepicker-popover-popconfirm-will-scroll-with-page
> > #3487
> 
> Thats not work for Ant Date Pickers.

Try using getCalendarContainer={trigger => trigger.parentElement}
