### ISSUE TITLE
Button component does not render the attribute data-testid on Chrome browser

### ISSUE THREAD

**Issue by herbertpimentel** [ant-design/ant-design#34393]
- [ X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-button-does-not-accept-data-testid-hl5xem)

### Steps to reproduce
set the attribute data-testid="datepicker1" for a date picker
set the attribute date-testid="button1" for a button

inspect the page html

the input for date picker HAS the attribute 
the button DOES NOT HAVE the attribute 

The same app running on mozilla firefox vesion 97.0.2 (64-bit) browser, the works as expected. and results in a button that does have the data-testid attribute for both date-picker and the button demonstrating a inconsistent behaviour. 

### What is expected?
The button also have in the redered html the atrribute data-testid as specified. 

### What is actually happening?
On Chrome 99.0.4844.51 - 64 bits the attribute is not present on rendered HTML
On mozilla firefox vesion 97.0.2 (64-bit) the attribute is present on rendered HTML

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | react 17.0.2 |
| System | WIndows 10 |
| Browser | Chrome 99.0.4844.51 - 64 bits |

**Comment by zombieJ** [comment]
<img width="553" alt="截屏2022-03-10 上午10 38 03" src="https://user-images.githubusercontent.com/5378891/157577480-46448b9d-d895-48ae-bbaf-a5ebc35799f4.png">
