### ISSUE TITLE
Table columns don`t pass into the title,title is null. why not set default upperFirst dataIndex

### ISSUE THREAD

**Issue by Germiniku** [ant-design/ant-design#34396]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In English websites, the interface response parameter field is the default title( title is optional ). When the default title is null, dataIndex is so cool by default

### What does the proposed API look like?
no api.

**Comment by Germiniku** [comment]
Example is this
```
 <Table
        columns={[
          { dataIndex: 'name' }
        ]}
 />
```


so title is default dataIndex, Name ----> upperFirst(dataIndex)

**Comment by afc163** [comment]
dataIndex is not a readable text in common.
