### ISSUE TITLE
Table errors if column header name is "children"

### ISSUE THREAD

**Issue by maycheongs** [ant-design/ant-design#34394]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-19-0-forked-ursdjj?file=/index.js)

### Steps to reproduce
Have a dataset with "children" as a column header. 

### What is expected?
Table does not error out.

### What is actually happening?
Throws syntax error "(data || []).forEach is not a function at flattenData
https://ursdjj.csb.app/node_modules/antd/es/table/hooks/useSelection.js:50:16"

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | Ubuntu 20.04 |
| Browser | Chrome |

---
The application is for displaying csvs that the users upload so I have no control over the column headers. It seems weird to impose a restriction "children is not a valid column header" since that is not a standard restriction.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31351#issuecomment-878021021

https://ant.design/components/table/#components-table-demo-tree-data
