### ISSUE TITLE
【Form】onFieldsChange validating always be false

### ISSUE THREAD

**Issue by kaichii** [ant-design/ant-design#34400]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ji-ben-shi-yong-antd-4-19-1-forked-8oe94p?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
修改任意字段

### What is expected?
validating true => false

### What is actually happening?
validating always be false

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | >= 16.14.0 |
| System | macOS 版本12.0.1（版号21A559） |
| Browser | Chrome 99.0.4844.51 (正式版本) (arm64)  |

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-19-1-forked-mvbhoq?file=/index.js

快速连续在 username 里输入，同时观察控制台输出。

> 注：第一次输入时 validating 会是 false，因为 onFieldsChange 触发时，只是值改变，还没有进入校验中状态。

**Comment by kaichii** [comment]
> 

逐字更改时只会触发两次 onFieldsChange, validating 都是 false，这和文档上的三次触发 false -> true -> false 不一致
