### ISSUE TITLE
[DatePicker] value should has higher priority than defaultPickerValue

### ISSUE THREAD

**Issue by boomler** [ant-design/ant-design#34404]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3412s8?file=/index.js)

### Steps to reproduce
open panel

### What is expected?
panel's month is 2021-01, and I can see my selection.

### What is actually happening?
panel's month is 2022-01, and I cannot see my selection.

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | All |
| System | All |
| Browser | all |

**Comment by boomler** [comment]
Does Antd has the ability to control pickerValue?
If yes, I think such behavior is reasonable. 

But in my case, I only want to give a suggestion time to help user to choose. After they already have their choice, defaultPickerValue should be ignored.

**Comment by shuheen** [comment]
Doesn't look like an issue to me.

If I am not getting wrong. this is what you want. https://codesandbox.io/s/antd-reproduction-template-forked-k42dnd
Actually, you have hardcoded the value of date-picker that's why it was not reflecting the change

**Comment by MadCcc** [comment]
Need more help?

**Comment by boomler** [comment]
@shuheen  Maybe not.
This point is behavior of `defaultPickerValue`.  
When a date-picker is not giving value, the picker panel will display current month. I want use defaultPickerValue to make picker panel to display  a special/ meaningful month, like the past month, the end of this year, or some other things.

But after I have picked a value,  when I open panel again, I should see my selection. This is quite like MUI's `defaultCalendarMonth`: https://codesandbox.io/s/basicdatepicker-material-demo-forked-pb73xj

cc: @MadCcc

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行处理。

如果有任何问题，欢迎随时创建新的 issue :)
