### ISSUE TITLE
Select onChange方法 在form中使用 有破坏性

### ISSUE THREAD

**Issue by zdxxxxxx** [ant-design/ant-design#3441]
- antd 版本:2.0
- 操作系统及其版本:win10
- 浏览器及其版本:chrome最新

`
constructor(){
        super();
        this.state={
            status:1
        }
    }
toggle(){
        let status = this.state.status==1?0:1;
        this.setState({
            status:status
        })
    }
render(){
        const { getFieldDecorator } = this.props.form;
        return (
            <Form>
                <FormItem
                    label="免费期限"
                    labelCol={{ span: 6 }}
                    wrapperCol={{ span: 14 }}
                    >
                    <Col span="8">
                        {getFieldDecorator("select",{
                                initialValue:this.state.status
                            }
                        )(
                            <Select size="large">
                                <Option value="0">0</Option>
                                <Option value="1">1</Option>
                            </Select>
                        )}
                        <Select value={this.state.status} size="large">
                            <Option value="0">0</Option>
                            <Option value="1">1</Option>
                        </Select>
                    </Col>
                </FormItem>
                <Button onClick={this.toggle.bind(this)}>toggle</Button>
            </Form>
        )
    }
`

现象:form中的select 选择完后 setState就不影响from的select了

**Comment by afc163** [comment]
代码无法阅读。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3311#issuecomment-252025039
