### ISSUE TITLE
Typescript complains about the align prop in the Typography.Title component

### ISSUE THREAD

**Issue by Billmike** [ant-design/ant-design#34417]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/missing-title-props-in-ts-qeg1bc)

### Steps to reproduce
1. Import the Typography component from antd
2. Use the Title component, and add the align prop to it.
3. Set the value of the align prop to center.
4. The title text is aligned to the center, but Typescript complains about the align prop

### What is expected?
The text should be aligned to the center, and Typescript should not complain about the align prop

### What is actually happening?
The text is aligned to the center, but Typescript complains about the align prop

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Version 98.0.4758.102 (Official Build) (arm64) |

**Comment by afc163** [comment]
There is no `align` prop in Typography.
