### ISSUE TITLE
Dropdown menu is truncated in table for last column

### ISSUE THREAD

**Issue by aleksey-10** [ant-design/ant-design#34413]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-mestorf-sosmfb?file=/src/App.js)

### Steps to reproduce
Hover on any "actions" button. Menu is not aligned correctly

### What is expected?
The menu automatically aligns and fits completely on the page

### What is actually happening?
Looks like dropdown always has a "bottomLeft" placement

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome/99.0.4844.51 |

---
It was ok in previous versions

**Comment by aleksey-10** [comment]
@shuheen check the last row

![gif](http://g.recordit.co/u5p24DXP6N.gif)

**Comment by MadCcc** [comment]
Fixed https://github.com/ant-design/ant-design/pull/34390
