### ISSUE TITLE
Array string of value Select Antd got undefined

### ISSUE THREAD

**Issue by LuongLegend** [ant-design/ant-design#34416]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/LuongLegend/pen/abVeJQa?editors=0011](https://codepen.io/LuongLegend/pen/abVeJQa?editors=0011)

### Steps to reproduce
Open select choose Option when value is an array of string [Jack(101)]. 

### What is expected?
The received value is an array. not undefined.

### What is actually happening?
Value received is undefined not an array of string. Please check!. I'm sure It is a bug.

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | React 17.0.2 |
| System | Window 10 |
| Browser | Chrome/99.0.4844.51 |

**Comment by afc163** [comment]
Select value don't support array type, please transform it to string.
