### ISSUE TITLE
Input 'setValue' not working after version 4.19.0

### ISSUE THREAD

**Issue by eduardobalbo** [ant-design/ant-design#34425]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focus-antd-4-19-1-forked-w6lu7c?file=/index.tsx)

### Steps to reproduce
Change antd to version 4.19.0 and the setValue property won't work anymore.

### What is expected?
To work like it did on versions prior to 4.19.0.

### What is actually happening?
Not working and thrwoing the error:
Property 'setValue' does not exist on type 'InputRef'.

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | react: 17.0.2 |
| System | Windows 10 |
| Browser | Brave |

---
On one of my components I can't use state to control the value of the input, so using refs and this property 'setValue' was the only way I could achieve what I needed on this case.

I saw on the releases notes of 4.19.0 that the Input component got refactored from a 'class component' to a 'functional component', maybe it's because of this? 

Is there any way to implement 'setValue' on 4.19.0, or any workarounds?

I tried using DOM directly to solve this and failed, so any help is appreciated.
Thanks.

**Comment by afc163** [comment]
We refactor Input to function component. And you should not depend on internal method in class component instance other than `focus` `blur` which we provide in our doucmentation.

Please control `value` in React's way.

**Comment by meetall** [comment]
Hi, what is the React's way to control the value? I'm also trying to use the ref to update the value but it doesn't work.

This the code I'm trying https://codepen.io/fibbers/pen/KoEGoO?editors=0010 

Please suggest if there is a workaround to set the value

**Comment by gnahzknarf** [comment]
try antInputRef.current.input.value = "xxx";

**Comment by danaoairuike** [comment]
> try antInputRef.current.input.value = "xxx";

not working either



Ant Design does not follow any widely accepted conventions. It's "Ali Smell", which smells. 👎

**Comment by danaoairuike** [comment]
> try antInputRef.current.input.value = "xxx";

And this is weird too. You would expect `antInputRef.current` is the native input itself, but no, `antInputRef.current.input` is the native input. It smells really bad.
