### ISSUE TITLE
The title text is not selected in the Tooltip drop-down box

### ISSUE THREAD

**Issue by JayMo666** [ant-design/ant-design#34426]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ji-ben-antd-4-19-1-forked-254b37?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Open the re-link and try to uncheck the title text in the Tooltip in select

### What is expected?
The title text of the tooltip in select can be selected

### What is actually happening?
The title text for tooltip in select cannot be selected

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 16.14.0 |
| System | Mac 12.0.1 |
| Browser | Chrome V 98.0.4758.80 |

**Comment by MadCcc** [comment]
`onMousedown` event on OptionList is handled with `preventDefault` to make Select not blur. 
In your case, you can apply `stopPropagation` to tooltip title like this:
```diff
<Select defaultValue="lucy" style={{ width: 120 }} open>
      <Option value="jack">
-       <Tooltip title="prompt text" visible>
+       <Tooltip title={<div onMouseDown={(e) => e.stopPropagation()}>prompt text</div>} visible>
          <span>Tooltip will show on mouse enter.</span>
        </Tooltip>
      </Option>
      <Option value="lucy">Lucy</Option>
    </Select>
```
