### ISSUE TITLE
Numbers are rounding after 17 digits or more in <InputNumber />

### ISSUE THREAD

**Issue by charles-otto** [ant-design/ant-design#34424]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-form-wrapped-inputnumber-verification-t8beo3?file=/index.js)

### Steps to reproduce
1) Add an InputNumber component inside a Form component.
2) Enter any number which has 17 digits or more in the input field.
3) Observe that the number automatically rounds.

### What is expected?
The number is not expected to round itself.

### What is actually happening?
Numbers which are 17 digits or longer are automatically rounding.

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 16.13.1 |
| System | Ubuntu 20.04.2 LTS |
| Browser | 92.0.4515.131 (Official Build) (64-bit) |

---
This issue does not occur when using a standalone InputNumber component that is not wrapped in an AntD Form.  

See reference example: https://codesandbox.io/s/antd-inputnumber-without-antd-form-ukw4py?file=/index.js

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32120
