### ISSUE TITLE
官方文档关于 antv 可视化部分内容补充

### ISSUE THREAD

**Issue by promise6512** [ant-design/ant-design#34427]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antv 中新增了 X6 XFlow，官方文档中没有介绍。而且 ant-designt-charts 被称为 G2Plot React 版 并不合适
文档位置：https://ant.design/docs/spec/visual-cn

### What does the proposed API look like?
新增关于 X6 XFlow 的介绍，修改对于 ant-designt-charts  的描述
clone 下来自己写了一下，但是没权限 pr。
![demo](https://gw.alipayobjects.com/mdn/rms_75bed3/afts/img/A*g9TwQrOrn_YAAAAAAAAAAAAAARQnAQ)

**Comment by MadCcc** [comment]
pr 没有权限限制，fork 就好。

**Comment by afc163** [comment]
直接来 PR 吧
