### ISSUE TITLE
[Pagination] pageSize 切换器 在旧版本浏览器上显示与新版不一致

### ISSUE THREAD

**Issue by kkkisme** [ant-design/ant-design#34420]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination-cn/#components-pagination-demo-basic](https://ant.design/components/pagination-cn/#components-pagination-demo-basic)

### Steps to reproduce
打开官方文档网址

### What is expected?
1、pageSize 切换器 文本显示完整

### What is actually happening?
1、pageSize 切换器 文本显示不完整，出现省略号

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 17 |
| System | windows 11 |
| Browser | Chrome 70 |

---
chrome 70 是有问题， 大概90 以上是正常的
chrome 101
![image](https://user-images.githubusercontent.com/18638401/157643697-4bf4bcdd-3b0e-4cf6-8f66-f30a1941f996.png)

chrome 70
![image](https://user-images.githubusercontent.com/18638401/157643870-3f2b9be0-3e00-42ee-af0a-78615f5a9566.png)

**Comment by afc163** [comment]
Chrome 老版本不再支持。
