### ISSUE TITLE
Dropdown  如不指定placement 不会根据所在位置及屏幕 进行自适应显示

### ISSUE THREAD

**Issue by VanLee1212** [ant-design/ant-design#34435]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Dropdown  如不指定placement 不会根据所在位置及屏幕 进行自适应显示

### What does the proposed API look like?
Dropdown  不指定placement  根据所在位置及屏幕 进行自适应显示

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/34413

**Comment by VanLee1212** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
