### ISSUE TITLE
Input Textarea 在 Form 内使用有bug, 无值，输入值后，点击外部使 Textarea 失焦，然后再点击删除，不会自动获焦

### ISSUE THREAD

**Issue by SCWR** [ant-design/ant-design#34431]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-19-1-forked-ld80ud?file=/index.js)

### Steps to reproduce
在表单里 Textarea 输入值后，点击外部使 Textarea 失焦，然后再点击删除

### What is expected?
自动获取焦点

### What is actually happening?
不会自动获焦

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 16.14.0 |
| System | Mac 12 |
| Browser | Chrome 99 |

**Comment by SCWR** [comment]
@MadCcc   可以跟进一下 #34728 吗

**Comment by SCWR** [comment]
hello

**Comment by MadCcc** [comment]
我继续跟进下

**Comment by SCWR** [comment]
谢谢你们的工作和帮助！！！
