### ISSUE TITLE
Unable to set focused element from the dropdown in Antd Autocomplete Input box

### ISSUE THREAD

**Issue by jayanthbondi** [ant-design/ant-design#34430]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-antd-4-19-1-forked-zfhjrk?file=/index.js)

### Steps to reproduce
1) Start typing in autocomplete Input
2) Focus the dropdown element using down and up arrow.

### What is expected?
When an element from the dropdown is focused, it should automatically be populated in the input box.
like Google search autocomplete / Flipkart autocomplete

### What is actually happening?
Focused element is not replaced in the Input Box.

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | 16.14.0 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by jayanthbondi** [comment]
![image](https://user-images.githubusercontent.com/35721161/157811259-f15c1b26-33f8-4aad-9f26-4083e4dffda6.png)

I want this behaviour in antd autocomplete, focused element from the dropdown should be set in the input box.

**Comment by MadCcc** [comment]
By pressing `Enter` you could get what you want.

**Comment by jayanthbondi** [comment]
Hi @MadCcc , yes.
But I have a different use case, can we replicate the same what we have in Google Search autocomplete?
