### ISSUE TITLE
Fix initial document title for better SEO

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3445]
https://github.com/ant-design/ant-design/blob/gh-pages/components/back-top/index.html#L7

It should be `Backtop - Ant Design`

**Comment by kvetoslavnovak** [comment]
https://github.com/ant-design/ant-design/pull/3443 - https://github.com/ant-design/ant-design/pull/3443/files

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/0920efb87f4d0bf5efa7359c5121298a10595640

That was only one little problem, this need to upgrade [bisheng](https://github.com/benjycui/bisheng/) for each entry html file.

**Comment by afc163** [comment]
Default content could be rendered into entry html too for better SEO.

https://www.google.co.jp/search?newwindow=1&q=%E5%9C%A8%E4%B8%AD%E5%8F%B0%E4%BA%A7%E5%93%81%E7%9A%84%E7%A0%94%E5%8F%91%E8%BF%87%E7%A8%8B%E4%B8%AD%EF%BC%8C%E4%BC%9A%E5%87%BA%E7%8E%B0%E4%B8%8D%E5%90%8C%E7%9A%84%E8%AE%BE%E8%AE%A1%E8%A7%84%E8%8C%83%E5%92%8C%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%EF%BC%8C%E4%BD%86%E5%85%B6%E4%B8%AD%E5%BE%80%E5%BE%80%E5%AD%98%E5%9C%A8%E5%BE%88%E5%A4%9A%E7%B1%BB%E4%BC%BC%E7%9A%84%E9%A1%B5%E9%9D%A2%E5%92%8C%E7%BB%84%E4%BB%B6%EF%BC%8C%E7%BB%99%E8%AE%BE%E8%AE%A1%E5%B8%88%E5%92%8C%E5%B7%A5%E7%A8%8B%E5%B8%88%E5%B8%A6%E6%9D%A5%E5%BE%88%E5%A4%9A%E5%9B%B0%E6%89%B0%E5%92%8C%E9%87%8D%E5%A4%8D%E5%BB%BA%E8%AE%BE&bav=on.2,or.&cad=b&biw=1435&bih=814&dpr=2&ech=1&psi=8CwYWOz3L8fz8QWc8qWgBg.1477979404316.3&ei=8CwYWOz3L8fz8QWc8qWgBg&emsg=NCSR&noj=1

Now google can't index `ant.design` page content.

**Comment by afc163** [comment]
@benjycui

**Comment by benjycui** [comment]
如果只是为了 title 的话，Google 是不需要任何调整的，现在已经能正确展示 title 了 https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:ant.design

![image](https://cloud.githubusercontent.com/assets/3580607/25212305/292a8520-25bc-11e7-8df6-41171349126f.png)

**Comment by benjycui** [comment]
所以现在 bisheng 加 SSR 的目的主要是为了初次加载速度，而非 SEO。
