### ISSUE TITLE
filterDropdown is misaligned in Table header

### ISSUE THREAD

**Issue by pterblgh** [ant-design/ant-design#34456]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-antd-4-19-1-forked-enzq3x)

### Steps to reproduce
Click on the magnifier (search) icon of the first column.

### What is expected?
The content of the dropdown would be placed to "bottom-left" compared to the table row header.

### What is actually happening?
The content of the dropdown is placed "bottom-right" which makes the content partially invisible (aka "floating" outside of the viewport) resulting in reduced usability of the component/functionality.

| 4.18.9  | 4.19.1 |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/11005750/157904629-1e37e4cc-b865-40da-ad7b-236fec7e2b73.png) | ![image](https://user-images.githubusercontent.com/11005750/157904244-eef51ca2-a257-4eef-887e-66c15bdc6909.png) |

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 16.14 |
| System | Windows, Mac OS |
| Browser | latest Chrome |

---
This is a regression as the demo perfectly works with `4.18.9` - you can test this by changing the version number in the package.json file of the CodeSandbox project and re-build the project. 

In the demo, the container div is on purpose set to be "narrow" to be able to demonstrate the wrong content positioning. Tried to look into `rc-table` and `rc-dropdown` but haven't seen anything obvious in the changelogs of those packages that could cause this behaviour.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/34390
