### ISSUE TITLE
Form.Item change in hasFeedback property blurs current input's focus

### ISSUE THREAD

**Issue by okebinda** [ant-design/ant-design#34458]
Changes introduced in version 4.19.0 affect Form.Item > Input focus. If user input changes the Form.Item `hasFeedback` property then Input focus is lost, interrupting the user while typing.

- [X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qutbge?file=/index.js)

### Steps to reproduce
Create a Form.Item element with a conditional `hasFeedback` property (initially set to false) and set `validateStatus` to "success". Add a child text Input that sets `hasFeedback` to true with some input (length, format, etc.). Type some characters into the Input, and when the `hasFeedback` property changes the Input focus is lost and the user can no longer continue typing in the input without manually refocusing.

### What is expected?
The user should be able to continue entering text into the Input after the `hasFeedback` property has changed.

### What is actually happening?
The Input focus is lost and any text the user types is lost until they refocus on the Input field.

| Environment | Info |
|---|---|
| antd | 4.19.0 |
| React | 17.0.2 |
| System | Node 16.14.0 |
| Browser | Firefox 97 |

---
Works as expected in version 4.18.9.

**Comment by MadCcc** [comment]
Since 4.19.0, `hasFeeback` is implemented by adding suffix in Input/InputNumber，so you can check this: https://ant.design/components/input/#Why-Input-lose-focus-when-change-prefix/suffix

**Comment by MadCcc** [comment]
In your case, you can control `validateStatus` instead.

**Comment by okebinda** [comment]
I see, thank you for the reply.

In my case I am controlling both `hasFeedback` and `validateStatus` on some forms. Most forms in my application use the default error styling (red border, error message below) with no `hasFeedback` X icon and no success feedback until submission with a simple alert (i.e.: I use the default Form feedback). However, some forms are enhanced with dynamic feedback as the user types to improve usability. For example, think of a registration form with a password field - we show a list of criteria (lowercase, uppercase, number, etc.) that gets checked off as the user types and once all criteria is met we show a "success" `hasFeedback` icon. In order to remain consistent with all other forms/inputs, I want to turn off the error `validateStatus` icon if there is an error, but keep the default error styling. If I treat the `hasFeedback` property as immutable, I do not have that option. I must either: remove the success feedback for enhanced inputs; add error feedback to all fields; or accept that some fields will handle errors differently than others.

Anyway I can make that choice and continue with a feature that is slightly less user friendly than it was previously. But I want to point out two other things:

1. I doubt that I am the only one who is affected by this change (which I consider a breaking change), and some of those won't find and fix this problem before it affects their users, who will be entering incorrect data into input fields through no fault of their own, which is frustrating and reflects poorly on the software/business they are using.
2. I would argue that having `hasFeedback` re-render the Input and losing focus goes against the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for the developer (and the user if the developer doesn't implement as intended). Plainly stated: why can I control `validateStatus` but not `hasFeedback`? And if I do, why does it seem to work, but actually negatively affects the user experience? Seems arbitrary (and undocumented). If it's truly important to not change that property over the lifecycle of the input, then wouldn't it make more sense to create a different component (e.g.: `Form.ItemWithFeedback`) to make it extremely clear what the intent is?

**Comment by sshwsfc** [comment]
I have the same issues.

**Comment by kishanPrajapat-Forcebolt** [comment]
Hi @okebinda, Have you found any solution regarding this? I'm using antd InputNumber and hasFeedback prop. When I've removed the hasfeedback prop then it is working fine but with that, it is losing focus!
Thanks @okebinda in advance.

**Comment by roninCode** [comment]
I am also running into this issue, where going from true -> false for `hasFeeback` is blurring the antd Input component. 

As @okebinda mentioned I also want to be able to control both `validateStatus` and `hasFeedback` as there are times when I want the icon with validation and times I don't want the icon with validation.

I believe this is still an issue and is causing usability issues in my app.

**Comment by afc163** [comment]
@roninCode Chould you provide a reproduce?

**Comment by roninCode** [comment]
@afc163 honestly the initial CodeSandbox posted by @okebinda demonstrates this well.

If you:
1) go to: https://codesandbox.io/s/antd-reproduction-template-forked-qutbge?file=/index.js
2) type 3 characters in the input
3) you will see that the success icon appears (that's good)
4) BUT the input becomes unfocused (that's bad)
5) you are forced to click back into the input to continue typing

**Comment by MadCcc** [comment]
@roninCode Try to make hasFeedback stable: https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qutbge?file=%2Fpackage.json%3A3%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpicf5ow00073b6mmp27x3si%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpicf5ow00033b6mrog5557z%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpicf5ow00043b6mb0iqyr0q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpicf5ow00063b6mmvl1q39l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpicf5ow00033b6mrog5557z%2522%253A%257B%2522id%2522%253A%2522clpicf5ow00033b6mrog5557z%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpicl2m4007k3b6m1t90362x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpicl2m4007k3b6m1t90362x%2522%257D%252C%2522clpicf5ow00063b6mmvl1q39l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpicf5ow00053b6mea0zvc3i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpicf5ow00063b6mmvl1q39l%2522%252C%2522activeTabId%2522%253A%2522clpicf5ow00053b6mea0zvc3i%2522%257D%252C%2522clpicf5ow00043b6mb0iqyr0q%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpicf5ow00043b6mb0iqyr0q%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by roninCode** [comment]
@MadCcc I looked at your example and it seems like when you say "make hasFeedback stable" you are saying "do not allow hasFeedback to have dynamic values". 

To me that sounds like a workaround for an actual bug - something it looks like you already solved for in InputNumber... but not in Input (https://github.com/ant-design/ant-design/pull/45632).

What if you `only` want the form item to have feedback if there is an error? 
Having dynamic values for hasFeedback is important.

**Comment by roninCode** [comment]
@afc163 / @MadCcc can we please re-open? 

Per https://github.com/ant-design/ant-design/issues/34458#issuecomment-1834421340 this is an actual bug (one that @MadCcc solved for in InputNumber just not Input)

**Comment by faizankhan1995** [comment]
Facing same issue, was this resolved ?
