### ISSUE TITLE
Select 支持自定义 selection item 的 label 或者 option list 的 label

### ISSUE THREAD

**Issue by momoworking** [ant-design/ant-design#34469]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求是 option list 的 label 和 选中后在 input 中显示的 label 不一致。如下列列表里是 1:00 (1 hr), 2:00 (2hrs)，选中后只显示 1:00。  
现在 selection item 的 label 和 option list 的 label 是一致的，是否可以可以提供一个功能来区分

### What does the proposed API look like?
<Select formatSelectionLabel={(option) => option.value   "hello world"} />
or 
<Select renderSelectionLabel={(option) => option.value   "hello world"} />

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#components-select-demo-option-label-prop
