### ISSUE TITLE
Select Ref scrollTo 函数参数不支持 scrollTo({ index: 1, align: 'top' })，和定义不符

### ISSUE THREAD

**Issue by momoworking** [ant-design/ant-design#34468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1qhx10)

### Steps to reproduce
点击例子的两个 scrollTo 的 button 就能看到效果不一致

### What is expected?
scrollTo 支持 `scrollTo({ index: 20, align: 'top' })`，现在只支持 `scrollTo(20)`

### What is actually happening?
scrollTo({ index: 20, align: 'top' }) 无效

| Environment | Info |
|---|---|
| antd | 4.18.9 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome/98.0.4758.109 |

**Comment by isbik** [comment]
@momoworking  Hi, [https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo](scrollTo) has't `index` option

**Comment by momoworking** [comment]
@isbik 

- https://github.com/react-component/select/blob/master/src/BaseSelect.tsx#L69
- https://github.com/react-component/virtual-list/blob/master/src/List.tsx#L35

**Comment by ManiacHanz** [comment]
这个问题在^修复了，如果需要麻烦合并一下😊

**Comment by BluesVN** [comment]
上述例子没有用到OptGroup分组，如果使用了分组，index该如何传。分组OptGroup的index 和Option是同级吗？

**Comment by BluesVN** [comment]
请问这个功能预计在antd 哪个版本会出现？🙏
