### ISSUE TITLE
RangePicker 能否实现时间范围的限制

### ISSUE THREAD

**Issue by oMaten** [ant-design/ant-design#3446]
#### 发生问题的环境是：

- antd 版本: 1.8.0
- 操作系统及其版本: darwin 15.6.0
- 浏览器及其版本: chrome 53.0

#### 您做了什么？

引入 antd 的 RangePicker 

#### 您期待的结果是：

通过 disabledDate 实现 相对于当前所选日期的相对时间范围功能，如：时间范围是1个月，那么用户选择 03/01 之后第二次选择范围只能限定在 03/01 (+/-) 1个月。 

#### 实际上的结果是：

disabledDate 回调函数只会在用户 hover 日期单位框时触发，无法得知用户第一次按下选择的日期，希望给出一个 callback 能在用户第一次点击选中某一天时触发。

目前只能通过官网上给出的 DatePicker 组件自行通过 state 的形式封装一个具有日期限制功能的 RangePicker。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/3568

**Comment by zhenyong** [comment]
限制一段时间的方式

```javascript
 ...
disabledDate(date, b, c) {
  if (start) {
    return date.diff(start, 'days') > 30;
  }
  return false;
},
onCalendarChange(dates) {
  if (dates.length === 1) {
    start = dates[0];
  } else {
    start = null;
  }
}
...
```

**Comment by allinshang** [comment]
求解决方法。好像是只能自己封装了。

**Comment by dearpeach** [comment]
限制了日期，怎样限制时间呢？
disabledTime返回的都是类似这样的返回值
return {
    disabledHours: () => range(0, 24).splice(4, 20),
    disabledMinutes: () => range(30, 60),
    disabledSeconds: () => [55, 56],
  };

那如果要限制 时间内 例如：15点内的时间 这种方式怎样设置呢？

**Comment by NuliNuli** [comment]
@CoderPoet 这个需求实现了吗？我也遇到了同样的问题

**Comment by NuliNuli** [comment]
@oMaten 请问如何封装呢？可以给提供下思路吗？

**Comment by capslocktao** [comment]
this.state.value为当前的时间段范围
```
disabledDate = date => {
    return (date.diff(this.state.value[1], 'days') < -2) || (date && date > this.state.value[1]); // 保证可选择的时间段范围只有两天
  }
```

**Comment by YUFENGWANG** [comment]
@capslocktao 正解。。。。

**Comment by boxiaowpl** [comment]
用自定义日期范围选择的方式，可以实现这个需求：https://ant.design/components/date-picker-cn/

**Comment by collinsyu** [comment]
> @zhenyong 你这个方法好像不行把。目前的range组件 只能两个都选好之后才会去触发change回调。因此你的这个dates.length===1是永远走不进来的。
> ![image](https://user-images.githubusercontent.com/19374680/40465918-b2f3351c-5f55-11e8-937b-0ac394a185c1.png)

用这个方法`handleCalendarChange`

**Comment by big-tutu** [comment]
@zhenyong 我也是和你一样的想法去做时间单位的动态限制，但是handleCalendarChange方法中的参数是默认值，不会变，你有解决么？

**Comment by Arlisol** [comment]
> @zhenyong 我也是和你一样的想法去做时间单位的动态限制，但是handleCalendarChange方法中的参数是默认值，不会变，你有解决么？

onCalendarChange这个事件我试了下，在只选择一个时间时dates会是一个长度为1的数组，前后都选择时长度为2。所以我想应该可以用dates.length === 1这个条件来判断只选择了开始时间吧，之后再去处理disabledTime。感觉逻辑上应该可以，但是还没有具体尝试，你可以尝试一下。

**Comment by samous0726** [comment]
https://github.com/samous0726/dynamic-antd-rangepicker

npm i dynamic-antd-rangepicker --save

**Comment by l4dfire** [comment]
disabledTime这个设计得很难用
不能给一个和disableTime不共存的参数来表示哪些范围的时间段可用么（精确到时分秒)

**Comment by clayJa** [comment]
```
  disabledDate = (date:any) => {
    const { rangeDate } = this.state
    if(!rangeDate) {
      return
    }
    if(rangeDate[0] && date.diff(rangeDate[0], 'days') >= 90) {
      return true
    }
    if(rangeDate[1] && date.diff(rangeDate[1], 'days') <= -90) {
      return true
    }
    return false
  }
  onCalendarChange = (dates:any) => {
    this.setState({
      rangeDate: dates
    })
  }
```

**Comment by Flcwl** [comment]
为什么 disableDate 不暴露 type 标识下当前禁用逻辑是 start 还是 end。

**Comment by carolin-violet** [comment]
onCalendarChange 我这边试了下也是只有开始时间那边选了点了ok后才会调用呀，直接点到结束时间的选择框上选择不会调用
