### ISSUE TITLE
Input allowClear Type fail with document

### ISSUE THREAD

**Issue by phuhd-0935** [ant-design/ant-design#34476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input/#API](https://ant.design/components/input/#API)

### Steps to reproduce
Access to https://ant.design/components/input/#API .
Then, at allowClear API, focus to Type column.
Finally, at your source code, inspect to /node_modules/antd/lib/input/Input.d.ts .

### What is expected?
In Input.d.ts, change InputProps comformable with document

### What is actually happening?
Input document is wrong with Input.d.ts type.
In Document, API allowClear allows boolean or object ({ clearIcon: React.ReactNode}).
But, In Input.d.ts, interface InputProps does not allow it, only boolean type (allowClear?: boolean;).

| Environment | Info |
|---|---|
| antd | 4.18.8 |
| React | 17 |
| System | Node 14 |
| Browser | Chrome 92 |

**Comment by MadCcc** [comment]
`{ clearIcon: React.ReactNode}` only allowed in version after 4.19.0
