### ISSUE TITLE
RangePicker组件open属性，通过js手动控制时，日期需要确认三次，panel 才会关闭

### ISSUE THREAD

**Issue by xueyang996** [ant-design/ant-design#34471]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-pwspsv](https://stackblitz.com/edit/react-pwspsv)

### Steps to reproduce
RangePicker组件
1、设置defaultOpen为true，此时日期需要确认三次，才可以关闭panel。
2、open属性通过js手动控制时，日期同样需要确认三次，才可以关闭panel

### What is expected?
RangePicker组件open属性，通过js手动控制时，日期确认两次，panel 就会关闭

### What is actually happening?
RangePicker组件open属性，通过js手动控制时，日期需要确认三次，panel 才会关闭

| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 17.0.2 |
| System | mac |
| Browser | Chrom 98.0.4758.109 |

**Comment by afc163** [comment]
录个屏，我不知道自己测试的效果和你看到的是否一致。

**Comment by afc163** [comment]
确实有问题，感谢反馈，合并到同类问题 [24083](https://github.com/ant-design/ant-design/issues/24083)

**Comment by xueyang996** [comment]
> 录个屏，我不知道自己测试的效果和你看到的是否一致。


https://user-images.githubusercontent.com/14260239/158053735-23a2ba8f-7c75-452b-8d33-b50b1c13325f.mov

**Comment by tingyugetc520** [comment]
我也遇到了这个问题，后面没办法把交互方案改掉了😂
