### ISSUE TITLE
Is it possible to use Popover inside of Popover?

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3448]
I can't get required result :(

I have popover and inside of popup i have another popover with Select and etc.

**Comment by afc163** [comment]
http://codepen.io/anon/pen/rrkYYb?editors=0011

There are some style conflict problems now.

**Comment by plandem** [comment]
i'm talking about a bit differ case, will add demo later.

**Comment by plandem** [comment]
ok, here is example:
http://codepen.io/anon/pen/jrvKjk?editors=0011

i can get correct result for filter of tag's popover.

**Comment by ifokeev** [comment]
I have the same problem. Want to make nested popovers that not to close on mouseLeave.

**Comment by benjycui** [comment]
Add `getPopupContainer={triggerNode => triggerNode.parentNode}` to `Popover`: 

```jsx
<Popover getPopupContainer={triggerNode => triggerNode.parentNode}>
    <Button icon="filter"/>
</Popover>
```

@ifokeev @plandem if it's OK, close this issue, thanks.

**Comment by ifokeev** [comment]
Amazing. I was writing my own bicycle, but your decision it what I really need.

**Comment by plandem** [comment]
Well, it works except one issue - width of parent container:
http://codepen.io/anon/pen/jrvKjk?editors=0011

as you can see popover inside of popover in that case can't be wider than parent :(

**Comment by plandem** [comment]
Have you look at my example at codepen?

**Comment by plandem** [comment]
I mean you can try by self :) I will try too - just need to get to computer

**Comment by benjycui** [comment]
Yep, this two problem is exist... https://github.com/ant-design/ant-design/issues/3448#issuecomment-255990256
