### ISSUE TITLE
@types/antd 现在的版本还是for antd0.12.1的,能否更新下?

### ISSUE THREAD

**Issue by shynome** [ant-design/ant-design#3449]
发生问题的环境是：

antd 版本:2.0.0
操作系统及其版本:w10 64
浏览器及其版本:谷歌 53.0.2785.143 m

您做了什么？
`npm install @types/antd`

您期待的结果是：
获得良好的提示

实际上的结果是：
有一些组件出现了错误提示

可重现的在线演示

**Comment by afc163** [comment]
不需要用这个了，2.0 之后官方版本直接提供了 type definitions。

另外，旧版本也确实没有精力维护了，尽快升级吧。

**Comment by afc163** [comment]
目前 antd@2.0 的 definitions 在 ts@2.0.3 下应该有一些报错，https://github.com/ant-design/ant-design/pull/3439 合并之后应该就能修复，欢迎持续关注和帮忙 review 。
