### ISSUE TITLE
OptGroup title attribute

### ISSUE THREAD

**Issue by rkhaslarov** [ant-design/ant-design#34496]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Please add title attr for optgroup component for showing the standard browser tooltip, it's automatically added to Select.Option component, but not for optgroup.

### What does the proposed API look like?
<Select.OptGroup key={} label={} title={}> or maybe label can be converted automatically.

**Comment by cielu** [comment]
这个Select.Option的，我也建议，像 element UI 里面那种写法，value可以存对象，在外面指定一下 label用对象的哪个key，这样就很nice，现在的用起来真是。。。

**Comment by rkhaslarov** [comment]
Thanks for quick fix! When it will be available in release?

**Comment by rkhaslarov** [comment]
Thanks a lot!
