### ISSUE TITLE
tree-select 的下拉菜单宽度不正确

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#34495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-19-2-forked-17ylhi?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/ji-ben-antd-4-19-2-forked-17ylhi?file=/index.js

### What is expected?
记录下

### What is actually happening?
记录下

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | os |
| Browser | chrome |

**Comment by afc163** [comment]
@MadCcc 看看，问题应该是 https://github.com/ant-design/ant-design/issues/33495#issuecomment-1056816606

**Comment by jljsj33** [comment]
无限滚动的问题吧？？？？https://github.com/react-component/virtual-list/blob/eeb7bdb274/src/Filler.tsx#L38

**Comment by jljsj33** [comment]
出现滚动宽度就不对了，，没滚动的宽度是没问题。。。
