### ISSUE TITLE
datepicker 选择一个日期后能否不关闭面板？

### ISSUE THREAD

**Issue by YDJSZY** [ant-design/ant-design#34499]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可自定义扩展日期组件，比如我可在底部加个取消，确定按钮

### What does the proposed API look like?
提供一个参数让面板不关闭，当选择一个日期时

**Comment by huntdream** [comment]
https://ant.design/components/date-picker-cn/#components-date-picker-demo-extra-footer

**Comment by zombieJ** [comment]
通过受控 `open` 管理面板状态
