### ISSUE TITLE
动态主题（实验性）怎么切换到暗黑主题https://ant.design/docs/react/customize-theme-variable-cn

### ISSUE THREAD

**Issue by linjc** [ant-design/ant-design#34502]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
支持暗黑模式下使用antd提供的variable.css

### What does the proposed API look like?
无

**Comment by afc163** [comment]
目前还不支持 #32807

**Comment by linjc** [comment]
@afc163 噢好的，有没有提供类似antd.variable.dark.css的方案，或者用户可否通过现有less自行生成。
