### ISSUE TITLE
Form.Item 里面的 shouldUpdate 方法没有触发

### ISSUE THREAD

**Issue by cielu** [ant-design/ant-design#34500]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
```tsx
<Form.Item
  noStyle
  shouldUpdate={(prevValues, currentValues) => {
    console.log("dsafwjdoisafjodisajf")
    return prevValues.failedRetry !== currentValues.failedRetry
  }}
>
```
就是这玩意，里面的 console.log 都不执行。。之前好像是正常的

### What is expected?
正常执行 console.log

### What is actually happening?
没有执行

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | mac os 12.2.1 |
| Browser | google 99.04844.51 |

**Comment by cielu** [comment]
你让我提供代码，我提供不出来，我用的 ant-design-pro 搞的，我估摸着和他有关系，让我录个视频还可以，搞代码，我搞到那个沙盒里面都不重现。。。用的我真是无话可说

**Comment by yyxTheOracle** [comment]
> 你让我提供代码，我提供不出来，我用的 ant-design-pro 搞的，我估摸着和他有关系，让我录个视频还可以，搞代码，我搞到那个沙盒里面都不重现。。。用的我真是无话可说

你是不是 Form.Item 的标签体里是空的啊，这里应该是有优化，标签体为空就直接没必要执行 shouldUpdate 逻辑了
