### ISSUE TITLE
Cascader搜索时崩溃

### ISSUE THREAD

**Issue by cbozi** [ant-design/ant-design#34505]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-19-2-forked-xu8ozb)

### Steps to reproduce
1. 搜索"1"
1. 点击"1 / 1"
1. 继续搜索"1"

当不同层级的选项有重复的value时会出现

### What is expected?
正常显示搜索结果

### What is actually happening?
页面崩溃，白屏

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | ^17.0.2 |
| System | macOS |
| Browser | Chrome 99.0.4844.51 |

**Comment by cbozi** [comment]
这个问题在rc-cascader 3.4.0修复了，ant design什么时候升级rc-cascader的版本？ @afc163

**Comment by yoyo837** [comment]
> 这个问题在rc-cascader 3.4.0修复了，ant design什么时候升级rc-cascader的版本？ @afc163

下一个MINOR以上版本.
