### ISSUE TITLE
Form.Item里的select样式问题，select宽度不受外部width限制.  Select style in form. Item. Select width is not limited by external width

### ISSUE THREAD

**Issue by carl-lou** [ant-design/ant-design#34512]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-85ee36?file=/index.js)

### Steps to reproduce
第三个form.item   3333的select选择文字长的option
translate: The third form. Item 3333 select selects options with long text

### What is expected?
select宽度不会溢出
translate: Select width does not overflow

### What is actually happening?
select本身宽度超出了col的限制，顶出去了
translate: Select itself is out of the col limit

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | macOS 12.2.1 |
| Browser | chrome 99.0.4844.51 |

**Comment by MadCcc** [comment]
给 Row 添加 `width: 100%` 可以解

**Comment by MadCcc** [comment]
看起来是 `flex` 布局问题，把 Form 的 `layout` 去掉就行了，既然已经用了 Row 用来布局的话，或者反过来只用 Form 的 `layout` 布局。
