### ISSUE TITLE
Dropdown button: unable to navigate in dropdown menu with arrows on Mac

### ISSUE THREAD

**Issue by kpustakhod** [ant-design/ant-design#34520]
- [+] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown/#components-dropdown-demo-trigger](https://ant.design/components/dropdown/#components-dropdown-demo-trigger)

### Steps to reproduce
```
const menu = (
  <Menu>
    <Menu.Item key="0">
      <a href="https://www.antgroup.com">1st menu item</a>
    </Menu.Item>
    <Menu.Item key="1">
      <a href="https://www.aliyun.com">2nd menu item</a>
    </Menu.Item>
    <Menu.Divider />
    <Menu.Item key="3">3rd menu item</Menu.Item>
  </Menu>
);

ReactDOM.render(
  <>
  <Dropdown overlay={menu} trigger={['click']}>
    <Button>Click me</Button>
  </Dropdown>
  </>
  ,
  document.getElementById('container'),
);
```
Navigate with Tab to dropdown button
Press Enter
Try to navigate in dropdown menu with arrows.

### What is expected?
Navigation with arrows works in dropdown menu in ant the same as navigaton with arrows works in rc-dropdown@3.3.3

### What is actually happening?
Functionality from rc-dropdown (https://github.com/react-component/dropdown/pull/196) is not working in ant. Unable to navigate in dropdown menu with arrows.
I see differences in structure of menuRef.current in rc-dropdown and in ant.design:
<img width="1148" alt="Screenshot 2022-03-15 at 14 20 50" src="https://user-images.githubusercontent.com/16884481/158399659-d8bf75c3-a1dc-4467-b569-97c6444288b5.png">
<img width="1148" alt="Screenshot 2022-03-15 at 14 21 00" src="https://user-images.githubusercontent.com/16884481/158399672-07184b9a-eb5f-4ecd-b5e2-9cb1f467e22f.png">

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17 |
| System | macOs |
| Browser | Chrome |

---
This issue is not reproduced on PC

**Comment by zombieJ** [comment]
Hold since I need do something refactor on feature of Menu

**Comment by mellis481** [comment]
@zombieJ Does your comment above mean that some refactoring you're currently doing will address this issue?  If so, is there a PR I can follow to I track when your fix gets released?
