### ISSUE TITLE
lessc 提前编译样式文件报错

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design#34539]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
lessc --modify-var='ant-prefix=ant-v4' --modify-var='iconfont-css-prefix=ant-v4-anticon' node_modules/antd-v4/dist/antd.variable.less client/src/css/_antd-v4.css

### What is expected?
可以正常编译

### What is actually happening?
SyntaxError: Function 'each' is undefined in /Users/xuxing_mac/Desktop/zentrust.cn_frontend/node_modules/antd-v4/lib/input/style/status.less on line  column 1:
each(@input-wrapper-cls, {
.@{value} {

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | MacOS |
| Browser | Chrome |

**Comment by iDestin** [comment]
![image](https://user-images.githubusercontent.com/36811055/169229285-3f7610d5-9ce3-4bae-8e17-6d9945166754.png)
突然遇到一个差不多的问题

**Comment by bigbigmyworld** [comment]
我也遇到了相同的问题

**Comment by bigbigmyworld** [comment]
> > each
> 
> each这个函数报错是因为less版本太低，但是升级less之后又会有新的问题，你可以先尝试升级less试试

less,升级到3.7.0，报错变成了.beziereasingmixin(); inline javascript is not enabled

**Comment by qian-zs** [comment]
我也遇到这个问题了。。。在用 `@ant-prefix: antd@4.x;` 的时候

**Comment by smithyj** [comment]
解决方法，装个别名包就可以解决啦

**Comment by liu-collab** [comment]
> 解决方法，装个别名包就可以解决啦

同求，怎么解决的

**Comment by smithyj** [comment]
> 解决方法，装个别名包就可以解决啦

@guojunhao118 @liu-collab 
安装方法：
`npm i --save less-v4@npm:less@4.1.2`

然后其他在 `package.json` 用的时候：
```
node_modules/less-v4/bin/lessc --js --modify-var='ant-prefix=ant-v4' --modify-var='iconfont-css-prefix=ant-v4-anticon' node_modules/antd-v4/dist/antd.variable.less client/src/assets/css/_antd-v4.css
```
- client/src/assets/css/_antd-v4.css 是你要生成的文件路径
