### ISSUE TITLE
Form的validateTrigger设置为["onChange"]，onFinish还会再触发校验

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design#34533]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-benji-qcs0mw?file=/src/App.tsx)

### Steps to reproduce
1、点击新增类型，当选择的类型id在exist数组中时，validator校验会报错提示“改类型已存在”【改校验主要用于去重】，修改为exist中不存在的类型后，通过校验，将新选择的类型id加入数组。
2、提交表单，再一次触发了validator，validateTrigger明明设置的是onChange，为什么onFinish时仍然触发了一次校验。
3、改为validateTrigger: ["onFinish"]，则只会在onFinish的时候校验

### What is expected?
validateTrigger: ["onChange"]时，只在onChange时校验，onFinish的时候不校验

### What is actually happening?
onFinish的重复触发了校验

| Environment | Info |
|---|---|
| antd | 4.15.5 |
| React | 16.14.0 |
| System | windows10 |
| Browser | chrome91 |

**Comment by Youmyin** [comment]
那为什么表单整体onFinish的时候还会再校验一次呢

**Comment by Youmyin** [comment]
有没有办法在onFinish的时候不触发这个validator呢

**Comment by youngjuning** [comment]
+1
