### ISSUE TITLE
Dropdown: children components lost focus

### ISSUE THREAD

**Issue by tanestila** [ant-design/ant-design#34532]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-j4821u)

### Steps to reproduce
1 Click on first button

2 Click on DatePicker

or 

1 Click on second button

2 Click on Input

3 Try to enter in input field

### What is expected?
1 opened DatePicker dropdown

or

2 entered text

### What is actually happening?
DatePicker and Input lost focus

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | react 17.0.2 |
| System | Windows 10 pro 1903 |
| Browser | Chrome 99.0.4844.51 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-disappears-when-I-click-another-popup-component-inside-it.-How-do-I-resolve-this

**Comment by afc163** [comment]
Works on 4.18.x: https://codesandbox.io/s/antd-reproduction-template-forked-bwqig5?file=/index.js

@MadCcc It is broken since https://github.com/react-component/dropdown/pull/196

**Comment by afc163** [comment]
It seem to be same issue as #34520
