### ISSUE TITLE
Transfer，支持可控的操作，能设置选项左移或者右移的disabled

### ISSUE THREAD

**Issue by driftee** [ant-design/ant-design#34541]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Transfer可能需要将某些左边的选项移动到右边一棵二级的树(Tree)的某个父节点的子节点之中，这时候需要同时选择了左边的一些选项和右边的一个父节点节点，才能执行选项的转移。而目前只要选择了左边的一些选项就能让右移的操作可用。选项是否能右移或者左移
目前是完全不可控的。
### What does the proposed API look like?
能够完全控制选项左移和右移是否可用，比如
```js
<Transfer operationDisabled={[operationToRightDisabled, operationToLeftDisabled]} {...restProps} />
```

**Comment by afc163** [comment]
We should support https://github.com/ant-design/ant-design/issues/25815

**Comment by afc163** [comment]
Duplicate of #25815
