### ISSUE TITLE
Barcode Scanner

### ISSUE THREAD

**Issue by JennyLeung030** [ant-design/ant-design#34551]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I hope ant design can support using barcode scanner in website

### What does the proposed API look like?
Provide barcode scanner api to detect value from barcode

**Comment by afc163** [comment]
I don't think barcode scanner is what UI component should do.

**Comment by JennyLeung030** [comment]
I try to add some barcode scanner API in the ant desin project, it will cannot detect div id element for barcode. Such as: https://github.com/zxing-js/library and https://github.com/mebjas/html5-qrcode, These way all cannot found id element. I was tried in the project, which cannot found the id element all. I added the div element and named it.
