### ISSUE TITLE
Popover does not work for Checkbox or Radio

### ISSUE THREAD

**Issue by Centaur** [ant-design/ant-design#3455]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: 
- 浏览器及其版本:
#### 您做了什么？

在 Checkbox 或 Radio 外面包一层 Popover

#### 您期待的结果是：

鼠标移到 Checkbox或Radio 上时显示 Popover
#### 实际上的结果是：

不显示 
#### 可重现的在线演示

https://jsfiddle.net/0camhs5r/3/

**Comment by yesmeck** [comment]
@afc163 这个我来看看吧

**Comment by afc163** [comment]
👌，Checkbox 外层需要传递一些参数过去。

**Comment by yesmeck** [comment]
其实不止`Checkbox`和`Radio`，像`DatePicker`、`Rating`等等没有把`props`传给组件里最外层 DOM 标签的都不能直接放在 `Popover` 里，我的建议是自己在外面套一层原生的 DOM 标签：

```javascript
<Popover content="abc" title="checkbox">
  <span><Checkbox>It works</Checkbox></span>
</Popover>
```

**Comment by benjycui** [comment]
@yesmeck 这个结论更新到文档中吧，Popover Tooltip 都需要。

主要是就算我们这边做了适配，开发者用第三方库的时候还是会碰到这个问题。

**Comment by afc163** [comment]
碰到一个改一个，老是加 span ，我自己都用的不爽。
