### ISSUE TITLE
Select展开输入文字远程搜索，无结果的时候自定义notFoundContent，空页面元素点击如何收起Select？

### ISSUE THREAD

**Issue by wenzhihao123** [ant-design/ant-design#34552]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望能支持手动收起Select下拉页面

### What does the proposed API look like?
可以参考：blur()和focus() API

**Comment by afc163** [comment]
先描述问题本身，提供重现例子。

**Comment by wenzhihao123** [comment]
> 

Select展开内容是我用dropdownRender自定义的，顶部有个输入框，输入调用远程搜索，无结果的时候自定义notFoundContent页面，这个空页面有个按钮可以让用户把填写的内容放到Select内容上，现在就是点击空页面的按钮无法关闭Select下拉内容，求指点下， 感谢~

**Comment by wenzhihao123** [comment]
@afc163  Select展开内容是我用dropdownRender自定义的，顶部有个输入框，输入调用远程搜索，无结果的时候自定义notFoundContent页面，这个空页面有个按钮可以让用户把填写的内容放到Select内容上，现在就是点击空页面的按钮无法关闭Select下拉内容，求指点下， 感谢~

**Comment by afc163** [comment]
给个 codesandbox

**Comment by MadCcc** [comment]
用 `open` 受控好了

**Comment by hoho2017** [comment]
1
