### ISSUE TITLE
Form 初始化执行 resetFields 会卸载2次组件

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#34569]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[16.13 https://stackblitz.com/edit/react-m76h1c-jkmwbf?file=index.js](https://stackblitz.com/edit/react-m76h1c-jkmwbf?file=index.js)
[19.2 https://stackblitz.com/edit/react-m76h1c](https://stackblitz.com/edit/react-m76h1c)

### Steps to reproduce
分别打开2个链接查看控制台，一个输出2次，一个输出一次

### What is expected?
都输出一次

### What is actually happening?
16.13 之后的版本会输出2次

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by kampiu** [comment]
我看了好像ant-design4.x 以及react < 18 就会有这个问题

**Comment by zombieJ** [comment]
看了一下，因为设置了 `deps` 为 `value`。reset 是通过 React.Fragment 的 `key` 来重置。这使得重置之前的 Field2 被设置 `value` 后通过 `key` 卸载触发了 `unmount`。而后新的组件进入触发 mount。新的子组件本身只触发了一次 effect：

https://stackblitz.com/edit/react-m76h1c-rmokjz?file=package.json,index.js,index.html
