### ISSUE TITLE
Tree with duplicate keys

### ISSUE THREAD

**Issue by christiananese** [ant-design/ant-design#34564]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/controlled-tree-antd-4-19-2-forked-ckuv10?file=/index.js)

### Steps to reproduce
Item 0-0-0-2 exists under parent 0-0-0 and 0-0-1
* Uncheck item 0-0-0-2
* Toggle 0-0-0 a few times
* For every "expand" the child "0-0-0-2" remains in the DOM as a dead child

### What is expected?
No dead node

### What is actually happening?
When expanding a parent that has a child that exists inside an other parent that child get's cloned and stays completely dead in the DOM 

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | react |
| System | all |
| Browser | all |

---
i.e. staff that works in certain departments. One staff member, can be in multiple departments.

Similar to #8480

**Comment by MadCcc** [comment]
You should apply different `key` to each TreeNode.

**Comment by MadCcc** [comment]
In your case, I recommend you to use `department` + `staff` as `key`, and `value` can be the same.

**Comment by LaiHB** [comment]
我也是上面那个问题，我的需求就是两个同样的人，选一个就两个都勾上，然后上面删除就两个都删除，如果两个key就没法做到这样了
