### ISSUE TITLE
clearFilters does not clear reset table

### ISSUE THREAD

**Issue by raoalok** [ant-design/ant-design#34562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/u5erlc)

### Steps to reproduce
Open filter and search, then click on reset it will clear the input field but doesn't reset table content to initial state (before filter state).
You have to click search button or press enter to bring table to unfiltered state, which it was doing earlier till antd v4.16

### What is expected?
onReset function should cleat the filtered state of the table. As it was doing till v4.16

var onReset = function onReset() {
setFilteredKeysSync([]);
triggerVisible(false);
internalTriggerFilter([]);
};

### What is actually happening?
But now it doesn't clear the filtered state of the table.  It clears the input field, then you have to click search button or press enter to bring table to unfiltered state.

v4.19.2
var onReset = function onReset() {
var _ref5 = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {
confirm: false,
closeDropdown: false
},
confirm = _ref5.confirm,
closeDropdown = _ref5.closeDropdown;

if (confirm) {
  internalTriggerFilter([]);
}

if (closeDropdown) {
  triggerVisible(false);
}

setSearchValue('');
setFilteredKeysSync([]);
};

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | macOS Monterey v12.2 |
| Browser | Microsoft Edge Version 99.0.1150.39 (Official build) (x86_64) |

**Comment by MadCcc** [comment]
After 4.19.0, you can pass `{ confirm: true }` to `clearFilters`.

**Comment by nickw-kr** [comment]
That did it for me @MadCcc - thanks!  Easy fix
