### ISSUE TITLE
自定义按钮实现标签页（Tabs）滚动时出现选不中标签的bug

### ISSUE THREAD

**Issue by tttonight** [ant-design/ant-design#34577]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-yj9l4o?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
重现：
（1）选中最后一个tab（tab11）
（2）滚动到最前面
（3）点击left按钮
（4）选择倒数第二个tab（tab10），这时候大概率会出现bug：选不中tab10这个标签，不会触发onChange事件

### What is expected?
希望解决自定义按钮实现标签页滚动时出现选不中标签的bug

### What is actually happening?
希望解决自定义按钮实现标签页滚动时出现选不中标签的bug

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | ^17.0.2 |
| System | win10 |
| Browser | chrome 86.0.4240.75 |

---
自定义按钮实现标签页

**Comment by afc163** [comment]
> 点击left按钮

onLeft 的实现相当于魔改了 dom 结构的样式，可能会影响 rc-tabs 内部的样式计算，不建议这样写。
