### ISSUE TITLE
RangePicker在抽屉组件下 style 100%点击选择时间会左右横跳

### ISSUE THREAD

**Issue by ahwgs** [ant-design/ant-design#34572]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-h1ld8t?file=/index.js)

### Steps to reproduce
1.在显示器上打开预览地址
2.将页面拖的尽可能大
3.打开抽屉选择时间
4.会发现时间选择弹窗再左右横跳

### What is expected?
不会抖动横跳

### What is actually happening?
左右横跳

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | React17 |
| System | mac |
| Browser | chrome 99 |

---
1.直接在页面上使用组件，即使是100%宽度也不会出现这个。目前发现在抽屉组件中会有这个问题

**Comment by ahwgs** [comment]
https://user-images.githubusercontent.com/26664586/158947171-024b3e7a-88ee-49cf-ab56-83436204daed.mp4

**Comment by myGitZone** [comment]
这个是由于监听了弹框容器的大小变化，如果没有popupStyle，会自动计算，导致容器大小一直变化。可以通过指定容器大小来处理

**Comment by afc163** [comment]
应该是同一个问题 https://github.com/ant-design/ant-design/issues/34755#issuecomment-1086612935
