### ISSUE TITLE
Button在Modal关闭后重新自动高亮

### ISSUE THREAD

**Issue by KshZh** [ant-design/ant-design#34571]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/guo-ji-hua-antd-4-19-2-forked-919mfz)

### Steps to reproduce
点击 Modal 按钮，关闭 Modal，Modal 按钮重新自动高亮

### What is expected?
Modal 关闭后，Modal 按钮不高亮

### What is actually happening?
Modal 关闭后，Modal 按钮重新自动高亮

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17 |
| System | macOS 12.2.1 (21D62) |
| Browser | Chrome 99.0.4844.51（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
`focusTriggerAfterClose` is `true` by default, you can use `false` to meet your demand.
