### ISSUE TITLE
Form表单获取表单校验状态，得到的值永远是 false

### ISSUE THREAD

**Issue by Soulwail** [ant-design/ant-design#34579]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiao-yan-qi-ta-zu-jian-antd-4-19-2-forked-g8gwz1?file=/index.js)

### Steps to reproduce
直接点击 Submit 按钮，表单出现校验，然后点击 Test 按钮

### What is expected?
点击 Test 按钮后，获得字段的校验状态为 true

### What is actually happening?
点击 Test 按钮后，获得字段的校验状态为 false

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment]
isFieldValidating 是指**正在校验中**，一般只有异步校验才会为 true，你给的 codesandbox 里面没有这种情况，因此拿到的始终为 false。
