### ISSUE TITLE
SubMenu 点击时控制台报错：Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by neohan666** [ant-design/ant-design#34575]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://null](https://null)

### Steps to reproduce
后台管理系统，侧边栏是多级菜单，点击SubMenu组件的菜单时控制台报错，项目使用了React.StrictMode

### What is expected?
不报错

### What is actually happening?
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chrome 99 |

**Comment by yoyo837** [comment]
Trace in #26136.
