### ISSUE TITLE
Form中Select异步赋值

### ISSUE THREAD

**Issue by zdxxxxxx** [ant-design/ant-design#3457]
- antd 版本: 2.0
- 操作系统及其版本:win 10
- 浏览器及其版本:chrome 最新

场景：
Model中  使用From表单 from中含有Select
点击按钮从服务端获取数据，然后设置Select的初始选中的值
initialValue不会使Select的值变化（此方法和defaultValue一样，只有第一次有用）
setFieldValues会造成死循环，我用了redux。

问题：setFieldValue只能触发吗？通过父组件更新子组件的props，子组件怎么用setFieldValues更新自己的表单值？

如果不用Form，直接用Select的value={this.state.value}就能实现，但是我取数据又不能用getFieldsValue取到它。

**Comment by afc163** [comment]
componentWillReceiveProps 里面监听和同步。

**Comment by zdxxxxxx** [comment]
已经解决 thk you
