### ISSUE TITLE
tooltip组件缺失overlay属性eslint语法检测有警告

### ISSUE THREAD

**Issue by reacher-lu** [ant-design/ant-design#3458]
如题，如果代码这样写

```js
<Tooltip title={ooxx}><a href="javascript:void(0);">xxoo</a></Tooltip>
```

则会弹出警告⚠️
<img src="https://cloud.githubusercontent.com/assets/3804296/19429208/010e0cb4-9481-11e6-847f-74adfb860f1b.png" width="500" />

``` code
element tooltip doesn't have required attribute overlay
```
看了内部实现，是把title属性直接赋值给了overlay，debug也确实有值，但是依然存在警告，把title换成直接用overlay代替后问题解决。

```js
<Tooltip overlay={ooxx}><a href="javascript:void(0);">xxoo</a></Tooltip>
```

不知道是何原因造成。

antd版本：1.6.0
内部所引用的rc-tooltip版本为3.3.5

**Comment by benjycui** [comment]
升到 1.11.2 可以？

**Comment by afc163** [comment]
eslint 不会警告这个，你用了 typescript 么？

**Comment by afc163** [comment]
看代码不会出现这个问题的，title 是直接传给 overlay 的，可能是楼主的编辑器的提示问题。

https://github.com/ant-design/ant-design/blob/1.6.0/components/tooltip/index.jsx#L83

**Comment by scottsut** [comment]
antd版本：2.6.1 
IDE：WebStorm 2016
依然还是有这个问题，没有用 typescript

![image](https://cloud.githubusercontent.com/assets/4098913/21880769/9fcd7152-d8db-11e6-9b47-46a44c06abf0.png)

**Comment by afc163** [comment]
@scottsut 由于我们没有环境，需要你自行排查一下，看看是什么工具在什么情况下报这个问题。
