### ISSUE TITLE
[AutoComplete] On Submit , Autocomplete gives show recent submitted option

### ISSUE THREAD

**Issue by Junaid300** [ant-design/ant-design#34580]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-wave-vo16x7?file=/index.js)

### Steps to reproduce
- Add an Autocomplete Component
- Add a button
- On button click , reset the autocomplete value
- Click on Autocomplete and in drop down it shows only recent submitted value

### What is expected?
- It should display all values or there should be an option to reset the filter.
- i don't know , is there any option to reset the filter ? 

### What is actually happening?
- Click on Autocomplete and in drop down it shows only recent submitted value

| Environment | Info |
|---|---|
| antd | 4.18.5 |
| React | 17.0.2 |
| System | 22000.556 |
| Browser | 99.0.4844.74 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27347#issuecomment-1066878930

**Comment by Junaid300** [comment]
@afc163  ,  I am using Autocomplete for Searching and if value not found I can add a new value from autocomplete.
I am using this for filtering  `filterOption={(input, option) => option.value.toUpperCase() .indexOf(input.toUpperCase()) >= 0`
but when i submit the form or value ,  `input` prop gives previous value . It should give "" or null
Is it possible to reset the input value on every form submit ?
