### ISSUE TITLE
Space 中 align='center' 和 width: '100%' 冲突

### ISSUE THREAD

**Issue by stormrise** [ant-design/ant-design#34609]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/stormrise/pen/rNpLYbw](https://codepen.io/stormrise/pen/rNpLYbw)

### Steps to reproduce
https://ant.design/components/space-cn/#components-space-demo-vertical

 按照文档说明设置 width: 100% 独占一行。并且我的元素也是width: 100%占满一行。

只有 width: 100%是正常的一行占满，

如果加上了align='center'就会出现占不满的情况。

### What is expected?
正常占满一行

### What is actually happening?
元素的width 100%没有生效

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | Window10 |
| Browser | chorme 96 |

**Comment by MadCcc** [comment]
Space 下的元素会被 item 包裹一层，所以 `width: 100%` 实际上没有生效到 item 上，这个看起来没什么特别好的办法。
试试 Row 和 Col？

**Comment by afc163** [comment]
这个演示和描述有问题，我改掉。

垂直这里需要把 Space inline-flex 改成 flex，否则无法占满一行。
