### ISSUE TITLE
showSearch的Select  选择其他值后 有抖动

### ISSUE THREAD

**Issue by zdxxxxxx** [ant-design/ant-design#3460]
- antd 版本:2.0
- 操作系统及其版本:win0
- 浏览器及其版本:chrome 最新

large的Select 值改变后会偏上

**Comment by benjycui** [comment]
这个 demo 中的 Select 也是 large，没问题啊。。 https://ant.design/components/form/#components-form-demo-validate-other

**Comment by zdxxxxxx** [comment]
加上showSearch

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
先试试 2.1.0。

https://github.com/ant-design/ant-design/issues/3413

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3481 修复后应该也没有这个问题了。
