### ISSUE TITLE
AnchorLink点击startOffset更新 scroll事件无法获取最新的startOffset

### ISSUE THREAD

**Issue by zhaojj332** [ant-design/ant-design#34603]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更新startOffset无法获取最新状态问题

### What does the proposed API look like?
期望等startOffset异步更新后scroll事件才被执行  AnchorLink.js 中使用
setTimeout(() => {
    scrollTo(href);
}, 0);

**Comment by aslan-alt** [comment]
可以给个codesandbox 吗？或者更多上下文呢？

**Comment by zhaojj332** [comment]
` <Anchor
             
              targetOffset={targetOffset}
              onClick={(e, link) => { anchorClick(e, link) }}
            >
// ...
</Anchor>

const [targetOffset, setTargetOffset] = useState(0)
const anchorClick = (e, o) => {
    // 每次点击都需要修改targetOffset的值，但是每次都是上一次set的值（useState异步导致）
    e.preventDefault()
    const newNum = o.href.slice(6)
    const n = newNum * 32 + 165 - 25
    setTargetOffset(n)
    console.log('targetOffset2:', targetOffset, newNum, '------', n)
  }

`
