### ISSUE TITLE
Secondary color for brand that has 2 colors

### ISSUE THREAD

**Issue by techandmedia** [ant-design/ant-design#34611]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Adding a secondary color to support brand that has 2 main colors

### What does the proposed API look like?
If a variable named @primary-color is for Primary Color, then @secondary-color for Secondary Color
A secondary color can be used interchangeably with primary color, for example: on a button, a primary color can be used as a background-color and a secondary color can be used as a border-radius color or vice versa

A secondary color can be inserted as a props of a component or from a config provider

Will use default secondary
<Button type="primary">Test<Button/>

 Will set custom secondary
<Button type="primary" secondary="#52c41a">Test<Button/>

**Comment by afc163** [comment]
It is not fit our design speification, but thanks for advice anyway.
