### ISSUE TITLE
Crash in example code of Tree component

### ISSUE THREAD

**Issue by ngotrongphuc** [ant-design/ant-design#34619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z3y853)

### Steps to reproduce
In the example code of Tree (directory): https://ant.design/components/tree/#components-tree-demo-directory. It crashes when click on anything except the dropdown icon of parent node

### What is expected?
It shouldn't be crashed

### What is actually happening?
Crashed when click on anything except the dropdown icon of parent node

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 16.14.0 |
| System | codesandbox.io |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Demo in site or stackblitz is fine，maybe issue of CodeSandbox.

**Comment by afc163** [comment]
```diff
-     console.log('Trigger Select', keys, info);
+    console.log('Trigger Select', keys);
```

CodeSandbox has perfermance issue when console complex object via `console.log(info)`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29937#issuecomment-904508915
