### ISSUE TITLE
Carousel 组件的属性 `arrows` 未生效

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design#34615]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-19-2-forked-hj6qep)

### Steps to reproduce
使用 Carousel，设置 arrow 属性，没有出现上一个、下一个切换按钮；

### What is expected?
使用 Carousel，设置 arrow 属性，正常出现上一个、下一个切换按钮；

### What is actually happening?
没有出现上一个、下一个切换按钮；

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17 |
| System | Windows 10 |
| Browser | Edge/99.0.1150.46 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4423#issuecomment-269749265
https://github.com/ant-design/ant-design/issues/5458#issuecomment-288713585
https://github.com/ant-design/ant-design/issues/12479
