### ISSUE TITLE
CheckboxGroup 的defaultValue 设置要先于options才能生效

### ISSUE THREAD

**Issue by lobinroromens** [ant-design/ant-design#3461]
- antd 版本:2.00
- 操作系统及其版本:mac 10.2
- 浏览器及其版本:chrome 53

#### 动态设置CheckboxGroup 的defaultValue和options发现defaultValue无效
设置defaultValue需要在options之前才能生效

**Comment by lobinroromens** [comment]
补充：由于defaultValue和options都是异步从服务器获取的所以无法保证defaultValue在options之前

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically

类似。
