### ISSUE TITLE
虚拟列表报ref错误

### ISSUE THREAD

**Issue by caixiaocai19** [ant-design/ant-design#34620]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/list-cn/中VirtualList例子](https://ant.design/components/list-cn/)

### Steps to reproduce
https://ant.design/components/list-cn/中VirtualList例子

### What is expected?
运行正常 但是控制台有报错

### What is actually happening?
运行正常 但是控制台有报错

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | win10 |
| Browser | 谷歌90.0.4758.102 |

**Comment by caixiaocai19** [comment]
![image](https://user-images.githubusercontent.com/75648273/159217964-ce26ab39-4ce0-4847-bcea-a1340d39d1d0.png)

**Comment by Benny-Chan** [comment]
同样的问题
