### ISSUE TITLE
Collapse的额外节点是input时，聚焦在input按下回车键，折叠面板会触发收起展开

### ISSUE THREAD

**Issue by wengfeifei** [ant-design/ant-design#34625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://reb189.csb.app/](https://reb189.csb.app/)

### Steps to reproduce
焦点在input，按下回车键

### What is expected?
折叠面板不会触发展开折叠

### What is actually happening?
折叠面板触发展开折叠

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | MacBook Pro (13-inch, M1, 2020) |
| Browser | Chrome 97.0.4692.99（正式版本） (arm64) |

**Comment by LoveEocding** [comment]
同样的问题，怎么避免

**Comment by wengfeifei** [comment]
<Input
  onClick={(e) => e.stopPropagation()}
  onKeyPress={(e) => e.stopPropagation()}
/>
