### ISSUE TITLE
Cascader components In mutile mode，setting props maxTagCount="responsive" and tagReander=renderFunc

### ISSUE THREAD

**Issue by KanadeHu** [ant-design/ant-design#34631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-antd-4-19-2-forked-igsw8f?file=/index.js)

### Steps to reproduce
1.Select multiple drop-down options until the omitted item appears
2.Close the tags one by one until all tags are closed
3.Expand the drop-down menu again to check the selection of options

### What is expected?
When clicking tag to close, it can correctly match the items selected in the drop-down menu

### What is actually happening?
When all tags are closed, there are still selected items in the drop-down menu

| Environment | Info |
|---|---|
| antd | 4.19.2|
| React | 17.0.1 |
| System | windows |
| Browser | chrome |

---
Is it wrong for me to use tagrender

**Comment by 1247748612** [comment]
It's not a bug because you're using the wrong

You should keep `visible` true because the `ant-tag-hidden` className will be set in the Tag when you click the close button. This will result in an incorrect display.

**Comment by KanadeHu** [comment]
> It's not a bug because you're using the wrong
> 
> You should keep `visible` true because the `ant-tag-hidden` className will be set in the Tag when you click the close button. This will result in an incorrect display.

Can I understand that when I close the custom tag, I must keep the drop-down option panel expanded

**Comment by KanadeHu** [comment]
> It's not a bug because you're using the wrong
> 
> You should keep `visible` true because the `ant-tag-hidden` className will be set in the Tag when you click the close button. This will result in an incorrect display.

Can I understand that when using tagRender, i need to keep maxtagcount not in responsive

**Comment by 1247748612** [comment]
> Can I understand that when using tagRender, i need to keep maxtagcount not in responsive

No!

I forgot to tell you that is the `visible` property of the Tag component.

You should keep Tag property `visible` as true.

like this [example](https://codesandbox.io/s/duo-xuan-antd-4-19-2-forked-igsw8f?file=/index.js)

**Comment by KanadeHu** [comment]
> > Can I understand that when using tagRender, i need to keep maxtagcount not in responsive
> 
> No!
> 
> I forgot to tell you that is the `visible` property of the Tag component.
> 
> You should keep Tag `visible` property as true.
> 
> like this [example](https://codesandbox.io/s/duo-xuan-antd-4-19-2-forked-igsw8f?file=/index.js)

Thanks , We need to update the official document about this problem https://codesandbox.io/s/uuyjyz，Preventing others from experiencing the same confusion

**Comment by 1247748612** [comment]
> Thanks , We need to update the official document about this problem [https://codesandbox.io/s/uuyjyz，Preventing](https://codesandbox.io/s/uuyjyz%EF%BC%8CPreventing) others from experiencing the same confusion

Yes, I will update the relevant documentation

**Comment by 1247748612** [comment]
I found inconsistent behavior of `tagRender` in `select` and `cascader` components

The `select` component also works without `visible`. [select example](https://codesandbox.io/s/uuyjyz?file=/index.js)

`Cascader`'s tagRender may behave incorrectly

**Comment by KanadeHu** [comment]
> 
yes
In my current project, I can avoid this unexpected problem by not using tagrender
Now the visible attribute of the tag component is configured, which can also solve the problem
I'll verify it later

**Comment by 1247748612** [comment]
Can you reopen this issues?, it's a bug
