### ISSUE TITLE
如何在表单获取Cascader默认值时，获取对应的label？

### ISSUE THREAD

**Issue by caice7** [ant-design/ant-design#34649]
### Reproduction link

[![Edit on CodeSandbox](https://gw.alipayobjects.com/zos/antfincdn/HnwnLhPWA/codesandbox.png)](https://codesandbox.io/s/serene-gould-c4rnpy?file=/src/App.tsx:973-981)

### Steps to reproduce

```
import "./styles.css";
import { Cascader, Button, Form } from 'antd';
import ProForm from '@ant-design/pro-form';
import 'antd/dist/antd.css';

export default function App() {
  const [form] = Form.useForm();
  const options = [
    {
      label: 'Light',
      value: '1',
    },
    {
      label: 'Bamboo',
      value: '2',
      children: [
        {
          label: 'Little',
          value: '3',
          children: [
            {
              label: 'Toy Fish',
              value: '4',
            },
            {
              label: 'Toy Cards',
              value: '5',
            },
            {
              label: 'Toy Bird',
              value: '6',
            },
          ],
        },
      ],
    },
  ];
  const onOk = () => {
    form.validateFields().then((value) => {
        console.log("value", value);
      })
  };


  return (
    <div className="App">
      <ProForm form={form} initialValues={{"ccc": ['2', '3', '6']}}>
        <Cascader
          name="ccc"
          changeOnSelect={true}
          options={options}
        />
      </ProForm>
      <Button onClick={onOk}>取值</Button>
    </div>
  );
}

```

### What is expected?

我想获取的结果是[{label:'Bamboo', value: '2'}, {label:'Little', value: '3'}, {label:'Toy Bird, value: '6'}]}]

### What is actually happening?

现在获取的是['2', '3', '6']

### Environment and version

- antd: `not specified`
- React: `16.14.0`
- System: `not specified`
- Browser: `chrome`

---
我试过把initialValues里带上label和value的值，但那样就不能默认显示选中的值了

**Comment by afc163** [comment]
获取 value 结果后，拿 options 去取到对应的完整对象数组。

**Comment by caice7** [comment]
> 
这样的效率非常低啊，因为正式项目里options是异步获取的。相当于既要在Cascader组件外找个地方去存取时时变化的options，还要在提交时递归去找一遍Form中每个使用了Cascader组件的label值。居然没有一个更简便的改造示例或方法么……？
