### ISSUE TITLE
Missing animation Badge RTL

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#34640]
### Reproduction link
[![Edit on CodeSandbox](https://gw.alipayobjects.com/zos/antfincdn/ytEWA%26gOl/c.svg)](https://codesandbox.io/s/dynamic-antd-4-19-3-forked-mhftnb)

### Steps to reproduce
Missing animation Badge RTL

### What is expected?
in version 4.16 have this animation for RTL
```
@keyframes antZoomBadgeInRtl {
  0% {
    transform: scale(0) translate(-50%, -50%);
    opacity: 0;
  }
  100% {
    transform: scale(1) translate(-50%, -50%);
  }
}

@keyframes antZoomBadgeOutRtl {
  0% {
    transform: scale(1) translate(-50%, -50%);
  }
  100% {
    transform: scale(0) translate(-50%, -50%);
    opacity: 0;
  }
```

### What is actually happening?
missing this.

### Environment and version
- antd: `4.19.3`
- React: `17.0.2`
- System: `4.19.3`
- Browser: `Chrome 90`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/34641
