### ISSUE TITLE
slider更新后绑定ref无法获取到dom属性

### ISSUE THREAD

**Issue by fancyvip** [ant-design/ant-design#34642]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kong-zhi-tooltip-de-xian-shi-antd-4-19-2-forked-rsz6pw?file=/index.js)

### Steps to reproduce
使用createRef()绑定Slider获取current内的方法

### What is expected?
获取到dom上所有属性

### What is actually happening?
只能获取到blur和focus两个事件

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome 版本 99.0.4844.74（正式版本）（64 位） |

**Comment by afc163** [comment]
不应该依赖 class component 实例上的任何内部属性，这些内部属性会随着重构发生不可预期的变化，除了 API 文档中提到的方法。https://ant.design/components/slider-cn/

**Comment by fancyvip** [comment]
> 不应该依赖 class component 实例上的任何内部属性，这些内部属性会随着重构发生不可预期的变化，除了 API 文档中提到的方法。https://ant.design/components/slider-cn/

像slider这种有鼠标事件或键盘事件的组件开发的时候可能会偶尔用到ref来操作dom（例如 **onMouseDown, onMouseMove**），4.18.9版本更新之后ref只暴露了blur和focus方法，是否意味着以后所有的组件都会如官网写的只暴露这两个方法

![1647927057(1)](https://user-images.githubusercontent.com/23178419/159414305-4f4e75c6-f875-4e64-91d3-cbb41bc729b9.png)
