### ISSUE TITLE
请问教程中的  顶部导航部分 右侧的工具区是如何实现的？

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#3464]
- antd 版本:2.0.1
- 操作系统及其版本:win10
- 浏览器及其版本:chrome 54

#### 您做了什么？

引入 antd 了 menu row col。

#### 您期待的结果是：

https://ant.design/docs/pattern/navigation#顶部导航
实现这里图片中的右侧工具区
![image](https://cloud.githubusercontent.com/assets/4524983/19445555/4f55026a-94c7-11e6-9a29-0c435d6c4bdf.png)

#### 实际上的结果是：
只有一个menu的情况下，左侧对其， 在添加一个menu后，就成2排了。

#### 可重现的在线演示
http://codepen.io/xjdata/pen/JRazdg

谢谢

**Comment by afc163** [comment]
建议学习 css 布局，可以用 `float` 或 `position: absolute` 让两个菜单在同一行。

http://zh.learnlayout.com/

**Comment by xjdata** [comment]
多谢。
