### ISSUE TITLE
Does not display checkbox changes

### ISSUE THREAD

**Issue by eugenestepanyuk** [ant-design/ant-design#34659]
### Reproduction link

[![Edit on CodeSandbox](https://gw.alipayobjects.com/zos/antfincdn/HnwnLhPWA/codesandbox.png)](https://codesandbox.io/s/great-forest-o5r2iy?file=/src/App.js)

### Steps to reproduce

1. Select a row from the table by clicking on it
2. Click on the Update user button
3. Change the state of the checkbox
4. Click OK

### What is expected?

Displaying the new state of the checkbox after an update

### What is actually happening?

The new state of the checkbox is not displayed after the update

### Environment and version

- antd: `4.15.6`
- React: `17.0.2`
- System: `Windows 10 Pro 1909`
- Browser: `Chrome 99.0.4844.82`

**Comment by eugenestepanyuk** [comment]
> ### Вы можете искать проблемы:
> 1. 67% [Не перерисовывается при изменении состояния ](https://github.com/ant-design/ant-design/issues/22421)[ #22421](https://github.com/ant-design/ant-design/issues/22421)[](https://github.com/ant-design/ant-design/issues/22421)
> 
> 🤖По [вопросам сходства-анализа](https://github.com/actions-cool/issues-similarity-analysis)

use setFieldsValue it doesn't solve my problem

**Comment by afc163** [comment]
https://ant.design/components/form/#API

<img width="1185" alt="图片" src="https://user-images.githubusercontent.com/507615/159458376-34fc09cb-25b0-4c6e-ae92-7c592f1c5b30.png">

**Comment by afc163** [comment]
https://codesandbox.io/s/silly-goldberg-ugiw9m?file=/src/App.js
