### ISSUE TITLE
test

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#34664]
### Reproduction link

<a href="https://codesandbox.io/s/awesome-pascal-0go3n7?file=/src/App.js"><img width="200" src="https://gw.alipayobjects.com/zos/antfincdn/HnwnLhPWA/codesandbox.png" alt="Edit on CodeSandbox" /></a>

### Steps to reproduce
xxx

**Comment by xrkffgg** [comment]
这精度 看的我都麻了
