### ISSUE TITLE
Select component does not show value being selected on dropdownRender

### ISSUE THREAD

**Issue by larxx** [ant-design/ant-design#34662]
### Reproduction link

[<img width="200" src="https://gw.alipayobjects.com/zos/antfincdn/HnwnLhPWA/codesandbox.png" alt="Edit on CodeSandbox" />](https://codesandbox.io/s/awesome-pascal-0go3n7?file=/src/App.js)

### Steps to reproduce

link provided to reproduce behavior: https://codesandbox.io/s/awesome-pascal-0go3n7?file=/src/App.js

### What is expected?

Onchange the select component should properly show selected value

### What is actually happening?

Select component does not show value being selected inside dropdownRender which has Cascader component

### Environment and version

- antd: `4.19.3`
- React: `React 17`
- System: `4.19.3`
- Browser: `Chrome 99.0.4844.82`

**Comment by MadCcc** [comment]
I don't understand what you mean. It works well in your demo.
![image](https://user-images.githubusercontent.com/27722486/159616515-755cde58-7e35-44cd-8cce-e9821acb787e.png)

**Comment by larxx** [comment]
In the demo above, when you click outside the select component, the expected behavior is that the Select should show "Car 2". Just like when you would select "apple" or "orange" then the select would reflect that value.
