### ISSUE TITLE
Select组件多选模式下，通过在输入框中输入内容对下拉选项进行筛选，选中某项后输入框中筛选内容被清空，同时此前筛选后的选项重置为筛选前的选项。导致用户不可就当前筛选后的选项直接多选，而要重复筛选并选择。

### ISSUE THREAD

**Issue by lee-soofen** [ant-design/ant-design#34672]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gcdc1j?file=/index.js)

### Steps to reproduce

对下拉选项进行筛选，选中任一筛选后的选项

### What is expected?

选中的选项显示在输入框中，同时输入框中的筛选字符不被清除

### What is actually happening?

输入框中的筛选字符被清除

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome 99.0.4844.51 |

**Comment by afc163** [comment]
`autoClearSearchValue={false}`
