### ISSUE TITLE
Cascader can't config readonly, only support disabled

### ISSUE THREAD

**Issue by believeZJP** [ant-design/ant-design#34674]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-19-3-forked-n5qe2n?file=/index.js)

### Steps to reproduce

readonly not work, why don't support readonly

### What is expected?

Cascader support readonly

### What is actually happening?

disabled background is not white.

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/issues/28773#issuecomment-756621227

**Comment by MadCcc** [comment]
You can use `open={false}` to make dropdown not shown, since `readonly` may not be introduced.
But I think `readonly` is something useful in some cases. @afc163

**Comment by believeZJP** [comment]
> You can use `open={false}` to make dropdown not shown, since `readonly` may not be introduced. But I think `readonly` is something useful in some cases. @afc163

In some cases, I need to set open like this `open={isEdit? '': false}`, when isEdit is true, Cascader should not automatically open, what value should be there?

  `readonly` is useful in this cases. strongly recommended for support~

**Comment by MadCcc** [comment]
> In some cases, I need to set open like this `open={isEdit? '': false}`, when isEdit is true, Cascader should not automatically open, what value should be there?

Use `undefined` instead of `''`.

**Comment by MadCcc** [comment]
Closing for possibly won't support it.

**Comment by believeZJP** [comment]
> > In some cases, I need to set open like this `open={isEdit? '': false}`, when isEdit is true, Cascader should not automatically open, what value should be there?
> 
> Use `undefined` instead of `''`.   @MadCcc 
use `undefined`  not work~~
[code link ]( https://codesandbox.io/s/ji-ben-antd-4-19-3-forked-jjpfqy?file=/Cas.js)
