### ISSUE TITLE
InputNumber 建议添加【滚轮】增减数字

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#3467]
这个功能或许可以让操作更加方便一些，提高一点易用度吧，个人觉得还是蛮实用的，比点击上下箭头方便多了。

可能要注意的操作细节
 在某些情况下，数字跨度比较大或许你会觉得上下滚比较累，可以根据滚轮的上下滚动幅度（onWheel事件的deltaY）变化的大小，变化数字增减的快慢程度

**Comment by yesmeck** [comment]
我之前项目里用`<input type="number" />`的时候都刻意把滚轮禁用掉的，滚轮很容易产生误操作。

**Comment by benjycui** [comment]
在 InputNumber 上下箭头已经支持长按的前提下，滚轮并没有带来多大的体验提升。

然后滚轮没有视觉暗示，用户还不一定能发现这个交互。

**Comment by xutou12** [comment]
嗯滚轮操作的话再考虑考虑吧

**Comment by benjycui** [comment]
问了交互，可做可不做，所以有需要可以自己 PR。

**Comment by zzz6519003** [comment]
looks like a girl XD
