### ISSUE TITLE
border color with transparency 重叠问题(Descriptions)

### ISSUE THREAD

**Issue by jesse3mh9a** [ant-design/ant-design#34687]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-transparency-issue-6obm9y?file=/src/index.js)

### Steps to reproduce

open codesandbox  link  for detail, preview in chrome/firefox  latest

### What is expected?

Descriptions Item can Collapse rendered element

### What is actually happening?

after v4.19.0, because of merging feature #33506, overlay borders begin to darken

| Environment | Info |
| --- | --- |
| antd | 4.19.0 |
| React | 17 |
| System | macos 12 |
| Browser | chrome/firefox  latest |

---
when Descriptions.Item set display: none,  row:last-child {border-bottom: none; } is unexpected.
we can custom label and content in DescriptionItem, but row(tr) seems can't do that

**Comment by MadCcc** [comment]
Should provide `rootStyle` for customizing style.

**Comment by jesse3mh9a** [comment]
can i provide `rowProps` for customizing more properties, eg: `className`

**Comment by MadCcc** [comment]
It's more complex...We will find a way to improve this.

**Comment by jesse3mh9a** [comment]
@MadCcc 
About handing table, I prefer to set cell border-bottom instead of row. I create a PR, hope to give me some advice.

```
&:last-child {
      > th,
      > td {
        border-bottom: none;
      }
    }
```

**Comment by afc163** [comment]
Why don't you try nullable react node instead of `display: none`: https://codesandbox.io/s/antd-transparency-issue-forked-4sz0yj?file=/src/App.js

**Comment by jesse3mh9a** [comment]
In some case, when it is toggled, expect it is not destroyed and re-constructed.
