### ISSUE TITLE
Input.TextArea 设置autoSize后，在表单resetFields偶现抖动

### ISSUE THREAD

**Issue by Y-qwq** [ant-design/ant-design#34683]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-19-3-forked-yozu0i?file=/index.js)

### Steps to reproduce

在表单里，对文本框重复聚焦失焦点，模拟校验失败运行resetFields，偶现行高从两行跳到实际计算后的行数

### What is expected?

文本框在form.resetFields时不抖动

### What is actually happening?

默认值不是两行高度时，文本框在form.resetFields时偶尔抖动

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 16.14.0 |
| System | macos |
| Browser | 99.0.4844.51 (arm64) |

---
看上去是因为resetFields会重新mount，而TextArea设置autoSize之后，autoSize的处理时序相对滞后，不是在mount的时候就计算好行高，导致重新mount的时候先展示默认行高，在变成计算后的行高

**Comment by afc163** [comment]
最新版本不存在这个问题了：https://codesandbox.io/s/ji-ben-shi-yong-antd-4-19-3-forked-umb020?file=/package.json

Fixed in https://github.com/react-component/textarea/pull/23
