### ISSUE TITLE
descriptionItem设置contentStyle后不生效

### ISSUE THREAD

**Issue by furan495** [ant-design/ant-design#34688]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/coiy4q)

### Steps to reproduce

descriptionItem值设置为{0}，添加contentStyle={{color:'red'}}属性

### What is expected?

0变红

### What is actually happening?

0没变红

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17.x |
| System | mac |
| Browser | 谷歌最新版 |

**Comment by furan495** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-1rt6cp?file=/index.js

**Comment by FeiFan-FTE** [comment]
![image](https://user-images.githubusercontent.com/37998952/159880204-7243ee33-b94e-473d-8d91-704c8ac343f6.png)

**Comment by furan495** [comment]
> ![image](https://user-images.githubusercontent.com/37998952/159880204-7243ee33-b94e-473d-8d91-704c8ac343f6.png)
我也试过转成string，但是业务场景中不容易想到这么个情况；
其他的int值貌似都可以，包括负数，只有0不行，很好奇是因为什么。

**Comment by FeiFan-FTE** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by FeiFan-FTE** [comment]
{`${parseInt(0)}`}

**Comment by SOCHINGYEE** [comment]
但是antd3.x就是不生效啊。。

**Comment by FeiFan-FTE** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
