### ISSUE TITLE
Steps支持设定responsive的宽度

### ISSUE THREAD

**Issue by scrapstation** [ant-design/ant-design#34680]
### What problem does this feature solve?

订单详情页面，左右分栏，左侧基本信息，右侧订单进度，订单进度超出card
![image](https://user-images.githubusercontent.com/56467036/159822069-72ad8440-bddd-4602-9bde-66c457cd1895.png)

### What does the proposed API look like?
responsive: false | number | string

**Comment by MadCcc** [comment]
本身应当就是 reponsive 的，可以看 Demo 的表现
![image](https://user-images.githubusercontent.com/27722486/159842431-30fa1cb9-78c5-4d4a-a3dc-428daa923d86.png)

**Comment by scrapstation** [comment]
@MadCcc 
在step比较多的时候
https://hz6hp6.csb.app/

**Comment by afc163** [comment]
responsive 宽度目前在 less 里作为全局变量，目前不支持单独定制某个组件的 responsive 断点。

你想要的更多是根据容器宽度改变 Steps 布局方式，我建议使用 https://github.com/react-component/resize-observer/ 配合 direction 属性来实现这个效果。
