### ISSUE TITLE
Customize Table sort Asc/Desc Icon

### ISSUE THREAD

**Issue by phuhd-0935** [ant-design/ant-design#34693]
### What problem does this feature solve?

In version 4.18.8, I can't override the icon of sort Asc/Desc Icon in Table component.

### What does the proposed API look like?

Apply new props to customise this, likely AscIcon, DescIcon

**Comment by afc163** [comment]
Duplicate of #19561

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/42498
