### ISSUE TITLE
文档有点小错误哈。。

### ISSUE THREAD

**Issue by luchenwei9266** [ant-design/ant-design#3469]
Table组件。可控的筛选和排序那一块。我这里看到下面的提示的序号都是“1”
![image](https://cloud.githubusercontent.com/assets/9455826/19467560/5e0f6e3a-9544-11e6-81ce-77d8c6e88dcb.png)

**Comment by benjycui** [comment]
文档类建议直接 PR 哈，谢谢。

**Comment by luchenwei9266** [comment]
![image](https://cloud.githubusercontent.com/assets/9455826/19468821/0a180e52-954b-11e6-93c3-c1aca8761434.png)
github上的该文件似乎没有问题的，但是网页中显示有问题。。

**Comment by afc163** [comment]
是 markdown 解析问题。@benjycui

**Comment by benjycui** [comment]
用的 parser 好像不支持 GitHub Flavour Markdown...
