### ISSUE TITLE
表格组件问题和需求

### ISSUE THREAD

**Issue by zhbhun** [ant-design/ant-design#347]
测试了下表格组件的概念, 遇到了下面这些问题:
1. `dataSource` 设置为动态加载数据的时候,  如果上层组件有状态更新, 无论 `dataSource` 属性是否变化, 表格每次都会从服务器端加载数据.
2. 不支持设置大小 --- 设置大小后, 如果内容超出表格, 能够出现滚动条的功能. 通过 style 属性设置, 分页显示会存在问题, 目前只能在外面再包装一层. 希望能够支持大小, 然后表头和分页栏能够固定住.
3. 数据搜索只支持预定义的值吗? 看示例是这么用的, 不知道还有没有其他用法.
4. 列不支持拖拽排序, 也不支持宽度调整, 不支持列固定(横向滚动条时固定某一些列的显示)
5. 记录怎么实现单选?

感觉这些功能在企业级后台产品都用得着, 不知道这些功能的的开发计划如何?

另外提一个跟标题不相干的问题, Antd 组件都没有多主题的颜色的设计. 例如: 按钮组件只有 primary, default, ghost, 在很多业务场景下更需要类似于 Bootstrap 的情景设置 --- 默认, 主要, 信息, 成功, 警告, 危险.

**Comment by afc163** [comment]
1. fixed by 05347da9269bd3618f2d52068ee143ce5191381b
2. 暂时不支持，欢迎 PR 。不过固定表头的需求后续可能会补充。
3. 筛选是可以自己配置的。
4. 暂时不支持，欢迎 PR 。
5. 可以关注 #252 的推进。
