### ISSUE TITLE
当上传成功后在调取一个异步接口的时候filelist 和单独file==done打印的数据不一致

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-design#34709]
### Reproduction link

![image](https://user-images.githubusercontent.com/31272499/160067008-3827d91f-a24c-4171-b79b-d90965fd647f.png)
![image](https://user-images.githubusercontent.com/31272499/160067027-c4babaed-c015-4788-94cd-3816315394cb.png)

### Steps to reproduce

当上传成功后在调取一个异步接口的时候filelist 和单独file==done打印的数据不一致

### What is expected?

当上传成功后在调取一个异步接口的时候filelist 和单独file==done打印的数据保持一致

### What is actually happening?

当上传成功后在调取一个异步接口的时候filelist 和单独file==done打印的数据不一致

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React |  "react": "^17.0.0", |
| System | mac |
| Browser | 谷歌 |

**Comment by MadCcc** [comment]
给个简单复现吧，截图看不明白的
