### ISSUE TITLE
tree trigger an error when other element drop to tree

### ISSUE THREAD

**Issue by yuwanlin** [ant-design/ant-design#34701]
### Reproduction link

[https://stackblitz.com/edit/react-ixxeen?file=index.js](https://stackblitz.com/edit/react-ixxeen?file=index.js)

### Steps to reproduce

1. drag node at the Tree, it works
2. drag right html element to tree, it trigger an error
> Error in /turbo_modules/antd@4.19.3/dist/antd.min.js (23:777274)
Cannot read properties of null (reading 'props')

### What is expected?

1. don't trigger an error
2. trigger any drag or drop event

### What is actually happening?

trigger an error

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17.0.2 |
| System | win10 |
| Browser | edge 99 |

---
**by the way, Is there a way to trigger a event when drag an other element(not in Tree) to tree?**  #5161 #12654

**Comment by MadCcc** [comment]
Didn't get error. Currently dragging another element into Tree is not supported.

**Comment by yuwanlin** [comment]
https://user-images.githubusercontent.com/18443683/160354361-2fd05961-1ebc-400e-acec-d30b512ce879.mp4

try step 1 first, then step 2 will trigger an error like video
