### ISSUE TITLE
Select component not displaying options as expected.

### ISSUE THREAD

**Issue by ryannealmes** [ant-design/ant-design#3471]
I have just started using your awesome framework and had a question aroung the select component. I have a case where the text in the options is longer than the width of the drop down. This results in strange behavior. Please see the screenshots and codepen below

Codepen for antd [implementation](http://codepen.io/anon/pen/vXVgPm?editors=001)
Codepen default html [implementation](http://codepen.io/anon/pen/QKkpLz)

If you compare the two selects you can see I have added an option with text that is greater than the width of the select. I would have expected the full text to be visible when the options are displayed. I can't see anything in the documentation around enabling this. There is also a strange piece of behaviour that displays the full text of the currently selected item when changing the select option.

Is the component intended to work this way?

Thanks.

**Comment by benjycui** [comment]
https://ant.design/components/select/#Select-props

`dropdownMatchSelectWidth={false}`

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by ryannealmes** [comment]
Did all of the suggestions before posting an issue. I am not here to waste your or my time. Next time I will spend more time reading the documentation more carefully. Apologies!
