### ISSUE TITLE
文档翻译术语 【栅格】 能否改为 【网格】

### ISSUE THREAD

**Issue by find456789** [ant-design/ant-design#34717]
### What problem does this feature solve?

https://ant-design.gitee.io/components/grid-cn/     这里的grid和css 的grid差不多，实现的都是布局，目前大部分资料都把grid称呼为【网格】， 并且 网格 这个称呼 比 栅格 更【语义化】，  

参考：  
https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout
https://www.google.com/search?q=css grid&newwindow=1&lr=lang_zh-CN&
https://www.baidu.com/s?wd=css%20grid&ie=utf-8

通过搜索 css grid， 大家更多是称呼为 网格， 而非栅格

 

### What does the proposed API look like?

希望可以把【栅格】修改为【网格】

**Comment by afc163** [comment]
栅格是老前端时代传来下的翻译，语义上没有明显问题。目前 Grid 没有用到 css grid 来实现，还是保持现有的翻译更合适。
