### ISSUE TITLE
datePicker组件type为week且自定义format格式时，悬浮日期组件框内容显示错误

### ISSUE THREAD

**Issue by CorgiTT** [ant-design/ant-design#34725]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/san-zhong-da-xiao-antd-4-19-3-forked-tji9tf?file=/index.js)

### Steps to reproduce

1、设置datepicker的自定义显示格式属性，format为`YYYY年第wo`;

2、当悬浮在2021年12月内的日期时，组件框内显示2021年第52周；
![image](https://user-images.githubusercontent.com/16759949/160233027-e9166def-8608-44eb-849b-68195ba8c6ca.png)

3、当悬浮在2022年1月内的日期时，组件框内显示2022年第52周；
![image](https://user-images.githubusercontent.com/16759949/160233063-86a1cdaa-2590-4a55-9ae5-255cacff832f.png)

### What is expected?

当悬浮在2022年1月内的日期时，组件框内显示2021年第52周；

### What is actually happening?

当悬浮在2022年1月内的日期时，组件框内显示2022年第52周；

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 16.14.0 |
| System | windows |
| Browser | edge 99 |

**Comment by 1247748612** [comment]
See https://github.com/ant-design/pro-components/issues/4785

**Comment by zombieJ** [comment]
YYYY 是日期年，GGGG 才是 Week Year:

https://codesandbox.io/s/san-zhong-da-xiao-antd-4-19-3-forked-pwpyq8?file=/index.js
