### ISSUE TITLE
Validation warning of type mismatch in TypeScript

### ISSUE THREAD

**Issue by arifszn** [ant-design/ant-design#34726]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-dan-0uj6yx?file=/src/App.tsx)

### Steps to reproduce

In a TypeScript project, use the props from state instead of direct writing as string.

```js
function MyApp() {
  const [state, setState] = useState('primary');

  return <Button type={state}>Primary Button</Button>
}
```

### What is expected?

No validation error.

### What is actually happening?

Validation error:
`Type 'string' is not assignable to type '"primary" | "link" | "text" | "ghost" | "default" | "dashed" | undefined'.`

![image](https://user-images.githubusercontent.com/45073703/160236828-e07c48b9-7852-40b1-857c-5baf9bb5172f.png)

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Try https://codesandbox.io/s/inspiring-yalow-c80dsr
