### ISSUE TITLE
InputNumber 组件控制台报错 TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by 1161853339** [ant-design/ant-design#34730]
### Steps to reproduce

<InputNumber controls={false} size="small" min={100} max={1000}  className="size-input size-input-left" placeholder="宽度" value={size.width} />

### What is expected?

不要报红色的错误

### What is actually happening?

console报错 TypeError: Do not know how to serialize a BigInt

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | React |
| System | Mac 12.0.1 |
| Browser | Chrome 99.0.4844.74 |

**Comment by 1161853339** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/20437338/160264627-98689aba-0f1f-40be-a24c-ca5485a838f7.png">

**Comment by zhao-huo-long** [comment]
Need Reproduce

**Comment by 1161853339** [comment]
不好意思，这个是安装的React Devtool插件的问题，关闭问题了

**Comment by Lawrence51** [comment]
@1161853339 你好，请问你最后是怎么处理的，除了把插件移除还有别的解决方法吗
