### ISSUE TITLE
Nested table vue duplicate records only

### ISSUE THREAD

**Issue by BackWebDev** [ant-design/ant-design#34731]
### Reproduction link

[https://antdv.com/components/table/#components-table-demo-nested-tables](https://antdv.com/components/table/#components-table-demo-nested-tables)

### Steps to reproduce

https://antdv.com/components/table/#components-table-demo-nested-tables
In your example displayed only duplicates for child nodes of each record in the table. But how I can pass different data to each record?

### What is expected?

Expect different data in each record in the table, NOT duplicates for each item inside.

### What is actually happening?

I see these lines inside every table item...
 
const innerData = [];
for (let i = 0; i < 3;   i) {
  innerData.push({
    key: i,
    date: '2014-12-24 23:12:00',
    name: 'This is production name',
    upgradeNum: 'Upgraded: 56',
  });
}

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | Vue |
| System | Mac |
| Browser | Chrome |

---
Sorry for so stupid question, but I cannot find any solution, but I love your package and want to use it in the future. Thanks

**Comment by afc163** [comment]
Wrong repo to report.
