### ISSUE TITLE
可以处理 table expander 的click事件吗

### ISSUE THREAD

**Issue by jzlxiaohei** [ant-design/ant-design#3474]
#### 发生问题的环境是：

- antd 版本: 2.x

#### 您做了什么？
用 `Table`展示树形结构数据时，想处理 前面的`expander-icon`的点击事件。

#### 您期待的结果是：

另外用 `onRowClick`去捕获 e.target，点击`expander-icon` 也捕获不到。

不知道这块能处理吗

**Comment by afc163** [comment]
onExpand

**Comment by jzlxiaohei** [comment]
thanks. 文档上需要更新下

**Comment by afc163** [comment]
来个 PR 如何？

**Comment by jzlxiaohei** [comment]
我去看下了 https://github.com/ant-design/ant-design/blob/master/components/table/index.en-US.md
是不是表格的标题和内容是不是对不上。比如 `description`的内容，现在在`type`下面

**Comment by afc163** [comment]
确实有问题，可以一并修正一下。

**Comment by LiboliboLibolibo** [comment]
前面的图标的点击事件怎么控制？
