### ISSUE TITLE
树组件TreeSelect暴露hover事件callback函数

### ISSUE THREAD

**Issue by zhangdora** [ant-design/ant-design#34745]
### What problem does this feature solve?

用户hover到tree item时，需要知道当前hover到什么节点，并获取该节点数据。

### What does the proposed API look like?

onHover	被hover时调用	function(value, node, extra)

**Comment by afc163** [comment]
做什么需求，TreeSelect 主要职责是选择，感知 hover 操作有点超出组件职责范围了。

**Comment by zhangdora** [comment]
> 

我们的需求是：
1. 需要知道当前鼠标所hover的节点，并实现与另一个节点的hover联动。
2. 多选的情况下，需要根据hover的节点进行逐一删除操作。

**Comment by afc163** [comment]
能给出截图或者具体交互效果么？感觉并不是很合理
