### ISSUE TITLE
树形空间勾选和选择框禁用问题bug

### ISSUE THREAD

**Issue by Magua-Q** [ant-design/ant-design#34743]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shou-kong-cao-zuo-shi-li-antd-4-19-4-forked-pwiesj?file=/index.js)

### Steps to reproduce

1. 访问链接：https://codesandbox.io/s/shou-kong-cao-zuo-shi-li-antd-4-19-4-forked-pwiesj?file=/index.js
2. 设置treeData属性的值
3. 给key为‘0-0’的children属性中的所有item;添加disabled属性

### What is expected?

界面应该是禁用状态并且默认选中

### What is actually happening?

禁用状态生效，但是没有默认选中，但是父节点却是选中状态

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | ^16.14.0 |
| System | mac |
| Browser | chrome版本 99.0.4844.83（正式版本） (x86_64) |
### 如图
<img width="732" alt="image" src="https://user-images.githubusercontent.com/33593848/160316524-c082db5d-d1a1-44d5-becb-27e808fd2037.png">

**Comment by Magua-Q** [comment]
disabled和selectable不兼容？

**Comment by afc163** [comment]
不应该默认选中，你只是指定了父节点选中，业务上的子节点可能需要 disabled + 不选中。各种情况在受控条件下自行选择就好，我们不做特殊判断。

**Comment by Magua-Q** [comment]
@afc163 @yang @edd @jhsu 这算是bug吗？子节点中有一个选中，但是父节点却没有半勾选
如图：
<img width="732" alt="image" src="https://user-images.githubusercontent.com/33593848/160325873-60361e37-70d1-44c4-a622-b96bbc6116e2.png">

```
import React, { useState } from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Tree } from "antd";
const treeData = [
  {
    title: "0-0",
    key: "0-0",
    children: [
      {
        title: "0-0-0",
        key: "0-0-0",
        children: [
          {
            disabled: true,
            title: "0-0-0-0",
            key: "0-0-0-0"
          },
          {
            title: "0-0-0-1",
            key: "0-0-0-1"
          },
          {
            title: "0-0-0-2",
            key: "0-0-0-2"
          }
        ]
      },
      {
        title: "0-0-1",
        key: "0-0-1",
        children: [
          {
            title: "0-0-1-0",
            key: "0-0-1-0"
          },
          {
            title: "0-0-1-1",
            key: "0-0-1-1"
          },
          {
            title: "0-0-1-2",
            key: "0-0-1-2"
          }
        ]
      },
      {
        title: "0-0-2",
        key: "0-0-2"
      }
    ]
  },
  {
    title: "0-1",
    key: "0-1",
    children: [
      {
        title: "0-1-0-0",
        key: "0-1-0-0"
      },
      {
        title: "0-1-0-1",
        key: "0-1-0-1"
      },
      {
        title: "0-1-0-2",
        key: "0-1-0-2"
      }
    ]
  },
  {
    title: "0-2",
    key: "0-2"
  }
];

const Demo = () => {
  const [expandedKeys, setExpandedKeys] = useState(["0-0-0", "0-0-1"]);
  const [checkedKeys, setCheckedKeys] = useState(["0-0-0-0"]);
  const [selectedKeys, setSelectedKeys] = useState([]);
  const [autoExpandParent, setAutoExpandParent] = useState(true);

  const onExpand = (expandedKeysValue) => {
    console.log("onExpand", expandedKeysValue); // if not set autoExpandParent to false, if children expanded, parent can not collapse.
    // or, you can remove all expanded children keys.

    setExpandedKeys(expandedKeysValue);
    setAutoExpandParent(false);
  };

  const onCheck = (checkedKeysValue) => {
    console.log("onCheck", checkedKeysValue);
    setCheckedKeys(checkedKeysValue);
  };

  const onSelect = (selectedKeysValue, info) => {
    console.log("onSelect", info);
    setSelectedKeys(selectedKeysValue);
  };

  return (
    <Tree
      checkable
      onExpand={onExpand}
      expandedKeys={expandedKeys}
      autoExpandParent={autoExpandParent}
      onCheck={onCheck}
      checkedKeys={checkedKeys}
      onSelect={onSelect}
      selectedKeys={selectedKeys}
      treeData={treeData}
    />
  );
};

ReactDOM.render(<Demo />, document.getElementById("container"));

```

**Comment by bigbigDreamer** [comment]
> @afc163 @yang @edd @jhsu 这算是bug吗？子节点中有一个选中，但是父节点却没有半勾选 如图： <img alt="image" width="732" src="https://user-images.githubusercontent.com/33593848/160325873-60361e37-70d1-44c4-a622-b96bbc6116e2.png">
> 
> ```
> import React, { useState } from "react";
> import ReactDOM from "react-dom";
> import "antd/dist/antd.css";
> import "./index.css";
> import { Tree } from "antd";
> const treeData = [
>   {
>     title: "0-0",
>     key: "0-0",
>     children: [
>       {
>         title: "0-0-0",
>         key: "0-0-0",
>         children: [
>           {
>             disabled: true,
>             title: "0-0-0-0",
>             key: "0-0-0-0"
>           },
>           {
>             title: "0-0-0-1",
>             key: "0-0-0-1"
>           },
>           {
>             title: "0-0-0-2",
>             key: "0-0-0-2"
>           }
>         ]
>       },
>       {
>         title: "0-0-1",
>         key: "0-0-1",
>         children: [
>           {
>             title: "0-0-1-0",
>             key: "0-0-1-0"
>           },
>           {
>             title: "0-0-1-1",
>             key: "0-0-1-1"
>           },
>           {
>             title: "0-0-1-2",
>             key: "0-0-1-2"
>           }
>         ]
>       },
>       {
>         title: "0-0-2",
>         key: "0-0-2"
>       }
>     ]
>   },
>   {
>     title: "0-1",
>     key: "0-1",
>     children: [
>       {
>         title: "0-1-0-0",
>         key: "0-1-0-0"
>       },
>       {
>         title: "0-1-0-1",
>         key: "0-1-0-1"
>       },
>       {
>         title: "0-1-0-2",
>         key: "0-1-0-2"
>       }
>     ]
>   },
>   {
>     title: "0-2",
>     key: "0-2"
>   }
> ];
> 
> const Demo = () => {
>   const [expandedKeys, setExpandedKeys] = useState(["0-0-0", "0-0-1"]);
>   const [checkedKeys, setCheckedKeys] = useState(["0-0-0-0"]);
>   const [selectedKeys, setSelectedKeys] = useState([]);
>   const [autoExpandParent, setAutoExpandParent] = useState(true);
> 
>   const onExpand = (expandedKeysValue) => {
>     console.log("onExpand", expandedKeysValue); // if not set autoExpandParent to false, if children expanded, parent can not collapse.
>     // or, you can remove all expanded children keys.
> 
>     setExpandedKeys(expandedKeysValue);
>     setAutoExpandParent(false);
>   };
> 
>   const onCheck = (checkedKeysValue) => {
>     console.log("onCheck", checkedKeysValue);
>     setCheckedKeys(checkedKeysValue);
>   };
> 
>   const onSelect = (selectedKeysValue, info) => {
>     console.log("onSelect", info);
>     setSelectedKeys(selectedKeysValue);
>   };
> 
>   return (
>     <Tree
>       checkable
>       onExpand={onExpand}
>       expandedKeys={expandedKeys}
>       autoExpandParent={autoExpandParent}
>       onCheck={onCheck}
>       checkedKeys={checkedKeys}
>       onSelect={onSelect}
>       selectedKeys={selectedKeys}
>       treeData={treeData}
>     />
>   );
> };
> 
> ReactDOM.render(<Demo />, document.getElementById("container"));
> ```

https://github.com/ant-design/ant-design/issues/34747#issuecomment-1192446474
