### ISSUE TITLE
Checkbox.Group items are not selected

### ISSUE THREAD

**Issue by chesterheng** [ant-design/ant-design#34752]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/use-with-grid-antd-4-19-4-forked-mpx917?file=/Metric.jsx:899-913)

### Steps to reproduce

Click option1 > Click Filters (all filters are checked)
Click option2 > Click Filters (no filter is checked)
Click option3 > Click Filters (no filter is checked)

### What is expected?

Click option1 > Click Filters (all filters are checked)
Click option2 > Click Filters (all filters are checked)
Click option3 > Click Filters (all filters are checked)

### What is actually happening?

Not sure

| Environment | Info |
| --- | --- |
| antd | 4.18.8 |
| React | react |
| System | Window 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
<img width="623" alt="图片" src="https://user-images.githubusercontent.com/507615/160363592-a221359d-a4c1-4604-add5-c769caacb820.png">

Is anything I miss?

**Comment by chesterheng** [comment]
Sorry for the false alarm. I replaced defaultValue with value props in Checkbox Group and it works.
