### ISSUE TITLE
2.1Badge设置了status="processing"后貌似 颜色和动作都不对了。

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#3475]
#### 发生问题的环境是：

- antd 版本:2.1
- 操作系统及其版本:win10
- 浏览器及其版本:chrome 54

http://codepen.io/xjdata/pen/WGadyq?editors=001

**Comment by afc163** [comment]
请按照演示的代码进行使用。

**Comment by xjdata** [comment]
额。。。貌似是2.01和2.1的区别。 2.01的时候是正常的。  那就是说新版的不能包裹标签后依然进行颜色和动画的区分了。 按照演示的来，包裹某个对象后徽标就是红色固定的了。

**Comment by benjycui** [comment]
现在 Badge 状态点必须是 standalone 的，不能包裹 children。
