### ISSUE TITLE
Cascader无法选择children

### ISSUE THREAD

**Issue by Full-Stack-ClarkChu** [ant-design/ant-design#34750]
### Reproduction link

[https://codesandbox.io/s/yi-ru-zhan-kai-antd-4-19-4-forked-svifvm?file=/index.js](https://codesandbox.io/s/yi-ru-zhan-kai-antd-4-19-4-forked-svifvm?file=/index.js)

### Steps to reproduce

Cascader无法选择children，expandTrigger="hover"模式下，只能选择第一层选项；expandTrigger="click"模式下，选择第一层，第二层子菜单会展开，但是第二层立刻又消失了，第一层被选中。

### What is expected?

点击第一层能够展开children选项

### What is actually happening?

点击第一层能够展开children选项

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 17.0.2 |
| System | macOS、windows |
| Browser | chrome 99.0.4844.84 |

**Comment by Full-Stack-ClarkChu** [comment]
> 

重现地址：https://codesandbox.io/s/yi-ru-zhan-kai-antd-4-19-4-forked-svifvm?file=/index.js

**Comment by imoctopus** [comment]
数据不对，isLeaf 应该是 boolean ， 查看正确数据地址：https://codesandbox.io/s/antd-34750-bkp1dk?file=/src/App.js

https://github.com/react-component/cascader/blob/a0efe2e1a0acc4faea827f56dd74aafd2a02ae05/src/utils/commonUtil.ts#L35-L37
rc-cascader 需要判断下 option.isLeaf 为 boolean
@Full-Stack-ClarkChu @afc163

**Comment by MadCcc** [comment]
> 数据不对，isLeaf 应该是 boolean ， 查看正确数据地址：https://codesandbox.io/s/antd-34750-bkp1dk?file=/src/App.js
> 
> https://github.com/react-component/cascader/blob/a0efe2e1a0acc4faea827f56dd74aafd2a02ae05/src/utils/commonUtil.ts#L35-L37 rc-cascader 需要判断下 option.isLeaf 为 boolean @Full-Stack-ClarkChu @afc163

判断 isLeaf 为 boolean 也不能解决写成 `'false'` 的问题。。感觉这实际上是用法问题，有 work 的 demo，先关闭了。

**Comment by Full-Stack-ClarkChu** [comment]
收到，感谢！我这边优化一下数据。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月29日(星期二) 中午11:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] Cascader无法选择children (Issue #34750)





  
数据不对，isLeaf 应该是 boolean ， 查看正确数据地址：https://codesandbox.io/s/antd-34750-bkp1dk?file=/src/App.js
 
https://github.com/react-component/cascader/blob/a0efe2e1a0acc4faea827f56dd74aafd2a02ae05/src/utils/commonUtil.ts#L35-L37 rc-cascader 需要判断下 option.isLeaf 为 boolean @Full-Stack-ClarkChu @afc163
  
判断 isLeaf 为 boolean 也不能解决写成 'false' 的问题。。感觉这实际上是用法问题，有 work 的 demo，先关闭了。
 
&mdash;
