### ISSUE TITLE
RangePicker设置disabledDate，当鼠标晃动，禁用日期（2月28日）会意外改变

### ISSUE THREAD

**Issue by shaw-Lee** [ant-design/ant-design#34754]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5rrbb9?file=/index.js)

### Steps to reproduce

~~~
<RangePicker showTime
                                         inputReadOnly
                                         allowClear
                                         disabledDate={(curent) => {
return current > moment() || current <= moment().subtract(1,'months');
}
                            />
~~~

### What is expected?

禁用今天之后和一个月以前的日期

### What is actually happening?

当鼠标在面板晃动时，日期（2月28日）在禁用和未被禁用之间切换

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 17.0 |
| System | win10 |
| Browser | chrome 99.0.x |

**Comment by afc163** [comment]
`moment()` 是不稳定的，最好比较对象稳定下来。

https://codesandbox.io/s/antd-reproduction-template-forked-on4kc6?file=/index.js

**Comment by afc163** [comment]
发现另一个问题 https://github.com/ant-design/ant-design/issues/34755
