### ISSUE TITLE
嵌套的二级列表使用scroll和fixed会导致一级列表撑开

### ISSUE THREAD

**Issue by doing123** [ant-design/ant-design#34761]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qian-tao-zi-biao-ge-antd-4-19-3-forked-eel1mb?file=/index.js)

### Steps to reproduce

嵌套子列表中，要求action列fix，由于二级列表colume太多使用scroll.x想要支持滚动。

### What is expected?

二级列表中的action列fix right，且 二级列表滚动

### What is actually happening?

导致一级列表撑开滚动

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
可以试试这么写： https://codesandbox.io/s/qian-tao-zi-biao-ge-antd-4-19-3-forked-ft0mx8?file=/index.js
