### ISSUE TITLE
Checkbox component support button style like Radio component

### ISSUE THREAD

**Issue by FOWind** [ant-design/ant-design#34769]
### What problem does this feature solve?

1. Checkbox component has the similar button style with the Radio component

### What does the proposed API look like?

1.  default button style

    ```
    <Checkbox onChange={onChange}  optionType="button">Checkbox</Checkbox>
    ```
2.  solid button style 

    ```
    <Checkbox onChange={onChange}  optionType="button" optionType="button" buttonStyle="solid">Checkbox</Checkbox>
    ```

**Comment by afc163** [comment]
Try https://procomponents.ant.design/components/check-card
