### ISSUE TITLE
关于组件步骤条Steps

### ISSUE THREAD

**Issue by liyi00** [ant-design/ant-design#34762]
### Reproduction link

[https://ant.design/components/steps-cn/#API](https://ant.design/components/steps-cn/#API)

### Steps to reproduce

![微信截图_20220329095955.png](https://s2.loli.net/2022/03/29/mqWZh6uM5JYjdQg.png)

### What is expected?

https://s2.loli.net/2022/03/29/soQNHjkgCK2TUeX.png

### What is actually happening?

![微信截图_20220329100150.png](https://s2.loli.net/2022/03/29/anlbtuB5C2jQOZg.png)

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 16.8 |
| System | window11 |
| Browser | Google Chrome |

---
重现步骤是现在使用组件Steps步骤条的效果，可以有进行中procsss或者是finish来表现，error来表现错误的步骤，然后搁置的状态可以使用wait灰色的statue，但是缺少一个warning警告标识的Step，期望加上警告色的step步骤，期望色如上图期望结果中原型中的颜色一样，实际结果希望在Steps中的status中增加一个状态，warning以便于用户使用

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/34763
