### ISSUE TITLE
Add built-in loading indicator for Form

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#34768]
### What problem does this feature solve?

- blocking all inputs after submit button was clicked
- showing a message for a user, e.g. "Validating creation...", "Submitting your application..."
- I'm currently using the approach where I wrap a form with `<Spin>` but this create issues, see [this example](https://codesandbox.io/s/antd-reproduction-template-forked-35spmr), when you submit the form you will see the input's value showing the default value from `initialValues` of the input instead of the one being submitted

### What does the proposed API look like?

`<Form loading={submitted} />`

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-vbkbic?file=/index.js

We need to dig why Form render initialValues after Spin is shown.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-vbkbic?file=/index.js

I think it is a bug.

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-c40zwu
Try to use `spinning` to control loading? Change of DOM make Form mount again and return to initial state.

**Comment by csandanov** [comment]
that's a very elegant solution, thank you
but adding `spinning`/`loading` to `Form` itself would be even more cool

**Comment by MadCcc** [comment]
It's still a bug since form is used to control form values. We'll try to fix it.

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/issues/33981

**Comment by vitalijalbu** [comment]
I also want this feature, like card does.. simply

**Comment by moon548834** [comment]
if you are using form with dialog 
my practice is using Modal + form(modalRender) + okButtonProps(loading: xxx)
sth looks like this:
```
const [isLoading, setIsLoading] = React.useState(false);
return (
  <Modal
    okButtonProps={{loading: isLoading}}
    modalRender={dom => (
        <Form> {dom} </Form>
    )
  >
    // your <Form.Item />
  </Modal>
)
```
