### ISSUE TITLE
关于组件步骤条Steps

### ISSUE THREAD

**Issue by liyi00** [ant-design/ant-design#34763]
### What problem does this feature solve?

![微信截图_20220329100014.png](https://s2.loli.net/2022/03/29/soQNHjkgCK2TUeX.png)

### What does the proposed API look like?

重现步骤是现在使用组件Steps步骤条的效果，可以有进行中procsss或者是finish来表现，error来表现错误的步骤，然后搁置的状态可以使用wait灰色的statue，但是缺少一个warning警告标识的Step，期望加上警告色的step步骤，期望色如上图期望结果中原型中的颜色一样，实际结果希望在Steps中的status中增加一个状态，warning以便于用户使用

**Comment by liyi00** [comment]
希望Steps步骤条追加一个status，warning警告的标识，警告色如上图所示

**Comment by afc163** [comment]
感觉这是 https://ant.design/components/timeline-cn/ 。

**Comment by HQ1363** [comment]
不一样吧，一个是步骤条，一个是时间线组件

**Comment by hacker0limbo** [comment]
不知道这个 issue 因为什么原因关闭的? 后期有计划对于 step 组件的 status 加上 warning 这个枚举吗? 或者说, 是否可以类似 `Tag` 组件一样, 既提供预设值比如 `procsss` 或者 `finish` 这种, 也可以手动给定颜色比如预设的颜色 `purple` 或者自定义颜色 `#87d068`?
