### ISSUE TITLE
select自定义多选，会删除选中的最后一个内容

### ISSUE THREAD

**Issue by hahaniu666** [ant-design/ant-design#34772]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-xia-la-antd-4-19-4-forked-ur25xg?file=/index.js)

### Steps to reproduce

点开下拉框，在search中输入搜索内容 1，然后点击全选，会选中52条数据，然后删除输入框中的1，就会删除最后一条，变成选中51条内容

### What is expected?

期望删除输入框中的元素时，不删除已选中的内容。

### What is actually happening?

删除输入框中的元素，会删除已选中的内容

| Environment | Info |
| --- | --- |
| antd | 4.5.3 |
| React | react@16.14.0 |
| System | windows |
| Browser | chrome 70  |

---
业务希望实现此种操作方式的下拉框

**Comment by MadCcc** [comment]
给你的 Input 加上 `onKeyDown={(e) => e.stopPropagation()}` 就可以解决，冒泡触发了删除逻辑。

**Comment by hahaniu666** [comment]
> 

好的，谢谢，只想着给外层加onKeyDown，没想到内层，思维禁锢了
