### ISSUE TITLE
Switch开关 样式问题

### ISSUE THREAD

**Issue by WDDWDDWDD** [ant-design/ant-design#34774]
### Reproduction link

[https://ant.design/components/switch-cn/](https://ant.design/components/switch-cn/)

### Steps to reproduce

switch样式错乱

### What is expected?

switch样式错乱

### What is actually happening?

switch样式错乱

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | antd官网 |
| System | mac |
| Browser | 版本 81.0.4044.138（正式版本） （64 位） |

**Comment by WDDWDDWDD** [comment]
![2222](https://user-images.githubusercontent.com/16702719/160614665-b42dac29-8216-4ece-bc94-bf109cde0ee1.png)

**Comment by afc163** [comment]
<img width="420" alt="图片" src="https://user-images.githubusercontent.com/507615/160735639-d49c4afe-f1f8-49a9-bb45-c15538150897.png">

官网样式渲染出来都变成 inset 了。@zombieJ @MadCcc 看看

**Comment by afc163** [comment]
https://github.com/evanw/esbuild/issues/1925
