### ISSUE TITLE
Tooltip 右侧或者底部箭头显示问题

### ISSUE THREAD

**Issue by WDDWDDWDD** [ant-design/ant-design#34773]
### Reproduction link

[https://ant.design/components/tooltip-cn/](https://ant.design/components/tooltip-cn/)

### Steps to reproduce

chorme 90以下版本

### What is expected?

箭头显示

### What is actually happening?

箭头显示异常

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | antd 官网版本 |
| System | mac |
| Browser | 版本 81.0.4044.138（正式版本） （64 位） |

**Comment by WDDWDDWDD** [comment]
![Uploading 111.png…]()

**Comment by WDDWDDWDD** [comment]
![111](https://user-images.githubusercontent.com/16702719/160614409-cd12dc79-8b47-4e7d-ae25-0b0945a1702a.png)

**Comment by afc163** [comment]
应该是一个问题 https://github.com/ant-design/ant-design/issues/34774#issuecomment-1082538301
