### ISSUE TITLE
antd table组件排序拦截

### ISSUE THREAD

**Issue by heningyuan6256** [ant-design/ant-design#34780]
### What problem does this feature solve?

我当前的表格使用到了滚动加载，行内编辑，以及服务端排序，行内编辑采用的是前端临时保存，最后点击保存调用后台，所以当行内编辑之后，再点击排序我希望能够给用户一个警告，目前有未保存的编辑行，请确认是否排序重新加载

### What does the proposed API look like?

增加排序拦截方法

**Comment by afc163** [comment]
可以用 onChange 开启受控模式进行拦截。
