### ISSUE TITLE
Button always show loading spinner on React 18 with StrictMode

### ISSUE THREAD

**Issue by mayef** [ant-design/ant-design#34788]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jia-zai-zhong-zhuang-tai-antd-4-19-4-forked-lmzfzj)

### Steps to reproduce

1. package.json: 替换react, react-dom版本为18.0.0
2. index.js: 替换ReactDOM.render为createRoot, 并添加<React.StrictMode>

### What is expected?

与官网demo相同
https://codesandbox.io/s/sdpcy1

### What is actually happening?

第二行第一个Button初始状态是loading，且状态不受this.state.loadings[0]影响

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Chrome 99.0.4844.84 |

**Comment by afc163** [comment]
Trace #26136

**Comment by afc163** [comment]
开着先，具体细节问题应该会有不少。

**Comment by afc163** [comment]
https://codesandbox.io/s/jia-zai-zhong-zhuang-tai-antd-4-19-4-forked-1nz2ie?file=/index.js

严格模式下，啥都不写也会出一个 loading 图标，初步判断和 rc-motion 有关系。

**Comment by afc163** [comment]
只有 createRoot 和 StrictMode 同时作用时才会出现，和 rc-motion 里的逻辑有关系，状态有点复杂排查不下去了。

**Comment by burning0xb** [comment]
有解决方案了吗

**Comment by tmkx** [comment]
@afc163 This PR(https://github.com/react-component/motion/pull/24) will fix this issue (and https://github.com/ant-design/ant-design/issues/34850).

https://github.com/react-component/util/pull/287, https://github.com/ant-design/ant-design/pull/34858 will fix: https://github.com/ant-design/ant-design/issues/34814

https://github.com/react-component/util/pull/288, https://github.com/react-component/trigger/pull/289 will fix: https://github.com/ant-design/ant-design/issues/34805, https://github.com/ant-design/ant-design/issues/34810, https://github.com/ant-design/ant-design/issues/34856 and so on that relevant with `Trigger`

For proof, you can check this repo: https://github.com/tmkx/react-18-rc.

**Comment by afc163** [comment]
@zombieJ 和 @MadCcc 统一看看

**Comment by tmkx** [comment]
resetting `mountedRef` on unmount works
https://github.com/react-component/motion/blob/981f60cc7ca592df8ced4e3ab3453e228f99df53/src/hooks/useStatus.ts#L55-L56

https://github.com/react-component/motion/pull/24/files#diff-4fddd5156b9e8675a8c9fae21de28f59c37f65f95b70c51dea1266da83b86c2aR220-R225

**Comment by zombieJ** [comment]
> resetting `mountedRef` on unmount works https://github.com/react-component/motion/blob/981f60cc7ca592df8ced4e3ab3453e228f99df53/src/hooks/useStatus.ts#L55-L56
> 
> https://github.com/react-component/motion/pull/24/files#diff-4fddd5156b9e8675a8c9fae21de28f59c37f65f95b70c51dea1266da83b86c2aR220-R225

aha, we got the same point : )

**Comment by zombieJ** [comment]
All the code should check mountRef or destroyRef related logic to ensure destroy mark is not one time configured.
