### ISSUE TITLE
table scroll

### ISSUE THREAD

**Issue by ohmyauthentic** [ant-design/ant-design#3478]
- antd 版本:2.0.1
- 操作系统及其版本:macosx
- 浏览器及其版本:chrome

#### 您做了什么？

将浏览器resize ，table长度超出了屏幕宽度，没有出现scroll效果。
scroll.x 的长度是大于所有非固定列和就行了吗
#### 您期待的结果是：

像官网一样正常显示 

#### 实际上的结果是：
table长度超出了屏幕宽度，没有出现scroll效果。
#### 可重现的在线演示

![17bec7ae-78cd-4dfd-9d7e-16fe15f1b0ca](https://cloud.githubusercontent.com/assets/5073389/19502856/28c8a4e6-95e2-11e6-9bb2-41d4d95d6860.png)

是不是因为mainlayout的问题，我换了一个mainlayout之后就正常了，这个mainlayout是官方demo里面的呀

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
scroll.x 应该大于表格的宽度。
