### ISSUE TITLE
Cascader多选时候，默认值defaultValue，不能显示多个，只能是最后一个值

### ISSUE THREAD

**Issue by Miiskye** [ant-design/ant-design#34792]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-antd-4-19-4-forked-h5j4vr?file=/index.js)

### Steps to reproduce

设置defaultValue可重现

### What is expected?

defaultValue里设置哪些id默认选中哪些枚举

### What is actually happening?

defaultValue设置无效或者有bug

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 16.9.17 |
| System | macOs |
| Browser | Chrome浏览器（80.0.3987.16） |

**Comment by afc163** [comment]
```diff
-       defaultValue={["bamboo", 2]}
+      defaultValue={[["bamboo", 2]]}
```

**Comment by afc163** [comment]
https://codesandbox.io/s/duo-xuan-antd-4-19-4-forked-wf8s44

https://github.com/ant-design/ant-design/issues/34486#issuecomment-1066571704
