### ISSUE TITLE
[BUG] PostCSS compile error because missing value ant-primary-color-deprecated-pure in node_modules/antd/dist/antd.variable.css or /components/style/themes/variable.less

### ISSUE THREAD

**Issue by kimthangatm** [ant-design/ant-design#34807]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/style/themes/variable.less#L33](https://github.com/ant-design/ant-design/blob/master/components/style/themes/variable.less#L33)

### Steps to reproduce

```sh
npm init -y
yarn add antd
```
Check these file: 
`node_modules/antd/dist/antd.variable.css` this file related to https://github.com/ant-design/ant-design/blob/master/components/style/themes/variable.less#L33

### What is expected?

Compile success

### What is actually happening?

Compile error: TypeError: Cannot read property 'raws' of undefined
```
ERROR in ./node_modules/.pnpm/registry.npmjs.org antd@4.19.3_react-dom@17.0.2 react@17.0.2/node_modules/antd/dist/antd.variable.less (../../../../../../home/kt/.bvm/versions/0.0.687/bit-0.0.687/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[6].use[1]!../../../../../../home/kt/.bvm/versions/0.0.687/bit-0.0.687/node_modules/@teambit/react/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[6].use[2]!../../../../../../home/kt/.bvm/versions/0.0.687/bit-0.0.687/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[6].use[3]!../../../../../../home/kt/.bvm/versions/0.0.687/bit-0.0.687/node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[6].use[4]!./node_modules/.pnpm/registry.npmjs.org antd@4.19.3_react-dom@17.0.2 react@17.0.2/node_modules/antd/dist/antd.variable.less)
Module build failed (from ../../../../../../home/kt/.bvm/versions/0.0.687/bit-0.0.687/node_modules/@teambit/react/node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'raws' of undefined
```

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Chrome |

**Comment by kimthangatm** [comment]
I close this issue, because some package in @teambit/react use lower version of postcss preset env

```
"postcss-preset-env": "6.7.0",
```

Update to `"7.4.3"` to resolve.

**Comment by jmeleropager** [comment]
There is no need to reproduce it, here is the issue https://github.com/ant-design/ant-design/blob/844905774a8f0cbcf5dc51f1eace55b976ccb8df/scripts/css-variable-sync.js#L66

That variable has no value, this generates an invalid css file.
