### ISSUE TITLE
Select cannot open in React 18

### ISSUE THREAD

**Issue by Serkey** [ant-design/ant-design#34805]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-fire-mqzioq?file=/src/App.js)

### Steps to reproduce

点击Select选择器，会发现无法弹出选项

### What is expected?

点击Select选择器，正常弹出选项

### What is actually happening?

点击Select选择器，会发现无法弹出选项

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 18.0.0 |
| System | macOS 12.1 |
| Browser | Chrome 版本 100.0.4896.60（正式版本） (x86_64) |

**Comment by liuye1296** [comment]
Dropdown 这个 组件也G了  直接浏览器卡死

**Comment by you-heng** [comment]
Select组件 无法弹出就算了，浏览器还直接卡死

**Comment by zombieJ** [comment]
resolve by:
* https://github.com/react-component/trigger/pull/291
* https://github.com/react-component/util/pull/288
* https://github.com/react-component/util/pull/291

**Comment by mengbo-ji** [comment]
> 
Dropdown.Button 也卡死了，请问有解决方案吗

**Comment by u007** [comment]
is the latest select fixed? how do we get the updare?

**Comment by adnan-sheikh** [comment]
I'm facing this issue as well, cannot open the dropdown while in `StrictMode`. If i disable StrictMode, it works but that browser tab freezes

**Comment by zdJOJO** [comment]
我也遇见了同样的问题，  如何解决

**Comment by gd-ldj** [comment]
这个看已经closed，有解决吗？react升级后出现select卡死，ant升级到最新还是会卡死

**Comment by adnan-sheikh** [comment]
It would be better if @zombieJ replied what exactly needs to be done

**Comment by skusnierz** [comment]
@zombieJ have all ant-design components already received support for React 18?

**Comment by zhengjunxin** [comment]
Same problem in antd version 4.21.6

**Comment by u007** [comment]
it is solved on my end

**Comment by adnan-sheikh** [comment]
> it is solved on my end, same 4.21.6

@u007 I tried with this version yesterday, but then as well it was not working

**Comment by u007** [comment]
try adding these 
"rc-picker": "~2.6.10",
    "rc-select": "^14.1.8",
    "rc-util": "^5.22.5",

**Comment by adnan-sheikh** [comment]
As a dev dependency?

**Comment by adnan-sheikh** [comment]
Nope, it doesn't work for me @u007

**Comment by adnan-sheikh** [comment]
For my project, I deleted the lock file and re-installed with updated packages `antd v4.21.6`, `react and react-dom v18.2.0`. And now, it's working

**Comment by tmtnckff** [comment]
> For my project, I deleted the lock file and re-installed with updated packages `antd v4.21.6`, `react and react-dom v18.2.0`. And now, it's working. No need to add any additional dependencies

Thank you, that resolved it for me
