### ISSUE TITLE
select多选(multiple)模式时，

### ISSUE THREAD

**Issue by chengandpeng** [ant-design/ant-design#3480]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: Mac OS Sierra
- 浏览器及其版本: Chrome 54

#### 您做了什么？
套用官方例子的，并且在<Option>中增加了一个tagId的参数
```javascript
import { Select } from 'antd';
const Option = Select.Option;

const children = [];
for (let i = 10; i < 36; i++) {
  children.push(<Option tagId={i} key={i.toString(36) + i}>{i.toString(36) + i}</Option>);
}

function handleChange(value) {
  console.log(`selected ${value}`);
}

ReactDOM.render(
  <Select multiple onChange={handleChange}>
    {children}
  </Select>
, mountNode);
```

#### 您期待的结果是：
选取选项后拿到当前选项tagId的值

#### 实际上的结果是：
只能拿到key的值

#### 业务需求：
1.必须返回选项的对应ID给后台。
2.因为select是通过key来匹配结果，所以key不能填写id，得和label值一致。

#### 尝试过的方法：
通过onSelect(value,option)的option拿到tagId的值，但是需要创建一个全局变量来管理，
删除的时候还得更新list，实现起来有点笨拙。
```javascript
<Select multiple onDeselect={this.handleDeselectTags} onSelect={this.handleSelectTags}>
 { children }
</Select>
```
```javascript
let tagsList = [];

//取消标签后更新list
handleDeselectTags(value) {
    let temp = tagsList.filter(tag => tag.value != value);
    tagsList = temp;
}

//选择标签后将标签名称和id加入list
handleSelectTags(value, option) {
    tagsList.push({id: option.props.tagId, value});
} 
```

## 有没有比较方便的实现方式？ 谢谢

**Comment by benjycui** [comment]
把 `tagId` 设为 `value`，同时使用 `filterOption`  https://ant.design/components/select/#Select-props

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
