### ISSUE TITLE
React 18 下 Image 的 preview 无效

### ISSUE THREAD

**Issue by ymjrcc** [ant-design/ant-design#34813]
### Reproduction link

[https://stackblitz.com/edit/react-y33gzl?file=index.js](https://stackblitz.com/edit/react-y33gzl?file=index.js)

### Steps to reproduce

使用 React 18.0.0 版本，用 createRoot 方法，在 StrictMode 下即可复现

### What is expected?

点击图片可以正常预览

### What is actually happening?

预览功能大概率无法正常使用，只有小概率可以正常弹出

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React |  18.0.0 |
| System | macOS 12.2.1 |
| Browser | Chrome 99.0 |

**Comment by zombieJ** [comment]
> resolve by:
> 
> * https://github.com/react-component/trigger/pull/291
> * https://github.com/react-component/util/pull/288
> * https://github.com/react-component/util/pull/291
