### ISSUE TITLE
Cannot read properties of null (reading 'removeEventListener') error appears after updating Ant Design version in tests where Select Component is present

### ISSUE THREAD

**Issue by skorinov** [ant-design/ant-design#34816]
### Reproduction link

[https://github.com/skorinov/antd-jest-bug](https://github.com/skorinov/antd-jest-bug)

### Steps to reproduce

1. Clone the repo
2. Run yarn install
3. Run yarn test
4. Check terminal

### What is expected?

Test should pass successfully

### What is actually happening?

Test crashes

```
 console.error
    Error: Uncaught [TypeError: Cannot read properties of null (reading 'removeEventListener')]

console.error
    The above error occurred in the <List> component:

Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
```

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 18.0.0 |
| System | MacOS Big Sur 11.6 |
| Browser | Chrome Version 99.0.4844.83 |

---
This issue only appears in tests when using Select Component. If I remove it, the test will pass successfully.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/virtual-list/pull/163, let me release a new patch of rc-virtual-list.

**Comment by afc163** [comment]
https://github.com/react-component/virtual-list/releases/tag/v3.4.6

Please remove yarn.lock and reinstall node_modules.
