### ISSUE TITLE
React 18.0.0 中 Popconfirm 气泡无法弹出

### ISSUE THREAD

**Issue by YuJian920** [ant-design/ant-design#34810]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elastic-pine-yvfcz9?file=/src/App.js)

### Steps to reproduce

```javascript
import "./styles.css";
import { Popconfirm } from 'antd';

export default function App() {
  return (
    <div className="App">
      <h1>Popconfirm</h1>
      <Popconfirm title="Are you sure？" okText="Yes" cancelText="No">
        <a href="#">Delete</a>
      </Popconfirm>
    </div>
  );
}
```

### What is expected?

弹出气泡

### What is actually happening?

无法弹出，卡死

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 18.0.0 |
| System | Windows 10 21H1 |
| Browser | Microsoft Edge 版本 99.0.1150.55 (正式版本) (64 位) |

**Comment by YuJian920** [comment]
只要是需要弹出气泡的组件都会出现问题，还可能会导致浏览器卡死

**Comment by sabertazimi** [comment]
目前我这边发现会直接导致页面直接卡死崩溃的组件包括 `<Tooltip>` 和 `<Popover>`.

**Comment by supriome** [comment]
Any Update?

**Comment by zombieJ** [comment]
Already fixed in `4.20.0-alpha`. Close:

https://codesandbox.io/s/awesome-waterfall-o5e2dp?file=/src/App.js

**Comment by nanxiaobei** [comment]
这个 Popconfirm 官方文档的 demo，`4.20.0-alpha`。
点击可以弹出，但再点击 No 或 Yes 按钮，就又卡死了。
https://codesandbox.io/s/urxkv4?file=/index.js

**Comment by zombieJ** [comment]
https://codesandbox.io/s/youthful-montalcini-ds16zr?file=/src/App.js

codesandbox 的问题，它会劫持 console 导致递归死循环。去掉 console 就好了

**Comment by JarvisArt** [comment]
我也遇到这个问题，select、menu、凡是有下拉弹窗的组件都会导致页面奔溃

**Comment by JarvisArt** [comment]
我也遇到这个问题，select、menu、凡是有下拉弹窗的组件都会导致页面奔溃，我用的谷歌浏览器（版本 102.0.5005.63）和 Edge 都会出现这种情况，有什么解决办法吗？ @zombieJ

**Comment by zombieJ** [comment]
> 我也遇到这个问题，select、menu、凡是有下拉弹窗的组件都会导致页面奔溃，我用的谷歌浏览器（版本 102.0.5005.63）和 Edge 都会出现这种情况，有什么解决办法吗？ @zombieJ

提供一下复现，开个新 issue 哈~~
