### ISSUE TITLE
React 18 下 BackTop 组件无法显示

### ISSUE THREAD

**Issue by ymjrcc** [ant-design/ant-design#34814]
### Reproduction link

[https://stackblitz.com/edit/react-bwwwus?file=index.js](https://stackblitz.com/edit/react-bwwwus?file=index.js)

### Steps to reproduce

 使用 React 18.0.0 版本，用 createRoot 方法，在 StrictMode 下即可复现

### What is expected?

可以正常使用 BackTop 组件

### What is actually happening?

无法显示该组件

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React |  18.0.0 |
| System | macOS 12.2.1 |
| Browser | Chrome 99.0 |

**Comment by yicrotkd** [comment]
Probably the same cause as https://github.com/ant-design/ant-design/issues/34788.
