### ISSUE TITLE
expose @base-primary to be set in styles/theme/variable.less

### ISSUE THREAD

**Issue by nichtsam** [ant-design/ant-design#34825]
### What problem does this feature solve?

Currently overriding @base-primary in variable.less is not an option, because it is scoped in the html tag.  
It should be global and editable in order to have the css variables based on the theme base color.  

Now theme is changeable via overriding @primary-color, but this causes a difficulty for writing additional css that matches the theme.

### What does the proposed API look like?

```less
// your-theme-file.less

@base-primary: <color>;
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/34602

**Comment by zombieJ** [comment]
Close since v5 use CSS-in-JS. It's not an issue any more.
