### ISSUE TITLE
Tooltip文字提示 方向箭头变形

### ISSUE THREAD

**Issue by zhc18244666699** [ant-design/ant-design#34828]
### Reproduction link

[https://ant.design/components/tooltip-cn/](https://ant.design/components/tooltip-cn/)

### Steps to reproduce

antd官网

### What is expected?

正常显示

### What is actually happening?

变形

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 17.0 |
| System | window |
| Browser |  (谷歌)86.0.4240.198 |

---
不确实 是不是本人浏览器的问题。

**Comment by MadCcc** [comment]
截个图看看？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/34774#issuecomment-1082866344
