### ISSUE TITLE
Input TextArea Show Count Words

### ISSUE THREAD

**Issue by robertocerdasilva** [ant-design/ant-design#34826]
### What problem does this feature solve?

Currently "showCount" does the character count, not the word count. That is, if I have typed: "hello", the counter will show 4 and not 1.

### What does the proposed API look like?

```
<Input.TextArea 
      showCount 
      count="words" 
      maxLength={ 100 } 
/>

<Input.TextArea 
      showCount 
      count="character" 
      maxLength={ 100 } 
/>
```

OR:

```
<Input.TextArea 
      showCount 
      wordsCount
      maxLength={ 100 } 
/>

<Input.TextArea 
      showCount 
      characterCount
      maxLength={ 100 } 
/>
```

**Comment by afc163** [comment]
We have no plan to support word count feature, and `showCount` could be a function.

**Comment by robertocerdasilva** [comment]
@afc163 And why not leave an option to take into account?
