### ISSUE TITLE
input不支持maxlength属性吗？

### ISSUE THREAD

**Issue by taotiehai** [ant-design/ant-design#3482]
发生问题的环境是：mac

- antd 版本:1.x
- 操作系统及其版本:10.10

引入 antd 了 input
设置maxlength无效果

**Comment by afc163** [comment]
#3479 这样很不礼貌。

**Comment by taotiehai** [comment]
@afc163 不许提问题？

**Comment by afc163** [comment]
已经回答你了，为何要提重复的问题呢？

**Comment by taotiehai** [comment]
@afc163 “开这种 issue 太随意了。”  这样的回答？

**Comment by afc163** [comment]
在开 issue 前尝试先搜索 issues。另外建议先做好功课，避免问那些查阅手册就能解决的问题，毕竟维护人员的精力都是有限的。

建议阅读 [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way) 和了解 [RTFM](http://baike.baidu.com/link?url=XwPvCv2aiGdBda7wgbWSh05nXq16Z5JDaLY2JxAYbp0uce7dlKyFWai2ZNX1UwDRfw_SpnDqeDi4mdNuWA77NK) 这样的术语。
