### ISSUE TITLE
升级 React18 后 message, notification两个组件会提示警告

### ISSUE THREAD

**Issue by fschenkun22** [ant-design/ant-design#34823]
### Reproduction link

[https://codepen.io/ 并没有找到react18](https://codepen.io/ 并没有找到react18)

### Steps to reproduce

只要在react18中使用这两个组件 就会提示 ReactDOM.render is no longer supported in React 18

### What is expected?

浏览器控制台不提示ReactDOM.render is no longer supported in...

### What is actually happening?

Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | v18.0.0 |
| System | Windows 11 专业版 22H2 |
| Browser | Chrome 版本 100.0.4896.60（正式版本） （64 位） |

---
只要更新成React 18 只要使用  message, notification两个组件 就会报这个错误

**Comment by PovilasKirna** [comment]
Same problem here hoping for a fix

**Comment by Lexyguo** [comment]
Modal 组件也会报这个错误，应该是一样的问题

**Comment by zhangyizhou99** [comment]
Same problem when using <Modal>

**Comment by zpc7** [comment]
Based on the issue description, I built an example, [Reproduction link](https://codesandbox.io/s/react-18-environment-a-warning-will-appear-when-using-message-4v9otu)

**Comment by zpc7** [comment]
Based on the issue description, I built an example, [Reproduction link](https://codesandbox.io/s/react-18-environment-a-warning-will-appear-when-using-message-4v9otu)

**Comment by tlt254** [comment]
Same problem

**Comment by KinXpeng** [comment]
Same problem in React 18,hoping a solution.

**Comment by hmthanh** [comment]
Thanks for anyone could suggest the solution

**Comment by zpc7** [comment]
I tried to submit a PR to solve this problem, but encountered a strange problem, welcome to join the discussion, you can view the associated draft PR in the Issue:
https://github.com/react-component/notification/issues/192

**Comment by grave5211** [comment]
同样的问题

**Comment by lap888** [comment]
+1 the same q.

**Comment by fangqiuyun** [comment]
+1 the same q.

**Comment by yuuko-1410** [comment]
直接这样写可以解决
import { message } from 'antd';
message.info('This is a message');

**Comment by ZhangWillYu** [comment]
Don't user the hooks, like `const [messageApi, contextHolder] = message.useMessage()`. You can use 
`
import {message} from 'antd'

function app () {
   return (
       <Button @click={() => message.info('Message info.')}>Show message</Button>
   )
}
`

**Comment by lucabubi** [comment]
> Don't use the hooks, like `const [messageApi, contextHolder] = message.useMessage()`. You can use
> 
> ```
> import {message} from 'antd'
> 
> function app () {
>    return (
>        <Button @click={() => message.info('Message info.')}>Show message</Button>
>    )
> }
> ```

Without using hooks it's working! Thanks!
