### ISSUE TITLE
SubMenu 在ie 11 里面 除了第一个可以显示二级菜单，后面的菜单都无法弹出二级菜单

### ISSUE THREAD

**Issue by ikonan** [ant-design/ant-design#34832]
### Reproduction link

[https://react-wpgwra.stackblitz.io/](https://react-wpgwra.stackblitz.io/)

### Steps to reproduce

1.创建一个menu mode='horizontal'
2.在ie 11 浏览器预览
3.第一个菜单可以显示二级菜单，后面的菜单都无法显示二级菜单

### What is expected?

在IE 11浏览器能够正常显示所有的二级菜单

### What is actually happening?

在IE 11浏览器无法弹出二级菜单

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17.x |
| System | window11 |
| Browser | ie11 |

---
1. 水平菜单模式才会出现这个问题

**Comment by afc163** [comment]
Duplicate of #31283
