### ISSUE TITLE
Input.search中文输入法下输入拼音缩写回车调接口时会出现空格

### ISSUE THREAD

**Issue by xuechao215** [ant-design/ant-design#34844]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qboklk?file=/index.js)

### Steps to reproduce

中文输入法下在输入框里输入tb，直接回车，搜索框里显示tb，
      但是控制台打印的是t b，是带空格的，导致搜索接口传入字段为t b，
      是带空格的，导致搜索接口传入字段为t b,搜索不到信息

### What is expected?

控制台及接口字段不带空格，像搜索框里一样不到空格

### What is actually happening?

搜索框里不带空格，但是控制台打印及接口字段带空格

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
不是 antd 的问题，`onSearch` 通过 `keydown` 触发，这时候输入还是带空格的。

**Comment by afc163** [comment]
t'b

**Comment by afc163** [comment]
在 GitHub 输入框里试试，也是一样的效果。

**Comment by xuechao215** [comment]
tb

**Comment by xuechao215** [comment]
但是github输入后搜索框里显示的是t b,并不是tb啊，antd组件里显示的是tb啊，明明有空格的，但是展示的时候却不展示空格

**Comment by xuechao215** [comment]
> 在 GitHub 输入框里试试，也是一样的效果。
但是github输入后搜索框里显示的是t b,并不是tb啊，antd组件里显示的是tb啊，明明有空格的，但是展示的时候却不展示空格

**Comment by MadCcc** [comment]
输入法和 input 的事件冲突

**Comment by xuechao215** [comment]
之前的antd的4.8.5的版本就不会啊，输入中文缩写的时候回车只会把缩写填入搜索框里，并不会发起请求，现在升级到最新版本就出现这个问题了，输入中文缩写的时候回车会直接调用onSearch方法，这个时候查询字段为t b（中间有空格），但是搜索框里显示的却是tb（中间无空格），再次点击回车的时候查询字段就为tb（不带空格了）

**Comment by MadCcc** [comment]
4.18.9 看起来没问题，还是需要兼容一下

**Comment by xuechao215** [comment]
至少用统一一下吧，回车的时候值中间到空格，那展示的时候是不是也要留着空格会更好一些。又不能直接用正则去掉所有空格，有的场景中间是带空格的（英文名字）

**Comment by xuechao215** [comment]
@afc163

**Comment by MadCcc** [comment]
> 至少用统一一下吧，回车的时候值中间到空格，那展示的时候是不是也要留着空格会更好一些。又不能直接用正则去掉所有空格，有的场景中间是带空格的（英文名字）

这是输入法的特性，这里应该只处理输入法回车不触发 onSearch

**Comment by xuechao215** [comment]
4.8.5的版本是不会直接调用的，现在4.19.2的版本是会直接调用的

**Comment by xuechao215** [comment]
@MadCcc 什么时候能处理一下？
