### ISSUE TITLE
2.0.1 Cascader defaultValue无效

### ISSUE THREAD

**Issue by liutwv** [ant-design/ant-design#3484]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: MacOS Seirra
- 浏览器及其版本: Chrome 54.0.2840.59 (64-bit), Firefox 49.0.1

#### 您做了什么？
按官网Cascader的省市区例子，引入 antd 的Cascader, 在本地写了个例子，传了默认值defaultValue如下:
<Cascader defaultValue={['zhejiang', 'hangzhou', 'xihu']} options={options} onChange={onChange} />
options也是完全拷贝官网例子。

#### 您期待的结果是：
像官网一样正常显示默认值 Zhejiang / Hangzhou / West Lake

#### 实际上的结果是：
Cascader没有显示默认值

#### 可重现的在线演示
我是在https://github.com/zuiidea/antd-admin的例子上自己本地添加了Cascader模块来调试的。原项目没有用到Cascader

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/3470
