### ISSUE TITLE
Select 组件 点击 自定义Dropdown内容时不触发onBlur事件

### ISSUE THREAD

**Issue by zsedcbm** [ant-design/ant-design#34840]
### What problem does this feature solve?

自定义Dropdown内容时，我想实现某些操作不会关闭dropdown，某些操作会关闭dropdown，select组件的open属性由自己控制，点击组件外的内容时，希望能够触发blur事件。
拿官方示例扩展菜单示例来看，点击自定义文本框的时候，会触发onblur，但是select组件 ant-select-focused 属性实际上还存在。

### What does the proposed API look like?

修改onBlur触发时机，或者新增一个事件

**Comment by zsedcbm** [comment]
https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-19-4-forked-rbyppi

**Comment by afc163** [comment]
触发 onblur 是用于什么样的需求？

**Comment by zsedcbm** [comment]
类似于 treeSelect 组件，我想把里面的内容换成table，换成table之后点击行进行选择。有单选和多选的情况，单选的时候选择一行后直接关闭dropdown。当多选的时候，需要点击组件外部关闭dropdown。

**Comment by afc163** [comment]
不建议用 dropdownRender 封装如此复杂的行为，dropdownRender 设计的时候是给选择项上下添加一些附属信息的，这已经不是默认组件的行为了，我建议自行用 rc-trigger 来做一个业务组件。

**Comment by Sweet-ddd** [comment]
我找到解决方案了，可以在select绑定一个ref，需要关闭下拉框时执行ref.currennt.blur()
不采用open去动态关闭dropdown
