### ISSUE TITLE
antd/lib/input/Input.d.ts:16:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

### ISSUE THREAD

**Issue by lidongze0629** [ant-design/ant-design#34848]
### Reproduction link

[https://github.com/lidongze0629/graphscope_jupyterlab/tree/dev](https://github.com/lidongze0629/graphscope_jupyterlab/tree/dev)

### Steps to reproduce

```shell
cd graphscope_jupyterlab
pip3 install -e .
jupyter labextension develop . --overwrite
# Rebuild extension Typescript source after making changes
jlpm run build
```

### What is expected?

编译通过

### What is actually happening?

编译失败: node_modules/antd/lib/input/Input.d.ts:16:6 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

![截屏2022-04-02 下午7 50 54](https://user-images.githubusercontent.com/23491543/161381861-0d23ede3-581c-4e11-aa64-dfba2c5addd2.png)

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | react@17.0.2  react-native@0.68.0 typescript@4.3.4 |
| System | MacOS BigSur 11.6.2 |
| Browser | chrome |

---
这个应该和 typescript 的版本有关系，我升级到最新的版本是可以的，但是犹豫限制，需要在 typescript < 4.4.0 下使用

**Comment by MadCcc** [comment]
最好是能升级一下 ts 版本，antd 本身就基于 4.x 写的，ts 向下兼容很难。
