### ISSUE TITLE
Form `ant-form-item-explain` 始终存在

### ISSUE THREAD

**Issue by mrxiaozhuox** [ant-design/ant-design#34859]
### Reproduction link

[https://codesandbox.io/s/condescending-beaver-tqtll4](
https://codesandbox.io/s/condescending-beaver-tqtll4)

### Steps to reproduce

在 HTML 中始终会出现一个 `div class="ant-form-item-explain ant-show-help-leave ant-show-help ant-form-item-explain-connected"` 这会导致间距更大（我发现官方 Demo 中没有这个问题）

```jsx
export default function Home() {
	const CommentEditor = ({ onChange, onSubmit, submitting, value }) => (
		<>
			<Form.Item>
				<TextArea
					rows={6}
					onChange={onChange}
					placeholder="尝试着记录点什么吧！"
					value={value}
				/>
			</Form.Item>
			<Form.Item>
				<Button
					htmlType="submit"
					onClick={onSubmit}
					loading={submitting}
					type="primary"
				>
					Send
				</Button>
			</Form.Item>
		</>
	);
```

### What is expected?

正常情况下，不会显示这个DIV

### What is actually happening?

多出一个DIV且正常的FORM间距没缩小。

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Windows |
| Browser | Google Chrome |

---
经过我的测试，在没有任何自定义CSS以及布局代码的情况下，问题依然存在。
我的版本信息：
```
    "antd": "^4.19.5",
    "next": "12.1.4",
    "react": "18.0.0",
    "react-dom": "18.0.0"
```

**Comment by mrxiaozhuox** [comment]
https://codesandbox.io/s/condescending-beaver-tqtll4

**Comment by mrxiaozhuox** [comment]
版本切换到 React 17 问题解决，可能是版本兼容的问题（顺带一提按钮也一直是 loading 状态）

**Comment by doveq** [comment]
+1， 也是用的 react 18.

**Comment by zombieJ** [comment]
Resolved by https://github.com/react-component/motion/pull/24
