### ISSUE TITLE
在React18 createRoot模式下 ，DatePicker focus时页面卡死

### ISSUE THREAD

**Issue by bighansen** [ant-design/ant-design#34856]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jvsgg5?file=/index.js)

### Steps to reproduce

1、使用ReactDOMClient.createRoot
2、创建DatePicker
3、点击DatePicker

### What is expected?

正常使用

### What is actually happening?

页面卡死

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0 |
| System | MacOS/Win10 |
| Browser | Chrome |

---
换成ReactDOM.render模式就没有问题

**Comment by 98kWarning** [comment]
menu和dropdown也有这个问题

**Comment by zombieJ** [comment]
resolve by:
* https://github.com/react-component/trigger/pull/291
* https://github.com/react-component/util/pull/288
* https://github.com/react-component/util/pull/291
