### ISSUE TITLE
Dropdown Overlay Menu 不显示

### ISSUE THREAD

**Issue by jacinyan** [ant-design/ant-design#34868]
### Steps to reproduce

正常步骤

### What is expected?

显示

### What is actually happening?

不显示

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Mac OS |
| Browser | Chrome 100 |

---
react 17正常显示

**Comment by riyadelberkawy** [comment]
The same issue happens to me but with **<Menu.SubMenu/>** 
I noticed that it only occurs when I add **StrictMode** to the app tree

**Comment by zombieJ** [comment]
resolve by:
* https://github.com/react-component/trigger/pull/291
* https://github.com/react-component/util/pull/288
* https://github.com/react-component/util/pull/291
