### ISSUE TITLE
缺少拖拽控件是否可以添加拖拽控件

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3486]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:windows 10
- 浏览器及其版本:chrome

是否可以添加拖拽组件。

**Comment by afc163** [comment]
可以使用社区成熟的拖拽组件：https://www.google.co.jp/search?newwindow=1&site=&source=hp&q=react+drag&oq=react+drag&gs_l=hp.3..0l10.1162.2663.0.2880.10.8.0.0.0.0.518.518.5-1.1.0....0...1c..64.hp..9.1.517.FF_kEERl1no&bav=on.2,or.&bvm=bv.135974163,d.cGc&biw=1436&bih=814&dpr=2&ech=1&psi=pygHWObONImEjwPZs7z4Bg.1476864169023.3&ei=pygHWObONImEjwPZs7z4Bg&emsg=NCSR&noj=1
