### ISSUE TITLE
Table 组件td字体颜色与官方sketch组件包中不符

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design#34864]
### Reproduction link

[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce

打开网页检查td样式即可

### What is expected?

https://ant.design/docs/resources-cn 提供的的组件包中 table>td的字体颜色为rgba(0, 0, 0, 0.65)

### What is actually happening?

字体颜色为默认的rgba(0, 0, 0, 0.85)

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17 |
| System | mac os |
| Browser | 99 |

**Comment by afc163** [comment]
官网 sketch 年久失修了，建议直接用 kitchen 中提供的组件。
