### ISSUE TITLE
antd table组件筛选功能，onChange 中filters丢失问题

### ISSUE THREAD

**Issue by shaoyh** [ant-design/ant-design#34877]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-shai-xuan-cai-dan-antd-4-19-5-forked-lkibgd?file=/index.js)

### Steps to reproduce

1、打开demo链接 https://codesandbox.io/s/zi-ding-yi-shai-xuan-cai-dan-antd-4-19-5-forked-lkibgd?file=/index.js
2、打开console
3、操作表格，搜索Address，输入1，可以看到console内打印出来的address 是 ['1'],  
4、然后继续操作表格，点击Address排序按钮，console打印出来的address为null， 预期是['1']

### What is expected?

{
    "name": null,
    "age": [],
    "address": [
        "1"
    ]
}

### What is actually happening?

{
    "name": null,
    "age": [],
    "address": null
}

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | mac |
| Browser | chrome |

---
场景：表格多条件过滤；
备注：如果把下面的的
filters: [],
filteredValue: []
去掉，就不会出现这个bug；

{
        title: "Age",
        dataIndex: "age",
        key: "age",
        width: "20%",
        filters: [],
        filteredValue: []
      },

**Comment by nieyuyao** [comment]
这个问题好像和这个改动有关 https://github.com/ant-design/ant-design/pull/30882/files#diff-b99a8e21b430359d7018248c40fcff54596fce122c3099e08d4bb404c3a0276fR211
由于Age列里面定义了filteredValue
```js
{
        title: "Age",
        dataIndex: "age",
        key: "age",
        width: "20%",
        filters: [],
        filteredValue: []
 },
```
导致如下判断生效
```js
if (filteredKeysIsNotControlled) {
      return filterStates;
 }
```

**Comment by afc163** [comment]
<img width="688" alt="图片" src="https://user-images.githubusercontent.com/507615/164161994-6681f786-a5a7-4330-8563-cf9cb9c2ef56.png">

Columns should all contain `filteredValue` or not contain`filteredValue`.

这是符合预期的，我们目前的 API 设计（不是非常合理）需要 filteredValue 必须每一列都指定，这样才是完整的受控模式。
