### ISSUE TITLE
表格是否可以支持列宽度拖拽以及是否支持表格自定义列展示，用来控制表头展示数量？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design#34875]
### What problem does this feature solve?

该方案在表头列数较多时，支持用户自行拖拽表格列宽度以及控制展示哪些列。

### What does the proposed API look like?

1、提供是否支持自定义列宽拖拽的api
2、提供列展示个数控制，甚至该字段可以用来与后端交互

**Comment by afc163** [comment]
> 列宽度拖拽
暂不支持。

> 控制展示哪些列。
可以使用 https://procomponents.ant.design/components/table/
