### ISSUE TITLE
Modal opening is deferred on React 18 (createRoot) in StrictMode 

### ISSUE THREAD

**Issue by kel666** [ant-design/ant-design#34878]
### Reproduction link

[https://stackblitz.com/edit/react-ts-khumrf](https://stackblitz.com/edit/react-ts-khumrf)

### Steps to reproduce

Hit "Click me" under "with createRoot".

### What is expected?

Modal should open.

### What is actually happening?

Modal is not opened. If you click again, modal is opened.

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Chrome 94 |

---
As you can see this works using old React render

**Comment by JackJCSN** [comment]
And once it show up you cant close it.
I'm facing same problem with Next JS 12, witch dependent on React 18

**Comment by kel666** [comment]
Any solution plan for this? tnx
