### ISSUE TITLE
Image 显示 count / total 浏览进度的标题，支持键盘左右查看上一张和下一张

### ISSUE THREAD

**Issue by mushan0x0** [ant-design/ant-design#34874]
### What problem does this feature solve?

方便查看图片

### What does the proposed API look like?

Image 显示 count / total 浏览进度的标题，支持键盘左右查看上一张和下一张

**Comment by mushan0x0** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/29084441/161906779-3a853c2f-2e01-448e-8caf-205835f65418.png">

**Comment by zpc7** [comment]
HI, @mushan0x0 , antd-design的Image组件, 背后也是使用了library `rc-image`, 当前版本[rc-image@5.4.0](https://www.npmjs.com/package/rc-image)中已经添加了对方向左右键切换图片的支持, 等待ant-design版本更新后, 应该就能直接使用此特性了.

对于顶部 count/total 的新feature, 未在上文所述的版本中.
