### ISSUE TITLE
Icon close图标不显示

### ISSUE THREAD

**Issue by PebblerWon** [ant-design/ant-design#3488]
#### 发生问题的环境是：

- antd 版本: v1.6.3
- 操作系统及其版本: windows 7 64bit
- 浏览器及其版本: Chrome 版本 54.0.2837.0

#### 您做了什么？

引入 antd 的 Icon;
ReactDOM.render(<Icon type="close"></Icon>,document.getElementById("test"));

#### 您期待的结果是：

像官网一样正常显示

#### 实际上的结果是：

close图标不显示，type换成edit，edit图标可以正常显示

**Comment by afc163** [comment]
请参考 1.x 的文档：http://1x.ant.design/components/icon/

页面右下角有版本切换按钮。
