### ISSUE TITLE
Select Options detach from Select on scroll

### ISSUE THREAD

**Issue by adilosa** [ant-design/ant-design#34892]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qyld1e?file=%2Findex.js)

### Steps to reproduce

Place a Select inside of an Affix. Click on the Select to show the Select Options. On scroll, the list of options detaches from the Select and scrolls with the whole page. 

### What is expected?

The Options list should stay attached to the Select

### What is actually happening?

the Options list detaches from the Select and scrolls with the page

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.1.0 |
| System | macOS |
| Browser | Firefox |

---
I believe this bug can happen in other circumstances as well, but using Affix is how I found it and is the way I can reproduce. 

Other instances of this bug:
ant-design/ant-design#34152
ant-design/ant-design#28985

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#How-do-I-prevent-Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-scrolling-with-the-page
