### ISSUE TITLE
Tooltip with React 18 and *without* StrictMode cause browser crash/freeze

### ISSUE THREAD

**Issue by kel666** [ant-design/ant-design#34890]
### Reproduction link

[https://stackblitz.com/edit/react-ts-9ektit?file=index.tsx](https://stackblitz.com/edit/react-ts-9ektit?file=index.tsx)

### Steps to reproduce

Go over the button of "createRoot".

### What is expected?

Tooltip appears

### What is actually happening?

Browser freeze than page crashes

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Chrome 94 |

---
If you go over button "without createRoot" (that is, using render) the  popup appears

**Comment by ludwighen** [comment]
same happens for Popover component

**Comment by zombieJ** [comment]
resolve by:
* https://github.com/react-component/trigger/pull/291
* https://github.com/react-component/util/pull/288
* https://github.com/react-component/util/pull/291

**Comment by deepakbhattmits** [comment]
Hi  @kel666 , Did your issue resolved ?

**Comment by kel666** [comment]
> Hi @kel666 , Did your issue resolved ?

I'm waiting for a beta release or other in npm in order to try

**Comment by binczech** [comment]
I can confirm that problems still persist on 4.20.0 when createRoot is used. I replaced it with render and it works now. So we still need support for createRoot.

**Comment by kel666** [comment]
Works with 4.20.0-alpha.1

**Comment by naivefun** [comment]
> Works with 4.20.0-alpha.1

With this version it doesn't freeze but the popover doesn't show either.

**Comment by naivefun** [comment]
> I can confirm that problems still persist on 4.20.0 when createRoot is used. I replaced it with render and it works now. So we still need support for createRoot.

Can you demo how to bypass createRoot in React 18?

**Comment by naivefun** [comment]
> I can confirm that problems still persist on 4.20.0 when createRoot is used. I replaced it with render and it works now. So we still need support for createRoot.

What is the difference between ReactDOM.render & createRoot?

**Comment by blaskodaniel** [comment]
The popover doesn't work with 4.20.4 version. (I use NextJs 12.1.6 with React 18.1.0)

**Comment by silakchhum** [comment]
> 

I'm also face like your problem and wait they release new version

**Comment by nodeworks** [comment]
This was marked as closed but this is still happening with ^4.20.7. I'm using React 18.1.0 and NextJS 12.1.6.

**Comment by alanwu4321** [comment]
Same thing with NextJS

**Comment by fdemian** [comment]
Hello. I'm experiencing the same problem with  `antd@4.21.4` and `react@18.2.0`.

**Comment by jourdanrodrigues** [comment]
Still same with 4.22.2 React 18.2.0

**Comment by antollika** [comment]
Hello
The most interesting thing is that I have M1 max and I do not have any issues. But my teammate with core i7 has it (macOs and windows) :)

**Comment by zombieJ** [comment]
> Hello The most interesting thing is that I have M1 max and I do not have any issues. But my teammate with core i7 has it (macOs and windows) :)

Strange. Is there any clues about this?

**Comment by antollika** [comment]
@zombieJ 
I can tell you a more interesting thing
We fixed the issue with browser freezing by wrapping RcTooltip with React.StrictMode
like this

`
...
<React.StrictMode>
      <RcTooltip
...
`

And it works fine for MacBook and PC with intel CPU
But - after this change - I stopped seeing a tooltip on my MacBook with M1 Max - another thing - my browser does not crash in any cases (with StrictMode and without it).

Another thing
This problem is on the dev build only. With production build, everything is fine on any PC or MacBook

**Comment by antollika** [comment]
@fdemian 
try to install
"rc-trigger": "^5.3.1",
if and-design tooltip is written based on rc-tooltip
it should help

**Comment by yoni-salt** [comment]
Have the same issue, ive installed "rc-trigger" its better but not stable, if i have several elements that has a tooltip and I run with the mouse between them to test it, it will crash the browser(latest chrome)

**Comment by amit-chaudhary4** [comment]
Same issue. Browser crashes when I move my cursor over popup.

**Comment by mMarcos208** [comment]
same issue after upgrade to React 18

antd 5.4.5

**Comment by oostashov** [comment]
> 

Same for me. However, slowing down performance helps to freeze the tab ;)

**Comment by oostashov** [comment]
Resolutions in `package.json` helped me:
```json
"resolutions": {
  "rc-tooltip": "5.3.1",
  "rc-picker": "2.6.9",
  "rc-trigger": "5.3.4"
}
```

Big thanks to @pkocherov-xometry

**Comment by aminhdev** [comment]
> Resolutions in `package.json` helped me:
> 
> ```json
> "resolutions": {
>   "rc-tooltip": "5.3.1",
>   "rc-picker": "2.6.9",
>   "rc-trigger": "5.3.4"
> }
> ```
> 
> Big thanks to @pkocherov-xometry

Thanks, This solves my problem
