### ISSUE TITLE
Form.Item labelCol与wrapperCol同为span 24 时样式错误

### ISSUE THREAD

**Issue by shusiwei** [ant-design/ant-design#34903]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-19-5-forked-gr8hrn?file=/index.js:397-405)

### Steps to reproduce

缩小浏览器宽度，触发sm md 响应式时，wrapperCol宽度为0，在v4.18.7以前wrapperCol另起一行

### What is expected?

样式正常

### What is actually happening?

样式错乱

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | windows |
| Browser | Chrome 99 |

![image](https://user-images.githubusercontent.com/6745335/162156429-bf0e4c72-c5f2-4b80-ba45-c04ac8500fe7.png)
v4.18.9+结果

![image](https://user-images.githubusercontent.com/6745335/162157222-3c50f7c9-6e4b-4bd1-b4e2-947f67049f15.png)
v4.18.7-结果

**Comment by afc163** [comment]
怎么又出现了。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/34117
https://github.com/ant-design/ant-design/issues/32980

**Comment by afc163** [comment]
我知道了，https://github.com/ant-design/ant-design/pull/34117/files#diff-76eea2956e65a679af86a906fcc3cd0046a33214a23aed25c6c1a01e84991c5aR17 没考虑到 ant-col-sm-24 ant-col-md-24 的场景。
