### ISSUE TITLE
Menu导航菜单， 默认开启defaultOpenKeys时

### ISSUE THREAD

**Issue by ntscshen** [ant-design/ant-design#34905]
### Reproduction link

预览地址：[https://react-wds88o.stackblitz.io/ ](https://react-wds88o.stackblitz.io/ )
编辑地址：[https://stackblitz.com/edit/react-wds88o?file=index.js ](https://stackblitz.com/edit/react-wds88o?file=index.js )

### screenshot
一图胜千言
![image](https://user-images.githubusercontent.com/21041458/162170364-13917718-d739-4ae9-8226-8be3a7ae97c4.png)

### Steps to reproduce

请打开预览地址，鼠标从最上层移入第一条内容
1. Three为默认展开内容

### What is expected?

当鼠标滑入非默认展开的内容上时，关闭默认展开的内容

### What is actually happening?

当鼠标滑入非默认展开的内容上时，是否应该关闭默认展开的内容。
在 onOpenChange中，得到的keys是混乱的

其他：SubMenu中的title字段是否应该改成其他的参数，当前title覆盖了原生title信息提示
( 假设一个需求：二级子菜单宽度被css变量固定后，需要title提示全量内容，此时无法覆盖~  )

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | macOS |
| Browser | 版本 100.0.4896.60（正式版本） (x86_64) |

**Comment by afc163** [comment]
目前是在 Menu Item 的 onMouseLeave 事件上关闭的子菜单，如果从上到下移入鼠标，不会触发 Three 的鼠标移出，所以不会隐藏默认展开的菜单。

**Comment by ntscshen** [comment]
thinks，感谢及时回复。
对初始时展示子菜单的用户来说，这个可能是个明显的bug，有什么好的解决方式吗
（ 我想到的是复写openKeys或者根据当前场景重新渲染组件，我觉得这些都不是一个理想的解决方式 ）

**Comment by MadCcc** [comment]
直接用 `openKeys` 受控如何？

**Comment by ntscshen** [comment]
Thanks，感谢建议，使用 `openKeys` 受控的方案。
如果可行的话，期待在这个边界问题在组件层面被解决。

-------

_tip: 在垂直和水平状态下的"子菜单默认展开"在我们的组件中这个功能已经被放弃，
初始化页面时，焦点被聚集在“悬浮”的菜单上，将用户焦点聚集在一个极轻量的多层嵌套悬浮的操作上。体验和产品上不合理_

**Comment by afc163** [comment]
建议直接用 openKeys 受控模式解决。
