### ISSUE TITLE
onDoubleClick event is called when rapidly select and unselect the checkbox in Ant Table

### ISSUE THREAD

**Issue by wanderowski** [ant-design/ant-design#34911]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mj9ot3?file=/index.js)

### Steps to reproduce

Rapidly select and unselect the checbox in the above reproduction. This fast select-unselect action calls an onDoubleClick callback. I found out that, this was fixed for 'onClick' callback in'onRow' prop, however, for 'onDoubleClick' it still appears. e.stopPropagation() has no meaning and doesn't work 

### What is expected?

Fast select-unselect action does not call onDoubleClick callback of onRow property inside the table

### What is actually happening?

Fast select-unselect action calls onDoubleClick callback of onRow property inside the table 

| Environment | Info |
| --- | --- |
| antd | 4.10.2 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/antd-reproduction-template-forked-gg63i4?file=/index.js
