### ISSUE TITLE
New component - Divider

### ISSUE THREAD

**Issue by MichaelSavin** [ant-design/ant-design#3492]
[Example](https://styleguide.cfapps.io/react_base_dividers.html)

**Comment by plandem** [comment]
why don't use common <hr>?

**Comment by MichaelSavin** [comment]
Because it could be coupled with text, icons.

**Comment by MichaelSavin** [comment]
This means everything must be done consistently with the basic framework design

**Comment by kvetoslavnovak** [comment]
Ant Design is based on 
- these design and styling principles https://ant.design/docs/spec/introduce and 
- rc-react components http://react-component.github.io/badgeboard/

It is not wise to blindly follow or cherry pick other third parties frameworks like Pivotal UI. But feel free to propose code as a PR or use Pivotal UI in your project in combination with ant-design.

**Comment by MichaelSavin** [comment]
Ok, look: https://ant.design/docs/spec/stay#Inlays
As you can see Ant.design uses the concept of horizontal dividers. But there is no guidelines, nor any components. I offer to fix and standardize the use of horizontal dividers and labels.

**Comment by kvetoslavnovak** [comment]
I agree this is a design element. 
But as a component I think it is a customized component , not so appropriate to put into antd.

**Comment by benjycui** [comment]
Relative: https://github.com/ant-design/ant-design/issues/3494
