### ISSUE TITLE
当InputNumber设置了min后，输入值为空时没有自动设置为最小值

### ISSUE THREAD

**Issue by jin-benben** [ant-design/ant-design#34921]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2fyww9)

### Steps to reproduce

清空输入

### What is expected?

当设置了min后当输入值为空时，自动设置InputNumber为最小值

### What is actually happening?

输入为空时没有自动设置

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | window |
| Browser | chrome 100.0.4896.75 |

**Comment by afc163** [comment]
默认行为不应该这样，有需要留空的场景。

**Comment by jin-benben** [comment]
> 默认行为不应该这样，有需要留空的场景。

比如购物车，购买商品数量至少为1，
