### ISSUE TITLE
ant组件,社区如何帮助一起升级到react.18？

### ISSUE THREAD

**Issue by spikeZwh** [ant-design/ant-design#34926]
### Reproduction link

[https://github.com/orgs/ant-design/projects/3](https://github.com/orgs/ant-design/projects/3)

### Steps to reproduce

none

### What is expected?

package.json 
peerDependencies
react >= "18.0.0"

### What is actually happening?

react >= "16.9.0"

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | macOS Big Sur 11.2.1 |
| Browser | chrome |

---
请问现在ant主要是在为react18产生的问题做兼容？
我看依赖基本上还是react >= 16.9.0。
为什么不是升级到18,然后做个18分支的修改？可能也是我没有找到这个依赖react18的分支吗？
这点我感到很疑惑。
我看到了Project里面有关于18版本的一些问题，但是我尝试去解决的时候，发现ant/react-component的依赖是react16.9,这让我很不解。
请问有相关的ant.v5的分支可以了解的吗

**Comment by zombieJ** [comment]
React 18 和 v4 并不冲突，兼容性也会在 v4 上做。参与发 PR 即可，参考：https://github.com/ant-design/ant-design/issues/34805#issuecomment-1092370052

**Comment by spikeZwh** [comment]
> 
谢谢。
我还有个问题: 
例如我要在ant4的情况,我想使用react18提供的一些新api或者一些新的方法去改进ant组件或者react-component.
这时候，我应该怎么办？
还是等ant5版本发出后,才会有具体这方面的考虑。
现在还是以兼容为主的改进吗？

**Comment by spikeZwh** [comment]
> React 18 和 v4 并不冲突，兼容性也会在 v4 上做。参与发 PR 即可，参考：[#34805 (comment)](https://github.com/ant-design/ant-design/issues/34805#issuecomment-1092370052)

@zombieJ 

谢谢。
我还有个问题:
例如我要在ant4的情况,我想使用react18提供的一些新api或者一些新的方法去改进ant组件或者react-component.
这时候，我应该怎么办？
还是等ant5版本发出后,才会有具体这方面的考虑。
现在还是以兼容为主的改进吗？

**Comment by zombieJ** [comment]
参考 https://github.com/ant-design/ant-design/blob/master/components/_util/compatible.ts ，兼容为主。不能 break 掉旧版本用户。v5 也会尽可能考虑兼容性。
