### ISSUE TITLE
upload video(视频) 能否获取视频第一帧图片

### ISSUE THREAD

**Issue by caizhehao** [ant-design/ant-design#34939]
### What problem does this feature solve?

upload video(视频) 获取视频第一帧图片为缩略图，或者如何获取视频第一帧图片
![image](https://user-images.githubusercontent.com/26589188/162416793-a0025e30-1e23-4732-8e7b-3d69858e78e6.png)

### What does the proposed API look like?

upload video(视频) 获取视频第一帧图片为缩略图，或者如何获取视频第一帧图片

**Comment by caizhehao** [comment]
> 

那个问题也是我提交的，因为问题提交格式不争取，就被关了

**Comment by afc163** [comment]
这个不是 antd 组件负责的范畴。
