### ISSUE TITLE
Multiple Select & TreeSelect onBlur doesn't fire when removing a node

### ISSUE THREAD

**Issue by kahummer** [ant-design/ant-design#34934]
### Reproduction link

[https://stackblitz.com/edit/react-ol4pmc?file=index.js](https://stackblitz.com/edit/react-ol4pmc?file=index.js)

### Steps to reproduce

For multiple select
- remove node via "X" icon
- Click outside the select
- Doesn't fire onBlur

### What is expected?

Should fire onBlur when removing a node via "X" icon

### What is actually happening?

Not firing onBlur when removing a node via "X" icon

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | react 16.12,0 |
| System | linux |
| Browser | chrome |

---
The onclear solution pointed here https://github.com/ant-design/ant-design/issues/21498#issuecomment-589950484. Is called when the clear all icon is selected and not on the individual nodes so this holds no solution for this problem

**Comment by afc163** [comment]
There is no focus behavior when click `x` to remove node, so no `onBlur` would be triggered, it is intented.
