### ISSUE TITLE
Modal 和 Popconfirm（可能是我的问题） 存在异常

### ISSUE THREAD

**Issue by ZZZCNY** [ant-design/ant-design#34936]
### Reproduction link

[https://github.com/ZZZCNY/Issue.git](https://github.com/ZZZCNY/Issue.git)

### Steps to reproduce

Modal 异常：点击新增按钮弹出 Modal，第一次打开关闭动画正常，之后动画异常。

Popconfirm 异常（可能是我的问题）：点击批量删除按钮，大概率卡死，无论按钮是否可用，也有概率 Popconfirm 异常弹出。

### What is expected?

Modal 动画始终如第一次打开的样子。

Button 禁用时，Popconfirm 不弹出，Button 启用时 Popconfirm 可以弹出，并且不卡死。（可能是我的问题）

### What is actually happening?

Modal 异常：点击新增按钮弹出 Modal，第一次打开关闭动画正常，之后动画异常。

Popconfirm 异常：点击批量删除按钮，大概率卡死，无论按钮是否可用，也有概率 Popconfirm 异常弹出。（可能是我的问题）

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Windows 11 专业版 21H2 |
| Browser | Microsoft Edge 版本 100.0.1185.36 (正式版本) (64 位) |

---
关于 Popconfirm，我尝试过只禁用 Button，在 Popconfirm 中没有设置 disabled，Popconfirm 会卡死；同时设置（我目前提供的代码），Popconfirm 也会卡死；我控制 Popconfirm 的显示与隐藏，接管 Button 的 onClick、Popconfirm 的 onConfirm 和 onCancel，Popconfirm 还是会卡死。在删除 App.tsx 中的路由有关的代码后，才恢复正常，所以不知道是我的问题还是 antd 的问题。

**Comment by ZZZCNY** [comment]
好吧，和路由无关，还是会卡死。

**Comment by afc163** [comment]
Duplicate of #34878
Duplicate of #34810

**Comment by ChineseBread** [comment]
前几天换18版本的时候也遇到这个问题了，zombiej在react社区问过，他们的绝对定位用了ReactDOM.render()创建元素，所以用到的地方会卡死而且会给18版本的warning
