### ISSUE TITLE
New component - Ribbon

### ISSUE THREAD

**Issue by MichaelSavin** [ant-design/ant-design#3494]
[Example](https://styleguide.cfapps.io/react_base_ribbons.html)

**Comment by plandem** [comment]
sorry, i can't understand what exactly do you mean?

**Comment by MichaelSavin** [comment]
This means that it would be good to have special visual markers (dividers), such as ribbons, banners & horizontal dividers

**Comment by kvetoslavnovak** [comment]
Ant Design is based on 
- these design and styling principles https://ant.design/docs/spec/introduce and 
- rc-react components http://react-component.github.io/badgeboard/

It is not wise to blindly follow or cherry pick other third parties frameworks like Pivotal UI. But feel free to propose code as a PR or use Pivotal UI in your project in combination with ant-design.

**Comment by MichaelSavin** [comment]
I'm trying to find of a good pattern for e-textbooks. I need the mark, which allows visually highlight a block of text with call to action such as "Read", "Calculate", etc. But it's not Alert nor Tag.

**Comment by plandem** [comment]
Maybe it's time to create own component for your special case?! :)

**Comment by MichaelSavin** [comment]
@plandem Yes, of course. We will do it in the next two weeks. But I think it might be useful to someone else :-)

**Comment by afc163** [comment]
I think it is a customized component too, not so appropriate to put into antd.

**Comment by MichaelSavin** [comment]
Ok!
