### ISSUE TITLE
兼容 @types/react@18 类型声明

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#34940]
### What problem does this feature solve?

@types/react@18 包含一些类型上的 breaking，其中 React.FC 受影响，antd 就依赖了这个类型，在 @types/react@17 已经有一些兼容的办法，创建这个 issue 以兼容 @types/react@17&18

see: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

### What does the proposed API look like?

修改 React.FC<Props> 增加 children: React.ReactNode

**Comment by dancerphil** [comment]
Work in progress.

**Comment by 0x219** [comment]
mark

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/34937
