### ISSUE TITLE
Bug: reopen Issues again because previous issue was not resolved Issue number : #34850

### ISSUE THREAD

**Issue by deepakbhattmits** [ant-design/ant-design#34957]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-kalam-wmdi8g)

### Steps to reproduce

No any extra effort to do for that 

### What is expected?

Button should display without loading spinner 

### What is actually happening?

Button is displaying with loading spinner 

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Ubuntu 20.0.4 |
| Browser | Chrome |

---
Could you please see my older issue that is not yet fixed then why this closed issue number 34850

**Comment by tmkx** [comment]
What's the version of `rc-motion` in your lockfile?

**Comment by zombieJ** [comment]
Clean up your node_modules and reinstall. It's already fixed:

https://stackblitz.com/edit/react-ervsno?file=index.js

PS: codesandbox cache the `rc-motion` which not apply the patch.
