### ISSUE TITLE
ImputNumber的step设置为小数，表单验证的问题

### ISSUE THREAD

**Issue by LarryLee8** [ant-design/ant-design#3495]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: win10
- 浏览器及其版本: chrome 最新版本

#### 您做了什么？

```
<FormItem {...formItemLayout} label="money">
{
    getFieldDecorator('money', {rules: [{ required: true, type="float" }]})(
        <InputNumber step={0.0001} min={8.0001} max={12.9999} />
    )
}
</FormItem>
```

#### 您期待的结果是：

1.  当数字变为 一个 【整数】 时控件显示一个小数. 如：当前值为5，实际展示5.0000；
2.  当数字变为 一个 【整数】 时依旧能够验证通过；

#### 实际上的结果是：

当变为一个整数时，小数部分不见了，同时也不能通过表单验证。

#### 可重现的在线演示

http://codepen.io/lhzh527/pen/NRENaG?editors=1010

**Comment by afc163** [comment]
对，这是模仿原生 `input[type=number]` 的行为，`1.0` 会被展示为 `1`。不要使用校验规则 `type: 'float'`，建议自己写校验规则。

> 另外，由于 InputNumber 本身已经限制了输入，其实这里也没有校验的必要。
