### ISSUE TITLE
antd table columns 中隐藏列 （Vue）

### ISSUE THREAD

**Issue by codthing** [ant-design/ant-design#34951]
### What problem does this feature solve?

通过动态控制Json数据隐藏列。

### What does the proposed API look like?

```base
const data = [
	{title:"a"}, 
	{title:"b", hide:true}
]
<a-table :columns="data"/>

// 通过在json数据data中设置hide属性，隐藏列“b”
```

**Comment by yoyo837** [comment]
请反馈到这边 https://github.com/vueComponent/ant-design-vue
