### ISSUE TITLE
页面使用Image组件后导致window添加mousewheel事件无效

### ISSUE THREAD

**Issue by 947840309** [ant-design/ant-design#34966]
### Reproduction link

[https://stackblitz.com/edit/issues-image](https://stackblitz.com/edit/issues-image)

### Steps to reproduce

window.addEventListener('mousewheel', () => console.log(123));失效 去除image组件恢复

### What is expected?

滚动鼠标滚轮打印123

### What is actually happening?

无反应

| Environment | Info |
| --- | --- |
| antd | 4.18.9 |
| React | 17.0.2 |
| System | macOS Monterey 12.2.1 |
| Browser | chrome 100.0.4896.75 |

**Comment by afc163** [comment]
Try `wheel` instead of `mousewheel`.

**Comment by afc163** [comment]
![图片](https://user-images.githubusercontent.com/507615/162729574-708bb16c-b289-415d-87b9-b2f3186ab43f.png)

**Comment by 947840309** [comment]
> 尝试`wheel`代替`mousewheel`.

thanks
