### ISSUE TITLE
fork的ant,当前下载了新的依赖,出现babel-plugin-import@1.13.4,lib文件中出现chencheng?

### ISSUE THREAD

**Issue by spikeZwh** [ant-design/ant-design#34967]
### Reproduction link

[https://github.com/umijs/babel-plugin-import](https://github.com/umijs/babel-plugin-import)

### Steps to reproduce

你们的ant-design的node_modules删除,重新install。
babel-plugin-import@1.13.4这个版本的lib文件内,会有这个问题

### What is expected?

期望不出现

### What is actually happening?

出现了私人路径

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | macOS Big Sur 11.2.1 |
| Browser | chrome |

---
你们的ant-design的node_modules删除,重新install。
当前下载了新的依赖,出现babel-plugin-import@1.13.4,lib文件中出现chencheng

![image](https://user-images.githubusercontent.com/103087638/162689780-ac35395a-4c6c-487d-87cc-a7f91872496b.png)

**Comment by afc163** [comment]
Trace https://github.com/umijs/babel-plugin-import/issues/607
