### ISSUE TITLE
form为什么不允许设置 fieldNameProp ？

### ISSUE THREAD

**Issue by shy2850** [ant-design/ant-design#3497]
[https://github.com/ant-design/ant-design/blob/master/components/form/Form.tsx#L106](https://github.com/ant-design/ant-design/blob/master/components/form/Form.tsx#L106)
这个为什么不让修改？
```
const formWrapper = createDOMForm(assign({}, options, {
      fieldNameProp: 'id',
      fieldMetaProp: FIELD_META_PROP,
}));
```

**Comment by benjycui** [comment]
这样可以自动绑定 `label[for]`。

我不觉得有自定义的需要。

**Comment by shy2850** [comment]
显然不是这问题，form里面默认把所有字段设置了id，我一个页面类似的表单要出现很多个，一坨重复id总不好吧？
