### ISSUE TITLE
关闭AutoComplete完全匹配时的蓝色高亮

### ISSUE THREAD

**Issue by shixinxin1111** [ant-design/ant-design#34975]
### What problem does this feature solve?

解决了用户使用时的视觉歧义问题

### What does the proposed API look like?

提供一个选项，关闭时不高亮显示完全匹配的项

**Comment by afc163** [comment]
> 解决了用户使用时的视觉歧义问题

具体是啥歧义问题？

**Comment by shixinxin1111** [comment]
同时出现了蓝色高亮和灰色高亮，不知道当前选中的是哪个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月11日(周一) 晚上7:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design] 关闭AutoComplete完全匹配时的蓝色高亮 (Issue #34975)




  
解决了用户使用时的视觉歧义问题
  
具体是啥歧义问题？

**Comment by afc163** [comment]
确实。

**Comment by albert-cai** [comment]
可否有新的属性来决定是否需要关闭蓝色高亮，因为从视觉上，蓝色和灰色区分还是很明显的，关闭了以后，在cursor不在选中项上的时候，会找不到选中项是哪一个，另外，虽然明确区分了AutoComplete和Select的使用，但是由于Select无法选中选择项，导致在某需要复制选中的值的场景下，只能用AutoComplete来替代。 @afc163
