### ISSUE TITLE
React18版本中使用RangePicker导致页面崩溃问题

### ISSUE THREAD

**Issue by JianWang-Mc** [ant-design/ant-design#34973]
### Reproduction link

[https://stackblitz.com/edit/react-ts-65bsxm?file=index.tsx](https://stackblitz.com/edit/react-ts-65bsxm?file=index.tsx)

### Steps to reproduce

点击日期选择框后即可触发

### What is expected?

点击日期选择框正常出现弹框选择日期

### What is actually happening?

点击后页面崩溃无任何反应

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | MacOS  |
| Browser | 100.0.4896.75 |

**Comment by JokerAn** [comment]
DatePicker.RangePicker' cannot be used as a JSX component.
10:40:52   Its instance type 'Component<RangePickerProps<Moment>, unknown, any> & CommonPickerMethods' is not a valid JSX element.  TS2786
10:40:52 
10:40:52     46 |       </Form.Item>
10:40:52     47 |       <Form.Item label="������������" name="dates">
10:40:52   > 48 |         <DatePicker.RangePicker ranges={ranges} />
10:40:52        |          ^
10:40:52     49 |       </Form.Item>
10:40:52     50 |       <div className="searchBtnBox">
10:40:52     51 |         <div>

解决办法：
const RangePicker**: any** = DatePicker.RangePicker;//写上any会是正确的
//const {RangePicker}=DatePicker 这种是错误的

      <Form.Item label="聚合日期" name="dates">
        <RangePicker ranges={ranges} />
      </Form.Item>

**Comment by JianWang-Mc** [comment]
> DatePicker.RangePicker' cannot be used as a JSX component. 10:40:52 Its instance type 'Component<RangePickerProps, unknown, any> & CommonPickerMethods' is not a valid JSX element. TS2786 10:40:52 10:40:52 46 | </Form.Item> 10:40:52 47 | <Form.Item label="������������" name="dates"> 10:40:52 > 48 | <DatePicker.RangePicker ranges={ranges} /> 10:40:52 | ^ 10:40:52 49 | </Form.Item> 10:40:52 50 |
> 
> 
> 10:40:52 51 |
> 解决办法： const RangePicker: any= DatePicker.RangePicker;//写上any会是正确的 //const {RangePicker}=DatePicker 这种是错误的
> 
> ```
>   <Form.Item label="聚合日期" name="dates">
>     <RangePicker ranges={ranges} />
>   </Form.Item>
> ```

感谢，试了一下这个可以

**Comment by zombieJ** [comment]
resolve by:
* https://github.com/react-component/trigger/pull/291
* https://github.com/react-component/util/pull/288
* https://github.com/react-component/util/pull/291
