### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & XXXProps'.

### ISSUE THREAD

**Issue by East-Apollo** [ant-design/ant-design#34989]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce

antd Add child elements to component Tags

### What is expected?

normal operation

### What is actually happening?

Type '{ children: Element; XXX: any; }' is not assignable to type 'IntrinsicAttributes & XXXProps'.
[Admin]   Property 'children' does not exist on type 'IntrinsicAttributes & XXXProps'.

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18 |
| System | mac |
| Browser | google latest |

---
Upgrade webpack5 and add child elements in the antd tag. Error: property 'children' does not exist on type 'internalattributes & xxxprops' The type children is not defined

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/34937

**Comment by East-Apollo** [comment]
> [在#34937](https://github.com/ant-design/ant-design/pull/34937)中修复[](https://github.com/ant-design/ant-design/pull/34937)



> [在#34937](https://github.com/ant-design/ant-design/pull/34937)中修复[](https://github.com/ant-design/ant-design/pull/34937)

具体什么时间呢？4.20.0我看发布没有成功

**Comment by afc163** [comment]
等 React 18 相关问题修复就发

**Comment by minhson3012** [comment]
Since antd 4.20.0 is not official released, is there any way to fix this on 4.19.5 or do I have to downgrade react from 18 to 17?

**Comment by jdgabriel** [comment]
> Como o antd 4.20.0 não foi lançado oficialmente, existe alguma maneira de corrigir isso no 4.19.5 ou tenho que fazer o downgrade reagir de 18 para 17?

You can downgrade, which is the most recommended.
But an also viable solution, BUT IT'S A TEMPORARY SOLUTION, is to manually change the files that give error in node_modules.
Personally I made the changes manually, so I don't need to downgrade and then update. That's why I recommend you change files manually by adding `children?: React.ReactNode;` where necessary.

Remembering again... this is a temporary workaround until 4.20.X is released.

**Comment by spikeZwh** [comment]
当我想要暂时把这个类型报错给忽略的时候。

例如:
 `
import { Steps } from 'antd';
const TemprorySteps = Steps as any as xxxxtype;
`

这个时候babel-plugin-import 无法把as any正确做处理，会变成
`
const TemprorySteps = _Steps;
// _Steps is undefined
`

我看babel-plugin-import有个这方面的pr
[babel-plugin-import](https://github.com/umijs/babel-plugin-import/pull/588)

是否会考虑这方面的兼容。
毕竟确实会存在做as赋值类型的场景;

**Comment by spikeZwh** [comment]
> 等 React 18 相关问题修复就发

当我想要暂时把这个类型报错给忽略的时候。

例如:
`
import { Steps } from "antd"; 
import type { StepsProps } from "antd/es/steps";

const TemporarySteps = Steps as any as React.FC<StepsProps & {
        children: JSX.Element;
}>;
`

这个时候babel-plugin-import 无法把as any正确做处理，会变成
`
const TemprorySteps = _Steps; 
// _Steps is undefined
`
因为import没有引进了_Steps

我看babel-plugin-import有个这方面的pr
[babel-plugin-import](https://github.com/umijs/babel-plugin-import/pull/588)

是否会考虑这方面的兼容
确实会有覆盖类型做as的场景存在
