### ISSUE TITLE
Tooltip放置在Dropdown内部，点击下拉菜单内容后控制台会报错

### ISSUE THREAD

**Issue by alienzhangyw** [ant-design/ant-design#34982]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/chu-fa-shi-jian-antd-4-19-5-forked-jz7rtg)

### Steps to reproduce

点击下拉菜单项目

### What is expected?

不报错

### What is actually happening?

控制台报错：
TypeError
_triggerRef$current$t2.focus is not a function
eval
https://2tc6ge.csb.app/node_modules/rc-dropdown/es/hooks/useAccessibility.js:61:364

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | Windows 11 |
| Browser | Edge 99 |

---
以前不会，升级到最新版出现。将Tooltip移到Dropdown外部可解决报错。
另外Dropdown目前不支持focus之后使用键盘上下和enter选择代替鼠标点击，只能使用tab。

**Comment by MadCcc** [comment]
4.20.0 修复， 4.19.5 的 dropdown 还固定在 3.3 版本
