### ISSUE TITLE
Select 中，设置 optionLabelProp 而 labelInValue 为 false 时，如何设置初始值？

### ISSUE THREAD

**Issue by Amorites** [ant-design/ant-design#3498]
#### 发生问题的环境是：

- antd 版本:  2.1.0
- 操作系统及其版本:
- 浏览器及其版本:
#### 您做了什么？
1. 动态获取 option，给每个option 设置一个属性叫 label 用于选中后的显示
2. 设置 Select 的 optionLabelProp='label'
#### 您期待的结果是：
1. Select 的 value 是待提交数据的数组（而不是{key, label}，因为一个表单中的类型有相当多种 )，可以方便地收集
2. 可以给 Select 赋初始值，能正确地收集 value， 正常地显示 label
#### 实际上的结果是：
1. Select 的 value 是待提交数据的数组，可以方便地收集(OK)
2. 可以给 Select 赋初始值，能正确地收集 value(OK)， 正常地显示 label (不OK，在不设置labelInValue 时）

设置了 labelInValue 后，解决了初值问题，但收集 value 又比较麻烦。尝试过使用 getValueFromEvent 提取，但它似乎会直接修改 Select 里的 value，让 Select 无法正常工作。

**Comment by yesmeck** [comment]
能给个例子吗 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by yesmeck** [comment]
大概理解了一下你的问题，在 labelInValue 为 false 的时候 initialValue 设置为 `{ key: 'foo', label: 'bar' }`这样即可。

例子：http://codepen.io/yesmeck/pen/ameJjV?editors=001

**Comment by Amorites** [comment]
多谢，可是你的 demo 里 labelInValue 是 true 啊……

之前我的目的是让组件收集到的 value 是 key 或者是 Array<key> （而不是{key, label} 或者是 Array<{key, label}）但貌似很难实现，现在的做法是在 handleSubmit 时做统一处理了。

**Comment by yesmeck** [comment]
> 在 labelInValue 为 false 的时候

说错了。。是 labelInValue 为 true 的时候。
