### ISSUE TITLE
Inconsistent selection of time range behavior and results

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#34990]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-4-19-5-forked-hxudyo?file=/index.js)

### Steps to reproduce

Reference Video

### What is expected?

2022-04-12 19:00:00 - 2022-04-12 22:00:00

### What is actually happening?

2022-04-12 18:00:00 - 2022-04-12 22:00:00

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17 |
| System | macos12 |
| Browser | chrome 100 |

---
Actually, I'm not sure this counts as a bug, just a discrepancy between user interaction and actual results. Personally, I'm more inclined to think it's a problem with my use of the control. So I'm wondering if that's the case?

(The description was translated by me using google. If you can reply in Chinese then that would be great)

Thanks!

https://user-images.githubusercontent.com/32004925/162922258-0e3da998-903b-449b-9d3e-0a2fcb9c8348.mp4

**Comment by MadCcc** [comment]
终止时间一开始是 18:00，起始时间不能超过。
