### ISSUE TITLE
Table.DataSource 使用问题

### ISSUE THREAD

**Issue by netskyline** [ant-design/ant-design#350]
项目中用到 Table 组件，并按官网文档中的方法配置数据源，用到 Table.DataSource，请问如何在我的render() 中获取这个 DataSource 中的请求API的返回值，比如，API中返回的记录总数。

**Comment by yiminghe** [comment]
不需要，表格自动渲染

**Comment by netskyline** [comment]
现在的情况是 Table 组件中没有渲染显示记录总数等信息，我想自己包装一下，通过取得 API 返回的数据，进行一些显示，不知道有没有办法拿到 Table.DataSource 中返回的数据集？

**Comment by afc163** [comment]
try `getPagination`

**Comment by netskyline** [comment]
测试了，在里面把 result 保存到全局变量里面，但是更新到 UI 上面的是上一次的数据，

**Comment by netskyline** [comment]
问题解决了，getPagination 中直接 setState 更新 UI 就不会有延迟了
      getPagination(result) {
          that.setState({
            resultTotalCount: result.Data.totalCount
          });
          return {}
      }
