### ISSUE TITLE
【Cascader】组件的子组件有一个Input组件，点击Input时，会直接崩溃

### ISSUE THREAD

**Issue by kobelin923** [ant-design/ant-design#35001]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-19-2-forked-8iztmm)

### Steps to reproduce

打开页面后，点击文本框，必现。
测试过版本是从4.17.0开始的版本都有这个问题，
4.16.13和以前版本没有这个问题。

### What is expected?

修复问题，页面不崩溃。

### What is actually happening?

页面崩溃
报如下错误：
TypeError
Cannot read properties of undefined (reading 'createElement')

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | Mac os monterey 12.3.1 |
| Browser | Microsoft Edge 版本 99.0.1150.55 (正式版本) (arm64) |

**Comment by zpc7** [comment]
`dropdownRender` 属性不知是否能解决你的业务场景, [antd示例](https://ant.design/components/cascader-cn/#components-cascader-demo-custom-dropdown)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33696#issuecomment-1012724385

**Comment by supercat55** [comment]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/26847207/186115816-4eab13c4-9c97-4baa-ab02-306a513e2d3b.png">
在Input上包裹一层div
