### ISSUE TITLE
Modal 组件 TS2322 错误

### ISSUE THREAD

**Issue by Iveon** [ant-design/ant-design#35003]
### Reproduction link

[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce

x

### What is expected?

x

### What is actually happening?

TS2322: Type '{ children: Element; title: any; visible: any; onOk: () => void; onCancel: () => void; }' is not assignable to type 'IntrinsicAttributes & ModalProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & ModalProps'.

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17 |
| System | debian |
| Browser | chrome 100 |

**Comment by Iveon** [comment]
![image](https://user-images.githubusercontent.com/21276534/163108614-8dec5bb1-3cc6-4fda-bc1e-0bbe36b76322.png)

**Comment by Iveon** [comment]
![image](https://user-images.githubusercontent.com/21276534/163108722-9aa9fc1b-7a7f-48c1-9744-5bd78e075267.png)

**Comment by meseme** [comment]
应该是 "@types/react": "18.0.3"的原因，Dropdown目前也报错，18.0.0的DatePicker也报错。

**Comment by Iveon** [comment]
确实是刚刚执行了以下update出现的问题。
![image](https://user-images.githubusercontent.com/21276534/163109153-c948b92a-dcfe-4dd3-ae89-6ffeb90dde73.png)
这也可以...2个@types/react版本

**Comment by Iveon** [comment]
> yarn add "@types/react@^17" -D
先这样用吧

**Comment by ifnk** [comment]
> > yarn add "@types/react@^17" -D
> > 先这样用吧

谢谢，原来 是 types/react 的原因  ，找了半天 错误 ……

**Comment by lamovv** [comment]
如果用的yarn，可先在package.json里锁定一下：
```json
{
  "resolutions": {
    "@types/react": "^17"
  }
}
```

**Comment by Siom-symboint** [comment]
> > yarn add "@types/react@^17" -D
> > 先这样用吧

这样用不是会导致DatePicker.RangePicker报错吗
