### ISSUE TITLE
旧版本的 icon 字体文件地址失效，导致 icon 组件不显示

### ISSUE THREAD

**Issue by lintendo** [ant-design/ant-design#35002]
### Reproduction link

[https://2x.ant.design/components/icon-cn/](https://2x.ant.design/components/icon-cn/)

### Steps to reproduce

访问官网即可：https://2x.ant.design/components/icon-cn/
失效地址：https://at.alicdn.com/t/font_zck90zmlh7hf47vi.woff

### What is expected?

显示图标

### What is actually happening?

不显示图标

| Environment | Info |
| --- | --- |
| antd | 2.11.0 |
| React | 16 |
| System | win/mac |
| Browser | Chrome |

**Comment by afc163** [comment]
可以访问。
