### ISSUE TITLE
Progress type="circle"时，设置的percent数字为98，进度条却是占满100%的状态

### ISSUE THREAD

**Issue by MrZMxZM** [ant-design/ant-design#35009]
### Reproduction link

[https://ant.design/components/progress-cn/](https://ant.design/components/progress-cn/)

### Steps to reproduce

              <Progress
                  type="circle"
                  strokeColor={{
                    '0%': '#EDF1A1',
                    '100%': '#4DEDF7',
                  }}
                  trailColor="#4E85E1"
                  strokeLinecap="square"
                  strokeWidth={15}
                  format={p => p}
                  percent={98}
              />

### What is expected?

显示的percent数字为98，进度条同样沾满98%

### What is actually happening?

显示的percent数字为98，进度条却是沾满的100%的状态

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.13.1 |
| System | windows10 |
| Browser | 87.0.4280.141（正式版本） （64 位） |

---
当type="line"的时候是没有进度条显示不精确的问题的，当type="circle"时，进度条是否精准与strokeWidth属性相关，percent越接近100越不精准

**Comment by afc163** [comment]
确实有问题，圆角边缘才应该是终点，现在的终点是圆角直径切面。

**Comment by afc163** [comment]
和 https://github.com/ant-design/ant-design/issues/19397 和打包一起解决 https://github.com/ant-design/ant-design/issues/17706

**Comment by afc163** [comment]
- https://codepen.io/JMChristensen/pen/AGbeEy
- https://css-tricks.com/building-progress-ring-quickly/
- https://www.geeksforgeeks.org/how-to-create-circular-progress-bar-using-svg/

**Comment by afc163** [comment]
需要重构 Progress，从长计划。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35433
