### ISSUE TITLE
求教：不使用redux，Form组件最快捷实现表单内部数据双向绑定的方式如何做？

### ISSUE THREAD

**Issue by mervynchung** [ant-design/ant-design#3500]
- antd 版本:1.8
- 操作系统及其版本:
- 浏览器及其版本:chrome
#### 您做了什么？

例如如下三个数字输入框a，b，c
c框disabled，且c值= a + b
在a框与b框输入数字，c框的值跟随变化，

```
<FormItem><InputNumber  {...getFieldProps('a')}/></FormItem>
<FormItem><InputNumber  {...getFieldProps('b')}/></FormItem>
<FormItem><InputNumber disabled  {...getFieldProps('c')}/></FormItem>
```
#### 您期待的结果是：

如在 a ， b 分别输入 “3”， ”5“
c框实时赋值”8“
且表单能通过getFieldValues() 采集到 a，b，c三项的值

api文档里看遍还是没找到比较直观的实现

**Comment by afc163** [comment]
try `Input`，`InputNumber` 只有 blur 的时候才会触发 onChange 。

**Comment by mervynchung** [comment]
谢谢回复，我的问题主要是c框的值怎样才能做到跟随a、b两输入框变化。
现在我看文档能想到的实现，是通过onFieldChange，把a、b的值传到上一级组件，在上一级组件实现c=a+b，然后再把a，b，c通过props传回Form，利用Form的mapFieldtoProps把值绑定回输入框。
想知道有没更加简单的实现方式呢？例如利用getFieldProps自身能不能实现c框与a、b的数值联动？

**Comment by benjycui** [comment]
c 应该是不可编辑的吧。

**Comment by mervynchung** [comment]
目前是c不可编辑
c能编辑的情况下如何处理，我也想知道

**Comment by benjycui** [comment]
c 不可编辑直接使用 `getFieldValue('a') + getFieldValue('b')` 就可以了，c 本身不需要 `getFieldProps` 处理。

**Comment by mervynchung** [comment]
现在我用<InputNumber disabled  value = {getFieldValue('a') + getFieldValue('b')}/> 可以实现跟随了。
但我想把c框也可以编辑，并具有fieldname，可以被作为表单的一项提交，该怎样做呢？

**Comment by benjycui** [comment]
要确保数据可靠，这个结果必须由服务端计算，不然我 mock 一个请求，就可以给服务器发送非法数据了。

**Comment by afc163** [comment]
我搞个例子。

**Comment by xutou12** [comment]
这种计算我都只会这样搞 a 和 b 的onChange中使用 setFields( { c: { value: a + b, error: null } } )

**Comment by afc163** [comment]
@mervynchung 

写了一下午，搞出两个表单关联的例子：

利用 onFieldsChange 的例子：http://codepen.io/anon/pen/XjvRzB?editors=001

利用 onChange 的例子：http://codepen.io/anon/pen/VKobro?editors=001

**Comment by benjycui** [comment]
@motorguo `onFieldsChange`，没 error 时才设为 `Button[disabled=false]`。

https://ant.design/components/form/#Form.create(options)

**Comment by motorguo** [comment]
@benjycui   `ant-design-mobile` 似乎没有这个 API, 是不是不支持呢
