### ISSUE TITLE
Image 希望显示 current / total 浏览进度的标题

### ISSUE THREAD

**Issue by mushan0x0** [ant-design/ant-design#35006]
### What problem does this feature solve?

可以显示 Image 图片浏览进度

### What does the proposed API look like?

在image显示的弹窗标题上显示current/total

**Comment by mushan0x0** [comment]
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/29084441/163107970-3ddc394b-a309-498a-a4ac-bad1f5eb9a32.png">

**Comment by afc163** [comment]
来 PR

**Comment by zpc7** [comment]
> 来 PR

那我又来继续加这个顶部进度的 `feature` 吧 😄 , 需要做成配置项吗, 例如: withPosition/withProgress 等

**Comment by mushan0x0** [comment]
@zpc7 image那边已经合并啦

**Comment by zpc7** [comment]
Hi @mushan0x0  我看官网已经更新了版本, 应该有相关的特性了
![image](https://user-images.githubusercontent.com/15316908/163940247-c61f4a07-ae25-4bd1-b320-1f2016fb9b5f.png)

**Comment by mushan0x0** [comment]
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/29084441/163948644-5a87c9ea-7e05-47f6-9100-aa1026cf9027.png">
@zpc7 样式似乎有问题

**Comment by zpc7** [comment]
看起来是rc-image的样式没带过来, 我来修复一下 @mushan0x0
