### ISSUE TITLE
Typography的Paragraph现在多行折叠时，在window 32位系统谷歌浏览器，折叠行数会比预设少一行

### ISSUE THREAD

**Issue by wLove-c** [ant-design/ant-design#35000]
### Reproduction link

[https://ant-design.gitee.io/components/typography-cn/#components-typography-demo-ellipsis](https://ant-design.gitee.io/components/typography-cn/#components-typography-demo-ellipsis)

### Steps to reproduce

```
import { Typography, Switch } from 'antd';

const { Paragraph, Text } = Typography;

const Demo = () => {
  const [ellipsis, setEllipsis] = React.useState(true);

  return (
    <>
      <Paragraph ellipsis={ { rows: 2, expandable: true, symbol: 'more' }}>
        Ant Design, a design language for background applications, is refined by Ant UED Team. Ant
        Design, a design language for background applications, is refined by Ant UED Team. Ant
        Design, a design language for background applications, is refined by Ant UED Team. Ant
        Design, a design language for background applications, is refined by Ant UED Team. Ant
        Design, a design language for background applications, is refined by Ant UED Team. Ant
        Design, a design language for background applications, is refined by Ant UED Team.
      </Paragraph>
    </>
  );
};

ReactDOM.render(<Demo />, mountNode);
```

### What is expected?

如上代码，按理应该是展示2行并...省略其他

### What is actually happening?

展示1行并...省略其他，如果设置3行则展示2行，设置了4行则展示了3行，会比预设少了一行，与window64位同版本的谷歌浏览器表现不一致

| Environment | Info |
| --- | --- |
| antd | 4.18.0 |
| React | ^17.0.2 |
| System | window 10 |
| Browser | 100.0.4896.60（正式版本）(32位) |

**Comment by afc163** [comment]
截个图？

**Comment by wLove-c** [comment]
@afc163 
windows 32位下
![iFu1GcQf8O](https://user-images.githubusercontent.com/24515513/163091792-c6fc454b-8099-47cb-94a8-3bcc32963a55.png)
![HnKsWcjQw8](https://user-images.githubusercontent.com/24515513/163091794-37653c06-422a-4cf2-98a2-3ff2bc2f6b43.png)

Mac 下

![image](https://user-images.githubusercontent.com/24515513/163091793-d8c63587-6246-40a8-a527-c5c4f6462b17.png)

**Comment by wLove-c** [comment]
@afc163 
windows下
![image](https://user-images.githubusercontent.com/24515513/163092370-cee8e112-b7a5-4474-b581-6e8ed2cfe52a.png)
![image](https://user-images.githubusercontent.com/24515513/163092394-ba693980-358a-45b7-9829-1763bccc3162.png)

Mac下
![HnKsWcjQw8](https://user-images.githubusercontent.com/24515513/163092464-ee8bd935-2335-4483-8779-5bffd83f1ccd.png)

刚叫测试同学去ant官网看了下，好像没问题~ 不知道是不是版本原因，但看了下之前的版本日志没有相应的这个问题修复

**Comment by afc163** [comment]
你应用里的 antd 版本是多少

**Comment by wLove-c** [comment]
@afc163 
<img width="224" alt="image" src="https://user-images.githubusercontent.com/24515513/163093550-998213bf-538b-4686-ab55-f7f4ee69a16a.png">

**Comment by afc163** [comment]
1. 检查一下浏览器是否放大缩小了。
2. 检查一下操作系统设置中是否放大缩小了。
3. 可以先升级 antd 到最新，试试看看问题是否还存在。

**Comment by drdevelop** [comment]
@wLove-c you can try @typgraphy-org/react

**Comment by earthaYan** [comment]
@afc163 https://codesandbox.io/s/zhe-die-shou-qi-duan-luo-qnw7q0?file=/src/TextMore.tsx  可复现，注释expandable之后显示行数貌似是符合预期的
