### ISSUE TITLE
希望table的onCell能支持Prosime函数

### ISSUE THREAD

**Issue by Valar103769** [ant-design/ant-design#35004]
### What problem does this feature solve?

有这样一个需求, 使用onCell改变单元格背景颜色, 函数为
```js
{  
onCell: async (record) => ({
   style: backgroundColor: await calcColor(record)
  }) 
}
const calcColor = (record) => 
    new Promise( /** const 总数  = record.xxx */)
    .then(总数 => ({style:{xxx}}))
```

需要所有单元格计算完毕才能得到总数,所有得是异步

### What does the proposed API look like?

 `function(record, index):Promise<any>`

**Comment by afc163** [comment]
不会这么做，render 阶段的函数都会是同步的。
