### ISSUE TITLE
notification的getContainer属性不好使

### ISSUE THREAD

**Issue by maoyutingMyt** [ant-design/ant-design#35014]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/svewor?file=/index.js)

### Steps to reproduce

就改了改上面的代码加了getContainer返回的dom不好使

### What is expected?

期望在对应的dom里展示

### What is actually happening?

实际还是在body里

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
实测没有问题：https://codesandbox.io/s/dai-you-tu-biao-de-tong-zhi-ti-xing-kuang-antd-4-19-5-forked-qpef2i?file=/index.js
