### ISSUE TITLE
Dropdown/Tooltip/Popover 箭头样式显示异常，clip-path属性不支持

### ISSUE THREAD

**Issue by zhupp034** [ant-design/ant-design#35010]
### Reproduction link

[https://ant.design/components/dropdown/](https://ant.design/components/dropdown/)

### Steps to reproduce

1. 鼠标任意带箭头的弹窗

### What is expected?

鼠标任意带箭头的弹窗，显示正常箭头

### What is actually happening?

 箭头很大，clip-path属性不支持导致
![image](https://user-images.githubusercontent.com/33925263/163124794-0149c5af-a5fa-4745-8ad0-f6277181a250.png)
![image](https://user-images.githubusercontent.com/33925263/163124856-bf3d9d4f-ceb8-4a7d-9633-074ff22eb340.png)

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | window 10 |
| Browser | chrome 86 |

**Comment by afc163** [comment]
老的浏览器不支持了，请升级。

**Comment by devchen13** [comment]
最新版的360浏览器

> 老的浏览器不支持了，请升级。

最新版的360浏览器也不支持

**Comment by afc163** [comment]
@devchen13 能看一下最新版 360 浏览器具体是什么版本么

**Comment by devchen13** [comment]
> @devchen13 能看一下最新版 360 浏览器具体是什么版本么

版本号：13.1.6000.0 内核：86.0.4240.198,直接官网下载的最新版本

**Comment by devchen13** [comment]
![image](https://user-images.githubusercontent.com/30109901/172275125-d5c9deea-be9e-413c-8820-bf3ea9f58718.png)


> > @devchen13 能看一下最新版 360 浏览器具体是什么版本么
> 
> 版本号：13.1.6000.0 内核：86.0.4240.198,直接官网下载的最新版本

![image](https://user-images.githubusercontent.com/30109901/172275147-22eeacc3-a325-466e-83f2-d909f0411aca.png)

**Comment by afc163** [comment]
360 的内核版本有点老了。

**Comment by devchen13** [comment]
> 

但用户群体还是不小的，我目前的解决方法是写样式去覆盖，希望出个官方解决方法

**Comment by afc163** [comment]
@MadCcc 看看能不能做个向下兼容？`clip-path: path(...)` 的兼容性确实不太好。

https://developer.mozilla.org/zh-CN/docs/Web/CSS/clip-path#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by yctjb1** [comment]
我最近有遇到类似的问题。似乎看上去并不是clip-path不支持，而是clip-path中的path绘制方式不支持，我用polygon解决了。

                    -webkit-clip-path: polygon(25% 100%, 50% 0%, 75% 100%);
                    clip-path: polygon(25% 100%, 50% 0%, 75% 100%);
这在我的代码中有用。
