### ISSUE TITLE
Ref attribute of Input control causes "Maximum update depth exceeded" exception

### ISSUE THREAD

**Issue by samushenkov** [ant-design/ant-design#35016]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-19-5-forked-3st0fp?file=/index.js)

### Steps to reproduce

1) Add Input control
2) Set ref attribute that keeps actual value in state

### What is expected?

Input control is rendered

### What is actually happening?

"Maximum update depth exceeded." exception happens

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | Windows 11 |
| Browser | Chrome 100.0.4896.75 |

---

Code snippet to use:
```
const PanelView = () => {
  const [ref, refSetter] = useState(null);

  return <Input ref={refSetter} placeholder="Basic usage" />;
};

ReactDOM.render(<PanelView />, document.getElementById("container"));
```

**Comment by MadCcc** [comment]
Use `useRef` to hold component ref.

**Comment by mhesham93** [comment]
I was on 4.12.0 and once I updated to 4.21.7 I started seeing this issue everywhere.
