### ISSUE TITLE
Discussion - default locales in English? 

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#3501]
Default locales are actually in Chinese. Also antd.js  (https://ant.design/docs/react/install) uses Chinese localisation.
What do you think about changing the default locales to English?
Or to consider to have building process with option to choose which locales should be used as a default ones (and other ones via LocaleProvider)?

**Comment by plandem** [comment]
+1 for english

**Comment by benjycui** [comment]
I agree, for the default locale of moment is English, too.

But this cannot be done before next major version, even it is accepted.

**Comment by kvetoslavnovak** [comment]
Agreed, this should go as significant release.

**Comment by kvetoslavnovak** [comment]
Closing   I hope to open as a PR soon.
