### ISSUE TITLE
Table 组件，state 更新的时候不会同步更新使用 render的列(Select组件），导致此列数据不同步

### ISSUE THREAD

**Issue by qkxu** [ant-design/ant-design#35024]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-19-5-forked-vequzt?file=/index.js)

### Steps to reproduce

在table中render一列为select组件，使用value属性，当onchang时更改state，并没有改变，有些类似问题[#418](https://github.com/ant-design/ant-design/issues/418)。即链接中当点击第一个下拉框时，第三个Slect框并没有更新，如果把select单独拿出来，则可以刷新数据，就像链接中的table外的select框。

### What is expected?

期望当onchange中设置state时，会同步更新到table中的select组件中,

### What is actually happening?

期望当onchange中设置state时，并没有同步更新到table中的select组件中

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | @types/react 16.14.24 |
| System | win7/win10 |
| Browser |  100.0.4896.75（正式版本） （64 位） |

---
在table渲染了两列为联动的下拉框，原本使用antd3.x没有问题，后来升级了antd到4.x才发现新版的渲染后的select不能更新

**Comment by MadCcc** [comment]
目前使用 render 属性的话是缓存过的，所以不会更新

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-4-19-5-forked-1tnc7m?file=/index.js

**Comment by qkxu** [comment]
> https://codesandbox.io/s/ji-ben-yong-fa-antd-4-19-5-forked-1tnc7m?file=/index.js

多谢指导，将columns放入到render里面解决问题

**Comment by 666-arch** [comment]
函数式组件呢？怎么处理

**Comment by GuanJdoJ** [comment]
函数式组件用useRef代替useState，可以获取到最新值

**Comment by leiyangs** [comment]
试了下不行，好像render形成了闭包 @GuanJdoJ

**Comment by GuanJdoJ** [comment]
https://codesandbox.io/p/sandbox/antd-colum-ref-tpq47v?file=%2Fsrc%2FApp.jsx%3A43%2C5-45%2C27

去控制台看输出，selectedValues.current已经改变了，只不过改变 ref.current 属性时，React 不会重新渲染组件，想看到页面变化，需要让页面重新渲染一次 @leiyangs
