### ISSUE TITLE
选择框组件在浏览器的设备模拟模式下无法点击显示下拉列表

### ISSUE THREAD

**Issue by 963542298** [ant-design/ant-design#35029]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sokxpw?file=/index.js)

### Steps to reproduce

1. 按f12
2. 打开设备模拟
3. 点击选择框

### What is expected?

点击显示下拉框

### What is actually happening?

无反应

| Environment | Info |
| --- | --- |
| antd | 4.7.3 |
| React | 16.14.0 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/163325064-0c8eedca-901a-4d77-8768-c4d0e025ade0.png">

It works.

**Comment by 963542298** [comment]
![image](https://user-images.githubusercontent.com/45931289/163327479-df8eb2af-ac04-4441-ae2b-3a4cb04f9c55.png)
我开启设备模拟 然后点击那块区域是无法显示下拉框

**Comment by 963542298** [comment]
我想问一下你的chrome版本是多少

**Comment by afc163** [comment]
用 https://sokxpw.csb.app/ 这个链接吧，估计是 codesandbox 里 iframe 交互无法穿透。

**Comment by 963542298** [comment]
我是用chrome和edge都不行，我chrome的版本是100.0.4896.75，edge的版本是100.0.1185.36，我不确定是否跟浏览器的版本相关

**Comment by 963542298** [comment]
我使用你的链接是没问题的，但是我自己写的组件在设备模拟中无法正常工作。然后我给select添加了click事件，然后是能够正常触发的
![image](https://user-images.githubusercontent.com/45931289/163328969-4696844a-ce4f-49b9-9bd9-3b58ea13ce82.png)

**Comment by afc163** [comment]
升级到最新的 antd 版本试试。

**Comment by 963542298** [comment]
好的 我试试

**Comment by 963542298** [comment]
我刚刚把antd 的版本升到了4.19.5还是没办法在设备模式下点击显示下拉框

**Comment by afc163** [comment]
那要想办法给我个重现了，否则我也不好排查，codesandbox 最新版本目前看上去没问题。

**Comment by 963542298** [comment]
那是否可以通过select 设置一个ref让下拉框显示出来，我再想办法弄一个react-app给你。

**Comment by 963542298** [comment]
那你针对这个问题有什么想法，我可以按照你的思路试试

**Comment by 963542298** [comment]
我有尝试其他antd的组件，比如date picker和dropdown这个是没问题的

**Comment by afc163** [comment]
先提供重现吧，定位问题前不想解决办法。

**Comment by 963542298** [comment]
原因找到了是因为项目中引入了react-fastClick 然后导致select组件无法拿到mouseDown事件的冒泡

**Comment by afc163** [comment]
那我关了，这个不是 antd 本身能解决的。
