### ISSUE TITLE
Publish merged PR in components packages

### ISSUE THREAD

**Issue by jdgabriel** [ant-design/ant-design#35021]
### What problem does this feature solve?

Solve latest version merged in PRs.

Merge (#34937) - 5 dasy ago
![image](https://user-images.githubusercontent.com/47068314/163198734-2ce92a21-939f-48eb-906f-4c9325ee81db.png)

Last npm publish - 11 dasy ago
![image](https://user-images.githubusercontent.com/47068314/163198818-580b2283-7e63-4ca9-a44f-5ad0434e3894.png)

Last version - 11 dasy ago
![image](https://user-images.githubusercontent.com/47068314/163198925-b377a3e1-b96b-47e4-b9b6-41d7096065b6.png)

### What does the proposed API look like?

Merge the PR (#34937)

Solve PRs in all component files, this is an example
![image](https://user-images.githubusercontent.com/47068314/163199871-e4e0a68b-9383-4fab-9a15-4a67182876df.png)

This is the build file, installed via yarn
![image](https://user-images.githubusercontent.com/47068314/163200114-0a0cf951-d898-4bb5-b53a-9a9af06fc23a.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/34989#issuecomment-1096469983
