### ISSUE TITLE
tree组件切换数据源的时候，已展开的子节点会看到向左抖动

### ISSUE THREAD

**Issue by destiny4** [ant-design/ant-design#35023]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-t8qewv?file=/index.js)

### Steps to reproduce

点击按钮，切换树数据源，子节点由少变多的时候，会出现抖动，按钮点击间隔慢一点，不要太快

### What is expected?

切换树数据源，子节点由少变多的时候，不会出现子节点抖动

### What is actually happening?

切换树数据源，子节点由少变多的时候，子节点会向左抖动抖动

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | mac OS 12.3.1 |
| Browser | Chrome 版本 100.0.4896.75（正式版本） (arm64) |

---
.ant-tree-indent-unit这个 class 的 span 引起的，需要调整树子节点实现缩进的结构；

**Comment by afc163** [comment]
看上去是同一个问题 #36676 ，合并跟踪

**Comment by afc163** [comment]
Should be fixed in https://github.com/react-component/tree/pull/743
