### ISSUE TITLE
在TS下遍历ColumnsType类型的数组，读取children属性报错

### ISSUE THREAD

**Issue by LeafFalls** [ant-design/ant-design#35032]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kfh5nc?file=/index.tsx)

### Steps to reproduce

```typescript
import type { ColumnsType } from "antd/es/table";

type Record = {
  id: number;
  name: string;
};
const columns: ColumnsType<Record> = [];

columns.forEach((item) => {
  console.log(item.title);
  console.log(item.children);
});
```

### What is expected?

类型不报错

### What is actually happening?

children属性不存在

| Environment | Info |
| --- | --- |
| antd | 4.8.2 |
| React | 16.8.6 |
| System | Window10 |
| Browser | Chrome/100.0.4896.88 |

---
类型应该不报错，我们可以根据children是否存在来判断是column是ColumnGroupType类型还是ColumnType类型，来进行后续处理。

**Comment by zombieJ** [comment]
ColumnsType 没有 children，你要的应该是 ColumnProps

**Comment by LeafFalls** [comment]
> ColumnsType 没有 children，你要的应该是 ColumnProps

![image](https://user-images.githubusercontent.com/49007955/163337136-ba1eb38d-df06-4c8c-9ba2-f2aca83f30db.png)
这不是定义的ColumnsType吗？

**Comment by LeafFalls** [comment]
![image](https://user-images.githubusercontent.com/49007955/163337926-f210e60a-2ab7-4748-b42d-0c2dc5db0dad.png)
这写的应该表达的是columns里的元素是ColumnGroupType类型或ColumnType类型。但在TS里 | 是取两个类型的交集，所以读取columns集合里的元素里的children属性报错不存在

**Comment by zombieJ** [comment]
哦，我误解你是要用 Table.Column 了。

**Comment by zombieJ** [comment]
ColumnsType 是聚合类型，如果你明确每个顶层都包含 children 则可以直接使用 ColumnGroupType。反之 TS 提示不存在 children 是正确的，因为你的上层可能是没有 children 的 ColumnType

**Comment by LeafFalls** [comment]
> ColumnsType 是聚合类型，如果你明确每个顶层都包含 children 则可以直接使用 ColumnGroupType。反之 TS 提示不存在 children 是正确的，因为你的上层可能是没有 children 的 ColumnType

如果是混合的呢？这时应该是要根据它的children是否有值来判断是哪种类型。

**Comment by LeafFalls** [comment]
> > ColumnsType 是聚合类型，如果你明确每个顶层都包含 children 则可以直接使用 ColumnGroupType。反之 TS 提示不存在 children 是正确的，因为你的上层可能是没有 children 的 ColumnType
> 
> 如果是混合的呢？这时应该是要根据它的children是否有值来判断是哪种类型。

children属性应该都是可以被读取到的，只是是否有值的问题。

**Comment by hellowuxin** [comment]
同样有这个问题，混合使用需要判断children，但是ts报错 @zombieJ

**Comment by coderlcb** [comment]
怎么解决呢

**Comment by Sissi-ok** [comment]
我直接这么改了，完了不报错了(ColumnGroupType<自定义类型> | ColumnType<自定义类型>)[],
