### ISSUE TITLE
带搜索自动补全的select组件设置value时，select组件显示code值的问题

### ISSUE THREAD

**Issue by wonyun** [ant-design/ant-design#3503]
#### 发生问题的环境是：

- antd 版本: 2.0.0
- 操作系统及其版本: mac OSX EI Capitan 10.11.1
- 浏览器及其版本: chrmoe 53.0.2785.143

#### 您做了什么？
按照select中带有搜索自动补全的例子修改了一下Option的配置，加了一个value属性对应置为`d.value`，结果每次在选择一个option时，设置state的value为`d.value`，组件展示结果并不是对应code的text值

#### 您期待的结果是：
组件展示对应option中value对应的text值

#### 可重现的在线演示
在原有例子的基础上修改的地方如下
```javascript
//对返回的数据格式进行修改
...
jsonp(`https://suggest.taobao.com/sug?${str}`, (err, d) => {
      if (currentValue === value) {
        const result = d.result;
        const data = [];
        result.forEach((r) => {
          data.push({
            value: r[1],
            text: r[0],
          });
        });
        callback(data);
      }
    });
...
//render方法
const options = this.state.data.map(d => <Option key={d.value} value={d.value+""}>{d.text}</Option>);
    return (
      <div className="ant-search-input-wrapper" style={this.props.style}>
        <Input.Group className={searchCls}>
          <Select
            combobox
            value={this.state.value}
            placeholder={this.props.placeholder}
            notFoundContent=""
            defaultActiveFirstOption={false}
            showArrow={false}
            filterOption={false}
            multiple={false} //加了这个属性
            optionLabelProp="children" //加了这个属性
            optionFilterProp="children" //加了这个属性
            onChange={this.handleChange}
            onFocus={this.handleFocusBlur}
            onBlur={this.handleFocusBlur}
          >
            {options}
          </Select>
          <div className="ant-input-group-wrap">
            <Button className={btnCls} onClick={this.handleSubmit}>
              <Icon type="search" />
            </Button>
          </div>
        </Input.Group>
      </div>
```

如上，在options配置时加了个`value={d.value+"}`,以及3个属性。
请问：该如何做才能选中的option时设置state中value的值后让组件显示value对应的text值？？

另外，搭个车问一下有关select的其他问题：
* 配置combobox下`onChange`在Option选中时也会触发，导致Onchange中获取suggest数据时会额外请求一次参数，为啥选中Option选中的事件不丢到`Onselect`中处理，怎么阻止这最后一次请求
* `onChange` 和`onSelect`事件在某个Option选中时，能否为事件添加一个当前选中Option的值所在对象数组中的item对象的参数呢？

请大神指教，谢谢！

**Comment by benjycui** [comment]
`optionLabelProp` http://ant.design/components/select/#Select-props

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by wonyun** [comment]
@benjycui 大神：
我都把select组件的配置属性看了好几遍了，觉得配置应该是`optionLabelProp`有关，就想配置项描述的：
> 回填到选择框的 Option 的属性值，默认是 Option 的子元素。比如在子元素需要高亮效果时，此值可以设为 value。

combobox模式下该配置值默认为`value`，代码示例中我已经将`optionLabelProp`设置为`children`了啊，可是选择组件后展示的并不是children对应的文本啊。也试了其他几个属性，比方我加了name属性，然后将该属性设置为name也不行。
```javascript
<Option key={d.value} value={d.value+""} name={d.text}>{d.text}</Option>
```

难道是我那个地方用错了么？求教啊

**Comment by afc163** [comment]
http://codepen.io/anon/pen/QKJxpb?editors=0011

value 和 text 不要分开。

在 combobox 模式下，value 和回填的数据是统一的，因为 combobox 本身就是 input。所以你的 value 其实没有意义，既无法提交也在输入中。

```jsx
<Select combobox>
  <Option value={text}>{text}</Option>
</Select>
```

**Comment by afc163** [comment]
补充一下 `Select[combobox]`，实际上就是 https://ant.design/components/auto-complete/

如果你的需求不是 AutoComplete ，那就不要用 `Select[combobox]`，建议改用 `Select[showSearch]`。

**Comment by wonyun** [comment]
其实我想用select[combobox]来实现suggest的功能

**Comment by kolf** [comment]
@wonyun 最后你怎么解决的

**Comment by kingyu** [comment]
@wonyun 这个问题我最近也遇到了，好像是没有解决方案

**Comment by yuanfang-fn** [comment]
如果重新渲染了options，那之前的的value就不能识别了。所以select之后就阻止重新渲染value就好了。

**Comment by jumplee** [comment]
@afc163 或许是时间不足吧。你说的确实是正确的，但是过于简单了吧。

combobox模式确实是错误的，需要用search
同时增加  showSearch labelInValue这两个参数就可以解决楼主的问题


```javascript

    const options = state.user.map((d) => <Option key={d.key}>{d.value}</Option>);

   <Select
                  showSearch
                  labelInValue
                  placeholder="请输入名称或工号"
                  notFoundContent="未找到"
                  defaultActiveFirstOption={false}
                  showArrow={false}
                  filterOption={false}
                  onSelect={userSelectChange}
                  onSearch={userSearch}
                >
                  {options}
                </Select>
```

**Comment by admire7444** [comment]
通过获取的code值在结果集中检索text的文本并显示到select的input中

**Comment by lyjloveabc** [comment]
> @afc163 或许是时间不足吧。你说的确实是正确的，但是过于简单了吧。
> 
> combobox模式确实是错误的，需要用search
> 同时增加 showSearch labelInValue这两个参数就可以解决楼主的问题
> 
> ```js
>     const options = state.user.map((d) => <Option key={d.key}>{d.value}</Option>);
> 
>    <Select
>                   showSearch
>                   labelInValue
>                   placeholder="请输入名称或工号"
>                   notFoundContent="未找到"
>                   defaultActiveFirstOption={false}
>                   showArrow={false}
>                   filterOption={false}
>                   onSelect={userSelectChange}
>                   onSearch={userSearch}
>                 >
>                   {options}
>                 </Select>
> ```

这种方式，我试了我这边可以！感谢大佬

**Comment by 0qiqi0** [comment]
同时给option加上value，key就能解决
