### ISSUE TITLE
Form 'hasFeedback' for non-input components.

### ISSUE THREAD

**Issue by 0407chan** [ant-design/ant-design#35047]
### What problem does this feature solve?

I want to use 'hasFeedback' on Form.
document says 'Recommended to be used only with Input' , and I get this but I want to show which form is done and which form is not done with that feedback.

I can see warnings when I submit 'onFinish' for Input components, but I can't see warnings from un checked checkbox (required).

### Want to be like this
![image](https://user-images.githubusercontent.com/19217576/163530359-5e0b25e1-97f2-4edb-a784-89871cbede13.png)

### What does the proposed API look like?

'hasFeedbackInput', 'hasFeedbackOthers' something like this.

**Comment by afc163** [comment]
We don't recommend `hasFeedback` in other components.
