### ISSUE TITLE
Dropdown鼠标滑过停留在下拉区域下拉区域还是被关闭了

### ISSUE THREAD

**Issue by wanzijinx** [ant-design/ant-design#35051]
### Reproduction link

[https://ant.design/components/dropdown-cn/#components-dropdown-demo-overlay-visible](https://ant.design/components/dropdown-cn/#components-dropdown-demo-overlay-visible)

### Steps to reproduce

鼠标迅速向下划过Hover me 按钮，停留在下拉菜单区域

### What is expected?

下拉菜单区域保持展示

### What is actually happening?

下拉菜单展示后自动关闭了，只有缓慢向下划过才会保持展示

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | windows10 |
| Browser | chrome |

**Comment by MadCcc** [comment]
给个录屏看看？

**Comment by afc163** [comment]
应该只有关闭时才需要 `pointerEvents: 'none'`。

https://github.com/react-component/trigger/blob/ac05814819a13a762136b644b7bf283a363f2d1d/src/Popup/PopupInner.tsx#L185 

类似的样式逻辑在：https://github.com/ant-design/ant-design/blame/master/components/style/mixins/motion.less#L31

**Comment by zombieJ** [comment]
> 应该只有关闭时才需要 `pointerEvents: 'none'`，参考 [ad92793](https://github.com/ant-design/ant-design/commit/ad92793a47d2ccac52b987a0fd8e275d7147370e)
> 
> 现在这个逻辑在 js 实现的时候丢了：https://github.com/react-component/trigger/blob/ac05814819a13a762136b644b7bf283a363f2d1d/src/Popup/PopupInner.tsx#L185
> 
> 类似的样式逻辑在：https://github.com/ant-design/ant-design/blame/master/components/style/mixins/motion.less#L31

DatePicker hover panel 在打开动画过程中因为快速扫过 Date Cell 看起来像是在乱跳，所以两边都禁用了。

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/trigger/pull/297
