### ISSUE TITLE
message.success 相关指令组件 使用参数config的同时 ts类型中还需要指定type

### ISSUE THREAD

**Issue by a572251465** [ant-design/ant-design#35063]
### Reproduction link

[https://gitee.com/li_haohao_1/antd-issue-message/blob/master/src/issue.tsx](https://gitee.com/li_haohao_1/antd-issue-message/blob/master/src/issue.tsx)

### Steps to reproduce

- 点击重现链接会有ts报错，就可以看出来
- 个人认为ts定义有误，是使用message.success的时候 还需要用户指定type，显然是不可理的

### What is expected?

message.success({
  content: '登录成功',
})

### What is actually happening?

message.success({
  content: '登录成功',
  type: 'success' // 多余的类型定义
})

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | React |
| System | win11 |
| Browser | Google 版本 99.0.4844.84（正式版本） |

**Comment by wangkaiwd** [comment]
This have been fixed in 4.20.0-alpha.0 version, changes of code in [here](https://github.com/ant-design/ant-design/commit/5b8e4e51e95c91efe4d57aa08b57fa6401d54111#diff-afb9eb50b70d2e8a149079009b7e3150485edaa7d56dec15d54e6f64da530499L135-L137).
