### ISSUE TITLE
Tree 组件中不能设置itemHeight

### ISSUE THREAD

**Issue by fanhaoyuan** [ant-design/ant-design#35069]
### What problem does this feature solve?

在节点不是默认的24px（大于24px）的时候，使用虚拟滚动，树会有一部分节点（最后的）不能显示，无法滚动到最后的位置。

### What does the proposed API look like?

`itemHeight: number | undefined;`

```ts
<Tree  itemHeight={32} />
```

**Comment by zombieJ** [comment]
`itemHeight` 指的是计算虚拟滚动元素未渲染时的占位高度，这个不是设置节点高度样式。节点高度由content + padding 自适应，要切换高度请使用 css 设置。

**Comment by tobeczm** [comment]
> `itemHeight` 指的是计算虚拟滚动元素未渲染时的占位高度，这个不是设置节点高度样式。节点高度由content + padding 自适应，要切换高度请使用 css 设置。

不能设置节点高度导致item的实际高度和itemHeight 不一致。导致整个ant-tree-list-holder的高度和设置的height不一致。这会导致最后几个几点不可见。
