### ISSUE TITLE
Table columns render 函数不会根据 dataSource 变化而重新执行

### ISSUE THREAD

**Issue by SaberA1ter** [ant-design/ant-design#35079]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-flower-qf8kf5?file=/src/App.js)

### Steps to reproduce

点击 change 按钮，会根据 index 去修改列表中 value true or false

### What is expected?

列表第一列和第二列数据都发生变化

### What is actually happening?

仅第二列会发生变化，第一列则不变

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 仅测试 16.14.0 和 18.0.0 且都存在问题 |
| System | win10 |
| Browser | chrome 100.0.4896.88 |

---
在 antd@4.18.7 及之前版本正常，而在 antd@4.18.8 及之后版本则会出现上述问题

**Comment by MadCcc** [comment]
同样的问题，https://github.com/ant-design/ant-design/issues/35820
会在 v5 优化，现在的解决方法是让 columns 跟着渲染变化。
