### ISSUE TITLE
upload上传插件建议提供隐藏添加按钮的props

### ISSUE THREAD

**Issue by minzhang2** [ant-design/ant-design#3507]
#### 发生问题的环境是：
- antd 版本:
- 操作系统及其版本: 2.1
- 浏览器及其版本: window

#### 您期待的结果是：

限制文件上传个数，当达到限制时，我可以通过设置隐藏按钮的props来控制按钮的显示
![image](https://cloud.githubusercontent.com/assets/15793061/19549201/8ddc42c2-96d5-11e6-9634-33d3dadd0880.png)

#### 实际上的结果是：

upload暂时只提供了disabled的porps，当达到文件上限时，我只能将按钮disabled，这样给人的感觉不太好

#### 可重现的在线演示

暂无

**Comment by afc163** [comment]
```
<Upload>
  {this.state.visible ? <button>上传</button> : null}
</Upload>

**Comment by minzhang2** [comment]
按照您说的方式改了，因为用的是listType: 'picture-card',的展现方式，按钮还是存在，由于用的是Stateless的写法，不能写ref所以这种问题就不好解决了
![image](https://cloud.githubusercontent.com/assets/15793061/19550667/28ed3fda-96dd-11e6-904d-ae6f89a04c3c.png)
![image](https://cloud.githubusercontent.com/assets/15793061/19550678/33cfdd04-96dd-11e6-938a-9d3fb6e0d5aa.png)

**Comment by afc163** [comment]
可以这么解决：

```jsx
<Upload className={hidden ? 'hidden-btn' : ''} />
```

```css
.hidden-btn .ant-upload-select {
  display: none;
}
```

**Comment by minzhang2** [comment]
好的好的，谢谢了
