### ISSUE TITLE
TreeSelect组件=>父级的key和children的key相同的时候会导致扁平化

### ISSUE THREAD

**Issue by JakeQuen** [ant-design/ant-design#35085]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-20-0-alpha-1-forked-yrtm26)

### Steps to reproduce

将parent 的key 设置为 和children 其中一个或者多个key都相同，则会出现

### What is expected?

parent的key 和 children的key  一样不会导致扁平化

### What is actually happening?

parent的key 和 children的key  一样会导致扁平化

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.8 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
对，不要一致，key 需要全局唯一。
