### ISSUE TITLE
Select doesn't scroll to the currently selected value

### ISSUE THREAD

**Issue by kaiyoma** [ant-design/ant-design#35081]
### Reproduction link

[https://ant.design/components/select/](https://ant.design/components/select/)

### Steps to reproduce

If you have a select with lots of options, opening the select does *not* scroll to the currently selected value. Rather, the scroll is kind of random. You can repro this on the documentation page for Select by playing with the "100000 Items" demo. Select and unselect some items until there's only one in the list, then close and reopen the select.

The problem is much more obvious for a single-select.

### What is expected?

The dropdown should scroll to the active option.

### What is actually happening?

The dropdown scrolls to a random location or doesn't scroll at all.

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome 100 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35025 and https://github.com/ant-design/ant-design/releases/tag/4.20.0-alpha.1
