### ISSUE TITLE
新建ts项目中tsx引用modal组件，modal中有子类标签提示报错

### ISSUE THREAD

**Issue by Blluo** [ant-design/ant-design#35082]
### Reproduction link

[https://gitee.com/Bluoluo/ant-Modal.git](https://gitee.com/Bluoluo/ant-Modal.git)

### Steps to reproduce

<Modal
                title="Modal 1000px width"
                centered
                visible={visible}
                onOk={() => setVisible(false)}
                onCancel={() => setVisible(false)}
                width={1000}
            >
                <p>some contents...</p>
                <p>some contents...</p>
                <p>some contents...</p>
            </Modal>

### What is expected?

正常运行，弹出modal框

### What is actually happening?

提示不能将类型“{ children: Element[]; title: string; centered: true; visible: boolean; onOk: () => void; onCancel: () => void; width: number; }”分配给类型“IntrinsicAttributes & ModalProps”。
  类型“IntrinsicAttributes & ModalProps”上不存在属性“children”。

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18，16.14 ，17 |
| System | window10 |
| Browser | html5.0 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/34937

**Comment by shuangsheng1** [comment]
解决了吗 react 17.0.0 用     "antd": "^4.17.2", 还是报这个同样的错误

**Comment by Blluo** [comment]
没有，直接改成jsx写了
