### ISSUE TITLE
onBlur event is triggered immediately after focusing on Input element

### ISSUE THREAD

**Issue by DeepAnchor** [ant-design/ant-design#35080]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-star-tib3ds?file=%2Fsrc%2FApp.js)

### Steps to reproduce

1. Click on Input element 
2. Open dev console
3. Observe that onBlur is triggered immediately after the onFocus event

### What is expected?

onBlur event should not trigger after focusing on Input element. 

### What is actually happening?

onBlur event is triggered immediately after focusing on Input element. 

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | MacOS 12.2.1 |
| Browser | 98.0.4758.109 (Official Build) (arm64) |

---
Only happens with React 18, this was still working fine with React 17.0.2.
I know React 18 compatibility is still a work in progress for Antd v5, just thought I'd file this bug

**Comment by zombieJ** [comment]
动态设置 showCount 也会重新创建元素，需要自行设置焦点。看来文档又要多加一个点：

https://ant.design/components/input-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-prefix/suffix-%E6%97%B6%EF%BC%8CInput-%E4%BC%9A%E5%A4%B1%E5%8E%BB%E7%84%A6%E7%82%B9%EF%BC%9F

**Comment by ranneyd** [comment]
Changing the state of `focus` causes a rerender, which causes the input to reset. If you remove the `setFocus(true)`

To do what you're trying to do, you can wrap the input in its own component (wrapped in `React.memo`) and pass a `setFocus` function (with `useCallback`!). That way, the `focus` state changing doesn't cause this wrapper component to rerender.
