### ISSUE TITLE
createForm()(XXX)后，外层调用refs.aa.handleSubmit()出问题

### ISSUE THREAD

**Issue by muxuehen** [ant-design/ant-design#3509]
我需要用antd的Steps写不同的form，点击下一步时，引用每个form的校验，校验通过时，才允许走到下一步。但是用了creatForm后，就没法用ref。有没有好的办法呢？
项目需要，急等！！！

**Comment by afc163** [comment]
1. 不建议用 refs。http://facebook.github.io/react/docs/more-about-refs.html
2. 有问题，先搜索：https://github.com/ant-design/ant-design/issues/3352
3. https://github.com/ant-design/ant-design/issues/1056

**Comment by muxuehen** [comment]
已看过#3352和#1065，我这种场景用form没法实现了吧！建议，不要修改原ref！

**Comment by benjycui** [comment]
`handleSubmit` 这种场景没必要用 `ref`，用 `onFieldsChange` 把值同步到上层即可。

**Comment by leishuimiao** [comment]
我也是这样的场景，点击下一步需要校验每个引用的表单组建，问下楼主最后怎么解决的 @muxuehen

**Comment by benjycui** [comment]
个人现在的做法是在点击下一步时触发一个自定义事件，然后在组件内部监听这个事件并触发 `validateFields` 即可，类似 jQuery 的自定义事件。

**Comment by zhongjie-chen** [comment]
create时候加上withRef为true的option属性
this.aa.wrappedComponent.refs.formWrappedComponent.handleSubmit()
