### ISSUE TITLE
fieldKey 缺少ts支持

### ISSUE THREAD

**Issue by gaowujian** [ant-design/ant-design#35094]
### Reproduction link

[https://www.baidu.com/](https://www.baidu.com/)

### Steps to reproduce

在使用Form.List组件进行表单项的动态添加的时候，ts提示fieldKey不存在。但是实际上该属性存在，且项目正常运行。应该修复相应的ts类型声明

### What is expected?

类型声明有对应的 fieldKey

### What is actually happening?
只有name和value属性，不包含fieldKey

```
export interface FormListFieldData {
    name: number;
    key: number;
}
declare const FormList: React.FC<FormListProps>;
```

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | linux 20.04 |
| Browser | chrome |

**Comment by TLHSIEH0610** [comment]
field.fieldKey is no longer required after antd@4.18.0. field.key should be the same.
