### ISSUE TITLE
提升国内镜像访问速度

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#35090]
https://ant-design.gitee.io/ 国内镜像最近比较慢，gitee page 的性能有问题。

![图片](https://user-images.githubusercontent.com/507615/163949085-a75d84ea-5c6b-4ba4-b152-59e04cd421ec.png)

考虑几个优化方案：

- [ ] dark.css 和 compact.css 请求都加了时间戳，每次都走不了缓存，gitee pages 的大文件最近一直比较慢，看看有没有办法不加时间戳。而且这两个文件还不小，也可能需要压缩一下。
- [x] gitee 最近不知道为啥特别慢，大文件尤其慢，把 index.js 做一个拆分：https://github.com/ant-design/ant-design/issues/24788
- [x] 给 gitee 发邮件，看看官方有没有解决方案。
- [x] 上面都没效果的话，兜底就是我们自己发一个，缺点是后续需要手动维护。（如果走这个方案，可以检测是否内网，弹框提示切换）

**Comment by Evoque** [comment]
已经慢到影响正常使用了

**Comment by olivewind** [comment]
太卡了，我没想到一个文档站居然可以卡成这样。

**Comment by yoyo837** [comment]
我以为大家都有梯子直接上ant.design，手动 /狗头。

**Comment by linlai163** [comment]
@yoyo837 国内还是有好多不用梯子，只用百度拒绝英文的人的，见过很多。

**Comment by ideaviewes** [comment]
确实是，我还以为是我网络问题呢

**Comment by fontomas** [comment]
感觉国内镜像甚至比github还慢，简直了！
一个文档站，竟然慢到几乎没法使用，这是我从来吗想到过的。

**Comment by afc163** [comment]
- https://gitee.com/oschina/git-osc/issues/I544S3
- https://gitee.com/oschina/git-osc/issues/I5335Y

**Comment by ideaviewes** [comment]
gitee pages应该是个免费的服务，他们公司的体量也没有巨无霸
感觉最好能把antd design的文档放在阿里云的oss？

**Comment by miaojinsing** [comment]
> 我以为大家都有梯子直接上ant.design，手动 /狗头。

用梯子是违法的，无脑孩子。

**Comment by yoyo837** [comment]
> > 我以为大家都有梯子直接上ant.design，手动 /狗头。
> 
> 用梯子是违法的，无脑孩子。

你守你的规，我违我的法。互不影响。

**Comment by yoyo837** [comment]
> > > 我以为大家都有梯子直接上ant.design，手动 /狗头。
> > 
> > 
> > 用梯子是违法的，无脑孩子。
> 
> 你守你的规，我违我的法。互不影响。有没有脑子各自心里有数，不需要提醒。

**Comment by miaojinsing** [comment]
> > > 我以为大家都有梯子直接上ant.design，手动 /狗头。
> 
> > 
> 
> > 用梯子是违法的，无脑孩子。
> 
> 
> 
> 你守你的规，我违我的法。互不影响。有没有脑子各自心里有数就行了，不用提醒。

只是怕你自己不知道。好心的我多虑了。

**Comment by afc163** [comment]
https://gitee.com/oschina/git-osc/issues/I544S3#note_10016366_link

gitee 官方已修复速度问题，我这里访问很快了。

**Comment by MadCcc** [comment]
国内镜像已发布，可以通过 https://ant-design.antgroup.com 访问，稍后会更新导航内容。

**Comment by afc163** [comment]
>  dark.css 和 compact.css 请求都加了时间戳，每次都走不了缓存，gitee pages 的大文件最近一直比较慢，看看有没有办法不加时间戳。而且这两个文件还不小，也可能需要压缩一下。

这个还没搞。
