### ISSUE TITLE
Add document for not using or using ref in Form

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3510]
https://github.com/ant-design/ant-design/issues/2477

https://github.com/ant-design/ant-design/pull/2992

https://github.com/ant-design/ant-design/issues/1056

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/commit/835dc2fb52f4793d07f9c50d49800a7762fd857f

除了这种需要调用 `this.props.form` 里面的方法的情况，其他情况好像都可以避免 `ref`，然后 `this.refs` 好像要废弃了。
