### ISSUE TITLE
分页，当前页为首页时，删除页码，点击搜索或保存等空白地方都没重置。非首页可重置

### ISSUE THREAD

**Issue by yesw6a** [ant-design/ant-design#35118]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-edyfzw?file=/App.js)

### Steps to reproduce

1. 页码框内为1时，删除页码
2. 点击 `one way` 按钮（触发页面状态）
3. 页码框内还是空白
4. 页码框内为2时，删除页码
5. 重复步骤2
6. 页码框内恢复显示1

### What is expected?

当页码框内为空白时，会自动回显为默认页码

### What is actually happening?

没有自动回显

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | Windows/MacOS |
| Browser | Chrome100 |

**Comment by afc163** [comment]
https://codesandbox.io/s/jian-ji-antd-4-20-1-forked-e7ehu9?file=/demo.js

**Comment by yesw6a** [comment]
> https://codesandbox.io/s/jian-ji-antd-4-20-1-forked-e7ehu9?file=/demo.js

成功复现了🥳
