### ISSUE TITLE
Menu.Item can be hidden in horizontal mode

### ISSUE THREAD

**Issue by nasreddineskandrani** [ant-design/ant-design#35117]
Hello,

### Reproduction link

[https://stackblitz.com/edit/react-7nox59?file=demo.js](https://stackblitz.com/edit/react-7nox59?file=demo.js)

### Steps to reproduce

My stackblitz (demo.js file) already show a broken menu because PermissionComponent is returning null.

### What is expected?

PermissionComponent should be able to return null and then the menu item wrapped should be ignored and hidden.
Important: The same code for a vertical mode of antd menu works

### What is actually happening?

The menu crashed

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17 |
| System | All |
| Browser | Chrome |

I am forking the repo. and debugging it => in the little time i have each day it will take time :)
Thanks in advance for your help if you can solve it faster

**Comment by afc163** [comment]
React 17 has same bug: https://stackblitz.com/edit/react-7nox59-cflwmw?file=demo.js

**Comment by nasreddineskandrani** [comment]
@afc163 what do you mean? you linked my stackblitz. You mean `rc.menu`?

**Comment by afc163** [comment]
I fork your stackblitz and make react to v17, and it shows same problem. Just for record.

**Comment by nasreddineskandrani** [comment]
@afc163 sorry i reported 17 in my description when i was using 18. 
Thanks for the quick feedback +1

**Comment by zombieJ** [comment]
Let me take a look

**Comment by nasreddineskandrani** [comment]
@zombieJ how can test this? i need to wait for the next tag version of antd?

**Comment by zChanges** [comment]
@zombieJ how to temporarily fix this problem

**Comment by zChanges** [comment]
@zombieJ modifying rc-overflow through patch-package according to https://github.com/react-component/overflow/pull/20  has no effect, what else needs to be modified

**Comment by nasreddineskandrani** [comment]
4.20 is released - tested all good in our real app not only the stackblitz since it was a little bit different in app.
Thanks again for this super fast fix!
