### ISSUE TITLE
Remove React.FC

### ISSUE THREAD

**Issue by kostazol** [ant-design/ant-design#35115]
### What problem does this feature solve?

https://github.com/facebook/create-react-app/pull/8177
https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components
https://fettblog.eu/typescript-react-why-i-dont-use-react-fc/

### What does the proposed API look like?

-

**Comment by GuichiZhao** [comment]
`children` props is removed from `React.FC` which breaks tons of antd's type declaration

**Comment by PawelBalcerek** [comment]
I'll try this one :).

**Comment by Cattttttttt** [comment]
Is there anyone working on this? Can I try this one?

**Comment by vkuprin** [comment]
Any updates?

**Comment by guan404ming** [comment]
I'll try it today!!

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/41900#issuecomment-1515626474
