### ISSUE TITLE
官网4.x的文档不存在了，最新的文档版本为4.20.0-alpha.1，该版本Menu示例中实现方式与4.19.5稳定版本不同，安装了最新稳定版本4.19.5的项目运行官网Menu示例会报错

### ISSUE THREAD

**Issue by BirdLearn** [ant-design/ant-design#35126]
### Reproduction link

[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce

https://ant.design/components/menu-cn/

### What is expected?

期望官网首页文档中有4.19.5版本的文档

### What is actually happening?

官网首页没有4.19.5版本的文档

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18 |
| System | windows |
| Browser | chrome |

---
4.20.0-alpha.0 的changelog 中有以下改动点：
Menu support items for perf prepare, and children will be removed in next major version.

最新的文档示例都是使用items来创建菜单的，但是4.20.0又没有正式发布，所以当用户安装4.x最新版本4.19.5的时候，官网文档中的示例会报错，而4.19.5的示例也没有

**Comment by afc163** [comment]
我还是先部署一份 4.19.5 的吧。

**Comment by zombieJ** [comment]
在第一个 Demo 位置前加一个 Deprecated 介绍？其他的还是用新的如何？
