### ISSUE TITLE
form 的 onFieldsChange 希望导出 FieldData typing

### ISSUE THREAD

**Issue by RaoHai** [ant-design/ant-design#35121]
### What problem does this feature solve?

写 ts 的时候比较难拿到这个 typing. 现在想拿这个定义非常之麻烦..

```tsx
import type { FieldData } from 'rc-field-form/lib/interface';
```

### What does the proposed API look like?

```tsx
import type { FieldData } from 'antd/lib/form';

const onFieldsChange = useCallback((changedFields: FieldData[]) => {}, []);

```

**Comment by zombieJ** [comment]
```tsx
const onFieldsChange: FormProps['onFieldsChange'] = useCallback((changedFields) => {}, []);
```

**Comment by RaoHai** [comment]
> ```tsx
> FormProps
> ```

![image](https://user-images.githubusercontent.com/566097/164168997-e09f801f-2275-49c0-8f47-ca72ab496898.png)

没用。参数还是 any

**Comment by zombieJ** [comment]
PS: 方法的参数也是可以通过 Parameters<> 推导的

**Comment by zombieJ** [comment]
挪个位置：
<img width="1010" alt="截屏2022-04-20 下午3 02 05" src="https://user-images.githubusercontent.com/5378891/164169759-0351f635-6cdc-4825-8559-a9f0db669868.png">

**Comment by RaoHai** [comment]
> PS: 方法的参数也是可以通过 Parameters<> 推导的

```
type FormData = Parameters<Required<FormProps>['onFieldsChange']>[0];
```

所以我的问题是麻烦。。。

**Comment by zombieJ** [comment]
> 所以我的问题是麻烦。。。

原子的一些类型定义会比较随意，目前还不太想直接导出出来。因为开了之后就收不回去了。

**Comment by rayronvictor** [comment]
@RaoHai 
```typescript
import { FormProps } from 'antd';

type FieldData = Exclude<FormProps['fields'], undefined>[number];
```
