### ISSUE TITLE
Modal 无法挂载到指定节点

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#35124]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-20-0-alpha-1-forked-4mm5qg?file=/demo.js)

### Steps to reproduce

如题

### What is expected?

如题

### What is actually happening?

如题

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by afc163** [comment]
Modal 的 getContainer 和 Drawer 的 getContainer 在实现上就不一样。

Modal 不支持局部容器打开，getContainer 只是用于 dom 节点位置。感觉 Drawer 的 getContainer 命名有问题，我把它废弃掉换个名字。

**Comment by meseme** [comment]
> Modal 的 getContainer 和 Drawer 的 getContainer 的功能上不一样。
> 
> Modal 不支持局部容器打开，getContainer 只是用于 dom 节点位置。感觉 Drawer 的 getContainer 命名有问题，我把它废弃掉换个名字，比如 `getDisplayContainer`

明白了，感谢回复

**Comment by afc163** [comment]
先修改一下文档。
