### ISSUE TITLE
Checkbox: defaultChecked works incorrectly

### ISSUE THREAD

**Issue by AryamnovEugeniy** [ant-design/ant-design#35130]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-20-0-alpha-1-forked-ojgmwl?file=/index.js)

### Steps to reproduce

1. Open the Demo
2. Take a look at two checkboxes: the first one (Antd's) is incorrect, the second one (native) is correct. 

### What is expected?

defaultChecked should work when checked is undefined

### What is actually happening?

defaultChecked is ignored when checked is undefined

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | Mas OS 12.0 |
| Browser | Google Chrome 100.0.4896.127 |

**Comment by afc163** [comment]
It will be a breaking change in 4.x.

**Comment by mikegutierreztelus** [comment]
Hey I want to work on this issue

**Comment by vkuprin** [comment]
It seems like no one has followed up for more than two weeks. That's fine, I'll take over then

**Comment by yoyo837** [comment]
Close by #41888
