### ISSUE TITLE
关于componentWillReceiveProps生命周期方法里调用setFieldsValue死循环的个人意见及解决办法

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#3513]
如： #2985 问题所描述的一样。

1）本人近期也碰到类似问题，按照官方文档所写，使用mapPropsToFields。
起初feel good，可是发现一个问题，假设我进入一个修改表单，利用 mapPropsToFields填充一部分值，剩下一半留待自己填写，其中有个带检索功能的Select，根据搜索输入的值动态option（根据输入的值进行请求数据，进而把数据动态拼装成option），
如果此时我将另一半没有填充值的表单控件输入值然后再进行下拉框检索功能（向后台发起请求）的话，当select的option变化后，我刚刚输入值的那些控件全部初始化了！！蓝瘦啊！！， 经 发现当动态拼装的option更改props时也会触发mapPropsToFields，而这个我却没有办法规避掉，没有条件能够让我if else！
所以愤而将mapPropsToFields删除，改用componentWillReceiveProps + setFieldsValue！

2）可是如何避免2985号话务员所说的setFieldsValue和 react生命周期方法发生的互撕行为呢？答案就是使用一个标识位 isFirst，将此存放在组件state里，初始值为true，更新后执行this.setState({isFirst: false})就ok了，独木桥和阳关道终于分开了。。。。
（在componentWillReceiveProps里setState不会引起render但是依然会改变state里相对应的值，请移步React Docs）
` componentWillReceiveProps(nextProps){`
   ` const {budgetItem} = nextProps;`
    `   const {setFieldsValue} = nextProps.form;`
    `    if (this.state.isFirst) {`
      `      ......(your code)`
     `       setFieldsValue(budgetItem);`
     `       this.setState({`
        `       isFirst: false,`
     `       })`
   `      }`
`      }`

项目环境：React+Redux
意思就是在组件存活期，我只进行一次更新表单

**Comment by benjycui** [comment]
其实 `mapPropsToFields` 基本都是结合 `onFieldsChange` 一起使用的。

**Comment by dreamcatcher081210** [comment]
那可否在官网说明详细一些呢？总感觉官网里的话述就是非mapPropsToFields不行那种意思，也是方便他人少走些弯路吧

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design/issues/3493

**Comment by dreamcatcher081210** [comment]
再补充下，随着业务需求不断改（cao）变（dan），有些时候像上述的用React State来控制标识位的做法已经不可取了，比如：在不能关闭当前form页的情况下，点击任意记录数据，相对应的在form页要实时的展现出来，如果此时还按照上述（即state 标识位来控制）那么做的话是不可行的，因为在form组件存活期，就无法再更新其它数据了。
解决方法：
如果该记录存在唯一的标示符（uuid，id），那就可以写成如下形式进行判断
meeting（为接受到的记录详情）
meetingId（为纪录详情对象的唯一标示符）
`if( meeting && meeting.meetingId != getFieldValue('meetingId')){
      setFieldsValue(meetingId);
     //your code
  }`

**Comment by lileilei** [comment]
componentWillReceiveProps(obj) {
    if (obj.appVo && !this.props.appVo) {
      this.props.form.setFieldsValue(obj.appVo)
    }
  }

当第obj有值，而this.prop.aapVo还没有给赋值，说明是第一次改变appVo属性，所以只会执行一次

**Comment by Molly6943** [comment]
还有一个解决办法是
父组件传一个unique key 给子组件
```  <AddUserModal key={(this.state.user.id || '0') + Date.now()} />```
子组件在componentDidMount的时候使用setFieldsValue方法
```componentDidMount () {
          this.props.form.setFieldsValue({
             fullName: user.full_name,
             mobile: user.mobile,
             email: user.email,
             password: user.password
    });
  }
```

原理貌似是 react在检测到key有变化的时候，会重新render
（小白，理解不到位的话，望指正）

**Comment by dreamcatcher081210** [comment]
@Molly6943 谢谢，还是需要根据当前业务模块设定来具体看待，符合“父-子”关系的组件，该方法可行！！！不符合时也只能像上述的那样了。
另：
`<AddUserModal key={(this.state.user.id || '0') + Date.now()} />`
这种设置key的方式 是否在特定情况下存在不可控的风险？而导致性能的不必要损耗？建议可控的选择手动设置uuid吧？！

**Comment by vonxq** [comment]
一年后再看这问题，分享一个解决思路吧

**Comment by ogbiyoyosky** [comment]
The above will work if only you set the state along side the componentDidMount live cycle event.

**Comment by HaiYoungs** [comment]
函数组件中使用 useEffect 在 componentDidMount 阶段去设置值（setFieldsValue) 可以解决
