### ISSUE TITLE
TS Error: Property 'items' does not exist on type 'Required<MenuProps>'

### ISSUE THREAD

**Issue by tobiasriemenschneider** [ant-design/ant-design#35135]
### Reproduction link

[https://ant.design/components/menu/#components-menu-demo-theme](https://ant.design/components/menu/#components-menu-demo-theme)

### Steps to reproduce

Copy code of https://ant.design/components/menu/#components-menu-demo-theme and try to get it working.

### What is expected?

Code compiles.

### What is actually happening?

TS error is thrown: `Property 'items' does not exist on type 'Required<MenuProps>'.`

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | mavcOS Monterey 12.2.1 |
| Browser | Google Chrome Version 100.0.4896.127 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/34937

**Comment by tobiasriemenschneider** [comment]
Thanks for your reply @afc163.

I'm on **React 17** though. 🤔

**Comment by OSfrog** [comment]
I'm having the same problems on React 18

**Comment by Susie6** [comment]
I‘m having the same problems too

**Comment by TomasMoratoPerezPorro** [comment]
Same here on react 17.0.2 ! 😢

**Comment by blockmood** [comment]
修好了吗这个问题。

**Comment by longld-0832** [comment]
Got same problem on React 17.0.2

**Comment by leo-rq22** [comment]
Got the same problem on React 17.0.0
