### ISSUE TITLE
Tabs搭配select出现样式异常

### ISSUE THREAD

**Issue by LL1314520** [ant-design/ant-design#35136]
### Reproduction link

[https://stackblitz.com/edit/fqjvgl--run?file=index.js](https://stackblitz.com/edit/fqjvgl--run?file=index.js)

### Steps to reproduce

antd的Tabs组件结合Select组件使用时，将Select组件设置getPopupContainer={el => el.parentNode}，Select挂载异常，没有挂载到select下而是挂载到了tabs下面，下面是代码：
```
import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { Tabs,Select } from 'antd';

const { TabPane } = Tabs;
const { Option } = Select

function callback(key) {
  console.log(key);
}

ReactDOM.render(
  <div>
  <Tabs defaultActiveKey="1" onChange={callback}>
  <TabPane tab="Tab 1" key="1">
    <Select defaultValue="lucy" style={{ width: 120 }} getPopupContainer={el => el.parentNode} >
      <Option value="jack">Jack</Option>
      <Option value="lucy">Lucy</Option>
      <Option value="disabled" disabled>
        Disabled
      </Option>
      <Option value="Yiminghe">yiminghe</Option>
  </Select>
  </TabPane>
  <TabPane tab="Tab 2" key="2">
    Content of Tab Pane 2
  </TabPane>
  <TabPane tab="Tab 3" key="3">
    Content of Tab Pane 3
  </TabPane>
</Tabs>
</div>,
  document.getElementById('container'),
);
```
   

### What is expected?

select能够挂载到正确位置

### What is actually happening?

下拉框挂载到了tabs下面

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18 |
| System | mac最新版本 |
| Browser | chrome最新版本 |

**Comment by LL1314520** [comment]
上面的复现链接打不开，重新弄了一个，应该可以打开，https://fqjvgl--run.stackblitz.io

**Comment by LL1314520** [comment]
上面的复现链接打不开，重新弄了一个，应该可以打开，https://fqjvgl--run.stackblitz.io

**Comment by afc163** [comment]
https://fqjvgl--run.stackblitz.io/ 也打不开

**Comment by LL1314520** [comment]
codesandbox链接：https://codesandbox.io/s/antd-reproduction-template-forked-loogec?file=/index.js，麻烦看下

**Comment by LL1314520** [comment]
新的codesandbox链接，麻烦看下：https://codesandbox.io/s/antd-reproduction-template-forked-loogec?file=/index.js @afc163

**Comment by afc163** [comment]
先去掉 getPopupContainer={(el) => el.parentNode} 把，或者挂载到 Tabs 外面。

**Comment by LL1314520** [comment]
但是现在的业务下有Tabs中的select滚动场景，所以麻烦能处理下挂载异常的问题 @afc163

**Comment by afc163** [comment]
挂载没有异常，只是 Tabs 上有个 `overflow: hidden;`，你可以先覆盖掉，我看看当初为啥要加这个。

https://github.com/ant-design/ant-design/issues/34021#issuecomment-1103356525

**Comment by LL1314520** [comment]
好的，解决了，谢谢大哥 @afc163
