### ISSUE TITLE
同时使用Select 和 useState 出现异常

### ISSUE THREAD

**Issue by yh4922** [ant-design/ant-design#35143]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-4-20-0-alpha-1-forked-t5nomx?file=/demo.js:0-628)

### Steps to reproduce

使用 `const [val, setVal] = useState("");` 绑定Select的值 在`onChange`回调中 调用 `setVal`方法后 打印`val `值无法获取到最新的值
获取到的都是上一次修改的值

### What is expected?

期望在 `setVal()` 之后能获取到最新的 `val`

### What is actually happening?

只能获取到上一次的值

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 18.0.0 |
| System | win10 21H2 19044.1526 |
| Browser | Google Chrome 100.0.4896.88 |

**Comment by afc163** [comment]
和 antd 无关：https://codesandbox.io/s/dai-sou-suo-kuang-antd-4-20-0-alpha-1-forked-s7gyfc
