### ISSUE TITLE
antd tabs typescript cannot infer active key type

### ISSUE THREAD

**Issue by shanpig** [ant-design/ant-design#35149]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-pine-6z6uyi?file=/src/App.tsx)

### Steps to reproduce

already in codesandbox

### What is expected?

Tabs component can have approaches to infer key types, rather than just string type.

### What is actually happening?

Tabs has no generic type of active key, and thus the onChange function will return a key which is string type.
Is there any possibility to support generic typing of the tab key?

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.1 |
| System | macOS Monterey 12.0.1 |
| Browser | chrome 100.0.4896.127  |

**Comment by zombieJ** [comment]
Whatever type pass to `key`, React will always convert to string type. Definition is correct: https://codesandbox.io/s/summer-field-z1gmg1?file=/src/App.tsx
