### ISSUE TITLE
setState is updating ,but not rendering UI in beforeUpload function in upload component in antd

### ISSUE THREAD

**Issue by Khadhiri786** [ant-design/ant-design#35150]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sbpgko?file=/index.js)

### What is expected?

when user upload image, the modal pop-up is not opening, but displayCaptionModal is true

### What is actually happening?

For this temp-solution, I have to do forceUpdate(), to open the modal

| Environment | Info |
| --- | --- |
| antd | 4.8.2 |
| React | 16.4 |
| System | Windows 10 |
| Browser | Google chrome |

**Comment by Khadhiri786** [comment]
@zombieJ  https://codesandbox.io/s/antd-reproduction-template-forked-sbpgko?file=/index.js

Expected Output: when User upload image, the modal needs to open

**Comment by afc163** [comment]
<img width="1358" alt="图片" src="https://user-images.githubusercontent.com/507615/164415110-436d1d97-5db3-4049-ae7b-2ca8a9749fbd.png">

https://codesandbox.io/s/antd-reproduction-template-forked-kor8qk?file=/index.js

It works.
