### ISSUE TITLE
Ant Tree Child cannot drag to top level index

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#35159]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-i92fs?file=/tree.jsx:0-3850)

### Steps to reproduce

Drag the second child index to be a first level index 

### What is expected?

should be able to change positions

### What is actually happening?

cant change position

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | react |
| System | macOS Monterey v12.3.1 |
| Browser | Google Chrome v100.0.4896.127 |

**Comment by zombieJ** [comment]
Please ref official demo:
https://ant.design/components/tree-cn/#components-tree-demo-draggable

![Kapture 2022-04-23 at 12 43 41](https://user-images.githubusercontent.com/5378891/164878042-8b789596-5c25-4645-bb05-e22eb951e730.gif)
