### ISSUE TITLE
Form组件校验期望校验数组格式数据

### ISSUE THREAD

**Issue by yangbo960618** [ant-design/ant-design#35151]
### What problem does this feature solve?

比如在select填入多个邮箱的时候

### What does the proposed API look like?

<Form.Item
        label="Email"
        name="Email"
        rules={[
          { 
            required: true,  
            pattern: new RegExp(/^[\w-] (\.[\w-] )*@([\w-] \.) [a-zA-Z] $/), 
            message: 'Please enter a valid email address'
          }
        ]}
      >
         <Select
                      mode="tags"
                      placeholder="Please select"
                    >
          </Select>
      </Form.Item>

**Comment by afc163** [comment]
建议用自定义 validator 去校验。
