### ISSUE TITLE
使用ant design的table，如何在某个table cell上绑定事件

### ISSUE THREAD

**Issue by anhuiliujun** [ant-design/ant-design#3515]
#### 发生问题的环境是：

- antd 版本: 1.6.5
- 操作系统及其版本: mac os 10.11.3
- 浏览器及其版本: chrome 53

使用ant design的table时，有个需求是点击某一行的某一列上，就弹出一个modal，不知该如何实现呢，table目前只支持onRowClick，如何处理这种onCellClick呢？

**Comment by anhuiliujun** [comment]
不知道大家有没有类似的需求？

**Comment by dreamcatcher081210** [comment]
(⊙o⊙)…可以自己进行操作啊，render里进行啊，加点击事件

**Comment by anhuiliujun** [comment]
ok，豁然开朗，一开始从想着怎么去通过dom去绑定了，谢谢，搞定了
