### ISSUE TITLE
Dropdown overlay menu cannot be a functional component containing hooks

### ISSUE THREAD

**Issue by Janaka-Steph** [ant-design/ant-design#35163]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ndmiv1)

### Steps to reproduce

Hover over dropdown button. 

### What is expected?

It just works

### What is actually happening?

You will get error `Invalid hook call`

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | MacOS 12.3.1 |
| Browser | Chrome v100 |

**Comment by zombieJ** [comment]
Dropdown is strong coupling with Menu instance which not support HOC.

**Comment by Janaka-Steph** [comment]
> Dropdown is strong coupling with Menu instance which not support HOC.

So there is no solution at all? Any alternatives?

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-itq7l0?file=/index.js
