### ISSUE TITLE
怎样修改监听端口号8989为其他端口

### ISSUE THREAD

**Issue by zhangolve** [ant-design/ant-design#3517]
使用antd-demo

antd-demo@1.0.0 dev /Users/xxx/git/src/demo
> dora -p 8001 --plugins atool-build,proxy,hmr

          proxy: listened on 8989
📦  311/311 build modules
webpack: bundle build is now finished.

我现在有两个项目要同时进行，如何设置能够改变   proxy: listened on 8989 监听端口。

**Comment by afc163** [comment]
`dora -p 8001 --plugins atool-build,proxy?port=9999,hmr`

**Comment by zhangolve** [comment]
应该还要同时修改dora端口吧，比如
dora -p 8002 --plugins atool-build,proxy?port=9999,hmr
否则，还是会出现端口的冲突。
我已经试过了，没问题了。
