### ISSUE TITLE
Form的preserve属性不生效

### ISSUE THREAD

**Issue by YagamiNewLight** [ant-design/ant-design#35177]
### Reproduction link

[https://stackblitz.com/edit/react-uqnwvg?file=demo.js](https://stackblitz.com/edit/react-uqnwvg?file=demo.js)

### Steps to reproduce

1. 点击按钮，弹出弹框，展示初始文本“汉堡0”
2. 点击关闭弹框，此时状态汉堡0变成了“嗨嗨嗨，汉堡1”
3. 再次打开弹框，初始文本应该是“嗨嗨嗨，汉堡1”
4. 结果还是“汉堡0”，关闭弹框，这个时候状态变成了“嗨嗨嗨，汉堡2”
5. 再次打开弹框，文本是已过期的“嗨嗨嗨，汉堡1”.

### What is expected?

第三步打开弹框时，展示文本应该是“嗨嗨嗨，汉堡1”
第五步打开弹框时，展示文本应该是“嗨嗨嗨，汉堡2”

### What is actually happening?

文本是过期的，没有展示最新传进去的状态

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Win10 |
| Browser | Chrome  91.0.4472.77 |

**Comment by zombieJ** [comment]
Modal 在关闭的时候不会更新窗体内的内容，所以 Form 的 initialValues 其实没有变化。这得加到文档里，免得坑人了。

**Comment by YagamiNewLight** [comment]
是所以上述情况下，想要重置表单初始值只能用`form.setFieldsValue`吗

**Comment by crazyair** [comment]
> Modal 在关闭的时候不会更新窗体内的内容，所以 Form 的 initialValues 其实没有变化。这得加到文档里，免得坑人了。

是因为 form 实例没有卸载，store 也还在。你可以看看这个 https://stackblitz.com/edit/react-uqnwvg-9v2zrr?file=demo.js

**Comment by YagamiNewLight** [comment]
@crazyair 那上述问题该怎么解决呢。我想在modal重新打开的时候应用我传进去的initialValues

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/commit/eb70223bdb2c2619067bcb47ba424ddef397c6c4

**Comment by crazyair** [comment]
> @crazyair 那上述问题该怎么解决呢。我想在modal重新打开的时候应用我传进去的initialValues

问题不在于 Modal，但是还是依旧是 form 的问题，除非你不实例化 form，或者打开的时候 resetFields 一次。

**Comment by YagamiNewLight** [comment]
> > @crazyair 那上述问题该怎么解决呢。我想在modal重新打开的时候应用我传进去的initialValues
> 
> 问题不在于 Modal，但是还是依旧是 form 的问题，除非你不实例化 form，或者打开的时候 resetFields 一次。

https://stackblitz.com/edit/react-uqnwvg-zpn3qk?file=demo.js 
调用resetFields方法貌似还是不行

**Comment by crazyair** [comment]
> > > @crazyair 那上述问题该怎么解决呢。我想在modal重新打开的时候应用我传进去的initialValues
> > 
> > 
> > 问题不在于 Modal，但是还是依旧是 form 的问题，除非你不实例化 form，或者打开的时候 resetFields 一次。
> 
> https://stackblitz.com/edit/react-uqnwvg-zpn3qk?file=demo.js 调用resetFields方法貌似还是不行

![image](https://user-images.githubusercontent.com/7971419/164953321-b8aa33bf-48ee-46e9-a21f-9f06eac74beb.png)

**Comment by YagamiNewLight** [comment]
> > > > @crazyair 那上述问题该怎么解决呢。我想在modal重新打开的时候应用我传进去的initialValues
> > > 
> > > 
> > > 问题不在于 Modal，但是还是依旧是 form 的问题，除非你不实例化 form，或者打开的时候 resetFields 一次。
> > 
> > 
> > https://stackblitz.com/edit/react-uqnwvg-zpn3qk?file=demo.js 调用resetFields方法貌似还是不行
> 
> ![image](https://user-images.githubusercontent.com/7971419/164953321-b8aa33bf-48ee-46e9-a21f-9f06eac74beb.png)

Emmm 感觉这样多少有点不优雅。。你们推荐直接用`form.setFields`这种方法吗，我认为在这种情况下`form.setFields`用注入进去的store去表达更好点？

**Comment by crazyair** [comment]
那 Modal 不设置 destroyOnClose 就可以这样用了
```
  const showModal = () => {
    setVisible(true);
    form.resetFields();
  };
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/fb04927ada6ef4a15e598499b9ff044c3dc5e7a3#diff-7a204621cc9425007680c097ad01151df377979692bbc09eb2796025b85043f3R52

这段说明如果不准确，也需要更新掉。@zombieJ

**Comment by YagamiNewLight** [comment]
其实我觉得逻辑应该是这样的：
1. `<Form name="form-1" />`标签在销毁的时候，如果内部form实例是受控传进来的，那么可以在组件销毁的时候根据`form-1`去对form实例进行对应的初始化。类似于`form.resetFieldsOf(name)`
2. 如果Form没有这样的默认行为，那么就需要在react state和form实例两个store里面进行状态的同步，这样的话还不如在react state改变的时候去显式的设置form. (这个时候<Form />标签的初始值仅在非受控条件下应用，如果都受控了，那么初始值就应该在受控实例`useForm()`实例化的时候去设置好，这里初始化的逻辑就跟实例初始化的时机绑定了，后续想要改初始化的值也会自然联想到直接去用实例的setFields方法.

**Comment by crazyair** [comment]
需要加 setTimeout 的原因是，Modal 打开需要加载完成 Form 后调用 resetFields 才会有效果。如果 Form 没有加载完成，执行 resetFields 是没用的。

**Comment by afc163** [comment]
这个问题之前就讨论过 https://github.com/ant-design/ant-design/issues/21740#issuecomment-644008703

后来才因此有了 preserve 属性：https://github.com/ant-design/ant-design/issues/21740#issuecomment-660825508

只是本帖的问题是，初始值 initialValues 目前没办法动态变化。

**Comment by crazyair** [comment]
要解决 issue 那个问题，有个简单的方法，就是 initialValues 在 useForm 里设置
```
const [ form ] = Form.useForm(null,{ initialValues:{ input: modalText } })
const showModal = () => {
    form.resetFields();
    setVisible(true);
  };
```

**Comment by YagamiNewLight** [comment]
> 要解决 issue 那个问题，有个简单的方法，就是 initialValues 在 useForm 里设置
> 
> ```
> const [ form ] = Form.useForm(null,{ initialValues:{ input: modalText } })
> const showModal = () => {
>     form.resetFields();
>     setVisible(true);
>   };
> ```

https://stackblitz.com/edit/react-uqnwvg?file=demo.js
好像不行呢？是我姿势错了？

**Comment by crazyair** [comment]
@YagamiNewLight 其实 form 应该在 Modal 里实例化，因为如果一个页面有多个 Modal Form ，在 Modal 未打开时，也需要实例化多个 form 有点不太好，Form 应该在 Modal 里面使用 https://zhuanlan.zhihu.com/p/388222294

**Comment by crazyair** [comment]
> > 要解决 issue 那个问题，有个简单的方法，就是 initialValues 在 useForm 里设置
> > ```
> > const [ form ] = Form.useForm(null,{ initialValues:{ input: modalText } })
> > const showModal = () => {
> >     form.resetFields();
> >     setVisible(true);
> >   };
> > ```
> 
> https://stackblitz.com/edit/react-uqnwvg?file=demo.js 好像不行呢？是我姿势错了？

这个是意见，(API 没实现呢)

**Comment by YagamiNewLight** [comment]
> 

这种情况下，我觉得用ref来获取实例可能更好一点

> @YagamiNewLight 其实 form 应该在 Modal 里实例化，因为如果一个页面有多个 Modal Form ，在 Modal 未打开时，也需要实例化多个 form 有点不太好，Form 应该在 Modal 里面使用 https://zhuanlan.zhihu.com/p/388222294

我觉得这种情况下用ref来获取实例可能更好一点

**Comment by crazyair** [comment]
> > @YagamiNewLight 其实 form 应该在 Modal 里实例化，因为如果一个页面有多个 Modal Form ，在 Modal 未打开时，也需要实例化多个 form 有点不太好，Form 应该在 Modal 里面使用 https://zhuanlan.zhihu.com/p/388222294
> 
> 我觉得这种情况下用ref来获取实例可能更好一点

我是不推荐用 ref 的，除非要获取 dom 元素，基本不用 ref

**Comment by YagamiNewLight** [comment]
> 

我觉得可以，既然使用的是注入store的方式，初始化值就由实例store初始化的时候去注入

**Comment by YagamiNewLight** [comment]
> 

我觉得ref是可以拿到非受控组件内部的数据流的，这样没啥问题。dom元素本质上也就是一个非受控组件。

**Comment by KingAmo** [comment]
请问这个问题解决了吗，只能手动reset吗

**Comment by YagamiNewLight** [comment]
> 请问这个问题解决了吗，手动reset似乎也不生效呢

```
const showModal = () => {
    setVisible(true);
    setTimeout(() => {
      form.resetFields();
    });
  };
```
打开弹框的时候在setTimeout里调一下resetFields

**Comment by WeiShengv99** [comment]
这个问题让人痛苦

**Comment by crazyair** [comment]
我自己是封装了，只有 visible =true 才会加载 Modal 组件(既加载 Form 组件)，visible = false 会卸载 Modal+Form，来达到 Form 实例跟随 Modal 打开加载，关闭卸载。

**Comment by WeiShengv99** [comment]
> 我自己是封装了，只有 visible =true 才会加载 Modal 组件(既加载 Form 组件)，visible = false 会卸载 Modal+Form，来达到 Form 实例跟随 Modal 打开加载，关闭卸载。

我也打算封装下  modal 了 直接 让form store 卸载

**Comment by WeiShengv99** [comment]
> 我自己是封装了，只有 visible =true 才会加载 Modal 组件(既加载 Form 组件)，visible = false 会卸载 Modal+Form，来达到 Form 实例跟随 Modal 打开加载，关闭卸载。

或许 不适用 Form.useForm 是一个方式  这样也可以避免这个问题  这是改动最少的方式  使用ref去获取

**Comment by AttackXiaoJinJin** [comment]
那我觉得目前有三种解决方法：

1. 不用 useForm，Modal/Drawer 使用 destroyOnClose，来重置表单值，代价是不能用 useForm

2. visible && <Modal/> / <Drawer/> ，直接销毁内部节点和状态，代价是 close 时没有动画

3. 使用 Form 的 setFieldsValue，变成可控 form，代价是不能使用 initialValues

**Comment by wpfalive** [comment]
Form配合Modal使用时，不要给Form设置initialValues, 否则给Modal设置destroyOnClose页不会在Modal关闭时销毁表单字段数据
解决方案如下：
```js
useEffect(() => {
    if (!initialValue) {
        form.resetFields()
    } else {
        form.setFieldsValue(initialValue)
    }
}, [modalVisible])
```

**Comment by yoyo837** [comment]
> Form配合Modal使用时，不要给Form设置initialValues, 否则给Modal设置destroyOnClose页不会在Modal关闭时销毁表单字段数据 解决方案如下：
> 
> ```js
> useEffect(() => {
>     if (!initialValue) {
>         form.resetFields()
>     } else {
>         form.setFieldsValue(initialValue)
>     }
> }, [modalVisible])
> ```

那是因为`form={form}`吧, 和 `destroyOnClose` 没关系, 给看看你的demo? See https://github.com/ant-design/ant-design/issues/42505

**Comment by wpfalive** [comment]
您的来信已收悉，我会尽快回复

**Comment by crazyair** [comment]
https://antd-pro-max.crazyair.cn/form

**Comment by wpfalive** [comment]
> > Form配合Modal使用时，不要给Form设置initialValues, 否则给Modal设置destroyOnClose页不会在Modal关闭时销毁表单字段数据 解决方案如下：
> > ```js
> > useEffect(() => {
> >     if (!initialValue) {
> >         form.resetFields()
> >     } else {
> >         form.setFieldsValue(initialValue)
> >     }
> > }, [modalVisible])
> > ```
> 
> 那是因为`form={form}`吧, 和 `destroyOnClose` 没关系, See #42505 或者给看看你的demo 来个新issue?

你说得对，之前没关注到那个issue.

**Comment by wpfalive** [comment]
> > Form配合Modal使用时，不要给Form设置initialValues, 否则给Modal设置destroyOnClose页不会在Modal关闭时销毁表单字段数据 解决方案如下：
> > ```js
> > useEffect(() => {
> >     if (!initialValue) {
> >         form.resetFields()
> >     } else {
> >         form.setFieldsValue(initialValue)
> >     }
> > }, [modalVisible])
> > ```
> 
> 那是因为`form={form}`吧, 和 `destroyOnClose` 没关系, See #42505 或者给看看你的demo 来个新issue?

你说得对，之前没关注到那个issue.

**Comment by PigPiggo** [comment]
2025 年了，这个问题解决了吗

**Comment by wpfalive** [comment]
您的来信已收悉，我会尽快回复
