### ISSUE TITLE
Segmented component highlighted option doesn't change on value change

### ISSUE THREAD

**Issue by arche-alan** [ant-design/ant-design#35170]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js)

### Steps to reproduce

Ant version is actually 4.20.0-alpha.1 Which I know isn't the latest stable version but this is still a bug. Not allowed to use CodeSandBox on enterprise network.

const [foo, setFoo] = useState("AND")

<Segmented
  value={foo}
  options={["AND", "OR"]}
  onChange={(e) => setFoo(e.target.value)}
/>
<Segmented
  value={foo}
  options={["AND", "OR"]}
  onChange={(e) => setFoo(e.target.value)}
/>

### What is expected?

The highlighted option should not be dependent on a "click" event on the Segmented component but rather should be dependent on the value passed into the component. I want multiple Segmented to be listening to the same state and the highlighted option should change on all Segmented components when state value changes, not only when the component is clicked. 

### What is actually happening?

Shared state value will be "OR" but one Segmented component will have "AND" highlighted but the other component that was clicked will have "OR" highlighted. 

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Chrome Version 100.0.4896.75 (Official Build) (64-bit) |

---
This functionality works as expected with the Switch component.

**Comment by afc163** [comment]
Reproduce: https://codesandbox.io/s/antd-reproduction-template-forked-79kn5o?file=/index.js

**Comment by vagusX** [comment]
@arche-alan fixed in rc-segmented https://github.com/react-component/segmented/releases/tag/v1.3.1, try to update local node_modules

**Comment by vagusX** [comment]
> Reproduce: [codesandbox.io/s/antd-reproduction-template-forked-79kn5o?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-forked-79kn5o?file=/index.js)

works with rc-segmented@1.3.1 https://codesandbox.io/s/antd-reproduction-template-forked-hvcsin

**Comment by faradaytrs** [comment]
Actually still doesn't work with rc-segmented 2.0.0,
