### ISSUE TITLE
[Typography] `copyable` prop copies a dark background with dark text

### ISSUE THREAD

**Issue by kripod-wise** [ant-design/ant-design#35182]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gfs9qe?file=/index.js)

### Steps to reproduce

Try copying the text using the button next to it and then pasting it into [a new Google Docs document](https://doc.new/).

### What is expected?

There should be no dark background or copied along with the text itself

<img width="721" alt="image" src="https://user-images.githubusercontent.com/92147789/164720367-9d40d2ee-2224-4d3b-a616-294f3db758f1.png">

### What is actually happening?

The dark background is being copied while the text itself is dark as well, making pasted snippets unreadable.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/92147789/164720192-6b035cb6-77b5-4e4e-8447-bb73771e2a5a.png">

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | macOS 12.3.1 |
| Browser | Chrome 100 |

**Comment by kanweiwei** [comment]
The dark background is the `document.body` 's backgroundColor, which is a default behavior。

Maybe we can use the `options.format` of `copy-to-clipboard` to do what you want.
