### ISSUE TITLE
Tooltip will jump up when first show

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#35197]
Browser: Mac Chrome 100.0.4896.127
Reproduce: https://ant.design/components/tooltip-cn/#components-tooltip-demo-basic

Steps:

1. Hover mouse on trigger
2. See Tooltip

![Apr-23-2022 23-33-15](https://user-images.githubusercontent.com/507615/164912800-b4e89c47-4ca9-4119-822c-ba6a9d635fee.gif)

**Comment by easyterry** [comment]
最近也发现了，甚至导致第一次hover会遮挡包裹元素的点击，体验感很差。

**Comment by zombieJ** [comment]
时序问题，Tooltip 在渲染之前不知道位置的时候是没有 padding 的。当觉得上面放得下后，就添加 class 标注在上方展示，这时候就添加了 paddingBottom。然后导致高度变化又重新 align：
<img width="348" alt="截屏2022-04-25 下午5 18 37" src="https://user-images.githubusercontent.com/5378891/165059642-7296ea82-2a09-4403-8e8c-cb77381c4e2b.png">

原来 rc-align 用的是同步对齐，但是在 React 18 会死循环。得想想办法。
