### ISSUE TITLE
tree组件的搜索功能结果渲染不正确

### ISSUE THREAD

**Issue by qianchengjie** [ant-design/ant-design#35199]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gwgq3l?file=/demo.js)

### Steps to reproduce

1. 首先搜索框输入1之后
2. 再快速输入-1

### What is expected?

期望搜索出来的结果是 1-1

### What is actually happening?

搜索出来的结果是 1-

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
牛。 。 。这都能发现

**Comment by zombieJ** [comment]
看起来是 Tree 的 BUG，我看看。
