### ISSUE TITLE
Tree and TreeSelect styles

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3519]
all my nodes has children, but in case of leafs - it's only empty array.

Here is what i see for TreeSelect:
https://www.dropbox.com/s/hzj3uofj2f6i83v/Screenshot%202016-10-20%2015.42.36.png?dl=0

and here is what i see for Tree:
https://www.dropbox.com/s/pakw3tgpge3zodh/Screenshot%202016-10-20%2015.43.06.png?dl=0

Same data, differ controls. As you see at Tree every node has **arrow**, because of **children** property - not matter empty or not. In case of TreeSelect empty arrays are considered as leafs. I think it must be same.

**Comment by warmhug** [comment]
Taking into account the dynamic TreeNodes and you need to create TreeNode components yourself in the Tree Component. But in the TreeSelect, the Tree and TreeNodes aren't the most important and I have helped generate TreeNodes. So, I don't think this is a problem.

**Comment by plandem** [comment]
Hmmm!! never thought in that way! Consider as closed.

P.S.: would like to have default renderer or somehow to redefine renderer - like renderItem at Breadcrumb
