### ISSUE TITLE
Form.Item tooltip prop not working

### ISSUE THREAD

**Issue by roddc** [ant-design/ant-design#35198]
### Reproduction link

[https://stackblitz.com/edit/react-9k5dm7?file=demo.js](https://stackblitz.com/edit/react-9k5dm7?file=demo.js)

### Steps to reproduce

Pass a tooltip prop into Form.Item
Hover the Form.Item

### What is expected?

Tooltip should be displayed when hovering over the Input

### What is actually happening?

No tooltip displayed

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | Ubuntu |
| Browser | Chrome |

---
How do I use the tooltip prop with Form.Item?

**Comment by afc163** [comment]
<img width="382" alt="图片" src="https://user-images.githubusercontent.com/507615/164952583-f2d3129c-56a1-4d11-aa89-499435c69511.png">

It works.

**Comment by roddc** [comment]
> <img alt="图片" width="382" src="https://user-images.githubusercontent.com/507615/164952583-f2d3129c-56a1-4d11-aa89-499435c69511.png">
> 
> It works.

Oh, I thought it will add the tooltip on the Input field
