### ISSUE TITLE
Datapicker 组件问题

### ISSUE THREAD

**Issue by yinickzhou** [ant-design/ant-design#352]
如果是一个全屏app且滚动条不在body上面，当datapicker在页面最下端时，弹出的popup会撑开body破坏布局。 最理想的状态应该是popup和datepicker应该在同一dom层级上。

**Comment by yiminghe** [comment]
? 绝对定位了还会撑坏？

**Comment by yinickzhou** [comment]
谢谢关注。我放了几个图。
图1放在页面最下方放了一个datapicker组件。可以看到滚动条不在body上面，body上是设置了overflow:hidden的。当calendar浮层弹出时，是在body下增加了浮层节点，撑开了布局图2图3。

![1](https://cloud.githubusercontent.com/assets/12145505/10153578/498deed4-6690-11e5-8054-b8c7dbdf615b.png)
![2](https://cloud.githubusercontent.com/assets/12145505/10153529/bcd8b712-668f-11e5-870c-09cccb63f279.png)
![3](https://cloud.githubusercontent.com/assets/12145505/10153534/c4741c14-668f-11e5-8a64-7a7918a156c8.png)

如果内容滚动条不在body上，应该都会有这个问题。

**Comment by yiminghe** [comment]
will fix in 0.10

**Comment by afc163** [comment]
应该修复了？

**Comment by yiminghe** [comment]
1. 设置 getCalendarContainer 到 dialog 里面

2. 自动弹出方向调整(antd 不支持)
