### ISSUE TITLE
Select组件使用了rc-virtual-list这种虚拟滚动技术，但是如何自定义这里面下拉滚动条的样式呢

### ISSUE THREAD

**Issue by fssh** [ant-design/ant-design#35209]
### What problem does this feature solve?

需要能自定义Select组件中下拉滚动条的样式。

### What does the proposed API look like?

能否提供一些参数用来自定义滚动条。

**Comment by fssh** [comment]
该问题已解决，设置.rc-virtual-list-scrollbar和.rc-virtual-list-scrollbar-thumb的样式即可。

**Comment by HeWenKe** [comment]
鼠标不动，过几秒就没有滚动条了，客户觉得是bug，怎么设置。

**Comment by Bravo123** [comment]
> 鼠标不动，过几秒就没有滚动条了，客户觉得是bug，怎么设置。

+1 打算自己改样式了
