### ISSUE TITLE
Layout中的MENU显示不正常

### ISSUE THREAD

**Issue by gvcode1** [ant-design/ant-design#35200]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-chu-fa-qi-antd-4-20-0-alpha-1-forked-ovm4jt?file=/demo.js)

### Steps to reproduce

在LAYOUT示例中，选择4.19.5版本与react版本为17.0.2时，MENU不显示
![图片](https://user-images.githubusercontent.com/18253653/164953090-a34240b1-ad33-4d32-bb07-daf382e6c9f9.png)

### What is expected?

MENU可以显示

### What is actually happening?

MENU中的图标与文字不显示

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | Windows |
| Browser | Firefox |

---
请查看codesandbox中的链接，代码从官方示例中拷贝过来

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/35131

**Comment by afc163** [comment]
https://ant.design/components/menu-cn/#4.20.0-%E7%94%A8%E6%B3%95%E5%8D%87%E7%BA%A7

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/35202

**Comment by gvcode1** [comment]
已经解决，非常感谢 @afc163
