### ISSUE TITLE
table没有数据时会覆盖submenu

### ISSUE THREAD

**Issue by flyfinec** [ant-design/ant-design#3521]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: win10
- 浏览器及其版本: chrome

如图：
![image](https://cloud.githubusercontent.com/assets/3030186/19562127/bebe607c-970d-11e6-834e-0ba3b8bb3d53.png)

table没有数据时，会遮住submenu，从1.0到最新版一直有这个问题
随手查了一下，.ant-table-placeholder的z-index：2，submenu的z-index：2，可能是产生问题的原因

**Comment by afc163** [comment]
.ant-table-placeholder 应该尽可能调低。@ddcat1115

**Comment by ddcat1115** [comment]
placeholder 设置为2是为了避免被 fixed-columns 时的阴影贯穿，这里 menu 的z-index好像可以去掉？这样弹出来的 .ant-menu-submenu-horizontal 的『z-index: 1050』才可以生效

**Comment by afc163** [comment]
这么晚还在。。。

**Comment by afc163** [comment]
👌 那先去掉 submenu 的 `z-index: 2`
