### ISSUE TITLE
使用虚列表的组件卸载时概率性报错

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#35221]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/djt6vz)

### Steps to reproduce

使用带虚列表的组件操作，然后切换路由，卸载组件，概率性报错，不是 100%！

### What is expected?

不报错

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | React 18 |
| System | WIN11 |
| Browser | Chrome 100 |

![image](https://user-images.githubusercontent.com/1730277/165010666-9e1fc50d-4d0a-4c58-b9b2-2592a66315e7.png)

![image](https://user-images.githubusercontent.com/1730277/165010773-243b1ae0-9a47-4991-be16-3869370e55c3.png)

**Comment by afc163** [comment]
https://github.com/react-component/virtual-list/releases/tag/v3.4.7

Please remove yarn.lock and package-lock.json and reinstall node_modules.
