### ISSUE TITLE
tree-select组件如何获取到dropdown的dom结构？

### ISSUE THREAD

**Issue by Gaox2025f** [ant-design/ant-design#35224]
### What problem does this feature solve?

想在TreeSelect的Option上自定义一些属性

### What does the proposed API look like?

在dropdownRender的参数中，获取到整个dropdown的dom元素

**Comment by afc163** [comment]
不支持，不应该依赖 dom 结构。

**Comment by Gaox2025f** [comment]
@afc163 谢谢您，请问有其他的方式给TreeSelect.TreeNode加上自定义属性的吗。
