### ISSUE TITLE
Table 组件中，某列多行合并，在一次性加载的全部数据的情况下，分页后渲染错误。

### ISSUE THREAD

**Issue by Zexoius** [ant-design/ant-design#35228]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6h76k8?file=/index.js)

### Steps to reproduce

1. 请求数据，后端**一次性**返回所有数据；
2. 分组，并向**列配置**传入行配置；
3. 渲染完成；

### What is expected?

若组名残留在上一页，翻页后不应丢失组名所在列。

### What is actually happening?

翻页后，组名所在列丢失造成塌陷。

| Environment | Info |
| --- | --- |
| antd | 4.18.0 |
| React | ^17.0.0 |
| System | mac |
| Browser | Chrome |

**Comment by Zexoius** [comment]
如果是纯前端完成这块工作，个人觉得并不好整（能力有限。

**在生产环境中**，最好的方式是：需要后端给出相应的分页配置，减轻双方的负担（虽然后端仔每次不乐意。

**在测试环境中**，虚拟化列表，不分页，会是比较好的选择。

但是还是希望专业团队得出一个解决办法，毕竟我们野队才智有限（不是

**Comment by Zexoius** [comment]
> 

只是针对这种分组的需求啊！

**Comment by Asarua** [comment]
可以在塌陷的那一列前面，增加一列，里面只有个 { width: 0 }，实测可用
