### ISSUE TITLE
🐛 [BUG] Modal弹出层中 添加属性destroyOnClose后 初始化时调用modal内表单form.submit不生效

### ISSUE THREAD

**Issue by jianhuagao** [ant-design/ant-design#35227]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dan-chu-ceng-zhong-de-xin-jian-biao-dan-antd-4-20-0-forked-9sbu82?file=/demo.js)

### Steps to reproduce

在官方Modal示例 【弹出层中的新建表单】示例中 给modal添加destroyOnClose属性 然后在useEffect中调用form.submit无效

### What is expected?

在useEffect中可以触发表单提交

### What is actually happening?

不触发表单提交

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 18.0 |
| System | Windows10 |
| Browser | Microsoft Edge 100.0.1185.50 (正式版本) (64 位) |

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#%E4%B8%BA%E4%BD%95%E5%9C%A8-Modal-%E4%B8%AD%E8%B0%83%E7%94%A8-form-%E6%8E%A7%E5%88%B6%E5%8F%B0%E4%BC%9A%E6%8A%A5%E9%94%99%EF%BC%9F
