### ISSUE TITLE
There's no way to disable the animation for badges

### ISSUE THREAD

**Issue by kaiyoma** [ant-design/ant-design#35234]
### Reproduction link

[https://ant.design/components/badge/](https://ant.design/components/badge/)

### Steps to reproduce

Render a badge.

### What is expected?

There should be a way to disable the animation for the initial rendering, but there isn't.

### What is actually happening?

The animation always happens.

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome 100 |

---
There's an old issue about this (https://github.com/ant-design/ant-design/issues/21345) but the workarounds mentioned in that issue no longer work, even with `!important` applied. There should be an easy way to disable the animation via the API.

**Comment by afc163** [comment]
There is no intial animation when render Badges: https://codesandbox.io/s/ji-ben-antd-4-20-0-forked-01egfv?file=/demo.js

Is there something I miss?

**Comment by kaiyoma** [comment]
You can see the animation here: https://ant.design/components/badge/

In the "Standalone" example, click the switch on and off and you'll see the badge animate when it opens and closes.

**Comment by MadCcc** [comment]
It's by design.

**Comment by MadCcc** [comment]
@afc163 Should we provide prop to disable motion?

**Comment by afc163** [comment]
The workaroud works: https://codesandbox.io/s/standalone-antd-4-20-0-forked-qjx7m9?file=/demo.js

**Comment by afc163** [comment]
> @afc163 Should we provide prop to disable motion?

If there is no workaroud.

**Comment by kaiyoma** [comment]
> The workaroud works: https://codesandbox.io/s/standalone-antd-4-20-0-forked-qjx7m9?file=/demo.js

Nice, that CSS works for me.
