### ISSUE TITLE
The demo on the official website does not work for switching the shape of the avatar skeleton screen

### ISSUE THREAD

**Issue by pengpengzx** [ant-design/ant-design#35238]
### Reproduction link

[https://ant.design/components/skeleton-cn/](https://ant.design/components/skeleton-cn/)

### Steps to reproduce

1. 选择https://ant.design/components/skeleton-cn/
2. 选择 `动画效果`
3. 稍微往下滚动到 `按钮/头像/输入框/图像` 的部分
4. 在 `Avatar Shape` 字段切换 `Square` 和 `Circle`，不起作用
 

### What is expected?

在 `Avatar Shape` 字段切换 `Square` 和 `Circle`，起作用

### What is actually happening?

之前没有用过这里

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17 |
| System | macOS 12.1 |
| Browser | Chrome v100.0.4896.127 |

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/165212163-efe14beb-bb6a-42f3-b549-970944e55134.png)
有生效
