### ISSUE TITLE
Tabs里面的onEdit方法的参数类型推断错误

### ISSUE THREAD

**Issue by yanhcao** [ant-design/ant-design#35237]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cnr74w?file=/demo.js)

这个是代码链接，把typeof去掉，build即会报错

### Steps to reproduce

1. 项目开启ts
2. 使用支持编辑的Tabs，以及onEdit方法
3. onEdit方法中的两个参数(currentKey, action) 中的currentKey的类型推断会存在string和Event两种，其实只需要string一种
4. build报错
5. 除非增加cuurentKey的类型判断再使用

### What is expected?

currentKey可能为Event的数据格式吗？如果不是的话，类型推断是否可以只给成key对应的类型；

### What is actually happening?

currentKey的类型推断会存在string和Event两种

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | ^16.8.X |
| System | macOS 10.15.7 |
| Browser | chrome 100.X |

**Comment by yanhcao** [comment]
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
上文中有，是类型推断问题，所以必须到代码下面build去看

**Comment by afc163** [comment]
@yanhcao 请提供公网可重现方式。

**Comment by yanhcao** [comment]
> @yanhcao 请提供公网可重现方式。

描述中有啊

**Comment by Dreamcreative** [comment]
Tabs 的 onEdit 事件，在 type = 'editable-card' 时，action = ’add‘ 时，返回的是 (key, action), action = ’remove‘ 时，返回的是(event, action)，应该没什么问题吧，最多就是文档中描述不详细。

**Comment by yanhcao** [comment]
> Tabs 的 onEdit 事件，在 type = 'editable-card' 时，action = ’remove‘ 时，返回的是 (key, action), action = ’add‘ 时，返回的是(event, action)，应该没什么问题吧，最多就是文档中描述不详细。

对的，是不是第一个参数给一个类型限定更好一些，remove时第一个参数是string类型，因为remove时需要用到第一个参数，目前直接把第一个参数类型当作string｜Event时，外界使用onEdit时会有误导，而且也会build报错
不做参数类型限定的话外界使用时只能先做类型判断再使用了

**Comment by yanhcao** [comment]
> 
好的，我可以提pr

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/35271
