### ISSUE TITLE
Extra padding in Breadcrumb component

### ISSUE THREAD

**Issue by kejistan** [ant-design/ant-design#35233]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-h22lfd?file=/index.js)

### Steps to reproduce

Render a Breadcrumb component

### What is expected?

No leading padding (should match the design site)

### What is actually happening?

UA styles are leaking into the component on the new `ol` element. The existing css reset bundled in antd doesn't cover this.

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | React 17 |
| System | MacOS |
| Browser | Chrome 100, Safari 15.3 |

**Comment by TheHolyWaffle** [comment]
Especially noticeable when used in `PageHeader` 
![image](https://user-images.githubusercontent.com/787914/165161700-45d61dec-01bb-4e2c-a69c-8ad814226cd3.png)
