### ISSUE TITLE
RangePicker设置了format=“HH:mm”和默认时间以后，第一次点击后面的时间框，时间选择面板会出现在前一个时间框的下方

### ISSUE THREAD

**Issue by sakurayeah** [ant-design/ant-design#35247]
### Reproduction link

[https://riddle.alibaba-inc.com/riddles/cbf2005b](https://riddle.alibaba-inc.com/riddles/cbf2005b)

### Steps to reproduce

第一次进入时（仅第一次进入时能复现），鼠标点击第二个时间选择框，时间选择下拉菜单出现在第一个时间选择框下方，如图所示
<img width="953" alt="123123" src="https://user-images.githubusercontent.com/18390067/165243060-0c245570-af17-43da-8be6-f916fc36f53e.png">

### What is expected?

鼠标点击第二个时间选择框，时间选择下拉菜单出现在第二个时间选择框下方

### What is actually happening?

第一次进入时，鼠标点击第二个时间选择框，时间选择下拉菜单出现在第一个时间选择框下方

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.x |
| System | / |
| Browser | Chrome100.0.4896.75 |

**Comment by zhangyunihao** [comment]
这个问题修复了嘛？为什么关掉了？

**Comment by IMlixingwang** [comment]
额 我也遇到了类似的问题，一直没找到解决的办法，就用一个比较蠢的办法解决了 这个问题
![image](https://github.com/ant-design/ant-design/assets/31892121/0a0f89e8-e339-45d1-8c50-fd6aa6885745)

**Comment by IMlixingwang** [comment]
我最近也遇到这个bug了，在网上没找到答案，自己摸索了一下，打开控制台，发现失位的只是选择时间的.ant-picker-panel-container,.ant-picker-range-arrow(小箭头)并没有失位，就想着通过监听面板打开/关闭时的回调（onOpenChange）来解决这个问题，其中本来是想用setInterval，发现用它还是会有问题（第一次先点右边，再点左边，选择框不会跟过去），就用setInterval了。只是个临时解决bug的方案，希望对你们有用咯
![image](https://github.com/ant-design/ant-design/assets/31892121/e106d5c8-5a1e-4583-80b9-707ea92f7009)

**Comment by cooljser** [comment]
调试后发现v5版本已修复。v4.24.10版本仍存在，原因是点击"结束时间"后rc-picker设置右侧panel的marginLeft时，因未能获取到arrow的offsetWidth,所以panelLeft设置成了0
@afc163 v4版本是否需要修复，需要的话，我提个pr

**Comment by yoyo837** [comment]
欢迎PR

**Comment by cooljser** [comment]
v4.x版本临时解决方案
```css
.ant-picker-range-arrow {
  display: block!important;
}
```

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/43179
