### ISSUE TITLE
Style of InputNumber in Input.Group compact mode is broken.

### ISSUE THREAD

**Issue by fix777** [ant-design/ant-design#35249]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inputnumber-style-bug-under-inputgroup-under-feedback-enabled-form-cxgijx?file=/demo.js)

### Steps to reproduce

See [demo](https://codesandbox.io/s/inputnumber-style-bug-under-inputgroup-under-feedback-enabled-form-cxgijx?file=/demo.js)

### What is expected?

The `<InputNumber />` wrapper div displayed as `inline-flex`

### What is actually happening?

The `<InputNumber />` wrapper div displayed as `inline-block`, so the style is broken.

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17.0.2 |
| System | Pop!_OS 22.04 LTS |
| Browser | MS Edge 100.0.1185.50 |

**Comment by xccjk** [comment]
The problem is mainly due to the **hasFeedback** property of **Form.Item**

demo: [https://codesandbox.io/s/inputnumber-style-bug-under-inputgroup-under-feedback-enabled-form-forked-1kj6ll?file=/demo.js](https://codesandbox.io/s/inputnumber-style-bug-under-inputgroup-under-feedback-enabled-form-forked-1kj6ll?file=/demo.js)

**Comment by xccjk** [comment]
When Form.Item has hasFeedback set, the style itself is also overridden when used with InputNumber. If this coverage is by design, I can provide pr
![w2](https://user-images.githubusercontent.com/21093699/182098492-9fbe7efb-ba2e-4831-996d-9281d4539603.jpg)

**Comment by afc163** [comment]
Introduced by this code: https://github.com/ant-design/ant-design/commit/d1f87ccc8080662150e582908ee61184b060ad82#diff-1b69896b627e11b980961d22f84c248986230123b13d63fe837714bc1db819edR47-R51
