### ISSUE TITLE
How to get the DateType type?

### ISSUE THREAD

**Issue by oodzchen** [ant-design/ant-design#35240]
### What problem does this feature solve?

When use `DatePicker` component, I need to define the `onChange` function's parameter type, but I can't get the type which named `DateType`. I can't import it neither from `antd` nor `rc-picker`.

I've see the[ documentation](https://ant.design/components/date-picker-cn/#DatePicker), which shows the first parameter of `onChange` is `moment`, but when I click it in VS Code, it shows `DateType | null`, I was confused, how could I get the parameter type in a right way?

![image](https://user-images.githubusercontent.com/9650699/165215280-35240576-61c8-44ba-9d15-ccdf05075b87.png)

### What does the proposed API look like?

```typescript
import { DateType } from 'antd'
```

**Comment by MadCcc** [comment]
```tsx
const handleChange: DatePickerProps['onChange'] = () => {}
```

**Comment by webbiffy** [comment]
I've passed **Moment** type instead of DateType and it's working on my end.
