### ISSUE TITLE
DatePicker中的面板时间(pickerValue)怎么改变?不是默认

### ISSUE THREAD

**Issue by cheng-xiaofeng** [ant-design/ant-design#35254]
### What problem does this feature solve?

如果选择时间是2044年, 点击x清空时间后,面板的时间还是2044年
![image](https://user-images.githubusercontent.com/33592850/165288253-ba5150de-0258-47de-a06f-80df0a07606d.png)
![image](https://user-images.githubusercontent.com/33592850/165288334-31344f7b-3431-4905-b0d4-fb58712b865e.png)

![image](https://user-images.githubusercontent.com/33592850/165288384-12936277-212e-4b71-a563-8598f1ecda72.png)

### What does the proposed API look like?

点击x后, 面板的时间恢复到当前时间

**Comment by afc163** [comment]
We might need a `pickerValue` to control state of panel. Trace https://github.com/ant-design/ant-design/issues/34404#issuecomment-1063724391
