### ISSUE TITLE
Menu组件水平方向收起之后，再水平方向展开，怎么使选中的菜单项的父菜单也是展开的状态？defaultOpenKeys无效的，求解决

### ISSUE THREAD

**Issue by zlh314159** [ant-design/ant-design#3525]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:win7旗舰版
- 浏览器及其版本:谷歌 版本 52.0.2743.116 (64-bit)
#### 您做了什么？

使用了antd的Menu组件实现可收起展开的侧边导航栏

#### 您期待的结果是：

step1：当首次进入页面时，侧边栏是水平展开的状态，根据地址栏上的url来匹配相对应的导航菜单，如果匹配成功，则将选中的菜单项高亮，其父菜单垂直展开，利用defaultOpenKeys={[xx]}可以实现该效果；
step2：和官网提供的一样，当点击导航栏底部的按钮时，导航栏收起；
step3：当再次点击导航栏底部的按钮时，导航栏是水平展开状态，选中的菜单确实高亮，我希望的是此时该高亮的菜单项的父菜单是垂直展开状态。
#### 实际上的结果是：

step3中的选中的菜单确实是高亮的，但是对应的父菜单不是垂直展开状态。
导航栏水平收起之后再展开，怎么使选中的菜单项的父菜单也是展开的状态，求大神解决，非常感谢！

**Comment by afc163** [comment]
通过 openKeys 进行精确控制。

**Comment by zlh314159** [comment]
antd的官网中的Menu导航菜单下的“切换菜单类型”例子，当我们展开多个一级目录的菜单时，点击切换按钮，再次切换到垂直方向展开的时候，所有的一级目录都是垂直方向折叠的，可以接受；但是我希望的是当我只展开一个一级目录的时候，点击切换按钮，再次切换到垂直方向展开的时候，能保持之前展开的那个一级目录的状态

**Comment by yt1520406335** [comment]
是的,感觉2.0.1版本的onOpenChange的方法看不懂,旧版的onClose 和 onOpen好用;还是官方文档的例子.....

**Comment by afc163** [comment]
使用 openKeys 把 Menu 变成受控组件，状态自行掌控。
