### ISSUE TITLE
Feature: support importing css on demand even if we use the CSS variable version.

### ISSUE THREAD

**Issue by TrickyPi** [ant-design/ant-design#35259]
### Reproduction link

[https://github.com/TrickyPi/issue-repo](https://github.com/TrickyPi/issue-repo)

### Steps to reproduce

1. git clone -b antd-variable https://github.com/TrickyPi/issue-repo && cd issue-repo
2. pnpm i
3. pnpm build
4. 看到最后的css产物，发现一些全局的style并没有使用css variable。
<img width="520" alt="error" src="https://user-images.githubusercontent.com/33021497/165321403-641751dd-48c8-4009-8d2b-7967ec9261da.png">

5. 修改node_modules/antd/es/style/default.less文件

```less
@root-entry-name: default;
@import './index-pure.less';
```

6. pnpm build 
7. 看到最后的css产物，发现一些全局的style使用了css variable。
<img width="520" alt="right" src="https://user-images.githubusercontent.com/33021497/165321450-1f729bc5-3061-437a-8660-ed33e3ef33d9.png">

### What is expected?

支持动态导入组件的样式（支持使用babel-import-plugin），可以减少最后包的体积

### What is actually happening?

官网的例子中，只有全局css文件引入，参考链接：https://ant.design/docs/react/customize-theme-variable#header

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 18.0.0 |
| System | unrelated |
| Browser | unrelated |

---

我在想，官网上没有提供按需引入的文档，是不是这个问题，如果是这个问题的话，
我觉得我们是否可以修改相关的gulp打包配置([.antd-tools.config.js](https://github.com/ant-design/ant-design/blob/master/.antd-tools.config.js))，在打包es或lib目录时，处理一下`es/style/default.less`文件。

出现第4个步骤的原因，是less-loader内配置的@root-entry-name影响不到`es/style/default.less`文件其后续导入的`es/style/themes/index.less`文件内的动态引入`@import './@{root-entry-name}.less`，这里的`@root-entry-name`的值其实一直都是`es/style/index.less`文件下`@root-entry-name: default`设置的值（`default`），

相关引用顺序
`es/style/default.less` -> `es/style/index.less` -> `es/style/index-pure.less` -> `es/style/themes/index.less`

**Comment by afc163** [comment]
Is it https://github.com/ant-design/ant-design/pull/34602/ helpful?

**Comment by TrickyPi** [comment]
跟这个issue不太一样。

假如less-loader配的@root-entry-name是variable，理想的情况下，应该是不会引用`es/style/themes/default.less`, 但是目前在打包阶段是引用了这个文件，所以造成全局样式（比如：`es/style/core/global.less`）的less变量受到了该文件的影响。

其他信息：
需要定制暗黑主题的时候，文档上写的方案是把所有dark的less变量配置在less-loader里，不能直接配置@root-entry-name为dark，感觉跟css variable版本是相同的问题（第4个步骤的原因）。

**Comment by afc163** [comment]
css variable 版本不会再深入改造了，我们会迁移到 CSS in JS 方案上：https://github.com/ant-design/ant-design/issues/34087

**Comment by TrickyPi** [comment]
感谢回复！dark主题或compact主题，也会迁移到CSS in JS方案上吗？

**Comment by afc163** [comment]
会。
