### ISSUE TITLE
antd的table组件，如何实现tr上右键功能，onContextMenu直接加了不起作用。

### ISSUE THREAD

**Issue by jeffycai** [ant-design/ant-design#3526]
#### 发生问题的环境是：antd 2.1.0

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by GrayChoi** [comment]
Table组件的暂时还不支持tr的onContextMenu事件。

**Comment by afc163** [comment]
自行添加加到 column.render 里。

**Comment by jeffycai** [comment]
@afc163 在column.render里无法拿到this对象。需要知道当前的tr对象。

**Comment by afc163** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by qivhou** [comment]
是否可以在rc-table中加上这个方法呢?
rc-table现在的Row支持Click和DoubleClick，是否也可以支持ContextMenu？

**Comment by chj-damon** [comment]
下一个版本有计算实现这个功能吗？复杂的table操作对右键菜单还是有很大需求的。
