### ISSUE TITLE
表格列表不能调整宽度

### ISSUE THREAD

**Issue by luofff** [ant-design/ant-design#35266]
### What problem does this feature solve?

表格数字有回行

### What does the proposed API look like?

表格列表能调整宽度

![image](https://user-images.githubusercontent.com/22536205/165433467-0bc484a0-49db-428f-92d0-d49dd2279214.png)

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/26413#issuecomment-802563939
