### ISSUE TITLE
[Feature Request] Children render props miss `onChange` when has `dependenices`. 

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#35276]
### What problem does this feature solve?

If I want to custom a form component, at now, I can create it and put it into the `Form.Item`. Just like

```
const CustomFormComponent = ({ onChange }) => ...

<Form.Item ...><CustomFormComponent /></Form.Item>
```

But if the `CustomFormComponent` need some other forms value, I need to set the `dependencies` prop.

```
<Form.Item name="bar" label="bar" dependencies={ ["foo"]} >
  <CustomFormComponent t="t1" />
</Form.Item>
```

But this is not work, because `CustomFormComponent` **won't re-render when `foo` updates**.

You need to do this:

```
<Form.Item label="bar" dependencies={ ["foo"]} >
  { () => <CustomFormComponent t="t1" /> }
</Form.Item>
```

But if you use Children of render props like this, the `CustomFormComponent` will not receive the `onChange` prop, **I know that's because there is `name` prop on Form.Item because it's not a valid usage**.

But if I want to store the value of  `CustomFormComponent` into the `form`, and trigger the `onValuesChange` when `CustomFormComponent` updates its value(Because it's a custom **form** component, so sure its value should be stored in the form). 

How could I do that?

### What does the proposed API look like?

I don't know for now.

**Comment by afc163** [comment]
If you need to report a bug, please using bug-report template instead of feature-request template.

**Comment by NE-SmallTown** [comment]
@afc163   这不是个 bug。。如果要解决这个问题需要一个新的 API 机制，和 bug 无关

**Comment by afc163** [comment]
> But this is not work, because CustomFormComponent won't re-render when foo updates.

> But if you use Children of render props like this, the CustomFormComponent will not receive the onChange prop, I know that's because there is noname prop on Form.Item because it's not a valid usage.

先确认这两个是不是 bug 吧。

**Comment by NE-SmallTown** [comment]
@afc163   确认了，不是，我补上 codesandbox 链接了（昨天写了提 issue 就忘了。。），你可以看下

> But this is not work, because CustomFormComponent won't re-render when foo updates.

因为这里传给 `Form.Item` 的是一个 element，所以 `Form.Item` 组件里面觉得 dep 变了我需要 re-render 的时候并不会导致 children 变化（children 的那个 element 的引用是没变化的）

> But if you use Children of render props like this, the CustomFormComponent will not receive the onChange prop, I know that's because there is noname prop on Form.Item because it's not a valid usage.

这个也不是，issue 里说了，就没法传 `onChange` 给自定义的 form 组件，因为 onChange 本身就是触发表单的值更新把新值往 form 内部的 fields 里面塞的，但是这里（render props + deps 的场景）根本就没有（也不 能/该 传） name

**Comment by afc163** [comment]
Reviewed against the latest `master` (`0b1021909f`). A Form.Item cannot simultaneously use the named control-injection and render-prop contracts.

Latest Form supports this composition by nesting a noStyle named Form.Item inside a dependencies or shouldUpdate render-prop item; injecting onChange without a field name is intentionally undefined.

Closing this issue accordingly. If a minimal reproduction still demonstrates different behavior on the current `master`, please open a new issue with that reproduction.
