### ISSUE TITLE
When Dropdown and Button are used together, the Select component in the Dropdown menu will be closed instantly after clicking.

### ISSUE THREAD

**Issue by KynoYang** [ant-design/ant-design#35275]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-shtern-t93v08)

### Steps to reproduce

1. open the link https://codesandbox.io/s/keen-shtern-t93v08
2. click the Button to show the Dropdown menu
3. click the Select in the menu

### What is expected?

The dropdown menu of the Select component works well

### What is actually happening?

The dropdown menu of the Select component is closed after clicking

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | macOs 11.4 |
| Browser | Chrome Version 100.0.4896.127  |

**Comment by afc163** [comment]
Don't put Select inside Menu.Item. Try https://codesandbox.io/s/strange-lamarr-vnwj2e?file=/src/App.js if you insist.

**Comment by KynoYang** [comment]
Thank you @afc163. One more question:
If you replace the `Button` with `a` or `div`, it works well. And if you use the antd version prior to 4.17.0, it works well too.
Don't you think it's a bug?

**Comment by afc163** [comment]
Oh, it is same problem as https://github.com/ant-design/ant-design/issues/34532, we fixed in https://github.com/react-component/dropdown/releases/tag/v3.5.2

Please remove lock files and reinstall node_modules in your machine then try again.
