### ISSUE TITLE
4.20.1 react 18 依然出现dropdown点了之后卡死tab的问题

### ISSUE THREAD

**Issue by luokebi** [ant-design/ant-design#35282]
### Reproduction link

[https://ant.design/components/dropdown-cn/](https://ant.design/components/dropdown-cn/)

### Steps to reproduce

暂无，暂时只在我的项目里重现，还没有找出规律。其中一种是刷新页面当tab图标还在loading状态（页面已经出现），点击dropdown, 这时比较容易出现。另，我的项目中页面完全加载后，没有loading，点击可能会出现. 还有一个现象，development 模式下比较容易出现，production也可以，但不是那么容易。 Menu用的Menu.Item写法

### What is expected?

打开dropdown

### What is actually happening?

未打开，tab卡死，tab cpu很高

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 18.1.0 |
| System | Macos 12.3.1 |
| Browser | Chrome 101.0.4951.41  |

**Comment by chinfeng** [comment]
+1

100% cpu占用率，似乎在不停的计算 scroll 坐标

**Comment by luokebi** [comment]
> +1
> 
> 100% cpu占用率，似乎在不停的计算 scroll 坐标

@chinfeng 你有简单例子复现吗？我没法用简单例子复现，只能在我的大项目里复现

**Comment by luokebi** [comment]
[Profile-20220428T172030.json.zip](https://github.com/ant-design/ant-design/files/8581454/Profile-20220428T172030.json.zip)

提供一个出现时的profile，看看有没有什么线索

**Comment by cx-emerge** [comment]
```javascript
// ======================== Aligns ========================

var prepareResolveRef = (0,
react__WEBPACK_IMPORTED_MODULE_3__.useRef)();
// `target` on `rc-align` can accept as a function to get the bind element or a point.
// ref: https://www.npmjs.com/package/rc-align

function getAlignTarget() {
    if (point) {
        return point;
    }

    return getRootDomNode;
}

function forceAlign() {
    var _alignRef$current;

    (_alignRef$current = alignRef.current) === null || _alignRef$current === void 0 ? void 0 : _alignRef$current.forceAlign();
}

function onInternalAlign(popupDomNode, matchAlign) {
    var nextAlignedClassName = getClassNameFromAlign(matchAlign);

    if (alignedClassName !== nextAlignedClassName) {
        setAlignedClassName(nextAlignedClassName);
    }

    if (status === 'align') {
        // Repeat until not more align needed
        if (alignedClassName !== nextAlignedClassName) {
            Promise.resolve().then(function() {
                forceAlign();
            });
        } else {
            goNextStatus(function() {
                var _prepareResolveRef$cu;

                (_prepareResolveRef$cu = prepareResolveRef.current) === null || _prepareResolveRef$cu === void 0 ? void 0 : _prepareResolveRef$cu.call(prepareResolveRef);
            });
        }

        onAlign === null || onAlign === void 0 ? void 0 : onAlign(popupDomNode, matchAlign);
    }
}
```

可能是卡在 `rc-align` 组件 `forceAlign` 函数无线循环计算上

**Comment by krailler** [comment]
+1

Same here with this issue

**Comment by krailler** [comment]
I upgrade rc-align to the latest version, and it works

**Comment by mengbo-ji** [comment]
我也是鼠标放到 Dropdown.Button 就卡死 tab也不会出现 
![image](https://user-images.githubusercontent.com/54396390/167576360-f7944234-a649-40f7-895a-2b6ff61d3c4e.png)

**Comment by mengbo-ji** [comment]
搞了一下午，也没复现，干~ Dropdown.Button卡死的问题

**Comment by mengbo-ji** [comment]
搞了一下午，还是没搞懂Dropdown.Button卡死的问题。

**Comment by mengbo-ji** [comment]
我也出现了卡死的情况
我的处理流程：删除node_modules 和 package-lock.json。
重新：npm install 
结果：就OK了~

> > +1
> > 100% cpu占用率，似乎在不停的计算 scroll 坐标
> 
> @chinfeng 你有简单例子复现吗？我没法用简单例子复现，只能在我的大项目里复现

我也出现了卡死的情况
我的处理流程：删除node_modules 和 package-lock.json。
重新：npm install 
结果：就OK了~

**Comment by mengbo-ji** [comment]
@chinfeng 
我也出现了卡死的情况
我的处理流程：删除node_modules 和 package-lock.json。
重新：npm install 
结果：就OK了~

**Comment by mengbo-ji** [comment]
> 

@chinfeng 
  我也出现了卡死的情况
  我的处理流程：删除node_modules 和 package-lock.json。
  重新：npm install 
  结果：就OK了~

**Comment by cx-emerge** [comment]
可以更新 rc-* 依赖到最新版本
```sh
yarn up 'rc-*' -R
```

**Comment by chenxiaochun** [comment]
如果执行`yarn up`无效。可以执行`yarn upgrade antd`，执行完毕之后，可以看一下`node_modules/rc-align/package.json`是否为最新版本。如果是最新版本，就没问题了

**Comment by zdJOJO** [comment]
> rc-align

老哥， 有啥解决方案吗？

**Comment by chenxiaochun** [comment]
今天在另外一个项目，又遇到了同样问题。就是用我上面提供的方法啊，肯定有效

**Comment by lu-sagar** [comment]
I was pulling my hair after upgrading my app to react 18 as my storybook tests were freezing randomly in CI in prod build. I was using Antd v4. This thread saved me. Overriding the rc packages fixed it for me.
`"overrides": {
    "rc-tooltip": "5.3.1",
    "rc-picker": "2.6.9",
    "rc-trigger": "5.3.4"
  },`
