### ISSUE TITLE
Menu导航菜单如何每一级都能触发click？

### ISSUE THREAD

**Issue by wangyun122** [ant-design/ant-design#35288]
### What problem does this feature solve?
[https://codepen.io/wangyun122/pen/ZEvgojw?editors=0010](url)
click事件只有在叶节点的时候才会触发，期望可以在点击每一层菜单的时候都能触发。

### What does the proposed API look like?

希望有个属性来设置menu的click事件能否在每个节点都触发。

**Comment by afc163** [comment]
无计划支持，SubMenu 目前在交互上设计为展开/收起，不响应 Menu 的选择和点击事件。如需单独监听可在 Submenu 子元素内自行绑定事件 https://codepen.io/afc163/pen/KKZOePJ?editors=0011
