### ISSUE TITLE
antd的官网的Menu导航菜单之“切换菜单类型”的例子能否改进下？

### ISSUE THREAD

**Issue by zlh314159** [ant-design/ant-design#3528]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

#### 您期待的结果是：

当展开多个一级目录的菜单时，点击切换按钮，再次切换到垂直方向展开的时候，所有的一级目录都是垂直方向折叠的；
当只展开一个一级目录的时候，点击切换按钮，再次切换到垂直方向展开的时候，能保持之前展开的那个一级目录的状态

#### 实际上的结果是：

当我们展开多个一级目录的菜单时，点击切换按钮，再次切换到垂直方向展开的时候，所有的一级目录都是垂直方向折叠的

**Comment by afc163** [comment]
不要重复提 issue：https://github.com/ant-design/ant-design/issues/3525
