### ISSUE TITLE
日历组件header能否支持取消 onSelect 回调的触发

### ISSUE THREAD

**Issue by l1shu** [ant-design/ant-design#35280]
我只想选择日期的时候会触发 onSelect，但是头部切换的时候也会触发 onSelect，这似乎并不合理

<img width="828" alt="image" src="https://user-images.githubusercontent.com/48285873/165525270-adb67b25-fdea-4809-83b0-7ba94cb1535a.png">

**Comment by l1shu** [comment]
我想做的效果是点击日期后隐藏日历组件

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28046#issuecomment-759176541
