### ISSUE TITLE
Form.Item 的 shouldUpdate 函数返回false 不会中断更新，造成死循环

### ISSUE THREAD

**Issue by vinson-bs** [ant-design/ant-design#35286]
### Reproduction link

[https://无](https://无)

### Steps to reproduce

<Form.Item key = 'SelectChild-noStyle' noStyle 
			shouldUpdate={ (prevValues, curValues) => {
                                   return false;
				// return prevValues['Select'] != curValues['Select'] 
			}
		}>
{组件内容更新代码片段}
</Form.Item>

### What is expected?

shouldUpdate 返回 false 时不更新组件；即不执行 组件内容更新代码片段

### What is actually happening?

shouldUpdate 返回 false 时；执行了 组件内容更新代码片段

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 16.14.0 |
| System | macOS Monterey 12.2 |
| Browser | Chrome |

<!-- generated by ant-design-issue-helper. DO NOT REMOVE --
[antd-reproduction-template-forked.zip](https://github.com/ant-design/ant-design/files/8579630/antd-reproduction-template-forked.zip)
>

**Comment by vinson-bs** [comment]
[antd-reproduction-template-forked.zip](https://github.com/ant-design/ant-design/files/8579626/antd-reproduction-template-forked.zip)
重现代码见附件

**Comment by vinson-bs** [comment]
> Hello @vinson-bs. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @vinson-bs, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
[Uploading antd-reproduction-template-forked.zip…]()

**Comment by vinson-bs** [comment]
> Hello @vinson-bs. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @vinson-bs, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

@github-actions
在线实例：
https://codesandbox.io/s/antd-form-item-shouldupdate-9jtbev

**Comment by sklinov** [comment]
I'm experiencing this too now @afc163 
When `shouldUpdate` used as a function and returns straight `false` value, still it executes everything enclosed as child an causes a loop in rendering.

**Comment by Ruegen** [comment]
Same here, we are experience the same bug even though we are returning false in the shouldUpdate

**Comment by MistChen** [comment]
把 setFieldsValue() 从 render props 里移到 shouldUpdate 中可以解决这个问题

https://codesandbox.io/s/antd-form-item-shouldupdate-forked-2237pk?file=/src/testFormItem.js

**Comment by cao-lianhui** [comment]
xdm，咋解决的
