### ISSUE TITLE
Fixed `<Table/>` header issue with scroll prop `x: 'max-content'`

### ISSUE THREAD

**Issue by nichita-pasecinic** [ant-design/ant-design#35284]
### Reproduction link

[https://stackblitz.com/edit/react-9m9qvl?file=demo.js](https://stackblitz.com/edit/react-9m9qvl?file=demo.js)

### Steps to reproduce

If `data={[]}` is empty then the header alignments are all broken and `width` property does not help as suggested per `antd` documentation

### What is expected?

To apply the `width` value on headers when `data` is empty array as well as it is applied when `data` is not empty

### What is actually happening?

Currently table headers styles are messed up and `width` value is not being applied per column

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.0.2 |
| System | Windows 10 pro |
| Browser | Chrome 100 |

```jsx
<Table
      tableLayout="fixed"
      scroll={{
        x: 'max-content',
        y: `300px`,
      }}
      columns={columns}
      dataSource={[]} // the table looks ok with non-empty data
    />
```

**Comment by afc163** [comment]
https://github.com/react-component/table/pull/595

**Comment by nichita-pasecinic** [comment]
@afc163 Thx for references, but aren't both of the above PRs already merged ?
Or there is still something left to do on your side ?

**Comment by afc163** [comment]
Just leave some related changes to me.

**Comment by afc163** [comment]
You should set width to all columns when using `scroll={{ x: 'max-content' }}`, otherwise the columns without width will shrink to one line: https://stackblitz.com/edit/react-9m9qvl-u4qohn?file=demo.js
