### ISSUE TITLE
js聚焦Textarea时会自动添加换行

### ISSUE THREAD

**Issue by furan495** [ant-design/ant-design#35287]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-3075f5?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

上方的文本域回车

### What is expected?

下方文本域聚焦，同时光标在首行

### What is actually happening?

光标没在首行

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.x |
| System | mac |
| Browser | 谷歌最新版 |

**Comment by MadCcc** [comment]
正常行为，onPressEnter 也是通过 onKeydown 实现的，换成两个原生 textarea 也是同样的行为

**Comment by afc163** [comment]
https://codesandbox.io/embed/antd-reproduction-template-forked-3075f5?fontsize=14&hidenavigation=1&theme=dark
