### ISSUE TITLE
最新版本4.20.1 Dropdown 支持方向键切换选项不生效

### ISSUE THREAD

**Issue by wuzhenji** [ant-design/ant-design#35298]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dan-chu-wei-zhi-antd-4-20-0-alpha-1-forked-i4pwl3?file=/package.json:504-536)

### Steps to reproduce

点击Dropdown 

### What is expected?

点击Dropdown 支持方向键切换选项生效

### What is actually happening?

点击Dropdown 支持方向键切换选项不生效

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome100 |

**Comment by MadCcc** [comment]
为了兼容一些可 focus 的 trigger，默认行为改成了需要按 tab 之后 focus menu。

**Comment by wuzhenji** [comment]
啥意思，怎么才能生效？

**Comment by MadCcc** [comment]
会提供 autoFocus 属性，跳过 tab 直接 focus menu

**Comment by wuzhenji** [comment]
意思就是暂时用不了？

**Comment by MadCcc** [comment]
可以用，多按一次 tab 键之后会 focus 到 menu 上。

**Comment by wuzhenji** [comment]
手动foucs解决问题
