### ISSUE TITLE
RangePicker 国际化设置中文 月份依旧无效

### ISSUE THREAD

**Issue by wywsoor** [ant-design/ant-design#35294]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kpm0ge?file=/demo.js)

### Steps to reproduce

import React from 'react';
import 'antd/dist/antd.css';
import './index.css';
import { DatePicker, Space,ConfigProvider } from 'antd';
import zhCn from 'antd/es/locale/zh_CN';

const { RangePicker } = DatePicker;

export default () => (
  <Space direction="vertical" size={12}>
   
    <ConfigProvider locale={zhCn}>
                        <RangePicker locale={zhCn} picker="month" />
                    </ConfigProvider>

  </Space>
);

### What is expected?

中文展示

### What is actually happening?

英文月份

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 18 |
| System | mac |
| Browser | Chrome |

**Comment by wywsoor** [comment]
@afc163

**Comment by wywsoor** [comment]
造成这个原因的问题是 cnpm 安装包导致重新使用npm 安装即可

**Comment by wywsoor** [comment]
@afc163  我使用在线实例无法复现，因为造成这个错误的原因是 cnpm 包的原因（我认为是这个原因，因为使用npm 安装了 4.19.0版本就没有问题了）

**Comment by wywsoor** [comment]
复现代码 
<ConfigProvider locale={zhCN}>
     <RangePicker locale={zhCN} picker="month" />
</ConfigProvider>

**Comment by wywsoor** [comment]
< ConfigProvider locale={zhCn}>
                    < RangePicker locale={zhCn} picker="month" />
               </ ConfigProvider>

**Comment by afc163** [comment]
一般是有两个 moment 版本同时存在的问题。
