### ISSUE TITLE
Modal.confirm属性okButtonProps中的loading无效

### ISSUE THREAD

**Issue by mtiger95** [ant-design/ant-design#35293]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2k51ns?file=/src/App.js)

### Steps to reproduce

点击确认按钮

### What is expected?

确认按钮点击后有异步操作，希望有loading

### What is actually happening?

按钮无loading

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | antd4.2 |
| Browser | chrome |

**Comment by afc163** [comment]
看看 https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux%E3%80%81%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F

静态方法没法接收 React state 状态。

**Comment by mtiger95** [comment]
> ### You may look for issues:
> 1. 51% [Modal.method中onOkProps配置loading属性无效 #29747](https://github.com/ant-design/ant-design/issues/29747)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

那边那个已经被关闭了，请解决下这里的这个问题吧

**Comment by mtiger95** [comment]
两边issue都没处理就都关闭？

**Comment by mtiger95** [comment]
我知道如何解决了，函数式调用Modal.method，需要拿到modal实例，调用 modalInstance.update({okButtonProps: {loading: true},})，异步逻辑执行完后，再次update将loading更新为false即可。

**Comment by afc163** [comment]
@mtiger95 可以试试我上面文档提供的方式。
