### ISSUE TITLE
The subtree is not displayed when the table is expanded!

### ISSUE THREAD

**Issue by QiuhuaLi** [ant-design/ant-design#35299]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-zhan-kai-antd-4-20-1-forked-bmj79m?file=/demo.js)

### Steps to reproduce

click  
the row is shown displayed
The subtree is not displayed

### What is expected?

The subtree can show 

### What is actually happening?

The subtree is not displayed

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | 18.1.0 |
| System | none |
| Browser | noen |

---
subtree can be displayed normally when I select the version below 4.17.0

**Comment by afc163** [comment]
`rowKey` should return unique and string type.
