### ISSUE TITLE
表单输入值后，界面一直报错

### ISSUE THREAD

**Issue by Zhongxiangyun** [ant-design/ant-design#3529]
#### 发生问题的环境是：

-react版本：15.3
- antd 版本:2.1
- 操作系统及其版本:win10 
- 浏览器及其版本:谷歌53  火狐49

#### 您做了什么？

动态生成表单界面

#### 您期待的结果是：

表单界面正常，可以正常的填写内容

#### 实际上的结果是：
表单里面 一旦某个值一输入后控制台报错：然后无法通过
const value = this.props.form.getFieldsValue();该方法获取那个报错了的输入值
TypeError: fieldMeta is undefined
var validate = fieldMeta.validate;

#### 可重现的在线演示

可以联系本人，找时间远程演示

**Comment by afc163** [comment]
推荐异步交流，没有精力去联系人的。烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
应该是这个问题：https://github.com/ant-design/ant-design/issues/2591

https://ant.design/components/form/#%E7%89%B9%E5%88%AB%E6%B3%A8%E6%84%8F

**Comment by Zhongxiangyun** [comment]
还请谅解，由于框架体系比较大，搭建一个demo展示暂时实现不了，用语言描述一下，第一点先排除使用的是 react@<15.3.0，则 getFieldDecorator 调用不能位于纯函数组件中，没有在纯函数中调用这个；第二点就是由于有了onChange 这个监听，当我输入值后，控制台就会报错：
TypeError: fieldMeta is undefined
var validate = fieldMeta.validate;

对应编译的代码
 onChange: function onChange(name_, action) {
	        var name = name_;
	        var fieldMeta = this.getFieldMeta(name);
	        var validate = fieldMeta.validate;
这里有问题就是 动态生成的表单中有一个字段中没有name的属性，感觉越描述越凌乱了！

**Comment by benjycui** [comment]
动态生成表单域参考下这个例子？ https://ant.design/components/form/#components-form-demo-dynamic-form-item
