### ISSUE TITLE
antd4的时间选择组件的RangePicker 能否提供一个属性ifInorder属性

### ISSUE THREAD

**Issue by xiaoshan100** [ant-design/ant-design#35295]
### What problem does this feature solve?

我有时候选择时间区间的时候  会忽略我当前选中的是开始时间和结束时间，一般都是先选开始再选结束的逻辑，能否跟antd3一样去除里面select的当前选择状态，默认在选择时间区间的时候，都是先选开始时间再选结束时间

### What does the proposed API look like?

ifInorder=true
代表跟antd3的时间选择一样的交互，不需要区分目前是选择的是开始时间还是结束时间

**Comment by afc163** [comment]
交互不会回到老版本了。
