### ISSUE TITLE
Cascader  displayRender 在 4.19.5 中报错

### ISSUE THREAD

**Issue by hlsky1988** [ant-design/ant-design#35291]
### Reproduction link

[https://github.com/hlsky1988/ant-displayRender](https://github.com/hlsky1988/ant-displayRender)

### Steps to reproduce

运行demo 打开F12

### What is expected?

无报错

### What is actually happening?

Warning: [antd: Cascader] `displayRender` not work on `multiple`. Please use `tagRender` instead. 

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17 |
| System | MacOS 11.6.1 |
| Browser | Chrome 100.0.4896.127 |

---
在 文档 https://ant.design/components/cascader-cn/ 中显示 Cascader multiple displayRender 在 4.18.0 版本已经支持, 但是在 4.19.5 中仍有报错信息, 目前功能正常, 希望修复或者确认这个报错

**Comment by hlsky1988** [comment]
在 ant 4.20.1 有相同的报错信息

**Comment by kanweiwei** [comment]
https://codesandbox.io/s/adoring-faraday-xbco4x?file=/src/App.js

**Comment by lalalazero** [comment]
https://github.com/ant-design/ant-design/pull/34116

**Comment by crazyair** [comment]
目前 4.24.8 还有错误 https://stackblitz.com/edit/react-k5atx3?file=demo.tsx
