### ISSUE TITLE
空格规范问题

### ISSUE THREAD

**Issue by amowu** [ant-design/ant-design#353]
> 空格规范
>
> 1. 中文和英文间需要空格。
> 2. 数字与单位之间需要增加空格。 例外：度、百分比与数字之间不需要增加空格。
> 3. 中文链接之间增加空格。

请问中文与数字之间需要空格吗？

**Comment by Chinglik** [comment]
中文与数字之间也是需要加空格的哦~

**Comment by amowu** [comment]
:+1:
