### ISSUE TITLE
antd@4.20.0版本的Select组件分词有问题

### ISSUE THREAD

**Issue by bibiehy** [ant-design/ant-design#35304]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ding-zhi-hui-tian-nei-rong-antd-4-20-0-alpha-1-forked-nop47k?file=/demo.js)

### Steps to reproduce

1、复制 China 粘贴进去可以筛选出来
2、复制 China,USA 粘贴进去，无法粘贴

### What is expected?

在mode="multiple" tokenSeparators={[',']}设置下，可以支持粘贴 China,USA

### What is actually happening?

不能按分词来粘贴

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 16.13.1 |
| System | windows10 |
| Browser | 谷歌 |

**！！补充说明：antd@4.17.4版本可以，以上的不行**

**Comment by zombieJ** [comment]
分次符号匹配后会自动选中，这里分词没有满足选项所以置空了。

**Comment by bibiehy** [comment]
> 分次符号匹配后会自动选中，这里分词没有满足选项所以置空了。

没懂，如codesandbox中那般，tokenSeparators分词的值应该是什么？

**Comment by afc163** [comment]
`tokenSeparators` 只能针对完全匹配进行填入（这是个输入交互而不是选择交互），`mode="multile"` 模式一旦修改了渲染逻辑就会失效，其实应该只有 `mode="tags"` 模式才应该生效的。
https://codesandbox.io/s/ding-zhi-hui-tian-nei-rong-antd-4-20-0-alpha-1-forked-6g5m8r?file=/demo.js

**Comment by bibiehy** [comment]
> `tokenSeparators` 只能针对完全匹配进行填入（这是个输入交互而不是选择交互），`mode="multile"` 模式一旦修改了渲染逻辑就会失效，其实应该只有 `mode="tags"` 模式才应该生效的。 https://codesandbox.io/s/ding-zhi-hui-tian-nei-rong-antd-4-20-0-alpha-1-forked-6g5m8r?file=/demo.js

支持了全匹配还不够，我说下使用场景和为啥不能用tags

**使用场景**：配置服务器ip，多则几百个所以必须是复制粘贴进去直接匹配到，又因必须加服务器备注，children用纯文本显得不合适，得用 `jsx + optionLabelProp`，最新版本虽然支持粘贴单个，显然这样做会被产品骂死， 把版本切换为 `antd@4.17.4` 看下，要的就是这种


**为啥不用tags**：借用我上面的场景(带备注的)，如果你粘贴5个带分词标识的ip进去，下了框中会新增5个不带备注的 ip 且被选中，加上带备注的 ip 也被筛选出来了，就显得很奇怪，获取值的问题就不说了

**Comment by afc163** [comment]
> 借用我上面的场景(带备注的)，如果你粘贴5个带分词标识的ip进去，下了框中会新增5个不带备注的 ip 且被选中，加上带备注的 ip 也被筛选出来了，就显得很奇怪

这个是什么样的，能提供一个重现么？

**Comment by afc163** [comment]
For The Record: https://github.com/react-component/select/blob/a77be9b456c94a8c13bf6ea1986fbd2ebd8b0c9e/src/hooks/useOptions.ts#L31

**Comment by bibiehy** [comment]
> 



> > 借用我上面的场景(带备注的)，如果你粘贴5个带分词标识的ip进去，下了框中会新增5个不带备注的 ip 且被选中，加上带备注的 ip 也被筛选出来了，就显得很奇怪
> 
> 这个是什么样的，能提供一个重现么？

你看这个例子，[猛击我antd@4.17.4](https://codesandbox.io/s/ding-zhi-hui-tian-nei-rong-antd-4-20-0-alpha-1-forked-rws407?file=/demo.js)，这个是antd@4.17.4，`children` 用的jsx，`mode="multile"` 然后复制粘贴 `222.73.1.2,222.73.1.3,222.73.1.4` 直接就匹配并选中了，这就是我想要的结果，这种 jsx 布局在开发中很常见，全匹配真不够用。

这个例子代码跟上面一样，[猛击我@4.20.2](https://codesandbox.io/s/duo-xuan-antd-4-20-0-alpha-1-forked-zml8vj?file=/demo.js) 唯一区别就是版本改成了antd@4.20.2，你复制黏贴 `222.73.1.2,222.73.1.3,222.73.1.4` 就不能选中了，如果你复制一个 `222.73.1.2` 却能选中。
这里是不能用 `mode="tags"`  的，1. 复制粘贴进去 `222.73.1.2,222.73.1.3,222.73.1.4` 下面会增加3个ip，看起来交互很怪，2.F12看 onChange 的输出，我是要获取 sid 的结果返回了 ip，改成  `tags`  试试看。

希望后面版本中能优化一下。

**Comment by afc163** [comment]
Fixed
