### ISSUE TITLE
Space duplicated child key

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design#35305]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-space-duplicated-child-key-forked-ppg5hc?file=/index.js)

### Steps to reproduce

```jsx
<Space>
    <div key="1" />
    <div />
</Space>
```

### What is expected?

No duplicated key

### What is actually happening?

Warning: Encountered two children with the same key, `ant-space-item-1`.

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | React 17 |
| System | macOS 12 |
| Browser | Chrome 100 |

---
This bug is introduced by #33607

**Comment by MadCcc** [comment]
Recommend to give all children customized key value, or it's hard to avoid duplicated keys.

**Comment by afc163** [comment]
让默认 Space 的 key 稍微复杂一点就能避免大部分问题：https://github.com/ant-design/ant-design/pull/35311

**Comment by cncolder** [comment]
@afc163 可以保持用户提供的 key 不变. 只给默认的 index key 加前缀 `ant-space-item-1`, 这样冲突的概率就很小了.

ptal https://github.com/ant-design/ant-design/pull/35344

**Comment by scplay** [comment]
虽然这个问题已经修复了，这里提供一种以前会出现同样问题的场景，为什么 space 要保留 null 元素呢？想不明白
<Space>
    <div key="1" />
    {cond ? null : <div key="2" />
</Space>
