### ISSUE TITLE
Form.List中的Item，无法通过setFieldsValue设置值。

### ISSUE THREAD

**Issue by peter-gong** [ant-design/ant-design#35316]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/dong-tai-zeng-jian-qian-tao-zi-duan-antd-4-20-1-forked-lft4w1?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

第一步add field，在lastname中输入
第二部在firstname中输入

### What is expected?

期望firstname输入时，重置lastname。

### What is actually happening?

无法setFieldsValue设置lastname值

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | 17.0.0 |
| System | Windows 10 家庭中文版 21H2 |
| Browser | Microsoft Edge 版本 100.0.1185.50 (正式版本) (64 位) |

**Comment by crazyair** [comment]
setFields

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/34863
