### ISSUE TITLE
能否弄一个拾色器的组件呢？虽然有 react-color组件，但并不能满足。

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#35315]
### What problem does this feature solve?

高度融合antd，不会造成样式（比如react-color不是antd的input）不一致

### What does the proposed API look like?

1、最好能将sv面板，hue滑条，Alpha滑条独立出来，可以单独调用，这样大家可以任意组合不同的功能。
2、hue滑条，alpha滑条可以设置横向或竖向。
3、hue和alpha同样有不同的尺寸。
4、事件嘛，onChange，onChangeComplete

**Comment by afc163** [comment]
暂时无计划，ColorPicker 组件很复杂，短时间很难实现到 react-color 的完整功能。

**Comment by afc163** [comment]
5.5.0 已经有啦！https://github.com/ant-design/ant-design/pull/41990
