### ISSUE TITLE
【文档】Form.useForm 类型是不是不太对

### ISSUE THREAD

**Issue by btnkr** [ant-design/ant-design#35313]
### Reproduction link

[https://ant.design/components/form-cn/#Form.useForm](https://ant.design/components/form-cn/#Form.useForm)

### Steps to reproduce

文档问题

### What is expected?

type Form.useForm = (): [FormInstance]

### What is actually happening?

type Form.useForm = (): FormInstance

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.0.2 |
| System | macOS Monterey12.3.1 |
| Browser | chrome 100.0.4896.127 |

![image](https://user-images.githubusercontent.com/46664126/165762774-7b6b0294-d52b-4aae-9ab0-a6170aa0f99b.png)

**Comment by afc163** [comment]
来个 PR
