### ISSUE TITLE
显示scroll bar 的时候会多处一块表头

### ISSUE THREAD

**Issue by LiXiaoRan** [ant-design/ant-design#35322]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-20-1-forked-fvrvut?file=/demo.js)

### Steps to reproduce

1. 设置滚动条显示
2. 将表格的分页隐藏， 限定高度滑动
3. 此时表格体中出现滚动条，触发bug

### What is expected?

正常显示表头

### What is actually happening?

表头多出一块，类名为 th.antd-table-cell-scrollbar 
![586a344727c5952d4803e2f869aeddb3](https://user-images.githubusercontent.com/9404112/165900356-b588019c-6124-4b06-a8e0-fc2c15667f1d.png)

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.0.2 |
| System | Mac os & Windows 10 |
| Browser | chrome 100 |

**Comment by afc163** [comment]
若自行样式覆盖了表头背景色，则需要把这个分割线也覆盖掉。

**Comment by LiXiaoRan** [comment]
> 

请问如何覆盖这个分割线，我一直没找到

**Comment by utali** [comment]
> > 
> 
> 请问如何覆盖这个分割线，我一直没找到

`.ant-table-cell-scrollbar:not([rowspan])`的`box-shadow`
