### ISSUE TITLE
抽屉组件内 Button 点击关闭抽屉动画非常快

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#35328]
### Reproduction link

[https://stackblitz.com/edit/react-vube8n?file=demo.js](https://stackblitz.com/edit/react-vube8n?file=demo.js)

### Steps to reproduce

1、点击open
2、点击取消
结果抽屉关闭的非常快

### What is expected?

点击抽屉里面的 Button 关闭时间与点击 X 关闭时间一致。

### What is actually happening?

点击抽屉里面的 Button 关闭时间非常快

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by yunsii** [comment]
试了一下，好像没感觉诶

**Comment by crazyair** [comment]
> 试了一下，好像没感觉诶

可以打开 console 点击蒙层关闭和点击取消关闭，看打印的间隔

**Comment by yunsii** [comment]
> 可以打开 console 看下点击蒙层关闭和点击取消关闭，看打印的间隔

动画时间应该是一样的，destory 回调慢了？

**Comment by crazyair** [comment]
> yunsii

destory 回调慢才是正常的，跟 close 一块打印，那就证明抽屉卸载太快，会导致动画无效

**Comment by crazyair** [comment]
我加了个超链接按钮，点击超链接是ok的，只有元素是 Button 才会导致卸载加快

**Comment by crazyair** [comment]
https://user-images.githubusercontent.com/7971419/165923417-539103bd-faeb-4b36-ad54-1bf31d8be5fa.mp4

感受下打印的间隙

**Comment by yunsii** [comment]
我的意思就是 close 回调先调用，destroy 回调延迟上会有点差别

**Comment by crazyair** [comment]
> 我本地没发现有啥问题。

https://user-images.githubusercontent.com/7971419/165924455-046bc2e8-b4fe-4b8c-a98a-b574d80231b2.mp4

**Comment by crazyair** [comment]
> 我的意思就是 close 回调先调用，destroy 回调延迟上会有点差别

改用 time timeEnd 了，现在应该能清晰的看到区别了

**Comment by afc163** [comment]
神奇，Chrome 下确实是这样，Firefox 下是一样的。

**Comment by crazyair** [comment]
> 神奇，Chrome 下确实是这样，Firefox 下触发时长是一样的。

我又补充了 Modal 示例，在 Modal 写卸载时间是正确的，那就只能说 Drawer 确实有问题，并且可以解决

**Comment by crazyair** [comment]
如果快速点击是很快关闭，但是如果长按 Button 再取消时间是 ok 的。

**Comment by crazyair** [comment]
知道问题出在这个问题 https://github.com/ant-design/ant-design/blob/master/components/button/style/mixin.less#L226

**Comment by crazyair** [comment]
这个应该很早很早就有这个问题，解决办法可能需要当  onTransitionEnd 后再执行卸载组件方法
