### ISSUE TITLE
使用select组件时浏览器报警告信息

### ISSUE THREAD

**Issue by KevinLee-Romens** [ant-design/ant-design#3532]
#### 发生问题的环境是：

- antd 版本: 2.1
- react 版本：15.3.2
- 操作系统及其版本: osx 10.11
- 浏览器及其版本: chrome 54

#### 您做了什么？

在正常使用Select组件时浏览器提示如下信息
the children of `Select` should be `Select.Option` or `Select.OptGroup`, instead of `Option`.

代码如下
```jsx
import { Menu, Select } from 'antd';
const Option = Select.Option;

...

<Select
     style={{ width: 200 }} >
     <Option value="jack">Jack</Option>
     <Option value="lucy">Lucy</Option>
     <Option value="disabled" disabled>Disabled</Option>
     <Option value="yiminghe">Yiminghe</Option>
</Select>
```

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by KevinLee-Romens** [comment]
尝试了一下没有复现出来，目前只在我的项目里会出现这个错误，不清楚是不是项目内容有问题，先把这个issue关了吧，如果能浮现的时候我再发出来

**Comment by Ben07** [comment]
@KevinLee-Romens 你有没有用react-hot-loader/patch这个东西？  我在另外个issue里面看到有人提过这个，我也用了这个，我也有这个错误信息

**Comment by KevinLee-Romens** [comment]
@Ben07 感谢答复，我那个估计是项目里版本冲突导致的，存在了不同版本的antd，后来解决了，再次感谢
