### ISSUE TITLE
switch component css broken on dark theme

### ISSUE THREAD

**Issue by guiohm** [ant-design/ant-design#35331]
### Reproduction link

[https://ant.design/components/switch/?theme=dark](https://ant.design/components/switch/?theme=dark)

### Steps to reproduce

Un-toggle a switch with text.

### What is expected?

background should be gray, and we should see the text.

### What is actually happening?

the background is white when switch is off, same as the text, so we cannot see it.

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 18 |
| System | win |
| Browser | chromium |

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/pull/35103

**Comment by guiohm** [comment]
Thanks for the quick fix 👍
