### ISSUE TITLE
Layout的Sider折叠时, 若有二级菜单被打开, 会闪烁一下折叠时hover会显示的二级菜单然后消失

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#35343]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j52xe1)

### Steps to reproduce

1. 官网Layout下的《侧边布局》例子 (就是有一个可折叠的Sider里面有Menu)
2. 点开二级菜单
3. 折叠

### What is expected?

像antd pro里就不会有这个问题

### What is actually happening?

如标题

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.1.0 |
| System | Windows 10 |
| Browser | Chrome 101 |

**Comment by xsjcTony** [comment]
![issue](https://user-images.githubusercontent.com/45784210/166134972-08a9739e-1381-4198-9658-f935d23bfc24.gif)

**Comment by WP-Jorge** [comment]
我的问题跟你一样

**Comment by lalalazero** [comment]
这个应该是 React18 导致的，我拷贝了你的例子，用 ReactDOM.render 就没问题

**Comment by apple-tom** [comment]
我的是"react": "^18.1.0","antd": "^4.20.3" 出现闪的问题

**Comment by alienzhangyw** [comment]
有时候还会出现折叠后二级菜单还保留在页面上的情况，而且每次都是最后一组二级菜单。但是这个问题没法准确复现（窗口大小变化触发breakpoint之后再点击折叠容易出现），并且有的antd版本有，有的没有。

**Comment by joker77877** [comment]
这个问题很严重，什么时候可以解决

**Comment by afc163** [comment]
@zombieJ https://github.com/ant-design/ant-design/issues/35708 这里还有一个问题

**Comment by datnguyen89** [comment]
how to fix it ? 4.20.7 and react 18.1.0 still has this bug

**Comment by joker77877** [comment]
This bug hasn't been solved. Why close it?

**Comment by kyrie8** [comment]
我的是"react": "^18.1.0","antd": "^4.20.5" 也会出现闪的问题

**Comment by joker77877** [comment]
升级到最新版本就可以了。

**Comment by xsjcTony** [comment]
> 升级到最新版本就可以了。

已升级到了最新版 "antd": "^4.21.3", "react": "^18.2.0",

**默认展开**的情况下, 第一次收起没有问题不会闪烁, 但后续每次收起时依然会有该问题

**Comment by joker77877** [comment]
当你的折叠二级菜单的getPopupContainer设置为它的父元素时就会出现一系列样式问题，如果父元素时body则无问题。

**Comment by xsjcTony** [comment]
没有对getPopupContainer进行过任何配置, 但似乎没有默认渲染到body上.
又尝试在 `ConfigProvider` 中配置 `getPopupContainer={() => document.body}` 后依然会闪烁

**Comment by juneszh** [comment]
同样问题
![menu](https://user-images.githubusercontent.com/2436252/174746516-c2d0d177-9339-47f3-9adc-8140d6c5d0b0.gif)

├── @ant-design/icons@4.7.0
├── @ant-design/pro-components@1.1.6
├── @testing-library/jest-dom@5.16.4
├── @testing-library/react@13.3.0
├── @testing-library/user-event@13.5.0
├── @tinymce/tinymce-react@4.1.0
├── antd@4.21.3
├── moment@2.29.3
├── react-dom@18.2.0
├── react-resize-detector@7.1.2
├── react-scripts@5.0.1
├── react@18.2.0
├── source-map-explorer@2.5.2
└── web-vitals@2.1.4

        <Layout style={{ minHeight: '100vh', height: 'auto' }}>
            <Sider
                collapsible
            >
                <Menu
                    mode='inline'
                    theme='dark'
                    inlineIndent={16}
                    defaultSelectedKeys={['menu-1-1']}
                    defaultOpenKeys={['menu-1']}
                    items={items}
                />
            </Sider>
            <Layout className='site-layout'>
                <Content style={{ display: 'flex' }}>
                </Content>
            </Layout>
        </Layout>

**Comment by joker77877** [comment]
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/62642184/174773982-ee94ffe5-0aa6-4e99-a240-e09e7fd0aa16.png">
主要bugchan's产生的原因就是在收起的时候样式错误。暂时可以通过修改样式解决。

**Comment by xsjcTony** [comment]
好的. 研究一下
顺便等下修复, 谢谢.

**Comment by mynameisxue** [comment]
> 好的. 研究一下 顺便等下修复, 谢谢.

楼主修复了吗，有什么解决方案吗，我搞了2天了竟然是官方的问题...

**Comment by joker77877** [comment]
`.ant-menu-submenu-vertical {
            .ant-zoom-big-leave,
            .ant-zoom-big-leave-start,
            .ant-zoom-big-leave-leave {
                display: none;
            }
            .ant-menu-submenu-title {
                position: static;
            }
        }`
我目前是加这个样式解决的

**Comment by witcan** [comment]
> `.ant-menu-submenu-vertical { .ant-zoom-big-leave, .ant-zoom-big-leave-start, .ant-zoom-big-leave-leave { display: none; } .ant-menu-submenu-title { position: static; } }` 我目前是加这个样式解决的

这个也不好用

**Comment by witcan** [comment]
请问楼主修复了吗？

**Comment by Mr-Pcg** [comment]
react18 hooks + antd^4.24.10  可以尝试用一个div标签包裹Menu组件， 在给这个div标签绑定ref, 再通过ref注册mouseover事件，给body标签添加 class='layout-menu-box' 具体代码如下： 

//*-------------------------------- 解决了antd 的 menu 组件子集闪现的问题 ------------------------
  useEffect(() => {
   // 菜单栏关闭
    if (!collapsed) {
      document.body.classList.add("layout-menu-box");
    } 
    ref.current?.addEventListener("mouseover", mouseoverEvent(collapsed));
  }, [collapsed]);

  // 鼠标移入菜单区域
  const mouseoverEvent = (collapse: boolean) => {
    ref.current?.addEventListener("mouseover", () => {
      collapse
        ?  document.body.classList.remove("layout-menu-box")
        : document.body.classList.add("layout-menu-box");
    });
  };
  //*---------------------------------------------- End --------------------------------------

const handleSideCollapse = () => {
     setCollapsed(!collapsed)
}

const handleMenuClickEvent = ({ key }: { key: string }) => {
    //  跳转路由， 隐藏 menu 的子菜单
    if (collapsed) {
      document.body.classList.add("layout-menu-box");
    }
    navigate(key);
  };

  const changeOpenKeysEvent = (keys: string[]) => {
    setOpenKeys(keys);
  };

<Sider
        collapsible
        collapsed={collapsed}
        onCollapse={handleSideCollapse}
>
  <div ref={ref}>
        <Menu
            mode="inline"
            theme="dark"
            items={[]} // 你的菜单数据
            openKeys={openKeys}
            selectedKeys={selectedKeys}
            onOpenChange={changeOpenKeysEvent}
            onClick={handleMenuClickEvent}
        />
  </div>
</Sider>

**Comment by Mr-Pcg** [comment]
> <img alt="image" width="1524" src="https://user-images.githubusercontent.com/62642184/174773982-ee94ffe5-0aa6-4e99-a240-e09e7fd0aa16.png">
> 
> 主要bugchan's产生的原因就是在收起的时候样式错误。暂时可以通过修改样式解决。

**Comment by Mr-Pcg** [comment]
你可以用使用一个div标签包裹Menu组件， 再给这个div标签注册 mouseover 事件，通过给body标签添加class属性来控制Menu组件的子级菜单的闪现， 具体代码如下图所示
![a7ccc8bba257e81b2880f1908d3e447](https://github.com/ant-design/ant-design/assets/57671953/f15b062f-a2bc-481a-9219-e9880c5169e6)

**Comment by hasakilol** [comment]
try `forceSubMenuRender` : https://4x.ant.design/components/menu/
