### ISSUE TITLE
Tooltip的箭头比较大，箭头根部还有一条线，整体看上去不如原来好看

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design#35358]
### Reproduction link

[https://codesandbox.io/s/u2yb3m](https://codesandbox.io/s/u2yb3m)

### Steps to reproduce

直接看ant.design的Tooltip的示例

### What is expected?

保持跟原来类似的样式，缩小箭头大小

### What is actually happening?

箭头比较大，箭头根部有一条黑线，看上去箭头跟矩形容器不是一个整体

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | react 16.13.1 |
| System | win10 x64 |
| Browser | chrome 90 |

**Comment by cyndra0** [comment]
这个应该是跟 dpr 有关系，我系统上设置了 150% 的显示缩放看到的效果是这样的：
![image](https://user-images.githubusercontent.com/44607044/166401496-459fce49-4530-4dd7-8924-8744d025460e.png)，没设置的话样式正常。

**Comment by semdy** [comment]
> 这个应该是跟 dpr 有关系，我系统上设置了 150% 的显示缩放看到的效果是这样的： ![image](https://user-images.githubusercontent.com/44607044/166401496-459fce49-4530-4dd7-8924-8744d025460e.png)，没设置的话样式正常。

箭头跟矩形有1px的重合，由于箭头和矩形都是0.75的透明度，重合部分就是全黑的，因此会看到一条黑线。箭头比以前大了，不知道故意这么设计的还是bug

**Comment by afc163** [comment]
PR 里没关联 close xxx，所以没自动关。

**Comment by yunsii** [comment]
![image](https://github.com/ant-design/ant-design/assets/18096089/64fcafd9-2260-424e-bded-e99a63ab3e08)
![image](https://github.com/ant-design/ant-design/assets/18096089/55726a9f-30b4-411d-914d-c2646b2fb913)
现在还是有些问题，只在向下弹出会这样，绝了。
