### ISSUE TITLE
Cannot pass the array to useWatch

### ISSUE THREAD

**Issue by tkc310** [ant-design/ant-design#35353]
### Reproduction link

[https://g53d1m.csb.app/](https://g53d1m.csb.app/)

### Steps to reproduce

- Pass `string[]` as an argument to useWatch
- The return value is undefined.

### What is expected?

I would like to be able to watch multiple properties in the form of arrays or objects.

### What is actually happening?

If there are multiple values to be monitored, as shown below, it is necessary to call useWatch multiple times.

```
// current
const watched = {
  foo: useWatch('foo', form),
  bar: useWatch('bar', form),
  baz: useWatch('baz', form),
};

// expect
const watched = useWatch(['foo', 'bar', 'baz'], form);
or
const watched = useWatch([{ name: 'foo' }, { name: 'bar' }, { name: 'baz' }], form);
```

The type is `NamePath = string | number | InternalNamePath (string[] | number[])`, so it looks like an I/F that expects an array to be passed.

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.0.2 |
| System | macOS monterey 12.1 |
| Browser | chrome 100.0.4896.127 |

---
antd is a wonderful library with a great attention to detail.

**Comment by zombieJ** [comment]
`useWatch` watches single field value. The namePath is array for nest usage:
```tsx
const info = {
  user: {
    name: 'xxx',
  }
};

useWatch(['user', 'name']);
```

**Comment by crazyair** [comment]
or
```tsx
useWatch('foo', form);
useWatch('bar', form);
useWatch('baz', form)
const fieldsValue = form.getFieldsValue();
```
