### ISSUE TITLE
Modal components :  Hydration failed because the initial UI does not match what was rendered on the server in react:18.1.0 

### ISSUE THREAD

**Issue by Hamzaelkhatri** [ant-design/ant-design#35351]
### Reproduction link

[https://github.com/Hamzaelkhatri/portfolio-react](https://github.com/Hamzaelkhatri/portfolio-react)

### Steps to reproduce

#Modal in React version: 18.1.0 issue : 
Hydration failed because the initial UI does not match what was rendered on the server
when I downgraded the version to 17.0.2. the component works perfectly.
![image](https://user-images.githubusercontent.com/40549481/166175621-98098245-cc47-455b-a3b5-51a226694ffe.png)

### What is expected?

Modal work without any runtime error!

### What is actually happening?

when I use Modal components, the error shows up.

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React |  18.1.0 |
| System | linux  |
| Browser | google Chrom |

**Comment by afc163** [comment]
trace #36011

**Comment by IonelLupu** [comment]
I got the same error in next.js 13 with this page:
```
'use client'
 
export default function PaymentConfirmationPage() {

	const [loadingTransaction, setLoadingTransaction] = useState(true)

	return <>
		<Space align="center" direction="vertical" className="my-20 w-full">
			<LoadingOutlined className="text-9xl"/>
		</Space>

		<Modal open={loadingTransaction} footer={null} closable={false}>
			<Space direction="vertical" align="center" className="w-full my-12">
				<LoadingOutlined className="text-8xl"/>
				<h3>Please do not refresh or go back</h3>
				<h5>Processing transaction...</h5>
			</Space>
		</Modal>
	</>
}

```
