### ISSUE TITLE
Dashboard 对于 gapDegree 的绘制不准确

### ISSUE THREAD

**Issue by hullis** [ant-design/ant-design#35352]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-biao-pan-antd-4-20-2-forked-6gmhvs)

### Steps to reproduce

不需要操作

### What is expected?

当 gapDegree = 180 时应当为一个半圆

### What is actually happening?

实际的 gapDegree 角度比 180 要大，当 gapDegree 相当大时成为一个整圆

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | macOS latest |
| Browser | Microsoft Edge lastest |

**Comment by afc163** [comment]
https://github.com/react-component/progress/commit/344c08b4fffd5a292260de03922a70aecfe7dc74

gapDegree 不准，还是按 gapWidth 计算的。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35433
