### ISSUE TITLE
collapsed menu: findDOMNode was passed an instance of Trigger which is inside StrictMode

### ISSUE THREAD

**Issue by jyang14** [ant-design/ant-design#35361]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-finddomnode-issue-ohxmod)

### Steps to reproduce

Hover over the icon in the reproduction link

### What is expected?

No findDOMNode error in the console

### What is actually happening?

in the console: "findDOMNode was passed an instance of Trigger which is inside StrictMode"

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.1.0 |
| System | Windows |
| Browser | Chrome 100 |

**Comment by Bing-Wang-20161208** [comment]
any answers?

**Comment by john-pimq** [comment]
throw warning too
```
"react": "^17.0.2",
"antd": "^4.22.5",
```

**Comment by Samuel-luo** [comment]
throw warning too
```json
"react": "18.2.0",
"antd": "5.0.7",
```

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/212308070-026f2a85-f8f4-4eb8-9d38-52db0de93683.png">

**Comment by binghuis** [comment]
这个问题在5.3.0依然存在

**Comment by hcw2175** [comment]
same issue in: react 18.2 antd 5.3.0

**Comment by pchaganti** [comment]
+1

**Comment by jerryyxu** [comment]
+1

**Comment by Emily-0616** [comment]
+1

**Comment by Jing233-JS** [comment]
Same here

```
"antd": "^5.2.2",
"react": "^18.2.0",
```

**Comment by yaoyonstudio** [comment]
same issue
`"react": "^18.2.0"
"antd": "^5.3.0"`

**Comment by cloudSchulze** [comment]
same issue 

`"antd": "^4.21.4",
"react": "^18.2.0",
"react-dom": "^18.2.0", `

**Comment by Michaelplus6** [comment]
same issue 
"react": "^18.2.0" "antd": "^5.3.2"

**Comment by QC2168** [comment]
same issue  
```json
"antd": "~5.3.2",
"react": "^18.2.0"
```

**Comment by CrazyDiablo** [comment]
same issue when use Dropdown
`
"antd": "^5.3.2",
"react": "^18.2.0"
`

**Comment by zombieJ** [comment]
closed since `rc-menu@9.8.4` fixed this: https://codesandbox.io/s/antd-reproduction-template-forked-finddomnode-issue-g4xkkq?file=/package.json

**Comment by Khalilsqu** [comment]
same issue 

"antd": "^5.4.2",
"react": "18.2.0",
"react-dom": "18.2.0",

Removed Tooltip and the problem is solved.

**Comment by Khalilsqu** [comment]
> same issue
> 
> "antd": "^5.4.2", "react": "18.2.0", "react-dom": "18.2.0",
> 
> Removed Tooltip and the problem is solved.

Update, 

Apparently, this was my mistake

inside Tooltip there must be only one component. 

<MyCustomTooltip >
<Component />
< / MyCustomTooltip >

I had two components inside the MyCustomTooltip!!

Thanks for this awesome library.

**Comment by b5414** [comment]
still the same

```json
"antd": "^5.5.1",
"react": "^18.2.0",
```

**Comment by brayanjeshua** [comment]
The solution is to add rc-menu@9.8.4 😉

`npm install rc-menu@9.8.4`
or

`yarn install rc-menu@9.8.4`

**Comment by vinceve** [comment]
This isn't the case for the popover element as far as I see.
