### ISSUE TITLE
inkBar of Tabs is removed at react 18

### ISSUE THREAD

**Issue by jongjunpark** [ant-design/ant-design#35367]
### Reproduction link

[https://github.com/jongjunpark/antd-issue-repo](https://github.com/jongjunpark/antd-issue-repo)

### Steps to reproduce

1. install react 18
2. install antd
3. import antd css
4. add Tabs (basic)

### What is expected?

show inkBar

### What is actually happening?

not show inkBar

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.1.0 |
| System | all OS (window, Mac OS) |
| Browser | Chrome 98, all browser |

---
I found it at react 18. When I changed react 17 in same project, inkBar is shown. but I re-change react 18 in same project, inkBar is un-shown
- react 18
![image](https://user-images.githubusercontent.com/60080679/166435062-88eb1a69-5dc8-4cdd-9f02-ef0b4de39ca9.png)
- change react 17
![image](https://user-images.githubusercontent.com/60080679/166435151-7c5c21b2-b9e4-41d5-90a0-2417285a9ac1.png)

**Comment by xsjcTony** [comment]
Same Problem here

**Comment by vkhv** [comment]
some problem

**Comment by Resetand** [comment]
same problem

**Comment by Resetand** [comment]
As i can see it's happens only with `<StrictMode>...</StrictMode>` in dev environment, because react renders each component twice to highlight such problems. I temporarily remove strict-mode wrapper. But it's definitely not the best way to solve this issue

**Comment by TrickyPi** [comment]
seems "bug" in [here](https://github.com/react-component/tabs/blob/master/src/hooks/useRaf.ts#L9) , the `removeRef.current`  value is `true` in second mount, it will cause this [callback function](https://github.com/react-component/tabs/blob/master/src/TabNavList/index.tsx#L321) never be called

**Comment by 231231zzzz** [comment]
请问如何解决这个问题呢 我也出现了 目前只能降低版本嘛

**Comment by peterbyCom** [comment]
In the end to repair the ah 3 weeks no news at all? Made in China?

**Comment by peterbyCom** [comment]
BUG to fix or not? 3 weeks now no news at all? Made in China.

**Comment by littledian** [comment]
> seems "bug" in [here](https://github.com/react-component/tabs/blob/master/src/hooks/useRaf.ts#L9) , the `removeRef.current` value is `true` in second mount, it will cause this [callback function](https://github.com/react-component/tabs/blob/master/src/TabNavList/index.tsx#L321) never be called

It seems @TrickyPi  has created pr to fix it, but no one merge it
