### ISSUE TITLE
Table fixed column warning when changing `ConfigProvider` direction

### ISSUE THREAD

**Issue by nichita-pasecinic** [ant-design/ant-design#35365]
### Reproduction link

[https://github.com/nichita-pasecinic/antd-fixed-column-dev-warning](https://github.com/nichita-pasecinic/antd-fixed-column-dev-warning)

### Steps to reproduce

```
git clone https://github.com/nichita-pasecinic/antd-fixed-column-dev-warning
npm i # install deps
npm run dev 
```
Toggle direction by clicking on the button

### What is expected?

Columns should be fixed and no warning / error is displayed in console 

### What is actually happening?

Columns are correctly fixed, but there is an annoying warning in dev mode
![image](https://user-images.githubusercontent.com/98735377/166425628-19904658-0183-4a16-8887-5a05f051fb71.png)

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17.0.2 |
| System | Windows 10 pro |
| Browser | Chrome 100 |

---
The issue is not reproducible in stackblitz playground, ONLY local.
The warning itself comes from `rc-table`, I presume that it comes from [useColumns hook](https://github.com/react-component/table/blob/4cba6e67cd5d08badbe54be6d4a8c423c258a83e/src/hooks/useColumns.tsx#L64)

**Comment by nichita-pasecinic** [comment]
@afc163 Hi, sorry for notification, but could you please help here ?

Thx in advance

**Comment by Dunqing** [comment]
I fixed it.
You can ignore it for now.

**Comment by afc163** [comment]
Is it https://github.com/react-component/table/pull/803 still needed?
