### ISSUE TITLE
node18编译hash错误

### ISSUE THREAD

**Issue by weidehai** [ant-design/ant-design#35363]
### Reproduction link

[http://github.com](http://github.com)

### Steps to reproduce

1.git clone 
2.npm install
3.npm start

### What is expected?

编译成功

### What is actually happening?

编译报错

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17 |
| System | win11 |
| Browser | chrome |

---
使用node18编译报错
Error: error:0308010C:digital envelope routines::unsupported
<img width="614" alt="image" src="https://user-images.githubusercontent.com/25458528/166411490-92207a3d-a211-4527-8bdd-59cd329498f0.png">
这个问题是否可以这样修改解决
"start": "antd-tools run clean && cross-env **NODE_OPTIONS=--openssl-legacy-provider** NODE_ENV=development concurrently \"bisheng start -c ./site/bisheng.config.js\""

**Comment by zombieJ** [comment]
提供一下更具体的信息，指的是 antd 官网启动还是什么？另外如果提供的是解决方案的话欢迎直接 PR 哈~

**Comment by weidehai** [comment]
> 提供一下更具体的信息，指的是 antd 官网启动还是什么？另外如果提供的是解决方案的话欢迎直接 PR 哈~

是的，就是npm start命令启动官网，编译webpack createHash报错，我的环境是node18，打断点看目前webpack使用的是md4算法，node18应该是不支持md4了，所以报错digital envelope routines::unsupported，webpack6计划会修复这个bug，使用NODE_OPTIONS=--openssl-legacy-provider这个环境变量可以暂时解决node18环境下的编译问题，但是不知道是否有更好的办法呢？

**Comment by zombieJ** [comment]
目前官方站点用的 bisheng，里面 webpack 之前尝试过升级到 5 但是调试速度会慢很多就又改回 webpack 4 了。之后 @PeachScript  会更新成 dumi。
