### ISSUE TITLE
Using searchValue with showSearch=false make the selected item to disapear

### ISSUE THREAD

**Issue by markferreiro** [ant-design/ant-design#35366]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-exm61e?file=/app.js)

### Steps to reproduce

Open the select dropdown, focus on the search input inside the dropdown, start writing, and see that the select selected item disappears.

### What is expected?

I would expect that when using searchValue to filter the select options, in a select with the prop showSearch=false should keep the selected item rendered, instead of removing it from the dom.

### What is actually happening?

When searchValue.length is bigger than 0, the selected item is removed from the dom, but it should be kept as the prop showSearch= false

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.1.0 |
| System | macOS 12.2.1 |
| Browser | Chrome 100.0.4896.127 |

**Comment by afc163** [comment]
I suggestion use `showSearch` instead of making your own search function via dropdownRender.

**Comment by markferreiro** [comment]
Why did you closed it as completed? Thanks for your suggestion, but the bug is there. My company has their needs. I covered their needs and its not in my hands to use the showSearch as you're saying. So, let's not try to avoid the bug and find a solution for it. Thanks.

**Comment by markferreiro** [comment]
This issue is not closed. @afc163  closed it for no reason. What does mean: I suggestion use `showSearch`....? I know I can use this prop, but it's intended. I don't want to use this prop, so why the component is removing the selected item from the DOM when I send `searchValue` when `showSearch` is false? If I don't want to show the search input, don't remove the selected item from the DOM.........
