### ISSUE TITLE
包含子项的Menu无法触发onClick事件

### ISSUE THREAD

**Issue by 786259135** [ant-design/ant-design#35373]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5l1lk3?file=/index.js)

### Steps to reproduce

分别点击Menu 无子选项、有子选项的菜单，例如：test01、test02，具体代码可看demo

### What is expected?

点击后触发onClick事件，可以拿到key等信息

### What is actually happening?

无子选项 test01 的触发了onClick事件，而有子选项的 test02 未触发

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17.0.2 |
| System | macos 12.3.1 |
| Browser | Chrome 版本 100.0.4896.127（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35288#issuecomment-1111675911

**Comment by afc163** [comment]
Try `onOpenChange` for SubMenu
