### ISSUE TITLE
Cant use shorthand style properties

### ISSUE THREAD

**Issue by kevinpainchaud** [ant-design/ant-design#35376]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-lud8xu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

Use `<Row>` with `style={{ margin: 0 }}` (_or other shorthand style_)  prop.

### What is expected?

Do not throw warning/error.

### What is actually happening?

Throw warnings/errors:

```
Warning: Removing a style property during rerender (marginTop) when a conflicting property is set (margin) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
```

or

```
Warning: Updating a style property during rerender (rowGap) when a conflicting property is set (gap) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
```

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.1.0 |
| System | macOS Monterey version 12.13.1 |
| Browser | Google Chrome Version 100.0.4896.127 (Official Build) (arm64) |

**Comment by KAROTT7** [comment]
I'll solve this problem.
and I found another problem, if <Row /> without any props, then actual html will have `row-gap: 0px` prop.
![1651827051290](https://user-images.githubusercontent.com/21054747/167099497-e119b68c-14d3-48c4-8a81-388adb0847f6.jpg)

**Comment by afc163** [comment]
@KAROTT7 PR welcome~

**Comment by KAROTT7** [comment]
@kevinpainchaud 
Hi! I thought a while about this problem, it wasn't raise by Row Component, but React CSS. Maybe you can replace `{ margin: 0 }` to `{ marginLeft: 0, marginRight: 0 }`, and other property you can do like this.

**Comment by kevinpainchaud** [comment]
The auto added `row-gap: 0px` is so strange...

Thanks for your investigation!

I had also noticed that the error disappeared when I no longer used shorthands. But in my opinion, it shouldn't generate any error. Using shorthand makes code simpler and more readable.

**Comment by KAROTT7** [comment]
I found a way to avoid this error, we can use `CSS custom properties (variables)` to refactor `Row` and `Col`'s styles.

**Comment by wh4t3ver-r** [comment]
@kevinpainchaud 
I tried to reproduce this bug using antd 5.18.0 and it seems that it is no longer there. I think it was fixed in some previous release. If so I believe that this issue can be closed.
