### ISSUE TITLE
Modal组件UI显示bug

### ISSUE THREAD

**Issue by Youky1** [ant-design/ant-design#35377]
### Reproduction link

[https://github.com/Youky1/antd_bug_modal](https://github.com/Youky1/antd_bug_modal)

### Steps to reproduce

访问[GitHub page](http://youky.top/antd_bug_modal/)

或拉取运行项目即可复现。

### What is expected?

关闭按钮与下方输入框有间距

### What is actually happening?

关闭按钮和输入框重叠

| Environment | Info |
| --- | --- |
| antd | 4.18.8 |
| React | 17.0.2 |
| System | Windows10 |
| Browser | Chrome 101.0.4951.41 |

**Comment by MadCcc** [comment]
关闭按钮是 absolute 定位的，可以自行给 content 加点间距

**Comment by afc163** [comment]
目前没什么好办法，建议自行处理一下样式，加个 titile 或者去掉 `x`。

**Comment by LongHaoo** [comment]
@afc163 我们可以做判断是否有title 自动加上padding吗？

**Comment by LongHaoo** [comment]
我收回我的话，想到如果用户需要自定义自己的title 设置了no title，给了padding就会限制用户。

**Comment by afc163** [comment]
@LongHaoo 因为不知道 Modal 里的内容是啥，默认加 padding 可能会浪费右侧的空间。
