### ISSUE TITLE
SelectBox的数据能否是ajax动态加载的？

### ISSUE THREAD

**Issue by ptlinyi** [ant-design/ant-design#3537]
经常SelectBox的下拉选项希望是从服务器端加载的，但没看到这种支持，而且，没有展开下拉的事件（本来这时调用ajax加载就合适），只有OnBlur事件。
另外，下拉选择能否提供一个自己绘制的API，传入一个函数。
还有，希望下拉选择自己绘制一些额外元素，比如想加入一个刷新按钮或者加入CheckBox，之类的

**Comment by afc163** [comment]
数据自行管理，antd 只负责 UI 层。

**Comment by ptlinyi** [comment]
可能我描述的不对，我的问题不是要antd处理数据来源，而是提供相应的事件，比如，需要一个下拉框准备下拉的事件，这样我就可以在这个事件请求ajax的数据了

**Comment by afc163** [comment]
需要 http://github.com/react-component/select 里提供 onOpenChange 属性。

**Comment by afc163** [comment]
trace in https://github.com/ant-design/ant-design/issues/3587#issuecomment-256318539
