### ISSUE TITLE
Menu二级菜单右箭头无法关闭 或 自定义

### ISSUE THREAD

**Issue by 786259135** [ant-design/ant-design#35374]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5l1lk3?file=/index.js)

### Steps to reproduce

包含 children 字段的二级菜单会自动添加右箭头，且无法自定义或关闭显示

### What is expected?

1.一级菜单含有children时也可以自动加上右箭头
2.可以自定义或关闭箭头显示

### What is actually happening?

demo中 test02 项里的 test0202 项会自动包含右箭头，无法自定义箭头或关闭箭头

<img width="732" alt="image" src="https://user-images.githubusercontent.com/16495257/166616302-17d381a3-b3ef-495c-b452-cc7814bc573d.png">

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17.0.2 |
| System | macos 12.3.1 |
| Browser | Chrome 版本 100.0.4896.127（正式版本） (x86_64) |

**Comment by crazyair** [comment]
expandIcon

**Comment by 786259135** [comment]
> expandIcon

设置这个字段可以自定义右箭头，但还存在以下问题
1. 一级菜单如果有children字段无法自动添加右箭头
2. expandIcon 字段的默认值与文档不符（文档里没写有默认值）

一级的没有自动加
<img width="838" alt="image" src="https://user-images.githubusercontent.com/16495257/166625935-df26746a-cd93-4019-991f-ad72370e8794.png">

二级的可以加上
<img width="479" alt="image" src="https://user-images.githubusercontent.com/16495257/166625952-c053ea54-1a56-49e6-9a91-158c15640987.png">

**Comment by afc163** [comment]
水平 Menu 一级没有 expandIcon 是设计如此，目前不做改动。
