### ISSUE TITLE
overlay as function in Dropdown creates component twice instead of once

### ISSUE THREAD

**Issue by ALEUT** [ant-design/ant-design#35380]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dropdown-overlay-twice-render-antd-w6kezl?file=/index.js)

### Steps to reproduce

Just open reproduction and take a look at console log, you will see that 'created' text is appeared 2 times in the log.

### What is expected?

Component should be created once.

### What is actually happening?

Component is created twice.

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17.0.2 |
| System | Windows 11 |
| Browser | Chrome 101.0.4951.41 |

---
Thanks for antd!

**Comment by MadCcc** [comment]
Seems issue with Menu children. After 4.20.0, `items` prop is recommended.

**Comment by ALEUT** [comment]
@MadCcc it would be great to mark Menu.Item as deprecated in typings.
