### ISSUE TITLE
table 拖拽样式异常

### ISSUE THREAD

**Issue by chenjh-8** [ant-design/ant-design#35384]
跟这个问题一模一样 https://github.com/ant-design/pro-components/issues/3296
![image](https://user-images.githubusercontent.com/38275824/166858108-4548e4ce-7d1c-4405-89c2-c7b4ffc93c12.png)
按照这个https://ant.design/components/table-cn/#components-table-demo-drag-sorting也一样

"name": "ant-design-pro",
 "version": "5.2.0",
 "antd": "^4.19.0",

**Comment by MrHuang123** [comment]
这个最后有什么好的解决方案吗

**Comment by ohhoney1** [comment]
提供一个思路：onSortStart 中获取th td的宽度，然后遍历拖拽行的td，依次赋值th td 中的offsetWidth 即可。
