### ISSUE TITLE
不支持火狐52.3版本？

### ISSUE THREAD

**Issue by wusfe** [ant-design/ant-design#35382]
### Reproduction link

[https://ant.design/components/table-cn/ 或者 https://table-react-component.vercel.app/demo/animation](https://ant.design/components/table-cn/ 或者 https://table-react-component.vercel.app/demo/animation)

### Steps to reproduce

1. windows10下载Firefox52.3版本
2. 访问上述链接
3. Table组件区域出现错误代码占位

### What is expected?

显示Table组件

### What is actually happening?

错误代码提示

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17.0.0 |
| System | windows10 |
| Browser | Firefox 52.3 |

**Comment by zombieJ** [comment]
<img width="653" alt="截屏2022-05-05 上午10 04 38" src="https://user-images.githubusercontent.com/5378891/166854095-d035a81b-93a5-4d62-9b79-deb1a1329b71.png">

**Comment by Fullsize** [comment]
怎么解决的?
