### ISSUE TITLE
Modal changes from v4.20.0 are breaking React-testing-library unit test cases

### ISSUE THREAD

**Issue by hedaukartik** [ant-design/ant-design#35392]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1gm5sj)

### Steps to reproduce

1. Open modal
2. Open dev tools
3. Accessibility of dialog role with label name is changed to just label name

### What is expected?

As per the `react-testing-library`, the priority of accessibility goes on top by using `getByRole` for `dialog` with label name. It was working fine till `4.19.5` and broke our test cases from the `4.20.0` upgrade

### What is actually happening?

We are currently not able to query dom by `getByRole` for `dialog` with a label name, and it's breaking our test cases. The workaround and the temporary solution we found is that we can `getbyLabelText` which doesn't seem to be the right way to query dialog.

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17.0.2 |
| System | Mas OS 12.1 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
https://github.com/react-component/dialog/pull/285

**Comment by dgreene1** [comment]
@zombieJ we should reopen this issue since it is a regression of #285
