### ISSUE TITLE
New hover behavior for table on top of JS is slower and breaks expectations

### ISSUE THREAD

**Issue by Resetand** [ant-design/ant-design#35395]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zlzw2m?file=/index.js)

### Steps to reproduce

- Open [the link](https://codesandbox.io/s/antd-reproduction-template-forked-zlzw2m?file=/index.js)
- Check the console

### What is expected?

Hovering styles, such as background should be declared using CSS only

### What is actually happening?

JS is handled hover behavior, and change a className for each row. It's creates the performance issues and trigger unnecessary rerenders (!!! Especially if using rowSpan Cells)

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | 18.1 |
| System | mac OS  |
| Browser | Chrome 100 |

---
Seems link after 4.17 upgrade, in addition to performance problems with table, I faced that hover also trigger a rerender of cell, if using rowSpan. JS to handle hover seems to me complete unnecessary. I will be very happy to help, as this largely blocks me

**Comment by zombieJ** [comment]
<img width="506" alt="截屏2022-05-05 下午8 35 55" src="https://user-images.githubusercontent.com/5378891/166924167-0483539b-d20a-40a2-825c-554c0896c3bd.png">

New behavior of `onCell` for rowSpan will always hight merge row which is not support by css.

Follow https://ant.design/components/table-cn/#components-table-demo-colspan-rowspan for `onCell` usage.

**Comment by Resetand** [comment]
Thanks a lot 👍 
But what the purpose of using JS to handle hover behaviour? 
As i can see on row/cell hover there’s `hovering` prop change `Cell` component and toggle `.ant-table-cell-row-hover` className. 

<img width="380" alt="Screenshot 2022-05-05 at 15 34 33" src="https://user-images.githubusercontent.com/33288402/166925715-48a561e8-2d30-423e-a5cb-34b93277ce5f.png">

Is there are some side effect except changing background? Maybe give an opportunity to turn-off hover behavior. Previously (before `14.7`) i had opportunity just to override a styles like:

<img width="532" alt="Screenshot 2022-05-05 at 16 48 54" src="https://user-images.githubusercontent.com/33288402/166926334-47c57490-2f88-4307-a0ac-eacf941f3380.png">

**Comment by Resetand** [comment]
Any updates? Is it possible to reopen this issue, this behavior make user experience worse for cases with big tables
