### ISSUE TITLE
字体出现跨域请求

### ISSUE THREAD

**Issue by falltodis** [ant-design/ant-design#354]
Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' 
字体在cdn上，能不能放到项目中去呢。

**Comment by afc163** [comment]
什么环境，各种项目使用应该都是没问题的。

**Comment by falltodis** [comment]
生成环境啊，字体域是 alicdn 其他的js css资源走的是项目域名

**Comment by falltodis** [comment]
生产

**Comment by afc163** [comment]
没有问题的。

**Comment by zhbhun** [comment]
生产环境在内网的时候不能使用 alicdn, 建议在项目中提供字体文件, 在 alicdn 上也可以提供 antd 的 css 文件, 类似于 bootstrap, 这样更方便使用.

**Comment by Tinker404** [comment]
同出现这个情况。。。

**Comment by afc163** [comment]
是 iconfont.cn 的 cdn 问题。

**Comment by gaofangxiu** [comment]
@falltodis ,如果在内网环境下，最终怎么解决的呢。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1070
