### ISSUE TITLE
defaultSortOrder of Table component is not working

### ISSUE THREAD

**Issue by serdaryesilmurat** [ant-design/ant-design#35408]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/js-antd-table-ordering-forked-4t9w2g)

### Steps to reproduce

* Initialize state columns and dataSource with an empty array
* Load external data containing columns and dataSource
* Add a custom sort to the first column
* Set column and dataSource to state
* Update table

### What is expected?

To show the first column with the default sort order and ordered.

### What is actually happening?

It's not ordering and also it's not activating the default sort order. You have to interact with it to apply the ordering.

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 101.0.4951.54 |

---
Is defaultSortOrder not supposed to be kept as the active sort order after componentDidMount until user clicks on the sort button (if sortOrder is not used).

As I understand, in this case, defaultSortOrder does not work at all. Using sortOrder makes the column component controlled which is not the desired behavior here. Also, is there any callback for the sort action to be able to set the sortOrder field with the new direction afterwards, because when sortOrder is used, user action on sort button does not have any effect.

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

**Comment by zxq08** [comment]
how did you resolved? I meet the same question...

**Comment by Andrew213** [comment]
same problem

**Comment by raczynskil** [comment]
I had the same problem, defaultSortOrder doesn't work with responsive prop on the column.

**Comment by v-zdorovcev** [comment]
And I have the same problem. `defaultSortOrder` does not work when the `responsive` field is used

**Comment by KresimirJurkovic** [comment]
Same issue, its sorted correctly, direction is not applied correctly withing the arrows of the column header

**Comment by nnthanh01061999** [comment]
> And I have the same problem. `defaultSortOrder` does not work when the `responsive` field is used

Thanks you. You make my day. It's still not working in  "antd": "^5.18.0".

**Comment by meet-bhimani** [comment]
Is there any solution for this? I am also facing the same issue. even after applying defaultSortOrder to first column, it is not working

**Comment by meet-bhimani** [comment]
make sure to check conditionally for columns that it should not be undefined when table renders, this will solve the issue of default sort not working
