### ISSUE TITLE
ant designer 这么优秀的前端控件 是否有类似 structor/react ui builder或 ext designer 这种所见即所得的IDE 呢，有没有开发计划呢

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3540]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:windows 7旗舰版
- 浏览器及其版本:chrome

#### 您做了什么？
ant designer 这么优秀的前端控件如果能有structor之类的IDE 就必将一统江湖
希望有类似 structor 一样的所见即所得的IDE 参考 https://github.com/ipselon/structor

**Comment by afc163** [comment]
目前 Ant Design 还在继续夯实底层功能的阶段，离可视化编程还有一段较长的距离要走。

目前内部有过一些尝试，欢迎持续关注。

**Comment by eddyzhang1986** [comment]
或者类似这个 https://www.sencha.com/products/architect/ 也很牛X

**Comment by hbrls** [comment]
反对，我觉得提供到 Axure 层面就已经很好了，可视化坑太大，不要浪费主力资源
