### ISSUE TITLE
打包后的生产代码包含警告打印等不必要的代码

### ISSUE THREAD

**Issue by KAROTT7** [ant-design/ant-design#35405]
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-f5juh7?file=src%2FApp.jsx,vite.config.js,package.json,src%2FApp.css&terminal=dev](https://stackblitz.com/edit/vitejs-vite-f5juh7?file=src%2FApp.jsx,vite.config.js,package.json,src%2FApp.css&terminal=dev)

### Steps to reproduce

请看复现链接，为了易于排查问题，所以 vite 打包配置如下
```js
export default defineConfig({
  plugins: [react()],
  build: {
    minify: !true,
    rollupOptions: {
      external: ['react', 'react-dom', 'classnames'],
    },
  },
});
```
复现案例中已经是打包后的生产代码，可以查看 `dist/assets/index.5278c392.js` 文件
- 334-345 以及 4638-4640 是警告函数定义
- 复现案例中使用了 `AutoComplete` 组件，13132-13135 是 `AutoComplete` 组件警告代码；

存在两个问题
1. 首先警告函数定义不对，导致打包后的生产代码包含不影响程序运行的警告代码，这个问题我已经在 `rc-util` 中提了 Issue（[#301](https://github.com/react-component/util/issues/301)）
2. 警告函数不应该写在只包含警告函数的函数里，比如 components/auto-complete/index.tsx 中 `103-115` 代码，还有 `Radio` `Upload` 组件也是同样的代码书写方式

### What is expected?

打包后的生产代码不包含警告代码

### What is actually happening?

打包后的生产代码包含警告代码

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.0.0 |
| System | macOs Monterey 12.3.1 |
| Browser | Chrome 版本 100.0.4896.127（正式版本） (arm64) |

**Comment by zombieJ** [comment]
https://github.com/react-component/util/issues/301#issuecomment-1119497916

看你已经找到解法了，直接 PR 吧
