### ISSUE TITLE
请问有固定对齐的样式名可用？

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design#3541]
`return (<div className="（**这里可用用居中对齐的class？antd 有？叫啥**）">版权所有 © 2016 科技有限公司</div>);`

**Comment by junmaqiang** [comment]
我就是想问，自己不写居中样式的情况下，antd有没有写好的class 我填在这里就可以了！

**Comment by afc163** [comment]
目前没有的，这个自定义成本很低的。
