### ISSUE TITLE
OnEnd not fires on blur event (typography/editable)

### ISSUE THREAD

**Issue by Krinopotam** [ant-design/ant-design#35428]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/editable-title-text-onend-not-fires-on-blur-event-fmnlng)

### Steps to reproduce

Try to modify an editable text and click outside the field

### What is expected?

the onEnd editable event is triggered since the text gets modified

### What is actually happening?

no event is triggered

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | react 17.0.2 |
| System | Windows 10 |
| Browser | Chrome latest |

---
A similar issue was resolved in version 2.2.0-beta.3 but remains in version 4.20.2
https://github.com/vueComponent/ant-design-vue/issues/4227

**Comment by zombieJ** [comment]
It's by design:
<img width="634" alt="截屏2022-05-12 下午6 10 38" src="https://user-images.githubusercontent.com/5378891/168047495-aa1d6fab-cef8-4c1f-a37b-ed29cb268e23.png">

ref: https://ant.design/components/typography/#editable

**Comment by SultanNasyrovDeveloper** [comment]
So is there a way to handle blur event on typography?

**Comment by daveruiz** [comment]
> So is there a way to handle blur event on typography?

Blur event will bubble up to parent elements. You can handle your blur action from there. That worked for me.
