### ISSUE TITLE
依赖 @types/react-slick: "*" 导致错误

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design#35426]
### Reproduction link

[https://github.com/facebook/react/issues/24304](https://github.com/facebook/react/issues/24304)

### Steps to reproduce

cannot be used as a JSX component

### What is expected?

normal

### What is actually happening?

tips error

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome 100 |

**Comment by afc163** [comment]
看了一下，antd 本身貌似没有依赖 @types/react-slick

**Comment by zicong-zhang** [comment]
我这使用的是 antd 3.26.19，也存在这个问题，看依赖是使用了 "react-slick": "~0.25.2"，这个库安装之后 @types/react-slick 下还会有个 node_modules/@types/react（因为这个库里依赖了 @types/react: *），而这个 @types/react 的版本就是最新的 18，但我项目里用的是 16 版本

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/32116218/168023804-5cbfcc91-9d5f-4dff-a2a9-0ae88cf323be.png">

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/32116218/168024128-f12982f9-8aea-48fa-aba3-91733f2cbdaa.png">
