### ISSUE TITLE
使用 mapPropsToFields （结合redux）设置Form的值之后input会失去focus

### ISSUE THREAD

**Issue by luckyyang** [ant-design/ant-design#3542]
#### 发生问题的环境是：

- antd 版本: 2.0.1
- 操作系统及其版本: macos, 10.12
- 浏览器及其版本: chrome 53.0.2785.143 (64-bit)

#### 做了什么？
使用antd的Form组件生成表单，利用onFieldsChange触发redux的改变，然后使用 mapPropsToFields 将redux的值设置回Form

#### 您期待的结果是：

Form的值正常显示并可以继续操作Form

#### 实际上的结果是：
使用mapPropsToFields将redux的值设置之后input会失去focus，再次在input中输入的话需要手动去focus

我看onFieldsChange的时候会提供一个object，结构是：
```js
content: {
  dirty : false,
  errors : undefined,
  name : "content",
  validating : false,
  value : "Qui possimus provident ab"
}
```

还以为其中的dirty是用来标识focus一类的状态的，其实不是。

我应该如何才能让input focus呢？万分感谢

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by luckyyang** [comment]
需要配合下面的代码使用，就可以了：
```js
  shouldComponentUpdate(nextProps, nextState) {
     return false
  }
```

**Comment by luckyyang** [comment]
这部分内容是否可以更新到文档里？应该也会帮助到别人，或者我来更新提交PR也行，你告诉我下文档的位置，谢谢

**Comment by benjycui** [comment]
就算 component update 了，也会尝试重用已有的 DOM 结构，所以不会 blur 的。

还是麻烦你提供重现 demo。
