### ISSUE TITLE
DatePicker 的 OK 按钮的文案还是 Ok

### ISSUE THREAD

**Issue by aix3** [ant-design/ant-design#35434]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cth8mv)

### Steps to reproduce

点击 DatePicker，出现浮窗，按钮文案是 Ok

### What is expected?

点击 DatePicker，出现浮窗，按钮文案是 OK

### What is actually happening?

点击 DatePicker，出现浮窗，按钮文案是 Ok

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.1.0 |
| System | MacOS |
| Browser | Chrome |

---
之前有一个 PR #32259 修改了这个文案，但是官网 Demo 的文案还是 Ok，好像没有生效的样子。

**Comment by afc163** [comment]
欢迎来 PR~ https://github.com/react-component/picker/search?q=Ok

**Comment by chzng** [comment]
Modal弹框也出现 按钮文案 是Ok, Cancel

**Comment by afc163** [comment]
@chzng 来个 PR

**Comment by yykoypj** [comment]
> Modal弹框也出现 按钮文案 是Ok, Cancel

Modal应该没有这个问题
https://github.com/ant-design/ant-design/blob/36ded1a741b4f15775fde2ee1a5b3ad9082571db/components/locale/default.tsx#L39
