### ISSUE TITLE
InputNumber组件使用 precision 时,在safari浏览器中且输入法为简体中文时,会自动填写小数点后面的值,小数点后值的长度为precision的值

### ISSUE THREAD

**Issue by promiseLC** [ant-design/ant-design#35438]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gg1di9?file=/index.js)

### Steps to reproduce

在Safari中执行并且输入法为中文时就可以,并且在InoputNumber中输入数字

### What is expected?

我想在input失去焦点的时候补齐我设置的小数

### What is actually happening?

input输入1时,会自动补齐为 1.00

| Environment | Info |
| --- | --- |
| antd | 4.15.1 |
| React | 17.0.1 |
| System | mac |
| Browser | safari 15.4 |

---
现在是我想输入120, 会在我输入1时,补齐为 1.00 ,然后我删除.00 ,输入120才可以

**Comment by promiseLC** [comment]
不是codesandbox在Safari中打开,是 InputNumber组件 运行在Safari 才可以

**Comment by zombieJ** [comment]
来个 gif 看看？

**Comment by promiseLC** [comment]
![ca38cca6cb6f7d88727498426cdd89cc](https://user-images.githubusercontent.com/56290517/167370002-6bfa30de-3dc0-4f23-8591-42d55de240f1.gif)

**Comment by promiseLC** [comment]
precision值设为1,所以我输入9时,会变成9.0,不只precision会影响, min max step知道为小数都是可以触发的

**Comment by promiseLC** [comment]
@zombieJ

**Comment by zombieJ** [comment]
> 不是codesandbox在Safari中打开,是 InputNumber组件 运行在Safari 才可以

我试了一下无法重现，Codesandbox 的 Demo 如果在 Safari 下不能重现，那大概率是业务代码的问题。

**Comment by wohaiwo** [comment]
antd v4.21.0 也出现了上述貌似的问题 但没找到对应的原因  
解决方案是  基于inputNumber 包了一层  precision 通过 js 逻辑来进行控制
暂不自动添加默认的小数位数了

**Comment by feargadh** [comment]
我也遇到了类似的问题。开启stringMode， precision=2， 在safari会自动补充小数点，导致无法输入超过百位数。
例如我想输入100 或者1001，他会给我在自动变成10.00，而不是变成100.00 或者1001.00

**Comment by chelseachen007** [comment]
> > 不是codesandbox在Safari中打开,是 InputNumber组件 运行在Safari 才可以
> 
> 我试了一下无法重现，Codesandbox 的 Demo 如果在 Safari 下不能重现，那大概率是业务代码的问题。

我也稳定复现 你试下Safari切换输入法

**Comment by marunrun** [comment]
我也稳定复现了 0-0 目前是去掉precision 就解决了，不知道为什么

**Comment by Yn0312** [comment]
这问题都多少年了 还没修复啊
