### ISSUE TITLE
T.filter is not a function

### ISSUE THREAD

**Issue by Waylon-Firework** [ant-design/ant-design#35436]
### Reproduction link

[https://www.打包放在附件中.com](https://www.打包放在附件中.com)

### Steps to reproduce

1. 从node_module中拿出antd.min.js和antd.min.css
node_mudules/antd/antd.js/antd.min.js
node_mudules/antd/antd.less/antd.min.css
2. 在html中使用其中的menu组件
  <script crossorigin src="https://unpkg.com/react@17.0.2/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
  <script src="./antd.min.js"></script>
  <link href="./antd.min.css" rel="stylesheet"/>

          ReactDOM.render(
          <div>
            <antd.Menu
                selectable={false}
                mode="inline"
                defaultOpenKeys={'Resources'}
                style={{ width: '100%' }}
                items={menu1Items(menu1List)}
            />
          </div>
          , document.getElementById('root'));
4. menu无法收起
react-dom.production.min.js:56 Uncaught TypeError: T.filter is not a function
    at Object.current (antd.min.js:23:270276)
    at antd.min.js:23:256187
    at onClick (antd.min.js:23:260299)
    at Object.vi (react-dom.production.min.js:202:330)
    at ui (react-dom.production.min.js:32:27)
    at xi (react-dom.production.min.js:32:81)
    at zg (react-dom.production.min.js:55:403)
    at rg (react-dom.production.min.js:56:317)
    at react-dom.production.min.js:66:168
    at react-dom.production.min.js:240:292

### What is expected?

menu正常收起

### What is actually happening?

报错
react-dom.production.min.js:56 Uncaught TypeError: T.filter is not a function
    at Object.current (antd.min.js:23:270276)
    at antd.min.js:23:256187
    at onClick (antd.min.js:23:260299)
    at Object.vi (react-dom.production.min.js:202:330)
    at ui (react-dom.production.min.js:32:27)
    at xi (react-dom.production.min.js:32:81)
    at zg (react-dom.production.min.js:55:403)
    at rg (react-dom.production.min.js:56:317)
    at react-dom.production.min.js:66:168
    at react-dom.production.min.js:240:292

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

[antd.zip](https://github.com/ant-design/ant-design/files/8647103/antd.zip)

**Comment by afc163** [comment]
确实有问题：https://codesandbox.io/s/ji-chu-yong-fa-fei-qi-de-yu-fa-tang-antd-4-20-2-forked-8vgofh?file=/demo.js

**Comment by afc163** [comment]
https://github.com/react-component/menu/pull/467

明天我再加个用例再发。

**Comment by afc163** [comment]
发现问题了，defaultOpenKeys 是个数组而不是字符串。

```diff
- defaultOpenKeys={"Resources"}
+ defaultOpenKeys={["Resources"]}
```

**Comment by gJhlee** [comment]
Still not fixed :(
