### ISSUE TITLE
多条message的显示问题

### ISSUE THREAD

**Issue by yeliex** [ant-design/ant-design#3543]
调用了多条message时现在会覆盖 是否可以考虑纵向排列避免覆盖

**Comment by benjycui** [comment]
`message` 和 `notification` 都是基于 [rc-notification](http://react-component.github.io/notification/) 的，所以改动应该不大。

**Comment by yeliex** [comment]
@benjycui 我可以提交一个pr

**Comment by wufeng87** [comment]
暂时用这个样式减弱了这个问题带来的影响
.ant-message span .ant-message-notice:first-child {    top: 41px;  }

**Comment by benjycui** [comment]
cc @yeliex , 本地跑起来能看到这个 demo，但是样式还是有问题，你可以试试，看能不能找到修复的办法。

**Comment by yeliex** [comment]
@benjycui 能不能麻烦截个图 
做不到单独控制某一个message是否重叠(可能是我思路不对
所以我的做法是在config中加一个stack属性 调用了stack以后所有message都会使用排列

**Comment by yeliex** [comment]
做不到单独控制某一个message是否重叠(可能是我思路不对
所以我的做法是在config中加一个stack属性 调用了stack以后所有message都会使用排列
正确的做法是进入页面以后直接点击unstack demo 这样所有message都不会重叠显示

**Comment by yeliex** [comment]
另外是否有必要允许配置也是一个要讨论的问题

**Comment by afc163** [comment]
感觉直接作为 bugfix 更好，不允许叠加了。

**Comment by yeliex** [comment]
@afc163 那么现在的问题就是 因为每条宽度不固定 所以如果要居中显示 两边就会被遮盖 不能点击下层的内容

**Comment by benjycui** [comment]
我把相关的提交 revert 了，比想象中的要麻烦。notification 因为是定宽，所以比较好做，message 因为是不定宽，略麻烦。。
