### ISSUE TITLE
Typescript: Replacing moment with dayjs as shown in documentation throw a type error on build

### ISSUE THREAD

**Issue by eightshone** [ant-design/ant-design#35441]
### Reproduction link

[https://github.com/eightshone/antd-typescript](https://github.com/eightshone/antd-typescript)

### Steps to reproduce

Just follow the sample code found here: https://ant.design/docs/react/replace-moment#DatePicker.tsx

### What is expected?

No Typescript errors

### What is actually happening?

Getting type errors both in VS Code and when building the project.
This is the error that is thrown:
TS2786: 'DatePicker' cannot be used as a JSX component.
  Its instance type 'Component<PickerProps<Dayjs> & { status?: "" | "warning" | "error" | undefined; }, unknown, any> & CommonPickerMethods' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("path/to/project/node_modules/@testing-library/react/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
     8 |
     9 | const TimePicker = React.forwardRef<any, TimePickerProps>((props, ref) => {
  > 10 |   return <DatePicker {...props} picker="time" mode={undefined} ref={ref} />;
       |           ^^^^^^^^^^
    11 | });
    12 |
    13 | TimePicker.displayName = "TimePicker";

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17 |
| System | Windows 10 Enterprise version 20H2 build 19042.1645 |
| Browser | Firefox (irrelevant) |

---
This error occurs with TimePicker.tsx file

**Comment by eightshone** [comment]
Here's a screenshot of the error from the build command:
![image](https://user-images.githubusercontent.com/36240779/167372211-2093321f-3abd-40df-9085-1169bc1c8828.png)

I had to recreate this issue because the other one got closed over my vacation 😅

**Comment by afc163** [comment]
You can try to upgrade @types/react to 18, https://github.com/ant-design/ant-design/issues/34952#issuecomment-1117412649

**Comment by domino-pablo-rodriguez** [comment]
For anyone else encountering the issue, the documentation is wrong (types should be inverted):

```
const TimePicker = React.forwardRef<TimePickerProps, any>((props, ref) => (
  <DatePicker {...props} picker="time" ref={ref} />
));
```

note `TimePickerProps` and `any`
