### ISSUE TITLE
InputNumber decimal separator for comma formats input incorrectly

### ISSUE THREAD

**Issue by JKortmann** [ant-design/ant-design#35447]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-input-number-decimal-seperator-i1d1y3?file=/index.js)

### Steps to reproduce

Enter the value "12.0" into the input field.

### What is expected?

The input should be formatted to "120".

### What is actually happening?

The input is formatted to "12,00".

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 17.0.2 |
| System | macOS Monterey v12.0.1 |
| Browser | Chrome Version 101.0.4951.54 (Official Build) (x86_64) |

---
Compare this to the behaviour of the decimal separator ".". There the input "12,0" gets formatted to "120" which is in line with the expectations.

**Comment by afc163** [comment]
It should be `12.00` and it's correct.

<img width="912" alt="图片" src="https://user-images.githubusercontent.com/507615/167404939-cc48d06b-9e62-414f-b38e-aaafb80c15f1.png">

**Comment by JKortmann** [comment]
@afc163 Sorry, I provided a wrong example. The decimal separator now is ",". Now the input "12.0" gets transformed to "12,00" which should be "120,00".

**Comment by MadCcc** [comment]
Why "12.0" should be transformed to "120,00"? `decimalSeperator` only changes '.'

**Comment by JKortmann** [comment]
Because e.g. in the German number system a dot is used to separate the thousand digits. So it is exactly the other way around to the English-international system, where "12.0" is made into "120" (dot as decimal separator, comma to separate the thousand places). Accordingly, if a comma is specified as a decimal separator, "12.0" should become "120" (comma as decimal separator, dot to separate the thousand digits).

I hope this clears things up.

**Comment by MadCcc** [comment]
> Because e.g. in the German number system a dot is used to separate the thousand digits. So it is exactly the other way around to the English-international system, where "12.0" is made into "120" (dot as decimal separator, comma to separate the thousand places). Accordingly, if a comma is specified as a decimal separator, "12.0" should become "120" (comma as decimal separator, dot to separate the thousand digits).
> 
> I hope this clears things up.

I've got what you mean. `decimalSeperator` is currently designed to replace `.` in input value, and the feature you want may not be introduced because it is an edge case. 
Could you try `formatter` and `parser` if these props can help you?

**Comment by endrit-mesh** [comment]
This not fixed and should not be closed
