### ISSUE TITLE
ant 样式类名在调用时出现问题因为“-”这个符号

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design#3544]
我是在下面这个地址 看到第一个演示案例觉得很棒
`https://ant.design/docs/spec/layout`

于是我就复制代码到本地，可是看到的效果不同

后来经过调试发现，antd 组件的样式命名都类似这样 “ant-layout-wrapper” ；
但是我在组件里用 `{styles.ant-layout-footer}和{styles.antLayoutFooter} `两种写法都无效
我尝试修改.less文件里面把 `.ant-layout-footer` 改为 `.footer`
然后在组件里面用 `{styles.footer}` 就可以了

这说明.less文件里面用的类名不能有 - 这个符号。
难道我要把antd的css文件里面这些样式命名都改一遍？
好奇怪！
我要咋办呢，求助！

**Comment by afc163** [comment]
`styles['ant-layout-wrapper']`
