### ISSUE TITLE
Strange behavior when the precision value of the statistics component is negative

### ISSUE THREAD

**Issue by ty888** [ant-design/ant-design#35450]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-20-3-forked-ovmuhr?file=/demo.js)

### Steps to reproduce

Just follow the sample code found here: [sample](https://codesandbox.io/s/ji-ben-antd-4-20-3-forked-ovmuhr?file=/demo.js)

### What is expected?
input: `<Statistic title="Active Users" precision={-1} value={-1112893.1212} />`
output: `-1,112,893.1212` or  `-1,112,893`

input: `<Statistic title="Active Users" precision={-2} value={-1112893.1212} />`
output: `-1,112,893.1212` or  `-1,112,893`

input: `<Statistic title="Active Users" precision={-3} value={-1112893.1212} />`
output: `-1,112,893.1212` or  `-1,112,893`

### What is actually happening?
input: `<Statistic title="Active Users" precision={-1} value={-1112893.1212} />`
output: `-1,112,893.121`

input: `<Statistic title="Active Users" precision={-2} value={-1112893.1212} />`
output: `-1,112,893.12`

input: `<Statistic title="Active Users" precision={-3} value={-1112893.1212} />`
output: `-1,112,893.1`

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 16.11 |
| System | mac |
| Browser | Google Chrome |

---
When this accuracy value is negative, it does not work properly, so it needs to be limited.
Can I try to fix it?

**Comment by MadCcc** [comment]
Why not use positive value?

**Comment by afc163** [comment]
```diff
-         decimal = padEnd(decimal, precision, '0').slice(0, precision);
+        decimal = padEnd(decimal, precision, '0').slice(0, precision > 0 ? precision : 0);
```
