### ISSUE TITLE
Popover位置异常

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#3545]
![image](https://cloud.githubusercontent.com/assets/13936160/19624577/dc42c43e-992f-11e6-8088-44ac5a79c4ed.png)
初次hover位置异常
![image](https://cloud.githubusercontent.com/assets/13936160/19624584/0eff23a4-9930-11e6-9ce1-33159839d54b.png)
第二次hover位置正常
**表格超出父元素width时出现这种case**
![image](https://cloud.githubusercontent.com/assets/13936160/19624625/0db1be2e-9932-11e6-80f5-bbd10000297a.png)

UA:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by qiaoyixuan** [comment]
Tooltip有同样的问题

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by qiaoyixuan** [comment]
[](http://codepen.io/anon/pen/rrPraK)
表格靠右侧的thead-title hover时会复现，左侧却正常
popover content若非<span/>不会复现，好像是因为内容没有展开为一行带来的位置错误，若将<span/>换为<div/>或为<span/>设置css: whiteSpace: nowrap可修复问题，但当content过长还是希望其能自动换行

**Comment by afc163** [comment]
```jsx
<Popover content={<div style={{ width: 400 }}>xxx</div>} placement="top">
  <a target="_blank">{title}</a>
</Popover>
```

用 `width` 或 `maxWidth` 给 Popover 定宽，排版的变化会导致位置计算错误。

**Comment by qiaoyixuan** [comment]
@afc163 没有对其定宽的操作，现在只能强制不换行解决这个问题

**Comment by afc163** [comment]
建议你定宽。
