### ISSUE TITLE
Hover behavior on top of JS for `Table` has performace issues

### ISSUE THREAD

**Issue by Resetand** [ant-design/ant-design#35459]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-j1i0oe?file=/index.js)

### Steps to reproduce

- Open [the link](https://codesandbox.io/s/antd-reproduction-template-forked-j1i0oe?file=/index.js) 
- Try to scroll to see frezzing of hover behavior
- Slowdown CPU to make sure more clearly (`devtools` → `Performance` → `CPU *x slowdown`)

### What is expected?

Hovering styles, such as background should be declared using CSS only

### What is actually happening?

JS is handled hover behavior, and change a className for each row. It's creates the performance issues especially for cases with grouped rows (eg `rowSpan`)

| Environment | Info |
| --- | --- |
| antd | > 4.17.0 |
| React | 18.1 |
| System | mac OS  |
| Browser | Chrome 100 |

---
Hi 👋 
This is actually clone of https://github.com/ant-design/ant-design/issues/35395 issue, it looks like the problem is still there, so i'm trying again
Is there are any side effect except changing a background that forces using JS to handle hover? 
PS Maybe give an opportunity to turn-off hover behavior complete for performance sensitive cases

**Comment by Resetand** [comment]
Uploading Screen Recording 2022-05-10 at 02.06.26.mov…

**Comment by zombieJ** [comment]
Since `render` side effect still exist in v4. Which will be removed in v5 to avoid breaking change.

**Comment by Resetand** [comment]
Can you share, what are the estimated v5 release date?

**Comment by alienzhangyw** [comment]
[antd表格性能差的解决方案](https://juejin.cn/post/7063332320339099678)

**Comment by Resetand** [comment]
@alienzhangyw thanks, ts is much faster

https://user-images.githubusercontent.com/33288402/167868669-86922631-4d0a-4b13-a8d9-80db396346c6.mov
