### ISSUE TITLE
`List.Item` – broken type

### ISSUE THREAD

**Issue by rsmeral** [ant-design/ant-design#35454]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/list-item-type-broken-152kes?file=/src/App.tsx:188-195)

### Steps to reproduce

See the type of the `actions` prop on `List.Item`.

### What is expected?

The `actions` prop should exist on `List.Item` as per documentation.

### What is actually happening?

The `actions` prop is missing.

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 17 |
| System | Any |
| Browser | Any |

**Comment by jjavierdguezas** [comment]
happening right now:
>  Type '{ children: Element; className: string; actions: any[]; }' is not assignable to type 'IntrinsicAttributes & ListItemMetaProps & RefAttributes<HTMLElement>'.
    Property 'actions' does not exist on type 'IntrinsicAttributes & ListItemMetaProps & RefAttributes<HTMLElement>'.  TS2322

**Comment by sh0umik** [comment]
Same here

**Comment by pgs-gmartowski** [comment]
+1 
`Property 'actions' does not exist on type 'IntrinsicAttributes & ListItemMetaProps & RefAttributes<HTMLElement>'.`
