### ISSUE TITLE
Incorrect types for InputNumber with forwardRef

### ISSUE THREAD

**Issue by artiii** [ant-design/ant-design#35457]
[###](url) Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-f9j7ej?file=/index.tsx)

### Steps to reproduce

import { forwardRef } from 'react'
import { InputNumber as AntInputNumber, InputNumberProps } from 'antd'

const InputNumber = forwardRef<typeof AntInputNumber, InputNumberProps>(
	({ className, ...props }, ref) => {
		return <AntInputNumber {...props} ref={ref} />
	}
)

export default InputNumber

### What is expected?

no any TS errors

### What is actually happening?

TS error

| Environment | Info |
| --- | --- |
| antd | 4.16.10 |
| React | 17.0.2 |
| System | - |
| Browser | - |

**Comment by artiii** [comment]
<img width="1157" alt="Screenshot 2022-05-09 at 23 39 03" src="https://user-images.githubusercontent.com/17064158/167485116-da074ba5-5aa5-4bf9-9a9f-1a7de2411328.png">

**Comment by artiii** [comment]
It looks like the issue https://github.com/ant-design/ant-design/issues/33417

**Comment by MadCcc** [comment]
Try `HTMLInputElement`?

**Comment by artiii** [comment]
thanks, It works
