### ISSUE TITLE
链接打不开

### ISSUE THREAD

**Issue by likunyan** [ant-design/ant-design#35460]
### Reproduction link

[https://ant-design.antgroup.com/components/grid-cn/](https://ant-design.antgroup.com/components/grid-cn/)

### Steps to reproduce

https://ant-design.antgroup.com/components/grid-cn/

### What is expected?

可以打开

### What is actually happening?

打不开

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | - |
| System | - |
| Browser | - |

**Comment by afc163** [comment]
已修复。
