### ISSUE TITLE
在 Pagination 组件中，当给定的 pageSize >= total 时，指定 current 无效 

### ISSUE THREAD

**Issue by fkworld** [ant-design/ant-design#35466]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2lhozt?file=/index.js)

### Steps to reproduce

构建一个  Pagination 组件，指定 pageSize=total=50, current=2，实际显示结果为第1页。
```tsx
<Pagination
  current={2}
  pageSize={50}
  total={50}
  showTotal={(v) => v}
  showSizeChanger
/>
```
示意图为：
![image](https://user-images.githubusercontent.com/11092123/167580107-956346e5-fc17-4c9e-81b1-9d47b386b1dd.png)

### What is expected?

在指定 current 时，无论 pageSize 和 total 的关系如何，都显示为指定的 current。

### What is actually happening?

在指定 current 时，当 pageSize >= total 时，都显示为 1。

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 16.14.0 |
| System | mac os |
| Browser | Edge 101 |

**Comment by afc163** [comment]
current 就是控制当前页是多少，尊重用户的指定值更合适。

**Comment by fkworld** [comment]
> current 就是控制当前页是多少，尊重用户的指定值更合适。

在我的例子中，在 pageSize=50, total=50 时，我指定 current=2 并未生效，而是显示为 1。

按照「尊重用户的指定值更合适」的思路，此时 current 应该显示为 2。

**Comment by afc163** [comment]
current 是当前 active 高亮节点。

**Comment by fkworld** [comment]
我明白了！

感谢回复。
