### ISSUE TITLE
Transfer组件支持server rendering吗

### ISSUE THREAD

**Issue by machao23** [ant-design/ant-design#3546]
使用Transfer组件使用渲染出错：
![image](https://cloud.githubusercontent.com/assets/5095336/19625853/a9c16b24-9956-11e6-8ee5-0ba1ceffc27d.png)

参考https://ant.design/components/transfer/ 的第一个例子

**Comment by afc163** [comment]
https://github.com/react-component/animate/blob/df8e4103fd253c3a51dccdfd6591bf3b2c2ef1fe/src/Animate.js#L10

指定一下数据的 key ，这个 defaultKey 是随机的。

**Comment by machao23** [comment]
@afc163 不好意思，是指data里的key吗，例子里用的是数组下标
for (let i = 0; i < 20; i++) {
      const data = {
        key: i,
        title: `content${i + 1}`,
        description: `description of content${i + 1}`,
        chosen: Math.random() * 2 > 1,
        disabled: Math.random() * 3 < 1,
      };
      if (data.chosen) {
        targetKeys.push(data.key);
      }
      mockData.push(data);
    }

**Comment by afc163** [comment]
知道了，不能用 0 做 key。例子我也改改。

**Comment by machao23** [comment]
@afc163 不好意思，0是指for循环里变量i的值吗，我换成for(let i=1; i<20; i++) 还是会warning。
