### ISSUE TITLE
改变字体大小后，Icon 不能在 Row 中垂直居中。

### ISSUE THREAD

**Issue by KAROTT7** [ant-design/ant-design#35468]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-icon-style-error-in-col-dpzuf8?file=/src/App.js)

### Steps to reproduce

看复现链接中第一列，然后通过切换`lineHeight: 1`样式看对比效果

### What is expected?

不管 Icon 组件字体大小多少，都应该在 Row 组件中垂直居中

### What is actually happening?

改变 Icon 字体大小后，不能在 Row 组件中垂直居中

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.0.0 |
| System | macOS Monterey 12.3.1 |
| Browser | 版本 100.0.4896.127（正式版本） (arm64) |

**Comment by afc163** [comment]
Row 是 `justify-content: center;` 的，但是 Col 不是，Icon 的容器实际上是 Col。

建议给 Col 内增加垂直居中的容器：https://codesandbox.io/s/antd-icon-style-error-in-col-forked-og83eq?file=/src/App.js
