### ISSUE TITLE
Modal.confirm的content里面包裹一个Radio的时候，radio切换不了值

### ISSUE THREAD

**Issue by duchaolin** [ant-design/ant-design#35469]
### Reproduction link

[http://ceshi.com](http://ceshi.com)

### Steps to reproduce

开发

### What is expected?

开发

### What is actually happening?

开发

| Environment | Info |
| --- | --- |
| antd | 3.26.20 |
| React | 16.14.0 |
| System | 开发 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
你需要使用 useModal 才能获得当前 React 渲染树的状态，纯粹的静态方法没有这个能力。

https://ant.design/components/modal-cn/#components-modal-demo-hooks

**Comment by afc163** [comment]
useModal 是 4.x 提供的功能，3.x 就没办法了，建议自行封装 `<Modal />` 组件。

**Comment by duchaolin** [comment]
> useModal 是 4.x 提供的功能，3.x 就没办法了，建议自行封装 `<Modal />` 组件。

难受，就只有直接用model然后控制它的显示隐藏。不能用modal.confirm，朋友，这个是怎么造成的，能解释一哈吗

**Comment by afc163** [comment]
看看 https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux%E3%80%81%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F

**Comment by duchaolin** [comment]
感谢

**Comment by duchaolin** [comment]
> 看看 https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux%E3%80%81%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F


> 看看 https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux%E3%80%81%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F

好的，感谢
