### ISSUE TITLE
Typescript type for List.Item is missing actions property

### ISSUE THREAD

**Issue by almoco** [ant-design/ant-design#35479]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/delicate-hill-1j6136?file=/src/App.tsx:109-121)

### Steps to reproduce

Use List.Item with actions prop.

### What is expected?

An existing actions prop

### What is actually happening?

My guess is a typo in the type declaration - the error says there is no actions property in ListItem**Meta**Props, not ListItemProps ..

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | react 17.0.2 |
| System | MacOS 12.1 |
| Browser | Chrome |

---
Error: Type '{ actions: never[]; }' is not assignable to type 'IntrinsicAttributes & ListItemMetaProps & RefAttributes<HTMLElement>'.
  Property 'actions' does not exist on type 'IntrinsicAttributes & ListItemMetaProps & RefAttributes<HTMLElement>'.ts(2322)

From declaration:

export interface ListItemTypeProps extends ForwardRefExoticComponent<**ListItemMetaProps** & React.RefAttributes<HTMLElement>> {
    Meta: typeof Meta;
}

**Comment by vicrep** [comment]
Pretty sure this is the culprit, experiencing same issue with other `List.Item` props: https://github.com/ant-design/ant-design/pull/35321/files#diff-7db9a406f484d525769144001ea160805de23afa26e4b84eba2672f9d81b9d1cR67

**Comment by vicrep** [comment]
Pretty sure this is the culprit, experiencing same issue with other `List.Item` props: https://github.com/ant-design/ant-design/pull/35321/files#diff-7db9a406f484d525769144001ea160805de23afa26e4b84eba2672f9d81b9d1cR67

**Comment by hengkx** [comment]
ref https://github.com/ant-design/ant-design/pull/35455
