### ISSUE TITLE
Table sticky not working RTL

### ISSUE THREAD

**Issue by edrmsgl** [ant-design/ant-design#35478]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fragrant-wildflower-9qqppt?file=/index.js)

### Steps to reproduce

Does the table sticky feature have rtl support?

### What is expected?

table sticky parameter RTL support

### What is actually happening?

Not working for RTL

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.1.0 |
| System | Windows 11 |
| Browser | Chrome 101.0.4951.41 |

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ant-design) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ant-design/ant-design/issues/35478">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ant-design/ant-design/issues/35478/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ant-design/ant-design/issues/35478/pledge.svg">
</picture>
</a>

**Comment by afc163** [comment]
It works: https://codesandbox.io/s/purple-feather-725glq?file=/index.html

**Comment by edrmsgl** [comment]
You cannot scroll left unless you are at the bottom of the page with the scrollbar.

**Comment by edrmsgl** [comment]
No feedback for the PR below

https://github.com/ant-design/ant-design/pull/35526
https://github.com/ant-design/ant-design/pull/35576

**Comment by afc163** [comment]
<img width="534" alt="图片" src="https://user-images.githubusercontent.com/507615/170224367-859748f7-a9ed-46cc-b44f-7e019584c7ec.png">

**Comment by edrmsgl** [comment]
> Both pull requests is not valid.
> 
> <img alt="图片" width="534" src="https://user-images.githubusercontent.com/507615/170224367-859748f7-a9ed-46cc-b44f-7e019584c7ec.png">

Why are both requests not valid?

**Comment by edrmsgl** [comment]
What is the latest status for this issue?

**Comment by afc163** [comment]
@edrmsgl There are no valid pull requests for now.

**Comment by edrmsgl** [comment]
Why is pull request number #35526, #35576 closed?

**Comment by yoyo837** [comment]
> Why is pull request number #35526, #35576 closed?

Commits should be clean. Feel free to open a new one please.

**Comment by afc163** [comment]
<img width="462" alt="图片" src="https://user-images.githubusercontent.com/507615/173177117-c42769ef-3f9c-4bf5-aa26-477af8ecd9bd.png">

**Comment by afc163** [comment]
Hi @edrmsgl Could you follow https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/ and try again?

**Comment by edrmsgl** [comment]
Hello, I want to make a small fix for this problem. I have no idea how to solve this problem, but I am waiting for your guidance to solve this problem.

**Comment by edrmsgl** [comment]
> > Hello, I want to make a small fix for this problem. I have no idea how to solve this problem, but I am waiting for your guidance to solve this problem.
> 
> Based on your situation, maybe you can try to delete your antd fork, re-fork antd, then make some changes you want and open a new PR

I have no idea how to solve the error, I am waiting for a developer or guidance from you who can solve it

**Comment by Ahmed-AbdElMoneam** [comment]
@afc163 
Could you provide me with the steps that enable me to scroll horizontally in RTL mode?

**Comment by Ahmed-AbdElMoneam** [comment]
@yoyo837 @edrmsgl @afc163 
Is there any solution to fix RTL tables and enable scrolling sticky scrollbar horizontally?

**Comment by saeedjafari68** [comment]
This problem is related to a bug in the `rc-table` ‍‍ library that the ant design uses it.

in 7.50.1 version Problem solved.

in package.json add this property:

`"overrides": {
    "antd": {
      "rc-table": "7.50.1"
    }
 }`
