### ISSUE TITLE
The redesigned <Menu> and TypeScript 

### ISSUE THREAD

**Issue by tonywu6** [ant-design/ant-design#35473]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-4-20-0-menu-typing-1yfl99?file=/src/App.tsx)

### Steps to reproduce

Create a `<Menu>` following the first example in the documentation, **except in TypeScript**:

```tsx
// works when >=4.20.0, recommended ✅
const items = [
  { label: 'item 1' },
  { label: 'item 2' },
  {
    label: 'sub menu',
    children: [{ label: 'item 3' }],
  },
];
return <Menu items={items} />;
```

### What is expected?

The menu renders as expected and TypeScript reports no issue.

### What is actually happening?

The menu renders as expected but TypeScript complains about incorrect typing for the `items` attribute.

<img width="600" alt="Screen Shot 2022-05-10 at 7 01 39 PM" src="https://user-images.githubusercontent.com/93302820/167614332-1a070828-cf58-44aa-a4dc-973cd19bd866.png">

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 17.0.2, 18.0.0 |
| System | macOS 11.4 |
| Browser | Chrome 101 |

---
AFAIK the new Menu component no longer _strictly requires_ each item to have a key for it to render (it's still preferred). Previously there would be a warning in the console for missing key on `Menu.Item`s.

However, the provided type still requires the `key` property for the `MenuItemType` interface, which is not immediately obvious in the documentation. Furthermore, due to `ItemType` being a union of several types `MenuItemType | SubMenuType | MenuItemGroupType | MenuDividerType`, the resulting error is incredibly unhelpful:

```
No overload matches this call.
  Overload 1 of 2, '(props: MenuProps | Readonly<MenuProps>): Menu', gave the following error.
    Type '({ label: string; children?: undefined; } | { label: string; children: { label: string; }[]; })[]' is not assignable to type 'ItemType[]'.
      Type '{ label: string; children?: undefined; } | { label: string; children: { label: string; }[]; }' is not assignable to type 'ItemType'.
        Type '{ label: string; children?: undefined; }' is not assignable to type 'ItemType'.
          Property 'type' is missing in type '{ label: string; children?: undefined; }' but required in type 'MenuItemGroupType'.
  Overload 2 of 2, '(props: MenuProps, context: any): Menu', gave the following error.
    Type '({ label: string; children?: undefined; } | { label: string; children: { label: string; }[]; })[]' is not assignable to type 'ItemType[]'
```

Here,

1) `MenuItemType` and `SubMenuType`, which extends the `MenuItemType` in `rc-menu`, **do require `key` properties:**

https://github.com/react-component/menu/blob/7a4a215f1d3918151b8f9ae7d73e72ed389406a1/src/interface.ts#L39-L46

2) However, `MenuItemGroupType` and `MenuDividerType` **allow `key` to be optional** but **require the `type` property:**

https://github.com/ant-design/ant-design/blob/338ec7dad74279bdbc4e06eed280c567ffb6f029/components/menu/hooks/useItems.tsx#L25-L33

With the example in the docs, with an item with a missing `key` property, TypeScript will assume it to be of type `MenuItemGroupType | MenuDividerType`, and reports the missing `type` error instead.

---

Besides emphasizing that `key`s are required for `MenuItemType` and `SubMenuType`, preferrably the interface module should be updated so that TypeScript can report better errors. The solution I currently have is to make `ItemType` an actual **discriminated union**, meaning `title` is now required for all four types and `ItemType` is non-nullable. For example:

```tsx
interface SubMenuType {
  type: 'submenu';
  /* ... */
}
interface MenuItemType {
  type: 'item';
  /* ... */
}
interface MenuItemGroupType {
  type: 'group';
  /* ... */
}
interface MenuDividerType {
  type: 'divider';
  /* ... */
}
export type ItemType = SubMenuType | MenuItemType | MenuItemGroupType | MenuDividerType
// ItemType cannot be null anymore
```

This would help TypeScript emit a (slightly) more helpful error message mentioning `key`:

```
No overload matches this call.
  Overload 2 of 2, '(props: MenuProps, context: any): Menu', gave the following error.
    Type '{ type: "item"; label: string; }' is not assignable to type 'ItemType'.
      Property 'key' is missing in type '{ type: "item"; label: string; }' but required in type 'MenuItemType'.
  Overload 2 of 2, '(props: MenuProps, context: any): Menu', gave the following error.
    Type '{ type: "item"; label: string; }' is not assignable to type 'ItemType'.
      Property 'key' is missing in type '{ type: "item"; label: string; }' but required in type 'MenuItemType'.
```

**Comment by newtonkiragu** [comment]
@tonywu6 I'm using `"antd": "^5.17.0",` and still facing the same issue, all my menu items have keys and labels. Below is an example

```javascript
const menuItems = [
    {
      key: "1",
      label: (
        <div style={{ textAlign: "center" }}>
          <div className="menu-text">
            awesome menu text 1
          </div>
          <div className="has-text">same but in grey</div>
        </div>
      ),
    },
    {
      key: "2",
      label: <span onClick={routeChange}>View stuff</span>,
      icon: <img src="/images/stuff.png" alt="stuff icon" />,
    },
    {
      key: "5",
      label: <span onClick={() => evenMoreRouteChanges()}>more actions</span>,
      icon: <img src="/images/moreActions.png" alt="more actions icon" />,
    },
  ];

  return (
    <Dropdown
      menu={{
        items: menuItems,
      }}
      className="menu-item"
      overlayClassName="menu-dropdown"
    >
      <div>
        <Space>
         The great Divide
          <DownOutlined />
        </Space>
      </div>
    </Dropdown>
  );
```
and the warning I get

```
Type
{   items: [{     label: Element,     key: string   }, {     icon: Element,     label: Element,     key: string   }, {     icon: Element,     label: Element,     key: string   }] }
is not assignable to type MenuProps ...   Type
[{   label: Element,   key: string }, {   icon: Element,   label: Element,   key: string }, {   icon: Element,   label: Element,   key: string }]
is not assignable to type ItemType[] | undefined     Type
[{   label: Element,   key: string }, {   icon: Element,   label: Element,   key: string }, {   icon: Element,   label: Element,   key: string }]
is not assignable to type ItemType[]       Type
({   label: Element,   key: string } | {   icon: Element,   label: Element,   key: string } | {   icon: Element,   label: Element,   key: string })[]
is not assignable to type ItemType[]
```

**Comment by fmalk** [comment]
I've experienced the same issue today, after some upgrades to React 18.
Providing a `key` to every Menu `items={[... ]}` (every root and child object) solved the issue.
