### ISSUE TITLE
4.20.3 react 18 Table 设置了scroll 之后 刷新页面Empty组件一闪而过

### ISSUE THREAD

**Issue by mengbo-ji** [ant-design/ant-design#35476]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-frog-w20if5?file=/src/index.js)

### Steps to reproduce

刷新页面就会复现

### What is expected?

刷新页面Empty组件不应该出现闪现效果

### What is actually happening?

刷新页面Empty组件一闪而过

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.1.0 |
| System | MacBook Pro (Retina, 15-inch, Mid 2015) 11.4 |
| Browser | 版本 101.0.4951.54（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
复现里数据是空的

**Comment by afc163** [comment]
@MadCcc 数据就是空的，可以录个屏逐帧看 empty 闪动的情况。

**Comment by mengbo-ji** [comment]
> 复现里数据是空的

有数据或者无数据，都会出现闪现的情况😁

**Comment by yykoypj** [comment]
应该是ResizeObserver一开始还没获取到Table宽度，因为componentWidth初始值是0所以有那个跳动。
但是这个能怎么办，宽度设成100%也不对，要不componentWidth为0的时候不显示Empty了，反正也没有意义。

https://github.com/react-component/table/blob/7cb94013372f24db047e3e435cfdde08f9b9f6f6/src/Body/ExpandedRow.tsx#L40

**Comment by afc163** [comment]
@yykoypj LGTM
