### ISSUE TITLE
Modal.confirm的content里面包裹一个Radio的时候，radio切换不了值

### ISSUE THREAD

**Issue by duchaolin** [ant-design/ant-design#35470]
### Reproduction link

[http://ceshi.com](http://ceshi.com)

### Steps to reproduce

 const [gotoUnbanked, setGotoUnbanked] = useState<number>(2);

 const onChange = (e: RadioChangeEvent) =>{

    console.log('当前切换的值' e.target.value)
    setGotoUnbanked(e.target.value)

  }

  const handleDelete = (id: string, index: number) => {

    Modal.confirm({
      centered: true,
      content:
      <div>
        <Radio.Group onChange={onChange} value={gotoUnbanked}>
          <Radio value={1}>删除</Radio>
          <Radio value={2}>不删除</Radio>
        </Radio.Group>
      </div>,
      title: '确认删除',
      okText: '确认',
      cancelText: '取消',
      onOk: async () => {
        console.log(gotoUnbanked)
      },
    })

  }

### What is expected?

切换值

### What is actually happening?

不切换

| Environment | Info |
| --- | --- |
| antd | 3.26.20 |
| React | 16.14.0 |
| System | 测试 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35469#issuecomment-1122166191
