### ISSUE TITLE
Table控件rowSelection的selectedRowKeys正确使用方式？

### ISSUE THREAD

**Issue by jmz331** [ant-design/ant-design#3547]
#### 发生问题的环境是：

- antd 版本:2.1.0
- 操作系统及其版本:macOS 10.11.6
- 浏览器及其版本:chrome 54.0.2840.71 (64-bit)

#### 您做了什么？
我在使用Table的时候设置了rowSelection及其属性selectedRowKeys，虽然在初次显示的时候能正确选中对应行。但是点击其他行的radio不会改变当前选择行。

**component部分代码：**
```
const rowSelection = {
    type: "radio",
    selectedRowKeys: [1],
    onChange(selectedRowKeys, selectedRows) {
      console.log(rowSelection.selectedRowKeys, selectedRowKeys);
    }
  };
```
**控制台日志：**
```
rowSelection.selectedRowKeys： [1] selectedRowKeys: [2]
rowSelection.selectedRowKeys： [1] selectedRowKeys: [3]
```

#### 您期待的结果是：
页面初始化时Table会默认能选中一行，可以通过手动点击来改变当前选中的radio。

#### 实际上的结果是：
无法通过手动点击来更改当前选中行

**Comment by jmz331** [comment]
添加了代码演示：
http://codepen.io/anon/pen/wzNJRj?editors=0011

点击radio的话不能改变当前选中对象

**Comment by afc163** [comment]
自行研习受控组件概念：https://facebook.github.io/react/docs/forms.html#controlled-components
