### ISSUE TITLE
table排序取消点击列头就排序

### ISSUE THREAD

**Issue by heningyuan6256** [ant-design/ant-design#35488]
### What problem does this feature solve?

antd table我用react-resizable增加了列头宽度自动伸缩，为了防止出现抖动，我在拖动结束的时候才会去计算表格列的宽度，但是伸缩列头持续按住的时候容易触发表格的排序

### What does the proposed API look like?

我想把表格排序，点到列头中的图标才能排序，而不是点击列头就排序

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/ba3f84f5c5474d01d3574ffbe9fedd584b836686

文档中有这个信息。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14647
https://github.com/ant-design/ant-design/issues/15350
