### ISSUE TITLE
antd upolad   antd-img-crop   oss  data中无url

### ISSUE THREAD

**Issue by 2449847346** [ant-design/ant-design#35483]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-shaw-13gfw1?file=/src/App.js)

### Steps to reproduce

1、选择图片裁剪；
2、beforeUpload 中设定url并且开始上传
3、data钩子中添加oss所需参数包括beforeUpload中的URL

### What is expected?

beforeUpload file的url被修改，且被return；
data 中的file 有修改后的url；
onChange中的file含有修改后的url；

### What is actually happening?

beforeUpload file的url被修改，且被return；
data 中的file 无url；

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | react:"^16.13.1" |
| System | windows 10 |
| Browser | chrome 101.0.4951.54 |

---
“antd“：“4.6.1”   “antd-img-corp”:"4.2.3"  可行；
“antd“：“4.20.3”   “antd-img-corp”:"4.2.3"  无用；
“antd“：“4.6.1”   “antd-img-corp”:"3.*.*"  无用，原码没动过，但某一天突然不兼容不可用；

**Comment by zombieJ** [comment]
你的重现里有 `url`：
<img width="386" alt="截屏2022-05-11 下午2 34 36" src="https://user-images.githubusercontent.com/5378891/167783921-8f4aa776-1918-4b9b-ad3e-b45539840717.png">

**Comment by 2449847346** [comment]
> 你的重现里有 `url`： <img alt="截屏2022-05-11 下午2 34 36" width="386" src="https://user-images.githubusercontent.com/5378891/167783921-8f4aa776-1918-4b9b-ad3e-b45539840717.png">

data中无url，onChange有了，或许是我没注意；[
![M$9SDO}(NT5J%J93C7Q~OX2](https://user-images.githubusercontent.com/54257812/167785577-17331112-ce14-4980-8a30-f796adea5c9c.png)
](url)

**Comment by 2449847346** [comment]
> Hello @2449847346. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @2449847346, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

你看的是否为data 中的file ，onChange中有，或许是我没注意，但data中file是没有的
![M$9SDO}(NT5J%J93C7Q~OX2](https://user-images.githubusercontent.com/54257812/167785803-1cd1979e-032f-4e3f-b1c9-359dbdca90cc.png)

**Comment by 2449847346** [comment]
> 你的重现里有 `url`： <img alt="截屏2022-05-11 下午2 34 36" width="386" src="https://user-images.githubusercontent.com/5378891/167783921-8f4aa776-1918-4b9b-ad3e-b45539840717.png">

请问你查看的是否是data中的file ，onChange 中 有file可能是我没注意，但4.16版本的onChange是没有的；
![M$9SDO}(NT5J%J93C7Q~OX2](https://user-images.githubusercontent.com/54257812/167786060-eb495493-172a-47ca-8dae-b013958ab9d0.png)

**Comment by 2449847346** [comment]
> 你的重现里有 `url`： <img alt="截屏2022-05-11 下午2 34 36" width="386" src="https://user-images.githubusercontent.com/5378891/167783921-8f4aa776-1918-4b9b-ad3e-b45539840717.png">

@zombieJ 请问你查看的是否是data中的file ，onChange 中 有file可能是我没注意，但4.16版本的onChange是没有的；

**Comment by afc163** [comment]
最新的 4.20.3 应该 data 和 onChange 里都有 file.url

<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/168066934-9d81c6cc-ffa9-4aa0-94a9-b7e50a17e519.png">

**Comment by afc163** [comment]
最新的 4.20.3 应该 data 和 onChange 里都有 file.url

<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/168066934-9d81c6cc-ffa9-4aa0-94a9-b7e50a17e519.png">

**Comment by 2449847346** [comment]
@afc163  我所发的版本号就是4.20.3的哦，console中显示data中没有url：‘fileUrl’

**Comment by afc163** [comment]
Chome 下确实 data 里没了 url，建议先找  antd-img-crop 排查一下。
