### ISSUE TITLE
antd table能否支持range单元格选中复制粘贴至excel，或者从excel复制数据

### ISSUE THREAD

**Issue by heningyuan6256** [ant-design/ant-design#35489]
### What problem does this feature solve?

产品经理提了一个能像excel一样操作表格的功能，主要在范围选择单元格的内容实现复制和粘贴，向下填充的功能

### What does the proposed API look like?

如暂时无计划，能否给一条指引关于改造antd table，谢谢！

**Comment by afc163** [comment]
暂无计划，excel 类型的表格和 antd 表格其实是完全不同的两类组件，建议用 https://github.com/NadavShaar/react-grid-table 或 https://handsontable.com/ 来做这类需求。
