### ISSUE TITLE
The current will be reassigned in constructor() taking the smallest of the current and page max values, should this trigger the onChange event? I think it should be triggered

### ISSUE THREAD

**Issue by QiangGuZi** [ant-design/ant-design#35482]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-20-3-forked-wmuu64)

### Steps to reproduce

just click the link above and watch console window

点上面的链接，看 console 窗口

### What is expected?

Set the page number to 6, exceed the maximum page number of 5, the component should maintain the page number of 5, and trigger the onChange event

设置页码为6，超过最大页码5，组件应维护页码为 5，且触发 onChange 事件

### What is actually happening?

页面上没有页码被选中，也没有触发 onChange

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.1.0 |
| System | Mac OS 12.3.1 |
| Browser | 100.0.4896.127 (Official Build) (x86_64) |

---
本问题发现与 antd vue 社区版，经查看后发现 react 版同样存在这个问题，且存在额外的问题（或者是 feature？）。
antd vue issue 前情提要：https://github.com/vueComponent/ant-design-vue/issues/5589

极简场景：
最大页码为5，用户初始设 current 为 6，在 constructor 生命周期钩子函数中会将其 6 维护成 5，而在 getDerivedStateFromProps 中却又没有维护，又直接改回了 6。

补充：
在 antd vue 社区版本中，在组件初始化以及 props.total 更新后，都会判断 current 是否超过当前 (total, pageSize) 所能显示的最大页码，若超过，则将当前所能显示的最大页码赋值给 current。

而在 react rc-pagination中，很奇怪的一点是：
1. 初始化（construcor）的时候有同样的维护；
2. 在 props.total 更新，也就是在 getDerivedStateFromProps 钩子函数中，却缺少了对 total 变化的维护；但是该钩子函数却有对 pageSize 变化时有类似的维护。

翻阅了当前 open 的 issue，未曾找到有其他人提出这个问题。我猜想是因为 getDerivedStateFromProps 的未维护，导致大家认为这可能一个 feature

疑问：
1. constructor 与 getDerivedStateFromProps 对 current 的维护行为不一致，这是符合预期的吗？
2. getDerivedStateFromProps 中 pageSize 改变会有类似维护，total 改变没有类似维护，这应该是漏了？
3. getDerivedStateFromProps 中 pageSize 维护时还要判断 current 是否在 props 中：若是，则维护中止，这是故意的吗？保持用户原输入？

重复预期：
在 total、pageSize 改变时，若原 current 已超出当前最大页码，则 current 取当前最大页码，并触发 onChange 事件，帮助用户更新正确数据。

其他：
1. 若前辈认同我上述所提出的问题，那么可以由我来提这个 PR 吗？（喜欢 antd 很久很久了，有机会希望能做出自己的一些贡献）
2. 基于我当下的理解，对 rc-pagination 进行了一些改动，截图待会放在 2 楼

**Comment by zombieJ** [comment]
**受控**状态数据不应该触发 `onChange` 事件。新版是符合预期的行为。同样的 InputNumber 如果**受控**设置超出 `min` `max` 、Form 通过 `setFieldsValue` 也不会触发 `onChange` 事件。

在 antd 中，过去有部分组件没有遵循受控值为 single source of truth 的原则。使得输入组件在 value 受控下自动转成“合理”的数值并且触发 `onChange` （或者类似事件）。但是如果当开发者没有处理 `onChange` 事件时，就会导致受控值和实际展示值不一致的问题。在表单页面如果使用受控且不处理 onChange 的方式，就会发生可见值与提交值不一致的问题。
在 Pagination 中，如果受控值超出范围，同时开发者自己对列表做 slice 也会存在不一致的情况。所以不会去自动切割，都会以受控值为准。
