### ISSUE TITLE
[Tree]blockNode 属性的显示效果不符合预期

### ISSUE THREAD

**Issue by kkkisme** [ant-design/ant-design#35484]
### Reproduction link

[https://stackblitz.com/edit/react-lwhf88?file=demo.js](https://stackblitz.com/edit/react-lwhf88?file=demo.js)

### Steps to reproduce

打开链接，鼠标随意悬浮或选择节点

### What is expected?

https://semi.design/zh-CN/navigation/tree

semiDesign的blockNode 默认为true ，可直接查看效果

### What is actually happening?

antd的Tree组件 的blockNode  并没有高亮一整行

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 17 |
| System | windows 11 |
| Browser | Chrome 101 |

**Comment by kkkisme** [comment]
![image](https://user-images.githubusercontent.com/18638401/167755270-4c758dee-7a5f-4c06-a694-c4851faf3b9e.png)
![image](https://user-images.githubusercontent.com/18638401/167755322-62a8a66b-8abb-4b7e-8a07-038221400979.png)

**Comment by afc163** [comment]
你可能需要 https://ant.design/components/tree-cn/#components-tree-demo-directory
