### ISSUE TITLE
List Item component is missing 'extra' property

### ISSUE THREAD

**Issue by gunslinger23** [ant-design/ant-design#35485]
### Reproduction link

[https://github.com/ant-design/ant-design/commit/1d3fd70dbf8e4798b3cff4269080426b5d97bce0](https://github.com/ant-design/ant-design/commit/1d3fd70dbf8e4798b3cff4269080426b5d97bce0)

### Steps to reproduce

We should tag new version to public the patch 1d3fd70dbf8e4798b3cff4269080426b5d97bce0

##### Example code

```ts
<List.Item
  key={map.map_id}
  className={styles.list}
  extra={
    <Tooltip className={styles.datetime} title={lastTime}>
      {lastTimeFromNow}
    </Tooltip>
  }
>
```

```
error TS2322: Type '{ children: Element[]; key: number; className: any; extra: any; }' is not assignable to type 'IntrinsicAttributes & ListItemMetaProps & RefAttributes<HTMLElement>'.
  Property 'extra' does not exist on type 'IntrinsicAttributes & ListItemMetaProps & RefAttributes<HTMLElement>'.

29           extra={
             ~~~~~
```

### What is expected?

tsc build success

### What is actually happening?

tsc build failed

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.1.0 |
| System | any |
| Browser | any |

**Comment by MadCcc** [comment]
We will publish a new patch today。
