### ISSUE TITLE
InputNumber 联合 Form 表单 onblur时 返回的值不正确 

### ISSUE THREAD

**Issue by promiseLC** [ant-design/ant-design#35493]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-20-3-forked-4y3ydn?file=/demo.js)

### Steps to reproduce

输入框 输入1,失去焦点时打印为1,  把1删除,失去焦点打印应该为null,但是打印的还是1

### What is expected?

onBlur打印应该为null

### What is actually happening?

打印的还是1

| Environment | Info |
| --- | --- |
| antd | 4.15.1 |
| React | 17.0.1 |
| System | macos |
| Browser | Chrome 101 |

**Comment by afc163** [comment]
现在删除到空后还不会触发 onChange，只有 blur 后才会触发。你可以试试给 Form.Item 触发 `trigger="onInput"` 事件。

**Comment by promiseLC** [comment]
完美解决,这个算是bug么? 我看4.20.3已经解决了

**Comment by afc163** [comment]
确实已解决，那我的解法不科学了：https://codesandbox.io/s/ji-ben-shi-yong-antd-4-20-3-forked-so7vhu?file=/demo.js
