### ISSUE TITLE
List.Item 和 List.Item.Meta 上无 onClick 的Ts定义

### ISSUE THREAD

**Issue by jianhuagao** [ant-design/ant-design#35497]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

组件<List.Item/> 无onclick定义 但onclick生效  以前是可以的

### What is expected?

有onclick定义 onclick生效

### What is actually happening?

无onclick定义 onclick生效

![Snipaste_2022-05-11_17-52-48](https://user-images.githubusercontent.com/39371828/167822821-e7d3d793-6ff6-473d-b85d-e4bc4fda137a.jpg)

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.1.0 |
| System | Windows10 |
| Browser | Microsoft Edge 100.0.1185.50 (正式版本) (64 位) |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35455

**Comment by arashchepkin-star** [comment]
Wasn't fixed for List.Item.Meta @afc163
