### ISSUE TITLE
List.Item onClick typescript error

### ISSUE THREAD

**Issue by dominikspiertz** [ant-design/ant-design#35496]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-noyce-wj9fsi?file=/src/App.tsx)

### Steps to reproduce

- Open App.tsx
- See error for onClick when used on List.Item

### What is expected?

The List.Item should accept the onClick method when using typescript.

### What is actually happening?

An error is shown that onClick does not exist inside the interface of ListItemMetaProps. The event itself is working when disabling type checks

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.1.0 |
| System | MacOS 12.3.1 |
| Browser | Safari 15.4 (17613.1.17.1.13) |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35455
