### ISSUE TITLE
Select组件，当导入 'react-hot-loader/patch'时就会报错

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#3550]
- antd 版本:2.1.0
- 操作系统及其版本:window
- 浏览器及其版本:chrome
  当我使用react-hot-loader3的时候，入口文件中导入 'react-hot-loader/patch'
  import  'react-hot-loader/patch'
  所有引用Select组件的地方就会报这个错：
  Warning: the children of `Select` should be `Select.Option` or `Select.OptGroup`, instead of `Option`.
  我去掉'react-hot-loader/patch‘就好了不知道怎么回事，反复检查没发现原因

**Comment by Ben07** [comment]
找到原因了吗？

**Comment by smile21** [comment]
+1

**Comment by afc163** [comment]
和 Table.Column 的判断是一样的？

**Comment by yesmeck** [comment]
react-hot-loader 会用 react-proxy 改掉原来的组件对象，要想想怎么搞。

**Comment by yesmeck** [comment]
有人提了 https://github.com/gaearon/react-hot-loader/issues/304

**Comment by yesmeck** [comment]
有 Hack 的办法，不过感觉这是 react-hot-loader 的问题。

**Comment by yesmeck** [comment]
hack 的办法比较搓：

```javascript
// 给 Option 自定义个 `__name`
Option.__name = 'rc-select-option'
```

后面要比较的地方用这个`__name`做比较。

**Comment by yesmeck** [comment]
displayName 太容易冲突了。

**Comment by zation** [comment]
其实冲突的可能性很小，只有当谁用了 rc-select-option 并且还传给 Antd 的 Select 或者 Tree 组件了才会出问题

**Comment by benjycui** [comment]
`displayName` 不推荐 https://github.com/facebook/react/issues/4915#issuecomment-162729355

**Comment by benjycui** [comment]
开发环境各工具之间难免有冲突，我不认为这个问题能够解决，而且不影响到生产环境，也还好。

> 一堆warning。有点烦人

这个可以像 antd 这样，限制每个 warning 只会显示一次。

**Comment by supnate** [comment]
Any update on this? Though it's not good to ask so but this is a very critical issue. It's not just warnings for `Select` but it doesn't work at all for `Tree` (#4404). This issue prevents people from using antd with Webpack and RHL which is very popular for React development.

I understand it's more like an issue of RHL. But it's just how RHL works. I don't think it could be resolved by RHL itself. And, high order component concept is widely accepted for React so `element.type` seems not to be reliable for type detection even without RHL. As I see there is `isTreeNode` property for `TreeNode` component, this could be workaround  for other scenarios.

**Comment by benjycui** [comment]
> As I see there is isTreeNode property for TreeNode component, this could be workaround for other scenarios.

It seems that there is no better way...

**Comment by yesmeck** [comment]
给 react-proxy 提了个 issue https://github.com/gaearon/react-proxy/issues/68

**Comment by yesmeck** [comment]
Traced in #4655.
