### ISSUE TITLE
feat: allow passing default values in useForm

### ISSUE THREAD

**Issue by andreas-soroko** [ant-design/ant-design#35501]
### What problem does this feature solve?

Hi,

we have (in our opinion) small feature request):
It would be really nice if we could provide `initialValues` with `useForm` hook.

Imagine we have a component like: 

```tsx
const DEFAULT_ORDERBY = 'newest'

export function Inbox() {
  const [form] = Form.useForm<{
    orderBy: string
    sinceDateTime: moment.Moment | null
    beforeDateTime: moment.Moment | null
  }>()
  const orderBy = Form.useWatch('orderBy', form) ?? DEFAULT_ORDERBY
  const sinceDateTime = Form.useWatch('sinceDateTime', form)
  const beforeDateTime = Form.useWatch('beforeDateTime', form)

  // some logic here...

  useEffect(() => {
    console.log(orderBy)
  }, [orderBy])

  return (
    <Form form={form} initialValues={{ orderBy: DEFAULT_ORDERBY }} layout="inline">
      <Form.Item label="From" name="sinceDateTime">
        <DatePicker showTime />
      </Form.Item>
      <Form.Item label="To" name="beforeDateTime">
        <DatePicker showTime />
      </Form.Item>
      <Form.Item label="Order By" name="orderBy">
        <Select>
          <Select.Option value="newest">Newest</Select.Option>
          <Select.Option value="oldest">Oldest</Select.Option>
          <Select.Option value="priority">Highest Priority</Select.Option>
          <Select.Option value="priorityInv">Lowest Priority</Select.Option>
        </Select>
      </Form.Item>
    </Form>
  )
}
```

Currently we have to provide the default value at  `<Form form={form} initialValues={{ orderBy: DEFAULT_ORDERBY }} layout="inline">` but on the first render, the value is undefined;
so the useEffect will be triggered twice
our workaround: `Form.useWatch('orderBy', form) ?? DEFAULT_ORDERBY` also adding here a default value... 
that feels a bit uncompleted.

Thanks and have a nice day :) 

PS: I already created here an issue https://github.com/react-component/field-form/issues/434 but after 5 days no one reacted and the when i look into the other issues, it looks like no one is really looking there into the issues.

If i am wrong, just close it :) 

### What does the proposed API look like?

The complete flow would be more straight forward if we could define on `useForm` already the default values: 

```ts
const [form] = Form.useForm<{
    orderBy: string
    sinceDateTime: moment.Moment | null
    beforeDateTime: moment.Moment | null
  }>({orderBy: DEFAULT_ORDERBY, sinceDateTime: null, beforeDateTime: null})
```

**Comment by crazyair** [comment]
useWatch 获取的是字段注册后的值，而不是 initialValues 的值

**Comment by zombieJ** [comment]
Thanks for feedback. But Form `initialValues` is designed as single source of truth. We may not modify this to avoid conflict.

**Comment by andreas-soroko** [comment]
Hi, 
don't see conflict potential here. It's more a question about the design or?

1. you have the possibility to use the `Form` (which will create a `form` instance) and fill the`initialValues` from the prop to the instance and the `onValuesChange` handler to archive something similar with some other overhead 
2. you can create the form outside (`Form.useForm`), pass it to `Form` and use `useWatch` to get the values from, but without the `initialValues` in first render cycle
`useForm` should logically allow setting the default values from the beginning.

I would expect from the data flow that `useForm` (or any initialization of the `form` instance) would allow passing in the defaults and the `Form` component is just using them.

If someone defines something like 
```tsx
const DEFAULT_ORDERBY = 'newest'

export function Inbox() {
  const [form] = Form.useForm<{
    orderBy: string
    sinceDateTime: moment.Moment | null
    beforeDateTime: moment.Moment | null
  }>({orderBy: DEFAULT_ORDERBY, sinceDateTime: null, beforeDateTime: null})

  // ....

  return (
    <Form form={form} initialValues={{ orderBy: 'oldest' }}>
       ....
    </Form>
  )
}
```
I would expect that the `initialValues` on the `Form` will be ignored, because he already got a `form` that has already `initialValues`

**Comment by zombieJ** [comment]
Thanks for feedback. Actually Form level `initialValues` is designed as top priority. Form do not need pass `form` props if you do not need interactive with it:
```tsx
const Demo = () => {
  const onFinish = () => {};

  return (
    <Form onFinish={onFinish}>
      ...
    </Form>
  );
};
```

For your requirement. You can wrap the useForm to customize `initialValues`:
```tsx
function useForm<T>(initialValues: T) {
  const [form] = Form.useForm<T>();

  React.useEffect(() => {
    form.setFieldsValue(initialValues);
  }, []);

  return [form];
}
```

We do not want to make it confuse sine when the FormInstance also enable set `initialValues` developers must confuse about which one is the single source of truth. In your case may think useForm is the first priority but in another case maybe follow the  Form `initialValues`. 2 way for setup root `initialValues` is not good design.

In addition, hooks should be stable but Form node do not need exist in the tree:
```tsx
const Demo = ({ id }) => {
  const [userData, setUserData] = useState();
  const [form] = Form.useForm(userData); // Is the time to take `undefined` as initialValue? `initialValues` should setup only when Form render. In other time, you can not tell when form instance to take params as `initialValues`

  useEffect(async () => {
    const data = await fetchData();
    setUserData(data);
  }, [id]);

  return userData ? <Form /> : null;
};
```
