### ISSUE TITLE
antd table表格编辑还原了上次修改的cell

### ISSUE THREAD

**Issue by superw-123** [ant-design/ant-design#35503]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6ur776?file=/index.js)

### Steps to reproduce

第一行的字段描述中输入aaa，第二行的字段描述中输入bbb，第一行的字段描述被清空

### What is expected?

第一行aaa不要清空

### What is actually happening?

第一行的字段描述aaa被清空

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | 17.0.1 |
| System | mac catalina 10.15.5 |
| Browser | chrome 97.0.4692.99（正式版本） (x86_64) |

**Comment by solitia7125** [comment]
闭包问题

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)

**Comment by superw-123** [comment]
> 闭包问题
> 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)

为什么只能一个字段使用shouldCellUpdate？

**Comment by superw-123** [comment]
> 闭包问题
> 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)

数据集字段展示名 该列使用shouldCellUpdate，输入没有生效

**Comment by superw-123** [comment]
> 闭包问题
> 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)



> 闭包问题
> 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)

表格中的数据编辑后是要传到上层组件中的，但是这里的datasource并没有改变

**Comment by superw-123** [comment]
> 闭包问题
> 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)


闭包问题

Edit on CodeSandbox

闭包问题

Edit on CodeSandbox

表格中的数据编辑后是要传到上层组件中的，但是这里的datasource并没有改变，这么解决有什么作用呢

**Comment by solitia7125** [comment]
没有改变 是因为record的值为"",参数从`(record)`=>`(text, record)`就行

但还有其它问题
debug下了 好像底层的Cell组件有问题

```
# 描述字段的shouldCellUpdate
# 看起来我们要控制更新的话, 需要判断两个记录的值不同
shouldCellUpdate: (record, prev) => {
  console.log(record.description);
  return record.description !== prev.description;
}
```

但是实际DEBUG发现 两个参数的值是相同的 @afc163 
![image](https://user-images.githubusercontent.com/39177579/168053652-34e14352-79e0-4711-9ac1-84b293af63b9.png)
![image](https://user-images.githubusercontent.com/39177579/168053670-cd7ae1cd-5781-4eb2-a986-630a3bf7eaad.png)

**Comment by superw-123** [comment]
> 但还有其它问题
> debug下了 好像底层的Cell组件有问题

demo中还是问题多多，对于已经存在的字段值，编辑时输入和删除都不好用，我再另想其他方法解决表格编辑性能问题吧

**Comment by lius14** [comment]
> > 闭包问题
> > [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)
> 
> 闭包问题
> 
> Edit on CodeSandbox
> 
> 闭包问题
> 
> Edit on CodeSandbox
> 
> 表格中的数据编辑后是要传到上层组件中的，但是这里的datasource并没有改变，这么解决有什么作用呢

遇到同样的问题，请问数据编辑，但dataSource未更新解决了吗？

**Comment by solitia7125** [comment]
> > > 闭包问题
> > > [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-8mbsnn)
> > 
> > 
> > 闭包问题
> > Edit on CodeSandbox
> > 闭包问题
> > Edit on CodeSandbox
> > 表格中的数据编辑后是要传到上层组件中的，但是这里的datasource并没有改变，这么解决有什么作用呢
> 
> 遇到同样的问题，请问数据编辑，但dataSource未更新解决了吗？

如果是跟题主相同的问题，以前说的这个应该早就修复更新了
