### ISSUE TITLE
Upload选择大量文件后，onChange被触发了，但是页面的任何事件修改state都不会重新渲染页面

### ISSUE THREAD

**Issue by ChenYu29** [ant-design/ant-design#35509]
### Reproduction link

[https://github.com/ChenYu29/forIssue](https://github.com/ChenYu29/forIssue)

### Steps to reproduce

1、点击上传图片，选择多张图片（为了能让加载过程体现长一点）
2、设置loading，Spin加载中

### What is expected?

上传图片的文件选择对话框关闭后页面显示loading

### What is actually happening?

在文件读取加载过程页面无任何响应，loading的值有改变但是页面无更新渲染

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | react |
| System | Windows 10 |
| Browser | 谷歌 101.0.4951.54 |

**Comment by zombieJ** [comment]
https://github.com/ChenYu29/forIssue/blob/4a09442b9c4c2091ae928dfe63362b4a3e5a645e/src/upload/UploadIndex.tsx#L31
你返回 false 后就不会管上传了。

ref：https://ant.design/components/upload-cn/#components-upload-demo-upload-png-only

**Comment by ChenYu29** [comment]
> https://github.com/ChenYu29/forIssue/blob/4a09442b9c4c2091ae928dfe63362b4a3e5a645e/src/upload/UploadIndex.tsx#L31 你返回 false 后就不会管上传了。
> 
> ref：https://ant.design/components/upload-cn/#components-upload-demo-upload-png-only

因为我是设置的手动上传，先显示文件列表再统一上传。这个是没有影响的
