### ISSUE TITLE
Tree Component not draggable on Android Devices

### ISSUE THREAD

**Issue by marioagarcia** [ant-design/ant-design#35506]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/draggable-antd-4-20-4-forked-b1y05x)

### Steps to reproduce

Attempt to drag any of the tree nodes

### What is expected?

The node will highlight and move 

### What is actually happening?

The leaf node is highlighting but not moving

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 16.14.0 |
| System | Android 11 |
| Browser | Chrome |

**Comment by afc163** [comment]
Sorry, antd component is not designed for dragging in mobile device.
