### ISSUE TITLE
modal 自定义 modalRender 点击蒙层无法关闭

### ISSUE THREAD

**Issue by suiboyu** [ant-design/ant-design#35512]
### Reproduction link

[https://codepen.io/suiboyu/pen/mdXrVdP?editors=0010](https://codepen.io/suiboyu/pen/mdXrVdP?editors=0010)

### Steps to reproduce

1. 点击按钮打开对话框
2. 点击蒙层，无法关闭

### What is expected?

点击蒙层，对话框消失

### What is actually happening?

点击蒙层，无法关闭

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.10.2 |
| System | mac 11.5.1 |
| Browser | 101.0.4951.64 |

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/KKQgVae?editors=0010

**Comment by A-birdFlyHigner** [comment]
style={{ pointerEvents: 'auto' }}

**Comment by RH-Xie** [comment]
尝试一下maskClosable设为true。（一般默认值也为true，但使用modalRender后似乎需要手动设置）
```tsx
<a 
  href="#/" 
  onClick={() => Modal.info({
    maskClosable: true, 
    modalRender: () => <img alt="" src="https://picsum.photos/200/300" />
  })}
>图片示例</a>
```
AntD版本4.16.11
