### ISSUE TITLE
Render Menu.Item with customised renderer

### ISSUE THREAD

**Issue by HualiangLI** [ant-design/ant-design#35510]
### What problem does this feature solve?

We are composing Menu with routers.

The menu nodes were generated with a node mapper recursively. And after `v4.20`, it is suggested to use items property to achieve a better performance.

It is amazing that there's a feature for performance improvement, but according to the api references, it looks like Menu nodes with link child cannot be generated with `Menu.props.items`. Hence, we cannot generate a menu node which navigate  to a page or link easily. We'll have to handle the `onSelect` callback to find the nodes' bind link recursively, then use `history.push` to open it.

Based on this, we suggest to add a customised render property for `items`.

### What does the proposed API look like?

For `ItemType` in Menu component, add a property like `render` to render customized nodes under `li.ant-menu-item`.

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by MadCcc** [comment]
You could pass ReactNode to `label`

**Comment by HualiangLI** [comment]
> You could pass ReactNode to `label`

Thanks. It works!!!

**Comment by HualiangLI** [comment]
> What does the proposed API look like?

@MadCcc provided a perfect way to achieve my requirement. 
There's no need to add new api. But still appreciate your reply.
