### ISSUE TITLE
File status doesn't update in render (react18   antd20)

### ISSUE THREAD

**Issue by LeopoldAssogbaA** [ant-design/ant-design#35517]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-upload-reproduce-forked-t4p5o2)

### Steps to reproduce

upload the file

### What is expected?

First, we upload the file with the dialog window.
The onChange(info) function is triggered a first time with the info.file.status state set to "uploading".
The onChange function is triggered a second time with the info.file.status state set to "done".
Then we process the file 

### What is actually happening?

The onChange(info) function is triggered only one time with the info.file.status state set to "uploading" 

The file state is not updated in the state/render and the onChange function is not triggered a second time

the file is not process. 

PS: It doesnt work since we updated react version to 18  and the antd version to 20  version.

Thanks for your work :)

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | react 18 |
| System | mac os |
| Browser | chrome |

**Comment by zombieJ** [comment]
What's `customRequest` in your real case?  Seems upload file may not sync in real world:

https://codesandbox.io/s/antd-upload-reproduce-forked-nrsdzy?file=/src/App.js:1251-1264

**Comment by LeopoldAssogbaA** [comment]
Thanks for your response, I did the logic in the handleChange function, I just triggered the onSuccess() at the end of the process. I will update this and do the logic in the customRequest function.

**Comment by lostintheway** [comment]
how did u fix it? need help
