### ISSUE TITLE
官方国内镜像 服务器配置错误，链接刷新404

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design#35511]
### Reproduction link

[https://ant-design.antgroup.com/docs/spec/introduce-cn](https://ant-design.antgroup.com/docs/spec/introduce-cn)

### Steps to reproduce

直接访问一下链接 404，对应的事 官方国内镜像的 设计，文档和资源模块下的链接；正常点击可以访问，刷新或直接打开URL，则4004；
类似 Nginx 的  try_files 没有配置；

[https://ant-design.antgroup.com/docs/spec/introduce-cn](https://ant-design.antgroup.com/docs/spec/introduce-cn)
[https://ant-design.antgroup.com/docs/react/introduce-cn](https://ant-design.antgroup.com/docs/react/introduce-cn)
[https://ant-design.antgroup.com/docs/resources-cn](https://ant-design.antgroup.com/docs/resources-cn)

### What is expected?

刷新或直接访问也能看到正常的页面

### What is actually happening?

实际上由于 404

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 17 |
| System | Windows 10 |
| Browser | Edge/101.0.1210.39 |

**Comment by MadCcc** [comment]
已解决
