### ISSUE TITLE
Menu菜单导航支持后端渲染吗？

### ISSUE THREAD

**Issue by machao23** [ant-design/ant-design#3551]
https://ant.design/components/menu/ 第1个例子后端渲染会报错
![image](https://cloud.githubusercontent.com/assets/5095336/19640208/3f01e580-9a0e-11e6-84d8-29539381151a.png)

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/menu/pull/56

**Comment by machao23** [comment]
@afc163 不好意思，请问类似这种依赖库的版本问题，要怎么修复？

**Comment by afc163** [comment]
如果你现在用了 babel-plugin-import ，重新安装 antd 即可。
