### ISSUE TITLE
请问，能开放下MonthPanel的props.contentRender接口（MonthTable）吗？

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#3553]
![image](https://cloud.githubusercontent.com/assets/1686808/19643450/f903139c-9a1c-11e6-890a-4dec6e699fb4.png)

我想实现如图中的效果，给特定的月份带上一个提醒的dom

**Comment by benjycui** [comment]
我们这边展示没有这个需求，可以 PR。

**Comment by benjycui** [comment]
涉及层级比较多，需要从 rc-calendar 改起。

**Comment by wufeng87** [comment]
ok，我抽时间试试PR

**Comment by wufeng87** [comment]
https://github.com/react-component/calendar/pull/170

**Comment by benjycui** [comment]
你可以给 antd 来个 PR，升级依赖并更新对应的文档 https://github.com/react-component/calendar/commit/b36478a730fff38f55ac6f2a3195daa324ccd8d3

**Comment by yesmeck** [comment]
Released in 2.3.0.
