### ISSUE TITLE
Menu导航菜单,单击事件携带节点自定义属性

### ISSUE THREAD

**Issue by gamemock** [ant-design/ant-design#35533]
### What problem does this feature solve?

背景：
1. Menu组件的onClick事件，其中包含了item属性，根据item的props可以获得自定义的属性，**_但是控制台有警告，将被移除_**；
2. 随后我通过在渲染每个MenuItem时增加onClick，并注入自定的属性，可以获得自定义属性。**_但在4.20 版本中再次警告，MenuItem将被移除_**；

使用场景：
1. 官方的AntDesignPro只提供了单页面版本的实现，业务功能需求多页签版本。为了实现多页签，且可配置渲染组件或iframe。针对MenuItem的点击事件进行了深度定制。具体的demo可参考我实现的一个多页签版本的AntDesignTabs。https://github.com/gamemock/ant-design-tabs

### What does the proposed API look like?
1. 保留Menu的Onclick事件中的item
2. 提供额外的方式获得节点的额外属性

例子：
下面是一段摘自官方的示例代码
```
const items = [
    { label: '菜单项一', key: 'item-1', title: '嘿哈', **extraAttr: '这是我自定义的'**}, // 菜单项务必填写 key
    { label: '菜单项二', key: 'item-2' },
    {
      label: '子菜单',
      key: 'submenu',
      children: [{ label: '子菜单项', key: 'submenu-item-1' }],
    },
  ];

  return (
    <Menu
      mode='inline'
      items={items}
      onClick={e => console.log(e)} **#希望在点击事件中，能够方便的获得extraAttr**
    />
  );
```

**Comment by MadCcc** [comment]
`{ label: '菜单项一', key: 'item-1', title: '嘿哈', **extraAttr: '这是我自定义的'**, onClick: () => {}}, // 菜单项务必填写 key`
`onClick` 可以给 items

**Comment by gamemock** [comment]
> ```
> { 
>   label: '菜单项一', 
>   key: 'item-1', 
>   title: '嘿哈', 
>   **extraAttr: '这是我自定义的'**, 
>   onClick: () => {}
> },
> ```
> 
> `onClick` 可以给 items

那还需要我再根据点击传入的key，去items里查询出需要的属性。 如果只是一个list还好，树形结构每次点击的时候 都去查询，似乎不太合适吧

**Comment by gamemock** [comment]
> ```
> { 
>   label: '菜单项一', 
>   key: 'item-1', 
>   title: '嘿哈', 
>   **extraAttr: '这是我自定义的'**, 
>   onClick: () => {}
> },
> ```
> 
> `onClick` 可以给 items

大概明白了，就是原先我拼的是MenuItem，现在直接拼一个json对象，这个对象里的onClick仍然可以自定义的，谢谢
