### ISSUE TITLE
Select 设置自定义后缀图标，设置suffixIcon不起作用

### ISSUE THREAD

**Issue by wave1998** [ant-design/ant-design#35534]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-uc925k?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

<Select
      placeholder="请选择"
      style={{ width: "400px" }}
      mode="tags"
      tokenSeparators={[";", "；", "\r\n"]}
      suffixIcon={<Button type="link">批量上传</Button>}
    />

### What is expected?

出现自定义的按钮后缀

### What is actually happening?

自定义后缀图标并没有显示出来

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17.0.2 |
| System | windows10 |
| Browser | chrome |

**Comment by wave1998** [comment]
![image](https://user-images.githubusercontent.com/46206982/168218303-0b62ec09-4e08-4a4f-9cd6-a12858e63f17.png)

**Comment by solitia7125** [comment]
可以临时加个`showArrow` prop

好像在mode="tags"时 不会显示
