### ISSUE TITLE
cascader dropdownRender 中有 input 时，删除input中的数据下拉框会自动收起

### ISSUE THREAD

**Issue by qiphon** [ant-design/ant-design#35540]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-20-4-forked-8hw1ej?file=/demo.js)

### Steps to reproduce

- 在下拉框中的input中输入数据
- 然后再按下删除键
- 下拉展示就收起了。。。

### What is expected?

希望可以不会在按删除键的时候下拉选项收起

### What is actually happening?

额。。。。

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 17 |
| System | mac lasted |
| Browser | Chrome lasted |

**Comment by solitia7125** [comment]
看起来是事件冒泡
我加了这个就不会收起
`onKeyDown={(event) => event.stopPropagation()}`

**Comment by qiphon** [comment]
是的，我也是这么处理的。但是这个组件为什么会监听键盘事件呢？

**Comment by zhenzhenChange** [comment]
> 是的，我也是这么处理的。但是这个组件为什么会监听键盘事件呢？

我记得`Cascader`组件是基于`Select`组件的，在多选模式下可以按删除键删除

**Comment by solitia7125** [comment]
> 是的，我也是这么处理的。但是这个组件为什么会监听键盘事件呢？

onKeyDown是全局事件肯定会有，不过底层做了处理。

![image](https://user-images.githubusercontent.com/39177579/168257309-e3d28166-3330-4f88-b1da-6cfb47784ac4.png)
![image](https://user-images.githubusercontent.com/39177579/168257361-989f6ba8-718b-4f26-acab-d6832e83142e.png)

**Comment by qiphon** [comment]
> > 是的，我也是这么处理的。但是这个组件为什么会监听键盘事件呢？
> 
> onKeyDown是全局事件肯定会有，不过底层做了处理。
> 
> ![image](https://user-images.githubusercontent.com/39177579/168257361-989f6ba8-718b-4f26-acab-d6832e83142e.png) ![image](https://user-images.githubusercontent.com/39177579/168260071-3d0dab24-c96e-46e8-970e-b21351412fa3.png) ![image](https://user-images.githubusercontent.com/39177579/168260329-f1c30d9c-d40d-40fd-86ae-75d622305a4a.png) ![image](https://user-images.githubusercontent.com/39177579/168260655-36e62894-0dbf-4f10-a1d9-370c1ec4df3d.png)

好的，感谢
