### ISSUE TITLE
Updates to Row are breaking aria-based queries

### ISSUE THREAD

**Issue by gtb104** [ant-design/ant-design#35549]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nby9ow)

### Steps to reproduce

Create a <Row> that has a nested <table> with a header and two rows.

Write an assertion using React Testing Library's role based query:  `getAllByRole('row')`

### What is expected?

I expect there to be three rows (the table header, and the two body rows).

### What is actually happening?

I'm getting four DOM elements because the <Row> has the attribute `role="row"`

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | React 17 |
| System | OSX 12.3.1 |
| Browser | All |

---
I don't think the addition of an aria role should have been added. The pull request where this was added is https://github.com/ant-design/ant-design/pull/35409/files#diff-24039ff6148d169a887fe30e0328a9c8336c49bf909b8a355c128510dac4c7ea.

The docs for the aria role `row` state: "_An element with role="row" is a row of cells within a tabular structure_". My believe is that `Row` and `Col` are not tabular data, they are layout. Therefore, they should not be applied to this use case.

**Comment by afc163** [comment]
cc @KAROTT7

**Comment by bartpio** [comment]
Also, the `row` and `col` aria roles on `Row` and `Col` make it difficult to comply with _aria-required-parent_. [Docs](https://www.w3.org/TR/wai-aria-1.1/#row) state:

> Authors MUST ensure elements with role `row` are contained in, or owned by, an element with the role `table`, `grid`, `rowgroup`, or `treegrid`.

**Comment by KAROTT7** [comment]
@afc163 哥，我错了，之前消息提醒被我乱设置，@提醒关了，加上我前段时间刚好工作忙。
