### ISSUE TITLE
Tabs not scrolling horizontally if inside a flex container since version 4.20.0

### ISSUE THREAD

**Issue by ruimarques** [ant-design/ant-design#35548]
### Reproduction link

[https://stackblitz.com/edit/react-ypbav8](https://stackblitz.com/edit/react-ypbav8)

### Steps to reproduce

Place the tabs component, inside a container with "display flex", with enough tabs that it should scroll.

It will not scroll, you can toggle "display flex" on/off to see the difference.

This regression seems to be introduced in 4.20.0 and still not working at 4.20.4.
This issue does not happen in version 4.19.5

### What is expected?

Tabs should scroll correctly inside a flex container.

### What is actually happening?

Tabs do not scroll when placed inside a flex container.

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | Tested with React 16 / 18 |
| System | OSX |
| Browser | Chromium Version 98.0.4753.0 |

**Comment by solitia7125** [comment]
You can add styles `overflow: 'hidden'` to the tabs component, it seems to have been removed with `.ant-tabs` in 4.20.0.

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-ypbav8-oibvgk?file=demo.js

https://stackoverflow.com/a/31972181/3040605
