### ISSUE TITLE
Badge显示异常，空心红圈数字显示为实心红点，如图

### ISSUE THREAD

**Issue by oillamp** [ant-design/ant-design#3554]
Badge 显示异常，红圈数字 显示为 实心红点

#### 发生问题的环境是：

- antd 版本:
"antd": "^2.1.0"
- 操作系统及其版本:
win 7 64位
- 浏览器及其版本:
chrome 25.0.1364.152

#### 您做了什么？

使用badge控件，
#### 您期待的结果是：

期望红圈里面显示数字，(在上面的环境下，官网示例也显示异常)

#### 实际上的结果是：

气泡显示为实心红点，hove弹出的数字正常

![f09a2a61cc6454a42cb2593740c3c34f](https://cloud.githubusercontent.com/assets/14213113/19643553/7a89ae30-9a1d-11e6-811f-4858796f1261.png)

**Comment by afc163** [comment]
chrome 25 ？

版本太老了吧

**Comment by oillamp** [comment]
enen 确实是比较老了

**Comment by oillamp** [comment]
上面图里， 临界值(99+)显示正常，我想是不是还有可能支持上， 哈哈

**Comment by afc163** [comment]
我们不太可能对这么老的版本进行支持了，调试环境都找不到。

如果你很急切需要改动，建议自己本地看看能否修复，然后给我们 PR 吧。
