### ISSUE TITLE
Need to show extra button in Menu List

### ISSUE THREAD

**Issue by Aravin** [ant-design/ant-design#35550]
### What problem does this feature solve?

Expected 
1: https://pasteboard.co/va1ulhYJGXL7.png
2: https://pasteboard.co/QjRCuSnJMkl0.png

I wanted to show extra button in Menu List - so that user can click on text or button

clicking on text,  will redirect to List View
clicking on button, will redirect to Add Item view.

### What does the proposed API look like?

Expected 
1: https://pasteboard.co/va1ulhYJGXL7.png
2: https://pasteboard.co/QjRCuSnJMkl0.png

**Comment by afc163** [comment]
`label` could be a ReactNode.
