### ISSUE TITLE
Option to keep a menu in full-width

### ISSUE THREAD

**Issue by marek-hanzal** [ant-design/ant-design#35554]
### What problem does this feature solve?

So, when I put AntD menu into PageHeader's extra, it's shrinked (some of items - when there are 3  items). It would be nice to have an option to control this behavior - there are places where I want to keep a menu in "static" fullwidth, there are places where this clever behavior is OK. But now, I don't have an option, which is extremely annoying as I cannot use Ant's menu in various places, mainly because of this forced shrink.

### What does the proposed API look like?

Add an prop to Menu like `shrink?: boolean` to control this behavior.

**Comment by MadCcc** [comment]
Could you provide a reproduction about your problem?

**Comment by RoyXun** [comment]
> Could you provide a reproduction about your problem?

just wrap `Menu` with a flex container like this:
```
<header style={{display: 'flex'}}>
  <Menu items={xxxx}/>
</header>
```
