### ISSUE TITLE
Collapse组件在extra属性中有Checkbox时，Checkbox的onChange事件会触发Collapse的展开/折叠事件，阻止冒泡无效

### ISSUE THREAD

**Issue by Tsu8sa** [ant-design/ant-design#35569]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shou-feng-qin-antd-4-20-5-forked-o5p2ij?file=/demo.js)

### Steps to reproduce

点击checkbox图标，触发checkbox勾选，同时会展开当前点击的目标

### What is expected?

点击checkbox图标，触发checkbox勾选，由stopPropagation控制是否展开

### What is actually happening?

点击checkbox图标，触发checkbox勾选，自动展开，stopPropagation设置无效

| Environment | Info |
| --- | --- |
| antd | 4.18.7 |
| React | 17.0.2 |
| System | win11 |
| Browser | chrome 101.0.4951.54 |

**Comment by crazyair** [comment]
```
extra={
    <div onClick={e => e.stopPropagation()}>
        <Checkbox
            onChange={e => {
                setChecked(e.target.checked);
            }}
            checked={checked}
        >
            显示
        </Checkbox>
    </div>
}
```
