### ISSUE TITLE
Tree 组件开启虚拟滚动后不能横向滚动了，现在支持横向滚动吗? 或者有没有兼容的方式？

### ISSUE THREAD

**Issue by mianmalife** [ant-design/ant-design#35564]
### What problem does this feature solve?

虚拟滚动下支持横向滚动条

### What does the proposed API look like?

虚拟滚动下支持横向滚动条

**Comment by yykoypj** [comment]
官网例子不就有横向滚动条
https://ant.design/components/table-cn/#components-table-demo-virtual-list

**Comment by mianmalife** [comment]
@yykoypj 我指的是Tree组件，你这是table

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31226#issuecomment-872133431

**Comment by xiaolifeipiao** [comment]
> ### What problem does this feature solve?
> 虚拟滚动下支持横向滚动条
> 
> ### What does the proposed API look like?
> 虚拟滚动下支持横向滚动条

大佬这个问题解决了吗？

**Comment by cong1223** [comment]
真lj，这都解决不了，自己重新封装了rc-tree解决了，antd组的人是真鸡儿菜

**Comment by cong1223** [comment]
知道为什么他们解决不了吗？因为他们也是封装的第三方组件rc-tree, rc-tree不支持这个特性，所以antd也支持不了，水平也就这样吧，做业务而已。
