### ISSUE TITLE
Button 组件增加同一区域多个按钮的demo

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3556]
效果：

<img width="713" alt="2016-10-24 9 35 51" src="https://cloud.githubusercontent.com/assets/7017767/19647761/328d806a-9a32-11e6-929e-02d654f0edeb.png">

**Comment by afc163** [comment]
补充相关设计规范文案。

**Comment by whx76** [comment]
这个demo好，备注下，好了就可以用。

**Comment by ddcat1115** [comment]
设计说明文案：

按钮组合使用时，推荐使用1个主操作，1个次操作，3个以上操作时把更多操作放到Dropdown中组合使用。

**Comment by afc163** [comment]
Dropdown.Button

**Comment by afc163** [comment]
推荐使用1个主操作 + n个次操作，3个以上操作...

**Comment by ddcat1115** [comment]
👌

**Comment by benjycui** [comment]
这种形式的的 Button.Group 好像没怎么用。。 https://ant.design/components/button/#components-button-demo-button-group

要不把这个 demo 替换成新的这个 demo?

**Comment by afc163** [comment]
不是同一个东西，Button.Group 还是先保留
