### ISSUE TITLE
让Sider默认收起同时让Menu在初始时不被选中

### ISSUE THREAD

**Issue by bboylilshaw** [ant-design/ant-design#35563]
### What problem does this feature solve?

我在用Layout(Sider) 和 Menu时没办法同时达到以下三点
1. Sider默认收起，同时初始进入页面时Menu没有hover弹出来的效果
2. 当展开Sider时，有Menu.Item的Menu都展开，而不是收起的
3. 当收起Sider时，鼠标hover到Menu上，会弹出Menu的Menu.Item选择，而不是hover上去没反应

查阅了之前人提的issue和stackoverflow，不管是修改Menu的defaulOpenKeys 还是运行时编程控制发现都只能满足以上2个

### What does the proposed API look like?

期望Sider在collapsed=true时，同时defaultOpenKeys有值时，初次进入页面Menu不弹出

**Comment by afc163** [comment]
defaultOpenKeys 有值就是代表菜单会默认展现，和 `初次进入页面Menu不弹出` 是矛盾的。

**Comment by bboylilshaw** [comment]
> defaultOpenKeys 有值就是代表菜单会默认展现，和 `初次进入页面Menu不弹出` 是矛盾的。

OK, 了解。我不是一定要用defaultOpenKeys， 我只是想知道什么方法可以满足上面提的三个需求。

**Comment by MadCcc** [comment]
https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-20-5-forked-ygmj97?file=/demo.js
受控 `openKeys`

**Comment by bboylilshaw** [comment]
Hi @MadCcc , 你的方案只满足了前2条，第3点，当收起Sider时，鼠标hover到Menu上，会弹出Menu的Menu.Item选择，而不是hover上去没反应

**Comment by bboylilshaw** [comment]
> [codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-20-5-forked-ygmj97?file=/demo.js](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-20-5-forked-ygmj97?file=/demo.js) 受控 `openKeys`

Hi @MadCcc , 你的方案只满足了前2条，第3点，当收起Sider时，鼠标hover到Menu上，会弹出Menu的Menu.Item选择，而不是hover上去没反应
