### ISSUE TITLE
Table标题在存在colspan和滚动条的时候border-right被覆盖

### ISSUE THREAD

**Issue by yykoypj** [ant-design/ant-design#35577]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-bian-kuang-antd-4-20-5-forked-nlk449?file=/demo.js)

### Steps to reproduce

为最右边的column设置colspan或children

### What is expected?

右上角的cell的border-right不要被覆盖

### What is actually happening?

右上角的cell的border-right被右边格子（的box-shadow？）覆盖掉了

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 16.14 |
| System | codesandbox |
| Browser | codesandbox |

---
.ant-table-cell-scrollbar{
  box-shadow: 0 1px 0 1px #fafafa;
}
应该是被这玩意覆盖掉的  但是这段东西的用处不太清楚

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/168715869-23d598b0-81a8-4384-82f9-fb0bb524e2c2.png)
resize 的时候会抖动，某些宽度下会导致消失

**Comment by yykoypj** [comment]
没有滚动条的时候右边的边框没掉可能是这个问题https://github.com/ant-design/ant-design/issues/34129#issuecomment-1047361928
