### ISSUE TITLE
增加锚点组件 Anchor

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3557]
点击跳转到固定位置，是否需要增加该组件？

**Comment by afc163** [comment]
感觉可以有，还是有一些通用组件库实现了这个。

**Comment by benjycui** [comment]
额。。。和 `a/Link` 有什么不同。。。

**Comment by jljsj33** [comment]
加上滑动效果就和 a/link 不同了。

**Comment by afc163** [comment]
1. affix 效果
2. 滚动监听
3. 样式

http://www.jozefbutko.com/stickynavbar/

**Comment by RaoHai** [comment]
这样？
```jsx
import { Anchor } from 'antd';
const { Affix, Link } = Anchor;

ReactDOM.render(<div>
  <Affix>
    <header>
      <ul>
        <li><Link to="components" />Components</li>
        <li><Link to="pattern" />Pattern </li>
      </ul>
    </header>
  </Affix>
  <div>
    <Anchor name="components"><section>.....</section></Anchor>
    <Anchor name="pattern"><section>.....</section></Anchor>
  </div>
</div>);
```

**Comment by afc163** [comment]
```html
<Anchor>
  <AnchorLink href="#xxx">xxxx</AnchorLink>
  <AnchorLink href="#yyy">yyyy</AnchorLink>
</Anchor>


<div id="xxx">xxxxxxxxx</div>
<div id="yyy">yyyyyyyyy</div>
```

这样吧

**Comment by jljsj33** [comment]
跟 scrollLink 有点像唉。。。。http://react-component.github.io/scroll-anim/examples/link.html。。。

不要套标签吧，，，直接用嘛好了。。。。。。

**Comment by benjycui** [comment]
所以直接使用 Ant Motion...

**Comment by ddcat1115** [comment]
这个设计师那边有样式要求，UI还在更新中，定了我会贴过来哈

**Comment by ddcat1115** [comment]
<img src="https://zos.alipayobjects.com/rmsportal/rawioSGeIduqPuw.png">

<img src="https://zos.alipayobjects.com/rmsportal/KxwktECUTKtbOjF.png">

**Comment by RaoHai** [comment]
没太理解。 Anchor 自由样式且限定只能是竖样式？如果用户想在他自己的菜单里加一个 Anchor 怎么办？

**Comment by RaoHai** [comment]
或者说设计师想做的是像 antd 页面上右上角的这个东西？而不是一个可以在任意地方使用的 “点击跳转到固定位置” 的组件？

![image](https://cloud.githubusercontent.com/assets/566097/19753716/aa00f4d4-9c39-11e6-964a-85f5087d2e2c.png)

**Comment by afc163** [comment]
对，就是这个。

**Comment by afc163** [comment]
<img width="133" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19768903/e8731574-9c8b-11e6-8c06-a0594b6b3108.png">

**Comment by ddcat1115** [comment]
最新的设计有改变，大致就像楼上发的样子，详细设计稿稍后给出

**Comment by ddcat1115** [comment]
设计稿：（没有sketch版=_=）

<img src="https://zos.alipayobjects.com/rmsportal/scRQAfvokosAqfT.png" />

**Comment by afc163** [comment]
垂直距离太远了，这样不行的。

**Comment by afc163** [comment]
交互和样式可参考：https://www.zhihu.com/topic/19573936

**Comment by ddcat1115** [comment]
调整了间距：

<img src="https://zos.alipayobjects.com/rmsportal/cAbwBHBYzNIRhia.png" />

**Comment by RaoHai** [comment]
小圆点直径 9px，灰线直径 2px 的话，圆点里的白点对不齐灰线的，会差 0.5px ……除非用    ` transform: translateX(0.5px);`

**Comment by afc163** [comment]
用一些水平居中的技巧。
