### ISSUE TITLE
暗黑模式下不支持配置化主题

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#35589]
### Reproduction link

[https://stackblitz.com/edit/react-eahy5w?file=demo.js](https://stackblitz.com/edit/react-eahy5w?file=demo.js)

### Steps to reproduce

点击按钮实现换肤

### What is expected?

期望暗黑模式下支持配置化主题

### What is actually happening?

现在没有支持，不知道是bug还是就是不支持，不支持的话有点鸡肋

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17.x |
| System | mac |
| Browser | 谷歌 |

**Comment by afc163** [comment]
目前不支持，请关注 5.0 的进展。
