### ISSUE TITLE
Missing information for the 'select all' checkbox in the Table onChange function (rowSelection prop)

### ISSUE THREAD

**Issue by artrn-nt** [ant-design/ant-design#35585]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/selection-and-operation-antd-4-20-5-forked-qrb2ls?file=/demo.js)

### Steps to reproduce

See the link to minimal reproduction.

## Requirements: 

- Create an Antd table with a minimal data set (4 items for this use case) and enabled rowSelection prop
- Use the onChange function (rowSelection prop):

## Common for use cases 

1. Select the 1st item:
```javascript
onChange: (
          selectedRowKeys
) => {
        console.log('selectedRowKeys: ', selectedRowKeys)
        // result: selectedRowKeys: [0]
}
```

### Use case 1 - select all:

2. Then select all items by clicking on the 'select all' checkbox in the table header (global checkbox):
```javascript
onChange: (
          selectedRowKeys
) => {
         console.log('selectedRowKeys: ', selectedRowKeys)
         // result: selectedRowKeys: [0, 1, 2, 3]
}
```

### Use case 2 - multiple selection (shift key):

2. Then select multiple items by pressing and holding the 'shift' keyboard key and by clicking on the last item:
```javascript
onChange: (
          selectedRowKeys
) => {
         console.log('selectedRowKeys: ', selectedRowKeys)
         // result: selectedRowKeys: [0, 1, 2, 3]
}
```

### Use case 3 - single selection (one by one):

2. Then select item one by one, from 2nd to 4th:
**For this use case we will take the last onChange function call**
```javascript
onChange: (
          selectedRowKeys
) => {
         console.log('selectedRowKeys: ', selectedRowKeys)
         // result: selectedRowKeys: [0, 1, 2, 3]
}
```

## Conclusion: 

As you can see there are no difference for the onChange param (selectedRowKeys) between use cases 1, 2 and 3, and because of this we are not able to differentiate the use of the 'select all' checkbox in the table header (global checkbox) and the use of the 'SHIFT' keyboard key, and the use of simple repetitive selection.

**In our app, we really need to know if the user clicked on the checkbox 'select all' in the table header (global checkbox) or not.**

### What is expected?

onSelectAll function VS onChange function: by using the onChange function, we should be able to easily know if the user selected all items one by one OR by using the 'select all' checkbox in the table header (global checkbox).

onSelectMultiple function VS onChange function: by using the onChange function, we should be able to easily know if the user selected all items by using the 'MAJ' keyboard key OR if he used the 'select all' checkbox in the table header (global checkbox).

**If onSelectAll, onSelectMultiple, onSelect (...) are deprecated, the onChange function must evolve to provide the accuracy that deprecated functions had.**

### What is actually happening?

See the link to minimal reproduction.

onSelectAll function VS onChange function: by using the onChange function, if the user selected all items, we are unable to know if he did so by selecting them one by one, or by using the 'select all' checkbox in the table header (global checkbox).

onSelectMultiple function VS onChange function: by using the onChange function, if the user selected all items by using the 'MAJ' keyboard key, we are unable to know if all items were selected by using that key, or by using the 'select all' checkbox in the table header (global checkbox).

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17.0.2 |
| System | macOS |
| Browser | 101.0.4951.64 (Build officiel) (arm64) |

---
This bug issue is linked to closed feature issue: "Should clarify Table component API regarding rowSelection prop - onSelectAll / onSelectMultiple #35543"

**Comment by xrutayisire** [comment]
I agree with the lack of information for the onChange function, it's not possible to know where the user clicked. 

It could be a new param in the onChange function saying if it's 'select_all', 'multiple' or 'single'. 

'select_all': Usage of the global checkbox only
'multiple': Usage of 'Shift' keyboard key only
'single': Usage a simple click on a row only

Thanks to this, all other functions could be deprecated 👍
