### ISSUE TITLE
Collapse 增加bordered属性

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3559]
支持无边框的折叠面板，需补充视觉稿

**Comment by ddcat1115** [comment]
无border样式：

<img src="https://zos.alipayobjects.com/rmsportal/fSwKcQAgLUUqhro.png">

<img src="https://zos.alipayobjects.com/rmsportal/OvlvvpCNWooRMHU.png">

**Comment by afc163** [comment]
标题栏的高度都不统一，这样不行的。
