### ISSUE TITLE
[Bug] Cascader自定义显示时，首次点击自定义显示内容，下拉浮层展示后，再次点击自定义显示内容，浮层无法关闭

### ISSUE THREAD

**Issue by Selvin11** [ant-design/ant-design#35592]
### Reproduction link

[https://ant.design/components/cascader-cn/#components-cascader-demo-custom-trigger](https://ant.design/components/cascader-cn/#components-cascader-demo-custom-trigger)

### Steps to reproduce

点击自定义显示区域，下拉浮层展示，再次点击自定义显示区域，下拉浮层快速隐藏一次和显示一次，导致最终浮层无法关闭

### What is expected?

点击自定义显示区域，下拉浮层展示，再次点击自定义显示区域，下拉浮层隐藏，依此类推。

### What is actually happening?

点击自定义显示区域，下拉浮层展示，再次点击自定义显示区域，下拉浮层显示，多次点击也无法隐藏。

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17.0.2 |
| System | MacOS Monterey |
| Browser | chrome  101.0.4951.64 |

**Comment by afc163** [comment]
无法重现。

**Comment by Selvin11** [comment]
> 无法重现。
![Kapture 2022-05-17 at 15 17 08](https://user-images.githubusercontent.com/16698757/168752208-6f65cc20-3368-4b27-a16a-6117d74f32a8.gif)

**Comment by afc163** [comment]
浏览器是啥？版本号是多少？

**Comment by afc163** [comment]
我按你的操作方式是会消失的。

**Comment by Selvin11** [comment]
> 

=。=，chrome，版本 101.0.4951.64（正式版本） (arm64)

**Comment by Selvin11** [comment]
> 

=。=，chrome，版本 101.0.4951.64（正式版本） (arm64)
