### ISSUE TITLE
4.20.0版本之后DatePicker相关组件加载后首次点击展开会闪烁一下莫名的value值

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#35590]
### Reproduction link

![demo](https://user-images.githubusercontent.com/49147660/168736689-cc1b6682-3a19-4108-9572-9a3ea988e025.gif)

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kvgn5n?file=/index.js)

### Steps to reproduce

重载演示页面后，首次点击DatePicker展开时会闪烁一下莫名的日期value值

### What is expected?

消除此闪烁异常

### What is actually happening?

首次点击DatePicker展开时会闪烁一下莫名的日期value值

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | latest |
| System | win11 |
| Browser | Chrome 98.0.4758.82 |

**Comment by afc163** [comment]
确实有问题。

**Comment by Dunqing** [comment]
挺奇怪的，在本地和文档中都没复现出来

**Comment by littledian** [comment]
Same problem

**Comment by solitia7125** [comment]
可能是第一次打开日期面板时，鼠标浮动到了面板的日期，所有有闪烁的效果。

**Comment by solitia7125** [comment]
去掉了 .App的padding样式，就没有闪烁了

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7hzg95)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35051#issuecomment-1101419957

但是理论上展开 panel 不应该和鼠标位置重叠。

**Comment by solitia7125** [comment]
实际打了断点，的确hover到了日期

![hover](https://user-images.githubusercontent.com/39177579/168965398-b8db4cd7-4f8e-46a9-b517-433d711abcc4.gif)

**Comment by afc163** [comment]
动画放慢点观察一下是怎么重叠的。

**Comment by yykoypj** [comment]
用录屏工具看，显示value的一瞬间，panel应该还没渲染才对
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/15713772/168969698-b2bb89c3-0b4b-475a-8050-cb1e27ea0397.png">

**Comment by solitia7125** [comment]
可以看下这个，panel虽然没有显示出来，但节点已经渲染了

![hover3](https://user-images.githubusercontent.com/39177579/168977346-fd994fa0-2846-4d13-ba79-b465cb6a649a.gif)

**Comment by yykoypj** [comment]
trigger的container放在了左上角，`picker-dropdown`一开始虽然opacity为0。但是其实就在那

https://user-images.githubusercontent.com/15713772/168984021-9bee3d9b-fbb1-42cb-a944-68134651a83a.mov

**Comment by afc163** [comment]
你这个视频是怎么重现出来的，我刷新页面后默认没有 ant-picker-dropdown 渲染出来。

**Comment by solitia7125** [comment]
应该是 [react-compnoent/trigger#297](https://github.com/react-component/trigger/pull/297/files) 这里改动的问题，以前的pointer-events的值是"none"

![image](https://user-images.githubusercontent.com/39177579/169006046-377f79ad-9b30-4482-9889-803acd08f493.png)

**Comment by yykoypj** [comment]
> 你这个视频是怎么重现出来的，我刷新页面后默认没有 ant-picker-dropdown 渲染在 dom 树上。

给useHoverValue.js的`setValue(date)`那一行打上断点

**Comment by afc163** [comment]
@zombieJ 第一次渲染的dom节点确实不应该在屏幕内。top 和 left 应该是负数。

**Comment by yykoypj** [comment]
我看了一下rc-trigger本身有-9999px的设定，只不过antd引用之后没有了。我补上以后发现就正常了，提了个pr 大佬们看看对不对
