### ISSUE TITLE
Table Sorting Icons loading when using React with webpack 5

### ISSUE THREAD

**Issue by starkblaze01** [ant-design/ant-design#35607]
### Reproduction link

[https://github.com/starkblaze01/Test/tree/dev](https://github.com/starkblaze01/Test/tree/dev)

### Steps to reproduce

- Setup React 18 with Webpack 5
- In any react component import table  by using any of these two methods:
    - import Table from "antd/lib/table";
    - import { Table } from "antd";
- Add Sorter to the columns

Webpack Config:
```
const HtmlWebpackPlugin = require("html-webpack-plugin");
const path = require("path");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "bundle.[hash].js",
    path: path.resolve(__dirname, "dist"),
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.html",
      favicon: "./src/assets/favicon.png",
    }),
  ],
  resolve: {
    modules: [__dirname, "src", "node_modules"],
    extensions: ["*", ".js", ".jsx", ".tsx", ".ts"],
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: require.resolve("babel-loader"),
      },
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
      },
      {
        test: /\.png|svg|jpg|gif$/,
        use: ["file-loader"],
      },
      {
        test: /\.less$/,
        use: ["style-loader", { loader: 'css-loader', options: { sourceMap: 1 } }, "postcss-loader", "less-loader"]
      }
    ],
  },
};
```

.babelrc:

```
{
    "presets": [
        "@babel/preset-react",
        "@babel/preset-env"
    ],
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd",
                "libraryDirectory": "lib",
                "style": true
            }
        ],
        [
            "@babel/transform-runtime"
        ]
    ]
}
```

package.json:
```
{
  "name": "client",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server --hot --open --mode development",
    "build": "webpack --config webpack.config.js --mode production"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@babel/core": "^7.17.10",
    "@babel/plugin-transform-runtime": "^7.17.12",
    "@babel/preset-env": "^7.17.10",
    "@babel/preset-react": "^7.16.7",
    "antd": "^4.20.5",
    "axios": "^0.27.2",
    "babel-loader": "^8.2.5",
    "babel-plugin-import": "^1.13.5",
    "css-loader": "^6.7.1",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.5.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "style-loader": "^3.3.1",
    "webpack": "^5.72.1",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.9.0"
  }
}

```

### What is expected?

It should be able to load the sorting icons

### What is actually happening?

It is not loading sorting icons, but sorting is working and printing this warning in the console:
Warning: [@ant-design/icons] icon should be icon definition, but got http://localhost:8080/b3fe4f7cd3e6b7f5b7517b3e346d2e2b.js

**Response of the link:**
"use strict";
// This icon file is generated automatically.
Object.defineProperty(exports, "__esModule", { value: true });
var CaretUpOutlined = { "icon": { "tag": "svg", "attrs": { "viewBox": "0 0 1024 1024", "focusable": "false" }, "children": [{ "tag": "path", "attrs": { "d": "M858.9 689L530.5 308.2c-9.4-10.9-27.5-10.9-37 0L165.1 689c-12.2 14.2-1.2 35 18.5 35h656.8c19.7 0 30.7-20.8 18.5-35z" } }] }, "name": "caret-up", "theme": "outlined" };
exports.default = CaretUpOutlined;

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 18.1.0 |
| System | macOS Catalina |
| Browser | Google Chrome |

**Comment by afc163** [comment]
```diff
  resolve: {
    modules: [__dirname, "src", "node_modules"],
-   extensions: ["*", ".js", ".jsx", ".tsx", ".ts"],
+   extensions: [".js", ".jsx", ".tsx", ".ts"],
  },
```

Could you try this?

**Comment by starkblaze01** [comment]
@afc163 no luck still the same also added the repo link

**Comment by starkblaze01** [comment]
@afc163 any suggestions?
