### ISSUE TITLE
class is set on wrong element when `Form.Item` is configured with `hasFeedback={true}`

### ISSUE THREAD

**Issue by KaiVolland** [ant-design/ant-design#35600]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-20-5-forked-svfty6?file=/demo.js)

### Steps to reproduce

1. Create a `Form.Item` with an Input Element as child.
2. Set `hasFeedback={true}` on the `Form.Item`
3. Set `className="should-be-on-input"` to the Input field.
4. Inspect the dom output of the `Form.Item` or `Input`

### What is expected?

The Input Element in the dom has the class "should-be-on-input".

### What is actually happening?

The Input Element is wrapped by a span element which acutally receives the class "should-be-on-input".

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | ^17.0.2 |
| System | linux |
| Browser | chrome |

**Comment by MadCcc** [comment]
It is intended. `hasFeedback` depends on `suffix` prop of Input. When `suffix` is enabled, `className` will be passed to `affix-wrapper` element.

**Comment by KaiVolland** [comment]
Ah ok. So how can i set a class on the input field for this scenario?
