### ISSUE TITLE
Tag 增加选中状态

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3560]
- 支持选中/取消，颜色需设计师指定
- 增加相关demo

**Comment by ddcat1115** [comment]
视觉：

<img src="https://zos.alipayobjects.com/rmsportal/lHcyhtGvOdDNhDa.png">

设计师的意见，觉得目前的状态色没有太大意义，建议下掉状态色功能，这样选中的蓝色不会跟原来的蓝色 Tag 冲突

**Comment by afc163** [comment]
Ok

**Comment by benjycui** [comment]
没选中没 hover 的标签没有背景色？

**Comment by ddcat1115** [comment]
默认的标签样式不变，只是可选中的加hover和选中样式，同时去掉现有的状态色，图上无底色和边框的是设计师希望支持的特定场景，总结起来有这么几点：

- 原有默认样式不变
- 增加选中/取消功能，有hover和选中样式（如上图）
- 去掉原有几种状态色
- 支持无边框无底色样式的需求

**Comment by benjycui** [comment]
> 增加选中/取消功能

增加 checked 属性。

> 有hover和选中样式（如上图）

所有 Tag 都有 hover、 checked 状态？还是只有 checkable 的才有 hover 状态？

> 去掉原有几种状态色

`color` 属性只能废弃，无法完全移除，要兼容。。

> 支持无边框无底色样式的需求

能给我个名字么。。都不知道怎么命名属性。。

**Comment by ddcat1115** [comment]
- 只有 checkable 的才有 hover 状态
- 属性名字...... `type: default | simple` ？default 就是原来的样式，simple 就是无边框底色，但两者都checkable，checkable标签的 default 和 simple 的 hover和选中样式相同，这样ok不？

**Comment by afc163** [comment]
color 属性不动就好，例子隐藏掉。

**Comment by benjycui** [comment]
上下两排 Tag 之间的间隔最好也确认一下。

**Comment by luojian001** [comment]
Tag关闭按钮不能用回调函数？

**Comment by benjycui** [comment]
RTFD https://ant.design/components/tag/#components-tag-demo-basic
