### ISSUE TITLE
Input - searchInput 支持展开收起 & 增加内容超长出tooltip的demo

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3561]
展开收起：

<img src="https://zos.alipayobjects.com/rmsportal/bBIrBpmtvjGGuDr.png">

内容超长：

<img src="https://zos.alipayobjects.com/rmsportal/gbmwstYLxFtogST.png">

**Comment by afc163** [comment]
@Chinglik 看下现有的 SearchInput 能否和这个样式直接统一了。

<img width="255" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19650779/12be8864-9a3d-11e6-942c-4d8142567dda.png">

<img width="98" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19650786/15fb337e-9a3d-11e6-8554-ce597d6e7011.png">

**Comment by Chinglik** [comment]
可以的 ，统一这个
![image](https://cloud.githubusercontent.com/assets/14192159/20170673/31f7bd44-a768-11e6-8677-da1a25c5fa9b.png)

**Comment by benjycui** [comment]
数值输入框内容超长时的例子，之前产品工厂好像做了，直接贴过来么。

**Comment by ddcat1115** [comment]
@benjycui 对，差不多直接搞过来
