### ISSUE TITLE
Upload组件在multiple为true时候嵌套在Form.Item中使用，第二次上传必现uploading 状态

### ISSUE THREAD

**Issue by jsmgg** [ant-design/ant-design#35619]
### Reproduction link

[https://codepen.io/jsmgg/pen/JjpNowm](https://codepen.io/jsmgg/pen/JjpNowm)

### Steps to reproduce

Upload组件在multiple为true时候，放在Form.Item里面，第二次上传高概率出现某几张图片一直停留在uploading状态，测试步骤：
第一次一次传三张图片，基本都会成功，而后也没别刷新，继续选图，
第二次选又三张图片，这很大概率会出现部分成功部分uploading状态

### What is expected?

每次批量上传都正常显示

### What is actually happening?

部分图片一致显示上传中，其实已经上传成功了

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.0.5 |
| System | macOS 10.13.6 |
| Browser | chrome 101.0.4951.64 |

**Comment by idrex** [comment]
同问

**Comment by kunkkaliu** [comment]
遇到了同样的问题，使用mock的上传接口（直接返回成功状态），非受控的fileList列表，大概率会出现uploading状态！
![image](https://user-images.githubusercontent.com/17879324/184105292-6eb6440b-284a-4ec9-bd9c-ee82cac169e1.png)

**Comment by pufei007** [comment]
同问

**Comment by whieet** [comment]
我提供了一个解决方法，希望有帮助。亲测是没问题的。
https://github.com/ant-design/ant-design/issues/26536#issuecomment-1311871104

**Comment by Tinyuen** [comment]
@kunkkaliu  大佬请教下，你Upload也是在 Form.Item 中使用的吗？我感觉这种情况下，几遍是Upload没有受控方式指定 fileList，内部也会被当成受控的方式来处理。导致onChange只会执行一次，图片一直在uploading状态。搞得我头都大了。大佬你是怎么解决的

**Comment by jsmgg** [comment]
回来回复一下，我后面没有解决这个问题。
我直接将 multiple 设置为了 false。
