### ISSUE TITLE
在form表单中使用Radio.Group组件包裹Select组件时，除了第一次选择之外，再次选择Select组件会自动失去焦点，无法选中值

### ISSUE THREAD

**Issue by mdzxy** [ant-design/ant-design#35627]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiao-yan-qi-ta-zu-jian-antd-4-20-5-forked-dmspet?file=/demo.js)

### Steps to reproduce

在form表单中使用Radio.Group组件包裹Select组件时，除了第一次选择之外，再次选择Select组件会自动失去焦点，无法选中值

### What is expected?

不再自动失去焦点，能够正常选择select的值

### What is actually happening?

Select组件自动失去焦点，无法选中Option的值

| Environment | Info |
| --- | --- |
| antd | 4.16.13 |
| React | 17.0.2 |
| System | Mac OS X Big Sur 11.5.2 |
| Browser | Chrome 93.0.4577.82 |

---
任何antd和React的版本都会出现此问题，包括最新的antd4.20.5都会出现问题

**Comment by MadCcc** [comment]
不太建议这样嵌套，Radio 的 children 会被当作 label。
建议让 Select 和 Radio 同级。

**Comment by mdzxy** [comment]
`<Form.Item name="radio-group" label="Radio.Group">
        <Radio.Group>
          <Radio value="a">
            <div>
              radio中的下拉选择1
              <Form.Item name="test">
                <Select>
                  <Option value="red">Red</Option>
                  <Option value="green">Green</Option>
                  <Option value="blue">Blue</Option>
                </Select>
              </Form.Item>
            </div>
          </Radio>
          <Radio value="b">
            <div>
              radio中的下拉选择2
              <Form.Item name="test2">
                <Select>
                  <Option value="red">Red</Option>
                  <Option value="green">Green</Option>
                  <Option value="blue">Blue</Option>
                </Select>
              </Form.Item>
            </div>
          </Radio>
          <Radio value="c">
            <div>
              radio中的下拉选择3
              <Form.Item name="test3">
                <Select>
                  <Option value="red">Red</Option>
                  <Option value="green">Green</Option>
                  <Option value="blue">Blue</Option>
                </Select>
              </Form.Item>
            </div>
          </Radio>
        </Radio.Group>
      </Form.Item>`
需求无法将Radio和Select同级处理，只能这样处理了 @MadCcc

**Comment by mdzxy** [comment]
`<Form.Item name="radio-group" label="Radio.Group">
        <Radio.Group>
          <Radio value="a">
            <div>
              radio中的下拉选择1
              <Form.Item name="test">
                <Select>
                  <Option value="red">Red</Option>
                  <Option value="green">Green</Option>
                  <Option value="blue">Blue</Option>
                </Select>
              </Form.Item>
            </div>
          </Radio>
          <Radio value="b">
            <div>
              radio中的下拉选择2
              <Form.Item name="test2">
                <Select>
                  <Option value="red">Red</Option>
                  <Option value="green">Green</Option>
                  <Option value="blue">Blue</Option>
                </Select>
              </Form.Item>
            </div>
          </Radio>
          <Radio value="c">
            <div>
              radio中的下拉选择3
              <Form.Item name="test3">
                <Select>
                  <Option value="red">Red</Option>
                  <Option value="green">Green</Option>
                  <Option value="blue">Blue</Option>
                </Select>
              </Form.Item>
            </div>
          </Radio>
        </Radio.Group>
      </Form.Item>`
需求无法将Radio和Select同级处理，只能这样处理了 @MadCcc

**Comment by mdzxy** [comment]
@MadCcc 我再想想办法吧，实际需求没有这个demo这样简单的～

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/25959
