### ISSUE TITLE
Table 增加 『添加一行』的demo & 可即时编辑的demo

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3562]
添加一行（包括列表单和删除操作）：

<img src="https://zos.alipayobjects.com/rmsportal/GyXXPgWEpqgoLeJ.png">

即时编辑（包括一处 和 一行）：

<img src="https://zos.alipayobjects.com/rmsportal/DTwxpbkoKUXfwlm.png">

<img src="https://zos.alipayobjects.com/rmsportal/NrIUJFgqKuwymWh.png">

**Comment by afc163** [comment]
包括列表单和删除操作。

**Comment by ruizhengyun** [comment]
antd的表格有及时编辑的demo么 @

**Comment by afc163** [comment]
@ruizhengyun 这就是计划了呀。

**Comment by raisezhang** [comment]
@afc163  我直接在 table columns 里面直接添加表单   getFieldDecorator  貌似是不能用了，  还有其他实现方式么， 多个name （id）共存

**Comment by eddyzhang1986** [comment]
#3796
