### ISSUE TITLE
[Chinese website feature request] Can Chinese documentation site icon search support search in Chinese mandarin?

### ISSUE THREAD

**Issue by shezhangzhang** [ant-design/ant-design#35634]
### What problem does this feature solve?

Chinese Description:
中文官方文档的：组件-通用-图标，搜索功能只支持英文的string匹配，每次找图标都非常麻烦。比如找爱心这个图标，以我为例，一般会搜索中文的“心”（or 'love'），搜索不到该图标，肉眼找到了，发现是“heart”。特别是很多图标的英文单词相当复杂，基本上搜索不到，如："shopping-cart"（购物车图标）、"customer-service"（耳机图标），我认为，英文差一点的用户查找效率很低。

English Description:
I'm usually search icons on the ant design build-in icons components page. But I found that the documentation site uses an icon string (English only) to match. If I used another word to search the same icon, I got nothing. (Such as, the 'love' icon is 'heart'.) Then I can only search with my own eyes. It's utterly Inefficient.

### What does the proposed API look like?

中文官网图标搜索，支持中文搜索。
Ant design documentation site icon search support Chinese search.

**Comment by afc163** [comment]
这个成本比较高，目前图标没有对应的中文描述。

**Comment by shezhangzhang** [comment]
> 这个成本比较高，目前图标没有对应的中文描述。

我可以来搞一下这个需求。不知道有没有其他用户有这样的需求，有的话请点个+1。
