### ISSUE TITLE
Tree 增加带搜索框的demo

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3563]
<img src="https://zos.alipayobjects.com/rmsportal/KhTAcRonvPlhnYY.png">

**Comment by zhangchao828** [comment]
这个例子差不多符合你的要求
http://codepen.io/anon/pen/VKOqwB

**Comment by afc163** [comment]
@ddcat1115 上面那些样式都不要做，和搜索没关系。单独加搜索就可以。

**Comment by afc163** [comment]
@zhangchao828 感谢你的例子，感觉很合适。PR 一个帮助我们加个 demo 如何？

**Comment by zhangchao828** [comment]
@afc163 好的，有空我弄一下

**Comment by afc163** [comment]
@ddcat1115 已经在做了，你等下次有机会吧~ 😃

**Comment by zhangchao828** [comment]
@afc163 好的，我等着，哈哈
