### ISSUE TITLE
Form doesn't return values for form if it's not wrapped into Form.Item, even that it was passed in the initialValue or set using setFieldValue

### ISSUE THREAD

**Issue by rybkowskigrzegorz** [ant-design/ant-design#35635]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dawn-fire-2oi404?file=/src/App.js)

### Steps to reproduce

https://codesandbox.io/s/dawn-fire-2oi404?file=/src/App.js

### What is expected?

using useFormInstance I expect to receive the whole form payload even if some fields aren't editable

### What is actually happening?

each field value that is not wrapped in the UI in the form.

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17.0 |
| System | macOS |
| Browser | chrome |

**Comment by MadCcc** [comment]
If values are not controlled by form, you can easily combine them with form values.
`initialValues` is only used to initialize existed form item and the rest values will not be stored in form instance.
