### ISSUE TITLE
resetFields makes TextArea form item flicker

### ISSUE THREAD

**Issue by acailly** [ant-design/ant-design#35632]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gsdnqf?file=/index.js)

### Steps to reproduce

Add a text area form item in a form with name "Comments"
Call form.resetField with "Comments"

### What is expected?

The text area value is cleared without flickering

### What is actually happening?

The text area value is cleared with flickering

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 18.1.0 and 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 101.0.4951.67 64bits and Firefox 100.0 64bits |

**Comment by Khavrolev** [comment]
Hello!

Any updates on this bug?

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/textarea/pull/23

https://codesandbox.io/s/antd-reproduction-template-forked-wy5hw2
