### ISSUE TITLE
The web page breaks down when open popup calendar of `DatePicker.RangePicker`

### ISSUE THREAD

**Issue by PinkChampagne17** [ant-design/ant-design#35636]
### Reproduction link

Sorry, l can not reproduce.

### Steps to reproduce

Just click the input box of DatePicker.RangePicker component.

### What is expected?

The web page will work normally.

### What is actually happening?

The web page breaks down.

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | React 18 Strict Mode |
| System | macOS Monterey 12.3.1 |
| Browser | Chrome 101.0.4951.64  |

---
I encountered a similar problem with them. #35282 https://github.com/react-component/trigger/issues/288

This problem should be resolved by [this commit](https://github.com/react-component/trigger/commit/017131d9afdc0181a8f2441370ff938386aa1212) in rc-trigger repo.
But ant-design repo still uses the old version rc-trigger@5.2.10, my project will work fine as I expect after updating it to the latest.
Can we upgrade dependency rc-trigger to the latest version in ant-design repo?

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/35638#issuecomment-1131678278
