### ISSUE TITLE
Form.watch does not work with namePath array

### ISSUE THREAD

**Issue by monmush** [ant-design/ant-design#35637]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/watch-hooks-antd-4-20-5-forked-g3h808?file=/demo.js)

### Steps to reproduce

Type in Name and Age input

### What is expected?

 It should console.log the watched values

### What is actually happening?

Logged "undefined" to the console

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | react 16.14.0 or any newer version |
| System | MacOS Monterey 12.2.1 |
| Browser | Chrome 101.0.4951.64 (Official Build) (x86_64) |

**Comment by afc163** [comment]
https://codesandbox.io/s/watch-hooks-antd-4-20-5-forked-90wpwi?file=/demo.js is correct way.

**Comment by monmush** [comment]
<img width="1025" alt="Screen Shot 2022-05-31 at 10 32 11" src="https://user-images.githubusercontent.com/43520044/171087366-240fb5c7-8236-4c34-88f6-418ce490931c.png">

@afc163 it states in the docs that namePath can be `string | number | (string | number)[]`. In the reproduction, I don't see it work with `string[]`
