### ISSUE TITLE
tabs标签页切换蓝色分隔线动画问题

### ISSUE THREAD

**Issue by ADheight** [ant-design/ant-design#35631]
### Reproduction link

[[https://codepen.io/pen](https://codepen.io/pen)](https://codesandbox.io/s/antd-reproduction-template-forked-v2d34b)

### Steps to reproduce

我将此组件引入我的开发环境中，但是tabs切换的时候，下面的蓝色分隔线不显示
![image](https://user-images.githubusercontent.com/67545606/169246538-6e0dfde1-d412-438a-aa09-a16f5ab94db4.png)

### What is expected?

期望显示效果如官方文档一样
![image](https://user-images.githubusercontent.com/67545606/169246984-7d75cadd-7684-40e1-a751-474ba5006eb2.png)

### What is actually happening?

tabs标签页进行切换的时候蓝色分割线不显示
![image](https://user-images.githubusercontent.com/67545606/169246538-6e0dfde1-d412-438a-aa09-a16f5ab94db4.png)

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 18.1.0 |
| System | win10 |
| Browser | Google |

**Comment by ADheight** [comment]
> 

请问您说的这个什么意思？求解

**Comment by ADheight** [comment]
> Hello @ADheight. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @ADheight, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

就是官网antd4.20.5的标签页代码哦，我原原本本复制进去啥也没改，然后就跟官网效果不一样，我在codesandbox里面是跟官网效果一样的，但是引用到我的开发文档中就没有那个效果，所以我很疑惑。我重新建立一个新的react项目，然后光放一个标签页也是一样的，没有那个蓝色分割线效果

**Comment by ADheight** [comment]
> Hello @ADheight. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @ADheight, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

链接实例已重新编辑在问题中

**Comment by afc163** [comment]
<img width="1346" alt="图片" src="https://user-images.githubusercontent.com/507615/169261771-efa41ee8-4687-4cfe-b66f-f003c5c72363.png">

无法重现。

**Comment by ADheight** [comment]
> <img alt="图片" width="1346" src="https://user-images.githubusercontent.com/507615/169261771-efa41ee8-4687-4cfe-b66f-f003c5c72363.png">
> 
> 无法重现。

你出来的效果就是我在codesandbox里面的效果，但是我在我的项目里没有这个效果，就像我图截取的那样

**Comment by littledian** [comment]
It is same of #35367 , @afc163
