### ISSUE TITLE
Menu组件的MenuItem有onClick事件的，文档中是否应该加上？

### ISSUE THREAD

**Issue by fybchristasker** [ant-design/ant-design#35649]
### Reproduction link

[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce

const items = [
  { label: '菜单项一', key: 'item-1' }, // 菜单项务必填写 key
  { label: '菜单项二', key: 'item-2' },
  {
    label: '子菜单',
    key: 'submenu',
    children: [{ label: '子菜单项', key: 'submenu-item-1' }],
  },
];
return <Menu items={items} />;

### What is expected?

const items = [
  { label: '菜单项一', key: 'item-1' }, // 菜单项务必填写 key
  { label: '菜单项二', key: 'item-2' },
  {
    label: '子菜单',
    key: 'submenu',
    children: [{ label: '子菜单项', key: 'submenu-item-1' }],
    onClick: () => {},
  },
];
return <Menu items={items} />;

### What is actually happening?

danger	展示错误状态样式	boolean	false	
disabled	是否禁用	boolean	false	
icon	菜单图标	ReactNode	-	
key	item 的唯一标志	string	-	
label	菜单项标题	ReactNode	-	
title	设置收缩时展示的悬浮标题	string	-

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome |

---
之前我们都是将onClick事件写在label或icon中。

**Comment by afc163** [comment]
建议用 Menu 的 onClick 事件统一处理。
