### ISSUE TITLE
[Select] tags 模式下，使用 tagRender 在删除 tag 时展示异常

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#35647]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-xuan-ze-biao-qian-antd-4-20-5-forked-5t91du?file=/demo.js)

### Steps to reproduce

1. 任意输入两个（或两个以上）tag
2. 删除非末尾的 tag（比如删第一个）

### What is expected?

删除指定的 tag

### What is actually happening?

点一下，删两个，但是下面下拉列表里看起来又是正常的

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17.0.2 |
| System | Gentoo Linux 5.4.97 |
| Browser | Chrome 103.0.5042.0 |

**Comment by MadCcc** [comment]
You should provide prop `options` for Select.
https://codesandbox.io/s/zi-ding-yi-xuan-ze-biao-qian-antd-4-20-5-forked-43nbrg?file=/demo.js

**Comment by jinliming2** [comment]
提供 `options` 属性后，针对 `options` 中的选项可以正常删除，但是针对用户手动输入的不在 `options` 中的选项还是会出现问题。
还是说我需要自己独立维护一个可变的 `options`，根据用户的输入来更新？官网的 [`Tags` 示例](https://ant.design/components/select/#components-select-demo-tags)貌似没有这样的逻辑。
不使用 `tagRender` 时是正常的。

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/pull/782
