### ISSUE TITLE
Clicking clear button triggers `onSearch` with an empty string

### ISSUE THREAD

**Issue by j10ccc** [ant-design/ant-design#35645]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

[https://codepen.io/j10c/pen/XWZROZy](https://codepen.io/j10c/pen/XWZROZy)

### Steps to reproduce

打开codespace console，在 antd 搜索框输入一些内容，点击 clear button

### What is expected?

仅仅搜索框内值被清空

### What is actually happening?

发现还触发了`onSearch`，console 显示了一条信息`triggles an event`

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 18.0.0 |
| System | Windows 11 |
| Browser | Edge 101.0.1210.47 |

---
`onSearch`函数中需要跳转页面，清空输入框会触发跳转页面

**Comment by j10ccc** [comment]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18729#issuecomment-529502936
