### ISSUE TITLE
DatePicker在360急速浏览器下打开很卡

### ISSUE THREAD

**Issue by moshuchao** [ant-design/ant-design#35648]
### Reproduction link

[https://ant.design/components/date-picker-cn/ ](https://ant.design/components/date-picker-cn/ )

### Steps to reproduce

点击时间选择器

### What is expected?

立即打开

### What is actually happening?

打开非常缓慢

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17 |
| System | mac |
| Browser | 360急速浏览器 |

**Comment by MadCcc** [comment]
🖥 Environment Support

IE / Edge | Firefox | Chrome | Safari | Electron
-- | -- | -- | -- | --
IE11, Edge | last 2 versions | last 2 versions | last 2 versions | last 2 versions
