### ISSUE TITLE
TimePicker does not accept popupClassName when replacing Moment.js with day.js

### ISSUE THREAD

**Issue by jamealg-jv** [ant-design/ant-design#35646]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-timepicker-popupclassname-issue-vh2nwv?file=/index.js)

### Steps to reproduce

1) Follow the steps on the Replace Moment.js documentation to replace with day.js: https://ant.design/docs/react/replace-moment
2) Set popupClassName prop with a defined class
3) Run and open the popup

### What is expected?

The className is applied to the popup container

### What is actually happening?

The className is not applied to the popup container

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 17 |
| System | macOS Catalina 10.15.7 |
| Browser | Chrome 98.0.4758.102 |

**Comment by MadCcc** [comment]
Use `dropdownClassName` instead.  `popupClassName` is only alias in TimePicker of antd, and is not work in Picker generated with `generatePicker`.
Maybe we should deprecate `popupClassName` and enable `dropdownClassName` for TimePicker to ensure consistency with DatePicker.

**Comment by MadCcc** [comment]
Trace in https://github.com/ant-design/ant-design/issues/34087
