### ISSUE TITLE
发现一个Spin不好的地方，就是比所有弹出来的层次还低

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#3565]
不论是modal弹出框，还是下拉选择弹出框，或者是上传图片的操作层次都比spin高，遮罩在还是能做操作～

**Comment by benjycui** [comment]
ref: https://www.qianduan.net/that-thing-on-the-z-index/

可以尝试设置弹出层的 `getPopupContainer`，使弹出层的 DOM 结构在 `Spin` 的里面。

**Comment by aw6658913** [comment]
getPopupContainer 这个属性在哪里有说明呢？官网跟git好像都没有这个属性的使用说明

**Comment by benjycui** [comment]
`Select` 有，`Modal` 没有。。。

@afc163 Modal 可能要加个 `spinning` 属性？`Spin` 现在的实现方式支持不了。

**Comment by afc163** [comment]
啥支持不了？

**Comment by benjycui** [comment]
就是用 Spin 的遮罩盖住 Modal。

@aw6658913 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
```
<Modal>
  <Spin>
   ...
  </Spin>
</Modal>
```

这样不行么

**Comment by afc163** [comment]
建议自行调节 Spin 的高度。
