### ISSUE TITLE
[Select] tags 模式下，使用 tagRender，在提供了 options 的情况下，删除用户输入的 tag 时展示异常

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#35657]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-xuan-ze-biao-qian-antd-4-20-5-forked-43nbrg?file=/demo.js)

### Steps to reproduce

1. **手动输入**任意两个（或两个以上）tag
2. 删除非末尾的**手动输入**的 tag

### What is expected?

删除指定的 tag

### What is actually happening?

点一下，删两个，但是下面下拉列表里看起来又是正常的

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17.0.2 |
| System | Gentoo Linux 5.4.97 |
| Browser | Chrome 103.0.5042.0 |

---
关联 issue：https://github.com/ant-design/ant-design/issues/35647

删除 `options` 中提供的选项时，不会触发 bug，但是删除用户手动输入添加的 tag 就会触发 bug。

使用 @MadCcc 提供的代码仍然存在问题。但上面的 issue 被关闭了。

**Comment by afc163** [comment]
应该是需要一个 key 来区分：https://codesandbox.io/s/zi-ding-yi-xuan-ze-biao-qian-antd-4-20-5-forked-vr166z

**Comment by jinliming2** [comment]
emmmm，更新下文档的示例吧

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/pull/782
