### ISSUE TITLE
Sandbox Info  Virtual list - antd@4.20.5 i see a gap between the header and the body

### ISSUE THREAD

**Issue by JSchmidt63** [ant-design/ant-design#35665]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/telinh)

### Steps to reproduce

change to last field

### What is expected?

i don't the gap between the header and the body

### What is actually happening?

the is a gap between between

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | react |
| System | Windows 10 |
| Browser | Chrome 101.0.4951.67 |

<!-- generated by ant-design-issue-helper. DO NOT REMOVE --
![antd table 2022-05-20 174126](https://user-images.githubusercontent.com/25293774/169564088-1defbabb-7866-4492-bcd7-e82023a65e85.png)
>
![antd table 1 2022-05-20 174126](https://user-images.githubusercontent.com/25293774/169564250-4ccdf026-b9c7-4d15-ad54-e819e1a8d5f2.png)

**Comment by JSchmidt63** [comment]
see it the pic
![antd table 2022-05-20 174126](https://user-images.githubusercontent.com/25293774/169564601-5116834a-7639-4dc3-93a9-1d49292071e2.png)

**Comment by JSchmidt63** [comment]
https://stackblitz.com/edit/react-o3dnhi?file=index.js,demo.js,index.css,index.html

good:
![antd table 2022-05-22 144233](https://user-images.githubusercontent.com/25293774/169695794-e371a97f-2b58-403f-baff-89c935502320.png)

bad:
![antd table see bug 2022-05-22 144344](https://user-images.githubusercontent.com/25293774/169695802-cc30b8a0-4bc7-48ee-8b40-d558d5cf5d61.png)

**Comment by JSchmidt63** [comment]
http://react-component.github.io/table/?path=/story/rc-table--virtual-list-grid

see here
![antd 2022-05-22 233639](https://user-images.githubusercontent.com/25293774/169717011-f2710766-a312-4779-82f8-dbbf473e413a.png)

![antd table 2022-05-22 233948](https://user-images.githubusercontent.com/25293774/169717087-2bc60d25-08aa-4943-bbe2-93bebc4cd4bf.png)

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/table/pull/816
