### ISSUE TITLE
4.20.5版本的Form.Item自动添加了class

### ISSUE THREAD

**Issue by swiftwind0405** [ant-design/ant-design#35664]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-fang-fa-diao-yong-antd-4-20-5-forked-6qel3l?file=/demo.js)

### Steps to reproduce

基于antd封装的一个公共组件库，在更新antd 4.20.5 后发现里面Form.Item下放一个Select控件，会自动添加ant-select-in-form-item这个class。而在之前的版本中ant-select的宽度100%，是通过.ant-form-item .ant-select这个样式来设置的。现在项目中使用封装好的这个组件（就是一个Form控件里面封装了常用的Item控件，也支持传入自定义Item控件），当传入自定义的一个Item控件，比如说CsSelect，不会自动添加ant-select-in-form-item这个class，导致必须手动设置样式才能做到样式的宽度继承（100%）。

### What is expected?

自己传入的控件，也能自动添加ant-select-in-form-item这个class

### What is actually happening?

没有添加ant-select-in-form-item这个class

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 16.9 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
建议用 `<Select style={{ width: '100%' }} />` 来直接设置宽度。
