### ISSUE TITLE
Modal.method( )中的样式问题，bodyStyle设置的宽度无法撑开父级元素

### ISSUE THREAD

**Issue by MuxinFeng** [ant-design/ant-design#35661]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-szjfrt?file=/index.js)

### Steps to reproduce

```
const Demo = () => {
  const renderModal = () => {
    return Modal.info({
      content: (
        <div>
          如果body太宽，modal不会自动撑开；如果body太宽，modal不会自动撑开
        </div>
      ),
      bodyStyle: { width: "500px" }
    });
  };
  return (
    <div className="App">
      <Button type="primary" onClick={renderModal}>
        查看模态窗
      </Button>
    </div>
  );
```

### What is expected?

modal随着body的扩大而扩大

### What is actually happening?

将body扩充，modal没能被撑开

| Environment | Info |
| --- | --- |
| antd | 4.16.3 |
| React | 17.0.2 |
| System | Mac |
| Browser | chrome101 |

**Comment by afc163** [comment]
建议直接用 width：https://codesandbox.io/s/antd-reproduction-template-forked-2u0wdg
