### ISSUE TITLE
React18下Modal组件的transform-origin计算有误，导致缩放动画的原点出现偏差

### ISSUE THREAD

**Issue by canlooks** [ant-design/ant-design#35663]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-waterfall-2xo676)

### Steps to reproduce

点击按钮两次以上

### What is expected?

Modal组件的缩放动画原点应在鼠标点击的按钮位置

### What is actually happening?

第二次之后打开Modal组件会出现缩放动画的原点偏移的情况，甚至会偏移至屏幕之外导致出现滚动条

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 18 |
| System | window 11 |
| Browser | Edge 101.0.1210.47 |

**Comment by MadCcc** [comment]
chrome 试了下没问题，只能在 edge 上复现？能否提供个录屏

**Comment by canlooks** [comment]
我用chrome试也是一样的，点击“按钮2”会比较明显，第二次弹窗关闭的时候会飞出窗口，窗口底部有一瞬间出现了滚动条。换回React17就没有这个现象

https://user-images.githubusercontent.com/59165337/170001294-192f6b32-4d49-43ca-bd1e-31f27ed52fca.mp4

**Comment by sudden3** [comment]
我也发现这个问题了，查看Modal.js源码发现getClickPosition函数获取到的e.pageX和e.pageY的值都是正确的， 想尝试自己修复但是水平不够🤣只能期待下个版本能够修复了

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/dialog/pull/306
