### ISSUE TITLE
popover组件的三角标错误显示

### ISSUE THREAD

**Issue by dyggod** [ant-design/ant-design#35675]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jel8l5)

### Steps to reproduce

1. 引入antd的popover组件.
2. 通过悬浮、点击或聚焦等方式触发气泡框显示.

### What is expected?

气泡框的三角指向小图正确显示

### What is actually happening?

小图标显示为一个矩形

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | react |
| System | window11家庭版：22000.675 |
| Browser | chrome浏览器，版本 86.0.4240.198（正式版本） （32 位） |

### 附上截图
1. 实际使用时：
![image](https://user-images.githubusercontent.com/49914353/169748704-bc28bc37-6a56-4e4b-985a-815d9c57b696.png)
2. 文档中问题相同：
![image](https://user-images.githubusercontent.com/49914353/169748869-0475be82-ea20-44fd-b6f2-54c30731407b.png)

**Comment by afc163** [comment]
需要升级浏览器版本了。

**Comment by dyggod** [comment]
> 需要升级浏览器版本了。

thanks~
