### ISSUE TITLE
datepicker 世纪选择

### ISSUE THREAD

**Issue by TMoDzzzz** [ant-design/ant-design#35673]
### Reproduction link

[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce

随意点击一个时间选择器，点击年份进入十年的选择器，再次点击进入百年的选择器

### What is expected?

激活的年份应该只有当前的时间段

### What is actually happening?

每次换页都会有激活的时间段

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 16.14.0 |
| System | windows |
| Browser | edge |

**Comment by afc163** [comment]
Duplicate of #35279
