### ISSUE TITLE
textarea 计算的emoji长度问题

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#35678]
### Reproduction link

[https://stackblitz.com/edit/react-4ptjcq?file=demo.js](https://stackblitz.com/edit/react-4ptjcq?file=demo.js)

### Steps to reproduce

直接即可看到
<img width="445" alt="image" src="https://user-images.githubusercontent.com/22299421/169759189-4c272f50-d0e4-4df7-b294-3a07406e99e1.png">

### What is expected?

表情的长度为1

### What is actually happening?

不同表情显示的长度不一样

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment]
这是合理的，emoji 本来就是一到多个字符拼起来的。
