### ISSUE TITLE
On Full Screen Mode Select Dropdown dont show

### ISSUE THREAD

**Issue by FGCorp** [ant-design/ant-design#35689]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8nt0c7?file=/index.js)

### Steps to reproduce

I m trying to make a component full window size using document's full screen event.When i make it full screen Select dropdown box not show as expected. 

### What is expected?

Select dropdown need to show at the bottom of select bar.

### What is actually happening?

I m trying to make a component full window size using document's full screen event.When i make it full screen Select dropdown box not show as expected. Heren an expample of the code;
<code>
import './style.scss';

import { Button, Select } from 'antd';
import React from 'react';

const makeFull = () => {
  document.getElementById('fullScreen').requestFullscreen();
};

function CommunityGraph() {
  return (
    <div id="fullScreen" className="FullScreen">
      test <Button onClick={() => makeFull()}>Make Full</Button>
      <Select placeholder="Test denem 12314214">
        <Select.Option key={1}>Test 1</Select.Option>
        <Select.Option key={2}>Test 2</Select.Option>
        <Select.Option key={3}>Test 3</Select.Option>
      </Select>
    </div>
  );
}

export default CommunityGraph;
</code>

This is the style.scss ;
<code>
.FullScreen {
  background-color: #e4708a;
  width: 100vw;
  height: 100vh;
}
</code>

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | React |
| System | Windows 10 |
| Browser | Google Chrome V 101.0.4951.67 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17923#issuecomment-515540485

**Comment by glantucan** [comment]
The solution in the comment for a dialog that fills the entire screen. 
Doesn't work in full screen mode, like on the controls of a video player in full screen. The options are not shown when clicking on the select box.

**Comment by atahanturk** [comment]
You need to add appendTo={'self'} to the dropwdown element.

**Comment by SimonSomlai** [comment]
What worked for me is to set the `popupContainer`: Basically setting the id of the element where the dropdown needs to render under.

```tsx
  <Col xs={24} sm={12} id={`${prefix}-countryId`}>
          <Text strong>Country</Text>
          <AutoComplete
            getPopupContainer={() =>
              document.getElementById(`${prefix}-countryId`)
            }
          >
            {countryOptions.map(option => (
              <Option key={option.value} value={option.value}>
                <Space>
                  <EnvironmentOutlined />
                  {option.label}
                </Space>
              </Option>
            ))}
          </AutoComplete>
        </Col>
```
