### ISSUE TITLE
antd 一个组件内多个form，设置name不生效，form.validateFields([namePath])拿到的永远是undefined

### ISSUE THREAD

**Issue by inmWang** [ant-design/ant-design#35682]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-snyder-55mj45?file=/src/App.js)

### Steps to reproduce

form.getFieldsValue(['test1')

### What is expected?

得到name为test1的form的表单数据

### What is actually happening?

undefined

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18.0.0 |
| System | macos monterry |
| Browser | chrome 101.0.4951.64 |

**Comment by afc163** [comment]
1. 不推荐 form 和多个 Form 同时进行绑定，应该一对一。
2. 你的例子里应该是  `console.log(form.getFieldsValue(["user1"]));` 而不是 `console.log(form.getFieldsValue(["test1"]));`。

**Comment by lbyupup** [comment]
诶如果有两个Form组件，通过一个状态来切换，初次渲染的Form绑定的form实例使用正常，可是切换后渲染的Form组件实例form拿不到数据，这是为什么呢？

**Comment by muliyang** [comment]
> 诶如果有两个Form组件，通过一个状态来切换，初次渲染的Form绑定的form实例使用正常，可是切换后渲染的Form组件实例form拿不到数据，这是为什么呢？

因为开始初始化的时候，会认为是一样的。 每个form 绑定一个key 应该就好了
