### ISSUE TITLE
Steps 增加页面使用示例

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#3569]
包含与内容及按钮的配合使用

<img width="821" src="https://zos.alipayobjects.com/rmsportal/gchUydJRuGFPVYv.png">

**Comment by afc163** [comment]
不增加，改造这个例子：https://ant.design/components/steps/#components-steps-demo-step-next

**Comment by ddcat1115** [comment]
这个 fixed 的按钮组在 demo 里没办法正常展示，改为一般按钮组
