### ISSUE TITLE
modal框是否支持全局修改closeIcon

### ISSUE THREAD

**Issue by yangweiqi666** [ant-design/ant-design#35698]
### What problem does this feature solve?

产品经理觉得目前的icon不好看，想替换一个新的icon.目前看上去比例不是方方正正，他们想要的效果是谷歌浏览器关闭这种样式。之前有个方案是写一个上层组件，然后名称全局替换一下，但是被领导否决了。理由是如果新人后续直接用antd modal,会有问题，看看是否可以让使用者无感知，直接更改antd 的icon。第一次提issue,期待回复一下。

### What does the proposed API look like?

有个全局配置，或者有什么好的方式可以实现吗？

**Comment by MadCcc** [comment]
`closeIcon`

> 理由是如果新人后续直接用antd modal,会有问题

组件库默认情况下也只提供默认配置，需要定制时封装还是有必要的

**Comment by yangweiqi666** [comment]
> `closeIcon`
> 
> > 理由是如果新人后续直接用antd modal,会有问题
> 
> 组件库默认情况下也只提供默认配置，需要定制时封装还是有必要的



> `closeIcon`
> 
> > 理由是如果新人后续直接用antd modal,会有问题
> 
> 组件库默认情况下也只提供默认配置，需要定制时封装还是有必要的

好的，感谢回复。
