### ISSUE TITLE
Transfer -> List -> Search，无法自定义 Transfer 中 Search 框的 onChange 函数

### ISSUE THREAD

**Issue by FTAndy** [ant-design/ant-design#3570]
#### 发生问题的环境是：

- antd 版本: 1.11.2
- 操作系统及其版本: OS X 10.10
- 浏览器及其版本: Chrome 最新

#### 您做了什么？

引入 antd 了 Transfer

#### 您期待的结果是：

自定义 Transfer 中的 Search onChange 事件

#### 实际上的结果是：

源码中 Transfer 定义的事件写死了，建议加一个 Search onChange 接口

**Comment by FTAndy** [comment]
Transfer 文件引入无用的 Search 变量

**Comment by benjycui** [comment]
> Transfer 文件引入无用的 Search 变量

???

**Comment by FTAndy** [comment]
@benjycui ant-design/components/transfer/index.tsx 定义的 Search 没什么用，提醒一下而已。

Search 框那个我在外面组件引入解决了
