### ISSUE TITLE
Carousel支持鼠标滚轮或者触摸板滑动切换

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#35711]
### What problem does this feature solve?

有时候的轮播的dot太小，点击困难，系统通过鼠标滚轮或者触摸板滑动切换上一个或者下一个，也就是onWheel事件。

### What does the proposed API look like?

wheel={true}直接支持wheel事件，afterChange中获取切换后的通知。

**Comment by afc163** [comment]
https://react-slick.neostack.com/docs/api#swipe
https://react-slick.neostack.com/docs/api#draggable
