### ISSUE TITLE
useId warning

### ISSUE THREAD

**Issue by kirill-linnik** [ant-design/ant-design#35719]
### Reproduction link

https://github.com/kirill-linnik/react-redux

### Steps to reproduce

that something you don't see in the sandbox, but actually, while building it, you get warnings below

### What is expected?

no compilation errors

### What is actually happening?

during compilation, I get:

  WARNING in ./node_modules/antd/node_modules/rc-util/es/React/render.js 14:17-36
  export 'createRoot' (imported as 'ReactDOM') was not found in 'react-dom' (possible exports: __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, createPortal, findDOMNode, flushSync, hydrate, render, unmountComponentAtNode, unstable_batchedUpdates, unstable_createPortal, unstable_renderSubtreeIntoContainer, version)
   @ ./node_modules/antd/es/modal/confirm.js 17:0-89 63:4-16 89:6-17
   @ ./node_modules/antd/es/modal/index.js 2:0-112 7:9-16 7:17-25 14:9-16 14:17-25 18:9-16 18:17-28 22:9-16 22:17-26 29:9-16 29:17-28 42:15-32
   @ ./node_modules/antd/es/index.js 35:0-43 35:0-43
   @ ./src/components/Header.tsx 5:0-39 69:41-51 85:34-37
   @ ./src/App.tsx 8:0-41 73:79-85
   @ ./src/index.tsx 7:0-24 11:211-214

  WARNING in ./node_modules/rc-dialog/node_modules/rc-util/es/hooks/useId.js 21:38-49
  export 'useId' (imported as 'React') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
   @ ./node_modules/rc-dialog/es/Dialog/index.js 8:0-43 54:15-20
   @ ./node_modules/rc-dialog/es/DialogWrap.js 5:0-30 35:44-50 53:44-50
   @ ./node_modules/rc-dialog/es/index.js 1:0-38 2:15-25
   @ ./node_modules/antd/es/modal/Modal.js 18:0-31 102:42-48
   @ ./node_modules/antd/es/modal/index.js 1:0-34 10:12-23
   @ ./node_modules/antd/es/index.js 35:0-43 35:0-43
   @ ./src/components/Header.tsx 5:0-39 69:41-51 85:34-37
   @ ./src/App.tsx 8:0-41 73:79-85
   @ ./src/index.tsx 7:0-24 11:211-214

  WARNING in ./node_modules/rc-dialog/node_modules/rc-util/es/hooks/useId.js 23:9-20
  export 'useId' (imported as 'React') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
   @ ./node_modules/rc-dialog/es/Dialog/index.js 8:0-43 54:15-20
   @ ./node_modules/rc-dialog/es/DialogWrap.js 5:0-30 35:44-50 53:44-50
   @ ./node_modules/rc-dialog/es/index.js 1:0-38 2:15-25
   @ ./node_modules/antd/es/modal/Modal.js 18:0-31 102:42-48
   @ ./node_modules/antd/es/modal/index.js 1:0-34 10:12-23
   @ ./node_modules/antd/es/index.js 35:0-43 35:0-43
   @ ./src/components/Header.tsx 5:0-39 69:41-51 85:34-37
   @ ./src/App.tsx 8:0-41 73:79-85
   @ ./src/index.tsx 7:0-24 11:211-214

  WARNING in ./node_modules/rc-notification/node_modules/rc-util/es/React/render.js 14:17-36
  export 'createRoot' (imported as 'ReactDOM') was not found in 'react-dom' (possible exports: __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, createPortal, findDOMNode, flushSync, hydrate, render, unmountComponentAtNode, unstable_batchedUpdates, unstable_createPortal, unstable_renderSubtreeIntoContainer, version)
   @ ./node_modules/rc-notification/es/Notification.js 11:0-58 269:8-15 290:2-8
   @ ./node_modules/rc-notification/es/index.js 1:0-42 2:15-27
   @ ./node_modules/antd/es/message/index.js 5:0-45 95:2-28
   @ ./node_modules/antd/es/index.js 32:0-47 32:0-47
   @ ./src/components/Header.tsx 5:0-39 69:41-51 85:34-37
   @ ./src/App.tsx 8:0-41 73:79-85
   @ ./src/index.tsx 7:0-24 11:211-214

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 17 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
Please try to remove yarn.lock and reinstall node_modules.
