### ISSUE TITLE
http://10.244.30.23:7001/monitor

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design#3571]
在打包或者运行的时候突然出现，无法连接到这个ip的错误。

**Comment by afc163** [comment]
@sorrycc @pigcan

**Comment by sorrycc** [comment]
内网用户? 监控服务器挂了? @saiyagg

**Comment by WhatAKitty** [comment]
![image](https://cloud.githubusercontent.com/assets/4178729/19674837/529fda16-9abd-11e6-89b2-83ff07b18b13.png)
这个地址是做啥的？

**Comment by sorrycc** [comment]
内网打点统计的，有疑问内网提。

**Comment by WhatAKitty** [comment]
@sorrycc 。。。貌似是我理解错了。。我说的内网用户，是我处于内网环境，不是你们的内网用户。不过，发布版是否可以去除这一段监控？
