### ISSUE TITLE
Upload组件在 Stackblitz 中打开因为缺少引入react报错

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design#35722]
### Reproduction link

[https://ant.design/components/upload-cn/#components-upload-demo-avatar](https://ant.design/components/upload-cn/#components-upload-demo-avatar)

### Steps to reproduce

点击在 Stackblitz 中打开因为缺少引入react报错

### What is expected?

Upload组件在 Stackblitz 中打开可以正常运行

### What is actually happening?

Upload组件在 Stackblitz 中打开因为缺少引入react报错

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | windows |
| Browser | chrome |

---
应该在index.js和demo.js中引入React

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35695
