### ISSUE TITLE
Vite Build not recognize useForm hook

### ISSUE THREAD

**Issue by ngthuongdoan** [ant-design/ant-design#35720]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7cv18z)

### Step 2: Run ```preview``` command by Vite
This cause ERROR `z.useForm() is not a function`
### Step 3: Try to run ```serve``` command with the build folder
It still causes the same error

### What is expected?

It should not have this Error.

### What is actually happening?

The Error occurs whenever I run the built code, in the development, it's working fine.

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | react 17.0.2 |
| System | MacOS |
| Browser | Chrome |

**Comment by ngthuongdoan** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/45509523/170715303-fd328cb2-267c-4c87-995e-a4eed47e2a61.png">

Here is the error I got because it just happens when building, it's working fine in dev.

**Comment by flipace** [comment]
For others stumbling upon this issue - I encountered the same, but it turned out this happened because I imported like this:

`import { FormInstance, useForm } from 'antd/lib/form/Form';`

and switching to the `es` variant fixed it:

`import { FormInstance, useForm } from 'antd/es/form/Form';`
