### ISSUE TITLE
antd2.1.0 modal中嵌套tabs

### ISSUE THREAD

**Issue by gezhishoul** [ant-design/ant-design#3573]
#### 发生问题的环境是：

- antd 版本:2.1.0
- 操作系统及其版本: mac10.11.6
- 浏览器及其版本: chrome 53

#### 您做了什么？
modal 中嵌套tabs，tabs中有若干tab，数组循环插入

#### 您期待的结果是：
正常切换显示。

#### 实际上的结果是：
tab第一个可以显示，之后的tab无法显示其中的标签，但是html中存在这些标签

**Comment by ggd543** [comment]
Modal 中嵌入Tab，无法关闭Modal
