### ISSUE TITLE
Form.List中使用dependencies无效

### ISSUE THREAD

**Issue by AliyaLiu** [ant-design/ant-design#35732]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-list-jmehrx?file=/src/App.js)

### Steps to reproduce

两个输入框相互依赖，但是改变其中一个，并不会触发另一个输入框对当前改变的输入框的校验

### What is expected?

改变last或者first字段，另一个依赖的字段重新校验

### What is actually happening?

改变last或者first字段，另一个依赖的字段没有触发校验

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 17.0.2 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/form-list-forked-8ppnw9?file=/src/App.js
