### ISSUE TITLE
pop的小三角不兼容360浏览器

### ISSUE THREAD

**Issue by devchen13** [ant-design/ant-design#35735]
### Reproduction link

[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce

随便一个pop的小三角

### What is expected?

正常显示小三角

### What is actually happening?

正方形

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | win10 |
| Browser | 360或360极速 |

---
clip-path不兼容

**Comment by afc163** [comment]
建议使用 Chrome 最新版本

**Comment by jing-wu** [comment]
升级至最新的 4.20.7 后，箭头显示还有问题
<img width="318" alt="arrow" src="https://user-images.githubusercontent.com/6805536/170977804-d93f76c5-82ff-4a1d-84db-586065b26be6.png">

**Comment by devchen13** [comment]
> 

你好，有解决办法吗

**Comment by jing-wu** [comment]
暂时没有，等官方确认问题并修复吧
