### ISSUE TITLE
AutoComplete组件能不能获得焦点时不要出现下拉框体？

### ISSUE THREAD

**Issue by luchenwei9266** [ant-design/ant-design#3574]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本:macOs Sierra
- 浏览器及其版本:chrome 53.0.2785.143
#### 您期待的结果是：
AutoComplete组件只有onChange的时候才出现下拉框体

#### 实际上的结果是：
现在的结果是，如果一开始把dataSource绑定好，我只要一点击组件就会出现下拉框体。而不是当我输入值后才出现。其实我想要的效果就是你们官网实例的效果，但是你们官网的实例，那个是本身就没有绑定数据的(或者绑定的是空值)，所以当点击时不会出现下拉框体，而是输入值的时候才出现。

**Comment by benjycui** [comment]
用户不输入时，就不该绑定 `dataSource`。。都不知道用户的输入，何来 AutoComplete

**Comment by luchenwei9266** [comment]
嗯，是我理解错了这个组件的应用场景，不好意思啊。我是想着用这个来做类似于淘宝的搜索框。

**Comment by benjycui** [comment]
没问题的话，麻烦顺手吧 issue 关掉，谢谢。
