### ISSUE TITLE
Tree组件，动态的异步数据，tree无法自动展开，静态数据可以

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#35749]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-zhan-kai-zhe-die-tu-biao-antd-4-20-6-forked-pwo52g?file=/demo.js)

### Steps to reproduce

刷新demo可看
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/8169783/170443533-35e01d0d-2848-4829-8e45-3145afed6a53.png">

### What is expected?

期望结果是不管数据来源是什么，都能自动展开树节点

### What is actually happening?

实际结果是无法自动展开

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | masOS Monterey 12.1 |
| Browser | chrome 101.0.4951.64 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by rawbin-** [comment]
答案也在demo 里
