### ISSUE TITLE
最后一级的子集没有line

### ISSUE THREAD

**Issue by Chasen-Zhang** [ant-design/ant-design#35744]
### Reproduction link

[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce

同官网例子

### What is expected?

同官网例子

### What is actually happening?

最后一级没有线条显示

| Environment | Info |
| --- | --- |
| antd | 4.16.3 |
| React | 17.0.0 |
| System | macos window |
| Browser | chrome |

---
官网也是最后一级没有线条

![image](https://user-images.githubusercontent.com/15354455/170400482-ae7819b5-e852-4175-a466-eec8158450f1.png)

**Comment by afc163** [comment]
设计如此。

**Comment by Chasen-Zhang** [comment]
为啥这样设计呢@afc163
