### ISSUE TITLE
table横向滚动时select multiple选择框错位不收起

### ISSUE THREAD

**Issue by lyk248** [ant-design/ant-design#3575]
#### 发生问题的环境是：

- antd 版本: 1.6.5
- 操作系统及其版本: mac OS Sierra
- 浏览器及其版本: Chrome 54

#### 您做了什么？

在\<Table scroll={{ x: 2000 }} />中嵌入了\<Select multiple />

<image src="http://d.pr/i/EpG5+">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3487

**Comment by lyk248** [comment]
如果使用getPopupContainer渲染在table内部，当table只有1行时会有选项显示不完全的情况，而且至少能做到像单选下拉框那样在点击滚动条的时候让选项收起吧？
