### ISSUE TITLE
Callback for onChange fails for the first time in Form.Item wrapped component

### ISSUE THREAD

**Issue by Gurochka** [ant-design/ant-design#35755]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-20-6-forked-y0yek9?file=/demo.js)

### Steps to reproduce

Start to type digits to username field (The field should accept only letters)

### What is expected?

Digits will be ignored

### What is actually happening?

I can type digits with letters. But it works only for the first time - the field prohibits to type digits if erase everything or type letters first.

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | Windows 10 |
| Browser | Chrome 101.0.4951.67 |

---
The field works correctly if add preventDefault() and  stopPropagation() to onKeyPress callback.

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-usage-antd-4-20-6-forked-x2o319?file=/demo.js

`value` property is `undefined` initially which make Input a uncontrolled component:

```jsx
<Input value={undefined} />   // same behavior as <Input />
```

You can set`initialValue={{ usename: '' }}` that make a controlled component from beginning.

```jsx
<Input value="" />   // a controlled component!
```
