### ISSUE TITLE
用cdn引入antd，报Failed to parse SourceMap: /antd.min.js.map错误

### ISSUE THREAD

**Issue by raoenhui** [ant-design/ant-design#3576]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:window7
- 浏览器及其版本:chroma版本 53.0.2785.143 m

#### 您做了什么？

用cdn引入antd，cdn.bootcss.com/antd/2.0.1/antd.min.js和cdn.bootcss.com/antd/2.0.1/antd.min.css

#### 您期待的结果是：

无报错

#### 实际上的结果是：

报Failed to parse SourceMap: /antd.min.js.map错误

![image](https://cloud.githubusercontent.com/assets/14011130/19678764/b58d3650-9ad1-11e6-8fa1-9bc0af3bb07e.png)

**Comment by afc163** [comment]
升级 chrome 到 54 试试。

**Comment by afc163** [comment]
@raoenhui ping~

**Comment by afc163** [comment]
https://github.com/webpack/webpack/issues/2145#issuecomment-228311436 

应该是 Chrome 53 的 bug。

**Comment by raoenhui** [comment]
![image](https://cloud.githubusercontent.com/assets/14011130/20045327/0d2d9978-a4db-11e6-93d7-be152c89f290.png)

![image](https://cloud.githubusercontent.com/assets/14011130/20045293/d37a043c-a4da-11e6-8b14-2ad245a8a1b3.png)
升级完了，error变成warning:DevTools failed to parse SourceMap: http://localhost:8080/antd.min.js.map
这个map是什么东西
