### ISSUE TITLE
Wrap <Select> with <Tooltip>, hover on <Option> shoud not show tooltip

### ISSUE THREAD

**Issue by Justin-ZS** [ant-design/ant-design#35765]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-20-6-forked-eh4mu2?file=/demo.js)

### Steps to reproduce

click `<select />`, hover on opened menu  

### What is expected?

don't show tooltip when user hover on the select options. 

### What is actually happening?

tooltip gets shown

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | lastest |
| System | Macos |
| Browser | Chrome |

**Comment by AkanoCA** [comment]
I have the same issue. Is there any solution to this problem?

**Comment by Justin-ZS** [comment]
> I have the same issue. Is there any solution to this problem?

I found a workaround. Attach the toolip to a transparent node like this:
```js
<Select
  onMouseEnter={() => dropdownVisible || setShowTooltip(true)}
  onMouseLeave={() => setShowTooltip(false)}
  value={selectValue}
  onDropdownVisibleChange={open => {
    if (open) setShowTooltip(false)
    setDropdownVisible(open)
  }}
/>
<Tooltip
  visible={showTooltip}
  title={tooltipContent}
  placement='bottom'
>
  <div style={{ position: 'absolute', top: '20px', left: '45px' }}></div>
</Tooltip>
```

**Comment by IndProgo** [comment]
Another workaround
https://codesandbox.io/s/py6t3s?file=/demo.js
