### ISSUE TITLE
Form中使用RangePicker报错

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design#3577]
#### 发生问题的环境是：
- antd 版本: v2.0.1
- 操作系统及其版本: OSX 10.11.6 (15G31)
- 浏览器及其版本: chrome 54
#### 您做了什么？

引入了Form, DatePicker, Input, Modal

Form会动态变化，可能是一个DatePicker.RangePicker，也可能是一个Input
#### 您期待的结果是：

console不报错，可以继续选择日期范围
#### 实际上的结果是：

不能选择日期范围
#### 可重现的在线演示

http://codepen.io/zhaozhiming/pen/ZpPyxJ?editors=001

操作步骤：
1. 点击`show input`按钮，点击弹出框的`取消`按钮
2. 点击`show date`按钮，选择日期范围
3. console报错，日期不能选择

报错信息：

```
Uncaught TypeError: Cannot read property 'onChange' of undefined(…)
```

**Comment by zhaozhiming** [comment]
我跟踪了一下源码，发现Form中的RangePicker会进入下面这段代码，把`fieldsMeta[name]`删除了，然后导致报错。

### createBaseForm.js

```js
    saveRef: function saveRef(name, _, component) {
        if (!component) {
          // after destroy, delete data
          delete this.fieldsMeta[name];
          delete this.fields[name];
          delete this.instances[name];
          delete this.cachedBind[name];
          return;
        }
```

**Comment by RaoHai** [comment]
为什么 Input 要和 RangePicker 共用一个 id 呢？

**Comment by zhaozhiming** [comment]
表单里面的同一个东西，只是根据type不同会展示不同的组件

**Comment by RaoHai** [comment]
嗯。是 React 在更新 children 的时候先会 detachRef  一下：https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/src/renderers/shared/stack/reconciler/ReactRef.js#L39

这里处理 form 的 fieldsMeta 的时候木有考虑重复利用的情况……

你先不要用同一个 id， 可以暂时避开这个错误。具体问题我继续看。。

**Comment by zhaozhiming** [comment]
好的，加油💪

我的场景要是用两个id会比较麻烦，要写好多代码来校验 form submit，谢谢啦

**Comment by benjycui** [comment]
真心没必要用相同的 `id`，加上同样的前缀，submit 时处理一下就好：

```jsx
state.collectA: true; // 记录该提交 A 还是 B

{
  'prefix-A': ...,
  'prefix-B': ...,
}
```

**Comment by zhaozhiming** [comment]
@benjycui 使用不同id是可以规避，不过要多写一些判断代码
另外 @RaoHai 检查出来这个问题好像是 Form组件的一个Bug？

**Comment by zhaozhiming** [comment]
@benjycui 我现在如果用不同的id，在 form submit时会报另外一个id的field的错，代码如下：

```js
this.props.form.validateFields((errors, values) => {
  // id为foo的field通过了，
  // 但是id为bar的field报错，要求bar的field不能为空
  if (errors) return; 
}
```

所以我只能写成这样：

```js
this.props.form.validateFields((errors, values) => {
  if (errors) {
    if (this.state.type === 'date' && errors.foo) return;
    if (this.state.type === 'input' && errors.bar) return;
  }
}
```

所以我觉得这样写比较麻烦，不知道你说的方法是不是指这个？
另外不同的id对于取值也麻烦，要多写一些代码才能达到同样的效果。

**Comment by benjycui** [comment]
如果是动态增减的话，应该不会有报错 https://ant.design/components/form/#components-form-demo-dynamic-form-item

**Comment by zhaozhiming** [comment]
@benjycui 不是动态增加，是始终只有一个formItem，只不过formItem里面可能是 Input，也可以能是 RangePicker

**Comment by benjycui** [comment]
意思是你可以尝试动态表单域。。

**Comment by zhaozhiming** [comment]
我看了下动态表单域的方法，其实也是用不同的id来生成formItem，所以没有我的那个问题

```js
getFieldDecorator(`name${k}`, {})
```

**Comment by benjycui** [comment]
所以就没有这个问题。

```jsx
this.props.form.validateFields((errors, values) => {
  if (errors) {
    if (this.state.type === 'date' && errors.foo) return;
    if (this.state.type === 'input' && errors.bar) return;
  }
});
```

**Comment by zhaozhiming** [comment]
@benjycui 把我刚才又试了一下，好像是我的render方法有问题，现在不会有这个问题，谢谢啦

```js
this.props.form.validateFields((errors, values) => {
  if (errors) {
    if (this.state.type === 'date' && errors.foo) return;
    if (this.state.type === 'input' && errors.bar) return;
  }
});
```
