### ISSUE TITLE
flex布局下在FormItem中组织RangePicker时，较宽尺寸下出现悬浮层抖动

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#35779]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/biao-dan-bu-ju-antd-4-20-6-forked-kmo4nv?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

打开演示例子，重载页面后，点击展开日期范围选择，在左半边选择开始日期后，快速移动鼠标到右半边会出现悬浮层抖动情况，如下方动图所示：

![FormItem+日期范围选择抖动bug](https://user-images.githubusercontent.com/49147660/170676044-16b889a9-97ea-44fc-af22-c86c7d8cd4f6.gif)

关键部分示例源码：

```javascript
import React from "react";
import "antd/dist/antd.css";
import "./index.css";
import { Button, Form, DatePicker } from "antd";

const { RangePicker } = DatePicker;

const App = () => {
  return (
    <Form layout={"inline"}>
      <Form.Item label="Field A" style={{ flex: 1 }}>
        <RangePicker style={{ width: "100%" }} />
      </Form.Item>
      <Form.Item label="Field B" style={{ flex: 1 }}>
        <RangePicker style={{ width: "100%" }} />
      </Form.Item>
      <Form.Item style={{ flex: "none" }}>
        <Button type="primary">Submit</Button>
      </Form.Item>
    </Form>
  );
};

export default App;

```

### What is expected?

消除悬浮层抖动情况

### What is actually happening?

所描述条件下悬浮层抖动

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | latest |
| System | win11 |
| Browser | Chrome 98.0.4758.82 |

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/36507
Trace in new issue.
