### ISSUE TITLE
tsx中使用DatePicker，报错：“DatePicker”不能用作 JSX 组件。

### ISSUE THREAD

**Issue by btnkr** [ant-design/ant-design#35771]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-m3ji7s?file=/index.tsx)

### Steps to reproduce

ts中引入DatePicker，使用DatePicker

> node 16.15.0

> ts 4.7.2

> @types/react 18.0.9

> @types/react-dom 18.0.5

### What is expected?

不报错 正常使用

### What is actually happening?

“DatePicker”不能用作 JSX 组件。
  其实例类型 "Component<PickerProps<Moment> & { status?: "" | "warning" | "error" | undefined; }, unknown, any> & CommonPickerMethods" 不是有效的 JSX 元素。
    在这些类型中，"render()" 返回的类型不兼容。
      不能将类型“React.ReactNode”分配给类型“import("/Users/******/node_modules/@types/hoist-non-react-statics/node_modules/@types/react/index").ReactNode”。
        不能将类型“{}”分配给类型“ReactNode”。ts(2786)

<img width="825" alt="image" src="https://user-images.githubusercontent.com/46664126/170653055-42e60f0e-9f09-4e10-8530-1f70f7bd76e6.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/46664126/170652893-2ae3fc36-9c5f-4f28-8636-ff95529125f0.png">

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 17.0.2 |
| System | macOS Monterey12.3.1 |
| Browser | chrome 100.0.4896.127 |

**Comment by zombieJ** [comment]
你的重现看起来是好的

**Comment by zombieJ** [comment]
你的重现看起来没有问题？

**Comment by btnkr** [comment]
> 你的重现看起来没有问题？

我在package.json加上了
```
    "resolutions": {
        "@types/react": "17.0.45"
    }
```
这个问题就没了

之前@types/react版本是18.0.9

**Comment by afc163** [comment]
我 reopen 了 #34952，在这里跟踪
