### ISSUE TITLE
'RangePicker' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by kirill-linnik** [ant-design/ant-design#35788]
### Reproduction link

[https://github.com/kirill-linnik/react-redux/tree/main/src](https://github.com/kirill-linnik/react-redux/tree/main/src)

### Steps to reproduce

run `yarn` then `yarn start`. during compile time you get:

  [tsl] ERROR in Main.tsx(28,8)
        TS2786: 'RangePicker' cannot be used as a JSX component.
    Its instance type 'Component<RangePickerProps<Moment>, unknown, any> & CommonPickerMethods' is not a valid JSX element.
      The types returned by 'render()' are incompatible between these types.

### What is expected?

No compile error

### What is actually happening?

While this issue claimed to be fixed here: https://github.com/ant-design/ant-design/issues/34973 I still see it is not the case in the latest library (4.20.6). is it some regression?

p.s. yarn.lock and node_modules where deleted prior the test, so it is an absolutely clean and fresh version

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35441#issuecomment-1120995320

**Comment by kirill-linnik** [comment]
> [#35441 (comment)](https://github.com/ant-design/ant-design/issues/35441#issuecomment-1120995320)

great point. updated react types and error is gone. thank you!

**Comment by gabrielopeyemi** [comment]
I ran `"preinstall": "npx npm-force-resolutions"` but it throw few errors, errors are mainly using hooks wrongly, after fixing I ran `yarn add @types/react@latest`
