### ISSUE TITLE
Modal is not showing and blocks everything after upgrade to React 18

### ISSUE THREAD

**Issue by kirill-linnik** [ant-design/ant-design#35782]
### Reproduction link

[https://github.com/kirill-linnik/react-redux](https://github.com/kirill-linnik/react-redux)

### Steps to reproduce

yarn, yarn start. application has only one page - Main. there you see button: Open Modal. if you click on that, no other buttons work, everything is broken. code is very simple, you can check it here: https://github.com/kirill-linnik/react-redux/blob/main/src/pages/Main.tsx

### What is expected?

Modal window should show up and closed

### What is actually happening?

app is stuck, nothing happens

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
Please try to remove yarn.lock and reinstall node_modules.

**Comment by kirill-linnik** [comment]
> Please try to remove yarn.lock and reinstall node_modules.

yeah, it works. now I have a different issue with another element, should create new ticket :(
