### ISSUE TITLE
<Form.Item name="nodeName" break everything

### ISSUE THREAD

**Issue by ALEUT** [ant-design/ant-design#35780]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-94lqd0?file=/index.js)

### Steps to reproduce

Open reproduction, click on select

### What is expected?

Select is opened

### What is actually happening?

elem.nodeName.toLowerCase is not a function

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 17.0.2 |
| System | Windows 11 |
| Browser | 102.0.5005.63 |

**Comment by afc163** [comment]
https://github.com/facebook/react/issues/6284
