### ISSUE TITLE
Badge 组件渲染的颜色跟设置的不一样

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#35784]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-cai-hui-biao-antd-4-20-6-forked-q390xw?file=/demo.js)

### Steps to reproduce

文字和左侧色标给的同样的颜色，渲染结果不一样

### What is expected?

期望给什么颜色就渲染什么颜色，给一样颜色的时候文字和色标颜色能一样

### What is actually happening?

实际结果色标渲染的不是给的颜色
<img width="213" alt="image" src="https://user-images.githubusercontent.com/8169783/170813577-09b059c6-04df-47b3-bd00-ead136f4fb09.png">

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | masOS Monterey 12.1 |
| Browser | chrome 101.0.4951.64 |

**Comment by afc163** [comment]
这些名称https://codesandbox.io/s/duo-cai-hui-biao-antd-4-20-6-forked-u8tp9c?file=/demo.js
