### ISSUE TITLE
Icon使用本地部署时报错

### ISSUE THREAD

**Issue by tianyacsdn** [ant-design/ant-design#3579]
Failed to decode downloaded font: http://127.0.0.1:8080/iconfont/iconfont.woff
OTS parsing error: invalid version tag
Failed to decode downloaded font: http://127.0.0.1:8080/iconfont/iconfont.ttf
OTS parsing error: invalid version tag

**Comment by afc163** [comment]
https://github.com/webpack/webpack/issues/1468
http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts

**Comment by K-walker** [comment]
你好，我使用roadhog脚手架，在.roadhogrc中配置了icon-url ，也出现这种错误, 但是[webpack/webpack#1468](https://github.com/webpack/webpack/issues/1468) 给出的方案，是在webpack.config.js 中配置loader，我想问，在roadhog中该如何去弄啊。麻烦了！

**Comment by SanPy** [comment]
@K-walker 最后解决了吗
