### ISSUE TITLE
Progress: circle模式下支持steps

### ISSUE THREAD

**Issue by yykoypj** [ant-design/ant-design#35802]
### What problem does this feature solve?

Progress在现有circle模式下传入steps参数并不起效果
反而会使中间内容被遮盖

### What does the proposed API look like?

与现有steps使用方法一致

**Comment by afc163** [comment]
预期长什么样子？

**Comment by yykoypj** [comment]
> 预期长什么样子？

类似这样
![image](https://user-images.githubusercontent.com/15713772/170917324-72097875-a24b-46ba-8564-8cf99aa9e0e0.png)

**Comment by afc163** [comment]
试试给 https://github.com/react-component/progress 来个 PR 如何？

**Comment by yykoypj** [comment]
我试试搞一个～😄

**Comment by afc163** [comment]
@yykoypj antd 还没相应做修改。

**Comment by afc163** [comment]
@yykoypj

**Comment by afc163** [comment]
ping

**Comment by yykoypj** [comment]
pong~
换了工作事情有点多，这就来～
