### ISSUE TITLE
InputNumber的defaultValue数据获取问题

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3580]
父组件中getInitialState定义了一个state比如temp，我想做的是父组件某个事件响应函数改变temp的值，改变之后的值则作为InputNumber组件的defaultValue值，但是这样行不通，因为defaultValue只会生效一次并且值为getInitialState时的空值。请问该怎样处理？

**Comment by afc163** [comment]
value

http://facebook.github.io/react/docs/forms.html#controlled-components
