### ISSUE TITLE
[AutoComplete] filterOption doesn't update inputValue if value has changed

### ISSUE THREAD

**Issue by Gurochka** [ant-design/ant-design#35809]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/non-case-sensitive-autocomplete-antd-4-20-7-forked-svricc?file=/demo.js)

### Steps to reproduce

1. type "bd" 
[result]: autocomplete list is empty
2. click outside input 
[result]: input value resets to "" because autocomplete list is empty
3. click to input 
[result]: autocomplete list doesn't appear because of old innerValue inside filterOption function

### What is expected?

1. type "bd" 
[result]: autocomplete list is empty
2. click outside input 
[result]: input value resets to "" because autocomplete list is empty
3. click to input 
[result]: full autocomplete list appears with all options

### What is actually happening?

innerValue doesn't represent value inside filterOption function if value has been reset

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by MuxinFeng** [comment]
我来试试看提个pr

**Comment by Can-Chen** [comment]
我试试

**Comment by ALCLCGS** [comment]
I have the same problem, did you solve it please?

**Comment by wh4t3ver-r** [comment]
@ALCLCGS @Gurochka 
I tried to reproduce this bug using antd 5.18.0 and it seems that it is no longer there. I think it was fixed in some previous release.

I believe that this issue can be closed.
