### ISSUE TITLE
Modal支持类似message.config的api

### ISSUE THREAD

**Issue by eightHundreds** [ant-design/ant-design#35819]
### What problem does this feature solve?

message.config支持配置默认的挂载点. message.config({getContainer})

但Modal.info/error... 等api不支持.

在qiankun的experimentalStyleIsolation模式下, 必须让之前往body插入的dom, 放到微前端挂载点

### What does the proposed API look like?

Modal.config

**Comment by MadCcc** [comment]
静态方法已经不推荐了
建议使用 hooks 来调用 Modal，使用 ConfigProvider 来配置 PopupContainer

**Comment by zhenzhenChange** [comment]
使用`ConfigProvider`配置又太统一化了，比如我只想全局设置`Select`的，但是会把所有的`overlay`类组件都设置了，有时候确实不是我所需要的，因为有些业务里的嵌套弹窗、浮层特别多，统一设置就炸了，所以如果这个全局配置能分一下组件就更好了：`getModalContainer/getSelectContainer....` 这样
