### ISSUE TITLE
table 固定列设置 scroll.x 后，拖动浏览器窗口使横向滚动条消失，这时候固定列的阴影样式残留

### ISSUE THREAD

**Issue by woowalker** [ant-design/ant-design#35817]
### Reproduction link

[https://stackblitz.com/edit/react-qsv4wk?file=demo.js](https://stackblitz.com/edit/react-qsv4wk?file=demo.js)

### Steps to reproduce

官网例子就能复现

### What is expected?

横向滚动条消失时，固定列的阴影样式消失

### What is actually happening?

横向滚动条消失时，固定列的阴影样式没有消失

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chorme 101.0.4951.54 |

**Comment by hs4601** [comment]
我也遇到这个问题了，antd的版本是4.21.0

**Comment by EvilChan** [comment]
奇怪的是，dev的时候是没问题，build就有问题了

**Comment by qiuziGirl** [comment]
> 我也遇到这个问题了，antd的版本是4.21.0

+1

**Comment by horseson2018** [comment]
+1, 顺便问一下为什么table的宽度这么难搞

**Comment by horseson2018** [comment]
rc的问题🤔父债子还🤣
