### ISSUE TITLE
Table设置scroll.x='max-content'时，column.width和column.ellipsis失效

### ISSUE THREAD

**Issue by lxow456** [ant-design/ant-design#35815]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-vd2tlu)

### Steps to reproduce

address这一列已经设置了ellipsis和width，但这一列被内容撑得非常宽

### What is expected?

address列宽度固定，且内容超过宽度后自动省略并打点

### What is actually happening?

address列被内容撑得很宽，也没自动省略、打点

| Environment | Info |
| --- | --- |
| antd | 4.19.2 |
| React | 16.14.0 |
| System | windows 10 |
| Browser | Chrome 102.0.5005.61 |

**Comment by afc163** [comment]
`scroll.x='max-content'` 代表内容会尽可能撑满宽度，因此 ellipsis 是失效的。两者基本上是矛盾的。

**Comment by guaizi149** [comment]
> `scroll.x='max-content'` 代表内容会尽可能撑满宽度，因此 ellipsis 是失效的。两者基本上是矛盾的。

如果table的列是动态的，这时候如果不设置scroll.x='max-content'就不会出现横向滚动条，设置之后，就会导致column.width和column.ellipsis失效

**Comment by shufangu** [comment]
> > `scroll.x='max-content'` 代表内容会尽可能撑满宽度，因此 ellipsis 是失效的。两者基本上是矛盾的。
> 
> 如果table的列是动态的，这时候如果不设置scroll.x='max-content'就不会出现横向滚动条，设置之后，就会导致column.width和column.ellipsis失效

解没

**Comment by CorgiTT** [comment]
> > > `scroll.x='max-content'` 代表内容会尽可能撑满宽度，因此 ellipsis 是失效的。两者基本上是矛盾的。
> > 
> > 
> > 如果table的列是动态的，这时候如果不设置scroll.x='max-content'就不会出现横向滚动条，设置之后，就会导致column.width和column.ellipsis失效
> 
> 解没

我先给每个动态列一个固定的宽度，计算出他们的宽度之和x，然后赋值的，算是基本能解决这个问题

**Comment by LLmoskk** [comment]
简单的做法可以给你的列设置对应的 className 名 然后在 css 设置上 min-width，就可以避免 scroll max-content 平分了宽度 @shufangu
