### ISSUE TITLE
请问Table组件的表格头如何设置背景颜色

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design#3581]
是否有专门的参数配置可以设置表头的背景色？
我看官方的例子都是有灰色的表头，
按照例子拷贝到本地为啥没有表头色了呢，
请问哪个参数可以配置。
小弟的确是找了没找到。

**Comment by benjycui** [comment]
样式覆盖，不过还是建议遵循 Ant Design 的规范。
