### ISSUE TITLE
Menu 当 菜单项为2个的时候会无限闪动

### ISSUE THREAD

**Issue by n0ruSh** [ant-design/ant-design#35816]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/menu-keep-flashing-isjv70)

### Steps to reproduce

1. 打开上面的 Codesandbox 链接，看到菜单项无限闪动
2. 反注释注释调的代码，使菜单项为3个。闪动问题消失

### What is expected?

不要闪动

### What is actually happening?

无限闪动

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
加一下样式如何？https://codesandbox.io/s/menu-keep-flashing-forked-gcpccq

**Comment by MadCcc** [comment]
v5 就会默认引入样式了

**Comment by n0ruSh** [comment]
引入样式之后确实就没问题了。

**Comment by limuyao1996** [comment]
> 

请教下，我这边用 next + antd5，遇到一样的问题，不确定是不是 next 打包antd 没有默认引入样式 ，但是 v5 用的 css-module 该怎么手动引样式呢？

**Comment by limuyao1996** [comment]
> v5 就会默认引入样式了

@MadCcc 
请教下，我这边用 next + antd5，遇到一样的问题，不确定是不是 next 打包antd 没有默认引入样式 ，但是 v5 用的 css-module 该怎么手动引样式呢？
