### ISSUE TITLE
希望被form包裹的组件可以选择不受form的影响

### ISSUE THREAD

**Issue by hellowuxin** [ant-design/ant-design#35821]
### What problem does this feature solve?

自定义Item控件时，使用了select组件用于搜索用户，但受到了form的样式影响（添加了form的类名），希望能提供一个参数来控制组件不受form的影响。
可以让用户自己决定哪些组件受form的控制，那些组件不受form的控制。

### What does the proposed API look like?

```jsx
<Select noForm/>
```

**Comment by afc163** [comment]
具体有哪些影响？

**Comment by hellowuxin** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-jffh1z?file=/index.js

**Comment by MadCcc** [comment]
4.20.x 引入的 feature，之前都是用样式覆盖的，所以影响不到 Modal 里的组件，现在是用 context 传递信息，Modal 里的组件也会受到 Form 影响。默认应该屏蔽 Form 样式

**Comment by MadCcc** [comment]
综合起来考虑了一下，4.20.x 之后类似 Modal 或者 Drawer 里的组件的 `status` `feedback` 等实际上都会受外层 Form 的影响，所以还是可以加一个 prop 让用户自己控制是否接收 Form 提供的样式

**Comment by hellowuxin** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-jffh1z?file=/selectUser.js

**Comment by zhenzhenChange** [comment]
这个问题确实是会，主要是校验状态的影响，需要给校验状态断言：
```html
<Form.Item validateStatus="success"  />
```

**Comment by hellowuxin** [comment]
这个可以解决校验样式的问题，但是select组件还有受其他样式影响：在form下，宽度被设为100%。
------------------ 原始邮件 ------------------
发件人: zhenzhenChange ***@***.***&gt;
发送时间: 2022年6月1日 11:09
收件人: ant-design/ant-design ***@***.***&gt;
抄送: wuxin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ant-design/ant-design] 希望被form包裹的组件可以选择不受form的影响 (Issue #35821)





 
这个问题确实是会，主要是校验状态的影响，需要给校验状态断言：
 <Form.Item validateStatus="success"  /&gt;

**Comment by zhenzhenChange** [comment]
> 这个问题确实是会，主要是校验状态的影响，需要给校验状态断言： ``` <Form.Item validateStatus="success" /> ``` `noStyle`并没有完全清除这部分样式
> 这个可以解决校验样式的问题，但是select组件还有受其他样式影响：在form下，宽度被设为100% ![image](https://user-images.githubusercontent.com/37543498/171320918-768b65bf-8ab7-4ee5-88b5-9b44487769d0.png)

这里的宽度好像要设置为`auto`，不仅是这个，分页组件放在`Form.Item`下，它的页码选择器的宽度也会异常，我反正全局设置`auto`就行了

**Comment by hellowuxin** [comment]
全局覆盖样式吗？
目前我是覆盖样式 + 设置校验状态掩盖了受`Form`影响的问题，但还是希望之后可以有更好的方法去避免这种影响

**Comment by MadCcc** [comment]
看起来 noStyle 在嵌套下还是有点问题，可以先试试给最外层的 Form.Item `noStyle`，不要嵌套。稍后修复。
https://codesandbox.io/s/antd-reproduction-template-forked-06yr8o?file=/index.js

**Comment by larryspace** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-jffh1z?file=/selectUser.js 添加`noStyle`后，还是有样式影响 ![image](https://user-images.githubusercontent.com/37543498/171147350-7339723a-caf1-4b48-99e3-d273b50392bf.png)

一样的问题，弹窗里面的表单都被Form.Item影响，包括表格的分页器组件，请问有解决方案了吗？

**Comment by idler8** [comment]
官方的Form太庞大复杂了，自定义需求高可以试试这个[`@idler8/observer`](https://github.com/idler8/observer)
@larryspace

**Comment by yoyo837** [comment]
> ### What problem does this feature solve?
> 自定义Item控件时，使用了select组件用于搜索用户，但受到了form的样式影响（添加了form的类名），希望能提供一个参数来控制组件不受form的影响。 可以让用户自己决定哪些组件受form的控制，那些组件不受form的控制。
> 
> ### What does the proposed API look like?
> ```js
> <Select noForm/>
> ```

等同于 3.x 的 没有使用 `getFieldDecorator` 的 `<Form.Item>`, 只想要布局, 不要表单.
