### ISSUE TITLE
table cloums 自定义render，使用了state属性的render函数不会更新

### ISSUE THREAD

**Issue by qietuzi** [ant-design/ant-design#35820]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/table-cloums-zi-ding-yi-render-shi-yong-liao-stateshu-xing-de-renderhan-shu-bu-hui-geng-xin-ltex8u)

### Steps to reproduce

1. 设置一个外部state
2. 在render函数中使用该状态
3. 更新state中的状态
4. render函数如果使用了该状态，应该更新

### What is expected?

组件state更新，使用了组件state的render函数应该更新。

或者提供相关api禁止对cell进行缓存。

### What is actually happening?

组件state更新，但是使用了组件state的render函数未更新

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 16.13.1  |
| System | mac/windows |
| Browser | 102.0.5005.61 |

---
这个问题是rc-table 7.23.0 更新后产生的。首先rc-table的这个更新有利于性能提升是肯定的，rc-table Cell 对自定义组件进行了缓存，另外由于是外部state发生了改变，所以无法检测到更新。

但是根据索引或者外部依赖的变化进行更新操作是非常常见的业务场景。否则每一次操作都对数据源进行操作，特别是数据源层级比较深的时候，这样在代码层面就是一个灾难。虽然这样会导致额外的渲染开销，但是在大部分情况下不必担心该问题。

**Comment by zombieJ** [comment]
Cell 缓存机制需要再整理一下，把 render 渲染更新和 Internal Update 切分开来。

**Comment by afc163** [comment]
这样可以 https://codesandbox.io/s/table-cloums-zi-ding-yi-render-shi-yong-liao-stateshu-xing-de-renderhan-shu-bu-hui-geng-xin-forked-qdijn5?file=/src/App.js

**Comment by MadCcc** [comment]
> 这样可以 https://codesandbox.io/s/table-cloums-zi-ding-yi-render-shi-yong-liao-stateshu-xing-de-renderhan-shu-bu-hui-geng-xin-forked-qdijn5?file=/src/App.js

可以写个 FAQ 了，之前也有类似的 issue，不过把 columns 写到 render 里确实有点反直觉

**Comment by afc163** [comment]
写到 render 里这样 columns 每次渲染引用都不一样，所以能 rerender。不过这应该还是 bug。

**Comment by MadCcc** [comment]
>  Table `colums.render` only support returning ReactNode

Trace in https://github.com/ant-design/ant-design/issues/34087

**Comment by leiyangs** [comment]
版本5升级了吗？好像还是不能实时获取组件的state @MadCcc

**Comment by reinaldo-teixeira** [comment]
Hi @MadCcc, I'm facing the same error, has this been done yet?
