### ISSUE TITLE
is the scroll behavior normal?

### ISSUE THREAD

**Issue by alanhaledc** [ant-design/ant-design#35825]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-20-6-forked-nl8w2z)

### Steps to reproduce

- open the select options box
- continuously scroll down the option items until to the bottom of box then the page scroll down to bottom.
- continuously scroll up the option items until to the top of box then the page scroll up to top.

### What is expected?

the scroll for select options box do not trigger page scroll.

### What is actually happening?

the scroll for select options box trigger page scroll.

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 16.14.0 |
| System | macOS v12.4 |
| Browser | Chrome v102.0.5005.61  |

---
I don't know if it is normal scroll behavior. and how to avoid it?

**Comment by MadCcc** [comment]
https://codesandbox.io/s/kind-platform-xihnuu
The simplest demo.
