### ISSUE TITLE
Tooltip does not display correctly when use getPopupContainer in Input suffix 

### ISSUE THREAD

**Issue by phuhd-0935** [ant-design/ant-design#35833]
### Reproduction link

[https://stackblitz.com/edit/react-eu1t9a?file=demo.js](https://stackblitz.com/edit/react-eu1t9a?file=demo.js)

### Steps to reproduce

- Import Input, Tooltip component
- Add Tooltip to suffix (prop of Input)
- Add prop getPopupContainer to Tooltip
- Wrapped icon svg/ img inside Tooltip
- Hover into icon 

### What is expected?

- Tooltip is displayed correctly

### What is actually happening?

Tooltip does not display correctly when use getPopupContainer in Input suffix  (wrapped icon inside tooltip)

| Environment | Info |
| --- | --- |
| antd | 4.18.8 |
| React | 17 |
| System | Node 14 |
| Browser | Chrome 92 |

**Comment by afc163** [comment]
You cannot insert dom node into `<img />`.

```diff
+ getPopupContainer={(triggerNode) => triggerNode}
- getPopupContainer={(triggerNode) => triggerNode.parentNode}
```

https://stackblitz.com/edit/react-eu1t9a-7jppup?file=demo.js

**Comment by phuhd-0935** [comment]
@afc163 Special thanks, but what about typescript version ? 
`ype '(triggerNode: HTMLElement) => ParentNode | null' is not assignable to type '(triggerNode: HTMLElement) => HTMLElement'.
  Type 'ParentNode | null' is not assignable to type 'HTMLElement'.
    Type 'null' is not assignable to type 'HTMLElement'.`
