### ISSUE TITLE
markdown supports ts code

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#3583]
needs ts examples to test whether ts type is correct

**Comment by benjycui** [comment]
It seems that it is impossible to test TypeScript in Markdown, for editor(VS Code) doesn't support TypeScript in Markdown.

**Comment by benjycui** [comment]
But, we can add a file, such as `button/demo/type.test.tsx`, to test TypeScript definition.

**Comment by yiminghe** [comment]
```
include(./demo.tsx)
```

**Comment by bang88** [comment]
Write tests is recommend

**Comment by yiminghe** [comment]
needs example for both typescript and js like angular2 docs

**Comment by benjycui** [comment]
不做 `include`，直接约定文件名就好？

**Comment by yiminghe** [comment]
http://docutils.sourceforge.net/docs/ref/rst/directives.html#include

**Comment by benjycui** [comment]
antd 没计划支持，antd-mobile 已经支持。
