### ISSUE TITLE
select放在form里面，select多选的情况，动态赋值value不生效

### ISSUE THREAD

**Issue by Meihualu-cc** [ant-design/ant-design#35840]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiang-ying-shi-maxtagcount-antd-4-20-7-forked-knec4v?file=/demo.js)

### Steps to reproduce

多选框做了限制 只能选三个 select动态赋值打印出来是对的但是显示不对

### What is expected?

期望如官方api所述：指定当前选中的条目，多选时为一个数组。（value 数组引用未变化时，Select 不会更新），其中value 数组引用未变化时，Select 不会更新   这里没满足

### What is actually happening?

其中value 数组引用未变化时，Select 更新了显示效果更新了

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 16.14.0 |
| System | Windows 10 专业版 |
| Browser | 谷歌101.0.4951.67（正式版本） |

**Comment by afc163** [comment]
<img width="1228" alt="图片" src="https://user-images.githubusercontent.com/507615/171311321-343467b2-230a-4565-9830-daaec26c7856.png">

https://ant.design/components/form-cn/#API

**Comment by Meihualu-cc** [comment]
> 已解决 非常感谢！
