### ISSUE TITLE
文档版本未同步

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#35846]
### Reproduction link

[https://ant-design.antgroup.com/components/overview-cn/](https://ant-design.antgroup.com/components/overview-cn/)

### Steps to reproduce

其它几个官网（镜像）都是 v4.20.7 了
这个里面还是 v4.20.6
不知道只是显示的问题，还是确实是版本没对上

### What is expected?

需要同步 v4.20.7 的文档

### What is actually happening?

版本是 v4.20.6 的

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 16 |
| System | Windows 10 x64 |
| Browser | Edge 最新版 |

**Comment by PeachScript** [comment]
镜像站已更新，感谢反馈 ❤️

**Comment by zhenzhenChange** [comment]
https://ant-design.antgroup.com/index-cn

还是有这个问题，镜像站比主站慢一个版本

**Comment by PeachScript** [comment]
cc @MadCcc 需要更新镜像站

**Comment by zhenzhenChange** [comment]
@PeachScript [镜像站](https://ant-design.antgroup.com/index-cn)的版本又双叒叕没跟上主站，这是自动同步的还是人工发布？建议每次发版后都访问一下镜像站确保同步。

**Comment by PeachScript** [comment]
人工的…受限于平台流程自动估计搞不了，但需要加到发布流程里了，不然负责发版的同学忘记是大概率事件，感谢多次反馈🤦‍♂️

cc @zombieJ @MadCcc 两位看看

**Comment by zhenzhenChange** [comment]
辛苦了

**Comment by afc163** [comment]
https://ant-design.gitee.io/index-cn 是自动同步的，如果速度尚可可以访问这个。

**Comment by zhenzhenChange** [comment]
`gay ee`上的是同步，不过不是很稳定，区域网络有时候访问也慢，主要是这个 https://ant-design.antgroup.com/index-cn
