### ISSUE TITLE
自定义FORM元素，能否给出个详细API，是否是这样使用？

### ISSUE THREAD

**Issue by cxd7744556** [ant-design/ant-design#3585]
### 项目中肯定会有一些输入模型antd无法支持，但是从官网找不到解决方案，经过尝试我解决了向props.form中的指定id写入value，但是不知道是不是正规写法?

```
<FormItem
    label="城市:"
    >
        {getFieldDecorator('city', {  })(
            //自定义城市选择器
            <CityPick/>
        )}
</FormItem>
```

在组件CityPick中通过props.value获取值，通过props.onchange(newValue)改变整个form的city字段的值。通过向onChange中传值的方式，不知道这种方式是不是正确方式，有没有详细文档提供，或者以后能否补全这一块的说明。

**Comment by afc163** [comment]
这个文档确实应该补齐。https://github.com/ant-design/ant-design/issues/3302#issuecomment-252805024
