### ISSUE TITLE
TreeSelect开启treeCheckable以及labelInValue后，搜索选中异常

### ISSUE THREAD

**Issue by ShawnLyn** [ant-design/ant-design#35862]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-bouman-ut234x?file=/src/App.js)

### Steps to reproduce

手动输入搜索树节点并选中，第二次选择内容后异常
<img width="466" alt="image" src="https://user-images.githubusercontent.com/12963987/171405161-635562ba-3c5a-488a-b495-aa1c29063616.png">

### What is expected?

选中数据正常

### What is actually happening?

选中异常

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 16.12.0 |
| System | Windows/Mac |
| Browser | Chrome>=86.0 |

**Comment by lzecheng** [comment]
异步加载，编辑回填时，删除选项时，未加载出的选项也会出现这个问题

**Comment by MadCcc** [comment]
目前不会缓存删除掉的节点，所以会丢失信息。
建议保证能够选中的节点稳定，选中的节点会从 `treeData` 中提取信息。

**Comment by ShawnLyn** [comment]
onSearch时向服务端发起请求是一个很常见的使用场景，搜索完之后自然而然的节点就会发现改变，无法认同你给出的关闭理由。

**Comment by hasnum-stack** [comment]
> 目前不会缓存删除掉的节点，所以会丢失信息。 建议保证能够选中的节点稳定，选中的节点会从 `treeData` 中提取信息。

select的labelInValue在没有节点时进行选择不会丢失label
TreeSelect会

**Comment by dydanyu** [comment]
请问这个问题怎么解决？
