### ISSUE TITLE
Select中的onFocus事件没有执行

### ISSUE THREAD

**Issue by ptlinyi** [ant-design/ant-design#3587]
#### 发生问题的环境是：

- antd 版本: 2.0
- 操作系统及其版本: Mac OS Sierra
- 浏览器及其版本:chrome 54.0
#### 您做了什么？

引用antd的Select，设置onFocus事件
#### 您期待的结果是：

执行onFocus事件
#### 实际上的结果是：

没有执行onFocus事件

**Comment by ptlinyi** [comment]
Select放在InputGroup中

**Comment by ptlinyi** [comment]
onClick事件也没有执行
但onBlur事件有执行

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
因为 Select 本来就没有这两个事件啊。。

即使你不放在 InputGroup 里面都不会触发这两个事件，提 issue 就不能走点心。。

**Comment by afc163** [comment]
需要补充 onFocus 和 onBlur 对应。

**Comment by ptlinyi** [comment]
https://ant.design/components/select/
那个搜索框的Demo里是有onFocus事件的，但实际执行没有，我没做什么特别的处理，直接拷的Demo的代码嵌到我的应用里的，你们要可重现的例子，直接用这个Demo，在onFocus时输出控制台应该就能看到没被执行了。
