### ISSUE TITLE
Tree component leaf animation is twitching when its key property gets updated

### ISSUE THREAD

**Issue by vytska** [ant-design/ant-design#35878]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-frost-fvyofn)

### Steps to reproduce

Make key attribute of tree component leaf updatable and update its state

### What is expected?

Leaf animation remains still

### What is actually happening?

Leaf component is visibly jumping to tree base position and back again

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 18.1.0 |
| System | macOS 12.3.1 |
| Browser | Chrome 101.0.4951.64 |

**Comment by MadCcc** [comment]
`key` is recommended to remain stable, since it is used to specify items in list.
