### ISSUE TITLE
类型“FormListFieldData”上不存在属性“fieldKey”。

### ISSUE THREAD

**Issue by nanianlisao** [ant-design/ant-design#35883]
### Reproduction link

[https://www.baidu.com/](https://www.baidu.com/)

### Steps to reproduce

类型“FormListFieldData”上不存在属性“fieldKey”。

### What is expected?

类型 FormListFieldData 包含 fieldKey

### What is actually happening?

类型“FormListFieldData”上不存在属性“fieldKey”。

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 17.0.2 |
| System | mac 12.1 |
| Browser | chrome |

---
antd@4.17.0 移除了FormListFieldData中的fieldKey 老项目未锁定antd版本  重新install后报错

**Comment by afc163** [comment]
有重现链接么？
