### ISSUE TITLE
v4.20.7 transfer 在非严格模式下，选中父节点，再选中任意一个子节点，父节点勾选状态没有被取消掉

### ISSUE THREAD

**Issue by chseahai** [ant-design/ant-design#35880]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

注释掉checkStrictly, 然后选中父节点 0-1， 在点击其子节点0-1-1，此时0-1的选中状态无法取消掉

### What is expected?

注释掉checkStrictly, 然后选中父节点 0-1， 在点击其子节点0-1-1，此时0-1的选中状态已经取消掉了，此时只选中0-1-0

### What is actually happening?

注释掉checkStrictly, 然后选中父节点 0-1， 在点击其子节点0-1-1，此时0-1的选中状态无法取消掉

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 16.12.0 |
| System | window |
| Browser | google |

**Comment by chseahai** [comment]
https://codesandbox.io/s/tree-transfer-antd-4-20-7-forked-3zskwt
<img width="1536" alt="transfer" src="https://user-images.githubusercontent.com/22994896/171582650-8f48ba2f-63e6-401f-a1bf-8846cce4ff95.png">

**Comment by Julycc41** [comment]
你好解决了吗 我也发现了这个问题

**Comment by WaveRunning** [comment]
确实会有这个问题，一旦是tree类型 并且父子关联就会有这个问题。
