### ISSUE TITLE
antd 4.19.0版本出现radio蓝点不居中

### ISSUE THREAD

**Issue by 1144075799** [ant-design/ant-design#35890]
### Reproduction link

[https://ant.design/components/radio-cn/](https://ant.design/components/radio-cn/)

### Steps to reproduce

              <div>
                    <Radio.Group onChange={(e)=>setIsComfirmPrice(e.target.value)} value={isConfirmPrice}>
                        <Radio value={1}>确认价格</Radio>
                        <Radio value={2}>取消确认</Radio>
                    </Radio.Group>
                </div>

### What is expected?

radio蓝点居中

### What is actually happening?

radio蓝点不居中

| Environment | Info |
| --- | --- |
| antd | 4.19.0 |
| React | 16 |
| System | macOS |
| Browser | Google Chrome 102.0.5005.61 |

**Comment by 1144075799** [comment]
演示的地址： https://codesandbox.io/embed/antd-reproduction-template-forked-z9tdke?fontsize=14&hidenavigation=1&theme=dark

**Comment by CNFeffery** [comment]
没看到有问题啊，你是不是项目里有其他版本的antd的css样式文件干扰了
![image](https://user-images.githubusercontent.com/49147660/171631718-479a841b-c178-4ad4-ab6c-bc079183fd93.png)

**Comment by yll0910** [comment]
我也是同样的问题，我的antd版本是4.16，radio这个蓝点就是刚进入的时候会错位，然后刷新一下又好了，你这个是怎么解决的呢
![image](https://user-images.githubusercontent.com/44368783/185026113-be77e751-1962-4a3a-97dc-3534728c54e8.png)

**Comment by bearguo** [comment]
应该是antd版本不同造成的样式覆盖，可能是微前端下主应用没做样式隔离导致的
我的一个项目主应用antd4.18.8，子应用4.16.5，复现了这个问题
4.18中radio的选中样式比4.16多了个margin-top:-8px; margin-left:-8px

**Comment by yll0910** [comment]
> 应该是antd版本不同造成的样式覆盖，可能是微前端下主应用没做样式隔离导致的 我的一个项目主应用antd4.18.8，子应用4.16.5，复现了这个问题 4.18中radio的选中样式比4.16多了个margin-top:-8px; margin-left:-8px

我反正试着把版本锁了下，确实没出现在这个问题了，但是没注意到是主应用没隔离，非常感谢我终于知道了是这个原因。
