### ISSUE TITLE
版本： 1.11.0  ，系统：windows，谷歌浏览器，引入分页组件，选中默认页码时，有时候页码不会高亮，有时候会高亮。

### ISSUE THREAD

**Issue by headforstars** [ant-design/ant-design#3589]
#### 发生问题的环境是：

- antd 版本: 1.11.0 
- 操作系统及其版本:windows 7
- 浏览器及其版本:chrome 54.0.2840.71 m
#### 您做了什么？

引入分页组件，选中默认页码时，有时候页码不会高亮，有时候会高亮。
#### 您期待的结果是：

像官网一样正常显示
#### 实际上的结果是：

有时候页码不会高亮，有时候会高亮,很不稳定。

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
@headforstars

**Comment by afc163** [comment]
没有重现只能关了。
