### ISSUE TITLE
Antd table even row should be blue color

### ISSUE THREAD

**Issue by Khadhiri786** [ant-design/ant-design#35898]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-m8dhcp?file=/index.js)

### Steps to reproduce

Table even row should be blue color

### What is expected?

Table even row should be blue color
![image](https://user-images.githubusercontent.com/60467237/171676134-5723bd9c-4ce7-4b6b-8cc4-5732949c6e6e.png)

### What is actually happening?

Table even row color is not displaying

| Environment | Info |
| --- | --- |
| antd | 4.18.2 |
| React | 16.8 |
| System | Windows 10 |
| Browser | Google chrome |

**Comment by 53746f696c** [comment]
This is a problem with your CSS rather than with antd. In your example, you are missing a class with that name, but if you inspect the rendered HTML you will see that the class name is added to every even row.
