### ISSUE TITLE
Dropdown does not work properly in the Shadow DOM

### ISSUE THREAD

**Issue by Jaggler3** [ant-design/ant-design#35897]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lx7d2v?file=/index.js)

### Steps to reproduce

Click each dropdown/trigger twice and observe the open/closing effect.

### What is expected?

It is expected for the dropdown in the web component to open on the first click and close on the 2nd click

### What is actually happening?

The dropdown in the web component is opening on the first click, and closing of the 2nd mouse-down, and reopening on the following mouse-up.

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | (latest) 18.1.0 |
| System | macOS 12.3.1 |
| Browser | Brave: Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64) |

---
The actual problem lies in `rc-trigger`, which is used by `rc-dropdown` which Ant Design uses for it's `Dropdown` component. It tries to reference the root of the element by using `element.ownerDocument`, which returns the `#document` almost always, when in certain cases we would want it to return a `#shadow-root`.

My current workaround:
```
const CustomDropdown = (props) =>

  const documentElement = useMemo(() => {
    if (!props.getPopupContainer) return
    const popupContainer = props.getPopupContainer()
    if (!popupContainer) return
    const newDocumentElement = popupContainer.getRootNode()
    const owner = popupContainer.ownerDocument
    if (newDocumentElement !== owner && !newDocumentElement.createElement) {
      newDocumentElement.createElement = (...args) => document.createElement(...args)
    }
    return newDocumentElement
  }, [props.getPopupContainer])

  return (
    <AntdDropdown
      // begin rc-trigger props
      getDocument={documentElement && (() => documentElement)}
      // end rc-trigger props
      {...props}
    > ...
```

I'm using a prop that is eventually passed down to `rc-trigger`, though I do not think it is specified anywhere in the documentation that this is possible.

**Comment by Jaggler3** [comment]
I've updated the CodeSandbox to include all broken components, which are:

  Dropdown,
  Menu,
  Popover,
  Tooltip,
  Popconfirm

**Comment by MadCcc** [comment]
Your workaround is reasonable, and you can config this with ConfigProvider.
`getDocument` is not stable currently and we may not specify it in docs of antd.

**Comment by errolgr** [comment]
I ran into this issue and was able to resolve this by using a ref from the parent component

```
  <Dropdown
             getPopupContainer={() => ref.current}
>...
```

**Comment by scarqin** [comment]
or
```javascript
const shadowRoot = root.attachShadow({ mode: 'open' })

...

  <ConfigProvider>
...
          getPopupContainer={(node) => {
            return shadowRoot
          }}
</ConfigProvider>
```
