### ISSUE TITLE
Documentation and README should be in English to be understandable for foreign developers

### ISSUE THREAD

**Issue by arnoldstoba** [ant-design/ant-design#359]
As a foreign developer i can say its difficult to work with the components without a proper english documentation. The demos and example code obviously help, but with an english documentation the project should surely gain popularity for western developers. This surely is a longer process but it should be thought about.

**Comment by yiminghe** [comment]
Wish we have time

**Comment by edinchez** [comment]
Please make English documentation. I absolutely love that UI, it looks insanely beautiful, but the documentation and the website are no where to be found in English. It actually makes me want to start learning React.

**Comment by arnoldstoba** [comment]
Well I wish I could assist you guys, but im not sure if the Google Translations are good and specific enough. Haha

**Comment by edinchez** [comment]
@arnoldstoba I tried. The translations are absolutely atrocious.

**Comment by arnoldstoba** [comment]
@edinchez sounds bad. Sadly.

**Comment by manV** [comment]
+1, google translate helps understanding documentation however, for hover tooltips and no-data error messages etc, there should be some way to display it in English. I would happy to help if someone can point me in right direction.

**Comment by Ehesp** [comment]
So I had a look at this, with the current setup it's pretty damn hard to integrate an English translation into the current setup, due to the way the pages are currently rendered and the docs for components are pulled in.

Without a re-write, I don't see a decent way of doing this, and the Nico docs aren't great either.

**Comment by yiminghe** [comment]
We are currently working to separate example code from doc text, stay tuned.

**Comment by Salakar** [comment]
any update on this? :question:

**Comment by TheInitializer** [comment]
Could you translate the ant.design website to english too, I can't understand anything

**Comment by waywardmonkeys** [comment]
I'm willing and able to assist with this if there is a plan that I could follow.

**Comment by Nuffx** [comment]
So am I.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1423 You guys may be interest.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1471

**Comment by benjycui** [comment]
Hey, guys. Hope that you can help us to translate `antd`'s documentation.

Trace: https://github.com/ant-design/ant-design/issues/1471

**Comment by benjycui** [comment]
Close now.
