### ISSUE TITLE
Animation problem with Upload (animation-fill-mode bug)

### ISSUE THREAD

**Issue by amirstepT** [ant-design/ant-design#35904]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-pebf3s)

### Steps to reproduce

This is an animation bug.  After uploading, the thumbnail image is displayed normally.  Once the user clicks on remove, there is a single frame of flickering of the image at the very end of the animation.  I cannot reproduce this on codesandbox or stackblitz, but it happens on multiple computers and multiple browsers that I've tried running my react app.  The code that I'm using is very simple and uploaded to the minimal reproduction on codesandbox (link above).

### What is expected?

It is expected that the animation ends without showing the old image.

### What is actually happening?

The old image is flickering for a single frame giving the appearance of flickering.

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 18.1.0 |
| System | MacOS Monterey |
| Browser | Chrome, Safari, Firefox |

---
You can see the flickering in the short video:  

https://user-images.githubusercontent.com/43920660/171906999-01fb7537-524f-4f8f-8514-f2db96ff5460.mov

I believe this is because of a bug in the antd main css file (antd/dist/antd.css).  The animation-fill-mode is set to cubic-bezier which is not a standard value based on MDN documentation (value should be none, forwards, backwards, etc).  I believe this should be set to forwards.  In addition, the duration should be just slightly shorter for inline-leave as comapred to inline-appear and inline-enter classes.  I am not sure why the bug is not easily demonstrated on codesandbox or stackblitz.  I over-wrote the css in my own css file and it works fine now.

**Comment by MadCcc** [comment]
Can setting animation-fill-mode to `forwards` solve your problem?

**Comment by amirstepT** [comment]
Yes, as I noted in my post.  It is not reproducible on codesandbox or stackblitz.  And yes, Changing the animation-fill-mode to forwards fixes the problem.  Lastly, I’ve tried in a barebones project where the only component is <Upload /> with no additional css (latest antd version, React 18.0) and it does this on two separate Mac machines (different OS) and three different browsers (Safari, Chrome, Firefox).  

As u can see, I tried to trouble shoot this bug and it was very odd that it was so specific.  Lastly, animation-fill-mode standard values as noted by MDN do not include “cubic-bezier” which is the value assigned in the ant design css file, and I wondered if this may affect others and requires a closer look.
