### ISSUE TITLE
Calendar日历 建议增加 日、周 视图

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#35908]
### What problem does this feature solve?

Calendar日历 建议增加 日、周 视图

![image](https://user-images.githubusercontent.com/3166799/172033528-40208f77-5f6a-48db-9219-621ccba89272.png)
![image](https://user-images.githubusercontent.com/3166799/172033534-b850bdb5-10ce-41b1-ad47-32198ac59a61.png)

**Comment by afc163** [comment]
Duplicate of #8024

**Comment by Blanco237** [comment]
@afc163 I've noticed you've closed almost all day and week view of the antd Calendar component issues as being a duplicate of #8024 but the main issue itself has not been solved
