### ISSUE TITLE
horizontal Menu is getting collapsed in Header

### ISSUE THREAD

**Issue by heatherKoo07** [ant-design/ant-design#35906]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-742lrw)

### Steps to reproduce

In the above CodeSandbox link, 
1. type "aaaa" in Menu.SubMenu title.  -> the menu is collapsed and ... shows up
2. type "aaaaa" in Menu.SubMenu title -> the "aaaaa" shows up
3. type "aaaaaaaaaaaaa" in Menu.SubMenu in title -> the menu is collapsed and ... shows up

### What is expected?

Regardless of the Menu.SubMenu title length, the typed string should show up on the screen.

### What is actually happening?

When the title string length is less than 5 or more than 12, the menu is collapsed in the Header layout.

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 16.14.0 |
| System | macOS 12.1 |
| Browser | Chrome |

---
Is there a way to work around?

**Comment by heatherKoo07** [comment]
I updated Reproduction link. Thanks

**Comment by MadCcc** [comment]
How about setting container `width`?

**Comment by afc163** [comment]
You need a width for fixed container: https://codesandbox.io/s/antd-reproduction-template-forked-l0e5zp
