### ISSUE TITLE
Table的footer如何和tbody对齐？

### ISSUE THREAD

**Issue by yhhwpp** [ant-design/ant-design#3591]
![image](https://cloud.githubusercontent.com/assets/7929656/19712127/ba2ce272-9b6d-11e6-814e-d8b44fe9ed96.png)

想实现如图的汇总行
而Table的footer参数是插入底部，而不是生成tfoot，如何实现跟tbody对齐？

**Comment by benjycui** [comment]
应该是对其的 https://ant.design/components/table/#components-table-demo-bordered

Table 各种组合的情况比较多，可能没有遍历到。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
不给重现只能关了。

有问题请按 issue 格式进行，否则信息损耗严重。

**Comment by yhhwpp** [comment]
我只是把想footer信息插入tfoot里。保证列跟tobody对齐，如图所示，但是footer参数这是生成一个div，而不是生成内容table 的tfoot。官网的没有对tfoot的说明。

**Comment by j306796405** [comment]
@yhhwpp 最后怎么解决的啊？

**Comment by yhhwpp** [comment]
@j306796405 ,没有解决，我就直接写在tfooter里面了...

**Comment by lucky3mvp** [comment]
悲剧，我也是遇到了这个问题。。。求 tfoot 。。。

**Comment by TangMonk** [comment]
同求

**Comment by ValeZhang** [comment]
同求，谢谢
