### ISSUE TITLE
Not allowing to setFieldsValue of Avatar inside select

### ISSUE THREAD

**Issue by Joshuajrodrigues** [ant-design/ant-design#35914]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3zwlor?file=/index.js)

### Steps to reproduce

On load I want the first item to be set from setFIeldsValue.

### What is expected?

Avatar and name should be prefilled in the select

### What is actually happening?

Shows nothing

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 16.14 |
| System | Windows 10 |
| Browser | Chrome, edge |

---
Kindly note that I am aware that this can be archived by using initial value prop. But this is just a simple reproduction, my original project does not have the value in the drop down as it will come from an api call, My actual select in project makes a api call, as I cant show 200 options in a single select, so if lets say i search for the word zebra, and select it I would then make an api call and save this in the backend. when i refresh the page, i want to show zebra as a default selected value already, to do this I make a get call which gives me the avatar url and the item name, But i can only pprefil the name and not the Avatar component

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-2egnv3?file=/index.js:411-417
You should set `value` to form data.

**Comment by Joshuajrodrigues** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-2egnv3?file=/index.js:411-417 You should set `value` to form data.

https://codesandbox.io/s/antd-reproduction-template-forked-7qfmc9
this is how it actually behaves with that method in my project

**Comment by MadCcc** [comment]
Maybe AutoComplete is more suitable in your case. Select is designed for certain options, and only get label from options list.
