### ISSUE TITLE
AutoComplete onSelect偶现不会触发，且不更改输入框的值

### ISSUE THREAD

**Issue by cheapCoder** [ant-design/ant-design#35929]
### Reproduction link

[![Edit autocomplete onselect](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autocomplete-onselect-ox3xhe?fontsize=14&hidenavigation=1&theme=dark&file=/demo.js)

### Steps to reproduce

经过form item包裹的Autocomplete组件onSelect可能不会触发。
异步生成options配置对象，选中一条option但输入框值偶现不更改且不会触发onSelect回调

### What is expected?

onSelect回调函数每次都能触发执行

### What is actually happening?

输入框值不更改且不会触发onSelect回调（暂不清楚什么时候不触发）

| Environment | Info |
| --- | --- |
| antd | 4.16.13 |
| React | 16.14.0 |
| System | macOS Monterey 12.4 |
| Browser | Chrome 102.0.5005.61（正式版本） (x86_64) |

---
这是我复现的操作

<img src="https://user-images.githubusercontent.com/60960561/172294544-82c01105-0554-4232-9acb-161437f9f617.gif" alt="图片" width="500"/>

**Comment by afc163** [comment]
先试试最新版本是否能重现。

**Comment by cheapCoder** [comment]
> 先试试最新版本是否能重现。

将复现demo的antd版本换成了最新的v4.21.0，依然会偶现

**Comment by cheapCoder** [comment]
貌似将onFocus异步执行后也不会出现问题，会不会是onSelect和onFocus执行顺序的问题
```
<AutoComplete
  open={show}
  onSelect={(val) => {
    console.log(val);
    // setShow(false);
  }}
  onFocus={() => {
    setTimeout(() => {
      setShow(false);
    }, 100);
  }}
  onBlur={handleBlur}
  options={websiteOptions}
  placeholder="website">
  <Input />
</AutoComplete>
```

**Comment by afc163** [comment]
为啥要在 onFocus 的时候 `setShow(false);`？

你可以在 onSelect 之后去 `setShow(false);`。

**Comment by cheapCoder** [comment]
> 为啥要在 onFocus 的时候 `setShow(false);`？
> 
> 你可以在 onSelect 之后去 `setShow(false);`。

我是期望聚焦输入时不显示下拉框，所以onFocus时也加了`setShow(false);`

**Comment by cheapCoder** [comment]
> focus 事件先触发了，直接关闭了下拉单，没有触发到 onSelect，看起来是合理行为。 Reproduction 的交互有些令人费解。。可以考虑换个交互方式，或者整理下你的逻辑，什么情况下 onFocus 里不需要关闭下拉单。

感谢你的解答！我期望的逻辑刚好和Autocomplete默认行为相反，失焦显示提示词，聚焦隐藏提示词，想要通过`open`来自定义实现，我个人认为这是可以出现的交互。
另外通过调试来看，貌似onSelect会先触发。

<img width="330" alt="image" src="https://user-images.githubusercontent.com/60960561/172510758-e00b259b-419e-4e94-9a1e-ded206c66a77.png">

**Comment by MadCcc** [comment]
onSelect 是基于 click 事件或者 keyDown 事件的，focus 在 mouseDown 就完成了，时间上 focus 会早一些。
可以这样阻止点击 option 时聚焦：https://codesandbox.io/s/autocomplete-onselect-forked-fw94gd?file=/demo.js
不过交互还是怪怪的...

**Comment by MadCcc** [comment]
因为属于正常现象，这个 issue 先关闭了。
