### ISSUE TITLE
您好，Form组件能否提供一个使用mapPropsToFields方法的，有校验的例子。

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#3593]
加入mapPropsToFields方法后，原来的校验都不好使了，不知道是什么原因。

**Comment by benjycui** [comment]
例子需要涉及的功能 `mapPropsToFields` `onFieldsChange` 校验。

**Comment by zhulichao** [comment]
这两个我都用到了，但是我不知道校验该怎么写，原来没用mapPropsToFields 的时候，在Form.item包裹的组件<Input style={style} disabled={disabled} ref='input' {...getFieldProps(item.ITEM_CODE, fieldPropsOptions)} /> 中，fieldPropsOptions里设置了校验信息。但是使用mapPropsToFields 之后就不好使了。我不知道现在该怎么写。有没有demo可以参考一下。

**Comment by afc163** [comment]
可以在这里面找找：http://react-component.github.io/form/

**Comment by zhulichao** [comment]
参考了http://react-component.github.io/form/examples/data-binding-form.html ，问题解决了。非常感谢。
