### ISSUE TITLE
suffixIcon={<CaretDownOutlined />}可覆盖后缀图标，但是点击图标下拉框不展开（点左边部分可展开）

### ISSUE THREAD

**Issue by tinydew** [ant-design/ant-design#35934]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-zhuang-tai-antd-4-21-0-forked-9uxbwu?file=/demo.js)

### Steps to reproduce

点击下拉框右侧图标

### What is expected?

下拉框展开

### What is actually happening?

未展开

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | ^16.14.0 |
| System | WIN10 |
| Browser | chrome102.0.5005.63 |

**Comment by MadCcc** [comment]
需要自行加上 `pointer-events: none`，自定义的 icon 不会自动加上这个，因为会支持用户自定义的点击事件。
