### ISSUE TITLE
v4.20.0版本，新增的Menu.items属性，没有渲染出来菜单

### ISSUE THREAD

**Issue by jielimi** [ant-design/ant-design#35938]
### Reproduction link

[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce

Menu设置items={items}

### What is expected?

渲染出导航菜单

### What is actually happening?

items="[object Object],[object Object]"

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17.0.0 |
| System | windows |
| Browser | chrome  102.0.5005.63 |

---
const items = [
  { label: '菜单项一', key: 'item-1' }, // 菜单项务必填写 key
  { label: '菜单项二', key: 'item-2' },
  {
    label: '子菜单',
    key: 'submenu',
    children: [{ label: '子菜单项', key: 'submenu-item-1' }],
  },
];
return <Menu items={items} />;

**Comment by netcore-jroger** [comment]
你是不是使用方式不对？看一下这个示例。https://stackblitz.com/edit/react-beptwy?file=demo.js

**Comment by saikrishnabanda5** [comment]
I am getting error as **TypeError: Cannot read property 'getPrefixCls' of undefined** when i use Progress in antd . Please help me

**Comment by netcore-jroger** [comment]
> I am getting error as **TypeError: Cannot read property 'getPrefixCls' of undefined** when i use Progress in antd . Please help me 

please provider you sample code.

**Comment by saikrishnabanda5** [comment]
import {  Progress } from 'antd';

<Progress
            percent={positionData >= 515 ? positionData / 26 : 0}
            showInfo={false}
            type="line"
            strokeColor="black"
            strokeWidth="2px"
            trailColor="#b6b6b6"
            // prefixCls="rc-tabs"
          /> 

I have used next js . During the build time i am getting this error

**Comment by netcore-jroger** [comment]
@saikrishnabanda5 
Here is an sample with `prefixCls` attribute https://codesandbox.io/s/antd-reproduction-template-forked-5d88rh?file=/index.js
But I Can't found any Error.

**Comment by saikrishnabanda5** [comment]
![Screenshot from 2022-06-08 11-25-29](https://user-images.githubusercontent.com/54619513/172542247-a94a9d7d-7c0d-48a3-8f2c-4f634449260c.png)

**Comment by saikrishnabanda5** [comment]
@netcore-jroger

**Comment by netcore-jroger** [comment]
Sorry, I haven't used next.js. Can't help you.
