### ISSUE TITLE
Table组件树形数据展示，data数据发生变化后Table未更新

### ISSUE THREAD

**Issue by qiang47199** [ant-design/ant-design#35930]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shu-xing-shu-ju-zhan-shi-antd-4-21-0-forked-ygq9zd?file=/demo.js)

### Steps to reproduce

点击按钮“更新Data数据下标0 名称“，数据更新后，表格数据未发生变化。

### What is expected?

数据更新后，表格正常显示更新后的数据。

### What is actually happening?

点击按钮后，数据发生变化，表格展示未更新。

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 16.14.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by MadCcc** [comment]
在 React 中，你需要将 data 转变为 state 才能重新渲染。
https://zh-hans.reactjs.org/docs/state-and-lifecycle.html
