### ISSUE TITLE
Latest release broke dynamic theme

### ISSUE THREAD

**Issue by hamdiwanis** [ant-design/ant-design#35940]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w2cb6u)

### Steps to reproduce

try to build and you will get an error

### What is expected?

File '~antd/lib/style/themes/variable.less' should exists

### What is actually happening?

File '~antd/lib/style/themes/variable.less' is missing

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
https://unpkg.com/browse/antd@4.21.0/lib/style/themes/variable.less

It exists in npm pacakge.
