### ISSUE TITLE
dropdown contextmenu 支持固定位置

### ISSUE THREAD

**Issue by iwege** [ant-design/ant-design#35945]
### What problem does this feature solve?

在 iframe 的场景下，如果trigger 使用 click   contextmenu ；dropdown 的 menu 可以响应iframe 的点击关闭下拉菜单。

### What does the proposed API look like?

底层rc 组件应该有一个固定位置，之前有一个 pr 实现了，但是被去掉。我理解暴露出底层的接口就行。

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by iwege** [comment]
> What does the proposed API look like?
https://github.com/ant-design/ant-design/commit/8f449861cf049d32786de1258f2a843d5512bf00#r29332154

**Comment by afc163** [comment]
没太理解 iframe（响应iframe 的点击关闭下拉菜单）的场景和固定位置有啥关系？

**Comment by iwege** [comment]
已经使用 window blur event解决。
