### ISSUE TITLE
Form 文档 & demo 整理

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#3594]
Form 文旦需要重新梳理，补充展示之前没有展示的功能，同时调整 demo 更接近常见的业务场景。
- [x] `mapPropsToFields` 使用 https://github.com/ant-design/ant-design/issues/3593 https://github.com/ant-design/ant-design/issues/3493
- [x] 自定义表单域 https://github.com/ant-design/ant-design/issues/3585
- [x] 只能使用 `ref` 实现的场景 https://github.com/ant-design/ant-design/issues/3510
- [x] 某个表单域依赖于其它表单域的值 https://github.com/ant-design/ant-design/issues/3500

**Comment by benjycui** [comment]
把几个例子调整为登陆、注册页面。

**Comment by benjycui** [comment]
与 Modal 配合的例子可以改为新建xx https://ant.design/components/form/#components-form-demo-form-in-modal

**Comment by afc163** [comment]
补充一个说明，原有组件的 defaultValue 使用 getFieldDecorator 的 InitialValue，动态修改使用 setFieldsValue 来代替。

**Comment by afc163** [comment]
原来的未使用 getFieldDecorator 纯样式表单例子也保留吧，用户还是可以选择自行管理数据的。

**Comment by afc163** [comment]
找个地方加一个这个：https://github.com/ant-design/ant-design/issues/3643

**Comment by ohmyauthentic** [comment]
@afc163 你好，今天更新了那个demo，如果我用stateless 格式申明的自定义组件在绑定onChange的时候会提醒Cannot read property 'validate' of undefined，在createBaseForm，用class XX extends React.component 方式绑定就不会出这个问题，这是为何呢

**Comment by benjycui** [comment]
@ohmyauthentic 新开个 issue，另外麻烦提供个 demo

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
这里有一篇社区文章也不错：[轻松实现ant.design中自定义组件验证](http://www.jianshu.com/p/886ba4338815)
