### ISSUE TITLE
InputNumber组件在 disabled 时无法触发 onClick

### ISSUE THREAD

**Issue by microJ** [ant-design/ant-design#35953]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-17-antd-4-21-0-inputnumber-cant-handle-click-event-ut0wu3)

### Steps to reproduce

1. 点击 `InputNumber 1`，观察 console，正常触发 onClick
2. 点击 `InputNumber 2`，观察 console，未触发 onClick

### What is expected?

InputNumber 在 disabled 时，依旧可以触发 onClick 回调

### What is actually happening?

InputNumber disabled 时，未触发 onClick 回调

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17.0.2 |
| System | MacOS 12.4 |
| Browser | Chrome 101 |

---
在 disabled 时点击，需要进行友好提示

**Comment by afc163** [comment]
原生 input 就是这样，antd 没加特殊逻辑，建议外面自行包裹一个 div 来监听 onClick。

https://codesandbox.io/s/react-17-antd-4-21-0-inputnumber-cant-handle-click-event-forked-v2cne4?file=/src/App.js
