### ISSUE TITLE
antd.css 能否适配手机

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#3595]
#### 发生问题的环境是：

- antd 版本:2.1.0
- 操作系统及其版本:安卓手机4.2
- 浏览器及其版本:chrome手机版

#### 您期待的结果是：
合适间距，漂亮界面

#### 实际上的结果是：
![image](https://cloud.githubusercontent.com/assets/19165238/19717817/fd95cf16-9b94-11e6-9906-ec7c0b959079.png)

能否在css中增加屏幕适配，以适应手机下显示。

**Comment by yhhwpp** [comment]
可以用移动端的 
[mobile-ant-design](https://mobile.ant.design/)

**Comment by whx76** [comment]
我是webapp 已经用antd开发了，在桌面，及手机浏览器都能跑，就是手机上有点丑点，如果这个可以适配，那开发一次就可以在多种设备上用，更好，否则还需要移动端开发。

**Comment by afc163** [comment]
antd 不对移动做官方支持，有问题就直接 PR 吧。
