### ISSUE TITLE
希望TreeSelect增加可以配置展开图标的功能（类似tree的icon）

### ISSUE THREAD

**Issue by lzh526457149** [ant-design/ant-design#35951]
### What problem does this feature solve?

treeIcon配置无法满足节点关闭和打开是不同图标的需求。

### What does the proposed API look like?

类似tree的icon

**Comment by afc163** [comment]
`switcherIcon`

**Comment by afc163** [comment]
`switcherIcon`https://github.com/react-component/tree-select

**Comment by lzh526457149** [comment]
>

**Comment by lzh526457149** [comment]
> 

大佬 这个是自定义最前面那个箭头图标的嘛

**Comment by lzh526457149** [comment]
> `switcherIcon`https://github.com/react-component/tree-select

大佬 这个是自定义最前面那个箭头图标的嘛

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/172749984-85459fae-3b20-4650-990d-0500788b0d9b.png)

**Comment by afc163** [comment]
@MadCcc https://ant.design/components/tree-select-cn/ 这里的类型定义文档要更新一下，和 Tree 保持一致。
