### ISSUE TITLE
Popover和Popconfirm组件里面包裹Button组件disabled问题

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design#35962]
### Reproduction link

[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce

```js
import React from 'react';
import 'antd/dist/antd.css';
import './index.css';
import { Button, Popover } from 'antd';

const content = (
  <div>
    <p>Content</p>
    <p>Content</p>
  </div>
);

const App = () => (
  <Popover content={content} title="Title" trigger="click">
    <Button type="primary" disabled>Hover me</Button>
  </Popover>
);

export default App;
```

### What is expected?

Popover和Popconfirm组件里面包裹Button组件，Popover设置trigger="click"，Button设置disabled，仍然可以点击触发气泡

### What is actually happening?

不触发气泡

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 16  |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
这里合理的，Button disabled 后可能也需要提示信息。

**Comment by DaJianWu** [comment]
> 

那只能在Popover和Popconfirm上加disabled或者通过visible来禁用了

**Comment by afc163** [comment]
对的。
