### ISSUE TITLE
I found a non-deleted console log on the Dropdown js file, it is always processed after a click

### ISSUE THREAD

**Issue by mcclaim** [ant-design/ant-design#35963]
### Reproduction link

LINK to SCRN: https://prnt.sc/TCsKxwfkY2OD

### Steps to reproduce

Add to onClick function to "Menu" component

### What is expected?

in Dropdown.js on code (65 line):

var onClick = function onClick(e) {
    var onOverlayClick = props.onOverlayClick;
    setTriggerVisible(false);
    console.log('!!!!!!!!!!!!', onOverlayClick);

    if (onOverlayClick) {
      onOverlayClick(e);
    }
  };

Delete console.log('!!!!!!!!!!!!', onOverlayClick);

### What is actually happening?

Delete console.log('!!!!!!!!!!!!', onOverlayClick);

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | ^18.1.0 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Fixed in https://github.com/react-component/dropdown/pull/220

**Comment by afc163** [comment]
@MadCcc 发个 patch

**Comment by MadCcc** [comment]
已发 v4.0.1
