### ISSUE TITLE
Dayjs@1.11.3替换Momentjs时，出现Types错误

### ISSUE THREAD

**Issue by lizhancheng** [ant-design/ant-design#35964]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bf62ng?file=/DatePicker.tsx)

### Steps to reproduce

因为不知道怎么将typescript错误显示到codesandbox，所以只有截图显示，截图的代码就是codesandbox的代码
在dayjs@1.11.3下会出现截图所示错误
<img width="954" alt="image" src="https://user-images.githubusercontent.com/8544620/172791115-b3280cc7-c4ca-4953-b331-ad07f4cdae95.png">

### What is expected?

去掉types错误

### What is actually happening?

出现weekday、localeData的types错误

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1.0 |
| System | MacOS |
| Browser | 无 |

**Comment by afc163** [comment]
You can fork https://codesandbox.io/s/wonderful-margulis-ri870n

**Comment by lizhancheng** [comment]
> You can fork https://codesandbox.io/s/wonderful-margulis-ri870n

复制过去没发现错误，然后本地删除node_modules和lock文件，重装一下就可以了
