### ISSUE TITLE
Alert banner border-radius is 0 

### ISSUE THREAD

**Issue by yuxuan** [ant-design/ant-design#35960]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/si-zhong-yang-shi-antd-4-21-0-forked-t5svm2?file=/demo.js)

### Steps to reproduce

alert banner的border-raidus始终为0

### What is expected?

请问alert banner是否应该也使用@border-radius-base，还是这个是by design的

### What is actually happening?

alert banner固定为0

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
It is by designed, banner should fit to edge of browser viewport.
