### ISSUE TITLE
建议input加入剩余字数统计的扩展

### ISSUE THREAD

**Issue by ypwlal** [ant-design/ant-design#3596]
问题
有时候会有需要统计字数的UI需求，类似微博输入 0/140这样子的UI。

尤其是与redux结合的时候，在reducer里来处理这样的逻辑觉得略不方便。

虽然可以通过getFieldValue + css定位达到类似的效果，总感觉这是个普遍需求，建议可以加上。

**Comment by benjycui** [comment]
等编辑器，然后做这个 https://ant.design/docs/pattern/form#字数校验框
