### ISSUE TITLE
Bug:Form表单的dependencies字段，首次改变被依赖Item时，validator不执行；首次改变依赖项就正常

### ISSUE THREAD

**Issue by fliyggywanglsd** [ant-design/ant-design#35976]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-form-j2bwxm)

### Steps to reproduce

1.先触发被依赖项，依赖项的validator不执行

### What is expected?

dependencies的项有改动应该立即执行validator

### What is actually happening?

不会执行

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17.x |
| System | Mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
默认字段没有更新时不会触发校验，但是可以手动触发下
https://codesandbox.io/s/antd-form-forked-mlz6b9?file=/src/App.js
