### ISSUE TITLE
Table组件，当sticky属性为true且scroll的x属性为max-content时，部分浏览器scroll属性不生效

### ISSUE THREAD

**Issue by Phil-Libra** [ant-design/ant-design#35977]
### Reproduction link

[https://phil-test-account.github.io/antd-table-bug/](https://phil-test-account.github.io/antd-table-bug/)

### Steps to reproduce

使用iOS的Safari/Edge/微信自带浏览器或者Android的微信自带浏览器打开链接页面即可重现。如取消sticky属性则bug消失。

### What is expected?

当横向宽度超过视口宽度时，不压缩每列宽度，可以用滚动条滚动。

### What is actually happening?

在部分浏览器上表格宽度被压缩，并没有滚动条出现。

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1 |
| System | Android 12.1/iOS 15.5 |
| Browser | WeChat 8.0.23(Android & iOS)/Safari(iOS) |

**Comment by afc163** [comment]
暂无计划对移动端做适配，当然如果发现问题所在欢迎给我们 PR。

https://github.com/ant-design/ant-design/issues/33728#issuecomment-1012998583

**Comment by Phil-Libra** [comment]
> 暂无计划对移动端做适配，当然如果发现问题所在欢迎给我们 PR。
> 
> [#33728 (comment)](https://github.com/ant-design/ant-design/issues/33728#issuecomment-1012998583)

经测试应该是浏览器内核问题，chrome 89.0.4350.0之前也存在同样情况。
