### ISSUE TITLE
Form表单值为对象时置空为空对象{}时不起作用，数据未改变

### ISSUE THREAD

**Issue by ONEGISER** [ant-design/ant-design#35972]
### Reproduction link

[https://stackblitz.com/edit/react-y3osgx-k5vkab?file=index.js](https://stackblitz.com/edit/react-y3osgx-k5vkab?file=index.js)

### Steps to reproduce

示例已能表达

### What is expected?

解决bug

### What is actually happening?

数据未置空

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17.0.2 |
| System | win10 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28314#issuecomment-744253708
