### ISSUE TITLE
Mix inline menu mode with vertical

### ISSUE THREAD

**Issue by Tzelon** [ant-design/ant-design#3597]
Hey, 
I want to create the following menu design I found.
https://colorlib.com/polygon/metis/dashboard.html
![image](https://cloud.githubusercontent.com/assets/4432120/19720232/f93395e4-9b75-11e6-93b4-a7194a45e342.png)

Is there anyway to mix the two modes ?

Thanks

**Comment by afc163** [comment]
Can't support now.
