### ISSUE TITLE
4.20 Menu Items Group `onClick` does not work as expected

### ISSUE THREAD

**Issue by bradgreens** [ant-design/ant-design#35985]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z4xjk5?file=/index.js)

### Steps to reproduce

Create a `<Menu>` including a group with children using the new `<Menu items={items} />` array. Assign an `onClick` handler to the group item and a child item. The `onClick` handler for the parent menu item only fires when its children are clicked.

### What is expected?

The group item `onClick` handler should fire when clicked, not when the children are clicked. I want the group item to be a router link.

### What is actually happening?

The group item `onClick` handler fires only when its children are clicked. Even if I do `event.domEvent.preventDefault()` and `event.domEvent.stopPropagation()`.

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1.0 |
| System | OSX 10.15.7 |
| Browser | Brave Version 1.38.119 / Chromium: 101.0.4951.67 |

---
This was possible and easy to implement with the legacy syntax. Example:

```
      <Menu
        mode="horizontal"
      >
        <SubMenu
          title="Group Menu Item"
          key="group-menu-item"
          onTitleClick={() => router.push("/group-target")}
        >
          <Menu.Item key="child-menu-item">
            <Link href="/group-target/child-target">Child Menu Item</Link>
          </Menu.Item>
        </SubMenu>
      </Menu>
```

**Comment by MadCcc** [comment]
Since your legacy example use `onTitleClick`, why not use it with `items`?

**Comment by bradgreens** [comment]
Thank you, that wasn't easy to determine in the documentation but I do now see that `type ItemType = MenuItemType | SubMenuType | MenuItemGroupType | MenuDividerType;` includes that property from the union.
