### ISSUE TITLE
`DropDownProps` is spelled wrong

### ISSUE THREAD

**Issue by kaiyoma** [ant-design/ant-design#35984]
### Reproduction link

[https://ant.design/components/dropdown/](https://ant.design/components/dropdown/)

### Steps to reproduce

```
import { DropDownProps } from 'antd';
```

### What is expected?

`DropDownProps` should be named `DropdownProps`, because the component name is `Dropdown`.

### What is actually happening?

The props interface is spelled wrong.

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | N/A |
| System | N/A |
| Browser | N/A |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35161

**Comment by zombieJ** [comment]
Seems already handled: https://github.com/ant-design/ant-design/blob/master/components/index.tsx#L82
