### ISSUE TITLE
2.x版本monthpicker国际化问题

### ISSUE THREAD

**Issue by cdoneshot** [ant-design/ant-design#3598]
#### 发生问题的环境是：

- antd 版本:2.x
- 操作系统及其版本:windows 10 x64
- 浏览器及其版本: chrome

#### 您做了什么？

参考https://github.com/ant-design/ant-design/issues/424 进行了国际化配置。

#### 您期待的结果是：

月份能显示为中文

#### 实际上的结果是：

月份依旧为英文

**Comment by cdoneshot** [comment]
config.js
export const locale = {
	timezoneOffset: 8 * 60,
	firstDayOfWeek: 1,
	minimalDaysInFirstWeek: 1,

	lang: {
		today: '今天',
		now: '此刻',
		ok: '确定',
		clear: '清除',
		previousMonth: '上个月 (翻页上键)',
		nextMonth: '下个月 (翻页下键)',
		placeholder: '请选择日期',
		timePlaceholder: '请选择时间',
		monthSelect: '选择月份',
		yearSelect: '选择年份',
		decadeSelect: '选择年代',
		hourInput: '上一小时(上方向键), 下一小时(下方向键)',
		minuteInput: '上一分钟(上方向键), 下一分钟(下方向键)',
		secondInput: '上一秒(上方向键), 下一小时(下方向键)',
		hourPanelTitle: '选择小时',
		minutePanelTitle: '选择分钟',
		secondPanelTitle: '选择秒',
		yearFormat: 'yyyy\'年\'',
		monthFormat: 'M\'月\'',
		dateFormat: 'yyyy\'年\'M\'月\'d\'日\'',
		previousYear: '上一年 (Control键加左方向键)',
		nextYear: '下一年 (Control键加右方向键)',
		previousDecade: '上一年代',
		nextDecade: '下一年代',
		previousCentury: '上一世纪',
		nextCentury: '下一世纪',

		format: {
			eras: ['公元前', '公元'],
			months: ['一月', '二月', '三月', '四月', '五月', '六月',
				'七月', '八月', '九月', '十月', '十一月', '十二月'
			],
			shortMonths: ['一月', '二月', '三月', '四月', '五月', '六月',
				'七月', '八月', '九月', '十月', '十一月', '十二月'
			],
			weekdays: ['星期天', '星期一', '星期二', '星期三', '星期四',
				'星期五', '星期六'
			],
			shortWeekdays: ['周日', '周一', '周二', '周三', '周四', '周五',
				'周六'
			],
			veryShortWeekdays: ['日', '一', '二', '三', '四', '五', '六'],
			ampms: ['上午', '下午'],
			datePatterns: ["yyyy'年'M'月'd'日' EEEE", "yyyy'年'M'月'd'日'", "yyyy-M-d", "yy-M-d"],
			timePatterns: ["ahh'时'mm'分'ss'秒' 'GMT'Z", "ahh'时'mm'分'ss'秒'", "H:mm:ss", "ah:mm"],
			dateTimePattern: '{date} {time}'
		}
	}
};
componen.js
import {
	locale
} from '../config/satisfaction';


<MonthPicker locale={locale} size="small" defaultValue={moment(defaultMonth,monthFormatter)} disabledDate={this.disableMonth.bind(this)}></MonthPicker>

**Comment by yesmeck** [comment]
提供下能重现的例子吧 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by cdoneshot** [comment]
sorry，已经找到原因，没有仔细看文档，2.x使用moment.js设置默认时间，需要设置moment.js的国际化和时区。
