### ISSUE TITLE
tooltip autoAdjustOverflow with incorrect placement

### ISSUE THREAD

**Issue by l619534951** [ant-design/ant-design#35986]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-21-0-forked-miu6x6?file=/demo.js)

### Steps to reproduce

1、move mouse over red backgound text, then tooltip show with bottom placement (correct placement).  
移动鼠标到红色的文字上，Tooltip朝下，正常显示。  
2、scroll div, then tooltip show with top placement (incorrect placement), the tooltip in shadow.  
滚动页面，移动鼠标到红色的文字上，Tooltip朝上，无法显示。

### What is expected?

Tooltip show with bottom placement.  
Tooltip显示在底部方向

### What is actually happening?

Tooltip show with top placement.  
Tooltip 显示在顶部方向。（在滚动区域内，看不见）

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1.0 |
| System | windows 11 21H2 |
| Browser | chrome 102.0.5005.63 |

---
发现这个问题是为了规避 [#5130](https://github.com/ant-design/ant-design/issues/5130) 产生的，但是 [#5130](https://github.com/ant-design/ant-design/issues/5130) 这个问题上，原本的逻辑本来就没有错呀，内容大小变化导致弹层大小也发生了变化，然后根据显示情况调整朝向，而且并不会影响正常使用。

而Tooltip应该很多时候用在图标按钮上面吧，因为看图标不一定能明白意思是什么，所以才需要进行解释。当用在页面顶部栏(display: fixed; top: 0)的时候，滚动页面，Tooltip就会朝上，这个时候Tooltip的自动调整方向就没有意义了，你还是要滚动到顶部才能看到Tooltip，这个时候，Tooltip又变成朝下了。

自动调整应该是：原来的展示方向看不见，自动调整展示方向让使用者看见。

### 对比了社区其他库：
material-ui : 弹层正常显示，相对浏览器窗口判断。  
Fluent UI : 弹层正常显示，相对浏览器窗口判断。  
blueprint : 弹层正常显示，相对浏览器窗口判断。  
Naive UI(vue.js) : 弹层正常显示，相对浏览器窗口判断。  

还是觉得这个调整行为不正确，应该是相对浏览器窗口判断才更符合，所以重开了这个issue。

### 相关issue:
[#30058](https://github.com/ant-design/ant-design/issues/30058)  
[#30578](https://github.com/ant-design/ant-design/issues/30578)  
[#5130](https://github.com/ant-design/ant-design/issues/5130)  
[#16046#issuecomment-482466445](https://github.com/ant-design/ant-design/issues/16046#issuecomment-482466445)

**Comment by afc163** [comment]
#5130 更好的解法可能是在 AutoComplete 和 Select 正在输入时，关掉 autoAdjustOverflow。

看上去是可以考虑把原来的行为拿回来。
