### ISSUE TITLE
DatePicker日期选择框style属性颜色无效

### ISSUE THREAD

**Issue by daifuyang** [ant-design/ant-design#35995]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ri-qi-shi-jian-xuan-ze-antd-4-21-0-forked-kmjt77?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

直接访问，颜色应该是红色的，目前未生效

### What is expected?

直接访问，颜色应该是红色的，目前未生效

### What is actually happening?

还是默认的颜色

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 16.14.0 |
| System | macOs |
| Browser | chrome 102.0.5005.61 |

**Comment by MadCcc** [comment]
style 只会给最外层的元素，想要魔改 input 的 color 建议使用自定义 css 更高优先级的选择器。
