### ISSUE TITLE
表单组件里的input输入框被tooltip包裹之后，表单验证失效的问题

### ISSUE THREAD

**Issue by CoderAWei** [ant-design/ant-design#35993]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/zhu-ce-xin-yong-hu-antd-4-21-0-forked-lezk4p?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

- 第一个输入框输入值之后清空，会弹出提示
- 第二个输入框输入值后清空，不会弹出提示
- 同时 打印的value值，在有tooltip的input那里为undefined

### What is expected?

期望能正确进行表单验证，并且``validator(_, value)``的第二个参数可以正常拿到值

### What is actually happening?

期望没有正确进行表单验证，并且``validator(_, value)``的第二个参数拿不到值

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1.0 |
| System | win 10 |
| Browser | chrome 101.0.4951.67 |

**Comment by JounQin** [comment]
得包装成标准的 `FormControl` 组件，不然 `value/onChange` 是没法透传到 `Input` 里的。

```ts
const TooltipInput = forwardRef(({ title, ...props }, ref) => (
  <Tooltip title={title}>
    <Input ref={ref} {...props} />
  </Tooltip>
))
```

See https://codesandbox.io/s/zhu-ce-xin-yong-hu-antd-4-21-0-forked-1x0ze8

**Comment by MadCcc** [comment]
如果还有问题可以 reopen

**Comment by CoderAWei** [comment]
谢谢！
