### ISSUE TITLE
RangePicker 指定 onOpenChange 属性后 clear 图标无法关闭

### ISSUE THREAD

**Issue by shaoshenchen** [ant-design/ant-design#35992]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xpz4yj?file=/index.js:0-1050)

### Steps to reproduce

codesandbox 代码

1. 选择一个时间段，然后它会自动关闭
2. 再次打开选择器，点击 clear icon，

```tsx
import React from "react";
import ReactDOM from "react-dom";
import { DatePicker } from "antd";
import "antd/dist/antd.css";
import "./index.css";

function Parent() {
  const [timeQuantum, setTimeQuantum] = React.useState([]);

  return <Child timeQuantum={timeQuantum} setTimeQuantum={setTimeQuantum} />;
}

function Child(props) {
  const { timeQuantum, setTimeQuantum } = props;

  let startTime, endTime;

  function onChange(moments) {
    if (moments) {
      startTime = moments?.[0];
      endTime = moments?.[1];
    }
  }

  function onOpenChange(open) {
    // 点击 clear icon 会被执行两次
    // 先是 open=false 然后 open=true
    console.log('open => ', open);
    
    if (open === false && startTime !== undefined && endTime !== undefined) {
      setTimeQuantum([startTime, endTime]);
    }
  }

  return (
    <div className="App">
      <DatePicker.RangePicker
        value={timeQuantum}
        onChange={onChange}
        onOpenChange={onOpenChange}
      />
    </div>
  );
}

ReactDOM.render(<Parent />, document.getElementById("root"));

```

### What is expected?

点击 clear icon 能关闭选择框

### What is actually happening?

点击 clear icon 会执行 **两次** 点击，选择框关闭后又被打开了

| Environment | Info |
| --- | --- |
| antd | 4.16.3 |
| React | 17.0.0 |
| System | Mac M1 |
| Browser | 102.0.5005.61 |

---
在 onChange 时间中如果起止日期都为空的话会在两次选完之后执行回调，但是如果选完之后重新修改起止日期，则在修改开始和结束两个日期都会触发一次 onChange 内部回调。因为回调会更改「时间」而在外部当 effect 监听到「时间」变化后就会请求接口。

简单点说，我们希望在修改起止日期后关闭选择器的同时再执行回调。

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-m2b5id?file=/index.js
因为没有在 clear 的时候清空 value，正常清空 value 后点击 clearIcon 就对了。
