### ISSUE TITLE
Menu组件中Menu.Item为null时会报错

### ISSUE THREAD

**Issue by zxyah** [ant-design/ant-design#3599]
Menu.Item为null时会报错
[demo](http://codepen.io/zxyah/pen/LRvpWZ?editors=0010)

![image](https://cloud.githubusercontent.com/assets/3394312/19720966/f0477414-9ba2-11e6-84e2-1b78d4e01869.png)

**Comment by afc163** [comment]
感觉可以兼容一下 @benjycui 这个问题很多人问。

https://github.com/ant-design/ant-design/issues/1746

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/menu/pull/57

感觉以后这种明显的 bug 可以尝试修复然后 PR..
