### ISSUE TITLE
Menu error

### ISSUE THREAD

**Issue by Sunny-L** [ant-design/ant-design#360]
react:0.13.3
node:4.1.1
Menu编译错误
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

**Comment by elrrrrrrr** [comment]
能不能提供一下使用代码？

**Comment by Sunny-L** [comment]
const React = require('react');
    const AntD = require('antd');
    const Menu = AntD.Menu;
    const SubMenu = AntD.SubMenu;
    var App = React.createClass({
      getInitialState() {
        return {
          current: 'mail'
        }
      },
      handleClick(e) {
        console.log('click ', e);
        this.setState({
          current: e.key
        });
      },
      render:function(){
        return (
          <div>
          <Menu onClick={this.handleClick} selectedKeys={[this.state.current]} mode="horizontal">
            <Menu.Item key="mail">
              <i className="anticon anticon-mail"></i>导航一
            </Menu.Item>
            <Menu.Item key="app">
              <i className="anticon anticon-appstore"></i>导航二
            </Menu.Item>
            <SubMenu title={<span><i className="anticon anticon-setting"></i>导航 - 子菜单</span>}>
              <Menu.Item key="setting:1">选项1</Menu.Item>
              <Menu.Item key="setting:2">选项2</Menu.Item>
              <Menu.Item key="setting:3">选项3</Menu.Item>
              <Menu.Item key="setting:4">选项4</Menu.Item>
            </SubMenu>
            <Menu.Item key="alipay">
              <a href="http://www.alipay.com/" target="_blank">导航四 - 链接</a>
            </Menu.Item>
          </Menu>
          </div>
        )
      }
    })

    React.render(<App />,document.getElementById('wrap'))

**Comment by yiminghe** [comment]
请注意看文档 SubMenu=Menu.SubMenu
