### ISSUE TITLE
Disable form submit on pressing "Enter"

### ISSUE THREAD

**Issue by davletovalmir** [ant-design/ant-design#36007]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ud044n?file=/index.js)

### Steps to reproduce

1. Create form
2. Add fields
3. Type in anything to the field and press enter

### What is expected?

Ability to control the submit behavior

### What is actually happening?

Form will trigger submit and when enter pressed on the input field, and there's no way to prevent this and take the control over submit

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17.0.2 |
| System | MacOS Monterey 12.04 |
| Browser | Chrome v102.0.5005.61 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10982#issuecomment-399005146
https://github.com/ant-design/ant-design/issues/16568#issuecomment-491768109

**Comment by davletovalmir** [comment]
@afc163, thanks for the links, but it's not giving any clean solution, just some workarounds, I can't add onKeyDown to every single input, my form is quite big :) I'm wondering if there is a better way to solve this issue.

**Comment by EnigamaE** [comment]
> @afc163, thanks for the links, but it's not giving any clean solution, just some workarounds, I can't add onKeyDown to every single input, my form is quite big :) I'm wondering if there is a better way to solve this issue.

you can add it to entire form
