### ISSUE TITLE
表单验证样式问题，输入正确值时，错误提示隐藏会导致FormItem下面的元素抖动

### ISSUE THREAD

**Issue by xiweixiong** [ant-design/ant-design#36020]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-bash-7kg4tw?file=/src/App.js)

### Steps to reproduce

表单验证出现不通过的错误提示时，再输入正确能够通过验证的值，FormItem的错误提示隐藏的一瞬间，会导致该FormItem下面的元素往下移动1～3个像素再复位，所呈现的视觉效果就是FormItem下面的元素抖动。

### What is expected?

FormItem隐藏错误提示样式不抖动。

### What is actually happening?

会导致该FormItem下面的元素往下移动1～3个像素再复位，所呈现的视觉效果就是FormItem下面的元素抖动

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1.0 |
| System | macOS，Win10，Win11 |
| Browser | Chrome102.0.5005.61 |

---
不知道antd官网是用的什么版本，没有出现这个问题。
但是我另外创建一个测试项目或者codesandbox，使用antd最新版本，都有这个问题。

**Comment by MadCcc** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-0-forked-dsbeoj?file=/index.js
React 18 环境下可以复现。

**Comment by xiweixiong** [comment]
> https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-0-forked-dsbeoj?file=/index.js React 18 环境下可以复现。

谢谢提醒，在react17下就没问题。

**Comment by afc163** [comment]
Duplicate of #34267

**Comment by xiweixiong** [comment]
> Duplicate of #34267

其实并不重复，我提这个问题是react18+才有的，#34267 的问题是快速删除内容输入内容才出现的问题，按道理说这种情况非特意操作是不会出现的，然后正常操作输入内容错误提示的时候是没问题的。我提的react18+是隐藏错误提示的时候必然会

**Comment by xiweixiong** [comment]
> Duplicate of #34267

其实并不重复，我提这个问题是react18+才有的，https://github.com/ant-design/ant-design/issues/34267 的问题是快速删除内容输入内容才出现的问题，按道理说这种情况非特意操作是不会出现的，然后正常操作输入内容错误提示的时候是没问题的。

我提的react18+是隐藏错误提示的时候必然会出现的问题。

**Comment by giscafer** [comment]
same issue

**Comment by afc163** [comment]
看看最新 antd 版本是否还有这个问题？

**Comment by giscafer** [comment]
> 看看最新 antd 版本是否还有这个问题？

"antd": "4.22.7" 后无此问题。

**Comment by afc163** [comment]
那我先关了，有问题再提哈。
