### ISSUE TITLE
如何测试一个用createFromIconfontCN创建出来的组件

### ISSUE THREAD

**Issue by DankeF** [ant-design/ant-design#36027]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ypwt6q)

### Steps to reproduce

点击test

### What is expected?

正常运行测试

### What is actually happening?

createFromIconfontCN创建出来的组件会报类型无效

| Environment | Info |
| --- | --- |
| antd | 4.17.2 |
| React | 16.14.0 |
| System | windows10 |
| Browser | Chrome 101.0.4951.67 |

---
实际代码与 CodeSandbox 等价，但是请忽略 CodeSandbox 测试里面的getAttribute的报错，这个已经解决。但是在运行测试文件时还是会报 createFromIconfontCN 创建出来的组件类型无效，具体报错如下：
```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by afc163** [comment]
我怎么在你的例子看到 `Warning: React.jsx: type is invalid` 这个报错呢？

**Comment by DankeF** [comment]
> 我怎么在你的例子`Warning: React.jsx: type is invalid`中看到这个报错呢？

是的，我就是想解决用 createFromIconfontCN 创建出来的组件，测试时会有 `Warning: React.jsx: type is invalid` 的报错。

**Comment by DankeF** [comment]
> 需要提供复现，现在看不到这个报错

您现在看到 CodeSandbox 里面的报错是否是
![image](https://user-images.githubusercontent.com/29647627/173763643-5f5e6d6f-3014-4771-b97b-31b245a2fcc3.png)

如果是这个得话，其实在我本地用 identity-obj-proxy 解决了。
![image](https://user-images.githubusercontent.com/29647627/173763770-91d9e3e0-eb16-4564-a55c-6a1c0bec26a6.png)

解决了这个报错后，测试时会给我报出
![image](https://user-images.githubusercontent.com/29647627/173764083-0b0740f1-083f-41ab-aaa6-6ad2b7684c92.png)
这个问题的根因是用 createFromIconfontCN 创建出来的组件，因为我在代码中把用 createFromIconfontCN 创建出来的组件注释掉后这个报错就消失了。

**Comment by DankeF** [comment]
> 目前看到的是
> 
> <img alt="图片" width="714" src="https://user-images.githubusercontent.com/507615/173766834-d1d5dff7-360b-479f-9412-a031e459e910.png">

getAttribute 这个iconfont的错误是可以用 identity-obj-proxy 解决的，就像我上面所说。主要是 jest 测试的时候报出这个错误：
![image](https://user-images.githubusercontent.com/29647627/173770878-2c92ffcd-0724-47dd-9f86-c11fbb11e3cd.png)

意思貌似是用 createFromIconfontCN 创建出来的组件不认为是组件？

**Comment by afc163** [comment]
先想办法在 codesandbox 里给我们重现吧。

**Comment by afc163** [comment]
如果 codesandbox 重现不出来，给一个 repo 也可以。
