### ISSUE TITLE
rc-tree 1.3.6 重现BUG

### ISSUE THREAD

**Issue by tangtaoit** [ant-design/ant-design#3602]
rc-tree 1.3.6重现了原来的BUG  此BUG原来有人提过issues(https://github.com/ant-design/ant-design/issues/1730 )后来在1.3.1被修复  现在1.3.6被重现.

Tree文件 622行 将if (props.checkable && (this.checkedKeysChange || props.loadData)) { 改为 if ((props.checkable && this.checkedKeysChange) || props.children) {

希望修复此问题。

**Comment by warmhug** [comment]
看不出是重现的问题，麻烦给个可重现的示例： http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
@tangtaoit

**Comment by afc163** [comment]
不给重现只能关了呢。。
