### ISSUE TITLE
请官方注意popover组件的样式bugs

### ISSUE THREAD

**Issue by lincolon** [ant-design/ant-design#36023]
### Reproduction link

[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce

点击或者移动到popover组件上弹出层箭头样式bug

### What is expected?

点击或者移动到popover组件上弹出层箭头样式bug

### What is actually happening?

点击或者移动到popover组件上弹出层箭头样式bug

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17 |
| System | macos |
| Browser | chrome |
![image](https://user-images.githubusercontent.com/4044707/173299163-5060d6c1-a5e5-4cde-929a-91a6756bc0fc.png)

**Comment by wangxigua1998** [comment]
360浏览器，我也遇到了，toolTip组件箭头只要向下的有bug，卡片确认框的箭头全是bug

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35735#issuecomment-1137095702

**Comment by devchen13** [comment]
> [#35735 (comment)](https://github.com/ant-design/ant-design/issues/35735#issuecomment-1137095702)

![image](https://user-images.githubusercontent.com/30109901/184274075-e4411675-0686-41c3-84fe-5bebb785383d.png)
还是360浏览器最新版本，Right和Bottom还有问题
