### ISSUE TITLE
Upload组件文档内手动上传案例有误。

### ISSUE THREAD

**Issue by fhydralisk** [ant-design/ant-design#36036]
### Reproduction link

[https://ant.design/components/upload-cn/#components-upload-demo-upload-manually](https://ant.design/components/upload-cn/#components-upload-demo-upload-manually)

### Steps to reproduce

依据官方文档内的手动上传代码片段创建一个简单的React App

### What is expected?

能够实现文件上传。

### What is actually happening?

通过Chrome开发工具，可以看到POST请求体并无文件内容，而是上传`files[]: undefined`至服务器。

| Environment | Info |
| --- | --- |
| antd | 4.21.1 |
| React | React 17.0.32 |
| System | macOS 12.3 |
| Browser | Chrome 102.0.5005.61 |

---
经过分析，`beforeUpload`回调参数file的类型为`RcFile`，而非`UploadFile`。因此在执行上传的代码片段
```javascript
    fileList.forEach(file => {
      formData.append('files[]', file.originFileObj as RcFile);
    });
```
中，append的参数2将永远为undefined。

**Comment by afc163** [comment]
@zombieJ 看看，是不是之前改挂了，这个 demo 一直没变过的。

**Comment by MadCcc** [comment]
> @zombieJ 看看，是不是之前改挂了，这个 demo 一直没变过的。

demo 改过，看起来改错了
https://github.com/ant-design/ant-design/pull/34742/files#diff-88c284046594b897978c328b29b1d6660f293cb9528176d0cb8b64ab2a3e2709

**Comment by afc163** [comment]
看上去是我的锅。
