### ISSUE TITLE
Select在mode="multiple"下，搜索结果如果高度有变化，dropdownRender下的事件无法点击问题

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design#36039]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-21-0-forked-lpmp03?file=/demo.js:677-692)

### Steps to reproduce

打开重现链接后，选择输入jack，然后点击下方的addItem无法完成添加选项

### What is expected?

搜索结果高度产生变化后，下方的dropdownRender渲染的区域事件可以正常运行点击

### What is actually happening?

搜索结果高度产生变化后，下方的dropdownRender渲染的区域事件无法正常运行点击

| Environment | Info |
| --- | --- |
| antd | 4.21.1 |
| React | react |
| System | mac os |
| Browser | chrome最新版本 |

**Comment by MadCcc** [comment]
先触发了 blur 事件，导致 click 事件没有正确触发。
可以通过给 ‘add item’ 添加 mousedown 事件的 `preventDefault` 避免。类似的点击下面的 input 之后搜索词消失也可以通过这种方法解决。
https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-21-0-forked-2muspe?file=/demo.js:1266-1305

如果没有解决你的问题可以随时 reopen。
