### ISSUE TITLE
cannot use imported antd components to be inside Form.Item

### ISSUE THREAD

**Issue by fandok** [ant-design/ant-design#36049]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jbiix9?file=/index.js)

### Steps to reproduce

- check radio button
- check second radio button
- click submit

### What is expected?

radio-group-2 has values

### What is actually happening?

radio-group-2 has no values

| Environment | Info |
| --- | --- |
| antd | 4.21.1 |
| React | 18 |
| System | macos monterey 12.4 |
| Browser | chrome 102.0.5005.115 |

---
-

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

https://codesandbox.io/s/antd-reproduction-template-forked-6kukbv
