### ISSUE TITLE
Antd-Select (multi-select) Search functionality to allow continuous searching instead of resetting the search text once item selected.

### ISSUE THREAD

**Issue by iamthomasvj** [ant-design/ant-design#36045]
### Reproduction link

[https://ant.design/components/select/](https://ant.design/components/select/)

### Steps to reproduce

User can be able to select item without entering the search text again. Scenario  can be suppose if the list has countries items and user searching for country "US" so list would contain all US related country codes. so if user wants to select all of the related search, user should enter US search text everytime. instead keep the search text and show the search result without resetting the search field.  component: https://ant.design/components/select/ 

### What is expected?

Once user select the item in multi select functionality, Instead of resetting the search text and showing the selected item, keep the search text until unless the user come out of multi select. once user comes out show selected items. This will improve the user experience.

### What is actually happening?

once user select the item in multi select it reset the search text so that user force to enter the search text again to see the same result

| Environment | Info |
| --- | --- |
| antd | 4.21.1 |
| React | 17 |
| System | Mac os |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Do you mean `autoClearSearchValue `?

**Comment by mzulfanw** [comment]
> Do you mean `autoClearSearchValue `? Feel free to reopen if it can not help.

thanks
