### ISSUE TITLE
在Select自定义下拉菜单中的Transfer的全选、反选，全部删除功能会使Select的下拉菜单自动关闭

### ISSUE THREAD

**Issue by YingJian-hu** [ant-design/ant-design#36059]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-d7q6tr?file=/index.js)

### Steps to reproduce

1.选中选择框弹出自定义下拉菜单穿梭框

2.点击穿梭框左边title上的按钮，点击全选、反选

3.点击穿梭框右边title上的按钮，点击全选，反选

### What is expected?

自定义下拉菜单不收回，可以继续操作穿梭框

### What is actually happening?

自定义下拉菜单收回，无法继续操作穿梭框

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | mac12.2.1  |
| Browser | chrome102.0.5005.61 |

**Comment by afc163** [comment]
这是拿 Select 当做 rc-trigger 用了，不建议这样使用。

**Comment by YingJian-hu** [comment]
@afc163 希望帮忙解答下 谢谢

**Comment by afc163** [comment]
避免在 Select 下拉菜单中加入过多和本身选择行为无关的交互，这个已经是自定义浮层的交互了，建议用 rc-trigger 自行封装组件。

**Comment by YingJian-hu** [comment]
@afc163 已用 rc-trigger重新封装，问题解决，感谢回复
