### ISSUE TITLE
InputNumber被div包裹后，errorValid 失效，onChange拿到的value值是旧值

### ISSUE THREAD

**Issue by tangwei01** [ant-design/ant-design#36050]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-0-forked-4j6nin?file=/demo.js)

### Steps to reproduce

1. input  120
2. input 12

### What is expected?

正确效验，拿到的值是正常的

### What is actually happening?

效验失效，值是上一步的值

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.14 |
| System | mac |
| Browser | chrome100 |

**Comment by afc163** [comment]
Form.Item 应该直接包裹对应的表单控件。https://ant.design/components/form-cn/#components-form-demo-complex-form-control
