### ISSUE TITLE
Upload组件新上传的图片没法预览

### ISSUE THREAD

**Issue by denzw** [ant-design/ant-design#3605]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: win10
- 浏览器及其版本: chrome 53
#### 您做了什么？

为上传组件配置onPreview事件，处理预览
#### 您期待的结果是：

新增加的上传的图片能正常预览
#### 实际上的结果是：

新增加上传成功的图片不能预览（没有触发onPreview事件），上传组件初始化时的则可以成功调用
#### 可重现的在线演示

无

**Comment by infeng** [comment]
麻烦提供一个可重现的demo http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by denzw** [comment]
demo  http://codepen.io/denzw/pen/QKPJqL?editors=0011
初始化的可以，新增加的不可以预览

**Comment by benjycui** [comment]
@afc163 这个是故意设计的么？

感觉缩略图 `thumbUrl` 预览意义不大啊。。

**Comment by infeng** [comment]
自己不写onChange事件的话，新增的file对象只有thumbUrl而没有url

**Comment by afc163** [comment]
来个 PR ~ @denzw

**Comment by afc163** [comment]
@denzw
