### ISSUE TITLE
Allow widening of ItemType

### ISSUE THREAD

**Issue by DavidSichau** [ant-design/ant-design#36065]
### What problem does this feature solve?

I want to provide additional properties to a menu for example to make it better testable. This works but TS is reporting an error as the attribute 'data-test' does not exit in type ItemType.

```
const items: Array<ItemType> = [
    {
      key: 'exercises',
      // @ts-ignore
      'data-test': 'exercises',
      icon: <Fa icon={faTasks} fixedWidth />,
      label: <Link to={`${url}/exercises`}>Exercises</Link>,
    },
]
```

ItemType can not be widened as the MenuItemType type is not exported and is private.

### What does the proposed API look like?

Maybe allow ItemType to be generic type, which can be extended with additional properties.

**Comment by guymoon** [comment]
Can I work on this?

**Comment by afc163** [comment]
sure

**Comment by Medmly20208** [comment]
is this issue still open?

**Comment by ashutosh887** [comment]
Can I work on this now?

**Comment by yoyo837** [comment]
> Can I work on this now?

PR welcome!
