### ISSUE TITLE
Allow to load more data when filter is active in TreeSelect

### ISSUE THREAD

**Issue by andreas-soroko** [ant-design/ant-design#36063]
### What problem does this feature solve?

I am using the `TreeSelect` and want to filter (search) on my data, after the result is displayed and when the item isn't a leaf item, I want to load more items.

Currently, I can see the switch icon and can press it, but the `loadData` method will not be triggered. (https://github.com/react-component/tree-select/blob/master/src/OptionList.tsx#L231)

Example: https://codesandbox.io/s/asynchronous-loading-antd-4-21-2-forked-n50npv?file=/demo.js
search for `B3` and click expand icon

real use case:
listening on the `onSearch` and using this value to load the filtered `treeData` from the service with the information if the item is a leaf or not,

so based on the example above, the user searches directly for `B` and would see `B1`, `B2`, `B3` and sees also, `B3` has more items and tries to expand (or switches between collapse/expand) but nothing happens

I'm not sure if that was deactivated because all nodes are expanded during a search?
Is there a different approach to solve the problem?

### What does the proposed API look like?

No preferences here

`<TreeSelect  loadDataOnSearch={true/false} />`

**Comment by afc163** [comment]
It is strange to trigger `loadData` when blur search.

**Comment by zombieJ** [comment]
In 4.0-alpha, TreeSelect will trigger `loadData` even in search. But it find out that when a TreeSelect need `loadData`, it will be large data in most case. So when user typing for example `test`, it will trigger multiple `loadData` for `t`, `te`, `tes`, `test` in one time which will block network directly. So we remove this behavior and I still do think provide `loadDataOnSearch` get any help.

But you can handle this with `filterTreeNode`:
```tsx
<TreeSelect filterTreeNode={(input, treeNode) => {
  const match = ...

  if (match && !treeNode.isLeaf && !treeNode.children) {
    // Do some loading logic
  }

  return match;
}} />
```

Since we may not recommend auto `loadData` in search which will trigger too many treeNode will be expanded at once, we may not handle this request. Thanks for understanding.

**Comment by HeyShinner** [comment]
> In 4.0-alpha, TreeSelect will trigger `loadData` even in search. But it find out that when a TreeSelect need `loadData`, it will be large data in most case. So when user typing for example `test`, it will trigger multiple `loadData` for all the TreeNode matching `t`, `te`, `tes`, `test` in one time which will block network directly. So we remove this behavior and I still don't think provide `loadDataOnSearch` get any help.
> 
> But you can handle this with `filterTreeNode`:
> 
> <TreeSelect filterTreeNode={(input, treeNode) => {
>   const match = ...
> 
>   if (match && !treeNode.isLeaf && !treeNode.children) {
>     // Do some loading logic
>   }
> 
>   return match;
> }} />
> Since we may not recommend auto `loadData` in search which will trigger too many treeNode will be expanded at once, we may not handle this request. Thanks for understanding.

arrow icon lost after search when we set filterTreeNode=true, so we can't click arrow icon to load data
