### ISSUE TITLE
Menu within a modal displays outside viewport

### ISSUE THREAD

**Issue by GoopyLotus5844** [ant-design/ant-design#36067]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/menu-bug-41mjuw?file=/src/App.js)

### Steps to reproduce

1. Resize the browser window to be around 400 pixels in height
2. Scroll to the bottom of the page
3. Use the button to open the modal. Then navigate to the last submenu.
![Menu bug](https://i.imgur.com/JC3czO7.png)

### What is expected?

The last submenu should display completely on the screen, or show a scroll bar if it cannot fit on the screen.

### What is actually happening?

The submenu is cut off at the top of the viewport.

| Environment | Info |
| --- | --- |
| antd | 4.21.2 |
| React | React 17.0.2 |
| System | Windows |
| Browser | Chrome 102 |

---
This is related to the scroll position of the page. If you repeat this process without scrolling down before opening the modal, the menu displays correctly. This is odd because the positioning of the menu should not be related to the scroll position of the page.

**Comment by afc163** [comment]
same problem as https://github.com/ant-design/ant-design/issues/35986
