### ISSUE TITLE
table 添加components属性后，column的shouldCellUpdate函数无法进入

### ISSUE THREAD

**Issue by HengLiYang** [ant-design/ant-design#36061]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-z9l1nl?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

当我上传文件改变list的时候，因为目前例子上不会写hook，所以写的假的，上传文件有进度，我点击选择日历会因为list改变而重新渲染，导致选择日历时候，日历面板关闭，我用shouldCellUpdate想阻拦刷新，结果一直进不来此函数

### What is expected?

进入shouldCellUpdate函数，可以控制cell是否重新渲染

### What is actually happening?

无法进入shouldCellUpdate

| Environment | Info |
| --- | --- |
| antd | 4.13.1 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome |

---
无

**Comment by HengLiYang** [comment]
发现问题出现在table的components属性上，给components加上useMemo就不会出现因为重新更新列表导致日历选择有问题

**Comment by houjin0803** [comment]
请问一下为什么加了useMemo，shouldCellUpdate j就会生效，我也遇到了这个问题。但是我始终不明白如果components不加useMemo, shouldCellUpdate就会失效？能够解答一下，非常感谢~
