### ISSUE TITLE
Tree DirectoryTree 类型错误，没有把Tree的泛型暴露出来

### ISSUE THREAD

**Issue by JaylanChen** [ant-design/ant-design#36068]
### What problem does this feature solve?

在TS环境中使用 DirectoryTree 时，自定义类型报错，因为 DirectoryTree 使用了Tree的默认类型，未暴露泛型；
[代码位置](https://github.com/ant-design/ant-design/blob/0e6e1c047d16f1e29f8807eeb84615e7dec36645/components/tree/DirectoryTree.tsx#L18)

### What does the proposed API look like?

 DirectoryTree 也支持泛型；

```
export interface DirectoryTreeProps<T extends BasicDataNode = DataNode> extends TreeProps<T> {
  expandAction?: ExpandAction;
}
```

**Comment by JaylanChen** [comment]
[Reproduce url](https://codesandbox.io/s/antd-reproduction-template-forked-wnkvzg?file=/index.js)

你看下这个我描述的是否清楚，如果不够清晰，我再新建个GitHub仓库来演示 DirectoryTree 不支持泛型的例子；

**Comment by afc163** [comment]
建个仓库吧，或者直接来 PR。

**Comment by JaylanChen** [comment]
#36092
