### ISSUE TITLE
Menu组件onSelect事件失效

### ISSUE THREAD

**Issue by dashaowang** [ant-design/ant-design#36064]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cai-dan-yin-cang-fang-shi-antd-4-21-2-forked-lef4ig?file=/demo.js)

### Steps to reproduce

点击下拉菜单，onSelect事件没触发，控制台无打印

### What is expected?

点击能够触发onSelect事件

### What is actually happening?

无法触发onSelect事件

| Environment | Info |
| --- | --- |
| antd | 4.21.2 |
| React | 17.0.2 |
| System | win10 |
| Browser | Microsoft Edge 99.0.1150.46 (正式版本) (64 位) |

**Comment by afc163** [comment]
https://ant.design/components/dropdown-cn/

<img width="659" alt="图片" src="https://user-images.githubusercontent.com/507615/173975315-ae8d66ee-885e-4b5e-acd8-55527ddc549c.png">
