### ISSUE TITLE
Input Group 样式问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3606]
<img width="377" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19724048/c6d82ff2-9bb0-11e6-8eef-0dbc48128908.png">

https://ant.design/components/form/#components-form-demo-validate-basic

**Comment by benjycui** [comment]
已经修复 https://github.com/ant-design/ant-design/commit/f599a24228cbbe684039ed1c5b0fb5d88de7a39f

不过这个 demo 我后来删除了，和注册的那个 demo 有重复。
