### ISSUE TITLE
日期选择框 DatePicker disabledDate 选择问题

### ISSUE THREAD

**Issue by KiligFei** [ant-design/ant-design#36088]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bu-ke-xuan-ze-ri-qi-he-shi-jian-antd-4-21-2-forked-w2914d?file=/index.js)

### Steps to reproduce

点击上面的切换月份按钮和刷新后在6月份面板点击虚的7月日期，7月显示的lastDate 不一样

### What is expected?

2次lastDate一样

### What is actually happening?

2次lastDate不一样

| Environment | Info |
| --- | --- |
| antd | 4.21.2 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | Google Chrome 版本 102.0.5005.61 |

**Comment by afc163** [comment]
不太理解『点击上面的切换月份按钮和刷新后在6月份面板点击虚的7月日期』这两个行为具体的路径是啥，能截图和提供详细重现步骤么？

**Comment by KiligFei** [comment]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/69230517/174108880-3ca69761-272b-48a9-8619-e34c40fd45f1.png">
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/69230517/174108924-ba2e9094-427a-4cea-a7c0-8682d00f4d8a.png">

**Comment by KiligFei** [comment]
https://www.bilibili.com/video/BV1yr4y137ko?share_source=copy_web 视频操作

**Comment by afc163** [comment]
https://codesandbox.io/s/bu-ke-xuan-ze-ri-qi-he-shi-jian-antd-4-21-2-forked-2rjfez

```diff
- const onDateChange = (date, dateString) => {
-   setDate(date, dateString);
- };
+ const onDateChange = (date) => {
+   setDate(date);
+ };
```
