### ISSUE TITLE
如何在Select组件中的onSearch事件中，获取Select中的所有值，不是当前选中值

### ISSUE THREAD

**Issue by BBliu** [ant-design/ant-design#3608]
## 发生问题的环境是：

antd 版本: 2.1.0
操作系统及其版本:OSX 10.11.5
浏览器及其版本:Firefox
## 您做了什么？
<Select tags searchPlaceholder="标签模式"
 style={{ width: 320 }} 
 onChange={this.handAutoCompleterChange} 
 onSelect={this.handAutoCompleterSelect} 
 onSearch={self.handAutoCompleterSearch}>
 {dataSource}
 </Select>
## 您期待的结果是：

能获取到己经选中的所有值

**Comment by yeliex** [comment]
```
handleAutoCompleteSearch=(originalData)=(value)=>{
  ... do sth.
}
onSearch={handleAutoCompleteSearch(dataSource)}
```

**Comment by afc163** [comment]
select 组件上层自行保留状态。

**Comment by afc163** [comment]
组件用法尽量到 https://segmentfault.com/t/antd 上去提问。issue 用于报告问题。
