### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by wulibaibao** [ant-design/ant-design#36096]
### Reproduction link

[https://ant-design.com/](https://ant-design.com/)

### Steps to reproduce

1. chrome高级设置
2. 语言设置成英语(美国)置顶语言
如上设置完成，页面会自动转成英文
此时控制台输出`navigator.language   'en-US'`
设置<ConfigProvider locale={{ locale: "zh-CN" }}>{dom}</ConfigProvider>，固定语言也没有用，分页和时间组件会固定位en-US

### What is expected?

如何在语言设置后仍然能保持内部config定义的语言状态，不去自主识别设备语言

### What is actually happening?

如何在语言设置后仍然保持内部config定义的语言状态，不去自主识别设备语言

| Environment | Info |
| --- | --- |
| antd | 4.21.1 |
| React | 17.0.0 |
| System | Macos |
| Browser | chrome |

**Comment by MadCcc** [comment]
把 chrome 的翻译关掉试试

**Comment by afc163** [comment]
试试：

```jsx
import zhCN from 'antd/lib/locale/zh_CN';

<ConfigProvider locale={zhCN}>
```

**Comment by wulibaibao** [comment]
> ```js
> locale={zhCN}
> ```

这个是可以的，目前使用页码、时间可行，ant UI这块相关的好了，但还是建议不要随设备语言，提bug的人不按常规操作
