### ISSUE TITLE
antd字体图标文件外链

### ISSUE THREAD

**Issue by cdoneshot** [ant-design/ant-design#3609]
antd css中antdicon字体文件默认从cdn加载，网站拦截外链导致字体加载不成功，每次都需要修改antd css不方便。
建议字体文件默认从当前网站下载。

**Comment by afc163** [comment]
静态资源走 cdn 有明显速度优势的。需要另行部署的可以参考：https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont
