### ISSUE TITLE
RangePicker的行为不是很理解。现在是设置不进去，读出来的未按预期格式。。。。

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#3610]
- antd 版本:2.1
- 操作系统及其版本:win10
- 浏览器及其版本:chrome 54

引入 antd 了 RangePicker

这个不可重现， 就是为了说明下 基本用法还是会的。
http://codepen.io/xjdata/pen/ozOamB?editors=001

但是当 RangePicker 在from中时， 不论是设置 defaultValue 或者 value 都无法显示。
```
//dateRange 确定 肯定有值的，直接打印 dateRange.map((date)=>moment(new Date(date)))，没问题。
  <FormItem>
            {getFieldDecorator('dateRange', {
              value: dateRange? dateRange.map((date)=>moment(new Date(date))) : null,
            })(
              <RangePicker style={{width: 300}} format="YYYY-MM-DD HH:mm:ss" showTime/>
            )}
</FormItem>
```

PS： 另外，当我提交这个表单时， dateRange的值自动变化为
```
dateRange[0]:Thu Oct 20 2016 11:13:20 GMT+0800
dateRange[1]:Tue Nov 22 2016 11:13:20 GMT+0800
```

不知道我哪里错了。 谢谢。

**Comment by yesmeck** [comment]
> 另外，当我提交这个表单时， dateRange的值自动变化

没明白你的意思，这个不能重现吗？

**Comment by afc163** [comment]
getFieldDecorator 的配置里没有 value 和 defaultValue 这两个东西。

**Comment by xjdata** [comment]
@afc163  第一个问题解决了。 确实没有那个属性，光顾着看 RangePicker 的属性 想当然了。。。。

@yesmeck  
![image](https://cloud.githubusercontent.com/assets/4524983/19758302/0d75da78-9c5a-11e6-9692-3924589c75ca.png)

![image](https://cloud.githubusercontent.com/assets/4524983/19758319/1e327880-9c5a-11e6-9350-e0c8fd441d57.png)

```
<RangePicker style={{width: 300}} format="YYYY-MM-DD HH:mm:ss" showTime/>
```
组件的属性里有格式化。 提交的时候转换成另外的格式化了。 当然后端可以处理。就是显示和提交没一致。  应该是我水平不行，所以才跑来请教了。

**Comment by yesmeck** [comment]
@xjdata 来个 demo 吧

**Comment by benjycui** [comment]
@xjdata https://ant.design/changelog?locale=zh-CN#2.x-不兼容改动

所有时间组件的 value 都是 moment 类型，提交前应该自己 format 一下。

**Comment by benjycui** [comment]
我加个 demo。
