### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by wang-binbin** [ant-design/ant-design#36107]
### Reproduction link

[https://stackblitz.com/edit/react-dyxhrw?file=index.js](https://stackblitz.com/edit/react-dyxhrw?file=index.js)

### Steps to reproduce

加入了 // 默认语言为 en-US，所以如果需要使用其他语言，推荐在入口文件全局设置 locale
// import moment from 'moment';
// import 'moment/locale/zh-cn';
// moment.locale('zh-cn');
  依然是英文

### What is expected?

期望 变成中文

### What is actually happening?

英文

| Environment | Info |
| --- | --- |
| antd | 4.21.2 |
| React | react |
| System | windwos |
| Browser | chrome |

**Comment by afc163** [comment]
你需要 https://ant.design/components/config-provider-cn/

Calendar 这块文档遗漏了，我来补上。

**Comment by wang-binbin** [comment]
> 

靠谱
