### ISSUE TITLE
Button组件能否在onClick返回一个promise时内部控制loading状态

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design#36103]
### What problem does this feature solve?

通常在点击按钮需要和后端交互时都会通过一个额外的state来控制loading，如果一个页面按钮比较多的情况下就显得非常冗余。是否可以在onClick返回一个promise时自动开启loading，resolve或者reject后自动关闭loading

### What does the proposed API look like?

onClick={(event) => void | Promise}

**Comment by afc163** [comment]
不会搞这么复杂，onClick 还是保持简单比较好，如果有封装诉求可以上层自行封装一个 `<ButtonWithLoading />`。

**Comment by faner11** [comment]
这个功能还是非常实用的，自己封装虽然也简单，但是还是希望官方的Button可以支持
