### ISSUE TITLE
column.render just call once, then don't change anymore

### ISSUE THREAD

**Issue by hisland** [ant-design/ant-design#36100]
### Reproduction link
👇👇👇click to show
[issue reproduction antd@4.21.2](https://codesandbox.io/s/antd-reproduction-template-forked-ry0yeh)
[ok reproduction antd@4.18.7 ](https://codesandbox.io/s/antd-reproduction-template-forked-s8ps7o)

### Steps to reproduce

click Select to choose one Option

### What is expected?

Select shows what choosed

### What is actually happening?

still blank

| Environment | Info |
| --- | --- |
| antd | 4.21.2 |
| React | 17.0.2 |
| System | macos |
| Browser | chrome |

---
maybe caused by the rc-table's pr: https://github.com/react-component/table/pull/752

**Comment by afc163** [comment]
原来的写法也是有问题的，只是 antd 没处理好而已。简单的说就是不要修改之前对象的属性引用，另外 columns 需要根据依赖变量做更新，不然永远是闭包渲染时的那个 dataSource。具体可以参考 https://overreacted.io/a-complete-guide-to-useeffect/

https://codesandbox.io/s/antd-reproduction-template-forked-clx6mz?file=/index.js:552-606

**Comment by hisland** [comment]
好的, 谢谢 🙏
