### ISSUE TITLE
`<Skeleton active />` is not dark-mode-styled correctly

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ant-design/ant-design#36114]
### Reproduction link

[https://stackblitz.com/edit/react-ts-2nwidc?file=App.tsx](https://stackblitz.com/edit/react-ts-2nwidc?file=App.tsx)

### Steps to reproduce

```js
import * as React from 'react';
import { Skeleton } from 'antd';
import 'antd/dist/antd.dark.css';

export default function App() {
  return <Skeleton active />;
}
```

### What is expected?

This was working before `v4.21`. In `v4.20`, it works. [Demo](https://stackblitz.com/edit/react-ts-wrhkry).

### What is actually happening?

The skeleton is white, and you can't see the animation. It looks very bad when rest of page is dark.

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.2.0 |
| System | StackBlitz |
| Browser | Microsoft Edge: 102.0.1245.41 (Official build) (64-bit)  |

---
This bug did not exist in `v4.20` - https://stackblitz.com/edit/react-ts-wrhkry

**Comment by afc163** [comment]
Broken in https://github.com/ant-design/ant-design/pull/35836
