### ISSUE TITLE
Add ref prop to all components

### ISSUE THREAD

**Issue by izhouteng** [ant-design/ant-design#36117]
### What problem does this feature solve?

大部分组件并没有转发 ref 属性，这使得 framer-motion 很难在 antd 当中使用。

虽然可以在组件外面包一层来实现动画，但这样既增加了多余的 DOM，也不利于维护。

对于某些组件，则根本行不通，像 Breadcrumb 只接受 Breadcrumb.Item 作为子组件，此时则无法使用 framer-motion 为 Breadcrumb.Item 加上动画效果。

许多其他流行的UI库（MUI、Chakra UI...），所有组件都是转发 ref 属性的，实现动画就很轻松。

希望 antd 团队能考虑加上，或是在V5版本中。

-----------------------------------------------------------------------
Most components do not forward ref prop, which makes framer-motion difficult to use in antd.

Although it is possible to wrap the component to achieve animation, but this increases the redundant DOM and is not conducive to maintenance.

For some components, it doesn't work at all. For example, Breadcrumb only accepts Breadcrumb.Item as a subcomponent. In this case, framer-motion cannot be used to animate Breadcrumb.Item.

With many other popular UI libraries (MUI, Chakra UI...), all components forward ref prop, making animations easy.

Hope the antd team can consider adding it, or add it in the V5 version.

### What does the proposed API look like?

<Component ref={ref} />

**Comment by afc163** [comment]
- https://github.com/ant-design/ant-design/issues/31442
- https://github.com/ant-design/ant-design/issues/31227

**Comment by MadCcc** [comment]
按照 menu 的改造看 breadcrumb 似乎也可以舍弃这种语法糖了？

**Comment by afc163** [comment]
可以按需来给 antd PR。

**Comment by standbyoneself** [comment]
I want that too. Currently I'm not able to add a tooltip for Breadcrumb.Item. Instead I have to use wrappers and overriding styles

**Comment by trionfordring** [comment]
希望所有组件都能实现`HTMLAttributes`。
我正在开发antd的低代码组件库，但是低代码的拖拽功能需要获取到dom对象才能进行。
如果没有ref，我就得使用一些html元素包裹antd组件，这么做会导致一些副作用。
