### ISSUE TITLE
TreeSelect delete node doesn't work when use tagRender

### ISSUE THREAD

**Issue by gmoniava** [ant-design/ant-design#36112]
### Reproduction link

[https://stackblitz.com/edit/react-bvy8ra?file=demo.js](https://stackblitz.com/edit/react-bvy8ra?file=demo.js)

### Steps to reproduce

In TreeSelect select two leaf nodes:
- **first** select "my leaf" and **then** "your leaf". 
- delete "my leaf" by clicking corresponding tags 'x' button 

### What is expected?

Deleted leaf should disappear

### What is actually happening?

Both nodes disappear

| Environment | Info |
| --- | --- |
| antd | 4.19.0 |
| React | 16 |
| System | Ubuntu |
| Browser | Chrome 101 |

---
Happens when I use tagRender

PS. This bug wasn't present in earlier versions. Such bugs make upgrading antd version risky, because it can break existing apps.

**Comment by gmoniava** [comment]
Suggested issues aren't related

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35657#issuecomment-1133123112

**Comment by gmoniava** [comment]
@afc163 i would like to ask you one question. Such bugs are problematic because they broke existing app which was working well with older antd version (4.17).

Is it _common_ in antd to introduce such new bugs which break _working_ code in older versions of antd? 

I am asking this because it is risky for me now to upgrade antd version, because it may break my existing app.

**Comment by afc163** [comment]
Could you provide codesandbox or stackblitz which works in old version?

**Comment by gmoniava** [comment]
Just use antd 4.17

**Comment by gmoniava** [comment]
Here is [demo](https://stackblitz.com/edit/react-bvy8ra-jse4jy?file=index.js), just use antd 4.17.0
