### ISSUE TITLE
Form Item focus style bug

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3613]
demo: https://ant.design/components/form/#components-form-demo-horizontal-form

<img width="597" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19757923/42656138-9c58-11e6-8b2d-646759352d6c.png">

There is no focus style in Input.

**Comment by benjycui** [comment]
WIP

**Comment by benjycui** [comment]
因为那个项提供了 `initialValue=''`，空串应该理解为不存在，我处理下。

**Comment by benjycui** [comment]
> 空串应该理解为不存在

因为视觉上根本就看不到。
