### ISSUE TITLE
动态主题错误

### ISSUE THREAD

**Issue by strongyc** [ant-design/ant-design#36138]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/92u39b?file=/demo.js:27-55)

### Steps to reproduce

https://codesandbox.io/s/92u39b?file=/demo.js:27-55

### What is expected?

官网给你demo，使用  ConfigProvider.config({
      theme: mergedNextColor,
    });设置主题不生效

### What is actually happening?

该如何动态设置主题

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 17.2 |
| System | windows10 |
| Browser | 98 |

**Comment by afc163** [comment]
https://ant.design/docs/react/customize-theme-variable-cn
