### ISSUE TITLE
在model组件中使用表格拖拽，会有被拖拽项完全透明的bug

### ISSUE THREAD

**Issue by KevinBrother** [ant-design/ant-design#36134]
### Reproduction link

[https://0o7ohx.csb.app/](https://0o7ohx.csb.app/)

### Steps to reproduce

可拖拽Table外层包一个Modal组件即可复现。
``` 
<Modal visible={true}>
      <Table
        pagination={false}
        dataSource={dataSource}
        columns={columns}
        rowKey="index"
        components={{
          body: {
            wrapper: DraggableContainer,
            row: DraggableBodyRow
          }
        }}
      />
    </Modal>
```

### What is expected?

与未包装Moal时展现一致

### What is actually happening?

被拖拽项完全透明了

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 17.0.1 |
| System | macos 12.0.1 |
| Browser | chrome 100 |

**Comment by afc163** [comment]
https://codesandbox.io/s/tuo-zhuai-shou-bing-lie-antd-4-21-3-forked-dgmrx3
