### ISSUE TITLE
ant-design 官网访问 500 错误

### ISSUE THREAD

**Issue by SmithJson** [ant-design/ant-design#36146]
### Reproduction link

[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce

打开官网

### What is expected?

官网可以访问

### What is actually happening?

访问报 500 错误

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.30 |
| System | Mac 10.15.7 |
| Browser | Chrome 102.0.5005.115 |

**Comment by see365** [comment]
好久了 什么情况啊

**Comment by sirzxj** [comment]
https://ant-design.gitee.io/index-cn

**Comment by GOWxx** [comment]
same #36145

**Comment by SmithJson** [comment]
> https://ant-design.gitee.io/index-cn

非常感谢

**Comment by afc163** [comment]
等 https://www.cloudflarestatus.com/ 恢复。

**Comment by RexHarris** [comment]
尝试过上面给出的镜像，但切换到3.x仍然报500
