### ISSUE TITLE
https://ant.design/ died. 

### ISSUE THREAD

**Issue by postbird** [ant-design/ant-design#36145]
![image](https://user-images.githubusercontent.com/16200574/174732300-78bff4da-7f95-4b8d-b0ec-49ba85f93982.png)

**Comment by GOWxx** [comment]
国内网络环境波动，网站本身是可以访问的
![image](https://user-images.githubusercontent.com/12870715/174733804-8e44d83a-6017-42a8-8a8d-7f3a1935cd1a.png)


可以先用国内镜像访问
https://ant-design.antgroup.com/index-cn
https://ant-design.gitee.io/
