### ISSUE TITLE
The Layout.Sider freezes whole application

### ISSUE THREAD

**Issue by davitp** [ant-design/ant-design#36158]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-m71ink?file=/package.json)

### Steps to reproduce

With React 18 and antd 4.21.3 some components are freezing the window.

In particular, Layout.Sider with a Menu inside freezes with (sometimes without) breakpoint='md'. 

### What is expected?

Expecting window to stay operational.

### What is actually happening?

Browser window hangs until gets killed.

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18 |
| System | Windows 10 |
| Browser | Firefox 101 |

**Comment by afc163** [comment]
It works fine in my machine.

**Comment by davitp** [comment]
Could not reproduce the behaviour in another repository with the same package set. However, it happens constantly with two components: Menu and Popconfirm. 

This issue is reproducible ONLY in firefox. Chrome works fine. 

Here is a stack trace after the script is forced to terminate, hope this will give an idea (looks like a recursion): 
`
swap@http://localhost:3001/static/js/vendors~main.chunk.js:106499:16
getWHIgnoreDisplay@http://localhost:3001/static/js/vendors~main.chunk.js:106647:9
@http://localhost:3001/static/js/vendors~main.chunk.js:106659:18
getRegion@http://localhost:3001/static/js/vendors~main.chunk.js:106970:15
doAlign@http://localhost:3001/static/js/vendors~main.chunk.js:107101:27
alignElement@http://localhost:3001/static/js/vendors~main.chunk.js:107247:10
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138023:80
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
promise callback*onInternalAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193459:27
Align/_useBuffer<@http://localhost:3001/static/js/vendors~main.chunk.js:138031:22
trigger@http://localhost:3001/static/js/vendors~main.chunk.js:138148:11
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:138106:16
forceAlign@http://localhost:3001/static/js/vendors~main.chunk.js:193446:114
onInternalAlign/<@http://localhost:3001/static/js/vendors~main.chunk.js:193460:11
`

**Comment by davitp** [comment]
We were not able to reproduce the issue in a minimal template, however, the issue is reproducible on an existing project.

The best guess we have this time is, that the issue happens due to concurrent rendering, as downgrading to React 17 solves the problem. 

More, the issue does not happen if the menu is manually collapsed and then uncollapsed. After that, on breakpoint='md' automatic collapse works as expected. Hope this information will help further investigation.
