### ISSUE TITLE
TimePicker not working correctly

### ISSUE THREAD

**Issue by MrFarhan** [ant-design/ant-design#36155]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fjp2ut)

### Steps to reproduce

Step 1- In the Start time select 11:00:00.
Step 2- In End time select 01:00:00
- it will switch the values
- This also happens with the time picker with AM and PM (like 11:00 AM start time and 01:00 PM end time, if we enter this then it will switch the values)

### What is expected?

Values should not be switched, values should remain the same as what the user has entered

### What is actually happening?

Values are being switched 

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 17.0.2 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by MadCcc** [comment]
How it works with AM and PM? Switching start time and end time if invalid makes sense to me.

**Comment by MrFarhan** [comment]
For example, I want to book an appointment from 11:00 PM till 1:00 AM so why it is changing my time.

I have not asked for any validation.

And what about in 24 hours scenario ?

**Comment by therbta** [comment]
The problem occurs when 'dayjs' is not used. I used to use 'moment', but I found out it's not compatible. 
Therefore, use 'dayjs' instead.
