### ISSUE TITLE
Layout的Sider折叠时Menu闪烁

### ISSUE THREAD

**Issue by juneszh** [ant-design/ant-design#36152]
### Reproduction link

[https://codesandbox.io/s/antd-reproduction-template-forked-447gqm?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-forked-447gqm?file=/index.js)

### Steps to reproduce

展开2级目录后，收起Sider

### What is expected?

不出现2级目录闪烁

### What is actually happening?

2级目录闪烁

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | Ubuntu |
| Browser | Firefox |

---
![menu](https://user-images.githubusercontent.com/2436252/174746516-c2d0d177-9339-47f3-9adc-8140d6c5d0b0.gif)

antd@4.21.3

_Originally posted by @juneszh in https://github.com/ant-design/ant-design/issues/35343#issuecomment-1161392675_

**Comment by juneszh** [comment]
[https://codesandbox.io/s/antd-reproduction-template-forked-447gqm?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-forked-447gqm?file=/index.js)

**Comment by HalseySpicy** [comment]
我也遇到这个问题了，我排查到了问题。我目前使用的是 react 18 版本 ，18创建 Dom 使用的是ReactDOM.createRoot().render() 就会存在闪烁问题，用react17版本创建就没问题。
![企业微信截图_20220622152608](https://user-images.githubusercontent.com/51069636/174969329-d85f245b-2786-4a26-bc94-bdd061ff7111.png)

**Comment by HalseySpicy** [comment]
查了整整我两天🙃🙃🙃🙃

**Comment by luzuoquan** [comment]
Upload 组件也有类似的问题，貌似是动画层需要适配一下 React 18

**Comment by mleister97** [comment]
Is the issue already closed or still open? Facing the same problem...
Any suggested solution?

**Comment by mleister97** [comment]
So this issue is happening using React 17 & 18? Can you please tell me a fix for the issue?

**Comment by JarvisArt** [comment]
rc-menu 属性 mode 切换时 代码有 bug，已提交相关 pr:  https://github.com/react-component/menu/pull/497

**Comment by MadCcc** [comment]
5.5.1 和 4.24.10 验证均无该问题，先关闭了。

**Comment by junkiet** [comment]
> 我也遇到这个问题了，我排查到了问题。我目前使用的是 react 18 版本 ，18创建 Dom 使用的是ReactDOM.createRoot().render() 就会存在闪烁问题，用react17版本创建就没问题。 ![企业微信截图_20220622152608](https://user-images.githubusercontent.com/51069636/174969329-d85f245b-2786-4a26-bc94-bdd061ff7111.png)

官方建议使用 18,
warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more

**Comment by JarvisArt** [comment]
> > 我也遇到这个问题了，我排查到了问题。我目前使用的是 react 18 版本 ，18创建 Dom 使用的是

升级下antd的版本

**Comment by junkiet** [comment]
antd": "^5.13.1", 最新也是一样

**Comment by wr404274848** [comment]
所以ANTD5必须使用React18？

**Comment by junkiet** [comment]
> 所以ANTD5必须使用React18？

不清楚，我现在是那最新的 "antd": "^5.13.3" 也是OK的

**Comment by Junlin-Zhu** [comment]
还是会遇到Menu闪烁的情况。

nextjs: 14.1.1
antd: 5.15.1

有趣的是，我如果把antd降级到5.8.6就没有这个问题。

**Comment by junkiet** [comment]
> 还是会遇到Menu闪烁的情况。
> 
> nextjs: 14.1.1 antd: 5.15.1
> 
> 有趣的是，我如果把antd降级到5.8.6就没有这个问题。

我是没有，不懂你的写法哪里出事
