### ISSUE TITLE
DatePicker不支持Safari？

### ISSUE THREAD

**Issue by Lxyour** [ant-design/ant-design#3616]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:Mac OS X 10.11.3 
- 浏览器及其版本:Safari 9.0.3 (11601.4.4)

#### 您做了什么？请提供尽可能详细的重现步骤。

DatePicker控件不支持Safari？

#### 您期待的结果是:

选择日期后得到正常的日期

#### 实际上的结果是:

实际选择日期后点击确定后，回调返回NaN

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
实测可以。
