### ISSUE TITLE
DatePicker日期国际化错误 中英文都存在

### ISSUE THREAD

**Issue by Mr-Grp** [ant-design/ant-design#36162]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-i2ijq?file=/index.js)

### Steps to reproduce

添加全局本地化

### What is expected?

显示应该是全部中文

### What is actually happening?

日期有中文有英文

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 17.0.1 |
| System | macos |
| Browser | chrome |

---
看了下，antd 依赖 moment 2.29.3 rc-picker 依赖 2.29.1；
我降级 2.29.1，ts会报类型错（传入的 Moment 类型 和 antd 要求的 moment.Moment 类型不匹配），升级2.29.3，中英混合
https://github.com/ant-design/ant-design/issues/23891 跟这个问题一样；
目前我降级了，并且把传入的 Moment 断言成了 any，它可以正常工作

**Comment by afc163** [comment]
https://ant.design/components/date-picker-cn/#%E5%9B%BD%E9%99%85%E5%8C%96%E9%85%8D%E7%BD%AE

**Comment by Mr-Grp** [comment]
> https://ant.design/components/date-picker-cn/#%E5%9B%BD%E9%99%85%E5%8C%96%E9%85%8D%E7%BD%AE
> 
> [#23891 (comment)](https://github.com/ant-design/ant-design/issues/23891#issuecomment-624429227)
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-2xmung

其实问题是因为，我自己装了 moment，如果我卸载了 moment，antd 自己的node_modules 里会安装 2.29.3，而外层的node_modules 会安装rc-picker 需要的 2.29.1，这样就会是正常的
但是一旦我自己装了依赖，antd 就不会在自己的 node_modules 再次安装 moment了，而是会使用我安装的版本，但是由于 rc-picker 和 antd 需要的版本不一样，无论我安装哪个版本都会有问题

为啥不考虑和 rc-picker 使用同一个版本的 moment？

**Comment by yoyo837** [comment]
2.29.1和2.29.3完全可以被npm抹平。

**Comment by afc163** [comment]
rc-picker 依赖的是更宽的版本，两者应该是兼容的，会只安装一个版本。

**Comment by Mr-Grp** [comment]
> 

但事实上。。。如果我手动装了 moment 2.29.3,就会中英混合了。。。
![image](https://user-images.githubusercontent.com/32298855/174948929-ffcf9c60-18fe-4a8d-81d7-99d119268c22.png)

**Comment by Mr-Grp** [comment]
> 

但事实上。。。我装了 2.29.3 ，再引入
import 'moment/locale/zh-cn'; 
是从 2.29.3 引入的，会中英混合
如果是 2.29.1 引入的，就会正常显示中文。。。
![image](https://user-images.githubusercontent.com/32298855/174949989-04725920-300b-49ad-8fd9-624e24e414d6.png)
但是 2.29.1 antd 又会报 ts 类型错误

**Comment by Mr-Grp** [comment]
沙箱为啥没有这个问题我也很奇怪...😅

**Comment by yoyo837** [comment]
删掉node_modules 和 lock文件重装。

**Comment by Mr-Grp** [comment]
> 

老项目，不敢呀。。。😅，暂时用的 2.29.1 的版本，把报类型错先断言成 any 了，也正常运行

**Comment by afc163** [comment]
应该是被 lock 锁住了。

**Comment by Mr-Grp** [comment]
> 应该是被 lock 锁住了。

ok，非常感谢，暂时先通过断言any解决吧，不敢大动，运行不出问题就好，moment 两个 patch版本应该也是兼容的

**Comment by afc163** [comment]
可以试试 yarn upgrade moment

**Comment by Mr-Grp** [comment]
> 

好的🙏

**Comment by yoyo837** [comment]
测试一下不提交嘛。除非你是直接动运行时的项目。

**Comment by Mr-Grp** [comment]
> 

那我肯定是早就试过了，不太行，各种报错😭，才用了这个不太好的方式
