### ISSUE TITLE
Button loading style broken when has Chinese chars

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#36165]
https://codesandbox.io/s/duo-ge-an-niu-zu-he-antd-4-21-3-forked-gvn0md?file=/demo.js

<img width="286" alt="图片" src="https://user-images.githubusercontent.com/507615/174936178-8dc14ed8-0b63-4a3c-a957-bf25547a7c50.png">

**Comment by iqlong** [comment]
您好， 4.21.3之后的版本就没有这个bug了吧
