### ISSUE TITLE
Loading icon customisation

### ISSUE THREAD

**Issue by SameerLogistic** [ant-design/ant-design#36172]
### Reproduction link

[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce

*step-1:* **import { Button } from 'antd'**

*step-2:* **&lt;Button loading &gt;Save&lt;/Button&gt;**

### What is expected?

Button loading icon should be replaced with custom icon or image

### What is actually happening?

Currently button loading API gives two parameters as boolean | { delay: number }, there is no option to change loading icon

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | react/0.2.0 |
| System | All |
| Browser | All |

---
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M17.3333 10.9333H21.6C22.3111 10.9333 22.6667 11.2889 22.6667 12C22.6667 12.7111 22.3111 13.0667 21.6 13.0667H17.3333C16.6222 13.0667 16.2667 12.7111 16.2667 12C16.2667 11.2889 16.6222 10.9333 17.3333 10.9333Z" fill="white"/>
<path opacity="0.9" d="M19.6027 18.0933C19.7059 18.1914 19.7884 18.3091 19.8454 18.4396C19.9024 18.5701 19.9327 18.7106 19.9345 18.853C19.9364 18.9954 19.9097 19.1366 19.856 19.2685C19.8024 19.4004 19.7229 19.5202 19.6222 19.6209C19.5215 19.7216 19.4017 19.8011 19.2698 19.8547C19.138 19.9084 18.9967 19.9351 18.8543 19.9332C18.7119 19.9314 18.5714 19.9011 18.4409 19.8441C18.3105 19.7871 18.1927 19.7046 18.0947 19.6013L15.064 16.572C14.8724 16.3703 14.7672 16.1018 14.7707 15.8237C14.7743 15.5455 14.8864 15.2798 15.083 15.0831C15.2797 14.8864 15.5455 14.7743 15.8236 14.7707C16.1018 14.7672 16.3703 14.8724 16.572 15.064L19.6027 18.0947V18.0933Z" fill="white"/>
<path opacity="0.8" d="M12 16.2667C12.7111 16.2667 13.0667 16.6222 13.0667 17.3333V21.6C13.0667 22.3111 12.7111 22.6667 12 22.6667C11.2889 22.6667 10.9333 22.3111 10.9333 21.6V17.3333C10.9333 16.6222 11.2889 16.2667 12 16.2667Z" fill="white"/>
<path opacity="0.7" d="M5.90664 19.6027C5.70498 19.7943 5.43644 19.8995 5.1583 19.8959C4.88015 19.8924 4.6144 19.7803 4.4177 19.5836C4.22101 19.3869 4.10893 19.1212 4.10537 18.843C4.10181 18.5649 4.20705 18.2963 4.39864 18.0947L7.42798 15.064C7.62964 14.8724 7.89817 14.7672 8.17632 14.7707C8.45447 14.7743 8.72022 14.8864 8.91691 15.0831C9.11361 15.2798 9.22568 15.5455 9.22924 15.8237C9.23281 16.1018 9.12757 16.3703 8.93598 16.572L5.90664 19.6027Z" fill="white"/>
<path opacity="0.6" d="M2.39998 10.9333H6.66665C7.37776 10.9333 7.73332 11.2889 7.73332 12C7.73332 12.7111 7.37776 13.0667 6.66665 13.0667H2.39998C1.68887 13.0667 1.33331 12.7111 1.33331 12C1.33331 11.2889 1.68887 10.9333 2.39998 10.9333Z" fill="white"/>
<path opacity="0.5" d="M4.39736 5.90666C4.20577 5.705 4.10053 5.43647 4.10409 5.15832C4.10765 4.88017 4.21973 4.61442 4.41642 4.41773C4.61312 4.22103 4.87887 4.10896 5.15702 4.1054C5.43516 4.10183 5.7037 4.20707 5.90536 4.39866L8.93603 7.42667C9.12762 7.62833 9.23286 7.89686 9.2293 8.17501C9.22574 8.45316 9.11366 8.71891 8.91697 8.9156C8.72027 9.1123 8.45452 9.22437 8.17637 9.22793C7.89823 9.2315 7.6297 9.12626 7.42803 8.93466L4.39736 5.90666Z" fill="white"/>
<path opacity="0.3" d="M12 1.33333C12.7111 1.33333 13.0667 1.68889 13.0667 2.4V6.66667C13.0667 7.37778 12.7111 7.73334 12 7.73334C11.2889 7.73334 10.9333 7.37778 10.9333 6.66667V2.4C10.9333 1.68889 11.2889 1.33333 12 1.33333Z" fill="white"/>
<path opacity="0.12" d="M16.8014 8.70672C16.5997 8.89832 16.3312 9.00355 16.053 8.99999C15.7749 8.99643 15.5091 8.88435 15.3124 8.68766C15.1157 8.49096 15.0036 8.22521 15.0001 7.94707C14.9965 7.66892 15.1018 7.40039 15.2934 7.19872L18.3227 4.16805C18.5244 3.97646 18.7929 3.87122 19.071 3.87478C19.3492 3.87834 19.6149 3.99042 19.8116 4.18711C20.0083 4.38381 20.1204 4.64956 20.124 4.92771C20.1275 5.20585 20.0223 5.47439 19.8307 5.67605L16.8014 8.70672Z" fill="white"/>
</svg>

**Comment by afc163** [comment]
You can use `icon` property to create a new loading button in upper application.

**Comment by SameerLogistic** [comment]
@afc163 When we apply icon prop, it always displays instead of only loading time.
