### ISSUE TITLE
Cascader bug

### ISSUE THREAD

**Issue by ryannealmes** [ant-design/ant-design#3617]
I ran into a bug with the cascader where it highlights multiple parent items when a child item is selected. This seems to stem from the case where a child `value` is equal to a parent `value` in the cascader.

Note I managed to get around this by appending the entity I was working with, so if the first column was ItemType and the second column was Item I would make the values for the ItemType column itemType:id and item:id. This would ensure that that nothing could match incorrectly.

This is a bit tricky to explain so I included an example - http://codepen.io/anon/pen/vXVgPm?editors=001

If you select `1 > 2` you will see what I mean.

**Comment by afc163** [comment]
Thx, you can reinstall antd to fix it.

**Comment by ryannealmes** [comment]
Working like magic. Thanks :)
