### ISSUE TITLE
Layout 的 Sider 在 React 18 版本中折叠时 SubMenu 会闪烁

### ISSUE THREAD

**Issue by HalseySpicy** [ant-design/ant-design#36174]
### Reproduction link

[http://hooks.spicyboy.cn/#/proTable/useHooks](http://hooks.spicyboy.cn/#/proTable/useHooks)

### Steps to reproduce

1、进入系统
2、到 超级表格/使用 Hooks 模块下
3、点击折叠菜单

### What is expected?

折叠菜单时 subMenu 不闪烁

### What is actually happening?

折叠菜单时 subMenu 闪烁

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1.0 |
| System | windows 21H2 |
| Browser | 谷歌 102.0.5005.63 |

---
目前存在是因为使用了 react 18 版本 ，18版本 创建 Dom 使用的是ReactDOM.createRoot().render() 就会存在闪烁问题，用react17版本创建就没问题。

**Comment by afc163** [comment]
Duplicate of #36152
