### ISSUE TITLE
DatePicker增加allowClear配置

### ISSUE THREAD

**Issue by lslvxy** [ant-design/ant-design#3618]
希望DatePicker能增加allowClear配置,现在默认是支持clerar的

**Comment by benjycui** [comment]
这儿可以加：

https://github.com/ant-design/ant-design/blob/master/components/date-picker/createPicker.tsx#L131-L135

https://github.com/ant-design/ant-design/blob/master/components/date-picker/RangePicker.tsx#L88-L93

试着来个 PR？

**Comment by benjycui** [comment]
WIP
