### ISSUE TITLE
antd 4.20版本Menu组件推荐使用items的写法，在5.0会废弃jsx的语法，如果有SSR的需求，没有办法处理

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design#36188]
### What problem does this feature solve?

解决SSR的问题，举个例子，antd跟nextjs一起使用，点击菜单，想使用nextjs的Link，就没办法使用

### What does the proposed API look like?

希望不要废弃菜单jsx的语法，或者是提供一个render函数，让用户可以自定义结构。

**Comment by MadCcc** [comment]
`label` 支持 ReactNode

**Comment by ideaviewes** [comment]
@afc163 ，之前是可以在Menu标签内写jsx的，比如这样
![image](https://user-images.githubusercontent.com/5431843/175852504-31df549f-0af7-4da7-b314-b3648c2a0943.png)
我看到警告说5.0会废除jsx这种写法
支持ReactNode的话，那应该就可以解决我的问题了
我的目录是个树形结构，我是在后台生成的这个树形，在前端递归生成需要的jsx的结构
废除jsx的写法后，我还是需要递归生成items的结构，因为要把Label弄成ReactNode
能不能提供一个方法，让用户可以自己控制每个Item的渲染？这样的话，就不需要在前段去做递归了

**Comment by valcosmos** [comment]
Recently, I used menu component like this, it does work.

```tsx
  const menuList: MenuProps['items'] = [
    {icon: <HomeOutlined/>, label: <Link href={'/'}>首页</Link>, key: '/'},
    {icon: <LinkOutlined/>, label: <Link href={'/links'}>友链</Link>, key: '/links'},
    {icon: <ProjectOutlined/>, label: <Link href={'/open-source'}>开源</Link>, key: '/open-source'},
    {icon: <FieldTimeOutlined/>, label: <Link href={'/timeline'}>时间轴</Link>, key: '/timeline'},
    {icon: <MessageOutlined/>, label: <Link href={'/messages'}>留言</Link>, key: '/messages'},
    {icon: <InfoCircleOutlined/>, label: <Link href={'/about'}>关于</Link>, key: '/about'}
  ]
```

**Comment by ideaviewes** [comment]
@valcosmos ,3q

**Comment by JayShen1943** [comment]
我也有这个疑惑，如果icon是动态的，数据库中存的svg的名字，不用jsx怎么写

**Comment by valcosmos** [comment]
> 我也有这个疑惑，如果icon是动态的，数据库中存的svg的名字，不用jsx怎么写

可以尝试将`@ant-design/icons` 全量导入后，通过 `React.createElement` 生成。
