### ISSUE TITLE
Textarea looses focus on "hasFeedback" change

### ISSUE THREAD

**Issue by lscheibel** [ant-design/ant-design#36180]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-validation-antd-4-21-3-forked-textarea-looses-focus-on-hasfeedback-change-wwokdz?file=/demo.js)

### Steps to reproduce

Start writing in the TextArea.

### What is expected?

TextArea retains focus even when the hasFeedback prop changes.

### What is actually happening?

The TextArea looses focus after each keystroke.

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.3.0 |
| System | macOS 12.3.1 |
| Browser | Chrome 102 |

**Comment by afc163** [comment]
You should keep `hasFeedback` stable, and use `status=""` to hide feedback icon.
