### ISSUE TITLE
InputNumber: userTyping does not work inside Form.Item

### ISSUE THREAD

**Issue by extempl** [ant-design/ant-design#36199]
### Reproduction link

[https://codepen.io/extempl/pen/jOZjQxX?editors=0011](https://codepen.io/extempl/pen/jOZjQxX?editors=0011)

### Steps to reproduce

Type inside the field - the userTyping will be always false.

### What is expected?

userTyping should be true when it should be true.

### What is actually happening?

userTyping is false

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 16.4.0 |
| System | - |
| Browser | Chrome |

---
The issue is reproduced when
- the inputNumber is within Form.Item (i.e. controlled) (any other place works just fine with stopPropagation)
- the keydown event is not propagated from outer wrapper and up (commenting the stopPropagation fixes the issue within Form.Item)

**Comment by xccjk** [comment]
Incorrect use

demo: [https://codesandbox.io/s/ge-shi-hua-zhan-shi-antd-4-22-2-forked-fc6b18?file=/demo.js](https://codesandbox.io/s/ge-shi-hua-zhan-shi-antd-4-22-2-forked-fc6b18?file=/demo.js)

**Comment by extempl** [comment]
@xccjk Hm, thanks, with functuion returning the ref it does work. Is there any explanation for this?
