### ISSUE TITLE
typings d.ts 错误

### ISSUE THREAD

**Issue by unclemake** [ant-design/ant-design#3619]
- antd 版本:2.1.0
- vscode

我使用  npm install @types/react  安装了react的typings
然后 npm install antd

d.ts 文件报错
比如文件：Input.d.ts
第一行：import React from 'react';

正常的应该是：
import * as React from 'react';

**Comment by benjycui** [comment]
Add this to your `tsconfig.json` https://github.com/ant-design/ant-design/blob/master/tsconfig.json#L5

**Comment by unclemake** [comment]
ok   谢谢
