### ISSUE TITLE
Input.Search allowClear

### ISSUE THREAD

**Issue by QDyanbing** [ant-design/ant-design#36191]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0jxclr?file=/index.js)

### Steps to reproduce

输入框输入值
点开console
清除console信息
点击搜索框的清除按钮

### What is expected?

onChange 先执行
onSearch后执行

### What is actually happening?

onSearch先执行
onChange后执行

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | ^17.0.0 |
| System | mac |
| Browser | 99.0.4844.51（正式版本） (arm64) |

---
import { useState, useCallback, useRef } from 'react';
import { getUsers } from '@/services';
import { useRequest } from 'ahooks';

export default function usePageStore() {
  const [condition, setCondition] = useState<string>();
  const search = useRef(condition);
  search.current = condition;

  const { data, loading, refresh } = useRequest(
    () => getUsers({  condition: search.current || undefined }),
    {
      refreshDeps: [search],
      ready: isLoad,
    },
  );

  const onSearchChange = useCallback(
    (e) => {
      setCondition(e.target.value);
    },
    [setCondition],
  );

  const onSearch = useCallback(
    () => {
      setPageNum(1);
      refresh();
    },
    [search, setPageNum, refresh],
  );

}

这这样的场景中，点击清除按钮请求后端所使用的数据还是清除之前的，尽管在onSearch中重新set一下condition值也拿不到最新的

**Comment by MadCcc** [comment]
受控状态下就算两个顺序倒过来，执行时也是在一次渲染内，你的 state 还是不会变。
建议用 `onSearch` 的回调参数 `value` 的值搜索
