### ISSUE TITLE
node端渲染被阻断，由动画库 velocity-animate 引起

### ISSUE THREAD

**Issue by ascoders** [ant-design/ant-design#362]
hello~各位辛勤的开发者们，我偶然间测试了贵项目的服务端渲染，发现涉及到动画部分会被卡住，例如引用 `Menu` 组件之时，究其原因，原来是引入了不兼容node端的动画库 `"velocity-animate": "~1.2.2"`

希望能在ant的库中做一下兼容。

这个问题在他们那也引发了一阵讨论 https://github.com/julianshapiro/velocity/issues/474 ， 看来可以在引入的代码层面区分浏览器与服务端。

看来他们已经在动画库层面解决了这个问题（ https://github.com/julianshapiro/velocity/pull/479 好像还没合并，求后续关注）~

**Comment by afc163** [comment]
discuss in #215

**Comment by afc163** [comment]
欢迎跟踪这个问题以及给我们 PR ~

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design/commit/fb43a1b86d4ba4b1daacddf12ebbda70932c7910

**Comment by amowu** [comment]
QueueAnim 也有引用到 velocity-animate，而且不是經過 openAnimation.js，所以在 server render 的時候也會錯誤。:'(
