### ISSUE TITLE
安装最新antd，es包里没有js文件，style里的less文件也丢失

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design#36207]
### Reproduction link

[http://localhost](http://localhost)

### Steps to reproduce

yarn add antd

### What is expected?

包含完整的js和css文件

### What is actually happening?

缺失js和css文件

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | win10 x64 |
| Browser | chrome 90 |

**Comment by yoyo837** [comment]
应该是你自己的问题，npm上面是正常的

**Comment by afc163** [comment]
https://unpkg.com/browse/antd@4.21.3/es/ 有的
