### ISSUE TITLE
Table in the expandable row gets additional margin when parent Table is set to small size

### ISSUE THREAD

**Issue by jakubszalek** [ant-design/ant-design#36206]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-columns-antd-4-21-3-forked-y1byoo?file=/demo.js)

### Steps to reproduce

1. Create a Table with expandable rows and size set to `small`
2. Put Table component inside expandable wrapper
3. Inner Table wrapper has applied additional margin which is not correct

### What is expected?

Table in expandable wrapper should not have applied any margin.

### What is actually happening?

Table in expandable wrapper has applied the following style that sets margin:

```
.ant-table.ant-table-small .ant-table-tbody .ant-table-wrapper:only-child .ant-table {
    margin: -8px -8px -8px 25px;
}
```

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.3 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
It is by designed to match first column between parent table and child table. You can override it if you don't need this style.
