### ISSUE TITLE
Cascader 多选模式能否在次级节点中存在禁用项时，选中全部可选项后不自动回显为父节点

### ISSUE THREAD

**Issue by dabanheiji** [ant-design/ant-design#36208]
### What problem does this feature solve?

我们的场景是多个级联菜单中的可选项存在互斥的情况下，我在第一个级联选择器选中一些节点后在第二个级联选择器中会禁用这些节点，但是在第二个级联选择器选择的时候恰好选择了第一个选择器没有选中的全部节点就会强制被修改为父节点，这种场景下使用showCheckedStrategy去控制明显很不合理，所以希望ant design后续能考虑一下子节点中存在禁用节点的情况

### What does the proposed API look like?

添加一个prop属性，用于控制子节点存在禁用选项时，选中全部可选节点是否强制选中父节点，或在options中添加类似disableCheckbox的属性用于只禁用选择器

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by MadCcc** [comment]
具体还是看下使用场景，能否提供下简单复现？
