### ISSUE TITLE
移除鼠标后 Menu 子菜单不消失

### ISSUE THREAD

**Issue by qhdxwdm** [ant-design/ant-design#36212]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-ji-cai-dan-antd-4-21-3-forked-90fv6w)

### Steps to reproduce

将鼠标移入后再移出 

### What is expected?

子菜单消失

### What is actually happening?

子菜单不消失

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | react |
| System | macos |
| Browser | chrome |

**Comment by MadCcc** [comment]
你用 `openKeys` 受控了，建议配合 `onVisibleChange` 使用。
Example: https://codesandbox.io/s/duo-ji-cai-dan-antd-4-21-3-forked-e6300l?file=/demo.js
