### ISSUE TITLE
Allowing more control on InputNumber

### ISSUE THREAD

**Issue by aghArdeshir** [ant-design/ant-design#36216]
### What problem does this feature solve?

I want to have an Input Number component. InputNumber has those beautiful up & down controls and is more numeric, so I want to use it. But the problem is that I don't have much control over it. For my specific use case I want my users not being able to enter decimal values (e.g. 45.789). I want them to be only able to write in numbers. (writing dot (`.`) or any letter should not appear in the input box at all)

https://codesandbox.io/s/basic-antd-4-21-3-forked-vznuob?file=/demo.js

### What does the proposed API look like?

I believe the `value` property must behave the same way it behaves for inputs in DOM. It must force the current value of the input.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14069#issuecomment-451468013
https://github.com/ant-design/ant-design/issues/28700#issuecomment-755014092

**Comment by aghArdeshir** [comment]
@afc163 What about having this feature in a very un-breaking way, like having a new prop:
```tsx
<InputNumber forceValue={3} />
```
or
```tsx
<InputNumber forceValue={() => 3} />
```

So it can handle another range of use cases like mine!

I just checked several other UI Libraries and all their number inputs allow developer to have freedom to have controlled input (just like how they are comfortable in React) (https://reactjs.org/docs/forms.html#controlled-components)

Take a look at each of these UI libraries (links already take you to intended page) (Note that you cannot enter letters in none of those input numbers)

https://rsuitejs.com/components/input-number/
https://primefaces.org/primereact/inputnumber/
https://chakra-ui.com/docs/components/number-input/usage
https://blueprintjs.com/docs/#core/components/numeric-input

https://mui.com/material-ui/react-text-field/#form-props (There is a number input in the middle)
https://v2.grommet.io/maskedinput (here it is possible using a masked input)
https://react-bootstrap.netlify.app/forms/input-group/ (It does not have a pre-pared example for preventing you from entering letters, but you can directly change the code example in place and make it controlled)

So there **is** a use case somewhere in the world to be able to have this (from UX point-of-view)

**Comment by aghArdeshir** [comment]
I can create and continue the discussion on `react-component/input-number` repository if required.

**Comment by aghArdeshir** [comment]
@afc163 also note that I created this issue as feature request not as a bug. Meaning I already am familiar with this design decision of Ant Design.

**Comment by aghArdeshir** [comment]
> [#14069 (comment)](https://github.com/ant-design/ant-design/issues/14069#issuecomment-451468013) [#28700 (comment)](https://github.com/ant-design/ant-design/issues/28700#issuecomment-755014092)

@afc163 the second link is kinda outdated and is trying to prove a point through some code that does not exist anymore. (but the concept is still there)
