### ISSUE TITLE
table组件的固定表头能否不用scroll属性实现？是否能用其他属性实现？

### ISSUE THREAD

**Issue by githubqh** [ant-design/ant-design#36218]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-kong-de-shai-xuan-he-pai-xu-antd-4-21-3-forked-crg6nc?file=/demo.js)

### Steps to reproduce

加上scroll属性

### What is expected?

是否有其他属性设置固定表头？

### What is actually happening?

暂无解决方案

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | all |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
不能。

**Comment by huanglei1991** [comment]
https://ant-design.antgroup.com/components/table-cn/#components-table-demo-sticky
你可能想要的是这种？

**Comment by githubqh** [comment]
> https://ant-design.antgroup.com/components/table-cn/#components-table-demo-sticky 你可能想要的是这种？
谢谢，不是这种~因为scroll属性和antd-mobile的无限滚动冲突了，导致无限滚动不能正常使用，所以我想问下是否有其他办法设置固定表头
https://mobile.ant.design/zh/components/infinite-scroll#%E5%B1%9E%E6%80%A7
