### ISSUE TITLE
Input className is wrongly attributed to wrapper span when Input has prefix

### ISSUE THREAD

**Issue by herbertpimentel** [ant-design/ant-design#36233]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/and-input-wrong-attribuition-to-classname-dsvhzd)

### Steps to reproduce

1) Create an Input with class name
inspect the Input, the class name is correctly attributed to the html input element

2) Create and  Input with class name and prefix 
inspect the Input, the class name is wrongly attributed to the span that wraps the input element

### What is expected?

We expect that className given to Input component to be attributed to the html input element, even when it has a wrapper due to prefix/sufix

### What is actually happening?

The class name is is wrongly attributed to the span that wraps the input element due to the html prefix structure

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.* |
| System | MacOS Montrey 12.4 (21F79) |
| Browser | Version 102.0.5005.115 (Official Build) (arm64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14902#issuecomment-465453189
