### ISSUE TITLE
用ant打包之后图片路径找不到，是不是webpack.config.js没有配配置文件

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#3623]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

#### 您期待的结果是:
打包之后图片可以找到

#### 实际上的结果是:

求配置文件的代码

**Comment by yesmeck** [comment]
请描述的详细点，webpack 是自己配置的还是用 antd-init/dva-cli 生成的，你做了什么等等。

**Comment by afc163** [comment]
webpack 问题建议到其他地方进行提问。
