### ISSUE TITLE
Form表单 DatePicker如果设置了initialValues默认值就会报错

### ISSUE THREAD

**Issue by 329697166** [ant-design/ant-design#36232]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-hermann-5n7e01)

### Steps to reproduce

export default function App() {
  const initialValues = {
    test: "2022-06-30T11:00:03.777Z"
  };

  return (
    <Form initialValues={initialValues}>
      <Form.Item label="日期选择" name="test">
        <DatePicker />
      </Form.Item>
    </Form>
  );
}

### What is expected?

日期选择应该显示正常的日期格式

### What is actually happening?

date.clone is not a function

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 16.14.0 |
| System | window 10 |
| Browser | Chrome 100.0.4896.127 |

---
这个日期如果在Form.Item组件设置的initialValue是能正常使用的,但是正常的情况下是希望在Form里面设置initialValues

**Comment by afc163** [comment]
DatePicker don't accept string value but moment instance.

**Comment by afc163** [comment]
设置 Form.Item initialValue 也是会报错的。
