### ISSUE TITLE
tabs in a modal

### ISSUE THREAD

**Issue by edanespi93** [ant-design/ant-design#36238]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-dust-qjw8dq?file=/src/App.js)

### Steps to reproduce

1.- open modal
2.- select tabs # 13 or >
3.-close modal , error key duplicate 

### What is expected?

solved bug 

### What is actually happening?

many tabs inside a modal generates an error, selecting tab inside the menu and then closing the modal gives an error key duplicate.

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18 |
| System | linux, windows |
| Browser | all browser |

**Comment by afc163** [comment]
Cannot reproduce in your codesandbox.

<img width="530" alt="图片" src="https://user-images.githubusercontent.com/507615/175843571-1a330e2a-9fc9-456d-8dc2-5a499f431f20.png">

**Comment by afc163** [comment]
<img width="760" alt="图片" src="https://user-images.githubusercontent.com/507615/176076444-0f2344e3-6fb6-4185-b99e-d2a936a11487.png">

Still cannot reproduce.
