### ISSUE TITLE
CheckboxGroup的onChange事件返回值不希望是进行过排序的

### ISSUE THREAD

**Issue by undefined9999** [ant-design/ant-design#36249]
### What problem does this feature solve?

CheckboxGroup是否考虑增加返回值格式的配置, 支持配置返回值是进行过排序的或者是实际进行选择的前后顺序的数组

### What does the proposed API look like?

期望增加配置项来支持是否需要进行过排序的返回值

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17297

CheckGroup 是一个顺序无关的组件，应该不会提供这个配置。
