### ISSUE TITLE
antd Tabs 组件 激活状态的下滑线 视觉效果不同（明显 有粗有细）

### ISSUE THREAD

**Issue by 521guyu** [ant-design/ant-design#36253]
### Reproduction link

[https://3x.ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar-node](https://3x.ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar-node)

### Steps to reproduce

肉眼观察。会发现 它们表现的不太一样

### What is expected?

应该 呈现出 一样的结果

### What is actually happening?

表现的结果一样

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 16.2.0 |
| System | 3.26.19 和 4.x |
| Browser | chorme、edge |

---
官网的例子 里 就能看出
https://3x.ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar-node

**Comment by MadCcc** [comment]
active 的 tab 下划线是 2px，设计如此

**Comment by 521guyu** [comment]
> active 的 tab 下划线是 2px，设计如此

可是 官网的例子https://ant.design/components/tabs-cn/  
第一个例子和第二个 下划线 肉眼看 感觉 不太 一样
