### ISSUE TITLE
Menu导航菜单怎么不超出省略？

### ISSUE THREAD

**Issue by BabyFriedCake** [ant-design/ant-design#36252]
### What problem does this feature solve?

不需要 Menu导航菜单  组件有超出省略

### What does the proposed API look like?

不需要 Menu导航菜单  组件有超出省略

**Comment by afc163** [comment]
为啥不需要省略呢？原始需求是什么样的？

**Comment by BabyFriedCake** [comment]
> 为啥不需要省略呢？原始需求是什么样的？

<img width="976" alt="image" src="https://user-images.githubusercontent.com/33448924/175913817-012be73e-31fe-4739-ba84-059678d8c650.png">
您好，我的导航高度是动态的，出现省略后，样式显示会有问题。

![image](https://user-images.githubusercontent.com/33448924/175914764-9080cfc5-9b49-45b2-880e-284f5f2c217d.png)

**Comment by afc163** [comment]
不省略就只能换行了，在你的场景下感觉也很奇怪。

**Comment by BabyFriedCake** [comment]
> 略就只能换行了，在你的场景下感觉也很奇怪

好的，我了解了，谢谢你的解答！
