### ISSUE TITLE
Divider组件中orientationMargin属性添加到项目中，本项目和自己的demo中该属性均未生效，搜索了相关的issue暂时未查询到该问题。

### ISSUE THREAD

**Issue by haichaozhang-ng** [ant-design/ant-design#36264]
### Reproduction link

[https://ant-design.antgroup.com/components/divider-cn/](https://ant-design.antgroup.com/components/divider-cn/)

### Steps to reproduce

项目中直接引入Divider组件，项目中直接Ts报错不能将类型“{ children: string; style: { fontSize: string; }; orientation: "left"; orientationMargin: string; }”分配给类型“IntrinsicAttributes & DividerProps & { children?: ReactNode; }”。
  类型“IntrinsicAttributes & DividerProps & { children?: ReactNode; }”上不存在属性“orientationMargin”。判断该组件没有该属性。

### What is expected?

orientationMargin能够正常生效

### What is actually happening?

Ts会自动报错，并且该属性未生效。

| Environment | Info |
| --- | --- |
| antd | 4.15.1 |
| React | 16.13.1 |
| System | linux |
| Browser | 谷歌浏览器 |

**Comment by haichaozhang-ng** [comment]
记录一下，问题升级了最新版本就OK了，我当时antd的版本是4.15.1，升级最新4.21.4问题解决，但是api文档里面并未标注有明确的版本要求。

**Comment by afc163** [comment]
@haichaozhang-ng 可以来个 PR
