### ISSUE TITLE
Checkbox.Group的onChange事件返回值不希望是进行过排序的

### ISSUE THREAD

**Issue by undefined9999** [ant-design/ant-design#36262]
### What problem does this feature solve?

Checkbox.Group是否考虑增加返回值格式的配置, 支持配置返回值是进行过排序的或者是实际点击顺序选择的前后顺序的数组.
![image](https://user-images.githubusercontent.com/35595635/176071744-97349ced-db01-440b-9596-5518932d9a68.png)
![image](https://user-images.githubusercontent.com/35595635/176071920-28deefe7-7845-4bae-a8ed-686b68981b21.png)

### What does the proposed API look like?

Checkbox.Group是否考虑增加返回值格式的配置, 支持配置返回值是进行过排序的或者是实际点击顺序选择的前后顺序的数组.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/36249#issuecomment-1167035717

我们默认提供的是按 check 顺序给的，但这个组件本身是顺序无关的，总之不要依赖 value 数组的顺序去实现应用功能。

**Comment by undefined9999** [comment]
现在组件给出来的值是按照options进行过排序的值, 而不是onclick顺序的值
