### ISSUE TITLE
网站维护

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design#3626]
- 网站去掉响应式代码，比如类似这些`Col lg={4} md={6} sm={7} xs={24}`，即便在手机上看、也应该看到的是和在 pc 上样子一样。
- mobile 站点 pc 部分 80% 代码和这里都一样，应该尽量抽取出公共的功能和组件、相同代码做到真正可复用。
- antd / antd-mobile pc 站点同一个人维护，维护同一份或同样的代码（数据不同可抽出成配置项），代码也尽量比现在少写点吧。。

**Comment by benjycui** [comment]
在做了。。。后面会增加 Theme as dependencies 支持，这样就可以把 Theme 作为 npm 包发布，依赖。

**Comment by afc163** [comment]
响应式还是要做的，这是起码的。

**Comment by yiminghe** [comment]
mobile 网站要简化重做

**Comment by warmhug** [comment]
站点的 mobile 部分，我正在改。 pc 部分 antd / antd-mobile 那都本杰来维护吧
