### ISSUE TITLE
Tooltip的visible在TS里的定义强制boolean，不允许传undefined

### ISSUE THREAD

**Issue by LaxusT** [ant-design/ant-design#36272]
### What problem does this feature solve?

Tooltip文档描述visible的是boolean类型，不过在业务代码编写中，发现个小问题，就是传了undefined也不会报错，这是因为rc-tooltip里定义的是visible?: boolean，所以ts编译不会报错。但其实rc的hook useMergedState会默认认为undefined是空值，所以即使传了undefined，也不会影响组件的默认行为。使用者有时候会以为undefined是false的意思，认为组件会受控，但其实传过去后并没有转化类型。我的想法是在该组件的Props定义强制要求传boolean，这样规避了一些问题，可在编译中就发现。

#### 在AbstractTooltipProps类型定义覆盖一下RcTooltipProps就好了，这样使用者只能传boolean类型
```
export interface AbstractTooltipProps extends Partial<Omit<RcTooltipProps, 'children'>> {
  visible: boolean; // 强制要求使用者传递boolean类型
  style?: React.CSSProperties;
  className?: string;
  color?: LiteralUnion<PresetColorType, string>;
  placement?: TooltipPlacement;
  builtinPlacements?: typeof Placements;
  openClassName?: string;
  arrowPointAtCenter?: boolean;
  autoAdjustOverflow?: boolean | AdjustOverflow;
  getPopupContainer?: (triggerNode: HTMLElement) => HTMLElement;
  children?: React.ReactNode;
}
```

**Comment by LaxusT** [comment]
如果可以的话，我会按照流程提PR

**Comment by afc163** [comment]
visible 不是必选项，可以忽略。

**Comment by LaxusT** [comment]
> visible 不是必选项，可以忽略。

明白了
