### ISSUE TITLE
popover color改变了inner的颜色，但是箭头没有改变

### ISSUE THREAD

**Issue by ladyruo** [ant-design/ant-design#36270]
### Reproduction link

[https://ant.design/components/tooltip-cn/](https://ant.design/components/tooltip-cn/)

### Steps to reproduce

  <Popover
          color={'#353945'}
          visible={true}
          overlayClassName="sell-listings-popover"
          content={
            <div className="margin-top-10">
            some text
              
            </div>
          }
          title={null}
          trigger="hover"
          placement="bottomRight"
        >
test text
        </Popover>

### What is expected?

箭头颜色改变成#353945

### What is actually happening?

箭头颜色是white

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 17.0.1 |
| System | mac  |
| Browser | 谷歌102.0.5005.115 |

<img width="346" alt="image" src="https://user-images.githubusercontent.com/28803604/176103441-6c714b67-6358-4d65-b5f6-40098ad148b8.png">

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/36241
