### ISSUE TITLE
在日历组件里面写输入框，键盘事件不会生效

### ISSUE THREAD

**Issue by MaZhengA** [ant-design/ant-design#36274]
### Reproduction link

[https://codepen.io/mazhengAA/pen/MWVWKmR?editors=001](https://codepen.io/mazhengAA/pen/MWVWKmR?editors=001)

### Steps to reproduce

1. 在任意输入框写一些数字
2. 在输入框内移动光标
3. 会发现不生效，会移动到别的日期上边

### What is expected?

期望光标可以在输入框内移动

### What is actually happening?

实际上移动到了日历的日期上

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | ^16.14.0 |
| System | mac |
| Browser | 103.0.5060.53（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://codepen.io/afc163-1472555193/pen/wvmvMbR?editors=001

```
onKeyDown={e => e.stopPropagation()}
```
