### ISSUE TITLE
对于 v5 的动态主题开放样式变量我有一些需求，我可以贡献这部分的代码吗？

### ISSUE THREAD

**Issue by kev1nzh37** [ant-design/ant-design#36284]
### What problem does this feature solve?

我需要一个很简单的 Antd App, 可以提供给设计人员实时修改协定最终的 框架主题样式。我可以提交这部分的代码来迭代吗？

### What does the proposed API look like?

比如 @border-width-base, @text-color 之类的变量，现在只能注入一些颜色变量。

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/34087
