### ISSUE TITLE
Dynamic theme not working via ConfigProvider during build time

### ISSUE THREAD

**Issue by priyankcommits** [ant-design/ant-design#36281]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/create-react-app-forked-m0q0ez?file=/src/App.js)

### Steps to reproduce

This happens only during build, it works on dev server. 

    "@ant-design/colors": "^6.0.0",
    "@ant-design/icons": "^4.6.4",
    "@craco/craco": "^6.2.0",
    "@googlemaps/js-api-loader": "^1.12.3",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "antd": "4.21.0",
    "axios": "^0.21.3",
    "craco-less": "^1.20.0",
    "dotenv": "^10.0.0",
    "esm": "^3.2.25",
    "event-source-polyfill": "^1.0.25",
    "exceljs": "^4.3.0",
    "file-saver": "^2.0.5",
    "https": "^1.0.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "react": "^17.0.2",
    "react-circular-progressbar": "^2.0.4",
    "react-color": "^2.19.3",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.3.0",
    "react-scripts": "4.0.3",
    "recharts": "^2.1.6",
    "serve": "^12.0.0",
    "sockjs-client": "^1.1.4",
    "stompjs": "^2.3.3",
    "sunburst-chart": "^1.15.2",
    "web-vitals": "^1.0.1"

    "dev": "craco start -v",
    "build": "craco build",

### What is expected?

Primary theme should change after static assets are built during build process. Working on dev server.

### What is actually happening?

Primary theme is not changing after static assets are built during build process.

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17.0.2 |
| System | mac os |
| Browser | chrome latest |

---
yarn: 1.22.19
node: 16.15.1

**Comment by afc163** [comment]
Don't import `antd/dist/antd.less` if you are using `antd/dist/antd.variable.min.css`, it would be conflicted.
