### ISSUE TITLE
Slider handle 支持自定义样式或传入 Icon

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design#36289]
### What problem does this feature solve?

在不同业务场景下支持自定义Slider手柄样式，目前样式太过单一

### What does the proposed API look like?

customHandle: ReactNode

**Comment by afc163** [comment]
There is `handleStyle`.

**Comment by DaJianWu** [comment]
> There is `handleStyle`.

现在不支持自定义吧？

**Comment by afc163** [comment]
https://github.com/react-component/slider/#common-api

**Comment by DaJianWu** [comment]
> https://github.com/react-component/slider/#common-api

antd里面会考虑支持一下吗

**Comment by afc163** [comment]
antd 里支持的，只是文档没体现，你可以试试。

**Comment by DaJianWu** [comment]
> antd 里支持的，只是文档没体现，你可以试试。

ok

**Comment by DaJianWu** [comment]
> antd 里支持的，只是文档没体现，你可以试试。

顺便问一下 是不是 rc 支持的 api antd 都可以透传
