### ISSUE TITLE
Input 的 autoFocus 屬性在 Drawer 中失效

### ISSUE THREAD

**Issue by YaoKaiPeng** [ant-design/ant-design#36287]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-chu-chou-ti-antd-4-21-4-forked-44u9ye?file=/demo.js)

### Steps to reproduce

打開 Drawer 側邊框，裡面的input設置了autoFocus，但無法生效

### What is expected?

Input autoFocus 生效

### What is actually happening?

Input autoFocus 失效

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-chu-chou-ti-antd-4-21-4-forked-nnbw80?file=/demo.js

```jsx
<Drawer autoFocus={false}>
```

**Comment by xinghul** [comment]
@afc163 the solution works for `v4.21.4`, however, after upgrading to `v4.24.3`, it stopped working.
