### ISSUE TITLE
Tooltip and Popover do not work on disabled buttons in Chrome-based browsers

### ISSUE THREAD

**Issue by mathieucaroff** [ant-design/ant-design#36283]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-on-disabled-button-bug-antd-4-20-5-0r9oxq)

### Steps to reproduce

Use a **disabled** button inside as child of a Tooltip or Popover.
Hover over the button with the mouse.

### What is expected?

The Tooltip box or Popover box should appear.

### What is actually happening?

Most of the time, nothing happens.

| Environment | Info |
| --- | --- |
| antd | 4.15.1 |
| React | 17.0.2 |
| System | Windows 10 and MacOS 12.2.1 |
| Browser | Chrome 103.0 as well as Edge and Safari |

---

This bug does not affect Firefox. This bug shows in Storybook.

Similar issues:
- https://github.com/ant-design/ant-design/issues/30191
- https://github.com/ant-design/ant-design/issues/9581

The solution proposed in issue 30191 of wrapping the button in a div does not work.

**Comment by Mzhang1994** [comment]
> I'm hardly able to reproduce this issue consistently, even in the Storybook, I'm not sure what's going on :T

I think it will happen when you move mouse from a tooltipless one to a tooltip one directly. No matter it is a disabled one or not.

**Comment by afc163** [comment]
Resolved this issue in https://github.com/ant-design/ant-design/blob/a2c7ea4ab6356865c5dc56c6a309dd8fac9ecdd8/components/tooltip/index.tsx#L83-L86 , cannot reproduce in your codesandbox.

<img width="580" alt="图片" src="https://user-images.githubusercontent.com/507615/176335453-e6ccc01f-1d53-46aa-915b-2bbbeeb01b2f.png">

**Comment by shamseerahammedm** [comment]
+1  getting same issue  on ```"antd": "^5.1.5",```, popover not coming when wrapped in disabled buttons 

 ```
 <Popover content={<div>Reject</div>} placement="bottom">
  <Button 
    onClick={() => somefunction(rowSelectionModel)}
    disabled={true}
  >
    Reject
  </Button>
</Popover>

**Comment by sawhil** [comment]
> +1 getting same issue on `"antd": "^5.1.5",`, popover not coming when wrapped in disabled buttons
> 
> ```
> <Popover content={<div>Reject</div>} placement="bottom">
>  <Button 
>    onClick={() => somefunction(rowSelectionModel)}
>    disabled={true}
>  >
>    Reject
>  </Button>
> </Popover>
> ```

Wrap the button in a div. It should work. Hover events are disabled when the button is disabled.
