### ISSUE TITLE
Upload Error状态删除时有蓝色Icon闪过

### ISSUE THREAD

**Issue by HkOri** [ant-design/ant-design#36286]
### Reproduction link

[https://ant.design/components/upload-cn/#components-upload-demo-picture-card](https://ant.design/components/upload-cn/#components-upload-demo-picture-card)

### Steps to reproduce

1、这是官网文档中照片墙的例子
2、删除那张代表Error状态的图片
3、在删除瞬间可以看到有个蓝色的图片ICON闪过

### What is expected?

没有蓝色的图片ICON闪过

### What is actually happening?

有蓝色的图片ICON闪过

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17.0.2 |
| System | macOS Catalina 10.15.7 |
| Browser | Chrome 103.0.5060.53 |

**Comment by afc163** [comment]
Reverted https://github.com/ant-design/ant-design/pull/36682
