### ISSUE TITLE
Npm下载的Antd 2.1.0 中TreeSelect 树搜索框样式缺失

### ISSUE THREAD

**Issue by lorrylockie** [ant-design/ant-design#3629]
#### 发生问题的环境是： 无需环境

- antd 版本: 2.1.0
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？请提供尽可能详细的重现步骤。

在Ant.design官网查看了TreeSelect这个组件，代码演示中的第一个例子，使用了树搜索功能，搜索框的样式如下

```

.ant-select-tree-dropdown .ant-select-dropdown-search .ant-select-search__field {
    padding: 4px 7px;
    width: 100%;
    box-sizing: border-box;
    border: 1px solid #d9d9d9;
    border-radius: 4px;
    outline: none;
}

```

在本地使用npm install antd  ，版本仍然为2.1.0

但是无法在node_modules antd的dist目录中的antd.css中找到对应的css样式，从源码less中也无法搜索到

#### 您期待的结果是:

npm中antd的2.1.0稳定版需要拥有搜索框这个默认样式

#### 实际上的结果是:

没有

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/3520
