### ISSUE TITLE
Modal Title 样式问题

### ISSUE THREAD

**Issue by aix3** [ant-design/ant-design#36293]
### Reproduction link

[https://ant.design/components/modal-cn/#header](https://ant.design/components/modal-cn/#header)

### Steps to reproduce

1. 点击 Open Modal 按钮
2. 出现 Modal 对话框

### What is expected?

默认的 Modal Title 右侧关闭按钮在容器里面是上下居中的。

### What is actually happening?

默认的 Modal Title 右侧关闭按钮在容器里面是上下不居中的。

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 18.1.0 |
| System | MacOS |
| Browser | Chrome |

---
Modal Title 容器的默认高度是 54px（22px   2*16px），底边框 1px。但是默认的 Modal Title 右侧关闭按钮的高度是 56px，这样看的话，关闭按钮不是上下居中的。

如图：
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/17353286/176350346-e514f8e4-4909-497f-b0b4-9500db6e6bb1.png">
<img width="187" alt="image" src="https://user-images.githubusercontent.com/17353286/176350398-f4fc316c-cdae-478d-9a97-e4686220c1a6.png">
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/17353286/176350441-40453802-e97e-43db-8db9-2ccf1dee8a29.png">

应该可以将 Modal Title 的行高改成 24px 或者把关闭按钮的高度改成 54px，这样就都居中了。

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/17353286/176350518-b425f5c2-ffbd-496d-a42c-9206d25d160c.png">

**Comment by MadCcc** [comment]
这个问题在 next 应该已经解了，v4 也可以搞一下
