### ISSUE TITLE
[Site Feature Request] Can we make the `copy code` button only copy the JSX code ?

### ISSUE THREAD

**Issue by shezhangzhang** [ant-design/ant-design#36304]
### What problem does this feature solve?

As far as I am concerned, most of time I only want to copy the JSX code but not the whole demo code there. (include the import xxx .etc.) So I always select the JSX code and copy which is not convenient.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/26793777/176407091-cd4c3ddf-f052-4d89-bbbe-95d4a1db9cd0.png">

### What does the proposed API look like?

Making the copy code button only copy JSX code on antd site. (or add a switch button maybe?)

**Comment by afc163** [comment]
Sorry, finding the exact code is difficult to implement.

**Comment by shezhangzhang** [comment]
> Sorry, finding the exact code is difficult to implement.

👌forget about it.😆
