### ISSUE TITLE
Popover组件在嵌套Icon的时候，样式错误

### ISSUE THREAD

**Issue by Tzng** [ant-design/ant-design#36316]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/popoveryang-shi-cuo-wu-z6o8ox?file=/demo.js)

### Steps to reproduce

    <Popover
      content={content}
      title="Title"
      trigger="click"
      placement="bottomLeft"
    >
      <TagsOutlined
        style={{ fontSize: 16, color: "#aaabac" }}
      />
    </Popover>

### What is expected?

剪头指向图标中间

### What is actually happening?

偏了

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17.0.2 |
| System | win11 |
| Browser | edge |

**Comment by MadCcc** [comment]
`arrowPointAtCenter`?

**Comment by afc163** [comment]
arrowPointAtCenter
