### ISSUE TITLE
antd 1.x表格组件，固定某些列，屏幕分辨率大的情况下，出现问题

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design#3631]
#### 发生问题的环境是：

- antd 版本: antd 1.11.2
- 操作系统及其版本: macOS\Windows 10\Windows 7 
- 浏览器及其版本: Chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

固定了scroll值，固定了所有的列width

#### 您期待的结果是:

不同分辨率下，显示的情况不理想，出现固定列重列的情况
![image](https://cloud.githubusercontent.com/assets/4178729/19793356/d5ea07fa-9cfe-11e6-8a42-6d2c1aa741f0.png)

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/4178729/19793351/c8fb9cd4-9cfe-11e6-959c-dacb516dba8b.png)

**Comment by afc163** [comment]
scroll.x 的值要大于表格的宽度。

**Comment by WhatAKitty** [comment]
试过了。。也不行。。。还是会出现该问题。

**Comment by afc163** [comment]
给个重现方便排查。

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by WhatAKitty** [comment]
ok，稍等

**Comment by WhatAKitty** [comment]
@afc163 http://codepen.io/anon/pen/Gjarkj?editors=0011 已经保存了，不过我这边没法运行，不知道为啥，代码基本上跟这个demo类似

**Comment by WhatAKitty** [comment]
bug解决了，不能设置可滚动列的width。
