### ISSUE TITLE
为Input.TextArea设置allowClear属性之后，当在TextArea内输入内容很多时导致滚动条出现，此时clear图标会和滚动条重叠

### ISSUE THREAD

**Issue by cw1997** [ant-design/ant-design#36311]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-f0z7kk)

### Steps to reproduce

为Input.TextArea设置allowClear属性之后，当在TextArea内输入内容很多时导致滚动条出现，此时clear图标会和滚动条重叠
![image](https://user-images.githubusercontent.com/11588555/176554602-b576ee79-5277-4c9d-bf0b-c2368240c7d7.png)

### What is expected?

期望滚动条和clear图标不重叠，并且他们之间有一定边距以保持美观

### What is actually happening?

为Input.TextArea设置allowClear属性之后，当滚动条出现时，clear图标会和滚动条重叠

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 18.2.0 |
| System | Windows 10 21H2 |
| Browser | Chrome Version 102.0.5005.115 (Official Build) (64-bit) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32869#issuecomment-976329038
