### ISSUE TITLE
DatePicker日期选择框 支持多选

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [ant-design/ant-design#36314]
### Reproduction link

[https://ant.design/components/date-picker-cn/#](https://ant.design/components/date-picker-cn/#)

### Steps to reproduce

无

### What is expected?

比如， 我想选出这个月哪些天， 做了某事， 这时候 在弹出日期选择框的时候， 需要 能对 【天】  进行多选， 但是目前 antd不支持

### What is actually happening?

只能单选， 或者选连续的范围， 不支持 随意挑选 多个 天

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/components/date-picker-cn/?theme=dark#components-date-picker-demo-range-picker

**Comment by hu-tu-yi-shi** [comment]
你好，我没找到 多选

**Comment by hu-tu-yi-shi** [comment]
类似这种  https://semi.design/zh-CN/input/datepicker#%E5%A4%9A%E4%B8%AA%E6%97%A5%E6%9C%9F%E9%80%89%E6%8B%A9

**Comment by MadCcc** [comment]
暂时不支持这种多选

**Comment by afc163** [comment]
Duplicate of #4447

**Comment by Codetotos** [comment]
你好，问题解决了吗？最后采用的什么方案？

**Comment by hu-tu-yi-shi** [comment]
@Codetotos  后来我改了需求， 如果你一定要这个功能，可以自己做一个， 或者换框架 https://semi.design/zh-CN/input/datepicker#%E5%A4%9A%E4%B8%AA%E6%97%A5%E6%9C%9F%E9%80%89%E6%8B%A9

**Comment by Codetotos** [comment]
@hu-tu-yi-shi 好的，谢谢
