### ISSUE TITLE
Progress text position

### ISSUE THREAD

**Issue by zhou-fuhao** [ant-design/ant-design#36324]
### What problem does this feature solve?

目前插件只能满足用户在进度条外侧显示数值，不支持数值显示在进度条内

### What does the proposed API look like?

数值显示在进度条内左对齐/居中对齐/右侧对齐

**Comment by xrkffgg** [comment]
emm 纯改 css 是可以实现的。
默认的 progress 的高度其实不适合放字体的

**Comment by xccjk** [comment]
默认progress高度确实不合适放字体，同时因为颜色可以动态设置，因此需要支持在进度条内展示文字时：

- `progress`类型为`line`时才支持设置
- 字体的大小、颜色、位置需要支持设置
- 在未设置`strokeWidth `属性或者`strokeWidth `值小于12px时，不允许设置字体展示在进度条上

**Comment by berber1016** [comment]
Can i work on this?

**Comment by sropansite** [comment]
我是一个设计师，想问可否实现数字在进度条下方居中？比如这样：
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/4220882/224878487-2d523197-f703-44ab-b286-868fc0a47e09.png">

**Comment by afc163** [comment]
@sropansite  可以，不过需要自行实现，组件库默认没有提供这个样式。

**Comment by sropansite** [comment]
> @sropansite 可以，不过需要自行实现，组件库默认没有提供这个样式。

谢谢！希望antd的库中可以早日提供这个样式，因为在我们产品中出现的场景还挺多的，谢谢！

**Comment by afc163** [comment]
https://semantic-ui.com/modules/progress.html 有这个样式。

**Comment by crazyair** [comment]
![image](https://github.com/ant-design/ant-design/assets/7971419/bb4ffdbd-76db-4e69-9c68-f61221c81461)
内联显示内容，还需要考虑 0 的值的场景

**Comment by LonelySnowman** [comment]
我有意向完成这个 feature，正在跟进。

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/48157
