### ISSUE TITLE
表格body添加minHeight属性

### ISSUE THREAD

**Issue by heningyuan6256** [ant-design/ant-design#36332]
### What problem does this feature solve?

想把表格横向滚动条控制在页面的底部，表格能够撑满页面，但外部又不出现滚动条，我想通过js去计算最小高度

### What does the proposed API look like?

minHeight={number | string}

**Comment by afc163** [comment]
> 想把表格横向滚动条控制在页面的底部，表格能够撑满页面

看看是不是需要的 https://ant.design/components/table-cn/#components-table-demo-sticky

**Comment by wangchao18654941093** [comment]
表格body添加minHeight属性的意思 不论当前表格数据多少，table内容的高度都是固定的

**Comment by wangchao18654941093** [comment]
![image](https://user-images.githubusercontent.com/107595890/188103882-bddb3785-beb9-4513-8ae0-57fe8d3b485d.png)
 比如scroll:{y: 500}, 有时候我们是想让table 的高度固定是500px，但实际Table给content加了个max-height:500px， 这导致了一个问题是，当表格里的内容是4条时，就会出现上图所示， 实际的table高度很小，分页也移动上去了，  我的页面布局全乱了

**Comment by harry118** [comment]
@afc163 @heningyuan6256 解决了吗？如果使用3.x版本的该怎么写呢？
