### ISSUE TITLE
表格只有一列时，该列固定，并且给scroll.x设置值，表格出现横向滚动条，并且出现右侧出现空白

### ISSUE THREAD

**Issue by dashaowang** [ant-design/ant-design#36330]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-bian-kuang-antd-4-21-4-forked-x0nshb?file=/demo.js)

### Steps to reproduce

表头只有一列，并且固定，给scroll.x设置值

### What is expected?

宽度不够时不出现滚动条

### What is actually happening?

出现滚动条

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17.0.2 |
| System | win10 |
| Browser | Microsoft Edge 99.0.1150.46 (正式版本) (64 位) |

**Comment by BingGeGeWu** [comment]
尽快解决一下这个问题吧，太丑了

**Comment by afc163** [comment]
只有一列为啥要开启 `scroll={{ x: true }}` 呢？

**Comment by dashaowang** [comment]
> 只有一列为啥要开启 `scroll={{ x: true }}` 呢？

表格的列宽是可调整的

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/table/pull/847
