### ISSUE TITLE
TreeSelect 在 npm 的antd@2.1.0 版本中，树搜索输入框样式缺失

### ISSUE THREAD

**Issue by lorrylockie** [ant-design/ant-design#3633]
#### 发生问题的环境是：

NPM

- antd 版本: 2.1.0
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？请提供尽可能详细的重现步骤。

npm 上antd的css文件(dist/antd.css) 和 官网上的最新版本css不一致

具体为：在NPM 的antd@2.1.0版本中 TreeSelect 下来搜索框(官网第一个例子） 没有样式

```
.ant-select-tree-dropdown .ant-select-dropdown-search .ant-select-search__field {
    padding: 4px 7px;
    width: 100%;
    box-sizing: border-box;
    border: 1px solid #d9d9d9;
    border-radius: 4px;
    outline: none;
}
```

#### 您期待的结果是:

1. Antd 2.1.0 npm 版本中， TreeSelect 默认拥有搜索框样式，而不是缺失

#### 实际上的结果是:

npm antd2.1.0 版本中缺失样式

#### 可重现的在线演示

npm install antd 2.1.0版本，打开 antd/dist/antd.css 文件搜索

**Comment by afc163** [comment]
???

duplicate https://github.com/ant-design/ant-design/issues/3629
