### ISSUE TITLE
折叠面板 提供 折叠图标color,折叠图标size,折叠图标旋转角度，可设置固定内容这几个属性

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#36348]
### What problem does this feature solve?

折叠面板 提供 折叠图标color,折叠图标size,折叠图标旋转角度，可设置固定内容这几个属性

### What does the proposed API look like?

expandIconSize
expandIconColor
expandIconRolate

**Comment by izhouteng** [comment]
你说的这些图标本身都可以支持设置。

无意义，关闭吧。

**Comment by afc163** [comment]
expandIcon 支持一个 ReactNode。
