### ISSUE TITLE
日期选择组件在移动端不能适配

### ISSUE THREAD

**Issue by j-kings-huang** [ant-design/ant-design#36341]
### What problem does this feature solve?

有一些需求使用到日期。移动端在页面之外了。交互显得很不友好

### What does the proposed API look like?

希望可以有兼容移动端的样式。或者提供响应的api

**Comment by izhouteng** [comment]
@j-kings-huang 来个PR改进下？

**Comment by afc163** [comment]
Duplicate of #26758

**Comment by yuenzp** [comment]
Any solutions?
