### ISSUE TITLE
DatePicker works differently when clicked tab vs select date manually

### ISSUE THREAD

**Issue by gmoniava** [ant-design/ant-design#36342]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/morning-http-kx9ze9?file=/src/App.js)

### Steps to reproduce

Scenario 1
==========
1. Type manually 2022-01-01 in the input
2. Click with mouse the suggested day "1"
3. You will see selected date will be 2021-12-31

Now, also do:

Scenario 2
==========

1. Type manually 2022-01-01 in the input
2. Instead of clicking with mouse on date, press TAB key twice
3. You will see selected date will be 2022-01-01

### What is expected?

The result in step 3 should be the same, in both scenarios.

### What is actually happening?

Step 3 is different for above two scenarios

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17 |
| System | Ubuntu |
| Browser | Chrome 101 |

**Comment by MadCcc** [comment]
Seems problem here is:
```js
m.utc().set({
  hour: 0,
  minute: 0,
  second: 0
});
```
Pressing tab twice only close the panel, `onChange` was not triggered. Please check your code.

**Comment by gmoniava** [comment]
@MadCcc click tab twice. Put log inside onChange, you will see it is called.

**Comment by gmoniava** [comment]
@afc163 can you please check? It was wrongly closed. `onChange` is called in both cases.
