### ISSUE TITLE
Transfer穿梭框组件，List组件 大数据量情况下支持虚拟滚动

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#36349]
### What problem does this feature solve?

Transfer穿梭框组件，List组件 大数据量情况下支持虚拟滚动

### What does the proposed API look like?

提供virtual属性 开闭虚拟滚动

**Comment by izhouteng** [comment]
List有支持虚拟滚动的例子。
Transfer虚拟滚动意义不大，你是有上千条数据要选么......？

**Comment by afc163** [comment]
Duplicate of #9703

**Comment by manwuyu** [comment]
@izhouteng  我有  
![image](https://user-images.githubusercontent.com/6800546/199454711-078a7af3-27d7-49e8-9e40-05fd6ea42a00.png)
