### ISSUE TITLE
导航栏位于左侧时与其他组件的布局问题

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design#3634]
导航栏设置为垂直、左侧、dark主题，右边放了个表格组件，布局不知道怎么回事，设置了宽度，导航栏任然会占有右侧部分
[http://codepen.io/RifeWang/pen/yaWojo](http://codepen.io/RifeWang/pen/yaWojo)

**Comment by afc163** [comment]
和 antd 没关系，业务系统样式问题建议自行解决。
