### ISSUE TITLE
Cascader只有一个子选项的时候无法取到子选项的值

### ISSUE THREAD

**Issue by fybchristasker** [ant-design/ant-design#36355]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-antd-4-21-5-forked-7p2cw7)

### Steps to reproduce

点击Light后的Number0

### What is expected?

选择了Number0

### What is actually happening?

选择了Light

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="324" alt="图片" src="https://user-images.githubusercontent.com/507615/177075144-fc46256c-f798-43f5-b43f-c335321547df.png">

没看出来有啥问题，这不是合理的么？

**Comment by fybchristasker** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/46596982/177075085-fa239301-ca88-4abb-8c54-6a8f5d1c8293.png">

**Comment by fybchristasker** [comment]
@afc163 sorry，忘了保存了，复现链接是这个
https://codesandbox.io/s/duo-xuan-antd-4-21-5-forked-7p2cw7

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/components/cascader-cn/#components-cascader-demo-showCheckedStrategy
用 `showCheckedStrategy`

**Comment by fybchristasker** [comment]
@MadCcc okok
