### ISSUE TITLE
Card tab sizing not working as expected

### ISSUE THREAD

**Issue by ryannealmes** [ant-design/ant-design#3635]
It seems [Card Tabs](https://ant.design/components/tabs/#components-tabs-demo-card) do not support the `small` size setting. White space is created between the tabs and the horizontal line that they sit on.

See [example](http://codepen.io/anon/pen/WGBkjr?editors=001) to understand what I mean.

I am not sure if this is just not supported, but I thought I would log it since I can't see anything in the documentation.

**Comment by benjycui** [comment]
Yep, `Tabs[type="card"]` doesn't support `size="small"`.
