### ISSUE TITLE
treeselect: key不同value相当的时候报错有同一个key

### ISSUE THREAD

**Issue by DBSDs** [ant-design/ant-design#36354]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-21-0-forked-bxftlw?file=/package.json:189-197)

### Steps to reproduce

treeselect: key不同value相当的时候报错有同一个key

### What is expected?

key作为react元素的key值必须不同，value可以相同

### What is actually happening?

key作为react元素的key和value必须相同

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | ^16.14.0 |
| System | macOS Monterey 12.1  |
| Browser | 103.0.5060.53（正式版本） (x86_64) |

---
业务场景：角色下拉选择用户，用户的value值相同。

**Comment by MadCcc** [comment]
TreeSelect 需要 value 在整个树中唯一
