### ISSUE TITLE
ant design pro V5版本，为什么在ie浏览器里打不开

### ISSUE THREAD

**Issue by littleGitYxr** [ant-design/ant-design#36369]
### Reproduction link

[https://preview.pro.ant.design/](https://preview.pro.ant.design/)

### Steps to reproduce

ie浏览器打不开

### What is expected?

兼容ie

### What is actually happening?

兼容ie

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.0 |
| System | windows |
| Browser | ie |

**Comment by afc163** [comment]
要看看报错信息具体是啥？https://github.com/ant-design/ant-design-pro/blob/89485358547a40a623e2f2c3ba1f2e096bba8e75/config/config.ts#L18-L25
