### ISSUE TITLE
Vite compatibility 

### ISSUE THREAD

**Issue by quantuminformation** [ant-design/ant-design#36366]
### What problem does this feature solve?

Allows migration to vite from CRA

### What does the proposed API look like?

stops vite build breaking via: https://stackoverflow.com/questions/72854489/vite-and-antd-error-vitecss-inline-javascript-is-not-enabled-is-it-set-in

```
✓ 3816 modules transformed.
[vite:css] Inline JavaScript is not enabled. Is it set in your options?
file: /Users/nikos/WebstormProjects/web/node_modules/.pnpm/antd@4.21.4_react-dom@17.0.2+react@17.0.2/node_modules/antd/es/tag/style/index.less:110:0
error during build:
Error: Inline JavaScript is not enabled. Is it set in your options?
    at less (/Users/nikos/WebstormProjects/web/node_modules/.pnpm/vite@2.9.13_less@4.1.3+sass@1.53.0/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38106:33)
```

**Comment by Dunqing** [comment]
refer to https://github.com/Dunqing/vite-ant-design-pro/blob/c85886cd216d6e61266cc108ba3b2b7d8a20949f/playground/vite.config.ts#L19-L26

**Comment by Dunqing** [comment]
`antd@4` uses `less`, so you must enable the less configuration required by `antd`

**Comment by afc163** [comment]
You can try `import 'antd/dist/antd.css'` in vite project.

**Comment by quantuminformation** [comment]
thanks all
