### ISSUE TITLE
表格组件onRow中设置的style样式，对固定列不生效。

### ISSUE THREAD

**Issue by ZTT820** [ant-design/ant-design#36363]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-lie-antd-4-16-5-forked-msvws1?file=/index.js)

### Steps to reproduce

在Table组件onRow中添加了style属性，当字段是fixed: "left"或者 fixed: "right", 该字段style中的backgroundColor颜色不是onRow中的颜色。

### What is expected?

以onRow中添加的style属性设置属性为准

### What is actually happening?

默认的 #fff

| Environment | Info |
| --- | --- |
| antd | 4.16.6 |
| React | 16.14.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
看了一下是生效的，只是固定列的单元格有个默认的白色背景，如果需要改动，你可以试试 onCell。

<img width="785" alt="图片" src="https://user-images.githubusercontent.com/507615/177241687-da6f50b4-9612-4964-a258-85e89c113347.png">
