### ISSUE TITLE
AutoComplete support TreeSelect

### ISSUE THREAD

**Issue by MrHeer** [ant-design/ant-design#36360]
### What problem does this feature solve?

`AutoComplete` now only supports normal `Select`, hope to support `TreeSelect`

### What does the proposed API look like?

```tsx
<AutoComplete treeData={treeData} />
```

**Comment by izhouteng** [comment]
无意义，那你直接用`TreeSelect`不就好了，它同样支持搜索。

**Comment by MrHeer** [comment]
@izhouteng  `TreeSelect` 是不支持输入任意字符串的吧，按照你的说法 `Select` 也是支持搜索的，那么是不是现在的 `AutoComplete` 也没有意义？

**Comment by izhouteng** [comment]
`AutoComplete`是辅助`Input`输入的，和`Select `其实没啥关系....`Select`是给用户多选一的。

**Comment by afc163** [comment]
AutoComplete 是自动完成，下拉列表是辅助输入。树形选择器重点是选择，提供树形数据的枚举值，两者的定位还是有差异，不建议揉合在一起。

**Comment by MrHeer** [comment]
其实就是希望自动完成的辅助输入可以是树形结构。现在的辅助输入只能是列表形式

**Comment by afc163** [comment]
如果要做简单的一级分类分组，可以参考 https://ant.design/components/auto-complete/#components-auto-complete-demo-certain-category

**Comment by MrHeer** [comment]
确实有需要用树形结构来辅助输入的需求情况，不是简单的一级分类

**Comment by afc163** [comment]
@MrHeer 能还原一下业务需求么？

**Comment by MrHeer** [comment]
@afc163 
- 我们有一个标准数据，它是树形结构。
- 有一个字段，他可以手动输入，在输入的时候过滤标准数据生成一个过滤后的树形结构，用户可以直接选择树上的节点来辅助输入。当然也可以直接手动输入任意的文字。

**Comment by afc163** [comment]
你这不是原始业务需求，这已经在描述实现方式了。

**Comment by MrHeer** [comment]
我不是太清楚原始业务需求是什么。产品就是需求自动完成下拉选项保持树形结构的视图，便于选择。因为数据可能是这个样子的
```ts
  A
  --C
  B
  --C
```
我输入C，他需要知道应该选择哪一个C，只能通过树形结构来区分吧

**Comment by MrHeer** [comment]
他除了希望能够自动完成，如果他使用下拉列表选择，他还希望知道用户具体选择的哪一个节点
