### ISSUE TITLE
s.Form.useWatch is not a function

### ISSUE THREAD

**Issue by YH-82** [ant-design/ant-design#36365]
### Reproduction link

[https://ant.design/components/form-cn/#components-form-demo-useWatch](https://ant.design/components/form-cn/#components-form-demo-useWatch)

### Steps to reproduce

使用了4.20.0新增的属性useWatch，我本地antd的版本是4.20.2，报错"s.Form.useWatch is not a function"，并且浏览器打印Form，里面并没有useWatch。

### What is expected?

不报错

### What is actually happening?

报错"s.Form.useWatch is not a function"

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 16.14.28 |
| System | mac |
| Browser | 87.0.4280.88 |

**Comment by calvinlee2022** [comment]
maybe is a new Issue that it can not find this function in higher version
