### ISSUE TITLE
父组件 useEffect回调里, 获取不到 Input.TextArea 的ref

### ISSUE THREAD

**Issue by Valar103769** [ant-design/ant-design#36368]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/wen-ben-yu-antd-4-21-5-forked-d1y99l?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

在 codepen 里无法复现,   需要放到本地, 也可能是modal的原因

```jsx
funtion MyCop = () => {
  const textAreaRef = useRef(null)
 useEffect(() => {
    console.log('xxx', textAreaRef.current)

  }, [activeKey])
return (
<Input.TextArea
            ref={textAreaRef}
            showCount
            autoSize={{ minRows: 3 }}
          />
)
}
```

### What is expected?

textAreaRef.current 是有值的

### What is actually happening?

textAreaRef.current = null

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18 |
| System | mac |
| Browser | 最新chrome |

**Comment by afc163** [comment]
你需要 `modalProps={{ forceRender: true }}` 提前渲染出弹层的内容。
