### ISSUE TITLE
使用Layout组件[顶部-侧边布局-通栏]布局样例代码时，多次快速切换header的nav，会报错Maximum update depth exceeded

### ISSUE THREAD

**Issue by un-defined-name** [ant-design/ant-design#36361]
### Reproduction link

[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce

在官方文档的codesandbox中调整至对应版本代码，多次快速在header中的nav中鼠标点击切换即可复现

### What is expected?

期望正常切换

### What is actually happening?

多次切换后会报错Maximum update depth exceeded

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18.2.0 |
| System | windows10 |
| Browser | Edge最新版 |

**Comment by jianhuagao** [comment]
https://codesandbox.io/s/shang-zhong-xia-bu-ju-antd-4-21-5-forked-bb8itx?file=/index.js
同样的问题 多点几次就直接会崩溃 这个问题在我项目里更加严重 非常容易触发 @afc163 
![Snipaste_2022-07-05_08-50-57](https://user-images.githubusercontent.com/39371828/177229596-5e0ec423-7eb6-4fa0-9c20-cc580d24e82d.jpg)

**Comment by dujiajun** [comment]
我也遇到了类似的问题。在手机浏览器，或者F12切换设备仿真，再点Header中的Menu菜单就会报这个错。

**Comment by himadrinath** [comment]
i also seeing the similar issue in device emulation

**Comment by 0529bill** [comment]
I am seeing the same issue as well!

**Comment by bcseda** [comment]
Also seeing in desktop Chrome browsers with DevTools Device Mode

**Comment by 1123612483** [comment]
我这边没有用antd的Layout组件，只是用Menu，操作几下就会报错。

**Comment by liyu233** [comment]
> 我也遇到了类似的问题。在手机浏览器，或者F12切换设备仿真，再点Header中的Menu菜单就会报这个错。



> 我也遇到了类似的问题。在手机浏览器，或者F12切换设备仿真，再点Header中的Menu菜单就会报这个错。

嘿解决了吗？！我也遇到了！

**Comment by foriLLL** [comment]
> 我也遇到了类似的问题。在手机浏览器，或者F12切换设备仿真，再点Header中的Menu菜单就会报这个错。

我也遇到了同样的问题，PC中没有发现问题，但在设备仿真以及移动端使用中出现同样的错误

**Comment by nicemango** [comment]
这个问题有啥标准的解决方案吗  升级React18后同样遇到

**Comment by foriLLL** [comment]
> 这个问题有啥标准的解决方案吗 升级React18后同样遇到

我目前采用的解决方案就是React降级。。

**Comment by jianhuagao** [comment]
> 这个问题有啥标准的解决方案吗 升级React18后同样遇到

如果是用在顶部当nav的话 我是用Tab组件替换掉了Menu

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/overflow/pull/24
