### ISSUE TITLE
tab页增加到一定数量时会产生偏移的问题

### ISSUE THREAD

**Issue by zhangfengrui** [ant-design/ant-design#3637]
#### 发生问题的环境是：

可做操的tab页，当增加数量多时，内容会产生偏移问题
- antd 版本: 2.0.1
- 操作系统及其版本: OS X EI Capitan 10.11.5
- 浏览器及其版本: chrome  52.0.2743.116
#### 您期待的结果是:

![](http://img.blog.csdn.net/20161028164702108?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center) 

不管增加多少tab页不会产生偏移
#### 实际上的结果是:

![](http://img.blog.csdn.net/20161028164644087?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

tab页数量增加过多时会产生偏移

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

这样贴两个图没啥用。

**Comment by afc163** [comment]
感觉和 https://github.com/ant-design/ant-design/issues/3304 是同一个问题。

**Comment by benjycui** [comment]
应该是，最新版已经没这个问题了。

这周会发布 2.2.0，如果升级后还有问题再开，谢谢。

**Comment by benjycui** [comment]
可能还有问题。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
重现了。

**Comment by afc163** [comment]
Chrome 的奇怪 bug，感觉没什么好办法。

**Comment by benjycui** [comment]
Fixed in c48d7b5

After create 81 new tabs, it still works fine.

![image](https://cloud.githubusercontent.com/assets/3580607/20956065/9ece23c0-bc82-11e6-945c-79a8cbfa97ba.png)
