### ISSUE TITLE
table 可编辑单元格触发行点击事件https://github.com/ant-design/ant-design/issues/36370

### ISSUE THREAD

**Issue by liuyingjie1130** [ant-design/ant-design#36378]
### What problem does this feature solve?

可编辑单元格聚焦时不触发行点击事件

### What does the proposed API look like?

可编辑单元格聚焦时不触发行点击事件
事实是先触发行点击 再触发的表单元素input -focus事件，不能用阻止冒泡解决

**Comment by liuyingjie1130** [comment]
https://codesandbox.io/embed/ke-bian-ji-dan-yuan-ge-antd-4-21-4-forked-gf8wnl?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-antd-4-21-4-forked-xzw85l?file=/demo.js

**Comment by zombieJ** [comment]
@afc163 已经回答你了 [comment-1174521575](https://github.com/ant-design/ant-design/issues/36370#issuecomment-1174521575)，阻止冒泡即可：

https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-antd-4-21-4-forked-r5wmh0

聚焦事件是异步调用，你要阻止的是点击冒泡。

**Comment by liuyingjie1130** [comment]
> https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-antd-4-21-4-forked-xzw85l?file=/demo.js

感谢！
