### ISSUE TITLE
可编辑单元格表格，点击单元格时会触发onRow

### ISSUE THREAD

**Issue by liuyingjie1130** [ant-design/ant-design#36370]
### What problem does this feature solve?

点击可编辑单元格时不触发onRow

### What does the proposed API look like?

希望点击可编辑单元格时不会触发onRow

**Comment by liuyingjie1130** [comment]
> Hello @liuyingjie1130. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @liuyingjie1130, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
可复现
https://codesandbox.io/embed/ke-bian-ji-dan-yuan-ge-antd-4-21-4-forked-gf8wnl?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
点击单元格内的元素触发行点击，这是符合预期的。如果不希望触发，可以给在表单元素上阻止事件冒泡。

**Comment by liuyingjie1130** [comment]
> 点击单元格内的元素触发行点击，这是符合预期的。如果不希望触发，可以在表单元素上阻止事件冒泡。

可是是先触发行点击 再触发的表单元素input -focus事件，不是冒泡啊
