### ISSUE TITLE
[Modal.confirm] 在 `modal.confirm` 外层包裹 `Promise`，在 `onOk` 方法或 `onCancel` 方法中调用 `reject` 会报错

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design#36375]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rglcg7?file=/index.js)

### Steps to reproduce

点击 `点击打开弹窗 验证 outer Promise reject` 按钮，在打开的弹窗中点击 `Cancel` 或者 `Ok`，会报错

### What is expected?

在这种情况下调用 `reject` 方法不报错，也不影响正确的处理 `resolve` 结果，如果调用 `close` 方法可以关闭弹窗。

### What is actually happening?

点击  `Cancel` 或者 `Ok` 按钮报错。

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 17 / 18 |
| System | macos Monterey |
| Browser | google chrome版本 103.0.5060.53（正式版本） (arm64) |

---
1. 在 antd version 4.20.7 和 4.21.5 都可以复现
2. 在 onOk 或 onCancel 方法内 new promise 里调用 reject 无问题 (见 demo)
3. 在 onOk 或 onCancel 方法内调用外面的 reject 方法都会报错

**Comment by afc163** [comment]
这和 antd 貌似没啥关系，Promise.reject 了本身就是报错。https://codesandbox.io/s/antd-reproduction-template-forked-xxsnmc?file=/index.js

**Comment by izhouteng** [comment]
没懂。。。你到底想说啥。。能简化下吗。。。

**Comment by GOWxx** [comment]
> 这和 antd 貌似没啥关系？Promise.reject() 本身就是报错。https://codesandbox.io/s/antd-reproduction-template-forked-xxsnmc?file=/index.js

确实，昨晚上头了 :flushed:
打扰了！

**Comment by GOWxx** [comment]
> 没懂。。。你到底想说啥。。能简化下吗。。。

是昨晚 ant design 社区群里在讨论到的内容，我这里没有提供完整的上下文，但既然不是组件的问题，我也就不再赘述了，感谢回复！
