### ISSUE TITLE
依赖下载报错 https://registry.npmmirror.com/antd/-/antd-4.21.5.tgz: unexpected end of file

### ISSUE THREAD

**Issue by azeory** [ant-design/ant-design#36377]
### Reproduction link

[https://registry.npmmirror.com/antd/-/antd-4.21.5.tgz](https://registry.npmmirror.com/antd/-/antd-4.21.5.tgz)

### Steps to reproduce

package.json 下，antd依赖版本是："antd": "^4.10.2",
他会默认下载https://registry.npmmirror.com/antd/-/antd-4.21.5.tgz 这个源下的文件，但是文件下载会报错unexpected end of file

### What is expected?

正确下载不报错

### What is actually happening?

正确下载不报错

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | windows |
| Browser | 暂无 |

---
 目前我是用了"antd": "4.17.2",版本代替，希望可以解决以上问题

**Comment by MadCcc** [comment]
我可以正常下载

**Comment by afc163** [comment]
网络或镜像源问题，和 antd 本身无关。

> BTW: 我这里可以下载。

**Comment by azeory** [comment]
> 我可以正常下载

不确定是不是源的问题，直接下载是可以，他会跳转到cdn上面去，我自己电脑也可以，但是放到服务器上不行，服务器是一个新的服务器，我只是安装了nodejs和npm，nodejs 是12版本。

**Comment by azeory** [comment]
> 网络

有可能，我这里是虚拟机内网里面无法下载
