### ISSUE TITLE
table组件  当在固定列上添加tooltip,tooltip是加在父级元素上时,前几行数据的tooltip会被遮挡.当不是固定列时,没有问题.

### ISSUE THREAD

**Issue by a64180120** [ant-design/ant-design#36397]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-21-5-forked-bv095r?file=/demo.js)

### Steps to reproduce

import React from "react";
import "antd/dist/antd.css";
import "./index.css";
import { Table, Tooltip } from "antd";

const columns = [
  {
    title: "Full Name",
    width: 100,
    dataIndex: "name",
    key: "name",
    fixed: "left"
  },
  {
    title: "Age",
    width: 100,
    dataIndex: "age",
    key: "age",
    fixed: "left"
  },
  {
    title: "Column 1",
    dataIndex: "address",
    key: "1",
    width: 150
  },
  {
    title: "Column 2",
    dataIndex: "address",
    key: "2",
    width: 150
  },
  {
    title: "Column 3",
    dataIndex: "address",
    key: "3",
    width: 150
  },
  {
    title: "Column 4",
    dataIndex: "address",
    key: "4",
    width: 150
  },
  {
    title: "Column 5",
    dataIndex: "address",
    key: "5",
    width: 150
  },
  {
    title: "Column 6",
    dataIndex: "address",
    key: "6",
    width: 150
  },
  {
    title: "Column 7",
    dataIndex: "address",
    key: "7",
    width: 150
  },
  {
    title: "Column 8",
    dataIndex: "address",
    key: "8"
  },
  {
    title: "Action",
    key: "operation",
    fixed: "right",
    width: 100,
    render: () => (
      <Tooltip
        getPopupContainer={(node) => node.parentNode}
        placement="top"
        title="Prompt Text"
      >
        <a>action</a>
      </Tooltip>
    )
  }
];
const data = [];

for (let i = 0; i < 100; i  ) {
  data.push({
    key: i,
    name: `Edrward ${i}`,
    age: 32,
    address: `London Park no. ${i}`
  });
}

const App = () => (
  <Table
    columns={columns}
    dataSource={data}
    scroll={{
      x: 1500,
      y: 300
    }}
  />
);

export default App;

### What is expected?

可以正常看到tooltip

### What is actually happening?

tooltip被遮挡,像是position:sticky属性引起的.

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome |

---
我需要点击这个tooltip的内容跳转新页面,如果我把tooltip挂在body上,跳转到新页面,tooltip不会关闭.所以需要挂载在父级元素上

**Comment by afc163** [comment]
第一个单元格层级比下面一个单元格的层级低（因为文档流顺序的关系），所以子元素会被下面的遮挡。

如果只是不想挂 body，可以挂到当前 table 的 .ant-table 节点上。
