### ISSUE TITLE
Table表格火狐浏览器较低版本中打不开，报错 "Component is not available" nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"

### ISSUE THREAD

**Issue by liwd163** [ant-design/ant-design#36398]
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn/](https://ant-design.antgroup.com/components/table-cn/)

### Steps to reproduce

在国产化环境中，自带的浏览器是火狐浏览器v52版本，打开Table报错，经验证在Windows下用v52版本的火狐浏览器也能重现，并且发现如果antd的版本使用4.15.3或更低，则正常。
重现方法：在火狐浏览器v52版本中，直接打开官网例子（https://ant-design.antgroup.com/components/table-cn/），就能重现。

### What is expected?

antd高于4.15.3的版本中，Table组件也能在火狐浏览器v52版本中使用。

### What is actually happening?

在火狐浏览器v52版本中，如果antd的版本高于4.15.3，Table组件无法打开，报错：Exception... "Component is not available" nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)" location: "JS frame :: https://gw.alipayobjects.com/render/p/yuyan/180020010001207320/index-f649b91b.js :: r :: line 49" data: no]

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 不限 |
| System | 不限 |
| Browser | 火狐浏览器 v52 |

---
政府部门的一些国产化环境中，浏览器往往是固定，无法升级也不能安装其他浏览器。
火狐浏览器下载：https://ftp.mozilla.org/pub/firefox/releases/52.0.2/

**Comment by afc163** [comment]
不再支持这么老的浏览器了。

**Comment by njleonzhang** [comment]
你好，我尝试使用babel对antd进行转义成es5后，依然无法访问。请问具体是什么语法或者api 在老浏览器不支持了？

**Comment by GuozhengXiong** [comment]
> 你好，我尝试使用babel对antd进行转义成es5后，依然无法访问。请问具体是什么语法或者api 在老浏览器不支持了？

你好，请问找到具体是什么语法或者api不支持了嘛

**Comment by yoyo837** [comment]
按理说, 以目标浏览器版本配好babel + browserslist 应该是能支持的. 请自行研究一下哈.

**Comment by GuozhengXiong** [comment]
> 按理说, 以目标浏览器版本配好babel + browserslist 应该是能支持的. 请自行研究一下哈.

您说的这两个都已经配置好了，还是有如题的错误，所以想知道是不是有什么垫片或者补丁需要额外添加。

**Comment by yoyo837** [comment]
babel + browserslist 的配置下, js的部分底层是core-js在负载polyfill.

可以具体错误扣一下, 对应一下源码位置, 看看到底啥错. 版本是在太低, 我们这边就不跟进了.

**Comment by coincidenceSS** [comment]
> babel + browserslist 的配置下, js的部分底层是core-js在负载polyfill.
> 
> 可以具体错误扣一下, 对应一下源码位置, 看看到底啥错. 版本是在太低, 我们这边就不跟进了.

好的，感谢回答
