### ISSUE TITLE
DatePicker works differently when clicked tab twice

### ISSUE THREAD

**Issue by gmoniava** [ant-design/ant-design#36394]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/morning-http-kx9ze9?file=/src/App.js)

### Steps to reproduce

**NOTE: The `onChange` handler is being called in both scenarios which you can check by doing `console.log`**

Scenario 1

- _Type manually_ 2022-01-01 in the input
- Click with mouse the suggested day "1"
- You will see selected date will be 2021-12-31

Scenario 2

- _Type manually_ 2022-01-01 in the input
- Instead of clicking with mouse on day, press TAB key twice
- You will see selected date will be 2022-01-01

### What is expected?

The result in step 3 should be the same, in both scenarios.

### What is actually happening?

Step 3 is different for above two scenarios

| Environment | Info |
| --- | --- |
| antd | 4.21 |
| React | 17 |
| System | Ubuntu |
| Browser | Chrome 101 |

---
**NOTE: Like I mentioned, the `onChange` handler is being called in both scenarios which you can check by doing `console.log`**.

**Comment by gmoniava** [comment]
@AryaBuddha probably you aren't following steps carefully. I can reproduce it from the sandbox link just now.

**Comment by gmoniava** [comment]
Not sure what above bot wants me to do, I just submitted bug, no time for pull request, or to fix it myself.

**Comment by gmoniava** [comment]
@AryaBuddha maybe your operating system or browser is different (check in the original issue). I recreated this behavior on few different PCs.

Ps. Also you typed different year, should be 2021, can't say if that's the cause now.

**Comment by LongHaoo** [comment]
Let me try to fix it? I have the same problem

**Comment by fandok** [comment]
Hi i think you can close this issue, tried to reproduce it on the latest 4.x.x version of antd here https://codesandbox.io/s/nice-sammet-kzd4dz?file=/src/App.js and it didn't happen like the one on the post

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
