### ISSUE TITLE
[v5] remove `es` dir for better import

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#36395]
### What problem does this feature solve?

Since we want to remove `lib` and focus on ESM only, it is better remove `es` dir.

Then we can:

```
import Button from 'antd/button';
```

instead of:

```
import Button from 'antd/es/button';
```

and have a better tree shaking experience.

### What does the proposed API look like?

```
import Button from 'antd/button';
```

**Comment by afc163** [comment]
Why not `import { Button } from 'antd';` ?

**Comment by Dunqing** [comment]
I like `import { Button } from 'antd'`;

**Comment by izhouteng** [comment]
import Button from 'antd/button'; 这种不觉得啰嗦吗？一大堆import。。 直接解构啊。。多简洁

**Comment by dancerphil** [comment]
Sorry for not reply in time. I agree that `import { Button } from 'antd';` should be the most recommend import pattern.

I'm talking about some edge cases which __have to__ import from es modules. Those will seems more trivial to import from `without-es` dir.

The main concept is that since we don't need to tell from `lib` and `es`, it's better just erase the `es` dir.

Some cases that I can imagine: 1. tree shaking without babel plugin. 2. import ts type from inner dirs. 3. some advanced usage of inner utils.

**Comment by izhouteng** [comment]
关于你说的这个问题，我深表理解。

题主之所以不喜欢 `import { Button } from 'antd'` 的语法，一个重要的原因，是因为这样 `tree shaking` 体验很差。

在 `Vite` 中，像上面这样简写的解构导入，会在打包时让 `Rollup` 去分析整个 `antd` 包。

因为，这样的解构导入，实际上是导入了整个 `antd` 模块，会极大的拖慢打包速度。

若改成 `import Button from 'antd/es/button'`，则打包速度可以飞跃提升。

但这种写法，实在是很啰嗦，好在，有一个插件 `vite-plugin-imp`，可以帮我们自动转换这种写法，并自动引入样式。

其实它就是 `babel-plugin-import` 的 `Vite` 版，给你参考一下我的配置，希望对你有帮助。

```
  plugins: [
    {
      ...styleImport({
        resolves: [
          AntdResolve()
        ]
      }),
      apply: 'serve'
    },
    {
      ...vitePluginImp({
        libList: [
          {
            libName: 'antd',
            style (name) {
              return `antd/es/${name}/style/index.js`
            }
          },
          { libName: 'lodash-es', libDirectory: '' },
          { libName: '@ant-design/icons', libDirectory: 'es/icons', camel2DashComponentName: false }
        ]
      }),
      apply: 'build'
    }
  ],
```

另外，这个问题其实并不关 `antd` 的事，删除 `lib` 目录只留 `es` 目录更是duck不必。

**Comment by dancerphil** [comment]
> 另外，这个问题其实并不关 `antd` 的事，删除 `lib` 目录只留 `es` 目录更是duck不必。

For clarification, in antd@v5, we may drop `lib` and ESM only, https://github.com/ant-design/ant-design/issues/34087.

So I'm talking about the further change after we drop `lib`.

If we decide that we will support `lib` for another major version, of course this will not happen.

**Comment by dancerphil** [comment]
由于我们仍需要保留 dist 等文件夹，关闭此 issue
