### ISSUE TITLE
popover 靠上或靠下超出部分会被浏览器遮挡

### ISSUE THREAD

**Issue by netskyline** [ant-design/ant-design#364]
popover 里面放置组件比较多的时候，会占用一部分页面，靠近浏览器上沿或下沿时超出部分会被浏览器遮挡，导致显示不完整，是否可以根据 popover 弹出的位置进行修正，最高只能到浏览器上沿，最低只能到下沿

**Comment by popomore** [comment]
+1 正在研究这个问题

2015年10月7日(水) 23:31 netskyline <notifications@github.com>:

**Comment by yiminghe** [comment]
tooltip 2.10.0 : https://github.com/react-component/tooltip/commit/646bf2270d2170ebc4834a64938c0dd9c02efc17
