### ISSUE TITLE
Feature request: optional close icon for messages

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#36401]
### What problem does this feature solve?

Real use case: a user creates a new API key, we generate a key, show it to him and redirect to the list of API keys. The key will be shown only once, so it's not visible on any specific page where I could've used `<Alert>`. I set the duration to 0 because it will be shown only once. But once user copied/saved the key it can close the message. It would be great to have optional "X" icon like Alerts have.

### What does the proposed API look like?

```
const closable = true;
message.info("Message", 0, closable);
```

**Comment by AryaBuddha** [comment]
Could you not just use a ``<Notification>`` instead? Has all the same features of a message and it's closeable.

**Comment by izhouteng** [comment]
visible on any page I don't think is a good idea.

It is recommended that you create keys on the API keys list page, then use `Alert ` to display the key.

maybe you can also use `Notification`

**Comment by csandanov** [comment]
I could use `<Notification>` but what bothers me is that I can't display it the center, the generated key is important to see, so it's not a "notification" but rather a result.

Anyway, I've reworked my UI to use `<Alert>` and it does look like a better solution in my case. I've posted this because that's not the first time I've came across that, I also considered using `Notification` back then.

Have you considered merging `message` and `Notification`? They are very similar, the limitation to place `Notification` only in right/left looks artificial to me. And at the same time why not allow `message` to have a title and a close icon.

**Comment by afc163** [comment]
See https://codesandbox.io/s/tong-guo-hooks-huo-qu-shang-xia-wen-4-5-0-antd-4-21-5-forked-uxcm9h?file=/demo.js

**Comment by csandanov** [comment]
wow, that's a lot of work to get a `Notification` in the middle

**Comment by afc163** [comment]
PR welcome to correct demo description.
