### ISSUE TITLE
Form components will break mobile view

### ISSUE THREAD

**Issue by Haocen** [ant-design/ant-design#36404]
### Reproduction link

[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce

Shrink the page using chrome mobile view.

### What is expected?

Page should fit screen width(responsive).

### What is actually happening?

Page no longer fit screen width.

https://user-images.githubusercontent.com/10842569/177693255-b8b5753d-38e2-4248-a0dc-a270faaaacb0.mov

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome Version 103.0.5060.66 |

**Comment by afc163** [comment]
Fixed now~
