### ISSUE TITLE
TreeSelect中的loadData和treeDefaultExpandedKeys一起使用时，有部分节点不能展开

### ISSUE THREAD

**Issue by Agzhen** [ant-design/ant-design#36403]
### Reproduction link

[https://stackblitz.com/edit/react-hzossa?file=demo.js](https://stackblitz.com/edit/react-hzossa?file=demo.js)

### Steps to reproduce

<TreeSelect
      loadData={onLoadData}
      treeDefaultExpandedKeys={['1', '2']}
    />

### What is expected?

期望的结果是默认展开的节点能够正常展开并显示

### What is actually happening?

给TreeSelect同时设置loadData和treeDefaultExpandedKeys，当treeDefaultExpandedKeys需要默认展开多个父节点时，虽然实际确实发送了每一个父节点的请求，但实际上只展开了其中的一个。
在官方文档中的异步加载例子里添加treeDefaultExpandedKeys={['1', '2']}会发现有一个节点失去了展开的功能
在实际项目中,我同时使用loadData和treeDefaultExpandedKeys,虽然指定的父节点的请求都发送了,但是并没有默认的展开(会有一个父节点是正常展开的),这让我无法获取某些属性,必须手动给节点点击展开后,才能正常获取属性

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 17.0.2 |
| System | window11 22000.739 |
| Browser | Google Chrome 103.0.5060.114 |

**Comment by zombieJ** [comment]
注意闭包：
https://stackblitz.com/edit/react-hzossa-zxqv8h?file=demo.js
