### ISSUE TITLE
在form Item里面多个input校验问题

### ISSUE THREAD

**Issue by is-cool** [ant-design/ant-design#36409]
### What problem does this feature solve?

在form Item里面有两个input, 只有一个需要走校验，怎么可以让它去忽略另外一个,或者说另一个不出现红框

### What does the proposed API look like?

在form Item里面有两个input, 只有一个需要走校验，怎么可以让它去忽略另外一个,或者说另一个不出现红框

https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-5-forked-b0lgl1?file=/CronInput.js
<img width="380" alt="截屏2022-07-07 15 52 29" src="https://user-images.githubusercontent.com/78067806/177721286-6172e4f7-022b-48e6-b26a-45495385fb20.png">

**Comment by MadCcc** [comment]
不要放在同一个 Form.Item 下？

**Comment by is-cool** [comment]
> 不要放在同一个 Form.Item 下？

https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-5-forked-b0lgl1?file=/CronInput.js；就是需要下面的input去生成上面的input值

**Comment by izhouteng** [comment]
就是啊，自己调整下样式能死？干嘛得放一个Item。。。无语
