### ISSUE TITLE
Modal里跳转路由后，无法自动关闭且无法通过原按钮事件关闭

### ISSUE THREAD

**Issue by dodospace** [ant-design/ant-design#36406]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mjshqx?file=/index.js)

### Steps to reproduce

如上述代码，在Modal里有route跳转业务，点击后正确跳转到route并渲染页面，但是Modal层无法自动关闭且无法通过modal上的按钮事件关闭

### What is expected?

自动销毁关闭

### What is actually happening?

始终停留在新route渲染的页面上

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17.0.2 |
| System | macOS Catalina 10.15.7 |
| Browser | 89.0.4389.90 |

**Comment by MadCcc** [comment]
Cannot reproduce
