### ISSUE TITLE
如何干掉默认的样式？比如 a:hover ？？

### ISSUE THREAD

**Issue by zaxlct** [ant-design/ant-design#3641]
急急急啊

**Comment by afc163** [comment]
自行覆盖样式。

**Comment by zaxlct** [comment]
能全局更改你们的主题色就好了

**Comment by afc163** [comment]
https://ant.design/docs/react/getting-started#%E9%85%8D%E7%BD%AE%E4%B8%BB%E9%A2%98%E5%92%8C%E5%AD%97%E4%BD%93

看文档啊。

**Comment by zaxlct** [comment]
@afc163  麻烦了，没仔细看文档。
