### ISSUE TITLE
在layout组件中嵌套使用 Menu, 并且将 Menu 的 mode 设置为 horizontal，会导致菜单一直闪烁，去掉 css 之后更佳明显

### ISSUE THREAD

**Issue by hlerenow** [ant-design/ant-design#36418]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ding-bu-ce-bian-bu-ju-antd-4-21-5-laout-menu-mode-horizontal-rpt08t?file=/demo.js:1001-1011)

### Steps to reproduce

打开链接即可复现

### What is expected?

停止闪烁

### What is actually happening?

一直闪烁

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac |
| Browser | chorme |

**Comment by afc163** [comment]
加上 css 后貌似没有闪动问题：https://codesandbox.io/s/ding-bu-ce-bian-bu-ju-antd-4-21-5-laout-menu-mode-horizontal-forked-csh1pk
