### ISSUE TITLE
Not able to input date manually, when format is passed as custom function

### ISSUE THREAD

**Issue by stanlaktionov** [ant-design/ant-design#36425]
### Reproduction link

[https://ant.design/components/date-picker/#components-date-picker-demo-format](https://ant.design/components/date-picker/#components-date-picker-demo-format)

### Steps to reproduce

In your example here - `https://ant.design/components/date-picker/#components-date-picker-demo-format` click the last date picker and try to type the date manually with the keyboard

### What is expected?

It is allowed to type date manually

### What is actually happening?

Inputting is not happening

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18.1.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by futbolistua** [comment]
I have the same issue. Wil it be fixed or not?

**Comment by zombieJ** [comment]
![Kapture 2022-07-26 at 15 57 35](https://user-images.githubusercontent.com/5378891/180954436-6e401c56-fbe0-47c4-8f82-ba9dc0081ea4.gif)

**Comment by LongHaoo** [comment]
Let me try to fix it

**Comment by LongHaoo** [comment]
https://github.com/react-component/picker/pull/222/files  
目前发现这个问题是因为这个 PR 导致的,设置了 readOnly
it is found that this problem is caused by this PR。
it set readOnly

**Comment by LongHaoo** [comment]
https://github.com/react-component/picker/blob/master/src/utils/dateUtil.ts#L226
@zombieJ 就算修改了 ReadyOnly 好像本身 format 传入函数也无法进行反向的选择解析。
Even if ReadyOnly is removed, it seems that the format input function itself cannot perform reverse selection parsing.
