### ISSUE TITLE
Drawer component fills full screen and instantly goes to normal when mask=false

### ISSUE THREAD

**Issue by AndrewEastwood** [ant-design/ant-design#36423]
### Reproduction link

[https://stackblitz.com/edit/react-cmt7mm?file=demo.js](https://stackblitz.com/edit/react-cmt7mm?file=demo.js)

### Steps to reproduce

Just observe how the drawer is being shown first time.

### What is expected?

I'd expect that the drawer wont goes fulls screen rather sets as usual (same as when mask is on)

### What is actually happening?

The drawer fills full screen at the beginning when when mask is set to false

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18.2.0 |
| System | macOS 11.3.1 |
| Browser | Chrome 103.0.5060.53 |

**Comment by afc163** [comment]
I can't reproduce in my machine. Mac Chrome 103.0.5060.114

![Jul-08-2022 10-18-23](https://user-images.githubusercontent.com/507615/177903577-50cf7442-94f3-48d4-9130-29eb875d58ca.gif)

**Comment by AndrewEastwood** [comment]
hmmm is it the same link that I gave? try to click refresh button few times

**Comment by AndrewEastwood** [comment]
here we go: https://codesandbox.io/s/antd-reproduction-template-forked-z5nbey?file=/index.js
I'm also adding recording (it's happening from 0:26)

https://user-images.githubusercontent.com/1483306/178043136-b4ccf28c-6ff9-469f-ba51-d8355d1d15af.mov

**Comment by AndrewEastwood** [comment]
besides the link you gave is not quite following React v18. See migration docs (https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)

**Comment by AndrewEastwood** [comment]
??

**Comment by AndrewEastwood** [comment]
@afc163 I will reopen this bug again
