### ISSUE TITLE
filterDropdown does not manage tab (usability regression since 4.19)

### ISSUE THREAD

**Issue by danielkov** [ant-design/ant-design#36424]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-filterdropdown-focus-issue-yy73v8)

### Steps to reproduce

- Add `filterDropdown` option to a column
- Press on the filter icon
- Focus on an input element
- Press `tab`

### What is expected?

Focus moves to the next element

### What is actually happening?

Focus is lost and filter dropdown is closed

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 17.0.2, 18.0.0 |
| System | MacOS 12.4 (21F79) |
| Browser | Chrome |

---
[Here's a link to the last working version](https://codesandbox.io/s/antd-filterdropdown-focus-issue-last-working-version-9tp2mv) (4.18.9) - it is the same code, the only difference is the antd version. Please also note that the bug occurs with React 17 and 18, so it's not related to `render` vs `createRoot` mounting implementation.

**Comment by afc163** [comment]
trace #36176
