### ISSUE TITLE
Radio嵌套Select场景下，Select设置defaultValue，Select下拉菜单无法打开，会先展开后，马上关闭

### ISSUE THREAD

**Issue by lsky-walt** [ant-design/ant-design#36438]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-5-forked-wpze2z?file=/demo.js)

### Steps to reproduce

直接点击select就能重现。
在示例中，只需注释 defaultValue，就恢复正常。

### What is expected?

正常展开下拉菜单

### What is actually happening?

下拉菜单展开之后，马上关闭。

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 16.14.0 |
| System | mac os |
| Browser | chrome 103 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25959#issuecomment-671129621
