### ISSUE TITLE
Form.Item组件可以添加后缀元素的配置吗?

### ISSUE THREAD

**Issue by xsjohn0306** [ant-design/ant-design#3643]
Form.Item组件可以添加后缀元素的配置吗?
比如说我想加一个a链接在表单元素后面

**Comment by yesmeck** [comment]
可以的，Form.Item 里可以写任意的元素。

**Comment by benjycui** [comment]
@xsjohn0306 给个截图之类？这样不知道你想问什么。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/ZpgKoR?editors=001

应该是需要这样的。

**Comment by benjycui** [comment]
也可以参考下这个：

http://ant.design/components/form/#components-form-demo-register

![image](https://cloud.githubusercontent.com/assets/3580607/19914478/f68640c4-a0e5-11e6-9c9e-6e17b5a4f1e8.png)

**Comment by xsjohn0306** [comment]
我想要的是这种布局

![demo](https://cloud.githubusercontent.com/assets/8650758/19928768/fa30104c-a13a-11e6-98fa-b6faf9b70d2c.JPG)

**Comment by benjycui** [comment]
现在 Form.Item 的布局是与 Layout 一致的，所以你这种需求应该满足不了。

可以尝试自己写样式，用 `display: table` 可以实现类似的效果。
