### ISSUE TITLE
Button 在执行useEffect后会出现loading 的动画效果

### ISSUE THREAD

**Issue by tgq52298** [ant-design/ant-design#36449]
### Reproduction link

[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce

1、在reactV18版本中使用"antd": "^4.21.3"
2、在useEffect 中执行api 请求接口 Button组件会出现loading的问题

### What is expected?

暂无

### What is actually happening?

暂无

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | reactV18 |
| System | windows |
| Browser | google |

**Comment by izhouteng** [comment]
关了吧。。提问都不会。。
