### ISSUE TITLE
Need method to get current page data or get current filtered total data in Table

### ISSUE THREAD

**Issue by jochenshi** [ant-design/ant-design#36440]
### What problem does this feature solve?

1. With this method user can get current page data without calculate themself when in pagination;
2. User can also get total data in filter situation without needing to listen `onChange` event, and can get data anytime they want

### What does the proposed API look like?

1. get current page data: `formRef.getCurrentPageFlatData()`;
2. get total data: `formRef.getTotalFlatData()`

**Comment by afc163** [comment]
Please use `onChange`.

**Comment by jochenshi** [comment]
> Please use `onChange`.

This cannot cover all situations. eg: Table is in front-end pagination and filtered, then new records could be added to dataSource which will not trigger `onChange`

**Comment by hellobq** [comment]
onChange 不能覆盖所有的情况。eg: 表格已经过滤了，但是后来改了 dataSource，那么不会主动出发 onChange 的 ...
