### ISSUE TITLE
upload组件使用问题

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#3644]
#### 发生问题的环境是：

- antd 版本:2.1.0
- 操作系统及其版本:wind10
- 浏览器及其版本:chrome54
#### 您做了什么？请提供尽可能详细的重现步骤。

在uplaod组件上不实现 onPreview及onRemove时，觉得从业务场景上组件对应的不应该有预览图标(或链接文字)及删除按钮。

#### 实际上的结果是:

 uplaod组件上不实现 onPreview及onRemove，也会有对应的操作图标及链接，删除点击后会删除。

#### 可重现的在线演示

网站例子不实现删除都如此

**Comment by afc163** [comment]
实际上，用户不实现 onPreview 和  onRemove 时，Upload 也有默认的行为。

- onPreview：默认新窗口打开（这里有问题）
- onRemove：默认移除文件
