### ISSUE TITLE
Skeleton组件active=true下，移动端浏览器圆角显示异常

### ISSUE THREAD

**Issue by wyj580231** [ant-design/ant-design#36444]
### Reproduction link

[https://ant-design.antgroup.com/components/skeleton-cn/#components-skeleton-demo-list](https://ant-design.antgroup.com/components/skeleton-cn/#components-skeleton-demo-list)

### Steps to reproduce

IOS手机Chorme/支付宝容器内打开Skeleton组件示例页，demo最后一项，展示异常，圆角丢失

### What is expected?

圆角正常

### What is actually happening?

圆角变方

| Environment | Info |
| --- | --- |
| antd |- |
| React |- |
| System | IOS |
| Browser | Chrome |

**Comment by afc163** [comment]
I don't know how to fix it, it seems to be a bug of safari browser.

**Comment by afc163** [comment]
Found it!! https://monshin.github.io/202109/css/safari-border-radius-overflow-hidden/
