### ISSUE TITLE
在 `Modal` 中使用 `Upload` 组件 `action` 不是最新的值

### ISSUE THREAD

**Issue by HuangKaiSong** [ant-design/ant-design#36442]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-cache-1ljbox?file=/src/App.js)

### Steps to reproduce

如上述代码，在 `Modal` 里有上传图片需求，选择图片后需要发起请求获取 `oss` 签名。但 `Upload` 组件的 `action` 属性没有实时更新到最新值

### What is expected?

`Upload` 组件的 `action` 属性获取到的是最新值

### What is actually happening?

`Upload` 组件的 `action` 属性获取到的是上一次的结果

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.0.0 |
| System | MacOS 12.4 |
| Browser | Google Chrome 103.0.5060.114（正式版本） (x86_64) |

**Comment by afc163** [comment]
如何重现，你的演示里下面这个请求貌似不会返回，走不到 ossConfig 更新这一步。

```
    const response = await fetch("https://oss-sign.joy-art.cn/");
```

**Comment by hhb1994** [comment]
https://github.com/ant-design/ant-design/issues/36949 看这个
