### ISSUE TITLE
AutoComplete的自定义输入项和自定义Option无法并存

### ISSUE THREAD

**Issue by tonylua** [ant-design/ant-design#36454]
### Reproduction link

[http://foo.bar/null](http://foo.bar/null)

### Steps to reproduce

null

### What is expected?

rt

### What is actually happening?

rt

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac 12.2 (21D49) |
| Browser | chrome 103.0.5060.114（正式版本） (arm64) |

**Comment by zombieJ** [comment]
`options` 等价 Option 语法糖，直接用 `options`
