### ISSUE TITLE
Image.Preview 不应该用动画放大控件

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#36456]
https://ant.design/components/image-cn/#components-image-demo-preview-group-visible

应该只有图片本身走动画放大。@shaodahong

**Comment by shaodahong** [comment]
> 应该只有图片本身走动画放大

我看现在是放大图片本身，这里指的是？

**Comment by afc163** [comment]
缩放按钮，转向按钮，mask，关闭按钮，现在会随图片打开也走一次放大的动画。

**Comment by shaodahong** [comment]
> 缩放按钮，转向按钮，mask，关闭按钮，现在会随图片打开也走一次放大的动画。

嗯，这个是 Modal 组件的放大逻辑，这里可以优化下，在 modal animate 结束后再显示操作栏
