### ISSUE TITLE
自定义表单组件的校验状态

### ISSUE THREAD

**Issue by JackShell2020** [ant-design/ant-design#36463]
### What problem does this feature solve?

自定义表单组件不使用或者不完全使用antd的组件，无法自动响应校验状态。当前antd的表单组件响应validateFields错误时，是在外层添加class的方法实现的，自定义组件无法完全响应对应的错误。

### What does the proposed API look like?

自定义组件除了value和onChange，再增加一个与校验相关的回调onValidate。这样当执行form.validateFields时或执行之后，执行onValidate，自定义组件内部根据onValidate的参数，封装对应的校验状态

**Comment by afc163** [comment]
> 自定义表单组件不使用或者不完全使用antd的组件，无法自动响应校验状态

给重现的例子。

**Comment by MadCcc** [comment]
是不是和这个需求一样？只要能拿到 formItem 的 status 就可以了
https://github.com/ant-design/ant-design/issues/36003

**Comment by JackShell2020** [comment]
> 
差不多，又不太一样。这个好像只有value变化时才输出，form执行validateFields的时候没有输出

**Comment by JackShell2020** [comment]
> 是不是和这个需求一样？只要能拿到 formItem 的 status 就可以了 #36003

差不多，又不太一样。这个好像只有value变化时才输出，form执行validateFields的时候没有输出

**Comment by MadCcc** [comment]
> 差不多，又不太一样。这个好像只有value变化时才输出，form执行validateFields的时候没有输出

formItem 的状态变化会通过这个 context 下传，触发校验也同理，先合并过去了。
Duplicate of https://github.com/ant-design/ant-design/issues/36003
