### ISSUE TITLE
Calendar 日历组件，官网是中文，实际使用是英文，默认配置zhCN 还是没用。

### ISSUE THREAD

**Issue by CodeCat01** [ant-design/ant-design#36465]
### Reproduction link

[https://stackblitz.com/run?file=demo.js](https://stackblitz.com/run?file=demo.js)

### Steps to reproduce

100%

### What is expected?

看到的是 周一～周日 

### What is actually happening?

英文

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome |

**Comment by gaokaifeis** [comment]
是否导入了moment的中文资源  import 'moment/locale/zh-cn'

**Comment by ydwan** [comment]
> 是否导入了moment的中文资源 import 'moment/locale/zh-cn'

同样的问题，已经导入了和设置了moment zh-cn。
但是依旧显示的是英文

**Comment by izhouteng** [comment]
你链接复制错了。。
还有，你是不是用的pnpm？

**Comment by ydwan** [comment]
> 你链接复制错了。。 还有，你是不是用的pnpm？

我这边完善了codesanbox，链接https://codesandbox.io/s/antd-reproduction-template-forked-cs1bjf?file=/index.js

**Comment by gaokaifeis** [comment]
> > 你链接复制错了。。还有，你不是用的pnpm？
> 
> 我这边完成了codesanbox，链接https://codesandbox.io/s/antd-reproduction-template-forked-cs1bjf?file=/index.js

![image](https://user-images.githubusercontent.com/29112400/178399205-36ffd7ab-2bd8-4f13-9d01-9b8b85667f09.png)
还是没导入moment资源，导入后就可以了

**Comment by ydwan** [comment]
> > > 你链接复制错了。。还有，你不是用的pnpm？
> > 
> > 
> > 我这边完成了codesanbox，链接https://codesandbox.io/s/antd-reproduction-template-forked-cs1bjf?file=/index.js
> 
> ![image](https://user-images.githubusercontent.com/29112400/178399205-36ffd7ab-2bd8-4f13-9d01-9b8b85667f09.png) 还是没导入moment资源，导入后就可以了

嗯嗯，发现是moment版本，我本地使用的是2.91.1，然后就稳定复现

![image](https://user-images.githubusercontent.com/11845768/178402308-908d67da-1860-4d7a-9f6e-7e57acddd537.png)

**Comment by afc163** [comment]
由于安全原因 antd 依赖的 moment 已经升级到 2.29.2 以上。项目中依赖低于这个版本的 moment 就会导致加载两个版本 moment 实例。解决方法是把项目里的 moment 也升级上来，API 是兼容的，理论上没有风险。

https://github.com/ant-design/ant-design/pull/34867

**Comment by qld-cf** [comment]
> moment

升级到2.29.3解决了

**Comment by CodeCat01** [comment]
你们都拿date-picker， 我用的是 calendar组建，引入了 moment/locale/zh-cn,还是英文



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月12日 10:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ant-design/ant-design] Calendar 日历组件，官网是中文，实际使用是英文，默认配置zhCN 还是没用。 (Issue #36465) |

是否导入了moment的中文资源 import 'moment/locale/zh-cn'

同样的问题，已经导入了和设置了moment zh-cn。
但是依旧显示的是英文

**Comment by qld-cf** [comment]
> 你们都拿date-picker， 我用的是 calendar组建，引入了 moment/locale/zh-cn,还是英文
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年07月12日 10:34 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [ant-design/ant-design] Calendar 日历组件，官网是中文，实际使用是英文，默认配置zhCN 还是没用。 (Issue #36465) | 是否导入了moment的中文资源 import 'moment/locale/zh-cn' 同样的问题，已经导入了和设置了moment zh-cn。 但是依旧显示的是英文 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@CodeCat01 

升级moment到最新版本
upgrade moment to newest version
