### ISSUE TITLE
Use rawgit cdn for improving site speed

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3646]
http://rawgit.com/

**Comment by benjycui** [comment]
加了代理之后，这个改动的意义不大了吧。

**Comment by afc163** [comment]
代理会降低其他地区的访问速度。

**Comment by benjycui** [comment]
内页的 demo.js 还是用 ant.design 的，不过文件比较小，应该还好。

**Comment by benjycui** [comment]
rawgit 的同步有问题，不能保证是 GitHub Page 上面最新的文件。

**Comment by afc163** [comment]
> Requests to cdn.rawgit.com are routed through MaxCDN's super fast content delivery network, and are cached permanently at the CDN layer based on the URL. This results in the best performance and reduces load on RawGit and on GitHub, but it means that reloading won't fetch new changes from GitHub.

**Comment by afc163** [comment]
> To ensure that the CDN always serves the version of the file you want, use a git tag or commit hash in the file's path instead of a branch name, and update the URL if you push a new version of the file.

> So, instead of a URL like https://cdn.rawgit.com/user/repo/branch/file, use a URL like https://cdn.rawgit.com/user/repo/tag/file or https://cdn.rawgit.com/user/repo/commit/file.

**Comment by afc163** [comment]
https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions

**Comment by benjycui** [comment]
这样每次发网站都要发两次？一次发布最新的网站内容，然后更新资源引用，再发布一次？有点扯。。

**Comment by benjycui** [comment]
这个先关了，方案不可行。

**Comment by afc163** [comment]
貌似不用发布两次，发布时直接修改 index.html 内的资源路径即可。

**Comment by benjycui** [comment]
> 貌似不用发布两次，发布时直接修改 index.html 内的资源路径即可。

ant.design 使用了 SSR，所以每次修改后，HTML 的内容是不以言的。

**Comment by afc163** [comment]
```html
<script src="/common.js"></script>  => 统一替换下这个路径不就可以了。
<script src="/index.js"></script>
```

**Comment by benjycui** [comment]
> To ensure that the CDN always serves the version of the file you want, use a git tag or commit hash in the file's path instead of a branch name, and update the URL if you push a new version of the file.

是统一替换就可以，但是要先发一版，然后拿到最新的 common.js index.js 再替换。
