### ISSUE TITLE
select的下拉框增加懒加载，选中后隐藏

### ISSUE THREAD

**Issue by JackShell2020** [ant-design/ant-design#36464]
### What problem does this feature solve?

select使用远程搜索时，不能一次渲染所有options，需要一个懒加载的机制，现在我在onPopupScroll中判断是否滚动到底，去执行下一页的搜索，此时还要处理option，增加一个loading-Spin的option，loading结束再删除spin并且拼接新的options，处理起来比较复杂，希望官方能够提供一个好的解决方案。
另一个进阶版的需求，当options被选中之后就隐藏的功能，官方demo只适用lable与value相同的情况，否则过滤掉option会导致渲染错误（卡bug呢，options中没有对应value时，直接显示value内容），我目前的方案是设置<Option style={{display: 'none'}}>，并且在dropdownRender中判断是否全部选中来确定是否return无数据的提示（官方也没有说dropdownRender与notFoundContent的冲突关系），显然我这种方式是不太好的

### What does the proposed API look like?

期望对上述两种功能进行优化升级，提供一个比较好的方式来处理逻辑

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by zombieJ** [comment]
> 增加一个loading-Spin的option

还是推荐 HOC 来实现一个 `loadOptions` 方法，Select 本身是受控组件，提供 `loadingOption` 实现滚动加载逻辑其实还是要自己实现受控部分。

> 当options被选中之后就隐藏

这个详细说说使用场景是什么？

**Comment by JackShell2020** [comment]
比如在onPopupScroll的基础上增加一个 onPopupScrollEnd，要求返回一个[promise, formatterHandle]，当执行onPopupScrollEnd时，antd负责管理loading状态，promise完成后，执行formatterHandle进行拼接options

关于：options被选中之后就隐藏
官方demo有个明显的问题就是上面说的那种情况，我看到demo可以隐藏选中项，就反馈给PM了，PM说那就隐藏，好家伙，结果给自己挖了个大坑。
众多数据中，选中后的不要再显示在options里面了，上下滚动实在太累，需要隐藏掉已经选中的项
```tsx
// selectValues
const optsDom = []
let hideCount = 0
const notFoundContent = <div>xxxx</div>
options.forEach(i => {
  const hidden = selectValues.includes(i.value)
  if (hidden) hideCount += 1
  return <Option className={ hidden ? 'hidden' : ''} value={i.value}>{i.label}</Option>
})
...

dropdownRender={(menu) => {
  if (loading) {
    return <>{menu}</>
  }
  if (searchVal && options.length === 0) {
    return notFoundContent
  }
  return <>
    {hideCount < options.length && menu}
    {
      options.length > 0 && hideCount === options.length && notFoundContent
    }
  </>
}}
```
