### ISSUE TITLE
0711版本升级带来的问题-表格列render文字超出省略号并且使用气泡框，省略号丢失且文字层级过高，超出省略不生效缩小屏幕会覆盖其他列文字，hover文字会发生截断

### ISSUE THREAD

**Issue by BearXmX** [ant-design/ant-design#36474]
### Reproduction link

[http://simg01.gaodunwangxiao.com/uploadfiles/tmp/upload/202207/12/08901_20220712120208.png](http://simg01.gaodunwangxiao.com/uploadfiles/tmp/upload/202207/12/08901_20220712120208.png)

### Steps to reproduce

无

### What is expected?

无

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | react17 |
| System | window |
| Browser | 谷歌 |

**Comment by BearXmX** [comment]
http://simg01.gaodunwangxiao.com/uploadfiles/tmp/upload/202207/12/77e22_20220712120343.png

**Comment by haungxinyan** [comment]
我也出现这个问题了   不显示省略号
