### ISSUE TITLE
formItem shaking

### ISSUE THREAD

**Issue by KKarai** [ant-design/ant-design#36470]
### Reproduction link

[https://ant.design/components/form/#header](https://ant.design/components/form/#header)

### Steps to reproduce

Enter one letter, then delete the text (repeat several times). 

### What is expected?

Input field not jumping

### What is actually happening?

When the validation text appears, the input box jumps

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | react |
| System | macOs 12.0.1 |
| Browser | chrome |

**Comment by nuintun** [comment]
https://github.com/ant-design/ant-design/pull/36358

**Comment by izhouteng** [comment]
@afc163 @zombieJ @MadCcc 这个抖动问题不看看吗.......修过之后抖动更夸张了，之前的版本还好点。

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#components-form-demo-complex-form-control

确实抖瞎了。

**Comment by izhouteng** [comment]
> https://ant.design/components/form-cn/#components-form-demo-complex-form-control
> 
> 确实抖瞎了。

是的，在Input快速输入然后快速删除，疯狂抖动，强迫症看了表示针滴难受（捂脸

在线等修复ing

**Comment by izhouteng** [comment]
话说。。目前有人修这bug吗？

**Comment by zombieJ** [comment]
Fixed. PS: 因为 dom 结构有改动，会到 minor 版本发布修复.
