### ISSUE TITLE
upload组件进行跨域上传如何设置headers属性

### ISSUE THREAD

**Issue by zhangshichun** [ant-design/ant-design#3647]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:win10
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。
引入了upload组件，并试图进行跨域上传。
在headers中如下写道：
                                headers={{
                                    accessControlAllowOrigin: "\*",
                                    AccessControlAllowOrigin:“\*”,
                                    accessControlAllowMethods: 'POST',
                                    accessControlAllowHeaders: 'x-requested-with,content-type',
                                }}

#### 您期待的结果是:

可以正常跨域

#### 实际上的结果是:

报错： Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ohmyauthentic** [comment]
那是你服务器端写的有问题吧
