### ISSUE TITLE
关于修改项目primary color的问题（参考了历史issue，但还是没有解决，求帮助）

### ISSUE THREAD

**Issue by MichaelHong002** [ant-design/ant-design#3648]
首先说明一下我是刚学react，是个菜鸟，使用create-react-app创建了一个新项目，没有使用antd建议的dav-cli来创建，然后在“项目根目录”安装了npm install antd babel-plugin-import --save，就这样。

然后我想在本地项目里修改primary color，做了以下几个步骤：
1. 在"项目根目录\node_modules\antd\lib\style\themes\"中修改了default.less的@primary-color为#ff0000
2. 在“项目根目录“中修改了package.json，增加了代码："theme": {    "primary-color": "#ff0000"  }
先这样试了一下没有反应...还是默认的蓝色
然后我看到历史issue中说要在根目录下npm run release，然后我就在“项目根目录”下运行了npm run release，但收到如下错误，颜色依然也还是默认的蓝色。。。求帮助，多谢了！
![default](https://cloud.githubusercontent.com/assets/20024007/19834298/daac38e4-9e93-11e6-8c60-bd49de9418ff.JPG)

**Comment by yesmeck** [comment]
定制主题参考 https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme

create-react-app 现在不支持 less。

**Comment by MichaelHong002** [comment]
@yesmeck 谢谢！根据你给的链接，那就是要用antd-init来创建项目了，对吧？但官网建议用dav-cli，定制主题的方法应该和antd-init一样吧？
另外在问一句，我在安装babel-plugin-import后没有配置.babelrc文件，因为项目根目录下也没看到有，请问在哪里找到并配置这个.babelrc文件？不知道是不是因为我是用create-react-app创建项目的。谢谢！

**Comment by yesmeck** [comment]
现在推荐 dav-cli 来创建项目，不过定制主题方式还是一样的。

create-react-app 不支持自己配置 babel 和 webpack，这种问题跟 antd 无关的，最好上 stackoverflow 或者 segmentfault  上问。

**Comment by MichaelHong002** [comment]
@yesmeck 多谢了！
