### ISSUE TITLE
Table Expand Column Title Customization

### ISSUE THREAD

**Issue by jonioni** [ant-design/ant-design#36490]
### What problem does this feature solve?

Enable customization of table expand column title / header, e.g. enable an "Expand" action with the same "plus" icon.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/31494475/178573884-19561ca8-f206-44ac-b66f-162107656328.png">

Related requests: #35302, #35300

### What does the proposed API look like?

Have an `expandColumn` or `expandColumnTitle` option (of type `ReactNode`) added to the `expandable` API.

**Comment by jonioni** [comment]
Seems it'd require a change made to `rc-table`:

https://github.com/react-component/table/blob/525534913426b8ed998ebc2d1f7dc582cccd2d65/src/hooks/useColumns.tsx#L199

**Comment by losgif** [comment]
I think I can do it.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/36794
