### ISSUE TITLE
`value` attribute in DOM for `<Select>` element is not updating after selecting a dropdown item

### ISSUE THREAD

**Issue by cliffordfajardo** [ant-design/ant-design#36491]
### Reproduction link

[![Edit Bug on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-select-missing-name-attribute-forked-9b2pst?file=/src/App.tsx)

### Steps to reproduce
1.Choose a dropdown item from the `<Select>` element and observe that the `value` attribute of the `<input>` element  associated with the `<Select>` in the DOM does not get updated with the value that was selected ↓

Codesandbox: 
- https://codesandbox.io/s/antd-select-missing-name-attribute-forked-9b2pst?file=/src/App.tsx
https://user-images.githubusercontent.com/6743796/178594235-9a9aa5e0-f110-4975-82c0-461d2d82ca3a.mp4

A strange behavior I observed is that if you type into the `<Select>` input box, it will update the `value` attribute of the `<input`> element associated with the `<Select>` but as soon as you select an item from the dropdown the `value` attribute clears (see video above ↑)

</br>

### What is expected?
After I select a value from the dropdown, it should update the `value` attribute on the `<input>` element with the value I selected from the `<Select>` menu.

</br>

### What is actually happening?
When I select a dropdown value it does not update the `value` attribute value on the `<input>` element in the DOM.

</br>

## Why is this important?
1. Frameworks like `remix` and many other upcoming full stack javascript frameworks follow the HTML standard and rely on form elements.

2. When you submit an HTML form, the `name` attribute on the form elements (input, select etc ) is used to create a key inside the form object. For example, you can verify this by filling in the form in the codesandbox demo and calling the function below inside your browser developer tools:

```ts
const getFormData = () => {
  const formObject = new FormData(document.querySelector("#my-form") as HTMLFormElement) as any;
  const formData = Object.fromEntries(formObject);
  console.log(`form values`, formData);
};
getFormData() // call from javascript console after filling out form
```
Codesandbox: https://codesandbox.io/s/antd-select-missing-name-attribute-forked-tmlsg0?file=/src/App.tsx

https://user-images.githubusercontent.com/6743796/178577370-7d28378c-3036-41fc-ba49-80827c089176.mp4

3. When you submit an HTML form with attribute `method=get`, the native HTML form element does not find the `name` attribute associated with the ant's `<Select>` element so the name attribute is not being added to the URL
Demo URL (open the preview in a new tab by clicking "Open in New Window"):
  - Stackblitz URL:
     - code (click "Open in New Window" to see URL param updates): https://stackblitz.com/edit/node-6z19rg?file=package.json,app%2Froutes%2Findex.tsx
     - code preview URL: https://node-6z19rg--3000.local.webcontainer.io/

https://user-images.githubusercontent.com/6743796/178580314-55669e6b-29cf-4727-9016-83220cb7f798.mp4

4. Many people would like to use Ant's form element's for decorative purposes only and often cannot use the `<Form>` element from Ant. ([example stackblitz sandbox](https://stackblitz.com/edit/node-6z19rg?file=package.json,app%2Froutes%2Findex.tsx))
   - for example, with several newer fulllstack javascript frameworks like [Remix](https://remix.run/) and NextJS, they provide their own `<Form>` and on submit they use standard browser API/behaviors to extract the values of the form from the DOM so often ant's own `<Form>` isn't necessary as long as the outputted HTML of the react component follows standard browser behahvior
   ```ts
   // non-framework code; I'm showing
   const getFormData = () => {
       const formObject = new FormData(document.querySelector("#my-form")) ;
       const formData = Object.fromEntries(formObject);
       console.log(`form values`, formData);
      return formData
    };
   getFormData() 
   ```

## Related
- https://github.com/react-component/select/issues/791
- https://github.com/react-component/select/issues/790

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 18.0.0 |
| System | MacOS |
| Browser | Chrome latest version |

**Comment by cliffordfajardo** [comment]
CC @zombieJ @afc163

**Comment by afc163** [comment]
Select don't support native `value` property, there is even no <input /> element in dom when `showSearch={false}`.

Don't depend on dom attribute to get current value of fields, try React's way.

**Comment by cliffordfajardo** [comment]
> `<Select>` don't support native value property,
you're right  🤦‍♂️ - I should have rephrased my original comment.
However ant's `<Select>` does render a `<input>` when its outputted into the DOM.
In this case since its a input element, the bug seems to be that after selecting an option from `<Select>` the `<input>` value property is not getting updated. This is problematic when you submit a form, because when a form is submitted the standard HTML behavior is that the `<form>` will grab HTML form elements with a `name` and `value` to create the form data object. In this case since `value` attribute of the underlying `<input>` for the `<Select>` is not getting updated to reflect the selected value


https://user-images.githubusercontent.com/6743796/178746289-6232f2b7-ffcc-4047-afe6-8301ad68c30e.mp4






> there is even no <input /> element in dom when showSearch={false}

I am seeing an `<input>` element when `showSearch={false}` as well  (video shows)
Stackblitz Example: https://stackblitz.com/edit/react-ltsgbj?file=demo.js
