### ISSUE TITLE
警告：getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

### ISSUE THREAD

**Issue by cnfi** [ant-design/ant-design#3649]
#### 发生问题的环境是：

- antd 版本: ^2.0.0
- 操作系统及其版本: mac os
- 浏览器及其版本: chrome
#### 您做了什么？请提供尽可能详细的重现步骤。

引入了antd的Dropdown组件
https://ant.design/components/dropdown/# 中的第一个例子
#### 您期待的结果是:

像官网一样正常显示
#### 实际上的结果是:

Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
antd.min.js:21
并 Fork http://codepen.io/benjycui/pen/KgPZrE?editors=001 -->

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by yesmeck** [comment]
你在 ES6 的 class 里用了 getDefaultProps ？

**Comment by cnfi** [comment]
没有写getDefaultProps，仅仅是复制了demo里的代码而已。我找个地方重现下

**Comment by cnfi** [comment]
在codepen中尝试，确实没有报错，但是在我的开发环境中确实一直有警告：
```
index.js:20 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```
警告的大概意思是getDefaultProps只能用在React.createClass形式声明的组件中。看了下antd的Menu源码，也没有错 https://github.com/ant-design/ant-design/blob/master/components/menu/index.tsx

```
//line 59
static defaultProps = {
    prefixCls: 'ant-menu',
    className: '',
    theme: 'light',  // or dark
  };
```

贴下我的出错代码吧

```
import '../../node_modules/antd/dist/antd.min.css';
import React from 'react';
import { render } from 'react-dom';
import {Menu, Dropdown, Icon} from 'antd';

const menu = (
  <Menu>
    <Menu.Item key="0">
      <a href="http://www.alipay.com/">1st menu item</a>
    </Menu.Item>
  </Menu>
);

render(
  <Dropdown overlay={menu} trigger={['click']}>
    <a className="ant-dropdown-link" href="#">
      11111 <Icon type="down"/>
    </a>
  </Dropdown>,
  document.getElementById('appContainer')
);
```

webpack版本^1.13.2
做了externals
```
externals: {
    react$: 'React',
    'react-dom': 'ReactDOM',
    antd: 'antd'
  }
```
相关依赖：
```
"dependencies": {
    "antd": "^2.0.0",
    "react": "^15.3.1",
    "react-addons-shallow-compare": "^15.3.1",
    "react-addons-transition-group": "^15.3.1",
    "react-dom": "^15.3.1"
  }
```

求相关同学帮忙解决哈~项目开发中问题，必须解决

**Comment by benjycui** [comment]
只能尝试重装依赖。。。

还有问题就尝试提供个可重现的 repo

**Comment by cnfi** [comment]
问题解决了~
主要问题出在webpack的externals配置：

```
externals: {
    react$: 'React',
    'react-dom': 'ReactDOM',
    antd: 'antd'
  }
```
把react后面的$去掉即可

**Comment by afc163** [comment]
看着好奇怪，$ 是干什么用的？

**Comment by cnfi** [comment]
从alias中复制出来的。当初为了做性能优化，把react及插件全部映射到react-with-addons.min.js文件中了

```
alias: {
       'react-dom': 'react-dom/dist/react-dom.min.js',
       'react$': 'react/dist/react-with-addons.min.js'
    }
```

**Comment by ioslh** [comment]
@afc163 你好，我出现这个一样的问题；
我这里的操作是：直接在 HTML 中引用 antd 的 JS 链接。
1. 引用压缩版本（ https://unpkg.com/antd@2.10.4/dist/antd.min.js ） 控制台会出现这个 issue 中提到的警告信息；
2. 引用未压缩版本（ https://unpkg.com/antd@2.10.4/dist/antd.js ）则没有上述问题。

重现的 demo 参考 https://codepen.io/ioslh/pen/YQzMjo

希望能获得支持，非常感谢~

**Comment by Pines-Cheng** [comment]
碰到了同样的问题。@ioslh

**Comment by afc163** [comment]
Have no any clue..

**Comment by yesmeck** [comment]
我两个小时前看的时候也是有警告的，但是现在看没有了。

**Comment by afc163** [comment]
看这个 https://codepen.io/anon/pen/OgxoxQ

@ioslh 改了 codepen 。

**Comment by ioslh** [comment]
@afc163 我访问你改过的 codepen 也是会报那个错误的 😂

**Comment by yesmeck** [comment]
要全部用 min 或者非  min 版本，不然 react 内部的 `process.env.NODE_ENV` 判断会错掉。 

![screen shot 2017-06-26 at 19 13 09](https://user-images.githubusercontent.com/465125/27536845-88e3f5ca-5aa3-11e7-96f4-856039c0e2e1.png)

**Comment by ioslh** [comment]
@yesmeck 确实是这样可以解决，非常感谢！

**Comment by afc163** [comment]
@ioslh 我的 codepen 就是重现，你原先的 codepen 不报错了。

**Comment by dragonghy** [comment]
@yesmeck 非常感谢。life saver。

**Comment by jndxzqc** [comment]
这个问题有没有结论呢，我也碰到了一样的问题，antd@3.1.6，react@16.2.0

**Comment by ioslh** [comment]
react和antd统一用 min 或者非 min 版本

**Comment by catnipan** [comment]
@ioslh +1
我出现该错误的时候是 dll 打包的 react 没有使用min版本，而 antd 使用了。把 react 换到 min 版本就好了

**Comment by joket1999** [comment]
什么min非min，都是默认npm的包。只要webpack添加按需加载的配置，就会报这错。
['import', {
	'libraryName': 'antd',
	'libraryDirectory': 'es',
	'style': true
}]
