### ISSUE TITLE
table列同时设置filters和fixed属性，table本身设置了scroll滚动和getPopupContainer，过滤菜单显示异常。

### ISSUE THREAD

**Issue by furan495** [ant-design/ant-design#36499]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/shai-xuan-he-pai-xu-antd-4-21-6-forked-1w23wb?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

小屏幕请打开控制台或将列宽设置大些，让表格能滚动，点击过滤菜单即可复现

### What is expected?

正常展示过滤菜单并能随表格滚动而跟随触发节点

### What is actually happening?

展示异常跟随触发节点

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 17.x |
| System | mac |
| Browser | 谷歌最新版 |

**Comment by zombieJ** [comment]
`overflow` 的老大难问题，参考一下  #25190 哈~
