### ISSUE TITLE
Table 组件更新时子组件没有同步更新

### ISSUE THREAD

**Issue by netskyline** [ant-design/ant-design#365]
Table 有一个编辑按钮，点击时弹出 popover 组件进行编辑（popover 组件中是一些表单，Table 加载数据的时候同时设置了相应默认值），问题是，只要点开过一次这一行的 popover，那么这一行的这个popover 里面的表单值就一直是点击时显示出来的值了，翻页，过滤，删除等操作改变这行的数据时，popover中表单中的值一直不变，也就是说，Table 更新了，但是popover中的表单没有对应更新，，。

**Comment by yiminghe** [comment]
#336
