### ISSUE TITLE
RangePicker with showtime and special scope width, position of end time popup is abnormal

### ISSUE THREAD

**Issue by fayhy** [ant-design/ant-design#36507]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daterangepicker-popover-po54hl)

### Steps to reproduce

RangePicker with time, click start time, and then click end time

### What is expected?

before 4.20.0, it's fine

![expected](https://user-images.githubusercontent.com/35906690/178710934-b5baa27d-02ab-4b5f-91e0-780d7cc0e1ba.gif)

### What is actually happening?

![actually](https://user-images.githubusercontent.com/35906690/178710880-3dc6756d-984f-4994-9be4-f33bea6c197c.gif)

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 16.14.0 |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment]
It is similar to #35779
