### ISSUE TITLE
Menu中Item无法使用Dropdown组件

### ISSUE THREAD

**Issue by rui19921122** [ant-design/ant-design#3650]
- antd 版本: 2.0
- 操作系统及其版本: windowns 10
- 浏览器及其版本: chrome 54.0

#### 您做了什么？请提供尽可能详细的重现步骤。

我试图在Menu组件中的Item中添加Dropdown，但是浏览器报错，报错信息为
React.Children.only expected to receive a single React element child.

**Comment by nightInSummer** [comment]
更新之后我也遇到了这个问题，请问是怎么解决的。
