### ISSUE TITLE
当 Select 父级元素带有 display: inline-flex，收起下拉框时会导致相邻的行间元素跳动

### ISSUE THREAD

**Issue by liuyib** [ant-design/ant-design#36517]
### Reproduction link

[https://stackblitz.com/edit/react-nlmwkb?file=demo.js](https://stackblitz.com/edit/react-nlmwkb?file=demo.js)

### Steps to reproduce

1. 在 Select 外层容器上添加 display: inline-flex 样式
2. 在 Select 外层容器前面添加行间元素（如 span、label）
3. 点击 Select 框，然后失焦让下拉菜单收回

### What is expected?

重现步骤 2 中的行间元素“不跳动”

### What is actually happening?

重现步骤 2 中的行间元素“跳动”

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 17.0.2 |
| System | macOS12.3.1 |
| Browser | Chrome 103.0.5060.114 |

**Comment by liuyib** [comment]
录制了一个 bug 复现视频：

https://user-images.githubusercontent.com/38221479/178928697-4a271997-7ca6-4d54-805f-8ce2a61ccafe.mov

**Comment by zombieJ** [comment]
感觉可以

**Comment by zombieJ** [comment]
> > 感觉可以（没想到这都会有影响……）
> 
> 请问这个有人在跟进么？没有的话可以让我来提一个pr吗？

来吧，别客气~~

**Comment by li-jia-nan** [comment]
> > > 感觉可以（没想到这都会有影响……）
> > 
> > 
> > 请问这个有人在跟进么？没有的话可以让我来提一个pr吗？
> 
> 来吧，别客气~~

[#796](https://github.com/react-component/select/pull/796)

麻烦review一下，另外这个包更新之后，antd中的package是不是也要更新？

**Comment by MadCcc** [comment]
Fixed in https://github.com/react-component/select/pull/796
