### ISSUE TITLE
Dropdown组件在StrictMode 模式下控制台警告

### ISSUE THREAD

**Issue by HanShuai-me** [ant-design/ant-design#36513]
### Reproduction link

[![Edit antd reproduction template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-k835qf?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

1. 运行项目
2. 鼠标放在国际化图标上，显示下拉框
3. 控制台报警告

### What is expected?

消除这个警告

### What is actually happening?

控制台报警:
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Trigger which is inside StrictMode. Instead, add a ref directly to the element you want to reference

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 18.2.0|
| System | Windows |
| Browser | chrome 103.0.5060.114 |

**Comment by afc163** [comment]
trace #35361
