### ISSUE TITLE
Drawer component fills full screen and instantly goes to normal when mask=false

### ISSUE THREAD

**Issue by AndrewEastwood** [ant-design/ant-design#36510]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z5nbey?file=/index.js)

### Steps to reproduce

See my ignored case: https://github.com/ant-design/ant-design/issues/36423

### What is expected?

I'd expect that the drawer wont goes fulls screen rather sets as usual (same as when mask is on)

### What is actually happening?

The drawer fills full screen at the beginning when when mask is set to false

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18.2.0 |
| System | macOS 11.3.1 |
| Browser | Chrome 103.0.5060.53 |

**Comment by AndrewEastwood** [comment]
Bug:
https://user-images.githubusercontent.com/1483306/178732205-44f1100c-dda7-4349-ad6e-4cbbf6420756.mov

**Comment by AndrewEastwood** [comment]
awesome!

**Comment by hydraZty** [comment]
Talking about the flashing full screen?
