### ISSUE TITLE
<Tag /> 在关闭时是否可以把当前值也回传回去

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#3652]
现在在关闭`<Tag />`时，如果要获取被关闭`<Tag />`的值，会通过以下方法：
```
onCloseTag (val, e) {
	// some code
	// .......
},

render() {
	// some code
	// .......
	
	return (
		<Tag
			value={val}
			onClose={this.onCloseTag.bind(this, val)}
		 />
	);
}
```
这样的话，如果父组件每次`render`的，`bind`方法都会生成一个函数，感觉这样有点纠结....

而如果在`onClose`事件回调中，能够将当前`<Tag />`的`value`做为第二个参数传入的话，感觉相对来说顺畅些，但不知有是否符合`antd`设计原则。代码如下：
```
onCloseTag (e, val) {
	// some code
	// .......
},

render() {
	// some code
	// .......

	return (
		<Tag
			value={val}
			onClose={this.onCloseTag}
		 />
	);
}
```

**Comment by benjycui** [comment]
事实上，`Tag` 并没有 `value` 属性。

这个算是你的自定义属性，所以相应的行为还是自行处理吧。

**Comment by benjycui** [comment]
> 如果父组件每次render的，bind方法都会生成一个函数，感觉这样有点纠结....

可以考虑把这些函数缓存。

**Comment by ystarlongzi** [comment]
哦哦，对，是的。我傻了。
谢谢！
