### ISSUE TITLE
table嵌套子表格时子表格数据超过1000条展开收起非常卡顿

### ISSUE THREAD

**Issue by keunone** [ant-design/ant-design#36524]
### What problem does this feature solve?

demo地址：https://ttt02c.csb.app/

### What does the proposed API look like?

性能优化

**Comment by afc163** [comment]
1000 条用户也基本没法阅读了，建议分页或开启 https://ant.design/components/table-cn/#components-table-demo-virtual-list

**Comment by afc163** [comment]
https://codesandbox.io/s/qian-tao-zi-biao-ge-antd-4-21-6-forked-yxq80d?file=/demo.js
