### ISSUE TITLE
组件 API 文档参数错误

### ISSUE THREAD

**Issue by ZhaoruiGuang** [ant-design/ant-design#36526]
### Reproduction link

[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce

打开上面的 ant 中文文档，查看 “Tabs 标签页“组件的文档底部的 API 介绍，Tabs 参数表里的第一个参数 ”activeKey“ 参数名错误，，实际使用中不生效，应为 "activedKey"

### What is expected?

activedKey

### What is actually happening?

activeKey

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 16.8.6 |
| System | MacOS |
| Browser | chrome |

**Comment by CNFeffery** [comment]
没问题啊：

![image](https://user-images.githubusercontent.com/49147660/178993825-1950803b-c46c-4982-89fe-a555d3c96789.png)
![image](https://user-images.githubusercontent.com/49147660/178993850-8219e242-d136-4f00-9564-5ae9bc807953.png)

**Comment by leviegu** [comment]
[文档是正确的，可以点击看下](https://codesandbox.io/s/adoring-bush-vndn4w?file=/src/App.js)

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/37723532/179000739-5917e09b-42a3-412f-9933-61ba10c02673.png">
