### ISSUE TITLE
Typography.Paragraph中设置rows(最多显示的行数),windows与mac系统不兼容

### ISSUE THREAD

**Issue by mingsen-Luo** [ant-design/ant-design#36535]
### Steps to reproduce

设置省略号行数为 3 行，在Windows 上打开只展示 2 行，在mac上打开展示 3 行

### What is expected?

期望两个系统设置的省略号行数一致

### What is actually happening?

之际结果设置的 行数只与 Mac 保持一致

| Environment | Info |
| --- | --- |
| antd | 4.16.3 |
| React | 16.9.0 |
| System | windows11 |
| Browser | 103.0.5060.114（正式版本） （64 位） |

**Comment by LiKJJ** [comment]
demo 来链接地址：https://uhr93b.csb.app/

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35000#issuecomment-1097528978

**Comment by earthaYan** [comment]
@afc163 https://codesandbox.io/s/zhe-die-shou-qi-duan-luo-qnw7q0?file=/src/TextMore.tsx 这个可以复现上述问题

**Comment by afc163** [comment]
应该和 https://github.com/ant-design/ant-design/issues/47167 是类似的问题，合并讨论。
