### ISSUE TITLE
页面缩放情况下，Radio 的蓝点有时候不居中

### ISSUE THREAD

**Issue by huajiang19** [ant-design/ant-design#36532]
### Reproduction link

[https://ant.design/components/radio/#API](https://ant.design/components/radio/#API)

### Steps to reproduce

1. 设置浏览器zoom 80% or 120%
2. 有些radio的蓝点不会居中显示

### What is expected?

蓝点居中显示

### What is actually happening?

1. 设置浏览器zoom 80% or 120%
2. 有些radio的蓝点不会居中显示

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 17 |
| System | windows |
| Browser | edge |

**Comment by afc163** [comment]
有 gif 或者录屏么？

**Comment by huajiang19** [comment]
您好，这是来自QQ邮箱的自动回复邮件。我已收到你的邮件，谢谢。

**Comment by huajiang19** [comment]
> 有 gif 或者录屏么？

![image](https://user-images.githubusercontent.com/62044903/179144460-83a775d6-fedc-465e-a7b8-622814c6cfdd.png)

**Comment by afc163** [comment]
代码上已经符合居中对齐逻辑了，各种不同操作系统不同浏览器下的不同缩放百分比下的场景，基本没有办法做到完美对齐。
