### ISSUE TITLE
Drawer 组件在 antd 4.x 时，外部显示内部 visible 为 true 的 Drawer 时会没有打开动画

### ISSUE THREAD

**Issue by Canight** [ant-design/ant-design#36543]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-21-6-forked-1vyjds?file=/demo.js)

### Steps to reproduce

点击 Open

### What is expected?

出现 Drawer 打开动画

### What is actually happening?

抽屉直接突兀出现，antd升级时发现，3.0 存在动画

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.14.0 |
| System | macOS Monterey |
| Browser | 版本 103.0.5060.114（正式版本） (arm64) |

---
antd升级时发现，3.0 存在动画

**Comment by afc163** [comment]
为啥要这么用呢，这个不是我们推荐的使用方式，不保证效果会符合预期。

**Comment by afc163** [comment]
确认是 bug 了 https://github.com/ant-design/ant-design/issues/36545#issuecomment-1185361234

不过还是不推荐这么用。

**Comment by izhouteng** [comment]
你为啥要这么写......？

像这种写法 `{ visible && <Drawer /> }` visible为false的话，React立马会把元素移除，怎么可能有动画。。。

你改成这样就好了啊。。。
```
     <Drawer
        title="Basic Drawer"
        placement="right"
        onClose={onClose}
        visible={visible}
      >
        <p>Some contents...</p>
        <p>Some contents...</p>
        <p>Some contents...</p>
      </Drawer>
```

**Comment by Canight** [comment]
> 你为啥要这么写……？
> 
> 这种写法`{ visible && <Drawer /> }`可见为假话，React 立马带元素移除，怎么可能有动画。。。
> 
> 你改成这样就好了啊。。。
> 
> ```
>      <Drawer
>         title="Basic Drawer"
>         placement="right"
>         onClose={onClose}
>         visible={visible}
>       >
>         <p>Some contents...</p>
>         <p>Some contents...</p>
>         <p>Some contents...</p>
>       </Drawer>
> ```

这只是一个例子，意思是外部解耦的参数来控制的时候，会失去打开动画，之前是根据特性这么用的，但是在4.9.2到4.9.3的时候这个特性消失了（4.9.2 之前这么使用是有动画的，内部有另外的控制），这种变更我在更新log里也没看到，很多项目是基于这个写的，如果是修复了这个BUG那OK的，我们之后根据新的来，如果是之前有预埋这种逻辑，然后下掉是不是要说一声

**Comment by Canight** [comment]
> 确认是 bug 了[#36545 (comment)](https://github.com/ant-design/ant-design/issues/36545#issuecomment-1185361234)
> 
> 不过还是不推荐这么用。

👌

**Comment by Canight** [comment]
> 为啥要用呢？

之前很多逻辑顺便使用了这个特性进行了内外参解耦，进行重构成本较大，如果确认以后不会恢复这个特性，我们这边是要安排时间进行重构，所以我提前来沟通

**Comment by yinhunfeixue** [comment]
用<Modal key={****.id} >  也会失去动画
