### ISSUE TITLE
Drawer 组件在 antd 4.9.2 -> 4.9.3 时丢失特性

### ISSUE THREAD

**Issue by Canight** [ant-design/ant-design#36545]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-21-6-forked-1vyjds?file=/demo.js)

### Steps to reproduce

点击 Open

### What is expected?

出现 Drawer 打开动画

### What is actually happening?

抽屉直接突兀出现，经过排查，4.9.2 -> 4.9.3 时丢失特性

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.14.0 |
| System | macOS Monterey |
| Browser | 版本 103.0.5060.114（正式版本） (arm64) |

---
antd升级时发现，经过排查，4.9.2 -> 4.9.3 时丢失特性

**Comment by zombieJ** [comment]
看起来 Drawer 默认渲染时如果 `visible` 是 `true` 就不展示动画应该是符合预期的，我 blame 确认一下

**Comment by li-jia-nan** [comment]
> 看起来 Drawer 默认渲染时如果 `visible` 是 `true` 就不展示动画应该是符合预期的，我 blame 确认一下

这个没什么问题吧，正常情况下的 visible 是应该传一个动态的布尔值，他这个demo中的visible属性值是写死的，然后整个Drawer组件用一个&&运算符控制是否渲染的，本来就没有动画吧

**Comment by Canight** [comment]
> > 看起来 Drawer 默认渲染时如果 `visible` 是 `true` 就不展示动画应该是符合预期的，我 blame 确认一下
> 
> 这个没什么问题吧，正常情况下的 visible 是应该传一个动态的布尔值，他这个demo中的visible属性值是写死的，然后整个Drawer组件用一个&&运算符控制是否渲染的，本来就没有动画吧

主要是4.9.3之前是有的，很多项目代码基于此开发，恢复这个动画成本比较大，得讨个说法

**Comment by yinhunfeixue** [comment]
即使用key控制modal，也会失去动画。
