### ISSUE TITLE
Form.Item typescript的验证

### ISSUE THREAD

**Issue by huang6349** [ant-design/ant-design#3654]
#### 发生问题的环境是：

- antd 版本:2.2.0
- 操作系统及其版本:win10
- 浏览器及其版本:GOOGLE Chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

在升级antd2.2.0之前使用书写一一段这样这代码是没有问题的

```
                <Form.Item { ...formItemLayout } label="登陆帐号">
                  {
                    getFieldDecorator('account', {
                      initialValue: '',
                      rules: [
                        { min: 5, message: '帐号最少为5个字符长度' },
                      ]
                    })(<Input type="text" placeholder="请输入帐号" disabled={ this.props.loading } />)
                  }
                </Form.Item>
```

[代码](https://github.com/huang6349/Pictures/blob/master/error/QQ%E5%9B%BE%E7%89%8720161031110215.png)

升级antd2.2.0后，发现这段代码Form.Item的ts验证发生了错误，提示

Property 'children' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<FormItem> & FormItemProps & { children?: ReactElem...'.

[错误](https://github.com/huang6349/Pictures/blob/master/error/QQ%E5%9B%BE%E7%89%8720161031110313.png)

**Comment by thewei** [comment]
我在使用 Tabs 时，也会报这个错误

**Comment by afc163** [comment]
fixed in #3653
