### ISSUE TITLE
table(树形) 组件设置列左固定 文字省略会引起ui展示异常

### ISSUE THREAD

**Issue by SaiyanGuo** [ant-design/ant-design#36541]
### Reproduction link

[https://stackblitz.com/edit/react-6uhc2f?file=demo.js](https://stackblitz.com/edit/react-6uhc2f?file=demo.js)

### Steps to reproduce

设置 ellipsis: true 和 fixed: true 同时有父子节点

### What is expected?

首列行内文字不换行

### What is actually happening?

首列行内文字换行

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 17.x |
| System | mac |
| Browser | edge |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/36496  , wait for next patch.
