### ISSUE TITLE
Autosized textarea is bouncing when dynamically displayed

### ISSUE THREAD

**Issue by CracANut** [ant-design/ant-design#36556]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/textarea-antd-4-21-6-forked-k0h42p)

### Steps to reproduce

1. Click on the "click me" button
2. Notice the textarea is slightly bigger than it should and then comes back the expected size

### What is expected?

The textarea should be displayed with the correct size directly

### What is actually happening?

The textarea is appearing a bit taller than it should and then it gets the expected size.

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 103.0.5060.114 |

---
If the value of the textarea is on multiple lines, the textarea appears first too small and then it gets the expected size.

**Comment by afc163** [comment]
https://github.com/react-component/textarea/pull/15 @zombieJ 看看能不能解决？

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/35632

**Comment by ankha0109** [comment]
https://codesandbox.io/s/n124nd
This one is the same.

**Comment by JarvisArt** [comment]
https://github.com/react-component/textarea/pull/20

**Comment by CracANut** [comment]
Is there any update on this issue? 
Do you have an idea when the linked merge request could be approved?

Thank you.

**Comment by jAtlasCode** [comment]
Dealing with same issue in some production apps...
