### ISSUE TITLE
AutoComplete 建议添加搜索的 不区分大小写 

### ISSUE THREAD

**Issue by Vsion** [ant-design/ant-design#3655]
#### 发生问题的环境是：

- antd 版本:截止目前最新 2016/10/31
- 操作系统及其版本: win10 
- 浏览器及其版本: chrome 版本 46.0.2490.86 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。
用 AutoComplete 做了一个搜索框

#### 您期待的结果是:
不区分大小写

#### 实际上的结果是:
我只是把datasource 给做了 处理 结果,  当然只是操作了汇总的数据

**Comment by yesmeck** [comment]
> 我只是把datasource 给做了 处理 结果, 当然只是操作了汇总的数据

没看懂。

自己写 onChange 的时候不区分大小写即可。

**Comment by Vsion** [comment]
@yesmeck 比如说 我input 里面输入 了 t , 但是我要datasource 中 带有大小写 t T的 都列出来, 怎么做?

**Comment by yesmeck** [comment]
栗子 http://codepen.io/yesmeck/pen/EgBeYZ

另外使用问题最好到 stackoverflow 或者 segmentfault 上提问，如果在 segmentfault 上可以邀请我回答。

@afc163 @benjycui 这个是不是可以文档上加个 demo，或者说明下 AutoComplete 跟 Select 的 API 是一样的。

**Comment by Vsion** [comment]
![image](https://cloud.githubusercontent.com/assets/11804448/19845225/b272cbea-9f6f-11e6-8699-74212b389a15.png)
不好使 啊,  以我的理解是 datasource 是筛选的集合, 但是出来结果的集合必须是 indexOf(value) > -1才有,  如图我这里完全改为和你一样的代码的时候 并不能出现我要的效果啊

**Comment by yesmeck** [comment]
没看懂你的需求，你可以用 codepen 给个例子。

**Comment by benjycui** [comment]
@yesmeck 在答疑的过程中，觉得文档那里可以改进，直接修改就好。

**Comment by Vsion** [comment]
我要的就是你在codepen中的结果,  但是在我这里不能用啊,  不知道为什么, 难道是版本问题? 
就是 我当前的datasource 是 ["Tab3", "Tab4", "测试2级tab", "Tab2"]  根据小写 t 筛选的, 但是出来的结果 只有 arr[2]
所以我的理解就是 datasource 是一个搜索集合 然后 onkeyup 的时候 只有 indexOf(value) > -1的结果进行展示

**Comment by Vsion** [comment]
我是 上周4拉的ant design @yesmeck   有改动吗

**Comment by yesmeck** [comment]
`dataSource`  是指要在下拉框中展示的数据。

周五有新版本发布，你可以尝试升级下。

最好是你提供有问题的代码。

**Comment by Vsion** [comment]
果然 = = 
之前的menu 的 openKey  onClose onOpen 已经欺骗过我一次了 = =

**Comment by Vsion** [comment]
![image](https://cloud.githubusercontent.com/assets/11804448/19846518/005d621a-9f7b-11e6-80da-f8453f8a26f5.png)

还是不行啊 ..

在setState 之后 依然是只有 一条 带小写的数据
![image](https://cloud.githubusercontent.com/assets/11804448/19846532/1a8b2d48-9f7b-11e6-9f46-f5757af1d849.png)

**Comment by yesmeck** [comment]
用 codepen 提供下可以重现的 demo，你这样我没法帮你看的。http://codepen.io/yesmeck/pen/EgBeYZ

**Comment by Vsion** [comment]
![image](https://cloud.githubusercontent.com/assets/11804448/19846706/8fedaa42-9f7c-11e6-9aa1-d721add682ee.png)
这.....    我刚开始以为是环境问题, 因为在你的 codepen中, 用我的代码也没问题, 在我的项目中改为你的代码 也没问题,   结果  ....   
![image](https://cloud.githubusercontent.com/assets/11804448/19846724/b090f632-9f7c-11e6-926c-6574bf1a5a0b.png)
官方文档里面压根 没有这个属性  = =

**Comment by yesmeck** [comment]
@Vsion 是的，我前面也说了，这里文档需要补一下。

**Comment by Vsion** [comment]
麻烦 留一个 stackoverflow 或者 segmentfault 的提问方式(链接等) 如果之后碰到问题 可以去提问

**Comment by yesmeck** [comment]
segmentfault 加上 antd 的标签即可，我 segmentfault  id 跟我 github 一样，急的话可以邀请我回答。

**Comment by Vsion** [comment]
麻烦 留一个 stackoverflow 或者 segmentfault 的提问方式(链接等) 如果之后碰到问题 可以去提问

**Comment by Vsion** [comment]
好的 谢谢
