### ISSUE TITLE
Table同时使用rowSelection和rowKey报错

### ISSUE THREAD

**Issue by qiang47199** [ant-design/ant-design#36553]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-xuan-ze-antd-4-21-6-forked-lx7xze?file=/demo.js:1582-1594)

### Steps to reproduce

直接打开看log就有错误。

### What is expected?

期望可以正常使用，支持rowSelection和rowKey属性同时使用

### What is actually happening?

TypeError
Cannot read properties of undefined (reading 'disabled')

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 16.14.0 |
| System | mac |
| Browser | 谷歌 |

---
在此 ( https://codesandbox.io/s/97djff  )基础上的Table增加自定义rowKey属性就会报错
rowKey={(record) => {
   return record.key + Math.random().toString(36);
}}

**Comment by afc163** [comment]
rowKey 应该稳定。

**Comment by qiang47199** [comment]
> rowKey 应该稳定，不应该加 Math.random() 。

我的应用场景比较特殊会存在同样的key值

**Comment by qiang47199** [comment]
> rowKey 应该稳定，不应该加 Math.random() 。

既然有这种属性为啥就不能支持呢？明显就是问题

**Comment by qiang47199** [comment]
> rowKey 应该稳定，不应该加 Math.random() 。

@afc163 有什么其他办法可以解决？

**Comment by afc163** [comment]
> 我的应用场景比较特殊会存在同样的 key 值

我建议对数据做处理，把相同的 key 先解决掉。
