### ISSUE TITLE
Calendar日历组件切换月份的时候会触发onSelect事件

### ISSUE THREAD

**Issue by Onion17** [ant-design/ant-design#36578]
### Reproduction link

[https://github.com/Onion17/antd-Calendar-iss](https://github.com/Onion17/antd-Calendar-iss)

### Steps to reproduce

右上角切换月份的时候，会同时触发onPanelChange，onSelect，onChange三个事件

### What is expected?

onPanelChange事件触发的时候，不要触发onSelect事件

### What is actually happening?

onPanelChange事件触发的时候，触发了onSelect事件，导致onSelect事件中弹窗功能会在切换月份的时候触发

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.0 |
| System | Mac os 12.4  |
| Browser | Microsoft Edge 版本 103.0.1264.62 |

---
用户点击具体日期触发onSelect事件出现弹窗，为该日期绑定日程，但是在切换月份的时候，触发了onSelect事件，导致切换月份也会有弹窗出现

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28046#issuecomment-758540659

**Comment by hundanwan** [comment]
同问题，解决了吗

**Comment by flashclub** [comment]
同问题，解决了吗
另外点击日期时会触发 dateFullCellRender ，怎么禁止触发呢

**Comment by afc163** [comment]
Duplicate of #39801
