### ISSUE TITLE
table(树形) 组件首列文字省略样式异常

### ISSUE THREAD

**Issue by SaiyanGuo** [ant-design/ant-design#36583]
### Reproduction link

[https://stackblitz.com/edit/react-6uhc2f?file=package.json,demo.js](https://stackblitz.com/edit/react-6uhc2f?file=package.json,demo.js)

### Steps to reproduce

创建多层父节点数据

### What is expected?

正常展示文字省略样式

### What is actually happening?

文字省略样式展示异常

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.x |
| System | mac |
| Browser | edge |

**Comment by afc163** [comment]
4.20.x 是好的：https://stackblitz.com/edit/react-6uhc2f-p9lrej?file=package.json,demo.js

**Comment by afc163** [comment]
改了一处小问题，引发好几个问题。。。[头疼]

**Comment by Wxh16144** [comment]
> 

![修水管](https://user-images.githubusercontent.com/32004925/179725822-66b688ab-553b-4e44-a35e-84fd1ccea31e.gif)


> 改了一处小问题，引发好几个问题。。。[头疼]

**Comment by afc163** [comment]
不对，4.20.1 也是错的。

<img width="1331" alt="图片" src="https://user-images.githubusercontent.com/507615/179888521-34a60de6-6fde-4749-82ca-f202a9fe10a3.png">

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/pull/36215

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/326978e7368b6f8e1b223e0c672b5530a82aed10#r77475770
