### ISSUE TITLE
overflowedIndicator's  description?（It will fail in some ways，The document description doesn't seem to be detailed）

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#36587]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6hty97?file=/index.js)

### Steps to reproduce

in index.css   // App.css——>  display:flex

### What is expected?

overflowedIndicator true

### What is actually happening?

overflowedIndicator false

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.2.0 |
| System | Windows10 |
| Browser | Chrome105.0.5148.2 |

---
I think we should note the problems that will fail in some cases in the document. By the way, we should mention a simple implementation of overflowindicator to avoid problems.

**Comment by RSS1102** [comment]
and When I expand my screen, he can't respond back and reset the `menu`.
![image](https://user-images.githubusercontent.com/81673017/179707274-029480e3-2270-4574-b7aa-2a37a4230d42.png)

**Comment by RSS1102** [comment]
i use your  CodeSandbox ,but i can't success.sorry.
https://codesandbox.io/s/6hty97?file=/index.js
can you see it what i error?

**Comment by afc163** [comment]
4.16.13 ✅：https://codesandbox.io/s/sweet-einstein-kk7k8m?file=/src/App.js
4.21.7❌：https://codesandbox.io/s/thirsty-monad-c906p8?file=/src/App.js

Something wrong was introduced in new version of antd. cc @zombieJ

**Comment by zombieJ** [comment]
flex 布局内部元素宽度设置一下 `min-width`，否则游览器不知道基准是什么：
https://codesandbox.io/s/antd-reproduction-template-forked-8et3uc?file=/index.css

**Comment by RSS1102** [comment]
> flex 布局内部元素宽度设置一下 `min-width`，否则游览器不知道基准是什么： https://codesandbox.io/s/antd-reproduction-template-forked-8et3uc?file=/index.css
> 
> Menu 现在是贪婪的，先占尽可能多的空间再减回去以减少额外的 renderTimes，过去是全减了一个个加回来。

好的，我尝试一下。

**Comment by zombieJ** [comment]
我文档里加一下
