### ISSUE TITLE
Select 组件的下拉框在 Drawer 组件中scroll事件穿透

### ISSUE THREAD

**Issue by jamesxwang** [ant-design/ant-design#36585]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-pond-8ilepf?file=/src/App.js)

### Steps to reproduce

1. Open the drawer
2. Open the Select component
3. Scroll the drawer.

### What is expected?

Select Option content fixed to the Select box

### What is actually happening?

dropdown fixed to screen
<img width="681" alt="WeChatWorkScreenshot_acd063c0-8791-4b9f-b193-580865bb4aaa" src="https://user-images.githubusercontent.com/36892657/179680489-aee8b6e6-e887-481b-8ebe-95b9733eaed9.png">

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.0.0 |
| System | MacOS 12.4 |
| Browser | Chrome Version 103.0.5060.114 (Official Build) (arm64) |

**Comment by MadCcc** [comment]
Scroll is not locked when Select is open. Your problem is more like the position of Select popup, and `getPopupContainer` can solve it.
Example: https://codesandbox.io/s/amazing-sound-lwtxy6?file=/src/App.js
