### ISSUE TITLE
Image.PreviewGroup 相册模式不能键盘上下/左右切换图片；页码不显示

### ISSUE THREAD

**Issue by dawpf** [ant-design/ant-design#36586]
### Reproduction link

[https://ant-design.gitee.io/components/image-cn/#components-image-demo-preview-group-visible](https://ant-design.gitee.io/components/image-cn/#components-image-demo-preview-group-visible)

### Steps to reproduce

拷贝 Image 组件相册模式代码至本地，无法实现功能

### What is expected?

期望功能正常使用

### What is actually happening?

不能键盘上下/左右，切换图片；页码不显示

| Environment | Info |
| --- | --- |
| antd | 4.15.4 |
| React | 17.0.2 |
| System | macOS 12.3.1 M1 |
| Browser | chrome版本 103.0.5060.114（正式版本） (arm64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/36607
