### ISSUE TITLE
Carousel 在被缩放后导致宽度计算错误

### ISSUE THREAD

**Issue by jerrybendy** [ant-design/ant-design#3659]
这应该是 react-slick 的一个 BUG，求教下有没有什么好的解决办法 

#### 发生问题的环境是：

- antd 版本:  v2.2.0
- 操作系统及其版本:  OS X 10.11
- 浏览器及其版本:  Chrome 53.0

#### 您做了什么？请提供尽可能详细的重现步骤。

把轮播图组件（Carousel）放入到带有 `transform: scale(xxxx)` 的元素内部，会导致轮播图内部获取到的宽度有误。实际获取到的宽度为 scale 缩放后的元素大小，所以就会导致元素的尺寸不正确。

#### 您期待的结果是:

可以和缩放前的显示结果保持一致

#### 可重现的在线演示

具体可以看下面的演示：

[http://codepen.io/jerrybendy/pen/ozrJpM?editors=0110](http://codepen.io/jerrybendy/pen/ozrJpM?editors=0110)

**Comment by afc163** [comment]
需要去给 react-slick PR~

**Comment by jerrybendy** [comment]
英文不好，怕问题描述不清楚 😅

**Comment by afc163** [comment]
react-slick 感觉已经弃坑了。https://github.com/akiran/react-slick/issues/824

**Comment by kyriejoshua** [comment]
LZ 还在吗……
我是在 render 前拿到 scale ，然后让 slick 放大 (1 / scale) 倍去计算正确的宽度，手动 render，然后在 didupdate 里面去恢复 slick 的 scale 为 1.
这个方法在 chrome 下没问题，在 IE 11 及以下宽度计算有问题。目前还没找到办法解决。
