### ISSUE TITLE
ProComponents EditableProTable组件怎么获取编辑好的表格数据内容？？？？？？？求助

### ISSUE THREAD

**Issue by 666-arch** [ant-design/ant-design#36591]
### Reproduction link

[https://procomponents.ant.design/components/editable-table#api](https://procomponents.ant.design/components/editable-table#api)

### Steps to reproduce

ProComponents EditableProTable组件怎么获取编辑好的表格数据内容？？？？？？？求助

### What is expected?

ProComponents EditableProTable组件怎么获取编辑好的表格数据内容？？？？？？？求助

### What is actually happening?

ProComponents EditableProTable组件怎么获取编辑好的表格数据内容？？？？？？？求助

| Environment | Info |
| --- | --- |
| antd | 4.8.6 |
| React | 17.0.1 |
| System | window 10  |
| Browser | chrome |

---
ProComponents EditableProTable组件怎么获取编辑好的表格数据内容？？？？？？？求助

**Comment by MadCcc** [comment]
procomponents 相关可以去 procompoennts 提问，另外用法可以开 discussion，并不是 issue

**Comment by beijipc** [comment]
const mainProdFormRef = useRef<EditableFormInstance>();

<EditableProTable
editableFormRef={mainProdFormRef}


mainProdFormRef.current?.getRowsData()
