### ISSUE TITLE
popover 组件内部表单会自动保存上次加载的或输入的值。

### ISSUE THREAD

**Issue by netskyline** [ant-design/ant-design#366]
popover 组件弹出后，其内部表单会自动保存上次加载的或输入的值，实际中需要重新加载新的赋值，和这个问题相关 #365

**Comment by yiminghe** [comment]
popover title overlay 属性同步更新了么

**Comment by netskyline** [comment]
title 属性是静态文本，不需要更新。

两个问题都关闭了啊。请问新版解决了吗？

**Comment by kevyu** [comment]
这个应该是因为form中的值是通过state传入的，一个解决方法是，加一个状态判断，每次popover关闭后unmount掉，类似：
```js
{this.state.isNotPopover && <Popover />}
```
感觉组件最好做成dumb的。

**Comment by kevyu** [comment]
这个应该不是popover的问题，而是form使用方法的问题，在modal里面使用form，也可能会出现这样的问题。

**Comment by netskyline** [comment]
不嵌套 Form ，直接使用表单也是这个情况，modal 和 popover 这些组件中用到组件的需求肯定是有的，有什么办法绕过这个问题呢？多谢。

**Comment by kevyu** [comment]
不知道你具体的应用场景，如果使用state存储form数据的话，一个方法是保证每次打开的都是新的modal或者overlay，另一个是通过componentWillReceiveProps修改state。

**Comment by netskyline** [comment]
Table 组件中最后一列是一些操作链接，点击后弹出对应的组件进程操作，UsersEdit 是我封装的一个组件，里面使用 Popover 弹出表单进行编辑，问题是 Table 更新后，对应行里面的 UsersEdit 还是上一次的，没有同步更新

  renderAction(text, record, index) {
    let data = { ........ };
    return (
      <div>
        <UsersEdit data={data} />&nbsp;&nbsp;
      </div>
    );
  }

const columns = [
     …………
      {title: '操作', dataIndex: '', key: 'x2', width: 70, render: this.renderAction}
    ];

<Table columns={columns} dataSource={this.state.dataSource} />

**Comment by kevyu** [comment]
@netskyline 这个要先看一下renderAction方法的record是不是还是原来的值吧，估计需要在UsersEdit中添加componentWillReceiveProps，最好把UsersEdit发出来看一下。

**Comment by netskyline** [comment]
以 UsersRenewals 组件为例吧，这个组件代码少。

Users 组件：
![qq20151022-2](https://cloud.githubusercontent.com/assets/2669032/10657194/3f767a42-78ba-11e5-8470-dd4d3244d7a6.png)

 UsersRenewals 组件：
![qq20151022-1](https://cloud.githubusercontent.com/assets/2669032/10657205/600d001e-78ba-11e5-829c-50beff9dba86.png)

**Comment by netskyline** [comment]
好像 Table 组件更新的时候没有重新生成 Action 列，

**Comment by kevyu** [comment]
UsersRenewals 组件：
```js
getInitialState() {
  return {
    isVisiable: false
  }
}
getContent() {
  return (
     <div>{this.state.isVisible && <div>...</div>}</div>
  )
}
onVisibleChange(visible) {
   this.setState({
     isVisble:visible 
  })
}
```

这样试试。

**Comment by netskyline** [comment]
这些直接就不显示 Popover 的 Content 了，默认 this.state.isVisible == flase 不会执行 && 后面的语句的。

测试过了，

**Comment by netskyline** [comment]
还是感觉 Table 组件更新的时候没有重新 rander 使用 render 函数生成的列，
