### ISSUE TITLE
Image.PreviewGroup 相册模式不能使用键盘查看上一张下一张图片；页码不显示

### ISSUE THREAD

**Issue by dawpf** [ant-design/ant-design#36607]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-k6wytm?file=/index.js)

### Steps to reproduce

完整引入示例代码，不能使用键盘的上下/左右键切换图片；顶部页码显示异常；preview属性中自定义countRender不生效

### What is expected?

组件功能正常显示

### What is actually happening?

不能使用键盘的上下/左右键切换图片；顶部页码显示异常；preview属性中自定义countRender不生效

| Environment | Info |
| --- | --- |
| antd | 4.15.4 |
| React | 17.0.2 |
| System | mac OS M1 |
| Browser | Chrome 版本 103.0.5060.114（正式版本） (arm64) |

---
antd最新版本没有这个问题，希望能在4.15.4中修复

**Comment by afc163** [comment]
不可能在已发布的版本中修复，请升级 antd。

**Comment by dawpf** [comment]
啊啊啊啊啊

**Comment by FanFanJUN** [comment]
使用previewType中 current属性 监听键盘左右键 自己实现
