### ISSUE TITLE
visible open API 统一至 open

### ISSUE THREAD

**Issue by yykoypj** [ant-design/ant-design#36609]
### What problem does this feature solve?

所有 visible  & open 都统一成 open 降低开发者记忆成本,涉及组件：
1. Tooltip (defaultVisible, onVisibleChange)
2. Modal
3. Dropdown (onVisibleChange)
4. Drawer
5. Popover (Tooltip的关联组件)
6. Popconfirm (Popover的关联组件)

以下组件需要确认一下：
1. Slider 的 tooltipVisible
2. Tag 的visible，这个语义上感觉不应该改
3. Table 的filterDropdownVisible

### What does the proposed API look like?

如果统一使用open，那状态变更的是否仍使用onVisibleChange，这个可能需要确认一下

### PR List
- Tags
  - [x] **v4 Deprecated warning** #36934
  - [x] **v5 Clean up** #36671
  - [ ] **Compatible package update**
- Slider
  - [x] **v4 Deprecated warning** #37000
  - [x] #37043
  - [ ] **Compatible package update**
- Table
  - [x] **v4 Deprecated warning** #37026
  - [x] #36747
  - [ ] **Compatible package update**
- Drawer
  - [x] **v4 Deprecated warning** #37047
  - [x] #36750
  - [ ] **Compatible package update**
- Modal
  - [x] **v4 Deprecated warning** #37084
  - [x] #36774
  - [ ] **Compatible package update**
- Dropdown
  - [x] **v4 Deprecated warning** #37232
  - [x] #36799 
  - [ ] **Compatible package update**
- Tooltip
  - [x] **v4 Deprecated warning** #37241
  - [x] #36807
  - [ ] **Compatible package update**

**Comment by afc163** [comment]
Tag 的 `visible` 没啥用，可以废弃掉，建议用 `visible && <Tag />`。

**Comment by turbo1128** [comment]
## dsfjklsd
## dsfjklsd
## dsfjklsd
## dsfjklsd

**Comment by afc163** [comment]
Slider 的所有 tooltipXxx 直接收敛到 `<Slider tooltip={{ ... }} />` 里直接透传，原先的属性都废弃掉。

**Comment by zombieJ** [comment]
1. 见上，tooltip={{ ..., open: true }}
2. 不要了
3. 感觉也是可以叫 open, `filterDropdownOpen`

**Comment by huangkairan** [comment]
mark

**Comment by zombieJ** [comment]
高产~~

**Comment by yoyo837** [comment]
上一个这么高产的人还是上一个。👍

**Comment by dancerphil** [comment]
动作那么快，支持统一，不过 open 有没有一种动词的感觉，说实话我经常这么写：

```
const [visible, open, close] = useSwitch(false);
```

突然就尬住了，得改成：

```
const [open, handleOpen, handleClose] = useSwitch(false);
```

**Comment by yoyo837** [comment]
并不需要一定改你自己的变量吧：

```
const [visible, open, close] = useSwitch(false);

<Xxx open={visible} />
```

**Comment by dancerphil** [comment]
在这个作用域里有 open 这个变量，却 `open={visible}`，还是有点蛋疼的。

如果要改的话，我肯定还是选择我的那种方式，多改一些没什么，不要留下犯错的可能性。

**Comment by yoyo837** [comment]
有点代码小洁癖是很好的。

**Comment by dancerphil** [comment]
话说如果要 break，最好现在 v4 里面 deprecate 一下，这样提前就可能 migrate 了

**Comment by Ritr** [comment]
吃饱了没事干改这个干嘛

**Comment by tzbcf** [comment]
> 吃饱了没事干改这个干嘛

没事干，才需要刷Kpi吧。不然就毕业了

**Comment by mumu-baba** [comment]
哪个傻x 提的这个需求。

**Comment by imloren** [comment]
> 吃饱了没事干改这个干嘛

visible这个属性，是不是已经被广大用户所熟知，突然改一个命名，考虑过其他用户的影响吗？文档还删除了4.23.0版本以下的说明，visible用了多少年了，为什么突然换成open，意义呢？

**Comment by imloren** [comment]
visible这个属性，是不是已经被广大用户所熟知，突然改一个命名，考虑过其他用户的影响吗？文档还删除了4.23.0版本以下的说明，visible用了多少年了，为什么突然换成open，意义呢？

**Comment by 452MJ** [comment]
KPI刷2次

**Comment by mir0ne** [comment]
改成open是兼容英语不好的吗😂

**Comment by zombieJ** [comment]
对于 antd 中弹层类组件展示并不统一导致记忆成本，对于 jsx 开发者而言没有提示情况下容易用错。对于新增弹层展示类 feature，选择 visible 还是 open 同样很随机。为了面向未来开发者，需要收一个口，对于 v4，过去用法没有变化，`visible` 仍然可以使用，但是会提示 warning。

**Comment by Ritr** [comment]
> 

open是动词不适合做属性

**Comment by MadCcc** [comment]
> open是动词不适合做属性

![image](https://user-images.githubusercontent.com/27722486/188537249-803b6d8d-9c94-44c1-9398-e98c7fa7faf2.png)
open 也是形容词，这里用于表示 “打开着的”，比如 Dropdown 处于 “打开着的” 状态

**Comment by shellphon** [comment]
只提到了统一，依旧不解为何选择open而不是visible？open字符少一点？

**Comment by zombieJ** [comment]
> 只提到了统一，依旧不解为何选择open而不是visible？open字符少一点？

`<Select visible={false} />` 语义上会有歧义。

**Comment by xiaorong61** [comment]
> 在这个作用域里有 open 这个变量，却 `open={visible}`，还是有点蛋疼的。
> 
> 如果要改的话，我肯定还是选择我的那种方式，多改一些没什么，不要留下犯错的可能性。

如果用的是 typescript，函数类型的 open 传给布尔类型的 open 会直接报错的。

**Comment by lucaslz2020** [comment]
1. `open`是动词，不应该作为属性的，正常来说会把他看做是一个行为，好歹使用`isOpen`  也稍微好一点吧。
2. 如果升级的话，工作量还是很大的，这种是不是应该提供一个工具，自动迁移。

**Comment by EnixCoda** [comment]
组件的 API 遵循相同的命名规则是好事。虽然这将大大增加v4和v5之间的迁移成本。 希望 antd v5 的迁移工具能自动化这个步骤（目前没看到 TODO item

大致扫了一下代码，没有看到通过复用的 interface 实现 `open` & `onOpenChange`，而似乎是通过在每个组件中手动输入 `open` 来实现的？这样看来，这个 `visible open API 统一至 open` ，像是在拼写层面的巧合，而不是代码逻辑层面的统一。我不太理解这背后的原因

关于具体命名的争议，这个 issue 的大部分参与者可能不是英语的 native speaker，但是可以参考社区中 native speaker 做的其他 UI 库的命名，我个人看到的是以 `isOpen` 为主流，几乎没有使用 `open` 的。一个有动词含义的词单独如此使用确实让人困惑。如果 Ant Design 考虑国际化的用户群体，这也是不可忽视的一环吧？

**Comment by sncer** [comment]
真是闲的，如果不兼容我就只能锁antd版本了，跟以后的版本说拜拜～👋

**Comment by minisola** [comment]
在5.0做这个改变不好吗，proComponent没跟进这个修改，导致dev启动一堆警告

**Comment by 666-arch** [comment]
我们在自定义一些列组件的时候，在判断改组件是否处于一个显示或者隐藏的状态时，通常会在所属属性前加入Isxxx的前缀，如果说是为了单纯的从字面意义上去做这个改变，我觉得是不是有点弄巧成拙了，而且open看起来也并没有isOpen更容易解释的通。

**Comment by Superman-wc** [comment]
> 我们在自定义一些列组件的时候，在判断改组件是否处于一个显示或者隐藏的状态时，通常会在所属属性前加入Isxxx的前缀，如果说是为了单纯的从字面意义上去做这个改变，我觉得是不是有点弄巧成拙了，而且open看起来也并没有isOpen更容易解释的通。

这真是一个有趣的问题，为了统一，把visible 改成了open , 结果在写代码的时候又不由自主的想到是不是应该用isOpen，那这样的改动真的是有必要的吗？

**Comment by 666-arch** [comment]
> 

不管从哪方面来思考这个问题，都不是属于一个明智的改动

**Comment by 666-arch** [comment]
> > 我们在自定义一些列组件的时候，在判断改组件是否处于一个显示或者隐藏的状态时，通常会在所属属性前加入Isxxx的前缀，如果说是为了单纯的从字面意义上去做这个改变，我觉得是不是有点弄巧成拙了，而且open看起来也并没有isOpen更容易解释的通。
> 
> 这真是一个有趣的问题，为了统一，把visible 改成了open , 结果在写代码的时候又不由自主的想到是不是应该用isOpen，那这样的改动真的是有必要的吗？

不管从哪方面来思考这个问题，都不是属于一个明智的改动

**Comment by Superman-wc** [comment]
> 

看看其他封装组件的， 对于组件是否可见，不都是习惯写成 xxx.visible = false  的吗？

**Comment by 666-arch** [comment]
> > 
> 
> 看看其他封装组件的， 对于组件是否可见，不都是习惯写成 xxx.visible = false 的吗？

我赞同你的说法，对于习惯了用visible的开发者，项目中突然对于同一功能需要改成open是看起来有点鸡肋的

**Comment by Superman-wc** [comment]
CSS 属性 visibility 显示或隐藏元素而不更改文档的布局
这个 visibility 应该是比较接近 像<Modal visible /> 中的解释了
visibility 有3个值：
visible：元素正常显示。

hidden：隐藏元素，但是其他元素的布局不改变，相当于此元素变成透明。要注意若将其子元素设为 visibility: visible，则该子元素依然可见。

collapse：关键字对于不同的元素有不同的效果：

用于 [<table>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/table) 行、列、列组和行组，隐藏表格的行或列，并且不占用任何空间（与将 [display](https://developer.mozilla.org/zh-CN/docs/Web/CSS/display): none 用于表格的行/列上的效果相当）。但是，仍会计算其他行和列的大小，就好像折叠的行或列中的单元格一样。此值允许从表中快速删除行或列，而不强制重新计算整个表的宽度和高度。
折叠的弹性项目被隐藏，他们将占用的空间被删除。
对于 [XUL](https://developer.mozilla.org/zh-CN/docs/Mozilla/Tech/XUL) 元素，元素的计算大小始终为零，而且通常会忽略影响大小的其他样式，尽管边距仍然有效。
对于其他元素，折叠处理与隐藏相同。

<Modal visible /> 用visible 时， 不管是否true或false都是会渲染出来的 只是是否可见而已

**Comment by Superman-wc** [comment]
刚又去看了html5 [https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/dialog]dialog

```
<dialog open>
  <p>Greetings, one and all!</p>
  <form method="dialog">
    <button>OK</button>
  </form>
</dialog>
```
对于这个对话框，的确是使用open做为属性名的

**Comment by jin-benben** [comment]
如果有时间有精力可以去优化性能或者解决bug,而不是做这些增加毫无意义的事情，刷KPI也要有个底线，有个度！

**Comment by youhongxing** [comment]
就很无语

**Comment by woohs** [comment]
这种改动说实话很没必要！要改也是 v5 再改吧？不想想全世界有多少系统用antd的，这一个改动要花费大家多少时间去改？

**Comment by Mzhang1994** [comment]
> 这种改动说实话很没必要！要改也是 v5 再改吧？不想想全世界有多少系统用antd的，这一个改动要花费大家多少时间去改？

我都直接锁版本了，这种版本内的break change真的是非常恶心。很多用antd的系统都是商业方案。又不是大家都做开源的。稍微体量大一点的系统，一旦有break changes。整个项目的工作量增加的不是一星半点。又不是前端改了，代码就能直接上线的。测试同事测起来都会烦死的。阿里内部自己的项目都没有这样搞的吧。

**Comment by afc163** [comment]
并没有 break change，只有开发环境会有警告信息。
