### ISSUE TITLE
Upload 组件上传文件损坏

### ISSUE THREAD

**Issue by ianzone** [ant-design/ant-design#36602]
### Reproduction link

[https://361p4g.csb.app](https://361p4g.csb.app)
[https://codesandbox.io/s/antd-reproduction-template-forked-361p4g?file=/upload.jsx](https://codesandbox.io/s/antd-reproduction-template-forked-361p4g?file=/upload.jsx)

### Steps to reproduce

上传文件后下载，对比两个文件的哈希值

### What is expected?

哈希值相同

### What is actually happening?

哈希值不同

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Version 103.0.5060.114 (Official Build) (64-bit) |

**Comment by afc163** [comment]
上传后下载的 hash 值，这个已经是服务端实现了，和前端组件无关。

**Comment by ianzone** [comment]
> 上传后下载的 hash 值，这个已经是服务端实现了，和前端组件无关。

使用预签名url直接从postman 上传就没有这个问题，而且后端根本就没有任何更改文件的行为，就是获得预签名url后上传至aws s3。

**Comment by ianzone** [comment]
@afc163 您好，使用postman上传可以保证文件哈希一致，而通过antd组件则不行，请问这有什么解释么？

**Comment by ianzone** [comment]
> 帮忙排查一下？antd 理论上不会做什么特殊处理

可能是依赖问题？ https://github.com/react-component/upload/issues/387

**Comment by vocoWone** [comment]
body结构的问题，直接把二进制传入body（重写customRequest）

`  
const customRequest = async (options: UploadRequestOption)=> {
    const response = await fetch(options.action, {
      headers: options.headers,
      method: options.method,
      body: options.file
    });
    options?.onSuccess?.(response);
  }
`

**Comment by ianzone** [comment]
> 帮忙排查一下？antd 理论上不会做什么特殊处理

看来是由于 antd 用 form-data 上传的缘故，aws S3 PUT 的预签名地址只能用二进制上传，否则文件会损坏。antd 应该在文档里注明一下，最好能增加一个属性控制传输格式。

**Comment by afc163** [comment]
来个 PR 增加一个 FAQ

**Comment by washmore** [comment]
我们也遇到了这个问题,在上传至腾讯云COS的时候使用预签名上传,用customRequest二进制上传没问题,直接使用action属性配置预签名URL和method属性put,会有问题,请问相关的FAQ在哪里,我们没有阅读到相应的章节
