### ISSUE TITLE
utf-8编码的antd库在gbk编码的项目中Table组件应用报错

### ISSUE THREAD

**Issue by wolf-tooth** [ant-design/ant-design#3661]
#### 发生问题的环境是：

- antd 版本: 2.2.0
- 操作系统及其版本: ubuntu 14.04
- 浏览器及其版本: chrome 39.0.2171.99(64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

由于项目的历史原因，我项目中的页面都是gbk编码的，在引入antd库Table组件的时候页面报错，原因是npm安装的antd库是utf-8编码的，在浏览器中单行注释影响到了代码而导致报错

#### 您期待的结果是:

之前做了一个utf-8编码的demo可以正常显示Table组件

#### 实际上的结果是:

在这个gbk编码的项目中浏览器报错了
提示 `Uncaught SyntaxError: Illegal return statement`
希望能提供gbk编码版本的antd库，或者将代码中的单行中文注释换成块注释

**Comment by afc163** [comment]
编码问题建议自行解决。

**Comment by wolf-tooth** [comment]
@afc163  你好 我现在的处理方法是把antd模块报错的文件编码成gbk或者将模块里面的注释统一处理成块注释都可以解决  但是感觉直接改库不太规范  有什么思路可以参考一下吗

**Comment by afc163** [comment]
试试 `<script charset="utf-8"></script>`

**Comment by wolf-tooth** [comment]
我是在[dvajs](https://github.com/dvajs/dva)这个脚手架中引入的antd  用的是import的方式  es6的import貌似不支持指定编码
