### ISSUE TITLE
Mentions提及组件框中出现滚动条后，@出现提及列表，提及列表显示位置有问题

### ISSUE THREAD

**Issue by Peony1** [ant-design/ant-design#36617]
### Reproduction link

[https://ant.design/components/mentions-cn/](https://ant.design/components/mentions-cn/)

### Steps to reproduce

1. Mentions提及组件框中输入多行文字，出现滚动条(可以设置输入框高度)
2. 输入@出现提及列表，提及列表显示位置有问题

### What is expected?

提及框出现滚动条之后，输入@符号，唤醒的选择列表出现在@附近，根据placement（弹出层展示位置）属性显示位置

### What is actually happening?

提及框提出现滚动条之后，输入@，唤醒的选择列表出现在距离输入框下方位置偏移明显，随着提及框中输入文字增加，选择列表位置偏差越明显
![image](https://user-images.githubusercontent.com/39027158/179958112-c389e563-6b56-42ef-88ba-6559fb965964.png)

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | chrome 88.0.4324.182 |

---
官网第一个案例（基本使用）就可复现

**Comment by JarvisArt** [comment]
https://github.com/react-component/mentions/pull/130

**Comment by afc163** [comment]
https://github.com/react-component/mentions/releases/tag/v1.9.1
