### ISSUE TITLE
Navbar menu related issue in layout section

### ISSUE THREAD

**Issue by santrajyadav196** [ant-design/ant-design#36623]
### Reproduction link

[https://beta.freakxgames.com/](https://beta.freakxgames.com/)

### Steps to reproduce

Important bugs

### What is expected?

Same as desktop behaviour

### What is actually happening?

When app is in mobile view and click on navbar, then page will be blank and error shows maximum updates.

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | Latest react version |
| System | All  |
| Browser | All |

---
Plasse updates same as desktop feature in mobile view. You can see my link what's happen in my aap which link is :https://beta.freakxgames.com/

**Comment by afc163** [comment]
same as #36559

**Comment by santrajyadav196** [comment]
> Duplicate of #36559 Duplicate of #36361

But we still facing same issues.

**Comment by santrajyadav196** [comment]
We can see on my above link.
