### ISSUE TITLE
Menu，display:flex =>display:none; display:none =>display:flex, error

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#36627]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6hty97?file=/index.css)

### Steps to reproduce

 in css  use ` @media`, display:flex =>display:none and display:none =>display:flex，

### What is expected?

`.header-class` ,it's box is Show and hide correctly

### What is actually happening?

`menu` not Render correctly

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 18.2.0 |
| System | Windows10 |
| Browser | Chrome105.0.5148.2 |

---
.header-class {display:brock} can use Render correctly,but it is not my need situation

**Comment by RSS1102** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-dnjlpu?file=/index.js

sorry.code is wrong just now.Now if i use `style={{ flex: "auto " }}` in it's code ,it's not my nedd,thanks.
https://codesandbox.io/s/antd-reproduction-template-forked-8j48oi?file=/index.js:789-814
![image](https://user-images.githubusercontent.com/81673017/180118191-f754db86-e03d-4079-a542-7450c118da18.png)
![image](https://user-images.githubusercontent.com/81673017/180118345-490bb6f4-b3d7-43ad-a4e7-2d3135df98e8.png)

**Comment by afc163** [comment]
<img width="1385" alt="图片" src="https://user-images.githubusercontent.com/507615/180119680-0b001fa4-fe26-4ded-b0c4-7dd00b02e5ba.png">

**Comment by RSS1102** [comment]
sorry ,i already change code in codesandbox, i want to have a logo in the left and have a menu in the right(use flex,    justify-content: space-between;)
https://codesandbox.io/s/antd-reproduction-template-forked-8j48oi?file=/index.css
![image](https://user-images.githubusercontent.com/81673017/180120377-b0aa2b31-4863-4a4b-8586-5d4576141369.png)

**Comment by RSS1102** [comment]
> 抱歉，我已经更改了代码沙箱中的代码，我想在左侧有一个徽标，在右侧有一个菜单（使用 flex，justify-content: space-between;） [https://codesandbox.io/s/antd-复制模板-forked-8j48oi?file=/index.css](https://codesandbox.io/s/antd-reproduction-template-forked-8j48oi?file=/index.css) ![图片](https://user-images.githubusercontent.com/81673017/180120377-b0aa2b31-4863-4a4b-8586-5d4576141369.png)
or In this case, only the display and hiding of menu can also be what I need, but it has not been successful(`menu` is replaced with other items and then replaced back.)，but also not success.@_@

**Comment by afc163** [comment]
这已经是你代码的样式逻辑了，并非 antd 的问题。

**Comment by RSS1102** [comment]
> 这已经是你代码的样式逻辑了，并非 antd 的问题。

ok =_=,
