### ISSUE TITLE
浏览器引入v2 跟v3的版本一直报错

### ISSUE THREAD

**Issue by Victor-XHH** [ant-design/ant-design#36624]
### Reproduction link

[https://www.antdv.com/docs/vue/introduce](https://www.antdv.com/docs/vue/introduce)

### Steps to reproduce

无

### What is expected?

正常

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | vue3 |
| System | windows10 |
| Browser |  google 103.0.5060.114 |

**Comment by afc163** [comment]
反馈错地方了。
