### ISSUE TITLE
Tree Com 可以动态定义节点拖拽图标

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#36633]
### What problem does this feature solve?

无法拖动的节点，有拖拽图标会让用户错误期待

### What does the proposed API look like?

declare type DraggableFn = (node: DataNode) => { icon?: React.ReactNode | false; nodeDraggable: boolean; };

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/36511
