### ISSUE TITLE
menu 收缩 hover 会导致 浮层闪一下

### ISSUE THREAD

**Issue by liuhongcheng1998** [ant-design/ant-design#36636]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-4-21-7-forked-5q9539?file=/demo.js:444-1018)

### Steps to reproduce

1. 选中最深层菜单
2. 收缩菜单
3. hover 到选中菜单
4. 展开菜单
5. 收缩菜单

发现 再次收缩会发现浮层闪一下

### What is expected?

浮层不显示

### What is actually happening?

浮层闪一下

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.47 |
| System | mac |
| Browser | chrome |

**Comment by zhangchao828** [comment]
+1

**Comment by JarvisArt** [comment]
Processing...

**Comment by JarvisArt** [comment]
已提交pr https://github.com/react-component/menu/pull/497

**Comment by zhangchao828** [comment]
@JarvisArt 没后续了吗，这个问题修复了吗

**Comment by JarvisArt** [comment]
> 

pr 还没有被合并， @afc163 @zombieJ

**Comment by zhengweipx** [comment]
+1 三层后 在展开情况下 选中最深层菜单 会出现popup

**Comment by Somethingbear** [comment]
> > 
> 
> pr 还没有被合并， @afc163 @zombieJ

https://codesandbox.io/s/m4nqeb
this is sample from official site (v4), it can repro another question,
1. click on submenu
2. click toggle button to shrink menu
it will show a submenu abnormally 

that also repro in v5 sample
https://codesandbox.io/s/jypcci

**Comment by JarvisArt** [comment]
@Somethingbear 大概月底发布修复版本
v4: https://github.com/ant-design/ant-design/pull/38876
v5: https://github.com/ant-design/ant-design/pull/38855
