### ISSUE TITLE
缩放状态下 Popconfirm 行为异常

### ISSUE THREAD

**Issue by izhouteng** [ant-design/ant-design#36639]
### Reproduction link

[https://stackblitz.com/edit/react-vno27r?file=demo.js](https://stackblitz.com/edit/react-vno27r?file=demo.js)

### Steps to reproduce

1. 网页缩放到 100% 以上。
2. 点击右侧网页中“删除”按钮。

### What is expected?

跟不缩放时行为一致。

### What is actually happening?

界面不正常。
![复现](https://s2.loli.net/2022/07/21/8nEkl9CuWtxjpTy.gif)

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.0.15 |
| System | Windows 10 |
| Browser | Chrome 101.0.4951.67 |

---
似乎只要使Popconfirm弹出的框触碰到网页最右边，就会出现此问题。

**Comment by Mzhang1994** [comment]
> ### Reproduction link
> https://stackblitz.com/edit/react-vno27r?file=demo.js
> 
> ### Steps to reproduce
> 1. 网页缩放到 100% 以上。
> 2. 点击右侧网页中“删除”按钮。
> 
> ### What is expected?
> 跟不缩放时行为一致。
> 
> ### What is actually happening?
> 界面不正常。 ![复现](https://camo.githubusercontent.com/c60bf6c46d3b14e7e6b6e1004c2662a8ae0a63dbb3cfc5ed4a1d7655d6b32193/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f32312f386e456b6c3943755774786a7054792e676966) [ ![复现](https://camo.githubusercontent.com/c60bf6c46d3b14e7e6b6e1004c2662a8ae0a63dbb3cfc5ed4a1d7655d6b32193/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f32312f386e456b6c3943755774786a7054792e676966) ](https://camo.githubusercontent.com/c60bf6c46d3b14e7e6b6e1004c2662a8ae0a63dbb3cfc5ed4a1d7655d6b32193/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f32312f386e456b6c3943755774786a7054792e676966) [ ](https://camo.githubusercontent.com/c60bf6c46d3b14e7e6b6e1004c2662a8ae0a63dbb3cfc5ed4a1d7655d6b32193/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f32312f386e456b6c3943755774786a7054792e676966)
> 
> Environment	Info
> antd	4.21.7
> React	18.0.15
> System	Windows 10
> Browser	Chrome 101.0.4951.67
> 似乎只要使Popconfirm弹出的框触碰到网页最右边，就会出现此问题。

这种一般设置一下placement就可以解决吧。你按照默认的设置，放在最右边肯定会挤得看着不正常。

**Comment by nick-ChenZe** [comment]
@zombieJ 看上去这个并不是一个低优先级的Bug, popConfirm 经常会被用来删作为Table的最后一列的操作，除非缩放外，滚动的场景调整popupContainer也同样会有这个问题

**Comment by afc163** [comment]
看下最新版 antd 这个问题还存在不？

**Comment by izhouteng** [comment]
> 看下最新版 antd 这个问题还存在不？

实测已修复。

我看了下是在 `4.24.10` 中   #41953 这个PR修复的，不过箭头还不准确。

v5中箭头指向也准确了。

![4.24.10](https://s2.loli.net/2023/07/01/SCfyd8XrLWjcZ57.png)

![5.6.3](https://s2.loli.net/2023/07/01/nBlNRbAGgQIjEhP.png)

**Comment by annihilationism** [comment]
placement: 'left'
