### ISSUE TITLE
How to use useWatch for field arrays

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#36649]
### Reproduction link

[https://uhr08x.csb.app/](https://uhr08x.csb.app/)

### Steps to reproduce

1. Click add field to render field
2. Check console log to see if the watch value is being watched

### What is expected?

Should be able to watch array field in Form.List

### What is actually happening?

Cannot get value using useWatch in array fields

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
Set as Form.List name path:
https://codesandbox.io/s/silly-easley-p7w6hh?file=/src/App.js

**Comment by tempoeric** [comment]
what if i only want to watch the value of foo can i get it using something like 
`  const watched = Form.useWatch("arrayFields.foo", form);
`

**Comment by tempoeric** [comment]
> Set as Form.List name path: https://codesandbox.io/s/silly-easley-p7w6hh?file=/src/App.js

what if i only want to watch the value of foo can i get it using something like
const watched = Form.useWatch("arrayFields.foo", form);

**Comment by zombieJ** [comment]
When you get the root field, you always can get sub:

```tsx
const arrayFields =  useWatch("arrayFields", form);
console.log(arrayFields[0].foo)
```

**Comment by chillyistkult** [comment]
It would be nice if `Form.List `could somehow expose full path along name property, because when you have multiple nested `Form.List` you are basically stuck unless explicitly defining root field + passing parent field name to useWatch.
