### ISSUE TITLE
TimePicker的disabledTime中有0分0秒的时候选择完时点确定默认会选择0分0秒

### ISSUE THREAD

**Issue by murrrrphy** [ant-design/ant-design#36642]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-4-21-7-forked-k2xq9b)

### Steps to reproduce

0分为disabledTime,点击时，点击确定，分默认为00

### What is expected?

1、分和秒默认为可选的第一个
2、或者加个参数时分秒都必须手动选择后才能确定

### What is actually happening?

分秒会默认到disabledTime中的内容

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Microsoft Edge 版本 103.0.1264.49 (正式版本) (64 位) |

**Comment by afc163** [comment]
Duplicate of #29179
