### ISSUE TITLE
Affix with Select as a children doesn't work as expected

### ISSUE THREAD

**Issue by kartoschechka** [ant-design/ant-design#36645]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-21-7-forked-uw4j7o?file=/demo.js)

### Steps to reproduce

Put Select component inside Affix.
Try to render React component.

### What is expected?

Successfully component render.

### What is actually happening?

Blank screen with error in console.
Argument appears to not be a ReactComponent. Keys: focus,blur,scrollTo

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | React 16.14.0, React 17.0.2 |
| System | MacOS 12.4 |
| Browser | Chrome 103 |

**Comment by afc163** [comment]
You can try to wrap a div as workaround.
