### ISSUE TITLE
InputNumber min 为 0 时，输入小于 0 的数值会重置为 0.01

### ISSUE THREAD

**Issue by Ice-cor** [ant-design/ant-design#36641]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-liskov-wsm5uy?file=/App.tsx)

### Steps to reproduce

min 设置为 0 InputNumber 输入小于 0 的数值，重置为0.01

### What is expected?

重置为 min 值

### What is actually happening?

重置为 0.01

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 16.12.0 |
| System | mac  |
| Browser | chrome |

---
rc-input-number 更新到 7.3.5 时出的问题

**Comment by zombieJ** [comment]
我先回滚一下，然后看看为什么

**Comment by zombieJ** [comment]
`+latest: rc-input-number@7.3.4`

**Comment by flexxWang** [comment]
min设置最小是0.5 步长0.5 结果变成了0步长每次都是0.6 之前版本都可以

**Comment by JunJianSyu** [comment]
min={1} 直接调成2 没法填1了

**Comment by flexxWang** [comment]
min={0.5} setup={0.5} 结果每次都是 从0.6开始

**Comment by jyxu1016** [comment]
2 hours ago。。。

**Comment by JackEqualsSparrow** [comment]
我也出现了这个问题

**Comment by JackEqualsSparrow** [comment]
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/eloquent-liskov-wsm5uy?file=/App.tsx)
> 
> ### Steps to reproduce
> min 设置为 0 InputNumber 输入小于 0 的数值，重置为0.01
> 
> ### What is expected?
> 重置为 min 值
> 
> ### What is actually happening?
> 重置为 0.01
> 
> Environment	Info
> antd	4.21.7
> React	16.12.0
> System	mac
> Browser	chrome
> rc-input-number 更新到 7.3.5 时出的问题

大佬，antd里面怎么看这个rc-input-number的版本

**Comment by zombieJ** [comment]
> > ### Reproduction link
> > [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/eloquent-liskov-wsm5uy?file=/App.tsx)
> > ### Steps to reproduce
> > min 设置为 0 InputNumber 输入小于 0 的数值，重置为0.01
> > ### What is expected?
> > 重置为 min 值
> > ### What is actually happening?
> > 重置为 0.01
> > Environment	Info
> > antd	4.21.7
> > React	16.12.0
> > System	mac
> > Browser	chrome
> > rc-input-number 更新到 7.3.5 时出的问题
> 
> 大佬，antd里面怎么看这个rc-input-number的版本

npm ls rc-input-number

**Comment by jyxu1016** [comment]
不打tag吗？

**Comment by Ice-cor** [comment]
> 
看 lock 文件

**Comment by Ice-cor** [comment]
@JackEqualsSparrow 看 lock 文件 + node_modules 包版本
