### ISSUE TITLE
DatePicker使用getFieldDecorator绑定form后，如果使用showTime属性则无法选择，只有点「此刻」才能选择

### ISSUE THREAD

**Issue by bestv2** [ant-design/ant-design#3665]
DatePicker使用getFieldDecorator绑定form后，如果使用showTime属性则无法选择，只有点「此刻」才能选择,不使用showTime的话则正常

#### 发生问题的环境是：
antd version: 2.2
os: mac os 10.12
browser： chrome

#### 可重现的在线演示
http://codepen.io/bestv2/pen/GjVjoX

**Comment by benjycui** [comment]
`RangePicker[showTime]` 可以，但是 `DatePicker[showTime]` 不可以。

**Comment by afc163** [comment]
是不是 cherry-pick 到 2.2.0 tag 上发个 fixed 版本？

**Comment by afc163** [comment]
受控模式下有问题，我改完发一个 2.2.1。

**Comment by bang88** [comment]
是同一个问题吗

**Comment by afc163** [comment]
是的，`DatePicker[showTime]` 我 2.2.0 的时候改过，现在只有 onOk 的时候才触发 onChange，把控制模式改挂了。

**Comment by afc163** [comment]
2.2.1 released
