### ISSUE TITLE
`useFormInstance` returns undefined

### ISSUE THREAD

**Issue by FOLLGAD** [ant-design/ant-design#36659]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-prnx2b?file=/index.js)

### Steps to reproduce

1. Import `useFormInstance` from `antd/lib/form/hooks/useFormInstance`
2. Use `useFormInstance` in a sub-component of a `<Form>` tag: `const form = useFormInstance()`

### What is expected?

The form instance should be returned.

### What is actually happening?

`undefined` is returned.

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.2 |
| System | macOS 12.3 |
| Browser | Firefox 102.0.1 |

---
Note: `Form.useFormInstance()` works as expected, but not `useFormInstance()`.

**Comment by afc163** [comment]
Please import Form in this way:

```jsx
import { Form } from 'antd';

Form.useFormInstance(); 
```

Other usage is not reliable.

**Comment by SlothDevLlama** [comment]
Same issue happens to me, I do the import like you mentioned @afc163 

In my case the issue appears, once the component who uses `Form.useFormInstance` is being imported from another module (like in yarn workspaces)
