### ISSUE TITLE
The only property working for Dynamic Theme is primaryColor, nothing else works !!!

### ISSUE THREAD

**Issue by GeorgeFlorian** [ant-design/ant-design#36657]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hfogw3?file=/demo.js)

### Steps to reproduce

Follow the steps provided by the Dynamic Theme (Experimental) guide: https://ant.design/docs/react/customize-theme-variable

### What is expected?

I expect to change various colors and background-colors in the theme by using `ConfigProvider.config({ theme: { ...properties }})` where properties are taken from here: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

### What is actually happening?

Except `primaryColor` property, no other property actually changes anything in the theme.

In default.less we have `@menu-bg: @component-background;` that should change the menu background.
As you can see in the reproduction example, I have set `componentBackground: '#98212E'` which is a red color, but the menu background is still white.

The same happens with drawer, with submenus, with headers.
Only primaryColor works and changes something in the theme.

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18.2 |
| System | Ubuntu 20.04.4 LTS |
| Browser | Chrome - Latest |

**Comment by GeorgeFlorian** [comment]
I have also tried using `craco` and the result is the same: the only color that I can change is `@primary-color`, everything else is ignored. I have followed these guides:
https://ant.design/docs/react/use-with-create-react-app and https://ant.design/docs/react/customize-theme

```javascript
const CracoLessPlugin = require('craco-less');

module.exports = {
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: {
              '@primary-color': '#98212E',
              '@component-background': '#98212E',
              '@border-color-base': '#000',
              '@layout-body-background': '#98212E',
              '@layout-header-background': '#98212E',
              '@text-color': '#fff',
            },
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};
```

The only style that I import is `@import '~antd/dist/antd.less';` which is inside `App.less` which is importend inside `App.jsx` component; the other components have no style imports.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32807#issuecomment-1168575848
