### ISSUE TITLE
ts error  in Table  onChange's sorter parameter 

### ISSUE THREAD

**Issue by lyan-ap** [ant-design/ant-design#36653]
### Reproduction link

[https://codesandbox.io/s/antd-reproduction-template-forked-mgi7el?file=/index.tsx](https://codesandbox.io/s/antd-reproduction-template-forked-mgi7el?file=/index.tsx)

### Steps to reproduce

When:
```
  onChange={(pagination, filter, sorter) => {
            setQuery({
              ...query,
              sortField: sorter.field,
              sortOrder: sorter.order,
```

### What is expected?

ts error passed , when I defined Column's type

### What is actually happening?

Property 'field' does not exist on type 'SorterResult<T> | SorterResult<T>[]'.
  Property 'field' does not exist on type 'SorterResult<T>[]'.ts(2339)

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome: Version 103.0.5060.114 (Official Build) (arm64) |

**Comment by lyan-ap** [comment]
Well , it was reproduced : [here](https://codesandbox.io/s/antd-reproduction-template-forked-mgi7el?file=/index.tsx)

**Comment by JarvisArt** [comment]
sorter 类型为 SorterResult<RecordType> | SorterResult<RecordType>[] 并没有问题，当 column.sorter 为 multiple 的时候，就会返回 SorterResult<RecordType>[] 的类型。

你可以这样做：
```jsx
import type { SorterResult } from 'antd/es/table/interface';

onChange={(pagination, filter, sorter) => {
  setQuery({
    ...query,
    sortField: (sorter as SorterResult<RecordType>).field,
    sortOrder: (sorter as SorterResult<RecordType>).order,
  })
}
````

**Comment by MadCcc** [comment]
> sorter 类型为 SorterResult | SorterResult[] 并没有问题

同意这个说法，类型并没有问题。

**Comment by ahmadrio** [comment]
> sorter 类型为 SorterResult | SorterResult[] 并没有问题，当 column.sorter 为 multiple 的时候，就会返回 SorterResult[] 的类型。
> 
> 你可以这样做：
> 
> ```js
> import type { SorterResult } from 'antd/es/table/interface';
> 
> onChange={(pagination, filter, sorter) => {
>   setQuery({
>     ...query,
>     sortField: (sorter as SorterResult<RecordType>).field,
>     sortOrder: (sorter as SorterResult<RecordType>).order,
>   })
> }
> ```

thanks it works

**Comment by revidovich** [comment]
reproduced in the "antd" version: "5.7.3" :(
