### ISSUE TITLE
Select dropdownRender 自定义内容点击后不会关闭

### ISSUE THREAD

**Issue by suyue0731** [ant-design/ant-design#36658]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

这个是https://ant.design/components/select-cn/ antd官网对于select组件dropdownrender的例子

官网的描述：使用 dropdownRender 对下拉菜单进行自由扩展。自定义内容点击时会关闭浮层，如果不喜欢关闭，可以添加 onMouseDown={e => e.preventDefault()} 进行阻止。

直接点击select，点击自定义区域发现dropdown没有收起，把代码中的preventDefault去掉后点击依然不能收起

### What is expected?

在用户没有拦截preventDefault的时候Select应该自动关闭才对

### What is actually happening?

实际上没有关闭

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17 |
| System | Mac os 11.3.1 |
| Browser | chrome 103 |

---
查了许多issue，都是要求不要关闭的，但是我的需求是要点击了自动关闭。。。所以希望组件的行为至少与文档描述一致，或者提供一个可以主动关闭的函数

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-7-forked-gnp4cy?file=/demo.js

4.x 应该已经修复了原始问题，演示和文档过期了，我来更新一波：https://github.com/ant-design/ant-design/issues/13448#issuecomment-536300552

**Comment by afc163** [comment]
4.x 升级的时候已经把 onMouseDown 干掉了，但是文档没改。

https://github.com/ant-design/ant-design/pull/20675/files#diff-fad140825176b9a1bc1586b17697b6c42249f26bf669cd1ba11b2af4578c1756L48

**Comment by suyue0731** [comment]
问题解决了，感谢

**Comment by bia2000** [comment]
> 问题解决了，感谢

请问怎么解决的？升到4.x?

**Comment by shuguangnet** [comment]
同问

**Comment by shuguangnet** [comment]
> 问题解决了，感谢

同问大佬
