### ISSUE TITLE
List组件下list.item展示的文本样式丢失

### ISSUE THREAD

**Issue by wuchencm** [ant-design/ant-design#36666]
### Reproduction link

[https://ant.design/components/list-cn/](https://ant.design/components/list-cn/)

### Steps to reproduce

原始文本出现的多个空格，被list.item渲染后均变成1个空格

### What is expected?

保留原始文本的样式

### What is actually happening?

清除了多余的空格，只保留了一个

| Environment | Info |
| --- | --- |
| antd | 4.19.0 |
| React | 17.0.0 |
| System | windows |
| Browser | chrome |

**Comment by wuchencm** [comment]
`import React from "react";
import ReactDOM from "react-dom";
import { List } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const data = [
  'Racing car sprays       burning fuel into crowd.',
  'Japanese princess to wed commoner.',
  'Australian walks 100km after outback crash.',
  'Man charged over missing wedding girl.',
  'Los Angeles battles huge wildfires.',
];

ReactDOM.render(
<List
      size="small"
      bordered
      dataSource={data}
      renderItem={item => <List.Item>{item}</List.Item>}
 />,
document.getElementById("root")
);
`

**Comment by wuchencm** [comment]
[codesandbox : https://codesandbox.io/embed/antd-reproduction-template-forked-9j3inb?fontsize=14&hidenavigation=1&theme=dark
](https://codesandbox.io/embed/antd-reproduction-template-forked-9j3inb?fontsize=14&hidenavigation=1&theme=dark)

**Comment by afc163** [comment]
It is not antd's problem: https://codesandbox.io/s/antd-reproduction-template-forked-02e7pp?file=/index.js
