### ISSUE TITLE
Affix 滚动容器定位错误

### ISSUE THREAD

**Issue by qianchengjie** [ant-design/ant-design#36668]
### Reproduction link

[https://ant.design/components/affix-cn/#components-affix-demo-target](https://ant.design/components/affix-cn/#components-affix-demo-target)

### Steps to reproduce

1. 先滚动示例3的容器，使得 Affix 固定示例3容器顶部
2. 再滚动window

### What is expected?

Affix不跟随window滚动

### What is actually happening?

会发现Affix跟随window滚动

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.2 |
| System | macOS Monterey 12.3.1 |
| Browser | Chrome 103.0.5060.114（正式版本） (x86_64) |

**Comment by qianchengjie** [comment]
`fixed` -> `relative & absolute`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16125

**Comment by qianchengjie** [comment]
@afc163 window水平滚动也会有问题，治标不治本
