### ISSUE TITLE
List组件下list.item展示的文本样式丢失

### ISSUE THREAD

**Issue by wuchencm** [ant-design/ant-design#36667]
### Reproduction link

[https://ant.design/components/list-cn/](https://ant.design/components/list-cn/)

### Steps to reproduce

原始文本出现的多个空格，被list.item渲染后均变成1个空格

### What is expected?

保留原始文本的样式

### What is actually happening?

清除了多余的空格，只保留了一个

![1 EGY0ZJ)LP2T{Z%X $LFKX](https://user-images.githubusercontent.com/14210543/180600389-d294eff5-71c2-4741-b7af-a89b56f27fd7.png)
控制台输出的是原始文本，深蓝色区域输出的是list.item渲染后的
| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.0 |
| System | windows |
| Browser | chrome |

**Comment by yoyo837** [comment]
Duplicate of #36666
