### ISSUE TITLE
Form表单验证会抖动

### ISSUE THREAD

**Issue by dxl519** [ant-design/ant-design#36669]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nlbfev?file=/demo.js:133-1528)

### Steps to reproduce

验证规则为必选，不输入内容直接提交，弹出提交失败提示以后再输入，布局会上下抖动

### What is expected?

表单输入内容不抖动

### What is actually happening?

抖动

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | 谷歌浏览器 100版本 |

---
登录

**Comment by nuintun** [comment]
https://github.com/ant-design/ant-design/issues/36470

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/36575
