### ISSUE TITLE
Select组件使用dropdownRender自定义带input框，同时设置mode="multiple"，input的删除动作会导致已经选择Item消失

### ISSUE THREAD

**Issue by santa955** [ant-design/ant-design#36670]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-21-7-forked-zboxvn?file=/demo.js)

### Steps to reproduce

1. 自定义dropdownRender，底部带输入框可新增选项；
2. 设置Select的mode="multiple"；
3. 选择几个已有选项；
4. 在输入框中输入内容，然后del删除input字符，可以看见已经选择的选项被删除。

https://user-images.githubusercontent.com/7077768/180602310-8efcb49a-b668-49d5-9b54-c4fe2afbb1d1.mp4

### What is expected?

Input输入不影响Select的选项

### What is actually happening?

Input输入删除影响了Select的选项

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome 103.0.5060.134 |

**Comment by zombieJ** [comment]
阻止冒泡：
https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-21-7-forked-pz48g7?file=/demo.js

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/28694
