### ISSUE TITLE
Tree组件更新数据时UI层面会出现节点闪烁跳动的问题 

### ISSUE THREAD

**Issue by zq210wl** [ant-design/ant-design#36676]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/treezu-jian-geng-xin-shu-ju-shi-uiceng-mian-hui-chu-xian-jie-dian-shan-shuo-tiao-dong-de-wen-ti-fn3trk)

### Steps to reproduce

* 等页面加载渲染完毕
* 然后点击“更新状态”按钮来切换状态，每次点击的时候对应的数据会在treeData1和treeData2之间进行切换
* 观察页面中Tree组件的更新，会发现每次更新都会出现节点跳动闪烁的UI问题

### What is expected?

Tree组件更新的时候不应该出现节点跳动闪烁的问题，而是直接切换到对应的结果UI

### What is actually happening?

Tree组件更新的时候会出现节点跳动闪烁的UI问题

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | react-16.14.0 |
| System | Mac |
| Browser | Chrome |

---
ant-design 3.x 版本没有这样的问题

**Comment by afc163** [comment]
Same issue：https://github.com/ant-design/ant-design/issues/35023

**Comment by maliml** [comment]
我也遇到同样的问题，怎么解决的？

**Comment by maliml** [comment]
我也遇到这样的问题：tree组件切换数据源的时候，已展开的子节点会看到向左抖动。怎么解决的呢

**Comment by afc163** [comment]
Should be fixed in https://github.com/react-component/tree/pull/743
