### ISSUE TITLE
SubMenu doesn't collapse/uncollapse when defaultOpenKeys React state changes dynamically

### ISSUE THREAD

**Issue by VladGeana** [ant-design/ant-design#36687]
### Reproduction link

[https://stackblitz.com/edit/react-zmmgqd-8stw7h?file=demo.js](https://stackblitz.com/edit/react-zmmgqd-8stw7h?file=demo.js)

### Steps to reproduce

Create a Menu with SubMenu
Set the `defaultOpenKeys` prop to useState([]) variable: `const [defaultOpenKeys, setDefaultOpenKeys] = useState([]);`
Using a setTimeout(), set the variable to a non-empty array: `setDefaultOpenKeys(['some SubMenu key']);`

### What is expected?

The submenu to be uncollapsed when `defaultOpenKeys` is updated.

### What is actually happening?

The subMenu is still collapsed

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 18.0.0 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by zombieJ** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically
