### ISSUE TITLE
using the Image component, the style shows: none or takes up space and can be clicked

### ISSUE THREAD

**Issue by xminc** [ant-design/ant-design#36680]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shou-kong-de-yu-lan-antd-4-21-7-forked-h3qf2f?file=/demo.js:355-362)

### Steps to reproduce

For details, see https://codesandbox.io/s/shou-kong-de-yu-lan-antd-4-21-7-forked-h3qf2f?file=/demo.js,
When <Image /> is set to display: none, ant-image-mask-info still takes up space. Although it is invisible, it is clickable and takes up unnecessary space.

### What is expected?

ant-image-mask-info does not take up space

### What is actually happening?

 ant-image-mask-info still takes up space. Although it is invisible, it is clickable and takes up unnecessary space.

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17.0.13 |
| System | macos |
| Browser | chrome-103.0.5060.134 |

**Comment by xccjk** [comment]
The problem does exist.

I feel that the original design of the preview should be to solve this problem by setting the preview mask

```
<Image
  width={200}
  style={{
    display: "none"
  }}
  src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?x-oss-process=image/blur,r_50,s_50/quality,q_1/resize,m_mfit,h_200,w_200"
  preview={{
    visible,
    src:
      "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    onVisibleChange: (value) => {
      setVisible(value);
    },
    mask: false
  }}
/>
```

demo: [https://codesandbox.io/s/shou-kong-de-yu-lan-antd-4-21-7-forked-ndgsfg?file=/demo.js:356-871](https://codesandbox.io/s/shou-kong-de-yu-lan-antd-4-21-7-forked-ndgsfg?file=/demo.js:356-871)
