### ISSUE TITLE
Dont work tooltip with options Radio.Group

### ISSUE THREAD

**Issue by goldpvlv** [ant-design/ant-design#36686]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-radio-group-lsctss)

### Steps to reproduce

create Radio.Group with Radio and try to view Tooltip

### What is expected?

The tooltip in the Radio button should show the tip text when hovered over

### What is actually happening?

nothing

| Environment | Info |
| --- | --- |
| antd | 4.15.2 |
| React | 17.0.2 |
| System | windows 10 |
| Browser | chrome |

---
sorry, i'm begginer in antd

**Comment by xccjk** [comment]
you are not using it correctly

[https://codesandbox.io/s/tooltip-radio-group-forked-ds1dll?file=/src/App.js](https://codesandbox.io/s/tooltip-radio-group-forked-ds1dll?file=/src/App.js)
