### ISSUE TITLE
Typography.Text 的 ellipsis 中使用 tooltip，切换内容后不显示

### ISSUE THREAD

**Issue by roc-an** [ant-design/ant-design#36698]
### Steps to reproduce

渲染代码：

`export const renderText = (value: string) => (<Typography.Text ellipsis={{ tooltip: value }}>{ value }</Typography.Text>);`

1、value 由 React State 维护；
2、改变 value 后，重新执行 renderText() 函数，渲染 Typography.Text 组件
3、toolip 不显示（value 改变前会正常显示）

### What is expected?

tooltip 正常显示，值为改变后的 value 值

### What is actually happening?

value 改变后，tooltip 不显示

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | ^16.13.1 |
| System | mac |
| Browser | chrome |

**Comment by roc-an** [comment]
在线 Demo 地址：https://codesandbox.io/s/antd-reproduction-template-forked-ig77om?file=/index.js

复现说明：

1、Modal 中渲染带 tooltip 文字
2、先打开弹窗，tooltip 正常
3、关闭弹窗后，改变值，再打开弹窗
4、tooltip 无法正常显示

**Comment by JarvisArt** [comment]
使用 Modal.destroyOnClose 属性可以解决该问题

**Comment by afc163** [comment]
Duplicate of #36786
