### ISSUE TITLE
Modal的zIndex设置过高，如果内部含有Select组件会导致遮盖下拉选择框。比如设置为2000

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/ant-design#36693]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-em0gvy?file=/index.js)

### Steps to reproduce

模态框中放置一个Select然后把Modal的zIndex设置大一些

### What is expected?

在提高Modal的同时不能影响Select的下拉框层级

### What is actually happening?

遮盖了Select的下拉框

| Environment | Info |
| --- | --- |
| antd | 4.21.2 |
| React | 16.14.0 |
| System | macos |
| Browser | chrome |

**Comment by LukerSpringtree** [comment]
z-index 是不是要超过1.  2 都比较少用

**Comment by afc163** [comment]
getPopupContainer

https://codesandbox.io/s/antd-reproduction-template-forked-xublnj?file=/index.js:409-426
