### ISSUE TITLE
带showTime的DatePicker结合getFieldDecorator使用无法选择日期

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#3669]
#### 发生问题的环境是：

- antd 版本: 2.2.0
- 操作系统及其版本: windows10
- 浏览器及其版本: chrome 56.0.2902.0 dev (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

带showTime属性的DatePicker结合getFieldDecorator使用

#### 您期待的结果是:

可以正常选择日期

#### 实际上的结果是:

无法选择日期

#### 可重现的在线演示

https://codepen.io/infeng/pen/QKXzLe?editors=0011

**Comment by afc163** [comment]
Fixed in #3665
