### ISSUE TITLE
input 的 allowClear 可否加入全局化配置

### ISSUE THREAD

**Issue by Cool-Star** [ant-design/ant-design#36704]
### What problem does this feature solve?

在Form中或者其余地方，input 的 allowClear 其实作为一个常见属性，通常所有控件都会保持一致。。
可否在全局化配置中加入或者Form可以配置？

### What does the proposed API look like?

allowClear

**Comment by afc163** [comment]
这样的属性很多，ConfigProvider 里加不完，还是建议统一做上层组件封装。
