### ISSUE TITLE
Popover建议：visible控制显示隐藏的问题

### ISSUE THREAD

**Issue by woodccc** [ant-design/ant-design#3670]
目前Popover的隐藏是通过display: none来实现，如果页面用到popover的地方很多，打开一个popover就会增加一个，一直存在。建议在hide时把它卸载掉，直接通render的方式来控制显示隐藏。

在Modal中好像也有同样的问题。Modal可以通过自己控制Modal的render，但是popover好像不能这样子做。

谢谢！

**Comment by afc163** [comment]
popover 有 `visible` 和 `onVisibleChange` 属性。

另外，底层有 `destroyPopupOnHide` 属性可用。https://github.com/react-component/trigger#props
