### ISSUE TITLE
Custom Object Structure for TreeSelect Value State

### ISSUE THREAD

**Issue by RobinUndersigned** [ant-design/ant-design#36709]
### What problem does this feature solve?

The current implementation only allows the value state to be of type string or string[]. In some cases you want to have more information for each selected value. For instance: When building a search UI you might want to add a different search type to each value like "and", "or", "not" in order to indicate how the values are going to be used. In that case it would be nice to have the option to store objects in that state like {value: "testValue", type: "and"}

### What does the proposed API look like?

Well there should by a possibility to tell the components which property of the value state object is going to be the label value which one is meant for other operations or which one is additional information.

**Comment by afc163** [comment]
`fieldNames`

**Comment by RobinUndersigned** [comment]
> `fieldNames`

This refers to the Nodes in the Tree not the State of the selected Values
