### ISSUE TITLE
新增ColorPicker组件

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#36705]
### What problem does this feature solve?

可以进行颜色选择

### What does the proposed API look like?

可以参考其他开源的UI组件库的ColorPicker的api

**Comment by MadCcc** [comment]
暂时没有计划，可以使用任何其他的 ColorPicker 组件配合 antd 使用，没有限制。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35315

**Comment by afc163** [comment]
5.5.0 已经有啦！https://github.com/ant-design/ant-design/pull/41990
