### ISSUE TITLE
[React 18] dropdown onMouseDown inconsistent behavior

### ISSUE THREAD

**Issue by hqwuzhaoyi** [ant-design/ant-design#36703]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-dropdown-bug-forked-4po9zj?file=/src/App.tsx)

### Steps to reproduce

- add Dropdown
- add div 
- div add onMouseDown event
- Dropdown add event onVisibleChange

### What is expected?

1.  trigger div onMouseDown event , then set dropdown visible true
1.  not trigger dropdown onVisibleChange

### What is actually happening?

1.  trigger div onMouseDown event  , then set dropdown visible true
1.  trigger dropdown onVisibleChange , then set dropdown visible false

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18 |
| System | mac 12.5 |
| Browser | chrome 103.0.5060.134 |

---
I found the code in rc-trigger 

```
 this.clickOutsideHandler = addEventListener(currentDocument, 'mousedown', this.onDocumentClick);
```

This handler will trigger after clicking on the div outer wrapper of the drop-down, but when in react 16 will not.

react 16 only trigger ther outer wrapper's event.

**Comment by hqwuzhaoyi** [comment]
I think the reason is `react Event system` differs between 16 and 17, also different from 18

![image](https://user-images.githubusercontent.com/44605072/180918471-b330bd37-ea39-4a7e-9dc8-6ea8534f2546.png)

**Comment by MadCcc** [comment]
Just remove `onVisibleChange` on Dropdown and you will get what you expected.

**Comment by hqwuzhaoyi** [comment]
> Just remove `onVisibleChange` on Dropdown and you will get what you expected.

it works😄,but can we change the code to solve it 

here is  [react 16 demo](https://codesandbox.io/s/antd-dropdown-bug-16-zpgepk?file=/src/App.tsx)

**Comment by MadCcc** [comment]
You have make Dropdown `visible` controlled, so you should make it stable in your code.
And it seems the same behavior with React 16.

**Comment by hqwuzhaoyi** [comment]
[](url)

> You have make Dropdown `visible` controlled, so you should make it stable in your code. And it seems the same behavior with React 16.

😄 thanks, It also solves my problem
