### ISSUE TITLE
v4.22.0 Form layout='vertical' 有问题

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#36719]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-bu-ju-antd-4-22-0-forked-de90rd?file=/demo.js)

### Steps to reproduce

v4.22.0 Form layout='vertical' 有问题

### What is expected?

v4.22.0 Form layout='vertical' 有问题

### What is actually happening?

Something went wrong.
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="698" alt="图片" src="https://user-images.githubusercontent.com/507615/181152942-2e664b3e-00fa-4642-96ab-3af454ba318a.png">

**Comment by zombieJ** [comment]
你的重现看起来没有问题？

**Comment by kaoding** [comment]
v4.22.0 Form layout="vertical" 就变成这样了（上面重现好像不行，我的截图就是这样，降到v4.21.x就不会这样）

![image](https://user-images.githubusercontent.com/18542211/181156208-a3bdc2e4-4158-4074-9e41-7929d36af872.png)

**Comment by yanjun0501** [comment]
+1  表示遇到了同样的问题  下面是例子
![image](https://user-images.githubusercontent.com/19325842/181219141-3d5de310-b7ba-44b0-9497-ab8b6d3916b2.png)

**Comment by kaoding** [comment]
可能是浏览器缓存的问题，强制刷新我已解决， @yanjun0501
