### ISSUE TITLE
Poorly designed Popover

### ISSUE THREAD

**Issue by Prathapkarumanchi** [ant-design/ant-design#36722]
### Reproduction link

[https://ant.design/components/popover/](https://ant.design/components/popover/)

### Steps to reproduce

The popover itself

### What is expected?

There's no way to create a separate Popover component and dynamically append trigger event to dynamically created elements.
And when these elements are triggered the popover should open but the current design is lacking this.

### What is actually happening?

There's no way to create a separate Popover component and dynamically append trigger event to dynamically created elements.
And when these elements are triggered the popover should open but the current design is lacking this.

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | react |
| System | all |
| Browser | all |

---
Fix this, to add dynamic popover where we can trigger popover from any external links and buttons.

**Comment by zombieJ** [comment]
You can HOC Popover with ghost holder to dynamic patch on the place you need.
