### ISSUE TITLE
日期选择器disabledTime

### ISSUE THREAD

**Issue by wb-wsx** [ant-design/ant-design#36724]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-sanne-c939wd?file=/src/App.js)

### Steps to reproduce

第一次结束时间选择7月27日  小时 可选00 （正确）点击确定
 第二次更改日期 结束时间选择7月26日，但是小时 可选还是只有00    正确的应该是00-23都可选

### What is expected?

结束时间 不可选 当日的00点之后的小时

### What is actually happening?

disabledtime 禁选一次之后  不管选哪个日期  他都禁选了

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.x |
| System | fcattribution |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
BUG: 选择时，disabledTime 提供的 Date 不正确。

**Comment by JarvisArt** [comment]
代码存在问题，dates 不是一个数组，moment(dates[1]).date() 应该为 moment(dates).date()
```js
  const disabledRangeTime = (dates, type) => {
    if (dates && moment(dates).date() === moment().date() && type == "end") {
      return {
        disabledHours: () => range(1, 23)
      };
    }
    return {
      disabledHours: () => []
    };
  };
```

**Comment by wb-wsx** [comment]
感谢
