### ISSUE TITLE
Form 设置 disable 不生效

### ISSUE THREAD

**Issue by xingyinsong** [ant-design/ant-design#36720]
### Reproduction link

[https://ant-design.gitee.io/components/form-cn/#components-form-demo-disabled](https://ant-design.gitee.io/components/form-cn/#components-form-demo-disabled)

### Steps to reproduce

这段代码复制到项目中即可

### What is expected?

设置 disable={true} 后 Form 显示为禁用状态

### What is actually happening?

Form 表格没有变成禁用状态

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | 18.1.0 |
| System | Windows 10 专业版 21H1 |
| Browser | Chome 103.0.5060.134（正式版本） （64 位） |

---
这个 demo 从 CodePen 中打开显示是正常的，但是我本地项目中显示是异常的

**Comment by xingyinsong** [comment]
@afc163 这个我也不知道该怎么给一个复现的例子，就是官方的这个 demo，我用 CodePen 打开都是正常的，但是我项目里引入后就是不正常的，跟 demo 的代码都是完全一致的，还希望可以看一下是不是版本的问题呢

**Comment by afc163** [comment]
没有重现的话，我也不知道从何排查起。

**Comment by xingyinsong** [comment]
> 没有重现的话，我也不知道从何排查起。

我给出了我用的版本号，能否从这里入手呢，我这边尝试给个重现试试

**Comment by afc163** [comment]
https://ant.design/changelog-cn#4.21.0

4.20.2 并不支持 Form 上的 disabled 属性。

**Comment by afc163** [comment]
@MadCcc 需要给 demo 和 API 文档里加上版本标记。

**Comment by xingyinsong** [comment]
> https://ant.design/changelog-cn#4.21.0
> 
> 4.20.2 并不支持 Form 上的 disabled 属性。

麻烦啦，我尝试升级试试，这个是可以复现的链接：https://codesandbox.io/embed/antd-reproduction-template-forked-nl2e8d?fontsize=14&hidenavigation=1&theme=dark
