### ISSUE TITLE
使用select组件，不能选择值进行复制内容操作

### ISSUE THREAD

**Issue by NeverMoVe** [ant-design/ant-design#36737]
### What problem does this feature solve?

select  tags模式，下拉列表动态新增内容时候方便复制新增，每次都要从新输入。

### What does the proposed API look like?

使用select组件，可以复制内容

**Comment by NeverMoVe** [comment]
这个我改变CSS没有啥作用。我把组件CSS样式改掉user-select:all。没有效果

**Comment by afc163** [comment]
Duplicate of #14395
