### ISSUE TITLE
Form 演示的间距要调整一下

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3673]
<img width="514" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19882245/2bd4187c-a047-11e6-98ea-48adaf442509.png">

验证码和提交按钮之间太挤了。验证码单独放在一个 Form.Item 里比较合适。

**Comment by afc163** [comment]
<img width="330" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19882282/702c4eae-a047-11e6-8c52-79c70463ec89.png">

然后这个应该直接用 FormItem 的布局属性。

**Comment by benjycui** [comment]
> 验证码和提交按钮之间。验证码单独放在一个 Form.Item 里比较合适。

不懂。。。

**Comment by afc163** [comment]
现在和 Button 放在一起了，贴的太近，直接单独放一个 Form.Item。
