### ISSUE TITLE
Darwer组件在360安全浏览器不兼容

### ISSUE THREAD

**Issue by woshiji1987** [ant-design/ant-design#36744]
### Reproduction link

[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce

自有项目，抽屉组件内有inset属性，低版本浏览器不兼容，esbuild设置targets无法解决

### What is expected?

期望官方能帮忙解决下这个组件的兼容性，不要在样式里直接设置inset属性

### What is actually happening?

360安全浏览器无法打开drawer

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 17.0 |
| System | win10 |
| Browser | 360安全浏览器 |

<!-- generated by ant-design-issue-helper. DO NOT REMOVE --
<img width="763" alt="截屏2022-07-27 20 02 49" src="https://user-images.githubusercontent.com/33452948/181243239-3df9cb05-e8b8-4f66-96b8-fb75fd5d567d.png">
>

**Comment by woshiji1987** [comment]
<img width="763" alt="截屏2022-07-27 20 02 49" src="https://user-images.githubusercontent.com/33452948/181243275-91e63e5c-398a-4fd5-9167-940c051db246.png">

**Comment by drizzlesconsin** [comment]
@zombieJ @afc163 ant.design 官网还存在这个问题 `inset: 0`.
