### ISSUE TITLE
antd v5 cssinjs 能否通过 document.head.prepend 进行 style 标签添加呢？

### ISSUE THREAD

**Issue by gaokaifeis** [ant-design/ant-design#36742]
### What problem does this feature solve?

原有项目有进行默认样式的覆盖，因拥有主题切换的需求，主题切换后将 新主题的style标签是通过document.head.appendChild进行添加的，导致antd style在项目业务样式后面，业务代码中进行覆盖的样式失效

### What does the proposed API look like?

 cssinjs 通过 document.head.prepend 进行style添加

**Comment by zombieJ** [comment]
@gaokaifeis 依赖顺序是不靠谱的，v5 的样式添加了 hashed 且提升了一部分样式优先级。如果确定有样式覆盖，应该通过 #id 提升优先级更为稳定。

**Comment by zombieJ** [comment]
@MadCcc 这个届时文档里要着重说一下。

**Comment by dancerphil** [comment]
这个说法略显激进，className 难道不是 antd 组件提供的 API 么，用 className 不能修改样式，应当认为是一个问题？

**Comment by zombieJ** [comment]
> 这个说法略显激进，className 难道不是 antd 组件提供的 API 么，用 className 不能修改样式，应当认为是一个问题？

className 可以覆盖样式，这里讨论的是加载顺序对应优先级的问题。

**Comment by afc163** [comment]
是不是应该尽量原位 insert 样式？

**Comment by zombieJ** [comment]
实验下来组件级别之间自身的 order 不重要，提上来也可以减少额外调整成本。改了。

**Comment by MadCcc** [comment]
看下来组件级别的顺序不重要。。但是复数主题的同一个组件的样式顺序还是有说法，后插入的永远会被覆盖了
