### ISSUE TITLE
antd版本从4.21.6升级到4.22.0以后drawer组件打开关闭有白底残留且extra中按钮显示异常

### ISSUE THREAD

**Issue by SmilingIdiot** [ant-design/ant-design#36741]
### Reproduction link

https://stackblitz.com/edit/react-h69b7g?file=package.json,demo.js

### Steps to reproduce

点击打开抽屉的按钮即可

### What is expected?

extra中的按钮横向展示；抽屉可以正常打开关闭

### What is actually happening?

extra中的按钮纵向展示；抽屉打开关闭时有白底

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 16.14.21 |
| System | macos |
| Browser | chrome 90.0.4430.212 |

---
突然迭代部署后线上就出问题了。。猝不及防，这种问题是不是还是要多测试下

**Comment by chencs-19950208** [comment]
我们也遇到类似的bug，希望尽快解决下，目前已经降版本，锁版本了

**Comment by chencs-19950208** [comment]
而且升级版本有段时间了，一直都好的，上周开始出现了这个bug，希望官方上线需要好好把控下质量

**Comment by afc163** [comment]
@chencs-19950208 最新版本应该已经修复了
