### ISSUE TITLE
AntD 补充图标建议

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#3674]
1.	信息技术图标
数据库
服务器
交换机
条码
打印机
多份的文件
拷贝
复制
粘贴
同步
漏斗（过滤）
沙漏
时钟
秒表
时间(带人的) 
望远镜
相机
分享
工具交叉
扳手
公文包
连接
断开连接
测试/检查
垃圾箱(更明显的) 
wifi
蓝牙
USB
发现（指南针）
铃铛
纸飞机
多语言
布局
换肤
进入（登录）
退出（登出）
头脑运转
Idea(灯泡) 
钥匙
声音
视频
标记（旗帜）
比例填充的圆
有信的信封

2.	业务相关图标
用户
人员信息
添加用户
删除用户
锁定用户
用户组
添加用户组
删除用户组
通讯录
赋权
删除权限
工作流
男士
女士
baby
家庭
男性符号
女性符号
商户
服务商（ISV）
代理人
沟通
议价
人际关系
合作伙伴
条码枪
扫码(扫一扫) 
付钱
ATM
POS
银行
保险
股票
贷款
账户
转账(双箭头账户) 
对账(打勾账户) 
签收
收益(扑满) 
收益(手接钱) 
业绩
保障(雨伞) 
钱袋子
钱包
药丸
周期
日历
日历完成
社交
美元符号
人民币符号
欧元符号
英镑符号
CopyRight符号
R 注册商标符号
账务明细
地球
城市
别针（附件，更明显的）
安全(盾) 
安全(带钱的盾) 
指纹
锁定收益
查询余额
公式
日历
计算器(更明显的)
算盘
天平
书（法律）
学位帽
汽车
摩托车
卡车
房屋
轮船
飞机
行李箱(出行) 
水电
物业费
VIP
铜钱
黄金
钻石
金币
皇冠
钞票
礼物
奖牌
奖杯
减(1个汉字) 
免(1个汉字)
赠(1个汉字)
罚(1个汉字)
收(1个汉字)
付(1个汉字)
赚(1个汉字)
成交(握手) 
赎回
蛋糕
咖啡杯（休息）
红包
公益
医药箱
受伤
住院
死亡(骷髅) 
信用卡
资产
身份证
骰子
抽奖
警察
小偷
火灾
台风
食物（碗筷）
卡券
卡券－已过期
卡券－已失效
判决（法槌）

**Comment by afc163** [comment]
...................

**Comment by afc163** [comment]
给点参考图标如何？

**Comment by Chinglik** [comment]
哈哈非常感谢你的建议，我们会仔细考虑并尽快补充哒~

**Comment by Chinglik** [comment]
哈哈非常感谢你的建议，我们会仔细考虑并尽快补充哒~

**Comment by bf185003** [comment]
To @afc163 ，我有列出参考图标，给伯约了，你找伯约要就行，或者找我，我是钟熊。

**Comment by afc163** [comment]
业务上的图标只能自己加，我们会筛选出通用的图标。

**Comment by JuelChiang** [comment]
### 1.	信息技术图标（2月18日完成）
1.数据库 
2.条码
3.打印机 
4.多份的文件
6.同步 
7.沙漏 
8.工具交叉
9.标记（旗帜）
10.扳手 
11.连接 
12.断开连接
13.测试/检查 
14.wifi
15.钥匙 
16.USB
17.发现（指南针） 
18.铃铛 
19.纸飞机 
20.声音 
21.布局 
22.换肤 
23.进入（登录） 
24.退出（登出）
25.Idea(灯泡)  
### 2.	业务相关图标（2月28日完成）
1.添加用户
2.删除用户
3.锁定用户
4.添加用户组
5.删除用户组
6.通讯录
7.男士
8.女士
9.医药箱
10.卡券
11.商户
12.银行
13.ATM
14.股票
15.账户
16.身份证
17.食物（碗筷）
18.收益(扑满)-钱袋
19.保障(雨伞)
20.日历完成
21.CopyRight符号
22.R 注册商标符号
23.地球
24.别针（附件，更明显的）
25.安全(盾)
26.红包
27.公益
28.钱包
29.汽车
30.轮船
31.飞机
32.奖杯
33.VIP
34.钻石
35.钞票
36.礼物
37.咖啡杯（休息）

**Comment by benjycui** [comment]
@JuelChiang  ???

**Comment by JuelChiang** [comment]
@benjycui 计划同步到这里一份
