### ISSUE TITLE
Antd theme '~antd/lib/style/themes/default.less' styles overriding '~antd/dist/antd.less' with form error messages

### ISSUE THREAD

**Issue by Rangyia** [ant-design/ant-design#36745]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-07ksw1?file=/index.js)

### Steps to reproduce

Add the following imports to the beginning of a React application that has less pre-processing set-up with webpack or vite:

@import '~antd/es/style/themes/default.less';
@import '~antd/dist/antd.less';

Use the following `Basic Example` form at this link: https://ant.design/components/form/

Click the 'submit' button from the example within your React application to force validation messages to populate on required fields.

### What is expected?

The forms should be setting the error messages on form fields to NOT be hidden.

### What is actually happening?

The forms are setting the following styles for error messages:

.ant-form-item-explain-connected {
  height: 0;
  min-height: 0;
  opacity: 0;
}

Which hides the error message.

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome, FireFox, Edge |

**Comment by Rangyia** [comment]
Styles:
![image](https://user-images.githubusercontent.com/49045807/181251392-b9a8a448-4bfe-496e-9904-d452ff699e15.png)

Reproduction:
![image](https://user-images.githubusercontent.com/49045807/181251303-8da55e98-bce6-43e4-a416-05f933e1390e.png)

**Comment by Rangyia** [comment]
Provided a link to the sandbox

**Comment by Rangyia** [comment]
> Hello @Rangyia. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @Rangyia, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

Provided a link to the sandbox

https://codesandbox.io/s/antd-reproduction-template-forked-07ksw1?file=/index.js

**Comment by afc163** [comment]
I can't see the styling problem in your codesandbox.

<img width="1003" alt="图片" src="https://user-images.githubusercontent.com/507615/181666018-dfddb3ba-3fa8-49a1-81fd-19ba761c1916.png">
