### ISSUE TITLE
Tooltip 中元素为button disabled = true时，导致修改的button默认样式失效

### ISSUE THREAD

**Issue by zsjincoder** [ant-design/ant-design#36740]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4rfptg)

### Steps to reproduce

1. 修改button样式
2. 设置disabled = true
3. 样式覆盖的样式丢失，antd处理后的代码如下，明显违背用户意愿

```html
<span class="anchor ant-tooltip-disabled-compatible-wrapper" style="display: inline-block; cursor: not-allowed;">
    <button type="button" disabled style="pointer-events: none;">xxx</button>
</span>
```

### What is expected?

保留用户原本的操作

### What is actually happening?

违背用户意愿

| Environment | Info |
| --- | --- |
| antd | 4.21.5 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
需修改html 元素时 请不要隐式更改

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/23961#issuecomment-625727358
