### ISSUE TITLE
Drawer 4.22.1 breaks width="500" usage

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#36754]
1. 这不是规范的用法，应该是 `width="500px"` 或者 `width={500}`，这是 [React 的约定](https://reactjs.org/docs/dom-elements.html)，但文档还是可以写清楚。
2. `4.21.7` 版本确实支持，比较诡异。https://codesandbox.io/s/ji-chu-chou-ti-antd-4-22-1-forked-2lqmdu?file=/demo.js 看上去还是得做个兼容。

**Comment by afc163** [comment]
文档的 PR：https://github.com/ant-design/ant-design/pull/36753

**Comment by legend80s** [comment]
确实需要兼容 否则就是 break change
