### ISSUE TITLE
表格将scroll.x设置为100%，不设置scroll.y时，所有列不固定的情况下，表格列宽均等分配了

### ISSUE THREAD

**Issue by dashaowang** [ant-design/ant-design#36751]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-22-1-forked-zbfr5o?file=/demo.js)

### Steps to reproduce

1、见重现连接，所有的列均有列宽，并且不设置固定列
2、将表格的scroll设置为{x:'100%'}

### What is expected?

表格出现滚动条，并且列宽和设置的列宽一致

### What is actually happening?

出现了滚动条，但是列宽均等分配了

| Environment | Info |
| --- | --- |
| antd | 4.22.1 |
| React | 17.0.2 |
| System | win10 |
| Browser | Microsoft Edge 99.0.1150.46 (正式版本) (64 位) |

---
查看了是因为table的table-layout属性的值为auto导致

**Comment by dashaowang** [comment]
出现问题是table-layout为auto，
![image](https://user-images.githubusercontent.com/40166750/181404574-292c594a-7e87-4372-89f1-5b47bd8fe63e.png)

设置table-layout为fixed是符合预期的
![image](https://user-images.githubusercontent.com/40166750/181404758-972b4933-c1b8-4410-8d1c-7feb3a1bacd8.png)

**Comment by afc163** [comment]
符合预期的，建议留一列不设宽度，否则就会按 table 原生方式被平均。

另外留这个 tableLayout 属性就是为了给用户选择权，没办法一刀切死渲染方式。

**Comment by dashaowang** [comment]
> 符合预期的，建议留一列不设宽度，否则就会按 table 原生方式被平均。
> 
> 另外留这个 tableLayout 属性就是为了给用户选择权，没办法一刀切死渲染方式。

有一列不设置也是会被均分

**Comment by afc163** [comment]
```
    scroll={{
      x: 'max-content',
    }}
```

**Comment by dashaowang** [comment]
> ```
>     scroll={{
>       x: 'max-content',
>     }}
> ```

好的  可以了  多谢大佬
