### ISSUE TITLE
 Can't resolve 'rc-table' in '/root/beta-umc-mono/node_modules/antd/es/table'

### ISSUE THREAD

**Issue by dohuuhuy** [ant-design/ant-design#36752]
### Reproduction link

[ https://umcmono-testing.medpro.com.vn/]( https://umcmono-testing.medpro.com.vn/)

### Steps to reproduce

./node_modules/antd/es/table/Table.js
Module not found: Can't resolve 'rc-table' in '/root/beta-umc-mono/node_modules/antd/es/table'

Import trace for requested module:
./node_modules/antd/es/table/index.js
./node_modules/antd/es/index.js
./pages/_app.tsx

./node_modules/antd/es/table/Table.js
Module not found: Can't resolve 'rc-table/es/hooks/useColumns' in '/root/beta-umc-mono/node_modules/antd/es/table'

Import trace for requested module:
./node_modules/antd/es/table/index.js
./node_modules/antd/es/index.js
./pages/_app.tsx

./node_modules/antd/es/table/Table.js
Module not found: Can't resolve 'rc-table/es/Table' in '/root/beta-umc-mono/node_modules/antd/es/table'

Import trace for requested module:
./node_modules/antd/es/table/index.js
./node_modules/antd/es/index.js
./pages/_app.tsx

./node_modules/antd/es/table/hooks/useSelection.js
Module not found: Can't resolve 'rc-table' in '/root/beta-umc-mono/node_modules/antd/es/table/hooks'

Import trace for requested module:
./node_modules/antd/es/table/Table.js
./node_modules/antd/es/table/index.js
./node_modules/antd/es/index.js
./pages/_app.tsx

> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### What is expected?

build not success

### What is actually happening?

Module not found: Can't resolve 'rc-table' in '/root/beta-umc-mono/node_modules/antd/es/table/hooks'

| Environment | Info |
| --- | --- |
| antd | 4.22.1 |
| React |  "react": "17.0.2", |
| System | 1 |
| Browser | 1 |

**Comment by zombieJ** [comment]
Please check your webpack or other build tool config instead. Module deps issue is not related with antd.

**Comment by dohuuhuy** [comment]
before there was no error related to webpack , web source has been working for 8 months, yesterday in hybrid build this error occurred.
