### ISSUE TITLE
antd最新版本组件Drawer缺失样式ant-drawer-open

### ISSUE THREAD

**Issue by zjtnumber2** [ant-design/ant-design#36757]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/drawer/style/drawer.less](https://github.com/ant-design/ant-design/blob/master/components/drawer/style/drawer.less)

### Steps to reproduce

查看antd源代码仓库master分支，查看drawer组件，发现缺少ant-drawer-open等相关样式，这些是dom结构依赖的

### What is expected?

对比以往antd版本，恢复drawer组件样式

### What is actually happening?

最新版本antd 4.22.1版本由于drawer组件缺少样式，导致显示不出来

| Environment | Info |
| --- | --- |
| antd | 4.22.1 |
| React | 16.8 |
| System | win10/Mac |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="1675" alt="图片" src="https://user-images.githubusercontent.com/507615/181441585-409cd3d3-dc95-433e-8268-b6bac5bad8f3.png">

貌似没问题。

**Comment by zombieJ** [comment]
显示样式不依赖 open className，提供一下重现看看？

**Comment by yizuierguo** [comment]
我们这边重现了这个问题～

**Comment by zombieJ** [comment]
> 我们这边重现了这个问题～

给个重现看看？
