### ISSUE TITLE
Table 增加一个 debug demo

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#3676]
类似这个例子：https://ant.design/components/tabs/#components-tabs-demo-position

上面是一个属性菜单，可以配置各种属性 size title footer 之类，下面可以预览对应的效果。

**Comment by yesmeck** [comment]
Table 要有哪些属性选项？

**Comment by benjycui** [comment]
主要是看 debug 需要，方便快速遍历 Table 各种属性的组合效果，只有有不少样式 bug 是因为没有遍历到。

先加简单的，后面根据需要可以继续加。
