### ISSUE TITLE
treeSelect set defaultValue or value no work

### ISSUE THREAD

**Issue by huya666** [ant-design/ant-design#36779]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-gou-xuan-antd-4-22-2-forked-fbgh1x?file=/demo.js:170-178)

### Steps to reproduce

1、 set value

### What is expected?

work

### What is actually happening?

![image](https://user-images.githubusercontent.com/34231749/181699413-6b36a885-723d-4fe7-96c3-6396b42e54f8.png)

no work

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.0.0 |
| System | macOS BigSur 11.5.2 |
| Browser | 版本 102.0.5005.115（正式版本） (arm64) |

**Comment by huya666** [comment]
有点难过，一天内我们发现了三个问题，其中有一个问题我们很多客户已感知并且向我们提出。也希望Antd团队每次更新时认真对待。

**Comment by afc163** [comment]
@huya666 antd 是开源项目，也期待你的贡献。

**Comment by huya666** [comment]
> @huya666 antd 是开源项目，也期待你的贡献。

团队人员 已向rc-overflow提出相关issues
https://github.com/react-component/overflow/issues/25

也请关注，感恩！

**Comment by huya666** [comment]
@afc163 团队已向rc-overflow提出issues
https://github.com/react-component/overflow/issues/25

也请关注，感恩！
