### ISSUE TITLE
input 开启 showCount 后当输入框包含emoji时 文本长度显示的不正确

### ISSUE THREAD

**Issue by 16code** [ant-design/ant-design#36773]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-zi-shu-ti-shi-antd-4-22-2-forked-zndxes?file=/demo.js)

### Steps to reproduce

输入👩‍👩‍👧‍👧 

### What is expected?

输入框字符长度统计应该按可视长度进行统计

### What is actually happening?

emoji 长度统计不正确

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.1.0 |
| System | macOS |
| Browser | Chrome |

**Comment by 16code** [comment]
![image](https://user-images.githubusercontent.com/5568503/181669114-65b98a8a-8a06-4fec-a498-01b58a6ac35e.png)

**Comment by marco5069** [comment]
https://juejin.cn/post/6945801630990204964   showCount 可以自定义下

**Comment by 16code** [comment]
> https://juejin.cn/post/6945801630990204964 showCount 可以自定义下

showCount 只能自定义显示格式
https://github.com/ant-design/ant-design/blob/51954aa470c03afe82f2e55c83d0755499805787/components/input/TextArea.tsx#L232-L239

**Comment by afc163** [comment]
我们可以在 showCount 里把原始 value 返回回去，方便开发者自行计算。

**Comment by afc163** [comment]
> 我们可以在 showCount 里把原始 value 返回回去，方便开发者自行计算。

@16code 就这点，方便来个 PR 不？

**Comment by JarvisArt** [comment]
我可以提个 PR

**Comment by JarvisArt** [comment]
> > 我们可以在 showCount 里把原始 value 返回回去，方便开发者自行计算。
> 
> @16code 就这点，方便来个 PR 不？

我可以提个 PR

**Comment by afc163** [comment]
> 我们可以在 showCount 里把原始 value 返回回去，方便开发者自行计算。

Supported in https://github.com/ant-design/ant-design/pull/36793
