### ISSUE TITLE
Drawer handler prop not being used

### ISSUE THREAD

**Issue by askurat** [ant-design/ant-design#36775]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-22-2-forked-8lltn9?file=/demo.js)

### Steps to reproduce

Create a Drawer component and add the handler prop.

### What is expected?

The handler should be added to the dom.

### What is actually happening?

It isn't being added to the dom.

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | react |
| System | Windows |
| Browser | Chrome |

---
In the previous version I was using: 4.21.3, the handler worked fine. 
Here is a reproduction of it working: https://codesandbox.io/s/basic-antd-4-22-2-forked-3gmcif?file=/demo.js

In the latest version: 4.22.2, it no longer works. If you look at the dom you will see it doesn't get added.
Here is the non-working reproduction: https://codesandbox.io/s/basic-antd-4-22-2-forked-8lltn9?file=/demo.js

**Comment by zombieJ** [comment]
> ### Can I use internal API which is not documented on the site?
> NOT RECOMMEND. Internal API is not guaranteed to be compatible with future versions. It may be removed or changed in some versions. If you really need to use it, you should to make sure these API is still valid when upgrading to a new version or just lock version for usage.

https://ant.design/docs/react/faq#Can-I-use-internal-API-which-is-not-documented-on-the-site
