### ISSUE TITLE
Form在vertical模式下，设置wrapperCol小于24并且不设置labelCol会变成一行

### ISSUE THREAD

**Issue by lq441028832** [ant-design/ant-design#36780]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-bu-ju-antd-4-22-2-forked-gk9056?from-embed=&file=/demo.js)

### Steps to reproduce

在表单项中ant-form-item下面多了一层ant-row ant-form-item-row节点，
但是  flex-direction: column;属性在ant-form-item节点上，导致下面的都失效了。

### What is expected?

layout="Vertical"未起作用

### What is actually happening?

layout="Vertical"起作用

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by huya666** [comment]
![image](https://user-images.githubusercontent.com/34231749/181707751-b817c832-6679-40f0-b4dc-8803f1d27842.png)

**Comment by 895433995** [comment]
老哥，vertical 的 v是小写

**Comment by xxcn-hj** [comment]
hei,bro,Vertical should be 'vertical'!

**Comment by lq441028832** [comment]
> 老哥，垂直的v是小写

...sorry，复制错了没注意

**Comment by lq441028832** [comment]
> hei,bro,Vertical should be 'vertical'!

谢啦。示例已经修改好了

**Comment by 895433995** [comment]
> 

antd 这个没问题，就保留一个 layout="vertical"就行了，不需要设置 labelCol 和 wrapperCol

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/ant-design/pull/36575#issuecomment-1199017020
