### ISSUE TITLE
当第一次渲染组件被隐藏时，Typography的Text组件的ellipsis属性无法展示tooltip

### ISSUE THREAD

**Issue by littleee** [ant-design/ant-design#36786]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-cohen-0ni1ku?file=/src/App.js:459-467)

### Steps to reproduce

1.点击按钮使隐藏的文字显示
2.鼠标悬停在文字上， 无法展示tooltip

### What is expected?

正常展示tooltip

### What is actually happening?

无法展示tooltip

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome103.0.5060.114（正式版本） (arm64) |

**Comment by fmkeke233** [comment]
我准备开始解决这个问题
