### ISSUE TITLE
select组件showArrow为false和loading为true时，loading图标未显示

### ISSUE THREAD

**Issue by chengwb53** [ant-design/ant-design#36789]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-2-forked-oyjqz6)

### Steps to reproduce

select组件，showArrow设置为false，loading设置为true时，loading图标未显示

### What is expected?

select组件，showArrow设置为false，loading设置为true，loading图标可以正常显示

### What is actually happening?

select组件，showArrow设置为false，loading设置为true时，loading图标未显示

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.1.0 |
| System | window10 64位 |
| Browser | chorme 103.0.5060.134（正式版本）（64 位） |

---
loading状态建议放入下拉列表中

**Comment by afc163** [comment]
loading 是利用 showArrow 位置的图标来实现的，如果显式声明不使用 showArrow，则没有地方可以展示。

> loading状态建议放入下拉列表中

建议用 notFoundContent 来自定义类似效果。
