### ISSUE TITLE
Form组件在vertical布局结构下面，如果wrapperCol和labelCol不超过24会导致不换行

### ISSUE THREAD

**Issue by oneQiu** [ant-design/ant-design#36783]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-bu-ju-antd-4-22-2-forked-cjo1fi?file=/demo.js)

### Steps to reproduce

1. Form组件设置layout为vertical
2. wrapperCol 设置 span为12
3. labelCol 设置span为12

### What is expected?

我期望的就是设置了vertical就是垂直布局，而不是配合span去控制。之前的4.19版本就是没问题，升级到最新版本就会如此。

### What is actually happening?

label和wrapper组件并没有换行成功，在同一行

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 17.0.1 |
| System | macOS 11.6 |
| Browser | Chrome 版本 103.0.5060.134（正式版本） (x86_64) |

---
如果是需要垂直布局，同时我需要限制label和wrapper只占用10，我不想太宽，那换行就无效了。

**Comment by drizzlesconsin** [comment]
在 `4.22.0` 会有这个问题，可以先退到 `4.21.7`。

感觉跟这个有关 https://github.com/ant-design/ant-design/pull/36575
