### ISSUE TITLE
antd4 TextArea 写了autoSize属性后，渲染时会闪动

### ISSUE THREAD

**Issue by GonsonInter** [ant-design/ant-design#36788]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/20674](https://github.com/ant-design/ant-design/issues/20674)

### Steps to reproduce

和重现链接中的链接描述的差不多，但是antd版本、浏览器都不同

### What is expected?

不要闪动

### What is actually happening?

页面复杂的时候，首先会出现基础的可以调整的textarea，即高度默认，右下角出现可以拖动的三角，然后恢复正常，这个过程整个textarea的样式、高度都会变化，影响到用户体验

| Environment | Info |
| --- | --- |
| antd | 4.20.5 |
| React | 17 |
| System | Mac 12.4 |
| Browser | Chrome。版本 103.0.5060.134（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/36556
