### ISSUE TITLE
Select does not properly assign values to options.

### ISSUE THREAD

**Issue by DylanAlloy** [ant-design/ant-design#36795]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g0hkkh?file=/index.js)

### Steps to reproduce
```
    <AutoComplete
      dropdownMatchSelectWidth={250}
      notFoundContent="No records found, try adding one"
      style={{
        width: 250,
        paddingBottom: 24,
      }}
      onSelect={(_, val) => {
        console.log(_, val)
      }}
      options={[
        {
          "value": true,
          "label": "1.cms.ccntr.spctrm.net"
        },
        {
          "value": true,
          "label": "2.cms.ccntr.spctrm.net"
        }
      ]}
    />
```

### What is expected?

Look at the values that console logs compared to the name you have selected.

### What is actually happening?

Antd is not instantiating values properly in select lists.

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 17.8 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by DylanAlloy** [comment]
> The value of the value field needs to be unique.

Thank you. I will have to restructure my data to accommodate this pattern but I appreciate the simple correction.

**Comment by dmitry-sidorov** [comment]
> The value of the value field needs to be unique.

Not always. I have a case with a city selector. I have a custom render for options. Options are objects with unique property `key` and some of `value` properties are not unique. (We have 2 cities with the same name, but different regions, what a suprise!). 

As a developer, I expect anything: throwing a warning/error, but not selecting a random value without any log messages!
Such a bad case of API design.

Unique `key` is not enough. I have to write custom work-around! 😎 

Throw an error in future versions, please! Fail fast is the best approach.
