### ISSUE TITLE
ConfigProvider 中 getPopupContainer，不能对 message Modal.confirm 生效

### ISSUE THREAD

**Issue by tipsxBase** [ant-design/ant-design#36792]
### What problem does this feature solve?

ConfigProvider 中 getPopupContainer，不能对 message、 Modal.confirm 等弹出组件生效

### What does the proposed API look like?

ConfigProvider 中 getPopupContainer，可以对 message、 Modal.confirm 等弹出组件生效

**Comment by afc163** [comment]
这是符合预期的，你需要 https://ant.design/components/message-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-message-%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-%E7%9A%84-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F
