### ISSUE TITLE
Transfer组件后端渲染问题

### ISSUE THREAD

**Issue by machao23** [ant-design/ant-design#3680]
使用了 https://ant.design/components/transfer/ 的演示代码第一个例子。
![image](https://cloud.githubusercontent.com/assets/5095336/19888975/295b130e-a06d-11e6-8231-99b9b03f22a7.png)

浏览器控制台报错：
![image](https://cloud.githubusercontent.com/assets/5095336/19888983/37e65c94-a06d-11e6-8da5-37f4324d3440.png)

**Comment by afc163** [comment]
对，不能用 Math.random 来渲染，前后端渲染结果要保持一致。这里只是个演示，就不修改了，业务代码里要自行保证。
