### ISSUE TITLE
overriding 'icon-font-prefix' variable require a class selector

### ISSUE THREAD

**Issue by yarinsa** [ant-design/ant-design#36809]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-r0tqjp?file=/index.js)

### Steps to reproduce

1. Change icon prefix to other selector then class (using modifyVars, configProvider or etc.) (I chose [class*='fa-'] to target font-awesome)
2. render `<Button icon={<FontAwesomeIcon icon={faGoogle}/>} `// or any other icon
3. The space between the text and icon doesn't exist (relying on the class nor the selector)

### What is expected?

The output css will be according to selector and not class
.ant-btn [class*='fa-']{
margin-right: 1em
}

### What is actually happening?

.ant-btn .[class*='fa-']{
margin-right: 1em
}

| Environment | Info |
| --- | --- |
| antd | 4.18.8 |
| React | 17.0.2 react |
| System | Mac OS X |
| Browser | Chrome |

**Comment by MadCcc** [comment]
> .ant-btn .[class*='fa-']{
> margin-right: 1em
> }

You can write this in your own code.

**Comment by yarinsa** [comment]
@MadCcc But then I will have to override every single case of the icon. Which kind of break the "override" idea, dont you agree?
