### ISSUE TITLE
当采用样式覆盖的方式变更主题色会出现部分组件依旧采用旧的主题色

### ISSUE THREAD

**Issue by strivelen** [ant-design/ant-design#36804]
### Reproduction link

[https://github.com/strivelen/cra-ant-admin/commit/8a7a23dd12790271c99d9c6fec5eca6a8f12294a](https://github.com/strivelen/cra-ant-admin/commit/8a7a23dd12790271c99d9c6fec5eca6a8f12294a)

### Steps to reproduce

当我采用以less变量覆盖的方式来改变antd主题色时，根据https://ant.design/docs/react/replace-moment-cn此站点配置方式来替换 Moment.js后，此文档中的配置代码 `import 'antd/es/date-picker/style/index';` 和 `import 'antd/es/calendar/style';` 会造成在渲染时DatePicker和Calendar组件的同级组件主题色失效问题，我认为是这两行样式代码把antd的原来样式又引入了一遍覆盖了我的自定义主题色变量，从而导致出现部分组件依旧采用旧的主题色。

### What is expected?

https://ant.design/docs/react/replace-moment-cn文档中是否需要调整移除上文中提到的这两行代码，因为antd本身样式就需要一次全局导入

### What is actually happening?

我删除上面提到的`DatePicker`和`Calendar`组件中的两行样式后，此时就不再出现部分组件自定义主题色失效的问题。

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 18.1.0 |
| System | window |
| Browser | chrome |

---
只是给文档提点意见，望采纳。这个bug是只要采用全局less变量覆盖的方式更改主题色，后期如果有部分子组件导入了antd样式，那么就会覆盖掉全局定义的自定义less变量。

**Comment by afc163** [comment]
确实可以删掉，来个 PR 吧
