### ISSUE TITLE
Upload组件闪屏

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/ant-design#36818]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhao-pian-qiang-antd-4-21-7-forked-9ml89v?file=/package.json:189-195)

### Steps to reproduce

随便上传什么东西（大于1个）
任意删除一个
会出现闪屏

### What is expected?

不出现闪屏

### What is actually happening?

出现了闪屏

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.2.0 |
| System | codesandbox |
| Browser | codesandbox |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35390

**Comment by afc163** [comment]
预计今天
