### ISSUE TITLE
event.preventDefault() seems not working in onSearch Antd Input Search

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#36816]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/search-box-antd-4-22-2-forked-p6g6ir?file=/demo.js)

### Steps to reproduce

Type any special characters to trigger the regex validation

### What is expected?

Should not be able to click the search button when there is an error
event.preventDefault() should be enough to handle the button functionality to disabled the search function

### What is actually happening?

Still able to logged or search inputted value

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 17.0.2 |
| System | Mac Os Monterey |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
`preventDefault` is native HTML event process. It's not related with your business logic:
https://codesandbox.io/s/search-box-antd-4-22-2-forked-2mtln5

**Comment by tempoeric** [comment]
nice thanks @zombieJ i thought the event parameter was used to handle these scenarios thanks for pointing this out
