### ISSUE TITLE
Form表单中的Select组件加入labelInValue属性报错

### ISSUE THREAD

**Issue by monsuns** [ant-design/ant-design#3681]
#### 发生问题的环境是：

- antd 版本: 2.2
- 操作系统及其版本: windows 10
- 浏览器及其版本:  chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

引入Form包装表单,表单中含有Select组件, 在为Select添加 labelInValue 输出带有标签内容的结果时报错,提示无法为字符串设置值, 如无 labelInValue 属性Form表单收集的结果正常且不会报错.

#### 您期待的结果是:

使用Form收集的表单结果中包含Select组件已选择的 value 和 label 两个值. 

#### 实际上的结果是:

目前Select加入 labelInValue 会报错, 不加只能收集到一个值.

#### 可重现的在线演示

http://codepen.io/monsuns/pen/ZpgJbb?editors=1010

演示中包含注解.错误信息需要打开控制台才能看到. 不知是我调用有问题还是哪里错了, 望大神解惑....

**Comment by yesmeck** [comment]
labelInValue 的时候要这样 `initialValue: { key: "1" }`。

**Comment by monsuns** [comment]
@yesmeck 非常感谢!! 看起来正常了~
