### ISSUE TITLE
在flex布局下，缩放浏览器后，Table组件变得很宽，但是在浏览器缩放比例恢复成100%时，Table组件的宽度依然是缩放的时候产生的最大宽度

### ISSUE THREAD

**Issue by 962464zyy** [ant-design/ant-design#36827]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-panna-vhvth0?file=/src/styles.css)

### Steps to reproduce

1. 缩小浏览器分辨率
2. 恢复成100%分辨率，table组件的宽度是缩放期间的最大宽度

### What is expected?

期望在下个版本解决Table组件在flex布局下的问题

### What is actually happening?

1

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | react |
| System | Win64 |
| Browser | chrome 103 |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/upbeat-chatelet-qxoroy?file=/src/styles.css
