### ISSUE TITLE
getCurrentAnchor 的值保存为状态后，无法在状态变化的时候，立即刷新view

### ISSUE THREAD

**Issue by DanielLeefu** [ant-design/ant-design#36832]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-mao-dian-gao-liang-antd-4-22-2-forked-tsrh44?file=/demo.js)

### Steps to reproduce

如codesandbox，使用state 保存状态后，getCurrentAnchor高亮的值。点击两次才会变化，页面高亮才会变化

### What is expected?

状态变化后，页面立即变化

### What is actually happening?

状态变化后，页面不会立即变化

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by xccjk** [comment]
react是异步更新的，getCurrentAnchor使用的是更新后的值...

demo: [https://codesandbox.io/s/zi-ding-yi-mao-dian-gao-liang-antd-4-22-2-forked-3nhe3k?file=/demo.js](https://codesandbox.io/s/zi-ding-yi-mao-dian-gao-liang-antd-4-22-2-forked-3nhe3k?file=/demo.js)

**Comment by MadCcc** [comment]
https://codesandbox.io/s/zi-ding-yi-mao-dian-gao-liang-antd-4-22-2-forked-3qlfbf?file=/demo.js
闭包问题，换成 ref 可以
