### ISSUE TITLE
Form bug

### ISSUE THREAD

**Issue by Miller-Wang** [ant-design/ant-design#36836]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce

4.22版本之后 ant-form-item 下多了一个dom层级，导致布局错乱

### What is expected?

布局正常

### What is actually happening?

布局错乱

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 16.8 |
| System | mac |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/62501739/182184813-d52a1f5a-f2dd-4b08-a2cc-39e4d098f5cf.png)

**Comment by EchoVie** [comment]
I also hit with this problem too. When i use nested component of FormItem，it will add a DOM element with classname of ant-form-item-row into the DOM tree;

![image](https://user-images.githubusercontent.com/57256068/182279147-cc8a0de1-f8c0-4153-a846-7f7a3578e2f4.png)

**Comment by afc163** [comment]
@EchoVie Could you provide a codesandbox?

**Comment by EchoVie** [comment]
> @EchoVie Could you provide a codesandbox?

https://codesandbox.io/s/antd-reproduction-template-forked-pfbm53?file=/index.js

**Comment by EchoVie** [comment]
> @EchoVie Could you provide a codesandbox?

![image](https://user-images.githubusercontent.com/57256068/182326790-c50c931c-fdab-41e8-af27-0e51e545a63b.png)

Row component is which makes it wrong ...

**Comment by Miller-Wang** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-f2kvkc

找到问题了，封装组件的时候给`ant-form-item`设置了flex样式导致的，已处理
