### ISSUE TITLE
DatePicker日期选择框的API中 "size" 属性描述问题

### ISSUE THREAD

**Issue by mgu-x** [ant-design/ant-design#36838]
### Reproduction link

[https://github.com/react-component/picker/blob/abbe6affe798dda8f8434b6bcff6733826524414/src/utils/uiUtil.ts#L192](https://github.com/react-component/picker/blob/abbe6affe798dda8f8434b6bcff6733826524414/src/utils/uiUtil.ts#L192)

### Steps to reproduce
DatePicker日期选择框的API中 [size](https://ant-design.antgroup.com/components/date-picker-cn/#API:~:text=4.17.0-,size,-%E8%BE%93%E5%85%A5%E6%A1%86%E5%A4%A7%E5%B0%8F)的描述是针对于输入框的高度和宽度，这里的size有点像input输入框本身的size属性。会出现一个问题，我们如何去影响内置的size大小？我看见rc-picker 对内置 Input 组件的size属性是通过format的长度去设置内置size属性的。我们除了修改format的长度以外，就不能通过其他方式去影响Input本身的size大小。

### What is expected?

期望通过自定义属性的方式来影响到内部属性size的大小

### What is actually happening?

可以自定义size的大小

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | * |
| System | * |
| Browser | * |

---
当DatePicker的placeholder设置的长度超过内置input的size时，会出现placeholder省略的情况

**Comment by afc163** [comment]
具体问题是啥，提供重现吧~

**Comment by afc163** [comment]
```jsx
<DatePicker style={{ width: 300 }} />
```

可以这样来定义宽度。

**Comment by mgu-x** [comment]
不是DatePicker的宽度，是内置的input的size

**Comment by afc163** [comment]
@mgu-x 提供一个问题重现？

**Comment by mgu-x** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/44564391/182284063-9e8a617b-53b0-4c88-a33d-93f0e249fb81.png">
看看这个图片中的size是17，我是通过设置format传入的字符串的长度强行改为17

**Comment by mgu-x** [comment]
在外部通过style设置宽度不能影响input本身的size吧？

**Comment by mgu-x** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-h7x843?file=/index.js
设置宽度可以改变省略的问题，但是内置的input的size是根据format长度+2来判断的？

**Comment by afc163** [comment]
对，size 也是 input 宽度的一种标识方式。能直接用 width 解决就好。

**Comment by mgu-x** [comment]
好，谢谢
