### ISSUE TITLE
flex布局下,Table组件在浏览器缩放后渲染宽度变宽

### ISSUE THREAD

**Issue by 962464zyy** [ant-design/ant-design#36830]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-panna-vhvth0?file=/src/index.js)

### Steps to reproduce

1.缩小浏览器分辨率
2.恢复成100%分辨率，table组件的宽度是缩放期间的最大宽度

### What is expected?

期望解决Table组件在flex布局下的问题

### What is actually happening?

1

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | react |
| System | Win64 |
| Browser | chrome 103 |

**Comment by xccjk** [comment]
demo: [https://codesandbox.io/s/thirsty-parm-3m235c?file=/src/App.js](https://codesandbox.io/s/thirsty-parm-3m235c?file=/src/App.js)

issue: [(#28158)](https://github.com/ant-design/ant-design/issues/28158)
