### ISSUE TITLE
bug: Modal 组件在 React18 中关闭会出现虚影。

### ISSUE THREAD

**Issue by iolh** [ant-design/ant-design#36837]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-kdzt5u?file=/index.js)

### Steps to reproduce

打开弹窗。点击关闭。
偶发现象，可多次点击关闭复现。

### What is expected?

不存在虚影

### What is actually happening?

弹窗虚影闪现

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.2 |
| System | win11 |
| Browser | chrome 103.0.5060.134 |

**Comment by afc163** [comment]
没重现，能给个 gif 或录屏么

**Comment by iolh** [comment]
[基本 - antd@4.22.3 (forked) - CodeSandbox - Google Chrome 2022-08-02 10-33-30.zip](https://github.com/ant-design/ant-design/files/9238609/-.antd%404.22.3.forked.-.CodeSandbox.-.Google.Chrome.2022-08-02.10-33-30.zip)

**Comment by iolh** [comment]
没重现可以尝试刷新下，刷新下容易复现

**Comment by iolh** [comment]
> 没重现，能给个 gif 或录屏么

和这个有些类似 https://github.com/ant-design/ant-design/issues/36174#issue-1279701988

**Comment by afc163** [comment]
你本地使用 antd 最新版本，移除 lock 文件后重新安装 node_modules，还能复现么

**Comment by iolh** [comment]
> 你本地使用 antd 最新版本，移除 lock 文件后重新安装 node_modules，还能复现么

使用最新的4.22.3版本，仍旧会出现这个弹窗闪烁问题。

**Comment by iolh** [comment]
使用 React18 的 ReactDOM.createRoot 就会出现此问题。
ReactDOM.render 则不会。

> 你本地使用 antd 最新版本，移除 lock 文件后重新安装 node_modules，还能复现么

看上面那个 issue。问题应该是同一个，只不过那个只修复了 Menu 组件。

**Comment by afc163** [comment]
trace #36911
