### ISSUE TITLE
一个 antd@2.2.0 版本 DatePicker 的Issue

### ISSUE THREAD

**Issue by ssruoyan** [ant-design/ant-design#3684]
关于antd@2.2.0 的 DatePicker 组件：

我在添加了showTime这个属性之后无法选择时间。
<img width="525" alt="2016-11-01 22 45 35" src="https://cloud.githubusercontent.com/assets/8360309/19893713/1203777e-a085-11e6-9162-00114bdeae94.png">

通过调试 createPicker 组件里面的 handleChange 方法，发现取到的 value 是 undefined
<img width="1320" alt="2016-11-01 22 45 49" src="https://cloud.githubusercontent.com/assets/8360309/19893716/15355d7c-a085-11e6-9684-ac619419aa81.png">

去掉showTime 或者去掉 Form 相关的组件就可以正常使用。

code pen 地址：
[http://codepen.io/hore/pen/zKgaPL](http://codepen.io/hore/pen/zKgaPL)

还有在使用moment 这个库之后。每次选择时间获取的 moment 对象里面的值 和 DateString的值相差8个小时。moment对象的 locale addr 是 ”zh-cn“。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3665

**Comment by benjycui** [comment]
时差问题参考 https://ant.design/components/form/#components-form-demo-time-related-controls

提问前应该先搜索一下。
