### ISSUE TITLE
TreeSelect 组件中 treeExpandAction 属性问题

### ISSUE THREAD

**Issue by g17628381307** [ant-design/ant-design#36842]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-ozkg10?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

我设置了treeExpandAction 属性为 click , 当我点击TreeNode中的Title时， 展开子节点后会选中后关闭下拉框
实际上我的Ant design版本是 4.9.4， 我无法在版本选择栏中选择到这个版本

### What is expected?

我期望当属性为click时， 点击父节点的title能够和展开图标的功能一样，不要选中和关闭下拉框

### What is actually happening?

当我点击TreeNode中的Title时， 展开子节点后会选中后关闭下拉框

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 17.0.1 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
感觉这个属性有点问题，TreeSelect 里点击是展开的话就没办法选中了

**Comment by g17628381307** [comment]
> 

我认为这个属性它的意义就是在于， 让父节点Title的功能局限于展开和收起， 如果他在展开和收起之后还是会选中当前父节点的value并且关闭下拉框， 很奇怪哇

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/34200#issuecomment-1061749566

**Comment by afc163** [comment]
@NE-SmallTown 看看这个问题，在 TreeSelect 开启之后，点击展开也会关闭 select，这个交互确实奇怪。

**Comment by g17628381307** [comment]
> 

使用treeExpandAction这个属性的时候， 将父节点selectable设置为false（不可选状态） 这两个属性搭配一起使用， 可以得到我想要的，仅展开但不选中的效果

**Comment by afc163** [comment]
我知道了，selectable 要放在节点上。

**Comment by afc163** [comment]
那预期就是 https://github.com/ant-design/ant-design/issues/34200#issuecomment-1061749566 描述的那样。

**Comment by NE-SmallTown** [comment]
> 使用treeExpandAction这个属性的时候， 将父节点selectable设置为false（不可选状态） 这两个属性搭配一起使用， 可以得到我想要的，仅展开但不选中的效果

是的，需要设置 `selectable` 为 `false`

**Comment by aaronxdd** [comment]
觉得treeExpandAction属性应该内部跟父节点做下selectable互斥，而不是还要去额外配置下父节点selectable false
