### ISSUE TITLE
看文档FormItem的getValueFromEvent 和 normalize是可以相互转化的， 那为什么form.getFieldsValue()取该值的时候，值却是 normalize转化结果，而非getValueFromEvent格式化结果

### ISSUE THREAD

**Issue by JokerDr** [ant-design/ant-design#36850]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](  https://codesandbox.io/s/biao-dan-chi-cun-antd-4-22-0-forked-n0pxiz?file=/demo.js:271-292)

### Steps to reproduce

codeBox链接已发

### What is expected?

form.getFieldsValue()取该值的时候，值是 getValueFromEvent转化结果

### What is actually happening?

form.getFieldsValue()取该值的时候，值却是 normalize转化结果，而非getValueFromEvent格式化结果，这样一来，感觉normalize意义不大，本以为二者能相互配合

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | 16.14 |
| System | macos 10.15.7 (19H1217) |
| Browser | chrome |

**Comment by afc163** [comment]
这两者实际上是同一个阶段的两个步骤，其实有点多余。getFieldsValue 拿到的是 normalize 后的结果。

**Comment by projectcss** [comment]
> 。
那为什么最终用Form.Item包裹的组件的value值也会设置成normalize后的值

**Comment by projectcss** [comment]
> > 。
> > 那为什么最终用Form.Item包裹的组件的value值也会设置成normalize后的值

这样会导致最终显示出来的值是错误的，我觉得normalize是不是可以做成一个纯转换的函数，getValues时会拿到转换后的值，但是不会影响Form.Item包裹的组件的value值
