### ISSUE TITLE
能不能在antd5中保留菜单jsx拼接的写法

### ISSUE THREAD

**Issue by rxdrag** [ant-design/ant-design#36852]
### What problem does this feature solve?

保留jsx拼接的写法，可以使用react-dnd等插件，拖放菜单项目，动态编辑菜单。要是取消jsx拼接的话，这个能力就没了。现在低代码项目这么流行，这个需求还是蛮大的。

### What does the proposed API look like?

```<Menu>
  <Menu.Item>菜单项一</Menu.Item>
  <Menu.Item>菜单项二</Menu.Item>
  <Menu.SubMenu title="子菜单">
    <Menu.Item>子菜单项</Menu.Item>
  </Menu.SubMenu>
</Menu>;
```

**Comment by zombieJ** [comment]
会提供兼容包，兼容包里还是可以使用该方式书写。
