### ISSUE TITLE
DatePicker能否加一个属性defaultOpen

### ISSUE THREAD

**Issue by CalvinP-Cai** [ant-design/ant-design#36855]
### What problem does this feature solve?

当使用键盘操作时，从上一个输入框跳转到DatePicker，回车回打开DatePicker的panel，但光标跳到下一个可输入的框内

### What does the proposed API look like?

聚焦时，自动展开panel

**Comment by CalvinP-Cai** [comment]
可以支持，属性为放开

**Comment by afc163** [comment]
可以使用 open 属性。

**Comment by CalvinP-Cai** [comment]
> 可以使用 open 属性控制。

这个就是受控了，我的想法是，ref手动聚焦然后可以把panel展开

**Comment by afc163** [comment]
受控的问题是啥？

**Comment by CalvinP-Cai** [comment]
> 受控的问题是啥？

需要定义个state，我不想去刷新
