### ISSUE TITLE
dropdown contextmenu 在ipad取消浏览器默认事件

### ISSUE THREAD

**Issue by MTCherish** [ant-design/ant-design#36864]
### Reproduction link

[https://antdv.com/components/dropdown-cn](https://antdv.com/components/dropdown-cn)

### Steps to reproduce

引用dropdown组件在ipad上 触发事件是 contextmenu，但是长按会触发默认事件，但是安卓机交流良好

### What is expected?

不触发默认事件

### What is actually happening?

会触发

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | vue |
| System | ios |
| Browser | chrome |

**Comment by MTCherish** [comment]
请问有人遇到过么

**Comment by afc163** [comment]
反馈错仓库了。

**Comment by qingweiSun** [comment]
没反馈错吧，确实有这个问题

**Comment by afc163** [comment]
@qingweiSun 上面给的链接是 vue 的。

**Comment by qingweiSun** [comment]
嗷嗷，react 存在相同的问题呢。ios上长按不会触发类似右键的操作

**Comment by afc163** [comment]
需要怎么改比较好呢？

**Comment by qingweiSun** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/16513906/236593161-d7ea5152-2368-4e56-9159-9dd11ca62cba.png">
j 就是我想要这种，长按会触发菜单，但是在 ios 上会触发类似放大镜的效果，

**Comment by afc163** [comment]
欢迎来个 PR。
