### ISSUE TITLE
datapicker 日期范围选择 预设常用日期范围 位置配置化

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#36860]
### What problem does this feature solve?

datapicker 日期范围选择 预设常用日期范围 位置配置化
DatePicker 日期范围选择 预设常用日期范围，目前看是在下面显示，是否可以在左边显示，或者做成配置项，用户可以自定义

### What does the proposed API look like?

DatePicker 日期范围选择 预设常用日期范围，目前看是在下面显示，是否可以在左边显示，或者做成配置项，用户可以自定义
![image](https://user-images.githubusercontent.com/5828057/182505077-54dc411c-8022-46f6-9958-812fb204b2f0.png)
![image](https://user-images.githubusercontent.com/5828057/182505089-941932ca-edb1-45fb-b1e1-3a15d6e007cd.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/15199

**Comment by wsxe9988** [comment]
目前最新版是否实现了侧边栏显示快捷时间呢

**Comment by afc163** [comment]
还没有。

**Comment by afc163** [comment]
@MadCcc @zombieJ V5 可以加上这个。

**Comment by MadCcc** [comment]
记一条

**Comment by wsxe9988** [comment]
嗯，赞，确实放到左边，竖着排列，能呈现的更多，更易于操作

**Comment by IloveKFCchicken** [comment]
@MadCcc 关于这个需求，目前用panelRender来自己实现，但是碰到一个问题，自定义的click事件无效.
请问是组件中有加阻止冒泡之类的操作吗？

代码示例如下
https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-l5mymf?file=/demo.js

![image](https://user-images.githubusercontent.com/19233255/183333016-37f04f4a-15c4-4cb5-807c-c2cf54562bbe.png)

**Comment by umagon** [comment]
This would be okay if we could mimic the hover behaviour of the onboard presets. Is there any way? They way it shows a preview when hovering on those presets?

**Comment by MadCcc** [comment]
Implemented in v5, please feel free to open new issue if have any other problems.

**Comment by liulib** [comment]
> Implemented in v5, please feel free to open new issue if have any other problems.

大佬 文档没更新吗 现在默认在侧边 我要在放在底部的话要怎么配置呀😔

**Comment by 33sauhdsbu** [comment]
> Implemented in v5, please feel free to open new issue if have any other problems.

Dude, what do I want to do with the original, not the lower version
