### ISSUE TITLE
分页器使用position: sticky固定在底部，点击分页选择弹出选框时仍然朝下弹出会被遮挡。

### ISSUE THREAD

**Issue by jxccc1998** [ant-design/ant-design#36866]
### What problem does this feature solve?

列表数据多时不希望滚动表格，通过滚动整个页面来浏览更多的数据，此时需要将表头吸附顶部，分页器吸附在底部。

### What does the proposed API look like?

分页器使用sticky时，弹出能朝向正确的方向，或者为pagination提供一个弹出方向的属性

**Comment by jxccc1998** [comment]
[https://codesandbox.io/s/antd-reproduction-template-forked-e6eygk](url)

**Comment by afc163** [comment]
<img width="883" alt="图片" src="https://user-images.githubusercontent.com/507615/182531321-d955fa33-dc2e-4ac5-b3a6-9bde769e4d46.png">

**Comment by jxccc1998** [comment]
[https://codesandbox.io/s/gifted-sara-vphk58?file=/index.js](url)

**Comment by afc163** [comment]
https://github.com/yiminghe/dom-align/blob/7110744d1b4d2f0e76d8f9e120127787c260ba71/src/isAncestorFixed.js#L20

需要处理 sticky 的情况。

**Comment by GeraltX** [comment]
这个没下文了吗。。。

**Comment by chenxiaochun** [comment]
> https://github.com/yiminghe/dom-align/blob/7110744d1b4d2f0e76d8f9e120127787c260ba71/src/isAncestorFixed.js#L20
> 
> 需要处理 sticky 的情况。

那，现在 antd 还没有更新？

**Comment by chenxiaochun** [comment]
去年8月份的问题，到现在没下文了吗？

**Comment by chenxiaochun** [comment]
> https://github.com/yiminghe/dom-align/blob/7110744d1b4d2f0e76d8f9e120127787c260ba71/src/isAncestorFixed.js#L20
> 
> 需要处理 sticky 的情况。

我在本地调试了一下，果然是这个地方的问题，我给他提一个 Pull Request

**Comment by chenxiaochun** [comment]
那个作者好像不维护那个库了？我看他去年的 PullRequest 都还没有处理

**Comment by MadCcc** [comment]
antd 后续不用 dom-align 了

**Comment by chenxiaochun** [comment]
那请问，大概啥时候会解决这个问题？

**Comment by zhengmenghuang** [comment]
插眼

**Comment by Emily-0616** [comment]
@afc163  目前这个问题有跟进吗

**Comment by afc163** [comment]
@MadCcc @zombieJ 换了依赖后貌似还没解。https://codesandbox.io/s/intelligent-rui-d4k5o0?file=/index.js

**Comment by zombieJ** [comment]
> antd 后续不用 dom-align 了，这个问题在底层都换成 @rc-component/trigger 之后可以解

替换了 `@rc-component/trigger` 本身也不会默认调整现在的处理逻辑。只要屏幕可以滚动，它还是会按照滚动区域来，应该需要提供一个 CP 支持全局设置 Select 的 `popupAlign` 逻辑用于覆盖。

**Comment by afc163** [comment]
这个得修吧，不是靠 popupAlign 来处理。

**Comment by zombieJ** [comment]
> 这个得修吧，不是靠 popupAlign 来处理。

对于 `sticky` 向下滚动仍然是可以滚动到的：
![Kapture 2023-03-29 at 15 21 21](https://user-images.githubusercontent.com/5378891/228457279-7049797a-0ef4-4c1b-93da-daf5c4a1f8b9.gif)

这个之前讨论过，对于 Tooltip 提示类为窗口可见区域，下拉菜单是否也要调整成可见区域：

> @zombieJ: 这里想聊一下类 Select 组件的弹层定位。在之前版本里，只要 window 有滚动空间，就不会转方向。原因是防止搜索态来回上下跳跃。但是相对而言，这种跳跃我自己感觉是比较少的场景，反而是在页面可见区域展示会更重要一些。所以我在想是否要保留原来的区域检测形式？滚动的区域不算裁剪
> @arvinxx: 默认应该不翻转吧。这种翻转的CLS太大了。

**Comment by afc163** [comment]
两个问题。

1. 这里想聊一下类 Select 组件的弹层定位。在之前版本里，只要 window 有滚动空间，就不会转方向。原因是防止搜索态来回上下跳跃。但是相对而言，这种跳跃我自己感觉是比较少的场景，反而是在页面可见区域展示会更重要一些。所以我在想是否要保留原来的区域检测形式？滚动的区域不算裁剪
> 建议改回去。

2. 上面这个问题就算不改，sticky 和 fixed 的情况也要单独解决。这种情况和页面是否能滚动都没关系，能滚动也肯定看不到。

**Comment by zombieJ** [comment]
> 建议改回去。
这里 `@rc-component/trigger` 没有改过，和原本一样的逻辑。

> 上面这个问题就算不改，sticky 和 fixed 的情况也要单独解决。这种情况和页面是否能滚动都没关系，能滚动也肯定看不到。
父容器本身 `position` 没有代表性，业务逻辑同样可以组合出滚动场景：

https://codesandbox.io/s/epic-chandrasekhar-8cwq4u?file=/index.js

**Comment by ShenHongFei** [comment]
@jxccc1998  其实是可以实现手动设置 Pagination 页面大小选择框的弹出方向的，只不过 API 里没写，需要通过 selectComponentClass 实现

```tsx
import { Pagination, Select, type SelectProps } from 'antd'

const UpSelect: React.FC<SelectProps> & { Option: typeof Select.Option } =
    Object.assign(props => <Select {...props} size='small' placement='topLeft' />, {
        Option: Select.Option
    })

<Pagination
    selectComponentClass={UpSelect}
/>
```

**Comment by jxccc1998** [comment]
> 



> @jxccc1998 其实是可以实现手动设置 Pagination 页面大小选择框的弹出方向的，只不过 API 里没写，需要通过 selectComponentClass 实现
> 
> ```tsx
> import { Pagination, Select, type SelectProps } from 'antd'
> 
> const UpSelect: React.FC<SelectProps> & { Option: typeof Select.Option } =
>     Object.assign(props => <Select {...props} size='small' placement='topLeft' />, {
>         Option: Select.Option
>     })
> 
> <Pagination
>     selectComponentClass={UpSelect}
> />
> ```

好的~

**Comment by Atw-Lee** [comment]
我封装了一层select，并且想要覆盖掉表格分页器里的这个select，找到了这个属性，产生了这个警告是什么原因。Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined @zombieJ @ShenHongFei
