### ISSUE TITLE
React 18 upload多选上传, 部分文件上传状态错误

### ISSUE THREAD

**Issue by yujunfan** [ant-design/ant-design#36869]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-okc5st)

### Steps to reproduce

一次上传10多个文件可以重现（越多越容易重现）

### What is expected?

所有接口返回结果之后，文件状态要么失败要么成功

### What is actually happening?

所有接口返回结果之后，部分文件状态还在上传中

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.20 |
| System | windows10 |
| Browser | chrome 103.0.5060.134 |

**Comment by yuningjiang123** [comment]
这个问题是由于React 18 的Automatic Batching引起的   看下大佬们怎么修复了

**Comment by zombieJ** [comment]
这个幽灵又出现了

**Comment by SergeyNedayvodaBit** [comment]
still actual in the 4.22.5
