### ISSUE TITLE
Can we add ref attribute for Modal component?

### ISSUE THREAD

**Issue by sakthi0803** [ant-design/ant-design#36867]
### What problem does this feature solve?

The feature that I have to export the components UI as an image/pdf file format with the help of a dom reference object, We can implement this to any other component. but we can't export the Modal Component with the node reference object, because Modal opened as a separate dom.

### What does the proposed API look like?

<Modal ref={useRef()} id={'netProfitModal'}>
 ... Some Content
</Modal>

**Comment by zombieJ** [comment]
It will be support in next major version with internal interface:
https://github.com/ant-design/ant-design/blob/c89f890e5693cab548f922ae45dee846f58f8402/components/modal/demo/render-panel.md
