### ISSUE TITLE
Transfer组件没有使用random方法，后端渲染出错

### ISSUE THREAD

**Issue by machao23** [ant-design/ant-design#3686]
- antd 版本: 2.0.1
- 操作系统及其版本: windows-10
- 浏览器及其版本: chrome43

根据例子 https://ant.design/components/transfer/ 去掉了random项，后端渲染出错
代码部分截图：
![image](https://cloud.githubusercontent.com/assets/5095336/19914283/23bf76ca-a0e4-11e6-9396-30e16573392f.png)

报错截图
![image](https://cloud.githubusercontent.com/assets/5095336/19914286/31606e6a-a0e4-11e6-87e3-f66d6be07dde.png)

**Comment by machao23** [comment]
补充：
即使属性全部使用常量还是出错
部分代码截图：
![image](https://cloud.githubusercontent.com/assets/5095336/19914326/9ef14076-a0e4-11e6-8ae9-7cd7e555166f.png)

报错截图：
![image](https://cloud.githubusercontent.com/assets/5095336/19914330/a7e911cc-a0e4-11e6-9f31-535fd0e00864.png)

**Comment by afc163** [comment]
感谢反馈~
