### ISSUE TITLE
Modal title overlaps the close button

### ISSUE THREAD

**Issue by 4ntke** [ant-design/ant-design#36872]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-22-3-forked-qlhtfm?file=/demo.js)

### Steps to reproduce

Open a modal in link above.

### What is expected?

The title text should not overlap the button to close.

### What is actually happening?

Title text overlaps the close button.

![image](https://user-images.githubusercontent.com/107024609/182586620-b23d0568-dde9-413d-8b78-204f379a5a02.png)

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 16.4.0 |
| System | Linux, MacOS |
| Browser | Google Chrome |

**Comment by MadCcc** [comment]
Position of close button is `absolute` due to dynamic modal content, such as content without title.
I recommend to apply `padding-right` to your title element to make sure there is gap between title and close button.
