### ISSUE TITLE
TreeSelect使用异步加载和支持搜索，搜索到未展开的父节点，无法再展开请求数据

### ISSUE THREAD

**Issue by 963542298** [ant-design/ant-design#36873]
### Reproduction link

[https://763d4g.csb.app/](https://763d4g.csb.app/)

### Steps to reproduce

1. 先展开第一个节点
2. 输入框输入load
3. 第一个节点展开的expand to load的子节点 无法再次展开拿到数据

### What is expected?

展开能够拿到数据

### What is actually happening?

展开无法拿到数据

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
Is https://github.com/ant-design/ant-design/issues/31845#issuecomment-918021641 helpful?

**Comment by 963542298** [comment]
> Is [#31845 (comment)](https://github.com/ant-design/ant-design/issues/31845#issuecomment-918021641) helpful?

好像还不太一样

**Comment by zombieJ** [comment]
试了一下，应该是 `treeDataSimpleMode` 相关的问题。
