### ISSUE TITLE
2.2.0 DatePicker组件有问题

### ISSUE THREAD

**Issue by cm93** [ant-design/ant-design#3687]
#### 发生问题的环境是：
- antd 版本:2.2.0
- 操作系统及其版本:win7
- 浏览器及其版本:52.0.2743.116 m

#### 您做了什么？请提供尽可能详细的重现步骤。

引入了DatePicker，
`<DatePicker
          showTime
          disabledDate={this.disabledStartDate}
          defaultValue={this.state.defaultStartValue}
          value={this.state.startValue}
          format={format}
          placeholder="开始日期"
          onChange={this.onStartChange}
          style={{ width: 150 }}
        />`
defaultValue 和 value 都用moment处理过

#### 您期待的结果是:

像官网一样正常显示

#### 实际上的结果是:

选不上时间，ant-calendar-input  一直没变

**Comment by afc163** [comment]
确实还有问题，我 reopen 那个 issue，这里先关了。

**Comment by lylhub** [comment]
<Modal style={{width:400}} title="自定义时间范围" onCancel={this.handleCancel} visible ={this.props.visible}>

                自&nbsp;&nbsp;&nbsp;&nbsp;
                <DatePicker  style={{width:200}}  size="large"
                  disabledDate={this.disabledStartDate}
                  showTime={{format:'HH:mm',disabledMinutes:this.disabledMinutes,disabledSeconds:this.disabledSeconds,hideDisabledOptions:true}}
                  format="YYYY-MM-DD HH:mm"

                  placeholder="开始时间"
                  onChange={this.onStartChange}
                  onOpenChange={this.handleStartOpenChange}
                  onOk ={this.handleOk}
                /><br/><br/>
              至&nbsp;&nbsp;&nbsp;&nbsp;<DatePicker style={{width:200}}  size="large"
                  disabledDate={this.disabledEndDate}
                  showTime={{format:'HH:mm',disabledMinutes:this.disabledMinutes,disabledSeconds:this.disabledSeconds,hideDisabledOptions:true}}
                  format="YYYY-MM-DD HH:mm"

                  placeholder="结束时间"
                  onChange={this.onEndChange}
                  open={this.state.endOpen}
                  onOpenChange={this.handleEndOpenChange}
                  onOk ={this.handleOk}
                />
            </Modal>

选择第一个时间正常，但是选择第二个时间的时候不能选择~~
