### ISSUE TITLE
DatePicker 不支持value和onChange同时赋值

### ISSUE THREAD

**Issue by zuizuihao** [ant-design/ant-design#3689]
我想一直在state 里面维护一个date变量，这样在别的地方修改date变量的时候，同时值也会改变。现在问题是，如果这样做，日期将无法改变
<DatePicker
              showTime
              value＝{date}
              format="yyyy-MM-dd HH:mm"
              onChange={this.onRealTimeOfSendCarChange}
              placeholder="请选择时间" />

**Comment by afc163** [comment]
duplicated in #3665
