### ISSUE TITLE
Controlled inputs with its own value and onChange event doesnt work in Form.Item

### ISSUE THREAD

**Issue by CatherineShemenkova** [ant-design/ant-design#36897]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3h332u)

### Steps to reproduce

I need to prevent entering numbers that more/less that 'max'/'min' props . I need to prevent entering non-numeric symbols.
I presented with Form component.
And I pass Form.Item which contains InputNumber into Form.
And I create [value, setValue] through useState() for InputNumber to handle all changes in this input and format entering values.
And I change the state by setValue in onChange event.
And I add "type"="number" prop in InputNumber to prevent entering non-numeric symbols 

### What is expected?

Input does not allow to enter non-numeric symbols.
Value changed.

### What is actually happening?

Nothing happens.
Input allow to enter non-numeric symbols.
Value does not change. 

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 17 |
| System | macos |
| Browser | google chrome, firefox |

**Comment by afc163** [comment]
It is intented behavior: https://ant.design/components/form/#API

<img width="1266" alt="图片" src="https://user-images.githubusercontent.com/507615/182832304-9ab78028-30e2-44d5-969f-adb7ab243709.png">
