### ISSUE TITLE
Tabs 内部的滚动条无法使用键盘方向键控制滚动

### ISSUE THREAD

**Issue by edision** [ant-design/ant-design#36895]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-ms4szi?file=/demo.js)

### Steps to reproduce

点击div，
键盘方向键上、下、左、右都无法滚动

### What is expected?

键盘方向键上、下、左、右能控制滚动

### What is actually happening?

点击div，
键盘方向键上、下、左、右都无法滚动

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 17 |
| System | win11 |
| Browser | edge 103.0.1264.71 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15610#issuecomment-475951448

**Comment by edision** [comment]
> [#15610 (comment)](https://github.com/ant-design/ant-design/issues/15610#issuecomment-475951448)

不是这个问题，我指的是tabpane内的div有滚动条时，方向键是没法让滚动条滚动。

https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-ms4szi?file=/demo.js

**Comment by afc163** [comment]
TabPane 容器里有个 `tabindex="0"` 用来做可访问性，但这会导致点击内部非 focusable 元素后会聚焦在外面这个 div 上，你可以在你的滚动容器上加上 tabIndex 来解决。

https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-lrcjnw

**Comment by edision** [comment]
> TabPane 容器里有个 `tabindex="0"` 用来做可访问性，但这会导致点击内部非 focusable 元素后会聚焦在外面这个 div 上，你可以在你的滚动容器上加上 tabIndex 来解决。
> 
> https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-lrcjnw

解决了，谢谢
