### ISSUE TITLE
Pagination分页器的size内的英文文案不正确

### ISSUE THREAD

**Issue by git997-small** [ant-design/ant-design#36908]
### What problem does this feature solve?

中文显示:10条/页  英文显示:10/pages   

### What does the proposed API look like?

不是应该显示:10 enties/pages么 有更改此处文案的api么

**Comment by LongHaoo** [comment]
https://ant.design/components/table/#components-table-demo-sticky 参考链接

**Comment by LongHaoo** [comment]
@MadCcc

**Comment by LongHaoo** [comment]
说实话 10 enties/pages 有点过于长了 10/pages 已经足够理解了

**Comment by izhouteng** [comment]
国外一般用：`10 items per page` 或者 `10 rows per page`（要改可以改这俩）

但没有用 `10 enties / pages` 的

我感觉无关紧要。。老外都没提。。`10 / page` 完全足够表达意思。

而且，文案完全可以自定义。

**Comment by afc163** [comment]
https://codesandbox.io/s/geng-duo-antd-4-22-3-forked-pi2bqf?file=/demo.js
