### ISSUE TITLE
antd-reproduction-template uses deprecated ReactDOM.render

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ant-design/ant-design#36919]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce

Open https://codesandbox.io/s/antd-reproduction-template-6e93z

### What is expected?

Should not have any errors

### What is actually happening?

Error:
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Microsoft Edge: 102.0.1245.41 (Official build) (64-bit)  |

---
Here my forked and fixed codesandbox: https://codesandbox.io/s/antd-reproduction-template-fixed-for-react-18-5xpyx5. Please update the link in the issue creator to use fixed one.

**Comment by samyarkd** [comment]
In react v18, there is no such thing as `ReactDom.render`. Instead, you should use the below pattern and code,
```JSX

const App = () => {
  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <DatePicker />
      <Button type="primary" style={{ marginLeft: 8 }}>
        Primary Button
      </Button>
    </div>
  );
};

const Container = document.getElementById("root");

const root = createRoot(Container);
root.render(<App />);

```

**Comment by ChocolateLoverRaj** [comment]
@samyarkd it is related to the link in the antd issue creator. Changing the template will save people's time when forking the template. 

https://new-issue.ant.design/
![screenshot](https://user-images.githubusercontent.com/52586855/183271421-17c61ecf-c9d2-4f81-b520-3c208373196f.png)
