### ISSUE TITLE
在自定义受控组件中有分页的时候，把受控组件包裹Form.Item中进行校验，当数据校验有误的时候，分页的页数切换器会有一个红色的border

### ISSUE THREAD

**Issue by Hubartist** [ant-design/ant-design#36931]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-3-forked-1b74e0?file=/demo.js)

### Steps to reproduce

进入链接，点击测试按钮，即可重现

### What is expected?

期望分页选择不要出现红色边框

### What is actually happening?

当目前的受控组件校验错误的时候，分页的pagesize选择下拉框会出现红色边框

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.3.0 |
| System | Monterey 12.4 |
| Browser | google |

**Comment by zhenzhenChange** [comment]
可以这样临时解决：
```tsx
<Form.Item validateStatus="success" />
```
