### ISSUE TITLE
Drawer组件zIndex属性设置失效

### ISSUE THREAD

**Issue by 1zilc** [ant-design/ant-design#36932]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-3-forked-z24tkc?file=/demo.js)

### Steps to reproduce

1. 设置drawer的zIndex属性为1001

### What is expected?
新版本（4.22.3）zindex没生效：
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/44715458/183285509-d1bf7229-98b7-414a-9b35-27329f88d8fa.png">

老版本（4.20.6）zindex生效：
![AEFAE8C4-023A-43CD-88B7-0739BD1E0B57](https://user-images.githubusercontent.com/44715458/183285396-01140980-8a7b-491c-b18c-958a3e447a10.png)

### What is actually happening?

样式不生效

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.1.0 |
| System | macos 12.3 |
| Browser | chrome v104 |

**Comment by Canight** [comment]
插眼 +1

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/36958

**Comment by 1zilc** [comment]
@afc163 `4.22.4`的`Drawer`的层级似乎还是不符合预期呢
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/44715458/183549238-e4b0267c-6a32-4ef7-bff1-0c5b42457c85.png">
