### ISSUE TITLE
置灰状态不应该显示字数限制

### ISSUE THREAD

**Issue by sonny372** [ant-design/ant-design#36936]
### Reproduction link

[http://none](http://none)

### Steps to reproduce

在输入框置灰的时候，查看输入框效果

### What is expected?

置灰的时候，隐藏字数限制，因为置灰的时候，说明已经完成了之前的文本输入字数限制

### What is actually happening?

目前看到的效果是  置灰的文本框 会显示 用户本文 字数限制

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react 18 |
| System | win10 |
| Browser | chrome |

**Comment by MadCcc** [comment]
`showCount` 自行控制一下
