### ISSUE TITLE
Cascader的option设置了disabled，然后将其设置成了defaultValue，但是还是可以删除

### ISSUE THREAD

**Issue by wave1998** [ant-design/ant-design#36941]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-hui-tian-fang-shi-antd-4-22-3-forked-cqgt44)

### Steps to reproduce

Cascader设置的是多选，然后设置defaultValue为某一个option，同时设置option为disabled，期望该项不可以被取消，但是目前看来还是可以被删除

### What is expected?

期望达到和Select的option设置disabled后一样的效果，无法删除无法取消

### What is actually happening?

实际的结果是，设置了disabled还是可以对当前opton做操作

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 17.0.2 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
你需要的是 `allowClear={false}` 么？

**Comment by hydraZty** [comment]
我试了试 `Select.Option` 如果设置了 `disabled` 也是可以被清空的。

**Comment by zombieJ** [comment]
`disabled` 有关闭按钮的确是有问题，这个需要修一下：
ref TreeSelect https://codesandbox.io/s/ke-gou-xuan-antd-4-22-4-forked-udzx3t?file=/demo.js
