### ISSUE TITLE
建议增加 自定义 Table filterDropdown 时 控制显示隐藏功能

### ISSUE THREAD

**Issue by Superman-wc** [ant-design/ant-design#3694]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: macOS
- 浏览器及其版本: chrome52

#### 您做了什么？请提供尽可能详细的重现步骤。
 
const columns = [
     {
        title: '省份',
        dataIndex: 'province',
        key: 'province',
        width: 80,
        // filters: Provinces,
        filterDropdown: <FilterDropdown  options={Provinces} onChange={v=>console.log(v)}/>
      },
      ...
];

<Table  columns={columns} ... />

列的过虑 filterDropdown 是自定义的React组件 ，内部有个确定按钮， 点击后希望隐藏 整个filterDropdown

由于antd 目前前的版本实现里 filterDropdown 的显示隐藏是由它的父元素控制的

https://github.com/ant-design/ant-design/blob/master/components/table/filterDropdown.tsx#L128

https://github.com/ant-design/ant-design/blob/master/components/table/filterDropdown.tsx#L163

所以自定义的filterDropdown没法控制隐藏

建议filterDropdown 改成 function(){ return React.Element} 这样的方法，以便可以传递控制Dropdown的显示隐藏的方法过来

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/3003

提 issue 前建议搜索。

**Comment by Superman-wc** [comment]
@benjycui 我搜索过后的啊，但好像没有任何解决方案提供
