### ISSUE TITLE
Upload组件 多文件上传，onChange执行次数不足

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/ant-design#36949]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhao-pian-qiang-antd-4-22-3-forked-l0tnm0?file=/index.js)

### Steps to reproduce

上传很多文件

### What is expected?

onChange正常更新

### What is actually happening?

onChange丢了。有的状态不继续更新

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18 |
| System | MacOS Big Sur 11.1 |
| Browser | Chrome90.0.4430.93（正式版本） (x86_64) |

**Comment by DerrickTel** [comment]
https://user-images.githubusercontent.com/24643779/183376708-4487dbfa-5c75-461b-b7da-9d7e519e67b7.mp4

**Comment by DerrickTel** [comment]
https://user-images.githubusercontent.com/24643779/183376767-0b1b1106-e359-42bd-959e-ee59058d02bb.mp4

**Comment by izhouteng** [comment]
目测又是 React 18 `Automatic Batching` 的锅...... 有点蛋疼，建议先用 `ReactDOM.render()` 方式渲染（降回 17 的渲染方式）

**Comment by afc163** [comment]
Duplicate of #36869

**Comment by kunkkaliu** [comment]
> 目测又是 React 18 `Automatic Batching` 的锅...... 有点蛋疼，建议先用 `ReactDOM.render()` 方式渲染（降回 17 的渲染方式）

React 18 对于原生事件、setTimeout等进行了自动批处理导致的，可以用flushSync在你的onChange函数里面同步刷新状态解决。
