### ISSUE TITLE
Tab Pane position bottom not working on mobile view inspect element

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#36959]
### Reproduction link
[(https://uwbdrg.csb.app/)]
### Steps to reproduce

View it in mobile view using inspect element any phone will do then refresh the tab pane rerenders on top even if set to bottom

### What is expected?

Tab Pane should still be on bottom

### What is actually happening?

Tab pane resets on top

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17.0.2 |
| System | Mac Os Monterey |
| Browser | Google Chrome |

**Comment by tempoeric** [comment]
@zombieJ any idea on this?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24831#issuecomment-640580344

https://github.com/react-component/tabs/commit/30e627453e8e00f1f8751cb5773d1d842b1702a4

上面的描述和 diff 貌似并不匹配。 @zombieJ 看看

**Comment by afc163** [comment]
感觉 mobile 下这个修改 tabPosition 的逻辑并无并要。

**Comment by tempoeric** [comment]
i need the tab position below on mobile cause whenever i  render the page in mobile view it renders tab pane top even i set it as tabPosition: bottom
<img width="798" alt="Screen Shot 2022-08-09 at 8 04 38 PM" src="https://user-images.githubusercontent.com/42777871/183642918-8cd39c41-0f3f-42dc-9c52-b154116a555d.png">

**Comment by tempoeric** [comment]
any news from this???

**Comment by tempoeric** [comment]
@zombieJ any fix on this or news?

**Comment by afc163** [comment]
PR welcome to remove ant-tabs-mobile logic.

**Comment by tempoeric** [comment]
can you do this @afc163 i dont know how to create pr for ant-design just needed for this project of mine

**Comment by tempoeric** [comment]
Hi @afc163  @kungege  still not working the tabposition bottom on mobile i would like to request to open this ticket

**Comment by tempoeric** [comment]
after refreshing in inspect mobile view it renders on top not bottom 
<img width="1020" alt="Screen Shot 2022-08-23 at 3 30 14 PM" src="https://user-images.githubusercontent.com/42777871/186098188-06e13764-3124-4e56-a124-1a7b0da03b56.png">

**Comment by kungege** [comment]
`react-component/tabs` needs to publish a new version...

**Comment by tempoeric** [comment]
> `react-component/tabs` needs to publish a new version...

okay then antd will inherit this version right?

**Comment by kungege** [comment]
> 

Not yet, we still need to submit a pull request to change `rc-tabs` version in `package.json`, then wait for `antd` to publish next version...

**Comment by tempoeric** [comment]
aww so it wont be possible this week to be released? :(

**Comment by afc163** [comment]
https://github.com/react-component/tabs/releases/tag/v12.1.0-alpha.1

**Comment by tempoeric** [comment]
hi @afc163 i know that it is released in rc-tab but still not working on the sandbox i provided

**Comment by afc163** [comment]
PR welcome on ant-design feature branch to upgrade rc-tabs version.

**Comment by tempoeric** [comment]
what current branch should i use to upgrade the master?

**Comment by tempoeric** [comment]
@afc163 @kungege  can you help me create pr release for antd please

**Comment by afc163** [comment]
You can send PR to feature branch on https://github.com/ant-design/ant-design/pulls which contains a bump version commit for rc-tabs.

**Comment by tempoeric** [comment]
<img width="1080" alt="Screen Shot 2022-08-29 at 2 47 45 PM" src="https://user-images.githubusercontent.com/42777871/187140116-e31965f5-62b0-45c7-bcaf-1253659a6059.png">
@afc163 i cannot push my branch seems i do not have access to push on antd github repo i based my current branch in antd master

**Comment by yoyo837** [comment]
https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by tempoeric** [comment]
@afc163  @zombieJ please review
https://github.com/ant-design/ant-design/pull/37281

**Comment by tempoeric** [comment]
@afc163 this is still not working even though i pushed the fixed in the feature branch
https://github.com/ant-design/ant-design/pull/37328#event-7301215757

**Comment by tempoeric** [comment]
hi @afc163 @zombieJ @kungege when can i use my pr fix for this since it's been almost a month since i raised this issue i already deployed it in the feature branch but yet still not taking effect due to that it's not yet on the master branch

**Comment by tempoeric** [comment]
<img width="1440" alt="Screen Shot 2022-09-01 at 9 07 52 PM" src="https://user-images.githubusercontent.com/42777871/187921414-a71bca47-1966-4382-8894-fce9dafd5ca1.png">
the issue is still existing when in mobile view
