### ISSUE TITLE
DatePicker 组件无法选择日期时间

### ISSUE THREAD

**Issue by weago** [ant-design/ant-design#3695]
#### 发生问题的环境是：

- antd 版本:  2.2.0
- 操作系统及其版本: MacOS 10.11.6
- 浏览器及其版本: Chrome 53.0

#### 您做了什么？请提供尽可能详细的重现步骤。

1. 访问antd官网：https://ant.design/components/form/
2. 在 DatePicker[showTime] 这个控件上选择日期时间，点击确定，日期时间显示
3. 再点击右边的叉叉，在点击DatePicker控件，此时无论如何选取日期时间，点击确定日期时间并没有反应到控件中

#### 您期待的结果是:

日期控件能正确的显示选择的值

#### 实际上的结果是:

什么都没有显示

![image](https://cloud.githubusercontent.com/assets/6398951/19921173/ac847f40-a117-11e6-9e20-f4ae991813d4.png)

![image](https://cloud.githubusercontent.com/assets/6398951/19921177/b24fda8c-a117-11e6-9475-0b7b5c42fabc.png)

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/3665
