### ISSUE TITLE
Allow  `layout` property in `Form.Item`. 

### ISSUE THREAD

**Issue by MostFrumiousBandersnatch** [ant-design/ant-design#36956]
### What problem does this feature solve?

By now, we have `layout` property in `Form`, though it makes sense to combine items with both vertical and horizontal layout in one form, sometimes. 

### What does the proposed API look like?

Form.Item -> layout : 'vertical' | 'horizontal'

**Comment by zombieJ** [comment]
Could you provide a layout sample about your reqirement?

**Comment by afc163** [comment]
Duplicate of #31044
