### ISSUE TITLE
关于 antd 与 dva 的疑问

### ISSUE THREAD

**Issue by llqgit** [ant-design/ant-design#3696]
从 2.0 开始，antd 官方推荐 dva 框架。
dva 的确在一定程度上解决了 redux 的相对复杂

但是官方组件，还是以原来的方式提供示例，为什么没有一份 dva 的示例呢？
由原来的项目，迁移过来，改动的地方比较多，是希望架构能够更佳清晰，易维护。

现在对于 antd 和 dva 的关系还是比较模糊的。希望能够得到更多的官方说明和支持。

**Comment by afc163** [comment]
antd 只提供 UI 解决方案，实现和演示都应该和应用架构无关，用户可以选用自己熟悉的任何 react 社区的开发框架。

**Comment by llqgit** [comment]
额～ 我还以为 antd 和 dva 都是 亲儿子，可能官方会支持一套完整的示例呢！ @afc163

**Comment by afc163** [comment]
完整的示例后续会慢慢完善的，内部现在都是用 dva 开发。

简单的使用示例现在可以看：https://ant.design/docs/react/practical-projects
