### ISSUE TITLE
antd\es\style\themes\default.less 注释有语法错误，/**/能通过，//报错

### ISSUE THREAD

**Issue by mxdmly** [ant-design/ant-design#36963]
### Reproduction link

[https://github.com/mxdmly/antd-less-issue](https://github.com/mxdmly/antd-less-issue)

### Steps to reproduce

运行 npm start 

### What is expected?

Compiled successfully!

### What is actually happening?

Failed to compile.

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.2.0 |
| System | Windows 10 教育版 21H2 (19044.1645) |
| Browser | Chrome 103.0.5060.134（正式版本） （64 位） |

---
antd\es\style\themes\default.less

**Comment by mxdmly** [comment]
我按照这里的说明改变主题颜色，@import '~antd/es/style/themes/default.less'; 后发现了这个错误
https://ant.design/docs/react/customize-theme-cn#%E5%9C%A8-create-react-app-%E4%B8%AD%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98

**Comment by zombieJ** [comment]
这是 less 的语法，请检查你的 loader 配置，是否没有正确配置到 less-loader 哈

https://lesscss.org/#comments
