### ISSUE TITLE
Modal对话框, 通过 react-draggable 实现拖拽，内容区域为iframe，拖拽出现问题。

### ISSUE THREAD

**Issue by Kitercc** [ant-design/ant-design#36969]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-xuan-ran-dui-hua-kuang-antd-4-22-4-forked-l4ip5h)

### Steps to reproduce

把弹出框移入可视区域角落，不要松开鼠标，在iframe上面松开鼠标

### What is expected?

无论在哪个区域松开鼠标，拖拽停止

### What is actually happening?

松开鼠标后依旧可以拖拽

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | react 17.0.2 |
| System | windows 10 |
| Browser | chrome |

---
其实应该和antd关系不大，iframe一直很难处理，期望能够解决

**Comment by afc163** [comment]
确实和 antd 关系不大，我们好像也没什么好办法。
