### ISSUE TITLE
Form 增加action属性后，无法直接提交的问题

### ISSUE THREAD

**Issue by yhhwpp** [ant-design/ant-design#3697]
#### 发生问题的环境是：

- antd 版本:2.2.1
- 操作系统及其版本:wind7
- 浏览器及其版本:chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

给Form 增加action属性，直接提交，无反应

#### 您期待的结果是:

像原生form一样直接提交

#### 实际上的结果是:

提交无反应

#### 可重现的在线演示

http://codepen.io/yhhwpp/pen/mObygv?editors=001

**Comment by afc163** [comment]
我们默认禁用了 onSumbit 的事件，因为应用场景大多数是单页应用。你可以重设 onSumbit 来恢复：

http://codepen.io/anon/pen/RobrXv?editors=001

**Comment by yhhwpp** [comment]
3q
