### ISSUE TITLE
antd 4.18.0 Table.SELECTION_COLUMN 无法将扩展图标设置右固定

### ISSUE THREAD

**Issue by zhengchunxia** [ant-design/ant-design#36984]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-k3i2o3?file=/columns.js)

### Steps to reproduce

使用4.18.0版本的Table.SELECTION_COLUMN和Table.EXPAND_COLUMN，不能同时固定在右侧

### What is expected?

希望可以同时右固定

### What is actually happening?

x滚动条滚动时，EXPAND_COLUMN加号会随滚动条滚动

| Environment | Info |
| --- | --- |
| antd | 4.18.0 |
| React | 16.9.0 |
| System | windows |
| Browser | 104.0.5112.8 |

---
业务场景：用户可以对Table设置显示哪些列，可以设置列展示顺序，可以自定义哪些列固定右侧或则左侧
类似ant design pro的columnSetting 组件功能 -》https://preview.pro.ant.design/list/table-list

**Comment by afc163** [comment]
```
      rowSelection={{
        fixed: "right",
      }}
```
