### ISSUE TITLE
在web component 使用动态主题切换，css3变量权重问题

### ISSUE THREAD

**Issue by yaoleia** [ant-design/ant-design#36982]
### Reproduction link

[https://github.com/Tencent/wujie/tree/master/examples](https://github.com/Tencent/wujie/tree/master/examples)

### Steps to reproduce

使用wujie微前端，web-component下动态设置antd的主题色，:host 或 :root样式权重低不生效，生效的是html下的初始css3样式变量值。

### What is expected?

web-component内的动态设置antd的主题色生效

### What is actually happening?

web-component内的动态设置antd的主题色不生效

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.0.0 |
| System | macOS 12.4 |
| Browser | Chrome 最新 |

**Comment by zombieJ** [comment]
提供一下 demo 启动相关 script 以及对应 Demo 页面样式元素哈~

**Comment by yaoleia** [comment]
@zombieJ 
demo地址：https://github.com/yaoleia/wujie.git
## 启动步骤
### 1. 启动主应用
```bash
cd ./examples/main-react/
yarn & yarn start
```

### 2. 启动react17子应用
```bash
cd ./examples/react17/
yarn & yarn start
```
打开主应用 http://localhost:7700 ，切换到react17子应用，shadow-dom内部的html下的初始css3样式变量比 :host 权重高
![截屏2022-08-10 18 39 04](https://user-images.githubusercontent.com/22293549/183882560-1835783c-dd16-4fb1-8378-b2e9c9bbbe23.png)

单独打开子应用 http://localhost:7100
![截屏2022-08-10 18 42 55](https://user-images.githubusercontent.com/22293549/183882740-a4430605-415a-4f05-a570-b37f0fd9eb55.png)

**Comment by zombieJ** [comment]
<img width="578" alt="截屏2022-08-16 下午6 05 15" src="https://user-images.githubusercontent.com/5378891/184853760-b223a2ae-3d9e-4999-a218-e86611b9702f.png">

**Comment by yaoleia** [comment]
@zombieJ  我写错 && ，项目应该可以运行

**Comment by afc163** [comment]
新的动态主题方案来解决吧 https://github.com/ant-design/ant-design/issues/33862
