### ISSUE TITLE
AutoComplete里的onChange在选中option时候会触发值的更新，和onSelect功能重复

### ISSUE THREAD

**Issue by goo-yyh** [ant-design/ant-design#36994]
### What problem does this feature solve?

在受控状态下，选中option时并不想修改value的值。可是onChange无法区分是input变更还是select option产生的值

### What does the proposed API look like?

1. 在onChange中能区分值的修改是来自input修改还是选中option
2. 根据API的名称区分功能，onChange不涉及option的选中，交给onSelect处理，设置默认onSelect

**Comment by goo-yyh** [comment]
![image](https://user-images.githubusercontent.com/45666106/183867682-b0f646f2-8fa9-44a5-8249-793c03a3b7c6.png)

**Comment by afc163** [comment]
任何修改 AutoComplete 输入框内容的行为都会触发 onChange，这个是符合预期的。AutoComplete 的本质是 input，不是 select。

**Comment by goo-yyh** [comment]
> 内容

问题是选中option时候并不想直接修改输入框内内容

**Comment by goo-yyh** [comment]
> 任何修改 AutoComplete 输入框内容的行为都会触发 onChange，这个是符合预期的。AutoComplete 的本质是 input，不是 select。

问题是选中option时候并不想直接修改输入框内内容

**Comment by afc163** [comment]
这个组件的默认交互就不是这样设计的，你可能要考虑换一个组件或者自行实现相关交互。

**Comment by goo-yyh** [comment]
> 这个组件的默认交互就不是这样设计的，你可能要考虑换一个组件或者自行实现相关交互。

好的谢谢
