### ISSUE TITLE
modal 组件，当高度过高时出现的bug

### ISSUE THREAD

**Issue by llqgit** [ant-design/ant-design#3699]
### 发生问题的环境是：

- antd 版本: 2.2.0
- 操作系统及其版本: macOS 10.12.1
- 浏览器及其版本:  chrome 54.0.2840.71 (64-bit)

### 您做了什么？请提供尽可能详细的重现步骤。

引入 antd 了 Modal
Modal 内容高度超过屏幕

### 您期待的结果是:

和 safari 一样正常显示

![safari 正常显示时的底部位置](https://cloud.githubusercontent.com/assets/8063914/19924761/53226802-a128-11e6-87cd-8df74c0f1b07.png)

### 实际上的结果是:

chrome 错位了，似乎是没有重新渲染导致的
下面的那个部分其实是 ```Modal``` 自身的中部位置,。

注：内容过高，向上滑动才能看见 ```Modal``` 底部。

![chrome 错误显示时的底部位置](https://cloud.githubusercontent.com/assets/8063914/19924618/a4f48e22-a127-11e6-9aed-eb13cee2942a.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by llqgit** [comment]
I want but i couldn't, sorry. @benjycui 
when I build on the codepen, there always be an Error that not happened in my local project.

**Comment by benjycui** [comment]
Then try to provide a re-producible repo.

**Comment by llqgit** [comment]
I run the same code today. And the error disappeared. I think it may be my chrome error some how, not the antd. Thanks for your time @benjycui
