### ISSUE TITLE
antd table 数据量大时，表格勾选严重卡顿

### ISSUE THREAD

**Issue by yudioll** [ant-design/ant-design#36999]
### Reproduction link

[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce

如标题

### What is expected?

优化选中的性能

### What is actually happening?

表格选中卡顿

| Environment | Info |
| --- | --- |
| antd | 4.17.2 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
trace #20339
