### ISSUE TITLE
关于 Form.Item 卸载加载时值的问题

### ISSUE THREAD

**Issue by Xingting-W** [ant-design/ant-design#36995]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hv9rsu)

### Steps to reproduce

1. 设置字段值为 undefined -> 卸载字段 -> 加载字段
2. 卸载字段 -> 设置字段值为 undefined -> 加载字段

### What is expected?

虽然 undefined 是非受控的标志，但是对于这个结果还是感觉有点奇怪，因为文档里有写 Form 的 initialValues 拥有最高优先级，但这里的值却是 initialValue

### What is actually happening?

initialValue 比 initialValues 优先级高

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

---
如果是设计成这样就当我没提

**Comment by zombieJ** [comment]
（preserve 时）`initialValues` 只有在 Form mount 和 `resetFields` 会生效，之后所有变更都不再重复。其设计就是为了防止 preserve 的值被 Field 反复注册所修改。所以不管你留下的是 `undefined` 还是其他值，这里其实已经不会再更新。

而当非 preserve 时，则在 Field 卸载时，会标记这个字段已经删除，当再次注册 Field 会重置到 `initialValues`，以清除 Field 更改造成的影响。

的确是设计如此哈~
