### ISSUE TITLE
Upload组件中accept设置为.txt时 .csv后缀文件也可以上传

### ISSUE THREAD

**Issue by distance321** [ant-design/ant-design#36993]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dian-ji-shang-chuan-antd-4-22-4-forked-puuh59?file=/demo.js)

### Steps to reproduce

accept 设置为.csv时可以禁用掉.txt后缀的文件，但设置为.txt时却禁用不掉.csv后缀的文件

### What is expected?

设置为.txt时禁用.csv后缀的文件

### What is actually happening?

设置为.txt时禁用不了.csv后缀的文件

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.0.1 |
| System | macOS 12.4 |
| Browser | chrome 102.0.5005.115 |

**Comment by afc163** [comment]
可以用原生 `<input type="file" accept=".txt" />` 试试，这个问题应该和 antd 无关。
