### ISSUE TITLE
若干问题

### ISSUE THREAD

**Issue by jidanji** [ant-design/ant-design#36990]
### What problem does this feature solve?

 1、日期选择器的周选择器 有bug2、treetable的图标不支持定义3、日期选择不支持非连续多选

### What does the proposed API look like?

 1、日期选择器的周选择器 有bug2、treetable的图标不支持定义3、日期选择不支持非连续多选

**Comment by afc163** [comment]
1. 请一个问题一个 issue。
2. 请使用 bug report 模板反馈 bug，并提供在线重现。
3. feature requirement 请描述 `What does the proposed API look like?`
