### ISSUE TITLE
Tooltip首次visible设为true位置错误

### ISSUE THREAD

**Issue by dyegral** [ant-design/ant-design#37004]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-1orjjg?file=/demo.js)

### Steps to reproduce

请求后dom位置变化，tooltip导致未跟着移动

### What is expected?

tooltip定位正确

### What is actually happening?

tooltip定位错误

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome100.0.4896.60 |

**Comment by afc163** [comment]
You can try `getPopupContainer` in this situation: https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-5f0ddq
