### ISSUE TITLE
When using custom body render in Table, columns width must be number otherwise header not work as expected

### ISSUE THREAD

**Issue by Jungzl** [ant-design/ant-design#37007]
### Reproduction link

[https://stackblitz.com/edit/react-ym5ip1?file=demo.js](https://stackblitz.com/edit/react-ym5ip1?file=demo.js)

### Steps to reproduce

just run

### What is expected?

columns width should work no matter number or string

### What is actually happening?

header style not work

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 105 |

**Comment by zombieJ** [comment]
When use customize body. It should strongly follow the guid to fill data of column. ref: https://ant.design/components/table-cn/#components-table-demo-virtual-list
