### ISSUE TITLE
a-tabs 关闭键盘切换事件

### ISSUE THREAD

**Issue by yb0112** [ant-design/ant-design#37006]
### What problem does this feature solve?

当前项目中使用到了上下左右的快捷键，当点击tab后，tabs的快捷键生效了，跟自己需要的快捷键形成冲突

### What does the proposed API look like?

希望可以对外提供一个参数，使用者可以自行控制要不要开启

**Comment by afc163** [comment]
官方只维护 React 版本。反馈错地方了。
