### ISSUE TITLE
select 默认第一个高亮关闭时，下拉选中 按enter 键，没有选中值

### ISSUE THREAD

**Issue by Johnny-young** [ant-design/ant-design#37008]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-qian-antd-4-22-4-forked-bln3hx?file=/demo.js:439-463)

### Steps to reproduce

1. defaultActiveFirstOption 设置为false
2. 下拉展开，输入选中项的值
3. 按enter键，选中想要的值

### What is expected?

按下enter 键，选中输入匹配的值

### What is actually happening?

按下enter键，没有反应

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.0.48 |
| System | mac os |
| Browser | chrome 104.0.5112.79 |

**Comment by afc163** [comment]
按下 `Enter` 时的行为就是把 active 的元素选中，如果没有 active 的元素，自然也就无法选中。这是预期效果。
