### ISSUE TITLE
Ellipsis suffix add color or other styles

### ISSUE THREAD

**Issue by shanpig** [ant-design/ant-design#37016]
### What problem does this feature solve?

Is there any possibilities that ellipsis config 'suffix' could support styling? Currently it is only a text node, and although it is technically possible to give a styled-component or styled html tag to suffix prop, it does not act accordingly. Perhaps wrap the text node with a span with class name so developors can at least use a class based styling?

### What does the proposed API look like?

[a minimal demonstration here](https://codesandbox.io/s/modest-saha-9m0rg4?file=/src/App.js)

```html
<span aria-hidden="true">
This is a very long te
</span>
<span aria-hidden="true">
...
</span>
<span class="i-am-the-suffix">
suffix
</span>
```

**Comment by zombieJ** [comment]
suffix with string type is design that as a text only since currently the measure function is js measure which may not strong enough to support to flexible style. We may not plan to support this requirement until get more better way to handle measure.

Thanks for feedback.
