### ISSUE TITLE
notification 显示有问题，与官网不符合

### ISSUE THREAD

**Issue by wuzeru** [ant-design/ant-design#3701]
#### 发生问题的环境是：

- antd 版本: 2.2.0
- 操作系统及其版本: mac
- 浏览器及其版本: chrome

#### 您做了什么？请提供尽可能详细的重现步骤。
```
            notification.error({
                message : '出错了！',
                description : error
                // duration: null
                // onClose : this.props.onClearError
            })
```

#### 实际上的结果是:
![image](https://cloud.githubusercontent.com/assets/6448232/19930390/3296cde2-a143-11e6-9008-3e59839bb119.png)

**Comment by afc163** [comment]
强刷一下？

**Comment by wuzeru** [comment]
是我引入了一个旧版本的anticon
![image](https://cloud.githubusercontent.com/assets/6448232/19930786/f210b7fe-a144-11e6-8125-7ba59dd77f56.png)
sorry，我的问题
