### ISSUE TITLE
Allow for the order of buttons in default footer for the Modal component to be configurable

### ISSUE THREAD

**Issue by mellis481** [ant-design/ant-design#37023]
### What problem does this feature solve?

There is debate or at least varying preferences in the design community regarding which side (left or right) buttons should be aligned in forms.  Here are a couple articles that advocate to align buttons to the left:

- https://adamsilver.io/blog/where-to-put-buttons-on-forms/
- https://medium.com/patternfly/button-placement-on-forms-aa57a81f7d

In addition to affecting UX, there are accessibility implications especially for low-vision users. Additionally, button _order_ is a consideration when talking about button _alignment_.

The default alignment for Ant form buttons (at least what I see in all examples) is left-aligned where the primary button is left-most. The alignment for buttons in the default footer of the Modal component, however, is right-aligned where the primary button is right-most.  Many designers expect the button alignment in a modal to mirror the alignment of the form since one can easily argue that many modal instances are forms.

The entire footer can currently be customized to accomplish this, but forcing every instance of a modal in an application to define a custom footer isn't a great DX, especially when the majority of modal instances likely use the default footer.  Yes, CSS can be applied to the footer to left-align the buttons, but the _order_ of the buttons cannot be changed with CSS, at least in an accessible manner (elements should appear in the same order visually as they exist in the DOM for screen readers).  Creating a base component in an app that corrects the button order and alignment would mean replicating the [defaultFooter](https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx#L188-L192) functionality which requires quite a bit of code (as well as re-implementing the `LocalReceiver` component since that isn't exported).

For this reason, it would be very beneficial for the order of the buttons in default footer for the Modal component to be configurable.

### What does the proposed API look like?

A new, optional prop added to `ModalProps` called `defaultFooterButtonOrder` where the options are `primary-left` and `primary-right`. eg:

```
export interface ModalProps {
  ...,
  defaultFooterButtonOrder?: 'primary-left' | 'primary-right';
}
```

The default value (if `defaultFooterButtonOrder` is `undefined`) would be `primary-right` so existing default functionality would be retained.

Then the only other change would be to the `renderFooter` function. eg:

```
  const renderFooter = (locale: ModalLocale) => {
    const { okText, okType, cancelText, confirmLoading, defaultFooterButtonOrder } = props;

    const cancelButton = (
      <Button onClick={handleCancel} {...props.cancelButtonProps}>
        {cancelText || locale.cancelText}
      </Button>
    );
    const okButton = (
      <Button
        {...convertLegacyProps(okType)}
        loading={confirmLoading}
        onClick={handleOk}
        {...props.okButtonProps}
      >
        {okText || locale.okText}
      </Button>
    );

    return defaultFooterButtonOrder === 'primary-left' ? (
      <>
        {okButton}
        {cancelButton}
      </>
    ) : (
      <>
        {cancelButton}
        {okButton}
      </>
    );
  };
```

If this is a feature that would be accepted, my team can create a PR for it.

**Comment by afc163** [comment]
You can customize footer https://ant.design/components/modal/#components-modal-demo-footer

**Comment by mellis481** [comment]
@afc163 I know. I noted that here:

> The entire footer can currently be customized to accomplish this, but forcing every instance of a modal in an application to define a custom footer isn't a great DX, especially when the majority of modal instances likely use the default footer.

**Comment by RiteshMakan** [comment]
@mellis481 Perhaps a solution would be to make a ButtonGroup component that standardise your footer buttons according to your needs. Then you just set that as your default footer for the modal
