### ISSUE TITLE
Multiple columns sort is broken

### ISSUE THREAD

**Issue by jer-sen** [ant-design/ant-design#37024]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wfxg22)

### Steps to reproduce

Sort column "Chinese Score" and then "Math Score", look at the console logs of the onChange event.

### What is expected?

All the sorted columns should be in the onChange event parameter to be able to make a correct call to the server to get the correct values to display.

### What is actually happening?

The event parameter only contains the first sorted column (not even the changed column that would allow to maintain an updated state of all the sorted columns).

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.0.2 |
| System | Windows |
| Browser | Firefox |

---
These should never have existed:
- issue https://github.com/ant-design/ant-design/issues/36653
- commit https://github.com/ant-design/ant-design/commit/9e7e32b60ce80363c5865eb10bdf44d2938b3721#
- PR https://github.com/ant-design/ant-design/pull/36710/commits

The type SorterResult<RecordType[]> is a nonsens. The PR has to be reversed.

**Comment by MadCcc** [comment]
[#36710](https://github.com/ant-design/ant-design/pull/36710/commits) reverted.

**Comment by yoyo837** [comment]
Still need to fix again, right? Or not? Reopen for now...

**Comment by MadCcc** [comment]
> Still need to fix again, right? Or not? Reopen for now...

No need to reopen this issue, and https://github.com/ant-design/ant-design/issues/36653 may not be treated as a bug.

**Comment by vaynevayne** [comment]
情况就是支持吗？ sorter 的结构根据column.sorter.multiple 有无来变吗
