### ISSUE TITLE
Transfer 树穿梭框 左侧是树，右侧变成列表了

### ISSUE THREAD

**Issue by hyy520** [ant-design/ant-design#37028]
### Reproduction link

[https://ant.design/components/transfer-cn/#components-transfer-demo-tree-transfer](https://ant.design/components/transfer-cn/#components-transfer-demo-tree-transfer)

### Steps to reproduce

见 树穿梭框 官网 demo

### What is expected?

穿梭到右侧结构还是树型结构

### What is actually happening?

右侧变成列表了
<img width="1030" alt="图片" src="https://user-images.githubusercontent.com/20987845/184274330-c9ebc27a-fb2e-456e-afe1-73b839eee421.png">

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 最新 |
| System | mac |
| Browser |  chrome |

**Comment by afc163** [comment]
这个例子预期就是这样，并不是 bug，具体看 demo 代码。

**Comment by pxim** [comment]
解决了么，右边能变成tree么？

**Comment by wangxing0204** [comment]
解决了么，右边能变成tree么？

**Comment by NotFound403** [comment]
@afc163  右边能变成tree么

**Comment by resetsix** [comment]
写了一个示例

https://github.com/resetsix/Antd_Tree-to-Tree_Transfer
