### ISSUE TITLE
Tabs标签页的行内transfrom样式导致字体模糊

### ISSUE THREAD

**Issue by lokewei** [ant-design/ant-design#3702]
#### 发生问题的环境是：

- antd 版本: v2.2.0
- 操作系统及其版本: win7
- 浏览器及其版本: chrome 54.0.2840.59 m

#### 您做了什么？请提供尽可能详细的重现步骤。

主内容区引入了tabs组件做内容切换
![image](https://cloud.githubusercontent.com/assets/1223119/19934112/89524ed8-a150-11e6-9e35-92d46591fc58.png)

#### 您期待的结果是:

正常的Tabs面板使用
主菜单字体清晰锐利：
![image](https://cloud.githubusercontent.com/assets/1223119/19933942/fe85b89e-a14f-11e6-9dac-54219a5c4064.png)

#### 实际上的结果是:

导致页面左侧菜单字体模糊
![image](https://cloud.githubusercontent.com/assets/1223119/19933757/7591d144-a14f-11e6-8dfb-3d907fbdaf81.png)
去掉如下行内transform后正常：
![image](https://cloud.githubusercontent.com/assets/1223119/19933855/c43e0e0c-a14f-11e6-8663-3260d9853c85.png)
![image](https://cloud.githubusercontent.com/assets/1223119/19933888/da7212fe-a14f-11e6-85c4-41c169f1d34f.png)

目前只在chrome上发现此问题，ie11下正常，其他浏览器暂未测试。

**Comment by afc163** [comment]
诡异的问题，可以帮助我们一起试试有什么好的解决方案：

http://stackoverflow.com/questions/20326220/blurry-text-on-transformrotate-in-chrome

https://github.com/nolimits4web/Swiper/issues/45

https://css-tricks.com/forums/topic/transforms-cause-font-smoothing-weirdness-in-webkit/

**Comment by afc163** [comment]
我在 win7 + Chrome 上没有重现出来，能给我一个可重现的 demo 么？

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by lokewei** [comment]
@afc163 好的，我晚点去codepen上弄一个demo

**Comment by afc163** [comment]
ping~

**Comment by lokewei** [comment]
@afc163 例子在这里：http://codepen.io/lockewei/pen/ENjbvL

**Comment by afc163** [comment]
测试环境：Window7 + chrome 54.0.2840.99 m

未发现模糊效果。

![default](https://cloud.githubusercontent.com/assets/507615/20314508/6a899d72-ab95-11e6-99bc-ec27aef003a2.PNG)

![1](https://cloud.githubusercontent.com/assets/507615/20314535/7e906a30-ab95-11e6-83f0-217d5027b5e0.PNG)

可能和某些硬件相关，你可能要靠自己来排查和解决了。

**Comment by afc163** [comment]
等等，貌似有一点点模糊！

**Comment by lokewei** [comment]
嗯，拿公司的几台电脑测试了下有的模糊明显有的看不出来。可能与硬件和分辨率(低分辨率更容易看出来)有关。

**Comment by lokewei** [comment]
嗯，拿公司的几台电脑测试了下有的模糊明显有的看不出来。可能与硬件和分辨率(低分辨率更容易看出来)有关。

**Comment by lokewei** [comment]
嗯，拿公司的几台电脑测试了下有的模糊明显有的看不出来。可能与硬件和分辨率(低分辨率更容易看出来)有关。

**Comment by xxn520** [comment]
这个问题并没有得到真正的解决，不应该closed，应该继续讨论解决的方案。

**Comment by afc163** [comment]
欢迎能够重现此问题的社区同学继续讨论，尝试帮助我们解决。

**Comment by xxn520** [comment]
还在尝试中，因为部分电脑上的字体模糊的程度作为前端实在是无法接受。

**Comment by xxn520** [comment]
stackoverflow 上提了很多种解决方案，都试了一下，`zoom: 97%;` 是目前唯一可行的。

**Comment by benjycui** [comment]
It seems that `zoom` doesn't work in Modern browsers https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/zoom

**Comment by xxn520** [comment]
chrome是支持zoom的，然后字体模糊也只在chrome下有。不过zoom据说会造成页面的重绘，这是目前了解到的问题。

**Comment by xxn520** [comment]
但是个人认为zoom:99%不是很好。设置的尺寸会变小一些。

**Comment by xxn520** [comment]
我觉得可以在rc-tabs里面isTransformSupported以外增加对windows下webkit引擎的判断，对于windows下webkit引擎也做降级处理。

**Comment by benjycui** [comment]
> 我觉得可以在rc-tabs里面isTransformSupported以外增加对windows下webkit引擎的判断，对于windows下webkit引擎也做降级处理。

建议是？

**Comment by xxn520** [comment]
rc-tabs里面原来就对不支持transform的情况有降级处理，所以我在不支持transform的if判断中又增加了一个判断windows下webkit的条件，判断逻辑写在了utils里面。

不过rc-tabs又有一个奇怪的地方就是对tabcontent的transform没有做降级，只有一个animated的参数，所以目前我将animated设置为false了，因为不设置false，模糊的情况还是不能避免。

> 这个issue其实可以在rc-tabs中。

**Comment by xxn520** [comment]
上面只是我临时使用的方案，我觉得还需要更好的方案。

**Comment by benjycui** [comment]
😢  关掉 transform 的话，animation 的意义就没了。。。

**Comment by afc163** [comment]
关了，感觉我们解决不了。

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/1187

相关资料 http://ued.ctrip.com/blog/font-rendering.html translate3D 非整数会导致字体模糊

**Comment by paranoidjk** [comment]
@xxn520 不要重复提issue，需要在不同的仓库提的话，最好把issue关联起来，https://github.com/react-component/tabs/issues/61

**Comment by xxn520** [comment]
这个issue之前关了不准备修，所以在rc-tabs上新建了一个，而且确实应该由rc-tabs来修。关联issue之前没想到，谢谢指出，会及时改正。

至于这个问题的解决方案，stackoverflow 上的基本都试过了，都不能达到要求。

**Comment by qinyuanbin** [comment]
@afc163 这个问题我经常遇到，模糊是chrome gpu渲染的一个一直存在的问题，对于需要进行gpu渲染的dom，应该需要用一个隔离容器装起来，明确指出需要gpu渲染的区域，这样就不会影响到其他地方了
```css
.animation-container {
    position: absolute;
    overflow: hidden;
    transform: translateZ(0);
}
```
ps: `position: relative;`不知道行不行，以上全是建议，希望可以帮助到你们

**Comment by zombieJ** [comment]
antd@3 里 tabs 现在用 margin-left: -100% * N 了，应该可以关了。
