### ISSUE TITLE
如何获取select尚未选中，但处于高亮状态的option的值

### ISSUE THREAD

**Issue by CassiniatSaturn** [ant-design/ant-design#37020]
### What problem does this feature solve?

我需要封装一个可以使用键盘上下键和翻页键分页的带搜索功能的select组件。要求只有当键盘高亮在第一项select option的时候可以向上翻页，在最后一项select option的时候可以向下翻页，否则上下键只起到上下高亮选择的功能。目前我需要获取当前高亮的a-select-option在分页结果的数组中的下标。

### What does the proposed API look like?

在a-select-option处于高亮选中时，回调一个可返回结点数据的函数。
```ts
<a-select-option @highlight="getCurrentOption" value="">

const getCurrentOption = (option)=>{
....
}
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/37006#issuecomment-1212925069
