### ISSUE TITLE
Form设置disabled禁用了Pagination的页数选择框

### ISSUE THREAD

**Issue by zhushiyao** [ant-design/ant-design#37036]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-wescoff-htb1k5?file=/src/App.js)

### Steps to reproduce

打开页面即可复现

### What is expected?

期望`Pagination`的页数选择框不被视为表单组件禁用，与`showQuickJumper`一致 

### What is actually happening?

`Pagination`的页数选择框被禁用，快速跳转功能正常

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.0.0 |
| System | windows11 |
| Browser | chromev103 |

**Comment by izhouteng** [comment]
你为啥要把 `Table`  放到 `Form` 里？

**Comment by Mayvis** [comment]
@zhushiyao 我認為 antd 這種優先級才是比較正確的唷 如果以開發組件庫的角度出發的話
Form disabled 這屬性字面的意思 input select...等 只要是 antd 的組件在 form 內都要禁止 這應該是開發者的初衷
所以這部分我認為應該由你這個開發者去個別設定組件的 disabled 會比較好 別使用 Form disabled 這屬性
畢竟是組件庫 肯定是無法滿足每個開發者的需求的 你自己也能在撰寫上確保彈性 可以試想一下有人需求是跟你相反的話 該怎辦？
推薦你可以去參考一下 vue element-ui 組件庫 他那邊就寫得比較詳細了
Form disabled 屬性 他是這樣敘述的
是否禁用该表单内的所有组件。若设置为 true，则表单内组件上的 disabled 属性不再生效 <== 是不是跟你的使用情境剛好相反

**Comment by zhushiyao** [comment]
> 你为啥要把 `Table` 放到 `Form` 里？
@izhouteng 项目里有比较繁琐的表单需求，其中一块的表单数据增删改是使用`Table`进行展示和前端分页，所以才会放在`Form`里一起收集数据，也是因为到使用`Form`的性能比向上抛`change`更好

**Comment by zhushiyao** [comment]
> @zhushiyao 我認為 antd 這種優先級才是比較正確的唷 如果以開發組件庫的角度出發的話 Form disabled 這屬性字面的意思 input select...等 只要是 antd 的組件在 form 內都要禁止 這應該是 antd 開發者的初衷 所以這部分我認為應該由你這個開發者去個別設定組件的 disabled 會比較好 別使用 Form disabled 這屬性 畢竟是組件庫 肯定是無法滿足每個開發者的需求的 你自己也能在撰寫上確保彈性 可以試想一下有人需求是跟你相反的話 該怎辦？ 推薦你可以去參考一下 vue element-ui 組件庫 他那邊就寫得比較詳細了 Form disabled 屬性 他是這樣敘述的 是否禁用该表单内的所有组件。若设置为 true，则表单内组件上的 disabled 属性不再生效 <== 是不是跟你的使用情境剛好相反

@Mayvis  是的，你说的很合理，我也很认可，`Form`的`disabled`是个很好用的属性，我是希望在这个基础上灵活性更高一点，在issues中也看到了类似的提问，如果可以支持单独改变`Form`下的antd组件或者`Form.Item`不受控，那么所运用的场景会更多一点，也是我提出的方式有问题，把第二条的希望放在建议里面会更好点

**Comment by izhouteng** [comment]
> > 你为啥要把 `Table` 放到 `Form` 里？
> > @izhouteng 项目里有比较繁琐的表单需求，其中一块的表单数据增删改是使用`Table`进行展示和前端分页，所以才会放在`Form`里一起收集数据，也是因为到使用`Form`的性能比向上抛`change`更好

这能影响啥性能。。`Form` 里 建议只放 `Form.Item` 或者 `Row`。

**Comment by Mayvis** [comment]
> @Mayvis 是的，你说的很合理，我也很认可，`Form`的`disabled`是个很好用的属性，我是希望在这个基础上灵活性更高一点，在issues中也看到了类似的提问，如果可以支持单独改变`Form`下的antd组件或者`Form.Item`不受控，那么所运用的场景会更多一点，也是我提出的方式有问题，把第二条的希望放在建议里面会更好点

@zhushiyao 因為我沒找到你說的相關 issues 有在討論這塊 那我就假設你的方案是可行的好了
1. 使用 Form disabled={true} 參數時 可以在子層 使用 disabled={false} 來複寫掉 <== 這是你的使用情境
2. 而我的使用情境是 我子層已經事先 disabled 了 我想透過 Form disabled={false} 來關掉子層的 disabled <== 你的邏輯在我這邊就掛掉了因為 disabled 不掉子層

其實光上面這點你就很難去說服 antd 開發者去支持你的想法 我認為 畢竟組件庫是大家都要使用的 而我大部分遇到的使用情境都是第二個居多 換種講法就是要能在父層 toggle 子層的 disabled 
我在退一步好了
html css 是一種層級概念 因為 Form disabled 會跟 子層 disabled 衝突 所以你事必要再給 Form 一個全新的 props 類似 xxx-disabled={...} 去處理你的需求 亦或著每個 input select 都要有新的 props 讓 disabled 層級最高 我個人認為這也很難讓開發者願意去做這件事 不考慮開發成本 光是因為“易混淆”可能就不過關了 而僅僅是你可以不使用 Form disabled 這屬性就好

我認為你的出發點是好的 但這建議比較難說服人 個人想法

**Comment by zhushiyao** [comment]
> > @Mayvis 是的，你说的很合理，我也很认可，`Form`的`disabled`是个很好用的属性，我是希望在这个基础上灵活性更高一点，在issues中也看到了类似的提问，如果可以支持单独改变`Form`下的antd组件或者`Form.Item`不受控，那么所运用的场景会更多一点，也是我提出的方式有问题，把第二条的希望放在建议里面会更好点
> 
> @zhushiyao 因為我沒找到你說的相關 issues 有在討論這塊 那我就假設你的方案是可行的好了
> 
> 1. 使用 Form disabled={true} 參數時 可以在子層 使用 disabled={false} 來複寫掉 <== 這是你的使用情境
> 2. 而我的使用情境是 我子層已經事先 disabled 了 我想透過 Form disabled={false} 來關掉子層的 disabled <== 你的邏輯在我這邊就掛掉了因為關不掉子層 disabled
> 
> 其實光上面這點你就很難去說服 antd 開發者去支持你的想法 我認為 畢竟組件庫是大家都要使用的 而我大部分遇到的使用情境都是第二個居多 換種講法就是要能在父層 toggle 子層的 disabled 我在退一步好了 html css 是一種層級概念 因為 Form disabled 會跟子層 disabled 衝突 在不影響原功能的情況下 所以你勢必要再給 Form 一個全新的 props 類似 xxx-disabled={...} 去處理你的需求 亦或著每個 input select 都要有新的 props 讓 disabled 層級最高 我個人認為這也很難讓開發者願意去做這件事 不考慮開發成本 光是因為“易混淆”可能就不過關了 而僅僅是你可以不使用 Form disabled 這屬性就好
> 
> 我認為你的出發點是好的 但這建議比較難說服人 個人想法

@Mayvis  感谢你的讨论，我认同你的说法，众口难调，公共组件是没办法同时满足各种需求，保持通用即可，我删除掉了第二条`2、希望可以降低Form disabled的优先级，支持单个组件不禁用的方式`，第一条我还是先保留，视后续情况再决定是否关闭issues

**Comment by zhushiyao** [comment]
> 响啥性能。。`Form` 里 建议只放 `Form.Item` 或者 `Row`。

@izhouteng 是的，我也都是这样使用，这次比较特殊一点，已经通过`Form.Provider`解决了问题，即使用了`Form``disabled`的便捷，也解决了`Pagination`被禁用的问题

**Comment by MadCcc** [comment]
现在的代码实现中是这样的
```
const mergedDisabled = customDisabled || contextDisabled;
```
只要 Form 有 `disabled={true}`，组件本身的 disabled 就无效了。

考虑把 `||` 改成 `??`，会带来 breaking change。

**Comment by WeiShengv99** [comment]
也许可以增加一个选项  用于来控制   disabled的优先级， 权重可以反着来 这种。

**Comment by MadCcc** [comment]
Trace https://github.com/ant-design/ant-design/pull/37603
