### ISSUE TITLE
table 当有层级结构，且有父子关系的节点处于同节时，展开折叠会增加多余节点

### ISSUE THREAD

**Issue by dongkexin01** [ant-design/ant-design#37031]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-violet-ktjldg?file=/src/App.js)

### Steps to reproduce

点击「子」节点

### What is expected?

只展开折叠「子」节点

### What is actually happening?

展开折叠了「子」节点的同时，「子」节点的下级节点会增加

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.0.0 |
| System | mac |
| Browser | 104.0.5112.79 |

**Comment by downce** [comment]
这就是id重复了,每个节点要有唯一的id
