### ISSUE TITLE
`activeDefaultKey` prop doesn't work with dynamically load data (`<Collapse>` component)

### ISSUE THREAD

**Issue by corocoto** [ant-design/ant-design#37032]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-collapse-defaultactivekey-issue-cyu10l?file=/src/App.js)

### Steps to reproduce

 Click on adding note button twice or much more

### What is expected?

List of expected scenarios:
1. By default, added panel should be in expanded state, but it shouldn't;
2. If user adds 2 notes, 2 added panels also should be in expanded state;
3. If user added one note, clicked on it, and after it added the new one again, only the last added note should be open (because user closed previous one manually)

### What is actually happening?

Added panel isn't in expanded state.

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.0.0 |
| System | macOS Monterey v12.5 |
| Browser | Chrome v104.0.5112.79 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

**Comment by corocoto** [comment]
@afc163, thanks a lot!

**Comment by virtualvoid** [comment]
well thanks, but how do I expand the collapse (including sub collapses) when I'm creating that dynamically ?
