### ISSUE TITLE
AutoComplete输入法激活时无法停止auto-complete

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#37033]
### Reproduction link

[https://translate.google.cn/?sl=auto&tl=en&text=%E6%B2%A1%E5%BF%85%E8%A6%81&op=translate](https://translate.google.cn/?sl=auto&tl=en&text=%E6%B2%A1%E5%BF%85%E8%A6%81&op=translate)

### Steps to reproduce

使用AutoComplee时，受控的`onChange`处理事件，无法阻止在输入法打开的状态下的auto complete行为。而Input是可以的

![动画](https://user-images.githubusercontent.com/20441896/184317260-dd51fc6d-3bd9-4d8a-8a95-c2afbbc2c00a.gif)
> 输入法激活时，仍然在auto complete

### What is expected?

阻止在中文输入法状态下的auto complete行为

### What is actually happening?

无法阻止在中文输入法状态下的auto complete行为

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.0.3 |
| System | win10-64bit |
| Browser | chrome 103 |

---
Input 下阻止输入法时调用`onChange`的方式

```ts
import React, { ChangeEvent, CompositionEvent, useEffect, useRef, useState } from 'react'
import { Input } from 'antd'

import type { InputProps } from 'antd/lib/input'

const SearchInput: React.FC<InputProps> = props => {
  const { onChange, value, ...rest } = props
  const lock = useRef(false)
  const [inputValue, setInputValue] = useState(value)

  useEffect(() => {
    setInputValue(value)
  }, [value])

  const handleChange = (e: ChangeEvent<HTMLInputElement> | CompositionEvent<HTMLInputElement>) => {
    const { value } = e.target as HTMLInputElement
    setInputValue(value)
    if (e.type === 'compositionstart') {
      lock.current = true
    }
    if (e.type === 'compositionend') {
      lock.current = false
    }
    if (lock.current) return
    typeof onChange === 'function' && onChange(e as ChangeEvent<HTMLInputElement>)
  }

  return (
    <Input
      value={inputValue}
      onChange={handleChange}
      onCompositionStart={handleChange}
      onCompositionEnd={handleChange}
      {...rest}
    />
  )
}

export default SearchInput
```

注意AutoComplete没暴露`onCompositionStart`及`onCompositionEnd`，因此无法通过此方法解决

**Comment by izhouteng** [comment]
窝感觉雀食能优化下。

因为 `AutoComplete` 经常需要调用 API 获取搜索数据。

虽然可以自己用 `lodash.debounce` 函数优化下，但还是有点影响体验。

因为中文输入法打字时会频繁触发，就要调高 `debounce` 的 `wait`，但调高后，等真正从输入法选择结果后，等待的时间又长点，有那么一点点影响用户体验。

倒不如直接优化下这块地方。。

@afc163

**Comment by afc163** [comment]
@izhouteng 有啥思路直接来 PR？

**Comment by afc163** [comment]
@cangSDARM 你可以自定义 input 组件，添加 onCompositionStart 相关函数。

https://ant.design/components/auto-complete-cn/#components-auto-complete-demo-custom
