### ISSUE TITLE
table 数据发生变化时， column 的  render 方法没有重新执行

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#37034]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-22-4-forked-xgkd41?file=/demo.js)

### Steps to reproduce

点击新增按钮，
查看打印的日志

### What is expected?

点击新增按钮，table 重新渲染且 cloumns 中的 render 方法都将重新执行

### What is actually happening?

点击新增按钮，table 重新渲染且 cloumns 中的 render 方法没有全部重新执行，
而是只有新增的数据对应的 cloumns 的render 方法执行

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 16.8.6 |
| System | windows11 |
| Browser | Google 100.0.4896.60 |

**Comment by afc163** [comment]
这是符合预期的，请使用 shouldCellUpdate 来处理渲染问题。

**Comment by guaijie** [comment]
> 
请问使用过 shouldCellUpdate  吗？我使用了，任何情况下返回true 依然不能解决

**Comment by guaijie** [comment]
> 这是符合预期的，请使用 shouldCellUpdate 来处理渲染问题。

请问使用过 shouldCellUpdate 吗？我使用了，任何情况下返回true 依然不能解决

**Comment by yoyo837** [comment]
给新数组对象不行吗？

**Comment by zombieJ** [comment]
这个例子里的 console 不是每次点击添加都会触发 dataSource.length 次么？

**Comment by guaijie** [comment]
> 这个例子里的 console 不是每次点击添加都会触发 dataSource.length 次么？

那是因为我将 columns 放在了函数内部，每次都会重新渲染

**Comment by guaijie** [comment]
> 给新数组对象不行吗？

我们当然可以在问题存在时换种方式解决，当这掩盖不了问题本身存在，

**Comment by guaijie** [comment]
> ### You may look for issues:
> 1. 56% [table render column to display chart,  #36596](https://github.com/ant-design/ant-design/issues/36596)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)



> Since the issue was labeled with `needs-more-info`, but no response in 3 days. This issue will be closed. If you have any questions, you can comment and reply.
> 
> 由于该 issue 被标记为需要更多信息，却 3 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

该问题现在得到解决了吗
