### ISSUE TITLE
Style API for menu item

### ISSUE THREAD

**Issue by theredspoon** [ant-design/ant-design#37048]
### What problem does this feature solve?

Menu item styling cannot be prioritized over properties defined in antd's menu item classes without the use of "!important". 

In antd v4.21.0, React nodes referenced as menu items via the label property cannot be styled separately.

For example:
If I want to change the padding of one or multiple menu items, I must define the scope of those styles with a child selector "menu li" and then use "!important" to override existing styles specified in antd classes.

```
menu li {
  padding: '0 0 0 20px !important'; //overrides antd menu item padding
  after {
    right: '0 !important'; //overrides placement of antd menu item purple underline
  }
}
```

### What does the proposed API look like?

Could be one or several of the following:

1. Modifying specific menu items using emotion-styled object style syntax
```
items = [{
key: '1' ,
  style: {
    padding: '0 10px'
    }
  }, {
  key: '2',
  style: {
    "::after":{
      right: 0
    }
  }
}]
```

or 

2. Modifying specific menu items -- alternate
```
items = [{
  key: '1' ,
  label: <ReactNode />
  },
  ...
]
```
and then defining styles in the ReactNode referenced in the label property. If there were a need, style could also be passed as props here.

2. Modifying all menu items using emotion-styled object style syntax
```
<Menu style={
  `${
    padding: '0 10px',
    "::after": {
      right: 0
    }
  }`
}/>
```

**Comment by MadCcc** [comment]
Ant Design should not related to one of style processors, which means you can try any of them in your own custom components.

**Comment by theredspoon** [comment]
@MadCcc I think your comment misunderstands the request. The Menu component has a style property. The Menu Item component does not. The impact is that styling menu items requires overriding existing defaults with "!important". I don't think that should be expected behavior.

Hope that helps clarify.

**Comment by rjgrazioli** [comment]
Is there any resolution to this or a recommended approach?
