### ISSUE TITLE
级联选择器Cascader怎样取得label的文字呢？

### ISSUE THREAD

**Issue by mervynchung** [ant-design/ant-design#3704]
貌似Select中的labelInValue不能用在Cascader中？

**Comment by afc163** [comment]
第二个参数可以拿到整个 option `function onChange(value, selectedOptions)`

**Comment by petitspois** [comment]
@afc163  用getFieldDecorator 的时候怎么拿到 selectedOptions?

**Comment by benjycui** [comment]
使用了 getFieldDecorator 时也能使用 onChange 的。

**Comment by coldice945** [comment]
解决方法参考：https://github.com/ant-design/ant-design/issues/25093#issuecomment-926301251
