### ISSUE TITLE
Form.List获取数据不对！预期是获取数据，但是获取到了一个DOM元素

### ISSUE THREAD

**Issue by iDestin** [ant-design/ant-design#37044]
### Reproduction link

[https://stackblitz.com/edit/react-bl99t5?file=demo.js,components%2Frule.js,index.js](https://stackblitz.com/edit/react-bl99t5?file=demo.js,components%2Frule.js,index.js)

### Steps to reproduce

![图片](https://s3.bmp.ovh/imgs/2022/08/14/c6c2d0e65e605491.png)

### What is expected?

正常获取表单数据

### What is actually happening?

获取到了一个DOM元素，上面含有数据值字段

| Environment | Info |
| --- | --- |
| antd | 4.16.13 |
| React | 17.0.2 |
| System | MacOS 12.2.1 |
| Browser | 104.0.5112.79（正式版本） (x86_64) |

**Comment by iDestin** [comment]
有大佬遇到过这样的问题吗？

**Comment by afc163** [comment]
最好排查之后给个最小重现，现在演示代码有点复杂。

**Comment by iDestin** [comment]
> 最好排查之后给个最小重现，现在演示代码有点复杂。

大佬看看这个呢！https://stackblitz.com/edit/react-bl99t5-hmyh23?file=demo.js,index.css

**Comment by zombieJ** [comment]
```diff
    <Button
      type="link"
      icon={<PlusOutlined />}
--    onClick={add}
++    onClick={() => add()}
  />
```

**Comment by iDestin** [comment]
😅 哈哈哈，感谢大佬...学到了
