### ISSUE TITLE
RTL issue on antD Notification component

### ISSUE THREAD

**Issue by khizarnajeeb** [ant-design/ant-design#37059]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/notification-rtl-issue-rg68yi)

### Steps to reproduce

- Open codesandbox link
- Click on the Open the notification box button, and the notification would be displayed as LTR
- Now, click on the RTL radio button and then click on the Open the notification box button, the notification would be displayed as RTL
- Now again click on the LTR button and then click on the Open the notification box button, the notification is still showing as RTL instead of LTR

### What is expected?

Notification should be showing based on the Locale, On the LTR locale, the Icon should be showing first then the message, and then the close icon 

The issue could be caused due to the `ant-notification-rtl` class that is not being removed on the LTR locale.

### What is actually happening?

When we change the locale from RTL to LTR, `ant-notification-rtl` class keeps visible, and the layout is showing as RTL instead of LTR

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | Mac |
| Browser | Chrome |

---
This functionality works fine with the message component, the Message component example is also available in the `codesandbox` link

<img width="1137" alt="Screen Shot 2022-08-15 at 3 20 37 PM" src="https://user-images.githubusercontent.com/96875036/184618849-f1958bb2-4138-4a97-8ad6-630de6afec19.png">

**Comment by afc163** [comment]
That is why we have useNotification: https://ant.design/components/notification/#Why-I-can-not-access-context,-redux,-ConfigProvider-locale/prefixCls-in-notification

**Comment by khizarnajeeb** [comment]
Thanks @afc163 for the response.

The context provider also has the same issue. I tried useNotification example on the antD [doc](https://ant.design/components/notification/#components-notification-demo-update) but unfortunately, when I change the locale from RTL, the notification is still showing as RTL.

Steps to reproduce:
Open antd Notification [doc](https://ant.design/components/notification/#components-notification-demo-update)
Change the locale to RTL and then reload the page
Open the `useNotification` demo (for-example: Open bottomRight notification inside [Get context with hooks section])
Change the locale to LTR and open the same bottom Right notification inside the [Get context with hooks section] demo.
The notification will be displayed as RTL as mentioned in the below screenshot.

Also, the icon and close(x) button overlap with each other when I try to change the locale from LTR to RTL

<img width="1183" alt="Screen Shot 2022-08-15 at 7 02 17 PM" src="https://user-images.githubusercontent.com/96875036/184650276-2add1fcf-1e21-4ff5-93d5-8e0c3c8740da.png">

<img width="1263" alt="Screen Shot 2022-08-15 at 7 10 00 PM" src="https://user-images.githubusercontent.com/96875036/184651556-a9e1fe7b-7b1a-49aa-adc4-4db1f800c610.png">

**Comment by afc163** [comment]
When you open notification in ltr mode, antd will create a `className="ant-notification"` container for all notification instances. This container will be reused even direction is changed to rtl.

I believe it is not a real-world situation and I prefer to pass it.
