### ISSUE TITLE
使用antd-dayjs-webpack-plugin并配置国际化，DatePicker/RangePicker的format会有问题

### ISSUE THREAD

**Issue by alienzhangyw** [ant-design/ant-design#37054]
### Reproduction link
[sandbox环境无法重现](https://codesandbox.io/s/ant-design-forked-uf5350?file=/src/App.js:908-914)
### Steps to reproduce

1. 参考官方文档配置和使用antd-dayjs-webpack-plugin，确认没有FAQ中多个moment版本的问题。
2. 参考国际化的文档，使用configProvider设置antd的语言，并且可以切换语言。
3. 组件使用如下，其中format属性含有国际化的设置（参考moment.js的文档）：
``` js
<DatePicker
      defaultValue={moment('2022/1/1', 'l')}
      format="l"
      style={{ width: 200 }}
      onChange={(v) => {
            console.log(v);
            console.log(moment.locale());
            console.log(v?.format('l'));
      }}
/>
```

### What is expected?

1. 切换antd语言时，组件上显示的时间格式也会跟随locale变化。
2. 能够手动输入改变DatePicker的value。

### What is actually happening?

1. 切换antd语言时，组件上显示的时间格式不会跟随locale变化，需要手动刷新页面或者通过面板来改变值（组件本身的文本语言会变化）。
2. 无法手动输入来改变value，修改后按回车会变回defaultValue，且不会触发onChange事件。
3. 将format=“l”注释掉可恢复正常，说明是该属性的问题。
![动画](https://user-images.githubusercontent.com/58874541/184598656-db79ea37-5d17-4e87-97c9-8e36926c37bf.gif)

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 18.2 |
| System | win10 |
| Browser | Edge 103 |

**Comment by alienzhangyw** [comment]
在codeSandbox里没法复现。
但是我可能找到原因了。
https://github.com/react-component/picker/blob/7492e10fc73fca9a29b0bb3e17efbec79a0d8b97/src/generate/dayjs.ts#L165
`const date = dayjs(formatText, format).locale(localeStr);`
当手动在输入框输入时间时，这一行解析date会出错。
比如当实际参数是`dayjs('2019/1/2 09:01:33', 'l HH:mm:ss').locale('zh-cn')`时得到的date就是invalidDate。
最大的嫌疑是dayjs的advancedFormat插件没有真正生效，要不就是语言包没有加载上。

如果format不包含advancedFormat的格式，或者不启用antd-dayjs-webpack-plugin，一切都是正常的。

**Comment by alienzhangyw** [comment]
> 在codeSandbox里没法复现。 但是我可能找到原因了。 https://github.com/react-component/picker/blob/7492e10fc73fca9a29b0bb3e17efbec79a0d8b97/src/generate/dayjs.ts#L165 `const date = dayjs(formatText, format).locale(localeStr);` 当手动在输入框输入时间时，这一行解析date会出错。 比如当实际参数是`dayjs('2019/1/2 09:01:33', 'l HH:mm:ss').locale('zh-cn')`时得到的date就是invalidDate。 最大的嫌疑是dayjs的[LocalizedFormat](https://day.js.org/docs/zh-CN/plugin/localized-format)插件没有真正生效，要不就是语言包没有加载上。 因为rc-picker这里并没有导入这个localizedFormat插件:https://github.com/react-component/picker/blob/7492e10fc73fca9a29b0bb3e17efbec79a0d8b97/src/generate/dayjs.ts#L12-L17
> 
> 如果format不包含localizedFormat的格式，或者不启用antd-dayjs-webpack-plugin，一切都是正常的。

经过调试研究，终于知道问题出在哪了：
antd传到rc-picker组件里调用的是generate/moment.ts，
https://github.com/react-component/picker/blob/7492e10fc73fca9a29b0bb3e17efbec79a0d8b97/src/generate/moment.ts#L115
其中parser是这样的：`const date = moment(formatText, format, locale, true);`，传进来的locale没有做map处理，中文的话是‘zh_CN’，比如`moment('2022/8/1 15:27:11', 'l HH:mm:ss', 'zh_CN', true)`
然后由于webpack插件的存在，moment被替换成了dayjs，就变成了`dayjs('2022/8/1 15:27:11', 'l HH:mm:ss', 'zh_CN', true)`，所以dayjs找不到该locale，所以解析不出来。
如果参数是`dayjs('2022/8/1 15:27:11', 'l HH:mm:ss', 'zh_cn', true)`，是能正常解析出来的。

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
