### ISSUE TITLE
defaultPickerValue not working for <RangePicker> 

### ISSUE THREAD

**Issue by jeremypeters** [ant-design/ant-design#37058]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ilcthw?file=/index.js:441-453)

### Steps to reproduce

Look at minimal reproduction

### What is expected?

The range picker should be populated with the dates provided to `<RangePicker>` via the `defaultPickerValue ` prop.

### What is actually happening?

The provided dates are ignored.

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 18.2.0 |
| System | MacOS 11.6 |
| Browser | Chrome 104.0.5112.79 |

**Comment by afc163** [comment]
The two panels of RangePicker cannot be two different dates, so only the first date of defaultPickerValue works.

**Comment by jeremypeters** [comment]
Seems like odd behaviour - it's a date range picker so it would be logical to be able to provide a date range, i.e. two different dates. And also in that case why is it expecting an array composed of two dates when only one is expected?
