### ISSUE TITLE
table组件，自动省略时候并且开启expandRowByClick={true}，点击Tooltip内部内容，会影响表格的展开收起

### ISSUE THREAD

**Issue by 172297555** [ant-design/ant-design#37050]
### Reproduction link

[https://stackblitz.com/edit/react-ccr5xw?file=demo.js,package.json](https://stackblitz.com/edit/react-ccr5xw?file=demo.js,package.json)

### Steps to reproduce

比如我要复制省略后 ，ToolTip内的文字，点击Tooltip内容

### What is expected?

不影响表格的展开收起 

### What is actually happening?

会展开收起

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.0.2 |
| System | macos 11.6  |
| Browser | 谷歌版本 104.0.5112.79（正式版本） (arm64) |

**Comment by afc163** [comment]
onClick stopPropagation()
