### ISSUE TITLE
Select、AutoComplete 分页的问题

### ISSUE THREAD

**Issue by yqwoe** [ant-design/ant-design#3705]
该如何实现？

**Comment by benjycui** [comment]
目前不支持分页，不知道你的使用场景是怎样？

**Comment by yqwoe** [comment]
@benjycui  我的使用场景是：下拉框中数据量比较大，然后我第一次加载只放入一页数据，当用户选择下拉的过程中开始异步加载。

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/select/issues/18

**Comment by benjycui** [comment]
或者我们可以增加个 `onScrollToEnd` 事件，当用户滚动到下拉菜单的底部时触发？

**Comment by benjycui** [comment]
Relative: https://github.com/ant-design/ant-design/issues/2092

**Comment by RaoHai** [comment]
“加载更多...”

**Comment by yqwoe** [comment]
或者我们可以增加个 onScrollToEnd 事件，当用户滚动到下拉菜单的底部时触发？@benjycui 可取

**Comment by benjycui** [comment]
> “加载更多...”

现在先用 @RaoHai 的方法实现。

`onScrollToEnd` 更多是交互优化。

**Comment by nicelj** [comment]
autocomplete怎么获取选中值啊 onchange里面放的是数据来源
