### ISSUE TITLE
modalRender with button inside does not trigger onClick

### ISSUE THREAD

**Issue by diegogurgel** [ant-design/ant-design#37060]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/use-hooks-to-get-context-antd-4-22-3-forked-0vo0tq?file=/demo.js:294-308)

### Steps to reproduce

Click on the button "Show modal", after the modal appears click on the button "Try me" 

### What is expected?

On the console, you should see  the message "Try me clicked"

### What is actually happening?

Nothing is being shown on the console  

### Confirm modal config
```javascript
const config = {
  modalRender: () => {
    return (
        <Button
          onClick={() => {
            console.log("Try me clicked");
          }}>
          Try me
        </Button>
    );
  }
};
```

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 16.12 |
| System | MacOS |
| Browser | Chorme - Version 103.0.5060.134 |

---
It is like the levels on the dialog are on top of the content preventing any interaction. I tried to change the z-indexes but it didn't work. When I render using the content config the button is interactive but the default controls are also present which I do not want. I'm assuming that other controls like inputs will not work also. Thank you

**Comment by afc163** [comment]
You can try https://codesandbox.io/s/use-hooks-to-get-context-antd-4-22-3-forked-08sovx

**Comment by diegogurgel** [comment]
If someone comes across this, the solution is to set the pointer-events as `auto` on your modal render content.

**Comment by A-birdFlyHigner** [comment]
加上 style={{ pointerEvents: 'auto' }}

**Comment by Priyanshsharma21** [comment]
> pointerEvents: 'auto'

Thanks bro It worked - 
<Modal
        visible={visible}
        // onCancel={onCancel}
        footer={null}
        type="primary"
        style={{
          background: "transparent",
          pointerEvents: "auto",
        }}
        modalRender={() => (
          <>
            <div className={classNames.eventDetailModelHomeNextBtn}>
              <button
                style={{
                  background: "transparent",
                  border: "none",
                  color: "#fff",
                  fontSize: 14,
                  cursor: "pointer",
                }}
                onClick={() => onClickRegister(data._id)}
   
              >
                Ok, I understand
              </button>
            
            </div>
          </>
        )}
        closeIcon={true}
      />
