### ISSUE TITLE
table表格高度不能自定义

### ISSUE THREAD

**Issue by Flame38** [ant-design/ant-design#37069]
### What problem does this feature solve?

我想要一个固定高度的表格，因为在数据不够的时候表格并没有撑满所给的区域高度，这样看起来下面会有很大的空白，分页只解决了过多数据情况，没有解决较少数据时的表格整体表现

### What does the proposed API look like?

固定高度的表格，使分页永远处于所给区域的右下角，而不是随着表格数据的多少而上下浮动

**Comment by zombieJ** [comment]
页面上长啥样子？

**Comment by Flame38** [comment]
如图所示，在数据过少的情况下页面有一半没有被任何组件覆盖




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月16日(星期二) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] table表格高度不能自定义 (Issue #37069)





 
页面上长啥样子？&nbsp;

**Comment by Flame38** [comment]
我的有数据，不是空数据，这个链接没有解决我的需求，不过谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] table表格高度不能自定义 (Issue #37069)





 
You may look for issues:
  
50% #14459
  
🤖 By issues-similarity-analysis

**Comment by afc163** [comment]
图在哪。

**Comment by Flame38** [comment]
我放到了邮件中，您看不到吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月16日(星期二) 中午11:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] table表格高度不能自定义 (Issue #37069)





 
图在哪。

**Comment by MadCcc** [comment]
邮件回复看不到的

**Comment by Flame38** [comment]
![页面](https://user-images.githubusercontent.com/55654498/184830274-0e765ead-373c-4c50-930c-b2aca933141b.png)

**Comment by afc163** [comment]
你期望的样子是什么样的

**Comment by Flame38** [comment]
想让分页始终在页面最下方，而不是跟随表格内信息多少而变化

**Comment by baikai55** [comment]
意思是要一个固定的高度？
scroll={{ y: height }}

**Comment by Flame38** [comment]
我使用了这个方法，他只能在数据量够多的时候生成滚动条来加载所有数据，而在数据量不足以撑满父组件高度时并没有什么效果，最后我通过计算高度并动态添加空数据来填满高度得以解决这个问题，感谢您的帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月18日(星期四) 上午9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] table表格高度不能自定义 (Issue #37069)





 
意思是要一个固定的高度？
 scroll={{ y: height }}

**Comment by zombieJ** [comment]
Table 的 Pagination 是 Table 的一部分，这种拆分设计上不合理。如果是需要始终在最下面，建议直接隐藏 Table 的 Pagination，然后自行 HOC 实现。

**Comment by Flame38** [comment]
好的，谢谢您的建议：）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月18日(星期四) 下午3:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] table表格高度不能自定义 (Issue #37069)





 
Table 的 Pagination 是 Table 的一部分，这种拆分设计上不合理。如果是需要始终在最下面，建议直接隐藏 Table 的 Pagination，然后自行 HOC 实现。

**Comment by wangchao18654941093** [comment]
> Table 的 Pagination 是 Table 的一部分，这种拆分设计上不合理。如果是需要始终在最下面，建议直接隐藏 Table 的 Pagination，然后自行 HOC 实现。

我并不认为这是一种拆分，我觉得这是一种很常见的业务场景，固定Table的高度，不会因为table数据的多少而改变整体的布局（分页会上移），但是咱们Table 却不支持，没发通过正常且合理的途径去解决这种需求

**Comment by wangchao18654941093** [comment]
难道你不觉得  存在分页时，当你点击最后一页（最后一页的数据很少时），分页忽然跑到了上面，布局一下就变了，不觉得很怪异吗？用具体验极差

**Comment by Flame38** [comment]
我添加到了附件里面，可以看到吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] table表格高度不能自定义 (Issue #37069)





 
邮件回复看不到的

**Comment by Atw-Lee** [comment]
可以通过样式覆盖，外层定义一个height值，子元素一层一层的 height：inherit实现
