### ISSUE TITLE
Rate 组件🌟数与 value 不是四舍五入关系

### ISSUE THREAD

**Issue by ch-liuzhide** [ant-design/ant-design#37072]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ji-ben-antd-4-22-5-forked-0yctzb?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

rate 组件 value 设置为 1.9

### What is expected?

2 颗星

### What is actually happening?

1 颗星

| Environment | Info |
| --- | --- |
| antd | 4.18.9 |
| React | 17.0.1 |
| System | mac os |
| Browser | chrome 91 |

---
四舍五入会更合理，2.9 分渲染 2颗星有点过分。

**Comment by MadCcc** [comment]
自行控制下近似逻辑就行，我觉得 2.9 渲染 3颗星也有点过分
