### ISSUE TITLE
Form 如何实现两个输入框联动呢？

### ISSUE THREAD

**Issue by CMG-CEO** [ant-design/ant-design#37079]
### What problem does this feature solve?

例如，两个输入框，当输入框输入 "111" 时，用什么方法可以将输入框2的配置项required 置为true（原先是false）
是否只能用设置一个state来控制呢？
如果是一个Form.List内要实现这样的需求呢？

### What does the proposed API look like?

无

**Comment by zombieJ** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-5-forked-qk5yhj?file=/demo.js

**Comment by CMG-CEO** [comment]
> 如果是一个Form.List内要实现这样的需求呢？

**Comment by Yilun-Sun** [comment]
> > 如果是一个Form.List内要实现这样的需求呢？

1. 对你的 `Form.Item` 加入 dependencies 或者 shouldUpdate 方法，使其依赖某个表单项
```TypeScript
shouldUpdate={(prevValues, curValues) => prevValues.name !== curValues.name}
```

2. 在 `Form.Item` 里写你的 rules 规则时，加入一个 validator
```TypeScript
rules={[
  {
    validator: ({ getFieldValue }) => {
      const name = getFieldValue([
        'name'
      ])

      if (name === '111') {
        return Promise.reject(
          new Error('此项为必填'),
        )
      } else {
        return Promise.resolve()
      }
    },
  },
]}
```
validator 中获取了 name 的值，然后进行判断，如果条件符合就返回 Promise.resolve()，如果不符合就返回 Promise.reject()。reject 中的 new Error('此项为必填') 的内容你可以自己定制。

@CMG-CEO 另外，最好不要 validator 和其他规则一起用，可以把直接所有你需要的规则都在 validator 中处理了。

**Comment by Chralay** [comment]
> https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-5-forked-qk5yhj?file=/demo.js

请问用Form.Item的dependencies属性能实现吗？我试了一下没效果
