### ISSUE TITLE
动态主题 紧凑主题结合使用

### ISSUE THREAD

**Issue by darin-lao** [ant-design/ant-design#37071]
### What problem does this feature solve?

现在动态主题无法跟紧凑主题变量结合使用

### What does the proposed API look like?

在umi配置开始动态主题，在config/config.ts
{
"theme": {
  '@root-entry-name': 'variable',  // 开启动态CSS变量主题
},

 antd: {
    compact: true, // 开启默认紧凑主题
  },
}

运行代码ConfigProvider可以动态切换compact变量

**Comment by zombieJ** [comment]
嗯，两者涉及 less 变量有所交织。暂无兼容计划。
