### ISSUE TITLE
Antd Sidebar Scrollbar resets when clicking menu item

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#37094]
### Reproduction link

[https://6xy1de.csb.app/user](https://6xy1de.csb.app/user)

### Steps to reproduce

Click any bottom menu items and the scrollbar will force to load on top not sure if the whole app rerenders? 
If yes any suggestion to fix this?

### What is expected?

Should stay where the scrollbar is placed should not reset or rerender or go up

### What is actually happening?

Sidebar scrollbar goes up

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by tempoeric** [comment]
@afc163 @zombieJ  any idea on this?

**Comment by afc163** [comment]
It is not a antd bug, the whole Menu is rerender when click menu.

We use similar layout with Menu on the left, and it works fine: https://ant.design/components/input-cn/

**Comment by tempoeric** [comment]
so how can i fix this to prevent the scroll from resetting and going up?

**Comment by tempoeric** [comment]
I hope we can fix this rerender issue

**Comment by tempoeric** [comment]
Hi @afc163 i know that you said this is not a bug but can we have a patch fix for this on where the sidebar doesnt need to go up and stays on place where the menu is active something like that cause our UX Designer doesnt want the overflow-y from going from the very top since we have a lot of items in the menu

**Comment by b-codex** [comment]
anyone found a way around this?

**Comment by tempoeric** [comment]
> anyone found a way around this?

Hi here is a solution i came up with while encountering the issue maybe this will help you
https://m5bd0g.csb.app/user
