### ISSUE TITLE
Badge单独使用初始位置偏移

### ISSUE THREAD

**Issue by jialeicui** [ant-design/ant-design#3709]
#### 发生问题的环境是：

- antd 版本:2.2.1
- 操作系统及其版本:OSX 10.11.6
- 浏览器及其版本:Safari 10.0.1 / Chrome 54.0.2840.71

问题描述: 
载入之后 ScrollNumber 有一个移动的过程, 只要刷新就能重现过程

[http://codepen.io/anon/pen/qqWMrr?editors=0010](http://codepen.io/anon/pen/qqWMrr?editors=0010)

**Comment by afc163** [comment]
还以为这里修复了。https://github.com/ant-design/ant-design/commit/1da5490ab8cd091a40338e845abe4a11552361a2

其实并没有。

**Comment by jialeicui** [comment]
多谢👍

**Comment by afc163** [comment]
1da5490 之前的修复完全是自欺欺人... 😓
