### ISSUE TITLE
select组件提供获得当前选中项的文本的属性

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#3710]
antD的select组件，现在能获取到选中的key，但是拿不到对应的text。如果key和text不一样的话，那么如果想获取text，必须得遍历一遍才行。
建议select增加属性，获取当前选中的项的文本。
迫切需要，多谢。

**Comment by yesmeck** [comment]
`labelInValue` 

https://ant.design/components/select/#components-select-demo-label-in-value
