### ISSUE TITLE
关于 Avatar 配合 Image 添加 referrerPolicy 属性

### ISSUE THREAD

**Issue by Xiaochena** [ant-design/ant-design#37107]
### What problem does this feature solve?

我在 给Acatar添加 referrerPolicy 属性 时 注意到 #31840 中提到方法
```tsx
import { UserOutlined } from "@ant-design/icons";
import { Avatar, Image } from "antd";

 <Avatar
  icon={<UserOutlined />}
  src={
    <Image
      refererPolicy="noreferrer"
      src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png"
    />
  }
/>
```
但是我留意到 这样做后 Acatar 的icon将失效、同时 Image的 fallback 只接收string、
这意味着我不得不将 `<UserOutlined />` 转为 base 64

### What does the proposed API look like?

````tsx
<Image
    refererPolicy="noreferrer"
    src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png"
    fallback={<UserOutlined />}
/>
````
或 Avatar 可以和Image 配合 使icon不失效

### 例子
[code](https://codesandbox.io/s/ji-ben-antd-4-22-5-forked-6h3c6p?file=/demo.js)

**Comment by afc163** [comment]
@Xiaochena 为啥关了？留个结论？

**Comment by Xiaochena** [comment]
> @Xiaochena 为啥关了？留个结论？

哈哈、因为我不确定我这是否是一个合理的需求。怕给大佬带来困扰
且我自行封装了一个组件作为对 `Avatar`的扩充

```tsx
import React from "react";

import { Avatar } from "antd";

const NewAvatar = (props) => {
  const { src, ...otherProps } = props;
  const hasImageElement = React.isValidElement(src);

  const [isSrcSucess, setIsSrcSucess] = React.useState(true);

  const onError = () => {
    setIsSrcSucess(false);
  };

  let srcToRender;
  if (hasImageElement) {
    srcToRender = React.cloneElement(src, { onError: onError });
  }

  return <Avatar {...otherProps} src={isSrcSucess ? srcToRender : ""} />;
};

export default NewAvatar;

```

[code demo]( https://codesandbox.io/s/ji-ben-antd-4-22-5-forked-6h3c6p?file=/demo.js )

**Comment by Xiaochena** [comment]
所以这个需求是合理的嘛、是否计划修改

**Comment by davepoon** [comment]
This is required to fix the issue when using an avatar image from social login(Google, Apple, Twitter login, etc.), otherwise, it cannot load the image.

A similar issue in Chakra UI.
https://github.com/chakra-ui/chakra-ui/issues/5909
