### ISSUE TITLE
DatePicker 使用 format 但是 value 还是全部的值

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#37104]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-4-forked-14vne5?file=/demo.js)

### Steps to reproduce

- 选择日程
- 查看控制台

### What is expected?

YYYY-MM-DD HH

### What is actually happening?

YYYY-MM-DD HH:mm:ss

![image](https://user-images.githubusercontent.com/7971419/185022866-42253af2-6e22-415c-8aea-2f840c52b0e2.png)

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | latest |
| System | mac |
| Browser | edge |

**Comment by zombieJ** [comment]
`value` 是 `moment`，和 DatePicker 的 format 没有关系。DatePicker format 是组件展示值，返回的 value 总是 moment 对象。

**Comment by crazyair** [comment]
> `value` 是 `moment`，和 DatePicker 的 format 没有关系。DatePicker format 是组件展示值，返回的 value 总是 moment 对象。

我觉得可以根据 format 格式化一次，`moment(value,format)`

**Comment by zombieJ** [comment]
> > `value` 是 `moment`，和 DatePicker 的 format 没有关系。DatePicker format 是组件展示值，返回的 value 总是 moment 对象。
> 
> 我觉得可以根据 format 格式化一次，`moment(value.format(format))`

这个没什么意义，`_d` 是它内部的临时结构，本身就是不给外部用户使用的。`moment` 本身不存储 `format` 你初始化传入什么 format 它都不会存这个 format。

**Comment by crazyair** [comment]
我用 getValueFromEvent 截断吧
