### ISSUE TITLE
Broken stackblitz playground

### ISSUE THREAD

**Issue by Lantianyou** [ant-design/ant-design#37113]
### Reproduction link

[https://stackblitz.com/run?file=demo.js](https://stackblitz.com/run?file=demo.js)

### Steps to reproduce

here

### What is expected?

The react version should be match

### What is actually happening?

not matched

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | any |
| System | any |
| Browser | any |

![image](https://user-images.githubusercontent.com/37259750/185052475-cf5ca5f5-80bf-4e16-a00f-089adf444e3b.png)

**Comment by MadCcc** [comment]
It seems to be problem with stackblitz's cache, the dependencies should be consistent with configuration.
We will remove react 17 demo soon to fix it.

**Comment by Lantianyou** [comment]
Thanks! Not only for this particular issue, but also for this great UI library called `antd`

**Comment by Lantianyou** [comment]
@zombieJ @MadCcc  Mind if re-opening the issue. Seems the dependencies (react/reactDOM) is not updated and wrong entry file. 
![image](https://user-images.githubusercontent.com/37259750/188051014-e838dc43-db71-4b31-865a-9869649e348a.png)
