### ISSUE TITLE
how to customize antd theme using webpack with react version@18 , 

### ISSUE THREAD

**Issue by devnomi1** [ant-design/ant-design#37123]
### Reproduction link

[https://github.com/hassanrafay/track/blob/tree-shaking/client/webpack.config.js](https://github.com/hassanrafay/track/blob/tree-shaking/client/webpack.config.js)

### Steps to reproduce

how to slove it

### What is expected?

Tell me how can i do this

### What is actually happening?

when i update antd.css to antd.less then syling is not applying

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | React |
| System | window 10, 64bit , |
| Browser | chrome |

---
module.exports = {
    mode: 'development',
    optimization: {
        usedExports: true
    },
    module: {
        rules: [
            {
                test: /\.less$/i,
                use: [
                    {
                        loader: 'style-loader'
                    },
                    {
                        loader: 'css-loader'
                    },
                    {
                        loader: 'less-loader',
                        options: {
                            lessOptions: {
                                strictMath: true,
                                modifyVars: {
                                    'primary-color': 'red',
                                    'link-color': '#1DA57A',
                                    'border-radius-base': '4px'
                                },
                                javascriptEnabled: true
                            }
                        }
                    }
                ]
            }
        ]
    }
};

**Comment by NadirBakhsh** [comment]
Hello, @devnomi1 if you are useing react@18 version with next.js you needs to install `[next-with-less](https://www.npmjs.com/package/next-with-less)' 

OR

if you are using  Pure create react app here we needs to configure first less compling with webpack.config
here is the installation link
https://webpack.js.org/loaders/less-loader/

**Comment by devnomi1** [comment]
thanks to response but  i have installed these dependencies and and config webpack but it is not working

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by afc163** [comment]
<img width="819" alt="图片" src="https://user-images.githubusercontent.com/507615/185279474-87c24c9e-70ed-4d75-ad5b-b280ef809c35.png">

**Comment by devnomi1** [comment]
Hey,
I have mentioned a link as I have tried to customize the ant-design theme with webpack but is not working. why ?
https://codesandbox.io/s/antd-reproduction-template-forked-cnfn33?file=/webpack.config.js
[https://codesandbox.io/api/v1/sandboxes/cnfn33/screenshot.png]<https://codesandbox.io/s/antd-reproduction-template-forked-cnfn33?file=/webpack.config.js>
antd reproduction template (forked) - CodeSandbox<https://codesandbox.io/s/antd-reproduction-template-forked-cnfn33?file=/webpack.config.js>
antd reproduction template (forked) using antd, less, moment, react, react-dom
codesandbox.io

________________________________

**Comment by devnomi1** [comment]
that is way to I am customize antd them using webpack
https://codesandbox.io/s/antd-reproduction-template-forked-cnfn33?file=/App.js
________________________________

**Comment by afc163** [comment]
Your webpack.config.js cannot start in the codesandbox.

**Comment by devnomi1** [comment]
As I mentioned  am using this code to customize antd theme so tell me this is way correct or not if any mistake then correct and tell me what happing here. you can see my code I just sample you to using code this way as i mentioned in codesandbox
________________________________

**Comment by devnomi1** [comment]
so ..?

________________________________

**Comment by afc163** [comment]
Could you provide a debuggable reproduce that can be started in local?

**Comment by devnomi1** [comment]
nope this private projects , I have sent you sample in codesandbox so what is the mistake ?
________________________________

**Comment by devnomi1** [comment]
are you getting my point what i am trying to say?
________________________________

**Comment by afc163** [comment]
I cannot start the webpack dev server in https://codesandbox.io/s/antd-reproduction-template-forked-cnfn33?file=/App.js
 so that I can see why your config is not working.

**Comment by devnomi1** [comment]
OKay I am sharing files there you can see
________________________________

**Comment by devnomi1** [comment]
please find attached

________________________________

**Comment by devnomi1** [comment]
Hello,
I have sent you my project you do not respond yet, I am still waiting for your response.
how much you will take to response
________________________________

**Comment by devnomi1** [comment]
?
________________________________

**Comment by afc163** [comment]
Cannot see files in github issue.

**Comment by devnomi1** [comment]
is it antd-design ? If i am stuck in this then I required solution from you
________________________________

**Comment by devnomi1** [comment]
this is not closed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
