### ISSUE TITLE
Table.Summary prop 'fixed' doesn't work when it's in separate component

### ISSUE THREAD

**Issue by CatherineShemenkova** [ant-design/ant-design#37126]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-30deth)

### Steps to reproduce

I need to provide a summary row, and it needs to be pinned on top.

Given `Table` component.

And I create separate component (need to reuse it in other tables, there are many tables in my project) and return from it `Table.Summary` with `fixed="top"` prop

And I pass this component to the `summary` prop of `Table` component

### What is expected?

`Table.Summary` is fixed in accordance with the `fixed` prop.

### What is actually happening?

`Table.Summary` is not fixed. Displayed at the end of the table.

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 17 |
| System | macos |
| Browser | chrome/firefox |

**Comment by zombieJ** [comment]
Do not use Wrap component since it can not get props of `fixed`:

https://codesandbox.io/s/antd-reproduction-template-forked-puon11?file=/index.js
