### ISSUE TITLE
Menu的bug

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#3712]
#### 发生问题的环境是：

- antd 版本:  2.0
- 操作系统及其版本:  OS X 10.11.6
- 浏览器及其版本: Chrome 版本 54.0.2840.71 (64-bit)

Menu的bug

Menu的Item内容过长的话，会被截断，右边显示不出小箭头了，见下图。

![image](https://cloud.githubusercontent.com/assets/23185348/19959066/d709e418-a1de-11e6-8c8d-a2992c1ed90c.png)

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

另外，针对这种超长文案，你期待的方式是啥？
