### ISSUE TITLE
BackTop组件问题（页面很长，但BackTop按钮无法显示）

### ISSUE THREAD

**Issue by wangwufan** [ant-design/ant-design#37136]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-chu-qia-pian-forked-07zh33)

### Steps to reproduce

页面打开后，从顶部向下滚动

### What is expected?

显示“回到顶部”按钮，且按钮有效

### What is actually happening?

看不到“回到顶部”按钮

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | chrome 104.0.5112.81（正式版本） （64 位） |

---
页面上有Tabs组件，TabPane内容很长，整个页面都有滚动条，但BackTop按钮始终无法显示

**Comment by afc163** [comment]
1. 不需要 target，滚动条在 body 上。
2. 没有引 antd 的样式。

https://codesandbox.io/s/ji-chu-qia-pian-forked-ye87t6?file=/App.tsx

**Comment by wangwufan** [comment]
最终原因，如果body中存在样式 overflow-y: overlay;    BackTop按钮就无法显示，去掉就好了

**Comment by wangwufan** [comment]
我的样例代码有问题，没能完全还原我的场景。
后来发现，如果body中存在样式 overflow-y: overlay;
BackTop按钮无法显示，去掉就好了


***@***.***
 
发件人： afc163
发送时间： 2022-08-18 16:19
收件人： ant-design/ant-design
抄送： wangwufan; Author
主题： Re: [ant-design/ant-design] BackTop组件问题（页面很长，但BackTop按钮无法显示） (Issue #37136)
不需要 target，滚动条在 body 上。
没有引 antd 的样式。
https://codesandbox.io/s/ji-chu-qia-pian-forked-ye87t6?file=/App.tsx
