### ISSUE TITLE
Customizing font size base theme

### ISSUE THREAD

**Issue by adinu** [ant-design/ant-design#37133]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-h3dfxd?file=/App.css)

### Steps to reproduce

Trying to change the font size base using the configProvider/css variables (look at solution 1/2 in my codesandbox)

### What is expected?

it should change the font size base

### What is actually happening?

it doesn't

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

---
i want to be able to change the font size not from .less file, and can't find a way to do it.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/discussions/37128#discussioncomment-3419173
