### ISSUE TITLE
Pagination的simple属性会把showTotal的设置无效掉

### ISSUE THREAD

**Issue by KevinBrother** [ant-design/ant-design#37140]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mi-ni-antd-4-22-6-forked-nbqnu9?file=/demo.js)

### Steps to reproduce

Pagination 同时设置simple和showTotal
  <Pagination size="small" total={50} showTotal={showTotal} simple={true} />

### What is expected?

simple只是改变分页的样式，是否showTotal由showTotal属性控制

### What is actually happening?

Pagination的simple属性会把showTotal的设置无效掉

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 17.0.1 |
| System | macos |
| Browser | chrome-100 |

**Comment by afc163** [comment]
simple 模式就是不带其他选项，否则就不 simple 了，因此最开始也没有设计其他属性开启的展现方式。

**Comment by KevinBrother** [comment]
simple修改的样式应该和showTotle无关的吧，想simple就不设置showTotle就行了呀

**Comment by KevinBrother** [comment]
https://github.com/react-component/pagination/pull/433

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/pagination/pull/433
