### ISSUE TITLE
input的suffix中的icon的事件无法触发

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#3714]
发生问题的环境是：

antd 版本: 2.0
操作系统及其版本: OS X 10.11.6
浏览器及其版本: Chrome 版本 54.0.2840.71 (64-bit)

如题，input的suffix中的icon的点击事件无法触发，然而在Prefix中增加的icon能够触发事件。

![image](https://cloud.githubusercontent.com/assets/23185348/19959143/6b0b5f34-a1df-11e6-950b-16db5fefb15c.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
http://codepen.io/afc163/pen/ENaMNL?editors=0011

**Comment by benjycui** [comment]
可点击区域比看起来小，这个用样式调整吧。

**Comment by bf185003** [comment]
改好了什么时候能发布呢？  @afc163

**Comment by afc163** [comment]
观察一下上面这个 commit，2.4.0 里应该已经发布了。
