### ISSUE TITLE
关于自定义表单Input、Select、Picker等组件的focus状态边框颜色问题

### ISSUE THREAD

**Issue by zrless** [ant-design/ant-design#37150]
### What problem does this feature solve?

有的公司产品的主题色是红色系或者黄色系，自定义primary-color颜色的时候，表单组件的focus状态边框颜色也会被更改，看起来像是报错或者警告，视觉体验上会产生歧义

### What does the proposed API look like?

themes/default.less中新增一个@active-border-color用于自定义表单 在focus/active状态的border-color

**Comment by arvinxx** [comment]
V5 里会支持好这个部分

**Comment by afc163** [comment]
@arvinxx 现在能解决了么

**Comment by arvinxx** [comment]
@afc163 能，改这几个 token 应该就可以：

- controlOutline
- controlItemBgActiveHover
- controlItemBgHover

**Comment by arvinxx** [comment]
@zrless 可以试试看，有问题再 reopen 吧
