### ISSUE TITLE
关于引入lodash包的问题

### ISSUE THREAD

**Issue by moshuchao** [ant-design/ant-design#37156]
### What problem does this feature solve?

减少打包体积

### What does the proposed API look like?

进行tree shaking

比如仅仅引用`<Avatar/>`，此时体积是：
![image](https://user-images.githubusercontent.com/27390758/185559860-734405dd-744d-4855-b65a-16c8b578a82e.png)

**Comment by yoyo837** [comment]
我看了一下依赖，lodash都是局部引用，只是好像起步需要这个大小。

**Comment by afc163** [comment]
貌似没找到可优化的点，如果有发现，欢迎直接来 PR

**Comment by tonny008** [comment]
主要是rc-align依赖了lodash的isEqual，isEqual依赖了lodash中其他好多
优化就得不判断deep equal，而是依赖immutable

**Comment by afc163** [comment]
是否可以用 https://www.npmjs.com/package/shallowequal 代替？

**Comment by yoyo837** [comment]
光去掉这里作用也有限，其他rc-*和ant-design也要配合吧？

**Comment by tonny008** [comment]
如果要换可以考虑这个
https://github.com/shuding/stable-hash

**Comment by yoyo837** [comment]
Trace in #39594
