### ISSUE TITLE
tooltip set `visible` to `undefined` tooltip shows

### ISSUE THREAD

**Issue by ah-yu** [ant-design/ant-design#37153]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-22-3-forked-l87l8h?file=/demo.js)

### Steps to reproduce

鼠标hover到文字上，点击(visible设为false)，把鼠标移出去，再把鼠标移到文字上，再点击按钮(visible设为undefined)，tooltip显示出来了

https://user-images.githubusercontent.com/23608309/185533141-bc9a1f0f-323d-4075-949a-5adb9b522f81.mov

### What is expected?

tooltip不显示

### What is actually happening?

tooltip显示了

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 16.14.0 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
受控 与 非受控 切换并不保证其行为正确性，还是建议始终保持 受控 或者 非受控。
