### ISSUE TITLE
Select the first option by default

### ISSUE THREAD

**Issue by Lantianyou** [ant-design/ant-design#37159]
### Reproduction link

[https://stackblitz.com/](https://stackblitz.com/)

### Steps to reproduce

This is a question

### What is expected?

This is a question

### What is actually happening?

This is a question

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | latest |
| System | any |
| Browser | any |

---
Is there a way to set the first options in a select by default. For example, 
```jsx
<Form.Item >
        <Select 
                options={options}
                selectDefaultFirstOption={true} />
</Form.Item>
```
As options changes dynamically, the default value is always the first option element by default. I tried 
-  `initialValues` in Form
-  `initialValue` in Form.Item
-  `defaultValue` in `Select`
None of the above is working. Would any one kind enough in the ant design community enlighten me with the solution? Thanks a lot.

**Comment by zombieJ** [comment]
`useEffect` with `setFieldsValue` to handle this.

**Comment by Lantianyou** [comment]
This would be quite convoluted if there is many filed depends on each other. For example if field C' options depends on field B's value, and field B's options depends on field A's value.

**Comment by XuQiY** [comment]
@Lantianyou 
Consider wrapping the Select For FormItem
![image](https://user-images.githubusercontent.com/30062755/186377846-5185bbb1-058c-492f-9dfb-3542eb7578d9.png)

**Comment by Lantianyou** [comment]
Thank you !
