### ISSUE TITLE
Typography editable 希望可以支持 defaultEditing，autofocus 或者 api 接口

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#37163]
### What problem does this feature solve?

可以支持默认状态下的文本编辑

### What does the proposed API look like?

defaultEditing autofocus

**Comment by tolerance-go** [comment]
另外现在 Typography 的一些属性比如 id，在 editing 状态下是不传的，这样不太不方便取元素

**Comment by afc163** [comment]
Duplicate of #25811
