### ISSUE TITLE
[bug] Search 按钮样式和Button样式不一样

### ISSUE THREAD

**Issue by neo-of-matrix** [ant-design/ant-design#37166]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sou-suo-kuang-antd-4-22-4-forked-okmtvp)

### Steps to reproduce

Search 按钮样式和Button样式不一样

### What is expected?

Search 按钮样式和Button样式保持一致

### What is actually happening?

Search 按钮样式和Button样式不一样

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | ^16.14.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
有啥区别？

**Comment by MadCcc** [comment]
Background in `ghost` Button is `transparent`, you can custom it with `style`.

**Comment by neo-of-matrix** [comment]
> 

Search 按钮样式是灰色的不是透明的，Button按钮是透明的

**Comment by neo-of-matrix** [comment]
> 有啥区别？

Search 按钮样式是灰色的不是透明的，Button按钮是透明的
