### ISSUE TITLE
[Bug] DatePicker 焦点问题

### ISSUE THREAD

**Issue by neo-of-matrix** [ant-design/ant-design#37165]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-22-4-forked-2uq02r?file=/demo.js)

### Steps to reproduce

点击一个日期输入框，按住鼠标不动然后移动到另一个日期输入框，这时会触发另一个日期输入框的点击事件

### What is expected?

不会触发另一个日期输入框的点击事件

### What is actually happening?

触发另一个日期输入框的点击事件

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | ^16.14.0 |
| System | windows |
| Browser | chrome |

**Comment by neo-of-matrix** [comment]
没有解决问题

**Comment by MadCcc** [comment]
实际场景是什么？

**Comment by neo-of-matrix** [comment]
> 实际场景是什么？

比如一个DatePicker，一个Input, 用户经常选择Input 内容进行复制时会滑到DatePicker

**Comment by wangmeijian** [comment]
我来处理
