### ISSUE TITLE
Cannot press space in input inside tab

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ant-design/ant-design#37172]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-tab-input-bug-q5d64t?file=/index.js)

### Steps to reproduce

```jsx
import { Tabs } from "antd"

<Tabs defaultActiveKey="tab">
  <Tabs.TabPane
    key="tab"
    tab={<input defaultValue="Try pressing space" />}
  >
    Tab Content
  </Tabs.TabPane>
</Tabs>
```

### What is expected?

Input should work like normal.

### What is actually happening?

I can type letters and numbers, but pressing space bar doesn't do anything. Copying and pasting space works.

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Microsoft Edge: 104.0.1293.54 (Official build) (64-bit)  |

---
Discovered bug when trying to make editable tabs: https://codesandbox.io/s/antd-editable-tabs-5bl1ty

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-tab-input-bug-forked-utnhvh?file=/index.js
Try `stopPropagation`

**Comment by ChocolateLoverRaj** [comment]
@MadCcc why is stopPropogation needed? I looked at the rc-tabs code and didn't see any handlers for space key. Is it related to keyboard navigation with Tab key?
