### ISSUE TITLE
Table横向滚动到任一位置，动态新增了Column后，滚动位置发生了变化

### ISSUE THREAD

**Issue by 1ib0** [ant-design/ant-design#37179]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-22-7-forked-ssqof1?file=/demo.js)

### Steps to reproduce

1. 横向向右滚动，让`Column 1`滚动到左侧固定列的相邻右侧位置
2. 点击Table上方的`expand按钮`
3. 这样会动态新增了两列`test1`和`test2`

### What is expected?

期望点击Table上方的`expand按钮`后，滚动条不要变化，固定列右侧的列仍然是`Column 1`

### What is actually happening?

Table会滚动，导致固定列的右侧是`Age`，同时横向向左滚动（轻微滚动即可），但是会发现，固定列的右侧又突然变成了`Column 1`

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 18.3.0 |
| System | Intel Mac OS X 10_15_7 |
| Browser | Chrome/104.0.5112.79 |

**Comment by zombieJ** [comment]
动态 columns 看起来会有时机问题

**Comment by libo-FE** [comment]
@zombieJ 看起来是table-header发生了滚动，table-body是正常的

**Comment by libo-FE** [comment]
@zombieJ 请问这个bug的修复计划是怎样的呢？有预期的发布时间吗

**Comment by 1ib0** [comment]
@zombieJ 请问这个问题有修复吗？我看有人提了PR，但是还没同意并且发布吧？

**Comment by 1ib0** [comment]
@zombieJ rc-table更新了版本后，是不是antd也需要更新下package.json中rc-table的版本，并发布一个新版本呢？

**Comment by code1379** [comment]
https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-22-7-forked-change4-24-8-etj1sm?file=/demo.js 
我把 antd 升级到了 4.24.8 看上去 问题似乎没有解决

**Comment by 1ib0** [comment]
> https://codesandbox.io/s/gu-ding-tou-he-lie-antd-4-22-7-forked-change4-24-8-etj1sm?file=/demo.js 我把 antd 升级到了 4.24.8 看上去 问题似乎没有解决

你需要升级的不是antd，而是rc-table。可以通过 https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/ 试下

**Comment by JJL-SH** [comment]
使用了临时的方案，主动触发一下滚动
`
React.useLayoutEffect(() => {
    let _node = document.getElementsByClassName('ant-table-body')[0];

    if (_node) {
      _node.scrollLeft++;
    }
}, [列长度值])
`
