### ISSUE TITLE
ConfigProvider doesn't apply the locale

### ISSUE THREAD

**Issue by yantakus** [ant-design/ant-design#37184]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-borg-8w7ky8)

### Steps to reproduce

Open the codesandbox. You can see the locale is not applied (we get US date format - 08/22/2022). If you uncomment line 15 you can see it changes to en-GB format - 22/08/2022.

### What is expected?

ConfigProvider should apply the given locale.

### What is actually happening?

It works only if `locale` prop is passed directly to `<DatePicker />`.

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 18.2.0 |
| System | Codesandbox |
| Browser | Chrome |

**Comment by zombieJ** [comment]
https://ant.design/components/config-provider/#components-config-provider-demo-locale

> moment.locale('en');

**Comment by yantakus** [comment]
@zombieJ thanks for the response. I tried it before and it doesn't help. I've updated the codesandbox above so that you can check it yourself. I've added `moment.locale("en")` and the date is still in US format (08/23/2022). I also tried `moment.locale("en-gb")`, doesn't work as well. The only way to make it work for me is to pass locale to the `DatePicker` itself, but it what I need is to use `ConfifProvider` to set the locale globally for all the components.

**Comment by zombieJ** [comment]
> https://ant.design/components/config-provider/#components-config-provider-demo-locale

Demo is all you need : )
https://codesandbox.io/s/intelligent-boyd-i5murq?file=/src/App.js

**Comment by yantakus** [comment]
@zombieJ Ah, thank you very much. What I was missing is `import "moment/locale/en-gb";`. This does the trick!
