### ISSUE TITLE
RangePicker 是否可以手填开始和结束年月日

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3718]
#### 本地环境

- antd-mobile 版本： ant designer 2.0.1
- 操作系统及其版本：windows 7旗舰版
- 浏览器及其版本：Chrome最新版

#### 你做了什么？

RangePicker 是否可以手填开始和结束年月日

#### 你期待的结果是：

RangePicker 可以手填开始和结束年月日，
因为我想输入 2016年12月1日~2099年12月1日，这样选择太繁琐啦

#### 实际上的结果：

RangePicker 貌似不可手动输入年月日

#### 可重现的在线演示

官网就可以。

**Comment by afc163** [comment]
1. 初始状态应该可以手填。
2. 现在填完就浮层消失了，最好不消失。

**Comment by benjycui** [comment]
1.x 的版本是可以手动输入 http://1x.ant.design/components/date-picker/#components-date-picker-demo-range

2.x 就不可以了 https://ant.design/components/date-picker/#components-date-picker-demo-range

当时做这个改动的目的是？ @RaoHai

**Comment by RaoHai** [comment]
我记得一开始 7.x 的时候也是可以输的……

**Comment by afc163** [comment]
现在选完之后是可以输的，没填值时不能。

**Comment by RaoHai** [comment]
https://github.com/react-component/calendar/commit/b6f2e1c710dc469173e331b081886244073611a1#diff-98d6796a72d7a2aa84fe51945063026cR58

这儿改掉的
