### ISSUE TITLE
bundle.js:5305 Warning: Failed prop type: Invalid prop `defaultChecked` supplied to `Checkbox`

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3719]
#### 发生问题的环境是：

- antd 版本:ant design 2.0.1
- 操作系统及其版本:Windows 7 旗舰版
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

引入了一个选择框 并设置defaultChecked
   <Checkbox id="code-enabled" defaultChecked={true} />

#### 您期待的结果是:

正常显示不弹出警告

#### 实际上的结果是:

bundle.js:5305 Warning: Failed prop type: Invalid prop `defaultChecked` supplied to `Checkbox`

#### 可重现的在线演示
![01](https://cloud.githubusercontent.com/assets/6470398/19960017/476b9a98-a1e5-11e6-80e9-0abf0bf65956.png)
![02](https://cloud.githubusercontent.com/assets/6470398/19960024/4c5a51f2-a1e5-11e6-83ee-686f61d13b82.png)

**Comment by yesmeck** [comment]
defaultChecked 必须是 number 或者 bool。

**Comment by eddyzhang1986** [comment]
OK,谢谢那我自己关了，谢谢

**Comment by eddyzhang1986** [comment]
是我们自己不小心设置了undefined,谢谢兄台。 @yesmeck 。
