### ISSUE TITLE
格式错误

### ISSUE THREAD

**Issue by zhangxingkong** [ant-design/ant-design#37203]
### Reproduction link

[https://ant.design/components/progress-cn/](https://ant.design/components/progress-cn/)

### Steps to reproduce

文档错误，一看便知

### What is expected?

string | string[] | { from: string, to: string, direction: string }

### What is actually happening?

string | string[] | { from: string; to: string; direction: string }

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 16.14.0 |
| System | mac |
| Browser | 版本 104.0.5112.101（正式版本）  |

---
文档错误一看就知道了，object里面的间隔是逗号，不是分号

**Comment by MadCcc** [comment]
是 TS 类型，不是 object
