### ISSUE TITLE
Form.List 在应用 preserve 的情况下 表现异常（文档里没有提到 isListField 相关信息）

### ISSUE THREAD

**Issue by WeiShengv99** [ant-design/ant-design#37202]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-zeng-jian-qian-tao-zi-duan-antd-4-22-7-forked-yhnv44?file=/demo.js)

### Steps to reproduce

1. 多点击几次点击 add field
2. 删除 其中一项
发现其他的  input值都被清除
1. 取消注释demo里的 代码
2. 重复上诉操作
3. 表现符合预期  其他input 没有被清除

### What is expected?

删除 form item 的时候 不影响其他 form item

### What is actually happening?

影响到其他item

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 17 |
| System | maos  big sur 11.6 |
| Browser | 版本 104.0.5112.101（正式版本） (arm64) |

**Comment by WeiShengv99** [comment]
应该是  formList 下的item  不许传递  fieldKey字段导致的 问题

**Comment by WeiShengv99** [comment]
或许可以优化下文档 关于  ...restProps 这部分操作 发生了什么事情 做一个说明。

**Comment by WeiShengv99** [comment]
![image](https://user-images.githubusercontent.com/35689628/186147418-d68afc82-0149-4e7b-ba75-8714d941b5e3.png)
TS的类型里也没有提到相关信息

**Comment by yoyo837** [comment]
怎么有点看不懂是描述啥

**Comment by WeiShengv99** [comment]
> 怎么有点看不懂是描述啥

Form.list 在和 preserve  一期使用的情况下， Form.Item必须传入 isListField 字段，不然在remove 的时候 会导致其他 item 的值清空

**Comment by zombieJ** [comment]
`fields` 里的东西需要都传给 Field，文档示例都是解构过去。不透出就是为了减少理解成本哈~

**Comment by lunar9621** [comment]
同样遇到“删除 其中一项，其他的 input值都被清除”的情况，还是在文档上加下吧 挺坑的
