### ISSUE TITLE
Select组件children使用条件渲染不符合预期

### ISSUE THREAD

**Issue by realzbc** [ant-design/ant-design#37209]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-4-22-7-forked-nz8m26?file=/demo.js)

### Steps to reproduce

在select输入文字，模拟搜索操作；

### What is expected?

在select中输入文字，下拉框显示“有值”选项

### What is actually happening?

在select中输入文字，下拉框显示 No Data

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | react 16.14 |
| System | macos |
| Browser | chrome latest |

**Comment by MadCcc** [comment]
1. option 需要 `value`；
2. select 中输入会触发筛选；

所以输入后在 options 中不存在对应的选项，下拉框显示 No Data。
