### ISSUE TITLE
当输入框填写“age”后，过滤后的包含 age 的 CheckBox 无法进行勾选

### ISSUE THREAD

**Issue by Emma-Alpha** [ant-design/ant-design#37206]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-tree-sqsdi6?file=/src/App.js)

### Steps to reproduce

1. 输入框中 填写 "age"
2. 将选中的age CheckBox 勾选状态取消掉
3. 再次点击age CheckBox 。
4. 发现无法选中了

### What is expected?

age CheckBox 勾选状态取消掉之后，再次点击后能够勾选上。

### What is actually happening?

age CheckBox 勾选状态取消掉之后，再次点击没有办法再次勾选上

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 18.2.0 |
| System | macOS 12.5 |
| Browser | 谷歌浏览器 104.0.5112.101 |

**Comment by zombieJ** [comment]
不要用 `index` 作为 key:
https://codesandbox.io/s/bold-lalande-k3dfbl
