### ISSUE TITLE
antd@2.2.0--Objects are not valid as a React child (found: object with keys {})

### ISSUE THREAD

**Issue by jeffycai** [ant-design/ant-design#3721]
#### 发生问题的环境是：

- antd 版本:2.2.0
- 操作系统及其版本:win10
- 浏览器及其版本:

#### 您做了什么？请提供尽可能详细的重现步骤。

Uncaught Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `RadioGroup`.(…)

**Comment by afc163** [comment]
```
<RadioGroup> 里面不能是 undfined <RadioGroup>
```

**Comment by JohnnyCao** [comment]
考虑兼容下？

**Comment by benjycui** [comment]
之前升 TypeScript@2.0 搞出的问题。。。 https://github.com/ant-design/ant-design/commit/08e21e0a2f734069faea4857329c64ca4b42287a#diff-d16752570f220b20a4a4b6c4019ac801R84

一直以来都是不支持 `children=undefined` 的。

**Comment by benjycui** [comment]
我还是做下兼容，与 Menu 支持 children 有`null|undefined` 的行为一致把。

**Comment by jeffycai** [comment]
tks,已解决。

**Comment by wang-dq** [comment]
怎么解决的
