### ISSUE TITLE
在 Select 多选模式的时候，当Form 的 initialValues 为 null 不是 [] 的时候，渲染了一个空的选择，怪怪的

### ISSUE THREAD

**Issue by wsdo** [ant-design/ant-design#37226]
### Reproduction link

<img width="140" alt="image" src="https://user-images.githubusercontent.com/9738969/186565260-27016d56-1ccd-4411-84f2-ae7426d96a49.png">

### What is expected?

期待处理一下 null 

处理成这种效果
<img width="114" alt="image" src="https://user-images.githubusercontent.com/9738969/186565826-9c3675ac-c0b5-4507-aa06-8a457228c6e1.png">

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/34437
