### ISSUE TITLE
Document how to replace deprecated withConfigContext()

### ISSUE THREAD

**Issue by heath-freenome** [ant-design/ant-design#37221]
### What problem does this feature solve?

We have code using the `withConfigContext()` HOC, but my IDE and the [code](https://github.com/ant-design/ant-design/blob/master/components/config-provider/context.tsx#L86) all indicate this is deprecated and to use hooks instead... But there is no documentation about HOW to use hooks to replace this function

### What does the proposed API look like?

Either the code itself describes how to use hooks or there is a documentation around how to do this somewhere easily searchable/accessible to users

**Comment by MadCcc** [comment]
```
import { ConfigProvider } from 'antd';
const Demo = () => {
  const { ...context } = useContext(ConfigProvider.ConfigContext);
  // ...
}
```
