### ISSUE TITLE
treeSelect 下拉列表滑动时数据渲染异常

### ISSUE THREAD

**Issue by RJM1996** [ant-design/ant-design#37228]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-gou-xuan-antd-4-22-7-forked-ykjdrj?file=/demo.js)

### Steps to reproduce

1、treeData 的 children 中配置了相同 key,value 的数据
2、初次打开时渲染正常

3、上下滑动后，下拉列表变为相同的一项，即 value 重复的那一项
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-gou-xuan-antd-4-22-7-forked-ykjdrj?file=/demo.js)

### Steps to reproduce

1、treeData 的 children 中配置了相同 key,value 的数据
2、初次打开时渲染正常
3、上下滑动后，下拉列表变为相同的一项，即 value 重复的那一项

### What is expected?

期望下拉列表根据 treeData 渲染

### What is actually happening?

上下滑动后，下拉列表变为相同的一项，即 value 重复的那一项

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 16.14 |
| System | Mac OS |
| Browser | Chrome 版本 104.0.5112.101（正式版本） (x86_64) |

### What is expected?

期望下拉列表根据 treeData 渲染

### What is actually happening?

上下滑动后，下拉列表变为相同的一项，即 value 重复的那一项

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 16.14 |
| System | Mac OS |
| Browser | Chrome 版本 104.0.5112.101（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
> treeData 的 children 中配置了相同 key,value 的数据

需要保证 value 唯一
