### ISSUE TITLE
treeSelect 组件设置treeCheckStrictly，maxTagCount={0}时，maxTagPlaceholder传入参数omittedValues不符合预期

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#37220]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-bvmq3j?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

选择选项

### What is expected?

omittedValues 与 value 一致

### What is actually happening?

omittedValues 与 value 不一致

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | Microsoft Edge 版本 104.0.1293.63 (正式版本) (64 位) |

**Comment by MadCcc** [comment]
建议配合 `showCheckedStrategy={TreeSelect.SHOW_ALL}` 使用，目前显示上是符合逻辑的，去掉 `maxTagCount={0}` 可以看出来。
