### ISSUE TITLE
antd tree-select

### ISSUE THREAD

**Issue by pavankaki** [ant-design/ant-design#37223]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-22-7-forked-mqjtqv?file=/demo.js:0-1623)

### Steps to reproduce

https://codesandbox.io/s/basic-antd-4-22-7-forked-mqjtqv?file=/demo.js:0-1623

### What is expected?

In tree select when there are more than 7 options it is showing 7 only example parent 1-0 has 10 leaves but showing only 7

### What is actually happening?

In tree select  parent 1-0 should have 10 leaves 

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.14.0 |
| System | windows 11  |
| Browser | chrome |

**Comment by zombieJ** [comment]
<img width="521" alt="截屏2022-08-25 10 20 23" src="https://user-images.githubusercontent.com/5378891/186559281-a412a498-b0f2-43c8-923a-8e798e2cde76.png">
