### ISSUE TITLE
Why are the values ​​entered into the inputs cleared during step change?

### ISSUE THREAD

**Issue by huseyingoztok** [ant-design/ant-design#37222]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/switch-step-antd-4-22-7-forked-xnv4ds?file=/demo.js)

### Steps to reproduce

https://codesandbox.io/s/switch-step-antd-4-22-7-forked-xnv4ds?file=/demo.js

### What is expected?

What is the best practice to keep the values ​​in step changes?

### What is actually happening?

Values ​​are not preserved in step changes. Is this (https://stackoverflow.com/questions/63807887/antd-v4-steps-and-form) solution correct?

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`useForm` to create Form instance to store the data. Your code destroy Form on every step change.

**Comment by huseyingoztok** [comment]
Which method would you recommend prevent destroy input data? @zombieJ

**Comment by huseyingoztok** [comment]
Is there a way to implement the useForm structure with useRef? How can I prevent the form instance from being destroyed in a version prior to Ant design 4? @zombieJ

**Comment by huseyingoztok** [comment]
https://codesandbox.io/s/switch-step-antd-4-22-7-forked-m1rfus?file=/demo.js
