### ISSUE TITLE
提供一个属性，决定AutoComplete是否需要 selected 样式

### ISSUE THREAD

**Issue by albert-cai** [ant-design/ant-design#37239]
### What problem does this feature solve?

虽然明确区分了AutoComplete和Select的使用，但是由于Select无法选中选择项，导致在某需要复制选中的值的场景下，只能用AutoComplete来替代，无法开启了以后，在cursor不在选中项上的时候，会找不到选中项是哪一个，

### What does the proposed API look like?

提供一个选项，来控制AutoComplete是否需要 selected 样式

**Comment by albert-cai** [comment]
@afc163

**Comment by albert-cai** [comment]
hello？

**Comment by afc163** [comment]
最终组件大概长什么样的？能否再精确描述一下？

**Comment by afc163** [comment]
有更多信息，欢迎继续回复，我会再 reopen。
