### ISSUE TITLE
minCount for <Upload > tag

### ISSUE THREAD

**Issue by lxtadhamnawito** [ant-design/ant-design#37242]
### What problem does this feature solve?

Sometimes you want to restrict the user to at least upload specific number of files before submit or before going with further actions, but this is not provided in the <Upload> tag. As you can specify maxCount of uploads but there's no way to restrict the minCount of uploads.

### What does the proposed API look like?

The minCount attribute will probably work as maxCount but you have to provide at least this number of files to be acceptable or your uploads will not show  "or display a message that says doesn't met minimum number of files to be uploaded"

The attribute should look like this
```
     <Upload minCount={2} maxCount={4} >
        <Button icon={<UploadOutlined />}>Upload</Button>
      </Upload>
```

**Comment by afc163** [comment]
See https://ant.design/components/upload/#components-upload-demo-fileList

**Comment by lxtadhamnawito** [comment]
@afc163 I've seen the it's saying "limit the number of uploaded files." but I though it means to limit them with maxCount.
and I couldn't find in the example anything that explain how to limit it to minimum number of uploaded files.

would you guide me please?
