### ISSUE TITLE
antd-tree-select

### ISSUE THREAD

**Issue by pavankrishna12345** [ant-design/ant-design#37244]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-22-7-forked-mqjtqv?file=/demo.js:0-1572)

### Steps to reproduce

https://codesandbox.io/s/basic-antd-4-22-7-forked-mqjtqv?file=/demo.js:0-1572

### What is expected?

when a tree select has more than 7 options it should display all options

### What is actually happening?

when a tree select has more than 7 options it is displaying first 7 options only

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.14.0 |
| System | windows 11  |
| Browser | chrome |

**Comment by pavankaki** [comment]
> ### You may look for issues:
> 1. 54% [antd tree-select #37223](https://github.com/ant-design/ant-design/issues/37223)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

Nope. It is not similar

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/186844499-2bacb9ab-ab62-4437-9f19-e98c84d081c6.png)
Cannot reproduce.
