### ISSUE TITLE
折叠面板能支持横向折叠吗？

### ISSUE THREAD

**Issue by PengQingYao** [ant-design/ant-design#37248]
### What problem does this feature solve?

页面是左侧是一个菜单， 希望可以折叠。 目前只支持纵向折叠，不支持横向折叠

### What does the proposed API look like?

<Collapse direction=xxx>
   xxxxx
<Collapse>

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/components/menu-cn/#components-menu-demo-inline-collapsed
