### ISSUE TITLE
TreeSelect 多选模式下，父亲节点选中并进行过滤显示错误

### ISSUE THREAD

**Issue by flyingzl** [ant-design/ant-design#3724]
#### 发生问题的环境是：

- antd 版本: 2.2.1
- 操作系统及其版本: win7
- 浏览器及其版本: Chrome 50.0.2661.94 

#### 您做了什么？请提供尽可能详细的重现步骤。

1. 打开样例 [https://ant.design/components/tree-select/](https://ant.design/components/tree-select/)
2. 定位到第三个样例，即多选样例
3. 清除`Node1`, 然后选中`Node2`, 会发现其下的三个孩子全部选中
4. 过滤，输入数字`2`，会显示`Child-Node5`,并且没有被选中
5. 选中`Child-Node5`, 文本框中会同时显示 `Node2`和`Child-Node5`

#### 您期待的结果是:

步骤4中，`Child-Node5`应该处于被选中状态

#### 实际上的结果是:

步骤4显示错误， `Child-Node5`该处于未选中状态
步骤5显示错误，不应该同时显示 `Node2`和`Child-Node5`，父亲和孩子不应该同时显示

**Comment by warmhug** [comment]
不是 bug，是正常行为。为什么这么做，见此 https://github.com/react-component/tree-select/issues/31#issuecomment-234715081
