### ISSUE TITLE
表单错误提示为什么不支持ReactNode？

### ISSUE THREAD

**Issue by margintopt** [ant-design/ant-design#37257]
### What problem does this feature solve?

表单错误提示为什么不支持ReactNode？

### What does the proposed API look like?

表单错误提示支持ReactNode？

**Comment by MadCcc** [comment]
`help` 和 `rules` 里的 `message` 都支持 ReactNode

**Comment by yunsii** [comment]
> `help` 和 `rules` 里的 `message` 都支持 ReactNode

为什么类型提示上不完善一下呢？
