### ISSUE TITLE
table 有一个不分配 width 的列宽自适应失败

### ISSUE THREAD

**Issue by Guokaiming** [ant-design/ant-design#37268]
### Reproduction link

[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce

切换 tab 渲染同一个组件，只不过组件内部接口不同，接口返回的部分字段不同，然后列项前部分相同、后部分相同，第二项不相同（不给宽度，自适应），宽度固定为 100%，第二项的宽度随着 tab 切换宽度没有自适应

### What is expected?

自适应宽度的列项 根据 列项自适应

### What is actually happening?

上个列项的宽度被带到上的列项的宽度中

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 18.1 |
| System | mac |
| Browser | chrome 104 |

---
多个 tab 切换渲染同一个组件（组件内部有 table 组件），请求接口不同，table 展示的列项不同但有相同处

举例：
tab1: id（104）、name（自适应）、adminer（118）、time（132）、edit（60）
tab2: id（104）、name（自适应）、a（118）、b（118）、adminer（118）、time（132）、edit（60）
tab3: id（104）、name（自适应）、c（118）、d（118）、e（118）、adminer（118）、time（132）、edit（60）

切换 tab 看表格，name 的自适应宽度会被带入到另一个 tab 下，然后拉长整个表格，表格设置 width 100% 不生效也不出现滚动条

**Comment by Guokaiming** [comment]
已经写上去了，然后发现是 grid 布局的某个属性，理解不精造成的。
demo 地址：https://codesandbox.io/s/antd-reproduction-template-forked-bw75kq?file=/Madular/style.css
已经发现问题所在：Madular/style.css 已经标注问题所在

**Comment by afc163** [comment]
所以是业务样式代码问题，不是 antd 的问题？
