### ISSUE TITLE
Add a "Select All" option in an AntD table filter? (feature request)

### ISSUE THREAD

**Issue by igalci** [ant-design/ant-design#37265]
### What problem does this feature solve?

I have a filter menu for the "Industry" column.

Lets say the user wants to select all industries, except for one.

Is there a way to implement a "Select All" button (perhaps beside the "Reset" button) to select all options so the user could de-select the option he wants to exclude?

![image](https://user-images.githubusercontent.com/70971657/186934568-5007722f-74a2-4e97-a21c-1d8f49ed7c9d.png)

### What does the proposed API look like?

This is the proposed "selectAll" option for a column in the antd table. Or maybe change the "Reset" button to "Select All" automatically when there is no selection made:
```
	{
			title: "Industry",
			dataIndex: ["industry","sector"],
			filters: sectors, 
                        filterSelectAllButton: True,
			onFilter: (value, record) => record.sector.indexOf(value) === 0,
		},
```

**Comment by afc163** [comment]
You can try `filterMode: "tree"`: https://codesandbox.io/s/zlo1gi?file=/demo.js

**Comment by amirrstm** [comment]
I've tried to write it independently, hoping It'll help you.

`import React, { Key, useState } from 'react'

import { Button, Checkbox, Input, TableColumnType } from 'antd'
import { ColumnFilterItem, FilterDropdownProps } from 'antd/es/table/interface'

function useTableFilter<T>(): { getColumnFilterProps: (dataIndex: string) => TableColumnType<T> } {
  const getColumnFilterProps = (dataIndex: string): TableColumnType<T> => {
    return {
      filterDropdown: ({ setSelectedKeys, selectedKeys, confirm, clearFilters, filters, ...props }) => (
        <div style={{ padding: 8 }} onKeyDown={e => e.stopPropagation()}>
          <FilterCheckBoxes
            {...props}
            filters={filters}
            confirm={confirm}
            selectedKeys={selectedKeys}
            clearFilters={clearFilters}
            setSelectedKeys={setSelectedKeys}
          />

          <div className="flex justify-between pt-2">
            <Button
              type="link"
              onClick={() => {
                clearFilters?.()
                confirm({ closeDropdown: true })
              }}
              size="small"
            >
              Reset
            </Button>

            <Button size="small" type="primary" onClick={() => confirm({ closeDropdown: true })}>
              Search
            </Button>
          </div>
        </div>
      ),

      onFilter: (value, record: any) => (record[dataIndex] || '') === (value as string),
    }
  }

  return { getColumnFilterProps }
}

export default useTableFilter

const FilterCheckBoxes: React.FC<FilterDropdownProps> = ({ filters, selectedKeys, setSelectedKeys }) => {
  const [search, setSearch] = useState('')
  const [activeFilters, setActiveFilters] = useState<ColumnFilterItem[]>(filters as ColumnFilterItem[])

  const onSearch = (value: string) => {
    if (value) {
      setSearch(value)
      setActiveFilters(
        (filters as ColumnFilterItem[])?.filter(filter =>
          (filter?.value as string).toLowerCase().includes(value.toLowerCase()),
        ),
      )
    } else {
      setSearch('')
      setActiveFilters(filters as ColumnFilterItem[])
    }
  }

  return (
    <>
      <div className="pb-2">
        <Input
          allowClear
          value={search}
          placeholder={`Search in filters`}
          onChange={e => onSearch(e.target.value)}
          className="!shadow-none !outline-none"
        />
      </div>

      <div className="h-[400px] overflow-auto flex flex-col gap-2">
        {activeFilters?.length > 0 && (
          <Checkbox
            checked={selectedKeys?.length === activeFilters?.length}
            onChange={e => {
              if (e.target.checked) {
                setSelectedKeys(activeFilters?.map(filter => filter.value) as Key[])
              } else {
                setSelectedKeys([])
              }
            }}
          >
            <span className="font-medium">Select All</span>
          </Checkbox>
        )}

        {activeFilters?.map((filter, index) => (
          <Checkbox
            key={index}
            onChange={e => {
              const nextSelectedKeys = e.target.checked
                ? [...(selectedKeys as string[]), filter.value]
                : (selectedKeys as string[])?.filter(f => f !== filter.value)

              setSelectedKeys(nextSelectedKeys as Key[])
            }}
            checked={(selectedKeys as string[])?.includes(filter.value as string)}
          >
            {filter.text}
          </Checkbox>
        ))}
      </div>
    </>
  )
}
`

and then you can use it like this on your columns: 

`
const { getColumnFilterProps } = useTableFilter<Record<string, any>>()

{
          key: 'name',
          title: 'Name',
          dataIndex: 'name',
          filters: Array.from(new Set(data.map(item => item.name))).map(text => ({ text, value: text })),
          ...getColumnFilterProps('name'), // Here is your column with desired data index.
 },
`
