### ISSUE TITLE
Modal.confirm方法中的onOk事件多次触发问题

### ISSUE THREAD

**Issue by xsjohn0306** [ant-design/ant-design#3727]
连续点击按钮会触发多次onOk事件,我这里需要做异步操作,会连续调用多次ajax,希望可以获取到button按钮手动禁用按钮或者组件这边做控制.

**Comment by afc163** [comment]
Modal.confirm 的 onOk 支持 Promise，会自动处理 Button loading 状态，你可以试试。

https://ant.design/components/modal/#Modal.xxx()

**Comment by xsjohn0306** [comment]
谢谢回复,不好意思,demo没看仔细~
