### ISSUE TITLE
联动删除时,autocomplete组件内部值未被重置

### ISSUE THREAD

**Issue by likelikeit** [ant-design/ant-design#37277]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/falling-forest-6c70i9?file=/src/App.js)

### Steps to reproduce

1.选择select，再选择autocomplete选项
2.重选select
3.通过联动删除 清空autocomplete的选项值
4.再次点击autocomplete，下拉选项中未能展示所有的可选项，仅在开启filterOptions选项下会出现

### What is expected?

联动删除时，恢复autocomplete状态

### What is actually happening?

联动删除，autocomplete有问题

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by LongHaoo** [comment]
@likelikeit 你好👋，有时间做吗？如果没有时间可以交给我hh

**Comment by LongHaoo** [comment]
https://github.com/react-component/select/blob/master/src/Select.tsx#L297 罪魁祸首找到了,空值的时候它不会保存

**Comment by LongHaoo** [comment]
@zombieJ 赔我睡眠
