### ISSUE TITLE
抽离自定义 Collapse.Panel 无法渲染出 content

### ISSUE THREAD

**Issue by xiaoYuanDun** [ant-design/ant-design#37282]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhe-die-mian-ban-antd-4-22-8-forked-oy6mdu?file=/demo.js)

### Steps to reproduce

查看 RP 地址中的 `CanNotRender` 组件表现即可

### What is expected?

何种方法可以正确渲染出 content，有些时候可能需要将业务逻辑收敛到子 Panel 中

### What is actually happening?

目前看 Panel 中的 childeren 无法 render 出来

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react 18.x |
| System | MAC  |
| Browser | chrome 104 |

**Comment by MadCcc** [comment]
https://codesandbox.io/s/zhe-die-mian-ban-antd-4-22-8-forked-ivvk49?file=/demo.js:404-409
你得把 props 透传给 Collapse.Panel

**Comment by xiaoYuanDun** [comment]
谢谢·

**Comment by xiaoYuanDun** [comment]
> https://codesandbox.io/s/zhe-die-mian-ban-antd-4-22-8-forked-ivvk49?file=/demo.js:404-409 你得把 props 透传给 Collapse.Panel

不过这里透传了之后，设置`defaultActiveKey` 好像也不会生效

**Comment by MadCcc** [comment]
`key="1"` 写在你的自定义组件上
