### ISSUE TITLE
Table, filters and tree data

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3728]
Is it possible to use table with tree data and use filter same time?!

**Comment by afc163** [comment]
We probably not support it now, what is the problem extactly?

**Comment by plandem** [comment]
need to filter by info that only children have.

**Comment by yesmeck** [comment]
@plandem Your can filter record by it's children's info. See http://codepen.io/yesmeck/pen/JbZQLa?editors=001

**Comment by plandem** [comment]
I already did. hoped it exists by default.
