### ISSUE TITLE
Cascader 组件多选模式下，无法设置多个默认值，只能设置一个默认值

### ISSUE THREAD

**Issue by kevin82008** [ant-design/ant-design#37288]
### Reproduction link

[https://ant.design/components/cascader-cn/#components-cascader-demo-default-value](https://ant.design/components/cascader-cn/#components-cascader-demo-default-value)

### Steps to reproduce

Cascader 组件的defaultValue里设置多个选项后，不会选中   
<Cascader defaultValue={['zhejiang', 'hangzhou', 'xihu','jiuxi']}    
options={[   
  {   
    value: 'zhejiang',   
    label: '浙江',   
    children: [   
      {   
        value: 'hangzhou',   
        label: '杭州',   
        children: [   
          {   
            value: 'xihu',   
            label: '西湖',   
          },  {   
            value: 'jiuxi',   
            label: '九溪',   
          },  {   
            value: 'qiantj',   
            label: '钱塘江',   
          },   
        ],   
      },   
    ],   
  },   
  {   
    value: 'jiangsu',   
    label: 'Jiangsu',   
    children: [   
      {   
        value: 'nanjing',   
        label: 'Nanjing',   
        children: [   
          {   
            value: 'zhonghuamen',   
            label: 'Zhong Hua Men',   
          },   
        ],   
      },   
    ],   
  },   
]}  />   

### What is expected?

支持以某种形式设置多选情况下的默认值

### What is actually happening?

没有选中（并显示）默认值

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome Version 104.0.5112.102 (Official Build) (64-bit) |

**Comment by kevin82008** [comment]
> ### You may look for issues:
> 1. 54% [Cascader 多选模式能否在次级节点中存在禁用项时，选中全部可选项后不自动回显为父节点 #36208](https://github.com/ant-design/ant-design/issues/36208)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

不一样的需求，是默认值，不是选中

**Comment by MadCcc** [comment]
https://codesandbox.io/s/mo-ren-zhi-antd-4-22-8-forked-6emobt?file=/demo.js
`defaultValue={['zhejiang', 'hangzhou', 'xihu'], ['zhejiang', 'hangzhou', 'jiuxi']}`
