### ISSUE TITLE
Modal open problem

### ISSUE THREAD

**Issue by SallyOne** [ant-design/ant-design#3729]
Modal 关闭打开后会带上一次的样式，比如搭配transfer,如果勾中了checkbox,那么Modal关闭后再打开checkbox还是勾中的。有什么办法解决这个问题？？？？

**Comment by benjycui** [comment]
重置 Modal 内组件的状态、属性。

**Comment by SallyOne** [comment]
transfer 里的checkbox全选怎么重置？文档里没有？

**Comment by benjycui** [comment]
Transfer 还是要增加 `selectedKeys` 受控属性。。

**Comment by yesmeck** [comment]
感觉这里还是自己把  model unmount 掉来处理好点吧？

**Comment by benjycui** [comment]
`Modal[visible]` 及其它组件的 `visible` 属性的设计就是为了重用，直接 unmount 有点违背初衷了。

**Comment by yowangbin** [comment]
antd is amazing,thanks

import React, { PureComponent, Component } from 'react';
import { Modal as AntModal } from 'antd';
import PropTypes from 'prop-types';

class Modal extends (PureComponent || Component) {
  constructor(props) {
    super(props);
    this.state = { renderChild: true };
  }

  componentWillReceiveProps(nextProps) {
    const { destroyInvisibleModal = false } = this.props;
    if (destroyInvisibleModal) {
      if (nextProps.visible)
        this.setState({ renderChild: true });
      else
        this.setState({ renderChild: false });
    }
  }

  render() {
    return (
      this.state.renderChild ? <AntModal {...this.props} /> : null
    );
  }
}

Modal.propTypes = {
  // destroy invisible Modal, default false
  destroyInvisibleModal: PropTypes.bool
};


export default Modal;
