### ISSUE TITLE
add props trigger:'onBlur' to form-item,it will not be able to enter anything after lose focus

### ISSUE THREAD

**Issue by CodeFly16** [ant-design/ant-design#37295]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fu-za-de-dong-tai-zeng-jian-biao-dan-xiang-antd-4-22-8-forked-57cbwq?file=/demo.js)

### Steps to reproduce

1. add Sights
2. enter anything to price-input
3. click submit
4. enter anything to price-input again,and then it will not able to enter anything

### What is expected?

whatever i operation,it will be enter anything to price-input
<img width="344" alt="image" src="https://user-images.githubusercontent.com/61872730/187333822-6b445dfb-e34b-4dfc-9a62-e530340f09ef.png">

### What is actually happening?

I can't enter anything again

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 16.14.0 |
| System | mac os monterey 12.2.1 |
| Browser | 104.0.5112.101 |

**Comment by MadCcc** [comment]
In Form every item is controlled. Setting `trigger` to `onBlur` means fields only change when blurred, so it's intended.
If you want to trigger validation when blurred, just use `validateTrigger` instead.

**Comment by CodeFly16** [comment]
> In Form every item is controlled. Setting `trigger` to `onBlur` means fields only change when blurred, so it's intended. If you want to trigger validation when blurred, just use `validateTrigger` instead.

I don't want to validate this item.

In my requirement, other Items are calculated by  this item. So, if use onChange rather than onBlur,it feel caton when I input anything

**Comment by mowangchuzhong** [comment]
I also have requirements.  any good solutions? thx
