### ISSUE TITLE
Notification close icon does not respect ConfigProvider.config

### ISSUE THREAD

**Issue by coolcorexix** [ant-design/ant-design#37294]
### Reproduction link

[https://github.com/coolcorexix/saleshood-playground/tree/antd-icon-reproduce](https://github.com/coolcorexix/saleshood-playground/tree/antd-icon-reproduce)

### Steps to reproduce

- Click on "Open static notification" Button

### What is expected?

The close icon of notification should be updated like the one in Modal

### What is actually happening?

It still uses the default ant-close icon 

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/25930830/187326023-8f6c23c4-d64f-475c-8af8-9e65fc422f8a.png">

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 18.2 |
| System | MacOs Monterey |
| Browser | Chrome |

**Comment by afc163** [comment]
Try https://ant.design/components/notification/#Why-I-can-not-access-context,-redux,-ConfigProvider-locale/prefixCls-in-notification

**Comment by coolcorexix** [comment]
@afc163 in my case I want to use static methods like 
```javascript
import { notification } from 'antd';

...
notification.success({
message: "Success",
})
```

not to attach some new Component to the DOM like the first FAQ. More like the second question, which I follow and did not work as expected
