### ISSUE TITLE
Table加载重复key的数据后再次加载正常数据后会遗留上次数据重复key部分数据

### ISSUE THREAD

**Issue by yijialee** [ant-design/ant-design#37307]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-22-8-forked-b5to4s)

### Steps to reproduce

加载有重复key的数据 显示正常 控制台报错
加载无重复可的数据 显示异常

### What is expected?

加载错误数据不影响下次加载正确数据

### What is actually happening?

再次加载正常数据后会遗留上次数据重复key部分数据

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Edge |

**Comment by MadCcc** [comment]
保证 `key` 唯一
