### ISSUE TITLE
tree 组件 checkable  与 multiple 

### ISSUE THREAD

**Issue by 879584395** [ant-design/ant-design#3730]
因为我用了checkable  有类似checked复选框的东西，我想让这个选框变成单选 ，而 multiple 只能使右侧文字只能选中一条 或多条，而不能控制 checkable  请问如何处理

**Comment by afc163** [comment]
文档有点混淆。

复选框支持单选的话，可以用 checkedKeys 进行精确控制。

**Comment by 879584395** [comment]
@afc163  能详细一点吗 文档有一点没看懂  checked 状态是如何取消的
