### ISSUE TITLE
tooltip popover 在macOS 10 下的Safari 13 样式错乱

### ISSUE THREAD

**Issue by lijiweigh** [ant-design/ant-design#37300]
### Reproduction link

[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce

直接看就能看到

### What is expected?

希望样式正常

### What is actually happening?

样式错乱，箭头错位

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 17.0.2 |
| System | Mac OS 10.14.6 |
| Browser | safari 13.0.1 |

![企业微信截图_a815bfc5-9c93-450f-8382-1fe86c2fb745](https://user-images.githubusercontent.com/23213046/187335872-cdf76c27-9063-4a07-a119-554b4d7b9735.png)

**Comment by MadCcc** [comment]
建议更新到新版本试试

**Comment by lijiweigh** [comment]
更新到最新版仍然不行，而且官网上的也是有问题的呀
