### ISSUE TITLE
RangePicker在panelRender中的Input无法获取焦点

### ISSUE THREAD

**Issue by ZhuHuaijun** [ant-design/ant-design#37316]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-4-22-8-forked-4re6fc?file=/demo.js)

### Steps to reproduce

RangePicker自定义panelRender中使用Input组件，点击Input组件，无法获取焦点，无法选择文字

### What is expected?

RangePicker自定义panelRender中使用Input组件，点击Input组件，能够获取焦点，能够选择文字

### What is actually happening?

RangePicker自定义panelRender中使用Input组件，点击Input组件，无法获取焦点，无法选择文字

| Environment | Info |
| --- | --- |
| antd | 4.20.2 |
| React | react ^17.0.2 |
| System | mac OS Big Sur 11.5.2 |
| Browser | Google Chrome 版本 104.0.5112.101（正式版本） (arm64) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31734#issuecomment-895684589
