### ISSUE TITLE
在自定义less文件中使用antd的样式名，在dark模式下正常，但是非dark模式下编译失败

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#37312]
### Reproduction link

[https://github.com/chj-damon/umi-max-theme-reproduce-demo](https://github.com/chj-damon/umi-max-theme-reproduce-demo)

### Steps to reproduce

npm start启动项目，项目正常启动
修改.umirc.ts里面antd下的dark为false，项目报错

### What is expected?

期望在非dark模式下，也能正常使用antd里面的样式名

### What is actually happening?

非dark模式下编译失败

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 17 |
| System | Macos 12.4 |
| Browser | chrome 104.0.5112.101 |

**Comment by afc163** [comment]
如果要在 less 使用 antd 的变量，需要引用一下主题文件。

配置了 `dark: true` 之后会默认引入 config.theme 全部变量，所以刚好可以用。

```
@import '~antd/es/style/themes/default.less';

.container {
  padding-top: 80px;
  background: @body-background;
}
```

**Comment by chj-damon** [comment]
那这样一来的话，如果项目很大的时候，每个less文件里面都要这么引入一下antd的less，岂不是特别麻烦？

我试了一下在umi项目的global.less里面加，好像没有效果。
有那种只需要引入一次就可以全局使用的办法吗？

**Comment by afc163** [comment]
在 global.less 里加一次应该就行。
