### ISSUE TITLE
sideEffects of antd@5.x

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#37313]
这个字段要改改了，可以改成 `sideEffects: false` https://github.com/ant-design/ant-design/blob/c8171b568068fd11bd2bbe3b2635bd892bfabdd3/package.json#L37-L41

另外 style/css.js 是否有必要保留（看上去可以对 babel-plugin-import 兼容，但是会增加很多 package size），内容看上去和 style/index.js 是一样的。

**Comment by MadCcc** [comment]
babel-plugin-import 不兼容了吧，后面 umi 插件里也会去掉
