### ISSUE TITLE
Select.OptGroup can't see last Element

### ISSUE THREAD

**Issue by mingyanghu** [ant-design/ant-design#37322]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-euler-269muf?file=/src/data.js:0-1068)

### Steps to reproduce

antd4.x https://codesandbox.io/s/quirky-euler-269muf?file=/src/data.js:0-1068

antd3.x https://codesandbox.io/s/currying-hooks-elcec4?file=/src/App.js

### What is expected?

antd4.x can scroll bottom normal

### What is actually happening?

can't see bottom element

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 17.0.1 |
| System | all |
| Browser | 104.0.5112.101 |

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/components/select-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-Option-%E6%A0%B7%E5%BC%8F%E5%AF%BC%E8%87%B4%E6%BB%9A%E5%8A%A8%E5%BC%82%E5%B8%B8%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F

**Comment by mingyanghu** [comment]
resolved，  thanks
