### ISSUE TITLE
Image.PreviewGroup 提供当前预览图片索引

### ISSUE THREAD

**Issue by Emily-0616** [ant-design/ant-design#37321]
### What problem does this feature solve?

目前有一个需求是展示大量图片并且图片能被选中，预览。图片选中会有选中态，但是预览时使用image 组件切换图片无法与页面的图片选中态作联动。

### What does the proposed API look like?

Image.PreviewGroup 方向键切换图片能获取当前图片索引。

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by Emily-0616** [comment]
previewType 增加  onChange 事件，onChange(current)，current 是当前预览模式下图片索引。 @afc163

**Comment by Emily-0616** [comment]
previewType 增加 onChange 事件，切换当前预览的图片会触发onChange(current)回调，current 能返回当前预览模式下当前图片索引。 @afc163

**Comment by Emily-0616** [comment]
> What does the proposed API look like?

previewType 增加 onChange 事件，切换当前预览的图片会触发onChange(current)回调，current 能返回当前预览模式下当前图片索引。

**Comment by yanghuanrong** [comment]
Is there a follow-up to the image indexing function?
