### ISSUE TITLE
Checkbox.Group内部嵌入select组件，当select组件disabled之后，点击select组件还能触发checkbox的更新

### ISSUE THREAD

**Issue by tinyzh** [ant-design/ant-design#37323]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/little-framework-33e7l9?file=/index.js)

### Steps to reproduce

点击置灰的select

### What is expected?

点击置灰的select时，checkbox不应该触发更新

### What is actually happening?

置灰的select能触发checkbox更新

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | react18 |
| System | windows |
| Browser | chrome最新版本 |

**Comment by afc163** [comment]
https://codesandbox.io/s/musing-sunset-zkkdge?file=/index.js
