### ISSUE TITLE
The style of Select's dropdown will crash when there are more than 10 options.

### ISSUE THREAD

**Issue by hydRAnger** [ant-design/ant-design#37330]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-8-forked-o9hrpe?file=/demo.js)

### Steps to reproduce

just check the first Select (with 10 options), the dropdown works as expected.
then check the second Select(with more than 10 options), the dropdown's width will crash.

### What is expected?

Select with any count of options, should behave the same in UI style.

### What is actually happening?

For Select with more than 10 options, the dropdown style defined by dropdownClassName will crash.

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 17.0.2 |
| System | MacBookPro18,3 macOS Monterey |
| Browser | Chrome: Version 104.0.5112.101 (Official Build) (arm64) |

**Comment by afc163** [comment]
`dropdownMatchSelectWidth={false}`: https://ant.design/components/select/#Select-props

**Comment by hydRAnger** [comment]
> dropdownMatchSelectWidth

thanks, that works.

BTW, another wired thing is: as dropdownMatchSelectWidth is ```default true```, for [this reproduce demo](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-22-8-forked-o9hrpe?file=/demo.js), why the Select with less than 10 options didn't require ```dropdownMatchSelectWidth={false}```, looks inconsistent.

**Comment by hydRAnger** [comment]
> `dropdownMatchSelectWidth={false}`: https://ant.design/components/select/#Select-props

so maybe we should mention it in the document? even in the FAQ section?

**Comment by afc163** [comment]
PR is welcome
