### ISSUE TITLE
Select.Option 自定义 element id

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#3733]
#### 发生问题的环境是：

- antd 版本: 1.10.0
- 操作系统及其版本: macOS Sierra
- 浏览器及其版本: Chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

e2e 测试需要模拟点击 `<Select>` 中的某个选项，但是我们没有办法给 `<Select>` 渲染出来的选项元素定位

#### 您期待的结果是:

提供一个 props 能设定 `Select.Option` 渲染成 DOM 后的 element id

**Comment by benjycui** [comment]
要不直接把 `Select.Option` 上所有的属性都拷贝到最终渲染出来的那个元素上面。

ref: https://github.com/ant-design/ant-design/issues/3063

**Comment by afc163** [comment]
`<Option><div id="xxx"></div></Option>

**Comment by djyde** [comment]
但是问题是，即使我已经给 `<Option>` 内的 element wrap 了一层 div, 但也要先通过点击最外层的 `<Select>` 才能点击这个 div. 而 `<Select>` 又不能自定义 id

**Comment by afc163** [comment]
所以你现在需要的是 `<Select id="xx" />`？

**Comment by djyde** [comment]
对的

**Comment by yesmeck** [comment]
你们用什么来做 e2e 测试的？

**Comment by djyde** [comment]
nightmare

**Comment by magicdawn** [comment]
同, Select 加了一堆属性, 都没有体现在 DOM 中

需求是需要在一些表单联动场景中, 判断这个 Select 在不在 DOM 中, 然后对其 validate ...
好像没法做...

没看到 antd Form 是如何做的, getFieldProps 是有返回 id 的...

**Comment by benjycui** [comment]
> 需求是需要在一些表单联动场景中, 判断这个 Select 在不在 DOM 中

这个是由业务代码决定的，你怎么会不知道？

**Comment by magicdawn** [comment]
@benjycui 这样不就是写死了么.... 还一堆逻辑... 要是有 id 在, 通过 document.getElementById(id) / window[id] 判断存不存在, 不存在跳过 validate 才是活的...

现在 Input 类的都是有 id, Select 没有, 不知道你们咋考虑的...

**Comment by yesmeck** [comment]
> 判断这个 Select 在不在 DOM 中

你应该去判断 state 里有没有这个 option，thinking in react.

**Comment by magicdawn** [comment]
BTW

> thinking in react.

有这本书么... 😂

**Comment by yesmeck** [comment]
https://facebook.github.io/react/docs/thinking-in-react.html

**Comment by magicdawn** [comment]
......

**Comment by magicdawn** [comment]
> >判断这个 Select 在不在 DOM 中

> 你应该去判断 state 里的值，thinking in react.

经过一番实践, 将 `condition && <Select></Select>` 抽成 `exists(id) && <Select />`
我想说, 可行是可行, 没拿 id 查来的直观和方便, 多了好多代码...

**Comment by magicdawn** [comment]
还是求一个不依赖 React 判断一个组件, 如 `Select` / `Input` / `InputNumber` etc 是否进行了输出的 feature
