### ISSUE TITLE
Cascader onClick event will never triggered in dropdownRender , after add onBlur

### ISSUE THREAD

**Issue by amyhuangxbd** [ant-design/ant-design#37339]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/red-paper-ppry0l?file=/index.js:2245-2259)

### Steps to reproduce

1，Cascader 添加dropdownRender，同时添加onBlur, 
2，dropdownRender 里的button添加onClick事件
3，button onClick事件不会执行到，但是确执行了onBlur

### What is expected?

当Cascader 添加dropdownRender，同时添加onBlur时，dropdownRender里的元素点击时不要触发onBlur

### What is actually happening?

当Cascader 添加dropdownRender，同时添加onBlur时，dropdownRender里的元素点击时触发onBlur，同时元素的click事件没有执行。

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | ^16.12.0 |
| System | mac |
| Browser | chrome |

**Comment by kiner-tang** [comment]
看你在`onBlur`中有设置了隐藏，应该是先触发了失去焦点事件导致组件隐藏了

**Comment by zombieJ** [comment]
`stopPropagation` 阻止 `dropdownRender` 点击导致焦点丢失。
