### ISSUE TITLE
期望Radio支持附带的参数

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design#37338]
### What problem does this feature solve?

我目前遇到的问题是 一组Radio 选择的值会被多个接口用到 但是 Radio组件却只支持label 和value这两个值

### What does the proposed API look like?

```
arr.map(r => ({ label: r.value, value: r.key,value1:r.id,value2:r.ids, }));
```
我后面传入多少参数 希望都能在选中的onChange中拿到

**Comment by afc163** [comment]
不属于 Radio 职责范围，建议自行 map。

**Comment by eiinu** [comment]
有类似的需求，一个 RadioGroup，内部是数组生成的多个 Radio。
我想在 RadioGroup 的 onChange 参数中获取到对应 Radio 上除了 value 以外的其他数据，简直比登天还难😅
