### ISSUE TITLE
我在ts中使用antd-Table-onChange希望优化

### ISSUE THREAD

**Issue by particlec** [ant-design/ant-design#37345]
### What problem does this feature solve?

我在使用antd-Table-onChange中，antd-Table-onChange的入参类型有四个分别为：
( pagination: TablePaginationConfig, filters: Record<string, FilterValue | null>, sorter: SorterResult<RecordType> | SorterResult<RecordType>[], extra: TableCurrentDataSource<RecordType>)

当我使用sorter时，不得不写前两个入参，由于写的时ts，我要写成
function XXX(
    pagination: TablePaginationConfig,
    filters: Record<string, FilterValue | null>,
    sorter: SorterResult<DatabaseType> | SorterResult<DatabaseType>[]
  ) {....}

但是我只用到了sorter啊，我并不想写pagination、filters

### What does the proposed API look like?

我期望把antd-Table-onChange的入参改成对象，包含这四个属性

**Comment by afc163** [comment]
```jsx
onChange(_, _, sorter) {}
```
