### ISSUE TITLE
Table column with not working if some cell is too wide

### ISSUE THREAD

**Issue by sspku-yqLiu** [ant-design/ant-design#37347]
### Reproduction link

[https://codepen.io/yorkyorkliu/pen/eYrOLaV?editors=0010](https://codepen.io/yorkyorkliu/pen/eYrOLaV?editors=0010)

### Steps to reproduce

open it,
see width in name, its 80 px

### What is expected?

it should be 150px

### What is actually happening?

80px

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 17 |
| System | macos |
| Browser | chrome latest |

**Comment by afc163** [comment]
```
      x:'max-content'
```
