### ISSUE TITLE
Table virtual scrolling supports tree data

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#37342]
### What problem does this feature solve?

I have a table with 100 columns, each row has 100 rows of sub-data, each time the expansion is stuck, I want to use virtual list to handle it

The official web demo does not support tree data  
https://codesandbox.io/s/xu-ni-lie-biao-antd-4-22-8-forked-2vrjmx?file=/demo.js

**Comment by afc163** [comment]
Duplicate of #20339
