### ISSUE TITLE
Select增加multiple以后提示错误

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design#3734]
- antd 版本: 2.2.1
- 操作系统及其版本: Linux
- 浏览器及其版本: Chrome 54.0.2840.87 m

下面代码Select增加multiple以后提示错误

Uncaught (in promise) Error: must set key for <rc-animate> children(…)

      const {Select, Form, Col, Input} = antd;
      const Option = Select.Option;
  
      const children = [];
      for (let i = 10; i < 36; i++) {
        children.push(<Option key={i.toString(36) + i}>{i.toString(36) + i}</Option>);
      }
  
      function renderSearchFormFields(getFieldDecorator, fields) {
        return fields.map((field, index)=> {
          const {label, name, render, placeholder, ...other} = field;
          let config = Object.assign({}, other);
          let comp = render ? render() : <Input placeholder={placeholder}/>;
          return (
            <Form.Item label={label}
                       labelCol={{ span: 8 }}
                       wrapperCol={{ span: 16 }}
                       key={index}
            >
              {getFieldDecorator(name, config)(comp)}
            </Form.Item>
  
          );
        });
      }
  
      const fields = [{
        label: '123',
        name: 'tradeTypes',
        initialValue: '',
        render: () => (
          <Select multiple>
            {children}
          </Select>
        )
      }];
  
      let App = React.createClass({
        render() {
          const {getFieldDecorator} = this.props.form;
          return (
            <div style={{margin: 10}}>
              {renderSearchFormFields(getFieldDecorator,fields)}
            </div>
          );
        }
      });
      App = Form.create()(App);
      ReactDOM.render(<App />, document.getElementById('container'));

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Sean-Snow** [comment]
@benjycui  我上面的代码直接复制进去就好了

**Comment by afc163** [comment]
能重现问题再 reopen 吧。。

**Comment by Sean-Snow** [comment]
@afc163  不能重现？把代码复制到 codepen里面就可以直接运行，去掉multiple 以后就正常，加上multiple以后就出错了

**Comment by afc163** [comment]
你 Fork 一份 codepen 吧，为什么不能多帮助我们一点呢。。。。

**Comment by afc163** [comment]
另外，把 `key={index}` 改成 `key={index.toString()}`，key 必须是 string 类型。

https://facebook.github.io/react/docs/lists-and-keys.html

**Comment by Sean-Snow** [comment]
@afc163 http://codepen.io/Sean-Snow/pen/LbVOxJ?editors=1010 这是代码，key 改为string以后还是不行

**Comment by xyunsh** [comment]
同样的问题

**Comment by benjycui** [comment]
重现步骤？

**Comment by afc163** [comment]
好奇怪的问题，单独使用 `Select[multiple]` 不会报错，@Sean-Snow 的例子里嵌套了一层就报错了。

**Comment by afc163** [comment]
知道了。

```diff
- initialValue: '',
+ initialValue: [],
```

`Select[multiple]` 的 value 类型是 Array 。@Sean-Snow

**Comment by Sean-Snow** [comment]
@afc163  非常感谢，解决了

**Comment by jiangxtx** [comment]
@afc163 的确是这个原因，我也解决了，多谢！！
```
- initialValue: '',
+ initialValue: [],
```
