### ISSUE TITLE
Mentions support duplicated values as options

### ISSUE THREAD

**Issue by danielaahlin** [ant-design/ant-design#37350]
### What problem does this feature solve?

When there is a list of options that has the same names, Mentions interpret multiple values as the same - when it isn't. This produces problem when there are 2 database tables with the same column that should both be mentioned. 

E.g. we use Mentions as a component to create arithmetic expressions with attributes from our database. In the database, a few tables can have the same column name (like Area or Measured time). In this case we want to have the value as the id of the row and the column name as a title. 

### What does the proposed API look like?

Could work the same as Options does in Select, where title is a prop.

**Comment by MadCcc** [comment]
If values are the same, how do users know which to choose?

**Comment by danielaahlin** [comment]
> If values are the same, how do users know which to choose?

Because there is a possibility to add labels to the options, we can show the user the origin table of where the attribute comes from. E.g. _Area - Building_ and _Area - Real estate_

**Comment by MadCcc** [comment]
Did you mean options with same title and different values? 
Currently it is supported, by providing `children` with title and `value` with id.
But it may be not a good idea because users need to differ which to choose from title.

**Comment by ruslanashaari** [comment]
Hi @danielaahlin Do you able to do it or found any workaround?

**Comment by danielaahlin** [comment]
Unfortunately no workaround yet. But I haven't worked much more on it because we haven't really got that issue from any of our users yet. As soon as we run into this problem I'll update here! 😄

**Comment by MrFarhan** [comment]
> Did you mean options with same title and different values? Currently it is supported, by providing `children` with title and `value` with id. But it may be not a good idea because users need to differ which to choose from title.

@MadCcc can you please provide the sample code of children which you mentioned.
