### ISSUE TITLE
DatePicker field is flickering after form.resetFields()

### ISSUE THREAD

**Issue by Khavrolev** [ant-design/ant-design#37352]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/late-glitter-t6zuqe?file=/src/App.tsx)

### Steps to reproduce

1) Create simple form with initialValues;
2) Add DatePicker;
3) Add button with form.resetFields() function;
4) Click that button multiple times

### What is expected?

DatePicker field doesn't flicker

### What is actually happening?

DatePicker field is flickering

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 18 |
| System | macOS Monterey 12.4 |
| Browser | Version 104.0.5112.101 (Official Build) (x86_64) |

**Comment by Khavrolev** [comment]
https://user-images.githubusercontent.com/43345369/187998242-2461d3b5-04d6-425a-9645-395c630029f2.mov

**Comment by Khavrolev** [comment]
As I understand it, you are not going to fix it? It's not insult, I just want to know :-)

**Comment by Khavrolev** [comment]
Guys, is it ok, that your lib is one of the best and you don't want to fix bugs? :-)

**Comment by zombieJ** [comment]
Sorry for delay.
Close since not an issue in latest version.
