### ISSUE TITLE
tooltip popover 在macOS 10 下的Safari 13 样式错乱，升级到最新版本仍然有问题

### ISSUE THREAD

**Issue by lijiweigh** [ant-design/ant-design#37353]
### Reproduction link

[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce

打开官网的链接，就能看到

### What is expected?

希望样式正常

### What is actually happening?

样式错乱，箭头错位

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 17.0.2 |
| System | Mac OS 10.14.6 |
| Browser | safari 13.0.1 |

https://user-images.githubusercontent.com/23213046/187335872-cdf76c27-9063-4a07-a119-554b4d7b9735.png
![企业微信截图_25e11598-0bb8-4286-a292-45891f6bd773](https://user-images.githubusercontent.com/23213046/188046125-682443ab-042b-4413-a2e2-6d80ca6ad57c.png)

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/188373720-267940c9-de00-469e-9587-2c9e15205ec2.png)
最新版是 14.x，可以更新么

**Comment by lijiweigh** [comment]
<img width="294" alt="截屏2022-09-06 上午11 19 04" src="https://user-images.githubusercontent.com/23213046/188541176-23714649-c908-45a7-84e7-f21937796e7d.png">
<img width="966" alt="截屏2022-09-06 上午11 29 09" src="https://user-images.githubusercontent.com/23213046/188541193-ea417c97-1e91-4e35-ba7e-f78a3565a0f2.png">

另一台电脑是14.0.3，仍然有问题

**Comment by MadCcc** [comment]
推荐更新到 14.1 及以上版本
