### ISSUE TITLE
<Menu> is unusable due to TypeScript error.

### ISSUE THREAD

**Issue by jeremypeters** [ant-design/ant-design#37351]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-typescript-forked-kbg4pl?file=/demo.tsx)

### Steps to reproduce

Look at the Sandbox example provided - it's using the demo code from https://ant.design/components/menu/ 

### What is expected?

No Typescript error

### What is actually happening?

Getting a TypeScript error - see red squiggly under `items` in Sandbox example.

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 17.0.2 |
| System | MacOS 11.6 |
| Browser | FF 103.0.2 |

**Comment by afc163** [comment]
Please upgrade antd to latest version.

**Comment by jeremypeters** [comment]
@afc163 4.22.8 is the latest version. Unless I'm missing something.
