### ISSUE TITLE
Layout组件 .has-sider 初始化后再添加导致 UI 闪烁等问题

### ISSUE THREAD

**Issue by zjfresh** [ant-design/ant-design#37367]
### Reproduction link

[https://8bhmrc.csb.app/](https://8bhmrc.csb.app/)

### Steps to reproduce

页面初始化加载时
![WX20220902-164413](https://user-images.githubusercontent.com/28496323/188101066-023e5b2d-002e-43c1-9213-d26b309a6e7d.png)

![antd-layout-css-bug2](https://user-images.githubusercontent.com/28496323/188099990-a43a7656-99da-406b-906b-b50a9e14859a.png)

### What is expected?

初始化 Laytou 时不会因为缺少 .has-sider 导致 content 区域错位闪烁以及宽度不对（导致 echarts 初始宽度错误）

### What is actually happening?

缺少 .has-sider 导致 content 区域错位闪烁以及宽度不对（导致 echarts 初始宽度错误）

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 18.2.0 |
| System | Mac OS |
| Browser | Microsoft Edge Version 104.0.1293.70 (Official build) (x86_64) |

**Comment by afc163** [comment]
对，这也是为什么会需要一个 `hasSider` 属性：https://ant.design/components/layout-cn/#Layout
