### ISSUE TITLE
Unable to open simple menu with testing-library

### ISSUE THREAD

**Issue by rgosse** [ant-design/ant-design#37376]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/menu-not-testable-if-items-length-1-0z4sno?file=/src/index.tsx)

### Steps to reproduce

Open the codesandbox link, a test function renders a simple `<Menu />` and tries to click on it using the react testing library but fails to find the menu item after clicking on the sub menu.

### What is expected?

I should be able to trigger a click on "Menu Item 1" using the react testing library.

This works if commenting the first item in `App.tsx`.

![image](https://user-images.githubusercontent.com/2352621/188186800-5918d5a0-7e18-4fc9-bb9f-c32a05f8945c.png)

### What is actually happening?

The tests fails to find the menu item after clicking on the menu

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by bdwade100** [comment]
I had a similar issue with the `<Menu />` element.

@rgosse , I noticed that you are using a mode of `"horizontal"`. I am, too. I changed my test to use a mode of `"vertical"` to solve this problem. I still use a mode of `"horizontal"` for my production code, though.

**Comment by antoinetissier** [comment]
@zombieJ it still does not work when dynamically controlling the `openKeys` through `onOpenChange`: https://codesandbox.io/s/menu-not-testable-if-items-length-1-forked-f5zdfh

**Comment by AlexeyTeterin** [comment]
> Config `openKeys` or mock hover to open: https://codesandbox.io/s/menu-not-testable-if-items-length-1-forked-b0omdq?file=/src/App.tsx

Not working in tests (Jest + RTL) - cannot detect the drop-down menu element.
