### ISSUE TITLE
建议改善：Select的value值支持string、number、boolen等类型

### ISSUE THREAD

**Issue by lanll** [ant-design/ant-design#3737]
`<Select.Option value="0">汽运</Select.Option>`
`<Select.Option value={0}>汽运</Select.Option>`

之前是支持多类型的，现在只支持String，导致后台传过来的数据需要做转换，不然会有警告：
`Warning: Failed propType: Invalid prop `value` of type `number` supplied to `Option`, expected `string`.`

**Comment by yesmeck** [comment]
重复 #2857

**Comment by Clish** [comment]
确实建议支持不同类型的值, 在表单提交要转换成目标格式,在显示的时候要重新转换成字符串
