### ISSUE TITLE
table表头下拉搜索，当列表左右滑动，这个下拉框错位

### ISSUE THREAD

**Issue by Hallelujah1** [ant-design/ant-design#37399]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/usrkuf?file=/demo.js)

### Steps to reproduce

https://codesandbox.io/s/usrkuf?file=/demo.js

### What is expected?

下拉搜索框，当table左右滑动时候，跟着表头的td滑动

### What is actually happening?

下拉搜索框，当table左右滑动时候，静止不动

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | react |
| System | mac os 10.15.4 |
| Browser | chrome 104.0.5112.101 |

**Comment by zombieJ** [comment]
如果确定 overflow 空间足够，可以设置 `getPopupContainer` 来处理： 

https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F
