### ISSUE TITLE
Select组件能获取到焦点吗

### ISSUE THREAD

**Issue by 1120340041** [ant-design/ant-design#3739]
，Input输入框跟Select组件混合使用的时候，Input组件可以使用回车实现焦点换行，但是到Select这里就切换不过去了，想问下怎么样才能input按下回车的时候焦点可以跳到Select上

**Comment by yesmeck** [comment]
不带搜索框的 Select 现在不支持 focus。应该可以通过  tabindex 来搞定，欢迎 PR。

**Comment by 1120340041** [comment]
tab键focus我知道，但是我们需要的是回车键，但是tab键这个应该是系统自带的吧

**Comment by yesmeck** [comment]
> 但是tab键这个应该是系统自带的吧

Select 是加了 tabindex 才有的，不懂你说的回车换焦点，回车并不能换焦点呀（不，Input 也不行）？

**Comment by 1120340041** [comment]
就是我现在已经实现的是Input组件我已经可以用键盘上下左右键或回车键来实现input之间的跳转了，也就是一个input的焦点可以通过回车键跳转到另一个input焦点上，但是碰到Select组件时焦点就落不到上面去了，比方说有一行内容包含有input组件和Select组件，然后我前面的input一直在用回车键实现切换跳转，但是到select这里就不得不再去动用鼠标来操作了

**Comment by yesmeck** [comment]
是这个意思吗？http://codepen.io/yesmeck/pen/vyEgGq?editors=001

**Comment by benjycui** [comment]
或者需要梳理一下输入空间的 `.focus` 方法 https://facebook.github.io/draft-js/docs/advanced-topics-managing-focus.html

**Comment by 1120340041** [comment]
谢谢各位的解答，Select组件焦点获取我用jquery直接去操作楼上说的class ant-select-selection是可以了的，但是Input和Select一起混合用时用键盘来控制随意切换焦点好像不怎么好实现

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/3790

**Comment by wangao029** [comment]
解决了吗？antd 内部是否有更优雅点的接口？

**Comment by acivang** [comment]
Select 没有 focus 方法吧？设置焦点只能通过findDOMNode(ref.Select).focus(); 请求是不支持ref.Select.focus()么？看过了 #3790 ，也测试了ref.Select.focus()，提示focus不是有效的函数

**Comment by helloli** [comment]
设置了 Select 的 ref 之后 this.refselect.blur() 根本就不生效啊，antd 最新版本
