### ISSUE TITLE
The button still use the style for hover after mouseup

### ISSUE THREAD

**Issue by PinkChampagne17** [ant-design/ant-design#37404]
### Reproduction link

[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce

Just click.

### What is expected?

The style of the button changes back after mouseup.

### What is actually happening?

The button still uses the style for hover.

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 18.2.0 |
| System | macOS Monterey 12.5.1 |
| Browser | Chrome 104.0.5112.101 (Official Build) (x86_64) |

**Comment by zombieJ** [comment]
Hover & Active style is similar. We will adjust it in next major version.
