### ISSUE TITLE
[New Component] Float Button

### ISSUE THREAD

**Issue by MadCcc** [ant-design/ant-design#37407]
RFC: https://github.com/ant-design/ant-design/discussions/37406

@li-jia-nan

**Comment by li-jia-nan** [comment]
received

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/12738

**Comment by MadCcc** [comment]
> Duplicate of #12738

旧的先关了吧，信息比较杂，在这里跟踪就好。

**Comment by li-jia-nan** [comment]
- #37520

**Comment by li-jia-nan** [comment]
@MadCcc close

**Comment by afc163** [comment]
撒花

**Comment by li-jia-nan** [comment]
> 撒花

中间改了很多次，给大佬们拖后腿了 ORZ

**Comment by afc163** [comment]
不不不，后面肯定还有很多要改，需要一起长期维护下去。
