### ISSUE TITLE
Incorrect type for InputNumber's onChange

### ISSUE THREAD

**Issue by pobch** [ant-design/ant-design#37412]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-danilo-tk9lum?file=/src/App.tsx)

### Steps to reproduce

1. Use `InputNumber` component
2. Inspect the parameter type of `onChange`

### What is expected?

The parameter type of `onChange` should be `string | number | null`. 

### What is actually happening?

The parameter type is `ValueType`, which is `string | number`. It's missing `null` from the parameter type.

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | react v18.2.0 |
| System | MacOS |
| Browser | - |

**Comment by li-jia-nan** [comment]
感觉这里不改也可以，实际上 `null` 类型就是 `number` 类型的子集，也是 `string` 类型的子集

![WX20220906-141701@2x](https://user-images.githubusercontent.com/49217418/188560728-98eca3d4-7ef3-4479-9afa-53a35895271c.png)
![WX20220906-141724@2x](https://user-images.githubusercontent.com/49217418/188560742-dfa3c3e1-3d08-41d0-99b4-40baff5a5ed3.png)

**Comment by li-jia-nan** [comment]
@zombieJ [https://github.com/react-component/input-number/pull/470](https://github.com/react-component/input-number/pull/470)

**Comment by Seasle** [comment]
There is a problem when building a project using Ant Design react-component/input-number#471.
