### ISSUE TITLE
DatePicker组件在英文系统上日期显示乱码

### ISSUE THREAD

**Issue by RichDaddyCashMany** [ant-design/ant-design#37416]
### Reproduction link

[https://ant.design/components/date-picker-cn/#header](https://ant.design/components/date-picker-cn/#header)

### Steps to reproduce

首先mac设置成英文语言，然后打开ant-design官方文档，然后chrome右键翻译成英文，再去点击打开日期选择器，就能看到问题了

### What is expected?

上面的部分数字日期应该不被翻译成英文日期

### What is actually happening?

上面的部分数字日期被翻译成了英文日期

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 16 |
| System | OSX 12.5 |
| Browser | Chrome 104.0.5112.101 (Official Build) (x86_64) |

**Comment by RichDaddyCashMany** [comment]
![Screen Shot 2022-09-06 at 10 03 07](https://user-images.githubusercontent.com/11496776/188532531-09340c33-47d4-4a6e-990c-a279f704fc9a.png)

**Comment by zombieJ** [comment]
Duplicate of #33360

**Comment by De-lovely-cute** [comment]
![image](https://github.com/ant-design/ant-design/assets/46861794/405b9d94-8b13-42b4-99c0-886457d25425)
谷歌浏览器是 version 114.0.5735
语言 英文english (United States)

**Comment by De-lovely-cute** [comment]
DatePicker组件选择日期的时候同时出现英文和数字
