### ISSUE TITLE
Table组件设置纵向滚动之后会将原来根据每列内容分配列宽的布局改成每列等宽的布局

### ISSUE THREAD

**Issue by newlife201702** [ant-design/ant-design#37411]
### Reproduction link

[https://riddle.alibaba-inc.com/riddles/c1a653f7](https://riddle.alibaba-inc.com/riddles/c1a653f7)

### Steps to reproduce

Table组件增加scroll={{y : 300}}

### What is expected?

able组件设置纵向滚动之后不改变列宽，只是增加可纵向滚动的功能

### What is actually happening?

Table组件设置纵向滚动之后会将原来根据每列内容分配列宽的布局改成每列等宽的布局

| Environment | Info |
| --- | --- |
| antd | 4.22.6 |
| React | 16.14.31 |
| System | Windows |
| Browser | chrome 103.0.5060.134 |

**Comment by afc163** [comment]
这是预期的，table-layout 改成 fixed 的了，否则默认情况下列头和列内容难以对齐。
