### ISSUE TITLE
组件 modal 在 360 安全浏览器打不开

### ISSUE THREAD

**Issue by ixugo** [ant-design/ant-design#37428]
### Reproduction link

[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce

1.使用 360 安全浏览器打开 antd 官网 https://ant.design/components/modal-cn/
2.随便点个 modal 相关的按钮

### What is expected?

期望能够显示出 modal

### What is actually happening?

 什么也没发生，modal 没有弹出来

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 按钮生效，modal 没有出来 |
| System |  windows |
| Browser | 360 安全浏览器 |

---
切换主题到黑暗模式下，可以看到 modal

**Comment by ixugo** [comment]
发现相同问题 #35270，关闭这个

**Comment by ixugo** [comment]
更新问题:
为什么 切换到 「黑暗主题」可以看到弹窗? 默认主题没有弹窗?

**Comment by afc163** [comment]
建议按模板提新的问题，并协助提供重现

**Comment by magiclixin** [comment]
我也遇到这个问题了，360浏览器和搜狗浏览器都有这个问题，看来还是css压缩打包的问题，低级别的浏览器不支持相关格式

**Comment by ixugo** [comment]
> 我也遇到这个问题了，360浏览器和搜狗浏览器都有这个问题，看来还是css压缩打包的问题，低级别的浏览器不支持相关格式，看来相关问题还是没有解决，而且暗黑模式下这个问题就没有

嗯嗯，你说得对!
在 config.ts 中设置 
```ts
  jsMinifier: 'terser',
  cssMinifier: 'cssnano',
```
即可

**Comment by mkRui** [comment]
@ixugo 你这个是用的 umi 吗？
