### ISSUE TITLE
React.createElement for @ant-design/icons

### ISSUE THREAD

**Issue by long76** [ant-design/ant-design#37427]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mdsz5y?file=/index.js)

### Steps to reproduce

add icon prop to React.createElement(Button)

### What is expected?

rendered button with icon

### What is actually happening?

got error:
```console
Objects are not valid as a React child (found: object with keys {$$typeof, render}). If you meant to render a collection of children, use an array instead.
```

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 18.2.0 |
| System | Kubuntu 20.04 |
| Browser | Google Chrome 105.0.5195.102 |

---
if set `icon: icons.DownloadOutlined.render()` all works 

Code:
```js
import React from "react";
import { createRoot } from "react-dom/client";
import * as antd from "antd";
import * as icons from "@ant-design/icons";
import "antd/dist/antd.css";
import "./index.css";

const ButtonWithIcon = React.createElement(
  antd.Button,
  { type: "primary", icon: icons.DownloadOutlined },
  "Test"
);

const App = () => {
  return (
    <div className="App">
      <h1>antd version: {antd.version}</h1>
      {ButtonWithIcon}
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);
```

**Comment by afc163** [comment]
```diff
-   { type: "primary", icon: icons.DownloadOutlined },
+  { type: "primary", icon: <icons.DownloadOutlined /> },
```

**Comment by long76** [comment]
> ```diff
> -  { type: "primary", icon: icons.DownloadOutlined },
> +  { type: "primary", icon: <icons.DownloadOutlined /> },
> ```
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-6eg0kx?file=/index.js

![image](https://user-images.githubusercontent.com/18124433/188623824-fd376c04-8ee8-4830-b8a1-300fb6e69727.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-6eg0kx?file=/index.js

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-6eg0kx?file=/index.js

**Comment by long76** [comment]
thanks!
