### ISSUE TITLE
360浏览器无法正常显示modal组件

### ISSUE THREAD

**Issue by jounzhang** [ant-design/ant-design#37437]
### Reproduction link

[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce

360浏览器打开
https://ant.design/components/modal-cn/

### What is expected?

正常打开modal框

### What is actually happening?

没反应

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | * |
| System | win11 |
| Browser | 360 |

---
谷歌浏览器正常

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/35270#issuecomment-1110749073
