### ISSUE TITLE
切换pageSize报Warning: [antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#37430]
### Reproduction link

直接用官网远程加载的例子打开codesandbox

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yuan-cheng-jia-zai-shu-ju-antd-4-23-0-forked-9kf217)

### Steps to reproduce

表格加载后点击pageSize 切换到20条/页后出现警告

![image](https://user-images.githubusercontent.com/22299421/188629358-71af2821-31b5-4548-8e47-e6df3cb89aec.png)

### What is expected?

不出现警告

### What is actually happening?

出现警告

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/yuan-cheng-jia-zai-shu-ju-antd-4-23-0-forked-jyd4lp?file=/demo.js

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/37431
