### ISSUE TITLE
Alert组件，期望info背景色边框根据primary主色来跟随！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design#37445]
### What problem does this feature solve?

如果配了色后，还是蓝色的，在整个系统里很突兀。希望info跟随主色走！

### What does the proposed API look like?

无api.直接跟随主色就行了！

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/12706830/188839918-94319c1f-d40b-4f6e-ac51-8638d014d880.png">
自己增加一个类去修改感觉也不是很方便！

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L24-L27
```ts
theme: {
  'info-color': 'red',
},
```

**Comment by afc163** [comment]
info 色脱离 primary 是刻意的，如果 primary 是黄色或绿色，alert info 就会有误解。
