### ISSUE TITLE
在select中使用rangePicker，日期没选完select就关闭了

### ISSUE THREAD

**Issue by SingleShadow** [ant-design/ant-design#37446]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-23-0-forked-0ulmog)

### Steps to reproduce

<Select
      style={{
        width: 300
      }}
      placeholder="custom dropdown render"
      dropdownRender={(menu) => (
        <>
          {menu}
          <Divider
            style={{
              margin: "8px 0"
            }}
          />
          <Space
            style={{
              padding: "0 8px 4px"
            }}
          >
            <RangePicker />
          </Space>
        </>
      )}
    >
      {items.map((item) => (
        <Option key={item}>{item}</Option>
      ))}
    </Select>

### What is expected?

期望可以选择完日期

### What is actually happening?

日期没选完select就关闭了

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | react |
| System | macos10.13.6 |
| Browser | chrome104.0.5112.79 |

**Comment by zombieJ** [comment]
https://ant.design/components/select-cn/#%E7%82%B9%E5%87%BB-dropdownRender-%E9%87%8C%E7%9A%84%E5%85%83%E7%B4%A0%EF%BC%8C%E4%B8%8B%E6%8B%89%E8%8F%9C%E5%8D%95%E4%B8%8D%E4%BC%9A%E8%87%AA%E5%8A%A8%E6%B6%88%E5%A4%B1%EF%BC%9F

**Comment by SingleShadow** [comment]
@zombieJ 使用受控模式也不好使，https://codesandbox.io/s/ji-ben-shi-yong-antd-4-21-7-forked-oq1d8j

**Comment by zombieJ** [comment]
Picker 在操作的时候 `onDropdownVisibleChange`  不要去设置 open
