### ISSUE TITLE
antd tree checkStrictly开启，checkedKeys默认赋值，如何在不点击组件的情况下获取halfChecked半选节点的数据?

### ISSUE THREAD

**Issue by HalcyonDaysssss** [ant-design/ant-design#37454]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quiet-rgb-si76g0?file=/src/App.js)

### Steps to reproduce

https://codesandbox.io/s/quiet-rgb-si76g0?file=/src/App.js

### What is expected?

开启父子节点不关联的情况下，复选框节点checkedKeys默认赋值，在不点击组件的情况下，获取halfChecked的数据

### What is actually happening?

不点击组件的情况下，无法获取halfChecked的数据

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | mac |
| Browser | 104 |

**Comment by afc163** [comment]
checkStrictly 了就不存在半选的样式了吧

**Comment by HalcyonDaysssss** [comment]
> checkStrictly 了就不存在半选的样式了吧

可以，在onClick那里可以获取到，但是有一个问题就是，假如我不点击组件，不通过onclick，直接保存数据，怎么获取到halfChecked,像其他tree，可以通过ref获取到，antd的tree只能通过点击组件onclick获取，这个就很麻烦，很头疼

**Comment by afc163** [comment]
checkedKeys 和 treeData 都是你传入的，你本身就知道了所有信息。

**Comment by 13417094465** [comment]
[https://blog.csdn.net/weixin_47183748/article/details/133173575?spm=1001.2014.3001.5502](url)

参考这篇文章

**Comment by 13417094465** [comment]
[]([https://blog.csdn.net/weixin_47183748/article/details/133173575?spm=1001.2014.3001.5502](https://github.com/ant-design/ant-design/issues/url))

**Comment by 13417094465** [comment]
['解决方法']([https://blog.csdn.net/weixin_47183748/article/details/133173575?spm=1001.2014.3001.5502](https://github.com/ant-design/ant-design/issues/url))
