### ISSUE TITLE
2.3.0dist文件夹缺少css文件

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#3745]
升级到2.3.0之后，发现dist文件夹少了antd.css，想问下是不是有意去掉的？

**Comment by afc163** [comment]
应该是 bug 。

**Comment by afc163** [comment]
貌似是这里搞挂的。https://github.com/ant-design/ant-design/pull/3397

**Comment by xuliuzhu1834** [comment]
我还以为你们是刻意去掉的， 之前是直接用min.css的 现在直接用less然后再打包。。。

**Comment by afc163** [comment]
刻意去掉的话，changelog 一定会体现的。

**Comment by yesmeck** [comment]
试了下单独跑 `atool-build run dist`，是没生成 antd.css，没看懂跟 #3397 有什么关系。

**Comment by afc163** [comment]
原来是依赖 extract-text-webpack-plugin 自动生成样式的。

https://github.com/ant-design/ant-design/pull/3397/files#diff-168726dbe96b3ce427e7fedce31bb0bcL11

**Comment by yesmeck** [comment]
已经发布了 2.3.1。
