### ISSUE TITLE
Switch 激活时背景闪白的问题

### ISSUE THREAD

**Issue by liuyib** [ant-design/ant-design#37453]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-switch-ji-huo-shi-bei-jing-shan-bai-de-bug-291sjr?file=/demo.js)

### Steps to reproduce

将 antd 依赖版本升级到 v4.20.0 及以上，点击 Switch 即可看到

### What is expected?

激活 Switch 时背景颜色不闪白

### What is actually happening?

激活 Switch 时背景颜色闪白

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 17.0.2 |
| System | macOS12.3.1 |
| Browser | Chrome 103.0.5060.114 |

---
该 bug 在暗色背景下可以明显看出，白色背景下不容易发现

**Comment by liuyib** [comment]
经测试，这个问题在 antd v4.20.0 版本引入，最新版本中仍存在

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/35103

**Comment by afc163** [comment]
background-image 不支持 transition，不好解决，我还是先回滚吧。
