### ISSUE TITLE
使用getFieldDecorator的DatePicker，调用form.resetFields后无法重置

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#3746]
#### 发生问题的环境是：

- antd 版本: 2.3.0
- 操作系统及其版本: windows10
- 浏览器及其版本: chrome 56.0.2906.0 dev (64-bit)

#### 您期待的结果是:

重置DatePicker

#### 实际上的结果是:

DatePicker无法重置

#### 可重现的在线演示

https://codepen.io/infeng/pen/QKXzLe?editors=1011

**Comment by benjycui** [comment]
需要设置 `initialValue` 为 `null`。

**Comment by infeng** [comment]
是因为https://github.com/ant-design/ant-design/commit/0b7856b7127a6ff165e5e74c78dc3f74bdb0a1ca 这个修改吗

**Comment by benjycui** [comment]
是滴。

**Comment by benjycui** [comment]
现在 antd 里面 `undefined | null` 的语义没有统一，但是还是建议在置空时只用 `null`，毕竟这是语言的设定。

**Comment by ycshill** [comment]
我遇到了类似的问题：
问题描述：from 表单重置的时候 ``this.props.form.resetFields();`` ,希望DatePicker 组件再次点击展开的时候，下拉时间还是上次的时间，我希望时间下来的时候能够和一进来的时候一样
