### ISSUE TITLE
Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design#37468]
### Reproduction link

[https://stackblitz.com/run?file=index.js](https://stackblitz.com/run?file=index.js)

### Steps to reproduce

open it

### What is expected?

show noraml case

### What is actually happening?

Error in /turbo_modules/react@18.2.0/cjs/react.development.js (1622:21)
Cannot read properties of null (reading 'useState')

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/16385443/189061249-d3c048e3-041a-4d10-a845-fbfd49af215d.png">

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
Your reproduce is empty.

**Comment by xuoutput** [comment]
https://ant.design/components/tabs-cn/ 就是官网的

**Comment by MadCcc** [comment]
So wired. `React` in stackblitz is `17.0.2`, and we do not have extra configuration for this.
Going to remove React 17 demo to fix this.
