### ISSUE TITLE
Upload上传为受控组件时Hooks写法在onChange事件status卡在uploading

### ISSUE THREAD

**Issue by daye99** [ant-design/ant-design#37474]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/emj2p3)

### Steps to reproduce

重现链接是官方文档的受控组件。在项目开发时遇到的问题。以为是偶然，在实验了官网的code，结果却是必然

### What is expected?

期望像不受控组建一样，status走uploading done error

### What is actually happening?

卡在uploading状态

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 16.13.1 |
| System | Mac OS 12.5.1 |
| Browser | Chrome  105.0.5195.52 |

---
在以往的issue里面找到了一个相同的问题，却是class写法，上面的解决办法是setState({fileList: [...FileList]})，但是在hooks写法里面，绑定了受控组件，如下：

const [fileList, setFileList] = useState([])

<Upload FileList={FileList} onChange={handleChange}><UIpload>

const handleChange = ({file, fileList}) => {
    console.log(file.status)
    const files = [...fileList]

   setFileList(files)
}

官网QA：
onChange 事件仅会作用于在列表中的文件，因而 fileList 不存在对应文件时后续事件会被忽略。请注意，在 4.13.0 版本之前受控状态存在 bug 导致不在列表中的文件也会触发

上述代码setFileList并不是空的，且也没有继续执行后续change事件

**Comment by afc163** [comment]
例子无法重现问题。

**Comment by daye99** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49061744/189105580-183dda9c-627b-4503-82e5-ea040828a5f0.png">


https://codesandbox.io/s/8v0vn4?file=/demo.js

刚刚发错链接了
