### ISSUE TITLE
Carousel 在某些情况下到了一定时间后就停止切换

### ISSUE THREAD

**Issue by fladower** [ant-design/ant-design#3747]
#### 发生问题的环境是：

- antd 版本:1.6.2  or 2.3.0
- 操作系统及其版本: windows 64x
- 浏览器及其版本: chrome 51.0.2704.103 m

#### 您做了什么？请提供尽可能详细的重现步骤。

页面引入了 Carousel，其中当前页面调用了两次， 当前页面的子页面同时引入了Carousel并且调用了两次，并且都设置了autoplay="true"和 autoplaySpeed="5000"

#### 您期待的结果是:

走马灯能够每5秒滚动一次

#### 实际上的结果是:

某些时候，或者说某些情况下， 走马灯不再切换，停止作用，鼠标拖动也没有效果，具体在哪些情况下也说不清楚，突然就停止作用了

**Comment by benjycui** [comment]
还是希望能给出重现步骤，然后这个组件出问题的话，基本都是底层的 [react-slick](https://github.com/akiran/react-slick) 的问题。

**Comment by warmhug** [comment]
也碰到过，可能跟页面销毁时处理不当有关，不确定

**Comment by fladower** [comment]
已经找到停止作用的原因。
假设第一次返回了5条数据渲染到carousel，这个时候carousel是正常的；第二次返回的数据如果是6条，这个时候carousel也能正常跑动。但是如果第二次返回的数据比前一次少，就会出现我上面提到的问题，会停止作用，而且还有一个前提，就是carousel刚好轮播到第一次数据的[length-2]条，将要轮播切换到最后一条数据[length-1]的时候，这个时候carousel拿到新的数据渲染，就出现问题了。
![image](https://cloud.githubusercontent.com/assets/5435475/20167305/97def946-a755-11e6-93af-1f4fa107fb2c.png)

差不多就上面这个意思。不知道算不算一个bug。。

**Comment by benjycui** [comment]
如果能翻译成英文，再提到 react-slick 就更好了 😄

**Comment by fladower** [comment]
底层的react-slick 是没问题的，在render的时候会多生成两个div，分别为 index=-1 和 index=data.length，这样貌似就避免了问题，但是在antd的Carousel内是有几条数据就生成几个div，从 index=0开始计算。

**Comment by benjycui** [comment]
那就奇怪了。。https://github.com/ant-design/ant-design/blob/master/components/carousel/index.tsx#L50-L68

你测试的是哪个版本的 react-slick

**Comment by fladower** [comment]
react-slick 版本是 0.14.5

**Comment by benjycui** [comment]
用最新版 antd，同时 `rm -rf node_modules & npm i` 试下。

**Comment by yesmeck** [comment]
没进一步反馈就关闭了，如果有问题随时可以再打开。
