### ISSUE TITLE
Hours, minutes and seconds don't change, when choosing date in datepicker

### ISSUE THREAD

**Issue by DiRover** [ant-design/ant-design#37478]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vqqlqz?file=/demo.js)

### Steps to reproduce

Сlick on the fist datepicker. Popup should always be opened -> choose date -> look on the date and time into the console -> choose other date -> look on the date and time into the console. Date was changed, but minutes and seconds did not -> click on the button "Today". All was changed

### What is expected?

All items in datepicker (date, hours, minutes, seconds) should change, when choosing different date from first choice

### What is actually happening?

Hours, minutes and seconds don't change, when choosing different date from first choice

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 18.2.0 |
| System | Mac Os Monterey |
| Browser | Google Chrome |

**Comment by MadCcc** [comment]
It's okay for `date` mode only changing date. If you want to change time at the meantime, you can use `showTime`.
