### ISSUE TITLE
Setting active key for Tabs doesn't change the tab

### ISSUE THREAD

**Issue by ronneldavis** [ant-design/ant-design#37472]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-io5h9p)

### Steps to reproduce

Set the selectedTab to any other tab and it doesn't update the tab shown on screen

### What is expected?

The tab to change when the selectedTab prop is updated

### What is actually happening?

Nothing happens

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | 18.2.0 |
| System | Mac OS |
| Browser | Safari |

**Comment by zombieJ** [comment]
```diff
    { key: "first", title: "First", children: <h1>First</h1> },
--  { key: "second", title: "Second", children: <h1>First</h1> }
++  { key: "second", title: "Second", children: <h1>Second</h1> }
```
