### ISSUE TITLE
4.19.0升级最新版form.Item表单结构发生了变化？

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design#37477]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blissful-gates-cf8x41?file=/src/App.js)

### Steps to reproduce

引入表单控件

### What is expected?

结构未发生变化

### What is actually happening?

层级结构发生变化丢失样式类名

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 16.14.0 |
| System | mac |
| Browser | 104.0.5112.79 |

![20220908182810](https://user-images.githubusercontent.com/16549630/189100418-b11a5c21-b7b3-469c-a2b4-10cd44fb28f0.jpg)
第一张图为4.19.0的form.Item结构

![20220908182643](https://user-images.githubusercontent.com/16549630/189100665-e40a4b31-dfdd-4d6c-b7ff-b67b80582362.jpg)
第二张图为4.23.0的form.Item结构

**Comment by afc163** [comment]
你遇到的问题是啥，表单展现具体出现了什么问题？是否有重现的例子。

**Comment by zhilianbi520** [comment]
@afc163 根据我们自己的设计要求重新覆盖了库的原样式，但是升级版本后由于结构发生变化，样式就有问题了。

**Comment by afc163** [comment]
那确实 dom 是有变化的，这种自定义样式覆盖需要开发者在版本升级的过程做好确认和回归。

**Comment by zhilianbi520** [comment]
@afc163 https://codesandbox.io/s/nice-jasper-1584wy?file=/src/App.js 即使不覆盖原样式4.19.0与2.23.0区别也很大，必选的提示星信息在23的版本上能正常展示，但是在19的版本中就不能正常展示了

**Comment by afc163** [comment]
> 但是在19的版本中就不能正常展示了

我打开这个链接看貌似没啥问题 https://codesandbox.io/s/epic-hopper-6x54ev?file=/package.json

<img width="748" alt="图片" src="https://user-images.githubusercontent.com/507615/189306785-91308988-fbd1-4e3b-91f1-eb1cef2033a5.png">
