### ISSUE TITLE
responsive does not work in Pagination

### ISSUE THREAD

**Issue by long76** [ant-design/ant-design#37479]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/total-number-antd-4-23-0-forked-i2lkqe?file=/demo.js)

### Steps to reproduce

set responsive to true and size to null

### What is expected?

window sized Pagination

### What is actually happening?

nothing to change

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 18.2.0 |
| System | Kubuntu 20.04 |
| Browser | Google Chrome 105.0.5195.102 |

**Comment by afc163** [comment]
It changed in your codesandbox. 
<img width="397" alt="图片" src="https://user-images.githubusercontent.com/507615/189110998-dc09283a-8ce1-4f94-93b2-e232cd497d1e.png">

**Comment by long76** [comment]
> It changed in your codesandbox. <img alt="图片" width="397" src="https://user-images.githubusercontent.com/507615/189110998-dc09283a-8ce1-4f94-93b2-e232cd497d1e.png">

i mean adjust to width window

**Comment by afc163** [comment]
`responsive` property is not working in this way now.

**Comment by long76** [comment]
> `responsive` property is not working in this way now.

i see thanks for help!
