### ISSUE TITLE
Divider in "inline" layout form is not working properly

### ISSUE THREAD

**Issue by xiyusullos** [ant-design/ant-design#37486]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-browser-nr9ze2)

### Steps to reproduce

Test

### What is expected?

divider line should be in the middle.

### What is actually happening?

divider line is in the bottom.

| Environment | Info |
| --- | --- |
| antd | 4.18.0 |
| React | latest |
| System | Windows 10 |
| Browser | Chrome Version 104.0.5112.102 (Official Build) (64-bit) |

**Comment by afc163** [comment]
```jsx
.ant-form-inline {
  display: flex;
}
```

This line will break Divider style, I think it is intented.
