### ISSUE TITLE
Mentions does not be triggered when typing the @ quickly

### ISSUE THREAD

**Issue by Miever1** [ant-design/ant-design#37493]
### Reproduction link

[https://ant.design/components/mentions-cn/#API](https://ant.design/components/mentions-cn/#API)

### Steps to reproduce

Mentions does not be triggered when typing the @ quickly

### What is expected?

should be triggered

### What is actually happening?

not be triggered

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | last |
| System | macos |
| Browser | Firefox |

**Comment by Miever1** [comment]
这个不需要重现实例，官网 Demo看一下就行吧

**Comment by clmz** [comment]
This problem happens to me occasionally even on the example page, when I start with typing '@' in input of the basic example. Deleting the '@' and typing it again often helps to trigger the dropdown, but not always - seems pretty random.

Browser is chrome Version 114.0.5735.110 (Official Build) (64-Bit)
