### ISSUE TITLE
Cascader列选项中只有一项disabled为false时，选中它，父级不应该被选中了,应该为半选状态

### ISSUE THREAD

**Issue by JessicaCoder** [ant-design/ant-design#37501]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-antd-4-23-0-forked-tvhlu9?file=/demo.js:606-608)

### Steps to reproduce

import React from "react";
import "antd/dist/antd.css";
import "./index.css";
import { Cascader } from "antd";

const options = [
  {
    label: "Light",
    value: "light",
    children: new Array(20).fill(null).map((_, index) => ({
      label: `Number ${index}`,
      value: index
    }))
  },
  {
    label: "Bamboo",
    value: "bamboo",
    children: [
      {
        label: "Little",
        value: "little",
        children: [
          {
            label: "Toy Fish",
            value: "fish"
          },
          {
            label: "Toy Cards",
            value: "cards",
            disabled: true
          },
          {
            label: "Toy Bird",
            value: "bird",
            disabled: true
          }
        ]
      }
    ]
  }
];

const onChange = (value) => {
  console.log(value);
};

const App = () => (
  <Cascader
    style={{
      width: "100%"
    }}
    options={options}
    onChange={onChange}
    multiple
    maxTagCount="responsive"
  />
);

export default App;

### What is expected?

children多项时，仅有一项未禁用数据且被选中时，其父级呈现半选状态

### What is actually happening?

children多项时，仅有一项未禁用数据且被选中时，其父级呈现半选状态

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 18.3.0 |
| System | macOS 12.3 |
| Browser | Microsoft Edge 99.0.1150.55 |

---
为了方便对比，请选Bamboo那行数据

**Comment by zombieJ** [comment]
https://ant.design/components/tree-cn/#disabled-%E8%8A%82%E7%82%B9%E5%9C%A8%E6%A0%91%E4%B8%AD%E7%9A%84%E5%85%B3%E7%B3%BB%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F

**Comment by JessicaCoder** [comment]
希望呈现的效果，与未禁用同级子项时的效果一致（除了呈现时，禁用的项不能点以外）
