### ISSUE TITLE
tabs在动态循环出来不显示

### ISSUE THREAD

**Issue by longang520** [ant-design/ant-design#3750]
<Tabs defaultActiveKey="-1" activeKey={this.state.activeKey} tabPosition={'left'} onTabClick={this.onTabClickHandle.bind(this) }>
                <TabPane tab={<span></span>} key="-1">
                    欢迎使用
                </TabPane>
                 <TabPane tab={<span>1</span>} key="1d45fcb9a9e24c6cbb3d9fe96b471bff">
                </TabPane>
                 <TabPane tab={<span>2</span>} key="2sdf">
                    欢迎使用2
                </TabPane>
                 <TabPane tab={<span>3</span>} key="3wer">
                    欢迎使用3
                </TabPane>
                {this.state.oftens.map(pane => <TabPane tab={pane.FriendName} key={pane.Key}>{pane.FriendName}</TabPane>)}
            </Tabs>

动态循环出来显示为空.
element.style {
    display: none;
}

**Comment by RaoHai** [comment]
oftens 的数据打出来看看。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by longang520** [comment]
![image](https://cloud.githubusercontent.com/assets/4744635/20049510/6dd78608-a4fe-11e6-9fbe-4bae1a68e88d.png)
主要是这个属性

**Comment by RaoHai** [comment]
如果 `activeKey` 在 `Tab` 的 `TabPane` 中找不到，` tabs-content` 就隐藏。检查一下 this.state.activeKey。

**Comment by longang520** [comment]
我检查了.中间是有的.郁闷了.

**Comment by longang520** [comment]
<Tabs defaultActiveKey="-1" tabPosition={'left'}>
                <TabPane tab={<span>123</span>} key="-1">
                    欢迎使用
                </TabPane>
                {this.renderList() }
            </Tabs>
我将this.state.activeKey 这个删除也不行。不知道为什么。

**Comment by longang520** [comment]
![image](https://cloud.githubusercontent.com/assets/4744635/20050359/de9c07ec-a503-11e6-9e65-24c14e5bcb84.png)
log出来是有的。

**Comment by RaoHai** [comment]
试试能不能用 mock 的数据在 http://codepen.io/benjycui/pen/KgPZrE?editors=001 重现一下。 截图 debug 效率不高。。

**Comment by longang520** [comment]
好的。在试了。

**Comment by longang520** [comment]
http://codepen.io/longang/pen/WobYZR

**Comment by longang520** [comment]
@RaoHai http://codepen.io/longang/pen/WobYZR

**Comment by RaoHai** [comment]
你的 demo 里有两个 key 为 1 的 Tabpanel.. key 不能重复的。。

**Comment by longang520** [comment]
我更新。你在看下。

**Comment by longang520** [comment]
http://codepen.io/longang/pen/dOPQdB

**Comment by RaoHai** [comment]
好像确实有点不对。。

**Comment by longang520** [comment]
是有点不对。我不确定是我的代码问题。

**Comment by afc163** [comment]
貌似和 https://github.com/ant-design/ant-design/commit/1f670b84a9abdd2af70160a7b1c678c9f203fcb8 要修复的问题类似。

**Comment by RaoHai** [comment]
是的。混写的时候 children 是 `[child, [child, child]] ` 的形式，用 React.Children.map/forEach 可以正常遍历，https://github.com/react-component/tabs/blob/master/src/utils.js#L16 用 for 是不行的。

**Comment by longang520** [comment]
我现在要怎么解决这个问题。或者有一个临时的解决方案。

**Comment by RaoHai** [comment]
尽快修复。或者你先不要混写。也就是所有的 TabPanel 全部从循环里生成。

**Comment by longang520** [comment]
```
return this.state.oftens.map(function (item, index) {
            console.log("````````````````````-", item.Key);
            return (<TabPane tab={<div className="messageSendListOne">
                <a className="closeOften" onClick={this.closeOften.bind(this, item.Key) }><Icon type="cross" /></a>
                <HeadImg type={item.Type} className={item.Type == "2" ? "img groupimg" : "img"} userKey={item.FriendKey} />
                <Badge count={item.MessageCount} >{item.FriendName}</Badge></div>} key={item.Key}>
                <MessageSend oftenInfo={item} newMessage={this.newMessageBind(item) }/>
            </TabPane>);
        }.bind(this));
```

我是这样写的。也不行。

**Comment by RaoHai** [comment]
那等修复吧。。

**Comment by longang520** [comment]
好的。
