### ISSUE TITLE
ant-design v4.23.0 introduces breaking changes

### ISSUE THREAD

**Issue by atanasov-deyan** [ant-design/ant-design#37519]
### Reproduction link

[https://github.com/ant-design/ant-design/releases/tag/4.23.0](https://github.com/ant-design/ant-design/releases/tag/4.23.0)

### Steps to reproduce

Try using for example a <Drawer/> component with the current `visible` visibility prop as per v4 api.

### What is expected?

Drawer to change visibility depending on whether it is passed true or false for `visible` prop

### What is actually happening?

visibility does not change since prop name has been changed to `open`

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | any |
| System | any |
| Browser | any |

---
given this is an API breaking change, shouldn't all related PRs that switch visibility state prop from `visible` to `open` be done in a new major release, i.e. v5.0.0? This is not explicitly said in any in the release note, too.

Related PRs:

- [ ] https://github.com/ant-design/ant-design/pull/37084
- [ ] https://github.com/ant-design/ant-design/pull/37047
- [ ] https://github.com/ant-design/ant-design/pull/37026
- [ ] https://github.com/ant-design/ant-design/pull/37000
- [ ] https://github.com/ant-design/ant-design/pull/37241
- [ ] https://github.com/ant-design/ant-design/pull/36934

**Comment by afc163** [comment]
visible is still work in 4.23.0: https://codesandbox.io/s/ji-chu-chou-ti-antd-4-23-1-forked-iqfz01?file=/demo.js

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Why-we-need-align-pop-component-with-open-prop?

**Comment by MadCcc** [comment]
We will keep `visible` in next major though it is deprecated, but I recommend to use `open` instead.

**Comment by atanasov-deyan** [comment]
Thanks for clarifying, @afc163 and @MadCcc! Wanted to double-check, as the release notes said 'deprecate', which I interpreted the wrong way.
