### ISSUE TITLE
Card with tabList prop still uses deprecated TabPane

### ISSUE THREAD

**Issue by adnan-i** [ant-design/ant-design#37515]
### Reproduction link

[https://ant.design/components/card/#components-card-demo-tabs](https://ant.design/components/card/#components-card-demo-tabs)

### Steps to reproduce

View the official demo for tabbed Card component. Follow the example link to Codepen.

### What is expected?

Expected not to see a deprecation error: "Warning: [antd: Tabs] Tabs.TabPane is deprecated. Please use `items` directly.".

### What is actually happening?

Seeing deprecation error.

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 16 |
| System | Mac OS Monterey |
| Browser | Chrome |

**Comment by edc-hui** [comment]
我来修复此问题
