### ISSUE TITLE
Table的rowSelection如何自定义单元格内容

### ISSUE THREAD

**Issue by yhhwpp** [ant-design/ant-design#3751]
#### 发生问题的环境是：

- antd 版本:2.3.0
- 操作系统及其版本:win7
- 浏览器及其版本:chrome 54.0

#### 您做了什么？请提供尽可能详细的重现步骤。

我不想设置getCheckboxProps 的 disabled 为true，而是想直接显示为"-",请问下支持吗？

**Comment by benjycui** [comment]
如非必须，尽量遵循 Ant Design 设计规范。

**Comment by yhhwpp** [comment]
@benjycui  产品经理提的需求，如果不支持的话，是不是只能自定义一列，自定义其内容，然后绑定事件？

**Comment by benjycui** [comment]
是的。

**Comment by yhhwpp** [comment]
ok

**Comment by suntenghub** [comment]
antd 版本:2.12.0
不能通过getCheckboxProps设置indeterminate属性吗？
使用场景是嵌套的树型数据表格，子节点选中时，对应父节点显示"-"状态
<img width="343" alt="783a534c-25b2-4bf3-91c3-1eef974fb48f" src="https://user-images.githubusercontent.com/12639649/29021791-44e2cfce-7b99-11e7-981c-65174a0feead.png">
如图中，选中Jim Green jr后，Jim Green的checkbox变为“-”

**Comment by benjycui** [comment]
@suntenghub it seems that [it doesn't support now](https://github.com/ant-design/ant-design/blob/53d279eb774325b2846178277c50bd31ff416235/components/table/SelectionBox.tsx#L71-L77). Please file a new issue as feature request, thanks.
