### ISSUE TITLE
Table filterSearch function doesn't work

### ISSUE THREAD

**Issue by BenBohannon** [ant-design/ant-design#37518]
### Reproduction link

[https://ant.design/components/table/#components-table-demo-filter-search](https://ant.design/components/table/#components-table-demo-filter-search)

### Steps to reproduce

Select "Address" column filters and attempt to search with "London" or "New"

### What is expected?

Filters are filtered down to the searched value.

### What is actually happening?

Everything is always filtered.

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 17 |
| System | latest macOS |
| Browser | chrome |

---
The Name column also doesn't work, but due to a mistake in the example:

    onFilter: (value, record) => record.address.startsWith(value),

should be

    onFilter: (value, record) => record.name.startsWith(value),

**Comment by samyarkd** [comment]
I would like to work on this issue.

**Comment by edc-hui** [comment]
Let me fix this problem.
