### ISSUE TITLE
气泡卡片指向位置偏离

### ISSUE THREAD

**Issue by jounzhang** [ant-design/ant-design#37524]
### Reproduction link

[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce

点击文字显示
指向箭头错位

### What is expected?

指向点击的元素

### What is actually happening?

偏离点击的元素
![image](https://user-images.githubusercontent.com/11515463/189827058-b10bf0bd-52f1-41d2-b420-e053d973c7bf.png)
![image](https://user-images.githubusercontent.com/11515463/189827080-e62d2a3e-4995-433a-bbf8-d57cd5bff81a.png)

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | * |
| System | win11 |
| Browser | 谷歌,360 |

**Comment by MadCcc** [comment]
1. 可以试试 `arrowPointAtCenter`，不过内容太长，暂时不支持箭头自动定位
2. 提供 reproduction 是指提供一个 CodeSandbox 等可运行的 demo，不是截图代码，可以不用重新开 issue

**Comment by jounzhang** [comment]
希望能够支持
