### ISSUE TITLE
Form中多个Input框时，回车不会触发onSubmit

### ISSUE THREAD

**Issue by zxyah** [ant-design/ant-design#3752]
在不用到Form校验时，当Form中有多个Input框时，回车不会触发onSubmit事件
[问题重现地址](http://codepen.io/zxyah/pen/LbEXOa)

**Comment by benjycui** [comment]
略诡异。。

**Comment by afc163** [comment]
这个是 HTML 规范。http://stackoverflow.com/a/17797230/3040605

**Comment by ImJoeHs** [comment]
@benjycui 那能否考虑给form一个onPressEnter？ 每个input都得写还是有点疼。

**Comment by benjycui** [comment]
增加 `<Button htmlType="submit">Submit</Button>` 后，`Form` 就可以相应 enter 时间了，同为 HTML 默认行为。
