### ISSUE TITLE
Table column filterMode=tree 时，filterSearch 为function时未执行，filterMode=menu时正常

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#37544]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-shai-xuan-de-sou-suo-antd-4-23-1-forked-bp2kc2?file=/demo.js)

### Steps to reproduce

选择name列进行搜索

### What is expected?

控制台打印出查询条件

### What is actually happening?

控制台未打印出查询条件

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | react 17 ，react 18  |
| System | mac |
| Browser | chrome |

**Comment by gonenoob** [comment]
filterMode为menu时正常执行了，但是tree时未执行

**Comment by gonenoob** [comment]
https://github.com/ant-design/ant-design/blob/711ed90141dcbd7b73e42a259de77f435961bf68/components/table/hooks/useFilter/FilterDropdown.tsx#L372
```js
node => {
  if (typeof filterSearch === 'function') {
    return filterSearch(searchValue, {
      key: node.key,
      title: node.title,
    })
  }

  return searchValueMatched(searchValue, node.title)
}
```

**Comment by afc163** [comment]
Depends on https://github.com/ant-design/ant-design/issues/27197#issuecomment-711488311

**Comment by gonenoob** [comment]
不不，我指的是filterSearch 为函数时没执行，而不是过滤treenode

**Comment by afc163** [comment]
现在代码加进去执行了也不会过滤，因为 Tree 本身还不支持过滤。

**Comment by gonenoob** [comment]
那就是filterMode为true时不支持filterSearch为function了...文档没标注这一点

**Comment by gonenoob** [comment]
我还以为filtersearch实际是匹配筛选项，只不过menu是筛选隐藏，tree是匹配到加重显示

**Comment by afc163** [comment]
> 那就是filterMode为tree时不支持filterSearch为function了...文档没标注这一点
对，应该标注。

> 我还以为filtersearch实际是匹配筛选项，只不过menu是筛选隐藏，tree是匹配到加重显示
理想情况是和 Menu 保持一致，因此需要 https://github.com/ant-design/ant-design/issues/27197#issuecomment-711488311
当然，先支持了 filterSearch 的调用，高亮显示也可以。

**Comment by gonenoob** [comment]
那就先支持下filterSearch的调用呗。因为业务里有时候匹配不只是title需要匹配，value有时候也需要.
