### ISSUE TITLE
通过 babel-plugin-import css 方式导入 antd 后，没有对应样式

### ISSUE THREAD

**Issue by markzhai** [ant-design/ant-design#3754]
#### 发生问题的环境是：

- antd 版本: 2.3.1
- 操作系统及其版本: OS X 10.11.6
- 浏览器及其版本: Chrome 54.0.2840.71 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

通过 `babel-plugin-import` 引入了 `antd`

bablelrc:
```
{
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": "css"
      }
    ]
  ]
}
```

#### 您期待的结果是:

像官网一样正常显示

#### 实际上的结果是:

css 并没有被导入，控制台看classname找不到对应的source，"style" 设为 true，webpack 加上 less loader 后才可以正确加载css并显示

#### 可重现的在线演示

无

**Comment by benjycui** [comment]
麻烦提供可重现 repo

**Comment by afc163** [comment]
没进一步信息就关了，无法解决。

**Comment by stoneshao** [comment]
遇到了同样的问题，按照 https://ant.design/docs/react/practical-projects-cn的步骤来，最后的页面没有antd的样式
