### ISSUE TITLE
Cannot close Message by effect cleanup on first mount in StrictMode

### ISSUE THREAD

**Issue by JackClown** [ant-design/ant-design#37540]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-feynman-ikhegq?file=/src/App.js)

### Steps to reproduce

just see it

### What is expected?

there is only one toast

### What is actually happening?

there are two toasts

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | Chrome 105 |

---
we know that StrictMode's development-only check will unmount and remount every component. so the effect will run twice in the demo and the first message should be closed by the cleanup.

**Comment by zombieJ** [comment]
to support StrictMode. Static function was rewrite in v5. Since to avoid break change, this may not fix in v4.

ref: https://codesandbox.io/s/charming-noether-crqpu0?file=/src/App.js
