### ISSUE TITLE
DatePicker component does not support changing yearStart with DayJS localization

### ISSUE THREAD

**Issue by vyacheslav31** [ant-design/ant-design#37556]
### Reproduction link

[https://stackblitz.com/edit/react-ts-dx5ysf?file=App.tsx](https://stackblitz.com/edit/react-ts-dx5ysf?file=App.tsx)

### Steps to reproduce

1. Install DayJS
2. Replace momentjs with dayjs
3. Update locale to start the year with any week other than 1. 
4. Instantiate a datepicker[picker='week']
5. Observe year start remaining the same

```JavaScript
import * as React from 'react';
import './style.css';
import 'antd/dist/antd.css';
import dayjs, { Dayjs } from 'dayjs';
// import { dayjs } from 'dayjs';
import updateLocale from 'dayjs/plugin/updateLocale';
import localeData from 'dayjs/plugin/localeData';
import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
import generatePicker from 'antd/es/date-picker/generatePicker';

dayjs.extend(updateLocale);
dayjs.extend(localeData);
const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig);

/**
 * DayJS Custom Localization:
 *
 * https://day.js.org/docs/en/customization/customization
 */

dayjs.updateLocale('en', {
  yearStart: 4, // February 1st (does NOT work)
  weekStart: 4, // Thursday (works)
});

export default function App() {
  return (
    <div>
      <DatePicker picker="week" />
    </div>
  );
}

```

### Screenshot
![image](https://user-images.githubusercontent.com/43866398/190336165-a6e77ee8-040b-41d9-a4fe-63d3777d3909.png)

### What is expected?

Year to begin at the specified week (4th week of the year / Feb 1st).

### What is actually happening?

Year always begins on January 1st. (1st week of the year / Jan 1st)

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 17.0.1 |
| System | MacOS Monterey Version 12.6 (21G115) |
| Browser | Chrome Version 105.0.5195.125 (Official Build) (arm64) |

---
Trying to implement business requirements.

**Comment by iamkun** [comment]
ref: https://day.js.org/docs/en/customization/customization

`yearStart: 4` means the week that contains Jan 4th is the first week of the year.

**Comment by vyacheslav31** [comment]
@iamkun With that logic, it should be `yearStart: 32`.  But while doing so displays the right date on the datepicker, if you try going to a date before that with the datepicker, it results in the following error:

```Maximum call stack size exceeded```

https://stackblitz.com/edit/react-ts-dx5ysf?file=App.tsx

**Comment by iamkun** [comment]
Jan 32 is an invalid date

**Comment by vyacheslav31** [comment]
> Jan 32 is an invalid date

Are you telling me the year can only start in January with AntD?

**Comment by vyacheslav31** [comment]
@iamkun Furthermore, January 16th **IS** and yet the DatePicker still crashes :) If you simply do not want to deal with this  issue, just let me know, I will close the issue :) 

```JavaScript
dayjs.updateLocale('en', {
  yearStart: 16,
  weekStart: 5,
});
```
![chrome-capture-2022-8-16](https://user-images.githubusercontent.com/43866398/190662229-be5b39bd-ba8d-442c-9ae2-a5636b28b03a.gif)

**Comment by iamkun** [comment]
seems Jan 16 should not be the first week of the year

**Comment by vyacheslav31** [comment]
> seems Jan 16 should not be the first week of the year

No you just don't want to fix it because you are 懒 .

**Comment by vyacheslav31** [comment]
I am done lol, I will just fix the problem by myself.

**Comment by irinazhyzhyian** [comment]
> I am done lol, I will just fix the problem by myself.

Please share your answer
