### ISSUE TITLE
【站点】antd系列站点适配问题

### ISSUE THREAD

**Issue by JaneYork** [ant-design/ant-design#37575]
### Reproduction link

[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce

Mac Safari浏览器手机模式（浏览器菜单栏 - 开发 - 进入响应式设计模式），或者IOS，官网站点无法出现左侧的side menu

### What is expected?

适配手机，，适配Safari，antdv全系站点也是这个适配问题。目测是使用了不兼容的语法，比如：零宽正则等

### What is actually happening?

站点适配

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 最新 |
| System | Mac OS12 |
| Browser | Safari最新 |

@zombieJ 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/29787967/190556249-1a14d4e7-df87-4f60-8886-3aea83d231e4.png">

**Comment by JaneYork** [comment]
手机端，样式错乱，不能自适应，比如：华为自带浏览器或者微信内打开ant.design，左右能滑动，布局样式错误。

**Comment by afc163** [comment]
原因是 https://github.com/react-component/drawer/pull/277/ 里移除了 Drawer `handler`。
