### ISSUE TITLE
日历组件DatePicker用周模式(picker="week")时，左边第一列的数据是多余的

### ISSUE THREAD

**Issue by bjtqti** [ant-design/ant-design#37573]
### Reproduction link

[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce

在官方文档中找到第一个示例，请选择周，点开日历，即可看到左边第一列的数字是不应该有的。

### What is expected?

左边第一列去掉（35,36,37,38,39,40）

### What is actually happening?

多出了35,36,37,38,39,40 这么一列

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 17.0.2 |
| System | macOS Big Sur |
| Browser | chrome 105.0.5195 |

---
日历中怎么可能会有35,36,37,38,39,40这样的日期嘛

**Comment by zombieJ** [comment]
左边数字标明当前选择年份中的第几周。
