### ISSUE TITLE
4.23.1版本使用Pagination组件报错：VM31:1 Uncaught TypeError: Cannot read properties of null (reading 'match')，ant-pagination-item在浏览器中会转化为a标签，a标签无法增加herf属性

### ISSUE THREAD

**Issue by CodeMak1r-zy** [ant-design/ant-design#37572]
### Reproduction link

[https://ant.design/components/pagination-cn/#API](https://ant.design/components/pagination-cn/#API)

### Steps to reproduce

官方文档里面的组件demo就存在这个问题

### What is expected?

控制台无报错，期望能够为ant-pagination-item转化的a标签新增API，为a标签提供herf属性。

### What is actually happening?

每次点击控制台都会报错，

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 18.2.0 |
| System | macOS 11.4 Big Sur |
| Browser | Chrome 105.0.5195.125 |

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/190552034-7204cedf-9c41-4163-a9ea-73824e9da567.png">

没发现问题。

**Comment by CodeMak1r-zy** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/90091332/190552480-19b42b88-bb52-4877-ad81-50edfd138265.png">

**Comment by afc163** [comment]
是不是有什么浏览器插件导致的？用隐身模式试试看？

**Comment by CodeMak1r-zy** [comment]
发现问题了，FeHelper的锅😫感谢您的回复
