### ISSUE TITLE
Cascader 多选框设置默认选中多层级的值，下拉框内容为什么不能展示多级的列

### ISSUE THREAD

**Issue by lijia-zg** [ant-design/ant-design#37588]
### What problem does this feature solve?

正常的联级下拉框有默认选中值后，列都会展示默认值的所有层级，而设置了多选框这个功能不行了，只能展示一列，需要点击后才能展示下一列，即使默认值配置的是多层级

### What does the proposed API look like?

多选框的默认选中下拉框的展示层级，与其他同步

**Comment by zombieJ** [comment]
多选框走不同分支时，你默认展示哪一条分支都是很诡异的。所以才会和单选不一样的逻辑。
