### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Ak6706072** [ant-design/ant-design#37581]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bq950z?file=/index.js)

### Steps to reproduce

Render menu inside Root and  Add some divs and add tabindex 0 on those divs then open the menu and press arrow keys  focus is going to those divs that is having tabindex not in menu

### What is expected?

As soon as we open the menu focus should get in the menu not somewhere else

### What is actually happening?

As soon as we open the menu focus should get in the menu not somewhere else

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 17.0.2 |
| System | Mac OS Monterey |
| Browser | Crome 105.0.5195.125 |

**Comment by afc163** [comment]
Try https://github.com/react-component/dropdown/pull/213/
