### ISSUE TITLE
Tabs 4.23.1 显示不了

### ISSUE THREAD

**Issue by shanhexi** [ant-design/ant-design#37583]
### Reproduction link

[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce

<Tabs items={[{ label: '123', key: '121' }]}></Tabs>

### What is expected?

正常展示

### What is actually happening?

无法显示

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | "umi": "^3.5.33" |
| System | mac |
| Browser | 版本 104.0.5112.101（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
查看 antd 版本，items 是新版本接口，老版本参考文档使用老的用法。

PS：没有提供重现，issue 就先关了。

**Comment by shanhexi** [comment]
4.32.1不就是新版本么，新版本的接口现在用不了，是antd的问题还是我使用方法有错误么



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月16日 18:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ant-design/ant-design] Tabs 4.23.1 显示不了 (Issue #37583) |

查看 antd 版本，items 是新版本接口，老版本参考文档使用老的用法。

PS：没有提供重现，issue 就先关了。

**Comment by Langlw1992** [comment]
+1 只能使用4.23之前的版本
