### ISSUE TITLE
Tooltip assumes child's `className` to be a string cause issues with `react-router` v6 `NavLink`

### ISSUE THREAD

**Issue by fguitton** [ant-design/ant-design#37596]
Hello everyone 🎈 
I hope you are doing wonderfully
I come today to challenge assumption made by the Tooltip component (and likely others)

### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-skhc8e)

### Steps to reproduce

Click on the links of the reproduction and witness that antd `Tooltip` shunts the styling.

### What is expected?

The tooltip shouldn't overwrite otherwise functional non-string `className` prop.

### What is actually happening?

The tooltip assumes that the child's `className` prop is a string which has no ground.
https://github.com/ant-design/ant-design/blob/87f9cf362b98095cb936da80ef10384250ee0ef4/components/tooltip/index.tsx#L279

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | * |
| System | * |
| Browser | * |

**Comment by zombieJ** [comment]
Hmmm... Tooltip need patch style on it. But yes. We should check on that.

**Comment by sunjiongjun** [comment]
the quick way is add <>{children} </>
