### ISSUE TITLE
Undisabled component form

### ISSUE THREAD

**Issue by germani** [ant-design/ant-design#37590]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L165](https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L165)

### Steps to reproduce

https://codesandbox.io/s/competent-tree-iqrr7j?file=/src/App.tsx

### What is expected?

undisabled component

### What is actually happening?

disabled button

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 18 |
| System | all |
| Browser | all |

**Comment by kiner-tang** [comment]
mark
