### ISSUE TITLE
select - defaultValue 的显示

### ISSUE THREAD

**Issue by haoxins** [ant-design/ant-design#376]
目前的默认值展示为 `value` 本身 (如: userId), 期望显示 `Option` 的 `children`

```html
<Select defaultValue={userId}>
  <Option key={userId} value={userId}>{username}</Option>
</Select>
```

**Comment by afc163** [comment]
默认展示的是 children ，比如这个例子：http://ant.design/components/select/#demo-basic 里是 Lucy 并非 lucy。

**Comment by TouchQQ** [comment]
如果value是数字，貌似有点问题

**Comment by yiminghe** [comment]
value 不能为数字

**Comment by TouchQQ** [comment]
@yiminghe  为什么不能是数字？

**Comment by yanglihuiylh102** [comment]
@likezero API就是这么写的，开发人员就是这么干的
