### ISSUE TITLE
为什么要把visible改成open，这会是一个不好的开始

### ISSUE THREAD

**Issue by Superman-wc** [ant-design/ant-design#37604]
### What problem does this feature solve?

对于弹出层是否显示的状态从visible 改为open ，不明白你们是怎么想的， 
从一个形容词改成了一个动词，
你要用open那也应该是opened, 应该是一种状态，而不是一个动作。
哎， 难怪阿里没落了。。。

### What does the proposed API look like?

哎， 难怪阿里没落了。。。

只是为了记忆，而去修改用了那么久的API，这不是一个成熟框架的表现

**Comment by 666-arch** [comment]
附议

**Comment by 666-arch** [comment]
请问具体是哪个版本开始由visible 改为 open了的？

**Comment by afc163** [comment]
Duplicate of #36609

**Comment by zxq08** [comment]
+1，最近用modal, popover, tooltip 发现我本地的attr和文档中完全对不上。属实恶心，旧版本直接舍弃？
