### ISSUE TITLE
[BUG] Steps步骤条 ant-steps-head-inner 中文字未垂直居中

### ISSUE THREAD

**Issue by WPH95** [ant-design/ant-design#3760]
#### 发生问题的环境是：

- antd 版本: 2.2.1
- 操作系统及其版本: Macintosh; Intel Mac OS X 10_11_5
- 浏览器及其版本:Chrome/54.0.2840.71

#### 您做了什么？请提供尽可能详细的重现步骤。

访问 https://ant.design/components/steps/ 即可看到 尤其是代码演示中的 迷你版的 step 2. 
2 明显靠上，未能垂直居中

#### 您期待的结果是:

ant-steps-head-inner 中的内容应该是垂直居中

#### 可重现的在线演示

https://ant.design/components/steps/

#### 问题分析:

```
.ant-steps .ant-steps-head-inner>.ant-steps-icon {
    line-height: 1;
    top: -1.5px;
    color: #2db7f5;
    position: relative;
}

.ant-steps.ant-steps-small .ant-steps-head-inner {
    border: 1px solid #ccc;
    width: 18px;
    height: 18px;
    line-height: 18px;
    text-align: center;
    border-radius: 18px;
    font-size: 12px;
    margin-right: 10px;
}
```
猜测该问题之前已经有发现，试图使用 top: -1.5px 矫正。 然而未起到效果。
参考 http://stackoverflow.com/questions/11829393/why-the-spans-line-height-is-useless

按以下办法可以解决问题：
1. ant-steps-head-inner 中的 span => div
2. line-height = ant-steps-head的 height + 2px (ant-steps-head的border-width 为1)

**Comment by afc163** [comment]
感谢你的反馈和细致分析，对我们很有帮助~ 👍
