### ISSUE TITLE
Antd Affix classname inconsistent issue when using offset bottom 0 or offset bottom 10

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#37619]
### Reproduction link

[https://3eitnc.csb.app/](https://3eitnc.csb.app/)

### Steps to reproduce

Inspect element and target div of affix you will only see <div class> 

### What is expected?

should display `<div class=ant-affix>` or something

### What is actually happening?

only displays `div class` should display a classname ant-affix

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 17.0.2 |
| System | Mac Os Monterey |
| Browser | Google Chrome |

**Comment by tempoeric** [comment]
<img width="1440" alt="Screen Shot 2022-09-18 at 2 10 40 PM" src="https://user-images.githubusercontent.com/42777871/190889575-90b6a0d8-3bed-402e-bdac-ec9528f3340f.png">
<img width="1440" alt="Screen Shot 2022-09-18 at 2 10 50 PM" src="https://user-images.githubusercontent.com/42777871/190889579-b7692495-60b8-4211-bbed-197082b84306.png">
<img width="1440" alt="Screen Shot 2022-09-18 at 2 47 16 PM" src="https://user-images.githubusercontent.com/42777871/190889581-3b2e7093-d73d-4392-a1f2-1357de287ce8.png">

in the demo it never shows classname `ant-affix` only `div class` the issue is so inconsistent that sometimes the class shows and sometimes it doesnt

**Comment by MadCcc** [comment]
`ant-affix` provide `position: fixed` to the element, but it is not needed when children is not out of window.

**Comment by tempoeric** [comment]
@MadCcc the issue was missing from the div element when you inspect it. If you look at the first and second image you can see that the ant-affix class isnt there
