### ISSUE TITLE
Anchor组件 自定义高亮链接state,并通过组件的clikc和change改变state,存在闭包问题

### ISSUE THREAD

**Issue by promiseLC** [ant-design/ant-design#37627]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-mao-dian-gao-liang-antd-4-23-0-forked-r7y86p?file=/demo.js)

### Steps to reproduce

https://codesandbox.io/s/zi-ding-yi-mao-dian-gao-liang-antd-4-23-0-forked-r7y86p?file=/demo.js

### What is expected?

希望没有闭包问题,修改值能快速响应

### What is actually happening?

修改值存在闭包,需要通过ref去处理

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 17.0.1 |
| System | mac |
| Browser | Chrome 101 |

**Comment by promiseLC** [comment]
还有就是,我通过ref确实可以解决这个问题,但是getCurrentAnchor=()=>ref.current  ,我通过一个与Anchor组件无关的方式去改变ref, Anchor不响应, 解决方法我通过给Anchor一个ref,然后调用 ref.current.props.onChange(ref.current) ,总感觉怪怪的,这个大概多久能解决呢,因为我看到源码里面有了 FC版本

**Comment by huangyao295** [comment]
@promiseLC 请问你是怎么做到的？能说的具体点吗？

**Comment by promiseLC** [comment]
@huangyao295 没做到,我之前应该说错了,不记得了,都antd5了,你升级一下就好了
