### ISSUE TITLE
使用modal弹出的表单，在IE10和11中，首次打开会触发校验

### ISSUE THREAD

**Issue by conan2008** [ant-design/ant-design#3762]
在谷歌火狐IE89都是正常的，目前发现IE10.11第一次打开会直接触发校验。redio和rangeTime 没有出现， input都出现了，麻烦哥哥们帮忙看一下，感谢做出这么棒的框架。

![image](https://cloud.githubusercontent.com/assets/16290807/20089926/e73d43ae-a5c4-11e6-94d6-2203d34e3ca8.png)

**Comment by RaoHai** [comment]
官网的例子在 IE 11 下是正常的。

请提供一个可复现的示例帮助排查 : http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
@yiminghe 印象中之前碰到过？

**Comment by afc163** [comment]
1. 尝试升级到 react 和 antd 的最新版本。
2. 若还有问题，给出重现并 reopen 此 issue，否则无法修复。
