### ISSUE TITLE
antd Select组件 设置showSearch后, 输入内容, 输入框宽度消失

### ISSUE THREAD

**Issue by ShuBuShao** [ant-design/ant-design#37635]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-4-23-0-forked-u5j0fq?file=/demo.js)

### Steps to reproduce

1. 使用Select组件
2. 添加一个名称比较长的选项
3. 点击搜索
4. 搜索刚才自定义的比较长的选项
5. 宽度消失

### What is expected?

宽度正常显示

### What is actually happening?

输入框宽度消失

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
业务场景:  实际场景是商户切换, 会遇到一些名字比较长的选项, 大概30字左右, 由于选项较多, 添加了搜素, 但是在搜索的时候, 遇到了搜索框样式的问题

**Comment by zombieJ** [comment]
Select 组件本身宽度和内容相关，最小宽度从为了不 break 用户现有行为所以没有加上。如果对固定宽度有要求可以设置宽度，或者使用 Flex 布局让 Select 适应哈。
