### ISSUE TITLE
Tab组件 TabPanel区域使用shift   鼠标左键 会出现黑框

### ISSUE THREAD

**Issue by holiy930561** [ant-design/ant-design#37637]
### Reproduction link

[https://ant.design/components/tabs-cn/#header](https://ant.design/components/tabs-cn/#header)

### Steps to reproduce

鼠标移动到TabPanel  按住shift  鼠标左键

### What is expected?

不会出现黑色边框

### What is actually happening?

会出现黑色边框

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 17 |
| System | win11 |
| Browser | chrome 100 |

![image](https://user-images.githubusercontent.com/63273780/191015404-d5d33828-797b-4018-b7d3-a14612d04030.png)

**Comment by MadCcc** [comment]
浏览器自带的 focus 样式

**Comment by MadCcc** [comment]
原来的 `outline: none` 丢了

**Comment by zombieJ** [comment]
> 原来的 `outline: none` 丢了

其实无障碍这样挺好的，先修了。v5 里调一个好看点的样式出来。

**Comment by MadCcc** [comment]
> 其实无障碍这样挺好的，先修了。v5 里调一个好看点的样式出来。

我想的是 tabpane 本身没有功能为啥需要 tabindex...
