### ISSUE TITLE
Multiple visible drawers are displayed in the wrong order

### ISSUE THREAD

**Issue by DVSoftware** [ant-design/ant-design#37643]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-dsh39p?file=/index.js)

### Steps to reproduce

Nest multiple drawers that are visible at the same time

### What is expected?

Drawers should be displayed in the correct order

### What is actually happening?

Drawers are displayed out of order, with the child drawer displayed over the parent drawer

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 105 |

---
I'm displaying the drawers based on the URL parameters, and everything is fine while the user navigates through the UI, however, when user refreshes the page, the state which is remembered in the URL has both drawers set as visible, and when the page loads, the drawer order is wrong.

**Comment by MadCcc** [comment]
Workaround: https://codesandbox.io/s/antd-reproduction-template-forked-1ngbnd

**Comment by DVSoftware** [comment]
Yeah, i did something like that, but it would be nice not to have workarounds
