### ISSUE TITLE
表格请求数据时，有很大概率转圈，需要刷新（请求没有发出去）

### ISSUE THREAD

**Issue by Hu-Carrot** [ant-design/ant-design#37654]
### Steps to reproduce

无法100%重现

### What is expected?
页面表单数据显示

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | react |
| System | win10 |
| Browser | chrome |

---
表格请求数据时，有很大概率转圈，需要手动刷新重新请求一次

**Comment by zombieJ** [comment]
antd Table 没有 loading 功能，请自行检查。

**Comment by afc163** [comment]
提问请给重现，现在这些信息不足以排查。
