### ISSUE TITLE
在tree中自定义渲染标题，使用dangerouslySetInnerHTML渲染html，a标签无法跳转

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#37653]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-tu-biao-antd-4-23-2-forked-jgexkp)

### Steps to reproduce

使用Tree组件，并使用titleRender自定义渲染，然后返回div 使用dangerouslySetInnerHTML渲染a标签

### What is expected?

能够正常点击跳转

### What is actually happening?

无法跳转，点击事件被阻止了

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | react |
| System | window |
| Browser | chrome |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/zi-ding-yi-tu-biao-antd-4-23-2-forked-u2v11x?file=/demo.js
