### ISSUE TITLE
 Cannot resolve module 'antd/lib/button'

### ISSUE THREAD

**Issue by jeffycai** [ant-design/ant-design#3765]
#### 发生问题的环境是：

- antd 版本:v2.3.0
- 操作系统及其版本:
- 浏览器及其版本:

#### 实际上的结果是:

Module not found: Error: Cannot resolve module 'antd/lib/button/style/css' in C:\code\client-new\src\containers\login
 @ ./src/containers/login/Login.js 7:11-47

ERROR in ./src/containers/login/Login.js
Module not found: Error: Cannot resolve module 'antd/lib/button' in C:\code\client-new\src\containers\login
 @ ./src/containers/login/Login.js 9:14-40

**Comment by afc163** [comment]
是有这个文件的。

https://unpkg.com/antd@2.3.0/lib/button/style/

请尝试重新安装 node_modules 。
