### ISSUE TITLE
tree组件拖动节点之后页面卡死

### ISSUE THREAD

**Issue by kagol** [ant-design/ant-design#37667]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m0b2ho)

### Steps to reproduce

1. 拖动最后一个节点到上一个节点位置
2. 鼠标不松开，停留3s左右松开鼠标

### What is expected?

期望节点拖动到指定位置，页面不卡死

### What is actually happening?

页面卡死

![image](https://user-images.githubusercontent.com/9566362/191404134-97fe976e-c763-4214-93a2-0b0806fa3737.png)

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 16.14.0 |
| System | Windows 10 |
| Browser | Chrome 104.0.5112.81（正式版本） （64 位） |

**Comment by zombieJ** [comment]
删除 codesandbox 中的 console 代码即可，这个是 codesandbox 的 bug，会序列化 console 内容：
https://codesandbox.io/s/tuo-dong-shi-li-antd-4-23-2-forked-q8d444

**Comment by kagol** [comment]
> 删除 codesandbox 中的 console 代码即可，这个是 codesandbox 的 bug，会序列化 console 内容： https://codesandbox.io/s/tuo-dong-shi-li-antd-4-23-2-forked-q8d444

确实是的，刚试了下 codepen 没这问题👍
