### ISSUE TITLE
能在Table的自定义筛选（FilterDropdown）里把关闭筛选的函数也给导出到props吗？

### ISSUE THREAD

**Issue by 1587315093** [ant-design/ant-design#37665]
### What problem does this feature solve?

columns应该就一次处理，然后传递给Table的时候这里业务一般都会将Table加工复用，也就是我在A页面用了加工的Table，如果要操作colums上的属性的话需要再源头传递一个回调函数让深层的filterDropdown组件来触发close，而这个close的逻辑又要来操作colunms上的显隐属性（filterDropdownOpen），我觉得在filterDropdown函数传递的props上可以添加一个closeDropdown，就像你们代码里的triggerVisible函数一样，解决了不用操作columns上的filterDropdownOpen属性。可通过FilterDropdown的子节点来关闭。

组件层级如下 Pgae/MyTable/Filter

### What does the proposed API look like?

filterDropdown函数再多传递一个关闭菜单的选项，亦或者是clearFilters函数多传递个params内部处理关闭
![image](https://user-images.githubusercontent.com/77056991/191398779-7894500b-aa38-4203-ad1f-4e05c5c8a4db.png)
![image](https://user-images.githubusercontent.com/77056991/191398832-74bd53a9-234d-4a03-b96d-826d832b8b37.png)

**Comment by kiner-tang** [comment]
你应该可以使用`confirm`实现你想要的功能：
<img width="812" alt="image" src="https://user-images.githubusercontent.com/10286961/191526332-bdc2d738-a726-4da5-9a85-d16c74b112ec.png">

**Comment by 1587315093** [comment]
closeDropdown参数只有为true时才会去关闭，而且为true它会做一个数据的提交，
还有就是这一块的API能bu'ch'n补充一下文档吗？我都是去看你们源码来猜这些参数的含义。。。
