### ISSUE TITLE
Tree组件拖拽，无法通过拖拽图标拖拽到一级节点

### ISSUE THREAD

**Issue by buyou0821** [ant-design/ant-design#37668]
### Reproduction link

[https://ant.design/components/tree-cn/#components-tree-demo-draggable](https://ant.design/components/tree-cn/#components-tree-demo-draggable)

### Steps to reproduce

官方示例即可复现。
![treedrag](https://user-images.githubusercontent.com/37977488/191404320-e3ad6b6c-ce80-45e8-9682-2237c0c71b2f.gif)

### What is expected?

可通过拖拽图标拖拽到一级节点

### What is actually happening?

无法拖拽到一级节点，只能拖拽到前一个节点的子集

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by buyou0821** [comment]
0-2无法拖拽到0-1同级上方

**Comment by fnoopv** [comment]
试了一下没问题啊，再试试

**Comment by kagol** [comment]
> 0-2无法拖拽到0-1同级上方

我这边需要拖两次，第一次拖动上一级的子节点，第二次从子节点里面拖出来，就能实现0-2无法拖拽到0-1同级上方

**Comment by zombieJ** [comment]
![Kapture 2022-09-21 at 11 23 51](https://user-images.githubusercontent.com/5378891/191407431-fa56ea8b-0204-4062-8e9c-3548fdbc64c0.gif)

**Comment by buyou0821** [comment]
是的需要拖拽两次，这边需要做成仅支持同级拖拽的方式，交互不友好
