### ISSUE TITLE
带页签的Card 组件不应该报Tabs.TabPane is deprecated warning

### ISSUE THREAD

**Issue by poyiding** [ant-design/ant-design#37669]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-ye-qian-de-qia-pian-antd-4-23-1-forked-whsuh5)

### Steps to reproduce

访问即可

### What is expected?

对应带标签页 的 Card组件，内部处理Tabs 的items 逻辑，不应该warning

### What is actually happening?

会报warning ，而且用户无法修改取消它

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 18.0 |
| System | mac |
| Browser | chrome |

**Comment by edc-hui** [comment]
@zombieJ @poyiding 这个问题在4.23.2版本中应该修复了，可看下这个PR #37537

**Comment by poyiding** [comment]
> 

ok
