### ISSUE TITLE
Encountered two children with the same key, `.${elem}`. Child keys must be unique; when two children share a key, only the first child will be used

### ISSUE THREAD

**Issue by pavilionking** [ant-design/ant-design#3766]
#### 发生问题的环境是：

- antd 版本:  2.3.1
- 操作系统及其版本: mac 10.12.1 (16B2555)
- 浏览器及其版本: 54.0.2840.87

#### 您做了什么？请提供尽可能详细的重现步骤。

使用Select 及 Option组件时，使用map返回的数组在DOMWrap里key不唯一，option只返回渲染了第一个

代码：
                      <Select>
                        {
                          list.map(function(elem, idx) {
                            return (
                              <Option key={idx} value={elem}>{elem}</Option>
                            );
                          })
                        }
                      </Select>

报错：
Mention.js?9c0c:44 Warning: flattenChildren(...): Encountered two children with the same key, `.${elem}`. Child keys must be unique; when two children share a key, only the first child will be used.
    in ul (created by DOMWrap)
    in DOMWrap (created by Menu)
    in Menu (created by DropdownMenu)
    in div (created by DropdownMenu)
    in DropdownMenu (created by SelectTrigger)
    in LazyRenderBox (created by PopupInner)
    in div (created by PopupInner)
    in PopupInner (created by Popup)
    in Align (created by Popup)
    in AnimateChild (created by Animate)
    in Animate (created by Popup)
    in div (created by Popup)
    in Popup

**Comment by infeng** [comment]
麻烦提供一个可重现的demo  http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by pavilionking** [comment]
const {
  DatePicker,
  Select,
  Option
} = antd;

const App = React.createClass({
  render() {
    const list = [1, 2, 3, 4, 5, 6];
    return (
      <div style={{margin: 10}}>
        <Select>
          {
            list.map((item)=>{
              return (<Option key={item} value={item}>{item}</Option>)
            })
          }
        </Select>
      </div>
    );
  }
});

ReactDOM.render(<App />, document.getElementById('container'));

**Comment by benjycui** [comment]
@pavilionking 你给的代码无法运行。

我稍微改了点，没有任何问题 http://codepen.io/benjycui/pen/KgPZrE?editors=0011

如果还有问题的话，请重开 issue 并提供可运行的在线 demo 以及重现步骤。

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by motorguo** [comment]
有空我把两端的 demo 都整出来，虽然现在能用。
但是 `.$xx`, `./0` 真的太不爽了。
需要利用 `Menu item` 的 `key` 做些事的时候，`e.key` 取出来的 `.$.$0`

**Comment by saymy** [comment]
遇到同样的问题，你的<Option>如果用MAP实现时，必须有一个key键，同时，你的key的值也是你的value.

这样一个页面就能共享一个数组生成两个以上的select组件。就会报如标题的错误。
