### ISSUE TITLE
Typography.Text with ellipsis: Width of visible text is smaller every time content is updated

### ISSUE THREAD

**Issue by hperronnet** [ant-design/ant-design#37664]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-h1t1b1?file=/index.js)

### Steps to reproduce

1. Create a `Typography.Text` Element with the props `ellipsis` with any function for `onEllipsis` and with a dynamic child content. \
E.g. `ellipsis={{ onEllipsis: () => {} }}`.
2. Change the value of the dynamic child content. Every time the child content of  `Typography.Text` is changed, less and less text is showing.

### What is expected?

In my example, when the child content of a `Typography.Text` is changed, the ellipsis should not show (same behaviour as `Typography.Paragraph`).

### What is actually happening?

In my example, when the child content of a `Typography.Text` is changed, an ellipsis appears and takes one character each time the child content changes. The visible text is also getting smaller and smaller.

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18.2.0 |
| System | Ubuntu 20.04.5 LTS |
| Browser | Firefox Version 104.0, Chrome Version 105.0.5195.125  |

---
After 10-15 updates of the child content, only the ellipsis is showing and the original text is completely gone. \
After some testing, it looks like the bug appeared when antd version 4.18.4 was released (https://ant.design/changelog#4.18.4). \
I also noticed that the `aria-label` attribute is not updating when changing child content.

**Comment by zombieJ** [comment]
Text component do not have default width which need customize width to ensure its ellipsis. We should doc this.
