### ISSUE TITLE
I have a couple of  buttons inside a row but when i press on any button it trigger the onRowClick  but not the button's action

### ISSUE THREAD

**Issue by sarfaraazkhan81** [ant-design/ant-design#37672]
I have a couple of  buttons inside a row but when i press on any button it trigger the onRowClick  but not the button's action

_Originally posted by @ahsanali60 in https://github.com/ant-design/ant-design/issues/16382#issuecomment-808229805_

**Comment by saaadshot** [comment]
Did you find the solution for your issue?

**Comment by ahsanali60** [comment]
`e.stoppropagation()` try writing this on button's onClick, this will prevent calling the parent onClick/onRowClick.
