### ISSUE TITLE
组件props声明补全注释

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#3767]
2.0改用typesscript重写之后，有了齐全的组件属性提示，在用typescript写antd的时候效率高了不少，现在唯一的不足就是很多组件的属性声明缺少注释，很多时候还是要到官网上查看属性的说明，如果能将官网上属性的说明搬到声明上就完美了，注释的写法可以参考[egret](https://github.com/egret-labs/egret-core)的，中英各一份

**Comment by benjycui** [comment]
里面用的 Annotation `@language` `@see` 之类，好像并不是 TypeScript 支持的，就算写了 VSCode 之类的提示里面也是不会出现的。
