### ISSUE TITLE
RangePicker allows selection of range with a disabled day in it

### ISSUE THREAD

**Issue by iliakhubuluri** [ant-design/ant-design#37685]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rangepicker-disabled-date-bug-rnrzgr)

### Steps to reproduce

- Open RangePicker dropdown
- Select any date before any disabled date as a starting date
- Select any date after any disabled date as an ending date

### What is expected?

RangePicker should not allow user to select range with a disabled date

### What is actually happening?

RangePicker will select range with a disabled date

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18.2.0 |
| System | macOS Monterey 12.0.1 |
| Browser | Firefox 104.0.2 (64 bit) |

---
I used RangePicker for booking app. A disabled day means that item is already booked, so any selection which has disabled day in it is not a valid selection. 

At minimum I'd need RangePicker to prevent selection of such ranges.
In best case scenario I would expect RangePicker not to even do hover effect after a disabled day.

**Comment by afc163** [comment]
trace #22912

**Comment by iliakhubuluri** [comment]
Thank you. Closing as duplicate.
