### ISSUE TITLE
Add prop to Card component to control "box-shadow" CSS property   any other component built on a Card (PageHeader, etc)

### ISSUE THREAD

**Issue by jAtlasCode** [ant-design/ant-design#37684]
### What problem does this feature solve?

- Adds more contrast to cards on top of page, especially when white on white, creating a more "elevated" and "3d" look
- Can provide the prop as a number, with varying levels of box-shadow strength (Ex: 1-24)
- Material UI does this with their Paper component for example https://mui.com/material-ui/api/paper/

### What does the proposed API look like?

<Card shadow={10} />
// shadow | integer | defaultValue: 1

/* ex underlying css: 
box-shadow 2px 2px 5px rgba(150, 150, 150, 0.2); 
transition all 0.2s; */

**Comment by afc163** [comment]
You can use `style={{ boxShadow: '2px 2px 5px rgba(150, 150, 150, 0.4)' }}` to customize it.

**Comment by jAtlasCode** [comment]
@afc163 

yeah I understand this, I practically placed that exact code in the issue. Was requesting an additional prop for cards to manage this built in to the API. Plenty of other antd components have a prop that controls easily set css so I figured this would be a great feature addition.
