### ISSUE TITLE
Menu.Item styling issue when not direct child of Menu

### ISSUE THREAD

**Issue by dosmond** [ant-design/ant-design#37686]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lwvv9w?file=/index.js)

### Steps to reproduce

Create a Menu component and two Menu.Item children inside it. Nest one of the Menu.Item children inside another component (div, span, etc). The nested Menu.Item will have the .ant-menu-item-active class.

Also when using a menu as the overlay inside a Dropdown, the nested Menu.Item will have the .ant-dropdown-menu-item-active class.

The data-menu-id will have undefined at the end as well 

e.g `data-menu-id="rc-menu-uuid-27554-1-undefined"` 

### What is expected?

The nested Menu.Item should not have the active status.

### What is actually happening?

The nested Menu.Item has the active status.

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | latest |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
> ## Notes for developers
> * Menu is rendered as a ul element, so it only supports [li and script-supporting elements](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element) as children nodes。Your customized node should be wrapped by Menu.Item.
> * Menu needs to collect its node structure, so its children should be Menu.* or encapsulated HOCs.

ref: https://ant.design/components/menu/#Notes-for-developers
