### ISSUE TITLE
form 表单提交和默认行为不一致

### ISSUE THREAD

**Issue by lengjing** [ant-design/ant-design#37690]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1tcb6g)

### Steps to reproduce

分别点击 submit 按钮

### What is expected?

原生表单行为和 antd 表单行为一致

### What is actually happening?

不一致

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | v18 |
| System | mac os |
| Browser | chrome |

**Comment by MadCcc** [comment]
具体是指哪里不一致？

**Comment by zombieJ** [comment]
Form 里的数据收集会 prevent 默认行为，并转为 `onFinish` 事件。是有意的设计行为哈。

**Comment by lengjing** [comment]
@zombieJ 是否可以加一个 `allow-default-action-when-all-fields-is-valid` 或者 检测到 `method` `action` 字段时允许默认提交

**Comment by zombieJ** [comment]
> @zombieJ 是否可以加一个 `allow-default-action-when-all-fields-is-valid` 或者 检测到 `method` `action` 字段时允许默认提交

主要它的校验是走的 React 生命周期，如果纯粹按照原生 form 的话，那原生 form 的校验能力其实也是没有的。另外对于自定义 `trigger` 的数据收集原生也是做不到的。所以按次强行做成一致也是不恰当的。

**Comment by lengjing** [comment]
> > @zombieJ 是否可以加一个 `allow-default-action-when-all-fields-is-valid` 或者 检测到 `method` `action` 字段时允许默认提交
> 
> 主要它的校验是走的 React 生命周期，如果纯粹按照原生 form 的话，那原生 form 的校验能力其实也是没有的。另外对于自定义 `trigger` 的数据收集原生也是做不到的。所以按次强行做成一致也是不恰当的。

我的理解是: 校验走的表单元素的原生事件( onSubmit onBlur onChange..) 每次 onSubmit 时判断是否允许默认提交应该可以做到的吧，另外原生 form 是有[校验能力](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/form)的只是浏览器提供的功能不是很友好。bty: 默认行为是校验不通过不允许提交
