### ISSUE TITLE
seperate `ButtonGroup` from `Button`, `Menu.Item` from `Menu` and etc 

### ISSUE THREAD

**Issue by xiaofan2406** [ant-design/ant-design#3769]
I think these components should be separated even though they look like they are tightly related.

We should be able to do
```
import { ButtonGroup } from 'antd'`
```
instead of
```
import { Button } from 'antd'`
const ButtonGroup = { Button };
```
Same goes for `Menu`, `SubMenu` and etc.

This allows
- consistent import
- effectively reduce the built size, if a user only uses `Button`, the `ButtonGroup` is still included atm.

I am not sure the reason behind the current setup, am I missing something?

**Comment by afc163** [comment]
I don't think this is a good idea. We seperate components into some main category like Button ( ButtonGroup), Radio(RadioGroup, RadioButton) to avoid fragmentization and make user find it in documentation easierly.

**Comment by kevart** [comment]
I agree with @xiaofan2406 the imports are not intuitive.
