### ISSUE TITLE
InputNumber添加'ant-input'的class，以支持Validator

### ISSUE THREAD

**Issue by YuhangGe** [ant-design/ant-design#377]
InputNumber的`<input>`元素，`className='ant-input-number-input'`扩展为`className='ant-input-number-input ant-input'`。这样才能和Validator配合，使得`.has-error .ant-input`的全局css生效。

**Comment by yiminghe** [comment]
css 上修改下，增加 ant-input-number-input 验证支持  @simaQ

**Comment by simaQ** [comment]
恩，好的
