### ISSUE TITLE
IE11中，Spin始终会显示蒙层

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#3770]
#### 发生问题的环境是：

- antd 版本: 2.3.1
- 操作系统及其版本: Windows 8
- 浏览器及其版本: IE11

#### 您做了什么？请提供尽可能详细的重现步骤。

使用了 Spin

#### 您期待的结果是:

在非loading状态，不应该显示蒙层

#### 实际上的结果是:

在非loading状态下也显示了蒙层

#### 可重现的在线演示

主页就可以重现，找到 loading state 示例，打开调试窗口，inspect 到 `.ant-spin-container`，找到附件图中的代码，check和uncheck `opacity` 属性，你会看到明显的变化
![screen shot 2016-11-09 at 10 34 08 am](https://cloud.githubusercontent.com/assets/1049425/20125421/66476b36-a668-11e6-8ad7-d0c066c0974c.png)

**Comment by ItManTos** [comment]
Chrome下也是这样的，回退到2.2.1版本就好了

**Comment by afc163** [comment]
fixed in #3755

**Comment by afc163** [comment]
@ItManTos Chrome 下有什么问题？@zation 截的那段代码只有 IE 会生效。

**Comment by ItManTos** [comment]
加载动画结束后，模糊化效果没有取消

**Comment by jljsj33** [comment]
@ItManTos chrome是什么版本的？？？？

**Comment by zation** [comment]
我在最新版的 Chrome 下没有发现这个问题，这个问题就先关闭了

**Comment by ItManTos** [comment]
Chrome 版本 47.0.2526.80 (64-bit)    关闭吧，暂时先用2.2.1版本开发，等正式升级的时候，如果有问题再发起新的问题。

**Comment by afc163** [comment]
fixed in 2.4.0
