### ISSUE TITLE
The default rowkey value of the table component should be index for each row

### ISSUE THREAD

**Issue by huhaoda-creat** [ant-design/ant-design#37708]
### What problem does this feature solve?

table中的rowkey如果没有设置应该设置为每一行的index下标，table在接受后端返回的数据时候，有可能没有值唯一的字段，这就导致了rowkey无法取值的现象

### What does the proposed API look like?

rowKey={(r,i)=>i.toString()}

**Comment by afc163** [comment]
Table 列表数据需要唯一的 key，否则不应该用 Table 来展现。如果服务端未返回可以自行前端加上 index，但还是建议和后端讨论一下，数据不可能没主键的。
