### ISSUE TITLE
mention无法搜索英文名，一输入空格就停止搜索了

### ISSUE THREAD

**Issue by into-piece** [ant-design/ant-design#37714]
### What problem does this feature solve?

解决mention组件输入英文名的时候遇到空格无法继续搜索的问题。

### What does the proposed API look like?

新增一个allowSpaceInQuery，@中输入空格还可以继续搜索

**Comment by zombieJ** [comment]
感觉不需要加这个属性，如果匹配的内容里有空格就继续匹配即可。需要优化一下。

**Comment by into-piece** [comment]
> 感觉不需要加这个属性，如果匹配的内容里有空格就继续匹配即可。需要优化一下。

感谢回复，发现已有的validateSearch属性可以解决这个问题
