### ISSUE TITLE
The delay property of the Button component is invalid

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#37719]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jia-zai-zhong-zhuang-tai-antd-4-23-2-forked-odxiy8)

### Steps to reproduce

```jsx
<Button loading={{ delay: 3000}}>click</Button>
```
The Button will immediately enter the loading state

### What is expected?

Button waits 3s before entering the loading state

### What is actually happening?

The Button will immediately enter the loading state

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 16.8.6 |
| System | windows11 |
| Browser | Google 100.0.4896.60 |

**Comment by MadCcc** [comment]
https://codesandbox.io/s/jia-zai-zhong-zhuang-tai-antd-4-23-2-forked-9lwvnl?file=/demo.js
You need to set `loading` dynamically.
