### ISSUE TITLE
SliderRangeProps type not properly exported

### ISSUE THREAD

**Issue by CBiglemon** [ant-design/ant-design#37723]
### What problem does this feature solve?

For the slider component, there are two available interfaces in TypeScript. SliderSingleProps and SliderRangeProps. The former is properly exported and can be imported, but the latter can not in a react/typescript project. It is troublesome, but very easy to fix as I did it locally on my machine in a few seconds.

### What does the proposed API look like?

All that is needed is to add "SliderRangeProps" in the export type inside the index where all the exports are.

```js
export type { SliderSingleProps, SliderRangeProps } from "./slider";
```

And then SliderRangeProps will be available for us and used to define Typescript interfaces.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/7846d69bbf7ded0c46fd90041470bb16303145e9/components/slider/index.tsx#L85

**Comment by JON418** [comment]
> https://github.com/ant-design/ant-design/blob/7846d69bbf7ded0c46fd90041470bb16303145e9/components/slider/index.tsx#L85

The missing export is actually here https://github.com/ant-design/ant-design/blob/7846d69bbf7ded0c46fd90041470bb16303145e9/components/index.tsx#L125
