### ISSUE TITLE
Input输入框文档 输入时格式化展示案例精度问题

### ISSUE THREAD

**Issue by feightwywx** [ant-design/ant-design#37725]
### Reproduction link

[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce

在输入框中输入超过16位的数字

### What is expected?

完整的格式化数字，或者限制输入长度

### What is actually happening?

过长数字被补零、舍入

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18.3.0 |
| System | macOS 12.6 |
| Browser | Google Chrome 105.0.5195.125 |

---
本案例使用`Intl.NumberFormat().format()`进行数字的格式化，该方法存在的精度限制导致了问题发生。
能否修改该案例中Input组件`maxLength`的值，或是在案例描述中增加一个注解说明此问题？

**Comment by afc163** [comment]
你说的是 https://ant.design/components/input-cn/#components-input-demo-tooltip 这个例子吧？

**Comment by afc163** [comment]
我加个 maxLength
