### ISSUE TITLE
antd 4.23版本后Tabs组件给Tabs.TabPane加上 display: flex css属性多个TabPane 会导致内容展示错误（全部内容都展示出来了）

### ISSUE THREAD

**Issue by yl196356303** [ant-design/ant-design#37722]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-740h21?file=/index.js)

### Steps to reproduce

1、点击项目一
2、点击项目二

### What is expected?

点击项目二期望项目一隐藏

### What is actually happening?

点击项目二期望项目一没隐藏

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | react18x |
| System | win10 |
| Browser | chrome任意版本 |

**Comment by afc163** [comment]
不要覆盖 display 属性，4.22.x 也会有问题的：https://codesandbox.io/s/antd-reproduction-template-forked-txyofk?file=/package.json
