### ISSUE TITLE
Ant Design Tabs dynamically changes id when clicking back button

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#37732]
### Reproduction link

[https://oyzw45.csb.app/user](https://oyzw45.csb.app/user)

### Steps to reproduce

1. Click the reproduction link once the sandbox has loaded you can see that the tabs has a background color
2. Click any items in the sidebar menu then click the back button of the browser. You can see that the background color of the tab is missing due to the id being changed

### What is expected?

Should retain the id of the tab pane

### What is actually happening?

Tab pane id dynamically changes every time the back button is being clicked

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 17.0.2 |
| System | Mac Os Monterey |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
Do not deps on the auto generate id if you want to have style override. Just give Tab a customize `id`:
https://codesandbox.io/s/custom-trigger-antd-4-22-5-forked-4svrgy
