### ISSUE TITLE
Affix包含div时报`findDOMNode is deprecated in StrictMode`

### ISSUE THREAD

**Issue by AlMiraiABC** [ant-design/ant-design#37731]
### Reproduction link

这是匿名账户链接，不保证可用性
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-23-2-forked-fdvo4s)

### Steps to reproduce

1. 创建组件，返回div
2. Affix包含该组件

### What is expected?

log nothing

### What is actually happening?

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18.2 |
| System | Windows 11 家庭中文版 21H2 |
| Browser | Edge 105.0.1343.33 (正式版本) (64 位) |

---
渲染正常，功能正常，不是error

**Comment by zombieJ** [comment]
`forwardRef`:

https://codesandbox.io/s/ji-ben-antd-4-23-2-forked-fr6qzx?file=/demo.js
