### ISSUE TITLE
antd input输入emoji长度不一致

### ISSUE THREAD

**Issue by linnaMao** [ant-design/ant-design#37733]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-bird-7oysuv?file=/src/App.tsx)

### Steps to reproduce

第一种
1 输入👩‍👩‍👧‍👧 显示长度为7
2 随便输入字符 只能输入9个 

第二种
1 输入🎸 显示长度为1
2 只能输入18个 

### What is expected?

我认为期望的结果如果是让用户感知不到emoji的长度的话(也就是无论什么情况下emoji长度都为1) 那么显示的showCount和输入的长度应该一致

如果是要感知到emoji的长度的话 第一种输入应该能够输入13个字符,而不是9个,并且🎸显示的长度在showCount上为2,但是实际上是1

### What is actually happening?

第一种输入 如果👩‍👩‍👧‍👧长度为7 ,输入该emoji后只能输入9个
第二种 可以理解为🎸的长度为2 所以能输入18个字符 

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 16.14.0 |
| System | Windows 11 企业版 |
| Browser | chrome |

**Comment by afc163** [comment]
有点意思。

```jsx
[...'👩‍👩‍👧‍👧'].length // 7
'👩‍👩‍👧‍👧'.length // 10
```

**Comment by linnaMao** [comment]
> 有点意思。
> 
> ```js
> [...'👩‍👩‍👧‍👧'].length // 7
> 
> '👩‍👩‍👧‍👧'.length // 11
> ```
所以这个问题还是输入框和showCount获取的length不一致导致的。。。

**Comment by zeroter** [comment]
![image](https://user-images.githubusercontent.com/31180239/192935090-a7b27b0e-feae-4fb1-9925-59cc4f96db7f.png)
还有为什么input 和 textarea 同样的设置showCount 与 maxLength , 实际能输入的长度不一致？

**Comment by linnaMao** [comment]
> 👩‍👩‍👧‍👧

因为textarea是有做处理的 但是input没做 ，textarea就相当于将输入字符串转为数组的形式计算了
![7EA7A987-E133-4e13-B0AE-B0D40CAEAAE9](https://user-images.githubusercontent.com/46858441/192952959-bbfd9b7f-d04c-4677-9c0c-448880b459a1.png)

![image](https://user-images.githubusercontent.com/46858441/192953092-7b3bc2ee-89f7-40fe-8493-1062f9a34ab2.png)

![CE04D37F-BFD8-4606-BA2E-F5856CE1F917](https://user-images.githubusercontent.com/46858441/192952915-4832a0da-3b8d-4208-b772-4d382ab4972d.png)

**Comment by linnaMao** [comment]
> ![image](https://user-images.githubusercontent.com/31180239/192935090-a7b27b0e-feae-4fb1-9925-59cc4f96db7f.png) 还有为什么input 和 textarea 同样的设置showCount 与 maxLength , 实际能输入的长度不一致？

主要原因在于value的截取处理，textarea里是有根据value和解构和maxLength进行截取的，但是input里对value是没有处理的，所以展示当出现emoji的时候就会不一样
![image](https://user-images.githubusercontent.com/46858441/192974229-de45791a-aff3-4b2c-8891-9e7f27e240bd.png)

![image](https://user-images.githubusercontent.com/46858441/192974284-1a79970d-0e03-4d6c-a66d-0d8e0be09045.png)

**Comment by zeroter** [comment]
由于后端对字符数的要求，按照textarea最大长度来计算，就会超过后端的要求长度，所以就不能使用maxLength。反而是input的长度是和后端吻合的，只需要自定义一下showCount

**Comment by afc163** [comment]
看上去可以试试 https://www.npmjs.com/package/runes

**Comment by igelar** [comment]
![image](https://user-images.githubusercontent.com/17963370/224218876-a081df46-6bc8-4dbe-8086-16e76468f8a9.png)

**Comment by archisketch-thangly** [comment]
This issue was created very long time.

So, When do you fix it?
Or how can i fix it?

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/45140
![image](https://github.com/ant-design/ant-design/assets/27722486/811d4d85-6534-4ca8-95e9-d2d7088ad3df)

**Comment by yoyo837** [comment]
<img width="609" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/68d84a61-e1b3-42be-960b-16f0573949b7">

那这个呢 @MadCcc

**Comment by MadCcc** [comment]
> 那这个呢

count 支持自定义计算长度的，可以配合三方库使用

**Comment by chenyajun-create** [comment]
不要使用maxLength，使用 normalize。

参考代码：
/** 按 Unicode code point 计算字符数，正确处理 emoji surrogate pair */
const getCharLength = (str: string): number => Array.from(str).length;

/** 按 Unicode code point 截断字符串，避免截断 emoji */
const sliceByChar = (str: string, maxLen: number): string =>
  Array.from(str).slice(0, maxLen).join('');

` <Form.Item
              normalize={(value: string) =>
                value && getCharLength(value) > MAX_CONTENT_LENGTH
                  ? sliceByChar(value, MAX_CONTENT_LENGTH)
                  : value
              }
            >
              <Input.TextArea
                autoSize={{ minRows: 6 }}
              />
            </Form.Item>`
