### ISSUE TITLE
Table "filterDropdown": pressing enter on filter's search Input will also trigger column sorting when enabled

### ISSUE THREAD

**Issue by freshgiammi** [ant-design/ant-design#37742]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-table-with-sorting-and-filter-issue-f7pu6r?file=/demo.js)

### Steps to reproduce

1. Open filter search box
2. Type anything (typing nothing is fine too)
3. Press enter
4. Data is filtered, but sort order is changed too

### What is expected?

Table is expected to get filtered, but sorting should not change because we're not pressing enter on the header (it should be the Input field)

### What is actually happening?

An event is propagated to the table header as well, resulting in a onPressEnter event of the table header, which triggers a change in the sorter options.

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18.3.0 |
| System | Windows 10 |
| Browser | Firefox 106 |

---
Apparently this was not happening on antd v3, as per this sandbox: https://codesandbox.io/s/y7kxxr1n8z

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-table-with-sorting-and-filter-issue-forked-evcc4r?file=/demo.js

**Comment by freshgiammi** [comment]
Thank you for the help. I think it would be a good idea to add sorting and the `onKeyDown` prop to the example this codebox was taken from (https://ant.design/components/table/#components-table-demo-custom-filter-panel),, so that the documentation can clarify this behaviour for future users.
