### ISSUE TITLE
表格没有 cell edit 功能

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3774]
#### 发生问题的环境是：

- antd 版本:ant design 2.0.1
- 操作系统及其版本:windows 10
- 浏览器及其版本:chrome 最新版

#### 您做了什么？请提供尽可能详细的重现步骤。

引入表格，点击某个单元格的时候，可以对该单元格进行编辑而不是一整行进行编辑
这样的话，需要最起码提供一个 cell click事件，但是没有

#### 您期待的结果是:

表格有 cell edit 功能，或cell click事件

#### 实际上的结果是:

表格没有 cell edit 功能

#### 可重现的在线演示

官网即可

**Comment by benjycui** [comment]
表格本身就没有这个功能，demo 在增加了，trace: https://github.com/ant-design/ant-design/issues/3562

**Comment by afc163** [comment]
我到 rc-table 里加一个单元格 click 事件。
