### ISSUE TITLE
tree 缓存问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#37752]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-23-2-forked-ymxiuc?file=/demo.js)

### Steps to reproduce

例如筛选2，随便去除勾，key返回不对

### What is expected?

返回正确的 key

### What is actually happening?

返回了错误的 key

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 16.8.0 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
你的 Tree 里没有这个节点，当然 checkedKeys 不会包含它了。Tree 永远以当前 treeData 为准。
