### ISSUE TITLE
InputNumber精度丢失问题

### ISSUE THREAD

**Issue by yuehaocc** [ant-design/ant-design#37753]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-23-2-forked-765bhj)

### Steps to reproduce

- 先输入6位小数，比如0.999999
- 再更新整数位为10位整数，比如9999999999
- 当整数位从9增至10时，小数最后一位变为8，光标也移至最后一位。此时删除重新输入最后一位小数数字也会跳

### What is expected?

小数位不变，数字精度不丢失

### What is actually happening?

当整数位从9增至10时，小数最后一位变为8，光标也移至最后一位。

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 16.14.0 |
| System | macOS 12.5.1 |
| Browser | Chrome 105.0.5195.125（正式版本） (x86_64) |

---
我同时在上面的codesandbox最小复现中，还提供了原生input number的例子，原生中没有问题。

**Comment by zombieJ** [comment]
使用 `stringMode`

**Comment by yuehaocc** [comment]
> 使用 `stringMode`

因为需求是6位小数，6位小数就要用stringMode吗
