### ISSUE TITLE
ant table 滚动功能异常,scroll中，同时设置x和y，x会失效

### ISSUE THREAD

**Issue by maoguotai** [ant-design/ant-design#37750]
### Reproduction link

[https://官方提供的任何一个table都有此问题.com](https://官方提供的任何一个table都有此问题.com)

### Steps to reproduce

为table的scroll属性，同时设置x和y，x的设置会失效，例如 scroll={{ x: 'max-content', y : 200 }};此时y生效，x失效；但只设置x或者只设置y是没有问题的

### What is expected?

能够同时设置x和y

### What is actually happening?

单个设置没问题，同时设置仅有y生效

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 17.0.2 |
| System | windows |
| Browser | chrome 105.0.5195.127 |

**Comment by heqiaoyun** [comment]
请问解决了吗，我也遇到了同样的问题
