### ISSUE TITLE
notification 怎么能根据状态自动open？ 

### ISSUE THREAD

**Issue by jindada** [ant-design/ant-design#3775]
#### 发生问题的环境是：

antd 版本: 2.2.0
操作系统及其版本: mac
浏览器及其版本: chrome

![image](https://cloud.githubusercontent.com/assets/16317349/20130279/bab7c1de-a690-11e6-9943-178ff63096c2.png)

#### 您期待的结果是:

显示正常  但是有报错

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/16317349/20130293/dc0ef208-a690-11e6-9165-f3dc1dceee12.png)

**Comment by benjycui** [comment]
就是字面的意思，在 `componentDidMount` 里面处理。

**Comment by jindada** [comment]
我用的无状态函数写的组件 没有生命周期
