### ISSUE TITLE
form 表单使用InputNumber组件 数字过大 输入内容会被组件修改成不一样的数字

### ISSUE THREAD

**Issue by rabZhang** [ant-design/ant-design#37765]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-xiao-yan-gui-ze-antd-4-23-2-forked-oxbohw?file=/demo.js)

### Steps to reproduce

在form 表单使用InputNumber组件 inputNumber输入数字过大会被转成带有e的数字缩写 以及会把某些订单号改成不同的单号 （参考测试数据2022092700000000135 ）复制进入时 会被组件强行改成 2022092700000000300

### What is expected?

输入常串数字 2022092700000000135 （订单号时）为数字number格式

### What is actually happening?

返回的是被修改的订单号 2022092700000000300 导致定位不到 

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | react |
| System | mac window |
| Browser | all |

**Comment by rabZhang** [comment]
https://codesandbox.io/s/dong-tai-xiao-yan-gui-ze-antd-4-23-2-forked-oxbohw?file=/demo.js
在线测试

**Comment by afc163** [comment]
订单号应该是字符串，建议用 Input，不应该用 InputNumber。

InputNumber 是用于可计算的数字量，由于 js 精度问题，不支持超长大数。
