### ISSUE TITLE
Form.List 设置initialValue无效

### ISSUE THREAD

**Issue by wes0310** [ant-design/ant-design#37772]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-zeng-jian-qian-tao-zi-duan-antd-4-23-2-forked-m5rldu?file=/demo.js:997-1016)

### Steps to reproduce

页面打开展示无效

### What is expected?

initialValue能正常使用

### What is actually happening?

initialValue设置无效

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 16.14.0 |
| System | Mac OS 10.15.7 |
| Browser | Chrome 94.0.4606.71 |

**Comment by afc163** [comment]
```diff
                  getValueProps={(value) => ({
                    style: {
                      color: "red"
                    },
+                   value,
                  })}
```
