### ISSUE TITLE
App crash when using Select (`tags` mode) with google translate extension

### ISSUE THREAD

**Issue by ds1371dani** [ant-design/ant-design#37779]
### Reproduction link

[https://rleyf8.csb.app/](https://rleyf8.csb.app/)

### Steps to reproduce

1. open this page with google chrome
2. activate google translate extension to translate to English on this page
3. inside the Select component write oi
4. wait for the extension to translate the select option to hi
5. remove oi
6. do the 2-5 steps again and the app will crash

### What is expected?

Not crashing

### What is actually happening?

```
NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 18.3.0 |
| System | Ubuntu |
| Browser | Google Chrome Version 105.0.5195.125 |

---
I had this recurring error in my sentry logs and for a long time I wasn't able to reproduce it until I found out that it was related to some extensions mutating the dom.

This is my reproduction code in [codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-rleyf8?file=/index.js), but since google translate extension wasn't working on the iframe please use the above link to reproduce the bug.

I don't know why, but the crash happens on the second try.

**Comment by zombieJ** [comment]
https://github.com/facebook/react/issues/11538#issuecomment-417504600
