### ISSUE TITLE
Cascader support grouped options

### ISSUE THREAD

**Issue by sxlwar** [ant-design/ant-design#37771]
### What problem does this feature solve?

the option can be grouped 

### What does the proposed API look like?

```ts
interface Options {
     label: React.ReactNode;
    value?: string | number | null;
    children?: DefaultOptionType[];
    group?: string | React.ReactNode;
}
```

**Comment by afc163** [comment]
设计上什么样？

**Comment by sxlwar** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/20088392/199663236-8b307d6c-e498-4f82-b659-eed2cc4be1b8.png">
类似这种，当然这里似乎看来起来不太有必要，完成可以移到上一层，但有时候分类的维度不一样
