### ISSUE TITLE
transfer onSearch搜索框异步搜索改变dataSource造成右边已选中的不显示 状态是已选中的状态

### ISSUE THREAD

**Issue by a1021427201** [ant-design/ant-design#37776]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-field-i0v9rh?file=/demo.js)

### Steps to reproduce

选中左边 移到右边 搜索

### What is expected?

左边不显示  右边已经选中的还显示

### What is actually happening?

左边没显示 右边也没显示

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 17 |
| System | mac |
| Browser | 无关 |

---
左边搜索如果改变dataSource会影响右边

**Comment by kiner-tang** [comment]
是你的实例有问题，搜索的时候为何要手动情况？
<img width="621" alt="image" src="https://user-images.githubusercontent.com/10286961/193244568-d8077db2-52ad-4bf3-9e3f-0604aad6fe4b.png">
