### ISSUE TITLE
升级2.3.0后 Select 的搜索输入框无法输入,点击会失去焦点

### ISSUE THREAD

**Issue by deerW** [ant-design/ant-design#3778]
#### 发生问题的环境是：

- antd 版本: 2.3.0
- 操作系统及其版本: mac
- 浏览器及其版本: chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

cnpm i antd
<Select> onSelect API 点击无法输入搜索内容便会失去焦点

#### 您期待的结果是:

像官网一样正常使用 可以输入搜索内容
![image](https://cloud.githubusercontent.com/assets/20079361/20135009/939afdd8-a6a8-11e6-97d9-9d8682e0b250.png)

#### 实际上的结果是:

无法输入要搜索的内容 直接失去焦点

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by deerW** [comment]
http://codepen.io/DeerW/pen/bBVzbL?editors=1111
多次点击下拉框下拉箭头，会出现下拉框打开马上合上的情况；
当选中某一项后，再想输入搜索时，点击框体，无法输入，只有点击下拉箭头才可再次输入，使用起来感觉是适度差点。

**Comment by RaoHai** [comment]
https://github.com/react-component/select/blob/master/src/Select.jsx#L532-L538

感觉这段逻辑很费解……

**Comment by HengCC** [comment]
@deerW 确实是这样的. 我今天发现了这个问题.  即使是点击下拉箭头也要点击2次才能够下拉出数据

我尝试了降版本. react->0.14.8 , antd->2.2.0  用这样的版本组合后是没有问题的.  但是升级了 react->15版本后就会出现这样的问题. 不管 antd 是2.2 还是2.3的.

**Comment by afc163** [comment]
我发现点击箭头时，有时候会弹出后立刻收起。

**Comment by joe-sky** [comment]
我使用2.3.1版也遇到了同样的问题，只有设置了`showSearch`属性才会触发。而且在**没有选中下拉框列表中的某一项之前**是不会秒收回的；但是只要**选中了一项后再点开下拉框**就每次都会出现这个问题。

**Comment by ystarlongzi** [comment]
这次升级后，下次再也不敢随随便便升级了。。。

**Comment by benjycui** [comment]
@ystarlongzi 这次的是底层组件 patch 版导致，只要重装依赖都会碰到。。

**Comment by mochase** [comment]
碰到同样问题了,目前有什么好的解决方法吗

**Comment by afc163** [comment]
升级到 2.4.2 即可。
