### ISSUE TITLE
直接展示的级联面板

### ISSUE THREAD

**Issue by bai123bai123** [ant-design/ant-design#37787]
### What problem does this feature solve?

如果使用css 隐藏 select 框，感觉会有性能影响

### What does the proposed API look like?

CascaderPanel

**Comment by afc163** [comment]
为啥需要这个能力，业务场景是什么？

**Comment by bai123bai123** [comment]
![image](https://user-images.githubusercontent.com/114127490/192935756-ec064673-16bc-4cf8-9d54-56cc67e7d251.png)
类似3个list，第一层有 children，那么就可以展开，看到第二层 list 内容

**Comment by bai123bai123** [comment]
![image](https://user-images.githubusercontent.com/114127490/192936035-4fa72d47-d6e4-4e3c-905f-1ed081fd2b50.png)
类似这样 3 个list，有 children，展示第二个 list，每一项有单独操作，也可以进行选中，也可以进行编辑

**Comment by afc163** [comment]
没理解，这个感觉更像是 Tree？

**Comment by bai123bai123** [comment]
更类似直接展示的级联面板
![image](https://user-images.githubusercontent.com/114127490/192953544-02ccf7d3-7a56-48b0-8aec-4b66d96026dd.png)
和这个组件类似的效果

**Comment by afc163** [comment]
为啥要直接展示，浮层显示会有什么问题？

**Comment by bai123bai123** [comment]
![image](https://user-images.githubusercontent.com/114127490/192953789-ed2f84d3-224e-4e3c-b5b2-14cbc7a5efdb.png)

**Comment by bai123bai123** [comment]
就是想问一下，会支持这个组件吗？

**Comment by bai123bai123** [comment]
直接浮层，上面的 input 框需要手动利用 css，隐藏起来，而且下面的选择上面会有交互，这样性能会不会有浪费呢

**Comment by afc163** [comment]
为啥要隐藏起来呢？ bordered={false} 隐藏掉边框就行了。

我其实想问的是这里直接用 <Cascader /> 有啥问题？

**Comment by bai123bai123** [comment]
bordered={false} 这样，触发的 select 还是存在的，我想直接使用，级联面板里面的内容，不想展示 select 触发

**Comment by MadCcc** [comment]
暂无计划支持非浮层的 Cascader

**Comment by yaya1286249672** [comment]
想问下你最后咋解决的   我们也有这个场景 非弹层的级联面板
