### ISSUE TITLE
table 是否应该可以支持一下垂直居中。现在就只有align。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#37785]
### What problem does this feature solve?

table 是否应该可以支持一下垂直居中。现在就只有align。

### What does the proposed API look like?

vertical-align 的参数。支持top ,bottom ,center

![image](https://user-images.githubusercontent.com/8272614/192927747-2d315a40-169e-4e41-b477-2cfff8675d56.png)

**Comment by afc163** [comment]
使用 onCell 可以设置自己需要的 style 属性。
