### ISSUE TITLE
Cascader 级联选择能否禁用一级节点，选择下级节点

### ISSUE THREAD

**Issue by liuhanbingdabendan** [ant-design/ant-design#37797]
### What problem does this feature solve?

有的用户不能够使用父节点的功能，但是需要有子节点的某个功能

### What does the proposed API look like?

类似与element的checkStrictly 的api，父子不关联，父节点禁用的情况下，仍可选择子阶段

**Comment by afc163** [comment]
父节点禁用如何选中子节点？

**Comment by MadCcc** [comment]
如果“有的用户不能够使用父节点的功能，但是需要有子节点的某个功能”，那这个功能可能不太适合用 Cascader
