### ISSUE TITLE
Table的defaultExpandAllRows应该支持修改dataSource的场景

### ISSUE THREAD

**Issue by heromac** [ant-design/ant-design#37794]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-onbrnu)

### Steps to reproduce

Table设置defaultExpandAllRows，通过异步设置dataSource后，table行不能自动展开。

### What is expected?

通常表格中的数据都是通过接口从后端获取后，再设置dataSource，希望此场景下defaultExpandAllRows属性能够起作用，即表格展开所有行。

### What is actually happening?

表格未能展开所有行。

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 18 |
| System | mac os 12.4 |
| Browser | chrome 105 |

---
使用defaultExpandAllRows属性，意图是拿到后端数据在表格中渲染时可以默认展开所有选项。实际上，defaultExpandAllRows只能支持渲染表格时就已经拿到数据，而通过修改dataSource后就不再有效。

**Comment by afc163** [comment]
Duplicate of #37793

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24559#issuecomment-635726149
