### ISSUE TITLE
Typography在同时支持copyable和ellipsis且子元素设置font-size: 12px时，展示不全

### ISSUE THREAD

**Issue by Ivan-zyl** [ant-design/ant-design#37791]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sheng-lue-zhong-jian-antd-4-23-3-forked-lx30f4?file=/demo.js)

### Steps to reproduce

打开链接就能看到，去掉font-size: 12px，就正常了

### What is expected?

任意font-size展示正常

### What is actually happening?

font-size: 12px展示不正常

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 18  |
| System | mac |
| Browser | chrome |

**Comment by Ivan-zyl** [comment]
估计是上次这行代码引起的，去掉这行就正常了。希望能帮到你们
https://github.com/ant-design/ant-design/blob/master/components/typography/Base/Ellipsis.tsx#L175

**Comment by afc163** [comment]
@zheeeng 看看

**Comment by zheeeng** [comment]
Reproduction 里的用的是 maxWdith 不是 width，改成 12px 没有 reproduction 里的问题，但感觉可能还会在某些情况下有问题，待测试。

用 maxWdith，在 Walking State 这一行传入的 width 一直变化，这是上面这个推论的原因：
https://github.com/ant-design/ant-design/blob/master/components/typography/Base/Ellipsis.tsx#L69

**Comment by zheeeng** [comment]
1. 设置了 maxWidth
2. 设置在 Text 上的 font-size 小于 measurement 使用的 font-size

会导致实体的宽度一直变小，触发 ResizeObservable 一直改变传入 Ellipsis 的 wdith 变化，walk state 总是在 prepare 阶段。

改变 font-size 为 12 可行吗？可行，也不可行，12 在当前 reproduction 中 ResizeObservable 大约会触发2次就可以进入 walk 阶段。大部分情况 ok，效果可以接受。

一般来说，chrome 的最小字体大小是 12px。写死 12 可以满足大多情况。但是当 chrome 被用户设置过字体超小时，最小字体会小于 12px，Text 上的字体大小再小于 12px 时仍然出现这个 bug。

可以更完备的 fix 方法是在 ResizeObservable 更新 width 时传入 font-size 计算小于等于当前 font-size 的最大偶数 font-size
