### ISSUE TITLE
Dropdown.Button

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3779]
at documentation for **Dropdown.Button** we have:
1. onVisibleChange
2. visible

In reality these props are not using. So need to fix documentation or component.

**Comment by benjycui** [comment]
This commit breaks it https://github.com/ant-design/ant-design/commit/0edd5ada9af1b68f7e6cbb1d8513e857d19d4c42

**Comment by yesmeck** [comment]
这个我来修吧
