### ISSUE TITLE
Table的defaultExpandAllRows

### ISSUE THREAD

**Issue by heromac** [ant-design/ant-design#37793]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-onbrnu)

### Steps to reproduce

Table设置defaultExpandAllRows，通过异步设置dataSource后，table行不能自动展开。

### What is expected?

通常表格中的数据都是通过接口从后端获取后，再设置dataSource，希望此场景下defaultExpandAllRows属性能够起作用，即表格展开所有行。

### What is actually happening?

表格未能展开所有行。

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 18 |
| System | mac os 12.4 |
| Browser | chrome 105 |

---
使用defaultExpandAllRows属性，意图是拿到后端数据在表格中渲染时可以默认展开所有选项。实际上，defaultExpandAllRows只能支持渲染表格时就已经拿到数据，而通过修改dataSource后就不再有效。

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11615

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10588#issuecomment-390542477

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24559#issuecomment-635726149
