### ISSUE TITLE
InputNumber的键盘交互问题

### ISSUE THREAD

**Issue by YuhangGe** [ant-design/ant-design#378]
设置InputNumber的min=8, max=12。当值为8, 9时，能够键盘删除；删除后，能够录入8或9，但不能更大数字。此外，当值为10以上时，也不能删除。

感觉这个交互会比较让人迷惑。

**Comment by jiehe** [comment]
inputnumber 还有个onchage参数问题哦，遍历数组生成的inputnumber触发onchange的时候并不能拿到相应的遍历item，导致inputnumber 变化的时候不能修改model， 所以也不好setstate。

**Comment by YuhangGe** [comment]
@jiehe 不能拿到相应的遍历item是指？能贴个简单代码不？

**Comment by YuhangGe** [comment]
@afc163 @yiminghe 两位怎么看这个键盘交互问题呀？代码逻辑是不允许用户录入小于'min'的数字，但用户想要把12改成11的时候，这个逻辑又会让用户无法最顺畅地操作。用户是想先删掉2，再输入1；但我们认为它删掉2后剩下的1小于了min不合法。

**Comment by yiminghe** [comment]
这个业界其他组件怎么做的？ @YuhangGe  调查下？

**Comment by YuhangGe** [comment]
@yiminghe chrome浏览器原生的input[type=number]键盘录入时，只限定不能输入非数字字符，但min, max是不检查的。点击上下箭头时会有约束。

我觉得InputNumber组件也可以考虑键盘录入时不对min, max检查。业务上有需要时，只要和Validator结合起来就行了。

**Comment by afc163** [comment]
先保留现状吧。
