### ISSUE TITLE
使用了ie不支持的startswith方法

### ISSUE THREAD

**Issue by bingotao** [ant-design/ant-design#3780]
#### 发生问题的环境是：

- antd 版本:2.3.2  在线版
- 操作系统及其版本:win7 64
- 浏览器及其版本:IE edge

**Comment by yesmeck** [comment]
见 https://github.com/ant-design/ant-design/issues/3400 ，https://github.com/ant-design/ant-design/commit/a7b384112e3195588836dc90d08a209ac2441ae4#comments

**Comment by yesmeck** [comment]
https://ant.design/docs/react/getting-started?locale=zh-CN#兼容性
