### ISSUE TITLE
select自定义下拉菜单嵌套tabs，当tabs过多时，点击更多按钮popup中的选项，下拉菜单自动关闭

### ISSUE THREAD

**Issue by OuZeWei** [ant-design/ant-design#37803]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-39m514?file=/index.js)

### Steps to reproduce
Select the custom drop-down menu nested tabs, when there are too many tabs, click the More button popup option，the drop-down menu closes automatically
select自定义下拉菜单嵌套tabs，当tabs过多时，点击更多按钮popup中的选项，下拉菜单自动关闭

### What is expected?
tab can be toggled and the drop-down menu is not closed
tab能够切换，且下拉菜单不关闭

### What is actually happening?
the drop-down closed
下拉菜单关闭

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 18 |
| System | windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
月经问题，看来要加个 FAQ 了：

https://codesandbox.io/s/antd-reproduction-template-forked-nbo8do?file=/index.js
