### ISSUE TITLE
react-activation 配合使用，恢复缓存后Button会意外的出现loading效果

### ISSUE THREAD

**Issue by Cool-Star** [ant-design/ant-design#37818]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-q3c2xf?file=/index.js)

### Steps to reproduce

1.点击toggle关闭组件
2.等待5s，再次点击toogle

### What is expected?

正常显示，没有loading的过度效果

### What is actually happening?

会出现意外的loading效果

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | windows |
| Browser | chrome |

---
PS: 快速点击，并不会有此问题。
实际应用场景中，恢复缓存时，toolTip,modal的遮罩层，dropDown  都会短暂的出现闪烁后再消失，在此最小demo中没有复现。

观测dom元素显示的时候，会有动画过度的class短暂出现并消失。

**Comment by guoguoqiqi** [comment]
请问这个问题解决了吗，如何解决的呢？

**Comment by zhenwei12138** [comment]
有解决方法吗？
