### ISSUE TITLE
treeSelect组件禁用问题

### ISSUE THREAD

**Issue by cainiaozhilu** [ant-design/ant-design#3781]
#### 发生问题的环境是：

- antd 版本:2.1
- 操作系统及其版本:windows7
- 浏览器及其版本:谷歌

treeSelect组件能不能只禁用右边的点击事件，而不是disable只能全部禁用（向下的箭头：展开功能，复选框。以及点击事件） 我想只禁用某一层的点击事件，无法实现。感谢

**Comment by benjycui** [comment]
`Tree.Node` 的 `title` 可以时一个 `React.ReactNode`，把其设为 `<span disable>{title}</span>` 之类即可。

**Comment by benjycui** [comment]
优先考虑组合。

**Comment by benjycui** [comment]
不好使。。

试了下面几种方法：

```jsx
<span disabled>
<span style={{ pointerEvents: 'none' }}>
<span onClick={(e) => e.nativeEvent.stopImmediatePropagation()}>
```

**Comment by benjycui** [comment]
> 我想只禁用某一层的点击事件

业务场景是什么？

**Comment by cainiaozhilu** [comment]
@benjycui 
需求就是这个样子
![a05f tmp](https://cloud.githubusercontent.com/assets/23371312/20166954/1819f546-a753-11e6-8a26-fae5737e5896.jpg)

感谢

**Comment by benjycui** [comment]
TreeNode 的选中也就是加个背景色，所以其实你是要禁用这个行为么？

不要假设别人知道你的需求背景，这东西描述越详细越好。

**Comment by cainiaozhilu** [comment]
@benjycui 
是呀  我现在的需求是禁用所有和Node1同级的click事件，然后其它所有的功能都正常使用   TreeSelect里面的数据都是动态生成的，我现在是用disable来禁用，但是这样之后，展开功能也被禁用了

**Comment by benjycui** [comment]
完全沟通不了。。。

如果你是想没有那个点击后出现的背景色，用样式覆盖吧。

**Comment by cainiaozhilu** [comment]
@benjycui
![7ee8 tmp](https://cloud.githubusercontent.com/assets/23371312/20207997/fd937868-a825-11e6-98e6-688c9c44d056.jpg)
非常感谢你的耐心回答  我的表达可能有问题，真是不好意思  麻烦了

**Comment by cainiaozhilu** [comment]
@benjycui
![7ee8 tmp](https://cloud.githubusercontent.com/assets/23371312/20207997/fd937868-a825-11e6-98e6-688c9c44d056.jpg)
非常感谢你的耐心回答  我的表达可能有问题，真是不好意思  麻烦了

**Comment by benjycui** [comment]
> TreeNode 的 click 也就是加个背景色，所以其实你是要禁用这个行为么？



> 如果你是想没有那个点击后出现的背景色，用样式覆盖吧。

**Comment by afc163** [comment]
感觉你应该用这个：https://ant.design/components/select/#components-select-demo-optgroup

**Comment by chenmengS** [comment]
树的深度不限，某一子节点禁用，该子节点下的子类可展开并且可用，该如何实现
