### ISSUE TITLE
ie11 日期时间选择框，多次选中切换，“SVGGraphicsElement”未定义，The above error occurred in the <TimeUnitColumn> component

### ISSUE THREAD

**Issue by notepadhub** [ant-design/ant-design#37814]
### Reproduction link

[ https://ant.design/components/date-picker/ ]( https://ant.design/components/date-picker/ )

### Steps to reproduce

第一次选择日期和时间且关闭弹框之后，再次选择日期时间，重复以上操作

### What is expected?

支持ie11

### What is actually happening?

支持ie11

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 17.0.44 |
| System | windows |
| Browser | ie11 |
![img_v2_05efc9ea-cfab-4e66-b129-eca2bd77c62g](https://user-images.githubusercontent.com/43948741/193200568-a4cb8fc2-60c3-48e7-85c0-6c0bb978feef.jpg)

**Comment by zombieJ** [comment]
https://github.com/react-component/util/issues/434
