### ISSUE TITLE
Tabs with a Input that has a ref not working as expected

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#37825]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-23-3-forked-1swmjk?file=/demo.js)

### Steps to reproduce

Click on the tabs, on any order, and then go back to clicking on the previous tab again.

### What is expected?

The input should be focused when a tab is clicked, even if you click on the same tab again.

### What is actually happening?

The input is only focused on the first time you click on a Tab, all the others clicks doesn't fire the focus on the input again.

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 18.3 |
| System | Windows 10 |
| Browser | Brave |

---
It seems a little weird to me that it works on the first time you click on a tab normally, but if you go back to a tab you already clicked it somehow doesn't work anymore. 

I couldn't figure out if the problem is with the refs on the Input component, or with some weird behaviour with the Tabs component.

**Comment by afc163** [comment]
Tabs will focus on panel when switch to a new tab for a11y reason, you can add setTimeout as workaround: https://codesandbox.io/s/basic-antd-4-23-3-forked-mv8ooq?file=/components/Tab1.js

**Comment by balboFK** [comment]
Worked like a charm, thank you!
