### ISSUE TITLE
Menu组件mode为vertical的时候，子菜单没有弹出

### ISSUE THREAD

**Issue by 104gogo** [ant-design/ant-design#3783]
#### 发生问题的环境是：

- antd 版本: 1.5.1
- 操作系统及其版本: win7
- 浏览器及其版本: chrome 54.0.2840.87 m (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。
我想改变openKeys和selectedKeys来控制Menu的展示
当mode是inline的时候是正常的
但mode为vertical的时候，子菜单就不弹出了

#### 可重现的在线演示
http://codepen.io/skyriver9/pen/MbaRWE?editors=0010

**Comment by yesmeck** [comment]
@afc163  https://github.com/ant-design/ant-design/blob/master/components/menu/index.tsx#L134-L136 这个好像是故意的？

**Comment by yesmeck** [comment]
@104gogo 不知道你的使用场景是？

**Comment by 104gogo** [comment]
@yesmeck router变了显示对应的菜单

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/3419

**Comment by afc163** [comment]
一开始确实没有需求，就偷懒了，在上面 PR 里一并修复了。

**Comment by afc163** [comment]
陈年老 issue ... 响应得慢了请多谅解。

**Comment by 104gogo** [comment]
@afc163 good job!
