### ISSUE TITLE
antd有没有类似ip地址的输入框？

### ISSUE THREAD

**Issue by guoxiangwen** [ant-design/ant-design#3785]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by yesmeck** [comment]
暂时没有，自己封装下吧。

**Comment by guoxiangwen** [comment]
@yesmeck 我看了form 的input验证用的一个插件
![image](https://cloud.githubusercontent.com/assets/7627191/20168473/61827b0e-a75d-11e6-8ec9-1a52d82aadea.png)
当验证不能输入空格的时候 如果开头有kong'ge空格就会输出错误，如果在中间输入空格就不会，怎么解决呢？

**Comment by yesmeck** [comment]
这是设计 https://github.com/yiminghe/async-validator#whitespace 中间不允许有空格可以自己写规则，参考 https://github.com/yiminghe/async-validator#usage

**Comment by benjycui** [comment]
IP 地址输入试下这个 http://insin.github.io/react-maskedinput/

没问题就顺手把 issue 关了吧。

**Comment by guoxiangwen** [comment]
好的，非常感谢解答。蚂蚁的同事效率真高

**Comment by afc163** [comment]
感觉这个功能蛮有用的。

**Comment by kennylbj** [comment]
ip和mac地址的输入框感觉挺有用的😄
