### ISSUE TITLE
Browser tab switching not working on Chrome

### ISSUE THREAD

**Issue by Genarito** [ant-design/ant-design#37859]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-tab-switching-bug-on-chrome-1hgquo?file=/demo.tsx)

### Steps to reproduce

Just use Radio buttons and normal text inputs.

### What is expected?

Using Tab control should switch between consecutive inputs without skipping any input/option.

### What is actually happening?

Tab control focuses on the first input, then on the first option in the Radio group, and finally on the last input, ignoring completely the last option in the Radio group ("Pear").

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 18.0.0 |
| System | Linux |
| Browser | Chrome version 106.0.5249.91 (Official Build) (64-bit) |

---
This bug is not present in Mozilla Firefox (I'm using version 105.0.1 (64-bit)).

**Comment by afc163** [comment]
Could you provide a video?

**Comment by afc163** [comment]
The native component `<input type="radio" />` works in a same way: https://codesandbox.io/s/form-tab-switching-bug-on-chrome-forked-rc4pp8 I don't think there is anything we can do about it.

**Comment by Genarito** [comment]
Ok thank you, I'll report to Chrome :)
