### ISSUE TITLE
关于下拉框设置宽度的问题，会导致如果下拉选项很长，选择之后，下拉框会自动撑开，影响页面布局

### ISSUE THREAD

**Issue by allen-kobe** [ant-design/ant-design#37868]
### What problem does this feature solve?

当我下拉框的宽度自适应外层宽度的前提下，保证页面不变形

### What does the proposed API look like?

能否设置了宽度为100%，但是不要根据选项的宽度自动撑开

**Comment by allen-kobe** [comment]
> 
https://codesandbox.io/s/antd-reproduction-template-y9vgcf?file=/index.js

**Comment by allen-kobe** [comment]
> Hello @allen-kobe. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @allen-kobe, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

这是codesandbox 对应的代码，下拉框选项很长的时候，选择之后，显示框会变的一样长
https://codesandbox.io/embed/antd-reproduction-template-forked-v5orxz?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
可以加个 maxWidth：https://codesandbox.io/s/antd-reproduction-template-forked-zt367z

**Comment by allen-kobe** [comment]
因为是通过a-col来设置长度，无法使用定长的方式去限制，早上发现在a-form-item上面设置labelCol和wrapCol可以达到效果

从 Windows 版邮件发送

发件人: afc163
发送时间: 2022年10月7日 16:27
收件人: ant-design/ant-design
抄送: allen-kobe; Mention
主题: Re: [ant-design/ant-design]=?UTF-8?Q?_=E5=85=B3=E4=BA=8E=E4=B8=8B=E6=8B=89=E6=A1=86=E8=AE=BE=E7=BD=AE=E5=AE=BD=E5=BA=A6=E7=9A=84=E9=97=AE=E9=A2=98=EF=BC=8C=E4=BC=9A=E5=AF=BC=E8=87=B4=E5=A6=82=E6=9E=9C=E4=B8=8B=E6=8B=89=E9=80=89=E9=A1=B9=E5=BE=88=E9=95=BF=EF=BC=8C=E9=80=89=E6=8B=A9=E4=B9=8B=E5=90=8E=EF=BC=8C=E4=B8=8B=E6=8B=89=E6=A1=86=E4=BC=9A=E8=87=AA=E5=8A=A8=E6=92=91=E5=BC=80=EF=BC=8C=E5=BD=B1=E5=93=8D=E9=A1=B5=E9=9D=A2=E5=B8=83=E5=B1=80?==?UTF-8?Q?_=28Issue_#37868=29?=

可以加个 maxWidth：https://codesandbox.io/s/antd-reproduction-template-forked-zt367z
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>



-------------------------------------------------------------------------------------------------------------------------------------
本邮件及其附件含有海智信息的保密信息，仅限于发送给上面地址中列出的个人或群组。
禁止任何其他人以任何形式使用（包括但不限于全部或部分地泄露、复制、或散发）本邮件中的信息。
如果您错收了本邮件，请您立即电话或邮件通知发件人并删除本邮件！
This e-mail and its attachments contain confidential information from Hic Tec, which is intended only for the person or entity whose address is listed above.
Any use of the information contained herein in any way (including, but not limited to, total or partial disclosure, reproduction, or dissemination) by persons other than the intended recipient(s) is prohibited.
If you receive this e-mail in error, please notify the sender by phone or email immediately and delete it!
