### ISSUE TITLE
Dropdown in <Select> does not move when scrolling up and down in a Modal

### ISSUE THREAD

**Issue by Caladan08** [ant-design/ant-design#37873]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/little-glitter-qbh5om?file=/src/App.js)

### Steps to reproduce

1. Click on the "Show Modal" button to raise the modal
2. Click on any of the `Select` inputs
3. Scroll up and down

### What is expected?

The dropdown should move with the Modal if we scroll up and down

### What is actually happening?

The dropdown stays in the same place and does not move

| Environment | Info                                                                    |
|-------------|-------------------------------------------------------------------------|
| antd        | 4.23.4                                                                  |
| React       | 18.2.0                                                                  |
| System      | macOS                                                                   |
| Browser     | Brave Version 1.44.105 Chromium: 106.0.5249.91 (Official Build) (arm64) |

**Comment by zombieJ** [comment]
https://ant.design/docs/react/faq#How-do-I-prevent-Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-scrolling-with-the-page
