### ISSUE TITLE
关于Select下拉框加入搜索功能后秒收回的问题

### ISSUE THREAD

**Issue by kongjunchao** [ant-design/ant-design#3787]
import React from 'react';
import ReactDom from 'react-dom';
import { Select } from 'antd';
const Option = Select.Option;
class SelectCity extends React.Component{
	constructor(props){
		super(props);
		this.state = {
		}
	}
	selectCity(val){
		console.log(val);
	}
	componentWillMount(){
	}
	componentDidMount(){
	}
	render(){
		return (
			<Select 
				showSearch
				style = {{width:100}}
				defaultValue = "全国"
				optionFilterProp = "children"
				onChange = {this.selectCity.bind(this)}
				notFoundContent = ""
			>
				<Option value="全国">全国</Option>
				<Option value="北京">北京</Option>
				<Option value="上海">上海</Option>
				<Option value="广州">广州</Option>
				<Option value="深圳">深圳</Option>
				<Option value="南京">南京</Option>
			</Select>
		);
	}
}
export default SelectCity;

#### 发生问题的环境是：
- antd 版本:2.3.2
- 操作系统及其版本:win7
- 浏览器及其版本:Chrome

在点击下拉框的时候，会出现下拉框详情，然后瞬间收回下拉框，重复几次依然如此，把showSearch属性去掉以后，便正常了

**Comment by RaoHai** [comment]
跟这个 #3778 同一个问题。

**Comment by kongjunchao** [comment]
补充下哈，在我使用2.0版本antd的时候，一切都是正常的，希望能解决下，谢谢啦
