### ISSUE TITLE
antd 5.0 Input.Password  样式异常

### ISSUE THREAD

**Issue by wanghui94** [ant-design/ant-design#37883]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-5-0-input-password-50hgxw)

### Steps to reproduce

无

### What is expected?

Input 和 Input.Password 在 From 组件中宽度一致

### What is actually happening?

Input 和 Input.Password 在 From 组件中宽度不一致

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | macOS 12.6 |
| Browser | chrome 105.0.5195.125 |

**Comment by Wxh16144** [comment]
貌似是 `box-sizing` 的问题

**Comment by MadCcc** [comment]
fixed in https://github.com/ant-design/ant-design/pull/37810
