### ISSUE TITLE
表格中render delete功能的疑问

### ISSUE THREAD

**Issue by guoxiangwen** [ant-design/ant-design#3788]
#### 发生问题的环境是：

- antd 版本:2.3.0
- 操作系统及其版本:Win10
- 浏览器及其版本:Chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

渲染一个表格如图：
![image](https://cloud.githubusercontent.com/assets/7627191/20170574/d6415a14-a767-11e6-99a7-dc4e1010a90c.png)
然后我希望删除的时候，有一个气泡确认框。确认框的onConfirm方法写在了AppManageTable的里面
![image](https://cloud.githubusercontent.com/assets/7627191/20170620/0b7f406a-a768-11e6-8351-0df188439045.png)

但是渲染AppManageTable的时候就会自动去执行deleteItem()方法。
![image](https://cloud.githubusercontent.com/assets/7627191/20170663/2e37a0e8-a768-11e6-99ca-3654ef88b4e1.png)

**Comment by afc163** [comment]
`onConfirm={() => this.deleteItem(record.id)}`

or

`onConfirm={this.deleteItem.bind(record.id)}`

该认真学习 JavaScript 了。:smile:

**Comment by afc163** [comment]
另外，用法问题优先到这里提问：https://segmentfault.com/t/antd

**Comment by guoxiangwen** [comment]
。哎，，底子薄了 不过onConfirm={this.deleteItem.bind(record.id)}这种拿不到record.id第一种arr函数可以

**Comment by afc163** [comment]
我错了，`onConfirm={this.deleteItem.bind(null, record.id)}`
