### ISSUE TITLE
Drawer 中extra 操作区域  如果使用input的search文本框会变形，而且看不到输入的内容

### ISSUE THREAD

**Issue by gdwisca** [ant-design/ant-design#37894]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modern-lake-uj6hss?file=/src/App.js)

### Steps to reproduce

<Drawer
        placement="right"
        open={true}
        extra={<Search placeholder="input search text" enterButton="Search" />}
      >
        <p>Some contents...</p>
        <p>Some contents...</p>
        <p>Some contents...</p>
      </Drawer>

### What is expected?

Drawer 中extra 操作区域  里面input能正常使用

### What is actually happening?

Drawer 中extra 操作区域  里面input能正常使用

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 18.2.0 |
| System | win7 |
| Browser | Chrome和360都试过不行 |

---
很久之前的版本是可以的，后来更新几次就不行了

**Comment by afc163** [comment]
你需要加个 width：https://codesandbox.io/s/practical-joliot-rvly3s
