### ISSUE TITLE
`ReferenceError: window is not defined` after upgrading from v4 to v5 in Next.js

### ISSUE THREAD

**Issue by Ayuilos** [ant-design/ant-design#37893]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/xenodochial-bird-x1orvm?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A35%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A35%2C%22startLineNumber%22%3A10%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9az000nlpgeaw1kc72o%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpages%252Findex.tsx%2522%252C%2522%252Fpages%252F_app.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl8zp6yq003d83b72bdx3m10o%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl8zp2qgi03233b72vz7wpjwt%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

### Steps to reproduce

Please check the codesandbox link.
I don't know whether this is my import way problem or v5 problem, but **I'm pretty sure everything is okay before I do the upgrade**. So I'm needing your supports. What I do is just upgrade and remove antd css import, then it broke.

### What is expected?

No error.

### What is actually happening?

ReferenceError happened.

| Environment | Info |
| --- | --- |
| antd | 5.0.0-alpha.0 |
| React | 17.0.2 |
| System | MacOS 12.3 |
| Browser | 103.0.5060.134 |

**Comment by zombieJ** [comment]
Seems bundle file use `window` variable:
<img width="819" alt="截屏2022-10-08 17 34 47" src="https://user-images.githubusercontent.com/5378891/194700847-88ca0ed8-1a2b-406c-885c-8adb5d8ce414.png">

It's strange that v4 also generate same code here. Maybe it picks es module in v4. Need additional check.

**Comment by zombieJ** [comment]
<img width="881" alt="截屏2022-10-08 17 37 42" src="https://user-images.githubusercontent.com/5378891/194700950-a5344b94-b6d3-4e19-a1b3-aa4030626548.png">

@MadCcc

**Comment by afc163** [comment]
We need a test case for that.

**Comment by chunsch** [comment]
@zombieJ @afc163 哈喽，这是 webpack 4  `output.globalObject` 默认配置引起的，上周已提交 PR：[feat: support for UMD bundles to be used on the ssr](https://github.com/ant-design/antd-tools/pull/257)。

目前还发现另外一个问题，引入 `antd/es/locale` 语言包会报错：`SyntaxError: Cannot use import statement outside a module`。昨天看了相关文档，是没有声明文件为 esm 引起的，在 node 有[两种声明方式](https://nodejs.org/api/packages.html#determining-module-system)：
1. 在 `package.json` 指定 `type` 字段为 `module `:
```json
{
   "type": "module"
}
```
但由于还有 umd dist，这会引发另一个问题。

2. esm 文件使用 `mjs` 后缀，如：`zh_CN.js` 修改为 `zh_CN.mjs`，这样可以正常引用。但 TypeScript 貌似没有输出 `mjs` 后缀的配置，相关 issues 的讨论：[Support .mjs output](https://github.com/microsoft/TypeScript/issues/18442)。

---

针对这个问题，目前想到两种方案：
1. esm 文件使用 `mjs`：build 后批量修改或使用支持配置输出 `mjs` 后缀的编译工具。
2. 像 [@mui/material](https://www.jsdelivr.com/package/npm/@mui/material) 一样，提供非 esm 的语言包文件。

不知道有没更好的方式。

---

这个问题的临时解决方案，除了改文件后缀，暂时还可用 `dynamic` 解决：

```ts
import dynamic from 'next/dynamic';

const zh_CN = dynamic('antd/es/locale/zh_CN', {
  ssr: false
})
```

**Comment by MadCcc** [comment]
1. esm 文件使用 mjs 后缀：build 后批量修改文件名或使用支持配置输出 mjs 后缀的编译工具。
改成 .mjs break 太大

2. 像 [@mui/material](https://www.jsdelivr.com/package/npm/@mui/material) 一样，提供非 esm 的语言包文件。
可能还是得考虑把 lib 加回来

**Comment by Ayuilos** [comment]
Hello, I was wondering if you have an estimated time for this issue to be fixed?

This helps me decide whether to wait for your update on v5 or continue to develop features based on v4.

**Comment by chunsch** [comment]
@Ayuilos Hi, the latest alpha version has fixed this problem, you can try upgrading the version. If there is another problem mentioned above (import `antd/es/locale` files in Next.js), you need to wait for [this PR](https://github.com/ant-design/ant-design/pull/38194) to be merged and a new version will be released.

**Comment by Ayuilos** [comment]
> @Ayuilos Hi, the latest alpha version has fixed this problem, you can try upgrading the version. If there is another problem mentioned above (import `antd/es/locale` files in Next.js), you need to wait for [this PR](https://github.com/ant-design/ant-design/pull/38194) to be merged and a new version will be released.

OK thanks!
