### ISSUE TITLE
table的filter没有重置和确定按钮，官方文档可以直接复现

### ISSUE THREAD

**Issue by XueMeijing** [ant-design/ant-design#37909]
### Reproduction link

[https://ant.design/components/table-cn/#API 官网直接可以复现](https://ant.design/components/table-cn/#API 官网直接可以复现)

### Steps to reproduce

官方文档table的filter没有重置和确定按钮，应该是跟国际化有关，我之前也碰到过，加上国际化就好了。但是最小复现仓库无法复现，不知道什么原因

这里是antd的代码

![image](https://user-images.githubusercontent.com/35559153/194791367-a7d34d0a-1acf-4e91-9622-d7333d77cd55.png)

### What is expected?

根据浏览器语言自动设置一个国际化，然后显示表格filter的重置按钮

### What is actually happening?

表格filter的重置按钮是空白

![image](https://user-images.githubusercontent.com/35559153/194791410-99595b9b-6cbc-41e7-8a58-3bc11f56ec53.png)

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 17 |
| System | macos |
| Browser | chrome 105 |

**Comment by afc163** [comment]
<img width="221" alt="图片" src="https://user-images.githubusercontent.com/507615/194792497-33bc6702-cd1a-4907-bfa9-f9d42976634b.png">
官网确实没了。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/37824/files#diff-240f91f05c76564ed31ee512d9d417fcbceebe5724988c4395ed7a346befc3f6R258
