### ISSUE TITLE
4.x版本的modal及drawer在safari浏览器中无法使用

### ISSUE THREAD

**Issue by wuxinzhe097** [ant-design/ant-design#37905]
### Reproduction link

[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce

官网所有例子都无法使用

### What is expected?

希望drawer/modal能正常展示

### What is actually happening?

无法打开drawer/modal

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 17 |
| System | macOS10.15.7 |
| Browser | safari13.1.3 |

**Comment by zombieJ** [comment]
可以试试国内镜像哈：https://ant-design.antgroup.com/

**Comment by wuxinzhe097** [comment]
> 可以试试国内镜像哈：https://ant-design.antgroup.com/

一样，在safari浏览器下，drawer不能正常显示

**Comment by zombieJ** [comment]
Hmmm。可能是旧版 Safari 兼容性问题，能提供一下错误信息吗？麻烦你啦

**Comment by wuxinzhe097** [comment]
> Hmmm。可能是旧版 Safari 兼容性问题，能提供一下错误信息吗？麻烦你啦
感觉是样式的问题，safari不支持inset属性
![image](https://user-images.githubusercontent.com/49263105/194748703-8355ca4b-98e2-4e3f-af52-f7a4d4a957eb.png)

**Comment by wuxinzhe097** [comment]
> > Hmmm。可能是旧版 Safari 兼容性问题，能提供一下错误信息吗？麻烦你啦


3.x版本中的样式可以正常展示
![image](https://user-images.githubusercontent.com/49263105/194748754-308c04b3-b522-4e5b-a508-dc6f86234ee3.png)

**Comment by zombieJ** [comment]
官网 css 文件用 postcss 压缩合并过哈，npm 包里的 css 是不压缩的哈：https://codesandbox.io/s/ji-chu-chou-ti-antd-4-23-4-forked-uldue2?file=/index.js

**Comment by wuxinzhe097** [comment]
> 官网 css 文件用 postcss 压缩合并过哈，npm 包里的 css 是不压缩的哈：https://codesandbox.io/s/ji-chu-chou-ti-antd-4-23-4-forked-uldue2?file=/index.js

在codepen和codesandbox中都可以正常使用，但是在实际项目和官网上感觉都有样式不兼容的问题

**Comment by wuxinzhe097** [comment]
> 官网 css 文件用 postcss 压缩合并过哈，npm 包里的 css 是不压缩的哈：https://codesandbox.io/s/ji-chu-chou-ti-antd-4-23-4-forked-uldue2?file=/index.js

而且inset属性好像确实不兼容14版本以下的safari

**Comment by zombieJ** [comment]
> 但是在实际项目和官网上感觉都有样式不兼容的问题

可以检查一下项目的 loader 配置，应该是一样被压成 inset 了。

**Comment by wuxinzhe097** [comment]
> > 但是在实际项目和官网上感觉都有样式不兼容的问题
> 
> 可以检查一下项目的 loader 配置，应该是一样被压成 inset 了。

是的，今天看了一下，之前vite配置里postcss使用的是autoprefixer，它并不会处理inset，换成postcss-preset-env后可以正常使用，谢谢
