### ISSUE TITLE
multiple select component when the option content is too long

### ISSUE THREAD

**Issue by JackDan9** [ant-design/ant-design#37902]
### What problem does this feature solve?

When the Option content is too long, the displayed content is strange

### What does the proposed API look like?

Effect link
: https://codesandbox.io/s/xiang-ying-shi-maxtagcount-antd-4-23-4-forked-wq2qee?file=/demo.js
Whether the content of the option can also be ellipsis or given a choice for default and better

### Default Solutions

![image](https://user-images.githubusercontent.com/12805846/194743763-f6e573a6-9d4d-4e16-a3f2-915aec82494f.png)

### Suggested Solutions

<img width="351" alt="image" src="https://user-images.githubusercontent.com/12805846/194743806-61207d41-f17d-4152-92d6-9f1cfc457cf8.png">

**Comment by JackDan9** [comment]
Discussion is welcome and find better solutions through discussion

**Comment by zombieJ** [comment]
Thanks for feedback. You can set `max-width` of this requirement:
https://codesandbox.io/s/xiang-ying-shi-maxtagcount-antd-4-23-4-forked-d4ntl3?file=/index.css
