### ISSUE TITLE
Add `.focus` `.blur` method for every form control components

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#3790]
Make sure that every form control component has`.focus` method, see: https://facebook.github.io/draft-js/docs/advanced-topics-managing-focus.html

* [x] auto-complete
* [x] cascader
* [x] checkbox
* [x] date-picker
* [x] input https://github.com/ant-design/ant-design/commit/d94f0ab09a5dd66a1dbb7b4504b14a9a58fa2a55#diff-26cb6da96d10397e18e7dbd6c5d8f7a1R141
* [x] input-number https://github.com/ant-design/ant-design/pull/7615
* [x] mention
* [x] radio
* [x] rate
* [x] select
* [x] slider
* [x] switch
* [x] time-picker https://github.com/ant-design/ant-design/commit/760a5ffc90ddd7718d2ada1b2cd19cba839dc40a
* [x] tree-select
<del>* [ ] upload</del>

**Comment by librae8226** [comment]
请教，如果用 Select 组件的话怎么设置 autofocus 呢？现在有什么 workaround 的方法吗？

**Comment by librae8226** [comment]
请教，如果用 Select 组件的话怎么设置 autofocus 呢？现在有什么 workaround 的方法吗？

**Comment by forever4313** [comment]
有进展吗？？、

**Comment by jaredleechn** [comment]
badly need select~

**Comment by artalar** [comment]
why AutoComplete.getInputElement not work (haven't `focus`) =(

**Comment by javaxiu** [comment]
input如何自动获取焦点？doc上好像没描述到

**Comment by wewoor** [comment]
In this version v6.9.0 of rc-select is not support autoFocus option, but support in v7.x . so if you want you want to implement autofocus，you can try this:

give you select component an id,  and write a focus function.
```javascript

    onfocus = () => {
        const selector =  document.getElementById('My_Select')
        if (selector) selector.focus()
    }



  <Select id="My_Select"> </Select>

```

**Comment by yesmeck** [comment]
@artalar Don't rely on undocumented API.

**Comment by yesmeck** [comment]
Rate needs focus style.

**Comment by chenxiao01** [comment]
badly need .focus to be efftive on Select

**Comment by ChuckJonas** [comment]
it looks like you can focus a select but it doesn't cause the options to open

**Comment by nnmrts** [comment]
@ChuckJonas That's exactly the problem. Most of you probably want to really focus and open the rc-select component beneath the antd select component. Try this:

```javascript
antdSelectRef.rcSelect.setOpenState(true, true);
```

You can also directly use setState on it to have full control over it. Doing it this way won't close the select on blur:

```javascript
antdSelectRef.rcSelect.setState({
    open: true
});
```
---
This is still an ugly workaround though.

**Comment by mths0x5f** [comment]
calling .focus() on a Select ref still does not work.

**Comment by MelancholYA** [comment]
what worked for me is to create a useState to handle the open state then change it with what ever event you want like so :
const [open, setOpen] = useState(false);
<Select
	open={open}>
</Select>

<Button onClick={()=>setOpen(!open)} >toggle dropdown</Btton>

what do you think about this ?
