### ISSUE TITLE
Outsourcing input number will cause buggy re-render on value set

### ISSUE THREAD

**Issue by leventebg93** [ant-design/ant-design#37919]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-23-4-forked-sjdmzv?file=/demo.js)

### Steps to reproduce

```
const App = () => {
  const [val, setVal] = useState(1);

  const onChange = (value) => {
    setVal(value);
  };

  const NumberInput = () => (
    <InputNumber min={1} max={10} value={val} onChange={onChange} />
  );

  return (
      <NumberInput />
  );
};
```

### What is expected?

To have a smooth experience when typing in the numbers to the input field just like when using without outsourcing it into an external function

### What is actually happening?

It rerenders on every keystroke, the selection is lost every time, so you have to click in everytime, when you delete the number it also does this on every time you press the backspace

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 17.0.2 |
| System | Windows 10 Pro 21H1 |
| Browser |  Chrome 106.0.5249.103  |

---
I want to simplify my code, containing 50-100 repeating, very similar looking InputNumber fields, and instead of using them one by one, I want to create a generic CustomInputNumber component which I can reuse with unique params

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-antd-4-23-4-forked-w0rvdq
