### ISSUE TITLE
table在同时设置scroll y和某列的fixed属性时，即时只有一条数据也会显示y轴滚动条

### ISSUE THREAD

**Issue by ALLTAKENS** [ant-design/ant-design#37910]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-biao-tou-antd-4-23-4-forked-ufdsgt?file=/demo.js)

### Steps to reproduce

比如有abc三列，给a列加了fixed: 'left'并且给表格加了scroll={{ y: 240 }}的属性后，在仅有一条数据的情况时也会出现滚动条

### What is expected?

行数未达到设置的滚动高度时不显示滚动条

### What is actually happening?

行数未达到设置的滚动高度时显示滚动条了，并且可以轻微滚动

| Environment | Info |
| --- | --- |
| antd | 4.17.3 |
| React | 17.x |
| System | windows10 |
| Browser | chrome 105.0.5195.127 |

**Comment by afc163** [comment]
Duplicate of #29082

**Comment by liyou-Leo** [comment]
同遇到了这个问题，表头设置了fixed并且给表格加了scroll={{ y: 240 }}后就会出现，目前还么找到比较合适的解决方案
