### ISSUE TITLE
Table表格最后一列无法合并行

### ISSUE THREAD

**Issue by flyingImmortal** [ant-design/ant-design#3791]
#### 发生问题的环境是：

- antd 版本: "antd": "2.0.1",
- 操作系统及其版本: windows7
- 浏览器及其版本:chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

第一列合并简单
this.columns = [{
            title: '发布代号',
            dataIndex: 'code',
            key: 'code',
            render(value, row, index) {
                const obj = {
                    children: value,
                    props: {},
                };
                obj.props.rowSpan = 2;
                return obj;
            }
        }
最后一列为操作列，没法合并，不知道怎么写

{
            title: '操作',
            key: 'action',
            render:function(value, row, index){
                const obj = {
                    children: value,
                    props: {},
                };
                obj.props.rowSpan =2;
                      return  (<span> <a onClick={() => this._update(row).bind(this)}>构建部署</a>
                     
            </span>)
            }

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by flyingImmortal** [comment]
搞定了，多了个单引号，内容写在children上就好了
{
            title: '操作',
            key: 'action',
            render: function (value, row, index) {
                const obj = {
                    children: <span>
                 <a onClick={() => this._buildAndDeployment(row).bind(this)}>构建部署</a>
                         
                 </span>
                    ,
                    props: {}
                }
                obj.props.rowSpan = row.rowSpan1;
                return obj;
            }

**Comment by flyingImmortal** [comment]
发现个bug，最后一行没有边框，可以增加以下css
.ant-table-bordered .ant-table-tbody > tr > td:last-child {
 border-right: 1px solid #e9e9e9;
}

**Comment by yesmeck** [comment]
麻烦贴代码的时候能用 markdown 格式化一下，最好能贴个例子  http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by flyingImmortal** [comment]
你格式化一下就错了

**Comment by flyingImmortal** [comment]
不会格式化啊

**Comment by yesmeck** [comment]
https://help.github.com/articles/about-writing-and-formatting-on-github/

**Comment by flyingImmortal** [comment]
这个还是有问题的
里面的方法无法访问到外面

**Comment by yesmeck** [comment]
@flyingImmortal 请给个例子，不然听不明白你在讲什么 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by yesmeck** [comment]
如果是使用问题建议到 https://segmentfault.com/ 上提问。

**Comment by afc163** [comment]
```js
render: (value, row, index) => {
```

代码格式化是最起码的尊重。

**Comment by flyingImmortal** [comment]
> render(value, row, index){
                const obj = {children:'',props: {}
                }
                obj.props.rowSpan = row.rowSpan1;
                obj.children=
                <span>
                 <a onClick={() => this._buildAndDeployment(row)}>构建部署</a>
                 <span className="ant-divider"/>
                 <a onClick={() => this._rePushPackage.bind(this)(row)}>重新开发</a>
                 <span className="ant-divider"/>
                 <a onClick={() => this._closeRelase.bind(this)(row)}>结束</a>
                 </span>
                return obj;
            }

_buildAndDeployment和_rePushPackage 都报undefind错误。
谁知道应该怎么写

**Comment by flyingImmortal** [comment]
> render:(value, row, index)=>(
                <span>
                 <a onClick={() => this._buildAndDeployment(row)}>构建部署</a>
                 <span className="ant-divider"/>
                 <a onClick={() => this._rePushPackage(row).bind(this)}>重新开发</a>
                 <span className="ant-divider"/>
                 <a onClick={() => this._closeRelase(this).bind(row)}>结束</a>
                 </span>
                )

这样写就可以访问，但无法全并列了。请高手解答

**Comment by benjycui** [comment]
@flyingImmortal comment 后你都不看下效果的么。。你确定预览的效果是你的代码？

Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by flyingImmortal** [comment]
确定啊，你们大家都不到代码？

**Comment by flyingImmortal** [comment]
https://segmentfault.com/q/1010000007480077?_ea=1358029

我已经在这里提问了，你们是来找茬和代码评审的还是来帮我解决问题的，纠结这格式干什么，我真的不会格式化。图片也放不上来

**Comment by afc163** [comment]
> 纠结这格式干什么

建议阅读 https://github.com/seajs/seajs/issues/545 的 『语法正确、格式清晰』部分。

**Comment by afc163** [comment]
另外，你的问题我上面已经回答过你了。
