### ISSUE TITLE
表格需要增加 单元格的 双击 回调 和 行的双击回调

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#3792]
#

#### 发生问题的环境是：

- antd 版本:ant design 2.0.1
- 操作系统及其版本:windows 10
- 浏览器及其版本:chrome 最新版

#### 您做了什么？请提供尽可能详细的重现步骤。

表格需要增加 单元格的 双击 回调 和 行的双击回调

#### 您期待的结果是:

表格需要增加 单元格的 双击 回调 和 行的双击回调

#### 实际上的结果是:

表格没有单元格的 双击 回调 和 行的双击回调

#### 可重现的在线演示

官网即可

**Comment by afc163** [comment]
onRowDoubleClick

https://github.com/react-component/table#properties

单元格双击回调暂不支持，您可以：

```
columns = [{
  render: () => {
    return <div onDoubleClick={this.onDoubleClick}>内容</div>
  }
}]
```
