### ISSUE TITLE
关于定制主题中多选框Checkbox的less变量选取问题

### ISSUE THREAD

**Issue by Roson99** [ant-design/ant-design#37921]
###### 覆盖多选框@checkbox-border-radius变量，使其选中时保持一致。

～/antd/lib/checkbox/style/mixin.less
```
&-checked::after {
      ...,
      border-radius: @border-radius-base;
      ...,
    }
&-inner {
      ...,
      border-radius: @checkbox-border-radius;
      ...,
    }
```

###### 统一变量来源。

～/antd/lib/checkbox/style/mixin.less
```
&-checked::after {
      ...,
      border-radius: @checkbox-border-radius;
      ...,
    }
&-inner {
      ...,
      border-radius: @checkbox-border-radius;
      ...,
    }
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/975def492b97a2fc5c1e1fc9eda7f1984b93bb4b/components/checkbox/style/mixin.less#L29

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/37131
