### ISSUE TITLE
Dynamic theme ConfigProvider add more color support like less do

### ISSUE THREAD

**Issue by TrustyTechSG** [ant-design/ant-design#37926]
### What problem does this feature solve?

Currently ConfigProvider.config({theme}) only support a handful of colors, compare to variables support much more, can we add all other missing color support like less variables do, thank you.

### What does the proposed API look like?

import { ConfigProvider } from "antd";

ConfigProvider.config({ theme });

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/33862
