### ISSUE TITLE
Tabs切换，对应内容不跟着切换

### ISSUE THREAD

**Issue by 77159** [ant-design/ant-design#37936]
### Reproduction link

[https://ant-design.antgroup.com/components/tabs-cn/](https://ant-design.antgroup.com/components/tabs-cn/)

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

1

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 17 |
| System | 1 |
| Browser | chrome |

---
1

**Comment by zombieJ** [comment]
请提供重现，否则无法帮助排查问题。
