### ISSUE TITLE
timepicker使用hideDisabledOptions和disabledMinutes显示问题

### ISSUE THREAD

**Issue by cdoneshot** [ant-design/ant-design#3793]
#### 发生问题的环境是：

- antd 版本:2.2.1
- 操作系统及其版本:win10 x64
- 浏览器及其版本:chrome 51

#### 您做了什么？请提供尽可能详细的重现步骤。

timepicker配置disabledMinutes，disabledSeconds，同时禁止的0-59分，0-59秒，配置hideDisabledOptions=true。

#### 您期待的结果是:
小时菜单占满整个弹层（或者其它比较美观的显示），而不是1/3。

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/20412044/20178244/4691065c-a78b-11e6-8a62-7cd6f8405950.png)

![image](https://cloud.githubusercontent.com/assets/20412044/20178298/7373d4ec-a78b-11e6-90d8-f8965601361b.png)

同时会报一个错，
Select.js?85f6:109 Uncaught TypeError: Cannot read property 'children' of null

#### 在线演示:
https://codepen.io/cdoneshot/pen/WorvMY?editors=1010

**Comment by benjycui** [comment]
...

你截图的是 DatePicker，却一直在说 TimePicker。

如果是 TimePicker 的话，请参考这个例子 https://ant.design/components/time-picker/#components-time-picker-demo-without-seconds

**Comment by benjycui** [comment]
麻烦组织好语言，理清你的问题再开 issue，这种信息混乱的 issue 只是浪费彼此的时间。

**Comment by cdoneshot** [comment]
不好意思，我不明白我描述是不是有问题，但是datepicker在对时分秒的选择上配置同timepicker一样，所以我觉得是一个效果，后面给的链接是用timepicker重现的问题。

**Comment by benjycui** [comment]
```jsx
<DatePicker showTime={{ format: 'HH:mm' }} format="YYYY-MM-DD HH:mm" placeholder="Select Time" onChange={onChange} />
```

**Comment by cdoneshot** [comment]
麻烦看一下重现的演示链接，不知道是我没有描述到点，还是你没有get到点。

ps：如果按照你给的配置，timepicker配置format:"HH:mm"，可选的是时、分，如果配置为format:'HH'，可选的依然是时、分，这里是不是也有一点问题

**Comment by afc163** [comment]
样式上应该是撑满的。

**Comment by benjycui** [comment]
在梳理相关的 demo，功能是正常的。

![image](https://cloud.githubusercontent.com/assets/3580607/20202939/60d576a6-a7fe-11e6-8714-977d60c754a9.png)

**Comment by benjycui** [comment]
RangePicker 的有问题，之前 demo 没有覆盖到：

![image](https://cloud.githubusercontent.com/assets/3580607/20202994/b36c7e14-a7fe-11e6-8ab1-3cec6badce09.png)

**Comment by afc163** [comment]
<img width="162" alt="image" src="https://cloud.githubusercontent.com/assets/507615/20203013/db068eb0-a7fe-11e6-87bc-d5f52437d75b.png">

楼主给的例子也很奇怪，除了面板里没撑满，弹出位置不对，弹出动画也不对。

**Comment by cdoneshot** [comment]
上面的demo应该是用format配置的，我使用的是hideDisabledOption+disabledMinutes，这样子会报错

**Comment by afc163** [comment]
你的例子也不太合适，如果使用 disabledMinutes disabledSeconds 禁止选择 0-59，那就是只展示小时面板。那你这么用就可以了：

```
<DatePicker showTime={{ format: 'HH' }} format="YYYY-MM-DD HH" />
```

disabledXxx 是用来禁选部分选项的。

**Comment by cdoneshot** [comment]
你说的这种用法我也试过，这样配置依然面板依然可以选到分钟，我查看文档里面，format应该只支持到分钟。
![image](https://cloud.githubusercontent.com/assets/20412044/20203805/80c130a2-a805-11e6-91fa-4978eceb1242.png)

**Comment by benjycui** [comment]
文档已更新，途中发现两个问题：
* [ ] RangePicker[showTime={format: xxx}] 后样式没做兼容
* [ ] DatePicker[disabledTime] 失效

下午我处理一下。

**Comment by afc163** [comment]
上面的提交修复了 ` Select.js?85f6:109 Uncaught TypeError: Cannot read property 'children' of null` 的报错。

**Comment by afc163** [comment]
- [ ] 我在给 rc-time-picker 加一个 showMinute 属性，以支持 `<TimePicker format="HH" />` 和 `<TimePicker format="ss" />` 的用法。

**Comment by afc163** [comment]
TimePicker 本身的相关样式修正完毕，支持上面那条评论里的用法。

DatePicker 的内的 TimePicker 样式问题由 @benjycui 继续跟进。

**Comment by cdoneshot** [comment]
DatePicker配置showToday={false}好像也没有作用= =

**Comment by benjycui** [comment]
Done.
