### ISSUE TITLE
Input.TextArea在4.23.5版本中使用autosize属性的时候无法输入中文，并且在页面的右上角出现一个textarea框

### ISSUE THREAD

**Issue by zkgaojianjian** [ant-design/ant-design#37931]
### Reproduction link

[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce

最新的4.23.5版本Input.TextArea

### What is expected?

请尽快修复

### What is actually happening?

无法输入中文，右上角出现一个textarea

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | react18 |
| System | macos |
| Browser | chrome 105.0.5195.12 |

**Comment by afc163** [comment]
> 使用autosize属性的时候无法输入中文
确实。。

**Comment by afc163** [comment]
重现方式：https://codesandbox.io/s/ji-ben-shi-yong-antd-4-23-5-forked-udg4x9?file=/demo.js

**Comment by cage1618** [comment]
4.23.6还是没有修复，还出现了新问题：
```No matching export in "node_modules/rc-tabs/node_modules/rc-util/es/ref.js" for import "useComposeRef"```

**Comment by yoyo837** [comment]
重装依赖试一试

**Comment by cage1618** [comment]
> 重装依赖试一试

删除node_modules 和 yarn.lock 后重新安装好了

**Comment by Veveue** [comment]
https://github.com/react-component/tabs/blob/master/package.json#L84
@zombieJ  建议升级一下 `rc-util`

**Comment by afc163** [comment]
@Veveue https://github.com/react-component/tabs/pull/597
