### ISSUE TITLE
调用validateFields进行表单验证后，错误信息不显示

### ISSUE THREAD

**Issue by q454067820** [ant-design/ant-design#3794]
#### 发生问题的环境是：

- antd 版本: antd v2.1.0
- 操作系统及其版本: OSX 10.11.5
- 浏览器及其版本: Chrome 54.0.2840.87 (64-bit)

##### 背景
- 项目架构React + Redux
- 引入的组件Button, Icon, Form, Input, Select, InputNumber, DatePicker
##### 业务逻辑

1. 点击 `Button` 通过 `form.validateFields` 进行表单验证，传回err信息正常，表单验证逻辑正常，控制台返回的错误信息正常。
2. 接下来触发 `onFieldsChange` 方法，在其中触发 redux dispatch 进行状态改变
3. 状态改变后，触发 `mapPropsToFields` ，页面重新渲染，因此 form 中的表单错误信息无法显示

#### 您期待的结果是:

1. 为什么在调用 `form.validateFields` 时会触发`onFieldsChange`，通过这个方法可能很难免进行状态改变，导致页面重新渲染，错误信息也就无法显示。
2. 如果需要经过 `onFieldsChange` 是否可以提供一个状态标识，让组件知道表单正在验证，避免进行状态改变。文档中的 `isFieldValidating` 方法在`onFieldsChange`中是无法获取到的，现在的解决方案只能通过一个全局变量作为`isFieldValidating`的替代flag，不是很优雅。

_以上是我的疑问，如果对您的设计方式有理解不当或使用不当的方式请您指出，期待您的回复，谢谢。_

**Comment by benjycui** [comment]
1. 你试着在 `onFieldsChange` 里面把第二个参数打印出来看下？field 里面包含的不仅仅是 value 还有校验状态，所以 `form.validateFields` 会触发 `onFieldsChange`。
2. field 里面也包含了 validate 的状态 https://ant.design/components/form/#components-form-demo-global-state

**Comment by benjycui** [comment]
有条理的 issue 对双方都好 👍

**Comment by insekkei** [comment]
@benjycui hi，我打印了onFieldsChange的第二个参数，有error信息，但是dispatch之后，进入mapPropsToFields，之前的错误信息就丢了，请问：
```
mapPropsToFields(props) {
    return {
      username: {
        ...props.username,
        value: props.username.value.toUpperCase(),
      },
    };
  },
```
demo中的...props.username,是包含onFieldsChange第二个参数打印出来的所有信息吗，那么我是否需要在onFieldsChange里把错误信息也保存起来以备mapPropsToFields使用呢...

**Comment by minzhang2** [comment]
这个问题怎么解决的@q454067820

**Comment by CRISTIANO-HAO** [comment]
没有解决也关issues？

**Comment by yangyakun19931120** [comment]
webpack 的 LodashModuleReplacementPlugin 插件破坏了 antd 的内部组件。

解决办法：


LodashModuleReplacementPlugin 配置参数

'paths': true

**Comment by leechar-lcn** [comment]
> webpack 的 LodashModuleReplacementPlugin 插件破坏了 antd 的内部组件。
> 
> 解决办法：
> 
> LodashModuleReplacementPlugin 配置参数
> 
> 'paths': true

这个方法是可行的，但是版本号的兼容性有待商榷。目前只发现 3.x 最新版的不行，我的是 3.25.2
