### ISSUE TITLE
Unable to change position suffixIcon in Select

### ISSUE THREAD

**Issue by MrFarhan** [ant-design/ant-design#37948]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jv5942)

### Steps to reproduce

Open the link, I just wanted to change the icon position to left instead of right.

### What is expected?

Just want to change the icon position to left instead of right.

### What is actually happening?

Unable to change suffixIcon position (prefix icon is also not working in Select)

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 17.0.2 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by afc163** [comment]
suffixIcon means suffix, not prefix.

**Comment by MrFarhan** [comment]
@afc163 Can I know the reason for closing this issue?

**Comment by MrFarhan** [comment]
Is it resolved? @afc163 ?

**Comment by MrFarhan** [comment]
@afc163 can you reopen this issue?

**Comment by afc163** [comment]
You can't show a suffixIcon in left position because it named as **suffix**.

**Comment by afc163** [comment]
If you need prefix icon in Select, you could try https://codesandbox.io/s/intelligent-wildflower-fbo1c?file=/index.js

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5744#issuecomment-616790412
