### ISSUE TITLE
antd表格组件嵌套表格 expandedRowRender 为什么出现多余空白列

### ISSUE THREAD

**Issue by qcxiaoshuai-snake** [ant-design/ant-design#37947]
### Reproduction link

[https://blog.csdn.net/qq_35909965/article/details/127267540?spm=1001.2014.3001.5502](https://blog.csdn.net/qq_35909965/article/details/127267540?spm=1001.2014.3001.5502)

### Steps to reproduce

https://blog.csdn.net/qq_35909965/article/details/127267540?spm=1001.2014.3001.5502

### What is expected?

 无空白行

### What is actually happening?

出现空白行

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by qcxiaoshuai-snake** [comment]
how can solute it
please click this link
https://blog.csdn.net/qq_35909965/article/details/127267540?spm=1001.2014.3001.5502

**Comment by afc163** [comment]
好像没看到相关代码？

**Comment by qcxiaoshuai-snake** [comment]
@afc163 https://blog.csdn.net/qq_35909965/article/details/127267540?spm=1001.2014.3001.5502

**Comment by afc163** [comment]
<img width="968" alt="图片" src="https://user-images.githubusercontent.com/507615/195062315-26453289-dca8-4cc2-920d-dec9e84e4b0d.png">

**Comment by qcxiaoshuai-snake** [comment]
@afc163 #37951

**Comment by afc163** [comment]
没必要提新 issue，在这里回复，提供可重新的在线 codesandbox 即可。

**Comment by qcxiaoshuai-snake** [comment]
https://codesandbox.io/s/lucid-rhodes-80jip8
看看这个吧
之前给你的那个 我这边看到的 和你那边看到的不一样 真奇怪

**Comment by qcxiaoshuai-snake** [comment]
@afc163 https://codesandbox.io/s/lucid-rhodes-80jip8
看看这个吧
之前给你的那个 我这边看到的 和你那边看到的不一样 真奇怪

**Comment by qcxiaoshuai-snake** [comment]
@afc163 收到邮件 不提供 代码 好像3天后 会被关闭

**Comment by afc163** [comment]
好像没有发现问题？

<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/195068002-0c392b26-ef3e-4558-80d8-50db3cf8de4a.png">

**Comment by afc163** [comment]
我知道了，你需要看一下 https://ant.design/components/table-cn/#components-table-demo-tree-data

**Comment by qcxiaoshuai-snake** [comment]
@afc163 但是这个配置还是有点隐蔽  我看网上有很多提了相关的问题 但是都没有人给出解答 😂 先这样吧
