### ISSUE TITLE
Cannot test input component on the change event.

### ISSUE THREAD

**Issue by DmytriyZahrebelny** [ant-design/ant-design#37959]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-input-test-dpup2c?file=/src/App.test.tsx)

### Steps to reproduce

I try to do the event onChange on the Input component and pass a new value to the component.

component
```
export const App = () => {
  const [value, setValue] = useState("initialValue");

  const onChange = (evt: FormEvent<HTMLInputElement>) => {
    setValue(evt.currentTarget.value);
  };

  return (
    <Row style={{ margin: 50 }}>
      <Col span={12}>
        <Input
          placeholder="input..."
          data-sdet="text-input"
          value={value}
          onChange={onChange}
        />
      </Col>
    </Row>
  );
};
```

test
```
describe("<App />", () => {
  it("test", () => {
    render(<App />);
    const user = userEvent.setup();

    const input = screen.getByDisplayValue("initialValue");
    user.type(input, "newValue");

    expect(input).toHaveValue("newValue");
  });
});
```

### What is expected?

I would expect that `user.type(input, "newValue")` will change a value in the Input.

### What is actually happening?

The container of the component has an initial value.

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.0.0 |
| System | All |
| Browser | Chrome |

**Comment by afc163** [comment]
Native input element has same behavior, should be it an none-antd issue? https://codesandbox.io/s/antd-input-test-forked-h3onrf?file=/src/App.tsx

**Comment by wangmeijian** [comment]
try this
```jsx
user.simulate('change', {
  target: {
    value: 'newValue',
  },
});
```
