### ISSUE TITLE
RangePicker日期控件显示bug问题

### ISSUE THREAD

**Issue by wb-chenlong** [ant-design/ant-design#3795]
#### 发生问题的环境是：

- antd 版本:  1.6.0
- 操作系统及其版本:  win7 x64
- 浏览器及其版本: chrome 49

#### 您做了什么？请提供尽可能详细的重现步骤。

在使用RangePicker日期控件时，format="YYYY-MM-DD HH:mm:ss"，这个是官网demo给出的事例，但是渲染的时候，会有bug，见下图
![image](https://cloud.githubusercontent.com/assets/14194437/20203715/a425dae4-a804-11e6-8c58-0f83d6c4ab68.png)

![image](https://cloud.githubusercontent.com/assets/14194437/20203703/8db15e1e-a804-11e6-876b-0608352c8512.png)

但是如果改成 这样： format="yyyy-MM-dd HH:mm:ss" || format="YYYY-MM-dd HH:mm:ss" 就不会出现这样的显示bug。

#### 您期待的结果是:

一般我们都会按照官网的demo来进行本地开发，遇到这样的情况会比较没有头绪，而且也无报错提示。希望能做好官网的demo事例，以及测试的各个环节，不然试错成本太大。

**Comment by afc163** [comment]
antd@1.x 请看 1.x 的文档：http://1x.ant.design/
