### ISSUE TITLE
当最外层dom高度比较小时select下拉框会遮挡输入框

### ISSUE THREAD

**Issue by gtt011029** [ant-design/ant-design#37965]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-gould-s1pjn8?file=/index.js:595-652)

### Steps to reproduce

当最外层dom高度比较小时， 使用getPopupContainer={() => document.getElementById("area")}， area的高度足够
select下拉框会遮挡输入框

### What is expected?

不被遮挡

### What is actually happening?

当最外层dom高度比较小时， 使用getPopupContainer={() => document.getElementById("area")}， area的高度足够
select下拉框会遮挡输入框

![image](https://user-images.githubusercontent.com/45391413/195232316-7724bafa-4155-4cff-a151-1d821e272ecb.png)

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
这是两难局面，目前的实现方式无法避免这样的问题。
