### ISSUE TITLE
Affix component breaks Tabs style

### ISSUE THREAD

**Issue by fihorvat** [ant-design/ant-design#37961]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-pine-tvurdk?file=/src/App.js)

### Steps to reproduce

1. Create the `Tabs` component and use the `renderTabBar` prop in order to customize `TabBar`.
2. Inside `renderTabBar` prop wrap the `TabBar` component inside `Affix` component.
3. Inside the `Items` collection add some items with long scrollable content.
4. Notice that the `TabBar` component style breaks into two lines and all the styles are lost (colors and InkBar)

```jsx
<Tabs
    renderTabBar={(props, TabBar) => (
      <Affix>
        <TabBar {...props} style={{ backgroundColor: "lightGray" }} />
      </Affix>
)}
...
```

### What is expected?

The tabs style should stay the same as it was before.

### What is actually happening?

The `TabBar` component style breaks into two lines and all the styles are lost (colors and InkBar).

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome (Latest) |

---
We use the `Drawer` component with some header and `Tabs` with long scrollable content. The current behavior (in version 3) is that `TabBar` stays on the top of the drawer as we scroll and we would love to have it going forwards. Now we are upgrading from version 3 and the style broke.
If the issue is that the `Ąffix` component is not compatible with `Tabs`. Could you please propose some other solution that could work?
This is how it looks in version 3:
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-liskov-0t09t9?file=/src/App.js)

**Comment by afc163** [comment]
Try https://ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar

**Comment by fihorvat** [comment]
Thanks, @afc163. We found the solution by positioning `TabBar` through `tabBarStyle` prop like:

```jsx
<Tabs
  tabBarStyle={{ position: "sticky", top: 0, zIndex: 10, backgroundColor: "lightGray" }}
  items={getItems().map((section) => ({
    key: section.key,
    label: section.name,
    children: section.content()
  }))}
/>
```
