### ISSUE TITLE
Tabs内有携带offsetTop属性的Affix时，切换会有残影抖动

### ISSUE THREAD

**Issue by fancyqin** [ant-design/ant-design#37970]
### Reproduction link

[https://stackblitz.com/edit/react-1jxp3p?file=src/App.js](https://stackblitz.com/edit/react-1jxp3p?file=src/App.js)

### Steps to reproduce

Tabs内容项有固钉Affix组件，且Affix组件设置offsetTop，切换Tabs选项，切回该Tab项时，Affix内容在初始化时会发生抖动残影。

### What is expected?

Tabs不使用destroyInactiveTabPane时，消除Affix内容的抖动和残影。

### What is actually happening?

发生抖动残影

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by pengyw97** [comment]
can i work for this issue ? @afc163

**Comment by afc163** [comment]
sure!

**Comment by imoctopus** [comment]
https://github.com/ant-design/ant-design/blob/ad3c7747e155ad0dd9e13a1a91417709fde73082/components/affix/index.tsx#L176-L177
这里 `width` 和 `height` 计算为 0 时，导致出现抖动，我可以提个 PR 吗？
