### ISSUE TITLE
Datasource children filtering

### ISSUE THREAD

**Issue by werneerm** [ant-design/ant-design#37972]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0hio79?file=/index.js)

### Steps to reproduce

Just use a dataSource with children and try the onFIlter on a column.

### What is expected?

I would expect the children to be filtered as well.

### What is actually happening?

Currently if i want to filter on the table and the dataSource has children it will only filter in the parents and does not in the children. The main issue that you can not filter in the children only in parents.

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.01 |
| System | All |
| Browser | All |

**Comment by PawelKonie99** [comment]
I've got same problem, can someone help with that?

**Comment by SleepWalker** [comment]
Did someone found a better solution then creating a local state and managing the filtering manually?

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/47170
