### ISSUE TITLE
InputNumber 首次输入 format 参数问题

### ISSUE THREAD

**Issue by eyouyou** [ant-design/ant-design#37979]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/green-night-nqc6s9?file=/index.js)

### Steps to reproduce

首次输入

### What is expected?

userTyping 为true时 input不应该为空

### What is actually happening?

userTyping 为true时 input为空

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.0.21 |
| System | win11 |
| Browser | firefox 105.0.3 |

**Comment by b-yp** [comment]
对于 input 文档里面并没有特别说明，我注意到有两种情况 input 是有值的
1. 当输入框从意外字符到有效字符时，input 会被赋值为最初的有效值（而  value 是打印不到这个值的，比如输入 `123abc`，然后我们再删掉 `abc`，这个时候不会打印任何值，我们再输入一个有效值，或者删掉一个值，这时候 input 打印的则是 `123`）
2. 当输入了意外的字符，这个时候 formatter 已经不会执行了，这时候按 enter 键，则会执行 formatter，而第一次执行时 input 的值正是当前输入框的值，而 value 是经过默认处理过的值（比如输入 `123abc`，按 enter，input 为 `123abc`，value 为 `123`）

**Comment by afc163** [comment]
formatter + 受控模式造成的。

**Comment by zombieJ** [comment]
Not an issue in v5 any more.
