### ISSUE TITLE
关于Input.Password组件密码明文和加密切换

### ISSUE THREAD

**Issue by zhengjialux** [ant-design/ant-design#37999]
### What problem does this feature solve?

例子：https://codepen.io/zhengjialux/pen/VwxgaqP
场景：在我们产品中有个专门修改密码的“页面”。修改密码后并不会去更新整个页面。
需求：
1、在密码框中输入密码后点击眼睛明文显示，input的type会变成text
2、点击保存后input的type并没有变回password模式，密码还是明文可见的。

### What does the proposed API look like?

希望加密和明文显示的状态开发者可控。

**Comment by afc163** [comment]
看上去可以让开发者显示控制 `type="password | text"`

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/37900
这个是不是解决问题？

**Comment by zhengjialux** [comment]
> #37900 这个是不是解决问题？

不是一个问题，我这个不是bug。是需求password组件的切换状态灵活可控。

**Comment by afc163** [comment]
需要一个 passwordVisible 受控属性。

**Comment by tonny008** [comment]
password现在只有visibilityToggle，意思是给加visible onVisibleChange两个属性，使他变成受控状态

**Comment by zhengjialux** [comment]
> password现在只有visibilityToggle，意思是给加visible onVisibleChange两个属性，使他变成受控状态

对的哥

**Comment by zhengjialux** [comment]
> 需要一个 passwordVisible 受控属性。

没错哥

**Comment by MrHeer** [comment]
有人在做这个了吗？没有的话我可以来做一下。

**Comment by afc163** [comment]
已支持 https://github.com/ant-design/ant-design/pull/38216
