### ISSUE TITLE
Ellipse shows expanded content before collapse causing flick

### ISSUE THREAD

**Issue by tonny008** [ant-design/ant-design#37998]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suffix-antd-4-23-5-forked-o24tt9?file=/demo.js)

### Steps to reproduce

click toggle to toggle ellipse

### What is expected?

ellipse should show collapsed at first time without showing the expanded content

### What is actually happening?

expanded content show first and then collapse.

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18 |
| System | mac |
| Browser | chrome 106 |

**Comment by zombieJ** [comment]
Sorry for delay. It's by design since mount for empty content is not friend with SSR SEO. You can HOC Typography to render empty for first mount and `useLayoutEffect` to mount it avoid blink.
