### ISSUE TITLE
5.0.0-alpha.2 样式丢失  vite   react

### ISSUE THREAD

**Issue by ALongLi** [ant-design/ant-design#37991]
### Reproduction link

[https://github.com/ALongLi/vitejs-vite-tdbz72](https://github.com/ALongLi/vitejs-vite-tdbz72)

### Steps to reproduce

运行直接看到

### What is expected?

样式正常

### What is actually happening?

样式丢失 

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | win10 |
| Browser | chrome87 |

---
在stackblitz 样式正常显示， 在 本地 win10 机器中运行后样式丢失
![image](https://user-images.githubusercontent.com/20749911/195490999-f1b9a2a6-19b7-428c-b720-dc03143c9dfe.png)

![image](https://user-images.githubusercontent.com/20749911/195490776-9f671a3d-ed86-42c9-beab-fb79a627ac93.png)

**Comment by ALongLi** [comment]
补充： 应该是浏览器兼容性问题 ，edge 106.0.1370.37 版本能正常显示样式，chrome 87.0.4280.66不显示样式

**Comment by ALongLi** [comment]
![image](https://user-images.githubusercontent.com/20749911/195492871-32f324bb-34f8-4a2e-868e-ee9857a1142d.png)

`:where(.css-dev-only-do-not-override-18jsc2e).ant-btn-dashed.ant-btn-dangerous`

where chrome87 不支持

**Comment by zombieJ** [comment]
<img width="648" alt="截屏2022-10-13 11 38 17" src="https://user-images.githubusercontent.com/5378891/195493616-fc42ba10-1a86-4a13-a574-efdb7564c9dc.png">

**Comment by zombieJ** [comment]
这个之前有考虑过是否要自动降级，但是想到自动降级会导致在不同游览器里 selector 权重不一致。所以这边就没有处理。还是按照 last 2 version 的规则来了。

**Comment by ALongLi** [comment]
这个太激进了吧，支持现代 JavaScript 语法的浏览器都不能运行了，  chrome版本升的那么快，用使用率应该会更好吧

**Comment by ALongLi** [comment]
或者有什么方式 能支持到 Chrome >=87
