### ISSUE TITLE
建议：组件页的左侧导航栏采用Affix

### ISSUE THREAD

**Issue by jinmmd** [ant-design/ant-design#3800]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本: win7 专业版
- 浏览器及其版本: chrome 54.0.2840

#### 您做了什么？请提供尽可能详细的重现步骤。

浏览组件-表单页面，展开所有代码

#### 您期待的结果是:

滚动页面到下面时，左侧导航栏固定浮动在左侧

#### 实际上的结果是:

导航栏不在视野中，需要返回到顶端

**Comment by afc163** [comment]
Affix 会导致底部部分菜单始终在视野外，现在的导航布局是设计师考量过的，暂不修改。
