### ISSUE TITLE
<Breadcrumb.Item> can not render {0}

### ISSUE THREAD

**Issue by ziposcar** [ant-design/ant-design#38004]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3qz8z9)

### Steps to reproduce

Just run it.

### What is expected?

Two same Breadcrumb.

### What is actually happening?

First Breadcrumb has no 0.

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.2.0 |
| System | windows |
| Browser | Chrome |

---
Maybe it should be considered empty only when it is  ' content === "" ' ?

**Comment by kiner-tang** [comment]
mark
