### ISSUE TITLE
Antd Menu openKeys in submenu

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#38017]
### Reproduction link

[https://e4yvjj.csb.app/user5-1](https://e4yvjj.csb.app/user5-1)

### Steps to reproduce

Click the link
User 5 should only be open when in page 5.1 or 5.2
otherwise closed

### What is expected?

User 5 should only be open when in page 5.1 or 5.2

### What is actually happening?

User 5 is closed when refreshed even 5.1 or 5.2 is active

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 17.0.2 |
| System | Mac Os Monterey |
| Browser | Google Chrome |

**Comment by tempoeric** [comment]
@afc163  @zombieJ  @MadCcc can I ask help for this? thanks in advance

**Comment by afc163** [comment]
Could you record a screen video?

**Comment by zombieJ** [comment]
Where is the `openKeys` config in your reproduce?

**Comment by tempoeric** [comment]
> Where is the `openKeys` config in your reproduce?

should i use open keys? i ask this in the discussion also and no one is replying so i consider this an issue

**Comment by tempoeric** [comment]
what i want is if the path user 5-1 or 5-2 is active the parent user 5 should not close when refresh and also close when i switch tabs

**Comment by zombieJ** [comment]
Use `openKeys` to handle Menu expand item. React will lose context and re-render all when page refresh.

**Comment by tempoeric** [comment]
> Use `openKeys` to handle Menu expand item. React will lose context and re-render all when page refresh.

do you have sample to use openkeys? based on the documentation its only defaultopenkeys

**Comment by tempoeric** [comment]
@zombieJ if i add open keys it does not close i only want it to open when the child is active
![image](https://user-images.githubusercontent.com/42777871/196147272-133f6545-8af9-43a7-aadd-0fe70580b559.png)
