### ISSUE TITLE
Mention 组件点击 focus 定位问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3801]
在线演示：https://ant.design/components/mention/

## Chrome 问题及重现步骤

1. 点击空白处。[示意图](https://zos.alipayobjects.com/rmsportal/nrWeORmKqwhypMt.png)
2. focus 到了文字开头。（**非预期行为**）
3. 点击外部 blur。
4. 再次点击空白处。[示意图](https://zos.alipayobjects.com/rmsportal/nrWeORmKqwhypMt.png)
5. focus 到文字尾部。（预期行为）

## Firefox 问题及重现步骤

1. 点击空白处。[示意图](https://zos.alipayobjects.com/rmsportal/nrWeORmKqwhypMt.png)
2. focus 到了文字尾部。（预期行为）
3. 点击外部 blur。
4. 再次点击空白处。[示意图](https://zos.alipayobjects.com/rmsportal/nrWeORmKqwhypMt.png)
5. focus 到文字开头。（**非预期行为**）

**Comment by RaoHai** [comment]
tnpm -i

**Comment by zheeeng** [comment]
Hi, @RaoHai There is another issue on Mention Component.

Click on Mention will trigger onChange event, and if the Mention is multi-lines, the onChange event will be fired twice, it seems unexpected. e.g. Manually set value of mention, focus event fired, and the cursor is positioned at the start of the text.

**Comment by afc163** [comment]
@RaoHai

**Comment by afc163** [comment]
@RaoHai 有进展不

**Comment by zheeeng** [comment]
Didn't dig into this draft.js, I have an assumption that [Selection](https://developer.mozilla.org/en-US/docs/Web/API/Selection) API may benefit this problem. Maybe we could try to save and restore the position of the selection cursor in handling change/input event.

**Comment by afc163** [comment]
Duplicate of #12931
