### ISSUE TITLE
Input.password输入框的显示和隐藏建议加一个切换事件的状态，通过改变这个状态的只，是否密码为显示或隐藏

### ISSUE THREAD

**Issue by zjtdsg** [ant-design/ant-design#38013]
### What problem does this feature solve?

当密码处于展示状态时，此时改变输入框的状态，使输入框disabled=true,密码依然处于展示状态
目前需求:当输入框禁止输入时，此时密码也需要隐藏展示
因此我需要一个一个暴露的状态可以控制输入框内的密码展示/隐藏，以及控制控制切换的图标状态

### What does the proposed API look like?

<Input.Password 
placeholder='请输入'
 passwordShow={true/false}      //期望API
 />

**Comment by afc163** [comment]
Duplicate of #37999
