### ISSUE TITLE
Progress component type dashboard and circle doesn't work correctly in safari with zoom in/out

### ISSUE THREAD

**Issue by EarlOld** [ant-design/ant-design#38026]
### Reproduction link

[https://j44b5p.csb.app/](https://j44b5p.csb.app/)

### Steps to reproduce

1. Open page in safari
2. Press command  (zoom in) or command- (zoom out)

### What is expected?

Progress component displayed correctly

### What is actually happening?

Progress component broken, I can't see it, widget is cut 

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.0.0 |
| System | MacOS |
| Browser | Safari  15.6 (17613.3.9.1.5) |

---
Looks like transform-origin CSS property doesn't work

https://user-images.githubusercontent.com/24506752/195802281-a13da9c8-b288-4d82-bb2b-65a417b8406a.mov

**Comment by Raz-Danielyan** [comment]
just add width, and height to the mother element of SVG-is and it will automatically fix your problem.

**Comment by edc-hui** [comment]
let me fix this problem.

**Comment by singlehcc** [comment]
提了个pr麻烦看一下哈

**Comment by singlehcc** [comment]
@afc163
