### ISSUE TITLE
打完包出现了跟你们官网一样的bug

### ISSUE THREAD

**Issue by qi-Nian-Jin-Xi** [ant-design/ant-design#38020]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn/](https://ant-design.antgroup.com/components/input-cn/)

### Steps to reproduce

https://ant-design.antgroup.com/components/input-cn/

### What is expected?

导航没有TextArea

### What is actually happening?

打完包 导航有TextArea

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 17 |
| System | windows |
| Browser | 谷歌 |

---
我们的软件打完包也是这样，一样的问题

**Comment by zombieJ** [comment]
看一下是否依赖了 dist，rc-textarea 里已经修复。

**Comment by afc163** [comment]
https://github.com/react-component/textarea/pull/23
