### ISSUE TITLE
Dropdown+Menu组件onClick出现异常

### ISSUE THREAD

**Issue by yunfeihuang** [ant-design/ant-design#3802]
#### 发生问题的环境是：

- antd 版本:2.1.0
- 操作系统及其版本:window7
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。
renderBatchButton() {
    return(
      <span>
        <Dropdown overlay={this.renderExportMenu("2")}>
          <button className="btn-icon">
            <i className="iconfont">&#xe62c;</i>
            <span>导出出库单</span>
          </button>
        </Dropdown>
        <Dropdown overlay={this.renderExportMenu("3")}>
          <button className="btn-icon">
            <i className="iconfont">&#xe62c;</i>
            <span>导出发货单</span>
          </button>
        </Dropdown>
      </span>
    );
  }
  
  renderExportMenu(category) {
    let exportFile=({key})=>{
      console.log(key)
    }
    let items=[];
    if(this.props.global.template_list){
      items=this.props.global.template_list.map((item)=>{
        if(category===item.category){
          return (<Menu.Item key={item.id}>{item.name}</Menu.Item>);
        }
      });
    }
    return (<Menu onClick={exportFile}>{items}</Menu>);
  }

弹出的菜单后点击菜单项出现异常

antd.min.js:21 Uncaught TypeError: Cannot read property 'props' of null(anonymous function) @ antd.min.js:21(anonymous function) @ antd.min.js:18forEachSingleChild @ vendor.js?v=0.5711554843557449:484traverseAllChildrenImpl @ vendor.js?v=0.5711554843557449:1458traverseAllChildrenImpl @ vendor.js?v=0.5711554843557449:1474traverseAllChildren @ vendor.js?v=0.5711554843557449:1553forEachChildren @ vendor.js?v=0.5711554843557449:504a @ antd.min.js:18i @ antd.min.js:21componentWillReceiveProps @ antd.min.js:21chainedFunction @ vendor.js?v=0.5711554843557449:2510(anonymous function) @ vendor.js?v=0.5711554843557449:15641measureLifeCyclePerf @ vendor.js?v=0.5711554843557449:15107updateComponent @ vendor.js?v=0.5711554843557449:15640receiveComponent @ vendor.js?v=0.5711554843557449:15577receiveComponent @ vendor.js?v=0.5711554843557449:7826_updateRenderedComponent @ vendor.js?v=0.5711554843557449:15784_performComponentUpdate @ vendor.js?v=0.5711554843557449:15754updateComponent @ vendor.js?v=0.5711554843557449:15675performUpdateIfNecessary @ vendor.js?v=0.5711554843557449:15591performUpdateIfNecessary @ vendor.js?v=0.5711554843557449:7858runBatchedUpdates @ vendor.js?v=0.5711554843557449:7455perform @ vendor.js?v=0.5711554843557449:8740perform @ vendor.js?v=0.5711554843557449:8740perform @ vendor.js?v=0.5711554843557449:7394flushBatchedUpdates @ vendor.js?v=0.5711554843557449:7477closeAll @ vendor.js?v=0.5711554843557449:8806perform @ vendor.js?v=0.5711554843557449:8753batchedUpdates @ vendor.js?v=0.5711554843557449:17610batchedUpdates @ vendor.js?v=0.5711554843557449:7402dispatchEvent @ vendor.js?v=0.5711554843557449:17770
antd.min.js:21 Warning: performUpdateIfNecessary: Unexpected batch number (current 34, pending 31)(anonymous function) @ antd.min.js:21(anonymous function) @ antd.min.js:33printWarning @ vendor.js?v=0.5711554843557449:1280warning @ vendor.js?v=0.5711554843557449:1304performUpdateIfNecessary @ vendor.js?v=0.5711554843557449:7850runBatchedUpdates @ vendor.js?v=0.5711554843557449:7455perform @ vendor.js?v=0.5711554843557449:8740perform @ vendor.js?v=0.5711554843557449:8740perform @ vendor.js?v=0.5711554843557449:7394flushBatchedUpdates @ vendor.js?v=0.5711554843557449:7477closeAll @ vendor.js?v=0.5711554843557449:8806perform @ vendor.js?v=0.5711554843557449:8753batchedUpdates @ vendor.js?v=0.5711554843557449:17610enqueueUpdate @ vendor.js?v=0.5711554843557449:7505enqueueUpdate @ vendor.js?v=0.5711554843557449:16575enqueueSetState @ vendor.js?v=0.5711554843557449:16760ReactComponent.setState @ vendor.js?v=0.5711554843557449:1736getOpenChangesOnItemHover @ antd.min.js:21onItemHover @ antd.min.js:34o.menuItemMouseLeaveFn @ antd.min.js:34

**Comment by afc163** [comment]
代码请格式化到可阅读的状态。https://guides.github.com/features/mastering-markdown/
