### ISSUE TITLE
Input.TextArea 在body里面多出一个输入框,并且不能隐藏,官网可以定位到Input组件,右上角可以看到

### ISSUE THREAD

**Issue by liguonan888** [ant-design/ant-design#38052]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn/](https://ant-design.antgroup.com/components/input-cn/)

### Steps to reproduce

官网打开https://ant-design.antgroup.com/components/input-cn/ 右上角就会出现一个小的输入框

### What is expected?

无输入框

### What is actually happening?

有输入框
![企业微信截图_de7517b4-fdb4-4353-af8a-264a8377f5af](https://user-images.githubusercontent.com/54622682/196100093-55312b54-5c97-413b-a57f-bea603f6e61b.png)

![企业微信截图_7773c232-1ad2-42ef-b940-8e9c7de1a640](https://user-images.githubusercontent.com/54622682/196100114-b76ff9ec-ddf4-491b-9ab3-c48b68308ee4.png)

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React |  "react": "^18.0.10", |
| System | mac |
| Browser | 谷歌106 |

**Comment by lihansir** [comment]
把 lock 文件删了，重新安装一遍。antd 里边依赖的 rc-textarea 升级到 0.4.5 就好了

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/textarea/pull/23
