### ISSUE TITLE
1.x版本中，弹窗销毁时没有进行清理工作

### ISSUE THREAD

**Issue by maggiehe** [ant-design/ant-design#3805]
#### 发生问题的环境是：

- antd 版本: 1.11.2

#### 您做了什么？请提供尽可能详细的重现步骤。

在父组件中根据条件决定是否引入子组件，list中没有数据时，引入子组件（其中子组件中包含了弹窗）。

``` 
{ list.length <= 0 ? <Comp1 {...params} add={ this.add } /> : null }
```
调用子组件的addItem方法将关闭弹窗，并调用父组件传入的方法为list添加一条数据

```
addItem = (item) => {
   const {add} = this.props
   this.hideModal()
   this.props.add(item) 
}
```

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close now, if you can provide a re-producible demo, just re-open this issue.

**Comment by afc163** [comment]
https://github.com/react-component/dialog/blob/2fa3f58451eab35691efb7b30f8af7278e2cccd4/src/Dialog.tsx#L319

这句可能需要在 componentWillUnmount 里调用一下。

**Comment by yiminghe** [comment]
应该不是这个原因 willMount 里调用了 removeScrollingEffect https://github.com/react-component/dialog/blob/master/src/DialogWrap.tsx#L36

再查下

**Comment by afc163** [comment]
统一到 #4475 看。
