### ISSUE TITLE
table rowSelection 中fixed:"right" 不生效

### ISSUE THREAD

**Issue by DODO7419** [ant-design/ant-design#38064]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-kong-zhi-biao-ge-shu-xing-antd-4-23-5-forked-0p59e3?file=/demo.js)

### Steps to reproduce

配置table  rowSelection={{fixd:"right"}} 不生效

### What is expected?

期望选择框移动到右侧

### What is actually happening?

在左面

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac |
| Browser | 谷歌 |

**Comment by gallen-1240** [comment]
Hello, bro, how did you finally solve this problem?
