### ISSUE TITLE
样式兼容性

### ISSUE THREAD

**Issue by ALongLi** [ant-design/ant-design#38076]
### What problem does this feature solve?

样式兼容性

### What does the proposed API look like?

感觉有点激进，以前因为支持 ie ,跑在 chrome上没问题，现在 连 chrome 87都有兼容性问题，这种大项目感觉应该追求稳定性，应该像vite一样 chrome>=某个版本 ， last 2 version 这种动态版本，容易出现小问题，可能升级个小版本，重新构建后就跑不起来了

**Comment by afc163** [comment]
追求兼容性可以继续使用 v4 版本，我们还会继续提供支持。
