### ISSUE TITLE
Antd menu not closing submenu when child is not active

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#38078]
### Reproduction link

[https://e4yvjj.csb.app/user4](https://e4yvjj.csb.app/user4)

### Steps to reproduce

Click the sandbox link
Click user 5 and click any of the submenu under user 5
Then click any of the parent menu in the sidebar
User 5 should close since the submenu is not active

### What is expected?

Should Close the parent menu when submenu is not active

### What is actually happening?

parent menu is not closing even though sub menu is not active

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
You can control `openKeys` as your need.

**Comment by tempoeric** [comment]
im using openKeys and onOpenchange here @afc163

**Comment by tempoeric** [comment]
could you help me here please @afc163
