### ISSUE TITLE
Table 自定义选择项 文案 全选所有是否可更改为全选当页？

### ISSUE THREAD

**Issue by pengyw97** [ant-design/ant-design#38086]
### What problem does this feature solve?

在Table自定义选择项中提供了一些内置选项： 
1. Table.SELECTION_ALL 中文文案为全选所有
2. Table.SELECTION_INVERT 中文文案为反选当页

点击全选所有后，实际上只全选了当前页面的所有选项，并没有全选所有。
我认为改为全选当页后，既可以和内置的反选当页相符合，也让用户更容易理解。

### What does the proposed API look like?

Table.SELECTION_ALL  全选所有 更改为 全选当页

**Comment by pengyw97** [comment]
![image](https://user-images.githubusercontent.com/48945950/196392999-aa6be8cc-ccec-4974-86ab-1012f1f70804.png)

**Comment by afc163** [comment]
Table 有 locale 属性可以自行覆盖文案。
