### ISSUE TITLE
antd input 受控模式下在umi的 models存input的value和change时中文输入不了

### ISSUE THREAD

**Issue by QDyanbing** [ant-design/ant-design#38081]
### Reproduction link

[https://github.com/QDyanbing/antd-input](https://github.com/QDyanbing/antd-input)

### Steps to reproduce

在输入框中输入 "测试"

### What is expected?

可以输入中文

### What is actually happening?

不能输入中文

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | ^18.0.0 |
| System | mac |
| Browser | 106.0.5249.119（正式版本） (arm64) |

**Comment by afc163** [comment]
把 Input 换成原生 input 也有一样的问题，应该和 antd 无关。

**Comment by afc163** [comment]
建议去 umi 那里咨询

**Comment by QDyanbing** [comment]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/66234749/196845414-a7946cd7-3632-496d-8eb5-25389899c01a.png">

**Comment by QDyanbing** [comment]
采用以上方式可以解决

**Comment by afc163** [comment]
这里重新渲染了整个页面，这会影响渲染和交互性能，不应该用这种方式解决。

**Comment by afc163** [comment]
问题不在这，问题在于为啥 umi 下这么用会刷新整个页面。

**Comment by chenJJ-88** [comment]
遇到同样的问题了，比如输入拼音，他会将拼音和中文一起放进输入框
