### ISSUE TITLE
Modal.confirm创建的弹窗，okButton按钮状态问题

### ISSUE THREAD

**Issue by EdogawaConan1996** [ant-design/ant-design#38099]
### Reproduction link

[https://ant-design.antgroup.com/components/modal-cn/](https://ant-design.antgroup.com/components/modal-cn/)

### Steps to reproduce

使用Modal.confirm或Modal.info等方法创建弹窗

### What is expected?

创建弹窗后，okButton按钮处于正常状态，鼠标hover上去后正常展示按钮的hover态

### What is actually happening?

okButton处于focus状态，且鼠标hover上去后无法展示按钮的hover态

| Environment | Info |
| --- | --- |
| antd | 4.16.12 |
| React | 17.0.2 |
| System | macos 12.1 |
| Browser | chrome 106.0.5249.103 |

**Comment by afc163** [comment]
这是预期行为。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33270#issuecomment-991890680

**Comment by EdogawaConan1996** [comment]
我访问了 [#33270(comment)](https://github.com/ant-design/ant-design/issues/33270#issuecomment-991890680) ，最后的评论提到这样设置是为了“键盘可访问性”，可以简单解释下吗

**Comment by yoyo837** [comment]
> 我访问了 [#33270(comment)](https://github.com/ant-design/ant-design/issues/33270#issuecomment-991890680) ，最后的评论提到这样设置是为了“键盘可访问性”，可以简单解释下吗

不碰鼠标的操作支持
