### ISSUE TITLE
Form下Mention 设置initialValue初始状态值，状态刷新后，Mention内容不改变。

### ISSUE THREAD

**Issue by ThinkCats** [ant-design/ant-design#3809]
#### 发生问题的环境是：

- antd 版本: 2.3.0
- 操作系统及其版本: macos 10.11.6
- 浏览器及其版本: Chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

在Form表单中使用Mention组件，并且对该Mention初始化数据。采用的是flux模式，初始化过程中，Mention 的状态内容为初始的字符串”helloworld“，调用toEditorState展示，无问题。但当数据加载完毕后，Mention的状态内容为服务器获取的字符串内容，此时状态刷新，新的Mention状态值并没有刷新到界面上，展示仍然是”hello world“。

经测试，使用Input组件，在该场景下，会刷新取到新的状态值。Mention不行。

#### 您期待的结果是:

当Mention的状态发生改变后，Mention能显示最新的状态值。

**Comment by RaoHai** [comment]
受控模式的写法参考这个：
https://ant.design/components/mention/#components-mention-demo-controllder-simple

最好能提供一个可重现的 demo：
http://codepen.io/benjycui/pen/KgPZrE

**Comment by Autumnwater** [comment]
试出来了，form的方法一个个试过去吧，那东西官方demo没更新，有的方法能用，有的不能用

**Comment by benjycui** [comment]
> 试出来了，form的方法一个个试过去吧，那东西官方demo没更新，有的方法能用，有的不能用

请问不能用的有哪些？方便我们更新文档。
