### ISSUE TITLE
升级到react0.14后出错了

### ISSUE THREAD

**Issue by wangyun** [ant-design/ant-design#381]
ERROR in ./~/antd/lib/affix/index.js
Module not found: Error: Cannot resolve module 'react/lib/joinClasses' in /home/dev/projects/admin-web/node_modules/antd/lib/affix
 @ ./~/antd/lib/affix/index.js 9:27-59

ERROR in ./~/antd/~/react-slick/lib/inner-slider.js
Module not found: Error: Cannot resolve module 'react/lib/EventListener' in /home/dev/projects/admin-web/node_modules/antd/node_modules/react-slick/lib
 @ ./~/antd/~/react-slick/lib/inner-slider.js 15:29-63

**Comment by afc163** [comment]
developing in #243
