### ISSUE TITLE
antd Tree 设置treeData无法设置TreeNode props

### ISSUE THREAD

**Issue by bilibilinatural** [ant-design/ant-design#38110]
### What problem does this feature solve?

新版本鼓励使用treeData渲染，但是这样的话就不能使用TreeNode prop配置项

### What does the proposed API look like?

TreeNodeProps = {disabled:true}

**Comment by bilibilinatural** [comment]
` <DirectoryTree
      multiple
      defaultExpandAll
      onSelect={onSelect}
      onExpand={onExpand}
      treeData={treeData}
    />`
这样如何添加TreeNode props的配置项

**Comment by afc163** [comment]
在 treeData 里加属性。

**Comment by bilibilinatural** [comment]
感谢回复，可能我文档看的不仔细，可以给个demo😂
`array<{key, title, children, [disabled, selectable]}>`，最后一个数组项就是TreeNode props的配置项吗，如果我想禁用鼠标移入显示title是不是就是
`treeData= [{ title: 'parent 1',key: '0-0',children:[]} ,[disabled]]`

**Comment by bilibilinatural** [comment]
> 在 treeData 里加属性。

感谢回复，可能我文档看的不仔细，可以给个demo吗😂
`array<{key, title, children, [disabled, selectable]}>`，最后一个数组项就是TreeNode props的配置项吗，如果我想禁用鼠标移入显示title是不是就是
`treeData= [{ title: 'parent 1',key: '0-0',children:[]} ,[disabled]]`
