### ISSUE TITLE
Image 相册模式 Image.PreviewGroup，如果里面的子项 src 有错误的话，相册模式会自动忽略该子项。如： <Image src="error.url" />

### ISSUE THREAD

**Issue by tigepro** [ant-design/ant-design#38112]
### Reproduction link

[https://codepen.io/fengyu_xu/pen/oNYJZjP](https://codepen.io/fengyu_xu/pen/oNYJZjP)

### Steps to reproduce

https://codepen.io/fengyu_xu/pen/oNYJZjP

### What is expected?

如果子项有错误 直接展示错误

### What is actually happening?

直接忽略，好像不存在该子项一样

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by huangkairan** [comment]
WIP
