### ISSUE TITLE
Transfer 中文语言包缺少titles配置导致运行错误，错误位置transfer/index.tsx:388行，424行

### ISSUE THREAD

**Issue by huicai-se** [ant-design/ant-design#38129]
### Reproduction link

[https://ant.design/components/transfer-cn/](https://ant.design/components/transfer-cn/)

### Steps to reproduce

使用官方的穿梭框中的表格穿梭框且将antd配置为中文语言

### What is expected?

不报错

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 所有版本 |
| System | 所有系统 |
| Browser | 所有浏览器 |

---
locale/zh_CN.tsx中Transfer下缺少titles配置

在transfer/index.tsx 388行
<List<KeyWise<RecordType>>
              prefixCls={`${prefixCls}-list`}
              titleText={titles[0]}
              dataSource={leftDataSource}

**Comment by kiner-tang** [comment]
确实是这样，我来加一下吧
