### ISSUE TITLE
Popover, Tooltip - how to render dynamically?

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#3812]
I'm trying to use one Popover for whole table just render differ content. But right now - no any success :(

Here is simplified version:
http://codepen.io/anon/pen/JbGBap?editors=0010

P.S.: in my real app i can't render popover for each row and i would like to use one popover and just change visibility/content for it dynamically. but i need to visually attach it to triggerNode. Any ideas?

**Comment by yesmeck** [comment]
Why not wrap the plus Button by Popover?

**Comment by afc163** [comment]
Just use Popover like @yesmeck said.

**Comment by varun-dev** [comment]
Has anyone been able to achieve this?
Calling popover programatically ??

**Comment by benjycui** [comment]
React components are not designed to called.

**Comment by varun-dev** [comment]
okay, thank  you for your response. I am a bit of React newbie
