### ISSUE TITLE
5.0.0-alpha.3  动态切换主题无法工作

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [ant-design/ant-design#38125]
### Reproduction link

[https://github.com/hu-tu-yi-shi/blog](https://github.com/hu-tu-yi-shi/blog)

### Steps to reproduce

1. 克隆代码   
2. npm run dev    
3. 不停的 点击 按钮【切换风格】  
4.  刚开始可以，点击多次之后，就会发现 风格没有变化，出现bug了  

### What is expected?

希望 点击切换风格， 可以正常切换

### What is actually happening?

切换几次后，就不工作了

| Environment | Info |
| --- | --- |
| antd | 5.0.0-alpha.3 |
| React | 18.2.0 |
| System | mac  |
| Browser | chrome 最新版 |

说明：

关于主题的控制代码 在这里 https://github.com/hu-tu-yi-shi/blog/blob/main/src/pages_comps/_app/Setter_AntdConfigProvider.tsx#L16

![image](https://user-images.githubusercontent.com/104620424/196843675-0b8575b6-1c58-425f-b94c-1299548ae9c7.png)

主题配置在这里  https://github.com/hu-tu-yi-shi/blog/blob/main/src/config/ThemeConfig.ts

![image](https://user-images.githubusercontent.com/104620424/196843719-209b73f7-26bc-4094-8cfb-61eefdc3d29f.png)

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/38089

**Comment by hu-tu-yi-shi** [comment]
@MadCcc   多谢，请问 下个 alpha什么时候出， 今天可以出吗
