### ISSUE TITLE
Inconsistent use of title case in the text for empty tables

### ISSUE THREAD

**Issue by angelaburon** [ant-design/ant-design#38120]
### Reproduction link

[https://preview.pro.ant.design/list/table-list](https://preview.pro.ant.design/list/table-list)

### Steps to reproduce

Type something that doesn't exist in the filters, hit the apply button and you will see the "No Data" text.

### What is expected?

The text should read "No data", without title case, for consistency with the rest of the elements in the system.

### What is actually happening?

The text reads "No Data", with title case.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | Any |
| System | Any |
| Browser | Any |

**Comment by zombieJ** [comment]
Thanks for feedback. Pls feel free to PR directly~

**Comment by angelaburon** [comment]
Thanks a lot!
