### ISSUE TITLE
5.0.0-alpha3 内部ConfigProvider修改theme会影响外部ConfigProvider

### ISSUE THREAD

**Issue by 1zilc** [ant-design/ant-design#38135]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-0-0-alpha-3-forked-4xgbki?file=/demo.js)

### Steps to reproduce

1. 点击按钮2，修改内部colorPrimary

### What is expected?

1. colorPrimary生效范围只在内部ConfigProvider包裹的组件中

### What is actually happening?

按钮1 和 按钮2 主题色都被修改了

| Environment | Info |
| --- | --- |
| antd | 5.0.0-alpha3 |
| React | 18 |
| System | macos 12.6 |
| Browser | chrome 106 |

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/38089
