### ISSUE TITLE
Feature request: Divider Item for SubMenu

### ISSUE THREAD

**Issue by jmatsushita** [ant-design/ant-design#3813]
In addition to `MenuItemGroup` it would be great to have a way to add a line separator as an `Item` between Items of the same level in the way [Bootstrap does it](http://getbootstrap.com/components/#btn-dropdowns-single) with `<li role="separator" class="divider"></li>`

**Comment by afc163** [comment]
https://ant.design/components/dropdown/#components-dropdown-demo-item

We already have this.

**Comment by afc163** [comment]
I just fix it's style in Menu.
