### ISSUE TITLE
时间选择器 time-picker 不支持 24:00 转换

### ISSUE THREAD

**Issue by MircoSans** [ant-design/ant-design#38141]
### What problem does this feature solve?

特定场景需要用到 24:00

关联
https://github.com/react-component/time-picker/issues/95#:~:text=from%20version%202.13.0%3A-,moment/moment%233102,-%2C%20if%20time%2Dpicker
### What does the proposed API look like?

https://github.com/moment/moment/pull/3102

``` jsx
<TimePicker
      format="kk:mm"
      defaultValue={moment(
      to,
      'kk:mm',
)}
></TimePicker>
```

**Comment by MadCcc** [comment]
moment 这种时间库支持的话应该是可以的，你的需求具体是什么？

**Comment by MircoSans** [comment]
> moment 这种时间库支持的话应该是可以的，你的需求具体是什么？

现在我使用这个格式化 kk:mm 时，时间选择器的小时直接不显示了

``` jsx
<TimePicker
      format="kk:mm"
      defaultValue={moment(
      to,
      'kk:mm',
)}
></TimePicker>
```

![image](https://user-images.githubusercontent.com/51395487/197102380-7b25577a-75f5-446c-8a7c-383e7a726bda.png)

**Comment by lbarakidouji** [comment]
希望支持选择24:00 +1

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/42494
