### ISSUE TITLE
2.4版本中的lib/index.js不见了

### ISSUE THREAD

**Issue by asoiso** [ant-design/ant-design#3814]
2.4版本中的package.json中的mian指向的lib/index.js不见了，
import {Modal, message} from 'antd';导入包报错，麻烦解决一下。

麻烦下次publish的时候检查一下，上次2.3版本丢了antd.css，这次lib/index.js入口文件丢了。

**Comment by asoiso** [comment]
幸苦了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3811#issuecomment-259972274
