### ISSUE TITLE
Pagination without last page control

### ISSUE THREAD

**Issue by dorijanf** [ant-design/ant-design#38156]
### What problem does this feature solve?

I am wondering if somebody managed to create this solution. The project I am currently working on displays 30.000 results in tables/lists and I was wondering if there is a way to change the pagination logic in a way where it doesn't display the last page rather an incremental number based on the current page.

The current ant design pagination looks like this:

[1] ... [4] [5] [6] [7] [8] ... [1452(lastPage)]

I am looking for something that looks like this:

< [1] ... [4] [5] [6] [7] [8] ... [10] >  ====>  [1] ... [11] [12] [13] [14] [15] ... [20]

or at least 

< [1] ... [4] [5] [6] [7] [8] >

Is it possible to do something like this with current antd?

### What does the proposed API look like?

I currently do not have a working example and before I try to implement something I would like to know if it is possible to have a workaround to implement this.

**Comment by afc163** [comment]
Set `total` to a limit number instead of the real count of table

**Comment by iamshanazar** [comment]
pagination.pageSize:is possibly 'undefined'
