### ISSUE TITLE
侧边栏菜单的二级菜单重叠

### ISSUE THREAD

**Issue by Hades-li** [ant-design/ant-design#38151]
### Reproduction link

[https://procomponents.ant.design/components/layout/](https://procomponents.ant.design/components/layout/)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/12124478/197135891-42d63bf7-42f7-4fed-a0d5-00121166730a.png)

侧栏导航->鼠标处于第二个菜单项的第二个二级菜单项上->然后往左滑动至第三个菜单项上，会出现两个 二级菜单项重叠

### What is expected?

菜单项不重叠，即第一个二级菜单项会消失

### What is actually happening?

二级菜单重叠展示

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | react 18.2.0 |
| System | win/mac |
| Browser | chrome/edge/safari |

**Comment by MadCcc** [comment]
procomponents 去这里 https://github.com/ant-design/pro-components
