### ISSUE TITLE
Autocomplete flickering with suffix icon on custom input.

### ISSUE THREAD

**Issue by Gurochka** [ant-design/ant-design#38157]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-23-6-forked-kgqi7y?file=/demo.tsx)

### Steps to reproduce

1. Type anything on upper input (with an arrow)
2. Click outside field
3. Click on an arrow in the upper input field

### What is expected?

Autocomplete list opens.

### What is actually happening?

Autocomplete list opens and closes immediately.

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Try https://codesandbox.io/s/basic-usage-antd-4-23-6-forked-wpzjmv

**Comment by Gurochka** [comment]
> Try https://codesandbox.io/s/basic-usage-antd-4-23-6-forked-wpzjmv

It doesn't fix anything. Autocomplete list still opens and closes immediately.
