### ISSUE TITLE
Table sort buttons `aria-label` is [object Object]

### ISSUE THREAD

**Issue by jmatelowski** [ant-design/ant-design#38155]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/filter-and-sorter-antd-4-23-6-forked-wmfq4g?file=/demo.tsx)

### Steps to reproduce

1. Open demo
2. Change any column title to ReactNode (`name` column already changed)
3. Inspect `th` `aria-label` prop

### What is expected?

aria-label="name sortable"

### What is actually happening?

aria-label="[object Object] sortable"
![image](https://user-images.githubusercontent.com/50398408/197164190-dbeda580-88ee-4702-a42b-7d5cde4d0fee.png)

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 16.14 |
| System | macOS |
| Browser | Chrome, Firefox |

---
Table columns documentation says that `column.title` supports `ReactNode` but unfortunatelly, if we provide the `ReactNode` instead of `string` the `aria-label` value is broken. It impede to table header cell accessibility. For example: it is difficult to get element by role in React Testing Library.

Added in https://github.com/ant-design/ant-design/pull/37167

**Comment by kiner-tang** [comment]
May i work on it?

**Comment by dgreene1** [comment]
@kiner-tang your change introduced this bug https://github.com/ant-design/ant-design/issues/39410 so if you can kindly please test your changes in a screen reader (like NVDA, VoiceOver, etc) that would help prevent regressions for non-visual users.

cc @mellis481
