### ISSUE TITLE
期待menu的api能够更加多样化

### ISSUE THREAD

**Issue by Musicminion** [ant-design/ant-design#38167]
### What problem does this feature solve?

menu（或者说顶栏）感觉是所有网站开发的一个基本需求，通常来说网页顶端会显示功能区域，有时候会显示用户的头像，登录按钮，配置网站的设置信息。
而基础的antdesign的menu没有提供能够左右布局，比如有些顶栏或者menu按钮我希望靠左边放置（或者在垂直页面，靠上放），有些按钮我希望靠右边，甚至或者我希望所有按钮居中设置。

### What does the proposed API look like?

布局：横向topBar可以设置左右分区，左边是功能区，右边是额外的功能区域，比如头像，登录按钮，设置按钮，由用户自定义

**Comment by Musicminion** [comment]
实际上，antdeisignpro提供了，但是被封装在pro layout里面，这让希望单独用到menu而有左右需求的人非常难办😂
期待更新

**Comment by afc163** [comment]
建议使用 ProLayout，antd Menu是原子化的，不会做布局封装。
