### ISSUE TITLE
Input.Search通过ref.input.value清空搜索值(此时ref.input.outerHTML的value里还显示之前搜索值)，组件获取焦点后依然显示之前搜索值

### ISSUE THREAD

**Issue by zixuemeng** [ant-design/ant-design#38171]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-dszmbi?file=/index.js)

### Steps to reproduce

搜索框输入123，点击清除Button(搜索框显示空)，再点击搜索框(搜索框显示123)

### What is expected?

能够通过清除Button清空搜索框内容，且再次focus时还是清空状态

### What is actually happening?

再次focus时还显示之前搜索内容

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 16.14.32 |
| System | macos |
| Browser | chrome版本 93.0.4577.63（正式版本） (arm64) |

---
如果通过ref.input.value方式不能清除的话，需要通过什么方式实现点击清除Button清除

**Comment by afc163** [comment]
请控制 value 属性。

**Comment by fantasy995** [comment]
我也碰到了这个问题，Input组件似乎并没有提供修改value的接口
