### ISSUE TITLE
竖向Step 自定义icon时样式问题

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#3817]
#### 发生问题的环境是：
- antd 版本: 2.4.1
- 操作系统及其版本: Ubuntu 16.04 (64-bit)
- 浏览器及其版本: chrome 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

引入 antd 了 Step, 设置成竖向展示，自定义icon

#### 您期待的结果是:

自定义的icon能大些

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/2271825/20235824/cb2d3752-a8d8-11e6-8ff6-91f3dcd1f9e4.png)

#### 可重现的在线演示

http://codepen.io/coderingz/pen/jVqPod

**Comment by benjycui** [comment]
先这样解决：

```jsx
<Icon type="xxx" style={{...}} />
```

**Comment by benjycui** [comment]
设计细节有些疑问，找设计确认中。
