### ISSUE TITLE
`expandable.indentSize` doesn't work

### ISSUE THREAD

**Issue by mohasarc** [ant-design/ant-design#38178]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-u9tvds?file=/index.js)

First of all I'd like to thank you for all the effort put into making this amazing library!

### Steps to reproduce

- Add an ant design Table into another as a nested table using `expandable`
- Set the value of `expandable.indentSize` of the parent table to 0.

### What is expected?

The indentation should change based on the specified value.

### What is actually happening?

The indentation didn't change,

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 18.2.0 |
| System | Ubuntu 20.04.5 LTS |
| Browser | Google Chrome 106.0.5249.119 |

---
I've had a look at previous similar issues, but none provide a working solution.

**Comment by kiner-tang** [comment]
when use `expandedRowRender`,It will be marked as `row` mode, but `indentSize` only support in `nest` mode.

- https://github.com/react-component/table/blob/2c6f53d900e254d8be0e37219283d57839d77fd3/src/Table.tsx#L278
- https://github.com/react-component/table/blob/2c6f53d900e254d8be0e37219283d57839d77fd3/src/Body/BodyRow.tsx#L149

It seem that you can use custom indent By custom style in React Element to solve this problem.

**Comment by afc163** [comment]
`indentSize` only support in nest mode.

**Comment by sm-nikolas** [comment]
`indentSize` only support in nest mode.
