### ISSUE TITLE
[antd: RangePicker] `dropdownClassName` is deprecated which will be removed in next major version. Please use `popupClassName` instead.

### ISSUE THREAD

**Issue by komarovalexander** [ant-design/ant-design#38185]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hevf0u?file=/index.js:0-427)

### Steps to reproduce

open provided demo link and see warning in console:
Warning: [antd: RangePicker] `dropdownClassName` is deprecated which will be removed in next major version. Please use `popupClassName` instead. 

but I already use popupClassName:  <TimePicker.RangePicker popupClassName="some-class" />

### What is expected?

no warning should appear

### What is actually happening?

Warning: [antd: RangePicker] `dropdownClassName` is deprecated which will be removed in next major version. Please use `popupClassName` instead. 

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by komarovalexander** [comment]
@kiner-tang , the issue is still actual, looks like it was not fixed for RangePicker
[antd: RangePicker] dropdownClassName is deprecated which will be removed in next major version. Please use popupClassName instead.
 "version": "4.24.4",
demo: https://codesandbox.io/s/antd-reproduction-template-forked-tlu0cd

**Comment by kiner-tang** [comment]
> @kiner-tang , the issue is still actual, looks like it was not fixed for RangePicker [antd: RangePicker] dropdownClassName is deprecated which will be removed in next major version. Please use popupClassName instead. "version": "4.24.4", demo: https://codesandbox.io/s/antd-reproduction-template-forked-tlu0cd

Yes, let me have a look
