### ISSUE TITLE
Badge组件没有配置text属性，空元素（类名ant-badge-status-text）消失

### ISSUE THREAD

**Issue by whale-jung** [ant-design/ant-design#38189]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/s9uokw?file=/demo.tsx)

### What is actually happening?

 

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react18.2.0 |
| System | widnow |
| Browser | chrome |

**Comment by whale-jung** [comment]
之前没有配置text属性空元素存在，这次迭代本地重新构建之后这个元素就消失了

**Comment by afc163** [comment]
在你提供的 demo 中没发现有啥问题。

**Comment by whale-jung** [comment]
https://github.com/ant-design/ant-design/pull/37681

**Comment by whale-jung** [comment]
https://github.com/ant-design/ant-design/pull/37681

这个fix引起的

**Comment by alienzhangyw** [comment]
> #37681
> 
> 这个fix引起的

啊这，之前一直把这个当作边距用的，可以把状态点（没用自带的text属性）和后面的内容分隔，现在需要自己加样式了。
