### ISSUE TITLE
tabs 的items 的forceRender 不生效

### ISSUE THREAD

**Issue by krulun** [ant-design/ant-design#38186]
### Reproduction link

[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce

  return (
    <Tabs activeKey={tabType} onChange={tabChange} 
      items={
        tableConfigs.map((table: BaseTableConfig, index) => {
          let {title, dateType} = table;
          return {
            label: title,
            key: dateType,
            children: props.children[index],
            forceRender: true,
            disabled: tabDisabled !== dateType
          }
        })
      }
    >
    </Tabs>
  )

其中props.children是slot, 为传入的react节点, 但没有渲染props.children这些节点

### What is expected?

期望forceRender生效, slot节点能执行

### What is actually happening?

slot节点没有执行

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 16.14.32 |
| System | mac |
| Browser | 谷歌 |

**Comment by krulun** [comment]
因为写了disabled, 所以没渲染.

**Comment by duzliang** [comment]
没有写 disabled，也不渲染

**Comment by yoyo837** [comment]
如果仍然有问题，请带复现打开一个新的issue.
