### ISSUE TITLE
下拉菜单点击没有出现下拉菜单问题

### ISSUE THREAD

**Issue by yunfeit** [ant-design/ant-design#3819]
#### 发生问题的环境是：

- antd 版本:2.4.0
- 操作系统及其版本:win10
- 浏览器及其版本:谷歌50.0.2661.102

#### 您做了什么？请提供尽可能详细的重现步骤。

const menu = (
  <Menu onClick={handleMenuClick}>
    <Menu.Item key="1">1st menu item</Menu.Item>
    <Menu.Item key="2">2nd menu item</Menu.Item>
    <Menu.Item key="3">3d menu item</Menu.Item>
  </Menu>
);
<Dropdown.Button onClick={handleButtonClick} overlay={menu} type="ghost">
      Dropdown
    </Dropdown.Button>

#### 您期待的结果是:

单击能出现下拉菜单

#### 实际上的结果是:

单击未出现下拉菜单

#### 可重现的在线演示

官网2.4.0的组件示例

**Comment by yesmeck** [comment]
重复 #3815
