### ISSUE TITLE
Select component - scroll to default bug

### ISSUE THREAD

**Issue by mmmbulochka** [ant-design/ant-design#38200]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-23-6-forked-ollnv4?file=/demo.tsx)

### Steps to reproduce

Open select component

### What is expected?

Dropdown will be scrolled to the selected option

### What is actually happening?

Opening for the first time - the menu scrolls two points higher (the selected item is not visible), opening for the second time everything works correctly (the selected item is visible in the drop-down list)

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | macOS 12.6 |
| Browser | chrome 106.0.5249.119 |

**Comment by zombieJ** [comment]
Seems not an issue for v5: https://codesandbox.io/s/basic-usage-antd-4-23-6-forked-q9cmnm?file=/demo.tsx
