### ISSUE TITLE
使用modal.info里面带有Form和Checkbox，Checkbox的值通过Form.useWatch来监听，但是拿到的值不对

### ISSUE THREAD

**Issue by lizhancheng** [ant-design/ant-design#38202]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-77ni4f?file=/index.js)

### Steps to reproduce

1、点击按钮
2、修改弹窗里的checkbox
3、点击ok
4、全局提示得到的checkbox值为undefined

### What is expected?

checkbox值对应显示正确

### What is actually happening?

无论是否勾选，checkbox值始终为undefined

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | MacOS |
| Browser | chrome107 |

**Comment by kiner-tang** [comment]
看起来是`useWatch`，这边直接使用`form.getFieldValue("isRemind")`获取是正常的
https://codesandbox.io/s/antd-reproduction-template-forked-2kd1h1

**Comment by ningshunqiang** [comment]
插眼

**Comment by zombieJ** [comment]
闭包问题，和 `useWatch` 无关：
https://codesandbox.io/s/antd-reproduction-template-forked-t7ufg4
