### ISSUE TITLE
关于antd Carousel组件竖向显示 横向滑动

### ISSUE THREAD

**Issue by codeLoseGay** [ant-design/ant-design#3820]
#### 发生问题的环境是：

- antd 版本:最新版本
- 操作系统及其版本:window
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

根据Carousel的示例代码 
```jsx
<Carousel vertical="true">
    <div><h3>1</h3></div>
    <div><h3>2</h3></div>
    <div><h3>3</h3></div>
    <div><h3>4</h3></div>
  </Carousel>
```
 和文档中的竖排显示竖排滑动效果不符 
我的是竖排显示 横向滑动

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
我帮你改了 Markdown 格式，以后自己注意。

Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by benjycui** [comment]
Close now, if you can provide a re-producible demo, just re-open this issue.
