### ISSUE TITLE
循环创建的form.item，删除后form表单还是存在该字段

### ISSUE THREAD

**Issue by KellenHe** [ant-design/ant-design#38225]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-23-6-forked-ereelg?file=/demo.tsx)

### Steps to reproduce

应该就是这个问题https://github.com/ant-design/ant-design/issues/21435
1、在item1中输入aaa，在item2中输入bbb
2、点击删除i，删除item2，再点击添加
3、item2里还存在bbb的值

### What is expected?

点击删除后再点击添加，会把之前的值带出来。使用setFieldsValue重置也不行。

### What is actually happening?

点击删除后再点击添加，不要有之前已经删除的值

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome106 |

**Comment by Wxh16144** [comment]
你可以将 Form 的 `preserve` 属性设置为 `false`。 默认是 `true`。
