### ISSUE TITLE
Menu Item属性中加入对menuitem增加click事件

### ISSUE THREAD

**Issue by 2449847346** [ant-design/ant-design#38221]
### What problem does this feature solve?

虽然label点击可以跳转对应路由，但点击menu-item中的padding以外的内容不会受到点击处理

### What does the proposed API look like?

###当前api情况

    item=[
        {
            key，
            icon，
            label:<span onClick={()=>history.push('/')}>测试</span>
        }
    ]
    

  <Menu
     selectedKeys={[selectedKey]}
     theme="dark"
     mode="inline"
     items={item}
     onClick={clickMenuItem}
 />

###点击menu-item padding范围不会触发click事件，仅限label

###需求新增click事件在每个item中，点击menu-item任意位置可触发相关事件

期望api：
    item=[
        {
            key，
            icon，
            label:<span >测试</span>,
            onClick:(e)=>history.push('/')
        }
    ]
整个menu-item点击都可触发相关事件

**Comment by afc163** [comment]
建议在 Menu 的 onClick 里做判断。

**Comment by 2449847346** [comment]
> 建议在 Menu 的 onClick 里做判断。
click拿不到item数据path吧？这样每次便利我都需要循环搜索key找到对应url-path吗？

**Comment by afc163** [comment]
或者 label 里改成 a 元素试试

**Comment by afc163** [comment]
a 标签加了特殊 hack 样式。

**Comment by 2449847346** [comment]
> a 标签加了特殊 hack 样式。

了解了，谢谢

**Comment by earthaYan** [comment]
4.23.6版本的a标签添加了特殊hack的代码具体体现在哪里呢？项目里有一个必须使用Button包裹的场景，看上去需要进行相同的操作 @afc163
