### ISSUE TITLE
TreeSelect 多选模式下 全选父节点下面的子节点 输入框里面竟然不展示父节点了，这很容易让人觉得这是bug

### ISSUE THREAD

**Issue by yl196356303** [ant-design/ant-design#38220]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fex4hk)

### Steps to reproduce

全选任意子节点，官网 TreeSelect 第二个例子就能复现

### What is expected?

子节点全选时也展示父节点

### What is actually happening?

子节点全选时不展示父节点

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | react18x |
| System | win10 |
| Browser | chrome任意版本 |

**Comment by kiner-tang** [comment]
通常来说，枝干节点都不是主要的数据节点，大多用于分组使用的，绝大部分场景，都是只需要叶子节点的数据，个人感觉这样的行为是没什么问题的。或者这边有什么特殊场景需要支持枝干节点也展示的吗？

**Comment by yl196356303** [comment]
站在开发人员角度上确实没什么问题，但是对于用户来说，只选择了一部分就会展示枝干节点，全选就不展示，我们组测试认为这是bug，确实从用户体验方面来说不怎么合理，不知道有没有什么解决方案

**Comment by afc163** [comment]
`showCheckedStrategy={TreeSelect.SHOW_ALL}`
