### ISSUE TITLE
Tabs 标签页 destroyInactiveTabPane 属性

### ISSUE THREAD

**Issue by zbkha** [ant-design/ant-design#38234]
### Reproduction link

[https://ant-design.gitee.io/components/tabs-cn/#API](https://ant-design.gitee.io/components/tabs-cn/#API)

### Steps to reproduce

该属性中文介绍是“被隐藏时是否销毁 DOM 结构”，但事实上设置该属性为true后，隐藏的标签页所在的DOM结构并没有被销毁，而是利用CSS规则{display: none}把DOM隐藏了起来，如果切换成上一页，那之前的状态依然保持着。

### What is expected?

被隐藏时能真正销毁 DOM 结构，从而重置之前的状态。

### What is actually happening?

只是通过{display: none}给隐藏。

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 103.0.5060.134 |

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-chu-yong-fa-fei-qi-de-yu-fa-tang-antd-4-23-6-forked-z4gmnd?file=/demo.tsx

目测是有效的。

**Comment by zbkha** [comment]
找到问题所在了，我的每一个`Tabs`内容里都有一个`Form`，并且都绑定了`Form.useForm`，经过测试，`Form`绑定了`form`属性后，无论`Tabs`是否设置`destroyInactiveTabPane`属性，切换`Tab`后再切换回来状态依然存在，这个估计跟`react hooks`的底层原理相关吧。

**Comment by afc163** [comment]
destroyInactiveTabPane 销毁的是 dom 元素，不会销毁外部的 react 状态。

**Comment by Pentium286** [comment]
> 

加了 `forceRender` 以后怎么解决销毁呢
