### ISSUE TITLE
Modal animations doesn't work as intended

### ISSUE THREAD

**Issue by MirciaGeorge** [ant-design/ant-design#38232]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-cache-cyvthb?file=/src/App.tsx)

### Steps to reproduce

step 1: click on the button "Click here" - the animation works fine
step 2: close the modal
step 3: open again - the animations don't work
step 4: repeat - the animation will not work until the page is refreshed, and after that only work once

### What is expected?

I expect second time when I click that button to have the same animation

### What is actually happening?

What is happening is that after the first click the animations don't work anymore

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.21 |
| System | windows 10 |
| Browser | 106.0.1370.52 |

**Comment by kiner-tang** [comment]
![show](https://user-images.githubusercontent.com/10286961/198154878-d6ec3b1f-c192-41b5-b96f-c4a08ec57e01.gif)
In the example you provided, it looks like the animation is working properly

**Comment by MirciaGeorge** [comment]
https://user-images.githubusercontent.com/33056198/198243425-7accfbc1-8318-4c19-ba31-a31c53d2d213.mp4

look at this, first animation is different

**Comment by kiner-tang** [comment]
Yes, the start position coordinates of 'Modal' change

**Comment by MirciaGeorge** [comment]
and how can I keep the same position (the first position)?
