### ISSUE TITLE
Styling issue on form error messages within `<Input.Group compact>`

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#38235]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/error-styling-antd-4-23-6-zsenpl?file=/demo.tsx)

### Steps to reproduce

Click the button in the demo which says "Click to toggle display issue".

### What is expected?

The error displays without causing a layout shift of the compacted input group

### What is actually happening?

There is a layout shift within the compacted input group meaning the button is moved along the horizontal axis

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | React |
| System | Windows 10 |
| Browser | Version 1.44.112  Chromium: 106.0.5249.119 (Official Build)  (64-bit) |

**Comment by zombieJ** [comment]
Please ref doc. Using `noStyle` to remove FormItem style:
https://codesandbox.io/s/error-styling-antd-4-23-6-zsenpl?file=/demo.tsx

**Comment by mjfwebb** [comment]
@zombieJ I think you made a mistake with that link. You pasted back my own sandbox link :smile:

To any future readers, the solution is to add `noStyle` as suggested but also wrap the `<Input.Group compact>` component in a `<Form.Item>`:

```jsx
<Form.Item> // <-- <Form.Item> added here
  <Input.Group compact>
    <Form.Item
      name="text-input"
      rules={[
        {
          required: true,
          message: "A long error message"
        }
      ]}
      noStyle // <-- noStyle added here
    >
      <InputNumber type="number" min={1} />
    </Form.Item>
    <Button type="default">Group Button</Button>
  </Input.Group>
</Form.Item> // <-- </Form.Item> added here
```
