### ISSUE TITLE
Collapse组件onChange事件

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design#38239]
### What problem does this feature solve?

目前Collapse组件在onChange事件里只能拿到当前激活 tab 面板的 key，但是在使用过程中往往是需要拿到当前操作面板的 key。比如，展开某个面板时远程请求对应的数据。

### What does the proposed API look like?

onChange: (activeKey, currKey) => void

**Comment by afc163** [comment]
使用受控模式，自行维护 current state 就行。

**Comment by DaJianWu** [comment]
> 使用受控模式，自行维护 current state 就行。

自行维护的话每次都要去找前后 state 这两个数组的唯一值差异，比较麻烦。个人感觉这个是个比较常用的场景，而且像 Checkbox 之类的组件也有类似的问题，完全可以支持一下吧

**Comment by wj0990** [comment]
> 1. %

不麻烦吧？判断length就行

**Comment by 12Ir** [comment]
真的很麻烦，不仅要判断点的哪个，还要判断点击之后是展开状态还是收起状态。

**Comment by DaJianWu** [comment]
> 真的很麻烦，不仅要判断点的哪个，还要判断点击之后是展开状态还是收起状态。

是的 确实比较麻烦
