### ISSUE TITLE
Documentation: Default filter on Table component

### ISSUE THREAD

**Issue by jmatsushita** [ant-design/ant-design#3823]
Hi there,

It would be nice to be able to specify default filters. It would allow for instance to pre-filter tables which are accessed via routes with query parameters for categories.

Cheers,

Jun

**Comment by jmatsushita** [comment]
Again... :) This is already implemented with `filteredValue`. Maybe the [documentation](https://ant.design/components/table/#Column) could say `Default` instead of `Controlled`?

**Comment by yesmeck** [comment]
IMO, default value is different from controlled value in React. Maybe we can remove the word "controlled", just call `filteredValue` is "the value of the filter"?
