### ISSUE TITLE
Popover Safari 点击 Focus me 按钮无法弹出气泡弹窗

### ISSUE THREAD

**Issue by jiajiangyuan** [ant-design/ant-design#38237]
### Reproduction link

[https://ant-design.gitee.io/components/popover-cn/](https://ant-design.gitee.io/components/popover-cn/)

### Steps to reproduce

safari 代码演示 三种触发方式  点击Focus me按钮无法弹出气泡弹窗

### What is expected?

显示气泡弹窗

### What is actually happening?

不显示气泡弹窗

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.1.0 |
| System | Mac |
| Browser | safari |

**Comment by wangmeijian** [comment]
我看看

**Comment by wangmeijian** [comment]
Safari浏览器下，点击a标签和button标签是不会获得焦点的，这个是Safari浏览器自己的问题，还不好做兼容。

使用键盘Tab切换焦点能正常弹出气泡弹窗

**Comment by afc163** [comment]
看上去没啥好办法。
