### ISSUE TITLE
TreeSelect组件搜索模式下，treeData数据中不同层级有相同value时，选中任意value时，部分相同的value在下拉中未被选中

### ISSUE THREAD

**Issue by yangxf1854** [ant-design/ant-design#38236]
### Reproduction link

https://stackblitz.com/edit/react-q8ui1e?file=index.css,demo.tsx

### Steps to reproduce

步骤1、搜索“莹姐”两个字
2、出现下拉内容后，在树内容中随便点击任意一个“莹姐”
3、“莹姐”被选中后，下拉数据中的“莹姐”未被全部选中，且点击后下拉的数据也变更了下，显示的数据层级不对
![image](https://user-images.githubusercontent.com/33971031/198467888-49693e15-b4cb-4e6e-9e51-3261e29b331a.png)

### What is expected?

treeData数据中不同层级有相同value时，选中任意value时，下拉中所有相同的value都应该被选中

### What is actually happening?

treeData数据中不同层级有相同value时，选中任意value时，部分相同的value在下拉中未被选中

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.0.23 |
| System | macOS Monterey12.1 |
| Browser | 谷歌 版本 106.0.5249.119（正式版本） (arm64) |

**Comment by zombieJ** [comment]
`value` 需要不同的，否则受控下组件是判断不出来目标是哪个。

**Comment by 303540023** [comment]
> 

你们居然不认为这是一个bug，不同node下的数据一样都不行
