### ISSUE TITLE
Pagination reset when onFilter triggered

### ISSUE THREAD

**Issue by sxlwar** [ant-design/ant-design#38240]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-kong-de-shai-xuan-he-pai-xu-antd-4-23-6-forked-mzxeg9?file=/package.json)

### Steps to reproduce

1. go to page 2
2. filter the data by name

### What is expected?

the pagination should be 2

### What is actually happening?

the pagination changed to 1

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.0.0 |
| System | macOS 12.6 |
| Browser | chrome 106.0.5249.119 |

**Comment by afc163** [comment]
It is intented.

**Comment by sxlwar** [comment]
Can't understand  why？
