### ISSUE TITLE
添加含有属性draggable的元素，下拉菜单及下拉选择框闪动，无法显示

### ISSUE THREAD

**Issue by flag-shen** [ant-design/ant-design#38244]
### Reproduction link

[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce

1.进入ant-Select页面；2.在’何时使用‘或其他元素上添加属性draggable=true，使其能够拖拽；3拖拽当前修改属性的元素；4. 点击下拉框luck

### What is expected?

下拉选项正常显示

### What is actually happening?

下拉选项闪动后消失

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | 版本 106.0.5249.119（正式版本） (arm64) |
| Browser | google |

---
react ant项目中，添加一个可拖拽的元素，拖拽该元素后，菜单及选择下拉框异常，google版本106；改变窗口大小1可恢复正常

**Comment by afc163** [comment]
Duplicate of #38152

**Comment by bjtqti** [comment]
这个问题我有一个临时办法 :
   1、给antd的Select组件加一下key, 在拖动结束后更新这个key,强制Select 重新渲染。同样的方法也适用于日历组件Datepicker
