### ISSUE TITLE
Dropdown多级菜单有相邻的submenu时，hover到相邻的菜单时，当前的submenu不会关闭

### ISSUE THREAD

**Issue by LuckLin520** [ant-design/ant-design#38241]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-ji-cai-dan-antd-4-23-6-forked-ftn6r1?file=/demo.tsx)

### Steps to reproduce

在sub menu和sub menu2来回hover切换

### What is expected?

hover离开当前菜单时隐藏当前submenu

### What is actually happening?

hover离开当前菜单时多数时候不会隐藏当前submenu并且同时弹出下一个submenu

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.0.0 |
| System | win10 |
| Browser | Chrome 版本 106.0.5249.119（正式版本） （64 位） |

**Comment by huangkairan** [comment]
WIP

**Comment by LuckLin520** [comment]
能给我加个急吗？
我正在焦急的等待这个bug的处理😘

**Comment by da-gen** [comment]
同求加急

**Comment by jeggy** [comment]
We also hit this issue in our project while moving to the `<Menu items={[...]} />` pattern. 
We are on version `4.24.2`

**Comment by mforncro** [comment]
Also hitting this on React18 using antd 4.24.4.  Are there any workarounds that can be applied?

**Comment by jovana** [comment]
> We also hit this issue in our project while moving to the `<Menu items={[...]} />` pattern. We are on version `4.24.2`

THis syntax is also not working in version 5.0.5. Using the overlay={} option still can be used, but for how long?

**Comment by MadCcc** [comment]
The reproduction works well in 4.24.8, closing.
https://codesandbox.io/s/duo-ji-cai-dan-antd-4-23-6-forked-p4tbfg
