### ISSUE TITLE
In the Select component, add a popup placement option of `none`

### ISSUE THREAD

**Issue by raquelmsmith** [ant-design/ant-design#38256]
### What problem does this feature solve?

One way to use the Select component for multi-select is for tags. However, not all tagging use-cases use a list of pre-defined options. That means that as someone type and selects a tag, all that shows up in the options popup are the things that the user has already entered. In this situation it would make sense to not show the options popup. So, it would be nice to be able to select a popup placement of `none` so that the popup doesn't appear.

### What does the proposed API look like?

Simply add an option for `none` for the `<Select>` placement.

**Comment by afc163** [comment]
I don't realy understand, could you provide a image to describe what you need?
