### ISSUE TITLE
message - key of zero creates new message instead of updating

### ISSUE THREAD

**Issue by ChrisHamilton91** [ant-design/ant-design#38259]
### Reproduction link

[https://stackblitz.com/edit/react-yceue2?file=demo.tsx](https://stackblitz.com/edit/react-yceue2?file=demo.tsx)

### Steps to reproduce

1. Call `message.open({content: "Loading...", key:0})`
2. Call `message.success({content: "Success!", key:0})`

### What is expected?

The loading message changes to a success message

### What is actually happening?

A new success message is created, and the loading message still exists.

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox 106.0.2 |

---
Probably the result of checking if the key is falsey. Since `number` is an acceptable key type, 0 should be allowed. Discovered when using a counter to assign ids to messages, which is probably a common use case.

**Comment by kiner-tang** [comment]
- https://github.com/react-component/notification/blob/3c1dab45ab190bf0f43bccccd758f980afb19483/src/Notification.tsx#L142

It seems that you should use '?? Instead of ` ` | | `

**Comment by afc163** [comment]
PR is welcome

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/notification/tree/v4.6.1

**Comment by kiner-tang** [comment]
> Fixed in https://github.com/react-component/notification/tree/v4.6.1

Do we need to send a PR update version of 'rc-notification' in 'ant-design' to fix this problem
@afc163

**Comment by afc163** [comment]
No neccessary, semver version will cover 4.6.1.
