### ISSUE TITLE
Select selector "search" optimization

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#38258]
### What problem does this feature solve?

Select 选择器的 showSearch 属性，目前只能搜索 value 字段，希望未来支持搜索 label 和 value 两个字段，因为生产环境大部分场景是 value 是 number 类型，用户输入是文字

### What does the proposed API look like?

Select 选择器的 showSearch 属性，目前只能搜索 value 字段，希望未来支持搜索 label 和 value 两个字段，因为生产环境大部分场景是 value 是 number 类型，用户输入是文字

**Comment by afc163** [comment]
Check `optionFilterProp`
