### ISSUE TITLE
tabpane切换的时候重绘了所有其它tabpane的数据，都置空了

### ISSUE THREAD

**Issue by leinue** [ant-design/ant-design#3826]
#### 发生问题的环境是：

- antd 版本: 2.2.1
- 操作系统及其版本: mac osx 10.11.4
- 浏览器及其版本:  chrome 54.0.2840.71 (64-bit)

还使用了dva，stateless function

#### 您做了什么？请提供尽可能详细的重现步骤。

tabpane内是一个aceEditor，每次新增的时候会给他自动生成一个唯一的id。

#### 您期待的结果是:

新增/切换/删除pane时对已有pane不产生任何影响

#### 实际上的结果是:

新增之后，之前存在的tabpane中的aceEditor所有内容都会消失且ID会发生改变，log之后发现，每次新增/切换/删除之后都会按照tabpane的数组数量依次循环重绘

**Comment by leinue** [comment]
// import React from 'react';
以下是我进行tab状态更新的代码

import dva from 'dva';

export default {
	namespace: 'devpanel',
	state: {

		panes: [
			{ title: '欢迎页面', content: 'welcome', key: '1', type: 'welcome' },
	    ],

	    activeKey: '1'
	},

	reducers: {

		tabChanged(state, {payload: key}) {
			return {...state, activeKey: key};
		},

		'remove'(state, {payload: targetKey}) {
			let target = targetKey.targetKey;
			let activeKey = state.activeKey;
			let lastIndex;

			let type = targetKey.type;

			console.log(targetKey, targetKey.type);

			state.panes.forEach((pane, i) => {
				if(pane.key === target) {
					lastIndex = i - 1;
					if(lastIndex < 0) {
						lastIndex = 0;
					}
				}
			});

			const panes = state.panes.filter(pane => pane.key !== target);
			if(lastIndex >= 0 && activeKey === target) {
				if(panes.length != 0) {
					activeKey = panes[lastIndex].key;					
				}else {
					if(type != 'welcome') {
						panes.push({
							title: '欢迎页面',
							content: 'content',
							key: '1',
							type: 'welcome'
						});
						activeKey = '1';
					}
				}
			}

			return {...state, panes, activeKey};
		},

		add(state, {payload: target}) {

		    const panes = state.panes;
		    const activeKey = (state.panes.length + 1).toString();

			target.title = target.title || '新标签页 ';
			target.type = target.type || 'editor';
			target.content = target.content || '';

		    panes.push({ title: target.title + activeKey, content: target.content, key: activeKey, type: target.type });

		    return {...state, panes, activeKey};
		}
	}

}

**Comment by leinue** [comment]
@luolonghao @sorrycc @raptium @vxzhong @lifesinger 请帮帮忙

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close now, if you can provide a re-producible demo, just re-open this issue.
