### ISSUE TITLE
Segmented need a 'loading' props （Segmented 组件需要增加 'loading' 属性）

### ISSUE THREAD

**Issue by AnteeHub** [ant-design/ant-design#38263]
### What problem does this feature solve?

- English

When I am using `<Segmented/>` I hope it can render a `loading` state ,before getting result from some asynchronous functions. So that I can avoid some unexpected or too frequent actions of users.

`<Segmented/>` has no props like 'loading' at current version (antd v4.23.6), so I hope there will be a rendering status ( e.g use with `<Spin/>` to show ).

- 中文

在使用 `<Segmented/>` 组件触发一些异步的事件时，希望在异步结果返回之前，通过显示 `loading` 状态来防止用户的意外操作或者是频繁改变 `<Segmented/>` 状态的动作。

目前 antd v4.23.6 版本的 `<Segmented/>` 组件没有表示'加载中'状态的属性，希望 `<Segmented/>` 组件能够支持显示“加载中”的状态（比如结合 `<Spin/>` 组件显示）

## API

- English 

| property | Description | Type | Default |
|---|---|---|---|
| loading | The loading state of Segmented  | boolean | false |

- 中文

| 参数 | 说明 | 类型 | 默认值 |
|---|---|---|---|
| loading | 表示当前 Segmented 组件是否处于加载状态 | boolean | false |

### API usage / API 使用示例

```jsx
import React, { useState } from "react";
import { Segmented } from "antd";


// example 1
const DefaultSegmented = () => {
  return (
    <Segmented
      options={["apple", "banana"]}
      defaultValue={"apple"}
      loading={true}
    />
  );
};

// example 2
const ControlledSegmented = () => {
  const [loading, setLoading] = useState(false);

  const onChange = () => {
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  };

  return (
    <Segmented
      options={["apple", "banana"]}
      defaultValue={"apple"}
      loading={loading}
      onChange={onChange}
    />
  );
};

```

**Comment by afc163** [comment]
直接用 disabled 就行了吧，Input 组件也没有 loading 属性。
