### ISSUE TITLE
MenuItem被设置为disabled且label使用a 包裹的时候，应该展示的toolTip没有展示

### ISSUE THREAD

**Issue by earthaYan** [ant-design/ant-design#38267]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rough-tree-lmlygk?file=/src/App.tsx)

### Steps to reproduce

鼠标分别移动到对应的item上，一个展示，一个不展示

### What is expected?

当前item为disabled的时候，可以正确展示ToolTip内容

### What is actually happening?

并没有展示ToolTip内容

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 17.0.0 |
| System | windows 11 |
| Browser | chrome106.0.5249.119（正式版本） （64 位） |

**Comment by afc163** [comment]
会引发别的问题，这个问题还是不修了，建议换一个 html 标签。

<img width="421" alt="图片" src="https://user-images.githubusercontent.com/507615/205019550-edaad360-4da1-4ef1-88cf-aaebc0fdf678.png">
