### ISSUE TITLE
Upload file percent value

### ISSUE THREAD

**Issue by aso1datov** [ant-design/ant-design#38262]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lbstmm?file=/index.js)

### Steps to reproduce

Upload the large file, see the console log

### What is expected?

The `file.percent` should be `1` instead of `100` when the upload is `done` because the other values are less than 1.

### What is actually happening?

The `file.percent` is equals `100`

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | MacOS Ventura |
| Browser | Google Chrome 107.0.5304.87  |

---
The loading percentage should have consistent values during the process. It is necessary either to return percentages multiplied by 100, or to return a percentage within one.

**Comment by afc163** [comment]
It depends on service side: https://github.com/react-component/upload/blob/0d0ca2f65acca13f64199ffbb05054fb13c210ea/src/request.ts#L32
