### ISSUE TITLE
Select options rendered is Unsatisfied

### ISSUE THREAD

**Issue by jay0815** [ant-design/ant-design#38260]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-23-6-forked-k07x9z)

### Steps to reproduce

1. Switch unique
2. Click drop-down arrow
3. Switch repeat
4. Click drop-down arrow
5. Switch unique
6. Click drop-down arrow

### What is expected?

while change repeat to unique，all select options can be rerender and do not keep old things

### What is actually happening?

when repeat options rendered, the option which has same key will  keep forever event they are not in next options

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 \ 17.0.2 |
| System | macos 13.0 (22A380) |
| Browser | 107.0.5304.87 (arm64) |

**Comment by afc163** [comment]
```
- const repeat = ["bus", "bus", "car", "bike"];
+ const repeat = ["bus", "car", "bike"];
```

Do not add item with duplicated key .
