### ISSUE TITLE
Modal double network requests on render

### ISSUE THREAD

**Issue by SamKirkland** [ant-design/ant-design#38271]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-4-23-6-forked-whyul3?file=/demo.tsx)

### Steps to reproduce

1. Open devtools, open network tab, filter to "Doc"
2. Click "Open Modal" button
3. Note two network requests to load example.com, the first was cancelled

### What is expected?

Only a single request should be made to load example.com

### What is actually happening?

Two requests are being made to load the iframe because PortalWrapper appends content to the page multiple times if getContainer and destoryOnClose are both set

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.0.24 (latest) |
| System | Windows 10 |
| Browser | Chrome v106 (latest), Firefox v106 (latest) |

**Comment by fnoopv** [comment]
look console, first request canceled because https://google.com set 'X-Frame-Options' to 'sameorigin',so request canceled by web browser. second request may be web brower edit request header or other and send request, i guess

**Comment by SamKirkland** [comment]
@fnoopv no the first request is cancelled because the iframe is added and removed immediately. Then a new one is added.

This is because the Portal wrapper clones the element

**Comment by afc163** [comment]
https://github.com/react-component/portal/blob/0747c5b520af3b33dd05b3c660b9eb34692d5ab7/src/useDom.tsx#L47 

cc @zombieJ

**Comment by zombieJ** [comment]
React 18 require effect should handle in `useEffect` which means append dom container need also handle in useEffect. That makes holder element change its position after effect.

**Comment by zombieJ** [comment]
tested in 4.24.x, since this question already gone: https://codesandbox.io/s/basic-antd-4-23-6-forked-feiqwh?file=/demo.tsx
