### ISSUE TITLE
Modal can't open on Chrome81.0.4044.92

### ISSUE THREAD

**Issue by qianjiachun** [ant-design/ant-design#38272]
### Reproduction link

[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce

open any Modal to reappear

### What is expected?

Modal be opened

### What is actually happening?

Modal can not be opened

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | win10 |
| Browser | AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36 |

**Comment by zombieJ** [comment]
What's the error message in console?

**Comment by qianjiachun** [comment]
> What's the error message in console?

No error msg in the console

**Comment by afc163** [comment]
Please upgrade Chrome version.

<img width="693" alt="图片" src="https://user-images.githubusercontent.com/507615/198818800-0a4bc7a9-2479-4551-821d-bf2cac1bb5d8.png">
