### ISSUE TITLE
Image.PreviewGroup 无法得到当前图片的索引

### ISSUE THREAD

**Issue by yanghuanrong** [ant-design/ant-design#38298]
### What problem does this feature solve?

退出全屏预览模式后需要根据当前图片的索引知道用户预览到了哪一张图片，方便给图片所处在的那条数据做状态联动

### What does the proposed API look like?

onCurrentChange?: (current, prevCurrent) => void;

**Comment by afc163** [comment]
https://github.com/react-component/image/pull/141

**Comment by Emily-0616** [comment]
> [反应组件/图像#141](https://github.com/react-component/image/pull/141)

什么时候发布啊

**Comment by Emily-0616** [comment]
> [react-component/image#141](https://github.com/react-component/image/pull/141)

什么时候会发布

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/pull/40660 应该是5.3.0
