### ISSUE TITLE
Importing the right css files for Modal component

### ISSUE THREAD

**Issue by AbuniDaniel** [ant-design/ant-design#38290]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-smoke-4mclcd?file=/src/App.js)

### Steps to reproduce

Click twice the button to open modal

### What is expected?

Modal to work properly

### What is actually happening?

So I know where is the problem but I don't know how to solve it. In the link from codesanbox.io on lines 3 and 4 I imported css for modal and button (I wanna mention that if I import "import 'antd/dist/antd.css';" like this works, but I wanna avoid messing up my site because like this antd.css has a lot of global things so the solve is to import separately the required css files for modal to work).

For example for 'notification' component importing "import "antd/lib/notification/style/index.css";" this works without any problem. 

Thank you!

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | react |
| System | Windows 10 |
| Browser | Opera |

**Comment by afc163** [comment]
```diff
- import "antd/lib/modal/style/index.css";
+ import "antd/lib/modal/style";
```

**Comment by afc163** [comment]
Trace #9363 for global styling issue.

**Comment by AbuniDaniel** [comment]
> ```diff
> - import "antd/lib/modal/style/index.css";
> + import "antd/lib/modal/style";
> ```

this doens't work
