### ISSUE TITLE
DatePicker.RangePicker缺少popupClassName声明

### ISSUE THREAD

**Issue by AdonLee** [ant-design/ant-design#38294]
### Reproduction link

[https://localhost.com](https://localhost.com)

### Steps to reproduce

DatePicker.RangePicker缺少popupClassName声明

### What is expected?

DatePicker.RangePicker缺少popupClassName声明

### What is actually happening?

DatePicker.RangePicker缺少popupClassName声明

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 17 |
| System | window edge |
| Browser | 100 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/38325
