### ISSUE TITLE
Upload上传zip时，获取 压缩包原始文件大小

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design#38302]
### What problem does this feature solve?

解决 获取 zip（模型 贴图打包成zip时） 压缩包原始文件大小 

目前只能获取压缩后的大小
![image](https://user-images.githubusercontent.com/5111701/198969782-e7ef5d46-f0ca-4784-845c-5bcc90d6733e.png)
![image](https://user-images.githubusercontent.com/5111701/198969741-811a1d6c-69fa-4126-baec-9385944492f1.png)

### What does the proposed API look like?

origin size

**Comment by afc163** [comment]
这不是 antd 的能力范畴。
