### ISSUE TITLE
树形数据的表格如何合并单元格 

### ISSUE THREAD

**Issue by Topthinking** [ant-design/ant-design#38300]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-4-23-6-forked-1r9rxw?file=/demo.tsx)

### Steps to reproduce

直接打开看即可

### What is expected?

树形数据的表格如何合并单元格 

### What is actually happening?

合并出现UI问题

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18 |
| System | mac |
| Browser | chrome 最新 |

![image](https://user-images.githubusercontent.com/13382821/198967933-200e46d4-fe88-4dbb-876a-2c3e7d24e33c.png)

**Comment by Topthinking** [comment]
https://user-images.githubusercontent.com/13382821/198981824-e953996b-7d00-491a-9a75-aa51312b0b14.mp4

**Comment by afc163** [comment]
暂不支持。

**Comment by afc163** [comment]
Trace #31377

**Comment by svonme** [comment]
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-4-23-6-forked-1r9rxw?file=/demo.tsx)
> 
> ### Steps to reproduce
> 直接打开看即可
> 
> ### What is expected?
> 树形数据的表格如何合并单元格
> 
> ### What is actually happening?
> 合并出现UI问题
> 
> Environment	Info
> antd	4.23.6
> React	18
> System	mac
> Browser	chrome 最新
> ![image](https://user-images.githubusercontent.com/13382821/198967933-200e46d4-fe88-4dbb-876a-2c3e7d24e33c.png)

在 onExpand 事件中对 dataSource 数据进行调整
展开时在触发事件对应的数据后添加一组数据
收起时删掉对应的数据

**Comment by Hjyperfect** [comment]
> > ### Reproduction link
> > [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-4-23-6-forked-1r9rxw?file=/demo.tsx)
> > ### Steps to reproduce
> > 直接打开看即可
> > ### What is expected?
> > 树形数据的表格如何合并单元格
> > ### What is actually happening?
> > 合并出现UI问题
> > Environment	Info
> > antd	4.23.6
> > React	18
> > System	mac
> > Browser	chrome 最新
> > ![image](https://user-images.githubusercontent.com/13382821/198967933-200e46d4-fe88-4dbb-876a-2c3e7d24e33c.png)
> 
> 在 onExpand 事件中对 dataSource 数据进行调整 展开时在触发事件对应的数据后添加一组数据 收起时删掉对应的数据

请问这个是怎么操作呢 展开后添加一组数据 是添加一个新的abc的数据吗

**Comment by Hjyperfect** [comment]
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/97cbe82b1619b42e1f78fce9db09104b932a9da1fd37751f4d9c41f4fe350241/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-4-23-6-forked-1r9rxw?file=/demo.tsx)
> 
> ### Steps to reproduce
> 直接打开看即可
> 
> ### What is expected?
> 树形数据的表格如何合并单元格
> 
> ### What is actually happening?
> 合并出现UI问题
> 
> Environment	Info
> antd	4.23.6
> React	18
> System	mac
> Browser	chrome 最新
> ![image](https://user-images.githubusercontent.com/13382821/198967933-200e46d4-fe88-4dbb-876a-2c3e7d24e33c.png)

hello 请问一下 这个问题你解决了吗 我也遇到了同样的问题 antd 版本是5.8.2  ，希望得到你的回复
