### ISSUE TITLE
Prevent Menu from closing on item click

### ISSUE THREAD

**Issue by mathtev** [ant-design/ant-design#38312]
### Reproduction link

[https://codepen.io/mathtev/pen/gOKaEQK?editors=0010](https://codepen.io/mathtev/pen/gOKaEQK?editors=0010)

### Steps to reproduce

1. Hower on menu dropdown button to open menu.
2. Click on input field

### What is expected?

Menu should not close, because of provided onClick function:

`onClick={(e) => e.domEvent.stopPropagation()}`

### What is actually happening?

Menu is closing

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 17 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by ahmedsayed1850** [comment]
`const { createRoot } = ReactDOM;
const {  DownOutlined, SmileOutlined  } = icons;
const {  Dropdown, Menu, Space  } = antd;
const items = [
      {
        key: "1",
        label: "<input />"
      },
      {
        key: "2",
        label: "<input />"
      },
      {
        key: "3",
        label: (
          <a target="_blank" href="https://www.example.com">
            Example
          </a>
        ),
      }
]

const menu = (
  <Menu
    items={items.map(e => {
        if(e.label === "<input />") {
          e.label = <input onClick={(e) => e.stopPropagation()} />
          return e
        }
        return e
      })}
  />
);

const App: React.FC = () => (
  <Dropdown overlay={menu}>

    <Space>
      Hover me
      <DownOutlined />
    </Space>
  </Dropdown>
);
const ComponentDemo = App;


createRoot(mountNode).render(<ComponentDemo />);`

I have faced this problem before and my solution works out of nowhere you have to wrap the label to string if it's an input.

**Comment by afc163** [comment]
```diff
-    onClick={(e) => e.domEvent.stopPropagation()}
+    onClick={(e) => e.stopPropagation()}
```

**Comment by nganbread** [comment]
> ```diff
> stopPropagation
> ```

This only works because `e.StopPropagation` throws an error which causes the parent handler to break. `stopPropagation` doesn't even exist as a function on the event
