### ISSUE TITLE
Anchor 锚点组件

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design#3832]
环境：antd 2.4.2

问题：
由于各种原因（动态加载，iframe，图片加载等）使得 Anchor 初始化定位不太准确

建议方案：
希望 Anchor 组件能够提供一个可配置的参数（属性），能够让使用者自己控制初始化时候的定位时机。

**Comment by jljsj33** [comment]
把整个添加 scroll 事件提出来就行了吧，，，，scrollLink是这样搞的。。。可供参考。。。。http://react-component.github.io/scroll-anim/examples/linkAsynchronous.html

**Comment by RaoHai** [comment]
有道理。。

**Comment by afc163** [comment]
Anchor 有个 affix 属性。

**Comment by jljsj33** [comment]
还有个建义，，，anchor 在点击时把 scroll 去掉，用点击触发，不要用滚动触发选中，这样感觉有延时，体验不好，，点击滚动完后再添加回scroll。。。。

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/pull/3853/files#diff-1acb4b0ae45944c30d228e0b14e214b6R86

点击后给样式就行了，，不要把动画删掉。。。@RaoHai
