### ISSUE TITLE
Tree控件treeData和fieldsName冲突

### ISSUE THREAD

**Issue by pyb0924** [ant-design/ant-design#38322]
### What problem does this feature solve?

Tree控件中treeData的类型为array<{key, title, children, [disabled, selectable]}> ，不支持自定义并似乎与fieldsName冲突

### What does the proposed API look like?

treeData	的类型能否支持字段名自定义

**Comment by crazyair** [comment]
因为 key 为必传的，所以自己定义类型，需要有 key: string

**Comment by pyb0924** [comment]
非常感谢！ 也希望能在官方文档中说明一下/(ㄒoㄒ)/~~

**Comment by pyb0924** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/50937198/199159962-1fd9a8dc-ed82-489b-b74a-5b7818acb464.png">

这个地方显示的好像是key也可自定义？
