### ISSUE TITLE
当我使用TreeSelect时,在使用defaultValue进行默认选择时, 我使用的是三元表达式 然后他渲染不出来我想要的值

### ISSUE THREAD

**Issue by LovePlayCode** [ant-design/ant-design#38321]
### Reproduction link

[https://ant.design/components/tree-select-cn/#API](https://ant.design/components/tree-select-cn/#API)

### Steps to reproduce

 defaultValue={groupList.length>0 ? groupList[0].value : ''}

### What is expected?

这里为true应该显示数组第一个元素

### What is actually happening?

然而他显示的结果是不对的

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 17.0.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
[FAQ: 当我动态改变 defaultValue 的时候它并没有生效](https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82)
