### ISSUE TITLE
用Form.List后打印出来的结果很奇怪

### ISSUE THREAD

**Issue by Shen-Shuyi** [ant-design/ant-design#38324]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fu-za-de-dong-tai-zeng-jian-biao-dan-xiang-antd-4-23-6-forked-triwl6?file=/src/App.tsx)

### Steps to reproduce

1. 点击ADD按钮填写一些内容
2. submit按钮

### What is expected?

console打印的结果中samples字段可以正常显示
{
  ...其他字段, 
  samples: [
    {samplePos: xxx, desc: xxx},
    {samplePos: xxx, desc: xxx}, ....
  ]
}

### What is actually happening?

samples字段列表貌似将对应的react对象打印了出来
如: 
samples: Array(2)
0: Object
_reactName: "onClick"
_targetInst: null
type: "click"
nativeEvent: PointerEvent
target: 
<button type="button" class="ant-btn ant-btn-default" ant-click-animating-without-extra-node="false">…</button>
currentTarget: null
......
samplePos: "aa" //页面填写内容
desc: "bb"  //页面填写内容

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 17.0.2 |
| System | windows11 |
| Browser | edge |

**Comment by zombieJ** [comment]
https://ant.design/components/form-cn/#operation

`add` 参数接收默认值，你直接 onClick=add 就把 event 扔进去了。

**Comment by Shen-Shuyi** [comment]
> 

正常了, 非常感谢
