### ISSUE TITLE
Local development currently broken

### ISSUE THREAD

**Issue by mellis481** [ant-design/ant-design#38334]
### Reproduction link

[https://github.com/ant-design](https://github.com/ant-design)

### Steps to reproduce

1. Fork repo.
2. Run `npm i`.
3. Run `npm start`.

### What is expected?

App starts successfully.

### What is actually happening?

App fails with lots of console errors.

![image](https://user-images.githubusercontent.com/39313898/199279232-f174fc02-40b6-4788-80be-8f6e8e94548b.png)

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | react |
| System | Windows |
| Browser | Chrome |

**Comment by abenhamdine** [comment]
Same error here, but only with version 4.24.0 (4.23.6 runs fine) : 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/7466144/199355883-083b1e9f-e242-4346-b195-bb0d76d810d4.png">

**Comment by afc163** [comment]
Have you try to remove pacakge-lock.json and reinstall node_modules?

**Comment by tomorrowcheng** [comment]
> Have you try to remove pacakge-lock.json and reinstall node_modules?

I've tried it, but still get an error

**Comment by mellis481** [comment]
> Have you try to remove pacakge-lock.json and reinstall node_modules?

That resolved the issue.

Why is the package-lock.json not checked in? [It should be.](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks#:~:text=It%20is%20highly%20recommended%20you%20commit%20the%20generated%20package%20lock%20to%20source%20control%3A%20this%20will%20allow%20anyone%20else%20on%20your%20team%2C%20your%20deployments%2C%20your%20CI/continuous%20integration%2C%20and%20anyone%20else%20who%20runs%20npm%20install%20in%20your%20package%20source%20to%20get%20the%20exact%20same%20dependency%20tree%20that%20you%20were%20developing%20on.)
