### ISSUE TITLE
Doc: Cannot open the Drawer in Safari

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#38332]
### Reproduction link

[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce

Open the documentation and click any button to open the Drawer

### What is expected?

Drawer is open

### What is actually happening?

1. It's not possible to scroll page
2. The Drawer is not opened

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | - |
| System | Mac |
| Browser | Safari 14.0 (15610.1.28.1.9, 15610) |

**Comment by afc163** [comment]
<img width="1756" alt="图片" src="https://user-images.githubusercontent.com/507615/199255892-c18d0e11-990d-4d35-9261-f7b1295b9942.png">

Safari 14.1.2 (16611.3.10.1.3)

**Comment by monolithed** [comment]
@afc163 > Safari 14.1.2 (16611.3.10.1.3)

Hm, I'll try to update it too
