### ISSUE TITLE
Anchor 锚点的球没有了

### ISSUE THREAD

**Issue by conorzhong** [ant-design/ant-design#38337]
### Reproduction link

[https://ant.design/components/anchor-cn/#components-anchor-demo-basic](https://ant.design/components/anchor-cn/#components-anchor-demo-basic)

### Steps to reproduce

看demo

### What is expected?

锚点前面的球存在

### What is actually happening?

锚点前面的球没有了

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | antd版本 |
| System | macOS 13.0 |
| Browser | Edg/107.0.1418.24 |

**Comment by afc163** [comment]
@li-jia-nan 看看
