### ISSUE TITLE
form表单的样式bug

### ISSUE THREAD

**Issue by guoxiangwen** [ant-design/ant-design#3833]
#### 发生问题的环境是：

- antd 版本:2.3
- 操作系统及其版本:win10
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

![image](https://cloud.githubusercontent.com/assets/7627191/20258855/9cc83348-aa8c-11e6-9ad5-8c82ec0fe084.png)
当我的标签name使用‘title‘的时候 表单域的样式就会发生改变。

**Comment by benjycui** [comment]
应该类似这个原因 https://github.com/ant-design/ant-design/issues/2950

**Comment by benjycui** [comment]
实测没问题。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
