### ISSUE TITLE
table表格中可编辑单元格children数组为数组[undefined,"real"]

### ISSUE THREAD

**Issue by iamphr** [ant-design/ant-design#38340]
### Reproduction link

https://codesandbox.io/s/wkw6t0

### Steps to reproduce
let childNode = children; console.log("childNode",childNode)
官网的例子已放上去demojs第52行 在这一行直接打印就行

### What is expected?

求教为什么会出现undefined？难道是一个隐藏的api吗 求解

### What is actually happening?

打印出来children就是[undefined,'真实数据']

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.* |
| System | macos |
| Browser | chrome |

**Comment by kiner-tang** [comment]
提供的示例链接貌似给错了

**Comment by iamphr** [comment]
对不起各位，第一次提issues不太懂。官网例子链接已经更新，希望各位大佬指点

**Comment by iamphr** [comment]
@afc163 已更新 例如某个打印出来的childNode就是一个数组 [undefined,'32']    不太清楚这个undefined是哪里来的

**Comment by afc163** [comment]
https://github.com/react-component/table/blob/0f86d2361a0b86cb71afb2072203cc8a5f7f4c35/src/Cell/index.tsx#L203-L208

这个 appendNode 带来的，普通场景 appendNode 为 undefined。
