### ISSUE TITLE
getPopupContainer prop for Select doesn't work correctly in case of lack of space (height)

### ISSUE THREAD

**Issue by rewweRrr** [ant-design/ant-design#38349]
### Reproduction link

[https://ant.design/components/select/#API](https://ant.design/components/select/#API)

### Steps to reproduce

1) Open API section using https://ant.design/components/select/#API
2) Find getPopupContainer section
3) Click to link:  Example (https://codesandbox.io/s/4j168r7jw0)
4) Change first "div" element's height from 200 -> 150
5) Change padding second "div" element's padding from 200 -> 0

### What is expected?

Popup should be under "select" element

### What is actually happening?

Popup overlap "select" element

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | Chrome 106.0.5249.119 |

**Comment by afc163** [comment]
It is intented. It happens when container don't have enough space to contian popup element.

**Comment by rewweRrr** [comment]
@afc163 But container has long scrollable area, so popup could be located in this area. Current behaviour looks strange in case of using AutoComplete instead of Select field. Because input part of autocomplete has overlaped by popup!

**Comment by rewweRrr** [comment]
@afc163 Is there any ability to open this popover always in bottom position?
