### ISSUE TITLE
Space.Compact broken when using Input with suffix

### ISSUE THREAD

**Issue by nosferatu500** [ant-design/ant-design#38341]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-andras-1o7v5z)

### Steps to reproduce

 - Add `<Input />` with `suffix`
 - Add `<Button />` with `icon` to `suffix`
 - Add another `<Button />` below `<Input />` component
 - Wrap everything with `<Space.Compact>`

### What is expected?

Consistent style from [documentation](https://ant.design/components/space/#components-space-demo-compact)

### What is actually happening?

Broken styles when using Input with suffix

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18.2 |
| System | MacOS 13 |
| Browser | Chrome 104 |

**Comment by afc163** [comment]
@foryuki

**Comment by foryuki** [comment]
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/admiring-andras-1o7v5z)
> 
> ### Steps to reproduce
> * Add `<Input />` with `suffix`
> * Add `<Button />` with `icon` to `suffix`
> * Add another `<Button />` below `<Input />` component
> * Wrap everything with `<Space.Compact>`
> 
> ### What is expected?
> Consistent style from [documentation](https://ant.design/components/space/#components-space-demo-compact)
> 
> ### What is actually happening?
> Broken styles when using Input with suffix
> 
> Environment	Info
> antd	4.24.0
> React	18.2
> System	MacOS 13
> Browser	Chrome 104

We recommend using 
`<Input suffix={<DeleteOutlined />} />`
 as Input suffix instead of using 
`<Input suffix={<Button icon={<DeleteOutlined />} size="small" type="text" />} />`.

```jsx
<Space.Compact block>
  <Input readOnly allowClear value="fileName" suffix={<DeleteOutlined />} />
  <Button>...</Button>
</Space.Compact>;

```

**Comment by foryuki** [comment]
We are considering whether to support stretching to the same height when the child elements of the Space.Compact component have different heights.

**Comment by nosferatu500** [comment]
Thanks for the suggestion! I think I will use the option you provided.

Feel free to close the issue!

**Comment by adanyal46** [comment]
<Space.Compact className={'w-100'} block size={'large'}>
                    <Form.Item className={'input__compact'}  name={'name'} style={{flex:1,marginBottom:0}} rules={[{required:true,message:'Please choose customer name'}]}>
                        <Select size={'large'} placeholder={'Select Customer Name'}>
                            {allUser.map((item,index)=>{
                                return (
                                    <Select.Option value={item.id} key={index}>{item.name + " " + item.email}</Select.Option>
                                )
                            })}

                        </Select>
                    </Form.Item>
                    <Button size={'large'} type={'primary'} htmlType={'submit'}>
                        Submit
                    </Button>
                </Space.Compact>
                you can use size large in space.compact then problem solve of input size

**Comment by adanyal46** [comment]
<Space.Compact className={'w-100'} block size={'large'}>
                <Form.Item className={'input__compact'}  name={'name'} style={{flex:1,marginBottom:0}} rules={[{required:true,message:'Please choose customer name'}]}>
                    <Select size={'large'} placeholder={'Select Customer Name'}>
                        {allUser.map((item,index)=>{
                            return (
                                <Select.Option value={item.id} key={index}>{item.name + " " + item.email}</Select.Option>
                            )
                        })}

                    </Select>
                </Form.Item>
                <Button size={'large'} type={'primary'} htmlType={'submit'}>
                    Submit
                </Button>
            </Space.Compact>
            you can use size large in space.compact then problem solve of input size

**Comment by devchen13** [comment]
![image](https://github.com/user-attachments/assets/39973305-171c-472b-a8b9-31b0e8b832cf)

  <Space.Compact  block  >
           <Select />
          <Input allowClear/>
          </Space.Compact>
圆角异常
@afc163
