### ISSUE TITLE
今天放了个版本(2.4.2)之后页面卡顿极其严重

### ISSUE THREAD

**Issue by zachshelter** [ant-design/ant-design#3834]
#### 发生问题的环境是：

- antd 版本:  2.4.2
- 操作系统及其版本: MacOS 10.12
- 浏览器及其版本: Chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。
看到antd 2.4.2发布了以后， 将所有的node_modules删除了以后重新执行npm install 之后，发现页面非常卡顿。甚至会导致浏览器挂了。

开始以为是自己代码的问题， 将代码切换回几个之前的版本(算是很原始的版本，那时候正常运行) , 重新执行npm install 都会出现同样的问题。 但是将原来版本的node_modules放回项目之后，就一切正常。

本以为降antd的版本会解决此问题，但是发现没有用。 （怀疑是否antd 或 dva 或者 dora 的库出现问题）

我们项目使用的是 dva 脚手架搭建的

目前不知道该如何解决。

非常感谢

**Comment by yyxiaowei** [comment]
貌似我们项目也发现了这个问题..暂时还未解决.只能回到前版本node_modules包

**Comment by yesmeck** [comment]
能不能先自己大概定位下问题？

**Comment by zachshelter** [comment]
@yesmeck 

我描述里面已经猜测就是 npm 包的问题，但是具体是 哪个依赖的包 很难找。 
觉得奇怪的是我install 的是2.4.1及以下版本， 但是安装过程会有一句 use grandfather(antd@2.4.2)'s dependencies version: "~2.3.0" instead of "2.x", parent: rc-dialog@6.5.0 类似这种描述。 （cnpm）

猜测是否某些包里面是相互依赖，且自动下载最新的。 

我能提供的信息可能就是这些。 （今天 即使 npm install 三周前的 package.json的包， 都会出现此问题， 但是用以前的包替换今天的，就不会有问题）

**Comment by yesmeck** [comment]
试试用 Chrome 的 Developer Tools 里的 Profiles 找找是哪个方法在一直执行，包的范围太大了。

**Comment by benjycui** [comment]
也可以尝试提供可重现 repo

**Comment by zachshelter** [comment]
![image](https://cloud.githubusercontent.com/assets/7088129/20260530/0500e7cc-aa95-11e6-8a14-4d058ca61ee3.png)

![image](https://cloud.githubusercontent.com/assets/7088129/20260561/322b8b4e-aa95-11e6-871d-610d8ec42958.png)

从selftime看来是lodash占用了非常大的资源。 但是奇怪的是，之前并不会导致此问题。

下图是替换原有node_modules的结果
![image](https://cloud.githubusercontent.com/assets/7088129/20260772/15c6e524-aa96-11e6-8a2e-4a7ac1535de6.png)

lodash的信息都很少看见。

**Comment by yesmeck** [comment]
@zachshelter 用这个看看 https://facebook.github.io/react/docs/perf.html 哪些组件 render 次数很多？

**Comment by zachshelter** [comment]
结果如下：
![image](https://cloud.githubusercontent.com/assets/7088129/20262897/3bcda038-aa9f-11e6-91be-c37c1e65bb4f.png)

我们的这个表单如下图
![image](https://cloud.githubusercontent.com/assets/7088129/20262909/52187a70-aa9f-11e6-890f-699f70c8aae8.png)

上述的行为是一个级联关联过程，第一个选择框是异步获取选项， 如果其有级联，则请求第二个，以此类推。

**Comment by yesmeck** [comment]
再用redux-logger 看看哪个 action 一直在 dispatch 吧

**Comment by afc163** [comment]
给个可重现的 repo，就不用这么反复的问来问去了。

**Comment by zachshelter** [comment]
https://github.com/zachshelter/antd-3834.git

新建了一个repo，里面可以重现这个问题。

注： 虽然只有三个选项，但是可以明显感觉卡顿。 但是实际上用以前的node_modules的时候，一点也不会卡的。 repo里面的写法是因为我们需要封装业务逻辑。

**Comment by yesmeck** [comment]
你这个 repo 我没看出什么问题来，起码没看出 antd 的问题来。

**Comment by zachshelter** [comment]
已经定位了问题了， 我将所有的package.json里面的包限定版本之后，再一个一个升级发现是lodash升级到4.17.0之后出现了卡顿。 之前是 4.16.6就没问题。

**Comment by afc163** [comment]
https://github.com/lodash/lodash/issues/2812
https://github.com/lodash/lodash/issues/2810

看来不是 antd 问题了，你可以到 lodash 上去跟踪。
