### ISSUE TITLE
Dropdown 组件的 children 使用自定义组件时无法触发

### ISSUE THREAD

**Issue by devenliu** [ant-design/ant-design#38342]
### Reproduction link

[https://ant.design/components/dropdown-cn/#components-dropdown-demo-basic](https://ant.design/components/dropdown-cn/#components-dropdown-demo-basic)

### Steps to reproduce

设置 Dropdown 的 overlay 属性
在 Dropdown 的 children 中使用自定义组件（简单的包装组件）

### What is expected?

可以触发下拉列表

### What is actually happening?

无法触发下拉列表

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 16.14.0 |
| System | Windows11 |
| Browser | Microsoft Edge 版本 107.0.1418.26 (正式版本) (64 位) |

---
// 代码如下：

import { DownOutlined, SmileOutlined } from '@ant-design/icons';
import { Dropdown, Menu, Space, Button } from 'antd';
import React from 'react';

const menu = (
  <Menu
    items={[
      {
        key: '1',
        label: (
          <a target="_blank" rel="noopener noreferrer" href="https://www.antgroup.com">
            1st menu item
          </a>
        ),
      },
      {
        key: '2',
        label: (
          <a target="_blank" rel="noopener noreferrer" href="https://www.aliyun.com">
            2nd menu item (disabled)
          </a>
        ),
        icon: <SmileOutlined />,
        disabled: true,
      },
      {
        key: '3',
        label: (
          <a target="_blank" rel="noopener noreferrer" href="https://www.luohanacademy.com">
            3rd menu item (disabled)
          </a>
        ),
        disabled: true,
      },
      {
        key: '4',
        danger: true,
        label: 'a danger item',
      },
    ]}
  />
);

// 文档示例：
export const App: React.FC = () => (
  <Dropdown overlay={menu}>
    <a onClick={e => e.preventDefault()}>
      <Space>
        Hover me
        <DownOutlined />
      </Space>
    </a>
  </Dropdown>
);

// 我的示例：
// 自定义组件，此时无法触发下拉列表
const MyButton = () => (<Button>Hover me</Button>);

export const MyApp: React.FC = () => (
  <Dropdown overlay={menu}>
    <MyButton />
  </Dropdown>
);

**Comment by zombieJ** [comment]
自定义组件需要接收事件，你的组件没有处理 `onMouseEnter` `onMouseLeave`，导致鼠标事件没有办法获取。

**Comment by devenliu** [comment]
代码如下
```jsx
import React from "react";
import { createRoot } from "react-dom/client";
import { Button, Space, version, Dropdown, Menu } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const menu = (
  <Menu>
    <Menu.Item>菜单项一</Menu.Item>
    <Menu.Item>菜单项二</Menu.Item>
  </Menu>
);

const MyButton = ()=> (
  <Button>Hover me</Button>
);

const App = () => {
  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <Space>
        <div>
          <h2>官方示例</h2>
          <Dropdown overlay={menu}>
            <a>Hover me</a>
          </Dropdown>
        </div>
        <div>
          <h2>我的示例</h2>
          <Dropdown overlay={menu}>
            <MyButton />
          </Dropdown>
        </div>
      </Space>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);

```

**Comment by devenliu** [comment]
> 自定义组件需要接收事件，你的组件没有处理 `onMouseEnter` `onMouseLeave`，导致鼠标事件没有办法获取。

请问应该如何将自定义组件和 Dropdown 关联呢？

**Comment by tobemaster56** [comment]
今天也遇到这个问题了，官方文档有提到
<img width="857" alt="image" src="https://github.com/ant-design/ant-design/assets/8998761/3b223db3-b79b-4e01-9b56-a6dd343830a0">

可以参考一下这个
<img width="1975" alt="image" src="https://github.com/ant-design/ant-design/assets/8998761/306efe96-9fbe-4b5f-8100-1fb352f985db">
