### ISSUE TITLE
Tabs slide arrow disabled

### ISSUE THREAD

**Issue by rish1831** [ant-design/ant-design#38359]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fast-frost-io6co9)

### Steps to reproduce

in tabs slide when we first clicking on right arrow button to move to the right and then clicking on Click ME button

### What is expected?

Upon clicking on click me button we should be scrolled to the left and left arrow should be disabled and right arrow should be enabled ,since we are already in the left.

### What is actually happening?

Upon clicking on click me button we are being  scrolled to the left but left arrow is enabled and right is disabled.

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | 18.2.0 |
| System | Version 21H2 (OS Build 19044.2130) |
| Browser | 106.0.5249.119 |

---
While working on a project

**Comment by afc163** [comment]
Nothing there?

<img width="676" alt="图片" src="https://user-images.githubusercontent.com/507615/199677297-4738fa0d-817a-4224-b429-9fa5294ce9b8.png">
