### ISSUE TITLE
[CSS] [LESS] use antd in container

### ISSUE THREAD

**Issue by long76** [ant-design/ant-design#38357]
### What problem does this feature solve?

in multi project app where each project use own frontend will be usefull apply styles not for all html but on some element

### What does the proposed API look like?

add class antd-container for element where planned using antd components

**Comment by afc163** [comment]
Try antd v5 https://github.com/ant-design/ant-design/issues/33862

ref https://github.com/ant-design/ant-design/issues/9363

**Comment by long76** [comment]
> Try antd v5 #33862
> 
> ref #9363

thanks!
