### ISSUE TITLE
Upload组件不设置action属性时，onChange会被重复触发3次

### ISSUE THREAD

**Issue by lamovv** [ant-design/ant-design#38351]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-82ddfp?file=/index.js)

### Steps to reproduce

```jsx
import type { UploadProps } from 'antd';
import { Upload } from 'antd';
import 'antd/dist/antd.css';
import React from 'react';

const props: UploadProps = {
  name: 'file',
  onChange(info) {
    // 未配置action属性，这里会重复触发3次
    console.log('repeat');
  },
};

const App: React.FC = () => <Upload {...props}>Click to Upload</Upload>;

export default App;
```

### What is expected?

onChange正常只触发一次

### What is actually happening?

onChange回调被触发了三次

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | react@17.0.2 |
| System | mac 12.6 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 |

**Comment by zombieJ** [comment]
不设置 action 上传就是当前地址。你打印一下 info 里的 file 信息，分别为：
* uploading 0%
* uploading 100%
* failed

**Comment by lamovv** [comment]
感谢
