### ISSUE TITLE
treeSelect组件，展开树点击某一层级，整颗树层级都被收起来了

### ISSUE THREAD

**Issue by yangxf1854** [ant-design/ant-design#38358]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-antd-4-23-5-forked-2e19x4?file=/demo.js)

### Steps to reproduce

1、在搜索框中输入“莹姐”
2、搜索到数据后，点击任意一下级的收起图标小箭头。整颗树都被收起来了

### What is expected?

点击哪一层收起就收起哪一层，不要整颗树收起来

### What is actually happening?

点击任意一层（包括下级或者平级），收起了全部

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 18.2.0 |
| System | macOS Monterey12.1 |
| Browser | 谷歌 版本 106.0.5249.119（正式版本） (arm64) |

**Comment by zombieJ** [comment]
<img width="562" alt="截屏2022-11-03 15 29 34" src="https://user-images.githubusercontent.com/5378891/199667151-29c77787-b09e-46a0-bdc7-b9c02dbe5d63.png">

`value` 要唯一。
