### ISSUE TITLE
drawer  Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by DanielWLam** [ant-design/ant-design#38352]
### Reproduction link

[https:www.alipay.com/pleasetryyourself](https:www.alipay.com/pleasetryyourself)

### Steps to reproduce

添加组件即报错

### What is expected?

组件正常使用

### What is actually happening?

Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at findExistNode (dynamicCSS.js:62:49)
    at removeCSS (dynamicCSS.js:71:19)
    at useScrollLocker.js:25:7
    at commitHookEffectListMount (react-dom.development.js:20573:26)
    at commitLifeCycles (react-dom.development.js:20634:11)
    at commitLayoutEffects (react-dom.development.js:23426:7)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at commitRootImpl (react-dom.development.js:23151:9)

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 17 |
| System | mac os |
| Browser | chrome 106 |

**Comment by adamblok** [comment]
I've got the same problem after updated to 4.24. The exception is throw whenever I try to use <Drawer> component.

**Comment by imfycc** [comment]
I've got the same problem after updated to 4.24. I rolled back the version to 4.23.6 and it is fine.

**Comment by H-Sven** [comment]
I've got the same problem after updated to 4.24. The exception is throw whenever I try to use component.

**Comment by imfycc** [comment]
亲，您的邮件我收到了，感谢您的来信。

**Comment by yoyo837** [comment]
请尝试删除node_module 和 lock 文件, 重新安装.

**Comment by H-Sven** [comment]
> 请尝试删除node_module 和 lock 文件, 重新安装.

没用

**Comment by imfycc** [comment]
> 请尝试删除node_module 和 lock 文件, 重新安装.

我这有用，不过会有其他问题：

Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead.

替换成 menu 后，Dropdown 组件就崩溃用不了。

**Comment by Guribeiro** [comment]
remeber to import `import 'antd/dist/antd.css';` at the top of your index.js file.

```
import 'antd/dist/antd.css';
import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const container = document.getElementById('root');
const root = createRoot(container);

root.render(<App />)
```
