### ISSUE TITLE
DatePicker disabled time and enable time for range picker

### ISSUE THREAD

**Issue by zzzzxiao** [ant-design/ant-design#3836]
#### 发生问题的环境是：

- antd 版本:antd@2.4.2
- 操作系统及其版本:windows10
- 浏览器及其版本:chrome53.0.2785.143 m (64-bit)

#### 您期待的结果是:
DatePicker showTime 限制了时分秒 range picker的可选值，比如起始时间我限制了只能选择30分或者00分，当我清空输入框的时间再重新选择日期的时候，时分秒默认值只能从我限制的时间里面取值

#### 实际上的结果是:
当我清空输入框的时间再重新选择日期的时候，时分秒默认为本地当前时间，不是我showTime里面限制的时间
![11](https://cloud.githubusercontent.com/assets/5946172/20259896/34061504-aa92-11e6-8829-44c0f59175df.jpg)
![22](https://cloud.githubusercontent.com/assets/5946172/20259899/35e7c9c6-aa92-11e6-99cf-ec24cd0e38bd.jpg)

**Comment by benjycui** [comment]
因为 `disabledTime` 是很灵活的一个配置，所以组件内部处理会很复杂，所以建议通过 `showTime` 去设置 TimePicker 的值为一个合法值。

相关 issue https://github.com/ant-design/ant-design/issues/3839

**Comment by zzzzxiao** [comment]
如何禁止用戶輸入不合法時間，或者输入不符合规范的自动变为range picker范围内的时间？

**Comment by benjycui** [comment]
> 输入不符合规范的自动变为range picker范围内的时间？

value 是受控属性，可以自行处理。
