### ISSUE TITLE
RangePicker组件属性 文档与实际不一致

### ISSUE THREAD

**Issue by earthaYan** [ant-design/ant-design#38362]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/currying-dream-v5wfi3?file=/index.js)

### Steps to reproduce

直接打开查看代码即可

### What is expected?

期望文档与实际代码能够保持一致

### What is actually happening?

文档中显示dropdownClassName属性自4.23.0版本起已修改为popupClassName，但实际并没有，依旧只能使用ropdownClassName

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.0.0 |
| System | windows 11 |
| Browser | chrome |

**Comment by afc163** [comment]
生效的：https://codesandbox.io/s/headless-wave-3f2kb2

**Comment by zombieJ** [comment]
<img width="464" alt="截屏2022-11-03 16 44 14" src="https://user-images.githubusercontent.com/5378891/199678611-4f67d777-b93c-47f0-b274-99817b413ed1.png">

大版本里不做 break change，但是会提供警告信息提示迁移哈~

**Comment by earthaYan** [comment]
但是目测在typescript下会报错 @ @afc163 @zombieJ https://codesandbox.io/s/lucid-moon-dpl1hu?file=/src/App.tsx

**Comment by earthaYan** [comment]
https://codesandbox.io/s/lucid-moon-dpl1hu?file=/src/App.tsx  目测在typescript下使用popUpClassName 会报错 @afc163 @zombieJ 

> No overload matches this call.
  Overload 1 of 2, '(props: RangePickerProps<Moment>, context?: any): Component<RangePickerProps<Moment>, unknown, any> & CommonPickerMethods', gave the following error.
    Type '{ popClassName: string; dropdownClassName: string; }' is not assignable to type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Moment>, unknown, any> & CommonPickerMethods> & Readonly<...>)'.
      Property 'popClassName' does not exist on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Moment>, unknown, any> & CommonPickerMethods> & Readonly<...>)'.
  Overload 2 of 2, '(props: RangePickerProps<Moment>, context?: any): Component<RangePickerProps<Moment>, unknown, any>', gave the following error.
    Type '{ popClassName: string; dropdownClassName: string; }' is not assignable to type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Moment>, unknown, any>> & Readonly<...>)'.
      Property 'popClassName' does not exist on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Moment>, unknown, any>> & Readonly<...>)'.ts(2769)

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/38294

Trace #38325
