### ISSUE TITLE
[Tree] When use treeData without "key", typescript reports a type error.

### ISSUE THREAD

**Issue by superbull** [ant-design/ant-design#38363]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blue-moon-0rs3hp?file=/src/App.tsx)

### Steps to reproduce

use Tree component with treeData without a "key" field

### What is expected?

the typescript compiler should not complain the treeData when a custom "fieldNames" is defined.

### What is actually happening?

the typescript compiler complains about the treeData:

(property) treeData?: (BasicDataNode | DataNode)[] | undefined
Type 'CatalogTree[]' is not assignable to type '(BasicDataNode | DataNode)[]'.
  Type 'CatalogTree' is not assignable to type 'BasicDataNode | DataNode'.
    Type 'CatalogTree' is not assignable to type 'DataNode'.
      Property 'key' is missing in type 'CatalogTree' but required in type '{ key: string | number; title?: ReactNode | ((data: DataNode) => ReactNode); }'.ts(2322)
interface.d.ts(20, 5): 'key' is declared here.
Tree.d.ts(38, 5): The expected type comes from property 'treeData' which is declared here on type 'IntrinsicAttributes & TreeProps<BasicDataNode | DataNode> & { children?: ReactNode; } & { ref?: Ref<Tree<DataNode>> | undefined; }'

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | Win10 |
| Browser | Chrome 106.0.5249.121 |

**Comment by superbull** [comment]
![image](https://user-images.githubusercontent.com/455630/199680777-7e4f9f04-61d2-4d5d-8769-8679b827e465.png)

**Comment by zombieJ** [comment]
https://codesandbox.io/s/objective-roentgen-hkiq98?file=/src/App.tsx:43-56

**Comment by raffidahmad** [comment]
> https://codesandbox.io/s/objective-roentgen-hkiq98?file=/src/App.tsx:43-56

treeData={categories as unknown as TreeDataNode[]}

Is this still a valid solution? The type is only DataNode for the treeData now and not BasicDataNode
