### ISSUE TITLE
input 输入框在火狐浏览器下，光标位置错位的问题

### ISSUE THREAD

**Issue by killdada** [ant-design/ant-design#38364]
### Reproduction link

[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce

1：官方链接里面最后一个文本输入框输入了一堆文字以后
2：光标移动到文字中间内容，开始输入其他文字
3：输入成功以后光标自动移动到文字最右边了

### What is expected?

从文字中间输入内容，光标保持正常，

### What is actually happening?

从文字中间输入内容，光标跑到最右边

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 17 |
| System | windw10 |
| Browser | 火狐 106.0.3（64位） |

**Comment by killdada** [comment]
输入框正常，文本域有这个问题

**Comment by afc163** [comment]
我这里没重现。能录个屏么

**Comment by killdada** [comment]
客户发的视频有这个问题，我昨天试了下也重现了，今天试的官方地址没有重现，我先关闭了。客户那个地址等我升级个版本再看下
