### ISSUE TITLE
Modal对话框 建议新增通过参数配置开启窗口拖拽功能

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#38360]
### What problem does this feature solve?
Modal对话框 建议新增通过参数配置开启窗口拖拽功能
![image](https://user-images.githubusercontent.com/3166799/199672370-f22ccb38-4df3-447e-a9c0-2b0d7c882e8d.png)

**Comment by afc163** [comment]
拖拽配置和交互细节很多，建议自行参考演示进行封装：https://ant.design/components/modal-cn/#components-modal-demo-modal-render
