### ISSUE TITLE
MenuItemType interface lacks `onContextMenu` attribute.

### ISSUE THREAD

**Issue by messaooudi** [ant-design/ant-design#38370]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-deprecated-syntactic-sugar-antd-4-24-0-forked-jn3ydd?file=/demo.tsx)

### Steps to reproduce

Add `onContextMenu` to a `MenuItemType` object

### What is expected?

The `MenuItemType` interface contains a `onContextMenu` attribute.

### What is actually happening?

The `MenuItemType` interface does not contain a `onContextMenu` attribute, leading to a typescript error.

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
There is no `onContextMenu` prop for Menu Item.

**Comment by messaooudi** [comment]
> There is no `onContextMenu` prop for Menu Item.

Note that the following works at runtime:
```js
const menuItem= {
  key: "item-1",  
  label: "item 1",
  onContextMenu: () => alert("context menu")
};
```
