### ISSUE TITLE
Table的title属性使用函数和直接传入ReactNode行为不一致

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#38371]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-24-0-forked-bgjhv3?file=/demo.tsx)

### Steps to reproduce

列配置的title如果是ReactNode,只取子一个子元素，如果是 () => ReactNode, 则会取整个

![image](https://user-images.githubusercontent.com/22299421/199749395-db8ad847-d273-4d7b-87b6-7b25498ae6be.png)

### What is expected?

都去整个ReactNode 作为title

### What is actually happening?

表现不一致

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | macOS |
| Browser | chrome |

**Comment by Wxh16144** [comment]
可否让我来试试?

**Comment by afc163** [comment]
Sure!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/21c4bcf40ab3aea8b2681f70c45b23a4d37de43b#diff-1c38d6be6ec30ec3a79f8c51605d41eca9b6300300f570f3fe5a22c2a8064101R47 

这里改挂的。cc @kiner-tang

**Comment by kiner-tang** [comment]
> [21c4bcf#diff-1c38d6be6ec30ec3a79f8c51605d41eca9b6300300f570f3fe5a22c2a8064101R47](https://github.com/ant-design/ant-design/commit/21c4bcf40ab3aea8b2681f70c45b23a4d37de43b#diff-1c38d6be6ec30ec3a79f8c51605d41eca9b6300300f570f3fe5a22c2a8064101R47)
> 
> 这里改挂的。cc @kiner-tang

我看看

**Comment by Wxh16144** [comment]
> > [21c4bcf#diff-1c38d6be6ec30ec3a79f8c51605d41eca9b6300300f570f3fe5a22c2a8064101R47](https://github.com/ant-design/ant-design/commit/21c4bcf40ab3aea8b2681f70c45b23a4d37de43b#diff-1c38d6be6ec30ec3a79f8c51605d41eca9b6300300f570f3fe5a22c2a8064101R47)
> > 这里改挂的。cc @kiner-tang
> 
> 我看看

我们是不是可以不修改 `renderColumnTitle` 方法，这是在 https://github.com/ant-design/ant-design/blob/master/components/table/hooks/useSorter.tsx#L209-L219 这里使用  `getElementFirstTextContent` 方法
