### ISSUE TITLE
【bug】4.4.2版本之后，分页组件出现滚动条闪动错误

### ISSUE THREAD

**Issue by mu-mx** [ant-design/ant-design#38379]
### Reproduction link

[https://stackblitz.com/edit/react-auqmte?file=demo.tsx](https://stackblitz.com/edit/react-auqmte?file=demo.tsx)

### Steps to reproduce

const App: React.FC = () => (
  <Pagination
    style={{
      display: 'flex',
      justifyContent: 'flex-end',
    }}
    total={85}
    showSizeChanger
    showQuickJumper
    showTotal={(total) => `Total ${total} items`}
  />
);

点击Open in New Tab ，   可以看到 分页居右之后 再 点击分页条数出现下拉，并且出现滚动条闪动   bug

### What is expected?

禁止闪动，因为这在4.4.2之前的版本是没有的，更新版本之后出现

### What is actually happening?

bug

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18 |
| System | window |
| Browser | 最新版谷歌 |

---
和table组件组合一起会出现滚动条闪动

**Comment by afc163** [comment]
<img width="770" alt="图片" src="https://user-images.githubusercontent.com/507615/199918150-0c4e6d8a-0ae4-434c-93a3-fd3fad368064.png">
你给的例子没有重现出问题。

**Comment by mu-mx** [comment]
![image](https://user-images.githubusercontent.com/22007967/199918463-c7f79d92-a3e3-48a7-92cc-943b1bd7f109.png)

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/199922245-9ec2f9b1-f529-46df-aaa4-20b867982959.png">
不知道为啥，我全局翻墙也打不开这个 new tab。

**Comment by mu-mx** [comment]
[screencast-nimbus-capture-2022.11.04-16_07_07.webm](https://user-images.githubusercontent.com/22007967/199924181-3f67315b-3650-4506-81ee-bf9e3e36cac5.webm)

**Comment by mu-mx** [comment]
录制的有点模糊，但是可以看到下方出现了滚动条在闪动，当我切换回4.2.1之前的版本就没有这个问题了，4.2.2开始出现的

**Comment by afc163** [comment]
确实有这个问题。

**Comment by afc163** [comment]
帮忙看看是只有 Pagination 有这个问题，还是单独用 Select 以及其他弹层组件也有这个问题。

**Comment by mu-mx** [comment]
测过的！目前只有 Pagination 有这个问题，单独使用 Select 放在右边没有这个问题。早先版本 Pagination 4.4.x之前是没有问题的

**Comment by afc163** [comment]
4.2.2 还是 4.4.2？

版本号是 antd 还是 rc-pagination?

**Comment by mu-mx** [comment]
复测了一下，确认是版本号   4.4.2 及之后出现的问题 
![微信截图_20221107115756](https://user-images.githubusercontent.com/22007967/200223563-401dcb7f-24ff-4806-9380-c7ca26655a82.png)

**Comment by Wxh16144** [comment]
我的 Chrome: 107.0.5304.87 未复现问题

https://user-images.githubusercontent.com/32004925/200485873-bb55b96d-bab1-42ef-8637-76c9c658ba6f.mp4

**Comment by tinyfind** [comment]
上面的例子，尝试缩小浏览器界面，就会出现
