### ISSUE TITLE
switch组件的一个样式小问题

### ISSUE THREAD

**Issue by woshiguabi** [ant-design/ant-design#3838]
![switch](https://cloud.githubusercontent.com/assets/17465858/20260076/f62897a6-aa92-11e6-8538-afa9947bd9d9.jpg)
如图 active状态下的switch 
```
.ant-switch-checked:active:after {
    left: 16px;
}
```
样式似乎错位了

改为`left:36px;`后
![swtich1](https://cloud.githubusercontent.com/assets/17465858/20260119/33686bdc-aa93-11e6-9459-a8e3efddebc4.jpg)

不知道是不是设计师有意为之的缩回效果？
small的switch同上

**Comment by afc163** [comment]
应该是 bug，我一会看看。

**Comment by afc163** [comment]
细致 👍
