### ISSUE TITLE
InputNumber在Form里使用时输入-0会变成0

### ISSUE THREAD

**Issue by JS-an** [ant-design/ant-design#38382]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhu-ce-xin-yong-hu-antd-4-24-0-forked-0yo60h?file=/demo.tsx)

### Steps to reproduce

Donation字段输入-0.1会变成0.1

### What is expected?

输入-0.1 显示-0.1

### What is actually happening?

0.1

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | react  |
| System | win10 |
| Browser | 版本 98.0.4758.102（正式版本） （64 位） |

**Comment by kiner-tang** [comment]
这看起来是用于格式化的正则表达式的问题？

**Comment by JS-an** [comment]
> 这看起来是用于格式化的正则表达式的问题？

同样的表达式在没有Form的InputNumber中使用是正确的

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/32706#issuecomment-960526694
