### ISSUE TITLE
I can't reset field at the nested form's item 

### ISSUE THREAD

**Issue by DonRyu** [ant-design/ant-design#38396]
### Reproduction link

[https://ant.design/components/form/#components-form-demo-dynamic-form-items-complex](https://ant.design/components/form/#components-form-demo-dynamic-form-items-complex)

### Steps to reproduce

 Q: How can I reset   name={['customer_section2', 'dispatcher_id']} field?

-form.resetFields({ customer_section2: [] }); not working
-form.setFieldsValue({customer_section2: []}); working but after I clear, I can't input (Whenever I try to input, it deletes automatically)

<Form.Item
            className={'box'}
            label={'Dispatcher'}
            name={['customer_section2', 'dispatcher_id']}
            rules={[{required: true}]}
          >
            <Select style={{width: 200}}>
              <Option value="dispatcher_id_key">hong kim</Option>
            </Select>
 </Form.Item>

### What is expected?

Delete the form.item at the nested form

### What is actually happening?

-form.resetFields({ customer_section2: [] }); not working
-form.setFieldsValue({customer_section2: []}); working but after I clear, I can't input (Whenever I try to input, it deletes automatically)

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 17.0.43 |
| System | Mac |
| Browser | chrome |

---
There is only very poor explanation about form.resetfield. Please, put some more explanation.

**Comment by kiner-tang** [comment]
It seem that you can use `namePath`.
```typescript
form.resetFields(['customer_section2', 'dispatcher_id']);
```
