### ISSUE TITLE
Codepen模板Demo里面Select的宽度不对

### ISSUE THREAD

**Issue by pixystone** [ant-design/ant-design#3840]
首页上Codepen的[模板](http://codepen.io/benjycui/pen/KgPZrE?editors=001)，Select组件是这样的：

![image](https://cloud.githubusercontent.com/assets/3050696/20263297/f2a9e554-aaa0-11e6-982d-8c47c7f55408.png)

正常是这样么？哪里css不对了？

**Comment by afc163** [comment]
1. 没给预设宽度。
2. @benjycui 怎么把默认模板给改了？

**Comment by benjycui** [comment]
因该是测试别人的 demo 时不小心改了。。不熟悉 CodePen 的用法。

已恢复。
