### ISSUE TITLE
image组件 顶部工具栏可否开放自定义

### ISSUE THREAD

**Issue by H-Sven** [ant-design/ant-design#38418]
### What problem does this feature solve?

顶部工具栏目前自带了旋转、缩放、关闭功能， 请问这块能否自定义内容，例如增加自定义dom按钮， 开关控制旋转等功能

### What does the proposed API look like?

新增toolbarRender属性，自定义渲染dom， 暴露上述api能力

**Comment by afc163** [comment]
好主意。

**Comment by AnteeHub** [comment]
是否会考虑开放预览状态下图片的自定义渲染能力？
比如我想在图片上渲染一些浮动的按钮。比如像图中黄色框框选出来的按钮一样：

![image](https://user-images.githubusercontent.com/55703989/200283844-daccdbb9-d176-4278-a53c-c994eb2d967c.png)

**Comment by huangkairan** [comment]
WIP

**Comment by danhua1** [comment]
预览按钮的旋转和放大按钮的点击没有控制冒泡导致会触发外层的点击事件。

**Comment by danhua1** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-0-3-forked-rfs4vd?file=/demo.tsx 追加一下demo

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/43075
