### ISSUE TITLE
Text 组件异常打开问题

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#38425]
### Reproduction link

[https://stackblitz.com/edit/react-5rc9ch?file=demo.tsx](https://stackblitz.com/edit/react-5rc9ch?file=demo.tsx)

### Steps to reproduce

鼠标先放到第二条数据上，然后移动鼠标到 click 按钮上，然后点击按钮

### What is expected?

不弹出 tooltip

### What is actually happening?

弹出 tooltip

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
排查方式，给`Typography.Text` 组件添加  key，可以解决。

**Comment by afc163** [comment]
Chrome 下可重现，Firefox 下没问题。

**Comment by crazyair** [comment]
> Chrome 下可重现，Firefox 下没问题。

Firefox 复现了

**Comment by crazyair** [comment]
#38431
