### ISSUE TITLE
ant-table表格rowSelection的columnWidth目前是最小宽度，我希望他能变成定宽

### ISSUE THREAD

**Issue by heningyuan6256** [ant-design/ant-design#38427]
### What problem does this feature solve?

ant-table表格rowSelection的columnWidth目前是最小宽度，我希望他能变成定宽，不根据表格剩余的空间而等比例分配

### What does the proposed API look like?

增加一个属性可以控制checkbox宽度不变

**Comment by afc163** [comment]
这个是表格布局决定的，你可以设置 `tableLayout="fixed"` 来修改表格布局方式。
