### ISSUE TITLE
Table: make column header clickable to sort by that column

### ISSUE THREAD

**Issue by chris-a-g** [ant-design/ant-design#3843]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by benjycui** [comment]
See: https://ant.design/components/table/?locale=en-US#components-table-demo-reset-filter

**Comment by Minasokoni** [comment]
@benjycui Is there anything in the API that would allow a table header cell click rather than a table cell row click? I would like to achieve the same as @chris-a-g

**Comment by benjycui** [comment]
@Minasokoni `columns[n].title` could be a ReactNode.

```jsx
[{
  title: <span onClick={...}>...</span>
  ...
}]
```

**Comment by Minasokoni** [comment]
@benjycui amazing! Thank you.
