### ISSUE TITLE
DatePicker 时间选择错乱

### ISSUE THREAD

**Issue by SturdyCat** [ant-design/ant-design#38432]
### Reproduction link

[https://github.com/SturdyCat/DatePicker-bug.git](https://github.com/SturdyCat/DatePicker-bug.git)

### Steps to reproduce

点击开始时间选择时间大于截止时间时，变成  00:00:00

### What is expected?

起始时间大于截止时间
起始时间保持录入，同时截止时间等于起始时间

### What is actually happening?

起始时间变成 00:00:00

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | v18.1 |
| System | macos 13.0 |
| Browser | chrome 107.0.5304.87 |

![image](https://user-images.githubusercontent.com/16874676/200488303-49f1b102-236a-40c8-8d5b-aa3bd80e05a6.png)

**Comment by zombieJ** [comment]
你的示例里写死了 value 值，非受控或者完整受控就好了：https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-4-24-0-forked-xj9urx?file=/demo.tsx
