### ISSUE TITLE
文件上传拖拽文件报错

### ISSUE THREAD

**Issue by yichenw7** [ant-design/ant-design#38436]
### Reproduction link

[https://3x.ant.design/components/upload-cn/](https://3x.ant.design/components/upload-cn/)

### Steps to reproduce

文件上传功能，点击可以上传，拖拽图片上传报错，不生效

### What is expected?

拖拽图片正常上传

### What is actually happening?

拖拽图片无法上传，控制台有错误提示Uncaught TypeError: t.drop is not a function

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | "react": "^15.1.0", |
| System | "antd": "3.6.4", |
| Browser |  谷歌浏览器107.0.5304.87 |

---
Uncaught TypeError: t.drop is not a function

**Comment by zombieJ** [comment]
3x 已经过了维护期了哈，另外官网示例是好的。
