### ISSUE TITLE
antd 4.24.1 的版本里 Dropdown.Button 出现了错误的警告

### ISSUE THREAD

**Issue by buuing** [ant-design/ant-design#38441]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tender-shape-e6immx?file=/src/App.js )

### Steps to reproduce

使用Dropdown.Button组件即可看到错误的警告

### What is expected?

使用menu属性之后, 不再弹出警告

### What is actually happening?

我没有使用overlay属性, 用了menu属性, 但还是有这个警告

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by buuing** [comment]
![image](https://user-images.githubusercontent.com/36689704/200573870-17cb0eca-ff22-44df-90f2-04f1e8d435a5.png)

以下是可复现问题的代码, 可以看到我使用了menu属性, 但依然出现了奇怪的警告

```
      <Dropdown.Button
        icon={<DownOutlined />}
        menu={{
          items: [
            {
              key: "1",
              label: (
                <a target="_blank" href="http://baidu.com" rel="noreferrer">
                  百度
                </a>
              )
            }
          ],
          onClick: (e) => {
            console.log(e);
          }
        }}
      >
        123
      </Dropdown.Button>
```

**Comment by afc163** [comment]
@JarvisArt

**Comment by li-jia-nan** [comment]
啊，没看到你的 comment，我刚已经修了
