### ISSUE TITLE
Table - Filter dropdown Flicker

### ISSUE THREAD

**Issue by Harshini2898** [ant-design/ant-design#38442]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/filter-search-antd-4-23-6-forked-8bb1y3?file=/demo.tsx)

### Steps to reproduce

1. Click on filter icon for "Name" column
2. Select "Joe" Option from dropdown and press "Ok"

### What is expected?

Close the filter dropdown and display the filtered table data

### What is actually happening?

Filter dropdown is flickering before completely closing

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.3.0 |
| System | MacOS Monterey 12.3 |
| Browser | Version 107.0.5304.87 (Official Build) (arm64) |

**Comment by afc163** [comment]
I can't reproduce it in your codesandbox, could you provide a video?

**Comment by Harshini2898** [comment]
Attaching video.

https://user-images.githubusercontent.com/31417310/200811603-b0b26052-d014-458c-b05e-ee60614db2d2.mov

**Comment by Harshini2898** [comment]
I attached the video, please let me know if any more info needed.

**Comment by afc163** [comment]
Similar to https://github.com/ant-design/ant-design/issues/35986

**Comment by afc163** [comment]
Could you try antd@5.5.1 to see if there is still a problem?

**Comment by afc163** [comment]
Fixed in 5.x https://codesandbox.io/s/filter-search-antd-4-23-6-forked-2gl994?file=/package.json
