### ISSUE TITLE
upload 上传失败 503

### ISSUE THREAD

**Issue by liuyingjie1130** [ant-design/ant-design#38455]
### Reproduction link

[https://ant-design.gitee.io/components/upload-cn/#API](https://ant-design.gitee.io/components/upload-cn/#API)

### Steps to reproduce

antd官网 upload上传失败

### What is expected?

上传成功

### What is actually happening?

上传失败

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | mac  |
| Browser | chrome |

**Comment by liuyingjie1130** [comment]
![image](https://user-images.githubusercontent.com/25972488/200728304-7cdd12f0-977e-4be7-a04c-f2c98c730a64.png)

**Comment by afc163** [comment]
这只是个演示，服务端本身是用的 mock 地址，正常情况。
