### ISSUE TITLE
Small size 的 table border 显示有问题

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#3845]
#### 可重现的在线演示

http://codepen.io/yesmeck/pen/pNbajW?editors=0010

右边的 border 是多余的。

跟 https://github.com/ant-design/ant-design/issues/3803 有关系

**Comment by afc163** [comment]
感觉没有关系。

**Comment by yesmeck** [comment]
而且感觉不好修。

**Comment by afc163** [comment]
无解，浏览器的问题。

**Comment by yesmeck** [comment]
那先关了。

**Comment by afc163** [comment]
右边的 border 在 https://github.com/ant-design/ant-design/commit/9e6439b06cd099ab384a4a2f026f0def6e12bf23 里修复了。
