### ISSUE TITLE
After the screen size changes, the console reports an error and the page appears blank in Umi4.0 framwork

### ISSUE THREAD

**Issue by Connor-lipalater** [ant-design/ant-design#38452]
### Reproduction link

[https://spdev.lipalaterapis.com/order](https://spdev.lipalaterapis.com/order)

### Steps to reproduce

Change the size of the browsing window, the page will appear blank, and the console will report an error

### What is expected?

Page adaptive display content

### What is actually happening?

The page will appear blank, and the console will report an error

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 18.6 |
| System | windows10 |
| Browser | Version 104.0.5112.102 |

**Comment by Connor-lipalater** [comment]
umi.js:122 TypeError: Cannot read properties of undefined (reading 'apply')

**Comment by afc163** [comment]
Should it report to umi project?
