### ISSUE TITLE
Table: enter event in custom filterDropdown triggeres unwanted sort event

### ISSUE THREAD

**Issue by StefanPahlplatz** [ant-design/ant-design#38464]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-antd-4-24-1-forked-4d623f)

### Steps to reproduce

- Click the search icon in the 'Address' column
- Popup opens, click in the input to focus the input.
- Press enter
- The popup closes (this is expected), but the table sorts the column (this is unexpected).

### What is expected?

That when searching in the input box, this is limited to the search variable, not the sorting state of the column.

### What is actually happening?

The sorting state of the column is impacted.

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 16.14.0 |
| System | Pop!_OS 22.04 LTS |
| Browser | Chrome Version 107.0.5304.87 (Official Build) (64-bit) |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/38393

**Comment by StefanPahlplatz** [comment]
Hello @afc163,

Unfortunately, it appears that with the new version this has not been fixed.

See the updated sandbox: https://codesandbox.io/s/customized-filter-panel-antd-4-24-1-forked-4d623f
