### ISSUE TITLE
Form调用resetFields无法清除DatePicker输入框里文字

### ISSUE THREAD

**Issue by dtcymmtc** [ant-design/ant-design#3846]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:mac os 10.11.6 (15G1104)
- 浏览器及其版本:Google Chrome 51.0.2704.103 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

Form调用resetFields

#### 您期待的结果是:

DatePicker里的文字被清除了

#### 实际上的结果是:

DatePicker里的文字没有被清除

#### 可重现的在线演示

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by dtcymmtc** [comment]
antd 版本:2.4.2

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
猜测是这个问题 https://github.com/ant-design/ant-design/issues/3746

**Comment by afc163** [comment]
把 `'value' in props` 的判断回滚好了，省得这么多咨询。
