### ISSUE TITLE
升级到最新版后， antd内部依赖dynamicCSS报错，Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by H-Sven** [ant-design/ant-design#38467]
### Reproduction link

[httsp://demo.com](httsp://demo.com)

### Steps to reproduce

老项目，无法定位具体哪个组件报错

### What is expected?

正常渲染

### What is actually happening?

function findExistNode(key) {
  var option = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  var container = getContainer(option);
  return Array.from(containerCache.get(container).children).find(function (node) {
    return node.tagName === 'STYLE' && node[MARK_KEY] === key;
  });
}

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | "react": "^16.10.0", |
| System | mac |
| Browser | chrome |

---
控制台报错信息显示是内部依赖库import { updateCSS, removeCSS } from "rc-util/es/Dom/dynamicCSS";
removeCSS这个方法报错
<img width="623" alt="image" src="https://user-images.githubusercontent.com/26042365/200832308-0516c231-3a3b-4bfb-b98b-e8af697a9446.png">
<img width="576" alt="image" src="https://user-images.githubusercontent.com/26042365/200832407-9366e5ee-1d61-47d7-b944-6121c8ca044b.png">

**Comment by H-Sven** [comment]
"rc-util": "^5.22.5", 这个包版本有问题

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/38352#issuecomment-1308723252

**Comment by li-jia-nan** [comment]
是ssr项目吗？

**Comment by H-Sven** [comment]
> 可能是 [react-component/portal#6](https://github.com/react-component/portal/issues/6) 这个问题。

我通过降级排查，发现在4.22.8这个版本开始就存在这个问题

**Comment by H-Sven** [comment]
会在最近的版本中修复这个问题吗

**Comment by afc163** [comment]
@H-Sven 我们没有办法重现这个问题。

**Comment by H-Sven** [comment]
> @H-Sven 我们没有办法重现这个问题。

删除node_modules和package-lock.json 似乎解决了，但是昨晚这样操作问题还是存在，不知道为什么现在好了

**Comment by afc163** [comment]
有可能是我发了一个 https://github.com/react-component/portal/releases/tag/v1.0.3
