### ISSUE TITLE
Need more LESS variables for customizing buttons

### ISSUE THREAD

**Issue by kaiyoma** [ant-design/ant-design#38476]
### What problem does this feature solve?

The existing set of LESS variables for customizing buttons is not extensive enough.

### What does the proposed API look like?

We would like the following customizations for all button types (primary, default, link, danger, etc):

* Ability to disable box-shadow
* Ability to disable text-shadow
* Change the background color on focus
* Change the border color on focus
* Change the text color on focus
* Change the background color on hover
* Change the border color on hover
* Change the text color on hover
* Change the background color on active
* Change the border color on active
* Change the text color on active
* Change the loading opacity

**Comment by afc163** [comment]
less variables won't be updated because we change to CSS-in-JS now: https://medium.com/ant-design/ant-design-5-0-alpha-is-ready-509c38db39fb?source=friends_link&sk=113588092a6c8165234043544b267195
