### ISSUE TITLE
CarouselRef is not exported and cannot be imported

### ISSUE THREAD

**Issue by alamorre** [ant-design/ant-design#38470]
### Reproduction link

[https://github.com](https://github.com)

### Steps to reproduce

Try to import the following:
import type { CarouselRef } from "antd";
It will not work.

### What is expected?

It should compile

### What is actually happening?

CarouselRef is not being exported globally

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by JarvisArt** [comment]
correct usage
```jsx
import { CarouselRef } from 'antd/es/carousel';
```
