### ISSUE TITLE
modal 关闭后不再渲染内部内容

### ISSUE THREAD

**Issue by flonny** [ant-design/ant-design#38479]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-24-0-forked-6ep3kj?file=/package.json)

### Steps to reproduce

打开弹窗 渲染 close-render 元素， 关闭时，close-render 未销毁

### What is expected?

close-render 销毁

### What is actually happening?

close-render 未销毁

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18.0.0 |
| System | mac 13.0 |
| Browser | chrome 107.0.5304.87 |

**Comment by afc163** [comment]
`destroyOnClose`
