### ISSUE TITLE
Add "type" property to "Icon"

### ISSUE THREAD

**Issue by Sagie501** [ant-design/ant-design#38485]
### What problem does this feature solve?

Sometimes when I'm using the icons I want to be able to change the color of the icon to one of the types ("primary", "secondary" etc..). It will be very useful to have `type` property similar to the `type` property on the `Button` component

### What does the proposed API look like?

Adding `type` property to the `Icon` components which have the values of `primary` | `ghost` | `dashed` | `link` | `text` | `default` or any something similar to that.

**Comment by zombieJ** [comment]
Pls wrapper with Typography.Text. Icon is not real component in antd.
