### ISSUE TITLE
Docs: Button docs don't include shape example

### ISSUE THREAD

**Issue by waywardmonkeys** [ant-design/ant-design#3848]
The docs for `Button` as seen at https://ant.design/components/button/ don't have an example for the `shape` property.

**Comment by afc163** [comment]
https://ant.design/components/button/#components-button-demo-icon

**Comment by waywardmonkeys** [comment]
Might be good to call that out specifically somehow since each other property basically has a section of its own.

**Comment by benjycui** [comment]
Next time, you can click the following button to expand all the demos' source code and search the property which you are interested in.

![image](https://cloud.githubusercontent.com/assets/3580607/20296007/64ff81ca-ab43-11e6-9bbb-8199d94a9a1a.png)

It's impossible to write demo for every property.
