### ISSUE TITLE
[V5] 暗色主题DatePicker弹出效果不正常

### ISSUE THREAD

**Issue by Dunqing** [ant-design/ant-design#38480]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-v439io?file=/index.js:256-601)

### Steps to reproduce

多点几次后稳定复现

### What is expected?

和默认主题一样

### What is actually happening?

无法正确弹出DatePicker

| Environment | Info |
| --- | --- |
| antd | 5@latest |
| React | * |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
没有试出来，给个录屏看看？

**Comment by Dunqing** [comment]
多点几次偶然成功复现有点怀疑和暗色没关系
https://user-images.githubusercontent.com/29533304/201023476-e7541481-d4a5-488f-b379-d921222b2e8b.mov

**Comment by afc163** [comment]
- [ ] 貌似没有弹出动画。

**Comment by afc163** [comment]
- [ ] DatePicker 和 Button 的样式是不是也有点问题。

<img width="371" alt="图片" src="https://user-images.githubusercontent.com/507615/201037977-db5afa7d-62cc-41bd-afc8-95610365d25a.png">

**Comment by Dunqing** [comment]
> * [ ]  DatePicker 和 Button 的样式是不是也有点问题。

我直接用的 #38450 的复现

**Comment by MadCcc** [comment]
> * [ ]  DatePicker 和 Button 的样式是不是也有点问题。
> 
> <img alt="图片" width="371" src="https://user-images.githubusercontent.com/507615/201037977-db5afa7d-62cc-41bd-afc8-95610365d25a.png">

这个是因为现在背景色计算有问题

**Comment by afc163** [comment]
<img width="383" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/df35a256-7b01-4a99-a868-73b1dbe0c077">

看上去现在都好了。https://codesandbox.io/s/antd-reproduction-template-forked-x8y05e?file=/index.js
