### ISSUE TITLE
Modal自定义居中显示IE9\10\11位置不正确

### ISSUE THREAD

**Issue by conan2008** [ant-design/ant-design#3849]
#### 发生问题的环境是：

- antd 版本: 1.x
- 操作系统及其版本: win10
- 浏览器及其版本:IE9、10、11

#### 您做了什么？请提供尽可能详细的重现步骤。
官网直接可以复现

#### 实际上的结果是:

![1q1xw 5 g rex 3 1kt6njn](https://cloud.githubusercontent.com/assets/16290807/20295194/85a60552-ab3e-11e6-823a-870a19e4d622.png)

**Comment by benjycui** [comment]
It works fine

![image](https://cloud.githubusercontent.com/assets/3580607/20296103/e65ea8f4-ab43-11e6-958a-f0d2cd94de34.png)


Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
话说你这个截图不是 1.x 版的文档。

**Comment by benjycui** [comment]
2.x 的话测试时正常的。

**Comment by conan2008** [comment]
@benjycui 我刚才是在IE11下  切换文档模式到IE9， 选择1.x版本无法切换（这个问题不关心哈。。）

您刚才点击的是 top：100px 那个是没问题，  看一下下边这个截图
![djd n rf65jyvaz8uomhf 0](https://cloud.githubusercontent.com/assets/16290807/20296415/a4e475c8-ab45-11e6-8416-f41ff22f04d4.png)

**Comment by afc163** [comment]
添加了一段 IE 兼容的演示代码。

**Comment by conan2008** [comment]
@afc163 感谢修复。 还有建议 Modal.info等 也增加一个 wrapClassName 属性吧。
