### ISSUE TITLE
Bug in TreeSelect component

### ISSUE THREAD

**Issue by miguelSoldado1** [ant-design/ant-design#38496]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/test-treedata-bug-fcpl9c)

### Steps to reproduce

select a child and a parent and it only selects one 
example: 
- child and parent selected and only child is selected, NOK
- parent and grandfather selected and only parent is selected, NOK
- child and grandfather selected and it works fine, OK

### What is expected?

child and parent are selected.

### What is actually happening?

only child is selected

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | react |
| System | 20H2 |
| Browser | Chrome 107 |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/test-treedata-bug-forked-cpejge?file=/demo.tsx
