### ISSUE TITLE
Slider style issue in 5.x

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#38490]
https://next.ant.design/components/slider-cn/

1. 拖动结束后缺少 focus 的样式，这样不方便继续 tab 键盘操作和了解当前页面交互点，建议参考 4.x 和 MUI：

<img width="294" alt="图片" src="https://user-images.githubusercontent.com/507615/201079083-664aee83-23e6-4c83-bedd-e5fc90ee2d11.png">
<img width="294" alt="图片" src="https://user-images.githubusercontent.com/507615/201079156-1feec4c6-7a97-45d6-8248-126dcc88e643.png">

2. hover 样式应该在对应的操作点上，现在是两个都会变成这个样式
<img width="292" alt="图片" src="https://user-images.githubusercontent.com/507615/201078974-fe8c4717-f0d3-47a7-b4aa-b3a217cb053a.png">

**Comment by Song2027** [comment]
1、之前没找到拖拽完毕以后 focus 效果还存在的具体使用场景，以为是个 bug 所以给去掉了，我们改回去；
2、不符合设计预期，应该改掉。

**Comment by Song2027** [comment]
问题一的改法：
1、保留放大状态（此刻可通过键盘操作）；
2、鼠标点击其他区域，切换为正常状态（不可键盘操作）。
![image](https://user-images.githubusercontent.com/52985178/201083129-ee413201-0c61-4a7e-9dec-b6d04fae3331.png)

**Comment by MadCcc** [comment]
> 2\. hover 样式应该在对应的操作点上，现在是两个都会变成这个样式

Tooltip 的定位问题，我统一改一下
