### ISSUE TITLE
antd v4.24.0 以上版本 Modal  getContainer 适用问题

### ISSUE THREAD

**Issue by Shany100** [ant-design/ant-design#38497]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-yc54uz?file=/index.js)

### Steps to reproduce

<Modal
  getContainer={() => { 
    const div = document.createElement('div');
    document.body.appendChild(div); // 或者是其他父级元素
    return div;
  }}
/>

### What is expected?

正常运行。
项目原有代码会每次弹出 Modal 时，要在 getContainer 创建新的 div 去挂载。

### What is actually happening?

导致死循环 crash 了。

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | react |
| System | windows 10 |
| Browser | chrome  106.0.5249.119（正式版本） (arm64) |

---
定位出的结果是因为 Dialog 引用的 Portal 是 rc-component 下的，用了 useEffect 设置 state innerContainer ，导致死循环 crash 了。

**Comment by zombieJ** [comment]
> getPopupContainer: 所有的 getPopupContainer 都需要保证返回的是唯一的 div。React 18 concurrent 下会反复调用该方法。

发现 v4 里没有写上这个，需要给 v4 文档补上。
