### ISSUE TITLE
[V5] Slider `tooltip` delay in close

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#38492]
### Reproduction link

[https://next.ant.design/components/slider](https://next.ant.design/components/slider)

### Steps to reproduce

https://user-images.githubusercontent.com/32004925/201080997-f73a0deb-b88a-4a48-afae-0b7958675fd3.mp4

### What is expected?

close now

### What is actually happening?

there is a delay, can not follow the mouse immediately move

| Environment | Info |
| --- | --- |
| antd | next |
| React | any |
| System | macOS 12.5 |
| Browser | Chrome: 107.0.5304.110 |

**Comment by afc163** [comment]
问题还在：https://ant.design/components/slider-cn
