### ISSUE TITLE
enter-animation 重构

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#385]

**Comment by yiminghe** [comment]
这个组件建议从 antd 删掉，不知道哪里会用到

**Comment by afc163** [comment]
已在重写中，涉及到 Ant Design 设计规范中动画进场效果，不建议移除。

**Comment by afc163** [comment]
https://github.com/react-component/queue-anim

**Comment by afc163** [comment]
已重构和改造完毕：http://ant.design/components/queue-anim/
