### ISSUE TITLE
ScrollBar error while using Firefox

### ISSUE THREAD

**Issue by xenbill** [ant-design/ant-design#38508]
### Reproduction link

[https://ant.design/components/select/](https://ant.design/components/select/)

### Steps to reproduce

While using Firefox open any drop-down menu and scroll with the mouse .. 

### What is expected?

Scroll

### What is actually happening?

When in production : Minified React error.
When in dev: Warning: `NaN` is an invalid value for the `top` css style property.

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | firefox 106.0.5 |

---
In chrome  is working as expected . Also when I am tyring  version 3.x (3.26.19) is working as expected.
Here is a screenshot : Left: what I see in development when I do the same thing
Right:what I see in antd site 
https://www.dropbox.com/s/ppve54noabimxpl/Screenshot%202022-11-11%2009.04.34.png?dl=0

**Comment by zombieJ** [comment]
试了一下没有报错，详细说一下操作步骤 & 录个屏看看？
