### ISSUE TITLE
Drawer mask设置为false时 背后的主窗口无法滚动

### ISSUE THREAD

**Issue by lvdougao1** [ant-design/ant-design#38506]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/angry-merkle-s5i8pe?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

展开组件时 mask为false 后面无法滚动

### What is expected?

展开组件时 mask为false 后面可以滚动

### What is actually happening?

展开组件时 mask为false 后面无法滚动

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.2 |
| System | macOs 12.0.1 |
| Browser | 谷歌107.0.5304.87 |

**Comment by afc163** [comment]
4.23.x 的行为是对的：https://codesandbox.io/s/cranky-robinson-j83e2c?file=/package.json
