### ISSUE TITLE
Select calls onSearch function with empty value when clicking for a second time in the input

### ISSUE THREAD

**Issue by roelvdboom** [ant-design/ant-design#38515]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w9w8ef?file=/index.js)

### Steps to reproduce

1. Type something in the input
2. Click in the input after the text
3. The onSearch function is called with an empty value

### What is expected?

The onSearch function shouldn't be called at all.

### What is actually happening?

The onSearch function is called with an empmty value.

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.2.0 |
| System | Ubuntu 20.04.5 LTS |
| Browser | Chrome: Version 107.0.5304.87 (Official Build) (64-bit) |

**Comment by sai6855** [comment]
hey team,  can i work on this issue?
