### ISSUE TITLE
message.loading 当duration设置为0时，手动关闭无法触发onclose

### ISSUE THREAD

**Issue by wangzj141** [ant-design/ant-design#38524]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0o3hz8?file=/index.js)

### Steps to reproduce

点击按钮

### What is expected?

控制台打印need log close msg与message close

### What is actually happening?

只打印了need log close msg

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 18.2 |
| System | window 11 |
| Browser | electron |

**Comment by afc163** [comment]
好像和 duration 没关系，设置成多少都不会触发 onClose。

**Comment by kiner-tang** [comment]
应该是这里也需要调用一下`onClose`
<img width="577" alt="image" src="https://user-images.githubusercontent.com/10286961/201516039-f0a2732b-3b87-44b5-8c30-cbacab99462f.png">

**Comment by yoyo837** [comment]
Close by #38669
