### ISSUE TITLE
文档官网疑似被劫持

### ISSUE THREAD

**Issue by debug-null** [ant-design/ant-design#38527]
### Reproduction link

[https://ant.design/components/dropdown-cn/?theme=dark](https://ant.design/components/dropdown-cn/?theme=dark)

### Steps to reproduce

点击官网更多中的 Ant design of vue 按钮后，跳转到了色情网站

网址：https://389295.cc/e.html?channelCode=a8f10203

无法再复现

### What is expected?

无

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 无 |
| System | mac |
| Browser | edge |

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/201466316-f9f5cb3a-b087-4009-b4fc-9438adaa441d.png">
我这里没问题。
