### ISSUE TITLE
Select inital value is not shown in specific situation

### ISSUE THREAD

**Issue by erikhofer** [ant-design/ant-design#38539]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shy-water-cz9ryj?file=/src/App.js)

### Steps to reproduce

Nothing, the rendered UI already demonstrates the issue.

### What is expected?

The `Select` should display "A" as the initial value like the native `<select>`.

### What is actually happening?

The `Select` appears empty.

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | React 18.2.0 |
| System | Windows 10 |
| Browser | Firefox 106.0.2 |

---
I'm not sure what the actual cause of this behavior is. I encountered this when using `react-hook-form`, hence its inclusion in the reproduction. However, the native HTML `<select>` works as expected, so there seems to be something wrong with antd or my usage of it.

Note that this does not happen when using plain strings as values in the data model. It has something to do with the transformation of the value before passing it to antd, e.g. `<Select {...field} value={field.value.key}>` (Line 69).

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16751#issuecomment-495268151
