### ISSUE TITLE
使用 react18   antd_4.24.0, 菜单闪烁，丢失默认样式

### ISSUE THREAD

**Issue by cxqy** [ant-design/ant-design#38534]
### Reproduction link

[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce

通过点击收缩菜单, 会出现闪烁的现象，并且再次展开之后，原来的展开样式和选中样式都丢失了

### What is expected?

展开和收缩，都保留原来的样式

### What is actually happening?

通过点击收缩菜单, 会出现闪烁的现象，并且再次展开之后，原来的展开样式和选中样式都丢失了
![a.gif](https://upload-images.jianshu.io/upload_images/13213920-b388f4ce4878c691.gif?imageMogr2/auto-orient/strip)

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | ^18.2.0 |
| System | window10 |
| Browser | chrome Version 107.0.5304 |

**Comment by JarvisArt** [comment]
请升级到 v4.24.0 版本，该版本已修复此问题
https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed

**Comment by cxqy** [comment]
hi JarvisArt:
----
https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed
这个例子有问题, 需要展开/收缩需要 在<Sider />中进行, 
![image](https://user-images.githubusercontent.com/50562423/201525306-36015ea4-e449-47b2-96e7-add746e4215a.png)
------
不知道是不是我使用方式不正确的导致的, 我的Layout布局是拆分成组件去写的
![image](https://user-images.githubusercontent.com/50562423/201525391-b2400185-ab59-4b8a-9321-e6e834f83555.png)

**Comment by JarvisArt** [comment]
React18 中使用 createRoot 渲染确实有问题，在解决前可先使用 ReactDOM.render 渲染
