### ISSUE TITLE
Modal.confirm无法适用于ConfigProvider

### ISSUE THREAD

**Issue by moshuchao** [ant-design/ant-design#38549]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-bhabha-zz2tre?file=/src/App.tsx)

### Steps to reproduce

打开重现链接，对比三者

### What is expected?

三者应该一致

### What is actually happening?

Modal.confirm Form 使用的默认validateMessages

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18 |
| System | macos |
| Browser | 谷歌 |

**Comment by afc163** [comment]
这是预期行为，详见：https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux%E3%80%81%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-ConfigProvider-locale/prefixCls-%E9%85%8D%E7%BD%AE%EF%BC%9F

建议用 useModal
