### ISSUE TITLE
Upload组件在受控状态时, 同时上传多个文件, onChange里的fileList内容不正确

### ISSUE THREAD

**Issue by jaykou25** [ant-design/ant-design#38545]
### Reproduction link

[https://github.com/jaykou25/antd-upload-bug-reproduce](https://github.com/jaykou25/antd-upload-bug-reproduce)

### Steps to reproduce

1. clone仓库, yarn install, yarn dev.
2. 选择至少三个文件同时上传.
3. 文件列表的状态显示不正确.

### What is expected?

onChange中的fileList内容正确.

### What is actually happening?

文件已经全部上传成功了, 但是最后一次的onChange中的fileList不正确, 有部分的status还是uploading, 但实际已经是done了.

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18.0.0 |
| System | windows10 |
| Browser | chrome 107.0.5304.107 |

---
👉只有当上传接口返回很快的时候才能复现. 所以在复现仓库中用了本地mock!

![image](https://user-images.githubusercontent.com/86033222/201583391-3b45e46d-fc8f-4f7c-a5c6-f3bb9092e370.png)

**Comment by Wxh16144** [comment]
下载了你提供的仓库，并且顺利复现了。我去尝试看看能不能解决。

**Comment by luotongzhou** [comment]
这个问题我也遇到过，mark一下

**Comment by kunkkaliu** [comment]
flushSync(() => {
			onChange(newFileList);
		});

**Comment by kunkkaliu** [comment]
《只有当上传接口返回很快的时候才能复现. 所以在复现仓库中用了本地mock!》是因为react 18中对于在时间间隔较短的不同事件里面的状态更新进行了批量处理。

**Comment by jaykou25** [comment]
> 《只有当上传接口返回很快的时候才能复现. 所以在复现仓库中用了本地mock!》是因为react 18中对于在时间间隔较短的不同事件里面的状态更新进行了批量处理。

恩, 确实是这样, 我试了react v17就没有这样的问题. 

源码中已经针对react 18的这一特性进行了修复, 但是只修复了非受控的情形. 对于受控模式, 可以在onChange里也用`flushSync处理`

```js
  <Upload
      action="/api/upload"
      multiple
      fileList={fileList}
      onChange={(info) => {
        flushSync(() => setFileList(info.fileList));
      }}
    >
    <Button>上传</Button>
  </Upload>
```

但是我感觉受控模式下组件也可以对onChange进行flushSync处理, 这样就不需要用户自已去处理了.  我想提一个pr @Wxh16144 

跟这个[pr](https://github.com/ant-design/ant-design/pull/36968)类似的

**Comment by xindoucha** [comment]
mark !  遇到了同样的问题。用了 flushSync 还是有问题

**Comment by xindoucha** [comment]
mark

**Comment by lingkedu** [comment]
Upload组件在受控状态时, 同时上传多个文件, onChange里的fileList内容不正确，同时上传多个，但是fileList里面只会返回我最后一个
![image](https://github.com/ant-design/ant-design/assets/55617889/0dd7b57d-fc0d-4e99-a6ef-63cfb1921f96)，
![image](https://github.com/ant-design/ant-design/assets/55617889/8f12913e-6f75-4b1e-9f07-123b3b52d833)，
