### ISSUE TITLE
Tree with line style

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3854]
![image](https://cloud.githubusercontent.com/assets/507615/20297744/f418f8a6-ab4c-11e6-91c6-081cfeddcec9.png)

**Comment by edutrul** [comment]
I am trying to accomplish the same "Tree with icons" any updates on how to do this ?
![tree_with_icons](https://cloud.githubusercontent.com/assets/1582129/20325737/e6712bae-ab53-11e6-9988-6c49ddda6909.png)

**Comment by benjycui** [comment]
@edutrul maybe you can override style to do so?

**Comment by plandem** [comment]
i tried few times (maybe spent not enough time), but had few glitches every time.

**Comment by ddcat1115** [comment]
@warmhug 目前 rc-tree 的 showline 好像有点问题：

http://react-component.github.io/tree/examples/contextmenu.html

`span.rc-tree-switcher` 的 center_x / bottom_x，还有 `ul.rc-tree-line` 的设置貌似不太对

**Comment by warmhug** [comment]
@ddcat1115 先加上 checkable 属性，当时做的时候和这个绑定了，随后要分离下。

**Comment by ddcat1115** [comment]
目前 checkable 的 rc-tree 对是否是 `bottom` 的认定方式也和顶部的设计不一样：

- rc-tree：一个ul中的最后一项 `rc-tree-switcher` 才是 bottom
- 设计：一个ul中，若这一项后面没有可展开的项了，它的 `rc-tree-switcher` 就是bottom，后面不会有连接线

@warmhug 看下是否rc-tree这里的认定方式需要修改下？或者设计修改下？

**Comment by warmhug** [comment]
rc-tree 的线条设计和这里一样 http://www.treejs.cn/v3/demo.php#_101 我觉得没问题

**Comment by warmhug** [comment]
不显示 icon 时是这样子，叶子节点前的线条还是要有的、不然感觉也缺少点什么。设计上考虑改下吧
![image](https://cloud.githubusercontent.com/assets/2011119/20876985/ab2f38b2-bb00-11e6-9593-117b5d8996f6.png)

**Comment by ddcat1115** [comment]
如果叶子节点也要连起来，建议叶子节点也带icon，设计中『基本样式』里面看起来是没有的，『带icon的样式』里貌似又有。。。

**Comment by warmhug** [comment]
叶子节点也带icon，这个考虑下在 antd 里包装下吧。现在 rc-tree 和 ztree 不一样的是，设置 showIcon={false} 时，rc-tree 是不渲染 icon 节点；ztree 是还渲染节点，但用样式隐藏掉、而对于叶子节点 icon 不隐藏。自定义 icon 的方式也不一样，rc-tree 自定义 icon 在 TreeNode title 属性里定义，可以在 antd 里对 leaf 节点设置自定义 icon，再设置线条样式即可。

**Comment by warmhug** [comment]
@ddcat1115  showLine 问题已修复，不用再加上 checkable 属性了。示例 http://react-component.github.io/tree/examples/contextmenu.html

另外 antd 的 [tree 或 tree-select](https://github.com/ant-design/ant-design/blob/master/components/tree/style/index.less#L19) 里去掉使用 a 标签 
![image](https://cloud.githubusercontent.com/assets/2011119/20880111/97a518be-bb11-11e6-955c-25af61dc93c7.png)
设置的样式，参考 rc-tree 的新样式设置 https://github.com/react-component/tree/blob/master/assets/index.less#L11  。以后 rc-tree 要去掉 a 标签。

以后 rc-tree / rc-tree-select 的维护主要由 @边柳 来负责（有什么不确定的问题或需要 review 的可以@我）

**Comment by aw6658913** [comment]
样式通过引入rc-tree的assets样式，那请问如下图中的出现子节点旁边的操作是通过什么实现的呢
![image](https://cloud.githubusercontent.com/assets/19485727/23089232/be7ffea6-f5c0-11e6-8ad1-fed5286ca3e4.png)

**Comment by yesmeck** [comment]
@aw6658913 使用问题建议到 StackOverflow 或  SegmentFault 上问。

你的问题可以参考 http://react-component.github.io/tree/examples/basic.html

**Comment by afc163** [comment]
这个有进展么，要不 @benjycui 和 #4932 一起搞掉？

**Comment by ddcat1115** [comment]
额。。。这个之前搞了一半，后来忘记了。。。我这周提交掉吧，跟 @benjycui 那个 issue 的内容区别还是挺大的

不过目前的样式，以及 #4932 里的样式看起来，hover及选中都是添加背景色，这个 issue 确定是要改字体颜色？还是只针对 line style 的树的hover及选中才改字体颜色？

**Comment by thuzhangjw** [comment]
能不能在选择showline是，把叶子节点前的那个图标给去了啊

**Comment by Here21** [comment]
楼上 +1
