### ISSUE TITLE
v5 文档内容展示错位

### ISSUE THREAD

**Issue by kunl** [ant-design/ant-design#38544]
### Reproduction link

[https://next.ant.design/docs/react/migration-v5-cn](https://next.ant.design/docs/react/migration-v5-cn)

### Steps to reproduce

设计规范调整, 主色调整，后面内容错位
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/2870324/201583922-22570f67-c771-4b36-9b4a-a752bb979b21.png">

### What is expected?

内容正常显示

### What is actually happening?

内容错位

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | * |
| System | mac |
| Browser |  chrome 107.0.5304.110 |

**Comment by Wxh16144** [comment]
问题重复了 https://github.com/ant-design/ant-design/issues/38463#issuecomment-1309619375, 有一个专门讨论 v5 新站点的 issue 可以去 #38463  那边补充 :)

**Comment by kunl** [comment]
> 问题重复了 [#38463 (comment)](https://github.com/ant-design/ant-design/issues/38463#issuecomment-1309619375), 有一个专门讨论 v5 新站点的 issue 可以去 #38463 那边补充 :)

多谢，已经提了 pr 了
