### ISSUE TITLE
Add capability for additional confirm buttons on Modal.confirm

### ISSUE THREAD

**Issue by Nemo64** [ant-design/ant-design#38553]
### What problem does this feature solve?

I show the user a dialog when they leave a form that explains that they have unsafed changes. What I want to do is give the user an option to save within that dialog. Like [cancel] [leave] [save and leave].

I also have a situation where process can be canceled and then restarted with a copy of the current information which has a modal like: Do you want to cancel this process? [no] [yes] [yes and copy this one]

These cases can all be solved by a custom modal instead of a Modal.confirm, but the Modal.confirm api is a lot more fitting instead of filling the react component with additional state.

### What does the proposed API look like?

I can think of 2 ways to solve this. 1 Is to extend the `Modal.confirm` api with something like `additionalButtons`.

```js
Modal.confirm({
  additionalButtons: [
    {
      type: "primary",
      children: "save and leave",
      onClick: async () => {await save(); await Router.redirect()}
    }
  ]
})
```

The other (maybe more elegant option) is to build a completely custom modal function, something like this:

```js
Modal.custom({
  buttons: [
    {
      type: "default",
      children: "cancel"
    },
    {
      type: "primary",
      children: "leave",
      actionFn: async () => {await Router.redirect()}
    },
    {
      type: "primary",
      children: "save and leave",
      actionFn: async () => {await save(); await Router.redirect()}
    }
  ]
})
```

**Comment by afc163** [comment]
Please use `<Modal />` for this situation.

**Comment by Nemo64** [comment]
I really dislike using `<Modal \>` for that.  
To get the confirm modal to behave similarly, i need to:

- basically copy https://github.com/ant-design/ant-design/blob/4.24.3/components/modal/ConfirmDialog.tsx
- then copy parts of https://github.com/ant-design/ant-design/blob/4.24.3/components/modal/confirm.tsx
- and maybe use or copy the private action button implementation: https://github.com/ant-design/ant-design/blob/4.24.3/components/_util/ActionButton.tsx

And it also means, a confirm modal takes 5 minutes, a confirm modal with 3 buttons requires writing a small library or just accept that your react component will be a bit of a mess and behave different to other confirm dialogs.
