### ISSUE TITLE
关于Grid布局不能适应的问题

### ISSUE THREAD

**Issue by guoxiangwen** [ant-design/ant-design#3856]
#### 发生问题的环境是：

- antd 版本:2.3.0
- 操作系统及其版本:Mac
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

使用Row Col对表单布局:
![image](https://cloud.githubusercontent.com/assets/7627191/20298142/2e5c3d32-ab4f-11e6-82c2-f46449efa373.png)
在win10台式机显示正确，在Mac上布局错乱了，如图:

#### 您期待的结果是:

正常布局

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/7627191/20298174/53dff094-ab4f-11e6-99e7-5566755da56c.png)

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
其实你需要调整一下 RangePicker 的宽度。

`Form[inline]` 就是直接平铺，控件的宽度是不管的，但是你又限制了 `Form.Item` 的宽度，所以 RangePicker 就掉下来了。
