### ISSUE TITLE
【TreeSelect】在showSearch的时候输入关键字icon会自动切换，且删除关键字后会自动触发loadData

### ISSUE THREAD

**Issue by CraiGZero** [ant-design/ant-design#38566]
### Reproduction link

[https://stackblitz.com/edit/react-nlgupj?file=demo.tsx](https://stackblitz.com/edit/react-nlgupj?file=demo.tsx)

### Steps to reproduce

- TreeSelect打开showSearch
- filterTreeNode设置为false
- 在输入框输入任意关键字（此时树节点的状态由可展开变为不可展开）
- 删除输入框内关键字（此时会自动触发loadData）

### What is expected?

- 在输入框输入任意关键字后，icon不应该由可展开变为不可展开，而应该保持原本的状态
- 清除关键字后也不应该自动触发loadData

### What is actually happening?

- 输入任意关键字后，本来有两项可展开的树节点全部变成不可展开
- 清除关键字以后触发loadData也会导致数据重复加载

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18.2.0 |
| System | mac |
| Browser | 107.0.5304.110（正式版本） (arm64) |

**Comment by zombieJ** [comment]
搜索态默认会展开内容，对大树会导致查询堵塞网络。所以搜索态下没有加载过数据的节点都是不可展开态。这个是预期的。

但是，清楚关键字后触发 loadData 应该是 bug。

**Comment by edc-hui** [comment]
我来修复此问题

**Comment by CraiGZero** [comment]
非常感谢
