### ISSUE TITLE
[space] The value attribute is not rendered correctly

### ISSUE THREAD

**Issue by c0dedance** [ant-design/ant-design#38561]
### Reproduction link

[https://stackblitz.com/edit/react-ljnrhf-dydgrz?file=demo.tsx](https://stackblitz.com/edit/react-ljnrhf-dydgrz?file=demo.tsx)

### Steps to reproduce

设置<Space wrap value={[0,8]}>

### What is expected?

![image](https://user-images.githubusercontent.com/38075730/201800437-f2a96667-6575-4415-b0e7-5cfaa12263dd.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/38075730/201801130-2368ab1c-97ec-4e8c-a99b-259c5f6e2c85.png)

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18.2 |
| System | win10 |
| Browser | Chrome 07.0.5304.107（正式版本） （64 位） |

---

input: [8,0] -> columnGap,rowGap -> gap: 0 8px ( /* row-gap column-gap */ )

**Comment by afc163** [comment]
value => size
