### ISSUE TITLE
这样的幻灯片功能能实现吗

### ISSUE THREAD

**Issue by heromen** [ant-design/ant-design#3857]
![image 3](https://cloud.githubusercontent.com/assets/16732697/20299350/8ab15896-ab55-11e6-9c9c-32cc5e0397e1.png)
请问一下，现在有没有组件能够实现这样的一个幻灯片功能，点击小图后可以加载大图，同时可以左右滑动

**Comment by afc163** [comment]
https://ant.design/components/carousel/

https://github.com/akiran/react-slick
