### ISSUE TITLE
官网切换组件，打开特别慢

### ISSUE THREAD

**Issue by GODOFZHZ** [ant-design/ant-design#38587]
### Reproduction link

[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce

打开 切换 其他组件

### What is expected?

快速切换  快速呈现

### What is actually happening?

乌龟一样慢  拉了！！   

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18 |
| System | mac |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25661
https://github.com/ant-design/ant-design/issues/19191
