### ISSUE TITLE
[BUG] Space.Compact 包裹单个 child 样式问题

### ISSUE THREAD

**Issue by luotongzhou** [ant-design/ant-design#38590]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2fujbw)

### Steps to reproduce

仓库是官方例子，删掉<Space.Compact>包裹的其他子组件留一下一个

### What is expected?

Space.Compact 包裹单个子组件时子组件的 border 样式正常显示

### What is actually happening?

Space.Compact 包裹单个子组件时子组件的 border 为 0

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 17 |
| System | mac os 12.4 |
| Browser | Chrome  107.0.5304.87 |

---
Space.Compact 的样式似乎会影响所有后代组件，比如 <Popover content={<Input />}><Button /></Popover>, popover content 里如果有 button, input, border的样式也会收到影响，这取决于Popover包裹的子组件在Space.Compact里的位置

**Comment by foryuki** [comment]
> Space.Compact 的样式似乎会影响所有后代组件，比如 <Popover content={}>, popover content 里如果有 button, input, border的样式也会收到影响，这取决于Popover包裹的子组件在Space.Compact里的位置

该问题已提 PR 。

> 期望：Space.Compact 包裹单个子组件时子组件的 border 样式正常显示

该场景在跟进中~

**Comment by foryuki** [comment]
@luotongzhou 只有一个子组件时不建议使用 Space.Compact 。能说说你的使用场景嘛？

**Comment by luotongzhou** [comment]
@foryuki  很常见的场景，表单里面，Space.Compact包裹的组件数目是动态的，根据另外一个表单项的值动态改变，恰好某个值可选项只有一个

**Comment by foryuki** [comment]
> @foryuki 很常见的场景，表单里面，Space.Compact包裹的组件数目是动态的，根据另外一个表单项的值动态改变，恰好某个值可选项只有一个

好嘞~马上支持

**Comment by luotongzhou** [comment]
这个改动会同步到5.x吗

**Comment by foryuki** [comment]
> 这个改动会同步到5.x吗

会先在 V5 改动，紧接着在 V4-stable
