### ISSUE TITLE
Carousel在flex布局的盒子中出现异常问题

### ISSUE THREAD

**Issue by debugksir** [ant-design/ant-design#38592]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nv7ii2)

### Steps to reproduce

可直接查看

### What is expected?

样式正常，Carousel组件正常工作

### What is actually happening?

样式错误，Carousel组件无法正常工作

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10902#issuecomment-396934693
