### ISSUE TITLE
antd 2.0+ 使用table组件的时候会提示This is a no-op. Please check the code for the Table component.

### ISSUE THREAD

**Issue by favers** [ant-design/ant-design#3859]
#### 发生问题的环境是：

- antd 版本: 2.0.0以上
- 操作系统及其版本:mac os 10.11.6
- 浏览器及其版本:chrome 54.0.2840.71 (64-bit)
- node版本: 7.0.0
#### 您做了什么？请提供尽可能详细的重现步骤。

使用table组件是多切换几次路由之后就会报一个Warning如图
![image](https://cloud.githubusercontent.com/assets/19677784/20300828/dcfd4faa-ab5b-11e6-92c5-875579a82d93.png)

```
warning.js?8a56:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Table component.
```

错误定位在table.js
```js
this.timer = setTimeout(function () {
      _this6.setState({
        fixedColumnsHeadRowsHeight: fixedColumnsHeadRowsHeight,
        fixedColumnsBodyRowsHeight: fixedColumnsBodyRowsHeight
      });
    });
```
但是进去看了一下在componentWillUnmount的时候清除了定时器
```
componentWillUnmount: function componentWillUnmount() {
    clearTimeout(this.timer);
    if (this.resizeEvent) {
      this.resizeEvent.remove();
    }
  }
```

#### 您期待的结果是:
没有Warning的报错，暂时为止没发现有什么影响功能的地方，之前用的是2.0.1版本就有这个错误了，今天我升级成了2.4.2错误依然存在，我记得我之前用0.12.x的时候没有遇到这样的提示

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by favers** [comment]
我也很想提供演示地址，但是codepen并没有提供react-router，不能写router跳转，这边的问题单个表格不会报错，第一次进表格也不会报错，但是在多个表格之间多次切换，就会出现，我能确定我这边业务逻辑中没有写定时器之类的代码，而且错误指向是table.js，我就在浏览器上看了一下table.js 错误定位的地方是有清除过定时器的。

**Comment by benjycui** [comment]
CodePen 是可以通过 CDN 引入 react-router 的，你看下 Setting 里面。

再怎么不济，也可以提供重现 repo 吧？

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by favers** [comment]
谢谢提醒，CodePen用的比较少不是很熟悉，刚刚写一个单纯的在页面内模拟数据的repo，然后切换router没有报错，因为项目还用了redux， 而且项目中部分table之间切换也是没有问题的，但是有几个地方切换报Warning很频繁，报错位置在table，但是单纯的写一了一个demo确实是不报错的，这问题我只能自己定位，找到原因了之后，再联系你们，麻烦了。谢谢各位。

**Comment by favers** [comment]
@afc163 @benjycui 这个Warning是rc-table中报的，我看了一下源码，[syncFixedTableRowHeight](https://github.com/react-component/table/blob/master/src/Table.jsx#L571)这个函数中的设置setState为什么要在[timer](https://github.com/react-component/table/blob/master/src/Table.jsx#L587)中去设置呢,有什么特殊的作用吗？我把定时器去掉，Warning就不会再提示，我想知道在这里这样写的目的是为了什么

**Comment by benjycui** [comment]
`timer` 问题要不要统一用 [`react-timer-mixn`](https://github.com/reactjs/react-timer-mixin) 或类似的东西去处理。

**Comment by favers** [comment]
我这边业务逻辑中没有使用到timer的地方，我只是昨天看rc-table看到这个timer 不太明白这个timer在这里有什么特殊的用途，或者说是为了处理什么而写的

**Comment by afc163** [comment]
setTimeout 之前可能是需要解决某些浏览器的兼容性问题，

我刚才在 Firefox 和 IE9 都测试了一下，貌似去掉也没问题，我先去掉吧。有问题再看看怎么改。

---

另外，componentWillUmount 中清除了定时器，理论上也应该不会报这个错，苦于不能重现。

**Comment by afc163** [comment]
reinstall antd 即可。

**Comment by favers** [comment]
@afc163 好的 非常感谢 我也看到了componentWillUmount中清除了定时器，我写了几次demo复现，都没有成功。

**Comment by yesmeck** [comment]
这里用 timer 会报错，应该是因为 setState 也是异步的原因， componentWillUmount  中调用 clearTimeout 的时候 setState 已经被放到队列里了，所以当 state 真正更新的时候，Table 其实已经  unmount 掉了。

这个错误其实我之前好像也碰到过，不过是偶尔出现又重现不出来就没在意。
