### ISSUE TITLE
RangePicker 如果使用open属性，手动控制日期选择面板的显示和隐藏会出现闪烁的问题

### ISSUE THREAD

**Issue by zyanfly** [ant-design/ant-design#38600]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cftxmj?file=/index.js)

### Steps to reproduce

聚焦时间选择器后，选择时间

### What is expected?

选择时不会闪烁

### What is actually happening?

选择日期时，面板出现闪烁

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18.3 |
| System | macOs |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ek5cwb
