### ISSUE TITLE
Divider 作为特定容器直接 child 样式异常

### ISSUE THREAD

**Issue by magicdawn** [ant-design/ant-design#38606]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lrpugd?file=/index.js)

### Steps to reproduce

样式异常

### What is expected?

样式正常

### What is actually happening?

样式异常

![image](https://user-images.githubusercontent.com/4067115/202201263-7e1b0983-9b41-4c96-ba3d-c4973d8f4835.png)

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18.2.0 |
| System | macos 12.6.1 |
| Browser | chrome 107.0.5304.110 |

---

Divider 如果有一个 display-flex, flex-direction=column, 并且设置了高度的父元素, 此时 Divider 两根线没居中了.
中间加一层空 div 又正常.

**Comment by afc163** [comment]
好像没什么好办法能修。。
