### ISSUE TITLE
Tabs component allow danger prop on its item (Tab)

### ISSUE THREAD

**Issue by dsmalikips** [ant-design/ant-design#38601]
### What problem does this feature solve?

It would be really good to have an prop attribute "danger" for items within <Tabs/> component

### What does the proposed API look like?

`<Tabs
    items={[
        {
            key: "tab1",
            label: <span>Tab1</span>,
            children: <div>Hello</div>,
            **danger: true**
         },
        {
            key: "tab2",
            label: <span>Tab2</span>,
            children: <div>Hello</div>,
         },
        {
            key: "tab3",
            label: <span>Tab3</span>,
            children: <div>Hello</div>,
            **danger: true**
         },
    ]}
/>
`

![antd-danger-tabs](https://user-images.githubusercontent.com/115991249/202143303-d735c0f1-9020-498a-8f79-81964baa99a0.png)

Example created using css

**Comment by afc163** [comment]
It is a weired design pattern, I prefer not to do it.

**Comment by dsmalikips** [comment]
hmm, why is that weired design pattern supported on menu items?

![image](https://user-images.githubusercontent.com/115991249/202646654-5e4a8486-7e4b-4a97-af10-543c3f365e53.png)

**Comment by dsmalikips** [comment]
@afc163 not answer?
