### ISSUE TITLE
InputTable

### ISSUE THREAD

**Issue by 6747377** [ant-design/ant-design#38607]
![20210115103413952](https://user-images.githubusercontent.com/118369951/202212170-286aa504-9fcf-48e0-adc0-345a3fc7b54e.png)
### What problem does this feature solve?

输入框支持展示Table表格,支持翻页,多属性展示

### What does the proposed API look like?

placeholder	String		输入框未填值展示提示信息
disabled	Boolean		true/false 默认false
value	String		绑定v-model或是v-decorator后不需要设置
columns	Array		表格列的配置描述，详见https://www.antdv.com/components/table-cn/#Column
url	string		table 数据源请求地址 查询需返回带分页的数据，
sorter	Object		排序字段及排序方式 { column: this.sorter, order: ‘desc’ }
saveLabel	string		选中实际保存字段
showLabel	string		选中输入框展示字段
queryParams	string		queryParams 额外参数如：部门人员、类型等 后台逻辑需自己书写
pageSize	string		指定每页显示条数
rowKey	string		指定rowKey 默认id 没有id时指定
scroll	string		设置显示Table高度限制，超出指定高度 滚动展示

**Comment by afc163** [comment]
这不是 antd 的职责范畴，建议自行业务封装。
