### ISSUE TITLE
TreeSelect树选择组件希望提供默认搜索功能

### ISSUE THREAD

**Issue by yobuke** [ant-design/ant-design#3860]
#### 发生问题的环境是：

- antd 版本:    "antd": "^1.10.0",
- 操作系统及其版本: Win7 X64
- 浏览器及其版本:Chrome  52.0.2743.116 m

#### 您做了什么？请提供尽可能详细的重现步骤。

TreeSelect树选择组件希望提供默认搜索功能，
比如有一个属性 searchValue=‘服务满意度’ ，TreeSelect就会筛选node中包含‘服务满意度’的node。
当‘服务满意度’ 改为 ‘服务满意度’，触发筛选。

#### 您期待的结果是:

TreeSelect树选择组件希望提供默认搜索功能，
比如有一个属性 searchValue=‘服务满意度’ ，TreeSelect就会筛选node中包含‘服务满意度’的node。
当‘服务满意度’ 改为 ‘服务满意度’，触发筛选。

![image](https://cloud.githubusercontent.com/assets/3202232/20302902/eb45d372-ab63-11e6-8e52-8752b3b4c966.png)

#### 实际上的结果是:

![1](https://cloud.githubusercontent.com/assets/3202232/20302916/fd28a36c-ab63-11e6-86f6-56bb04b42a90.png)

**Comment by afc163** [comment]
暂无精力提供，建议使用 https://ant.design/components/tree/#components-tree-demo-search 自行封装。

**Comment by warmhug** [comment]
TreeSelect 不是有搜索功能吗 @yobuke
