### ISSUE TITLE
Modal: support Modal.open to invoke modal like Component's styles

### ISSUE THREAD

**Issue by arlendp** [ant-design/ant-design#38614]
### What problem does this feature solve?

When i use `Modal.method()` like `info` and `confirm`, it has specific styles different from `Modal` components in title and footer, what i want is `Modal.open` method to trigger modal with the same styles like `Modal` components.

![image](https://user-images.githubusercontent.com/9403654/202345903-13e9c2f7-13cb-49e7-8166-544361b2b93c.png)

### What does the proposed API look like?

We can add `Modal.open` method to solve this by using
```javascript
Modal.open({
    title: 'This is a modal message',
    content: (
      <div>
        <p>You can use Modal.open to invoke modal with same styles like Modal Component</p>
      </div>
    ),
});
```
this is the default behavior, and it's compatible with other methods like `info` as below
```javascript
Modal.open({
    type: 'info',
    title: 'This is a notification message',
    content: (
      <div>
        <p>some messages...some messages...</p>
        <p>some messages...some messages...</p>
      </div>
    ),
    onOk() {},
});
```
please visit the PR [https://github.com/ant-design/ant-design/pull/38609](https://github.com/ant-design/ant-design/pull/38609) for more detail.

**Comment by afc163** [comment]
Please use Modal instead of `Model.open`, we don't provide `Modal.open` usage in our documentation.
