### ISSUE TITLE
[v5] Menu 缩起内嵌菜单，图标不居中

### ISSUE THREAD

**Issue by l1xnan** [ant-design/ant-design#38612]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dmooi2)

### Steps to reproduce

antd v5.0.0-rc.1 版本 Menu 收缩内嵌菜单

### What is expected?

Menu 内嵌菜单收缩后图标居中

### What is actually happening?

图标不居中
![image](https://user-images.githubusercontent.com/6105390/202340308-8077bef6-e937-46be-9c0d-c014a31a61b9.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.0-rc.1 |
| React | React 18 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by afc163** [comment]
确实有问题。

---

<img width="349" alt="图片" src="https://user-images.githubusercontent.com/507615/202342526-ae94a387-b4e6-4ed4-b6e3-9c6fe4e3df99.png">

codesandbox 里这个 Menu 顶部也少 padding。和 https://next.ant.design/components/menu-cn#components-menu-demo-inline-collapsed 表现不一致，也需要看看。 @MadCcc

**Comment by JarvisArt** [comment]
我来修复下
