### ISSUE TITLE
Safari: Disabled Input value changes color when suffix/prefix applied

### ISSUE THREAD

**Issue by edvrie** [ant-design/ant-design#38627]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/prefix-and-suffix-antd-4-24-2-forked-w9uemy?file=/demo.tsx)

### Steps to reproduce

If you have an input with a set value, adding suffix/prefix makes the value color change

### What is expected?

Input value does not change color when suffix is applied

### What is actually happening?

Input changes color when suffix is applied

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18.0.0 |
| System | iOS |
| Browser | Safari  |

---
First encountered with Form.Item hasFeedback. Removing disabled and adding it again makes the input value change colors twice. Chrome and Firefox seem to work as expected.

**Comment by afc163** [comment]
Great catch!

<img width="579" alt="图片" src="https://user-images.githubusercontent.com/507615/202407634-37bd97c9-88a1-4eff-a14b-1aab1cd2ab9a.png">

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/39830
