### ISSUE TITLE
Tabs使用prefixCls属性导致来回切换不生效

### ISSUE THREAD

**Issue by fangyinghua** [ant-design/ant-design#38620]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-o1zyir?file=/index.js)

### Steps to reproduce

只是自定义样式

### What is expected?

切换内容卡片生效

### What is actually happening?

第一次切换成功，后面切换内容并未切换

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 17.0.2 |
| System | windows |
| Browser | 谷歌 |

**Comment by afc163** [comment]
prefixCls 改掉要配合修改 less 里的 antPrefixCls 变量，否则相当于没引用样式。

**Comment by fangyinghua** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
