### ISSUE TITLE
npm install warning

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3862]
<img width="1019" alt="image" src="https://cloud.githubusercontent.com/assets/507615/20335708/a6d1d83e-abff-11e6-98fc-96e1bca1e0c4.png">

**Comment by watonyweng** [comment]
@afc163 需要在package.json文件中peerDependencies

**Comment by AlbertZheng** [comment]
遇到同样问题。另外，npm3不会自动安装插件包所依赖的peerDependencies包，这意味着每个重新编译antd的用户都回遇到这个问题。看看能否在bisheng-plugin-antd这个项目里在源头解决下这个问题?

**Comment by benjycui** [comment]
如果只是上面两个 peerDependencies 的问题的话，最新的 bisheng-plugin-antd 已经没问题了。

@AlbertZheng 普通用户在安装 antd 时，不会安装 antd devDependencies 下面依赖的吧。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/c3064949cccfce4e4d14ff6d1876d1217dd04888/package.json#L93

这里也要升上来？

**Comment by AlbertZheng** [comment]
@benjycui  如果只是使用antd库的普通用户，是不会报这些警告和安装antd devDependencies 下面依赖的。
