### ISSUE TITLE
文档布局

### ISSUE THREAD

**Issue by wkylin** [ant-design/ant-design#38636]
### Reproduction link

[https://next.ant.design/docs/spec/illustration-cn](https://next.ant.design/docs/spec/illustration-cn)

### Steps to reproduce

https://next.ant.design/docs/spec/illustration-cn

### What is expected?

https://next.ant.design/docs/spec/illustration-cn

### What is actually happening?

https://next.ant.design/docs/spec/illustration-cn

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
@zombieJ 看看，这一块的样式应该都失效了。

**Comment by afc163** [comment]
这个得修。

**Comment by afc163** [comment]
<img width="159" alt="图片" src="https://user-images.githubusercontent.com/507615/202600472-be853757-1eda-4b92-9c01-5d5975723a0f.png">

这个可以先简单点解，给 `.markdown img[align="right"] { ... }` 加上 v4 官网的样式。

<img width="730" alt="图片" src="https://user-images.githubusercontent.com/507615/202600636-456c6a0c-6430-45c3-a52e-914d926315e3.png">
