### ISSUE TITLE
Modal对话框里面加入table默认是黑色

### ISSUE THREAD

**Issue by qdleader** [ant-design/ant-design#38634]
### Reproduction link

[https://ant.design/components/modal-cn/#components-modal-demo-width](https://ant.design/components/modal-cn/#components-modal-demo-width)

### Steps to reproduce

里面加一个table，展示默认是黑色

### What is expected?

期望是白色

### What is actually happening?

是黑色

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by qdleader** [comment]
https://github.com/HalseySpicy/Hooks-Admin.git

**Comment by afc163** [comment]
Need a minimal reproduce, try https://u.ant.design/codesandbox-repro
