### ISSUE TITLE
Form.Item装多个getFieldDecorator包装的child。

### ISSUE THREAD

**Issue by anlia260** [ant-design/ant-design#3864]
![image](https://cloud.githubusercontent.com/assets/11311553/20336913/aaace3fa-ac08-11e6-85f3-4383323bc5b4.png)
![image](https://cloud.githubusercontent.com/assets/11311553/20336933/cf43229c-ac08-11e6-96ca-06970363e527.png)
我想在Form.Item下面装两个child，能否给一个demo，文档不是很明白。谢谢了。
试过Form.Item里面嵌套Form.Item，虽然可以解决问题，但是不够优雅。

**Comment by infeng** [comment]
可以参考 https://ant.design/components/form/#components-form-demo-validate-static 最后一个选择日期的做法

**Comment by anlia260** [comment]
看到了，的确可以解决但是还是嵌套啊。文档说的是建议包装一个element，但是没有说必须（可能有些钻牛角尖）。但是还是其他更优雅的写法

**Comment by anlia260** [comment]
看到了，的确可以解决但是还是嵌套啊。文档说的是建议包装一个element，但是没有说必须（可能有些钻牛角尖）。但是还是其他更优雅的写法，谢谢@infeng

**Comment by anlia260** [comment]
看到了，的确可以解决但是还是嵌套啊。文档说的是建议包装一个element，但是没有说必须（可能有些钻牛角尖）。但是还是希望有其他更优雅的写法，谢谢@infeng

**Comment by anlia260** [comment]
看到了，的确可以解决但是还是嵌套啊。文档说的是建议包装一个element，但是没有说必须（可能有些钻牛角尖）。但是还是希望有其他更优雅的写法，谢谢@infeng

**Comment by xiongran** [comment]
我是封装了一个组件实现的。https://github.com/ant-design/ant-design/issues/3866

**Comment by benjycui** [comment]
楼上的方案是靠谱的 👍
