### ISSUE TITLE
Corrupted primary button default style in a dropdown menu

### ISSUE THREAD

**Issue by acailly** [ant-design/ant-design#38655]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-pfl7yr?file=/index.js)

### Steps to reproduce

add a modal in a dropdown menu

### What is expected?

only `ant-btn ant-btn-primary` styles are applied to a primary button in the footer

### What is actually happening?

`ant-btn ant-btn-primary ant-btn-lg ant-btn-compact-item ant-btn-compact-last-item` styles are applied to a primary button in the footer

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox 106.0.3 (64-bit) |

**Comment by afc163** [comment]
@foryuki

**Comment by foryuki** [comment]
正在处理中，主要是 Space.Compact context 未做阻断。
