### ISSUE TITLE
reset.css 里可以把默认字体和行高加上

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#38656]
https://unpkg.com/antd@5.0.0-rc.2/dist/reset.css

https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js:141-160

不然用户还得自己去取字体变量或者拷贝到应用样式文件里。

**Comment by zombieJ** [comment]
这个不行，字体是 token 的一部分。特地去掉的。

**Comment by afc163** [comment]
不过 `font-family: sans-serif;` 貌似在大多数系统里看着也没啥问题。
