### ISSUE TITLE
ant design5.0 组合输入框的按钮和输入框边框不对齐

### ISSUE THREAD

**Issue by onewink** [ant-design/ant-design#38659]
### Reproduction link

[https://next.ant.design/components/input-cn](https://next.ant.design/components/input-cn)

### Steps to reproduce

1. 进入 https://next.ant.design/components/input-cn
2. 在搜索框介绍里面，大型的组合输入框的按钮与输入框边框没有对齐
![image](https://user-images.githubusercontent.com/30338668/202519666-2cc91c79-fb94-481b-b256-96cd5c044c3b.png)

### What is expected?

应该按钮与输入框应该边框对齐

Ant Design4.0 是对齐的
![image](https://user-images.githubusercontent.com/30338668/202520000-07ea1e6f-f8cb-4598-81ca-45d20fdae3b4.png)

Ant Design5.0 没对齐
![image](https://user-images.githubusercontent.com/30338668/202519776-df5244ba-0414-4347-9398-7a6d3d83b3a8.png)

### What is actually happening?

Ant Design5.0 组合输入框，按钮与输入框边框没有对齐

| Environment | Info |
| --- | --- |
| antd | 5.0 |
| React | xxx |
| System | xxx |
| Browser | edge |

**Comment by onewink** [comment]
可能需要放大点才能看出来~

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/88bc0f644aa40869066e13f658a23a3f7250db45/components/input/style/index.tsx#L856

这里算出来是 7px，4.x 上是 6.5px。
