### ISSUE TITLE
搜狗浏览器高速模式不能打开官网的modal和drawer例子

### ISSUE THREAD

**Issue by mwj610** [ant-design/ant-design#38661]
### Reproduction link

[https://ant-design.antgroup.com/components/drawer-cn/](https://ant-design.antgroup.com/components/drawer-cn/)

### Steps to reproduce

在搜狗浏览器中打开antd官网modal或者drawer

### What is expected?

modal或者drawer可以打开

### What is actually happening?

modal或者drawer不能打开

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 18.0.1 |
| System | windows 11 |
| Browser | 搜狗浏览器  11.0.1.34700 |

**Comment by afc163** [comment]
建议使用 Chrome。
