### ISSUE TITLE
v5 hashPrefix reasoning and not configurable

### ISSUE THREAD

**Issue by StuartMorris0** [ant-design/ant-design#38660]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-haze-k5pfmb?file=/src/App.js)

### Steps to reproduce

This issue is for version 5, although not possible to select.
"antd": "5.0.0-rc.2",

### What is expected?

No hashPrefix is needed

### What is actually happening?

A hashPrefix is used for all elements. This causes for larger dom as the className is long. For example, a button renders this additional classname. 
ant-btn css-dev-only-do-not-override-w9vaau ant-btn-primary

There is no need to include the 'css-dev-only-do-not-override' multiple and multiple times throughout the DOM. 

What is the reasoning for using a hashPrefix? With a styled-components approach you can directly target elements as needed and styled-components adds a unique id to each element, so it doesn't make much sense why one is included? 

This is also not able to be switched off currently.

```
var hashPrefix =  true ? 'css-dev-only-do-not-override' : undefined;
```

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 18 |
| System | 5 |
| Browser | 5 |

---
There are comments for the hashPrefix such as:
// Generate different prefix to make user selector break in production env.
// This helps developer not to do style override directly on the hash id.

Not sure what the use for this is without any documentation?

**Comment by sebastiangseijo** [comment]
Any fix for this situation?

**Comment by MadCcc** [comment]
Hash is generated by version and tokens, and is important for local style. We have reduced hash class in components, though it is still needed once at least in single component.

**Comment by StuartMorris0** [comment]
Could you elaborate on why it's needed please? Any example of this? 

Also will there be any functionality to change it

**Comment by abenhamdine** [comment]
This prefix `css-dev-only-do-not-override-` is renamed `css-` in the production build.
It's just a warning for the developer to prevent relying on this className to target an element.

**Comment by StuartMorris0** [comment]
So on every component you add an non optional additional css tag just as a warning to not use the class name?
No option to not include that for dev and prod. Right?

**Comment by MadCcc** [comment]
Ref: https://ant.design/docs/blog/css-in-js

**Comment by zaneadix** [comment]
This hash is breaking all of my snapshot tests. It changes on every single run. Using 5.0.2

**Comment by abenhamdine** [comment]
> This hash is breaking all of my snapshot tests. It changes on every single run. Using 5.0.2

It' shouldn't change if the token and antd version are the same.
A simple way to test this : if your code hasn't been changed, the hashes generated should be the sames.

**Comment by zaneadix** [comment]
> It' shouldn't change if the token and antd version are the same.
> A simple way to test this : if your code hasn't been changed, the hashes generated should be the sames.

Not sure what you mean by token, but I'm changing nothing. Also just restarted my computer and the hash changed again on a new test run. No files were changed.

**Comment by abenhamdine** [comment]
> Also just restarted my computer and the hash changed again on a new test run. No files were changed.  

Therefore it's a bug I think, it's supposed to be stable.

**Comment by sebastiangseijo** [comment]
> > It' shouldn't change if the token and antd version are the same.
> > A simple way to test this : if your code hasn't been changed, the hashes generated should be the sames.
> 
> Not sure what you mean by token, but I'm changing nothing. Also just restarted my computer and the hash changed again on a new test run. No files were changed.

no reason to be commenting in here, they will tell you everything is fine, that's a correct release and that is stable too.

**Comment by abenhamdine** [comment]
>> Also just restarted my computer and the hash changed again on a new test run. No files were changed.

>Therefore it's a bug I think, it's supposed to be stable

hash should be stable in next release, see https://github.com/ant-design/ant-design/pull/39069

**Comment by zaneadix** [comment]
Awesome thank you @abenhamdine. I've upgraded and things are working as expected.
