### ISSUE TITLE
antd Dropdown    Menu   Input   InputNumber 光标不可被键盘控制问题, 鼠标的行为不符合预期

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design#38663]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-forest-tf2dzf?file=/menu.jsx)

### Steps to reproduce

 1. 点击按钮后打开下拉框, 出现 Menu 菜单
2. 在 Input输入框中输入 串 dddddddd,  然后使用键盘 左右移动, 发现不能移动
3. 在 InputNumber 中点击上下箭头可以增减数字, 但 使用键盘 上下, 发现是移动 MenuItem 的上下选中, 而不是增减数字

### What is expected?

 1. 点击按钮后打开下拉框, 出现 Menu 菜单
2. 在 Input输入框中输入 串 dddddddd,  然后使用键盘 左右移动, 发现不能移动
3. 在 InputNumber 中点击上下箭头可以增减数字, 但 使用键盘 上下, 发现是移动 MenuItem 的上下选中, 而不是增减数字

### What is actually happening?

输入框保持自己的行为

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/festive-tamas-xlek93?file=/menu.jsx

**Comment by soulcm** [comment]
我也遇到了，这是什么原因，为什么要   `onKeyDown={(e) => e.stopPropagation()}`，阻止冒泡下
