### ISSUE TITLE
Mention组件的onSelect回调方法，强烈建议增加回调项

### ISSUE THREAD

**Issue by ThinkCats** [ant-design/ant-design#3867]
当前的onSelect(suggestion: String),只有一个回调项，是string类型的。目前有这么一个需求，我自定义的Mention数据（类似[自定义数据例子](https://ant.design/components/mention/#components-mention-demo-custom-tag)）：
```
const webFrameworks = [
  { name: 'React', type: 'JavaScript' },
  { name: 'Angular', type: 'JavaScript' },
  { name: 'Laravel', type: 'PHP', disabled: true },
  { name: 'Flask', type: 'Python' },
  { name: 'Django', type: 'Python' },
];
```
我选择展示name的话，onselect只能回调出name值，但是我需要的是type数据。通过这个回调是拿不到这个值得。这个mention组件应该像select那样，option有值value，也有展示的label值。

#### 发生问题的环境是：

- antd 版本: 2.1
- 操作系统及其版本: macos
- 浏览器及其版本:  chrome 54

**Comment by RaoHai** [comment]
重新安装一下依赖。在 Nav 上把数据当作 props 传进去。

```jsx
const suggestions = filtered.map(suggestion =>
      <Nav value={suggestion.name} data={suggestion}>
        <span>{suggestion.name} - {suggestion.type} </span>
      </Nav>);
```

这样做就可以拿到了：

```javascript
function onSelect(suggestion, data) {
  console.log('onSelect', suggestion, data);
}
```

其实原本就支持的。更新了下文档。

**Comment by ThinkCats** [comment]
@RaoHai 感谢万分，解决了一大难题，困扰了好一会儿
