### ISSUE TITLE
Cascader 懒加载，回显有问题

### ISSUE THREAD

**Issue by stupidZhu** [ant-design/ant-design#38679]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/dong-tai-jia-zai-xuan-xiang-antd-4-24-2-forked-wq5jjy?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

给懒加载的 Cascader 设置 `defaultValue={["zhejiang", "dynamic1"]}`

### What is expected?

回填 `Zhejiang / Zhejiang Dynamic 1`

### What is actually happening?

回填为 `Zhejiang / dynamic1`

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18.2.0 |
| System | win10 |
| Browser | Microsoft Edge 版本 107.0.1418.42 (正式版本) (64 位) |

---
通过 defaultValue 可以知道 dynamic1 上一级为 zhejiang，是否可以自动加载 zhejiang 子节点并更新显示？

**Comment by afc163** [comment]
`loadData` 是在点击一级菜单时才会触发的，所以你对这个 API 的理解可能有误。

**Comment by stupidZhu** [comment]
> `loadData` 是在手动点击一级菜单时才会触发的，所以你对这个 API 的理解可能有误。

但是在使用到懒加载并且编辑表单的时候，Cascader 会回显 key 的值而不是 label。而且例子中 defaultValue 已知 dynamic1 上一级为 zhejiang，能否自动 loadData 获取 zhejiang 的子节点？或者通过其他的方式使其正常展示 label？

**Comment by qiutian00** [comment]
> 
遇到相同问题， 回显显示的是key值

**Comment by qiutian00** [comment]
用`displayRender`, 回填用中文字段显示，设置表单字段还是keys。要修改重新选行政区划

**Comment by zscgxs** [comment]
> 用`displayRender`, 回填用中文字段显示，设置表单字段还是keys。要修改重新选行政区划

displayRender 回填好像也有问题，三级的在点击一个回填的第一级时后面的两级会显示成key

**Comment by ratelgogo** [comment]
+1,也是行政区域选择，没有什么好的思路

**Comment by DFive5** [comment]
还没解决这个问题呢?
