### ISSUE TITLE
官网样式变量链接404

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design#38673]
### Reproduction link

[https://ant-design.antgroup.com/docs/react/customize-theme-cn](https://ant-design.antgroup.com/docs/react/customize-theme-cn)

### Steps to reproduce

点击所有样式变量的链接访问https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

### What is expected?

可以访问

### What is actually happening?

无法访问

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by IceLeach** [comment]
似乎是5.0发布后地址变更了？

**Comment by zombieJ** [comment]
嗯，官网还在切换中。稍等哈~

**Comment by afc163** [comment]
4.x 的站点也确实要改改。

**Comment by zombieJ** [comment]
Updated~

https://github.com/ant-design/ant-design/commit/90a5a9f58393d1ba90f7118e99e70b165f503643
