### ISSUE TITLE
Date picker is laggy

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#38686]
### Reproduction link

[https://ant.design/components/date-picker](https://ant.design/components/date-picker)

### Steps to reproduce

Click on any date picker, especially the range picker there is a huge lag in the dropdown

### What is expected?

should be smooth like v4

### What is actually happening?

animation lag

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | web |
| Browser | chrome |

**Comment by zombieJ** [comment]
Thanks for feedback. Could you help provide a screen record about this?

**Comment by MatrixAge** [comment]
+1 TimePicker的Popover有明显弹出延迟。

**Comment by AsuraKev** [comment]
It looks like only the date picker example in the documentation is having animation lag on the popover. In the code pen it seems smooth, maybe its multiple datepicker instances on the doc that causes it? Same with the Menu, on initial collapse it lags and its fine after

**Comment by afc163** [comment]
Try 5.0.1

**Comment by MatrixAge** [comment]
> Try 5.0.1

https://ant.design/~demos/components-date-picker-demo-range-picker
https://ant.design/~demos/components-time-picker-demo-basic

Macos Ventura 13.0.1 (22A400)
Chrome 版本 107.0.5304.110（正式版本） (x86_64)

点击大约0.5s的延迟弹出，点击页面其他处，组件失焦，弹层会抖动一下，然后消失（新窗口打开上述example依然如此）。

**Comment by zjfresh** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/28496323/203463288-159130a7-4dd0-4f72-bb65-100b2e56860a.png">

![image](https://user-images.githubusercontent.com/28496323/203463363-794c8599-0073-4437-b9b0-8bc548a472c0.png)

**Comment by afc163** [comment]
比起 4.x 确实慢半拍：https://4x-ant-design.antgroup.com/components/date-picker-cn/
