### ISSUE TITLE
官网代码预览左右滚动code区域有竖线

### ISSUE THREAD

**Issue by luke358** [ant-design/ant-design#38680]
### Reproduction link

[https://ant.design/components/auto-complete-cn](https://ant.design/components/auto-complete-cn)

### Steps to reproduce

随便一个点击查看代码，左右滚动

### What is expected?

不出现竖线

### What is actually happening?

竖线和滚动条一起滚动

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 官网demo |
| System | macpro2020 |
| Browser | Chrome 107.0.5304.110 |

**Comment by afc163** [comment]
<img width="750" alt="图片" src="https://user-images.githubusercontent.com/507615/202663706-e2e071a8-afbb-4983-95d8-56b5db6b9511.png">

**Comment by luke358** [comment]
👍🏻
