### ISSUE TITLE
官网发现一个bug

### ISSUE THREAD

**Issue by cuitengf** [ant-design/ant-design#38682]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

datepiker 失去焦点后，会闪现几下

https://user-images.githubusercontent.com/38001280/202657801-032975ed-7863-45be-a6d8-dc85f25c0859.mp4

### What is expected?

修改闪现

### What is actually happening?

datepiker 失去焦点后，会闪现几下

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 官网demo |
| System | macOS 13.0.1 |
| Browser | safari 16.1 |

**Comment by cuitengf** [comment]
https://user-images.githubusercontent.com/38001280/202659631-e4b0ae6a-0954-432d-b77e-9c0f5255c3bf.mp4

补充：
1. 好像弹出类的都会复现
2. Chrome 未发现。

**Comment by Wxw-Gu** [comment]
我这正常

**Comment by zhenzhenChange** [comment]
![不情愿](https://user-images.githubusercontent.com/51586637/202660645-a35c17ee-c780-48ca-b421-153a3c76738f.gif)

好像它不是很情愿的关闭喔

**Comment by beautiful-boyyy** [comment]
我这边chromium正常，safari有问题

**Comment by yoyo837** [comment]
印象中曾经有个issue, 也是类似这个问题,没找着.

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/38548
