### ISSUE TITLE
拖动 Slider 的滑块时，tooltip 的位置未同步更新

### ISSUE THREAD

**Issue by Visualizeit** [ant-design/ant-design#38685]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jrsjmy?file=/index.js)

### Steps to reproduce

拖动 Slider 的滑块，观察 tooltip 的显示位置

https://user-images.githubusercontent.com/61679509/202662332-fdef2066-11c1-4ce4-b4fa-5b8d4785068e.mp4

### What is expected?

拖动 Slider 的滑块，tooltip 的位置与 Slider 的滑块同步

### What is actually happening?

拖动 Slider 的滑块，tooltip 的位置延迟了约1秒才与滑块同步

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | macos 13.0.1  |
| Browser | Chrome Version 107.0.5304.110 |

---
在官网的 Slider 文档页面也可重现此bug：https://ant.design/components/slider-cn

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/38492
