### ISSUE TITLE
DatePicker组件中英文显示不准确

### ISSUE THREAD

**Issue by Design-duke** [ant-design/ant-design#38692]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

点击日期选择框年份是中文的，月份却是英文的显示，中英文切换没有切换月份，但是官网的月份显示是正确的，刚刚npm下载的包不行

### What is expected?

显示中文月份，像官网那样

### What is actually happening?

月份显示的是英文，和官网显示不一致

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | win11 |
| Browser | 谷歌 |

**Comment by chuangwei** [comment]
@Design-duke  需要import dayjs语言包
import 'dayjs/locale/zh-cn';

**Comment by lixiaojian** [comment]
官网也是年份中文，月份英文

**Comment by lixiaojian** [comment]
使用 npm ls dayjs  看了一下 dayjs 的版本列表 如下 
`
├─┬ @ant-design/pro-components@2.3.34
│ ├─┬ @ant-design/pro-field@2.1.22
│ │ └── dayjs@1.11.6 deduped
│ ├─┬ @ant-design/pro-list@2.0.31
│ │ └── dayjs@1.11.6 deduped
│ ├─┬ @ant-design/pro-table@3.1.8
│ │ └── dayjs@1.11.6 deduped
│ ├─┬ @ant-design/pro-utils@2.3.5
│ │ └── dayjs@1.11.6 deduped
│ └─┬ antd@5.0.0
│   ├── dayjs@1.11.6 deduped
│   └─┬ rc-picker@3.0.0-4
│     └── dayjs@1.11.5
└─┬ ahooks@3.7.2
  └── dayjs@1.11.6

`

发现 有一个 dayjs 是 1.11.5 的版本，它是在 @ant-design/pro-components 中依赖的， 去 rc-picker 的 package.json 里看了下  他写的版本依赖是  "dayjs": "1.x",  并没有写死版本 ，然后就把 @ant-design/pro-components 删除重新安装一下，再看  npm ls dayjs    
`
├─┬ @ant-design/pro-components@2.3.34
│ ├─┬ @ant-design/pro-field@2.1.22
│ │ └── dayjs@1.11.6 deduped
│ ├─┬ @ant-design/pro-list@2.0.31
│ │ └── dayjs@1.11.6 deduped
│ ├─┬ @ant-design/pro-table@3.1.8
│ │ └── dayjs@1.11.6 deduped
│ └─┬ @ant-design/pro-utils@2.3.5
│   └── dayjs@1.11.6 deduped
├─┬ ahooks@3.7.2
│ └── dayjs@1.11.6
└─┬ antd@5.0.0
  ├── dayjs@1.11.6 deduped
  └─┬ rc-picker@3.0.0-4
    └── dayjs@1.11.6 deduped

`
dayjs 的版本都是 1.11.6了 ， 再回去看页面效果月份变中文了

**Comment by wkl007** [comment]
有同样的问题

**Comment by lixiaojian** [comment]
@afc163 @zombieJ   我发现这个问题很神奇呀，时好时坏，我去官网看 https://ant.design/components/date-picker-cn  和 https://ant-design.gitee.io/components/date-picker-cn  刚进去年份、月份、星期都是中文，刷新一下页面，月份和星期就变英文了。

**Comment by kingstone3** [comment]
打包的问题吧，我暂时这么解决的：
`<ConfigProvider
      locale={zhCN?.default ?? zhCN}`

**Comment by wkl007** [comment]
> 打包的问题吧，我暂时这么解决的： `<ConfigProvider locale={zhCN?.default ?? zhCN}`

有效，非常感谢

**Comment by afc163** [comment]
@wkl007 这不一定是合理的解决方式，最好还是给一个重现看看 antd 本身有没有问题。

**Comment by wkl007** [comment]
@afc163 我看这个有 pr 修复了 https://github.com/ant-design/ant-design/pull/39055/files

**Comment by wkl007** [comment]
@afc163 先参考这个处理吧，上面这个 pr 方案有待斟酌。https://github.com/ant-design/ant-design/issues/39045#issuecomment-1328472538

**Comment by chenyu1990** [comment]
遇到了同样的问题

**Comment by lexmin0412** [comment]
Same issue in project built with rspack.

**Comment by qiutian00** [comment]
在前端构建后，出现同样问题 antd v5
