### ISSUE TITLE
定制主题 属性不全

### ISSUE THREAD

**Issue by randomtc** [ant-design/ant-design#38691]
### Reproduction link

[https://ant.design/docs/react/customize-theme-v5-cn#seedtoken](https://ant.design/docs/react/customize-theme-v5-cn#seedtoken)

### Steps to reproduce

使用theme修改属性  个别属性提示不存在 例如 radiusBase

### What is expected?

改变样式（举例：圆角改变）

### What is actually happening?

提示没有 该属性  
SeedToken文档 api中存在该属性（）

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | react 18.2.0 |
| System | windows |
| Browser | chrom |

---
不只圆角这一个 应该是文档和实际api未同步

**Comment by afc163** [comment]
确实没同步。@MadCcc 看看

**Comment by zombieJ** [comment]
感谢反馈，这个之后会做成自动收集的。

**Comment by QC2168** [comment]
我想直接使用暗黑主题，没有找到相关配置

**Comment by QC2168** [comment]
找到了在定制主题里的基本算法
