### ISSUE TITLE
antd 5 动态黑暗主题与 next.js 不兼容

### ISSUE THREAD

**Issue by dujiajun** [ant-design/ant-design#38709]
### Reproduction link

[https://github.com/dujiajun/antd-bug-report](https://github.com/dujiajun/antd-bug-report)

### Steps to reproduce

1. 使用 yarn dev 运行，浏览器访问 http://localhost:3000 ，显示浅色样式。
2. Windows 切换到深色模式，再切换到浏览器，显示深色样式。（此时看似正常）
3. 保持系统为深色，刷新浏览器，此时显示回浅色样式。
4. 如果第1步时，系统为深色，也会显示浅色样式。

如果代码中的isDark ? theme.darkAlgorithm : theme.defaultAlgorithm 改成 isDark ? theme.defaultAlgorithm: theme.darkAlgorithm，那么效果相反，仍然有问题。

### What is expected?

第一次加载时就能正确根据主题算法生成正确的颜色。

### What is actually happening?

第一次加载时未正确生成颜色。

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | Windows 11 |
| Browser | Edge 107 |

---
注意到使用 umi 框架无此问题，猜测可能和 ssr 有关。

注意到部分控件正确显示颜色，而 Layout 和 Card 没有。

**Comment by chunsch** [comment]
ssr 情况下，服务端无法知道客户端主题，`isDark` 会是 `false`，可以参考 [next-themes 文档提的如何避免这种情况](https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch)。

**Comment by dujiajun** [comment]
感谢回复，参考这个文档解决了。

**Comment by hemengke1997** [comment]
返回null的话直接影响SEO了，请问有什么解决方案吗
