### ISSUE TITLE
Migration  V4 to V5 page is Not Found

### ISSUE THREAD

**Issue by DercilioFontes** [ant-design/ant-design#38701]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/5.0.0/docs/react/migration-v5](https://github.com/ant-design/ant-design/blob/5.0.0/docs/react/migration-v5)

### Steps to reproduce

The link is Page not found

### What is expected?

Access to the migration page

### What is actually happening?

Not Found

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | - |
| System | - |
| Browser | - |

**Comment by afc163** [comment]
https://ant.design/docs/react/migration-v5
