### ISSUE TITLE
Table expand icon shouldn't be on same line with parent expand icon

### ISSUE THREAD

**Issue by sherali-1** [ant-design/ant-design#38713]
### Reproduction link

[https://ant.design/components/table](https://ant.design/components/table)

### Steps to reproduce

Just click expand icon and you can see that nested expand icon is on same line with parent. 

### What is expected?

should be nested like a tree views

### What is actually happening?

 nested expand icon is on same line with parent. 

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | react 18 |
| System | Linux |
| Browser | chrome |

**Comment by afc163** [comment]
Which demo?

**Comment by LuciNyan** [comment]
![image](https://user-images.githubusercontent.com/22126563/202742965-afa5bb05-12ce-4b9e-a403-dd99af3f2aeb.png)
->
![image](https://user-images.githubusercontent.com/22126563/202743047-2ec83e08-7df0-4f16-91f0-de36a6d72111.png)

**Comment by sherali-1** [comment]
@LuciNyan yeah, this is the demo for issue. thank you.

Children's expand icon shouldn't be same line with parent's icon.

**Comment by sherali-1** [comment]
@afc163 okay let me try to fix this issue myself
