### ISSUE TITLE
Proper documentation for new dynamic theme capabilities

### ISSUE THREAD

**Issue by fitterfizzle** [ant-design/ant-design#38712]
### Reproduction link

[https://ant.design/](https://ant.design/)

### Steps to reproduce

Currently there is no proper documentation how to integrate the new theme capabilities

### What is expected?

A good documentation so that the toolbox of the ant homepage can be implemented.

![image](https://user-images.githubusercontent.com/96863959/202740901-1ea340c3-b627-4fc5-ac46-94980723a983.png)

### What is actually happening?

Very hard to understand the whole new concept with algorithms, seeds, tokens

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 17 |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment]
See https://ant.design/docs/react/customize-theme-v5
