### ISSUE TITLE
TreeSelect替换数据数据操作状态无重置

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#3871]
- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本: chrom

#### 您做了什么？请提供尽可能详细的重现步骤。

引入TreeSelect组件，给出两组数据分别为treeData，treeData2，都默认设置下拉全部展开，默认下拉数据为treeData，先把treeData下拉数据第一个选择项缩起来，然后将下拉数据切换成treeData2，这时候第一个选择项还是缩起来，并重置为设置的默认全部展开

#### 您期待的结果是:

替换下拉数据之后要重置之前下拉数据的操作状态

#### 实际上的结果是:

下拉状态依然是上一组数据的状态

#### 可重现的在线演示

http://codepen.io/anon/pen/mOrMpa?editors=001

**Comment by warmhug** [comment]
你只是替换了 treeData，treeData 变化已经显示到树上，表现正常。但并没有设置也没有改变 value ，组件就不是受控的，所以内部会有状态。

**Comment by aw6658913** [comment]
那请问下如果我要重置状态要如何整呢？因为我treeData下拉数据是异步的，treeData整个也是变化的，当treeData整个数据变化时候刚操作的状态还在，但是箭头还是往下掉，这都点奇怪

**Comment by warmhug** [comment]
设置 value ，让组件受控

**Comment by aw6658913** [comment]
不好意思 不是很能明白您的意思，能给个简单的 demo吗？

**Comment by aw6658913** [comment]
@warmhug 弄个demo太麻烦的话或者直接在我的在线演示改下，可以么？

**Comment by aw6658913** [comment]
@warmhug 我设置了value好像也不行

**Comment by ohmyauthentic** [comment]
@aw6658913 怎么才能更新treeData 值呢，设置了state 更新，可是界面没有反应
