### ISSUE TITLE
Some component's type definitions do not include displayName

### ISSUE THREAD

**Issue by dev-nicolaos** [ant-design/ant-design#38719]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9bq62p?file=/index.tsx)

### Steps to reproduce

1. In an Ant project with TypeScript installed, create a new _.tsx_ file containing

```ts
import React from "react";
import { Form, Menu, Select, Space, Table, Tabs, version } from "antd";

const MyComponent: React.FC = (props) => <div>Hello World</div>;

MyComponent.displayName = "Foo";

Space.displayName = "Bar";

Form.displayName = "Baz";
Form.Item.displayName = "Form.Item";
Menu.displayName = "Lorem";
Select.displayName = "Ipsum";
Table.displayName = "dolor";
Tabs.displayName = "sit";
```

2. View the results of type checking the file, either by running `tsc` from the command line or viewing the file in an editor with TypeScript support, such as VS Code.

3. Observe that no type error is thrown when setting `displayName` on `MyComponent` or `Space`

4. Observe that a type error is thrown when setting `displayName` on...
    - `Form`
    - `Form.Item`
    - `Menu`*
    - `Select`
    - `Table`
    - `Tabs`

*: This issue appears to have been resolved for Menu in v5 of Ant, but it is still a bug in the 4.x branch

### What is expected?

No type errors are thrown, as setting `displayName` is a valid operation on any React component

### What is actually happening?

Type errors are being thrown when trying to set `displayName` on a number of components

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | Tested on v17.0.2 and v18.2.0 |
| System | Tested on Windows and Mac |
| Browser | NA |

**Comment by afc163** [comment]
Is it https://github.com/opbeat/babel-plugin-add-react-displayname useful?

**Comment by dev-nicolaos** [comment]
I don't think so. We don't use babel as part of our build process and even if we did, that seems more like a workaround than an actual fix.

**Comment by zombieJ** [comment]
Since we do not have plan to enable developer override these `displayName` self. We will only handle the issue that dev mode missing the official `displayName`. TS extension def will not provide.

**Comment by dev-nicolaos** [comment]
@zombieJ thanks for responding to this issue. Two questions:

- Is there a reason the types will be left inaccurate? `displayName` is a valid property on these components, and React provides helper types such as `React.FC` so that developer's don't have to manually specify properties like `displayName` and `props.children` for every component.
- Is there a ticket where we can track the work to correct the `displayName`s in dev mode?
