### ISSUE TITLE
table 合并列样式错误（最后一行缺少border）

### ISSUE THREAD

**Issue by ratelgogo** [ant-design/ant-design#38724]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-5-0-0-forked-roxl90)

### Steps to reproduce

合并列必现

### What is expected?

border-bottom可以正常设置

### What is actually happening?

缺少了border

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | mac |
| Browser | chorme107 |

**Comment by ratelgogo** [comment]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/23555154/202834028-8503ce64-85f1-4db0-9221-cd497504568d.png">

**Comment by afc163** [comment]
<img width="1382" alt="图片" src="https://user-images.githubusercontent.com/507615/202955880-7f25ccea-5aa9-4a74-bab8-abf7e9f85801.png">

好像没发现有问题。

**Comment by ratelgogo** [comment]
@afc163 要把最下面一行去掉，我之前给的demo忘记删了，重新看下demo

**Comment by afc163** [comment]
> @afc163 要把最下面一行去掉，我之前给的demo忘记删了，重新看下demo

最下面一行具体是？

**Comment by ratelgogo** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/23555154/203027255-7fc14ed8-fa25-470e-9807-ffedd2a9047d.png">
要把Jake White 这行数据删掉

**Comment by afc163** [comment]
- 4.x https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-4-x-forked-zlwzpg?file=/demo.tsx
- 5.x https://codesandbox.io/s/biao-ge-xing-lie-he-bing-antd-5-0-0-forked-q5hzlc?file=/package.json

4.x 里是 border-bottom，5.x 里变成 border-top 了。

<img width="284" alt="图片" src="https://user-images.githubusercontent.com/507615/208602870-04552a6e-2521-420c-8f24-e5e33dfe1211.png">
