### ISSUE TITLE
bundle size increased a lot with v5

### ISSUE THREAD

**Issue by mzaien** [ant-design/ant-design#38720]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/38671#issuecomment-1320572845](https://github.com/ant-design/ant-design/issues/38671#issuecomment-1320572845)

### Steps to reproduce

upgrade to ant design v5 then build react project 

### What is expected?

bundle size would be much smaller after dropping `moment.js`

### What is actually happening?

it increased by 55kb 

![Screenshot 1444-04-25 at 1 08 20 AM](https://user-images.githubusercontent.com/43112535/202812085-d87b6225-50b4-408a-b853-9316189deb13.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | CRA/ react 18.2.0 |
| System | macos 16.0.1 |
| Browser | brave |

**Comment by Dunqing** [comment]
Because `rc-picker` still supports `moment.js`, but `antd` uses `dayjs`, bundler does not contains `moment.js`.

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/29533304/202834118-853d42f2-b72a-4cea-a827-d14158196ea0.png">

**Comment by Dunqing** [comment]
And cssinjs bundles styles in js, so main.css is reduced, but main.js is increased.

**Comment by Dunqing** [comment]
The Antd team will soon optimize the size of the styles generated in cssinjs to reduce the size of js

**Comment by afc163** [comment]
css bundle size moved to js bundle size.

**Comment by tbswork1** [comment]
with v5.21.6 project build size increases by 100Kb compared to 4.23.2.
