### ISSUE TITLE
The color of <a>/Typography.Link elements don't respect colorPrimary design token

### ISSUE THREAD

**Issue by ddadaal** [ant-design/ant-design#38728]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-p0z928?file=/index.js)

### Steps to reproduce

Wrap an `<a>` or `<Typography.Link>` element with ConfigProvider and specify a different `colorPrimary` design token.

### What is expected?

The color of the a element is the new `colorPrimary`, just like other elements like `Button`.

### What is actually happening?

The color of the a element is still `#1677ff`, the new default color of antd v5.

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | Arch Linux |
| Browser | Edge/Chrome/Firefox |

**Comment by Dunqing** [comment]
`Typography.Link` should respect colorPrimary design token, but `a` not.

**Comment by ddadaal** [comment]
Why shouldn't? antd already adds styles to `<a>` elements (like color, transition etc). I think antd should either provide no styles to `<a>` elements at all, or manage its style like other elements.

**Comment by Dunqing** [comment]
>  I think antd should either provide no styles to <a> elements at all, or manage its style like other elements.

Yes, i agree with you. I thought that in v5 because of the use of cssinjs so will not add style to the `<a>`

**Comment by Dunqing** [comment]
Look like `Typography.Link` use `colorInfo` token
![image](https://user-images.githubusercontent.com/29533304/202838290-e18db263-aee4-4b75-8ba3-704806dac895.png)

**Comment by ddadaal** [comment]
If it is not possible to make `<a>` respect design tokens, it is better to remove `<a>`'s global styles completely to avoid confusion.

**Comment by afc163** [comment]
Typography.Link use `colorInfo` token. Global styles pollution has been removed since 5.0. https://github.com/ant-design/ant-design/issues/9363

**Comment by ddadaal** [comment]
It seems global styles still exist in 5.0
