### ISSUE TITLE
Slider style problem

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3872]
<img width="504" alt="image" src="https://cloud.githubusercontent.com/assets/507615/20347086/71d972a0-ac3a-11e6-8490-b3ebc61002a4.png">

marks 应该占据空间，方便正常的排版，否则会遮挡其他元素（例如校验信息）的位置。

**Comment by benjycui** [comment]
给 `Slider[marks]` 统一加了 `margin-bottom`，能处理常见情况了。。

`marks` 的定位是用 `position: absolute` 做的，目前也没想到更好的方案。
