### ISSUE TITLE
<Button hidden>Should be Hidden</Button> is not hidden

### ISSUE THREAD

**Issue by vojkog** [ant-design/ant-design#38732]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cvyhff)

### Steps to reproduce

 <Button hidden>Should be Hidden</Button>

### What is expected?

 <Button hidden>Should be Hidden</Button> should not be visible.

### What is actually happening?

 <Button hidden>Should be Hidden</Button> is visible.

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 17.x 18.x |
| System | windows |
| Browser | Chrome Version 107.0.5304.107 (Official Build) (64-bit) |

---
Notice that when `// import "antd/dist/reset.css"` is uncommented Button is hidden as expected.

The example from the original documentation template also does not work: [codesandbox](https://codesandbox.io/s/type-antd-5-0-0-forked-zdlqtk?file=/demo.tsx:108-149)
(Here, `reset.css` is not included)

**Comment by 13632632437** [comment]
![image](https://user-images.githubusercontent.com/73922151/202842195-777b8cd2-4f4d-4dd1-aa66-39f117eb59f9.png)
Where is hidden？

**Comment by vojkog** [comment]
It is inherited:
[image: image.png]

**Comment by yoyo837** [comment]
Are you referring to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden?

**Comment by vojkog** [comment]
> Are you referring to https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden?

Yes.

![image](https://user-images.githubusercontent.com/3501456/202843798-272a4cdb-d7ba-4ba7-9dac-1914ab3fd6ab.png)

**Comment by vojkog** [comment]
... just for clarification, in version <5.0  `hidden` attribute was working as expected.

**Comment by TrickyPi** [comment]
Bug here.
![image](https://user-images.githubusercontent.com/33021497/203255265-66386867-6e1b-4cc0-82fc-a9ccb86f076d.png)
the `css-in-js` style override `hidden` style.

**Comment by afc163** [comment]
Try import 'antd/dist/reset.css' mannually.

**Comment by mrlubos** [comment]
Thanks @afc163, importing the CSS reset fixes this. I think this should be mentioned more explicitly in the [migration guide](https://ant.design/docs/react/migration-v5) though
