### ISSUE TITLE
antd@4.18.1中 Calendar 内渲染 datepicker 后无法切换月份年份

### ISSUE THREAD

**Issue by udbbbn** [ant-design/ant-design#38731]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-4-18-1-calendar-nei-qian-datepicker-chong-fu-xuan-ran-forked-iysnt4)

### Steps to reproduce

1. DatePicker 选择任意一个日期
2. 再次点击 DatePicker 顶部切换年份月份 切换失败

### What is expected?

能正确切换月份

### What is actually happening?

组件重复渲染导致切换失败。
似乎是Calendar组件重复渲染， 即使是给了 Key 也不解决问题。

| Environment | Info |
| --- | --- |
| antd | 4.18.1 |
| React | 17.0.1 |
| System | win10家庭版 21H2 |
| Browser | Chrome 版本 107.0.5304.107（正式版本） （64 位） |

**Comment by afc163** [comment]
感觉和 Calendar 的 Context 冲突了。

**Comment by edc-hui** [comment]
我来修复此问题

**Comment by edc-hui** [comment]
@afc163 @yoyo837 可以帮忙看下这个PR  github ci 未通过是什么原因么？

**Comment by afc163** [comment]
https://codecov.io/gh/react-component/picker/pull/535/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=react-component#diff-dGVzdHMvdXRpbC9jb21tb25VdGlsLnRzeA==

覆盖率掉了

**Comment by edc-hui** [comment]
> https://codecov.io/gh/react-component/picker/pull/535/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=react-component#diff-dGVzdHMvdXRpbC9jb21tb25VdGlsLnRzeA==
> 
> 覆盖率掉了

好的，那这个应该就是我写的测试用例有问题，对么？

**Comment by zombieJ** [comment]
根据 @edc-hui 的 [PR](https://github.com/react-component/picker/pull/535/files#diff-f58dff739e69c7dfdb061e97561f25702ad26366affb9f5e983ab17772f2a140R339) 又看了一下。这个传入 obj 重置内部状态是符合预期的，你这边每次传入一个新的 moment 对象，都会被认为是需要受控改变这个值。如果没有变化可以 memo or 直接用返回的值即可：
https://codesandbox.io/s/antd-4-18-1-calendar-nei-qian-datepicker-chong-fu-xuan-ran-forked-71tj3k?file=/demo.tsx
