### ISSUE TITLE
document.title show undefined in dependent demo

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#38736]
https://ant.design/~demos/components-button-demo-basic

<img width="297" alt="图片" src="https://user-images.githubusercontent.com/507615/202846378-820dc074-7edc-4ecd-a700-a12da73637b2.png">

**Comment by afc163** [comment]
现在 title 变成 404 了。

**Comment by afc163** [comment]
<img width="761" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/2d6d364c-0c43-4262-a845-79269c5ce2c9">

**Comment by PeachScript** [comment]
@MadCcc alpha.6 部署过了么
