### ISSUE TITLE
Enable Table Filtering on Tree Data

### ISSUE THREAD

**Issue by jonioni** [ant-design/ant-design#38730]
### What problem does this feature solve?

Currently table filter `onFilter` only runs on top-level rows instead of nested rows.

Also mentioned in #3728 but slightly different. The filter should be able to filter out non-matching nested rows.

### What does the proposed API look like?

`onFilter` runs on all rows (or can be optionally turned on by a filter mode setting).

**Comment by afc163** [comment]
Duplicate of #37972
