### ISSUE TITLE
:where Selector 带来的兼容性问题（国内普及率只有61%）

### ISSUE THREAD

**Issue by yar2001** [ant-design/ant-design#38752]
### What problem does this feature solve?

在更新 5.0 版本的 Ant Design 后，新的 `css in js` 库生成了含有 `:where()` 的样式。

![Screenshot from 2022-11-19 11-42-56](https://user-images.githubusercontent.com/20311434/202886275-502b5563-5a09-4020-a4ce-e407841c65be.png)

这导致所有不支持 `:where` 的浏览器（Chrome 81 才支持），都无法使用 Ant Design 的所有组件， 根据 [caniuse 提供的数据](https://caniuse.com/mdn-css_selectors_where)，:where 在国内的普及率只有61%，而它只是用于降低 css 优先级。

### What does the proposed API look like?

目前，postcss 没有提供[相关的 polyfill](https://github.com/csstools/postcss-plugins/discussions/509)，希望可以提供降级方案（至少不要让它完全不能用），或者避免使用这个 css 特性。

**Comment by li-jia-nan** [comment]
@zombieJ 这个选择器我记得是动态插入的吧？只有当前环境的浏览器支持 where 的时候才会插入吧

**Comment by yar2001** [comment]
我用 Chrome v61 试了下，整个 Ant Design 5.0 官网的组件都用不了。我自己的网站也是这样

**Comment by zombieJ** [comment]
> @zombieJ 这个选择器我记得是动态插入的吧？只有当前环境的浏览器支持 where 的时候才会插入吧

`:where` 是通过配置 hashPriority 来管理的，默认是 where。这个我补一下文档。自动检查会导致一个问题就是相同 css 在不同游览器里优先级不同给用户覆盖造成困难。

**Comment by zombieJ** [comment]
@yar2001 ，嗯，我补一下文档

**Comment by zombieJ** [comment]
@yar2001 可以先参考一下 #38764 里的文档，社区讨论了一下想是否可以更进一步分封装。这个我晚点会写个 RFC 出来。

**Comment by collins401** [comment]
> 我用 Chrome v61 试了下，整个 Ant Design 5.0 官网的组件都用不了。我自己的网站也是这样

我在chrome v70版本试，也是组件样式全乱，不能用。

**Comment by zombieJ** [comment]
@collins401, 参考 #38764 。之后也会提供一个兼容旧版本游览器的 guide。

**Comment by iugo** [comment]
https://caniuse.com/?search=%3Awhere

92% 的可用率.

Chrome 88 开始支持, 发布于 2021 年初.
