### ISSUE TITLE
Can not hide arrow in Dropdown

### ISSUE THREAD

**Issue by goldwind-ting** [ant-design/ant-design#38750]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-chu-yong-fa-fei-qi-de-yu-fa-tang-antd-5-0-0-forked-37806v?file=/demo.tsx)

### Steps to reproduce

run

### What is expected?

hide arrow when config arrow={false}.

### What is actually happening?

Not hide

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | Ubuntu 22.04.1 LTS |
| Browser | chrome Version 107.0.5304.110 (Official Build) (64-bit) |

**Comment by JarvisArt** [comment]
![image](https://user-images.githubusercontent.com/38420763/202862236-20bea135-053a-4795-b30b-9ee1abf2776d.png)

**Comment by goldwind-ting** [comment]
> ![image](https://user-images.githubusercontent.com/38420763/202862236-20bea135-053a-4795-b30b-9ee1abf2776d.png)

Got it, thanks!
