### ISSUE TITLE
Form.List嵌套会刷新已经填好的值为undefined

### ISSUE THREAD

**Issue by twwch** [ant-design/ant-design#38757]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-r1tl2w?file=/index.js)

### Steps to reproduce

使用https://codesandbox.io/s/antd-reproduction-template-forked-r1tl2w?file=/index.js的组建重现

### What is expected?

Form.List嵌套会不刷新已经填好的值

### What is actually happening?

Form.List嵌套会刷新已经填好的值为undefined

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 17.0.52 |
| System | mac |
| Browser | Chrome |

**Comment by afc163** [comment]
你的例子跑不起来。

**Comment by twwch** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-vpvk0p?file=/index.js
可以看这个例子

**Comment by afc163** [comment]
你的例子比较复杂，最好给一下详细的重现步骤，steps by steps 那种。

**Comment by twwch** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/44161003/202897510-43a3fb4e-1f7f-478b-bbcd-95ab4ca736c1.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/44161003/202897531-0f78451d-0f11-4f1f-8de0-86a4f559533d.png">
<img width="463" alt="image" src="https://user-images.githubusercontent.com/44161003/202897588-d45fdd48-7bac-4dca-afbb-a6da71389ad4.png">

**Comment by chunsch** [comment]
@twwch 第 94 行 `name={["containers", "ports"]}` 改成 `name={[field.name, "ports"]}` 试试 : D

**Comment by twwch** [comment]
> @twwch 第 94 行 `name={["containers", "ports"]}` 改成 `name={[field.name, "ports"]}` 试试 : D

多谢指点，确实是这个原因导致的
