### ISSUE TITLE
FloatButton悬浮按钮 Bug

### ISSUE THREAD

**Issue by xiaohuooo** [ant-design/ant-design#38759]
### Reproduction link

[https://ant.design/components/float-button-cn](https://ant.design/components/float-button-cn)

### Steps to reproduce

https://ant.design/components/float-button-cn  菜单模式  点击效果 切换bug

### What is expected?

https://ant.design/components/float-button-cn  菜单模式  点击效果没有bug

### What is actually happening?

https://ant.design/components/float-button-cn  菜单模式  点击效果 切换bug

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | react |
| System | win11 |
| Browser | Microsoft Edge 版本 107.0.1418.52 |

**Comment by xiaohuooo** [comment]
FloatButton悬浮按钮 Menu mode click effect switch bug

**Comment by li-jia-nan** [comment]
我这边用 Edge 浏览器看了一下是正常的，请问具体是什么问题呢？

**Comment by li-jia-nan** [comment]
但是发现了另一个bug，返回顶部有点问题，我来修一下

**Comment by xiaohuooo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 晚上8:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] FloatButton悬浮按钮 Bug (Issue #38759)





 
但是发现了另一个bug，返回顶部有点问题，我来修一下

**Comment by ldt1997** [comment]
> 我这边用 Edge 浏览器看了一下是正常的，请问具体是什么问题呢？

看起来触发后点击叉号 会闪烁一下

**Comment by xiaohuooo** [comment]
对就是那个切换时的闪烁




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月21日(星期一) 上午10:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] FloatButton悬浮按钮 Bug (Issue #38759)





  
我这边用 Edge 浏览器看了一下是正常的，请问具体是什么问题呢？
  
看起来触发后点击叉号 会闪烁一下

**Comment by li-jia-nan** [comment]
> > 我这边用 Edge 浏览器看了一下是正常的，请问具体是什么问题呢？
> 
> 看起来触发后点击叉号 会闪烁一下

已经复现了，我来尝试修一下

**Comment by chzng** [comment]
> 对就是那个切换时的闪烁
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月21日(星期一) 上午10:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ant-design/ant-design] FloatButton悬浮按钮 Bug (Issue #38759) 我这边用 Edge 浏览器看了一下是正常的，请问具体是什么问题呢？ 看起来触发后点击叉号 会闪烁一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

对有闪闪闪，这个bug太明显了

**Comment by chzng** [comment]
> 

对有闪闪闪，这个bug太明显了 哈哈哈哈
