### ISSUE TITLE
Tabs在弹性盒子中使用会撑开盒子，无法出现更多按钮

### ISSUE THREAD

**Issue by liaohongxing** [ant-design/ant-design#38777]
### Reproduction link

https://stackblitz.com/edit/react-x7cjrt?file=demo.tsx

[https://react-x7cjrt.stackblitz.io](https://react-x7cjrt.stackblitz.io)

### Steps to reproduce

多次点击Add按钮

### What is expected?

能和官网的 [自定义新增页签触发器](https://ant.design/components/tabs-cn#components-tabs-demo-custom-add-trigger) 一样 ，当标签页过多时，自动出现更多按钮。代码中去掉弹性盒子包裹 。表现就和官网一样

### What is actually happening?

tabs会撑开div 。并且无法自动出现 ”更多按钮“ 

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | win10 |
| Browser | Firefox107 |

**Comment by afc163** [comment]
<img width="642" alt="图片" src="https://user-images.githubusercontent.com/507615/203026569-8bb8a71b-3095-4831-9af7-8612527ebfe4.png">
