### ISSUE TITLE
DatePicker 2.x版本locale不支持配置firstDayOfWeek了吗？

### ISSUE THREAD

**Issue by zds2015** [ant-design/ant-design#3877]
#### 发生问题的环境是：更新antd 2.x版本后的环境

- antd 版本: 2.x
- 操作系统及其版本: win7
- 浏览器及其版本:  chrome 49

#### 您做了什么？请提供尽可能详细的重现步骤。
今天把antd更新到最新版，发现DatePicker组件的locale不支持配置firstDayOfWeek了（配了没效果）。
以前用antd@1.10.0的时候还可以配置。

#### 您期待的结果是:
我期望的结果是使用DatePicker组件选择时间时，左边第一列是星期天。

#### 实际上的结果是:
现在实际情况是：DatePicker加了时区控制，美国的（en_US）的是从星期天开始，但中国（zh_CN）的是从星期一开始。我想用的是zh_CN，但我希望能从星期天开始。

**Comment by afc163** [comment]
http://stackoverflow.com/a/22754413/3040605

**Comment by zds2015** [comment]
多谢提醒。
moment@2.15.0的配置
moment.defineLocale('zh-cn', {
    week: {
        dow: 7 //set sunday as the first day of week
    }
})
