### ISSUE TITLE
悬浮按钮-返回顶部显示 / 隐藏动画错误

### ISSUE THREAD

**Issue by getatny** [ant-design/ant-design#38778]
### Reproduction link

[https://ant.design/components/float-button-cn](https://ant.design/components/float-button-cn)

### Steps to reproduce

回到顶部 demo，滚动页面没有按预期展示返回顶部的按钮，但是已经可以点击，这时向上滚动，按钮出现，但是点击无效。感觉是 fade 动画 enter 和 leave opacity 值写反了

### What is expected?

向下滚动大于 400px 按钮显示，滚动小于 400px 时按钮隐藏

### What is actually happening?

与预期相反

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | react |
| System | macos13 |
| Browser | chrome 106.0.5249.119 |

**Comment by li-jia-nan** [comment]
- #38769 

已经修复了，晚点会发一版
