### ISSUE TITLE
Input.Group 组合两个含有 addonBefore 的 Input 样式错误

### ISSUE THREAD

**Issue by Lorry1123** [ant-design/ant-design#38780]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-69p4eu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

InputGroup 组合两个有 addonBefore 的 input，border   margin 组合不正确

### What is expected?

margin   border 配合实现正常的 Group compact 效果

### What is actually happening?

第二个 input 的 addonBefore 没有正确的 margin   border，与第一个 input 的本体重叠了

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | windows 10 |
| Browser | chrome 107 |

**Comment by afc163** [comment]
为啥会有这种设计？
