### ISSUE TITLE
Form组件里面如何使用 Google reCAPTCHA?

### ISSUE THREAD

**Issue by soulmachine** [ant-design/ant-design#3878]
这是一个 antd 的用法咨询，由于 StackOverflow 人气是在太少，没人回答，只好在这里重复发了

Stackoverflow 的问题在这里  <http://stackoverflow.com/questions/40644615/how-to-use-google-recaptcha-in-the-ant-design-form-component>

reCAPTCHA 能够拦截普通的 HTML form标签，给 form 加上自己额外的`g-recaptcha-response`的字段，但是
由于`Form`组件比较复杂，貌似拦截不了。

我死活无法获取到 reCAPTCHA 返回的 payload, 不知道哪位大神可以给一个例子？能够做到在 `console.log(payload)`打印出 reCAPTCHA返回的值就可以了

**Comment by yesmeck** [comment]
https://www.google.com.hk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Recaptcha%20react

**Comment by RaoHai** [comment]
```jsx
const RecaptchaItem = React.createClass({
  verifyCallback(result) {
    this.props.onChange(result); // 通知到 form
  },
  render() {
    return (<Recaptcha
      render="explicit"
      sitekey=""
      verifyCallback={this.verifyCallback}
      onloadCallback={this.callback}
    />);
  }
});
```
这样用：
```jsx
{getFieldDecorator('captcha', {
          rules: [{ required: true, message: 'Please input the captcha you got!' }],
        })(<RecaptchaItem />)}
```

**Comment by RaoHai** [comment]
@afc163 要不我们 form 的 demo 上的 Capcha 改用 reCAPTCHA ？

**Comment by afc163** [comment]
可以有，正好演示一下怎么把 rc-form 和第三方表单组件进行配合。

**Comment by benjycui** [comment]
这个 demo ? https://ant.design/components/form/#components-form-demo-register

**Comment by soulmachine** [comment]
@benjycui 对的，如果能把这个验证码换成一个真实的验证码服务，就最好了， Google reCAPTCHA是一个很流行的验证码服务，虽然在国内被墙。。。

**Comment by soulmachine** [comment]
@RaoHai 非常感谢，你的答案看起来非常好，不过我个人水平太菜，貌似还是显示不出来，下图是 react-devtools的截图：
<img width="553" alt="screen shot 2016-11-17 at 3 09 14 am" src="https://cloud.githubusercontent.com/assets/620768/20387110/7451dd0e-ac73-11e6-8752-975f813fd770.png">

**Comment by RaoHai** [comment]
就算用了 react-rechapcha, 页面也要手动引入 `<script src="https://www.google.com/recaptcha/api.js" async defer></script>` 的。

<img width="534" alt="screen shot 2016-11-17 at 8 08 52 pm" src="https://cloud.githubusercontent.com/assets/566097/20388852/b5d5a20e-ad01-11e6-9098-127e23f3431d.png">

**Comment by soulmachine** [comment]
@RaoHai 高手，果然可以了，不过还有个小问题，当我开始在表单上输入用户名，密码的时候，Console 不断地报警:

    recaptcha__zh_cn.js:302 Uncaught Error: ReCAPTCHA placeholder element must be an element or id

同时验证码组件会从网页消失掉

**Comment by RaoHai** [comment]
没出现这个问题。请提供一个可复现的 demo

**Comment by RaoHai** [comment]
http://codepen.io/RaoHai/pen/dOOgPj?editors=0110

**Comment by soulmachine** [comment]
@RaoHai 明白了，我把 `const RecaptchaItem = React.createClass({` 这个声明语句，放在了 `render()`函数里面，而你则放在了类的外面，做成了一个全局变量。

现在代码还有两个个小问题“
1. 即便我勾选了 Google 的那个复选框，提交的时候，还是会报错，说我没有填写captcha，把 required改为false可以绕过这个问题
1. 点击`登录`之后，在console里看到 `captcha`字段是`undefined`, 这个问题比较急切

**Comment by RaoHai** [comment]
可能是组件问题。必须同时指定 onloadCallback 和 verifyCallback , verifyCallback 才能触发。。。

```jsx
<ReactRecaptcha
  render="explicit"
  sitekey="6LdSLAwUAAAAAFBwEUIlvzTxJE8zpRlh9r87eCL5"
  onloadCallback={this.callback}       
  verifyCallback={this.verifyCallback}
/>
```

这个 issue 就到这里吧。。。我的第一次回复之后已经不关 antd 什么事了。

**Comment by soulmachine** [comment]
@RaoHai 试了一下，果然可以了，感谢大神的耐心解答 👍
