### ISSUE TITLE
Layout Sider 宽度最小只能是80

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#38783]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sider-antd-5-0-0-forked-qlelm8)

### Steps to reproduce

当Sider的collapsedWidth设为40时，图标撑开，以前版本无此问题。

### What is expected?

当Sider的collapsedWidth设为40时，像以前版本一样正常就行。

### What is actually happening?

当Sider的collapsedWidth设为40时，图标撑开

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.0.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by afc163** [comment]
以前是什么样的？

**Comment by meseme** [comment]
> 以前是什么样的？
这是以前版本，一切正常
[https://codesandbox.io/s/sider-antd-4-24-3-forked-htp7ir?file=/demo.tsx:1198-1218](url)
