### ISSUE TITLE
360安全浏览器打开文档页面，页面样式混乱

### ISSUE THREAD

**Issue by Mossoul** [ant-design/ant-design#38789]
### Reproduction link

[https://ant.design/components/overview-cn](https://ant.design/components/overview-cn)

### Steps to reproduce

打开连接样式混乱

### What is expected?

修复样式

### What is actually happening?

样式混乱

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.1 |
| System | win10 |
| Browser | 360安全浏览器  版本13.1.6320.0 |

**Comment by MadCcc** [comment]
文档站暂不支持低版本浏览器，ref:https://github.com/ant-design/ant-design/issues/38752
