### ISSUE TITLE
[v5] 有些组件再次包裹了ConfigProvider, 例如Modal.confirm等系列方法，导致丢失了theme，至少应该透传theme

### ISSUE THREAD

**Issue by gaokaifeis** [ant-design/ant-design#38784]
### Reproduction link

[https://stackblitz.com/edit/react-jbcad7?file=demo.tsx](https://stackblitz.com/edit/react-jbcad7?file=demo.tsx)

### Steps to reproduce

定义theme，使用Modal.confirm(也包括其他以这种方式定义的组件)

### What is expected?

Modal.confirm也使用自定义theme

### What is actually happening?

Modal.confirm未使用自定义theme

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 17.0.2 |
| System | macos |
| Browser | chrome |

**Comment by gaokaifeis** [comment]
![image](https://user-images.githubusercontent.com/29112400/202981116-787840a0-df3c-4482-be4a-3e5d796fba5a.png)
通过这种方式应该就可以吧？

**Comment by MadCcc** [comment]
静态方法在 v5 不再推荐了，同时也不支持动态主题。推荐使用 hooks 方案：https://ant-design.antgroup.com/components/modal-cn#modalusemodal

**Comment by zombieJ** [comment]
静态方法不走 context，v4 里做了很多黑科技在用到 ConfigProvider 的地方会把数据存到全局，然后静态方法消费。当存在多个 CP 时，其行为充满随机性。因而在 v5 里不再推荐静态方法，也因此在新的动态主题方案下也不准备去支持。
