### ISSUE TITLE
后端开发人员如何用ant

### ISSUE THREAD

**Issue by doterme** [ant-design/ant-design#3879]
我是一个后端开发人员，对react+webpack+babel这些也了解，我们的项目是asp.net mvc的，暂时没办法做到前后端分离，react+webpack+babel这套也就没法在项目中用起来。我想问我直接引用ant的css和js如何做到可以html+js混合的方式来用。我测试的是只能写js，混合的时候就报错，请给后端开发人员一点建议，谢谢。

**Comment by xiexingen** [comment]
我也遇到同样问题

**Comment by anlia260** [comment]
**你的描述我暂且当你比较熟练（react+webpack+babel）** 
如果不会自行补习。你能明白react是可以把所有的js+css+html都集合成JSX/JS Component，然而ant就是现成的component，你直接拿来用。
比如你需要做一个列表页，很好。你就直接拿table的组件组成你需要的列表页。
（这点你要会单独的（react）前端调试开发）ant有脚手架工具，看得清文档就OK。
最后就是打包，打包需要webpack，这里你就需要把公用组件打在一起，比如（ant）多个页面都需要用的，提出来，然后每个页面的view单独提出来就完了。这个时候你把你的后端数据源与你开发是的数据源接上就好了。
这些是个人的一些经验。

**Comment by doterme** [comment]
@anlia260 感谢回复。你说的我大概能明白，我看了ant的demo，如果用一个component，那就需要import进来，这样的js对asp.net mvc应用来说是没法直接用的，应该先需要babel去编译吧？如果需要编译，那我每次调整这个js都需要编译，调试就会变得很麻烦。而且我的view不是单纯的html，而是程序渲染出来的。大神看看有其他建议么？

**Comment by infeng** [comment]
前后端不分离，而且是asp.net mvc的话，比较难用react吧

**Comment by doterme** [comment]
@infeng 这个我看过了，但是我import ant的component就不支持。确实如你所说，用react没必要用razor模板去渲染页面，但是对后端开发来说，项目都是那种前后端不分离的项目，基本上自己就是全栈。

**Comment by infeng** [comment]
@doterme 自己一个做也可以前后端分离，服务端改成只是提供数据接口不做渲染就好了。你说的import antd不支持是什么意思，报什么异常，可以贴出来给大家看下

**Comment by yesmeck** [comment]
实际上你的问题应该是：如何在不用前端构建工具的情况下使用`React`。

你可以参考 http://codepen.io/benjycui/pen/KgPZrE?editors=001 （看 Settings 里的 CSS 和 JavaScript）这里实际上就是在没用任何前端构建工具的情况下，把 React 和 antd 通过 `<script />`  引入进来。不过这种方式可能会有不少限制，不能发挥 React 技术栈的全部优势，你要自己权衡。

**Comment by anlia260** [comment]
@yesmeck 说的很对，如果你想不用构建工具使用react，是可以的。你用什么语法写无所谓。比如先用引入ant（相关资源），react，然后你直接手写es5的react组件，然后你直接把这一坨的功能扔到你对应的页面。

**Comment by doterme** [comment]
@infeng reactjs.net我测试过了，reactjs.net 不支持JavaScript modules。

**Comment by doterme** [comment]
@yesmeck 这个demo我看过了，不支持html+js的方式，只能写js。

**Comment by leejaen** [comment]
asp、jsp什么的不要硬用react的东西吧，不是正道，吃力不讨好何苦为难自己呢，研究这条路的时间转前端会更好……

**Comment by afc163** [comment]
想直接裸写 JS 的话可以看看：https://facebook.github.io/react/docs/react-without-jsx.html

**Comment by doterme** [comment]
@leejaen 确实不是正道，执着了。感谢以上各位的解答。
