### ISSUE TITLE
建议增加获取value 接口

### ISSUE THREAD

**Issue by carr123** [ant-design/ant-design#388]
现在的 Datepicker， Radio 等控件，如想获取输入的值，必须通过定义回调函数才行。
组件能不能实现获取值的API， 组件外面可以通过类似this.refs.xxx.getValue() 这样的调用就能获取组件的值，而不需要定义回调 ？

**Comment by TouchQQ** [comment]
对，这个是个大问题。
现有模式，获取值太麻烦了，设想一个页面很多select组件，都是相同的class。 咋搞？

**Comment by afc163** [comment]
https://github.com/react-component/react-component.github.io/blob/master/docs/zh-cn/component-design.md#%E9%81%BF%E5%85%8D%E4%BD%BF%E7%94%A8-ref

**Comment by TouchQQ** [comment]
@afc163  不是简单的这种示例，在一个复杂的表单页面，各种嵌套，最后收集数据进行提交的时候就太麻烦了

**Comment by benjycui** [comment]
如果是读操作，使用 `ref` 应该也是可以的吧？

毕竟，楼上的那种情况，不允许 `this.refs.input.getVal()` 的话，父组件就要为每个子组件准备一个 `onXXXChange` 以获取它们的值，感觉要写很多 boilerplate。

**Comment by yiminghe** [comment]
不增加，数据是单向流，不允许读，自行通过 onchange 收集 ，boilerplate 自己 js 封装

**Comment by warmhug** [comment]
原来是老早提的问题，那么就这样保持不变好了。 

额外一个问题：通过`onchange`获取数据、或者在 componentDidMount / events / ... 里通过`this.refs.input.getVal()` 获取数据，是否一样都是单向数据流？另外`onchange`里一般都会写或者通过redux间接触发 `this.setState({xx:zz})`、触发生命周期函数都再执行一遍、或许最终ui完全没什么变化，但多了这些多余计算、感觉总是不太好。

**Comment by tuoxiansp** [comment]
@yiminghe | 不增加，数据是单向流，不允许读，自行通过 onchange 收集 
`Action -> Dispatcher -> Store -> View`
antd 仅仅涉及 View 层吧。。为什么需要单向呢。。
