### ISSUE TITLE
子组件挂载到父组件上导出，tree shaking 会失效

### ISSUE THREAD

**Issue by lifegit** [ant-design/ant-design#38804]
### Reproduction link

[https://github.com/lifegit/export-tree-shaking](https://github.com/lifegit/export-tree-shaking)

### Steps to reproduce

参见readme

### What is expected?

不使用子组件时，产物中没有该组件。

### What is actually happening?

不使用子组件，产物中打包进去了。

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | macos |
| Browser | 106.0.5249.119 (x86_64) |

**Comment by MadCcc** [comment]
挂载子组件一般都是相关组件，共用样式，所以体积不会特别大。
这个可以讨论一下。

**Comment by lifegit** [comment]
虽然会共用父组件的样式。但是子组件也有自己的样式和DOM代码。

**Comment by lifegit** [comment]
复现的demo现象是 没用子组件，但是产物中存在了子组件的样式。

**Comment by lifegit** [comment]
你说的也对，因为样式是一起管理的。但是现象确实是产物中存在了子组件的样式（属于浪费）

**Comment by lifegit** [comment]
> > 复现的demo现象是 没用子组件，但是产物中存在了子组件的样式。
> 
> 样式其实是一起的，不是 tree-shaking 失效了。你的需求应该是组件样式更细粒度的分割。

请教一下， 那是不是子组件的DOM因为tree shaking并没有打包进去，只是因为样式是一起管理的恰巧打包进去了。这样来说tree shaking 并没有失效。

**Comment by zombieJ** [comment]
Tree Shaking 也无法去配置做剥离，这个 issue 先关了。
