### ISSUE TITLE
穿梭框能支持disabled属性吗，像Select的disabled一样， 可以控制不可编辑

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#3880]

**Comment by ddcat1115** [comment]
没有整体的disabled，控制每项不可选吧，https://ant.design/components/transfer/#components-transfer-demo-basic

**Comment by zhulichao** [comment]
场景是这样的，刚开始进入页面时选项是都可选的，当我点击一个按钮后，所有都不可选。我在点击按钮后让每个选项disabled为true，但仍然是可选状态，选完一次后才变成不可选。示例代码如下：http://codepen.io/zhulichao/pen/qqqdJw?editors=001

**Comment by afc163** [comment]
> 我在点击按钮后让每个选项disabled为true，但仍然是可选状态

这句有点矛盾..

**Comment by afc163** [comment]
另外，状态变化必须使用 setState 来触发，直接修改数据是没有用的。https://facebook.github.io/react/docs/state-and-lifecycle.html#using-state-correctly

**Comment by zhulichao** [comment]
这个我知道，我这就是给个示例代码，没写那么麻烦。
![transfer](https://cloud.githubusercontent.com/assets/18158633/20381885/6703f5c6-ace4-11e6-9c01-44c7b390d472.png)

**Comment by afc163** [comment]
你的需求是啥？

**Comment by zhulichao** [comment]
我的需求就是刚进入页面时Transfer是可选的，点击一个按钮切换状态后，Transfer都不可选。

**Comment by afc163** [comment]
http://codepen.io/afc163/pen/RooWqZ?editors=0010

**Comment by zhulichao** [comment]
非常感谢。
