### ISSUE TITLE
https://4x.ant.design.com 网页加载速度很慢

### ISSUE THREAD

**Issue by ZhongJingBo** [ant-design/ant-design#38800]
### Reproduction link

[https://4x.ant.design/components/form-cn/](https://4x.ant.design/components/form-cn/)

### Steps to reproduce

点击打开 https://4x.ant.design/components/form-cn/
https://4x.ant.design/anticon~b39e3fdb.0d8e35.js  加载8分钟

### What is expected?

加载成功

### What is actually happening?

超级缓慢的加载

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 17 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25661
