### ISSUE TITLE
`Select` search text color didn't follow theme config

### ISSUE THREAD

**Issue by Ayuilos** [ant-design/ant-design#38805]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-5-0-0-forked-b34zwf)

### Steps to reproduce

Please check link

### What is expected?

The search text color should be white

### What is actually happening?

The search text color is black, and it's super hard to see it in dark mode

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | MacOS 12.6 |
| Browser | 107.0.5304.110 |

**Comment by Dunqing** [comment]
I think it's a bug, `AutoComplete` has the same problem
![image](https://user-images.githubusercontent.com/29533304/203215378-712e6c8d-4f45-40ee-8f58-877daea664c7.png)

**Comment by Dunqing** [comment]
And `Pagination`
![image](https://user-images.githubusercontent.com/29533304/203217892-04d5bd6c-f9d4-463a-894c-e151a479fe22.png)
