### ISSUE TITLE
Module not found: Can't resolve 'antd/es/auto-complete/style'

### ISSUE THREAD

**Issue by songhanlin** [ant-design/ant-design#38803]
### Reproduction link

[https://github.com/ant-design/ant-design/tree/master/components/auto-complete](https://github.com/ant-design/ant-design/tree/master/components/auto-complete)

### Steps to reproduce

下载最新的antd依赖, 找到antd/es/auto-complete/文件夹下, 没有style文件夹

### What is expected?

有antd/es/auto-complete/style/文件夹

### What is actually happening?

找不到antd/es/auto-complete/style/文件夹

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | any |
| System | any |
| Browser | any |

**Comment by zombieJ** [comment]
`babel-plugin-import` 不需要了，我给迁移文档加一下。

**Comment by afc163** [comment]
@songhanlin 你需要去掉 babel-plugin-import 或者关掉 babel-plugin-import 的 style 属性。

**Comment by liuxi0811** [comment]
![image](https://user-images.githubusercontent.com/75471072/210329574-7d33981c-4fdf-4aad-887e-4577ed42858e.png)
这样如何关了 babel-plugin-import的引入呢
