### ISSUE TITLE
Invalid aria prop `aria-open` on <div> tag. For details, see https://fb.me/invalid-aria-prop

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design#3881]
- antd 版本: 2.4.2
- 操作系统及其版本: win10
- 浏览器及其版本:  54.0.2840.87 m (64-bit)

react 15.4.0 版本上有这个警告。。

    warning.js:36Warning: Invalid aria prop `aria-open` on <div> tag. For details, see https://fb.me/invalid-aria-prop
        in div (created by SubMenu)
        in li (created by SubMenu)
        in SubMenu (created by Menu)
        in ul (created by DOMWrap)
        in DOMWrap (created by Menu)
        in Menu (created by Menu)
        in Menu (created by Application)
        in div (created by Application)
        in div (created by Application)
        in Application (created by Unknown)
        in Unknown (created by Form(WrappedComponent))
        in Form(WrappedComponent) (created by Connect(Form(WrappedComponent)))
        in Connect(Form(WrappedComponent)) (created by RouterContext)
        in RouterContext (created by Router)
        in Router
        in Provider

**Comment by yeliex** [comment]
+1

**Comment by afc163** [comment]
react 15.4.0 issues all trace #3882
