### ISSUE TITLE
Space.Compact Button 紧凑布局 导致样式问题

### ISSUE THREAD

**Issue by Veveue** [ant-design/ant-design#38812]
### Reproduction link

[https://stackblitz.com/edit/react-1klrrl?file=demo.tsx,Component.tsx,index.html](https://stackblitz.com/edit/react-1klrrl?file=demo.tsx,Component.tsx,index.html)

### Steps to reproduce

🈚️

### What is expected?

样式正常

### What is actually happening?

弹框 按钮样式 问题
可看上面链接

| Environment | Info |
| --- | --- |
| antd | 5.0.0、4.24.x |
| React | 17.0.1 |
| System | 所有 |
| Browser | 所有 |

**Comment by afc163** [comment]
Duplicate of #38655

**Comment by foryuki** [comment]
正在处理中，主要是 Space.Compact context 未做阻断。
