### ISSUE TITLE
dropdown cascading menu keeps previous menu visibible

### ISSUE THREAD

**Issue by maxired** [ant-design/ant-design#38818]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-o0oit8?file=/index.js)

### Steps to reproduce

- create dropdown element with a cascading menu
- open the dropdown
- hover a cascading entry
- hover a second cascading entry

### What is expected?

- the currently hovered cascading entry is visible
- the previously hovered cascading entry Is not visible  

### What is actually happening?

- the currently hovered cascading entry is visible
- the previously hovered cascading entry Is still visible  

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | macos |
| Browser | chrome |

<img width="471" alt="Screenshot 2022-11-21 at 15 42 47" src="https://user-images.githubusercontent.com/1194083/203083221-12906792-33c2-46bb-b8d7-dd92b118fc3b.png">

**Comment by bowdawn** [comment]
add <Menu hidden /> as a temporary bug fix. It seems that the Menu must be imported for the casecade menu to work inside a dropdown element.

**Comment by maxired** [comment]
@bowdawn thanks for the suggestion. I was not able to have it working.
would you be able to provide a working repro ?

**Comment by playola** [comment]
I am having the same issue with the example from the documentation: https://ant.design/components/dropdown#components-dropdown-demo-sub-menu

See reproducible example: https://codesandbox.io/s/cascading-menu-antd-5-0-1-forked-v4pzgm

**Comment by maxired** [comment]
Not sure which component is faulty, but it seems the issue is because the leavedClassName (`-hidden`) is not correctly applied to hide the not visible anymore element.

**Comment by maxired** [comment]
I was able to solve part of the problem by adding `initZoomMotion(token, 'zoom-big')`  in https://github.com/ant-design/ant-design/blob/master/components/dropdown/style/index.tsx#L416

this is required because of https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.tsx#L407-L408

**Comment by maxired** [comment]
The previous comment says `part of the problem` because there is still an issue with the menu where the previously open submenu is still visible.

https://user-images.githubusercontent.com/1194083/203829846-891e86a0-9e4d-4c13-bcf9-713a78290d7d.mov

**Comment by iska9der** [comment]
This problem still exist on 5.0.7 
![image](https://user-images.githubusercontent.com/11888809/208649019-b35f58ad-5c99-469a-8de6-807b7c1effce.png)

**Comment by ashishgupta-sf** [comment]
Has this issue been resolved.
Because this still exists
