### ISSUE TITLE
Inline Menu does not close when clicking on item

### ISSUE THREAD

**Issue by GeorgeFlorian** [ant-design/ant-design#38813]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inline-menu-antd-5-0-0-forked-q72d4j)

### Steps to reproduce

Create an inline menu
Open inline menu
Click on a random menu item

### What is expected?

Close inline menu when item is clicked

### What is actually happening?

Inline menu stays open when clicking on menu item

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 18.1.0 |
| System | Ubuntu 20.04.5 LTS |
| Browser | Version 107.0.5304.110 (Official Build) (64-bit) |

---
In the example I have added routes and option to navigate when clicking on a menu item (because that is the main functionality of a menu).  
The menu stays open even when changing routes.  
The other two menu types `vertical` and `horizontal` close automatically after clicking on a menu item.  
I have also tried using antd v5.0.0 and the result is the same.

**Comment by GeorgeFlorian** [comment]
> I don't think it is antd Menu's problem, could you provide a **minimal** reproduce with antd components only?

Here it is: https://codesandbox.io/s/inline-menu-antd-5-0-0-forked-8behpl?file=/demo.js

How can I close Navigatino Three menu when I click on of its Options ? There is no close attribute for the Menu API.
Thank you.

**Comment by afc163** [comment]
You could control `openKeys` prop. It is not a antd bug but a usage question, I am closing this.
