### ISSUE TITLE
在Safari浏览器中，打开日期或者时间选择框，再点击其他地方关闭时出现重复动画

### ISSUE THREAD

**Issue by Aug-Sunrise** [ant-design/ant-design#38817]
### Reproduction link

[https://ant.design/components/time-picker-cn](https://ant.design/components/time-picker-cn)

### Steps to reproduce

点击日期选择框（或者时间选择框），再点击元素外部触发关闭，在Safari中出现两次或三次关闭动画，并且打开的时候也有几百毫秒的延迟

### What is expected?

正常显示

### What is actually happening?

出现重复动画并且打开的时候也有几百毫秒的延迟

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | react18 |
| System | macOS 12.16.1 |
| Browser | Safari 版本16.1 (17614.2.9.1.13, 17614) |

**Comment by Aug-Sunrise** [comment]
https://user-images.githubusercontent.com/51350414/203078669-6668f95b-9714-4fb6-a9f8-9cdc9d1a880b.mov

**Comment by afc163** [comment]
看上去可能和 #38548 是一个问题。cc @zombieJ

**Comment by Aug-Sunrise** [comment]
> 试试 5.0.1


https://user-images.githubusercontent.com/51350414/203465049-e832b233-f5d6-4d16-b3de-5a01a133e044.mov

经测试，本地项目antd5.0.0以及5.0.1都未复现，但Ant Design官网仍有此问题

**Comment by zombieJ** [comment]
推测是页面卡顿导致的，等一下 https://github.com/ant-design/ant-design/issues/38548#issuecomment-1323396459

**Comment by zombieJ** [comment]
merge into #38686
