### ISSUE TITLE
CompoundedComponent and DropdownInterface is not exported which results in error ts(4032)

### ISSUE THREAD

**Issue by ctretyak** [ant-design/ant-design#38824]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-dream-tq0ujg?file=/src/styled.ts)

### Steps to reproduce

Wrap Button component into styled (styled-components)

### What is expected?

No error

### What is actually happening?

We are exporting component that using an interface that hadn't exported and in result we have error `Exported variable 'ButtonStyled' has or is using name 'CompoundedComponent' from external module "/sandbox/node_modules/antd/es/button/button" but cannot be named.ts(4023)`

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | react |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Is it fixed in https://github.com/ant-design/ant-design/pull/38666 ?

**Comment by ctretyak** [comment]
> 

partly. With Button it will be ok. But I don't see any fix on DropdownInterface

**Comment by ctretyak** [comment]
> Is it fixed in #38666 ?

partly. With Button it will be ok. But I don't see any fix on DropdownInterface

**Comment by callmenikk** [comment]
remove `"declaration": true` from **tsconfig.json** and it will disappear the error

**Comment by ctretyak** [comment]
> remove `"declaration": true` from **tsconfig.json** and it will disappear the error

Of course, but if I need it?

**Comment by callmenikk** [comment]
thats good issue, if [`CompoundedComponent`](https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L134-L140) and [`DropdownInterface`](https://github.com/ant-design/ant-design/blob/master/components/dropdown/dropdown.tsx#L84-L87) had exports that would fix that error easily doing like this

```ts
import { CompoundedComponent } from 'antd/lib/button/button';

export const SButton: CompoundedComponent = styled(Button)``
```
