### ISSUE TITLE
Support React v15.4.0

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#3882]
#### 发生问题的环境是：

- antd 版本: 2.4.2
- 操作系统及其版本: macOS Sierra
- 浏览器及其版本: Chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

Webpack build error:

```
ERROR in ./~/rc-editor-core/lib/EditorCore/export/getHTML.js
Module not found: Error: Cannot resolve module 'react/lib/CSSProperty.js' in xxx/node_modules/rc-editor-core/lib/EditorCore/export
 @ ./~/rc-editor-core/lib/EditorCore/export/getHTML.js 18:19-54
```

https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html

> However, there is a possibility that you imported private APIs from react/lib/*, or that a package you rely on might use them. We would like to remind you that this was never supported, and that your apps should not rely on internal APIs. The React internals will keep changing as we work to make React better.

**Comment by yesmeck** [comment]
https://github.com/react-component/editor-core/issues/1

**Comment by afc163** [comment]
```
warning.js:36Warning: Invalid aria prop `aria-open` on <div> tag. For details, see https://fb.me/invalid-aria-prop
    in div (created by SubMenu)
    in li (created by SubMenu)
    in SubMenu (created by Menu)
    in ul (created by DOMWrap)
    in DOMWrap (created by Menu)
    in Menu (created by Menu)
    in Menu (created by Application)
    in div (created by Application)
    in div (created by Application)
    in Application (created by Unknown)
    in Unknown (created by Form(WrappedComponent))
    in Form(WrappedComponent) (created by Connect(Form(WrappedComponent)))
    in Connect(Form(WrappedComponent)) (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider
```

And this: https://github.com/ant-design/ant-design/issues/3881

**Comment by RaoHai** [comment]
* [x] rc-editor-core@0.5.9

**Comment by Verten** [comment]
is this "Invalid aria prop `aria-open` on <div> tag" problem has been fixed?

**Comment by xieyihao** [comment]
~  什么时候能更新解决此问题

**Comment by afc163** [comment]
已修复。

**Comment by aifly** [comment]
怎么解决的啊？

**Comment by yesmeck** [comment]
@aifly 升级 antd 到最新。

**Comment by aifly** [comment]
@yesmeck 谢谢，终于好了。

**Comment by yangfan0095** [comment]
老版本 肿么办

**Comment by magicdawn** [comment]
貌似 1.x latest 没有这个 patch

**Comment by magicdawn** [comment]
https://github.com/react-component/menu/commit/79c52bbce197cdcceb6a8a07351aa4bc0a46a628
antd@1.x 我看包含的是 rc-menu@4.x, 但是 patch 在 5.0.10  5.0.9 5.0.8 5.0.7 5.0.6 5.0.5 😂

**Comment by afc163** [comment]
1.x is not maintianed anymore.
