### ISSUE TITLE
v5默认使用了dayjs，rc picker 默认的dayjs配置有问题 需要改下 

### ISSUE THREAD

**Issue by adolfheir** [ant-design/ant-design#38839]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pd5j5n?file=/package.json:124-127)

### Steps to reproduce

1. 时间选择器选择xx:59:59这个时间
2.输入框最后一位按delete键
3.dayjs默认formate 会先formate成xx:59:05 再操作会变成xx:59:00 然后在变成59:0

![Sep-29-2022 14-13-34](https://user-images.githubusercontent.com/26828649/192953216-508e19bb-6b38-4906-a22c-754f0c277363.gif)

### What is expected?

期望和moment 一致 
步骤3 直接变成 xx:59:5

### What is actually happening?

dayjs默认formate 会先formate成xx:59:05 再操作会变成xx:59:00 然后在变成59:0

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | all |
| System | all |
| Browser | all |

---
具体解决方案参照之前issue 
e.g
https://github.com/react-component/picker/issues/482

**Comment by zombieJ** [comment]
看这边你已经有解了 https://github.com/react-component/picker/issues/482， 直接来个 PR？

**Comment by adolfheir** [comment]
hh 果然这边人还是多呀 那边提了几个月没啥动静 我看你们已经搞了pr 我就算了

> 看这边你已经有解了 [react-component/picker#482](https://github.com/react-component/picker/issues/482)， 直接来个 PR？

hh 果然这边人还是多呀 那边提了几个月没啥动静 我看你们已经搞了pr 我就算了

**Comment by zombieJ** [comment]
> hh 果然这边人还是多呀 那边提了几个月没啥动静 我看你们已经搞了pr 我就算了


信息流太多了，被淹了 😂
