### ISSUE TITLE
Calender: There are no options for categories  (scheduler)

### ISSUE THREAD

**Issue by imamaad** [ant-design/ant-design#38831]
![Screenshot 2022-11-22 012046](https://user-images.githubusercontent.com/22539527/203165205-d5aaae31-2c57-47c0-9272-4865d111e9ee.png)
### What problem does this feature solve?

Categorize events in the calendar

### What does the proposed API look like?

<Calendar
  dataSource={[{
  date:'2022-11-22',
  dataIndex: 'aircraftCRJ200',
 type: 'warning', content: 'This is warning event'
 }]}
  columns={[{
    title: 'Aircraft',
    dataIndex: 'aircraftCRJ200',
    key: 'aircraft',
  }]}
/>

**Comment by afc163** [comment]
Sorry, we don't have plan to implement this feature in Calendar.
