### ISSUE TITLE
setFieldsValue不会触发已经定义的校验吗，校验没有生效

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#3883]

**Comment by benjycui** [comment]
只会在 `validateTrigger` 定义的时机触发校验 https://ant.design/components/form/#getFieldDecorator's-parameters

手动触发请调用 `validateFields`

**Comment by zhulichao** [comment]
那有什么方法可以回填表单值并且触发校验吗

**Comment by zhulichao** [comment]
好的，非常感谢。
