### ISSUE TITLE
site demo in FloatButton.BackTop fail

### ISSUE THREAD

**Issue by ruoduan-hub** [ant-design/ant-design#38836]
### Reproduction link

[https://ant.design/components/float-button-cn#components-float-button-demo-back-top](https://ant.design/components/float-button-cn#components-float-button-demo-back-top)

### Steps to reproduce

官网点击 back-top 无效，但是 fork 后本地看是没问题的，是因为修复了 还没来得及发布吗 ？

### What is expected?

0

### What is actually happening?

0

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | macos |
| Browser | chrome 107.0.5304.110 |

---
![img](https://s2.loli.net/2022/11/22/ayfhM9rTFLmGBY3.png)

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/38770
