### ISSUE TITLE
v5 版本在 Safari 中样式全部异常，无错误提示

### ISSUE THREAD

**Issue by Clover-You** [ant-design/ant-design#38837]
### Reproduction link

[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce

使用 Safari 打开

### What is expected?

正常显示antd所有样式

### What is actually happening?

antd所有样式无法正常显示

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | 10.15.4 |
| Browser | Safari 13.1 (15609.1.20.111.8) |

---
在google chrome正常，Safari就不行了，未禁止 JavaScript
<img width="1439" alt="截屏2022-11-22 11 24 52" src="https://user-images.githubusercontent.com/50982977/203216330-dacf7a74-3b06-4696-9309-a24e60bc678b.png">

**Comment by afc163** [comment]
试试 https://ant-design.antgroup.com

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/203216681-fe7957b0-0e4e-46de-b662-b731449454a1.png)
safari 13.1 版本不支持 where

**Comment by afc163** [comment]
你需要升级 safari 版本了，我们用了 :where 。

**Comment by zombieJ** [comment]
官网使用最新浏览器，自己研发的站点可以关闭 selector：
https://github.com/ant-design/ant-design/blob/master/docs/react/customize-theme.zh-CN.md#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%B0%83%E6%95%B4

**Comment by Clover-You** [comment]
@zombieJ OK了，谢谢🙏

**Comment by Clover-You** [comment]
@afc163 升级Safari好像要升级系统，电脑显卡造不动了。谢谢你的帮助！

**Comment by Clover-You** [comment]
@MadCcc 谢谢
