### ISSUE TITLE
Request to add the antd theme change option on the website as it was before

### ISSUE THREAD

**Issue by gauthamhc09** [ant-design/ant-design#38840]
### What problem does this feature solve?

It is easy to change the theme from light mode to dark mode or vice-versa. 
Light mode causes lot of strain while going through the documentation.
It will be really great if we have the option to change the theme.
Thanks

### What does the proposed API look like?

On the previous version the option was available.

**Comment by afc163** [comment]
@MadCcc Could we bring back theme switcher ?
