### ISSUE TITLE
qiankun 下 css 位置被劫持，导致 Modal 的 ScrollLock 不能解除

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#38845]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/30479](https://github.com/ant-design/ant-design/issues/30479)

### Steps to reproduce

在 Modal 打开时，会锁定 document.body 的滚动，在关闭时再解开，对应代码如下：

https://github.com/react-component/portal/blob/master/src/useScrollLocker.tsx#L25-L35

然而，在 qiankun 下，由于 qiankun 劫持了样式位置，在 removeCSS 时，并不能找到对应的样式标签，导致 lock 未解锁。

### What is expected?

在 injectCSS 和 removeCSS 时，加入 qiankun 的兼容

### What is actually happening?

Modal ScrollLock 未解锁，页面无法滚动

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| qiankun | 2.4.2 ... 2.8.4（需要一定的触发条件） | 
| React | 18 |
| System | macOS 11.7(M1) |
| Browser | Chrome 107 |

---
类似的 issue：https://github.com/ant-design/ant-design/issues/30479
一个相关的改动：https://github.com/react-component/util/commit/eb6d4df109ff83f4d3cd573133a41946deb59bcc
但是似乎没有对 injectCSS 和 removeCSS 做相同的修复
如果需要 reproduce，我再搞一下，涉及qiankun搞起来比较麻烦。
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/7264444/203246443-34d6351f-90d6-41b1-b1f7-79e951eb309d.png">

**Comment by zombieJ** [comment]
还是搞一个吧，这样我方便给qiankun 作者看一下怎么配合的好

**Comment by dancerphil** [comment]
> 还是搞一个吧，这样我方便给qiankun 作者看一下怎么配合的好

OK，没问题

**Comment by dancerphil** [comment]
看起来 https://github.com/umijs/qiankun/releases/tag/v2.7.4 解决了此问题，排查下来是内部平台的主应用版本落后导致的

**Comment by zhujun24** [comment]
qiankun 2.8.4 + antd 4.24.5 仍有这个问题

**Comment by dancerphil** [comment]
> 

你有办法重现么？

**Comment by dancerphil** [comment]
再描述一下另一个现象，可能有助于排查问题：

`antd5` 的样式采用 `prepend` 方式插入，但是在 `qiankun` 下并不能正常的插到前面，而是按照 js 代码的顺序添加，所以在 class 优先级相同的情况下，class 的顺序不对，使得部分样式覆盖不了。

**Comment by dancerphil** [comment]
由于有多个用户有该问题，所以 Reopen 该问题，并期待一个 reproduction。

**Comment by zhujun24** [comment]
> 

本地dev是好的，build之后就是不行的，奇怪

**Comment by dancerphil** [comment]
> > 
> 
> 本地dev是好的，build之后就是不行的，奇怪

有解决问题或找到原因吗？

**Comment by zhujun24** [comment]
关闭 sandbox 试试

**Comment by Peiiii** [comment]
> 再描述一下另一个现象，可能有助于排查问题：
> 
> `antd5` 的样式采用 `prepend` 方式插入，但是在 `qiankun` 某些情况下（不知道怎么触发）并不能正常的插到前面，而是按照 js 代码的顺序添加，所以在 class 优先级相同的情况下，class 的顺序不对，使得部分样式覆盖不了。

遇到了同样的问题，一部分style没有正确的prepend到前面，导致样式优先级关系变化。并且dev是ok的，只在prod模式下有问题。

**Comment by gtgtkiss** [comment]
好像有关滚动，antd都是监听body的，放到qiankun后，滚动的不是body了，就导致scroll相关的都失效了

**Comment by mmmmmmmgo** [comment]
我这边遇到的问题

1. Portal（Modal 的底层） 在打开时候，会往head 添加一段 `html body {  overflow-y: hidden;  }` 来锁定模层的滚动。这段 style 被 qiankun 劫持，并插入`<qiankun-head>`
2. 当 Portal 关闭后, Portal 会删除刚刚注入的 style
3. 但观察发现, 在打开 Portal 时候,qiankun 内部的`currentRunningApp` 是非空的, 代表当前微应用正在运行, 所以能成功插入到`qiankun-head` 但是在关闭时, `currentRunningApp`为空, 我怀疑是 是 antd 的 CSSMotion 影响了执行时机 导致真正在移除时,qiankun 已经认为当前不属于微应用代码在执行.

> 另外,我的项目 antd 是放在主应用的, 一开始以为这个主要原因(可能是代码不在微应用,所以 qiankun 不劫持),但是 插入`qiankun-head`是成功的, 所以就算放到主应用的代码 qiankun 也可能劫持

**Comment by mmmmmmmgo** [comment]
> 我这边遇到的问题
> 
> 1. Portal（Modal 的底层） 在打开时候，会往head 添加一段 `html body {  overflow-y: hidden;  }` 来锁定模层的滚动。这段 style 被 qiankun 劫持，并插入`<qiankun-head>`
> 2. 当 Portal 关闭后, Portal 会删除刚刚注入的 style
> 3. 但观察发现, 在打开 Portal 时候,qiankun 内部的`currentRunningApp` 是非空的, 代表当前微应用正在运行, 所以能成功插入到`qiankun-head` 但是在关闭时, `currentRunningApp`为空, 我怀疑是 是 antd 的 CSSMotion 影响了执行时机 导致真正在移除时,qiankun 已经认为当前不属于微应用代码在执行.
> 
> > 另外,我的项目 antd 是放在主应用的(作为全部微应用的 external), 一开始以为这个主要原因(可能是代码不在微应用,所以 qiankun 不劫持),但是 插入`qiankun-head`是成功的, 所以就算放到主应用的代码 qiankun 也可能劫持

升级到最新版解决🌚

**Comment by afc163** [comment]
@mmmmmmmgo 最新版指的是 antd 的还是 qiankun 的？

**Comment by mmmmmmmgo** [comment]
> @mmmmmmmgo 最新版指的是 antd 的还是 qiankun 的？

qiankun

在https://github.com/umijs/qiankun/pull/2404 这个pr中, 将劫持逻辑从document.createELement =  改成 `with(proxyDoucment){}` 这样能保证主应用的antd.min.js中的创建的style 不会被乾坤劫持

**Comment by HankWang1999** [comment]
> > @mmmmmmmgo 最新版指的是 antd 的还是 qiankun 的？
> 
> qiankun
> 
> 在[umijs/qiankun#2404](https://github.com/umijs/qiankun/pull/2404) 这个pr中, 将劫持逻辑从document.createELement = 改成 `with(proxyDoucment){}` 这样能保证主应用的antd.min.js中的创建的style 不会被乾坤劫持

升级到最新版本并没有解决这个问题😭
