### ISSUE TITLE
文案页面的显示似乎有问题

### ISSUE THREAD

**Issue by mintcheese** [ant-design/ant-design#38846]
### Reproduction link

[https://ant.design/docs/spec/copywriting-cn](https://ant.design/docs/spec/copywriting-cn)

### Steps to reproduce

直接进入此页面

### What is expected?

布局正常，元素完整，可读性高

### What is actually happening?

布局显示混乱，部分元素消失，导致页面可读性极低

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 不适用 |
| System | macOS 13.0 |
| Browser | Chrome 98.0.4758.109（正式版本） (x86_64) |

**Comment by afc163** [comment]
可以提到 https://github.com/ant-design/ant-design/issues/38463 我们一起修改。

**Comment by MadCcc** [comment]
Trace in https://github.com/ant-design/ant-design/issues/38463
