### ISSUE TITLE
FloatButton 置顶按钮展现逻辑有错误

### ISSUE THREAD

**Issue by onewink** [ant-design/ant-design#38858]
### Reproduction link

[https://ant.design/components/float-button-cn](https://ant.design/components/float-button-cn)

### Steps to reproduce

1.  进入https://ant.design/components/float-button-cn
2. 找到『回到顶部』的介绍
3. 下拉一段距离
4. 可以观察到置顶按钮是不展现的
![image](https://user-images.githubusercontent.com/30338668/203298898-a8bd4ee7-457f-47ae-b597-1145481ddb8d.png)

6. 将窗口上滑到顶部，按钮展现（正常逻辑应该是视窗在顶部时，置顶按钮是隐藏的）
![image](https://user-images.githubusercontent.com/30338668/203298829-12c74cc8-6858-4e1b-b016-60888f6d6927.png)

### What is expected?

1.  下拉时按钮展现
2. 窗口置顶时，按钮隐藏

### What is actually happening?

1.  下拉时按钮隐藏
![image](https://user-images.githubusercontent.com/30338668/203298875-ee7d9e17-b54b-49b6-8573-85fe56c4fdf8.png)

3. 窗口置顶时，按钮展现
![image](https://user-images.githubusercontent.com/30338668/203298829-12c74cc8-6858-4e1b-b016-60888f6d6927.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | react |
| System | OSX Monterey 12.1  M1 |
| Browser | Chrome 107.0.5304.110|

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/38770
