### ISSUE TITLE
can't make form layout responsive with labelCol and wrapperCol

### ISSUE THREAD

**Issue by fireflies1988** [ant-design/ant-design#38863]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z4xkf5?file=/demo.js:890-900)

### Steps to reproduce

Just test the form responsive, you can see it.
![image](https://user-images.githubusercontent.com/64318804/203308874-a9b4822f-7d22-4972-ad3c-ed47adc0be80.png)
![image](https://user-images.githubusercontent.com/64318804/203308916-efdfa7cf-0b0f-4c7f-ba4c-dec290d4b7cb.png)

### What is expected?

It should have changed from horizontal layout to vertical layout when it reaches the breakpoint 'xs'.

### What is actually happening?

it's not responsive, looks awful

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | Window 11 |
| Browser | Chrome 107.0.5304.107 |

**Comment by fireflies1988** [comment]
antd version 4.24.3 works perfectly, should I downgrade to 4.24.3?

**Comment by arvinxx** [comment]
@MadCcc  Kitchen 的 form 样式报错好像也是这个问题。刚试了下 5.0.1 并没有修复
