### ISSUE TITLE
layout.sider 使用默认的trigger收起时，sider内submenu闪烁问题

### ISSUE THREAD

**Issue by Ivan-hl** [ant-design/ant-design#38867]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wsin9i)

### Steps to reproduce

1. 点击submenu展开（必须要submenu为展开状态）
2. 点击layout.sider底步默认触发器 收起sidebar
3. 发现sider中的submenu会有一个闪烁的动画

### What is expected?

在submenu不管是展开还是收起时，在点击sider底部收缩触发器进行收缩sider时，都不应该出现submenu的动画闪烁

### What is actually happening?

submenu展开时，在点击sider底部收缩触发器进行收缩sidebar时，出现submenu的动画闪烁

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome 107 |

---
使用layout.sider布局
sider内嵌menu mode=inline
展开layout.sider.menu.submenu
点击sider底部trigger收起
出现submenu闪烁

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/36152

**Comment by Ivan-hl** [comment]
请问修复的问题什么时候发到正式版？
