### ISSUE TITLE
setFieldsValue设置的值通过getFieldsValue()不能取出来。

### ISSUE THREAD

**Issue by xiongran** [ant-design/ant-design#3887]
#### 发生问题的环境是：

- antd 版本: 2.4.2
- 操作系统及其版本: WIN7专业版
- 浏览器及其版本: chrome 50.0.2661.87 m

#### 您做了什么？请提供尽可能详细的重现步骤。
1、通过setFieldsValue设置了某个值，比如setFieldsValue({abc: 123})。
2、通过getFieldsValue()返回的对象没有包含abc属性。
      const addFields = getFieldsValue();
      addFields.abc === undefined;
3、但是通过getFieldsValue(['abc'])可以获取到abc的值
      getFieldsValue(['abc']) === 123;

#### 实际上的结果是:
getFieldsValue()仅返回了通过getFieldDecorator绑定的属性和属性值，而通过setFieldsValue设置的属性和属性值则不能返回。如果希望返回的话必须指定属性名获取，如getFieldsValue(['abc'])。

#### 您期待的结果是:
getFieldsValue()能返回全部的属性和属性值，即不仅能返回通过getFieldDecorator绑定的属性和属性值，同时能返回通过setFieldsValue设置的属性和属性值。

#### 可重现的在线演示
按上述编码即可重现。

**Comment by afc163** [comment]
https://github.com/react-component/form/issues/38#issuecomment-252904727
