### ISSUE TITLE
Antd 5.0.0 is not working in cent browser

### ISSUE THREAD

**Issue by anhpt-bss** [ant-design/ant-design#38884]
### Reproduction link

[https://ant.design/components/overview/](https://ant.design/components/overview/)

### Steps to reproduce

Open app in cent browser

### What is expected?

css apply

### What is actually happening?

css is not apply

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | window 10 |
| Browser | Cent Browser (Version 4.3.9.248 (Official Build) (32-bit) (Chromium 86.0.4240.198)) |

**Comment by zombieJ** [comment]
antd official site only  support modern browser. But you can enable css downgrade with `StyleProvider` in you web application:

https://ant.design/docs/react/customize-theme#compatible-adjustment
