### ISSUE TITLE
v5.0.1找不到lib/icon/style

### ISSUE THREAD

**Issue by 123wodekuaile** [ant-design/ant-design#38889]
![image](https://user-images.githubusercontent.com/28552860/203461127-1362c104-0e2e-4fb1-aac7-394b6aa8cc45.png)

### Reproduction link

[https://ant.design/components/icon-cn](https://ant.design/components/icon-cn)

### Steps to reproduce

 Can't resolve 'antd/lib/icon/style' 

### What is expected?

增加antd/lib/icon/style文件

### What is actually happening?

缺少antd/lib/icon/style文件

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 17.0.2 |
| System | mac |
| Browser | 107.0.5304.110 |

**Comment by zombieJ** [comment]
你使用的库不支持 v5，请向库作者反馈哈。
