### ISSUE TITLE
.ant-table-fixed 样式缺失

### ISSUE THREAD

**Issue by kiwim** [ant-design/ant-design#3889]
### table 中的ant-table-fixed样式缺失
.ant-table-fixed{
  table-layout: fixed;
}

#### 发生问题的环境是：
- antd 版本:2.4.2
- 操作系统及其版本:win7
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

table 中的ant-table-fixed样式缺失,导致无法固定宽度，
在table 的index.less中并没有对ant-table-fixed这个样式做定义

#### 您期待的结果是:
表头th和表格内td在横向滚动，并设置了colomn的width后能够上下对齐,并固定为设置的column的宽度。

**Comment by yesmeck** [comment]
删掉 node_modules/rc-table 重新 npm install 下试试。

**Comment by afc163** [comment]
最好给出重现，什么叫做无法固定宽度。

烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by yesmeck** [comment]
@afc163 这个是我上次引入的问题，刚发了 path 版本。

**Comment by afc163** [comment]
:ok_hand:

**Comment by afc163** [comment]
@yesmeck 可能需要发一个 rc-table@5.0.6，现在还没升上来。

加上这个：https://github.com/react-component/table/commit/f65305b079b6f6ec543c6b4c82b47c5054b92219

**Comment by afc163** [comment]
rc-table 的用例怎么挂了。

**Comment by yesmeck** [comment]
就是把 timer 去掉的缘故，好像会死循环。。大概就是当初用 setTimeout 的原因吧。。

`componentDidMount` 的时候执行 `syncFixedTableRowHeight` 更新 state，然后触发 `componentDidUpdate`，再执行  `syncFixedTableRowHeight` 。。。。

**Comment by yesmeck** [comment]
奥，不会死循环，这里有判断 https://github.com/react-component/table/blob/master/src/Table.jsx#L582

**Comment by yesmeck** [comment]
不过确实是死循环了，明天再研究下。

**Comment by yesmeck** [comment]
修正了，这里 https://github.com/react-component/table/commit/a024364d69a1bbfe1dd403d929fadf5627bfa0a8 导致的死循环。

**Comment by afc163** [comment]
直接把 antd 里的 rc-table 升上来好了。

**Comment by yesmeck** [comment]
刚发了 5.0.6
