### ISSUE TITLE
Anchor和Affix组件，当进行路由切换时，控制台警告存在内存泄漏？

### ISSUE THREAD

**Issue by Jauuo** [ant-design/ant-design#38894]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cvpll4?file=/app.js)

### Steps to reproduce

1.先点击Affix
2.然后点击Index
3.查看控制台
(1,2两步可能需多次尝试会出现)
![](https://alpha.glilmu.com/i/2022/11/23/j3wehi.jpg)

### What is expected?

希望没有警告

### What is actually happening?

控制台：
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | 17.0.2 |
| System | window |
| Browser | Chrome (Latest) |

**Comment by zombieJ** [comment]
> **No warning about `setState` on unmounted components**: Previously, React warned about memory leaks when you call setState on an unmounted component. This warning was added for subscriptions, but people primarily run into it in scenarios where setting state is fine, and workarounds make the code worse. We've https://github.com/facebook/react/pull/22114 this warning.

ref: https://github.com/facebook/react/pull/24195

大部分的卸载后 `setState` 都不会造成内存泄漏，反而是解决这个 warning 会造成糟糕的代码。在 React 18 中这个 warning 已经被移除了。

同样的，Affix 里有个 ResizeObserver 来检测容器尺寸变化，在移除时触发了异步的尺寸计算，因而触发了旧版本 React 的 warning。但是实际上当元素卸载后，ResizeOberver 组件也会被卸载，并不会有内存泄漏。加上 mount ref 反而会有额外的性能检查损耗。
