### ISSUE TITLE
Tabs新增标签页后，鼠标移动到折叠按钮。重复移出移回，点击没有反应

### ISSUE THREAD

**Issue by liaohongxing** [ant-design/ant-design#38890]
### Reproduction link

[https://stackblitz.com/edit/react-ph8wx3?file=demo.tsx](https://stackblitz.com/edit/react-ph8wx3?file=demo.tsx)

https://react-ph8wx3.stackblitz.io

### Steps to reproduce

多次点击ADD按钮，直到出现折叠按钮，鼠标移动到三个点[折叠]按钮上。不做任何操作，鼠标移走。再次移动回来，发现菜单不能点击
![动画](https://user-images.githubusercontent.com/35255844/203461853-e1d5a634-1b81-43ae-8ad1-1fe079a295bc.gif)

### What is expected?

跟官网一样，折叠菜单能正常操作

### What is actually happening?

此案例从官网例子fork出来 ，无任何修改，折叠菜单无法操作

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.2.0 |
| System | win10 |
| Browser | Firefox107 |

**Comment by zombieJ** [comment]
动画样式丢失了
