### ISSUE TITLE
Segmented properties missing when using options or onChange. API document is out updated.

### ISSUE THREAD

**Issue by TranNgocKhoa** [ant-design/ant-design#38898]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-custom-filter-ts-forked-36s4fx)

### Steps to reproduce

1. Use antd 4.24.3, react 18.2.0 with TypeScript.

2. Declare a component using `<Segmented />` with option or onChange property.
```
<Segmented
    onChange={(option) => {}}
/>
```

3. Run the web app.

### What is expected?

No compiler error

### What is actually happening?

Compiler error: TS2739: Type '{ options: { label: Element; value: string; }[]; onChange: (option: SegmentedValue) => void; }' is missing the following properties from type 'Pick ': onResize, onResizeCapture

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 18.2.0 |
| System | MacOS 12.6 |
| Browser | Chrome 107.0.5304.110 |

---
API document doesn't mention about missing properties. I think it's out updated.
https://ant.design/components/segmented

**Comment by HuanxinHu** [comment]
same issue here

**Comment by s0ngyee** [comment]
with same issue

**Comment by afc163** [comment]
Please upgrade @types/react and @types/react-dom to latest version in your codesandbox: https://codesandbox.io/s/antd-custom-filter-ts-forked-9jn5x7?file=/index.tsx
