### ISSUE TITLE
5.0 版本无法在飞书浏览器中正常显示

### ISSUE THREAD

**Issue by zfben** [ant-design/ant-design#38908]
### Reproduction link

[https://ant.design](https://ant.design)

### Steps to reproduce

通过飞书浏览器或飞书开发者工具访问antd官网，会看到样式缺失

### What is expected?

样式完整

### What is actually happening?

样式缺失

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | 全系统 |
| Browser | 飞书浏览器及飞书开发者工具 |

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/38884#issuecomment-1324460458
