### ISSUE TITLE
Cannot build types because of module @/theme/interface from cssinjs

### ISSUE THREAD

**Issue by xrutayisire** [ant-design/ant-design#38904]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bug-antd-v5-cssinjs-9gdy09?file=/package.json)

### Steps to reproduce

1. Fork the [CodeSandBox](https://codesandbox.io/s/bug-antd-v5-cssinjs-9gdy09?file=/package.json)
2. Open a new terminal
3. Execute yarn tsc

### What is expected?

Types generated successfully

### What is actually happening?

Command crash with this output:

```
node_modules/@ant-design/cssinjs/lib/theme/createTheme.d.ts:2:48 - error TS2307: Cannot find module '@/theme/interface' or its corresponding type declarations.

2 import type { DerivativeFunc, TokenType } from '@/theme/interface';
                                                 ~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@ant-design/cssinjs/lib/theme/createTheme.d.ts:2
```

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | react 18.2.0 |
| System | OSX |
| Browser | Chrome |

---
Issue in antd cssinjs repo: https://github.com/ant-design/cssinjs/issues/55

**Comment by s0ngyee** [comment]
same issue

**Comment by xrutayisire** [comment]
Hi, can you update cssinjs version to have the fix in next antd release? Thanks :)
