### ISSUE TITLE
Getting Error While importing Comment Component from @ant-design/compatible

### ISSUE THREAD

**Issue by nishant23122000** [ant-design/ant-design#38905]
### Steps to reproduce

1. update antd to the latest 5.0.1 version
2. Change the import location of Comment from antd to @ant-design/compatible.

### What is expected?

it should not give a compile error

### What is actually happening?

When I upgrade antd to 5.0.1 and change the import location of Comment from `import { Comment } from antd` to `import { Comment } from @ant-design/compatible` I am getting the below error.

<img width="1277" alt="Screenshot 2022-11-23 at 2 36 14 PM" src="https://user-images.githubusercontent.com/53515714/203510223-b9927e12-4f69-4a14-a097-0b76de9ec894.png">

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | React |
| System | Macbook M1  |
| Browser | Chrome |

**Comment by avalladaresm** [comment]
@nishant23122000, I had a similar issue. I fixed it by changing the package import from `import { Comment } from "@ant-design/compatible"` to `import Comment from "@ant-design/compatible/lib/comment"`.

**Comment by zombieJ** [comment]
Seems same as prev export type as entity bug

**Comment by nishant23122000** [comment]
This is actually working if i start in https://u.ant.design/codesandbox-repro. Any reason ?
