### ISSUE TITLE
Upload 上传oss

### ISSUE THREAD

**Issue by Mluocheng** [ant-design/ant-design#38910]
### Reproduction link

[https://ant.design/components/upload-cn#components-upload-demo-upload-with-aliyun-oss](https://ant.design/components/upload-cn#components-upload-demo-upload-with-aliyun-oss)

### Steps to reproduce

官方demo

### What is expected?

data: getExtraData,不论怎么插入额外参数OSSAccessKeyId 结果都为underfined
![image](https://user-images.githubusercontent.com/31057183/203535240-9454e0c7-9c17-49c7-93f1-d4ed1eff73c1.png)
![image](https://user-images.githubusercontent.com/31057183/203535301-f59c3c43-9a0c-4714-96f5-91b48a631287.png)

### What is actually happening?

传入值

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.0 |
| System | win11 |
| Browser | chrome 107.0.5304.107（正式版本） （64 位 |

**Comment by afc163** [comment]
<img width="512" alt="图片" src="https://user-images.githubusercontent.com/507615/203696992-7d1b3da3-57e5-4f29-b132-fa50c806e452.png">
