### ISSUE TITLE
[Antd v5] support css-in-js in shadowdom 

### ISSUE THREAD

**Issue by noru** [ant-design/ant-design#38911]
### What problem does this feature solve?

Before v5, I can inject `antd/dist/antd.less` directly into the shadowdom root. How can I do the equivalent in v5?

Went through the document seems there're no related topics.

### What does the proposed API look like?

Something like:
```jsx
<ConfigProvider
  theme={
     container: <htmlelement>
  }
>
</ConfigProvider>

```

---

Workaround, partially works: 

```js
// first, import these 2 badboys
import { StyleProvider } from '@ant-design/cssinjs'
import Cache from '@ant-design/cssinjs/es/Cache'

// second, create custom Cache entity
class CustomCache extends Cache {
  override update(keys, valFn) {
    let path = keys.join('%')
    let prevValue = this.cache.get(path)!
    let nextValue = valFn(prevValue)
    let shadowRoot = container.getRootNode()
    let id = keys.join('-')
    let style = shadowRoot.getElementById(id)
    if (!style) {
      style = document.createElement('style')
      style.id = id
      container.appendChild(style)
    }
    style.innerText = nextValue
    super.update(keys,valFn)
  }
}

// lastly, give it to the StyleProvider
<StyleProvider cache={new CustomCache()}>
   <App />
</StyleProvider>
```

**Comment by MatrixAge** [comment]
+1

**Comment by zombieJ** [comment]
Could you help to provide a reproduce on this? I need check usage case. Thanks.

**Comment by noru** [comment]
> Could you help to provide a reproduce on this? I need check usage case. Thanks.

[![Edit admiring-poincare-dxw87m](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-poincare-dxw87m?fontsize=14&hidenavigation=1&theme=dark)

**Comment by noru** [comment]
@zombieJ https://github.com/ant-design/cssinjs/issues/60 may related to this. Would you please take a look? 🙏

**Comment by xs-ekram** [comment]
I am working on antd in WordPress + React using shadow dom. Where the styles tag of the antd is appending on head tag. But I want them to append in the shadow dom. I used the code from antd documentation but this is not working on my WordPress site. Here I am giving an example of my consoled element.

<head>
  <style data-rc-order="prependQueue" data-css-hash="b38o0g" data-token-hash="5unovc">
    :where(.css-z9xyz9)[class^="ant-drawer"],

    :where(.css-z9xyz9)[class^="ant-drawer"] [class^="ant-drawer"]::before,
    :where(.css-z9xyz9)[class*=" ant-drawer"] [class*=" ant-drawer"]::after {
      box-sizing: border-box;
    }

    :where(.css-z9xyz9).ant-drawer .ant-drawer-close {
      display: inline-block;
      margin-inline-end: 12px;
      color: rgba(0, 0, 0, 0.45);
      font-weight: 600;
      font-size: 16px;
      font-style: normal;
      line-height: 1;
    }
  </style>
  <style data-rc-order="prependQueue" data-css-hash="1vl0t8n" data-token-hash="5unovc">
    :where(.css-z9xyz9) a {
      color: #1677ff;
      text-decoration: none;
      background-color: transparent;
      outline: none;
      cursor: pointer;
      transition: color 0.3s;
      -webkit-text-decoration-skip: objects;
    }

    :where(.css-z9xyz9) a:hover {
      color: #69b1ff;
    }
  </style>
  <style data-rc-order="prependQueue" data-css-hash="ux9z8n" data-token-hash="5unovc">
    :where(.css-z9xyz9)[class^="ant-col"],
    :where(.css-z9xyz9)[class^="ant-col"]::before,
    :where(.css-z9xyz9)[class*=" ant-col"]::before,
    :where(.css-z9xyz9)[class^="ant-col"]::after,
    :where(.css-z9xyz9)[class*=" ant-col"]::after {
      box-sizing: border-box;
    }
  
  </style>

</head>

This style tag are appended here in the head tag. Do you know how I can add them in my shadow dom?

The js code that I used from antd official website.


import { StyleProvider, legacyLogicalPropertiesTransformer } from '@ant-design/cssinjs';
import { createRoot } from 'react-dom/client';

const shadowRoot = someEle.attachShadow({ mode: 'open' });
const container = document.createElement('div');
shadowRoot.appendChild(container);
const root = createRoot(container);

root.render(
  <StyleProvider container={shadowRoot} hashPriority="high" transformers={[legacyLogicalPropertiesTransformer]}>
    <MyApp />
  </StyleProvider>,
);

But still, the styles tag is appending in the head element. I am expecting to append them in my shadow dom.

**Comment by mb8z** [comment]
This was closed for some reason – @noru, have you maybe found another solution apart from the one you provided?

**Comment by xs-ekram** [comment]
Yes, I have found the solution. I just manipulate the dom. like window.shadow

**Comment by mb8z** [comment]
Took another try at this one – it's actually documented here:
https://ant.design/docs/react/compatible-style#shadow-dom-usage

I've done:

```js
import React from 'react';
import { ConfigProvider as AntdConfigProvider } from 'antd';
import { StyleProvider as AntdStyleProvider } from '@ant-design/cssinjs';
import enUS from 'antd/es/locale/en_US';

const container = myShadowRootHere;

const App = () => {
  return (
    <AntdStyleProvider container={container}>
      <AntdConfigProvider
        locale={enUS}
        theme={{
          token: {
            colorPrimary: '#000',
          },
        }}
      >
        {/* Rest of the code */}
      </AntdConfigProvider>
    </AntdStyleProvider>
  );
};
```

**Comment by PaulleDemon** [comment]
@mb8z It also doesn't work for select dropdown and tooltips as well

**Comment by PaulleDemon** [comment]
Nvm, I found the solution, by default dropdown and tooltips were being rendered in the DOM not ShadowDom

So do this

```js
<StyleProvider container={shadowRoot}>
	<ConfigProvider 
               getPopupContainer={() => shadowRootContainer} // important
		>
	    <App />
	</ConfigProvider>
</StyleProvider>
```

**Comment by Geczy** [comment]
```tsx
import '@ant-design/v5-patch-for-react-19';
import React from "react";
import { createRoot } from 'react-dom/client';
import "./index.css";
import reportWebVitals from "./reportWebVitals";
import App from './App';
import { StyleProvider } from '@ant-design/cssinjs';
import { ConfigProvider } from 'antd';

const host = document.createElement("div");
host.id = "react-chrome-content-script";
document.body.appendChild(host);

const shadowRoot = host.attachShadow({ mode: "open" });
const container = document.createElement("div");
shadowRoot.appendChild(container);

const root = createRoot(container);

root.render(
	<React.StrictMode>
		<StyleProvider container={shadowRoot}>
			<ConfigProvider
				getPopupContainer={() => shadowRoot as unknown as HTMLElement}
			>
				<App />
			</ConfigProvider>
		</StyleProvider>
	</React.StrictMode>
);

reportWebVitals();
```

Got it working thanks to the last comment! Added styleprovider container too though

**Comment by zhanzizhen** [comment]
It is now supported. The link is https://ant.design/docs/react/compatible-style#shadow-dom-usage.
