### ISSUE TITLE
tableBg or tableHeaderBg defined in TableToken Interface doesn't seem to be consumed

### ISSUE THREAD

**Issue by abhilashlr7** [ant-design/ant-design#38914]
### What problem does this feature solve?

Customise table header, and rows theme using these tokens.

### What does the proposed API look like?

`TableComponentToken extends TableToken`

**Comment by kiner-tang** [comment]
`tableBg` and `tableHeaderBg` had been consumed here.Is there something wrong with you?can you provide some example code and scenarios?

- https://github.com/ant-design/ant-design/blob/aae35a4d3cbe68e46c4174ca9cc1f2a7915281ba/components/table/style/index.tsx#L106
- https://github.com/ant-design/ant-design/blob/aae35a4d3cbe68e46c4174ca9cc1f2a7915281ba/components/table/style/index.tsx#L142

@abhilashlr7

**Comment by abhilashlr7** [comment]
> `tableBg` and `tableHeaderBg` had been consumed here.Is there something wrong with you?can you provide some example code and scenarios?
> 
>     * https://github.com/ant-design/ant-design/blob/aae35a4d3cbe68e46c4174ca9cc1f2a7915281ba/components/table/style/index.tsx#L106
> 
>     * https://github.com/ant-design/ant-design/blob/aae35a4d3cbe68e46c4174ca9cc1f2a7915281ba/components/table/style/index.tsx#L142
> 
> 
> @abhilashlr7

@kiner-tang: Try adding `tableHeaderBg` in the theme for Antd Config provider and see if that works for you? If yes, can you share what makes it work for you?

**Comment by kiner-tang** [comment]
> > `tableBg` and `tableHeaderBg` had been consumed here.Is there something wrong with you?can you provide some example code and scenarios?
> > ```
> > * https://github.com/ant-design/ant-design/blob/aae35a4d3cbe68e46c4174ca9cc1f2a7915281ba/components/table/style/index.tsx#L106
> > 
> > * https://github.com/ant-design/ant-design/blob/aae35a4d3cbe68e46c4174ca9cc1f2a7915281ba/components/table/style/index.tsx#L142
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @abhilashlr7
> 
> @kiner-tang: Try adding `tableHeaderBg` in the theme for Antd Config provider and see if that works for you? If yes, can you share what makes it work for you?

Yes, I see what you mean. Let me see what went wrong

**Comment by kiner-tang** [comment]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/10286961/204422870-6bbd98d7-7bf1-475f-b8a7-81c5e70c4419.png">

![image](https://user-images.githubusercontent.com/10286961/204423442-84849c86-b4c1-4caf-a1f5-fa9e364cce93.png)


![image](https://user-images.githubusercontent.com/10286961/204423298-3881c747-1d3c-4cfd-92aa-737ae2388ef3.png)

![image](https://user-images.githubusercontent.com/10286961/204423321-e699dfdb-2a05-4a79-a13f-528e5cc2be5c.png)

What is the purpose of 'CommonToken'? If we want better type hints in 'ConfigProvider', wouldn't it be better to use 'TableToken'?
@afc163

**Comment by zombieJ** [comment]
`TableToken` is internal interface which can not access by outer. Currently Table's ComponentToken is empty but we do have plan to add.

**Comment by kiner-tang** [comment]
> `TableToken` is internal interface which can not access by outer. Currently Table's ComponentToken is empty but we do have plan to add.

When will the plan be launched? Which 'tokens' should be add into the common 'tokens'? May I add some table's 'token' to 'commonToken' to solve this problem?
@zombieJ

**Comment by zombieJ** [comment]
Merge into #38975
