### ISSUE TITLE
input组件

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#3891]
- antd 版本: 15 
- 操作系统及其版本: mac os
- 浏览器及其版本: chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

input如果加上校验检查后，后面的图标会遮挡一部分文字，在input很短的情况下，甚至无法输入值。
另外，就算不让校验显示校验图标，也是无法录入，感觉图标隐藏起来并挡住了位置。

![image](https://cloud.githubusercontent.com/assets/23185348/20381775/e3e977d8-ace3-11e6-8401-cc922c4887ad.png)

**Comment by afc163** [comment]
关掉校验图标。 `hasFeedback={false}`

**Comment by bf185003** [comment]
关掉校验图标也不行，还是点击不下去。

**Comment by afc163** [comment]
我看看。

**Comment by afc163** [comment]
我试了一下，在 `antd@1.11.2` 下，`hasFeedback={false}` 之后，图标那里的 dom 元素直接去掉了。

我不确定到底是什么挡住了你的输入框，建议你在控制台中查看一下。

另外，你使用 antd 版本是多少，我们没有 15 这个版本。

**Comment by afc163** [comment]
不过，出现图标的时候确实不应该挤压和挡住，这个我修正一下。
