### ISSUE TITLE
table导航问题

### ISSUE THREAD

**Issue by zhouchunguang2020** [ant-design/ant-design#38927]
### Reproduction link

[https://ant.design/components/table-cn](https://ant.design/components/table-cn)

### Steps to reproduce

随意点击table的导航，不会定位到点击想要导航的位置

### What is expected?

导航位置正确

### What is actually happening?

导航位置错误

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18 |
| System | window |
| Browser | google |

---
很容易复现

**Comment by afc163** [comment]
@PeachScript 看看这个问题

**Comment by zhouchunguang2020** [comment]
form表单也存在类似问题

**Comment by zhouchunguang2020** [comment]
[antd-table.webm](https://user-images.githubusercontent.com/68039784/203679958-f8221b44-f631-4b91-bac8-1be64f5348cc.webm)

**Comment by zhouchunguang2020** [comment]
@MadCcc

**Comment by afc163** [comment]
而且会卡顿，有时还会白屏一下

**Comment by PeachScript** [comment]
原因是 dumi 的锚点跳转和 antd 的锚点跳转冲突导致的，dumi@2.0.6 已修复该问题，自定义主题时不再处理锚点跳转，应该重新部署就能修复 cc @MadCcc
