### ISSUE TITLE
文档 连接 404

### ISSUE THREAD

**Issue by wkylin** [ant-design/ant-design#38924]
### Reproduction link

[https://ant.design/docs/react/customize-theme-v5-cn](https://ant.design/docs/react/customize-theme-v5-cn)

### Steps to reproduce

https://ant.design/docs/react/customize-theme-v5-cn

### What is expected?

https://ant.design/docs/react/customize-theme-cn

### What is actually happening?

https://ant.design/docs/react/customize-theme-v5-cn

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
你在哪看到这个链接的，应该是 https://ant.design/docs/react/customize-theme-cn
