### ISSUE TITLE
input组件问题

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#3892]
antd 版本: 15
操作系统及其版本: mac os
浏览器及其版本: chrome
您做了什么？请提供尽可能详细的重现步骤。

input如果加上校验检查后，后面的图标会遮挡一部分文字，在input很短的情况下，甚至无法输入值。
另外，就算不让校验显示校验图标，也是无法录入，感觉图标隐藏起来并挡住了位置。

补充一下，关掉校验图标，虽然看不到图标了，但是图标的那个位置还是点不下去。

![image](https://cloud.githubusercontent.com/assets/23185348/20382591/748973e4-ace7-11e6-98ee-3e9d742f3934.png)

**Comment by afc163** [comment]
在 https://github.com/ant-design/ant-design/issues/3891 里继续讨论就好。
