### ISSUE TITLE
Tooltip does not work with HOC button (when the button disabled)

### ISSUE THREAD

**Issue by yogjin** [ant-design/ant-design#38932]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-clarke-nnbfhl)

### Steps to reproduce

mouse up on the disabled wrapped button

### What is expected?

Tooltip should be visible even if disabled hoc button is used

### What is actually happening?

Tooltip is not visible

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | Chrome |

---
I think we can solve it if we fix [this function](https://github.com/ant-design/ant-design/blob/6aa8002f60fdf49c2d175ea0dfc3e5750df95062/components/tooltip/index.tsx#L117)

I tried to solve this problem using Object.setPrototypeOf(WrappedButton, Button), but i think this is not proper way to solve.

**Comment by afc163** [comment]
```
(WrappedButton as any).__ANT_BUTTON = true;
```

https://codesandbox.io/s/misty-haze-23y58p?file=/src/App.tsx:177-221

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9581#issuecomment-374113785
