### ISSUE TITLE
Tooltip is laggy in iframe (v5)

### ISSUE THREAD

**Issue by luc-hn** [ant-design/ant-design#38940]
### Reproduction link

[https://drive.google.com/file/d/1ywxH1d7fsjVjD0qHJM8yzDrUHVEYv7P-/view](https://drive.google.com/file/d/1ywxH1d7fsjVjD0qHJM8yzDrUHVEYv7P-/view)

### Steps to reproduce

Implement tooltip in an iframe

### What is expected?

Should be smooth like v4

### What is actually happening?

 It takes 1-2 seconds to open and close tooltip

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 17.0.2 |
| System | Window |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Please provide minized reproduction with CodeSandbox to help us debug.
