### ISSUE TITLE
Form表单中.ant-form-item中的margin-bottom改小后 在进行validateFields校验 rules必填项的判断动画卡顿

### ISSUE THREAD

**Issue by zhengxdlol** [ant-design/ant-design#38947]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lbto62?file=/index.css)

### Steps to reproduce

上面链接是你们官网Form的代码
Form表单中.ant-form-item中的margin-bottom改小后 在进行validateFields校验 rules必填项的判断动画卡顿
添加.ant-form-item {
  margin-bottom: 8px;
}的样式后
在进行required判断后会出现卡顿
先出现message提示后在将margin变大

### What is expected?

和4.x一样 同时进行

### What is actually happening?

5.x和4.x效果不一样

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | ^17.0.2 |
| System | win 10 |
| Browser | Chrome 107.0.5304.107 |

**Comment by zhengxdlol** [comment]
import { EditableProTable } from '@ant-design/pro-components';
EditableProTable 中的required也是有卡顿的现象

**Comment by zombieJ** [comment]
看起来是动画丢失了
