### ISSUE TITLE
Page-header component is missing in latest version

### ISSUE THREAD

**Issue by anjaneyuluk-mls** [ant-design/ant-design#38949]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js)

### Steps to reproduce

just import PageHeader

### What is expected?

should be able to use PageHeader

### What is actually happening?

PageHeader is not present in code base

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | mac OS monetary |
| Browser | chrome |

**Comment by li-jia-nan** [comment]
- [https://ant.design/docs/react/migration-v5](https://ant.design/docs/react/migration-v5)
