### ISSUE TITLE
getFieldProps 传name的时候最多只能分两级

### ISSUE THREAD

**Issue by 275287902** [ant-design/ant-design#3894]
#### 发生问题的环境是：

- antd 版本: 1.11.2
- 操作系统及其版本: macOs Sierra 10.12.1 (16B2555)
- 浏览器及其版本: chrome 版本 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。
```
<Input {...getFieldProps('obj.a.b')} />
....
{...getFieldsValue()} // obj: {a.b:value}
```
#### 您期待的结果是:
<Input {...getFieldProps('obj.a.b')} />
....
{...getFieldsValue()} // obj: {a: {b:value}}
```
#### 实际上的结果是:
```
<Input {...getFieldProps('obj.a.b')} />
....
{...getFieldsValue()} // obj: {a.b:value}
```

#### 可重现的在线演示

http://codepen.io/tl/pen/JbbGwM

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/2965
