### ISSUE TITLE
[Select] Fix/Improve types (and document) to show how to build option groups via `options` prop

### ISSUE THREAD

**Issue by yifanwww** [ant-design/ant-design#38955]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-knpmnb?file=/index.js)

### Steps to reproduce

Open the codesandbox link, wait for the rendering, and you will see that there are three Selects on the right.

### What is expected?

It's an issue about inconsistency between behaviour and type (and document, see additional comments).

```ts
export interface BaseOptionType {
  disabled?: boolean;
  [name: string]: any;
}

export interface DefaultOptionType extends BaseOptionType {
  label: React.ReactNode;
  value?: string | number | null;
  children?: Omit<DefaultOptionType, 'children'>[];
}
```

`DefaultOptionType` **may** indicate that when we are using `options` prop, if we want to build option groups we should use `{children}` field. But as what codesandbox shows, we actually should use `{options}` field.

This is inconsistent.

**What is expected is that the type and the behaviour should be consistent. (at least when we don't customize `fieldNames`)**

### What is actually happening?

In the codesandbox, you can find the option groups in the dropdown of `via OptGroup` and `via {options} field`, but cannot find that in `via {children} field`.

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 17.0.2 |
| System | MacOS 11.7.1 |
| Browser | Chrome 107.0.5304.110 |

---

### Additional Comments

I know that we can change `fieldNames` to decide how `options` should look like. But I knew this by reading the source code and found [code](https://github.com/react-component/select/blob/v14.1.14/src/utils/valueUtil.ts#L79).

It's really hard to understand that we should use `{options}` field *by default* if we don't read the source code:
- in document [select](https://ant.design/components/select)
  - there is no such example showing how to use `{options}` field to build option groups
  - there is no such example showing how we can change `fieldNames` to support customized `options`
  - the description of `fieldNames` is a little bit simple
- we cannot find anything that indicates we should use `{options}` field *by default* from the provided type definitions

**Comment by zombieJ** [comment]
Since we recommend data driven instead of syntactic sugar, change demo with data driven version seems make sence.
