### ISSUE TITLE
image组件放在Drawer抽屉里预览不展示顶部工具栏和其他icon

### ISSUE THREAD

**Issue by yizhifeimao** [ant-design/ant-design#38958]
### Reproduction link

[https://暂无](https://暂无)

### Steps to reproduce

<Drawer title="Basic Drawer" placement="right" onClose={onClose} open={open} >
        <Image.PreviewGroup >
          {arr.map((item) => {
            return <Image key={item.url} src={item.url} width={80} height={80} />;
          })}
        </Image.PreviewGroup>
      </Drawer> 

### What is expected?

image组件放在Drawer抽屉里预览展示顶部工具栏和其他icon

### What is actually happening?

image组件放在Drawer抽屉里预览不展示顶部工具栏和其他icon

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | 4.24.3 |
| Browser | Chrome  107.0.5304.110 |

**Comment by yizhifeimao** [comment]
Steps to reproduce
<Drawer title="Basic Drawer" placement="right" onClose={onClose} open={open} >
        <Image.PreviewGroup >
          {arr.map((item) => {
            return <Image key={item.url} src={item.url} width={80} height={80} />;
          })}
        </Image.PreviewGroup>
      </Drawer>

**Comment by IvenBao** [comment]
这里有个简单的例子，不过是在modal中使用Image的预览功能时，PreviewGroup中的默认icons都消失了
https://codesandbox.io/s/imagezu-jian-yu-lan-wen-ti-antd-4-24-3-forked-gntwk4?file=/demo.tsx:244-276

**Comment by afc163** [comment]
4.24.3 ❌：https://codesandbox.io/s/imagezu-jian-yu-lan-wen-ti-antd-4-24-3-forked-2b82ev?file=/package.json
4.24.1 ✅：https://codesandbox.io/s/imagezu-jian-yu-lan-wen-ti-antd-4-24-3-forked-gntwk4?file=/demo.tsx:244-276

**Comment by afc163** [comment]
@JarvisArt
