### ISSUE TITLE
List.Item.Meta title validateDOMNesting warning

### ISSUE THREAD

**Issue by khetho** [ant-design/ant-design#38953]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/and-list-item-meta-title-validatedomnesting-issue-9rlrq1)

### Steps to reproduce

Create a List as per the example of the Vertical List (https://ant.design/components/list). Include at least one List.Item which must contain at least one List.Item.Meta item which specifies a title attribute. For the title pass in a Antd Title node (from Typography) with level 3. Provide any text you like for the title itself.

### What is expected?

My list item will render with the Meta title rendered at my expected header level h3 without any browser errors or warnings.

### What is actually happening?

The Meta title is rendered at the expected level h3. However there is a browser warning "Warning: validateDOMNesting(...): \<h3\> cannot appear as a child of \<h4\>." Looking at the rendered code there and includes an enclosing h4 around the node passed in through the title attribute

| Environment | Info |
| --- | --- |
| antd | 4.23.2 |
| React | 18.1.0 |
| System | Mac OS Ventura |
| Browser | Chrome 107.0.5304.110 |

**Comment by afc163** [comment]
I can't reproduce in your codesandbox, anything I miss?
