### ISSUE TITLE
Add two documentation in side bar

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3895]
- [x] [customize theme](https://github.com/ant-design/antd-init/) @afc163
- [ ] [internationalization](https://github.com/ant-design/intl-example) @benjycui

**Comment by benjycui** [comment]
先解决问题。。 https://github.com/ant-design/ant-design/commit/59f0e6254bb065f7d8829abe2bba7f42ef4aa861

**Comment by afc163** [comment]
改成这个链接？https://github.com/ant-design/intl-example/blob/master/docs/understanding-antd-i18n.md

**Comment by benjycui** [comment]
intl 下面的文档其实不止一个。。需要时间梳理。
