### ISSUE TITLE
Incorrect option passed to onSelect in AutoComplete 

### ISSUE THREAD

**Issue by peterlacko** [ant-design/ant-design#38951]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-antd-5-0-1-forked-8n47fd?file=/demo.tsx)

### Steps to reproduce

1. Click to input, dropdown opens;
2. Click on first option;
3. Click to input again;
4. Click on second option;
5. Observe console output

### What is expected?

After first click, option with 'key: "id1"' should be passed to onSelect. After second click, option with 'key: "id2"' should be passed to onSelect

### What is actually happening?

Same option is passed to onSelect (id3) regardless which option I select.

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.0.0 |
| System | Windows 11 |
| Browser | latest Firefox, Chrome |

---
Issue only happens when "value" prop is same for some options. I can not pass "options" prop since additional formatting is needed as in example. I can not pass unique id as a value since backfill with correct value is a must.

**Comment by IonelLupu** [comment]
hey @peterlacko . I have the exact same problem. Passing options with the same `value` but different keys always returns the last option in list.


Here is some code that replicates the problem:

```
<AutoComplete
	options={
		[...Array(3)].map((_, index) => ({
			value: 'some item',
			key: index,
			label: `item ${index + 1}`
		}))
	}
	placeholder="input here"
	style={{width: '200px'}}
	onSelect={(value: string, option: DefaultOptionType) => {console.log('option ->', value, option)}}
/>
``` 

Upon selecting any option, the log always prints the last option from the list.

**Comment by zombieJ** [comment]
Do not pass option with same `value`. For control mode, component do not get which option should be active. So we do not handle this with uncontrol mode also.

**Comment by IonelLupu** [comment]
@zombieJ Take a look at this example: 
![image](https://user-images.githubusercontent.com/4083652/217741305-e08f6a72-09e1-49b7-be06-e433254f4c05.png)

When searching for London, the API returns 4 different London locations. They have the same name, but they don't have the same geophysical location. I show the users it's London and underneath I show them the actual location. The users see there are clearly different locations but `Autocomplete` always returns the last one 😢. 

Isn't possible to make the `Autocomplete` component identify the option based on the key instead of the value?

**Comment by peterlacko** [comment]
Thanks for another example @IonelLupu. Using `value` as a key, when `key` is provided not sign of a good design I think. For now we "hacked" this by appending whitespaces to the value but obviously it's not ideal solution.

**Comment by IonelLupu** [comment]
@peterlacko 

We use the location ID as the key, which is the ID from the database. Something like:

```
options={(locations.map(location => ({
    label: location.name + "some more complex jsx", // this is used in the list of options
    value: location.name, // this is used to fill in the input once a list item was selected
    key: location.id, // this is what we send to the backend side
}))}
```

Also, if we set `value: location.id`, we get the actual ID in the input while we want the label:
![image](https://user-images.githubusercontent.com/4083652/217809921-b16dd1b9-d653-41f0-ae63-e373af8f0449.png)

How can we handle this use case? Is there a way to customise what goes in the input? I tried `value={locations.find(item => item.id === form.locationId)?.name}` but it doesn't do anything. ('form' is just an object that holds what the user selected). All the inputs are inside a <Form>

**Comment by peterlacko** [comment]
@IonelLupu we render options like this: `<AntAutoComplete.Option key={suggestion.key} value={suggestion.text + uniqueWhitespace}>`, where uniqueWhitespace is string composed of whitespaces with variable length. So in your case we would set values to 'London', 'London ', 'London  ' and so on. Backfilled values are thus same: 'London', 'London ' and 'London  '. We also tried to use non printable characters but in input you'll get their utf codes.

**Comment by IonelLupu** [comment]
@peterlacko that's an interesting hack. But I think I will stick with my solution with adding an onClick listener on the label. Still not ideal but it will do the job for now 😢
