### ISSUE TITLE
[Input.Group] White border present in dark mode

### ISSUE THREAD

**Issue by GuichiZhao** [ant-design/ant-design#38954]
### Reproduction link

[https://ant.design/components/input](https://ant.design/components/input)

### Steps to reproduce

Add a Input.Group component, switch to dark mode and see what happen

### What is expected?

NO white border
![Screenshot from 2022-11-24 17-03-34](https://user-images.githubusercontent.com/12082547/203740639-4000f2ed-e870-4c80-9cc4-010570ef5546.png)
![Screenshot from 2022-11-24 17-03-41](https://user-images.githubusercontent.com/12082547/203740657-181ab92a-343d-4e05-acc9-33b002862636.png)

### What is actually happening?

Border is white

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
In which demo could we reproduce this problem?

**Comment by GuichiZhao** [comment]
If the dark mode is support by antd5 officially,  I suppose it is better to support dark mode in the doc page.
The broken style should be more obvious by doing this

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/203916159-da730ed0-16de-4537-bb4e-50abead15101.png)
It seems to be okay in dark theme. Could you provide a repoduction with your code in CodeSandbox?

**Comment by GuichiZhao** [comment]
When I switch off  `border-inline-end-width` the white border disappear

![Screenshot from 2022-11-25 14-46-06](https://user-images.githubusercontent.com/12082547/203917898-3e9041b2-2fbc-41e1-9f62-628b5c89a75a.png)
![Screenshot from 2022-11-25 14-46-18](https://user-images.githubusercontent.com/12082547/203917907-319adb5b-8a4f-40cf-af58-431f4785234f.png)

I will create a new project now

**Comment by GuichiZhao** [comment]
![Screenshot from 2022-11-25 15-31-06](https://user-images.githubusercontent.com/12082547/203925692-c40e3c1e-f7a7-4839-9643-b60db6394b52.png)
I tried my best to reproduce,but I can.  Here is the process:
I notice that the cause is `border-inline-end-with`, so I increase it to `40px` to make it more visible, Notice that I my setting, the border with apply to both `.ant-select` (red)  and `.antd-select-selector` (yellow) 

I there "correct" setting 
 
![Screenshot from 2022-11-25 15-38-29](https://user-images.githubusercontent.com/12082547/203926864-206d22f4-90d6-479a-ab67-7bd556616082.png)
`border-inline-end-with` is also applied to  `.ant-select` (red) and `.antd-select-selector` (yellow) , but for some reason I can not understand, the `border-inline-end-with` has no visual effect at `.ant-select` (red) 
![Screenshot from 2022-11-25 15-42-11](https://user-images.githubusercontent.com/12082547/203927278-a1ec0fc4-70fe-414b-8429-f01610ddacdc.png)
Why the computed when is `40px` but it is rendered as `0` ?

**Comment by GuichiZhao** [comment]
![Screenshot from 2022-11-25 15-52-36](https://user-images.githubusercontent.com/12082547/203929480-67019ef8-e616-4249-a5d5-225ac6218397.png)
The picture above is the "buggy" one, but at least it `40px` make sense to me,


![Screenshot from 2022-11-25 15-52-20](https://user-images.githubusercontent.com/12082547/203929656-9eb11434-a4ac-46c2-b8a3-674e78802f33.png)
While it the the "correct" one, But it is totally beyond my expectation, could you guys tell me what kind of magic you play to make the `border-inline-end-with` rendered as 0 giving the correct visual effect?

**Comment by GuichiZhao** [comment]
Finally I know the answer, the case it

```
/*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/

*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
}
```

This is from https://unpkg.com/tailwindcss@3.2.4/src/css/preflight.css 
which is required by https://tailwindcss.com/docs/preflight

I suppose antd already did some kind of normalization already, maybe it is a bad idea to introduce another one

By the way 

```
button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}

```
In the preflight.css will also break the antd style

**Comment by MadCcc** [comment]
Ref: https://github.com/ant-design/ant-design/issues/38794#issuecomment-1328262525
