### ISSUE TITLE
Badge `showZero` does not work in combination with custom `color`

### ISSUE THREAD

**Issue by nightvisi0n** [ant-design/ant-design#38965]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cfo53o?file=/index.js)

### Steps to reproduce

Please refer to reproduction link.

### What is expected?

I expect to get a `Badge` with a custom color showing `0`.

### What is actually happening?

A custom colored badge without any number.

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.2.0 |
| System | macOS Monterey 12.5.1 (21G83) |
| Browser | Google Chrome 107.0.5304.110 |

**Comment by Wxh16144** [comment]
我来看看这个问题~
