### ISSUE TITLE
`defaultExpandAllRows: true` doesn't works with asynchronous dataSource

### ISSUE THREAD

**Issue by turdiyev** [ant-design/ant-design#38960]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/defaultexpandallrows-antd-table-forked-134g3h)

### Steps to reproduce

1) initial state: `dataSource = []. expandable={defaultExpandAllRows:true}` and component starts fetching data from server and table loading is true
2) Then after data comes, `dataSource` is not empty know and `loading` is false. 

You can see reproduction link. 

### What is expected?

defaultExpandAllRows should be works for asyncron dataSource

### What is actually happening?

doesn't expanded

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18 |
| System | Linux, Windows |
| Browser | Chrome latest |

**Comment by MadCcc** [comment]
`defaultExpandAllRows` only works for component mount, you need to set `expandedRowKeys` manually when async data is rdy。

**Comment by turdiyev** [comment]
@MadCcc I didn't know about that, thank you!
