### ISSUE TITLE
 It is not possible to control the size of the typed text when selecting the showSeach option in Select

### ISSUE THREAD

**Issue by RafaelCss** [ant-design/ant-design#38972]
### Reproduction link

[https://ant.design/components/select](https://ant.design/components/select)

### Steps to reproduce

Control the number of characters typed

### What is expected?

Control the number of characters typed

### What is actually happening?

How do I control input length in select with showSeach?

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | React 18 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Use `searchValue` & `onSearch` to litmit input size.
