### ISSUE TITLE
Expose Layout tokens to ConfigProvider

### ISSUE THREAD

**Issue by khalibloo** [ant-design/ant-design#38970]
### What problem does this feature solve?

Internally, the Layout component has tokens such as `layoutFooterPadding` and so on. But these are not available to customize in ConfigProvider.

### What does the proposed API look like?

`<ConfigProvider theme={{components: {Layout: {layoutFooterPadding: 0}}}} />`

**Comment by MadCcc** [comment]
Trace in https://github.com/ant-design/ant-design/issues/38975
