### ISSUE TITLE
表单验证全局提示信息以及自定义提示信息

### ISSUE THREAD

**Issue by yuriwxc** [ant-design/ant-design#3897]
#### 发生问题的环境是：

- antd 版本: 2.4.3
- 操作系统及其版本: win10
- 浏览器及其版本: chrome 54.0.2840.99 m

#### 您做了什么？请提供尽可能详细的重现步骤。

使用antd Form组件, 像demo一样定义验证信息没有问题
rules: [{ required: true, message: 'Please input your username!'}]
需求一: 定义多个验证条件, 提示不同的错误信息
rules: [{ required: true,min:6, message: '请输入用户名!'}]

需求二: 定义多个验证条件,使用全局默认提示信息,并能够自定义全局提示信息
rules: [{ required: true,min:6}]

需求三: 用户是否存在异步校验怎么处理? 希望提供官方demo 
#### 您期待的结果是:
需求一:  没填写时提示: 请输入用户名!
              输入过长时提示: 您输入的用户名不能少于6位!
需求二:  没填写时提示: 该属性不能为空!
              输入过短时提示:  该属性不能少于6位字符!

#### 实际上的结果是:
需求一:  错误时永远提示: 请输入用户名!
需求二:  没填写时提示: userName is required
              输入过短时提示:  userName must be at least 6 characters

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
尽力了，还是看不懂，麻烦提供重现 demo

**Comment by somewhereMrli** [comment]
表单验证全局提示信息默认设置入口
