### ISSUE TITLE
antd table 进行列筛选时后，更新 columns, datasource， 导致页面显示错误

### ISSUE THREAD

**Issue by moling1234** [ant-design/ant-design#38978]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shai-xuan-he-pai-xu-antd-5-0-1-forked-3crfdv?file=/demo.tsx)

### Steps to reproduce

1: 选择 Name \ Address 列进行筛选（这时是正确的）
2: 再点击 refresh ，页面显示无数据（这时是错的）

### What is expected?

期望在点击  refresh 后，页面显示 name1 列，并显示4行数据

### What is actually happening?

有 name1 列，但是没有数据

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.0.0 |
| System | mac |
| Browser | chrome 版本 107.0.5304.110（正式版本） (x86_64) |

---
1: 在不进行列筛选，直接点击 refresh，显示是正确的
2: 经调试，原因是 filters 会被缓存
3: 期望在 columns 发生修改，清空 filters

**Comment by moling1234** [comment]
> ### You may look for issues:
> 1. 56% [Table Columns can't have dynamic filters #37962](https://github.com/ant-design/ant-design/issues/37962)
> 2. 56% [How to render Radio in a table column antd #27947](https://github.com/ant-design/ant-design/issues/27947)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

**Comment by moling1234** [comment]
> ### You may look for issues:
> 1. 56% [Table Columns can't have dynamic filters #37962](https://github.com/ant-design/ant-design/issues/37962)
> 2. 56% [How to render Radio in a table column antd #27947](https://github.com/ant-design/ant-design/issues/27947)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

那些解决方式解决不了这个问题

**Comment by yoyo837** [comment]
机器人留言是匹配相似issue, 不是解决方案.

**Comment by moling1234** [comment]
> 机器人留言是匹配相似issue, 不是解决方案.

我知道，我只是回应一下，以上方案解决不了我的问题，然后有人来看

**Comment by moling1234** [comment]
> 来个用例？

https://codesandbox.io/s/shai-xuan-he-pai-xu-antd-5-0-1-forked-3crfdv?file=/demo.tsx``

**Comment by moling1234** [comment]
thank you very much
