### ISSUE TITLE
Menu 菜单 使用了openKeys属性无法展开二级菜单

### ISSUE THREAD

**Issue by frontend-winter** [ant-design/ant-design#38984]
### Reproduction link

[https://github.com/react-component/menu/issues/556](https://github.com/react-component/menu/issues/556)

### Steps to reproduce

<Menu
        theme="dark"
        mode="inline"
        items={items}
        openKeys={[]}
/>

### What is expected?

Menu 菜单 使用了openKeys属性可以展开二级菜单

### What is actually happening?

Menu 菜单 使用了openKeys属性可以展开二级菜单

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | ^18.2.0 |
| System | Mac os |
| Browser | Chrome 最新版本 |

**Comment by afc163** [comment]
See https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-inputselect-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86
