### ISSUE TITLE
组件总览

### ISSUE THREAD

**Issue by 1746196052** [ant-design/ant-design#38983]
### Reproduction link

[https://ant.design/components/overview-cn](https://ant.design/components/overview-cn)

### Steps to reproduce

选择版本号4.x

### What is expected?

跳转4.x版本的api

### What is actually happening?

5.x的api

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | react 18.2.0 |
| System | windows |
| Browser | chrome |

**Comment by MadCcc** [comment]
具体什么问题？

**Comment by 1746196052** [comment]
选择4.x版本 进去还是5.0.1版本






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 下午2:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 组件总览 (Issue #38983)





 
具体什么问题？

**Comment by 1746196052** [comment]
直接4.x就404




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 下午2:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 组件总览 (Issue #38983)





 
具体什么问题？

**Comment by MadCcc** [comment]
是说国内镜像跳转么

**Comment by 1746196052** [comment]
版本号跳转




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 组件总览 (Issue #38983)





 
是说国内镜像跳转么

**Comment by 1746196052** [comment]
先进3.x版本 再进4.x版本就进到5.0.1的版本api




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 组件总览 (Issue #38983)





 
是说国内镜像跳转么

**Comment by MadCcc** [comment]
3.x 的官网已经不维护了，4.x 在主站没有复现到 404 问题，镜像之间的跳转确实有问题，已修复：https://github.com/ant-design/ant-design/commit/1f0fbd4dcff90f89b8baa9b8f4184f2489fe0593
