### ISSUE TITLE
抓到一只 Badge 的 bug

### ISSUE THREAD

**Issue by leejaen** [ant-design/ant-design#3898]
![image](https://cloud.githubusercontent.com/assets/1638970/20415048/c79f3328-ad70-11e6-8243-fa6ea19dcbfd.png)
![image](https://cloud.githubusercontent.com/assets/1638970/20415076/f7e0da00-ad70-11e6-811c-81eb08d9108d.png)
怀疑是CSS问题。
演示地址：http://codepen.io/leejaen/pen/NbbLwm

**Comment by anlia260** [comment]
因为badge的作用就是用来提醒的，层级设置很高是能理解的，你这种场景我也同样遇到过，框架只能提供基础的，这种需要自己可以fix的。

**Comment by afc163** [comment]
确实没必要设高度。
