### ISSUE TITLE
自定义 disabled Button，Popover 无法打开

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#38980]
### Reproduction link

[https://stackblitz.com/edit/react-kaqyfj?file=demo.tsx](https://stackblitz.com/edit/react-kaqyfj?file=demo.tsx)

### Steps to reproduce

Hover me 2 

### What is expected?

显示 popover

### What is actually happening?

没有显示 popover

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/38932#issuecomment-1325954065

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9581#issuecomment-374113785

**Comment by crazyair** [comment]
我修改了示例，为什么还不行

**Comment by afc163** [comment]
```diff
const Button2 = (props: any) => {
  return <Button {...props} />;
};

+ (Button2 as any).__ANT_BUTTON = true;
```

**Comment by crazyair** [comment]
Tooltip 里面能先获取 Component.children.__ANT_BUTTON 吗？

**Comment by afc163** [comment]
封装是不可控的，这样查是不稳定的。

**Comment by crazyair** [comment]
我发现还有个问题，Popover 会给 children props 注入 `className:null; style:pointerEvents: 'none'`?

**Comment by crazyair** [comment]
虽然最终渲染的 button 有 class，但是为什么要把 props 的 className 改成 null

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21404

**Comment by crazyair** [comment]
```tsx
<Popover content="content">
    <Input disabled />
</Popover>
```
input 是不是也需要 hover 显示，目前没有支持
<img width="750" alt="image" src="https://user-images.githubusercontent.com/7971419/203936871-6d3117e0-8282-4269-9dcc-e270792883c1.png">

**Comment by crazyair** [comment]
能不能 Tooltip 加个属性，是否要报错个 span，并且在 Tooltip 加个 FAQ
