### ISSUE TITLE
[Select] The values of Select in mode multiple is working incorrect

### ISSUE THREAD

**Issue by caocuong2404** [ant-design/ant-design#38985]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/custom-dropdown-bugs-antd-5-0-1-forked-ovzo5g?file=/demo.tsx)

### Steps to reproduce

The selected values of Select component in `mode='multiple'` was deleted when deleting the values of the input box inside the custom dropdown component
---
- Use Select component with mode='multiple'
- Custom dropdown with input box inside the custom component
- Select some value
- Enter the name of the item and delete them.
- Bug is throwing

### What is expected?

Not deleting the value is selected

### What is actually happening?

Is deleting the values was selected

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | React v17, v18 |
| System | MacOS, Windows, Linux |
| Browser | Chrome, Brave, Safari |

---
I have fixed the bug on the pull request of the `rc-select`. Please review it and merge
https://github.com/react-component/select/pull/835

**Comment by zombieJ** [comment]
Use `stopPropagation` for block event bubble.
