### ISSUE TITLE
Form.Item组件为RangePicker，设置initialValue，时间不停刷新

### ISSUE THREAD

**Issue by BeiMeng1998** [ant-design/ant-design#38992]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shi-jian-lei-kong-jian-antd-5-0-1-forked-uly3u2?file=/demo.tsx)

### Steps to reproduce

https://uly3u2.csb.app/

### What is expected?

初始时间不变

### What is actually happening?

时间不停刷新

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
v5 换成 dayjs 了：
https://codesandbox.io/s/shi-jian-lei-kong-jian-antd-5-0-1-forked-xnwfro?file=/demo.tsx
