### ISSUE TITLE
Calendar 组件能否支持 range 选择时间段

### ISSUE THREAD

**Issue by MircoSans** [ant-design/ant-design#38996]
### What problem does this feature solve?

能够选择时间段

### What does the proposed API look like?

```jsx
<Calendar mode="range"/>
```
<img width="270" alt="image" src="https://user-images.githubusercontent.com/51395487/203958090-bac92ffe-e132-4819-af05-0e32aa8e88da.png">

**Comment by afc163** [comment]
Merged to #40051
