### ISSUE TITLE
Docs: Antd Table render function first parameter is wrong

### ISSUE THREAD

**Issue by anjantalatam** [ant-design/ant-design#38998]
### Reproduction link

[https://ant.design/components/table](https://ant.design/components/table)

### Steps to reproduce

1. Open the reproducible link.
2. Check the type ( 3rd Column ) of render function in Table Column API
3. First parameter reads text [function(text, record, index) {}]

### What is expected?

As per rc-table documentation, this should be `value`  instead of `text`.  

### What is actually happening?

The first parameter is shown as text which conveys it as a string but a column value can be of any type in real-time usage. This will be misleading in some cases.

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18 |
| System | Mac |
| Browser | Chrome |

**Comment by anjantalatam** [comment]
Minor documentation change. 

I can pick this.

**Comment by afc163** [comment]
It should be `text`, we should update rc-table's documentation.
