### ISSUE TITLE
Typography组件希望可以支持收起

### ISSUE THREAD

**Issue by WenDaaa** [ant-design/ant-design#38994]
### What problem does this feature solve?

目前Typography.Paragraph只可以对隐藏的文字进行展开，无法收起
children是否可以支持html元素 目前只支持stirng类型 特定文字需要支持高亮 所以string无法满足

### What does the proposed API look like?

可以支持类似react的dangerouslySetInnerHTML的方式插入html片段
增加一个api 可以存在展开的内容也可以支持收起

**Comment by eternallycyf** [comment]
自己封装下 http://wangxince.site/my-demo-markdown/components/my-components/custom-tooltip

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20639#issuecomment-759251717
