### ISSUE TITLE
I can not change max-height of TreeSelect dropdown. It shows max 11 TreeNode.

### ISSUE THREAD

**Issue by berkaykirtillii** [ant-design/ant-design#39005]
### What problem does this feature solve?

I want to use TreeSelect as a Tree component design. But I can not change max height of TreeSelect dropdown with dropdownStyle API. It shows max 11 TreeNode.

Here is the link : https://codesandbox.io/s/cool-gould-bkk6jc?file=/src/App.js

### What does the proposed API look like?

dropdownStyle

**Comment by berkaykirtillii** [comment]
Hello @afc163 , I can not change max height of TreeSelect component with dropdownStyle or manupulating ant design css. What should I do ?

**Comment by afc163** [comment]
@berkaykirtillii It works in your codesandbox.

https://codesandbox.io/s/muddy-leaf-hzz4r4?file=/src/App.js

<img width="1391" alt="图片" src="https://user-images.githubusercontent.com/507615/204453493-35a12606-c5fa-4c25-9e82-da07bba76eaf.png">

**Comment by berkaykirtillii** [comment]
@afc163 thanks for your interest. But I want to change maxHeight of dropdown because it shows only 9 TreeNodes. Changing dropdownStyle maxHeight doesnt change the maxHeight of dropdown. I can not see 15 or more TreeNodes anyway.

**Comment by grants** [comment]
@berkaykirtillii  you could use listHeight setting for treeselect. 

`
const tProps = {
    treeData: your_data,
    listHeight: 1000  // number type, it can change list show height of your select box
}
`

**Comment by berkaykirtillii** [comment]
> @berkaykirtillii Did you resolve this problem?

> Yes, TreeSelect component has virtual prop(default value is true). If you change this prop to false this problem is solved and maxHeight starts working.

**Comment by berkaykirtillii** [comment]
@grants I'm not entirely sure since it's been a long time, but I do remember that any height style setting wouldn't work without making the virtual prop false.

**Comment by karthik1120** [comment]
```
const tProps = {
    treeData: your_data,
    listHeight: 1000  // number type, it can change list show height of your select box
}
```

along with 

`
  dropdownStyle={{
            maxHeight: '350px',
            maxWidth: '300px',
            overflow: 'auto',
          }}
`
will works.
