### ISSUE TITLE
Menu ant-menu-overflow内的SubMenu，鼠标移动到上方的样式不正确

### ISSUE THREAD

**Issue by 786259135** [ant-design/ant-design#39007]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rc5gw6?file=/index.js)

### Steps to reproduce

鼠标移动到menu的"..."节点展开面板，再移动到例如“Item 6”节点上

### What is expected?

1.移动到 ant-menu-overflow内的SubMenu节点，也应该是手指形状
2.鼠标从“Item 6”左边移出，c_Item 6未获得焦点时自动隐藏
3.仅显示鼠标焦点所在位置的子节点，如停留在“Item 9”则只展示“c_Item 9”

### What is actually happening?

- [ ] 现在是选择文本的样式
- [ ] 鼠标从“Item 6”左边移出，c_Item 6节点未自动隐藏
- [ ] 鼠标在“Item 8”、“Item 9”之间快速切换，然后停留在“Item 9”，有一定概率会同时显示“c_Item 8”、“c_Item 9”节点

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18 |
| System | macos  |
| Browser | Chrome last |

**Comment by afc163** [comment]
<img width="385" alt="图片" src="https://user-images.githubusercontent.com/507615/204140358-5e3cd277-8f64-420f-8fc2-2096e294de57.png">

弹层位置也是错的。

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/42648
