### ISSUE TITLE
Sorted/Filtered table fixed column transparent background unreadable

### ISSUE THREAD

**Issue by la99er** [ant-design/ant-design#39006]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-flower-zsbrg0)

### Steps to reproduce

1. Sort by the name column
2. Scroll the table to the left

### What is expected?

The content that scrolls should hide behind the fixed table column.

### What is actually happening?

The background of the fixed column is transparent which makes the content unreadable.

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Firefox |

---
This is caused by the color scheme which uses  `rgba(0,0,0,0.02)` for `colorFillQuaternary` and in the header `rgba(0, 0, 0, 0.06)` for `colorFillSecondary`

**Comment by afc163** [comment]
<img width="162" alt="图片" src="https://user-images.githubusercontent.com/507615/204018695-3fb862e3-df09-45d8-89a3-3feb24b3997e.png">
Good catch!
