### ISSUE TITLE
Modal嵌套Form关闭之后闪烁

### ISSUE THREAD

**Issue by southliu** [ant-design/ant-design#39013]
### Reproduction link

[https://ant.design/components/form-cn#components-form-demo-form-in-modal](https://ant.design/components/form-cn#components-form-demo-form-in-modal)

### Steps to reproduce

点击官网案例中的“New Collection”按钮，弹出弹窗之后关闭弹窗，会出现弹窗闪烁一下。

### What is expected?

关闭弹窗之后不要重新闪烁弹窗。

### What is actually happening?

关闭弹窗之后会闪烁一下弹窗。

![GIF 2022-11-26 19-09-54](https://user-images.githubusercontent.com/26358837/204086121-9a6167da-c0c6-4690-9ccd-1330c3b80f1b.gif)

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18 |
| System | Window |
| Browser | Google Chrome |

**Comment by southliu** [comment]
解决办法在Modal中添加destroyOnClose(关闭时销毁 Modal 里的子元素)。
```
<Modal destroyOnClose={true}>
  /* ... */
</Modal>
```

**Comment by afc163** [comment]
解决了？

**Comment by Chastrlove** [comment]
> 解决了？

好像是动画结束后，ant-zoom-leave的className被移除了，但是onVisibleChanged在useEffect里触发的晚了，就会使得style:display:none 延迟渲染，导致了闪烁一下
https://github.com/react-component/motion/blob/1a133a53f6dba2e87a013f9c83bd39d90d599076/src/hooks/useStatus.ts#L237

**Comment by afc163** [comment]
看看是不是同一个问题。#39054

**Comment by murrayee** [comment]
> 解决办法在Modal中添加destroyOnClose(关闭时销毁 Modal 里的子元素)。
> 
> ```
> <Modal destroyOnClose>
>   /* ... */
> </Modal>
> ```

useModal 无效
