### ISSUE TITLE
在 webcomponent 中无法使用样式

### ISSUE THREAD

**Issue by xiaoYown** [ant-design/ant-design#39011]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/live/748da676523)

### Steps to reproduce

1. 使用 webcomponent 自定义标签创建 React 根节点元素
2. 正常使用 antd

### What is expected?

期望 css-in-js 可以选择样式挂载位置, 在 webcomponent 中正常使用样式

### What is actually happening?

在 webcomponent 中使用的 antd 组件，样式挂在 head, 被 webcomponent 样式隔离

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.2.0 |
| System | mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
Duplicate of #38911
