### ISSUE TITLE
Run snapshot testing against all demos

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#3902]
#3771

---

- [x] Parse js code in markdown.
- [x] Create a test which can run snapshot testing against all demos automatically.
- [x] Integrate coveralls.io.

Make a plan for this, assign to @ant-design/ant-design-team, and add coverage badge and ci. @yesmeck

**Comment by yesmeck** [comment]
我觉得现在等 @benjycui 搞定把 demo 的 js 从 markdown 里分离出来后，对所有的 demo 做自动的 snapshot 测试会比较好，把这么多组件的不同状态补一次测试的话工作量有点多。

**Comment by afc163** [comment]
👍

**Comment by yesmeck** [comment]
更新了标题和描述

**Comment by benjycui** [comment]
所以现在要把 demo 代码从 Markdown 里面提取出来了么。

**Comment by benjycui** [comment]
也就是 demo 文档和代码分开写。

**Comment by yesmeck** [comment]
不是正好有这个计划吗？

**Comment by afc163** [comment]
那还是不要吧，markdown 可读性高。

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design-mobile/pull/477/files 这里不是已经这么做了吗？

**Comment by afc163** [comment]
antd 这边别改。宁愿把 js 从 markdown 中解析出来。

**Comment by yesmeck** [comment]
那解析也可以的。

**Comment by benjycui** [comment]
test 需要 watch 么？不需要的话，在跑 test 前把代码 extract 到一个目录就可以了。

**Comment by yesmeck** [comment]
估计写一个 typescript-babel-jest 类似的预处理器就可以了
