### ISSUE TITLE
Antd Confirm Modal's OK Button doesn't respect the theme-token-colorPrimary

### ISSUE THREAD

**Issue by nhatncb** [ant-design/ant-design#39023]
### Reproduction link

[https://ant.design/components/modal](https://ant.design/components/modal)

### Steps to reproduce

- Using antd with **### ant-design/pro-layout**
- Set theme token colorPrimary
- Using Modal.confirm
- The OK button will have the default primary color, not the color I set.

### What is expected?

- Show correct primary color

### What is actually happening?

- Show the default primary color

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18 |
| System | MACOS |
| Browser | Chrome |

---
![image](https://user-images.githubusercontent.com/49893714/204101066-61af1088-9468-4cbf-9ec6-9e5c65d09a89.png)

**Comment by afc163** [comment]
Use `Modal.useModel`: https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

**Comment by ghostlhq** [comment]
> Use `Modal.useModel`: https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

如果我要是在class组件中使用modal应该怎么办呢？

**Comment by ywzou** [comment]
在类组件中怎么处理呢？

**Comment by mMarcos208** [comment]
Any solution?

**Comment by StubbornDeer** [comment]
Any progress on this issue? I have useModal and contextHolder and it's only working when I use Modal component explicitly but is not working for the confirm method.

**Comment by StubbornDeer** [comment]
For some reason, when using confirm() the whole context of the current functional component is gone. I mean all the state variables have their initial (mostly empty) values. Why is that and what is the fix? Thanks!

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546
