### ISSUE TITLE
Card meta regression after updating from 4.20.0

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ant-design/ant-design#39025]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-content-antd-4-24-4-forked-3er85f?file=/demo.tsx)

### Steps to reproduce

* Open link and change antd version to 4.24.4
* See that title only occupies part of the card width
* Change to version 4.20.0
* See how it was before

### What is expected?

All width is used

### What is actually happening?

Not all width is used

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 18.0.0 |
| System | Windows 10 |
| Browser | Chrome 107 |

---
I believe it was introduced in this commit:
https://github.com/ant-design/ant-design/pull/35278

In this line:
https://github.com/ant-design/ant-design/pull/35278/files#diff-20032e8b53cd02a2d8979da7307524cc4e572d1d31798f42084bf015c454ee1bR201

I can work around this, but it won't be elegant, better fix in the library. Thanks.

**Comment by justanotheranonymoususer** [comment]
Please don't forget to backport to v4. Or should I open a new PR? @afc163

**Comment by afc163** [comment]
PR is welcome, 4.x-stable branch is the target.

**Comment by justanotheranonymoususer** [comment]
Here: https://github.com/ant-design/ant-design/pull/39039
Thanks.

**Comment by justanotheranonymoususer** [comment]
@afc163 can you also merge this please? https://github.com/ant-design/ant-design/pull/39027
It's another one-line regression fix, I'd like to have it merged in the next 4.x version so I can update.
