### ISSUE TITLE
Transfer组件点击复选框选中后，如果点击复选框位置不可以取消选中， 只有点击列表才行，点击复选框位置不可以取消选中，触发了两次onSelectChange

### ISSUE THREAD

**Issue by dnwu** [ant-design/ant-design#39030]
### Reproduction link

[https://ant-design.gitee.io/components/transfer-cn#transfer](https://ant-design.gitee.io/components/transfer-cn#transfer)

### Steps to reproduce

点击官网demo, Transfer点击复选框选中，再次点击复选框，不可以取消选中，（注意不是点击列表，而是复选框位置）

### What is expected?

onSelectChange触发一次就行

### What is actually happening?

点击复选框，onSelectChange触发两次

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 任意版本 |
| System | * |
| Browser | * |

**Comment by edc-hui** [comment]
我来修复此问题
