### ISSUE TITLE
Transfer tree mode has style issue

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#39038]
<img width="630" alt="图片" src="https://user-images.githubusercontent.com/507615/204141877-8a216e79-6fa5-410e-a756-dc33adf72053.png">

Tree 和容器边框贴住了，此处应该有 padding。

https://ant.design/components/transfer-cn#components-transfer-demo-tree-transfer

**Comment by zombieJ** [comment]
v4 也是顶格，这边可以优化一下 demo。
