### ISSUE TITLE
打包后 语言包丢失 开发的为中文 打包后变英文了

### ISSUE THREAD

**Issue by muddyrain** [ant-design/ant-design#39045]
### Reproduction link

[https://github.com/muddyrainTestProject/antdv5.0.2-test](https://github.com/muddyrainTestProject/antdv5.0.2-test)

### Steps to reproduce

引入 语言包 
上下文引入 然后 嵌套 APP

### What is expected?

打包后会根据引入的语言包来进行打包

### What is actually happening?

引入的中文语言包 打包后为中文

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | react |
| System |  macOS 12.3  |
| Browser | chrome 106.0.5249.119 |

**Comment by BenXi630** [comment]
同样问题

**Comment by passerV** [comment]
+1

**Comment by 786259135** [comment]
这么刺激嘛 =。=

**Comment by Dunqing** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/29533304/204182913-af22c4c1-b3c4-4b48-b202-4e30c76b3fe6.png">
改成 `antd/es/locale/zh_CN`就好了

**Comment by shixiaozhang** [comment]
就离谱！

**Comment by MadCcc** [comment]
vite 打包会对 cjs 处理，导致无法正确引入。推荐 vite 用户使用 `antd/lib/local` 引入 locale 文件。

**Comment by Dunqing** [comment]
> vite 打包会对 cjs 处理，导致无法正确引入。推荐 vite 用户使用 `antd/lib/local` 引入 locale 文件，后续会兼容处理。

应该是 `antd/es/locale` ?

**Comment by yzhang318** [comment]
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/29533304/204182913-af22c4c1-b3c4-4b48-b202-4e30c76b3fe6.png">
> 
> 改成 `antd/es/locale/zh_CN`就好了

值得一个大 upvote！谢谢！

**Comment by hsulei** [comment]
![image](https://user-images.githubusercontent.com/12029069/205911433-abc917d3-8c2a-470a-b539-ba5091eed35a.png) 没这个包么

**Comment by jsoncode** [comment]
离大普
