### ISSUE TITLE
FormItem下面的Input 的 Suffix 如果是Select组件，点击Select下拉三角失效

### ISSUE THREAD

**Issue by antgod** [ant-design/ant-design#3905]
#### 发生问题的环境是：

- antd 版本:2.4.2
- 操作系统及其版本:mac 
- 浏览器及其版本:chrome 52

#### 您做了什么？请提供尽可能详细的重现步骤。

如标题

**Comment by yesmeck** [comment]
如果能提供一个 demo （http://codepen.io/benjycui/pen/KgPZrE?editors=001） 的话会更快帮我们定位问题。

**Comment by benjycui** [comment]
Close now, if you can provide a re-producible demo, just re-open this issue.
