### ISSUE TITLE
SSR Warning: Prop `className` did not match with Avatar

### ISSUE THREAD

**Issue by phatify** [ant-design/ant-design#39065]
### Steps to reproduce

try to import Avatar to server component in Nextjs

### What is expected?

This warning should be remove

### What is actually happening?

The message warning in console:

`Warning: Prop `className` did not match. Server: "ant-avatar ant-avatar-circle ant-avatar-image ant-avatar-icon css-dev-only-do-not-override-6w1yu4" Client: "ant-avatar ant-avatar-circle ant-avatar-image ant-avatar-icon css-dev-only-do-not-override-1x6ld8w"`

![image](https://user-images.githubusercontent.com/70096611/204345887-4183c059-701a-4c4d-91ac-2e9fb78bb03e.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | React lastest version |
| System | Windows 10 |
| Browser | Chrome lastest version |

**Comment by aaronamm** [comment]
@phatify have you found this issue fixed? It still happens to me.
