### ISSUE TITLE
Theme variables not working for some components

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#39066]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/text-and-link-component-antd-5-0-2-forked-czq91r)

### Steps to reproduce

Check the color on the copyable icon on Text component.
Check the color on the Modal confirm Ok button

### What is expected?

To have the same color as the theme "colorPrimary"

### What is actually happening?

Has default color.

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | ^18.2.0 |
| System | Windows 10 |
| Browser | Brave |

---
Is there something else that needs to be done? Some components are now working as intended?

**Comment by MadCcc** [comment]
Theme of Modal/Notification/Message created by Static function will not affected by ConfigProvider because we need Context to pass theme variables. Please use `useModal` instead.

**Comment by balboFK** [comment]
@MadCcc what about the Text with copyable? The icon on it is also not working with the primary color.

**Comment by zombieJ** [comment]
That's `colorInfo`:
https://codesandbox.io/s/text-and-link-component-antd-5-0-2-forked-ckzi72
