### ISSUE TITLE
微信中antd@5样式不工作 / Antd@5 style doesn't work in wechat

### ISSUE THREAD

**Issue by By-Ha** [ant-design/ant-design#39063]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

使用微信（PC或安卓均可复现）打开
![1](https://user-images.githubusercontent.com/46854508/204328651-d243dbfd-bec3-41a1-96ea-736ca7e335b1.png)
![2](https://user-images.githubusercontent.com/46854508/204328676-c3ec92ea-0450-4fd3-8b16-9da4038e9315.png)

### What is expected?

正确显示样式

### What is actually happening?

默认样式并未显示

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 18 |
| System | Windows 11 |
| Browser | 微信内置浏览器/Wechat built in browser |

**Comment by linchCN** [comment]
一样的问题

**Comment by afc163** [comment]
https://ant.design/docs/react/customize-theme-cn#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%B0%83%E6%95%B4

**Comment by jsoncode** [comment]
我遇到的同样的问题，但是，根据官方的方案(https://ant.design/docs/react/compatible-style-cn)，并未解决。
我的项目配置是：antd5+nextjs13。
我疑惑是不是不支持nextjs?

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/13176273/213859966-1246a640-3e4e-4de5-b9b8-4d8c3d7dc22e.png">

**Comment by By-Ha** [comment]
> 我遇到的同样的问题，但是，根据官方的方案( https://ant.design/docs/react/compatible-style-cn )，并未解决。 我的项目配置是：antd5+nextjs13。 我疑惑是不是不支持nextjs? 产生的样式仍然是带有where选择器。
> 
> <img alt="image" width="1259" src="https://user-images.githubusercontent.com/13176273/213859966-1246a640-3e4e-4de5-b9b8-4d8c3d7dc22e.png">
> 
> <img alt="image" width="543" src="https://user-images.githubusercontent.com/13176273/213860036-692e9a55-67eb-4cb1-b210-756d35556ab5.png">

我用的也是Next@13，在用了StyleProvider后已经没有where选择器了，你可以开个demo看看是哪里配错了可能。而且微信也增加了对where选择器的支持，现在没有再看到样式问题了

**Comment by By-Ha** [comment]
附上我的主要依赖版本
"react": "18.2.0",
"next": "13.1.2",
"antd": "^5.1.4",

**Comment by jsoncode** [comment]
> 附上我的主要依赖版本 "react": "18.2.0", "next": "13.1.2", "antd": "^5.1.4",

请问一下，你是在layout/index.tsx里修改的，还是在/pages/_app.tsx里修改的呢？

这是我的代码：
layout/index.tsx
```tsx
import type {AppProps} from 'next/app'
import Head from "next/head";
import React from "react";
import {StyleProvider} from '@ant-design/cssinjs';
import '@/styles/globals.css'

export default function App({Component, pageProps}: AppProps) {
    return <StyleProvider hashPriority={'high'}>
        <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no" />
        </Head>
        <Component {...pageProps} />
    </StyleProvider>
}

```

_app.tsx

```tsx
import React from "react";
import {StyleProvider} from "@ant-design/cssinjs";
import type {AppProps} from 'next/app'
import '@/styles/globals.css'

export default function App({Component, pageProps}: AppProps) {
    return <StyleProvider hashPriority={'high'}>
        <Component {...pageProps} />
    </StyleProvider>
}

```

以上均未生效。

**Comment by jsoncode** [comment]
> > 附上我的主要依赖版本 "react": "18.2.0", "next": "13.1.2", "antd": "^5.1.4",
> 
> 请问一下，你在/pages/_app.tsx里是怎么修改的呢？
> 
> _app.tsx
> 
> ```tsx
> import React from "react";
> import {StyleProvider} from "@ant-design/cssinjs";
> import type {AppProps} from 'next/app'
> import '@/styles/globals.css'
> 
> export default function App({Component, pageProps}: AppProps) {
>     return <StyleProvider hashPriority={'high'}>
>         <Component {...pageProps} />
>     </StyleProvider>
> }
> ```
> 
> 其他依赖版本是： @ant-design/cssinjs@1.5.6 antd@5.1.6 next@13.1.2 react@18.2.0
> 
> 以上均未生效。

经过重新创建demo验证：
把旧项目代码，全部拷贝到新项目里面去，就可以生效了。==~
