### ISSUE TITLE
form-item嵌套会出现bug

### ISSUE THREAD

**Issue by antgod** [ant-design/ant-design#3907]
金蝉在包装Input/Select组件时，因为用到了一些Form组件属性，所以在input/select外面包了一层form-item,导致input的suffix里面如果是一个select的话，会出现样式bug。Select组件完全显示不出来。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close now, if you can provide a re-producible demo, just re-open this issue.
