### ISSUE TITLE
Table 内使用 Popover 导致打开时页面滚动最顶部

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#39073]
### Reproduction link

[https://stackblitz.com/edit/react-eudfaf?file=demo.tsx](https://stackblitz.com/edit/react-eudfaf?file=demo.tsx)

### Steps to reproduce

滚动最底部，然后点击 30 

### What is expected?

不滚动页面顶部

### What is actually happening?

滚动到页面顶部了

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by GuYith** [comment]
Try commenting out the focus(), as shown below
```
 useEffect(() => {
    if (editing) {
      // inputRef.current?.focus();
    }
  }, [editing]);
```

**Comment by crazyair** [comment]
need focus

**Comment by zombieJ** [comment]
Focus after Popover aligned:

```diff
    useEffect(() => {
       if (editing) {
--       inputRef.current?.focus();
++       setTimeout(() => {
++         inputRef.current?.focus();
++       }, 300);
       }
     }, [editing]);
```

https://stackblitz.com/edit/react-eudfaf-fa1efk?file=demo.tsx

**Comment by crazyair** [comment]
能拿到 Popover 打开动画结束回调吗

**Comment by crazyair** [comment]
试了下，不能用 300，太慢了，Popover 打开了等一会才会激活
