### ISSUE TITLE
<DatePicker /> with buddhist year in decade selector it's add year twice.

### ISSUE THREAD

**Issue by panudetjt** [ant-design/ant-design#39076]
### Reproduction link

[https://stackblitz.com/edit/react-e2yyn2?file=DatePicker.ts](https://stackblitz.com/edit/react-e2yyn2?file=DatePicker.ts)

### Steps to reproduce

1. click at `<DatePicker />` component
2. click at `.ant-picker-year-btn`

### What is expected?

it should be correct decade selector [like this](https://stackblitz.com/edit/react-kcapsv?file=demo.tsx)

### What is actually happening?

it's add year twice.

### Related issues

#10644 

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 18.2.0 |
| System | stackblitz |
| Browser | chrome Version 107.0.5304.110 (Official Build) (arm64) |

**Comment by RedJue** [comment]
ok, I'll try to fix it.

**Comment by panudetjt** [comment]
If I can help anything please let me know.

Thank you 🙏

**Comment by RedJue** [comment]
> If I can help anything please let me know.
> 
> 
> 
> Thank you 🙏 

Please check again, whether the date range selection pops up first, and then the date selection pops up, which is in line with expectations.

**Comment by panudetjt** [comment]
> > If I can help anything please let me know.
> > Thank you 🙏
> 
> Please check again, whether the date range selection pops up first, and then the date selection pops up, which is in line with expectations.

My expectation is 2566 which mean 2023 + 543. 
But if I try to manually add 543 years in config `getYear()` like this
<img width="537" alt="image" src="https://user-images.githubusercontent.com/3482285/212376579-d28ed679-72bd-4da1-9a2f-d745ead604ba.png">
It will ended up with add 543 years twice in decade selector like this 
<img width="294" alt="image" src="https://user-images.githubusercontent.com/3482285/212376875-8d06d0b7-183c-48bf-bc79-35dd10ccd01f.png">

**Comment by RedJue** [comment]
> > > If I can help anything please let me know.
> 
> > > Thank you 🙏
> 
> > 
> 
> > Please check again, whether the date range selection pops up first, and then the date selection pops up, which is in line with expectations.
> 
> 
> 
> My expectation is 2566 which mean 2023 + 543. 
> 
> But if I try to manually add 543 years in config `getYear()` like this
> 
> <img width="537" alt="image" src="https://user-images.githubusercontent.com/3482285/212376579-d28ed679-72bd-4da1-9a2f-d745ead604ba.png">
> 
> It will ended up with add 543 years twice (3109) in decade selector like this 
> 
> <img width="294" alt="image" src="https://user-images.githubusercontent.com/3482285/212376875-8d06d0b7-183c-48bf-bc79-35dd10ccd01f.png">
> 
> 

Ok, I understand what you mean, I will fix this as soon as possible👌

**Comment by zombieJ** [comment]
Checked again. You are almost close to the answer. Just miss part of year convert: https://stackblitz.com/edit/react-e2yyn2-3mxni6?file=DatePicker.ts

**Comment by panudetjt** [comment]
> Checked again. You are almost close to the answer. Just miss part of year convert: https://stackblitz.com/edit/react-e2yyn2-3mxni6?file=DatePicker.ts 

Thank you very much.

Xie xie 

You saved my life.
