### ISSUE TITLE
V3 to V4 migration url is not working

### ISSUE THREAD

**Issue by iowg** [ant-design/ant-design#39084]
### Reproduction link

[https://ant.design/docs/react/migration-v4](https://ant.design/docs/react/migration-v4)

### Steps to reproduce

-

### What is expected?

see documentation how to upgrade from v3 to v4

### What is actually happening?

404 Sorry, the page you visited does not exist.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | - |
| System | - |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Visit https://4x.ant.design/docs/react/migration-v4/

**Comment by iowg** [comment]
![image](https://user-images.githubusercontent.com/54708829/204493785-97a902d8-e0d0-405f-9950-f3d91eb12d1c.png)

you should update link here

**Comment by zombieJ** [comment]
Let me handle this
