### ISSUE TITLE
Steps 组件，第一项带有进度时，进度条显示溢出

### ISSUE THREAD

**Issue by liuyib** [ant-design/ant-design#39088]
### Reproduction link

[https://stackblitz.com/edit/react-hh9a2w?file=demo.tsx](https://stackblitz.com/edit/react-hh9a2w?file=demo.tsx)

### Steps to reproduce

给 Steps 组件设置以下参数：

```jsx
size="small"
current={0}
percent={90}
```

### What is expected?

第一项带有进度时，进度条显示正常

### What is actually happening?

第一项带有进度时，进度条显示溢出

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 18.2.0 |
| System | macOS12.3.1 |
| Browser |  107.0.5304.110 |

---
size="small" 的 Steps 组件才有这个问题，size="default" 的没有

**Comment by Wxh16144** [comment]
let me try :)

**Comment by liuyib** [comment]
> The progress bar in the reproduction link is working normally.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/38221479/204539542-ca04492f-8ed8-4485-98a3-335b699e172c.png">

reappears only in the horizontal mode

**Comment by Wxh16144** [comment]
> > The progress bar in the reproduction link is working normally.
> 
> <img alt="image" width="591" src="https://user-images.githubusercontent.com/38221479/204539542-ca04492f-8ed8-4485-98a3-335b699e172c.png">
> 
> reappears only in the `horizontal` mode, `vertical` is normal :)

Yes, it should be a css writing order problem. I'll submit a PR later.

**Comment by Wxh16144** [comment]
version: 5.0.2, link: https://ant.design/~demos/components-steps-demo-progress-debug


https://user-images.githubusercontent.com/32004925/204565674-538b5e1e-7fdc-47e8-b162-28daca6e0b6d.mp4
