### ISSUE TITLE
求官方版本vue

### ISSUE THREAD

**Issue by evolutionjay** [ant-design/ant-design#3909]
没啥，就一个需求。
虽然不是自己没办法写，
但是改起来好麻烦，
看了一下第三方的版本，
要么是vue版本跟不上，
要么是ant库一般般，实在无法应用到生产上。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#are-you-going-to-provide-angularvueetc-edition

**Comment by afc163** [comment]
https://ant.design/docs/spec/introduce#%E5%89%8D%E7%AB%AF%E5%AE%9E%E7%8E%B0
