### ISSUE TITLE
[Input.TextArea]: resize 不为 none 时 close 和 feedback 图标样式问题

### ISSUE THREAD

**Issue by 3Alan** [ant-design/ant-design#39099]
### Reproduction link

[https://ant.design/~demos/components-form-demo-validate-static](https://ant.design/~demos/components-form-demo-validate-static)

### Steps to reproduce

调整文本域宽度即可复现

### What is expected?

close 和 feedback 图标在文本域内

### What is actually happening?

close 和 feedback 图标在文本域外

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 18.2.0 |
| System | MACOS 12.1 |
| Browser | chrome 107.0.5304.121 |

---
4.x 版本的文本域仅支持高度调整所以没有这个问题，5.x 版本同时支持了高度和宽度的调整

![image](https://user-images.githubusercontent.com/49978973/204557087-dda977af-34b5-4f96-bbad-f1ca5a0e3f4e.png)

**Comment by 51wangping** [comment]
let me try
