### ISSUE TITLE
Datepicker  抛出异常

### ISSUE THREAD

**Issue by carr123** [ant-design/ant-design#391]
< antd.Datepicker format="yyyy/MM/dd" defaultValue="1998/10/12" / >

当我设置defaultValue 值的时候就抛出如下异常：
Uncaught Error: calendar must be type of GregorianCalendar

我想在组件初始化的时候设置如上格式的日期，怎么弄？  谢谢

**Comment by afc163** [comment]
看看你的例子。

**Comment by carr123** [comment]
你好，  就是这样写运行出错： < antd.Datepicker format="yyyy/MM" defaultValue="1998-10-13"  />

**Comment by afc163** [comment]
你的 defaultValue 和 format 格式是否应该保持一致？

**Comment by carr123** [comment]
你好，defaultValue 和 format 格式 是保存一致的。

**Comment by afc163** [comment]
确实有问题，感谢反馈~

**Comment by xileliu** [comment]
我也再次遇到这个问题

**Comment by xileliu** [comment]
![image](https://cloud.githubusercontent.com/assets/13429648/18744851/3bcb5c82-80f2-11e6-86b5-163668d44380.png)

**Comment by afc163** [comment]
moment 的 format 和 GregorianCalendar 的 format 是不一样的。

**Comment by xileliu** [comment]
您是说moment format出来的日期和GregorianCalendar的不一样吗，但是后端给我的数据是一个时间戳，前端必须format这个时间戳。

**Comment by qiaoyixuan** [comment]
一年了。。。这个问题依旧存在。。。。。。。
import { DatePicker } from 'antd';
import moment from 'moment';

ReactDOM.render(
  <DatePicker defaultValue={moment('2015-06-06', 'YYYY-MM-DD')} disabled />
, mountNode);
按照官网的例子写依然报错calendar must be type of GregorianCalendar

**Comment by afc163** [comment]
@qiaoyixuan 不是同一个问题。

请见：https://github.com/ant-design/ant-design/issues/3294#issuecomment-252392777

如果 antd 没升级，请查看旧版文档，文档版本切换见右下角。

**Comment by basebase** [comment]
const dateFormat = 'YYYY-MM-DD';
	

	 <DatePicker defaultValue={moment('2017-10-27', dateFormat)} showTime format={dateFormat} {...getFieldProps(field.key)}/>
报相同错误

**Comment by basebase** [comment]
const dateFormat = 'YYYY-MM-DD';
		 <DatePicker defaultValue={moment('2017-10-27', dateFormat)} showTime format={dateFormat} {...getFieldProps(field.key)}/>

相同错误，请问你们是怎么解决的？

**Comment by afc163** [comment]
@basebase 你不看上面回复的么
