### ISSUE TITLE
Upload.Dragger does not recognize "picture-card" option for `listType`

### ISSUE THREAD

**Issue by hgbao** [ant-design/ant-design#39106]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-fr1705?file=/index.js)

### Steps to reproduce

`<Upload.Dragger listType="picture-card"/>`

### What is expected?

`<Upload.Dragger listType="picture-card"/>` should render `picture-card` for uploaded files

### What is actually happening?

`<Upload.Dragger listType="picture-card"/>` is still rendering type `text` for uploaded files

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.2.0 |
| System | MacOS Ventura |
| Browser | Chrome (Version 107.0.5304.110) |

**Comment by afc163** [comment]
Yes, we don't support `listType="picture-card"` for Dragger yet.
