### ISSUE TITLE
table 固定列，表格无数据时，右侧边框不显示

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#39115]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-0-2-forked-tpcu4s?file=/demo.tsx)

### Steps to reproduce

无

### What is expected?

表格右侧显示边框

### What is actually happening?

表格右侧无边框

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | react@18.2.0 |
| System | macOS 13 |
| Browser | chrome 107.0.5304.110 |

**Comment by wanghui2021** [comment]
这个应该修复5.x版本的样式即可。4.x版本无此问题

**Comment by edc-hui** [comment]
![image](https://user-images.githubusercontent.com/33356467/205534582-9c419cab-2ffe-4ec8-b535-7ef81e053418.png)
@wanghui2021 你说的是图中这个在无数据的时候不应该显示是么？我这边测试  5.x 和  4.x  都会出现这个现象。所以我现在有点怀疑自己是不是理解错这个issue了

**Comment by afc163** [comment]
4.x: https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-0-2-forked-3i6fhh?file=/package.json
<img width="699" alt="图片" src="https://user-images.githubusercontent.com/507615/209040049-daef8bf7-a611-4757-a2ef-0341223cc9d0.png">

5.x: https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-0-2-forked-w8gu8q?file=/demo.tsx
<img width="634" alt="图片" src="https://user-images.githubusercontent.com/507615/209040104-52b5c748-35a5-4105-bf59-c8c01f96fd6a.png">

**Comment by afc163** [comment]
<img width="120" alt="图片" src="https://user-images.githubusercontent.com/507615/209040557-bb4aae2b-7f3f-40d2-9d7c-eec79ece9139.png">

顶部也缺边框。

**Comment by afc163** [comment]
只有一个右上角滚动后的圆角问题，我修掉。
<img width="81" alt="图片" src="https://user-images.githubusercontent.com/507615/209041694-fce08bbe-1920-4463-a8e7-a3996c272c41.png">

**Comment by wanghui2021** [comment]
> 4.x: https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-0-2-forked-3i6fhh?file=/package.json <img alt="图片" width="699" src="https://user-images.githubusercontent.com/507615/209040049-daef8bf7-a611-4757-a2ef-0341223cc9d0.png">
> 
> 5.x: https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-0-2-forked-w8gu8q?file=/demo.tsx <img alt="图片" width="692" src="https://user-images.githubusercontent.com/507615/209040943-58b0a609-fd15-4182-8357-df373a2533dc.png">
> 
> 好像没啥问题。

antd@5.0.2 版本有该问题，antd@5.1.0 无该问题

**Comment by wanghui2021** [comment]
antd@5.0.2
<img width="761" alt="image" src="https://user-images.githubusercontent.com/37385554/209043608-93c50284-d015-401e-b0f8-a4de1a650d76.png">

antd@5.1.0
<img width="758" alt="image" src="https://user-images.githubusercontent.com/37385554/209043755-580cf963-a334-436f-bf11-cb6f7a817210.png">

**Comment by afc163** [comment]
那就是 5.1.0 不知道怎么就修复了。
