### ISSUE TITLE
Do not destroy notifications

### ISSUE THREAD

**Issue by ChebotarevKonstantin** [ant-design/ant-design#39116]
### Reproduction link

[https://ant.design/~demos/components-notification-demo-with-btn](https://ant.design/~demos/components-notification-demo-with-btn)

### Steps to reproduce

get a list of notifications, click "destroy"

### What is expected?

hide all notifications

### What is actually happening?

notifications are not hidden

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | react - 18 |
| System | macOS |
| Browser | Google chrome |

**Comment by any1024** [comment]
好像是 `rc-notification` 出了问题

**Comment by ChebotarevKonstantin** [comment]
Thanks!
