### ISSUE TITLE
antdv4.21.3及以上版本Menu组件子节点jsx形式渲染重复

### ISSUE THREAD

**Issue by drdevelop** [ant-design/ant-design#39120]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ig68xq)

### Steps to reproduce

1. 渲染页面
2. 控制台查看菜单渲染的子组件元素
3. 发现有两个完全一样的子元素

### What is expected?

display: none底下的子元素删除

### What is actually happening?

Menu子元素渲染重复

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome任意版本 |

**Comment by afc163** [comment]
不应该在 Menu 里直接放 div。

**Comment by drdevelop** [comment]
@afc163 历史代码，不太明白这里为啥会多余复制一份渲染呢，是有啥意图吗
<img width="555" alt="image" src="https://user-images.githubusercontent.com/39514265/204773674-230d021b-22ef-4a2b-ae5e-782836ea36b7.png">

**Comment by afc163** [comment]
Menu 需要 overflow 自动缩起的能力。
