### ISSUE TITLE
文档中全局化配置theme报错

### ISSUE THREAD

**Issue by yzy185** [ant-design/ant-design#39147]
### Reproduction link

[https://ant-design.antgroup.com/components/config-provider-cn#components-config-provider-demo-theme](https://ant-design.antgroup.com/components/config-provider-cn#components-config-provider-demo-theme)

### Steps to reproduce

修改border radius，直接error

### What is expected?

normal

### What is actually happening?

error

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 17 |
| System | mac |
| Browser | google |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/39152
