### ISSUE TITLE
FloatButton 悬浮按钮，回到顶部的示例效果展示不正确。

### ISSUE THREAD

**Issue by yujianxia** [ant-design/ant-design#39148]
### Reproduction link

[https://ant-design.gitee.io/components/float-button-cn#components-float-button-demo-back-top](https://ant-design.gitee.io/components/float-button-cn#components-float-button-demo-back-top)

### Steps to reproduce

1，打开https://ant-design.gitee.io/components/float-button-cn#components-float-button-demo-back-top，定位至‘回到顶部’功能演示
2，第一次向下滚动下拉条至底部，并未展示FloatButton。
3，下拉条复位，展示FloatButton按钮，点击无效。
4，第二次向下滚动下拉条至底部，仍然未展示FloatButton，但是FloatButton展示的区域，可以点击，并且能回到顶部。

### What is expected?

2，展示FloatButton且功能正常
3，不展示FloatButton按钮
4，展示FloatButton且功能正常

### What is actually happening?

与预期不符合

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.0.0 |
| System | mac os 11.3.1 |
| Browser | Google Chrome 版本 94.0.4606.61（正式版本） (x86_64) |

**Comment by li-jia-nan** [comment]
最新的版本已经修复了，升级即可

**Comment by afc163** [comment]
先看 https://ant.design/components/float-button-cn#components-float-button-demo-back-top 

gitee 的问题我晚点同步一下站点。

**Comment by yujianxia** [comment]
> 



> 最新的版本已经修复了，升级即可
 
antd官网的展示错误，如何升级能正确展示？
