### ISSUE TITLE
AutoComplete 查询模式。右侧按钮底部样式溢出。

### ISSUE THREAD

**Issue by yujianxia** [ant-design/ant-design#39149]
### Reproduction link

[https://ant-design.gitee.io/components/auto-complete-cn#components-auto-complete-demo-uncertain-category](https://ant-design.gitee.io/components/auto-complete-cn#components-auto-complete-demo-uncertain-category)

### Steps to reproduce

打开AutoComplete 查询模式。右侧按钮底部样式溢出。

### What is expected?

AutoComplete 查询模式。右侧按钮底部样式对齐。

### What is actually happening?

与期望不符合

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.0.0 |
| System | mac os 11.3.1 |
| Browser | Google Chrome 版本 94.0.4606.61（正式版本） (x86_64) |

**Comment by afc163** [comment]
<img width="561" alt="图片" src="https://user-images.githubusercontent.com/507615/204993276-58f2282a-3f1f-45f4-bc54-9fe478291729.png">

没看出有啥问题。

**Comment by yujianxia** [comment]
> 

我是在gitee的镜像上看的。https://ant-design.gitee.io/components/auto-complete-cn#components-auto-complete-demo-uncertain-category
![image](https://user-images.githubusercontent.com/28092003/204994175-8becd9d5-1905-47f1-8f92-e4be1b3152a2.png)

**Comment by afc163** [comment]
@yujianxia 看看 https://ant.design/components/auto-complete-cn#components-auto-complete-demo-uncertain-category 是否有问题

**Comment by yujianxia** [comment]
> <img alt="图片" width="561" src="https://user-images.githubusercontent.com/507615/204993276-58f2282a-3f1f-45f4-bc54-9fe478291729.png">
> 
> 没看出有啥问题。

我是在gitee的镜像上看的。https://ant-design.gitee.io/components/auto-complete-cn#components-auto-complete-demo-uncertain-category
![image](https://user-images.githubusercontent.com/28092003/204994175-8becd9d5-1905-47f1-8f92-e4be1b3152a2.png)

**Comment by yujianxia** [comment]
> @yujianxia 看看 https://ant.design/components/auto-complete-cn#components-auto-complete-demo-uncertain-category 是否有问题

我看还有。是镜像的版本问题吗？
![image](https://user-images.githubusercontent.com/28092003/204995699-7a430bbd-7f2c-49aa-b7ad-94e86093e257.png)

**Comment by afc163** [comment]
Chrome 版本感觉有点低

**Comment by afc163** [comment]
<img width="1210" alt="图片" src="https://user-images.githubusercontent.com/507615/204996189-b55426c1-88c7-4ba3-ab49-68cc89f7cab8.png">

你浏览器控制台里改下这个 line-height 试试，比如改成 1.5

**Comment by yujianxia** [comment]
> <img alt="图片" width="1210" src="https://user-images.githubusercontent.com/507615/204996189-b55426c1-88c7-4ba3-ab49-68cc89f7cab8.png">
> 
> 你浏览器控制台里改下这个 line-height 试试，比如改成 1.5

 line-height: 1.5，能正常展示。  我试了高版本Chrome，也是正常的。   就是我Chrome版本太低。

**Comment by afc163** [comment]
这样我们先不修了，免得影响更多浏览器。
