### ISSUE TITLE
希望文件上传组件 (Upload) 中的 fileList 中暴露整个 file 对象，及可以自定义 fileListItem 模板样式

### ISSUE THREAD

**Issue by uniquexiaobai** [ant-design/ant-design#3914]
目前的 `Upload` 组件中的 `listType` 只支持 `text`、`picture`、`picture-card`，它们只暴露了 `file.name`、`file.url` ，有的时候，需要显示 `file.lastModifiedDate`、`file.size` 等属性，就不得不重新实现 `Upload`，希望不要这么**简单粗暴**！

**Comment by afc163** [comment]
是暴露所有对象的。有问题请帮忙重现。

**Comment by afc163** [comment]
目前的模板只包含了设计规范中出现的字段，如果有特殊的需求，建议参照 [完全控制的上传列表](https://ant.design/components/upload/#components-upload-demo-fileList) 用 fileList 里的数据自行实现文件列表。

如果有现有功能的任何优化建议，欢迎直接给我们 PR，感谢支持~
