### ISSUE TITLE
Typography expandable text always with a `...` while even set the ellipsis symbol property

### ISSUE THREAD

**Issue by fyyhome** [ant-design/ant-design#39145]
### What problem does this feature solve?

It enables the user to customize the expandable symbol. 
If users don't want the `...` or want to use another string symbol, they can use the `symbol` property to rewrite it.

### What does the proposed API look like?

No addon interface, keep the `ellipsis` and make the `symbol` overwrite the `...展开`.

**Comment by afc163** [comment]
Please use bug-report template if you are trying report a bug.

**Comment by fyyhome** [comment]
Not sure whether it should be regarded as a bug, because I checked the official demos of [Typography expand](https://ant.design/components/typography-cn#components-typography-demo-ellipsis) and it always contains `...` before the `展开` button.

I'm searching for an appropriate way to remove the `...`, while I feel using a specific CSS selector to make it hidden is not a appropriate way.
