### ISSUE TITLE
table的宽度 撑开了外面 产生了横向滚动条

### ISSUE THREAD

**Issue by qcxiaoshuai-snake** [ant-design/ant-design#39141]
### Reproduction link

[https://blog.csdn.net/qq_35909965/article/details/128129675?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22128129675%22%2C%22source%22%3A%22qq_35909965%22%7D](https://blog.csdn.net/qq_35909965/article/details/128129675?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22128129675%22%2C%22source%22%3A%22qq_35909965%22%7D)

### Steps to reproduce

设置了 scroll  x为所有列的width的总和 外面还是 出现了滚动条

### What is expected?

外层没有滚动条

### What is actually happening?

外层出现滚动条

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by qcxiaoshuai-snake** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-5lphcl?file=/index.js

**Comment by afc163** [comment]
@qcxiaoshuai-snake 给一个只包含 antd table 的例子？

**Comment by qcxiaoshuai-snake** [comment]
我定位到 问题了 
 cols.forEach(col => {
      col.filterDropdown = ({ setSelectedKeys, selectedKeys, confirm, clearFilters }) => {
        return null;
      }
      col.filterSearch = true;
      col.filterDropdownOpen = true;
      col.filteredValue = filteredInfo ? filteredInfo[col.dataIndex] || null : null,
        col.filterIcon = () => {
          return (
            <FilterOutlined style={{fontSize: 15}} onClick={() => {
              if (toolbarRef.current) {
                toolbarRef.current.addFilterOption(col)
              }
            }} />
          )
        }
    })
是因为 过滤面板 没有内容 导致的 但是如何解决呢

![image](https://user-images.githubusercontent.com/54222132/204976230-7c490993-312e-4102-a308-d57af45de618.png)

**Comment by qcxiaoshuai-snake** [comment]
col.filterDropdownOpen = true;

我知道了  过滤面板 我return null 
但是 这里打开了  所以还有有面板   这是个bug啊

**Comment by qcxiaoshuai-snake** [comment]
麻烦 这个问题 可以关闭了

**Comment by afc163** [comment]
如果定位到问题并已解决，可以自行关闭。
