### ISSUE TITLE
Antd Mask Closable for Avatar

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#39143]
### What problem does this feature solve?

Should not be able to close avatar zoom image when clicking outside the image
Should only be able to close when clicking the (x) button when zooming

### What does the proposed API look like?

<Avatar maskClosable={false} />

**Comment by tempoeric** [comment]
@afc163 here is the the link for the reproduce issue
https://3xi7bj.csb.app/

**Comment by tempoeric** [comment]
Here is a video demo of the issue
[screen-capture (1).webm](https://user-images.githubusercontent.com/42777871/204973169-232c4ef8-281d-4a03-8165-7b392e0245d1.webm)

**Comment by Wxh16144** [comment]
let me try~

**Comment by tempoeric** [comment]
> let me try~

thanks

**Comment by Wxh16144** [comment]
I looked at the specific implementation and it originally supported these features. It's just not written in the documentation.

```tsx
<Image
    width={200}
    src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
    preview={{
      // Whether to close the modal dialog when the mask (area outside the modal) is clicked; default: true
      maskClosable: false,
      // Whether support press esc to close; default: true
      keyboard: false,
    }}
  />
```

**Comment by tempoeric** [comment]
> ```tsx
>  preview={{
>       // Whether to close the modal dialog when the mask (area outside the modal) is clicked; default: true
>       maskClosable: false,
>       // Whether support press esc to close; default: true
>       keyboard: false,
>     }}
> ```

I tried this but it's not working currently using antd 4.20.0 it seems the props isnt available. This are the only available api for avatar
<img width="893" alt="Screenshot 2022-12-02 at 5 19 12 AM" src="https://user-images.githubusercontent.com/42777871/205161368-b9a562ed-ad04-487f-9151-32e64c4bdc27.png">

**Comment by tempoeric** [comment]
i saw this on Image and they have mask but dont have maskClosable boolean type maybe we can add this on the image component itself 
<img width="986" alt="Screenshot 2022-12-02 at 5 24 57 AM" src="https://user-images.githubusercontent.com/42777871/205162390-f479d378-7813-4057-ab7d-bc5ee0d674f3.png">

**Comment by Wxh16144** [comment]
> i saw this on Image and they have mask but dont have maskClosable boolean type maybe we can add this on the image component itself <img alt="Screenshot 2022-12-02 at 5 24 57 AM" width="986" src="https://user-images.githubusercontent.com/42777871/205162390-f479d378-7813-4057-ab7d-bc5ee0d674f3.png">

Yes, the documentation here does not describe more props, there is actually a Dialog component inside.  

Take a look at this demo, does it meet your needs https://codesandbox.io/s/ji-ben-yong-fa-antd-4-24-4-forked-5tdfkf?file=/demo.tsx

**Comment by tempoeric** [comment]
> > i saw this on Image and they have mask but dont have maskClosable boolean type maybe we can add this on the image component itself <img alt="Screenshot 2022-12-02 at 5 24 57 AM" width="986" src="https://user-images.githubusercontent.com/42777871/205162390-f479d378-7813-4057-ab7d-bc5ee0d674f3.png">
> 
> Yes, the documentation here does not describe more props, there is actually a Dialog component inside.
> 
> Take a look at this demo, does it meet your needs https://codesandbox.io/s/ji-ben-yong-fa-antd-4-24-4-forked-5tdfkf?file=/demo.tsx

yes this does the job maybe i need to update my antd 4.20 to 4.22 to get that props
