### ISSUE TITLE
Tabs Component with More Icon Issue - Tabs does not scroll to any selected tab from the More Menu

### ISSUE THREAD

**Issue by isaac-wahba** [ant-design/ant-design#39166]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yvjo4v?file=/demo.tsx:633-1000)

### Steps to reproduce

N/A

### What is expected?

Tabs should scroll to any selected tab from the More Menu

### What is actually happening?

 Tabs does not scroll to any selected tab from the More Menu

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 17 |
| System | Windows |
| Browser | Chrome |

---
It is working on the demo (link to minimal reproduction), but not working on my app

**Comment by afc163** [comment]
We can't help if an online reproduce is provided.
