### ISSUE TITLE
Site with Ant design <5 version in first time work very slow

### ISSUE THREAD

**Issue by mcclaim** [ant-design/ant-design#39167]
### Reproduction link

[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce

CTRL   R in browser (for example in Chrome) and try open console or try to do something in first time, browser will be lagging if you try to do. Links to screenshot: https://i.ibb.co/dpyKbn2/Screenshot-1.jpg, https://i.ibb.co/s9Qmtpd/Screenshot-2.jpg

### What is expected?

In Ant design v4, all work fine, until opening Console after reload page. Right now, browsers are lagging when open site

### What is actually happening?

Lags in browser with ant design <v5: Links to screenshot: https://i.ibb.co/dpyKbn2/Screenshot-1.jpg, https://i.ibb.co/s9Qmtpd/Screenshot-2.jpg

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | ^18.1.0 |
| System | Windows |
| Browser | Chrome |

**Comment by rinick** [comment]
@zombieJ  when I profile the table page between 5.1 and 4x in chrome
5.1 takes about 7 seconds to load,  while 4x takes only 4 seconds

seems the v5 spends a lot of time on re-rendering stuff, and v4 is able to merge the script time together so it has less re-rendering

**Comment by rinick** [comment]
is it possible that cssinjs injects the css after the components are rendered, so it causes all the components to be rendered twice by the browser?

**Comment by zombieJ** [comment]
`cssinjs` using cache logic which will skip after second time render on component part. But app level cssinjs may not have optimize about this.

**Comment by zombieJ** [comment]
Another clue may be the site suspense hydrate issue. We've found that some page it throw hydrate fail error.

**Comment by rinick** [comment]
@zombieJ  it's not about react render, but the browser render.

because of the way cssinjs inject style into DOM, the first time a style is created, browser needs to do a lot of redundant style calculation

if you use chrome's dev tool's performance tab, you can easily see the difference.  

I tried a sample code with about 20 tables:
https://codepen.io/rinick/pen/qBydRYg

The time browser spend on "Recalculate Style" takes 480ms and the same example in v4 only takes only 180ms.

**Comment by rinick** [comment]
I think this is not a documentation issue but a general performance issue.

**Comment by rinick** [comment]
I created an issue about another performance problem here : https://github.com/ant-design/ant-design/issues/39746

But I'm not sure if they are exact the same issue.

**Comment by zombieJ** [comment]
close since https://github.com/ant-design/cssinjs/pull/143

**Comment by joshboley** [comment]
@zombieJ it appears https://github.com/ant-design/cssinjs/pull/143 was released in `@ant-design/cssinjs` [v1.17.0](https://github.com/ant-design/cssinjs/compare/v1.16.2...v1.17.0).  We're currently using `antd@5.19.2` which uses `@ant-design/cssinjs` v1.21.0 and we're still experiences significant slowness.
![Screenshot 2024-10-07 at 5 14 43 PM](https://github.com/user-attachments/assets/0c5b8d13-e9e8-4086-8b07-df607c27787e)
