### ISSUE TITLE
v5 Drawer getContainer 失效

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#39164]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drawer5-k0l7pc)

### Steps to reproduce

Drawer 的 getContainer 在 v5 版本中失效，在v4版本中没有问题

[此为 v4 版本链接](https://codesandbox.io/s/drawer4-4mm5qg)

### What is expected?

getContainer 在 v5 版本中正常

### What is actually happening?

getContainer 在 v5 版本中失效

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.0.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by 51wangping** [comment]
let me try~

**Comment by 51wangping** [comment]
在 4.x 版本中 style 行内样式映射到 RcDrawer 组件 rootStyle 属性上。 可用于设置 Drawer 最外层容器的样式。所以不会有问题。
在 5.x 版本中 style 行内样式作用于 Drawer 容器, 所以需要显示写成 rootStyle 才可用于设置 Drawer 最外层容器的样式。
4.x 与 5.x 部分 API有区别。@afc163 这个问题是否需要处理？
![image](https://user-images.githubusercontent.com/44744910/205200260-5b50d659-a389-48ec-8e96-42ea334486cf.png)
![image](https://user-images.githubusercontent.com/44744910/205200334-15639930-9354-40c3-aa4d-362456a03c04.png)

**Comment by afc163** [comment]
这个感觉是个 breaking change。要修改一下 demo 并在 changelog 里声明一下。

@zombieJ

**Comment by weeqe** [comment]
感觉像是rc-drawer里` <DrawerPopup {...sharedDrawerProps} inline={getContainer === false} /> ` `getContainer === false` 这个判断导致的 应该是 !== undefined

**Comment by zombieJ** [comment]
Drawer 和 Modal 对齐了，我文档里加一下
