### ISSUE TITLE
darkAlgorithm 作用于滚动条样式 / darkAlgorithm affects scrollbar style

### ISSUE THREAD

**Issue by 1pone** [ant-design/ant-design#39176]
### What problem does this feature solve?

目前默认主题在darkAlgorithm作用下滚动条仍然是浅色样式, 显得十分突兀, 可以参考官网效果
<img width="985" alt="image" src="https://user-images.githubusercontent.com/54310591/205203523-5afe7cea-f093-4826-b0c6-701cd28eec91.png">

### What does the proposed API look like?

darkAlgorithm生成一个默认的深色样式滚动条样式, 顺带可以把官网目前深色主题的滚动条样式修复一下

**Comment by MadCcc** [comment]
全局样式目前不在动态主题的考虑范围内，如 body、html 上的样式等，如果有需要的话可以自行根据当前主题变化。
