### ISSUE TITLE
Tabs 是否可以支持只展示前x个超过收缩起来

### ISSUE THREAD

**Issue by CalvinP-Cai** [ant-design/ant-design#39175]
### What problem does this feature solve?

比如我有10个页签，但是我想前5个页签平铺展示，超过5个的收缩到更多里

### What does the proposed API look like?

whatever。count， num之类的API吧

**Comment by afc163** [comment]
给 Tabs 上的容器设定一个宽度如何？

**Comment by CalvinP-Cai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CalvinP-Cai** [comment]
> 

我现在用的是给容器加min-width，我只是建议出个api

**Comment by CalvinP-Cai** [comment]
> 我现在用的是给容器加min-width，我只是建议出个api



> 给 Tabs 上的容器设定一个宽度如何？

我现在用的是给容器加min-width，我只是建议出个api
