### ISSUE TITLE
Tooltip在destroyTooltipOnHide={{keepParent:false}}时，会丢失关闭动画

### ISSUE THREAD

**Issue by dislido** [ant-design/ant-design#39184]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-4vok90?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

设置destroyTooltipOnHide={{keepParent:false}}

### What is expected?

Tooltip在完成关闭动画后再销毁

### What is actually happening?

Tooltip立刻被销毁了

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 17.x |
| System | MacOS 12.4 |
| Browser | chrome 107 |

**Comment by afc163** [comment]
是的，父元素上没有动画延迟，会直接销毁。
