### ISSUE TITLE
Style of antd5 tree blockNode

### ISSUE THREAD

**Issue by wenqi73** [ant-design/ant-design#39194]
### Reproduction link

[https://stackblitz.com/edit/react-vgqnqg?file=demo.tsx](https://stackblitz.com/edit/react-vgqnqg?file=demo.tsx)

### Steps to reproduce

set [blockNode] for tree

### What is expected?
the `.ant-tree-title` element width is not stretched
![image](https://user-images.githubusercontent.com/23337087/205257839-dbbb03c3-bc1d-4112-ba58-c76f86b3a2d2.png)

### What is actually happening?
the `.ant-tree-title` element width is stretched
![image](https://user-images.githubusercontent.com/23337087/205258129-4cc81989-e087-4d8c-8789-61954bbfb94b.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.2.0 |
| System | mac |
| Browser | Chrome |

---

**Comment by afc163** [comment]
5.x 上 `.ant-tree .ant-tree-checkbox + span` 上有个 `display: flex` 导致的，需要和 4.x 样式对齐。
