### ISSUE TITLE
对Tabs动态配置选项卡内容时，inkBar消失，不跟随

### ISSUE THREAD

**Issue by xldll** [ant-design/ant-design#39190]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w8g74l?file=/index.js)

### Steps to reproduce

1.点击重现链接demo中的change按钮
2.tabs内容重新渲染
3.inkBar消失
4.重新渲染后，切换tabs页签，inkBar不出现

### What is expected?

Tabs内容改变，inkBar出现在默认位置，或者使用activeKey确定的当前激活 tab 面板下方，并且在切换tab页签时能够跟随移动

### What is actually happening?

Tabs内容改变，inkBar消失，且切换tab页签时inkBar不出现，不跟随移动

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.x |
| System | windows，macOS没有尝试 |
| Browser | Chrome 106.0.5249.119 |

**Comment by afc163** [comment]
<img width="308" alt="图片" src="https://user-images.githubusercontent.com/507615/205245078-fdac21d1-232c-4712-a726-f688bbbff89e.png">
没发现问题，能录个屏么

**Comment by xldll** [comment]
https://user-images.githubusercontent.com/18284701/205251843-a31ea30f-525e-4454-8612-d4ee062def32.mp4

**Comment by afc163** [comment]
我这里的 Chrome 是好的。

**Comment by xldll** [comment]
mac没问题，windows可以复现

**Comment by xldll** [comment]
而且是在items数组长度相同时会触发，改变items长度，可以正常出现inkBar

**Comment by zhangtao25** [comment]
当我使用 https://github.com/johnwalley/allotment 组件时会遇到同样问题。这是我的codesandbox

**Comment by zhangtao25** [comment]
> 当我使用 https://github.com/johnwalley/allotment 组件时会遇到同样问题。这是我的 [codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-8wcwsr?file=/index.js)

a

**Comment by zhangtao25** [comment]
> 当我使用 https://github.com/johnwalley/allotment 组件时会遇到同样问题。这是我的 [codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-8wcwsr?file=/index.js)

https://user-images.githubusercontent.com/37892968/207266249-e53442bf-8336-474e-8dea-753a5fe9860f.mov
