### ISSUE TITLE
The Menu is not updated if you used the useNavigate hook

### ISSUE THREAD

**Issue by gitRacoon** [ant-design/ant-design#39198]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-beaver-5bmihp?file=/src/index.js)

### Steps to reproduce

Click to the "Go to About" button.

### What is expected?

The current page will be highlighted in the menu.

### What is actually happening?

In the menu, the page that was clicked on the last time (or the one by default) is highlighted.

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.2.0 |
| System | Pop!_OS 22.04 LTS |
| Browser | Google Chrome Version 108.0.5359.71 (Official Build) |

**Comment by afc163** [comment]
Why should it updated? You didn't do anything when page changed.

**Comment by gitRacoon** [comment]
> Why should it updated? You didn't do anything when page changed.

So what should i do to update?

**Comment by gitRacoon** [comment]
> Why should it updated? You didn't do anything when page changed.

So what should i do for update?
