### ISSUE TITLE
表单中 Form.Item 值修改后 , 需要联动修改 Form.List 值, 但 form.setFieldValue 在 Form.Item 调用后每次都会触发, 导致 Form.List 值重置

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design#39202]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-zeng-jian-biao-dan-xiang-antd-4-24-4-forked-57dn5x?file=/demo.tsx:911-929)

### Steps to reproduce

有两个 Form Item 值, 一个是单选组RadioGroup, 一个是名称列表Form.List.
期望切换 RadioGroup 的时候, 如果值是 ALLOW 时, 遇到 name list 是空的, 则在 names List 中初始化一个 name alice,  如果有数据, 就不用初始化
1. 从 No 单选切换到 Allow list, 出现一个初始 name alice 值
2. 可以继续添加 name bob
3. 切换回 No, 再切换到 Allow list, 不清空, 不重置, 保持原来的 alice 和 bob

<img width="155" alt="image" src="https://user-images.githubusercontent.com/16385443/205312133-498fda4c-5882-4755-b1a1-97dc8264698c.png">
<img width="310" alt="image" src="https://user-images.githubusercontent.com/16385443/205312166-55a19bed-9635-4853-ad96-1a1ff6cb7b49.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/16385443/205312195-12a4f322-6ce8-4d75-bb0e-21a7e3074140.png">
<img width="198" alt="image" src="https://user-images.githubusercontent.com/16385443/205312226-5f73fb73-7180-48a5-a7ef-75f70a837110.png">
<img width="319" alt="image" src="https://user-images.githubusercontent.com/16385443/205312257-3eaf753b-1d19-4807-a6f9-d4ed81290032.png">

### What is expected?

 1. 从 No 单选切换到 Allow list, 出现一个初始 name alice 值
2. 可以继续添加 name bob
3. 切换回 No, 再切换到 Allow list, 不清空, 不重置, 保持原来的 alice 和 bob

### What is actually happening?

依旧重置为 alice

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by powerdong** [comment]
是不是因为 && 导致组件卸载掉了？  试试这样？
```jsx
 <div
          style={{
            display: type === "ALLOW" ? "block" : "none"
          }}
        >
```

**Comment by xuoutput** [comment]
> ```js
> style={{
>             display: type === "ALLOW" ? "block" : "none"
>           }}
> ```

嗯 可以

**Comment by zombieJ** [comment]
嗯，`useWatch` 监听的是 Field。Field 卸载后内容为空是符合预期的。解法就如上面你们聊的。这个 issue 先关了哈~
