### ISSUE TITLE
Card Component with Actions: background color covers card's rounded corners

### ISSUE THREAD

**Issue by jeffmarshall** [ant-design/ant-design#39203]
### Reproduction link

[https://ant.design/components/card#components-card-demo-meta](https://ant.design/components/card#components-card-demo-meta)

### Steps to reproduce

It can be seen in the example in the component documentation. The bottom corners of the Card with the actions; they're overlapped by the background of `.ant-card-actions`.

### What is expected?

Cards should have 4 rounded corners by default. Cards with actions have their bottom-left and bottom-right actions covered.

### What is actually happening?

`.ant-card-actions` has a `background-color` property that covers the rounded corners

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 18.2.0 |
| System | MacOS 13.0 |
| Browser | Chrome 107 |

**Comment by MuxinFeng** [comment]
i will create a pr ~
