### ISSUE TITLE
Theme Editor page is blank

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [ant-design/ant-design#39211]
### Reproduction link

[https://ant-design.github.io/antd-token-previewer/~demos/docs-theme-editor-simple](https://ant-design.github.io/antd-token-previewer/~demos/docs-theme-editor-simple)

### Steps to reproduce

The link that I have shared is not working.

### What is expected?

The page should work and show the editor where we can edit things related to token modification

### What is actually happening?

the page isn't working

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.0 |
| System | windows 11  |
| Browser | chrome |

**Comment by afc163** [comment]
https://ant-design.github.io/antd-token-previewer/~demos/docs-editor-demo-theme-editor-simple

**Comment by ThePiyushAggarwal** [comment]
Thank you! @afc163 
But the link isn't update here.
https://ant.design/docs/react/customize-theme#how-to-debug-your-theme

**Comment by afc163** [comment]
PR is welcome to update urls

**Comment by sucaifenxiang** [comment]
主题编辑器不显示保存和导出按钮
