### ISSUE TITLE
DatePicker and RangePicker flicker when close in Firefox

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#39222]
https://user-images.githubusercontent.com/507615/201565729-4e4b7e83-27aa-402a-aa69-0c0854c2850e.mov

<img width="755" alt="图片" src="https://user-images.githubusercontent.com/507615/201565803-dcb290af-a1c2-42e0-bde4-1aa7b5e8779c.png">

_Originally posted by @afc163 in https://github.com/ant-design/ant-design/issues/38540#issuecomment-1312975020_

**Comment by afc163** [comment]
RangePicker 问题非常明显。

**Comment by acyza** [comment]
对react.js和ant-design不熟，但初步判断可能是`DatePicker`面板回收动画中多次切换`Align`组件的`disabled`值导致，我尝试把https://github.com/react-component/trigger/blob/5.x/src/Popup/PopupInner.tsx#L214这里改成`if (!visible || (align !== null && align !== void 0 && align.points && (status === 'align' || status === 'stable'))) {`它关闭时就不重复播放动画了。

**Comment by acyza** [comment]
@zombieJ

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/41090
