### ISSUE TITLE
官网上的5.0 研发 > 定制主题 > 主题编辑器 无法打开

### ISSUE THREAD

**Issue by xzzor** [ant-design/ant-design#39221]
### Reproduction link

[https://ant.design/docs/react/customize-theme-cn](https://ant.design/docs/react/customize-theme-cn)

### Steps to reproduce

定制主题（https://ant.design/docs/react/customize-theme-cn）文档里：
调试主题章节里的主题编辑器 url 无法打开：https://ant-design.github.io/antd-token-previewer/~demos/docs-theme-editor-simple

### What is expected?

主题编辑器 url 正常 https://ant-design.github.io/antd-token-previewer/~demos/docs-theme-editor-simple

### What is actually happening?

https://ant-design.github.io/antd-token-previewer/~demos/docs-theme-editor-simple
空白页面

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react  |
| System | windows |
| Browser | edge |

---
调试主题
我们提供了帮助用户调试主题的工具：主题编辑器

你可以使用此工具自由地修改 Design Token，以达到您对主题的期望。

**Comment by afc163** [comment]
欢迎来 PR 修改掉 https://github.com/ant-design/ant-design/issues/39211#issuecomment-1336145985
