### ISSUE TITLE
通过 colorBgBase 或 colorBgLayout 都无法改变 Layout 的 backgound

### ISSUE THREAD

**Issue by wood3n** [ant-design/ant-design#39227]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ding-bu-ce-bian-bu-ju-tong-lan-antd-5-0-3-forked-vxvncq?file=/index.tsx)

### Steps to reproduce

[![Edit 顶部-侧边布局-通栏 - antd@5.0.3 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ding-bu-ce-bian-bu-ju-tong-lan-antd-5-0-3-forked-vxvncq?fontsize=14&hidenavigation=1&theme=dark)

### What is expected?

能够通过 colorBgBase 或 colorBgLayout 改变 Layout 的 background

### What is actually happening?

Layout 的 background 无法通过 colorBgBase 或 colorBgLayout 这两个 token 改变

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18 |
| System | windows10 |
| Browser | chrome 105 |

**Comment by MadCcc** [comment]
The background-color of Layout content is inherit from `.ant-layout`, which is affected by styles from demo. 
So it will work if you remove the styles in `index.css`.

**Comment by wood3n** [comment]
so i need to use `theme.useToken` to change the `background-color` of `Header` or `Sider`.

```js
  const {
    token: { colorBgContainer },
  } = theme.useToken();
```

**Comment by joshhopkins** [comment]
@MadCcc it appears that when using `theme.defaultAlgorithm` that `Layout.Content` isn't inheriting `colorBgContainer`. Is this expected?
