### ISSUE TITLE
dropdown submenu items couldnot hide when mouse move outside

### ISSUE THREAD

**Issue by frankzhiwen** [ant-design/ant-design#39232]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/67bpwv?file=/index.tsx)

### Steps to reproduce

  move to dropdown menu
  move to submenu
  move outside of submenu

### What is expected?

submenu items disappear

### What is actually happening?

submenu items always show

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in 5.0.4 https://github.com/ant-design/ant-design/pull/39235 

https://codesandbox.io/s/duo-ji-cai-dan-antd-5-0-3-forked-zdyksb

**Comment by afc163** [comment]
@zombieJ https://github.com/ant-design/ant-design/pull/39235 这个貌似不是修复丢失动画的问题，应该是修复『二级菜单』不会消失的问题？另外 PR 里关联了 https://github.com/ant-design/ant-design/issues/39234 感觉也有点奇怪，没太看懂。
