### ISSUE TITLE
ios 15.7.1 chrome/ safari error 

### ISSUE THREAD

**Issue by robozb** [ant-design/ant-design#39234]
![99F30DB0-83CC-4EC7-ABF5-8DB8B3BFFA46](https://user-images.githubusercontent.com/8656998/205475359-0053a36e-bac5-4cad-8db6-94c4abed4947.jpeg)
### Reproduction link

[https://ant.design/](https://ant.design/)

### Steps to reproduce

open the site

### What is expected?

useable site

### What is actually happening?

unavailable site

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | n/a |
| System | ios 15.7.1 |
| Browser | chrome/ safari |

---
i can t attach my sample image!

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/39233#issuecomment-1336322315

Thx for feedback. Let me handle this : )
