### ISSUE TITLE
Table 当 checkStrictly 为 false 时， preserveSelectedRowKeys 属性不生效

### ISSUE THREAD

**Issue by baibaibai455** [ant-design/ant-design#39238]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yuan-cheng-jia-zai-shu-ju-antd-4-24-4-forked-7u16xz?file=/demo.js:161-168)

### Steps to reproduce

在第一页勾选，然后跳转第二页，如果勾选的话，第一页的将消失，违背了属性preserveSelectedRowKeys

 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/47173675/205479873-b3d7db67-ed71-4cfb-bdb7-bdd83800732f.png">

![Jietu20221204-下午35452-HD](https://user-images.githubusercontent.com/47173675/205480558-f0616310-0eb7-454a-a088-aa2150b1406f.gif)

 

### What is expected?

当数据被删除时仍然保留选项的 key    ，当切换分页时保留勾选项的key

### What is actually happening?

未保留其他页面勾选项

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | ^17.0.2 |
| System | mac |
| Browser | 版本 107.0.5304.121（正式版本） (x86_64) |

**Comment by baibaibai455** [comment]
![Jietu20221204-下午35452-HD](https://user-images.githubusercontent.com/47173675/205480590-11c45866-d6ca-42b2-a136-ec672d00751b.gif)

**Comment by afc163** [comment]
Duplicate of #30482

**Comment by baibaibai455** [comment]
> Duplicate of #30482

请详细看我的问题 以及代码片段，问题并没有解决
