### ISSUE TITLE
官网首页的“搜索组件”的菜单，无法使用鼠标滚轮向下移动，页面向下滚动。

### ISSUE THREAD

**Issue by Remexllee** [ant-design/ant-design#3923]
#### 发生问题的环境是：

- antd 版本: 2.4.2
- 操作系统及其版本: Mac OX Sierra
- 浏览器及其版本: 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

在使用Ant Design 首页中的 “搜索组件” 出现结果菜单之后，使用鼠标滚轮向下滚动结果的时候，菜单会消失，然而主页向下滚动。

**Comment by benjycui** [comment]
好像玉伯说过要把首页的动画去掉？这样就没这个问题了。

@jljsj33 确认下？

**Comment by jljsj33** [comment]
改版后的吧。。。
