### ISSUE TITLE
Switch组件当checkedChildren为空 unCheckedChildren 有值时，unCheckedChildren 不显示

### ISSUE THREAD

**Issue by 786259135** [ant-design/ant-design#39231]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ordxnp?file=/index.js)

### Steps to reproduce

切换Switch开关状态

### What is expected?

checkedChildren为空，unCheckedChildren 有值时，unCheckedChildren 也需要显示出来

### What is actually happening?

checkedChildren为空，unCheckedChildren 有值时，unCheckedChildren 不显示

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18 |
| System | macos  |
| Browser | Chrome last |

**Comment by weeqe** [comment]
checkedChildren或者unCheckedChilren没内容 高度没有撑开
