### ISSUE TITLE
ios 15.7.1 chrome/ safari error 

### ISSUE THREAD

**Issue by robozb** [ant-design/ant-design#39233]
the site is completely unavailable 

![AA1C7863-476A-43CA-8013-BC6DBDC405E6](https://user-images.githubusercontent.com/8656998/205475212-358ed1d0-8754-4dfe-a1a7-035b0c2a2a2f.jpeg)

**Comment by zombieJ** [comment]
Official site is follow the latest modern browser version. If want to compatible with legacy browser, pls follow tips in the screenshot.

**Comment by zombieJ** [comment]
Merge into #39234
