### ISSUE TITLE
4.x 站点访问速度慢

### ISSUE THREAD

**Issue by shijiatongxue** [ant-design/ant-design#39237]
### Reproduction link

[https://4x.ant.design/components/form-cn/](https://4x.ant.design/components/form-cn/)

### Steps to reproduce

访问即可

### What is expected?

速度快一点

### What is actually happening?

拉取 index.js 用了 1 分钟

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/26477537/205478183-b73b55ae-14ce-4aa8-890a-713174d039f2.png">

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | latest |
| System | mac os |
| Browser | chrome |

**Comment by shijiatongxue** [comment]
用手机访问也是比较慢。

**Comment by zombieJ** [comment]
https://4x-ant-design.antgroup.com/

访问国内镜像哈~
