### ISSUE TITLE
Message RTL Problem

### ISSUE THREAD

**Issue by shadoworion** [ant-design/ant-design#39244]
### Reproduction link

[https://ant.design/components/message?direction=rtl](https://ant.design/components/message?direction=rtl)

### Steps to reproduce

Click to open the message

### What is expected?

You see a message on the top in the middle of the screen

### What is actually happening?

You see a message on the top on the left side of the screen

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.2.0 |
| System | macOS 13.0.1 |
| Browser | Edge 107.0.1418.68 |

**Comment by Yuiai01** [comment]
let me try~

**Comment by Yuiai01** [comment]
Hello, I found that simply removing this line of style from the message component would solve the problem.
![image](https://user-images.githubusercontent.com/112228030/205491577-e9748f98-5403-4940-a5ca-6d2ee99024a3.png)

**Comment by shadoworion** [comment]
> Hello, I found that simply removing this line of style from the message component would solve the problem. ![image](https://user-images.githubusercontent.com/112228030/205491577-e9748f98-5403-4940-a5ca-6d2ee99024a3.png)

Hi, so how can I provide a quick fix, or do I need to wait for a new version?

**Comment by xhh0223** [comment]
> let me try~

+++
