### ISSUE TITLE
引入Popconfirm 报 'className' of undefined错误

### ISSUE THREAD

**Issue by zwz111** [ant-design/ant-design#3924]
#### 发生问题的环境是：

- antd 版本:2.4.3
- 操作系统及其版本:win
- 浏览器及其版本: Google Chrome版本 54.0.2840.99 m

#### 您做了什么？请提供尽可能详细的重现步骤。

引入antd  的 Popconfirm

报错  Uncaught TypeError: Cannot read property 'className' of undefined

如果不用这个组件 代码正常

代码如下

const columns = [
    {title: '昵称', dataIndex: 'nickName', key: 'nickName'},
    {title: '登录名', dataIndex: 'loginName', key: 'loginName'},
    {title: '姓名', dataIndex: 'name', key: 'name', render: (text)=><a href="#">{text}</a>},
    {title: '操作', dataIndex: '', key: 'operation', render: (text)=>(
      <p>
        <a>编辑</a>
        <Popconfirm title="确定要删除吗"
                    onConfirm={()=>Message.success("点击了确认删除")}
                    okText="Yes"
                    cancelText="No"
        >删除</Popconfirm>
      </p>
    )}
  ];

**Comment by yesmeck** [comment]
能帮我们重现一下吗 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
```diff
<Popconfirm>
-  删除
+  <span>删除</span>
</Popconfirm>
```

**Comment by afc163** [comment]
Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by benjycui** [comment]
感觉可以做一层适配，如果 `children` 不是 ReactElement，就自动包上 `span` 标签？

**Comment by benjycui** [comment]
在 antd 这一层做适配即可。

**Comment by davidfurlong** [comment]
Similar issue with `Dropdown` I think

**Comment by Carrie999** [comment]
Similar issue with Dropdown I think
