### ISSUE TITLE
Input Textarea break new line work incorrect with Shift + Enter

### ISSUE THREAD

**Issue by phatify** [ant-design/ant-design#39240]
### Reproduction link

[https://ant.design/components/input#components-input-demo-textarea](https://ant.design/components/input#components-input-demo-textarea)

### Steps to reproduce

1. Go to link minimal reproduction above.
2. Add onPressEnter prop to TextArea
3. Try press both Shift   Enter to break new line.

### What is expected?

When press both **Shift + Enter**, `TextArea `**shouldn't** trigger `onPressEnter()`

### What is actually happening?

onPressEnter() trigger incorrect when break new line by Shift   Enter

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | React latest version |
| System | Windows 10 |
| Browser | Chrome latest version |

**Comment by afc163** [comment]
I think you should handle this situation in onKeyDown.
