### ISSUE TITLE
`onResize` and `onResizeCapture` required tags for `segmented` component

### ISSUE THREAD

**Issue by richxcame** [ant-design/ant-design#39251]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js)

### Steps to reproduce

when I use segmented component in antd version 5.0.2 with typescript `onResize` and `onResizeCapture` tags are required tag. So if I want to avoid  eslint error i must give them undefined or add a comment for disabling eslint stuff. 

### What is expected?

Remove required `onResize` and `onResizeCapture` tags from rc-segmented

### What is actually happening?

Just eslint bug

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | react 17.0.2 |
| System | macOS big sur |
| Browser | Chrome latest |

**Comment by richxcame** [comment]
<img width="1280" alt="Screen Shot 2022-12-05 at 01 00 59" src="https://user-images.githubusercontent.com/76844818/205512685-b550a548-3b3d-4665-8b96-7204d6eb54cb.png">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/38537#issuecomment-1312669009
https://github.com/ant-design/ant-design/issues/39004#issuecomment-1327594537
https://github.com/ant-design/ant-design/issues/38898#issuecomment-1324859923

**Comment by richxcame** [comment]
ping @afc163

I  updated `@types/react` to "^17.0.52" and `@types/react-dom` "^17.0.18". And also deleted `node_modules` + `package-lock.json`  => reinstall packages as you said here [#38898 comment](https://github.com/ant-design/ant-design/issues/38898#issuecomment-1324859923) and here [#39004 comment](https://github.com/ant-design/ant-design/issues/39004#issuecomment-1327594537). But it didn't help.

**Comment by librehat** [comment]
@afc163 I'm also having the same issue.. React v17 latest with ant design lates v4...

**Comment by mayank-cubyts** [comment]
@afc163  Same issue. 
antd v5.1.4, react v17 and @types/react to "^17.0.52" and @types/react-dom "^17.0.18".

**Comment by ILoveChy** [comment]
@afc163  因为18版本的children类型问题,暂时没办法升级到react18版本,安装17版本的最新type包并不会解决上述问题
