### ISSUE TITLE
Ant Design 5 如何获取主题色

### ISSUE THREAD

**Issue by yetrun** [ant-design/ant-design#39253]
### What problem does this feature solve?

我想要做一个自定义的错误展示组件，文字想要显示为红色。但我不想用 `color: red`，而想用 Ant Design 里面提供的红，类似于 `<Button danger>` 提供的那种红。

### What does the proposed API look like?

在网上搜索的答案是引入一个 less 文件：

```less
@import '~antd/dist/antd.less';
```

但我发现 Ant Design 的版本 5 没有这个文件了。版本 5 能够使用什么方式获取到主题颜色呢？

**Comment by zombieJ** [comment]
[使用 Design Token](https://ant.design/docs/react/customize-theme-cn#%E4%BD%BF%E7%94%A8-design-token)

**Comment by lxmbetterman** [comment]
到底如何在自定义的less中获取 primaryColor 这样的主题颜色值啊？？ 文档就不能提一嘴吗
