### ISSUE TITLE
Select allowClear时点击clear后，自动focus但下拉列表未展示

### ISSUE THREAD

**Issue by h1orz** [ant-design/ant-design#39258]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-4-24-4-forked-0930jn)

### Steps to reproduce

选中任意选项，再点击Clear Icon。
此时Select自动Focus。

### What is expected?

展示下拉列表。

### What is actually happening?

未展示下拉列表。

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 16  |
| System | Window/Mac |
| Browser | 107  |

**Comment by afc163** [comment]
设计如此。

https://github.com/ant-design/ant-design/discussions/39229

**Comment by h1orz** [comment]
sad.
