### ISSUE TITLE
How to hide the OK and Cancel buttons of antd Modal?

### ISSUE THREAD

**Issue by soulmachine** [ant-design/ant-design#3925]
This is a question about usage instead of issues, I've also posted this question on [Stackoverflow here](http://stackoverflow.com/questions/40699879/how-to-hide-the-ok-and-cancel-button-of-antd-modal)

I wrote a `Login` component, which is basically as follows:

    const Login = (
      <Modal>
        <NormalLoginForm/ 
         ...
        </NormalLoginForm >
      </Modal>
    )

The `NormalLoginForm` component is from the official website here <https://ant.design/components/form/>

I don't need the two Buttons `OK` and `Cancel` on the Modal, how to hide the two buttons ?

Also are there any good examples about how to integrate login and signup buttons with the navigation menu?

**Comment by afc163** [comment]
https://ant.design/components/modal/#components-modal-demo-footer

**Comment by soulmachine** [comment]
@afc163 Thanks!

**Comment by NugzarGaguliya** [comment]
what about X in the top right corner?

**Comment by erdemkeren** [comment]
If you want to disable one of them, this helps you utilize the other button implementations like `onOk`.:

```javascript
<Modal
    cancelButtonProps={{ style: { display: 'none' } }}
/>
```

**Comment by mbv401920150** [comment]
> https://ant.design/components/modal/#components-modal-demo-footer

It's a shame that cannot be able into Modal.method() component

**Comment by timtamimi** [comment]
If anyone's looking at this in the future, the thing you're looking for is: `<Modal footer={null} />`

**Comment by NookieGrey** [comment]
What about Modal.open ?

**Comment by luisalbertodev** [comment]
In my case I am using Modal.info which I pass in a function, to pass its properties I do it through objects. I hope it serves someone. 😉 This worked for me.
const modal = Modal.info({
			title: "Title",
			content: 'Lorem insump'
			okButtonProps: { disabled: true, className: "modal-footer-hiden-button" },
		});

**Comment by vishnusnathann** [comment]
This helped me.
https://stackoverflow.com/questions/40699879/how-to-hide-the-ok-and-cancel-buttons-of-antd-modal

**Comment by javiermendozain** [comment]
Easy 🤔 solution, pass prop `footer={null}`  😍

more here: https://ant.design/components/modal/#components-modal-demo-footer

**Comment by adnanHussain07** [comment]
<Modal
        footer={null}
      >
