### ISSUE TITLE
timeline 组件 timeline.item 写在子组件中会丢失样式

### ISSUE THREAD

**Issue by herbertxy** [ant-design/ant-design#39265]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-qian-antd-5-0-3-forked-ur8cx9?file=/demo.tsx)

### Steps to reproduce

```
 <Timeline mode={mode}>
        {Array.from(Array(5).keys()).map((v) => {
         return <Item />
        })}
      </Timeline>
```
```
const Item: React.FC = (props) => {
  return <Timeline.Item label="lable">content----</Timeline.Item>;
};
```

### What is expected?

期望timeline.item 可以写在子组件中

### What is actually happening?

写在子组件，样式异常，丢失

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 16.18 |
| System | win10 |
| Browser | chrome 最新 |

**Comment by afc163** [comment]
https://codesandbox.io/s/biao-qian-antd-5-0-3-forked-vceg2r?file=/demo.tsx

**Comment by herbertxy** [comment]
label还是不正常呢 @afc163 
![image](https://user-images.githubusercontent.com/19306050/205599922-7006cf01-3621-42ec-bb0b-aed8138ce50e.png)

 https://codesandbox.io/s/biao-qian-antd-5-0-3-forked-5o0qku

**Comment by afc163** [comment]
下面的正常的也有点问题。。

**Comment by afc163** [comment]
现在是通过 cloneElement 后看 label 属性是否存在来判断要切换到这种布局模式的，感觉需要加个属性显式声明。

**Comment by Erdrian** [comment]
黑暗模式下，自定义节点图标的背景颜色还有问题

**Comment by Wxh16144** [comment]
我去看看这个问题～

**Comment by Wxh16144** [comment]
貌似有点棘手，子组件 clone 后添加了一些 className 

https://github.com/ant-design/ant-design/blob/122b3f1041039ed22297fbe330c7dbde376acfde/components/timeline/Timeline.tsx#L78-L84

业务二次封装 Item 的时候应该需要透传 className 才可以.

```tsx
const Item: React.FC = ({ className, ...restProps }) => {
  return (
    <Timeline.Item
      className={classNames('your-custom-cls', className)}
      label="lable"
      {...restProps}
    >
      content----
    </Timeline.Item>
  );
};
```

**Comment by MadCcc** [comment]
往后不建议封装子组件了，逐渐都会废弃 jsx，转向数据驱动

**Comment by heiyu4585** [comment]
这个先关了,后续建议使用items
