### ISSUE TITLE
Remove Highlight text when searching in table

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#39260]
### Reproduction link

[https://i6ftqn.csb.app/](https://i6ftqn.csb.app/)

### Steps to reproduce

1. Search Jim Green in name
2. Click again the search icon

### What is expected?

Jim Green name should not be highlighted

### What is actually happening?

Jim Green name is highlighted

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | 17.0.2 |
| System | Mac Os Monterey |
| Browser | Google Chrome |

**Comment by afc163** [comment]
It is a demo, you can change it as you need.

**Comment by tempoeric** [comment]
i mean @afc163 can we remove the highlighted text in the field? is there a props for this? or css changed?
<img width="1335" alt="Screenshot 2022-12-05 at 1 26 19 PM" src="https://user-images.githubusercontent.com/42777871/205556149-c7d51088-2e15-41bc-8f51-d891560f1717.png">
