### ISSUE TITLE
Broken official site for Linux users

### ISSUE THREAD

**Issue by Lantianyou** [ant-design/ant-design#39269]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-y9vgcf)

### Steps to reproduce

no

### What is expected?

no

### What is actually happening?

no

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | latest |
| System | Ubuntu |
| Browser | Latest Chrome |

**Comment by Lantianyou** [comment]
Not an expert like you guys, but I'll try :)

**Comment by Lantianyou** [comment]
I ran the code snnieppet in the local environment, seems `supportedWhere` is true in my Linux machine, however, the official is site broken in same browser 

![image](https://user-images.githubusercontent.com/37259750/205614464-ef53b938-9ef1-483c-b6d4-f9be21050560.png)

**Comment by zombieJ** [comment]
<img width="53" alt="截屏2022-12-05 18 28 09" src="https://user-images.githubusercontent.com/5378891/205614794-5cc19e74-20e6-48be-ab37-483dbe5e27e4.png">

Find it. Let me handle this.

**Comment by Lantianyou** [comment]
Mind if sharing why? Quite curious.
