### ISSUE TITLE
menu layout 2个组件有 theme 属性

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#39263]
### What problem does this feature solve?

1、menu layout 2个组件有 theme 属性值默认不要设置
2、如果用户设置了，light 对应 defaultAlgorithm 计算的值，dark 对应 darkAlgorithm 计算的值

### What does the proposed API look like?

v5 api 文档对 theme 属性做说明

**Comment by MadCcc** [comment]
Menu 和 Layout 的 theme 是遗留属性，和 v5 的定制主题没有关系
