### ISSUE TITLE
AutoComplete & Select 组件里的:after会覆盖组件下面的内容，导致点击等鼠标事件被拦截

### ISSUE THREAD

**Issue by awaw00** [ant-design/ant-design#3927]
Repo: http://codepen.io/awaw00/pen/WorMPL?editors=0010

这个不可见的 :after 是出于什么考虑，如果是为了给底部一个边距为什么不用 margin 来实现？

**Comment by afc163** [comment]
这是一个 bug，在 https://github.com/ant-design/ant-design/issues/3855 里修复了，可以等待下一个版本发布。
