### ISSUE TITLE
How to change the tip text of getFieldDecorator dynamically?

### ISSUE THREAD

**Issue by soulmachine** [ant-design/ant-design#3928]
This is a question about usage instead of issues, I've also posted this question in [Stackoverflow here](http://stackoverflow.com/questions/40705924/how-to-change-the-tip-text-of-getfielddecorator-dynamically)

In the example component `NormalLoginForm` from the official website here <https://ant.design/components/form/>, for the username item,

```
<FormItem>
  {getFieldDecorator('userName', {
    rules: [{ required: true, message: 'Please input your username!' }],
  })(
      <Input addonBefore={<Icon type="user" />} placeholder="Username" />
    )}
</FormItem>
```

If a user enters an incorrect password and the server returns an error, how to  show and change the message from `Please input your username!` to `Wrong username or password` ?

**Comment by yesmeck** [comment]
https://ant.design/components/form/#components-form-demo-register

参考里面 password  的验证。

**Comment by soulmachine** [comment]
@yesmeck Thanks ! With your tip I've made it work, [here](https://github.com/soulmachine/meteor-tutorial/commit/e4bb68364bc9afd300ec3399bd4c95597810dec9) is my code in case other  people have the same quesion

**Comment by xiangfengsu** [comment]
@yesmeck 我有个问题，我做用户登录，点击登录按钮后，申请接口判断用户信息，如果用户名或密码错误，怎样动态改变表单错误提示信息？谢谢！

**Comment by yesmeck** [comment]
你看楼上的例子啊 https://github.com/soulmachine/meteor-tutorial/commit/e4bb68364bc9afd300ec3399bd4c95597810dec9#diff-65f998d22ee0bb1cc7b63cf201ae2429R71

**Comment by xiangfengsu** [comment]
他的需求和我不太一样，他是对表单通过接口实时校验，我是表单输入合法后，当点击登录按钮后，通过接口判断输入的信息是否合法，如果不合法把错误的表单信息显示出来，如：用户名错误或密码错误

**Comment by yesmeck** [comment]
用 `setFields` 自己设置下字段的错误信息。
