### ISSUE TITLE
descriptions如果包含的是子组件而不是DescriptionItem则不会渲染

### ISSUE THREAD

**Issue by nabaonan** [ant-design/ant-design#39286]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cxw52q?file=/index.js)

### Steps to reproduce

使用description组件
创建子组件返回一个DescriptionItem
使用descriptions包含创建的子组件，不会渲染出来

### What is expected?

descriptions正常渲染descriptionItem

### What is actually happening?

没有正常渲染descriptionItem子组件

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react |
| System | macos 12 |
| Browser | 107.0.5304.110 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27411#issuecomment-717267040
