### ISSUE TITLE
Menu组件展开缩起内嵌菜单时 悬浮菜单意外显示

### ISSUE THREAD

**Issue by jianhuagao** [ant-design/ant-design#39283]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7nfh7x)

### Steps to reproduce

1.缩起内嵌菜单 2.鼠标悬浮到一个二级菜单上 3.迅速展开缩起的内嵌菜单 具体操作看gif

### What is expected?

正常显示

### What is actually happening?

菜单异常显示

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome108 |

---
具体操作看gif
![bug](https://user-images.githubusercontent.com/39371828/205806626-534c84d3-b8a8-45a1-86a9-756d0c98ffd8.gif)

**Comment by jianhuagao** [comment]
@afc163

**Comment by afc163** [comment]
我重现不出来。。升到 5.0.5 试试？

**Comment by nuintun** [comment]
@afc163 手速要快，折叠状态下移动上去展开二级菜单，快速移动到折叠按钮打开，很容易复现！

![image](https://user-images.githubusercontent.com/1730277/206859369-eb238256-e054-4a12-bde3-046ea7f5b7ef.png)

**Comment by jianhuagao** [comment]
> 我重现不出。。升到5.0.5试试？
把控制台动画调慢试试，因为官方示例的二级菜单在第四位，所以操作起来需要手速。我项目的第一位就有二级菜单，所以非常容易复现。
@afc163 
![bug3](https://user-images.githubusercontent.com/39371828/206942435-f00e3c2d-7738-4e27-b210-261c3586081a.gif)
![bug4](https://user-images.githubusercontent.com/39371828/206942794-4bfeee5b-4f48-421d-b356-612a65d51d1e.gif)

**Comment by tankle0** [comment]
我也遇到了，目前发现是因为menu组件被Layout.Sider组件包裹的原因，具体不知道为啥，不用Sider组件包裹就没这个问题，只不过布局样式需要手动修改

**Comment by tankle0** [comment]
> 我重现不出来。。升到 5.0.5 试试？

https://github.com/tankle0/reactHome
我这个项目也遇到这个问题，目前发现是因为layout.sider包裹

**Comment by tankle0** [comment]
@afc163 
https://github.com/tankle0/reactHome
我这个项目也遇到这个问题，目前发现是因为Layout.Sider包裹的原因，如果二级菜单折叠，鼠标悬浮在选中的菜单所在一级菜单上，下次展开就没问题了

**Comment by 1764720201** [comment]
我感觉是因为 收缩的时候mode被改了 默认是 vertical    你设置了inline但是 收缩的时候mode被改了 应该是bug 我也遇到了这种情况
