### ISSUE TITLE
antd 5 自定义主题，设置品牌主色不生效

### ISSUE THREAD

**Issue by byehoney** [ant-design/ant-design#39296]
### Reproduction link

[https://github.com/byehoney/my-imooc-react-app](https://github.com/byehoney/my-imooc-react-app)

### Steps to reproduce

页面自定义主题已经配置好， 页面有个按钮，可直接查看

### What is expected?

页面主题色配置了绿色，期望 <Button type='primary'>333</Button> 按钮展示绿色

### What is actually happening?

实际现在展示仍然是 primary初始的蓝色， 但是悬浮的时候按钮颜色变成了绿色

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | ^18.1.0 |
| System | windows |
| Browser | 谷歌 |

**Comment by MadCcc** [comment]
配置在哪个文件

**Comment by MadCcc** [comment]
被 v4 样式污染，考虑到项目中没有直接依赖 v4，两种解决方案：
1. 排查哪个依赖引入了 v4 样式，去掉。
2. 使用 ConfigProvider 给 v5 的 antd 组件替换 `prefixCls`

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/205867474-7e25a236-ab94-46f3-b522-752004019c0e.png)
