### ISSUE TITLE
antd.Upload 直传 oss 必须要初始化，不能实时获取到最新签名上传文件？

### ISSUE THREAD

**Issue by sanheng** [ant-design/ant-design#39291]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/a-li-yun-oss-antd-5-0-4-forked-99z8s1?file=/demo.tsx)

### Steps to reproduce

1、点击上传
2、控制台没有打印获取到最新的 oss 签名信息
3、文件没有上传成功

### What is expected?

获取到最新的 oss 签名信息并上传文件成功。

### What is actually happening?

没有获取到最新的 oss 签名信息，感觉就像没有执行到上传。

| Environment | Info |
| --- | --- |
| antd | 5.0.4/4.24.4 |
| React | 18.3.0 |
| System | macos@13.0.1  |
| Browser | chrome@108.0.5359.71 |

---
使用官方 demo 做了修改，改动地方是
1、把 useEffect(() => {}, []) 初始化签名的代码删掉了。
2、mockGetOSSData() 里面返回值写了定时器

我发现 mockGetOSSData() 不写定时器就没有问题，写定时器就获取不到最新的值，我测试过 axios 或 umi-request 获取签名也不行，感觉必须要同步返回才可以获取到最新的签名，要是异步请求返回就获取不到最新的签名。

之前用的是 react@17，antd@4.24.4 是可以获取到最新的 oss 签名，好像升级了 react@18 之后就不行了。

**Comment by afc163** [comment]
这是个 demo，如果有更好的方案可以自己尝试修改一下，欢迎给我 PR。

**Comment by afc163** [comment]
react 18 下 useEffect 可能会跑两次，所以这个逻辑可能会挂。

**Comment by sanheng** [comment]
> 这是个 demo，如果有更好的方案可以自己尝试修改一下，欢迎给我们 PR。

增加了 ref 来取 action 和 getExtraData 可以实现上传：
https://codesandbox.io/s/a-li-yun-oss-antd-5-0-4-forked-mm6sqh?file=/demo.tsx

猜测是 react@18 做了渲染优化，在同一个任务过程中不会取更新的 state，而是当时的 state，使用 ref 来避免没有取到最新值。
