### ISSUE TITLE
Select多选可否支持颜色自定义

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#3929]
select 支持多选时，编辑框里面会有多个tag, 可否支持 tag 自定义？我目前用的方法不太美观，不知道是否还有其他方式？详情例子。http://codepen.io/zzcode/pen/rWyaKa

**Comment by benjycui** [comment]
不支持。

而且感觉这做出来也不好看啊。

**Comment by zhonggithub** [comment]
我改成没有颜色了
