### ISSUE TITLE
Select 组件 ， 设置style width 宽度大于200后，组件前方会出现空白

### ISSUE THREAD

**Issue by PengQingYao** [ant-design/ant-design#39298]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-0-4-forked-528fqs?file=/demo.tsx)

### Steps to reproduce

设置组件 style={{width:400}},  输入框聚焦， 光标位置不对

### What is expected?

光标在输入框的开始位置

### What is actually happening?

光标距离输入框开始位置有一段空白。

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react |
| System | windows |
| Browser | chrome 106 |

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/205869105-ecd65930-a66e-4b92-9d59-f1a93fb2cc01.png)
这样就好了
