### ISSUE TITLE
Deploy site when release version

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#39303]
类似 https://github.com/ant-design/ant-design-mobile/commit/72b8225153c4f4d23fa2c81f48b61d3a320d16eb#commitcomment-91035744

地址：https://ant-design-{version}.surge.sh

**Comment by Wxh16144** [comment]
就这段配置么: https://github.com/ant-design/ant-design-mobile/blob/72b8225153c4f4d23fa2c81f48b61d3a320d16eb/.github/workflows/doc-site.yml#L55-L68

**Comment by afc163** [comment]
差不多是的。
