### ISSUE TITLE
[Antd v5] Tour组件: TourStep 设置 type=‘primary’ 无效

### ISSUE THREAD

**Issue by passerV** [ant-design/ant-design#39307]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-idfhso)

### Steps to reproduce

‘’

### What is expected?

TourStep 可以设置 type

### What is actually happening?

设置无效

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react 18.0.0 |
| System | Mac os |
| Browser | chorme |

---
源码中好像并没有根据 TourStepProps 中的 type 做判断给出类名

**Comment by MuxinFeng** [comment]
我提个 pr 吧
