### ISSUE TITLE
Skeleton active motion broken in Safari

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#39300]
用 Safari 16.1 (18614.2.9.1.12) 打开 https://ant.design/components/skeleton-cn#components-skeleton-demo-active

1. 会闪动
2. 动画效果有时候会丢失

**Comment by afc163** [comment]
网站有报错

<img width="1502" alt="图片" src="https://user-images.githubusercontent.com/507615/205897422-a05effd0-0646-41ee-b337-a34b5cf612a4.png">

**Comment by MadCcc** [comment]
这页注水失败了

**Comment by MadCcc** [comment]
> 用 Safari 16.1 (18614.2.9.1.12) 打开 https://ant.design/components/skeleton-cn#components-skeleton-demo-active
> 
> 1. 会闪动
> 2. 动画效果有时候会丢失

似乎是个老问题了，4.x 版本也可以复现，需要优化一下动画

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/40692
