### ISSUE TITLE
Antd 4.24.5+React 18.3，受控的TextArea不能输入空格和换行

### ISSUE THREAD

**Issue by Aoy-007** [ant-design/ant-design#39308]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-zi-shu-ti-shi-de-wen-ben-yu-antd-4-24-5-forked-0vudsi?file=/demo.tsx)

### Steps to reproduce

受控组件 value.trim

### What is expected?

和textarea一样可以输入空格和换行

### What is actually happening?

不能换行不能空格

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 18.3 |
| System | win 10 |
| Browser | Chrome  108.0.5359.73（正式版本） （64 位） |

**Comment by Aoy-007** [comment]
重现片段
const App: React.FC = () => {
  const [state, setState] = React.useState("");
  React.useEffect(() => {
    console.log("trim result: ", state);
  }, [state]);
  return (
    <>
      <TextArea
        showCount
        value={state}
        maxLength={100}
        style={{ height: 120 }}
        placeholder="can resize"
        onChange={(e) => {
          setState(e.target.value.trim());
        }}
      />
    </>
  );
};

**Comment by Aoy-007** [comment]
`const App: React.FC = () => {
  const [state, setState] = React.useState("");
  React.useEffect(() => {
    console.log("trim result: ", state);
  }, [state]);
  return (
    <>
      <TextArea
        showCount
        value={state}
        maxLength={100}
        style={{ height: 120 }}
        placeholder="can resize"
        onChange={(e) => {
          setState(e.target.value.trim());
        }}
      />
    </>
  );
};`

**Comment by afc163** [comment]
这和 antd 无关，你这样写交互逻辑就是这样的。https://codesandbox.io/s/dai-zi-shu-ti-shi-de-wen-ben-yu-antd-4-24-5-forked-w2zrrt
