### ISSUE TITLE
Warning should be removed in production environment

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#3930]
Most of warnings in `antd` are not going to be removed in production, like [this](https://github.com/ant-design/ant-design/blob/master/components/form/Form.tsx#L127).

We should wrap those warning like [this](https://github.com/ant-design/ant-design/blob/master/components/index.tsx#L3-L8).

```jsx
if (process.env.NODE_ENV !== 'production') {
  if (typeof console !== 'undefined' && console.warn) {
    console.warn(`You are using prebuilt antd,
please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.`);
  }
}
```

**Comment by afc163** [comment]
https://github.com/BerkeleyTrue/warning/blob/master/warning.js#L19

**Comment by benjycui** [comment]
It will not `console.log` warning, but code are still there.

**Comment by paranoidjk** [comment]
This is a option
```
    new webpack.optimize.UglifyJsPlugin({
      compressor: {
        drop_console: true
      }
    })
```

**Comment by benjycui** [comment]
I don't think this option is smart enough to drop warning..

**Comment by benjycui** [comment]
But you can try locally.

**Comment by afc163** [comment]
构建后也省不了多少代码。

**Comment by starInEcust** [comment]
我感觉uglify也行，我这个项目不确定有多少子模块使用了antd，就想全打包进去，就不想减少，如何破~

The following are translations:
I think uglify is also feasible, I am uncertain about the number of sub-module used in the project antd, wanted to all packaged into, do not want to reduce.

**Comment by afc163** [comment]
It seems that no more console warnings is shown now: https://ant.design/
