### ISSUE TITLE
Menu collapse wrong css RTL

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#39306]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sider-antd-5-0-4-forked-dnn2bx?file=/demo.tsx)

### Steps to reproduce

when add ConfigProvider and direction rtl menu collapse left css 515px

### What is expected?

--

### What is actually happening?

in RTL is left:515px most be 117px

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18.0.0 |
| System | Windows 11 |
| Browser | Chrome 90 |

**Comment by MadCcc** [comment]
Didn't find anything wrong in reproduction. Could you provide more detail?

**Comment by BoyYangzai** [comment]
mark，晚点回家看一下
https://codesandbox.io/s/sider-antd-5-0-4-forked-1rfimf?file=/demo.tsx
新版本依旧存在

**Comment by afc163** [comment]
看上去最新版本已经解决了：https://codesandbox.io/s/sider-antd-5-0-4-forked-1rfimf?file=/demo.tsx

<img width="351" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/fabe5dd9-a66b-4d82-8ffa-050cb2c9376b">
