### ISSUE TITLE
Modal弹出导致固定定位的标题移动，如何才能避免？

### ISSUE THREAD

**Issue by three-water666** [ant-design/ant-design#39304]
### Reproduction link

[https://41vhcp.csb.app/](https://41vhcp.csb.app/)

### Steps to reproduce

点击Modal

### What is expected?

后面的简易导航栏里的文字不发生移动

### What is actually happening?

后面的简易导航栏里的文字发生了移动

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | win10家庭版 |
| Browser | Google Chrome 版本 108.0.5359.94（正式版本） （64 位） |

---
https://41vhcp.csb.app/ 是一个简易demo，绿色部分是项目的固定定位的导航栏，在点击Modal时，导航栏里的文字会发生移动，请问如何才能解决，使得点击Modal时，后面的文字不发生移动

**Comment by afc163** [comment]
这个能力看上去在 5.x 里改丢了。

**Comment by afc163** [comment]
哦，不对，你这个用法比较特殊。

**Comment by MadCcc** [comment]
滚动条挤占的空间吧

**Comment by three-water666** [comment]
> 滚动条挤占的空间吧

哦哦，我忘了说了，就是要有滚动条的情况才有这个问题，但是不知道怎么解决

**Comment by MadCcc** [comment]
两种方案：
1. 关闭 mask，这样打开 Modal 之后 body 仍可滚动
2. header 添加 `padding-right: calc(${固定距离} - 100vh + 100%)`

**Comment by afc163** [comment]
这是一个 feature，参考 bootstrap 的实现搞的。

**Comment by afc163** [comment]
>  我这里看 4.23 和 4.24 都会移动

这个对楼主的例子不生效，因为用了 fixed 元素，不受 body 样式的影响。

**Comment by afc163** [comment]
哦，这个 feature 还在，用 inject css 实现的：https://github.com/react-component/portal/blob/85e6e15ee97c70ec260c5409d9d273d6967e3560/src/useScrollLocker.tsx#L25

<img width="683" alt="图片" src="https://user-images.githubusercontent.com/507615/205883609-ed1152fb-4c6b-4bca-a46f-3f158dd3003c.png">

**Comment by afc163** [comment]
所以问题还是 fixed 元素的问题，感觉没有好办法能解决。

**Comment by MadCcc** [comment]
> 所以问题还是 fixed 元素的问题，感觉没有好办法能解决。

fixed 元素推荐还是自己写 padding
