### ISSUE TITLE
最基础的input增加字数限制配置

### ISSUE THREAD

**Issue by liu2080019** [ant-design/ant-design#3931]
项目运用了antd的大部分组件，挺好的，但是这个input没有字数限制，下面的代码是我项目之前封装的带中英文混合字数限制的，希望能把这个功能加进去呢？

-------------------------------------------分割线----------------------------------------------
'use strict';
import React from 'react';
import PureRenderMixin from 'react-addons-pure-render-mixin';
let CommonInput = React.createClass({
    mixins: [PureRenderMixin],
    chineseIng: false,//正在输入的是否是中文字符
    getDefaultProps(){
        return {
            maxChinese:100,//默认长度为50个中文 100个英文字母
            onChange:()=>{},//onChange回调方法
            value:''//初始化值
        }
    },
    render() {
        return (
            <input disabled={this.props.disabled} placeholder={this.props.placeholder} value={this.props.value} onCompositionStart={this._ststst} onCompositionEnd={this._enenen} onChange={this._changeStoreValue} type="text"/>
        );
    },
    _ststst(){
        this.chineseIng = true;
    },
    _enenen(){
        this.chineseIng = false;
    },
    _changeStoreValue(e){
        let _this = this;
        let titleMaxLength = this.props.maxChinese;
            let wx = e.target.value;//当前输入的值
            if (this._fucCheckLength(wx) > titleMaxLength) {
                wx = this._subCharStr(wx, titleMaxLength);//限制长度截取后的值
                e.target.value = wx;
            }else{
                _this.props.onChange(wx);
            }
    },

    _fucCheckLength(strTemp){
        var i, sum;
        sum = 0;
        for (i = 0; i < strTemp.length; i++) {
            if ((strTemp.charCodeAt(i) >= 0) && (strTemp.charCodeAt(i) <= 255)) {
                sum = sum + 1;
            } else {
                sum = sum + 2;
            }
        }
        return sum;
    },

    _subCharStr(str,n){
        var _len=this._fucCheckLength(str,n);
        if(_len>n){
            var _newLen=Math.floor(n/2);
            var _strLen=str.length;
            var _newStr = "";
            for(var i=_newLen;i<=_strLen;i++){
                var tmpStr = str.substr(0,i);
                if(this._fucCheckLength(tmpStr)>n){
                    return _newStr;
                    break;
                } else {
                    _newStr = tmpStr;
                }
            }
        }else{
            return str;
        }
    }
    /**
     * 操作组件中的当前数据
     * */

});

module.exports=CommonInput;

**Comment by afc163** [comment]
很好的例子，感谢建议。

关于数字限制功能可以参考这里的回复：https://github.com/ant-design/ant-design/issues/3596

**Comment by afc163** [comment]
帮你格式化了一下。

**Comment by liu2080019** [comment]
因为我们之前带字数限制的input已经上线了，现在这个input不好切了，那个#3596的校验功能又太多了

**Comment by afc163** [comment]
建议自行封装，antd 的 Input 和原生 input 基本是一致的。

**Comment by liu2080019** [comment]
ok

**Comment by mqyqingfeng** [comment]
可以使用getFieldDecorator中的rules实现字数的限制
`                                    { getFieldDecorator(`input-${item.id}`, {
                                        validateTrigger: ['onChange', 'onBlur'],
                                        rules: [{
                                            required: true, whitespace: true, message: "请输入选项内容"
                                        }, {
                                            type: 'string', max: 100, message: '最多100个字符'
                                        }],
                                        initialValue: item.name
                                   })(
                                       <Input placeholder="选项内容" />
                                   )}`

**Comment by HopeLyn** [comment]
@liu2080019  在新版本的 Chrome 中 compositionend 事件后不会再触发 input 事件，所以 onCompositionEnd 事件的处理中可能要加上 onChange 的逻辑。

**Comment by ctq123** [comment]
https://github.com/ctq123/antd-input 可以解决
