### ISSUE TITLE
V4 Dropdown MenuItem disabeld 和 danger 样式优先级问题

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#39322]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-ip8ypb?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

dropdown menu items 

### What is expected?

表现与button一致

### What is actually happening?

![image](https://user-images.githubusercontent.com/23520283/205949536-4b5e2a9a-086d-446c-82a5-570480b0b9ab.png)

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 17.0.2 |
| System | windows 11 |
| Browser | Microsoft Edge 107.0.1418.62 (正式版本) (64 位) |

**Comment by samyarkd** [comment]
I'd like to contribute to this issue and fix it. Would you assign me ?

**Comment by afc163** [comment]
sure.

**Comment by yoyo837** [comment]
Close by #39434
