### ISSUE TITLE
Table 组件的每一列是否可以不用每一列都设置width，自动撑开表格宽度出现滚动条

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design#3932]
如果列的数据过长，不指定每一列的宽度，在小屏幕上面数据自动换行。导致数据显示混乱
![qq 20161121121354](https://cloud.githubusercontent.com/assets/4498796/20470492/1f2dbc34-afe4-11e6-85b0-8be1fca7e08b.png)

这种情况我指定`` scroll={{x: true, y: 500}} `` 是不生效的，x为true或者固定值都没有用。必须每一列都设置宽度。这个能优化么

**Comment by afc163** [comment]
`scroll={{x: true, y: 500}}` 配合以下代码：

```jsx
const column = [{
  render() {
    return <div style={{ whiteSpace: 'nowrap' }}></div>
  }
}]
```

**Comment by Sean-Snow** [comment]
这样也不行呢，之前看过文档， 如果不指定每一列的宽度，表头和内容就不整齐了
![qq 20161121122421](https://cloud.githubusercontent.com/assets/4498796/20470652/74b3a9f6-afe5-11e6-8a23-8407a09c5572.png)

**Comment by afc163** [comment]
嗯，如果有固定表头，确实无解，只能指定宽度。

**Comment by Sean-Snow** [comment]
我的表头没有固定么。都是很普通的column

**Comment by afc163** [comment]
scroll.y 设置了就是固定表头。

**Comment by Sean-Snow** [comment]
谢谢了，去掉 scroll.y 基本上解决了。

**Comment by hitzzc** [comment]
请问后续有计划支持固定表头下不指定width吗？
