### ISSUE TITLE
Customize datepicker font family problem

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#39327]
### What problem does this feature solve?

When use generatePicker for generate datepicker ConfigProvider theme font family not effected and just show default font family

### What does the proposed API look like?

Please fix it

**Comment by devuxer** [comment]
With v5.1, no matter what I set the `fontFamily` to in `configProvider`, it renders Times New Roman. This isn't specific `DatePicker`, it affects all components as far as I can tell, including `Typography.Text`.

Browser: Brave on Windows 10

**Comment by devuxer** [comment]
@afc163,

If you want to reproduce this, just open the [demo](https://codesandbox.io/s/tvlbw0) for `Typography.Text` in Code Sandbox:

Here's a screen capture with development tools open showing that `Typography.Text` is rendering as Times New Roman (not Segoe UI, as it is on the [Antd website](https://ant.design/components/typography)).

![image](https://user-images.githubusercontent.com/1298521/209073855-ed533cee-04a7-4056-8de3-8b0222d325da.png)

**Comment by afc163** [comment]
@MadCcc `font-family` should apply to antd components.

**Comment by barreeeiroo** [comment]
I've just found this issue after getting it suggested by the bot. I was able to reproduce it and add a few more details to this issue, in case you want to check it out: #39802.

It includes reproduction links (5.1.0 and legacy).

**Comment by MadCcc** [comment]
Now you could use App to make font-family right.
Ref: https://ant.design/components/app

**Comment by MadCcc** [comment]
Gonna to make font-family work for all components again.

**Comment by dizefurkan** [comment]
@MadCcc it still does not work

**Comment by benfjohnson** [comment]
I'm also seeing the same thing.

**Comment by Panchi99** [comment]
I am also facing the same issue for notifications.
