### ISSUE TITLE
Missing documentation on how to configure horizontal Menu as it's being used in ant.design page

### ISSUE THREAD

**Issue by xedef** [ant-design/ant-design#39323]
### What problem does this feature solve?

To be able to customize Menu components in the same way it's used in ant.design

### What does the proposed API look like?

```
<Menu mode="horizontal" items={items} activeIndicatorPlacement="top|bottom"/>
```

or

```
const items = [{
  key: "foo",
  label: "Foo",
  activeIndicatorPlacement="top|bottom"
}]
<Menu mode="horizontal" items={items} />
```

**Comment by xedef** [comment]
To be clear, what I can't find is how to show the active indicator for an horizontal menu at the top as it's being used in ant's page:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/2538617/205968778-de9fef72-a4ba-44b9-a270-cbb8e9e056a0.png">

**Comment by MadCcc** [comment]
It's not feature of antd's Menu, and we may not treat it as feature.
Here's code in site for you: https://github.com/ant-design/ant-design/blob/master/.dumi/theme/slots/Header/Navigation.tsx#L55
