### ISSUE TITLE
5.0下select默认值第一次展开滚动不到正确的位置

### ISSUE THREAD

**Issue by wdaglb** [ant-design/ant-design#39343]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lxk37g?file=/index.js)

### Steps to reproduce

下拉展开第一次滚动不到，第二次展开则滚动到正确位置
如codsanbox中的默认20，第一次滚动到18，第二次才到20

### What is actually happening?

 

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome 108.0.5359.94 |

**Comment by ZN1996** [comment]
是不是因为组件本身设置的虚拟滚动默认选项高度`24px`，与实际渲染出来的选项高度不匹配，才导致这个现象出现的？示例中选项渲染出来的实际高度为`32px`，用组件默认的滚动容器高度`256px`除以这两个高度，分别是10和8，所以滚动总是差了两个选项。

**Comment by zombieJ** [comment]
`24` 是最小高度，只要小于实际高度就行，这个需要 debug 看一下为什么。
