### ISSUE TITLE
Tree 组件可选中的功能失效

### ISSUE THREAD

**Issue by xqinwl** [ant-design/ant-design#39340]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9clwcb)

### Steps to reproduce

向Tree 组件传递 defaultSelectedKeys 或 selectedKeys 时， Tree items 的选中样式失效

### What is expected?

正确显示选中的Tree items

### What is actually happening?

Tree items 的选中样式、 鼠标hover 样式失效

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18.0 |
| System | macos 12.4 |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
这个案例中传入的 defaultSelectedKeys 不是被选中了吗？
![image](https://user-images.githubusercontent.com/112228030/206092517-49c2d879-d14e-4dde-bd52-e7cf02037399.png)

![image](https://user-images.githubusercontent.com/112228030/206092430-38e4f410-bf07-4fbf-bf18-0fbaf1c52f0d.png)
