### ISSUE TITLE
Control RangePicker failure with the value property

### ISSUE THREAD

**Issue by rick-chou** [ant-design/ant-design#39342]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/timepicker-zp39mv)

### Steps to reproduce

clicking on the button in the footer

### What is expected?

I hope the date will be changed

### What is actually happening?

 date not be changed

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

---
I'm refactoring the Angular project and the previous version of antd angular doesn't seem to have this problem

**Comment by MadCcc** [comment]
Didn't find anything wrong in your reproduction.

https://user-images.githubusercontent.com/27722486/206102303-337ffba9-1dfa-4c16-94d6-75385a18c6e0.mp4

**Comment by rick-chou** [comment]
https://user-images.githubusercontent.com/56244178/206108360-7ad67c11-4d6f-495a-b023-f50e2f51cab1.mov

**Comment by rick-chou** [comment]
By the way, if I want to trigger the callback function once after the final date is selected, is there a way that the onChange property will be triggered after both the start/end date is selected?

**Comment by rick-chou** [comment]
Hello, is there any progress or message so far? @MadCcc

**Comment by MadCcc** [comment]
DatePicker's `value` won't be changed until ok button is clicked, so reseting date after selecting time or date doesn't work.

**Comment by MadCcc** [comment]
What you need may be `presets` prop of RangePicker.

> By the way, if I want to trigger the callback function once after the final date is selected, is there a way that the onChange property will be triggered after both the start/end date is selected?

Try `onCalendarChange`

**Comment by rick-chou** [comment]
> What you need may be `presets` prop of RangePicker.
> 
> > By the way, if I want to trigger the callback function once after the final date is selected, is there a way that the onChange property will be triggered after both the start/end date is selected?
> 
> Try `onCalendarChange`

`onCalendarChange`  also trigger every time @MadCcc
