### ISSUE TITLE
Popconfirm problem in RTL

### ISSUE THREAD

**Issue by jabdon00** [ant-design/ant-design#39350]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/api/v1/sandboxes/define)

### Steps to reproduce

use antd samples in RTL mode

### What is expected?

Popconfirm show normal

### What is actually happening?

Popconfirm width is 100%

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18 |
| System | 5.0.4 |
| Browser | Chrome |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/39311
