### ISSUE TITLE
使用Table组件，内容无法展示

### ISSUE THREAD

**Issue by jinmmd** [ant-design/ant-design#3935]
#### 发生问题的环境是：

- antd 版本: 2.4.3
- 操作系统及其版本: win7
- 浏览器及其版本: chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

引入Table组件，按demo编写代码，console无错误，例如：
```
const dataSource = [{
  key: '1',
  name: '胡彦斌',
  age: 32,
  address: '西湖区湖底公园1号'
}, {
  key: '2',
  name: '胡彦祖',
  age: 42,
  address: '西湖区湖底公园1号'
}];

const columns = [{
  title: '姓名',
  dataIndex: 'name',
  key: 'name',
}, {
  title: '年龄',
  dataIndex: 'age',
  key: 'age',
}, {
  title: '住址',
  dataIndex: 'address',
  key: 'address',
}];

<Table dataSource={dataSource} columns={columns} />
```

#### 您期待的结果是:

出现表格内容

#### 实际上的结果是:

一片空白

使用开发者工具查看，是由于table的父节点div带有“clearfix”样式，导致内容无法显示。以及，其他dom节点都包含class：“ant-spin-nested-loading”。

请帮忙查看下是否有问题。

![2016-11-21_144110](https://cloud.githubusercontent.com/assets/480907/20472981/9b3a0a94-aff8-11e6-8f70-a3e741f8b17f.png)

**Comment by yesmeck** [comment]
这边没重现出来，麻烦提供一个“可重现的在线演示” http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by jinmmd** [comment]
用这种方式 `import { Table } from 'antd';` 是空白（_难道不支持这种方式？_）
用这种方式`const { Table } = antd` 可以正常显示

完整代码（没有codepen的账号，抱歉）：
```
import { Table } from 'antd';

const dataSource = [{
  key: '1',
  name: '胡彦斌',
  age: 32,
  address: '西湖区湖底公园1号'
}, {
  key: '2',
  name: '胡彦祖',
  age: 42,
  address: '西湖区湖底公园1号'
}];

const columns = [{
  title: '姓名',
  dataIndex: 'name',
  key: 'name',
}, {
  title: '年龄',
  dataIndex: 'age',
  key: 'age',
}, {
  title: '住址',
  dataIndex: 'address',
  key: 'address',
}];

ReactDOM.render(<Table dataSource={dataSource} columns={columns} />
, document.getElementById('container'));
```

**Comment by yesmeck** [comment]
你代码我试过了没问题，不能提供重现演示的话，没办法帮你解决问题。

**Comment by jinmmd** [comment]
代码在这里：
http://codepen.io/jinmmd/pen/dOvMRe?editors=0011

我在win7的chrome和mac的safari都试了，就是空白。如果你那边还是没法复现，那就算了。

**Comment by jinmmd** [comment]
`import { Table } from 'antd'` 这种方式可能是我引用问题吧。不考虑引用的情况下，的确是可以显示的。我还是排查下我自己的其他代码吧，请关闭吧，打扰了，谢谢。

**Comment by afc163** [comment]
演示里无法使用 import 。

http://codepen.io/afc163/pen/oYZxyM?editors=0011

**Comment by jinmmd** [comment]
![2016-11-21_165715](https://cloud.githubusercontent.com/assets/480907/20476368/95fbf836-b00b-11e6-9ba2-b7b0bc06605f.png)

确实不是antd的问题，而是shadow-root加了段style。。。一脸懵逼

**Comment by jinmmd** [comment]
排查到最后，发现这段style来自chrome插件：AdBlock Plus T_T

**Comment by hbrls** [comment]
仍然遇到这个问题，退回 2.2.1 就好了

**Comment by yesmeck** [comment]
@hbrls 请提供可重现的演示
