### ISSUE TITLE
Form.List内部的字段没有被清理

### ISSUE THREAD

**Issue by hongzhangian** [ant-design/ant-design#39364]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w8lyvx?file=/index.js)

### Steps to reproduce

点击当前值，显示{"list":[{"arrayField":2}],"normalField":1}，点击消除字段后再点击当前值，显示{"list":[{"arrayField":2}]}

### What is expected?

normalField和arrayField这两个字段被消除后，通过校验获取的值应当同时没有normalField和arrayField字段

### What is actually happening?

normalField和arrayField这两个字段被消除后，通过校验获取的值没有normalField字段(符合预期)，但是有arrayField字段(不符合预期)

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 16.14.34 |
| System | macos |
| Browser | chrome |

**Comment by MadCcc** [comment]
你的 reproduction 里 Form.List 并没有被清除
https://codesandbox.io/s/antd-reproduction-template-forked-sfjefk
这样就没了。

**Comment by hongzhangian** [comment]
这样不是我需要的效果，list不能整体消除，只是list元素的其中一个字段消除，你可以假设还有很多其他字段。

**Comment by hongzhangian** [comment]
例如我这个case里：https://codesandbox.io/s/antd-reproduction-template-forked-bse0v3?file=/index.js
是不要arrayField这个字段，但是keepfield还是要的，整体list消除是不对的

**Comment by hongzhangian** [comment]
例如我这个case里：https://codesandbox.io/s/antd-reproduction-template-forked-bse0v3?file=/index.js
是不要arrayField这个字段，但是keepfield还是要的，整体list消除是不对的。
