### ISSUE TITLE
上传组件应该能够设置上传文件的大小

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#3936]
如题。
现在不知道如何限制上传文件的大小。

**Comment by benjycui** [comment]
See: https://developer.mozilla.org/zh-CN/docs/Web/API/Blob/size

自行处理。

**Comment by benjycui** [comment]
空了把这个加进 demo

**Comment by afc163** [comment]
其实就是这个：https://ant.design/components/upload/#components-upload-demo-beforeUpload
