### ISSUE TITLE
如何取消按钮点击时的动画？

### ISSUE THREAD

**Issue by KidneyFlower** [ant-design/ant-design#3937]
#### 发生问题的环境是：
- antd 版本: v2.4.3
- 操作系统及其版本: Max OS X Sierra
- 浏览器及其版本: Chrome v54.0

#### 您做了什么？请提供尽可能详细的重现步骤。

按钮点击时会有一个边框向外辐射的动画，如何禁用这个动画？

#### 您期待的结果是:

禁用按钮点击动画

#### 实际上的结果是:

点击时有边框向外辐射的动画
![image](https://cloud.githubusercontent.com/assets/16027183/20474830/7d86557e-b003-11e6-9d7d-b91523cb1b31.png)

**Comment by yesmeck** [comment]
自己覆盖 .ant-btn-clicked 样式 https://github.com/ant-design/ant-design/blob/master/components/button/style/index.less#L103

**Comment by KidneyFlower** [comment]
@yesmeck 感谢
