### ISSUE TITLE
官网文档可锚定节点无法快速复制链接

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#39370]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/6134547/206172306-fd685830-8061-4389-b6ff-9d71fc77da6f.png">

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/206174549-b6059447-cf7f-4d1d-b478-4f18889d2426.png)


这个能支持包一个`<a href="#${id}">` 吗?

**Comment by PeachScript** [comment]
@MadCcc 这个上次聊过，锚点的 DOM 节点是有的，需要加点样式把它展示出来，因为 v5 没有使用 dumi 默认的 Markdown 样式
