### ISSUE TITLE
DatePicker API extension: openToDate prop

### ISSUE THREAD

**Issue by erselnordlys** [ant-design/ant-design#39375]
### What problem does this feature solve?

**Case**: user wants to see the suggested date which is 6 months later than today. So the calendar panel should be opened on this month and the date on it should look like it's selected, but the input must stay empty. On the closing panel (on blur), no date should be chosen. 

**Analogy**: https://reactdatepicker.com/#example-open-to-date

### What does the proposed API look like?

```<DatePicker openToDate={dayjs(dateValue)} />```

**Comment by MadCcc** [comment]
Do you mean `defaultPickerValue` ?

**Comment by erselnordlys** [comment]
Not exactly. `defaultPickerValue` sets the date to the DatePicker, but I just need the calendar panel to be opened on the particular suggested date without it being selected. So the DatePicker should remain empty until the user selects it themselves.

**Comment by MadCcc** [comment]
`defaultPickerValue` won't change DatePicker's value until ok button is clicked. 
It's unnecessary to provide a new prop with similar funciton to `defaultPickerValue`.

**Comment by erselnordlys** [comment]
I see it now. Thank you!
But still, the date is not outlined on a picker, this indication would be very useful since we can pass the full date, not only year and month
