### ISSUE TITLE
Issue create for cssinjs, with no anwser and people affected

### ISSUE THREAD

**Issue by bougassaa** [ant-design/ant-design#39377]
### Reproduction link

[https://github.com/ant-design/cssinjs/issues/57](https://github.com/ant-design/cssinjs/issues/57)

Hello, there is an issue that has been created for [CSSINJS](https://github.com/ant-design/cssinjs/issues/57), which can be fixed quickly, which impacts people

### Steps to reproduce, What is expected?, What is actually happening?

👉 See the issue on cssinjs [#57](https://github.com/ant-design/cssinjs/issues/57)

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react 18 |
| System | All |
| Browser | All |

**Comment by zombieJ** [comment]
Thx for notice. Let me check this.

**Comment by bougassaa** [comment]
Thank you 🙏
