### ISSUE TITLE
Missing hovering cursor and selected highlight style in Tree

### ISSUE THREAD

**Issue by ledge74** [ant-design/ant-design#39384]
### Reproduction link

[https://ant.design/components/tree#components-tree-demo-basic](https://ant.design/components/tree#components-tree-demo-basic)

### Steps to reproduce

On the basic tree demo, hover an item and select it

### What is expected?

The tree item should provide an hover effect as well as a "pointer" cursor. On selection, a background color should be applied.
This is the behaviour in V4 : https://4x.ant.design/components/tree/#components-tree-demo-basic

### What is actually happening?

The hovering and selected style is missing

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18 |
| System | macOS 13.0 |
| Browser | Chrome Version 108.0.5359.94 (Official Build) (arm64) |

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/39292
