### ISSUE TITLE
Affix固钉，官网上滚动容器例子的bug

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design#3938]
#### 发生问题的环境是：

- antd 版本: v2.4.3
- 操作系统及其版本: win7 旗舰版
- 浏览器及其版本: chrome 版本 52.0.2743.116 m

#### 您做了什么？请提供尽可能详细的重现步骤。

查看官网Affix固钉示例，滚动容器那个，即设置了target的例子。拖到容器的滚动条，使其中的蓝色按钮到达容器顶部，再拖动最右侧整个页面的滚动条，会发现蓝色按钮已经跑出了容器。可以多尝试几遍，很容易重现。

#### 您期待的结果是:

正常显示

#### 实际上的结果是:

蓝色按钮已经跑出了容器，这个问题在早期的antd版本中也存在，只不过我现在才提交这个问题。

#### 可重现的在线演示

https://ant.design/components/affix/

**Comment by benjycui** [comment]
就是这样的。

在嵌套了 N 层的可滚动容器里面 Affix，如果 Affix 要监听每一层的滚动事件，会很卡的。
