### ISSUE TITLE
Tree hover和选中后无样式

### ISSUE THREAD

**Issue by Edric-Li** [ant-design/ant-design#39397]
### Reproduction link

[https://ant.design/components/tree-cn](https://ant.design/components/tree-cn)

### Steps to reproduce

直接放个Tree，hover 选中都无效果

### What is expected?

有效果

### What is actually happening?

无效果

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/39292
