### ISSUE TITLE
4.24  版本 table组件的scroll设置成true,不生效

### ISSUE THREAD

**Issue by SophiaBaby** [ant-design/ant-design#39396]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sui-ye-mian-gun-dong-de-gu-ding-biao-tou-he-gun-dong-tiao-antd-4-24-5-forked-90yzum)

### Steps to reproduce

直接打开就可以

### What is expected?

设置成true 可以滚动

### What is actually happening?

.

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react |
| System | 任意 |
| Browser | 谷歌 任意 |

**Comment by SophiaBaby** [comment]
.

**Comment by lovewaner** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/21039467/206440214-e294e19c-ced7-49a9-a11d-586d4f9abed9.png">

**Comment by zombieJ** [comment]
抱歉延迟这么就回复，示例现在看起来是好的，应该是没问题了。这里就先关啦。
