### ISSUE TITLE
主题设计器无保存按钮,但是本地启动的项目中主题设计器有保存按钮

### ISSUE THREAD

**Issue by heart-to-the-sea** [ant-design/ant-design#39390]
### Reproduction link

[https://ant.design/theme-editor](https://ant.design/theme-editor)

### Steps to reproduce

直接进入

### What is expected?

存在保存按钮

### What is actually happening?

页面不存在保存按钮

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react |
| System | archlinux |
| Browser | chrome 109.0.5414.25 |

**Comment by MadCcc** [comment]
等下次部署文档站即可
