### ISSUE TITLE
希望Popover的content可以获取到本次打开时触发的trigger

### ISSUE THREAD

**Issue by dislido** [ant-design/ant-design#39419]
### What problem does this feature solve?

比如聊天室用户列表，onClick时打开用户资料卡片，onContextMenu时打开 禁言/屏蔽/举报 等操作菜单

### What does the proposed API look like?

```tsx
<Popover
  trigger={['click', 'contextMenu']}
  // 可能会同时触发多个trigger？
  content={
    (triggers: ActionType[]) => triggers.includes('contextMenu')
      ? <UserMenu />
      : triggers.includes('click') && <UserProfile />
  }
>
  {children}
</Popover>
```

**Comment by MadCcc** [comment]
You may want this: https://ant.design/components/popover-cn#components-popover-demo-hover-with-click
