### ISSUE TITLE
Huge size of SSG migrating to antdv5

### ISSUE THREAD

**Issue by jperelli** [ant-design/ant-design#39418]
### Reproduction link

I'm leaving 2 files, one is from antv4 and the other from antv5 generated using exactly the same components.
ant4 file is 0.04mb
ant5 file is 1.7mb

[ant4.txt](https://github.com/ant-design/ant-design/files/10190880/ant4.txt)
[ant5.txt](https://github.com/ant-design/ant-design/files/10190881/ant5.txt)

### Steps to reproduce

Deploy an SSG page to vercel and try to run.

### What is expected?

Smaller size of generated html

### What is actually happening?

Size is too big

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 18 |
| System | vercel |
| Browser | chrome |

---
I ran into this because of a generated page error in vercel
LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.

**Comment by zombieJ** [comment]
https://ant.design/docs/react/customize-theme#server-side-render-ssr

antd will render inline style by default to support ssr, you should extract if care about the bundle size.

**Comment by jperelli** [comment]
Thank you, it worked but I just needed to make a few workarounds to make it work in nextjs/swc together with styled-components.

Most notably i had to manually convert the style string that antd returns to <style /> tsx nodes using an external library to parse the string. 

It would be nice if antd cssinjs could return the style nodes instead of the stringified version.

```typescript
import { XMLParser } from 'fast-xml-parser'
...

  static async getInitialProps(ctx: DocumentContext) {
    // antd cssinjs cache
    const antdCssCache = createCache()

    // Styled Components
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage

    try {
      // Fetch stylesheets for rendered components
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(
              <StyleProvider cache={antdCssCache}>
                {/* Styleprovider is for ant cssinjs cache */}
                <App {...props} />
              </StyleProvider>,
            ),
        })

      const initialProps = await Document.getInitialProps(ctx)

      // convert style string to style nodes
      const antdSsrStylesString = extractStyle(antdCssCache)
      const antdSsrStyles = new XMLParser({
        ignoreAttributes: false,
        attributesGroupName: '@_',
      }).parse(antdSsrStylesString)
      const antdSsrStyleNodes =
        antdSsrStyles.style?.map((s: any, i: number) => {
          const attrs = Object.fromEntries(Object.entries(s['@_']).map((e) => [e[0].replace('@_', ''), e[1]]))
          return <style key={`antdcssinjs_${i}`} {...attrs} dangerouslySetInnerHTML={{ __html: s['#text'] }}></style>
        }) || []

      // Inject styles in document
      return {
        ...initialProps,
        styles: [initialProps.styles, ...sheet.getStyleElement(), ...antdSsrStyleNodes],
      }
    } finally {
      sheet.seal()
    }
  }
```

**Comment by zombieJ** [comment]
@MadCcc could we remove default inline style logic. I think it's useless for a complete page.
