### ISSUE TITLE
基于antd上开发组件 发布到npm 提示babel-plugin-import 

### ISSUE THREAD

**Issue by jindada** [ant-design/ant-design#3942]
#### 发生问题的环境是：

- antd 版本: 最新
- 操作系统及其版本: win10
- 浏览器及其版本: google chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

我想基于antd二次开发组件 用webpack测试没有后问题 发布之后 提示我写的组件
![image](https://cloud.githubusercontent.com/assets/16317349/20479154/1459f8e8-b018-11e6-82f7-c2552f4db1e7.png)
我是将js less编译之后发布的
引入antd的方式 用的 import  { Button } from antd 这样的写法 
我大体知道是因为发布之后没有webpack上的配置所以才会这样的
翻了issues也没有找到类似的问题 想问一下 如何解决

#### 您期待的结果是:
正常显示

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/16317349/20479263/8d4bb50c-b018-11e6-8853-5c2b1ea8c7a7.png)

#### 可重现的在线演示

无

**Comment by yesmeck** [comment]
见 https://ant.design/docs/react/getting-started?locale=zh-CN#按需加载

**Comment by jindada** [comment]
@yesmeck 正常加载了 但是页面似乎没加载上 我输出也都正常输出出来了
![image](https://cloud.githubusercontent.com/assets/16317349/20479579/b80d903e-b019-11e6-8ad9-d7b219a9e1c5.png)
是webpack的配置文件需要做什么更改？

**Comment by yesmeck** [comment]
这个要你自己查一下了。

**Comment by benjycui** [comment]
构建问题自己深挖吧，毕竟你都决定要造轮子了。
