### ISSUE TITLE
小白从V4升级V5，less迁移出现问题

### ISSUE THREAD

**Issue by beautiful-boyyy** [ant-design/ant-design#39424]
### Reproduction link

[https://github.com/beautiful-boyyy/antdPro](https://github.com/beautiful-boyyy/antdPro)

### Steps to reproduce

1.用antdPro脚手架搭建一个初始项目
2.`npm install --save antd@5.x`
3. 修改`config.ts`文件
``` javascript
  lessLoader: {
    modifyVars: v4Token,
  },
```

### What is expected?

 less迁移完成

### What is actually happening?
![Screenshot 2022-12-09 at 10 52 25](https://user-images.githubusercontent.com/66351806/206614681-828cd288-630d-45f2-9dcb-be58eaca6f61.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | ^17.0.0 |
| System | MacOS 13.1 Beta (22C5033e) |
| Browser | chrome 108.0.5359.94 |

**Comment by zombieJ** [comment]
less 引入 antd 的部分不需要了，这个看起来文档里要标注一下。

**Comment by beautiful-boyyy** [comment]
> less 引入 antd 的部分不需要了，这个看起来文档里要标注一下。
> 
> ```diff
> --  @import (reference) '~antd/es/style/themes/index';
> ```

正常工作了，谢谢～～

**Comment by xhua007** [comment]
> 

哥们，用的Umi 吗？

**Comment by beautiful-boyyy** [comment]
> > 
> 
> 哥们，用的Umi 吗？

嗯

**Comment by beautiful-boyyy** [comment]
> > 
> 
> 哥们，用的Umi 吗？

嗯

**Comment by qc-z** [comment]
> <img alt="image" width="1716" src="https://user-images.githubusercontent.com/51936110/208576566-b16c6257-d5cd-4cb2-a323-45298ff55bcf.png">
> 
> 那src下 .umi文件夹中引用到一个不存在的less改怎么解决

解决了吗？

**Comment by qc-z** [comment]
升级umi和@ant-design/pro-components到最新即可解决

**Comment by haobarry** [comment]
> 升级umi和@ant-design/pro-components到最新即可解决

把umi升级到4才行？

**Comment by haobarry** [comment]
> <img alt="image" width="1716" src="https://user-images.githubusercontent.com/51936110/208576566-b16c6257-d5cd-4cb2-a323-45298ff55bcf.png">
> 那src下 .umi文件夹中引用到一个不存在的less改怎么解决

同样的问题 如何解决呀？？
