### ISSUE TITLE
小白从V4升级V5，less迁移出现问题

### ISSUE THREAD

**Issue by beautiful-boyyy** [ant-design/ant-design#39423]
### Reproduction link

[https://github.com/beautiful-boyyy/antdPro](https://github.com/beautiful-boyyy/antdPro)

### Steps to reproduce

1.用antdPro脚手架搭建一个初始项目
2.`npm install --save antd@5.x`
3. 修改`config.ts`文件
``` javascript
  lessLoader: {
    modifyVars: v4Token,
  },
```

### What is expected?

 less迁移完成

### What is actually happening?

![image](https://imgbed.link/file/10039)

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | ^17.0.0 |
| System | MacOS 13.1 Beta (22C5033e) |
| Browser | chrome 108.0.5359.94 |

**Comment by MadCcc** [comment]
图挂了
