### ISSUE TITLE
Popcomfirm有没有那种类似Modal.confirm的js使用方式？antd4.0

### ISSUE THREAD

**Issue by KalkinWong** [ant-design/ant-design#39429]
### Reproduction link

[https://ant.design/components/popconfirm-cn](https://ant.design/components/popconfirm-cn)

### Steps to reproduce

<ProFormUploadButton
                    name="poster"
                    label="视频封面"
                    max={1}
                    action={UPLOAD_URL.fileUploadUrl}
                    rules={[{ required: false, message: '请上传视频封面图片' }]}
                    fieldProps={{
                      name: 'upload',
                      listType: 'picture-card',
                      accept: '.jpg, .png, .jpeg',
                      headers: {
                        // 'x-appid': getLocalStorage('appId'),
                        Authorization: 'Bearer '   getCookie('token'),
                      },
                      onPreview: handlePreview,
                      beforeUpload: async (file: any) => {
                        if (!file.type.startsWith('image/')) {
                          message.error('仅支持上传jpg/png/jpeg图片');
                          return Upload.LIST_IGNORE;
                        }
                        return true;
                      },
                      onChange: (file: any) => {
                        if (file.status === 'done') {
                        }
                      },
                      onRemove: async (file: any) => {
                        if (!['uploading', 'done'].includes(file.status)) {
                          return false;
                        }
                        return await new Promise((resolve, _reject) => {
                          Modal.confirm({
                            title: `是否确认删除封面？`,
                            content: '删除后， C端页面上将无法展示封面图',
                            okText: '确定',
                            cancelText: '取消',
                            onOk: () => resolve(true),
                            onCancel: () => resolve(false),
                          });
                        });
                      },
                    }}
                  />

### What is expected?

上传按钮Upload组件的onRemove事件时希望先弹出一个小的Popconfirm 弹窗， 而不是通过JS的Modal.confirm来弹出一个全屏的弹窗（希望这个popconfirm在upload删除按钮旁边）

### What is actually happening?

通过Modal.confirm来弹出一个全屏的弹窗

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | reactHook, next |
| System | macOs M1 |
| Browser | chrome |

**Comment by KalkinWong** [comment]
ant 4.0.0 版本

**Comment by afc163** [comment]
没有。
