### ISSUE TITLE
Cascader margin style

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#39432]
<img width="301" alt="图片" src="https://user-images.githubusercontent.com/507615/206650190-6e35ed7c-234b-4584-ab8b-1f420a272d92.png">

https://codesandbox.io/s/8wvxx3?file=/demo.tsx

ul 没重置 margin 。

**Comment by Wxh16144** [comment]
应该加在  `components/style/reset.css` 里面么？还是只是在这个组件加样式
