### ISSUE TITLE
antd 5.0 Table组件设置单行宽度无效

### ISSUE THREAD

**Issue by chenmeiling2016** [ant-design/ant-design#39437]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-0-5-forked-ik04r9?file=/demo.tsx)

### Steps to reproduce

给任意一个表格的列设置width宽度

### What is expected?

列的宽度随width设置变化

### What is actually happening?

宽度没变
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/51880353/206660542-065db8fd-7905-4266-9560-8a4647e45979.png">

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
html 原生表格默认会根据页面宽度和内容进行宽度计算的，不会严格遵守列宽度。你可以：

1. 将表格变成可滚动，内容尽可能撑宽。
  - https://codesandbox.io/s/ji-ben-yong-fa-antd-5-0-5-forked-31s2fk?file=/demo.tsx
3. 使用 tableLayout="fixed"，让 table 布局严格遵循用户定义的宽度。 
  - https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout
  - https://codesandbox.io/s/ji-ben-yong-fa-antd-5-0-5-forked-jxo643?file=/demo.tsx

**Comment by mengxingshike2012** [comment]
antd4  没有这个问题吗
