### ISSUE TITLE
开启动画的 Tabs 下使用 Affix，Affix 内容在滚动后消失 

### ISSUE THREAD

**Issue by yulanggong** [ant-design/ant-design#3943]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: Win 10
- 浏览器及其版本: Chrome 56， Edge 39

#### 您做了什么？请提供尽可能详细的重现步骤。

开启动画的 Tabs 下使用了 Affix

#### 您期待的结果是:

Affix 内容在滚动后能正常吸附

#### 实际上的结果是:

Affix 内容在滚动后消失

#### 可重现的在线演示

http://codepen.io/yulanggong/pen/GNWjbG?editors=001

#### 可能的原因分析

关闭 Tabs 的动画后一切正常，bug 的原因是 transform 改变了 position: fixed 的上下文。

#### 可能的解决方案

Tabs 做完切换动画后，使用代替的定位方式定位，移除 transform。

**Comment by benjycui** [comment]
ref: http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/

**Comment by benjycui** [comment]
antd 这边还需要升级。

**Comment by yesmeck** [comment]
需要更新下 snapshot。
