### ISSUE TITLE
Can't use vertical Form.Item without antd form

### ISSUE THREAD

**Issue by Gurochka** [ant-design/ant-design#39447]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g0t0lz?file=/index.js)

### What is expected?

Label is above Input

### What is actually happening?

Label is to the left from the Input 

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.1.0 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Sorry for miss understand #39444, here we go:
https://codesandbox.io/s/antd-reproduction-template-forked-lhvszh?file=/index.js

**Comment by Gurochka** [comment]
Thanks a lot!
