### ISSUE TITLE
Pagination 组件 文档能不能详细点 还是组件本身的问题

### ISSUE THREAD

**Issue by Aaronphy** [ant-design/ant-design#3944]
#### 发生问题的环境是：

- antd 版本:2.1.0
- 操作系统及其版本:mac
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

-使用了Pagination 组件，onShowSizeChange, 监听不到size 的变化
- showQuickJumper 这个 又该如何监听？ 
#### 您期待的结果是:
- size 和 jumper能够监听到页码的操作
#### 实际上的结果是:

- 啥都没有，文档写的不详细，是不是组件没有这个功能

**Comment by benjycui** [comment]
`onShowSizeChange` https://ant.design/components/pagination/#components-pagination-demo-changer
