### ISSUE TITLE
Use vertical Form.Item styles without antd Form

### ISSUE THREAD

**Issue by Gurochka** [ant-design/ant-design#39444]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g0t0lz?file=/index.js)

### Steps to reproduce

1. Labels stays horizontal with html form, and there is no any prop to change it (at least I couldn't find it).
2. antd Form onFinish doesn't fit - we need html event onSubmit (we use react-hook-form to manage forms)

### What is expected?

1. Vertical Form Items with html form through class/prop/anything else...
2. onFinish with regular html event 

### What is actually happening?

How to apply vertical styles to one Form.Item bypassing antd Form? 

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Form.Item do not block native event. You should preventDefault with form to avoid page refresh:

https://codesandbox.io/s/antd-reproduction-template-forked-eoblg5?file=/index.js

**Comment by Gurochka** [comment]
> Form.Item do not block native event. You should preventDefault with form to avoid page refresh:
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-eoblg5?file=/index.js

The question is about vertical form.item styles

**Comment by AzPrime44** [comment]
you can have the layout as vertical  by using labelCol and wrapperCol props
here an exemple
` <Form.Item
            labelCol={{ span: 24 }}
            wrapperCol={{ span: 24 }}
        >
            //children here
        </Form.Item>`
