### ISSUE TITLE
If you set the href attribute, the disabled style does not take effect

### ISSUE THREAD

**Issue by leo220yuyaodog** [ant-design/ant-design#39452]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8ev4je?file=/index.js)

### Steps to reproduce

在button 的`disable={true}` 时，设置`href`，此时`disable`样式不生效

### What is expected?

Actually, I found this issue https://github.com/ant-design/ant-design/issues/35952 is similar. But in anted 5.0.5, the problem seems to have resurfaced and is not fully fixed.  What I expect is that when the button is not just a link type, setting disabled will take effect as well as the button type.

### What is actually happening?

button设置href后，diabled样式不生效

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.2.0 |
| System | Windows 11 22623.1028 |
| Browser | 107.0.1418.52 (正式版本) (64 位) |

**Comment by BoyYangzai** [comment]
I tried to solve it，and passed all tests，I don't know if it met the author's expectations. qwq

**Comment by leo220yuyaodog** [comment]
> I tried to solve it，and passed all tests，I don't know if it met the author's expectations. qwq

Thank you very much!  As the example in [Reproduction link](https://codesandbox.io/s/antd-reproduction-template-forked-8ev4je?file=/index.js).
The left button is disabled, but now it is not has disabled style. I expect it has the same sytle as the middle button.
![image](https://user-images.githubusercontent.com/71440988/206854631-b9a8183f-0cc3-493d-9aca-7d29c15d78f8.png)

**Comment by BoyYangzai** [comment]
- #39456
This problem should have been solved in this pr, you can take a look

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/35975
new feature in 4.21, and lost in v5
