### ISSUE TITLE
Dark algorithm not working like the old dark css

### ISSUE THREAD

**Issue by Jeffmagma** [ant-design/ant-design#39454]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wy9nyu)

### Steps to reproduce

1. Update from ant design 4 to 5
2. Remove the dark mode css file
3. Wrap app with config provider with dark algorithm

### What is expected?

The page is dark, the text is white, etc

### What is actually happening?

Only the date select is partially dark, nothing else is

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Firefox 107.0.1 |

**Comment by MadCcc** [comment]
Dynamic theming in V5 won't modify style on body/html. In current version, you have to modify it by yourself.
And in next minor, we will provide `App` to handle this. Ref: https://github.com/ant-design/ant-design/discussions/38901
