### ISSUE TITLE
Popconfirm和Input一起使用时，input change会使Popover位置异常

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#3945]
![image](https://cloud.githubusercontent.com/assets/13936160/20509799/3d4eed56-b0a6-11e6-826d-7c75d14f752e.png)
onInputChange Popconfirm会跑到页面左上角去

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by qiaoyixuan** [comment]
问题找到了，Popconfirm children display == “none”时，Popconfirm位置会跑

**Comment by afc163** [comment]
Popconfirm 是根据 children 定位的，children 消失了错位很正常。
