### ISSUE TITLE
TimeLine 使用 line-height: 20px，定位异常

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#39451]
### Reproduction link

[wxn1f3.zip](https://github.com/ant-design/ant-design/files/10199076/wxn1f3.zip)

### Steps to reproduce

下载 zip，启动查看

### What is expected?

显示正常

### What is actually happening?

显示异常

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by any1024** [comment]
> ### Reproduction link
> [wxn1f3.zip](https://github.com/ant-design/ant-design/files/10199076/wxn1f3.zip)
> 
> ### Steps to reproduce
> 下载 zip，启动查看
> 
> ### What is expected?
> 显示正常
> 
> ### What is actually happening?
> 显示异常
> 
> Environment	Info
> antd	4.24.5
> React	latest
> System	mac
> Browser	chrome

能使用 [CodeSandbox](https://codesandbox.io/) 提交一个最小化 demo 看看吗

**Comment by crazyair** [comment]
是有，https://codesandbox.io/s/bold-cookies-wxn1f3?file=/src/App.js 但是我打不开，不知道效果怎么样

**Comment by any1024** [comment]
> 是有，https://codesandbox.io/s/bold-cookies-wxn1f3?file=/src/App.js 但是我打不开，不知道效果怎么样
这块代码的加载导致了页面一直卡死
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/32009993/206906742-00a8c2ed-5db2-4c1a-b474-fa5a5a3ac19f.png">

**Comment by any1024** [comment]
本地 `import "antd/dist/antd.less";` 就出现这个问题了
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/32009993/206907117-e82d0e35-012a-4508-8ed8-613e8def7f69.png">
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/32009993/206907128-4ba6a783-dcd7-4db1-98fe-ccd1500819c8.png">

**Comment by any1024** [comment]
`@line-height-base` 的单位为数字，`timeline`  的 `top` 属性依赖了 `@line-height-base` 做计算，所以使用 `20px` 时出现了布局错误
<img width="664" alt="image" src="https://user-images.githubusercontent.com/32009993/206907713-8d55902f-d9c8-47ed-a31b-5005a757b349.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/32009993/206907739-93736dd9-1848-4441-ab7f-0b8f51d98bfc.png">
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/32009993/206907763-f4e847f0-9c83-498f-8e6f-e069f13f127e.png">

**Comment by any1024** [comment]
将 `@line-height-base` 设置为数据，也就是字体的倍数可以解决这个问题
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/32009993/206907913-79d83d11-f93e-422e-a5ba-7dcaea365008.png">

CodeSandbox 打不开是因为下面的引入 ant less 会导致错误发生，但是 CodeSandbox 并为报错，有点坑
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/32009993/206907988-606f7c3b-7767-48b8-8460-ef5d5095b123.png">
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/32009993/206908202-e01ec473-78f4-494e-9c81-ae341b892a7e.png">

**Comment by MadCcc** [comment]
line-height 会用于计算，看看上面能否解决问题？

**Comment by crazyair** [comment]
我看 v5 类型定义为 number，那就使用倍数吧(可以在类型这里增加个注释，不推荐用 px)
<img width="313" alt="image" src="https://user-images.githubusercontent.com/7971419/207476956-25aa7b6c-acdd-43cc-a0fb-1cc650edfb8a.png">

**Comment by MadCcc** [comment]
number 本身就是个强约束了，应该还好，先关了

**Comment by crazyair** [comment]
那是 v5 啊，v4、v3 是没类型的，如果升级应该也会遇到跟我一样的困扰

**Comment by crazyair** [comment]
还有`CSSProperties` 中 `lineHeight` 是支持，string、number 的 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/7971419/207496510-36352bbc-fdb1-4385-8e12-060c32c113ef.png">

**Comment by MadCcc** [comment]
token 和 CSSProperties 并不等同，类型上不会保持一致。
v4 主题文档里可以写一下 FAQ

**Comment by crazyair** [comment]
v5 应该也需要加，不然下个人觉得这里不合理，再补充个 | string 怎么办。

**Comment by MadCcc** [comment]
> v5 应该也需要加，不然下个人觉得这里不合理，再补充个 `| string` 怎么办。

不会补充 string 类型的，这个在实现层面就解决不了了

**Comment by crazyair** [comment]
其实还是能解决的，如果是 px 不就 fontSize * lineHeight 了，直接 fontHeight 就可以了

**Comment by MadCcc** [comment]
过于复杂了，取其一就好

**Comment by any1024** [comment]
> token 和 CSSProperties 并不等同，类型上不会保持一致。 v4 主题文档里可以写一下 FAQ

我来提一个 pr 吧

**Comment by any1024** [comment]
@MadCcc 麻烦帮忙看下文案是否需要修改

**Comment by afc163** [comment]
Close at https://github.com/ant-design/ant-design/pull/39565
