### ISSUE TITLE
1.x版本的Input组件在IE8下有错，IE下并没有getComputedStyle方法

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#3946]
#### 发生问题的环境是：
- antd 版本: 1.x
- 操作系统及其版本: win7
- 浏览器及其版本: IE8

#### 您做了什么？请提供尽可能详细的重现步骤。

引入 antd 了 Input, type设置为'textarea'

#### 您期待的结果是:

IE8下能正常显示

#### 实际上的结果是:

在IE8下报错

#### 可重现的在线演示

无

#### 当时针对textarea提交的代码
https://github.com/ant-design/ant-design/pull/2001/files#diff-b065c31999febd08c14efc6d96febd04R51

虽然现在2.x不再支持IE8了，但是当时添加这个功能的时候antd对外是兼容IE8的，
还是说当时就没考虑兼容IE8？ 让使用者去处理兼容性？

**Comment by afc163** [comment]
可以来个 PR：http://stackoverflow.com/questions/21797258/getcomputedstyle-like-javascript-function-for-ie8
