### ISSUE TITLE
DatePicker.RangePicker hovering over a date in the range has inconsistent background color

### ISSUE THREAD

**Issue by IonelLupu** [ant-design/ant-design#39462]
### Reproduction link

[https://stackblitz.com/edit/react-3u7rjv-qyvxps?file=demo.tsx](https://stackblitz.com/edit/react-3u7rjv-qyvxps?file=demo.tsx)

### Steps to reproduce

- open de range picker
- select a date range
- open de range picker
- hover over dates inside that range

### What is expected?

To see a consistent background color when hovering over dates in the selected range

### What is actually happening?

The background color has some inconsistent color: 
- there is a whitish 1px line between two dates in the video
- these is a whitish half background and half blue background between the 13th and 14th dates in the video

https://user-images.githubusercontent.com/4083652/206893940-3a508e50-7baa-497c-935a-0d6b6e5aaee6.mov

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.2.0 |
| System | MacOS Ventura 13.0.1 |
| Browser | Chrome 108 |

**Comment by IonelLupu** [comment]
@MadCcc not sure what happened with the first link but now I updated it. But it doesn't even need a link actually to reproduce. You just use default RangePicker. I just added the Stackblitz link with the RangePicker from the website.

**Comment by IonelLupu** [comment]
I updated the link to include the latest AndDesign version just to make sure this issue wasn't fixed already

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
