### ISSUE TITLE
Export Rule / RuleConfig types for user access

### ISSUE THREAD

**Issue by edmundsj** [ant-design/ant-design#39466]
### What problem does this feature solve?

I am unable to create custom type-safe components based on Form.Item, because I do not have access to the Rule or RuleConfig type. I would like this to be exported.

### What does the proposed API look like?

export {RuleConfig, Rule} from wherever they live.

**Comment by MadCcc** [comment]
Use `FormItemProps['rules']`

**Comment by thoughtpalette** [comment]
Doesn't seem to work for the pro-form component(s).
