### ISSUE TITLE
图片点击大图demo是可以的，但是迁移到v5后，本地直接跑图片demo 报错

### ISSUE THREAD

**Issue by ByronFanglei** [ant-design/ant-design#39461]
### Reproduction link

[http://本地跑图片点击大图 demo 即可](http://本地跑图片点击大图 demo 即可)

### Steps to reproduce

本地跑图片点击大图 demo 即可

### What is expected?

点击大图正常

### What is actually happening?

点击大图正常

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.2 |
| System | mac |
| Browser | chrome |

**Comment by ByronFanglei** [comment]
> 

https://ant.design/components/image-cn#components-image-demo-preview-group-visible
可以直接本地拷贝这个 demo 例子就会复现

**Comment by any1024** [comment]
> > 
> 
> https://ant.design/components/image-cn#components-image-demo-preview-group-visible 可以直接本地拷贝这个 demo 例子就会复现

看着好像没问题，https://codesandbox.io/s/wlrnz0?file=/demo.tsx，本地跑 demo 可以截图看看错误信息吗

**Comment by ByronFanglei** [comment]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/45235628/209442794-e8fa61cc-98e8-4a97-8097-5579cbf14319.png">

**Comment by ByronFanglei** [comment]
> > > 
> > 
> > 
> > https://ant.design/components/image-cn#components-image-demo-preview-group-visible可以直接访问这个demo 例子就会恢复
> 
> 看着好像没有问题，[Demo](https://codesandbox.io/s/wlrnz0?file=/demo.tsx)，本地跑 demo 可以截图看看错误信息吗

<img width="815" alt="image" src="https://user-images.githubusercontent.com/45235628/209442815-0265e33b-7efe-4a77-9451-3d6abcbfb3e5.png">

**Comment by ByronFanglei** [comment]
> 18.2

我这边又看了下 react 18.0 是没有问题的 而且你的demo也是这个版本 但是 18.2 是有问题的 报错如上
