### ISSUE TITLE
Support rgba() styling in colors passed into themes

### ISSUE THREAD

**Issue by edmundsj** [ant-design/ant-design#39472]
### What problem does this feature solve?

Currently the only way to set primary/secondary colors with themes is with hexadecimal color codes. This is annoying, as many of my colors are in rgba, and I have to convert them manually. This is very basic standard CSS.

### What does the proposed API look like?

token: { colorPrimary: '#dc5c2c'}} could be written as token: {colorPrimary: 'rgb(220, 92, 44)'}

**Comment by MadCcc** [comment]
Default Algorithm didn't support colors with alpha for Seed Token.
You can customize algorithm if needed. Ref: https://ant.design/docs/react/customize-theme#algorithm
