### ISSUE TITLE
Tabs调整大小后underline漂移

### ISSUE THREAD

**Issue by oboard** [ant-design/ant-design#39477]
### Reproduction link

[https://ant.design/components/tabs-cn#components-tabs-demo-size](https://ant.design/components/tabs-cn#components-tabs-demo-size)

### Steps to reproduce

切换大小

### What is expected?

不漂移

### What is actually happening?

漂移

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18.2.0 |
| System | macOS 12。6 |
| Browser | Chrome 107.0.5304.110 (正式版本) (x86_64) |

**Comment by Pulset** [comment]
let me try

**Comment by afc163** [comment]
5.1.0 问题还在

**Comment by zombieJ** [comment]
https://github.com/react-component/tabs/pull/620 解的是 `key` 变化不更新问题，`key` 相同变化就需要依赖 `rc-resize-observer` ，性能损耗就要大了。

**Comment by zombieJ** [comment]
https://github.com/react-component/tabs/pull/620 这边改挂了

**Comment by afc163** [comment]
<img width="412" alt="图片" src="https://user-images.githubusercontent.com/507615/209038771-049c098d-e4a0-4957-9bdd-f19187e33a1f.png">

这个例子现在也切换不了了，一起看看是不是修复了。https://ant.design/components/tabs-cn#components-tabs-demo-slide
