### ISSUE TITLE
AutoComplete does not work if added as part of a functional component to Form (e.g. within Steps)

### ISSUE THREAD

**Issue by gregholst** [ant-design/ant-design#39473]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sccfq3?file=/index.js)

### Steps to reproduce

1) create a Modal
2) create a Form within the Modal
3) add to the Form with a functional component that includes an AutoComplete field

### What is expected?

When typing letters into the AutoComplete field, a list of options as a dropdown is expected

### What is actually happening?

No options are displayed

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | react 18 |
| System | MacOS Monterey |
| Browser | newest Chrome / Firefox |

---
This problem occurs only when adding to the Form as a functional component. This scenario occurred for me within a multi-step form as part of a modal. When using Steps as shown within antd documentation contents of the steps is added to a list, e.g. shown here https://ant.design/components/steps#components-steps-demo-step-next So in order to create the multi step form several of these functional components would be added to the list. 

Maybe related #27115 (https://github.com/ant-design/ant-design/issues/27115) 

Please excuse if adding functional components within a functional component like shown in the codebox is an anti-pattern. I could not find evidence for this. Maybe it would also be an interesting example for documentation of the Steps component as multi step Form seems to be a common use case.

**Comment by gregholst** [comment]
"So in order to create the multi step form several of these functional components would be added to the list."

This is an example of a multi-step form with such functional components, but without AutoComplete, to make my setup clearer: https://codesandbox.io/s/cool-mcnulty-or8jw?file=/src/MyStepForm.js

**Comment by gregholst** [comment]
@YinDongFang You are right, it is not a bug, but my fault. Thanks for explaining. I would still be interested why you recommended step 2? It seems to work also with the <LocationForm /> style: https://codesandbox.io/s/antd-reproduction-template-forked-m8zimd?file=/index.js

**Comment by gregholst** [comment]
@YinDongFang You are right, it is not a bug, but my fault. Thanks for explaining. I would still be interested why you recommended step 2? It seems to work also with the <LocationForm /> style: https://codesandbox.io/s/antd-reproduction-template-forked-m8zimd?file=/index.js

**Comment by afc163** [comment]
https://ant.design/components/form#components-form-demo-customized-form-controls

https://ant.design/components/form#form

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ubnue0

**Comment by afc163** [comment]
You should pass `value` and `onChange` to AutoComplete.

**Comment by YinDongFang** [comment]
> @YinDongFang You are right, it is not a bug, but my fault. Thanks for explaining. I would still be interested why you recommended step 2? It seems to work also with the style: https://codesandbox.io/s/antd-reproduction-template-forked-m8zimd?file=/index.js

sorry. It's not two steps but two ways to resolve your problem.
