### ISSUE TITLE
tableBg or tableHeaderBg defined in TableToken Interface doesn't seem to be consumed 

### ISSUE THREAD

**Issue by Feras-Alsaedi** [ant-design/ant-design#39487]
### Reproduction link

[https://ant.design/docs/react/customize-theme](https://ant.design/docs/react/customize-theme)

### Steps to reproduce

When going to the Ant configuration then going to Theme, components and table there is no way of changing the table header 

### What is expected?

to see the table bgheader in the table configs 

### What is actually happening?

tableBg or tableHeaderBg defined in TableToken Interface doesn't seem to be consumed 

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | React  v18 |
| System | Windows |
| Browser | chrome |

**Comment by MadCcc** [comment]
Trace here: https://github.com/ant-design/ant-design/issues/38975
