### ISSUE TITLE
Modal.confirm国际化失败

### ISSUE THREAD

**Issue by jianhao2010303** [ant-design/ant-design#39481]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce

1. 项目中配置了国际化。
2.调用Modal.confirm方法，语音为中文，但操作按钮显示为英文。

### What is expected?

1. 底部操作按钮可以根据国际化正常显示。

### What is actually happening?

1.底部按钮国际化失败。

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 18 |
| System | win10 |
| Browser | chrome |

**Comment by jianhao2010303** [comment]
![image](https://user-images.githubusercontent.com/22093101/206969685-816939f1-f404-4e42-8d57-329a46700a00.png)

**Comment by jianhao2010303** [comment]
增加了属性：okType: 'danger'。
不增加正常显示，增加了国际化异常。

**Comment by xliez** [comment]
https://github.com/ant-design/ant-design/issues/19692
可以看下这个issue
