### ISSUE TITLE
Table组件鼠标移上去对应行显示底色蓝色的bug

### ISSUE THREAD

**Issue by kongjunchao** [ant-design/ant-design#3948]
使用table组件，默认鼠标移到某一行，会出现相应的背景色改变，但是当我表格数据过多，出现横向滚动条的时候，另表格第一列我是fix固定显示的状态下，鼠标移上去不显示背景色，或出现跳单元格显示背景色bug

#### 发生问题的环境是：

- antd 版本:  2.4.2
- 操作系统及其版本:  window 7
- 浏览器及其版本:  chrome

**Comment by kongjunchao** [comment]
补充一下啊，我用火狐是正常的，就chrome有问题

**Comment by afc163** [comment]
之前内网报告过类似的问题，结论是没法修，只能等 Chrome 修复。
