### ISSUE TITLE
step 渲染 时间久

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#3949]
node做服务端渲染， f5刷新页面 form  等其他的组件很快render  但是 step组件 要等 全部加载完毕后才会加载

**Comment by benjycui** [comment]
Steps 需要在 componentDidMount 后重新计算部分样式，see：https://github.com/react-component/steps/blob/master/src/Steps.jsx#L13

所以需要先隐藏，在计算完成后再显示。

如有更好的方案，可以 PR。
