### ISSUE TITLE
`FloatButton.Group` click on the external area to collapse the feature

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#39493]
### What problem does this feature solve?

https://user-images.githubusercontent.com/32004925/207041942-182841c4-c026-4783-ab60-d36a4882d4d4.mp4

就拿官网右下角的主题切换操作来说，点击展开更多按钮，但是选择完功能后，我们可能不愿意再去点击底部的关闭按钮，从而继续浏览网页了。期望加入一个点击其他区域自动收起按钮组功能

### What does the proposed API look like?

unknown

**Comment by BoyYangzai** [comment]
我暂时写了第一版代码去实现这个功能，加了一个 `clickOutAutoClose` 字段去开启这个功能，辛苦review一下
