### ISSUE TITLE
Popover color not set on arrow

### ISSUE THREAD

**Issue by rkuykendall** [ant-design/ant-design#39499]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-0-6-forked-pubtoy?file=/demo.tsx)

### Steps to reproduce

Set color prop on Popover

### What is expected?

Popover background color is consistent

### What is actually happening?

Popover background color is different for the arrow notch

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18 |
| System | Mac OS X |
| Browser | Chrome |

**Comment by sguergachi** [comment]
I see this problem too, seems to only happen with custom colors, preset colors works fine
https://codesandbox.io/s/basic-antd-5-0-6-forked-g10758?file=/demo.tsx
