### ISSUE TITLE
Need theme tokens for Layout.Header and Layout.Sider background color

### ISSUE THREAD

**Issue by c3Vu** [ant-design/ant-design#39495]
### What problem does this feature solve?

I can dynamically configure the background color for Layout components, like in v4, using the less variable @layout-header-background

### What does the proposed API look like?

colorBgLayoutHeader / colorBgLayoutSider

**Comment by MadCcc** [comment]
Use `colorBgHeader`, It works for header and sider at the same time

**Comment by aashayamballi** [comment]
@MadCcc `colorBgHeader` we need to use in the ConfigProvider? I tried but it didn't work for me and I looked for docs too for this property and I couldn't find it. can you please help?

**Comment by aashayamballi** [comment]
@MadCcc 

do we need explicltly create a propertey i..e `colorBgHeader` like

```
<ConfigProvider
        theme={{
          token: {
            colorBgHeader: 'white',
          },
        }}
      >
        <Routes />
</ConfigProvider>
```

and consume the design token i.e. `colorBgHeader` via useToken like below?

```
const { token } = useToken();
return (
<Layout className="site_layout">
    <Header
      className="site_layout__header"
      style={{ background: token.colorBgHeader }}
    >
      <NavHeaderMenu />
    </Header>
    <Content className="site_layout__content">
      <Outlet />
    </Content>
</Layout>
)
```

**Comment by mrlubos** [comment]
@MadCcc Where is this documented? I'm quite sure there's no like-for-like replacement for the v4 `@layout-header-background` Less variable. Defining `colorBgHeader` in `ConfigProvider`'s `theme.token` does nothing.

**Comment by osumoclement** [comment]
What's the solution?

**Comment by anotheri** [comment]
still an issue on 5.2.0
