### ISSUE TITLE
Tabs not showing underline below tab title

### ISSUE THREAD

**Issue by hbatalhaStch** [ant-design/ant-design#39494]
### Reproduction link

[https://github.com/hbatalhaStch/antd-tabs-no-underline-bug](https://github.com/hbatalhaStch/antd-tabs-no-underline-bug)

### Steps to reproduce

just run `npm start`

### What is expected?

Blue underline below the tab title

### What is actually happening?

Only showing the tab title, no underline
![image](https://user-images.githubusercontent.com/114578587/207042660-720c2fb5-0812-450b-9bd2-97190373bd26.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.2.0 |
| System | Windows 10 Pro; Version: 21H2; OS Build: 19044.2251 |
| Browser | Microsoft Edge Version 108.0.1462.46 (Official build) (64-bit) |

---
Only happens with Typescript, running the same project in Javascript works fine

**Comment by MadCcc** [comment]
Seems bug in React.StrictMode, maybe associated with https://github.com/ant-design/ant-design/issues/39477
