### ISSUE TITLE
List crash when pagination pageSize is undefined

### ISSUE THREAD

**Issue by blluv** [ant-design/ant-design#39496]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-knuth-bi6zlu)

### Steps to reproduce

```
<List
...
  pagination={{
    pageSize: undefined
  }}
...
/>
```

### What is expected?

Not crush

### What is actually happening?

TypeError
Cannot read properties of undefined (reading 'pageSize')

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.3.0 |
| System | MacOs Ventura 13.0.1 |
| Browser | Chrome 108.0.5359.71 |

**Comment by BoyYangzai** [comment]
why you want to set the `pageSize: undefined`?  this scene is weird😂

**Comment by blluv** [comment]
This is because the behavior is different from the table and crashes before receive api response.

**Comment by iamshanazar** [comment]
how to fix this error please help me!
(parameter) pagination: TablePaginationConfig
'pagination.pageSize' is possibly 'undefined'
