### ISSUE TITLE
Table的dataSource为自己维护的话，如何进行服务器端排序(sort)

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#395]
目前手册上是：
var columns = [{
  title: '年龄',
  dataIndex: 'age',
  sorter: true
}...
];
和
var dataSource = new Table.DataSource({
  url,
  data: {},
  getPagination,
  getParams: function(pagination, filters, sorter) {
    console.log(sorter);
    var params = {
      sortField: sorter.field,
      sortOrder: sorter.order
    };
    return params;
  }
});
我需要的功能：
1，服务器端排序
2，自定义dataSource（自己维护的数组），而不是new Table.DataSource()对象
请问怎么办？

你们提供的Table.DataSource有几点不满足我的需求。
如，不支持mock数据，不支持跨域等。所以只能自己维护dataSource。

@yiminghe

**Comment by yiminghe** [comment]
@afc163

**Comment by afc163** [comment]
#404 看下这个是否能满足需求？@zccst

**Comment by zccst** [comment]
@afc163 这个新增支持，在0.10.x才支持吧。我现在用的还是0.9。所以还没办法验证，目前项目已进入提测阶段了。这时候升级的0.10.x beta版，觉得有点风险，所以暂时没法验证使用这个功能。

**Comment by afc163** [comment]
是的，等到 0.10.x 才会发布。

你先看看 API 是否能满足需求就好。

**Comment by zccst** [comment]
嗯，看了，能够满足。
