### ISSUE TITLE
DatePicker 提个bug

### ISSUE THREAD

**Issue by Vsion** [ant-design/ant-design#3950]
![image](https://cloud.githubusercontent.com/assets/11804448/20517675/1a88147e-b0d7-11e6-9522-8e88c46b151c.png)

默认为当前时间, 而当前时间在禁用时间范围内. 所以...

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/3836

**Comment by kunkkaliu** [comment]
1.11.*版本也有这个问题，可以把1.11.*一并解决了吗 辛苦了
