### ISSUE TITLE
Website: English version pages not currently showing English translation

### ISSUE THREAD

**Issue by GeekDisplaced** [ant-design/ant-design#39506]
### Reproduction link

[http://na](http://na)

### Steps to reproduce

Navigate to:
https://ant.design/docs/spec/data-list (English is not in English)
https://ant.design/docs/spec/form-page (English is not in English)

### What is expected?

English version

### What is actually happening?

Non English version, just for these two pages ... other pages show English content.

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | na |
| System | na |
| Browser | na |

---
Apologies if I have submitted a site issue in the wrong location/way.

**Comment by MadCcc** [comment]
I'm sorry that we do not have official translation for design articles currrently. Please try chrome translation if needed.
