### ISSUE TITLE
Select's dropdownRender not showing when no options

### ISSUE THREAD

**Issue by roninCode** [ant-design/ant-design#39507]
### Reproduction link

[https://ant.design/components/select#components-select-demo-custom-dropdown-menu](https://ant.design/components/select#components-select-demo-custom-dropdown-menu)

### Steps to reproduce

1) Add dropdownRender prop same as https://ant.design/components/select#components-select-demo-custom-dropdown-menu
2) Pass Select empty options: []
3) Click on the select to open the menu
4) You can not see the "Add Item" section - no dropdown is shown

### What is expected?

I expect the dropdown to still show the dropdownRender content, even if there are no options passed

### What is actually happening?

The select is focused, but there is no dropdown.

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | React 17.0.2 |
| System | MacOS 12.4 |
| Browser | Chrome |

**Comment by Wxh16144** [comment]
In my opinion, this should not be a bug, the first argument to `dropdownRender` is the dropdown options `<Options  />`, which he gets from the `options` traversal.

we should tweak the usage a bit.

**Comment by MadCcc** [comment]
Can't find anything wrong.
![image](https://user-images.githubusercontent.com/27722486/207242166-774c855f-9d8d-41ae-b4ce-9d0d968ad4fc.png)

**Comment by roninCode** [comment]
Apologies - this turned out to be an issue where the `notFoundContent` prop was overwriting the `dropdownRender` prop when no options were present. I added extra logic to check for no options in `notFoundContent` (returning `undefined` to not trigger it's effect)
