### ISSUE TITLE
Timeline dot style changed as well, when modifying Timeline rail style

### ISSUE THREAD

**Issue by Nate93** [ant-design/ant-design#39500]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/black-sun-0mjfs5?file=/src/App.js)

### Steps to reproduce

Set value <code>'dashed'</code> to lineType in Timeline component token

### What is expected?

<code>lineType</code> value changed should only affect Timeline rail

### What is actually happening?

<code>lineType</code> value changed affected Timeline dot as well

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.2.0 |
| System | window 10 |
| Browser | Chrome 108 |

**Comment by MadCcc** [comment]
`lineType` is for all `border-style`, and we could provide component token to meet your demand.
Trace here: https://github.com/ant-design/ant-design/issues/38975
