### ISSUE TITLE
Their should be props to rename, delete, add item in tree node or tree component in antd.

### ISSUE THREAD

**Issue by mAsadSiddique** [ant-design/ant-design#39516]
### What problem does this feature solve?

This will solve the adding new item, renaming, and deleting thing's in the tree component in antd.

### What does the proposed API look like?

There should be some deleting, renaming, and adding a new item to tree props for these functionalities.

**Comment by MadCcc** [comment]
Not planned. We won't make components too complex with data. You can easily customize Tree to meet your demand.
