### ISSUE TITLE
Add data-* attributes to ItemType[] within menu object

### ISSUE THREAD

**Issue by shon2789** [ant-design/ant-design#39518]
### What problem does this feature solve?

Using React testing library we should be able to get an element by "getByTestId" and we need the ability to add "data-testid" attribute to every item inside ItemType[] configuration.

### What does the proposed API look like?

Option to add data-* attributes to items inside ItemType[]

**Comment by pumpkin123** [comment]
The properties passed to “items” pass through the properties of the li tag, which is supported
<img width="308" alt="image" src="https://github.com/ant-design/ant-design/assets/18691796/54c04590-58c0-4a38-a344-dfe002d8c356">
<img width="597" alt="image" src="https://github.com/ant-design/ant-design/assets/18691796/e7a2388b-422b-4888-acb0-4f7ac8e35671">

**Comment by micnic** [comment]
@pumpkin123 It works, but the TypeScript definition does not allow it

**Comment by areichman** [comment]
@micnic's hack works for me on the `Dropdown` itself also.

```jsx
<Dropdown 
  menu={{
    items, 
    ...{'data-testid': 'user-menu'}
  }} 
/>
```
