### ISSUE TITLE
Customizing components theme does not work for Menu background color

### ISSUE THREAD

**Issue by c3Vu** [ant-design/ant-design#39512]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-y1kz0k?file=/index.js)

### Steps to reproduce

global colorBgBase token works, but it does not work when customizing component tokens

### What is expected?

I can customize component tokens in Menu

### What is actually happening?

its not working

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 18 |
| System | mac big sur |
| Browser | chrome |

**Comment by MadCcc** [comment]
Try `colorItemBg`. 
Notice that these component tokens are not stable in current version, please reference on tokens in offcial site in later versions.
