### ISSUE TITLE
Menu置于多个flex元素内无法根据元素宽度自动缩略

### ISSUE THREAD

**Issue by holmesliang** [ant-design/ant-design#39521]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/quiet-frog-u15d87?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

菜单未省略

### What is expected?

menu 省略

### What is actually happening?

menu 未省略

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 17.0.2 |
| System | mac |
| Browser | 谷歌版本 108.0.5359.98 |

---
4.15.4版本上看已修改，最新版本看错误

**Comment by MadCcc** [comment]
`flex: 1` 和 `width: 0` 一起使用
https://codesandbox.io/s/fervent-blackwell-pd2qcj
