### ISSUE TITLE
Table组件pageSize由大到小选择后报dataSource length is less than pagination.total but large than pagination.pageSize

### ISSUE THREAD

**Issue by candy4290** [ant-design/ant-design#39523]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g7u0ei?file=/index.js)

### Steps to reproduce

1、选择20/page
2、选择10/page

### What is expected?

没有warning

### What is actually happening?

不影响结果，但产生了warning

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.2.0 |
| System | Windows11 |
| Browser | 102.0.5005.63 |

---
我搜索过issues，找到https://github.com/ant-design/ant-design/issues/23554    ，但是没能看到一个好的解释。
我不太清楚，这个warning的用意是什么。是希望用户在分页切换的时候，先将异步数据获取到之后，再更新pagination这个props配置吗？希望得到反馈~~~
上面的复现链接，来源于官网的示例：https://ant.design/components/table-cn#components-table-demo-ajax

**Comment by zombieJ** [comment]
因为在异步和非异步下数据是共用的  `dataSource` ，所以它判断是否是按照异步展示的逻辑是检查当前的  `dataSource`  数据量和配置的 `pagination` 是否对的上。如果对不上 `total` 但是对得上 `pageSize` 的话就说明这是异步模式。

因而存在一种情况，那就是  `dataSource`  的长度既不等于 `total` 又不等于 `pageSize`。在这种情况下， Table 是无法确定到底这是因为异步导致  `dataSource` 不全，还是用户单纯的配置错了 `total`。所以报 warning 提示用户。

Demo 更新看起来还是有点问题，要调整一下。

**Comment by candy4290** [comment]
> 因为在异步和非异步下数据是共用的 `dataSource` ，所以它判断是否是按照异步展示的逻辑是检查当前的 `dataSource` 数据量和配置的 `pagination` 是否对的上。如果对不上 `total` 但是对得上 `pageSize` 的话就说明这是异步模式。
> 
> 因而存在一种情况，那就是 `dataSource` 的长度既不等于 `total` 又不等于 `pageSize`。在这种情况下， Table 是无法确定到底这是因为异步导致 `dataSource` 不全，还是用户单纯的配置错了 `total`。所以报 warning 提示用户。
> 
> Demo 更新看起来还是有点问题，要调整一下。

感谢回复，理解为什么报这个warning了。
