### ISSUE TITLE
The locale for the DatePicker component cannot be specified using dayjs.

### ISSUE THREAD

**Issue by Jay-flow** [ant-design/ant-design#39532]
### Reproduction link

[https://ant.design/components/date-picker#localization](https://ant.design/components/date-picker#localization)

### Steps to reproduce

I am using Next.js `13.0.6` and   dayjs `1.11.7`,

1. Set the locale in ConfigProvider.
`_app.tsx`

```tsx
import koKR from "antd/lib/locale/ko_KR"

export default function App({
  Component,
  pageProps,
}: AppProps) {
  return (
      <SessionProvider session={session}>
         <ConfigProvider locale={koKR}>
             <Component {...pageProps} />
         </ConfigProvider>
      </SessionProvider>
  )
}
```

2. Set the locale of dayjs according to the document.
```tsx
import "dayjs/locale/ko"
import dayjs from "dayjs"
import koKR from "antd/lib/locale/ko_KR"

dayjs.locale("ko")

export default function App({
  Component,
  pageProps,
}: AppProps) {
  return (
      <SessionProvider session={session}>
         <ConfigProvider locale={koKR}>
             <Component {...pageProps} />
         </ConfigProvider>
      </SessionProvider>
  )
}
```

3. Invoke the DatePicker component.
```tsx
<DatePicker
    inputReadOnly={true}
    onChange={onChangeAccidentDate}
    defaultValue={dayjs(new Date())}
    className="w-full"
 />
```

### What is expected?

DatePicker's language must be set to Korean.

### What is actually happening?

The locale of some items (months, weeks) is not set.

<img width="547" alt="Screenshot 2022-12-13 at 8 51 41 PM" src="https://user-images.githubusercontent.com/29420674/207310715-470f01f3-7906-4ba1-9fb5-de5bdf83ce6d.png">

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.2 |
| next | 13.0.6 |
| dayjs | 1.11.7 |
| System | Mac OS, Ventura 13.0.1 |
| Browser | Chrome Version 108.0.5359.98 (Official Build) (arm64) |

**Comment by PtkFerraro** [comment]
@Jay-flow did you get this o work? I am having the same problem... the weekday is stuck in english....

**Comment by LeeManh** [comment]
Any solutions ?

**Comment by eddi00** [comment]
Same here

**Comment by christianquispe** [comment]
Same here

**Comment by Soul244** [comment]
i tried this method and it worked.

https://github.com/ant-design/ant-design/issues/42087#issuecomment-1533385010

my dayjs version was 1.11.12 but ant design was using 1.11.11. I deleted node_modules, changed dayjs version in package.json by hand and reinstalled the packages. It worked.
