### ISSUE TITLE
Using css variables inside antd version 5

### ISSUE THREAD

**Issue by liel-almog** [ant-design/ant-design#39530]
### Reproduction link

[https://github/](https://github/)
There is no link

### Steps to reproduce

No steps

### What is expected?

Expected to use css variables inside css file in react with css modules

### What is actually happening?

There are no css variables inside

### Description

I've read in the docs there you have implemented CSS-in-JS but you also mention in the docs that there is a way to enable this feature and I could not have found a way to do this. I rely heavily on css and have been using antd for a while now, we are changing the styling in our component to match our design and using it with css targeting class and we want to also change the color with css variables

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | Windows 10 |
| Browser | firefox |

**Comment by MadCcc** [comment]
CSS variables is no longer supported in V5.

**Comment by liel-almog** [comment]
![antd V%](https://user-images.githubusercontent.com/70017134/207303511-f776db58-9547-4137-bb73-a44071637c75.jpg)

What about this section in the docs

**Comment by liel-almog** [comment]
And if there is no another way 
How could we use our colors inside css files?

**Comment by gsccheng** [comment]
@liel-almog [This](https://medium.com/@for.mvpetrov/using-css-variables-with-antd-design-system-3d0cd43c438b) may help

**Comment by liel-almog** [comment]
Actually, now they have fixed it.
If you wrap your app with the App component that AntD exports, you have all the variables inside the css in any nested component.
As you can see I had just recently.

https://github.com/liel-almog/SkyArchive
