### ISSUE TITLE
Tabs 高亮条状态不更新

### ISSUE THREAD

**Issue by 1pone** [ant-design/ant-design#39536]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-88tjhj)

### Steps to reproduce

点击change按钮, tabs组件重渲染, 但是高亮条状态不会同步更新

### What is expected?

高亮条状态跟随Tabs props更新

### What is actually happening?

高亮条状态被缓存没有发生变化

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.2.0 |
| System | macOS 12.4 |
| Browser | 108.0.5359.98 |

---
阅读rc-tabs源码发现在最近的一次更新中 updateTabSizes 方法副作用依赖了 [tabs.map(tab => tab.key).join('_')], 导致当不涉及 key 的更新时不触发 updateTabSizes. 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/54310591/207322315-a26b094c-3067-462d-9f8f-00922d5cb3e7.png">

相同情节还有动态更新 Tabs.size 高亮条状态不更新, 参考官方文档 https://ant.design/components/tabs-cn#components-tabs-demo-size
此外, 官方文档中的这个 demo https://ant.design/components/tabs-cn#components-tabs-demo-slide , 当选择 Vertical 类型时高亮条失效.
当前 updateTabSizes 副作用是否因为出于性能优化只依赖的 key 的变化, 实际场景中需要更新的依赖可能更多, 是否改为 [tabs] 更合理

**Comment by MadCcc** [comment]
Maybe same issue as https://github.com/ant-design/ant-design/issues/39477

**Comment by lifan2000** [comment]
我在5.0.7版本用tabs也遇到了一样的问题——底部高亮条宽度和位置都为0并且不随改变而刷新，但是降版本到5.0.1的tabs底部高亮条就是随点击正常刷新的。

**Comment by zombieJ** [comment]
merge into #39477
