### ISSUE TITLE
v5版 旧版浏览器兼容通过 StyleProvider 去除降权操作，页面Modal、Menu css显示异常

### ISSUE THREAD

**Issue by xiaofuliang** [ant-design/ant-design#39548]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kjl907?file=/index.js)

### Steps to reproduce

用360最新版浏览器或者微信电脑上打开

### What is expected?

显示正常居中

### What is actually happening?

显示靠左

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.3 |
| System | window10 |
| Browser | 微信PC浏览器 |

---
Modal、Menu里面使用了inset-inline、padding-inline，这些都要chrome 87才支持，要不然光StyleProvider 降权没有用，部分样式显示还是不正常的

**Comment by zombieJ** [comment]
Duplicate of #39082

**Comment by wsm14** [comment]
我用的umijs/max搭建的项目，antd是v5，在chrome上运行是正常的，在360极速浏览器里面css样式全部都没了是什么情况呢

**Comment by yoyo837** [comment]
看上面
