### ISSUE TITLE
visibilityToggle params don't match

### ISSUE THREAD

**Issue by Noaya** [ant-design/ant-design#39541]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/live/5accd5c5be2)

### Steps to reproduce

I am using the following code snippet:

<Input.Password
          placeholder="input password"
          visibilityToggle={{
            visible: passwordVisible,
            onVisibleChange: setPasswordVisible,
          }}
          iconRender={() => <span />}
        />
        <Button
          style={{
            width: 80,
          }}
          onClick={() => setPasswordVisible((prevState) => !prevState)}
        >
          {passwordVisible ? 'Hide' : 'Show'}
        </Button>

However, it doesn't compile because of visibilityToggle - it expects it to be a boolean, not a function. Yet I copied this from your API, so it should work.

### What is expected?

visibilityToggle should accept an object.

### What is actually happening?

It doesn't even compile. If I pass the hook passwordVisible instead, the show/hide button just doesn't work.

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.1.0 |
| System | Windows |
| Browser | Chrome |

**Comment by akaguny** [comment]
@Noaya , your version is antd version: 4.22.5
in antd version: 4.24.5
all works fine
https://codesandbox.io/s/reproduction-visibilitytoggle-params-dont-match-39541-od338q?file=/src/App.tsx

**Comment by akaguny** [comment]
@Noaya , update antd version solved your issue?

**Comment by Noaya** [comment]
@akaguny, yes, thank you :-)
