### ISSUE TITLE
当浏览窗口有滚动条时，Dropdown样式出错

### ISSUE THREAD

**Issue by andrew2558** [ant-design/ant-design#39549]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kmzb1r?file=/index.js)

### Steps to reproduce

点击最右侧按钮
菜单弹出
但是弹出的菜单宽度不对

### What is expected?

菜单正常显示 

### What is actually happening?

弹出的菜单宽度不对，全部挤到一起去了，菜单项都换行了

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.0 |
| System | win10 |
| Browser | last chrome |

**Comment by andrew2558** [comment]
![image](https://user-images.githubusercontent.com/25080605/207509054-05ae8b45-1070-4a06-b8c5-bd647de0f8c3.png)
我看到的是这样

**Comment by andrew2558** [comment]
> ![image](https://user-images.githubusercontent.com/27722486/207499970-ce515ef8-197d-466a-a849-d2d19e338e5d.png) How to reproduce?

你这个似乎不对，AA在左边，而我做的flex到end,右边的。

**Comment by Crazyxiaoming0827** [comment]
![image](https://user-images.githubusercontent.com/59348640/210055835-a2c01c6d-1a1c-4f24-92ce-7ea846b349d1.png)
You can set the width of the a tag in the menu attribute

**Comment by andrew2558** [comment]
@Crazyxiaoming0827  thanks, your way is ok
