### ISSUE TITLE
DatePicker 点击展开的内容可否自定义设置某个日期选择内容

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#3954]
#### 发生问题的环境是：

- antd 版本: max
- 操作系统及其版本: win7
- 浏览器及其版本: chrome max

#### 您做了什么？请提供尽可能详细的重现步骤。
希望在不给DatePicker赋值的前提下，点击展开选择面板显示指定的日期内容 比如：在不赋值的情况下，点击展开后选择面板展示2020-12-12

**Comment by benjycui** [comment]
Try: `defaultPickerValue`.

**Comment by dreamcatcher081210** [comment]
@benjycui 方法无效

**Comment by dreamcatcher081210** [comment]
@benjycui 看了下源码如你所说，THX!

**Comment by benjycui** [comment]
不是常用的属性，还是不暴露了。
