### ISSUE TITLE
Virtualized table in docs doesn't work with dark theme

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#39555]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-5-0-7-forked-h2ck29?file=/demo.tsx)

### Steps to reproduce

Open sandbox. Wait for it to load. Look at body of table.

### What is expected?

Table body text is visible.

### What is actually happening?

Table body has wrong background color and text is not visible.

![image](https://user-images.githubusercontent.com/1298521/207527072-772844b9-db23-460b-966a-c5df3d89df79.png)

### Comment

This is a simple fork of [the docs](https://ant.design/components/table#components-table-demo-virtual-list) wrapped with `ConfigProvider` set to dark theme. Nothing else was modified.

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.3.0 |
| System | Windows 10 Latest |
| Browser | Chrome/Brave |

**Comment by JSchmidt63** [comment]
same problem with the summary, i guess. 
Toggle Dark Theme, then summary keep it white
https://ant.design/components/table?theme=dark&theme=compact#components-table-demo-summary

**Comment by BoyYangzai** [comment]
![image](https://user-images.githubusercontent.com/94534613/208250450-6462185d-14ca-4c23-bfd2-dd5d3f607f52.png)

**Comment by devuxer** [comment]
@MadCcc, Thanks! What version of Antd will this be live? (Not fixed as of 5.1.0.)
