### ISSUE TITLE
Custom primaryColor not working for Modal.method() Ok/Cancel buttons

### ISSUE THREAD

**Issue by ovoloshchenko** [ant-design/ant-design#39559]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/late-water-q0n2ih?file=/src/App.js)

### Steps to reproduce

1. Wrap application with `ConfigProvider` and provide custom `primaryColor` (as mentioned in "Customize Theme" docs)
2. Add a `type='primary'` button - it will have a custom color provided in `ConfigProvider`
3. Add `onClick` method to the button which will open `Model.confirm({})` window.
4. Observe OK button in the confirm modal

### What is expected?

 OK button in confirmation modal (`Modal.confirm()` or other `Modal[method]()`) has a color provided by the developer in `ConfigProvider`

### What is actually happening?

OK button in confirmation modal has a default ant color

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 16.x |
| System | Mac OS Ventura |
| Browser | Latest Chrome |

**Comment by MadCcc** [comment]
Dynamic theming will not work with static methods in V5 by default, you could try this: https://github.com/ant-design/ant-design/blob/feature/components/app/index.en-US.md#global-scene-redux-scene

**Comment by lesh1j** [comment]
You can wrap the footer in the ConfigProvider like this
```
Modal.confirm({
  title: "title",
  content: "content",
  footer: (_, { OkBtn, CancelBtn }) => (
    <ConfigProvider theme={YOUR_THEME}>
      <Flex justify="space-between">
        <CancelBtn />
        <OkBtn />
      </Flex>
    </ConfigProvider>
  ),
});
```
