### ISSUE TITLE
Theme color does not take color into account for links

### ISSUE THREAD

**Issue by mleister97** [ant-design/ant-design#39560]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1zxccq?file=/index.js)

### Steps to reproduce

I configured a different primary color for my project as follows:

```
export const theme: ThemeConfig = {
    token: {
        colorPrimary: '#3fb984',
     }
}
```

Links are shown in blue. Is this intended? However, if I configure the `colorLink` attribute, the hover color is not configured automatically.

```
export const theme: ThemeConfig = {
    token: {
        colorPrimary: '#3fb984',
        colorLink: '#3fb984',
     }
}
```

Using this configuration, hovered links are still blue. is this the intended behaviour?

### What is expected?

The color configuration should apply for links as well, even if there is no explicit colorLink set

### What is actually happening?

The primary color is not used. Even if specifying a colorLink, the hover color does not take this color into account.

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.3.0 |
| System | Windows 11 |
| Browser | Latest Chrome |

**Comment by MadCcc** [comment]
`colorLink` follows `colorInfo` now. And in current version, `colorLink` `colorLinkHover` `colorLinkActive` cannot be calculated automaticly, you should override theme all to make it.

**Comment by mleister97** [comment]
@MadCcc Thanks for pointing that out. Is it planned in future releases to follow the primary color?

**Comment by bencerf** [comment]
> `colorLink` follows `colorInfo` now. And in current version, `colorLink` `colorLinkHover` `colorLinkActive` cannot be calculated automaticly, you should override theme all to make it.

@MadCcc sorry to add something to this old already closed issue but do you have any documentation about which Token follows specific other Token (as you mentionned, if you change `colorInfo`, it changes `colorLink` too).
In v4, I could get this information directly through the list of LESS variable mapping in the [default.less file](https://github.com/ant-design/ant-design/blob/4.x-stable/components/style/themes/default.less). The [Customize Theme](https://ant.design/docs/react/customize-theme#seedtoken), it's indicate only the HEX hard-coded value, not the Token if it follows an other Token.

Thank you in advance for your support and answer !
