### ISSUE TITLE
全局主题配置中深色模式无法对 message 和部分 Modal 生效

### ISSUE THREAD

**Issue by allynlin** [ant-design/ant-design#39570]
### Reproduction link

[https://github.com/allynlin/antd-demo](https://github.com/allynlin/antd-demo)

### Steps to reproduce

1. 点击按钮展示出三个提示，分别是 message 和两个 Modal
2. 这三个中只有一个 Modal 可以正确应用深色模式，还有一个 Modal 和 message 仍旧是浅色模式

### What is expected?

三个都是深色模式

### What is actually happening?

一个深色模式，两个浅色模式

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.2.0 |
| System | Windows 11 家庭版 Insider Preview 22H2 25262.1000 |
| Browser | Microsoft Edge 108.0.1462.46 |

**Comment by MadCcc** [comment]
V5 中静态方法直接使用不跟随主题。推荐使用 hooks 版本或者在后续的 5.1.0 版本中使用 App 组件。Ref: https://github.com/ant-design/ant-design/discussions/38901

当前版本的兼容方案：https://github.com/ant-design/ant-design/blob/feature/components/app/index.zh-CN.md#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF
