### ISSUE TITLE
表格列最后一列操作列如果是固定列，希望不参与宽度弹性计算

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#39577]
### What problem does this feature solve?

例如：
table设置了3列
序号、名称、操作
序号宽度100，名称宽度200
其中【操作】列固定显示在最右侧，设置宽度100
在大于400的页面中，3列会动态等比例增长宽度，能否对于固定在最右侧的列，不参与宽度自动计算
确保操作列可以是固定宽度

### What does the proposed API look like?

确保操作列可以是固定宽度

**Comment by crazyair** [comment]
试试 `onCell: () => ({ style: { width: 0, whiteSpace: 'nowrap' } })`

**Comment by phoema** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-0-7-forked-yx0qm9?file=/demo.tsx
onHeaderCell、onCell都试了一下，没有什么效果
当整个表格挤到出了横向滚动条后，操作列正好是100；
&nbsp;但宽度不满的时候，它也自动计算宽度


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月15日(星期四) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 表格列最后一列操作列如果是固定列，希望不参与宽度弹性计算 (Issue #39577)





 
试试 onCell: () =&gt; ({ style: { width: 0, whiteSpace: 'nowrap' } })

**Comment by crazyair** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-0-7-forked-09d57m?file=/demo.tsx
