### ISSUE TITLE
修改Modal的样式

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design#3957]
#### 发生问题的环境是：

- antd 版本:2.1.0
- 操作系统及其版本:ios
- 浏览器及其版本:chrome 54.0.2840.71 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

使用了弹出框Modal，想更改它的样式
![image](https://cloud.githubusercontent.com/assets/22025844/20521720/92653f66-b0e7-11e6-81e6-e11ce029c089.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20521731/94eccdee-b0e7-11e6-8066-e346957d5600.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20521747/a89128ea-b0e7-11e6-8417-7bab1bac1074.png)
我只在一个组件里面引用了，为什么其他组件里面的样式也改变了

**Comment by ssjjnn** [comment]
![image](https://cloud.githubusercontent.com/assets/22025844/20521799/09cb6da0-b0e8-11e6-8caa-3f8304566d76.png)
zui'hou'zhan最后张图片贴错了

**Comment by yesmeck** [comment]
CSS 本来就是全局的。

**Comment by yesmeck** [comment]
如果想只给指定 modal 加样式的话，加一个 `wrapClassName` https://ant.design/components/modal/#API
