### ISSUE TITLE
At 99, the circle is full

### ISSUE THREAD

**Issue by louzhihao** [ant-design/ant-design#39584]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o5n01s?file=/demo.tsx)

### Steps to reproduce

Set the percent of Progress to 99

### What is expected?

With the Progress size at 12 pixels, set percent of Progress to 99

### What is actually happening?

If the Progress size is 12 pixels, set the percent of Progress to 99. Do not fill up the circle

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.0.0 |
| System | Windows10 |
| Browser | Chrome107.0.5304.10 |

**Comment by zombieJ** [comment]
<img width="855" alt="截屏2022-12-15 16 46 40" src="https://user-images.githubusercontent.com/5378891/207813997-cbe99b6c-8879-4fab-85b4-d5d12bca2fb0.png">

**Comment by louzhihao** [comment]
Progress大小在12像素情况下,效果是占满了
![微信图片_20221215165919](https://user-images.githubusercontent.com/45398295/207817163-1e7a06a7-9673-46e7-8311-c005b26fc1bc.png)

**Comment by zombieJ** [comment]
这个 antd 侧就不做 Hack 了，如果特别想要个口子就 HOC 一下：

https://codesandbox.io/s/xiang-ying-shi-jin-du-quan-antd-5-0-7-forked-u5yzhd?file=/demo.tsx
