### ISSUE TITLE
Cannot customize theme token "colorSuccess" 

### ISSUE THREAD

**Issue by aswez** [ant-design/ant-design#39589]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/uen87q)

### Steps to reproduce

1. Replace the file `index.tsx` with
```

import React from 'react';
import { createRoot } from 'react-dom/client';
import Demo from './demo';
import {ConfigProvider} from 'antd'

createRoot(document.getElementById('container')).render(
  <ConfigProvider
  theme={{
    token: {
      colorSuccess: '#fdf',
      colorPrimary: 'red',
    },
  }}
>
  <Demo />
</ConfigProvider>
);

```
Result: colorSuccess token doesn't has any effect.

### What is expected?

Color of message icon is changed.

### What is actually happening?

Color of message icon is not changed.

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | React 18.2.0 |
| System | Mac M1 |
| Browser | Chrome 108.0.5359.98 (arm64) |

**Comment by BoyYangzai** [comment]
The code in your example is used **wrong**❌

The correct one to use `colorSuccess` should be✅
```diff
-    messageApi.info('Hello, Ant Design!');
+    messageApi.success('Hello, Ant Design!');
```

**Comment by aswez** [comment]
That's right, thank you.

BTW,
[message.config](https://ant.design/components/message#global-static-methods) can be used to set a custom class prefix, and based on that I can use it to set my own style.
