### ISSUE TITLE
官网DEMO的SELECT自动补全功能存在不显示下拉列表的BUG

### ISSUE THREAD

**Issue by broadliyn** [ant-design/ant-design#3958]
![2016-11-22 19 31 33](https://cloud.githubusercontent.com/assets/12005965/20522284/75c706de-b0ea-11e6-8ff8-0bbb7b761212.png)

之前几个版本，在这里输入关键字，会自动跳出下拉列表提示。但是今天上去看2.4.3版本，输入文字以后经常会不显示下拉列表，需要按一下向下/向上箭头、空格或者多输入几个字符才会跳出下拉列表。

**Comment by benjycui** [comment]
是有问题，请求已经发出并且收到响应，但是结果列表没有展示出来。

**Comment by broadliyn** [comment]
@benjycui 应该是组件的bug吧？因为我在线上的项目里也出现了这个问题

**Comment by afc163** [comment]
@RaoHai 来看下，貌似和之前的改动 https://github.com/react-component/select/pull/134 和 https://github.com/ant-design/ant-design/issues/3778 有关。

1.x 上的例子是好的：http://1x.ant.design/components/select/#components-select-demo-search-box

**Comment by RaoHai** [comment]
https://github.com/react-component/select/blob/master/src/Select.jsx#L702

此处。

第一次 onChange 的时候，触发 adjustOpenState ，此时 children 仍为空，open 就会被设成 false 了。

异步获取到数据的时候，再 setState， 触发 adjustOpenState ， 此时因为 open 为 false，不会进入判断 children 的逻辑。。

adjustOpenState 的初衷是修复这个问题， https://github.com/ant-design/ant-design/issues/2975 。想想是不是有更好的方法……
