### ISSUE TITLE
Remove lodash and use a smaller alternative lib or implement it ourselves

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#39594]
- [x] `antd` #39599 #39602
- [x] `@ant-design/react-slick` https://github.com/ant-design/react-slick/pull/104 #39634
- [x] `rc-align` https://github.com/react-component/util/pull/396 https://github.com/react-component/align/pull/283

`lodash/isEqual` => `shallowequal`、`rc-util/lib/isEqual`
`lodash/debounce` => `throttle-debounce`
`...`

**Comment by li-jia-nan** [comment]
mark

**Comment by yoyo837** [comment]
All landed!

**Comment by li-jia-nan** [comment]
体积有变小吗？

**Comment by yoyo837** [comment]
我看看

**Comment by afc163** [comment]
为啥要保留 shallowequal rc-util/lib/isEqual 两个？

**Comment by yoyo837** [comment]
我再发PR 去掉shallowequal吧

**Comment by yoyo837** [comment]
> 体积有变小吗？

我记得我好像回复了两个图片, 咋找不见了.
