### ISSUE TITLE
我想知道为什么tree组件不可以渲染empty状态 尤其是可搜索的树 这样不是很奇怪吗

### ISSUE THREAD

**Issue by Keen-w** [ant-design/ant-design#39590]
### Reproduction link

[https://ant.design/components/tree-cn](https://ant.design/components/tree-cn)

### Steps to reproduce

就是可搜索的树 如果没搜出来结果 没办法渲染empty状态

### What is expected?

希望可以渲染empty状态

### What is actually happening?

不可以

| Environment | Info |
| --- | --- |
| antd | 4.19.3 |
| React | 17.0.1 |
| System | mac |
| Browser | google |

**Comment by Thulof** [comment]
@Keen-w 可搜索的树，实际上是根据输入框的值计算 Tree 组件的 expandedKeys 属性。因此当搜索结果为空的时候，整颗树处于收起的状态。为了实现你的需求，建议你可以这样写
```tsx
const Demo = () => {
  //  ... other
  return (
    <div>
      { result ? <Tree expandedKeys={result} /> : null }
    </div>
  );
};
