### ISSUE TITLE
"You are calling notice in render" warning when using message via hooks in callback

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#39592]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hooks-usage-recommended-antd-5-0-7-forked-3552bq?file=/demo.tsx)

### Steps to reproduce

When using useMessage hook and triggering the message in a callback (e.g. onSuccess/onError callback of @tanstack/query), the message never shows but triggers "Warning: [antd: Message] You are calling notice in render which will break in React 18 concurrent mode. Please trigger in effect instead."

### What is expected?

Message should show

### What is actually happening?

Message doesnt show

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.2.0 |
| System | osx |
| Browser | chrome |

**Comment by KwokKwok** [comment]
1. use `contextHolder`
```diff
const App: React.FC = () => {
+  const [msg, contextHolder] = message.useMessage();
  // ...
  return (
+    <>
+      {contextHolder}
        <Button type="primary" onClick={() => mutate()}>
          Trigger
        </Button>
+    </>
  );
};

export default App;
```

2. you can use [`message.success()`](https://ant-design.antgroup.com/components/message#api) directly

**Comment by Nuriddin-775** [comment]
It worked on me, nice solution. I was using react 19
