### ISSUE TITLE
`getFieldDecorator` 未实现旧版本中的 `onXxx` 事件参数

### ISSUE THREAD

**Issue by jerrybendy** [ant-design/ant-design#3960]
#### 发生问题的环境是：

- antd 版本:    v2.2.0 （最新版本依旧）
- 操作系统及其版本:  OS X 10.11.6
- 浏览器及其版本:  Chrome 53.0.2785.143

#### 您做了什么？请提供尽可能详细的重现步骤。

既需要 `getFieldDecorator` 的绑定功能用于在 `Form` 顶层获取整个表单的数据，又需要使用 `Select` 的 `onChange` 事件在被选择的项目发生变化时动态增减表单项的内容。

在之前版本中使用 `getFieldProps` 一直工作很好，包括在 antd 2.x 版本中使用 `getFieldProps` 都可以正常工作，只是会抛出一个建议替换成 `getFieldDecorator` 的错误。但换成 `getFieldDecorator` 后就无法工作了。

`getFieldProps` 的参数中支持 `options.onXXX` 形式的事件代理，使得可以自己实现 `onChange` 函数或其它事件函数，并不与 `getFieldProps()` 返回的 `onChange` 事件产生冲突。 

#### 您期待的结果是:

期待能和旧版本的 `getFieldProps` 产生相同的行为。

#### 实际上的结果是:

实际结果事件没有被触发。

#### 可重现的在线演示

演示中使用新旧两种方式各创建一个 `Select` 选择框，但上面的选择框的 `onChange` 事件无法触发。

http://codepen.io/jerrybendy/pen/NbpVJP?editors=0010

**Comment by afc163** [comment]
https://ant.design/changelog#2.x-%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%94%B9%E5%8A%A8

认真阅读下 changelog。:smile_cat:

**Comment by jerrybendy** [comment]
@afc163  很抱歉提出了重复的问题。

我在升级 2.x 之前是有仔细看过升级说明的，也知道继续使用 `getFieldProps` 会产生警告，只是不影响使用就暂时没做修改。今天改成 `getFieldDecorator` 时发现这个问题又重新看了下 changeLog，确信没有提及才提的 BUG。

关于 options.onXXX 的参数在 changeLog 中没有写出， 而是在链接的 #1533 中有相关的讨论。

更新了下 codePen ，现在可以正常工作了。http://codepen.io/jerrybendy/pen/NbpVJP?editors=0010

```diff
- <Select {...getFieldDecorator('SelectField', {onChange: this.handleSelectChange })}>
+ <Select {...getFieldDecorator('SelectField')} onChange={ this.handleSelectChange }>
```

沿用了旧版的写法，和官网上的不太一致。

Thanks :grin:

**Comment by afc163** [comment]
```diff
-  <Input placeholder="text" {...getFieldProps('userName', { ... })} />
+  {getFieldDecorator('userName', { ... })(
+    <Input placeholder="text" />
+  )}
```

**Comment by afc163** [comment]
```js
{getFieldDecorator('userName', {
  onChange: this.handleSelectChange,
})(
  <Input placeholder="text" />
)}
```

另外 onChange 可以这么写。

**Comment by jerrybendy** [comment]
不知道两种写法有多少差距，但后者的可读性都要差一些，并且导致表单组件无法做为顶层组件，例如：

```js
const XXXX = (props) => {
    return (
        <Input {...getFieldDecorator('xxx')} />
    );
}
```

类似的这种情况（应该不会有人这么写吧～），`getFieldDecorator` 函数的形式是无法放在顶层的。

可读性这块倒还好，虽然会有所损失，好在也并不糟糕 😬
