### ISSUE TITLE
TimePicker引入报错，无法获取Style

### ISSUE THREAD

**Issue by zxwGH** [ant-design/ant-design#39603]
### Reproduction link

[https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js](链接)

### Steps to reproduce

import {TimePicker} from 'antd';
import dayjs from 'dayjs';
<TimePicker  defaultOpenValue={dayjs('00:00:00', 'HH:mm:ss')} />

### What is expected?

正常使用

### What is actually happening?

报错  Can't resolve 'antd/es/time-picker/style' 

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.2 |
| System | macOS Ventura 13 |
| Browser | chrome 107.0.5304.110 |

---
使用场景就是 安装antd，引入就会报错，帮忙看看是什么原因，是否需要引入什么全局样式和插件

**Comment by zxwGH** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js

**Comment by zxwGH** [comment]
https://github.com/zxwGH/test/blob/main/antdLink

**Comment by Damon0316** [comment]
a similar error occurred when I started packaging：AssertionError [ERR_ASSERTION]: filePath not found of D:/XXX/XXX/node_modules/antd/es/time-picker/style

**Comment by Thulof** [comment]
抱歉，我使用 vite 创建一个新项目，并没有复现问题。请问你的脚手架是什么？

**Comment by kkxujq** [comment]
![image](https://user-images.githubusercontent.com/14943597/208641743-da06acd9-df91-4424-9efb-2bb0f539d965.png)

**Comment by zxwGH** [comment]
> 抱歉，我使用 vite 创建一个新项目，并没有复现问题。请问你的脚手架是什么？

使用umi脚手架

**Comment by INTMIN** [comment]
> > 抱歉，我使用 vite 创建一个新项目，并没有复现问题。请问你的脚手架是什么？
> 
> 使用umi脚手架
你好，请问下你最后怎么解决的这个问题

**Comment by zxwGH** [comment]
> > > 抱歉，我使用 vite 创建一个新项目，并没有复现问题。请问你的脚手架是什么？
> > 
> > 
> > 使用umi脚手架
> > 你好，请问下你最后怎么解决的这个问题

没有解决

**Comment by INTMIN** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CynthiaNC** [comment]
现在仍然有这个问题，在umi 框架V3.2.28 安装依赖 antd V5.16.1，在Form表单里面引入 <TimePicker /> 组件仍然报错，

 antd/es/time-picker/style in ./src/pages/xxxx/components/xxxx/index.tsx

To install it, you can run: npm install --save antd/es/time-picker/style

看了node_module里面的antd， antd/es/time-picker路径下没有style文件，其他的组件是有style文件的

<img width="315" alt="image" src="https://github.com/ant-design/ant-design/assets/10840720/046fd1d5-4003-4b10-893a-9b4ed3e4b51e">

**Comment by INTMIN** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yoyo837** [comment]
> 现在仍然有这个问题，在umi 框架V3.2.28 安装依赖 antd V5.16.1，在Form表单里面引入 组件仍然报错，
> 
> antd/es/time-picker/style in ./src/pages/xxxx/components/xxxx/index.tsx
> 
> To install it, you can run: npm install --save antd/es/time-picker/style
> 
> 看了node_module里面的antd， antd/es/time-picker路径下没有style文件，其他的组件是有style文件的
> 
> <img alt="image" width="315" src="https://private-user-images.githubusercontent.com/10840720/321835488-046fd1d5-4003-4b10-893a-9b4ed3e4b51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODkwNjEsIm5iZiI6MTcxMjg4ODc2MSwicGF0aCI6Ii8xMDg0MDcyMC8zMjE4MzU0ODgtMDQ2ZmQxZDUtNDAwMy00YjEwLTg5M2EtOWI0ZWQzZTRiNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyMjYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjgwMTEyMjZjNjlmNDM2ZWZmMWYzMDNlM2MyYTZhY2RmYjJmZjBkZGM0YmUwZmVlYTAxZmI1MjM4NWJjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HyHW2Sz34tjw0Ny5vCHFTCelgHHS1KL4kxe6SJWJBnU">

摆脱看一下升级文档

**Comment by yoyo837** [comment]
antd@5是css in js的，你不需要手动引入组件下的style/index.js

**Comment by CynthiaNC** [comment]
> antd@5是css in js的，你不需要手动引入组件下的style/index.js

没有手动引入组件下的style，而是一引入了 TimePicker组件就报错了，报错内容是找不到style文件

**Comment by yoyo837** [comment]
> > antd@5是css in js的，你不需要手动引入组件下的style/index.js
> 
> 没有手动引入组件下的style，而是一引入了 TimePicker组件就报错了，报错内容是找不到style文件

你的umi在尝试查找antd4存在而antd5不存在的问题，请从umi方面尝试解决，例如升级到umi@4

**Comment by WSYProject** [comment]
> > antd@5是css in js的，你不需要手动引入组件下的style/index.js
> 
> 没有手动引入组件下的style，而是一引入了 TimePicker组件就报错了，报错内容是找不到style文件

最后这个问题解决了吗

**Comment by INTMIN** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
