### ISSUE TITLE
Segmented options as links

### ISSUE THREAD

**Issue by bdproduction** [ant-design/ant-design#39608]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ktz4ic?file=/index.js)

### Steps to reproduce

Add options in Segmented component with custom Label containing link

### What is expected?

Label in segmented option containing link to used as navigation.

### What is actually happening?

Clicking on segmented option blocks the link that is provided in the label. 

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.2 |
| System | Windows 10 |
| Browser | Chrome 108.0.5359.100 (Official Build) (64-bit) |

**Comment by afc163** [comment]
It is not proper to use navigation in Segmented.
