### ISSUE TITLE
BreadcrumbItem in react component cause warning in console

### ISSUE THREAD

**Issue by SamanthaGeorges** [ant-design/ant-design#39610]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-t3kkh8)

### Steps to reproduce

1. Create a component A that render a Breadcrumb
2. Instead of put directly a Breadcrumb.Item under the Breadcrumb, create a new react component B that render a BreadcrumbItem
3. Add this new component B inside <Breadcrumb> in component A

### What is expected?

No console warning

### What is actually happening?

If I create a component to define my Breadcrumb.Item I have this warning in console : 
```Warning: [antd: Breadcrumb] Only accepts Breadcrumb.Item and Breadcrumb.Separator as it's children ```

But if I put the code of my Breadcrumb.Item directly under my Breadcrumb inside the same component there is no warning

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 18.x |
| System | Fedora 37 |
| Browser | Chrome Version 108.0.5359.98 (Official Build) (64-bit) |

**Comment by Thulof** [comment]
As the warning say, you should render Breadcrumb.Item directly under Breadcrumb.

**Comment by afc163** [comment]
Please follow the warning.
