### ISSUE TITLE
Input 组件组合使用错位

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#39619]
### Reproduction link

[https://ant.design/components/input-cn](https://ant.design/components/input-cn)

### Steps to reproduce

在Windows 10 系统，2K显示器，使用系统推荐缩放 125% 下 ，浏览器缩放 100%，导致 Input 组件组合使用错位，系统缩放 100% 正常，但是字太小
![微信截图_20221217212913](https://user-images.githubusercontent.com/3166799/208244393-e141ca4f-608d-4e65-9af7-c1522b1b9f21.png)
![微信截图_20221217213004](https://user-images.githubusercontent.com/3166799/208244396-085c3b7a-5bf7-4707-b429-74d1c799cbb3.png)

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | React 18.2.0 |
| System | Windows |
| Browser | Chrome 103 |

**Comment by zombieJ** [comment]
Windows 的缩放老问题

**Comment by afc163** [comment]
没有机器调试，需要大家帮忙了

**Comment by hihuangwei** [comment]
这问题依然还是没有解决，正常高度是32px，在系统缩放是125%s时，变成31.6px，而按钮正常
![360截图20230128124943166](https://user-images.githubusercontent.com/3166799/215242700-6aff0dc3-ec6e-49e5-89bd-806535a8187e.jpg)
