### ISSUE TITLE
Dropdown 配合 Menu 使用，抛出 React.Children.only expected to receive a single React element child. 错误

### ISSUE THREAD

**Issue by ilRainbow** [ant-design/ant-design#39614]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-danilo-t467sp?file=/index.js)

### Steps to reproduce

Dropdown 使用 menu 配置而不是 overlay, 配合定义好的 Menu 组件，即可复现。

### What is expected?

no error

### What is actually happening?

React.Children.only expected to receive a single React element child.

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18 |
| System | windows |
| Browser | chrome@any |

---
使用 overlay 替代 menu 时组件正常

**Comment by JarvisArt** [comment]
认真看一下文档这个api怎么使用
![image](https://user-images.githubusercontent.com/38420763/208238277-705ce083-3cb8-48e8-8c5d-88b47b54b40b.png)

**Comment by wangbiye** [comment]
@JarvisArt menu 配置的变量名只能叫`items`吗

**Comment by JarvisArt** [comment]
menu的配置就是menu的api

**Comment by Aspark1996** [comment]
我遇到的问题是Dropdown menu报错，但Dropdown.Button menu就不会

**Comment by someok** [comment]
这个 bug 我也遇到了，果然 menu 的参数必须命名为 items 才行，汗

**Comment by jiash1998** [comment]
> 这个 bug 我也遇到了，仔细一看，这个 menu 对应的是 Menu 组件的参数，所以这儿必须得是 items

那这样岂不是一个页面只能用一个Dropdown嘛？我就是用了两处，然后发现另一个不是items的一直报错。请问你有什么解决方法吗？

**Comment by afc163** [comment]
@jiash1998 看看这个 https://github.com/ant-design/ant-design/issues/41378#issuecomment-1477938291

**Comment by jiash1998** [comment]
> @jiash1998 @someok @wangbiye 看看这个 [#41378 (comment)](https://github.com/ant-design/ant-design/issues/41378#issuecomment-1477938291)

感谢，问题已解决

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/42256#issuecomment-1541601316
