### ISSUE TITLE
Ant Design Theme Editor theme upload

### ISSUE THREAD

**Issue by rohanbhangui** [ant-design/ant-design#39620]
### What problem does this feature solve?

I was hoping to request the addition of a feature to the theme editor (https://ant.design/theme-editor), where by a user can upload their theme config to make editing easier

### What does the proposed API look like?

Soem sort of upload/import button that allows for a json object to be added

**Comment by BoyYangzai** [comment]
I wrote a version to achieve this feat
you can have a try 
#39621

**Comment by rohanbhangui** [comment]
> I wrote a version to achieve this feat you can have a try #39621

@BoyYangzai  instead of an upload it would be great to have a window open where you can paste the code

**Comment by BoyYangzai** [comment]
> @BoyYangzai instead of an upload it would be great to have a window open where you can paste the code

ok, I done it
have a try
