### ISSUE TITLE
CSS is not loaded 

### ISSUE THREAD

**Issue by shahinghasemi** [ant-design/ant-design#39625]
I'm using next 13, however the CSS are not loaded properly.

### Steps to reproduce

app/layout.tsx
```tsx
import 'antd/dist/reset.css';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head />
      <body>
        {children}
      </body>
    </html>
  );
}
```

app/ant/page.tsx
```tsx
'use client';

import { Button, DatePicker } from 'antd';
export default function () {
  return (
    <div>
      <Button type="primary">Ok</Button>
      <DatePicker />
    </div>
  );
}

```

### What is expected?

When entering http://localhost:3000/ant, the components should be rendered with css applied.

### What is actually happening?

Both components are first rendered without any style then after about 1 seconds the css is applied.

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.2 |
| System | Ubuntu |
| Browser | Firefox/Chrome |

**Comment by BoyYangzai** [comment]
Hello , I tried https://github.com/ant-design/ant-design/issues/16037
It can resolve the problem for `transition flash`

I'm not very familiar with SSR, but I have done ssr-related frameworks, inserting js and css after the DOM is built, maybe a little delay in css is acceptable?

Perhaps this problem can be solved in the field of SSR . Try CDN prefetch or others？

**Comment by CeamKrier** [comment]
I am having a similar issue with the following:

"antd": "^5.0.7"
"next": "13.0.6"
"react": "18.2.0"

I had another project, it was using antd 4.x version and was working fine. The issue might be related that we are not importing the distributed CSS file with version 5 anymore.

**Comment by SohaibRaza** [comment]
I facing the same issue I tries https://github.com/ant-design/ant-design/issues/16037 but issue is still there.
I am using Next.js TypeScript, Ant.design + TailwindCSS

**Comment by davepoon** [comment]
same issue with Next.js 13.1.6 and Ant design 5.1.7

**Comment by silviaphungky** [comment]
i have same issue, please check this url https://63e1ce6cd0f5a308abd8a5d8--gentle-florentine-6b22dd.netlify.app/

**Comment by chrispytoes** [comment]
Same thing is happening to me in my Next.js project but only when I deploy to a DigitalOcean App. Just the CSS reset doesn't load, but the rest of the component styles work.

Running locally everything works fine.

**Comment by stevenpalma123** [comment]
> i have same issue, please check this url https://63e1ce6cd0f5a308abd8a5d8--gentle-florentine-6b22dd.netlify.app/ you can check the repo in https://github.com/silviaphungky/antd-ssr @afc163

This Worked For Me FOUC Solution

**Comment by ashutosh887** [comment]
Happens with me as well
IDK why antd styles don't appear in one of my Browser!

@shahinghasemi @stevenpalma123 @silviaphungky @chrispytoes

**Comment by moodless3** [comment]
me too . until i saw this (CSS files are no longer included in package. Since CSS-in-JS supports importing on demand, the original antd/dist/antd.css has also been abandoned. If you need to reset some basic styles, please import antd/dist/reset.css.
If you need to reset the style of the component, but you don't want to introduce antd/dist/reset.css to pollute the global style, You can try using the [App](https://ant.design/components/app) in the outermost layer to solve the problem that native elements do not have antd specification style.
