### ISSUE TITLE
Add ref to Collapse and Panel component

### ISSUE THREAD

**Issue by Sagie501** [ant-design/ant-design#39628]
### What problem does this feature solve?

I'm using `Collapse` component with a lot of `Panel` components within it with scrolling. I am currently trying to use third party libraries to achieve virtual scroll. Every library that I looked for used refs in order to make the calculation of heights etc. So in order to achieve virtual scroll I need to forward the ref into the `Collapse` and the `Panel` components.

### What does the proposed API look like?

Making `Collapse` and `Panel` components as `forwardRef` components so they can get ref from outside.

**Comment by monolithed** [comment]
https://github.com/ant-design/ant-design/issues/43664
