### ISSUE TITLE
Feature 希望框架可以出一个 类似 ScrollContainer 的组件，美化滚动条

### ISSUE THREAD

**Issue by Venus-WXP** [ant-design/ant-design#39623]
### What problem does this feature solve?

默认情况下，Windows的滚动条就很丑就不说了，而且默认滚动条出现时会占用dom空间导致页面闪动，体验很不好；希望官方可以考虑出一个这样的组件，而且目前 AntDesign Table组件默认滚动条好像也不是特别美观，而且有时候鼠标滑动的时候会偶尔恢复到操作系统原生的丑陋滚动条，这个我就不知道是不是bug了哈。

### What does the proposed API look like?

出一个Scroll组件或者 Container 之类的组件，AntDesign内部所有用到滚动的地方，例如表格定高后的滚动、横向滚动等优先使用这个组件，其次这个组件也可以供UI库使用者自己使用。但愿可以采纳我的菜鸟建议，非常感谢。

**Comment by MadCcc** [comment]
滚动条在各种环境都不一样，浏览器的兼容性也不一样，比如 macos 默认会隐藏滚动条，这点非常难统一，所以暂时不会考虑。

**Comment by Venus-WXP** [comment]
> 滚动条在各种环境都不一样，浏览器的兼容性也不一样，比如 macos 默认会隐藏滚动条，这点非常难统一，所以暂时不会考虑。

请教一下大佬，有没有react好用的虚拟滚动组件可以推荐的？找了好久，每个好用的，Vue3的NaiveUI 和 ElementPlus 都有对应的虚拟滚动组件实现😭：
NaiveUI：
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/18739624/208289662-c6a76fde-014a-45f2-8c92-2747c2a05088.png">
ElementPlus：
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/18739624/208289722-9aa494ba-3fff-4e51-a746-ed6024547c51.png">
