### ISSUE TITLE
Implement theming for use with css-modules

### ISSUE THREAD

**Issue by delijah** [ant-design/ant-design#3963]
React CSS Themr is shipping a very good solution for that approach: https://github.com/javivelasco/react-css-themr

**Comment by afc163** [comment]
Thx for nice suggestion~ `react-css-themr` will be a breaking change for antd less style implementation, you can try this https://github.com/ant-design/ant-design/blob/master/docs/react/customize-theme.en-US.md now.

**Comment by delijah** [comment]
Thank you for your response. I have already seen the docs and i am customizing the theme already with less. It is doable this way, but i think the react-css-themr way is just more convenient. That is why i have created this issue, to start a discussion about that.
