### ISSUE TITLE
English docs for layout

### ISSUE THREAD

**Issue by lednhatkhanh** [ant-design/ant-design#3964]
Can you provide the English version of the [layout ](https://ant.design/docs/spec/layout) docs, they are so nice in mobile devices but I don't understand it!

**Comment by benjycui** [comment]
Try Google translator.

We have no time to translate it now, sorry.

**Comment by afc163** [comment]
Find some volunteers in communication for this? @benjycui

**Comment by benjycui** [comment]
Specification can be translated, but Pattern will be removed in the future.

**Comment by afc163** [comment]
@bang88 @infeng @GrayChoi @xueqingxiao @codering Any of you guys is willing to translate https://ant.design/docs/spec/layout?

**Comment by bang88** [comment]
I think this is unnecessary some contents will changed in the future. I have no time these days ❤️

**Comment by GrayChoi** [comment]
If you think OK,  I will translate it in this month.

**Comment by afc163** [comment]
@GrayChoi OK, thx!

**Comment by afc163** [comment]
@GrayChoi ping

**Comment by GrayChoi** [comment]
@afc163  Sorry, I'm so busy recently . I will translate it in this week.

**Comment by benjycui** [comment]
@lednhatkhanh could you help us to review translation in this PR https://github.com/ant-design/ant-design/pull/4542 ?
