### ISSUE TITLE
Using Cascader as menu item label is not working

### ISSUE THREAD

**Issue by aashayamballi** [ant-design/ant-design#39640]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/top-navigation-antd-5-0-7-forked-3ut4ph?file=/demo.js:0-1097)

### Steps to reproduce

Created a custom component for cascader which takes menu item name/lable as a prop
Add that component in the menu item list for the key label

### What is expected?

when I hover over the menu item or click on the menu item, I should see a cascader component

### What is actually happening?

Gettign the below error 

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Trigger2`.

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by aashayamballi** [comment]
I used label as function to make it as react component and not element, and now it's not showing the menu label name. Can anyone please help me why this is happening?

**Comment by afc163** [comment]
```
<Cascader options={options} onChange={onChange}>
  <span>Navigation One</span>
</Cascader>
```

https://codesandbox.io/s/top-navigation-antd-5-0-7-forked-6dg3o9?file=/demo.js

**Comment by afc163** [comment]
However, it is a bad practice to use Cascader in a Menu Item. Don't try it.

**Comment by aashayamballi** [comment]
@afc163 thanks for you help. 

I would like to know why is it bad practice to use cascader in the menu item? 

for example If I want to display the menu children item as a associated data set with multi stage classification separated for easy selection, is there any better way to do than using Cascader in the Menu Item?

**Comment by aashayamballi** [comment]
well my assumption was incorrect.. I will go with the children items. thanks for your help @afc163
