### ISSUE TITLE
Card 组件在仅传入 extra 时样式异常

### ISSUE THREAD

**Issue by NoDocCat** [ant-design/ant-design#39643]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ylgcz5?file=/index.js)

### Steps to reproduce

打开链接, 无需操作

### What is expected?

卡片头部应该有一定的高度或边距

### What is actually happening?

extra 插入的元素上下贴边

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18 |
| System | Windows 11 |
| Browser | Microsoft Edge 108.0.1462.46 |

**Comment by JarvisArt** [comment]
试了下padding是需要title撑起
![image](https://user-images.githubusercontent.com/38420763/208360886-fddf6810-2096-4598-a0dc-b0d61ed3b3a5.png)

**Comment by JarvisArt** [comment]
对比了下v4中的extra也会有padding，v5是忘了加上样式还是设计如此？

**Comment by NoDocCat** [comment]
@JarvisArt 

这是 V5 的样式:
![image](https://user-images.githubusercontent.com/20502666/208361308-40b10704-23fe-405b-aa3a-350c11967c92.png)

这是 V4 的样式:
![image](https://user-images.githubusercontent.com/20502666/208361410-243cdbff-9b19-441b-84a2-9ec1fafdaccd.png)

简单的读了下 Card 的 style, 声明处存在两个 height token:

https://github.com/ant-design/ant-design/blob/1ce7d3a13d0f76eff60cc2e12076c50419b92470/components/card/style/index.tsx#L9-L21

在使用时使用的是 `cardHeadHeight`:

https://github.com/ant-design/ant-design/blob/1ce7d3a13d0f76eff60cc2e12076c50419b92470/components/card/style/index.tsx#L36-L38

但是有值的 token 应该是 `cardHeaderHeight`:

https://github.com/ant-design/ant-design/blob/1ce7d3a13d0f76eff60cc2e12076c50419b92470/components/card/style/index.tsx#L383-L387

**Comment by NoDocCat** [comment]
追溯了一下, 两个 height token 声明分别来自 @MadCcc 和 @miracles1919
