### ISSUE TITLE
浏览器兼容性

### ISSUE THREAD

**Issue by ffhope** [ant-design/ant-design#39654]
### Reproduction link

[http://43.142.186.210:8082/](http://43.142.186.210:8082/)

### Steps to reproduce

用谷歌浏览器打开显示正常，但是用搜狗浏览器打开显示不正常，已经用了<StyleProvider hashPriority="high">
          <App />
        </StyleProvider>进行兼容，antd代码没有对浏览器进行兼容

### What is expected?

浏览器兼容

### What is actually happening?

没有兼容

| Environment | Info |
| --- | --- |
| antd | 5.0.6 |
| React | 18.2.0 |
| System | window10 |
| Browser | 搜狗浏览器 |

**Comment by yoyo837** [comment]
太久的内核不再支持. 请升级浏览器. 或者联系浏览器开发者升级内核.

**Comment by zombieJ** [comment]
Duplicate of #39511

**Comment by ffhope** [comment]
我手机的夸克浏览器打开也有样式问题，夸克不算旧了吧

**Comment by yoyo837** [comment]
新出的壳不代表内核不旧.

**Comment by ffhope** [comment]
不可能整天要求客户升级浏览器或者换浏览器的，兼容性还是得做的吧，优雅降级

**Comment by yoyo837** [comment]
antd也没有每天都提升一个浏览器版本要求哦.

**Comment by zombieJ** [comment]
兼容样式维护成本非常大，所以才在大版本做切割。这种就是看国产浏览器厂家是不是真心维护自己产品的事情，实际上你知道...

**Comment by SGDS666** [comment]
但是国产浏览器是否及时升级 用户是否保持浏览器版本更新 这些都是不可控因素 业务 也不是技术最新用那个 业务上兼容性的权重占比很大 如果官方不去做兼容 真的对于使用者来说 很麻烦 antdpro 更新antd到v5  chrome88以下的浏览器都会造成样式丢失 布局混乱 这个问题似乎没有什么好的解决方案 只能选择降级到antd v4  希望得到重视 这个仁者见仁 智者见智 业务正常开展 重要 还是技术实现方便重要 需要做平衡 v5 确实激进了 毕竟是做后台管理 的ui库 作为开发者 开发体验固然重要 但是做出来的东西能普及多少用户也很重要 希望有个独立方案可以进行兼容

**Comment by afc163** [comment]
See https://ant.design/docs/react/compatible-style-cn

**Comment by SGDS666** [comment]
> 参见https://ant.design/docs/react/compatible-style-cn

这个方案尝试过 并没有解决问题 而且有bug没有样式 只能导入了v4的样式 勉强出来了 但是antpro 基本上通病是侧边栏 向右侧位移了一个身位 被一个同等大小的div挤到右边去了 head 也被挤占下去 被一个同等大小的div挤占 而且背景变成全黑 页面容器尺寸被撑大到浏览器右侧 通知信息出现后不消失 等等 如果专门维护这个样式 新版本的浏览器也会收到影响 所以并不实用

**Comment by afc163** [comment]
看上去是 pro-components 没有兼容好？可以提到 https://github.com/ant-design/pro-components/issues 并提供重现。

**Comment by SGDS666** [comment]
> 看上去是pro-components没有兼顾好？可以提到https://github.com/ant-design/pro-components/issues并提供重新发现。

这个不用提供重新 随便找个antdpro项目升级到v5  用 chrome 88以下浏览器打开 100%出现的

**Comment by SGDS666** [comment]
就是浏览器兼容问题 这个pro-components应该没有办法解决

**Comment by SGDS666** [comment]
就是花时间处理 后续维护2套样式的方案也不是很靠谱 所以目前的选择是降级比较稳妥 除非有一套新的兼容方案出现
