### ISSUE TITLE
请问你们团队能提供 ReScript 的绑定吗？

### ISSUE THREAD

**Issue by limitLiu** [ant-design/ant-design#39658]
### What problem does this feature solve?

我目前在项目使用到你们的这个 ant-design 组件库，但是我的项目语言是 ReScript，现在的情况是我基本上想用啥就要手写对应组件的绑定。因此希望官方能出一个 ReScript 的绑定 npm 包，如果你们有相关想法可以跟我交流一下。

### What does the proposed API look like?

希望能提供一个 ReScript 版的绑定 npm 包。

**Comment by zombieJ** [comment]
我们暂时没有这个计划，但是如同 antd vue、antd angular、Ant Design Blazor 等库一样，如果有兴趣维护一套，我们很乐意在官网推荐哈~
