### ISSUE TITLE
Tabs Pane ink bar doesn't properly calculate width and position

### ISSUE THREAD

**Issue by mrlubos** [ant-design/ant-design#39666]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zoj0go?file=/index.js)

### Steps to reproduce

Simple use of the `<Tabs>` component with changing label value.

### What is expected?

Ink bar position is calculated correctly.

### What is actually happening?

Ink bar position is calculated incorrectly. This used to work in v4

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.2.0 |
| System | macOS 13.1 |
| Browser | Chrome 108.0.5359.124 |

**Comment by candy4290** [comment]
I solved this problem temporarily by changing the key
https://codesandbox.io/s/antd-reproduction-template-forked-9tuijg?file=/index.js

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/39653
