### ISSUE TITLE
Introduce tslint-react

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#3966]
Rules need fix:

- [x] jsx-alignment
- [x] jsx-curly-spacing
- [x] jsx-no-multiline-js
- [x] ~~jsx-no-string-ref~~
- [x] jsx-self-close

**Comment by afc163** [comment]
版本也可以升上来了？https://github.com/ant-design/ant-design/blob/13e13f333d37e099e95d5d33d284c177641df8c8/package.json#L80
