### ISSUE TITLE
Missing `menuSubMenuBg` when override Menu color

### ISSUE THREAD

**Issue by doiya46** [ant-design/ant-design#39676]
### Reproduction link

Currently We have to add `as any` to pass EsLint

![Screenshot from 2022-12-20 13-44-45](https://user-images.githubusercontent.com/61301244/208601481-d6b4e820-3a7f-46b6-8fb6-c79313384f88.png)

[Edit on CodeSandbox](https://codesandbox.io/s/vertical-menu-antd-5-0-7-forked-9hzle2?file=/demo.tsx:1520-1535)

### Steps to reproduce

```ts
<ConfigProvider
      theme={{
        components: {    
          Menu: {
            menuSubMenuBg: '#1f2e6c',
          },
        },
      }}
    >
</ConfigProvider>
```

### What is expected?

Typescript EsLint worked

### What is actually happening?

```
Type '{ menuSubMenuBg: string; }' is not assignable to type 'Partial<ComponentToken> & Partial<AliasToken>'.
  Object literal may only specify known properties, and 'menuSubMenuBg' does not exist in type 'Partial<ComponentToken> & Partial<AliasToken>'.
```

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | ^18.0.26 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by MuxinFeng** [comment]
maybe you can try replacing `colorSubItemBg` with `menuSubMenuBg `

**Comment by doiya46** [comment]
> 

It didn't work correctly

**Comment by doiya46** [comment]
> maybe you can try replacing `colorSubItemBg` with `menuSubMenuBg `

It didn't work correctly

**Comment by MadCcc** [comment]
`menuSubMenuBg` is not exported, it may be a bug that it works in theming.

**Comment by MadCcc** [comment]
Component Token request will be traced here: https://github.com/ant-design/ant-design/issues/38975
