### ISSUE TITLE
way to set row attributes in Table

### ISSUE THREAD

**Issue by vagusX** [ant-design/ant-design#39682]
### What problem does this feature solve?

Sometimes I need to set a extra html attribute for `tr`

![image](https://user-images.githubusercontent.com/6828924/208630105-c1e8fff2-b99d-45a1-a13c-16a62a38233c.png)

### What does the proposed API look like?

no idea yet

**Comment by linxianxi** [comment]
[onRow](https://ant.design/components/table-cn#onrow-%E7%94%A8%E6%B3%95)
