### ISSUE TITLE
Tabs Alignment

### ISSUE THREAD

**Issue by SohaibRaza** [ant-design/ant-design#39684]
### What problem does this feature solve?

Currently horizontal Tabs can only be positioned "left" or "center".
by default positioned left, and can positioned center by passing `centered={true/false}`.
Need to allow `"right"  | "center" | "left"`, while `left` is default

### What does the proposed API look like?

`position="right"  | "center" | "left"`

**Comment by afc163** [comment]
Try https://ant.design/components/config-provider#components-config-provider-demo-direction

```
  <ConfigProvider direction="rtl">
    <App />
  </ConfigProvider>
```
