### ISSUE TITLE
Inner links are not working on the documentation

### ISSUE THREAD

**Issue by viranmalaka** [ant-design/ant-design#39680]
### Reproduction link

[https://ant.design/components/form#api](https://ant.design/components/form#api)

### Steps to reproduce

When you click on a link (highlighted in blue), the documentation page navigates to a subsection of the same page, they are not working correctly.
eg: on the Form API section, the fourth row, has a description with `View example`. that link is not working.

### What is expected?

I need to navigate to the subsection of the same page by clicking on the hash route links.

### What is actually happening?

Nothing happened. It just stuck the page there. 

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | react |
| System | Mac OS Ventura |
| Browser | Chrome latest |

---
but the URL is changing correctly and if you refresh the browser it will navigate to the correct section.

**Comment by BoyYangzai** [comment]
It's really a bug
