### ISSUE TITLE
Justify and align properties are not reactive for Row

### ISSUE THREAD

**Issue by KathRains** [ant-design/ant-design#39690]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/grid-sort-antd-5-0-7-forked-85qlli?file=/demo.js)

### Steps to reproduce

1. Create a row with align and justify properties lined to the variables.
2. Change the variables with some UI (like in our example, we use Select)

### What is expected?

The align and justify of Row should change reactively

### What is actually happening?

They don't

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.0.0 |
| System | Windows 7 |
| Browser | 108.0.5359.125  |

---
Other properties like gutter work reactively.

**Comment by candy4290** [comment]
Can I pick up this task?
