### ISSUE TITLE
Typing of onCheck prop of Tree component is inconsistent with it's document

### ISSUE THREAD

**Issue by ryohpops** [ant-design/ant-design#39696]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-e0fuv5?file=/index.tsx)

### Steps to reproduce

1. Use Tree component with some data.
1. TypeScript complier reports an error at first parameter of onCheck callback, as line 31 in the sandbox.

### What is expected?

According to the document of Tree component, type of the parameter should be `Key[]`.

### What is actually happening?

The type is defined as `{checked: Key[]; halfChecked: Key[];} | Key[]`.

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | react 18.2.0 |
| System | Windows 10 22H2 |
| Browser | Chrome 108.0.5359.99 |

**Comment by afc163** [comment]
https://github.com/react-component/tree/blob/7dbaebb3fa3ddead8b0a24284169a12133ca074e/src/Tree.tsx#L893-L896

**Comment by MadCcc** [comment]
![image](https://user-images.githubusercontent.com/27722486/208807207-a70e4793-6006-49bb-b981-893cd9d9970f.png

**Comment by ryohpops** [comment]
I'm sorry for not checking the document closely. I might have seen too many issues caused by outdated typings. Thank you for your pinpointed replies.
