### ISSUE TITLE
单选框（Radio.Group） buttonStyle 属性不起作用

### ISSUE THREAD

**Issue by bowlingQ** [ant-design/ant-design#39709]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-driscoll-ne6z9g?file=/src/App.tsx)

### Steps to reproduce

Radio.Group 上的属性 buttonStyle 默认为 outline，改为 solid 不生效

### What is expected?

buttonStyle 能够正常使用

### What is actually happening?

buttonStyle 可以控制样式 描边还是填充

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.0.0 |
| System | macos 13.0.1 |
| Browser | 108.0.5359.124（正式版本） (arm64) |

**Comment by Gip886** [comment]
![image](https://user-images.githubusercontent.com/49873054/208855191-201bef45-9292-47ea-8396-00abbcbf78c3.png)
设置一下optionType？

**Comment by afc163** [comment]
只有当 optionType 为 button 时，buttonStyle 才生效。

**Comment by BraisedEggs** [comment]
/
![sp20240829_145803_586](https://github.com/user-attachments/assets/88fddd40-ae11-4c0d-b8cb-96d9439b6d69)
没用
