### ISSUE TITLE
Modal.method 和 Notification 在Shadow DOM中沒有样式

### ISSUE THREAD

**Issue by TallNutAlarak** [ant-design/ant-design#39707]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-sunset-3vw651)

### Steps to reproduce

点击 modal 和 notification 按钮，出现的东西没有样式

### What is expected?

带有样式

### What is actually happening?

没有样式

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | win11  10.0.22621 版本 22621 |
| Browser | 版本 108.0.5359.125（正式版本） （64 位） |

---
可能其他类似的组件也有问题

**Comment by zombieJ** [comment]
使用 hooks 版本，静态方法无法感知上下文。另外你的 reproduce 没有写相关代码示例哈~

**Comment by csic21** [comment]
@zombieJ  用了hooks版本也不行没有样式,在他的基础上加了一下 [codesandbox](https://codesandbox.io/embed/aged-monad-vtsix8?fontsize=14&hidenavigation=1&theme=dark)

**Comment by TallNutAlarak** [comment]
@zombieJ 十分感谢

**Comment by csic21** [comment]
> @csic21 我这可以了 reproduce 更新了

那就是除了hooks另外要补充下getContainer，手动更改下挂载节点
