### ISSUE TITLE
Table 固定列 如果不是columns的头和尾，样式错误。

### ISSUE THREAD

**Issue by weishenlan** [ant-design/ant-design#39710]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-1-0-forked-l40vb5)

### Steps to reproduce

columns为配置化，固定列不一定在头和尾

### What is expected?

不论顺序，只看固定位置

### What is actually happening?

固定列在页面中间，很奇怪

| Environment | Info |
| --- | --- |
| antd | 4.21.6 |
| React | 16.14.0 |
| System | mac 2021 |
| Browser | chrome |

**Comment by afc163** [comment]
我们建议把固定列始终放在 columns 头部或尾部。
