### ISSUE TITLE
Drawer组件无法关闭

### ISSUE THREAD

**Issue by niujianqiang123** [ant-design/ant-design#39711]
### Reproduction link

[https://4x.ant.design/components/drawer-cn/#API](https://4x.ant.design/components/drawer-cn/#API)

### Steps to reproduce

1、引入Drawer组件
2、设置open属性和控制open属性的state状态
3、改变state为true，Drawer组件显示
4、改变state为false，也就是open属性为false，Drawer组件无法隐藏

```js
const [open, setOpen] = useState(false);
<Drawer
        title='选择'
        placement='right'
        onClose={onClose}
        open={open}
      >
        <p>Some contents...</p>
        <p>Some contents...</p>
        <p>Some contents...</p>
      </Drawer>
```

### What is expected?

open属性改变为false时，Drawer可以正常关闭

### What is actually happening?

open属性改变为false时，Drawer无法关闭

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 17 |
| System | macOS Monterey 12.6 |
| Browser | Chrome  108.0.5359.124（正式版本） (arm64) |

**Comment by yoyo837** [comment]
Fixed by #39561

**Comment by candy4290** [comment]
我尝试复现：https://codesandbox.io/s/ji-chu-chou-ti-antd-4-24-5-forked-xc9jgn?file=/demo.tsx
但是没有发现任何问题 @niujianqiang123

**Comment by niujianqiang123** [comment]
open={open || visible}



// 当open为true，则这个表达式为true；
// 当open为false，则这个表达式为undefined；
// 建议更改为 visible || open; open应该在后面；




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月22日(星期四) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Drawer组件无法关闭 (Issue #39711)





 
我尝试复现：https://codesandbox.io/s/ji-chu-chou-ti-antd-4-24-5-forked-xc9jgn?file=/demo.tsx
 但是没有发现任何问题 @niujianqiang123

**Comment by afc163** [comment]
@niujianqiang123 最新的 4.x 版本已无法重现你描述的问题。

**Comment by niujianqiang123** [comment]
rc-Drawer 6.0.2 可复现，6.0.3无复现
关键代码段, rc-Drawer内，猜测，这个处理内没有把open为undefined的情况进行处理，所以当open为false时；open: open || visible; 接收到的最终open值为undefined;
  var props = _objectSpread(_objectSpread({}, defaultProps), drawerProps);









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月22日(星期四) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Drawer组件无法关闭 (Issue #39711)





 
我尝试复现：https://codesandbox.io/s/ji-chu-chou-ti-antd-4-24-5-forked-xc9jgn?file=/demo.tsx
 但是没有发现任何问题 @niujianqiang123

**Comment by afc163** [comment]
那移除 lock 文件重新按照 node_modules 即可，semver 会安装到最新 rc-drawer 的。

**Comment by niujianqiang123** [comment]
嗯呢，感谢您的回复，我也想到了这个解决办法，但是最好还是在下个版本里修改代码，判断open为false；visible为undefined的情况，否则别人可能无法解决这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月22日(星期四) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Drawer组件无法关闭 (Issue #39711)





 
那移除 lock 文件重新按照 node_modules 即可，semver 会安装到最新 rc-drawer 的。

**Comment by MadCcc** [comment]
rc-drawer 已经发布了 6.1.0，配套升级：https://github.com/ant-design/ant-design/pull/39561
