### ISSUE TITLE
暗黑模式下modal的confirm是白色

### ISSUE THREAD

**Issue by louzhihao** [ant-design/ant-design#39725]
### Reproduction link

[https://ant.design/components/modal-cn?theme=dark](https://ant.design/components/modal-cn?theme=dark)

### Steps to reproduce

点击confirm弹出弹窗

### What is expected?

点击confirm弹出弹窗的主题色要跟暗黑模式匹配上

### What is actually happening?

点击confirm弹出弹窗的主题色还是明亮模式的效果一样

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.0.0 |
| System | Windows10 |
| Browser | Chrome107.0.5304.10 |

**Comment by louzhihao** [comment]
![image](https://user-images.githubusercontent.com/45398295/209049648-3f476767-b056-4077-9db3-c4379829b877.png)

**Comment by afc163** [comment]
你需要使用 useModel 来获取 context 上下文。https://ant.design/components/modal-cn?theme=dark#components-modal-demo-hooks

https://ant.design/components/modal-cn?#%E4%B8%BA%E4%BB%80%E4%B9%88-modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-contextredux%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-configprovider-localeprefixclstheme-%E7%AD%89%E9%85%8D%E7%BD%AE

**Comment by MadCcc** [comment]
这个 demo 可以改一下

**Comment by louzhihao** [comment]
OK

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546
