### ISSUE TITLE
Why Tabs defaultActiveKey undefined or the key which is not present activates the first tab pane?

### ISSUE THREAD

**Issue by aashayamballi** [ant-design/ant-design#39730]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-1-0-forked-cicz5o?file=/demo.js)

### Steps to reproduce

create a simple tabs component

add a defaultActiveKey prop and pass undefined/the key which does not exist

### What is expected?

no default tab pane should be selected

### What is actually happening?

so when defaultActiveKey prop has an incorrect key, the Tab component is actually activating the first tab pane. Also for the activeKey prop when undefined is passed, first tab pane gets activated. 

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
It's by design. For Tabs component. It's meanless when all tabs not match and pane not show. It will fallback to first.

This is used to deal with the situation that if the deleted / modified tab are in the active state under the uncontrolled state, the developer has to change to the controlled state to reset the active Tab.

ref: https://github.com/react-component/tabs/blob/879139fea07d04187306d860b1d21bfcf97ef95a/src/Tabs.tsx#L126

**Comment by aashayamballi** [comment]
thank you for clarifying this

**Comment by aashayamballi** [comment]
@zombieJ  is there any way where we do not want to fall back to the first tab pane?

because in my case the active tabs are key based on the URL path parameter. for example, if the user gives an invalid path operation that does not exist in the Tab component never should activate the first tab pane. even if I programmatically set it to some invalid value defaultActiveKey will always set it to the first tab.

**Comment by aashayamballi** [comment]
got it working by using activeKey prop instead of defaultActiveKey.

**Comment by aashayamballi** [comment]
@zombieJ for the `activeKey={undefined}` actually sets the first tab pane. I know we cann write a logic like this `activeKey={activeTabKey || null}`

should `undefined` for activeKey prop, activate the first tab pane too?

**Comment by zombieJ** [comment]
You can HOC with 2 Tabs. One is Tabs Nav list and another is pane list. When key not exist in the tab list, pane list tabs hide directly.
