### ISSUE TITLE
Tree组件在微信小程序中使用时，拖拽无效

### ISSUE THREAD

**Issue by xhh1996** [ant-design/ant-design#39737]
### Reproduction link

[https://docs.qq.com/slide/DU2RGc051QWZmYWtm](https://docs.qq.com/slide/DU2RGc051QWZmYWtm)

### Steps to reproduce

微信小程序中的腾讯文档ppt，工具栏绘图-排列-全部图层侧边栏中可复现
1.点击工具栏绘图-排列-全部图层
2.拖动item

### What is expected?

能够正确拖动和放置

### What is actually happening?

放置无效

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 16.14.0 |
| System | ios |
| Browser | chrome 106.0.5249.119 |

---
微信小程序不响应dragover事件

**Comment by afc163** [comment]
antd 专注于 PC 端应用，不适合在微信小程序中使用。

**Comment by zombieJ** [comment]
这个应该和腾讯的 X5 反馈。。。
