### ISSUE TITLE
升级2.4后侧边导航hover状态时显示被遮挡

### ISSUE THREAD

**Issue by ericshao** [ant-design/ant-design#3973]
#### 发生问题的环境是：

- antd 版本:2.4.3
- 操作系统及其版本: macOS 10.12.1
- 浏览器及其版本: Chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。
侧边导航hover时显示不完整，菜单文字被遮挡（附截图）

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/2464931/20551745/b2ccae96-b17e-11e6-8f1c-147fe5ceb890.png)

**Comment by benjycui** [comment]
自行调整 `z-index` 解决吧。

**Comment by ericshao** [comment]
overflow: visible;
