### ISSUE TITLE
Table Column 的filtered只有第一次设置时生效的，后面在更改就不生效了

### ISSUE THREAD

**Issue by Edric-Li** [ant-design/ant-design#39740]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-dqtn6m?file=/index.js)

### Steps to reproduce

点击Set按钮，会切换 filtered 的值

### What is expected?

表头的筛选高亮效果动态的消失或显示

### What is actually happening?

一旦显示，再也不会消失了

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

---
我的筛选情况比较复杂，是自定义筛选，大概功能有，等于不等于，包含不包含等，就是数据库查询那一套东西，in like等，但是现在这个高亮效果没办法设置上。

**Comment by Edric-Li** [comment]
希望官方能尽快确认一下这个bug，是否能修复，因为下周就内测了，是否可以修复，希望官方先给个消息，哪怕后边在修也是可以的，拜托了...

**Comment by afc163** [comment]
看上去是个 bug。

**Comment by candy4290** [comment]
我来尝试解决下

**Comment by zqran** [comment]
@Edric-Li 
要通过受控模式来控制筛选的话，需要添加 `filteredValue` 属性~ 否则，受控无效。参考：[可控的筛选和排序](https://ant.design/components/table-cn#components-table-demo-reset-filter)
