### ISSUE TITLE
antd 文档问题

### ISSUE THREAD

**Issue by Dreamcreative** [ant-design/ant-design#39749]
### Reproduction link

[https://ant.design/components/overview-cn/](https://ant.design/components/overview-cn/)

### Steps to reproduce

1. 组件总览 -> 搜索组件
2. 网站左上角 版本切换

### What is expected?

1. 组件总览 -> 搜索组件 能正常搜索
2.  网站左上角 版本切换可以切换其他版本

### What is actually happening?

1. 组件总览 -> 搜索组件 无效
2. 网站左上角 版本切换无效

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | react |
| System | MacBook Pro (15-inch, 2016) |
| Browser | chrome 108.0.5359.124 |

**Comment by MadCcc** [comment]
JS 没加载完。国内用户推荐访问国内镜像：https://ant-design.antgroup.com/

**Comment by Dreamcreative** [comment]
![WX20221223-112359](https://user-images.githubusercontent.com/23378455/209264869-8013e087-cdb4-4fca-a46a-6d4d90b1ea0b.png)
