### ISSUE TITLE
主题 Token Typescript 类型  HeightMapToken 缺少值

### ISSUE THREAD

**Issue by zynyy** [ant-design/ant-design#39752]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2nrlkn?file=/index.js)

### Steps to reproduce

![](https://user-images.githubusercontent.com/28705449/209272512-d64a3476-f330-4092-9595-a8fe44fd4de7.png)
![](https://user-images.githubusercontent.com/28705449/209272803-9c8cac4c-3dde-4588-a7e4-82ed50ed5448.png)
```
import { genComponentStyleHook } from "antd/es/theme/internal";

export default genComponentStyleHook("DatePicker", (token) => {
  const { controlHeightSM, antCls, controlHeight } = token || {};

  return {
    [`${antCls}-demo`]: {
      height: controlHeightSM || controlHeight * 0.75
    }
  };
});
```

### What is expected?

```js
export interface HeightMapToken {
  controlHeightXS: number;
  controlHeightSM: number;
  controlHeightLG: number;
}
```

### What is actually happening?

```js
export interface HeightMapToken {

}
```

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | mac |
| Browser | Google Chrome 108.0.5359.124 |

**Comment by MadCcc** [comment]
这些被打了 internal flag，编译之后省略了。
