### ISSUE TITLE
Documentation: notification.warn is deprecated but the documentation still shows it under API

### ISSUE THREAD

**Issue by anjantalatam** [ant-design/ant-design#39764]
### Reproduction link

[https://ant.design/components/notification#api](https://ant.design/components/notification#api)

### Steps to reproduce

1. Open the reproducible link
2. Check the 5th line [ notification.warn(config) ]

### What is expected?

notification.warn(config) shouldn't be in the documentation as it is deprecated.

### What is actually happening?

notification.warn(config) is currently listed under API

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

**Comment by anjantalatam** [comment]
I can pick this up.

Let me know.

**Comment by anjantalatam** [comment]
Check this line for supported API's for notification

https://github.dev/ant-design/ant-design/blob/master/components/notification/interface.ts#L15

**Comment by zombieJ** [comment]
Thx @anjantalatam , pls feel free to PR to update doc : )
