### ISSUE TITLE
yarn3 安装使用 antd 5.1.0， error： Could not resolve "rc-motion"

### ISSUE THREAD

**Issue by qlniu** [ant-design/ant-design#39763]
### Reproduction link

[https://github.com/qlniu/vite-react-demo](https://github.com/qlniu/vite-react-demo)

### Steps to reproduce

1. 使用 yarn  版本 3.3.1

2. 
安装项目： yarn

本地运行： yarn dev

3. 在 /src/App.tsx文件中引入antd, 并使用
```
import { Button } from 'antd';
```
```
<Button>的点点滴滴</Button>
```

4. 报错如下:

```
✘ [ERROR] Could not resolve "rc-motion"

    .yarn/__virtual__/rc-image-virtual-8cbb919e39/0/cache/rc-image-npm-5.12.1-247d2e7cb0-93cb53f013.zip/node_modules/rc-image/es/Preview.js:10:22:
      10 │ import CSSMotion from 'rc-motion';
         ╵                       ~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "rc-motion" here because it's not listed as a
  dependency of this package:

    .pnp.cjs:7412:33:
      7412 │           "packageDependencies": [\
           ╵                                  ~~

  You can mark the path "rc-motion" as external to exclude it from the bundle, which will remove
  this error.

```

### What is expected?

可以正常使用antd

### What is actually happening?

[ERROR] Could not resolve "rc-motion"

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | MacBook Pro  12.4  |
| Browser | 108.0.5359.98（正式版本） (x86_64) |

**Comment by afc163** [comment]
https://github.com/react-component/image/releases/tag/v5.12.2
