### ISSUE TITLE
使用 Form getFieldDecorator 遇到的问题

### ISSUE THREAD

**Issue by zhaotoday** [ant-design/ant-design#3976]
```js
<Form.Item
  labelCol={{span: 2}}
  wrapperCol={{span: 20}}
  label="内容"
  required
  hasFeedback>
  {getFieldDecorator('content', {
    rules: [{
      required: true,
      message: '请输入内容'
    }],
  })(
    <Editor afterChange={this._handleAfterChange} />
  )}
</Form.Item>
```
Editor 是我自定义的组件，程序可以执行但是报了个警告：
Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.

**Comment by benjycui** [comment]
`Editor.defaultProps` 里面应该是定义了 `value`，得去掉。

目前没想到办法区分用户自行设置的属性和默认属性。

**Comment by zhaotoday** [comment]
有点坑，不过构建后的代码没有警告，先这样了。

**Comment by yaoxiaobei** [comment]
怎么解决的啊大神

**Comment by Xiaoshuai** [comment]
改成用initialValue？

**Comment by FE-Mars** [comment]
有办法解决么

**Comment by yaoxiaobei** [comment]
benjycui 说的对

**Comment by lileilei** [comment]
upload 组件
`<FormItem
              {...formItemLayout}
              label="图片"
            >
              {getFieldDecorator('picurls', {
                valuePropName: 'fileList',
                initialValue: item ? item.picurls : [],
                getValueFromEvent: this.handleChange
              })(
                <Upload
                  action={pkage.imgServer+"upload"}
                  listType="picture-card"
                  data={{prx:'jpg,png,gif,jpeg'}}
                  onPreview={this.handlePreview}
                  onChange={this.handleChange}
                >
                  {uploadButton}
                </Upload>
              )}
            </FormItem>`
初始化的值格式，与后添加的值格式，getFieldsValue 获取的两种数据类型

**Comment by xgqfrms-gildata** [comment]
# too much bugs!

> `type="number" ` === `initialValue: record.pname,`

# must keep `input type` same 

```jsx
    <FormItem
        label={<span className="left-spaces">角色编码:</span>}
        style={{}}
        >
        {
            getFieldDecorator('roleCode', {
                initialValue: record.pname,
                rules: [{ required: false, message: '角色编码' }],
            })
            (
                <Input 
                    prefix={<Icon type="user" style={{ fontSize: 13 }} />} 
                    type="number" 
                    placeholder="角色编码" 
                    />
            )
        }
    </FormItem>

```

**Comment by YoRenChen** [comment]
使用setFieldsValue 里面的属性的设置来代替Value？

**Comment by lizhengnacl** [comment]
`getFieldDecorator`的参数`valuePropName`指向的属性，不能出现在自定义组件的`defaultProps`中，`valuePropName`默认指向`value`

**Comment by navono** [comment]
应该在`getFieldDecorator`的时候，设置`initialValue`。
然后把自定义控件中的`value`属性删除。
这样就没有警告了。

**Comment by CallMeXYZ** [comment]
`defaultProps`用起来貌似没bug，只是会报warning。解决办法一种是前面说的`initialValue`，另一种是在组件内每次取value时手动设置默认值。

**Comment by fenghuizhang** [comment]
Input 组件设置 valuePropName: 'disabled' , 也有问题;
设置这个报警告 只能用setFieldsValue,  明明我用的就是setFieldsValue;
 只能用setState,才能正确控制表单内的Input的disabled

**Comment by CallMeXYZ** [comment]
antd 里面很多的组件都是内部用state去管理，state根据控制层的props变化，这样state可以有设置默认值等各种行为

**Comment by nazhenhuiyi** [comment]
```
export default function (props: Overwrite<SchemaFormEditorProps, {
    onChange?(value: any[]): void,
    value?: FieldSchema[]
  }>) {
  return <SchemaFormEditor {...props} />
}
```

解决思路是在原来的设置了 defaultProps 的组件再包装一层，可以避免这个 warning。
感觉这个 warning 校验的不是很好。

**Comment by hellomrbigshot** [comment]
> `getFieldDecorator`的参数`valuePropName`指向的属性，不能出现在自定义组件的`defaultProps`中，`valuePropName`默认指向`value`

对的，我就是自定义 markdown 编辑器设置了 defaultProps 后出现了这个 warning。

**Comment by hellomrbigshot** [comment]
> > `Editor.defaultProps` 里面应该是定义了 `value`，得去掉。
> > 目前没想到办法区分用户自行设置的属性和默认属性。
> 
> 去掉了defaultProps里的value，但是报了这种错，有设置initialValue且initialValue不为undefined：
> 
> ```
> The prop `value` is marked as required in `BackendInputNumber`, but its value is `undefined`
> ```
> 
> 大佬能解答一下吗？自定义组件只是封装了一下inputNumber。另外，input和inputNumber包了个其它元素,getFieldDecorator就没法对它赋值和onChange操作了？

用法问题吧，我的在 antd 表单中使用组件的方式是这样的
```
<Form.Item>
        {getFieldDecorator('content', {
             rules: [{ required: true, message: '请输入文章内容' }],
             initialValue: articleDetail.content
         })(<MEditor theme='dark'/>)}
</Form.Item>
```
你的 initialValue 在组件初始化的时候是不是未定义？

**Comment by cuiWant** [comment]
index.js:1 Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.

**Comment by cuiWant** [comment]
index.js:1 Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.

**Comment by cuiWant** [comment]
index.js:1 Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.
我也遇到这个错误了，自定义组件报的错，我是value 值设置出的问题自定义的value 值没有传入参数 undefind 就会出这个错误。
