### ISSUE TITLE
全局样式针对 Modal.confirm 不生效，比如按钮颜色

### ISSUE THREAD

**Issue by AsasinCree** [ant-design/ant-design#39760]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-0-3-forked-9u4861)

### Steps to reproduce

无

### What is expected?

全局样式针对 Modal.confirm 生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 17.0.2 |
| System | win 10专业版1909 |
| Browser | chrome 版本 96.0.4664.45（正式版本） |

---
已经看过  https://github.com/ant-design/ant-design/issues/39239 和 https://github.com/ant-design/ant-design/issues/39023
都没有正确的答复

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/39725#issuecomment-1362365736
https://github.com/ant-design/ant-design/issues/39023#issuecomment-1328256100

**Comment by afc163** [comment]
https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-1-0-forked-ldqd9f?file=/demo.tsx
