### ISSUE TITLE
Table -> Expandable row table header is rendered as td and has no top left border radius

### ISSUE THREAD

**Issue by marekPrzybylakSof** [ant-design/ant-design#39769]
### Reproduction link

[https://ant.design/components/table](https://ant.design/components/table)

### Steps to reproduce

Even in official docs this bug is visible.

### What is expected?

Bugfix to render `<td>` as `<th>`

### What is actually happening?

In Table -> Expandable row version first `<th>` is rendered as `<td>` so CSS is not following this rule:
```
:where(.css-dev-only-do-not-override-19mkp0n).ant-table-wrapper .ant-table-container table>thead>tr:first-child th:first-child {
    border-start-start-radius: 8px;
}
```
<img width="1528" alt="Screenshot 2022-12-23 at 11 29 12" src="https://user-images.githubusercontent.com/98966835/209321389-b0575aa0-3470-48e3-829b-334304f0b32e.png">

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | MacOs Ventura 13.1 |
| Browser | Chrome 108.0.5359.124 (Official Build) (x86_64) |

**Comment by chunsch** [comment]
render `<td>` because a11y: https://github.com/react-component/table/pull/859, let me fix it.
