### ISSUE TITLE
Drawer component is broken in 5.1.0

### ISSUE THREAD

**Issue by shanthuk** [ant-design/ant-design#39777]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-1-0-forked-9t2vtu?file=/demo.tsx)

### Steps to reproduce

https://codesandbox.io/s/basic-antd-5-1-0-forked-9t2vtu?file=/demo.tsx

### What is expected?

Drawer expanding with whole space

### What is actually happening?

See the sandbox sample

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18 |
| System | chrome and Edge |
| Browser | chrome and Edge |

---
https://codesandbox.io/s/basic-antd-5-1-0-forked-9t2vtu?file=/demo.tsx

**Comment by candy4290** [comment]
It looks like the missing default value of "right" for the placement property,

**Comment by candy4290** [comment]
![image](https://user-images.githubusercontent.com/19907991/209415461-f7af0c1e-caba-403b-9ef8-ecc981ed0e2f.png)

**Comment by yoyo837** [comment]
Why set `placement={undefined}`?
