### ISSUE TITLE
Passing custom css-in-js to Ant components

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#39787]
### What problem does this feature solve?

All the components that already consume `style` prop e.g. Modal's `bodyStyle`, `maskStyle` and `style` should be able to consume css-in-js as well. 

I am converting less to Emotion. I need to adjust css for Modal's `.ant-modal-content` class and it's impossible to do. 

### What does the proposed API look like?

New props such as `bodyCss`, `maskCss`, `css` etc.

**Comment by zombieJ** [comment]
Please fire issue to emotion instead. `css` style is emotion wrap props which we do not have. And as I know emotion also support nest structure selector to handle inner dom style:

https://codesandbox.io/s/ji-ben-antd-5-1-0-forked-n59lhc?file=/demo.tsx

**Comment by Kamahl19** [comment]
@zombieJ This has nothing to do with Emotion library. I am talking about Ant components actually supporting css-in-js, not just using it internally.

Most of the codebases migrating from ant v4 to v5 are also migrating their Less files to css-in-js (most probably Emotion since it's recommended in Ant documentation). However Ant components don't really allow customising their css using css-in-js. They only allow passing custom `className` prop or custom css via `style` prop. The css-in-js (eg. emotion) is impossible to be passed to Ant component. 

It's true emotion supports nest structure. But there is nowhere we can pass the emotion to. Only by applying global styles. If e.g. Modal accepted `css` prop same way it accepts `style` and `className`, then we could easily build our own custom css-in-js styles (even with nest selectors) and pass them to Modal root. 

Mantine supports this https://mantine.dev/styles/styles-api/

**Comment by alhawk** [comment]
@Kamahl19 , I also have the same issue with this. I plan to modify a certain style inside antd components since there are some adjustment we need to do.
