### ISSUE TITLE
webkitRelativePath is empty

### ISSUE THREAD

**Issue by chanh-eftax** [ant-design/ant-design#39786]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ovgequ)

### Steps to reproduce

- console.log(file) in beforeUpload
- check webkitRelativePath

### What is expected?

webkitRelativePath shows the file path

### What is actually happening?

webkitRelativePath shows nothing

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | NextJS |
| System | Ubuntu 20.04 LTS |
| Browser | Chrome |

---
This happens with both Antd 4.x and 5.x, with both Typescript and Javascript.
It can be reproduced with the sandbox links provided on Antd's webpage.

**Comment by chanh-eftax** [comment]
Can be reproduced on Firefox also.

**Comment by afc163** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath

> The File.webkitRelativePath is a read-only property that contains a string which specifies the file's path relative to the directory selected by the user in an [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element with its [webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-webkitdirectory) attribute set.
