### ISSUE TITLE
Menu实现一个四级菜单遇到问题

### ISSUE THREAD

**Issue by sjxhgjxf** [ant-design/ant-design#3978]
场景：用Meun组件想实现一个四级菜单
思路：前三级菜单最外层的Meun设置mode是inline，第四级菜单不想inline方式嵌入到第三级菜单下，考虑到避免嵌套过深，欲使第四级菜单相对第三级菜单是vertical mode显示
问题：无法通过在第三级SubMenu里再次嵌入Meun（该Menu设置mode为vertical）来实现
希望牛人支招！

**Comment by afc163** [comment]
目前不支持这种用法。
