### ISSUE TITLE
table 树型筛选菜单 选中颜色错误

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#39799]
### Reproduction link

https://ant.design/components/table-cn#components-table-demo-filter-in-tree

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3166799/209466192-c621a144-bcd1-4c78-8fd4-6ee609d950aa.png)

table 树型筛选菜单 选中颜色错误

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | React 18.2.0 |
| System | Windows |
| Browser | Chrome 103 |

**Comment by afc163** [comment]
<img width="328" alt="图片" src="https://user-images.githubusercontent.com/507615/209491227-8113cc3d-988f-4571-9173-c95e1d9e2df9.png">

Dropdown 的阴影也丢了。

**Comment by MadCcc** [comment]
Wrong usage of token.

**Comment by JarvisArt** [comment]
> Wrong usage of token.

+1
