### ISSUE TITLE
找不到如何透過設置主題來更改 code 的字體

### ISSUE THREAD

**Issue by bluelovers** [ant-design/ant-design#39790]
### Steps to reproduce

```
<Text code>Ant Design (code)</Text>
```

### What is expected?

控制 pre, code, kbd, samp 的預設字體 (不透過 !important)

### What is actually happening?

```
pre, code, kbd, samp {
	font-size: 1em;
	font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace;
}
```

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
@MadCcc another global className case.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/39327#issuecomment-1362483680

**Comment by MadCcc** [comment]
Maybe same resolution as `<a>` could help.
