### ISSUE TITLE
image组件预览大图在部分场景下关闭遮罩时会闪烁

### ISSUE THREAD

**Issue by choby** [ant-design/ant-design#39809]
### Reproduction link

[https://ant.design/components/image-cn](https://ant.design/components/image-cn)

### Steps to reproduce

首次打开官方实例“受控的预览”预览图后，点击遮罩层关闭预览弹窗，即出现预览弹窗关闭后闪烁的问题。
同样在我们的业务系统中，如果在弹窗中（其他地方打开预览没有该问题）打开一个图片的预览，点击遮罩关闭预览也会出现这个问题， 并且是必然复现。 

### What is expected?

正常关闭预览

### What is actually happening?

点击遮罩层关闭预览弹窗，即出现预览弹窗关闭后闪烁的问题

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | react |
| System | windows 11 |
| Browser | microsoft edge 108 |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/39054
