### ISSUE TITLE
Tabs 选中选项卡时tabs-bar没有动态计算宽度，只计算了第一次渲染宽度

### ISSUE THREAD

**Issue by 105197** [ant-design/ant-design#39810]
### Reproduction link

[https://ant.design/components/tabs-cn#tabs](https://ant.design/components/tabs-cn#tabs)

### Steps to reproduce

items：TabItemType[].其中label动态渲染

### What is expected?

 选中选项卡时tabs-bar动态计算宽度

### What is actually happening?

选中选项卡时tabs-bar没有动态计算宽度

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | react |
| System | Windows 10 |
| Browser | chrome 108 |

**Comment by candy4290** [comment]
好像和这个是同一个问题: #39536 @105197

**Comment by 105197** [comment]
![20221226140757](https://user-images.githubusercontent.com/44538190/209510121-e127d7c2-610b-471b-9e5f-349764e406fc.gif)

**Comment by 105197** [comment]
> 好像和这个是同一个问题: #39536 @105197

谢谢

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/tabs/pull/630 ，请重装 node_modules

**Comment by airfisher** [comment]
antd4.x 也有这个问题，请问又计划修复吗？

**Comment by afc163** [comment]
@airfisher 给个 4.x 的重现？
