### ISSUE TITLE
TreeSelect on Form stop working with DataNode type in v 5.1

### ISSUE THREAD

**Issue by hadarby** [ant-design/ant-design#39821]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-1-0-forked-izu8sz?file=/demo.tsx)

### Steps to reproduce

1.work with typescript
2. create form with TreeSelect with treeCheckable={true}
3. create treeData of type DataNode[] (DataNode doesn't except value field but TreeSelect needs it to work)
4.run
5. try to check a node
(same code works on v 4.x)

### What is expected?

node selected

### What is actually happening?

node not selected there is an type error - Cannot read properties of undefined (reading 'label')

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 108.0.5359.125 (Official Build) (64-bit) |

---
When I changed the type to any and can add value fields it working but on typescript I actually need the type

**Comment by zombieJ** [comment]
Its also not work on v4:
https://codesandbox.io/s/basic-usage-antd-5-1-0-forked-mdxgrw?file=/demo.tsx

**Comment by zombieJ** [comment]
`treeData` deps on `value` instead of `key`:
https://codesandbox.io/s/basic-usage-antd-5-1-0-forked-9r6qo8?file=/demo.tsx

**Comment by AshishKapoor** [comment]
Still facing the same problem on the latest release of Ant Design.
