### ISSUE TITLE
Tree showLine icon backgroundColor

### ISSUE THREAD

**Issue by 1pone** [ant-design/ant-design#39826]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-zhan-kai-zhe-die-tu-biao-antd-5-1-1-forked-neuv5t?file=/demo.tsx)

### Steps to reproduce

Tree组件showLine为true, 自定义设置Tree的backgroundColor

### What is expected?

下拉按钮和连接线icon backgroundColor 为 transparent, 参考showLine为false时的效果. 或者期望整个Tree组件的backgroundColor为transparent

### What is actually happening?

下拉按钮和连接线icon backgroundColor 受theme影响

<img width="533" alt="image" src="https://user-images.githubusercontent.com/54310591/209547352-31fe0a7b-9d59-431c-b5ae-6167da6b7c5d.png">

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | macOS 12.4 |
| Browser | 108.0.5359.98 |

**Comment by kiner-tang** [comment]
这个我看一下
