### ISSUE TITLE
New component - draggable ListView

### ISSUE THREAD

**Issue by MichaelSavin** [ant-design/ant-design#3982]
Could you add new component same as [list-view in ant.mobile](https://mobile.ant.design/components/list-view/) but with draggable feature like [here](https://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage)?

**Comment by luojian001** [comment]
Tag的关闭按钮不能使用回调函数？
我使用的场景是：我点了关闭按钮触发回调函数来选择是否关闭掉，但目前我一点就关闭掉了，onClose也一样

**Comment by yesmeck** [comment]
@luojian001 Please file a new issue.

**Comment by afc163** [comment]
You can use https://github.com/gaearon/react-dnd directly now.
