### ISSUE TITLE
Checkbox 为 disabled 状态的时候有概率不会触发 Popover 隐藏

### ISSUE THREAD

**Issue by duziten** [ant-design/ant-design#39822]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tmvu3n?file=/index.js)

### Steps to reproduce

checkbox disabled 很大概率不会触发隐藏popover

### What is expected?

无论checkbox状态都会触发隐藏popover

### What is actually happening?

checkbox disabled 不会触发隐藏popover

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 17.0.2 |
| System | Macos |
| Browser | Chrome 106.0.5249.119 |

![image](https://user-images.githubusercontent.com/29852019/209537635-02e41fc6-629a-4d13-820e-161881392aa3.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/7ca85ad11a20d8840b40cbb95ab3276cf2585c0a#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966R92 

这里在最新代码里改丢了。

**Comment by afc163** [comment]
哦原来在这里换了实现方式：https://github.com/ant-design/ant-design/pull/33772

**Comment by afc163** [comment]
但是 https://github.com/ant-design/ant-design/pull/33772/files#diff-16b999cfd2d209afbbdaa3f7c0af5adf1ca5ef514ceec7db9706e1496e3a66f1R125 这个迁移到 css-in-js 后丢了 https://github.com/ant-design/ant-design/blob/5ea90df382ec57f8c6262cc389eb629b9e77ea71/components/checkbox/style/index.tsx#L245-L249

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/a1f3f5593301a59e8cf1e0e55d8589791b3020f8/components/checkbox/style/index.tsx#L184 刚迁移过来是在的。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/989a27ada872e5119775651da2e735986abb1c60#diff-17c6a64972b945a29c5a53348d97412a776a8f23badd84a04280998c0f4c0462L184

这里移除的，需要 @zombieJ 看看为啥移除了，能否加回来。

**Comment by zombieJ** [comment]
看了一下应该是当时挪位置过去，可以加回来：
https://github.com/ant-design/ant-design/commit/5aa492338eea8ee36c612878b9605df4abccda08

**Comment by aojunhao123** [comment]
![Image](https://github.com/user-attachments/assets/37ee4f2a-3e86-491e-bb22-64a90ce571b8)

`pointer-events:"none"`导致了Tree的checkbox hover时指针样式不正确
