### ISSUE TITLE
Issue on global search input

### ISSUE THREAD

**Issue by Gnanakumar-MB** [ant-design/ant-design#39839]
### Reproduction link

[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce

1. Go to the Ant Design 5.1.1 landing page and where we can see the global search input.
2.  when I try to search for something by typing keys, the page crashes and throws an ''Uncaught DOMException" error in the console.

### What is expected?

Expecting result page of searched value.

### What is actually happening?

The page gets crashes while typing.

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | React 18 |
| System | windows 10 |
| Browser | Google Chrome Version 108.0.5359.125 |

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/209627881-9e023712-afe9-418a-bd0b-ce3407815a57.png">

Nothing happend in my machine, could you provide a screen record video?

**Comment by Gnanakumar-MB** [comment]
yes @afc163 Here, I attached the screen record video.

https://user-images.githubusercontent.com/68071704/209637951-662ec900-529a-42d9-9662-af820e224ed6.mp4

**Comment by afc163** [comment]
Please turn off Chrome auto translation: 
<img width="344" alt="图片" src="https://user-images.githubusercontent.com/507615/209643420-47c23e47-fc84-4fdf-802e-7f4036b4a323.png">

**Comment by Gnanakumar-MB** [comment]
@afc163 I must need an English translation.

**Comment by afc163** [comment]
You can change to English version.

<img width="292" alt="图片" src="https://user-images.githubusercontent.com/507615/209645387-c65686dc-ed61-4a5a-ba59-7e110db24032.png">

**Comment by Gnanakumar-MB** [comment]
@afc163 Got it. Thank you.
