### ISSUE TITLE
Modal的style.left不生效

### ISSUE THREAD

**Issue by jianhao2010303** [ant-design/ant-design#39833]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce

 <Modal title='20px to Top' style={{ top: clientY, left: clientX }} open={open} onOk={setOpen} onCancel={setOpen} mask={false}>
      <p>some contents...</p>
      <p>some contents...</p>
      <p>some contents...</p>
    </Modal>

### What is expected?

1. 可根据传入left位置生效。

### What is actually happening?

style.left无法根据传入位置生效。

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18 |
| System | win10 |
| Browser | chrome |

**Comment by kiner-tang** [comment]
试试在`wrapStyle`中设置看看

**Comment by jianhao2010303** [comment]
实现了， style={{ position: 'absolute', top: clientY + 'px', left: clientX + 'px' }} 增加了绝对定位。
