### ISSUE TITLE
StyleProvider     配置transform.  legacyLogicalPropertiesTransformer 后，Menu组件样式丢失

### ISSUE THREAD

**Issue by keyus** [ant-design/ant-design#39846]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/styleprovider-transformers-6zt0ri?file=/src/App.js)

### Steps to reproduce

import "./styles.css";
import { Menu } from "antd";
import {
  StyleProvider,
  legacyLogicalPropertiesTransformer
} from "@ant-design/cssinjs";

export default function App() {
  return (
    <StyleProvider
      hashPriority="high"
      transformers={[legacyLogicalPropertiesTransformer]}
    >
      <div className="App">
        <h1>Hello CodeSandbox</h1>
        <h2>Start editing to see some magic happen!</h2>
        <Menu
          theme="dark"
          items={[
            { label: "1", key: "1" },
            { label: "2", key: "2" }
          ]}
        />
      </div>
    </StyleProvider>
  );
}

### What is expected?

menu样式正常

### What is actually happening?

样式错误

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.0.2 |
| System | mac |
| Browser | chrome 108 |

**Comment by xiaofuliang** [comment]
@ant-design/cssinjs  1.3.1 是会有这样问题，menu组件选中效果的样式都没有了

**Comment by yoyo837** [comment]
和这个同一个问题吗? https://github.com/ant-design/cssinjs/issues/69

**Comment by xiaofuliang** [comment]
应该不是一个问题吧，这个问题是menu的样式直接是没有了的

**Comment by yoyo837** [comment]
开个issue吧
