### ISSUE TITLE
Tooltip 在右对齐div中错位

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#39843]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-1-1-forked-nfitrg)

### Steps to reproduce

当Button在右对齐div中，点击Button，例如“增加”，“存盘”的标签错位，还会出现双标签同屏，所有版本都存在此问题。

![Screenshot 2022-12-27 153726](https://user-images.githubusercontent.com/86905784/209631241-01096034-4835-40d7-a7a6-9b6ac0f292ef.png)

### What is expected?

错位

### What is actually happening?

不错位

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.0.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by afc163** [comment]
Duplicate of #33242

**Comment by afc163** [comment]
We should destroy tooltip when children is unmounted. @ant-design/ant-design-collaborators

**Comment by meseme** [comment]
> We should destroy tooltip when children is unmounted. @ant-design/ant-design-collaborators

好像还不太一样，那个“存盘”Button并没有unmouted，只是位置变动了

**Comment by crazyair** [comment]
map 需要加 key

**Comment by meseme** [comment]
> 
加上了，但除了没有error提示，并没有作用
![Screenshot 2022-12-27 200133](https://user-images.githubusercontent.com/86905784/209663918-74c4595c-82b3-4b4a-a158-144f4410367a.png)

**Comment by crazyair** [comment]
不加key会有同屏显示问题，加上就能解决

**Comment by meseme** [comment]
> 不加key会有同屏显示问题，加上就能解决
加上了，问题依旧
![Screenshot 2022-12-27 200503](https://user-images.githubusercontent.com/86905784/209664324-b0a94df8-a430-425a-8ada-35ca02b34da0.png)

**Comment by crazyair** [comment]
no no no
![image](https://user-images.githubusercontent.com/7971419/209664473-43def22f-b696-45d8-a857-796155a82e22.png)
这个是 index，你切换数据，这里还是从 0 开始

**Comment by meseme** [comment]
> no no no ![image](https://user-images.githubusercontent.com/7971419/209664473-43def22f-b696-45d8-a857-796155a82e22.png) 这个是 index，你切换数据，这里还是从 0 开始

问题解决，非常感谢
