### ISSUE TITLE
Table border transition style

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#39841]
<img width="1205" alt="图片" src="https://user-images.githubusercontent.com/507615/209494964-8d091220-3d96-4502-9b7c-4de72274108f.png">

这个会造成筛选表格时 border 的 transition 效果出现黑条。

_Originally posted by @afc163 in https://github.com/ant-design/ant-design/issues/39729#issuecomment-1364837469_

**Comment by afc163** [comment]
筛选表格时可重现。

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/39713
border 有 transition 就会有这种现象。。

**Comment by psxxj-cash** [comment]
I also have a same issue too.

**Comment by psxxj-cash** [comment]
This issue is not fixed fix for changing the pagination.
