### ISSUE TITLE
Visible tooltip's position is not updated as max is updated

### ISSUE THREAD

**Issue by serdaryesilmurat** [ant-design/ant-design#39850]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/js-antd-table-ordering-forked-wij8n0)

### Steps to reproduce

Slider tooltip position is not updated as "max" prop of slider increases.

### What is expected?

Slider tooltip should follow the updated slider handle.

### What is actually happening?

Slider tooltip stay still

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/js-antd-table-ordering-forked-pf4o3v?file=/App.js

This is the workaround.

**Comment by serdaryesilmurat** [comment]
> https://codesandbox.io/s/js-antd-table-ordering-forked-pf4o3v?file=/App.js
> 
> Here is the workaround.

Thx for the workaround. Works like a charm 😉
