### ISSUE TITLE
zhCN模式下，useApp 导出的 modal.confirm 默认的okText属性为"知道了"，而库导出的 Modal.confirm 默认的okText 属性值为"确定"

### ISSUE THREAD

**Issue by Huaxink** [ant-design/ant-design#39861]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sql9sb?file=/index.js)

### Steps to reproduce

```
import { App, Modal } from "antd";

const { modal } = App.useApp();
modal.confirm({ title: "确认模态框" });
Modal.confirm({ title: "确认模态框" });
```
确认按钮的问题不一样

### What is expected?

确认按钮的文字均为 "确定"

### What is actually happening?

useApp 导出的 modal.confirm 确认按钮文字为 "知道了"

库直接导出的 Modal.confirm 确认按钮文字为 "确定"

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | window10 |
| Browser | chrome |

---
ConfigProvider 的 locale={zhCN}

**Comment by BoyYangzai** [comment]
看了下源码，源代码中okText默认了两种
`okText || (mergedOkCancel ? mergedLocale?.okText : mergedLocale?.justOkText`
`okText` 是`确定`，`justOkText` 是`知道了`
应该是有意这样设计的

**Comment by sushi-su** [comment]
当然是个 BUG ，`知道了`应该是在没有取消按钮的情况下才会出现

**Comment by BoyYangzai** [comment]
> 当然是个 BUG ，`知道了`应该是在没有取消按钮的情况下才会出现

这样的话确实说得通了

**Comment by BoyYangzai** [comment]
@Huaxink @sushi-su 
我同步了一下modal组件中的逻辑，你们可以看一下
https://github.com/ant-design/ant-design/pull/39884
