### ISSUE TITLE
官方文档切换版本错误

### ISSUE THREAD

**Issue by jrr997** [ant-design/ant-design#39868]
### Reproduction link

[https://4x.ant.design/index-cn](https://4x.ant.design/index-cn)

### Steps to reproduce

1.打开v5官网https://ant.design/index-cn  右上角版本选择4.x
2.页面跳转到https://4x.ant.design/  右上角没有5.x的选项

### What is expected?

4.x的官网可以切换到5.x官网

### What is actually happening?

4.x的官网没有切换到5.x官网的选项

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18 |
| System | win10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
Close by #39872
