### ISSUE TITLE
Tag里只有空格的时候，样式错误

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [ant-design/ant-design#39863]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-1-1-forked-zq70fd)

### Steps to reproduce

打开重现链接即可

### What is expected?

我期望当 tag标签内是空格的时候， 样式也可以正常，因为我就是想要展示这种效果

![image](https://user-images.githubusercontent.com/104620424/209773277-e2361f20-250b-4397-a926-f9aba736e869.png)

虽然我可以用 `&nbsp;` 来暂时代替空格，但总觉得多了一个步骤

### What is actually happening?

当tag标签内是空格的时候， 只有一个横线了

![image](https://user-images.githubusercontent.com/104620424/209773407-2f20fd69-daae-49cc-96c5-bbc6562c673f.png)

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
浏览器 dom 树对于独立存在的空格或者连续空格不会当成正常空格字符来处理，除非标记 `white-space: pre;` 样式或用 `&nbsp;` 或其他空格字符来代替。antd 也不会做特殊处理。
