### ISSUE TITLE
datepicker和dateRangePicker能否修改为disabledTime时间段不可以翻页到且默认右侧是最后有效月份？

### ISSUE THREAD

**Issue by leejaen** [ant-design/ant-design#3987]
![image](https://cloud.githubusercontent.com/assets/1638970/20585425/0c51b724-b236-11e6-8b2e-deac05c143a2.png)
后面的disabledTime即使翻页到也操作不了，是不是有些多余？直接显示成这样是不是更好：
![image](https://cloud.githubusercontent.com/assets/1638970/20585507/a5e7f650-b236-11e6-8419-66621cf067f7.png)

**Comment by benjycui** [comment]
最多给翻页按钮加 `disabled` 属性。

`disableDate` 是一个函数，不排除只 disable 一段时间的情况。

**Comment by benjycui** [comment]
但感觉这个交互优化提升不大、、

**Comment by afc163** [comment]
这样不好的，翻页和选择行为是分开的，还是保持交互的一致性比较好。

**Comment by leejaen** [comment]
确实我忽略掉了某一段时间disabled的情况……
