### ISSUE TITLE
FloatButton 设置stlye属性 top:200 , 按钮样式错误

### ISSUE THREAD

**Issue by ZerosLifeCycle** [ant-design/ant-design#39873]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-torvalds-tlhogu?file=/index.js)

### Steps to reproduce

<FloatButton
      style={{right: 80, top: 200}}
      icon={<SearchOutlined/>}
      type={"primary"}
      shape={"square"}
      onClick={() => {}}
    />

### What is expected?

按钮为 方形

### What is actually happening?

按钮过高，显示为长方形

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | chrome 108.0.5359.125 |

**Comment by MadCcc** [comment]
原先有 bottom 定位，加上 `bottom: unset` 就可以
