### ISSUE TITLE
Next.js无法在服务器发出HTML时渲染style标签

### ISSUE THREAD

**Issue by Lrunlin** [ant-design/ant-design#39885]
### Reproduction link

[https://ant-design.github.io/cssinjs/demo/ssr-advanced](https://ant-design.github.io/cssinjs/demo/ssr-advanced)

### Steps to reproduce

https://ant-design.github.io/cssinjs/demo/ssr-advanced

### What is expected?

在服务器发出HTML字符串时已经添加了style标签

### What is actually happening?

style标签只在浏览器渲染

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2 |
| System | next.js13 |
| Browser | Chrome100 |

**Comment by Lrunlin** [comment]
请问是否只能向[#服务端渲染](https://ant-design.antgroup.com/docs/react/customize-theme-cn#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%B8%B2%E6%9F%93)这样在document中手动处理呢？

**Comment by Lrunlin** [comment]
![image](https://user-images.githubusercontent.com/54397964/209906949-123d1edd-94f8-474f-a0a8-5cd1b702a7c8.png)

目前是使用这种方法进行解决的

**Comment by MadCcc** [comment]
不太明白你的意思。SSR 渲染 style 标签可能会导致 html 体积过大以及其他问题，推荐还是将样式 extract 出去。

**Comment by Lrunlin** [comment]
> 不太明白你的意思。SSR 渲染 style 标签可能会导致 html 体积过大以及其他问题，推荐还是将样式 extract 出去。如果有问题请提供复现

类styled-jsx那种，在HTML中携带style，这样不会倒是CSS加载慢而出现的闪屏

**Comment by Lrunlin** [comment]
![image](https://user-images.githubusercontent.com/54397964/209922531-673eaf8b-855b-4e88-b3d8-fd4ab5f01c6c.png)
![image](https://user-images.githubusercontent.com/54397964/209922560-8b4f4029-1662-46c2-a333-432ad147931d.png)

如果通过JS来设置style标签，那么下载、解析JS期间会出现DOM的样式没有加载出来的情况

**Comment by IonelLupu** [comment]
I noticed the same problem with Next.js and AntDesign.

I created a more detailed issue here: https://github.com/ant-design/ant-design/issues/39891

**Comment by afc163** [comment]
可以合并到 #39891 里讨论。
