### ISSUE TITLE
cssinjs1.3.1   StyleProvider配置hashPriority='high'。同时配置. transformers. legacyLogicalPropertiesTransformer后，:where选择器降级失败

### ISSUE THREAD

**Issue by keyus** [ant-design/ant-design#39882]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-einstein-6zt0ri?file=/src/App.js)

### Steps to reproduce

<StyleProvider
                hashPriority='high'
                transformers={[legacyLogicalPropertiesTransformer]}
            >
      <App />
</StyleProvider>

### What is expected?

:where选择器成功降级

### What is actually happening?

依然是:where()

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.0.2 |
| System | mac |
| Browser | chrome 108 |

**Comment by yoyo837** [comment]
可能有关的 #39881
