### ISSUE TITLE
StyleProvider 配置了legacyLogicalPropertiesTransformer Menu组件的选中效果样式丢失

### ISSUE THREAD

**Issue by xiaofuliang** [ant-design/ant-design#39881]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-erny9v?file=/index.js:1322-1373)

### Steps to reproduce

设置了legacyLogicalPropertiesTransformer就会出现

### What is expected?

样式正常

### What is actually happening?

样式丢失

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.3 |
| System | window10 |
| Browser | chrome 108.0.5359.125 |

**Comment by yoyo837** [comment]
ref: #39846

**Comment by afc163** [comment]
StyleProvider 应该合并到 ConfigProvider 里，统一配置入口。

**Comment by zombieJ** [comment]
> StyleProvider 应该合并到 ConfigProvider 里，统一配置入口。 @zombieJ

这样就把 cssinjs 的库配置耦合进来了，如果未来添加其他的 transformer，antd 就要把这些 transformer 一起打包进来。否则用户也会奇怪为什么 antd 的 ConfigProvider 要用三方包的方法。
