### ISSUE TITLE
表头分组和固定列同时使用时，表格最右侧会产生裂缝

### ISSUE THREAD

**Issue by hxguo** [ant-design/ant-design#39880]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-resonance-95ii7y?file=/src/App.tsx)

### Steps to reproduce

```
const columns: ColumnsType<User> = [
  {
    title: "父表头右侧的阴影导致整个表格最右侧有空隙",
    children: [
      {
        key: "name",
        title: "Name",
        fixed: "left",
        dataIndex: "name"
      },
      {
        key: "name",
        title: "Name",
        fixed: "left",
        dataIndex: "name"
      },
      {
        key: "name",
        title: "Name",
        dataIndex: "name"
      },
      {
        key: "name",
        title: "Name",
        fixed: "right",
        dataIndex: "name"
      }
    ]
  }
];

const data: User[] = [
  {
    key: 0,
    name: "Jack"
  },
  {
    key: 1,
    name: "Jack1"
  },
  {
    key: 2,
    name: "Jack1"
  }
];

export default function App() {
  return (
    <div className="App" style={{ padding: 24 }}>
      <Table<User>
        columns={columns}
        dataSource={data}
        rowSelection={{ fixed: true }}
        scroll={{ x: true }}
      />
    </div>
  );
}
```

### What is expected?

正常情况下，表格个右侧应该没有多出的空隙

### What is actually happening?

整个表格的最右侧有一个空隙。

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | react |
| System | 所有 |
| Browser | 所有 |

---
产生该空隙的原因是父表头的右侧有固定列阴影，导致整个表格的最右侧有空隙。
![image](https://user-images.githubusercontent.com/9603098/209894051-663217c2-26a5-492c-9fa8-eaa5d622f678.png)

**Comment by kiner-tang** [comment]
还有一个问题，就是选择列的`zIndex`太低会导致滚动是被其他元素挡住
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/10286961/210128831-9789010d-5d68-4d08-91ea-32e3399e3df4.png">
