### ISSUE TITLE
Collapse 不能设置宽度吗?

### ISSUE THREAD

**Issue by Vsion** [ant-design/ant-design#3988]
![image](https://cloud.githubusercontent.com/assets/11804448/20585716/38b719ec-b238-11e6-8a1b-9cd34521e410.png)

![image](https://cloud.githubusercontent.com/assets/11804448/20585731/522c18d2-b238-11e6-85a2-329cd7975896.png)

**Comment by afc163** [comment]
fixed in https://github.com/react-component/collapse/commit/6549e1aa0fddb2e47a11b14b877363e8faacb9c8

尝试重装 antd 最新版本。

**Comment by afc163** [comment]
报告问题最好按格式来，提供标准的信息。

**Comment by Vsion** [comment]
ok
