### ISSUE TITLE
refactor Affix to function component

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#39892]
https://github.com/ant-design/ant-design/blob/dc77959e7ced3f0ae393116e2f3d18cf9b3e0f14/components/affix/index.tsx#L57

**Comment by anjantalatam** [comment]
@afc163 I can start with Affix refactor if no one is working on it.

**Comment by SnowingFox** [comment]
> @afc163 I can start with Affix refactor if no one is working on it.

yeah, you can try it, i have no idea to `removeObserveTarget` `addObserveTarget`

**Comment by ZWkang** [comment]
@afc163 @SnowingFox  anyone still working on this? can i try to refactor it?

**Comment by SnowingFox** [comment]
> @afc163 @SnowingFox anyone still working on this? can i try to refactor it?

No, my pr was closed.

**Comment by yoyo837** [comment]
> No, my pr was closed.

If you want pick it up and finish it again, you can open a new one.

**Comment by SnowingFox** [comment]
> > No, my pr was closed.
> 
> If you want pick it up and finish it again, you can open a new one.

In fact, i tried to refacotr it, but there still has some problems i can't resolve, like i mentioned https://github.com/ant-design/ant-design/issues/39892#issuecomment-1376610243

**Comment by ZWkang** [comment]
do you want to finish it? or maybe i can just work in your branch and maybe we can resolve it together? @SnowingFox

**Comment by SnowingFox** [comment]
> do you want to finish it? or maybe i can just work in your branch and maybe we can resolve it together? @SnowingFox

Sure, I'm very welcome

**Comment by afc163** [comment]
这个事好像还没人领。

**Comment by ZWkang** [comment]
@afc163 申请我来做这个
