### ISSUE TITLE
Next.js fails to render style tags when server emits HTML

### ISSUE THREAD

**Issue by IonelLupu** [ant-design/ant-design#39891]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/eager-shirley-k0zlcq?file=%2FREADME.md)

### Steps to reproduce

1. Create a new Next.js 13 app with the "app" directory feature:
```
npx create-next-app@latest --experimental-app
# or
yarn create next-app --experimental-app
# or
pnpm create next-app --experimental-app
```

2. Add ant design to the project
3. Add a few random components in the "app/page.tsx" file. Don't forget to add "use client" at the top of the file
4. Run the "dev" script and open the browser at the specified port
5. Observe how the page loads without styles for a brief second. After a few moments, the styles get downloaded.

I noticed this issue was introduced with @ant-design/cssinjs v1.3.1. Here is a [reproduction link](https://codesandbox.io/p/sandbox/purple-sun-8o8z8e?file=%2FREADME.md) where I modified the yarn.lock file to load an older version on cssinjs (v.1.1.0) where everything loads ok.

Here are also some videos to see how it looks like.  Pay attention at the reload button to see when I refresh the page:

Before (using a yarn.lock file that requires cssinjss v.1.1.0):

https://user-images.githubusercontent.com/4083652/209926786-2127bca0-6708-44d0-b962-166807bcc718.mov

After (using the latest version of AntDesign which comes with cssinjs v.1.3.1):

https://user-images.githubusercontent.com/4083652/209926824-ecdb3f27-f805-48fa-97c4-72b6e6dfe468.mov

Other mentions of the issue:
- https://github.com/ant-design/ant-design/issues/39885
- https://github.com/ant-design/cssinjs/issues/69#issuecomment-1367104002

### What is expected?

The styles to be loaded together with the HTML as before

### What is actually happening?

The styles are loaded after the page loads the HTML

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | MacOS Ventura 13.0.1 |
| Browser | Chrome 108 |

**Comment by Lrunlin** [comment]
![image](https://user-images.githubusercontent.com/54397964/209930759-82d0050a-4461-4978-abc2-29e98151f280.png)
我想要使用这个方法来解决，但是他好像只能运行在可以使用router的组件中。目前还没有找到好的使用的方法。也许可以将`<StyleProvider cache={cache}>`中包裹的<Component/>组件进行更换，但是现在没有发现任何好的方法

**Comment by ptvinhdtk** [comment]
install version antd@5.0.0 without this error

**Comment by IonelLupu** [comment]
> install version antd@5.0.0 without this error

This is not possible because our project is using the `App` component which was released in v5.1.0

**Comment by Lrunlin** [comment]
> > install version antd@5.0.0 without this error
> 
> This is not possible because our project is using the `App` component which was released in v5.1.0


我将antd的版本下调到了5.0.0，有趣的是的确如他所说。

**Comment by Lrunlin** [comment]
> > install version antd@5.0.0 without this error
> 
> This is not possible because our project is using the `App` component which was released in v5.1.0

![image](https://user-images.githubusercontent.com/54397964/210164420-5d432797-f183-43c4-8f71-b26c0f25f3cc.png)
![image](https://user-images.githubusercontent.com/54397964/210164425-01963c28-cc46-4552-99fa-687ee4d3fdc0.png)

**Comment by Lrunlin** [comment]
Maybe it was an error made by antd during the upgrade

**Comment by IonelLupu** [comment]
Ant Design v5.0.0 has the `cssinjs` v1.1.0 package which does't have the issue we reported. The issue is there starting with Ant Design v5.1.0.

But, you will get into theming problems with v5.0.0. For example, try and change the primary color and then create a modal. You will notice the modal not having the primary color you've chosen. To fix this issue, AntDesign v5.1.0 added the `App` component which  allowed you to create a modal that has the theme colors configured by you.

>  Maybe it was an error made by antd during the upgrade
I think so too.

**Comment by Lrunlin** [comment]
> Ant Design v5.0.0 包含`cssinjs`v1.1.0 包，它没有我们报告的问题。这个问题是从 Ant Design v5.1.0 开始的。
> 
> 但是，您将遇到 v5.0.0 的主题问题。例如，尝试更改原色，然后创建模态。您会注意到模式没有您选择的原色。为了解决这个问题，AntDesign v5.1.0 添加了一个`App`组件，允许您创建一个具有您配置的主题颜色的模式。
> 
> > 可能是升级的时候antd出错了
> > 我也这么觉得。

也许，输出style标签和使用主题颜色两个功能，我们暂时只能二选一，等待团队修复这个BUG

Maybe we can only choose one of the two functions of outputting style tags and using theme colors for the time being, waiting for the team to fix the bug

**Comment by mghizzo** [comment]
Check this issue: https://github.com/vercel/next.js/issues/44125

This is how you should do it inside the main layout.
![Screenshot 2023-01-03 alle 12 37 37](https://user-images.githubusercontent.com/29211226/210350079-3fb2c8ab-91a4-4c9c-8913-c4c750381388.png)

Note that ConfigProviderLayout is something inside my project so it may just be <>children</> in your case

Then like in the issue mentioned above, nextjs currently has a bug which will ignore useServerInsertedHTML without a head tag somewhere, so make sure to include also that inside your rootlayout.
![Screenshot 2023-01-03 alle 12 39 42](https://user-images.githubusercontent.com/29211226/210350445-6424661b-4fc1-4c34-a780-a6414f219929.png)

**Comment by williamstein** [comment]
For people like me wondering what createCache and extractStyle are in @mghizzo 's helpful comment, they are from cssinjs.  See https://github.com/ant-design/ant-design/issues/38767#issuecomment-1350362026

**Comment by IonelLupu** [comment]
@mghizzo  What is `parse`? I tried implementing your solution (without the `parse` function) and now I get errors like:
 ```
- Expected server HTML to contain a matching <div> in <body>.
- Hydration failed because the initial UI does not match what was rendered on the server.
- An error occurred during hydration. The server HTML was replaced with client content in <#document>.
```

Also, the page shows the styles as text on the page. Here is a link: https://codesandbox.io/p/sandbox/busy-feather-vh5bii

**Comment by mghizzo** [comment]
> @mghizzo What is `parse`? I tried implementing your solution (without the `parse` function) and now I get errors like:
> 
> ```
> - Expected server HTML to contain a matching <div> in <body>.
> - Hydration failed because the initial UI does not match what was rendered on the server.
> - An error occurred during hydration. The server HTML was replaced with client content in <#document>.
> ```
> 
> Also, the page shows the styles as text on the page. Here is a link: https://codesandbox.io/p/sandbox/busy-feather-vh5bii

Check my solution [here](https://github.com/vercel/next.js/issues/44125#issuecomment-1372270391)

**Comment by IonelLupu** [comment]
@mghizzo That did 🥳  🚀 (almost). I had to install the `html-react-parser` package. 

But, it almost did it 😭. I am using TailwindCSS in my project on top of AntDesign. It's easier than writing my own CSS classes. Before implementing your solution, Tailwind classes were added on top of the AntDesign classes (meaning AntDesign classes were less specific than Tailwind classes). Now, Tailwind classes are just ignored because the AntDesign classes are more specific for some reason. The only solution I found for this is to use the `!` character to make Tailwind classes `!important`. Any other ideas?

**Comment by mghizzo** [comment]
> @mghizzo That did 🥳 🚀 (almost). I had to install the `html-react-parser` package.
> 
> But, it almost did it 😭. I am using TailwindCSS in my project on top of AntDesign. It's easier than writing my own CSS classes. Before implementing your solution, Tailwind classes were added on top of the AntDesign classes (meaning AntDesign classes were less specific than Tailwind classes). Now, Tailwind classes are just ignored because the AntDesign classes are more specific for some reason. The only solution I found for this is to use the `!` character to make Tailwind classes `!important`. But I have thousands of these in my app. Any other ideas?

Glad to hear that it works, took me about 8hrs to figure that out. 
Btw I just updated the solution in the other issue if you want to check it out I found a workaround made by someone which doesn't require html-react-parser. I'm using tailwind css too in my projects and since I use it only for things which don't need to follow ant design rules I always set `important: true` in `tailwind.config.js`

**Comment by MarkLyck** [comment]
This also seems to affect projects NOT using the app directory. I'm only using the normal pages directory and this is happening to me as well.

I spent hours debugging why my NextJS app had a flash of unstyled content with antd, until I found this thread. I downgraded to 5.0.0 and the FOUC is fixed 👍 (but of course I don't want to be stuck on this version forever either).

**Comment by IonelLupu** [comment]
@MarkLyck  Check the solution in the link posted by @mghizzo. It should work on the latest version of Ant Design:
> Check my solution https://github.com/vercel/next.js/issues/44125#issuecomment-1372270391

**Comment by MarkLyck** [comment]
> vercel/next.js#44125 (comment)

Yeah I saw this, but that solution is for the app directory layouts, which I'm not using. I tried putting it in `_document.tsx` in `getInitialProps` but couldn't get that working. But I don't think I use any features from 5.1.0 so for me, downgrading to 5.0.0 until this is fixed is an okay solution.

**Comment by williamstein** [comment]
For what it is worth, this is my production _document.tsx file that is working correctly for https://cocalc.com right now, to workaround this problem:  https://github.com/sagemathinc/cocalc/blob/master/src/packages/next/pages/_document.tsx
I'm currently still stuck on nextjs v 12.x, so had to use _document.tsx. 

Something that caused me a lot of confusion regarding all of this is that I was importing the wrong copy of "@ant-design/cssinjs".  There's a version of that package that antd uses, but it's possibly not exposed, so you have to also install it, and you could end up with a slightly different version; then everything you're doing in _document.tsx will fail, since it's using the wrong state.  This might have been more of an issue for me, since I'm using pnpm, which is very conservative about exposing package versions.

I'm really looking forward to this somehow getting properly fixed.  I can see how it will be difficult, since it seems to be simultaneously neither antd's nor next.js's "responsibility" to fix.  All that said, it's very nice that antd v5 doesn't use separate css anymore, since trying to deal with the very large css that resulted via various hacks wasn't fun either.

For me personally, explicitly exposing the cssinjs that antd is using would help, e.g., instead of
```ts
import { createCache, extractStyle, StyleProvider } from "@ant-design/cssinjs";
```
I would much prefer to be able to do
```ts
import { cssinjs } from "antd";
```

Without that, I have to use hoisting rules to pnpm to ensure I get the same copy of @ant-design/cssinjs as antd is using.  Of the "bazillion" packages in my massive webapp, this is the only one that requires any hoisting rules.

**Comment by DophinL** [comment]
i met same problem when using next@13, please solve this bug

**Comment by mghizzo** [comment]
> i met same problem when using next@13, please solve this bug

There is the solution in the comments, please read carefully.

**Comment by EdgarKisman** [comment]
I checked the versions, and it looks like the first time this behavior appears is with v.5.0.1

**Comment by tugayevci** [comment]
"antd": "^5.2.0",
"next": "13.1.6"

same issue, any update?

**Comment by Lrunlin** [comment]
> 

I didn't try. I thought that outputting HTML to style would result in huge output content on the server side, so I chose antd4. If you let cssinjs run in the browser, it will cause a very bad user experience

我没有进行尝试，我认为将HTML输出到style中会导致服务端输出内容体积庞大，所以选择了antd4。如果让cssinjs在浏览器运行会造成很不好的用户体验

**Comment by chunsch** [comment]
Hello everyone, I have submitted a PR to next.js before, and the following code has been added:

https://github.com/vercel/next.js/pull/44015

1. add app dir demo
2. extract styles, avoid no style when the page is loaded, or the generated page size is too large

I hope it will be helpful to everyone : D

**Comment by IonelLupu** [comment]
hey @chunsch  Thant's incredible. thanks. 

What do you mean by "or the generated page size is too large"? Is the fix suggested above (which I also use in Next.js 13) making the page too large? I see your PR is doing pretty much the same thing so I am not sure where is the page getting too big 🤔

**Comment by Lrunlin** [comment]
> 嘿@chunsch 那太不可思议了。谢谢。
> 
> “或生成的页面大小太大”是什么意思？上面建议的修复（我也在 Next.js 13 中使用）是否使页面太大？我看到您的 PR 正在做几乎相同的事情，所以我不确定页面在哪里变得太大🤔

Perhaps the<style>is generated in HTML, so the website cannot use CDN. And cause the file loaded for the first time to be too large

**Comment by chunsch** [comment]
@IonelLupu @Lrunlin In the early version of antd v5.0, the extraction style is not set, and the style will be generated repeatedly, causing this problem. eg: https://github.com/ant-design/ant-design/issues/38767 https://github.com/ant-design/ant-design/issues/39418

**Comment by marvinscheffold** [comment]
Thanks for the info about Ant Design v5.0.0. 
 I changed to that version and now it works without FOUC. 
 
 For me it didn't mean any drawbacks though, so I understand the concern some of you have.

**Comment by hongfaqiu** [comment]
I spent a long time trying to deal with the conflict between nextjs13 and antd5, finally, they can work together. And then, I added tailwindcss and dark theme support. I created a template for this: [Next.js13 app dir with Antd 5 & tailwindcss](https://github.com/hongfaqiu/nextjs13-with-antd-tailwindcss)
The whole process is painful, and after I finished my work, I found that the size of the document sent by the server was ten times larger than that of the scheme without using css-in-js, lighthouse also prompts the page to lack " HTML DOCTYPE".

On the whole, I decided to give up letting antd5 and nextjs13 work together.

我花了很长时间试图处理nextjs13和antd5之间的冲突，最终，它们可以一起工作。然后，我添加了tailwindcss和深色主题支持。我为此创建了一个模板：[Next.js13 app-dir with Antd 5&tailwindcss](https://github.com/hongfaqiu/nextjs13-with-antd-tailwindcss)

整个过程是痛苦的，在我完成工作后，我发现服务器发送的document的大小比不使用css-in-js方案时大了近十倍(8kb - 40kb)，lighthouse还提示页面缺少 HTML DOCTYPE。

总的来说，我决定放弃让antd5和nextjs13一起工作。

**Comment by Lrunlin** [comment]
> I spent a long time trying to deal with the conflict between nextjs13 and antd5, finally, they can work together. And then, I added tailwindcss and dark theme support. I created a template for this: [Next.js13 app dir with Antd 5 & tailwindcss](https://github.com/hongfaqiu/nextjs13-with-antd-tailwindcss) The whole process is painful, and after I finished my work, I found that the size of the document sent by the server was ten times larger than that of the scheme without using css-in-js, lighthouse also prompts the page to lack " HTML DOCTYPE".
> 
> On the whole, I decided to give up letting antd5 and nextjs13 work together.
> 
> 我花了很长时间试图处理nextjs13和antd5之间的冲突，最终，它们可以一起工作。然后，我添加了tailwindcss和深色主题支持。我为此创建了一个模板：[Next.js13 app-dir with Antd 5&tailwindcss](https://github.com/hongfaqiu/nextjs13-with-antd-tailwindcss)
> 
> 整个过程是痛苦的，在我完成工作后，我发现服务器发送的document的大小比不使用css-in-js方案时大了近十倍(8kb - 40kb)，lighthouse还提示页面缺少 HTML DOCTYPE。
> 
> 总的来说，我决定放弃让antd5和nextjs13一起工作。

Exactly speaking, the combination of css-in-js component library and SSR is not very good. It will cause HTML output miracle to be too large

准确来说 css-in-js的组件库搭配SSR，并不是很好的组合，他会导致HTML的输出奇迹过大

**Comment by Lrunlin** [comment]
> @Lrunlin 为了获得最佳性能，只能自己写组件了，所幸tailwind社区的组件也很多，相对来说antd很适合业务密集、表单多的中后台场景。

可以推荐一个tailwind的组件库嘛，除了官方那个

**Comment by hongfaqiu** [comment]
@Lrunlin 我最近也在找tailwind的组件库，表单逻辑等内容还是需要自己实现，工作量也不小。我这里推荐几个比较好的仓库，欢迎补充。

- [headlessui](https://github.com/tailwindlabs/headlessui) 官方的组件，样式非常漂亮，但是组件很少
- [material-tailwind](https://github.com/creativetimofficial/material-tailwind) tailwind版的MUI，很漂亮，缺少Table等重型组件
- [shadcn/ui](https://github.com/shadcn/ui) 个人维护的组件库，前景很好，样式也很漂亮，就是popover出现后没法滚动的机制不太友好
- [daisyUI](https://github.com/saadeghi/daisyui) 老牌组件库了，个人觉得样式上不是很美观
- [Tailwind-Elements](https://github.com/mdbootstrap/Tailwind-Elements) 大而全的tailwind组件库，风格偏向以前的MUI

**Comment by Lrunlin** [comment]
> @Lrunlin 我最近也在找tailwind的组件库，更应该说是模板库，表单逻辑组件封装等内容还是需要自己实现，工作量也不小。我这里推荐几个比较好的仓库，欢迎补充。
> 
> * [flowbite](https://github.com/themesberg/flowbite) 很完善的组件库，基本都覆盖了
> * [headlessui](https://github.com/tailwindlabs/headlessui) 官方的组件，样式非常漂亮，但是组件很少
> * [material-tailwind](https://github.com/creativetimofficial/material-tailwind) tailwind版的MUI，很漂亮
> * [shadcn/ui](https://github.com/shadcn/ui) 个人维护的组件库，前景很好，样式也很漂亮，就是popover出现后没法滚动的机制不太友好
> * [daisyUI](https://github.com/saadeghi/daisyui) 老牌组件库了，个人觉得样式上不是很美观
> * [Tailwind-Elements](https://github.com/mdbootstrap/Tailwind-Elements) 大而全的tailwind组件库，风格偏向以前的MUI

谢谢

**Comment by zombieJ** [comment]
最近会更新一下文档，提供一个模板出来，抱歉让大家体验不好了。

We'll update doc recently to provide template for this. Sorry for bad experience.

**Comment by Yuvalz19500** [comment]
This issue happens to me on Nextjs 13.2.3 and antd 5.2.3. I'm not using the app dir for nextjs I'm using the pages dir. Anyone happend to fix this issue ?

**Comment by atom-shanghai** [comment]
> 最近会更新一下文档，提供一个模板出来，抱歉让大家体验不好了。
> 
> We'll update doc recently to provide template for this. Sorry for bad experience.

期待

**Comment by zombieJ** [comment]
Update:
RFC [#40985](https://github.com/ant-design/ant-design/discussions/40985) passed. Will enter the development process.

**Comment by DicksonPunTS** [comment]
does anyone encounter the same issue for antd layout? even implement the solution above

**Comment by qinzehua** [comment]
> 

That is because antd apply some css to layout component after page loaded.

**Comment by qinzehua** [comment]
> does anyone encounter the same issue for antd layout? even implement the solution above


That is because antd apply some css to layout component after page loaded.

**Comment by Shotteammate** [comment]
> > does anyone encounter the same issue for antd layout? even implement the solution above
> 
> 
> 
> 
> 
> That is because antd apply some css to layout component after page loaded.
> 
> 
> 
> 

Is there any solution for handling that case?

**Comment by bombillazo** [comment]
So finally, what is the recommended path to get `antd` working with SSR on Next.js 13, either for the`app` directory or classic mode?

**Comment by bombillazo** [comment]
> For what it is worth, this is my production _document.tsx file that is working correctly for https://cocalc.com right now, to workaround this problem: https://github.com/sagemathinc/cocalc/blob/master/src/packages/next/pages/_document.tsx I'm currently still stuck on nextjs v 12.x, so had to use _document.tsx.

@williamstein Thanks for sharing this, is _almost_ worked for me completely. I am using Ant Desing Pro Components and I am having trouble styling them. Is there something that should be doing to ensure that I extract styles related to these components? Pro Components uses its own ProConfigProvider so not sure if this helps.

**Comment by nhatpdXkalapa** [comment]
Anyone can provide solution for Ant Design Vue. Much appreciated.

**Comment by Zeng95** [comment]
> does anyone encounter the same issue for antd layout? even implement the solution above

I'm having the same problem

**Comment by Zeng95** [comment]
> does anyone encounter the same issue for antd layout? even implement the solution above

I got my problem fixed

**Comment by Shotteammate** [comment]
> > does anyone encounter the same issue for antd layout? even implement the solution above
> 
> I got my problem fixed

how do you fixed the antd layout issue?

**Comment by Zeng95** [comment]
> > > does anyone encounter the same issue for antd layout? even implement the solution above
> > 
> > 
> > I got my problem fixed
> 
> how do you fixed the antd layout issue?

What is your problem exactly?
My problem is just a CSS issue and I'm using [Sider](https://ant.design/components/layout#components-layout-demo-side)

**Comment by novarca-suzuki** [comment]
@Zeng95 I'm faced with Sider issue now. I want to know how you fixed the problem.

**Comment by IonelLupu** [comment]
@zineanteoh  what do you mean by "whole export"?

Also, does it work with NextJS's new app directory?

**Comment by tannguyenthanhreiq** [comment]
How

> Finally got it to work! 👍 I followed [the instructions here](https://ant.design/docs/react/customize-theme#server-side-render-ssr) and used [this repo](https://github.com/ant-design/create-next-app-antd) as an example reference.
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/58854510/242036282-82cd3da0-8903-4984-90e0-ed3074b89884.png">
> ## Steps ('Whole export'):
> 
>     1. Install dependencies
> 
> 
> ```
> npm install ts-node tslib cross-env --save-dev
> npm install @ant-design/static-style-extract
> ```
> 
>     2. Create the following file `tsconfig.node.json`
> 
> 
> ```
> {
>   "compilerOptions": {
>     "strictNullChecks": true,
>     "module": "NodeNext",
>     "jsx": "react",
>     "esModuleInterop": true
>   },
>   "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
> }
> ```
> 
>     3. Create the following file `scripts/genAntdCss.tsx`
> 
> 
> If you are using Antd with default theme, then make sure you use the first option. Otherwise, if you are using custom theme, use the second option (see how `withTheme` is [implemented here](https://github.com/ant-design/create-next-app-antd/blob/main/theme/index.tsx)). Finally, [read more here](https://ant.design/docs/react/customize-theme#whole-export) if you are using mixed/multiple themes
> 
> ```tsx
> // Script to make SSR work with Antd + Next.js 13
> // This will generate a full antd.min.css file directly in the specified directory (e.g. ./public)
> // Source: https://github.com/ant-design/create-next-app-antd
> import fs from 'fs';
> import { extractStyle } from '@ant-design/static-style-extract';
> import withTheme from '../theme/index';
> 
> const outputPath = './public/antd.min.css';
> 
> // 1. default theme
> 
> // const css = extractStyle();
> 
> // 2. With custom theme
> 
> const css = extractStyle(withTheme);
> 
> fs.writeFileSync(outputPath, css);
> 
> console.log(`🎉 Antd CSS generated at ${outputPath}`);
> ```
> 
>     7. We then need to modify `package.json` to automatically execute this script `genAntdCss.tsx` whenever we run/build our app.
> 
> 
> ```
> // package.json
> {
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start",
>     "lint": "next lint",
>     "predev": "ts-node --project ./tsconfig.node.json ./scripts/genAntdCss.tsx",
>     "prebuild": "cross-env NODE_ENV=production ts-node --project ./tsconfig.node.json ./scripts/genAntdCss.tsx"
>   }
> }
> ```
> 
>     8. Finally, make sure we import the generated css within our `pages/_app.tsx`:
> 
> 
> ```tsx
> import { StyleProvider } from '@ant-design/cssinjs';
> import type { AppProps } from 'next/app';
> import '../public/antd.min.css';
> import '../styles/globals.css'; // add this line
> 
> export default function App({ Component, pageProps }: AppProps) {
>   return (
>     <StyleProvider hashPriority="high">
>       <Component {...pageProps} />
>     </StyleProvider>
>   );
> }
> ```
How I can archive this without using typescript, I'm using javascript and a customized theme. But seem like the file doesn't recognize scss and jsx when running predev: "node..."

**Comment by mvshvets** [comment]
> @zineanteoh what do you mean by "whole export"?
> 
> Also, does it work with NextJS's new app directory?


The method does not work with the new app directory. Tested on next@13.4.9

**Comment by leineveber** [comment]
"Whole export" methods doesn't work for me. Only "inline mode" and "export css files on demand" work just fine, but I cannot find how to pass custom theme, looks like these methods work with default antd theme only

**Comment by IonelLupu** [comment]
@mvshvets  can you provide some repro links and error messages?

**Comment by mvshvets** [comment]
> @mvshvets can you provide some repro links and error messages?

There are no errors. There is a problem with styles when updating the site page. This is observed when using the app directory

https://github.com/mvshvets/nextjs-antd


https://github.com/ant-design/ant-design/assets/46225129/e59b14cd-5379-4c13-8abf-877db80f8340

**Comment by monolithed** [comment]
@mvshvets, you forgot to add the following line`import '../public/antd.min.css';`
There'a an alternative way as well:

```tsx
'use client'

import React, {useState} from 'react';
import {useServerInsertedHTML} from 'next/navigation';

import {
    createCache,
    extractStyle,
    StyleProvider
} from '@ant-design/cssinjs'

const AntdProvider: React.FunctionComponent<React.PropsWithChildren> = ({children}) => {
    const [cache] = useState(() => createCache());

    useServerInsertedHTML(() => {
        return (
            <script dangerouslySetInnerHTML={{
                __html: `</script>${extractStyle(cache)}<script>`
            }}/>
        )
    });

    return <StyleProvider cache={cache}>{children}</StyleProvider>;
}

export default AntdProvider;
```


```tsx
import React from 'react';
import {Metadata} from 'next';
import {Inter} from 'next/font/google';

import AntdProvider from 'src/providers/ant';
import './globals.css'

const inter = Inter({
    subsets: ['latin']
});

const metadata: Metadata = {
    title: 'Pergum',
    description: 'Talent scaling as a service',
}

const RootLayout: React.FunctionComponent<React.PropsWithChildren> = ({children}) => (
    <html lang="en">
        <body className={inter.className}>
            <AntdProvider>{children}</AntdProvider>
        </body>
    </html>
);

export {metadata};
export default RootLayout;
```

**Comment by mvshvets** [comment]
@monolithed Your method works. My mistake. Thank you for helping me see her

**Comment by blockmood** [comment]
内联样式可以看到有两个相同内容的 <style id="antd"> 样式节点（造成html文件变大一倍）， 无法再生产中使用，你们有什么解决办法吗，V14的版本

**Comment by monolithed** [comment]
> 内联样式可以看到有两个相同内容的 <style id="antd"> 样式节点（造成html文件变大一倍）， 无法再生产中使用，你们有什么解决办法吗，V14的版本

@blockmood the main concern is that styles will be compiled on the server at runtime, and the rendering time could take several seconds. I've already [opened a ticket](https://github.com/ant-design/ant-design/issues/44770) for this issue, but it was closed.

**Comment by migokcek** [comment]
"next": "^13.5.6",
"antd": "^5.12.8",

Next.js App router

I have same issue, any update?

**Comment by XDXXDXXDXXDXXDX** [comment]
gatsby has same problem, anyone can help? thanks a lot
