### ISSUE TITLE
InputNumber onChange is not firing when I change value using arrow, it fires only when I update the value by keyboard.

### ISSUE THREAD

**Issue by gshudhanshu** [ant-design/ant-design#39908]
### Reproduction link

[https://sb9hzy.csb.app/](https://sb9hzy.csb.app/)

### Steps to reproduce

1) Create a form, form.Item, InputNumber
2) add onChange to InputNumber
3) Add console.log inside onChange

https://sb9hzy.csb.app/

### What is expected?

InputNumber onChange should trigger when changing the value using the arrow on the right side of the field.

### What is actually happening?

Currently, it fires on when the value is changed by the keyboard but not using arrows

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18 |
| System | Windows 11 |
| Browser | Chrome 108.0.5359.125 |

**Comment by jrr997** [comment]
It works when u move onChange to <InputNumber />, now it's on <Form.Item />

**Comment by MadCcc** [comment]
> It works when u move onChange to InputNumber, now it's on <Form.Item />

That's right. And you do not have to pass `onChange` to Form.Item since it will be handled automatically.

**Comment by gshudhanshu** [comment]
Sorry It is was not clearly mentioned, onChange is already in <Form.Item />
![image](https://user-images.githubusercontent.com/33764308/210047071-6ce30a0c-a455-494e-870c-1dc633b6d3d5.png)
