### ISSUE TITLE
Tag是否支持异步回调

### ISSUE THREAD

**Issue by luojian001** [ant-design/ant-design#3990]
#### 发生问题的环境是：

antd 版本:2.4.3
操作系统及其版本:MAC
浏览器及其版本:Chrome 54.0.2840.98 (64-bit)

**Comment by afc163** [comment]
duplicate #3984

**Comment by afc163** [comment]
加了 `e.preventDefault()` 就不会默认关闭掉了，可以自行在 onClose 逻辑中决定要展示哪些 Tag 。

**Comment by luojian001** [comment]
可能是我没有描述清楚，目前用到的场景是需要二次确认，点击关掉后弹出一个确认确框，根据确认框来确认是否删除掉
