### ISSUE TITLE
RangePicker 再次选择更远的时间时，日历面板没有同步更新到新的“开始时间”

### ISSUE THREAD

**Issue by helvenk** [ant-design/ant-design#39902]
### Reproduction link

[https://ant.design/~demos/components-date-picker-demo-extra-footer](https://ant.design/~demos/components-date-picker-demo-extra-footer)

### Steps to reproduce

1. 日期范围选择，先正常选一个时间段，比如 2022-12-01 到 2022-12-30；
2. 面板收起后，再次点击组件选择，开始时间选择一个更远的时间，比如 2023-04-01
3. 因为开始时间大于了原来的结束时间，旧的结束时间会被清除（rc-picker内部逻辑）
3. 这时展开的面板会回到上次的开始时间  2022-12-01 所在的月份

### What is expected?

弹出面板应该显示新的开始时间 2023-04-01 所在的月份

### What is actually happening?

弹出面板显示上次的开始时间 2022-12-01 所在的月份

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | * |
| System | macOS 12.6 |
| Browser | Chrome 107.0.5304.110 |

**Comment by Wxh16144** [comment]
> 2. 面板收起后，再次点击组件选择，开始时间选择一个更远的时间，比如 2023-04-01

步骤 2 重新点击开始时间选择 2023-04-01, 这个时候应该需要我们再选择结束时间。只选择了开始时间，并没有再选择结束，是不是这一次操作就不生效呢？

**Comment by helvenk** [comment]
> > 2. 面板收起后，再次点击组件选择，开始时间选择一个更远的时间，比如 2023-04-01
> 
> 步骤 2 重新点击开始时间选择 2023-04-01, 这个时候应该需要我们再选择结束时间。只选择了开始时间，并没有再选择结束，是不是这一次操作就不生效呢？

结束日期想选2023-05-01 要怎么办，面板时间还在2022-12-01，要手动一直切换到那个时间。如果面板时间同步到开始日期了，那就可以就近选择结束日期

**Comment by EmilyLike** [comment]
> > > 2. 面板收起后，再次点击组件选择，开始时间选择一个更远的时间，比如 2023-04-01
> > 
> > 
> > 步骤 2 重新点击开始时间选择 2023-04-01, 这个时候应该需要我们再选择结束时间。只选择了开始时间，并没有再选择结束，是不是这一次操作就不生效呢？
> 
> 结束日期想选2023-05-01 要怎么办，面板时间还在2022-12-01，要手动一直切换到那个时间。如果面板时间同步到开始日期了，那就可以就近选择结束日期

同样有类似的疑问，面板时间如果能同步就好了

**Comment by EmilyLike** [comment]
> 



> > > 2. 面板收起后，再次点击组件选择，开始时间选择一个更远的时间，比如 2023-04-01
> > 
> > 
> > 步骤 2 重新点击开始时间选择 2023-04-01, 这个时候应该需要我们再选择结束时间。只选择了开始时间，并没有再选择结束，是不是这一次操作就不生效呢？
> 
> 结束日期想选2023-05-01 要怎么办，面板时间还在2022-12-01，要手动一直切换到那个时间。如果面板时间同步到开始日期了，那就可以就近选择结束日期

**Comment by MadCcc** [comment]
Duplicated, trace in https://github.com/ant-design/ant-design/issues/40680 .
