### ISSUE TITLE
Transfer component's filterOption prop doesn't work unless something is entered in the search box

### ISSUE THREAD

**Issue by ivan-tkatchev** [ant-design/ant-design#39906]
### Reproduction link

https://codesandbox.io/s/antd-reproduction-template-forked-p0hnr1

### Steps to reproduce

When a Transfer component has a filterOption prop that doesn't depend on search filter state, it will not be triggered unless a non-empty string is entered into the search filter input.

### What is expected?

filterOption should work regardless of whether something is entered into the search input.

### What is actually happening?

User is forced to type something into the search input for filtering to occur.

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 17.0.1 |
| System | Linux |
| Browser | Mozilla |

**Comment by afc163** [comment]
Like Select/AutoComplete, Transfer `filterOption` prop works in searching situation. If you need to filter items in initial situation, please filter dataSource before passed to Transfer.

https://github.com/ant-design/ant-design/pull/39916

**Comment by ivan-tkatchev** [comment]
I need to filter the left (available items) pane only. If I filter the dataSource before passing to Transfer this affects the items in the right (selected items) pane too.
