### ISSUE TITLE
Ant Select causing the hydration to fail on SSR when enabling open state as default

### ISSUE THREAD

**Issue by phatify** [ant-design/ant-design#39912]
### Reproduction link

[https://stackblitz.com/edit/nextjs-pk1wps?file=pages%2Findex.js](https://stackblitz.com/edit/nextjs-pk1wps?file=pages%2Findex.js)

### Steps to reproduce

go to the above link

### What is expected?

Select should work when enabling open state of dropdown, ensures that the initial server-rendered page matches what will be rendered on the client.

### What is actually happening?
![image](https://user-images.githubusercontent.com/70096611/210008963-2f8189a6-0cf5-4d96-b7b6-b9e85b166b29.png)

Error: Hydration failed because the initial UI does not match what was rendered on the server.

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | React latest version |
| System | Windows 10 |
| Browser | Chrome latest version |

**Comment by afc163** [comment]
Could you try to upgrade antd to latest version?

**Comment by elis** [comment]
Similar issue with `<Slider />` and `tooltip.open=true`

**Comment by zombieJ** [comment]
Trigger patch the popup in body but ssr do not real have dom env. Seems open should be effect set in `rc-trigger`

**Comment by Riko2909** [comment]
same with `<Input type=password />`

**Comment by Riko2909** [comment]
Im getting the same error

**Comment by yunsii** [comment]
Similar issue with `forceRender`

**Comment by monolithed** [comment]
@petr166, https://github.com/ant-design/ant-design/issues/43727
