### ISSUE TITLE
Select 组件受 form 控制后赋值错误

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#39918]
### Reproduction link

[https://stackblitz.com/edit/react-arwra3?file=demo.tsx](https://stackblitz.com/edit/react-arwra3?file=demo.tsx)

### Steps to reproduce

```ts
const App: React.FC = () => {
  const [form] = Form.useForm();
  return (
    <Form form={form}>
      <Form.Item name="hmgIndexList" label="指数">
        <Space>
          <Form.Item noStyle name={['hmgIndexList', 0]}>
            <Select options={conditionOptions} style={{ width: '120px' }} />
          </Form.Item>
          <Form.Item noStyle name={['hmgIndexList', 1]}>
            <Input placeholder="请输入大于等于0的数量" />
          </Form.Item>
        </Space>
      </Form.Item>
    </Form>
  );
};
```

右边 input 框中值的改变会影响 select 框中的值，并且会将 input 的值赋值给 select

### What is expected?

右边 input 框中值的改变不会影响 select 框中的值

### What is actually happening?

右边 input 框中值的改变会影响 select 框中的值，并且会将 input 的值赋值给 select

| Environment | Info |
| --- | --- |
| antd | 4.24.6 |
| React | 16.8.6 |
| System | windows11 |
| Browser | Google 100.0.4896.60 |

**Comment by zombieJ** [comment]
只有需要绑定字段的组件才用 `name`，最上面那个是不用的：
https://stackblitz.com/edit/react-arwra3-37csw8?file=demo.tsx

**Comment by guaijie** [comment]
> 只有需要绑定字段的组件才用 `name`，最上面那个是不用的： https://stackblitz.com/edit/react-arwra3-37csw8?file=demo.tsx

是需要的， 否则字段hmgIndexList 初始值会是一个 [null, null]，而不是 undefined 。 而且只有这种组合（select,input）才会出现这种问题，我试过其他的组合是没有问题的
