### ISSUE TITLE
Invalid prop `value` of type `number` supplied to `Option`, expected `string`.

### ISSUE THREAD

**Issue by TDiDa** [ant-design/ant-design#3991]
`<FormItem {...formItemLayout} label="设备状态">
          {getFieldDecorator('deviceStatus', {
            initialValue: item.deviceStatus,
            rules: [
              {
                required: true,
                message: '请输入设备状态',
                type: 'number'
              }
            ]
          })(<Select style={{ width: '100%'}}>
              <Option value={1}>正常运行</Option>
              <Option value={0}>停机状态</Option>
            </Select>)}
        </FormItem>`

**Comment by yesmeck** [comment]
重复 https://github.com/ant-design/ant-design/issues/2857
