### ISSUE TITLE
Theme is not applied to notification and modal via ConfigProvider

### ISSUE THREAD

**Issue by denisputnov** [ant-design/ant-design#39911]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-framework-c0rek8?file=/src/App.js)

### Steps to reproduce

1. Use `ConfigProvider` with `theme.darkAlgorithm`
2. Try to use `notification` or `Modal` APIs

### What is expected?

Dark theme is applied to notification and modal

### What is actually happening?

Theme is not applied

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | MacOS Monterey 12.3 |
| Browser | Google Chrome - 108.0.5359.124 - (arm64) |

**Comment by 1pone** [comment]
https://ant.design/components/message#why-i-can-not-access-context-redux-configprovider-localeprefixclstheme-in-message

**Comment by MadCcc** [comment]
Use hooks or App instead. If you have to use static methods, try this way: https://ant.design/components/app#global-scene-redux-scene

**Comment by ShubhankarSinghTroopr** [comment]
> Use hooks or App instead. If you have to use static methods, try this way: https://ant.design/components/app#global-scene-redux-scene

can we hava js example for that..its typescript there

**Comment by AliwerDev** [comment]
I had the same problem and I was able to fix it

https://ant.design/docs/blog/modal-hook-order
