### ISSUE TITLE
Tour在StrictMode模式下卡片指向元素错误

### ISSUE THREAD

**Issue by trywenJun** [ant-design/ant-design#39921]
### Reproduction link

[https://8prkit.csb.app/](https://8prkit.csb.app/)

### Steps to reproduce

该示例为官方文档示例源码 请点击后查看控制台！

### What is expected?

去除warning 在实际开发中会遇到不可预期的错误

### What is actually happening?

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Trigger which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at eval (https://8prkit.csb.app/node_modules/rc-trigger/es/Popup/index.js:26:22)
    at eval (https://8prkit.csb.app/node_modules/rc-util/es/Portal.js:11:25)
    at Trigger (https://8prkit.csb.app/node_modules/rc-trigger/es/index.js:62:35)
    at Tour (https://8prkit.csb.app/node_modules/@rc-component/tour/es/Tour.js:47:32)
    at Tour (https://8prkit.csb.app/node_modules/antd/es/tour/index.js:27:21)
    at div
    at App (https://8prkit.csb.app/index.js:25:34)

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2 |
| System | win11 |
| Browser | Edge Chorme |

---
codesandbox无法复现在StrictMode下实际场景中的卡片指向元素错误 但是控制台的warning可以看到

**Comment by MadCcc** [comment]
指向元素错误录个屏看看？

**Comment by trywenJun** [comment]
附件录屏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月30日(星期五) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Tour在StrictMode模式下卡片指向元素错误 (Issue #39921)





 
指向元素错误录个屏看看？

**Comment by trywenJun** [comment]
已发送邮件 请查看

**Comment by MadCcc** [comment]
邮件看不到的，在 github 上传一下

**Comment by trywenJun** [comment]
> 邮件看不到的，在 github 上传一下


https://user-images.githubusercontent.com/91248348/210048924-415e33e1-c6f3-4281-bdee-c25fac30e5a4.mp4

**Comment by MadCcc** [comment]
你本地的 @rc-component/tour 版本是多少？

**Comment by trywenJun** [comment]
> 你本地的 @rc-component/tour 版本是多少？

![image](https://user-images.githubusercontent.com/91248348/210049625-f93f92d6-16e8-4267-b148-05abecfc2869.png)

**Comment by MadCcc** [comment]
5.1.1 还没更新到 1.3.0，你是项目里的依赖么

**Comment by trywenJun** [comment]
> 5.1.1 还没更新到 1.3.0，你是项目里的依赖么

不好意思 我记错了命令 npm view package version是查看最新版本的

本地的版本是1.1.0

![image](https://user-images.githubusercontent.com/91248348/210051268-03f02cf6-af71-4435-ab0f-2bfe0828d2a3.png)

**Comment by MadCcc** [comment]
最好是能够提供一下复现能定位问题。`findDOMNode` 是底层 `rc-trigger` 的问题，应该不会影响。

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/210052177-dde2379c-d5ff-49a8-93ae-bf4efdab7f1c.png">

可以重现，重现步骤：

1. 点击『Begin Tour』
2. 点击右上角关闭按钮。

**Comment by trywenJun** [comment]
> 最好是能够提供一下复现能定位问题。`findDOMNode` 是底层 `rc-trigger` 的问题，应该不会影响。

https://user-images.githubusercontent.com/91248348/210052613-610e9d67-2b2b-4912-8d9d-accbcfc026e1.mp4

我精简了代码 react-router-dom也不要了（但其实router对它毫无影响）
当我不用React.StrictMode 它就正常了

**Comment by trywenJun** [comment]
> > 最好是能够提供一下复现能定位问题。`findDOMNode` 是底层 `rc-trigger` 的问题，应该不会影响。
> 
>  20221230165513.mp4 
> 我精简了代码 react-router-dom也不要了（但其实router对它毫无影响） 当我不用React.StrictMode 它就正常了



> 最好是能够提供一下复现能定位问题。`findDOMNode` 是底层 `rc-trigger` 的问题，应该不会影响。

所以还是在StrictMode下出现了问题

**Comment by kiner-tang** [comment]
> <img alt="图片" width="1792" src="https://user-images.githubusercontent.com/507615/210052177-dde2379c-d5ff-49a8-93ae-bf4efdab7f1c.png">
> 
> 可以重现，重现步骤：
> 
> 1. 点击『Begin Tour』
> 2. 点击右上角关闭按钮。

是的，确实是关闭时会出现

**Comment by chendong-xie** [comment]
是有问题 在严格模式下报错 有什么进展吗 这个问题

**Comment by yoyo837** [comment]
Reopen by #40159

**Comment by trywenJun** [comment]
> > 邮件看不到的，在 github 上传一下
> 
>  20221230160739.mp4

请仔细查看标题 观看录频的问题 是元素指向出错！！！ 下一步的时候指向的是上一个元素 在5.20版本依旧没有解决
