### ISSUE TITLE
[docs] :  Tabs: `onEdit`  callback type is wrong

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#39925]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lz9exn?file=/index.tsx)

### Steps to reproduce

The ts type error occurred in using the Tabs deletion function.

### What is expected?

Obtain the correct type under ts

### What is actually happening?

The type of the first parameter under ts gets an error warning

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome  108.0.5359.125 |

---
I didn't see this problem in the codesandbox, but it only occurred locally.
![image](https://user-images.githubusercontent.com/81673017/210052841-96833d8a-7dfa-45d4-a9fb-eaba1fd5ba90.png)

![image](https://user-images.githubusercontent.com/81673017/210052808-9e760526-5bcf-4f2e-bde2-77d33efdb553.png)

**Comment by afc163** [comment]
onEdit 貌似没有报错？https://codesandbox.io/s/antd-reproduction-template-forked-obond0?file=/index.tsx

**Comment by RSS1102** [comment]
> onEdit 貌似没有报错？https://codesandbox.io/s/antd-reproduction-template-forked-obond0?file=/index.tsx

但是在本地跑的时候

> onEdit 貌似没有报错？https://codesandbox.io/s/antd-reproduction-template-forked-obond0?file=/index.tsx

但是在本地之前是出现错误的。。。而且你看下type.d.ts声明，的确是声明不一致啊。。。

**Comment by afc163** [comment]
@RSS1102 能给个 codesandbox 重现么？

**Comment by RSS1102** [comment]
> @RSS1102 能给个 codesandbox 重现么？没有重现没办法确定怎么修，以及是否修复了

@afc163 抱歉在codesandbox 没有复现，
但是在最新版的antd使用官方的demo依然出现ts报错（见README）。
请clone至本地：https://github.com/RSS1102/antd-tabs-demo

---
之前提过一个pr，但是到年关了，公司里项目要的太紧，所以目前还没有时间去跟踪。

**Comment by afc163** [comment]
确实，strict 模式会报错。
