### ISSUE TITLE
Tabs下划线ant-tabs-ink-bar 的width和left都是0

### ISSUE THREAD

**Issue by wangyingjie123** [ant-design/ant-design#39927]
### Reproduction link

[https://4x.ant.design/components/tabs-cn/#API](https://4x.ant.design/components/tabs-cn/#API)

### Steps to reproduce

```
<div>
     <Tabs
        className="margin-t-10"
        defaultActiveKey="1"
        items={[
          {
            label: '入库审核',
            key: '1',
          },
          {
            label: `下载审核`,
            key: '2',
          },
        ]}
      />
</div>
```

### What is expected?

正常展示下划线

### What is actually happening?

未出现选中下划线ant-tabs-ink-bar 的width和left都是0

| Environment | Info |
| --- | --- |
| antd | 4.24.6 |
| React | 18.0.2 |
| System | mac |
| Browser | chrome108 |

**Comment by kiner-tang** [comment]
@wangyingjie123 你可以在这里提供一下复现用例吗？这边使用你提供的代码无法复现问题。
https://codesandbox.io/s/ji-ben-antd-4-24-7-forked-t3tihe

**Comment by wangyingjie123** [comment]
> @wangyingjie123 你可以在这里提供一下复现用例吗？这边使用你提供的代码无法复现问题。 https://codesandbox.io/s/ji-ben-antd-4-24-7-forked-t3tihe <img alt="image" width="1237" src="https://user-images.githubusercontent.com/10286961/210121829-a61a963f-59ee-4d1c-9a82-450e79d63610.png">

升级到4.24.7好了

**Comment by FlexibleHha** [comment]
@wangyingjie123 这个问题我也遇到了，复现不了这个bug，项目中的代码出现left，width始终是0 的情况
