### ISSUE TITLE
Table grows with duplicate rows when sorting is enabled.

### ISSUE THREAD

**Issue by kethiri-fm** [ant-design/ant-design#39920]
### Reproduction link

[https://stackblitz.com/edit/react-vqytq3?file=demo.tsx](https://stackblitz.com/edit/react-vqytq3?file=demo.tsx)

### Steps to reproduce

Sort the Math and English scores.

### What is expected?

Scores to be sorted in ascending/descending order

### What is actually happening?

Duplicate rows appearing.

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Microsoft Edge 108.0.1462.54 |

**Comment by MadCcc** [comment]
Use unique `key` for each row.

**Comment by pergunt** [comment]
I am facing the same issue. Even with rowKey prop (where I return el ID. It exists) the table duplicates each row
