### ISSUE TITLE
Button effect problem after scroll

### ISSUE THREAD

**Issue by amiryxe** [ant-design/ant-design#39949]
### Reproduction link

[https://ant.design/components/button](https://ant.design/components/button)

### Steps to reproduce

There is a problem with displaying the round effect of the button when it is clicked

### What is expected?

The effect around the button will always stay around it.

### What is actually happening?

When we click on the button, the effect around it will be displayed. If we scroll the page immediately, the effect will follow the page

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.0.0 |
| System | Ubuntu 22.04.1 LTS |
| Browser | Chrome Version 108.0.5359.124 |

**Comment by afc163** [comment]
Introduced in https://github.com/ant-design/ant-design/pull/39705

@li-jia-nan
