### ISSUE TITLE
5.1.2版本使用vite打包后国际化配置丢失

### ISSUE THREAD

**Issue by Swz0321** [ant-design/ant-design#39946]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

antd5.1.2下使用vite@4.0.3打包

### What is expected?

国际化在开发时正常，打包后丢失

### What is actually happening?

国际化配置，打包与开发场景应一致

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | 22000.1335 |
| Browser | 108.0.1462.54 |

**Comment by li-jia-nan** [comment]
是哪个组件的国际化丢失了？

**Comment by Swz0321** [comment]
> 

全部，神奇的是create-react-app的打包是没有问题的，可能是vite那边的问题吧

**Comment by li-jia-nan** [comment]
只有 5.1.2 是这样吗？其它版本有这个问题吗？

**Comment by Swz0321** [comment]
> 只有 5.1.2 是这样吗？其它版本有这个问题吗？

回退到5.1.1用vite打包是正常的，5.1.2就不行了，用create-react-app打包5.1.2也是正常的，用vite就不行

**Comment by li-jia-nan** [comment]
- #39890 
- #39934 
应该是这个导致的……

**Comment by li-jia-nan** [comment]
但是看 CI 的 size-limit 又是合理的，奇怪

**Comment by li-jia-nan** [comment]
- https://github.com/ant-design/antd-tools/pull/270

**Comment by li-jia-nan** [comment]
我这边用 `vite  4.0.3` + `antd 5.1.2` 打包出来好像是正常的

![image](https://user-images.githubusercontent.com/49217418/210177477-36bac369-df97-47c3-9c42-5f9b214f5853.png)

**Comment by li-jia-nan** [comment]
- https://github.com/ant-design/antd-tools/pull/270

merged~

**Comment by li-jia-nan** [comment]
@Swz0321 等下周 5.1.3 发布，看看问题有没有解决，因为我这边没有复现出来，如果到时候还没解决的话，需要你提供更详细的复现 demo，这个我先 close 了~

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/components/config-provider-cn#vite-%E7%94%9F%E4%BA%A7%E6%A8%A1%E5%BC%8F%E6%89%93%E5%8C%85%E5%90%8E%E5%9B%BD%E9%99%85%E5%8C%96-locale-%E8%AE%BE%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88
先看下是不是这个问题，如果打包有问题的话 dev 下也是不行的

**Comment by Swz0321** [comment]
> https://ant-design.antgroup.com/components/config-provider-cn#vite-%E7%94%9F%E4%BA%A7%E6%A8%A1%E5%BC%8F%E6%89%93%E5%8C%85%E5%90%8E%E5%9B%BD%E9%99%85%E5%8C%96-locale-%E8%AE%BE%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88 先看下是不是这个问题，如果打包有问题的话 dev 下也是不行的

是的，更改引入locale的路径之后解决了

**Comment by Swz0321** [comment]
> @Swz0321 等下周 5.1.3 发布，看看问题有没有解决，因为我这边没有复现出来，如果到时候还没解决的话，需要你提供更详细的复现 demo，这个我先 close 了~

@li-jia-nan @MadCcc 用这位老哥方案解决了
