### ISSUE TITLE
DatePicker initial value issue

### ISSUE THREAD

**Issue by AndreuSerraSastre** [ant-design/ant-design#39956]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/time-related-controls-antd-5-1-2-forked-fq7btw?file=/demo.tsx:0-634)

### Steps to reproduce

When using the DatePicker component from Ant Design within a form and setting an initial value, all dates in the pop up calendar are highlighted in blue as if they are selected. Moving the cursor over the pop up calendar causes the date and month to change automatically without any clicks. Clicking the "back" button also causes the year to change. This issue does not occur when the DatePicker does not have an initial value.

### What is expected?

It is expected that the DatePicker component will display the initial value correctly and allow the user to select a different date without any unexpected behavior, such as automatically changing the date or month when the cursor is moved over the pop up calendar. The initial value should also not cause any dates to be highlighted in blue as if they are selected.

### What is actually happening?

According to your description, when the initial value is set for the DatePicker component, all of the dates in the pop up calendar are highlighted in blue as if they are selected. Moving the cursor over the pop up calendar causes the date and month to change automatically without any clicks. Clicking the "back" button also causes the year to change. This issue does not occur when the DatePicker does not have an initial value.

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | react  |
| System | Any |
| Browser | Any |

**Comment by anjantalatam** [comment]
Ant Design Pickers are using `Dayjs` as date library from `5.0.0`

Your issue seems to be resolved when Dayjs is used instead of moment js.  Check this [Sandbox](https://codesandbox.io/s/ant-design-issues-39956-vz866g)

Follow [this guide](https://ant.design/docs/react/use-custom-date-library) to use moment as your date library

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774

**Comment by 11biswanath** [comment]
hey there is a new kind of problem  i face i cannot view  the date instead of placeholder  when im using value prop but i can see with default value which throws an error 
```jsx
          import React from 'react'
          import { Col, Form, DatePicker } from 'antd'
          import dayjs from 'dayjs'
          import { useOnboarding } from '@/providers/OnboardingProvider'
          
          const DateOfBirthPicker: React.FC = () => {
              const { formData, handleDateChange } = useOnboarding()
              console.log(formData.dateOfBirth ? dayjs(formData.dateOfBirth) : null)
          
              return (
                  <Col span={24}>
                      <Form.Item
                          className="mb-0"
                          label="Date Of Birth"
                          name="dateOfBirth"
                      >
                          <DatePicker
                              style={{ width: "100%", height: "50px" }}
                              placeholder="DD/MM/YYYY"
                              value={formData.dateOfBirth}
                              onChange={(date) => handleDateChange(date, date ? date.format('YYYY-MM-DD') : '')}
                          />
                      </Form.Item>
                  </Col>
              )
          }
          
          export default DateOfBirthPicker
```
the console log shows up the daysjs object perfectly fine

![Image](https://github.com/user-attachments/assets/7e7e5a72-df9f-479b-a80a-cdae8ee9ca7f)

```js
    useEffect(() => {
        const storedFormData = localStorage.getItem("formData");
        if (storedFormData) {
            const parsedFormData = JSON.parse(storedFormData);
            parsedFormData.dateOfBirth = dayjs(parsedFormData.dateOfBirth);
            setFormData(parsedFormData);
        }

        const storedOnboardingStatus = localStorage.getItem("onboardingCompleted");
        setOnboardingCompleted(storedOnboardingStatus === "true");
    }, []);

```
here is the part of useOnboarding ie context where i set the date

**Comment by abdrhxyii** [comment]
hey @anjantalatam , thanks for your help. It worked for me. I just replace the moment.js with dayjs.
