### ISSUE TITLE
DatePicker value受控模式下，无法使用 useState 清空

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#39953]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

DatePicker value受控模式下，无法使用 useState 清空

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | React 18.2.0 |
| System | Windows |
| Browser | Chrome 103 |

**Comment by hihuangwei** [comment]
demo https://codesandbox.io/s/ji-ben-antd-5-1-2-forked-shi86n?file=/demo.tsx

**Comment by afc163** [comment]
```diff
- <DatePicker vlaue={startDate} onChange={onChange}/>
+ <DatePicker value={startDate} onChange={onChange}/>
```
