### ISSUE TITLE
Pass attributes to date range picker input elements

### ISSUE THREAD

**Issue by ahamdy89** [ant-design/ant-design#39951]
### What problem does this feature solve?

For out automation testing - using selenium - we need to pass `data-test-id` to dom elements but in the date range picker this is not possible with the current API 

### What does the proposed API look like?

```js
<DatePicker.RangePicker
  startDateInputProps={{"data-test-id": "start-date-input}}
  endDateInputProps={{"data-test-id": "end-date-input}}
/>
```

**Comment by afc163** [comment]
Duplicate of #39629
