### ISSUE TITLE
Customising Ant components and their inner elements

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#39957]
### What problem does this feature solve?

There is no way to properly customise ant components nor their inner elements right now. Ant components dont accept css-in-js and dont have any API to style their inner elements neither.

### What does the proposed API look like?

I imagine something like Styles API from Mantine https://mantine.dev/styles/styles-api/ 

```
<Modal 
    styles={{
        root: { color: '' },
        content: { ... },
        mask: { ... }
    }}
/>
```

**Comment by afc163** [comment]
Try https://ant.design/docs/react/customize-theme

**Comment by Kamahl19** [comment]
@afc163 I have read that page multiple times. It does not solve the problem at all. The customisation of Ant went from OK with less.js to horrible with css-in-js. It should be the exact opposite. Could you please take a look on the link I posted above https://mantine.dev/styles/styles-api/ . This API would improve the customisation tremendously. 

This is a second issue I have created regarding customisation, and similarly to the first one #39787 , it was closed without any discussion and consideration by @zombieJ . 

I believe this the biggest and only major issue with Ant right now. And not just me, I hear this from everyone. Could you please explain me how you consider proper customisation to be done or can we start a discussion where we lay down the real-world needs and issues and try to find the solution together?

Thanks for the great work on Ant.

**Comment by mleister97** [comment]
@Kamahl19 did you find a solution? i would like to style as it's the case in MUI or mantine...

**Comment by Kamahl19** [comment]
@mleister97 nope, it's not possible until Ant exposes all the tokens used in all components and let developers override them.
