### ISSUE TITLE
Access Table coulmn title/dataIndex through render function 

### ISSUE THREAD

**Issue by lxtadhamnawito** [ant-design/ant-design#39960]
### What problem does this feature solve?

If you're trying to make a generic function for rendering data among table, and you want to make a specific action according to what is the column you're at rigth now, this won't be possible. As render function gets you three values (text, record, index)
where text is data, record is the entire row data, and index is row index not column index.

### What does the proposed API look like?

I think it might be just a new parameter that is send to render function which give you dataIndex of current column or column index directly.

**Comment by zombieJ** [comment]
Just HOC it:

```tsx
const columns = [{
  title: 'abc',
  render: (text, record, index, columnData) => {
    // ...
  } 
}];

const injectColumnsInfo = (cols) => cols.map(col => ({
   ...col,
   render: (text, record, index) => {
     return col.render(text, record, index, col);
   },
}));

<Table columns={injectColumnsInfo(columns)} />
```
