### ISSUE TITLE
Transfer 搜索无结果时不能显示 Not Found

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#3996]
#### 您做了什么？请提供尽可能详细的重现步骤。

对官网可搜索的 Transfer 例子搜索一个不存在 item

#### 您期待的结果是:

显示 “Not Found”

#### 实际上的结果是:

什么都没显示

#### 可重现的在线演示

https://ant.design/components/transfer/#components-transfer-demo-search

应该是上次引入 LazyLoad 的时候改坏了，因为把搜索的动作放到 Item 里做了，所以 list 里的这个 `showItems` https://github.com/ant-design/ant-design/blob/master/components/transfer/list.tsx#L211 永远都是长度大于 0 的。

**Comment by afc163** [comment]
还有个奇怪的问题，第一个例子一开始显示不出来了。
