### ISSUE TITLE
[tabs] type `TabItemType`，whether it should be exported

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#39970]
### What problem does this feature solve?

我在文档看到规范了这个类型，但是我在代码内并没有查找到对于这个类型的定义https://ant.design/components/tabs-cn#tabitemtype
在定义tab的items数据时，想用一个类型进行约束。

### What does the proposed API look like?

export TabItemType

**Comment by RSS1102** [comment]
或许他应该是一个bug，我不太明确。

**Comment by afc163** [comment]
Try `TabsProps['items']`.

https://github.com/ant-design/ant-design/pull/39982#issuecomment-1369715966
