### ISSUE TITLE
filePath not found    /node_modules/antd/es/auto-complete/style

### ISSUE THREAD

**Issue by liuxi0811** [ant-design/ant-design#39973]
### What problem does this feature solve?

filePath not found    /node_modules/antd/es/auto-complete/style

### What does the proposed API look like?

v4升级到v5遇到
![image](https://user-images.githubusercontent.com/75471072/210335282-25ae1ef3-bf6c-4230-83b2-687f5d73199c.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/38803#issuecomment-1322111921
https://github.com/ant-design/ant-design/issues/39716#issuecomment-1361389584

**Comment by liuxi0811** [comment]
> [#38803 (comment)](https://github.com/ant-design/ant-design/issues/38803#issuecomment-1322111921) [#39716 (comment)](https://github.com/ant-design/ant-design/issues/39716#issuecomment-1361389584)

![image](https://user-images.githubusercontent.com/75471072/210353693-ab4a4b3d-0c3e-4d41-993d-792bbf90e915.png)
但是出现这种情况
![image](https://user-images.githubusercontent.com/75471072/210353762-3da11e94-be43-4a4e-9d9b-6c804e90a5bc.png)

**Comment by afc163** [comment]
看上去不需要这个 antd 配置。

**Comment by liuxi0811** [comment]
> 看上去不需要这个 antd 配置。

在umi中是如何关掉的呢

**Comment by afc163** [comment]
@liuxi0811 删掉 antd 这个配置

**Comment by liuxi0811** [comment]
![image](https://user-images.githubusercontent.com/75471072/210479799-e36a9d01-153b-480b-9d06-fb96eedc58a7.png)
依旧会报这个错

**Comment by liuxi0811** [comment]
> @liuxi0811 删掉 antd 这个配置

是不是没有lib的原因呢？

**Comment by afc163** [comment]
你最好能给个 github repo 的最小可重现。

**Comment by yoyo837** [comment]
可能是 `@umijs/preset-built-in`里使用了`babel-plugin-import`

**Comment by liuxi0811** [comment]
> 可能是 `@umijs/preset-built-in`里使用了`babel-plugin-import`

我在lock文件确实找到了

**Comment by liuxi0811** [comment]
> 

`// https://umijs.org/config/
import { defineConfig } from 'umi';
import { join } from 'path';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
import routes from './routes';

const { theme } = require('antd/lib');
const { convertLegacyToken } = require('@ant-design/compatible/lib');
const { defaultAlgorithm, defaultSeed } = theme;
const mapToken = defaultAlgorithm(defaultSeed);
const v4Token = convertLegacyToken(mapToken);

const { REACT_APP_ENV } = process.env;

export default defineConfig({
  hash: true,
  antd: {
    // import: false,
  },
  dva: {
    hmr: true,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  access: {},
  lessLoader: {
    modifyVars: v4Token,
  },
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    // 如果不想要 configProvide 动态设置主题需要把这个设置为 default
    // 只有设置为 variable， 才能使用 configProvide 动态设置主色调
    // https://ant.design/docs/react/customize-theme-variable-cn
    'root-entry-name': 'variable',
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  // Fast Refresh 热更新
  fastRefresh: {},
  openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],
  nodeModulesTransform: { type: 'none' },
  mfsu: {},
  webpack5: {},
  exportStatic: {},
  history: {
    type: 'hash',
  },
  publicPath: `/page/${defaultSettings.path}/`,
  outputPath: `./dist/${defaultSettings.path}`,
});
`

**Comment by liuxi0811** [comment]
> 你最好能给个 github repo 的最小可重现。
这事umi配置文件
// https://umijs.org/config/
import { defineConfig } from 'umi';
import { join } from 'path';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
import routes from './routes';

const { theme } = require('antd/lib');
const { convertLegacyToken } = require('@ant-design/compatible/lib');
const { defaultAlgorithm, defaultSeed } = theme;
const mapToken = defaultAlgorithm(defaultSeed);
const v4Token = convertLegacyToken(mapToken);

const { REACT_APP_ENV } = process.env;

export default defineConfig({
  hash: true,
  antd: {
    // import: false,
  },
  dva: {
    hmr: true,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  access: {},
  lessLoader: {
    modifyVars: v4Token,
  },
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    // 如果不想要 configProvide 动态设置主题需要把这个设置为 default
    // 只有设置为 variable， 才能使用 configProvide 动态设置主色调
    // https://ant.design/docs/react/customize-theme-variable-cn
    'root-entry-name': 'variable',
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  // Fast Refresh 热更新
  fastRefresh: {},
  openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],
  nodeModulesTransform: { type: 'none' },
  mfsu: {},
  webpack5: {},
  exportStatic: {},
  history: {
    type: 'hash',
  },
  publicPath: `/page/${defaultSettings.path}/`,
  outputPath: `./dist/${defaultSettings.path}`,
});

**Comment by yoyo837** [comment]
demo给在线的,或者repo可以直接 clone然后install就可见问题的

**Comment by afc163** [comment]
umi 文档里的配置好像和源码里的对不上：

- import：https://umijs.org/docs/max/antd#import
- disableBabelPluginImport：https://github.com/umijs/plugins/blob/2aaf8ebb750b76698e755af8ad0b700ae5138297/packages/plugin-antd/src/index.ts#L12

**Comment by xiaogonggong-w** [comment]
> demo给在线的,或者repo可以直接 clone然后install就可见问题的

我看closed,请问你是怎么解决的呀

**Comment by dongtao0725** [comment]
nmi的改成这样：
 antd: {
    disableBabelPluginImport:true
  },

**Comment by CheneyH** [comment]
把babel-plugin-import配置中的antd的style改成false即可

**Comment by guanyx** [comment]
> ![image](https://user-images.githubusercontent.com/75471072/210479799-e36a9d01-153b-480b-9d06-fb96eedc58a7.png) 依旧会报这个错

把umijs配置里的 
antd设为false
删掉是会默认生效的

原因应该是 [@umijs/plugin-antd](https://v3.umijs.org/plugins/plugin-antd) 里默认使用了 babel-plugin-import

**Comment by guojunhao118** [comment]
> 

所以umi也需要升级到4.0版本？
