### ISSUE TITLE
ConfigProvider 设置统一样式前缀 prefixCls，Modal.confirm 的样式不生效

### ISSUE THREAD

**Issue by soapwong** [ant-design/ant-design#39975]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g61jlk?file=/index.js:0-665)

### Steps to reproduce

1. 点击 button 触发 `Modal.confirm`
2. 控制台查看 Modal 的 HTML 元素 css 前缀。仍然是 `ant-`

### What is expected?

预期 `Modal.confirm` 触发的 `Modal` 样式前缀都是 `统一设置前缀-modal-xxx`

### What is actually happening?

实际 `Modal.confirm`  触发的 `Modal` 样式前缀仍是 `ant-modal-xxx`

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 18.2 |
| System | macOS Monterey 12.6.1 |
| Browser | chrome |

**Comment by zombieJ** [comment]
[#静态方法如何设置-prefixCls-？](https://4x.ant.design/components/modal-cn/#%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE-prefixCls-%EF%BC%9F)
