### ISSUE TITLE
使用hashPriority和transformers后，在旧版浏览器下radio-group的选中样式消失

### ISSUE THREAD

**Issue by Cowjiang** [ant-design/ant-design#39979]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/39978](https://github.com/ant-design/ant-design/issues/39978)

### Chrome 108（正常显示）
https://user-images.githubusercontent.com/57822554/210339598-4d1f8d61-2766-4a12-be99-fc7af188b8b4.png

### 微信浏览器（样式丢失）
https://user-images.githubusercontent.com/57822554/210339698-d11400e7-6c93-4d84-8f2a-5755a97b11fe.jpg

### cssinjs兼容性配置
```typescript
React.createElement(StyleProvider, {
  hashPriority: 'high',
  transformers: [legacyLogicalPropertiesTransformer]
}, rootElement);
```

### 版本信息
```json
"antd": "5.1.2",
"@ant-design/cssinjs": "1.3.2",
"@types/react": "18.0.26",
"@types/react-dom": "18.0.9"
```

### What is expected?

正常显示

### What is actually happening?

radio btn group组件，在进行了cssinjs的兼容性配置后，当前选中的样式（.ant-radio-button-wrapper-checked）在旧内核浏览器（如微信浏览器）中丢失

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.0.26 |
| System | Android / Windows 11 |
| Browser | 旧内核浏览器（如微信） |

**Comment by MadCcc** [comment]
旧版浏览器不支持 `:not` 的 list argument，导致样式失效。
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/:not#browser_compatibility

**Comment by Cowjiang** [comment]
> 

在 transformer 中拿到的 `cssObj` 的 key 是包含 `&` 的，并非最终 css 类名，如：

![image](https://user-images.githubusercontent.com/57822554/210540330-c84a69a0-2ae8-45f2-a686-31e5b6c50689.png)

`&` 最终会替换为类似 `.css-dev-only-do-not-override-k83k30.ant-btn-compact` 的

但是在 transformer 中，如果要进行兼容性处理，该如何转换呢？
