### ISSUE TITLE
List: footer not visible/fixed

### ISSUE THREAD

**Issue by hbatalhaStch** [ant-design/ant-design#39977]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/scrolling-loaded-antd-5-1-2-forked-zvostw?file=/demo.tsx)

### Steps to reproduce

Add a footer to the demo example

### What is expected?

a bottom-fixed List footer

### What is actually happening?

footer only visible after scrolling all the items in the List

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | Windows 10 Pro Version: 21H2 OS Build: 19044.2251 |
| Browser | MS Edge |

**Comment by ayushete02** [comment]
Actually there is no footer tag in code
assign me this i will fixed

**Comment by hbatalhaStch** [comment]
> Actually there is no footer tag in code 

I just added footer tag to the code

> assign me this i will fixed

I don't think I have permission to assign an issue to someone, this is up to the maintainers/collaborators
You can fix the issue and create a pull request

**Comment by afc163** [comment]
https://codesandbox.io/s/scrolling-loaded-antd-5-1-2-forked-zvostw?file=/index.css
