### ISSUE TITLE
Avtar CSS having Some Issue

### ISSUE THREAD

**Issue by ayushete02** [ant-design/ant-design#39981]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0g7dh2)

### Steps to reproduce

https://codesandbox.io/s/0g7dh2

### What is expected?

Change avatar CSS

### What is actually happening?

Avatar circle is not flexible

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 0.70 |
| System | Windows 11 |
| Browser | Version 108.0.5359.125 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Merge to #39962
