### ISSUE TITLE
5.1.2 introduced new bug: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by MarkLyck** [ant-design/ant-design#39984]
### Steps to reproduce

upgrade existing project from antd 5.1.1 to 5.1.2

### What is expected?

should not throw an error

### What is actually happening?

The following error is occurring on all pages in multiple applications after upgrading to 5.1.2

```
TypeError: Right-hand side of 'instanceof' is not an object
 ❯ _default node_modules/.pnpm/rc-util@5.27.1_biqbaboplfbrettd7655fr4n2y/node_modules/rc-util/lib/Dom/isVisible.js:14:15
```

Seems to be a problem in rc-util which is used in antd and only breaks when upgrading from 5.1.1 to 5.1.2

Sorry for the poor "ticket", but don't have time to fully reproduce it today and just wanted to make sure you are at least aware of this happening.

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | MacOS Ventura |
| Browser | Any |

**Comment by zombieJ** [comment]
Thanks for feedback. But `rc-util` is low level util lib which can not help which component give an invalidate params. We still need reproduce to trace it.

**Comment by MarkLyck** [comment]
Figured out the problem.

`rc-util` introduced a new check for `instanceof SVGGraphicsElement` which is not supported in `happy-dom` and thus causing a bunch of unit tests to fail for antd components that use `isVisible` from `rc-util`

This does seem to be supported in `jsDOM` which I imagine most people are using and why there aren't many people running into this issue with antd.

Created an issue for happy-dom here: https://github.com/capricorn86/happy-dom/issues/761
