### ISSUE TITLE
Themes only cover the components, not the entire page

### ISSUE THREAD

**Issue by mxye** [ant-design/ant-design#39986]
### Reproduction link

[https://codepen.io/benjycui/pen/KgPeME?editors=001](https://codepen.io/benjycui/pen/KgPeME?editors=001)

### Steps to reproduce

1. Create a new project using create-react-app
2. Follow the documentation to add antd: https://ant.design/docs/react/use-with-create-react-app#import-antd
2. Follow the documentation on using dark themes: https://ant.design/docs/react/customize-theme#use-preset-algorithms

### What is expected?

When I was using Antd 4.x, the craco-less method of dark theme made the entire webpage dark. I'd expect the new 5.x ConfigProvider would achieve the same result

### What is actually happening?

with 5.x, despite that the ConfigProvider providing the dark theme wraps around the entire app, the page is still on a white background. Only the antd components are dark. As a result, some of the white text in the dark components aren't visible on the white background. Of course, I could fix the background to a dark color with css, but wouldn't that prevent the easy switching between dark and light themes using antd 5.x, which is why we upgrade from 4.x to 5.x? 

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | mac OS |
| Browser | Chrome |

---
I didn't provide a link to reproduce believing it's not necessary. I didn't change anything to the new create-react-app project, except making the minimum accommodations as instructed by the documentation. I'm sure it's well known that the background color remains light with the dark theme. The question is, what is the recommended way to turn the entire page dark with the dark theme that still benefits from the strength of 5.x, in terms of theme-switching?

If there's something I'm missing, please add a paragraph to the documentation to explain

**Comment by zombieJ** [comment]
Please use Layout component. It's by design to apply theme on antd component instead of global style pollution.

**Comment by Ricardosssss** [comment]
I have the same problem

**Comment by liesislukas** [comment]
same problem, though it's good antd does not leak out of it's scope. just add Layout component or add custom code for your custom stuff
