### ISSUE TITLE
Drawer opening after a delay in Safari

### ISSUE THREAD

**Issue by anjantalatam** [ant-design/ant-design#39995]
### Reproduction link

[https://ant.design/components/drawer](https://ant.design/components/drawer)

### Steps to reproduce

1. Open the above link in Chrome first and click Open button in the first Demo
2. Do the same in Safari
3. Safari Drawer is opening after a delay compared to Chrome and Firefox

### What is expected?

Drawer should open smoothly on Safari as in Chrome, and Firefox.

### What is actually happening?

Drawer is taking some time to open.

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.0.0 |
| System | Mac |
| Browser | Safari |

---
You can observe similar behavior in Codesandbox. https://codesandbox.io/s/m199g4?file=/demo.tsx
But here the delay is less compared to the delay in https://ant.design/components/drawer

In the project I am using the delay is the same as in the Demo ( https://ant.design/components/drawer )

**Comment by afc163** [comment]
感觉和 Wave 的重构有关系，Drawer 疑似会等到水波动画结束后才出现。

**Comment by afc163** [comment]
问题还在

**Comment by kiner-tang** [comment]
Let me see what causes the problem.
