### ISSUE TITLE
带有tabs组件的页面切换控制台报错

### ISSUE THREAD

**Issue by wangyingjie123** [ant-design/ant-design#39999]
### Reproduction link

[https://4x.ant.design/components/tabs-cn/#API](https://4x.ant.design/components/tabs-cn/#API)

### Steps to reproduce

从一个带有tabs的页面切换到另一个不带tabs的页面，控制台报错了
```
index.js:315 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
```

### What is expected?

正常运行不报错

### What is actually happening?

```
var btnNode = tabListRef.current.querySelector("[data-node-key=\"".concat(key, "\"]")); 这行js报错
```

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 18.0.2 |
| System | mac |
| Browser | chrome108 |

**Comment by wangyingjie123** [comment]
还原回4.30以前版本了，你们再好好测试吧，自从改了item一堆问题

**Comment by afc163** [comment]
<img width="884" alt="图片" src="https://user-images.githubusercontent.com/507615/210722199-a62f5893-05a5-4cf9-8227-806dc612ccc6.png">

我本地也发现这个问题了，反复修改 hmr 之后出现。

**Comment by zombieJ** [comment]
https://github.com/react-component/tabs/blob/785422dc5d9ae69cba968e83be001f94bd559f1e/src/TabNavList/index.tsx#L110

推测是 `raf` 更新在 unmount 没有清理 raf。

**Comment by afc163** [comment]
antd 里的依赖版本也升级上来吧。

**Comment by MadCcc** [comment]
发的 patch，不用改 antd 了吧

**Comment by afc163** [comment]
改吧，免得有些项目 lock 了。

**Comment by anjan-rpf** [comment]
@afc163  Facing the same issue in antd@5.1.4

Error: 
> Uncaught TypeError: Cannot read properties of null (reading 'querySelector')

Should I open a new issue?

<img width="624" alt="Screenshot 2023-01-12 at 12 51 59 PM" src="https://user-images.githubusercontent.com/106671988/212004490-fa93831e-3545-4c69-a579-072103340895.png">

**Comment by hfknight** [comment]
It is still happening on antd@5.1.7

**Comment by afc163** [comment]
@hfknight Could you provide a reproduce demo?
