### ISSUE TITLE
Improvement for the Badge component

### ISSUE THREAD

**Issue by MichaelSavin** [ant-design/ant-design#3999]
The Badge component could be usefull as a delete icon like 
![image](https://cloud.githubusercontent.com/assets/1640229/20594861/8ea95416-b259-11e6-8160-7d036fdece08.png)
Can I set this status?

**Comment by benjycui** [comment]
I don't think this could be a feature of Badge.

And it's easy to implement with Icon.

**Comment by MichaelSavin** [comment]
I think that we should add SVG property, not just the Text or Count
