### ISSUE TITLE
pickrange disabledDate时间范围为年时，会重复执行上万次，导致很卡

### ISSUE THREAD

**Issue by zero-npm** [ant-design/ant-design#39991]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ze-bu-chao-guo-qi-tian-de-fan-wei-antd-5-1-2-forked-wiqnk3?file=/demo.tsx)

### Steps to reproduce

官方组件选择不超过七天的时间的示例，修改为不超过3年的时间，选择时间，查看控制台打印数据

### What is expected?

选择年时和选择日一样流畅

### What is actually happening?

选择第一个日期后，后卡很久，控制台一直循环打印

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 16.14.0 |
| System | windows |
| Browser | google |

**Comment by kiner-tang** [comment]
看情况是出现了死循环了

**Comment by kaisa911** [comment]
> 看情况是出现了死循环了 ![屏幕录制2023-01-04 09 16 51 mov](https://user-images.githubusercontent.com/10286961/210467132-36cf6657-8b6f-46a7-9e2b-6cbb576ab237.gif) [ ![屏幕录制2023-01-04 09 16 51 mov](https://user-images.githubusercontent.com/10286961/210467132-36cf6657-8b6f-46a7-9e2b-6cbb576ab237.gif) ](https://user-images.githubusercontent.com/10286961/210467132-36cf6657-8b6f-46a7-9e2b-6cbb576ab237.gif) [ ](https://user-images.githubusercontent.com/10286961/210467132-36cf6657-8b6f-46a7-9e2b-6cbb576ab237.gif)

没有死循环，只是重复的次数多，大概5w多次就停了

**Comment by kaisa911** [comment]
> > 看情况是出现了死循环了 ![屏幕录制2023-01-04 09 16 51 mov](https://user-images.githubusercontent.com/10286961/210467132-36cf6657-8b6f-46a7-9e2b-6cbb576ab237.gif)
> 
> 没有死循环，只是重复的次数多，大概5w多次就停了


感觉是在计算disabledDate的时候，年度的都会转成日度来算，就会有走很多个365遍比较，于是就会卡顿。

加个map 记录一下，应该会省一些时间？
```
import React, { useState } from 'react';
import './index.css';
import { DatePicker } from 'antd';
import type { Dayjs } from 'dayjs';

const { RangePicker } = DatePicker;

type RangeValue = [Dayjs | null, Dayjs | null] | null;
interface YearValue {
  [propName: string]: boolean;
}

const App: React.FC = () => {
  const [dates, setDates] = useState<RangeValue>(null);
  const [value, setValue] = useState<RangeValue>(null);
  const [yearMap, setYearMap] = useState<YearValue>({});

  const disabledDate = (current: Dayjs) => {
    const currentYear = current.format('YYYY');
    const tempList = Object.keys(yearMap);
    if (!dates || (!dates[0] && !dates[1]) || tempList.includes(currentYear)) {
      if (tempList.includes(currentYear)) {
        return yearMap[currentYear];
      }
      return false;
    }

    const date0Year = dates[0]?.format('YYYY') || '';
    const date1Year = dates[1]?.format('YYYY') || '';

    const tooLate = dates[0] && Number(currentYear) - Number(date0Year) > 7;
    const tooEarly = dates[1] && Number(date1Year) - Number(currentYear) > 7;

    const map = yearMap;
    map[currentYear] = !!tooEarly || !!tooLate;
    setYearMap(map);
    console.log(1, currentYear, date0Year, date1Year, tooEarly, tooLate);

    return !!tooEarly || !!tooLate;
  };

  const onOpenChange = (open: boolean) => {
    if (open) {
      setDates([null, null]);
    } else {
      setDates(null);
      setYearMap({});
    }
  };
  return (
    <RangePicker
      picker={'year'}
      value={dates || value}
      disabledDate={disabledDate}
      onCalendarChange={(val) => setDates(val)}
      onChange={(val) => setValue(val)}
      onOpenChange={onOpenChange}
    />
  );
};

export default App;

```

**Comment by yuyeqianxun** [comment]
[demo](https://codesandbox.io/s/jin-yong-antd-5-6-3-forked-55cgpm?file=/demo.js)
为什么这个问题有好多次类似issue，但始终没人解决呢

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
