### ISSUE TITLE
react-dom支持

### ISSUE THREAD

**Issue by ascoders** [ant-design/ant-design#400]
将React.render换成ReactDom.render
否则会报错 `React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead`

**Comment by benjycui** [comment]
因为你用的是 React@0.14.x，已经在跟进了：https://github.com/ant-design/ant-design/issues/243

另外，这个不是报错，只是因为 React@0.14.x 用 `console.error` 输出 warning，所以在 React@0.14.x 下用 `React.render` 的话，功能仍然是正常的。
