### ISSUE TITLE
Ant theme custom tokens v5

### ISSUE THREAD

**Issue by fihorvat** [ant-design/ant-design#40006]
### What problem does this feature solve?

The main issue is that we need a few background tokens that we could change and that would not change the other components.
In the documentation, I found these variables for the background: `colorBgContainer, colorBgElevated, colorBgLayout, colorBgSpotlight, colorBgMask`. The problem with these tokens is that we cannot use them as primary, secondary, tertiary and quaternary backgrounds for custom components or use them as background for custom container components, and by changing them we change how antd components look.
In v4 we had a custom logic that parsed the `less` files to extract `less variables` and then we could override variables or define new variables. Then we exported this to files for each theme.

So we had more flexibility for migration from v3 to v4. Now it looks like we need to have another definition file (for each theme) and then custom logic that would merge antd tokens with our custom variables. This also means that we cannot use `theme.useToken()` and need to have some custom implementation for that.

### What does the proposed API look like?

- The best solution (and future-proof) would be that we have the ability to modify `ThemeConfig` so that it allows us to define custom variables in the theme file and we could get them with `theme.useToken()`. Maybe not the whole `ThemeConfig` but `ThemeConfig.token` this would mean that type cannot be hardcoded to `token?: Partial<AliasToken>` but it should be generic or inferred.

Maybe something like this:
```ts
interface ThemeConfig<T = unknown> {
  token?: Partial<AliasToken> & T;
  components?: OverrideToken;
  algorithm?: MappingAlgorithm | MappingAlgorithm[];
  hashed?: boolean;
  inherit?: boolean;
}

type CustomVariables = {
  colorBg: string;
  colorBgSecondary: string;
  colorBgTertiary: string;
  colorBgQuaternary: string;
};

const theme: ThemeConfig<CustomVariables> = {
  token: {
    colorPrimary: '#1a6ae3',
    colorBgMask: 'rgba(34, 46, 84, 0.95)',
    colorBg: '#FFFFFF',
    colorBgSecondary: '#F3F4F9',
    colorBgTertiary: '#E5E7EB',
    colorBgQuaternary: '#D1D5DB',
  },
  components: {
    Tabs: {
      fontSize: 12,
    },
  },
  algorithm: antTheme.defaultAlgorithm,
};

export default theme;

```

- If not, for now, it would be ok to create 4 new tokens the same as we have for text components. (`colorText, colorTextSecondary, colorTextTertiary, colorTextQuaternary`)
Something like this:
```js
colorBg,
colorBgSecondary,
colorBgTertiary,
colorBgQuaternary
```

**Comment by MadCcc** [comment]
Just wrap these custom tokens in your custom hooks? 
Like this:
```
const useMyToken = () => {
  const { token } = theme.useToken();
  return {
    ...token,
    colorBg: '#FFFFFF',
    colorBgSecondary: '#F3F4F9',
    colorBgTertiary: '#E5E7EB',
    colorBgQuaternary: '#D1D5DB',
  };
}
```

**Comment by fihorvat** [comment]
@MadCcc That would work perfectly fine if we only use one theme.
We would need to have some custom logic that would sync multiple fliles and themes.
The issue is that we need this tokens to change for each theme. Like for default (light) theme colors will be lighter and for dark they will be darker.
That is why it makes sense for custom colors to be inside theme config.
Is it a big change to allow defining a type for custom colors and just spreading what came from theme config into generated tokens?
This way everything closely related to theme would be in one file which is great.

**Comment by fihorvat** [comment]
@MadCcc if that is easier maybe something like this would suffice:

```
interface ThemeConfig<T = unknown> {
  token?: Partial<AliasToken>;
  customTokens?: T;
  components?: OverrideToken;
  algorithm?: MappingAlgorithm | MappingAlgorithm[];
  hashed?: boolean;
  inherit?: boolean;
}
```

And then after the theme is generated just spread custom tokens inside token collection.

**Comment by MadCcc** [comment]
> Since custom tokens will not be handled by antd, it is unncessary to put them into configuration.

In your PR, ConfigProvider did nothing to custom tokens and just put them into context. It's better to maintain these tokens by users, not ConfigProvider.

**Comment by fihorvat** [comment]
@MadCcc Could you at least spread all the keys from `ThemeConfig` that you didn't consume and return them back in `useToken()`?

Like if this is my theme definition:

```ts
type ExtendedThemeConfig = ThemeConfig  & { a: { b: string; }};
const theme: ExtendedThemeConfig = {
  token: {
    colorPrimary: '#1a6ae3',
  },
  components: { ... },
  algorithm: antTheme.defaultAlgorithm,
  a: {
    b: "test",
  }
};
```

And if I call:

```
const token = antdTheme.useToken();
console.log(token);
```

I would expect to see `a` object inside the token object.

**Comment by fihorvat** [comment]
@MadCcc Any updates on this?

**Comment by alramalho** [comment]
bump

**Comment by monolithed** [comment]
It's unclear why the ticket was closed. Supporting multiple custom tokens is essentially theming.
Without this functionality, we have to create wrappers around all components to pass the 'theme' property from the custom config. This introduces significant overhead, especially for landing pages, where there are typically numerous color blocks.

If someone needs a workaround, here it is below. It's a mess that increases code size, makes it confusing, and doesn't transfer well to other projects, unlike how it's done in MUI, where they [offer alternative solutions](https://mui.com/joy-ui/customization/approaches/).

```tsx
// thems.ts

enum Themes {
    PRIMARY = 'primary',
    GREEN = 'green',
    YELLOW = 'yellow',
    VIOLET = 'violet',
}

const selectTheme = (name: Themes): ThemeConfig => ({
    [Themes.PRIMARY]: {}
    [Themes.YELLOW]: {
        components: {
            Button: {}
        }
    }
}[name]);
}

export {Themes, selectTheme};
```

```css
// button.module.css

.primary.theme--yellow {
    border-color: #F6F6F6 !important;
}
```

```tsx
// button.tsx

import {
    Button as AntButton,
    ConfigProvider
} from 'antd';

const Button: React.FunctionComponent<Props> = ({
    children,
    className,
    theme = Themes.PRIMARY,
    ...props
}) => {
    const config = selectTheme(theme);

    const classes = cn([
        styles[`theme--${theme}`],
        className
    ], {
        [styles.primary]: primary
    })

    return (
        <ConfigProvider theme={config}>
           <AntButton className={classes} {...props} />
        </ConfigProvider>
    )
};

export {Button};
```

```tsx
// your-code.tsx

<Button  theme={Themes. YELLOW}>Click</Button>
```

**Comment by FeNoMeNa** [comment]
One hacky way to get the theme configuration is by getting it from the context which is used under the hood:

```js
import { useContext } from 'react';
import { ConfigProvider } from 'antd';

export const CustomComponent = () => {
	const config = useContext(ConfigProvider.ConfigContext)
	console.log(config);
}
```

**Comment by bolshchikov** [comment]
I found that this is the best way to extend it:

1. Create customToken.d.ts file to extend the theme (necessary to `theme.useToken()` method)
```ts
import '@ant-design/cssinjs';
import 'antd/es/theme/interface';

declare module 'antd/es/theme/interface' {
  export interface GlobalToken {
    secondary30: string;
    secondary40: string;
    secondary50: string;
    secondary60: string;
    secondary70: string;
    secondary80: string;
    secondary90: string;
  }
}
```
2. Create theme config
```ts
export default <ThemeConfig>{
  token: { 
    // Custom tokens
    secondary30: '#8F1E69',
    secondary40: '#B52986',
    secondary50: '#C14B9A',
    secondary60: '#C961A6',
    secondary70: '#E291C7',
    secondary80: '#F7CBE9',
    secondary90: '#F7EDF4',
  },
  components: {
    ...
  },
};
```
3. Use via hook
```ts
const {
  token: { secondary40 },
} = theme.useToken();
```

**Comment by istvan73** [comment]
> I found that this is the best way to extend it:
> 
> 1. Create customToken.d.ts file to extend the theme (necessary to `theme.useToken()` method)
> 
> import '@ant-design/cssinjs';
> import 'antd/es/theme/interface';
> 
> declare module 'antd/es/theme/interface' {
>   export interface GlobalToken {
>     secondary30: string;
>     secondary40: string;
>     secondary50: string;
>     secondary60: string;
>     secondary70: string;
>     secondary80: string;
>     secondary90: string;
>   }
> }
> 2. Create theme config
> 
> export default <ThemeConfig>{
>   token: { 
>     // Custom tokens
>     secondary30: '#8F1E69',
>     secondary40: '#B52986',
>     secondary50: '#C14B9A',
>     secondary60: '#C961A6',
>     secondary70: '#E291C7',
>     secondary80: '#F7CBE9',
>     secondary90: '#F7EDF4',
>   },
>   components: {
>     ...
>   },
> };
> 3. Use via hook
> 
> const {
>   token: { secondary40 },
> } = theme.useToken();

It looks to me like it overrides the default tokens.
