### ISSUE TITLE
期望：Table -> th 表格组件的表头期望不添加width等api props，默认情况不折行（white-space: nowrap），通常业务场景下也是不希望表头有折行的情况

### ISSUE THREAD

**Issue by louhaojie99** [ant-design/ant-design#40007]
### Reproduction link

[https://xxxx](https://xxxx)

### Steps to reproduce

很平常现象

### What is expected?

期望：Table -> th 表格组件的表头期望不添加width等api props，默认情况不折行（white-space: nowrap），通常业务场景下也是不希望表头有折行的情况

### What is actually happening?

有 td 被其他 td 拥挤的时候，会出现表头折行

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | mac os |
| Browser | chrome.xxx |

**Comment by afc163** [comment]
我们无法预设是否需要折行，有些定宽的 column 的标题比较长时是希望正确折行。这个交给业务自行决定就好，我们不预设样式。
