### ISSUE TITLE
Build failed with Error: Can't resolve 'antd/lib/locale-provider/en_US'

### ISSUE THREAD

**Issue by tnsivanagarajan** [ant-design/ant-design#40008]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

build failed

### What is expected?

build should pass

### What is actually happening?

When I use latest version of antd current project build failed. 

antd version: 5.1.2

Module not found: Error: Can't resolve 'antd/lib/locale-provider/en_US' in '/home/administrator/**/node_modules/react-awesome-query-builder/lib/config/antd'

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | "react": "^16.14.0", |
| System | Ubuntu, windows 10 |
| Browser | firefox, chrome |

**Comment by IndhuKandhaiya** [comment]
@tnsivanagarajan Yes, I'm also facing the same issue.

**Comment by afc163** [comment]
`locale-provider` had been deprecated in antd@3.x years ago, you should not depend on it's file path.
