### ISSUE TITLE
Best way to make all the components bigger?

### ISSUE THREAD

**Issue by Altiano** [ant-design/ant-design#4000]
I can't find any documentation of how to do this. So, I just think that someone could help me if I ask here.

I want to make the components like Button and Checkbox bigger because my site doesn't really have that many controls so bigger components would make it more recognisable.

**Comment by benjycui** [comment]
Try `size` property or customized theme https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme

**Comment by Hesesses** [comment]
ant-design looks super nice, but I was also wondering why the components are so small. I would say the `size=large` feels small to me. Default and small feels xxxx-small...

I hope there would be easy way to scale everything up

**Comment by acomito** [comment]
@benjycui I was able to make the checkbox larger, but the check icon is now off center. Do you know where that code is? I need to make it bigger or center it.


![screen shot 2017-07-16 at 10 55 51 am](https://user-images.githubusercontent.com/12701635/28248615-6b30fcae-6a15-11e7-83db-ab986893e271.png)

**Comment by acomito** [comment]
UPDATE:

Sorry, found it: .ant-checkbox-inner:after

**Comment by hardav31** [comment]
https://ant.design/docs/spec/icon
if you want to do bigger icons,you should change your font-size of <i>  
i{
font-size:20px;
}

**Comment by wangxingxing123654** [comment]
> @benjycui I was able to make the checkbox larger, but the check icon is now off center. Do you know where that code is? I need to make it bigger or center it.
> 
> ![screen shot 2017-07-16 at 10 55 51 am](https://user-images.githubusercontent.com/12701635/28248615-6b30fcae-6a15-11e7-83db-ab986893e271.png)

但是不能居中啊。中间那个勾。    打完包以后更加不居中 了

**Comment by keithort** [comment]
@wangxingxing123654 The css class you need to target is `.ant-checkbox-inner::after`. https://github.com/ant-design/ant-design/blob/master/components/checkbox/style/mixin.less#L58
