### ISSUE TITLE
tagFontSize doesnt work in seed token config

### ISSUE THREAD

**Issue by woutqargo** [ant-design/ant-design#40016]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4rvijl?file=/index.js)

### Steps to reproduce

Use the ant ConfigProvider with tagFontSize

### What is expected?

When changing tagFontSize the tag font size is changed

### What is actually happening?

When changing tagFontSize the tag font size doesn't change

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 17.0.2 |
| System | macOS 12.5.1 |
| Browser | Chrome 108.0.5359.124 |

---
This might be intented?

**Comment by MadCcc** [comment]
We do not have `tagFontSize` in Design Token. You could customize in this way:
```
<ConfigProvider theme={{ components: { Tag: { fontSizeSM: 40 } } }}>
```
