### ISSUE TITLE
期待Progress能支持top进度条，用于展示当前操作的进度

### ISSUE THREAD

**Issue by pixystone** [ant-design/ant-design#4001]
比如接口可以类似`Progress.start()`，`Progress.stop()`这样的

**Comment by benjycui** [comment]
现在不也可以么。。只是没有动画。

**Comment by benjycui** [comment]
你需要的是这种？ http://ricostacruz.com/nprogress/

**Comment by pixystone** [comment]
Right! thanks

**Comment by benjycui** [comment]
直接使用 NProgress 即可，不觉得有集成及 antd 的必要。
