### ISSUE TITLE
ToolTip组件在鼠标移到上面时需要自动关闭

### ISSUE THREAD

**Issue by lnstock** [ant-design/ant-design#40011]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9pzo4o)

### Steps to reproduce

button在鼠标移动上去时会出现tooltip，但是鼠标移动到tooltip上时会挡住底层的按钮，导致无法点击

### What is expected?

鼠标移到上面时需要自动关闭

### What is actually happening?

鼠标移到上面时没有自动关闭

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | windows11 |
| Browser | Edge |

**Comment by kiner-tang** [comment]
如果不想让鼠标移动到`tooltip`上面，设置移出延迟时间为0即可：
```tsx
<div className="App">
  <h1>antd version: {version}</h1>
  <div style={{ width: 100 }}>
    {Array.from({ length: 40 }).map((x, i) => (
      <Tooltip key={i} title="TEST" mouseLeaveDelay={0}>
        <Button>TEST</Button>
      </Tooltip>
    ))}
  </div>
</div>
```

**Comment by lnstock** [comment]
可以，多谢了
