### ISSUE TITLE
DatePicker/RangePicker no longer accept manual input of dates

### ISSUE THREAD

**Issue by zaneadix** [ant-design/ant-design#40020]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

Manually type in a date and press enter. Nothing happens. 
Manually type in a date and click off of the field, value disappears.

### What is expected?

In previous version of Ant (v4 that I know of), manually typing in a date and pressing enter would set the DatePicker field value and format it properly.

### What is actually happening?

Trying to manually enter a date in a DatePicker of RangePicker no longer works.

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome 108.0.5359.124 |

---
In addition to this issue, I went to to the documentation to see if this happened there. I noticed another issue.
It seems that the documentation has a "keyword search" feature that opens a modal upon pressing the '/' key. 
If I'm trying to manually type in a date in a DatePicker and i press the '/' key, the DatePicker loses focus and that search modal takes over. This is not ideal. 

This happens in the v5 docs: https://ant.design/components/date-picker#components-date-picker-demo-format
But not in the v4 docs: https://4x.ant.design/components/date-picker/#components-date-picker-demo-range-picker

**Comment by Yuiai01** [comment]
Hello, when I tried to reproduce the problem you mentioned, I found that it is feasible to enter the date manually. For example, if I enter 2023-01-05, the date will be displayed in the input box and selected.

**Comment by MadCcc** [comment]
I could type in and select date too.

**Comment by zaneadix** [comment]
I'm realizing now that the manually entered value must directly match the provided format. 
My input format was set to `MM/DD/YYYY` and I was entering `8/1/1987`.
While I guess technically the field is working, this still stands out to me as a strange user experience issue. 
With some more testing, I'm noticing another strange quirk.

If the field is initially blank and I manually type the value `2023-1-1` and press enter, nothing happens. 
If the field already has a value like `2023-01-05` and I manually type `2023-1-1` and press enter, it reverts to the value `2023-01-05`.

Both instances above provide no feedback to the user as to why they happen and just aren't consistent. 

I understand this could likely be alleviated with placeholder text and validation feedback but as a base experience is weirdly frustrating to interact with.

**Comment by zombieJ** [comment]
It's caused by dayjs must align the format as validate. You can extends dayjs format logic instead : )

**Comment by vitalijalbu** [comment]
How i can do that? didn't get it..

**Comment by rwilliams3088** [comment]
Running into this same issue...
