### ISSUE TITLE
Transfer 组件不支持非受控模式

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/ant-design#40031]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-gauss-hx9b7r?file=/src/index.tsx)

### Steps to reproduce

之前将 Transfer 组件由 `class component` 重构为 `function component`，在重构的过程中发现 Transfer 不支持非受控模式，为了不造成其它影响，重构时还是保留了原有的逻辑

### What is expected?

支持非受控模式

### What is actually happening?

不支持非受控模式

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
非受控的使用场景是？

**Comment by li-jia-nan** [comment]
就是想让组件本身接管数据，无需自己管理？
（其实我也没遇到非受控的场景，只是在偶然间发现了这个bug）
