### ISSUE TITLE
How to checkbox All with different Id using ant with reactjs

### ISSUE THREAD

**Issue by Quocphu123** [ant-design/ant-design#40034]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-select-all-checkbox-forked-wy8bgt)

### Steps to reproduce

1. Check the checkbox with value all
2. All the remaining checkboxes with value all are checked

### What is expected?

1. All same-line values are checked
2. get the result 
```
 [
     {id:'1' ,  key: "view"  }, 
     {id:'1' ,  key: "add"  }, 
     {id:'1' ,  key: "edit"  }, 
     {id:'1' ,  key: "delete"  }, 
   ]
```

### What is actually happening?

Can't recognize which line's checkbox all

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | Reactjs version 18.2.0 |
| System | Windows 10 |
| Browser | Google Chrome 108 |

**Comment by afc163** [comment]
It is not a antd issue, you should resolve by youself.
