### ISSUE TITLE
Menu导航菜单收起状态自定义展开图标依然存在

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#40041]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kvcn9q?file=/index.js)

### Steps to reproduce

1. <Menu>组件添加自定义图标expandIcon={<DownOutlined />}
2. 点击收起按钮
3. 自定义图标依然存在

### What is expected?

Menu导航菜单在收起状态时，自定义图标应该消失

### What is actually happening?

Menu导航菜单收起状态自定义时，展开图标依然存在

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | "react": "^18.2.0" |
| System | win10 |
| Browser | chrome108 |

**Comment by Wxh16144** [comment]
我来尝试修复一下～
