### ISSUE TITLE
Menu item group titles are not readable when using the dark theme in Ant Design 5 because the text color is dark as well

### ISSUE THREAD

**Issue by doomlaur** [ant-design/ant-design#40049]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/top-navigation-antd-5-1-2-forked-8hdm4e?file=/demo.tsx)

### Steps to reproduce

1. Check out the documentation for "Menu" and look at the first example: https://ant.design/components/menu
2. Hover with the mouse over "Navigation Three - Submenu" -> everything looks nice, as it uses the light theme.
3. Open the same example in my CodeSandbox example, which uses the dark theme: https://codesandbox.io/s/top-navigation-antd-5-1-2-forked-8hdm4e?file=/demo.tsx
4. Hover again with the mouse over "Navigation Three - Submenu" -> the text for "Item 1" and "Item 2" almost cannot be seen, because both the background and the text use a dark color.

### What is expected?

The text should be visible in the dark theme as well, so it should use a lighter color.

### What is actually happening?

The text color is too dark to be seen on the dark background.

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | Windows 10 22H2 |
| Browser | Brave 1.46.144 (based on Chromium 108.0.5359.128) / Firefox 108.0.2 |

**Comment by afc163** [comment]
Here is 4.x style.

<img width="675" alt="图片" src="https://user-images.githubusercontent.com/507615/210917910-93200de8-8d72-401d-a2ba-8cbfc8e4db26.png">

**Comment by MadCcc** [comment]
Working on it now.

**Comment by doomlaur** [comment]
Perfect, thank you! 😄
