### ISSUE TITLE
Layout 菜单建议增加 API 可以隐藏 tooltip 提示

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#40044]
### What problem does this feature solve?

Layout 菜单建议增加 API 可以隐藏 tooltip 提示

![994717c4ef07de53c1c117a7d1dfbe3d_210708707-5c769c73-5d54-495d-8842-907f6601195e](https://user-images.githubusercontent.com/3166799/210774430-b4b1abb0-3347-4ae7-9153-720c78d7d4a9.png)

**Comment by peterleng** [comment]
+1
菜单收起时，已经有了子菜单的popup，再出现tooltip很奇怪，会有两个元素重叠在一起。
