### ISSUE TITLE
Cascader notFoundContent onClick event does not take effect

### ISSUE THREAD

**Issue by wangjiaojiao77** [ant-design/ant-design#40059]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4zgbo9?file=/index.js)

### Steps to reproduce

When no content is found in the input box, the custom notFound content will be displayed. I added a click event to this content, but the click does not take effect

### What is expected?

addItem function take effect

### What is actually happening?

addItem function does not take effect

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | macOS 12.5.1 |
| Browser | Chrome  108.0.5359.124 |

**Comment by zwtkito** [comment]
![image](https://user-images.githubusercontent.com/85665962/210942844-7649b296-b2ae-437b-9df0-c9a070026598.png)
Maybe you can try to override this css

**Comment by wangjiaojiao77** [comment]
> ![image](https://user-images.githubusercontent.com/85665962/210942844-7649b296-b2ae-437b-9df0-c9a070026598.png) you can try to override this css

I'll try it, thanks a lot!
