### ISSUE TITLE
Upload组件，disabled属性为true时，只是上传按钮不可用，文件列表还是可删除的。

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#4005]
示例代码：http://codepen.io/zhulichao/pen/zozBmj 。个人认为组件不可用时应该是不可编辑的，包括文件列表，要保持现在这样吗？

**Comment by afc163** [comment]
先保持现状吧，Upload 的属性目前更偏向于触发按钮，UploadList 里的属性才是列表元素的属性。
