### ISSUE TITLE
Unexpected default value in Select in conjunction with Steps

### ISSUE THREAD

**Issue by kapolos** [ant-design/ant-design#40052]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-violet-zpp9xt?file=/src/App.js)

### Steps to reproduce

Click "Next".

### What is expected?

The default value on Step 2 should have been "CCCCCC".

![image](https://user-images.githubusercontent.com/10794126/210861541-d2d26a06-85c1-4668-8286-f45e05ff2a49.png)

### What is actually happening?

It is "AAAAA", which does not exist in the Select button of Step 2.

![image](https://user-images.githubusercontent.com/10794126/210861467-7c7a0ca5-5ba9-40f1-8a5f-9987a822e071.png)

![image](https://user-images.githubusercontent.com/10794126/210861918-da58e46f-11fc-47d4-b680-ff3517a865b5.png)

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | Linux |
| Browser | Chrome |

---

Amazingly, if you replace `<div> ... </div>` with `<> ... </>` on Step 2 content, it works as expected :o

It also works fine if I define the content value into its own component (`content: <Step2Content>`), instead of directly into the array.

**Comment by afc163** [comment]
```
console.log({ value: "a", label: "AAAAA" } === { value: "a", label: "AAAAA" }) // false;
```

**Comment by kapolos** [comment]
@afc163 Thank you for looking into it. Two notes: 

a) Changing the `defaultValue` does **not** fix the reported issue. I've updated the code in the [sandbox](https://codesandbox.io/s/hopeful-violet-zpp9xt?file=/src/App.js), the wrong behavior is the same:

![image](https://user-images.githubusercontent.com/10794126/210933143-3760d3ff-9529-4871-848a-bd1f11f60b12.png)

![image](https://user-images.githubusercontent.com/10794126/210933367-ea433d96-e6a9-4856-b493-f5c42cb3f81a.png)

b) According to the [documentation](https://ant.design/components/select#select-props), the `defaultValue` **does** accept a non-primitive, so maybe there's a mistake there?

![image](https://user-images.githubusercontent.com/10794126/210932790-fbcdf6d1-ee34-4c1b-b990-e9f4c79bfe60.png)

![image](https://user-images.githubusercontent.com/10794126/210933015-4d2aa36c-ebe8-4970-89c0-d2df0c03249e.png)

**Comment by afc163** [comment]
> b) According to the [documentation](https://ant.design/components/select#select-props), the defaultValue does accept a non-primitive, so maybe there's a mistake there?

You should enable `labelInValue` in this case.

**Comment by afc163** [comment]
> a) Changing the defaultValue does not fix the reported issue. I've updated the code in the [sandbox](https://codesandbox.io/s/hopeful-violet-zpp9xt?file=/src/App.js), the wrong behavior is the same:

You are right, I will dig into it.

**Comment by kapolos** [comment]
@afc163 Thank you!
