### ISSUE TITLE
Progress 建议新增一个去掉动画的属性，否则在 requestAnimationFrame 中会出现进度停滞的现象

### ISSUE THREAD

**Issue by woowalker** [ant-design/ant-design#40056]
### What problem does this feature solve?

可以参见例子：https://stackblitz.com/edit/react-udphnl?file=demo.tsx

点击空白处，进度就停了，F12把ant-progress-bg的transition关掉，就不会了

### What does the proposed API look like?

```GIT
<Progress animation={false} />
```

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-udphnl-xxpv9q?file=demo.tsx

You can try ConfigProvider `theme`.
