### ISSUE TITLE
DatePicker国际化月份、周仍然展示英文

### ISSUE THREAD

**Issue by FaberSober** [ant-design/ant-design#40075]
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-w2w6rj?file=src/App.tsx](https://stackblitz.com/edit/vitejs-vite-w2w6rj?file=src/App.tsx)

### Steps to reproduce

```
import { ConfigProvider, DatePicker } from 'antd';
import zhCN from 'antd/locale/zh_CN';

function App() {
  return (
    <ConfigProvider locale={zhCN}>
      <div className="App">
        <DatePicker />
      </div>
    </ConfigProvider>
  );
}
```

### What is expected?

日期面板全部展示中文

### What is actually happening?

部分展示中文，月份、周仍然展示英文

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | win11 |
| Browser | Google Chrome 108.0.5359.125（正式版本） （64 位） |

**Comment by FaberSober** [comment]
![image](https://user-images.githubusercontent.com/8201946/211020097-d8081e09-9d3b-4b71-ac09-43f083358126.png)

![image](https://user-images.githubusercontent.com/8201946/211020153-744c6ec7-e5c3-420a-a961-907d44706eb5.png)

**Comment by zombieJ** [comment]
```tsx
dayjs.locale('zh-cn');
```

https://ant.design/components/config-provider-cn#components-config-provider-demo-locale

**Comment by FaberSober** [comment]
整理了下，问题已解决。使用的是`vite4.0.4`+`antd5.1.2`+`dayjs1.11.7`
1. 在package.json中安装dayjs；
2. 国际化使用如下代码：
```js
import { ConfigProvider, DatePicker } from 'antd';
// vite打包国际化丢失，需要使用es目录下的locale文件
import zhCN from 'antd/es/locale/zh_CN';

import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
dayjs.locale('zh-cn');

function App() {
  return (
    <ConfigProvider locale={zhCN}>
      <div>
        <DatePicker />
      </div>
    </ConfigProvider>
  );
}

export default App;
```

示例代码在：
https://stackblitz.com/edit/vitejs-vite-zev9gs?file=src/App.tsx
