### ISSUE TITLE
Tooltip Inverting preset colors does not work

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#40072]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-cai-wen-zi-ti-shi-antd-5-1-2-forked-q6kbvi?file=/demo.tsx)

### Steps to reproduce

open CodeSandbox link

### What is expected?

The documentation does not indicate whether or not this is supported

1. if the design is such that it is not supported, the class name `{color}-inverse` should not be displayed, and the TS type derivation should be narrowed

2. If the color is in the design, I can file a [PR](https://github.com/ant-design/ant-design/pull/39742/commits/d89d8cdd9ddd428fffb91f703ae066825d455950) to fix it, as mentioned before

### What is actually happening?

Default colors are displayed

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | any |
| System | any |
| Browser | any |

**Comment by MadCcc** [comment]
Not planned yet.
