### ISSUE TITLE
Table在Chrome中展示数据，顺序错位

### ISSUE THREAD

**Issue by importcjj** [ant-design/ant-design#4007]
#### 发生问题的环境是：

- antd 版本:^2.1.0
- 操作系统及其版本: mac os x 10.11.4
- 浏览器及其版本: chrome 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

Table数据展示

#### 您期待的结果是:

![](http://7xna17.com1.z0.glb.clouddn.com/4A759CAE-0228-4CA4-A1FE-7EE04D671CD9.png)
#### 实际上的结果是:

![](http://7xna17.com1.z0.glb.clouddn.com/AE297D0D-404D-4511-AC6E-1E1456B3F7B9.png)

#### 问题描述:

如上图所示，后端返回的数据按照红框中的时间默认排序。然而Table组件在展示是发生问题。在safari和firefox中均能正常展示，然而在chrome中却出现了数据错位。

**Comment by yesmeck** [comment]
能给个重现吗？ http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zhengqingxin** [comment]
我也遇到这个问题了，怎么解决的呢？ @importcjj
