### ISSUE TITLE
短时间多次点击同一个 message 信息提示，key 相同时候，toast 不消失

### ISSUE THREAD

**Issue by running-little-snail** [ant-design/ant-design#40076]
### Reproduction link

https://codesandbox.io/s/antd-reproduction-template-forked-hqjor1?file=/index.js:340-602

### Steps to reproduce

使用 message.success({
key:"test",
duration:3,
content:"测试快速多次点击"
})

### What is expected?

toast 正常消失

### What is actually happening?

连续快速多次点击之后，toast 一直显示，没有消失

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | deepin |
| Browser | chrome |

## sandbox code

```
import React, { useEffect } from "react";
import { createRoot } from "react-dom/client";
import { Button, version, message } from "antd";
import "antd/dist/reset.css";
import "./index.css";

const App = () => {
  const onClick = () => {
    message.success({
      key: "test",
      content: "toast info",
      duration: 2
    });
  };

  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <Button type="primary" onClick={onClick}>
        Primary Button
      </Button>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);

```

**Comment by kiner-tang** [comment]
好像确实有问题，我看来一下

**Comment by running-little-snail** [comment]
> 好像确实有问题，我看来一下

好的，感谢。
