### ISSUE TITLE
SSR causes FOUC

### ISSUE THREAD

**Issue by quinn** [ant-design/ant-design#40087]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xoy3ic)

### Steps to reproduce

The sandbox should display the problem immediately. You can adjust the timeout ms to help demonstrate the problem.
 

### What is expected?

styles are supplied as an actual stylesheet, to be loaded as a `<link>` tag in the `<head>`. Styles are then visible before js has finished loading. 

### What is actually happening?

Styles are injected into the page inline, via js. 

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | Ubuntu |
| Browser | Firefox |

**Comment by quinn** [comment]
related: https://github.com/remix-run/remix/discussions/2756

**Comment by zombieJ** [comment]
Inline style is removed in latest version:
https://codesandbox.io/s/antd-reproduction-template-forked-4cxvhk?file=/package.json

**Comment by zombieJ** [comment]
And fully apply in SSR pls ref doc:
https://ant.design/docs/react/customize-theme#server-side-render-ssr

**Comment by zombieJ** [comment]
https://github.com/ant-design/cssinjs/pull/64

**Comment by quinn** [comment]
@zombieJ still seeing some problems with this: https://github.com/ant-design/ant-design/discussions/41783

**Comment by devbytyler** [comment]
Was a solution ever found for this? I been trying for a few days now to get dynamic themes working without FOUC, but have been unsuccessful.

**Comment by ruhleder** [comment]
@devbytyler Did you find a solution in the meanwhile? I'm struggling with the same problem and we're considering dropping ant-design because of it.
