### ISSUE TITLE
受控DatePicker删除日期时，出现Invalid date

### ISSUE THREAD

**Issue by antgod** [ant-design/ant-design#4008]
#### 发生问题的环境是：

谷歌浏览器最新版

- antd 版本:

2.4.1

- 操作系统及其版本:
mac
- 浏览器及其版本:
54

#### 您做了什么？请提供尽可能详细的重现步骤。

DatePicker受控，设置value以后，再点右侧x删除掉日期，结果出现Invalid date
调试： onChange里面的value已经变成Invalid Date

#### 您期待的结果是:

清空DatePicker

#### 实际上的结果是:

DatePicker显示Invalid date

#### 可重现的在线演示

http://site.alipay.net/cicada/cicada-engine/ 进入Select

**Comment by yesmeck** [comment]
例子不对？内网地址不要贴到这里来。

**Comment by benjycui** [comment]
尽量提供孤立的可重现 demo，带有业务代码的很难排查。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by 84538667** [comment]
受限的datepicker组件

![image](https://cloud.githubusercontent.com/assets/3725139/20654817/99f959aa-b557-11e6-97c2-9306f037ee18.png)

这个东西点击右边的xx

![image](https://cloud.githubusercontent.com/assets/3725139/20654826/abc453a6-b557-11e6-913a-aa7c7689c7a7.png)

就变成了这个样子，上面那个地址 进入datePick 就可以重现了....

**Comment by yesmeck** [comment]
现在要清空受控组件的值，需要把 `value` 设设成 `null`。

**Comment by afc163** [comment]
官网无法重现：https://ant.design/components/date-picker/#components-date-picker-demo-basic

**Comment by benjycui** [comment]
这里的都是受控的组件 https://ant.design/components/form/#components-form-demo-time-related-controls

测试正常。

**Comment by bf185003** [comment]
请看下面的例子：
http://riddle.alibaba-inc.com/riddles/9dfb5bbf?mode=jsx

**Comment by yesmeck** [comment]
应该清空的时候 onChange 接收到的是 null，不能传给 moment.

**Comment by benjycui** [comment]
已确认是用法问题，不是 bug。
