### ISSUE TITLE
Wrong rtl direction for Badge component

### ISSUE THREAD

**Issue by ds1371dani** [ant-design/ant-design#40090]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ecm2px?file=/index.js)

### Steps to reproduce

- Create a simple page with **ConfigProvider**'s direction set to `rtl`
- Add a **Badge** component whose child is an element with a display other than (inline*) like a `div`

### What is expected?

When `direction` is set to `rtl`, The **Badge** should be on the left side of **Badge's** child.

### What is actually happening?

When `direction` is set to `rtl`, The **Badge** won't move at all.

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Firefox 108.0 (64-bit) |

---
Is this intentional or should it be fixed? Since I wasn't sure I created this issue

**Comment by ds1371dani** [comment]
@li-jia-nan 
This issue is different from the pull request that I created.
 In the pull request the problem is only in the documentation because of the missing `direction` prop of ConfigProvider.
But even with the ConfigProvider correctly configured this issue persists, please check the reproduction link to see what I mean

**Comment by li-jia-nan** [comment]
reopen
