### ISSUE TITLE
只在Select 和 Input 组件组合使用时受 form 控制后赋值错误

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#40098]
### Reproduction link

[https://stackblitz.com/edit/react-arwra3?file=demo.tsx](https://stackblitz.com/edit/react-arwra3?file=demo.tsx)

### Steps to reproduce

```tsx
const App: React.FC = () => {
  const [form] = Form.useForm();
  return (
    <Form form={form}>
      {/* 当前受控表单出现此类问题 */}
      <Form.Item name="hmgIndexList" label="指数">
        <Space>
          <Form.Item noStyle name={['hmgIndexList', 0]}>
            <Select options={conditionOptions} style={{ width: '120px' }} />
          </Form.Item>
          <Form.Item noStyle name={['hmgIndexList', 1]}>
            <Input placeholder="请输入大于等于0的数量" />
          </Form.Item>
        </Space>
      </Form.Item>

      {/* 当前受控表单没有出现此类问题 */}
      <Form.Item name="omgIndexList" label="指数">
        <Space>
          <Form.Item noStyle name={['omgIndexList', 0]}>
            <Select options={conditionOptions} style={{ width: '120px' }} />
          </Form.Item>
          <Form.Item noStyle name={['omgIndexList', 1]}>
            <Select options={conditionOptions} style={{ width: '120px' }} />
          </Form.Item>
        </Space>
      </Form.Item>
    </Form>
  );
};
```

第一个受控表单右边 input 框中值的改变会影响 select 框中的值，并且会将 input 的值赋值给 select
第二个受控则不会出现第一个受控表单的问题
为什么需要给最外层的 Form.Item 配置 name , 这样我就可以将校验规则和normalize 写在最外层 Form.Item，以便同时控制这个复合的表单，而且初始值不会是 [null, null] 而是 null 。更有助于表单提交后对数据进行处理

### What is expected?

第一受控表单右边 input 框中值的改变不会影响 select 框中的值

### What is actually happening?

请不要急着关闭，我知道可以通过重新封装一个新的表单组件的方式实现这种复合的表单组件。但这不失为一种好的解决方式。
因为你提供了这种便利性，但这种便利性只在第一种复合情况下失效，我会认为这是 bug。你也可以试着去尝试其他可能

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 16.8.6 |
| System | windows11 |
| Browser | Google 100.0.4896.60 |

**Comment by afc163** [comment]
1. Input 和原生 input 一样，onChange 事件会向上冒泡。
2. onChange 会冒泡到 Space 组件上，本质是一个 div，这个 div 的 onChange 事件会触发。
3. Space 组件直接放在具有 name 属性的 Form.Item 下，因此这个 Space 会被视为是一个表单控件，onChange 会反应到 `<Form.Item name="hmgIndexList" label="指数">` 上。从而影响 `hmgIndexList[0]` 的值。就是 Select 会取 Input 里的 `string[0]` 值。

解决方案有三种：

1. 按你所描述的 `通过重新封装一个新的表单组件的方式实现这种复合的表单组件`。
2. 阻止 Input 冒泡事件：https://stackblitz.com/edit/react-arwra3-moukzs?file=demo.tsx
3. `<Form.Item label="指数">` 上不要加 name，避免把 Space 当成表单控件。
