### ISSUE TITLE
Bug with Nested <Space/> and <Menu/> components

### ISSUE THREAD

**Issue by JulesLecuir** [ant-design/ant-design#40094]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7yu728?file=/index.js)

### Steps to reproduce

Just launch the minimal repro.

### What is expected?

Nested Spaces should work with anything inside them

### What is actually happening?

It doesn't work with a \<Menu/> item inside it

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | Ubuntu 22.04.1 |
| Browser | Brave v 1.46.144 built on Chromium: 108.0.5359.128 (Official Build) (64-bit) |

---
Everything explained in the minimal repro.

**Comment by zombieJ** [comment]
Space is light way `inline-flex` layout component. Please use Col & Row for flex layout.
