### ISSUE TITLE
Datepicker. TreeSelect, Select等 slideUpIn  slideUpOut动画 在safari下聚焦，失焦动画问题、收起时闪烁，感观上多次播放，展开收起动画；

### ISSUE THREAD

**Issue by keyus** [ant-design/ant-design#40104]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

safari下，直接访问官网 日期组件, treeselect,select等组件，点击展示，收起

### What is expected?

修复动画效果

### What is actually happening?

动画闪烁

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2 |
| System | mac |
| Browser | safari 16.1 |

---
safari全系版本，

**Comment by afc163** [comment]
@zombieJ rc-motion 在 safari 下貌似有问题。

Image 关闭也会延迟一下 https://preview-40117-ant-design.surge.sh/components/image-cn

还有 Drawer 和 Modal https://github.com/ant-design/ant-design/issues/39995

**Comment by afc163** [comment]
<img width="370" alt="图片" src="https://user-images.githubusercontent.com/507615/211321882-ada89eb8-7191-4cf4-872a-c49b797a7efc.png">

1. DatePicker / Select 等弹层组件在 Safari 下打开会慢一拍。
2. 上门截图里这个年月字体偏小。

**Comment by afc163** [comment]
![Jan-20-2023 22-18-15](https://user-images.githubusercontent.com/507615/213721046-43d4f17d-fce6-42e2-b2ef-5f40981593ea.gif)

关闭后会跳好几次。

**Comment by IonelLupu** [comment]
I just got this issue too. 😭
