### ISSUE TITLE
Table Column is breaking column title

### ISSUE THREAD

**Issue by debotos** [ant-design/ant-design#40101]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-and-scroll-bar-with-the-page-antd-4-24-5-forked-m41flk?file=/demo.js)

### Steps to reproduce

1. Open the codesandbox link.
2. Reduce the preview window width.
3. You can see, instead of horizontal scrolling it's just breaking the column header and taking the the same width of a value cell.

### What is expected?

First it should set the column width to the column header cell width then if the any column value cell width is longer than header cell width it fall back to cell value width.

### What is actually happening?

When table header is sticky, scroll={{  x: 'max-content' }} and there is no width property specified in each column definition then unless column cell value width is bigger than column header title, column title is breaking(Simply, Column width is equal to max cell width without respecting the column header width).

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome 108 |

---
This situation is happening because of 'sticky'.
My row data & column definition is from remote API call and i want horizontal scrolling instead of 'Ellipsis' & don't wanna set hardcoded width to each column, fixed scrollX.

**Comment by storrella** [comment]
Same issue here. I had the 4.16 version installed on my project without issues but I wanted the sticky feature so I upgraded it to the latest v4 (4.24.7). With the new version the columns layout is broken if I don't specify a width for each column, buy only if `sticky` is set to `true` or a value of `scroll.y` is given. If I omit those parameters the layout doesn't get broken

**Comment by RedJue** [comment]
I'll fix it

**Comment by debotos** [comment]
Thanks a lot.

**Comment by debotos** [comment]
Hi @RedJue - Kindly let me know if there is any update. Thanks :)

**Comment by RedJue** [comment]
> Hi @RedJue - Kindly let me know if there is any update. Thanks :)

I will deal with this issue in a few days👀

**Comment by debotos** [comment]
> 

Thank You 🙏🏼

**Comment by debotos** [comment]
> > Hi @RedJue - Kindly let me know if there is any update. Thanks :)
> 
> I will deal with this issue in a few days👀

Thank You 🙏🏼

**Comment by RedJue** [comment]
> Thank You 🙏🏼 I found this issue in the latest version too - https://codepen.io/debotos/pen/wvxpBNK?editors=0010

Hi bro, after internal discussion, modifying the problem in this scenario may cause unanticipated problems in other scenarios as well as affect table performance, we suggest you to solve the problem by fixing the column width, which will bring better performance.

By the way, for the reasons and solutions, you can see [here](https://github.com/react-component/table/pull/947).

Appreciate understanding! 🙏🏼

**Comment by ahmettulutas** [comment]
What about using whitespace: nowrap on th ?
