### ISSUE TITLE
Flickering with image preview on Chrome/Android

### ISSUE THREAD

**Issue by opike** [ant-design/ant-design#40115]
### Reproduction link

[https://ant.design/components/image](https://ant.design/components/image)

### Steps to reproduce

Open the link in android/chrome, tap on an image to preview it, and then close the preview. There is noticeable flickering. It doesn't always happen, but it occurs about 80% of the time.

### What is expected?

No flickering

### What is actually happening?

Noticeable flickering

| Environment | Info |
| --- | --- |
| antd | 5.1.3 |
| React | The version being used on the ant.design website |
| System | Android 13 |
| Browser | Chrome 108.0.5359.128 |

---
Just noticed that it also happens with Safari on MacOS desktop: https://d.pr/v/uTds1P (mac OS 13.1, Safari 16.2)

**Comment by opike** [comment]
Looks like it may happen with all browser/OS combinations. This is Chrome 108, MacOS 13.1: https://d.pr/v/WvSOOV (it appears it happens less frequently with this combination, but right after you refresh the page it tends to happen about 90% of the time).

**Comment by opike** [comment]
Regarding the severity: on macOS the issue may not be as noticeable or frequent in general, but on android, especially with the browser taking up the entire screen, it's quite annoying.

**Comment by afc163** [comment]
Could you try antd 5.1.3 ?

**Comment by opike** [comment]
That's the version I reproduced it with:
<img width="627" alt="Screenshot on 2023-01-09 at 05-32-39" src="https://user-images.githubusercontent.com/2823563/211319851-87c52e1e-538c-4b31-93f1-bfb5507b4019.png">

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/motion/pull/39 , will be released in https://github.com/ant-design/ant-design/pull/40117

**Comment by opike** [comment]
great - thanks! Now extra motivation to upgrade my project from 4.x to 5.x 😊

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/releases/tag/5.1.4

**Comment by opike** [comment]
Quick turnaround - thanks!
Is there any possibility that the fix can also be merged into the v4 train? We're still working on the migration.
