### ISSUE TITLE
Radio Wave don't work when click label

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#40110]
https://ant.design/components/radio-cn

![Jan-09-2023 19-06-25](https://user-images.githubusercontent.com/507615/211294503-16dfc529-7046-4491-af73-853af81e612e.gif)

**Comment by jiaozitang** [comment]
试了没问题
![Untitled7](https://user-images.githubusercontent.com/18493352/211295384-814d5c8b-3dc9-4d62-ab5e-def8a4a03563.gif)

**Comment by afc163** [comment]
1. 点击 label，水波不出现。
2. 点击 radio 圆点，水波出现。

**Comment by afc163** [comment]
算了，感觉不一定要修，担心修了反而影响性能。
