### ISSUE TITLE
Cannot find module 'antd/locale/xx_XX'

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#40113]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/type-antd-5-1-3-forked-pd0w4u?file=/demo.tsx)

### Steps to reproduce

Just try to compile the project

### What is expected?

should import locale settings

### What is actually happening?

Cannot find module 'antd/locale/xx_XX

| Environment | Info |
| --- | --- |
| antd | 5.1.3 |
| React | React ^18.2.0 |
| System | MacOS and CodeSandbox |
| Browser | Chrome 108.0.5359.124 |

**Comment by zhangtao25** [comment]
import en from 'antd/es/locale/en_US';
import zh from 'antd/es/locale/zh_CN';

**Comment by nonam4** [comment]
> import en from 'antd/es/locale/en_US'; import zh from 'antd/es/locale/zh_CN';

This worked

If this is how we should use the locale modue so the [docs](https://ant.design/docs/react/i-18-n#configprovider) should be updated too

**Comment by QizhengMo** [comment]
> 

This worked for me, THANKS!

**Comment by QizhengMo** [comment]
> import en from 'antd/es/locale/en_US'; import zh from 'antd/es/locale/zh_CN';

This worked for me

**Comment by MadCcc** [comment]
@nonam4 locales in `es/` is not missing, did you encounter with another problem?

**Comment by nonam4** [comment]
> @nonam4 locales in `es/` is not missing, did you encounter with another problem?

@MadCcc yes, using `es/` I've got the following errors: 

```
error - ..../node_modules/antd/es/locale/pt_BR.js:2
import Pagination from "rc-pagination/es/locale/pt_BR";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

With `/lib` works like charm

**Comment by MadCcc** [comment]
> > @nonam4 locales in `es/` is not missing, did you encounter with another problem?
> 
> @MadCcc yes, using `es/` I've got the following errors:
> 
> ```
> error - ..../node_modules/antd/es/locale/pt_BR.js:2
> import Pagination from "rc-pagination/es/locale/pt_BR";
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
> ```
> 
> With `/lib` works like charm

In your case you should use cjs locales, so `lib/` works.
