### ISSUE TITLE
Radio.Group Button 只有 icon，不是正方形

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#40123]
### Reproduction link

[https://stackblitz.com/edit/react-js5hke?file=demo.tsx](https://stackblitz.com/edit/react-js5hke?file=demo.tsx)

### Steps to reproduce

查看按钮宽高

### What is expected?

与 Button 一样，是正方形
![image](https://user-images.githubusercontent.com/7971419/211440540-ee6bac65-d432-4ef9-b0bb-7267cc3c3224.png)

### What is actually happening?

长方形

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by MuxinFeng** [comment]
找不出啥原因，mark 学习一下

**Comment by afc163** [comment]
Radio.Button 没对 icon only 做特殊处理，我想想有没有必要。

**Comment by MuxinFeng** [comment]
`Radio.Group` 的`optionType`为 `button`时，不用添加额外的 `span`

**Comment by crazyair** [comment]
> Radio.Button 没对 icon only 做特殊处理，我想想有没有必要。

这个怎么样了

**Comment by afc163** [comment]
icon only 会让可点击区域变小，我建议还是不特殊处理了。
