### ISSUE TITLE
Table: Sticky table header overlapped shadow at right hand side

### ISSUE THREAD

**Issue by edc-pl** [ant-design/ant-design#40132]
### Reproduction link

[https://codepen.io/edc-pl/pen/qByrmEX](https://codepen.io/edc-pl/pen/qByrmEX)

### Steps to reproduce

1. Make sure no `fixed: 'right',` at last columns, and have `fixed: 'left',` at first column only
2. Set `sticky={true}` at Table
3. You will see shadow do not overlap the table header at right hand side

### What is expected?

The table header should be overlapped by the right shadow

### What is actually happening?

The right shadow is overlapped by table header

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 16.13.1 |
| System | Windows 10 22H2 19045.2364 |
| Browser | Chrome 109.0.5414.74 |

---
In antd4, the table header is overlapped by the right shadow. But in antd5, it didn't. Please see this codepen link (https://codepen.io/edc-pl/pen/wvxJdvN) with antd4 to compare the shadow appearance at right hand side of the table.

The shadow style affected by these css style

- antd4:
```
.ant-table .ant-table-container::after {
  z-index: calc(calc(2 + 1) + 1);
}
```
- antd5:
```
.ant-table-wrapper .ant-table-container::after {
  z-index: 2;
}
```

**Comment by Wxh16144** [comment]
mark~
