### ISSUE TITLE
Select 组件 multiple 模式下是否可以支持 overflow 的样式

### ISSUE THREAD

**Issue by hellowuxin** [ant-design/ant-design#40131]
### What problem does this feature solve?

Select 组件 multiple 模式下，随着选项的增多，会撑大内容区，但有时候并不希望无限撑大，于是希望有一个最大高度加以限制。
我尝试过响应式maxTagCount，但好像只适用于单行的场景，而我希望可以多行。

### What does the proposed API look like?
```
<Select mode="multiple" allowClear style={{maxHeight}} />
```
![acc37384e7c0d498cf26349571abae3e8ef9673de2e4ccac4926167ba5e7cc5eQzpcVXNlcnNcd3V4aW5cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDYzOTY0NDA0NV92MlxJbWFnZUZpbGVzXDE2NzMzMzUzMTU5ODRfQzJDNjU0NzctQjM1Ni00MGMwLThBMzYtNDMwNERCOEUxNTdCLnBuZw==](https://user-images.githubusercontent.com/37543498/211489467-a5c22934-5394-4d2b-97b7-5a5845fd04d4.png)

**Comment by hellowuxin** [comment]
上图是我调整了组件样式之后的效果，清除按钮的位置会有点问题

**Comment by zombieJ** [comment]
感谢反馈，目前没有计划。交互上两种一个是直铺、另一种就是响应式缩成 `+ 3` 这种。滚动对于不同系统滚动条展示配置不同体验不会特别好。但是如果的确有这种需求的话，就如你现在做的自行实现就好哈。
