### ISSUE TITLE
datePicker在week类型设置disabledDate部分不生效

### ISSUE THREAD

**Issue by zxq08** [ant-design/ant-design#40138]
### Reproduction link

[https://codepen.io/zxq08/pen/OJwpjxv?editors=0010](https://codepen.io/zxq08/pen/OJwpjxv?editors=0010)

### Steps to reproduce

disabled设置了禁用日期，并在函数中做了判断，但是2023-01-01一直没有被禁用

### What is expected?

2023-01-01正常被禁用

### What is actually happening?

2023-01-01没有被禁用，且选择后返回了2023年的52周

| Environment | Info |
| --- | --- |
| antd | 4.13.1 |
| React | react |
| System | macOS |
| Browser | chrome 92.0.4515.159 |

**Comment by afc163** [comment]
<img width="351" alt="图片" src="https://user-images.githubusercontent.com/507615/211526223-ddad2115-1595-4688-a68e-1659b0766d70.png">

看上去好像没问题？codepen 选不到 1 月 1 日。

**Comment by zxq08** [comment]
> <img alt="图片" width="351" src="https://user-images.githubusercontent.com/507615/211526223-ddad2115-1595-4688-a68e-1659b0766d70.png">
> 
> 看上去好像没问题？codepen 选不到 1 月 1 日。

sry 我刚刚在调试代码，您现在在看

**Comment by zxq08** [comment]
![image](https://user-images.githubusercontent.com/46339071/211527237-710fe0af-984e-44b6-ac90-f39ec0e347e8.png)

**Comment by afc163** [comment]
```diff
- YYYYWW
+ GGGGWW
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/20618#issuecomment-570456669

**Comment by zxq08** [comment]
> ```diff
> - YYYYWW
> + ggggWW
> ```
似乎还是不行
![image](https://user-images.githubusercontent.com/46339071/211530843-c226dff9-0737-4977-9ec6-1ef00ea34a06.png)

**Comment by zxq08** [comment]
同事提醒了下，我尝试换成了用 moment.isBefore和isAfter 去夹区间，这样倒是可以禁用 2023-01-01 的。
不确定是否和周的计算方式有关系？

**Comment by afc163** [comment]
哦，是 GGGGWW

**Comment by zxq08** [comment]
> 

这个可以！感谢

**Comment by afc163** [comment]
或者 `ggggww`，具体区别看  https://momentjs.com/docs/#/parsing/string-format/
