### ISSUE TITLE
Table: Figure out pagination rather than scroll dynamically

### ISSUE THREAD

**Issue by insertmike** [ant-design/ant-design#40141]
### Abstract

Adjust `<Table/>` component to be able to automatically figure out how many rows to render and respectively pages, depending on the height it was rendered, contrary to using scroll when rows do not fit in the wrapping container height.

### Expected Behavior

If there is 20 items but there is only space for 5 rows to be rendered, there should be 4 pages with 5 items per page.

### Actual Behavior

10 items are rendered per page and if scroll is adjusted, it will be activated. Otherwise user needs to do calculations on it's own but this can be tedious and should be handled by ant.

### What does the proposed API look like?

No API change, maybe a flag to enable this, for backward compatibility.

**Comment by MadCcc** [comment]
Any reference or implementation in other library?
In my opinion that responsive pagination may cause performance issue, and it may not act as expected for some edge case.
