### ISSUE TITLE
beforeUpload 多选时候 上传钩子Bug

### ISSUE THREAD

**Issue by fenghuizhang** [ant-design/ant-design#4015]
#### 发生问题的环境是：

如果是报告 bug，请按照下列格式书写，并务必提供复现步骤，否则恕难解决，感谢您的支持。
-->
- antd 版本:1.11.2
- 操作系统及其版本:win7 64bit
- 浏览器及其版本:chrome54

#### 您做了什么？请提供尽可能详细的重现步骤。
多选状态下，也就是multiple为true时候。当我在beforeUpload 函数内限制文件上传数量的时候，单个文件可以判断我设置的state，也就是fileLis的数组长度。
多个文件下beforeUpload 并不会获取fileList的真实长度，会当成上传一个文件来获取fileList这个state！

说明：onchange()里面更新了state

**Comment by benjycui** [comment]
本地实测可以在 fileList 中拿到全部的 file。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
不是很懂你的意思。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by caolvchong** [comment]
文件数量限制应该在 onChange 做

**Comment by benjycui** [comment]
onChange 里面能获取包含所有上传文件的 fileList

**Comment by fenghuizhang** [comment]
恩 文件数量只能在onchange里面才能控制，beforeUpload 里做多个文件个数限制的时候，也就是限制fileList的时候 一次上传多个文件就会当成上传一个文件来处理了

**Comment by benjycui** [comment]
现在的逻辑，可以限制用户最终被记录的上传的文件数量，但是不需要的文件还是上传到服务器了。
