### ISSUE TITLE
tabs新增新的tab后滚动条没有滚动到激活状态的标签上

### ISSUE THREAD

**Issue by helloJincheng** [ant-design/ant-design#40155]
### Reproduction link

[https://4x.ant.design/components/tabs-cn/](https://4x.ant.design/components/tabs-cn/)

### Steps to reproduce

新增页签直到出现滚动条

### What is expected?

滚动条滚动到新加的标签上

### What is actually happening?

滚动条没有滚动到新加的标签上，需要自己手动滚动一下

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17  |
| System | mac |
| Browser | 谷歌 |

**Comment by Yuiai01** [comment]
这个链接看不到 demo 来着

**Comment by helloJincheng** [comment]
![image](https://user-images.githubusercontent.com/27672145/211741441-f7044ab7-1525-40e3-8030-26bcb2838cc6.png)
官网tabs组件

**Comment by helloJincheng** [comment]
> 这个链接看不到 demo 来着

官网示例

**Comment by Yuiai01** [comment]
> > 这个链接看不到 demo 来着
> 
> 官网示例

嗯嗯

**Comment by Yuiai01** [comment]
确实在添加到尾部后会出现不会滚动到最新添加上的 tab 内容上

**Comment by Yuiai01** [comment]
这个问题我来尝试看看能不能解决

**Comment by Yuiai01** [comment]
> emmm 我能提pr么

哈哈哈 可以的，我刚刚下班到家

**Comment by Sneaken** [comment]
> > emmm 我能提pr么
> 
> 哈哈哈 可以的，我刚刚下班到家

我已经在 rc-tabs 里面提了 = =

**Comment by Yuiai01** [comment]
> > > emmm 我能提pr么
> > 
> > 
> > 哈哈哈 可以的，我刚刚下班到家
> 
> 我已经在 rc-tabs 里面提了 = =

嗯呐 看到了 大佬强的

**Comment by helloJincheng** [comment]
这个问题还没解决呢

**Comment by Yuiai01** [comment]
> 这个问题还没解决呢

那个大佬的 PR 貌似还没有合进去~

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/40816#issuecomment-1438000799
