### ISSUE TITLE
使用 Antd 5.x Menu “popupOffset” 属性，浏览器控制台报 warning

### ISSUE THREAD

**Issue by JC-Ge** [ant-design/ant-design#40150]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ding-bu-dao-hang-antd-5-1-4-forked-tzemf2?file=/demo.tsx:0-442)

### Steps to reproduce

进入链接，功能运行正常，但打开 console，可以看到对应报错

### What is expected?

无 warning，功能正常

### What is actually happening?

功能正常，控制台有 warning

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.1.0 |
| System | mac os |
| Browser | chrome 107.0.5304.87 |

**Comment by MadCcc** [comment]
Nothing in console.
![image](https://user-images.githubusercontent.com/27722486/211735655-587d367d-55e2-4a06-b3eb-b8403780073a.png)

**Comment by MadCcc** [comment]
`popupOffset` should be given to Submenu istead of MenuItem.
https://codesandbox.io/s/ding-bu-dao-hang-antd-5-1-4-forked-8ilph9?file=/demo.tsx:210-237

**Comment by JC-Ge** [comment]
我的需求就是控制 MenuItem 的 popupOffset，因为我想单独控制叶子 menu 的 offset，我提个需求吧
