### ISSUE TITLE
使用React 18以上时，select组件卡死

### ISSUE THREAD

**Issue by helloqian12138** [ant-design/ant-design#40157]
### Reproduction link

[https://github.com/JDFED/drip-table](https://github.com/JDFED/drip-table)

### Steps to reproduce

lerna bootstrap
npm start
open localhost:8000/demo
打开右侧属性栏，选择字段下拉框，页面卡死

### What is expected?

出现下拉选项

### What is actually happening?

页面卡死

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | >=18.0.0 |
| System | windows, macos |
| Browser | Chrome 108.0.5359.124 |

---
由于rc-trigger版本过低导致，建议升级到5.3.4

**Comment by afc163** [comment]
移除 yarn.lock，重新安装 node_modules 即可。

**Comment by danielyeh-meepshop** [comment]
目前使用 
- Antd 4.24.8 
- React 18 
一樣有卡死的問題 Popover & Select ，目前不考慮升級 v5 ，需要協助 非常感謝
