### ISSUE TITLE
RangePicker end date trigger panel at wrong position

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#40162]
https://4x.ant.design/components/date-picker-cn/ ✅

<img width="582" alt="图片" src="https://user-images.githubusercontent.com/507615/211763915-0e887b06-50e5-45e5-80f6-5e30fd9db606.png">

https://ant.design/components/date-picker-cn ❌

<img width="731" alt="图片" src="https://user-images.githubusercontent.com/507615/211764196-3981fadb-e3c1-4959-8f49-dbd25edf1eb8.png">

**Comment by Yuiai01** [comment]
在复现这个问题的时候我发现，如果在不同的 DatePicker 组件间切换，会出现明显的卡顿，且会让部分样式丢失。类似于：
![image](https://user-images.githubusercontent.com/112228030/211986034-99f44553-5274-434d-a95d-03b2bb0975bc.png)

**Comment by Yuiai01** [comment]
但是在 https://4x.ant.design/components/date-picker-cn/  中，切换的很流畅

**Comment by CCherry07** [comment]
picker 组件中 panelLef 计算异常，导致，RangePicker结束日期触发面板位置错误
@afc163  https://github.com/react-component/picker/pull/565

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/41090
