### ISSUE TITLE
Table暂无数据的dom覆盖到了横向滚动条

### ISSUE THREAD

**Issue by sameenzm** [ant-design/ant-design#4016]
表格无数据时会显示暂无数据，但是当我表格是有横向滚动条的时候，暂无数据的dom会覆盖到我的横向滚动条导致点不了滚动条
![image](https://cloud.githubusercontent.com/assets/17029105/20621982/bbe40146-b33b-11e6-86bb-05049a21778b.png)
ant有相应的配置处理吗？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/2875#r76722434

@ddcat1115
