### ISSUE TITLE
[select] keydown & highlight option

### ISSUE THREAD

**Issue by axehash** [ant-design/ant-design#40165]
### What problem does this feature solve?

use case: I need to customize the option. When the user hovers over the option, the option displays the delete and edit icon.
now: onMouseEnter & onMouseLeave is okay, but users can also select option by pressing up and down on the keyboard

用例场景：我想要自定义 option，在用户 hover 到 option 上时， option 右侧展示 删除/编辑 icon
现状：可以通过鼠标事件来实现效果，但是 select 的 option 还可以通过键盘上下键来选择，操作键盘时我没法知道当前哪个 option 处于高亮状态

### What does the proposed API look like?

onInputKeyDown = (e, focusOption) => {}

**Comment by Wxh16144** [comment]
或许你可以不用这么麻烦，用 css 来控制你 options 右侧操作的显隐。

options 激活的 class `ant-select-item-option-active`

**Comment by axehash** [comment]
> 

非常感谢~
