### ISSUE TITLE
如何关闭组件的动画？

### ISSUE THREAD

**Issue by liushaozhen** [ant-design/ant-design#40169]
### Reproduction link

[https://ant-design.gitee.io/components/overview-cn](https://ant-design.gitee.io/components/overview-cn)

### Steps to reproduce

无

### What is expected?

可以通过全局配置关闭所有组件的动画效果

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 18 |
| System | mac |
| Browser | chrome最新版 |

**Comment by afc163** [comment]
看看 https://github.com/ant-design/ant-design/discussions/40040 里 Other solutions 的部分。

**Comment by wjj5728** [comment]
@4 无法使用Other solutions 吧

**Comment by wjj5728** [comment]
antd@4 无法使用Other solutions吧
