### ISSUE TITLE
GeneratePicker 返回的 DatePicker 等组件主题失效

### ISSUE THREAD

**Issue by Yilun-Sun** [ant-design/ant-design#40161]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/range-picker-antd-5-1-4-forked-yod59z)

### Steps to reproduce

分别点击上下两个时间选择器。
![image](https://user-images.githubusercontent.com/43896664/211760232-1866e0db-93af-4679-9942-276126dc1995.png)

上方的用的是 antd 未经过 generatePicker 包装的。
![image](https://user-images.githubusercontent.com/43896664/211760123-fdd0c6dd-b0da-4bd2-84d1-53eba3509ed4.png)

下方的用的是经过 generatePicker 包装的。
![image](https://user-images.githubusercontent.com/43896664/211760170-fae58e5f-5113-4908-9d19-b7d2a6264a79.png)

现设置的是绿色主题，下方的时间选择器没有被应用主题颜色。

### What is expected?

经过 generatePicker 包装的时间选择器也可以被应用设置的主题。

### What is actually happening?

经过 generatePicker 包装的时间选择器未被应用设置的主题。

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | ^18.0.0 |
| System | MacOS 12.4 |
| Browser | 108.0.5359.98（正式版本） (x86_64) |

**Comment by afc163** [comment]
统一用 es 就好了：https://codesandbox.io/s/range-picker-antd-5-1-4-forked-h7h2c8

**Comment by shanelin7783** [comment]
> 



> 统一用 es 就好了：https://codesandbox.io/s/range-picker-antd-5-1-4-forked-h7h2c8

Hi, if I use "es" to import generatePicker in Next.js, I will get an error "SyntaxError: Cannot use import statement outside a module".
Is there any solution?
