### ISSUE TITLE
Collapse sizes

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#40176]
### What problem does this feature solve?

Have option to set collapse size like others components does

### What does the proposed API look like?
```
<Collapse size={'small' | 'large' | 'middle'}>
....
</Collapse>
```

**Comment by Yuiai01** [comment]
let me try~

**Comment by Yuiai01** [comment]
@nonam4   Hello, my current scheme is consistent with the size attribute of list component, can you accept it?

**Comment by Wxh16144** [comment]
> @nonam4 Hello, my current scheme is consistent with the size attribute of list component, can you accept it?

有讨论设计么？

**Comment by Yuiai01** [comment]
> > @nonam4 Hello, my current scheme is consistent with the size attribute of list component, can you accept it?
> 
> 有讨论设计么？

目前没有，想问问这个老哥

**Comment by Wxh16144** [comment]
> > > @nonam4 Hello, my current scheme is consistent with the size attribute of list component, can you accept it?
> > 
> > 
> > 有讨论设计么？
> 
> 目前没有，想问问这个老哥

cc @MadCcc

**Comment by nonam4** [comment]
> @nonam4 Hello, my current scheme is consistent with the size attribute of list component, can you accept it?

I didn't understood your question :thinking:

Will we get the option to set sizes of collapse elements?
Or the current scheme is the only one and we'll not be able to change it?

In my case, I'm using it inside a small sized Description component but with the current size the row is looking like the default instead

**Comment by Yuiai01** [comment]
> > @nonam4 Hello, my current scheme is consistent with the size attribute of list component, can you accept it?
> 
> I didn't understood your question 🤔
> 
> Will we get the option to set sizes of collapse elements? Or the current scheme is the only one and we'll not be able to change it?
> 
> In my case, I'm using it inside a small sized Description component but with the current collapse's size the row ended up looking like the default size instead

Maybe provide a link?

**Comment by nonam4** [comment]
> > > @nonam4 Hello, my current scheme is consistent with the size attribute of list component, can you accept it?
> > 
> > 
> > I didn't understood your question 🤔
> > Will we get the option to set sizes of collapse elements? Or the current scheme is the only one and we'll not be able to change it?
> > In my case, I'm using it inside a small sized Description component but with the current collapse's size the row ended up looking like the default size instead
> 
> Maybe provide a link?

Sure, here is a [codesandbox](https://codesandbox.io/s/collapse-antd-5-1-4-forked-jt0ckr?file=/demo.tsx) link

Take a look in `css` file and pay attention in screen width, should have no line breaks :grin::grin:

**Comment by Yuiai01** [comment]
> > > > @nonam4 Hello, my current scheme is consistent with the size attribute of list component, can you accept it?
> > > 
> > > 
> > > I didn't understood your question 🤔
> > > Will we get the option to set sizes of collapse elements? Or the current scheme is the only one and we'll not be able to change it?
> > > In my case, I'm using it inside a small sized Description component but with the current collapse's size the row ended up looking like the default size instead
> > 
> > 
> > Maybe provide a link?
> 
> Sure 😁😁 Here is a [codesandbox](https://codesandbox.io/s/collapse-antd-5-1-4-forked-jt0ckr?file=/demo.tsx) link

  Great design 👍🏻👍🏻, but I saw in the link you provided that only the header part of Collapse has been configured, I may not distinguish its Panel.

**Comment by nonam4** [comment]
@Yuiai01 I'm glad you liked my design 😁 
About Panels, maybe add two settings options: 

```
<Collapse
size='smal | medium | large' // this will change the Collapse header size
panelSize='smal | medium | large' // this will change collapsed panels size
> ... </Colapse>
```

So there will have two independent size options.
Here's an updated [codesandbox](https://codesandbox.io/s/collapse-antd-5-1-4-forked-jt0ckr?file=/demo.tsx) url

**Comment by Yuiai01** [comment]
> @Yuiai01 I'm glad you liked my design 😁 About Panels, maybe add two settings options:
> 
> ```
> <Collapse
> size='smal | medium | large' // this will change the Collapse header size
> panelSize='smal | medium | large' // this will change collapsed panels size
> > ... </Colapse>
> ```
> 
> So there will have two independent size options. Here's an updated [codesandbox](https://codesandbox.io/s/collapse-antd-5-1-4-forked-jt0ckr?file=/demo.tsx) url

🤔🤔 I think this is too cumbersome. The size attribute should be used to configure the size of the entire component.  Maybe we should get more people to talk about it.

**Comment by nonam4** [comment]
> The size attribute should be used to configure the size of the entire component. 

Yes, this makes sense.
If it's too cumbersome or if if you have a dev/layout pattern you can just ignore this seccond suggestion.
Anyway, with some css/classess we can change the layout if needed 😅 

Thanks for your attention and I hope that I had contributed with something

**Comment by Abhishek332** [comment]
size property is not working, I am getting same size of collapse if I use small | large size
