### ISSUE TITLE
upgrade moment

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4018]
2.17.0

**Comment by visvadw** [comment]
@afc163 Speaking about versions, what means `Antd Plus`, as mentioned in [Features / Demos for Antd Plus](https://github.com/ant-design/ant-design/projects/3)?

Thanks.

**Comment by benjycui** [comment]
@visvadw you can think it's a plan to improve demos, and make it more practical.

And it's best practice in real world, too.
