### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nodeType')

### ISSUE THREAD

**Issue by anjantalatam** [ant-design/ant-design#40189]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rpqjvq?file=/demo.tsx)

### Steps to reproduce

1. This is a console error thrown on a page using an Input type password.
2. I have found this error [ Cannot read properties of null (reading 'nodeType') ] quite a few times but have been unable to reproduce it separately
3. One common thing I observed every time: This error happens on lazyLoad of a component or when the internet is slow. 

### What is expected?

console errors should be minimized. 

### What is actually happening?

console errors are popping up quite a few times

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

<img width="659" alt="Screenshot 2023-01-12 at 11 34 31 AM" src="https://user-images.githubusercontent.com/53368431/211994731-0de517c6-9624-4643-9dcb-687468e3969b.png">

**Comment by anjantalatam** [comment]
Adding some screenshots that could help to figure out the issue.
<details>
</details>

**Comment by anjantalatam** [comment]
Adding some screenshots that could help to figure out the issue.

<details>
<summary>
getOffsetParent
</summary>
<img width="749" alt="getOffsetParent dot js" src="https://user-images.githubusercontent.com/53368431/211996347-49c94e8c-e03a-4188-8d31-67867ee176be.png">
</details>

<details>
<summary>
getVisibleRectForElement
</summary>
<img width="749" alt="getVisibleRectForElement dot js" src="https://user-images.githubusercontent.com/53368431/211996631-083f7a4a-7fc1-4e84-8ffe-ef618fb7e2ff.png">
</details>

<details>
<summary>doAlign</summary>
<img width="749" alt="align" src="https://user-images.githubusercontent.com/53368431/211996795-83296fe0-788f-491c-9f16-5268cb575b01.png">
</details>

<details>
<summary> alignElement  </summary>
<img width="749" alt="alignElement dot js" src="https://user-images.githubusercontent.com/53368431/211996952-59763b27-8883-4275-ba2d-4ca6be649e5a.png">

</details>

<details>
<summary>Align.js </summary>
<img width="749" alt="Align dot js" src="https://user-images.githubusercontent.com/53368431/211996974-890e7967-d485-48b7-b686-2a8f31011d54.png">

</details>

<details>
<summary> trigger ( useBuffer.js )</summary>
<img width="749" alt="useBuffer dot js" src="https://user-images.githubusercontent.com/53368431/211997031-7c08024b-0107-4e74-bb3e-24312386a5a1.png">

</details>

<details>
<summary> utils.js</summary>
<img width="749" alt="utils dot js" src="https://user-images.githubusercontent.com/53368431/211997225-1717be1c-0d0b-4b96-a212-fe39f9c7a644.png">

</details>

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/212300004-43da85c8-18a0-42b9-929a-5c24151d09be.png">

Cannot reproduce it.
