### ISSUE TITLE
鼠标点击官网右上角的更多选项，右上角的菜单样式异常

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#40186]
鼠标点击官网右上角的更多选项，右上角的菜单样式异常

https://user-images.githubusercontent.com/37385554/211957905-ada9be53-6e67-4af2-8b28-298dd16b5308.mov

_Originally posted by @wanghui2021 in https://github.com/ant-design/ant-design/issues/38671#issuecomment-1379715725_

**Comment by afc163** [comment]
@li-jia-nan @zombieJ 新的 wave 有问题，会 append node 到当前文档流，这个会有副作用。这个例子是导致 last-child 的样式失效，可能还会有别的问题。

**Comment by CCherry07** [comment]
这个似乎是，Button 在 dropdown 作为子组件时， button active 的样式问题。

**Comment by qjp88995** [comment]
@afc163 
![image](https://user-images.githubusercontent.com/21209765/211998702-f81cd2a7-3ce7-463e-aeb3-29663f057dca.png)
这个链接应该写错了，其他没有问题

**Comment by CCherry07** [comment]
@qjp88995  https://github.com/ant-design/ant-design/pull/40164 已经解决了
