### ISSUE TITLE
chrome上Table的expanded row中添加loading为true的Button组件时会导致表格绘制异常。

### ISSUE THREAD

**Issue by Frezc** [ant-design/ant-design#4019]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本: win10
- 浏览器及其版本: chrome 54.0.2840.99 m

#### 您做了什么？请提供尽可能详细的重现步骤。

在Table组件的expandedRowRender中只要有一个loading为true的Button组件就会导致表格绘制异常。

#### 您期待的结果是:

正常显示

#### 实际上的结果是:

除了展开的那一行，其他行的背景绘制异常。
![is1](https://cloud.githubusercontent.com/assets/6942296/20639691/86da6876-b405-11e6-8398-2efb59c715dc.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Frezc** [comment]
http://codepen.io/Frezc/pen/yVoPzO?editors=0110

**Comment by benjycui** [comment]
测了下，感觉更多的是流浪器渲染的问题。。

**Comment by Frezc** [comment]
只有chrome有这个问题吗

**Comment by benjycui** [comment]
是的，并且到 Chrome@57 就没这个问题了。

而且你给出的例子里面，loading button 后面的行还是有部分背景色的，不过 hover 后就会消失，然后鼠标移开也没有了。

把 loading button 的动画去除就一切正常。

综上，应该是浏览器本身渲染的 bug。

**Comment by Frezc** [comment]
好的 了解了
