### ISSUE TITLE
Popover绑定Button上，点击Popover的内容部分button会有水波纹

### ISSUE THREAD

**Issue by linlias** [ant-design/ant-design#40191]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3stzsm?file=/index.js)

### Steps to reproduce

import React from "react";
import ReactDOM from "react-dom";
import { Popover, Button, Icon } from "antd";
// import "antd/dist/antd.css";

function App() {
  const content = (
    <div
      onClick={(e) => {
        e.stopPropagation();
      }}
    >
      <div style={{ width: 300, height: 300, backgroundColor: "red" }}>
        fdlsakfsa
      </div>
    </div>
  );
  const click = (e) => {
    console.log(e);
  };
  return (
    <div
      className="container"
      onClick={() => {
        alert("container");
      }}
    >
      <Popover
        content={content}
        title=""
        trigger="focus"
        getPopupContainer={(trigger) => trigger}
      >
        <Button type="primary">Hover me</Button>
      </Popover>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

### What is expected?

点击Popover，button不会有水波纹的效果

### What is actually happening?

点击Popover，button的ant-click-animating-without-extra-node属性会变成true

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 17.0.0 |
| System | win10 |
| Browser | 谷歌 |

---
button是绝对定位，Popover需要页面滚动后随着button移动，所以需要  getPopupContainer={(trigger) => trigger}进行绑定，但绑定后点击content的内容，buttton上就会有水波纹的效果，        e.stopPropagation()也不能阻止

**Comment by zombieJ** [comment]
click 事件在 React 生命周期之外监听，的确是个问题。

**Comment by RedJue** [comment]
我看看能不能找到解决方案

**Comment by zombieJ** [comment]
看了一下，发现是：
```diff
-- getPopupContainer={(trigger) => trigger}
++ getPopupContainer={(trigger) => trigger.parentNode}
```
https://codesandbox.io/s/antd-reproduction-template-forked-l0puj0?file=/index.js:579-630

Popover 放到 Button 内部，点击触发 Button 的事件是预期行为。
