### ISSUE TITLE
form.validateFields() 表单属性 scrollToFirstError失效

### ISSUE THREAD

**Issue by bilibilinatural** [ant-design/ant-design#40190]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-pwvfzr?file=/index.js)

### Steps to reproduce

表单实例validateFields触发表单验证和onFinish	提交表单且数据验证成功后回调事件 具有不同的效果。

### What is expected?

from.validateFields()和onFinish对scrollToFirstError属性具有同样的效果

### What is actually happening?

from.validateFields()不能使scrollToFirstError属性生效

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 17.0.2 |
| System | macOS 12.3 |
| Browser | 版本 108.0.5359.124（正式版本） (x86_64) |

**Comment by linxianxi** [comment]
#30174  应该是一样的

**Comment by MadCcc** [comment]
Should trigger manually.

**Comment by bilibilinatural** [comment]
我可能表达的不够清楚，看了你们的回复我在codeSandBox中试了一下找到一种解决方案。
在392行有相关代码。
[![Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-tqu97r)
我想表达的是，给From表单添加scrollToFirstError属性。当用户点击htmlType='submit'的按钮的时候这时候表现没有问题。
但是我们使用另一种方式触发验证
``` jsx
<Button
          type="primary"
          // htmlType='submit'
          onClick={() => {
            form
              .validateFields()
              .then()
              .catch((err) => {
                //使用 form.validateFields()方式触发验证，只能通过这种方式实现提交失败自动滚动到第一个错误字段
                form.scrollToField(err.errorFields[0].name[0]);
              });
          }}
        >
          Register
 </Button>
```

**Comment by li-jia-nan** [comment]
reopen

**Comment by maggieyyy** [comment]
解决了吗，我在5.17.0还是会碰到这个问题

**Comment by yogithesymbian** [comment]
> 我可能表达的不够清楚，看了你们的回复我在codeSandBox中试了一下找到一种解决方案。 在392行有相关代码。 [![Edit on CodeSandbox](https://camo.githubusercontent.com/97cbe82b1619b42e1f78fce9db09104b932a9da1fd37751f4d9c41f4fe350241/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-forked-tqu97r?file=/index.js) 我想表达的是，给From表单添加scrollToFirstError属性。当用户点击htmlType='submit'的按钮的时候这时候表现没有问题。 但是我们使用另一种方式触发验证
> 
> ```js
> <Button
>           type="primary"
>           // htmlType='submit'
>           onClick={() => {
>             form
>               .validateFields()
>               .then()
>               .catch((err) => {
>                 //使用 form.validateFields()方式触发验证，只能通过这种方式实现提交失败自动滚动到第一个错误字段
>                 form.scrollToField(err.errorFields[0].name[0]);
>               });
>           }}
>         >
>           Register
>  </Button>
> ```

thankyou you saved my life but for `<ProLayout` its hide by `navBar` of `breadCrumb` how to specify height of `form.scrollToField` there is any properties to custom inside / alr ?
