### ISSUE TITLE
官网代码演示部分展开所有代码按钮失效

### ISSUE THREAD

**Issue by Yuiai01** [ant-design/ant-design#40196]
### Reproduction link

[https://ant.design/components/button-cn](https://ant.design/components/button-cn)

### Steps to reproduce

进入官网任一组件界面的代码演示部分，点击展开全部代码按钮即可复现

### What is expected?

组件演示代码能全部展开

### What is actually happening?

组件演示代码能未全部展开
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/112228030/212041361-9fa5fb33-5e8d-4da0-a2d1-057fe6036fd6.png">

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18.0.0 |
| System | macOS 12.2.1 |
| Browser | Chrome 108.0.5359.124 |

**Comment by Wxh16144** [comment]
确实存在问题，我去看看吧
