### ISSUE TITLE
How to set a font globally?

### ISSUE THREAD

**Issue by MichaelJHaywood** [ant-design/ant-design#40199]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-y1x6l5?file=/index.js)

### Steps to reproduce

Specifying a font at the top level of an app gets overridden by antd.

### What is expected?

A selected font should be able to be specified globally.

### What is actually happening?

When an element is wrapped within an antd component it has its font overridden. I can't find any documentation on the correct method of specifying a font globally. 

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18.1.0 |
| System | Windows 10 |
| Browser | Chrome 108.0.5359.125 |

**Comment by Yuiai01** [comment]
It appears that the `Col`  internal font overwrites the imported font.

**Comment by MichaelJHaywood** [comment]
@Yuiai01 Sorry about this. I thought I updated the issue earlier and have updated it now. 

The problem is I can't find any way of specifying a font globally in antd or any documentation.

**Comment by zombieJ** [comment]
Here is the token doc:
https://ant.design/docs/react/customize-theme#api

Sample:
https://codesandbox.io/s/antd-reproduction-template-forked-y9zt9n?file=/index.js
