### ISSUE TITLE
Table filter does not work if column has grouped header

### ISSUE THREAD

**Issue by rpander93** [ant-design/ant-design#40203]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/grouping-table-head-antd-5-1-4-forked-xeub76)

### Steps to reproduce

Create a table with a grouped headers. Add a filter to a column within a parent header. Observe that the filter does not work.

In the reproducer, I added a filter to the "Street" column. The filter button is visible. But the filter does not work.

### What is expected?

Rows are filtered as with non-grouped headers

### What is actually happening?

Rows are not filtered

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18.2.0 |
| System | macOS 13.1 |
| Browser | Firefox 108 |

**Comment by kunchit** [comment]
me too.
please update on next version
