### ISSUE TITLE
官网 demo：Breadcrumb 使用 menu 参数，console 报警告 `overlay` is deprecated. Please use `menu` instead.

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#40204]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wp13k3?file=/demo.tsx:762-778)

### Steps to reproduce

打开 demo

### What is expected?

console 报警告

### What is actually happening?

console 不报警告

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18 |
| System | Gentoo Linux 5.15.80 |
| Browser | Chrome 110.0.5481.24 |

---
原因是 `BreadcrumbItem` 组件里直接写了 `overlay`，导致 `props` 里有了 `overlay` 字段。
https://github.com/ant-design/ant-design/blob/52478c78d343fe68e0d57376e8613a9fb06fcd00/components/breadcrumb/BreadcrumbItem.tsx#L52

然后在 `Dropdown` 组件里用 `'overlay' in props` 来判断，所以报警告了。
https://github.com/ant-design/ant-design/blob/52478c78d343fe68e0d57376e8613a9fb06fcd00/components/dropdown/dropdown.tsx#L109-L113

**Comment by li-jia-nan** [comment]
都分析出原因了，直接来个PR？

**Comment by MadCcc** [comment]
改下 warning 的条件吧

**Comment by JarvisArt** [comment]
> 改下 warning 的条件吧

改成这种形式即可
```ts
if ('overlay' in props) {
  dropdownProps.overlay = overlay;
}
```

**Comment by jaaia** [comment]
使用menu ts也报错
