### ISSUE TITLE
NextJS V13.x   Antd V5.x 开发ssr运行时报错

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design#40218]
### Reproduction link
[Github Repo](https://github.com/hqwlkj/next-antd.git)
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading '1')

### Steps to reproduce

使用 NextJs13   Anrd 5搭建一个环境。  

### What is expected?

编译和运行时都能正常访问

### What is actually happening?

![image](https://user-images.githubusercontent.com/12181423/212265490-4881bca3-5d0f-4eec-9483-65e77e75bafc.png)

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | "react": "^18.2.0", |
| System | Mac OS 11.7.2 (20G1020) |
| Browser | Google Chrome  版本 109.0.5414.87（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
试了一下不能稳定复现，感觉是 next 里把什么东西清理了。globalCache 是一次性 init 的，可能需要给 next 反馈一下。

**Comment by hqwlkj** [comment]
> 试了一下不能稳定复现，感觉是 next 里把什么东西清理了。globalCache 是一次性 init 的，可能需要给 next 反馈一下。

是的，运行后第一次进入系统没有问题，跳转页面之后就会出现。这个问题 antd 这边没有办法处理吗？

**Comment by hqwlkj** [comment]
可以参考这个issue进行处理：

https://github.com/vercel/next.js/issues/44125#issuecomment-1372270391

**Comment by MadCcc** [comment]
extractcss 是推荐使用方法
