### ISSUE TITLE
windows上无法编译; linux上一切正常

### ISSUE THREAD

**Issue by bochen2014** [ant-design/ant-design#4021]
好像是bi sheng的问题.  路径hard code 了'/'
```
  ERROR in ./~/bisheng/tmp/entry.index.js
    Module not found: Error: Cannot resolve module 'D:__workant-design
outes.js' in D:\__work\ant-design\node_modules\bisheng\tmp
     @ ./~/bisheng/tmp/entry.index.js 16:13-79
```

另:  看了antD, bisheng, dva, 很震撼. 但震撼之余,觉得国内的同行好像宣传的不够(或者是澳大利亚信息太闭塞?) 我是很偶然地机会才发现antd
我觉得比material ui好, material ui做的太花哨了, antd明显有模信material ui的痕迹,但做出的效果很适合商业应用! 希望能多推广一下, 让更多人看到!

还有, 为什么采用type script? 我看了很多react的源代码, antd是唯一一个用type script写的. 不太明白

**Comment by benjycui** [comment]
* Windows 没环境也没时间支持，不是 contributor 的话，直接看官网吧。
* 宣传的力度的确是不够。。基本靠口碑。
* 微软的 Fabric，百度的 fit-component 都是 TypeScript。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/973
