### ISSUE TITLE
message.config中的自动关闭延时 duration 设置无效

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#40223]
### Reproduction link

[https://stackblitz.com/edit/react-ts-xbbbgf?file=App.tsx](https://stackblitz.com/edit/react-ts-xbbbgf?file=App.tsx)

### Steps to reproduce

打开链接，点击弹出message，时间设置了100秒，3秒就关闭了

### What is expected?

duration 能够全局设置

### What is actually happening?

duration 全局设置无效

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | react 18 |
| System | Windows 10 |
| Browser | Chrome 104.0.5112.102 |

**Comment by Yuiai01** [comment]
确实存在问题，当我设置 duration 为10时，会保持10s，但是设置100貌似就不生效了

**Comment by Yuiai01** [comment]
确实存在问题，我提一个 PR
