### ISSUE TITLE
Using Accelerators and Mnemonics in Menu and Dropdown?

### ISSUE THREAD

**Issue by JSchmidt63** [ant-design/ant-design#40230]
### What problem does this feature solve?

1. use accelerator in menu / dropdown - key bind to the items (maybe with mousetrap)
2. show mnemonics in items

### What does the proposed API look like?

in items:
accelarators/menmonics

**Comment by afc163** [comment]
Sorry, we have no plan to implement these features in Menu. I believe you can do it in your application.
