### ISSUE TITLE
在Button里使用“down” icon会比其他icon要小

### ISSUE THREAD

**Issue by Frezc** [ant-design/ant-design#4023]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本: win10
- 浏览器及其版本: chrome 54.0.2840.99 m

#### 您做了什么？请提供尽可能详细的重现步骤。

```jsx
<Button icon="down">down</Button>
<Button ><Icon type="down"/>down</Button>
```

#### 您期待的结果是:

down icon的默认大小和其他icon一样

#### 实际上的结果是:

down icon会小一号

#### 可重现的在线演示

http://codepen.io/Frezc/pen/JbyMwQ?editors=001

**Comment by benjycui** [comment]
这个可以通过设置 Icon 的 `font-size` 调整。

**Comment by Frezc** [comment]
恩 不过希望默认能一样啊

**Comment by benjycui** [comment]
按设计稿，我们现在的 Icon 大小是有问题：

![image](https://cloud.githubusercontent.com/assets/3580607/20695644/956d50ea-b628-11e6-9a54-9045cd9f78a4.png)

**Comment by benjycui** [comment]
@Frezc 不过你提的问题，其实是 by designed。

![image](https://cloud.githubusercontent.com/assets/3580607/20748167/191dc988-b728-11e6-81d7-2f96eec5f459.png)

**Comment by afc163** [comment]
改为只有放在 Dropdown 和 Dropdown.Button 下的向下图标才会变小。其他情况下和其他图标保持一致。
