### ISSUE TITLE
Improve pagespeed score of ant.design

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#40235]
https://pagespeed.web.dev/report?url=https%3A%2F%2Fant.design%2F&form_factor=desktop

https://pagespeed.web.dev/analysis/https-ant-design-components-button-cn/cfu4ujqhwf?form_factor=mobile

<img width="1008" alt="图片" src="https://user-images.githubusercontent.com/507615/225842346-73895dc0-f73d-4220-ac45-019ecd20288d.png">

---

PRs:

### CLS
- https://github.com/ant-design/ant-design/pull/43763

### JS Bundle Size
- https://github.com/ant-design/ant-design/pull/43765
- https://github.com/ant-design/ant-design/pull/43775
- https://github.com/ant-design/ant-design/pull/43777

### CSS Bundle Size
- https://github.com/ant-design/ant-design/pull/43762

**Comment by md5pk** [comment]
I think you should fix the rendering performance issue first.  
like this one:  https://github.com/ant-design/ant-design/issues/39746
It might be the fundamental architect decision, if that's the case it's not something the community can help.

**Comment by rinick** [comment]
as shown in pagespeed, the biggest performance impact is the Cumulative Layout Shift (CLS)
which can be easily reproduced with the test case of my issue:

https://deepmess.com/antd5performance/5.1/build/
if you refresh the page , you can see the table header's height is changed, which means it gets rendered at least twice, with different layout.

**Comment by xinghul** [comment]
I had to revert back to v4 because of the performance issue, mostly with the Table component.

I have a large number of records in the Table and I noticed that with v5, the UI becomes unresponsive when changing the Table filters.

**Comment by xinghul** [comment]
@afc163 do we have a plan to address this issue? I noticed the community has a lot of complaints regarding the performance issues, would be great if we have some sort of plan or workaround for this issue.

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/b6688c1a-e8fb-4f12-8feb-2fa7c0c12019)

**Comment by MadCcc** [comment]
@PeachScript 感觉 dumi 的打包结构还可以优化一下，比如 theme 模块是完全可以分离的
