### ISSUE TITLE
Can not override `Alert` seed token in theme

### ISSUE THREAD

**Issue by Ayuilos** [ant-design/ant-design#40240]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-chatterjee-et7ryr?file=/src/App.js)

### Steps to reproduce

Plz check the link.
I just wanna override `Alert` style, by setting `colorInfo` in `theme.token` can work, but set `theme.components.Alert.colorInfo` can't.

### What is expected?

`Alert` style can be override successfully

### What is actually happening?

Nothing happened

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18.2.0 |
| System | MacOS 13.1 |
| Browser | 109.0.5414.87 |

**Comment by kiner-tang** [comment]
you can use token like this: https://codesandbox.io/s/can-not-override-alert-style-forked-lhvshd?file=/src/App.js

**Comment by Ayuilos** [comment]
Thank you!

**Comment by Ayuilos** [comment]
But TBH, I still think this problem should get solved, because this is not a normal use way. I think it's enough for me to just give the `colorInfo`, the component style should be derived automatically from seed token, @kiner-tang.

At least your solution is the answer to my urgent need, thanks again.

**Comment by arvinxx** [comment]
a much more easy usage: https://codesandbox.io/s/token-usage-bygiog

**Comment by Ayuilos** [comment]
@arvinxx My situation was I just wanna change the `Alert` style, in this way, some other components style will also be influenced.

**Comment by arvinxx** [comment]
> @arvinxx My situation was I just wanna change the `Alert` style, in this way, some other components style will also be influenced.

You don't understand my demo. Just wrapper the Cp only on Alert.Then the influence will only on Alert and not on another components

**Comment by Ayuilos** [comment]
@arvinxx I didn't read it carefully, now I understand, but it will cause me to import CP every time when I need to use `Alert`, waiting for the fix

**Comment by arvinxx** [comment]
> @arvinxx I didn't read it carefully, now I understand, but it will cause me to import CP every time when I need to use `Alert`, waiting for the fix

Yeah, my demo is only work for a single component change. If you want to change all Alert, better to work with component token. The issue of component token will be fixed
