### ISSUE TITLE
Popconfirm组件，当Button按钮设置disabled以后，点击Button，还是会弹出Popconfirm

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design#40245]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wei-zhi-antd-5-1-5-forked-8guy5x?file=/demo.tsx:384-394)

### Steps to reproduce

Button直接设置disabled即可

### What is expected?

Button禁用以后，点击按钮不在唤起Popconfirm

### What is actually happening?

Button禁用以后，点击按钮仍然唤起Popconfirm

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 17 |
| System | MacOS |
| Browser | chrome |

**Comment by zombieJ** [comment]
By Design。受控禁用即可哈~

**Comment by overcastsky** [comment]
gsdg45sd4g5s4dg5sdイシリーズからドムをプレゼンりやかなベルガモットオジビタから
