### ISSUE TITLE
Image组件的preview功能可以加个图片切换事件吗

### ISSUE THREAD

**Issue by etsvain** [ant-design/ant-design#40259]
### What problem does this feature solve?

1.实际业务场景中，需要对当前切换的图片下标做响应

### What does the proposed API look like?

// cur 当前预览图片下标
// prev 上一个图片下标

onChange: (cur: number, prev: number) =>  void;

**Comment by li-jia-nan** [comment]
现在有切换按钮的，你的意思是把切换的回调函数暴露出来吗？

**Comment by li-jia-nan** [comment]
```tsx
<Image.PreviewGroup onChange={(cur) => console.log(cur)}>
  <Image src="" alt="" />
  <Image src="" alt="" />
  <Image src="" alt="" />
</Image.PreviewGroup>
```

**Comment by li-jia-nan** [comment]
@afc163 @MadCcc @zombieJ 感觉可以做？

**Comment by etsvain** [comment]
> ```tsx
> <Image.PreviewGroup onChange={(cur) => console.log(cur)}>
>   <Image src="" alt="" />
>   <Image src="" alt="" />
>   <Image src="" alt="" />
> </Image.PreviewGroup>
> ```

是的是的，就是要这个

**Comment by MadCcc** [comment]
这个要加的话最好考虑下受控

**Comment by li-jia-nan** [comment]
受控的话一个 api 不够了，还得加一个 currentIndex
