### ISSUE TITLE
使用StyleProvider做低版本chrome兼容之后，部分属性不支持，例如inset-inline-start

### ISSUE THREAD

**Issue by zhupp034** [ant-design/ant-design#40260]
### Reproduction link

[https://ant.design/components/switch-cn](https://ant.design/components/switch-cn)

### Steps to reproduce

1. 开启<StyleProvider hashPriority="high">，兼容360安全
2. 查看switch组件样式，inset-inline-start属性不支持
![image](https://user-images.githubusercontent.com/33925263/212617810-99d6ef35-2467-476d-98ab-8983a416bb7e.png)

### What is expected?

正常显示switch组件

### What is actually happening?

显示异常

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0 |
| System | window 10 |
| Browser | chrome 86 |

**Comment by Wxh16144** [comment]
逻辑属性？看看这个 https://ant.design/docs/react/compatible-style#css-logical-properties

**Comment by zhupp034** [comment]
> 逻辑属性？看看这个 https://ant.design/docs/react/compatible-style#css-logical-properties

感谢，解决了
