### ISSUE TITLE
Second row column is getting highlighted when use the Button in the column of the Table

### ISSUE THREAD

**Issue by msohaib-nisum** [ant-design/ant-design#40266]
### Reproduction link

[[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)](https://stackblitz.com/edit/react-h5ab2c-jafcun?file=demo.tsx)

https://react-h5ab2c-jafcun.stackblitz.io

### Steps to reproduce

When using button in the column of the table, so the next column gets highlighted. 

### What is expected?

It should not select the next column

### What is actually happening?

When using button in the column of the table, so the next column gets highlighted. 

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | React.js |
| System | MacBook Pro (Retina, 15-inch, Mid 2015) |
| Browser | Google Chrome |

---
no

**Comment by Wxh16144** [comment]
Can you provide a link to the correct reproduction of the problem?

**Comment by msohaib-nisum** [comment]
## Editor URL:
https://stackblitz.com/edit/react-h5ab2c-jafcun?file=demo.tsx

## Application URL:
https://react-h5ab2c-jafcun.stackblitz.io

**Comment by msohaib-nisum** [comment]
https://user-images.githubusercontent.com/83700313/212662391-34d5062b-3bf6-4f49-ad24-f5289f302898.mp4

**Comment by afc163** [comment]
<img width="1792" alt="图片" src="https://user-images.githubusercontent.com/507615/212792692-1a23f6bc-814e-4441-ae46-366452fec08d.png">

I can't see the problem in your link.
