### ISSUE TITLE
@types/antd message.warning() not exist

### ISSUE THREAD

**Issue by CalabashFox** [ant-design/ant-design#4026]
#### 发生问题的环境是：

- antd 版本: 0.12.31
-@types/antd 0.12.31
- 操作系统及其版本: macos
-开发环境: intellij idea
- 浏览器及其版本: chrome os LATEST

#### 您做了什么？请提供尽可能详细的重现步骤。
使用全局提示message.
但是warning方法均不存在.在antd的message声明处查看发现没有warning方法
antd的message声明如下:

```
export const message: {

        success: MessageFunc
        error: MessageFunc
        info: MessageFunc
        loading: MessageFunc
        config: (options: {
            /**
             * 消息距离顶部的位置
             *
             * @type {number}
             */
            top: number
        }) => void
        destroy: () => void
    }
```

**Comment by infeng** [comment]
可以考虑将antd升级到最新版，最新版的声明齐全

**Comment by benjycui** [comment]
1.0 开始才有声明文件 https://github.com/ant-design/ant-design/releases/tag/1.0.0

**Comment by infeng** [comment]
DefinitelyTyped上面是有一个v0.12.31的声明文件

**Comment by bang88** [comment]
是的。 楼主用的还是旧版的`antd`，文档也要对照旧版的去看，新版的有的功能是没有的。

如果你使用的是新版是不需要手动安装`typings`的。
