### ISSUE TITLE
Typography.Text code ellipsis 丢失右边框

### ISSUE THREAD

**Issue by 1pone** [ant-design/ant-design#40261]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sheng-lue-hao-antd-5-1-5-forked-1gog5y?file=/demo.tsx)

### Steps to reproduce

开启 ellipsis Switch

### What is expected?

Typography.Text code 有完整的边框
<img width="509" alt="image" src="https://user-images.githubusercontent.com/54310591/212618738-49de25f4-2fbd-466c-a0d2-8d9f36669458.png">

### What is actually happening?

Typography.Text code 丢失右边框
<img width="515" alt="image" src="https://user-images.githubusercontent.com/54310591/212618612-fb504ded-731c-4fd4-bbc7-06bbbe95559d.png">

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | macOS 12.4 |
| Browser | 108.0.5359.98 |

**Comment by Wxh16144** [comment]
看看官方维护者怎么说吧，如果是 Bug 可以指给我，我去看看

**Comment by afc163** [comment]
是 Bug

**Comment by Francoshum95** [comment]
@Wxh16144 I have an idea to fix this issue. Can we create an additional `useRef()` for `code` element and use `useEffect()` to override its styles? I'm not too familiar with this component, so I'm not sure if it's a good practice to do so.

**Comment by Wxh16144** [comment]
> fix(typography): Fix code tag overflow truncation style error #40503

I'm not sure, I haven't found a solution. If you can, feel free to make a pull request 😊.

**Comment by Francoshum95** [comment]
> > fix(typography): Fix code tag overflow truncation style error #40503
> 
> @Francoshum95 I'm not sure, I haven't found a solution. If you can, feel free to make a pull request 😊.

This is the best I could do. The complex nature of dealing with the code element when overflow occurs can make it challenging to maintain the design.

**Comment by wangcch** [comment]
Maybe we just need to customize the code tag style. 🤔

**Comment by Francoshum95** [comment]
> Maybe we just need to customize the code tag style. 🤔

Yeah, this solution does look cleaner. But do you have any ideas for how we can handle the issue of row > 1?

**Comment by wangcch** [comment]
> > Maybe we just need to customize the code tag style. 🤔
> 
> Yeah, this solution does look cleaner. But do you have any ideas for how we can handle the issue of row > 1?

Oh, right. Because the code container (Paragraph) is not `display: inline`. The style may not be as expected.🥲

<img width="795" alt="image" src="https://user-images.githubusercontent.com/28584349/222318726-d0ae9ffc-11b2-4423-a35f-9b56f07d65fb.png">

**Comment by Francoshum95** [comment]
> > > Maybe we just need to customize the code tag style. 🤔
> > 
> > 
> > Yeah, this solution does look cleaner. But do you have any ideas for how we can handle the issue of row > 1?
> 
> Oh, right. Because the code container (Paragraph) is not `display: inline`. The style may not be as expected.🥲
> 
> <img alt="image" width="795" src="https://user-images.githubusercontent.com/28584349/222318726-d0ae9ffc-11b2-4423-a35f-9b56f07d65fb.png">

That's right, if you give the code tag element a width (like using 'display: block' or 'display: inline-block'), it becomes a block-level element that takes up the full width of its parent container. This causes the border to be applied to the whole container, rather than to each line of text.

Another way to solve this issue is to separate the text into elements like span or div, and apply the border to each of those elements one by one. But it's going to be a bit of a challenge.

**Comment by wangcch** [comment]
🤔 I don't want to change the elements structure yet. This is not my original intention.
Need a better way...

**Comment by teenth** [comment]
> > > > Maybe we just need to customize the code tag style. 🤔
> > > 
> > > 
> > > Yeah, this solution does look cleaner. But do you have any ideas for how we can handle the issue of row > 1?
> > 
> > 
> > Oh, right. Because the code container (Paragraph) is not `display: inline`. The style may not be as expected.🥲
> > <img alt="image" width="795" src="https://user-images.githubusercontent.com/28584349/222318726-d0ae9ffc-11b2-4423-a35f-9b56f07d65fb.png">
> 
> That's right, if you give the code tag element a width (like using 'display: block' or 'display: inline-block'), it becomes a block-level element that takes up the full width of its parent container. This causes the border to be applied to the whole container, rather than to each line of text.
> 
> Another way to solve this issue is to separate the text into elements like span or div, and apply the border to each of those elements one by one. But it's going to be a bit of a challenge.

Typography使用`display: block`应该是没问题的，text可以算出多少行（通过一个字的box计算一行的box，然后将text分成几行），然后每行一个`div`元素。

**Comment by zombieJ** [comment]
相互叠加效果会让 Typography 的逻辑变得过于复杂，很容易埋坑。调整 `display` 本身也会对 baseline align 产生影响。目前试下来，最好的方式还是多个 Typography 来处理：
https://codesandbox.io/s/sheng-lue-hao-antd-5-1-5-forked-3gqp9w?file=/demo.tsx

**Comment by wangcch** [comment]
> 相互叠加效果会让 Typography 的逻辑变得过于复杂，很容易埋坑。调整 `display` 本身也会对 baseline align 产生影响。目前试下来，最好的方式还是多个 Typography 来处理： https://codesandbox.io/s/sheng-lue-hao-antd-5-1-5-forked-3gqp9w?file=/demo.tsx

好主意。不过好像没办法处理 `Typography.Paragraph` 情况 （或 ellipsis.rows > 1）
