### ISSUE TITLE
`<Select />` dropdown menu scrolls page instead of menu

### ISSUE THREAD

**Issue by superveetz** [ant-design/ant-design#40276]
### Reproduction link

[https://reservationscenter.com/hotel/embassy-suites-by-hilton-convention-center-las-vegas?id=d4098bed-4441-5761-8730-03cae6ccfa5f&start=01/16/2023&end=01/17/2023&room=[[18]]&modal](https://reservationscenter.com/hotel/embassy-suites-by-hilton-convention-center-las-vegas?id=d4098bed-4441-5761-8730-03cae6ccfa5f&start=01/16/2023&end=01/17/2023&room=[[18]]&modal)

### Steps to reproduce

From the link, scroll down to the first item in the list that says "BOOK NOW >>", tap that button.

On the checkout page, scroll down to the State dropdown select. Tap it to open the menu, notice that when scrolling the menu, you must swipe up and down very slowly to scroll the menu. If you do large or fast swipes, it ends up scrolling you up or down the page. 

I was able to reproduce this in a minimal React project using `npx create-react-app`

### What is expected?

I would expect large or fast swipes to just scroll the dropdown menu faster.

### What is actually happening?

The dropdown menu doesn't scroll, page scrolls instead.

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | React@18.2.0 |
| System | iOS 16.1.1 |
| Browser | Chrome |

**Comment by afc163** [comment]
> I was able to reproduce this in a minimal React project using npx create-react-app

Could you provide one?
