### ISSUE TITLE
Image支持自定义预览内容

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design#40279]
### What problem does this feature solve?

之前就有人提供类似issue #27273 ，一直没解决，在此新开一个 issue ，望采纳。

比如视频、文档之类文件有个示例图展示，点击预览展示 Modal 自定义内容。

可以参考 Upload 上传组件， onPreview 自定义预览的行为表现。

### What does the proposed API look like?

onPreview

---

以下是上传组件的表现形式，期望图片展示组件也可以支持（onPreivew）。

<img width="419" alt="image" src="https://user-images.githubusercontent.com/5070722/212802762-7fd047fb-8002-4410-9055-d5dde30cddf2.png">

<img width="699" alt="image" src="https://user-images.githubusercontent.com/5070722/212802796-79d29526-ff4a-440d-bb57-9d2306abe590.png">

**Comment by afc163** [comment]
Duplicate of #27273
