### ISSUE TITLE
Modal confirm resolved function can be fired twice

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#40272]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confirmation-modal-dialog-antd-5-1-5-forked-9nmp96?file=/demo.tsx)

### Steps to reproduce

Click on the "with promise" button, then click on the "Ok" button and click it several times really fast while it still loading. 
If you are fast enough you can see that the button can be clicked again an the function fired again before the modal finishes closing.

### What is expected?

The button to not fire the function while it is loading and the modal is closing.

### What is actually happening?

If you are fast enough you can click the button while the modal is closing and it ends up firing the function again.

https://user-images.githubusercontent.com/87539237/212683977-aae26e63-ea55-4634-bd6d-d9550100707b.mp4

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | ^18.2.0 |
| System | Windows 10 |
| Browser | Brave |

---
This problem can be more easily reproduced on lower end systems that have a bigger window on unmounting components on the screen, so its easier to click the button while the modal is closing.

**Comment by ecreeth** [comment]
🤔 It's weird, I'm getting this instead:
![image](https://user-images.githubusercontent.com/20761166/212711070-44d4cc20-3cc9-4691-bd3c-c5a9553f106c.png)

**Comment by balboFK** [comment]
I see, the warning is from the codepen, you can ignore it. I made the short video to proof that it happens in some cases.
Maybe your machine is to fast to be able to click on the button while it closes, or you're not clicking fast enough? The machine used on the video is not as  bad but I can reproduce it very consistently on it.

**Comment by ecreeth** [comment]
> I see, the warning is from the codepen, you can ignore it. I made the short video to proof that it happens in some cases. Maybe your machine is to fast to be able to click on the button while it closes, or you're not clicking fast enough? The machine used on the video is not as bad but I can reproduce it very consistently on it.

"Warning: `NaN` is an invalid value for the `left` css style property" is also happening in my local.

**Comment by balboFK** [comment]
I see, then it must be the example from the docs that shows that warning, since I forked it to make the reproduction link of this issue, the problem must have carried over, but I dont think it has something to do with this issue problem itself.

**Comment by Wxh16144** [comment]
Perhaps the same question as this one? #37329

**Comment by balboFK** [comment]
Hello @Wxh16144 it seems to be! Maybe the migration to antd v5 brought back this problem?

**Comment by ywzou** [comment]
+1

**Comment by xams-creator** [comment]
When using react-router
---
"Warning: NaN is an invalid value for the left css style property" is also happening in my local。


```tsx
{
    path: 'page1',
    element: <Page1 />,
},
{
    path: 'page2',
    element: <div>page2</div>,
}
```
```tsx
export default function Page1() {
    const navigate = useNavigate();
    const click = useCallback(() => {
        navigate('../page2');
    }, [navigate]);
    return (
        <div>
            <Button
                onClick={click}
            >gogogo</Button>
        </div>
    );
}
```

**Comment by WuJiY** [comment]
+1

**Comment by balboFK** [comment]
I can't really make a PR for this issue right now, if someone is available feel free to take over!

**Comment by Rafael-Martins** [comment]
Hey guys, I'm new here, I managed to reproduce the issue and I would love to contribute and fix this, I'm currently working in a fix and will open a pr if I did manage to fix it!

**Comment by Laboor** [comment]
> ## When using react-router
> "Warning: NaN is an invalid value for the left css style property" is also happening in my local。
> 
> ```tsx
> {
>     path: 'page1',
>     element: <Page1 />,
> },
> {
>     path: 'page2',
>     element: <div>page2</div>,
> }
> ```
> 
> ```tsx
> export default function Page1() {
>     const navigate = useNavigate();
>     const click = useCallback(() => {
>         navigate('../page2');
>     }, [navigate]);
>     return (
>         <div>
>             <Button
>                 onClick={click}
>             >gogogo</Button>
>         </div>
>     );
> }
> ```

May be this is a bug that occurs in antd/WaveEffect.js, When router Changing, The old page or components was destoryed,But the component wave effect is still continuing to calculate,It will cause javascript cannot get the ‘left’ or ‘top’ css style property for this component!

**Comment by Rafael-Martins** [comment]
Apologies for the absence here. I am still actively working on this issue on my free time. The codebase does not provide a clear explanation of the behavior when using `confirm` with Promises, I'm investigating it and writing some tests to cover this case.
