### ISSUE TITLE
Custom theme variable not used in confirm modal

### ISSUE THREAD

**Issue by woutqargo** [ant-design/ant-design#40275]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1f2dh9)

### Steps to reproduce

open confirm modal by clicking button

### What is expected?

* the buttons in confirm modal should not be rounded
* the skip button border hover color should be purple

### What is actually happening?

Confirm modal uses the default style

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 17.0.2 |
| System | macOS 12.5.1 |
| Browser | Chrome 108.0.5359.124 |

**Comment by Wxh16144** [comment]
Repetitive #39559, If you solve it you can close it now.

**Comment by lesh1j** [comment]
You can wrap the footer in the ConfigProvider like this
```
Modal.confirm({
  title: "title",
  content: "content",
  footer: (_, { OkBtn, CancelBtn }) => (
    <ConfigProvider theme={YOUR_THEME}>
      <Flex justify="space-between">
        <CancelBtn />
        <OkBtn />
      </Flex>
    </ConfigProvider>
  ),
});
```
