### ISSUE TITLE
【DatePicker】：周范围选择器没有高亮选中区间

### ISSUE THREAD

**Issue by WgCg** [ant-design/ant-design#40277]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

周选择器选中开始时间和结束时间后，没有高亮选中区间，目前的面板反馈让人产生没有选中的错觉，但是其它时间粒度的范围选择器都有高亮，交互上是不是应该统一？

日范围选择器有高亮选中区间：
![image](https://user-images.githubusercontent.com/20108513/212800698-12610676-833a-4870-8a2e-60945c602e6a.png)

但是周范围选择器却没有：
![image](https://user-images.githubusercontent.com/20108513/212800618-3777c86f-ecd7-49ac-8944-7fa284b3e842.png)

### What is expected?

周选择器选中开始时间和结束时间后，没有高亮选中区间

### What is actually happening?

周选择器选中开始时间和结束时间后，选中区间高亮

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 17.0.2 |
| System | windows |
| Browser | chrome 109.0.5414.74 |

**Comment by afc163** [comment]
Duplicate of #27984
