### ISSUE TITLE
ant-design 可以考虑优化增加全局配置

### ISSUE THREAD

**Issue by Titans1001** [ant-design/ant-design#40284]
### What problem does this feature solve?

ant-design 可以优化增加全局配置，诸如全局的button图标，全局的组件默认配置，全局的下拉弹出位置，全局的图标配置，注入此类。

### What does the proposed API look like?

全局初始化调用:
ant.setup(options) || ant.setGlobalDefaultConfig(options)
其中options可参照https://vxetable.cn/v3/#/table/start/global

**Comment by afc163** [comment]
https://ant.design/components/config-provider-cn/

**Comment by yoyo837** [comment]
ConfigProvider就是干这个的吧
