### ISSUE TITLE
⚠ Delay in loading CSS | Flash of Unstyled Content

### ISSUE THREAD

**Issue by SohaibRaza** [ant-design/ant-design#40285]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/amazing-mcnulty-y3whnb)

### Steps to reproduce

I am using Ant.Design   TailwindCSS with Next.js

### What is expected?

CSS should load normally when rendering.

### What is actually happening?

Flash of Unstyled Content: CSS loading is delayed, as a result it there is UI glitch when loading a page. Every thing is out of order and after a few sec or milliseconds it displays normally

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | ubuntu 20.4 LTS |
| Browser | Firefox 108.0.2 (64-bit) |

**Comment by MadCcc** [comment]
https://github.com/ant-design/create-next-app-antd/blob/main/pages/_document.tsx
Try to extract css.

**Comment by SohaibRaza** [comment]
> https://github.com/ant-design/create-next-app-antd/blob/main/pages/_document.tsx Try to extract css.

Already tried didn't work.

**Comment by MasterWolfx** [comment]
Same issue here

**Comment by monolithed** [comment]
@sabertazimi, 

Great that Ant Design version 5 has been released, and I've even come to terms with finding dozens of bugs on the first day, but this issue is much more important. Why was the build with styles deprecated if it doesn't work without it? We need a proper workaround for including styles, including for Next.js 13.

Look at my layout, Look, all the styles are flashing! 

https://github.com/ant-design/ant-design/assets/803674/9b5b787e-795a-46e6-acd1-61d954bee8d5

**Comment by inderrr** [comment]
Same issue here using tailwindcss without any component library.

**Comment by hheinsoee** [comment]
[https://ant.design/docs/react/use-with-next](https://ant.design/docs/react/use-with-next)

**Comment by monolithed** [comment]
@hheinsoee, https://github.com/ant-design/ant-design/issues/44770#issuecomment-1720835015

**Comment by musaddekali** [comment]
This one works
https://ant.design/docs/react/use-with-next#using-app-router

**Comment by vandercloak** [comment]
I am using nextjs `pages` router and had this issue. 

The [docs](https://ant.design/docs/react/use-with-next#using-pages-router) have a really helpful note that was the key for solving for me. 

Once my package.json `@ant-design/cssinjs` version matched the ant design `@ant-design/cssinjs` things worked great for me. Thanks @ant devs for including that note!

<img width="1200" alt="image" src="https://github.com/ant-design/ant-design/assets/7164984/e73b1589-d497-402c-b1dd-f11e1883b27c">

**Comment by lidusol** [comment]
> I am using nextjs `pages` router and had this issue.
> 
> The [docs](https://ant.design/docs/react/use-with-next#using-pages-router) have a really helpful note that was the key for solving for me.
> 
> Once my package.json `@ant-design/cssinjs` version matched the ant design `@ant-design/cssinjs` things worked great for me. Thanks @Ant devs for including that note!
> 
> <img alt="image" width="1200" src="https://private-user-images.githubusercontent.com/7164984/324235031-e73b1589-d497-402c-b1dd-f11e1883b27c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzE2ODEsIm5iZiI6MTcyMDUzMTM4MSwicGF0aCI6Ii83MTY0OTg0LzMyNDIzNTAzMS1lNzNiMTU4OS1kNDk3LTQwMmMtYjFkZC1mMTFlMTg4M2IyN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTMyMzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNhNmYxM2E3Njc0NjFlNzJhN2FhNTlhMmUyYTE5MWIzZjU5YTU5MzQ1MjFkMzJmNzNhNjM5YmI0M2U0MzRmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bc30psqrD5ir41EqqpnITEnZg6Q_LQuBTv6gzXNFs80">

Thank you, this has also helped me fix flicker issue in `app` router
