### ISSUE TITLE
Expose underlying tooltip styled component

### ISSUE THREAD

**Issue by evantrimboli** [ant-design/ant-design#40280]
### What problem does this feature solve?

I am using a charting library that allows the user to render a custom tooltip on hover. I would like to keep tooltips consistent throughout the app, so I would like to use the antd tooltip.

The code is something like:
```
tooltip={data => {
  return <Tooltip>{data.label} - {data.value}</Tooltip>
}}
```

The problem is that the tooltip never displays correctly because the chart is handling the hover/positioning aspect.

### What does the proposed API look like?

I'm not sure on the best name, however it would be something like:

```
tooltip={data => {
  // No hovering etc, just the raw tooltip that shows on popup with the styling
  return <TooltipBase>{data.label} - {data.value}</TooltipBase>
}}
```

**Comment by afc163** [comment]
`<Tooltip open>{data.label} - {data.value}</Tooltip>`
