### ISSUE TITLE
AntD Slider: Clicking on the circle of the right-most mark of an AntD Slider does not change the value of the slider

### ISSUE THREAD

**Issue by edgar-mg** [ant-design/ant-design#40288]
### Reproduction link

[https://codepen.io/engwenya/pen/bGjoMmB?editors=001](https://codepen.io/engwenya/pen/bGjoMmB?editors=001)

### Steps to reproduce

On the slider:
1. Hover the cursor over the center of the circle of the mark above 100°C
2. Click in the center of the circle of the mark above 100°C

### What is expected?

1. The cursor should change from default to pointer 
2. The value of the slider should change to 100

### What is actually happening?

1. The cursor stays as default pointer
2. The value of the Slider does not change

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | React 18 |
| System | MacOS |
| Browser | 109.0.5414.87 (Official Build) (arm64) |

**Comment by MuxinFeng** [comment]
Expand the length of the track, mainly by adding the length of dot

**Comment by LongHaoo** [comment]
I coming
