### ISSUE TITLE
modal组件报错 Warning: `NaN` is an invalid value for the `left` css style property.

### ISSUE THREAD

**Issue by kaneaaa** [ant-design/ant-design#40293]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-1-5-forked-f1x4hm?file=/demo.tsx)

### Steps to reproduce

modal组件设置destroyOnClose={true} 第一次打开modal在关闭modal，控制台会报 Warning: `NaN` is an invalid value for the `left` css style property.

### What is expected?

modal组件设置destroyOnClose={true} 不要报错

### What is actually happening?

destroyOnClose={false}就正常 destroyOnClose={true}就报错

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by hungtcs** [comment]
+1，不过我是在按钮点击的时候出现的。看起来是 CSSMotion、WaveEffect 引起的。

```
Warning: `NaN` is an invalid value for the `left` css style property.
    at div
    at DomWrapper (http://localhost:8080/antd.js:44274:90)
    at http://localhost:8080/antd.js:43956:32
    at WaveEffect (http://localhost:8080/antd.js:5570:5)
```

**Comment by mashirozx** [comment]
同样，pro-layout的菜单组件报错了

<img width="590" alt="image" src="https://user-images.githubusercontent.com/16148054/213128195-1c64b45d-a77d-4cb2-b6e4-b7fba83e2312.png">


<img width="1049" alt="image" src="https://user-images.githubusercontent.com/16148054/213128092-a8749c11-17c9-49c5-ae16-9815b41bb039.png">

**Comment by jianhao2010303** [comment]
+1

**Comment by yoyo837** [comment]
antd@5并未承诺支持IE
