### ISSUE TITLE
主题编辑器切换黑色后，导出功能没有正确导出切换后的颜色变量

### ISSUE THREAD

**Issue by prototypeof** [ant-design/ant-design#40299]
### What problem does this feature solve?

可以在项目中使用黑色主题的配置文件

### What does the proposed API look like?

能够在生产环境进行动态主题切换，支持通过上传的方式修改主题

**Comment by arvinxx** [comment]
@MadCcc 还是得把算法作为字符串导出的

**Comment by MadCcc** [comment]
> @MadCcc 还是得把算法作为字符串导出的

字符串也需要用户手动转，这个现在确实没好办法一键套用代码

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/39525

**Comment by prototypeof** [comment]
😭

**Comment by arvinxx** [comment]
> > @MadCcc 还是得把算法作为字符串导出的
> 
> 
> 
> 字符串也需要用户手动转，这个现在确实没好办法一键套用代码

我觉得还是加一个注册方法吧，至少有个可以用的。不然设计师也用不了，开发配了也用不了，这切换就是摆设了。
