### ISSUE TITLE
jsx风格的Table Column API提供自定义Column支持

### ISSUE THREAD

**Issue by xyunsh** [ant-design/ant-design#4029]
#### 发生问题的环境是：

- antd 版本:2.5
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？请提供尽可能详细的重现步骤。

采用jsx风格的Table.Column API  定义一个通用的DateColumn

// DateColumn.jsx
```

import React, { Component } from 'react';
import { Table } from 'antd';
import moment from 'moment';

export default ({format,...rest})=>{
    return <Table.Column {...rest} render={(text,record)=>{
        const t = moment.unix(text).format(format||'YYYY-MM-DD');
        return <span>{t}</span>
    }/>
}

```

#### 您期待的结果是:

能提供自定义Column支持，在Table中能像Table.Column一样工作

#### 实际上的结果是:

not work

function isColumnElement(element) {
  return element && (element.type === Column || element.type === ColumnGroup);
}

屏蔽了自定义Column

**Comment by benjycui** [comment]
感觉这个不是必须的，用函数的方式调用你那个 Stateless Component 即可。
```jsx
<Table>
  {getDateColumn({...})}
  {getDateColumn({...})}
  ...
</Table>
```

**Comment by yesmeck** [comment]
我还是把这个限制去掉吧， `getDateColumn({...})` 这样写就没 JSX 的感觉了，跟当初引入 JSX 的想法有点不一样可。

**Comment by yesmeck** [comment]
不过因为现在的实现其实是把 `Column` 的 `props` 读出来转换成原来的 `columns`，如果允许自己封装的话可能会有人这么做：

```javascript
class MyColumn extends Component {
  render() {
    return (
      <Column className="my-awesome-class" {...this.props} />
    );
  }
}

class App extends Component {
  render() {
    return (
      <Table>
        <MyColumn title="Name" dataIndex="name" key="name" />
      </Table>
    );
  }
}
```

这时候 Table 其实是读不到 `className`  的。

所以还是不改了，如果要对 columns 做 DRY 的话还是用原来的 `columns` 或者 @benjycui 的方式把。

**Comment by xyunsh** [comment]
看来只有自己封装一下了
