### ISSUE TITLE
table 组件的 rowScope 属性会造成一些样式问题，目前发现的是 border 消失

### ISSUE THREAD

**Issue by MuxinFeng** [ant-design/ant-design#40297]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/demo-of-rowscope-690ky2)

### Steps to reproduce

打开链接即可

### What is expected?

rowScope 不造成任何副作用

### What is actually happening?

table 组件的 rowScope 属性会造成一些样式问题，目前发现的是 border 消失

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18 |
| System | Mac |
| Browser | chrome101 |

**Comment by Yuiai01** [comment]
我发现是因为样式没有加上, 我这边给 tbody 里面的 th 也加上 thead 里的 th 的样式，大概是这样：
![image](https://user-images.githubusercontent.com/112228030/213096843-8f4bbffe-1d22-4a39-98d2-68a2866ea715.png)

**Comment by MadCcc** [comment]
还是把 table 样式还原到 v4 的吧
