### ISSUE TITLE
如何集成到 nextjs 13 中???

### ISSUE THREAD

**Issue by xushanpei** [ant-design/ant-design#40308]
### What problem does this feature solve?

服务端渲染

### What does the proposed API look like?

期望能集成进去,目前直接集成刷新样式闪烁,会出现从无样式到有样式的过程,不知道怎么去解决这个问题

**Comment by MadCcc** [comment]
https://github.com/ant-design/create-next-app-antd/blob/main/pages/_document.tsx

**Comment by xuhuanzy** [comment]
> https://github.com/ant-design/create-next-app-antd/blob/main/pages/_document.tsx

这个案例没用吧, build后还是出现明显的无样式到有样式的过程, 即使next export也是这样

**Comment by prakashmallow** [comment]
@MadCcc  I need antd v4 solution not antd v5.
