### ISSUE TITLE
钉钉会议室预定功能

### ISSUE THREAD

**Issue by ALYxiaochun** [ant-design/ant-design#40301]
### What problem does this feature solve?

可以解决交互提升

### What does the proposed API look like?

1、可以对视图做出一定的更改
2、基本事件的保持

**Comment by li-jia-nan** [comment]
啊？这个不是应该去给钉钉团队反馈吗？

**Comment by ALYxiaochun** [comment]
可否做一个开源的出来







                       
原始邮件
                       
                     

发件人："lijianan"< ***@***.*** &gt;;

发件时间：2023/1/18 11:43

收件人："ant-design/ant-design"< ***@***.*** &gt;;

抄送人："ALYxiaochun"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ant-design/ant-design] 钉钉会议室预定功能 (Issue #40301)




 
啊？这个不是应该去给钉钉团队反馈吗？
 
&mdash;

**Comment by li-jia-nan** [comment]
> 可否做一个开源的出来

不知道，我不是钉钉团队的，我甚至不是蚂蚁的，相关的问题你可以去联系钉钉团队，这里是 antd 组件库
