### ISSUE TITLE
Modal.confirm底部按钮颜色没用主题色

### ISSUE THREAD

**Issue by etsvain** [ant-design/ant-design#40305]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n0inb3)

### Steps to reproduce

Modal.confirm

### What is expected?

底部按钮应用主题色colorPrimary

### What is actually happening?

使用了#1677ff默认色

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | react18 |
| System | macos big sur 11.6.5 |
| Browser | 103.0.5060.114 |

---
在message.loading中的icon也没有应用colorPrimary

**Comment by MadCcc** [comment]
静态方法不消费 context，推荐参考 https://ant-design.antgroup.com/components/app-cn#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF，或者使用 hooks
