### ISSUE TITLE
Segmented: Type '"onResize"' is not assignable to type 'keyof SegmentedProps'. Did you mean '"onReset"'?

### ISSUE THREAD

**Issue by andreas-soroko** [ant-design/ant-design#40309]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hk5sou?file=/index.tsx)

### Steps to reproduce

- create a project like the one above
- run tsc --noEmit

### What is expected?

no type error

### What is actually happening?

```
node_modules/antd/es/segmented/index.d.ts:21:79 - error TS2344: Type '"max" | "required" | "type" | "data" | "default" | "high" | "low" | "key" | "id" | "media" | "height" | "width" | "block" | "start" | "open" | "name" | "color" | "content" | "direction" | ... 347 more ... | "onResizeCapture"' does not satisfy the constraint 'keyof SegmentedProps'.
  Type '"onResize"' is not assignable to type 'keyof SegmentedProps'. Did you mean '"onReset"'?
```

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17.0.2 |
| System | macOS 13.1 |
| Browser | Edge 109.0.1518.49 |

---
looks like it was introduced with 4.24.2, because 4.24.1 is working.

there was already an issue for it: https://github.com/ant-design/ant-design/issues/38808 (but for antd5 vs react 18)

saw also the [comment](https://github.com/ant-design/ant-design/issues/39004): 
> Please upgrade @types/react version to latest

but shouldnt the types version match the installed react version? latest version of `@types/react@17.X` does not fix it.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-6uwpbf?file=/index.tsx

Please upgrade @types/react version to latest, `18.0.27` for instance.
