### ISSUE TITLE
Space component sets a font-size

### ISSUE THREAD

**Issue by grossbart** [ant-design/ant-design#40315]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zubuvo?file=%2Findex.js)

### Steps to reproduce

Nest a `Space` component inside a `Typography.Title` component.

### What is expected?

The font size of `Typography.Title` is respected.

### What is actually happening?

`Space` overrides the font size to be the default (`14px`)

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | macOS |
| Browser | Firefox |

---
`Space` uses `genComponentStyleHook`, which in turn uses `genCommonStyle`, which then sets a `font-size` property on `Space` items like so:

```
:where(.css-dev-only-do-not-override-wcexds)[class^="ant-space"],
:where(.css-dev-only-do-not-override-wcexds)[class*=" ant-space"] {
 font-family:"Open Sans",sans-serif;
 font-size:14px;
 box-sizing:border-box;
}
```

This should not happen, spacing should not change font sizes. This might affect other components as well like `Row` or `Col` etc.

**Comment by rexyanglucky** [comment]
Row and Col Component have the same issue at V5.20.0
