### ISSUE TITLE
In v5, cannot define primary Buttons background (limited to background-color)

### ISSUE THREAD

**Issue by TdyP** [ant-design/ant-design#40311]
### What problem does this feature solve?

In antd v5, I would like to be able to use a gradient for the background of my primary Button.
For example: `transparent linear-gradient(180deg, #2CCEFF 0%, #0A8EE0 100%) 0% 0% no-repeat padding-box`

I'm able to change background color using a custom theme: changing the `colorPrimary` token define on `components.Button` is working. The problem is this token is affected to the `background-color` property in CSS, thus using a gradient is not working here. (see [source code](https://github.com/ant-design/ant-design/blob/master/components/button/style/index.ts#L241))

### What does the proposed API look like?

It would be nice to have access to the `background` property, instead of the `background-color` or via another token to be able to have more flexibility on backgrounds.

**Comment by Wxh16144** [comment]
我想尝试修复这个问题，可能不仅仅是 Button 有这个问题，其他组件类似的场景应该还有🤔。

应该换一种方式去实现，`colorPrimary` 仅仅是颜色相关的值。

**Comment by MadCcc** [comment]
改成 background 就好了，已经有相关 PR
https://github.com/ant-design/ant-design/pull/38644

**Comment by MadCcc** [comment]
But it seems cssinjs transformer could solve this problem quickly.

**Comment by MadCcc** [comment]
```ts
const transform: Transformer = {
  visit: (cssObj) => {
    if ('backgroundColor' in cssObj) {
      const clone: CSSObject = { ...cssObj };
      clone.background = clone.backgroundColor;
      delete clone.backgroundColor;
      return clone;
    }
    return cssObj;
  },
};
```
Try to add this transformer to StyleProvider.

**Comment by shahbazshueb** [comment]
> ```ts
> const transform: Transformer = {
>   visit: (cssObj) => {
>     if ('backgroundColor' in cssObj) {
>       const clone: CSSObject = { ...cssObj };
>       clone.background = clone.backgroundColor;
>       delete clone.backgroundColor;
>       return clone;
>     }
>     return cssObj;
>   },
> };
> ```
> 
> Try to add this transformer to StyleProvider.

Thanks @MadCcc . This works like a charm. However, whenever I set colorPrimary to a gradient color, it gets reset to #ffff. Any workaround for it?
