### ISSUE TITLE
Module not found: Error: Can't resolve 'antd/lib/upload/style/css' in

### ISSUE THREAD

**Issue by ajay-wadhwa** [ant-design/ant-design#40310]
### Reproduction link

[https://www.bug.com/](https://www.bug.com/)

### Steps to reproduce

I have changed the version of antd to 5.1.5 and then I am starting my project using yarn sart command but getting this error .
Module not found: Error: Can't resolve 'antd/lib/upload/style/css' .

### What is expected?

Dont know how to proceed further

### What is actually happening?

Not able to do yarn start.

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 16.9.0 |
| System | Linux |
| Browser | Terminal |

**Comment by yoyo837** [comment]
remove `babel-plugin-import`

**Comment by ilDeffo** [comment]
@yoyo837 do I have to remove it from package.json right? if I do that, then when launching `yarn workspace @myPackage run start` I get
```
./src/index.js
Error: Cannot find module 'babel-plugin-import' from 'C:\Users\myUser\Projects\myProject\packages\myPackage'
    at Array.map (<anonymous>)
```

**Comment by gabrielcalk** [comment]
I was having this issue and even deleting babel-plugin-import I was still having the same error. I was only able to solve by deleting craco-antd (which includes babel-plugin-import).

**Comment by Implementist** [comment]
> @yoyo837 do I have to remove it from package.json right? if I do that, then when launching `yarn workspace @myPackage run start` I get
> 
> ```
> ./src/index.js
> Error: Cannot find module 'babel-plugin-import' from 'C:\Users\myUser\Projects\myProject\packages\myPackage'
>     at Array.map (<anonymous>)
> ```
> 
> **EDIT** I solved it by removing this lines
> 
> ```
> fixBabelImports('import', {
>     libraryName: 'antd',
>     libraryDirectory: 'es',
>     style: 'css',
> })
> ```

Thanks, this works for me.
