### ISSUE TITLE
table  的展开中使用  scroll

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#4031]
table 有个api  scroll  可以出来滚动条 但是 如果在 展开的 tr中  就没有效果了

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by qq645381995** [comment]
<p data-height="265" data-theme-id="0" data-slug-hash="KgPZrE" data-default-tab="result" data-user="benjycui" data-embed-version="2" data-pen-title="KgPZrE" class="codepen">See the Pen <a href="http://codepen.io/benjycui/pen/KgPZrE/">KgPZrE</a> by BenjyCui (<a href="http://codepen.io/benjycui">@benjycui</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>

**Comment by qq645381995** [comment]
<iframe height='265' scrolling='no' title='KgPZrE' src='//codepen.io/benjycui/embed/KgPZrE/?height=265&theme-id=0&default-tab=result&embed-version=2' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'>See the Pen <a href='http://codepen.io/benjycui/pen/KgPZrE/'>KgPZrE</a> by BenjyCui (<a href='http://codepen.io/benjycui'>@benjycui</a>) on <a href='http://codepen.io'>CodePen</a>.
</iframe>

**Comment by yesmeck** [comment]
@qq645381995 你要把 Codepen fork 成你自己的才能保存

**Comment by qq645381995** [comment]
<p data-height="265" data-theme-id="0" data-slug-hash="VmMrLW" data-default-tab="result" data-user="qq645381995" data-embed-version="2" data-pen-title="VmMrLW" class="codepen">See the Pen <a href="http://codepen.io/qq645381995/pen/VmMrLW/">VmMrLW</a> by crazyair (<a href="http://codepen.io/qq645381995">@qq645381995</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>

**Comment by qq645381995** [comment]
展开的table 列太多 不好写滚动条！  我现在方案 是获取page 宽度来出来滚动条的最大宽度的

**Comment by yesmeck** [comment]
跟 expandedRowRender 没关系，好像现在设计就是这样的？设置`scroll.x`的是必须有一个宽度小于 x 的容器把 table 包起来才有效果。

@afc163

**Comment by qq645381995** [comment]
>跟 expandedRowRender 没关系，好像现在设计就是这样的？设置scroll.x的是必须有一个宽度小于 x 的容器把 table 包起来才有效果。
那  @afc163   你怎么看

**Comment by yesmeck** [comment]
想了下这个设计是合理的，没有固定宽度的容器把 table 包起来的话， scroll 就没意义。
