### ISSUE TITLE
Type error: ',' expected. Next JS build

### ISSUE THREAD

**Issue by d90375** [ant-design/ant-design#40324]
### Reproduction link

[https://github.com/onebar/onebar-mono/actions/runs/3955725142/jobs/6774387403#step:10:700](https://github.com/onebar/onebar-mono/actions/runs/3955725142/jobs/6774387403#step:10:700)

### Steps to reproduce

semantic error in node modules - import { type CalendarProps } from './generateCalendar'; Type error: ',' expected.

### What is expected?

semantic error in node modules - import { type CalendarProps } from './generateCalendar'; Type error: ',' expected.

### What is actually happening?

semantic error in node modules -  import { type CalendarProps } from './generateCalendar'; Type error: ',' expected.

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | Mac OS Ventura 13.1 |
| Browser | Chrome Version 109.0.5414.87 |

---
semantic error in node modules import { type CalendarProps } from './generateCalendar'; Type error: ',' expected.

![image](https://user-images.githubusercontent.com/18696683/213379929-2514cb2b-ea68-46b0-8c76-59a1470f53f2.png)

**Comment by d90375** [comment]
this is issue solved by update typescript, thanks

**Comment by anhnghia47** [comment]
@d90375  Can you give me the typescript version to solved this issue?
