### ISSUE TITLE
menu 里的 item 没带上 props

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#4032]
在 Item 上加 id, 没带到 li 上面...

**Comment by afc163** [comment]
为啥需要 id ？

**Comment by jljsj33** [comment]
不是在编辑系统里都他吗的加了ID了吗，，，，算了，，不要了，，我整块信息放着编缉吧。。。不过，，这ITEM应该得把PROPS带上

**Comment by jljsj33** [comment]
https://github.com/react-component/menu/blob/master/src/MenuItem.jsx#L183-L189

把 { ...props }  放在 attrs 前面不就行了
