### ISSUE TITLE
No reaction in TreeNode for onRightClick on MacOS

### ISSUE THREAD

**Issue by selfrefactor** [ant-design/ant-design#40321]
### Reproduction link

cannot provide

### Steps to reproduce

Right click on tree item doesn't work on MacOS but it does on Linux

### What is expected?

right click handler to work

### What is actually happening?

handler is ignored as if it is not respected

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Latest Chrome, Firefox |

**Comment by zombieJ** [comment]
Could you help to provide gif for this?

**Comment by selfrefactor** [comment]
If it works for you, then I will close it. Maybe it is some mouse settings that makes the issue. Thanks for the speed.
