### ISSUE TITLE
Input with status doesn't colorize suffix icons

### ISSUE THREAD

**Issue by lscheibel** [ant-design/ant-design#40339]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/status-antd-5-1-5-forked-3dtlkp)

### Steps to reproduce

Add status prop with value "warning" or "error" to Input component. Also add an icon into the suffix prop.

### What is expected?

The icon has the error/warning color as icons, which are declared in the prefix, do.

### What is actually happening?

The suffix icon stays colorless.

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 109.0.5414.75  |

**Comment by Yuiai01** [comment]
I found the cause, and I'm going to fix it.
