### ISSUE TITLE
TimePicker与DatePicker选择后可输入

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#4033]
#### 发生问题的环境是：

- antd 版本:2.5.0
- 操作系统及其版本:window10
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

使用TimePicker与DatePicker组件。

#### 您期待的结果是:

选中时间后不可以在输入。

#### 实际上的结果是:

选中时间后可以在显示的时间后面输入。

#### 可重现的在线演示

https://ant.design/components/time-picker/#components-time-picker-demo-basic
![timepicker](https://cloud.githubusercontent.com/assets/4525647/20662280/c38979fe-b58d-11e6-87a9-ea50853ff18b.png)

**Comment by kairi1227** [comment]
@afc163 如何解决？？

**Comment by afc163** [comment]
是这么设计的，用户可以用输入直接修改时间类组件的值。
