### ISSUE TITLE
Tooltips don't hide with mouse delays set to 0

### ISSUE THREAD

**Issue by MikeYermolayev** [ant-design/ant-design#40338]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-shadow-onlfou?file=/src/App.js)

### Steps to reproduce

Just hover triggers and sometimes tooltips are stuck and not hidden. Seems like it happens only when I set delays to 0.

P.S. in our project it reproduces very easily. In sandbox it was easily reproduced with open Dev Tools

<img width="434" alt="image" src="https://user-images.githubusercontent.com/8783498/213470830-29d06f02-dd4b-47c2-9049-c1066aaa5210.png">

### What is expected?

Only one tooltip shown at a time

### What is actually happening?

A lot of tooltips are visible even after mouseLeave

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | MacOs Ventura 13.1 |
| Browser | Brave Version 1.46.153  Chromium: 108.0.5359.128 (Official Build)  (x86_64) |

---
Bumped into this issue after ant upgrade from 4.18.8 to 4.24.7

**Comment by MikeYermolayev** [comment]
This is how it looks like in our app after update:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/8783498/213476375-047ee68b-ac0e-414f-af5c-c1a5e8064ba7.png">

**Comment by afc163** [comment]
@MikeYermolayev Could you try 5.5.1 to see whether this issue still exists?

https://codesandbox.io/s/reverent-kapitsa-0wt36w?file=/src/App.js

**Comment by zombieJ** [comment]
Close since no more response.
