### ISSUE TITLE
Checkbox with button layout / toggle button

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#40335]
### What problem does this feature solve?

Have an alternative to checkbox default layout. It will act/look as a toggle button.

Here's a [codesandbox](https://codesandbox.io/s/basic-antd-5-1-5-forked-jp0c2y?file=/demo.tsx) example

### What does the proposed API look like?

```
<Checkbox
  layout={'button'}
>
  Toggle Button
</Checkbox>
```

**Comment by afc163** [comment]
We don't provide a toggle button in our design system.

**Comment by nonam4** [comment]
> We don't provide a toggle button in our design system.

Yes, I know you don't provide toggle button in your design system
That's why I've created this feature request.

I think more people should discuss about this and see if this is a nice feature to add or not

**Comment by afc163** [comment]
We believe Switch component is a better solution for this situation.

**Comment by afc163** [comment]
Or you can try CheckboxTag https://github.com/ant-design/ant-design/issues/4761#issuecomment-277566866

**Comment by nonam4** [comment]
> Or you can try CheckboxTag [#4761 (comment)](https://github.com/ant-design/ant-design/issues/4761#issuecomment-277566866)

Yes, [checkable tags](https://ant.design/components/tag#components-tag-demo-checkable) works like a toggle button. 

I just have one question, can I force them to look like a default tag when they're not checked?

**Comment by afc163** [comment]
Then you have override the default styles.

**Comment by nonam4** [comment]
> Then you have override the default styles.

Overriding Checkable Tags, Checkboxes, Switches... 
All of these options takes me back to my [codesandbox](https://codesandbox.io/s/basic-antd-5-1-5-forked-jp0c2y?file=/demo.tsx) example where I've changed default styles with CSS to make it looks like a toggle button

But it's ok, this is not a feature you are planning to add.
I'll change it with CSS in my project instead


Thanks 👍🏼
