### ISSUE TITLE
React 18, findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by omarc1492** [ant-design/ant-design#40340]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/26136#issuecomment-1249110917](https://github.com/ant-design/ant-design/issues/26136#issuecomment-1249110917)

### Steps to reproduce

Increment count of `<Badge/>` component

### What is expected?

nothing

### What is actually happening?

react_devtools_backend.js:4012 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react 18.0, react-native not installed |
| System | Windows 10 |
| Browser | Version 1.47.171  Chromium: 109.0.5414.87 (Official Build)  (64-bit) |

**Comment by omarc1492** [comment]
![image](https://user-images.githubusercontent.com/10967529/213500007-bfc83596-e306-4928-a76f-eae64d4ec2f9.png)

**Comment by yanglee2421** [comment]
今天用Menu组件的时候碰到了，antd@5.1.6，win11@22000.1455，chrome@109.0.1518.61

**Comment by zzswang** [comment]
DropDown 组件还是会报这个错

**Comment by suzyvivi** [comment]
> DropDown 组件还是会报这个错

在你的自定义组件外边再套一个div就好了。

```jsx
< DropDown >
  <div>
    <YourComponent>
  </div>
</DropDown>
```

**Comment by Resolute-qqw** [comment]
> > DropDown 组件还是会报这个错误
> 
> 在你的自定义组件的外面再套一个div就好了。
> 
> ```js
> < DropDown >
>   <div>
>     <YourComponent>
>   </div>
> </DropDown>
> ```

yes

**Comment by scplay** [comment]
我在用 popover 组件时也发现了，popover 的子组件是个 svg 组件，就会报这个错，这样也可以
```jsx
<>
  <YourComponent>
</>
```
