### ISSUE TITLE
[Popover] Input component in Popover causes the `afterOpenChange`  function to be called repeatedly

### ISSUE THREAD

**Issue by hsuanxyz** [ant-design/ant-design#40342]
### Reproduction link

[https://stackblitz.com/edit/react-tznnbe?file=demo.tsx](https://stackblitz.com/edit/react-tznnbe?file=demo.tsx)

### Steps to reproduce

1. Click the button to open the popover and type something in the input component.
2. See the outputs of the console.

### What is expected?

This callback is called once when it is opened or closed each time

### What is actually happening?

It will be called every time you type.

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18 |
| System | macOS |
| Browser | Chromium Version 101.0.4950.0 (Developer Build) (x86_64) |

**Comment by zombieJ** [comment]
Check the internal realization that `rc-trigger` is coupling with `rc-util/Portal`. It's better to refactor `rc-trigger` instead of patch on it.

**Comment by zombieJ** [comment]
fixed in #40632

https://stackblitz.com/edit/react-tznnbe-hwezcx?file=package.json
