### ISSUE TITLE
Modal confirm not using seed token colorPrimary

### ISSUE THREAD

**Issue by franco-marzano** [ant-design/ant-design#40352]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mq6zcj)

### Steps to reproduce

- Set colorPrimary seedToken with ConfigProvider
- Open modal through Modal.confirm()

### What is expected?

Color of primary "ok" button should consume colorPrimary seedToken

### What is actually happening?

Color of primary "ok" button uses antd default colorPrimary

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 16.13.1 |
| System | Windows 10 64bits |
| Browser | Opera GX 94.0.4606.69 |

**Comment by Yuiai01** [comment]
Hi. I thought you could take a look at this. https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/40305
https://github.com/ant-design/ant-design/issues/39023

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/40546
