### ISSUE TITLE
Allow users to pass ref

### ISSUE THREAD

**Issue by flexicious** [ant-design/ant-design#40359]
### What problem does this feature solve?

We are developing an adapter for our datagrid component to use Ant. https://reactdatagrid.com/docs/ant-design/ant-design-adapter. There is a demo of this at https://reactdatagrid.com/examples/?example=Ant_Design_Demo. However, we are not able to reference the underlying input element. By comparison, Material allows to pass inputRef property (https://mui.com/material-ui/api/text-field/#props) which we can use to perform custom actions on the text input. Is it possible to expose a ref property? 

### What does the proposed API look like?

<Input ref={inputRef}
<Select ref={selectRef}
<Checkbox ref={checkBoxRef}

Which can then be use

**Comment by zombieJ** [comment]
Good point. I wrote the root props RFC. Pls feel free to comment on this.

Merge into #40227
