### ISSUE TITLE
"placement" not working

### ISSUE THREAD

**Issue by goran-dev** [ant-design/ant-design#40376]
### Reproduction link

[https://prnt.sc/iIcASsCX2Fdv](https://prnt.sc/iIcASsCX2Fdv)

### Steps to reproduce

Put placement="bottomLeft"

### What is expected?

It is expected for dropdown to be at the bottom left

### What is actually happening?

The fropdown is on top, not bottom

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | All |
| Browser | Chrom |

---
It is not like docs say "The position where the selection box pops up" but more like "The desired position where..." so the dropdown will not care about this prop and if there is more free space above the input, the dropdown will be at the top and ignore the prop placement="bottomLeft"

**Comment by goran-dev** [comment]
I provided screenshot already, "online reproduction by forking code..." too much, faster to switch from ant-design to different LIbrary.

**Comment by MadCcc** [comment]
Just fork our CodeSandbox example and provide minimized reproduction. It would help a lot if there's problem with components of antd.

**Comment by goran-dev** [comment]
Ok.
https://codesandbox.io/s/antd-reproduction-template-forked-f7zc8n?file=/index.js
So if you open select in example, it will ignore `placement="bottomLeft"`, because I guess there is more space at the top
If you scroll a bit down, to make space at the bottom, then it will open at the bottom.

I am expecting, if `placement="bottomLeft"` is set, the it will always be like that.

Thanks!

**Comment by MadCcc** [comment]
Since dropdown will be adjust automatically, `placement` will be changed due to the position of target element.

**Comment by goran-dev** [comment]
Yeah I know and told you already. So placement="bottomLeft" doesn't work. "placement" is then automatic. If this will not be fixed, update API documentation accordingly

**Comment by S-ophie** [comment]
+1

**Comment by replygirl** [comment]
+1

**Comment by pmd5** [comment]
+1

**Comment by markqq** [comment]
+1

**Comment by anastasia-adv** [comment]
+1

**Comment by zombieJ** [comment]
Hi, Pls provide issue with reproduce instead of snapshot which can not help on dig the cause.

**Comment by tuanbui050198** [comment]
I use placement 'bottomLeft' but it renders 'topLeft'. please check again 
![21](https://github.com/ant-design/ant-design/assets/65756205/ac2e024c-e772-4953-9226-b778534a7356)
![22](https://github.com/ant-design/ant-design/assets/65756205/206d2a34-410a-477d-8288-5141d3c8fd1e)

**Comment by Rajil1213** [comment]
Apologies. Looks like I misread the issue. The solution I found applies to the `placement` value not being used in the [`Notification`](https://ant.design/components/notification) component created via the [`App`](https://ant.design/components/app) component and not the `Select` component. I have created a [separate issue](https://github.com/ant-design/ant-design/issues/43467).

**Comment by VasilNikolov** [comment]
> Hi, Pls provide issue with reproduce instead of snapshot which can not help on dig the cause.

The ticket author already provided an example [here](https://github.com/ant-design/ant-design/issues/40376#issuecomment-1410979638).

**Comment by Samuel-Montoya** [comment]
Anything on this issue? This is happening to me, only on Mobile where I have placement as bottomLeft, but it renders at the top.

**Comment by uazure** [comment]
Had issues with placement as well. For me the problem was not with the antd, but with the fact that for some reason overlay element had `position: absolute;` which wasn't expected and supported by antd.
