### ISSUE TITLE
getContainer prop description should be more clear

### ISSUE THREAD

**Issue by Raviranjan98210** [ant-design/ant-design#40371]
### Reproduction link

[https://4x.ant.design/components/modal/](https://4x.ant.design/components/modal/)

### Steps to reproduce

None 

### What is expected?

The getContainer prop specifies the DOM element to which the modal should be rendered. this prop allows you to specify a different DOM element, such as a div with a specific id.

### What is actually happening?

Return the mount node for Modal

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 18 |
| System | MacBook Air (M1, 2020) Big Sur version 11.2.3 (20D91) |
| Browser | Chrome (Version 109.0.5414.87 (Official Build) (arm64) |

**Comment by MadCcc** [comment]
If you have more suitable description of `getContainer`, PR is welcome~
