### ISSUE TITLE
Form method "resetFields" without async call does not correctly work with a ref

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#40387]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-1-6-forked-1p0bhh?file=/demo.tsx)

### Steps to reproduce

Type on the Username input and click on the "Reset" button, then type again and click on the "Reset async" button.

### What is expected?

When you click on the "Reset" button, the form should reset and should also focus the input correctly.

### What is actually happening?

The form resets but the input does not get focused on the ref, but if you fire the method via an async call, clicking the "Reset async" button, it works as intended.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | ^18.2.0 |
| System | Windows 10 |
| Browser | Brave |

---
Is the "resetForm" method an async one? Or is there something going on while on the same function we try to reset a pseudo state used by the form and also fire a call to a ref using focus?

**Comment by zombieJ** [comment]
Good question. `resetFields` will do unmount & re-mount field to avoid side effect such as customize component do not handle `undefined` value which makes `value` is undefined in Form store but still show as in input. So call reset and focus immediately does focus the input but in next React life cycle render, origin input is replaced by new input which do not have the focus.

And yes. Your await is a good solution. Let me make this issue as `Q&A`.

**Comment by balboFK** [comment]
@zombieJ Thank you! For now the solution that I found without using an await call was to create a state with a numeric value that is incremented everytime the form is reset, so I watch this state in a useEffect and call the `ref.focus()` method on it. Works aswell and you don't have to make your function async if you don't want to.
