### ISSUE TITLE
Note on classNames; no need for computed prop

### ISSUE THREAD

**Issue by STRML** [ant-design/ant-design#4038]
[This code](https://github.com/ant-design/ant-design/blob/72fad02024b13067fced75c22e60d23df5537927/components/anchor/index.tsx#L118) ([another example](https://github.com/ant-design/ant-design/blob/08e21e0a2f734069faea4857329c64ca4b42287a/components/switch/index.tsx#L33)):

```jsx
const classes = classNames({
  [className]: !!className,
  [`${prefixCls}-small`]: size === 'small',
});
```

Can be simplified to:

```jsx
const classes = classNames(className, {
  [`${prefixCls}-small`]: size === 'small',
});
```

[Runnable Example](https://runkit.com/582b986d443e280014695763/583c5f6bfb94e60014cd2b44).

**Comment by plandem** [comment]
oh! author of **grid** here. Is it possible to re-create **grid** in terms (and using) of antd only?! :)

**Comment by benjycui** [comment]
Yep.. But we don't have time to do this now. 

If someone is interested in this, just create a PR to `master`.
