### ISSUE TITLE
Tooltip does not handle "darkAlgorithm"

### ISSUE THREAD

**Issue by ivankravets** [ant-design/ant-design#40385]
### Reproduction link

[https://www.dropbox.com/s/bq0c0sd4lgj5app/antd-tooltip-issue.png?dl=0](https://www.dropbox.com/s/bq0c0sd4lgj5app/antd-tooltip-issue.png?dl=0)

### Steps to reproduce

```js
    <ConfigProvider
      theme={{
        algorithm: theme.darkAlgorithm,
        token: {
          colorBgBase: "#1e1e1e",
          colorText: "d4d4d4",
          colorPrimary: "#2B6398",
          borderRadius: "2px",
        },
      }}
    >
    <Tooltip title="Hello World"><Tag>tag</Tag></Tooltip>
   </ConfigProvider>
````

### What is expected?

Valid tooltip with "bottom arrow"

### What is actually happening?

A strange tooltip with a rectangle instead of the arrow

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | macOS |
| Browser | Firefox |

**Comment by Yuiai01** [comment]
Hello, I run similar code with one difference that I set borderRadius to 2.
~~~tsx
import React from 'react';
import { ConfigProvider, Tag, Tooltip, theme } from 'antd';

const App: React.FC = () => (
  <ConfigProvider
    theme={{
      algorithm: theme.darkAlgorithm,
      token: {
        colorBgBase: '#1e1e1e',
        colorText: 'd4d4d4',
        colorPrimary: '#2B6398',
        borderRadius: 2,
      },
    }}
  >
    <Tooltip title="Hello World">
      <Tag>tag</Tag>
    </Tooltip>
  </ConfigProvider>
);

export default App;
~~~
The following results are obtained.
![image](https://user-images.githubusercontent.com/112228030/214181484-9ca440ca-67a6-4b3f-8581-0e64f32c040c.png)

**Comment by Yuiai01** [comment]
I found that if you set borderRadius to 2px, then the problem you're talking about occurs. borderRadius can only be set to number or undefined according to typescript Settings.
![image](https://user-images.githubusercontent.com/112228030/214183335-677377b4-ff38-41eb-a08d-c4a44f939162.png)

**Comment by ivankravets** [comment]
@Yuiai01, thanks for the quick help! Sorry, it was my typo passing `pixels` to the border's radius. I used to the CSS where we use `border: 2px...`.

Small offtopic. Do you know how to achieve good UI with a dark theme while using [Segmented](https://ant.design/components/segmented) component? I checked the source code of the component ( https://github.com/ant-design/ant-design/blob/master/components/segmented/style/index.tsx#L53) and I see that the main BG is the same as the base BG. The resulting UI looks ugly. See the picture below:

<img width="238" alt="Screenshot 2023-01-24 at 12 11 44" src="https://user-images.githubusercontent.com/1760209/214265093-1895aeec-a7ca-4f2a-9f5b-a0f224605bb5.png">

**Comment by Yuiai01** [comment]
@ivankravets You can look at this https://ant.design/docs/react/customize-theme#consume-design-token. Maybe this will help you solve the problem.

**Comment by ivankravets** [comment]
Yes, I already use it. The issue is caused by the default "BG". If you set BG to dark, and do not apply extra "patches" to the components, some of the, look ugly. I mean, there is no correct "color autogeneration".

Maybe, it makes sense to provide a DARK theme on the official antd components documentation. After this, you will see that a lot of components are rendered with bad CSS.

In any case, thanks for the help. This issue is solved.
