### ISSUE TITLE
Another issue about hardcoded styles

### ISSUE THREAD

**Issue by cathayandy** [ant-design/ant-design#4039]
ref: #2424
I've got the same problem with him and I fixed some of them.

**Comment by benjycui** [comment]
Cool, could you just create a PR to `master`?

**Comment by benjycui** [comment]
@afc163 这个 commit 这样使用 `@body-background` 语义我觉得 OK https://github.com/cathayandy/ant-design/commit/dd22277504b68e903fbe23871629ce116fd8dfc0
