### ISSUE TITLE
Tooltip doesn't encapsulate all wrapped elements

### ISSUE THREAD

**Issue by dustinstender** [ant-design/ant-design#40392]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapsed-inline-menu-antd-5-1-6-forked-c5v6jc?file=/demo.tsx)

### Steps to reproduce

- Wrap two strings with a Tooltip
- The placement of the Tooltip should be "right"
- Wrap the second string inside the Tooltip with a span
- Add some styling to the span (float: "right")

### What is expected?

I would expect that if I hover over the span element, between the two strings, or over the first string that the Tooltip would appear to the right of the span element.

### What is actually happening?

The Tooltip appears to the right of the first child of the Tooltip, the string that isn't wrapped with a span element. Even when hovering over the span element, the Tooltip appears to the right of the first child of the Tooltip. Nothing happens when hovering between the two.

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.0.0 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
https://ant.design/components/tooltip#note
Wrap all of children with `span`, make sure children element could accept these events.

**Comment by dustinstender** [comment]
Thanks for getting back @MadCcc.

I wrapped both children with a `span` element, but still the tooltip only shows to the right of the first child of the outer `span` element. Even when hovering over "21" the tooltip shows up to the right of "hey".
