### ISSUE TITLE
List.Item.Meta 的 avatar和title错位

### ISSUE THREAD

**Issue by 565784135** [ant-design/ant-design#40390]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/c5fuet)

### Steps to reproduce

打开连接

### What is expected?

与官方文档显示结果一致  
https://ant-design.antgroup.com/components/list-cn#components-list-demo-basic

### What is actually happening?

与官方文档显示结果不一致

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | >=16.9.0 |
| System | window10 |
| Browser | chrome-109.0.5414.75 |

![8` NEY_WF%NUD3TQ18 EI24](https://user-images.githubusercontent.com/24539345/214242075-b4621afe-f7ad-431b-b8fb-6d9b0a94fa05.png)

**Comment by li-jia-nan** [comment]
其实也不算是 bug，因为 `<h4 />` 标签的默认带了margin，建议引入全局的 `reset.css` 文件
