### ISSUE TITLE
collapse fit header to content

### ISSUE THREAD

**Issue by long76** [ant-design/ant-design#40397]
### What problem does this feature solve?

using collapse header like a button

### What does the proposed API look like?

boolean property `fitHeaderToContent`

**Comment by MadCcc** [comment]
Could you give more description about your demand?

**Comment by long76** [comment]
> Could you give more description about your demand?

sure

now:

![ttt drawio](https://user-images.githubusercontent.com/18124433/215477755-60a61b03-2b73-4742-bb1e-0c560157f226.png)

with `fitHeaderToContent`:

![ttt drawio (1)](https://user-images.githubusercontent.com/18124433/215478484-961e6baa-7879-4b07-aeda-d4b2c5b276c4.png)


header with text will not have width parent - header will have width = text length like `span`

**Comment by long76** [comment]
it's usefull for `ghost` panels without borders

**Comment by long76** [comment]
and it's will set toggle area only on (text length + icon) width

**Comment by zombieJ** [comment]
Use `collapsible="header"` to config response region:

https://codesandbox.io/s/you-ling-zhe-die-mian-ban-antd-5-1-6-forked-wgc232?file=/demo.tsx

And if you want to make it real collapsed as span, you can use css to override. This `fitHeaderToContent` requirement may not added since it not match our Collapse component design.

**Comment by long76** [comment]
> Use `collapsible="header"` to config response region:
> 
> https://codesandbox.io/s/you-ling-zhe-die-mian-ban-antd-5-1-6-forked-wgc232?file=/demo.tsx
> 
> And if you want to make it real collapsed as span, you can use css to override. This `fitHeaderToContent` requirement may not added since it not match our Collapse component design.

but how i can align text header to `end`? for icon exist property `expandIconPosition`

**Comment by long76** [comment]
plus if use `collapsible="header"` icon do not have `pointer: cursor` style
