### ISSUE TITLE
theme for Table component doesn't work, need to customize header

### ISSUE THREAD

**Issue by DiRover** [ant-design/ant-design#40406]
### What problem does this feature solve?

After migration from v4 to v5, in some places vertical borders of table header cells were disappeared.

### What does the proposed API look like?

I want to resolve this by adding new style for table via theme, but when I try to add something like this nothing works:
```
export const theme = {
    token: {
        colorPrimary: '#207ca3',
    },
    components: {
        Table: {colorBorder: 'red'},
    },
} satisfies ThemeConfig;
```
And I don't understand how to apply styles, border I mean, exactly to table header via theme, and I don't see anything similar in TableToken

**Comment by MadCcc** [comment]
Trace in https://github.com/ant-design/ant-design/issues/38975
