### ISSUE TITLE
Links are not crawlable on lighthouse

### ISSUE THREAD

**Issue by swadique** [ant-design/ant-design#40403]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5w52g0?file=/index.js)

### Steps to reproduce

The lighthouse still shows the "links are not crawlable"

### What is expected?

The error should not be shown on the lighthouse

### What is actually happening?

Showing an issue on the seo score

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | react |
| System | 17.0.2 |
| Browser | Version 109.0.5414.87 (Official Build) (arm64) |

---
https://codesandbox.io/s/antd-reproduction-template-forked-5w52g0?file=/index.js

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/25792582/214344432-fd05a609-2670-49d7-8d7e-aa6355994025.png">

**Comment by ilhamkukuh** [comment]
> It's common to add `rel="nofollow"` to pagination links, which in my opinion is not an issue.

where I put rel="nofollow", I have tried but nothing changes?
