### ISSUE TITLE
Tour component is not responsive / working on mobile

### ISSUE THREAD

**Issue by mleister97** [ant-design/ant-design#40419]
### Reproduction link

[https://ant.design/components/tour](https://ant.design/components/tour)

### Steps to reproduce

Simply open the tour on a mobile phone

![photo1674842112](https://user-images.githubusercontent.com/16700053/215159588-8c556318-1373-4cd6-9fb2-33f902d34b5c.jpeg)

### What is expected?

To be responsive

### What is actually happening?

Tour is not responsive, I cannot even close the tour. The site stops working as I also cannot scroll.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Latest Chrome |

**Comment by azharhussain96** [comment]
Running into similar issue - width is being set explicitly to 520px in the Ant stylesheet. Tour component does not seem to accept inline styles to override and `ConfigProvider` for Tour component does not have a property for width.

Seems like a very simple implementation to be able to pass in width as I can manipulate it just fine from Browser inspector.

**Comment by mendahu** [comment]
Is there a plan to have this fixed? The Tour component is essentially unusable on Mobile.

**Comment by gerjand** [comment]
Any updates on this?

**Comment by mxye** [comment]
I use 

```.ant-tour-content {
  max-width: 100vw;
 margin: auto;
}``` 

as a workaround, and it seems to work

**Comment by tuzua** [comment]
use 
.ant-tour 
  max-width: fit-content
if using saas or 

.ant-tour  {
  max-width: fit-content
} if using css

**Comment by solomkinmv** [comment]
For me, workaround suggested by @mxye didn't work in 100% of cases. For some reason some of the tour steps were outside of the screen boundaries.
Option from @tuzua works perfectly:
```
.ant-tour {
    max-width: fit-content
}
```

**Comment by sholatel** [comment]
This works for me perfectly 

.ant-tour {
    width: fit-content;
    max-width: 100%
}
