### ISSUE TITLE
ReactDom.render到window.open新窗口时事件错位

### ISSUE THREAD

**Issue by fgfg163** [ant-design/ant-design#4041]
当我在主窗口用window.open新建一个窗口，并把ReactDom.render渲染到这个窗口时，发现一些组件，例如Select出现问题。Select的下拉列表隐藏事件注册到了主窗口里，就是点击子窗口下拉列表不消失，点击主窗口下拉列表反而消失了。

Select下拉列表组件被生成到主窗口的问题可以用getPopupContainer解决，而关闭窗口事件则无法解决

```
let theSelectWindow;


  theSelectWindow = window.open("", "iwmdtwindow", "");

  store.dispatch(setChildWindow(theSelectWindow));

  let rootDom = theSelectWindow.document.querySelector('#iwmdt_react_root');
  if (!rootDom) {
    rootDom = theSelectWindow.document.createElement('div');
    rootDom.id = "iwmdt_react_root";
    theSelectWindow.document.body.appendChild(rootDom);
  }
  ReactDOM.render(<RootComponent/>, rootDom);

  theSelectWindow.onbeforeunload = function () {
    ReactDOM.unmountComponentAtNode(rootDom);
    return void(0);
  }
```
这段代码在主窗口运行，里面获取到的window也是主窗口的。然而我希望内容显示在子窗口里

**Comment by benjycui** [comment]
简单粗暴的方法是加个 `getDocument` 之类的方法。。

**Comment by fgfg163** [comment]
@benjycui 具体的方法？

**Comment by afc163** [comment]
如果可以的话就尝试 PR 吧，我们现在人手紧张。

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/trigger/pull/40

**Comment by benjycui** [comment]
@fgfg163  rc-trigger had support `getDocument` see https://github.com/react-component/trigger/pull/40

But we still need to update other components to expose it.

Could you just list components which you had met this problem here?

And it will be better to try to PR, too.

**Comment by benjycui** [comment]
Close now, it's an edge case. I am not going to spend time on collect all the edge cases.

Just fix it one by one when we meet them.
