### ISSUE TITLE
TimePicker is missing style folder

### ISSUE THREAD

**Issue by nataliakukula** [ant-design/ant-design#40420]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0pinq9)

### Steps to reproduce

Issue:

Ant Design version 5 is producing Uncaught Error: Cannot find module 'antd/lib/time-picker/style' when importing TimePicker.

See StackOverflow issue:

https://stackoverflow.com/questions/74688880/how-to-solve-timepicker-import-problem-on-ant-design-5-0-3

Bug:

When looking into the node_modules/antd folder it seems that time-picker folder component doesn't include any style folder, but all other components have one. I'm guessing it's missing a file from moving time-picker outside of the date-picker folder since release 5.0.0.

To reproduce:

Import Ant Design: yarn add antd
Add time-picker to file: import {TimePicker} from 'antd'
Implement it.
You will get the module error.

Version: ^5.0.0.

### What is expected?

If you copy and paste the style folder from date-picker into the time-picker folder it seems to work.

### What is actually happening?

TimePicker cannot be used in a production pipeline.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | React ^17.0.0 |
| System | Node v16.13.2 |
| Browser | Chrome Version 109.0.5414.119 (Official Build) (x86_64) |

---
Link to reproduce doesn't give the error, because of missing node modules.

**Comment by afc163** [comment]
Please remove babel-plugin-import after 5.0.0. 

See https://ant.design/docs/react/migration-v5-cn/
