### ISSUE TITLE
[tabs]: docs error in `tabPosition` API type.

### ISSUE THREAD

**Issue by tilakbasyal** [ant-design/ant-design#40429]
### Reproduction link

[https://ant.design/components/tabs#tabs](https://ant.design/components/tabs#tabs)

### Steps to reproduce

The `Tabs` component's API type of`tabPosition` has a typo resulting in mistakes in `Type`, `Version` and `Default` fields.
https://ant.design/components/tabs#tabs

### What is expected?

Typo should be fixed with proper type of `tabPosition` API.
| tabPosition | Position of tabs | `top` \| `right` \| `bottom` \| `left` | `top` |  |
instead of
| tabPosition | Position of tabs | `top` \| `right` \| `bottom` \  | `left` | `top` |  |

### What is actually happening?

The `Tabs` component's API type of`tabPosition` has a typo resulting in mistakes in `Type`, `Version` and `Default` fields.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React |   ^18.0.0 |
| System | macOS Monterey |
| Browser | Firefox Browser, 108.0.2 (64-bit) |

**Comment by Yuiai01** [comment]
The reason is that there is a blank space. I'll fix it.
![image](https://user-images.githubusercontent.com/112228030/215300308-da71eceb-deca-4352-ac2b-04e29b03cd97.png)
