### ISSUE TITLE
Promotion Wanted

### ISSUE THREAD

**Issue by cihadturhan** [ant-design/ant-design#4042]
From Maintainer: 

We published `antd` in 2015, and it's stabled and practical now. Actually, hundreds of systems in Ant Financial are built with `antd`, so we must make sure that `antd` is practical and robust(that's our job).

So, just use `antd` in your next project, and recommend it to your friends and colleagues. It won't disappoint you.

---

I saw this UI Kit today and admired the work done. All the little details, careful design and simplicity made me excited a lot. It will be definitely my next UI kit.
Thanks.

Feel free to close this issue.

**Comment by visvadw** [comment]
Indeed, this React.js based UI library is absolutely superb! 😄 
It deserves some articles so that many will start enjoying it.
I will definitely start writing one or two before this year ends.

**Comment by jihdeh** [comment]
I agree, it's a good job well done. I'm going to write an article on this too.

**Comment by ifokeev** [comment]
Antd, thank you a lot. (But Is there a way to make bundle less size?)

**Comment by yesmeck** [comment]
@ifokeev See https://ant.design/docs/react/getting-started?locale=en-US#Import-on-Demand

**Comment by benjycui** [comment]
Thanks! It's a good idea to write article about `antd` or just recommend it to your friends and colleagues.

For all the members of `antd` team are Chinese, and we feel hard to promote `antd` to global community.

**Comment by benjycui** [comment]
I updated @cihadturhan 's comment, and this issue will keep opening for some time.

**Comment by visvadw** [comment]
@benjycui Hi Benjy, why do you think is hard to promote `antd` and how can I help you in this case, besides creating some articles and tutorials?

As I appreciate the quality of this product and the good feedback from some of the team members like you, @afc163, and @GrayChoi, I had a great satisfaction contributing to some of the english translations and reviews. That is why I am asking about helping with promoting it.

**Comment by visvadw** [comment]
Yesterday, Fullstack React team tweeted about Ant Design library:
https://twitter.com/fullstackreact/status/803318827081732097

**Comment by benjycui** [comment]
@visvadw just because we are not familiar with global community, and most of our teammate have no time to write article..

**Comment by visvadw** [comment]
@benjycui Alright, I will start writing articles or tutorials on `antd`, being sure that I will get feedback from AntD team, if needed.

**Comment by javier-tarazaga** [comment]
Hi @benjycui! 

First of all, thank you so much for this awesome library. 

Apart from writing articles as the guys have suggested would be for me I guess one of the first things I would suggest would be to write everything in English. I can see many of the issues are written in Chinese which does not help if you want to search for issues, read comment or contribute.

**Comment by benjycui** [comment]
@javier-tarazaga yep.. but we cannot push others to write issues in English..

**Comment by afc163** [comment]
Anyone can help at this ? https://github.com/ant-design/ant-design/issues/4353

**Comment by afc163** [comment]
[Styling React Applications with Ant.Design](https://medium.com/@yoniweisbrod/styling-react-applications-with-ant-design-92b742aab0b0)
