### ISSUE TITLE
Text alignment issue with Typography component in Select component

### ISSUE THREAD

**Issue by keita-determined** [ant-design/ant-design#40421]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-1-6-forked-izq79l?file=/demo.tsx)

<img width="152" alt="image" src="https://user-images.githubusercontent.com/109113616/215223090-5fe52be8-6c78-4c2a-990f-c5d17dc9367c.png">

### Steps to reproduce

- Set value with antd typography component for Select component
- Select the value
- Text is not aligned center

### What is expected?

Text alignment is centered

### What is actually happening?

Text alignment is not centered

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | macOS Ventura |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
let me try~

**Comment by Yuiai01** [comment]
I found that simply adding the following styles would solve the problem.
![image](https://user-images.githubusercontent.com/112228030/215238738-55544860-c893-4d0f-aeeb-5a1174f9bd0b.png)

**Comment by keita-determined** [comment]
i didnt test this, but setting a `line-height` could be a solution.

**Comment by LongHaoo** [comment]
I don't think this is a BUG, We can't count on the alignment of the block elements inside the Input.
It will create more problems

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/43097 is reverted.
