### ISSUE TITLE
Upload maxCount not working

### ISSUE THREAD

**Issue by imsimgaa022** [ant-design/ant-design#40430]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mlz9sb?file=/index.js)

### Steps to reproduce

When you set maxCount prop, you can still chose any number of files to upload.
List is still as you set the maxCount, but you are still able to choose more than maxCount set

### What is expected?

If you set maxCount={5} you shouldn't be able to select more than 5 files.
Same as it is when you set multiple={false}, you can chose only 1 file.

### What is actually happening?

You can choose X number of files to upload, no matter maxCount is set to something or not.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.1 |
| System | MacOS 13.0.1 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Upload is a wrap of native `<input type="upload" />`. Seems spec not provide the limitation attr. We can not help on this. Sorry : (

**Comment by edmundsj** [comment]
Then why on earth is it in the component spec? It should be removed. Having this issue as well.

**Comment by archisketch-thangly** [comment]
> Upload is a wrap of native `<input type="upload" />`. Seems spec not provide the limitation attr. We can not help on this. Sorry : (

@zombieJ  So is there a way we can prevent this? I use `customRequest` and it loads all files not stop at file number like `maxCount`

**Comment by ahmad-punch** [comment]
Any update here? I'm facing the same issue.

**Comment by lamhungypl** [comment]
Does anybody have a workaround to prevent auto-uploading out-of-range files? 
I'm trying `beforeUpload` but no luck because batch React setState ( below length not updated at the time `beforeUpload` ran)

```typescript
     <Upload
        beforeUpload={(file) => {
          if (fileList.length >= MAX_COUNT) {
            return false;
          }
        }}
```

**Comment by robert-obendorf** [comment]
Here's a simple work around.

```js
     <Upload
        beforeUpload={(file, newFileList) => {
          if (newFileList.findIndex(f => f.name === file.name) + 1 + fileList.length > MAX_COUNT) {
            return Upload.LIST_IGNORE;
          }
        }}
```
