### ISSUE TITLE
ConfigProvider设置message组件圆角无效

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#40459]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-p2hzkc?file=/index.js:145-155)

### Steps to reproduce

点击名为message的按钮可以看到

### What is expected?

设置borderRadius后message的圆角应该和borderRadius保持一致

### What is actually happening?

message的圆角不能通过ConfigProvider来统一设置。

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | react 18 |
| System | Windows 10 |
| Browser | Chrome 104.0.5112.102 |

**Comment by MadCcc** [comment]
静态方法不受 ConfigProvider 的 context 影响。推荐使用 hooks 或者 App 组件。

**Comment by xiaoliu1990** [comment]
> 静态方法不受 ConfigProvider 的 context 影响。推荐使用 hooks 或者 App 组件。
https://ant-design.antgroup.com/theme-editor-cn
那这个在主题编辑器里面改动就会生效。

**Comment by xiaoliu1990** [comment]
@MadCcc 
https://ant-design.antgroup.com/theme-editor-cn
那这个在主题编辑器里面改动就会生效。

**Comment by MadCcc** [comment]
> 推荐使用 hooks 或者 App 组件。

这两种方法才能受 context 控制。

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/issues/40456
另一个问题
目前可以参考这种方式手动将 hooks 的 instance 暴露出来：https://ant-design.antgroup.com/components/app-cn#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF
