### ISSUE TITLE
[Question] Can we update JSS realtime when use wrapSSR without reload web browser?

### ISSUE THREAD

**Issue by doiya46** [ant-design/ant-design#40452]
### What problem does this feature solve?

Demo code sandbox https://codesandbox.io/s/how-to-realtime-wrapssr-g5xuti?file=/demo.tsx

Jss with wrapSSR does not realtime change.

```ts
import React from "react";
import "./index.css";
import { Space, theme } from "antd";
import { useStyleRegister } from "antd/es/theme/internal";
import type { CSSInterpolation } from "@ant-design/cssinjs";

const { useToken } = theme;

const genCss = (): CSSInterpolation => {
  return {
    [`.classA`]: {
      color: "red"
    }
  };
};

const App: React.FC = () => {
  const { token, theme } = useToken();
  const wrapSSR = useStyleRegister({ token, theme, path: ["app"] }, () => [
    genCss()
  ]);

  return wrapSSR(
    <Space wrap>
      <div className="classA">A</div>
      <div className="classB">B</div>
    </Space>
  );
};

export default App;
```

### What does the proposed API look like?

When we change `classA` color from `red` to `blue` and save, color is change without reload web browser

**Comment by arvinxx** [comment]
no. `@ant-design/cssinjs` is a component-level solution, not for application. https://ant.design/docs/blog/css-in-js

If you want to use cssinjs in application, you can try with styled or emotion, and we are also working on a app-level solution combined with antd v5 token system.

**Comment by aspen1234** [comment]
> no. `@ant-design/cssinjs` is a component-level solution, not for application. https://ant.design/docs/blog/css-in-js
> 
> If you want to use cssinjs in application, you can try with styled or emotion, and we are also working on a app-level solution combined with antd v5 token system.

可以支持less的global的语法吗？
