### ISSUE TITLE
Namespace 'React' has no exported member 'SFC'

### ISSUE THREAD

**Issue by luluqweasd** [ant-design/ant-design#40451]
### Reproduction link

[https://4x.ant.design/components/table/#components-table-demo-drag-sorting-handler](https://4x.ant.design/components/table/#components-table-demo-drag-sorting-handler)

### Steps to reproduce

Alternatively you can implement drag sorting with handler using react-sortable-hoc，then，
yarn build

### What is expected?

build succeeded

### What is actually happening?

yarn run v1.22.19
$ tsc && vite build
node_modules/react-sortable-hoc/types/index.d.ts:108:11 - error TS2694: Namespace 'React' has no exported member 'SFC'.

108   | React.SFC<P>
              ~~~


Found 1 error in node_modules/react-sortable-hoc/types/index.d.ts:108

error Command failed with exit code 2.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | - |
| Browser | chrome |

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by luluqweasd** [comment]
This question is encountered when v4 to v5

**Comment by afc163** [comment]
It is  `react-sortable-hoc`'s problem, not antd's.
