### ISSUE TITLE
`AutoComplete` will show a clear icon in the input suffix, if add `Input` as `AutoComplete` `children`

### ISSUE THREAD

**Issue by Ayuilos** [ant-design/ant-design#40450]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cha-xun-mo-shi-que-ding-lei-mu-antd-5-1-6-forked-lrvqj0?file=/demo.js)

### Steps to reproduce

Pls check the link

### What is expected?

As you can see, here comes a clear icon and this clear icon color will always be "blue".

I hope "No clear icon, or the clear icon follow my global theme config"

### What is actually happening?

An unexpected clear icon appears and also doesn't follow theme config.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | MacOS 13.1 |
| Browser | 103.0.5060.134 |

**Comment by Ayuilos** [comment]
I forget to say that you have to input something first

**Comment by Ayuilos** [comment]
Another unexpected problem is that when I press `ESC`, the content of the input are cleared, but this is not always the case. 

You could try the examples you provided in the `AutoComplete` component page.

**Comment by MadCcc** [comment]
Pressing `ESC` to clear input is native behavior of input when `type="search"`, which is not handled by antd.
