### ISSUE TITLE
[建议]更多的图标(Icon)库

### ISSUE THREAD

**Issue by yubozhao** [ant-design/ant-design#4046]
有时还得用fontawesome的比如控制播放器的（声音大／小／静音）。

**Comment by benjycui** [comment]
还是重新打开这个？ https://github.com/ant-design/ant-design/issues/1473

开发者可以根据需要 import iconfont 集。

**Comment by yubozhao** [comment]
如果能import也很好。  只是希望ant design的icon包能更充实点， 现在有点少

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3674

**Comment by afc163** [comment]
另外你也可以直接配合业界框架使用：https://github.com/andreypopp/react-fa

**Comment by yubozhao** [comment]
我在用类似的react-fontawesome， 谢谢。   有 #3674 我就把这个关了
