### ISSUE TITLE
Multiple nested form list, and form items do not render value in input

### ISSUE THREAD

**Issue by JuanPedroPontVerges** [ant-design/ant-design#40462]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/size-antd-5-1-6-forked-315hum?file=/demo.tsx)

### Steps to reproduce

1.  Click DEBUG button
2.  See form watcher logs in output.
3.  Verify that form watcher has values, but the values are not rendered in the input. The only thing rendered are the amount of items in the array.

### What is expected?

To set values to all input fields, and

### What is actually happening?

It´s not rendering input value in nested item

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | react |
| System | Windows |
| Browser | Brave |

---
So i was trying to dinamically set form values in a complex Form with a lot of nested Form.Lists and its only setting the values, and not rendering the value itself in the input

**Comment by zombieJ** [comment]
This reproduce is little complex with too many content. Could you help to simplify this reproduce?

**Comment by zombieJ** [comment]
Field should directly wrap out of component. You wrap on the `<Row />` which do not have `value` control:

https://codesandbox.io/s/size-antd-5-1-6-forked-xdu48z?file=/concatenation.component.tsx
