### ISSUE TITLE
map遍历Tag时，如果使用遍历索引作为key，会导致相邻兄弟元素被隐藏掉

### ISSUE THREAD

**Issue by hotfireeagle** [ant-design/ant-design#40465]
### Reproduction link

[https://stackblitz.com/edit/react-ts-31ptjd?file=App.tsx](https://stackblitz.com/edit/react-ts-31ptjd?file=App.tsx)

### Steps to reproduce

删除第一个标签

### What is expected?

显示标签2和标签3

### What is actually happening?

显示标签3

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | macOS Monterey 12.3.1 |
| Browser | chrome 109.0.5414.119 |

---
大致看了一下，感觉和tag源码中关于这个样式这块引起的一样：

```jsx
// line75
const [wrapSSR, hashId] = useStyle(prefixCls)
```

对于这种删除的场景，react复用了第二个标签，但是antd不知道内部为何又给它加了一个hidden的样式，而且还是滞后添加的一样。

噢对了，如果想避免这个问题发生的话，可以不用索引作为key，而是使用特有id。但是为什么使用索引作key时会出现这个问题还是有些奇怪的。

**Comment by MadCcc** [comment]
不要使用索引作为 key，列表每一项的 key 都应该是独特的，否则列表增删或者更新的时候会有渲染问题。
