### ISSUE TITLE
message 内 icon 颜色被错误的指定

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#40467]
### Reproduction link

<img width="352" alt="image" src="https://user-images.githubusercontent.com/7264444/215654976-46d18d49-4402-482b-8436-66d18a491f5e.png">

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qi-ta-ti-shi-lei-xing-antd-5-1-6-forked-snyxgy?file=/demo.tsx)

### Steps to reproduce

点击 error 按钮

### What is expected?

在消息中，仅 IconError 为红色，其余 icon 还是默认颜色（注：此处应该 inherit 自 Typography.Link 的蓝色）

### What is actually happening?

错误指定了其他 icon 的颜色

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18 |
| System | macOS 11.7(M1) |
| Browser | Chrome 108 |

**Comment by Wxh16144** [comment]
Leave it to me to fix.
