### ISSUE TITLE
theme token: colorPrimary not work when use css :root selector to set color variable

### ISSUE THREAD

**Issue by jim19901103** [ant-design/ant-design#40470]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qfqqtr?file=/index.js)

### Steps to reproduce

index.css file set 
:root {
  --colorBorder: red;
  --colorPrimary: #3266ff;
}

import "./index.css" after import "antd/dist/reset.css";

在 ConfigProvider 中传入 theme, 然后设定 
token: { 
  colorBorder: "var(--colorBorder)", // work
  colorPrimary: "var(--colorPrimary)",  // not work
  // colorPrimary: "#3266ff"  // work
}

colorBorder is work but colorPrimary not work

### What is expected?

color will be set correctly

### What is actually happening?

color not be set correctly

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.x |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
antd Design Token Modal do not accept css variables. It use js to calculate derivative color.

**Comment by jim19901103** [comment]
> antd Design Token Modal do not accept css variables. It use js to calculate derivative color.

Thanks for reply, I found a solution to solve

```
const styles = getComputedStyle(document.documentElement);

root.render(
  <ConfigProvider
    theme={{
      token: {
        colorPrimary: styles.getPropertyValue("--colorPrimary")
      }
    }}
  >
    <App />
  </ConfigProvider>
);
```
