### ISSUE TITLE
Select broken on mode tags when have options with number values and add double with input

### ISSUE THREAD

**Issue by Asanio06** [ant-design/ant-design#40483]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tags-antd-5-1-7-forked-ywnz0i?file=/demo.tsx)

### Steps to reproduce

Use Select on mode="tags"
Use options list with value of type number only
write the double 2.2 in select 
check options display
new value is not add in dopdown and when you scroll down you see that the select is broken

### What is expected?

I think when i have options with only number and i add double, it should add this options

### What is actually happening?

new value is not add in dopdown and when you scrool down you see that the select is broken

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 17 |
| System | MacOs |
| Browser | Chrome |

**Comment by MadCcc** [comment]
There's warning here: 
![image](https://user-images.githubusercontent.com/27722486/215933208-c72db2d9-23b7-4be5-a7c8-afa1f4a5ab80.png)

**Comment by Asanio06** [comment]
Thanks @MadCcc
