### ISSUE TITLE
Changes to success percent section in the progress component are not animated

### ISSUE THREAD

**Issue by opike** [ant-design/ant-design#40481]
### Reproduction link

[https://codepen.io/opike99/pen/MWBPjKo](https://codepen.io/opike99/pen/MWBPjKo)

### Steps to reproduce

Click on the   and - buttons to see that the successPercent indicator is not animated

The minimal reproduction is the  example "Dynamic" from this page:
https://ant.design/components/progress

With the line 
`      <Progress percent={percent} />`
changed to
`      <Progress successPercent={percent} />`

### What is expected?

The portion of the progress that represents success percent should be animated when it changes

### What is actually happening?

Changes are not animated

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | Mac OS 13.1 |
| Browser | Chrome 109.x |

**Comment by opike** [comment]
It's also missing the rounded termination.
<img width="225" alt="Screenshot on 2023-01-31 at 11-32-14" src="https://user-images.githubusercontent.com/2823563/215863706-d64ad005-87b1-4ba2-9356-8f99409c84d3.png">

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/40378
Is this PR related？

**Comment by MadCcc** [comment]
Broken in v5
