### ISSUE TITLE
TypeError: getFieldDecorator is not a function

### ISSUE THREAD

**Issue by wudechang** [ant-design/ant-design#4048]
直接饮用“动态增加、减少表单项”实例，报题目这个错误

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
先确认你的 `antd` 版本 >2.0

**Comment by wudechang** [comment]
好的，多谢


发自网易邮箱大师
在2016年11月29日 17:29，Benjy Cui 写道:

先确认你的 antd 版本 >2.0

**Comment by wudechang** [comment]
Because the version is lower than 2.0...sorry!


发自网易邮箱大师
On 11/29/2016 16:05, Wei Zhu wrote:

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
