### ISSUE TITLE
Custom component with panel does not expandable within Collapse component

### ISSUE THREAD

**Issue by no0dly** [ant-design/ant-design#40484]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapsible-antd-5-1-7-forked-n9m5mf?file=/demo.tsx)

### Steps to reproduce

- Put the Panel within separate component
- Wrap this new component within Collapse component,

### What is expected?

- content should be collapsable
- icon should be presenting

### What is actually happening?

- Content is not collapsible
- Icon is not presented

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | MacOS 13.1 (22C65) |
| Browser | Chrome 109.0.5414.119 |

---
Found similar issue here: https://github.com/ant-design/ant-design/issues/36327
![Screenshot 2023-01-31 at 11 17 31 AM](https://user-images.githubusercontent.com/8776095/215860704-d7e19136-d6b9-44d3-8a95-6f3cf7dea78b.png)

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/36327#issuecomment-1171840648

**Comment by afc163** [comment]
https://codesandbox.io/s/collapsible-antd-5-1-7-forked-nmxw78?file=/RandomPanel.tsx
