### ISSUE TITLE
Tabs nav-more button adds an extra height

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#40482]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/slide-antd-5-1-7-forked-51668t?file=/demo.tsx)

### Steps to reproduce

The overflow is already visible

### What is expected?

For Tabs to not exceed expected height

### What is actually happening?

Tabs parent might have overflow: scroll, or Tabs might be at the full height of the page.
Tabs button .ant-tabs-nav-more has :after rule, which translates it below the button, what causes the extra 5px height

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18 |
| System | Windows 10 |
| Browser | Firefox, Chrome |

---
In the example, I added css with background-color to the :after element on hover, for better visualization

**Comment by MadCcc** [comment]
Seems that this peseudo is meaningless? Not sure if save to remove.

**Comment by IndProgo** [comment]
It is still present in v5.2.0, though the changelog says it's fixed
