### ISSUE TITLE
Table 和Form一起使用pagination样式被打乱

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#4049]
- antd 版本: 最新
- 操作系统及其版本: WIN7 
- 浏览器及其版本: Chrome 最新

如果Table 和Form 一起使用 ，并且Table设置了pagination，会看到pagination的样式排列显示不正常。详情看：  http://codepen.io/zzcode/pen/YpredZ?editors=001

**Comment by yesmeck** [comment]
为什么要嵌套呢？

**Comment by zhonggithub** [comment]
复杂页面  我这个例子写的比较简单

**Comment by benjycui** [comment]
@zhonggithub 你需要收集 Table 里面的数据么。

**Comment by benjycui** [comment]
或者可以这样：

```
<div>
  <Form />
  <Table />
  <Form />
</div>
```

**Comment by benjycui** [comment]
`Form` 本身就是个布局组件。

**Comment by zhonggithub** [comment]
嗯  也可以
