### ISSUE TITLE
Create before sort event hook on Table component

### ISSUE THREAD

**Issue by zhurasique** [ant-design/ant-design#40495]
### What problem does this feature solve?

I want to handle a before sort event on a Table component. It will allows me to make some logic before sorting will start.

### What does the proposed API look like?

Create property which will called "beforeSortChange" or "beforeChange".

**Comment by MadCcc** [comment]
Make sort controlled is recommended. You could wrap Table with hoc or other ways to solve it.

**Comment by BrotaOne** [comment]
> Make sort controlled is recommended. You could wrap Table with hoc or other ways to solve it.

do you mean do like the example custom selection?

but it's complex, and some surplus code. Changing filter icon is much easier
