### ISSUE TITLE
table columns项配置fixed，render方法中使用tooltip显示位置不正确

### ISSUE THREAD

**Issue by Thinking80s** [ant-design/ant-design#40492]
### Reproduction link

[https://4x.ant.design/components/tooltip-cn/](https://4x.ant.design/components/tooltip-cn/)

### Steps to reproduce
[https://codesandbox.io/s/gu-ding-lie-antd-4-24-7-forked-971c53](url)
table columns 中 render 方法
<Tooltip
          placement="top"
          title={desc}
          getPopupContainer={(triggerNode: any) => triggerNode}
        >
          <div className={S.desc}>{desc}</div>
        </Tooltip>

### What is expected?

能够正常显示tooltip位置

### What is actually happening?
<img width="337" alt="image" src="https://user-images.githubusercontent.com/338079/216008844-0477a916-63ff-4676-b851-d579711af3b2.png">

没有正常显示tooltip位置

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 17.0.2 |
| System | macos 12.6.1  |
| Browser | 版本 109.0.5414.119（正式版本） (x86_64) |

**Comment by Yuiai01** [comment]
能提供一个复现问题的链接吗？

**Comment by luo3house** [comment]
getPopupContainer 指向 triggerNode 也就是头像昵称那个 Cell，Cell 把 Tooltip 挡住了

**Comment by Thinking80s** [comment]
> 

去掉是可以，但是列表滚动情况tooltip不会跟随了

**Comment by Thinking80s** [comment]
> 能提供一个复现问题的链接吗？

https://codesandbox.io/s/gu-ding-lie-antd-4-24-7-forked-971c53

**Comment by MadCcc** [comment]
试试把 container 放在滚动区域上？

**Comment by afc163** [comment]
> 试试把 container 放在滚动区域上？

可以使用这种方式。
