### ISSUE TITLE
表格头部 header 相对于表格向右溢出

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#40498]
### Reproduction link

[https://stackblitz.com/edit/react-ts-q4ucrl?file=App.tsx,style.css,node_modules%2Fantd%2Flib%2Ftable%2FTable.d.ts](https://stackblitz.com/edit/react-ts-q4ucrl?file=App.tsx,style.css,node_modules%2Fantd%2Flib%2Ftable%2FTable.d.ts)

### Steps to reproduce

1. 需要设置表格的纵向滚动高度
2. 表格终端数据值的总高度小于设置的滚动高度

### What is expected?

1. 通常情况下我们需要表格尽量铺满整个页面，所以需要设置一个滚动高度。但有时返回的数据量少，不足以使得表格出现滚动条，此时表格头部就会向右溢出，溢出的宽度将是计算出的滚动条宽度
2. 可能的解决方案是将 ant-table-body 的样式设置成 overflow-y: auto (而不是 scroll)。计算 scrollHeight 是否大于 clientHeight, 大于设置 th.ant-table-cell {right: 滚动条宽度}

### What is actually happening?

表格头部 header 相对于表格向右溢出

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 16.8.6 |
| System | windows11 |
| Browser | Google 100.0.4896.60 |

---
![image](https://user-images.githubusercontent.com/30885718/216225698-46f98bcd-3cef-426c-a356-4beb39f8cff5.png)
![image](https://user-images.githubusercontent.com/30885718/216225883-7bd82cdc-033c-4d1b-9b74-17b21716023c.png)

**Comment by afc163** [comment]
给的例子好像无法重现？
