### ISSUE TITLE
部分场景下，左键点击 Select 的下拉箭头无反应

### ISSUE THREAD

**Issue by UNIkeEN** [ant-design/ant-design#40496]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-445lzi)

### Steps to reproduce

左键点击结点中 Select 的右侧下拉箭头按钮

### What is expected?

Select 的下拉框正常弹出

### What is actually happening?

选中 Select 可以获得焦点，但左键下拉箭头没有反应（下拉框没有弹出），而右键下拉箭头有反应（下拉框弹出）

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 109.0.5414.120 |

---
将 reactflow 结点中的 Select 换作 InputNumber、TreeSelect 亦有此问题，换作如 DatePicker 则其右侧日历图标可以正常点击
而同样添加在结点右上角的 Button 可以正常左键点击

**Comment by zombieJ** [comment]
antd 侧没做什么 magic code，都是 React 生命周期的事件处理。可以给 `reactflow` 反馈一下，或者看看它们文档是否有什么可配置的选项。

**Comment by ritawr** [comment]
请问后来怎么解决了？
