### ISSUE TITLE
Modal中的Form.Item设置了help后，重置表单导致原Form.Item的marginBottom发生变化

### ISSUE THREAD

**Issue by xihayouyi** [ant-design/ant-design#40500]
### Reproduction link

[https://github.com/xihayouyi/demo1.git](https://github.com/xihayouyi/demo1.git)
[http://oss.cn-software.top/](http://oss.cn-software.top/)

### Steps to reproduce

1）点击表单的”重置“按钮
2）设置了"help"的表单项的marginBottom发生了变化

### What is expected?

点击表单的”重置“按钮后，显式的设置了'help'的表单项的marginBottom不应该有变化

### What is actually happening?

点击了表单的”重置“按钮后，设置了'help'的表单项的marginBottom间距变化了

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | macOS Monterey12.5 |
| Browser | Chrome108.0.5359.98 |

**Comment by Yuiai01** [comment]
感觉是这个的问题
![image](https://user-images.githubusercontent.com/112228030/216252539-621ec2a6-c7d9-47dd-a7b9-1e60a00e1616.png)

**Comment by xihayouyi** [comment]
@Yuiai01 是的，如果Form没有放在Modal中，带"help"的表单项默认都会有”ant-form-item-margin-offset“。而把Form放在Modal中后，带'help'的表单项默认就没有”ant-form-item-margin-offset“，表单”重置“后才会出现。

**Comment by vw2c** [comment]
UMD环境下，Form在Modal里，表单项校验失败时会出现这个`ant-form-item-margin-offset`，UI表现是突然塌陷

![image](https://github.com/ant-design/ant-design/assets/11835233/b09c5182-e425-436e-bc83-9b3d802071e0)

**Comment by Yuiai01** [comment]
> UMD环境下，Form在Modal里，表单项校验失败时会出现这个`ant-form-item-margin-offset`，UI表现是突然塌陷

能整个在线项目吗，方便排查一些。

**Comment by vw2c** [comment]
> > UMD环境下，Form在Modal里，表单项校验失败时会出现这个`ant-form-item-margin-offset`，UI表现是突然塌陷
> 
> 能整个在线项目吗，方便排查一些。

已解决，是我的js和css文件版本不一致导致的😄
这个`margin-bottom: 0`在新版本已经移除了
![b1903b4d8d642ece91dc0347c3c6ce5](https://github.com/ant-design/ant-design/assets/11835233/9d2a6dfa-aa97-4d1e-8fbf-3a972c771a68)
