### ISSUE TITLE
Datepick and range picker is laggy and clunky

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#40501]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ln3gcc)

### Steps to reproduce

just click on it and compare it with v4. V4 is so much smoother and v5 is so laggy and clunky

### What is expected?

should be smooth

### What is actually happening?

laggy and clunky

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18 |
| System | N/A |
| Browser | chrome latest |

**Comment by MadCcc** [comment]
Same problem: https://github.com/ant-design/ant-design/issues/40104
