### ISSUE TITLE
DatePicker 选择器 预设范围的功能如何动态的获取当前的时分秒？

### ISSUE THREAD

**Issue by shizhihuaxu** [ant-design/ant-design#40504]
### Reproduction link

[https://ant.design/components/date-picker-cn#components-date-picker-demo-presetted-ranges](https://ant.design/components/date-picker-cn#components-date-picker-demo-presetted-ranges)

### Steps to reproduce

在官方demo中找到DatePicker预设范围这一模块，在带有时、分、秒的这一个demo中选择一个预设的范围例如 Last 7 Days，观察此时输入框内的时间，过几分钟后再次选择一个预设时间例如 Last 14 Days

### What is expected?

结束时间应该是点击时此刻的时间

### What is actually happening?

结束时间是页面第一次渲染时的时间

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | react |
| System | macos 12.4 |
| Browser | chrome 108.0.5359.124（正式版本） |

**Comment by solo-xwz** [comment]
怎么解决 同求
