### ISSUE TITLE
Static Modal: dark theme is not applied

### ISSUE THREAD

**Issue by la99er** [ant-design/ant-design#40509]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-fermi-p8v2l7?file=/src/App.js)

### Steps to reproduce

Click the button

### What is expected?

The modal should appear in dark mode.

### What is actually happening?

The modal appears in light mode.

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | Linux |
| Browser | Firefox |

---
This happens with all static modals.

**Comment by zombieJ** [comment]
> In most case, you do not need static method. **It can not consume context like dynamic theme**. Please use hooks version or App provided instance first.

ref https://ant.design/components/modal#components-modal-demo-static-info

**Comment by la99er** [comment]
Oh my bad! Thanks for the quick response!
