### ISSUE TITLE
Tour component not following target positions

### ISSUE THREAD

**Issue by hishamank** [ant-design/ant-design#40515]
### Reproduction link

[https://stackblitz.com/edit/react-zra4dh?file=demo.tsx](https://stackblitz.com/edit/react-zra4dh?file=demo.tsx)

### Steps to reproduce

just open the tour and see it's not changing place

### What is expected?

to follow the set target positions 

### What is actually happening?

the dialog is staying in place, or moving in the wrong direction

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | react |
| System | macos latest version |
| Browser | chrome, arc |

**Comment by Yuiai01** [comment]
Hello, the link you provided does not reproduce the problem.

**Comment by hishamank** [comment]
my mistake, copied the wrong reproduction link, updated the issue
here's the link [https://stackblitz.com/edit/react-zra4dh?file=demo.tsx](https://stackblitz.com/edit/react-zra4dh?file=demo.tsx)

**Comment by hishamank** [comment]
I provided a reproduction link, can we reopen this issue @MadCcc

**Comment by zombieJ** [comment]
Seems after refactor with `@rc-component/trigger`. It's fixed.
