### ISSUE TITLE
DatePicker日期选择框 激活选择面板时， 鼠标在日期上移动时，会更新value值，请问如何监听此时value的变动

### ISSUE THREAD

**Issue by H-Sven** [ant-design/ant-design#40514]
### What problem does this feature solve?

DatePicker日期选择器 激活展开面板时， 鼠标在日期上移动会更新value值，请问如何监听此时value的变动
（真正的value还没有被更新，只是hover在某个日期时，输入框里面的值变化了）， 我需要监听此时的变化

### What does the proposed API look like?

DatePicker日期选择器 激活展开面板时， 鼠标在日期上移动会更新value值，请问如何监听此时value的变动
（真正的value还没有被更新，只是hover在某个日期时，输入框里面的值变化了）， 我需要监听此时的变化

**Comment by yangwei-s** [comment]
disabledTime 在这个属性中可以监听到鼠标value的值
const disabledDateTime: RangePickerProps['disabledTime'] = (date, type) => {
          console.log(date)
          return {}
}

**Comment by chenlongshu** [comment]
能关闭这个功能吗
