### ISSUE TITLE
Modal.confirm 上增加modal，多次操作 modal会在confirm下层

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#40513]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shi-yong-hooks-huo-de-shang-xia-wen-antd-4-24-7-forked-636f4q)

### Steps to reproduce

先点击 confirm按钮，弹出confirm，再点击confirm内容中的打开modal 打开modal这个时候正常。
然后关闭modal ，关闭confirm
再点击 confirm按钮，弹出confirm，再点击confirm内容中的打开modal 打开modal这个时候异常。

### What is expected?

后打开的一直在最上层
<img width="762" alt="image" src="https://user-images.githubusercontent.com/8169783/216296432-a0ea603e-d576-496d-9147-e626499184a9.png">

### What is actually happening?

后打开的modal可能在先打开confirm的下层
<img width="776" alt="image" src="https://user-images.githubusercontent.com/8169783/216296212-82a293f1-f967-4da6-af47-cf6305abb64d.png">

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17.0.2 |
| System | masOS Monterey 12.1 |
| Browser | chrome 101.0.4951.64 |

**Comment by MadCcc** [comment]
Try `destoryOnClose` to make order always right.
https://codesandbox.io/s/shi-yong-hooks-huo-de-shang-xia-wen-antd-4-24-7-forked-d9mjri?file=/demo.tsx:1806-1820

**Comment by rawbin-** [comment]
@MadCcc thanks a lot, It works,  and also we can arrange z-index of each modal by `zIndex `
