### ISSUE TITLE
Focus on first error

### ISSUE THREAD

**Issue by nvmnghia** [ant-design/ant-design#40510]
### What problem does this feature solve?

When submitting forms, the first error should be focused.

I think this is a big missing feature. If you think that this should be avoided (moving focus around without user interaction), could you please provide a source?

### What does the proposed API look like?

No change to user API.

**Comment by xataxxx** [comment]
Ant Form has 'scrollToFirstError' property. You can enable it and even provide options for smooth scrolling.

**Comment by zombieJ** [comment]
You can handle this by `onFinishFailed`:

https://codesandbox.io/s/ji-ben-shi-yong-antd-5-1-7-forked-9nswuu?file=/demo.tsx

**Comment by dathymax** [comment]
const formRef = useRef(null);

const onFinishFailed = () => {
    const formInstance = formRef.current;
    if (formInstance) {
      const firstErrorInput = formInstance?.getFieldInstance(formInstance.getFieldsError()?.find(field => field?.errors?.length > 0)?.name);
      if (firstErrorInput) {
        firstErrorInput.focus();
      }
    }
  };

<Form
            ref={formRef}
            scrollToFirstError={{
                behavior: 'smooth',
                block: 'center',
                inline: 'center',
            }}
            onFinishFailed={onFinishFailed}
            {...rest}
        >
            {children}
</Form>

You can try my code
