### ISSUE TITLE
RTL support all pages and components?

### ISSUE THREAD

**Issue by mhf-ir** [ant-design/ant-design#4051]
Is ant support RTL languages?
Persian, Arabic and etc. ..

**Comment by benjycui** [comment]
Actually, we may need Persian, Arabic and etc locale file for [`LocaleProvider`](https://ant.design/components/locale-provider/) first.

**Comment by benjycui** [comment]
And, all the `antd` maintainers are Chinese now. So, it's impossible for us to implement this feature.

**Comment by afc163** [comment]
No offially support now, we suggest you give us PR directly.

**Comment by Tsury** [comment]
Can you maybe explain what would be the best way to add RTL support?

**Comment by benjycui** [comment]
How about a new props `LocaleProvider[rtl]` ？

**Comment by benjycui** [comment]
Anyway, RTL support is a part of locale.

**Comment by farskid** [comment]
@benjycui @afc163 Since Persian locales are added to the LocaleProvider right now, Can we continue with this issue? I'd be really happy to contribute!

**Comment by benjycui** [comment]
@farskid you can try to find a solution and post your idea here.

**Comment by farskid** [comment]
@benjycui will update with an idea soon 👍

**Comment by AienTech** [comment]
@farskid waiting for you solution :+1:

**Comment by farskid** [comment]
@benjycui sorry about the delay. the best thing on top of my head for this issue would be to go forward with current LESS styles and modify them to support directions.
for the components, we can create a provider same as `LocaleProvider` that passes the direction via context to the whole hierarchy.

**Comment by yesmeck** [comment]
@farskid Can you pick a component (like: Select) as start point?

**Comment by farskid** [comment]
@yesmeck Sure. I'll start with a component preferably `Select` component. It will include minimum global styles, component specific styles and `LocaleProvider` component for the starting step.

**Comment by papigers** [comment]
I'm willing to start working on RTL support. Is there some sample app which uses each component various options, in order to test my code?

I'm thinking something like the antd website's component pages.
Thanks.

btw, in a totally irrelevant subject, are there any plans to replace scss styling with something like styled components?

**Comment by yesmeck** [comment]
@papigers About styled-components, we've discussed it in #5570

**Comment by papigers** [comment]
I've eventually given up on this.
Customizing styles proved to be too difficult for components that use outside libraries, like those of `react-component`. I managed to style `rc-menu`, but it was an ugly solution, and couldn't apply the same on `rc-editor-mention` without making things even more uglier.

Still, if someone wants to continue my work, you can find it [here](https://github.com/papigers/ant-design/tree/feature/rtl-support)

**Comment by yesmeck** [comment]
@papigers We can refactor inline styles to class.

**Comment by papigers** [comment]
@yesmeck Yes, but we can't do that with library code. If we want to add RTL support to antd we also need to add RTL support for our dependencies.
With `Menu`, indeed, I only needed to change the component to give right padding and overwrite the `rc-menu` left padding. But with `rc-editor-menu`, I couldn't do that without changing the library code.
I can only assume that with more complex components, such as date/time picker, it would be even more difficult.

**Comment by yesmeck** [comment]
Yes, we can add RTL support for `rc-*` components, it's difficult, but we don’t need to do it all at once, once a component supports RTL, we can add a badge ![](https://img.shields.io/badge/RTL-supported-brightgreen.svg) to the doc.

**Comment by jzhangs** [comment]
Though we have some automatic tools, I would suggest manually refactor css/style of each component. Not sure if you read links below:

https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/
https://hacks.mozilla.org/2015/10/building-rtl-aware-web-apps-websites-part-2/
https://wiki.mozilla.org/Gaia/CSS_Guidelines#Direction_.28RTL.2FLTR_and_BiDi.29

If not that outdated, it's still best practice.

**Comment by KhaledSMQ** [comment]
My language from RTL and i am glade to support, i see the components very useful, And i have tried  http://rtlcss.com and it works fine

**Comment by yaronlevi** [comment]
So basically RTL is not fully supported out-of-the-box?

**Comment by HDaghash** [comment]
Such a great lib should have RTL support !!! :(

**Comment by HDaghash** [comment]
@benjycui what's the plane for this, it's very important to have

**Comment by yassinebridi** [comment]
is there any plans to do this in the near future?

**Comment by elkhawajah** [comment]
@huemix can I get your work done so far ? I have a reactjs developers who can update components to have the properties to support RTL instead of doing it out of the box.

Anyone interested to join the efforts to implement this please drop me a message, we can try to finish this in June as I have work depends on this theme.

**Comment by mehrdad-shokri** [comment]
@yesmeck hey, is there any progress on this issue? I can help with adding RTL support to Ant.
I think I can start the project by adding RTL support to a component on Ant.

**Comment by yesmeck** [comment]
> @yesmeck hey, is there any progress on this issue? I can help with adding RTL support to Ant.
> I think I can start the project by adding RTL support to a component on Ant.

@zombieJ

**Comment by zombieJ** [comment]
@mehrdad-shokri, 
Sure. Since we are preparing for 4.0, you can start on `4.0-prepare` branch.

**Comment by mehrdad-shokri** [comment]
@zombieJ How can I start to work on it? I mean what's your intuition on adding RTL support? do you think customizing ``less`` files is an appropriate way? some hints would really benefit me.

**Comment by zombieJ** [comment]
Since we don't use RTL, we can help less on this. Maybe you can add the config prop on `ConfigProvider` to start and process component one by one with RTL mode to check if it works (maybe both js & css should do something on it. I don't know). Some antd component is base on `rc-component`. If antd side update is not enough, it should also create the PR with `rc-component` too.

**Comment by huemix** [comment]
antd uses rc-components which they don't support RTL and that's the proplem.
I had to clone **rc-drawer**, and **Antd Tabs** components to add RTL support to those components.
and for the rest getPopupContainer did the trick, and I believe changing it to RTL is a quick process but it needs to clone the rc-* components such as dropdown.
I'll add pull request with the tabs and drawer components with RTL support.
@elkhawajah of course I am interested in this and I already did that, I can help on this.

**Comment by beblaawy** [comment]
Do you have any plan to support RTL anytime soon?

**Comment by yoyo837** [comment]
some one working on #19380

**Comment by hatemalimam** [comment]
@ahmedrhuma any chance you could share the cloned components, such as drawer and tabs ?
thanks.

**Comment by saeedrahimi** [comment]
RTL support has been added to all of Ant Design components with #19380
It will be shipping out with v4 release 😉

**Comment by saeedrahimi** [comment]
I am closing it, feel free reopen

**Comment by husseinpenart** [comment]
hello every body 
to my Iranian friends :
the best way to make RTL in you project by ant design is add this code on you jsx tag
style={{direction: 'rtl'}}
and done you have rtl on your project

**Comment by aderchox** [comment]
@saeedrahimi It seems that RTL for tabs is buggy, if you can have a look at this sandbox: https://codesandbox.io/s/stoic-minsky-hhxic7?file=/src/App.js
