### ISSUE TITLE
DatePicker 问题

### ISSUE THREAD

**Issue by Vsion** [ant-design/ant-design#4052]
#### 发生问题的环境是：

- antd 版本:2.5.0
- 操作系统及其版本: win10
- 浏览器及其版本:

#### 您做了什么？请提供尽可能详细的重现步骤。

![image](https://cloud.githubusercontent.com/assets/11804448/20701677/50eaecee-b64f-11e6-8341-3670c20ca463.png)
![image](https://cloud.githubusercontent.com/assets/11804448/20701692/603a978a-b64f-11e6-9cd8-6837ae0cfdae.png)
```
var placeholder = [this.props.startPlaceholder || "开始时间", this.props.endPlaceholder || "结束时间"];
     return(
       <RangePicker placeholder={placeholder} startPlaceholder={this.props.startPlaceholder || "开始时间"} endPlaceholder={this.props.endPlaceholder || "结束时间"} defaultValue={[defaultValue,defaultValue]} locale={locale} placeholder={this.props.placeholder} format={this.props.format} showTime={this.props.showTime} disabledDate={this.props.disabledDate} disabledTime={this.props.disabledTime} onChange={this.props.onChange} />
     );
```

#### 您期待的结果是:

传了placeholder 但是render 的时候是undefined

**Comment by yesmeck** [comment]
可以在标题里**简要**描述下问题吗？不要都是“xx 问题”，这样不方便碰到同样问题的人查找。

另外最好请提供一个能重现的例子 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Vsion** [comment]
好的, 下次注意.

**Comment by Vsion** [comment]
解决了, 是自己的代码问题...
