### ISSUE TITLE
antd 4.24.7 Dropdown.Button 在button是loading状态时, menu的button没有loading样式且依然能触发事件

### ISSUE THREAD

**Issue by Rayzhangzhang** [ant-design/ant-design#40528]
### Reproduction link

[https://4x.ant.design/components/dropdown-cn/#components-dropdown-demo-loading](https://4x.ant.design/components/dropdown-cn/#components-dropdown-demo-loading)

### Steps to reproduce

官方demo

### What is expected?

loading 后面的menu button 也有类似loading的样式，且不触发hover click事件

### What is actually happening?

前面的button在loading的情况下，后面的menu button 依然是默认状态

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17 |
| System | macOs |
| Browser | chrome109.0.5414.119 |

**Comment by afc163** [comment]
https://codesandbox.io/s/jia-zai-zhong-zhuang-tai-antd-4-24-7-forked-c0fj8w?file=/demo.tsx

**Comment by Rayzhangzhang** [comment]
> 

这个看起来只是换了一个icon，样式和事件依然能触发

**Comment by Rayzhangzhang** [comment]
> https://codesandbox.io/s/jia-zai-zhong-zhuang-tai-antd-4-24-7-forked-c0fj8w?file=/demo.tsx

这个看起来只是换了一个icon，样式和事件依然能触发
