### ISSUE TITLE
Menu in Header, Sider and Drawer has wrong colors in default & dark theme

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#40531]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/header-content-footer-antd-5-1-7-forked-u54eef)

### Steps to reproduce

When Menu is used inside Layout.Header, Layout.Sider or Drawer, its color does not match in default nor dark theme. I have included a reproduction demo with theme switcher.

### What is expected?

When Menu is used in Header/Sider background colors should match

### What is actually happening?

In default theme:
- Header & Sider bg: `#001529`
- Drawer bg: `#ffffff`
- Menu bg: `#ffffff`

In dark theme:
- Header & Sider bg: `#001529`
- Drawer bg: `#1f1f1f`
- Menu bg: `#141414`

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18 |
| System | all |
| Browser | all |

**Comment by MadCcc** [comment]
Use Menu `theme="dark"`.

**Comment by mauceri** [comment]
'theme="dark"' is an ad hoc solution, this should be automatic.

**Comment by Geczy** [comment]
any solution here? still really weird that we have light theme by default but its showing 001529

![image](https://user-images.githubusercontent.com/1036968/229541703-953ff5ce-baf5-41e0-acaf-3638ee66e331.png)

**Comment by Geczy** [comment]
i had to replace with a div for my layouts lol
![image](https://user-images.githubusercontent.com/1036968/231519941-95e8a0e7-e841-4d9c-8367-440e3ac10219.png)

**Comment by jglee96** [comment]
Sider background style was hard coded [here](https://github.com/ant-design/ant-design/blob/83e3b5218af3c91b47b00cdcd1dd5e5879578502/components/layout/style/index.ts#L224C13-L224C13)

It could be easily fixed by change to token color.
However I don't know what token color is proper, it makes me afraid to make a PR.

**Comment by iamchenxin** [comment]
> I fix with ConfigProvider theme.我用 ConfigProvider 主题修复。
> 
This works, but why is it designed like this.  Where can I find layout documentation, ```https://ant.design/components/layout-cn``` Except for examples, there are almost no functional instructions

**Comment by MadCcc** [comment]
Well, it's an issue about default background of Layout, which should be a design issue.
We will take this into consideration

**Comment by tang2087** [comment]
> > > Use Menu `theme="dark"`.
> > 
> > 
> > Not the solution, you should not have to set dark mode manually when using ConfigProvider. This is still a problem as seen in [@Geczy](https://github.com/Geczy) picture. Even if you did set dark mode manually it still doesnt work. `theme="dark"` only makes the menu items dark and light but doesn't change the background to the sidebar.
> > A temp solution is to set the sidebar background to colorBgContainer which should be updated when setting the ConfigProvider to `darkAlgorithm` or `defaultAlgorithm`. You will still see a lag in the color change though as seen in the gif
> >     const {
> >         token: { colorBgContainer },
> >     } = theme.useToken();
> >     
> >     return (
> >         <Sider style={{  background: colorBgContainer  }}>
> >     )
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![lag-background](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >       
> >         [
> >           
> >         
> >             ![lag-background](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >           ](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >         
> >        [ ![lag-background](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif) ](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >       
> >         [
> >           
> >         
> >             ![lag-background](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >           ](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/44310933/231066512-555e16da-4e8e-44f2-96cb-1267c25725e5.gif)
> 
> This is the best solution so far. I can't believe there is such a visible glitch and no one fixes it...
> 
> What does everyone use for Headers and Menus then if not the AntD Layout components?

`colorBgContainer` doesn't work for me.
