### ISSUE TITLE
Displayed value of DatePicker is croped when setting a higher global borderRadius value

### ISSUE THREAD

**Issue by JulesLecuir** [ant-design/ant-design#40547]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xpynrx?file=/index.js:445-459)

### Steps to reproduce

Just see the repro

### What is expected?

Letters are cropped because of border radius

### What is actually happening?

They should not (it works fine in other inputs, see the repro)

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 17.0.2 |
| System | Ubuntu 22 |
| Browser | Brave Browser (Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)) |

**Comment by JulesLecuir** [comment]
My workaround at the moment is:
```css
.ant-picker .ant-picker-input > input {
  border-radius: 0;
}
```

**Comment by Yuiai01** [comment]
> My workaround at the moment is:
> 
> ```css
> .ant-picker .ant-picker-input > input {
>   border-radius: 0;
> }
> ```

I think the input in the DatePicker doesn't need the borderRadius attribute because borderRadius is already applied to the outermost div of the DatePicker 🤔🤔

**Comment by Wxh16144** [comment]
> I think the input in the DatePicker doesn't need the borderRadius attribute because borderRadius is already applied to the outermost div of the DatePicker 🤔🤔

You misunderstood, @JulesLecuir is describing that the content inside the input box is incomplete due to the rounded corners property. I've submitted a Pull request to fix it.
