### ISSUE TITLE
Delay on open select options

### ISSUE THREAD

**Issue by tem8888** [ant-design/ant-design#40545]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/custom-dropdown-antd-5-1-7-forked-hkue0p?file=/demo.js)

### Steps to reproduce

1. Create Dropdown
2. Inside dropdownRender put div as container and Select component with defaultOpen=true
3. Use getPopupContainer for that div
4. Click on the button

### What is expected?

List of options opens at the same time with select

### What is actually happening?

List of options opens after some delay

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | ^18.0.0 or older |
| System | Win 10 |
| Browser | Firefox 110, Chrome 109 |

**Comment by zombieJ** [comment]
Select motion is later after Dropdown motion. We can do nothing on this.
