### ISSUE TITLE
Tab label使用contentEditable，无法输入空白

### ISSUE THREAD

**Issue by cwtuan** [ant-design/ant-design#40542]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-1-7-forked-bfkfzd?file=/demo.tsx)

### Steps to reproduce

1. 点击"editable text" => 可以输入空白键
2. 点击Tab上的"editable tab label" => 无法输入空白键

![image](https://user-images.githubusercontent.com/3455798/216769742-3a04d48a-f88c-4dcb-ad03-7af6ee3de762.png)

### What is expected?

Tab上的"editable tab label" => 应该要能输入空白键

### What is actually happening?

Tab上的"editable tab label" => 无法输入空白键

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | react 18 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
`stopPropagation`:

https://codesandbox.io/s/ji-ben-antd-5-1-7-forked-csh7vr?file=/demo.tsx
