### ISSUE TITLE
Modal.confirm does not use primary color

### ISSUE THREAD

**Issue by mleister97** [ant-design/ant-design#40546]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-pj6gxi)

### What is expected?

Hover over the close button, the color should be my primary color (green)

### What is actually happening?

the hover color is blue

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Latest Chrome |

**Comment by Yuiai01** [comment]
Hi, the static methods of Modal cannot access the ConfigProvider context. You can see this https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

**Comment by Wxh16144** [comment]
Wrap your application with the `<App />` components provided by Ant Design. It is important to note that you need to place the `<App />` component inside your `<ConfigProvider />` component.

<details>
<summary>Click to see examples</summary>

```jsx
import React from "react";
import { createRoot } from "react-dom/client";
import {
  Button,
  DatePicker,
  Space,
  version,
  // Modal,
  App as AntdApp
} from "antd";
import { ConfigProvider } from "antd";
import "antd/dist/reset.css";
import "./index.css";

const App = () => {
  const { modal } = AntdApp.useApp();

  React.useEffect(() => {
    modal.confirm({
      content: `Hi`,
      footer: (
        <div className="ant-modal-confirm-btns">
          <Button key="back">Cancel</Button>,<Button danger>OK</Button>
        </div>
      )
    });
  }, []);

  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <Space>
        <DatePicker />
        <Button type="primary">Primary Button</Button>
      </Space>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(
  <ConfigProvider
    theme={{
      token: {
        colorPrimary: "#3eb984",
        colorLink: "#3eb984",
        colorLinkHover: "#31475e",
        colorLinkActive: "#31475e",
        colorTextDisabled: "(0, 0, 0, 0.88)"
      },
      components: {
        Layout: {
          // header
          lineHeight: 48
        }
      }
    }}
  >
    <AntdApp>
      <App />
    </AntdApp>
  </ConfigProvider>
);
```
</details>

**Comment by KYLFYK** [comment]
Also check that you are exporting component directly from "antd", if you export from "antd/lib/..." then the data from ConfigProvider will not be used

**Comment by afc163** [comment]
Try `useModal` or `App.useApp` instead of Modal static methods: [ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx](https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx)
