### ISSUE TITLE
Image fallback don't show as expected in 5.x

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#40555]
https://ant.design/components/image-cn#components-image-demo-fallback

https://4x.ant.design/components/image-cn#components-image-demo-fallback

**Comment by afc163** [comment]
https://codesandbox.io/s/l7ev2l?file=/index.tsx

codesandbox 里是好的。

**Comment by Yuiai01** [comment]
@afc163 大佬，你直接访问 https://ant.design/components/image-cn 也是好的，感觉可能跟页面路径有关？

**Comment by afc163** [comment]
SSR 的问题。

**Comment by afc163** [comment]
https://github.com/vercel/next.js/issues/7047
