### ISSUE TITLE
官网文档，不能记录上一次的访问设置，比如AntD版本号

### ISSUE THREAD

**Issue by ghyghoo8** [ant-design/ant-design#40559]
### What problem does this feature solve?

RT。 现在默认都去最新版，不能记住上次访问的版本号，体验很差！！！每次都要手动切换！！！

### What does the proposed API look like?

种个cookie，view自动路由一下吧。记录用户上次浏览的版本号、语言、LTR等设置

**Comment by afc163** [comment]
具体问题是啥？

**Comment by yoyo837** [comment]
<img width="94" alt="image" src="https://user-images.githubusercontent.com/6134547/216879370-78b81035-3ee0-4d63-833e-8dcd75158179.png">

他应该是想看每个版本的文档

**Comment by yoyo837** [comment]
而不是某个mojar的最后一个版本

**Comment by RedJue** [comment]
现在都是默认最新的 ，旧文档需要去里面自己切换。

**Comment by afc163** [comment]
建议直接访问和收藏 https://4x.ant.design/index-cn 链接。

**Comment by yoyo837** [comment]
> 现在都是默认最新的 ，旧文档需要去里面自己切换。

不是这个意思,
他想要比如, 4.1.0, 4.1.2, 4.1.3, 4.1.4 等每个版本的

**Comment by yoyo837** [comment]
clone后切换到git tag然后本地跑起来看, 算一个方案.

**Comment by Wxh16144** [comment]
每次发布一个版本会发一个指定地址 

- #39303

之前提交过一个讨论是 生成一个 Docker Image

- #40479

**Comment by yoyo837** [comment]
> 每次发布一个版本会发一个指定地址
> 
> * [Deploy site when release version #39303](https://github.com/ant-design/ant-design/issues/39303)
> 
> 之前提交过一个讨论是 生成一个 Docker Image
> 
> * [添加 Ant Design Docs Docker Images #40479](https://github.com/ant-design/ant-design/discussions/40479)

那这个有在官网说明一下吗?好多人不知道

**Comment by afc163** [comment]
>  不是这个意思，他想要比如, 4.1.0, 4.1.2, 4.1.3, 4.1.4 等每个版本的

恐怕不是，用户是希望切换一次后，下次进来一直是这个版本的。

**Comment by yoyo837** [comment]
> > 不是这个意思，他想要比如, 4.1.0, 4.1.2, 4.1.3, 4.1.4 等每个版本的
> 
> 恐怕不是，用户是希望切换一次后，下次进来一直是这个版本的。

那我理解错了.

**Comment by yoyo837** [comment]
> > 每次发布一个版本会发一个指定地址
> > 
> > * [Deploy site when release version #39303](https://github.com/ant-design/ant-design/issues/39303)
> > 
> > 之前提交过一个讨论是 生成一个 Docker Image
> > 
> > * [添加 Ant Design Docs Docker Images #40479](https://github.com/ant-design/ant-design/discussions/40479)
> 
> 那这个有在官网说明一下吗?好多人不知道

@Wxh16144 建议这个补一下文档.

**Comment by ghyghoo8** [comment]
> 具体问题是啥？

google搜索antd，进入第一个搜索结果，链接是：https://ant.design/components/overview-cn 。 每次进来都是5.x，就得手动切换到4.x 。 我的意思是，主域名站点下，是不是可以用cookie记录下用户选择，方便快速查看文档。
