### ISSUE TITLE
Input组件点击非常靠近边框的位置时，光标会跳到内容的最前面

### ISSUE THREAD

**Issue by zewxerox** [ant-design/ant-design#40560]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn](https://ant-design.antgroup.com/components/input-cn)

### Steps to reproduce

Input组件点击非常靠近边框的位置时

### What is expected?

光标不要跳到内容的最前面

### What is actually happening?

光标会跳到内容的最前面

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

---
可以先点击input组件，将光标置于input内容的中间，然后点击非常靠近边框的位置就能复现，input组件内文字内容距离组件边框越远越容易复现

**Comment by RedJue** [comment]
应该是点到`padding`上面了 脱离了`input`的热区范围，导致失焦，属于正常的期望，不算bug。

**Comment by Yuiai01** [comment]
这个将光标跳到内容最前面应该是 input 元素的原生事件，靠近边框的部分应该是 input 元素的内边距，将内边距设置大一点，就很容易复现楼主描述的问题。
<img width="991" alt="image" src="https://user-images.githubusercontent.com/112228030/217146089-4f1503cd-eecb-4f91-a301-166139a3369d.png">

**Comment by MadCcc** [comment]
给个录屏看看？

**Comment by MadCcc** [comment]
看了下是原生 input 的行为，antd 这里就不做处理了。

**Comment by afc163** [comment]
@MadCcc 给个codepen
