### ISSUE TITLE
Table组件暂无数据提示在IE11下没有宽度

### ISSUE THREAD

**Issue by CaptainJon** [ant-design/ant-design#40564]
### Reproduction link

[http://test.com](http://test.com)

### Steps to reproduce

使用Antd的Table组件渲染一个空数据，正常会展示一个暂无数据的占位内容。在IE11下，这个暂无数据的宽度只有1px。我看到dom上的宽度是通过行内样式，也就是可能通过计算动态赋值，在IE11下，其显示的宽度为1px，且`position: sticky`属性失效。

### What is expected?

暂无数据元素宽度保持正常，而不是1px

### What is actually happening?

暂无数据元素的宽度只有1px

| Environment | Info |
| --- | --- |
| antd | 4.20.7 |
| React | 17.0.2 |
| System | win10 |
| Browser | IE 11 |

![image](https://user-images.githubusercontent.com/51065061/216896679-9bdae323-679a-4b4c-a3c6-dd9d6a3aa623.png)

**Comment by CaptainJon** [comment]
由于第三方代码平台不支持ie浏览器，因此暂时无法提供复现链接，抱歉。

**Comment by MadCcc** [comment]
Could your provide a github repo as reproduction?
