### ISSUE TITLE
Can I change a color of text button when I set a band color to yellow.

### ISSUE THREAD

**Issue by kritsananac** [ant-design/ant-design#40569]
### What problem does this feature solve?

Can I change a color of text button when I set a band color to yellow.
It hard to see text in button (Text Button is white and Background Button is Yellow)
<img width="1592" alt="Screen Shot 2566-02-06 at 15 52 28" src="https://user-images.githubusercontent.com/84554889/216928296-39258382-6dc0-4e6a-ab31-8135ce7fc894.png">

### What does the proposed API look like?

Text Button should be contrast with Band color is yellow
<img width="547" alt="Screen Shot 2566-02-06 at 15 59 01" src="https://user-images.githubusercontent.com/84554889/216928690-9127ba5d-98e6-4963-bc59-e29fb090a20b.png">

**Comment by zombieJ** [comment]
Do you mean `colorTextLightSolid`?

<img width="813" alt="截屏2023-02-06 17 07 02" src="https://user-images.githubusercontent.com/5378891/216930427-45d2bf39-b2b0-4a47-9314-2741922e7f98.png">
