### ISSUE TITLE
官网中transfer组件第一个示例初始化时不显示列表数据，勾选全选之后才显示出来。

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#4056]
我用的360浏览器。
![image](https://cloud.githubusercontent.com/assets/18158633/20707937/9ea4bfe6-b668-11e6-8256-b2e3952d68ff.png)

**Comment by benjycui** [comment]
加了 LazyLoad 后导致的问题。

**Comment by benjycui** [comment]
官网这行代码 https://github.com/ant-design/ant-design/blob/master/site/theme/static/template.html#L27

影响了 LazyLoad 的判断 https://github.com/loktar00/react-lazy-load/blob/master/src/utils/inViewport.js#L4

See: https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/offsetParent

所以不是组件 bug。

**Comment by benjycui** [comment]
LazyLoad 组件没有考虑到祖先元素一开始是隐藏，然后再显示的情况。

**Comment by benjycui** [comment]
这里 https://github.com/ant-design/ant-design/issues/3934 搞定后就没问题了。
