### ISSUE TITLE
Make all api that accept JSON instead of JSX accept null

### ISSUE THREAD

**Issue by AhmadMayo** [ant-design/ant-design#40568]
### What problem does this feature solve?

If use JSX for the table clumns, we can easily do this
```jsx
{condition && <Column />}
```
or this
```jsx
{condition ? <Column /> : null}
```
And react will not render anything when these statements evaluate to null or false. Same goes for Select Options, menu Items, etc.
Changing these to the JSON equivalent, we have to do this
```jsx
const columns = [];
if (condition) {
  columns.push({/* my column */});
}
// after a lot of other lines
<Table columns={columns} />
```
I prefer to inline the columns/options/etc. for colocation to make it easier to understand what happens from looking at a specific part of the code. It would be very helpful if we can do this

### What does the proposed API look like?

```jsx
<Table
  columns={[
    condition ? {/* column */} : null,
  }]
/>
```
or
```jsx
<Table
  columns={[
    condition && {/* column */},
  }]
/>
```

**Comment by RedJue** [comment]
Let me try👀

**Comment by AhmadMayo** [comment]
hey @zombieJ , thanks a lot. Is it possible to implement it in other components that accept JSON props and render them? here's an exhaustive list of all the components that do so:
- Menu
- Steps
- Checkbox.Group
- Radio.Group
- Select
- TreeSelect
- Segmented
- Tabs
- Timeline
- Tour
- Tree

Thanks again

**Comment by RedJue** [comment]
I will continue to optimize these components 😊

**Comment by RedJue** [comment]
> hey @zombieJ , thanks a lot. Is it possible to implement it in other components that accept JSON props and render them? here's an exhaustive list of all the components that do so:
> 
> * Menu
> * Steps
> * Checkbox.Group
> * Radio.Group
> * Select
> * TreeSelect
> * Segmented
> * Tabs
> * Timeline
> * Tour
> * Tree
> 
> Thanks again

Which of the components here are not supported by null? I checked that they all seem to work.

**Comment by AhmadMayo** [comment]
@RedJue  Only `Menu` worked. Maybe it's just the TS types that are not correct?

![image](https://user-images.githubusercontent.com/15085304/220182755-e73370f8-cddd-4346-beeb-0e04beae4db3.png)
