### ISSUE TITLE
App 组件支持 message 和 notification 全局配置，并支持 style 属性 

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#40566]
### What problem does this feature solve?

项目中有可能要求一些 message 和 notification 的默认配置，现阶段 App 是不支持设置的，另外支持 style 可以更方便的由 token 派生动态样式！

### What does the proposed API look like?

```ts
<App 
  style={{...}}
  message={{...}}
  notification={{...}}>
  <Page />
</App>
```

PR: https://github.com/ant-design/ant-design/pull/39750

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/40458 更完整一些。`style` 暂时不考虑，这个组件本身不可见。
Duplicate of https://github.com/ant-design/ant-design/issues/40456

**Comment by nuintun** [comment]
@MadCcc 如果定于为组件不可见，建议去除 className 属性和 div 层
