### ISSUE TITLE
Modal confirm is in white color in dark theme

### ISSUE THREAD

**Issue by Khadhiri786** [ant-design/ant-design#40576]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rr55gu?file=/index.js)

### Steps to reproduce

https://github.com/ant-design/ant-design/issues/38671#issuecomment-1418981697

### What is expected?

Modal, Notification and Message popups should display with black background in dark mode.

### What is actually happening?

These popup's background is displaying with white background in dark theme. If we use hooks from `App` we are getting error message as shown below.

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

Screenshots:

![image](https://user-images.githubusercontent.com/60467237/216988941-279454aa-42e0-4f31-91a7-ba0b66bb12f0.png)

**Comment by Khadhiri786** [comment]
None of the above links are helpful to the mentioned issue.

**Comment by Khadhiri786** [comment]
@afc163

**Comment by Yuiai01** [comment]
@Khadhiri786 Hello, The App component should be used by wrapping your component like this.
~~~tsx
const MyApp: React.FC = () => (
  <App>
    <ButtonComponent/>
  </App>
);
~~~

**Comment by Khadhiri786** [comment]
@Yuiai01  I have tried, it's not working. Refer below codesandbox link
https://codesandbox.io/s/antd-reproduction-template-forked-rr55gu?file=/index.js

**Comment by Yuiai01** [comment]
@Khadhiri786 You can change the theme like I did. https://codesandbox.io/s/dark-theme-tmg8u9

**Comment by Yuiai01** [comment]
@Khadhiri786 This link might help you, too. https://ant.design/components/app#sequence-with-configprovider 😁

**Comment by tnsivanagarajan** [comment]
@Yuiai01 Thank you for quick response. The expected outcome is the message should be in dark theme. Right now it seems having light them.

**Comment by Wxh16144** [comment]
I have the impression of having commented on a similar issue before, [here](https://github.com/ant-design/ant-design/issues/40546#issuecomment-1416914060).

In the reproduction address you provided, I found two problems.

1. You need to place the `<App />` component provided by `antd` inside the `<ConfigProvider />` component.

```jsx
import { ConfigProvider, App } from "antd";

const root = createRoot(document.getElementById("root"));
root.render(
  <ConfigProvider>
    <App>{/** Use App.useApp here */}</App>
  </ConfigProvider>
);
```

2. you need to use the useApp hook in the `<App />` wrapped component.

```jsx
const My = () => {
  const { message } = App.useApp();

  return (
    <Button
      onClick={() => {
        message.success("Clicked");
      }}
    >
      Click Here
    </Button>
  );
};
```

<details>
<summary>Toggle full code</summary>

```jsx
import React from "react";
import { createRoot } from "react-dom/client";
import { ConfigProvider, theme, App, Button } from "antd";
import "antd/dist/reset.css";
import "./index.css";

const ButtonComponent = () => {
  const { message } = App.useApp();

  return (
    <Button
      onClick={() => {
        message.success("Clicked");
      }}
    >
      Click Here
    </Button>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(
  <div className="App">
    <ConfigProvider
      theme={{
        algorithm: theme.darkAlgorithm,
      }}
    >
      <App>
        <ButtonComponent />
      </App>
    </ConfigProvider>
  </div>
);
```

</details>

Hope my answer can help you (I rely on translation software to communicate with you in

**Comment by Khadhiri786** [comment]
@Wxh16144 do you have any idea about class component in react.
Please refer below codesandbox link
https://codesandbox.io/s/antd-reproduction-template-forked-rr55gu?file=/index.js

**Comment by Wxh16144** [comment]
> @Wxh16144 do you have any idea about class component in react. Please refer below codesandbox link https://codesandbox.io/s/antd-reproduction-template-forked-rr55gu?file=/index.js

I'm not familiar with class components, so I guess what you might want to know is how the HOC is handled. Here is a link
https://codesandbox.io/s/antd-reproduction-template-forked-e3h1nz?file=/index.js

**Comment by lriho** [comment]
We faced a similar issue with notifications. Cannot use the hooks everywhere as we use them in redux and react-query handlers as well. Figured we can have a component always rendered in App that will listen to messages sent through DOM events. Hope this helps someone. Should be easily tweaked to support modals or messages.

NotificationHolder.tsx
```tsx
import { App } from 'antd';
import React from 'react';

import { NotificationDetail } from 'utils';

export function NotificationHolder(): null {
    const { notification } = App.useApp();

    React.useEffect(() => {
        const handleMessage = ((event: CustomEvent<NotificationDetail>) => {
            const { args, type } = event.detail;
            notification[type](args);
        }) as EventListener;

        document.addEventListener('notificationEvent', handleMessage);

        return () => {
            document.removeEventListener('notificationEvent', handleMessage);
        };
    }, [notification]);

    return null;
}
```

utils/notification.ts
```ts
import { ArgsProps, NotificationInstance } from 'antd/es/notification/interface';

export interface NotificationDetail {
    type: 'success' | 'error' | 'warning' | 'info';
    args: ArgsProps;
}

function getEvent(type: NotificationDetail['type'], args: ArgsProps) {
    return new CustomEvent<NotificationDetail>('notificationEvent', {
        detail: {
            type,
            args,
        },
    });
}

export const notification: Omit<NotificationInstance, 'open' | 'destroy'> = {
    info: (args: ArgsProps) => {
        document.dispatchEvent(getEvent('info', args));
    },
    error: (args: ArgsProps) => {
        document.dispatchEvent(getEvent('error', args));
    },
    success: (args: ArgsProps) => {
        document.dispatchEvent(getEvent('success', args));
    },
    warning: (args: ArgsProps) => {
        document.dispatchEvent(getEvent('warning', args));
    },
};
```

Your App.tsx
```tsx
import { App } from 'antd';
import { NotificationHolder } from 'components';

<App>
  <NotificationHolder />
</App>
```

Anywhere else
```ts
import { notification } from 'utils';

notification.success({ message: 'Operation successful.' })
```

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546
