### ISSUE TITLE
How to change button primary type text color at theme level?

### ISSUE THREAD

**Issue by gariggio** [ant-design/ant-design#40572]
### What problem does this feature solve?

I don't know if I missed something simple...
How to change primary type button text color at theme level with antd 5.1.7?

https://codesandbox.io/s/button-type-primary-text-color-q5gpx8

It should be a very common task... or not?

### What does the proposed API look like?

```tsx
<ConfigProvider 
   theme={{
        token: {
          colorPrimary: "#FBED42",
        },
        components: {
          Button: {
            primary: { // <---- some key or some prop
              colorText: "#ff9900",
            },
          },
        },
      }}>
 ...
</ConfigProvider>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/3fdedacf3823a7e1ae84519ad841dbf5102c35d8/components/button/style/index.ts#L242

https://codesandbox.io/s/button-type-primary-text-color-forked-25p16z?file=/index.js

**Comment by gariggio** [comment]
Thanks a lot. TOP!
