### ISSUE TITLE
Multiple column sorting - last clicked column has the highest priority

### ISSUE THREAD

**Issue by AdamczykMaciej** [ant-design/ant-design#40571]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sorting-ant-design-tables-in-react-the-easy-way-forked-642fql?file=/src/App.js)

### Steps to reproduce

Click on column A and sort it ascendingly. Click on column B and sort ascendingly.
Priority of sorting: A, B.
Click again on column A. Sort the column descendingly. Intuitively the sorting order should be: A, B.
(Why? Because I started sorting firstly by column A. Then by B. And now I would like to tweak the first column - column A. To sort descendingly. Column B should have still the lower priority. In order to reset the priority of column A and make column B the one with higher priority I should first reset column A sorting. When Column A is reset then it should first be sorting by column B.)

But the priority of sorting is: B, A

### What is expected?

The sorting order should be: A, B instead of B, A in the described scenario.

### What is actually happening?

It seems that when sorting antd takes the order of clicks. The last clicked column will have the lowest priority.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome, Version 109.0.5414.120 |

**Comment by zombieJ** [comment]
You can use `multiple` to dynamic adjust priority:

```tsx
sorter: {
      compare: (a, b) => a.xxx - b.xxx,
      multiple: [DynamicWithStateHere],
    },
```

**Comment by AdamczykMaciej** [comment]
yes, multiple is the  property which sets the priority of columns. The thing is that we are insisted to you use onChange function in the Table component. It returns **sorter** which does not have the order we would like to have. We have to write an overlaying custom code to correct the sorting order of columns (or you could call it the priority of columns, which determines which column should be sorted firstly, secondly and so on. So it is possible to implement it by ourselves but it is cumbersome and a little hacky. It would be nice to have this correct behavior by default in antd when sorting by multiple column and having the same priority for all columns, but the factor that matters is the order of clicks (taking into consideration that the first clicked column (sorted) should have the highest priority, then 2nd, 3rd... When clicking back on the 1st column the sorting order should not be changed because the column is still active (unless clicking on the column means switching off sorting for that column - null). That's what does not happen today, in the discussed scenario the priority would be 2,3,1 instead of still 1,2,3 where numbers denote corresponding columns.

**Comment by jeannnemelanie** [comment]
+1 the order of `sorter` params when using `onChange` doesn't respect the columns `sorter` settings.
