### ISSUE TITLE
CSS delay when SSR

### ISSUE THREAD

**Issue by silviaphungky** [ant-design/ant-design#40587]
### Reproduction link

[https://63e1ce6cd0f5a308abd8a5d8--gentle-florentine-6b22dd.netlify.app/](https://63e1ce6cd0f5a308abd8a5d8--gentle-florentine-6b22dd.netlify.app/)
github: https://github.com/silviaphungky/antd-ssr

### Steps to reproduce

- throttling the connection to fast 3G to see the issue clearer
- refresh the page you will see the style is not applied at the first second

### What is expected?

the style should be applied in the first second

### What is actually happening?

the style is delay when ssr

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | next js 13.1.6 |
| System | mac os |
| Browser | chrome |

**Comment by silviaphungky** [comment]
> ### You may look for issues:
> 1. 50% [SSR causes FOUC #40087](https://github.com/ant-design/ant-design/issues/40087)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)

I already try this solution https://github.com/ant-design/ant-design/issues/16037#issuecomment-509024637 but still not working

**Comment by MadCcc** [comment]
Try this: https://github.com/ant-design/create-next-app-antd/blob/main/pages/_document.tsx
You need to extract styles in `_document.tsx`
