### ISSUE TITLE
Theme tokens don't work for generatePicker

### ISSUE THREAD

**Issue by kembly** [ant-design/ant-design#40582]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

1. Set `colorPrimary` in antd config
2. Observe DatePicker generated via generatePicker is ignoring the custom theme.

### What is expected?

The custom color theme set in the antd config will be adopted by the date picker created from:  `generatePicker`.

### What is actually happening?

The custom color theme is ignored for the `DatePicker` which is created via `generatePicker`

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | React 18 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Change `lib` to `es` and everything looks good. It's problem width different context instance.
https://codesandbox.io/s/antd-reproduction-template-forked-pkpgbi

**Comment by sorokinvj** [comment]
@MadCcc thanks for the example! doesn't work in my case with days though: 
```
import generatePicker from 'antd/es/date-picker/generatePicker'
import { Dayjs } from 'dayjs'
import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs'

export const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig)
```
gives me:

```
Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/vladislavsorokin/Webprojects/paytrix/merchant-portal-web-app/node_modules/antd/es/date-picker/generatePicker/index.js (1)
Object.compileFunction
node:vm (360:18)
wrapSafe
node:internal/modules/cjs/loader (1055:15)
Module._compile
node:internal/modules/cjs/loader (1090:27)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1180:10)
Module.load
node:internal/modules/cjs/loader (1004:32)
Function.Module._load
node:internal/modules/cjs/loader (839:12)
Module.require
node:internal/modules/cjs/loader (1028:19)
require
node:internal/modules/cjs/helpers (102:18)
Object.antd/es/date-picker/generatePicker
file:///Users/vladislavsorokin/Webprojects/paytrix/merchant-portal-web-app/.next/server/pages/_app.js (2898:18)
__webpack_require__
file:///Users/vladislavsorokin/Webprojects/paytrix/merchant-portal-web-app/.next/server/webpack-runtime.js (33:42)
```
I am using NextJs 12.3.4 and antd 5.2.1

**Comment by zahirekrem09** [comment]
> @MadCcc thanks for the example! doesn't work in my case with dayjs though:
> 
> ```
> import generatePicker from 'antd/es/date-picker/generatePicker'
> import { Dayjs } from 'dayjs'
> import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs' // same error if I use es here
> 
> export const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig)
> ```
> 
> gives me:
> 
> ```
> Server Error
> SyntaxError: Cannot use import statement outside a module
> 
> This error happened while generating the page. Any console logs will be displayed in the terminal window.
> Call Stack
> <unknown>
> file:///Users/.../node_modules/antd/es/date-picker/generatePicker/index.js (1)
> Object.compileFunction
> node:vm (360:18)
> wrapSafe
> node:internal/modules/cjs/loader (1055:15)
> Module._compile
> node:internal/modules/cjs/loader (1090:27)
> Object.Module._extensions..js
> node:internal/modules/cjs/loader (1180:10)
> Module.load
> node:internal/modules/cjs/loader (1004:32)
> Function.Module._load
> node:internal/modules/cjs/loader (839:12)
> Module.require
> node:internal/modules/cjs/loader (1028:19)
> require
> node:internal/modules/cjs/helpers (102:18)
> Object.antd/es/date-picker/generatePicker
> file:///Users/.../.next/server/pages/_app.js (2898:18)
> __webpack_require__
> file:///Users/.../.next/server/webpack-runtime.js (33:42)
> ```
> 
> I am using NextJs 12.3.4 and antd 5.2.1

did you solve this error, i am getting the same error but i couldn't solve it.

**Comment by Lolinpiko** [comment]
@sorokinvj / @zahirekrem09 Did you found a solution, i'm getting the same error

**Comment by zahirekrem09** [comment]
Unfortunately, I couldn't find it, but as far as I've told, it seems like an improvement has been made, I don't know when it will be published.

**Comment by dquang-tran** [comment]
Yep, problem still there

**Comment by zahirekrem09** [comment]
> Yep, problem still there

`import React from 'react'

import { DatePicker } from 'antd'

import momentGenerateConfig from 'rc-picker/lib/generate/moment'

const HDatePicker = DatePicker.generatePicker(momentGenerateConfig)

export default HDatePicker
` `"antd": "5.5.0",`

**Comment by dquang-tran** [comment]
My problem was that the theme algorithm wasn't being picked up
```
<ConfigProvider
  theme={{
    algorithm: darkAlgorithm,
    token: {
      colorBgContainer: 'transparent',
      colorPrimary: colors.zinc[300],
    },
  }}
>
```
and that was due to my imports referring to lib, which I implemented due to this problem [so](https://stackoverflow.com/questions/64428363/syntaxerror-cannot-use-import-statement-outside-a-module-react-js-antd). I changed it back to es, fixed the original issue by adding transpilePackages to my next.config.js, and now everything works
