### ISSUE TITLE
Table官网示例设置了rowSelection  再点击复选框的时候样式问题

### ISSUE THREAD

**Issue by mrKylinZhou** [ant-design/ant-design#4059]
bug复现问题，ant-design官网 Table组件

**Comment by yesmeck** [comment]
所以问题是？

**Comment by afc163** [comment]
....

**Comment by benjycui** [comment]
个人测试感觉没问题，请提供重现 demo。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
没反馈就关了，有进一步信息可自行 reopen。
