### ISSUE TITLE
级联选择组件，希望能够自定义每个选项的渲染，开一个 optionItemRender的属性

### ISSUE THREAD

**Issue by anran108** [ant-design/ant-design#40590]
### What problem does this feature solve?

后端给的数据格式类似于：

```
interface Response {
  success: boolean;
  code: string;
  data: Array<{
    id: string;
    title: string;
    code: string;
  }>
}
```

业务中显示选项时，需要把 code   title 拼接显示，类似于  `code   '-'   title` ，目前只能递归拼接，比较麻烦。

### What does the proposed API look like?

期望开一个 optionItemRender 的属性，入参是当前项数据，返回ReactNode，能够自定义每项内容的render，就不需要递归处理数据了。

**Comment by MadCcc** [comment]
`options={data.map((item) => ({ label: `${item.code}-${item.title}` }))}`
