### ISSUE TITLE
希望不同prefixCls的ConfigProvider的tokens不互相继承

### ISSUE THREAD

**Issue by viking7982** [ant-design/ant-design#40599]
### What problem does this feature solve?

背景：
有一组父子组件，都通过ConfigProvider进行了antd5样式定制。由不同团队维护。
子组件和父组件使用了不同的prefixCls，希望达到样式区分的效果。
但是效果是父组件的token会被子应用继承，导致子组件的样式出现问题。

复现场景：
https://codesandbox.io/s/zhu-ti-antd-5-1-7-forked-gg52xy?file=/demo.tsx

希望通过prefixCls对这些token进行隔离，或者提供一个接口中断这个继承

### What does the proposed API look like?

解决思路：
1. token等配置通过prefixCls进行隔离。
可以考虑修改ConfigProvider的config配置。原本config是配置，修改成一个对象。对象的key是前缀，对象的value是对应前缀的config

2. 新增一个参数 isolated之类的，如果为true，就不进行config合并

如果认为这个需求合理，我可以尝试提pr

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/docs/react/customize-theme-cn#theme
Use `inherit: false`.
