### ISSUE TITLE
[Vite Module Federation]：Cannot read properties of null (reading 'useContext') in button.xxx.js

### ISSUE THREAD

**Issue by ytftianwen** [ant-design/ant-design#40600]
### Reproduction link

[https://github.com/originjs/vite-plugin-federation/tree/main/packages/examples/react-vite](https://github.com/originjs/vite-plugin-federation/tree/main/packages/examples/react-vite)

### Steps to reproduce

1. git clone https://github.com/originjs/vite-plugin-federation.git
2. cd ./packages/examples/react-vite
3. pnpm install
4. pnpm install antd --filter shared
5. Add `<Button>Shared</Button>` in 'shared/src/components/Button.jsx'
5. pnpm build
6. pnpm serve

### What is expected?

render in browser

### What is actually happening?

react_devtools_backend.js:4012 TypeError: Cannot read properties of null (reading 'useContext') 
at LocaleReceiver (button-ddaefe1e.js:6863:34)

<img width="800" alt="image" src="https://user-images.githubusercontent.com/13484089/217207577-09825e46-4337-4aec-9cc8-bc120c0d905b.png">

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | mac os |
| Browser | 109.0.5414.87 |

**Comment by Wxh16144** [comment]
I'm guessing the error is probably not related to antd. https://github.com/originjs/vite-plugin-federation/issues/173

**Comment by Ankit-Garg21** [comment]
I'm facing the same issue although not with module federation but with a monorepo build.
@ytftianwen Did you find a solution for this?

**Comment by haghsheno** [comment]
I have same issue with module federation in NextJS using injectScript.
It's ok in dev mode but in production it cause this error.

**Comment by favarete** [comment]
Same here with a monorepo, works in dev but doesn't build for production. Does anyone found a workaround for this?

**Comment by canyuegongzi** [comment]
这问题解决了吗，纯粹使用  cdn  也遇到了这问题

**Comment by soadergi** [comment]
I have spent a lot of time fighting this error. What I came up with is quite simple: you should import like {Select} from 'antd', not import Select from 'antd/lib/select'
