### ISSUE TITLE
Need to know where to change createRoot in antd umi dva project

### ISSUE THREAD

**Issue by Khadhiri786** [ant-design/ant-design#40609]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

I'm migrating my antd umi dva  react project from version 16.4.0 to 18.2.0. After updating I'm getting error.

### What is expected?

Where to use CreateRoot in BasicLayout.tsx. ReactDOM.render is not used in project

### What is actually happening?

Getting error in console.
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
It is not a antd issue.
