### ISSUE TITLE
Tooltip doesn't encapsulate all wrapped elements

### ISSUE THREAD

**Issue by dustinstender** [ant-design/ant-design#40601]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapsed-inline-menu-antd-5-1-6-forked-gzysqm?file=/demo.tsx)

### Steps to reproduce

- Wrap span elements with text inside with a span element wrapped with a Tooltip
- The placement of the Tooltip should be "right"
- Add some styling to the second span inside the parent span (float: "right")

### What is expected?

I would expect that if I hover over the span element, between the two strings, or over the first string that the Tooltip would appear to the right of the span element.

### What is actually happening?

The Tooltip appears to the right of the first child of the Tooltip, the string that isn't wrapped with a span element. Even when hovering over the span element, the Tooltip appears to the right of the first child of the Tooltip. Nothing happens when hovering between the two.

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.0.0 |
| System | Windows |
| Browser | Chrome |

---
I made another issue, but it was closed before I could explain that the solution given does not work - https://github.com/ant-design/ant-design/issues/40392

**Comment by zombieJ** [comment]
Tooltip work as expect since wrapped span is real what `hey` width is. When use `float`, element will not take space for parent. Use `flex` layout if need full size on the wrapped span element:

https://codesandbox.io/s/collapsed-inline-menu-antd-5-1-6-forked-v0iku7?file=/demo.tsx

**Comment by dustinstender** [comment]
Unfortunately when using the flex layout in project the text doesn't show at all... I can't replicate the issue though so I'll look more into it on my end. Thanks.
