### ISSUE TITLE
showSearch选中后不能把值input框中无值

### ISSUE THREAD

**Issue by luojian001** [ant-design/ant-design#4060]
#### 发生问题的环境是：

 "antd": "2.5.0",
    "bluebird": "3.4.6",
    "core-js": "2.4.1",
    "lodash": "4.17.2",
    "mobx": "2.6.3",
    "mobx-react": "4.0.3",
    "mobx-react-devtools": "4.2.10",
    "moment": "2.17.0",
- 操作系统及其版本:MAC系统
- 浏览器及其版本:chrome 54

#### 实际上的结果是:ant升级到最新版本后showSearch和numberInput框输入数字后点击页面其它的地方数字不显示，在点击输入框可以看到，点击其它的地方输入框看不到输入的内容

![Uploading image.png…]()

**Comment by yesmeck** [comment]
能把问题描述清楚吗？如果能提供一个可重现的在线演示就更好的！

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
无法理解。

**Comment by luojian001** [comment]
ant升级到最新版本后showSearch和numberInput框输入数字后点击页面其它的地方数字不显示，在点击输入框可以看到，点击其它的地方输入框看不到输入的内容

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

demo 和重现步骤，谢谢。

**Comment by afc163** [comment]
请按照 issue 模板描述问题，否则非常影响交流的准确率和效率。
