### ISSUE TITLE
「DataPicker」时间选择器在年份和季度选择的时候光标不准确

### ISSUE THREAD

**Issue by ONLY-yours** [ant-design/ant-design#40602]
### Reproduction link

[http://ant-design.antgroup.com/~demos/components-date-picker-demo-range-picker](http://ant-design.antgroup.com/~demos/components-date-picker-demo-range-picker)

![image](https://user-images.githubusercontent.com/52664827/217210976-44846000-39ce-4f21-9b22-fd1ed91d8759.png)

### Steps to reproduce

官网可以复现

### What is expected?

光标正确位于合适的位置

### What is actually happening?

光标展示问题有偏移

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18 |
| System | MacOs |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
是这两行代码的问题，我看看能不能修复一下。
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/112228030/217223132-fa00dfd0-9eb3-4333-b6d1-1f0f7fd7ea2f.png">
