### ISSUE TITLE
Sider.defaultCollapsed behaves weiredly when Sider.breakpoint is set

### ISSUE THREAD

**Issue by IronSean** [ant-design/ant-design#40616]
### Reproduction link

[https://stackblitz.com/edit/react-jypqye?file=demo.tsx](https://stackblitz.com/edit/react-jypqye?file=demo.tsx)

### Steps to reproduce

Set breakpoint to a value
Set defaultCollpased to true
handle onCollapse to update Collapsed state
render sider on screen size where breakpoint is triggered

### What is expected?

If defaultCollapsed is true I would expect the sider to default to collapsed on all screen sizes. But with a breakpoint set, it still defaults to open on some sizes

### What is actually happening?

If a Layout.Sider.breakpoint is set, Layout.Sider.defaultCollapsed will not be respected at layouts triggered by the breakpoint. i.e. if breakpoint="md" is set on the Sider, then on medium and above breakpoints the sider will render as collapsed but immediately open instead of staying collapsed.

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`breakpoint` is a trigger to tell Sider what state changed. `defaultCollapsed` set the default state but re-set to `false` by `onCollapse` prop. If you want to ignore this event at first, you can `useRef` or `useState` to record to ignore first time `onCollapse` trigger.
