### ISSUE TITLE
Table的分组表头没有正确显示

### ISSUE THREAD

**Issue by hitzzc** [ant-design/ant-design#4061]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本: OS X 10.10.5
- 浏览器及其版本: chrome 和 firefox都无法正确显示

#### 实际上的结果是:

样式错位了

#### 可重现的在线演示
http://codepen.io/hitzzc/pen/pNWqzy?editors=0010

**Comment by yesmeck** [comment]
对，不支持这种分组，不好实现而且感觉实际应用中也很少出现这种分组方式。

**Comment by hitzzc** [comment]
额那请问支持什么样的分组啊。我是根据官网样例写的，所以很困惑

**Comment by yesmeck** [comment]
有兄弟的 column 不能有 children。

**Comment by hitzzc** [comment]
哦？请问您指的有兄弟的column是？
我看https://ant.design/components/table/#components-table-demo-grouping-columns这个例子里，column “Age”有兄弟column "Address", 但“Address”是有children的啊~

**Comment by yesmeck** [comment]
我想想，刚才看错你的意图了，你是想要这样吧：

<table>
  <thead>
    <tr>
      <th rowSpan="3">Host</th>
      <th colSpan="5">Requests</th>
      <th>Errors</th>
    </tr>
    <tr>
      <th rowSpan="2">Total</th>
      <th rowSpan="2">POST</th>
      <th rowSpan="2">GET</th>
      <th rowSpan="2">Pending</th>
      <th rowSpan="2">Slow</th>
      <th>ADS</th>
    </tr>
    <tr>
      <th>failed</th>
    </tr>
  </thead>
</table>

**Comment by hitzzc** [comment]
对，是的

**Comment by hirohe** [comment]
必须对部分column加上 rowSpan才行
http://codepen.io/anon/pen/yVPJaW?editors=0010

**Comment by yesmeck** [comment]
修正了，重新安装下依赖。

**Comment by hitzzc** [comment]
赞！
