### ISSUE TITLE
Tour: Weird behavior on DOM changes and when target disappears from DOM

### ISSUE THREAD

**Issue by JulesLecuir** [ant-design/ant-design#40620]
#### Use case:
I want my user to click on a button A, so it can make the button B an C appear. When I click the button A, it disappears, and the buttons B and C show up.

#### How it works today:
- No way to react to user clicks or actions on the target
- If the target disappears from view, the Tour step automatically becomes a step without target (and goes fullscreen, that's not coherent)

### What does the proposed API look like?

Cheap fix: At least, if the focus on the target is lost, it could try to go to the next step automatically

Expensive fix and improvement: I would like the component to observe actions on the target and detect a click on it for example (and be able to fire actions on those events). Basically that could allow the Tour to go to the next step when I click on button A, so it can show me what are buttons B and C. 

See the 10th step of the [Reactour](https://reactour.vercel.app/) tour guide: 
> And the Tour could be observing changes to update the view, try clicking the button…

**Comment by MadCcc** [comment]
When `target` is null, antd Tour will be displayed at the center of screen. Could you provide a reproduction for this problem?
