### ISSUE TITLE
select控件和远程数据结合，第一次下拉框时没有滚动条。

### ISSUE THREAD

**Issue by fulisheng** [ant-design/ant-design#40625]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sjoj6f?file=/index.tsx)

### Steps to reproduce

1：打开官方文档链接的“控件”的"select选择器"，URL： https://ant.design/components/select-cn
2：找到 “搜索和远程数据结合” 
3：在下拉搜索框里随便输入，如输入"1"，等待数据加载。
4：数据加载后，没有滚动条。
5：滚动鼠标中键，滚动条出现。

这种情况数据很多，但没有出现滚动条，用户第一反应以为就可见的这些数据，导致界面不友好。

### What is expected?

数据多时，select控件第一次能出现滚动条。

### What is actually happening?

没有出现滚动条。

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 5.17 |
| System | win10 |
| Browser | chrome |

**Comment by MadCcc** [comment]
Scroll bar is forced visible when first mounted, and hidden by default. It is intended.

**Comment by MadCcc** [comment]
We could force scroll bar visible when list is changed.

**Comment by MuxinFeng** [comment]
#https://github.com/react-component/select/pull/916
