### ISSUE TITLE
The modal component doesn't apply the fontFamily from ConfigProvider

### ISSUE THREAD

**Issue by shahradelahi** [ant-design/ant-design#40627]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-ben-soqebs?file=/src/App.js)

### Steps to reproduce

Just open the sandbox

### What is expected?

The `Modal` component does not use config from `ConfigProvider`.

### What is actually happening?

NOt WoRkiNg

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
>  In most case, you do not need static method. It can not consume context like dynamic theme. Please use hooks version or App provided instance first.

https://ant.design/components/modal#components-modal-demo-static-info
