### ISSUE TITLE
12 hour format for time picker

### ISSUE THREAD

**Issue by andrewmclagan** [ant-design/ant-design#4063]
(Apologies cannot read the issue template as its in Mandarin/Cantonese character set)

Would you be interested in a pull request for a 12 hour option on the time picker?

**Comment by dreamcatcher081210** [comment]
+1，项目里同样遇到这类问题，只能手动写一堆代码来控制，最好封装下提供给用户，补充一句：antd正走向世界，如果说React是一个华美绝伦的王冠，我们中国人很希望antd成为那王冠上最璀璨的明珠！

**Comment by gushecht** [comment]
@andrewmclagan, do you have a solution that I can borrow?

**Comment by hlindley-ccssi** [comment]
I'm also looking for a solution for this. TIA

**Comment by pwax** [comment]
Also looking for 12 hour formatting 👍

**Comment by megawac** [comment]
Related: https://github.com/react-component/time-picker/issues/27

**Comment by afc163** [comment]
@shaleynikov is working on it.

https://github.com/react-component/time-picker/pull/34

**Comment by pwax** [comment]
Since 12 hour mode has been merged, is there an easy way to integrate it to ant? I'd love to contribute but I'm unsure how to incorporate the 12 hour format in the ant TimePicker.

**Comment by shaleynikov** [comment]
@pwax I'll try to bring PR on that next couple of days. There is only one new option -- use12Hours, so code should be trivial.
