### ISSUE TITLE
Ant Design Tree Component lagging when too much data

### ISSUE THREAD

**Issue by jonbala** [ant-design/ant-design#40635]
### Reproduction link

[https://ant.design/components/tree](https://ant.design/components/tree)

### Steps to reproduce

The speed when Tree has to deal with a lot of data

### What is expected?

a better and smooth, fast UI without lagging

### What is actually happening?

is lagging when tree is dealing with a lot of data

| Environment | Info |
| --- | --- |
| antd | 4.20.0 |
| React | React |
| System | MacOS |
| Browser | Chrome |

---
no :)

**Comment by MadCcc** [comment]
Could you provide a screenshot or gif for this performance issue?
