### ISSUE TITLE
Table的拖拽手柄列示例，被拖拽项在被拖拽时样式改变

### ISSUE THREAD

**Issue by three-water666** [ant-design/ant-design#40638]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/table-cn/#components-table-demo-drag-sorting](https://4x-ant-design.antgroup.com/components/table-cn/#components-table-demo-drag-sorting)

### Steps to reproduce

拖拽某一项

### What is expected?

被拖拽过程中的样式和被拖拽前一样

### What is actually happening?

样式错乱

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 18.0.0 |
| System | win10家庭版 |
| Browser | Google Chrome 版本 108.0.5359.94（正式版本） （64 位） |

---
Table的拖拽手柄列示例，被拖拽项在被拖拽过程中样式改变，表现为表格内容左移，内容之间间距缩小

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/40346
