### ISSUE TITLE
我可以将antd跟immutableJS一起用吗？antd组件内部是否能够支持PureRenderComponent

### ISSUE THREAD

**Issue by ubibi** [ant-design/ant-design#4064]
我可以将antd跟immutableJS一起用吗？antd组件内部是否能够支持PureRenderComponent

**Comment by benjycui** [comment]
`antd` 并不支持 immutable.js 的类型，所以传进来之前还是得转换一下。

部分组件加了 PureRenderMixin。

如果你碰到性能问题，建议每个场景一个 issue 并提供 demo，逐个解决。

**Comment by dreamcatcher081210** [comment]
如果用到了redux 可以使用immutable-redux，但是如果使用merge()方法的话要记得在取出来使用时toJS()一下，其它方法暂且不用，reducer里set后取出直接给antd组件即可，现在我们的项目里已经用过了

**Comment by benjycui** [comment]
> 如果你碰到性能问题，建议每个场景一个 issue 并提供 demo，逐个解决。

Close now.

**Comment by goodmind** [comment]
@benjycui can't you just support `Symbol.iterable` where you need arrays now?
