### ISSUE TITLE
v4.16.13升级v4.24.7几大类兼容问题，预期要兼容么？

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#40643]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shi-yong-hooks-huo-de-shang-xia-wen-antd-4-24-7-forked-636f4q?file=/demo.tsx)

#### 升级后，FormItem flex及其嵌套样式错位问题

* 4.24.7 复现版本：https://codesandbox.io/s/antd-4-24-7-repo-o7sv1q?file=/index.js
* 4.16.13对比版本：https://codesandbox.io/s/antd-4-16-13-repo-forked-ge1xox?file=/index.js

【符合预期】Form.Item 结构调整对应 `flex` 位置也进行了调整。魔改样式需要自行升级时调整。

#### 升级后原Tabs滚动内容无法出现滚动条

* https://codesandbox.io/s/antd-tabs-scroll-forked-949jet?file=/index.js

【符合预期】Tabs 从水平切换动画替换成渐隐渐入动画，不再使用 `flex` 布局。魔改样式需要自行升级时调整。

#### 升级后Modal和Drawer 使用ESC关闭时无法依次关闭，要么都关闭，要么最后一层无法关闭(如上复现链接)，要么关闭了底层同时上层无法关闭

【BUG】已修复 ref #40748

#### 升级后下拉菜单折行，无法撑开等

【WONT FIX】#34177 修复过长文本不换行导致超出屏幕的问题。例子中的屏幕出现横向滚动条使得对齐逻辑认为空间足够而不翻转。如果不存在滚动条则不会有这个问题。考虑到 超长出屏幕 和 屏幕滚动 两个情况，前者更常见，因而选择不修复：
* 4.24.7 https://codesandbox.io/s/antd-4-24-7-repo-forked-719pbf?file=/index.js
* 4.16.13 https://codesandbox.io/s/antd-4-16-13-repo-forked-0ekzuf?file=/index.js

PS: 这的确是个兼容性问题，在 v5 中更新了对齐逻辑应该就不会有这个情况了。

#### 不兼容的参数和逻辑变更

- 【符合预期】Drawer参数 visible 变成了open
  - 原本的 `visible` 仍然可以使用
- 【符合预期】TreeSelect treeData属性字段 key 变成了value
  - 本来也是 `value`，`key` 只是作为 `React.Key` 映射用，从 v3 起官方文档的示例就是 `value`。因为有不少误用的情况 v4 后期对 `value` 和 `key` 做检查并 warning 出来。
- 【WONT FIX】Select value值格式和tagRender传参内容和调用方式变了，这个版本传数组能拿到数组
  - `value` 类型定义不使用 `labelInValue` 为 `(string | number)[]`，`string[][]` 即便在某个版本可行也是 BUG as Feature。非标用法，不会做兼容。
  - 4.16.13 https://codesandbox.io/s/antd-4-16-13-repo-forked-6029ft?file=/index.js
  - 4.24.7 https://codesandbox.io/s/antd-4-24-7-repo-forked-w79n8t?file=/index.js
- 【符合预期】Table渲染过程有区别，这个版本可以改数字
  - 数据更新不能直接改原来对象，同样是 BUG as Feature 哈。参考：https://codesandbox.io/s/antd-4-24-7-repo-forked-zykqbz?file=/index.js
- 其他有待发现

### What is expected?

希望能兼容就兼容，不兼容的希望能给出不兼容的说明，看看哪些预期要兼容的，我来提供复现场景，一起搞一搞，不兼容的就只能认栽了

### What is actually happening?

升级后不兼容问题多，影响范围较大

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17.0.2 |
| System | masOS Monterey 12.1 |
| Browser | chrome 101.0.4951.64 |

**Comment by afc163** [comment]
如果确定是改出来的问题，那都要兼容，帮忙提供一下重现吧。

**Comment by arvinxx** [comment]
@afc163  1 和 2 我在 kitchen 都有遇到，应该都是 dom 结构改了以后造成的

**Comment by rawbin-** [comment]
先给出几个样式和交互差异来，后面在补参数格式和字段变更的影响
4.24.7 复现版本：https://codesandbox.io/s/antd-4-24-7-repo-o7sv1q?file=/index.js
4.16.13对比版本：https://codesandbox.io/s/antd-4-16-13-repo-o7sv1q?file=/index.js

**Comment by rawbin-** [comment]
Tabs无法出现原有的滚动条，看起来是.ant-tabs-content 丢掉了 display:flex 导致
https://codesandbox.io/s/antd-tabs-scroll-o7sv1q?file=/index.js

**Comment by MadCcc** [comment]
> Tabs无法出现原有的滚动条，看起来是.ant-tabs-content 丢掉了 display:flex 导致 https://codesandbox.io/s/antd-tabs-scroll-forked-949jet?file=/index.js

https://codesandbox.io/s/antd-tabs-scroll-forked-gymsio?file=/index.js:1069-1075 这是不是你期望的？

**Comment by rawbin-** [comment]
> > Tabs无法出现原有的滚动条，看起来是.ant-tabs-content 丢掉了 display:flex 导致 https://codesandbox.io/s/antd-tabs-scroll-forked-949jet?file=/index.js
> 
> https://codesandbox.io/s/antd-tabs-scroll-forked-gymsio?file=/index.js:1069-1075 这是不是你期望的？

主体有一个诉求：页面直接由Tabs组成，每一个Tab里面可能有多个内容要可能没有内容
有内容的话：依次为A，B，C，希望只是C部分滚动，这个会受.ant-tags-content 去掉的display:flex影响，升级后无法滚动（如上demo）
没内容的话：直接tabs里面的内容滚动，而不是全页面滚动（需要Tabs头始终在页面顶部），这个会受.ant-tabs去掉的overflow:hidden影响，升级后变成了全页面滚动

**Comment by rawbin-** [comment]
modal Drawer同时使用，按ESC关闭，升级后弹层关闭异常，（最严重的见场景2）
4.24.7版本：https://codesandbox.io/s/antd-4-24-7-modal-drawer-repo-forked-dvmjed?file=/index.js
4.16.13版本：https://codesandbox.io/s/antd-4-16-13-modal-drawer-repo-forked-92kdxe?file=/index.js

**Comment by afc163** [comment]
> Drawer参数 visible 变成了open

这是预期的，visible 还是能用的。

**Comment by zombieJ** [comment]
> modal Drawer同时使用，按ESC关闭，升级后弹层关闭异常，（最严重的见场景2） 4.24.7版本：https://codesandbox.io/s/antd-4-24-7-modal-drawer-repo-forked-dvmjed?file=/index.js 4.16.13版本：https://codesandbox.io/s/antd-4-16-13-modal-drawer-repo-forked-92kdxe?file=/index.js
> 
> 这个问题比较严重，直接影响到交互过程了，单独提了个Issue #40748

@rawbin- 能帮忙像 #40748 拆一下 issue 吗？这样单独好解，不容易漏东西。

**Comment by zombieJ** [comment]
@rawbin- 我更新了一下描述部分，有一些需要重现，帮忙看看补一补哈~

**Comment by afc163** [comment]
> 升级后下拉菜单折行，无法撑开等

在两个 codesandbox 里对比。
<img width="189" alt="图片" src="https://user-images.githubusercontent.com/507615/219351823-702461dc-69aa-4ba6-8c2b-2034288fbcd6.png">
<img width="126" alt="图片" src="https://user-images.githubusercontent.com/507615/219351864-a6588e95-2681-4299-8cca-e39762344e99.png">

**Comment by afc163** [comment]
> 【需要重现】Select value值格式和tagRender传参内容和调用方式变了，这个版本传数组能拿到数组 
重现也在这两个codesandbox里。

<img width="252" alt="图片" src="https://user-images.githubusercontent.com/507615/219352038-35a6e152-5b3a-47cb-8eef-fd778c038c41.png">

<img width="242" alt="图片" src="https://user-images.githubusercontent.com/507615/219352068-a788aaec-6e2b-45b0-8297-709aaa232ac5.png">

**Comment by rawbin-** [comment]
对，前面两个对比都在demo里面，table那个这里竟然没复现有点尴尬哈，按理说也是符合预期，4.16.13版本里面直接改了表格data，然后没有重新生成data数组，也能渲染出来（这个看起来不符合预期的，但demo里没复现我再研究研究），4.24.7 需要data引用变了才能渲染出来（也就是实现更改数字的效果），这个才对

**Comment by zombieJ** [comment]
> 对，前面两个对比都在demo里面，table那个是这样的，如demo那样改数字的值，4.16.13版本下OK（可以正常改），4.24.7版本下不OK（改不了），但分析发现，4.24.7版本这个改不了的状态本身才是符合技术逻辑的。。。因为dataSource的引用没有变更

嗯，我更新到 desc 里了。你再看看有没有其他的哈~其中 Dropdown 那个的确是问题，但是两者相较还是选择不修了
