### ISSUE TITLE
需要统一修改 input:focus box-shadow 颜色的能力

### ISSUE THREAD

**Issue by 1026903031** [ant-design/ant-design#40648]
### What problem does this feature solve?

主题定制里面没有相关参数 https://github.com/vueComponent/ant-design-vue/blob/master/components/style/themes/default.less

### What does the proposed API look like?

能够在主题定制中实现box-shadow的修改

**Comment by Yuiai01** [comment]
我来试试看

**Comment by li-jia-nan** [comment]
你这个是 vue 的仓库吧，是不是走错了

**Comment by yoyo837** [comment]
有 https://github.com/vueComponent/ant-design-vue 仓库权限的给 Transfer 过去一下.

**Comment by Yuiai01** [comment]
尴尬了 没注意是 vue 的库

**Comment by 1026903031** [comment]
了解了，我这边close掉，重新提吧
