### ISSUE TITLE
ConfigProvider对Modal.warning()函数调用式组件不起作用

### ISSUE THREAD

**Issue by kororinto** [ant-design/ant-design#40646]
### Reproduction link

[https://github.com/kororinto/antd-issue](https://github.com/kororinto/antd-issue)

### 1. 使用ConfigProvider组件修改样式
```javascript
const primary = '#006bfd';
```
渲染部分
```jsx
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: primary,
          colorInfo: primary,
          colorInfoText: primary,
          colorLink: primary,
          colorPrimaryText: primary,
          colorText: '#20242C',
          colorSuccess: '#26bd71',
          colorWarning: '#ff7900',
          colorError: '#f53f3f',
        },
      }}
    >
      <div id="theme-container" className="w-full h-[100vh] flex flex-col">{children}</div>
    </ConfigProvider>
```

### 2. 在别的地方使用Modal.success、Modal.warning、Modal.error
```javascript
Modal.success({
  title: 'ConfigProvider配置的主题色未生效',
  content: '使用Modal的函数式组件 在ConfigProvider配置的主题色无法生效',
  okText: 'ConfigProvider配置的主题色未生效',
  getContainer: '#theme-container',
});
```

### What is expected?

ConfigProvider配置的主题色在Modal中没有生效
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/58289085/217589458-40b6eea7-d7b3-446a-a0b1-59179f0eca4d.png">

### What is actually happening?

ConfigProvider配置的主题色在Modal中生效

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome 109.0.5414.119（正式版本） (arm64) |

**Comment by Yuiai01** [comment]
你好 @kororinto ，我发现你在代码中是使用 Modal 的静态方法：
<img width="678" alt="image" src="https://user-images.githubusercontent.com/112228030/217684118-be7e646b-fe60-41de-9df2-3e395bad51b7.png">
直接调用 Modal 方法，antd 会通过 `ReactDOM.render` 动态创建新的 React 实体。其 context 与当前代码所在 context 并不相同，因而无法获取 context 信息。你可以参考这个：https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx。或者使用 App 组件 https://ant.design/components/app。

**Comment by yoyo837** [comment]
Duplicate of #40546 #40576

**Comment by kororinto** [comment]
> 你好 @kororinto ，我发现你在代码中是使用 Modal 的静态方法： <img alt="image" width="678" src="https://user-images.githubusercontent.com/112228030/217684118-be7e646b-fe60-41de-9df2-3e395bad51b7.png"> 直接调用 Modal 方法，antd 会通过 `ReactDOM.render` 动态创建新的 React 实体。其 context 与当前代码所在 context 并不相同，因而无法获取 context 信息。你可以参考这个：https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx 或者使用 App 组件 https://ant.design/components/app

这种方法只能在React的函数组件中使用，在普通函数中怎么使用？

**Comment by kororinto** [comment]
> 

上述方法只能在React的函数组件中使用，在普通函数中怎么使用？

**Comment by luo3house** [comment]
> 上述方法只能在React的函数组件中使用，在普通函数中怎么使用？

https://github.com/ant-design/ant-design/issues/40459#issuecomment-1408267164

在 React 周期封装所需配置后暴露实例

**Comment by kororinto** [comment]
> > 上述方法只能在React的函数组件中使用，在普通函数中怎么使用？
> 
> [#40459 (comment)](https://github.com/ant-design/ant-design/issues/40459#issuecomment-1408267164)
> 
> 在 React 周期封装所需配置后暴露实例

按照这个方法报错了：
<img width="433" alt="image" src="https://user-images.githubusercontent.com/58289085/217737178-73780f6e-c9e1-4b4d-994c-1817ebde4eaf.png">
<img width="483" alt="image" src="https://user-images.githubusercontent.com/58289085/217737204-cdc85ced-5bb8-442a-9b8f-5da5bebdd5ba.png">
![image](https://user-images.githubusercontent.com/58289085/217737246-eb519cab-4f3e-467c-8d7f-07615479fa26.png)

**Comment by kororinto** [comment]
已解决，谢谢

**Comment by kororinto** [comment]
> > 上述方法只能在React的函数组件中使用，在普通函数中怎么使用？
> 
> [#40459 (comment)](https://github.com/ant-design/ant-design/issues/40459#issuecomment-1408267164)
> 
> 在 React 周期封装所需配置后暴露实例

已解决，多谢

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546
