### ISSUE TITLE
Form 中添加 DatePicker以后，不能通过 回车键 提交表单

### ISSUE THREAD

**Issue by hungtcs** [ant-design/ant-design#40651]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-p7r5xm?file=/index.js)

### Steps to reproduce

鼠标聚焦到 input，然后按回车键。

### What is expected?

提交表单。

### What is actually happening?

不会提交表单。

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

---
奇怪的是，如果在表单中添加一个 `<button type="submit"></button>`，就又可以使用回车键提交了。
另外，怎么禁用回车打开日历选择，而是提交表单呢？

**Comment by hungtcs** [comment]
```ts
const App = () => {
  const onFinish = useCallback((values) => {
    console.log("form submit", values);
  }, []);

  return (
    <div className="App">
      <Form onFinish={onFinish} layout="vertical">
        <Form.Item name="field1">
          <Input placeholder="尝试使用回车键提交" />
        </Form.Item>
        <p>如果添加 date picker，则无法使用键盘提交</p>
        <Form.Item name="field2">
          <DatePicker />
        </Form.Item>
      </Form>
    </div>
  );
};
```

上面代码中，如果注释掉 field2，回车键就会生效。
```ts
<Form.Item name="field2">
  <DatePicker />
</Form.Item>
```

**Comment by zombieJ** [comment]
这是浏览器原生行为，和 antd 和 React 都没关系的，单个表单项回车会提交。如果你是多个表单项需要回车提交，在 Form 上监听一下 keyDown 事件，如果是回车就提交就好了。
