### ISSUE TITLE
StyleProvider设置升级“high”后，Model.confirm没有生效，还是使用:where

### ISSUE THREAD

**Issue by LinWeb** [ant-design/ant-design#40658]
### Reproduction link

[https://ant-design.gitee.io/components/modal-cn](https://ant-design.gitee.io/components/modal-cn)

### Steps to reproduce

在谷歌浏览器V65版本打开

### What is expected?

StyleProvider设置升级“high”后，Model.confirm样式生效

### What is actually happening?

StyleProvider设置升级“high”后，Model.confirm样式没有生效

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 16.10.2 |
| System | window |
| Browser | 谷歌浏览器V65 |

**Comment by zombieJ** [comment]
> 在绝大多数场景，都不需要静态方法。它无法消费 context，例如无法响应动态主题。请优先使用 hooks 版本或者 App 组件提供的 Modal 实例。

StyleProvider 也是 context。

**Comment by LinWeb** [comment]
> 



> > 在绝大多数场景，都不需要静态方法。它无法消费 context，例如无法响应动态主题。请优先使用 hooks 版本或者 App 组件提供的 Modal 实例。
> 
> StyleProvider 也是 context。

那就是无法解决了么？样式兼容方案无法解决类似Modal.confirm静态方法这种问题了？

**Comment by yoyo837** [comment]
兼容方案只是处理样式的吧? 和静态方法读取不到context是两件事吧

**Comment by LinWeb** [comment]
> 



> 兼容方案只是处理样式的吧? 和静态方法读取不到context是两件事吧

现在是设置<StyleProvider hashPriority="high" transformers={[legacyLogicalPropertiesTransformer]}>后，是为了解决兼容低版本浏览器的问题，但是无法解决类似Modal.confirm静态方法的样式，Modal.confirm用的还是“:where”选择器导致样式没有生效

**Comment by yoyo837** [comment]
换 hooks

**Comment by LinWeb** [comment]
> 换 hooks

改的地方太多了，改动太大了，已回滚到V4版本，希望后面能有更好的解决方案

**Comment by xiaofuliang** [comment]
现在还是不要用V5版本，国内厂商的浏览器内核版本还是太低了，有些样式还是不兼容，我也是回滚到了V4

**Comment by supuwoerc** [comment]
StyleProvider包在App外面就行了，我们团队遇到了message等组件的where降级不成功的问题，然后这样修复了~😁

**Comment by chenJJ-88** [comment]
> > 换 hooks
> 
> 改的地方太多了，改动太大了，已回滚到V4版本，希望后面能有更好的解决方案

我看到你使用的是chrome65版本的，请教一下如何处理样式兼容问题呢？我是71版本，antd 的样式无法生效，安装文档配置后也不行，谢谢大佬

**Comment by qwe5117022** [comment]
> StyleProvider包在App外面就行了，我们团队遇到了message等组件的where降级不成功的问题，然后这样修复了~😁

这样不行的，能解决message，不能解决modal.confirm
