### ISSUE TITLE
RangePicker 的交互形式能否兼容3.x版本或者提供一些API来实现3.x的交互效果

### ISSUE THREAD

**Issue by renpeng11** [ant-design/ant-design#40657]
### What problem does this feature solve?

下拉 pannel 的日期面板，相互不连续，能够各自选择各自的日期

### What does the proposed API look like?

是否开启，各自切换左右两边的日期

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32982#issuecomment-976174396
