### ISSUE TITLE
Provide examples about how `antd` integrates in different backend langs & frameworks

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4065]
Background: https://segmentfault.com/q/1010000007629298

I think that we can create a repository in ant-design group, and provide examples that how `antd` works with different backend programming languages(PHP/JAVA..) and frameworks(ThinkPHP/Spring MVC...)

I am not sure if it is necessary, for someone it's simple and obvious, but not for everyone.

**Comment by benjycui** [comment]
Something like this https://github.com/tastejs/todomvc

**Comment by afc163** [comment]
Nothing special to normal React project.
