### ISSUE TITLE
searchValue 属性设置后，无法修改

### ISSUE THREAD

**Issue by msyesyan** [ant-design/ant-design#40661]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xi517n)

### Steps to reproduce

1. focus 到选择器上, 应该能看到默认的 searchValue 是 lucy
2. 尝试输入或者删除 searchValue, 发现不能修改 searchValue

### What is expected?

希望 searchValue 可以被修改

### What is actually happening?

searchValue 一旦设置不可修改

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | Debian GNU/Linux 11 |
| Browser | Chrome 109.0.5414.119 |

**Comment by msyesyan** [comment]
![image](https://user-images.githubusercontent.com/2162116/217784048-4d71add2-a21e-4348-832e-d66de20511c7.png)

如图所示，这个 searchValue 设置上不能修改

**Comment by afc163** [comment]
searchValue 是受控属性

https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-inputselect-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86
