### ISSUE TITLE
DatePicker.RangePicker Bug

### ISSUE THREAD

**Issue by ssdeniss** [ant-design/ant-design#40669]
### Reproduction link

[https://github.com/ssdeniss/Antd-Components](https://github.com/ssdeniss/Antd-Components)

### Steps to reproduce

Create a DatePicker.RangePicker in my case in Form.Item and add a initialValue after open the DatePicker

### What is expected?

it's terrible, sometimes it doesn't work, if I open DatePicker it starts an infinite loop that changes the date without stopping

### What is actually happening?

it's terrible, sometimes it doesn't work, if I open DatePicker it starts an infinite loop that changes the date without stopping

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by ssdeniss** [comment]
@ant-design-bot pls help me

**Comment by Yuiai01** [comment]
@ssdeniss Hello, can you provide an online link that can reproduce the problem?

**Comment by ssdeniss** [comment]
https://github.com/ssdeniss/Antd-Components
https://codepen.io/ssdeniss/pen/MWBMoJJ

in codepen I tried to create a project on version 5.2.0 but I couldn't, above I have an example from my repository

**Comment by ssdeniss** [comment]
If u have some project on antd 5.2.0, try this 
            <Form>
              <Form.Item
                name="dateRange"
                initialValue={[moment("2022-01-01"), moment("2022-01-15")]}
              >
                <DatePicker.RangePicker />
              </Form.Item>
            </Form>

**Comment by ssdeniss** [comment]
@Yuiai01 This is a link with example of bug
https://codesandbox.io/s/elegant-mestorf-qu4f1x?file=/src/App.js

**Comment by ssdeniss** [comment]
@Yuiai01 I created a RangePicker and simple DatePicker, they have different problems, Range start a infinite loop when u open it, but datePicker start a loop when u open it and move mouse inside

**Comment by MadCcc** [comment]
In 5.x, dayjs is used by default instead of momentjs.
https://codesandbox.io/s/heuristic-tu-orlphk?file=/src/App.js

**Comment by MadCcc** [comment]
If you still want to use momentjs, ref: https://ant.design/docs/react/use-custom-date-library

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774
