### ISSUE TITLE
[Bug] Grid: Card components flickering inside Col

### ISSUE THREAD

**Issue by hbatalhaStch** [ant-design/ant-design#40662]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/grid-gutter-antd-5-2-0-forked-5w8rx2?file=/demo.tsx)

### Steps to reproduce

Open the sandbox browser in a window: https://5w8rx2.csb.app/

### What is expected?

The componebts laid out correctly

### What is actually happening?

The components flickering nonstop

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 18.0.0 |
| System | Windows 10 Pro Version: 21H2 OS; Build: 19044.2486 |
| Browser | MS Edge |

**Comment by MadCcc** [comment]
Could you provide a screenshot?

**Comment by hbatalhaStch** [comment]
Open the [Steps to reproduce link](https://5w8rx2.csb.app/)

> Could you provide a screenshot?
![CPT2302151050-1904x512](https://user-images.githubusercontent.com/114578587/219019952-cd79faf7-9631-4d31-a584-b7225034906e.gif)

**Comment by bomangoo** [comment]
Hello hbatalhaStch
First of all, I don't know why are you write components twice.

like this,
<Row><Col><Row><Col>contents</Col></Row></Col></Row>

I tried it. If write once, no error occur.
like this,
<Row><Col>contents</Col></Row>

If there is a reason to write twice, you should write 'width:100%' in Row component.

**Comment by afc163** [comment]
Like @bomangoo said, you can try to remove extra Row/Col: https://codesandbox.io/s/grid-gutter-antd-5-2-0-forked-rrnrdh?file=/demo.tsx

**Comment by hbatalhaStch** [comment]
hi @bomangoo @afc163 

The reason I put the extra Row/Col is that I want a separate space beside the two cards. In that space I want it to have its own scrollbar.
Like here: https://altence.com/lightence-admin-demo#/medical-dashboard
