### ISSUE TITLE
Form表单错误状态异常：<Input addonBefore="operator" />

### ISSUE THREAD

**Issue by JackXM** [ant-design/ant-design#40664]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-biao-dan-kong-jian-antd-5-1-7-forked-cwvpt3?file=/demo.tsx)

### Steps to reproduce

点击确定按钮，可以看到中间那个输入框左边的文案框变红了，被校验住了。

### What is expected?

我没写rules必填，他不应该被报错

### What is actually happening?

红框报错

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 17.0.2 |
| System | Mac |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
确实
<img width="837" alt="image" src="https://user-images.githubusercontent.com/112228030/217807097-97215870-8143-47fd-abf3-6dbbbc12c261.png">

**Comment by Yuiai01** [comment]
感觉和这个问题类似 https://github.com/ant-design/ant-design/issues/40589

**Comment by carla-cn** [comment]
让我试试呢
