### ISSUE TITLE
Table - Text selection after multiple clicks on sorting arrows

### ISSUE THREAD

**Issue by DrDoodlez** [ant-design/ant-design#40678]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/filter-and-sorter-antd-5-2-0-forked-s96yji)

### Steps to reproduce

Open demo table with enabled sorting.
Click multiple times on sorting arrows or header with sorting.

### What is expected?

Sorting was changed. Header text or text in placeholder shouldn't be selected(highlighted)

### What is actually happening?

Sorting was changed. BUT нeader text or text in placeholder are selected(highlighted) after few clicks

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 18.0 |
| System | 10.0.19045 |
| Browser | 109.0.5414.120 |

---
Maybe click on sort arrows(header with sorting) should prevent another default actions(like selection)

**Comment by MadCcc** [comment]
Add `preventDefault` to prevent.

**Comment by AnathanPham** [comment]
> Add `preventDefault` to prevent.

I tried it. It does not work,whatever I add EventListener to Dom or V-Dom of React.

you need to use `user-select: none;` to prevent text from being selected

**Comment by zombieJ** [comment]
Since sometime user need native behavior of selection by double click. It may not apply by default. But yes, style updating is the resolution.
