### ISSUE TITLE
从 v4 到 v5 升级文档有问题

### ISSUE THREAD

**Issue by besoshanjun** [ant-design/ant-design#40676]
### Reproduction link

[https://ant.design/docs/react/migration-v5-cn#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%B0%83%E6%95%B4](https://ant.design/docs/react/migration-v5-cn#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%B0%83%E6%95%B4)

### Steps to reproduce

组件重构与移除
移除 Comment 组件，移至 @ant-design/compatible 中维护。

移除 PageHeader 组件，移至 @ant-design/pro-components 中维护。

- import { PageHeader, Comment } from 'antd';
  import { Comment } from '@ant-design/compatible';
  import { PageHeader } from **'@ant-design/pro-layout';**
  const App: React.FC = () => (
    <>
      <PageHeader />
      <Comment />
    </>
  );
  export default App;

### What is expected?

组件重构与移除
移除 Comment 组件，移至 @ant-design/compatible 中维护。

移除 PageHeader 组件，移至 @ant-design/pro-components 中维护。

- import { PageHeader, Comment } from 'antd';
  import { Comment } from '@ant-design/compatible';
  import { PageHeader } from '@ant-design/pro-components';
  const App: React.FC = () => (
    <>
      <PageHeader />
      <Comment />
    </>
  );
  export default App;

### What is actually happening?

  import { PageHeader } from '@ant-design/pro-layout';

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 17 |
| System | macOS |
| Browser | chrome |

---
不是bug，文案有误，前后不对应

**Comment by LongHaoo** [comment]
@besoshanjun 统一在 pro-component 导出

**Comment by LongHaoo** [comment]
<img width="530" alt="截屏2023-02-10 16 57 28" src="https://user-images.githubusercontent.com/45565100/218047935-077ccb0a-9d69-4d32-9690-ac6a01696a31.png">
应该是没问题的，统一收敛到 @ant-design/pro-components 导出
