### ISSUE TITLE
Mention 组件输入增强提议

### ISSUE THREAD

**Issue by developerworks** [ant-design/ant-design#4067]
https://ant.design/components/mention/?locale=zh-CN

当我结束一个输入的时候, 必须手工再次点击该文本框进行第二次输入, 如果在需要输入 **多个@项** 的情况下, 我需要 **重复** 的用鼠标点击文本框.

![](https://cloud.githubusercontent.com/assets/725190/20738081/b3b4df32-b6eb-11e6-85c3-df85f242b915.gif)

**Comment by RaoHai** [comment]
reinstall dependencies will fix this issue.
