### ISSUE TITLE
日期组件时间范围动态跟随（can rangepicker component provied prop to achieve paneltime dynamically followed pre chosen time）

### ISSUE THREAD

**Issue by EmilyLike** [ant-design/ant-design#40680]
### What problem does this feature solve?

解决的问题：日期时间高频更改问题

这个需求来自我公司的用户，使用场景为：

在已设置一个时间的情况下，并且时间不能清空，去修改时间为更久远的时间。

比如：
当前功能：当前选择时间为：2023-02-01 至 2023-02-10，
修改开始时间为 2022-11-01，结束时间的时间选择范围首先弹出的是 2023 年 2月 和 2023年3月。
期待功能： 
 修改开始时间为 2022-11-01，结束时间的时间选择范围首先弹出的是 2022年 11月 和 2022年 12 月。

### What does the proposed API look like?

提供一个boolean 属性： followBeforeUpdate，默认为 false，
如果修改 为 true 的时候，改为 时间范围跟随之前选中的时间。

**Comment by Yuiai01** [comment]
感觉这个场景在总时长不变，但是起始时间变更的情况下能提供很好的帮助

**Comment by EmilyLike** [comment]
这个需求我是通过 onfocus + onblur + onOpenChange 实现的。

通过各种api 调试，我发现，在当前 api下，如果想实现时间范围动态跟随，必须清空当前选择。
也就是说，当 focus 到当前日期选择框的时候（无论是开始还是结束），清空当前选择框的时间，所弹出的选择范围就会跟随第一个更改的时间。

如果切换时间选择框之后，用户不选择新的时间，就会存在时间为空的情况。

于是缓存了改变之前的日期，在onBlur 和 onOpenChange 中，修正没有填充的日期。

talk is cheep，I will show  the code。

`import React, { useEffect, useState } from "react";
import "./index.css";
import type { DatePickerProps } from "antd";
import { DatePicker, Space } from "antd";
import dayjs from "dayjs";
import customParseFormat from "dayjs/plugin/customParseFormat";
import isBetween from "dayjs/plugin/isBetween";
dayjs.extend(customParseFormat);
dayjs.extend(isBetween);

const { RangePicker } = DatePicker;

const dateFormat = "YYYY/MM/DD";

const App: React.FC = () => {
  const [rangValue, setRangValue] = useState([
    dayjs(),
    dayjs().add(2, "month")
  ]) as any;

  const [originValue, setOriValue] = useState(rangValue);

  const onFocus = (f: any) => {
    // 获取当前聚焦的值（不同的环境可能聚焦的值存的位置不同）
    const value = f.srcElement._value;

    const isStart =
      dayjs(rangValue[0]).format(dateFormat) ===
      dayjs(value).format(dateFormat);

    // 聚焦在哪一个，就清空哪一个
    setRangValue([isStart ? "" : rangValue[0], isStart ? rangValue[1] : ""]);
  };

  const onBlur = (b) => {
    setRangValue([
      rangValue[0] || originValue[0],
      rangValue[1] || originValue[1]
    ]);
    setOriValue(rangValue);
  };

  const onOpenChange = (open) => {
    if (!open) {
      setRangValue([
        rangValue[0] || originValue[0],
        rangValue[1] || originValue[1]
      ]);
      setOriValue(rangValue);
    }
  };

  return (
    <Space direction="vertical" size={12}>
      <RangePicker
        value={rangValue}
        format={dateFormat}
        onFocus={onFocus}
        onBlur={onBlur}
        onOpenChange={onOpenChange}
      />
    </Space>
  );
};

export default App;
`

**Comment by EmilyLike** [comment]
在issue： https://github.com/ant-design/ant-design/issues/39902 中也提到了类似的问题。

**Comment by MadCcc** [comment]
这个功能在相反场景下仍会有体验问题，比如起始和结束时间相差较远，重新选择后没有定位到上次选择的结束时间而是新选择的起始时间，还是会增加用户操作。

**Comment by EmilyLike** [comment]
> 这个功能在相反场景下仍会有体验问题，比如起始和结束时间相差较远，重新选择后没有定位到上次选择的结束时间而是新选择的起始时间，还是会增加用户操作。当用户只希望改一个时间的情况下不定位到上次选择的时间反而比较反直觉。

是的，所以我提供了两种可能的解决方案：
1、添加一个新的prop（提供一个boolean 属性： followBeforeUpdate，默认为 false，
如果修改 为 true 的时候，改为 时间范围跟随之前选中的时间。） 
2、我在stackoverflow 看到过类似的问题，都是在onfocus中更改双向绑定的日期，但是onfocus仅提供了focus 的dom 参数，因此，简单办法，可以在 focus 回调中暴露当前所选中的 日期值。

**Comment by jiaojiaoovruirui** [comment]
这个功能在相反场景下仍会有体验问题，比如起始和结束时间相差较远，重新选择后没有定位到上次选择的结束时间而是新选择的起始时间，还是会增加用户操作。当用户只希望改一个时间的情况下不定位到上次选择的时间反而比较反直觉。

**Comment by MadCcc** [comment]
如果第二次选择的开始/截止时间在范围外可以不跳转面板

**Comment by EmilyLike** [comment]
https://github.com/ant-design/ant-design/issues/26853   
经过搜索，发现了一个相同的问题。
| 提供一个手动的切换到上个面板或者下个面板的方法（或者内部已自动实现，只需要配置一个布尔变量表明是否要开启此功能即可）。
issuer提出的解决方法与我的一致。

**Comment by kkkkkkxser** [comment]
> 这个需求我是通过 onfocus + onblur + onOpenChange 实现的。
> 
> 通过各种api 调试，我发现，在当前 api下，如果想实现时间范围动态跟随，必须清空当前选择。 也就是说，当 focus 到当前日期选择框的时候（无论是开始还是结束），清空当前选择框的时间，所弹出的选择范围就会跟随第一个更改的时间。
> 
> 如果切换时间选择框之后，用户不选择新的时间，就会存在时间为空的情况。
> 
> 于是缓存了改变之前的日期，在onBlur 和 onOpenChange 中，修正没有填充的日期。
> 
> talk is cheep，I will show the code。
> 
> https://codesandbox.io/s/date-format-antd-5-1-7-forked-kltlrb?file=/demo.tsx:0-1572
> 
> 代码中存在一个问题，在focus的时候，必须知道是start 时间还是end 时间，只能通过onfocus函数的参数去判断。
> 
> 如果考虑到新增加一个prop 的成本太大，也可以增加onfocus 事件暴露的参数，可以和oncalendarchange 暴露的参数保持一致。

demo报错了啊

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
