### ISSUE TITLE
Select在数据过多时，通过给Option设置样式：display：'none' 前端隐藏某些选项，下拉框会出现空白，被隐藏的数据不显示 但是dom结点还在

### ISSUE THREAD

**Issue by 15167103105** [ant-design/ant-design#40685]
### Reproduction link

[https://ant.design/components/select-cn#select-props](https://ant.design/components/select-cn#select-props)

### Steps to reproduce

antd版本：4.17.0
1.不用options传递数据源 通过select.option的写法 给Option样式 style={{ display:  'none' }}

<Option style={{ display:  'none' }} value={item.id}  key={item.id}  label={item.title}> {item.title} </Option>

2.数据多一些 能滚动下拉框则能复现

### What is expected?

下拉框中没有多余留白，被隐藏的数据dom结点不显示

### What is actually happening?

下拉框中有多余留白，被隐藏的数据dom结点仍显示

| Environment | Info |
| --- | --- |
| antd | 4.20.3 |
| React | 18.0 |
| System | macOs |
| Browser | google |

---
不能直接过滤隐藏的数据 被隐藏的数据只是不能选 但是需要回显 所以通过css样式隐藏

**Comment by 15167103105** [comment]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/34081651/218249884-b28ae262-1c59-4425-b534-0553f658a4a9.png">

select和treeselect都有这个问题

**Comment by yoyo837** [comment]
这根本不是React style用法，这不是jquery

**Comment by yoyo837** [comment]
disabled不满足你的需求？

**Comment by 15167103105** [comment]
> disabled不满足你的需求？

产品不想要 可能存在很多数据被暂停和删除 disabled交互不太好

**Comment by chenzn1** [comment]
可以过滤一下 options
```
options.filter(option => option.display)
```

**Comment by 15167103105** [comment]
> 



> 可以过滤一下 options
> 
> ```
> options.filter(option => option.display)
> ```

options.filter(option => option.display)

> 可以过滤一下 options
> 
> ```
> options.filter(option => option.display)
> ```

因为被过滤的数据需要回显和修改 所以不能过滤哈 被过滤了之后就只能回显value 而不是label 所以只能通过css样式隐藏哈

**Comment by MadCcc** [comment]
如果想删除 dom 节点就过滤。设置 css 样式不能影响 dom。

**Comment by 15167103105** [comment]
> 
表达有问题 不是删除dom结点 是有dom结点 但是不显示 且不占空间 目前在下拉列表看到 是占空间了 不能过滤 因为涉及到数据回显和修改

**Comment by yoyo837** [comment]
别再纠结这个了, 占不占用空间不是基于你自行display:none来判断的.

**Comment by PlutoCA** [comment]
同样的问题，想了解一下后续怎么做的 @15167103105

**Comment by linxianxi** [comment]
设置 virtual 为 false 关闭虚拟滚动即可

**Comment by zwmmm** [comment]
同样的问题，最后是怎么解决的？并且还存在所有选项都被隐藏的时候，不能正确展示 nodata

需求其实就是不展示 disabled 的选项，但是还不能影响旧数据的回显

**Comment by linxianxi** [comment]
> 同样的问题，最后是怎么解决的？并且还存在所有选项都被隐藏的时候，不能正确展示 nodata
> 
> 需求其实就是不展示 disabled 的选项，但是还不能影响旧数据的回显

```
<Select
     // 过滤后的选项
    options={filterOptions}
    // 在过滤里的选项里找不到回显值时，使用总量的 options 查文本
    labelRender={({ label, value }) => label ?? options.find((i) => i.value === value)?.label}
/>
```
