### ISSUE TITLE
Breadcrumb 与 react-router结合后，有什么方式控制部分页面不显示面包屑么

### ISSUE THREAD

**Issue by tt-ghost** [ant-design/ant-design#4069]
在网站最外层容器添加Breadcrumb，不知有没有方式通过参数控制部分页面不显示面包屑

**Comment by benjycui** [comment]
Route Component 都会获得 location 之类的属性，判断是需要隐藏 Breadcrumb 的页面的话，用 `null` 替换 Breadcrumb 即可。

**Comment by tt-ghost** [comment]
你是说每个页面单独引入Breadcrumb组件么？这种比较麻烦，还是希望全局引入一次的方式。我的问题在于全局引入的话不太清楚怎么判断，因为路由切换的时候只是子页面在render，全局的这个容器组件没有render

**Comment by benjycui** [comment]
你可以监听 `context.router.listen` 啊。。
