### ISSUE TITLE
DateTimeRangePicker时间预设(presets)能否实现动态更新

### ISSUE THREAD

**Issue by solo-xwz** [ant-design/ant-design#40696]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-oxw76z?file=/index.js)

### Steps to reproduce

DateTimeRangePicker 中 presets设置后无法动态更新时间范围

### What is expected?

非受控模式下每次点击可以实现以点击时间为结束点的时间范围

### What is actually happening?

1. 时间范围结束点总是渲染的时间点，无法动态更新
2. 点击结束时间有可能重复弹出选择面板

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 18.2.0 |
| System | win10 |
| Browser | egde 110.0.1587.41 |

**Comment by Wxh16144** [comment]
我大概理解一下你描述的问题。你是期望预设范围的时间是以当前最新的时分秒填入。其实最好的方式还是你作为一个受控组件，手动 update 时间。

我这里给一个[非受控打开时更新预设时间的例子](https://codesandbox.io/s/datetimerangepickershi-jian-yu-she-presets-shi-xian-dong-tai-geng-xin-vnrkww)，不确定能不能暂时满足你的需求。或者等大佬们看看是否需要加一个 fetaure。
