### ISSUE TITLE
当Select的options属性变化的过程中，出现一次含有重复选项的options，后续options属性变化（不包含该重复选项）会携带该重复选项。

### ISSUE THREAD

**Issue by chenjunkai-ones** [ant-design/ant-design#40699]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-5-2-0-forked-h21fpc?file=/demo.tsx)

### Steps to reproduce

1、传入没有重复选项的options
2、传入带有重复选项的options
3、传入没有重复选项的options
4、打开下拉框

### What is expected?

正常显示3步骤的options

### What is actually happening?

显示3步骤的options，多了2步骤中的重复option

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | React 17/18 |
| System | mac |
| Browser | chrome lastest |

**Comment by zombieJ** [comment]
<img width="743" alt="截屏2023-02-13 11 28 16" src="https://user-images.githubusercontent.com/5378891/218363840-1b0f683f-ffa2-452a-aebf-1afa4e66d989.png">

选项的值是它的 `key`，React 要求 `key` 必须唯一：
https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings

**Comment by chenjunkai-ones** [comment]
> <img alt="截屏2023-02-13 11 28 16" width="743" src="https://user-images.githubusercontent.com/5378891/218363840-1b0f683f-ffa2-452a-aebf-1afa4e66d989.png">
> 
> 选项的值是它的 `key`，React 要求 `key` 必须唯一： https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings
<img width="520" alt="image" src="https://user-images.githubusercontent.com/6036348/218364415-78d890ec-4e1d-4d21-8079-8fae97db9f88.png">
<img width="519" alt="image" src="https://user-images.githubusercontent.com/6036348/218364441-cf7ee426-5a21-4573-876c-4f5d560f66f4.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/6036348/218364469-1f4006b2-a548-4e09-bc61-d956003f6a02.png">
