### ISSUE TITLE
Anchor: scrollTo helper truncating the first char, assumes ID. Error prone and pointless.

### ISSUE THREAD

**Issue by jkoudys** [ant-design/ant-design#4070]
There are several things wrong with the "href" in an `<Anchor.Link>`.

1. It isn't an href, but a selector.
2. Using a selector is very limiting. I propose allowing it to take a `DOMNode`, that way you could easily pass in the results from a `document.querySelector` if you wanted to get the same result. Calling it `target` would make sense since it's the target of the AnchorLink.
3. This is especially bad, because it's both assuming it's an ID selector, and for some reason truncating it: `const targetElement = document.getElementById(href.substring(1));`
4. If your href were '.foobar', but there was a '#foobar' on the page, that's what it would match. This would be a massive pain to debug.
5. It's a pointless waste and added confusion to pass this to a `getElementById`, when you could simply `querySelector`.

https://github.com/ant-design/ant-design/blob/ee2654dbe1a6532f60b146bf6f9f3346299553c8/components/anchor/anchorHelper.tsx#L48

While there are many problems with this approach, taking a 'target' property as a DOMNode solves them all.

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/issues/3844

即然用 getElementById,  href 就必须用ID，，@RaoHai API上标明下呗。。。

**Comment by benjycui** [comment]
How about `Link[target]`? Just like[`Affix[target]`](https://ant.design/components/affix/#components-affix-demo-target).

**Comment by RaoHai** [comment]
in order to solve special selectors, e.g. `<div id="0.12.x-=>-1.0.x" />` in #3844 , we use `getElementById` but `querySelector`.

**Comment by benjycui** [comment]
And `.footer` is unstabled, it must be an ID to make sure that it's unique.

Just update docs now.

**Comment by benjycui** [comment]
@RaoHai 其实我觉得 `#` 还真的没必要。。默认就认定 target 就是 ID 即可，这也是浏览器默认的行为，如 location.hash?

**Comment by afc163** [comment]
@RaoHai Any progress?

**Comment by afc163** [comment]
Anchor.Link only supports node with ID now cause it can be scrolled to by location hash, which non-ID node sepcified via`target` property can not do that. So sorry for that.
