### ISSUE TITLE
建议：<Datepicker /> 在还未点击日时，可以不高亮不？

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#4071]
在操作中，如果修改了『年』或『月』后，最终到达『日』面板时，在还未点击情况下，会有个『日』被高亮，这样会给人误解以为已经选择了『日』，然后点击『确定』或失去焦点时，实际上并没有选中，造成误解。

如下图，如果不联系实际操作，仅根据图片很容易误解已经选中了30号

![image](https://cloud.githubusercontent.com/assets/2840462/20739711/0db71ec6-b6f8-11e6-81f5-d520566911b1.png)

操作动图如下：
![111](https://cloud.githubusercontent.com/assets/2840462/20739921/f93e5a98-b6f9-11e6-9cf5-73bed0349ab7.gif)

**Comment by afc163** [comment]
https://github.com/react-component/calendar/issues/138

**Comment by ystarlongzi** [comment]
『键盘操作的当前日期』是什么意思？
『选中日期』是指用户点击选中的日期，还是像目前这样，在用户未点击时，antd 指定的选中日期？

**Comment by afc163** [comment]
`键盘操作的当前日期` 指使用键盘的『上下左右按键』时，当前操作的日期。
