### ISSUE TITLE
New Timeline Implementation (>5.2.0) Does Not Support Animation/Effect

### ISSUE THREAD

**Issue by lgants** [ant-design/ant-design#40713]
### Reproduction link

[https://codepen.io/lgants/pen/QWVLVmp?editors=0010](https://codepen.io/lgants/pen/QWVLVmp?editors=0010)

### Steps to reproduce

The reproduction utilizes CodePen, which does not seem to like animations. But, the concept/issue seems relatively straight-forward. The QueueAnim component passes refs to children that are utilized for animation enter/exit of the items. The ant Timeline implementation prior to 5.2.0 with Timeline.Item allowed users to manually forward refs. The new implementation, which internally uses the Timeline.Item, does not support ref forwarding. Unless I'm mistaken, implementing React.forwardRef on the TimelineItem component should address the issue (i.e. the contents of each item is already spread through so inclusion of a "ref" in the item dictionary should suffice once forwardRef is implemented). Here's the TimelineItem component: https://github.com/ant-design/ant-design/blob/f7232ebeb53b0eaf677ce938a4b9e046004d89de/components/timeline/TimelineItem.tsx#L27? Thoughts?

### What is expected?

The timeline should forward refs to timeline list items. 

### What is actually happening?

The timeline does not forward refs to timeline list items, which prevents visual effects such as animating enter/exit of items.

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | React 18.2.0 |
| System | 109.0.5414.119 |
| Browser | Chrome |

**Comment by heiyu4585** [comment]
There is no good way to support it, because data-driven is the trend.It is closed now. If you have other ideas, please continue to ask questions,thank you.

**Comment by lgants** [comment]
@heiyu4585 why can't we simply use forwardRef with a new `ref` prop? I never proposed moving away from a data-driven approach. My proposal was to simply forward the ref onto the list item and add `ref` to the data item schema. data-driven and animated UIs are not inconsistent. 🫤

**Comment by lgants** [comment]
Is ant design going to stop letting ppl animate lists? If so, that is very very concerning
