### ISSUE TITLE
Table row selection by custom event

### ISSUE THREAD

**Issue by sarankup** [ant-design/ant-design#40717]
### What problem does this feature solve?

Looking for a AntDesign table row gets selected by custom events. For example, when I onClick a button which not part of table, I need the select the nth row by passing the row id. 

### What does the proposed API look like?

`<Button type="primary" onClick={highlightRowById('abc123')>Color</Button>`
```
const highlightRowById = (rowId) =>
{
???//here is what I want to highlight a particular row by rowId, on a specified table (page has multiple tables in it)
}```

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
Try `rowSelection.selectedRowKeys`.

https://ant.design/components/table#components-table-demo-row-selection-and-operation
