### ISSUE TITLE
DatePicker 和 RangePicker 在使用了 panelRender 后，日期面板关闭行为不一致

### ISSUE THREAD

**Issue by CasoMemory** [ant-design/ant-design#40727]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-burnell-er61f3?file=/src/App.js)

### Steps to reproduce

首先是展开 RangePicker 的面板，点击红色区域，面板不会自动关闭，点击红色区域的按钮会展示警告信息；而展开 DatePicker 的面板后，点击红色区域，面板自动关闭，点击该区域内的 Button，也不会触发其 onClick 事件。

### What is expected?

期望 DatePicker 与 RangePicker 的行为保持一致：

1. 点击红色区域不会自动关闭面板
2. 点击按钮可以触发其 onClick 事件

### What is actually happening?

DatePicker 内的红色区域点击会自动关闭面板；按钮的 onClick 事件不触发

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 18.2.0 |
| System | macOS Ventura Version 13.2 |
| Browser | Chrome Version 109.0.5414.119 (Official Build) (arm64) |

**Comment by zombieJ** [comment]
使用 `panelRender` 后，行为需要自己配合 `open` 进行控制。另外需要注意的是防止原 Picker 事件处理可以在最外层的 div 上加个 stopPop。

**Comment by zombieJ** [comment]
使用 `panelRender` 后，行为需要自己配合 `open` 进行控制。另外需要注意的是防止原 Picker 事件处理可以在最外层的 div 上加个 stopPop。

**Comment by CasoMemory** [comment]
> 使用 `panelRender` 后，行为需要自己配合 `open` 进行控制。另外需要注意的是防止原 Picker 事件处理可以在最外层的 div 上加个 stopPop。

你好，首先感谢及时答复。配合 open 控制这个没问题的，但是我不太理解的是为何 DatePicker 和 RangePicker 的行为不一致？麻烦先看下具体的 demo 么。

**Comment by CasoMemory** [comment]
> 使用 `panelRender` 后，行为需要自己配合 `open` 进行控制。另外需要注意的是防止原 Picker 事件处理可以在最外层的 div 上加个 stopPop。

其次，通过对 document 监听 click 事件，在 DatePicker 日期面板的红色区域点击后，其 event 的 target 是整个 body，而其他区域点击是可以感知到 target 具体是哪个 Dom 节点。同理，RangePicker 日期面板也是符合预期的。

假使真要去 stopPop，这个`最外层的 Div` 是指返回给 panelRender 的 dom 最外层节点么？

**Comment by zombieJ** [comment]
主要是单面板和多面板的处理逻辑不同，单面板纯日期下交互至点击元素后截止，而多面板则是范围选择后截止。因而在处理关闭逻辑上也会有所不同，在不使用 `panelRender` 时，不会感知到这点。但是在自定义后，面板的事件拦截就需要自己来处理。

https://codesandbox.io/s/cranky-dewdney-9n7122?file=/src/App.js

**Comment by CasoMemory** [comment]
> 主要是单面板和多面板的处理逻辑不同，单面板纯日期下交互至点击元素后截止，而多面板则是范围选择后截止。因而在处理关闭逻辑上也会有所不同，在不使用 `panelRender` 时，不会感知到这点。但是在自定义后，面板的事件拦截就需要自己来处理。
> 
> https://codesandbox.io/s/cranky-dewdney-9n7122?file=/src/App.js

已理解，感谢解答，👍
