### ISSUE TITLE
switch valuePropName="checked" is not work 

### ISSUE THREAD

**Issue by zhu-hongwei** [ant-design/ant-design#40724]
### Reproduction link

[https://4x.ant.design/components/form-cn/#components-form-demo-size](https://4x.ant.design/components/form-cn/#components-form-demo-size)

### Steps to reproduce

on the website https://4x.ant.design/components/form-cn/#components-form-demo-size

```
        <Form.Item
          valuePropName="checked"
        >
          <Switch />
        </Form.Item>

```

### What is expected?

this component switch status is on !!!!

### What is actually happening?

but is off

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18 |
| System | macos |
| Browser | chrome |

---
I want to add a picture.

**Comment by zhu-hongwei** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/61079864/218687287-27e67f78-1df5-49a0-b90d-7d13c1de2349.png">

**Comment by zombieJ** [comment]
This demo is only provide style. Not bind field with `name`. Only use `valuePropName` without `name` will not work.

**Comment by zombieJ** [comment]
Here is the Demo. Use `name` for bind field name. `initialValues` help to set the initial value:
https://codesandbox.io/s/biao-dan-chi-cun-antd-4-24-8-forked-uzp347?file=/demo.tsx

**Comment by afc163** [comment]
You need `name` in Form.Item.

**Comment by yoyo837** [comment]
Double shooting! 😄

**Comment by zhu-hongwei** [comment]
thanks you !
