### ISSUE TITLE
旧版本的级联选择控件Cascader如何实现搜索功能

### ISSUE THREAD

**Issue by aNameHere** [ant-design/ant-design#4072]
- antd 版本:1.0.1
- 浏览器及其版本:chrome

由于改用新版本的antd的话,现有页面的所有样式都会收到影响,而 旧版本的Cascader控件又没有实现搜索功能, 请问如何才能让其变成可输入文字的? 或者有什么办法可以单独引用新版本的Cascader控件?

**Comment by afc163** [comment]
不太可能做到，只能尝试升级。

**Comment by afc163** [comment]
或者单独引用 http://github.com/react-component/cascader/

**Comment by benjycui** [comment]
搜索是在 antd 这一层做的，只能升级。

**Comment by benjycui** [comment]
Try https://github.com/ant-design/antd-codemod

可以减少点工作量。
