### ISSUE TITLE
Image图片，不点击预览，就能看到操作按钮组（缩放，旋转等），并能操作图片

### ISSUE THREAD

**Issue by yoghurtxu** [ant-design/ant-design#40721]
### What problem does this feature solve?

减少用户操作路径

### What does the proposed API look like?

期望效果：不点击图片就能看到操作按钮。

**Comment by afc163** [comment]
> 期望效果：https://arco.design/react/components/image 挂载节点的示例

这个例子也是要点击图片的。

**Comment by yoghurtxu** [comment]
期望效果：不点击图片就能看到操作按钮。
目前看了市面上的组件库都得点击之后才能看到操作按钮组（缩放，旋转等）

**Comment by afc163** [comment]
这个可能要自行实现了，目前内建功能只限于预览的时候。
