### ISSUE TITLE
v4 升级到 v5 导致一些 Popover 或者 Select 样式发生了变化

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/ant-design#40736]
### Reproduction link

[https://ant.design/components/select-cn](https://ant.design/components/select-cn)

### Steps to reproduce

<img width="566" alt="9CAA44F8-631E-49F1-AF74-C87C18EA272F" src="https://user-images.githubusercontent.com/49217418/218979840-94ee11f4-683e-4818-b72b-2d75708f6b2f.png">

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/49217418/218981532-19a6a987-a7b7-4714-ad8b-16271545b2b1.png">

### What is expected?

dom 层级结构和 v4 保持一致

### What is actually happening?

Popover 的 content 内容多了一层包裹，Select 使用了自定义 dropdownRender 的时候，也会出现同样的情况，目前看到是因为 v4 中`ant-popover-inner-content` 的 `padding` 属性在 v5 中移到 `ant-popover-inner` 里面去了，但是项目中用到了比较多的 Popover 或者 Select，所以想问问有没有比较通用的解法？
 
| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2.0 |
| System | mac |
| Browser | Chrome |

**Comment by afc163** [comment]
原来代码怎么写的？

**Comment by li-jia-nan** [comment]
```tsx
<Popover
  placement="right"
  overlayClassName="noArrow"
  trigger={['click']}
  content={<ActionOverlay className="w-44" />}
  title=""
>
  <div className="dropdown-item px-3">
    <ArrowDownSquareOutlined />
    在下方添加操作
  </div>
</Popover>
```

代码没变，就是升级了 ant 版本

**Comment by afc163** [comment]
ActionOverlay 怎么实现的？

**Comment by afc163** [comment]
来个 codesandbox 看看吧

**Comment by li-jia-nan** [comment]
codesandbox 里面好像又没问题，先close了
