### ISSUE TITLE
InputNumber precision为0时，onChange输出错误的值

### ISSUE THREAD

**Issue by cloudZQY** [ant-design/ant-design#40733]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-5jf1f0)

### Steps to reproduce

InputNumber组件中，输入任意两个小数点的字符，如1.55.55，组件显示2，而表单实际的值为1.55

### What is expected?

显示和onChange的值一致且正确

### What is actually happening?

InputNumber组件显示和实际的值不一致

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 16.14.0 |
| System | macos |
| Browser | chrome |

**Comment by cloudZQY** [comment]
![未命名](https://user-images.githubusercontent.com/16647306/218950239-d3389c06-c4c0-4bc8-ac81-8c3ca8ae85b2.gif)

**Comment by Sunny-117** [comment]
我试了下，是antd内部用到的rc-input-number的bug

**Comment by Sunny-117** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/73089592/218978566-2e10994c-a849-4e78-a174-5d45808e4317.png">
fu'xian复现了

**Comment by Sunny-117** [comment]
1.55.55 是按照合法数字来处理吗？@MadCcc

**Comment by Sunny-117** [comment]
https://github.com/react-component/input-number/pull/540
