### ISSUE TITLE
anchor 使用動態 items 會產生問題

### ISSUE THREAD

**Issue by frankA10019** [ant-design/ant-design#40730]
### Reproduction link

[https://youtu.be/Hssq9pySchU](https://youtu.be/Hssq9pySchU)

### Steps to reproduce

1. 點擊Anchor锚点頁 隐藏调试专用演示
2. 滑動內容

### What is expected?

正常對應到anchor item

### What is actually happening?

anchor顯示會卡住

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2.0 |
| System | mac |
| Browser | Chrome 108.0.5359.124 |

---
看起來是容器內容高度改變時沒有重新計算錨點高度
我是使用react-hook-form內的field array動態產生anchor items和container內容

[https://legacy.react-hook-form.com/api/usefieldarray](https://legacy.react-hook-form.com/api/usefieldarray)

list 1
list 2
list 3
  child item 1  
  child item 2 <-- 動態新增 item3
list 4
list 5
list 6

測試結果為如果新增內容時 該父項(list 3)為高亮時，新增後正常
若此時高亮為其他項目(list 2)時 新增內容後anchor會卡住。

**Comment by MadCcc** [comment]
文档站问题

**Comment by frankA10019** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-f31wcy?file=/index.js

@MadCcc 您好 為了使您更加了解這個問題
我做了一個codesandbox 專案來重現

等待子項出現後
可以看到滑到紫色區塊時 Anchor並未顯示正確的範圍
但點擊anchor內的紫色區塊按鈕還是會滑到相對應區塊
再請協助確認
謝謝
