### ISSUE TITLE
Default french locale for tour component is missing

### ISSUE THREAD

**Issue by nlapointe-swood** [ant-design/ant-design#40747]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/locale/fr_FR.ts](https://github.com/ant-design/ant-design/blob/master/components/locale/fr_FR.ts)

### Steps to reproduce

Tour is missing in fr_FR.ts. You can compare with en-US that is ok: https://github.com/ant-design/ant-design/blob/master/components/locale/en_US.ts

### What is expected?

Default french locale

### What is actually happening?

No default (so no translation)

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by RedJue** [comment]
I'll handle it
