### ISSUE TITLE
docs [Modal] :  `closable` default value error

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#40749]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qixkqr?file=/demo.tsx)

### Steps to reproduce

Use minimum function

### What is expected?

Do not display the close button

### What is actually happening?

Show close button

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome  108.0.5359.125 |

**Comment by RSS1102** [comment]
docs:
![image](https://user-images.githubusercontent.com/81673017/219251174-d4aedf67-4a2f-4b8f-a6aa-5f18f5ee2ff9.png)
codesandbox:
![image](https://user-images.githubusercontent.com/81673017/219251240-90e6c428-5130-4aad-9793-d7998898d6ac.png)
code:
![image](https://user-images.githubusercontent.com/81673017/219251403-f8d9b40b-a987-4e72-a67a-846c8daf2e28.png)

**Comment by afc163** [comment]
This is params document of `Modal.confirm`, not `<Modal />`. https://ant.design/components/modal-cn#components-modal-demo-confirm

<img width="1229" alt="图片" src="https://user-images.githubusercontent.com/507615/219252250-8e015153-6d8c-465f-be1f-6b5ca9ba91a9.png">

<img width="1018" alt="图片" src="https://user-images.githubusercontent.com/507615/219252306-5b83979a-aa3c-4eb0-ab4f-08245c451ecf.png">
