### ISSUE TITLE
建议：datepicker支持value传递时间字符串

### ISSUE THREAD

**Issue by cnchanning** [ant-design/ant-design#4074]
昨天把项目中依赖antd从1.x升级为2.5，时间相关的组件都无法使用，经排查发现2.x版本的时间组件默认的value传参为moment实例。

目前来看使用上有些不大友好：
1.  传递时间字符串进去会报错 value.format is not a function (错误提示不大友好)
2.  给组件传参之前还需要对取得的时间值使用moment做一次包装，既然组件内部已经依赖了moment，为什么还需要使用时再继续包装一次，毕竟前后通信是值传递，可能我使用场景不多，没有理解到为何这样设计

建议改进：
1.  对value进行合法性检测，并给出友好的错误提示
2. 兼容 value 的传值为 moment || string ，传递string时组件内部做一次包装

建议如果能通过的话，我晚点提个PR

**Comment by benjycui** [comment]
现在时区和部分 locale 都是从 value 里面读取，用字符串的话内部需要处理得比较多。

**Comment by benjycui** [comment]
其实配合 `Form.create` 使用时，只需要在提交时统一处理就好。

**Comment by cnchanning** [comment]
好的，了解

**Comment by muzidx** [comment]
请问如何结合getFieldDecorator提交和获取正确的日期值呢？我看了文档说2.xx版本将时间string变成了moment对象，不知如何通过form.create时将datepicker的字段转成需要的moment对象形式？
现在在更新修改字段的时候，时间日期的字段带不回来，在空间上没显示

```
class ActivityForm extends Component {
render () {
    const { getFieldDecorator } = this.props.form
    const 'end_time' =    //   是应该在这里转吗？然后下面获取的时候就直接转成moment对象了？

    return (
        <Form horizontal onSubmit={ this.submit.bind(this) }>
           <Col span='5'>
            <FormItem label="结束时间">
              {getFieldDecorator('end_time', {
                'rules': [{ type: 'object', required: true }]
              })(
                <DatePicker placeholder="选择结束时间" 
                            format='YYYY-MM-DD'
                            disabledDate={ disabledDate } />
              )}
            </FormItem>
          </Col>
        </Form>
    )
}
}

export default Form.create({
    'mapPropsToFields': (props) => {
        return formTranslate(props.date)  // 还是在props.data里获取时间的那个字段转换呀？
    }
})(ActivityForm)
```

**Comment by benjycui** [comment]
@muzidx https://ant.design/components/form/#components-form-demo-time-related-controls

**Comment by hansnow** [comment]
@benjycui 
这是不是意味着，文档中提到的
> options.getValueFromEvent: 可以把 onChange 的参数转化为控件的值，例如 DatePicker 可设为：(date, dateString) => dateString
已经不再适用了呢？如果是的话建议删除此段并加上一些参考链接

**Comment by benjycui** [comment]
@hansnow 👍

**Comment by afc163** [comment]
@hansnow 来个 PR 吧~

**Comment by benjycui** [comment]
昨天更新了。。 https://github.com/ant-design/ant-design/commit/5fd3baaff0cd61cfdfc87c1e41af2f18e35699b0
