### ISSUE TITLE
Input在禁用状态下，显示字体超长是否可以...显示

### ISSUE THREAD

**Issue by xiaolifeipiao** [ant-design/ant-design#40756]
### What problem does this feature solve?

解决Input禁用下显示问题

### What does the proposed API look like?

扩展一个支持配置的属性

![image](https://user-images.githubusercontent.com/42238961/219303322-37f4af37-9a8c-478f-88de-d7ca39e458e3.png)

**Comment by Yuiai01** [comment]
是否可以使用限定父元素宽度达到省略文字的效果？如下图：
<img width="512" alt="image" src="https://user-images.githubusercontent.com/112228030/219334412-4df04f25-076a-4ac7-9b69-44bd816e21f2.png">
