### ISSUE TITLE
Add "maxTagTextLength" for TreeSelect for consistency.

### ISSUE THREAD

**Issue by Becavalier** [ant-design/ant-design#40755]
### What problem does this feature solve?

Add "maxTagTextLength" attribute for the TreeSelect component for consistency.

### What does the proposed API look like?

Similar to the same API designed for Select.

**Comment by MuxinFeng** [comment]
目前是支持的哈，可以看下这里 https://codesandbox.io/s/ke-gou-xuan-antd-5-2-1-forked-d3279o

我补充下 api 文档吧
