### ISSUE TITLE
[Bug] [Table] 设置 columns 中 onHeaderCell 返回的 colSpan 不生效

### ISSUE THREAD

**Issue by youngBrain1893** [ant-design/ant-design#40753]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-tou-fen-zu-antd-4-24-5-forked-6r80pu?file=/demo.tsx)

### Steps to reproduce

查看 Table Header 渲染结果
关注表头 Other -> Address -> Block -> 【Building | Door No.】展示

### What is expected?

Table Header 渲染结果中
Other -> Address -> Block 下仅展示 colSpan 为 2 的 Building 列头
Why:
  - Building 列通过 onHeaderCell 执行返回 { colSpan: 2 }（合并）
  - Door No. 列通过 onHeaderCell 执行返回 { colSpan: 0 }（隐藏）

<table>
  <thead>
	  <tr>
	    <th colSpan=3>Other</th>
	  </tr>
	  <tr>
	    <th rowSpan=3>Age</age>
	    <th colSpan=3>Address</td>
	  </tr>
	  <tr>
	     <th colSpan=2>Block</th>
	  </tr>
	  <tr>
             
	     <th style="color: red" colSpan=2>Building</th>
	  </tr>
  <thead>
  <tbody>
	  <tr>
		  <td>Lake Park</td>
		  <td>C</td>
		  <td>2035</td>
	  </tr>
  <tbody>
</table>

### What is actually happening?

<table>
  <thead>
	  <tr>
	    <th colSpan=3>Other</th>
	  </tr>
	  <tr>
	    <th rowSpan=3>Age</age>
	    <th colSpan=3>Address</td>
	  </tr>
	  <tr>
	     <th colSpan=2>Block</th>
	  </tr>
          
	  <tr>
	     <th style="color: red">Building</th>
	     <th style="color: red">Door No.</th>
	  </tr>
  <thead>
  <tbody>
	  <tr>
		  <td>Lake Park</td>
		  <td>C</td>
		  <td>2035</td>
	  </tr>
  <tbody>
</table>

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 18.2.0 |
| System | macOS Monterey  12.5.1 (21G83) |
| Browser | Microsoft Edge 版本 110.0.1587.41 (正式版本) (x86_64)   <br/>  UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41 |

---
RC 相关代码：
1. HeaderCell 渲染 `...cell` 和 `additionProps` 设置值 [rc-table src/Header/HeaderRow.tsx](https://github.com/react-component/table/blob/master/src/Header/HeaderRow.tsx#L75)
2. Cell 渲染 `colSpan` 取值逻辑 [rc-table src/Cell/index.tsx](https://github.com/react-component/table/blob/master/src/Cell/index.tsx#L151)
  此处 onHeaderCell 返回值(additionProps) 中 colSpan 优先级最低

**Comment by afc163** [comment]
onHeaderCell => onCell

**Comment by youngBrain1893** [comment]
> onHeaderCell 改成 onCell 即可。

<table>
    <thead>
        <tr>
            <th colspan=3>
                Other
            </th>
        </tr>
        <tr>
            <td rowspan=3>Age</td>
            <td colspan=2>Address</td>
        </tr>
        <tr>
            <td colspan=2>Block</td>
        </tr>
        <tr>
            <td>Building</td>
            <td>Door No.</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Lake Park</td>
            <td colspan=2>C</td>
        </tr>
    </tbody>
</table>


Thanks for reply, 尝试了 onHeaderCell 调整为 onCell，渲染如上：
设置作用在 tbody 上（保留 Door No. 表头，渲染丢失 Door No. 列），期望结果为 thead 的合并，tbody 正常按照 colspan 1 的方式渲染 Door No. 列

**Comment by zombieJ** [comment]
Header 的组合是自动的，不接受自定义 span。

**Comment by youngBrain1893** [comment]
> Header 的组合是自动的，不接受自定义 span。

看到改动已经 merge 预计会在那个版本 release 出来呢

**Comment by zombieJ** [comment]
minor 版本
