### ISSUE TITLE
waring:the children of `Select` should be `Select.Option` or `Select.OptGroup`, instead of `Option`.

### ISSUE THREAD

**Issue by jinxin479** [ant-design/ant-design#4075]
#### 发生问题的环境是：

- antd 版本:2.4.3
- 操作系统及其版本:win7
- 浏览器及其版本:chrome,firefox

#### 您做了什么？请提供尽可能详细的重现步骤。
引入了antd的Select
出现警告，改为Select.Option还是同样的警告

#### 您期待的结果是:

像官网一样正常显示 

#### 实际上的结果是:

控制台出现警告：
waring:the children of `Select` should be `Select.Option` or `Select.OptGroup`, instead of `Option`.

**Comment by yesmeck** [comment]
Select 的里面只能嵌套  Select.Option 和 Select.OptGroup。

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
可能是这个问题：https://github.com/ant-design/ant-design/issues/3550

**Comment by jinxin479** [comment]
谢谢大家的回答，我想把这个问题再说的清楚一些，我的代码如下。实在不知道为什么，改过来改过去都出现警告
<FormItem
              {...formItemLayout}
              label="国籍：">
				  {getFieldDecorator("select",{
			    rules: [
			        { required: true, message: '请选择您的国籍' }
				],
			})(
				<Select  placeholder="请选择国家" style={{ width: '100%' }}>
	              <Select.Option value="china">中国</Select.Option>
	              <Select.Option value="use">美国</Select.Option>
	              <Select.Option value="japan">日本</Select.Option>
	              <Select.Option value="korean">韩国</Select.Option>
	              <Select.Option value="Thailand">泰国</Select.Option>
	            </Select>
			)}

          </FormItem>

**Comment by jinxin479** [comment]
不好意思，我的antd 版本是2.5.0
现在在codepen上无法复现，。完全正常。同样的代码在本地就会出现警告

const { DatePicker,Form,Select } = antd;
const FormItem = Form.Item;
const Option = Select.Option;
const Demo = React.createClass({
  render(){
    return(
      <FormItem>     
  <Select  placeholder="请选择国家" style={{ width: '100%' }}>
    <Option value="china">中国</Option>
    <Option value="use">美国</Option>
    <Option value="japan">日本</Option>
    <Option value="korean">韩国</Option>
    <Option value="Thailand">泰国</Option>
  </Select>

   </FormItem>
    )
  }
})
ReactDOM.render(<Demo />, document.getElementById('container'));

**Comment by yesmeck** [comment]
@jinxin479 帮你格式化了下代码，请学习下 markdown。

**Comment by yesmeck** [comment]
@jinxin479 是不是有用 `react-hot-loader`？

**Comment by jinxin479** [comment]
@yesmeck 
好的，谢谢。不好意思，我直接粘上来了。哈哈。
我有用react-hot-loader 版本是3.0.0-beta.6。
和这个有关系么

**Comment by yesmeck** [comment]
见 #3550

**Comment by jinxin479** [comment]
@yesmeck  万分感谢！！，没好好看 #3550，有点浪费你的感情了
