### ISSUE TITLE
官网V5版本中，“使用自定义日期库”文档中，代码没有更新为dayjs

### ISSUE THREAD

**Issue by ALvinCode** [ant-design/ant-design#40752]
### Reproduction link

[https://ant.design/docs/react/use-custom-date-library-cn](https://ant.design/docs/react/use-custom-date-library-cn)

### Steps to reproduce

打开 https://ant.design/docs/react/use-custom-date-library-cn 即可见

### What is expected?

推荐使用dayjs，文档案例中更新为dayjs集成用法

### What is actually happening?

v5版本文档中仍为momentjs集成代码

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18 |
| System | mac os |
| Browser | chrome 110.0.5481.100 |

**Comment by li-jia-nan** [comment]
这个文档不就是教用户怎么用自定义库吗，所以用 momentjs 举例

**Comment by zombieJ** [comment]
> Ant Design 默认使用 [Day.js](https://day.js.org/) 来处理时间日期问题。Day.js 相比于 [moment](http://momentjs.com/) 使用了不可变数据结构，性能更快，体积仅 2KB，API 设计完全一致。你可以很方便的改用其他自定义日期库如（moment、[date-fns](https://date-fns.org/)）。在这里我们提供了两种方式来实现替换:

这个文档就是教用户替换成其他日期库的教程，没有写错哈~

**Comment by yoyo837** [comment]
相对于使用dayjs, 非dayjs的就是“其他”或叫“自定义”了.
