### ISSUE TITLE
button的loading没有delay的效果

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#40751]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-putmi7?file=/index.js)

### Steps to reproduce

想让一个按钮延迟loading 但是不生效

### What is expected?

应该是延迟的loading

### What is actually happening?

直接loading了

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18 |
| System | mac |
| Browser | google |

---
ts的类型不一致。
在prps中定义的 loading为 loading?: boolean | { delay?: number } 当需要延迟的时候应该是 {delay:2000} 这是一个对象
但是在内部的state状态的时候  Loading的类型为  type Loading = number | boolean; 
const [innerLoading, setLoading] = React.useState<Loading>(!!loading); 这样loading就是默认为true了 
没有延迟 delay的效果

**Comment by RedJue** [comment]
我看看这个问题
