### ISSUE TITLE
多个表单组件未添加readOnly属性

### ISSUE THREAD

**Issue by CaptainJon** [ant-design/ant-design#40767]
### What problem does this feature solve?

目前给Select、Radio、Checkbox、Switch等表单组件添加readOnly属性会提示TS类型警告，但readOnly属性是实实在在添加到了dom上。因为不想用disabled，readOnly和disabled还是有区别的，因此希望官方能添加上这个TS类型，或者有什么办法可以在项目中临时解决这个问题？使用的Antd版本4.x。另外DatePicker相关的时间组件和Upload组件添加readOnly无效，dom上无添加。

### What does the proposed API look like?

既然readOnly有添加到dom上，应该要添加对应的TS类型

**Comment by MadCcc** [comment]
`readonly` 暂时没有计划全部支持，可以使用受控属性强制不可修改
