### ISSUE TITLE
oceanbase.com 404

### ISSUE THREAD

**Issue by ram1lk** [ant-design/ant-design#40764]
### Bug?

https://ant.design/docs/spec/cases/%5Bhttp://oceanbase.alipay.com%5D(https://www.oceanbase.com/docs/enterprise/oceanbase-ocp-cn/V3.3.3/10000000000636101)

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | . |
| System | . |
| Browser | website error 404 |

---
https://ant.design/docs/spec/cases/%5Bhttp://oceanbase.alipay.com%5D(https://www.oceanbase.com/docs/enterprise/oceanbase-ocp-cn/V3.3.3/10000000000636101)

**Comment by Yuiai01** [comment]
I'll fix it.

**Comment by ram1lk** [comment]
Can I join the ranks of contributors for finding this bug?
