### ISSUE TITLE
Form表单隐藏域或者说不要删除掉fieldsvalue中的非Form.Item的值

### ISSUE THREAD

**Issue by baicoding** [ant-design/ant-design#40760]
### What problem does this feature solve?

场景1：系统中用户很多，放在form表单中的时候，用户用select去选择不太友好，这个时候，我用Input框加个图标去弹出一个用户查询的界面去选择用户，返回一个用户ID和用户姓名，使用setFieldsValue进行了赋值，用户姓名直接在form表单中进行了显示，用户ID并不显示，form表单提交时，用户ID会丢失掉。这样就很麻烦，必须在form外进行记录用户的ID
场景2：最常见的修改数据的情况，被修改的数据的id，丢失后，在提交form数据的时候不得不再去找回再拼接回去

### What does the proposed API look like?

setFieldsValue赋值的，即使不在UI上显示，在提交表单的时候也不要丢失。

**Comment by luo3house** [comment]
我觉得这应该有意为之。你可以使用隐藏的 `<Form.Item hidden />` 存储表单的一些内部数据。
HTML 原生表单也有 `<input type="hidden" />` 的相似功能，保持表单完整的同时，避开它与用户交互。
