### ISSUE TITLE
Menu是否能提供更细化的回调或者提供 renderItem

### ISSUE THREAD

**Issue by kaneaaa** [ant-design/ant-design#40777]
### What problem does this feature solve?

我的需求：
1.点击SubMenu菜单展开菜单并选中第一个菜单（现在SubMenu菜单在label上添加a标签点击范围太小）
2.点击展开图标不触发a标签跳转只控制菜单展开和收起

### What does the proposed API look like?

希望能提供上面需求的api，或者提供Rander方法

**Comment by MadCcc** [comment]
你期待的 API 是什么样的？
