### ISSUE TITLE
Modal.confirm里content使用Paragraph展开文字汉化失败

### ISSUE THREAD

**Issue by yaya1286249672** [ant-design/ant-design#40776]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/guo-ji-hua-antd-4-24-8-forked-7mhsvt?file=/demo.tsx)

### Steps to reproduce

点击confirm
Modal.confirm content里使用<Paragraph> 组件展开文字汉化失败

### What is expected?

汉化成功

### What is actually happening?

展示Expand不显示展开

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | react |
| System | windows10 |
| Browser | 107.0.5304.122 |

**Comment by MuxinFeng** [comment]
没复现出来，我怀疑 codeSandbox 的默认环境是 en，但是改了 ConfigProvider 里的 locale 配置还没生效，麻烦大佬看看呢 https://codesandbox.io/s/guo-ji-hua-antd-4-24-8-forked-dqdfkx?file=/demo.tsx:2445-2459

**Comment by yaya1286249672** [comment]
我自己本地项目也已经本地化了  在modal里使用Paragraph组件“展开”是正常汉化的  但是Modal.confirm就不行

还有codeSandbox 的默认环境是zh吧  它的按钮都是中文的

**Comment by luo3house** [comment]
`Modal.confirm` 是动态挂载，所在上下文和 `<Modal />` 不同，画出来的组件没有 ConfigProvider，要给 content 再封一层 ConfigProvider

```jsx
Modal.confirm({ content: <ConfigProvider locale={zhCN}><Paragraph /></ConfigProvider> })
```

或者仅局限这个 Paragraph
```jsx
Modal.confirm({ content: <Paragraph ellipsis={{ symbol: "展开", ... }} /> })
```

**Comment by yaya1286249672** [comment]
解决了 谢谢大佬

**Comment by yoyo837** [comment]
Duplicate of #40646
