### ISSUE TITLE
为何button shape 保留circle-outline

### ISSUE THREAD

**Issue by limerickgds** [ant-design/ant-design#4077]
outline的形式不是应该由 type来决定button展示样式  shape 根据语义就应该只影响它的形状。
暂时看设置为cricle 和cricle-outline也没有区别（可能我没认真看）

**Comment by benjycui** [comment]
May bad... https://github.com/ant-design/ant-design/issues/306#issuecomment-142480858

现在看来 `circle-outline` 是可以废弃的。。

**Comment by benjycui** [comment]
隐藏这个属性，基本没代码量，就不废弃了。
