### ISSUE TITLE
自定义表格row 拿不到row index

### ISSUE THREAD

**Issue by rxdrag** [ant-design/ant-design#40788]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-antd-5-2-0-forked-iwg6b9?file=/demo.tsx)

### Steps to reproduce

直接运行，看console log 打印数据

### What is expected?

期望打印真实的row index

### What is actually happening?

undefined

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react 18 |
| System | win11 |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/18096128/219854492-5620adb4-d4b6-4eb2-9fb2-973a9f8fae3e.png)
![image](https://user-images.githubusercontent.com/18096128/219854514-75990812-c8e1-4f1c-8e3c-4cb8a8e51f56.png)

**Comment by afc163** [comment]
Try onRow

https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-antd-5-2-0-forked-qrzsx9?file=/demo.tsx:4916-4958
