### ISSUE TITLE
The height of the cards are not the same in the list

### ISSUE THREAD

**Issue by kafkahw** [ant-design/ant-design#40786]
### Reproduction link

[https://stackblitz.com/edit/react-wf9wmw?file=demo.tsx](https://stackblitz.com/edit/react-wf9wmw?file=demo.tsx)

### Steps to reproduce

1. follow the link to minimal reproduction (https://stackblitz.com/edit/react-wf9wmw?file=demo.tsx)
2. resize the window so the content of the cards will take multiple lines
3. the content of the second card is longer than others and may take an extra line. In that case, the height of the second card is noticeably higher than the rest cards'.

### What is expected?

The height of the cards should be visually the same.
Or there should be one `prop` provided for consumers to opt in to make all cards' height the same.

### What is actually happening?

The height of the second card is noticeably higher than the rest cards'.

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2.0 |
| System | Mac OS 11.7.1 |
| Browser | Chrome  109.0.5414.119 |

**Comment by RiteshMakan** [comment]
I had a similar situation when using the cards in a list. Because the content was not in the same size I used the `ellipses` from Typography to build  "show more" Component. This way you can control that if the content is larger then you can have a "...more" link that will expand the container.

Hope this helps

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/82932397/219936348-a998c80c-2778-47cd-808f-b8ce89eb9c92.png">

```
import React, { useState } from 'react';
import { Typography } from '../../../index';

const { Paragraph } = Typography;

interface ShowMoreProps {
  textArray: [];
  expandTextDisplay?: string;
}

const ShowMore = ({ textArray, expandTextDisplay = 'more' }: ShowMoreProps) => {
  const [isCollapsed, setIsCollapsed] = useState(true);

  const expandText = () => {
    setIsCollapsed(!isCollapsed);
  };

  return (
    <div className="cc-show-more">
      {textArray.map((paragraph, i) => {
        if (i === 0) {
          return (
            <Paragraph
              key={i}
              ellipsis={
                textArray.length >= 1
                  ? {
                      rows: 2,
                      expandable: true,
                      symbol: expandTextDisplay,
                      onExpand: expandText,
                    }
                  : false
              }
            >
              {paragraph}
              {textArray.length >= 1 && isCollapsed && (
                <>
                  <span aria-hidden="true">...</span>
                  <a
                    href="#/"
                    className="ant-typography-expand"
                    aria-label="Expand"
                    onClick={expandText}
                  >
                    more
                  </a>
                </>
              )}
            </Paragraph>
          );
        }
        return (
          <Paragraph className={`${isCollapsed && 'hidden'}`} key={i}>
            {paragraph}
          </Paragraph>
        );
      })}
    </div>
  );
};

export default ShowMore;
```

**Comment by afc163** [comment]
Height of List.Item will depend on the content of it, not it's parent. It is intentional.

**Comment by kafkahw** [comment]
@afc163 I understand that's how it works now, but this is more like a feature request. It's very common for consumers to expect the same height cards (regardless of the height of content) in a list since it's aesthetically much better. As a component library, we should probably provide the options for consumers to choose different styles.

Can you please re-open the issue or point me a place where I can create a feature request?

**Comment by afc163** [comment]
PR welcome~

**Comment by kafkahw** [comment]
I'll take a look at it when I get a chance. For the time being, a simple workaround could be to just append "\u00A0" to the short content so that it will take the same number of lines as those having lengthy content.

**Comment by RedJue** [comment]
This is a simple style problem, here is a [link](https://stackblitz.com/edit/react-wf9wmw-2i6mck?file=index.css,demo.tsx) to the solution, I hope it will help you.

**Comment by kafkahw** [comment]
> This is a simple style problem, here is a [link](https://stackblitz.com/edit/react-wf9wmw-2i6mck?file=index.css,demo.tsx) to the solution, I hope it will help you.

@RedJue this is awesome! thanks a lot!
