### ISSUE TITLE
Filter submenu is rendered outside the target container when used with ConfigProvider

### ISSUE THREAD

**Issue by MehmetYararVX** [ant-design/ant-design#40781]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/filter-search-antd-4-24-8-forked-t5xse4)

### Steps to reproduce

1. Load the sandbox
2. Click the filter button in the "Name" column
3. Hover over the "Submenu"
4. Inspect the first item in the menu

### What is expected?

The submenu is rendered within the target container.

### What is actually happening?

The submenu is rendered outside the target container (attached to the body instead of the target container).

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 18 |
| System | MacOS Ventura 13.2 |
| Browser | All |

---
The submenu is rendered correctly within the container for simple dropdowns. Please see https://codesandbox.io/s/cascading-menu-antd-4-24-8-forked-zeyndq.

Ref: UIEN-3286

**Comment by RedJue** [comment]
Let me try
