### ISSUE TITLE
[Tooltip] [Table] Cannot set properties of undefined (setting 'hook')

### ISSUE THREAD

**Issue by rivaslive** [ant-design/ant-design#40784]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/error-hover-tooltip-nextjs-and-antd-m66gbv?file=%2Fpages%2Findex.js&selection=%5B%7B%22endColumn%22%3A3%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A3%2C%22startLineNumber%22%3A11%7D%5D)

<img width="566" alt="image" src="https://user-images.githubusercontent.com/39039038/219781194-5fbb3a16-7cd9-4439-b5e8-5ff73893d1b0.png">

### Steps to reproduce

* Create Nextjs Project with version 13.x
* Use Tooltip and see browser console

### What is expected?

Not print console logs with error "Cannot set properties of undefined (setting 'hook')"

### What is actually happening?

Console error when you mouse over tooltip

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.x |
| System | MacOS |
| Browser | lasted |

---
Happens in Tooltip and Table,, but happened in other components

**Comment by afc163** [comment]
<img width="1787" alt="图片" src="https://user-images.githubusercontent.com/507615/219935963-2f6d7d17-41bc-48dc-8f38-10c2eb1fd414.png">

I can't reproduce in your codesandbox link.

**Comment by rivaslive** [comment]
> <img alt="图片" width="1787" src="https://user-images.githubusercontent.com/507615/219935963-2f6d7d17-41bc-48dc-8f38-10c2eb1fd414.png">
> 
> I can't reproduce in your codesandbox link.

Sorry, I leave you the correct instruction to replicate

1. Open in new tab 
2. Open Console in browser
3. Hover in button and click
4. Hover again

Add Link vide to reproduce
https://drive.google.com/file/d/1fcUjY79qEeA2Sgezi8on05kUHDP3UBv1/view?usp=sharing

**Comment by afc163** [comment]
Cannot reproduce it. https://m66gbv-3000.preview.csb.app/

<img width="1785" alt="图片" src="https://user-images.githubusercontent.com/507615/220806088-14271ab7-48b0-47b7-8684-9934eb831a0a.png">

Could you try it in incognito window?

**Comment by rivaslive** [comment]
> Cannot reproduce it. https://m66gbv-3000.preview.csb.app/
> 
> <img alt="图片" width="1785" src="https://user-images.githubusercontent.com/507615/220806088-14271ab7-48b0-47b7-8684-9934eb831a0a.png">
> 
> Could you try it in incognito window?

Incognito seems unable to replicate

**Comment by rivaslive** [comment]
@afc163 This was closed not knowing if it could be replicated? The message is really annoying

**Comment by afc163** [comment]
I believe it was introduced by one of your chrome extension, not antd.

**Comment by rivaslive** [comment]
> I believe it was introduced by one of your chrome extension, not antd.

Thanks!

**Comment by 2239058652** [comment]
![image](https://github.com/ant-design/ant-design/assets/85220715/270a2791-662f-4900-ac8e-7dc749fdc70d)
just when i use googlechrom it will like this and open your React Developer Tools,i dont know why
