### ISSUE TITLE
Cascader search results selects by the last value path

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#40782]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-2-1-forked-gxrtwj?file=/demo.tsx)

### Steps to reproduce

Search `a` in the Cascader and press keyboard's down arrow to navigate found options

### What is expected?

To navigate search results

### What is actually happening?

All children options with the same last value in path are selected at once

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18 |
| System | windows |
| Browser | Firefox, Chrome |

**Comment by kiner-tang** [comment]
It seem that caused by the same value.let me try to fix this problem
