### ISSUE TITLE
3.x 版本的跳转链接可以改么

### ISSUE THREAD

**Issue by Wxw-Gu** [ant-design/ant-design#40798]
### Reproduction link

[https://3x.ant.design/index-cn](https://3x.ant.design/index-cn)

### Steps to reproduce

右上角切换4.x版本 实际跳转到5.x版本

### What is expected?

跳转到 https://4x.ant.design/

### What is actually happening?

跳转到 https://ant.design/

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.5.2 |
| System | 22000.258 |
| Browser | 98.0.4758.80 |

---
https://github.com/ant-design/ant-design/pull/40787

**Comment by li-jia-nan** [comment]
来个pr

**Comment by zombieJ** [comment]
= =，感觉旧版本不应该指向新版本，否则每次加 major，老的全部都要改。

**Comment by Wxw-Gu** [comment]
> ==，感觉旧版本不应该指向新版本，否则每次加专业，老的全部都要改。

是这样的，3.x官网  4.x和链接需要改一个

**Comment by afc163** [comment]
老版本网站不会再部署了。
