### ISSUE TITLE
[Upload]上传文件组件会自动把文件名带有的斜线“/”转换为冒号“:”

### ISSUE THREAD

**Issue by wjf40390** [ant-design/ant-design#40819]
### Reproduction link

[https://codepen.io/pen?&editors=001&prefill_data_id=9b45b668-8e91-44f4-96d8-17089ad64ad7](https://codepen.io/pen?&editors=001&prefill_data_id=9b45b668-8e91-44f4-96d8-17089ad64ad7)

### Steps to reproduce

1.选择一个名字中带有斜线的文件（可以手动修改文件名进行测试）；
2.在Upload组件官方demo中上传该文件（https://ant.design/components/upload-cn）；
3.会发现上传结果的文件名里的斜线“/”被转换为冒号“:”。

### What is expected?

上传文件的文件名显示原始文件名称，不进行转换

### What is actually happening?

上传文件的文件名会自动把斜线“/”转换为冒号“:”

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 17.0.0 |
| System | macOS 10.15.7 |
| Browser | Google Chrome 109.0.5414.119 |

---
使用原生的<input type="file" />上传文件不会出现自动转换的情况。我看了一下源码，没有找到文件名转换的逻辑，希望能告知一下转换逻辑，或者暴露一下api可以控制是否需要进行文件名转换。这些如果都不能提供的话，至少给一下文档说明有哪些字符会被自动转换为什么字符。

**Comment by zombieJ** [comment]
这个是浏览器的行为，和 antd、React 都没有关系哈。

**Comment by wjf40390** [comment]
> 这个是浏览器的行为，和 antd、React 都没有关系哈。

如果是浏览器的行为，为什么使用原生的input type="file" 上传文件时文件名可以正常显示，没有被转换。

<img width="653" alt="image" src="https://user-images.githubusercontent.com/41931794/220055635-c7e99783-5c83-411c-aac1-cd599d2e07e7.png">

**Comment by afc163** [comment]
<img width="698" alt="图片" src="https://user-images.githubusercontent.com/507615/220057809-f094401d-5631-4829-b7a6-19116b1dd509.png">

其实原生文件名就会转换成 `:`，不过回显的时候 Chrome 做了特殊处理。

**Comment by wjf40390** [comment]
> 

了解！那有没有相关的文档说明那些字符会被转换，或者如果我想做类似处理把文件名还原的话，怎么能知道那些字符是被转换的，哪些是原有的呢？

**Comment by afc163** [comment]
这个得看 W3C 规范文档了。
