### ISSUE TITLE
[Tabs]卡片式页签在关闭后没有立即触发TabNavList的transform变化

### ISSUE THREAD

**Issue by scottsut** [ant-design/ant-design#40816]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ik5ssj)

### Steps to reproduce

1. 点击新增按钮，新增多个 tab 页签直到超出 Tabs 长度

![image](https://user-images.githubusercontent.com/4098913/220010400-ea828b31-ce5b-409e-b838-57eb49c59f8c.png)

2. 关闭最后一个 tab 页签，可以发现 tab list 没有向右滚动对齐

![image](https://user-images.githubusercontent.com/4098913/220010493-8fbfd725-0ace-4f6d-9624-dc2b04b44dda.png)

3. 此时如点击其他 tab 页签，首次点击行为并不能生效，而是会触发 tab list 向右滚动对齐

![image](https://user-images.githubusercontent.com/4098913/220010618-61ac8528-176c-4503-9424-cc66e2dbf3e8.png)

![image](https://user-images.githubusercontent.com/4098913/220010777-3d699a18-9acf-463e-882c-26eb5c79c51b.png)

### What is expected?

关闭最后一个 tab 页签时，能够立即触发 tab list 向右滚动对齐

### What is actually happening?

没有自动触发滚动，导致之后的其他事件（如点击）会首先触发滚动行为而失效

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.0.0 |
| System | macOS Ventura 13.2.1 |
| Browser | Google Chrome 109.0.5414.119 |

---
经验证，将 antd 版本回滚到 4.23.5 后问题得以解决，[复现链接](https://codesandbox.io/s/xin-zeng-he-guan-bi-ye-qian-antd-5-2-2-forked-y4fuuj)

从 4.23.5 升级至 4.23.6 时，rc-tabs 依赖从 12.1.0-alpha.1 升级到了 12.2.0，追溯代码，猜测是 [ca8a22d](https://github.com/react-component/tabs/commit/ca8a22d6eea31ee76bb893fbb94d0dbac1a8862d) 这次提交导致的问题

**Comment by Yuiai01** [comment]
感觉跟这个问题一致：https://github.com/ant-design/ant-design/issues/40155

**Comment by zombieJ** [comment]
> 从 4.23.5 升级至 4.23.6 时，rc-tabs 依赖从 12.1.0-alpha.1 升级到了 12.2.0，追溯代码，猜测是 [ca8a22d](https://github.com/react-component/tabs/commit/ca8a22d6eea31ee76bb893fbb94d0dbac1a8862d) 这次提交导致的问题

看起来是计算逻辑有点问题，我挖一下。

**Comment by zombieJ** [comment]
看了一下，由于统计数据是通过 raf 异步计算。导致 effect 触发的时候，使用的还是变化前的数据，使得 Tabs 觉得不用位移。我想想。

**Comment by zombieJ** [comment]
+ rc-tabs@12.5.7
https://codesandbox.io/s/xin-zeng-he-guan-bi-ye-qian-antd-5-2-2-forked-t7fm1u?file=/package.json
