### ISSUE TITLE
[table] rowSelection.selections 有值时，选择列列宽不够

### ISSUE THREAD

**Issue by boomler** [ant-design/ant-design#40814]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-xuan-ze-antd-5-2-2-forked-mwquv0?file=/demo.tsx)

### Steps to reproduce

查看渲染结果

### What is expected?

首列表头的宽度增大到 64px, 以便下拉箭头和表格线框有足够的空间

### What is actually happening?

下拉箭头和表格线框贴在了一起

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | All |
| System | All |
| Browser | All |

---
虽然可以用  rowSelection.columnWidth 来自己改，但这个逻辑应该做在内部，即：
1. 无下拉选择，默认列宽 32px
2. 有下拉选择，默认列宽 64px

**Comment by boomler** [comment]
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/17810913/220002333-68b6233a-066d-44a0-bfb0-5f5901bf91bc.png">

**Comment by MuxinFeng** [comment]
要不我来试试提个 pr 修复吧

**Comment by li-jia-nan** [comment]
> 要不我来试试提个 pr 修复吧

别急，这个应该要设计师讨论一下

**Comment by idler8** [comment]
这个时候，是不是就不要checkbox了，直接改成下拉，第一项全选
