### ISSUE TITLE
[Modal] 对话框希望增加一个切换动画结束后的回调

### ISSUE THREAD

**Issue by zynyy** [ant-design/ant-design#40810]
### What problem does this feature solve?

因为对话框在动画执行过程中渲染页面获取的宽度不够准确导致会时不时的布局错乱。所以希望跟 Drawer抽屉一样增加一个 afterOpenChange 切换动画结束后的回调

### What does the proposed API look like?

afterOpenChange: (open: boolean) => void

**Comment by afc163** [comment]
Wait for https://github.com/react-component/dialog/pull/251

**Comment by zombieJ** [comment]
@MadCcc  确保一下 API 都是统一规范
