### ISSUE TITLE
AutoComplete onKeyPress does not work

### ISSUE THREAD

**Issue by drcmda** [ant-design/ant-design#4082]
The onKeyPress seems to be missing on the AutoComplete. It works on the Input. I'm not sure if this is an issue with 2.5.0, i think it should have worked previously. We need this event to check for special keys.

```js
@connect((state, props) => ({ item: state.elements[props.id] }))
export default class ConsoleElement extends React.PureComponent {
    handleChange = value => this.props.dispatch(actions.update(this.props.id, { value }))
    handleKeyPress = event =>this.props.dispatch(actions.event(this.props.id, event))
    render() {
        let { value, children } = this.props.item;
        return (
            <AutoComplete
                ref="input"
                placeholder="Just type ..."
                style={{ ...this.props.style }}
                value={value}
                dataSource={children}
                onChange={this.handleChange} onKeyPress={this.handleKeyPress} />
        )
    }
}
```

**Comment by benjycui** [comment]
Actually, AutoComplete is sub class of `Select[combobox]`, so it doesn't has `onKeyPress` event like Input...

**Comment by benjycui** [comment]
@afc163 组件间的关系应该可以梳理一下，概念上，所有表单类组件都是 Input 的子类，所以基础的 API 应该都有。

现在使用了 TypeScript，所以我们可以定义 interface Input，并要求其他表单类组件都继承这个接口。

Popover Popconfirm Tooltip 也是类似的关系。

**Comment by afc163** [comment]
其实最好 AutoComplete 支持下面这样的用法，会比较灵活。

```jsx
<AutoComplete>
  <Input />
</AutoComplete>
```

**Comment by drcmda** [comment]
@benjycui Yes, but it wraps a regular input. It would be consistent if we had the same events avilable. Could this be routed to the text input sitting under ant-select-search__field?

**Comment by bang88** [comment]
相同的属性继承会比较好一点.

**Comment by RaoHai** [comment]
@afc163 有道理

**Comment by afc163** [comment]
@RaoHai can update antd's AutoComplete API now.
