### ISSUE TITLE
Incorrect value displaying if min changes to value which is more than max after first render

### ISSUE THREAD

**Issue by didolf** [ant-design/ant-design#40826]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-oiq1in?file=/index.js)

### Steps to reproduce

Set up min to 100 max to 500, value to 600
Change min to 600

### What is expected?

handle invisible

### What is actually happening?

handle positioned on very big distance.

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2 |
| System | MacOS |
| Browser | Chrome 110 |

---
https://github.com/react-component/slider/issues/861 closing this issue can help)

**Comment by MadCcc** [comment]
It's wired to set `min` larger than `max`, which may not be considered by antd.
