### ISSUE TITLE
Incorrect value displaying on dynamically changing min value to equal to max value

### ISSUE THREAD

**Issue by didolf** [ant-design/ant-design#40827]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-opsf4x)

### Steps to reproduce

Set up min to 1 max to 10
Change value to 5
Change min to 10

### What is expected?

handle positioned on start of rail, track width = 0

### What is actually happening?

handle positioned on center of rail, track width != 0

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2 |
| System | MacOS |
| Browser | Chrome 110 |

---
Fix this issue can help https://github.com/react-component/slider/issues/860

**Comment by zombieJ** [comment]
Since it's meaningless for max value equals min value, I don't think it should be 'a rule' to guide what it should look like. But if you need this, you can HOC for slider:
https://codesandbox.io/s/antd-reproduction-template-forked-7tiwnn?file=/index.js
