### ISSUE TITLE
TimePicker force disabledTime when calling form.setFieldsValue

### ISSUE THREAD

**Issue by FrenchMajesty** [ant-design/ant-design#40832]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-liskov-h37z9i?file=/src/App.js)

### Steps to reproduce

- Enter random time: 8:00AM
- Click "Load data"
- Try to change time again

### What is expected?

I should be able to pick any time

### What is actually happening?

I am unable to pick any time before 5:30PM when using Mobile view.

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2 |
| System | MacOS |
| Browser | Chrome |

---
This works fine in browser desktop view, but is broken on mobile view because the time is no longer scrollable

**Comment by MadCcc** [comment]
Why not? You could select time before by touchmove.

**Comment by FrenchMajesty** [comment]
@MadCcc I don't understand what you mean or what you're asking
