### ISSUE TITLE
Timeline "alternate" and "right" modes are broken for items that have an extra className

### ISSUE THREAD

**Issue by antonabramovich** [ant-design/ant-design#40833]
### Reproduction link

[https://stackblitz.com/edit/react-rfoveg?file=demo.tsx](https://stackblitz.com/edit/react-rfoveg?file=demo.tsx)

### Steps to reproduce

1. Add mode="alternate" or mode="right" to the `<Timeline />`
2. Add "className" property to one or more items

### What is expected?

Timeline items are displayed either in center ("alternate") with the text on alternating sides or on the right ("right") with the text on left side

### What is actually happening?

Items with "className" property are displayed in the center

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2 |
| System | Windows |
| Browser | Chrome |

---
Most likely caused by this fix https://github.com/ant-design/ant-design/pull/40700

**Comment by Yuiai01** [comment]
I'll fix it.

**Comment by Yuiai01** [comment]
Since the `item` itself has a className, the className passed in first is overridden.
![image](https://user-images.githubusercontent.com/112228030/220215823-0cd19630-e189-47a7-a23a-09fa5450e52b.png)
