### ISSUE TITLE
Input.TextArea inside Form.Item with name doesn't set a value

### ISSUE THREAD

**Issue by romankolychev** [ant-design/ant-design#40830]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/textarea-antd-5-2-2-forked-qg7kds?file=/demo.tsx:302-310)

### Steps to reproduce

Set `value` to `<Input.TextArea>` wrapped into `<Form.Item>` with `name` prop:
```
      <Form.Item name="formName">
        <Input.TextArea rows={4} value="input value" />
      </Form.Item>
```

### What is expected?

The passed value is displayed in textarea.

### What is actually happening?

The passed value is not displayed in textarea.

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.0.0 |
| System | Linux Mint 20.2 |
| Browser | Chrome 105.0.5195.102 |

**Comment by Yuiai01** [comment]
This looks like a bug 🤔

**Comment by zombieJ** [comment]
Please ref doc about Form.Item `name` usage before create issue. When `name` configured, `value` is taken control by Form.Item:
https://codesandbox.io/s/textarea-antd-5-2-2-forked-3dzog4

**Comment by MuxinFeng** [comment]
maybe you can try this demo https://codesandbox.io/s/textarea-antd-5-2-2-forked-l8rqrr?file=/demo.tsx

**Comment by romankolychev** [comment]
thank you
