### ISSUE TITLE
Rate V5 readonly is moving on hover even though it is disabled 

### ISSUE THREAD

**Issue by quaverlyy** [ant-design/ant-design#40834]
### Reproduction link

[https://ant.design/components/rate?theme=dark](https://ant.design/components/rate?theme=dark)

### Steps to reproduce

hover over the stars, it moves even though it is supposed to be readonly/disabled. V4 was working fine. 

### What is expected?

the stars should not move when it is disabled

### What is actually happening?

the stars are moving on mouse in/out

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | 22h2 windows 11 |
| Browser | chrome 110.0.5481.104 |

**Comment by Yuiai01** [comment]
I'll fix it.
