### ISSUE TITLE
[DatePicker国际化]反复切换语言后文案就不正确了

### ISSUE THREAD

**Issue by yexingxia** [ant-design/ant-design#4083]
#### 发生问题的环境是：

- antd 版本:  2.5.0
- 操作系统及其版本:  win7
- 浏览器及其版本: chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

切换到中文后再切回英文，点开日历，年月和星期部分的文案不正确

#### 您期待的结果是:

年月和星期部分的文案是英文

#### 实际上的结果是:

年月和星期部分的文案显示为中文，但又不完全和切换到中文时一致

#### 可重现的在线演示

http://codepen.io/anon/pen/PbOWme?editors=0010

**Comment by benjycui** [comment]
语言切换推荐直接刷新页面，不然大量的 state 需要处理，不划算。

**Comment by benjycui** [comment]
https://github.com/ant-design/intl-example
