### ISSUE TITLE
异步获取treeData，勾选TreeNode报错

### ISSUE THREAD

**Issue by wnow20** [ant-design/ant-design#4084]
#### 发生问题的环境是：

- antd 版本: 2.4.3
- 操作系统及其版本: OS X 10.11.6
- 浏览器及其版本: Chrome 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。
异步获取treeData，勾选TreeNode报错

#### 实际上的结果是:
![image](https://cloud.githubusercontent.com/assets/6159049/20755067/981f7ae0-b748-11e6-90c2-469be9f23dd3.png)

#### 可重现的在线演示

http://codepen.io/GanisEnder/pen/ZBavNv?editors=0010

**Comment by batouy** [comment]
好像确实有这个问题

**Comment by batouy** [comment]
这个问题还是没有办法解决吗

**Comment by yesmeck** [comment]
tree 比较复杂，暂时还知道怎么修。

**Comment by yesmeck** [comment]
https://ant.design/components/tree/#note 试试这个？

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design/issues/1730#issuecomment-270600608

**Comment by warmhug** [comment]
这种问题记得以前有 issue 提到过的。  @yesmeck 可以先全部搜搜其他 issue 看、再确认怎么改动
