### ISSUE TITLE
notification、message使用StyleProvider样式降级后未降级成功

### ISSUE THREAD

**Issue by GuanErShuiShou** [ant-design/ant-design#40845]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-p0yjz5?file=/index.js)

### Steps to reproduce

搜狗浏览器访问链接按钮等组件降级成功，notification、message降级失败

### What is expected?

搜狗浏览器等低内核notification、message降级成功

### What is actually happening?

搜狗浏览器等低内核notification、message降级失败

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | win |
| Browser | 搜狗浏览器  |

**Comment by zombieJ** [comment]
你的重现里没有 notification  和 alert。

**Comment by mkRui** [comment]
[Modal.confirm](https://codesandbox.io/embed/antd-reproduction-template-forked-1oct1u?fontsize=14&hidenavigation=1&theme=dark)

**Comment by GuanErShuiShou** [comment]
> 你的重现里没有 notification 和 alert。

现在有了

> 你的重现里没有 notification 和 alert。

我更新了代码实例
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-p0yjz5?file=/index.js)

在低版本内核浏览器错误组件是notification 和 message以及modal这种挂载刀body上的相关API

**Comment by mkRui** [comment]
@GuanErShuiShou [使用APP组件](https://ant.design/components/app-cn/) 可以看一下这个

**Comment by frostbelt** [comment]
> @GuanErShuiShou [使用APP组件](https://ant.design/components/app-cn/) 可以看一下这个

Modal.confirm 还是不生效
