### ISSUE TITLE
时间类组件提交服务器出错

### ISSUE THREAD

**Issue by dongtao0725** [ant-design/ant-design#40844]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k1zt57?file=/demo.js)

### Steps to reproduce

官方组件代码就运行出错，TypeError: Cannot read properties of undefined (reading 'format')

### What is expected?

将dayjs对象格式话成字符串

### What is actually happening?

TypeError: Cannot read properties of undefined (reading 'format')

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.0 |
| System | Win10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
操作步骤是什么？

**Comment by dongtao0725** [comment]
随便选择日期时间，然后提交form，看看console能否输出字符串格式的日期时间，现在console会返回TypeError: Cannot read properties of undefined (reading 'format')

**Comment by afc163** [comment]
<img width="1787" alt="图片" src="https://user-images.githubusercontent.com/507615/220302031-d37a9768-c41a-4856-8dd0-17a1a6df1222.png">

没发现问题。

**Comment by dongtao0725** [comment]
<ProFormDateRangePicker name="dateRange" width={'md'} label="日期区间" />
在沙盒返回字符串正常，但在本地返回的是object，导致提交服务器异常，依赖版本均一致
[
    {
        "$L": "en",
        "$d": "2023-02-22T02:59:19.790Z",
        "$x": {},
        "$y": 2023,
        "$M": 1,
        "$D": 22,
        "$W": 3,
        "$H": 10,
        "$m": 59,
        "$s": 19,
        "$ms": 790
    },
    {
        "$L": "en",
        "$d": "2023-02-23T02:59:19.790Z",
        "$x": {},
        "$y": 2023,
        "$M": 1,
        "$D": 23,
        "$W": 4,
        "$H": 10,
        "$m": 59,
        "$s": 19,
        "$ms": 790
    }
]

**Comment by zombieJ** [comment]
还是需要提供在线重现的，否则不知道你遇到的是什么问题。

**Comment by dongtao0725** [comment]
https://codesandbox.io/embed/shi-jian-lei-kong-jian-antd-5-2-2-forked-qf5wug?fontsize=14&hidenavigation=1&theme=dark

**Comment by zombieJ** [comment]
ProForm 在提交阶段会转一下日期对象值，可以额外包一层如果要自己处理的话：

https://codesandbox.io/s/shi-jian-lei-kong-jian-antd-5-2-2-forked-51j1lk?file=/demo.js

**Comment by dongtao0725** [comment]
![image](https://user-images.githubusercontent.com/30116184/221080868-701eeac3-95d8-4e93-b5d6-09ddd9b73f94.png)
沙盒中ProForm的日期对象是格式化之后的
但在本地电脑、一样的代码和依赖
ProForm的日期对象没有格式化，返回的是对象，因此使用dayjs()格式化出错，请问是否有什么可能原因
![image](https://user-images.githubusercontent.com/30116184/221081040-4dd6fb45-f76d-4b6e-aee8-c6a894437ec0.png)
