### ISSUE TITLE
Steps component document within the clickable example of the onchange print event within the print value will have doubts

### ISSUE THREAD

**Issue by linercoder** [ant-design/ant-design#40846]
### Reproduction link

[https://ant.design/components/steps-cn#components-steps-demo-clickable](https://ant.design/components/steps-cn#components-steps-demo-clickable)

### Steps to reproduce

The value printed after the onChange is triggered within the clickable example is current, which is an asynchronous value, which can be confusing for people reading the documentation

### What is expected?

The value printed should be the value of the callback inside the onChange

### What is actually happening?

The printout is current in the useState

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.0.0 |
| System | window11 |
| Browser | edge 110.0.1587.50 |

**Comment by zombieJ** [comment]
Good point. It's confusing if not read the demo code.
