### ISSUE TITLE
Modal.confirm方法，title前会有一个黄色的感叹号，有什么方法可以去除它吗？

### ISSUE THREAD

**Issue by guanshining** [ant-design/ant-design#40842]
### What problem does this feature solve?

普通弹窗不需要有状态icon

### What does the proposed API look like?

Modal.confirm({iconType:'none'})

**Comment by yoyo837** [comment]
官网例子没看见有啥感叹号

**Comment by luo3house** [comment]
https://github.com/ant-design/ant-design/blob/7043cadab0e35ebc2def8577caea022501c395ed/components/modal/ConfirmDialog.tsx#L57-L60

**Comment by guanshining** [comment]
我们项目是从v4升级到v5的，在v4中，icon:false，可以去除icon，v5中icon:false好像无效耶，icon:null，可以不显示小icon。
