### ISSUE TITLE
关于 Pagination 的 pageSize 下拉框 dropdown 定位问题

### ISSUE THREAD

**Issue by chenxiaochun** [ant-design/ant-design#40849]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-driscoll-7fcy71?file=/src/App.tsx:126-127)

### Steps to reproduce

1. 如上面示例，Pagination 的定位为 position: sticky
2. 使页面滚动条在大概页面中部的位置。这时，点击 Pagination 上的 pageSize 下拉框，会发现它的 dropdown 被遮挡在了页面下方
3. 之前在 Antd4.0 中没有这种问题

### What is expected?

其实 Select 组件上提供了 placement 属性。能不能也在 Pagination 上将 SelectProps 也暴露出来，使得开发者可以自定义 pageSize 下拉框

### What is actually happening?

实际并没有任何办法修改

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/36866

**Comment by MadCcc** [comment]
Trace https://github.com/ant-design/ant-design/issues/36866
