### ISSUE TITLE
<Badge count={0} color='#000' />会有个宽高的占位，不设置color没有宽高占位

### ISSUE THREAD

**Issue by zhaoxiangyan** [ant-design/ant-design#40841]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1o97hy?file=/index.js)

### Steps to reproduce

<Badge count={0} color="#000" />
<Badge count={0} />
执行结果，样式不一样

### What is expected?

count为0时，自定义color，无宽度占位

### What is actually happening?

count为0时，自定义color，有宽度占位

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2 |
| System | windows10 |
| Browser | Microsoft Edge 版本 110.0.1587.41 (正式版本) (64 位) |

---
antd版本4转化过来，发现版本5显示不一样

**Comment by MadCcc** [comment]
Same in v4.24.8
![image](https://user-images.githubusercontent.com/27722486/220280120-8845c7ce-cf83-4896-b194-e05b8999acb7.png)

**Comment by zhaoxiangyan** [comment]
刚去看了下，之前4版本我是用style background直接写在组件上的，我改了下，没问题就关了吧
