### ISSUE TITLE
bodyStyle in Modal for version 5.x is not same as version 4.x 

### ISSUE THREAD

**Issue by yashkk3640** [ant-design/ant-design#40856]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-2-2-forked-j546eu?file=/demo.tsx)

### Steps to reproduce

Create Modal with bodyStyle with padding in 5.x and 4.x to check the difference

### What is expected?

In version 5.x Modal component bodyStyle applies differently than version 4.x on `div.ant-modal-body`

### **Not able to modify padding of the modal in version 5.x**
**in 4.x bodyStyle padding override the default padding but in 5.x it is adding extra padding on some other div**

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 17.x |
| System | any |
| Browser | chrome |

---
Demo on version 4.x [https://codesandbox.io/s/basic-antd-4-24-8-forked-08oxd3](https://codesandbox.io/s/basic-antd-4-24-8-forked-08oxd3)
Demo on version 5.x [https://codesandbox.io/s/basic-antd-5-2-2-forked-j546eu?file=/demo.tsx](https://codesandbox.io/s/basic-antd-5-2-2-forked-j546eu?file=/demo.tsx)

**Comment by yoyo837** [comment]
Why do they should must to be the same? This is the major version changes.

**Comment by yashkk3640** [comment]
<html>
<body>


bodyStyle | Body style for modal body element. Such as height, padding etc | CSSProperties
-- | -- | --



</body>
</html>

I thought this means to modify, if it's not can you explain how I can modify the default padding to make this same as version 4.x?

**Comment by MadCcc** [comment]
Design is updated in v5, and we have different css implementation for style.
It is recomended to update your `bodyStyle` for v5.
Or if you prefer styles of v4, you can get it back like this:
```
<ConfigProvider theme={{ components: { Modal: { wireframe: true }} }}>
  <Modal />
</ConfigProvider>
```
