### ISSUE TITLE
Date picker unexpected behaviour

### ISSUE THREAD

**Issue by rustam-as** [ant-design/ant-design#40858]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3mkj09)

### Steps to reproduce

I use Antd and React. In my modal I set fields value with antd useForm hook. It seems to work okay so far.

### What is expected?

I used antd datepicker couple of times. We used to see simple datepicker renders dates and it works normal.

### What is actually happening?

But somehow it render dates weirdly. I added froked codesandbox link. On the first click dates seems to be collapsed with blu background. Only after clicking 'today' datepicker works okay.

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | react@18.2.0 |
| System | Windows 11 pro 64bit (10.0 Build 22000) |
| Browser | Google Chrome Version 110.0.5481.77 (Official Build) (64-bit) |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-3mkj09?file=/index.js

<img width="445" alt="图片" src="https://user-images.githubusercontent.com/507615/220356883-43b6df26-ff76-4155-8d32-91b3406b9b84.png">

It is good to me, anything I miss?

**Comment by rustam-as** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-3mkj09?file=/index.js
> 
> <img alt="图片" width="445" src="https://user-images.githubusercontent.com/507615/220356883-43b6df26-ff76-4155-8d32-91b3406b9b84.png">
> 
> It is good to me, anything I miss?

you need to update antd version to 5.2.2.

**Comment by rustam-as** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-3mkj09?file=/index.js
> 
> <img alt="图片" width="445" src="https://user-images.githubusercontent.com/507615/220356883-43b6df26-ff76-4155-8d32-91b3406b9b84.png">
> 
> It is good to me, anything I miss?

try this link https://codesandbox.io/s/antd-reproduction-template-forked-vu1sg0

**Comment by rustam-as** [comment]
> ### You may look for issues:
> 1. 57% [Date picker is laggy #38686](https://github.com/ant-design/ant-design/issues/38686)
> 2. 57% [ant-design date picker #25235](https://github.com/ant-design/ant-design/issues/25235)
> 3. 54% [DatePicker multiple date selection? #4447](https://github.com/ant-design/ant-design/issues/4447)
> 
> 🤖 By [issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis)
