### ISSUE TITLE
[Tour]组件初次渲染的open为false时，TourStep的第一个指向超过一屏时会出现页面滚动想象

### ISSUE THREAD

**Issue by dabanli123** [ant-design/ant-design#40868]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-gauss-ux5ozl?file=/src/App.js)

### Steps to reproduce

页面初次渲染，TourStep的第一个引导指向的内容超过一屏时会出现页面滚动想象

### What is expected?

未开启引导时，页面不会向下滚动

### What is actually happening?

页面初次渲染时，open为false，页面不会向下滚动

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 17.0.1 |
| System | Win 11 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
@kiner-tang 正好测测这个会不会也能好~

**Comment by kiner-tang** [comment]
> @kiner-tang 正好测测这个会不会也能好~

ok

**Comment by kiner-tang** [comment]
> > @kiner-tang 正好测测这个会不会也能好~
> 
> ok

目前还是有问题，我来修复一下，应该`open`为 true 时才需要触发`scrollIntoView`的逻辑
