### ISSUE TITLE
Owl Carousel 

### ISSUE THREAD

**Issue by JunaidAli-56** [ant-design/ant-design#40866]
### What problem does this feature solve?

Add owl carousel like component. Requested from Pakistan. 

### What does the proposed API look like?

https://www.jqueryscript.net/demo/Powerful-Customizable-jQuery-Carousel-Slider-OWL-Carousel/

it should look like this

**Comment by AliHaiderPgm** [comment]
> Would love to see that... 👀

**Comment by zombieJ** [comment]
Could you help to provide more detail instead lib directly. What's the interactive do you want?

**Comment by afc163** [comment]
See https://ant.design/components/carousel

**Comment by JunaidAli-56** [comment]
> Could you help to provide more detail instead lib directly. What's the interactive do you want?
https://www.jqueryscript.net/demo/Powerful-Customizable-jQuery-Carousel-Slider-OWL-Carousel/demos/custom.html
Look at this you will understand what we are looking for. Thanks

**Comment by AliHaiderPgm** [comment]
Control scrolling of elements when we scroll over them and they stop when we stop scrolling.
