### ISSUE TITLE
4.x文档中版本订阅其中一个链接错误

### ISSUE THREAD

**Issue by 7NZ** [ant-design/ant-design#40869]
### Reproduction link

[https://4x-ant-design.antgroup.com/docs/react/introduce-cn](https://4x-ant-design.antgroup.com/docs/react/introduce-cn)

### Steps to reproduce

4.x文档里面，点击文档，下面的版本更新订阅链接第二个链接不对，点了链接跳到porn网站。

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18 |
| System | win10 |
| Browser | chrome110 |

**Comment by afc163** [comment]
来个 PR 干掉

**Comment by crazyair** [comment]
不是一个链接，是所有组件切换都丢失 / 导致 404
![image](https://user-images.githubusercontent.com/7971419/220520849-50cb669c-aec1-4abd-a839-d9cb4fe4fe44.png)
![image](https://user-images.githubusercontent.com/7971419/220520875-a6c55a4d-0cef-4211-833a-4d57d764c672.png)

**Comment by zombieJ** [comment]
> 不是一个链接，是所有组件切换都丢失 / 导致 404

这个切换新旧路由不一致导致的，也没有完全对应的规则。这个 issue 里是文档里的链接有问题。
