### ISSUE TITLE
再使用 Modal.confirm 等函数式弹框时未降级成功

### ISSUE THREAD

**Issue by mkRui** [ant-design/ant-design#40873]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-1oct1u?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

调用 Modal.confirm 或者使用 ReactDOM.render 的组件

### What is expected?

可以正确取消 :where 选择器

### What is actually happening?

降级无反应

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.x |
| System | win |
| Browser | 360 等低版本浏览器 |

**Comment by zombieJ** [comment]
> 在绝大多数场景，都不需要静态方法。它无法消费 context，例如无法响应动态主题。请优先使用 hooks 版本或者 App 组件提供的 Modal 实例。

ref https://ant.design/components/modal-cn#components-modal-demo-static-info
