### ISSUE TITLE
table shouldCellUpdate render方法的index问题

### ISSUE THREAD

**Issue by Cyxwmm** [ant-design/ant-design#40880]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd16-8-w1go19?file=/src/App.tsx)

### Steps to reproduce

1. 初始化获取数据，dataSource rowKye为uid
2. 然后点击反转按钮。这个时候 我们再第一行输入时会发现，index的值是4。因为配置了scu，由于rowKey没有变，导致对比字段时，并没有触发渲染，没有命中scu，没有触发更新，index还是之前uid对应行的index

### What is expected?

table 的 dataSource 通过 dataSource.slice().reverse() 之后得到一个新的反转数组。反转之后，对于配置了scu逻辑的单元格，render方法的index发生改变

### What is actually happening?

如果只是单纯的反转，或者从已有的数据中 从中间截取一部分数据出来。rowKey没有变化，行的record不会发生改变，即record和preRecord不会发生改变，不会命中scu。

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.9 |
| System | windows10 |
| Browser | 谷歌 |

---
业务中无条件查询出所有数据，然后过滤查询中间几条数据，修改字段时，配置了scu后 导致bug发生。这个应该怎么解决比较好呢？

**Comment by RedJue** [comment]
复现链接打开空白
