### ISSUE TITLE
如果form表单被设置readonly/disabled，自定义FormItem的组件的props是否可以增加这两个属性。

### ISSUE THREAD

**Issue by HowCanLove** [ant-design/ant-design#40905]
### What problem does this feature solve?

用于 减少 需要 多次判断页面是否处于readonly/disabled状态。

### What does the proposed API look like?

能够在自定义开发组件的HOC里返回这两个状态，供自定义组件内部使用渲染对应的内容。

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by idler8** [comment]
是否与 #39545  重复
自定义需求高，可以看看我的新库[@idler8/form-react](https://github.com/idler8/observer)开发灵活的自定义嵌套表单
