### ISSUE TITLE
ConfigProvider 组件提供的 token 不生效

### ISSUE THREAD

**Issue by Gatsby069** [ant-design/ant-design#40909]
### Reproduction link

[https://stackblitz.com/edit/ant-desigin-configprovider?file=demo.tsx](https://stackblitz.com/edit/ant-desigin-configprovider?file=demo.tsx)

### Steps to reproduce

1.使用 `ConfigProvider` 组件包裹 `Layout.Header` 组件
2.在 `ConfigProvider` 组件中，为 `Layout.Header` 设置专属的 `theme`, 如 `colorBgHeader`

### What is expected?

Header的背景色变白

### What is actually happening?

`colorBgHeader` 无效

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | Window 10 |
| Browser | Google Chrome(110.0.5481.178) |

---
我查询到一个相关的 [issue](https://github.com/ant-design/ant-design/issues/38975)，应该是造成该问题的原因。
如果官方暂时不支持组件全量token注入，但是又不再使用 Less，那么当前推荐的修改样式的方案，应该是如何？
比如，我当前使用 emotion （CSS-in-JS），我该如果修改样式？因为`::where`选择器的存在，我的 emotion 代码权重被降低了。

**Comment by zombieJ** [comment]
发现是个 BUG

**Comment by Gatsby069** [comment]
> 发现是个 BUG，cssinjs 作用在 Layout 上，子元素不支持更新，我修一下： https://stackblitz.com/edit/ant-desigin-configprovider-bevlqw?file=demo.tsx

我看了下你的修复demo，发现你把 `ConfigProvider` 标签向上移动了一层，包裹在了 `Layout.Header` 和 `Layout.Content` 的外层 `Layout`元素上，然后样式生效。
但是我依然还是存在一个疑问，比如这个demo:
https://stackblitz.com/edit/react-ts-fjpwm8?file=App.tsx
我无法修改表头颜色。
我找到了属于 table 的 theme 的类型声明 `TableComponentToken`, 但是它是空的。然后我发现了 `TableToken` 这个声明具有我所需要的 `tableHeaderBg` 属性， 但是我不知道该如果使它生效。
![image](https://user-images.githubusercontent.com/66930419/221157424-9ec1ac30-4e8d-4f06-af33-cf2d1a5d2079.png)

我通过这个[issue](https://github.com/ant-design/ant-design/issues/38975)意识到可能是这个原因导致的。

**所以我最大的疑问是：我该如何正确地修改样式呢？（因为`antd`不再使用Less，但是 component token 目前又没有发布）**
比如这个例子：
https://stackblitz.com/edit/react-ts-7eecdl?file=App.tsx
**我不知道该如何编写`emotion`代码来让表头变色。**（因为我看你们的 [StyleProvider](https://github.com/ant-design/cssinjs#styleprovider)，其实底层依赖了 `emotion`，所以我也使用 `emotion` 库来书写我的CSS样式。）

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/40933/files#diff-cbecb841e4a0032c882897c0cf4ffcdca91a1804ec870b4808609e45a583c7c1R12
