### ISSUE TITLE
RangePicker结合Form使用设置disabled={[false, true]}默认带出当前时间，且无法清空

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design#40906]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jin-yong-antd-5-2-2-forked-jiwqf8?file=/demo.js)

### Steps to reproduce

将RangePicker的defaultValue设置成[]

### What is expected?

应该是可以置空

### What is actually happening?

无法置空

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.0 |
| System | MacOS |
| Browser | chrome |

**Comment by Yuiai01** [comment]
我看看~

**Comment by overcastsky** [comment]
gsdg45sd4g5s4dg5sdイシリーズからドムをプレゼンりやかなベルガモットオジビタから
