### ISSUE TITLE
<Select /> options dropdown gets hidden behind column cells, when used as an editor in a fixed column in <Table />

### ISSUE THREAD

**Issue by SaurabhDesaiCeloxis** [ant-design/ant-design#40913]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-column-select-editor-z-index-issue-s6bgq0)

### Steps to reproduce

1. Create a Table component with <Select /> as the editor in the fixed column.
2. Now, try to update the value using Select editor.
3. Observe that the dropdown of Select is hidden behind the cells of fixed column.
<img width="709" alt="Screenshot 2023-02-24 at 5 08 32 PM" src="https://user-images.githubusercontent.com/112700746/221173314-cbc5cbd2-0fe7-4e3b-be9b-0b617d7c11d5.png">

### What is expected?

The dropdown of the Select editor should be visible on top of the cells of fixed column.

### What is actually happening?

The dropdown of the Select editor is not visible when used in a fixed column.

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | react |
| System | Mac OS - Ventura 13.1 |
| Browser | Chrome - Version 110.0.5481.100 (Official Build) (x86_64) |

---
Let me know if you need any further information.

**Comment by DercilioFontes** [comment]
I saw that same behaviour. And removing the fixed showed the menu. But it only happened if using `getPopupContainer={(triggerNode) => triggerNode.parentElement}`. Without that, it was working fine.

**Comment by SaurabhDesaiCeloxis** [comment]
But after removing `getPopupContainer={(triggerNode) => triggerNode.parentElement}` when we try to scroll the table rows the dropdown of select remains on the screen while scrolling.PFA video for your reference

https://user-images.githubusercontent.com/112700746/221484164-0aab9e16-ad95-45c4-b0d6-54905cba0188.mov

The dropdown of select should scroll with the respective row.

**Comment by zombieJ** [comment]
We are working on auto align which will no need additional config of `getPopupContainer`. It's in progress : )

**Comment by nkli** [comment]
> 我们正在研究自动对齐，这不需要额外的配置`getPopupContainer`。正在进行中:)

How's the research going
