### ISSUE TITLE
TimePicker component- Adding a hour step that is not a factor of 24, or even adding a string results in unexpected behaviour

### ISSUE THREAD

**Issue by rgumzej** [ant-design/ant-design#40914]
### Reproduction link

[https://stackblitz.com/edit/react-bzrvwk?file=demo.tsx](https://stackblitz.com/edit/react-bzrvwk?file=demo.tsx)

### Steps to reproduce

Add hourStep to TimePicker component.
Assign it a value of "1.432" as string
Assign it a value as 1.432 as number
Assign it a value of 34

### What is expected?

Expected behaviour is that only factorable values of 24 can be assigned

### What is actually happening?

It is possible to assign any value, even a string, resulting in console warnings and weird values in the component such as a number with 9 decimal spaces

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Google Chrome |

https://user-images.githubusercontent.com/97878479/221252279-c679df46-aba2-4c11-86cc-295e740d310d.mp4

**Comment by rgumzej** [comment]
a fix is ready for PR if/ when accepted as bug

**Comment by Wxh16144** [comment]
I don't think developers would do something so stupid😂, but it could be a suggestion for improvement.

**Comment by rgumzej** [comment]
Probably not, but a typo is always possible :) Could we label it as improvement then?

**Comment by Wxh16144** [comment]
welcome~

**Comment by rgumzej** [comment]
As a 1st time contributor, don't have an option to label it...could You do it ?

**Comment by Wxh16144** [comment]
> As a 1st time contributor

I just joined the team not long ago, some things may not be able to make decisions, you are so positive that I will assign to you, to help you conduct code review.

**Comment by rgumzej** [comment]
Thank You :)

**Comment by zombieJ** [comment]
> I just joined the team not long ago, some things may not be able to make decisions, you are so positive that I will assign to you, to help you conduct code review.

contributor mark will be auto marked by github when PR merged. No need add additional label for this. But `assign` to developer is a good way to avoid other contributor PR for the same issue : )
