### ISSUE TITLE
Table - Column render not update on outer state variables change

### ISSUE THREAD

**Issue by shinryuken0505** [ant-design/ant-design#40915]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-fire-c807te?file=/src/App.js)

### Steps to reproduce

1.Set columns by useState(<columnsType>) in antd table.
2.columns  render content with outer "status" variable, and the "status" is initialed by useState(<String>). 
2.Update setState("New") to update  "status" variable,  but table content cann't render in table content.

### What is expected?

Table content render content renew when outer "status" variable by useState()

### What is actually happening?

Table content content no update when setState("New") at useEffect triggering

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | windows |
| Browser | Chrome |

---
Thanks all~

**Comment by cpboom** [comment]
Maybe you can try useMemo

**Comment by Wxh16144** [comment]
Wrong use of React causes this. As mentioned above, you should use React.useMemo, adding status to the second argument of useMemo as a dependency.

**Comment by shinryuken0505** [comment]
Thank you all very much, I'll try this method.

**Comment by adelobosko** [comment]
> Wrong use of React causes this. As mentioned above, you should use React.useMemo, adding status to the second argument of useMemo as a dependency.

i have updated antd from 4.17.2 to 4.24.1 and it broked tables in class components

**Comment by guiwustro** [comment]
> > Wrong use of React causes this. As mentioned above, you should use React.useMemo, adding status to the second argument of useMemo as a dependency.
> 
> i have updated antd from 4.17.2 to 4.24.1 and it broked tables in class components

I have the same problem. I'm updating the library from 3.x to 4.x and thanks to your comment at least I can update to 4.x.. This update also broke my tables in class components. Did you find some solution? I will keep the 4.17.2 version meanwhile. The another solution would be refactoring to functional components 😅

**Comment by adelobosko** [comment]
> > > Wrong use of React causes this. As mentioned above, you should use React.useMemo, adding status to the second argument of useMemo as a dependency.
> > 
> > 
> > i have updated antd from 4.17.2 to 4.24.1 and it broked tables in class components
> 
> I have the same problem. I'm updating the library from 3.x to 5.x and thanks to your comment at least I can update to 4.x.. This update also broke my tables in class components. Did you find some solution? I will keep the 4.17.2 version meanwhile. The another solution would be refactoring to functional components 😅

4.18.0 cause it, so you can use < 4.18.0 or rewrite to the functional component
