### ISSUE TITLE
BackTop和Tooltip搭配使用有bug

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#4091]
```
<Tooltip title={"回到顶部"}>
    <BackTop />
</Tooltip>

```
上述方式有个问题：
onMouseEnter => tooltip show => onClickBackTop => page scroll to top => tooltip did not hide
切换路由至另一短页面，由于tooltip没消失导致短页面被撑长，改进使用方法如下：

```
<Tooltip
    title={<span style={{whiteSpace: "nowrap"}}>回到顶部</span>}
    getTooltipContainer={() => document.getElementById("backtop")}>
    <BackTop id="backtop" />
</Tooltip>
```
又带来另一个问题：BackTop第一次渲染Tooltip是有效的，但在回到页面顶端后BackTop消失，向下滑动页面后BackTop重新渲染，导致Tooltip渲染异常，无法再显示

**Comment by benjycui** [comment]
@ddcat1115 [这儿](https://github.com/ant-design/ant-design/blob/master/components/back-top/index.tsx#L118-L122) 可以用 `display: none` 实现？

**Comment by ddcat1115** [comment]
应该可以，我试下

**Comment by ddcat1115** [comment]
采用 `display: none` 会影响动效，这里就采用第一种方式，BackTop onClick 时自己把 Tooltip 的 visible 设置为 false 吧
