### ISSUE TITLE
Default filter for form to handle set

### ISSUE THREAD

**Issue by b5414** [ant-design/ant-design#40916]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-y3g1fh?file=/index.js)

### Steps to reproduce

1. Open: [codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-y3g1fh?file=/index.js)
2. Type something in the input
3. Before you click untitled btn, you see the data with category "aaa"
4. Click button, for search "new data" with (set) category "bbb"
5. Click something to trigger h.tableChange(), eg: update column sort
6. Now you see "aaa" category items // **because table received no feedback on filter change**

### What is expected?

You see "aaa" category items, but how to make table show "bbb" - for now no solution (as far I see)

### What is actually happening?

You see "aaa" category items

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | Windows 10 latest |
| Browser | Chrome 112 |

---
It's probably should be the feature request, but imho it's more than just a feature request and it breaking the table filter/sort things

My suggestion is that the table must take some input value so that you can not only read the output value, due to the problems described above

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ireled?file=/index.js

If you want to fully control filter logic, you should use control mode instead.

**Comment by b5414** [comment]
```js
columns.state.filteredValue = [];
columns.category.filteredValue = [filterby?.category || null];
columns.updated_at.sortOrder = sortby?.[0]?.order === 'desc' ? 'descend' : 'ascend';
```

ref: https://ant.design/components/table#components-table-demo-reset-filter
