### ISSUE TITLE
分段进度条的Info信息显示不符合预期

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#40921]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nurj39?file=/index.js:328-336)

### Steps to reproduce

1. progress设置 success属性
2. 动态增加减少 percent 
3. info的百分比没有发生变化

### What is expected?

点击发生之后 显示对应的百分比

### What is actually happening?

一直显示为0

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 18 |
| System | mac |
| Browser | google |

---
progressInfo中 React.useMemo的依赖为 percentNumber  但是 percentNumber在里面没有使用 
 text = textFormatter(validProgress(percent), validProgress(successPercent));
percent引起percentNumber的变化  progressInfo 会重新执行 但是 text的取值不符合预期

**Comment by Yuiai01** [comment]
percentNumber 会优先取 success 中的 percent，所以导致了后续 percent 更改，进度条也没有进行更改，加上依赖项应该就好了~
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/112228030/221387737-56a60d21-b498-440b-813e-7bdc4f52e6ed.png">

**Comment by kiner-tang** [comment]
我来看看吧

**Comment by kiner-tang** [comment]
@Yuiai01 来个pr修复一下？

**Comment by Yuiai01** [comment]
> @Yuiai01 来个pr修复一下？

好~ 在写测试用例了

**Comment by Wxh16144** [comment]
> percentNumber 会优先取 success 中的 percent

我在想这个是不是就是预期行为？如果有 success 则使用 success 里面的 percent, 如果要修改也是修改 succnes.percent

直接这样做就好了

```tsx
const App = () => {
  const [percent, setPercent] = React.useState(0);
  return (
    <>
      <Progress percent={percent} />
      <Progress success={{ percent }} />
      <Progress type="dashboard" percent={percent} success={{ percent }} />
      <Progress type="circle" percent={percent} success={{ percent }} />
      <button type='button' onClick={() => setPercent(v => (v + 5) % 100)}>
        Change Percent
      </button>
    </>
  );
}

export default App;```

cc @zombieJ @MadCcc

**Comment by Yuiai01** [comment]
> > percentNumber 会优先取 success 中的 percent
> 
> 我在想这个是不是就是预期行为？如果有 success 则使用 success 里面的 percent, 如果要修改也是修改 succnes.percent
> 
> 直接这样做就好了
> 
> ```tsx
> const App = () => {
>   const [percent, setPercent] = React.useState(0);
>   return (
>     <>
>       <Progress percent={percent} />
>       <Progress success={{ percent }} />
>       <Progress type="dashboard" percent={percent} success={{ percent }} />
>       <Progress type="circle" percent={percent} success={{ percent }} />
>       <button type='button' onClick={() => setPercent(v => (v + 5) % 100)}>
>         Change Percent
>       </button>
>     </>
>   );
> }
> 
> export default App;
> ```
> 
> 上述代码发现一个新的问题： ![image](https://user-images.githubusercontent.com/32004925/221392391-ed35b90e-548d-4e0f-9106-cf70e287d8ed.png)
> 
> cc @zombieJ @MadCcc

大佬，我觉得 success.percent 是进度条 success 状态的节点，而 percent 是用于记录进度条的进度，节点应该固定，而不能随着进度的更改而更改🤔🤔

**Comment by Wxh16144** [comment]
> 我觉得 success.percent 是进度条 success 状态的节点，而 percent 是用于记录进度条的进度，节点应该固定，而不能随着进度的更改而更改

你是对的，我当初没考虑清楚。我赞同你那边 PR 的修复过程。 添加到依赖项就好了。
