### ISSUE TITLE
不直接使用ConfigProvider包裹传入token, 而是调用方法传入token

### ISSUE THREAD

**Issue by qc-z** [ant-design/ant-design#40923]
### What problem does this feature solve?

除了用ConfigProvider包裹组件外的, 另一种方法，比如是调用一个方法来改变主题颜色

### What does the proposed API look like?

ConfigProvider.mergedToken({
      colorPrimary: "green",
     ...
})

**Comment by Wxh16144** [comment]
我感觉功能都是一样的，没必要多一个 API。

**Comment by afc163** [comment]
还是使用 ConfigProvider 更符合 React context 的用法心智。
