### ISSUE TITLE
Popover 在 Input textarea下位置出错

### ISSUE THREAD

**Issue by FourKnife** [ant-design/ant-design#4092]
#### 发生问题的环境是：

- antd 版本: 2.3.2
- 操作系统及其版本: 0S X 10.11
- 浏览器及其版本: chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

const { Input, Popover } = antd;

const Context = () => { return(
  <div>
    test
    <div style={{ width: '100px' }}>
      <Popover placement='right' content='hello' arrowPointAtCenter >
        <Input type='textarea'/>
      </Popover>
    </div>
  </div>
);};

ReactDOM.render(<Context />, document.getElementById('container'));

#### 您期待的结果是:

Popover 弹窗位置显示在Input中间,

#### 实际上的结果是:
![image](https://cloud.githubusercontent.com/assets/5261128/20784620/7b4480d0-b7d6-11e6-9e3b-9243256e6339.png)
显示在了input下部，是input高度和位置计算错了？
<!- 如：样式错位了，最好提供截图 -->

#### 可重现的在线演示
http://codepen.io/anon/pen/YpYKQz?editors=001#anon-signup

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.
