### ISSUE TITLE
AutoComplete 组件example 用法不正确  不能让使用者正确使用options field

### ISSUE THREAD

**Issue by MrWangJustToDo** [ant-design/ant-design#40925]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-55qums)

### Steps to reproduce

有两个autocomplete的example，第一个使用了同一个option， 第二个各自有各自的option 。
当一个example的每一个输入框包含不同的内容时，focus后的panel内容会根据option渲染

### What is expected?

文档应该显示option正确的用法

### What is actually happening?

文档中的example使用了同一个option，focus后panel的内容不正确

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | 所有 |
| Browser | 所有 |

**Comment by Yuiai01** [comment]
确实会迷惑使用者
![image](https://user-images.githubusercontent.com/112228030/221409667-000a179a-90c3-4840-8456-3cecbfb5d30c.png)

**Comment by Yuiai01** [comment]
我来完善一下吧~

**Comment by mleister97** [comment]
My really bad solution for this problem:

```
<AutoComplete
 ...
  optionRender={(oriOption) => <span data-id={oriOption.data.id}>{oriOption.label}</span>}
  onClick={(e) => {
    const optionContent = (e.target as HTMLElement).closest('.ant-select-item-option-content')
    if (!optionContent) return
    const span = optionContent.querySelector('span')
    if (!span) return
    const productId = span.getAttribute('data-id')
    if (productId == null) return
    ProductLinesService.onProductSelect(formInstance, fieldName, productId, products, !isTaxEnabled, isIGL)
  }}
/>
```
