### ISSUE TITLE
Ant Design Multiple Select Data Combined

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#40937]
### Reproduction link

[https://9wjl90.csb.app/](https://9wjl90.csb.app/)

### Steps to reproduce

Click more than 1 value in Select
blue selected css missing and icon check missing

### What is expected?

selected css still there

### What is actually happening?

blue selected css missing and icon check missing

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by tempoeric** [comment]
should retain this css
![image](https://user-images.githubusercontent.com/42777871/221495487-ebd78ea6-34c5-4c03-9952-d273a3a81f54.png)

**Comment by tempoeric** [comment]
but if i selected for more than 1 value there is no way to deselect the item

**Comment by zombieJ** [comment]
You can combine 2 Select to handle this. When you modify `value` with `x selected items`, option of course can not be checked.

**Comment by zombieJ** [comment]
One Select for your customize selection. And another with real options.

**Comment by tempoeric** [comment]
@zombieJ  can you provide example please

**Comment by tempoeric** [comment]
i really need an example @zombieJ  on  how to implement this
