### ISSUE TITLE
getFieldDecorator.initialValue值为数组的话使用validateFieldsAndScroll校验会报“xxx need to revalidate”错误。

### ISSUE THREAD

**Issue by xiongran** [ant-design/ant-design#4093]
#### 发生问题的环境是：

- antd 版本: 2.4.2
- 操作系统及其版本:WIN7专业版
- 浏览器及其版本:chrome 50.0.2661.87 m

#### 您做了什么？请提供尽可能详细的重现步骤。
1、我实现的功能是选择及时生效的话仅显示最快生效时间和单位，最晚生效时间和单位隐藏。默认值为0，默认单位为小时，对应initialValue为[0, '1']。
当我选择及时生效的时候，直接提交表单，校验checkEffectiveTime判断是及时生效的话直接callBack()。
![e8c5 tmp](https://cloud.githubusercontent.com/assets/13461531/20785986/3c3d79d4-b7de-11e6-8088-000a8b6aefb4.jpg)
选择及时生效
![df94 tmp](https://cloud.githubusercontent.com/assets/13461531/20786023/7ea6a7e6-b7de-11e6-8a3a-2a66d35184ec.jpg)
2、getFieldDecorator.initialValue赋值为一个数组，比如initialValue: [0, '1']
![71dd tmp](https://cloud.githubusercontent.com/assets/13461531/20785221/057d653e-b7da-11e6-9749-4adb4dde5c75.jpg)
3、选择及时生效的时候，直接提交表单，form.validateFieldsAndScroll校验的时候报错“xxx need to revalidate”，导致FormItem一直处于validating状态。
![88c0 tmp](https://cloud.githubusercontent.com/assets/13461531/20786135/32cea048-b7df-11e6-8c3e-881aa47f2b8d.jpg)  
跟代码发现 nowField.value !== allValues[name] 结果为true， nowField.value和allValues[name]内容相同，都是[0, '1']。
![d8dc tmp](https://cloud.githubusercontent.com/assets/13461531/20785867/7bda022a-b7dd-11e6-8148-d841e52594b6.jpg)
4、如果输入再提交表单则校验通过，nowField.value !== allValues[name] 结果为false。nowField.value和allValues[name]内容相同，都是[1, '1']。
![61a2 tmp](https://cloud.githubusercontent.com/assets/13461531/20786156/56d03650-b7df-11e6-8fdc-f20d9952276c.jpg)

#### 您期待的结果是:
既然已经赋予了默认值[0, '1']，并且验证方法是直接callback()返回，应该校验通过才对。

**Comment by benjycui** [comment]
有重现 demo 最好

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
在 rules 里面设置 `type: 'array'`，see: https://ant.design/components/form/#components-form-demo-register

**Comment by clarkhan** [comment]
@benjycui 这个问题应该是校验过程中，虽然值未改变，但对象被改变（新的引用）问题。

如，项目使用 Immutable 等相关的类。
在方法 `validateFieldsInternal` 中，
```javascript
      validateFieldsInternal(fields, {
        fieldNames,
        action,
        options = {},
      }, callback) {
        const allRules = {};
        const allValues = {};
        const allFields = {};
        const alreadyErrors = {};
        fields.forEach((field) => {
          ...
        });
        this.setFields(allFields);
```
`this.setFields(allFields);`  会触发 onChange。
如果项目使用 redux 存储表单值，且有不可变的机制，如使用 `Immutable` ，则在 form 中通过  `mapPropsToFields` 得到的 value 为新的数组（对象）。   
由于校验异步，在下面代码中的判断条件中一个是新的对象，一个是旧的对象，分支进入异常的处理流程。

```javascript
        validator.validate(allValues, options, (errors) => {
          ...
          Object.keys(allRules).forEach((name) => {
            ...
            if (nowField.value !== allValues[name]) {
              expired.push({
                name,
              });
            } 
          .....
          }
        })
```

所以，将不会通过校验。

建议此处判断条件考虑实现为 deep comparison

**Comment by benjycui** [comment]
> deep comparison

考虑到时间类组件的值是 moment 对象，这个成本太大，暂时保留现状吧。

用变量缓存即可 `const xxxInitialValue = xxx`
