### ISSUE TITLE
<Steps>组件、希望在每条横线之间再添加一个文案

### ISSUE THREAD

**Issue by duzuimoye** [ant-design/ant-design#40939]
### What problem does this feature solve?

很多场景下、用户光看步骤条之间的title可能不太明显、希望能更直接一些

### What does the proposed API look like?

新增一个字段可以用来表示二个步骤条之间的状态

**Comment by zombieJ** [comment]
有示意图么？

**Comment by kiner-tang** [comment]
感觉说得是不是把中间的连接线改成类似`Divider`的线。
![image](https://user-images.githubusercontent.com/10286961/221504579-8161be2c-717e-493f-b332-97f5bc01c3d6.png)
![image](https://user-images.githubusercontent.com/10286961/221504594-66c93d5a-8cff-4d4a-9586-71bd680662bd.png)

**Comment by duzuimoye** [comment]
> 

![image](https://user-images.githubusercontent.com/37163594/221737040-b708d9a8-84db-44e7-8c38-2e825b3deac2.png)
就是图中箭头的一个文案来表示状态

**Comment by afc163** [comment]
状态应该放在节点上，而不是另开一个地方写，这样设计上比较混乱，职责也不清晰。

**Comment by duzuimoye** [comment]
> 状态应该放在节点上，而不是另开一个地方写，这样设计上比较混乱，职责也不清晰。

好吧、那我自己封装一个组件吧
