### ISSUE TITLE
<List.Item.Meta /> title prop wrapps Node with <h4> tag

### ISSUE THREAD

**Issue by amed** [ant-design/ant-design#40945]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-byqcj1)

### Steps to reproduce

Both items (node & string) are wrapped with `<h4>`

### What is expected?

Expected string to have `<h4>` tag, node title have no `<h4>` tag

### What is actually happening?

Node title & string title are wrapped with `<h4>` tag

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | MacOS 13.2.x |
| Browser | Firefox/Chrome |

![image](https://user-images.githubusercontent.com/5637272/221537042-cb9c688d-71c2-40ea-a034-d2c3101d43d6.png)

**Comment by Yuiai01** [comment]
Hello, I feel that the behavior of components should be consistent and should not change depending on what is passed in. 🤔🤔

**Comment by amed** [comment]
@Yuiai01 
Check docs:
https://ant.design/components/list#listitemmeta

`title` is ReactNode, it would make sense not to wrap it with any tag.
Since string is also possible, title can be wrapped with a default tag.

**Comment by zombieJ** [comment]
Since we can not check children node real element on render. We may not support this request. You can follow the structure of title that not using additional `h5` element.

**Comment by amed** [comment]
It is fully understandable that maintaining such a large project is challenging and small fixes can cause large effects. BUT:

@zombieJ we can check children on render:

https://github.com/ant-design/ant-design/blob/059042b2cdcdde663e47d3689d7ec0647fde66b1/components/avatar/avatar.tsx#L175

title prop should not be wrapped with h4 by default if it's a node. It could be the case if type is only string.
