### ISSUE TITLE
tabel中rowSelection设置selectedRowKeys之后，无法改变勾选状态

### ISSUE THREAD

**Issue by wangzengkai** [ant-design/ant-design#4094]
#### 发生问题的环境是：

- antd 版本: 2.50
- 操作系统及其版本: win7
- 浏览器及其版本: chrome 54.0.2840.99 (正式版本) m （32 位）

#### 您做了什么？请提供尽可能详细的重现步骤。
修改数据的时候，希望进入页面时可以默认选中table中的一行数据，然后用户可以取消勾选或者保持勾选状态。

#### 您期待的结果是:
进入修改页面的时候是勾选状态，并且可以随意操作是否勾选。

#### 实际上的结果是:
![image](https://cloud.githubusercontent.com/assets/18696364/20787017/9d5f0010-b7e4-11e6-8b7b-f6266c671b10.png)
点击之后还是无法去掉勾选状态

**Comment by yesmeck** [comment]
设置默认选中项应该用`getCheckboxProps` 给 Checkbox 设置 `checked` 属性。

设置 `selectedRowKeys` 后需要自己控制 `selectedRowKeys`  的变化。

参考：https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-action

**Comment by wangzengkai** [comment]
我也试过这种方法了，可以默认勾选，但是点击之后还是无法去掉勾选状态。

**Comment by yesmeck** [comment]
请给个可重现的例子 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by wangzengkai** [comment]
老师您好，因为在线编译器特别慢，我给您发了一封gmail邮件。谢谢了

**Comment by OneAndOnly1111** [comment]
@yesmeck 你好,也遇到了这种使用selectedRowKeys设置默认之后, 无法勾选其他的情况，能否详细说明下怎么在noChange的时候自控吗？？  （以及希望defaultChecked 支持数组）

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-action

@OneAndOnly1111  道理是一样的。

**Comment by OneAndOnly1111** [comment]
@yesmeck 原来也是通过控制state就行，以为是不一样的，解决了，感谢！

**Comment by roser240** [comment]
`设置默认选中项应该用getCheckboxProps 给 Checkbox 设置 defaultChecked 属性`
请问antd 中table 下面没有defaultChecked 属性可以给补充到api中吗
