### ISSUE TITLE
动态增减表单，点击删除，方法中获取到的是正确的索引，但是实际被销毁的是最后一个表单

### ISSUE THREAD

**Issue by whale-jung** [ant-design/ant-design#40957]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuo-dong-shi-li-antd-5-2-2-forked-uso6f1?file=/AddForm.js)

### Steps to reproduce

点击第一个表单（非最后一个表单）的“删除”按钮，最后一个表单被删除（看表单中字段值）

### What is expected?

删除点击指定 索引的表单

### What is actually happening?

删除的是最后一个表单

| Environment | Info |
| --- | --- |
| antd | 4.20.4 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
有实现删除相应索引表单的方法吗？请教一下这个是什么原因造成的

**Comment by whale-jung** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/80868414/221624486-f38138a4-0b45-42fd-9db5-ff4a0f061450.png">

**Comment by RedJue** [comment]
我看看这是不是个bug

**Comment by whale-jung** [comment]
> 我看看这是不是个bug

好的，感谢

**Comment by RedJue** [comment]
看了下是写法的问题，主要的问题在于 `Ref` 并不是一个常量，所以不能当做唯一值检索。`Ref` 需要固定到 `AddForm` 组件里保证唯一性，每次循环 `RefList` 就导致组件`Ref`被重新赋值，所以按照`index`来排序的话，结果就是最后一个组件会被丢失，我这里写了个正确的例子，你可以参考一下，repo在[这里](https://codesandbox.io/s/tuo-dong-shi-li-antd-5-2-2-forked-i254jv?file=/demo.tsx)。

**Comment by whale-jung** [comment]
> 



> 看了下是写法的问题，主要的问题在于 `Ref` 并不是一个常量，所以不能当做唯一值检索。`Ref` 需要固定到 `AddForm` 组件里保证唯一性，每次循环 `RefList` 就导致组件`Ref`被重新赋值，所以按照`index`来排序的话，结果就是最后一个组件会被丢失，我这里写了个正确的例子，你可以参考一下，repo在[这里](https://codesandbox.io/s/tuo-dong-shi-li-antd-5-2-2-forked-i254jv?file=/demo.tsx)。

这样处理的话怎么实现表单批量提交呢，以及还要实现表单上下移动的需求

**Comment by whale-jung** [comment]
> 

解决了
