### ISSUE TITLE
Tour漫游式引导如何隐藏下面的按钮

### ISSUE THREAD

**Issue by andrew2558** [ant-design/ant-design#40950]
### What problem does this feature solve?

Tour不能隐藏下面按钮的问题

### What does the proposed API look like?

Tour可以控制按钮的显示与隐藏

**Comment by afc163** [comment]
```jsx
nextButtonProps: {
  style: { display: 'none' },
},
prevButtonProps: {
  style: { display: 'none' },
},
```

Try this.

**Comment by andrew2558** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/25080605/221559113-b929c30c-99fb-49fd-b91c-bbf47e1d6b50.png">
谢谢 @afc163 你的回答，我说的是这个上一步与结束的这两个按钮。
你说的nextbuttonprops好像没有这个属性呀

**Comment by kiner-tang** [comment]
> nextbuttonprops

是在`steps`中的，每一个步骤都可以定制按钮的样式

**Comment by andrew2558** [comment]
@kiner-tang 谢谢你的回答，找到了，但似乎最后的那个结束导览的按钮没有设置
最后用了一个最笨的全局样式来隐藏

**Comment by afc163** [comment]
把上一步和下一步去掉还是 Tour 组件么？你需要的是不是 Popover？
