### ISSUE TITLE
Apply color-scheme CSS property to components for light/dark mode

### ISSUE THREAD

**Issue by PhosphorusP** [ant-design/ant-design#40958]
### What problem does this feature solve?

While using theme.darkAlgorithm to apply a dark theme, scrollbars on the page keep in light mode.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/13076466/221631099-aa695ee9-ac95-4b8a-a4d8-7742aba10e59.png">

### What does the proposed API look like?

When a dark theme is used,
```
<ConfigProvider
      theme={{
        algorithm: darkAlgorithm
......
```
the `color-scheme` property is applied to the components.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/13076466/221631288-f6f4dbaa-f87c-4432-a1ab-3e45ef81e289.png">

**Comment by MadCcc** [comment]
You could change `color-scheme` in your application by judging theme of antd.
