### ISSUE TITLE
Tour component in Drawer

### ISSUE THREAD

**Issue by joelcampospi** [ant-design/ant-design#40954]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-spence-pmsle5?file=/src/App.js)

### Steps to reproduce

Create a Drawer component. Then, add a Tour component. When the Tour component gets opened (no matter if its opened by default o by an state update) it sets a gray layer between the Tour "modal" and the app itself. The problem is that when teh Tour is part of a Drawer, the Drawer is positioned on top of the gray layer, so the UI gets very confusing.

### What is expected?

The Drawer should be behing the gray layer (mask).

### What is actually happening?

The Drawer does not appear behind the gray layer.

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox and Edge |

**Comment by kiner-tang** [comment]
let me try to fix it

**Comment by joelcampospi** [comment]
Thanks!
