### ISSUE TITLE
Tooltip（Popconfirm）组件子组件不能有多个或者单个TextElement

### ISSUE THREAD

**Issue by leungwensen** [ant-design/ant-design#4095]
#### 发生问题的环境是：

- antd 版本: 2.4.3
- 操作系统及其版本: MacOS Sierra 
- 浏览器及其版本: Chrome 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

多个子组件：

```jsx
<Tooltip title="prompt text">
    <span>Text will show when mouse enter.</span>
    extra text element
</Tooltip>
```

单个TextElement子组件

```jsx
<Tooltip title="prompt text">
    extra text element
</Tooltip>
```

#### 您期待的结果是:

正常显示tooltip

#### 实际上的结果是:

`index.tsx:128 Uncaught TypeError: Cannot read property 'className' of undefined`

问题的根源在于，Tooltip的实现用到了childNode的属性（直接写了`children.props`），而当childNode不止一个，或者是一个裸的TextElement的时候children是个数组或者字符串，而这两种情况下`children.props`都是取不到的。

问题代码： https://github.com/ant-design/ant-design/blob/master/components/tooltip/index.tsx#L122

#### 可重现的在线演示

* 多个子组件  http://codepen.io/leungwensen/pen/RoxwOM
* 单个Text元素  http://codepen.io/leungwensen/pen/mOpdZK

Popconfirm的情况类似。

**Comment by RaoHai** [comment]
https://github.com/react-component/trigger/blob/master/src/Trigger.jsx#L422 

Tooltip and Popconfirm are both depend on rc-trigger, and it expected to receive a single React element child.

**Comment by RaoHai** [comment]
@benjycui maybe we could update document, or  hoist `React.Children.only` from rc-trigger to Tooltip. Or automatic generate a wrapper element, when Tooltip and Popconfirm receive multiple children.

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/issues/3924
