### ISSUE TITLE
Add a property to Progress component for disabling animation

### ISSUE THREAD

**Issue by PhosphorusP** [ant-design/ant-design#40978]
### What problem does this feature solve?

The Progress component may show wrong progress when frequently updated because of animation.

### What does the proposed API look like?

`<Progress percent={50} size="small" status="active" animate={false} />`

**Comment by afc163** [comment]
How about removing `status="active"`?

**Comment by PhosphorusP** [comment]
> How about removing `status="active"`?

Thanks for replying. Removing `status="active"` only disables the repeating animation of the progress bar, while the animation when updating the `percent` property causes issues. Sometimes the progress bar cannot show corrent progress when `percent` property is frequently updated.

@afc163

**Comment by afc163** [comment]
Could you provide a reproduce?

**Comment by PhosphorusP** [comment]
> Could you provide a reproduce?

A simple example: [https://codesandbox.io/s/dry-framework-i3i4dr](url)

@afc163

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/40056#issuecomment-1373051878
