### ISSUE TITLE
`useFormItemStatus` 在Next.js服务端渲染时会报错

### ISSUE THREAD

**Issue by AndyBoat** [ant-design/ant-design#40976]
### Reproduction link

[https://stackblitz.com/edit/nextjs-9tnoqz?file=pages/index.js](https://stackblitz.com/edit/nextjs-9tnoqz?file=pages/index.js)

### Steps to reproduce

在Next.js的需预渲染的组件中中使用 `useFormItemStatu`

### What is expected?

正常使用

### What is actually happening?

Next服务端渲染时提示:Server Error ReferenceError: window is not defined

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18.2.0 |
| System | MacOSX |
| Browser | Chrome 109 |

**Comment by AndyBoat** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/8624194/221916166-0c620957-6c89-420b-8772-c333bf21e758.png">

**Comment by zombieJ** [comment]
Seems client side work as expect but SSR not get the context:
https://codesandbox.io/s/ji-ben-shi-yong-antd-5-2-2-forked-clljk4?file=/demo.tsx
