### ISSUE TITLE
Type of onChange in the InputNumber shouldn't be a Generics 

### ISSUE THREAD

**Issue by csu-feizao** [ant-design/ant-design#40970]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-keller-47gpbc?file=/src/App.tsx)

### Steps to reproduce

1. Use InputNumber component
2. Define a value with the `string` type
3. Inspect the parameter type of onChange

### What is expected?

The parameter type of onChange should be `string | number | null`

### What is actually happening?

The parameter type of onChange was inferred by the value, which is `string | null`. It may cause serious problems in the user's application. So I think the parameter type of onChange should be fixed, not Generics like `T extends ValueType`

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18 |
| System | win 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
You can config type like this:
```tsx
<InputNumber<string | number>  />
```

Actually it works as expect. If you config the type to `string | number` you will get follow error:
<img width="326" alt="截屏2023-02-28 16 06 51" src="https://user-images.githubusercontent.com/5378891/221791568-8f903139-be53-40e9-9f11-88204d10d1c0.png">
<img width="527" alt="截屏2023-02-28 16 07 16" src="https://user-images.githubusercontent.com/5378891/221791661-5d2f217d-7348-4517-acf7-d1b8b9b9c94d.png">

**Comment by csu-feizao** [comment]
> You can config type like this:
> 
> ```tsx
> <InputNumber<string | number>  />
> ```
> 
> Actually it works as expect. If you config the type to `string | number` you will get follow error: <img alt="截屏2023-02-28 16 06 51" width="326" src="https://user-images.githubusercontent.com/5378891/221791568-8f903139-be53-40e9-9f11-88204d10d1c0.png"> <img alt="截屏2023-02-28 16 07 16" width="527" src="https://user-images.githubusercontent.com/5378891/221791661-5d2f217d-7348-4517-acf7-d1b8b9b9c94d.png">

I know this config would work. But I wonder that why it should be a Generics, is there any reason?
