### ISSUE TITLE
Cascader 组件在 changeOnSelect 和 expandTrigger="hover" 组合使用的时候出bug

### ISSUE THREAD

**Issue by SamChan1204** [ant-design/ant-design#4097]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本:  macOS Sierra 10.12.1
- 浏览器及其版本:  Google Chrome 54.0.2840.98

#### 您做了什么？请提供尽可能详细的重现步骤。

如下使用 Cascader 组件：
```
<Cascader
  options={dimData}
  placeholder="请选择题目所属维度"
  changeOnSelect
  expandTrigger="hover"
  onChange={onChange}/>
```

#### 您期待的结果是:

1、鼠标移入菜单时，展示其子菜单
2、点击菜单时，触发 onChange 回调

#### 实际上的结果是:

鼠标移入非叶子节点菜单时即触发 onChange 回调

#### 可重现的在线演示

[http://codepen.io/sam5712381/pen/yVpyqg?editors=1111](http://codepen.io/sam5712381/pen/yVpyqg?editors=1111)

**Comment by benjycui** [comment]
其实 changeOnSelect 的行为就是 changeOnExpand。

**Comment by afc163** [comment]
这是合理的，`changeOnSelect` 表示非叶子节点的展开会触发 change。`expandTrigger="hover"` 表示 hover 行为会触发展开。
