### ISSUE TITLE
Table expand icon is not following the theme color

### ISSUE THREAD

**Issue by azro352** [ant-design/ant-design#40979]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jribl9?file=/index.js)

### Steps to reproduce

- Use a ConfigProvider and change the token.colorPrimary (to differenciate of the default blue)
- Create a table with expandable rows
- look at the expand-icon color when hovering it

### What is expected?

The color should follow the theme, and be like `theme.colorPrimaryBorderHover` I think

### What is actually happening?

It keeps being its default color, not following the theme

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome |

**Comment by li-jia-nan** [comment]
You shoule set `colorPrimary` and `colorLinkHover` both:

```tsx
return (
  <ConfigProvider
    theme={{
      token: {
        colorPrimary: "#FADB12",
        colorLinkHover: '#FADB12',
      }
    }}
  >
      <Demo />
  </ConfigProvider>
);
```

**Comment by afc163** [comment]
```jsx
return (
  <ConfigProvider
    theme={{
      token: {
        colorPrimary: "#FADB12",
        colorLink: '#FADB12',
      },
    }}
  >
      <Demo />
  </ConfigProvider>
);
```
