### ISSUE TITLE
使用 legacyLogicalPropertiesTransformer ProLayout aside组件submenu样式显示出现问题

### ISSUE THREAD

**Issue by wangs1203** [ant-design/ant-design#40986]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hun-he-dao-hang-forked-7cvtbi?file=/App.tsx)

### Steps to reproduce

收起菜单栏

### What is expected?

menuItem icon 显示正常
<img width="695" alt="image" src="https://user-images.githubusercontent.com/26623688/222037847-33487948-43ca-4196-8496-8ffc5e8010c0.png">

### What is actually happening?

menuItem icon 显示异常
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/26623688/222037612-096ca5b0-da1a-4627-9deb-310e1e843b67.png">

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | window 11, macos 12.3.1  |
| Browser | chrome 107.0.5304.121 |

**Comment by wangs1203** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/26623688/222038655-26309ad5-ffaf-40ba-a80b-979d79227859.png">

**Comment by zombieJ** [comment]
我瞅瞅

**Comment by wangs1203** [comment]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/26623688/222041647-e0af78fc-3a80-42f5-90f0-8b8f9adc1a84.png">

**Comment by Airkro** [comment]
Same problem when using @ant-design/cssinjs@1.6.1

![image](https://user-images.githubusercontent.com/12206891/222407572-d6e572ab-b5fe-45f7-afb0-3266d78cebd4.png)

**Comment by Ryuurock** [comment]
@zombieJ 瞅完了吗，这个问题好像一直没修？
