### ISSUE TITLE
table 组件使用Table.EXPAND_COLUMN，会在某一列的前面多出展开收起，如何让展开收起位于某一列正下方

### ISSUE THREAD

**Issue by yangxf1854** [ant-design/ant-design#40981]
### What problem does this feature solve?

某一列展开收起

### What does the proposed API look like?

使用Table.EXPAND_COLUMN，可以在正下方展示展开收起
![image](https://user-images.githubusercontent.com/33971031/222078861-c33e483b-c3ae-49c4-aacc-4240ca2aab17.png)

**Comment by yangxf1854** [comment]
已找到其他办法解决掉了

**Comment by wxingheng** [comment]
> 已找到其他办法解决掉了

怎么解决的，我有类似的需求，可以指点一下吗？

**Comment by yangxf1854** [comment]
![image](https://user-images.githubusercontent.com/33971031/234549541-fb35c006-e4ac-4e51-9cfb-ce8c588ebf35.png)
我是加了这两个属性
