### ISSUE TITLE
Using Row and Col in List Item destroys divider line per item

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#40997]
### Reproduction link

[https://vfsf2g.csb.app/](https://vfsf2g.csb.app/)

### Steps to reproduce

Just click the link and when the data has loaded you could see that the divider line per item is cut per each column

### What is expected?

should have a straight line divider

### What is actually happening?

broken line is displaying

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2.0 |
| System | Mac OS Ventura 13.1 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-list-antd-undefined-forked-mm8hud?file=/demo.tsx
