### ISSUE TITLE
select - onSelect hook 将全部选中值也作为参数传回 (if multiple)

### ISSUE THREAD

**Issue by haoxins** [ant-design/ant-design#410]

**Comment by yiminghe** [comment]
用 onChange

**Comment by haoxins** [comment]
用户输入会触发 onChange

**Comment by yiminghe** [comment]
multiple 用户输入不会触发 onChange

**Comment by haoxins** [comment]
0.9.1中 multiple 下, 用户输入确实触发 onChange, **而且也需要**. (`最好能将用户输入作为单独参数传入`)

使用场景是 搜索选择(多选), 并且根据用户输入自行筛选.

所以希望能在 onSelect 得到全部选中值, 因为 onChange 时难以剔除用户输入.

**Comment by yiminghe** [comment]
使用 http://react-component.github.io/select/examples/force-suggest.html 模式
