### ISSUE TITLE
Unable to select text  in the popover if it is rendered as suffixIcon component inside Cascader

### ISSUE THREAD

**Issue by weihe8892** [ant-design/ant-design#41007]
### Reproduction link

[https://stackblitz.com/edit/react-fsfjxe-j38osi?file=demo.tsx,index.tsx](https://stackblitz.com/edit/react-fsfjxe-j38osi?file=demo.tsx,index.tsx)

### Steps to reproduce

Hover over the "info" icon on the left side (before text "Zhejiang") ,a popover will be shown, try to select any text in popover and nothing happened. It is not working since 4.16.11 and 5.x.x versions

### What is expected?

Be able to select text and copy it to other places. It worked in older version 4.16.10 and prior, here is an example of workable version: https://stackblitz.com/edit/react-cydsvy?file=index.tsx,index.css,demo.tsx 

### What is actually happening?

Unable to select text. 

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.2 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
suffix 包东西，容易被组件内部的事件处理影响。如果一定要用的话，加个阻止哈：

https://stackblitz.com/edit/react-fsfjxe-wtddkj?file=demo.tsx,index.tsx

**Comment by weihe8892** [comment]
@zombieJ , thanks a lot!  I tried stopPropagation in onClick, now I know should be onMouseDone. Thanks again!
