### ISSUE TITLE
使用Typescript，Input组件报style为必填。

### ISSUE THREAD

**Issue by BoizZ** [ant-design/ant-design#4100]
#### 发生问题的环境是：

- antd 版本: 1.11.4
- 操作系统及其版本: win7 x64 专业版
- 浏览器及其版本: Chrome 54.0.2840.99 m (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

``` ts
import * as React from 'react'
import { Input } from 'antd'

interface IAppProps {}
interface IAppState {}

class App extends React.Component<IAppProps, IAppState> {
    public render(): JSX.Element {
        return <Input type='text' placeholder='hello world' />
    }
}

export default App
```

#### 您期待的结果是:

应该这么写没问题...

#### 实际上的结果是:

```
file: 'file://.../App.tsx'
severity: '错误'
message: 'Property 'style' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & InputProps & { children?: ReactNode; }'.'
at: '40,11'
source: 'ts'
```

**Comment by afc163** [comment]
antd@1.x 未提供官方的 TypeScript type definitions，建议升级。

**Comment by BoizZ** [comment]
npm install antd 默认安装1.x，建议修复。

**Comment by afc163** [comment]
<img width="469" alt="image" src="https://cloud.githubusercontent.com/assets/507615/20798520/0b1286f6-b81a-11e6-9768-976400a79a5b.png">

现在默认安装应该是 2.5.0。

**Comment by BoizZ** [comment]
好的，那估计是我的命令打错了，谢谢~
