### ISSUE TITLE
TimePicker.RangePicker onBlur v4.24.8 do not have target.value

### ISSUE THREAD

**Issue by komarovalexander** [ant-design/ant-design#41018]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5xlhc5?file=/index.js)

### Steps to reproduce

TimePicker.RangePicker onBlur v4.24.8 do not have input value but in v4.23.6 it is there

open: https://codesandbox.io/s/antd-reproduction-template-forked-ly94ee?file=/index.js see that there are logged values for each input onBlur in the console

open: https://codesandbox.io/s/antd-reproduction-template-forked-5xlhc5?file=/index.js see that values are empty after each input onBlur

### What is expected?

behavior of v4.23.6 is correct.
after each onBlur input must have value 

### What is actually happening?

input value is empty in v4.24.8 

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by komarovalexander** [comment]
I found that  rc-picker "~2.7.0" is causing the issue, if I change this library version to rc-picker "~2.6.11" TimePicker.RangePicker works correctly

**Comment by Wxh16144** [comment]
Thank you for providing the address that accurately describes the problem.

I took a look at the history. It was done intentionally inside this https://github.com/ant-design/ant-design/pull/38411

But it is not the case in version 5.x.

**Comment by komarovalexander** [comment]
it is strange because if you set rc-picker "~2.6.11" as a dependency to v4.24.8 -  it will work as it should. 

what is the best way to hide ok button and set the value on onBlur event now?
I used advices from there https://github.com/ant-design/ant-design/issues/21189 but seems none of them will work now

we do not have plans to migrate to version 5 at this time
thanks!

**Comment by zombieJ** [comment]
Why using `onBlur` to get input value instead of `onChange` get parsed date value?

**Comment by komarovalexander** [comment]
@zombieJ answer is simple: without "ok" button `onChange` does not work at all: https://codesandbox.io/s/antd-reproduction-template-forked-x6lrcm?file=/index.js

**Comment by zombieJ** [comment]
It's a XY problem.  We should support this requirement.

merge into #21189

**Comment by komarovalexander** [comment]
@zombieJ do you have any estimations when this https://github.com/ant-design/ant-design/issues/21189  will be fixed for range picker in v4.x?
