### ISSUE TITLE
allowClear button on Select component isn't showing up 

### ISSUE THREAD

**Issue by jordykoppen** [ant-design/ant-design#4101]
Currently I'm experiencing a ¿bug? with the Select component.
I filled a Select box with the "multiple" property and set allowClear={true}.
Yet the all clear button doesn't show up.

<Select
multiple
        style={{ width: '100%' }}
        placeholder={this.props.placeholder}
        onChange={(value) => this.props.handleChange(value, this.props.filterName)}
        allowClear={true}
        size="large">

Am i doing something wrong or is this a bug?

Thanks!

**Comment by afc163** [comment]
Sorry for typo in Select API, `allowClear` is only working in single mode.

**Comment by jordykoppen** [comment]
Thanks for your response. If i may ask, why is allowClear only working in single mode? Wouldn't it make more for it to work only in multiple mode?

**Comment by afc163** [comment]
Because you can always remove selected items in multiple Select by close `x`, which is a clear button.

**Comment by jordykoppen** [comment]
Ah i see.. 
Although it would be nice to be able to clear all the values at once by clicking the clear button.
