### ISSUE TITLE
当tour漫游引导组件配合form form.item使用的时候报错

### ISSUE THREAD

**Issue by bulai0408** [ant-design/ant-design#41012]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-higjrr?file=/index.js)

### Steps to reproduce

只需要进入重现链接就可以看到

### What is expected?

没有报错，tour配合form正常使用

### What is actually happening?

TypeError
Cannot read properties of undefined (reading 'createElement')

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | ^18.2.0 |
| System | macos 13.1 |
| Browser | 版本 110.0.5481.177（正式版本） (arm64) |

**Comment by kiner-tang** [comment]
我来看看

**Comment by kiner-tang** [comment]
看起来是获取`ref`的方式不对，你可以这样获取：
https://codesandbox.io/s/antd-reproduction-template-forked-5twjef?file=/index.js

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-0errsc?file=/index.js
通过 `ref.current.input` 获取 Input 的 dom 元素。

**Comment by bulai0408** [comment]
> 看起来是获取`ref`的方式不对，你可以这样获取： https://codesandbox.io/s/antd-reproduction-template-forked-5twjef?file=/index.js

thanks
