### ISSUE TITLE
list item of Checkbox.Group style for vertical layout

### ISSUE THREAD

**Issue by muh-hizbe** [ant-design/ant-design#41027]
### What problem does this feature solve?

Cause in may case when i add className="flex flex-col gap-1" using tailwind utilities, list of checkbox after index 0 there a margin left. Link image preview:

![image](https://user-images.githubusercontent.com/37175249/222616156-4e81af6b-59cd-43a4-910b-1188f7024e7b.png)

### What does the proposed API look like?

Maybe it's look very cool if this component have many props for layouting the checkbox list, like:

- layout='vertical'|'horizontal'
- display='flex'|'grid'
- col=number (when display is grid)

**Comment by MadCcc** [comment]
Do you mean https://ant.design/components/checkbox#components-checkbox-demo-layout ?

**Comment by bombillazo** [comment]
How can we use this when passing options? Do we have to manage the rendering ?
