### ISSUE TITLE
InputNumber's parser returns a TS error when setting up min or max

### ISSUE THREAD

**Issue by m3c-ode** [ant-design/ant-design#41025]
### Reproduction link

[https://snipboard.io/Yt56Fn.jpg](https://snipboard.io/Yt56Fn.jpg)

### Steps to reproduce

Create a form with a Form.Item and an Input Number as such: 

```
    <Form.Item
                    label="Expected ABV"
                    name="abv"
                    // wrapperCol={{ span: 1 }}
                    labelAlign='left'
                    labelCol={{ span: 12 }}
                >
                    <InputNumber
                        min={0.1}
                        // max={20}
                        formatter={(value) => `${value}%`}
                        parser={(value) => value!.replace('%', '')}
                        step={0.1} placeholder={'5.0%'} />
       </Form.Item>

```

### What is expected?

No error should be returned. InputNumber expects numbers as `min` and /or `max`, and it should work with the parser prop.

### What is actually happening?

The error showm in this case is: 

`Type '(value: string | undefined) => string' is not assignable to type '(displayValue: string | undefined) => 0.1'.
  Type 'string' is not assignable to type '0.1'.ts(2322)`

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2   |
| System | Windows 11 |
| Browser | Firefox |

**Comment by MadCcc** [comment]
`parser` should return a `number` value.

**Comment by MadCcc** [comment]
https://codesandbox.io/s/ji-chu-chou-ti-antd-5-2-2-forked-bseqnm?file=/demo.tsx
Could be a workaround.

**Comment by m3c-ode** [comment]
Thank you!
