### ISSUE TITLE
Modals are not following theme from ConfigProvider

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#41020]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crop-image-before-uploading-antd-undefined-forked-u3gxro)

### Steps to reproduce

Click on buttons and see modal colors.
Upload any image and see modal title

### What is expected?

All modals should follow ConfigProvider theme

### What is actually happening?

Some modals are not following ConfigProvider theme but one is

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | React ^18.0.0 |
| System | MacOS and CodeSandbox |
| Browser | Chrome 108.0.5359.124 |

**Comment by nonam4** [comment]
Some extra info:

As git bot suggested, I've looked those issues but I didn't find anything about image cropper modal

**Comment by MadCcc** [comment]
Static methods could't get context provided by ConfigProvider. Please use hooks or App instead.
Ref: https://ant.design/components/config-provider#why-cant-configprovider-props-like-prefixcls-and-theme-affect-reactnode-inside-messageinfo-notificationopen-modalconfirm

**Comment by nonam4** [comment]
> Static methods could't get context provided by ConfigProvider. Please use hooks or App instead. Ref: https://ant.design/components/config-provider#why-cant-configprovider-props-like-prefixcls-and-theme-affect-reactnode-inside-messageinfo-notificationopen-modalconfirm

Ok, but how about image cropper? There's nothing in docs about using it with hooks

**Comment by MadCcc** [comment]
ImgCrop is maintained by community，you could open issue in that repo.

**Comment by nonam4** [comment]
> ImgCrop is maintained by community，you could open issue in that repo.

oh, thanks
I tought it was maintened by antd :sweat_smile::sweat_smile:
