### ISSUE TITLE
Space设置vertical时顶部有额外的空白

### ISSUE THREAD

**Issue by MorningK** [ant-design/ant-design#41026]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/chui-zhi-jian-ju-antd-undefined-forked-gyyh3l)

### Steps to reproduce

在展示组件内使用Space组件且设置Space的direction为vertical，此时展示组件顶部会有额外的空白出现

### What is expected?

展示组件没有额外的空白

### What is actually happening?

展示组件顶部会有额外的空白出现

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18 |
| System | MacOS |
| Browser | chrome 109.X |

---
设置Space的style的display为flex可以解决这个问题，建议direction为vertical时默认设置display为flex

**Comment by zombieJ** [comment]
Space 设定就是 `inline-flex`，可以额外添加样式 `verticalAlign` 对齐，或者按你说的 `flex` 对齐。但是本身 `display` 不会改成 `flex`，这样就不能实现 inline 效果了（同时也是个 break change）：
https://codesandbox.io/s/chui-zhi-jian-ju-antd-undefined-forked-zi46hi?file=/demo.tsx
