### ISSUE TITLE
Could not resolve "rc-util/es/hooks/useMobile"，node_modules/rc-input-number/es/StepHandler.js:6:22:    ，import useMobile from "rc-util/es/hooks/useMobile";

### ISSUE THREAD

**Issue by youjia727** [ant-design/ant-design#41030]
### What problem does this feature solve?

本地运行失败，node_modules/rc-input-number/es/StepHandler.js中import useMobile from "rc-util/es/hooks/useMobile"，rc-util/es/hooks文件夹缺少useMobile文件

### What does the proposed API look like?

添加useMobile文件

**Comment by yoyo837** [comment]
删除node_modules和lock文件, 重新安装试一下
