### ISSUE TITLE
select 中包含宽度较长的选项，开启搜索，选择后再输入出现宽度不正常

### ISSUE THREAD

**Issue by Eviwang** [ant-design/ant-design#41035]
### Reproduction link

[https://stackblitz.com/edit/react-jdpmec?file=demo.tsx](https://stackblitz.com/edit/react-jdpmec?file=demo.tsx)

### Steps to reproduce

选择后，再输入时出现宽度计算不正常

### What is expected?

正常展示

### What is actually happening?

宽度不正常

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18.0.28 |
| System | windows |
| Browser | 110.0.5481.178 (正式版本) |

**Comment by Yuiai01** [comment]
确实是个 bug，我来修复一下~

**Comment by Yuiai01** [comment]
看了一下感觉是 select 组件的默认行为，如果想要限定 select 组件的宽度可以直接设置 select 组件的宽度~

**Comment by Eviwang** [comment]
这不是bug？

**Comment by MadCcc** [comment]
默认行为，与其 antd 帮用户设置宽度不如用户自己来更灵活？

**Comment by Eviwang** [comment]
问题是默认打开是有宽度的，输入之后就没宽度了，得保持一致吧？

**Comment by Eviwang** [comment]
@zombieJ

**Comment by MadCcc** [comment]
自行设置一下宽度可以么

**Comment by MadCcc** [comment]
另外可以配合 `dropdownMatchSelectWidth={false}` 使用
