### ISSUE TITLE
Anchor 和 react router 的 hashHistory 冲突应该如何解决

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#4104]
#### 发生问题的环境是：

- antd 版本:ant design 2.5.1
- 操作系统及其版本:windows7 旗舰版
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

Anchor 和 react router 的 hashHistory 冲突
因为 react router  是使用#关键字来定位路由
Anchor 组件使用# 关键字定位锚点。
导致报错

![qq 20161202103300](https://cloud.githubusercontent.com/assets/6470398/20821101/c9b02540-b87a-11e6-9280-7834768cdfbe.png)

**Comment by bang88** [comment]
这个不是`antd`的问题，但是你可以看看这里的讨论 https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604

**Comment by bang88** [comment]
@eddyzhang1986  你是怎么使用的。

**Comment by eddyzhang1986** [comment]
@bang88 说来，我这个需求是有点变态我使用react router  + 锚点 
先用react router 的路由 导航，这时候的路由链接地址 是 http://xxxxxx/#getnews
然后我 用 锚点控件 定位 ,结果发现 链接地址 变为 http://xxxxx/#anchor1.
此时右键点击刷新,然后出的问题 ,目前我认为这个 不能算是 BUG,也不需要解决，当然如果能有类似
http://xxxxxx/#getnews@anchor1 这类地址具体定位  哪个路由的哪个 锚点似乎更好点，但是如果这么设计必然会引发很多问题，比如参数怎么取之类的，所以我觉得，我暂时也不需要处理这个问题。

**Comment by benjycui** [comment]
其实 react-router 推荐也是 browserHistory，为什么要执着 hashHistory

**Comment by bang88** [comment]
主要为了兼容ie9吧
