### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by bowenWeb** [ant-design/ant-design#41046]
### Reproduction link

[https://ant.design/docs/react/i18n-cn](https://ant.design/docs/react/i18n-cn)

### Steps to reproduce

import zhCN from 'antd/locale/zh_CN';资源找不到
应该是 import zhCN from 'antd/lib/locale/zh_CN';

### What is expected?

国际化文档修改为  import zhCN from 'antd/lib/locale/zh_CN';

### What is actually happening?

import zhCN from 'antd/locale/zh_CN';

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | react |
| System | windows |
| Browser | 谷歌 |

---
文档写错啦

**Comment by MadCcc** [comment]
https://unpkg.com/browse/antd@5.2.3/locale/zh_CN.js
检查一下本地的 antd 版本？文件是存在的。
