### ISSUE TITLE
样式编辑器设置 message 的 colorText 属性后不生效

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design#41041]
### Reproduction link

[https://ant.design/theme-editor-cn#Anchor-Props](https://ant.design/theme-editor-cn#Anchor-Props)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/12181423/222658341-d5f59401-5f19-48d7-96f1-55df05ccfa39.png)

### What is expected?

![image](https://user-images.githubusercontent.com/12181423/222659605-243c8764-bbea-41be-90c5-e0d8e4d240e2.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/12181423/222658380-6b821495-3393-4c3c-852c-82c1fd38bbdb.png)

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | "react": "^18.2.0", |
| System | Mac OS 11.7.2 (20G1020) |
| Browser | Google Chrome  版本 109.0.5414.87（正式版本） (x86_64) |

**Comment by Yuiai01** [comment]
我来尝试修复一下~
