### ISSUE TITLE
如何获取Upload 批量上传是否全部上传完成的状态

### ISSUE THREAD

**Issue by 1769762790** [ant-design/ant-design#41052]
### What problem does this feature solve?

在Modal里创建Form 表单， 此时批量上传多个文件，部分上传成功，还有其他文件正在上传中，接口还没返回数据，此时点击提交按钮需要判断批量上传的文件是否已全部上传完成，否则提交会丢失还在上传中的数据，但是接口还会继续上传。

### What does the proposed API look like?

提供监听开始上传和上传结束的方法

**Comment by kiner-tang** [comment]
使用`onChange`不能达到你的目的吗？
https://ant.design/components/upload-cn#onchange

**Comment by 303394539** [comment]
我想他的意思应该是选择多文件同时上传以后，在异步的情况下，怎么在所有的文件都完成的时机组件有一下反馈。如果是直接用onChange，由于onChange是所有状态都会回调，他得自己记录多文件的状态来判断。

**Comment by MadCcc** [comment]
可以通过 `onChange` 来封装这一个功能
