### ISSUE TITLE
onFieldsChange会出发两次

### ISSUE THREAD

**Issue by pangao66** [ant-design/ant-design#41051]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/36bh64)

### Steps to reproduce

```
  <Form
      onFieldsChange={()=>{
      console.log('bbb')} // 这里每次表单项更改都会触发两次
      }
    >
      <Form.Item
        label="Username"
        name="username"
        rules={[{ required: true, message: 'Please input your username!' }]}
      >
        <Input />
      </Form.Item>
    </Form>
```

### What is expected?

触发一次

### What is actually happening?

触发两次

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18 |
| System | mac |
| Browser | edge |

**Comment by kiner-tang** [comment]
我看看

**Comment by idler8** [comment]
https://ant.design/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%AD%97%E6%AE%B5%E8%AE%BE%E7%BD%AE-rules-%E5%90%8E%E6%9B%B4%E6%94%B9%E5%80%BC-onfieldschange-%E4%BC%9A%E8%A7%A6%E5%8F%91%E4%B8%89%E6%AC%A1
预期变化

**Comment by kiner-tang** [comment]
> https://ant.design/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%AD%97%E6%AE%B5%E8%AE%BE%E7%BD%AE-rules-%E5%90%8E%E6%9B%B4%E6%94%B9%E5%80%BC-onfieldschange-%E4%BC%9A%E8%A7%A6%E5%8F%91%E4%B8%89%E6%AC%A1 预期变化
> 
> > 为什么字段设置 rules 后更改值 onFieldsChange 会触发三次？
> > 字段除了本身的值变化外，校验也是其状态之一。因而在触发字段变化会经历以下几个阶段：
> > Trigger value change
> > Rule validating
> > Rule validated
> > 在触发过程中，调用 isFieldValidating 会经历 false > true > false 的变化过程。
文档里面说会触发三次，但实测却触发了2次，我们正在确认是文档老旧还是程序异常

**Comment by idler8** [comment]
变化应该出在这里
https://github.com/react-component/field-form/commit/55de0f372323f064759b2fc510af5cea0c32507f
加油

**Comment by zombieJ** [comment]
Update. 测试了一下现在的确是两次，在校验时原 forceUpdate 被合并了。需要再看一下具体原因。

**Comment by zombieJ** [comment]
确认了一下是漏了一次，这在 redux 下状态就错了。居然一直没人报，看来 redux 场景已经基本没了。。。

**Comment by yuanzhaoK** [comment]
https://codesandbox.io/s/biao-dan-shu-ju-cun-chu-yu-shang-ceng-zu-jian-antd-5-4-4-forked-hvlvyx?file=/demo.tsx:632-646
会被触发三次

<img width="1827" alt="image" src="https://user-images.githubusercontent.com/124442084/233416363-de3312ac-33f4-4624-9a0a-950dbd7e358f.png">
