### ISSUE TITLE
TimePicker required click before scroll

### ISSUE THREAD

**Issue by krivochenko** [ant-design/ant-design#41059]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js)

### Steps to reproduce

1. Click input field
2. Try to scroll to select value which initially not visible (hours, minutes...)

### What is expected?

Expected to be scrolled

### What is actually happening?

Firstly user has to click some of visible value, to be able to scroll to hidden one.

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18.1.0 |
| System | Android |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
@krivochenko Hello, the link you provided did not reproduce the problem, could you please provide a link to reproduce the problem you described?

**Comment by krivochenko** [comment]
> @krivochenko Hello, the link you provided did not reproduce the problem, could you please provide a link to reproduce the problem you described?

I don't know why sandbox reset my changes. Just change DatePicker to TimePicker. Also you can check it in docs page.

**Comment by krivochenko** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-shbgpo?file=/index.js

**Comment by Yuiai01** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-shbgpo?file=/index.js

I tried to reproduce the question, but I seem to be able to scroll without clicking, and you can watch this video I recorded.

https://user-images.githubusercontent.com/112228030/222940742-cf805b16-c218-49be-8831-88f4f1e70694.mov

**Comment by krivochenko** [comment]
It looks like a desktop. But my issue on Android. Sorry, maybe I confused you by saying "click" instead of "tap".

**Comment by Yuiai01** [comment]
> It looks like a desktop. But my issue on Android. Sorry, maybe I confused you by saying "click" instead of "tap".

Ok, if you want to run it on mobile, I recommend using it [Ant Design Mobile](https://mobile.ant.design).

**Comment by krivochenko** [comment]
But my app used on different platforms, and it's not good idea to support two different layouts just because unexpected behaviour of one component.

**Comment by Yipee-ki-yay** [comment]
I've fixed that issue by enabling the scroll on the devices with the mobile size:

`
  .ant-time-picker-panel .ant-time-picker-panel-select {
    ...
    overflow-y: auto;

    @media (min-width: 1024px) {
      overflow: hidden;
    }
  }
`

**Comment by oluwatobiiloba** [comment]
> I've fixed that issue just in the css by enabling the scroll on the devices with the mobile size:
> 
> ```
> .ant-time-picker-panel .ant-time-picker-panel-select {
>     overflow-y: auto;
> 
>     @media (min-width: 1024px) {
>       overflow: hidden;
>     }
>   }
> ```

Hi @Yipee-ki-yay , I can't seem to get this to work even with the css provided. Any tips?

**Comment by daytwoat** [comment]
@oluwatobiiloba 
this fixed it

`.ant-picker-time-panel-column){
    overflow-y: scroll !important;
}`

**Comment by IEatPrayLove** [comment]
![rc-picker](https://github.com/user-attachments/assets/bf17e79e-303c-4db9-94ad-bb71c3a4395e)
调试发现，当点击li节点之后，会一直执行doScroll
![rc-picker-01](https://github.com/user-attachments/assets/e0d5866a-6db8-4532-8225-5f11842cd4bd)

**Comment by jaydeep911** [comment]
> [@oluwatobiiloba](https://github.com/oluwatobiiloba) this fixed it `.ant-picker-time-panel-column{ overflow-y: scroll !important; }`

This works thanks
