### ISSUE TITLE
onValuesChange 收集到的数据不准确

### ISSUE THREAD

**Issue by loo41** [ant-design/ant-design#41053]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-flower-8jnwx6?file=/src/App.tsx)

### Steps to reproduce

使用 form.list 组件，使用 add 方法添加 2 个元素，在使用 remove 方法删除 1 个元素，使用 onValuesChange 的第二个参数收集数据，fields 数组依然存在 2 个元素，被删除的元素在 fields 的下标位置存在为 undefined

### What is expected?

我理解的 onValuesChange 第二个参数收集数据，如复现步骤操作，被删除元素的在 onValuesChange 收集到的数据下标中不应该存在，

### What is actually happening?

被删除的元素在 fields 的下标位置存在为 undefined

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by loo41** [comment]
我看了一下，感觉大概的情况是调用 remove 之后 onVauleChange 方法调用之前没有执行 unRegisterField，导致 this.fieldEntities 还是未移出前的数据，只有当 componentWillUnmount 声明周期起作用的时候 this.fieldEntities  才是最新的数据，所以 onVauleChange 和直接调用 getFieldsValue 拿到的结果不一致

**Comment by Ali-ovo** [comment]
看了一下这个组件的源码引用了rc的 rc-field-form 组件 
我要怎么才能帮忙修改rc的组件呢，目前是发现了在antd的源码中貌似无法修复这个bug

**Comment by yoyo837** [comment]
PR 发到 `rc-field-form`, 关联此issue即可

**Comment by Ali-ovo** [comment]
> PR 发到 `rc-field-form`, 关联此issue即可

在 `rc-field-form` 项目中 `复现该bug` 十分复杂 
复现该bug 必须使用 Antd 的 `Form.Item` 这个 包装的控件 的 **name 属性** 来变成 **被表单控件所控制的状态**才能复现
但是 `rc-field-form` 并没有  `Form.Item`  这个包装控件

**Comment by yoyo837** [comment]
不明白你啥意思, 你先到上游提交PR , 发版本, 然后再来antd改

**Comment by yoyo837** [comment]
两边都是同一个团队的仓库

**Comment by Ali-ovo** [comment]
> 不明白你啥意思, 你先到上游提交PR , 发版本, 然后再来antd改

就是在 `rc-field-form` 这个库中无法复现这个bug， 因为这个bug依赖了 Antd 的 `Form.Item` 组件才可以复现
但是在  `rc-field-form`  库中没有这个组件

**Comment by Francoshum95** [comment]
Can I have a try in this issue 

> > 不明白你啥意思, 你先到上游提交PR , 发版本, 然后再来antd改
> 
> 就是在 `rc-field-form` 这个库中无法复现这个bug， 因为这个bug依赖了 Antd 的 `Form.Item` 组件才可以复现 但是在 `rc-field-form` 库中没有这个组件

You need to go to the [rc-field-form](https://github.com/react-component/field-form) repository, and find `src/List.tsx`.  You can take a look at `const operations = {add: ..., remove: ...}`

**Comment by Ali-ovo** [comment]
> > > 不明白你啥意思, 你先到上游提交PR , 发版本, 然后再来antd改
> > 
> > 
> > 就是在 `rc-field-form` 这个库中无法复现这个bug， 因为这个bug依赖了 Antd 的 `Form.Item` 组件才可以复现 但是在 `rc-field-form` 库中没有这个组件
> 
> You need to go to the [rc-field-form](https://github.com/react-component/field-form) repository, and find `src/List.tsx`. You can take a look at `const operations = {add: ..., remove: ...}`

However, this bug can only be reoccurrence by relying on `Antd Input component `. Cant  reoccurrence in `rc-field-form`

**Comment by kiner-tang** [comment]
> > > > 不明白你啥意思, 你先到上游提交PR , 发版本, 然后再来antd改
> > > 
> > > 
> > > 就是在 `rc-field-form` 这个库中无法复现这个bug， 因为这个bug依赖了 Antd 的 `Form.Item` 组件才可以复现 但是在 `rc-field-form` 库中没有这个组件
> > 
> > 
> > You need to go to the [rc-field-form](https://github.com/react-component/field-form) repository, and find `src/List.tsx`. You can take a look at `const operations = {add: ..., remove: ...}`
> 
> However, this bug can only be reoccurrence by relying on `Antd Input component `. Cant reoccurrence in `rc-field-form`

You can fork both of `antd` and `rc-field-form`,then fix this bug in `rc-field-form` and link it into `antd` to check it.
![image](https://user-images.githubusercontent.com/10286961/223894451-6d9dcaf1-6bda-4558-9fbd-32d75f765fcd.png)
![image](https://user-images.githubusercontent.com/10286961/223894473-d436857b-8e2f-4bb2-a610-1453a52de822.png)

**Comment by Ali-ovo** [comment]
> > > > > 不明白你啥意思, 你先到上游提交PR , 发版本, 然后再来antd改
> > > > 
> > > > 
> > > > 就是在 `rc-field-form` 这个库中无法复现这个bug， 因为这个bug依赖了 Antd 的 `Form.Item` 组件才可以复现 但是在 `rc-field-form` 库中没有这个组件
> > > 
> > > 
> > > You need to go to the [rc-field-form](https://github.com/react-component/field-form) repository, and find `src/List.tsx`. You can take a look at `const operations = {add: ..., remove: ...}`
> > 
> > 
> > However, this bug can only be reoccurrence by relying on `Antd Input component `. Cant reoccurrence in `rc-field-form`
> 
> You can fork both of `antd` and `rc-field-form`,then fix this bug in `rc-field-form` and link it into `antd` to check it. ![image](https://user-images.githubusercontent.com/10286961/223894451-6d9dcaf1-6bda-4558-9fbd-32d75f765fcd.png) ![image](https://user-images.githubusercontent.com/10286961/223894473-d436857b-8e2f-4bb2-a610-1453a52de822.png)

Wow, amazing

**Comment by zombieJ** [comment]
发现是 field 数据没填进去：https://codesandbox.io/s/floral-platform-zujs63

**Comment by nirvana-for-ever** [comment]
<Form.Item {...field} name={...}>...</Form.Item>
貌似这样就行?
