### ISSUE TITLE
Antd Pagination should be able to customize display for showSizeChanger

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#41069]
### Reproduction link

[https://w71z3p.csb.app/](https://w71z3p.csb.app/)

### Steps to reproduce

just click the link and see page options

### What is expected?

should only display
10 items
20 items
50 items

### What is actually happening?

displaying 10 items/page

/page should be removed

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 18.2.0 |
| System | Mac OS Ventura 13.1 |
| Browser | Google Chrome |

**Comment by tempoeric** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/42777871/222957656-e9adea2f-ae37-42fc-bd10-2ce756b10206.png">

should also be able to configure showSizeChanger position like in the image

**Comment by Wxh16144** [comment]
> displaying 10 items/page
> 
> /page should be removed

The display content can be modified by modifying the multilingual text.

![image](https://user-images.githubusercontent.com/32004925/222968794-5df8939f-bce8-41da-b6aa-1a29cf93ba51.png)

**Comment by tempoeric** [comment]
thanks @Wxh16144 how about moving the sizeChanger to left?
