### ISSUE TITLE
Breadcrumb配合react-router使用，不支持browserHistory

### ISSUE THREAD

**Issue by BriefGuo** [ant-design/ant-design#4106]
#### 发生问题的环境是：

- antd 版本:2.5.0
- 操作系统及其版本:Debian 8
- 浏览器及其版本:Chrome 54.0.2840.100

#### 您做了什么？请提供尽可能详细的重现步骤。
引用了antd的Breadcrumb，并配合react-router使用

react-router我配置的history是browserHistory，这是我的入口main.js对react-router的配置
```jsx
/*...*/

ReactDOM.render(
  <Router history={browserHistory} routes={routes}/>,
  document.getElementById('root')
);
```
结合antd的官方文档

> 和 react-router@2.x 进行结合使用。
https://ant.design/components/breadcrumb/

而这时候我在浏览器里查看面包屑的dom的时候，发现a标签的href为是带有“#”的，让我无法跳转到准确页面。

所以我臆测这里所谓的结合react-router使用，是不是只支持hashHistory而不支持browserHistory。

我把browserHistory换成hashHistory是可以正常使用的，但是我觉得是不是Breadcrumb组件需要一个属性手动来适应不同的history，或者能兼容browserHistory。

#### 您期待的结果是:

我觉得Breadcrumb组件需要一个属性手动来适应不同的history，或者直接能兼容browserHistory。

#### 实际上的结果是:

当react-router设置为browserHistory，面包屑仍是按照hashHistory的方式生成的，导致我不能正确的跳转

**Comment by afc163** [comment]
用 itemRender 自行配置链接。

**Comment by BriefGuo** [comment]
$B9%E*(B??$B!$(B?$B@'WL46(B???

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B12$B7n(B4$BF|!$2<8a(B3:18$B!$JP1&(B <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B


Closed #4106<https://github.com/ant-design/ant-design/issues/4106>.

-
