### ISSUE TITLE
Input.Group size=large or size=small is not honored for the button

### ISSUE THREAD

**Issue by armpogart** [ant-design/ant-design#41078]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w13m6t?file=/index.js)

### Steps to reproduce

Create a compact `Input.Group` size set to 'large' or 'small' with one input and one button in it.

### What is expected?

It is expected that the `size` modifier on input group will be honored by buttons inside it.

### What is actually happening?

The sizes 'large' and 'small' are not applied to the button in `Input.Group`. If the size is set to 'large' manually on button, the border radiuses will be incorrect, and input and button will look separate.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | Windows 10 build 19045 |
| Browser | Microsoft Edge 110.0.1587.57 |

**Comment by kiner-tang** [comment]
let me have a look

**Comment by Yuiai01** [comment]
@armpogart  Hello, the size configured on input. Group only applies to the internal input. You can take a look at this.https://ant.design/components/input#inputgroup

**Comment by kiner-tang** [comment]
@armpogart why not use `Input.Search`? Like this: https://ant.design/components/input-cn#components-input-demo-search-input

**Comment by armpogart** [comment]
@kiner-tang Cause it's not a search actually, and I have custom icon in instead of text in the button. As far as I see I can't set custom icon for `Search` input and also control when the button (only button not the input) is disabled or not.

**Comment by armpogart** [comment]
@Yuiai01 I see, but it's not stated in the examples section explicitly, where the example with button is shown. Also why not to apply it to internal buttons, or at least honor the border radiueses when the button in input.group has explicitly set the size?

**Comment by kiner-tang** [comment]
> @kiner-tang Cause it's not a search actually, and I have custom icon in instead of text in the button. As far as I see I can't set custom icon for `Search` input and also control when the button (only button not the input) is disabled or not.

why not? you can pass custom ReactNode into `enterButton`, see this: 
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/10286961/223004065-bb83f1ba-080b-4508-808a-83d3997367c9.png">

**Comment by armpogart** [comment]
@kiner-tang So you mean I can pass `<Button icon={...} />` directly there? That will solve the problem, but it will be still not intuitive to use `Search` for getting something completely not search related, so I'm not sure why not to support the sizing for internal buttons.

**Comment by kiner-tang** [comment]
> @kiner-tang So you mean I can pass `<Button icon={...} />` directly there? That will solve the problem, but it will be still not intuitive to use `Search` for getting something completely not search related, so I'm not sure why not to support the sizing for internal buttons.

why not just pass a icon? like this:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/10286961/223007051-15da923e-7a5c-460b-b5c9-152733a06c05.png">

**Comment by armpogart** [comment]
@kiner-tang How do I enable/disable the button in that case? I need a way to control whether the button is enabled.

**Comment by zombieJ** [comment]
We should update doc here. Since Space.Campact is the replacement of Input.Group:
https://codesandbox.io/s/antd-reproduction-template-forked-kxdmwn?file=/index.js
