### ISSUE TITLE
Form feedback icon not showing if the input has valid value while using validateFields method

### ISSUE THREAD

**Issue by manikandanm1757** [ant-design/ant-design#41084]
### Reproduction link

[https://stackblitz.com/edit/react-nspdpm?file=demo.tsx](https://stackblitz.com/edit/react-nspdpm?file=demo.tsx)

### Steps to reproduce

1. Run the stackblitz demo
2. Check the input boxes with valid and invalid email values.
3. Feedback shows for invalid input only

### What is expected?

I'm expecting feedback icon (success/error) should show for both valid or invalid values while validating the form if the Form.Item has 'hasFeedback' prop as true

### What is actually happening?

error feedback icon only showing while using validateFields method, success feedback not showing in input while using the validateFields method. Success feedback icon rendering when start changing the value in input.

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 17 |
| System | Stackblitz |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Hmmm... call `validateFields` should also trigger success. Strange.

**Comment by manikandanm1757** [comment]
Is this fix will be included in 4.x version?
