### ISSUE TITLE
upload图片上传为什么预览改成用a链接了呢？

### ISSUE THREAD

**Issue by Vantown** [ant-design/ant-design#41087]
### What problem does this feature solve?

一个不用打开新标签页了，再就是现在的微应用，就比如你们的钉钉市场的微应用，一点预览直接掉浏览器了，这种操作体验给用户很不好

### What does the proposed API look like?

期望能通过api控制像image组件那样预览，如果有用户需要渲染a标签预览的话，通过api参数控制

**Comment by MadCcc** [comment]
文件上传的 `url` 一直都是下载地址，同时照片墙也有图片预览的功能。可否详细描述一下你的需求？

**Comment by Vantown** [comment]
> 文件上传的 `url` 一直都是下载地址，同时照片墙也有图片预览的功能。可否详细描述一下你的需求？

那可能是v4版本我们没注意到，是最近更到v5以后用户提的，我们是crm系统，比如新建单据页面上传的产品图片，传完了以后要看预览图片，或者产品更新迭代了需要更换单据里的产品图片，我们表单里有个字段是个图片字段，只能上传图片，用户更换产品图片的时候就会点预览，我们还有自定义表单，用户可以通过表单拖拽往里拖图片上传组件，这些都会涉及到预览功能，再比如合同里签署的合同等信息放在图片上传里传上去，上传完了也会有用户点大图预览看看效果，而且如果像Image组件那样预览的话，放大缩小和旋转都有，也在同一个页面不会让用户的操作产生割裂感，像现在钉钉里的微应用，我们一个组件用户可以传多张图片，每点一张都跳到浏览器的话这种操作体验不是太好

**Comment by MadCcc** [comment]
先直接使用图片墙类型呢，图片墙的预览可以考虑直接换成 Image 组件相同的。普通上传兼顾所有类型的文件预览不太好做的。

**Comment by Vantown** [comment]
> 先直接使用图片墙类型呢，图片墙的预览可以考虑直接换成 Image 组件相同的。普通上传兼顾所有类型的文件预览不太好做的。

用户反馈的时候我们是临时改成用Modal弹窗预览了，我看你们图片墙的预览也是用的Modal预览，可能这种要比Image组件要差一些，或者Image组件可以做到像Modal弹窗那样的Modal.method()调用也可以，可以直接调用预览方法然后往里传个图片数组加current能实现吗？就像钉钉手机端微应用sdk里自带的dd.biz.util.previewImage那样

**Comment by zombieJ** [comment]
列表可以用 `itemRender` 自定义的：
https://4x-ant-design.antgroup.com/components/upload-cn/#components-upload-demo-drag-sorting
