### ISSUE TITLE
Initial Values for `Checkbox` and `Switch` do not render `truthy` inside of `Form` component

### ISSUE THREAD

**Issue by kevinreber** [ant-design/ant-design#41093]
### Reproduction link
[https://stackblitz.com/edit/react-7nohyc?file=demo.tsx](https://stackblitz.com/edit/react-7nohyc?file=demo.tsx)

### Steps to reproduce
When assigning a Form components `initialValues` prop, the `initialValues` for `<Checkbox />` and `<Switch />` are not being rendered as expected.

For example, if the initial value for a `<Checkbox />` component is `true`, the `<Checkbox />` will render as `false`, but the components value will be `true`.
![CleanShot 2023-03-06 at 08 15 30@2x](https://user-images.githubusercontent.com/42260999/223171105-20304c5f-b83b-4f2e-864f-96307a4e938b.png)

Code snippet
```tsx
import React from 'react';
import './index.css';
import { Checkbox, Form, Switch, Button, Card, Input } from 'antd';

const handleSubmit = (values: any) => {
  console.log(values);  // 🟡 `values={ checkbox: true, input: "hello world", switch: true}`
};

const App: React.FC = () => {
  return (
    <Card>
      <Form
        onFinish={handleSubmit}
        //  🟡 Assign a Forms `initialValues`
        initialValues={{ 
          input: 'hello world', 
          switch: true,    //  🟡 < -- Switch initial value is `true`
          checkbox: true     //  🟡 < -- Checkbox initial value is `true`
        }}
      >
        <Form.Item label="Input" name="input">
          <Input />
        </Form.Item>
        <Form.Item label="Checkbox" name="checkbox">   //  🟡 < -- `checkbox` initial value is `true`, but UI renders as `false`
          <Checkbox />
        </Form.Item>
        <Form.Item label="Switch" name="switch">   //  🟡 < -- `switch` initial value is `true`, but UI renders as `false`
          <Switch />
        </Form.Item>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form>
    </Card>
  );
};

export default App;
```

### What is expected?
I was expecting the `<Checkbox />` and `<Switch />` component to render "checked" or "unchecked" based on the initial value they are assigned.

I'd expect the both components to behave similar as an `<Input />` component when assigned an initial value. 
If I assign a Form's `initialValues` of an `<Input />` component as `"hello world"`, I would see `"hello world"` inside of the `<Input />` component

### What is actually happening?
The `Form` `initialValues` for `<Checkbox />` and `<Switch />` are assigned as expected, but not rendering as expected in the UI.

I believe there may be some missing html attributes within the `Checkbox` and `Switch` components when they are assigned an initial value within a `Form` component.

See screenshot for example
![CleanShot 2023-03-06 at 08 29 21@2x](https://user-images.githubusercontent.com/42260999/223174241-58e02567-ba19-4a1a-97f7-f5caf862c0bf.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | macOS Ventura 13.2.1 |
| Browser | Google Chrome v110.0.5481.100 |

**Comment by notverysalty** [comment]
use valuePropName to solve
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/50540241/223307923-0913abe0-21e2-45da-bd35-b3551ee5529f.png">

**Comment by kevinreber** [comment]
@notverysalty  Awesome, thanks so much! That's exactly what I needed 😄 🙌
Sorry for the false issue!
