### ISSUE TITLE
Rule validateTrigger onBlur not working

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#41091]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-undefined-forked-zs4dfm?file=/demo.tsx)

### Steps to reproduce

Change input data and blur input or change to another field

### What is expected?

The rule should be executed when the actual input loses its focus

### What is actually happening?

It's only validating when submiting the form

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | React ^18.2.0 |
| System | MacOS and CodeSandbox |
| Browser | Chrome 108.0.5359.124 |

---
Should be nice to add types to validateTrigger instead of only type `string | string[]`
It should have all available trigger options

**Comment by MadCcc** [comment]
`validateTrigger` in `rules` must be the sub set of `validateTrigger` in Form.Item.
Ref: https://ant.design/components/form#rule

**Comment by nonam4** [comment]
> `validateTrigger` in `rules` must be the sub set of `validateTrigger` in Form.Item. Ref: https://ant.design/components/form#rule

Yes yes, I got that...
But validating `onBlur` is not working. `onChange` (default) and `onSubmit` is working fine.

It should be nice if you set the `validateTrigger` type too instead of just leaving it as `string | string[]`. Every component has defined types, e.g.: Buttons... if I want to change button type for example, when I type `type='....'` VSCide intelisense shows all available type options but with `validateTrigger` type as `string | string[]` this doesn't helps because we have to guess what type is going there and if we type it wrong TS will not throw any error... This could lead to a hard to find error.

Hope you take all of this information in consideration to reopen this issue because I always read all the documentation and spend a lot of time testing every possibility before opening issues

**Comment by nikzanda** [comment]
I agree with @nonam4, it would be easier to type validateTrigger with `onChange | onSubmit | onBlur` etc… for a better understanding of the code and to avoid making mistakes such as typos.

**Comment by sorcara-max** [comment]
Why close this issue? so what is the sub set of `validateTrigger` in `Form.Item`? find noting in docs.

**Comment by baohouse** [comment]
> Why close this issue? so what is the sub set of `validateTrigger` in `Form.Item`? find noting in docs.

Here is an example:

```
<Form.Item
  name="phoneNumber"
  label="Phone number"
  validateTrigger={['onChange', 'onBlur']}
  rules={[
    { required: true, validateTrigger: 'onChange' },
    { validator() => {}, validateTrigger: 'onBlur' },
  ]}
>
```

Make sure you list all trigger types covered by all your rules into the `validateTrigger` prop, and then for each rule, specify the `validateTrigger` attribute that you want to assign to that rule. This is what is meant by rule.validationTrigger being a subset of FormItem.validateTrigger.
