### ISSUE TITLE
TreeSelect自定义fieldNames导致告警

### ISSUE THREAD

**Issue by LydiaAgute** [ant-design/ant-design#41092]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0uvfux?file=/index.js)

### Steps to reproduce

见重现链接，使用treeData数据作为TreeSelect组件的数据源，且treeData中指定了key。修改为自定义fieldNames后，如果新指定了value和key不一致，控制台会显示报警

### What is expected?

不应对自定义fieldNames产生报警，或者应当允许在fieldNames指定key值

### What is actually happening?

控制台报警：Warning: `key` or `value` with TreeNode must be the same or you can remove one of them. key: 1, value: 0101.

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 17.0.2 |
| System | windows11 |
| Browser | edge 版本 110.0.1587.63 (正式版本) (64 位) |

**Comment by MadCcc** [comment]
`key` 和 `value` 保持一致，留一个就可以了。可以按照报错修改下？

**Comment by LydiaAgute** [comment]
> `key` 和 `value` 保持一致，留一个就可以了。可以按照报错修改下？
问题在于treeData是后台返回的，数据结构里是携带了值相同的key和value的，我不太好修改。在不指定fieldNames时使用完全正常，但是fieldNames一旦指定就会出现key和value不一致。能否在不修改数据的前提下解决报错？比如支持fieldNames指定key值？

**Comment by LydiaAgute** [comment]
> `key` 和 `value` 保持一致，留一个就可以了。可以按照报错修改下？

问题在于treeData是后台返回的，数据结构里是携带了值相同的key和value的，我不太好修改。在不指定fieldNames时使用完全正常，但是fieldNames一旦指定就会出现key和value不一致。能否在不修改数据的前提下解决报错？比如支持fieldNames指定key值？

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-305os6?file=/index.js
看看这样是不是符合你的需求？

**Comment by LydiaAgute** [comment]
是的，希望TreeSelect能够实现这种效果。像是Tree组件就支持在fieldNames中对key进行配置

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月7日 17:52
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ant-design/ant-design] TreeSelect自定义fieldNames导致告警 (Issue #41092)


https://codesandbox.io/s/antd-reproduction-template-forked-305os6?file=/index.js
看看这样是不是符合你的需求？

―

**Comment by zombieJ** [comment]
key 和 value 不一致 warning 是预期行为，`key` 是 React 保留关键字所以 antd 上也不提供 mapping 的方式。如果真的无所谓这个 warning 的话，可以 webpack alias `rc-util` 的 warning 过滤掉。或者 treeData 做一个预处理把数据清洗一下哈。
