### ISSUE TITLE
select combobox 输入框高度问题

### ISSUE THREAD

**Issue by zengze** [ant-design/ant-design#4110]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本: mac
- 浏览器及其版本: chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

```
<Form inline>
            <FormItem label="遥测站地址">
              <Select style={{ width: 120 }} combobox>
                <Option value="全部">全部</Option>
              </Select>
            </FormItem>
            <FormItem label="遥测站地址">
              <Input style={{ width: 120 }} />
            </FormItem>
</Form>
```

#### 实际上的结果是:
error_1---------------
![error_001](https://cloud.githubusercontent.com/assets/20620151/20827627/2ba459fa-b8ae-11e6-967c-b0f4389b2d9f.png)

error_2---------------

![error_002](https://cloud.githubusercontent.com/assets/20620151/20827628/2be2e526-b8ae-11e6-98d4-50a6df1350fe.png)

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zengze** [comment]
@afc163  刚才代码没出来

**Comment by afc163** [comment]
提供一个可重现的演示。

**Comment by zengze** [comment]
这个上面正常-.-

**Comment by afc163** [comment]
尝试升级或重新安装 antd，我怀疑你本地的 antd 版本并非 2.5.0。

**Comment by afc163** [comment]
没进一步反馈就关了，有问题再 reopen。
