### ISSUE TITLE
Cascade 实现选择任意项的选择器

### ISSUE THREAD

**Issue by NotFound403** [ant-design/ant-design#41106]
### What problem does this feature solve?

很多时候我们并不会选择到最终节点，比如 选择省市县    到省一级或者市一级就结束了    目前多选的级联选择器好像必须选择整个链条

### What does the proposed API look like?

期望实现类似的效果  https://tdesign.tencent.com/react/components/cascader#%E9%80%89%E6%8B%A9%E4%BB%BB%E6%84%8F%E4%B8%80%E9%A1%B9%E7%9A%84%E7%BA%A7%E8%81%94%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by MadCcc** [comment]
参照 https://ant-design.antgroup.com/components/cascader-cn#components-cascader-demo-change-on-select

**Comment by MadCcc** [comment]
多选本身就支持这种能力 https://ant-design.antgroup.com/components/cascader-cn#components-cascader-demo-change-on-select

**Comment by NotFound403** [comment]
@MadCcc  感谢回复  是我提问漏了一些信息，单选目前是支持的，但是多选不支持`changeOnSelect `， 未来是否有支持的计划呢？ 感觉这个特性多选下的场景也挺多的。目前使用了替代方案实现，不够优雅

**Comment by afc163** [comment]
多选感觉用 TreeSelect 更合适一点，在 Cascader 上交互上比较复杂，用户也比较难懂。
