### ISSUE TITLE
button组件的下边为什么有一个阴影，看起来很突兀

### ISSUE THREAD

**Issue by niudoss** [ant-design/ant-design#41102]
### Reproduction link

[https://ant.design/components/button-cn#%E8%AE%BE%E8%AE%A1%E6%8C%87%E5%BC%95](https://ant.design/components/button-cn#%E8%AE%BE%E8%AE%A1%E6%8C%87%E5%BC%95)

### Steps to reproduce

无重现步骤

### What is expected?

无

### What is actually happening?

去除

| Environment | Info |
| --- | --- |
| antd | 5.2.1 |
| React | 17.0.2 |
| System | window mac |
| Browser | 谷歌浏览器110.0.5481.177 |

**Comment by zombieJ** [comment]
投影可以通过自定义主题去除：
https://ant.design/docs/react/customize-theme-cn
