### ISSUE TITLE
打开和关闭Modal弹框时，页面滚动条会自动跳到顶部

### ISSUE THREAD

**Issue by Ading163** [ant-design/ant-design#41112]
### Reproduction link

[https://4x-ant-design.antgroup.com项目页面无法提供](https://4x-ant-design.antgroup.com项目页面无法提供)

### Steps to reproduce

点击打开关闭 visible 通过redux状态控制

### What is expected?

为什么页面滚动条会自动跳到顶部

### What is actually happening?

解决此问题

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 17.0.2 |
| System | windows10 |
| Browser | 谷歌浏览器 |

**Comment by candy4290** [comment]
我这里项目中也用了，不存在你说的问题呢，最好提供一个最小复现链接，来直接展示你的问题

**Comment by wcmboy** [comment]
我也存在这个问题，用的最新版本5.10
