### ISSUE TITLE
Form是否有紧凑型布局

### ISSUE THREAD

**Issue by hornetbillow** [ant-design/ant-design#4111]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by afc163** [comment]
`<FormItem style={{ marginBottom: 8 }}></FormItem>` 可以覆盖 FormItem 的 margin 来实现。

**Comment by Nokecy** [comment]
表单验证 提示 可否使用Tooltip实现？ 现在的提示放在控件下面比较占用空间

**Comment by xiaohulu** [comment]
期望支持使用 tooltip 显示校验信息

**Comment by Crown1991** [comment]
期望支持使用 tooltip 显示校验信息

**Comment by ellisonLou** [comment]
vue的element在form上可以配置size，直接可以控制form里面输入框、按钮等组件的高度，还可以控制表单里面上下组件的间隔。对于需要比较有效率地展示很有用，希望antd也加入紧凑型表单的功能。

**Comment by afc163** [comment]
@ellisonLou 快有了。https://github.com/ant-design/ant-design/issues/17570

cc @zombieJ
