### ISSUE TITLE
Anchor 锚点使用 getCurrentAnchor 设置默认高亮的锚点后，无法触发 onChange

### ISSUE THREAD

**Issue by yangrenmu** [ant-design/ant-design#41118]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-mao-dian-gao-liang-antd-4-24-8-forked-m7lp8x?file=/demo.tsx:236-244)

### Steps to reproduce

使用 getCurrentAnchor 设置默认高亮的锚点，同时使用 onChange 监听锚点的变化，会发现滚动时候，无法触发 onChange。

### What is expected?

使用 getCurrentAnchor 设置默认高亮锚点的同时，滚动时候可以触发 onChange 更新高亮的锚点。

### What is actually happening?

滚动时候无法触发 onChange，高亮的锚点一直是 getCurrentAnchor 设置的默认高亮锚点。

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`getCurrentAnchor` 是自定义高亮锚点，所以设置该值后，相当于告诉 Anchor 无论如何滚动始终高亮 `#one`，自然就不会触发 `onChange` 了。

使用 `getCurrentAnchor` 就需要自行实现 anchor 的 active 逻辑了哈。

**Comment by yangrenmu** [comment]
https://github.com/ant-design/ant-design/pull/30601，看到以前有这个功能，很好用的，没了，可惜了
