### ISSUE TITLE
Input 组件 TextArea添加删除按钮， 文字太多会遮挡住删除按钮

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#41125]
### Reproduction link

[https://ant.design/components/input-cn#inputtextarea](https://ant.design/components/input-cn#inputtextarea)

![image](https://user-images.githubusercontent.com/67216143/223679947-a5ac3ae8-5458-4889-8cfb-55fceaf2348d.png)

### Steps to reproduce

官网demo即可复现

### What is expected?

文字不遮挡删除按钮

### What is actually happening?

文字遮挡了

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | React17/18 |
| System | Mac |
| Browser | chrom |

**Comment by MuxinFeng** [comment]
padding-left 多给点？

**Comment by Ali-ovo** [comment]
> 

感觉这种组件自己提供的功能选项出现的bug 应该组件自己内部处理掉比较好， 外部用css来覆盖有点奇怪

**Comment by MuxinFeng** [comment]
> > 
> 
> 感觉这种组件自己提供的功能选项出现的bug 应该组件自己内部处理掉比较好， 外部用css来覆盖有点奇怪

嗯嗯，我是提个 pr 的思路，看看维护者咋说

**Comment by MadCcc** [comment]
clearIcon 是 absolute 的，让文字区域 padding 也会显得右边比较空。需要更好的设计。

**Comment by Ali-ovo** [comment]
我准备提一个pr， 我当用户设置了 `allowClear` 属性的时候加上 `右padding`，大概是这个样子
![image](https://user-images.githubusercontent.com/67216143/223902661-ac384df7-fda3-45f5-9067-0d413c0559e3.png)

不知道合不合适

**Comment by Ali-ovo** [comment]
> clearIcon 是 absolute 的，让文字区域 padding 也会显得右边比较空。需要更好的设计。

我准备提一个pr， 我当用户设置了 `allowClear` 属性的时候加上 `右padding`，大概是这个样子
![image](https://user-images.githubusercontent.com/67216143/223902661-ac384df7-fda3-45f5-9067-0d413c0559e3.png)

不知道合不合适

**Comment by MadCcc** [comment]
PR welcome
