### ISSUE TITLE
Tree组件展开、收缩动画消失

### ISSUE THREAD

**Issue by boiboif** [ant-design/ant-design#41120]
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-bnejex?file=package.json](https://stackblitz.com/edit/vitejs-vite-bnejex?file=package.json)

### Steps to reproduce

npm create vite@latest
pnpm add antd
使用antd文档中Tree组件第一个例子

### What is expected?

Tree组件展开、收缩动画消失

### What is actually happening?

Tree组件展开、收缩有动画动画效果

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome 103.0.5060.134 |

**Comment by MadCcc** [comment]
Maybe bug with Vite.

**Comment by ZZZCNY** [comment]
+1，用的cra

**Comment by acyza** [comment]
> Maybe bug with Vite.

[vite demo](https://stackblitz.com/edit/vitejs-vite-fpvwzs?file=src%2Fmain.tsx)
[webpack demo](https://stackblitz.com/edit/react-egucsg?file=index.tsx)
看样子和`<React.StrictMode>`有关。

**Comment by ZZZCNY** [comment]
打包完也有这个问题

**Comment by acyza** [comment]
好像严格模式下，动画还没开始就在这调用`onMotionEnd`清除掉了。https://github.com/react-component/tree/blob/master/src/MotionTreeNode.tsx#L62
