### ISSUE TITLE
Tabs items key 错误

### ISSUE THREAD

**Issue by Matrix-The-One** [ant-design/ant-design#41129]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-3-0-forked-5bh2bh?file=/demo.tsx)

### Steps to reproduce

key值不符合document.querySelector语法时

### What is expected?

正常渲染

### What is actually happening?

出现document.querySelector语法错误
![image](https://user-images.githubusercontent.com/63146237/223756493-935d6116-fdb2-434a-b215-3bb8e98ee1b2.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.0.2 |
| System | window |
| Browser | 110 |

---
rc-tabs 底层依赖问题 https://github.com/react-component/tabs/blob/81f004d7ea59b37dd5950b86ee5995d9036ea39a/src/TabNavList/index.tsx#L314

**Comment by Yuiai01** [comment]
querySelector 应该本身就不支持这种参数作为选择条件。

**Comment by MadCcc** [comment]
当前我们使用 `querySelector` 来查询子节点，`key` 中避免使用 `"` 可以解决这个问题。
