### ISSUE TITLE
Why verification is triggered by "submit"

### ISSUE THREAD

**Issue by SongJuXin** [ant-design/ant-design#41132]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-undefined-forked-g2xh1i?file=/demo.tsx)

### Steps to reproduce

key code:
1. Set validateTrigger of Form.Item  to "onBlur"
2. Set validateTrigger of Form.Item.rules[]  to "onBlur"

operate step:
1. Open Link
2. Open terminal
3. Click "submit" button
4. Check terminal output."expect triggered by onBlur,not submit! " is showed.

### What is expected?

The submit action does not trigger the validator.

### What is actually happening?

The submit action  trigger the validator.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.0.0 |
| System | mac |
| Browser | 111.0.5563.64 |

**Comment by zombieJ** [comment]
It's by design. `submit` is final enter point of form submit. It's meaningless the form only validate on event but not care in submit. If you don't want this, just modify button type to `button`:
https://codesandbox.io/s/basic-usage-antd-undefined-forked-0vhqxe
