### ISSUE TITLE
form行内组件(inline)，在单独设置部分表单组件宽度后，展示label于组件换行，显示异常，4.22.0版本以下均无问题。4.22.0以上至最新的5.x都有这个问题

### ISSUE THREAD

**Issue by itkui** [ant-design/ant-design#41136]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-l1uiri?file=/index.js)

### Steps to reproduce

必现问题，设置表单组件宽度后，label与选择表单换行

### What is expected?

Inline 布局下，正常一行展示，与4.21.x一致

### What is actually happening?

inline布局下，错位了

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 16.14.0 |
| System | mac/window |
| Browser | 所有 |

---
bug引入原因应该是4.22.0解决“修复 Form.Item 在快速切换校验状态时高度抖动的问题”造成的。主要原因是因为在FormItem中增加了一层div，导致一个布局css没有应用上
components/form/FormItem/ItemHolder.tsx 增加了一层div
components/form/style/inline.less 
.@{form-prefix-cls}-item {
    flex-wrap: nowrap;  // 属性失效
}

**Comment by MuxinFeng** [comment]
我试试提个 pr 吧~

**Comment by zombieJ** [comment]
4.21.x: https://codesandbox.io/s/antd-reproduction-template-forked-wr9v71?file=/index.js
<img width="738" alt="截屏2023-03-09 14 52 05" src="https://user-images.githubusercontent.com/5378891/223943463-635292d6-f9e6-469f-9104-8519d6e3ded4.png">


<img width="730" alt="截屏2023-03-09 14 52 14" src="https://user-images.githubusercontent.com/5378891/223943512-e6a89908-8def-47e8-9f1d-d30c7266a02f.png">

**Comment by itkui** [comment]
我准备自己提个pr
