### ISSUE TITLE
Cascader组件在设置expandTrigger为hover时，如果悬停到没有下级菜单的一个一级菜单上，不会隐藏之前显示的其它一级菜单的二级菜单

### ISSUE THREAD

**Issue by wangzhengbo** [ant-design/ant-design#41134]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-3-0-forked-s8zx1f?file=/demo.tsx:1002-1015)

### Steps to reproduce

1. 鼠标hover到Zhejiang上，会显示Hangzhou二级菜单；
2. 鼠标hover到beijing上，由于beijing没有children，且设置了isLeaf为true，所以没有二级菜单，但是没有隐藏Hangzhou二级菜单；
3. expandTrigger属性设置为click(默认值)时，没有上述问题

### What is expected?

在设置expandTrigger为hover时，如果悬停到没有下级菜单的一个一级菜单上，会隐藏之前显示的其它一级菜单的二级菜单

### What is actually happening?

在设置expandTrigger为hover时，如果悬停到没有下级菜单的一个一级菜单上，不会隐藏之前显示的其它一级菜单的二级菜单

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome 111 |

---
具体应该是https://github.com/react-component/cascader/blob/e7b6d156f6f3e303d4f7e1a81575a9abbb3be382/src/OptionList/Column.tsx中的

```javascript
const triggerOpenPath = () => {
            if (!disabled && (!hoverOpen || !isMergedLeaf)) {
              onActive(fullPath);
            }
};
```

方法中，对于leaf节点，限制了!hoverOpen时才生效。

**Comment by Wxh16144** [comment]
让我来看看该应该怎么修复

**Comment by Wxh16144** [comment]
已经在 `5.3.1` 中修复~

**Comment by wangzhengbo** [comment]
> 已经在 `5.3.1` 中修复~

多谢。麻烦问下修复会合并到4.x版本中吗？

**Comment by Wxh16144** [comment]
> 会合并到4.x版本中

瞟了一眼，4.x 依赖的 rc-cascader 版本差了 2 个 minor，我需要检查一下能否升级。

**Comment by wangzhengbo** [comment]
> > 会合并到4.x版本中
> 
> ~瞟了一眼，4.x 依赖的 rc-cascader 版本差了 2 个 minor，我需要检查一下能否升级。~
> 
> 更新：4.x 版本在 `antd >= 4.23.2` 包含修复

多谢，辛苦了。

**Comment by kashtian** [comment]
> > 会合并到4.x版本中
> 
> ~瞟了一眼，4.x 依赖的 rc-cascader 版本差了 2 个 minor，我需要检查一下能否升级。~
> 
> 更新：4.x 版本在 `antd >= 4.23.2` 包含修复

看了下，antd 4.x 并未修复该问题呢

**Comment by Wxh16144** [comment]
> 目前看，antd4.x 仍未修复该问题

需要重新安装 antd, 注意检查 lock 文件. 如果还存在问题可以帮助我们提供一个复现仓库, 感谢~

**Comment by afc163** [comment]
@kashtian 清了 lock 文件重新安装即可。需要底层依赖更新到 rc-cascader@3.7.2 。

**Comment by kashtian** [comment]
@Wxh16144 我发现 antd 官方提供的 cdn 包也有问题，https://cdnjs.cloudflare.com/ajax/libs/antd/4.24.8/antd-with-locales.js

**Comment by afc163** [comment]
@kashtian 试试 4.24.9

**Comment by kashtian** [comment]
> ```js
> triggerOpenPath
> ```

4.24.9 可以的，多谢

**Comment by kashtian** [comment]
> @kashtian 试试 4.24.9

4.24.9 可以的，多谢
