### ISSUE TITLE
Grid 使用xs sm响应式时，sm offset 0 不会覆盖 xs offset 非0

### ISSUE THREAD

**Issue by VanChans** [ant-design/ant-design#41142]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zuo-you-pian-yi-antd-5-3-0-forked-nk4kw7?file=/demo.tsx)

### Steps to reproduce

栅格响应式既出现 offset 0 又出现其他的值 (offset 非0)

### What is expected?

满足相应屏幕宽度的offset number生效

### What is actually happening?

满足相应屏幕宽度的offset numner 不生效

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 17.0.2 |
| System | macos 11.4 |
| Browser | chrome 112.0.5596.2 |

**Comment by MadCcc** [comment]
在多少宽度下可以复现？

**Comment by VanChans** [comment]
> 

例子中屏幕宽度大于992 就可以

**Comment by VanChans** [comment]
> 在多少宽度下可以复现？

例子中屏幕宽度大于992 就可以

**Comment by Yuiai01** [comment]
我来解决一下～
