### ISSUE TITLE
Warning: [antd: Breadcrumb] `Breadcrumb.Item and Breadcrumb.Separator` is deprecated. Please use `items` instead. 

### ISSUE THREAD

**Issue by brayanjeshua** [ant-design/ant-design#41147]
### Reproduction link

[https://4x.ant.design/components/breadcrumb/](https://4x.ant.design/components/breadcrumb/)

### Steps to reproduce

My component works very well but I'm having this warning in the console. I've tried to resolve it with the new syntax in the page but is not working. Seems is not correct the documentation or anything else.

### What is expected?

-

### What is actually happening?

My component works very well but I'm having this warning in the console. I've tried to resolve it with the new syntax in the page but is not working. Seems is not correct the documentation or anything else.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | Linux, Mac,Windows |
| Browser | Chrome |

---

```tsx
import React from 'react';
import { Breadcrumb, Col, Row } from 'antd';
import { NavLink, useLocation } from 'react-router-dom';

const capitalizeChar = (str) => {
  return str.charAt(0).toUpperCase()   str.slice(1);
};

/**
 * This component uses react-router-dom
 * (should be used inside a Provider)
 */
const Breadcrumbs = () => {
  const location = useLocation();
  const pathSnippets = location.pathname.split('/').filter((i) => i);
  const breadcrumbItems = pathSnippets.map((snippet, index) => {
    const url = `/${pathSnippets.slice(0, index   1).join('/')}`;
    const title = snippet.replace(/-/g, ' ');
    return (
      <Breadcrumb.Item key={url}>
        <NavLink to={url}>{capitalizeChar(title)}</NavLink>
      </Breadcrumb.Item>
    );
  });

  return (
    <>
      <Row>
        <Col className="flex items-center gap-2 p-4">
          <Breadcrumb>
            <Breadcrumb.Item>
              <NavLink to="/">Home</NavLink>
            </Breadcrumb.Item>
            {breadcrumbItems}
          </Breadcrumb>
        </Col>
      </Row>
    </>
  );
};

export { Breadcrumbs };
```

**Comment by brayanjeshua** [comment]
https://codesandbox.io/s/breadcrumbs-ant-desing-react-router-y8t2p7

**Comment by guyutian** [comment]
@brayanjeshua 
![image](https://user-images.githubusercontent.com/42087449/224540808-60fd2449-705e-4419-9016-dda7d7d040c0.png)

**Comment by brayanjeshua** [comment]
`import React from 'react';
import { Breadcrumb, Col, Row } from 'antd';
import { NavLink, useLocation } from 'react-router-dom';

const capitalizeChar = (str) => {
  return str.charAt(0).toUpperCase() + str.slice(1);
};

/**
 * This component uses react-router-dom
 * (should be used inside a Provider)
 */
const Breadcrumbs = () => {
  const location = useLocation();
  const pathSnippets = location.pathname.split('/').filter((i) => i);

  const breadcrumbItems = [
    {
      title: <NavLink to="/">Home</NavLink>,
      key: '/',
    },
  ].concat(
    pathSnippets.map((snippet, index) => {
      const url = `/${pathSnippets.slice(0, index + 1).join('/')}`;
      const title = snippet.replace(/-/g, ' ');

      return {
        title: <NavLink to={url}>{capitalizeChar(title)}</NavLink>,
        key: url,
      };
    })
  );

  return (
    <>
      <Row>
        <Col className="flex items-center gap-2 p-4">
          <Breadcrumb items={breadcrumbItems}></Breadcrumb>
        </Col>
      </Row>
    </>
  );
};

export { Breadcrumbs };
`

well trying and trying i've Solve the component, thanks the same way 👍🏻
