### ISSUE TITLE
menu item break with ellipsis typography text 

### ISSUE THREAD

**Issue by coolcorexix** [ant-design/ant-design#41143]
### Reproduction link

[https://github.com/coolcorexix/saleshood-playground/tree/reproduce-text-ellipsis-error](https://github.com/coolcorexix/saleshood-playground/tree/reproduce-text-ellipsis-error)

### Steps to reproduce

- Start the repo (npm install && npm run dev)
- Observe the option 1

### What is expected?

the `Option 1` is well aligned like other options

### What is actually happening?

With Ellipsis text enabled, Option 1 label drop to a newline 
![image](https://user-images.githubusercontent.com/25930830/223958812-53915ac8-58a0-4c23-b918-0736ea80a7ae.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | MAC OS |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
I converted to an online link, and there was a problem. https://codesandbox.io/s/ji-ben-shi-yong-antd-5-2-2-forked-hfr7q4?file=/demo.js

**Comment by Yuiai01** [comment]
Let me fix it～
