### ISSUE TITLE
InputNumber在设置disable时, 展示的字体颜色和其他input组件disable颜色不一致

### ISSUE THREAD

**Issue by sy0uta1k0n** [ant-design/ant-design#41159]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js)

### Steps to reproduce

1. 引入antd, react
2. 引入Input, InputNumber
3. 给值, 并把这俩都disable

### What is expected?

InputNumber组件disable后的文字颜色和Input组件disable后的文字颜色一致

### What is actually happening?

InputNumber组件disable后的文字颜色和disable前无差异

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | mac os 13.0 |
| Browser | chrome 110.0.5481.177 |

**Comment by sy0uta1k0n** [comment]
看了一下4.0最后一个版本, 是正常的, disable后颜色是灰色.
https://4x.ant.design/components/input-number-cn/

**Comment by Yuiai01** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-nbfs6j?file=/index.js 确实存在问题，我来看看~
