### ISSUE TITLE
Table 使用了自定义 component.body 。当 columns={[]} 控制台就会报错

### ISSUE THREAD

**Issue by eternallycyf** [ant-design/ant-design#41150]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dou8ne)

### Steps to reproduce

      columns={mergedColumns}  =>       columns={[]}

### What is expected?

不报错

[react-component(#965) pull request](https://github.com/react-component/table/pull/965)

### What is actually happening?

控制台会提示： Warning: When use `components.body` with render props. Each column should have a fixed `width` value. 

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18  |
| System | macos |
| Browser | chrome最新 |

---
期望不会报错

**Comment by eternallycyf** [comment]
<img width="1057" alt="截屏2023-03-09 23 11 24" src="https://user-images.githubusercontent.com/63464198/224067680-224a6880-13dc-4bb7-9877-b3652718c471.png">

**Comment by eternallycyf** [comment]
-

**Comment by Francoshum95** [comment]
Let me have a look, seems easy to fix ^^
