### ISSUE TITLE
[feat] Please unify APi style

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#41156]
### What problem does this feature solve?

there are three types of Api when u try to style the Modal, `width` / `bodyStyle` / `wrapperClassName`, which are not uniform and make it so bad.

### What does the proposed API look like?

make them unified, style/property/className. do not mixed them in a single Api

**Comment by zombieJ** [comment]
Thanks for feedback. We already notice this. But to avoid breaking change. It's still there. Here is the latest RFC we are trying:

[[RFC] Semantic DOM Structure for all Components](https://github.com/ant-design/ant-design/discussions/40221)
