### ISSUE TITLE
Tooltip doesn't work with svg elements as children

### ISSUE THREAD

**Issue by josedefreitas91** [ant-design/ant-design#41153]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-yalow-rm6fzg)

### Steps to reproduce

Using an svg element as children

### What is expected?

show the popup when hovering over an svg

### What is actually happening?

the styles in the tooltip use the wrong left and top position (-1000vh)

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | react 18.2.0 |
| System | macos 12.6.3 |
| Browser | Google Chrome 110.0.5481.177 (x86_64) |

**Comment by notverysalty** [comment]
let me try~
