### ISSUE TITLE
通过 Modal.method 调用弹窗，全局配置的 ConfigProvider 主题失效

### ISSUE THREAD

**Issue by keene-dalveytech** [ant-design/ant-design#41154]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-icvbqf?file=/index.js)

### Steps to reproduce

直接就能重现

### What is expected?

命令式调用显示弹窗能正常展示主题

### What is actually happening?

命令式调用显示弹窗不能正常展示主题

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
静态方法无法消费 context，建议使用 hooks 或者 App 组件。
Ref: https://ant-design.antgroup.com/components/config-provider-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-messageinfonotificationopen-%E6%88%96-modalconfirm-%E7%AD%89%E6%96%B9%E6%B3%95%E5%86%85%E7%9A%84-reactnode-%E6%97%A0%E6%B3%95%E7%BB%A7%E6%89%BF-configprovider-%E7%9A%84%E5%B1%9E%E6%80%A7%E6%AF%94%E5%A6%82-prefixcls-%E5%92%8C-theme

**Comment by zombieJ** [comment]
> 在绝大多数场景，都不需要静态方法。它无法消费 context，例如无法响应动态主题。请优先使用 hooks 版本或者 App 组件提供的 Modal 实例。

https://ant.design/components/modal-cn#components-modal-demo-static-info
