### ISSUE TITLE
Current User Menu Item component

### ISSUE THREAD

**Issue by jmatsushita** [ant-design/ant-design#4115]
It would be good to have a component which allows to simplify the implementation of the Pattern below and specifically number 3. login tools.

![image](https://cloud.githubusercontent.com/assets/356097/20838720/0ff0b9fa-b8aa-11e6-92aa-2a8f0202653b.png)

**Comment by afc163** [comment]
It is more like a bussiness component and you can create it by using http://ant.design/components/dropdown
