### ISSUE TITLE
日期选择不超过七天的范围demo

### ISSUE THREAD

**Issue by Calas7** [ant-design/ant-design#41165]
### Reproduction link

[https://ant.design/components/date-picker-cn#components-date-picker-demo-select-in-range](https://ant.design/components/date-picker-cn#components-date-picker-demo-select-in-range)

### Steps to reproduce

选择开始时间2020-03-05，再次点击开始时间选择年份，发现2020年之后的都被禁用了

### What is expected?

再次选择能选择所有

### What is actually happening?

部分被禁用

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 17 |
| System | Google Chrome |
| Browser | 110.0.5481.177 |

**Comment by Calas7** [comment]
> 能整个录屏吗？我这按步骤貌似没有恢复出来( Ĭ ^ Ĭ )


https://user-images.githubusercontent.com/121657656/224278369-ee2402cb-6666-43a1-ba23-10b95f9ff56f.mp4

电脑录屏文件太大，手机录下你看看~

**Comment by Yuiai01** [comment]
> > 能整个录屏吗？我这按步骤貌似没有恢复出来( Ĭ ^ Ĭ )
> 
> 电脑录屏文件太大，手机录下你看看~

确实存在问题，我来跟一下~

**Comment by Calas7** [comment]
> > > 能整个录屏吗？我这按步骤貌似没有恢复出来( Ĭ ^ Ĭ )
> > 
> > 
> > 电脑录屏文件太大，手机录下你看看~
> 
> 确实存在问题，我来跟一下~

好滴，辛苦～

**Comment by Yuiai01** [comment]
@Calas7 你好，我这边研究了一下这个 demo。这个 demo 会在我们选择了开始或者结束日期后，根据所选择的日期设置可选时间范围，当我们想重新选择日期时，因为没有触发设置可选时间的逻辑，所以产生了你所描述的问题。在后续的跟进流程中，我发现当前并没有监听 RangePicker 选择区域的方法，既无法判断是处于开始或者结束日期的选择框内，因此没有办法清除掉可选时间范围，我也尝试了其他的方法，但都失败了 ( Ĭ ^ Ĭ )。不过可以通过手动的方式来清除掉可选时间范围：
1、鼠标脱离 RangePicker。此时会触发 `onOpenChange` 方法的逻辑将选中的日期清空；
2、通过清除按钮来清空选中的日期。

**Comment by Calas7** [comment]
> @Calas7 你好，我这边研究了一下这个 demo。这个 demo 会在我们选择了开始或者结束日期后，根据所选择的日期设置可选时间范围，当我们想重新选择日期时，因为没有触发设置可选时间的逻辑，所以产生了你所描述的问题。在后续的跟进流程中，我发现当前并没有监听 RangePicker 选择区域的方法，既无法判断是处于开始或者结束日期的选择框内，因此没有办法清除掉可选时间范围，我也尝试了其他的方法，但都失败了 ( Ĭ ^ Ĭ )。不过可以通过手动的方式来清除掉可选时间范围： 1、鼠标脱离 RangePicker。此时会触发 `onOpenChange` 方法的逻辑将选中的日期清空； 2、通过清除按钮来清空选中的日期。

是滴，要是监听选择开始日期和结束日期的方法能暴露出来就能解决这个问题嘞
