### ISSUE TITLE
TextArea组件allowClear时，获取焦点时父元素.ant-input-affix-wrapper没有添加.ant-input-affix-wrapper-focused样式, Input组件会增加这个class

### ISSUE THREAD

**Issue by starsoul666** [ant-design/ant-design#41164]
### Reproduction link

[https://4x.ant.design/components/input-cn/#components-input-demo-allowClear](https://4x.ant.design/components/input-cn/#components-input-demo-allowClear)

### Steps to reproduce

打开ant design官网，点击Input组件的带移除图标 demo，点击第二个TextArea组件

### What is expected?

和Input组件一样，获取焦点时增加ant-input-affix-wrapper-focused样式

### What is actually happening?

ant-input-affix-wrapper父元素没有ant-input-affix-wrapper-focused样式

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | react |
| System | macos |
| Browser | chrome |

**Comment by MuxinFeng** [comment]
确实，我提个 pr 补一下吧
