### ISSUE TITLE
Example of Table & Chart combination

### ISSUE THREAD

**Issue by jmatsushita** [ant-design/ant-design#4116]
It would be useful to have [a code example for the chart and table feature](https://ant.design/docs/spec/feature#集成创新)

![image](https://cloud.githubusercontent.com/assets/356097/20838835/8c6cddc4-b8aa-11e6-8f76-e2b4439ea804.png)

**Comment by benjycui** [comment]
We haven't provided recommended chart library now.

cc @simaQ @jaredleechn

**Comment by afc163** [comment]
Actually, we do not implement this demo yet.
