### ISSUE TITLE
Focus treatment issue for button with dropdown

### ISSUE THREAD

**Issue by mellis481** [ant-design/ant-design#41175]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/go5q7x)

### Steps to reproduce

1. Tab to button.

### What is expected?

Focus outline will appear over secondary button element.

### What is actually happening?

Focus outline is behind secondary button element.

![image](https://user-images.githubusercontent.com/39313898/224345200-8c776ea2-6679-4d8d-8425-692ab56a3eac.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | Latest |
| System | Windows |
| Browser | All |

**Comment by Yuiai01** [comment]
@mellis481 Hello, I think button and menu are two separate parts, the hierarchy should be the same, so the selected style should be relatively independent.

**Comment by mellis481** [comment]
@Yuiai01 The issue is with any button with multiple segments (eg. drop down button).  

Are you asserting that you don't believe there is any issue in my screenshot?

**Comment by Yuiai01** [comment]
@mellis481 I'm sorry. I may have misunderstood. But the page I saw looked like this.
![image](https://user-images.githubusercontent.com/112228030/224517445-e7d03dfe-c6f5-4863-b834-2c8dfcc14b00.png)

**Comment by mellis481** [comment]
@Yuiai01 It looks like you're looking at 4.x.  Current master branch (5.x) looks like this: https://ant.design/components/dropdown#components-dropdown-demo-dropdown-button

**Comment by Yuiai01** [comment]
> @Yuiai01 It looks like you're looking at 4.x. Current master branch (5.x) looks like this: https://ant.design/components/dropdown#components-dropdown-demo-dropdown-button

No, I checked the link you provided, and I also checked the official example of 5.x, but the problem you mentioned did not reappear. 🤔

**Comment by mellis481** [comment]
@Yuiai01 You're not tab-focusing the button (like a keyboard user would do). You're just clicking the button with your mouse.

**Comment by Yuiai01** [comment]
> @Yuiai01 You're not tab-focusing the button (like a keyboard user would do). You're just clicking the button with your mouse.

Yes, the focus style of the button is masked. I'll try to fix it.
