### ISSUE TITLE
Confirm Modal has an empty div below confirm buttons

### ISSUE THREAD

**Issue by Svudec** [ant-design/ant-design#41170]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zjshu0?file=/index.js:940-950)

### Steps to reproduce

Click on a 'Confirm Modal' button and look at the confirm buttons position. I added Default Modal for a comparison.

### What is expected?

Styles of the modal are the same when opening with `confirm` function or `<Modal>` component.

### What is actually happening?

When opening a Modal with `confirm` function, confirm buttons are too distant from the bottom edge of the Modal. 
There's an empty `div` element (ant-modal-footer) that has a 12px top-margin that is causing misalignment.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | react v18.2.0 |
| System | Windows 11 Pro 21H2 |
| Browser | Latest Chrome and Firefox |

**Comment by Svudec** [comment]
![image](https://user-images.githubusercontent.com/11903509/224309189-13ed1ff6-8303-4e7a-ad61-6111de71c181.png)

**Comment by Svudec** [comment]
I'll investigate this and am willing to make a PR with the fix

**Comment by Wxh16144** [comment]
I did the same thing as you, but I added some test cases. https://github.com/Svudec/ant-design/pull/1
