### ISSUE TITLE
antd slider gets crashed

### ISSUE THREAD

**Issue by majidaliharoon-dev** [ant-design/ant-design#41174]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-3-0-forked-h9w4bd)

### Steps to reproduce

1. open https://ant.design/components/slider in mobile device.
2. move the Basic slider forwards and backward five-six or more times
3. It produces following error https://reactjs.org/docs/error-decoder.html/?invariant=185

### What is expected?

the slider should not crash even if I change the slider values many times.

### What is actually happening?

It is getting crashed and producing minified react error #185.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | next 13.0.7 |
| System | mac, android |
| Browser | google chrome |

**Comment by Yuiai01** [comment]
@majidaliharoon-dev  Hello, there is something wrong with the link you provided to describe the problem, could you please provide it again?

**Comment by MARKX97** [comment]
> @majidaliharoon-dev Hello, there is something wrong with the link you provided to describe the problem, could you please provide it again?

i just opened the link, my man

**Comment by Yuiai01** [comment]
> > @majidaliharoon-dev Hello, there is something wrong with the link you provided to describe the problem, could you please provide it again?
> 
> i just opened the link, my man

I'm sorry, maybe my description wasn't very clear. I'm trying to say that the link to this error seems to point to the wrong address.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/112228030/224555398-a714a28d-e8a6-44a3-b5a6-00249bdffd96.png">

**Comment by Yuiai01** [comment]
The wrong link that I'm reproducing here is this https://reactjs.org/docs/error-decoder.html/?invariant=422

**Comment by majidaliharoon-dev** [comment]
> @majidaliharoon-dev Hello, there is something wrong with the link you provided to describe the problem, could you please provide it again?

Hi, I am sorry for the wrong link I have updated the link. please check now.

**Comment by zombieJ** [comment]
@majidaliharoon-dev pls update reproduce instead. Since it maybe not related with Slider component or by other thing on the site.
