### ISSUE TITLE
Select(showSearch),下拉的数据根据输入的关键字从远端获取，选中下拉项后输入框被清空

### ISSUE THREAD

**Issue by yulrosy** [ant-design/ant-design#4118]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本: windows10
- 浏览器及其版本: chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

    'use strict';

    const {Select,Form} = antd;
    const Option = Select.Option;
    const FormItem = Form.Item;
    
    const getJSON = (url, params, cb) => {
     cb(null,[{id:'1',name:'xx'},{id:'2',name:'yy'}]) 
    };
    
    const Complete = React.createClass({
      timeout: null,
      currentValue: '',
      getInitialState() {
        return {
          data: [],
          value: this.props.value || {key: '', label: ''}
        };
      },
      componentWillReceiveProps(nextProps) {
        // Should be a controlled component.
        if ('value' in nextProps) {
          const value = nextProps.value;
          this.setState({value});
        }
      },
      fetch(value, callback){
        const self = this;
        const props = self.props;
        const url = props.url;
        if (self.timeout) {
          clearTimeout(self.timeout);
          self.timeout = null;
        }
        self.currentValue = value;
    
        function _fetch() {
          if (!value || !value.trim()) {
            if (self.currentValue === value) {
              return callback(null, []);
            }
            return;
          }
          getJSON(url + '?q=' + value, {}, (err, result) => {
            if (self.currentValue === value) {
              const data = [];
              result.forEach(row => {
                data.push({
                  value: row[props.valueField],
                  text: row[props.textField]
                });
              });
              callback(null, data);
            }
          })
        }
    
        self.timeout = setTimeout(_fetch, 300);
      },
      handleSearch(value){
        this.fetch(value, (err, data) => {
          data = err ? [] : data;
          this.setState({data, value: {key: value}});
        });
      },
      triggerChange(value, option){
        const props = this.props;
        if (!('value' in props)) {
          this.setState({value});
        }
        props.onChange(value);
      },
      render(){
        const state = this.state;
        const options = state.data.map((d, i) => <Option key={d.value + ''}>{d.text}</Option>);
        const props = {
          style:{width:200} ,                         
          value: state.value,
          showSearch: true,
          labelInValue: true,
          defaultActiveFirstOption: false,
          filterOption: false,
          onSearch: this.handleSearch,
          onSelect: this.triggerChange,
        };
        return (
          <Select  {...props}>
            {options}
          </Select>
        );
      }
    });
    
    let Demo = ({form}) => (
      <Form>
        <FormItem>
         {form.getFieldDecorator('id')(<Complete textField='name' valueField='id'/>)}
        </FormItem>
      </Form>
    )
    Demo = Form.create()(Demo);
    
    ReactDOM.render(<Demo/>, document.getElementById('container'));

#### 您期待的结果是:

选择下拉框的某一项，输入框展示该项

#### 实际上的结果是:

选择后输入框被清空

**Comment by afc163** [comment]
You should use `Select[combobox]` other than `Select[showSearch]`.

**Comment by yulrosy** [comment]
使用combobox,value的 key和label都是value，取不到文字

**Comment by afc163** [comment]
`optionLabelProp="children"`

**Comment by yulrosy** [comment]
thanks
