### ISSUE TITLE
Menu在菜单收缩后出现hover状态

### ISSUE THREAD

**Issue by qiuqfang** [ant-design/ant-design#41186]
### Reproduction link

[https://stackblitz.com/run?file=demo.tsx](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

1、收缩菜单
2、移入第一至三项
3、打开菜单
4、收缩菜单

### What is expected?

在第4步收缩菜单后，第一到三项的hover状态不应该同时出现

### What is actually happening?

第一到三项的hover状态同时出现

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | Windows 10 10.0.19044 |
| Browser | Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41) |

**Comment by Yuiai01** [comment]
这个链接貌似看不到你的项目，能重新整一个吗？

**Comment by li-jia-nan** [comment]
这个貌似已经解决了，等明天发版就好了

**Comment by afc163** [comment]
Duplicate of #41081

**Comment by afc163** [comment]
@li-jia-nan 看上去没有相关修复。https://github.com/ant-design/ant-design/issues/41081
