### ISSUE TITLE
Popconfirm组件包裹的元素hover消失的时候，弹框位置偏移

### ISSUE THREAD

**Issue by lvdougao1** [ant-design/ant-design#41180]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ji-ben-antd-5-3-0-forked-fdvqhy?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

点击Popconfirm包裹a标签，当a标签display属性为none时，Popconfirm位置偏移

### What is expected?

Popconfirm位置不发生改变

### What is actually happening?

Popconfirm位置偏移

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.0 |
| System | macOs 13.1 (22C65) |
| Browser | 谷歌111.0.5563.64 |

**Comment by Yuiai01** [comment]
Popconfirm 需要显示在目标元素附近，而当元素设置 `display: none` 时，会从页面中消失，因此 Popconfirm 的位置就会产生偏移。或许可以使用 `visible: hidden` 替代 `display: none` ？

**Comment by lvdougao1** [comment]
> Popconfirm 需要显示在目标元素附近，而当元素设置 `display: none` 时，会从页面中消失，因此 Popconfirm 的位置就会产生偏移。或许可以使用 `visible: hidden` 替代 `display: none` ？

好的 我试一下，但是之前在5.2.3版本中使用display: none时 没有出现位置偏移

**Comment by zombieJ** [comment]
因为之前版本的 Popconfirm 对齐是惰性的，现在总是会检测元素位置。我感觉是可以调整一下的。

**Comment by zombieJ** [comment]
fixed https://codesandbox.io/s/ji-ben-antd-5-3-0-forked-5gt6pp?file=/package.json

**Comment by XuJin186** [comment]
意思我等新版本就可以解决了嘛 谢谢各位大佬

**Comment by afc163** [comment]
5.3.1 昨天已经发了
