### ISSUE TITLE
在暗黑模式中是否可以将网页背景色默认设置为暗色

### ISSUE THREAD

**Issue by qiuqfang** [ant-design/ant-design#41181]
### What problem does this feature solve?

解决了在使用的时候无需在重新设置背景颜色

### What does the proposed API look like?

需要修改暗黑模式算法

**Comment by kiner-tang** [comment]
这个不应该在`ant-design`当中实现吧，`ant-design`只管理组件皮肤，网页的背景色感觉自己额外根据当前是否暗黑模式设置比较好

**Comment by qiuqfang** [comment]
这么说也没问题吧。但就是我在暗色模式时使用类型为text的按钮，一开始没有设置网页背景色，我还以为按钮样式出bug了呢

**Comment by afc163** [comment]
可以配合 Layout 组件作为全局布局来实现这个效果。

**Comment by DorothyGuan** [comment]
> 可以配合 Layout 组件作为全局布局来实现这个效果。

Layout组件也是挂在root div下铺满整个页面，但根元素或者body还是空白网页背景色，这个由浏览器决定并不和ant暗色主题背景色一致，进页面时可能会有一个“闪白”的过程，体验不是很好。
