### ISSUE TITLE
使用message静态方法唤起创建了新的.anticon样式，覆盖了icon的.anticon导致line-height失效

### ISSUE THREAD

**Issue by xwHsj** [ant-design/ant-design#41197]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zrnfeh?file=/index.js)

### Steps to reproduce

进入页面，点击按钮【提示message】

### What is expected?

红色块的高度不丢失

### What is actually happening?

红色块的高度消失。

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | react: "^18.2.0" |
| System | mac |
| Browser | 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 |

---
因为message.info后增加了.anticon 的全局样式，该样式与@ant-design/icons icon中的anticon冲突并进行了覆盖。

**Comment by Wxh16144** [comment]
确实存在问题，我去看看~

**Comment by zombieJ** [comment]
最好这个在 App 里包一下，现在 App 也是没有这个功能：
https://codesandbox.io/s/antd-reproduction-template-forked-624etl?file=/index.js:413-416

**Comment by afc163** [comment]
可以把 @ant-design/icons 里的自带样式统一成 `display: 'inline-flex';`。
