### ISSUE TITLE
【Feature】tabs升级改造后前后数据不一致导致初始化选中失败

### ISSUE THREAD

**Issue by CDragonTime** [ant-design/ant-design#41194]
### What problem does this feature solve?

避免v4升级到v5后对所有涉及到的tabs进行初始化的逻辑更改
https://codesandbox.io/s/ji-chu-yong-fa-fei-qi-de-yu-fa-tang-antd-4-24-7-forked-ttzzrj?file=/demo.tsx:1214-1292

### What does the proposed API look like?

源码中不直接返回items，而是和v4版本执行一样的操作：return items.map(v=>{(...v,key:String(v.key))})

**Comment by afc163** [comment]
key 应该是 string。

**Comment by zombieJ** [comment]
jsx 中获取的 key 总是会被替换成 string 类型，导致 activeKey 如果是 number 它是对不上的。items 就不会有这个问题，也不准备把 bug as feature 去兼容旧版本。如果有这个需求的话，可以 HOC 一下，总是把所有的 key 转成 string 类型。

**Comment by CDragonTime** [comment]
好的👌
