### ISSUE TITLE
Modal 组件在手机上使用时出现样式错误

### ISSUE THREAD

**Issue by MicleMing** [ant-design/ant-design#41192]
### Reproduction link

[https://ant.design/components/modal-cn](https://ant.design/components/modal-cn)

### Steps to reproduce

1. 手机打开 antd modal 官网
2. 点击demo出现modal

### What is expected?

modal样式在手机上正常呈现

### What is actually happening?

1. 关闭按钮错位
2. modal位置未居中

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18 |
| System | ios16.3.1 |
| Browser | chrome 110.0.5481.114 |

**Comment by MuxinFeng** [comment]
我这没复现出来诶，具体是哪个demo呢？

**Comment by MicleMing** [comment]
![IMG_1483](https://user-images.githubusercontent.com/6770547/224643038-536f43c3-8306-458f-abdb-00e9eb728f81.PNG)
basic modal 就会

**Comment by MuxinFeng** [comment]
我这边浏览器和真机都没能复现（ios 16.1.2）

官网默认打开是 PC 环境，等到识别运行环境为移动端后，还在回流的过程中你就打开了 demo，然后部分样式还没计算完成？
![image](https://user-images.githubusercontent.com/46584765/224656676-29a98f28-7aca-480f-80ac-1cdc8275c602.png)

**Comment by yoyo837** [comment]
iPhone 11 iOS 16.3.1 表示正常

**Comment by zombieJ** [comment]
完整的系统信息截个图看看？

**Comment by RedJue** [comment]
看了下 好像没有描述的问题，是什么特定浏览器么
![096DAA8A-836F-4E2C-BB34-F54284BB2B45](https://user-images.githubusercontent.com/21119589/224891032-ddde377f-77bf-4e9c-b6b2-663be8203144.jpeg)

**Comment by MicleMing** [comment]
升级了appstore 之后就正常了，未升级前Safari和chrome都有问题..... @RedJue

**Comment by yoyo837** [comment]
app store?

**Comment by MicleMing** [comment]
ios 打开 app store --> 弹出更新弹窗 --> 点击 更新

**Comment by afc163** [comment]
https://ant.design/docs/react/compatible-style-cn
