### ISSUE TITLE
tabs 统一添加删除设计

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#412]
<img width="461" alt="2015-10-20 9 51 25" src="https://cloud.githubusercontent.com/assets/200876/10609131/bf74c830-7774-11e5-9253-0e1fd96ce423.png">

**Comment by afc163** [comment]
这个页签式的 Tabs 视觉样式，和原有的 Tabs 风格不统一。和设计讨论后，不是很通用，建议业务先实现。

**Comment by yiminghe** [comment]
http://react-component.github.io/tabs/examples/add.html

**Comment by yiminghe** [comment]
http://ant.design/components/tabs/
