### ISSUE TITLE
Argument appears to not be a ReactComponent. Keys: forceAlign,forcePopupAlign

### ISSUE THREAD

**Issue by fitterfizzle** [ant-design/ant-design#41206]
### Reproduction link

[https://ant.design/](https://ant.design/)

### Steps to reproduce

1. Use <ProTable/>
2. Use latest version of antd

### What is expected?

Table should appear

### What is actually happening?

Table shows error message "Argument appears to not be a ReactComponent. Keys: forceAlign,forcePopupAlign"

![image](https://user-images.githubusercontent.com/96863959/224722431-53fdf697-836c-4925-8186-32a220fe8257.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 17.0.2 |
| System | macOS |
| Browser | Chrome |

**Comment by kiner-tang** [comment]
@fitterfizzle I can't reproduce this problem in Ant Design website. Can you provide a detailed reenactment procedure or record a video?

**Comment by fitterfizzle** [comment]
Sure thing here it is

https://user-images.githubusercontent.com/96863959/224733851-dbf79d7d-f575-42f7-a143-1f8689873ece.mp4

**Comment by kiner-tang** [comment]
> Sure thing here it is

Can you provide the link which you reproduce?

**Comment by fitterfizzle** [comment]
> > Sure thing here it is
> 
> Can you provide the link which you reproduce?

I am not allowed to share the source code. I can try and see if a codesandbox is able to reproduce it. As additional info everything was working until 5.3.0, if I downgrade to 5.2.3 then everything works again. Does this help?

**Comment by fitterfizzle** [comment]
Maybe this is also helpful

![image](https://user-images.githubusercontent.com/96863959/224745085-2642c64b-c84f-403c-a3f3-66095b0639f2.png)

**Comment by kiner-tang** [comment]
> I am not allowed to share the source code. I can try and see if a codesandbox is able to reproduce it. As additional info everything was working until 5.3.0, if I downgrade to 5.2.3 then everything works again. Does this help?

Thanks, If it is convenient, please provide the link for codesandbox to reproduce

**Comment by fitterfizzle** [comment]
I even tried rendering only the <ProTable/> component in my environment top level at index.js level and the problem still appears. Here a more detailed `console.error`

![image](https://user-images.githubusercontent.com/96863959/224953941-ab73507f-1d24-4b71-a81a-bc7fa2b04de3.png)

**Comment by deng-yc** [comment]
same problem

**Comment by deng-yc** [comment]
使用了ProTable 会上面的错误
设置options={{ setting:false }} 正常显示
```
<ProTable
            size="small"
            options={{
              setting: false,
            }}
          />
```

**Comment by fitterfizzle** [comment]
> 

I can confirm that using the `options={{setting:false}}` indeed renders the table normally. However this completely removes the custom hide/unhide and reorder functionality of `<ProTable/>` which is a no go

**Comment by fitterfizzle** [comment]
> Hello @fitterfizzle. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository.

I can't reproduce it on sandbox, but as said both by me and by @deng-yc this is happening in both of our environments.

**Comment by fitterfizzle** [comment]
Any news?

**Comment by afc163** [comment]
A reproduce is needed.

**Comment by askurat** [comment]
I can confirm this is also happening to me. I have tried reproducing in a sandbox but can't seem to produce the error.

**Comment by hbatalhaStch** [comment]
I just ran into this issue but I reverted back to `v5.2.3` and updated again to `v5.3.1` and now it is working as expected. I have no idea what just happened. I am just hoping this is not a bug that will creep up on me when I am least expecting.

**Comment by fitterfizzle** [comment]
> I just ran into this issue but I reverted back to `v5.2.3` and updated again to `v5.3.1` and now it is working as expected. I have no idea what just happened. I am just hoping this is not a bug that will creep up on me when I am least expecting.

If you do a clean install of `v5.3.1` and `npm run start` the problem will still be there...

**Comment by hbatalhaStch** [comment]
>If you do a clean install of v5.3.1 and npm run start the problem will still be there...

That is what I did after commenting but still worked as expected. Tbh idk what is happening, I can confirm that this issue happened but now I can't reproduce it (using the same exact code).

**Comment by askurat** [comment]
We reverted back to `v5.2.3` as well. Reverting and upgrading back to `v5.3.1` did not work.

**Comment by hbatalhaStch** [comment]
I just tested in a another computer so I deleted the whole `node_modules` folder and ran `npm i` and it worked.

**Comment by hooliy** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/3368691/225825131-75bd9369-d891-4bba-a68e-a3cc81731818.png">
同样的问题，升级到最新版后，不管怎么降级都会一直报错，删除 node_modules 再重新 yarn 同样报错！

**Comment by afc163** [comment]
>  同样的问题，升级到最新版后，不管怎么降级都会一直报错，删除 node_modules 再重新 yarn 同样报错！ 

@hooliy 试试删除 yarn.lock 和 package-lock.json 后重装。

**Comment by hooliy** [comment]
> > 同样的问题，升级到最新版后，不管怎么降级都会一直报错，删除 node_modules 再重新 yarn 同样报错！
> 
> @hooliy 试试删除 yarn.lock 和 package-lock.json 后重装。

3Q！多谢解决了我的问题，要不又要肝到半夜了！

**Comment by xuqiang1227** [comment]
删除 yarn.lock 后执行yarn install 报错：

Cannot find module 'antd/dist/theme'

**Comment by askurat** [comment]
While deleting node_modules and package-lock.json/yarn.lock did seem to resolve the issue, I ran into issues where tooltips/popovers were very inconsistent. Sometimes they would work, sometimes not. They would also stay on the screen after the mouse moved away. I couldn't click on buttons I had wrapped in a tooltip either.

For know I will stick with `5.2.3` until this is resolved.

**Comment by xuqiang1227** [comment]
@afc163 @zombieJ 
我这个问题我尝试在codesandbox，都没办法复现，但是本地依然存在问题。
尝试debug了一下发现在 `resize-observer` 工程中的 `src\SingleObserver\index.tsx` 文件里第42行的 `getDom`方法中：
```
  const getDom = () =>
    findDOMNode<HTMLElement>(elementRef.current) || findDOMNode<HTMLElement>(wrapperRef.current);
```
当这个问题出现时：`elementRef.current` 的 值为：
```
{
   forceAlign: () => {},
   forcePopupAlign: () => {}
}
```
![image](https://user-images.githubusercontent.com/4525647/227862924-ee36f053-f036-48ba-91e4-1cf8aaea05b3.png)

该值应该为antd 中 `ant-design\components\tooltip\index.tsx` 第221行定义的 ref。
所以麻烦再review一下这里的代码，看看是否存在bug。

**Comment by GirlGlitter** [comment]
in version 5.5.1, i also encountered the same issue

**Comment by GirlGlitter** [comment]
v5.6.2, tootlips also has same issue

**Comment by TdyP** [comment]
Any workaround for this issue until it get fixed?
I really need the color picker available since 5.5, but this bug appeared in 5.3 so I'm pretty stuck

**Comment by TdyP** [comment]
FWIW, in my case it seems to be related to the combination of Popconfirm + Tooltip (if I remove one or the other, the error disappears). Unfortunately, in a codesandbox it all works fine... I have no idea where it comes from :/

**Comment by TdyP** [comment]
Sorry for spamming around. I just found a workaround for my case: wrapping my `Tooltip` with a React fragment `<></>` like so:
``` 
<Popconfirm
    title="My title"
    onConfirm={_myFunction}
    placement="bottomRight"
>
    <>
        <Tooltip title="Some title">
            <Button icon={<ClearOutlined />} />
        </Tooltip>
    </>
</Popconfirm>
``` 

Hope this helps

**Comment by geosigno** [comment]
I had the same issue, I fixed by added a <></> inside my tooltip that was inside my table data sources.

Before:
```js
 <Tooltip
            title={}
          >
              <Checkbox
                defaultValue={field.isMandatory}
                disabled={!isAllowed}
                checked={field.isMandatory}
                onChange={async () => {
                  handleChange(field, {
                    isMandatory: !field.isMandatory,
                  });
                }}
              />
          </Tooltip>
```

after
```js
 <Tooltip
            title={
              field.isMandatory
                ? t("Discussion:Make this field non-mandatory")
                : t("Discussion:Make this field mandatory")
            }
          >
            <>
              <Checkbox
                defaultValue={field.isMandatory}
                disabled={!isAllowed}
                checked={field.isMandatory}
                onChange={async () => {
                  handleChange(field, {
                    isMandatory: !field.isMandatory,
                  });
                }}
              />
            </>
          </Tooltip>```

**Comment by cuongle-hdwebsoft** [comment]
For me, I've dev and inspected `/node_modules/rc-util/es/Dom/findDOMNode.js` in the browser, and here are things they show me:

<img width="868" alt="CleanShot 2023-11-23 at 16 00 47@2x" src="https://github.com/ant-design/ant-design/assets/102006695/2540a0e9-bbac-4690-9198-c250e92543e4">

This issue may be related to `rc-util`. I am using v`5.27.1` for my project and then when I bump that version to `5.38.1`, I get no error. 

[Here is the latest code that finds dom node](https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L13).

[Here is the actual change that led to the error](https://github.com/react-component/util/pull/419/files#diff-78f21c517711076cc49d7384819808e4ddbe48ad701a697e914e84413d00df1d).

I don't know whether it will cause any error in the feature, but by the way, I found my own problem. 😄

**Comment by dmytro-machulskyi** [comment]
no solution for that problem that a lot of people experienced and yes, it is already **CLOSED**. should i pretend it is gone?
