### ISSUE TITLE
DatePicker 控件没切换年份区间时，选择年份后不是选择月份，切换年份区间后，就是月份选择

### ISSUE THREAD

**Issue by CookyG** [ant-design/ant-design#41202]
### Reproduction link

[https://4x.ant.design/components/date-picker-cn/](https://4x.ant.design/components/date-picker-cn/)

### Steps to reproduce

看最基本的代码演示

### What is expected?

DatePicker 控件没切换年份区间时，选择年份后不是选择月份

### What is actually happening?

选择年份后，选择月份

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by Yuiai01** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/112228030/224678226-7968f1e4-a676-46e9-b7c3-300a5c08ffd0.png">
这里面的哪个啊？

**Comment by CookyG** [comment]
> <img alt="image" width="547" src="https://user-images.githubusercontent.com/112228030/224678226-7968f1e4-a676-46e9-b7c3-300a5c08ffd0.png">
> 
> 这里面的哪个啊？

第一个日期选择

**Comment by afc163** [comment]
给个 GIF ？

**Comment by CookyG** [comment]
> 给个 GIF ？

![Kapture 2023-03-13 at 21 38 54](https://user-images.githubusercontent.com/20312873/224718664-dd109149-8077-4153-ab8f-1d320b41ac26.gif)

**Comment by zombieJ** [comment]
好细。。。

**Comment by Yuiai01** [comment]
5.x 也存在这个问题，感觉是 pikcer 的问题，我去康康~

**Comment by madocto** [comment]
https://github.com/react-component/picker/blob/f512f18ed59d6791280d1c3d7d37abbb9867eb0b/src/panels/YearPanel/index.tsx#L82
或许这里应该 `onPanelChange ( 'month' ,  date ) ;`

**Comment by cooljser** [comment]
有人在处理吗？没有的话，我跟进一下

**Comment by yoyo837** [comment]
See https://github.com/react-component/picker/pull/604#issuecomment-1608632412
