### ISSUE TITLE
Antd insert global shared styles in my app

### ISSUE THREAD

**Issue by dacorm** [ant-design/ant-design#41204]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-cookies-lylpit?file=/src/App.js)

### Steps to reproduce

Just open xd 

### What is expected?

I expect antd not to override the global style of my A tag

### What is actually happening?

Here on screenshot https://disk.yandex.ru/d/P3mgNzwbbvFPZA you can see that i got injected style tag with data attribute data-dev-hash which includes word Shared and its overriding style of A tag in html. It affects on my app style and i want to avoid it

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Yandex |

---
I think you can help me to understand how to cancel this style injection or maybe you can help me to specify this styles with some class

**Comment by kiner-tang** [comment]
I don't understand what you mean, if you want to use antd's component, it is necessary to inject related style in html.   If you want to use select without style, maybe you can try [rc-select](https://github.com/react-component/select)

**Comment by dacorm** [comment]
> I don't understand what you mean, if you want to use antd's component, it is necessary to inject related style in html. If you want to use select without style, maybe you can try [rc-select](https://github.com/react-component/select)

I want antd to not inject shared styles (watch my screen) which directly applies to a tag without any antd related class names

**Comment by zombieJ** [comment]
When you closed `hashed`, all the style will inject without `css-xxx`. If you need more strict way, reopen it. `hashed`'s purpose is to isolate styles:

https://codesandbox.io/s/boring-sun-2gjsit?file=/src/index.js
