### ISSUE TITLE
期望Typography.Paragraph在自定义onExpand回调时能够有能力阻止原本的展开事件

### ISSUE THREAD

**Issue by Taylord-Lee** [ant-design/ant-design#41219]
### What problem does this feature solve?

在使用时，文字溢出触发省略后，期望能在省略号的末尾自定义添加一个【查看更多】的symbol，点击该symbol以自定义行为（例如弹窗的形式）展示出更多相关的信息且不展开文字，但发现无法对该组件的Expand行为进行阻止。

### **期望可阻止默认展开的行为，例如在ellipsis中添加一个forbidExpand属性值来控制展开行为**

``` js
<Paragraph ellipsis={{ forbidExpand: true }}>{content}</Paragraph>
```

___

### 发现源码中先执行了变更折叠state后触发自定义的onExpand函数，导致无法阻止Expand行为

```js
// >>>>> Expand
const onExpandClick: React.MouseEventHandler<HTMLElement> = (e) => {
  setExpanded(true);
  ellipsisConfig.onExpand?.(e);
};
```

___

### 如果不考虑拓既可展开又可折叠，可先进行简单变更实现控制展开行为
``` js
// >>>>> Expand Function Update
const onExpandClick: React.MouseEventHandler<HTMLElement> = (e) => {
  setExpanded(!!ellipsisConfig?.forbidExpand);
  ellipsisConfig.onExpand?.(e);
};
```

**Comment by Taylord-Lee** [comment]
I'll do it when it's confirmed.

**Comment by afc163** [comment]
```
ellipsis={{ expandable: false, symbol: 'more' }}
```

Try expandable

**Comment by Taylord-Lee** [comment]
> ```
> ellipsis={{ expandable: false, symbol: 'more' }}
> ```
> 
> Try expandable

源码中, 当expandable设置为false时, symbol则会直接返回null

**Comment by afc163** [comment]
来个 codesandbox 看看？

**Comment by Taylord-Lee** [comment]
https://codesandbox.io/s/charming-poitras-9ink3n?file=/index.js

**Comment by afc163** [comment]
可以来个 PR，symbol 在 expandable 为 false 时也显示出来。

**Comment by Taylord-Lee** [comment]
好的，我明天看看写一下。 我大概想了一下，既然使用者将expandable设置了false，我认为更多情况下是为了将其配置为不可展开。因此在expandable: false且symbol未被定义时，将不应再展示symbol的默认值。
