### ISSUE TITLE
Cannot resolve module 'react/lib/CSSProperty.js' in node_modules/rc-editor-core/lib/EditorCore/export

### ISSUE THREAD

**Issue by Centaur** [ant-design/ant-design#4121]
#### 发生问题的环境是：

- antd 版本: 2.5.0 react 15.4.1
- 操作系统及其版本: 
- 浏览器及其版本:

#### 您做了什么？请提供尽可能详细的重现步骤。
Webpack 

import {message, Button, Form, Input, Steps, Row, Col, Table, Alert, Checkbox, Radio, Popover, Tooltip} from 'antd' 

#### 您期待的结果是:
正常编译运行

#### 实际上的结果是:
```
ERROR in ./~/rc-editor-core/lib/EditorCore/export/getHTML.js
Module not found: Error: Cannot resolve module 'react/lib/CSSProperty.js' in node_modules/rc-editor-core/lib/EditorCore/export
 @ ./~/rc-editor-core/lib/EditorCore/export/getHTML.js 18:19-54
```

估计是因为React 新版（15.4.0+）中 CSSProperty.js 被从 react/lib 挪到 react-dom/lib 里了而 antd 依赖的 rc-editor-mention 依赖的 rc-editor-core 还依赖旧版本。
可能相关：https://github.com/sstur/draft-js-export-html/issues/51

**Comment by yesmeck** [comment]
Try `rm -rm node_modules && npm install`.

**Comment by Centaur** [comment]
@yesmeck 删除 node_modules 后重新 npm install 确实解决了问题。
