### ISSUE TITLE
Popconfirm弹窗跳到左上角

### ISSUE THREAD

**Issue by wengxiaofeng** [ant-design/ant-design#41215]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-demo-forked-87kt98?file=/index.js)

### Steps to reproduce

移动到sss，单击执行

### What is expected?

弹窗不跳动

### What is actually happening?

弹窗跳动到左上角

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 16.13.1 |
| System | macos  |
| Browser | chrome版本 107.0.5304.110（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
你的重现 antd 用的 4.7，属性用的却是最新的 items。请调整一下[重现](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-demo-forked-z1peoo?file=/package.json)哈~

**Comment by wengxiaofeng** [comment]
> 你的重现 antd 用的 4.7，属性用的却是最新的 items。请调整一下[重现](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-demo-forked-z1peoo?file=/package.json)哈~

改了

**Comment by wengxiaofeng** [comment]
其实和这个issue是一样的，https://github.com/ant-design/ant-design/issues/41180
突然不兼容了

**Comment by yoyo837** [comment]
那就 Duplicate of #41180 了
