### ISSUE TITLE
[BUG] select dropdownAlign not working

### ISSUE THREAD

**Issue by hemengke1997** [ant-design/ant-design#41222]
### Reproduction link

[https://stackblitz.com/edit/react-xgx7c2?file=demo.tsx](https://stackblitz.com/edit/react-xgx7c2?file=demo.tsx)

### Steps to reproduce

see above

### What is expected?

dropdownAlign works

### What is actually happening?

dropdownAlign not working

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2 |
| System | windows11 |
| Browser | edge latest |

**Comment by hemengke1997** [comment]
In 5.2.3, everything works well

**Comment by zombieJ** [comment]
fixed in https://github.com/react-component/trigger/pull/339
Pls reinstall node_modules instead:

https://stackblitz.com/edit/react-xgx7c2-wmdcof?file=package.json
