### ISSUE TITLE
Clear Autocomplete after form submit

### ISSUE THREAD

**Issue by shivekkhurana** [ant-design/ant-design#4122]
Dear Community,

Ant Design is an awesome ui system and we've been using it extensively for the past few months. 
Thank you for designing and open sourcing this lib. 

--

I need to clear the AutoComplete component after the form has been submitted. 

I have tried to do the following : 
```
...
<AutoComplete ref='toField' />
...

// In a callback 
this.refs.toField.value = null;
```
But it isn't working. How can this be done ?

Thanks.

**Comment by afc163** [comment]
Do not use ref to control component state, use React state.

http://facebook.github.io/react/docs/forms.html#controlled-components

http://codepen.io/afc163/pen/MbQXRV?editors=001

**Comment by shivekkhurana** [comment]
@afc163 Thank you.
