### ISSUE TITLE
从v4升级到v5后，启动项目，报错These dependencies were not found

### ISSUE THREAD

**Issue by EasonBeaty** [ant-design/ant-design#41224]
### Reproduction link

[https://github.com/ant-design/ant-design/tree/master/components/auto-complete](https://github.com/ant-design/ant-design/tree/master/components/auto-complete)

### Steps to reproduce

从v4升级到v5
npm run start
启动项目

### What is expected?

启动成功

### What is actually happening?

启动失败报错
These dependencies were not found:

* antd/es/auto-complete/style in ./src/components/HeaderSearch/index.jsx
* antd/es/locale-provider/en_US in ./src/pages/.umi/LocaleWrapper.jsx
* antd/es/locale-provider/pt_BR in ./src/pages/.umi/LocaleWrapper.jsx
* antd/es/locale-provider/style in ./src/pages/.umi/LocaleWrapper.jsx
* antd/es/locale-provider/zh_CN in ./src/pages/.umi/LocaleWrapper.jsx
* antd/es/locale-provider/zh_TW in ./src/pages/.umi/LocaleWrapper.jsx
* antd/es/version/style in ./src/pages/.umi/LocaleWrapper.jsx

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | any |
| System | any |
| Browser | any |

**Comment by zombieJ** [comment]
参考一下迁移文档哈：https://ant.design/docs/react/migration-v5-cn
