### ISSUE TITLE
使用@ant-design/static-style-extract导出自定义主题样式时出错

### ISSUE THREAD

**Issue by silentim** [ant-design/ant-design#41226]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-twgu10)

### Steps to reproduce

根据官方文档https://ant.design/docs/react/customize-theme-cn#%E6%95%B4%E4%BD%93%E5%AF%BC%E5%87%BA：
```
1. 创建文件 gen.mjs
2. 在package.json文件中添加相关命令  "predev": "node ./gen.mjs" 以及 "prebuild": "node ./gen.mjs"
3. 运行npm run dev，在生成文件时出现错误，无法继续
```

### What is expected?

可以正常运行

### What is actually happening?

出现错误，被终止并退出终端

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | macbook |
| Browser | chrome |

### 错误截图

![WX20230314-164320@2x](https://user-images.githubusercontent.com/65599013/224944891-b85d5abf-382f-4930-85ac-0d5cc749ca95.png)

**Comment by MadCcc** [comment]
nodejs 默认处理不了 jsx，需要 jsx-node 或者 ts-node

**Comment by silentim** [comment]
换成 ts-node 也是一样的

**Comment by MadCcc** [comment]
> 换成 ts-node 也是一样的

配置 `jsx` 了么

**Comment by silentim** [comment]
配置了 "jsx": "react-jsx"
