### ISSUE TITLE
建议：space内的子组件是否可以设置其包裹组件的属性？

### ISSUE THREAD

**Issue by konayukis** [ant-design/ant-design#41227]
### Reproduction link

[https://ant.design/components/space-cn](https://ant.design/components/space-cn)

### Steps to reproduce

 ```tsx
<Space className={classnames(styles.menuOperate, { collapsed: collapsed })}>
      <div>1<div/>
      <div style={{flex: 1}}>2<div/>  // 不生效，因为space会自动包裹一层父元素
       <div>3<div/>
 </Space>
```

### What is expected?

可以支持子元素中flex: 1 类似的效果

### What is actually happening?

不支持

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
Space 本身就是轻量级的内联组件，如果对于布局有额外要求可以直接用 div + flex 哈~

**Comment by xyJen** [comment]
> Space 本身就是轻量级的内联组件，如果对于布局有额外要求可以直接用 div + flex 哈~

Space 组件包裹默认使用的是div，未来考虑自定义包裹元素吗？

```
<Space comp="span">
    <a>this is one</a>
    <a>this is two</a>
</Space>
```

html 元素
```
<div>
    <span><a>this is one</a></span>
    <span><a>this is two</a></span>
</Space>
```
