### ISSUE TITLE
Image.PreviewGroup 不支持 preview.rootClassName

### ISSUE THREAD

**Issue by sanheng** [ant-design/ant-design#41230]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-zhang-tu-pian-yu-lan-antd-5-3-1-forked-3e3302?file=/demo.tsx)

### Steps to reproduce

给 Image.PreviewGroup 自定义 preview.rootClassName 无效，因为在 antd 里面写死了[rootClassName](https://github.com/ant-design/ant-design/blob/master/components/image/PreviewGroup.tsx#L52)

```
 <Image.PreviewGroup
    preview={{
      onChange: (current, prev) => console.log(`current index: ${current}, prev index: ${prev}`),
      rootClassName: 'rootClassName-test'
    }}
  >
...
 </Image.PreviewGroup>
```

### What is expected?

自定义的 rootClassName 传给 rc-image

### What is actually happening?

自定义的 rootClassName 没有传给 rc-image 的 group preview.rootClassName

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | macos: 13.2.1 (22D68) |
| Browser | chrome: 版本 111.0.5563.64（正式版本） (x86_64) |

**Comment by Yuiai01** [comment]
目前好像不支持自定义 preview.rootClassName 的，可见 https://ant.design/components/image-cn#previewtype ，或许可以用  `maskClassName` 替代？

**Comment by sanheng** [comment]
> 目前好像不支持自定义 preview.rootClassName 的，可见 https://ant.design/components/image-cn#previewtype ，或许可以用 `maskClassName` 替代？

我试了不行的，不会加给预览的 class，只会加给展示的 hover 的那个 mask。

我看 rc-image 是支持的 group.preview.rootClassName，是因为 antd 里面写死了。

**Comment by Yuiai01** [comment]
> > 目前好像不支持自定义 preview.rootClassName 的，可见 https://ant.design/components/image-cn#previewtype ，或许可以用 `maskClassName` 替代？
> 
> 我试了不行的，不会加给预览的 class，只会加给展示的 hover 的那个 mask。
> 
> 我看 rc-image 是支持的 group.preview.rootClassName，是因为 antd 里面写死了。

那我来康康~
