### ISSUE TITLE
RadioGroup with div components

### ISSUE THREAD

**Issue by jcherqui** [ant-design/ant-design#4123]
Hello,

RadioGroup work correctly with this code : 

```jsx
<RadioGroup value={2}>
    <Radio value={1}>A</Radio>
    <Radio value={2}>B</Radio>
</RadioGroup>
````

But it doesn't set default value when I have div components inside : 

```jsx
<RadioGroup className="choices" value={2}>
    <div>
        <img src="http://placehold.it/100?text=A"/>
        <Radio value={1}>A</Radio>
    </div>
    <div>
        <img src="http://placehold.it/100?text=B"/>
        <Radio value={2}>B</Radio>
    </div>
</RadioGroup>
```

I would like a result like this : http://codepen.io/marty69/pen/eBVRyo
This case works with `react-radio-group`.

**Comment by afc163** [comment]
RadioGroup is only a syntactic sugar for generating Radios quickly. You have to create your own HOC RadioGroup for customized needs by `Radio`.
