### ISSUE TITLE
tooltip被遮挡了是否符合预期

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#41235]
### What problem does this feature solve?

https://ant.design/components/tooltip-cn#components-tooltip-demo-shift 在官网提供的demo中  位置是否可以自动修复

### What does the proposed API look like?

期望是可以自动调整位置 不被遮挡

**Comment by Lliuxs** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/35122287/224970619-931c1a59-3809-4af2-a096-f44e57dbbbae.png">

**Comment by zombieJ** [comment]
神奇，本地是好的。build 完就是错的：
<img width="344" alt="截屏2023-03-15 18 15 28" src="https://user-images.githubusercontent.com/5378891/225278935-9af5e5cb-3237-4e2d-8387-b5fe6c5e14f3.png">

**Comment by Lliuxs** [comment]
大佬 现在看是好了的。

**Comment by zombieJ** [comment]
> 大佬 现在看是好了的。

我这边看还是挂的， @PeachScript 说是构建相关的事情，还在看哈~

**Comment by Lliuxs** [comment]
这个问题在最新版的 rc-trigger。v6上也是存在这种问题的。
rc-tooltip中调用rc-trigger的时候  如果走默认的 top设置的话 他不会调整left和right的值 就会出现left小于0的情况
在rc-trigger中的 useAlign的hook逻辑感觉还是有问题的。
用5.3版本的话 使用的是  rc-align中的dom-align就是表现正常
默认的top位置 在rc-trigger中的这个计算可能是负数 但是在  rc-tooltip中传递的 placementInfo 为
const autoAdjustOverflowTopBottom = {
  shiftX: 64,
  adjustY: 1,
};
会导致left和right的位置不调整
<img width="910" alt="image" src="https://user-images.githubusercontent.com/35122287/225492441-f73ad756-9d6b-4352-83e6-7c5401909df3.png">
<img width="799" alt="image" src="https://user-images.githubusercontent.com/35122287/225492770-e1708c7a-d4f0-4613-ba1e-6bb487fa8569.png">

位置不调整就会出现left<0被遮挡的问题

5.3 正常 left调整为0了
<img width="364" alt="image" src="https://user-images.githubusercontent.com/35122287/225493127-dee6f2b9-b88f-4b89-8874-f0a1815ad5a2.png">

新版的left为负值 表现不正常

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/35122287/225493274-53265170-1478-488b-b39a-5dd372d5a58e.png">


在5.3中的话 overflow的值统一为:  overflow: autoAdjustOverflow,
<img width="454" alt="image" src="https://user-images.githubusercontent.com/35122287/225492884-75056d7f-61df-4c83-b101-fc21e59f7847.png">

**Comment by zombieJ** [comment]
> 这个问题在最新版的 rc-trigger

这个搞个 codesandbox 看看？

**Comment by Lliuxs** [comment]
这个应该不是antd的问题 是我在用 @rc-component/trigger 最新版的时候发现的。 如果是  "@rc-component/trigger": "^1.5.5", 这个依赖就存在问题了
大佬可以看看 useAlign这个代码 我觉得就是位置没调整

现在antd中的rc-trigger是 "rc-trigger": "^5.3.4",的版本 还不是最新的就没这个问题

**Comment by afc163** [comment]
> 这个搞个 codesandbox 看看？

搞个 codesandbox 重现，我们来解决。

**Comment by Lliuxs** [comment]
https://github.com/react-component/trigger/issues/333

**Comment by zombieJ** [comment]
> codesan中的元素不是被设置了...

这个地址发一下哈

**Comment by Lliuxs** [comment]
> 

https://codesandbox.io/s/antd-reproduction-template-forked-z6txrc?file=/index.css

我按照 ant-tooltip的定位给设置了一个 absolute的定位

<img width="567" alt="position" src="https://user-images.githubusercontent.com/35122287/226267930-6548feae-02e6-4758-8c7f-efb4e70ede2a.png">

可以看long content和较短的内容的对比

<img width="453" alt="1" src="https://user-images.githubusercontent.com/35122287/226267997-4c33d1e5-89c3-48a5-8e26-1689f05f7bb5.png">

<img width="473" alt="2" src="https://user-images.githubusercontent.com/35122287/226268016-92742798-6eea-4075-a7ee-dd98a6573122.png">

**Comment by Yuiai01** [comment]
![image](https://user-images.githubusercontent.com/112228030/226328093-90c95c5d-8834-4392-81a4-95e0f745db76.png)
奇怪哩，我这咋不跟你一样 🤔

**Comment by afc163** [comment]
@Lliuxs 问题解决了么？

**Comment by codegun6545** [comment]
被同样的问题困扰，我的antd的版本是：  "antd": "4.24.7",
