### ISSUE TITLE
 Can't resolve 'rc-util/es/dom/isVisible' ，原因是node_modules/rc-util/es/Dom目录名开头的D是大写，但是在node_modules/@rc-component/trigger/es/hooks/useAlign.js文件中import isVisible from "rc-util/es/dom/isVisible";的dom是小写的d

### ISSUE THREAD

**Issue by chenchengwork** [ant-design/ant-design#41236]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/package.json)

### Steps to reproduce

无

### What is expected?

编译通过

### What is actually happening?

ERROR in ../node_modules/@rc-component/trigger/es/hooks/useAlign.js 
Module not found: Error: Can't resolve 'rc-util/es/dom/isVisible' 

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | ubuntu22.04 |
| Browser | chrome |

---
我这边查到问题的原因是node_modules/rc-util/es/Dom目录名开头的D是大写，但是在node_modules/@rc-component/trigger/es/hooks/useAlign.js文件中import isVisible from "rc-util/es/dom/isVisible";的dom是小写的d,在linux系统中文件名是区分大小写，所以造成编译报错，希望下一版发布的时候能修正这个问题

**Comment by MadCcc** [comment]
已经修复，+ @rc-component/trigger 1.5.5，重新安装依赖即可
