### ISSUE TITLE
在Form.List 下面存在多个同级的Form.List会出现 Encountered two children with the same key, `0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version

### ISSUE THREAD

**Issue by liuxiansheng2018** [ant-design/ant-design#41233]
### Reproduction link
复现链接
https://codesandbox.io/s/fu-za-de-dong-tai-zeng-jian-biao-dan-xiang-antd-5-3-1-forked-m101k4?file=/demo.tsx

### Steps to reproduce

打开demo。 查看控制台会发现key 重复

### What is expected?

key 不会报错

### What is actually happening?

key 不会重复， 并报错

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | macos monterey |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="1784" alt="图片" src="https://user-images.githubusercontent.com/507615/224967174-f1a597da-927b-4e55-9a05-ec81b4a6ff6b.png">

好像没重现出来？

**Comment by liuxiansheng2018** [comment]
这个是复现连接 https://codesandbox.io/s/fu-za-de-dong-tai-zeng-jian-biao-dan-xiang-antd-5-3-1-forked-m101k4?file=/demo.tsx

**Comment by zombieJ** [comment]
> 这个问题是由于 `filed` 对象里包含了 key，然后将同样的 key 值赋值给了两个同级 list 导致了这个问题的产生，或许可以过滤一下 key 值然后进行使用~

+1，按照 VDM 结构找一下： https://codesandbox.io/s/fu-za-de-dong-tai-zeng-jian-biao-dan-xiang-antd-5-3-1-forked-pr7vd4?file=/demo.tsx
