### ISSUE TITLE
Select选择器是否可以支持禁用原生的title属性

### ISSUE THREAD

**Issue by programmer-jiangtao** [ant-design/ant-design#41247]
### What problem does this feature solve?

目前业务需要在选择器上面要定制一个tooltip，但是原生的title属性没法禁止，导致出现两个提示框，影响客户体验

### What does the proposed API look like?

提供一个title属性来定制提示内容，可以是字符串或者函数来扩展title或者直接禁用title

**Comment by afc163** [comment]
title 设置为 `""` 即可。

**Comment by programmer-jiangtao** [comment]
> title 设置为 `""` 即可。

不行，这个属性设置了没有效果，我看过源码，你们这个title是设置在已选择的内容span上的；
Select直接设置title影响不了选择的内容

**Comment by programmer-jiangtao** [comment]
> title 设置为 `""` 即可。

这个title设置的源码在rc-select里面，你们antd这边是不是也改不了？

**Comment by afc163** [comment]
@programmer-jiangtao 最好能给个重现的 codesandbox

**Comment by programmer-jiangtao** [comment]
> @programmer-jiangtao 最好能给个重现的 codesandbox

你们antd的官方文档库select组件只要选过值，鼠标放在输入框上都会出现title，而且没法取消这个title，这难道不是demo?

**Comment by afc163** [comment]
看下是否符合预期：https://codesandbox.io/s/ji-ben-shi-yong-antd-5-3-1-forked-tftuqd

**Comment by programmer-jiangtao** [comment]
> 看下是否符合预期：https://codesandbox.io/s/ji-ben-shi-yong-antd-5-3-1-forked-tftuqd
> 
> ref #14894

如果是固定数据源是没有问题的，但是不符合我们这边业务的预期，我们这边的数据源是远程数据源，第一次是不加载数据源的，也就是options是空，这样select的初始值在options里面找不到，title会赋值undefined，导致rc-select里面getTitle方法会直接取初始值的label作为title

**Comment by afc163** [comment]
是不是对远程数据源做一次加工再传给 options 就行了。

**Comment by afc163** [comment]
> 也就是options是空，这样select的初始值在options里面找不到，title会赋值undefined，导致rc-select里面getTitle方法会直接取初始值的label作为title

给个重现我看看？

**Comment by afc163** [comment]
懂了，重现在这里 https://codesandbox.io/s/ji-ben-shi-yong-antd-5-3-1-forked-0fsdlb?file=/demo.tsx

**Comment by programmer-jiangtao** [comment]
> 懂了，重现在这里 https://codesandbox.io/s/ji-ben-shi-yong-antd-5-3-1-forked-0fsdlb?file=/demo.tsx

对，大佬，有方案能解决吗

**Comment by zombieJ** [comment]
> 如果是固定数据源是没有问题的，但是不符合我们这边业务的预期，我们这边的数据源是远程数据源，第一次是不加载数据源的，也就是options是空，这样select的初始值在options里面找不到，title会赋值undefined，导致rc-select里面getTitle方法会直接取初始值的label作为title

这个是预期的，`title` 是跟着 option 走的，没有就会按照默认方式填充，它不是 Select 的 `title`。如果是异步数据，直接 HOC 一下就好了 ：
https://codesandbox.io/s/ji-ben-shi-yong-antd-5-3-1-forked-qfhq15?file=/demo.tsx

**Comment by afc163** [comment]
我在改了，有办法。

**Comment by afc163** [comment]
https://github.com/react-component/select/pull/931

这样就可以指定 `<Select title="" />` 来重置里面的默认 title 了。

**Comment by weixihd** [comment]
Select的选项数据是从后端获取，前端需要做一下转换把英文的标记映射到中文名称上，当鼠标悬停在选择框上时，就不能显示当前选中项的 label，这个要怎么解决呀？因为选择框的宽度是有限的，名称太长显示不了，就需要鼠标悬停的时候能出现这个title。表单是用JSON Schema 写的。

**Comment by Userluckytian** [comment]
#### 异常效果图 【antd-design版本：5.17.0】

![异常图](https://github.com/user-attachments/assets/26865cc3-3602-44a6-b899-00383ab0815c)

#### 描述：
如上图，我自定义了options的展示方式，但是options选项中HTML标签的title属性仍生效。导致其遮挡了我定义的tooltip内容。
#### 期望结果：
移除默认的title内容
#### 尝试：
根据上面介绍，在Select标签上添加title=“” 并没有效果。
#### 解决方式：
```javascript

<Select
    rootClassName='FMC-target-select'
    showSearch allowClear
    options={targetFieldsArr}
    placeholder='请选择字段'
    onFocus={() => removeTitleProps()}       // <--------------Here！
    optionRender={(option) => {
        return (
            <Tooltip placement="right" title={option.data.des}>
                {option.data.label}
            </Tooltip>
        )
    }}
/>


//  remove title function
const removeTitleProps = () => {
    const optionNode = document.querySelectorAll('.ant-select-item-option');
    if (optionNode && optionNode.length) {
        optionNode.forEach((item: any) => {
            item.removeAttribute('title');
        })
    }
};


```
声明：希望这个问题，能被官方解决下[抱拳]，这里仅提供了一种临时的处理办法。如果大家有更好的方式，建议在下面补充。🎉
