### ISSUE TITLE
Wrong d.ts

### ISSUE THREAD

**Issue by ae-draft** [ant-design/ant-design#4124]
```
ERROR in .../node_modules/antd/lib/upload/interface.d.ts
(2,8): error TS1192: Module '".../node_modules/@types/react/index"' has no default export.
```

`import  React from 'react';` - wrong!
`import * as React from 'react';` - correct for typescript!

This error inside all d.ts files.

Definitions installed from @types/antd correct, but d.ts in node_modules throw error again!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design#typescript

`"allowSyntheticDefaultImports": true`

**Comment by afc163** [comment]
Don't install definitions from `@types/antd`, use antd directly.
