### ISSUE TITLE
pagination 组件 showTotal 的 range 参数是 undefined

### ISSUE THREAD

**Issue by lucky3mvp** [ant-design/ant-design#4125]
#### 发生问题的环境是：

- antd 版本: 2.4.3
- 操作系统及其版本: win7 64位
- 浏览器及其版本: chrome  55.0.2883.75 m

#### 您做了什么？请提供尽可能详细的重现步骤。
使用 pagination 组件的 showTotal 属性时，官网上的说明 showTotal 是 Function(total, range) 这样的函数，但是实际上在使用时 不能获取到 range 参数，console.log 打印出的 range 为 undefined。
showTotal: (total, range) => {
			console.log('total: ', total);
			console.log('range: ', range);
			// `${range[0]}-${range[1]} of ${total} items`
		}

#### 您期待的结果是:
像官网例子一样能正常使用

#### 实际上的结果是:
range:  undefined

**Comment by afc163** [comment]
https://ant.design/changelog#2.5.0

**Comment by lucky3mvp** [comment]
谢谢，已经升级了
