### ISSUE TITLE
DatePicker 组件在 picker=month｜quarter｜year 时，  dateRender这个函数不生效

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#41255]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-3-1-forked-qqptm5?file=/demo.tsx:486-496)

### Steps to reproduce

打开demo即可看到 

### What is expected?

期望能函数能够正常运行

### What is actually happening?

在 picker=month｜quarter｜year 时，并不生效

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | React17/18 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by Ali-ovo** [comment]
目前我用的 antd的版本是 `4.17.0`，但是我看 5.x 也有这个问题

**Comment by kiner-tang** [comment]
确实是这样，我来看看

**Comment by kiner-tang** [comment]
在'month'当中，可以使用`monthCellRender`

**Comment by Ali-ovo** [comment]
> 在'month'当中，可以使用`monthCellRender`

对 这个是可以的 但是剩下两个坏掉了

**Comment by kiner-tang** [comment]
> > 在'month'当中，可以使用`monthCellRender`
> 
> 对 这个是可以的 但是剩下两个坏掉了

我们会在后续版本提供新的 api 支持 这些类型的 render 的统一处理，开发进展会在这里同步。

**Comment by Ali-ovo** [comment]
> > > 在'month'当中，可以使用`monthCellRender`
> > 
> > 
> > 对 这个是可以的 但是剩下两个坏掉了
> 
> 我们会在后续版本提供新的 api 支持 这些类型的 render 的统一处理，开发进展会在这里同步。

好的

**Comment by kiner-tang** [comment]
- https://github.com/ant-design/ant-design/discussions/41303

**Comment by Ali-ovo** [comment]
> * [📋 [RFC] Unify API about picker's custom render #41303](https://github.com/ant-design/ant-design/discussions/41303)

关于这个 API 的更新会同步到V4的版本么

**Comment by Wxh16144** [comment]
> 关于这个 API 的更新会同步到V4的版本么

不会，v4 现在只做 bug 修复。

**Comment by yoyo837** [comment]
Close by #41584
