### ISSUE TITLE
Upload图片上传按钮样式丢失

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design#41256]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yong-hu-tou-xiang-antd-5-3-1-forked-b7mlel?file=/demo.tsx:319-337)

### Steps to reproduce

将antd版本从最新的版本修改为4.23.5，Upload按钮的样式丢失，除非手动引入antd/dist/antd.css，但是在项目中引入，会影响到页面中的其他样式

### What is expected?

antd4.23.5版本的Upload样式恢复正常

### What is actually happening?

antd4.23.5版本的Upload样式不正常

| Environment | Info |
| --- | --- |
| antd | 4.23.5 |
| React | 16.14.0 |
| System | windows10 |
| Browser | chrome111 |

**Comment by afc163** [comment]
antd 4 需要单独引入 css 的，否则没有样式，这个是符合预期的。
