### ISSUE TITLE
Antd Filter should not only be limited to table

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#41254]
### What problem does this feature solve?

Button should also have the ability to filter data

### What does the proposed API look like?

Button type ='filterButton'

**Comment by tempoeric** [comment]
i am expecting something like this
<img width="497" alt="image" src="https://user-images.githubusercontent.com/42777871/225241759-63904db6-531b-4cbb-b55b-ce15acb903a3.png">

**Comment by tempoeric** [comment]
after selecting the data filtered should be like this
<img width="471" alt="image" src="https://user-images.githubusercontent.com/42777871/225241948-b820afb2-531c-4eb6-a797-3f40ca517cca.png">

**Comment by tempoeric** [comment]
> Not planned yet. You could implement it yourself.

i dont know how could you help me @MadCcc please i know you are busy but i am asking for your help

**Comment by tempoeric** [comment]
> Not planned yet. You could implement it yourself.

i will really much appreciate if you could help me implement this @MadCcc

**Comment by afc163** [comment]
I believe it is better and easier to implement it in your application.

**Comment by tempoeric** [comment]
@afc163 can you just give me a sample please?

**Comment by tempoeric** [comment]
i am asking for your help @afc163 and @MadCcc

**Comment by tempoeric** [comment]
should i funded this @afc163 for help cause i really need your help

**Comment by yoyo837** [comment]
This is not a situation that the ui library needs to consider. It depends on your own logic needs. Sorry, we can do nothing.

**Comment by tempoeric** [comment]
> This is not a situation that the ui library needs to consider. It depends on your own logic needs. Sorry, we can do nothing.

i am a new junior developer for almost a year thats why im asking help here since i do not know how to implement it based on the design i provided i am willing to fund this task if needed

**Comment by tempoeric** [comment]
can i reopen this to be funded?
