### ISSUE TITLE
Form.Item Label requiredMark position

### ISSUE THREAD

**Issue by Ahmad129096** [ant-design/ant-design#41259]
### What problem does this feature solve?

In some design requiredmark of the required field is placed at the right of label, but currently we only have it on the left side of label.

### What does the proposed API look like?

`<Form  requiredMarkPosition={'right'}/> `default behavior would be same as it is right now. person should be able to chnage required mark position at Form level or at least at the Item level

**Comment by zombieJ** [comment]
In doing so, the API becomes too fragmented. You can HOC Form.Item to realize it:
https://codesandbox.io/s/bi-xuan-yang-shi-antd-5-3-1-forked-sodhjo?file=/demo.tsx

**Comment by Ahmad129096** [comment]
Thank you so much. It is really helpful

**Comment by fireflysmile** [comment]
In doing so:
const customizeRequiredMark = (label: React.ReactNode, { required }: { required: boolean }) => (
  <>
    {label}
    {required && <span style={{ color: "red" }}>*</span>}
  </>
);

<Form requiredMark={customizeRequiredMark}></Form>

**Comment by fireflysmile** [comment]
In doing so:
`const customizeRequiredMark = (label: React.ReactNode, { required }: { required: boolean }) => (
  <>
    {label}
    {required && <span style={{ color: "red" }}>*</span>}
  </>
);
use
<Form requiredMark={customizeRequiredMark}></Form>
`

**Comment by fireflysmile** [comment]
```
const customizeRequiredMark = (label: React.ReactNode, { required }: { required: boolean }) => (
  <>
    {label}
    {required && <span style={{ color: "red" }}>*</span>}
  </>
);
<Form requiredMark={customizeRequiredMark}></Form>
```

**Comment by zxlvera** [comment]
hijacking this thread, is it possible to display the requiredMark without declaring `label` and place the requiredMark on the input instead e.g. placeholder prop?

**Comment by Ahmad129096** [comment]
> hijacking this thread, is it possible to display the requiredMark without declaring `label` and place the requiredMark on the input instead e.g. placeholder prop?

you can use a similar pattern for putting a required mark on input. All you have to do is to not add label property for form item and use an extra span rendered conditionally based on same rule your required field is working

**Comment by tungxd96** [comment]
> fireflysmile

Disregard this solution. This will also reverse the tooltip position. Second the solution from @fireflysmile

**Comment by tungxd96** [comment]
> Another way is to modify the css of the related classes and use row-reversed. That will bring the required mark from left to right. Here's the snippet:
> 
> ```css
> .ant-form-item-required {
>   flex-direction: row-reverse;
> }
> 
> .ant-form-item-required::before {
>   margin-left: 4px;
> }
> 
> .ant-form-item-required::after {
>   width : 0;
>   margin: 0 !important;
> }
> ```

Disregard this solution. This will also reverse the tooltip position. Second the solution from @fireflysmile

**Comment by LasyaHemadri** [comment]
> ### What problem does this feature solve?
> In some design requiredmark of the required field is placed at the right of label, but currently we only have it on the left side of label.
> 
> ### What does the proposed API look like?
> `<Form requiredMarkPosition={'right'}/> `default behavior would be same as it is right now. person should be able to chnage required mark position at Form level or at least at the Item level

**Comment by LasyaHemadri** [comment]
This worked for me!!

**Comment by LasyaHemadri** [comment]
> > ### What problem does this feature solve?
> > In some design requiredmark of the required field is placed at the right of label, but currently we only have it on the left side of label.
> > ### What does the proposed API look like?
> > `<Form requiredMarkPosition={'right'}/> `default behavior would be same as it is right now. person should be able to chnage required mark position at Form level or at least at the Item level



This worked for me!

**Comment by dule-kitemetric** [comment]
I found a solution for this: you can custom your Form.Item to show the required mark on the RIGHT of the label by default via the global ConfigProvider.

Here is the example code (I use TailwindCss)
```TS
<ConfigProvider
              form={{
                requiredMark: (label, { required }) => (
                  <>
                    {label}
                    {required && <span className="ml-1 text-ant-red">*</span>}
                  </>
                ),
              }}
            >
              // ........
</ConfigProvider>
```
