### ISSUE TITLE
希望 RangePicker 的format 支持function

### ISSUE THREAD

**Issue by xiaoming0827** [ant-design/ant-design#41257]
### What problem does this feature solve?

1、希望和DatePicker的format功能对齐，也支持function
2、RangePicker同样也有需求进行自定义的格式化回显，比如日期前加一些自定义文案，甚至日期直接显示中文如农历日期等，format支持function将会RangePicker的回显更加零活

### What does the proposed API look like?

希望和DatePicker的format功能对齐，也支持function

**Comment by Wxh16144** [comment]
看了一眼 [`rc-picker` 的逻辑](https://github.com/react-component/picker/blob/f512f18ed59d6791280d1c3d7d37abbb9867eb0b/src/RangePicker.tsx#L456)，RangePicker 的 format 属性是支持function 的。如下：

```tsx
<RangePicker
  defaultValue={[dayjs('2015/01/01', dateFormat), dayjs('2015/01/01', dateFormat)]}
  format={(value) => `test-${value.format(dateFormat)}`}
/>
```

回头我去更新一下组件文档说明。
