### ISSUE TITLE
Drawer抽屉组件，这是一个什么边框，只要一焦聚它就出现。也找不到css去掉它！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design#41258]
### Reproduction link

[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce

只要一打开drawer组件就会发现有这个边框，　也找不到css去掉它,关闭抽屉后，再次点击鼠标它就消失了！找也找不到对应的css.
<img width="789" alt="image" src="https://user-images.githubusercontent.com/12706830/225274102-efbf2a78-98d5-4f21-bb3a-cc126d95ff04.png">

### What is expected?

无边框

### What is actually happening?

有边框

<img width="789" alt="image" src="https://user-images.githubusercontent.com/12706830/225274162-b4862e97-b7e9-4c5c-ad1d-6a7c3a4b2755.png">

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 17.0.2 |
| System | macos |
| Browser | chorme 86.0.4240.183 |

**Comment by MadCcc** [comment]
这是浏览器默认 focus 样式吧
