### ISSUE TITLE
Maximum update depth exceeded on Select components

### ISSUE THREAD

**Issue by Kestutis** [ant-design/ant-design#41261]
### Reproduction link

[https://ant.design/components/select](https://ant.design/components/select)

### Steps to reproduce

Open https://ant.design/components/select and try multiple time focus and remove focus from Select component quickly. I made a screen recording of it: https://www.dropbox.com/s/4uhgjhjr5spq7hv/screen-capture.webm

We started to catch this issue with our e2e runner Cypress first. 

### What is expected?

Select works as usual 

### What is actually happening?

Select crashes with `Maximum update depth exceeded` message

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome 110 |

---
My guess this started to happen after https://github.com/react-component/resize-observer/pull/172 PR

**Comment by Wxh16144** [comment]
It seems that this problem only occurs in the documentation site?

In the document:

https://user-images.githubusercontent.com/32004925/225413469-59b5ba36-725f-40a6-a48c-51d991b03ba5.mp4



---

In the sandbox:


https://user-images.githubusercontent.com/32004925/225413536-f7622d3d-19d0-425f-872f-2200bea1a484.mp4

**Comment by Kestutis** [comment]
It's same with sandbox: 


https://user-images.githubusercontent.com/431551/225430766-b2483ac6-ddf7-4cb6-bf22-78531be38e86.mp4

**Comment by maximelafarie** [comment]
Same with `<Dragger>` / `<Upload>` component when uploading more than 50 files at the same time (`multiple: true`). 

<img width="1465" alt="image" src="https://github.com/ant-design/ant-design/assets/5319267/aff989a0-61dc-4997-8c21-57d39b0a8e62">
