### ISSUE TITLE
Tooltip: Setting state of "open" prop in "false" via button from the title content on mobile device causes onChange event to fire with "true" value

### ISSUE THREAD

**Issue by AlexEmashev** [ant-design/ant-design#41260]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-silence-pbm01c?file=/src/App.tsx)

### Steps to reproduce

1. Open sandbox on mobile device or in responsive view.
2. Click a header with text "Click me in responsive view". Tooltip appears.
3. Click "X" button on the tooltip. The tooltip closes and opens once again. "X" button sets "open" prop to false. But "onOpenChange" callback fires with true value.
4. Click "X" button second time. The tooltip closes this time. But "onOpenChange" won't fire.

### What is expected?

Expected "X" button set state for "open" prop to "false" value and "onOpenChange" fires with "false" value.

### What is actually happening?

The "X" button sets state of "open" to false but "onOpenChange" fires with "true" value.

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 110.0.5481.100 |

---
In desktop mode this issue is not reproduced.
There were no such problem with on 5.1.7 if I recall it correctly.

**Comment by Wxh16144** [comment]
This is what seems reasonable and not a mistake. 🤔

**Comment by AlexEmashev** [comment]
I'd understand if it was how the Tooltip handles touch events to close itself. But it seems like it is not the case since tooltip won't close itself by touching it.

The case I'd like to cover is when the Tooltip has a lot of content in it which covers the major part of a phone screen. And user would have an option to click "Close" button to hide it.

**Comment by zombieJ** [comment]
Updated:
https://codesandbox.io/s/interesting-snow-y1n2ry?file=/package.json
