### ISSUE TITLE
alert组件中顶部公告没有适配暗黑模式

### ISSUE THREAD

**Issue by wangzj141** [ant-design/ant-design#41275]
### Reproduction link

[https://ant.design/components/alert-cn#components-alert-demo-banner](https://ant.design/components/alert-cn#components-alert-demo-banner)

### Steps to reproduce

点击右下角图标切换暗黑主题，其他组件都切换成了暗黑模式，但是顶部公告没有变化。

### What is expected?

变成暗色主题

### What is actually happening?

没有变化

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2 |
| System | window 11 |
| Browser | chrome |

**Comment by Yuiai01** [comment]
确实，我来康康~

**Comment by Wxh16144** [comment]
应该不是 Bug 吧，文档使用 iframe 模式。theme 没有包裹在里面。

**Comment by afc163** [comment]
可以想办法透传一下。
