### ISSUE TITLE
Select onClear property not working as expected when used with Form

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#41277]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-methods-antd-5-3-1-forked-5fuuno?file=/demo.tsx)

### Steps to reproduce

Choose an option on the "gender" select and then click on it's reset icon, the value will allways be reset to undefined, even if you try to use the Select prop onClear to set the form field value, it will overwrite any value used on setFieldsValue to undefined.

### What is expected?

It should allow to use the onClear property of Select to set any value to the field using the form state with setFieldsValue.

### What is actually happening?

The value is allways reset to 'undefined' when using the Select clear.

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | ^18.2.0 |
| System | Windows 10 |
| Browser | Brave |

---
If you have any use case that you need a Select to be cleared and its value set to anything other than undefined you can't. 
I have a use case that I need to clear the Select on a form to an empty string and another that I want to clear the Select on a form to a specific value, but that is not achievable now with using the clear of the Select. 
A workaround would be to put a external click on an icon or something and use that to fire setFieldsValue to a specific field and value, but I really don't see it as a good method, since the Select already has an option that makes said "icon" and has a property for listening to it's calls, onClear. 
A better API for this case would be onClear allowing the value set to the Select to be passed as a prop, something among the lines of resetValue='your_reset_value'.
I don't know the implications of that or if there's a better way of doing it, since on this case it would only make sense if your Select is inside a Form.

**Comment by afc163** [comment]
You should use `normalize` in this case.

**Comment by afc163** [comment]
https://codesandbox.io/s/form-methods-antd-5-3-1-forked-9rok5w?file=/demo.tsx

**Comment by balboFK** [comment]
Awesome! Works like a charm!
