### ISSUE TITLE
给面包屑添加onClick事件后，点击不触发事件

### ISSUE THREAD

**Issue by tonymaa** [ant-design/ant-design#41274]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-k8uc82?file=/index.js)

### Steps to reproduce

点击 Test01、Test02或Test03 都不触发onClick事件

### What is expected?

触发onClick事件，控制台输出结果

### What is actually happening?

不触发onClick事件，控制到无输出

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.1.0 |
| System | windows10 |
| Browser | Google Chrome	111.0.5563.65 (Official Build) (64-bit) (cohort: Stable) |

**Comment by notverysalty** [comment]
我试试看～

**Comment by romulorod** [comment]
If your title is a HTML node, you can add the onClick there and it works.
Not qurie sure why it doesn't work as a separate prop either. :/

**Comment by acyza** [comment]
看起来这是一个文档中存在但并未实现的功能。
