### ISSUE TITLE
设置 StyleProvider hashPriority='high' 后在pro-components组件内失效

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design#41272]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/faner11/react-antd/draft/goofy-solomon)

### Steps to reproduce

使用pro-components即可

### What is expected?

hashPriority='high' 生效

### What is actually happening?

在pro-components外部的生效了，pro-components组件包裹着的antd 组件不生效
![image](https://user-images.githubusercontent.com/26560612/223071635-e216dcd3-cbc4-42d0-bc95-a57876c0ea87.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | mac |
| Browser | 104 |

---
https://github.com/ant-design/pro-components/issues/6681
给pro-components提过，但是他们给的方案行不通

**Comment by MadCcc** [comment]
里面的 hash 被禁用了

**Comment by faner11** [comment]
@MadCcc 有解法吗

**Comment by chenshuai2144** [comment]
npm ls 一下，看看是不是两份provide了？

**Comment by faner11** [comment]
@chenshuai2144 只有一份

**Comment by chenshuai2144** [comment]
style 也是同一个版本吗？

**Comment by faner11** [comment]
是的

**Comment by faner11** [comment]
@chenshuai2144  大哥，没解决，别关闭呀

**Comment by ningkehua** [comment]
> @chenshuai2144 大哥，没解决，别关闭呀

请问有解决方案了吗？:(

**Comment by ningkehua** [comment]
> @chenshuai2144 大哥，没解决，别关闭呀

请问有解决方案了吗？:(

**Comment by yoyo837** [comment]
@chenshuai2144 关闭理由说一下吧

**Comment by yoyo837** [comment]
能提供个mini repo的zip看看吗

**Comment by yoyo837** [comment]
我个人大概分析了一下，你这边分别从 `antd` 和 `@formily/antd-v5` (打包后的)引用过 `StyleProvider`, 需要确保所有引用链路里 `StyleProvider` 是同一个，而不是分别来自 `dist` 和 `esm`。

请从这个方向定位一下。

**Comment by faner11** [comment]
我也跑了下demo，现在是正常的，antd 将hashPriority='high' 变成了默认值，我没有使用StyleProvider ，所以组件也是以hashPriority='high' 工作的。

**Comment by yoyo837** [comment]
> 我也跑了下demo，现在是正常的，antd 将hashPriority='high' 变成了默认值，我没有使用StyleProvider ，所有组件也是以hashPriority='high' 工作的。

上面的复现有使用 `StyleProvider`. 如果你说的是其他情况，可以提供复现开启一个新的issue.
