### ISSUE TITLE
关于传递className属性到组件根元素

### ISSUE THREAD

**Issue by alanwei0** [ant-design/ant-design#4129]
最近有一个项目重度使用antd，发现antd中的各个组件对className属性的处理并不一致，例如:
```
<Input className="test" />   {/* 这个test类传递到了输出的input标签上 */}
<InputNumber className="test" />  {/* 这个test类则不能传递到输出的input标签上 */}
```
对于类似没有传递的组件，如果需要添加修改一些样式，往往就需要在外层再包一层容器，一定程度上增加了开发成本，同时也使dom结构显得很冗余。

希望antd团队能够尽量保证`className`的传递，即使由于某些技术原因不能统一，那么也最好能够在组件的属性列表中显式声明是否接受`className`属性。

最后，也请考虑能否传递`data-*`这样的属性到组件内部。

**Comment by benjycui** [comment]
所有的组件都可以接受 `className` 属性，然后 `className` 添加在组件最外层的 DOM 元素上可以确保对组件内的 DOM 元素的最大控制，毕竟 CSS selector 无法反向选择。

**Comment by alanwei0** [comment]
@benjycui  似乎是这样的，但是我发现Input组件最外层有一个span，自定义的类为啥没有加在这个span上，而是加在input标签上的。。

**Comment by benjycui** [comment]
这个就是历史遗留问题了。。但是大部分组件都是上面说的那样。

**Comment by alanwei0** [comment]
@benjycui 好的
