### ISSUE TITLE
Config Provider API does not allow customization for button text. 

### ISSUE THREAD

**Issue by Danishkhurshid** [ant-design/ant-design#41291]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-btn-color-forked-fd6319?file=/src/App.tsx:327-926)

### Steps to reproduce

Customizing text for AntD button through Config Provider doesn't work. Above is the link to codesandbox that displays a button component. 

### What is expected?

I expect the button text to change change on hover but it doesn't. 

### What is actually happening?

I have played around all the text variables but nothing seems to be working. Ideally applying colorPrimaryTextHover should change the color of the button text but it doesn't. 

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React |  "react": "^18.2.0", |
| System | mac m1 |
| Browser | chrome |

**Comment by zombieJ** [comment]
`colorTextLightSolid`:
https://codesandbox.io/s/antd-btn-color-forked-kze7iy?file=/src/App.tsx:270-289

**Comment by zombieJ** [comment]
Button token can find here:
https://ant.design/components/button#design-token

<img width="835" alt="截屏2023-03-17 11 04 18" src="https://user-images.githubusercontent.com/5378891/225801985-a3d1d5cc-3ae4-4045-b467-15f6b0baf8da.png">

**Comment by Danishkhurshid** [comment]
@zombieJ how would you change the button text color on hover? Don't see any token for that?

**Comment by coderbahrom** [comment]
> `colorTextLightSolid`: https://codesandbox.io/s/antd-btn-color-forked-kze7iy?file=/src/App.tsx:270-289

but this is not working on your colorPrimaryTextHover: "green"

**Comment by a-giovana** [comment]
@Danishkhurshid  I'm having the exact same problem. how did you manage to resolve it?

**Comment by Danishkhurshid** [comment]
@a-giovana We ended up replacing ant with our own design system because of all the issues we were running into.
