### ISSUE TITLE
message希望可以支持定位是相对于自定义的container

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#41298]
### What problem does this feature solve?

1. 支持 duration为0的时候不关闭(这个比较好实现，因为是在其他组件看到有这种的设定 message中没有)
2. getContiner的表现不符合预期 (不知道是不是自己的使用问题)
3. 希望该属性可以在对应的方法中配置 而不是调用 config (这个问题很多人提过对应的issue了)

### What does the proposed API look like?

现在有个设计要求: message的信息是相对于弹出层的modal来说的

期望是相对于 传入的 getCOntainer容器定位的 而不是 body来定位的 
期望如下的效果:
显示元素是没有设置定位的，就不能相对于自定义的容器来定位

**Comment by Lliuxs** [comment]
实际效果:

<img width="1416" alt="企业微信20230317-131448@2x" src="https://user-images.githubusercontent.com/35122287/225818541-0da2249c-34eb-4053-ab8d-f533e310c7ca.png">

dom元素已经在对应的 container容器中了 但是对应的定位没有相对于容器来定位

期望的效果: 加上了一个 绝对定位的样式 可以相对于我自定义的容器来定位显示message的消息
如果做最小的改动 判断如果传入了自定义的就加一个 绝对定位的样式?

<img width="1495" alt="企业微信20230317-131240@2x" src="https://user-images.githubusercontent.com/35122287/225818447-7a03a943-fbd8-464e-8833-f2dfeef09583.png">

**Comment by Lliuxs** [comment]
大致代码如下: 
https://codesandbox.io/s/antd-reproduction-template-forked-3vrhg3?file=/index.js

**Comment by afc163** [comment]
从设计上来说这个有点奇怪。。。

**Comment by afc163** [comment]
> 支持 duration为0的时候不关闭(这个比较好实现，因为是在其他组件看到有这种的设定 message中没有)

这个现在是这样的。

**Comment by Lliuxs** [comment]
这个就是设计提的要求。。。

那我理解这个自定义的容器主要是为了解决qiankun的问题吗？ 只是将dom元素放在对应的container容器中 还有其他的用途么

我们设计的理解是message的信息在这个自定义的container容器中

**Comment by Lliuxs** [comment]
> > 支持 duration为0的时候不关闭(这个比较好实现，因为是在其他组件看到有这种的设定 message中没有)
> 
> 这个现在是这样的。

是的 是的 是我本地没刷新页面 我傻逼了

**Comment by afc163** [comment]
getContiner 只是 dom 节点渲染位置，不会印象展示位置。

**Comment by Lliuxs** [comment]
> getContiner 只是 dom 节点渲染位置，不会印象展示位置。

好的 感谢大佬。 组件设计如此的。  那我去叼设计去了

**Comment by afc163** [comment]
message 的设定就是全局提示，当前浏览器窗口居中偏上的位置弹出，目前不支持局部临时提示。这种设计也比较少见，也不建议这样设计。

**Comment by Lliuxs** [comment]
> 

好的 感谢大佬～～～ 那我关掉了
