### ISSUE TITLE
垂直的 Radio.Group，配合Select使用的时候，当选中一个选项后，再次触发选择，点击Select下拉框会自动收起

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design#41293]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hyv0yi?file=/demo.tsx)

### Steps to reproduce

首先使用下拉框先选择一个选项，然后再次点击下拉框

### What is expected?

选择值后可以再次选择

### What is actually happening?

选择后再次点击Select下拉框会自动收起无法选中

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18 |
| System | macOS |
| Browser | chrome |

**Comment by zombieJ** [comment]
你的例子里没有 Select。。。

**Comment by overcastsky** [comment]
> 

https://codesandbox.io/s/radio-group-chui-zhi-antd-5-3-1-forked-13rhk5

**Comment by zombieJ** [comment]
合并至 #25959
