### ISSUE TITLE
站点跪了！站点跪了！

### ISSUE THREAD

**Issue by RichardZhao1986** [ant-design/ant-design#41304]
### Reproduction link

[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce

https://ant.design/components/date-picker-cn/

### What is expected?

站点啥时候正常

### What is actually happening?

站点啥时候正常

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | XXX |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment]
先用 https://ant-design.antgroup.com/index-cn

**Comment by MadCcc** [comment]
现在好了，cdn 流量分发问题。国内优先访问 https://ant-design.antgroup.com/index-cn
