### ISSUE TITLE
怎么覆盖ant-design组件的样式

### ISSUE THREAD

**Issue by yaochuxia** [ant-design/ant-design#4130]
不管是在根目录index.css里的:global 写样式，还是在组件目录里面添加样式文件，都覆盖不了。

**Comment by ddcat1115** [comment]
https://ant.design/docs/react/customize-theme

**Comment by yaochuxia** [comment]
这样只能改改颜色啊，我需要覆盖的样式大范的覆盖，如表单输入框大小，圆角，按钮，下拉菜单等等

**Comment by wenpengfei** [comment]
终于可以定制样式了

**Comment by yaochuxia** [comment]
@wenpengfei 怎么定制的，我需要大范围的改样式

**Comment by benjycui** [comment]
@yaochuxia 建议定制 theme，如发现有不一定制的部分，建议 PR 增加变量以便配置。

**Comment by yaochuxia** [comment]
@benjycui  我就是定制theme,但是我们随便改一下，后台的页面也更着变了风格，前端能不能直接新建less，覆盖组件class的样式啊

**Comment by benjycui** [comment]
定制 theme 是全局的。

好吧，如果你只是想改某个页面的某个组件，还是用 `className` 吧。

**Comment by yuanmao5200** [comment]
@benjycui  部分情况 定位不到节点（组件没暴露） 添加不了className 如何解决。

**Comment by wenpengfei** [comment]
@yaochuxia 审查元素写class覆盖。。。
