### ISSUE TITLE
Antd date picker show single calendar instead of two calendars

### ISSUE THREAD

**Issue by vobile-wangzhenfeng** [ant-design/ant-design#41307]
### What problem does this feature solve?

I need RangePicker to show only one picker when picker= 'mouth'

<RangePicker picker="month" />

### What does the proposed API look like?

As shown in the picture below

![image](https://user-images.githubusercontent.com/111114334/225861067-e6491a0d-516a-4927-85ec-b7d9f876130e.png)

**Comment by vobile-wangzhenfeng** [comment]
I read that other solutions are hiding through CSS, and I wonder if there are other solutions?

**Comment by vobile-wangzhenfeng** [comment]
https://stackblitz.com/edit/react-sgts7q?file=demo.tsx

I found a solution, but I don't know why

```jsx
 <RangePicker
      picker="month"
      showTime
      format="YYYY/MM/DD"
    />

```

**Comment by afc163** [comment]
Hiding through CSS is what we recommend, there is no plan to add a option about it.
