### ISSUE TITLE
Increase code coverage up to 90%+

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4132]
- [ ] _util
- [ ] affix
- [x] alert
- [x] anchor @RaoHai 
- [ ] auto-complete @RaoHai
- [ ] back-top
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] cascader @yesmeck
- [ ] checkbox
- [ ] col
- [ ] collapse
- [ ] date-picker
- [ ] dropdown
- [ ] form
- [ ] grid
- [ ] icon
- [x] input
- [ ] input-number
- [ ] layout
- [x] locale-provider
- [ ] mention @RaoHai
- [ ] menu
- [ ] message @Raohai
- [ ] modal
- [ ] notification
- [ ] pagination
- [ ] popconfirm
- [ ] popover
- [ ] progress
- [ ] radio
- [x] rate
- [x] row
- [x] select
- [x] slider
- [x] spin
- [x] steps
- [x] switch
- [x] table @yesmeck
- [ ] tabs
- [ ] tag
- [ ] time-picker
- [ ] timeline
- [ ] tooltip
- [x] transfer https://github.com/ant-design/ant-design/pull/4191 @benjycui
- [ ] tree
- [ ] tree-select
- [ ] upload

**Comment by yesmeck** [comment]
😱

**Comment by yesmeck** [comment]
之前 coverage 的配置有问题，现在正确的覆盖率差不多是71。

https://github.com/ant-design/ant-design/commit/9701825c236e6955e6b512464e1a0f75d4ac090e

**Comment by yesmeck** [comment]
Working on Table.

**Comment by yesmeck** [comment]
更新了描述，组件覆盖率超过 80 后打个钩。

@RaoHai 认领的时候更新下组件后面的名字。

**Comment by yesmeck** [comment]
其实我觉得要 90 以上。。。

**Comment by afc163** [comment]
一步一步来，上 80% 之后 badge 就不会是刺眼的红色了。

**Comment by yesmeck** [comment]
82% 了。

**Comment by afc163** [comment]
针对覆盖率最差的文件列表写几个用例可以有效提高覆盖率：https://coveralls.io/github/ant-design/ant-design

<img width="782" alt="image" src="https://cloud.githubusercontent.com/assets/507615/22731776/c74c0fe4-ee26-11e6-873b-94b9241de125.png">

**Comment by benjycui** [comment]
`Tooltip` 等弹出类组件的 demo [snapshot 测试](https://github.com/ant-design/ant-design/blob/master/components/tooltip/__tests__/__snapshots__/demo.test.js.snap) 没意义，这些都要手写测试。

**Comment by benjycui** [comment]
然后都要确保 API 内有 `getPopupContainer` 之类

**Comment by afc163** [comment]
搞一个 popupSnapshot 的公共方法。

**Comment by benjycui** [comment]
> 搞一个 popupSnapshot 的公共方法。

但个人觉得不现实。。

cc @yesmeck

**Comment by benjycui** [comment]
弹出类的组件，用 [ModalTester](https://github.com/ant-design/ant-design/blob/ce2fe2aa455b6559bc4109ce986c2c4e2cba0471/components/modal/__tests__/Modal.test.js#L6) 的思路测试，应该也还好？

**Comment by afc163** [comment]
还是 simulate 事件比较好。
