### ISSUE TITLE
`NumberInput` warning about `useLayoutEffect`-usage when using NextJS

### ISSUE THREAD

**Issue by AntonPieper** [ant-design/ant-design#41321]
### Reproduction link

[https://github.com/AntonPieper/inputnumber-warning](https://github.com/AntonPieper/inputnumber-warning)

### Steps to reproduce

Use a [`InputNumber`](https://github.com/ant-design/ant-design/blob/master/components/input-number/index.tsx)-component anywhere inside a [NextJS](https://nextjs.org/) page. When running the NextJS server via `npm run dev` the warning will be shown.

An example of a page that shows the warning:
```tsx
import {InputNumber} from "antd";

export default function Home() {
    return <InputNumber/>;
}
```

### What is expected?

No warning should be shown.

### What is actually happening?

A warning shows up in the console:

 > Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See [https://reactjs.org/link/uselayouteffect-ssr](https://reactjs.org/link/uselayouteffect-ssr) for common fixes.

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | MacOS 13.3 Beta (22E5236f) |
| Browser | Chrome 111.0.5563.64 (Official Build) (arm64) |

**Comment by MadCcc** [comment]
It is intended that we use `useLayoutEffect` for client rendering, and it works fine in SSR. 
This warning actually didn't mean anything wrong in InputNumber.

**Comment by AntonPieper** [comment]
But this does result in noise in the logs which could be prevented by i.e. not running the code on the server (`if (typeof window === "undefined") { ... }`
