### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prefixCls') When testing Table Summary Cell

### ISSUE THREAD

**Issue by duytruong0916** [ant-design/ant-design#41324]
### Reproduction link

[https://nsoutherland.enterprise-manager.shop-ware.io/](https://nsoutherland.enterprise-manager.shop-ware.io/)

### Steps to reproduce

Create a dummy component that contains <Table.Summay.Cell>
Run Jest test

### What is expected?

Should be able to render the component in the test 

### What is actually happening?

TypeError: Cannot read properties of undefined (reading 'prefixCls') 

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | ^18.2.0 |
| System | IOS |
| Browser | Chrome |

---
TypeError: Cannot read properties of undefined (reading 'prefixCls') When testing component containing  Table Summary Cell with Jest   React testing Libraray

**Comment by kiner-tang** [comment]
@duytruong0916 I can't reproduce this problem. And the following link you provide can not login for me. Can you provide other reproduction link?
![image](https://user-images.githubusercontent.com/10286961/226113020-c9966be5-62be-474c-baa6-9c320853e280.png)

**Comment by vipulchaudhary1601** [comment]
Again faced this.
