### ISSUE TITLE
Does Typography support responsiveness?

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#41329]
### Reproduction link

[https://ant.design/components/typography#typographytext](https://ant.design/components/typography#typographytext)

### Steps to reproduce

The Typography component has 3 elements: Title, Text Paragraph. 

### What is expected?

Responsive text depending on screen resolution

### What is actually happening?

Now text rendered by Typography is not responsive

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome 111 |

---
How can I make the text they render shrink/enlarge according to the current screen resolution?

**Comment by afc163** [comment]
Try https://github.com/malte-wessel/react-textfit

**Comment by evgeniyworkbel** [comment]
@afc163 this package has 30 open issues and the last commit was 3 years ago so using it as project dependencies can cause problems

**Comment by evgeniyworkbel** [comment]
I use react 18 and I have just installed react-textfit through yarn: this package is invisible in project. I got eslint error "import/no-extraneous-dependencies". I tried to avoid it by disabling rule for line with import - it didn't work, text is still unresponsive

**Comment by evgeniyworkbel** [comment]
@afc163 could you reopen this topic?

**Comment by monolithed** [comment]
It's really painful to redefine Ant's styles, and here's why:

1. ConfigProvider does not allow setting fontSize: 'inherit'.
2. The elements body, a, and others have predefined font sizes.
3. It is necessary to use !important to override inherited styles.
4. 14px is clearly not a standard size, 16px is the minimum in this century.

**Comment by fliptrail** [comment]
This should be reopened imo.
