### ISSUE TITLE
Add icons for LTR and RTL

### ISSUE THREAD

**Issue by PhosphorusP** [ant-design/ant-design#41338]
### What problem does this feature solve?

Currently the library does not have icons for LTR and RTL needed in some applications.
Because of lack of these icons, the LTR/RTL switch button of the document site is using icons from Alipay CDN, which cannot show in correct colors defined in Design Tokens.

### What does the proposed API look like?

```
<LTRFilled />
<RTLFilled />
```

**Comment by aaarichter** [comment]
@PhosphorusP normally icon sets are designed for be used in both LTR and RTL context, but with the exception of directional icons (e.g arrows). But this doesn't apply to all directional icons, e.g a search magnifying glass, or a an icon that includes a small directional arrow is normally not flipped.
You can learn a lot of those rules at https://developer.apple.com/design/human-interface-guidelines/foundations/right-to-left

To flip those directional icons you could conditionally apply `transform: scaleX(-1)` to the icons based on `document.dir` property

```tsx
const myComponent = () => {
  const isRTL = document.body.dir=== 'rtl';

  return <LeftOutlined style={{...(isRTL && { transform:  'scaleX(-1)' })}} title={isRTL ? 'right' : 'left'} />;
}
```

**Comment by PhosphorusP** [comment]
> @PhosphorusP normally icon sets are designed for be used in both LTR and RTL context, but with the exception of directional icons (e.g arrows). But this doesn't apply to all directional icons, e.g a search magnifying glass, or a an icon that includes a small directional arrow, are normally not flipped. You can learn a lot of those rules at https://developer.apple.com/design/human-interface-guidelines/foundations/right-to-left
> 
> To flip those directional icons you could conditionally render the icon OR apply `transform: scaleX(-1)` to the icons based on `document.dir` property
> 
> ```tsx
> const myComponent = () => {
>   const isRTL = document.body.dir=== 'rtl';
> 
>   return isRTL ? <RightOutlined /> : <LeftOutlined />
> }
> ```
> 
> OR
> 
> ```tsx
> const myComponent = () => {
>   const isRTL = document.body.dir=== 'rtl';
> 
>   return <LeftOutlined style={{...(isRTL && { transform:  'scaleX(-1)' })}} title={isRTL ? 'right' : 'left'} />;
> }
> ```
> 
> In the last example, don't forget to update accessibility properties like `title` or `aria-label` as well

Thank you very much for your response. I may not have expressed my issue clearly, and I think my description was not clear enough. What I meant was to add the icons of LTR and RTL. Please let me know if you have any further doubts or questions, and I will do my best to clarify. Thank you again for your time and help!

<img width="31" alt="image" src="https://user-images.githubusercontent.com/13076466/229285853-e330dc2e-540b-4e97-9866-c9237bb1f430.png">
<img width="25" alt="image" src="https://user-images.githubusercontent.com/13076466/229285867-df0b8f3d-2e3d-4559-9a41-22646a27491a.png">

@aaarichter

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design-icons/issues/71#issuecomment-2101878389
