### ISSUE TITLE
优化message组件和notification组件

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#41332]
### What problem does this feature solve?

notification也可以支持promise的操作

### What does the proposed API look like?

1. 在学习message的过程中。发现定义了 open和typeopen两个方法，理论上是可以合并的
在看notification的过程中的确是做了合并的操作的。
2. message和notification区别是支持了 promise的操作。 notification是否也考虑支持promise的
3. 如果notification直接调用message组件的操作就更舒服了😌。 例如 popver直接使用 tooltip这样的操作
总体上来说他们的功能是差不多的

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by Lliuxs** [comment]
> 

message support promise why notification donnot。 both of them use rc-notification
