### ISSUE TITLE
rc-form 支持绑定数组吗

### ISSUE THREAD

**Issue by onlyWuj** [ant-design/ant-design#4133]
rc-form可以支持绑定嵌套比如
       `<Input {...getFieldProps('names.a')}/>`
        `<Input {...getFieldProps('names.b')}/>`
       
收集数据的时候输出是
`Object { names: Object}
names:Object a:''b:''`

但我这样写
     `<Input {...getFieldProps('names.[0]')}/>`
      `<Input {...getFieldProps('names.[1]')}/>`

收集数据的时候输出是
`Object { names.[0]: ''  names.[1]: ''}`
完全当成字符串处理了

问题就是：现在支持数组形式的绑定吗，要怎么写

**Comment by benjycui** [comment]
现在不支持，trace: https://github.com/ant-design/ant-design/issues/2965

**Comment by onlyWuj** [comment]
1 是现在人手不够，实现这功能有难度吗？未来这种特性会考虑进去吗？还是这种特性是不合适的。
2 如果这种需求是不合适的，那么我想做一个可编辑列表，应该如何规范地绑定数据呢。
