### ISSUE TITLE
请问是否考虑给 `Typography.Paragraph` 组件添加一个块级代码的样式？

### ISSUE THREAD

**Issue by yifeishu-com** [ant-design/ant-design#41334]
### What problem does this feature solve?

目前 Typography.Paragraph 的 code 属性只支持行内代码样式，请问是否可以添加类似于`<pre></pre>`标签的可换行代码样式？

### What does the proposed API look like?

```
<Typography.Paragraph code='pre'>
function Demo() {
    echo 1;
}
</Typography.Paragraph/>
```

**Comment by afc163** [comment]
```
    <Paragraph>
      <pre>{blockContent}</pre>
    </Paragraph>
```

<img width="1181" alt="图片" src="https://user-images.githubusercontent.com/507615/226164023-91e97302-e902-4819-b330-3989f6c28517.png">

**Comment by yifeishu-com** [comment]
Sorry，是我的问题！感谢回复
