### ISSUE TITLE
Select components，Why not use the native select tag

### ISSUE THREAD

**Issue by CanXinWu** [ant-design/ant-design#41348]
### Reproduction link

[https://ant.design/components/select-cn](https://ant.design/components/select-cn)

### Steps to reproduce

none

### What is expected?

use the native select tag

### What is actually happening?

use the native select tag

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | react |
| System | all |
| Browser | all |

**Comment by zombieJ** [comment]
Native components cannot implement complex interactive function, so we implement the Select component by customizing the dom structure.

**Comment by CanXinWu** [comment]
nonsupport accessibility

**Comment by CanXinWu** [comment]
When I used the screen reader software JAWS, I didn't want to press the up or down key to open the drop-down option directly. I wanted to press the "enter" key to open it

**Comment by CanXinWu** [comment]
> Native components cannot implement complex interactive function, so we implement the Select component by customizing the dom structure.

When I used the screen reader software JAWS, I didn't want to press the up or down key to open the drop-down option directly. I wanted to press the "enter" key to open it

**Comment by CanXinWu** [comment]
Attempts to prevent the up/down keys from acting by default were also prevented by 'defaultPrevented'
