### ISSUE TITLE
【InputNumber】onChange was triggered twice

### ISSUE THREAD

**Issue by z979054461** [ant-design/ant-design#41342]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/issue-antd-4-24-8-inputnumber-kjjepr?file=/demo.tsx)

### Steps to reproduce

```jsx
import React, { useState } from "react";
import "antd/dist/antd.css";
import "./index.css";
import { InputNumber, Modal } from "antd";

const App: React.FC = () => {
  const [test, setTest] = useState(11);

  return (
    <InputNumber
      value={test}
      onChange={(e) => {
        console.log("test onChange:", e);
        Modal.confirm({
          title: "test",
          content: "test1",
          onOk: () => {
            console.log("set value");
            setTest(e);
          }
        });
      }}
    />
  );
};

export default App;
```

### What is expected?

onChange触发一次

### What is actually happening?

onChange触发两次

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 16.14.0 |
| System | macOS 11.6.8 |
| Browser | 111.0.5563.64 (正式版本) (x86_64)  |

**Comment by zombieJ** [comment]
You should not call `setState` async in Modal.

More info pls ref React official doc: https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

**Comment by z979054461** [comment]
> You should not call `setState` async in Modal.
> 
> More info pls ref React official doc: https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

但是我就是要用Modal.confirm来提示用户确认，还没有触发到setState。
Input是正常的！

**Comment by zombieJ** [comment]
InputNumber 在输入的时候如果符合 parser 会触发 onChange。失去焦点时如果符合 parser 则会再一次比较，由于你受控 `value` 导致其不一致，所以会再次触发 `onChange`。非受控则不会有这个情况：

https://codesandbox.io/s/issue-antd-4-24-8-inputnumber-forked-8wv1y2

还是前面提到的，参考官方文档看一下受控非受控，不要做半受控：

 https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

**Comment by z979054461** [comment]
我的InputNumber是在一个表格中作为受控组件的。用户输入是需要二次确认，请问下这个需求怎么实现呢?

**Comment by zombieJ** [comment]
HOC InputNumber，内部受控，然后 onBlur 的时候弹出确定，cancel 则重置。

**Comment by z979054461** [comment]
我可以考虑用别的方式去规避这个问题。
但是我传了value，组件就应该是受控的，不该把内部值直接更新到UI上，而是onChange抛出来。InputNumber现在表现为“半受控”
