### ISSUE TITLE
Can you fix this onChange function in <RangePicker onChange={onChange} />

### ISSUE THREAD

**Issue by Bikramjit-1** [ant-design/ant-design#41355]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-jepsen-h08ldf?file=/src/App.tsx)

### Steps to reproduce

open this codeSandBox link

### What is expected?

i want to fix this onchange function

### What is actually happening?

(property) onChange: ((value: dayjs.Dayjs | null, dateString: string) => void) | undefined
No overload matches this call.
  Overload 1 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any> & CommonPickerMethods', gave the following error.
    Type '((value: Dayjs | null, dateString: string) => void) | undefined' is not assignable to type '((values: RangeValue<Dayjs>, formatString: [string, string]) => void) | undefined'.
      Type '(value: Dayjs | null, dateString: string) => void' is not assignable to type '(values: RangeValue<Dayjs>, formatString: [string, string]) => void'.
        Types of parameters 'value' and 'values' are incompatible.
          Type 'RangeValue<Dayjs>' is not assignable to type 'Dayjs | null'.
            Type '[EventValue<Dayjs>, EventValue<Dayjs>]' is not assignable to type 'Dayjs'.
  Overload 2 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any>', gave the following error.
    Type '((value: Dayjs | null, dateString: string) => void) | undefined' is not assignable to type '((values: RangeValue<Dayjs>, formatString: [string, string]) => void) | undefined'.ts(2769)
RangePicker.d.ts(24, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, unknown, any> & CommonPickerMethods> & Readonly<...>)'
RangePicker.d.ts(24, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, unknown, any>> & Readonly<...>)'

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Your reproduce not seems error. What's the reproduce step?

**Comment by caslanbigeyes** [comment]
I don't see how your error is reproduced, please be more specific

**Comment by Bikramjit-1** [comment]
import React, { useState } from "react";
import type { DatePickerProps, TimePickerProps } from "antd";
import { DatePicker, Select, Space } from "antd";
import { DateTime } from "luxon";

const { Option } = Select;
const { RangePicker } = DatePicker;

type PickerType = "custom" | "date";

const PickerWithType = ({
  type,
  onChange
}: {
  type: PickerType;
  onChange: TimePickerProps["onChange"] | DatePickerProps["onChange"];
}) => {
  if (type === "custom") return <RangePicker onChange={onChange} />;
  if (type === "date") return <DatePicker onChange={onChange} />;

  return <DatePicker picker={type} onChange={onChange} />;
};

const App: React.FC = () => {
  const [type, setType] = useState<PickerType>("custom");
  const shiftDefnList = ["6-14", "14-22", "22-6"];
  const [shift, setShift] = useState(shiftDefnList[0]);
  const [customDate, setCustomDate] = useState<{
    startTime: number;
    endTime: number;
  }>({
    startTime: 0,
    endTime: 0
  });

  let customDateRange = { startTime: 0, endTime: 0 };

  return (
    <Space>
      <Select value={type} onChange={setType}>
        <Option value="Day">Day</Option>
        <Option value="week">Week</Option>
        <Option value="shift">shift</Option>
        <Option value="month">Month</Option>
        <Option value="custom">Custom</Option>
      </Select>

      <PickerWithType
        type={type}
        onChange={
          (value) => console.log("value", typeof value, value)
          
        }
      />
    </Space>
  );
};

export default App;







in this  RangePicker-> if (type === "custom") return <RangePicker onChange={onChange} />;
i face this error =>
(property) onChange: ((value: dayjs.Dayjs | null, dateString: string) => void) | undefined
No overload matches this call.
  Overload 1 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any> & CommonPickerMethods', gave the following error.
    Type '((value: Dayjs | null, dateString: string) => void) | undefined' is not assignable to type '((values: RangeValue<Dayjs>, formatString: [string, string]) => void) | undefined'.
      Type '(value: Dayjs | null, dateString: string) => void' is not assignable to type '(values: RangeValue<Dayjs>, formatString: [string, string]) => void'.
        Types of parameters 'value' and 'values' are incompatible.
          Type 'RangeValue<Dayjs>' is not assignable to type 'Dayjs | null'.
            Type '[EventValue<Dayjs>, EventValue<Dayjs>]' is not assignable to type 'Dayjs'.
  Overload 2 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any>', gave the following error.
    Type '((value: Dayjs | null, dateString: string) => void) | undefined' is not assignable to type '((values: RangeValue<Dayjs>, formatString: [string, string]) => void) | undefined'.ts(2769)
RangePicker.d.ts(24, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, unknown, any> & CommonPickerMethods> & Readonly<...>)'
RangePicker.d.ts(24, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, unknown, any>> & Readonly<...>)'

**Comment by Bikramjit-1** [comment]
https://codesandbox.io/s/serene-goodall-qnn2gq


this is the codesandbox link

**Comment by Bikramjit-1** [comment]
![image](https://user-images.githubusercontent.com/96054843/226533737-f00b6afb-a2ec-4105-bfa7-fe0e17cadfe9.png)

**Comment by Bikramjit-1** [comment]
in this onChange i face this error =
(property) onChange: ((value: dayjs.Dayjs | null, dateString: string) => void) | undefined
No overload matches this call.
  Overload 1 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any> & CommonPickerMethods', gave the following error.
    Type '((value: Dayjs | null, dateString: string) => void) | undefined' is not assignable to type '((values: RangeValue<Dayjs>, formatString: [string, string]) => void) | undefined'.
      Type '(value: Dayjs | null, dateString: string) => void' is not assignable to type '(values: RangeValue<Dayjs>, formatString: [string, string]) => void'.
        Types of parameters 'value' and 'values' are incompatible.
          Type 'RangeValue<Dayjs>' is not assignable to type 'Dayjs | null'.
            Type '[EventValue<Dayjs>, EventValue<Dayjs>]' is not assignable to type 'Dayjs'.
  Overload 2 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any>', gave the following error.
    Type '((value: Dayjs | null, dateString: string) => void) | undefined' is not assignable to type '((values: RangeValue<Dayjs>, formatString: [string, string]) => void) | undefined'.ts(2769)
RangePicker.d.ts(24, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, unknown, any> & CommonPickerMethods> & Readonly<...>)'
RangePicker.d.ts(24, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, unknown, any>> & Readonly<...>)'

**Comment by sRoke** [comment]
@Bikramjit-1 May I ask how you resolved it

**Comment by sRoke** [comment]
解决方案： onChange方法中  value的类型应该指定为（Dayjs | null）;官网示例直接写Dayjs会提示类型错误

**Comment by denvudd** [comment]
Hello! Can someone please tell me how you solved this issue? I encountered the same problem while developing a project, even though I followed the documentation and examples.

Here's the piece of code where the problem occurs:
```
...
const handleDateChange: DatePickerProps["onChange"] = (
date: Dayjs | null,
dateString: string
): void => {
console.log(selectedDates);
};
...
{
key: "dateRelease",
label: "Дата релізу",
type: "group",
children: [
{
key: "datepicker",
label: (
<DatePicker.RangePicker
onChange={handleDateChange}
size="small"
/>
),
type: "group",
},
],
},
...
```
And here's the error message:
`Type error: Type '(date: Dayjs | null, dateString: [string, string]) => void' is not assignable to type '(value: Dayjs | null, dateString: string) => void'`

As far as I could discover if you look at the `export declare type RangePickerSharedProps<DateType>`, you can see the following annotation for onChange:
`onChange?: (values: RangeValue<DateType>, formatString: [string, string]) => void;`
But if you look at DatePickerProps["onChange"], you can see the following annotation for onChange:
`onChange?: (value: DateType | null, dateString: string) => void;`

They seem different, aren't they? Both annotations for onChange are causing an error. Does someone know a solution? Thank you!

**Comment by Inzendis** [comment]
> Hello! Can someone please tell me how you solved this issue? I encountered the same problem while developing a project, even though I followed the documentation and examples.
> 
> Here's the piece of code where the problem occurs:
> 
> ```
> ...
> const handleDateChange: DatePickerProps["onChange"] = (
> date: Dayjs | null,
> dateString: string
> ): void => {
> console.log(selectedDates);
> };
> ...
> {
> key: "dateRelease",
> label: "Дата релізу",
> type: "group",
> children: [
> {
> key: "datepicker",
> label: (
> <DatePicker.RangePicker
> onChange={handleDateChange}
> size="small"
> />
> ),
> type: "group",
> },
> ],
> },
> ...
> ```
> 
> And here's the error message: `Type error: Type '(date: Dayjs | null, dateString: [string, string]) => void' is not assignable to type '(value: Dayjs | null, dateString: string) => void'`
> 
> As far as I could discover if you look at the `export declare type RangePickerSharedProps<DateType>`, you can see the following annotation for onChange: `onChange?: (values: RangeValue<DateType>, formatString: [string, string]) => void;` But if you look at DatePickerProps["onChange"], you can see the following annotation for onChange: `onChange?: (value: DateType | null, dateString: string) => void;`
> 
> They seem different, aren't they? Both annotations for onChange are causing an error. Does someone know a solution? Thank you!

` const onChange = (time: Dayjs | null, timeString: string) => {
    console.log(time, timeString);
  };`
  
  
  
  the parameter of time needs to be either Dayjs | null to fix this, the documentation needs to be updated.

**Comment by emoxowa** [comment]
I've been working with DatePicker, and I noticed that the type for the `date` parameter in the `onChange` handler is defined as `unknown`. 

(property) onChange?: ((date: unknown, dateString: string | string[]) => void) | undefined

Could you please provide some insight into why the type of the date parameter is set to unknown?

**Comment by JonathanTube** [comment]
> 解决方案： onChange方法中 value的类型应该指定为（Dayjs | null）;官网示例直接写Dayjs会提示类型错误

> Solution: The type of value in the onChange method should be specified as (Dayjs | null）; Writing Dayjs directly to the official website example will prompt a type error

Definitely right!!!
