### ISSUE TITLE
menu组件 水平的顶部导航菜单 点击后会变成3个点的缩略状态，即使是在全屏状态下

### ISSUE THREAD

**Issue by dalxy** [ant-design/ant-design#41353]
### Reproduction link

[https://blog.csdn.net/songth1ef/article/details/126462980](https://blog.csdn.net/songth1ef/article/details/126462980)

### Steps to reproduce

点击导航菜单

### What is expected?

全屏状态下不会变成缩略图

### What is actually happening?

全屏状态下会变成缩略图

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | react18 |
| System | windows11 |
| Browser | chrome 版本 111.0.5563.65（正式版本） （64 位） |

**Comment by theOnlyUnique** [comment]
确实有这个问题哦，诚如你的博客有人评论那样，可以添加disabledOverflow属性，使其不进行缩略
我在Ubuntu 2404的VSCode当中开发 使用Chrome没有这个问题
但是我在Windows下开发，不管啥浏览器都会有这个问题，应该是样式方面的问题
