### ISSUE TITLE
(Yarn 2) Error: While persisting rc-pagination-npm-3.3.0 when install antd version 5.3.2

### ISSUE THREAD

**Issue by duypham90** [ant-design/ant-design#41357]
### Reproduction link
> yarn install antd
We will got error as picture:

![image](https://user-images.githubusercontent.com/24804332/226337190-91ba1d22-72bf-4b14-ac26-db3060069f18.png)

### Steps to reproduce
```bash
Install yarn 2
yarn install atnd@5.3.2
```
Current error:
> Error: While persisting /E:/Projects/.yarn/cache/rc-pagination-npm-3.3.0-1838abafd7-6b40cb2ab6.zip/node_modules/rc-pagination/ -> /E:/Projects/node_modules/rc-pagination ENOENT: no such file or directory, mkdir 'E:\Projects\node_modules\rc-pagination\dist\~demos\:id'

### What is expected?

- Working same with `antd: 5.3.0`

### What is actually happening?

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Window 10 |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Going to publish rc-pagination@3.3.1 to fix this issue.

**Comment by duypham90** [comment]
> Going to publish `rc-pagination@3.3.1` to fix this issue.

Thank you
