### ISSUE TITLE
https://ant.design/components/form-cn中Form如何使用中const App: React.FC = () => ()应为{}而不是()

### ISSUE THREAD

**Issue by dalxy** [ant-design/ant-design#41352]
### Reproduction link

[https://ant.design/components/form-cn](https://ant.design/components/form-cn)

### Steps to reproduce

无

### What is expected?

const App: React.FC = () => {}

### What is actually happening?

const App: React.FC = () => ()

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18 |
| System | windows11 |
| Browser | chrome |

**Comment by li-jia-nan** [comment]
具体是哪个 demo 呢？

**Comment by zombieJ** [comment]
这是合法的语法，详情请了解一下相关 eslint：
https://eslint.org/docs/latest/rules/arrow-body-style
