### ISSUE TITLE
Popover won't close after opening a Modal

### ISSUE THREAD

**Issue by hbatalhaStch** [ant-design/ant-design#41362]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/controlling-the-close-of-the-dialog-antd-5-3-2-forked-fytgiz?file=/demo.tsx)

### Steps to reproduce

Hover the `Test` button and open modal. 

### What is expected?

Close the popover and it should remain closed.

### What is actually happening?

If I move the mouse out of the browser and move it back in, it will open the popover again.

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.0.0 |
| System | Windows 10 Pro Version: 21H2 OS Build: 19044.2728 |
| Browser | MS Edge |

**Comment by Yuiai01** [comment]
When I oepn modal and the mouse went into the browser and popover opened again
![image](https://user-images.githubusercontent.com/112228030/226488857-f4e9e751-10d1-4dd9-ace2-a002268734f0.png)

**Comment by kiner-tang** [comment]
@hbatalhaStch  If you don't want to display popover when mouseover modal, you can move the Modal code outside the content of popover.

**Comment by zombieJ** [comment]
As @kiner-tang said. It's not a bug.

Popover trigger visible event in `hover` when `target` or `popup` trigger `mouseEnter` event. In React, virtual dom tree is not same as native dom, Modal is still the `children` of `popup`. If you do not need this, you can move Modal out instead.

**Comment by hbatalhaStch** [comment]
> Popover trigger visible event in `hover` when `target` or `popup` trigger `mouseEnter` event. In React, virtual dom tree is not same as native dom, Modal is still the `children` of `popup`. If you do not need this, you can move Modal out instead.

Thanks for for clarifying this for me. It makes sense now and I was able to fix my code.
