### ISSUE TITLE
Cannot refer new breadcrumb `item` prop by `BreadcrumbProps["item"]`

### ISSUE THREAD

**Issue by keita-determined** [ant-design/ant-design#41364]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-router-v6-antd-5-3-2-forked-tst9e7?file=/demo.tsx)

### Steps to reproduce

```tsx
import { BreadcrumbProps } from "antd";
const breadcrumbItems: BreadcrumbProps["items"] = []
```
- cannot refer new `item` prop for breadcrumb.
- I get error `Property 'items' does not exist on type 'BreadcrumbProps'` when i declare `BreadcrumbProps["items"]`

### What is expected?

`BreadcrumbProps["items"]` should be able to be used as a new breadcrumb prop type

### What is actually happening?

`Property 'items' does not exist on type 'BreadcrumbProps'` error

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | macOS Ventura |
| Browser | Chrome |

**Comment by li-jia-nan** [comment]
You can use `NewBreadcrumbProps['items']`

**Comment by zombieJ** [comment]
You can always get real type by infer:
https://codesandbox.io/s/react-router-v6-antd-5-3-2-forked-cm66kr?file=/demo.tsx

**Comment by keita-determined** [comment]
thank you for some information, but `NewBreadcrumbProps['items']` doesnt work either.
`infer` works, but its not ideal 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/109113616/226551971-882be509-1abe-46b1-b2d4-1f80ee8d05e5.png">
