### ISSUE TITLE
ant4.0 升级5.0报错 Could not resolve "antd/es/page-header/style"

### ISSUE THREAD

**Issue by dengying918** [ant-design/ant-design#41365]
### What problem does this feature solve?

ant4.0 升级5.0报错 Could not resolve "antd/es/page-header/style"

### What does the proposed API look like?

ant4.0 升级5.0报错 Could not resolve "antd/es/page-header/style"

**Comment by yoyo837** [comment]
Dupllicate of #38803

**Comment by Wxh16144** [comment]
PageHeader 在 v5 中移除了

**Comment by zhangruolin** [comment]
这个解决了嘛，遇到了同样的问题，求助下。

**Comment by yoyo837** [comment]
> 这个解决了嘛，遇到了同样的问题，求助下。

去掉babel-import-plugin插件

**Comment by yoyo837** [comment]
稍微搜索一下，到处都是答案。

**Comment by zhangruolin** [comment]
<img width="1463" alt="image" src="https://github.com/ant-design/ant-design/assets/17541511/3528b90a-72e4-4574-b62f-491c7021a0e9">


> 稍微搜索一下，到处都是答案。

我在全局搜索里面没有找到这个插件，我是做后端的，前端是小白，请教呀。

**Comment by yoyo837** [comment]
那就是别的东西引用了，比如dumi

**Comment by zhangruolin** [comment]
> 那就是别的东西引用了，比如dumi

这种应该怎么解决呢。

**Comment by yoyo837** [comment]
去掉插件就好了。

**Comment by zhangruolin** [comment]
> 去掉插件就好了。

全局搜索了下，dumi也是没有的。
