### ISSUE TITLE
关于打包的问题,排除moment依赖包

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design#4136]
- antd 版本: 2.5.1
- 操作系统及其版本: win10
- 浏览器及其版本: google

DatePicker 和 TimePicker 引入了 moment的国际化文件

我在自己项目中 设置 webpack的 ``externals.moment = true`` , 打包完成以后，bundle文件里面还是包含了很多moment的文件，这个有什么办法可以优化吗

**Comment by benjycui** [comment]
可重现 repo?

**Comment by benjycui** [comment]
看了代码逻辑，确认只会引进开发者主动引进的 locale

**Comment by yesmeck** [comment]
试了下没有你说的情况，应该跟 antd 没关系。

**Comment by Sean-Snow** [comment]
这是 webpack的日志，
![1](https://cloud.githubusercontent.com/assets/4498796/21004510/b8983022-bd6b-11e6-8aef-ca669160d354.png)
![2](https://cloud.githubusercontent.com/assets/4498796/21004544/ea37e26c-bd6b-11e6-8f9c-6a66ff6a3537.png)

**Comment by Sean-Snow** [comment]
我引入 date-picker 以后 接着就是 locale 里面的所有 文件了

**Comment by Sean-Snow** [comment]
第一个张图片是开发时候的，第二张是我做生产包的

**Comment by yesmeck** [comment]
是不是 externals  里要把 `moment/locale/bo` 也设置 true？

**Comment by Sean-Snow** [comment]
@yesmeck  额，怎么弄？每个 文件都写？

**Comment by yesmeck** [comment]
我猜是吧，如果你发现是因为 antd 代码原因且可以改进的话就 reopen 好了。

**Comment by benjycui** [comment]
可重现 repo 及步骤。

**Comment by Sean-Snow** [comment]
https://github.com/sitb-software/test   仓库地址

测试步骤
    npm run dll
    npm run production   // 打包

打包完成以后再build目录中的app.bundle.js 里面包含了moment 的代码

**Comment by Sean-Snow** [comment]
如何我只引入Input组件，打包以后app.bundle只有29KB， 引入DatePicker ，打包以后变成300KB 了

**Comment by yesmeck** [comment]
[这里](https://github.com/ant-design/ant-design/blob/383101830ac03fb3feffea185f0474ee4f933f63/components/date-picker/locale/zh_CN.tsx#L7) import 了 `moment/locale/zh-cn`，把这个也设置成 external 就可以了。

另外你要把 antd 要搞成 external 的话就不能这样`import DatePicker from 'antd/lib/date-picker'`。

**Comment by Sean-Snow** [comment]
antd 是刚刚测试才设置external ，我没用

**Comment by yesmeck** [comment]
可以用 https://github.com/robertknight/webpack-bundle-size-analyzer https://webpack.github.io/analyse/ 查看 buid 的依赖情况。

如果发现有设置 external 的包被打包了的话可以尝试把那个包删掉，再打包的时候 webpack 就会报错，就知道哪里依赖这个包了。

**Comment by Sean-Snow** [comment]
moment/locale/zh-cn 设置为true 倒是可以了

**Comment by Sean-Snow** [comment]
@yesmeck  额，昨天没有仔细检查，moment/locale/zh-cn 设置为true 打包没问题，运行的时候 直接报错了

    locale is not defined

**Comment by yesmeck** [comment]
不打包就需要自己用 <script /> 把 locale 引入了吧。

**Comment by Sean-Snow** [comment]
script  我已经引入了moment-with-locales.min.js

**Comment by Sean-Snow** [comment]
@yesmeck  这个能解决吗

**Comment by yesmeck** [comment]
要你自己搞定了

**Comment by Sean-Snow** [comment]
@yesmeck   externals['moment/locale/zh-cn'] = 'moment.locale'; 就ok了

**Comment by bornkiller** [comment]
碰到同样的问题，临时解决如下：

```json
{
  "externals":  {
    "moment": "moment",
    "../moment": "moment"
  }
}
```

**Comment by sundayha** [comment]
综上所述：
解决方案
```
在 index.html 引入
<script src="https://cdn.bootcss.com/moment.js/***/moment.min.js"></script>
<script src="https://cdn.bootcss.com/moment.js/***/locale/zh-cn.js"></script>
```
```
在webpack.config.js 加入
externals:  {
    'moment': 'moment',
    'moment/locale/zh-cn' : 'moment.locale'
}
```
