### ISSUE TITLE
Cascader组件onChange方法返回值错误

### ISSUE THREAD

**Issue by Silenceeric945** [ant-design/ant-design#41376]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-7jxhkz?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

搜索雅安，用键盘下键选择第一个，回车

### What is expected?

期望用键盘选择的onChange返回与鼠标点击的返回结果一致

### What is actually happening?

onChange返回的value和selectedOptions跟鼠标点击的返回不一致导致label显示错误

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.0 |
| System | Windows10 |
| Browser | Chrome |

**Comment by kiner-tang** [comment]
我来看看

**Comment by kiner-tang** [comment]
或许也可以尝试升级一下`antd`：
https://codesandbox.io/s/sou-suo-antd-4-24-8-forked-szvi3j?file=/map.ts

**Comment by zombieJ** [comment]
> 好像和这个issue #40782 类似，可以尝试更新一下rc-cascader版本 https://github.com/ant-design/ant-design/blob/master/package.json#L123

`rc-cascader` 还依赖了 `rc-tree-select` `rc-select` 这一路更新上去容易引入非预期 BUG。还是得看看 `3.7.x` 上能不能 patch 一下

**Comment by zombieJ** [comment]
v5 也有这个 bug：
https://codesandbox.io/s/antd-reproduction-template-forked-3perwq?file=/index.js

<img width="408" alt="截屏2023-03-22 15 32 52" src="https://user-images.githubusercontent.com/5378891/226831717-9b39a254-e5cb-4455-92a5-9f07d992774f.png">
