### ISSUE TITLE
DatePicker 中MonthPicker怎么设置中文版本的

### ISSUE THREAD

**Issue by linaijiao** [ant-design/ant-design#4137]
1、我引用了 antd的DatePicker 中MonthPicker组件，有值得情况下是英文版本的
`mport {DatePicker} from 'antd';
import moment from 'moment';
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
const MonthPicker = DatePicker.MonthPicker;
<MonthPicker defaultValue={item.endTime !== 0 && moment(item.endTime,'YYYY.MM') || null}  format="YYYY.MM" placeholder="结束日期" locale="zh-cn"  onChange={(val,dateStrings) => t.submitInfo(dateStrings,5)} style={{width:56}} />`

如果defaultValue设置为null，就能正常显示中文版本的

2、我想要实现的年月日期展示的是中文版的，想知道引用的数据格式是怎样的

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by benjycui** [comment]
Issue 是给人看的，现在一坨根本看不了。

**Comment by afc163** [comment]
默认应该就是中文的：http://codepen.io/anon/pen/qqMzGK?editors=001

**Comment by wwgc** [comment]
国际化的组件，怎么默认显示中文？
有没有办法切换成英文？
