### ISSUE TITLE
Weird behavior of TreeSelect/Select with maxTagCount: "responsive" when it works with treeData/options whose content is too long

### ISSUE THREAD

**Issue by sidayang** [ant-design/ant-design#41374]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hgj4fd?file=/index.js)

### Steps to reproduce

When the length of options is too long, in this case, longer than the width of the TreeSelect/Select itself
1. select the first option and unselect the first option
2. select the first option again, the original content of the option (label) would be shown in TreeSelect/Select instead of a " 1" tag, resulting in the height of the Select component being stretched to two lines, but this only lasts a very short time and then the " 1" tag appears and the height of Select become normal (one line)

### What is expected?

The " 1" tag shows up immediately after the option is chosen, and the height of TreeSelect/Select component keeps being one line

### What is actually happening?

When the first option is selected for the second time, the original content of the option (label) would be shown in TreeSelect/Select instead of a " 1" tag, resulting in the height of the Select component being stretched to two lines, but this only lasts a very short time and then the " 1" will appear and the height of Select become normal (one line)

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.x |
| System | macOS 13.0.1 |
| Browser | Chrome Version 111.0.5563.64 (Official Build) (x86_64) |

**Comment by zombieJ** [comment]
Internal use `rc-overflow` to measure size by effect. Seems can be optimized .
