### ISSUE TITLE
表格组件Table 展示错位 

### ISSUE THREAD

**Issue by CandyQiu** [ant-design/ant-design#4138]
#### 发生问题的环境是：

- antd 版本 2.5.0 :
- 操作系统及其版本: mac 10.11.4 (15E65)
- 浏览器及其版本: chrome  53.0.2785.143 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

引用表格Table组件，展示数据

#### 您期待的结果是:

表格正常展示数据

#### 实际上的结果是:

表格样式错位：

![错位演示图1](https://img.alicdn.com/tps/TB1Qf4wOFXXXXb0apXXXXXXXXXX-1138-426.png)

![最终鼠标hover效果](https://img.alicdn.com/tps/TB113pNOFXXXXXaaXXXXXXXXXXX-991-315.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
@CandyQiu any progress?

**Comment by benjycui** [comment]
Close now, just re-open if you can provide re-producible online demo.
