### ISSUE TITLE
Dropdown的z-index和Modal冲突问题

### ISSUE THREAD

**Issue by zhipenglin** [ant-design/ant-design#41380]
### Reproduction link

[https://zhipenglin.github.io/antd-test/](https://zhipenglin.github.io/antd-test/)

### Steps to reproduce

1.点击按钮一触发Dropdown显示内容
2.点击Dropdown内容中的按钮二弹出弹窗

### What is expected?

期望Dropdown内容的层级在弹窗下面，不然会遮挡弹窗内容展示

### What is actually happening?

Dropdown内容的层级在弹窗上面

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | windows10 |
| Browser | chrome 111.0.5563.65 |

---
Modal的z-index被设置成了1000，Dropdown的内容的z-index被设置为1050，导致Dropdown的内容永远在Modal上面

**Comment by Wxh16144** [comment]
这个应该是故意这样设计的，应该是考虑到 Modal 中使用 Dropdown 的场景，所以你反馈的问题现目前只能通过样式覆盖满足。也可以关注 #38975 讨论统一设置组件的层级。

**Comment by MadCcc** [comment]
使用 `ConfigProvider theme` 更改组件的 `zIndexPopup` 即可
```
<ConfigProvider 
  theme={{
    components: {
      Dropdown: {
        zIndexPopup: 600, // smaller than Modal
      }
    }
  }}
>
  <Dropdown />
</ConfigProvider>
```
