### ISSUE TITLE
Incorrect useStatus value

### ISSUE THREAD

**Issue by VolhaMalevich** [ant-design/ant-design#41384]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-for-usestatus-hook-rb3z5p?file=/index.js)

### Steps to reproduce

1. Create a simple ANTD form with a single Form.Item component
2. Add a length check rule (e.g. len: 3) to this Form.Item component
3. Create a custom component that returns an <Input/> component and use it as an input component inside <Form.Item> tags
4. Use the "useStatus" hook inside your custom component and check the status

### What is expected?

I expect the following sequence of statuses at the start of input:
1. not defined
2. "validating"
3. "error"

I expect the following sequence of statuses when the state changes from invalid to valid (when the input length becomes correct):
1. ...
2. "error"
3. "validating"
4. "success"

### What is actually happening?

I receive the following sequence of statuses at the start of input:
1. not defined
2. "validating"
3. **"success"**
4. "error"

I receive the following sequence of statuses when the state changes from invalid to valid (when the input length becomes correct):
1. ...
2. "error"
3. "validating"
4. **"error"**
5. "success"

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Windows |
| Browser | Google Chrome |

---
I need to show a specific suffix icon based on the input status, but the icon is blinking due to the wrong intermediate state.

**Comment by VolhaMalevich** [comment]
the start of input:
![image](https://user-images.githubusercontent.com/83364258/226690075-12e666b9-661c-4ff2-871a-5591da5ea444.png)
From invalid to valid:
![image](https://user-images.githubusercontent.com/83364258/226690361-9b38a7d3-1f48-4401-a0a2-b7dd142b174a.png)

**Comment by zombieJ** [comment]
@kiner-tang seems status sync has some sync issue.

**Comment by kiner-tang** [comment]
> @kiner-tang seems status sync has some sync issue.

👌🏻
