### ISSUE TITLE
Adding getPopupContainer in popover triggers button when clicking in content

### ISSUE THREAD

**Issue by tempoeric** [ant-design/ant-design#41383]
### Reproduction link

[https://zcsqm7.csb.app/](https://zcsqm7.csb.app/)

### Steps to reproduce

1. Click the link
2. Click the Click me button
3. Click on the content

You will see that the button effect triggers around the button

### What is expected?

Should not render or trigger button

### What is actually happening?

Button effect is showing when clicking on content

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18.2.0 |
| System | Mac OS Ventura 13.1 |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
When you move PopOver in. It does be the children node in the button. It's not a bug.
