### ISSUE TITLE
Table组件使用Typography.Paragraph，当width设置为百分比时，rows=1会把列撑开

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#41398]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quiet-flower-fkde5c?file=/src/App.js)

### Steps to reproduce

参考注释

### What is expected?

正常展示

### What is actually happening?

列被撑开了

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | react |
| System | macos |
| Browser | chrome最新 |

**Comment by Yuiai01** [comment]
我来康康~

**Comment by Yuiai01** [comment]
这个问题是由于当 `Typography.Paragraph` 的 `ellipsis` 其 rows 为1时，在源码内部是使用 text-overflow 来控制文本省略，但是 text-overflow 是需要父元素指定具体的 width，在你的这个例子里使用的是百分比的 width 所以文本把列撑开了，如果你想实现百分比下的单行文本省略的话，可以使用 `column` 的 `ellipsis` ，就像这样 https://codesandbox.io/s/sad-rosalind-4s0uw1?file=/src/App.js

**Comment by hans000** [comment]
> 这个问题是由于当 `Typography.Paragraph` 的 `ellipsis` 其 rows 为1时，在源码内部是使用 text-overflow 来控制文本省略，但是 text-overflow 是需要父元素指定具体的 width，在你的这个例子里使用的是百分比的 width 所以文本把列撑开了，如果你想实现百分比下的单行文本省略的话，可以使用 `column` 的 `ellipsis` ，就像这样 https://codesandbox.io/s/sad-rosalind-4s0uw1?file=/src/App.js

你给的例子我当然知道了，那种布局太简单了，现在需求就是要单元格有两个字段，一个两行，一个一行

**Comment by Yuiai01** [comment]
> > 这个问题是由于当 `Typography.Paragraph` 的 `ellipsis` 其 rows 为1时，在源码内部是使用 text-overflow 来控制文本省略，但是 text-overflow 是需要父元素指定具体的 width，在你的这个例子里使用的是百分比的 width 所以文本把列撑开了，如果你想实现百分比下的单行文本省略的话，可以使用 `column` 的 `ellipsis` ，就像这样 https://codesandbox.io/s/sad-rosalind-4s0uw1?file=/src/App.js
> 
> 你给的例子我当然知道了，那种布局太简单了，现在需求就是要单元格有两个字段，一个两行，一个一行

如果父元素宽度是百分比的话，当前的逻辑确实是无法满足你这个需求

**Comment by hans000** [comment]
> 

所以说rows=1时为什么做特殊处理？

**Comment by Yuiai01** [comment]
> > 
> 
> 所以说rows=1时为什么做特殊处理？

可见 https://github.com/ant-design/ant-design/pull/33725

**Comment by youngluo** [comment]
4.x 的版本也有这个问题 https://codesandbox.io/s/thirsty-lamarr-2vj8zl?file=/src/App.js

**Comment by afc163** [comment]
https://codesandbox.io/s/cranky-water-hnv75t?file=/src/App.js

加个 `tableLayout="fixed"`。
