### ISSUE TITLE
V4.x 的table组件虚拟滚动不生效

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#41394]
### Reproduction link

https://codesandbox.io/s/shu-xing-shu-ju-zhan-shi-antd-4-24-8-forked-hif3oz?file=/index.tsx

### Steps to reproduce

链接效果

### What is expected?

有虚拟滚动的效果

### What is actually happening?

无效果 页面甚至卡死

| Environment | Info |
| --- | --- |
| antd | 4.17.0 |
| React | 17 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by Ali-ovo** [comment]
如果我想使用虚拟滚动， 必须安装官网的例子下载其他的包才可以支持嘛 
有无其他更简便的方案呢

**Comment by zombieJ** [comment]
> 如果我想使用虚拟滚动， 必须安装官网的例子下载其他的包才可以支持嘛 有无其他更简便的方案呢

就如你所说的，虚拟滚动实例其实自定义组件的 Demo。所以实现该功能需要依赖于三方虚拟组件哈。另外 v5 有计划做纯展示态的虚拟滚动支持。
