### ISSUE TITLE
如何获取一个结构化组件API

### ISSUE THREAD

**Issue by xiyangjun** [ant-design/ant-design#41390]
### What problem does this feature solve?

我在做一款基于antd的低代码工具，想通过结构化的API来展示组件列表

### What does the proposed API look like?

期望的JSON API类似于
```json
[{
   "name": "Input",
   "props": [{
         "name": "type",
         "desc": "声明 input 类型",
         "type": "string"
   }, {
         "name": "onChange",
         "desc": "输入框内容变化时的回调",
         "type": "string"
   }]
}]
```

**Comment by zombieJ** [comment]
可以研究一下 dumi 的 API 表格实现： https://d.umijs.org/guide/auto-api-table

这个 issue 本身和 antd 无关，我就先关了哈

**Comment by xiyangjun** [comment]
> 可以研究一下 dumi 的 API 表格实现： https://d.umijs.org/guide/auto-api-table
> 
> 这个 issue 本身和 antd 无关，我就先关了哈

感谢！
