### ISSUE TITLE
Form.List 里面的add 方法是否可以支持外部调用，如果支持如何写呢。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#41399]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ksy7ix)

### Steps to reproduce

按照例子都是写在Form.List里面的，外部如何调用呢？

### What is expected?

Form.List add 方法，remove方法外部可以调用

### What is actually happening?

Form.List add 方法，remove方法外部不能可以调用

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 16.17 |
| System | windows |
| Browser | chrome |

**Comment by acyza** [comment]
不知道这样会不会有bug。https://codesandbox.io/s/dong-tai-zeng-jian-qian-tao-zi-duan-antd-5-3-2-forked-y51oz9?file=/demo.js
