### ISSUE TITLE
设置子菜单 popupClassName 属性时，浏览器控制台报错 React does not recognize the `popupClassName` prop on a DOM element

### ISSUE THREAD

**Issue by ManiaJack** [ant-design/ant-design#41395]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-5-3-2-forked-yiz8kk?file=/demo.tsx)

### Steps to reproduce

生成 items 数组时，动态根据 children 字段赋值 popupClassName 为 有效值或 undefined，浏览器控制台报错

### What is expected?

不报错

### What is actually happening?

功能正常，但是控制台会报错

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.0.0 |
| System | Windows 10 19045.2728 |
| Browser | Chrome  111.0.5563.65 |

**Comment by acyza** [comment]
这样写相当于给`MenuItem`加了`popupClassName={undefined}`，可以把popupClassName拿到外面来根据children单独赋值。https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-5-3-2-forked-cvbjr7

**Comment by ManiaJack** [comment]
> 这样写相当于给`MenuItem`加了`popupClassName={undefined}`，可以把popupClassName拿到外面来根据children单独赋值。https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-5-3-2-forked-cvbjr7

Property 'popupClassName' does not exist on type 'ItemType'.

**Comment by Yuiai01** [comment]
我来康康~
