### ISSUE TITLE
antd v5 的config-provider组件目前可以单独对table设置边框颜色吗

### ISSUE THREAD

**Issue by rocketsbigfan** [ant-design/ant-design#41397]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0mpgsr)

### Steps to reproduce

/

### What is expected?

边框颜色改变

### What is actually happening?

没改变

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18  |
| System | mac  |
| Browser | chrome 110.0.5481.100 |

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-h90ec6
Customize with AliasToken.
