### ISSUE TITLE
请不要把开发版，用在官网的DEMO中，OK？

### ISSUE THREAD

**Issue by TouchQQ** [ant-design/ant-design#414]
请不要把开发版，用在官网的DEMO中，OK？
请不要把开发版，用在官网的DEMO中，OK？
请不要把开发版，用在官网的DEMO中，OK？
请不要把开发版，用在官网的DEMO中，OK？
请不要把开发版，用在官网的DEMO中，OK？

**Comment by afc163** [comment]
http://09x.ant.design/

https://github.com/ant-design/ant-design/issues/406
