### ISSUE TITLE
Set overflow on select to false does not work

### ISSUE THREAD

**Issue by daribock** [ant-design/ant-design#41400]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-u8nr7k?file=/index.js&resolutionWidth=685&resolutionHeight=476)

### Steps to reproduce

To be honest I don't know what the issue is the only thing I know is that I can't deactivate the autoOverflow from the dropdown of the select component eventhough I set the dropdownAlign to:

```tsx
<Select ... dropdownAlign={{ overflow: { adjustX: false, adjustY: false } }} >
  ...
</Select>
```

like suggested here: https://github.com/ant-design/ant-design/issues/12070#issuecomment-558683920

### What is expected?

Version 4.x worked for us. So I would love to have the same behaviour of the select box as before.

### What is actually happening?

The dropdown of the Select component is sometimes opened bottemleft and sometimes where it wants. So I would love to set the autoAdjustOverflow to false like I can on the Tooltip component.

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18 |
| System | MacOS Ventura 13.2.1 |
| Browser | Chrome 111.0.5563.110 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/41222#issuecomment-1475533218

**Comment by zombieJ** [comment]
Already fixed in latest version: https://codesandbox.io/s/antd-reproduction-template-forked-22r0u3?file=/index.js:431-432

**Comment by hungify2022** [comment]
In old version 
Let put `dropdownAlign={{ htmlRegion: "visible" }}` to resolve
I don't know why (by  default htmlRegion is `visible`)
