### ISSUE TITLE
Remove and add from DOM inside Shadow-dom causes dropdown to fail

### ISSUE THREAD

**Issue by Illedan** [ant-design/ant-design#41404]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/popup-container-bugged-ohsmqh?file=/demo.tsx)

### Steps to reproduce

1. Hover the dropdown and see console logged
2. Click Remove everything => div with shadowdom is removed from dom
3. Click Add everything => div with shadowdom is added to dom
4. Experience dropdown has inverted state (the styling on the items have `pointer-events: none; ` when they should be selectable and the drodown shows when it shouldn't and visa versa)

### What is expected?

Dropdown should be working when added to shadowdom again.
This problem occurs in our environments when we use Antd5 inside a Webcomponent which is removed/added based on external state. The code inside Index.tsx is to mimic this behavior.

### What is actually happening?

See reproduction steps.
This also fails with the Select component.

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.0.0 |
| System | Windows |
| Browser | Chrome/Edge |

**Comment by zombieJ** [comment]
fixed with `@ant-design/cssinjs@1.6.2`: https://codesandbox.io/s/popup-container-bugged-forked-4pd7t2?file=/package.json
