### ISSUE TITLE
2.5.1 AbstractTooltipProps 下 children 为必选，导致 TS 编译出错

### ISSUE THREAD

**Issue by hjin-me** [ant-design/ant-design#4140]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: Mac OS X, Typescript 2.1.1
- 浏览器及其版本: Chrome 54

#### 您做了什么？请提供尽可能详细的重现步骤。

```
import Popover from 'antd/lib/popover'
<Popover content="1"><div/></Popover>

ERROR in [default] ****/index.tsx:149:16
Property 'children' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Popover> & PopoverProps & { children?: ReactNode; }'.
```

使用 ts 编译时不通过。

#### 您期待的结果是:

TS 编译正常通过

#### 实际上的结果是:

编译出错，`AbstractTooltipProps` 下 children 为必选项。

**Comment by benjycui** [comment]
看起来是 TS 识别的问题，children 的确是必须的，并且你已经传了一个 `<div />` 作为 children。

**Comment by benjycui** [comment]
TS 2.1.x 还不是正式版本，试着用回 2.0.x 看还有没有这个问题。

**Comment by hjin-me** [comment]
typescript@2.0.10
antd@2.5.1

问题依旧存在

我查了一下网上的一些资料，例如 https://github.com/Microsoft/TypeScript/issues/8588
似乎这个是 TS 本身的坑，并且尚未解决，别人通常都是把 children 设置为 optional 来绕开这个问题。

**Comment by benjycui** [comment]
那就只能设为 optional 了。。

**Comment by benjycui** [comment]
It seems that this problem will be solved in TypeScript@2.3, trace https://github.com/Microsoft/TypeScript/issues/13618
