### ISSUE TITLE
Shadow DOM 下 Popconfirm 组件无法正常工作

### ISSUE THREAD

**Issue by hewenguang** [ant-design/ant-design#41428]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-3-2-forked-tjow71?file=/index.tsx)

### Steps to reproduce

打开后直接点击按钮即可复现

### What is expected?

正常打开弹窗

### What is actually happening?

打不开，打开立即自动关闭了

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18 |
| System | mac m1 |
| Browser | chrome 111.0.5563.110 |

**Comment by zombieJ** [comment]
debug 了一下，点击触发 Popconfirm 的时候会添加 window 点击事件监听。此时由于点击元素是 shadow dom，所以它并不能拿到真实的 dom 节点，以至于弹层认为点了外部所以关关闭。可以先加个 stopPop：
https://codesandbox.io/s/ji-ben-antd-5-3-2-forked-9q8lyv?file=/demo.tsx

**Comment by hewenguang** [comment]
强，确实可以临时解决！！！

**Comment by acyza** [comment]
大概试了下，好像shadowroot下的所有dom的click事件target都是shadowroot宿主
或许可以用event中提供的一些坐标判断范围，但肯定没有target准确。

**Comment by acyza** [comment]
也许可以给Popconfirm外套个节点，用stopPropagation()阻止节点内的click事件被window捕获，这样基本不影响Popconfirm正常功能。https://codesandbox.io/s/ji-ben-antd-5-3-2-forked-0le5qc?file=/demo.tsx

**Comment by zombieJ** [comment]
fixed: https://codesandbox.io/s/ji-ben-antd-5-3-2-forked-hxh93q?file=/package.json

**Comment by RyzenPan** [comment]
请问怎么解决，没看懂在哪里加stopPop？

**Comment by acyza** [comment]
> 请问怎么解决，没看懂在哪里加stopPop？

https://github.com/ant-design/ant-design/issues/41428#issuecomment-1481466692
`stopPropagation`看这条评论的demo

**Comment by RyzenPan** [comment]
> > 请问怎么解决，没看懂在哪里加stopPop？
> 
> [#41428 (comment)](https://github.com/ant-design/ant-design/issues/41428#issuecomment-1481466692) `stopPropagation`看这条评论的demo，或升级rc-trigger

之后官方会解决是吧，大概什么时候发正式版？

**Comment by RyzenPan** [comment]
> rc-trigger

请问rc-trigger需要升级到哪个版本，我看现在最新的是5.3.4，跟仓库的tag版本不一致

**Comment by RyzenPan** [comment]
> 在 @rc-component/trigger 了

请问怎么更新antd的@rc-component/trigger包了，我直接安装最新版在项目中，antd没有用到这个包，我用的是pnpm

**Comment by hewenguang** [comment]
试试卸载 antd 后重新安装，这样相关的依赖会更新
