### ISSUE TITLE
Table 表格远程排序一直是descend

### ISSUE THREAD

**Issue by lsq33123** [ant-design/ant-design#41430]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-table-sort-rync2p)

### Steps to reproduce

点击字段排序，onchange排序方式未变化

### What is expected?

正常变化

### What is actually happening?

未变化

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome |

**Comment by MuxinFeng** [comment]
sorter 为 true 的情况好像确实有点问题，我跟下吧~  一例：https://ant.design/components/table-cn#components-table-demo-fixed-columns

**Comment by MuxinFeng** [comment]
这里仅仅将 sorter 设置为 true 是没用的哈，还需要服务端配合。
可以理解为这个时候只有 sorter 对应的 ui 交互效果，然后你拿到 sorter 的值传给服务端，服务端做好排序再把结果给你。

**Comment by zombieJ** [comment]
见 @MuxinFeng 的回复，远程数据是由远程控制，前端只是做展示用。

**Comment by lsq33123** [comment]
> Reference i

我知道数据是由服务端排序的，我的问题是表格的箭头的排序方式不会 切换 一直都是descend

**Comment by lsq33123** [comment]
> 这里仅仅将 sorter 设置为 true 是没用的哈，还需要服务端配合。 可以理解为这个时候只有 sorter 对应的 ui 交互效果，然后你拿到 sorter 的值传给服务端，服务端做好排序再把结果给你。

按道理来说，每点击一下排序方式都会变，现在是不变的（我指的不是数据）

**Comment by MuxinFeng** [comment]
你在每次点击排序后，都会重新请求数据，然后重置 tableData，引起整个表格组件的刷新，所以看起来好像排序的交互没有触发一样。

**Comment by IHongTaoI** [comment]
> 你在每次点击排序后，都会重新请求数据，然后重置 tableData，引起整个表格组件的刷新，所以看起来好像排序的交互没有触发一样。

我也有遇到问题，我用远端排序时 defaultSortOrder 不起作用
