### ISSUE TITLE
change default font-size to 14px

### ISSUE THREAD

**Issue by pierre-b** [ant-design/ant-design#4143]
Hi guys,

The recommended default font size should not be less 14px (for latin characters), as it's hard for the eyes to read 12px letters (publishing websites use 16px minimum).

Even if it's possible to increase it in the theme, many components have been hardcoded for a 12px font-size and don't scale properly.

Is 12px the size in China?

Thanks

**Comment by benjycui** [comment]
I `grep`, but didn't find any component's font size is hard code.

You can just try to customize font size with theme, and PR anytime if you find hard code font size.

**Comment by yesmeck** [comment]
Close as there is no action can be token.

**Comment by pierre-b** [comment]
The issue here is not about the hardcoded font-size, but the default 12px.

Don't you think the default font size should be 14px and not 12px?

Thanks

**Comment by yesmeck** [comment]
@afc163 Any thoughts?

**Comment by benjycui** [comment]
It's by designed https://ant.design/docs/spec/typography

cc @Chinglik

**Comment by Chinglik** [comment]
Actually, 12-point font can be appropriately applied to enterprise-oriented scenario. But we are planing to  provide more theme configuration.

**Comment by pierre-b** [comment]
@Chinglik alright, thanks for taking it into consideration!

Github is 14px, try to use it with 12px for few days and you should be convinced ;)

**Comment by teesloane** [comment]
Just getting in here to say an ability to override fontsizes across the app would be amazing. Love this library! keep up the great work folks.

**Comment by tz5514** [comment]
14px is better. Ant Design is amazing but most component's size is too small.

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/5570

**Comment by parlop** [comment]
I'm using bootstrap 4 with antd, in order to change the font size I modified the file antd.css I replaced all the lines with font-size: 12px; to font-size: 16px; everything is fine.

**Comment by clodal** [comment]
@parlop Yeah but the components don't scale nicely, for example the datepicker popup dates should have higher paddings to create room for the larger font size.

**Comment by sebasgarcep** [comment]
The font size is definitely an issue. People without 20/20 vision also use the web and designing to exclude them is a bad move. And this library is too awesome for that.

**Comment by supersky07** [comment]
I use this design for some old people. And I create a `patch.css` to fix it. But it not as convenient as this design itself.

**Comment by afc163** [comment]
After antd@3.0, the default font size will be 14px.

**Comment by chenpeng1102** [comment]
Upgrade to antd@3.0, the default font change to 14px, But out UI design's default font is 12px, How to setting default font to 12px?

**Comment by chenpeng1102** [comment]
solved the issue by this(I used create react app)
https://ant.design/docs/react/use-with-create-react-app

**Comment by douglas168** [comment]
how do I set default font size to 16px?

**Comment by xrkffgg** [comment]
> how do I set default font size to 16px?

https://ant.design/docs/react/customize-theme#Ant-Design-Less-variables
