### ISSUE TITLE
Breadcrumb items配置menus后，menu的onClick事件获取的key是数组的index不是menu item的实际key

### ISSUE THREAD

**Issue by beeant0512** [ant-design/ant-design#41432]
### Steps to reproduce

```javascript

  const options = [{id: 'id1', name: 'name1'}, {id: 'id2', name: 'name2'}, ].map((data) => {
    return {
      key: data.id,
      label: data.name,
    };
  });


<Breadcrumb.Item
          key="breadcrumb"
          menu={{
            items: options,
            onClick: (e) => {
              console.log(e.key)
            },
          }}
        >
          
        </Breadcrumb.Item>


```

### What is expected?

console.log(key)  key是 id1, id2

### What is actually happening?

console.log(key)  key是 1, 2

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | ^18.2.0 |
| System | windows |
| Browser | chrome |

**Comment by Yuiai01** [comment]
https://codesandbox.io/s/ji-ben-antd-5-3-2-forked-y6pwym?from-embed=&file=/demo.tsx 看了一下确实是输出的下标，我看看是不是默认就是这样的~

**Comment by Yuiai01** [comment]
看了一下，因为现在不需要传入 key，默认会将下表作为 key，或许可以拓展一下 🤔

**Comment by MadCcc** [comment]
下表不能当 key，得改

**Comment by Yuiai01** [comment]
> 下标不能当 key，得改

那我改一下吧
