### ISSUE TITLE
select[多选] 有搜索值时,再次focus,会导致搜索值被清空 

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#41441]
### Reproduction link

[https://stackblitz.com/edit/react-thcqcp?file=demo.tsx](https://stackblitz.com/edit/react-thcqcp?file=demo.tsx)

### Steps to reproduce

随便搜索点什么,然后再次鼠标左键点击搜索框

### What is expected?

不要清空内容,就像单选框一样

### What is actually happening?

会执行onSearch,并清空内容

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by Wxh16144** [comment]
好像设计就是如此，有待考察🤔

**Comment by vaynevayne** [comment]
关键触发条件 可能是那个filter Option 为false

**Comment by zombieJ** [comment]
<img width="799" alt="截屏2023-03-27 11 27 18" src="https://user-images.githubusercontent.com/5378891/227833597-0ccc274f-e540-4d43-8ed3-fd003017d45a.png">


https://stackblitz.com/edit/react-thcqcp-ctgj7w?file=demo.tsx

**Comment by vaynevayne** [comment]
@zombieJ  感觉不是autoClear的原因, 而是 filterOption的逻辑有bug, 
autoClear设置项, 是让值常驻在tag旁边, 而bug是再次focus时值导致的, 跟有没有再次选中项目没有关系,

你切换设置 filterOption 为true/false, false 时将出现bug,
