### ISSUE TITLE
vite打包时报模块相互依赖

### ISSUE THREAD

**Issue by yanglee2421** [ant-design/ant-design#41444]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

使用vite@4.2.1打包antd@5.3.2版本的代码

### What is expected?

模块间的引用关系正常，打包不报异常

### What is actually happening?

模块间发生了相互依赖导致打包弹出异常信息

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | 19045.2728 |
| Browser | 111.0.1661.51 |

---
Export "genPresetColor" of module "node_modules/antd/es/style/presetColor.js" was reexported through module "node_modules/antd/es/style/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/antd/es/tag/style/index.js" to point directly to the exporting module or reconfigure 
"output.manualChunks" to ensure these modules end up in the same chunk.

**Comment by acyza** [comment]
给antd打到同一个包里呢?
```typescript
import { defineConfig } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
  //...
  build: {
   //...
    rollupOptions: {
      //...
      output: {
        manualChunks: (id) => {
          if (id.includes("node_modules/antd")) return "antd";
        },
      },
    },
  },
})
```

**Comment by yanglee2421** [comment]
把antd单独打到一个chunk可以解决报出的异常，不过打出来的chunk大小超过1m了

发件人: ***@***.***>
发送时间: 2023年3月24日 22:19
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ant-design/ant-design] vite打包时报模块相互依赖 (Issue #41444)


给antd打到同一个包里呢?

import { defineConfig } from 'vite'



// https://vitejs.dev/config/

export default defineConfig({

  //...

  build: {

   //...

    rollupOptions: {

      //...

      output: {

        manualChunks: (id) => {

          if (id.includes("node_modules/antd")) return "antd";

        },

      },

    },

  },

})

―

**Comment by luo3house** [comment]
```
components/tag/style/index.ts 
1 -> components/style/index.ts
2 -> components/style/presetColor.tsx
3 -> components/theme/internal.ts
4 -> components/theme/util/genComponentStyleHook.ts
5 -> components/style/index.ts -> 1
```

https://github.com/ant-design/ant-design/blob/950f7cf2c1292ea16c3f89832d61a95cc8e07bee/components/style/presetColor.tsx#L4
我认为这里应该改为 `interface` 毕竟它没有入度
```ts
import { PresetColors } from '../theme/interface';
```
