### ISSUE TITLE
components height is hardcoded

### ISSUE THREAD

**Issue by pierre-b** [ant-design/ant-design#4144]
Hi guys,

I use a 14px default font-size in my project and the following components have their height hardcoded, it would be good to use the ```@input-height-base```, ```@input-height-lg``` and ```@input-height-base```.

Affected components are:
- Select (line 161)
- Radio (line 140)
- Switch (line 11, 57)

Thanks for the fix ;)

**Comment by benjycui** [comment]
A PR is welcomed, and we will publish a patch in this weekend.
