### ISSUE TITLE
select组件能否添加clear的一个回调函数

### ISSUE THREAD

**Issue by BeastHoo** [ant-design/ant-design#41452]
### What problem does this feature solve?

当在select函数中同时使用search和allow-clear时，由于我使用@search用作搜索，而@change这个钩子函数和@search有一点重合，所以我不能在@change里面去处理clear时的情况，我想如果在清除图标上添加一个函数应当会使select组件的api更全面

### What does the proposed API look like?

比如，当我点击select组件上的清除图标时，此时会触发一个@clear的钩子

**Comment by Wxh16144** [comment]
现在的 `<Select />` 组件有 `onSearch` 事件回调，你可以在 `onSearch` 中做业务逻辑，另外设置了 `allowClear` 同时 `onClear` 方法也会触发执行，clear 后会触发 `onChange`。

这里有个示例： https://codesandbox.io/s/sou-suo-kuang-antd-5-3-2-forked-b15vul?file=/demo.tsx
文档：https://ant.design/components/select-cn#components-select-demo-search-box

如果你需要 clear 单独做事件响应，可以考虑通过 `clearIcon` 自定义一个 clear 图标和自定义事件方法。
