### ISSUE TITLE
Form.List不显示初始输入框

### ISSUE THREAD

**Issue by cityvoice** [ant-design/ant-design#41459]
### Reproduction link

[https://codepen.io/cityvoice/pen/qBMgVzK?editors=001](https://codepen.io/cityvoice/pen/qBMgVzK?editors=001)

### Steps to reproduce

无

### What is expected?

在没有提供初始值时，需要有一个初始输入框

### What is actually happening?

不提供初始值时，无默认输入框

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2 |
| System | windows |
| Browser | chrome |

---
目前解决办法是提供一个包含undifined的初始值，比如[undefined]

**Comment by Yuiai01** [comment]
你这个链接貌似看不见项目，能重新提供一个吗？

**Comment by cityvoice** [comment]
> 你这个链接貌似看不见项目，能重新提供一个吗？

已重新更新预览地址。

**Comment by zombieJ** [comment]
> 目前解决办法是提供一个包含undifined的初始值，比如[undefined]

Form.List 默认是空列表，需要初始输入框就是在初始值里提供一个预设值哈。
