### ISSUE TITLE
defaultExpandAllRows={true}不展开问题

### ISSUE THREAD

**Issue by seap** [ant-design/ant-design#4145]
![image](https://cloud.githubusercontent.com/assets/944003/20910809/dc4d76c2-bb9e-11e6-8ccf-3707a8cdf8d7.png)

#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本: Mac
- 浏览器及其版本: Chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

```
<Table
     ...
     defaultExpandAllRows={true}
/>
```

#### 您期待的结果是:

默认展开树型table的结点

#### 实际上的结果是:
默认没有展开

**Comment by haisapan** [comment]
遇到同样的问题

**Comment by Catlite91** [comment]
这个我也遇到过，在很多ant组件中都是（如tree，input），不知道算不算一个问题。
原因可能是因为初始值data被替换掉后，如setState后data从空对象，变成了对象数组，导致重新渲染后所有和Default相关的属性都无效。
是否可以考虑在willReceiveProps中增加对default属性的控制？

**Comment by yesmeck** [comment]
是这个原因吗？

https://github.com/react-component/table/issues/93#issuecomment-259054213

**Comment by yesmeck** [comment]
@Catlite91 以 Input 为例，defaultValue 是（仅）用来设置默认值，如果要控制值的变化应该用 value，其他组件亦如是。

**Comment by Catlite91** [comment]
@yesmeck 确实应该是这样，但总觉得defaultValue用处不大，但一旦用到，很容易出错

**Comment by yesmeck** [comment]
@Catlite91 请研读：https://facebook.github.io/react/docs/forms.html

**Comment by spademan** [comment]
我也遇到这个问题

**Comment by yesmeck** [comment]
@spademan 确保有正确的 rowKey。

**Comment by spademan** [comment]
@yesmeck  是有的，不然会红warn的

**Comment by yesmeck** [comment]
@spademan 给个重现吧。

**Comment by spademan** [comment]
@yesmeck 暂时没时间写demo..囧
你异步一个数据估计就能出现 
复现步骤
1.componentWillMount中触发请求
2.render中渲染table
实在没复现的话 我晚点给

**Comment by yesmeck** [comment]
@spademan 那晚点给吧，拜托了。

**Comment by spademan** [comment]
demo 来了 ~~ 大大 @yesmeck   
http://codepen.io/spademan/pen/ggpjbw?editors=1010

**Comment by yesmeck** [comment]
`defaultExpandAllRows` 文档说的 `初始时，是否展开所有行`，第二次渲染其实已经不是初始时了吧。

**Comment by spademan** [comment]
你这么说 我是没有什么异议的.不过表格的作用大多都是展示数据,而数据本身可不是一开始就会有的.毕竟用`react`不是在写静态网页...,数据都是从后端请求而来的.如果说因为他叫 `defaultExpandAllRows`这个`default` 限制了他的行为.那要是有一个  `alwaysExpandAllRows`属性就好了,只要我不手动关闭它,只要我不手动关闭它都会展示 不管是第一次还是第二次.
估计提这个issue的最初都是这样用这个属性的.
大大 你说是吧?

**Comment by yesmeck** [comment]
是的，`defaultExpandAllRows ` 确实比较鸡肋，不过用 `expandedRowKeys` 自己控制一下也很简单。

**Comment by spademan** [comment]
expandedRowKeys 要指定...要是n多行的话 而且是动态的 .估计有点强编了...哈哈

**Comment by afc163** [comment]
`this.state.data ? <Table defaultExpandAllRows={...} dataSource={this.state.data} /> : null`

也可以这样，数据没加载完之前不渲染。

**Comment by caolvchong** [comment]
defaultExpandAllRows 基本没啥用，可以通过 expandedRowKeys，onExpand 两个结合控制一下

http://codepen.io/anon/pen/PWPWqz?editors=0010

里面的state可以根据自己需要放到redux之类的，有分页的分页获取数据后处理下就好了

**Comment by wuguanghai45** [comment]
@afc163  如果本身数据是空的话， 表格的title都不会显示。。。

**Comment by wuguanghai45** [comment]
<Table
     key={`table-${this.state.data && this.state.data.length}`}
     defaultExpandAllRows={true}
/>
借助了key改变自动变成新的componet
虽然可以解决默认问题。。但总觉得不是key正确的用法

**Comment by benjycui** [comment]
@wuguanghai45 如你认为碰到 bug，应该单独起一个 issue，并提供可重现 demo
