### ISSUE TITLE
Table组件在可拖拽场景下，操作按钮如果添加Popconfirm，按钮操作会失效

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design#41457]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuo-zhuai-pai-xu-antd-5-3-2-forked-nlkwnx?file=/demo.tsx)

### Steps to reproduce

给可拖拽Table操作按钮添加Popconfirm，点击按钮操作失效

### What is expected?

点击按钮可正常操作

### What is actually happening?

点击操作按钮失效，且Popconfirm不会弹出提示框

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 17 |
| System | MacOs |
| Browser | chrome |

**Comment by zombieJ** [comment]
`@dnd-kit/sortable` 默认会劫持事件，导致 `onClick` 不会触发。可以参考其 issue 进行处理： https://github.com/clauderic/dnd-kit/issues/893
