### ISSUE TITLE
Form.Item not get value from Input field. 

### ISSUE THREAD

**Issue by prashilCeloxis** [ant-design/ant-design#41473]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-float-label-forked-s2xqxe?file=/Example.js)

### Steps to reproduce

 Add  text to input field and save form.

### What is expected?

Get updated value from input field on submitting of form.

### What is actually happening?

Not getting updated value from input field.

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | react 18 |
| System | macOS moneterey version 12.2.1 |
| Browser | Chrome Version 111.0.5563.64  |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-float-label-forked-uvb5gr
