### ISSUE TITLE
RangePicker 设置defaultValue 报错

### ISSUE THREAD

**Issue by alonehover** [ant-design/ant-design#4147]
#### 发生问题的环境是：
- antd 版本: 2.5.1
- 操作系统及其版本: macOS 10.12.1
- 浏览器及其版本: chrome 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

引入antd 的 RangePicker，并按照官方示例设置了默认值

#### 您期待的结果是:

像官网一样正常显示默认值

#### 实际上的结果是:

浏览器控制台报错

    bundle.js:52856 Uncaught Error: The value/defaultValue of RangePicker must be a moment object array after `antd@2.0`

#### 可重现的在线演示

http://codepen.io/anon/pen/yVKRxM?editors=0010

**Comment by benjycui** [comment]
你直接使用 `dist/antd.js` 是么？

**Comment by sangxiaolong** [comment]
2.5.1版本的依然报错啊

The value/defaultValue of RangePicker must be a moment object array after `antd@2.0`

**Comment by benjycui** [comment]
等待 2.5.2 

上面的修改还么发布。
