### ISSUE TITLE
clone项目之后使用npm install安装依赖时提示报错

### ISSUE THREAD

**Issue by resetsix** [ant-design/ant-design#41479]
### Reproduction link

[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce

1、cd ant-design
2、npm install

### What is expected?

安装完依赖能正常start运行项目

### What is actually happening?

安装依赖时报错:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@19.8.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@19.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\nodejs\node_cache\_logs\2023-03-27T08_25_00_738Z-debug.log
```

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.0.0 |
| System | win10 |
| Browser | 版本 111.0.5563.65（正式版本）（64 位） |

**Comment by zombieJ** [comment]
网络问题，可以搜索一下如何配置 npm 安装 puppeteer 使用国内镜像哈。
