### ISSUE TITLE
cascader filter search result max length is 50

### ISSUE THREAD

**Issue by kylvia** [ant-design/ant-design#41477]
### Reproduction link

[https://stackblitz.com/edit/react-jsa2bt?file=demo.tsx](https://stackblitz.com/edit/react-jsa2bt?file=demo.tsx)

### Steps to reproduce

Search box input : ‘a’

### What is expected?

 All the results of the matched

### What is actually happening?

If the number of matching entries exceeds 50, only 50 entries are displayed

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome  111.0.5563.64 (arm64) |

**Comment by zombieJ** [comment]
https://ant.design/components/cascader#showsearch

<img width="927" alt="截屏2023-03-27 15 24 01" src="https://user-images.githubusercontent.com/5378891/227869836-6f61d6bc-8d95-43f3-ba2b-997994f9f975.png">
