### ISSUE TITLE
Transfer穿梭框在oneWay模式下，右侧缺失hover鼠标悬停整行高亮样式

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#41485]
### Reproduction link

[https://ant.design/~demos/components-transfer-demo-oneway](https://ant.design/~demos/components-transfer-demo-oneway)

### Steps to reproduce

Transfer穿梭框在oneWay模式下，右侧缺失hover鼠标悬停整行高亮样式。在非oneWay模式下正常

### What is expected?

hover鼠标悬停整行高亮 

### What is actually happening?

hover鼠标悬停整行无样式

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 108 |

**Comment by Yuiai01** [comment]
感觉 `oneWay` 就是这么设计的

**Comment by hihuangwei** [comment]
从体验上，有鼠标悬停高亮会体验更好

**Comment by zombieJ** [comment]
因为右侧悬停是没有交互的，交互在删除按钮上。但是如果有需求，你可以魔改一下样式哈。
