### ISSUE TITLE
用Omit处理DatePickerProps后部分属性不能被TS识别

### ISSUE THREAD

**Issue by GuanJdoJ** [ant-design/ant-design#41487]
### Discussed in https://github.com/ant-design/ant-design/discussions/41486

<div type='discussions-op-text'>

<sup>Originally posted by **GuanJdoJ** March 27, 2023</sup>
antd5中，DatePickerProps中有showTime属性
我自定义了个属性用于重写DatePickerProps的value属性
代码示例如下
```
import React from 'react';
import { DatePickerProps } from 'antd';

type PropsType = Omit<DatePickerProps, 'value'> & {
  value?: string; 
};

const MyComp: React.FC<PropsType> => {...}

export default  MyComp;
```
```
//此时会报错，不存在showTime
< MyComp showTime/>
```

此时在用PropsType的组件中再使用showTime就会报TS类型错误，请问下大家这个问题怎么解决</div>

**Comment by Wxh16144** [comment]
@GuanJdoJ 
<img width="801" alt="image" src="https://user-images.githubusercontent.com/32004925/227928687-301aab5f-6942-4f3e-a05a-77c38a1f095f.png">

**Comment by GuanJdoJ** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/30386473/227934865-f4489b64-5d8f-415c-b680-e5ff982bed97.png">
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/30386473/227935349-74da97ae-a5cf-4e09-92f1-e3474d2e982b.png">

应该是这个原因了
