### ISSUE TITLE
Cascader custom Input component can't input

### ISSUE THREAD

**Issue by wangjiaojiao77** [ant-design/ant-design#41483]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-x7olkb?file=/demo.js:0-387)

### Steps to reproduce

click Cascader => click zhejiang => appear Input

### What is expected?

except Input component can input

### What is actually happening?

Input component can't input

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | macOS 12.5.1 |
| Browser | Chrome  108.0.5359.124 |

**Comment by Yuiai01** [comment]
Is this input element can't input？
<img width="531" alt="image" src="https://user-images.githubusercontent.com/112228030/227910686-a6b6b9d2-15a3-4ff7-afc4-a7f072f67e39.png">

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-lqyks6?file=/demo.js

**Comment by wangjiaojiao77** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-lqyks6?file=/demo.js

it's work, thanks!
