### ISSUE TITLE
Modal   NextJS 13 - Expected server HTML to contain a matching <div> in <div>.

### ISSUE THREAD

**Issue by iquirino** [ant-design/ant-design#41495]
### Reproduction link

[https://github.com/iquirino/antd-nextjs13-hydrate-issue](https://github.com/iquirino/antd-nextjs13-hydrate-issue)

### Steps to reproduce

npx create-next-app@latest --typescript
Answers: my-app, yes, no, no, @/*
cd my-app

add ```import { Modal } from "antd";``` and ```<Modal open={true}>ANTD</Modal>``` to /pages/index.tsx

### What is expected?

To have modal showed well

### What is actually happening?

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <div> in <div>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | react: 18.2.0 |
| System | Linux Manjaro |
| Browser | All |

---
When I opened the Modal with useEffect, it worked well:
```
  const [visible, setVisible] = React.useState<boolean>(false);
  useEffect(() => {
    setVisible(true);
  }, []);

<Modal open={visible}>ANTD</Modal>
```

**Comment by MadCcc** [comment]
Your code is totally template code. BTW, have you tried `forceRender`?

**Comment by bombillazo** [comment]
This is probably due to some issue with SSR , ant design requires some specific setup for it to work server side, and Im guessing some components aren't build for SSR either.

**Comment by Atrus619** [comment]
@bombillazo can you point me in the direction of the "specific setup" you are talking about to make ant design work server side? I am making a switch to react server components and I heavily rely upon ant design, so I am looking for any and all tips you may have!

**Comment by bombillazo** [comment]
@Atrus619  Sure, this is the official way provided by the Ant Design docs:

https://ant.design/docs/react/customize-theme#server-side-render-ssr

There are 2 paths, inline or pre-baked (whole export). You can go through this thread as well for more on the discussion and further info:

https://github.com/ant-design/ant-design/issues/39891
