### ISSUE TITLE
WebComponent的shadow模式下，一个页面如果存在两个Table，第二个Table样式丢失

### ISSUE THREAD

**Issue by SailorF** [ant-design/ant-design#41490]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-3-2-forked-xkkjzp?file=/demo.tsx)

### Steps to reproduce

问题如题，打开 codesandbox 即可查看问题

### What is expected?

第二个Table样式不应该丢失

### What is actually happening?

第二个Table样式丢失

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome:111.0.5563.64 |

**Comment by SailorF** [comment]
@MadCcc 与 styleProvider 的使用有关系，麻烦帮忙看一下？ [合十]

**Comment by trionfordring** [comment]
前几个月处理过这个问题，每个shadowdom都需要一个独立的cache。
```jsx
const cache = useMemo(() => {
  return createCache();
}, []);

return (
  <StyleProvider container={shadowRoot} cache={cache}>
    {children}
  </StyleProvider>
);
```
不怎么会写前端不知道对不对，需要引入'@ant-design/cssinjs'包。注意打包`resolveId`阶段需要和antd里的是同一个。

**Comment by SailorF** [comment]
> 前几个月处理过这个问题，每个shadowdom都需要一个独立的cache。
> 
> ```js
> const cache = useMemo(() => {
>   return createCache();
> }, []);
> 
> return (
>   <StyleProvider container={shadowRoot} cache={cache}>
>     {children}
>   </StyleProvider>
> );
> ```
> 
> 不怎么会写前端不知道对不对，需要引入'@ant-design/cssinjs'包。注意打包`resolveId`阶段需要和antd里的是同一个。

可以，大佬牛逼
