### ISSUE TITLE
table设置fixed表头之后，dropdown在fixed那一列，滚动时dropdown的overlay跟随table纵向滚动了

### ISSUE THREAD

**Issue by rurounibatousai** [ant-design/ant-design#41505]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-biao-tou-ant-design-demo-forked-zvuift?file=/index.js)

### Steps to reproduce

展开Dropdown，滚动table

### What is expected?

希望dropdown不要跟随滚动

### What is actually happening?

dropdown跟随滚动

| Environment | Info |
| --- | --- |
| antd | 4.19.4 |
| React | 16.14.0 |
| System | Windows |
| Browser | Chrome 111.0.5563.65 |

**Comment by rurounibatousai** [comment]
如果设置了`getPopupContainer={(node) => node.parentElement}`,就会出现展示不全的问题

**Comment by rurounibatousai** [comment]
我提供的reproduce是不能展示完全的情况，请去掉`getPopupContainer`，即可出现跟随table纵向滚动的问题

**Comment by rurounibatousai** [comment]
目前尝试的方法是使用递归自行查找最上层tr，挂载到该tr即可实现滚动定位在原地。
如图：[https://imgloc.com/i/it7n5y](url)

**Comment by rurounibatousai** [comment]
> 目前尝试的方法是使用递归自行查找最上层tr，挂载到该tr即可实现滚动定位在原地。 如图：![it7n5y.png](https://camo.githubusercontent.com/36c7e6ee94734545cf9d226f59e5c690c06f721dec36af9b373780533fc0ba81/68747470733a2f2f692e3332383838382e78797a2f323032332f30332f32382f6974376e35792e706e67)

但是会出现tr宽度被撑开的问题

**Comment by zombieJ** [comment]
rc-dropdown 还没替换新版 `@rc-component/trigger`

**Comment by DercilioFontes** [comment]
Adding to tbody worked for me.
``` typescript
// adds to tbody for testing, avoiding style issues
getPopupContainer={(triggerNode) => triggerNode.parentElement.parentElement.parentElement}
```

**Comment by rurounibatousai** [comment]
> Adding to tbody worked for me.
> 
> ```ts
> // adds to tbody for testing, avoiding style issues
> getPopupContainer={(triggerNode) => triggerNode.parentElement.parentElement.parentElement}
> ```

I‘ll try this,thank you!

**Comment by DercilioFontes** [comment]
> Adding to tbody worked for me.
> 
> ```ts
> // adds to tbody for testing, avoiding style issues
> getPopupContainer={(triggerNode) => triggerNode.parentElement.parentElement.parentElement}
> ```

This solution is getting a new warning in antd v5.5.0
`Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>.`

So, appending to a table parent element:
`getPopupContainer={(triggerNode) => document.getElementById('container')}`

**Comment by rurounibatousai** [comment]
> > Adding to tbody worked for me.
> > ```ts
> > // adds to tbody for testing, avoiding style issues
> > getPopupContainer={(triggerNode) => triggerNode.parentElement.parentElement.parentElement}
> > ```
> 
> This solution is getting a new warning in antd v5.5.0 `Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>.`
> 
> So, appending to a table parent element: `getPopupContainer={(triggerNode) => document.getElementById('container')}`

maybe there is a official solution next version~.thanks for your answer!

**Comment by MadCcc** [comment]
Reproduction 打不开了。目前 5.5.1 版本下 Dropdown 已迁移 `@rc-component/trigger`，有问题欢迎新开 issue 反馈

**Comment by rurounibatousai** [comment]
> Member

好的 感谢
