### ISSUE TITLE
Timepicker组件onBlur方法的e.target.value没法拿到最新选中的时分秒值

### ISSUE THREAD

**Issue by LeMorlalala** [ant-design/ant-design#41504]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ze-shi-fen-antd-undefined-forked-3lphg8?file=/demo.tsx)

### Steps to reproduce

选好“时分秒”值之后，不点击“确定”，直接点击空白处，触发“onBlur”事件，拿到的e.target.value不是我选定的值，是上一次输入框内的值。
我使用antd4.x结合React16.13.1,onBlur表现正常；
我使用antd5.x结合React18.x ,onBlur表现也正常；
但是使用antd5.x结合React16.13.1, onBlur表现不正常；

### What is expected?

onBlur事件触发后拿到的e.target.value能够正常为选定的值

### What is actually happening?

onBlur事件触发后拿到的e.target.value是上一次输入框内的值

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 16.13.1 |
| System | win10 |
| Browser | Chrome 111 |

**Comment by zombieJ** [comment]
不要依赖 `onBlur` 事件获取数值，所有取值都应该从 `onChange` 来。如果是 `onBlur` 记录更新，应该 HOC 组件，然后记录 `onChange` 值然后在 `onBlur` 时抛出。

**Comment by LeMorlalala** [comment]
> 不要依赖 `onBlur` 事件获取数值，所有取值都应该从 `onChange` 来。如果是 `onBlur` 记录更新，应该 HOC 组件，然后记录 `onChange` 值然后在 `onBlur` 时抛出。

在选择`时分秒`不点击`确定`按钮的情况，或者直接输入时间而没有回车的情况，都不会触发`onChange`

**Comment by zombieJ** [comment]
`onPanelChange`，不过不太推荐最终确认前的数据获取

**Comment by LeMorlalala** [comment]
我用的antd版本是5.2.3, 测试下来无论怎么样都不能触发`onPanelChange`方法 😅

**Comment by LeMorlalala** [comment]
我说的是`TimePicker`组件
