### ISSUE TITLE
Can't change type of week in datepicker and change week position for example from Mo to Sun

### ISSUE THREAD

**Issue by ssdeniss** [ant-design/ant-design#41515]
### Reproduction link

[https://stackblitz.com/edit/react-9aegkj-uaq4dx?file=index.js](https://stackblitz.com/edit/react-9aegkj-uaq4dx?file=index.js)

### Steps to reproduce

Just open the date picker, in old version is working but after 5.0.0 not

### What is expected?

Can't change type of week in datepicker and change week position for example from Mo to Sun

### What is actually happening?

Can't change type of week in datepicker and change week position for example from Mo to Sun

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | last |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
v5 use dayjs not moment.
