### ISSUE TITLE
在3.0版本中进行切换时，点击4.x版本，跳转为5.0版本

### ISSUE THREAD

**Issue by LiYun-Ru** [ant-design/ant-design#41512]
### Reproduction link

[https://ant.design/components/form](https://ant.design/components/form)

### Steps to reproduce

进入3.x版本之后，点击右上方进行版本切换，选择4.x版本之后会自动跳转到5.x版本的页面中。

### What is expected?

跳转到4.x版本的对应组件库中。

### What is actually happening?

跳转到了5.x版本对应的组件库中。

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0 |
| System | mac/windows |
| Browser | 最新版本chrome浏览器 |

**Comment by MuxinFeng** [comment]
是不是要改一下 3.x-stable 的路由配置了

**Comment by MadCcc** [comment]
已经修复了，但是 3.x 的依赖可能要修一下才能发文档了

**Comment by afc163** [comment]
老的文档不再更新了。
