### ISSUE TITLE
DatePicker.RangePicker 中文设置不了

### ISSUE THREAD

**Issue by rankaifeng** [ant-design/ant-design#41523]
### Reproduction link

[http://192.168.100.176:3008/alarm-control/list](http://192.168.100.176:3008/alarm-control/list)

### Steps to reproduce

在v5.X之前 在入口文件设置了import zhCN from 'antd/lib/locale/zh_CN';
import 'moment/dist/locale/zh-cn'; 正常使用日期控件都是显示的中文 但是在升级为5.x之后 日期控件就设置不了中文

### What is expected?

日期控件星期 月份都显示中文

### What is actually happening?

日期控件 星期几 月份都是显示的英文

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | react |
| System | mac |
| Browser | Chrom |

---
这是内网地址 打不开的

**Comment by zombieJ** [comment]
v5 不是 moment，是 dayjs。参考 https://ant.design/components/config-provider-cn#components-config-provider-demo-locale 示例调整一下哈~
