### ISSUE TITLE
table的Table.Summary 的fixed元素不生效

### ISSUE THREAD

**Issue by lemonig** [ant-design/ant-design#41522]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sui-ye-mian-gun-dong-de-gu-ding-biao-tou-he-gun-dong-tiao-antd-5-3-2-forked-ksihsh?file=/demo.js)

### Steps to reproduce

summer返回多个元素时候，fixed="top" 不生效

### What is expected?

期望 `  <Table.Summary fixed="top">` 的元素固定在table首行

### What is actually happening?

`<Table.Summary fixed="top">` 的元素出现在末行

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | window 10 |
| Browser | chrome 110.0.5481.178 |

---
我反复的测试官网给的demo，发现 <Table.Summary fixed="top">元素只能做为的顶层元素才能生效，而放在`<></>`中，或者放在数组中返回都是无效的。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/37126#issuecomment-1219158152

**Comment by lemonig** [comment]
这么说，`table.sumary`是不能实现 同时在首行和末行的咯。 只能是在首行**或者** 在末行，这样理解吗吗?

**Comment by lemonig** [comment]
> [#37126 (comment)](https://github.com/ant-design/ant-design/issues/37126#issuecomment-1219158152)

这么说，table.sumary是不能实现 同时在首行和末行的咯。 只能是在首行或者 在末行，这样理解吗吗?
