### ISSUE TITLE
官方示例Select选择器没有设置宽度并带搜索框时样式异常

### ISSUE THREAD

**Issue by jianhuagao** [ant-design/ant-design#41530]
### Reproduction link

[https://3bgn3i.csb.app/](https://3bgn3i.csb.app/)

### Steps to reproduce

1.点击select选择器，先选择一个选项（必须）
2.在select选择器进行输入即可复现

![bug32901](https://user-images.githubusercontent.com/39371828/228466995-27af0aa3-6f28-412b-a4e9-ade6c4623d57.gif)

### What is expected?

宽度显示正常

### What is actually happening?

宽度异常

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome 111.0.5563.147 |

**Comment by MadCcc** [comment]
加一个最小宽度，避免没有 placeholder 时宽度缩成 0 的情况

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27688

**Comment by afc163** [comment]
#41534 不是解决办法，要看下 4.24.8 为啥没这个问题了。

https://github.com/ant-design/ant-design/issues/27688#issuecomment-1475156610

**Comment by MadCcc** [comment]
select 一直没有最小宽度，通常使用的时候会加上宽度所以没有问题。

**Comment by zombieJ** [comment]
这个从 v2 起就是这个逻辑，在 v4 alpha 时加过最小宽度，但是这是一个 breaking change 后来就没有加上。所以 2、3、4、5 都是没有最小宽度的：

<img width="51" alt="截屏2023-04-04 17 14 12" src="https://user-images.githubusercontent.com/5378891/229745632-7536def2-c513-4752-8306-3f3fbcc4cd72.png">

**Comment by MadCcc** [comment]
4.24.8 官网可以复现的

**Comment by afc163** [comment]
我再看看，这个应该是可以修复的。

**Comment by afc163** [comment]
@MadCcc @zombieJ 看下 https://github.com/react-component/select/pull/934
