### ISSUE TITLE
Slider组件第一次显示Tooltip时报错： Warning: [antd: Tooltip] `forcePopupAlign` is align to `forceAlign` instead.

### ISSUE THREAD

**Issue by chengjian1998** [ant-design/ant-design#41532]
### Reproduction link

[https://79gldi.csb.app/](https://79gldi.csb.app/)

### Steps to reproduce

鼠标第一次移入Slider的滑块，显示Tooltip时报错：Warning: [antd: Tooltip] `forcePopupAlign` is align to `forceAlign` instead.

### What is expected?

不报错

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | windows10 |
| Browser | Chrome 110.0.5481.180 |

**Comment by MuxinFeng** [comment]
我来个 pr 吧~
