### ISSUE TITLE
导航菜单Menu 警告getElementById() 被传递了空字符串参数

### ISSUE THREAD

**Issue by tyyzqmf** [ant-design/ant-design#4153]
#### 发生问题的环境是：

- antd 版本:2.5.0
- 操作系统及其版本:
- 浏览器及其版本:

#### 您做了什么？请提供尽可能详细的重现步骤。
引入 Menu 

#### 实际上的结果是:
官网的例子也有警告

**Comment by yesmeck** [comment]
我这边官网没看到警告，你用的什么浏览器？

**Comment by benjycui** [comment]
重现步骤捏。

**Comment by tyyzqmf** [comment]
浏览器：火狐50.0.2，F12调试界面就能看到
https://ant.design/components/menu/
但是Google Chrome好像不会

**Comment by yesmeck** [comment]
我这也没有，重现步骤？相信错误信息？

**Comment by tyyzqmf** [comment]
打开网页，然后F12-控制台就能看到警告了

**Comment by yesmeck** [comment]
没看到。Menu 中应该也没有用到 getElementById，请检查下自己的代码，浏览器插件等等。

**Comment by xushimin** [comment]
看看是不是使用了lable标签，其中有一个属性是for，在firefox会去找for属性的值id，如果把for属性去掉则不会出现相关问题
