### ISSUE TITLE
Menu is not rendered

### ISSUE THREAD

**Issue by juanvalag2019** [ant-design/ant-design#41544]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapsed-inline-menu-antd-4-24-8-forked-wyzs9h?file=/demo.js)

### Steps to reproduce

Run the code

### What is expected?

The inline menu should be rendered 

### What is actually happening?

The menu does not render

| Environment | Info |
| --- | --- |
| antd | 4.16.12 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome v111.0.5563.110 |

**Comment by MadCcc** [comment]
Menu `items`  is available after `4.20.0`. Please upgrade your dependencies.
