### ISSUE TITLE
table 列中有 group 且横向滚动时最右列对齐错误

### ISSUE THREAD

**Issue by Phinome** [ant-design/ant-design#41549]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-3-3-forked-2z77vn)

### Steps to reproduce

横向滚动时

### What is expected?

横向滚动时最右侧列行对齐

### What is actually happening?

横向滚动时最右侧列行没有对齐

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.0.0 |
| System | codesandbox |
| Browser | 111.0.5563.110 |

**Comment by MadCcc** [comment]
指定一下宽度可不可以？
https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-3-3-forked-v4gxve?file=/demo.tsx

**Comment by zombieJ** [comment]
最右列剩余的空间不足，加宽度即可：
https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-3-3-forked-d674ge?file=/demo.tsx:887-998

**Comment by Phinome** [comment]
@MadCcc 目前不支持不指定宽度而达到自适应内容宽度么？

**Comment by zombieJ** [comment]
不指定宽度是列自适应，但是你的滚动空间是固定的，所以剩余空间就是不足撑不开了。

**Comment by Phinome** [comment]
@zombieJ ok，明白了。多谢
