### ISSUE TITLE
 Antd@5 的 Table 组件在 Nest.js@13 中先以无 css 样式的形式进行渲染，之后可正常展示. 

### ISSUE THREAD

**Issue by lucaschang95** [ant-design/ant-design#41545]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/compassionate-jang-qokerd)

### Steps to reproduce

刷新页面

### What is expected?

首次渲染携带 antd table 样式

### What is actually happening?

首次渲染不携带 antd table 样式

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | Mac |
| Browser | chrome 111 |

---
https://codesandbox.io/p/sandbox/compassionate-jang-qokerd

**Comment by Tongyaoyu** [comment]
我在#41498 这里提问，有一个回复，同时我想请问在next.js13中，你是怎么修改antd5中组件的默认样式的，正如 #41498 中所说，css module想改默认样式不起作用或报错，有什么好方法吗

**Comment by MadCcc** [comment]
参照文档：https://ant.design/docs/react/customize-theme-cn#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%B8%B2%E6%9F%93
