### ISSUE TITLE
官网的nextjs自定义主题例子无效

### ISSUE THREAD

**Issue by ibufu** [ant-design/ant-design#41559]
### Reproduction link

[https://github.com/ant-design/create-next-app-antd](https://github.com/ant-design/create-next-app-antd)

### Steps to reproduce

```
import fs from "fs";
import { extractStyle } from "@ant-design/static-style-extract";
import { ConfigProvider } from "antd";
import React from "react";

const outputPath = "./public/antd.min.css";

// 1. default theme

// const css = extractStyle();

// 2. With custom theme

const testGreenColor = "#008000";
const testRedColor = "#ff0000";

const css = extractStyle((node) => (
  <>
    <ConfigProvider
      theme={{
        token: {
          colorBgBase: testGreenColor,
        },
      }}
    >
      {node}
    </ConfigProvider>
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: testGreenColor,
        },
      }}
    >
      <ConfigProvider
        theme={{
          token: {
            colorBgBase: testRedColor,
          },
        }}
      >
        {node}
      </ConfigProvider>
    </ConfigProvider>
  </>
));

fs.writeFileSync(outputPath, css);

console.log(`🎉 Antd CSS generated at ${outputPath}`);
```
修改文件genAntdCss.tsx

### What is expected?

主题变化

### What is actually happening?

主题没有变化

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by kiner-tang** [comment]
我来看看

**Comment by kiner-tang** [comment]
@ibufu 如果着急的话，可以尝试按照这种方式支持自定义主题的静态化样式抽离

**Comment by ibufu** [comment]
> @ibufu 如果着急的话，可以尝试按照这种方式支持自定义主题的静态化样式抽离：https://github.com/ant-design/create-next-app-antd/pull/5/files#diff-a9827ce1be32c607c948881a89b99c592f752898f9c49e0dea0b7199eb151029

测试了一下，虽然确实分离了css，但是 server 返回的 HTML 首屏还是没有样式的。

**Comment by kiner-tang** [comment]
> > @ibufu 如果着急的话，可以尝试按照这种方式支持自定义主题的静态化样式抽离：https://github.com/ant-design/create-next-app-antd/pull/5/files#diff-a9827ce1be32c607c948881a89b99c592f752898f9c49e0dea0b7199eb151029
> 
> 测试了一下，虽然确实分离了css，但是 server 返回的 HTML 首屏还是没有样式的。

你有在 _app.tsx 中引入样式吗？
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/10286961/229035497-51960ee4-aa0e-42db-8d4d-ffe8993c45da.png">

**Comment by ibufu** [comment]
duplicate https://github.com/ant-design/ant-design/issues/41573
