### ISSUE TITLE
TimePicker 不想要日期

### ISSUE THREAD

**Issue by onlyWuj** [ant-design/ant-design#4155]
目前用了一个TimePicker，显示的时候只有时分秒，但数据保存的时候把日期也带上了。

看了antd的文档，好像没有这样一个设置。

请问：有没有这样一个参数设置呢。

如果没有，那我也只有在form数据收集的时候自动进行处理了，只是有点别扭。

**Comment by benjycui** [comment]
https://ant.design/components/form/#components-form-demo-time-related-controls

**Comment by onlyWuj** [comment]
谢谢
