### ISSUE TITLE
drawer内使用tabs时，某些状态会出现 duplicated key 错误

### ISSUE THREAD

**Issue by Xcstar1360** [ant-design/ant-design#41552]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-aryabhata-jly1w4?file=/src/App.js)

### Steps to reproduce

1. 打开抽屉，然后直接关闭，Console 没有任何报错，good
2. 再次打开抽屉，将 Tabs 的头部滚动至最后一个 tab（无需激活该tab内容）,然后关闭抽屉，会发现 Console 报 duplicate key
3. 原因应该是 Tabs moreIcon 的 Context.Provider 计算存在问题

### What is expected?

无论 Tabs 是处于什么状态下切换抽屉是否可见，都不应该有任何报错

### What is actually happening?

在 Tabs 头部的一些特殊位置，切换抽屉的可见性，会提示绑定了重复的 key 值

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Window10 20H2 |
| Browser | Chrome 110.0.5481.178（正式版本）（64位） |

**Comment by Xcstar1360** [comment]
复现步骤需要更新一下，按照上面的复现步骤不能100%出现：
1. 打开抽屉，然后直接关闭，Console 没有任何报错，good
2. 再次打开抽屉，使用 Tabs 的 moreIcon 切换至最后一个 tab，然后关闭抽屉
按照上面两步可以稳定复现

**Comment by zombieJ** [comment]
有意思。。。

**Comment by guan404ming** [comment]
I will try to fix it!

**Comment by Ec-tracker** [comment]
以sandbox中的示例测试看下来是因为rc-tabs里TabNavList中useVisibleRange这个hooks这里出了问题：
![image](https://user-images.githubusercontent.com/46723726/236249252-d0fcb9e5-6509-453b-a85f-212d6fbb20d9.png)
这里的visibleStart变成了2而visibleEnd变成了0，直接导致接下来的这部分根据visibleStart和visibleEnd截取数组再合并时出现错误了：
![image](https://user-images.githubusercontent.com/46723726/236250711-ad40d34f-14e3-4c86-9dcb-bcf79517814c.png)
可以看到合并时，由于截取的两个数组有重叠元素最终导致生成hiddenTabs也有了重复的元素。hiddenTabs是之后生成dropdown列表所需要的。


回到之前useVisibleRange Hooks, 个人推测是因为在drawer隐藏后这个visbleTabContentValue变为了0, 导致了之后计算startIndex和endIndex出现了逻辑错误。
![image](https://user-images.githubusercontent.com/46723726/236252204-73170772-a503-485d-8e02-d26a8ae863e4.png)

**Comment by linxianxi** [comment]
https://github.com/react-component/tabs/pull/664 应该解决了

**Comment by heiyu4585** [comment]
已解决
