### ISSUE TITLE
Tabs切换后items中的children组件参数更新两次

### ISSUE THREAD

**Issue by opopeieie** [ant-design/ant-design#41551]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-chihiro-kxtzvt?file=/App.js)

### Steps to reproduce

App.js -> line:14, line:6

### What is expected?

新版本items写法，children主需要触发一次

### What is actually happening?

触发两次

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 17.x,18.2 |
| System | Mac OS |
| Browser | Chrome |

---
items模式把React组件与数据强行捆绑起来是否会对后续开发产生更多困难（处理数据的同时还需要维护ReactElement的代价），有没有可能JSX本身就是一种常用的数据驱动了？

**Comment by MadCcc** [comment]
https://codesandbox.io/s/headless-waterfall-prw01p?file=/OldApp.js
因为你 JSX 写法里 prop 写成 `mode` 了

**Comment by MadCcc** [comment]
> items模式把React组件与数据强行捆绑起来是否会对后续开发产生更多困难（处理数据的同时还需要维护ReactElement的代价），有没有可能JSX本身就是一种常用的数据驱动了？

因为内部实现会把 JSX 先转成数据处理，所以直接使用 items 省去了这一步骤

**Comment by zombieJ** [comment]
你写错了，两个等价的：
```diff
-- mode={mode}
++ data={mode}
```

> 有没有可能JSX本身就是一种常用的数据驱动了？

JSX 本身是 ReactElement，并不是数据。内部仍然要将其转为数据，这就导致了 HOC 的组件是没有办法获取真实数据内容。它不是真正的数据驱动。

**Comment by opopeieie** [comment]
好的，我的Demo写的太差了
