### ISSUE TITLE
CheckBox text on the left

### ISSUE THREAD

**Issue by emin-karadag** [ant-design/ant-design#41557]
### What problem does this feature solve?

Hello,
In the last version available, when using the CheckBox, the text is on the right and the selection is on the left.
I want the opposite of that. That is, the text is on the left and the selection box is on the right.
How can I do that?

### What does the proposed API look like?

[CheckBox](https://ant.design/components/checkbox)

**Comment by zombieJ** [comment]
It's revert in RTL: https://ant.design/components/checkbox?direction=rtl
<img width="240" alt="截屏2023-03-30 15 12 51" src="https://user-images.githubusercontent.com/5378891/228757884-59e2f93f-5244-4bac-9c61-1f5997b44b7b.png">


Or you can use checkbox only without text and wrap by your own to adjust.

Or css to change the order of inline-flex layout
