### ISSUE TITLE
Modal的closable属性失效 小插号关闭不了

### ISSUE THREAD

**Issue by kcshan** [ant-design/ant-design#4156]
Modal组件的closable属性失效 小插号隐藏不了

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
It is working: http://codepen.io/anon/pen/XNEvMW?editors=001

**Comment by kcshan** [comment]
thanks

**Comment by kcshan** [comment]
thanks

**Comment by afc163** [comment]
不能重现的 bug 往往给维护者添加负担。
