### ISSUE TITLE
5.x版本弹层类组件兼容旧浏览器

### ISSUE THREAD

**Issue by winner0330** [ant-design/ant-design#41560]
### What problem does this feature solve?

5.x版本样式兼容旧浏览器官方给出的解决办法为使用 @ant-design/cssinjs 取消默认的降权，但是这一操作只能对root节点中的元素生效，对于message、modal等弹出层并不起作用，希望可以有一个解决方法。

### What does the proposed API look like?

5.x版本中的弹出层兼容旧版本浏览器

**Comment by zombieJ** [comment]
使用 App 组件哈：
https://ant.design/components/app-cn

**Comment by winner0330** [comment]
> 使用 App 组件哈： https://ant.design/components/app-cn

使用App组件可以解决弹层类不兼容的2问题，但是伪元素的样式还是没有办法兼容旧浏览器怎么办呀......

**Comment by winner0330** [comment]
请问伪元素样式不兼容旧浏览器有什么解决办法吗？
&nbsp;


周雨莹
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 下午5:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] 5.x版本弹层类组件兼容旧浏览器 (Issue #41560)





 
使用 App 组件哈：
 https://ant.design/components/app-cn

**Comment by zombieJ** [comment]
伪类可以给个重现看看，按理说降级后 v5 v4 用的都是相同的 css selector，就没有新特性了
