### ISSUE TITLE
Input + Form defaultValue onFinish no working

### ISSUE THREAD

**Issue by YuvalPeretz** [ant-design/ant-design#41562]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ktxlu5?file=/index.js)

### Steps to reproduce

1. Create a Form and insert a Form.Item with an Input inside of it
2. Add to the Form an onFinish function to display the Input of the Form
3. Add to the Input any defaultValue
4. Add a submit Button to the Form
5. Now watch the result, the value inside of the Input that was set by the defaultValue won't display in the Form result

### What is expected?

To have the defaultValue as an Input value inside of the Form submit result.

### What is actually happening?

An undefined is placed instead of the value.

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

---
If you change the value inside of the Input the result will yield the expected outcome.

**Comment by afc163** [comment]
Try Form `initialValues`：https://codesandbox.io/s/antd-reproduction-template-forked-z4ouq4?file=/index.js
