### ISSUE TITLE
Uncaught Error: Minified React error 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#41563]
重现方式：

1. 访问 https://ant-design.antgroup.com/components/table-cn#components-table-demo-filter-in-tree
2. 等右边 anchor 出现后，随便点一个演示。

<img width="1223" alt="图片" src="https://user-images.githubusercontent.com/507615/228887692-421facca-0657-43e5-9a62-66c65516227d.png">

**Comment by afc163** [comment]
<img width="150" alt="图片" src="https://user-images.githubusercontent.com/507615/229268029-9e3087fe-7baf-4158-9e29-8bdf00f1714f.png">

点击这两按钮，也会出现一样的问题。

**Comment by afc163** [comment]
@MadCcc 给个 dead line 吧，现在官网体验真的不太好。

**Comment by PeachScript** [comment]
同步下解决方案：
1. Umi 层实现一个假的 `Suspense`，只提供 Loading 功能，以确保可以在 API 不变更的情况下对原 Suspense 进行替换
2. Umi 层增加一个不公开的配置项，打开后会使用假的 `Suspense`，dumi 层默认开启该配置

计划时间点：下周四（06.01）Umi 和 dumi 一起发版

**Comment by MadCcc** [comment]
本周尝试实现了上周讨论的解决方案，不太顺利，发现了几个新坑：
1. 由于路由按需加载是刚需，所以需要使用 loadable 来替代 Suspense 做降级方案；
2. 使用 loadable 后服务端渲染需要特殊处理，保证首屏渲染完整的 html 以及在首屏 chunk 异步加载完成后再进行注水。

这样考虑的话改动量和复杂度上升非常多，需要重新评估一下对 umi 的改造方案。
1. 继续使用 Suspense。Suspense 特性下的分段注水会导致打断注水的现象发生，并且源头可能出现在三方包中（比如常用的 react-router)，这也是现在官网存在的问题。考虑到 React 18 现在主推 Suspense 和 renderToPipeableStream，还是要继续跟，看看有没有官方或者社区的解决方案。
2. 不使用 Suspense。需要对 umi 的 SSR 做一个完整的规划，包括路由方案，首屏处理等等。

目前官网主要问题是 `@ant-design/antd-style` 引入的，维护者也是我们自己，所以后面会先对该包做一个兼容方案。

**Comment by mistek131995** [comment]
I use Monorepository + Module Federation + Vite. When i press button component I have this error.

`
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Bt (index-OkZSMibp.js:30:16731)
    at r.useRef (__federation_shared_react-CsUMYuEf.js:9:6188)
    at oP (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:142:15315)
    at Sm (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:30:16998)
    at C1 (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:32:43950)
    at y1 (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:32:39714)
    at Yb (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:32:39642)
    at Mu (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:32:39495)
    at Fd (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:32:35862)
    at p1 (__federation_expose_AppCatalogIndex-Dq0HhWM2.js:32:34813)
`

**Comment by afc163** [comment]
https://ant-design.antgroup.com/index-cn 首页也有类似的情况了。

**Comment by PeachScript** [comment]
> https://ant-design.antgroup.com/index-cn 首页也有类似的情况了。

@Jinbao1001 这个是不是替换 CDN 资源导致的水合失败，有解法么

**Comment by Jinbao1001** [comment]
> > https://ant-design.antgroup.com/index-cn 首页也有类似的情况了。
> 
> @Jinbao1001 这个是不是替换 CDN 资源导致的水合失败，有解法么

是的, 镜像产物同步的时候注入环境变量应该可以解. @MadCcc 开搞?

**Comment by afc163** [comment]
https://ant-design.antgroup.com

https://ant-design.antgroup.com/components/button-cn

相同地址的 https://ant.design/ 则不会出现。


```
Error: Minified React error #418; visit https://react.dev/errors/418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

```
Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

![Jul-28-2024 09-11-59](https://github.com/user-attachments/assets/d9fcb9a8-6155-4116-ab99-a0729fe7a30c)

**Comment by PeachScript** [comment]
@zombieJ 已修复，issue 关闭
