### ISSUE TITLE
在ssr场景下使用antd页面会闪烁，用户体验非常差

### ISSUE THREAD

**Issue by ideaviewes** [ant-design/ant-design#41573]
### Reproduction link

[https://github.com/ant-design/create-next-app-antd.git](https://github.com/ant-design/create-next-app-antd.git)

### Steps to reproduce

git clone https://github.com/ant-design/create-next-app-antd.git
cd create-next-app-antd
tyarn
tyarn run build
tyarn start

### What is expected?

希望页面可以正常加载出来，不要闪烁

### What is actually happening?

打开页面后，页面会闪烁一下，这种体验真的非常糟糕，

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome |

---
https://github.com/ant-design/create-next-app-antd.git 是官方的演示示例，里面有这种问题。

**Comment by kiner-tang** [comment]
已经更新新的使用方式
- 相关 PR : https://github.com/ant-design/create-next-app-antd/pull/5
- 相关问题： https://github.com/ant-design/ant-design/issues/41559

**Comment by zombieJ** [comment]
@ideaviewes，试试最新的版本，如果有问题欢迎反馈哈

**Comment by kiner-tang** [comment]
> @zombieJ ,您好，是把antd更新到最新的5.3.3吗？

不需要升级 antd ，只需要参考：https://github.com/ant-design/create-next-app-antd.git 这里给出的最新 demo 实现即可。相关文档我们正在写，之后会更新到 antd 的文档当中

**Comment by ideaviewes** [comment]
@zombieJ ，您好，我重新下clone了一下，还是通用的问题，闪烁一下，然后样式加载出来，感觉像是transition的锅

**Comment by kiner-tang** [comment]
> @kiner-tang ，您好，我重新下clone了一下，还是同样的问题，闪烁一下，然后样式加载出来，感觉像是transition的锅

可以录个视频看看么？这边是不会闪烁的
![屏幕录制2023-03-31 14 06 43 mov](https://user-images.githubusercontent.com/10286961/229082451-68f751eb-5e36-47e8-9ca8-9b2046485a45.gif)

**Comment by ideaviewes** [comment]
@zombieJ ,您好
![image](https://user-images.githubusercontent.com/5431843/229085946-507ef8db-3709-4859-a814-509efa792c91.png)
![GIF 2023-3-31 17-41-46](https://user-images.githubusercontent.com/5431843/229085964-1dfb2fe7-a8a2-4648-b169-0c28cc6ebff5.gif)

**Comment by afc163** [comment]
https://github.com/ant-design/create-next-app-antd/commits/main 好像不是最新 commit。

**Comment by ideaviewes** [comment]
@afc163 
我又重新git clone https://github.com/ant-design/create-next-app-antd.git一份代码，
还是这样
![GIF 2023-3-31 18-36-07](https://user-images.githubusercontent.com/5431843/229098079-ad72a529-09e3-407f-b625-103781890299.gif)

**Comment by ideaviewes** [comment]
@afc163 @kiner-tang 
tyarn dev的确实不闪烁了
但是
tyarn run build
tyarn start的时候闪烁，您那边可以试一下

**Comment by kiner-tang** [comment]
@ideaviewes 看看这个是否能够满足你的需求：
- https://github.com/ant-design/create-next-app-antd/pull/6

**Comment by ideaviewes** [comment]
有没有办法像是tailwindcss那样，直接把css抽取出来，或者是直接输出在页面上也行
我看这个demo，处理后，生成了一个接近1M的css文件，antd.min.css
感觉这样成本太大了

**Comment by kiner-tang** [comment]
> @kiner-tang ,谢谢 有没有办法像是tailwindcss那样，直接把css抽取出来，或者是直接输出在页面上也行 我看这个demo，处理后，生成了一个接近1M的css文件，antd.min.css 感觉这样成本太大了

我们目前正在讨论根据首屏页面使用到的 antd 组件按需抽取 css 样式，支持后，每个页面只会导入当前页面首屏渲染所需的 css，其他非首屏 css 则在运行时动态注入。

**Comment by ideaviewes** [comment]
@kiner-tang ,嗯嗯，好的，超棒

**Comment by atom-shanghai** [comment]
> > @kiner-tang ,谢谢 有没有办法像是tailwindcss那样，直接把css抽取出来，或者是直接输出在页面上也行 我看这个demo，处理后，生成了一个接近1M的css文件，antd.min.css 感觉这样成本太大了
> 
> 我们目前正在讨论根据首屏页面使用到的 antd 组件按需抽取 css 样式，支持后，每个页面只会导入当前页面首屏渲染所需的 css，其他非首屏 css 则在运行时动态注入。
非常需要这个，目前样式闪烁非常不友好

**Comment by kiner-tang** [comment]
@atom-shanghai @ideaviewes 
可以先看看这个方案。使用这个方案，ssr 生成的样式将根据当前页面首屏渲染使用的 antd 组件的按需抽取样式
- https://github.com/ant-design/create-next-app-antd/pull/6/files

**Comment by ideaviewes** [comment]
@kiner-tang ,这样可以，马上就要解决我的问题了，还有一点问题
我使用了tailwindcss，antd抽取出来的css有一部分会冲突掉tailwindcss的样式，
我看了下页面上的情况，tailwindcss生成的css文件在antd生成的style标签之前引用，所以被覆盖了一些样式
这个应该不是antd的问题，您那边可以给我提供一些思路如何解决吗？
实现的代码是这样的
```
import type { DocumentContext, DocumentInitialProps } from 'next/document'
import Document, { Html, Head, Main, NextScript } from 'next/document'
import { createCache, extractStyle, StyleProvider } from '@ant-design/cssinjs'

class MyDocument extends Document {
    static async getInitialProps(
        ctx: DocumentContext
    ): Promise<DocumentInitialProps> {
        const cache = createCache()
        const originalRenderPage = ctx.renderPage

        ctx.renderPage = () =>
            originalRenderPage({
                enhanceApp: (App) => (props) =>
                    (
                        <StyleProvider cache={cache}>
                            <App {...props} />
                        </StyleProvider>
                    ),
            })

        const initialProps = await Document.getInitialProps(ctx)
        return {
            ...initialProps,
            styles: (
                <>
                    {initialProps.styles}
                    {/* hacky code, `extractStyle` does not currently support returning JSX or related data. */}
                    <script
                        dangerouslySetInnerHTML={{
                            __html: `</script>${extractStyle(cache)}<script>`,
                        }}
                    />
                </>
            ),
        }
    }
    render() {
        return (
            <Html>
                <Head />
                <body>
                <Main />
                <NextScript />
                </body>
            </Html>
        )
    }
}

export default MyDocument

```

**Comment by MadCcc** [comment]
@ideaviewes 是的这是我们一开始推荐的做法，这样会导致 html 文件太大，所以我们又推出了静态导出的方案。

**Comment by hemengke1997** [comment]
> @ideaviewes 是的这是我们一开始推荐的做法，这样会导致 html 文件太大，所以我们又推出了静态导出的方案。

静态导出也会导致样式闪烁吧？ 我理解的是 只有把当前渲染页面的样式内联到html中才能避免这个问题

**Comment by ideaviewes** [comment]
> > @ideaviewes 是的这是我们一开始推荐的做法，这样会导致 html 文件太大，所以我们又推出了静态导出的方案。
> 
> 静态导出也会导致样式闪烁吧？ 我理解的是 只有把当前渲染页面的样式内联到html中才能避免这个问题

导致闪烁的原因为那个css是用js加上去的

**Comment by hemengke1997** [comment]
> 导致闪烁的原因为那个css是用js加上去的

css外链是在客户端加载，跟js加载一样的道理呀，也会样式闪烁吧？（比如网络不好，css加载很慢）

**Comment by hemengke1997** [comment]
> styles: (
>                 <>
>                     {initialProps.styles}
>                     {/* hacky code, `extractStyle` does not currently support returning JSX or related data. */}
>                     <script
>                         dangerouslySetInnerHTML={{
>                             __html: `</script>${extractStyle(cache)}<script>`,
>                         }}
>                     />
>                 </>
>             )

如果使用这个方案，那 next13.2 和 react18 的 RSC 功能就没生效呀？最外层是客户端组件了

**Comment by ideaviewes** [comment]
@hemengke1997 ，不会，你可以尝试一下

**Comment by hemengke1997** [comment]
> @hemengke1997 ，不会，你可以尝试一下

对对对，link会阻塞渲染，所以不会出现样式闪烁

**Comment by ideaviewes** [comment]
所以有什么比较完美的方案吗，不会输入很大的css，然后又能跟tailwindcss结合的比较完美的

**Comment by ideaviewes** [comment]
https://github.com/ideaviewes/extractstyle.git
tyarn
tyarn dev
可以看到生成的css非常长，我保存了下，164k，我仅仅是使用了antd的Row Col Menu组件，这里感觉应该是有问题

**Comment by atom-shanghai** [comment]
这个有好的解决办法了吗？

**Comment by zombieJ** [comment]
> https://github.com/ideaviewes/extractstyle.git tyarn tyarn dev 可以看到生成的css非常长，我保存了下，164k，我仅仅是使用了antd的Row Col Menu组件，这里感觉应该是有问题

看了一下生成的样式，它们分别是 Col、Row、Menu 和 Tooltip 的样式。其中 Menu 有使用过 Tooltip，所以这些提取的样式是符合预期的。

业界现在的方案基本都是 inline html 导出，这个就会导致 ssr 出的 html 里带着样式全都无法被 cache 掉。所以我们给 antd 加了一个静态全量导出的能力，一次性烘焙好完整的 css 文件。好处是和原生的 css 加载一样，一次使用全部缓存。缺点就是需要提前烘焙一下，如果用了动态主题就要多烘焙一点。

ref: https://ant.design/docs/react/customize-theme-cn#%E6%95%B4%E4%BD%93%E5%AF%BC%E5%87%BA

**Comment by ideaviewes** [comment]
@zombieJ ,好的，谢谢

**Comment by bluefantasy728** [comment]
> @afc163 @kiner-tang tyarn dev的确实不闪烁了 但是 tyarn run build tyarn start的时候闪烁，您那边可以试一下 dev闪不闪都无所谓，start上线不能有这个问题吧

你好，我clone了他提供的demo： [https://github.com/ant-design/create-next-app-antd.git](https://github.com/ant-design/create-next-app-antd.git%E4%B8%80%E4%BB%BD%E4%BB%A3%E7%A0%81)，dev run的时候还是会闪烁一下，你之前是改了什么之后变好的吗？

**Comment by ideaviewes** [comment]
@bluefantasy728 ,https://github.com/ant-design/create-next-app-antd/pull/6/files,用这个方法可以解决

**Comment by Onurakdeniz** [comment]
Still I am facing the same css issue though.

**Comment by zombieJ** [comment]
> 这个方案没有更新到文档上面，是不是这个方法有缺陷而待定？

有的，这里：https://ant.design/docs/react/customize-theme-cn#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%87%BA-css-%E6%A0%B7%E5%BC%8F%E6%96%87%E4%BB%B6

**Comment by Veath** [comment]
![image](https://user-images.githubusercontent.com/15187953/235047601-1691c9e1-fc6f-467d-91b1-262fea09f1d1.png)
生成的css 文件 在script后面，这个是Nextjs的问题，但有解决办法建议吗

**Comment by yoyo837** [comment]
截图中这个前后没关系

**Comment by Veath** [comment]
> 截图中这个前后没关系

这个前后关系，导致tailwindcss 的优先级被覆盖

**Comment by yoyo837** [comment]
> 

js也是append css style, js本身没有样式优先级啊

**Comment by yunsii** [comment]
提取 css 通过 link 加载也会有闪烁问题，现在我的做法是直接提取 style，通过 dangerouslySetInnerHtml 添加到 head 中

**Comment by ideaviewes** [comment]
> 提取 css 通过 link 加载也会有闪烁问题，现在我的做法是直接提取 style，通过 dangerouslySetInnerHtml 添加到 head 中

我最后选择不使用antd来做C端的功能了，自己需要的组建简单封装一下，antd做管理后台确实无敌，C端的，我感觉不太适合。

**Comment by yunsii** [comment]
@ideaviewes 我们的原则也是这样，但是难免有些复杂的交互，手搓吃力不讨好

**Comment by ideaviewes** [comment]
> @ideaviewes 我们的原则也是这样，但是难免有些复杂的交互，手搓吃力不讨好

对，要看具体的业务来定用什么方案，我用antd的组件不多，两三个而已，后来问题越来越多，索性直接去掉了

**Comment by 3kinglee** [comment]
> ![image](https://user-images.githubusercontent.com/15187953/235047601-1691c9e1-fc6f-467d-91b1-262fea09f1d1.png) 生成的css 文件 在script后面，这个是Nextjs的问题，但有解决办法建议吗

试试不要注入，而是在HEAD里link，我是用这种方法解决的
<img width="768" alt="image" src="https://github.com/ant-design/ant-design/assets/14836590/6b12ea1d-4512-4294-be6c-3afc7c880578">

**Comment by Dimitri-WEI-Lingfeng** [comment]
> https://ant.design/docs/react/customize-theme-cn#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%87%BA-css-%E6%A0%B7%E5%BC%8F%E6%96%87%E4%BB%B6

请问大佬后来选择什么组件库了？

**Comment by zombieJ** [comment]
组件库选择和这个 issue 关联性不大，不过一般根据 8020 原则，大部分持续维护的组件库都能满足基本需求，剩余的一些业务相关需求则通过三方库做拓展，如果强相关则自行研发。
此外，关闭的 issue 不一定能够很好的追踪。大家如果有问题，欢迎开新的 issue 哈。

**Comment by abstain23** [comment]
通过内联解决了闪烁问题
![image](https://github.com/ant-design/ant-design/assets/51360233/a303bfb2-283a-4edb-8699-d30ec7ceb86b)

**Comment by DophinL** [comment]
@kiner-tang  请问有更好的方案吗？希望能封装在组件包里就能解决，而不影响到工程。我们业务场景有很多工程都用的next.js，如果都要接入还挺麻烦，而且不太优雅

好奇这个根本原因是什么，我发现style标签是在浏览器首屏渲染结束后才插入的，这个没有办法优化吗？

**Comment by yunsii** [comment]
因为我这里：

> 提取 css 通过 link 加载也会有闪烁问题，现在我的做法是直接提取 style，通过 dangerouslySetInnerHtml 添加到 head 中

具体怎么做可提供如下参考：

- 如果使用 `App Router`，请使用 [`useServerInsertedHTML`](https://nextjs.org/docs/app/building-your-application/styling/css-in-js#configuring-css-in-js-in-app) 插入样式，参考 https://github.com/ant-design/ant-design/issues/41573#issuecomment-1612516029 我还没用过 `App Router`
- 如果还是老式的 `Pages Router`, 那就在 `_document.js` 中注入的方式，演示如下（目前在用的方案）：

```ts
import Document, { Head, Html, Main, NextScript } from 'next/document'
import { StyleProvider, createCache, extractStyle } from '@ant-design/cssinjs'

import type { DocumentContext } from 'next/document'

export default class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const cache = createCache()
    const originalRenderPage = ctx.renderPage
    ctx.renderPage = () =>
      originalRenderPage({
        enhanceApp: (App) => (props) =>
          (
            <StyleProvider cache={cache}>
              <App {...props} />
            </StyleProvider>
          ),
      })

    const initialProps = await Document.getInitialProps(ctx)
    const styles = extractStyle(cache)

    return {
      ...initialProps,
      styles: (
        <>
          {initialProps.styles}
          {styles && <style dangerouslySetInnerHTML={{ __html: styles }} />}
        </>
      ),
    }
  }

  render() {
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```

**Comment by wujiantao123** [comment]
@kiner-tang https://github.com/ant-design/create-next-app-antd.git demo在next 13.4.7 正常运行，14后失效

**Comment by yoyo837** [comment]
nextjs 14 的问题移步 https://github.com/ant-design/ant-design/issues/45567 讨论.

**Comment by ondery** [comment]
### Nextjs v13.5.5 & Antd v5.10.3 - Chrome console
look inside the tag <style id="antd">
<img width="1031" alt="image" src="https://github.com/ant-design/ant-design/assets/7957487/485a73c3-a41c-4d67-b996-3a384d79fb3a">

vs

### Nextjs v14.0.0 & Antd v5.10.3 - Chrome console
look inside the tag <style id="antd">
<img width="1052" alt="image" src="https://github.com/ant-design/ant-design/assets/7957487/c5be9d23-67f9-4589-9227-8c2e0c094c3a">

**Comment by hqwlkj** [comment]
可以参考这个例子  [next-antd](https://github.com/hqwlkj/next-antd)

**Comment by Vsion** [comment]
有人遇到过这个问题吗 https://github.com/ant-design/antd-style/issues/136
