### ISSUE TITLE
RangePicker when value is [null, null] and disabled is [false, true], will trigger Maximum update depth exceeded issue

### ISSUE THREAD

**Issue by xjhjzxh** [ant-design/ant-design#41579]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jin-yong-antd-4-24-8-forked-n6b2l9?file=/demo.tsx)

### Steps to reproduce

open codesandbox link, look at console log

### What is expected?

fix issue

### What is actually happening?

Maximum update depth exceeded issue trigged

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | Chrome 108 |

**Comment by BoyYangzai** [comment]
看了下报错，我觉得应该是你这里disabled用的数组，但是value却没有使用正确的dayjs[]格式，而是使用了react响应式变量导致的，或许可以再查看下文档中的正确参数类型

**Comment by xjhjzxh** [comment]
> 

我看了文档Demo, https://codesandbox.io/s/71et1z?file=/demo.tsx
我声明的类型和文档类型应该没有差异, 我用的4.24.8版本, 使用的是moment|null类型

**Comment by Yuiai01** [comment]
> > 
> 
> 我看了文档Demo, https://codesandbox.io/s/71et1z?file=/demo.tsx 我声明的类型和文档类型应该没有差异, 我用的4.24.8版本, 使用的是moment|null类型

这应该是 rc-picker 的问题，在 3.5.0 中，这个问题已经被修复掉了～  https://github.com/react-component/picker/pull/594

**Comment by yoyo837** [comment]
2.7.x给修复一下?

**Comment by Yuiai01** [comment]
> 2.7.x给修复一下?

这咋整😂

**Comment by yoyo837** [comment]
给rc-picker的2.7.x发PR就可以

**Comment by Yuiai01** [comment]
> 给rc-picker的2.7.x发PR就可以

好，我待会整一下

**Comment by yoyo837** [comment]
Close by https://github.com/react-component/picker/pull/622

**Comment by winddies** [comment]
@yoyo837 @Yuiai01 我这边升级后仍然有这个问题呀

**Comment by winddies** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/25814552/236428948-3cca544d-b200-4935-a9d2-5b497a6a5e16.png">
![image](https://user-images.githubusercontent.com/25814552/236429017-75ad4fb3-6fe8-45bf-9a49-742482754d4b.png)
@yoyo837 @Yuiai01 我这里 antd 用的 4.24.10，我是用的 @ant-design/pro-components 里的 ProFormDateRangePicker

**Comment by winddies** [comment]
![image](https://user-images.githubusercontent.com/25814552/236429352-1099d581-9129-4ad6-82f3-d591b72c0d76.png)

**Comment by fstn** [comment]
Same issue here

**Comment by Yuiai01** [comment]
在4.24.10中用同样的代码貌似是好的啊，https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-4-24-10-forked-lv88m1

**Comment by sky170201** [comment]
4.18.3的版本里有这个问题，4.24.12是正常的

**Comment by yoyo837** [comment]
升上去吧, 4.18.x不会再发patch版本了.
