### ISSUE TITLE
antd version ^5.3.3 or any 5 version Carousel、 Select、Dropdown在移动端谷歌浏览器上无法正常显示

### ISSUE THREAD

**Issue by caoqizihi** [ant-design/ant-design#41571]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-elhgmi?file=/index.js)

### Steps to reproduce

在pc端打开是正常的，使用移动端Chrome浏览器打开时Carousel 、Select 、Dropdown样式效果不对，且Carousel无法正常显示。
使用手机自带的浏览器没有问题。

### What is expected?

移动端谷歌浏览器上正常显示Carousel 、Select 、Dropdown

### What is actually happening?

移动端谷歌浏览器上错误显示Carousel 、Select 、Dropdown

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | Android 12 |
| Browser | Chrome 78.0.3904.96 |

---
当我把antd版本降低至4.2时，问题解决了。

**Comment by zombieJ** [comment]
`Chrome 78` 不支持 `:where` selector，参考兼容性教程做个降级哈：
https://ant.design/docs/react/compatible-style-cn

**Comment by caoqizihi** [comment]
好的，非常谢谢
