### ISSUE TITLE
Form.Item hasFeedback shows success instead of error

### ISSUE THREAD

**Issue by getvega** [ant-design/ant-design#41577]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-3-3-forked-0zvdh4)

### Steps to reproduce

- Click on the submit button

### What is expected?

- form item feedback should be error

### What is actually happening?

- form item feedback show success (even if the validation error is shown correctly underneath the form)
![image](https://user-images.githubusercontent.com/246213/229090498-cb0b860d-d75e-4838-80d6-56ab9361771b.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | MacOS 12.3.1 |
| Browser | Chromium 109 |

---
Code forked from the docs' [first example](https://ant.design/components/form#examples)

**Comment by Yuiai01** [comment]
The status seems to be normal, but the icon is displayed incorrectly. Let me fix it～

**Comment by Yuiai01** [comment]
@getvega Hello, `hasFeedback` needs to be used with `validateStatus`, like this:  https://codesandbox.io/s/basic-usage-antd-5-3-3-forked-hc8fim?file=/demo.tsx

**Comment by getvega** [comment]
Thanks for your help 🙏 .

From the docs:
> `validateStatus` The validation status. If not provided, it will be generated by validation rule. options: success warning error validating

So it means that validation status is optional and computed from the validation rules execution right? Regardless of `hasFeedback` property?

**Comment by duypham90** [comment]
I got the same problem.
The errors can set manual from API response. There for it should be changed as @getvega said.

**Comment by Yuiai01** [comment]
Ok, so the logic can really be optimized here, so let me try it. @getvega @duypham90

**Comment by Yuiai01** [comment]
I found that the state I got was wrong when setting the icon corresponding to feedback, which is a bug. I will fix it.
