### ISSUE TITLE
Using <Dropdown> results in "findDOMNode is deprecated in StrictMode" warning 

### ISSUE THREAD

**Issue by amberyufangchiu** [ant-design/ant-design#41570]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z4obo4)

### Steps to reproduce

I use <Dropdown/> component from antd version 5.3.2, but when i hover it shows warming.

```react_devtools_backend.js:2655 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:```

### What is expected?

It shouldn't show the warming
so far I had searched a solution is remove <React.StrictMode>
but I think that's a bad practice.

Is anything else I can do to fix it?

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | macOS |
| Browser | Chrome |

**Comment by yoyo837** [comment]
Can not see the warning in your reproduction.

**Comment by amberyufangchiu** [comment]
@

> Can not see the warning in your reproduction

> Hello @amberyufangchiu. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @amberyufangchiu, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)


Hello! I have been reproduce in codesandbox. 
https://codesandbox.io/s/antd-reproduction-template-forked-z4obo4?file=/index.js

**Comment by nhatncb** [comment]
This is easily found if you use antd pro layout in strict mode. There is another warning when using in mobile screen

**Comment by amberyufangchiu** [comment]
> This is easily found if you use antd pro layout in strict mode. There is another warning when using in mobile screen

but how can I solve this? and Im not using antd pro

**Comment by zombieJ** [comment]
Let me check this.

**Comment by zombieJ** [comment]
fixed with `rc-menu@9.8.4`:
https://codesandbox.io/s/antd-reproduction-template-forked-j0t46c?file=/package.json

**Comment by camsong** [comment]
Got stuck by this 'Warning: findDOMNode is deprecated in StrictMode in ' for a while, finally I got an answer.

if you still encounter this in your owner component, you'd better add forwardRef and restProps to your component, here is an example:

export const MyIcon = forwardRef(function MyIconInner(
  { icon, className, ...restProps }: { icon: string; className: string },
  ref: React.Ref<HTMLDivElement>,
) {
  return <div className={className} {...restProps} ref={ref}  />{icon}</div>
})

**Comment by zzswang** [comment]
> fixed with `rc-menu@9.8.4`: https://codesandbox.io/s/antd-reproduction-template-forked-j0t46c?file=/package.json

Not work for me

**Comment by yoyo837** [comment]
> >

Can you provide a new reproduction link and open a new issue for that?

**Comment by zzswang** [comment]
> > >
> 
> Can you provide a new reproduction link and open a new issue for that?

I'll keep an eye on this issue later.

Currently, I just use Popover instead of Dropdown to avoid such case.

Thanks, appreciating for this great lib.
