### ISSUE TITLE
在antd form中使用自定义的antd select组件，如果select设置为mode="multiple"就会有memory leak的warning

### ISSUE THREAD

**Issue by buslightyear** [ant-design/ant-design#41572]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z9hznz?file=/index.js)

### Steps to reproduce

点击按钮，打开对话框，浏览器控制台报错：react_devtools_backend.js:4026 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### What is expected?

不报错

### What is actually happening?

react_devtools_backend.js:4026 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 17.0.2 |
| System | win11 |
| Browser | chrome 111.0.5563.147（正式版本） （64 位） |

**Comment by zombieJ** [comment]
React 18 里已经不认为这是需要注意的了：

> ### Notable Changes
> * No warning about setState on unmounted components: Previously, React warned about memory leaks when you call setState on an unmounted component. This warning was added for subscriptions, but people primarily run into it in scenarios where setting state is fine, and workarounds make the code worse. We've [remove](https://github.com/facebook/react/pull/22114) this warning.

在之前版本，React 在卸载的组件里调用 `useState` 会提示 mem leaks。但是大多数情况下，这种设置状态的代码都是没问题的，但是为了解决这个 warning 反而会使代码变得糟糕。我们移除了这个 warning。

ref: https://github.com/facebook/react/blob/main/CHANGELOG.md#react-2

**Comment by josephxin** [comment]
意思是这个警告不处理不会影响程序运行呗。

**Comment by HyaCiovo** [comment]
老哥你解决这个问题了吗？我也遇到了这个报错，不好去升react版本，这个报错在控制台还很长一串🫥

**Comment by dh336699** [comment]
Select组件，本身没问题，当mode为multiple时就有这个问题，所以是直接把问题甩锅给React版本问题了吗？
这也算是解决方案？？？@zombieJ @zombieJ
