### ISSUE TITLE
Tabs 组件支持动态更新 items 中的 label 组件

### ISSUE THREAD

**Issue by zfben** [ant-design/ant-design#41581]
### What problem does this feature solve?

例子：当 tabs 的 label 中包含了一些统计数字，操作 tabpane 后需要实时更新 label 中的统计数字。

当前 key 不变化时，label 不会刷新，但如果更新 key，会导致 tabpane 被整体重新渲染。

### What does the proposed API look like?

没想好

**Comment by zongyanglaobiao** [comment]
> ### What problem does this feature solve?
> 例子：当 tabs 的 label 中包含了一些统计数字，操作 tabpane 后需要实时更新 label 中的统计数字。
> 
> 当前 key 不变化时，label 不会刷新，但如果更新 key，会导致 tabpane 被整体重新渲染。
> 
> ### What does the proposed API look like?
> 没想好

你好我也遇到了同样的问题其中items的数据改变了但是Tabs组件并没有重新渲染，请问官方最后解决了吗
