### ISSUE TITLE
DatePicker点击input框中的日历小图标会触发onBlur事件

### ISSUE THREAD

**Issue by surongm** [ant-design/ant-design#41608]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

想要使用DatePicker日期选择框中的onBlur事件，即失去焦点后执行某个处理方法。
现在点击input框后面的日历小图标执行的方法如下
（先选择一个日期，然后再点击一次这个小图标就会触发）
onFocus
onBlur
onFocus
onClick
![1680501400101](https://user-images.githubusercontent.com/41141486/229426360-95f04662-b18d-4627-9adb-32424be0b00b.jpg)

为什么会触发onBlur事件，这个时候的焦点其实一直都在input框里面。
而且第一次选择日期的时候不会触发，input框有值再点击小图标的时候就会触发onBlur事件
代码如下：

```
    const onFocus = () => {
        console.log('onFocus');
    }

    const onBlur = () => {
        console.log('onBlur');
    }

    const onClick = () => {
        console.log('onClick');
    }

  <DatePicker format={'YYYY-MM-DD'} onFocus={onFocus} onBlur={onBlur} onClick={onClick} allowClear={false} style={{ width: '200px' }} />
```

### What is expected?

点击日期选择框（包括input框的日历小图标）不会触发onBlur事件，点击其他地方真正失去焦点的时候再触发

### What is actually happening?

点击input框的日历小图标会触发onBlur事件，这个时候其实一直都在操作日期的input框

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React |  "react": "^16.8.6", |
| System | window10 |
| Browser | 谷歌浏览器 |

---
或者有什么方法可以在onBlur事件的时候知道是点击input框的小图标触发的（好像不太科学）

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-antd-4-24-8-forked-3hj4g6?file=/demo.tsx

升级到 4.24.8 试试？

**Comment by surongm** [comment]
> https://codesandbox.io/s/ji-ben-antd-4-24-8-forked-3hj4g6?file=/demo.tsx
> 
> 升级到 4.24.8 试试？

不行的，就是上面这个例子 https://codesandbox.io/s/ji-ben-antd-4-24-8-forked-3hj4g6?file=/demo.tsx
先选中一个日期，再点击input框的日历小图标，就会触发onBlur

**Comment by surongm** [comment]
![image](https://user-images.githubusercontent.com/41141486/229697411-d5a28922-8d20-418f-b563-b1e37707d61e.png)

**Comment by afc163** [comment]
<img width="175" alt="图片" src="https://user-images.githubusercontent.com/507615/229707536-7f227aeb-5e9b-407f-abec-4242f87e67a7.png">

选中日期后，光标还在输入框内时，此时点击黄色区域（和日期图标本身没关系）都会触发 onBlur。不太合理，确实要看一下。

**Comment by surongm** [comment]
你好，看到了提交记录，请问我这边要怎么测试这个bug，是升级antd版本么

**Comment by yoyo837** [comment]
尚未修复

**Comment by surongm** [comment]
你好，修复的时候可以告知一下不~我现在使用的是antd 4.21.0

**Comment by yoyo837** [comment]
> 你好，修复的时候可以告知一下不~我现在使用的是antd 4.21.0

看上面, 已经处理了, 升到4.24.2+, npm ls rc-picker 版本2.7.1+

**Comment by surongm** [comment]
> > 你好，修复的时候可以告知一下不~我现在使用的是antd 4.21.0
> 
> 看上面, 已经处理了, 升到4.24.2+, npm ls rc-picker 版本2.7.1+

已经可以了，非常感谢！
