### ISSUE TITLE
销毁内部Select后，隐藏气泡弹出框错误

### ISSUE THREAD

**Issue by DDBSB** [ant-design/ant-design#41612]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9wwtb3?file=/index.js)

### Steps to reproduce

点击筛选，展开气泡弹出框，点击增加，选择任意Option，然后点击重置，再点击外部蒙层隐藏气泡弹出框，控制台TypeError。

### What is expected?

销毁内部Select，能够正常隐藏外层气泡弹出框

### What is actually happening?

销毁内部Select，TypeError

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.x |
| System | windows 10 21H2 |
| Browser | Google Chrome 111.0.5563.147 |

**Comment by zombieJ** [comment]
发现已经有了，没发 patch，我补一下：
https://github.com/react-component/trigger/pull/348
