### ISSUE TITLE
当Columns中的fixed元素有多个时，Table.Summary会对不齐

### ISSUE THREAD

**Issue by RenShine** [ant-design/ant-design#41610]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-yp6dje?file=/index.js)

### Steps to reproduce

Columns中设定多个靠右的Fixed列，该bug即可复现，当只有一个fixed列时正常

### What is expected?

Table.Summary正常对齐

### What is actually happening?

只有第一个fixed的列被对齐了

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.X |
| System | Mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-izbm3i
index 是 column 起始点，合并列要记得算上偏移量。
