### ISSUE TITLE
希望Upload组件的ListItem可以缓存图片

### ISSUE THREAD

**Issue by lankerened** [ant-design/ant-design#41611]
### What problem does this feature solve?

在修改表单的情况下，ListItem的缩略图已经请求一次，使用文档示例中的预览功能又要发起一次请求，希望在 antd 的 Upload 组件中增加一个配置项 cacheThumbUrl，用于控制是否缓存 thumbUrl。当配置为 true 时，thumbUrl 将被缓存，并在下一次渲染时直接使用缓存，避免重复请求。

### What does the proposed API look like?

```javascript
<Upload
  cacheThumbUrl={true}
  // 其他配置项
>
  // 其他 JSX
</Upload>
```

**Comment by afc163** [comment]
> 在修改表单的情况下，ListItem的缩略图已经请求一次，使用文档示例中的预览功能又要发起一次请求

来个重现。

**Comment by lankerened** [comment]
测试发现是 thumbUr l和 url 同时设置才会请求两次，只设置 url 就只请求一次
