### ISSUE TITLE
FormItem required 为 undefined 时会使 必选样式 丢失

### ISSUE THREAD

**Issue by liixing** [ant-design/ant-design#41621]
### Reproduction link

[https://stackblitz.com/edit/react-ts-kxpvis?file=App.tsx](https://stackblitz.com/edit/react-ts-kxpvis?file=App.tsx)

### Steps to reproduce

FormItem required 为 undefined 时会使 必选样式 丢失

### What is expected?

rules 里面有 required 后，required 传 undefined 时不会影响必选样式

### What is actually happening?

FormItem required 为 undefined 时会使 rules 里的必选样式丢失

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.1.0 |
| System | macos Ventura version 13.2.1 |
| Browser | chrome Version 111.0.5563.146 (Official Build) (x86_64) |

**Comment by Wxh16144** [comment]
应该是漏掉了某些 props 导致的内部判断有些问题。你可以先这样使用。

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/32004925/229686585-6fb4000e-b993-44a3-bf6e-feab9d5f7dee.png">

```tsx
interface MyFormInputProps extends FormItemProps {
  inputProps: InputProps;
}

function MyFormInput(props: MyFormInputProps) {
  const { inputProps, ...formProps } = props;
  return (
    <Form.Item {...formProps}>
      <Input {...inputProps} />
    </Form.Item>
  );
}
```

**Comment by liixing** [comment]
@Wxh16144   不是漏传，是 required 传了 undefined 后就会变成可选

**Comment by Yuiai01** [comment]
@liixing 是指 required 的样式丢失了吗？

**Comment by liixing** [comment]
@Yuiai01  是的

**Comment by Wxh16144** [comment]
> 不是漏传，是 required 传了 undefined 后就会变成可选


感谢你的指出，根据你提供的 demo， 我找到了问题。参数透传下去有些默认的值会被覆盖。这里还需要处理一下 `formItemProps`，如下所示

```tsx
 Object.keys(formItemProps).forEach((propName) => {
    if (typeof formItemProps[propName] === 'undefined') {
      delete formItemProps[propName];
    }
  });
```

**Comment by Yuiai01** [comment]
> > 不是漏传，是 required 传了 undefined 后就会变成可选
> 
> 感谢你的指出，根据你提供的 demo， 我找到了问题。参数透传下去有些默认的值会被覆盖。这里还需要处理一下 `formItemProps`，如下所示
> 
> ```tsx
>  Object.keys(formItemProps).forEach((propName) => {
>     if (typeof formItemProps[propName] === 'undefined') {
>       delete formItemProps[propName];
>     }
>   });
> ```

应该是这里被覆盖了
<img width="571" alt="image" src="https://user-images.githubusercontent.com/112228030/229692544-bde4104c-a1a6-4f36-8b23-75efd2639533.png">

**Comment by zombieJ** [comment]
嗯，见上。这相当于自己覆盖了一个 `required`。

**Comment by liixing** [comment]
@zombieJ  这感觉不妥吧， isRequred 判断了 required 为 undefined 情况但是下面却被覆盖了，感觉这应该 merge 一下

**Comment by Wxh16144** [comment]
> 感觉不妥吧， isRequred 判断了 required 为 undefined 情况但是下面却被覆盖了，感觉这应该 merge 一下

我和你看法一致，我这边已经在做了，带会儿提交 PR 看看用例通过情况。
