### ISSUE TITLE
problems with upgrade to antd 5 (less configuration)

### ISSUE THREAD

**Issue by daryazata** [ant-design/ant-design#41634]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

(sorry I dont have a link to reproduce, its not an open source repo)

 Im following the upgrade guide of antd5 and have a problem with the point on [less migration](https://ant.design/docs/react/migration-v5#less-migration). I copied the config code from the guide to my webpack config, then installted atn-design https://github.com/ant-design/ant-design/issues/20833. I get an error that "options" is not a valid property in webpack. 

![Screenshot (110)](https://user-images.githubusercontent.com/44365122/229755593-e3f194d1-293e-4a2f-955b-c24e33609b86.png)

### What is expected?

expected that there are no errors with suggested code from the upgrade guide

### What is actually happening?

webpack throws an error 

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | chrome |

---
would be great if you provide code that is valid, so that webpack doesnt throw errors

**Comment by zombieJ** [comment]
Thanks for feedback. But we can help nothing if reproduce can not provided. You can try to remove main logic of your app to simplify the app only for the error tracing instead.

**Comment by daryazata** [comment]
@zombieJ well in this case i think the error description is quite clear. Its not about the project code, but a webpack config..
