### ISSUE TITLE
时间范围组件可以支持类似22:00-06:00形式的范围嘛

### ISSUE THREAD

**Issue by Merely-chao** [ant-design/ant-design#41632]
### What problem does this feature solve?

比如填写睡眠时间段:22:00-06:00,这样选取后会自动变成06:00-22:00

### What does the proposed API look like?

是不是默认就不需要自动转换位置了

**Comment by Wxh16144** [comment]
看了一下文档 [TimePicker.RangePicker](https://ant.design/components/time-picker-cn#rangepicker) 允许设置 `order=false` 来禁止时间自动排序功能

```tsx
import React from "react";
import { TimePicker } from "antd";

const App: React.FC = () => (
  <TimePicker.RangePicker 
    order={false} 
    onChange={console.log}
  />
);

export default App;
```
