### ISSUE TITLE
Form enter search with Checkbox and Selexbox

### ISSUE THREAD

**Issue by edrmsgl** [ant-design/ant-design#41637]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-vdlbr8?file=/src/App.js:0-1131)

### Steps to reproduce

Do you search form elements with the "enter" key? When I check the checkbox or after selecting the selectbox, I want to search with the enter key on the keyboard, but when I press the enter key, the selectbox opens again and I cannot search. Can you give me a hint on how to do this?

### What is expected?

awaiting solution

### What is actually happening?

Unable to search

| Environment | Info |
| --- | --- |
| antd | 4.21.1 |
| React | 18.0.0 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by afc163** [comment]
You could press <kbd>Tab</kbd> to focus `Submit` button, then press <kbd>Enter</kbd> to trigger form submit.
