### ISSUE TITLE
黑暗主题下输入框、按钮出现黑色阴影

### ISSUE THREAD

**Issue by ldd27** [ant-design/ant-design#41638]
### Reproduction link

[https://ant.design/components/button-cn?theme=dark](https://ant.design/components/button-cn?theme=dark)

### Steps to reproduce

<img width="728" alt="image" src="https://user-images.githubusercontent.com/11850305/229810655-f239c491-3ac0-4dee-a51b-b2c0c511ec88.png">
<img width="488" alt="image" src="https://user-images.githubusercontent.com/11850305/229811293-ad2321e9-9917-4187-b85e-4b324abf92c2.png">

### What is expected?

无黑色阴影显示

### What is actually happening?

有黑色阴影显示

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by MuxinFeng** [comment]
感觉是预期行为吧

**Comment by ldd27** [comment]
这个阴影看着有点不协调呢

**Comment by MadCcc** [comment]
预期行为，如果不需要的话可以修改 `controlOutline` 这个 token
