### ISSUE TITLE
small button 缺少 fontSizeSM 的 Token 设定

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#41640]
### What problem does this feature solve?

能够配置小型按钮的字号

https://github.com/ant-design/ant-design/blob/master/components/button/style/index.ts#L463

### What does the proposed API look like?

能否加上 fontSizeSM Token？

```tsx
export default function App() {
  return (
    <ConfigProvider
      theme={{
        components: {
          Button: {
            fontSizeSM: 16, // 目前没有设定该 Token
            borderRadiusSM: 21,
            controlHeightSM: 42,

            fontSize: 20,
            borderRadius: 23,
            controlHeight: 46,

            fontSizeLG: 22,
            borderRadiusLG: 24,
            controlHeightLG: 48,
          },
        },
      }}
    >
    </ConfigProvider>
  )
}

```

**Comment by zhenzhenChange** [comment]
因为默认按钮（`middle`）和大型按钮（`large`）都设定了`fontSize`，所以小型按钮（`small`）也应该要可以设定才行吧。

**Comment by MuxinFeng** [comment]
这里需要吗，我可以提个 pr~

**Comment by MadCcc** [comment]
小尺寸按钮目前用的也是 fontSize，直接改也是可以生效的。暂时没有相关 component token 支持。

**Comment by MadCcc** [comment]
Trace in https://github.com/ant-design/ant-design/issues/38975

**Comment by arvinxx** [comment]
> 小尺寸按钮目前用的也是 fontSize，直接改也是可以生效的。暂时没有相关 component token 支持。

但这样的话默认尺寸的按钮字号也会被改。其实我之前是觉得小号的按钮字号应该小一号的…

**Comment by zombieJ** [comment]
这个其实是跟着设计规范走的，如果确实有这个需求。可以跟一下：https://github.com/ant-design/ant-design/discussions/39862

**Comment by zhenzhenChange** [comment]
而且设定其实也不影响吧，可以兜个底：

```ts
const fontSize = fontSizeSM ?? fontSize
```

**Comment by arvinxx** [comment]
> 但其实有点心智负担：这个组件不支持这个Token，但是类型fontSizeSM又存在。

@zombieJ @MadCcc 这个的确是个很大的问题。能把类型明确收敛一下么？把组件里用到 token 的准确地显示在类型定义里。这样开发者也能比较清楚地知道可以用哪些 token。

**Comment by MadCcc** [comment]
5.9.0 已支持
https://ant.design/components/button-cn#%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8Fdesign-token
