### ISSUE TITLE
DatePicker 国际化问题

### ISSUE THREAD

**Issue by weishaodaren** [ant-design/ant-design#41649]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ri94lb?file=/index.js)

### Steps to reproduce

```Js
...
import locale from "antd/es/locale/zh_CN";
import zhCN from "antd/es/date-picker/locale/zh_CN";
import moment from "moment";
import "moment/dist/locale/zh-cn";
moment.locale("zh-cn");

// 执行结果
moment.months()
[
    "一月",
    "二月",
    "三月",
    "四月",
    "五月",
    "六月",
    "七月",
    "八月",
    "九月",
    "十月",
    "十一月",
    "十二月"
]
```

### moment 依赖
`pnpm ls moment --depth=3`
```json
antd 4.18.0
├── moment 2.29.4
└─┬ rc-picker 2.5.19
  └── moment 2.29.4
moment 2.29.4
```

### What is expected?

展示全中文

### What is actually happening?

一半中文一半英文

| Environment | Info |
| --- | --- |
| antd | 4.18.0  |
| React | 16.13.1 |
| System | macOS V13.2.1 |
| Browser | Chrome V111.0.5563.146 |

---
pnpm v8.10
vite v3.0.0

react v16.13.1
antd v4.18.0
moment v2.29.4

**Comment by afc163** [comment]
See https://codesandbox.io/s/antd-reproduction-template-forked-nwqsky?file=/index.js

**Comment by weishaodaren** [comment]
> See https://codesandbox.io/s/antd-reproduction-template-forked-nwqsky?file=/index.js

我不是锁定了antd的版本号了吗..... 项目中暂时只使用4.18.0
