### ISSUE TITLE
Select.Option 组件内无法正常使用 input

### ISSUE THREAD

**Issue by aoue-hyg** [ant-design/ant-design#41648]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-5-4-0-forked-ibvd0i?file=/demo.tsx)

### Steps to reproduce

在 Select.Option 内使用 input 组件,  无法聚焦编辑 input.

### What is expected?

input 正常编辑 

### What is actually happening?

input 无法通过 click 聚焦,  只能通过 `inputElement.focus()` 聚焦

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18 |
| System | windows wsl2  |
| Browser | chrome  111 |

**Comment by Yuiai01** [comment]
试试这个，https://codesandbox.io/s/antd-5-4-0-forked-w6xytx?file=/demo.tsx

**Comment by zombieJ** [comment]
> 试试这个，https://codesandbox.io/s/antd-5-4-0-forked-w6xytx?file=/demo.tsx

嗯，`onMouseDown` 阻止冒泡即可。
