### ISSUE TITLE
Badge.Ribbon text line breaks do not works correctly

### ISSUE THREAD

**Issue by GisCat** [ant-design/ant-design#41653]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-badge-ribbon-kqbkfs?file=/index.js)

### Steps to reproduce

* In text attribute of Badge.Ribbon
* I wrote Line 1 
* I wrote <br/> to line break
* I wrote Line 2 

### What is expected?

The Ribbon must cover Line 1 and Line 2 

### What is actually happening?

The Ribbon cover only the Line 1

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Microsoft Edge |

---
I guess the design is not responsive to line breaks ?

**Comment by MuxinFeng** [comment]
A fixed height is set here, is this the expected behavior
https://github.com/ant-design/ant-design/blob/master/components/badge/style/index.ts#L287

**Comment by MuxinFeng** [comment]
![image](https://user-images.githubusercontent.com/46584765/230043561-6a5e1d8a-d4f9-4e2c-9c2a-27ca52efe1cd.png)

**Comment by GisCat** [comment]
Thank you !
I liked a lot the component Ribbon are you planing to add features or ability to customise it ?

**Comment by MuxinFeng** [comment]
If necessary, I can create a PR.

**Comment by MuxinFeng** [comment]
@zombieJ Please see if it is necessary

**Comment by zombieJ** [comment]
> @zombieJ Please see if it is necessary

Pls feel free to contribute on this : )

**Comment by yoyo837** [comment]
@MuxinFeng 你已在钉钉群, 这个机器人信息太多看不过来, 有事你到群里圈他.
