### ISSUE TITLE
文档函数调用书写错误

### ISSUE THREAD

**Issue by yizhimo** [ant-design/ant-design#41659]
### Reproduction link

[https://ant.design/components/message-cn](https://ant.design/components/message-cn)

### Steps to reproduce

Message文档中，「加载中」例子里，关闭Message写的是messageApi.destroy，实际上应该是message.destroy

### What is expected?

messageApi.destroy -> message.destroy

### What is actually happening?

messageApi.destroy -> messageApi.destroy

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | @16.9 |
| System | macOS |
| Browser | 谷歌 |

**Comment by kiner-tang** [comment]
我看看

**Comment by yoyo837** [comment]
没看出啥问题 `onst [messageApi, contextHolder] = message.useMessage();` 申明的就是 `messageApi`.

**Comment by yizhimo** [comment]
但是实际类型是MessageInstance，没有destroy属性，MessageApi才有

**Comment by yoyo837** [comment]
不太明白你在说什么, 我命名为abc不行么?

<img width="638" alt="image" src="https://user-images.githubusercontent.com/6134547/230262669-6aad625f-660d-40fd-ad59-10d8948b5dd5.png">

**Comment by zombieJ** [comment]
> 但是实际类型是MessageInstance，没有destroy属性，MessageApi才有

指的是 API 和文档里的 API 会让人误解是么？

**Comment by yizhimo** [comment]
![image](https://user-images.githubusercontent.com/58139305/230263336-6344f7f0-686c-47a7-af2d-7b15ffdcdacb.png)

**Comment by zombieJ** [comment]
> ![image](https://user-images.githubusercontent.com/58139305/230263336-6344f7f0-686c-47a7-af2d-7b15ffdcdacb.png)

嗯，的确是这里的 `messageApi` 会让人误解，有兴趣来个 PR 改一下不~改成 `messageInstance`

**Comment by yoyo837** [comment]
这就不是文档问题, 是代码问题啦

**Comment by yizhimo** [comment]
文档里改成MessageInstance也没用，因为useMessage第一个参数类型就是来自MessageInstance，如果不改代码的情况下，文档里应该改成messageApi.destroy -> message.destroy
![image](https://user-images.githubusercontent.com/58139305/230264231-005d634b-bf2a-4f7d-bc1e-65ee5f3037c7.png)

**Comment by yoyo837** [comment]
> ![image](https://user-images.githubusercontent.com/58139305/230263336-6344f7f0-686c-47a7-af2d-7b15ffdcdacb.png)

这个代码从哪里扣的, 没找到代码呢

**Comment by yizhimo** [comment]
![image](https://user-images.githubusercontent.com/58139305/230264836-cb2fbc92-3ad6-4605-ad37-c08ca84c42cd.png)

**Comment by yoyo837** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/6134547/230264954-3d49cbf4-50e2-46d1-ba17-67cd90d3dc87.png">


我以为说5, 看了半天

**Comment by yoyo837** [comment]
https://ant.design/components/message-cn 是5 的文档

**Comment by yizhimo** [comment]
噢噢 没注意，不知道5的源码解决这个问题没

**Comment by yoyo837** [comment]
5 就没你说这个问题吧

**Comment by yizhimo** [comment]
![image](https://user-images.githubusercontent.com/58139305/230265867-af379206-04b0-45d7-8a6e-70200d35ee39.png)
5添加了destroy，谢谢
