### ISSUE TITLE
modal 关闭后之前填写的值还存在

### ISSUE THREAD

**Issue by wm3445** [ant-design/ant-design#4165]
modal 关闭后之前填写的值还存在，这种问题怎么解决啊，
这是我目前的解决方案
ModalGen = () => <MyModal {...props} />;
但是现在出现的问题是配合属性confirmLoading使用 他会先清空内容，请问有没有关闭就销毁的方法啊。

**Comment by yesmeck** [comment]
见 https://github.com/ant-design/ant-design/issues/3729

**Comment by afc163** [comment]
尝试给 Modal 一个 key，打开时换一个。

```jsx
<Modal key={xxx}></Modal>
```

或者打开 Modal 时自行重置数据。

**Comment by imperio-wxm** [comment]
@afc163 Hi，如果在点击Modal后，会有一个websocket长连接打开，在用<Modal key={xxx}></Modal>时，重新打开时会出现全新的Modal，那以前的Modal会自动卸载吗？长连接是否会自动断开？

**Comment by benjycui** [comment]
@imperio-wxm 这属于 React 生命周期的问题，建议看下相关文档。

**Comment by zhulinpinyu** [comment]
现在的方案还是 

```
<Modal key={xxx}></Modal>
```

**Comment by benjycui** [comment]
其实我觉得，在 Modal 关闭事件里调用 Form 的 resetFields 会更好。

**Comment by zjh65204** [comment]
我是这么处理的，有时候需要条件表单：例如根据男、女生成不同的表单内容。
我用resetFields 重置表单，然后再把管理表单的变量也置为初始值

**Comment by songdun** [comment]
<Modal key={xxx}> 你确定能这么做吗？为啥我设置的时候完全不起作用，看源码也没有开放出这个属性啊

**Comment by HelloHolyLi** [comment]
我给两个方案：

1. 使用model的 **afterClose** 
`      
<Modal afterClose={() => this.props.form.resetFields(); >
...
</Modal>
`
2. 使用  **destroyOnClose**

`
<Modal destroyOnClose={true} >
...
</Modal>
`

**Comment by youngjuning** [comment]
> 我给两个方案：
> 
> 1. 使用model的 **afterClose**
> 
> ```
> <Modal afterClose={() => this.props.form.resetFields(); >
> ...
> </Modal>
> ```
> 
> 1. 使用  **destroyOnClose**
> 
> ```
> <Modal destroyOnClose={true} >
> ...
> </Modal>
> ```

我觉得 Model 里边有 Form，统一写 destoryOnClose 应该是规范

**Comment by souldjl** [comment]
> > 我给两个方案：
> > 
> > 1. 使用model的 **afterClose**
> > 
> > ```
> > <Modal afterClose={() => this.props.form.resetFields(); >
> > ...
> > </Modal>
> > ```
> > 
> > 
> > 
> > 1. 使用  **destroyOnClose**
> > 
> > ```
> > <Modal destroyOnClose={true} >
> > ...
> > </Modal>
> > ```
> 
> 我觉得 Model 里边有 Form，统一写 destoryOnClose 应该是规范

但是实际情况并没有destory
