### ISSUE TITLE
When multiple Modals are superimposed, the screen flickers

### ISSUE THREAD

**Issue by rick-chou** [ant-design/ant-design#41662]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-flickering-vwqcww?file=/App.js)

### Steps to reproduce

Click Node to create Modal

### What is expected?

screen does not flicker

### What is actually happening?

screen flicker

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | macos 12.6.3 |
| Browser | chrome |

**Comment by rick-chou** [comment]
https://user-images.githubusercontent.com/56244178/230282655-271e7e69-48a2-4d6d-b6dc-4fc6bce40a2b.mov

**Comment by zombieJ** [comment]
Strange, I can not reproduce this. Could you help to test other browser?

**Comment by rick-chou** [comment]
> Strange, I can not reproduce this. Could you help to test other browser?

You need to create enough Modal

**Comment by rick-chou** [comment]
I've found in my testing that this problem occurs when the browser is full screen and there are enough modals, but not when the browser is not full screen, so I'm just curious as to where the problem occurs

**Comment by zombieJ** [comment]
Thx for tips. Tested with other browser seems it's Chrome only. It may be bug with Chrome which need more dig.

**Comment by zombieJ** [comment]
> Thx for tips. Tested with other browser seems it's Chrome only. It may be bug with Chrome which need more dig.

Tested. When disabled mask it will still blink:
https://codesandbox.io/s/modal-flickering-forked-juxstu?file=/App.js

But again hide svg path, blink gone:
https://codesandbox.io/s/modal-flickering-forked-kd8mj6?file=/styles.css:266-291

Seems it does be the bug of Chrome. Pls feel free to fire issue to https://bugs.chromium.org/ instead.

**Comment by rick-chou** [comment]
Thx!
