### ISSUE TITLE
table数据为空时在 Modal提供的静态方法中展示 ” No data “，与不在该方法中不同

### ISSUE THREAD

**Issue by konayukis** [ant-design/ant-design#41669]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-4-0-forked-kw96io?file=/demo.tsx)

### Steps to reproduce

如题

### What is expected?

展示效果和没在Modal静态方法中的一致

### What is actually happening?

弹框中展示”No data“

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
静态方法不消费 context
* v4 请使用 hooks 版本
* v5 则使用 `App.useApp` 替代

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546
