### ISSUE TITLE
Cascader级联选择 TS代码示例，直接复制引入 onChange方法提示类型错误

### ISSUE THREAD

**Issue by Wster11** [ant-design/ant-design#41666]
### Reproduction link

[https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAyglgOwOYBsIDUCGKCuEAq40AvFABQDOwAToklAD5QI4C2ARhNQJQDaAugG4AUMNCQoAeQTxkaAMIALTMggAeSWGBwA9gkKQAfFFJkAbtjwAuWHTRZcBIgBooFCGgDGwTdr0UbX119IgFuE2MzHTgAExFhRGAuADNMT2gAQSgAb2EofPzPRQhPAGtMdjQAfhtUlHcRAvy9JRUkCBqpGTsIVtU1FRBDEQBfUTRgKEwrDNFMExy8qCKS8sqIWux3ZyWW5VUrc0sNqlpkMIicz38dNAA6FB0kI8duMZGgA](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAyglgOwOYBsIDUCGKCuEAq40AvFABQDOwAToklAD5QI4C2ARhNQJQDaAugG4AUMNCQoAeQTxkaAMIALTMggAeSWGBwA9gkKQAfFFJkAbtjwAuWHTRZcBIgBooFCGgDGwTdr0UbX119IgFuE2MzHTgAExFhRGAuADNMT2gAQSgAb2EofPzPRQhPAGtMdjQAfhtUlHcRAvy9JRUkCBqpGTsIVtU1FRBDEQBfUTRgKEwrDNFMExy8qCKS8sqIWux3ZyWW5VUrc0sNqlpkMIicz38dNAA6FB0kI8duMZGgA)

### Steps to reproduce

官方代码demo，onChange方法提示类型错误

### What is expected?

期望不提示类型错误

### What is actually happening?

onChange方法类型错误

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | 17 |
| System | Mac m1 |
| Browser | Chrome |

**Comment by MadCcc** [comment]
strict 下确实不行

**Comment by Wster11** [comment]
> strict 下确实不行

多谢
