### ISSUE TITLE
How to config table token?

### ISSUE THREAD

**Issue by Caesar-APAX** [ant-design/ant-design#41668]
### Reproduction link

[https://github.com/AsuraLuo/Turbo-Nextjs-Antd-Ecommerce](https://github.com/AsuraLuo/Turbo-Nextjs-Antd-Ecommerce)

### Steps to reproduce

Table token

### What is expected?

Table token can be config on the ConfigProvider or other way to change?

### What is actually happening?

export interface ComponentToken {
}
export interface TableToken extends FullToken<'Table'> {
    tableFontSize: number;
    tableBg: string;
    tableRadius: number;
    tablePaddingHorizontal: number;
    tablePaddingVertical: number;
    tablePaddingHorizontalMiddle: number;
    tablePaddingVerticalMiddle: number;
    tablePaddingHorizontalSmall: number;
    tablePaddingVerticalSmall: number;
    tableBorderColor: string;
    tableHeaderTextColor: string;
    tableHeaderBg: string;
    tableFooterTextColor: string;
    tableFooterBg: string;
    tableHeaderCellSplitColor: string;
    tableHeaderSortBg: string;
    tableHeaderSortHoverBg: string;
    tableHeaderIconColor: string;
    tableHeaderIconColorHover: string;
    tableBodySortBg: string;
    tableFixedHeaderSortActiveBg: string;
    tableHeaderFilterActiveBg: string;
    tableFilterDropdownBg: string;
    tableFilterDropdownHeight: number;
    tableRowHoverBg: string;
    tableSelectedRowBg: string;
    tableSelectedRowHoverBg: string;
    tableFontSizeMiddle: number;
    tableFontSizeSmall: number;
    tableSelectionColumnWidth: number;
    tableExpandIconBg: string;
    tableExpandColumnWidth: number;
    tableExpandedRowBg: string;
    tableFilterDropdownWidth: number;
    tableFilterDropdownSearchWidth: number;
    zIndexTableFixed: number;
    zIndexTableSticky: number;
    tableScrollThumbSize: number;
    tableScrollThumbBg: string;
    tableScrollThumbBgHover: string;
    tableScrollBg: string;
}

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | mac os 14.0.0 |
| Browser | google |

**Comment by Caesar-APAX** [comment]
@MadCcc 您好，我想知道怎么修改table token的参数，目前没有方法修改到

**Comment by zombieJ** [comment]
TableToken is not ComponentToken which only used internal. What do you want to modify in read world?

**Comment by kaidouya** [comment]
如果只是单纯想要改table hover的背景颜色要怎麽做呢？
在antd4可以直接用less的modifyVars取代掉@table-row-hover-bg的颜色
但现在有什麽比较优雅的作法可以使用？
感谢。

**Comment by zhaoxuhui1122** [comment]
> 

```
theme:{
    components:{
        Table:{
             colorFillAlter: "xxx"
         }
    }
}
```

**Comment by kaidouya** [comment]
> 

知道这个，但接著会遇到这个问题
https://github.com/ant-design/ant-design/issues/38975#issuecomment-1488509566
其实我只是想要tableRowHoverBg更换颜色而已
