### ISSUE TITLE
和 browserHistory 配合使用面包屑，浏览器有嵌套a标签警告

### ISSUE THREAD

**Issue by se1phine** [ant-design/ant-design#41670]
### Reproduction link

[https://stackblitz.com/edit/react-hs7y9g?file=demo.tsx](https://stackblitz.com/edit/react-hs7y9g?file=demo.tsx)

### Steps to reproduce

见示例

### What is expected?

`itemRender` 的结果不应该渲染在a标签的里面

### What is actually happening?

--

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | win11.22000 |
| Browser | Chrome 111.0.5563.147 |

**Comment by zombieJ** [comment]
自定义 `itemRender` 了就可以随便改了，不需要使用原生的 `path` 创建链接：
https://stackblitz.com/edit/react-hs7y9g-ugyzep?file=demo.tsx
