### ISSUE TITLE
[4.x]Able to navigate between disabled dates with keyboard.

### ISSUE THREAD

**Issue by saurabhsain20** [ant-design/ant-design#41677]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-uxgnjb?file=/index.js)

### Steps to reproduce

Go to the reproduction link. I have added a condition for disabling the past dates in Calendar. 
1. Click on the current date or any future date in Calendar.
2. Now use keyboard keys to select/navigate and you'll be able to select the disabled past dates.

### What is expected?

User should not be able to select disabled dates with mouse or keyboard.

### What is actually happening?

User is able to navigate between past disabled dates in calendar and select the disable dates and can do the operation with past dates data.

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 16.12 |
| System | Lenovo T14 |
| Browser | Google Chrome 111.0.5563.147 |

**Comment by Wxh16144** [comment]
Not only v4, v5 also has the same problem

**Comment by Yuiai01** [comment]
Let me fix it

**Comment by saurabhsain20** [comment]
@Yuiai01  @zombieJ  How can i replicate this change at my end?

**Comment by saurabhsain20** [comment]
@Yuiai01 @zombieJ It's not working at my end everything is same like before.

**Comment by yoyo837** [comment]
Remove 'node_modules' and lock file, then reinstall it.

**Comment by yoyo837** [comment]
And need `antd@5.4.2+`.

**Comment by yoyo837** [comment]
@Yuiai01 Can we fix it for 4.x?

**Comment by saurabhsain20** [comment]
> And need `antd@5.4.2+`.

We are working on 4.x for more than 2 years. Now i don't think we can directly move our project to 5.x+ .

**Comment by saurabhsain20** [comment]
@yoyo837  @Yuiai01 Is it going to be fixed for v4.x?

**Comment by Wxh16144** [comment]
> @yoyo837  @Yuiai01 Is it going to be fixed for v4.x?
> 
> 

Yes, and we have already started working on it.

**Comment by saurabhsain20** [comment]
@Wxh16144 @yoyo837 @Yuiai01  Hi, can you please update on this.

**Comment by Yuiai01** [comment]
> @Wxh16144 @yoyo837 @Yuiai01 Hi, can you please update on this.

I'm very sorry. I will finish it as soon as possible. 🙏

**Comment by saurabhsain20** [comment]
@Yuiai01  Hi, can you please update on this.

**Comment by Yuiai01** [comment]
> @Yuiai01 Hi, can you please update on this.

This should be fixed in the latest 4.x release.

**Comment by yoyo837** [comment]
> @Yuiai01 Hi, can you please update on this.

Fixed in https://github.com/react-component/picker/releases/tag/v2.7.1
