### ISSUE TITLE
List Item title has unnecessary margin at top

### ISSUE THREAD

**Issue by harsh26shah03** [ant-design/ant-design#41684]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hf1b0u?file=/demo.tsx)

### Steps to reproduce

Open this link and see https://codesandbox.io/s/hf1b0u?file=/demo.tsx

List Item title has unnecessary margin at top,

On digging further found that this is because user-agent-styles for h4 not cleared, so margin-block-start making this margin.

### What is expected?

User-agent-styles should be cleared in Ant's design

### What is actually happening?

Open this link and see https://codesandbox.io/s/hf1b0u?file=/demo.tsx

List Item title has unnecessary margin at top,

On digging further found that this is because user-agent-styles for h4 not cleared, so margin-block-start making this margin.

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | Latest |
| System | Mac |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
It's not aligned, so let me fix it.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/112228030/230373434-6ce29ba7-4e9d-467e-bc35-f3601e5f2b03.png">

**Comment by spyshower** [comment]
That's ant, what did you expect :)

**Comment by gazcn007** [comment]
Thanks for the fix
