### ISSUE TITLE
Form.Item disable showing error message on error

### ISSUE THREAD

**Issue by tw-andri** [ant-design/ant-design#41681]
### What problem does this feature solve?

I would like use the rules attribute on `Form.Item` for validation, but do not need the error message - the red outline is enough. The `validateStatus` attribute could be used, but if the status depends on the value inside the field, using it would lead to extra code and complexity. Could it be possible in some way to disable showing the error message?

The message actually causes weird issues elsewhere, and I would just like to disable it. For example, if I use the `Form` inside a `Modal` - I have fields in a column. They have some space between each other by default. When submitting the form, the spaces contract and then expand again to show the message. This causes the modal to resize and leads to weird flickering effect. It can be fixed by adding `ant-form-condensed` class on the form, but this is always not wanted as it changes the style of the form.

My code example:
```
        <Modal
            title="Add new address"
            visible={visible}
            width="50vw"
            okText="Save"
            onCancel={() => setVisible(false)}
            onOk={saveAddress}
        >
            <Form
                id="addressForm"
                size="middle"
                form={form}
                labelCol={{ span: 12 }}
                wrapperCol={{ span: 11, offset: 1 }}
                labelAlign="left"
                initialValues={data}
                requiredMark={false}
                colon={false}
            >
                <Form.Item
                    name="buildingNumberOrName"
                    label="Building number or name"
                    rules={[{ required: true, whitespace: true, message: " " }]}
                >
                    <Input type="text" />
                </Form.Item>

                <Form.Item
                    name="street"
                    label="Street"
                    rules={[{ required: true, message: " " }]}
                >
                    <Input />
                </Form.Item>
            </Form>
        </Modal>
```

### What does the proposed API look like?

Maybe, if the `message` inside the `Rule` object is an empty string, just apply the `ant-input-status-error` on the input as it is applied when `validateStatus` is `error`.

**Comment by Yuiai01** [comment]
Sorry, can you provide a complete online example? I can't reproduce the problem using your code.
