### ISSUE TITLE
升级react版本到15.4.1后antd的2.5.1版本报错

### ISSUE THREAD

**Issue by leejaen** [ant-design/ant-design#4168]
问题出现在升级react 15.3.2 到15.4.1 后，使用webpack打包时：
```
ERROR in ./~/rc-editor-core/lib/EditorCore/export/getHTML.js
Module not found: Error: Cannot resolve module 'react/lib/CSSProperty.js' in E:\xxxx\xxxx\node_modules\rc-editor-core\lib\EditorCore\export
 @ ./~/rc-editor-core/lib/EditorCore/export/getHTML.js 18:19-54
```
![image](https://cloud.githubusercontent.com/assets/1638970/20958458/b7753be4-bc90-11e6-848a-6c7c20cd6ede.png)
此问题在 [https://github.com/ant-design/ant-design/issues/3882](url) 解决过，现在的版本又出现同问题。

**Comment by yesmeck** [comment]
删除 node_modules 重新安装。

**Comment by afc163** [comment]
可以神图镇楼。

**Comment by yesmeck** [comment]
![npm](https://cloud.githubusercontent.com/assets/465125/20958772/4b77c798-bc92-11e6-911b-c9aaae21ef08.jpg)

**Comment by cycgit** [comment]
![image](https://cloud.githubusercontent.com/assets/13112014/20960608/3c4778ea-bc9c-11e6-92c1-cf7cdec0b6d5.png)

**Comment by leejaen** [comment]
还好有 git reset --hard
![image](https://cloud.githubusercontent.com/assets/1638970/20993415/0438b46c-bd25-11e6-9bb7-96c56537766e.png)

**Comment by yesmeck** [comment]
@leejaen 还有问题？

**Comment by leejaen** [comment]
@yesmeck 有，昨天我试了各种方法还是不行，但是不能确定一定是antd引起的，我还用到其他的库，回滚了……

**Comment by afc163** [comment]
确保 node_modules/rc-editor-core/package.json 里的版本号大于 0.5.8。
