### ISSUE TITLE
我的项目中在旧版antd通过设置className和DatePicker类一致，是可以正确按照antd的样式渲染，但是在v5不生效了，可以怎么修改呢

### ISSUE THREAD

**Issue by jiialinn** [ant-design/ant-design#41699]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/que-ren-dui-hua-kuang-antd-5-4-0-forked-cylzc0?file=/demo.tsx:78-115)

### Steps to reproduce

如这样一段代码 `<div className="ant-button">123</div>`

### What is expected?

ant-button样式，我只是举个例子，实际上我会保证dom结构和antd对应组件一致

### What is actually happening?

antd5没有任何样式，在旧的版本可以正常渲染

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 16.9 |
| System | macos |
| Browser | chrome |

**Comment by Wxh16144** [comment]
v5 中使用了 Css in Js 生成样式，默认会有一个 `:where(xxx)` 选择器，可以阅读 [这里的文档](https://ant.design/docs/react/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8) 关闭，`where` 选择器, 这样可能会出现意想不到的样式错误问题。并不推荐这样做。

**Comment by jiialinn** [comment]
> 

我试过在组件内部使用<StyleProvider hash="high">包裹，但并不生效，只能在最外层全局设置吗，或者有办法只在当前组件生效吗

**Comment by Wxh16144** [comment]
我前面的回答有问题，即使你关闭 `:where` 选择器后。仍然不能通过使用 `ant-xxx` 类名来复用样式。

**Comment by jiialinn** [comment]
> 

那是否有其他办法能支持我实现这样的效果呢，我通过rc-picker, rc-trigger等组件实现了一个和DatePicker结构一模一样的组件，只是为了把原本的日期输入框改成我想要的组件，实际弹框和DatePicker组件是完全一致的，只是现在没有和DatePicker一样的样式

**Comment by afc163** [comment]
我们没有官方支持过这类用法，理论上切 CSS-in-JS 后，这种用法就会失效。建议还是直接引用官方组件。

**Comment by arvinxx** [comment]
似乎可以通过加上hashId的方式来实现？

useToken 里可以拿u hash，然后也放到类名里？

**Comment by jiialinn** [comment]
> 似乎可以通过加上hashId的方式来实现？
> 
> useToken 里可以拿u hash，然后也放到类名里？

我试试嗷，回来跟你说一下

**Comment by jiialinn** [comment]
> 似乎可以通过加上hashId的方式来实现？
> 
> useToken 里可以拿u hash，然后也放到类名里？

正常的一些Button这种简单的组件是可以的，但是像dropdown的弹出框,select的下拉框这种脱离正常上下文的节点就没有用了

**Comment by arvinxx** [comment]
> > 似乎可以通过加上hashId的方式来实现？
> > useToken 里可以拿u hash，然后也放到类名里？
> 
> 正常的一些Button这种简单的组件是可以的，但是像dropdown的弹出框,select的下拉框这种脱离正常上下文的节点就没有用了

@jiialinn  hash 挂到 rootClassName 上
