### ISSUE TITLE
使用StyleProvider的hashPriority="high"去除where选择器，调用message.info还是会生成where选择器导致在360浏览器不兼容？

### ISSUE THREAD

**Issue by bruce-zhang932** [ant-design/ant-design#41703]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0g7rdz?file=/index.js)

### Steps to reproduce

点击按钮不弹出message信息

### What is expected?

解决这个兼容性的问题

### What is actually happening?

在360浏览器，搜狗浏览器message无法使用

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 17.0.2 |
| System | window |
| Browser | 360急速浏览器 |

**Comment by afc163** [comment]
静态方法无法感知 React Context，调用处需要改造成 useMessage 或者 useApp 的 hooks 版本用法。

**Comment by bruce-zhang932** [comment]
@afc163 您好，useApp的方式怎么解决这个问题呢？

**Comment by trampboy** [comment]
@bruce-zhang932  可以参考 App
包裹组件 https://ant.design/components/app-cn
