### ISSUE TITLE
table滚动条样式错误

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#4170]
发生问题的环境是：
        (1) antd 版本 2.5.0 :
        (2)操作系统及其版本: win8.1
        (3)浏览器及其版本: chrome 53.0.2785.143 (64-bit)
您做了什么？请提供尽可能详细的重现步骤。
       (1)在表格的右侧固定了一个操作列
       (2)修改了表格的滚动条样式
       (3) 下拉滚动条的时候出现行错位
您期待的结果是:
      行数据正常显示
实际上的结果是:
      在滑动滚动条时出现行错位
错位演示图
![bug](https://cloud.githubusercontent.com/assets/11780264/20959175/8caaf97c-bc94-11e6-8e9e-38fd4f2c14db.gif)
![css](https://cloud.githubusercontent.com/assets/11780264/20959210/c2568adc-bc94-11e6-8498-9944fa5c0870.png)

**Comment by benjycui** [comment]
看不懂，具体怎么错位。预期和实际的区别。

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
同样看不懂。

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
可能和楼主定义了滚动条宽度有关系，https://github.com/react-component/table/blob/ad9db3febac5bd4e02ca1de672e6c757d4101089/src/utils.js#L12-L30 这里有测量浏览器滚动条宽度。

**Comment by XUGAOBO** [comment]
不好意思,由于近期工期比较紧,没有及时反馈,近期会整理下demo放上去

**Comment by XUGAOBO** [comment]
测试了下,确实与设置滚动条的宽度有关系

**Comment by afc163** [comment]
这个问题不解决了，如果自定义了滚动条宽度，建议全局的滚动条保持一致。
