### ISSUE TITLE
Notification hooks calls do not accept `bottom` argument

### ISSUE THREAD

**Issue by rkuykendall** [ant-design/ant-design#41719]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hooks-usage-recommended-antd-5-4-0-forked-zeuxnz?file=/demo.tsx)

### Steps to reproduce

Try to pass `bottom` argument to `api.info` similar to the `top` argument.

### What is expected?

`api.info` accepts  `bottom` argument similar to the `top` argument.

### What is actually happening?

`api.info` does not accept  `bottom` argument similar to the `top` argument.

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 17.0.2 |
| System | Mac OS X 12.6 |
| Browser | Chrome |

---
```
Argument of type '{ message: string; description: JSX.Element; placement: NotificationPlacement; top: number; bottom: number; }' is not assignable to parameter of type 'ArgsProps'.
  Object literal may only specify known properties, and 'top' does not exist in type 'ArgsProps'.ts(2345)
```

**Comment by MuxinFeng** [comment]
Maybe there is a problem with the documentation, you can use style first.
```
const openNotification = (placement: NotificationPlacement) => {
    api.info({
      message: `Notification ${placement}`,
      description:
        'This is the content of the notification. This is the content of the notification. This is the content of the notification.',
      placement,
      style: { bottom: 240 },
    });
  };
```

**Comment by MuxinFeng** [comment]
The parameters of hooks seem to be inconsistent with those of regular usage.Do we need to add a hooks parameter description？
![image](https://user-images.githubusercontent.com/46584765/230810557-03121566-df2d-4aaf-98e8-72a65f919053.png)

**Comment by zombieJ** [comment]
Seems your reproduce not throw TS error.
