### ISSUE TITLE
Ant Design Upload: eye icon is not clickable when i select video

### ISSUE THREAD

**Issue by FatimeyiZahra** [ant-design/ant-design#41718]
### Reproduction link

[https://ant.design/components/upload#components-upload-demo-upload-png-only](https://ant.design/components/upload#components-upload-demo-upload-png-only)

### Steps to reproduce

https://ant.design/components/upload

### What is expected?

i wanna preview video 

### What is actually happening?

eye icon is not clickable

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | reactJs |
| System | windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Demo with `onPreview` is show how it work. If you want to support video preview, you need to realize it with video player instead.

ref demo: https://ant.design/components/upload#components-upload-demo-picture-card

**Comment by pavanh007** [comment]
When I upload the the video, preview eye icons is in disabled state. Is it possible to preview the video in ant design
