### ISSUE TITLE
Select 弹层体验问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#41728]
https://user-images.githubusercontent.com/507615/230823324-41beb299-d4b3-43a4-b932-97fcff94ae31.mov

删掉搜索词后，弹层会先向下跳，然后再向上跳，体感就是闪一下。

<img width="589" alt="图片" src="https://user-images.githubusercontent.com/507615/230820358-c13c0d4f-842d-4369-9373-278d95bd817e.png">

<img width="585" alt="图片" src="https://user-images.githubusercontent.com/507615/230820373-e31ab9f2-cc0a-4fd1-941a-cdac50c8075a.png">

**Comment by afc163** [comment]
另外，上下跳的问题貌似还存在。

**Comment by zombieJ** [comment]
> 另外，上下跳的问题貌似还存在。

这个指的是？

**Comment by afc163** [comment]
就是这个 https://github.com/ant-design/ant-design/issues/5130#issue-211118691

**Comment by zombieJ** [comment]
> 就是这个 [#5130 (comment)](https://github.com/ant-design/ant-design/issues/5130#issue-211118691)

那应该没问题了，https://github.com/react-component/trigger/pull/362 会稳定 flip 位置
