### ISSUE TITLE
treeSelect如何根据子节点知道当前子节点的第一个父节点到本身的所有节点的name跟key

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#4172]

**Comment by aw6658913** [comment]
我目前的做法是异步渲染的时候给每个节点的key加上上一级的value，然后利用indexOf去循环查询上一级的节点的value值，但是这样效率很慢～特别是节点多而且层级深的时候

**Comment by yesmeck** [comment]
你是要在什么阶段获取？

**Comment by aw6658913** [comment]
在下拉去该节点下子节点的时候～

**Comment by warmhug** [comment]
描述不够清楚，codepen 贴下可运行的示例代码出来

**Comment by pixystone** [comment]
每个node给一个parent引用，用递归计算得到，我这边是这么实现的。

**Comment by yesmeck** [comment]
没反馈关闭了，有问题再重新打开。
