### ISSUE TITLE
Disabled Button's classNames error with Tooltip。

### ISSUE THREAD

**Issue by aswez** [ant-design/ant-design#41721]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-4-0-forked-qdc8sl?file=/demo.tsx)

### Steps to reproduce

1. Open the link https://codesandbox.io/s/basic-antd-5-4-0-forked-qdc8sl?file=/demo.tsx
2. Open the Dev Tool, and select the button

### What is expected?

The button's class name is on itself, not the ancestor.

### What is actually happening?

The button's class name is on the ancestor, but not itself.

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | React latest |
| System | Mac |
| Browser | Chrome lastest |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/21404#issuecomment-586798570
