### ISSUE TITLE
使用umi3.5，v4 升级 v5后报错'~antd/es/style/themes/default.less

### ISSUE THREAD

**Issue by haobarry** [ant-design/ant-design#41733]
### Reproduction link

[http://localhost:8000](http://localhost:8000)

### Steps to reproduce

前端框架使用 umi3的最新版
antd升级v5后 ，按要求进行了对less变量的兼容处理，现在启动项目总会有个报错
``` 
@import '~antd/es/style/themes/default.less';
^
Can't resolve 'antd/es/style/themes/default.less' in 'D:\Project\k-b-ts\.umi\plugin-layout\layout\layout'
``` 
![''](https://github.com/haobarry/mzui/blob/master/QQ%E6%88%AA%E5%9B%BE20230410174314.png?raw=true)

### What is expected?

正常编译

### What is actually happening?

页面打不开

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 17 |
| System | win11 |
| Browser | chrome110 |

**Comment by Wxh16144** [comment]
你的 umi 使用了 antd 插件吗？可能需要先升级你的 umi

**Comment by haobarry** [comment]
> 

插件按官方文档配置了一些基本参数，没有其他复杂的

**Comment by yoyo837** [comment]
要用 umi 4

**Comment by yoyo837** [comment]
总之就是antd@5 没有less 文件了, 谁再引用 less 就消灭谁, 试试.

**Comment by Wxh16144** [comment]
> 要用 umi 4

得需要问问 umijs 的人，应该在 umijs plugin 那边说明一下版本范围啥的。

**Comment by haobarry** [comment]
确实是，3.5的插件

> 总之就是antd@5 没有less 文件了, 谁再引用 less 就消灭谁, 试试.

确实是这样，只能升级umi4  或者修改这个插件了。。。

**Comment by haobarry** [comment]
> > 要用 umi 4
> 
> 得需要问问 umijs 的人，应该在 umijs plugin 那边说明一下版本范围啥的。

@import '~antd/es/style/themes/default.less';
确实是插件问题 ，删除了这个引入就正常了。 插件开发的时候没想到antd升级把 less删除了

**Comment by Wxh16144** [comment]
这个 issue 没办法转移到 umijs 那边，你可以考虑给他们提交一个 PR 修复他，然后关闭这个 issue。
