### ISSUE TITLE
使用5.4.0版本的modal组件，afterOpenChange属性typescript报错

### ISSUE THREAD

**Issue by wh940816** [ant-design/ant-design#41735]
### Reproduction link

[https://ant.design/components/modal-cn](https://ant.design/components/modal-cn)

### Steps to reproduce

无

### What is expected?

能正常使用该属性

### What is actually happening?

使用该属性，ts报错

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2 |
| System | mac |
| Browser | chrome |

**Comment by wh940816** [comment]
5.4.0版本 modal组件是不是不支持这个属性啊，如果不支持，文档里面为啥会写啊

**Comment by Yuiai01** [comment]
确实是存在 ts 报错的情况
![image](https://user-images.githubusercontent.com/112228030/230883798-1ccb07fd-128c-49da-be34-9e6474ebb035.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-ben-antd-5-4-0-forked-7slk0c?file=/demo.tsx

**Comment by MuxinFeng** [comment]
我补充下 TS 定义吧~
