### ISSUE TITLE
hide Pagination when there is the only page

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#4173]
I would like to hide pagination in case if there is only one page. Is it possible to do via configs (e.g. Table)?

**Comment by yesmeck** [comment]
Set pagination to `false` if your data size lte page size.

**Comment by plandem** [comment]
so, if in my case it's default behavior, then I have to use special code everywhere?! I think it would be useful to have "autoHide" feature for Pagination component.

**Comment by yesmeck** [comment]
It's easy to implement your need by following code, I don't thinks it's worth to introduce a new prop.

```javascript
const pageSize = 20;

<Table pagination={data.length > pageSize && { pagrSize }} />
```

**Comment by plandem** [comment]
ok, i see you.

**Comment by linhuiw** [comment]
@yesmeck  Maybe pagination can set to false when only one page by default.

**Comment by shanthan25** [comment]
use like this  

`<Table pagination={{defaultPageSize: 10, hideOnSinglePage: true}} />`

**Comment by frantwo** [comment]
Hello, 
According to the documentation ([first FAQ of Table documentation](https://ant.design/components/table/#components-table-demo-pagination)) I have the next code:
`
  <Table
    key={index + plant.nombre}
    columns={setColumns(plant.nombre, plant.id)}
    data={setData(plant)}
    pagination={{ defaultPageSize: 10, hideOnSinglePage: true }}
  />
`
But it is still appearing the pagination:
![image](https://user-images.githubusercontent.com/11053804/91700183-c2325180-eb75-11ea-9e37-4f01b06ff182.png)

Also I have tried all combinations as:
pagination={{false}} 
pagination={false}
pagination={"false"}

But nothing runs properly.
Could you help me please?
Thank you very much for your time!

**Comment by monika-octet** [comment]
pagination={false} working for me
