### ISSUE TITLE
Select组件快速输入时显示不全的bug

### ISSUE THREAD

**Issue by aoto** [ant-design/ant-design#4174]
Select组件multiple模式快速输入会出bug，输入的内容显示不全。
![antd bug](https://cloud.githubusercontent.com/assets/2315342/20963160/3d402a48-bca7-11e6-9342-1ff1c1a00e9d.gif)

**Comment by benjycui** [comment]
得多块。。下面的例子我长按都没问题。

https://ant.design/components/select/#components-select-demo-multiple

**Comment by afc163** [comment]
发现和输入快慢没关系，输入过程中弹层不显示时（`notFoundContent={null}`），就会出现这个 bug。
