### ISSUE TITLE
Calendar with date-fns not styled properly with NextJS

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#41749]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/wispy-fast-ywg1ty)

### Steps to reproduce

Click Default tab: works correctly. Click Date Fns tab: styling is incorrect (`colorPrimary` is ignored).

### What is expected?

Colored items should be the correct color (`colorPrimary`).

### What is actually happening?

Colored items show as default color (blue).

| Environment | Info |
| --- | --- |
| antd | 5.4.1 |
| React | 18.2.0 |
| System | Windows Professional 21H2 |
| Browser | Chrome Version 112.0.5615.50 (Official Build) (64-bit) |

---
I tried changing calendar.tsx imports from "antd/lib" to "antd/es", which is what the documentation says to do, but this does not compile with NextJS.

I believe this bug also applies to `generatePicker`.

**Comment by zombieJ** [comment]
NextJS using es modules, we can improve this export from DatePicker.generate instead of developer import from path

**Comment by devuxer** [comment]
@zombieJ,

Thank you for working on this!

Can you show a usage example? I don't quite understand what you've done.

**Comment by devuxer** [comment]
@zombieJ,

Can you please answer our questions?

1. Does your patch solve the issue with styling? (See @iakovmarkov 's comment)

    I want this:

    ![image](https://user-images.githubusercontent.com/1298521/233859387-314e4d7e-39f5-4dfb-8532-62a933eda18c.png)

    But I'm getting this:

    ![image](https://user-images.githubusercontent.com/1298521/233859405-b8239983-98f8-40d0-ba47-9625982dc88c.png)

2. When will this patch be released? I just installed version 4.5.4 and still don't see any of your code changes so I can test it. Are you waiting for a code review or something?

**Comment by zombieJ** [comment]
feature branch release minor version at end of each month. Please ref #41773 for more info : )

**Comment by devuxer** [comment]
@zombieJ , It's a new month now. I don't see any difference.

**Comment by iakovmarkov** [comment]
I've tried the new version as well and the bug is still present. I tried to look into the source code again but the interactions with theme provider are simply too arcane for an outsider to understand.

Unfortunately, that's not the only place where Theme/Config Provider is outright broken. There is not much interest from the Antd team in fixing those edge cases it seems.

**Comment by devuxer** [comment]
@iakovmarkov,

That's not good. What other components are broken? If there are issues for them, can you link here? Thx.
