### ISSUE TITLE
使用DatePicker组件报错Warning: 'dateRender' is deprecated. Please use 'cellRender' instead.

### ISSUE THREAD

**Issue by AprildreamMI** [ant-design/ant-design#41751]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-0xl22c?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

1. 打开codesandbox最小重现
2. 点击一个日期选择器选择日期
3. 观察console

### What is expected?

无警告，无报错

### What is actually happening?

Warning: 'dateRender' is deprecated. Please use 'cellRender' instead. 
Warning: 'monthCellRender' is deprecated. Please use 'cellRender' instead. 

| Environment | Info |
| --- | --- |
| antd | 5.4.1 |
| React | 18.2.0 |
| System | win10 |
| Browser | 谷歌111.0.5563.148（正式版本） （64 位） |

---
需要监听onChange事件 <DatePicker onChange={handleChange}></DatePicker>

**Comment by MadCcc** [comment]
这是一个 dev warning，只会在开发环境生效。如果条件允许请按照提示升级 api

**Comment by AprildreamMI** [comment]
这不是用户使用废弃的方法产生的警告，是antd内部产生的警告，查看实例，没有使用任何废弃的方法
```
<DatePicker onChange={handleChange}></DatePicker>
```

**Comment by AprildreamMI** [comment]
![image](https://user-images.githubusercontent.com/31964372/231108136-89284da5-540b-4a7a-b57f-605178586ca7.png)
@MadCcc

**Comment by AprildreamMI** [comment]
上方提供了最小重现麻烦看一下

**Comment by shivankkunwar** [comment]
I am using 5.3.2 version - can I fix this without updating to newer version?
