### ISSUE TITLE
Breaking change in version 5.4.1 - Form.Item is missing requiredMark prop 

### ISSUE THREAD

**Issue by HermanBilous** [ant-design/ant-design#41750]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-forest-rqog1s?file=/src/App.tsx)

### Steps to reproduce

Open the link and see that the app doesn't compile, because requiredMark is not a prop in Form.Item
version 5.4.0 works:
https://codesandbox.io/s/practical-paper-n0vsof?file=/src/App.tsx

### What is expected?

Form.Item accepts requireMark prop. A warning must be thrown.

### What is actually happening?

Form.Item does not accept requiredMark

| Environment | Info |
| --- | --- |
| antd | 5.4.1 |
| React | any |
| System | any |
| Browser | any |

---
https://github.com/ant-design/ant-design/pull/41725 introduced this issue, and the release notes for version 5.4.1. don't flag removal of requiredMark as a breaking change.

**Comment by zombieJ** [comment]
`requiredMark` is always config on Form level since v4 instead but pass the TS support in Form.Item by mistake:

<img width="1354" alt="截屏2023-04-11 16 43 28" src="https://user-images.githubusercontent.com/5378891/231105762-5ae42b56-947f-4353-8d7b-a8d03cf91897.png">

v4 doc ref: https://4x.ant.design/components/form/#API

**Comment by zombieJ** [comment]
Add could you tell which case you need is on the Form.Item instead of Form level?

**Comment by HermanBilous** [comment]
I checked our usage of requiredMark, and it appears that switching from using it from Form.Item to Form in 5.4.0 does not make any visible differences, so it's safe for us to change usage.

As for the docs, I agree, they clearly state that it's not something that we should use. Still, I'm mostly working with code, and if I have a prop that works and exists in the interface, I will use it. Even if it's not in the docs.

**Comment by zombieJ** [comment]
Thanks for feedback. Please feel free to comment if meet any case current Form `requiredMark` can not satisfy : )

**Comment by canvascat** [comment]
实际业务中确实存在表单中部分输入必填又不要显示*的情况（搞不懂产品怎么想的）
