### ISSUE TITLE
树形控件能否将多选和单选结合？

### ISSUE THREAD

**Issue by atkxyh** [ant-design/ant-design#41757]
### What problem does this feature solve?

在操作系统的内核配置中（Kernel Config），是一个树形的配置结构，其中包括了下拉（多选+input）以及下拉单选的情景 

### What does the proposed API look like?

```typescript
{
      title: 'parent 1-3',
      key: '0-0-3',
      checkable:false,
      children: [
        {
          title: '苹果',
          key: '0-0-3-0',
          value:'apple',
          type:'radio'
        },
        {
          title: '香蕉',
          key: '0-0-3-1',
          value:'banana',
          type:'radio'
        },
        {
          title: '西瓜',
          key: '0-0-3-2',
          value:'watermelon',
          type:'radio'
        },
        {
          title: '橘子',
          key: '0-0-3-3',
          value:'orange',
          type:'radio'
        }
      ],
    }
```

**Comment by afc163** [comment]
没太理解具体是什么样的交互？

**Comment by atkxyh** [comment]
不好意思 手机上画的比较抽象，就是在一个Tree组件中同时存在单选和多选的子项节点，他们的关系可以是父子（多选中包含单选下拉框和CheckBox）也可以是平级发自我的 iPhone在 2023年4月11日，20:23，afc163 ***@***.***> 写道：﻿
没太理解具体是什么样的交互？

**Comment by zombieJ** [comment]
这边没有看到你的图，直接到 github 的 issue 来贴一下？

**Comment by atkxyh** [comment]
![Tree结构](https://user-images.githubusercontent.com/67258027/231186145-c04f56ad-b275-4b20-8bb5-de1cc365dd9c.jpg)

**Comment by zombieJ** [comment]
我转给设计师评估一下

**Comment by atkxyh** [comment]
好的 多谢！发自我的 iPhone在 2023年4月12日，15:56，二货爱吃白萝卜 ***@***.***> 写道：﻿
我转给设计师评估一下

**Comment by atkxyh** [comment]
请问使用titleRender可以实现上述的情景吗？

**Comment by atkxyh** [comment]
有消息了嘛？ 如果不使用checkbox给tree初始化，可以提供一份使用titleRender的阳历代码嘛？
