### ISSUE TITLE
Badge number position offset in Chrome when using non-default font size.

### ISSUE THREAD

**Issue by JesperWe** [ant-design/ant-design#4176]
antd version 2.5.1
I am using default theme modified with `@font-size-base: 16px;`
The issue is hard to fix using custom CSS overlay, since scroll position is computed in JS...

Firefox:

![image](https://cloud.githubusercontent.com/assets/1643015/20985611/7f6b1324-bcc5-11e6-9bb3-7fa3bb0ab3e3.png)

Chrome (v55):

![image](https://cloud.githubusercontent.com/assets/1643015/20985665/b1644aa8-bcc5-11e6-94e4-2519c15a7a9b.png)

**Comment by benjycui** [comment]
In https://github.com/ant-design/ant-design/blob/master/components/badge/style/index.less#L12

`height` `min-width` `line-height` and so on should be configurable in theme.

You can replace some of them with LESS variables and test locally, if anything is fine, just create a PR. Thanks.
