### ISSUE TITLE
form组件里switch组件后面些注释为什么form就获取不到值了

### ISSUE THREAD

**Issue by wangyi997042** [ant-design/ant-design#41769]
### Reproduction link

[https://ant.design/components/switch-cn](https://ant.design/components/switch-cn)

### Steps to reproduce

<Field
          label="开关"
          name={'switch'}
          valuePropName='checked'
        >
          <Switch /> {/* 23 */}
        </Field>

### What is expected?

switch:true

### What is actually happening?

无论开关switch的值都为undefined

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 17.0.2 |
| System | mac |
| Browser | 谷歌 |

**Comment by lvvlan** [comment]
请问这个问题解决了吗？ 目前5.5.0版本还是会有这个问题，而且在表单验证的时候如果有Switch组件，并且是必选的情况下，无论如何设置Switch的checked值，提交表单的时候都会报错。

demo link： https://stackblitz.com/edit/react-hrtwox-duo6pt?file=demo.tsx

**Comment by Wxh16144** [comment]
> 请问这个问题解决了吗？ 目前5.5.0版本还是会有这个问题，而且在表单验证的时候如果有Switch组件，并且是必选的情况下，无论如何设置Switch的checked值，提交表单的时候都会报错。
> 
> demo link： https://stackblitz.com/edit/react-hrtwox-duo6pt?file=demo.tsx

你的 switch 的 rule 需要多加一个 type 

```diff
        <Form.Item
          name="switch"
          label="switch"
-          rules={[{ required: true }]}
+          rules={[{ required: true, type: 'boolean' }]}
          valuePropName="checked"
        >
          <Switch
            checkedChildren="YES"
            unCheckedChildren="NO"
            checked={false}
          />
        </Form.Item>
      </Form>

```
