### ISSUE TITLE
The form component cannot get the file list from another file upload component

### ISSUE THREAD

**Issue by lvs071103** [ant-design/ant-design#41768]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-g6v85j?file=/index.js)

### Steps to reproduce

normFile func content is as follows:
```javascript
  const normFile = (e) => {
    console.log(e.fileList)
    if (Array.isArray(e)) {
      return e
    }
    return e && e?.fileList
  }
```
Form.item:
```javascript
    <Form.Item label="比价/豁免附件">
            <Form.Item
              name="exempt_files"
              valuePropName="fileList"
              getValueFromEvent={normFile}
              noStyle
            >
              <ExemptAttachmentsUpload getExemptUpload={getExemptUpload} />
            </Form.Item>
          </Form.Item>
```

upload content is as follows：

```javascript
import { InboxOutlined } from '@ant-design/icons'
import { message, Upload } from 'antd'
import { http, getToken } from '@/utils'
// import { flushSync } from 'react-dom'


const { Dragger } = Upload

const ExemptAttachmentsUpload = (props) => {
  const { getExemptUpload } = props
  const options = {
    name: 'doc_file',
    multiple: true,
    action: 'http://10.1.32.152:8000/api/contract/exempt_attachments/upload',
    headers: { Authorization: `Bearer ${getToken()}` },
    onChange (info) {
      const { status } = info.file
      if (status !== 'uploading') {
        // console.log(info.file, info.fileList)
        console.log('status: ', status)
        getExemptUpload(info)
      }
      if (status === 'done') {
        message.success(`${info.file.name} file uploaded successfully.`)
        // flushSync(() => { setExemptFiles(info.fileList) })
      } else if (status === 'error') {
        message.error(`${info.file.name} file upload failed.`)
      }
      if (status === 'removed') {
        const removed = async () => {
          await http.post(`contract/exempt_attachments/delete/${info.file.response.pk}`)
        }
        removed()
      }
      // flushSync(() => { setExemptFiles(info.fileList) })
    },
    onDrop (e) {
      console.log('Dropped files', e.dataTransfer.files)
    },
  }

  return (
    <Dragger {...options}>
      <p className="ant-upload-drag-icon">
        <InboxOutlined />
      </p>
      <p className="ant-upload-text">Click or drag file to this area to upload</p>
      <p className="ant-upload-hint">
        Support for a single or bulk upload. Strictly prohibited from uploading company data or other
        banned files.
      </p>
    </Dragger>
  )
}

export default ExemptAttachmentsUpload
```

### What is expected?

I want to write the two functions in different files, and then I want get the file list by the normFile

### What is actually happening?

The normFile function cannot get ExemptAttachmentsUpload  component uploaded file list， report exempt_files: undefined
 If written in the same file is obtainable

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18.2.0 |
| System | Centos 7 |
| Browser | chorm |

**Comment by zombieJ** [comment]
Your customize component not accept `value` & `onChange` event. 
ref https://ant.design/components/form-cn#components-form-demo-customized-form-controls for how to create customize component.

**Comment by lvs071103** [comment]
![image](https://user-images.githubusercontent.com/5029708/232363741-69da7a99-93ce-4e5f-b756-37d6f8b41863.png)
I updated the code, but I don't know how to use it, I tried it, but the variable value is still undefined

**Comment by zombieJ** [comment]
> Your customize component not accept `value` & `onChange` event. 

Do it in `ExemptUpload`

**Comment by lvs071103** [comment]
![image](https://user-images.githubusercontent.com/5029708/232459941-ac197c29-84da-4d45-84d6-b50c22c2b495.png)
@zombieJ thank you very much， I'm a novice, thanks for the guidance
