### ISSUE TITLE
Tour 漫游式引导的 type 为 primary 时，箭头的颜色仍为白色

### ISSUE THREAD

**Issue by iola1999** [ant-design/ant-design#41760]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-4-2-forked-ynr39y?file=/demo.tsx:433-456)

### Steps to reproduce

点击 Begin Tour

### What is expected?

该 step 或整个 Tour 的 type 为 primary 时，箭头应为蓝色。

### What is actually happening?

箭头颜色为白色。
![image](https://user-images.githubusercontent.com/24544721/231197781-e5889a83-185a-489d-9580-1d2d59fc203f.png)

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | ^18.0.0 |
| System | macOS |
| Browser | Chrome |

**Comment by li-jia-nan** [comment]
自己提 PR 修自己的 issue，太酷辣！
