### ISSUE TITLE
Very difficult to adjust the height

### ISSUE THREAD

**Issue by feryrmdhn** [ant-design/ant-design#41766]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/option-group-antd-4-24-8-forked-ilks4h?file=/demo.js)

### Steps to reproduce

I just want to custom the height, I've also changed it directly in the css class but it has no effect

### What is expected?

Easy to customize the height

### What is actually happening?

Difficult to customize the height

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | react v16 |
| System | Mac OS Monterey |
| Browser | Chrome v109.0.5414.119 (Official Build) (arm64) |

---
It should be easy to customize css not only in this component, both for beginners and advanced developers

**Comment by afc163** [comment]
https://codesandbox.io/s/option-group-antd-4-24-8-forked-4368t7?file=/demo.js:484-522

Try `dropdownStyle`.

**Comment by feryrmdhn** [comment]
@afc163  I think you misunderstood what I meant not the height of the wrapper but the height of the list, here the data is only visible until 'willy' should appear full to the bottom above the button.
and if the data is more than that it will scroll automatically

**Comment by afc163** [comment]
We may need a `optionRender`. @ant-design/ant-design-collaborators

**Comment by feryrmdhn** [comment]
Thanks for the response

**Comment by MadCcc** [comment]
Try `listHeight`

**Comment by feryrmdhn** [comment]
@MadCcc Got it!, thanks
