### ISSUE TITLE
支持 rowSelection 可以自行控制，用以支持行合并

### ISSUE THREAD

**Issue by Phinome** [ant-design/ant-design#41767]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/1940194/231374594-ca27abbd-ae1c-4af5-bf3d-ac72e4d710e5.png)
如上图所示，此时，如果能够有 column 的 onCell 函数，我就可以自行控制，将两个同样的选择器合并为一个。

### What does the proposed API look like?

rowSelection: {
   onCell: function(record, rowIndex)
}

**Comment by Ylg12345** [comment]
这个可以再描述的再细致点吗？我看看能不能解决

**Comment by zombieJ** [comment]
测了一下，有这个函数的。就是选中要自己处理一下行逻辑：
https://codesandbox.io/s/te-shu-lie-pai-xu-antd-5-7-3-forked-mlstsc?file=/demo.tsx
