### ISSUE TITLE
Tree Checking is very slow and causes a large re-render when you have a lot of nodes expanded

### ISSUE THREAD

**Issue by iamBevan** [ant-design/ant-design#41774]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-y0zxtg?file=/index.js)

### Steps to reproduce

Load ~1000 items into tree data and expand all the items, check the root level node

### What is expected?

The tree should be able to efficiently manage checking nodes when they have many expanded child items

### What is actually happening?

The tree takes 2-4 seconds to render the checkbox ticks and locks up the system

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 111.0.5563.147 |

---
Virtualization doesn't appear to have fixed the delay when checking the root node of a large tree.

**Comment by zombieJ** [comment]
```diff
--  console.log("selected", selectedKeys, info);
++  console.log("selected", selectedKeys);
```

https://codesandbox.io/s/antd-reproduction-template-forked-3co4t6?file=/index.js:206214-206256

Codesandbox console will loop obj props. This is not related with antd.
