### ISSUE TITLE
存在相同 rowKey 项时翻页顶部会显示重复的 rowKey 中的一项

### ISSUE THREAD

**Issue by Phinome** [ant-design/ant-design#41787]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ze-he-cao-zuo-antd-5-4-2-forked-40gosk)

### Steps to reproduce

翻页即可复现，第一项始终会重复

### What is expected?

翻页仅展现当前的页的数据，无论上一页是否有重复的行

### What is actually happening?

翻页后重复行会在顶部重复出现。

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.0.0 |
| System | codesandbox |
| Browser | 111.0.5563.110 |

---
如果你们认为这不是一个 BUG，可否能提供一个强制 rerender 的方法，多谢。

**Comment by yoyo837** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/6134547/231643236-8a8a1fbd-83ce-4e14-aa8d-6cf091c1ca67.png">


rowKey隔离呀

**Comment by yoyo837** [comment]
https://codesandbox.io/s/xuan-ze-he-cao-zuo-antd-5-4-2-forked-be7hu5?file=/demo.tsx

**Comment by afc163** [comment]
需要确保 rowKey 不重复，否则会出现各种异常行为。
