### ISSUE TITLE
Form.Item使用getValueFromEvent获取DatePicker的时间戳发生错误

### ISSUE THREAD

**Issue by zhaozkTHU** [ant-design/ant-design#41786]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tqd8ig?file=/index.js)

### Steps to reproduce

使用`Form`通过`getValueFormEvent`来获取`DatePicker`的时间戳，`event`类型理应是`dayjs.Dayjs`，调用`valueof()`出现`date.year is not a function`

### What is expected?

获取时间戳

### What is actually happening?

`TypeError: date.year is not a function`

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18 |
| System | Windows11 |
| Browser | Chrome最新版 |

**Comment by afc163** [comment]
getValueFormEvent 的返回值需要是一个 dayjs 的对象，并非是 valueOf 的调用导致的报错。

https://codesandbox.io/s/antd-reproduction-template-forked-g1wukl?file=/index.js

**Comment by afc163** [comment]
我感觉你需要解决的是 TS 定义问题，给个 TS 的 codesandbox 重现看看？
