### ISSUE TITLE
Release Cycle in README.md

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4178]
See: https://gitlab.com/gitlab-org/gitlab-ce/blob/2325e3be0793aa29412bc00281df39ed483a841e/doc/release/README.md

As we had discussed before @afc163 :

* Weekly release. Release patch version at the end of every week.
* Emergence release. Release emergence patch anytime if necessary. 
* Monthly release. Release minor version at the end of every month.
* Major version is not in cycle.

**Comment by afc163** [comment]
:+1:

**Comment by afc163** [comment]
Add Weekly about antd and publish here: https://github.com/ant-ued/blog/issues
