### ISSUE TITLE
Dropdown menu behave inverted when css hashes are disabled in nextjs app dir

### ISSUE THREAD

**Issue by Skyriis** [ant-design/ant-design#41789]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/weathered-browser-1750b6?file=%2Fapp%2Flayout.tsx)

### Steps to reproduce

1. Start a NextJS Project with App dir
2. Setup Antd and Static Style Extract Script
3. disable `hashed` option in css gen script and root layout config provider
4. Add Dropdown Menu
5. Hover over the Menu
6. Hover away from the Menu

### What is expected?

Open the Menu when hover above the menu and closing the menu when hovering away

### What is actually happening?

Open the Menu when hover away from the menu and closing the menu when hovering over it

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 112.0.5615.50 |

---
NextJS: 13.3.0

**Comment by zombieJ** [comment]
Your online reproduce shows:
<img width="345" alt="截屏2023-04-13 14 03 08" src="https://user-images.githubusercontent.com/5378891/231667737-ed383b9f-b6ea-45fc-afc0-b3e8de1ebaa6.png">


Please help to correct the reproduce

**Comment by Skyriis** [comment]
Weird :S it works just fine in my browser.
![image](https://user-images.githubusercontent.com/128689017/231668203-97f48a13-9c1b-43eb-ae6e-08172efe3260.png)

**Comment by Skyriis** [comment]
Try https://1750b6-3000.csb.app/ instead of https://1750b6-3001.csb.app/ in the preview
