### ISSUE TITLE
Issue of dropdown scrolling in a modal.

### ISSUE THREAD

**Issue by ianneo97** [ant-design/ant-design#41784]
### Reproduction link

[https://github.com/ianneo97/component-library](https://github.com/ianneo97/component-library)

### Steps to reproduce

Clone the package and open up the table.stories.tsx   add-table.tsx.
Currently modified the table height to be 800px to further showcase the bug.

When in a modal where there is a table   a select. When scrolling from the bottom to the top the select will be following the page screen rather than sticking to its' own container.

### What is expected?

The select to not follow the page scroll.

### What is actually happening?

It is following the page scroll.

| Environment | Info |
| --- | --- |
| antd | 5.2.3 |
| React | 18.2.0 |
| System | - |
| Browser | Chrome |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#how-do-i-prevent-select-dropdown-datepicker-timepicker-popover-popconfirm-scrolling-with-the-page
