### ISSUE TITLE
Select 文档描述错误

### ISSUE THREAD

**Issue by Raaabbit** [ant-design/ant-design#41795]
### What problem does this feature solve?
避免 Select 组件 showArrow参数的误用
在最新的 antd 5.x，Select组件支持在默认情况下无论多选还是单选都展示下拉箭头
参考源码：[https://github.com/ant-design/ant-design/blob/master/components/select/useShowArrow.ts](https://github.com/ant-design/ant-design/blob/master/components/select/useShowArrow.ts)
而在官网文档中，showArrow 这个属性的默认值描述为“单选为 true，多选为 false”
详见：[https://ant-design.gitee.io/components/select-cn#select-props](https://ant-design.gitee.io/components/select-cn#select-props)

### What does the proposed API look like?

期望更正官网文档，showArrow 默认值为 true

**Comment by yoyo837** [comment]
#41028 5.3.0+变更的逻辑. 漏改文档
