### ISSUE TITLE
Table 组件 filter dropdown 错位：当父元素设置 transform: scale 且 Table 组件设置 getPopupContainer

### ISSUE THREAD

**Issue by SADYX** [ant-design/ant-design#41791]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lperm1)

### Steps to reproduce

1. Table组件父元素设置transform: scale(x)
2. 为Table组件设置 getPopupContainer

### What is expected?

filter dropdown位置正确

### What is actually happening?

filter dropdown位置不正确

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | Windows 10 |
| Browser | Chrome 111 |

**Comment by Yuiai01** [comment]
本来应该在红色方框这的，确实存在问题
![image](https://user-images.githubusercontent.com/112228030/231746651-03cb07d5-3a4c-46f0-961f-b642d2a93226.png)

**Comment by MadCcc** [comment]
等 Dropdown 底层替换为 `@rc-component/trigger` 就可以了

**Comment by elvira1112** [comment]
@MadCcc Menu 也有同样的问题，好像没解决
https://codesandbox.io/s/antd-reproduction-template-forked-w7mobu?file=/index.js
