### ISSUE TITLE
ant design 的树形组件（可搜索的demo）会报错

### ISSUE THREAD

**Issue by Mrwans** [ant-design/ant-design#4179]
warning.js:45Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Test`.
这是报错的提示，我查了一下貌似是循环引用了某个模块，麻烦您看下

**Comment by ddcat1115** [comment]
官网未能重现，麻烦提供可重现的demo

**Comment by afc163** [comment]
给出重现再 reopen。

![](https://zos.alipayobjects.com/rmsportal/VdwiVSnBQQQVdBIFengm.png)
