### ISSUE TITLE
Transfer 穿梭框分页 SizeChanger 无效且缺少左右 padding 样式

### ISSUE THREAD

**Issue by YMNNs** [ant-design/ant-design#41790]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fen-ye-pagesizeqie-huan-wu-xiao-antd-5-4-2-forked-e2vksi)

### Steps to reproduce

1. 为 Transfer 组件设置 `pagination={{ showSizeChanger: true, simple: false }}`

### What is expected?

1. `pagination` 右侧距离 `Transfer` 右侧边框有 `padding`
2. `SizeChanger` 可以正确切换每页数量

### What is actually happening?

1. 发现 `pagination` 右侧紧贴 `Transfer` 右侧边框
2. 发现 `SizeChanger` 打不开或打开后无法选择任何选项

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 112 |

---
1. 在某些情况下 `SizeChanger` 可以打开但选择具体数量后并未改变
2. `PaginationType` 中没有类似 `onPageSizeChange` 的函数也就无法控制 `pageSize` 的值
3. `SizeChanger` 打不开在 `react-grid-layout` 中单独使用 `Pagination` 时也会出现，暂时无法复现

**Comment by Yuiai01** [comment]
这样就可以弹出来了，确实是存在问题
![image](https://user-images.githubusercontent.com/112228030/231744084-a0d4b757-c483-420e-ab9c-595809ef9602.png)

**Comment by Yuiai01** [comment]
找到原因了， 是因为有一个 `overflow: hidden` 属性将其隐藏了

**Comment by Yuiai01** [comment]
![image](https://user-images.githubusercontent.com/112228030/231911776-b3694a47-7ae7-4cc2-b762-bd99d2bc4773.png)

**Comment by Yuiai01** [comment]
我来提个 pr 修复一下～

**Comment by YMNNs** [comment]
> 找到原因了， 是因为有一个 `overflow: hidden` 属性将其隐藏了

没错，我尝试对css做出下面的修改可以解决样式问题

```diff
/* 解决SizeChanger打不开的问题 */
.ant-transfer-list-body {
+   overflow: visible;
}

/* 解决边距问题 */
.ant-transfer .ant-transfer-list-pagination {
+   padding: 8px;
}
```

![image](https://user-images.githubusercontent.com/10176553/231923541-daaa9ab8-3ef7-43ab-b34e-684a7f1d1a57.png)

但是当选中任何 `pageSize` 选项时每页的数量并不会改变，并且选中的选项也没有正确回填到下拉框中。这个问题暂时没有找到原因。

**Comment by Yuiai01** [comment]
这个地方看了一下得重构一波，我来跟一下吧~
