### ISSUE TITLE
Table 组件，state 更新的时候不会同步更新使用 render 参数的列，导致此列数据不同步。

### ISSUE THREAD

**Issue by netskyline** [ant-design/ant-design#418]
Table 组件，state 更新的时候不会同步更新使用 render 参数的列。

也可以这么说，Table 组件只在页面刷新的时候调用了 render 参数指定的方法进行渲染，state 更新的时候没有重新调用这个方法，导致数据不同步，显示的还是上一次的数据。

同这个问题 #366

**Comment by afc163** [comment]
更新什么 state 的时候，数据未更新。有例子就好了。

**Comment by afc163** [comment]
http://ant.design/components/tree/#demo-special

**Comment by pmtao** [comment]
这个代码示例中有类似的Table 组件 state 更新问题：[官方 Table  筛选和排序示例](http://jsbin.com/nocige/edit?js)

在这个例子中，分页、筛选、排序时触发的 onChange 事件内部，调用 this.setState ，用来设置在筛选状态下“姓名”标题旁显示一个漏斗图标。

但是在 onChange 触发 this.setState 更新后，筛选出的表格数据仍然是原数据无变化。如果去掉 this.setState 部分，筛选又能起作用。

麻烦看下这是什么问题造成的。

**Comment by afc163** [comment]
@pmtao 搞个可以看的例子吧，http://jsfiddle.net/yiminghe/9zrstuto/1/

**Comment by pmtao** [comment]
@afc163 不好意思，在线编辑器用的还不太熟。

演示如下：[Table 筛选和排序示例](http://jsfiddle.net/pmtao/nn9xf5y8/1/)

将 this.setState 部分注释后，筛选又能起作用。

**Comment by afc163** [comment]
可以先把 columns 移出 render 来解决，修复代码：http://jsfiddle.net/nn9xf5y8/3/

columns 的修改可能有点问题，我还要在看下。

**Comment by baizn** [comment]
更新了Table的数据列表，render里面的子组件没有更新，还是使用上一次Table的数据。
另外render里面不放子组件，只方式编辑按钮，要调用modal，该如何操作呢？

**Comment by baizn** [comment]
貌似render里面的子组件只会渲染一次，以后都不会进去到子组件里面

**Comment by baizn** [comment]
解决方法：使用props传数据到子组件中，子组件中改变值后使用onChange事件监听，将子组件可以改变的数据（如表单中的数据）作为state，通过setState改变其状态，提交表单时候将props和子组件的state合并，经测试，子组件中的数据得到了更新。
该问题并不是组件本身的问题，而是由于对react的state及props理解不透彻导致。

**Comment by afc163** [comment]
:+1:
