### ISSUE TITLE
Notification 参数问题

### ISSUE THREAD

**Issue by ThorSmallice** [ant-design/ant-design#41804]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-sn4nok?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

  const [api, contextHolder] = notification.useNotification(); 
api.info({
top:200
}),

### What is expected?

top值生效

### What is actually happening?

top值不生效

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 17.0.2 |
| System | windows11 |
| Browser | Chrome 111.0.5563.65（正式版本） （64 位） |

**Comment by MuxinFeng** [comment]
跟这个一样，我再看下吧 https://github.com/ant-design/ant-design/issues/41719

**Comment by ThorSmallice** [comment]
> 跟这个一样，我再看下吧 #41719

     style: { bottom: 240 } ，如果用这种方法，它是设置的内部的div的bottom, 最外层容器位置不变，会挡住原本我要显示的元素

**Comment by zombieJ** [comment]
Top 是配置参数，不是调用参数：https://codesandbox.io/s/hooks-diao-yong-tui-jian-antd-5-4-5-forked-xkg5qv?file=/demo.tsx
