### ISSUE TITLE
Can't cancel modal body's padding

### ISSUE THREAD

**Issue by rick-chou** [ant-design/ant-design#41805]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-4-2-forked-2cks0c?file=/demo.tsx)

### Steps to reproduce

set bodyStyle={{ padding: 0 }}

### What is expected?

I used to customize padding this way in the past, but it doesn't seem to work recently.
And I don't want to override antd's css style through global css

### What is actually happening?

/

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

---
/

**Comment by MadCcc** [comment]
Modal style is updated in v5, and `bodyStyle` will not work, it should be deprecated.
Now the padding is on `ant-modal-content` element, which makes Modal whole.

**Comment by shkhaksar** [comment]
You can use this code to modify content style:
```
 <Modal
        modalRender={(modal) => {
          return React.cloneElement(modal, {
            style: { ...modal.props.style, ...{ borderRadius: 0, padding: 0 } },
          });
        }}
 </Modal>
```

**Comment by seemamathiyarasu** [comment]
> style: { ...modal.props.style, ...{ borderRadius: 0, padding: 0 } },

not working

**Comment by dipakpatil5050** [comment]
Yes it's working to set padding 0 In Ant Design Modal ,

set bodyStyle={{ padding: 0 }}

**Comment by dipakpatil5050** [comment]
![image](https://github.com/user-attachments/assets/e729df74-2b83-4f3d-9f9a-2d1e87155b17)
