### ISSUE TITLE
When showCount and extra are used in TextArea, they are overlapped

### ISSUE THREAD

**Issue by StubbornDeer** [ant-design/ant-design#41802]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nest-antd-5-4-2-forked-133y0g)

### Steps to reproduce

1. Add the form with a text area
2. Set up long "extra" and function for showCound

### What is expected?

The showCount element should be shown as it was shown in the previous versions, in a separate block. Instead, it's rendered wrong with overlapping the extra text.

### What is actually happening?

Not sure, but it looks like the developers moved the extra from "after" to some other element and it just doesn't work correctly when "extra" is used too.

| Environment | Info |
| --- | --- |
| antd | 5.0.1, 5.4.2 |
| React | 18 |
| System | Windows 7 |
| Browser | Chrome 109.0.5414.120  |

Note. First, I found this issue in 5.0.1.

---
Anyway, Ant.design is really great framework!

**Comment by afc163** [comment]
<img width="671" alt="图片" src="https://user-images.githubusercontent.com/507615/231963395-a1dbd00c-d9b6-4df1-a100-7953ffeeced0.png">

I can't reproduce it in your sandbox.

**Comment by StubbornDeer** [comment]
> 
> 
> I can't reproduce it in your sandbox.

I'm sorry I probably forgot to add the code. Please see the updated code now, it looks like this:

![image](https://user-images.githubusercontent.com/91156314/232114305-dca8b60b-13bd-4ffe-97bf-ec4f3b70e53c.png)

**Comment by StubbornDeer** [comment]
You don't plan to fix the bug? Why? And may some human look into it and decide if it's planned or not? Many thanks.

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/29709 , you can trace it.
