### ISSUE TITLE
Upload Component CustomRequest onSuccess function not render file status

### ISSUE THREAD

**Issue by SageJustus** [ant-design/ant-design#41807]
### Reproduction link

[https://github.com/SageJustus/question/blob/main/demo3/src/App.tsx](https://github.com/SageJustus/question/blob/main/demo3/src/App.tsx)

### Steps to reproduce

1. 点击上传按钮，上传一个图片文件
2. 数据上文件状态已经是完成了`file.status='done'`，但实际上页面没有渲染。

![屏幕截图 2023-04-14 142617](https://user-images.githubusercontent.com/39724295/231961548-c383f576-c1a1-4cba-9b54-91b299a8b8e5.png)

### What is expected?

文件名高亮为蓝色

### What is actually happening?

文件名为黑色

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | 110.0.5481.178 |

**Comment by MadCcc** [comment]
需要有 url 才能展示为链接
