### ISSUE TITLE
cascader组件，expandTrigger="hover"，changeOnSelect="true"，导致在使用搜索功能时，聚焦返回的列表项时，会异常定位到最开始那项

### ISSUE THREAD

**Issue by Yyutaa** [ant-design/ant-design#41806]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ze-ji-gai-bian-antd-5-4-2-forked-nfe55w)

### Steps to reproduce

cascader组件，expandTrigger="hover"，changeOnSelect="true"，导致在使用搜索功能时，聚焦返回的列表项时，会异常定位到最开始那项

### What is expected?

能正常选择或聚焦返回的列表项

### What is actually happening?

异常定位到列表的最开始那一项

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 17.0.1 |
| System | mac |
| Browser | 谷歌浏览器 |

**Comment by afc163** [comment]
能给出手把手的重现步骤么，我没太理解具体是什么异常？

**Comment by Yyutaa** [comment]
> 能给出手把手的重现步骤么，我没太理解具体是什么异常？
打开我上面给的链接，在组件搜索框输入“wo”，下面会出现搜索列表，然后往下拉，鼠标移到具体某一项，这个时候就会重新定位到最开始那项，你可以在我给的demo.tsx文件里面试下

**Comment by afc163** [comment]
确实。

**Comment by Yyutaa** [comment]
> 

所以我现在只能将expandTrigger改为“click”的交互方式

**Comment by crazyair** [comment]
https://github.com/react-component/cascader/pull/532

**Comment by zmhweb** [comment]
请问这个是不是只修复了5的版本，4的版本还没修复？
