### ISSUE TITLE
Linux icon is till missing

### ISSUE THREAD

**Issue by ShiftcodeDream** [ant-design/ant-design#41819]
### What problem does this feature solve?

Linux icon is still missing, and WE NEED IT ! All cases about this are closed, so I open a new case.

### What does the proposed API look like?

Linux icon is still missing, and WE NEED IT !

**Comment by afc163** [comment]
<img width="496" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/47dd78fd-cdd6-444d-9f18-32b32bcbcae5">
