### ISSUE TITLE
Table  pagination 远程翻页  onShowSizeChange  总是返回1

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#41813]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yuanchengjiazaishuju-ant-design-demo-7y2uf?file=/index.js)

### Steps to reproduce

切换pageSize 从 10/页 到 20 /页, 发现还是10/页

### What is expected?

20 /页

### What is actually happening?

10 /页

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome |

---
实际onShowSizeChange: (val) => {
            console.log('val', val) // 总是1
            
          },

**Comment by afc163** [comment]
官网看上去没问题，可以参考一下这里的写法：

https://codesandbox.io/s/e46uxh?file=/index.tsx
https://4x.ant.design/components/table-cn/#components-table-demo-ajax

**Comment by vaynevayne** [comment]
好了, 是我类型看错了, onShowSizeChange,第二个参数才是pageSize, 惯性思维了

另外问一下, 关于 pagesize改变时,page 是否需要回到第一页?  你们推荐哪一种?  @afc163

**Comment by vaynevayne** [comment]
另外 这是bug吗?
当我从 page:2 pageSize:30 切换到 pageSize:10 时,我顺便重置page为1, 但是page没回到1, page仍然是2


```jsx
  const [pagination, setPagination] = useSetState({
    page: 1,
    perPage: 30,
  })
  console.log('pagination', pagination)

    pagination={{
          total: res?.data.total,
          current: pagination.page,
          pageSize: pagination.perPage,
          onChange(page, pageSize) {
            console.log('onChange', page, pageSize)

            setPagination({ page })
          },
          onShowSizeChange(current, size) {
            console.log('onShowSizeChange', current, size)

            setPagination({ perPage: size, page: 1 })
          },
        }}
```

<img width="488" alt="image" src="https://user-images.githubusercontent.com/124666577/231985439-7fd95a93-82cf-4fe3-881e-ccaebf878a70.png">

**Comment by afc163** [comment]
这个看需求，有些人希望回到第一页，有些希望不变，最好应用层自行控制。

**Comment by vaynevayne** [comment]
@afc163  好兄弟, 帮忙看看, 
貌似 缺少单纯的 onPageChange prop,   所以没办法做到回到第一页
目前只能我使用onChange, 结合useRef 记录pageSize 来做回到第一页
