### ISSUE TITLE
useContext error as soon as I am using any Ant Design component

### ISSUE THREAD

**Issue by VanshSh** [ant-design/ant-design#41824]
### Reproduction link

[https://github.com/VanshSh/next-valid-date](https://github.com/VanshSh/next-valid-date)

### Steps to reproduce

npm run start

### What is expected?

Checkbox be visible on the load but it is not showing

### What is actually happening?

Error 

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Window |
| Browser | Chrome |

**Comment by VanshSh** [comment]
Issue resolved

**Comment by aliciafdezrov** [comment]
> Issue resolved

I'm facing a similar issue, how did you manage to resolve it?

**Comment by VanshSh** [comment]
@aliciafdezrov 
I was making a very silly mistake I was not installing the dependencies properly.

**Comment by aliciafdezrov** [comment]
@VanshSh In my case, it was due to the use of an internal library whose version of React conflicted with that of the project itself, unrelated to antd. In any case, thank you very much for your response; it helped me rule out possibilities.
