### ISSUE TITLE
Type 'number' is not assignable to type 'IntRange<1, 59> | undefined'. for RangePicker

### ISSUE THREAD

**Issue by kirill-linnik** [ant-design/ant-design#41834]
### Reproduction link

[https://github.com/kirill-linnik/react-redux/blob/main/src/pages/MainPage.tsx](https://github.com/kirill-linnik/react-redux/blob/main/src/pages/MainPage.tsx)

### Steps to reproduce

in the link brough, please, look at line 59:
<RangePicker minuteStep={5} />

that gives an error:
No overload matches this call.
  Overload 1 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any> & CommonPickerMethods', gave the following error.
    Type 'number' is not assignable to type 'IntRange<1, 59> | undefined'.
  Overload 2 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any>', gave the following error.
    Type 'number' is not assignable to type 'IntRange<1, 59> | undefined'.ts(2769)

![image](https://user-images.githubusercontent.com/15168102/232290155-8430aa2b-d0f1-4bb3-adbf-20fb014002dc.png)

### What is expected?

no error :)

### What is actually happening?

error :))

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18 |
| System | any |
| Browser | any |

**Comment by zombieJ** [comment]
It's from TimePicker.RangePicker not DatePicker.RangePicker. Or set prop `picker` to `time` will see the `minuteStep`.

**Comment by kirill-linnik** [comment]
> It's from TimePicker.RangePicker not DatePicker.RangePicker. Or set prop `picker` to `time` will see the `minuteStep`.

Sorry, but I want date and time pricker, not just a time picker. Therefore, I use `DatePicker.RangePicker`, and it used to work prior 5.4.2.

**Comment by xxKeefer** [comment]
I am finding this bug when trying to follow the [5.13.3 docs](https://ant.design/docs/react/use-custom-date-library#timepickertsx) for converting the timepicker to use date-fns. it breaks the hour, minute and second step params
