### ISSUE TITLE
`Form.List`获取`Upload fileList`出现`undefined`

### ISSUE THREAD

**Issue by zhaozkTHU** [ant-design/ant-design#41836]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-evr6t0)

### Steps to reproduce

实现了一个`Form`组件来获取`Upload`中的`fileList`，但按照官网示例，无法复现。

`onChange`中显示，`Upload`中存在`fileList`，`Form.Item`却无法捕获

<img width="288" alt="image" src="https://user-images.githubusercontent.com/92924106/232320053-aad318a4-ff1c-4f26-bf38-fa311a6f8ad1.png">

### What is expected?

显示正确的`fileList`

### What is actually happening?

`undefined`

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18 |
| System | windows |
| Browser | Chrome |

**Comment by afc163** [comment]
你给的例子里没有 Form.List ？

**Comment by zhaozkTHU** [comment]
写错了，是`Form.Item`没有捕获到`Upload`中的`fileList`

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-irqrd8?file=/index.js

有个例子漏了 getValueFromEvent，我补一下。

**Comment by zhaozkTHU** [comment]
如果使用ts，如何判断`getValueFromEvent`的类型呢？好像看起来像是`import type { UploadChangeParam } from "antd/es/upload"`这个类型，但该类型不可能是`Array`

**Comment by zhaozkTHU** [comment]
还有在例子中删去`valuePropName="fileList"`仍有一样的结果
