### ISSUE TITLE
Deprecated Warning Message Input.Group with nested form items

### ISSUE THREAD

**Issue by devcaco** [ant-design/ant-design#41830]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zj990h?file=/demo.js)

### Steps to reproduce

In a Controlled form with nested Form Inputs inside Input.Group. -> Code from the Complex Form Control in the antd form documentation

### What is expected?

No Warnings or Error Messages

### What is actually happening?

Getting a Deprecated Input.Group warning message and to use Space.Compact instead. The problem is that if I use Space.Compact it doesn't support Form.Items

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | MacOs Monterrey 12.6 |
| Browser | Chrome@Latest |

---
I followed the instructions in the antd documentation for Complex Form Control and the same thing happens.

**Comment by zombieJ** [comment]
Your reproduce work as expect when replaced to `Space.Compact`: https://codesandbox.io/s/complex-form-control-antd-5-4-2-forked-71lxo4?file=/demo.js
