### ISSUE TITLE
ant-design样式错位了

### ISSUE THREAD

**Issue by hawx1993** [ant-design/ant-design#4183]
>ant-design样式错位了

正常显示应该如下：

![d091918f-b002-49eb-974a-9e555d51185e](https://cloud.githubusercontent.com/assets/5305263/20996029/a4d48df0-bd35-11e6-8fd3-01d1c9b27613.png)

当你滚动页面而没有让他失去焦点的时候：
![9e53a2aa-542c-47da-87db-ec6d610229a6](https://cloud.githubusercontent.com/assets/5305263/20996005/88f1baea-bd35-11e6-8f36-f52cd03cd365.png)

不仅仅Tooltips组件有这样的问题，很多组件都有这样的问题，希望可以尽快解决啊。还有我们现在在用的是1.70版本，发现最新的2.5.1版本很多样式都改了，怕用户会不习惯，希望可以提供原来的样式

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3487
