### ISSUE TITLE
给input Number组件添加一个错误提示信息

### ISSUE THREAD

**Issue by shiwofeiwo** [ant-design/ant-design#41843]
### What problem does this feature solve?

比如formItem管理了一个inputNumber组件时，当我在inputNumber输入字符串时，能够提示一些自定义的错误提示，目前的效果只是inputNumber不接收字符串，没有错误提示

### What does the proposed API look like?

在inputNumber输入时，即使输入字符串也能触发formItem的rules

**Comment by afc163** [comment]
<img width="360" alt="图片" src="https://user-images.githubusercontent.com/507615/232426764-e6c17a2c-0653-40b5-97b3-44fb0731d13a.png">

直接用 Form 提供的错误提示是不是就可以了。

**Comment by zombieJ** [comment]
InputNumber 会确保 `onChange` 事件返回的是数字类型，如果你需要非标内容做控制可以 HOC 一下用 `onInput` 获取完整内容。
