### ISSUE TITLE
Dropdown menu behave inverted when css hashes are disabled in nextjs app dir

### ISSUE THREAD

**Issue by Skyriis** [ant-design/ant-design#41841]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/weathered-browser-1750b6?file=%2Fapp%2Flayout.tsx)

### Steps to reproduce

1. Start a NextJS Project with App dir
2. Setup Antd and Static Style Extract Script
3. disable `hashed` option in css gen script and root layout config provider
4. Add Dropdown Menu
5. Hover over the Menu
6. Hover away from the Menu

For Codesandbox.io minimal reproduction: Please change the port of the preview url from 3001 to 3000

### What is expected?

Open the Menu when hover above the menu and closing the menu when hovering away

### What is actually happening?

Open the Menu when hover away from the menu and closing the menu when hovering over it

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 112.0.5615.50 |

---
Please change the port of the preview url from 3001 to 3000. I'm using a NextJS production build for the minimal reproduction due to the limited resources in codesandbox.io

**Comment by afc163** [comment]
There is no `hashed` config in ConfigProvider accroding to officail documentation: https://ant.design/docs/react/customize-theme

**Comment by Skyriis** [comment]
Yeah it looks like it is missing on the documentation but exists for sure. I already run into an other issue in #41777 where is forgot to disable `hashed` at static style extract and at runtime.

**Comment by MadCcc** [comment]
`hashed` is re commended to be `true` since it may cause theme mixed up when turned to `false`.
That why it was not included in the document.

**Comment by MadCcc** [comment]
Seems animation didn't generated correctly.

**Comment by zombieJ** [comment]
Do not import from `antd/lib`. Your ConfigProvider from `antd` path and Dropdown from `antd/lib` path which is not the same in NextJS. Import from same one instead:

```diff
-- import { ConfigProvider, Space } from "antd";
-- import { Dropdown } from "antd/lib";
++ import { ConfigProvider, Space, Dropdown } from "antd";
```

https://codesandbox.io/p/sandbox/antd-dropdown-issues-forked-63pszx?file=%2Fapp%2Flayout.tsx%3A8%2C1
