### ISSUE TITLE
Reduce unused CSS

### ISSUE THREAD

**Issue by fakehungry** [ant-design/ant-design#41840]
### What problem does this feature solve?

Hi, I'm looking for how to reduce unused CSS after build. I try this option, https://purgecss.com/ant_design.html, it can reduce the css but the styles got weird.

### What does the proposed API look like?

What I'm looking for is how to reduce unused 'ant' class in css files. ~90% of it is unused. Appreciate if you can help me.

**Comment by Wxh16144** [comment]
5.x uses css in js, there are no more .css style files

**Comment by zombieJ** [comment]
Thanks for feedback. As @Wxh16144 said, it's not a question in v5 anymore.

**Comment by fakehungry** [comment]
@Wxh16144 & @zombieJ , Thanks for quick response. Now, I trying to migrate v4 to v5 as guide, https://ant.design/docs/react/migration-v5. In v4, I use less file as below
```
@import '~antd/lib/style/themes/default.less';
@import '~antd/dist/antd.less';
```
After I upgrade to v5, i remove those line and some styles differ from original. Then, I try to build the app but it got error with onClick props in my custom div.

Can you guide me how to setup the project?
