### ISSUE TITLE
chrome的密码自动填充第二次才能submit成功

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#41859]
### Reproduction link

[https://ant.design/components/form-cn](https://ant.design/components/form-cn)

### Steps to reproduce

填充基本的例子，然后点击chrome保存密码
刷新页面，chrome会自动填充(视觉上
打开dev tools，点击submit
会发现 fail 一次，再点击才会成功

### What is expected?

第一次点击即可成功

### What is actually happening?

会发现 fail 一次，再点击才会成功

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 17.0.3 |
| System | win10-64bit |
| Browser | chrome 103 |

---
这个有可能会触发，也有可能不触发，大概率第一次测试的时候会触发。所以麻烦多试一下，不行清空缓存再刷页面

**Comment by yoyo837** [comment]
这个应该antd无关吧?

**Comment by yoyo837** [comment]
按步骤操作不出来

**Comment by yoyo837** [comment]
> 填充基本的例子，然后点击chrome保存密码

这一步就操作不出来

**Comment by cangSDARM** [comment]
![image](https://user-images.githubusercontent.com/20441896/233239789-04486883-371b-4e1b-b15b-de336fc8d81d.png)
6. 看bug复现

**Comment by yoyo837** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/6134547/233240098-fdbcaff0-e454-4a03-86a5-b8d8874704cd.png">

一次得到, 无法复现
