### ISSUE TITLE
Select 支持 addon

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#4186]
类似 Input 的 `addonBefore` `addonAfter`

https://ant.design/components/input/#components-input-demo-addon

**Comment by benjycui** [comment]
其实我觉得实现一个容器组件更靠谱：

```jsx
<Container addonBefore={...} addonAfter={...}>
  <Select />
</Container>

<Container addonBefore={...} addonAfter={...}>
  <Input />
</Container>
```

不然以后就有一大堆组件有 `addonBefore` `addonAfter` 属性了。

**Comment by benjycui** [comment]
或者可以直接做进 `Input.Group` 里面？

现在的 Input.Group 是很鸡肋的存在 https://ant.design/components/input/#components-input-demo-group

**Comment by afc163** [comment]
我觉得 Input.Group 可以试试。

**Comment by ddcat1115** [comment]
根本需求是要把两个及以上的 Select 『无缝』拼到一起，用 InputGroup 实现了

**Comment by CoderPoet** [comment]
input.group还是不错的，在某些特定布局需求上
