### ISSUE TITLE
Paragraph自定义symbol省略时显示的行数不正确

### ISSUE THREAD

**Issue by datoou** [ant-design/ant-design#41861]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sheng-lue-hao-antd-5-4-2-forked-1u466k?file=/demo.tsx:213-217)

### Steps to reproduce

修改symbol

### What is expected?

正确显示行数

### What is actually happening?

不正确显示行数

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.0.0 |
| System | windows 11 |
| Browser | edge |

**Comment by zombieJ** [comment]
行数计算是基于基本行高，展开按钮高于1行则会认为是跨行的。这个不好解。
