### ISSUE TITLE
V5版本自定义表单组件value和onchange丢失

### ISSUE THREAD

**Issue by guoshijie1990** [ant-design/ant-design#41862]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nuox9g)

### Steps to reproduce

打印form finish的value，是空的。
自定义组件里面打印props，也取不到value和onchange

### What is expected?

value和onchange可以透传给自定义组件

### What is actually happening?

value和onchange没有透传给自定义表单组件

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.0.37 |
| System | mac oc |
| Browser |  112.0.5615.49（正式版本） (x86_64) |

---
上面这个连接是官网示例，也是不好使的。

**Comment by guoshijie1990** [comment]
![image](https://user-images.githubusercontent.com/5399019/232721649-a3190c74-81a2-40d4-ac55-a4dc3f4282f9.png)

**Comment by zombieJ** [comment]
<img width="423" alt="截屏2023-04-18 16 43 16" src="https://user-images.githubusercontent.com/5378891/232723086-fa572886-745b-4ad0-a1f7-66bc658f88f5.png">

**Comment by guoshijie1990** [comment]
一个逗号引发的血案！，子组件后面不小心加上了个逗号，就像下面这个例子
`<Form.Item
          name={ 'test'}
          label=""
        >
          <Test /> ，
        </Form.Item>`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/41771#discussion_r1163894341 @zombieJ
