### ISSUE TITLE
notification content won't be captured by storycap visual regression test

### ISSUE THREAD

**Issue by Gfast2** [ant-design/ant-design#41864]
### Reproduction link

[https://github.com/Gfast2/ant_design_notification_storybook_storycap_visual_regression_test](https://github.com/Gfast2/ant_design_notification_storybook_storycap_visual_regression_test)

### 1. init project

After checkout repo.

```sh
npm install
```

### 2. start storybook dev server

```sh
npm run storybook
```

### 3. run visual regression test

```sh
npm run storycap
```

After this step, you may got newly created png file under `/.reg`. You can tell from the image all the element are captured in the file except the notification itself.

### What is expected?

the notification should be in the captured image.

### What is actually happening?

the notification isn't in the captured image.

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.2.0 |
| System | Ubuntu 20.04.6 LTS x86_64 |
| Browser | Chrome 112.0.5615.49 |

---
We've tried other approaches which will trigger notification as well (like do it directly by calling `notification({message: ''message content})`). Still we won't be able to capture it.

**Comment by MadCcc** [comment]
Not familiar with storybook, if it capture screen on page mounted, there will be animation before Notification shows up.
