### ISSUE TITLE
能否通过配置Menu组件API的方式支持subMenu选中？

### ISSUE THREAD

**Issue by yu244** [ant-design/ant-design#41865]
### What problem does this feature solve?

我通过Menu 的 items（树形数据）生成菜单节点，onClick 和 onSelect 不会在 subMenu 的节点上触发，如果想选中 subMenu 只能通过给每个 items 绑定 onTitleClick 获取点击的 key，然后修改 Menu 的 selectedKeys 去实现 subMenu 选中。

疑问：
1. 默认 subMenu 无法单独选中是预期还是bug？（毕竟 selectedKeys 和 onClick 的 keyPath 都包含了 subMenu 的 key）
2. 能否新增API支持 subMenu 单独选中？

例：  
https://ant.design/components/menu-cn#components-menu-demo-vertical
  Menu 组件垂直菜单 Navigation Two 中第三项 subMenu 没办法单独选中，只能选中第三层级中的 menuItem 来激活 subMenu 的单独选中。

### What does the proposed API look like?

在 Menu API 中新增配置 支持 subMenu 选中

**Comment by afc163** [comment]
> 默认 subMenu 无法单独选中是预期还是bug？（毕竟 selectedKeys 和 onClick 的 keyPath 都包含了 subMenu 的 key）

这是预期行为，subMenu 在设计中就只有展开的行为，没有叠加选中行为。
