### ISSUE TITLE
RangePicker default error

### ISSUE THREAD

**Issue by anurag835** [ant-design/ant-design#41867]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-antd-css-import-forked-qz9ocn?file=/src/index.js)

### Steps to reproduce

1. add disableDate prop to RangePicker component 
2. log the currentDate parameter in disableDate callback function. It is not the current date/time value.

### What is expected?

current date parameter in disableDate callback function should return the current date 

### What is actually happening?

current date parameter in disableDate callback function is returning inappropriate date, dates other than the current date/time value

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.2 |
| System | 22.04(Ubuntu) |
| Browser | 98.0.4758.102  |

**Comment by afc163** [comment]
`currentDate` means the current date of each date cell, not `Date.now()`.
