### ISSUE TITLE
Upload 组件的accept 设置 "text/plain", 无法拦截到csv和js文件

### ISSUE THREAD

**Issue by skyliusj** [ant-design/ant-design#41869]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-19hg6o?file=/index.js)

### Steps to reproduce

Upload 组件的accept 设置 "text/plain", 无法拦截到csv和js文件

### What is expected?

只能上传txt文件

### What is actually happening?

设置后，能上传txt以及csv和js文件

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | 1 |
| Browser | chrome |

**Comment by afc163** [comment]
这是原生 input file 的逻辑，antd 没有做什么特殊拦截。

**Comment by 624515059** [comment]
原生input设置text/plain后，禁止不了.csv和.js文件，应该是chrome最新版本的问题
