### ISSUE TITLE
Table filters tree and menu 提供开启虚拟滚动的开关

### ISSUE THREAD

**Issue by oushu1tanqiang1** [ant-design/ant-design#41879]
### What problem does this feature solve?

table filter 项目过多时卡顿

### What does the proposed API look like?

尽可能提供 tree 本身的 API？

 table filters tree 功能增强相关 issue：https://github.com/ant-design/ant-design/issues/32754

**Comment by afc163** [comment]
合并至 https://github.com/ant-design/ant-design/issues/41863
