### ISSUE TITLE
Tree 组件删除其中一个节点的时候页面会闪一下

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/ant-design#41878]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-4-2-forked-xn3nbd)

### Steps to reproduce

先展开所有节点，再点删除

### What is expected?

页面不会闪

### What is actually happening?

页面会闪

https://user-images.githubusercontent.com/49217418/232949715-9576a5a0-2808-4377-974b-0fa5f1862f6a.mp4

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | mac |
| Browser | Chrome |

**Comment by afc163** [comment]
我怎么看到的视频是白的？

**Comment by li-jia-nan** [comment]
> 我怎么看到的视频是白的？

唉？看不到视频吗大佬？我发群里你看下

**Comment by afc163** [comment]
<img width="602" alt="图片" src="https://user-images.githubusercontent.com/507615/232975275-e7c6a1c1-8d04-4d91-8451-c4305967a5ae.png">

**Comment by afc163** [comment]
和 https://github.com/ant-design/ant-design/issues/27702 是同一个问题。

**Comment by GitHubJackson** [comment]
> 和 #27702 是同一个问题。

请问这个问题解决了吗？我用的 4.22.0 版本好像还是存在这个问题

**Comment by afc163** [comment]
有人看看这问题不。 @ant-design/ant-design-collaborators

**Comment by BoyYangzai** [comment]
@li-jia-nan @afc163  试了一下 好像只有当上层key的dom元素完全被移除的时候才会出现这种抖动
https://codesandbox.io/s/ji-ben-antd-5-4-2-forked-bbd1x7?file=/demo.tsx:658-664
只需要移除下面的dom元素 保证上方key的dom不变就不会出现这种情况

**Comment by NoDocCat** [comment]
@BoyYangzai 
我之前尝试分析的时候发现 rc-tree 不存在这个问题, 感觉样式的问题可能性更高一些. 
https://codesandbox.io/s/blissful-wing-mbq451?file=/App.jsx

**Comment by BoyYangzai** [comment]
> @BoyYangzai 我之前尝试分析的时候发现 rc-tree 不存在这个问题, 感觉样式的问题可能性更高一些. https://codesandbox.io/s/blissful-wing-mbq451?file=/App.jsx

我本地也试了一下 确实没有问题呜呜呜

**Comment by BoyYangzai** [comment]
@NoDocCat 排除法挨个试了一下
![image](https://github.com/ant-design/ant-design/assets/94534613/a010c8c1-a22e-4fb4-9519-0896308bd5f4)
是这个hashId的原因

**Comment by ayuan-gy** [comment]
motion动效先渲染旧值造成的问题。
![image](https://github.com/ant-design/ant-design/assets/82928935/918e2d9a-88d7-480d-b0e0-624057b815be)
在这一块中，transitionData是上一次的旧值，data是这一次的新值，导致渲染了旧的再渲染新的，所以造成了闪动。

**Comment by li-jia-nan** [comment]
https://juejin.cn/post/7231940493256998972

**Comment by xiaohuoni** [comment]
徒增一个烦恼 https://codesandbox.io/s/ji-ben-antd-5-4-2-forked-zsfrxl?file=/demo.tsx
![image](https://github.com/react-component/tree/assets/11746742/95e1175c-e35b-4e77-bb9e-0c47b2fb415c)

**Comment by afc163** [comment]
居然有这么多 PR 修这个问题。 @zombieJ @MadCcc 看看？
