### ISSUE TITLE
Input.Group[compact] 改成了 Space.Compact 组件UI有问题

### ISSUE THREAD

**Issue by ByYogi** [ant-design/ant-design#41876]
### Reproduction link
[![Edit on CodeSandbox](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/feedback-antd-5-space-compact-tewsj1?file=/demo.js)

![image](https://user-images.githubusercontent.com/111735598/232959395-da5a7583-c416-4371-a75b-6de88e6fa965.png)

### What problem does this feature solve?
使用`componentSize="large"`模式，Space.Compact 组件高度与宽度都没变化。
确保Space.Compact 与 Input.Group使用起来一样

### What does the proposed API look like?
期望Space.Compact的样式 与 Input.Group 基本一样，这样才好更迭
目前使用以下代码缓解，但是不适用`Select`
```jsx
<Space.Compact style={{ minHeight: 40, width: '100%' }}>
      <Input
        style={{ width: '50%' }}
      />
      <Input
       style={{ width: '50%' }}
      />
</Space.Compact>
```

**Comment by zombieJ** [comment]
@foryuki pls help on this

**Comment by Ec-tracker** [comment]
Can I work on it?

**Comment by afc163** [comment]
@Ec-tracker sure.
