### ISSUE TITLE
【BUG】select 的listItemHeight不生效

### ISSUE THREAD

**Issue by Lands-1203** [ant-design/ant-design#41886]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-4-2-forked-levrj3?file=/demo.tsx)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/61341868/233009482-1474fa44-74fd-41aa-8f77-4deb1ee94671.png)
![image](https://user-images.githubusercontent.com/61341868/233009588-397f2fad-4ad3-45ed-95d6-ea9fd07e5b10.png)

```
import React from "react";
import "./index.css";
import { Select } from "antd";

const option = [];
for (let i = 0; i < 1000; i  ) {
  option.push({
    value: `jack${i}`,
    label: (
      <div
        style={{
          width: 100,
          height: 50,
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          border: "1px solid red"
        }}
        >
        jack{i}
      </div>
    )
  });
}
const App: React.FC = () => (
  <Select
    style={{ width: 500 }}
    options={option}
    // listItemHeight 不管写多少永远只有6个 写0是全部
    listItemHeight={0}
    dropdownRender={(dom) => {
      return <div className="dropdown-render">{dom}</div>;
    }}
    />
);

export default App;




.dropdown-render .rc-virtual-list-holder-inner {
  flex-direction: row !important;
  flex-wrap: wrap;
}
.dropdown-render .rc-virtual-list-holder-inner > div {
  height: 60px;
  width: 110px;
  padding: 0;
}

```

### What is expected?

调整listItemHeight的值会生效

### What is actually happening?

调整listItemHeight的值不生效

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.0.28 |
| System | windows |
| Browser | google chrome |

**Comment by zombieJ** [comment]
[自定义样式](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-4-2-forked-levrj3?file=/index.css)就不要使用虚拟滚动了，直接使用 dropdownRender 按自己的需求来实现即可。
