### ISSUE TITLE
App.useApp().message 动态自定义主题样式有误

### ISSUE THREAD

**Issue by onlyling** [ant-design/ant-design#41885]
### Reproduction link

[https://onlyling.github.io/antd-cssinjs/#/antd](https://onlyling.github.io/antd-cssinjs/#/antd)

### Steps to reproduce

- 点击「TEST MESSAGE WIDTH APP」按钮
- 点击「token1」按钮（此时 message.info 的图标没有动态改变颜色，内部的按钮颜色显示正确）
- 点击「TEST MESSAGE WIDTH APP」按钮（此时 message.info 的图标和内部按钮的颜色显示正确）
- 点击「token reset 」按钮（此时第二个 message 位置错误，开发环境位置正常，图标没有动态改变颜色，内部的按钮颜色显示正确）

### What is expected?

弹出的 message.info 图标颜色可以动态跟随 token 变化而变化，和内部的按钮表现一致。

### What is actually happening?

message.info 在出现的情况下不能动态相应 token 变化。

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | ^18.2.0 |
| System | Mac OS 13.3.1  |
| Browser | Google Chrome 111.0.5563.146（正式版本） (arm64) |

---
具体代码：https://github.com/onlyling/antd-cssinjs/blob/main/src/modules/antd/index.tsx
主要是测试动态更新主题。

**Comment by zombieJ** [comment]
`className` 从 config 传过去的，要拆一下，我想想怎么搞。
