### ISSUE TITLE
npm安装后node_modules/antd/lib/menu/OverrideContext.d.ts:11:16 导出的OverrideContext未定义

### ISSUE THREAD

**Issue by senro** [ant-design/ant-design#41882]
### Reproduction link

[https://u.ant.design/codesandbox-repro](https://u.ant.design/codesandbox-repro)

### Steps to reproduce

npm安装antd@5.4.2
打开node_modules/antd/lib/menu/OverrideContext.d.ts:11:16 

export default OverrideContext; //OverrideContext未定义

### What is expected?

node_modules/antd/lib/menu/OverrideContext.d.ts:11:16 

export default OverrideContextProps; //应该是导出OverrideContextProps才对

### What is actually happening?

参看重现步骤

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 17.0.2 |
| System | mac os 12.6 |
| Browser | chrome |

**Comment by zombieJ** [comment]
default 没有导错，但是 OverrideContext 定义丢了。

**Comment by Wxh16144** [comment]
> default 没有导错，但是 OverrideContext 定义丢了。

跟进了一下这个问题, 本身 `OverrideContext` 被标记为 `@internal` , 应该就不期望开发者去使用这个 Context,  根本原因是在 tsconfig 中配置了 [stripInternal=true](https://www.typescriptlang.org/tsconfig#stripInternal)(默认是 false); 构建后 Context 就不会被打包进去了. 具体提交在 https://github.com/ant-design/ant-design/pull/37816 这里, 所以应该是没问题了.不算一个 bug 🤔

如果要解决这个报错, 我更倾向于在 export default 前加一个 `@internal` ;( 我猜测所有地方都应该在最终 export 的地方加 `@internal` 注释, 我可以整个项目检查一下

```tsx
/** @internal Only used for Dropdown component. Do not use this in your production. */
export default OverrideContext;
```
