### ISSUE TITLE
transfer组件为什么不提供监听 scroll事件的api呢

### ISSUE THREAD

**Issue by cqh2015** [ant-design/ant-design#4188]
如题

**Comment by benjycui** [comment]
使用场景？

**Comment by benjycui** [comment]
技术上可以支持，但是如果没有使用场景的话就没必要了吧。

先关，有合理的使用场景是可以 re-open。

**Comment by cqh2015** [comment]
这边的场景是，数据源需要和后台交互，且需要分页查询

**Comment by benjycui** [comment]
relative: https://github.com/ant-design/ant-design/issues/3705

Transfer 加了 onScroll 也不方便，用 加载更多按钮 也不适合。

还是加 onScrollToEnd 之类的方法吧。

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/pull/5084

只提供 `onScroll`，然后自行封装 `onScrollEnd` 即可。

**Comment by YaoKaiLun** [comment]
```
handleScroll = (direction, e) => {
   let target = e.target
   if (target.scrollTop + target.offsetHeight === target.scrollHeight) {
      // do something
   }
}
```
