### ISSUE TITLE
Cannot clear Select Component's value if it is within a Form.Item Component

### ISSUE THREAD

**Issue by Paper-Folding** [ant-design/ant-design#41889]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clear-antd-select-0190s9?file=/index.js)

### Steps to reproduce

Just click the "Clear Select" button, the select cannot be cleared 

### What is expected?

The select should be cleared.

### What is actually happening?

It appears that if set a `Select`'s `value` prop to `null`, the Select did not clear its value, this only happens when the Select is in a `Form.Item` Component, if a `Select` is not in that component, the `Select` can be cleared normally.

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Microsoft Edge 112.0.1722.48 |

**Comment by zombieJ** [comment]
When you set `name` on Form.Item, all the `value` is control by Form store:
https://codesandbox.io/s/clear-antd-select-forked-zezlzo?file=/index.js

If do not want to control by form, remove `name` instead.
