### ISSUE TITLE
Tree-select 样式错误

### ISSUE THREAD

**Issue by whyer11** [ant-design/ant-design#4189]
#### 发生问题的环境是：

- antd 版本:2.5.1
- 操作系统及其版本:Mac OS 10.12.1
- 浏览器及其版本: 这个bug跟浏览器没有关系

#### 您做了什么？请提供尽可能详细的重现步骤。

自己试试tree select loading data的时候什么样子

#### 您期待的结果是:

并且官网的treeselect的例子不全啊

#### 实际上的结果是:

样式错误

#### 可重现的在线演示

https://github.com/ant-design/ant-design/blob/master/components/tree-select/style/index.less#L63

这行 content的错了

**Comment by benjycui** [comment]
fix, thanks

**Comment by benjycui** [comment]
如果能这样使用，就能规避这些问题了。

```less
.iconfont-font('loading') 
```

但试了下，没找到可行的办法。
