### ISSUE TITLE
Button herf 属性的跳转能像umi那样流畅

### ISSUE THREAD

**Issue by Locter9001** [ant-design/ant-design#41897]
### What problem does this feature solve?

优化使用体验，去除顿挫感

### What does the proposed API look like?

使用 Button 的 herf 属性可以触发umi的跳转效果，又或者说可以用别的属性

**Comment by MadCcc** [comment]
```tsx
<Link>
  <Button>link</Button>
</Link>
```
你觉得不流畅只是因为没有走路由跳转
