### ISSUE TITLE
proposal: 文档样式调整

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#419]
现在文档 demo 部份的展开按钮，使用 `top: 50%` 进行定位。在说明过长的时候，位置有点奇怪，毕竟大多数人的阅读都是从左上到右下，所以把这个按钮定位在右下怎样？

现在：
![snip20151022_8](https://cloud.githubusercontent.com/assets/3580607/10660462/cd9cdca2-78d9-11e5-9eb4-762963986853.png)

建议：

![snip20151022_6](https://cloud.githubusercontent.com/assets/3580607/10660554/62b0117e-78da-11e5-81bf-e45aeafbe581.png)

**Comment by Chinglik** [comment]
可以的，我与工程师跟进下~谢谢建议哈！

**Comment by afc163** [comment]
搞定~
