### ISSUE TITLE
RangePicker中选择不超过七天范围的示例中组件宽度太小，无法看到准确日期的优化

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#41903]
### What problem does this feature solve?

https://4x-ant-design.antgroup.com/components/date-picker-cn/#components-date-picker-demo-select-in-range

上面是示例代码，但rangepicker的宽度太小，无法看到准确的日期，点开后又清空了日期，还是无法查看。

优化方案暂时也没有特别好的，建议在下拉框的日期上面加一个header部分，展示当前选中的日期。

现在虽然有renderFooter，但是和ranges不在一行，给人双下巴的感觉，丑的很。

### What does the proposed API look like?

renderExtraHeader=() => React.ReactNode

**Comment by afc163** [comment]
> 建议在下拉框的日期上面加一个header部分，展示当前选中的日期。

大概长什么样，我没有太理解到。

**Comment by qingfengmy** [comment]
算了，加大宽度是最简单的
