### ISSUE TITLE
Checkboxes in Tree component misaligned with node title

### ISSUE THREAD

**Issue by Semro** [ant-design/ant-design#41914]
### Reproduction link

[https://stackblitz.com/edit/react-pnnjcm?file=demo.tsx](https://stackblitz.com/edit/react-pnnjcm?file=demo.tsx)

### Steps to reproduce

Open any example with checkboxes from Tree component documentation: https://ant.design/components/tree

### What is expected?

Checkbox vertically aligned on the same level with node title

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/3332159/233451821-6d25ab7a-cc8c-4c55-9796-922219451a68.png)
  
</details>

### What is actually happening?

Checkbox has 4px margin from the top. Class `ant-tree-checkbox ant-tree-checkbox-checked`
<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/3332159/233450857-75296433-8977-4d11-a5cc-131e8cdd604e.png)
  
</details>

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18.2.0 |
| System | Linux 64-bit |
| Browser | Chrome Version 112.0.5615.121 (Official Build) (64-bit) |

---
It's regressed in antd v5.4.0
Example with antd v5.3.3 that works correctly: https://stackblitz.com/edit/react-fv5jpr?file=demo.tsx,package.json

**Comment by Yuiai01** [comment]
I figured out why. I'll try to fix it.
![image](https://user-images.githubusercontent.com/112228030/233509720-4ef4659e-0074-4b38-9cd0-177cc98778f7.png)
