### ISSUE TITLE
表单在label过多换行的时候，如果这时候有错误校验，会出现抖动现象

### ISSUE THREAD

**Issue by douzi8** [ant-design/ant-design#41917]
### Reproduction link

[https://stackblitz.com/edit/react-dvydy3?file=demo.tsx](https://stackblitz.com/edit/react-dvydy3?file=demo.tsx)

### Steps to reproduce

1. 出现表单校验， 页面抖动

### What is expected?

不抖动

### What is actually happening?

抖动了

| Environment | Info |
| --- | --- |
| antd | 5.4.3 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
https://stackblitz.com/edit/react-dvydy3?file=demo.tsx

**Comment by Wxh16144** [comment]
具体表现是怎么样的呢? 我这边没发现你说的抖动问题 🤔

https://user-images.githubusercontent.com/32004925/233795249-e3b4dbcc-bca6-44dd-9214-e32f092b489e.mp4

**Comment by lihansir** [comment]
我这边复现了😱 @Wxh16144 
https://user-images.githubusercontent.com/44010674/233816793-f59d2c31-a312-4476-a897-960b2c9cd3ca.mp4

**Comment by lihansir** [comment]
貌似是左边 label 的 padding 导致两个 form-item 间距变大。我把 padding 去掉后没有出现抖动
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/44010674/233817000-b5262213-04a3-4e4b-a067-e014f0fdff2e.png">

**Comment by Wxh16144** [comment]
嗯嗯, 确实有你反馈的这个问题, 我跟踪一下

**Comment by zombieJ** [comment]
配置的 `flex` 没有考虑响应式问题，使得 `< 575px` 的时候原本的折行变成了内联，但是 `padding` 还在。一起干掉就好了：https://stackblitz.com/edit/react-dvydy3?file=index.css,demo.tsx
