### ISSUE TITLE
Antd: custom theme not working with NextJS 13 and appDir enabled

### ISSUE THREAD

**Issue by okarook** [ant-design/ant-design#41919]
### Reproduction link

[https://github.com/okarook/antd-nextjs-13](https://github.com/okarook/antd-nextjs-13)

### Steps to reproduce

Run the following commands:
> `npm i`

> `npm run dev`

### What is expected?

The app should open in the browser and show the primary color of the button in red because that's how it's configured in the custom theme.

### What is actually happening?

The color of the button is not red, it has the primary color that is by default in Antd

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18.2.0 |
| System | macOS 13.2.1  |
| Browser | Google chrome - version 112.0.5615.121 |

---
I followed the steps in the following document https://ant.design/docs/react/customize-theme#whole-export

**Comment by zombieJ** [comment]
Please follow demo https://github.com/ant-design/create-next-app-antd/blob/main/pages/_app.tsx#L4
Your proj only modify ssr style and miss modify client style

**Comment by okarook** [comment]
ok, I add this. 

```
"use client";
import { Button, ConfigProvider } from "antd";

const Theme = ({ children }: { children: React.ReactNode }) => {
  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: "red",
        },
      }}
    >
      <Button type="primary">Hola</Button>
      {children}
    </ConfigProvider>
  );
};
```


But now I have this flashing when entering the page.

https://user-images.githubusercontent.com/4731245/233653271-a3664350-9d2d-42c3-8db9-b1d01853ffc2.mov

**Comment by rodsfreitas** [comment]
the flickering is related to https://github.com/ant-design/ant-design/issues/42166
