### ISSUE TITLE
Input组件如果在compositionEnd事件中setState会导致中文无法正确输入

### ISSUE THREAD

**Issue by lovetingyuan** [ant-design/ant-design#41922]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/test-composition-event-forked-42rsoz?file=/src/HelloWorld.jsx)

### Steps to reproduce

使用火狐浏览器打开重现链接，输入法切换到中文，在输入框中输入任意中文内容
原生的input元素是可以正常输入中文的，但是antd的Input无法正确输入中文

### What is expected?

antd的Input在空格时正确键入中文

### What is actually happening?

原生的input元素是可以正常输入中文的，但是antd的Input无法正确输入中文

| Environment | Info |
| --- | --- |
| antd | 5.4.3 |
| React | 18.2.0 |
| System | mac os 11.6.8 (20G730) |
| Browser | firefox 112.0.1 (64 位) |

---
注：chrome和firefox在composition事件和change（react）事件的触发顺序上不同

**Comment by zombieJ** [comment]
因为 Input 内部监听的是 onChange 事件做状态同步，如果有特殊的定制需求，可以自行 HOC 一下把 value 代理到你的逻辑上哈。
