### ISSUE TITLE
popconfirm 处于页面右边界时，absolute left 计算有问题。

### ISSUE THREAD

**Issue by bcwekj537** [ant-design/ant-design#41921]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/popconfirm-cn/](https://4x-ant-design.antgroup.com/components/popconfirm-cn/)

### Steps to reproduce

1. 在官网上随便选择一个样例的 popconfirm 触发元素，将其样式设置为 position: absolute; right: 0; top: 500px;
2. 点击触发 popconfirm

### What is expected?

popconfirm title 一行，buttons 一行

### What is actually happening?

title 被换行，buttons 被换行成上下两个按钮

| Environment | Info |
| --- | --- |
| antd | 4.24.9 |
| React | 17 |
| System | macOS |
| Browser | chrome 112.0.5615.49 |

---
antd 3 和 antd 5 都没有问题，antd 4 在之前版本（大概是 4.17 左右）也没有问题，后来升级了 4.23 之后出现了问题。估计是在中间版本对 popconfirm 做了改造导致的。
原因应该是 absolute left 值的计算有点问题，太大了导致内容宽度变小

**Comment by zombieJ** [comment]
提供一下在线的 codesandbox 哈。

**Comment by bcwekj537** [comment]
> 提供一下在线的 codesandbox 哈。

https://codesandbox.io/embed/antd-reproduction-template-forked-kqu2rp?fontsize=14&hidenavigation=1&theme=dark

**Comment by zombieJ** [comment]
* 🚨 4.24.9
<img width="221" alt="截屏2023-04-23 17 13 35" src="https://user-images.githubusercontent.com/5378891/233830776-6311d5ab-3176-45b7-ad92-48d45bb6c07c.png">

* ✅ 4.17.4
<img width="195" alt="截屏2023-04-23 17 14 39" src="https://user-images.githubusercontent.com/5378891/233830838-566ed3bb-e7a7-4f91-86cd-a7d53a282fe2.png">

看起来是 flex 布局导致的。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/41953
