### ISSUE TITLE
Browser input user agent stylesheet input overrides ant css

### ISSUE THREAD

**Issue by jeanbmar** [ant-design/ant-design#41938]
### Reproduction link

https://codesandbox.io/s/0w9y5f

### Steps to reproduce

Right click input, inspect, Computed tab, font-family: Arial

### What is expected?

Antd font selection should apply

### What is actually happening?

Antd css is overriden by Chrome default input styling

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18.2 |
| System | Windows 10 19045.2846 |
| Browser | Chrome 111.0.5563.147 |

**Comment by Wxh16144** [comment]
What is the situation on your device?

This is my:
![image](https://user-images.githubusercontent.com/32004925/233784635-f27f9bdf-dfa2-4e2b-bc6b-dfd6fd071f38.png)

**Comment by jeanbmar** [comment]
Here is mine:

![image](https://user-images.githubusercontent.com/12987993/233786493-dbe8119f-0b37-4eea-902c-f1b16953376e.png)

I've also fixed the repro link (but its just one from the docs)

**Comment by jeanbmar** [comment]
Same result in Brave browser.
Firefox:

![image](https://user-images.githubusercontent.com/12987993/233787320-2a0c9613-3e59-41c0-8067-3045f179785c.png)

**Comment by Wxh16144** [comment]
I see, you are referring to the InputNumber component, which does have a problem with the font-family. Thanks for your feedback, I'll try to submit a pr, and send it to the core members for review.

**Comment by jeanbmar** [comment]
Thank you for the quick fix!
