### ISSUE TITLE
RengePicker with date and time throws an error on minuteStep

### ISSUE THREAD

**Issue by kirill-linnik** [ant-design/ant-design#41936]
### Reproduction link

[https://github.com/kirill-linnik/react-redux/blob/main/src/pages/MainPage.tsx](https://github.com/kirill-linnik/react-redux/blob/main/src/pages/MainPage.tsx)

### Steps to reproduce

Somehow #41834 was closed, therefore, I need to create this issue again.

If I want to have range picker which has date and time, then, according to manual, I do:
`const { RangePicker } = DatePicker;`
...
`<RangePicker showTime format={"DD.MM.YYYY hh:mm"} minuteStep={5} />`
...but `minuteStep` throws an error:

```
No overload matches this call.
  Overload 1 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any> & CommonPickerMethods', gave the following error.
    Type 'number' is not assignable to type 'IntRange<1, 59> | undefined'.
  Overload 2 of 2, '(props: RangePickerProps<Dayjs> & { dropdownClassName?: string | undefined; popupClassName?: string | undefined; }, context?: any): Component<RangePickerProps<Dayjs> & { ...; }, unknown, any>', gave the following error.
    Type 'number' is not assignable to type 'IntRange<1, 59> | undefined'.ts(2769)
```

Please, have a look at: https://github.com/kirill-linnik/react-redux/blob/main/src/pages/MainPage.tsx, line 59.

### What is expected?

No error thrown when `showTime` is `true` for `DatePicker.RangePicker`

### What is actually happening?

Error

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18 |
| System | any |
| Browser | any |

**Comment by Wxh16144** [comment]
@kirill-linnik Sorry, the types here have been updated recently, let me follow up on this issue :)

**Comment by Wxh16144** [comment]
Oh, I see it's the way you use it, the documentation has showTime as a boolean or an object
You should pass `minuteStep` as an object:

![image](https://user-images.githubusercontent.com/32004925/233786837-69bec450-72ef-4ee7-87d4-e930abab2aeb.png)

```tsx
<RangePicker
  format={"DD.MM.YYYY hh:mm"}
  showTime={{
    minuteStep: 5,
  }}
/>
```

**Comment by kirill-linnik** [comment]
> Oh, I see it's the way you use it, the documentation has showTime as a boolean or an object You should pass `minuteStep` as an object:
> 
> ![image](https://user-images.githubusercontent.com/32004925/233786837-69bec450-72ef-4ee7-87d4-e930abab2aeb.png)
> 
> ```tsx
> <RangePicker
>   format={"DD.MM.YYYY hh:mm"}
>   showTime={{
>     minuteStep: 5,
>   }}
> />
> ```

yeah, not super obvious but huge thank you for the hint!
