### ISSUE TITLE
请问如何在ts中使用 message 组件 ?

### ISSUE THREAD

**Issue by 544751779** [ant-design/ant-design#41939]
### What problem does this feature solve?

之前的版本 在ts中正常  message.error('xxx'); 没有问题 , 现在的版本会有如下错误提示 , 怎么解决这个问题呢? 
rning: [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.
c

### What does the proposed API look like?

  message.error('xxx'); 在ts中正常使用

**Comment by Wxh16144** [comment]
可以移步 #41855 进行讨论 (不过最近有点忙, 那边也还没给 demo

**Comment by miss55** [comment]
试试这个 [可以通过自定义事件来解决全局message问题](https://www.wenyisong.cn/js/antd-message-global/)
