### ISSUE TITLE
Less variable to defined a width of timePicker panel

### ISSUE THREAD

**Issue by monapasan** [ant-design/ant-design#4194]
According to [documentation](https://ant.design/docs/react/customize-theme) I have to create an issue if the list of less variables is not enough for me. 
So here we go. Would it be possible to define a width of [timePicker](https://github.com/ant-design/ant-design/blob/master/components/time-picker/style/index.less#L8) as a variable?

**Comment by benjycui** [comment]
Yep, and you may need to replace [this](https://github.com/ant-design/ant-design/blob/master/components/time-picker/style/index.less#L85) with variable, too.
