### ISSUE TITLE
从2.x版本升级到3.2.18后,有用Form.Item的validateFirst 的默认值为false.所以页面会有多个错误提示,样式不符合预期.希望能提供全局修改的api!

### ISSUE THREAD

**Issue by HanPengzhou** [ant-design/ant-design#41949]
### What problem does this feature solve?

解决了2.x版本迁移后的一些代码上的兼容问题.

### What does the proposed API look like?

  <a-Config-Provider  :form-item="{validateFirst: true}">
</a-Config-Provider>

**Comment by zombieJ** [comment]
v2 和 v3 都已经过了维护期了哈

**Comment by HanPengzhou** [comment]
> v2 和 v3 都已经过了维护期了哈

v4版本呢?要不要考虑加一下?

**Comment by zombieJ** [comment]
> v4版本呢?要不要考虑加一下?

如果有遇到 v4 版本的问题欢迎开 issue 哈，v4 仍然在维护期的。另外 v4 的 Form 是和 v3 完全不一样的，所以如果是 v2 到 v4 的话，Form 需要改造成 v4 的版本哈~
