### ISSUE TITLE
Form setFieldsValue 在labelInValue为true情况下，不能设置select的某个选项为选中状态。

### ISSUE THREAD

**Issue by jinxin479** [ant-design/ant-design#4195]
#### 发生问题的环境是：

- antd 版本:antd 2.5.0
- 操作系统及其版本:win7
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

引入Select组件，因为我想同时获得label，和value,所以设置了labelInValue = {true}，同时 想通过一个按钮，通过调用form.setFieldsValue.设置某个选项为选中状态。但是没有效果。
把labelInValue属性去掉就可以了。
form.setFieldsValue 的参数，输入为 {"id",value},同时不设置labelInValue ，是可以选中的。如果设置了labelInValue ，就会报错，“cannot create label ......”

#### 您期待的结果是:
点击另一个按钮，通过form.setFieldsValue.设置某个选项为选中状态。提交时能同时获得value和label。

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
labelInValue 会把 select 的 value 格式从 string 变成 `{ key: xx, label: xx }` 这样的 object 格式。所以你后续传递 value 都要按这个格式来。
