### ISSUE TITLE
Tabs组件在Google Chrome(112.0.5615.138)浏览器中将控制台转为手机模式，刷新页面，"更多"展开按钮不正常展示

### ISSUE THREAD

**Issue by Taylord-Lee** [ant-design/ant-design#41952]
### Reproduction link

[https://ant.design/components/tabs#components-tabs-demo-slide](https://ant.design/components/tabs#components-tabs-demo-slide)

### Steps to reproduce

1. F12打开控制台，点击Toggle device toolbar切换至手机模式，刷新此页面
2. 观察tabs栏右侧的更多操作扩展按钮

正常情况下可展示
![image](https://user-images.githubusercontent.com/88412586/233831251-47aa46e1-ff09-4787-983d-67d0d48e599b.png)
切换为移动设备模式下不正常展示
![image](https://user-images.githubusercontent.com/88412586/233831144-eb06e451-aaf7-4f2e-b104-ffe7943a13f0.png)

### What is expected?

期望扩展按钮能够在该状态下正常展示

### What is actually happening?

扩展按钮不正常显示

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18.0.0 |
| System | windows 10 |
| Browser | Google Chrome(112.0.5615.138) |
---
使用Row Col进行屏幕判断展示时，发现手机等移动设备下，Tabs的更多操作按钮无法正常显示

**Comment by zombieJ** [comment]
By Design. 移动端不会展示更多。因为 Tabs 标签本身是可以横向滑动的。

**Comment by Taylord-Lee** [comment]
那请问我有什么办法能够在移动端也展示"更多"吗？

**Comment by zombieJ** [comment]
设计上不支持，但是可以webpack注入 isMobile: https://github.com/react-component/tabs/blob/master/src/Tabs.tsx#L5
