### ISSUE TITLE
Drawer组件设置了getContainer并不总是起作用

### ISSUE THREAD

**Issue by baicoding** [ant-design/ant-design#41951]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-32risx?file=/index.js)

### Steps to reproduce

getContainer在使用时，对应的元素有什么要求，在实际使用时发现下面的问题：
1.getContainer={false}，且style={{ position: "relative" }}时，能够正常挂载在对应的div中，
2.去掉style={{ position: "relative" }}，会挂载到body中去
3.设置成getContainer={ref.current}，将drawer放到上一级div中挂载时无法正常挂载在上一级div中，会挂载在body中，这个时候上一级的div同样设置position: "relative"也不启用，无法正确挂载到div中

### What is expected?

能够根据getContainer的设置，正确挂载

### What is actually happening?

在不同的情况下，挂载的结果不一样

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18.2 |
| System | windows11 |
| Browser |  Chrome111.0.5563.111 |

**Comment by zombieJ** [comment]
试了一下你的重现，插入位置都是对的：

### 父容器 `positionL relative` + Drawer `getContainer=false`:
<img width="527" alt="截屏2023-04-23 17 25 58" src="https://user-images.githubusercontent.com/5378891/233831381-11e32057-2b19-4492-8a7f-93f2f11db3d4.png">

### 父容器无 `positionL relative` + Drawer `getContainer=false`:
<img width="413" alt="截屏2023-04-23 17 26 39" src="https://user-images.githubusercontent.com/5378891/233831419-6a38c5a8-c3cb-4f7f-a03f-164dbdb86f1b.png">

### 父容器 `positionL relative` + Drawer `getContainer=ref.current`:
<img width="390" alt="截屏2023-04-23 17 28 29" src="https://user-images.githubusercontent.com/5378891/233831497-de86019e-b394-42f5-8709-f26213263f0c.png">

### 父容器无 `positionL relative` + Drawer `getContainer=ref.current`:

<img width="384" alt="截屏2023-04-23 17 29 15" src="https://user-images.githubusercontent.com/5378891/233831536-49cb209f-e1e6-4c43-b783-d3592a76709e.png">

**Comment by baicoding** [comment]
codesanbox链接
[https://codesandbox.io/s/antd-reproduction-template-forked-32risx?file=/index.js](url)
### 父容器  `position: relative` + Drawer `getContainer=ref.current`: 展示效果不对
![image](https://user-images.githubusercontent.com/29280682/233834596-c49af9d0-5068-4356-9d5b-023fe0457f03.png)
> 
![image](https://user-images.githubusercontent.com/29280682/233834659-487e8006-3f17-4645-ada2-c61ef06c45ee.png)

### 子容器能正常显示
![image](https://user-images.githubusercontent.com/29280682/233835345-61548232-9f1a-472a-8c16-f29c3c51bae5.png)


> ### 父容器 `position: relative` + Drawer `getContainer=false`:

> 试了一下你的重现，插入位置都是对的：
> 
> ### 父容器 `position: relative` + Drawer `getContainer=false`:
> <img alt="截屏2023-04-23 17 25 58" width="527" src="https://user-images.githubusercontent.com/5378891/233831381-11e32057-2b19-4492-8a7f-93f2f11db3d4.png">


> ### 父容器无 `position: relative` + Drawer `getContainer=false`:
> <img alt="截屏2023-04-23 17 26 39" width="413" src="https://user-images.githubusercontent.com/5378891/233831419-6a38c5a8-c3cb-4f7f-a03f-164dbdb86f1b.png">
> 
> ### 父容器 `position: relative` + Drawer `getContainer=ref.current`:
> <img alt="截屏2023-04-23 17 28 29" width="390" src="https://user-images.githubusercontent.com/5378891/233831497-de86019e-b394-42f5-8709-f26213263f0c.png">
> 
> ### 父容器无 `position: relative` + Drawer `getContainer=ref.current`:
> <img alt="截屏2023-04-23 17 29 15" width="384" src="https://user-images.githubusercontent.com/5378891/233831536-49cb209f-e1e6-4c43-b783-d3592a76709e.png">



> 试了一下你的重现，插入位置都是对的：
> 
> ### 父容器 `position: relative` + Drawer `getContainer=false`:
> <img alt="截屏2023-04-23 17 25 58" width="527" src="https://user-images.githubusercontent.com/5378891/233831381-11e32057-2b19-4492-8a7f-93f2f11db3d4.png">
> 
> ### 父容器无 `position: relative` + Drawer `getContainer=false`:
> <img alt="截屏2023-04-23 17 26 39" width="413" src="https://user-images.githubusercontent.com/5378891/233831419-6a38c5a8-c3cb-4f7f-a03f-164dbdb86f1b.png">
> 
> ### 父容器 `position: relative` + Drawer `getContainer=ref.current`:
> <img alt="截屏2023-04-23 17 28 29" width="390" src="https://user-images.githubusercontent.com/5378891/233831497-de86019e-b394-42f5-8709-f26213263f0c.png">
> 
> ### 父容器无 `position: relative` + Drawer `getContainer=ref.current`:
> <img alt="截屏2023-04-23 17 29 15" width="384" src="https://user-images.githubusercontent.com/5378891/233831536-49cb209f-e1e6-4c43-b783-d3592a76709e.png">

**Comment by baicoding** [comment]
> Hello @baicoding. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @baicoding, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

重现示例
[https://codesandbox.io/s/antd-reproduction-template-forked-32risx?file=/index.js](url)

**Comment by zombieJ** [comment]
那和 `getContainer` 就没有关系了哈。`getContainer` 只关注放入位置。
在 Drawer 里有个逻辑是如果 `getContainer=false`，会被作为内联元素添加一个 `position: absolute`。如果是设置 ref，那 Drawer 就不能确定是否是内联展示，则需要自行添加对应样式：
https://codesandbox.io/s/antd-reproduction-template-forked-3e07dp?file=/index.js

**Comment by afc163** [comment]
这个 `getContainer=false` 现在有点潜规则的意思，是不是把 `inline` 放出来好了。
