### ISSUE TITLE
Checkbox.Group 排版样式与 Antd v4 保持一致

### ISSUE THREAD

**Issue by onlyling** [ant-design/ant-design#41950]
### What problem does this feature solve?

Checkbox.Group 候选项太多，外层容器固定宽度的情况下。

问题一
v5 版本的 group 使用 `display: inline-flex`，候选项会挤在一行，不会换行，文字竖着排版
v4 版本的 group 使用 `display: inline-block`，会自动换行

问题二
v5 版本候选项采用左边距间隔，换行后第二行会导致出现多于的空白区域

### What does the proposed API look like?

Checkbox.Group 排版样式与 Antd v4 保持一致

**Comment by onlyling** [comment]
v5 demo：https://codesandbox.io/s/antd-5-checkbox-group-hpwewj?file=/index.js
v4 demo：https://codesandbox.io/s/antd-4-checkbox-group-oqr9ur?file=/index.js

**Comment by afc163** [comment]
@zombieJ 看看这个问题。

**Comment by BoyYangzai** [comment]
@afc163 @zombieJ @MadCcc 
https://github.com/ant-design/ant-design/pull/42103 cc
这个改动同时影响到checkbox.group与grid的联动
v4是这样
![image](https://user-images.githubusercontent.com/94534613/235548421-cd979c20-ad67-4cf2-a917-cf0d5e78efa1.png)
v5修复之前是这样
![image](https://user-images.githubusercontent.com/94534613/235548398-a9ab9128-626b-421d-8f3d-ca9f46bb9192.png)
v5修复之后是这样
![image](https://user-images.githubusercontent.com/94534613/235548611-91cb5cb8-a3b0-4d3a-bae9-eff4b03dbb56.png)

**Comment by zombieJ** [comment]
@BoyYangzai 试试这个？
https://codesandbox.io/s/antd-5-checkbox-group-forked-b72fdo?file=/index.css

**Comment by BoyYangzai** [comment]
> https://codesandbox.io/s/antd-5-checkbox-group-hpwewj?file=/index.js

这样改样式和之前v4的差的太多了 会不会在某些地方表现不一致
@zombieJ
