### ISSUE TITLE
antd Form 调用resetFields后hasFeedback的图标并没有重置

### ISSUE THREAD

**Issue by SnowCabbage** [ant-design/ant-design#41966]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-fang-fa-diao-yong-antd-5-4-5-forked-o1dgef?file=/demo.tsx)

### Steps to reproduce

输入Note后点击reset

### What is expected?

校验图标重置，不显示

### What is actually happening?

校验图标仍然显示

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 9.6.4 |
| System | win11 |
| Browser | 当前浏览器版本 |

**Comment by SnowCabbage** [comment]
![image](https://user-images.githubusercontent.com/94156667/233927667-dd5febf3-82ef-4bd8-b2ff-ceb03f85e06a.png)

**Comment by Yuiai01** [comment]
确实存在问题，我来跟一下
