### ISSUE TITLE
createFrom 之后， 调用ref的问题

### ISSUE THREAD

**Issue by conan2008** [ant-design/ant-design#4196]
#### 发生问题的环境是：

- antd 版本: 1.10.0
- 操作系统及其版本: win10
- 浏览器及其版本: 

#### 实际上的结果是:

看了#2843 等等， 但是1.10.0 版本 设置了withRef，
this.refs.xxx.refs.wrappedComponent.refs.formWrappedComponent 也不行

this.refs.xxx.refs.wrappedComponent是 undefined

**Comment by benjycui** [comment]
你要通过 ref 调用什么方法？

**Comment by afc163** [comment]
尝试升级到 1.11 或 2.5

**Comment by JJAWX** [comment]
this.props.form.getFieldInstance(xxx)可以获取到实例
