### ISSUE TITLE
使用message全局提示时，提示结束后创建的div未被销毁

### ISSUE THREAD

**Issue by xinbo97** [ant-design/ant-design#41961]
### Reproduction link

[https://ant-design.gitee.io/components/message-cn](https://ant-design.gitee.io/components/message-cn)

### Steps to reproduce

step1：打开antd官网文档，找到Message全局提示；
step2：拉到Display normal message 普通提示处，点击Display normal message处的按钮；
step3：立马点击代码展开，代码收起，触发回流；
step4：此时会发现DOM树里利用portals创建的div盒子不会被销毁；

或者频繁点击触发message提示，并且快速点击代码展开收起触发回流，也可重现div盒子不被销毁的问题；

### What is expected?

期望在提示结束后，div盒子能被销毁！

### What is actually happening?

实际上，message提示结束后，div没有被销户

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | react18.x |
| System | macOS 12.6 (21G115) |
| Browser | chrome 107.0.5304.110（正式版本） (arm64) |

---
业务场景：自己利用message.info('This is a normal message') 的方式进行全局提示，当后台多个接口报错时，调message.info方法进行提示。但是提示结束后div盒子没有被销毁！

**Comment by zombieJ** [comment]
实验了一下无法重现，搞个 codesandbox 看看？

**Comment by supuwoerc** [comment]
+1 safari12版本message所属的元素未销毁
