### ISSUE TITLE
OnBlur event not working on controled editable typography

### ISSUE THREAD

**Issue by hungtcs** [ant-design/ant-design#41960]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3sgq87?file=/index.js)

### Steps to reproduce

1. Click on input 
2. Click outside of input

### What is expected?

Typography text blur event emit.

### What is actually happening?

Typography text blur event not emit.

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.2.0 |
| System | MacOS 13.3 (22E252) |
| Browser | Google Chrome 111.0.5563.146 (arm64) |

---

- https://github.com/ant-design/ant-design/issues/29371
- https://github.com/ant-design/ant-design/issues/35428

**Comment by zombieJ** [comment]
Text will be replaced with Input component. Which means no blur on the Text. So you can wrap on parent to get this event:
https://codesandbox.io/s/antd-reproduction-template-forked-28ep4n?file=/index.js:428-429
