### ISSUE TITLE
基于antd 4.24 table 示例的虚拟列表方案，我想要固定两边的列，我尝试过不能锁定列，因为 VariableSizeGrid 好像会不渲染隐藏的列单元格，即使头部已经固定，但是单元格并不会渲染

### ISSUE THREAD

**Issue by zhangqiankunai** [ant-design/ant-design#41964]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p0j9pf?file=/demo.tsx  你们可以尝试去锁定两边的列)

### Steps to reproduce

往下滑动的时候左侧列单元格已经不刷新，右侧找不到方法进行锁定，根本不生效，感谢了

### What is expected?

按照例子能够正常锁列就行，我期望最左侧和最右侧的列能够固定

### What is actually happening?

无论怎么尝试都不能最左侧和最右侧列给固定

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | react/^18.1.0 |
| System | mac |
| Browser | chrome |

---
怎么才能锁定列，我只想要基于4.24版本的虚拟列表锁定列，搞不定就提桶了哥哥们

**Comment by zombieJ** [comment]
merge into #20339
