### ISSUE TITLE
Issue #41749 should be marked as a BUG and is not fixed (@zombieJ)

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#41977]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/41749](https://github.com/ant-design/ant-design/issues/41749)

### Steps to reproduce

See https://github.com/ant-design/ant-design/issues/41749

### What is expected?

Calendar/pickers styled according to theme

### What is actually happening?

Calendar/pickers not styled according to theme

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.2.0 |
| System | Windows Professional 21H2 |
| Browser | Chrome Version 112.0.5615.50 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
As https://github.com/ant-design/ant-design/issues/41749#issuecomment-1504859989  commented. It's not antd bug. To simplify developer handle the correct module, I create the PR #41773 which will release in next minor version.
Minor version release for each end of month : )

**Comment by devuxer** [comment]
@zombieJ , It's a new month now. I don't see any difference.

**Comment by yoyo837** [comment]
@devuxer 5.5.0 is out!

**Comment by devuxer** [comment]
@yoyo837 YES!
