### ISSUE TITLE
DatePicker - defaultPickerValue doesn't display

### ISSUE THREAD

**Issue by MichaelJHaywood** [ant-design/ant-design#41974]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-uzk5ye?file=/index.js)

### Steps to reproduce

Click the date picker on the left and view the default picked value. 

### What is expected?

It should show the date/time that is passed in the `defaultPickerValue` prop.

### What is actually happening?

It isn't showing a default value. Nothing seems to happen. The value works correctly when using the `defaultValue` prop.

| Environment | Info |
| --- | --- |
| antd | 4.24.9 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome 112.0.5615.138 |

**Comment by zombieJ** [comment]
Hmmm... In most time it should be `defaultValue`. `defaultPickerValue` is legacy prop but not removed. But check reproduce, it does a bug.

**Comment by urveshgodhani** [comment]
can someone explain more about it I want to contribute.

**Comment by pengyw97** [comment]
@zombieJ 请问我可以提一个将defaultPickerValue移除的PR吗？

**Comment by zbw-zbw** [comment]
> Hmmm... In most time it should be `defaultValue`. `defaultPickerValue` is legacy prop but not removed. But check reproduce, it does a bug.

大佬好，我看了下源码，发现确实是已经不支持这个属性了 只是文档没删除掉，我可以针对这个问题提个 pr 吗？？嘿嘿谢谢

**Comment by zbw-zbw** [comment]
@zombieJ 大佬 有空审批下 pr

**Comment by zbw-zbw** [comment]
> @zombieJ 大佬 有空审批下 pr

https://github.com/ant-design/ant-design/pull/43620

**Comment by komarovalexander** [comment]
Hi Team defaultPickerValue was useful when you want to set default date for popup value (when it oppens) and do not set this value in editor - Is it possible without defaultPickerValue?
