### ISSUE TITLE
InputNumber: class `ant-input-number-input` overrides class `ant-input-number-lg` styles

### ISSUE THREAD

**Issue by jeanbmar** [ant-design/ant-design#41971]
### Reproduction link

[https://stackblitz.com/edit/react-rzsc9z?file=demo.tsx](https://stackblitz.com/edit/react-rzsc9z?file=demo.tsx)

### Steps to reproduce

Right-click number input, inspect, Computed tab, font-size: 14px

### What is expected?

Font-size should be 16px since the input is large

### What is actually happening?

Large class / props seem to be missing on the input itself

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.2 |
| System | Windows 10 19045.2846 |
| Browser | Chrome 111.0.5563.147 |

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/pull/41940

cc @Wxh16144

**Comment by Wxh16144** [comment]
oh, sorry 😞
