### ISSUE TITLE
select使用dropdownRender时，手动收起下拉框无效

### ISSUE THREAD

**Issue by 605472218** [ant-design/ant-design#41973]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js)

### Steps to reproduce

设置了ref，想用selectRef?.current?.blur()来收起下拉框但不生效，试图用select的open属性来控制，也没有生效。

是只能在列表外进行操作吗？如果想在列表中操作的话需要怎么解决呢？    
  

### What is expected?

自定义下拉框时，在下拉框中里面的点击事件中可以正常收起下拉框

### What is actually happening?

自定义下拉框时，在下拉框中里面的点击事件中收起下拉框无效

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | - |
| Browser | 109.0.5414.119 |

**Comment by 605472218** [comment]
> 

https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js

**Comment by afc163** [comment]
<img width="1231" alt="图片" src="https://user-images.githubusercontent.com/507615/234153933-3180880f-d91d-4bfc-9621-f8eb561d83cc.png">

这边提供的 codesandbox 里没有发现 Select 和 dropdownRender，是否搞错了？

**Comment by 605472218** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-m9dllz?file=/index.js
不好意思，再看看呢？
不行的话代码直接在这里：
import React, { useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { Button, Select, Card, Checkbox } from "antd";
import "antd/dist/reset.css";
import "./index.css";

const App = () => {
  let selectRef = useRef(null);
  const [value, setValue] = useState("");

  const options = [
    { label: "Apple", value: "Apple" },
    { label: "Pear", value: "Pear" },
    { label: "Orange", value: "Orange" }
  ];

  const changeChecked = (val) => {
    console.log(value);
    changeSelect(val?.join());
  };

  const changeSelect = (val) => {
    setValue(val);
  };
  return (
    <Select
      value={value}
      style={{ width: "100%" }}
      placeholder="请选择"
      ref={(r) => {
        selectRef = r;
      }}
      dropdownRender={(menu) => (
        <div>
          <Card
            title={
              <div>
                <Checkbox>共{options?.length}条</Checkbox>
              </div>
            }
            extra={
              <Button
                type="primary"
                onClick={() => {
                  selectRef?.current?.blur();
                }}
              >
                确定
              </Button>
            }
          >
            <Checkbox.Group options={options} onChange={changeChecked} />
          </Card>
        </div>
      )}
    ></Select>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);

**Comment by afc163** [comment]
受控模式看上去没啥问题：https://codesandbox.io/s/antd-reproduction-template-forked-s8mfzw?file=/index.js

**Comment by 605472218** [comment]
> 受控模式看上去没啥问题：https://codesandbox.io/s/antd-reproduction-template-forked-s8mfzw?file=/index.js

试了下，受控模式是可以的，我之前不知道要用onDropdownVisibleChange，可能是因为这个不生效，谢谢。

还想问下，使用ref.current.blur()的话是必须在下拉选项之外使用吗？

**Comment by afc163** [comment]
blur() 方法从语义上也不一定保证关闭下拉菜单。在这个场景不建议用。

**Comment by 605472218** [comment]
> blur() 方法从语义上也不一定保证关闭下拉菜单。在这个场景不建议用。

好的，谢谢了
