### ISSUE TITLE
[Table] Bad border-radius when a header and a scroll are defined

### ISSUE THREAD

**Issue by TdyP** [ant-design/ant-design#41975]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/border-title-and-footer-antd-5-4-5-forked-q2cf7p?file=/demo.tsx)

### Steps to reproduce

Define a table with a custom header (`header` props) AND a scroll (`scroll` props) like so
```ts
  <Table
    columns={columns}
    dataSource={data}
    bordered
    title={() => 'Header'}
    footer={() => 'Footer'}
    scroll={{y: '50px'}}
  />
```

### What is expected?

The columns header shouldn't have a border-radius defined, as there's the custom header above. 
![image](https://user-images.githubusercontent.com/13244173/234006323-ff69d92b-d6b9-499a-8112-9fcf42e40cb5.png)

### What is actually happening?

The columns header has some border-radius, only if scroll if defined. If scroll is not defined, there's no radius
![Capture d’écran du 2023-04-24 15-10-39](https://user-images.githubusercontent.com/13244173/234006469-2215c272-4266-49f6-900b-04ed849e8bc0.png)

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/commit/b82d9d35e65225f63057d7b7412c9c6e9871be6c

**Comment by TdyP** [comment]
Very reactive, thank you!
