### ISSUE TITLE
AntD官网-设计资源-Axure 部件库无法下载

### ISSUE THREAD

**Issue by hujinbo** [ant-design/ant-design#41984]
### Reproduction link

[http://library.ant.design/](http://library.ant.design/)

### Steps to reproduce

1.打开设计资源页面：https://4x.ant.design/docs/resources-cn/  
2.点击Axure 部件库：http://library.ant.design/

### What is expected?

正常展示下载页

### What is actually happening?

打开http://library.ant.design/  ，页面闪了一下，跳转回了：https://ant-design.antgroup.com/docs/resources-cn

| Environment | Info |
| --- | --- |
| antd | 4.24.9 |
| React | 17 |
| System | win10 |
| Browser | Chrome |

**Comment by afc163** [comment]
可以用这个链接下载：https://github.com/ant-design/ant-design/releases/download/resource/library.ant.design_V2.2.zip

不过这个库 6 年没更新了。

**Comment by hujinbo** [comment]
> 可以用这个链接下载：https://github.com/ant-design/ant-design/releases/download/resource/library.ant.design_V2.2.zip
> 
> 不过这个库 6 年没更新了。

好的，谢谢！

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/releases/download/resource/AntDesign3.9.x_Axure_20180903.rplib

这里有个更新一点的 2018 年的。

**Comment by poyiding** [comment]
很赞，老版本的Axure 还是不要轻易的下了

**Comment by zhangxinyong12** [comment]
axure10 打不开嘛？
