### ISSUE TITLE
using modals in tables giving unexpected results 

### ISSUE THREAD

**Issue by surajmn1** [ant-design/ant-design#41989]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-78dev8?file=/index.js)

### Steps to reproduce

1. open the sandbox provided
2. click on delete action in the table
3. click on okay in the modal
4. view the console

or 
create a table which has a button in its columns and it onclick opens a modal using the render method . 

### What is expected?

same item from the data array should be available to both modal and button . but it gives different . 

### What is actually happening?

it selects the wrong item in modal and correct item in button .

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.x |
| System | macOS monterey 12.2.1 |
| Browser | Google Chrome Version 108.0.5359.124 (Official Build) (arm64) |

**Comment by zombieJ** [comment]
Your call `setModalOpen(true)` mean open every modal on the list so it open 4 Modal and last one is in the front. It's not antd bug but your application logic bug:

https://codesandbox.io/s/antd-reproduction-template-forked-qbg451

PS: This is just for example. You should correct on your own.
