### ISSUE TITLE
Pass prefix (trigger) to filterOptions function in <Mentions ..> component

### ISSUE THREAD

**Issue by bennidi** [ant-design/ant-design#41991]
### What problem does this feature solve?

**Scenario**: There are **multiple prefixes** and I want to use the **filterOptions** callback to control which suggestions are shown (suggestions are passed as data array in options property).

**Problem**: filterOptions does not receive the selected prefix as parameter such that option filtering by prefix is not possible within the context of that function. It is not possible to work around this by means of using the **onSearch** callback because it is fired only after the filterOptions callback has been triggered.

**Solution**: If the current prefix were passed to the filterOptions callback then this could be the one and only place to handle the entire filtering logic **without causing any rerenders** of the component (which is what the current example in Antd docs is doing).

### What does the proposed API look like?

The API could be designed such that there is no breaking change, simply by adding the prefix as a third parameter to the callback like so `(input: string, option: OptionProps, prefix:string) => boolean`

**Comment by bennidi** [comment]
I just noticed that the filterOptions callback does not work as expected. I used onChange callback to extract prefix and other info from current value (onChange fire before filterOptions). I then correctly filter the options and return true only for the valid options and still nothing is displayed.
Is it supposed to work like this?

**Comment by zombieJ** [comment]
Prefix is a trigger mark but not affect filter you can modify the official demo to get this: https://codesandbox.io/s/zi-ding-yi-chu-fa-zi-fu-antd-5-4-5-forked-6yn7dm?file=/demo.tsx

**Comment by bennidi** [comment]
The sample shows that the different prefixes are meant to control what options are shown. I think that a very natural way to do this, is to have a filter function that selects valid options from current input. The input should include the trigger because it is relevant to the filter. The demo code makes use of useState and causing component rerenders (for which there is no actual need).

Is there any reason why you would not want to pass the current prefix into the filterOptions?
