### ISSUE TITLE
TimePicker 设置 moment 对象作为 value 无法正常显示

### ISSUE THREAD

**Issue by flyinghail** [ant-design/ant-design#4199]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: win10
- 浏览器及其版本: firefox 50.0.2

#### 您做了什么？请提供尽可能详细的重现步骤。

给 TimePicker 设置 value，形如：
```
const time = '00:00';

<TimePicker value={moment(time, 'HH:mm')} format="HH:mm" />
```

#### 您期待的结果是:

正确显示 TimePicker

#### 实际上的结果是:

console报错：
Error: The value/defaultValue of TimePicker must be a moment object after `antd@2.0`, see: http://u.ant.design/time-picker-value

#### 可重现的在线演示

以下照抄官网的例子，不管设置 value 还是 defautValue 都无法显示
http://codepen.io/anon/pen/ObwLmo?editors=001

**Comment by flyinghail** [comment]
antd 2.5.0 是正常的

**Comment by benjycui** [comment]
2.5.2 会修复，这周末发。
