### ISSUE TITLE
Custom alignment of Tooltip is broken in v5

### ISSUE THREAD

**Issue by mellis481** [ant-design/ant-design#41992]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-4-5-forked-y9psqg?file=/demo.tsx:111-535)

### Steps to reproduce

1. Define `align` property.
2. Hover over text.

### What is expected?

 Tooltip should be offset to the top right slightly.

### What is actually happening?

Tooltip is offset to the bottom left and to a more significant amount. 

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | react |
| System | Windows |
| Browser | All |

---
This is only an issue in v5, not v4. eg: https://codesandbox.io/s/basic-antd-4-24-8-forked-4q5hov?file=/demo.tsx

**Comment by zombieJ** [comment]
Your reproduce in v5 is using `div` but v4 use `span`. Could you help to update the reproduce to align?

**Comment by zombieJ** [comment]
Patch screenshot here:

#### v5
https://codesandbox.io/s/basic-antd-5-4-5-forked-0jl2gz

<img width="460" alt="截屏2023-05-08 14 16 42" src="https://user-images.githubusercontent.com/5378891/236748422-c71580eb-8bb7-425d-aa28-c4fd44b01387.png">

#### v4
https://codesandbox.io/s/basic-antd-4-24-8-forked-vnll4f?file=/demo.tsx

<img width="341" alt="截屏2023-05-08 14 16 49" src="https://user-images.githubusercontent.com/5378891/236748445-fb8c7160-b115-43a6-94b3-590699492584.png">
