### ISSUE TITLE
是否可能给jsx页面打断点调试?

### ISSUE THREAD

**Issue by astwyg** [ant-design/ant-design#420]
各位:
  我们使用的并不是ant-design, 但是设计思想非常类似, 我们也是通过`JSXTransformer.js`对jsx文件进行加载和转义, 但是有一个问题一直困扰我们: `JSXTransformer.js`进行转义的jsx文件是无法打断点的, 我们使用的浏览器是Chrome 44.0.2403.155 (64-bit).

  不知道各位对于使用组件库的jsx文件调试有何解决方案? 十分感谢!

**Comment by benjycui** [comment]
官方已经不推荐使用 [JSXTransformer.js](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#deprecation-of-react-tools)。

> ## Deprecation of react-tools
> The react-tools package and JSXTransformer.js browser file have been deprecated. You can continue using version 0.13.3 of both, but we no longer support them and recommend migrating to Babel, which has built-in support for React and JSX.

预先用 Babel 编译成 JS，就可以调试了。

**Comment by yiminghe** [comment]
yes, 要预编译

**Comment by astwyg** [comment]
痛失灵活性了, 我们希望直接把组件库提供给后端人员用, 一个js, 一个css文件搞定, 不需要node环境, 看来是没戏了
