### ISSUE TITLE
折叠面板如何实现搜索后自动跳转定位功能？

### ISSUE THREAD

**Issue by atkxyh** [ant-design/ant-design#42003]
### What problem does this feature solve?

Kconfig 系统内核配置 需要支持搜索跳转到配置项

### What does the proposed API look like?

Collapse支持通过key来跳转定位

**Comment by zombieJ** [comment]
这个是业务实现，和组件没有关系。你的搜索的完成后直接调用 scrollTo 过去。

**Comment by atkxyh** [comment]
这个scrollTo是需要自己实现的方法嘛？
另外Collapse没有找到控制展开折叠的API，我要怎么样实现搜索后自动展开对应的面板节点呢

**Comment by zombieJ** [comment]
设置一个 id，然后 querySelector 到它后调用 scrollTo。这个就是纯 js 的方式。和组件没有关系哈
