### ISSUE TITLE
How can I disable the Cancel button while the Ok button is loading when using Modal.confirm?

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#42006]
### What problem does this feature solve?

Block user from closing Modal confirm while calling API.

### What does the proposed API look like?

CancelButtonProps should be updated when there is an action on the OK button.

**Comment by zombieJ** [comment]
Just call `update` for:
https://codesandbox.io/s/que-ren-dui-hua-kuang-antd-5-4-5-forked-iq0t29?file=/demo.tsx

**Comment by edikurniawan-dev** [comment]
not working
