### ISSUE TITLE
Space.Compact 在Form.Item组件中时，操作Form数据有异常

### ISSUE THREAD

**Issue by ByYogi** [ant-design/ant-design#42001]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/feedback-antd-5-space-compact2-68dvel?file=/App.tsx)

### Steps to reproduce

1. 输入绿框框中的输入框，查看实时数据变化。是正常的。
2. 在红框框（Space.Compact）输入。数据设置异常
![image](https://user-images.githubusercontent.com/111735598/234445320-fcf95778-1885-4034-9749-0acb7f8b846c.png)

### What is expected?

期望Space.Compact组合输入组件时，对数据的操作反馈与Input.Group一样。

### What is actually happening?

我在Space.Compact的第一个输入框输入“123”，结果是”13“
![image](https://user-images.githubusercontent.com/111735598/234445457-fc03be0d-375d-48cd-8e34-20b4409136b2.png)

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.2.x |
| System | Win10/Codesandbox |
| Browser | Version 112.0.5615.138 (Official Build) (64-bit) |

---
一般用于自定义表单组件，类似From-To的组合输入框。

**Comment by zombieJ** [comment]
如果你的值是自己控制的，就是不要为 Form.Item 配置 `name`。配置后 Form 会接管 `value` 和 `onChange` 事件：
https://codesandbox.io/s/feedback-antd-5-space-compact2-forked-i8qc75?file=/App.tsx

自定义表单组件需要将 `value` 和 `onChange` 托管掉，不能半受控。参考一下示例哈：
https://ant.design/components/form-cn#components-form-demo-customized-form-controls
