### ISSUE TITLE
Input in form Item should keep the cursor position after normalizing

### ISSUE THREAD

**Issue by Felix-Kistler-TWT** [ant-design/ant-design#42010]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-q1brj9)

### Steps to reproduce

1. Enter "12" in the text input
2. Move the cursor between "1" and "2"
3. Enter "A" between "1" and "2"

### What is expected?

"A" is automatically replaced by "B", and the cursor stays between "B" and "2"

### What is actually happening?

"A" is automatically replaced by "B", and the cursor move to the end of the text (after "2")

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.2.0 |
| System | Windows 10 (64-bit) |
| Browser | Google Chrome 112.0.5615.138 (64-bit) |

---
If you think it is more like a new feature please change the issue type. However, it was easier to describe with the reproduction steps and sample.
In case the sandbox is not working, this is the relevant code:
    <Form>
        <Form.Item
          name="InputNormalizingA"
          label="Enter 'A' in the middle of previous input"
          normalize={(value) => value.replace("A", "B")}
        >
            <Input />
        </Form.Item>
    </Form>

**Comment by BoyYangzai** [comment]
good idea👍

**Comment by BoyYangzai** [comment]
I thought about it. `normalize` just provides the modified `value` value. Your scenario is a single replacement of `replace`. If it is `replaceAll`, I think the props function currently provided by antd is reasonable. More The function should be realized by the specific business side. For example, our requirement may be able to listen to the `change` event and change the position of `cursor` by ourselves. @Felix-Kistler-TWT cc

**Comment by Felix-Kistler-TWT** [comment]
@BoyYangzai: I am unsure. No matter if it is `replace `or `replaceAll`, as a user I would expect that the cursor stays at its "original" position. I understand that this is quite tricky as from the form item point of view there is no relation between the original and the normalized value. And I don't really have an idea on how to fix this. It might be an input and output value for the cursor position in the normalize method? Or a separate change event for being able to fix the cursor position manually.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-hv2zbz?file=/index.js

native input has the same issue in controlled mode, I afraid we could not find a proper solution.
