### ISSUE TITLE
AutoComplete scroll disappearing

### ISSUE THREAD

**Issue by linras** [ant-design/ant-design#42016]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autocomplete-antd-5-4-5-forked-bzu7ff?file=/package.json:212-218)

### Steps to reproduce

1. Click on the input to see the drop-down options with the scroll visible.
2. Wait a few seconds.

### What is expected?

Nothing changes.

### What is actually happening?

The scroll disappears. 

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.0.0 |
| System | Microsoft Windows 10 Enterprise |
| Browser | Google Chrome Version 112.0.5615.138 (64-bit) |

---
After using mouse scroll the drop-down scroll is back, but it disappears again after some time.

**Comment by mrshukhratbek** [comment]
This is a commonly observed practice in web design. It is frequently employed when working with scrollable content, whereby the scroll bar disappears after a period of inactivity and reappears when scrolling resumes. As an illustration, please try using the scroll feature on the left sidebar of the website youtube.com.

**Comment by linras** [comment]
I agree that the youtube example is nice, where the content is static and the scroll appears on hover and is not hidden until cursor is moved away. But for the AutoComplete search component it turns out to be quite confusing. It disappears quickly and users are complaining that the data is not loaded while it's just the hidden scroll issue.

**Comment by afc163** [comment]
It is intented to simulate as MacOS scrollbar behavior.
