### ISSUE TITLE
[antd: Tabs] Tabs.TabPane is deprecated. Please use `items` directly. 

### ISSUE THREAD

**Issue by smahmoodh** [ant-design/ant-design#42021]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-dawn-8jksff?file=/src/App.js)

### Steps to reproduce

I have used a demo like the code posted in codesandbox and now 'TabPane' is deprecated warning. There is no example of putting too many tags in 'items' on the each tab content.

### What is expected?

Replace 'items' instead of 'TabPane'

### What is actually happening?

The message "[antd: Tabs] Tabs.TabPane is deprecated. Please use `items` directly." 
is displayed.

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by subhankar496k** [comment]
yeah same issue with me also you are using TabPane , i used Tabs.TabPan as a component then i found out that TabPane directly can be used
`import { Tabs } from 'antd';
const onChange = (key) => {
  console.log(key);
};
const items = [
  {
    key: '1',
    label: `Tab 1`,
    children: `Content of Tab Pane 1`,
  },
  {
    key: '2',
    label: `Tab 2`,
    children: `Content of Tab Pane 2`,
  },
  {
    key: '3',
    label: `Tab 3`,
    children: `Content of Tab Pane 3`,
  },
];
const App = () => <Tabs defaultActiveKey="1" items={items} onChange={onChange} />;
export default App;`

In the above code as you can see Tabs.TabPane is not used at all and the tab prop which specifies the tab name is replaced with label and inside the children you can just put a React fragment <></> which works just like a usual render component and you can add further functionalities in it and the error of depricated TabsPan won't show in the console anymore 
for further details you can visit the ant design docs on this topic using the link below
https://ant.design/components/tabs
![console](https://user-images.githubusercontent.com/100505729/234977213-8612531b-049a-4dc6-b568-e07f16856756.png)

**Comment by subhankar496k** [comment]
`import { Tabs } from 'antd';
const onChange = (key) => {
  console.log(key);
};
const items = [
  {
    key: '1',
    label: `Tab 1`,
    children: `Content of Tab Pane 1`,
  },
  {
    key: '2',
    label: `Tab 2`,
    children: `Content of Tab Pane 2`,
  },
  {
    key: '3',
    label: `Tab 3`,
    children: `Content of Tab Pane 3`,
  },
];
const App = () => <Tabs defaultActiveKey="1" items={items} onChange={onChange} />;
export default App;`

**Comment by subhankar496k** [comment]
![antd](https://user-images.githubusercontent.com/100505729/234978330-ca8b2e17-03fc-46c1-a27e-5ad5de4873af.png)
![console](https://user-images.githubusercontent.com/100505729/234978355-fbd8aaba-5125-4e27-8059-29c702c4d5e4.png)
### Problem Solved
yeah same issue with me also you are using TabPane , i used Tabs.TabPan as a component then i found out that TabPane directly can be used then i  tried using it with the items method as shown in the picture above and it works fine.
In the above code as you can see Tabs.TabPane is not used at all and the tab prop which specifies the tab name is replaced with label and inside the children you can just put a React fragment <></> which works just like a usual render component and you can add further functionalities in it and the error of depricated TabsPan won't show in the console anymore
for further details you can visit the ant design docs on this topic using the link below

**https://ant.design/components/tabs**

**Comment by smahmoodh** [comment]
I know this according to the example of the site, but if I want to put the following code in tab 1 and other tabs, for example, what should I do?

```
<div>
      <h2>Tab 1 content</h2>
      <div>
        <p>{product.content}</p>
        <ul>
          <li>{product.id}</li>
          <li>{product.name}</li>
          <li>{product.address}</li>
        </ul>
      </div>
    </div>
```

**Comment by smahmoodh** [comment]
I know this according to the example of the site, but if I want to put the following code in tab 1 and other tabs, for example, what should I do?

```
<div>
      <h2>Tab 1 content</h2>
      <div>
        <p>{product.content}</p>
        <ul>
          <li>{product.id}</li>
          <li>{product.name}</li>
          <li>{product.address}</li>
        </ul>
      </div>
    </div>
```

**Comment by subhankar496k** [comment]
yeah i understand your task now that you know how to use the tabs you can create a list that has all the data and you can access those data through the . operator and try mapping the product content because inside the product object there can be multiple product contents (as i am assuming) and each product content must contain a unique id  so the approach would be mapping thorough all the product content and rendering them one by one in the list so  i am also assuming that the product is an array object hence it has indexed product.content and the key must be unique so you can have the index as the key and if you dont add key it will show error . then you can individually access all the contents of the product.content and show them in the div 

## Here is my approach
![Screenshot 2023-04-30 230551](https://user-images.githubusercontent.com/100505729/235368017-50191716-c21c-4185-8e3d-86b8d9032c3a.png)

**Comment by subhankar496k** [comment]
One more thing don't forget to import all the stuff and i just randomly used a prebuilt layout for the tabs you can directly render it.

**Comment by subhankar496k** [comment]
😅 after the list i forgot to remove the snippet you provided for lists you can remove that also . I was in a hurry so didn't see that one😊 hope it helps👌🏻

**Comment by smahmoodh** [comment]
Yes it works. 👌😁
But the previous way of using TabPane was more logical and better.
Thank you very much for your help 🙋‍♂️

**Comment by subhankar496k** [comment]
Mm hm the previous one was great but when we scale up the code and when it has to handle huge loads of data it just creats unnecessary boilerplate code so thats why this modular approach is way more optimized for scalable code still not that complex if you give time a understand the logic, you dont really need to memorize the syntax just know the theme rest will be easy👌🏻😊 And you're welcome,  keep trying out new things and keep solving bugs...

**Comment by stephenykk** [comment]
> Yes it works. 👌😁 But the previous way of using TabPane was more logical and better. Thank you very much for your help 🙋‍♂️

i think so

**Comment by BangyuanX** [comment]
Agree, the previous TabPane logic was much more clear.

**Comment by Sanan4li** [comment]
Not sure why it's deprecated. TabPane make sense because it's written in JSX. The items is confusing when someone else reading the code.
