### ISSUE TITLE
Use popover for DatePicker

### ISSUE THREAD

**Issue by RobertHosking** [ant-design/ant-design#42025]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-field-og9zqw?file=/index.js)

### Steps to reproduce

I need to use popover styles for a date picker. Specifically, I need to use the placement="top" and I need to use a caret at the bottom which points to the button trigger for the DatePicker.

Click the button in the codesandbox link to see how the popup renders the datepicker.
![Screenshot 2023-04-26 at 5 25 26 PM](https://user-images.githubusercontent.com/12145976/234706337-4d539ae3-1c6c-44e9-89db-cb8ea7337460.png)

### What is expected?

The Popup should become the new container for the datepicker.

![Screenshot 2023-04-26 at 5 27 08 PM](https://user-images.githubusercontent.com/12145976/234706830-7b23adcb-0890-4709-914f-f0624fe73996.png)

### What is actually happening?

The datepicker has it's own dropdown-style container which is rendered in addition to the popover. 

| Environment | Info |
| --- | --- |
| antd | 4.24.9 |
| React | 18 |
| System | MacOS 13 |
| Browser | Chrome 112 |

**Comment by RobertHosking** [comment]
@kdrsfr please check the updated codesandbox in the OP. I added the relative div and target with getPopupContainer, now it looks like this:

![Screenshot 2023-04-27 at 1 07 37 PM](https://user-images.githubusercontent.com/12145976/234937559-e327efc4-c686-4ffd-982d-970990a1fe1b.png)

**Comment by afc163** [comment]
getPopupContainer is used for customize dom node position of popup element, not the visible position we could see.

**Comment by afc163** [comment]
You should try `<Calendar />`, or trace https://github.com/ant-design/ant-design/issues/40051

**Comment by zengdukan** [comment]
@RobertHosking maybe you can try inputRender.
`<DatePicker suffixIcon={null} allowClear={false} bordered={false} onChange={onChange} inputRender={(props) => <Text code {...props}>20230505</Text>} />`
