### ISSUE TITLE
InputNumber 的 className 会挂在两个 dom 元素上

### ISSUE THREAD

**Issue by afishhhhh** [ant-design/ant-design#42028]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-zhuang-tai-antd-5-4-5-forked-vlugn7?file=/demo.tsx)

### Steps to reproduce

无

### What is expected?

className 不会同时挂到 div.ant-input-number-affix-wrapper 和 div.ant-input-number

### What is actually happening?

className 同时挂到了 div.ant-input-number-affix-wrapper 和 div.ant-input-number 上

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.0.0 |
| System | macOS |
| Browser | chrome 110.0.5481.177 |

---
rootClassName 只会挂到根节点上，但是文档上没有说明

**Comment by MadCcc** [comment]
rc-input-number 迁移 rc-input 后可解

**Comment by afishhhhh** [comment]
> 

你是指后续更新 InpuNumber 会用 rc-input 去实现，不再使用 rc-input-number ?

**Comment by afishhhhh** [comment]
> rc-input-number 迁移 rc-input 后可解

你是指后续更新 InpuNumber 会用 rc-input 去实现，不再使用 rc-input-number ?

**Comment by MuxinFeng** [comment]
这个 issue 可以关了~

**Comment by yoyo837** [comment]
Fixed in #43000 and released in [5.7.0](https://github.com/ant-design/ant-design/releases/tag/5.7.0)
