### ISSUE TITLE
Select组件的onBlur事件参数event是字符串

### ISSUE THREAD

**Issue by dongli** [ant-design/ant-design#4202]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: macOS 10.12.1
- 浏览器及其版本: Chrome 56.0.2924.18 dev (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

触发`Select`的`onBlur`事件，以取得被选择的值，并设置父组件的`state`。

#### 您期待的结果是:

`onBlur`的参数`event`应该是个`object`，这样我可以访问`target`，取得其中的`name`和`value`。

#### 实际上的结果是:

`onBlur`的参数`event`是个字符串，其值是被选择的值，我无法判断是哪个`Select`组件。

```
<Form.Item label='模拟类型'>
{
    getFieldDecorator('type', {
      rules: [{
        required: true, message: '请选择模拟类型！'
      }]
    })(
      <Select onBlur={this.onBlur}>
        <Select.Option value='回报'>回报</Select.Option>
        <Select.Option value='预报'>预报</Select.Option>
      </Select>
    )
  }
</Form.Item>
```

![2016-12-10 5 55 29](https://cloud.githubusercontent.com/assets/367959/21065835/527e06b2-be9d-11e6-9dd2-4b00126cf0ce.png)

**Comment by ddcat1115** [comment]
请使用 `labelInValue ` 属性，具体看下API说明

**Comment by benjycui** [comment]
参数类型请看文档，不要 YY API 的用法。

**Comment by dongli** [comment]
@benjycui 不是我YY，文档只有如下：
![2016-12-13 4 04 41](https://cloud.githubusercontent.com/assets/367959/21132242/fd72d14e-c14d-11e6-9851-c17fa06b00d2.png)

我从中无法看出function的参数是啥。
