### ISSUE TITLE
Modal dialog default text language

### ISSUE THREAD

**Issue by jihdeh** [ant-design/ant-design#4203]
Sorry I don't understand Chinese, I skipped the options.

I implemented the modal dialog and found out the default buttons `OK` and `Cancel` are in Chinese by default unless prop added.

As I've found where this happens in the code [https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx#L131](https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx#L131)

Any chance this could be changed to English? I could submit a PR for this.

**Comment by boneyao** [comment]
Hi, @jihdeh  change you code like this `<Modal title="Hi"  cancelText = "I'm English Text">` and check your antd version;

**Comment by kvetoslavnovak** [comment]
Some time ago I proposed PR with English as a default language:
#3768

But it is postponed not soo er untill 3.0. So you have to use Local provider.
