### ISSUE TITLE
DatePicker.RangePicker编辑时不触发onCalendarChange事件

### ISSUE THREAD

**Issue by tinyhealer** [ant-design/ant-design#42034]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-687lbd)

### Steps to reproduce

1.  在codesandbox中或直接定位至antd文档DatePicker组件中“选择不超过七天的范围”示例代码。
2.  点击RangePicker选择框打开日期选择面板，通过点击面板2023年4月10日选择该日期作为日期下限，鼠标光标跳转至编辑日期上限，4月10日之前的日期变为disabled状态。此时可以正确触发onCalendarChange，达到将4月16日之后的日期置为disabled状态的效果。
3.  编辑RangePicker下限（不通过面板点击选择），将2023-04-10改为2023-04-03，点击日期上限选择框，4月3日之前的日期变为disabled状态。但此时由于没有触发onCalendarChange，上限disabled状态的日期仍然是4月16日之后的，即此时日期上限可选范围为4月3日至4月16日，而不是期望的4月3日至4月10日。通过点击日期面板选择日期则没有该问题。
4.  给onCalendarChange时间回调函数添加console打印，发现编辑选择框日期导致可选日期变化不会有期望的打印内容，因此可以确定该事件未触发。

### What is expected?

编辑DatePicker.RangePicker时和通过日期选择面板都能使范围之外的日期变为disabled，期望此时都能够正确触发onCalendarChange。

### What is actually happening?

通过编辑RangePicker日期选择框不会触发onCalendarChange。

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 17.0.1 |
| System | windows 10 |
| Browser | Chrome 112.0.5615.138 |

**Comment by zombieJ** [comment]
嗯，有很多相关 issue 了。感觉是要出个 `selectOnBlur` 之类的属性。

**Comment by HahnBrunt** [comment]
有什么其他的方法绕过这个问题吗

**Comment by yoyo837** [comment]
误操作.
