### ISSUE TITLE
复用多个Panel，单独控制每一个Panel的collapsible属性

### ISSUE THREAD

**Issue by atkxyh** [ant-design/ant-design#42045]
### What problem does this feature solve?

面板为多选框形式，当选中该面板的多选按钮，则可折叠展开，当取消选中时，则自动折叠且禁止展开

### What does the proposed API look like?

nothing

**Comment by Wxh16144** [comment]
我印象中好像看到过你类似需求, 多选的时候收集已选的 key,  感觉现有的 api 也满足需求呀

**Comment by atkxyh** [comment]
禁止展开这个操作应该是设置collapsible = ‘disabled’  但是我如何根据header中的checkbox勾选情况，设置对应的panel的collapsible属性呢？
<Panel collapsible={expand} key={item.key} header={<KCheckbox {...item} checkChange = {checkChange}/>}/>

**Comment by atkxyh** [comment]
用state控制的话，任意一个的点选会影响其他的collapsible状态
我也尝试过将Panel封装一遍，结果发现必须修改封装组件的collapsible才生效  参考链接中的KPanel

**Comment by afc163** [comment]
Panel 上有 collapsible 属性，可以单独控制。
