### ISSUE TITLE
两个汉字之间的空格特殊情况下不能正常添加

### ISSUE THREAD

**Issue by lemonliu2022** [ant-design/ant-design#42043]
### Reproduction link

[https://github.com/lemonliu2022/antd-demo](https://github.com/lemonliu2022/antd-demo)

### Steps to reproduce

```shell
pnpm install && pnpm run dev
```

### What is expected?

期望`你好`的中间添加空格

### What is actually happening?

没有空格

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2.0 |
| System | Mac 13.2 |
| Browser |  112.0.5615.121（正式版本） (arm64) |

---
看源码 components/button/button.tsx isNeedInserted限制了 spaceChildren 传入的children.length===1，但 spaceChildren 却处理了{String('你')}{String('好')}的情况，代码让人很迷惑，且这种情况只能自己添加空格

**Comment by Wxh16144** [comment]
> 代码让人很迷惑，且这种情况只能自己添加空格

感觉你的入参也很迷惑呀, 为什么不直接处理完后丢给 Button 组件呢 🤔

**Comment by lemonliu2022** [comment]
> 

处理有很多方式，没有问题。我在疑问的是children.length=1应该不用再forEach处理了，代码是否可优化

**Comment by Wxh16144** [comment]
原谅我没 Get 到你的点 😭, 如果你感兴趣优化可以发起一个 PR ~

**Comment by tianjucun** [comment]
> > 
> 
> 处理有很多方式，没有问题。我在疑问的是children.length=1应该不用再forEach处理了，代码是否可优化

感觉这个 `spacelChildren` 核心做的事情好像是对 字符串或者是 fragment ，在外面包一层 span 然后再返回。或者有可能说这么做应该是在执行某个标准 🤔

**Comment by tianjucun** [comment]
比较有疑惑的是，为啥在新增了 spaceChildren 后并没有去删除之前的 css 代码实现呢
`[`${prefixCls}-two-chinese-chars`]: hasTwoCNChar && mergedInsertSpace && !innerLoading,`
  ```
useEffect(() => {
    // FIXME: for HOC usage like <FormatMessage />
    if (!buttonRef || !(buttonRef as any).current || !mergedInsertSpace) {
      return;
    }
    const buttonText = (buttonRef as any).current.textContent;
    if (needInserted && isTwoCNChar(buttonText)) {
      if (!hasTwoCNChar) {
        setHasTwoCNChar(true);
      }
    } else if (hasTwoCNChar) {
      setHasTwoCNChar(false);
    }
  }, [buttonRef]);
```
但是这个 hasTwoChar 应该在 spaceChildren 处理后，应该总是false，所以感觉这段代码应该没啥存在意义了吧？cc 大佬 @li-jia-nan
