### ISSUE TITLE
select组件

### ISSUE THREAD

**Issue by longang520** [ant-design/ant-design#4204]
动态渲染的时候,根据某些值进行筛选,无法返回空

`
return this.state.searchList.map(function (item, index) {
           if(this.cacheUserList[item.Key]) return "";
            return <option key={item.Key} value={item.Key} label={item.Name} disabled={this.cacheUserList[item.Key]}>
                <div className="searchUserOption">
                    <div className="headImg">
                        <HeadImg className="img" userKey={item.Key} />
                    </div>
                    <div className="userInfo">
                        <div className="name">
                            {item.Name}
                        </div>
                        <div className="unit">
                            {item.Info}
                        </div>
                    </div>
                </div>
            </option>;
        }.bind(this))
`

**Comment by yesmeck** [comment]
请按模板来提 issue。

**Comment by longang520** [comment]
谢谢.
