### ISSUE TITLE
form里的label换行了以后文本内容被截掉了一点

### ISSUE THREAD

**Issue by Vantown** [ant-design/ant-design#42057]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

一个换行的label就可以，我放的地址是你们官网示例的地址，你们官网示例上也有这个问题，只不过被截掉的区域很小，部分汉字才能发现

### What is expected?

汉字不被截掉

### What is actually happening?

汉字被截掉

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18 |
| System | win11 |
| Browser | chrome |

**Comment by BoyYangzai** [comment]
你的意思是 label的盒子高度要随着 label换行的增加而变高吗 那样会影响整个form的布局吧 @Vantown

**Comment by Vantown** [comment]
> 你的意思是 label的盒子高度要随着 label换行的增加而变高吗 那样会影响整个form的布局吧 @Vantown
![image](https://user-images.githubusercontent.com/29136022/235087467-70b6a3c9-935d-4292-baab-669764d5c2e8.png)

如果不撑高的话那不是最多只能放两行的label了吗？而且两行换行也会有部分汉字显示不全，这样相当于1行文字是最佳显示效果，这样这个labelWrap不就失去意义了吗？既然有labelWrap控制是否换行了，那不允许换行的时候超长了显示为省略号禁止换行，允许换行的时候就撑高，这样通过labelWrap用户自己选择是否撑高+换行怎样？

**Comment by BoyYangzai** [comment]
允许换行之后虽然盒子没有变大，但是文本可以正常预览 感觉这才是大部分用户的使用体验 部分汉字显示不全是什么原因 自己设置了overflow hidden吗
如果设置labelWrap后 少部分用户想让label盒子可以随着换行而增高 或许可以自己手动通过className加css来实现 @Vantown

**Comment by Vantown** [comment]
> 允许换行之后虽然盒子没有变大，但是文本可以正常预览 感觉这才是大部分用户的使用体验 部分汉字显示不全是什么原因 自己设置了overflow hidden吗 如果设置labelWrap后 少部分用户想让label盒子可以随着换行而增高 或许可以自己手动通过className加css来实现 @Vantown

没修改，这个示例包括截图都是你们官网的代码，像那个换行功能，第一行的字段和第二行的字段我都放需要3行才能显示全的内容，第一行的字段的label和第二行字段的label那不直接重叠一起了吗？这样的也不处理吗？

**Comment by Vantown** [comment]
> https://codepen.io/pen?&editors=001

最顶上有一个  https://codepen.io/pen?&editors=001

**Comment by Vantown** [comment]
> Hello @Vantown. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @Vantown, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

最顶上有一个   https://codepen.io/pen?&editors=001

**Comment by afc163** [comment]
> https://codepen.io/pen?&editors=001

这是一个空的 codepen 。
