### ISSUE TITLE
Allow changing the thickness of progress bar when type is circle

### ISSUE THREAD

**Issue by kevgilmore** [ant-design/ant-design#42052]
### What problem does this feature solve?

When creating a large circle progress bar the thickness becomes an issue, because it isn't relative to it's size. When using size about 500 it becomes so thick it changes the look and style too much and doesn't look good.

### What does the proposed API look like?

Currently you can pass in `size={[500, 20]}` with 20 being the thickness, so the api is already able to accept the config. Except when combined with `type=circle` the thickness is ignored.

**Comment by BoyYangzai** [comment]
maybe when `type = circle`, you can use `strokeWidth` to change it's thickness
![image](https://user-images.githubusercontent.com/94534613/235076508-3313179e-cc6d-422a-b377-6788784f2d00.png)
![image](https://user-images.githubusercontent.com/94534613/235076557-b8dc5dd5-b376-4dbe-9738-05b54e5bf51e.png)
