### ISSUE TITLE
BUG: Missing ConfigProvider locale for table onFilterDropdown buttons ("RESET", "OK").

### ISSUE THREAD

**Issue by svyatoslavratov** [ant-design/ant-design#42069]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/immutable-grass-5vsb06?file=/src/App.tsx)

### Steps to reproduce

1. Add ConfigProvider with locale property.
2. Add Table component with column with onFilter option

### What is expected?

- Button ok with text "OK"
- Button reset with text "RESET"

### What is actually happening?

- Empty button text

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2.0 |
| System | macOS Monterey 12.0.1 |
| Browser | Version 112.0.5615.49 (Official Build) (arm64) |

---
For another components (ex. Modal buttons has text). That logic expected for onFilter column. Maybe missing onFilter column locale in merge ConfigProvider locale options.

**Comment by kiner-tang** [comment]
let me try to fix it.

**Comment by BoyYangzai** [comment]
you should use the `locale` as AntD demo 
https://ant.design/components/config-provider-cn#components-config-provider-demo-locale
`import enUS from 'antd/locale/en_US';` or
`import zhCN from 'antd/locale/zh_CN';`
and 
`locale = { enUS/ zhCN }`
if you do as demo , the text will be correct show
the reason why you can't show it's text is that there is not correct `locale` Object from `locale` props
@svyatoslavratov
