### ISSUE TITLE
Tree 无法 render 子 TreeNode

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#4206]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: MacOS
- 浏览器及其版本: Chrome 54.0.2840.98
- React 版本: 15.4.1

#### 您做了什么？请提供尽可能详细的重现步骤。

使用 Tree，并且使用官网的第一个例子

#### 您期待的结果是:

像官网一样正常显示

#### 实际上的结果是:

没有 render children

#### 调试到的问题

首先我使用的代码完全与官网一致，我是复制粘贴到我自己项目中的。然后我调试了一下：
https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L202
https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L205
上面两个地方的 `children.type === TreeNode` 和 `item.type === TreeNode` 都返回了 false，导致 newChildren 没有被重新赋值，让后面的 render 直接忽略掉了 children。不知道是不是我用的 webapck 或者 babel 的影响？这里用 reference 去比较是不是也不太好？

#### 可重现的在线演示

无法在 code pen 中重现。。。应该是跟我自己的环境有关系

**Comment by yesmeck** [comment]
用了 react-hot-reload?

**Comment by afc163** [comment]
应该是同一个问题：https://github.com/ant-design/ant-design/issues/3550
