### ISSUE TITLE
ant design datePicker

### ISSUE THREAD

**Issue by FatimeyiZahra** [ant-design/ant-design#42087]
### Reproduction link

[https://ant.design/components/date-picker#localization](https://ant.design/components/date-picker#localization)

### Steps to reproduce

Im using ant design DatePicker component and i wanna see calendar in azerbaijan language.but i see days of the week in english language. locale change only "today" text to azerbaijan language. But i worked well at antd v4.23.4

import React from "react";
import dayjs from "dayjs";
import "dayjs/locale/zh-cn";
import locale from "antd/es/date-picker/locale/az_AZ";
import { ConfigProvider, DatePicker } from "antd";
const Date = () => {
  return (
    <>
      <ConfigProvider locale={locale}>
        <DatePicker locale={locale} />
      </ConfigProvider>
      ;
    </>
  );
};

export default Date;

### What is expected?

Im using ant design DatePicker component and i wanna see calendar in azerbaijan language.but i see days of the week in english language. locale change only "today" text to azerbaijan language. But i worked well at antd v4.23.4

### What is actually happening?

Im using ant design DatePicker component and i wanna see calendar in azerbaijan language.but i see days of the week in english language. locale change only "today" text to azerbaijan language. But i worked well at antd v4.23.4

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | react 18.2.0 |
| System | windows, ios |
| Browser | chrome, safari |

**Comment by BoyYangzai** [comment]
I looked up the source code and found that the language file needed for dayjs is missing here 
But the last time I saw the code change was three years ago, and it seems to be an old problem.
![image](https://user-images.githubusercontent.com/94534613/235325997-eaaeff57-c0d2-48bf-96e4-9e51f490f545.png)
I added `require` to dynamically fetch the required language file and it works just like it should
![image](https://user-images.githubusercontent.com/94534613/235326031-9f808fba-7be8-4387-913d-ab8ddb0788a5.png)
![image](https://user-images.githubusercontent.com/94534613/235326056-f634a7f5-a7cd-406d-b503-4f547d1d6c60.png)
 But I'd better consult with the official people first
@zombieJ @li-jia-nan

**Comment by FatimeyiZahra** [comment]
Thank you, all i can do is wait or i can fix it in my project?

**Comment by BoyYangzai** [comment]
> Thank you, all i can do is wait or i can fix it in my project?

i am sorry，you should wait for it

**Comment by FatimeyiZahra** [comment]
Thank you, it work correctly now.
