### ISSUE TITLE
tsc error with typescript@2.1

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4208]
```
antd-tools run compile
components/modal/confirm.tsx(92,7): error TS2531: Object is possibly 'null'.
components/tooltip/index.tsx(127,40): error TS2345: Argument of type 'ReactElement<any> | (undefined & ReactElement<any>) | (null & undefined) | (null & ReactElement<a...' is not assignable to parameter of type '{}'.
  Type 'undefined' is not assignable to type '{}'.
components/tooltip/index.tsx(128,24): error TS2532: Object is possibly 'undefined'.
components/tooltip/index.tsx(128,30): error TS2339: Property 'props' does not exist on type 'ReactElement<any> | (undefined & ReactElement<any>) | (null & ReactElement<any>) | (string & unde...'.
  Property 'props' does not exist on type 'string & undefined'.
components/tooltip/index.tsx(143,33): error TS2345: Argument of type 'ReactElement<any> | (undefined & ReactElement<any>) | (null & undefined) | (null & ReactElement<a...' is not assignable to parameter of type 'ReactElement<any>'.
  Type 'undefined' is not assignable to type 'ReactElement<any>'.
[14:08:49] TypeScript: 5 semantic errors
[14:08:49] TypeScript: emit succeeded (with errors)
```

And travis is ok.

```
$ tsc -v
2.0.10
```

**Comment by yesmeck** [comment]
```
$ tsc -v
Version 2.1.4
```

这个是没问题。

**Comment by afc163** [comment]
发现是 https://github.com/lozinsky/typescript-babel-jest 依赖了 typescript@2.1。然后使用 tnpm 安装时，antd-tools 优先使用了 2.1 版本导致报错。

我们需要优先适配下 2.1.4？

**Comment by yesmeck** [comment]
这个 `typescript-babel-jest` 最好换成 [ts-jest](https://github.com/kulshekhar/ts-jest)，现在用 `typescript-babel-jest` 统计出来的 coverage 是错误的，不过现在 ts-jest 有个问题 https://github.com/kulshekhar/ts-jest/issues/63 ，不知道我们现在配置 `"jsx": "preserve"` 目的是什么？

**Comment by bang88** [comment]
配置`jsx` 为`preserve`可以不经过`TypeScript`处理`React`. 编译出来的 js 跟我们写es6一样.

**Comment by benjycui** [comment]
@yiminghe 这个问题我也想不通。

> 不知道我们现在配置 "jsx": "preserve" 目的是什么？

**Comment by warmhug** [comment]
配置 preserve ，估计是保留给 babel-presets-react 来处理

**Comment by yesmeck** [comment]
@bang88 @warmhug 你们说的都是 `preserve` 的作用，但是让 babel 去处理的目的是什么？

**Comment by bang88** [comment]
使用babel的各种plugins，如果typescript直接编译出来的话就不需要babel了。

**Comment by infeng** [comment]
typescript直接编译的话，babel-plugin-import就起不到作用了

**Comment by benjycui** [comment]
但是就算提前把 `<div />` 编译成 `React.createElement('div')` 也不会影响其他 babel-plugin 的行为吧。

**Comment by benjycui** [comment]
2.1.x 正式发布了 https://github.com/Microsoft/TypeScript/releases/tag/v2.1.4

其实搞不懂 TypeScript 的版本号规则。。

**Comment by bang88** [comment]
😭

**Comment by infeng** [comment]
好像beta的时候版本也会递增，跟webpack一样

**Comment by benjycui** [comment]
antd 依赖的 TypeScript 升级到 2.1.x 了。

@yesmeck typescript-babel-jest 的问题，有必要的话，另起一个 issue 记录。

**Comment by yesmeck** [comment]
splitObject 可以去掉了。

**Comment by warmhug** [comment]
antd-mobile 谁来帮忙升级下

**Comment by benjycui** [comment]
> splitObject 可以去掉了。

已去。

**Comment by benjycui** [comment]
@warmhug antd-mobile 升级 antd-tools 的话，还要处理 tslint 的问题吧。。

**Comment by warmhug** [comment]
lint 规则先忽略掉
