### ISSUE TITLE
Allow developers to control which Cascader tags (in multiple mode) have the "clear" button and which don't

### ISSUE THREAD

**Issue by georgeciobanu** [ant-design/ant-design#42093]
### What problem does this feature solve?

When using the Cascader in multiple mode each tag that gets created (each selected option) can be cleared using the little x button. I would like to be able to enable/disable the x button on each tag individually.

I need it in order to not allow the user to clear some options until certain conditions are satisfied.

I love the work you do (thank you so much), this is a lower priority item for me but I would use it as soon as you implement it!

### What does the proposed API look like?

Probably a "clearable" boolean parameter that defaults to true on every single Option.

**Comment by georgeciobanu** [comment]
For the record,. I managed to achieve this by using diplayRender to draw custom tags

**Comment by afc163** [comment]
Could you provide a codesandbox for those who have same requirement.

**Comment by georgeciobanu** [comment]
Apologies, I was wrong: in "multiple" mode a custom displayRender function renders each selectedOption within a closable Tag, and that cannot be changed.

Here's an example https://codesandbox.io/s/custom-display-render-cascader-0ilkst?file=/demo.js

I would love to be able to have full control over what is rendered for each option in multiple mode as well. In other words, when a custom displayRender is provided as a parameter in "multiple" mode, I would prefer to have a simple <div> container as the render parent for each selected option instead of a closable tag (but I have to think through it).
