### ISSUE TITLE
表单有一个很低级的错误

### ISSUE THREAD

**Issue by Midas-Li** [ant-design/ant-design#42092]
### Reproduction link

[http://xxxx](http://xxxx)

### Steps to reproduce

```
import React                 from 'react';
import {Button, Form, Input} from 'antd';

function AddAdmin() {
  // const [form] = Form.useForm();

  const onFinish = (values) => {
    console.log(values);
  };

  return (
    <Form name = "basic" autoComplete = "off" onFinish = {onFinish}>
      <Form.Item label = "User" name = "arqr"
                 rules = {[{required: true, message: '请输入数据'},]}
      > <Input/>
      </Form.Item>
      <Form.Item> <Button type = "primary" htmlType = "submit">提交</Button> </Form.Item>
    </Form>
  );
}
```

export default AddAdmin;
使用这个组件，会发现多次输入，表单无法得到新值！
但是如果我把源码中Input前的空格删除，即是>与<之间的空格，删除，就会正常！！

### What is expected?

点提交，表单每次都能获得Input输入的值

### What is actually happening?

多次输入，点提交，表单无法得到新值！

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18 |
| System | win 2012 r2 |
| Browser | chrome |

**Comment by Yuiai01** [comment]
好奇怪的问题，能提供一个在线的 demo 链接吗？

**Comment by Midas-Li** [comment]
我没有云服务器，只有普通电脑。如果要提供在线demo,应该如何弄？告诉一下我步骤，我会很快弄好。
或者你可以新建一个普通的react 18项目，安装最新的antd在Index.js使用这个组件，就可以马上重现这个bug.什么特殊条件也不需要。

**Comment by Yuiai01** [comment]
@Midas-Li  你看看是不是这样子的 https://codesandbox.io/s/ji-ben-shi-yong-antd-5-4-6-forked-cci0fk?file=/demo.tsx

**Comment by Midas-Li** [comment]
对的。
我在你提供的地址中运行了这个实例，能重现bug,程序只要特殊情况下（只要>和<之间有个空格）就可以重现。以下是控制台的输出。
{arqr: "1234"}
{arqr: "5532"}
Warning: [antd: Form.Item] A `Form.Item` with a `name` prop must have a single child element. For information on how to render more complex form items, see https://u.ant.design/complex-form-item. 
{arqr: "5532"}
{arqr: "5532"}

**Comment by Midas-Li** [comment]
1234是我在没有加空格之前输入的，然后在代码加了空格后，再在文本框再输入，可以看到数值一直不变。

**Comment by Yuiai01** [comment]
> 

可以提供一张你运行异常的代码截图么？我这边没法按照你描述的那样保存运行代码...

**Comment by Yuiai01** [comment]
> 1234是我在没有加空格之前输入的，然后在代码加了空格后，再在文本框再输入，可以看到数值一直不变。

我复现出来了，但感觉这不是 antd 的问题
![image](https://user-images.githubusercontent.com/112228030/235387685-d02d19fc-4f35-4f6f-8900-7b480db4d01a.png)

**Comment by Midas-Li** [comment]
那为什么多加一个空格，表单就无法更新值？你把rules注释下，就可以更清楚了解到，有空格的情况下，表单内容无法更新值，但是空格不要后，一切都正常。

**Comment by Yuiai01** [comment]
> 那为什么多加一个空格，表单就无法更新值？你把rules注释下，就可以更清楚了解到，有空格的情况下，表单内容无法更新值，但是空格不要后，一切都正常。

问题的原因是由于 react 将空格识别为 children 了，form 表单没控制到 input...

**Comment by Midas-Li** [comment]
上图的warning应该是antd给出的吧，antd能检测到这些无效的内容，是否在内部也要去掉无意义的children(空格)，并不要给出waring?否则多个空格就出现waring和这个怪问题，会与用户很迷惑...

**Comment by Midas-Li** [comment]
这个问题我花了很大力气才找出来，是看一个视频教程，发现为什么人家表单能输入，我的不能。我用最小系统法慢慢排查出来。

**Comment by Yuiai01** [comment]
> 上图的warning应该是antd给出的吧，antd能检测到这些无效的内容，是否在内部也要去掉无意义的children(空格)，并不要给出waring?否则多个空格就出现waring和这个怪问题，会与用户很迷惑...

关于空格，由于 react 中 children 可以是任何内容，因此将空格识别为 children 我认为是一种正确的行为。warning 出现的原因是由于检测到传入空格作为 children，针对错误的用法给出 warning 这也是正确的行为。antd 接收到的 children 见下图：
![image](https://user-images.githubusercontent.com/112228030/235392487-9707ab52-6720-4103-9c79-48fc7fd29d22.png)

**Comment by Yuiai01** [comment]
> 这个问题我花了很大力气才找出来，是看一个视频教程，发现为什么人家表单能输入，我的不能。我用最小系统法慢慢排查出来。而且好像有时能输入，有时会出问题，当时真是莫名其妙。

问题的根本原因是因为组件标签堆在一起了，或许可以用 prettier 或者其他代码格式化工具格式化一波代码来杜绝这种问题。

**Comment by Midas-Li** [comment]
> > 这个问题我花了很大力气才找出来，是看一个视频教程，发现为什么人家表单能输入，我的不能。我用最小系统法慢慢排查出来。而且好像有时能输入，有时会出问题，当时真是莫名其妙。
> 
> 问题的根本原因是因为组件标签堆在一起了，或许可以用 prettier 或者其他代码格式化工具格式化一波代码来杜绝这种问题。

这是为了让行数看起来没有那么多。太长了，浏览就不方便。这个问题最少warning要报告得详细点,所产生可能严重的效果。

**Comment by BoyYangzai** [comment]
> 这是为了让行数看起来没有那么多。太长了，浏览就不方便。这个问题最少warning要报告得详细点,所产生可能严重的效果。

![22414736ea4deb9fe7019dcaad4415fd](https://user-images.githubusercontent.com/94534613/235470594-3137a439-6817-45bd-a6c6-2b56d6fa6409.png)
这确实是一个很边缘的case，这是React识别节点的机制导致的
可以这样修复 https://github.com/ant-design/ant-design/pull/42099
@zombieJ @li-jia-nan @Yuiai01 @Midas-Li cc

**Comment by Wxh16144** [comment]
这个问题, 我思考的解决方案是在开发环境下控制台打印错误提示更合适一些, 而不是通过条件去过滤无效 children, 本来 Form.Item 就是只期望有且仅有一个受控的子组件. 🤔

**Comment by yoyo837** [comment]
> 那为什么多加一个空格，表单就无法更新值？你把rules注释下，就可以更清楚了解到，有空格的情况下，表单内容无法更新值，但是空格不要后，一切都正常。

加了其他的就相当于自定义组件, 需要自己接受value和onChange的受控

**Comment by yoyo837** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/6134547/236594440-66b7b1d1-7677-42da-b15d-f22f77fdbf38.png">

**Comment by afc163** [comment]
> 下图的第一个组件怎么都用不了

![图片](https://user-images.githubusercontent.com/507615/236594392-aec975d8-d83f-4630-bd80-24b4a1a49e9a.png)

类似这样带个 `，` 就破坏 Form.Item 数据流绑定的，确实违背开发者的直觉，相信很多人都踩过坑。

**Comment by yoyo837** [comment]
底层实现无非就是让`<Input />` 能被`cloneElement`传入`value`和`onChange`, 改变children结构如果无法传入, 就失效.

**Comment by Midas-Li** [comment]
> 这个问题, 我思考的解决方案是在开发环境下控制台打印错误提示更合适一些, 而不是通过条件去过滤无效 children, 本来 Form.Item 就是只期望有且仅有一个受控的子组件. 🤔

这个可行但不理想，因为有时代码后面维护，在集成测试时小改动，不小心又加了空格（即时按format命令也会加)，还是会错误。而错误信息，开发者的眼睛不会老盯着控制台不放，没有打开控制台还是看不到。试想下系统中这么多个form,一个form无疑就是埋下一个地雷，只是你不知道什么时候会爆。

**Comment by yoyo837** [comment]
任何不小心不应该由程序买单吧?

**Comment by yoyo837** [comment]
就好比你不小心给字符串值多打了一个空格, 程序以什么标准来判断是不是不小心的呢

**Comment by Midas-Li** [comment]
如果不小心在字串加了个空格，造成程序错误，我可以使用单元测试出问题来，这好比会计中的试算平衡的原理。
但是form是在集成测试阶段，为了这个问题还要建测试用例或者自动测试，是不是太没有必要了？

**Comment by yoyo837** [comment]
这个设计这么久了, 也只有今天这个issue提出了这样的问题,  没有出现第二个.  是否你们的团队工具本身配置或者开发风格容易造成这样的问题? 个人认为是本问题won't fix, 不过核心成员可能有不同的看法.

**Comment by yoyo837** [comment]
最多在form组件里加个警告

**Comment by heiyu4585** [comment]
> 这个问题, 我思考的解决方案是在开发环境下控制台打印错误提示更合适一些, 而不是通过条件去过滤无效 children, 本来 Form.Item 就是只期望有且仅有一个受控的子组件. 🤔

个人感觉 多加个空格是违反编程直觉的吧, 同意加个warning的方案.
具体等大佬们定吧

**Comment by yoyo837** [comment]
> > > 这个问题我花了很大力气才找出来，是看一个视频教程，发现为什么人家表单能输入，我的不能。我用最小系统法慢慢排查出来。而且好像有时能输入，有时会出问题，当时真是莫名其妙。
> > 
> > 
> > 问题的根本原因是因为组件标签堆在一起了，或许可以用 prettier 或者其他代码格式化工具格式化一波代码来杜绝这种问题。
> 
> 这是为了让行数看起来没有那么多。太长了，浏览就不方便。这个问题最少warning要报告得详细点,所产生可能严重的效果。

还有你说的行数问题, 靠手工敲格式以达到“想要的易读”目的, 难以在团队里保持风格一致, 现代开发都是统一开发工具和格式化配置, 比如行宽, 属性是否自动换行等等.

**Comment by Midas-Li** [comment]
我就不明白，为啥就不能过滤这些无效children? 既然它们都是无效，还是有害的，留下来干什么？string处理还有trim函数。

> 还有你说的行数问题, 靠手工敲格式以达到“想要的易读”目的, 难以在团队里保持风格一致, 现代开发都是统一开发工具和格式化配置, 比如行宽, 属性是否自动换行等等, 稍有不符合配置的直接eslint报错, 比如prettier与eslint的集成.

我是个人开发，代码只要我能看懂就行。prettier和eslint我觉得它们是增强了一点功能，好象可有可无。webstorm自带格式化我就觉得够用。所以我觉得使用它们暂没有必要。当然这些在不断的开发积累中也许慢慢改变。但是现阶段我就知道这么多。

**Comment by yoyo837** [comment]
确实不必要, 其他的不赘述了, 等核心成员看看...

**Comment by MadCcc** [comment]
抛开这个问题而言的话，推荐还是使用 prettier 或者 eslint 或者其他代码规范工具，人不是机器，不能写出完美的代码。今天是多了一个空格，下次就可能是其他问题，也许与 antd 无关。好的代码规范对一个应用很重要。

**Comment by zombieJ** [comment]
= =，有 wanring 的。这个 https://codesandbox.io/s/ji-ben-shi-yong-antd-5-4-6-forked-cci0fk?file=/demo.tsx 打开 console 就能看到：

<img width="522" alt="截屏2023-05-08 10 58 46" src="https://user-images.githubusercontent.com/5378891/236724199-228f5a4c-dab1-485d-afcd-2ced73e931e4.png">

**Comment by zombieJ** [comment]
> 抛开这个问题而言的话，推荐还是使用 prettier 或者 eslint 或者其他代码规范工具。人不是机器，不能写出完美的代码。今天是多了一个空格，下次就可能是其他问题，也许与 antd 无关。好的代码规范对一个应用很重要。

+1，lint 工具是很有帮助的。如果真的不想搞，就 HOC 兜个底，但是我个人觉得是没有必要的：https://codesandbox.io/s/ji-ben-shi-yong-antd-5-4-6-forked-x1epiw?file=/demo.tsx

**Comment by li-jia-nan** [comment]
我的想法是，对于库来说，在确保自己不崩溃的情况下，尽可能提示用户，而不是自行帮用户做决策

**Comment by Midas-Li** [comment]
初学不知道prettier 或 eslint，也许它们是生于ide不发达的年代，但随着ide的发展，webstorm的自带的format和设置我也认为足够。是否要考虑到初学情况或个人风格？
这个空格的产生，就webstorm的format而言，在某些设置和条件下满足下就会自动插入空格。即使你当时把空格删除。所以代码是有机会在后来也产生bug。只要我轻轻format一下就出现。相当危险。而format是不会在字串插入空格，而造成程序错误。所以字串插入空格造成程序错误，的确是程序员的问题，这个不冤。但是format一下就产生bug，对程序员来说太冤。

这个warning我也知道，但信息量也不够完整，它也没有说到可能产生严重的效果。warning的出现，并没有说这个窗体用不了，自然会选择忽略。更重要的是初学者并不知道空格也是一个children。

**Comment by yoyo837** [comment]
警告改为抛出错误如何?

**Comment by Midas-Li** [comment]
我觉得，不增加一些代码，让用户处理，是为了减少耦合，用户有更多自主权。但是这些无效符号，有没有可能用户也会去绑定，如果觉得这种情况是零，就不怕对无效符号做个filter.完全能100%放心这样做。

**Comment by yoyo837** [comment]
一个空格, 一个都逗号是React或者html合法的东西, 只是Form.Item 里需要单个而已. “无效符号”的假设是有条件成立, 不是无条件成立.

**Comment by bolosea** [comment]
自己react不会就怪人家的组件有问题,挺搞笑的。。

**Comment by Midas-Li** [comment]
> 自己react不会就怪人家的组件有问题,挺搞笑的。。

既然各位管理员都给出各种fix回复，就已经承认这也是一个问题了。

**Comment by yoyo837** [comment]
fix是相对应用来说, 对应用是问题, 对antd来说是错误使用.

**Comment by Midas-Li** [comment]
> > 抛开这个问题而言的话，推荐还是使用 prettier 或者 eslint 或者其他代码规范工具。人不是机器，不能写出完美的代码。今天是多了一个空格，下次就可能是其他问题，也许与 antd 无关。好的代码规范对一个应用很重要。
> 
> +1，lint 工具是很有帮助的。如果真的不想搞，就 HOC 兜个底，但是我个人觉得是没有必要的：https://codesandbox.io/s/ji-ben-shi-yong-antd-5-4-6-forked-x1epiw?file=/demo.tsx

一开始没留意你链接后的代码,以为还是我写的那份，现在看过了，原来重封装组件和过滤，这个办法也可以。

**Comment by zombieJ** [comment]
> 一开始没留意你链接后的代码,以为还是我写的那份，现在看过了，原来重封装组件和过滤，这个办法也可以。

推荐还是 lint 优先哈，组件层面能做的就是尽量多给 warning 而不是让`错误的使用出现正确的表现`，否则就相当于帮助用户更方便的埋坑了。
