### ISSUE TITLE
input样式问题

### ISSUE THREAD

**Issue by Jieraaa** [ant-design/ant-design#4209]
#### 发生问题的环境是：

- antd 版本:2.5.1
- 操作系统及其版本:mac 10.12.1 
- 浏览器及其版本:

#### 实际上的结果是:
ant-design/components/input/style/search-input.less的28行
&:hover .@{ant-prefix}-input-search:not[disabled]
实际上应是:
&:hover .@{ant-prefix}-input-search:not([disabled])
这个问题导致在使用webpack打包使用postcss-selector-not中的balanced-match返回undefined的错误

**Comment by afc163** [comment]
来个 PR ~
