### ISSUE TITLE
Select: selected value is not updated when options are updated 

### ISSUE THREAD

**Issue by jeanbmar** [ant-design/ant-design#42100]
### Reproduction link

[https://stackblitz.com/edit/react-ubbcst?file=demo.tsx](https://stackblitz.com/edit/react-ubbcst?file=demo.tsx)

### Steps to reproduce

- Open https://stackblitz.com/edit/react-ubbcst?file=demo.tsx
- Select "bar" option
- Wait 8s timeout
- Open select: "bar" option is selected, "baz" option is listed

### What is expected?

Selected option should update to "baz" as well

### What is actually happening?

Selected option does not update

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2 |
| System | Windows 10 19045.2846 |
| Browser | Chrome 111.0.5563.147 |

**Comment by BoyYangzai** [comment]
You can achieve your goal by using the `value` property
![image](https://user-images.githubusercontent.com/94534613/235474271-7aabb120-6feb-4e36-afcb-b78b3a17a9ef.png)
When you `setOptions`, at the same time `setValue`
Only you need to handle the change of `value` with `onSelect`

**Comment by jeanbmar** [comment]
> maybe you can achieve your goal by using the `value` property ![image](https://user-images.githubusercontent.com/94534613/235474271-7aabb120-6feb-4e36-afcb-b78b3a17a9ef.png) When you `setOptions`, at the same time `setValue` Only you need to handle the change of `value` with `onSelect` @jeanbmar

Indeed this is a good work-around thank you
