### ISSUE TITLE
Popover closes when mouse pointer (mouse up) is outside content

### ISSUE THREAD

**Issue by mkomissarov** [ant-design/ant-design#42114]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r5ej94)

### Steps to reproduce

1. Open popover with any trigger
2. Select text in the popover window with the mouse (or in input inside popover)
3. "Mouseup" outside of the popover content

**v.4:**
![Screenshot_14042023_at_130737](https://user-images.githubusercontent.com/61121083/235863403-562890d1-08a8-4480-aeaa-1e49ae1a299c.gif)

**v.5:**
![Screenshot_14042023_at_130516](https://user-images.githubusercontent.com/61121083/235863427-f1a76c1b-c762-470e-9b4b-4e5720d19c1d.gif)

### What is expected?

Popover remains open, text selected

### What is actually happening?

Popover closes

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 17.0.2 |
| System | macos |
| Browser | Chrome |

---
Before the release of the 5th version, our team actively used inputs / textareas in popovers. After the update, this became inconvenient, popovers are closed if you select any text and inadvertently on mouseup outside the popover container. In the 4th version, the bug is not reproduced.

**Comment by SinaMicrocis** [comment]
this problem didn't solve?
