### ISSUE TITLE
Can't use antd with create-react-app

### ISSUE THREAD

**Issue by ga12ru12** [ant-design/ant-design#4211]
I'm using the [create-reatc-app](https://github.com/facebookincubator/create-react-app) of facebook's recommendation. I like it because it create react app with no build configuration.
But when I import **antd** into my project, it's not working. How can i use **antd** with **create-reatc-app**?

**Comment by yesmeck** [comment]
@ga12ru12 A reproduce repo would help.

**Comment by yesmeck** [comment]
@ga12ru12 If you can provide a repo, I can look into this.

**Comment by afc163** [comment]
https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup

`npm run eject` for custom webpack config.

**Comment by ga12ru12** [comment]
@yesmeck @afc163 Thanks for your answer. But when I eject and add babel config into **package.json**, it's still not working. Maybe I missing some configs, can you help me take a look my project [here](https://github.com/ga12ru12/testAnt) ?
