### ISSUE TITLE
Add 'duration' to useNotification hook config

### ISSUE THREAD

**Issue by IlhanYapici** [ant-design/ant-design#42116]
### What problem does this feature solve?

The documentation recommends to use the hook useNotification rather than the static method notification.config. Currently, the hook miss the property 'duration' that can be found in the static method configuration. (see the link: https://ant.design/components/notification#notificationconfig)

The 'placement' property seems not to work properly in the codesandbox env. Example can be found in this codesandbox : https://codesandbox.io/s/antd-reproduction-template-forked-juqkgr?file=/NotificationProvider.js

### What does the proposed API look like?

Instead of using notification.config({ duration: 7, placement: 'bottomRight', maxCount: 5) we would use notification.useNotification({ duration: 7, placement: 'bottomRight', maxCount: 5 })

**Comment by BoyYangzai** [comment]
@IlhanYapici the `api.open` has the `duration` config
![image](https://user-images.githubusercontent.com/94534613/235975593-3e3dc5ad-575a-4edf-b9d9-aadf0c16dcae.png)
https://ant.design/components/notification#components-notification-demo-duration
