### ISSUE TITLE
Antd carousel 

### ISSUE THREAD

**Issue by RuslanMehdiyev** [ant-design/ant-design#42115]
### Reproduction link

[https://ant.design/components/carousel](https://ant.design/components/carousel)

### Steps to reproduce

 <Carousel
                    arrows
                    autoplay
                    prevArrow={<ArrowLeftOutlined />}
                    nextArrow={<ArrowRightOutlined />}
                  > ... </Carousel>
when I use prevArrows and nextArrows in Carousel it gave me below error 
" React does not recognize the `currentSlide` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `currentslide` instead. If you accidentally passed it from a parent component, remove it from the DOM element." "react-dom.development.js:86 Warning: React does not recognize the `slideCount` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `slidecount` instead. If you accidentally passed it from a parent component, remove it from the DOM element"

### What is expected?

when I use prevArrows and nextArrows in Carousel it gives me errors

### What is actually happening?

when I use prevArrows and nextArrows in Carousel it gives me errors

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | reactJS |
| System | windows |
| Browser | chrome |

**Comment by BoyYangzai** [comment]
@RuslanMehdiyev maybe these can help you
https://github.com/ant-design/ant-design/issues/12479
https://github.com/akiran/react-slick/issues/1195#issuecomment-390383615

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/issues/2051

**Comment by afc163** [comment]
See https://github.com/akiran/react-slick/issues/1195#issuecomment-390383615

**Comment by 0xAl3xH** [comment]
How did you use the comment to fix this? I'm getting a type error 
```
Type '{ children: Element; }' is missing the following properties from type '{ [x: string]: any; currentSlide: any; slideCount: any; children: any; }': currentSlide, slideCount
```
