### ISSUE TITLE
搭配试用Progress和Tooltip组件，控制台报错：findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by luichooy** [ant-design/ant-design#42110]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7j08s7?file=/index.js)

### Steps to reproduce

Tooltip组件和Progress组件搭配试用

### What is expected?

解决报错问题

### What is actually happening?

报错信息如下：

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
```

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2.0 |
| System | Win11 |
| Browser | Edge |

**Comment by BoyYangzai** [comment]
定位了一下问题 应该是因为 rc-resize-observer 用到了 rc-util 中的 `findDOMNode`
![image](https://user-images.githubusercontent.com/94534613/235863895-004bcaac-a2fe-403e-afeb-48b5431a1d29.png)
@zombieJ

**Comment by zombieJ** [comment]
Progress 不支持 ref，所以降级成 `findDOMNode` 了
