### ISSUE TITLE
Not able to update fontWeight style for button , it hardcoded to 400 in Button 

### ISSUE THREAD

**Issue by sumitjhajharia** [ant-design/ant-design#42120]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-m70235)

### Steps to reproduce

There is no way to update fontWeight styling in button , it's hardcoded to 400.

Also observed the same in some more components like divider, where it's hardcoded to -500

### What is expected?

there should be a design token to update based on theme passed by user

### What is actually happening?

not able to  update button font-weight based on values in theme provider

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 17 |
| System | Mac OS 12.0.1  |
| Browser | chrome 112.0.5615.137 |

**Comment by MadCcc** [comment]
There's no `fontWeight` token in current Design Token, and all components have default `font-weight` given by browser.
You could change `font-weight` in style of body or html.
And seems we should remove `fontWeight: 400` for Button.

**Comment by sumitjhajharia** [comment]
we should also do it for typography, tree as they are also hardcoded -     fontWeight: 600 | fontWeight: 500

**Comment by MadCcc** [comment]
> @MadCcc we should also do it for typography, tree as they are also hardcoded - fontWeight: 600 | fontWeight: 500

Try to use `fontWeightStrong` to customize.

**Comment by sumitjhajharia** [comment]
Please check once in these files , i can see them hardcoded as below : 

 in file : antd/es/typography/style/mixins.js 
 `  strong: {
    fontWeight: 600
  },`


In file : antd/es/tree/style/index.js:

` 
[&:not(${treeNodeCls}-disabled).filter-node ${treeCls}-title]: {
          color: 'inherit',
          fontWeight: 500
        },`
