### ISSUE TITLE
Space Compact 样式问题，对于有图标的Input组合样式没有融合

### ISSUE THREAD

**Issue by ByYogi** [ant-design/ant-design#42122]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-spacecompact3-ms91ku?file=/demo.js)

### Steps to reproduce

看第一个Input的右边还是圆的。
![image](https://user-images.githubusercontent.com/111735598/236096103-e767a004-c199-41c7-a0ab-d6e8c63699fc.png)

### What is expected?

能正常融合

### What is actually happening?

无法融合

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2.x |
| System | Win10/Codesandbox |
| Browser | Version 112.0.5615.138 (Official Build) (64-bit) |

**Comment by pengyw97** [comment]
let me go try to fix it
