### ISSUE TITLE
table with scroll enabled leads to misaligned columns with table body

### ISSUE THREAD

**Issue by jwkvam** [ant-design/ant-design#4212]
When I enable scrolling in my table, the columns become misaligned. I don't think this is expected since I don't see this behavior in the ant.design examples.

I'm using:
MacOS Sierra
Chrome 55.0.2883.75
Firefox 50.0.2
Antd 2.5.2

Here is a reproducible demo.

https://codepen.io/anon/pen/VmGLmP?editors=0011

With `scroll = true`
![image](https://cloud.githubusercontent.com/assets/86304/21082898/ca8af848-bf99-11e6-90ff-db97f7821521.png)

With `scroll = false` (desired look)
![image](https://cloud.githubusercontent.com/assets/86304/21082919/2399322e-bf9a-11e6-80a1-ca24401b8289.png)

**Comment by afc163** [comment]
Yes, you have to specify each column's width when `scroll.x` is true.
