### ISSUE TITLE
Input.Password能否不用type=‘password’实现？

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#42125]
### What problem does this feature solve?

<input type='password' />

浏览器会自动填充密码，但我那个地方不想自动填充，现在也没有好的办法解决。

能否不用type=password实现，就是一个普通的type。

### What does the proposed API look like?

<Input.password type='text' />

现在这样写，无效，希望可以支持

**Comment by zombieJ** [comment]
用 `autoComplete`？

**Comment by qingfengmy** [comment]
> 用 `autoComplete`？

不好使吧

**Comment by afc163** [comment]
密码最好使用原生实现，否则无法做到隐藏文字。

**Comment by yoyo837** [comment]
自行state管理 if true Input else Input.Password呗
