### ISSUE TITLE
定制主题-服务端渲染的示例中，Modal.method()创建的对话框没有适配主题

### ISSUE THREAD

**Issue by mirai027** [ant-design/ant-design#42130]
### Reproduction link

[https://github.com/ant-design/create-next-app-antd](https://github.com/ant-design/create-next-app-antd)

### Steps to reproduce

在`/pages/index.tsx`中加入对话去代码

```typescript
confirm({
      title: 'Do you Want to delete these items?',
      icon: <ExclamationCircleFilled />,
      content: 'Some descriptions',
      onOk() {
        console.log('OK')
      },
      onCancel() {
        console.log('Cancel')
      },
})
```

### What is expected?

对话框的按钮为自定义的主题色 `colorPrimary: '#52c41a'`

### What is actually happening?

对话框的按钮主题色依旧是默认的蓝色 `#1677ff`

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome/111.0.0.0 |

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/components/config-provider-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-messageinfonotificationopen-%E6%88%96-modalconfirm-%E7%AD%89%E6%96%B9%E6%B3%95%E5%86%85%E7%9A%84-reactnode-%E6%97%A0%E6%B3%95%E7%BB%A7%E6%89%BF-configprovider-%E7%9A%84%E5%B1%9E%E6%80%A7%E6%AF%94%E5%A6%82-prefixcls-%E5%92%8C-theme
静态方法不支持消费 context，可以替换为 hooks 或者使用 App 组件

**Comment by my3188** [comment]
> https://ant-design.antgroup.com/components/config-provider-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-messageinfonotificationopen-%E6%88%96-modalconfirm-%E7%AD%89%E6%96%B9%E6%B3%95%E5%86%85%E7%9A%84-reactnode-%E6%97%A0%E6%B3%95%E7%BB%A7%E6%89%BF-configprovider-%E7%9A%84%E5%B1%9E%E6%80%A7%E6%AF%94%E5%A6%82-prefixcls-%E5%92%8C-theme 静态方法不支持消费 context，可以替换为 hooks 或者使用 App 组件

你好，可以帮忙看下这个静态方法的样式为什么不生效？App 组件包裹了，但是modal的圆角还是不生效？体验地址见https://codepen.io/my3188/pen/XWyVyBd?editors=0010
