### ISSUE TITLE
Popover 的样式 .ant-popover 添加了 max-width:100% 之后 getPopupContainer 设置为父元素时，存在问题

### ISSUE THREAD

**Issue by defolly** [ant-design/ant-design#42137]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-likybo?file=/index.js)

### Steps to reproduce

在表单中使用选择输入组件，通过Popover 包多 Input 组件来实现，Popover 中放一个Table ，设置宽度为 600px, Popover 设置getPopupContainer = (triggerNode) => triggerNode.parentNode.parentNode，如果不设置，页面滚动时，Popover会错位，设置了之后，弹出框的样式不对，原因是添加了 max-width:100%。

### What is expected?

把 max-width:100% 改为 max-width: min-content

### What is actually happening?

内容超出了外层的宽度

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 17 |
| System | window10 |
| Browser | chrome 110.0.5481.104 |
![image](https://user-images.githubusercontent.com/10161473/236175898-2f3fb375-4a7d-4cef-910d-ba49c260a42f.png)

**Comment by afc163** [comment]
这种情况不好处理，我建议把 getPopupContainer 设置到滚动元素上，而不是 parentNode，否则很容易被 parentNode 上的样式影响。
