### ISSUE TITLE
Tabs组件设置成可编辑，当删除完所有tabs以后，新增功能（加号）也跟着消失。

### ISSUE THREAD

**Issue by antgod** [ant-design/ant-design#4213]
Tabs组件设置成可编辑，当删除完所有tabs以后，新增功能（加号）也跟着消失。业务方提的bug，请尽快修改

**Comment by ddcat1115** [comment]
官网未能重现，https://ant.design/components/tabs-cn/#components-tabs-demo-editable-card

请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/1071
