### ISSUE TITLE
在 iframe 中渲染弹层组件无法正确的展示弹层

### ISSUE THREAD

**Issue by wwsun** [ant-design/ant-design#42131]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-4-24-8-forked-jqe0ji?file=/index.tsx)

### Steps to reproduce

如上面的代码所示，Iframe 中的弹层无法正确打开

### What is expected?

正确打开弹层

### What is actually happening?

弹层没有启动，似乎是 dom 中弹层的动效状态没有正确的执行

<img width="969" alt="image" src="https://user-images.githubusercontent.com/6984035/236122542-79ff3e48-6459-4025-8f6a-633b6d3f0000.png">

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18.x |
| System | mac os |
| Browser | chrome v112 |

**Comment by zombieJ** [comment]
StyleProvider 配置一下样式渲染位置，参考：

https://github.com/ant-design/cssinjs/pull/59/files#diff-d7491960bdbaeadf992ed132b9182d0e5c1bc8789bde8c740b1bcba782f4cf6fR21

**Comment by wwsun** [comment]
antd 4.x 没有 cssinjs 吧
