### ISSUE TITLE
(multi)Select not showing label of initially selected items

### ISSUE THREAD

**Issue by Poltsi** [ant-design/ant-design#42145]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wtx5yc?file=/index.js)

### Steps to reproduce

Use {id, name} as key-name pair in multi-mode Select within a Form, defining fieldNames as {label: 'name', value: 'id'}, and use same structure for both options as well as value attribute. Attempt to pre-populate the Select with some key-value pairs by setting the value-attribute.

### What is expected?

The name for the pre-populated items are displayed.

### What is actually happening?

The name of the prepopulated items is not displayed. Printing out the list shows that the items are undefined. The options input-value is however not undefined.

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2 |
| System | Fedora 38 |
| Browser | Firefox 112.0.1 |

**Comment by afc163** [comment]
See https://codesandbox.io/s/antd-reproduction-template-forked-8gkete?file=/index.js
