### ISSUE TITLE
antd table的defaultExpandAllRows属性，在异步请求数据传来，defaultExpandAllRows：true不生效

### ISSUE THREAD

**Issue by hyy110** [ant-design/ant-design#42148]
### What problem does this feature solve?

antd table的defaultExpandAllRows属性，在异步请求数据传来，defaultExpandAllRows：true不生效

### What does the proposed API look like?

在数据变化或异步请求数据到来时，defaultExpandAllRows：true默认展开所有行

**Comment by zombieJ** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultvalue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88
