### ISSUE TITLE
okButton with htmlType="submit" (in popconfirm) does not trigger native validation

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#42144]
### Reproduction link

[https://gitlab.com/itpm-chat-bot/bot-frontend/-/blob/main/src/components/Messages/MessageCreateForm/ActionButtonRow/Modals/CreateActionBtnModal.jsx](https://gitlab.com/itpm-chat-bot/bot-frontend/-/blob/main/src/components/Messages/MessageCreateForm/ActionButtonRow/Modals/CreateActionBtnModal.jsx)

### Steps to reproduce

1. create react component returning form. Inside it there is input type="url"
1. import Popconfirm
2. set Popconfirm props like okButtonProps={{ htmlType: 'submit'  }}
3. click okButton

### What is expected?

Trigger native validation

### What is actually happening?

Ignore native validation

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome 111 |

---
I use react-hook-form for most validation cases, but it does not processes input type="url". I noticed that native submit button (type="submit") or antd Button (with props htmlType="submit") trigger native url validation, but okButton in Popconfirm component does not. I suspect the same behavior in other components such as Popover and so on

**Comment by afc163** [comment]
Try `getPopupContainer` to make sure `button (type="submit")` rendered inside form element.
