### ISSUE TITLE
spin的icon会比视觉上的高度多6px

### ISSUE THREAD

**Issue by cheapCoder** [ant-design/ant-design#42150]
### Reproduction link

[官方demo](https://ant.design/components/spin-cn#components-spin-demo-inside)

### Steps to reproduce

devtool查看这个[官方demo](https://ant.design/components/spin-cn#components-spin-demo-inside)的样式，ant-spin-dot只有20px高

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/60960561/236374097-f2a2140a-6b78-4d1b-935f-99d2805f828e.png">

而父级ant-spin有26px的高度

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/60960561/236374130-1b382c41-e360-455f-b495-974d6992941f.png">

### What is expected?

父级和子级保持相同的高度

### What is actually happening?

在`容器`这个demo里父级高6px导致并没有完全垂直居中，在`各种大小`这个demo里不同size的spin父级总是比子级高6px

<img width="651" alt="image" src="https://user-images.githubusercontent.com/60960561/236374193-6aad9843-d568-4cb3-b204-eab31f7d8fea.png">

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.0.0 |
| System | macOS Monterey 12.4 |
| Browser | Chrome |

---
调试发现需要给父级子级分别加上`line-height: initial;`, `vertical-align: middle;`才能保持高度一致，我不清楚多出的6px是否是设计如此，以及加样式的方式是否合适，如果可以，我可以补一个pr
![20230505-115614](https://user-images.githubusercontent.com/60960561/236374785-2766c12a-1112-4323-b38f-a61058116f3d.png)

**Comment by zombieJ** [comment]
嗯，是 `line-height` 导致的，加个 `line-height: 1` 就好了。

**Comment by cheapCoder** [comment]
> 嗯，是 `line-height` 导致的，加个 `line-height: 1` 就好了。

我实测只加`line-height`还会是会多2px，从[这个demo](https://codesandbox.io/s/focused-mendeleev-pdm86r?file=/index.html)看起来，看起来svg和img都会撑高父元素宽度
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/60960561/236388136-9db59ddd-f253-44da-92a3-99d2061c91ed.png">

**Comment by afc163** [comment]
给 .ant-spin-spinning 增加 `font-size: 0;` 样式，再给 `.ant-spin-show-text` 还原 font-size 。
