### ISSUE TITLE
DatePicker when used directly inside a Form.Item goes crazy and jumps to future years

### ISSUE THREAD

**Issue by boi87** [ant-design/ant-design#42158]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ve0cit?file=/index.js)

### Steps to reproduce

Clicking inside of the DatePicker shows all dates as selected and any further interaction will make the year jump to random years in the future.

![date picker 1](https://user-images.githubusercontent.com/25410752/236250371-ce0e1d97-75ca-4f81-9a43-6d0dbe33b385.gif)

- In my project, we use `moment` to format dates and I am using the DatePicker like this:
```
<Form.Item>
   <DatePicker />
</Form.Item>
```

I found out that wrapping the DatePicker in a div fixes the issue:
```
<Form.Item>
    <div>
         <DatePicker />
    </div>
</Form.Item>
```

In the CodeSandBox I provided, I am using the DatePicker the same way I do in my project, providing a value with `moment`, and the issue happens as well. However, wrapping it in a div doesn't solve the issue in this case.

### What is expected?

The DatePicker should not jump to random future years or select all dates when it opens.

### What is actually happening?

The DatePicker goes crazy and jumps to next years, and all the date squares appear as selected.

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18.2.0 |
| System | MacOS Ventura 13.3.1 |
| Browser | Chrome Version 112.0.5615.137 (Official Build) (arm64) |

**Comment by zombieJ** [comment]
Replace moment with dayjs in v5

**Comment by afc163** [comment]
@zombieJ 这里能加个 warning 么？

**Comment by fstn** [comment]
Same issue here

**Comment by win9s** [comment]
Same issue for me
![image](https://github.com/ant-design/ant-design/assets/13539755/bd413445-3279-46b6-ab11-f1c4aac305e1)

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774

**Comment by afc163** [comment]
See See https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774
