### ISSUE TITLE
ios 14 Drawer 不能打开

### ISSUE THREAD

**Issue by j787701730** [ant-design/ant-design#42154]
### Reproduction link

[https://ant.design/components/drawer-cn](https://ant.design/components/drawer-cn)

### Steps to reproduce

https://ant.design/components/drawer-cn 用ios14自带浏览器和微信内打不开Drawer, 个人项目中也是如此, 但安卓手机正常. 

### What is expected?

ios 14能打开Drawer

### What is actually happening?

ios 14打不开Drawer

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | ios 14.4.2 |
| Browser | safari 14 |

**Comment by afc163** [comment]
Check https://ant.design/docs/react/compatible-style-cn

**Comment by Milo-Kong** [comment]
大佬想问这个兼容性的问题您解决了啊   江湖救急 我也遇到了 不知道咋解决

**Comment by hanyanxx1** [comment]
![image](https://github.com/ant-design/ant-design/assets/10085134/d3027872-2296-4eaf-9a07-4225e328f97d)
可能是这个属性导致的，用top:0,bottom:0,left:0,right:0，替换一下试试

**Comment by yoyo837** [comment]
> ![image](https://private-user-images.githubusercontent.com/10085134/344729972-d3027872-2296-4eaf-9a07-4225e328f97d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODIzMzksIm5iZiI6MTcxOTg4MjAzOSwicGF0aCI6Ii8xMDA4NTEzNC8zNDQ3Mjk5NzItZDMwMjc4NzItMjI5Ni00ZWFmLTlhMDctNDIyNWUzMjhmOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAxMDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjU0YWE2OWYzZjc0NTU5YWUxOTIxZWEyZjEyN2ZlYTYyYmM5NDBkODVjMDQwMGJmMjdjNGIwMzY2ZDQzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wrK4ot5BJImDJlXYuGlM0BJdoRpVii2pHY5Cexs5jFI) 可能是这个属性导致的，用top:0,bottom:0,left:0,right:0，替换一下试试

自己的browserslist配置不能处理这个吗？

**Comment by hanyanxx1** [comment]
> > ![image](https://private-user-images.githubusercontent.com/10085134/344729972-d3027872-2296-4eaf-9a07-4225e328f97d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODIzMzksIm5iZiI6MTcxOTg4MjAzOSwicGF0aCI6Ii8xMDA4NTEzNC8zNDQ3Mjk5NzItZDMwMjc4NzItMjI5Ni00ZWFmLTlhMDctNDIyNWUzMjhmOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAxMDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNjU0YWE2OWYzZjc0NTU5YWUxOTIxZWEyZjEyN2ZlYTYyYmM5NDBkODVjMDQwMGJmMjdjNGIwMzY2ZDQzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wrK4ot5BJImDJlXYuGlM0BJdoRpVii2pHY5Cexs5jFI) 可能是这个属性导致的，用top:0,bottom:0,left:0,right:0，替换一下试试
> 
> 自己的browserslist配置不能处理这个吗？

没试过配置browserslist，你可以试试。我是那天项目遇到问题急着解决，先用top:0,bottom:0,left:0,right:0这种方式给解决了

**Comment by yoyo837** [comment]
现在没有人手写css了吧？像自动添加兼容前缀什么的都是让工具编译去做。所以我理解 postcss / browserslist 应该是大多数项目都有的
