### ISSUE TITLE
Nextjs 13.4 and app router support for server components

### ISSUE THREAD

**Issue by rodsfreitas** [ant-design/ant-design#42166]
### What problem does this feature solve?

This feature solves the problem of antd components' styles not rendering correctly on server side when used within the new app router. For instance, in a `Select` component, there is a flickering when the page is refreshed and finally the css is applied on client-side.

### What does the proposed API look like?

Antd would support styling Sever Components by outputting css files, as recommended here: https://nextjs.org/docs/app/building-your-application/styling/css-in-js

**Comment by rodsfreitas** [comment]
This is a simple example with a `Button`.

https://codesandbox.io/p/sandbox/thirsty-lake-gv94g8

1. Once in the main index, click on [antd on app router](https://gv94g8-3000.csb.app/antd)
2. once `/antd` is rendering, notice the button style taking a while to be applied.

**Comment by rodsfreitas** [comment]
One workaround is to use https://github.com/ant-design/static-style-extract to extract a static css, and then load it on `app/layout.tsx`, however this is suboptimal, as the entire css file is too large (almost 1mb).

**Comment by cong1223** [comment]
> One workaround is to use https://github.com/ant-design/static-style-extract to extract a static css, and then load it in `app/layout.tsx`, however this is suboptimal, as the entire css file is too large (almost 1mb).
> 
> just thinking out loud here, maybe it would be ideal to
> 
> 1. generate static css more or less like tailwind does, based only on the components that are actually used in the project or
> 2. have a `registry` with `use client ` approach like this: https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-jsx
> 
> I hope it helps!

Hey,buddy! do you happen to have a killer solution for this issue?

**Comment by rodsfreitas** [comment]
> > One workaround is to use https://github.com/ant-design/static-style-extract to extract a static css, and then load it in `app/layout.tsx`, however this is suboptimal, as the entire css file is too large (almost 1mb).
> > just thinking out loud here, maybe it would be ideal to
> > 
> > 1. generate static css more or less like tailwind does, based only on the components that are actually used in the project or
> > 2. have a `registry` with `use client ` approach like this: https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-jsx
> > 
> > I hope it helps!
> 
> Hey,buddy! do you happen to have a killer solution for this issue?

Hey, unfortunately I have no solution for antd. I ended up using this killer solution: [radix ui](https://www.radix-ui.com) with [tailwind](https://tailwindcss.com)

**Comment by quannv** [comment]
> One workaround is to use https://github.com/ant-design/static-style-extract to extract a static css, and then load it in `app/layout.tsx`, however this is suboptimal, as the entire css file is too large (almost 1mb).
> 
> just thinking out loud here, maybe it would be ideal to
> 
> 1. generate static css more or less like tailwind does, based only on the components that are actually used in the project or
> 2. have a `registry` with `use client ` approach like this: https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-jsx
> 
> I hope it helps!

If I use a `registry` with `use client ` approach, can it  be affect to SEO? because I found the client component will contain server component
