### ISSUE TITLE
DatePicker 在 ConfigProvider 设置为 zh_CN 后面板显示仍然有英文

### ISSUE THREAD

**Issue by dnxbf321** [ant-design/ant-design#42170]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-4-6-forked-yro82h)

### Steps to reproduce

sandbox

### What is expected?

月份显示中文

### What is actually happening?

年份是中文，月份是英文

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18 |
| System | macOS |
| Browser | chrome > 100 |

**Comment by yoyo837** [comment]
https://ant.design/components/config-provider-cn#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA

**Comment by yoyo837** [comment]
https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-4-6-forked-mfk20p?file=/demo.tsx

**Comment by dnxbf321** [comment]
不应该这么简单吧，我觉得是 locale 缺少部分值导致的，譬如，我在 zh_CN 文件中添加 monthFormat: 'M月' ，月份就能正常显示了。

以上的解决办法是用 dayjs 来解决 antd 的问题。

**Comment by yoyo837** [comment]
日历里默认依赖的就是 dayjs 呀, dayjs 是 antd的上游包, 依赖它有啥问题?  你手动添加 monthFormat 等值, 无非就是添加 dayjs/locale/zh-cn 这个文件里提供的东西

**Comment by yoyo837** [comment]
默认日期有关操作都是 dayjs 的 对象, 只是缺国际化而已.

**Comment by yoyo837** [comment]
如果喜欢用 dayjs, 也可以使用其他日历库, https://ant.design/docs/react/use-custom-date-library-cn#calendar

**Comment by dnxbf321** [comment]
好的，感谢

**Comment by coderweiweihu** [comment]
我也遇到了这个问题，有点恶心。解决方案就是安装dayjs依赖包，然后配置成中文。
```js
import { DatePicker, ConfigProvider } from "antd";
import zhCN from "antd/locale/zh_CN";

import dayjs from "dayjs";
import "dayjs/locale/zh-cn";

dayjs.locale("zh-cn");

const App = () => {
  return (
    <ConfigProvider locale={zhCN}>
         <DatePicker picker="month" />
    </ConfigProvider>
  )
};
```

**Comment by weiliang903** [comment]
同样的问题，需要更新最 dayjs:
`"dayjs": "1.11.9"`

**Comment by noahge0923** [comment]
`import React from "react"
import dayjs from "dayjs"

import "dayjs/locale/zh-cn"
import locale from "antd/locale/zh_CN"

import { ConfigProvider } from "antd"
import DashboardLayout from "./components/layout/Layout"

dayjs.locale("zh-cn")

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main>
      <ConfigProvider locale={locale}>
        <DashboardLayout>{children}</DashboardLayout>
      </ConfigProvider>
    </main>
  )
}

export default Layout`

日期组件是中文了，但是选择年月日的时候还是英文，该怎么解决？

**Comment by yoyo837** [comment]
> `import React from "react" import dayjs from "dayjs"
> 
> import "dayjs/locale/zh-cn" import locale from "antd/locale/zh_CN"
> 
> import { ConfigProvider } from "antd" import DashboardLayout from "./components/layout/Layout"
> 
> dayjs.locale("zh-cn")
> 
> const Layout = ({ children }: { children: React.ReactNode }) => { return (
> 
> 
> 
> {children}
> 
> 
> )
> }
> export default Layout`
> 
> 日期组件是中文了，但是选择年月日的时候还是英文，该怎么解决？

提供复现

**Comment by leookun** [comment]
当项目中的 dayjs和ant-design依赖的 dayjs 版本不同时，如果包管理工具没有将两个 dayjs 合并为同一个版本，那么dayjs.locale("zh-cn"); 不会生效，因为他只是修改你项目中的 dayjs 的语言，并未影响ant-design内置的 dayjs

我认为如果 ant-design想要与项目共享 dayjs 或者其他时间处理器，是否应该要求外部通过 props传入 dayjs？

我不得不删除我项目中的 dayjs，并且用过npm 的幽灵依赖(实际上是一个 bug)，让 antd的日期回复正常

**Comment by wjljan** [comment]
> 当项目中的 dayjs和ant-design依赖的 dayjs 版本不同时，如果包管理工具没有将两个 dayjs 合并为同一个版本，那么dayjs.locale("zh-cn"); 不会生效，因为他只是修改你项目中的 dayjs 的语言，并未影响ant-design内置的 dayjs
> 
> 我认为如果 ant-design想要与项目共享 dayjs 或者其他时间处理器，是否应该明确要求外部通过 props传入 dayjs？
> 
> 我不得不删除我项目中的 dayjs，并且用过npm 的幽灵依赖(实际上是一个 bug)，让 antd的日期内容正常工作

是这个问题，改为同一个版本后就正常了

**Comment by renny-ren** [comment]
把
```
import zhCN from 'antd/locale/zh_CN'
```
改成
```
import zhCN from 'antd/es/locale/zh_CN'
```
解决

**Comment by echoyl** [comment]
> 把
> 
> ```
> import zhCN from 'antd/locale/zh_CN'
> ```
> 
> 改成
> 
> ```
> import zhCN from 'antd/es/locale/zh_CN'
> ```
> 
> 解决

解决了我的问题。这个问题反复横跳。。。
