### ISSUE TITLE
Modal弹出框层次问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#4217]
#### 您做了什么？请提供尽可能详细的重现步骤。

新建两个弹出框，分别放两个Upload控件，都默认有一张可以点击预览的图片，点击第一个弹出框里的图片预览，图片可以正常展示，关闭第一个弹出框然后打开第二个弹出框点击预览图片，这时候预览图片的弹出框在第一个弹出框下面了

#### 您期待的结果是:

不论点开哪个弹出框的预览图片都可以正常展示

#### 实际上的结果是:

点开第一个弹出框的预览图片可以正常展示，点开第二个弹出框的预览图片，这时候预览图片的弹出框在第二个弹出框下面，被第二个弹出框遮住了，目测应该是弹出框本身是按照第一次被打开来决定层级的，所以当预览图片等弹出框被打开过之后，后面新打开的图片都在它上面

#### 可重现的在线演示

http://codepen.io/anon/pen/VmGmjK?editors=001

**Comment by benjycui** [comment]
你给的 demo 没问题，麻烦再确认一下。

**Comment by yesmeck** [comment]
给 preview 弹出的两个 Modal  设两个不同的 key。
