### ISSUE TITLE
点击 debug 按钮就让所有 demo 都 rerender 了

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42173]
![May-06-2023 11-47-34](https://user-images.githubusercontent.com/507615/236598095-92870387-5e4b-4ab5-8cc0-9e4da37a0835.gif)

- 重现链接：https://ant.design/components/form-cn
- 预期：只影响 debug: true 的 demo。
- 现在：不仅整个页面 rerender 了，非 debug 的 demo 内部也 rerender 了。感觉非常卡。

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/blob/master/.dumi/theme/builtins/DemoWrapper/index.tsx#L78

**Comment by MadCcc** [comment]
这个是不是 dumi 处理下好点？@PeachScript
