### ISSUE TITLE
带页签的卡片中 Tabs 的 size 和 Card 的size 保持一致

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#42176]
### What problem does this feature solve?

带页签的卡片中修改Card的size值，Tabs的size同步变化。
当前情况下 Tab  [size="large"。](https://github.com/ant-design/ant-design/blob/aff6314d116c9fab63bdf05f6a31b08f57258388/components/card/Card.tsx#L122)

### What does the proposed API look like?

api无变化

**Comment by afc163** [comment]
来个 PR 如何？

**Comment by huangkairan** [comment]
我来吧，card size "default" 时 tab size 默认 "large"，用户手动配了 card size 后，tab size 跟随 card size 如何

**Comment by afc163** [comment]
可行
