### ISSUE TITLE
input组件的样式不符合预期

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#42182]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fu2ge6)

### Steps to reproduce

官网提供的demo
设置了style的样式之后 拖动之后的样式被 设计叼了

### What is expected?

样式好看一些 

### What is actually happening?

好丑

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18 |
| System | mac |
| Browser | google |

**Comment by Lliuxs** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/35122287/236610039-62674d57-85f4-4bfb-91e5-d4e7ecbf7609.png">

是否可以限制下位置。 设置了style的高度之后 就不让让往下面拖动了 这样好丑呀 被设计大大叼了

**Comment by 1587315093** [comment]
给 `resize: "none"` 不是解决了么？是希望给高度后组件来自己加 `resize: "none"` 吗

**Comment by afc163** [comment]
4.x 里我专门修过，可能迁移的时候搞丢了：https://codesandbox.io/s/dai-zi-shu-ti-shi-de-wen-ben-yu-antd-4-x-forked-hndosh?file=/demo.tsx

我来看看。

**Comment by zombieJ** [comment]
> 4.x 里我专门修过，可能迁移的时候搞丢了：https://codesandbox.io/s/dai-zi-shu-ti-shi-de-wen-ben-yu-antd-4-x-forked-hndosh?file=/demo.tsx
> 
> 我来看看。

是结构变了 cc @MadCcc

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/41947

**Comment by afc163** [comment]
4.x 里是这么解决的，现在 input 样式又回去了：https://github.com/ant-design/ant-design/commit/3fa274190e19d8387e8eb00450412674956a3660#diff-d28aae5be4c7d25798c9f56158c2d345e5e7e32abd8fa0fbc6cc82e099c0d400R5-R12

**Comment by MadCcc** [comment]
> 4.x 里是这么解决的，现在 input 样式又回去了：[3fa2741#diff-d28aae5be4c7d25798c9f56158c2d345e5e7e32abd8fa0fbc6cc82e099c0d400R5-R12](https://github.com/ant-design/ant-design/commit/3fa274190e19d8387e8eb00450412674956a3660#diff-d28aae5be4c7d25798c9f56158c2d345e5e7e32abd8fa0fbc6cc82e099c0d400R5-R12)

4.x border 是在 textarea 上的，现在还是改到 affix-wrapper 上了。textarea 触发 resize 后把 affixWrapper 的 height 干掉可以。
