### ISSUE TITLE
tree-select 组件样式升级

### ISSUE THREAD

**Issue by whyer11** [ant-design/ant-design#4218]
还有一个需求不知能不能支持一下,就是我现在会选到很深的树节点,尴尬的是如果选的太深就会出现我不记得当前展开的是哪一级下面的子节点了.

希望能实时的将当前查看的子节点们的祖先节点都浮动在选择器上面,这样用户可以随时看到自己当前在选什么

希望得到答复

**Comment by afc163** [comment]
> 将当前查看的子节点们的祖先节点都浮动在选择器上面。

最好把你的诉求描述再清晰一点，例如操作步骤、交互稿或截图之类的。

> 希望得到答复

尽量减少这种对解决问题毫无帮助的语句。

**Comment by afc163** [comment]
没反馈就关了，有进一步详细的信息自行 reopen 吧。
