### ISSUE TITLE
Table 总结栏 表格触底时滚动条位置有误差

### ISSUE THREAD

**Issue by zhu-hongwei** [ant-design/ant-design#42185]
### Reproduction link

[https://4x.ant.design/components/table-cn/#components-table-demo-summary](https://4x.ant.design/components/table-cn/#components-table-demo-summary)

### Steps to reproduce

表格触底，滚动条显示还有一段距离

### What is expected?

表格触底，滚动条显示正常

### What is actually happening?

.

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | null |
| System | macos |
| Browser | 版本 112.0.5615.137（正式版本） (x86_64) |

**Comment by zhu-hongwei** [comment]
<img width="1440" alt="企业微信截图_4cbc9822-5f60-4447-a8d5-808d7e99083d" src="https://user-images.githubusercontent.com/61079864/236614215-a93366db-9818-4d79-a764-7bebef05ae68.png">

**Comment by afc163** [comment]
这疑似是 Mac Chrome 的一个渲染问题，滚动条意外多了个占位，但滚动区域是已经滚动完了的，你可以对比一下 https://codesandbox.io/s/an-niu-lei-xing-antd-4-24-10-forked-k4hcfm?file=/demo.tsx 这个例子在 Chrome/Safari/Firefox 下的效果。
