### ISSUE TITLE
scaffold market

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4219]
方便交流就先不用英文了。

1. 行业模板包是一个完整前端项目，开源部署在 GitHub 上。
2. 行业模板包有标准的文件目录、文档以及完善的元数据定义，包括英文名、中文名、描述、分类、截图等等。
2. 行业模板包有独立的静态展示站点，类似现在的 http://design.alipay.com/practice/payboss/summary 。
2. 行业模板包提供标准化的设计稿、交互稿、产品文档的展现方式。
3. 行业模板包是一个标准 dva-cli 的脚手架，将整合现有工具和开源框架，包括 dva + webpack + dora + antd + antd-mobile 这一套东西，在默认的 [dva 脚手架](https://github.com/dvajs/dva-cli/tree/master/boilerplates/app) 的基础上进行扩展开发。
4. 行业模板包将支持业务组件的开发、调试和展现，使用 [react-storybook](https://github.com/kadirahq/react-storybook) 这个非常适合项目内进行业务组件开发的工具。
5. 包含 mock 数据方案和初始数据，以及能够生成相关的 API 对接文档。
6. 包含完整的 UI 测试方案，能够快速简单的生成应用快照和测试脚本。
7. 包含代码质量检查的相关功能，`david-dm` `travis` `eslint` 等等，持续维护保证模板包的健康度。
8. 行业模板包统一发布到 `@antd-template/xxx` 的 npm 仓库中，可以被 dva-cli 读取和一键调用。也可以方便后续的客户端开发工具工具读取。
   ```bash
   $ dva init     // read scope @antd-template and list all
   $ dva init xxx // read and init from npmjs.com/package/@antd-template/xxx
   ```
9. 支持 PC 和 Mobile 模板。
10. 有独立的网站统一展现所有的模板包，类似 http://v4-alpha.getbootstrap.com/examples/ 。初步构想是：http://gallary.ant.design
11. 网站对行业模板包的标准进行定义，提供使用文档、接入文档和简单检索功能，鼓励社区进行贡献，尝试构建行业模板生态圈。

@benjycui @yesmeck 有没有想法把这个撸起来。

**Comment by afc163** [comment]
- [ ] 建立标准脚手架项目。
- [ ] 建议 gallery 网站。
- [ ] 改造 dva-cli 。

**Comment by afc163** [comment]
dva-cli 现在已经支持自定义脚手架功能了，看了下还有几点可以做：

1. 脚手架补充 README.md、设计文档、badge 和静态站点展示等：https://github.com/dvajs/dva-example-user-dashboard
2. 建立独立的站点，把所有 `https://github.com/dvajs/dva-example-xxxx` 的项目集中进行展现。

**Comment by sorrycc** [comment]
> dva-cli 现在已经支持自定义脚手架功能了 

改在哪了? 我咋没看到。

**Comment by afc163** [comment]
发现我理解错了，看你文档 https://github.com/sorrycc/blog/issues/18

```
dva new user-dashboard // 我理解成读取 https://github.com/dvajs/dva-example-user-dashboard 了
```

**Comment by benjycui** [comment]
@sorrycc 脚手架可以改成从线上下载模板么，本地的模板会有过时的问题。

**Comment by sorrycc** [comment]
可以，我也想这么改。

**Comment by ChrisFan** [comment]
@afc163 

1. 行业模板包不应该强制使用 dva 吧，考虑 H5 等情况，应用框架应该是自由的
2. 私有行业模板包是否要考虑，在内部，这样的用户应该不少
3. 作为一个 scaffold market，应该包含行业模板包以外的脚手架，行业模板包应该是其中一个分类
4. 是不是考虑直接把 scaffold market & antd plus(component market) 直接合二为一，变成 ui market，类似这样:

```
UI MARKET                      scaffolds  components  tools
------------------------------------------------------------

...

------------------------------------------------------------
```

tools 下放 cli、client 等使用这些脚手架和组件的工具

**Comment by afc163** [comment]
1. dva-cli 不是 dva 。
2. 应该有。
3. 脚手架和行业模板包是同一个东西。
4. 两者没关系。

**Comment by ChrisFan** [comment]
1. `在默认的 dva 脚手架 的基础上进行扩展开发。` 默认的 dva 脚手架不就是默认使用 dva 的么
2. --
3.  行业模板包是包含行业属性的，是必须遵循一定规范的，如果我只是想上传一个 dva-ssr 的脚手架，这个要不要纳入进来？
4. 一种场景，我查看一个行业模板包，发现下面几个业务组件不错，想参考或者使用，这个时候点击业务组件的链接，如果链到一个完全不同的系统会不会比较奇怪，索性就放在一个系统下面会更好？

**Comment by afc163** [comment]
1. dva-cli 只是初始化工具，本身和 dva 没有绑定。
2. --
3. 纳入，肯定有很多脚手架是泛行业属性或纯技术属性的。
4. 脚手架里如果有业务组件，不一定是会放到一个公共的地方存放的。

**Comment by ChrisFan** [comment]
前面三点我没意见，顺便提下脚手架的信息结构，我的理解大概是这样的：

a scaffold should contains:
- name
- author
- version
- stack: h5 pc nodejs
- framework: react/angular ...
- industry: ...
- *source: npm or tnpm or cdn?

**Comment by afc163** [comment]
- source: 应该是 git remote url.
- chineseName: 
- description:
- sceenshot ?

**Comment by afc163** [comment]
https://github.com/vuejs-templates

**Comment by afc163** [comment]
boilerplate

**Comment by afc163** [comment]
http://scaffold.ant.design/ published.
