### ISSUE TITLE
table 樹狀自動展開

### ISSUE THREAD

**Issue by jackypan1989** [ant-design/ant-design#4220]
想請問，目前 table 是否可以

1. 支援樹狀 table 自動展開 
(像 tree 一樣可以全開或是針對 key 開)

2. 在其他欄位底下縮排，不限第一個 column

官方文件目前沒有看到相關說明
萬分感謝

**Comment by afc163** [comment]
用 expandedRowKeys 进行控制。

**Comment by jackypan1989** [comment]
感謝，後來在 rc-table 找到相關設定
