### ISSUE TITLE
Customize Pagination style in antd

### ISSUE THREAD

**Issue by SYSUww** [ant-design/ant-design#42202]
### What problem does this feature solve?

I update antd from antd@4.19 to antd@5.x.x, and then the Pangination's style is changed.

 I want to use the  former Pagination  style. How can I do it ? In other word, if I want Customize Pangination's style，what should I do ?

### What does the proposed API look like?

Customize Pangination's style

**Comment by SYSUww** [comment]
![image](https://user-images.githubusercontent.com/52075786/236682482-a59c8c6a-490e-4b8d-8084-692eb324ec8c.png)
![image](https://user-images.githubusercontent.com/52075786/236682483-702bcd6d-6bad-433e-8f90-d77314c0169d.png)
I want to get antd@4.x.x's style in antd@5.x

**Comment by li-jia-nan** [comment]
This is expected, by design.

if you want the style of v4, you can customize the style.

**Comment by SYSUww** [comment]
> This is expected, by design.
> 
> if you want the style of v4, you can customize the style.

If I want to do so, where can I learn about it?
I have tried to solve it in two ways.
1. the  "itemRender" API of Pagination
2. Customize Theme in antd
they both doesn't work.
Can you tell me some correct methods?Thank you.

**Comment by li-jia-nan** [comment]
No need to Customize Theme or any api, directly use css to override the default style

**Comment by afc163** [comment]
See https://ant.design/docs/react/customize-theme
