### ISSUE TITLE
The notification's maxCount property is not working when set on config.

### ISSUE THREAD

**Issue by prakashmallow** [ant-design/ant-design#42207]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-4-6-forked-2xkei7)

### Steps to reproduce

The notification's maxCount property is not working to set on config.

### What is expected?

The notification's maxCount property is working fine when setting the notification's config. 

### What is actually happening?

The notification's maxCount property is not working when setting the notification's config. 

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18 |
| System | Mac |
| Browser | Chrome latest version |

**Comment by zombieJ** [comment]
Your issue title are not related with issue description. Could you help to modify one of them?

**Comment by prakashmallow** [comment]
> Your issue title are not related with issue description. Could you help to modify one of them?

Changed

**Comment by zombieJ** [comment]
`maxCount` is used by `notification.config`, not instance call:
https://codesandbox.io/s/basic-antd-5-4-6-forked-sl03hv

**Comment by prakashmallow** [comment]
> `maxCount` is used by `notification.config`, not instance call: https://codesandbox.io/s/basic-antd-5-4-6-forked-sl03hv

Thank you
