### ISSUE TITLE
[feature request] 给 table.components.header.cell 注入 column index

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#42208]
### What problem does this feature solve?

我在使用react-sortable-hoc来制作列拖拽排序功能, 需要一个列的唯一index, number类型
目前, restProps 接收到的参数里, 没有什么有效的数据, title也没有, 但是页面有title, 我都懵逼了, 我的title是怎么渲染出去的

### What does the proposed API look like?

```jsx
import { SortableContainer, SortableElement } from 'react-sortable-hoc'

const Th = SortableElement((props) => <th {...props} />)

const Cell = ({ className, style, ...restProps }) => {
  console.log('restProps', restProps) // react-sortable-hoc 要求: 得有一个index:number 类型的prop,  表示该列在tr中是属于第几个

  return <Th index={JSON.stringify(restProps.children)} {...restProps} />
}
 <Table
          components={{
            header: {
              row: DraggableContainer,
              cell: Cell,
            },
          }}

        />
```

**Comment by vaynevayne** [comment]
@afc163  好兄弟,有空吗, 帮忙看看这个问题呢, 比较着急

**Comment by afc163** [comment]
可以用这种方式来拿 index：https://codesandbox.io/s/ji-ben-yong-fa-antd-4-24-10-forked-thz8rm?file=/demo.tsx

**Comment by vaynevayne** [comment]
多谢

**Comment by SuAutumn** [comment]
> 可以用这种方式来拿 index：https://codesandbox.io/s/ji-ben-yong-fa-antd-4-24-10-forked-thz8rm?file=/demo.tsx

Can not open, ssl error.

**Comment by yoyo837** [comment]
> > 可以用这种方式来拿 index：https://codesandbox.io/s/ji-ben-yong-fa-antd-4-24-10-forked-thz8rm?file=/demo.tsx
> 
> Can not open, ssl error.

It works for me at this moment.

**Comment by SuAutumn** [comment]
> > > 可以用这种方式来拿 index：https://codesandbox.io/s/ji-ben-yong-fa-antd-4-24-10-forked-thz8rm?file=/demo.tsx
> > 
> > 
> > Can not open, ssl error.
> 
> It works for me at this moment.

Yes, I can open it on my phone, Maybe company network Error.
