### ISSUE TITLE
Popover 组件当content值为空时，弹出空白

### ISSUE THREAD

**Issue by hairgc** [ant-design/ant-design#42216]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-4-7-forked-ghnwme)

### Steps to reproduce

Popover title 跟 content属性均传空值

### What is expected?

不展示气泡卡片

### What is actually happening?

弹出空白卡片

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18 |
| System | Win10 |
| Browser | Chrome112 |

---
4.x与5.x均有次问题，请务必修复下4.x版本

**Comment by afc163** [comment]
这不一定是问题，我建议应用代码里自行做一下判断。

**Comment by zombieJ** [comment]
Popover 和 Tooltip 不一样，它倾向于重型交互，所以不会替开发者去做过滤。你可以 HOC 一下来实现这个效果。

**Comment by zombieJ** [comment]
例子：https://codesandbox.io/s/ji-ben-antd-5-4-7-forked-4pwnhx?file=/demo.tsx

**Comment by hairgc** [comment]
> Popover 和 Tooltip 不一样，它倾向于重型交互，所以不会替开发者去做过滤。你可以 HOC 一下来实现这个效果。

但之前的版本是做了过滤的，antd升级最新版本4.x后，项目中大量使用的地方都需要整改

**Comment by hairgc** [comment]
> 

这个问题时

> 这不一定是问题，我建议应用代码里自行做一下判断。

这个确实是个问题，是我这边升级了最新的antd版本才出现的，之前的版本是没有问题的，具体引发的原因是22年9月的这个提交引起的 08188f72ce6daf97dadd158d31960b96ef8fe50a

**Comment by zombieJ** [comment]
> > 这不一定是问题，我建议应用代码里自行做一下判断。
> 
> 这个确实是个问题，是我这边升级了最新的antd版本才出现的，之前的版本是没有问题的，具体引发的原因是22年9月的这个提交引起的 [08188f7](https://github.com/ant-design/ant-design/commit/08188f72ce6daf97dadd158d31960b96ef8fe50a)

👌
