### ISSUE TITLE
二维码组件设置背景颜色后下载的图片显示不对

### ISSUE THREAD

**Issue by bolosea** [ant-design/ant-design#42213]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xia-zai-er-wei-ma-antd-5-4-7-forked-tg2ggf?file=/demo.tsx)

### Steps to reproduce

直接点击下载

### What is expected?

下载下来的二维码图片颜色是红色的

### What is actually happening?

下载下来的二维码图片颜色是黑色的

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.0.0 |
| System | macos 13.2 (22D49) |
| Browser | chrome 112.0.5615.137 |

---
我已经解决了这个bug并且提交了个pr.

**Comment by kiner-tang** [comment]
@bolosea 如果已经提交了 pr ,可以在描述里面贴上 id
