### ISSUE TITLE
建议将CSS IN JS的库，从emotion改为linaria，以提高运行时的性能，感觉ant.design官网有明显的卡顿

### ISSUE THREAD

**Issue by houlang** [ant-design/ant-design#42222]
### What problem does this feature solve?

1、linaria比emotion优点在于，build后会将jsx中的css独立出来，不会和js融合到一起，可以减小js的大小提高运行时的性能
2、他们两的语法也差不多，
3、只是建议，希望ant.design越来越好，官网不卡

### What does the proposed API look like?

linaria地址：https://github.com/callstack/linaria

**Comment by yoyo837** [comment]
个人觉得antd官网不能做性能参考

**Comment by MadCcc** [comment]
antd 底层的 cssinjs 没有使用 emotion，只是官网在使用。
官网确实有不少优化空间。

**Comment by MadCcc** [comment]
antd 的 cssinjs 主要用于动态主题用途，虽然也支持 build-time 导出的能力，但是导出后会失去动态能力，所以底层不会采用 linaria 类似的方案。

**Comment by zombieJ** [comment]
> 个人觉得antd官网不能做性能参考

嗯，官网还有很多历史代码没有清理。以 antd 官网做参考不适合，的确需要翻一下。

**Comment by houlang** [comment]
> 

组件里，点击切换个组件，都要3秒5秒，甚至更长时间才有反应，这性能，感觉v5比v4差多了，当然，希望官网也考虑一下性能优化，虽然是免费给大家用的，哈哈

**Comment by houlang** [comment]
> > 个人觉得antd官网不能做性能参考
> 
> 嗯，官网还有很多历史代码没有清理。以 antd 官网做参考不适合，的确需要翻一下。

组件里，点击切换个组件，都要3秒5秒，甚至更长时间才有反应，这性能，感觉v5比v4差多了，当然，希望官网也考虑一下性能优化，虽然是免费给大家用的，哈哈

**Comment by arvinxx** [comment]
@houlang  来看看 https://procomponents.ant.design/  的性能感受如何

**Comment by zombieJ** [comment]
> 组件里，点击切换个组件，都要3秒5秒，甚至更长时间才有反应，这性能，感觉v5比v4差多了，当然，希望官网也考虑一下性能优化，虽然是免费给大家用的，哈哈

嗯，这是在尝试  Suspense 功能，但是效果并不好导致有额外渲染。其实也是在吃狗粮，想把这个功能完善好搞到 dumi 里去。

**Comment by houlang** [comment]
> @houlang 来看看 https://procomponents.ant.design/ 的性能感受如何

@arvinxx 这个速度还行，不过多少还是能感觉到点击左边切换组件的时候有略微的延迟(点击后选中的样式延迟)，，要是能点击就立刻响应变成选中状态就好了，中间内容显示骨架图或者显示Suspense的loading这样用户也能理解，毕竟单个页面里塞了很多组件呢

**Comment by houlang** [comment]
@zombieJ 没看到Suspense 的loading提示，，只看到了骨架图，，目前官网是点击切换后，，等到内容组件加载完以后，被点击的组件选项那里才会变成选中状态，问题在这里。

**Comment by zombieJ** [comment]
<img width="798" alt="截屏2023-05-11 10 41 44" src="https://github.com/ant-design/ant-design/assets/5378891/d2e4bde3-cec4-4b80-8ca2-d2bdd523ea27">

**Comment by arvinxx** [comment]
> 不过多少还是能感觉到点击左边切换组件的时候有略微的延迟(点击后选中的样式延迟)

@houlang  这个点感觉和 CSSinJS 可能没啥关系，激活态是切换路由时根据路由路径来判断的。可能是切换的时候路由跳转还没切？

**Comment by houlang** [comment]
> > 不过多少还是能感觉到点击左边切换组件的时候有略微的延迟(点击后选中的样式延迟)
> 
> @houlang 这个点感觉和 CSSinJS 可能没啥关系，激活态是切换路由时根据路由路径来判断的。可能是切换的时候路由跳转还没切？

这个问题应该和CSSinJS没太大关系，浏览器地址栏的地址路径是已经切了，但要等到路由将组件加载完以后，选中状态才会生效，这是是不合理的，如果可以解决这个延迟问题的话，个人觉得用户体验应该会更好。
