### ISSUE TITLE
Select Demo: Search and Select Users is broken

### ISSUE THREAD

**Issue by crazyjat** [ant-design/ant-design#42227]
### Reproduction link

[https://ant.design/components/select#components-select-demo-select-users](https://ant.design/components/select#components-select-demo-select-users)

### Steps to reproduce

Type anything to get list of things to appear. Notice list does not include anything that matches typed text. Try typing one of the names that does appear, for example aaron, that name will no longer appear in the results. The demo functionality makes no sense.

### What is expected?

Typed names to appear in the list or nothing to appear if typed name is not contained in the list.

### What is actually happening?

Bizarre and unexplainable results.

| Environment | Info |
| --- | --- |
| antd | All |
| React | n/a |
| System | n/a |
| Browser | n/a |

---
WTF?

**Comment by zombieJ** [comment]
If you check the Demo code you will find:

```tsx
return fetch('https://randomuser.me/api/?results=5')
```

This Demo shows the usage of:

> A complete multiple select sample with remote search, debounce fetch, ajax callback order flow, and loading state.

But we do not have real service to do 'filter'.
