### ISSUE TITLE
Select组件验证失败后无法再次选择

### ISSUE THREAD

**Issue by qazzhoubin** [ant-design/ant-design#4222]
#### 发生问题的环境是：

- antd 版本: 1.10.0
- 操作系统及其版本: win7
- 浏览器及其版本: chrome 52.0.2743.116 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

`<Select {...getFieldProps("demo",{
      initialValue:this.state.demo,
      rules:[{required:true,message:"请选择"}]
})}>...</Select>`

使用 this.props.form.validateFields(); 验证，验证不通过后，再次选择新值，无法选择。

#### 您期待的结果是:

即使验证不通过也可以选择新值。

#### 实际上的结果是:

验证不通过无法选择新值。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/WogBed?editors=001

未能重现，请提供 fork 并提供可重现演示后 reopen 此 issue。
