### ISSUE TITLE
displayRender behaves inconsistently in multiple vs single mode (it should not use Tag components as the render parent for each selected option)

### ISSUE THREAD

**Issue by georgeciobanu** [ant-design/ant-design#42228]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)]( https://codesandbox.io/s/custom-display-render-cascader-0ilkst?file=/demo.js)

### Steps to reproduce

@afc163  Cascader should **not** render a Tag component for each selected option in multiple mode (when a custom displayRender is provided by the user) because:

1. The developer provided a displayRender function which means they intend to draw custom UI for each option the user selected
2. It is inconsistent with the behavior of displayRender in single selection mode (where the component just displays whatever the function returns)
3. The current functionality is easily achieved by trivial displayRender code that can be provided as example to the developer:
`return (<Tag closable> {labels[ labels.length - 1 ]} </Tag>`
4. Developers who do not want the Tag component at all (or want to customize it) have no way to remove or customize it.

Context:
I would love to be able to have full control over what is rendered for each option in multiple mode as well. In other words, when a custom displayRender is provided as a parameter in "multiple" mode, I would prefer to have nothing (or a simple div) as the render parent for each selected option instead of a closable tag. This would actually be consistent with what happens in non-multiple mode, where we can render anything we want. Is it reasonable to say that this is a "bug" or at least an inconsistency in how "displayRender" works in single vs multiple mode?

To be clear, I understand the convenience of using closable Tag elements as the parent element (I'm sure it makes sense for a lot of users as the default behavior) and appreciate your work and attention to detail in doing so.

### What is expected?

Instead of a tag, render exactly what the user returns from displayRender (perhaps inside an empty div if needed)

### What is actually happening?

When providing a custom displayRender function, all of the UI components are enclosed inside a closable Tag component.

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | All |
| System | All |
| Browser | All |

---
If you do agree and fix this bug, there's a risk of breaking someone's product who relies on the tag elements and their closable button as returned today. What if we keep the default behavior as it is today and add an new argument to displayRender that defaults to false but the user can flip manually if they want the new behavior, for example:

`displayRender(labels, selectedOptions, noTagParent=false)
`

**Comment by georgeciobanu** [comment]
In case my English / explanation was not good, here it is explained differently:

Custom displayRender: When the user provides a custom displayRender function, it implies they want to handle the display of selected options in their own way, which might not necessarily involve using Tag components. Rendering Tag components by default in this scenario can interfere with the user's custom implementation and limit their control over the UI.

Consistency: The behavior of displayRender in single selection mode is different, as it simply displays the output returned by the displayRender function. To maintain consistency, the multiple selection mode should also adhere to the same principles, allowing users to have full control over the display of selected options.

Flexibility: By not rendering Tag components by default and allowing users to provide their custom displayRender code, it gives more flexibility to users in customizing the UI. As mentioned, the current functionality can be achieved with a simple example provided in the documentation, which would look like this:



```
function customDisplayRender(labels, selectedOptions) {
  return (
    <div>
      {labels.map((label, index) => (
        <Tag key={index} closable>
          {label}
        </Tag>
      ))}
    </div>
  );
}
```

By providing this example, users who want to use Tag components can implement the functionality themselves, while others who want a different UI can create their custom displayRender functions accordingly.

**Comment by zombieJ** [comment]
`displayRender` only affect inner content. You can use `tagRender` if need fully replace of it:
https://codesandbox.io/s/custom-display-render-cascader-forked-ij23o3?file=/demo.js

**Comment by georgeciobanu** [comment]
Thank you so much! Might it be useful to add tagRender to the Cascader API documentation? For some reason I don't see it.

**Comment by zombieJ** [comment]
Cascader is Select-like component so they share the API. But yes, pls feel free to PR to help enhance the doc : )

**Comment by georgeciobanu** [comment]
> 



> Cascader is Select-like component so they share the API. But yes, pls feel free to PR to help enhance the doc : )

PR sent https://github.com/ant-design/ant-design/pull/42262
