### ISSUE TITLE
notification destroy not working

### ISSUE THREAD

**Issue by haidv1992** [ant-design/ant-design#42234]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-scgxr4)

### Steps to reproduce

 notification.destroy() not working 

### What is expected?

i want notification.destroy() global before open new notification but not working

### What is actually happening?

 notification.destroy() not working

this my function helper
```

export const openNotification = ({
                                     des = 'Vui lòng thử lại thao tác hoặc liên hệ bộ phận kỹ thuật để được hỗ trợ',
                                     title = 'Thông báo !',
                                     duration = 4.5,
                                     type = 'error',
                                 }) => {

    notification.destroy()
         notification[type]({
            message: title || 'Thông báo !',
            description: des || 'Vui lòng thử lại thao tác hoặc liên hệ bộ phận kỹ thuật để được hỗ trợ',
            duration,
        });
};
```

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React |  "react": "^17.0.1", |
| System | macos |
| Browser | chorm |

**Comment by afc163** [comment]
I can't find any unexpected behavior in your codesandbox, did I miss something?

https://codesandbox.io/s/antd-reproduction-template-forked-8wol0h?file=/index.js

**Comment by BoyYangzai** [comment]
> I can't find any unexpected behavior in your codesandbox, did I miss something?

me too
https://codesandbox.io/s/antd-reproduction-template-forked-2nc81s

**Comment by zuoLingLing** [comment]
### **notification destroy not working;**

import { notification } from "antd";
const [api, contextHolder] = notification.useNotification();
useEffect(()=>{
    api.open({
      message:'111',
      duration:0,
      placement:"bottomLeft"
    });
    setTimeout(()=>{
      notification.destroy();
    },5000)
  },[]);
