### ISSUE TITLE
响应式样式问题 offset push 等问题

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#4223]
#### 发生问题的环境是：

- antd 版本:2.5.2
- 操作系统及其版本:macOS
- 浏览器及其版本:主流浏览器

#### 您做了什么？请提供尽可能详细的重现步骤。

```jsx
<Row>
  <Col md={24} lg={12}>
    <Col md={5} lg={6} className="ant-form-item-label">
      <label>标题</label>
    </Col>
    <Col md={{ span: 18, offset: 1 }} lg={{ span: 18 }}>
      <Input />
    </Col>
  </Col>
  <Col md={24} lg={12}>
    <Col md={5} lg={6} className="ant-form-item-label">
      <label>标题</label>
    </Col>
    <Col md={{ span: 18, offset: 1 }} lg={{ span: 18 }}>
      <Input />
    </Col>
  </Col>
</Row>
```

#### 您期待的结果是:

lg 的情况下是两列布局比较**紧凑** offset 不设置应该为 0
md 的情况下是一列布局比较**宽松** offset 设置为 1

#### 实际上的结果是:

lg 的情况下 offset 为 1 (受到了 md 的 offset 样式影响，使布局挤压变形换了行) 我希望是 0， 试了一下没有offset:0的样式
md 的情况下 offset 为 1 （正常）
(offset 换成 push 也是一样)

#### 可重现的在线演示

http://codepen.io/xutou12/pen/ENeJmp?editors=0010

**Comment by afc163** [comment]
@pinggod 来帮忙看看？

**Comment by pinggod** [comment]
@xutou12 @afc163 

问题定位结果：antd @media 样式只指定了最小生效宽度，比如 `@media (min-width: 768px)`。不指定最大生效宽度的特点在于，如果 lg 不完全覆盖 md 下的样式，则 md 下的样式会继续在 lg 下生效——这是一个褒贬不一的特点，所以之前不设置最大生效宽度的原因有哪些呢？

如果没有特别的原因，在这里可以通过同时设置最大、最小生效宽度解决此类问题，比如：`@media (min-width: 798px) and (max-width: 991px)`。

**Comment by xutou12** [comment]
@pinggod 
添加最大生效宽度可以解决这个问题
如果当初设计不设置最大生效宽度有原因的话，我觉得在 lg md sm 下添加一些默认样式向下覆盖，应该可以最小幅度解决这个问题吧，比如： ant-col-lg-offset-0, ant-col-lg-push-0 等等

**Comment by afc163** [comment]
Grid 是参考了 bootstrap 的推荐配置：http://getbootstrap.com/css/#grid-media-queries 没有选用下面 `occasionally` 的配置是因为当你没有其他分配率的需求时，你不需要总是把四个大小都写全。

```diff
- <Col xs={xx} sm={yy} md={yy} lg={yy} />
+ <Col xs={xx} sm={yy} />  // 后面两个可以省略
```

---

这个问题本质上还是像 @xutou12 所有，这里 
https://github.com/ant-design/ant-design/blob/666e80a1ba6e4cf168881d8dcfca7081600b97b5/components/grid/style/mixin.less#L53 没有生成 `**-offset-0` `**-push-0` 等样式，应该是一个 bug。补充了这些样式之后，就可以这么写：

```jsx
<Col md={{ span: 18, offset: 1 }} lg={{ span: 18, offset: 0 }}>
```

@pinggod 来个 PR 把 `-0` 补充上吧。

**Comment by pinggod** [comment]
PR: [https://github.com/ant-design/ant-design/pull/4281](https://github.com/ant-design/ant-design/pull/4281)
