### ISSUE TITLE
Dropdown组件内嵌套自定义组件，菜单无妨正常展开，需要包裹一层原生 html 元素

### ISSUE THREAD

**Issue by luichooy** [ant-design/ant-design#42232]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-bxxtwj?file=/index.js)

### Steps to reproduce

1. DropDown 内嵌自定义组件，子菜单无法正常展开
2. 如果给自定义组件包裹一层原生 html 元素。则 Dropdown 子菜单正常展开

### What is expected?

这是 bug 吗？还是无法规避的问题

### What is actually happening?

DropDown 内嵌自定义组件，子菜单无法正常展开

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2.0 |
| System | Win11 |
| Browser | Edge |

**Comment by luichooy** [comment]
```jsx
// This component is styled Component
const CircleBgIcon = ({ children }) => {
  // span with some styles ellipsis
  return <span className="CircleBgIcon">{children}</span>;
};

const App = () => {
  const items = [{ label: "Item", icon: <HomeOutlined /> }];
  return (
    <div className="App">
      <Space>
        {/* this is not working */}
        <Dropdown menu={{ items }}>
          <CircleBgIcon>
            <MoreOutlined />
          </CircleBgIcon>
        </Dropdown>

        {/* this is working ok */}
        <Dropdown menu={{ items }}>
          <div>
            <CircleBgIcon>
              <MoreOutlined />
            </CircleBgIcon>
          </div>
        </Dropdown>

        {/* this is working ok */}
        <Dropdown menu={{ items }}>
          <MoreOutlined />
        </Dropdown>

        {/* this is working ok */}
        <Dropdown menu={{ items }}>
          <span className="CircleBgIcon">
            <MoreOutlined />
          </span>
        </Dropdown>
      </Space>
    </div>
  );
};
```

第一个DropDown无法正常工作，其他均正常工作

**Comment by pengyw97** [comment]
第三个Dropdown好像也有问题，鼠标移上去没有hover

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15909

**Comment by luichooy** [comment]
> 第三个Dropdown好像也有问题，鼠标移上去没有hover
第三个就是内签了一个图标，没写 css 样式，自然没有 hover 样式

**Comment by luichooy** [comment]
> 第三个Dropdown好像也有问题，鼠标移上去没有hover

第三个就是内嵌了一个图标，没写 css 样式，自然没有 hover 样式
