### ISSUE TITLE
TreeSelect树选择 FAQ 中的 codesandbox 代码运行报错（https://codesandbox.io/s/wk080nn81k）

### ISSUE THREAD

**Issue by Elgar17** [ant-design/ant-design#42237]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk080nn81k)

### Steps to reproduce

https://codesandbox.io/s/wk080nn81k

### What is expected?

无

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 16.3.1 |
| System | mac OS 12.6 |
| Browser | Edge 版本 112.0.1722.34 |

---
升级到 ant5 后不需要引入样式， 删除报错行可解决

**Comment by afc163** [comment]
更新了：https://github.com/ant-design/ant-design/pull/42238
