### ISSUE TITLE
input-number组件升级到5.x之后range的样式被层叠掉了

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#42243]
### Reproduction link

[https://ant.design/components/input-number-cn#components-input-number-demo-out-of-range](https://ant.design/components/input-number-cn#components-input-number-demo-out-of-range)

### Steps to reproduce

打开官方demo的
对比4.x  https://4x.ant.design/components/input-number-cn/#components-input-number-demo-out-of-range

### What is expected?

受控的情况下 超出范围 有警告的样式

### What is actually happening?

样式被层叠掉了

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18 |
| System | mac |
| Browser | google |

**Comment by Lliuxs** [comment]
<img width="834" alt="2" src="https://github.com/ant-design/ant-design/assets/35122287/afbba680-8f91-4a25-9bb4-bcf385b20556">
<img width="1089" alt="1" src="https://github.com/ant-design/ant-design/assets/35122287/5934d2d0-7960-4de2-b13d-d916c3f72943">
5.x的类名是 .ant-input-number .ant-input-number-input {}
在4.x中是.ant-input-number-input
超出范围的类名为: .ant-input-number-out-of-range input

**Comment by pengyw97** [comment]
can i work for this?

**Comment by MadCcc** [comment]
@pengyw97 Sure.

**Comment by pengyw97** [comment]
Let me look at the problem, it might take some time
