### ISSUE TITLE
Form 表单能否手动触发字段校验

### ISSUE THREAD

**Issue by tt-ghost** [ant-design/ant-design#4225]
场景如下：
A为 Input 组件，B为 Checkbox 组件

期望：
B选中后，A的disabled=true，且不对A进行校验，去掉A的错误警告
B取消选中时，A的disabled=false，且对A进行校验

现状：
A是否校验只受自身change、blur等事件的触发

不知是否有什么方式可以手动触发A的校验？

**Comment by benjycui** [comment]
采用自定义校验即可，看这个 demo 里面对 password 的校验 https://ant.design/components/form-cn/#components-form-demo-register

清空 A 的错误信息请用 `setFields`

**Comment by tt-ghost** [comment]
多谢回复，现在有个问题，官方文档没有介绍`setFields` 的使用，我尝试了 [2115](https://github.com/ant-design/ant-design/issues/2115) 的方法，也没生效，不知道需要注意什么？
