### ISSUE TITLE
Form: onFieldChange called without "validated" flags

### ISSUE THREAD

**Issue by lscheibel** [ant-design/ant-design#42259]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-onfieldschange-called-without-errors-ngo0hp)

### Steps to reproduce

1. Open and clear terminal.
2. Enter "3" into input.

### What is expected?

As a developer I'd expect the onFieldsChange callback to fire once and with errors.

According to the docs the callback should fire 3 times but the last time with a "validated" flag set to true.

### What is actually happening?

OnFieldsChange is called twice, the first time without errors.

There is now way to differentiate between the first and second event.

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
The first time call should be `validating: true`, seems a bug of this.

**Comment by zombieJ** [comment]
This is fixed in v5 but v4 not upgrade with latest `rc-field-form`:
ref https://github.com/react-component/field-form/pull/580

**Comment by lscheibel** [comment]
Thank you!
