### ISSUE TITLE
hashPriority=hight开启后，组件的className设置失效这样设计合理吗？

### ISSUE THREAD

**Issue by chongqiangchen** [ant-design/ant-design#42254]
### Reproduction link

[https://stackblitz.com/edit/react-dcfr3t?file=demo.tsx](https://stackblitz.com/edit/react-dcfr3t?file=demo.tsx)

### Steps to reproduce

开启hashPriority=hight，button上使用classname设置一个自定义的样式

### What is expected?

期望能够正常生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18 |
| System | mac |
| Browser | 最新 |

---
我知道因为csshash存在造成权重拉高，但是组件本身的classname既然给出来使用，却无法让样式直接生效，这样是否合理，where的版本要求是88，是完全不考虑88以下的直接兼容？

有没有可能在classname设置的时候组件内部会使用上hashid做个组装？至少让组件本身的classname设置时候在开启hashPriority=hight还是生效的？

**Comment by MadCcc** [comment]
css 文件是用户自己写的，antd 无法控制其选择器权重。
提供一个思路：应用外层给一个 id，之后所有的覆盖样式都可以用优先级最高的 id 选择器覆盖：
```
#app {
  .test-button {
    color: red;
  }
}
```

**Comment by chongqiangchen** [comment]
> css 文件是用户自己写的，antd 无法控制其选择器权重。你举的例子是一个简单的 Button 组件，但是就算在 v4，一些复杂组件也会使用权重较高的选择器，用户无法简单覆盖。 提供一个思路：应用外层给一个 id，之后所有的覆盖样式都可以用优先级最高的 id 选择器覆盖： https://stackblitz.com/edit/react-dcfr3t-m2sewx?file=index.css
> 
> ```css-less
> #app {
>   .test-button {
>     color: red;
>   }
> }
> ```

虽然知道这样做，但是每个组件的css都得包裹一层，一是感觉麻烦，二是给后续维护的人需要通过制定规则来知道这个点，有没有什么更为推荐的方案？（暂时不考虑cssinjs的使用，因为V4到V5要变动的样式过大）

**Comment by MadCcc** [comment]
> 有没有什么更为推荐的方案？

可以使用 PostCSS 自动添加

**Comment by chongqiangchen** [comment]
> 感谢反馈，antd 的兼容版本为最近 2 个版本：
> 
> <img alt="截屏2023-05-10 15 21 12" width="609" src="https://user-images.githubusercontent.com/5378891/237309037-a43a3bb8-5e3e-4387-aa65-c769ed36fc59.png">
> 对于 88 版本，已经过于老旧。所以为了让这些版本还能使用才提供了兼容方式将 hash 提权。
> 
> 关于 `组件内部会使用上hashid做个组装` 我们于考虑过，但是最后没有去做，有以下几点：
> 
> 1. antd 底层使用 `rc-component` 加之样式实现设计系统，底层组件库设计上并不关注上层样式实现是否是 cssinjs。所以只会有顶层的 hash 做标注。
> 2. antd 的 cssinjs 不同于传统 cssinjs 方案，它是基于 Design Token 一次成型。因而无论样式如何实现，使用相同的 Design Token 会生成相同的 hash，所以本身对组件是没有标注性的。
> 
> 最重要的是这个实现方式对现在浏览器是没有升级成本的。

感谢告知

**Comment by chongqiangchen** [comment]
> > 有没有什么更为推荐的方案？
> 
> 可以使用 PostCSS 自动添加 id

好，我试试
