### ISSUE TITLE
Dropdown menu is some wired.

### ISSUE THREAD

**Issue by angdry** [ant-design/ant-design#42256]
### Reproduction link

Is private repo.

### Steps to reproduce

```
  const itemss = [
    {
      label: 'Add channel button',
      key: 0
    },
    {
      label: 'Weblink button',
      key: 1
    },
    {
      label: 'Applink button',
      key: 2
    }
  ]
```

```
  <Dropdown
    menu={{ itemss }}
    trigger={['click']}
  >
    <Button type='default'>Add buttons..</Button>
  </Dropdown>
```

### What is expected?

React.Children.only expected to receive a single React element child.

### What is actually happening?

I cant change items.
Try use couple of dropdown in one component.
but only use items.

If I changed items, some kind itemsssss, I have error React.Children.only...

| Environment | Info |
| --- | --- |
| antd | 5.4.1 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by angdry** [comment]
https://codesandbox.io/s/stoic-glade-32dbv9?file=/src/App.js

**Comment by zombieJ** [comment]
`items` is the API what you need use. `{{ items }}` is set object `{ items: items }`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/42256#issuecomment-1541601316
