### ISSUE TITLE
Popconfirm阻止content事件冒泡

### ISSUE THREAD

**Issue by bolosea** [ant-design/ant-design#42265]
### What problem does this feature solve?

阻止事件往上冒泡

### What does the proposed API look like?

contentStopPropagation = true

**Comment by bolosea** [comment]
如果是常规的Popover可以自己给content加个click事件阻止，但是这个组件内部content使用的是Overlay，没法自己加事件阻止事件冒泡了https://codesandbox.io/s/antd-reproduction-template-forked-9vex6u?file=/index.js

**Comment by zombieJ** [comment]
`contentStopPropagation` 这个 API 太裸了，但是允许给 Popconfirm 加额外的事件比如 `onXXXClick` 感觉挺不错的

**Comment by bolosea** [comment]
> `contentStopPropagation` 这个 API 太裸了，但是允许给 Popconfirm 加额外的事件比如 `onXXXClick` 感觉挺不错的

。。onContentClick的确更好一些，但是这个content的click事件好像除了拿来阻止冒泡也没有其他作用了？因为那个取消和确定有单独的事件

**Comment by zombieJ** [comment]
> 。。onContentClick的确更好一些，但是这个content的click事件好像除了拿来阻止冒泡也没有其他作用了？因为那个取消和确定有单独的事件

适用范围更广可以做更多事情，比如就是要处理 Popup 内容点击的场景就不用额外再添加一个 API 了。

**Comment by bolosea** [comment]
> > 。。onContentClick的确更好一些，但是这个content的click事件好像除了拿来阻止冒泡也没有其他作用了？因为那个取消和确定有单独的事件
> 
> 适用范围更广可以做更多事情，比如就是要处理 Popup 内容点击的场景就不用额外再添加一个 API 了。

ok 那可以功能可以加上吗?可以的话我准备提个pr了。。

**Comment by zombieJ** [comment]
`onPopupClick` @ant-design/ant-design-collaborators 意下如何？

**Comment by bolosea** [comment]
> 

ok，那就叫onPopupClick，另外后面那个@ant-design/ant-design-collaborators 是什么意思。。我在代码里没找个这个包诶

**Comment by yoyo837** [comment]
> > 
> 
> ok，那就叫onPopupClick，另外后面那个@ant-design/ant-design-collaborators 是什么意思。。我在代码里没找个这个包诶

批量at这个组织下的人

**Comment by CharlesLzo** [comment]
可以这样解决，曲径通幽：
`
                  <span
                    style='display: flex'
                    onClick={withModifiers(() => {}, ['stop'])}
                  >
                    <NPopconfirm
                      on-positive-click={this.handlePositiveClick}
                      on-negative-click={this.handleNegativeClick}
                    >
                      {{
                        default: () => <span>确认删除吗？</span>,
                        trigger: () => (
                          <NIcon size='16' color='#F98008'>
                            <img
                              src={this.deleteIcon}
                              style={'width:100%'}
                            ></img>
                          </NIcon>
                        )
                      }}
                    </NPopconfirm>
                  </span>
`
