### ISSUE TITLE
Input 设置 maxlength 在初始化设置 value 大于 maxlength 无法自动截断

### ISSUE THREAD

**Issue by loo41** [ant-design/ant-design#42268]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-greider-hhlvx2?file=/src/App.tsx)

### Steps to reproduce

打开重现链接即复现

### What is expected?

自动截断

### What is actually happening?

不会截断

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
这是预期行为，原生也是如此。晚点我写个文章说说为什么这么设计：
https://codesandbox.io/s/priceless-water-59cbog?file=/src/App.tsx

**Comment by loo41** [comment]
mark
