### ISSUE TITLE
button focus时border样式失效

### ISSUE THREAD

**Issue by haoli-0115** [ant-design/ant-design#42264]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ko1fkq?file=/index.js)

### Steps to reproduce

点击button后，移开鼠标，点击button的样式失效

### What is expected?

点击button，移开鼠标显示选中状态样式，border显示，文字color显示

### What is actually happening?

点击button，移开鼠标没有继续显示hover时的样式

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | react 18.2.0 |
| System | window 10 |
| Browser | 版本 108.0.5359.95（正式版本） （64 位） |

**Comment by MadCcc** [comment]
v5 的 focus 样式不再和 hover 样式相同，by design
