### ISSUE TITLE
请问本地可以运行多个项目？（多个npm start 多个端口）

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design#4227]
我司有一台服务，我在上面搭建了两个dva的项目，但是端口我不想都是8989.
请问修改哪里才可以做到，分别端口，并且能同时运行？

**Comment by infeng** [comment]
`dora --plugins \"proxy?port=8001&watchDirs=./mock,webpack,webpack-hmr\"`，具体可以去看[dora](https://github.com/dora-js/dora-plugin-proxy)
