### ISSUE TITLE
Array of numbers with select tags or multiple

### ISSUE THREAD

**Issue by lorraineS** [ant-design/ant-design#42271]
### What problem does this feature solve?

This component necessarily expects strings. It cannot be passed a number, which is extremely problematic in many cases.

As soon as we format our input to transform a string into a number, a warning "value` should be array when `mode` is `multiple` or `tags`" is displayed in the console but above all, adding tags to the table no longer works.

We should be able to pass anything to our array.

There is no way to turn the array into a number array. You can see the problem on this codesandbox :
https://codesandbox.io/s/antd-select-with-react-hook-form-qq6k5o

**Comment by zombieJ** [comment]
Could you provide codesandbox with Select `tag` mode and show the problem your described?

**Comment by lorraineS** [comment]
@zombieJ post updated with codesandbox!

**Comment by zombieJ** [comment]
Select tag mode accept string only since the internal native `input` element return string by value. But it's easy to HOC of this:
https://codesandbox.io/s/biao-qian-antd-5-4-5-forked-gjpfu6?file=/demo.tsx
