### ISSUE TITLE
Nextjs 13 and Antd Layout Issue

### ISSUE THREAD

**Issue by PuckxPuck** [ant-design/ant-design#42275]
### Reproduction link

[https://github.com/PuckxPuck/back.git](https://github.com/PuckxPuck/back.git)

### Steps to reproduce

Install the NPM packages, view the first page

### What is expected?

Render the page with all the css and html, and not break

### What is actually happening?

for a few seconds while refreshing, the antd Content part goes on top of the sider part, I debugged a little and i saw the ant-layout-has-sider class loads after a few seconds

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | react/nextjs 13 |
| System | 10.0.22621 Build 22621 |
| Browser | Opera GX browser |

---
At first the issue was the page loading before the antd style load, i fixed it by following this
https://github.com/ant-design/ant-design/issues/38555#issuecomment-1535788843
and after that this issue came

**Comment by seanroades** [comment]
+1

**Comment by annschultequindar** [comment]
+1

**Comment by rodsfreitas** [comment]
+1

maybe related to https://github.com/ant-design/ant-design/issues/42166

**Comment by kiner-tang** [comment]
@PuckxPuck You can tell the Layout component that Sider exists on the current page by explicitly specifying the 'hasSider' prop
![image](https://github.com/ant-design/ant-design/assets/10286961/13ff0861-7454-471c-ad78-0f1450838185)

**Comment by afc163** [comment]
@kiner-tang is right.
