### ISSUE TITLE
beforeUpload not working properly Dragger upload

### ISSUE THREAD

**Issue by Sunil61** [ant-design/ant-design#42279]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drag-and-drop-antd-4-24-10-forked-uu429m)

### Steps to reproduce

1. Upload a file to Upload Dragger
2. Check the behavior of file upload

### What is expected?

When I upload more than a 2MB file then it's not uploading in upload dragger.

### What is actually happening?

Currently, It's showing the error message and uploading the file.

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | ^16.8.6 |
| System | Windows 10 |
| Browser | Chrome |

---
Screenshot -  https://prnt.sc/JNeAIsjwkh7w

The before upload not working properly and I didn't receive any status in the onChange method.
I have added the code sandbox link for reference.

**Comment by afc163** [comment]
https://ant.design/components/upload#components-upload-demo-upload-png-only

**Comment by Sunil61** [comment]
@afc163 I got it. Sorry for the trouble and Thank you for your response. 👍
