### ISSUE TITLE
Haader light theme has darks margins

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#42274]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/header-content-footer-antd-5-4-7-forked-17uoij?file=/demo.tsx)

### Steps to reproduce

Just create a header light theme

### What is expected?

all area must be white

### What is actually happening?

margins are dark

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
See https://codesandbox.io/s/header-content-footer-antd-5-4-7-forked-m93lvf?file=/demo.tsx
