### ISSUE TITLE
Popconfirm 判断 inShadow 的方式情况未完全覆盖，导致重现 issues/41428

### ISSUE THREAD

**Issue by canGeEr** [ant-design/ant-design#42285]
### Reproduction link

主应用
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/elegant-wildflower-0w5n37?file=%2Fsrc%2Fmain.tsx%3A1%2C1)

子应用
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/popconfirm-bug-sub-app-2i1t4f-2i1t4f?file=%2Fsrc%2Fmain.tsx%3A1%2C1)

### Steps to reproduce

创建主应用，创建子应用，子应用使用antd 的Popconfirm

### What is expected?

Popconfirm内容点击不会闪烁并消失

### What is actually happening?

Popconfirm 闪烁并立马消失 和 issues/41428 表现一直

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.0.0 |
| System | macOS 13.3 (22E252) |
| Browser | google @latest |

---
// 在rc-component/trigger 中
const inShadow = targetRoot && targetRoot !== targetEle.ownerDocument;
对无界场景判断失效，无界的子应用的html元素被shadowDom包含

**Comment by zombieJ** [comment]
你的重现里没有 Popconfirm，看看是不是没有更新 Codesandbox 哈~

**Comment by zombieJ** [comment]
打了一下断点，元素的 `getRootNode` 和 `ownDocument` 都被劫持指向同一个 iframe 中的 `document` 导致无法判断出是否是在 shadow 中。这个组件侧没法做什么了，只能让无界来处理一下这个逻辑了。一种思路是 window.addEventListener 里也同样劫持掉，把 `target` 也代理成真实节点，把全部都模拟掉，不过具体还是需要向无界反馈哈~

**Comment by TobinXu** [comment]
@zombieJ 请问下 无界是啥？

**Comment by RyzenPan** [comment]
更新版本之后出现这个问题了
