### ISSUE TITLE
Form.List label pushes form items after the first down

### ISSUE THREAD

**Issue by tw-andri** [ant-design/ant-design#42287]
### Reproduction link

[https://ant.design/components/form#components-form-demo-dynamic-form-item](https://ant.design/components/form#components-form-demo-dynamic-form-item)

### Steps to reproduce

Add `labelWrap` to the form and make the label for the item longer.

### What is expected?

It would be perfect if the items all stay equal distance from each other.

### What is actually happening?

Because the label wraps to new line and its height becomes greater than the form item's, a big gap will be left between the first and the subsequent items.

<img width="480" alt="image" src="https://github.com/ant-design/ant-design/assets/113446798/4982d5eb-92c8-4df9-acb0-3cd645ea7733">

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | any |
| System | any |
| Browser | any |

**Comment by zombieJ** [comment]
This is only a demo. You can put ReactNode in `label` to customize this part. Follow code only handle the horizontal style. You need do the vertical responsive style self of it:

https://codesandbox.io/s/dynamic-form-item-antd-5-5-0-forked-mbnph8?file=/demo.tsx:230-232
