### ISSUE TITLE
Locale DatetimePicker

### ISSUE THREAD

**Issue by ga12ru12** [ant-design/ant-design#4228]
I set locale for DatetimePicker is **en_US** but only placeholder is english. All is still chinese. I liked **antd** but maybe chinese is default language. How can i set english is default language?

**Comment by gidich** [comment]
@ga12ru12 the following may help you out:

You'll want to use the [LocaleProvider](https://ant.design/components/locale-provider/) to get this working, the following is a simple approach to implementing this:

```javascript
import enUS from 'antd/lib/locale-provider/en_US';
import { LocaleProvider } from 'antd';

public render() {
  ...
  <LocaleProvider locale={enUS}><DatePicker /></LocaleProvider>
  ...
}
```

**Comment by Palisand** [comment]
How can I use this to wrap an entire app built using **dva**, rather than individual components? Is there another way to do this during initialization? Something like:
```javascript
// .../src/index.js

const app = dva({
  locale: {enUS}
  ...
});
```

**Comment by benjycui** [comment]
To work with dva:

```jsx
ReactDOM.render(
  <LocaleProvider>
    {app.start()}
  </LocaleProvider>,
  document.getElementById('root')
);
```
