### ISSUE TITLE
Table sticky模式 在父元素有height，padding,overflowY样式下，显示有问题

### ISSUE THREAD

**Issue by Ivan-hl** [ant-design/ant-design#42289]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-d2rbhd?file=/index.js)

### Steps to reproduce

1. html,body{height: 100%}

2. <div style={{ height: "100%", padding: 20, overflowY: "auto" }}>
      <Table
        dataSource={data}
        pagination={{ pageSize: 30 }}
        columns={columns}
        sticky
      />
    </div>

### What is expected?

滚动时，不应该出现table row溢出显示

### What is actually happening?

滚动时，出现table row溢出显示

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome 111 |

**Comment by Ivan-hl** [comment]
重现链接：https://codesandbox.io/s/antd-reproduction-template-forked-d2rbhd?file=/index.js:448-650

**Comment by afc163** [comment]
sticky 目前只支持 body 上滚动。

**Comment by afc163** [comment]
哦，可以用 offsetHeader 微调一下。

https://codesandbox.io/s/antd-reproduction-template-forked-qbx0xh?file=/index.js
