### ISSUE TITLE
Input 框输入表情时，最大字数和实际输入不一致

### ISSUE THREAD

**Issue by yuwanlin** [ant-design/ant-design#42297]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-zi-shu-ti-shi-antd-4-24-10-forked-gxr0zy)

### Steps to reproduce

1.input输入框限制字数20
2.使用微软拼音输入十个表情 🙂🙂🙂🙂🙂🙂🙂🙂🙂🙂
3.字数显示10/20，但是无法输入

### What is expected?

可以继续输入或者字数显示20/20

### What is actually happening?

字数显示10/20，但是无法输入

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 17 |
| System | win10 |
| Browser | edge 113 |

---
antd v4、v5都存在这个问题

**Comment by zombieJ** [comment]
这个对 emoji 的 length 有做过特殊处理，导致它和原生的计数是不一样的。看起来还是应该贴近原生才比较好。

https://codesandbox.io/s/dai-zi-shu-ti-shi-antd-4-24-10-forked-rb1u61?file=/demo.tsx

**Comment by yuwanlin** [comment]
如果计数不一样，那就应该可以继续输入。一样的话，就应该显示20/20。现在就是两种行为不一致，应该需要处理吧？

**Comment by zombieJ** [comment]
嗯，就是这个意思

**Comment by pengyw97** [comment]
我想跟进下这个🤓

**Comment by pengyw97** [comment]
看了下，应该是rc-input导致的
有个相同的issue：https://github.com/react-component/input/issues/18

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/37733#issuecomment-1274411261
