### ISSUE TITLE
`Spin`组件的tip在`5.4.7`中无效

### ISSUE THREAD

**Issue by YMNNs** [ant-design/ant-design#42291]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/spinde-tipzai-5-4-7zhong-wu-xiao-antd-5-4-7-forked-2pkqgd?file=/index.js)

### Steps to reproduce

使用组件`<Spin tip={"loading"} />`

### What is expected?

`Spin`组件下方出现`loading`

### What is actually happening?

`Spin`组件下方空白

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 113 |

**Comment by YMNNs** [comment]
出现此问题的原因是 #42162 中的修改
```diff
+    fontSize: 0,
```

**Comment by zombieJ** [comment]
的确是个 BUG，v4：
https://codesandbox.io/s/spinde-tipzai-5-4-7zhong-wu-xiao-antd-5-4-7-forked-rrtbv1?file=/demo.js

**Comment by zombieJ** [comment]
> 出现此问题的原因是 #42162 中的修改
> 
> ```diff
> +    fontSize: 0,
> ```

都找到原因了哈哈~直接来个 PR 吧~

**Comment by YMNNs** [comment]
我更新了codesandbox，如果`Spin`中间嵌套了其他东西，`fontSize: 0`就会被覆盖掉，这也是官网上的例子没有这个问题的原因
![image](https://github.com/ant-design/ant-design/assets/10176553/73f0e17a-4371-4943-b9ac-3b4234daa828)

**Comment by zombieJ** [comment]
哦，等等。`tip` 是包裹元素时才会生效，我加个 warning 好了。

**Comment by YMNNs** [comment]
我把文档看走眼了，bug当做feature用了很久

**Comment by zombieJ** [comment]
> 我把文档看走眼了，bug当做feature用了很久

😂 也算是 v5 帮忙纠正了。我加 warning 固化掉。谢谢
