### ISSUE TITLE
antd 4.x 表格里的可编辑行 如果当前cell是日期选择器的话 拿不到最新的值

### ISSUE THREAD

**Issue by CoderAWei** [ant-design/ant-design#42292]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-bian-ji-xing-antd-4-24-10-forked-iuw9zc?file=/demo.tsx)

### Steps to reproduce

- 点击``edit``
- 选择除默认日期之外的其他日期，点击``save``
- 发现编辑完之后的日期的值还是默认日期

### What is expected?

期望日期选择器的值能正常的回显

### What is actually happening?

始终是默认值

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.2.0 |
| System | win 10 |
| Browser | chrome 101.0.4951.67 |

---
业务需要在行内进行编辑字段，有日期选择的字段

**Comment by zombieJ** [comment]
保存的时候也要用编辑的数据：
https://codesandbox.io/s/ke-bian-ji-xing-antd-4-24-10-forked-rpy5v0?file=/demo.tsx
