### ISSUE TITLE
V4 modal点击事件冒泡导致popover关闭，modal套div加阻止冒泡无效，v5正常

### ISSUE THREAD

**Issue by XueMeijing** [ant-design/ant-design#42295]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-herschel-3vi7c3?file=/src/App.js)

### Steps to reproduce

1. 点击按钮出现popover
2. 点击popover content出现modal
3. 点击modal会关闭popover

### What is expected?

点击modal不会影响popover

### What is actually happening?
popover好像是通过Trigger组件绑定在window上，可能是因为点击modal冒泡的问题，但是加了stopPropagation无效

v4.22.0如视频，点击modal会关闭popover

https://github.com/ant-design/ant-design/assets/35559153/922330a0-37f6-4c28-8e9e-a9b63ee6b4dd

v5正常

https://github.com/ant-design/ant-design/assets/35559153/68e4f558-742b-4dbf-80ad-f63d26eb11b4

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 17 |
| System | chrome |
| Browser | 112.0.5615.49 |

**Comment by zombieJ** [comment]
v5 底层重构过成统一的 `@rc-component/portal`，这个在 v4 里应该是动不了了。可以做个锁检查：
https://codesandbox.io/s/loving-architecture-qczhoi?file=/src/App.js

**Comment by XueMeijing** [comment]
> v5 底层重构过成统一的 `@rc-component/portal`，这个在 v4 里应该是动不了了。可以做个锁检查： https://codesandbox.io/s/loving-architecture-qczhoi?file=/src/App.js

可以了，非常感谢！！
