### ISSUE TITLE
在5.4.7版本中选择中文后，点击其他文章会从中文跳英文

### ISSUE THREAD

**Issue by 1801256646** [ant-design/ant-design#42296]
### Reproduction link

[https://ant.design/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-ant-design-%E7%9A%84%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98](https://ant.design/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-ant-design-%E7%9A%84%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98)

### Steps to reproduce

https://ant.design/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-ant-design-%E7%9A%84%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98这个链接进入，切换成中文，点击定制主题，跳转英文

### What is expected?

期望跳转中文

### What is actually happening?

实际跳转英文

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 17.0.2 |
| System | mac |
| Browser | Google |

**Comment by li-jia-nan** [comment]
点定制主题确实有这个问题，来个 PR
