### ISSUE TITLE
InputNumber 长按增减按钮不会触发 onChange

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#4229]
官网可重现

http://localhost:8001/components/input-number/#components-input-number-demo-basic

**Comment by benjycui** [comment]
怎么我测这个没问题。。 https://ant.design/components/input-number/#components-input-number-demo-basic

这个 demo 是有最大值最小值限制的，到边界后不能 onChange 是正常的。

**Comment by ddcat1115** [comment]
是长按哦，点击没问题的

**Comment by benjycui** [comment]
好吧，懂你说的长按是哪个长按了。。
