### ISSUE TITLE
date-picker的指定placement无效

### ISSUE THREAD

**Issue by pmd5** [ant-design/ant-design#42301]
### Reproduction link

[https://ant.design/components/date-picker-cn#components-date-picker-demo-placement](https://ant.design/components/date-picker-cn#components-date-picker-demo-placement)

![image](https://github.com/ant-design/ant-design/assets/10841758/faebcae7-e009-4d30-b402-c94657409d40)

### Steps to reproduce

指定placement,滚动页面,会发现弹层自动移动位置

### What is expected?

指定placement,滚动页面,弹层不移动位置

### What is actually happening?

指定placement,滚动页面,会发现弹层自动移动位置

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome |

**Comment by kiner-tang** [comment]
当屏幕滚动导致某个方向不足以显示弹层时会自动调整位置，尽可能确保面板展示完整，这边有什么特殊需求不需要自动调整吗？或许可以看看要不要暴露个开关出来控制是否需要超出自动调整位置

**Comment by afc163** [comment]
```
popupAlign={{
  overflow: { adjustY: false },
}}
```

**Comment by moabbar** [comment]
@afc163 @kiner-tang is there a way to manually disable the automatic adjustment behavior?
