### ISSUE TITLE
Drawer z-index 

### ISSUE THREAD

**Issue by CHWYH** [ant-design/ant-design#42306]
### Reproduction link

[https://ant-design.antgroup.com/components/drawer-cn](https://ant-design.antgroup.com/components/drawer-cn)

### Steps to reproduce

目前 Drawer   z-index 默认设置了1000,能解释下为啥要设置1000吗？另外type申明中，z-index设置成了number，为啥不能是string，假如用户有需要设置成‘auto’（node_modules\rc-drawer\lib\DrawerPopup.d.ts：DrawerPopupProps），怎么搞？

### What is expected?

z-index 不要默认 1000 或者类型支持string，方便用户改成‘auto’

### What is actually happening?

z-index 设置1000 ，影响其他样式， 类型设定number，又无法更改

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18 |
| System | win |
| Browser | chrome |

**Comment by MadCcc** [comment]
`auto` 具体是什么场景？如果你需要修改 Drawer 的 `z-index`，大概率是有一个层级关系的，这个数字也比较方便指明。
