### ISSUE TITLE
关于message静态方法调用时降级无效问题

### ISSUE THREAD

**Issue by chongqiangchen** [ant-design/ant-design#42302]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/s53b1i)

### Steps to reproduce

在request 拦截器统一的报错提醒

### What is expected?

message能够取消where的使用

### What is actually happening?

仍然使用

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | react |
| System | mac |
| Browser | 86 |

---
我清楚知道使用useApp的方案，但是原有业务的request请求情况下，在拦截器那层统一处理message相关，但是因为降级无效以至于低版本的浏览器无法正确显示message，这个有什么建议或者处理方案吗

**Comment by RedJue** [comment]
我在项目里遇到过类似情况，也是静态方法降级失败，你可以通过 `@ant-design/static-style-extract` 这个包统一导出降级的 `css` ，判断低版本浏览器的时候引入

**Comment by chongqiangchen** [comment]
> 我在项目里遇到过类似情况，也是静态方法降级失败，你可以通过 `@ant-design/static-style-extract` 这个包统一导出降级的 `css` ，判断低版本浏览器的时候引入

咦，官网有类似的这个包使用的文档不

**Comment by chongqiangchen** [comment]
> > 我在项目里遇到过类似情况，也是静态方法降级失败，你可以通过 `@ant-design/static-style-extract` 这个包统一导出降级的 `css` ，判断低版本浏览器的时候引入
> 
> 咦，官网有类似的这个包使用的文档不

哦哦，看到了相关介绍，那是不是可以仅导出message这些相关的样式即可，你当时想到这个方案是为了利用这个方法做低版本兼容还是仅仅针对message这种降级无效？

**Comment by RedJue** [comment]
> > > 我在项目里遇到过类似情况，也是静态方法降级失败，你可以通过 `@ant-design/static-style-extract` 这个包统一导出降级的 `css` ，判断低版本浏览器的时候引入
> > 
> > 
> > 咦，官网有类似的这个包使用的文档不
> 
> 哦哦，看到了相关介绍，那是不是可以仅导出message这些相关的样式即可，你当时想到这个方案是为了利用这个方法做低版本兼容还是仅仅针对message这种降级无效？

官方的降级方案，我这里静态方法降级失败，可能跟我用了 `vite` 有关系，打包出来拿不到上下文，所以没法注入进去对应的静态方法，退而求其次用了原始的 `css` 引入。

**Comment by chongqiangchen** [comment]
咦，那提到这个我想问下：
https://codesandbox.io/s/antd-reproduction-template-forked-mx6117

为什么我这样写好像没用，官方提供的useApp调用message产出的样式还是有where

**Comment by chongqiangchen** [comment]
> 咦，那提到这个我想问下： https://codesandbox.io/s/antd-reproduction-template-forked-mx6117
> 
> 为什么我这样写好像没用，官方提供的useApp调用message产出的样式还是有where

这个却又是有效果的
https://codesandbox.io/s/antd-reproduction-template-forked-5o4pjx?file=/index.js

**Comment by RedJue** [comment]
> > 咦，那提到这个我想问下： https://codesandbox.io/s/antd-reproduction-template-forked-mx6117
> > 为什么我这样写好像没用，官方提供的useApp调用message产出的样式还是有where
> 
> 这个却又是有效果的 https://codesandbox.io/s/antd-reproduction-template-forked-5o4pjx?file=/index.js

`@ant-design/cssinjs` 版本得和 `antd` 里的保持一致，不然会导致消费的 `context` 不一样，获取不到配置

**Comment by chongqiangchen** [comment]
> > > 咦，那提到这个我想问下： https://codesandbox.io/s/antd-reproduction-template-forked-mx6117
> > > 为什么我这样写好像没用，官方提供的useApp调用message产出的样式还是有where
> > 
> > 
> > 这个却又是有效果的 https://codesandbox.io/s/antd-reproduction-template-forked-5o4pjx?file=/index.js
> 
> `@ant-design/cssinjs` 版本得和 `antd` 里的保持一致，不然会导致消费的 `context` 不一样，获取不到配置

好的，然后message静态方法这个我直接采用在app下event做个监听调用useApp message完成，就不需要把样式抽出处理了

**Comment by Ivan-hl** [comment]
@chongqiangchen 没太懂你最终怎么处理的， 我这也是需要在axios拦截器中进行message提示， 调用的是useApp的静态方法，但依旧无法消费styleprovider的降级

**Comment by chongqiangchen** [comment]
> @chongqiangchen 没太懂你最终怎么处理的， 我这也是需要在axios拦截器中进行message提示， 调用的是useApp的静态方法，但依旧无法消费styleprovider的降级

app.tsx层加了一个event.on('message', callback)接收事件，在axios写了一个message.success等函数，映射的是event.emit('message', args);

**Comment by GKLL** [comment]
> > @chongqiangchen 没太懂你最终怎么处理的， 我这也是需要在axios拦截器中进行message提示， 调用的是useApp的静态方法，但依旧无法消费styleprovider的降级
> 
> app.tsx层加了一个event.on('message', callback)接收事件，在axios写了一个message.success等函数，核心是event.emit('message', args);

在app.tsx层加了一个event.on('message', callback)接收事件里面有示例吗？ @chongqiangchen

**Comment by GKLL** [comment]
> EventEmitter

好哒，谢谢

**Comment by GKLL** [comment]
谢谢啦

**Comment by shawn-play** [comment]
> > > [@chongqiangchen](https://github.com/chongqiangchen) 没太懂你最终怎么处理的， 我这也是需要在axios拦截器中进行message提示， 调用的是useApp的静态方法，但依旧无法消费styleprovider的降级
> > 
> > 
> > app.tsx层加了一个event.on('message', callback)接收事件，在axios写了一个message.success等函数，核心是event.emit('message', args);
> 
> 在app.tsx层加了一个event.on('message', callback)接收事件里面有示例吗？ [@chongqiangchen](https://github.com/chongqiangchen)

在任何地方触发事件:
> window.dispatchEvent(new CustomEvent('popMsg', { detail: data.errMsg }));
在app入口或者目标页面监听:
> useEffect(() => {
    const errMsgEvent = (e) => {
      message.error(e.detail || 'Something Wrong!');
    };
    window.addEventListener('popMsg', errMsgEvent);
    return () => {
      window.removeEventListener('popMsg', errMsgEvent);
    };
  }, []);
