### ISSUE TITLE
希望 Menu 的 items 能更好地支持 title 属性

### ISSUE THREAD

**Issue by yshenhua** [ant-design/ant-design#42308]
### What problem does this feature solve?

目前只有 MenuItemType 支持 title属性，API 说明是设置收缩时展示的悬浮标题，但实际上它还会在 [role=“menuitem”] 元素上添加 title，这在展开时是符合预期的，可以用这个 title 查看超过菜单宽度而显示不全的内容；但在收缩时是不需要的，因为已经有对应的 tooltip 了，建议： 
1. SubMenuType 支持 title 属性用来设置对应 [role=“menuitem”] 元素上的 title；
2. 菜单收缩时移除 [role=“menuitem”] 元素上的 title 属性。

### What does the proposed API look like?

```
<Menu
  items={[
    {
      label: '这个submenutitle内容比较长内容比较长内容比较长',
      title: '这个submenutitle内容比较长内容比较长内容比较长',
      icon: <CalendarOutlined />,
      key: '1',
      children: …,
      …
    }
  ]}
  …
```

**Comment by afc163** [comment]
既然数据中给了 title，Menu 很难判断是否要在某些内部状态下是否需要加到 element 上。我建议配合上提 collapsed 状态，来决定是否要给 menu item 加上 title：https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-5-4-7-forked-vkcs4m?file=/demo.tsx
