### ISSUE TITLE
Model内使用List报错需要key 

### ISSUE THREAD

**Issue by ericzhao007** [ant-design/ant-design#42305]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6bwd6p?file=/index.js)

### Steps to reproduce

对话框内使用List

### What is expected?

无报错

### What is actually happening?

Warning: Each child in a list should have a unique "key" prop.

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2 |
| System | windows |
| Browser | Edge |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-42ktz2

你给 `footer` 赋予的是数组，React 里节点为数组时就需要给数组里的每个元素都加上 `key` 哈。
