### ISSUE TITLE
DataPicker选择日期后会自动关闭面板，能不能自己来控制点击后不关闭面板

### ISSUE THREAD

**Issue by SweeperDuan** [ant-design/ant-design#42319]
### What problem does this feature solve?

基于DataPicker来自行封装日期多选，类似于Select的multi模式

### What does the proposed API look like?

可以自行控制选择日期后是否关闭面板，默认关闭即可

**Comment by afc163** [comment]
使用 open 和 onOpenChange 受控模式即可自行控制开关状态。

**Comment by SweeperDuan** [comment]
> 使用 open 和 onOpenChange 受控模式即可自行控制开关状态。

理论上是这样，但实际上不行啊，我就用的受控模式，但是还是会自动关闭（我并没有把open设为false）

**Comment by yoyo837** [comment]
提供复现, 开新issue
