### ISSUE TITLE
Add draggable attribute to Tree Node.

### ISSUE THREAD

**Issue by dgtllion** [ant-design/ant-design#42310]
### What problem does this feature solve?

I want to eliminate the drag function of some Tree nodes and i want to specify which nodes are not draggable.

### What does the proposed API look like?
```
const treeNodes = [{
title: 'Node 1',
key: 'node1',
...
draggable: false
}, {
title: 'Node 2',
key: 'node2',
...
draggable: true
}];


<Tree treeData={treeNodes} draggable />```

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by zombieJ** [comment]
Already support. Pls check doc for more detail:
<img width="858" alt="截屏2023-05-12 15 49 07" src="https://github.com/ant-design/ant-design/assets/5378891/8de782a4-ab0c-410f-8f7d-afcc83cdba1e">

ref https://ant-design.antgroup.com/components/tree#tree-props
