### ISSUE TITLE
antd的form的shouldUpdate执行了validator没有执行

### ISSUE THREAD

**Issue by nkli** [ant-design/ant-design#42320]
### Reproduction link

[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce

a和b的校验都相互依赖，这里用shouldUpdate去做，结果shouldUpdate执行了，对应的validator没有执行。这种应该怎么处理？
<Form.Item
noStyle
shouldUpdate={(pre: any, current: any) => {
const result = JSON.stringify(pre.a) !== JSON.stringify(current.a)
|| JSON.stringify(pre.b) !== JSON.stringify(current.b);
console.log('shouldUpdate', result);
return result;
}}
>
{
() => (
<Form.Item name="a" label="a方式" required rules={[
({ getFieldValue }) => ({
validator(_, value) {
// 依赖b
console.log('validate);
},
})]}>
<Radio.Group disabled={disabled}>
<Radio value={'ddd'}>ddd
<Radio value={'xxx'}>xxx
</Radio.Group>
</Form.Item>
)
}
</Form.Item>

### What is expected?

shouldUpdate执行后能够执行validator

### What is actually happening?

没有执行

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | react |
| System | 无 |
| Browser | chrome90 |

**Comment by nkli** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-5w67rv?file=/index.js

Implementation steps: Enter 1 at the beginning and 4 at the end
Expected result: Start Digit check needs to be removed

**Comment by linxianxi** [comment]
执行校验要用 dependencies https://ant.design/components/form-cn#dependencies

**Comment by nkli** [comment]
dependencies与shouldUpdate同时使用会警告报错，但我的场景必须使用shouldUpdate，那shouldUpdate能否支持rule的validator更新呢

**Comment by linxianxi** [comment]
dependencies 同时有更新和校验的功能啊。https://codesandbox.io/s/antd-reproduction-template-forked-gthq1b?file=/index.js

**Comment by nkli** [comment]
您说的没错，大部分场景dependencies就能够解决更新的问题，但是表单的依赖处理有时候不仅仅是更新和校验，还涉及表单的显隐，shouldUpdate处理起来比dependencies更方便，看看shouldUpdate能否支持检验的更新。
如若不行，也麻烦说明一下具体不能实现的原因，感谢。

**Comment by linxianxi** [comment]
dependencies 也能处理显隐啊，上问题的沙盒链接吧

**Comment by nkli** [comment]
dependencies 也能处理显隐啊，上问题的沙盒链接吧
=====================
这种如何处理呢，有示例么
