### ISSUE TITLE
非浮层的级联面板

### ISSUE THREAD

**Issue by wangshaoyi9738** [ant-design/ant-design#42325]
### What problem does this feature solve?

系统类型：客服系统
具体场景：在与客户沟通完毕进行电话内容记录时，使用级联选择器展示所有问题分类及子一级分类，现有方案只能点击触发并浮层展示，希望可以非浮层显示并固定放置在页面中，占据页面的一部分，在选择到最后一级分类后，在下方实现后续步骤。

### What does the proposed API look like?

1. 自定义级联选择的触发方式，增加一种非浮层的展示方式。
2. 自定义面板的CSS层级，增加Z-index属性，使用数值自定义。
3. 参照：https://arco.design/vue/component/cascader和https://element-plus.org/zh-CN/component/cascader.html

**Comment by BoyYangzai** [comment]
看起来是个很简单的 feature 工作(使用 `cascader` 的 `OptList` )，我自己做了一版 但是感觉问题太多了 没有pr 😭

**Comment by wangshaoyi9738** [comment]
之前有人提过Issues，看起来好像并不会考虑增加这一功能，目前只有Vue生态提供相关功能，所以现在因为一个组件，可能要去使用Vue了
