### ISSUE TITLE
[select] 开启OptGroup ，并自定义fieldNames时，分组label不显示

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#42328]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fen-zu-antd-5-4-7-forked-qup60h?file=/demo.tsx:687-697)

### Steps to reproduce

1.
```ts
[
      {
        label: "Manager",
        options: [
          { name: "Jack", data: "jack" },
          { name: "Lucy", data: "lucy" }
        ]
      },
      {
        label: "Engineer",
        options: [{ name: "yiminghe", data: "Yiminghe" }]
      }
    ]
```
2. 
```
 fieldNames={{ value: "data", label: "name" }}
```

### What is expected?

正常显示

### What is actually happening?

分组label没有正常显示

![image](https://github.com/ant-design/ant-design/assets/81673017/828992a2-1688-46d0-80db-fdef5b69b7e8)

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React |  "react": "^18.0.0", |
| System | win11 |
| Browser | Chrome  108.0.5359.125 |

**Comment by RSS1102** [comment]
最近几天没有空余时间，我尽快抽出时间看下，能否PR（在别人认领之前）。🙆‍♀️🙆‍♀️

**Comment by afc163** [comment]
当然~

**Comment by BoyYangzai** [comment]
@RSS1102 @afc163
 hello 我看了下源码发现这里的问题在于 
源码中 OptGroup 最后使用的一直是 `label` 字段 而 `label` 来自于 `data['label']`
但是当你设置了 `fieldNames` 之后 这里就变成了 `label = data['name']`   此时这里为空
所以只需要把你的例子中的 `label` 改成 `name` 就可以正常运行了 我认为这是符合预期的
https://codesandbox.io/s/fen-zu-antd-5-4-7-forked-knxnby?file=/demo.tsx
![image](https://github.com/ant-design/ant-design/assets/94534613/57b81e69-de09-4e34-a3db-af9836dacc82)

**Comment by RSS1102** [comment]
> @RSS1102 @afc163 你好 我看了下源码发现这里的问题在于 源码中 OptGroup 最后使用的一直是`label`一段 并且`label`来自于`data['label']` 但是当你设置了`fieldNames`之后 这里就变成了`label = data['name']` 这个时候这里为空 所以只需要把你的例子中的`label`改成`name`就可以正常运行了我认为这是符合预期的 https://codesandbox.io/s/fen-zu-antd-5-4-7-forked-knxnby?file=/demo.tsx ![图像](https://user-images.githubusercontent.com/94534613/238148223-57b81e69-de09-4e34-a3db-af9836dacc82.png)

但是我认为`options`中的数据不应该被组件所固定（我当前业务上就这样避开这个问题的）。
（有可能原始数据仍为`  options: [{ name: "yiminghe", data: "Yiminghe" }]`），则需要对源数据进行操作处理，我认为这是不对的。

---
我认为：
1. 应该保持数据的简洁，不应该操作源数据。
2. 当同一个数据源面对多个`<Select/>`时，需要绑定的`label`可能不同。
还是需要对组件进行fix。

**Comment by RSS1102** [comment]
> > @RSS1102 @afc163 你好 我看了下源码发现这里的问题在于 源码中 OptGroup 最后使用的一直是`label`一段 并且`label`来自于`data['label']` 但是当你设置了`fieldNames`之后 这里就变成了`label = data['name']` 这个时候这里为空 所以只需要把你的例子中的`label`改成`name`就可以正常运行了我认为这是符合预期的 https://codesandbox.io/s/fen-zu-antd-5-4-7-forked-knxnby?file=/demo.tsx ![图像](https://user-images.githubusercontent.com/94534613/238148223-57b81e69-de09-4e34-a3db-af9836dacc82.png)
> 
> 但是我认为`options`中的数据不应该被组件所固定（我当前业务上就这样避开这个问题的，出现了大量的操作数据的代码）。 （有可能原始数据仍为` options: [{ name: "yiminghe", data: "Yiminghe" }]`），则需要对源数据进行操作处理，我认为这是不对的。
> 
> 我认为：
> 
> 1. 应该保持数据的简洁，不应该操作源数据。
> 2. 当同一个数据源面对多个`<Select/>`时，需要绑定的`label`可能不同。
>    还是需要对组件进行fix。

**Comment by BoyYangzai** [comment]
@RSS1102 Hello 我的理解是这里无需对原数据做过多的改动
参考 https://codesandbox.io/s/fen-zu-antd-5-4-7-forked-knxnby?file=/demo.tsx
原数据仍然是自定义 name 和 data 字段 
只不过 OptGroup 的 label 字段 也相应的变成了 name 字段 这并没有过多操作源数据 只需要一个简单的function就能搞定 如下
![image](https://github.com/ant-design/ant-design/assets/94534613/f4057378-7dbd-4f51-a83e-026c53d1f570)

因为暂时不太清楚原作者的用意 -- 原先这个 filedNames 的 `自定义节点字段` 是否包含了 `OptGroup`中的 `label`
所以目前有两种解法：
1.包含 则添加FAQ
![image](https://github.com/ant-design/ant-design/assets/94534613/ad11dbcb-16f3-44c6-9f10-f94cfd1f91cb)
2.不包含 更改源码 只需添加一行代码即可
![image](https://github.com/ant-design/ant-design/assets/94534613/6c65263b-9795-45ac-bd50-ea9fac273bee)
![image](https://github.com/ant-design/ant-design/assets/94534613/ed72cfb5-6dea-476c-ba2f-0444dbe90d03)

**Comment by RSS1102** [comment]
> 2.不包含 更改源码 只需添加一行代码即可

我认为从数据的定义结构来说:
无分组数据结构
```ts
[
  {
     { name: "Jack", data: "jack" },
     { name: "Lucy", data: "lucy" }
 },
]
```
分组数据结构
```ts
  {
        label: "Manager",
        options: [
          { name: "Jack", data: "jack" },
          { name: "Lucy", data: "lucy" }
        ]
      },
```
其中`label`唯一的意义就是定义分组的名称，如果使用别名`label`就失去了他数据存在的意义。

---

所以我认为 `filedNames `修改`label`时（`  fieldNames={{ label: "name" }}`）就不应该影响分组名称。
（我个人理解是是这样的）

**Comment by BoyYangzai** [comment]
@RSS1102 收到 这个我们周一等大佬上班之后再讨论一下 感谢反馈💗
@afc163 @zombieJ @MadCcc

**Comment by RSS1102** [comment]
> 目前

😳ok，那你来PR吧。

**Comment by zombieJ** [comment]
`fieldNames` 要控制自然是一起控制的，否则 optGrp 的 `label` 其实就没字段可以控制了。

**Comment by RSS1102** [comment]
> fieldNames

我个人想法：
1.{
labe:xxx
option:[]
}
`label`就已经被定义了，分组的时候就已经给这个分组定义了别名了

2. 对于`fieldNames `API进行扩展，比如增加`optionGroupName`进行单独控制

---
如果用`fieldNames `同时控制`Select`组件的`label`展示，和`Option-label`是不是不太合适，本来就是不同的两个名字，控制之后变成相同了

**Comment by zombieJ** [comment]
没太明白，optGrp 的展示标题是 `label`，optItem 的展示标题也是 `label`。`fieldNames` 做映射也是 `label`。两个不同的名字指的是什么哈？

**Comment by RSS1102** [comment]
> 没有太明白，optGrp 的显示标题是`label`，optItem 的显示标题也是`label`。`fieldNames`做投影也是`label`。两个不相同的名称搜索的是什么哈？

`Options`数据格式
```ts
[
      {
        label: "Manager",
        options: [
          { name: "Jack", data: "jack" },
          { name: "Lucy", data: "lucy" }
        ]
      },
      {
        label: "Engineer",
        options: [{ name: "yiminghe", data: "Yiminghe" }]
      }
    ]
```
需求：
1. ：`Select`组件需要选中第一个分组第一个项（即` { name: "Jack", data: "jack" }`）时，展示的是**Jack**，获得的结果是**jack**
则使用` fieldNames={{ label:"name"value: "data" }}`进行映射显示。
2. 分组的标题保持不变。

----

当前Question是：
如果我使用了` fieldNames={{ label:"name"value: "data" }}`操作了label，分组label就会改变（当前是不显示）。但是我实际不想让他改变。(或者说我想让分组label单独控制）

**Comment by zombieJ** [comment]
OK，这么看起来是数据源给的数据分组信息和数据信息的 label field 是不一致的对吧

**Comment by RSS1102** [comment]
> OK，这么看起来是数据源给的数据分组信息和数据信息的 label field 是不一致的对吧

应该是这样理解的。

---
目的/需求：
1. 使用`fieldNames`操作`label:"name"`时，不会影响到每个Option的label（即每个分组的label）。

**Comment by zombieJ** [comment]
> 目的/需求：
> 
> 1. 使用`fieldNames`操作`label:"name"`时，不会影响到每个Option的label（即每个分组的label）。

这个是 breaking change，把业务需求带到组件里去了，不适合。倒是 `groupLabel` 可以考虑一下，这样也可以有 `groupOption`做对齐。

**Comment by RSS1102** [comment]
> > 目的/需求：
> > 
> > 1. 使用`fieldNames`操作`label:"name"`时，不会影响到每个选项的标签（即每个分组的标签）。
> 
> 这个是breaking change，把业务需要带到组里去了，不合适。倒是`groupLabel`可以考虑一下。

同意后者。整体的需求。
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fen-zu-antd-5-4-7-forked-qup60h?file=/demo.tsx:687-697)
在这种情况下出现了分组`label`的问题，是我使用方法不对吗？
如果不是的话 我认为要么是扩展API（使用`groupLabel`），要么是减少API的影响，避免掉。

**Comment by zombieJ** [comment]
如果是新的 `groupLabel` 它的逻辑应该是，先看有没有 `groupLabel`，没有的话使用 `label`，最后使用默认的 `.label`

**Comment by RSS1102** [comment]
> 如果是新的 `groupLabel` 它的逻辑应该是，先看有没有 `groupLabel`，没有的话使用 `label`，最后使用默认的 `.label`

对的，我也是这样想的，要我todo嘛？
@BoyYangzai 你要对这个API进行pr吗？

**Comment by BoyYangzai** [comment]
> > 如果是新的 `groupLabel` 它的逻辑应该是，先看有没有 `groupLabel`，没有的话使用 `label`，最后使用默认的 `.label`
> 
> 对的，我也是这样想的，要我todo嘛？ @BoyYangzai 你要对这个API进行pr吗？

👌 我来吧 这部分源码 已经看过一遍了
