### ISSUE TITLE
官网例子BUG

### ISSUE THREAD

**Issue by zhump** [ant-design/ant-design#4233]
官网这个例子
https://ant.design/components/tree-cn/#components-tree-demo-search

第一步：点击 0-1 节点,该节点展开
第二步：点击 0-1-1 节点 ,该节点展开
第三步：点击 0-1 节点,该节点无反应
正常场景是 0-1节点收起，但是官网这个例子没有收起，好奇怪。

**Comment by xieyihao** [comment]
careful
