### ISSUE TITLE
Wrong scroll position in Select drop down list in rtl (right to left)  

### ISSUE THREAD

**Issue by omidabd** [ant-design/ant-design#42331]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-276e0p?file=/index.js)

### Steps to reproduce

1. click the Select to open the dropdown list
2. scroll its list by mouse wheel

### What is expected?

When page layout is Rtl, it is expected to see the vertical scroll bar in left side

### What is actually happening?

scroll bar is on the right side.

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18 |
| System | Windows 10 |
| Browser | Version 113.0.5672.93 (Official Build) (64-bit) |

---
this happens only in virtual scroll mode

**Comment by GeneralChauhan** [comment]
Is this still open??

**Comment by BoyYangzai** [comment]
@GeneralChauhan Please wait a moment. I have fixed this and will submit pr immediately

**Comment by GeneralChauhan** [comment]
ohh alright!
