### ISSUE TITLE
ColorPicker review issues

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42333]
<img width="388" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/cf31e4c9-99a2-45ed-9efc-7da3b27d874d">

- [x] 弹出动画方向有点不对，上面这个是从中间弹开的，应该从箭头方向弹开。可以参考 Popover。

---

发现 https://preview-42329-ant-design.surge.sh/components/popover-cn 也丢了，不是 ColorPicker 的问题，是其他地方改挂了。

**Comment by afc163** [comment]
<img width="261" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/e867053e-f6ec-4781-82c5-90a6c219982e">

- [ ] 操作点 hover 时没有出现鼠标手型。

**Comment by afc163** [comment]
<img width="142" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/822de0c4-253b-4c2a-b785-aff842685c21">

- [ ] https://preview-42329-ant-design.surge.sh/components/color-picker-cn#components-color-picker-demo-format 这个例子里切换无效。

**Comment by afc163** [comment]
<img width="242" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/f461449d-6a2e-40e1-b638-1c6a0c89168e">

- [ ] 描述里少 `。`

**Comment by afc163** [comment]
```
import type { Color } from 'antd/es/color-picker';
```

- [ ] 建议都用 es 目录。

**Comment by afc163** [comment]
<img width="205" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/d5a98623-6de3-4958-bea4-c462c77026cb">

- [ ] 这个图案是重复的，感觉 16X16 + repeat 就够了，不需要这么大。

**Comment by afc163** [comment]
- [ ] 可以把这里用到的这个 react-color 换掉：https://ant.design/docs/spec/colors-cn

**Comment by li-jia-nan** [comment]
> * [ ]  操作点 hover 时没有出现鼠标手型。

done~

**Comment by li-jia-nan** [comment]
> * [x]  描述里少 `。`
> * [x]  可以在这里提醒用户是 5.*.0 版本后新增的组件。类似 https://preview-42329-ant-design.surge.sh/components/float-button-cn

done~

**Comment by li-jia-nan** [comment]
> ```
> import type { Color } from 'antd/es/color-picker';
> ```
> 
> * [x]  建议都用 es 目录。

done~

**Comment by li-jia-nan** [comment]
> 发现 https://preview-42329-ant-design.surge.sh/components/popover-cn 也丢了，不是 ColorPicker 的问题，是其他地方改挂了。

这个需要 @zombieJ 豆酱大佬看看

**Comment by li-jia-nan** [comment]
> * [ ]  这个图案是重复的，感觉 16X16 + repeat 就够了，不需要这么大。

这个需要 @MadCcc @RedJue 提供一个 16x16 的素材

**Comment by li-jia-nan** [comment]
> * [ ]  https://preview-42329-ant-design.surge.sh/components/color-picker-cn#components-color-picker-demo-format 这个例子里切换无效。

这个我的理解是预期行为，因为这里本来默认非受控模式，但是 demo 中指定了 `format`，那么就变成了受控模式，所以切换就不起作用了吧

不知道我理解对不对，需要 @MadCcc @RedJue 两位大佬看看

**Comment by RedJue** [comment]
> > * [ ]  https://preview-42329-ant-design.surge.sh/components/color-picker-cn#components-color-picker-demo-format 这个例子里切换无效。
> 
> 
> 
> 这个我的理解是预期行为，因为这里本来默认非受控模式，但是 demo 中指定了 `format`，那么就变成了受控模式，所以切换就不起作用了吧
> 
> 
> 
> 不知道我理解对不对，需要 @MadCcc @RedJue 两位大佬看看

是这样的，这里变成受控了，所以没法切换 **format**

**Comment by RedJue** [comment]
> > * [ ]  这个图案是重复的，感觉 16X16 + repeat 就够了，不需要这么大。
> 
> 
> 
> 这个需要 @RedJue 大佬看看，是不是需要 @MadCcc 闲夕大佬提供一个 16x16 的素材

需要的，要重新弄个16*16的

**Comment by afc163** [comment]
> 这个我的理解是预期行为，因为这里本来默认非受控模式，但是 demo 中指定了 format，那么就变成了受控模式，所以切换就不起作用了吧

demo 里不要出现让用户费解的交互，这里 format + onChange 配合吧。

**Comment by li-jia-nan** [comment]
> > > * [ ]   这个图案是重复的，感觉 16X16 + repeat 就够了，不需要这么大。
> > 
> > 
> > 这个需要 @RedJue 大佬看看，是不是需要 @MadCcc 闲夕大佬提供一个 16x16 的素材
> 
> 需要的，要重新弄个16*16的

那这个等闲夕大佬周一上班了提供一个素材吧

**Comment by li-jia-nan** [comment]
> > 这个我的理解是预期行为，因为这里本来默认非受控模式，但是 demo 中指定了 format，那么就变成了受控模式，所以切换就不起作用了吧
> 
> demo 里不要出现让用户费解的交互，这里 format + onChange 配合吧。

这样的话是不是 demo 中只需要一个就够了，不用出现三次了，@RedJue 大佬要不你来看一下？

**Comment by RedJue** [comment]
> > 这个我的理解是预期行为，因为这里本来默认非受控模式，但是 demo 中指定了 format，那么就变成了受控模式，所以切换就不起作用了吧
> 
> 
> 
> demo 里不要出现让用户费解的交互，这里 format + onChange 配合吧。

嗯嗯 可以加个 onFormatChange 配合一下

**Comment by RedJue** [comment]
> > > 这个我的理解是预期行为，因为这里本来默认非受控模式，但是 demo 中指定了 format，那么就变成了受控模式，所以切换就不起作用了吧
> 
> > 
> 
> > demo 里不要出现让用户费解的交互，这里 format + onChange 配合吧。
> 
> 
> 
> 这样的话是不是 demo 中只需要一个就够了，不用出现三次了，@RedJue 大佬要不你来看一下？

写3个只是为了显示更清楚，比较直观展现 format 的效果，还是必要的，就把受控优化一下好了，demo 还是减少用户理解的成本，简单处理。

**Comment by jinboren** [comment]
+1

**Comment by linxianxi** [comment]
应该支持下 #fff 这种就三个英文的色号

**Comment by RedJue** [comment]
> 应该支持下 #fff 这种就三个英文的色号

后续版本可以考虑支持
