### ISSUE TITLE
希望能导出 TextAreaProps 等 Input 组件中的类型声明

### ISSUE THREAD

**Issue by luichooy** [ant-design/ant-design#42335]
### What problem does this feature solve?

当在 tsx中使用 Input.TextArea组件时，目前需要开发者声明相关 props 值的类型并传递给 TextArea 组件，如
```tsx
import React, { FC, KeyboardEventHandler,ChangeEventHandler } from 'react'
interface WrappedTextAreaPropsType {
	value: string
	onChange: ChangeEventHandler<HTMLTextAreaElement>
	onPressEnter: KeyboardEventHandler<HTMLTextAreaElement>
}
```
希望导出TextAreaProps帮助开发者快速声明相关 props 的类型

### What does the proposed API look like?

导出：
```tsx
export type { 
    InputProps, 
    InputRef , 
    TextAreaProps , 
    SearchProps, 
    PasswordProps, 
    GroupProps
} from './input';
```
导入及使用:
```tsx
import type {TextAreaProps ,SearchProps,PasswordProps,GroupProps} from 'antd'

interface WrappedTextAreaPropsType {
	value: string
	onChange: TextAreaProps['onChange']
	onPressEnter: TextAreaProps['onPressEnter']
}
```

**Comment by BoyYangzai** [comment]
@luichooy 或许可以直接 `import type {TextAreaProps} from 'antd/lib/input'` 拿到你需要的 type
若是像umi一样 export all的话 Type 名称会不会重复这样子 
可能 `import type {TextAreaProps} from 'antd/lib/input'` 这样可以根据需求自己去导出

**Comment by RedJue** [comment]
> @luichooy 或许可以直接 `import type {TextAreaProps} from 'antd/lib/input'` 拿到你需要的 type
> 
> 若是像umi一样 export all的话 Type 名称会不会重复这样子 
> 
> 可能 `import type {TextAreaProps} from 'antd/lib/input'` 这样可以根据需求自己去导出

+1，直接拿需要的就行了

**Comment by li-jia-nan** [comment]
> @luichooy 或许可以直接 `import type {TextAreaProps} from 'antd/lib/input'` 拿到你需要的 type 若是像umi一样 export all的话 Type 名称会不会重复这样子 可能 `import type {TextAreaProps} from 'antd/lib/input'` 这样可以根据需求自己去导出

建议用 es 目录

**Comment by li-jia-nan** [comment]
issue 先 close 了，如果还有问题可以留言我重新打开

**Comment by luichooy** [comment]
> @luichooy 或许可以直接 `import type {TextAreaProps} from 'antd/lib/input'` 拿到你需要的 type 若是像umi一样 export all的话 Type 名称会不会重复这样子 可能 `import type {TextAreaProps} from 'antd/lib/input'` 这样可以根据需求自己去导出

嗯嗯  目前是按需去具体文件夹下导入的。但是一开始并不清楚相应的文件夹下有这个类型，一直在 import 语句中输入 textArea关键字利用编辑器的提示尝试寻找库导出的类型。困惑了好一会儿。后来找到了。是否可以在文档中补充上类型示例以作提示
@li-jia-nan
