### ISSUE TITLE
Typography Editable onEnd not being called onBlur

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#42345]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interactive-antd-5-4-7-forked-56tp8r)

### Steps to reproduce

- Pass `onStart`, `onEnd` and `onCancel` to `editable` config of `Typography`
- `onStart` is called when clicking on element
- `onCancel` is called when canceling with ESC
- `onEnd` is called when confirming with ENTER
- when confirming and leaving editing is done by clicking outside of element (onBlur), no callback is being called. This action is identical to pressing ENTER and therefor should also trigger `onEnd` callback

### What is expected?

Call `onEnd` when leaving editing with onBlur 

### What is actually happening?

It is impossible to act on onBlur

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | all |
| System | all |
| Browser | all |

**Comment by georgiossalon** [comment]
@Kamahl19 I am with you on this one. Or at least add the possibility of passing an onBlur function.

**Comment by lhz87127855** [comment]
In this context, onChange can be treated as onBlur. Since onEnd triggers onChange, we only need to handle the onBlur logic within onChange
