### ISSUE TITLE
AntD Form errors not update with i18next in React

### ISSUE THREAD

**Issue by jacob-duong** [ant-design/ant-design#42347]
### Reproduction link

[https://miro.medium.com/v2/resize:fit:1302/1*mFDAF6yPKY8z9Aqhb7fGmw.gif](https://miro.medium.com/v2/resize:fit:1302/1*mFDAF6yPKY8z9Aqhb7fGmw.gif)

### Steps to reproduce

https://medium.com/@emrerdem/update-antd-form-errors-with-i18next-in-react-61ae5b8efbfb

### What is expected?

The form error needs to be rerendered based on locate changed

### What is actually happening?

The form error does not change when I switch languages, it's keeping the first initial language 

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18.2.0 |
| System | MacOS 13.3.1 (22E261) |
| Browser | Google Chrome Version 92.0.4515.131 |

**Comment by zombieJ** [comment]
Form trigger validate by the `validateTrigger` config. Which means it will not updated by the locale modification. I think we can add config to re-validate touched field.
