### ISSUE TITLE
resolve failed:  { [Error: Cannot find module 'rc-util'] code: 'MODULE_NOT_FOUND' } rc-util node_modules/nan

### ISSUE THREAD

**Issue by febobo** [ant-design/ant-design#4235]
I'm use antd(v2.5.2) in react-reudx-starter-kit.
but throw error, see Image.
I try install rc-util and caniuse-db resolve it, but not resolve
![image](https://cloud.githubusercontent.com/assets/9276376/21167364/fa8b7226-c1e6-11e6-9f07-3e10639bdd6b.png)

**Comment by yulanggong** [comment]
https://github.com/babel/babel/commit/16c84fb35393157dc94d238b669140d08e8802c6
