### ISSUE TITLE
Antd5 run in the qiankun with shadow dom, css not appear? 

### ISSUE THREAD

**Issue by AsuraLuo** [ant-design/ant-design#42358]
### Reproduction link

[https://github.com/AsuraLuo/Turbo-React-Vite-Qiankun](https://github.com/AsuraLuo/Turbo-React-Vite-Qiankun)

### Steps to reproduce

本地pnpm dev, 会启动乾坤，3000端口主应用，都是antd5版本

### What is expected?

css in js的话，隔离到子应用，不会污染到主应用

### What is actually happening?

目前子应用的style都会自动追到到主应用，乾坤配置开启了shadow dom

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.2.0 |
| System | mac os 14.0.0 |
| Browser | google |

**Comment by vaynevayne** [comment]
css in js 原来还有这个妙用

**Comment by AsuraLuo** [comment]
```javascript
 await start({
    singular: true,
    sandbox: {
      strictStyleIsolation: true,
      experimentalStyleIsolation: true
    }
  })
```

**Comment by kuitos** [comment]
strictStyleIsolation 不建议使用了，新版本准备废弃了

**Comment by AsuraLuo** [comment]
> strictStyleIsolation 不建议使用了，新版本准备废弃了
是在乾坤3.0版本里面吗。目前2.新版本有什么办法能解决这个问题吗
