### ISSUE TITLE
Image组件展示Base64编码的图片报红,但是可以正常运行

### ISSUE THREAD

**Issue by zhangyuanlin666** [ant-design/ant-design#42353]
### Reproduction link

[http://localhost:8000/](http://localhost:8000/)

### Steps to reproduce

 <Image
                  preview={false}
                  height={40}
                  width={105}
                  src={vercodeState.imageBase64Data}   //这个地方报 红
                  onClick={() => {console.log("图片被点击了!")}}
                />

### What is expected?

Image组件显示Base64编码的图片

### What is actually happening?

实际src={vercodeState.imageBase64Data}   //这个地方报 红   提示(JSX attribute) ImageProps.src?: string | undefined

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | "react": "^17.0.0", |
| System | win10 |
| Browser | 谷歌 |

**Comment by BoyYangzai** [comment]
@zhangyuanlin666 哈喽 你提供的链接是本地链接哦 不能观看 
还有根据你的描述来看 应该是传入src的数据类型不太对 方便的话提供一下codesandbox复现链接

**Comment by zhangyuanlin666** [comment]
> @zhangyuanlin666 哈喽 你提供的链接是本地链接哦 不能观看 还有根据你的描述来看 应该是传入src的数据类型不太对 方便的话提供一下codesandbox复现链接

对,链接是我随便写的, 页面是正常显示了, 就是vscode中报红

**Comment by zhangyuanlin666** [comment]
已经搞定,  类属性中string 写成了String

**Comment by zhangyuanlin666** [comment]
已经搞定, 类属性中string 写成了String
