### ISSUE TITLE
Dropdown 组件的 DropDownProps interface onVisibleChange 有误（官网文档也有误）

### ISSUE THREAD

**Issue by hjin-me** [ant-design/ant-design#4236]
#### 发生问题的环境是：

- antd 版本: 2.5.2
- 操作系统及其版本: TS 2.1.4， Mac OS X
- 浏览器及其版本: Chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

对比以下三处文档，发现 `rc-dropdown` 是 `onVisibleChange(visible: boolean)`
但是 官网和 interface 里面写的是 `onVisibleChange({visible:boolean})`

rc-dropdown 的 onVisibleChange 
https://github.com/react-component/dropdown/blob/master/src/Dropdown.jsx#L84

官网文档描述：
https://ant.design/components/dropdown-cn/#API

DropDownProps interface:
https://github.com/ant-design/ant-design/blob/master/components/dropdown/dropdown.tsx#L9

**Comment by yesmeck** [comment]
欢迎 PR。
