### ISSUE TITLE
@rc-component/portal Not found

### ISSUE THREAD

**Issue by helianthuswhite** [ant-design/ant-design#42371]
### Reproduction link

[https://registry.npmjs.org/@rc-component/portal/-/portal-1.1.0.tgz](https://registry.npmjs.org/@rc-component/portal/-/portal-1.1.0.tgz)

### Steps to reproduce

Antd v5 project install error 404, `@rc-component/portal` package can not be found, Direct links to open https://registry.npmjs.org/@rc-component/portal/-/portal-1.1.0.tgz found will Not found error. Searching for the `@rc-component/portal` package on npm also results in a Service Unavailable.

### What is expected?

Install the package success.

### What is actually happening?

I can't install antd in my project.

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by yoyo837** [comment]
<img width="996" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/8c14ba63-2267-41c3-8d49-0d495a908cc7">

**Comment by helianthuswhite** [comment]
Now it's ok, if there is a reason for this weird problem?
It seems I'm not the only one with this problem. https://github.com/react-component/portal/issues/13

**Comment by afc163** [comment]
<img width="832" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/3e15815e-1617-4c1d-a905-3aa8033056e1">
