### ISSUE TITLE
Rendering <Menu /> component twice causes: Can't perform a React state update

### ISSUE THREAD

**Issue by mehmetkarakamis** [ant-design/ant-design#42378]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-playground-forked-1fxmqk?file=/src/index.js)

### Steps to reproduce

Click one of the items in Menu component.

### What is expected?

No error.

### What is actually happening?

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 16.8.6 |
| System | Ubuntu |
| Browser | Chrome |

---
I need use my CustomMenu component in 2 different components but when I navigate between these 2 components or from another component, React gives error. The reason I want to use <CustomMenu /> inside 2 different components is that I don't want to include <CustomMenu /> for my other components.

**Comment by zombieJ** [comment]
For latest React version. It's not consider a issue by official any more:

> ### Notable Changes
> No warning about setState on unmounted components: Previously, React warned about memory leaks when you call setState on an unmounted component. This warning was added for subscriptions, but people primarily run into it in scenarios where setting state is fine, and workarounds make the code worse. We've https://github.com/facebook/react/pull/22114 this warning.

https://github.com/ant-design/ant-design/issues/41572#issuecomment-1491449544
