### ISSUE TITLE
在 shadow 元素中使用 antd 

### ISSUE THREAD

**Issue by AsuraLuo** [ant-design/ant-design#42375]
### Reproduction link

[https://github.com/AsuraLuo/Turbo-React-Vite-Qiankun](https://github.com/AsuraLuo/Turbo-React-Vite-Qiankun)

### Steps to reproduce

我需要在 shadow dom 中使用我的应用程序，我不想影响 root 的 css。当我尝试这样做时，antd 将 css 附加到 root 的 head 标签，它破坏了视图。我试图删除js中的css导入并通过cdn在shadow中导入它，出现了不同的问题。在这种情况下，modals 和 dropdowns 附加到 body，所以我必须在 js 中导入 css。

我只需要一个附加选项，我可以在其中选择解决此问题。我不想将它附加到 root 的身体。我需要它在阴影中。

### What is expected?

或者能否提供一个方法，我想动态的css in js添加到document.body的最后

### What is actually happening?

我需要在 shadow dom 中使用我的应用程序，我不想影响 root 的 css。当我尝试这样做时，antd 将 css 附加到 root 的 head 标签，它破坏了视图。我试图删除js中的css导入并通过cdn在shadow中导入它，出现了不同的问题。在这种情况下，modals 和 dropdowns 附加到 body，所以我必须在 js 中导入 css。

我只需要一个附加选项，我可以在其中选择解决此问题。我不想将它附加到 root 的身体。我需要它在阴影中。

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | mac os 14.0.0 |
| Browser | google |

**Comment by afc163** [comment]
这是英文机翻的中文？有一点点难理解

**Comment by AsuraLuo** [comment]
@afc163 我需要把动态的css，指定可以传递一个container，而不是添加到document.head，有什么办法吗？

**Comment by AsuraLuo** [comment]
@afc163 @MadCcc 

```javascript
import createCache from '@emotion/cache'
import type { EmotionCache, Options } from '@emotion/cache'

export const createAppCache = (devModule: boolean) => {
  const cacheOptions: Options = {
    key: 'css',
    prepend: false,
    speedy: false,
    stylisPlugins: []
  }

  if (devModule) {
    const qiankunShadowDom: any = document.querySelector('div[data-name="react-app"]')?.shadowRoot
    const targetContainer: Node = qiankunShadowDom.querySelector('qiankun-head')
    cacheOptions.container = targetContainer
  }

  const cache: EmotionCache = createCache(cacheOptions)

  return cache
}

```

**Comment by AsuraLuo** [comment]
@afc163 类似于emotion的可以提供插入的container，传入一个dom元素，不需要一味的添加到document.head

**Comment by afc163** [comment]
https://github.com/ant-design/cssinjs#styleprovider 这里有个 `container` 属性，不知道是否是你需要的 API？

**Comment by AsuraLuo** [comment]
类似于antd支持px to rem
https://github.com/ant-design/ant-design/discussions/40789

**Comment by AsuraLuo** [comment]
@afc163 感谢大佬，我忘了还有这个npm，thanks, 我准备解决qiankun集成antd5的案例。
