### ISSUE TITLE
InputNumber不兼容data-*

### ISSUE THREAD

**Issue by xieyihao** [ant-design/ant-design#4238]
#### 发生问题的环境是：

- antd 版本:2.5.2
- 操作系统及其版本:win 10
- 浏览器及其版本:chrome 版本 55.0.2883.87 m

#### 您做了什么？请提供尽可能详细的重现步骤。

在InputNumber上设置data-*属性，希望是在onBlur等事件中拿到。
结果不能像React的input一样实现

#### 可重现的在线演示
[codepen](http://codepen.io/xieyihao/pen/XNxqWa?editors=1011)

**Comment by yesmeck** [comment]
不建议用 data-* 来传数据。

```javascript
 <InputNumber
  context={{id: 100}}
  onBlur={(e) => this.handlerBlur(e, 100)}
 />
```

**Comment by xieyihao** [comment]
@yesmeck  InputNumber也不能从e.target中拿到context

**Comment by yesmeck** [comment]
不要这样来传数据。
