### ISSUE TITLE
nextjs with antd5.x  style not work on production!   

### ISSUE THREAD

**Issue by RobinYang11** [ant-design/ant-design#42384]
### Reproduction link

[http://121.43.189.236:3000/material_manager](http://121.43.189.236:3000/material_manager)

### Steps to reproduce

访问页面

### What is expected?

样式正常

### What is actually happening?

没有样式

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18 |
| System | windows |
| Browser | chrome  |

**Comment by RobinYang11** [comment]
@kiner-tang  did you tried  on production?

**Comment by RobinYang11** [comment]
@kiner-tang   or you just want load B by forking this project  https://github.com/ant-design/create-next-app-antd ?

**Comment by zombieJ** [comment]
Could you help to provide a github repo about this? Seems your web antd component part style work as expect:

<img width="1065" alt="截屏2023-05-16 16 45 11" src="https://github.com/ant-design/ant-design/assets/5378891/0adb282c-53e2-4ee6-9298-d92ced047a73">

**Comment by fyh1996** [comment]
我也出现了这个问题 在开发环境一切正常 但是在生成环境 antd的样式失效

**Comment by MadCcc** [comment]
> 

Hello there, any issues about nextjs with antd could be opened here. https://github.com/ant-design/create-next-app-antd is used to provide examples, and we mainly handle issues here :)

**Comment by RobinYang11** [comment]
> Could you help to provide a github repo about this? Seems your web antd component part style work as expect:
> 
> <img alt="截屏2023-05-16 16 45 11" width="1065" src="https://user-images.githubusercontent.com/5378891/238587504-0adb282c-53e2-4ee6-9298-d92ced047a73.png">


用ConfigerProvider 自定义主题会有问题 ，我把自定义主题干掉了
