### ISSUE TITLE
ColorPicker添加吸色功能

### ISSUE THREAD

**Issue by 1123612483** [ant-design/ant-design#42385]
### What problem does this feature solve?

用户可以在页面上吸取颜色，快速设置为ColorPicker的值。

### What does the proposed API look like?

```javascript
import { ColorPicker, theme } from 'antd';
import type { Color } from 'antd/es/color-picker';
import React, { useState } from 'react';

export default () => {
  return <ColorPicker dropper />;
};
```

### Demo
CodeSandbox: https://codesandbox.io/s/xi-qu-yan-se-antd-5-5-0-forked-0zfsod
示例: https://0zfsod.csb.app/

**Comment by 1123612483** [comment]
利用EyeDropper API去实现。
[https://wicg.github.io/eyedropper-api/#eyedropper-interface](url)

**Comment by yoyo837** [comment]
> 利用EyeDropper API去实现。 [https://wicg.github.io/eyedropper-api/#eyedropper-interface](url)

目前的兼容性， 不提也罢

**Comment by 1123612483** [comment]
> > 利用EyeDropper API去实现。 [https://wicg.github.io/eyedropper-api/#eyedropper-interface](url)
> 
> 目前的兼容性， 不提也罢

是的，目前基于Chromium内核的浏览器才支持。

**Comment by li-jia-nan** [comment]
<img width="1512" alt="image" src="https://github.com/ant-design/ant-design/assets/49217418/d9605fd8-d3f7-4d52-936a-54ba670c84fb">

**Comment by RedJue** [comment]
主要还是兼容性太差，加上目前也没有很好的解法去处理，所以在具体实现的时候弃了

**Comment by 1123612483** [comment]
> 主要还是兼容性太差，加上目前也没有很好的解法去处理，所以在具体实现的时候弃了

确实，还有一种做法就是只有在支持EyeDropper的浏览器显示吸管，不兼容的不显示，不过这种做法也不推荐。

**Comment by yoyo837** [comment]
而且，个人觉得，这个东西的必要性也没那么强烈。

**Comment by 1123612483** [comment]
> 而且，个人觉得，这个东西的必要性也没那么强烈。

是的，不过这个功能很强大，不仅仅是在浏览器吸取颜色，它甚至能够吸取屏幕像素的颜色。

**Comment by yoyo837** [comment]
见识短了我以为只能吸body下

**Comment by li-jia-nan** [comment]
> 见识短了我以为只能吸body下

这个是操作系统级别的

**Comment by li-jia-nan** [comment]
先关了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/43262#issuecomment-1612398546
