### ISSUE TITLE
Select使用了fieldNames选项，数据回显时还是需要label value这样的数据结构

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#42398]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-snyder-h6je5t?file=/src/App.tsx:353-369)

### Steps to reproduce

参考codesandbox

### What is expected?

使用fieldNames配置的选项

### What is actually happening?

必须使用label value

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | react |
| System | macos |
| Browser | chrome最新 |

---
是bug还是故意这样设计的

**Comment by hans000** [comment]
> `value` 的值是 `string[]`，你 `setFieldsValue` 填的是 `option`，自然不对了哈： https://codesandbox.io/s/exciting-merkle-6pbmwb?file=/src/App.tsx

我意思是启用labelInValue（少写了，抱歉）

**Comment by zombieJ** [comment]
`labelInValue` 和 `fieldNames` 是可以一起用的，最好是 HOC 一下，否则在应用页面混 Select 控制逻辑会比较乱哈~
