### ISSUE TITLE
Select增加optionsInValue选项

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#42399]
### What problem does this feature solve?

主要目的是解决一些Select的选项是搜索查询时做持久化数据回显的场景，可能那个时候只需要value的值，但由于是调接口查询options，因此还要手动维护options

### What does the proposed API look like?

设计一个optionsInValue选项，如果options为空可以把value的作为options

**Comment by zombieJ** [comment]
有 `labelInValue` 属性哈，可以参考一下这个例子：
https://ant.design/components/select-cn#components-select-demo-label-in-value

**Comment by zombieJ** [comment]
另外和表单组合场景如果觉得有些复杂，可以 HOC 一下 Select，把需要的东西封装到自定义组件里再用会方便不少哈~
