### ISSUE TITLE
Badge状态点只有processing有闪烁动画，其他的都没有

### ISSUE THREAD

**Issue by Renzo-Lee** [ant-design/ant-design#42397]
### Reproduction link

[https://ant.design/components/badge-cn#components-badge-demo-status](https://ant.design/components/badge-cn#components-badge-demo-status)

### Steps to reproduce

官方示例就存在这个问题
![image](https://github.com/ant-design/ant-design/assets/52516315/1c41624a-6f07-4b9d-8857-3ec00abe49b3)

### What is expected?

希望状态点要么都有闪烁动画，要么都没有动画

### What is actually happening?

只有processing有闪烁动画，其他的都没有

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | windows10 |
| Browser | Chrome版本 113.0.5672.93（正式版本） |

**Comment by li-jia-nan** [comment]
这个不是 bug，是设计如此吧

**Comment by Renzo-Lee** [comment]
> 这个不是 bug，是设计如此吧

 啊！这不 看着难受嘛，想关也关闭掉

**Comment by li-jia-nan** [comment]
```tsx
function App() {
  return (
    <Badge
      status="processing"
      className="customize-badge"
      text={<span>自定义样式</span>}
    />
  );
}
```

```css
.customize-badge .ant-badge-status-dot::after {
  display: none;
}
```

**Comment by afc163** [comment]
设计如此，只有 processing 是进行中状态，类似 loading 或 `<Skeleton />` 的 active 样式。
