### ISSUE TITLE
datapicker时区问题

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#424]
datapicker中选择“此刻”始终时北京时区，能提供指定或自动适应吗？

**Comment by afc163** [comment]
预计接口：

```
let locale = {
  timezoneOffset: 8 * 60,
  firstDayOfWeek: 1,
  minimalDaysInFirstWeek: 1,
  lang: {
    today: '今天',
    now: '此刻',
    ok: '确定',
    clear: '清除',
    previousMonth: '上个月 (翻页上键)',
    nextMonth: '下个月 (翻页下键)',
    monthSelect: '选择月份',
    yearSelect: '选择年份',
    decadeSelect: '选择年代',
    hourInput: '上一小时(上方向键), 下一小时(下方向键)',
    minuteInput: '上一分钟(上方向键), 下一分钟(下方向键)',
    secondInput: '上一秒(上方向键), 下一小时(下方向键)',
    hourPanelTitle: '选择小时',
    minutePanelTitle: '选择分钟',
    secondPanelTitle: '选择秒',
    yearFormat: 'yyyy\'年\'',
    monthFormat: 'M\'月\'',
    dateFormat: 'yyyy\'年\'M\'月\'d\'日\'',
    previousYear: '上一年 (Control键加左方向键)',
    nextYear: '下一年 (Control键加右方向键)',
    previousDecade: '上一年代',
    nextDecade: '下一年代',
    previousCentury: '上一世纪',
    nextCentury: '下一世纪',
  }
};
```

参考：

- https://github.com/react-component/calendar/blob/master/src/locale/zh-cn.js
- https://github.com/yiminghe/gregorian-calendar/blob/master/src/locale/zh-cn.js

**Comment by qiaolb** [comment]
支持神速，谢谢！

**Comment by Vsion** [comment]
我初始化一个RangeDatePicker
![image](https://cloud.githubusercontent.com/assets/11804448/20517946/52e55010-b0d8-11e6-864f-8f04997bcb9a.png)

我的本意是想改placehorder中的文字, 不好使啊= = 而且还有如图bug
![image](https://cloud.githubusercontent.com/assets/11804448/20517923/3d981d50-b0d8-11e6-8b44-7d10d9eae21e.png)

**Comment by afc163** [comment]
@Vsion 文档缺失了，在 https://github.com/ant-design/ant-design/commit/7b61b8414503b5018c075c9a2243cabfa973c07c 里补充了。

有问题建议新开 issue，否则很容易被忽视。

**Comment by Vsion** [comment]
@afc163  好的

**Comment by monsterooo** [comment]
[这个本地化](https://github.com/ant-design/ant-design/issues/424#issuecomment-150492079)没起作用呢？ 月份修改不到。而且新版的都是大Y格式化年份了。小y已经不支持了

**Comment by afc163** [comment]
@monsterooo 2.0 之后 locale 确实有变化，感谢提示。

https://ant.design/components/date-picker/#Common-API 里 locale 的文档链接需要更新下。@benjcui

**Comment by benjycui** [comment]
@monsterooo https://github.com/ant-design/ant-design/pull/4150
