### ISSUE TITLE
tabList in Card does not accept closeable as prop

### ISSUE THREAD

**Issue by AO19** [ant-design/ant-design#42405]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tablist-without-closable-8z674o?file=/index.js)

### Steps to reproduce

Set closeable false on tabList item.

### What is expected?

With the closeable prop set to false on the tabListItem, the X/ Close Icon should not appear.

I expected all the Tabs Props to also work on the Card tabsProps. Or that the tab items are treated the same and not have different props.

### What is actually happening?

Close Icon/ X is showing on tab.

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | React 18.2.0 |
| System | macOS 13.3.1 |
| Browser | Chrome 113.0.5672.92 |

**Comment by zombieJ** [comment]
Hmmm. This is not align with Tabs `items`. Need migrate in minor version.
