### ISSUE TITLE
Modal 的 className 的问题

### ISSUE THREAD

**Issue by 1587315093** [ant-design/ant-design#42401]
### What problem does this feature solve?

`className`  文档写着是 容器类名 设置上是在 `.ant-modal` 那一层，为什么不是  `.ant-modal-content` 那一层

这里的容器  与 modal 弹出的视觉感受有点区别吧
### What does the proposed API look like?

或许可以增加一个 `contentName`

![image](https://github.com/ant-design/ant-design/assets/77056991/37691ebd-0460-4ba6-b775-a330ce5aa44c)
![image](https://github.com/ant-design/ant-design/assets/77056991/2e7c9681-7250-4388-bddc-7d2f93b908d2)
![image](https://github.com/ant-design/ant-design/assets/77056991/4af092f0-cda5-4e48-9fd6-f8df40af418c)

**Comment by zombieJ** [comment]
包外层是可以用 css selector 对应到内部的，但是放内部就无法调整外部了。另外这个会在语义化 classNames 里一起考虑哈~

merge into #40221
