### ISSUE TITLE
Pagination component emits warnings related to Select component

### ISSUE THREAD

**Issue by saha80** [ant-design/ant-design#42418]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/c8e44g)

### Steps to reproduce

Open the console, and there will be "Warning: [antd: Select] `dropdownMatchSelectWidth` is deprecated. Please use `popupMatchSelectWidth` instead." 

### What is expected?

Expected to see no warnings.

### What is actually happening?

The `Pagination` component emits warnings related to the `Select` when no `Select` component is been used.

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | react@^18.0.0 |
| System | Windows 10 22H2 19045.2965 |
| Browser | Chrome 113.0.5672.93 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/42382
