### ISSUE TITLE
<RadioGroup /> 当前项选中时，再次点击仍会触发 onChange

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#4242]
如下图，最后 `B` 选项选中后，再次点击该项，仍然会触发`onChange`，是不是不触发会合理点？

![111](https://cloud.githubusercontent.com/assets/2840462/21174466/438e3bc6-c218-11e6-926b-1f306a03b2c7.gif)

**Comment by afc163** [comment]
确实如此。

**Comment by ystarlongzi** [comment]
那我尝试提个 PR
