### ISSUE TITLE
升级antd5.x部分用户平台样式全部丢失

### ISSUE THREAD

**Issue by whale-jung** [ant-design/ant-design#42427]
### Reproduction link

[https://ant-design.antgroup.com/components/tag-cn](https://ant-design.antgroup.com/components/tag-cn)

### Steps to reproduce

无复现地址

### What is expected?

无

### What is actually happening?

样式正常展示

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
升级前样式都是正常的，升级之后有一个用户平台样式都丢失了（清过缓存，没有开无痕模式，用谷歌浏览器和Safari都不行）

**Comment by RedJue** [comment]
> ### Reproduction link
> https://ant-design.antgroup.com/components/tag-cn
> 
> ### Steps to reproduce
> 无复现地址
> 
> ### What is expected?
> 无
> 
> ### What is actually happening?
> 样式正常展示
> 
> Environment	Info
> antd	5.0.0
> React	18
> System	mac
> Browser	chrome
> 升级前样式都是正常的，升级之后有一个用户平台样式都丢失了（清过缓存，没有开无痕模式，用谷歌浏览器和Safari都不行）

V5 有用到 where 选择器，低版本需要做降级处理。
