### ISSUE TITLE
关于 Search 组件的 defaultValue 

### ISSUE THREAD

**Issue by llqgit** [ant-design/ant-design#4243]
#### 发生问题的环境是：

- antd 版本: 2.5.2
- 操作系统及其版本: MacOS 10.12.1
- 浏览器及其版本: safari, chrome
- dva, redux

#### 您做了什么？请提供尽可能详细的重现步骤。

用 search 组件写了一个搜索框
```
<Search
  style={{ width: '100%' }}
  size='large'
  placeholder="请输入用户名"
  defaultValue={search_str}
  onSearch={onSearch}
/>
```
`defaultValue` 的 `search_str` 为 **store** 中的值，即上一次搜索保存的值

1. 搜索框默认为空

2. 当 **dispatch** 更改 **store** 中的 `search_str` 时（这个值例如：'abc'），该搜索组件的环境发生改变，`search_str` 打印出来 `abc`，已经变化。但是搜索框中的值却没变。

3. 当 再一次 **dispatch** 更改 **store** 中的 `search_str` => `123` 时，搜索框中的值变成 `abc` 而不是现在 **store** 中的值 `123`

如果不用 `defaultValue`，而使用 `value` 或者 `placeholder` 搜索框中的值都是当前 store 中的值
但是 使用 `value` 会导致搜索框不可修改的问题

#### 您期待的结果是:

能够设置 **input** 组件的初始值，就像 **placeholder** 一样，但是能够编辑

**Comment by afc163** [comment]
自行研习受控组件概念：http://facebook.github.io/react/docs/forms.html#controlled-components

---

Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by llqgit** [comment]
@afc163 我之前搜过 issues ，看了那个链接的内容，但是觉得不是一回事，所以来提问。
如果我没会错意的话，大神的意思是让我们用 组件的私有 state 来自己控制 value 的初始化和赋值。

可是，我觉得 Search 组件或者说 Input 组件的 defaultValue 不在正确的运行方式上。并且我们在用 dva 的那种无状态的代码模式。

现在，我的做法是在 Search 组件外面套了一个 Form 组件，利用 Form 组件的 `mapPropsToFields` 方法来初始化 Search 框的初始值。
虽然现在效果是正确的，但是我们却对 defaultValue 的作用产生质疑，如果不能设置初始值，请大神指教defaultValue 设计时的作用，也许是我们考虑的用法是错误的

在提一下我们遇到的错误，defaultValue 在第二次赋值时仍然使用上一次的值，按理说 defaultValue 只是在开始初始化一次，但是我们觉得每次更新 store 时都应该是新的组件在进行初始化，而不是一直用同一个组件，所以并不冲突。

可能在学习的路上理解并不全面，还请大神指教，谢谢

**Comment by afc163** [comment]
defaultValue 只有第一次生效，需要绑定的话用 value 和 onChange 自行控制，用 Form 组件也能达到类似的作用。

一切答案都在上面 react 的官方文档里了。

---

> 但是我们觉得每次更新 store 时都应该是新的组件在进行初始化

另外，并不是每次更新都有新的组件。

**Comment by llqgit** [comment]
明白了，多谢指点:P @afc163

**Comment by Zuckjet** [comment]
我也遇到这种问题了。
使用场景：我有一组checkbox，如果设置成defaultValue, 因为defaultValue需要点击操作能获取到值，在点击操作之前defaultValue为空。因为defaultValue只有第一次生效，所以这组checkbox不会有默认值。
但是如果我设置value属性，那么又会使得checkbox不能进行勾选操作。
求指导 @afc163 @llqgit

**Comment by llqgit** [comment]
@Zuckjet 要自定义动态改变初始值（defaultValue），用 Form + `mapStateToProps` 方法映射 store 中的值过来，或者 onChange 去 dispatch 到 store 然后设置 value， value 保持和 store 一致，不要去设置 标签的 defaultValue 属性

**Comment by Zuckjet** [comment]
@llqgit   Thank you very much

**Comment by songqiaoyi** [comment]
@Zuckjet 我也遇到相同的问题，还有一种解决方案，就是加载数据后再展现组件及设置defaultValue

**Comment by CZL95** [comment]
@Zuckjet 您好！我今天也遇到了和您一样的问题，困惑了我好久，虽然看了上面的解答，但还是得不到结果，如果您解决了问题，前端小白希望得到前辈的指点。谢谢！

**Comment by Zuckjet** [comment]
@songqiaoyi @CZL95  用state中的数据设置value值，然后在onChange事件中改变这个state值

**Comment by CZL95** [comment]
@Zuckjet 非常感谢!

**Comment by Trioblack** [comment]
Por favor, podem escrever em inglês? :(

**Comment by dengnan123** [comment]
学习了
