### ISSUE TITLE
Inline form multiple inputs having no margin bottom

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#42449]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-layout-antd-5-5-0-forked-6gdxgs?file=/demo.js)

### Steps to reproduce

Run codesandbox

### What is expected?

Margin bottom as normal vertical form

### What is actually happening?

As horizontal or vertical form, inline form also must have margin bottom, if we have multiple inputs they are all unified

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
It is broken in 5.x.

<img width="781" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/81e4aa32-5570-4465-9877-2c1abeedd827">

4.x is good.

<img width="1216" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/38e2766d-d002-4cee-a965-c11f3ce124be">

**Comment by Wxh16144** [comment]
Oh? It doesn't seem to be a bug 🤔 , it was designed that way

5.x and 4.x are the same.

5.x demo:  #Reproduction link
4.x demo: https://codesandbox.io/s/biao-dan-bu-ju-antd-4-24-10-forked-kmsfzq?file=/demo.tsx

**Comment by afc163** [comment]
@li-jia-nan 这个 maxWidth 要修改一下。

**Comment by li-jia-nan** [comment]
> @li-jia-nan 这个 maxWidth 要修改一下。

大佬 demo 这里具体怎么改？是要把 `max-width` 去掉吗？

**Comment by afc163** [comment]
<img width="280" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/b5ade618-e949-4035-9dea-bd2c8656d01c">

按 v4 这个样式的逻辑来改。

**Comment by li-jia-nan** [comment]
> 按 v4 这个样式的逻辑来改，简单说就是 form inline 时不需要给 maxWitdh: 600 。

- 大佬看看 #42476
