### ISSUE TITLE
v5.5.0 依赖 @rc-component/color-picker 版本问题

### ISSUE THREAD

**Issue by dingziqi** [ant-design/ant-design#42440]
### Reproduction link

[https://github.com/react-component/color-picker/blob/v1.1.0/src/index.tsx](https://github.com/react-component/color-picker/blob/v1.1.0/src/index.tsx)

### Steps to reproduce

运行项目

### What is expected?

正常运行

### What is actually happening?

编译报错，是因为 @rc-component/color-picker 1.1.0 移除了 ColorPickerPanel 从而导致报错

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18 |
| System | web |
| Browser | chrome |

**Comment by AntonyHunbert** [comment]
我也遇到了这个问题，现在还没有解决

**Comment by MadCcc** [comment]
antd 的对 `@rc-component/color-picker` 的依赖是 `~1.0.0`，默认不会安装到 v1.1.0 版本。出问题的是 v1.0.1，现在已经发布 1.0.2，重新安装依赖即可。
Ref: https://github.com/ant-design/ant-design/issues/42437

**Comment by BoyYangzai** [comment]
安装版本记得删除lock～

**Comment by MadCcc** [comment]
https://unpkg.com/browse/@rc-component/color-picker@1.0.2/es/index.js
v1.0.2 中有正确的 export。

**Comment by AntonyHunbert** [comment]
请问删除lock是什么意思，我是初学者，不太明白，大佬能否详细指点

**Comment by MadCcc** [comment]
> 请问删除lock是什么意思，我是初学者，不太明白，大佬能否详细指点

```bash
rm -rf node_modules && rm package-lock.json && npm i
```

**Comment by AntonyHunbert** [comment]
> > 请问删除lock是什么意思，我是初学者，不太明白，大佬能否详细指点
> 
> 如果你是npm的话 删除package.json文件 yarn -yarn-lock pnpm pnpm-lock lock文件是用来锁定版本的 删除之后重新安装就不会锁定版本了～

好的我试试，谢谢！

**Comment by BoyYangzai** [comment]
@AntonyHunbert 
package-lock.json 哈 上面那个大佬的命令可以直接跑 也可以手动删

**Comment by dingziqi** [comment]
删 lock 重装已解决

**Comment by devinRex** [comment]
> > 请问删除lock是什么意思，我是初学者，不太明白，大佬能否详细指点
> 
> ```shell
> rm -rf node_modules && rm package-lock.json && npm i
> ```

不建议直接删lock文件哈，建议remove antd，然后重新安装antd就好

**Comment by AntonyHunbert** [comment]
> 删 lock 重装已解决

请问是1.yarn remove antd
2. 删除 package-lock.json
3. 重新yarn add antd
吗

**Comment by AntonyHunbert** [comment]
> > > 请问删除lock是什么意思，我是初学者，不太明白，大佬能否详细指点
> > 
> > 
> > ```shell
> > rm -rf node_modules && rm package-lock.json && npm i
> > ```
> 
> 不建议直接删lock文件哈，建议remove antd，然后重新安装antd就好

我刚刚尝试了两次删除重装，但还是不行

**Comment by MadCcc** [comment]
@AntonyHunbert 用的什么包管理器？

**Comment by AntonyHunbert** [comment]
> @AntonyHunbert 用的什么包管理器？
yarn

**Comment by MadCcc** [comment]
@AntonyHunbert 
```bash
yarn remove antd && yarn add antd
```
如果不行的话就删除 lock 文件后重装
```bash
rm -rf node_modules && rm yarn.lock && yarn
```
如果还不行就要用 `npm ls antd` 看下是不是有其他依赖污染了

**Comment by AntonyHunbert** [comment]
> @AntonyHunbert
> 
> ```shell
> yarn remove antd && yarn add antd
> ```
> 
> 如果不行的话就删除 lock 文件后重装
> 
> ```shell
> rm -rf node_modules && rm yarn.lock && yarn
> ```
> 
> 如果还不行就要用 `npm ls antd` 看下是不是有其他依赖污染了

感谢，再次重装之后解决了！
