### ISSUE TITLE
Menu rerender after click, updating data in the table, changing component styles

### ISSUE THREAD

**Issue by eugenestepanyuk** [ant-design/ant-design#42441]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k-doc-phvkll?file=/src/pages/directories/names/index.tsx)

### Steps to reproduce
//For menu rerender after click
1. Click on any menu item

// For updating data
1. Press "Directories names" menu item
3. Press the add button, 
4. Fill in the fields
5. Press ok

### What is expected?
Menu not rerendering. Adding data and rendering table with updated data

### What is actually happening?
The fact is that now, on such a basic example, everything is done as it should, adding and updating the table is correct.
On my working project, I am fetching data from a database in the fetchDataTable function and populating it in setDataTable. After filling out the form, I send the data to the server and add it to the database, after which I call the fetchDataTable function again to get the actual data from the database (the handleOk function in the Modal component). But my props.fetch() is executed for some reason earlier than props.form?.submit() although it is after. I read that form.submit() can take some time to complete and therefore is executed after props.fetch(), how can I fix this, all my options turned out to be not working

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | windows 1909 |
| Browser | Google Chrome 112.0.5615.138 |

---
Also, after each click on the menu, it is recreated, how to make sure that the menu is not re-rendered when switching between pages?
Also, the question is how to change the styles of the components, in my case, these are changes in the style of the modal window buttons on hover.
In styles.module.scss file i changed button styles with :global but it didn't help

I will be grateful for your help

**Comment by sherry-vend** [comment]
@eugenestepanyuk , Did you find any solution to this?

I'm facing the same issue where I have a few items in the menu initially and later on, I add extra items based on the role of the logged in user.
