### ISSUE TITLE
Theme Editor syntax error on edit theme config 

### ISSUE THREAD

**Issue by Giogia** [ant-design/ant-design#42448]
### Reproduction link

[https://ant.design/theme-editor](https://ant.design/theme-editor)

### Steps to reproduce

Paste the following configuration in the "edit Theme Config" editor:
```
{
  "token": {
    "colorPrimary": "#1890ff",
    "colorSuccess": "#b7eb8f",
    "colorWarning": "#ffe58f",
    "colorError": "#f5222d",
    "colorInfo": "#9cdcfe",
    "colorTextBase": "#666666",
    "colorBgBase": "#ffffff",
    "colorBgLayout": "#f0f0f0",
    "fontSize": 14,
    "margin": 16,
    "padding": 16,
    "borderRadius": 4,
    "colorBgElevated": "#ffffff",
    "wireframe": false
  }
}
```

### What is expected?

The theme editor applies the theme configuration correctly.

### What is actually happening?

The theme editor returns "The theme of the JSON format is incorrect".

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | - |
| System | Ubuntu 22.04.2 |
| Browser | Google Chrome 113.0.5672.92 (Official Build) (64-bit) |

**Comment by BoyYangzai** [comment]
let me check it

**Comment by MadCcc** [comment]
Didn't get error with data provided. Could you provide a screen shot？
