### ISSUE TITLE
Rounded bottom border in table filter menu in dark mode

### ISSUE THREAD

**Issue by AmrAhmedA** [ant-design/ant-design#42444]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/filter-and-sorter-antd-5-5-0-forked-8yqfyz?file=/demo.tsx)

### Steps to reproduce

1- click on click me button
 
2- dark mode is shown

3- click on the name column filter in the table

4- filter menu is shown with rounded bottom border

### What is expected?

the table filter menu body bottom border shouldn't be rounded in dark mode. 

### What is actually happening?

the table filter menu body bottom border is rounded

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | React 18 |
| System | MacOs |
| Browser | Chrome - Version 113.0.5672.126 (Official Build) (arm64) |

---
The antd table filter menu in default mode color doesn't have any differences between the body and the footer color of the filter menu. so the rounded border is not apparent in the default mode. but in the dark mode, the footer color is different from the body color on the table filter menu. that is why there is difference in bottom border.

### dark mode behavior
<img width="320" alt="image" src="https://github.com/ant-design/ant-design/assets/47694180/d3a66f9c-1ff1-4013-8960-467d0edba1d0">
<br/>
<img width="177" alt="image" src="https://github.com/ant-design/ant-design/assets/47694180/d52b6501-ede1-4349-8847-e4e434cead6a">

### white mode behavior
<img width="179" alt="image" src="https://github.com/ant-design/ant-design/assets/47694180/ecb8cdae-8fcd-4645-802d-bbde0d80376b">

**Comment by AmrAhmedA** [comment]
> Changing its `border-radius` in the filter drop-down menu of the table should fix the problem here. Just like this: ![image](https://user-images.githubusercontent.com/112228030/238946605-ecb4634f-289d-4038-8264-10d84f847e6b.png)

Changing it via what? token based css change? direct css override?

**Comment by Yuiai01** [comment]
> Changing it via what? token based css change? direct css override?

I will submit a PR to fix this problem.
