### ISSUE TITLE
Add possible to add styles for header title in drawer.

### ISSUE THREAD

**Issue by nameishari** [ant-design/ant-design#42454]
### What problem does this feature solve?

The default behaviour of drawer is to show the close on the left side. 
But I want to display close icon on the right side, like below.

<img width="417" alt="image" src="https://github.com/ant-design/ant-design/assets/42765972/1f81958c-dce9-4e62-bbee-61b321aa7812">

Right now I was able to solve it by adding css:
```
.ant-drawer-header-title {
  flex-direction: row-reverse;
}
```
But it would awesome to have it supported on the api level.

### What does the proposed API look like?

<Drawer headerTitleStyles={{"flex-direction":"row-reverse"}}/>

**Comment by zombieJ** [comment]
Drawer provide `className` prop to config root drawer panel. So you can get title by the selector path:
https://codesandbox.io/s/ji-chu-chou-ti-antd-5-5-0-forked-94z4vh?file=/demo.tsx:144-220

**Comment by nameishari** [comment]
@zombieJ Yes I am aware of this, am doing exacts the same. The api already supports footerStyles, headerStyles, bodyStyles etc.. So I wanted to suggest to have headerTitleStyles.
But it's fine if you don't want it.
