### ISSUE TITLE
[Table] 在rowSelection中使用selectedRowKeys控制时，checkbox的disabled会失效。

### ISSUE THREAD

**Issue by Frezc** [ant-design/ant-design#4245]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: win10
- 浏览器及其版本: chrome 55

#### 您做了什么？请提供尽可能详细的重现步骤。

在Table组件中使用rowSelection，设置好getCheckboxProps的disabled触发条件，使用selectedRowKeys控制选中。
然后使用setState更新表格的dataSource使其符合该触发条件。

#### 您期待的结果是:

checkbox能直接正确地disable掉。

#### 实际上的结果是:

第一次更新时disabled会失效（如果有选中项，除了该项其他项会正常）。

#### 可重现的在线演示

http://codepen.io/Frezc/pen/qqJJeN?editors=001

**Comment by Fairyshi** [comment]
antd会根据 Table的 rowKey={record => record.uid} 对 CheckboxPropsCache进行缓存控制，要保证 getCheckboxProps 获取预期效果，请务必确保设置了<Table rowKey={record => ....} />，排查这个问题花了点时间，最后翻了源码才解决。见下面的链接中 155-170行：
https://github.com/ant-design/ant-design/blob/5d72c6d7e51dbe70ded98da0c87befd0f61c76d8/components/table/Table.tsx#L208-L210
