### ISSUE TITLE
Table pagination dropdown showing Warning: [antd: Select] `dropdownMatchSelectWidth` is deprecated. Please use `popupMatchSelectWidth` instead.

### ISSUE THREAD

**Issue by DercilioFontes** [ant-design/ant-design#42453]
### Reproduction link

[CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-k07vb3)

### Steps to reproduce

The table with pagination with the page size dropdown shows the warning. 
VM2101:1 Warning: [antd: Select] `dropdownMatchSelectWidth` is deprecated. Please use `popupMatchSelectWidth` instead.

### What is expected?

To not show the warnings.

### What is actually happening?

Showing the warning

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | macOS Ventura 13.3.1 |
| Browser | Version 115.0.5762.4 (Official Build) dev (arm64) |

---
This warning is new for v5.5.0. I changed some Select components, but it is showing for the Table dropdown that we can't change.
You need a large data to see it. It is on the link to minimal reproduction.

**Comment by saha80** [comment]
#42418

**Comment by DercilioFontes** [comment]
It seems my demo was not saved. I’m looking at it on another device now. I’ll update it later.

**Comment by DercilioFontes** [comment]
Fixed code sandbox link.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/42382 , wait for next patch.
