### ISSUE TITLE
RangePicker onCalendarChange only triggers with a range type of 'start'

### ISSUE THREAD

**Issue by premdav** [ant-design/ant-design#42450]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-tes0cm?file=/index.js)

### Steps to reproduce

Click on two dates of the calendar range picker. The dates will not get selected properly

### What is expected?

expecting to receive two different range types of 'start' for the first date clicked and 'end' for the second date picked

### What is actually happening?

Receiving one type of 'start' range for every date clicked

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | macos 13.3.1 |
| Browser | chrome 113.0.5672.92  |

**Comment by Yuiai01** [comment]
About the problem you describe. You can try changing the end date by selecting the end date first and then selecting again, so that `onCalendarChange` fires with a range type of `end`. Just like this:
![image](https://github.com/ant-design/ant-design/assets/112228030/6d03f47f-e9d3-4361-913e-740dcbfd76ba)

**Comment by zombieJ** [comment]
I can get the `end` as @Yuiai01 screenshot

**Comment by L-Ryland** [comment]
Noted different behavior on `DatePicker.RangePicker` and `TimePicker.RangePicker`. With the condition an initial value is already given, on date rangepicker, selecting only the start date with doesn't trigger an `onValuesChange` form event, but on time rangepicker, selecting the start time directly fires `onValuesChange`. While the initial value of time rangepicker is still empty, selecting the start time doesn't fire it. 

Here's the url for producing the problems: 
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-rhrc5y?file=%2Findex.js%3A61%2C23
