### ISSUE TITLE
Form 组件在onValuesChange里面使用form.validateFields()会一直触发catch

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#42465]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-10-forked-1wkro9)

### Steps to reproduce

输入框输入内容观察控制台

### What is expected?

不会打印catch

### What is actually happening?

会一直打印catch

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by zombieJ** [comment]
因为你的这个 validate 过期了：
<img width="206" alt="截屏2023-05-18 15 18 48" src="https://github.com/ant-design/ant-design/assets/5378891/d8498dfa-23bb-4517-b231-a1084e0eab01">

Form 本身在字段变化时会触发 change 事件并且校验，你在 change 事件里校验会被之后的校验给盖掉。

ref: [为什么字段设置 rules 后更改值 onFieldsChange 会触发三次？](https://ant.design/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%AD%97%E6%AE%B5%E8%AE%BE%E7%BD%AE-rules-%E5%90%8E%E6%9B%B4%E6%94%B9%E5%80%BC-onfieldschange-%E4%BC%9A%E8%A7%A6%E5%8F%91%E4%B8%89%E6%AC%A1)
