### ISSUE TITLE
树组件中，异步数据加载当前节点的子节点数据children为空时，会一直重复调用loadData

### ISSUE THREAD

**Issue by MrMengJ** [ant-design/ant-design#42460]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-24-10-forked-ilqeul)

### Steps to reproduce

展开树节点，重复循环调用loadData

### What is expected?

不循环调用loadData

### What is actually happening?

重复循环调用loadData

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | "react": "17.0.2" |
| System | windows 11 |
| Browser | Chrome 111.0.5563.111 |

---
业务场景需要每次展开节点，都请求最新的子节点数据，故设置 loadedKeys 为 空数组
用户A初次加载树，树节点a是有子节点的，即isLeaf为false
用户B此时将a节点的所有子节点删除，导致a节点下没有子节点
用户A点击展开a节点，从服务端请求回来子节点数据为空数组，导致loadData重复调用，重复发送数据请求

**Comment by zombieJ** [comment]
`loadedKeys` 就是用来检查是否加载过的，设置为空数组后自然是要去查询的。

**Comment by BoyYangzai** [comment]
@MrMengJ 第一次用这个组件 应该是这样子用吧ovo 
https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-4-24-10-forked-g3ey1e?file=/demo.tsx

**Comment by MrMengJ** [comment]
@

> > `loadedKeys` 就是用来检查是否加载过的，设置为空数组后自然是要去查询的。
> 
> 那请问如果不设置 `loadedKeys` 为空数组，怎么让每次展开节点都去查询子节点呢

@zombieJ 你好，需求就是想每次展开节点都去重新请求一下子节点，当子节点为空数据时就会出现以上问题，这是一个bug

**Comment by snowflakett** [comment]
@MrMengJ 请问老师是如何处理此问题的呢 我也遇到此问题  卡了一天了

**Comment by MrMengJ** [comment]
> @MrMengJ 请问老师是如何处理此问题的呢 我也遇到此问题 卡了一天了

没有解决，放弃每次展开节点都去请求最新数据了

**Comment by CharlesLeocc** [comment]
我也遇到了同样的问题，展开父节点时，请求接口返回的子节点为空，然后loadData就会一直重复请求。。。

**Comment by zdJOJO** [comment]
> 我也遇到了同样的问题，展开父节点时，请求接口返回的子节点为空，然后loadData就会一直重复请求。。。

老哥 我也卡住， 如何解决？

**Comment by CharlesLeocc** [comment]
子节点为空时 将父节点的children置为空数组,并设置节点的isLeaf=false，就不会一直请求了
