### ISSUE TITLE
Ant Responsive Navbar Menu Web?

### ISSUE THREAD

**Issue by ga12ru12** [ant-design/ant-design#4246]
How can i do the navbar responsive menu like in [home page](https://ant.design/)?

**Comment by afc163** [comment]
Use the media query: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries, which is not related to antd, actually.

**Comment by johhansantana** [comment]
@afc163 is there anything close to something like [sider responsive](https://ant.design/components/layout/#components-layout-demo-responsive) component for the Menu?

**Comment by afc163** [comment]
https://ant.design/components/layout/#components-layout-demo-side

**Comment by johhansantana** [comment]
@afc163 that only works for the Sider though right? I would have to make 2 separate menus, one with regular `Menu` and the other one with `Sider` and show/hide each one with media queries or javascript?

**Comment by afc163** [comment]
You can controll Menu by `inlineCollapsed`: https://ant.design/components/menu/#components-menu-demo-inline-collapsed

**Comment by mitjade** [comment]
@afc163 I am struggling with this as well. Maybe an example of horizontal responsive menu like in [docs](https://ant.design/docs/react/introduce) the docs would really clear things up.

**Comment by mitjade** [comment]
Found an example [here](https://github.com/ant-design/ant-design-pro-site/blob/master/site/theme/template/Layout/Header.jsx).
