### ISSUE TITLE
TimePicker禁用时间bug

### ISSUE THREAD

**Issue by KejieLiu** [ant-design/ant-design#42468]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-4-24-10-forked-2zx3o7?file=/demo.tsx)

### Steps to reproduce

通过先选9点的00分，再选8点，就可以选到8：00。实际8点已经禁用00到29分

### What is expected?

8点只能选到8点半以后

### What is actually happening?

通过先选9点的00分，再选8点，就可以选到8：00

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17.0.2 |
| System | windows |
| Browser | chrome113.0.5672.93 |

**Comment by Yuiai01** [comment]
这个问题我来康康~

**Comment by Yuiai01** [comment]
> 这个问题解决了吗，应该是`rc-picker`中选择小时后没有判断是否设置`disabledTime `导致的吧，不清楚是否有必要进行修改🤔

是的，我的想法是更换位置后判断相对事件为禁用时间的话，那么就清空

**Comment by linxianxi** [comment]
我在解决了
