### ISSUE TITLE
ColorPicker新增属性renderExtraFooter

### ISSUE THREAD

**Issue by 1123612483** [ant-design/ant-design#42470]
### What problem does this feature solve?
跟DatePicker一样，在浮层中加入额外的页脚，可以自定义一些功能，比如添加一个按钮，配合`open`用于关闭浮层。
https://ant.design/components/date-picker-cn#components-date-picker-demo-extra-footer
效果：
![image](https://github.com/ant-design/ant-design/assets/20741541/66e063a2-8d58-47a5-a022-92b8e107cbad)

### What does the proposed API look like?
| 参数 | 说明 | 类型 | 默认值 | 版本 |
| --- | --- | --- | --- | --- |
| renderExtraFooter | 在面板中添加额外的页脚 | (mode) => React.ReactNode | - |  |

**Comment by Wxh16144** [comment]
这感觉是一个合理的功能建议 👍 , 此外我发现 API 默认有一个 `open` 用于控制面板打开状态, 是否可以考虑加一个 `defaultOpen` 用于非受控的?

**Comment by RedJue** [comment]
https://github.com/react-component/color-picker#api rc 已经实现了，`antd` 里需不需要暴露这个 `API` 得等维护者讨论下哈~

**Comment by MadCcc** [comment]
这个 feature 短期内不会有哈，需要更合适的场景，这个 issue 会保持开启。

“确定”按钮和内部逻辑息息相关，可以参考 RangePicker 这个组件，仅有自定义 render 是无法完成这个逻辑的。所以这个可能属于另一个 feature

**Comment by dez0514** [comment]
能否再细一点，新增 disableAlpha 属性，隐藏透明度相关的部件，某特定情况下不希望用户修改透明度。

**Comment by 1123612483** [comment]
> 这个 feature 短期内不会有哈，需要更合适的场景，这个 issue 会保持开启。
> 
> “确定”按钮和内部逻辑息息相关，可以参考 RangePicker 这个组件，仅有自定义 render 是无法完成这个逻辑的。所以这个可能属于另一个 feature

目前我能想到的场景就是`确定`，更准确应该是`关闭`，`ColorPicker`关闭浮层的方式很奇怪，不像`DatePicker`选中立即关闭浮层，是需要点击浮层外部区域，有些用户不习惯，解决方法要么就是开放自定义 render给使用者实现，要么`ColorPicker`内部封装实现，我更倾向于开放自定义 render去解决。

**Comment by 1123612483** [comment]
> 这个 feature 短期内不会有哈，需要更合适的场景，这个 issue 会保持开启。
> 
> “确定”按钮和内部逻辑息息相关，可以参考 RangePicker 这个组件，仅有自定义 render 是无法完成这个逻辑的。所以这个可能属于另一个 feature

当然还有一个场景就是封装`ColorPicker`组件，更改颜色修改内部`state`不传给父组件，而且点击浮层外部不要关闭浮层，必须点击`确定`按钮后，关闭浮层，把颜色值传给父组件。

**Comment by 1123612483** [comment]
> 能否再细一点，新增 disableAlpha 属性，隐藏透明度相关的部件，某特定情况下不希望用户修改透明度。

对的，`react-color`是有这个属性

**Comment by RedJue** [comment]
> > 能否再细一点，新增 disableAlpha 属性，隐藏透明度相关的部件，某特定情况下不希望用户修改透明度。
> 
> 
> 
> 对的，`react-color`是有这个属性

这个我觉得可以考虑加上，毕竟确实有不想要透明度的场景。@MadCcc

**Comment by 1123612483** [comment]
https://tdesign.tencent.com/react/components/color-picker?tab=api
![image](https://github.com/ant-design/ant-design/assets/20741541/f4f729d9-07b0-4494-9e21-ba800d0ff491)

**Comment by 1123612483** [comment]
#43134
