### ISSUE TITLE
Sometimes render component without style.

### ISSUE THREAD

**Issue by charian** [ant-design/ant-design#42477]
### Steps to reproduce
sometimes, navigating 

### What is actually happening?
Sometimes, when switching between screens, a component's style doesn't load.
For example, on a screen using a Button component, the button will render like a pure html button with no styles applied.

The logic of CSS-IN-JS seems to declare the following style in the header of the component used in the screen, but sometimes it doesn't work that way.
<style data-rc-order="prependQueue" data-css-hash="1tm4gwl" data-token-hash="1tzbqhu"> <style data-rc-order="prependQueue" data-css-hash="1tm4gwl

I am using the primary color in index.js by setting it via ConfigProvider.

<img width="1727" alt="bug" src="https://github.com/ant-design/ant-design/assets/2831532/1188ec09-2530-44fc-9482-d2ff3dbffc71">

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | latest |
| System | mac, windows |
| Browser | chrome, safari |

**Comment by nguyenvuhoang** [comment]
Hello . same my issue. have any fixed?
