### ISSUE TITLE
Form.Item下嵌套一个div， div下再嵌套Input，Input修改内容后会设置form field value

### ISSUE THREAD

**Issue by wangzhengbo** [ant-design/ant-design#42475]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-fang-fa-diao-yong-antd-5-5-0-forked-hnut0w?file=/demo.tsx)

### Steps to reproduce

三个Note输入框分别输入内容，查看console日志输出。

### What is expected?

```javascript
<Form.Item name="note">
  <div>
   <Input />
  </div>
</Form.Item>
```
之前的版本，Input中输入内容后，不会导致form item的value改变，因为Input和Form.Item中间用div隔离了。
现在会导致form item的value改变。这个是bug吗？还是在antd哪个版本中特意改成这样的呢? 5.0版本改的吗？

如果不用div，改成fragment，Input中输入内容后，form item的value不会改变。
```javascript
<Form.Item name="note">
  <>
   <Input />
  </>
</Form.Item>
```

### What is actually happening?

见上面的描述。

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome 113 |

**Comment by afc163** [comment]
onChange 事件会冒泡，因此 div 也能作为 Form.Item 的直接子元素，监听到表单项内容变化：https://codesandbox.io/s/div-onchange-gg8yzh?file=/demo.tsx

**Comment by wangzhengbo** [comment]
> onChange 事件会冒泡，因此 div 也能作为 Form.Item 的直接子元素，监听到表单项内容变化：https://codesandbox.io/s/div-onchange-gg8yzh?file=/demo.tsx

那之前的某些版本不会这样呢？
antd 4.x应该不是这样的。5.x早期版本不太确定。
