### ISSUE TITLE
怎么让展开的行关闭

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#4247]
额外的table展开行 点击打开了 ，  怎么用其他的操作 把展开的行关闭？

**Comment by yesmeck** [comment]
`expandedRowKeys `

**Comment by qq645381995** [comment]
@yesmeck   怎么用呢  不应该参数是bool吗？

**Comment by yesmeck** [comment]
看文档，`expandedRowKeys` 是数组，里面的值是需要展开行的 `key`。

**Comment by qq645381995** [comment]
我提的问题是 比方触发个事件  把已经展开的全部关闭！！   不是要 展开行的key  文档只有说明  没看到实现！

**Comment by yesmeck** [comment]
`expandedRowKeys` 就类似于 `input` 的 `value`，给 `Table` 传 `expandedRowKeys` 后，需要展开哪些行，收起哪些行，就是你自己来控制了。需要展开的行就把 `key` 放 `expandedRowKeys` 里，需要收起的行就把相应的 `key` 从 `expandedRowKeys` 里去掉。

**Comment by qq645381995** [comment]
expandedRowKeys={[1]}  这样是展开第一行吗？  但是 都打不开了

**Comment by yesmeck** [comment]
自己学习下受控组件的知识吧 https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by afc163** [comment]
github 有置顶功能就好了，这个问题太多了。而且用户都不看 FAQ：https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically

**Comment by qq645381995** [comment]
哦 知道了  expandedRowKeys  的 Array  填充的不是行的索引   是table的rowKey  都不说清楚 你说是key  我理解成索引了 ，现在好了

**Comment by qq645381995** [comment]
@afc163  有问的问题 改了 可以在文档中更新下，描述清楚些，或者 放个demo  那样后来的人看文档就够了 其实就不需要看这里了

**Comment by afc163** [comment]
https://facebook.github.io/react/docs/forms.html#controlled-components

说的是这个。理论上不是 antd 的问题，属于 react 基础知识，我们不可能每个组件都去说这个的。

**Comment by qq645381995** [comment]
这个我知道啊  我只是不知道你这个 api  要怎么去使用，传的参数我误以为是table  行的 索引了 我给成 rouKey就好了，

**Comment by qq645381995** [comment]
虽然之前我不知道受控组件的定义  但是实际应用中 就是 props是不可改的，state是可改的，你这个当然要动态的 setState更改

**Comment by yesmeck** [comment]
欢迎帮我们改进文档。

**Comment by qq645381995** [comment]
expandedRowKeys  要使用起来 还需要  onExpandedRowsChange  这个方法中去 setState  这个文档就没有说明

**Comment by yesmeck** [comment]
这个就是 React 里使用受控组件的基础知识，我们没办法在 antd 的文档里教人怎么用  React。

**Comment by qq645381995** [comment]
好吧 知道了 谢谢大大们解答。
