### ISSUE TITLE
form 组件getFieldsValue(namePath) 与 getFieldsValue() 对 preserve={false} 的字段取值逻辑不同

### ISSUE THREAD

**Issue by bearguo** [ant-design/ant-design#42474]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/getfieldsvalue-bug-demo-j17zh6)

### Steps to reproduce

切换field1的值，观察控制台

### What is expected?

getFieldsValue(namePath) 与 getFieldsValue() 对 preserve={false} 的字段取值逻辑相同

### What is actually happening?

getFieldsValue(namePath) 与 getFieldsValue() 对 preserve={false} 的字段取值逻辑不同

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | ^18.0.0 |
| System | macOS 11.3.1 |
| Browser | chrome 113.0.5672.126 |

**Comment by bearguo** [comment]
感觉getFieldsValue()的逻辑是对的，getFieldsValue(namePath)忽略了preserve这个字段对表单值的影响

**Comment by zombieJ** [comment]
`getFieldsValue` 默认会过滤 FormInstance 中不存在对应字段的值。在设置路径时则会按照路径获取对应的值，在设置 `true` 时会直接返回所有的值。这个设计就是为了满足不同的需求，如果是不需要不存在字段的值，直接 `getFieldsValue().xxx` 获取即可（就是你的例子中另一个写法）：
<img width="531" alt="截屏2023-05-18 23 15 20" src="https://github.com/ant-design/ant-design/assets/5378891/6b9e6c4b-bcdc-4c18-948a-fb082525697f">
