### ISSUE TITLE
Layout组件在浏览器刷新时会造成短暂的布局错乱

### ISSUE THREAD

**Issue by Yuuki-Yuuna** [ant-design/ant-design#42487]
### Reproduction link

[https://ant-design.antgroup.com/components/layout-cn](https://ant-design.antgroup.com/components/layout-cn)

### Steps to reproduce

直接在布局页面刷新浏览器即可

### What is expected?

![](https://cdn.jsdelivr.net/gh/Yuuki-Yuuna/images/image/antd-test1.png)

能够正确显示

### What is actually happening?

![](https://cdn.jsdelivr.net/gh/Yuuki-Yuuna/images/image/2023-05-19%20(2).png)

加载中布局错位

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | window 10 |
| Browser | Microsoft Edge v113.0.1774.42 |

---
是css中的`flex-direction: row`属性加载过慢导致的，使用style设置layout后就正常了

**Comment by MadCcc** [comment]
其实是 Sider 里有 effect 控制布局了，算是个遗留问题，可以优化

**Comment by afc163** [comment]
Demo 里加个 hasSider
