### ISSUE TITLE
没有图片选择器

### ISSUE THREAD

**Issue by JiaErGen** [ant-design/ant-design#42486]
### What problem does this feature solve?

可以选择图片

### What does the proposed API look like?

<ImageSelect options={[{ label: '图片地址', value: '图片地址' }, { label: '图片地址', value: '图片地址' }]} />

**Comment by MadCcc** [comment]
Upload？

**Comment by MadCcc** [comment]
和 https://github.com/ant-design/ant-design/issues/41618 类似吧

**Comment by MadCcc** [comment]
Merged into #41518
