### ISSUE TITLE
自定义类组件使用 @ant-design/cssinjs 来实现css in js 方案， Dropdown组件不展示自定义下拉框内容 

### ISSUE THREAD

**Issue by cx91** [ant-design/ant-design#42488]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuo-zhan-cai-dan-antd-5-5-0-forked-mq23vl?file=/demo.tsx)

### Steps to reproduce

鼠标移上去不显示Dropdown组件的自定义下拉框内容 

### What is expected?

鼠标移上去展示Dropdown组件的自定义下拉框内容 

### What is actually happening?

不展示自定义下拉框内容 

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.0.0 |
| System | macOS Ventura 13.3.1 |
| Browser | Chrome   113.0.5672.92 |

---
1、因为以前的组件是类写法，想采用css in js 方案，所以采用了@ant-design/cssinjs
2、由于 @ant-design/cssinjs 组件好像只能在hook里面使用，为了不去大改组件，所以写了一个高阶组件包裹一下处理
3、css in js 生成的样式是生效了的，就是Dropdown的内容不展示

**Comment by MadCcc** [comment]
目前不推荐使用 `@ant-design/cssinjs` 作为 cssinjs 方案哈，这个库为 antd 定制的，上手难度较高。
复现中 Dropdown 不展示的原因是 Dropdown 的 children 需要能够接受鼠标事件，透传到 dom 元素上。参考：https://ant-design.antgroup.com/components/tooltip-cn#%E6%B3%A8%E6%84%8F
