### ISSUE TITLE
Select multiple style have align issues

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42489]
https://codesandbox.io/s/duo-xuan-antd-5-5-0-forked-hor1sf?file=/demo.tsx

- [ ] 选中文案和关闭按钮都没有垂直居中。
<img width="616" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/9b331c94-177d-43ad-9b31-40430e24acd1">

- [ ] 选中✅没有垂直居中。
<img width="616" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/0e7cbe44-9925-4c4e-9c9e-8b2db412baac">

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/b7f0d371-c8d3-4efa-ad52-922bf30823ca)
感觉其实 baseline 对齐了的，中文会比较偏上

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/0deb2f6e-98b3-40d6-8ca0-4d0a4b5b7750)
看了一下去掉边框之后高度还保持 24px，line-height 也保持了 22px，所以整体看起来比较偏上。
1. tag 调整为 22px，符合行高
2. 文字行高改为 24px
二选一吧
