### ISSUE TITLE
ConfigProvider组件会错误地导入整个'rc-field-form'，导致包体积剧增

### ISSUE THREAD

**Issue by BanShan-Alec** [ant-design/ant-design#42499]
### Reproduction link

[https://github.com/BanShan-Alec/test-bundle-antd](https://github.com/BanShan-Alec/test-bundle-antd)

### Steps to reproduce

https://codesandbox.io/p/sandbox/stupefied-euclid-6twq7w

- `yarn build`
- `yarn analyze`

然后会生成`source-map-explorer`的分析报告，输出路径`./result.html`

查看分析报告，发现'rc-field-form' 中 useForm.js，Field.js 等资源都被错误地打包。

而我并没有使用Form组件&相关hook，只是使用ConfigProvider组件

### What is expected?

没有使用到的资源，不要错误地被打包进去

### What is actually happening?

查看分析报告，发现'rc-field-form' 中 useForm.js，Field.js 等资源都被错误地打包。
![rc-field-form 问题](https://github.com/ant-design/ant-design/assets/44499686/11161494-76d3-4e80-a53f-57b097008cac)

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18.x, 17.x |
| System | windows |
| Browser | chrome 113 |

---
https://github.com/ant-design/ant-design/issues/41607，有类似问题但是被关闭了；

我尝试过比较旧的Antd4.x版本，该问题也被复现。
我不太清楚，这是`antd` import 方式错误导致的，还是`rc-field-form` export 方式有问题。

同时，我对antd中`rc-field-form`的引用进行分析，发现ConfigProvider的这行代码可能是问题的原因之一。
然后，我尝试进行修改FormProvider`的引用方式，并对比修改前后的打包产物发现，这样的修改可以解决上述问题。

![image](https://github.com/ant-design/ant-design/assets/44499686/c412644c-ca6e-46f7-8348-ab8c1c46a908)

![image](https://github.com/ant-design/ant-design/assets/44499686/8a236acb-3a94-4339-bf35-9df6980b2ccd)

**Comment by BanShan-Alec** [comment]
![image](https://github.com/ant-design/ant-design/assets/44499686/b2c144cf-5137-4082-9d4a-a7284e2140d2)
感觉是这个导致整个rc-field-form都被导出了

**Comment by yoyo837** [comment]
`ConfigProvider` 确实有直接引用 `rc-field-form` 的 `FormProvider`

**Comment by yoyo837** [comment]
Reopen by https://github.com/ant-design/ant-design/pull/42604#issuecomment-1562386072

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/43023

**Comment by yoyo837** [comment]
> Fixed in #43023

That fix is for v5, not for v4.

**Comment by BanShan-Alec** [comment]
> > Fixed in #43023
> 
> That fix is for v5, not for v4.

期望v4尽快被修复，该issue提出已经超过一个月的时间了

**Comment by yoyo837** [comment]
Fixed in #43207
