### ISSUE TITLE
RangePicker设置 disabled=[false, true] 之后，第二项还是能改

### ISSUE THREAD

**Issue by gu-xiaohui** [ant-design/ant-design#42493]
### Reproduction link

[https://ant.design/components/date-picker-cn#components-date-picker-demo-disabled](https://ant.design/components/date-picker-cn#components-date-picker-demo-disabled)

### Steps to reproduce

点击禁用例子，正常选择日期

### What is expected?

被禁用的项不能被修改

### What is actually happening?

被禁用的项还是能被修改

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.1.0 |
| System | MacOS ventura 13.3.1 (22E261) |
| Browser | Microsoft Edge 113.0.1774.42 (正式版本) (x86_64) |

**Comment by Wxh16144** [comment]
5.x does have problems, 4.x is good
