### ISSUE TITLE
能否为Modal添加 可去除动画的api。Add api for Modal to remove animations

### ISSUE THREAD

**Issue by ByYogi** [ant-design/ant-design#42490]
### What problem does this feature solve?

有时动画速度太慢，会影响页面的视觉效果。
The animation speed is too slow, which will affect the visual effect of the page

### What does the proposed API look like?

{animated: false}

**Comment by MadCcc** [comment]
通过 ConfigProvider 的 theme 修改动画时间或者关闭动画
![image](https://github.com/ant-design/ant-design/assets/27722486/5885999e-f2c2-4322-9a02-c704fba0f9a8)

Ref: https://ant-design.antgroup.com/docs/react/customize-theme-cn#seedtoken

**Comment by gantrylau** [comment]
如何指定Modal禁用动画而非全局设置
