### ISSUE TITLE
nodejs如何使用ant-design

### ISSUE THREAD

**Issue by lucifercd** [ant-design/ant-design#425]
我是一名新手，试了几次在nodejs(thinkjs框架)里面使用ant-design，都没有成功。nodejs加载模块大部分是require方式，ant-design的快速上手使用的import React from 'react';   不知道在项目中怎么使用？
建议以后的教程可以针对新手一些，也利于项目的传播。

**Comment by benjycui** [comment]
[`import`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/import) 是 ES6 的语法。

```js
import React from 'react'; 
```

等价于：

```js
var React = require('react');
```

**Comment by afc163** [comment]
是使用 webpack 进行打包，服务端渲染目前没有试过。
