### ISSUE TITLE
Collapse Panel is getting close on click of Enter

### ISSUE THREAD

**Issue by agrajit-cubyts** [ant-design/ant-design#42503]
### What problem does this feature solve?

Normally also the collapse is getting close on click of Enter. In my Case , I have Editable Paragraph in header prop of Panel and that should be saved on click of Enter. Its getting saved also but along with that the collapse Panel is also getting closed . So here the collapse Panel should not get close on click of Enter

### What does the proposed API look like?

it Should prevent the Collapse from closing on press of Enter

**Comment by kiner-tang** [comment]
You can try to prevent the event from bubbling like this:
https://codesandbox.io/s/krpny5?file=/demo.tsx

**Comment by agrajit-cubyts** [comment]
> You can try to prevent the event from bubbling like this: https://codesandbox.io/s/zhe-die-mian-ban-antd-5-5-0-forked-575ds4

tried that but still its not working.

**Comment by kiner-tang** [comment]
@agrajit-cubyts If you using Typography, you can try to wrapper a `div` outside the Typography and prevent the event from bubbling like this:
https://codesandbox.io/s/zhe-die-mian-ban-antd-5-5-0-forked-575ds4?file=/demo.tsx

**Comment by agrajit-cubyts** [comment]
@kiner-tang thanks for the solution. It worked like a charm. Just curious to know if we can use any other event than onKeyPress because it seems onKeyPress is deprecated. I tried with onKeyUp and onKeyDown. But that does not work.

**Comment by kiner-tang** [comment]
@agrajit-cubyts Of course, we'll talk about it, and then we'll try to do some internal refactoring, and we'll synchronized here about it.
