### ISSUE TITLE
V5.5.0 Form组件中form和initialValues冲突

### ISSUE THREAD

**Issue by wenzhu-eternal** [ant-design/ant-design#42505]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-bug-r5g06f?file=/demo.tsx)

### Steps to reproduce

1.分别两个点击button，看弹窗中数据效果；
2.然后删除Form组件的form属性后，再次点击两个button，看弹窗中数据效果

### What is expected?

两次结果应该一致

### What is actually happening?

第一个数据无法重置
第二个可以

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | macos 11.7.1 |
| Browser | Google Chrome 113.0.5672.92 |

**Comment by BoyYangzai** [comment]
@wenzhu-eternal 我认为这是符合预期的
![image](https://github.com/ant-design/ant-design/assets/94534613/ba720fba-f488-4930-a7cf-90e3ea13169b)
文档里很明确的说明了 如果不绑定 form 就会自动去创建实例
initalValue在 Form 创建时生效
开关Modal相当于重新卸载安装 Form 组件 他会自动创建一个新的实例
而如果用 useForm 的 form 实例 
那每次 Form渲染时都会去使用  useForm 的 form 实例 ，Select的值也就不会随着重新 Form Render 而 initalValue 生效了

**Comment by yoyo837** [comment]
你说的对，我没注意到 destroyOnClose

**Comment by wenzhu-eternal** [comment]
@BoyYangzai 不，Modal的destroyOnClose会清空Modal中所有节点，那么这个时候form应该是更新的；
并且原先版本一直是这样的，不知道从啥时候开始就变成不可以了

**Comment by wenzhu-eternal** [comment]
@yoyo837 这个目前就是定位成bug了吗？预计啥时间修复，还是是我们自己想办法处理

**Comment by yoyo837** [comment]
我不了解之前什么效果，但 destroyOnClose 去到应该能满足你的需求，你所说的“应该更新”，我不太理解，如果Modal内需要销毁，所谓“更新”相对什么？如果用户只点击了一个按钮呢？

**Comment by wenzhu-eternal** [comment]
@yoyo837 就比如说一个表格，然后用户点击编辑每次塞数据到form，关闭之后需要销毁节点，第二次在塞值进去就只能用form.setFieldsValue？不能使用例子当中的使用initialValues

**Comment by wenzhu-eternal** [comment]
@yoyo837 如果不销毁的Modal中子节点，那么initialValues只有第一次更新是有效，下来就只能使用form.setFieldsValue，而不能说根据state中的改变而改变数据当中的值

**Comment by yoyo837** [comment]
> @yoyo837 如果不销毁的Modal中子节点，那么initialValues只有第一次更新是有效，下来就只能使用form.setFieldsValue，而不能说根据state中的改变而改变数据当中的值

所以去掉form={form}，两次按钮点击不一样不就和你说的是一致的表现吗？区别在于不去掉form={form}时这个form是useForm提供的，是同一个。

**Comment by wenzhu-eternal** [comment]
> > @yoyo837 如果不销毁的Modal中子节点，那么initialValues只有第一次更新是有效，下来就只能使用form.setFieldsValue，而不能说根据state中的改变而改变数据当中的值
> 
> 所以去掉form={form}，两次按钮点击不一样不就和你说的是一致的表现吗？区别在于不去掉form={form}时这个form是useForm提供的，是同一个。

对的，可以这么说；如果按照代码来讲的话，意思就是Modal子节点销毁后二次打开这个时候Form组件应该是新的，那么这个时候初始化不应该取initialValues中的值吗？现在情况是没有取initialValues中的值而取了form中的值

**Comment by yoyo837** [comment]
按我的表述，这是预期的，不清楚你是理解

**Comment by wenzhu-eternal** [comment]
> > > @yoyo837 如果不销毁的Modal中子节点，那么initialValues只有第一次更新是有效，下来就只能使用form.setFieldsValue，而不能说根据state中的改变而改变数据当中的值
> > 
> > 
> > 所以去掉form={form}，两次按钮点击不一样不就和你说的是一致的表现吗？区别在于不去掉form={form}时这个form是useForm提供的，是同一个。
> 
> 对的，可以这么说；如果按照代码来讲的话，意思就是Modal子节点销毁后二次打开这个时候Form组件应该是新的，那么这个时候初始化不应该取initialValues中的值吗？现在情况是没有取initialValues中的值而取了form中的值

你觉按照这句话的后半句看，initialValues定义不是表单默认值，只有初始化以及重置时生效吗？Form组件重新从无到有这个过程不算初始化吗？


<br class="Apple-interchange-newline">

**Comment by yoyo837** [comment]
使用form={form}时，form只初始化一次，两次按钮前后一致，没问题，
不使用form={form}时，因为destroyOnClose，form初始化两次，两次按钮点击使用各自的initialValues。

综合以上，就是预期的。

**Comment by yoyo837** [comment]
> > > > @yoyo837 如果不销毁的Modal中子节点，那么initialValues只有第一次更新是有效，下来就只能使用form.setFieldsValue，而不能说根据state中的改变而改变数据当中的值
> > > 
> > > 
> > > 所以去掉form={form}，两次按钮点击不一样不就和你说的是一致的表现吗？区别在于不去掉form={form}时这个form是useForm提供的，是同一个。
> > 
> > 
> > 对的，可以这么说；如果按照代码来讲的话，意思就是Modal子节点销毁后二次打开这个时候Form组件应该是新的，那么这个时候初始化不应该取initialValues中的值吗？现在情况是没有取initialValues中的值而取了form中的值
> 
> 你觉按照这句话的后半句看，initialValues定义不是表单默认值，只有初始化以及重置时生效吗？Form组件重新从无到有这个过程不算初始化吗？

initialValues是表单的默认值，但默认值不可更改，只在初始化时确定。

**Comment by wenzhu-eternal** [comment]
> 使用form={form}时，form只初始化一次，两次按钮前后一致，没问题， 不使用form={form}时，因为destroyOnClose，form初始化两次，两次按钮点击使用各自的initialValues。
> 
> 综合以上，就是预期的。

那我理解你的意思了，按照这个说发就是存在form时初始化只会进行一次，而不是说Form组件加载就算一次初始化对吧

**Comment by BoyYangzai** [comment]
> 那我理解你的意思了，按照这个说发就是存在form时初始化只会进行一次，而不是说Form组件加载就算一次初始化对吧

是的  初始化也应该事相对于实例而言 而不是Form组件

**Comment by wenzhu-eternal** [comment]
> > 那我理解你的意思了，按照这个说发就是存在form时初始化只会进行一次，而不是说Form组件加载就算一次初始化对吧
> 
> 是的 初始化也应该是相对于实例而言 而不是Form组件

@yoyo837 @BoyYangzai 好的，那我就知道了，感谢你们讲解
