### ISSUE TITLE
Add showZero option to Badge component

### ISSUE THREAD

**Issue by jmatsushita** [ant-design/ant-design#4251]
I would like to be able to show a `0` for my `Badge` component. Right now it's hidden when equal to `0`. I propose to introduce a new boolean prop `showZero` which would show the badge even when count equals 0.

I'm working on a pull request now, let me know if you'd be interested!

**Comment by kvetoslavnovak** [comment]
Good point.

**Comment by kvetoslavnovak** [comment]
PR added

**Comment by afc163** [comment]
@jmatsushita @kvetoslavnovak Didn't find any PR coming?

**Comment by afc163** [comment]
ping~

**Comment by kvetoslavnovak** [comment]
@jmatsushita @afc163  - PR made by jmatsushita did not have test case and was closed https://github.com/ant-design/ant-design/pull/4267

**Comment by benjycui** [comment]
@kvetoslavnovak yep, and you should PR to branch [`feature-2.8`](https://github.com/ant-design/ant-design/tree/feature-2.8) now.
