### ISSUE TITLE
antd cascader 搜索后回显异常

### ISSUE THREAD

**Issue by daydayfish** [ant-design/ant-design#42517]
### Reproduction link

[https://stackblitz.com/edit/react-sfgbj6?file=demo.tsx](https://stackblitz.com/edit/react-sfgbj6?file=demo.tsx)

### Steps to reproduce

1. 搜索"营销"，键盘向下选择，显示value
2.通过一层层点选显示正常

### What is expected?

显示与点击选择保持一致

### What is actually happening?

显示value

| Environment | Info |
| --- | --- |
| antd | 4.18.3 |
| React | 18 |
| System | macos13 |
| Browser | Chrome 113.0.5672.126 |

**Comment by daydayfish** [comment]
<img width="489" alt="image" src="https://github.com/ant-design/ant-design/assets/134256421/ed6797d5-7674-40e0-8fb4-c31dea2fc82c">

**Comment by MadCcc** [comment]
https://stackblitz.com/edit/react-sfgbj6-jrbuqk?file=package.json
4.24.10 正常，升级一下 antd 版本吧
