### ISSUE TITLE
Button icon size and margin issues 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42514]
5.4.x ✅：https://codesandbox.io/s/tu-biao-an-niu-antd-5-4-x-forked-9rx0db?file=/package.json

<img width="222" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/099f3f49-046e-4641-9fc3-de1526e247dc">

5.5.x ❌：https://codesandbox.io/s/tu-biao-an-niu-antd-5-5-0-forked-601t1q?file=/demo.tsx

<img width="190" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/fc826ec3-4268-45e5-b0e5-5886621dccb4">

---

- [ ] 图标右侧边距丢失。
- [ ] Dropdown 右边箭头大小偏大。

业务中也遇到了。

![图片](https://github.com/ant-design/ant-design/assets/507615/b30bb683-fb7a-4531-beaa-56e1e360f4e0)

**Comment by afc163** [comment]
疑似：https://github.com/ant-design/ant-design/pull/41456/ 里改出来的。

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/24635650-648b-4e93-a0ad-25de01dd9070)
这个是不是没有用 icon 属性？

**Comment by afc163** [comment]
对，但是这个一直是遗留的老用法，应该兼容：

```
    <Button type="primary">
      <SearchOutlined />
      <span>按钮</span>
    </Button>
```
