### ISSUE TITLE
Select组件更换自定义suffixIcon后，icon不能响应点击事件打开/关闭选择浮层

### ISSUE THREAD

**Issue by blanky01** [ant-design/ant-design#42515]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/huo-de-xuan-xiang-de-wen-ben-antd-5-5-0-forked-8vktxk?file=/demo.tsx)

### Steps to reproduce

点击select中的切换图标

### What is expected?

点击切换图标能够打开选择列表浮层

### What is actually happening?

点击切换图标不能打开/关闭选择列表浮层

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.0.0 |
| System | mac |
| Browser | chrome |

**Comment by RedJue** [comment]
应该是事件没绑到 `icon` 上，我提个 **pr** 修复一下。

**Comment by afc163** [comment]
It is a conflicted behavior with https://github.com/ant-design/ant-design/issues/23263

**Comment by MadCcc** [comment]
添加 `pointer-events: none` 来穿透 icon

**Comment by zombieJ** [comment]
> It is a conflicted behavior with #23263

suffixIcon 可以加个描述，告诉为什么这么设计。以防万一被当成 bug 修了。
