### ISSUE TITLE
Dropdown glitches when using`trigger={['click']}` and triggering the open state from some other click

### ISSUE THREAD

**Issue by IonelLupu** [ant-design/ant-design#42526]
### Reproduction link

[https://stackblitz.com/edit/react-s4prys?file=demo.tsx](https://stackblitz.com/edit/react-s4prys?file=demo.tsx)

### Steps to reproduce

- add a Dropdown on the page with `trigger={['click']}`
- add a state that tracks the Dropdown's open state
- add a Button that changes the Dropdown's open state to `true`

```ts
import React, { useState } from 'react';
import './index.css';
import { DownOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { Dropdown, Space, Button } from 'antd';

const items: MenuProps['items'] = [
  {
    label: 'Clicking me will not close the menu.',
    key: '1',
  },
  {
    label: 'Clicking me will not close the menu also.',
    key: '2',
  },
  {
    label: 'Clicking me will close the menu.',
    key: '3',
  },
];

const App: React.FC = () => {
  const [open, setOpen] = useState(false);

  return (
    <>
      This one works (with 'trigger={['click']}')
      <br />
      <Button onClick={() => setOpen(true)}>Open dropdwon</Button>
      <Dropdown
        trigger={['click']}
        menu={{
          items,
        }}
        onOpenChange={(flag: boolean) => {
          console.log('open changed', flag);
          setOpen(flag);
        }}
        open={open}
      >
        <a onClick={(e) => e.preventDefault()}>
          <Space>
            Click me
            <DownOutlined />
          </Space>
        </a>
      </Dropdown>
    </>
  );
};

export default App;
```

### What is expected?

The Dropdown with `trigger={['click']}` should not glitch and behave the same as a Dropdown without `trigger={['click']}`

### What is actually happening?

The Dropdown is glitching

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | MacOS Ventura 13.0.1 |
| Browser | 113 |

**Comment by BoyYangzai** [comment]
@IonelLupu 
Hi you can'ts use the  `setOpen` in `onOpenChange` and `setOpen` in Button  at the same time
it makes `open` `false - true -false`

you can use it like: 
https://stackblitz.com/edit/react-s4prys-ea1bfq?file=demo.tsx

**Comment by BoyYangzai** [comment]
@li-jia-nan @zombieJ  cc `usage` label

**Comment by afc163** [comment]
It is a bug.

**Comment by IonelLupu** [comment]
@BoyYangzai @afc163  that works. thank you very much!

Is there a way to get the "click outside dropdown to close the dropdown" feature back?

**Comment by IonelLupu** [comment]
@BoyYangzai @afc163 

Actually, now, the dropdown doesn't close when I click outside of it
