### ISSUE TITLE
ColorPicker能否提供渐变色的选择

### ISSUE THREAD

**Issue by xxi-arch** [ant-design/ant-design#42523]
### What problem does this feature solve?

css 支持渐变色

### What does the proposed API look like?

渐变色选择

**Comment by RedJue** [comment]
不太清楚意图，有可以看的 demo 么？

**Comment by li-jia-nan** [comment]
感觉不太现实，渐变色的话还要提供倾斜角度、渐变尺寸、还有渐变的值个数也不确定，两个颜色还是三个颜色，还是多个颜色，怎么确定呢？

**Comment by 544751779** [comment]
https://tdesign.tencent.com/react/components/color-picker  这个组件实现了

**Comment by RedJue** [comment]
什么场景下用呢？本来渐变色就是组合而成的，感觉让整个颜色选择器过于复杂了。

**Comment by li-jia-nan** [comment]
> https://tdesign.tencent.com/react/components/color-picker 这个组件实现了

这个看起来只实现了两个颜色渐变？如果有三个或者多个呢？

**Comment by 544751779** [comment]
> 什么场景下用呢？本来渐变色就是组合而成的，感觉让整个颜色选择器过于复杂了。

在数据可视化中设置柱状图或者其他颜色，现在基本都是渐变色。现在我们二次封装了一个弹出层表单来配置。
一般情况下，只需要四个方向两个颜色的渐变就够了。

**Comment by 544751779** [comment]
> > https://tdesign.tencent.com/react/components/color-picker 这个组件实现了
> 
> 这个看起来只实现了两个颜色渐变？如果有三个或者多个呢？

他可以点击新增一个颜色，但是一般情况下，只需要两个渐变四个方向就够了。再多的目前没遇到过。

**Comment by li-jia-nan** [comment]
> > > https://tdesign.tencent.com/react/components/color-picker 这个组件实现了
> > 
> > 这个看起来只实现了两个颜色渐变？如果有三个或者多个呢？
> 
>  这个可以增加的

看懂了，是可以新增，有点高级

**Comment by 1123612483** [comment]
> https://tdesign.tencent.com/react/components/color-picker 这个组件实现了

真高级，希望出这个组件，目前我是用n个`ColorPicker`和`InputNumber`去实现的

**Comment by RedJue** [comment]
> > https://tdesign.tencent.com/react/components/color-picker 这个组件实现了
> 
> 
> 
> 真高级，希望出这个组件，目前我是用n个`ColorPicker`和`InputNumber`去实现的

这个确实感觉挺不错的，看看有没有合适的设计方案。

**Comment by xiaopujun** [comment]
好想法，有计划支持嘛?

**Comment by hungtcs** [comment]
看起来最新版 5.20.0 已经支持了
https://ant.design/components/color-picker-cn#color-picker-demo-line-gradient

但是用了一下没有用明白，主要有以下几个问题

1. 渐变色添加多个点以后无法删除，建议点击添加点，再次点击点删除，但是最少保留两个点。或者拖动两个点重合删除，总之能删除点就好了

2. 预设颜色可以支持渐变色预设，但是预设颜色的预览方块没有提现出来渐变。

    <img width="258" alt="image" src="https://github.com/user-attachments/assets/b1255d9c-a43b-495e-93bc-742de11e495c">

**Comment by afc163** [comment]
> 渐变色添加多个点以后无法删除，建议点击添加点，再次点击点删除，但是最少保留两个点。或者拖动两个点重合删除，总之能删除点就好了

https://github.com/ant-design/ant-design/pull/50050#issuecomment-2252115249
