### ISSUE TITLE
select 展开时选项文字有肉眼可见的抖动

### ISSUE THREAD

**Issue by echoyl** [ant-design/ant-design#42539]
### Reproduction link

无

### Steps to reproduce

1.在弹出中使用不会抖动
![drawer](https://github.com/ant-design/ant-design/assets/21699984/82a205db-daab-4ed6-95e6-9aa2349c9cc8)
2.在页面的时候就会抖动
![page](https://github.com/ant-design/ant-design/assets/21699984/67066c21-ceba-4079-abab-31d60676d60c)

3.尝试将版本退回5.4.0还是一样的，再退回到5.2.0后正常了
4.当前使用的版本是 5.5.1

### What is expected?

不要抖动

### What is actually happening?

抖动了

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome版本 113.0.5672.127（正式版本） （64 位） |

**Comment by zombieJ** [comment]
看起来像是屏幕分辨率导致精度问题

**Comment by echoyl** [comment]
> 

再次测试了 在form居中屏幕显示时 出现了left是小数的时候会发生这个情况
将form不居中了 input的屏幕left是整数了 就好了

**Comment by zombieJ** [comment]
嗯，这个组件侧做不了什么。可以给需要用到的地方设置一下 width 固化掉哈~

**Comment by echoyl** [comment]
> 嗯，这个组件侧做不了什么。可以给需要用到的地方设置一下 width 固化掉哈~

关键是5.2.0是好的啊，没有出现小数，应该是后面更新了改到哪了，不修复下吗？
