### ISSUE TITLE
antd 2.5.2 Menu dark主题，二级已选择项的样式不正确

### ISSUE THREAD

**Issue by conzi** [ant-design/ant-design#4253]
#### 发生问题的环境是：

- antd 版本:2.5.2
- 操作系统及其版本: mac osx
- 浏览器及其版本:chrome 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

```
<Menu mode="vertical" theme="dark">
   <SubMenu  title={<span><Icon type="plus" /><span className="nav-text">subitem</span></span>}>
    <Menu.Item>选中状态不正确</Menu.Item>
    <Menu.Item>选中状态不正确</Menu.Item>
   </SubMenu>
</Menu>

```

#### 您期待的结果是:
正常显示高亮

#### 实际上的结果是:
高亮的背景不正确
![示意](http://static.galileo.xiaojukeji.com/static/tms/galileo/bug1214.png)

#### 可重现的在线演示

http://codepen.io/conzi/pen/XNypYK

**Comment by benjycui** [comment]
这个 demo 没问题吧 https://ant.design/components/menu/#components-menu-demo-theme

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by conzi** [comment]
mode="vertical"时有问题：

http://codepen.io/conzi/pen/XNypYK

**Comment by afc163** [comment]
My fault, this problem is introduced at `2.5.2`.
