### ISSUE TITLE
QRCode 可以开放 renderAs 属性吗

### ISSUE THREAD

**Issue by sy296565890** [ant-design/ant-design#42540]
### What problem does this feature solve?

renderAs='svg' 的情况下，可以使用renderToStaticMarkup 或 renderToString将React组件转换为对应的html，而 renderAs='canvas' 的情况下转换出来的却是空白的

### What does the proposed API look like?

期待 QRCode 开放 与value同级的renderAs 属性

**Comment by li-jia-nan** [comment]
`canvas` 也是可以通过 `const url = canvas.toDataURL()` 的方式保存为图片，可以满足需求吗？如果有问题的话可以提供一个复现链接看看

**Comment by zombieJ** [comment]
能说一下需要 svg 的场景是什么么？

**Comment by sy296565890** [comment]
由于使用了低代码平台+在打印可以自定义开发，在生成二维码的时候，由于antd v5 QRCode只支持canvas，而canvas的特性在renderToStaticMarkup 或 renderToString下无法正常使用。
经过尝试【import {QRCodeSVG} from 'qrcode.react';】可以正常显示，既然QRCode使用的也是qrcode.react  就没必要单独再引入qrcode.react了，故有此请求，效果图如下
![image](https://github.com/ant-design/ant-design/assets/85245446/ea680a31-32a7-40ca-8e1c-bf3a9fd3a841)
