### ISSUE TITLE
2.4.2+版本使用webpack构建时的错误

### ISSUE THREAD

**Issue by huzion** [ant-design/ant-design#4254]
#### 发生问题的环境是：

- antd 版本: ^2.4.2
- 操作系统及其版本: win7 x64
- 浏览器及其版本: chrome 55

#### 您做了什么？请提供尽可能详细的重现步骤。

1、在项目中安装antd，  npm i antd --save-dev
2、建立corelibs.js核心库文件，代码：

```
import Antd from 'antd';
import 'antd/dist/antd.less';
window.Antd = Antd;
```

3、然后使用webpack构建，无压缩混淆，纯构建

#### 您期待的结果是:

像官网一样正常显示

#### 实际上的结果是:

window.Antd 未定义，使用antd组件失败
同样的项目，同样的环境，同样的配置，换2.0.1版本则无任何问题

**Comment by huzion** [comment]
补充：
webpack@1.13.2
webpack-core@0.6.8
webpack-sources@0.1.2

**Comment by benjycui** [comment]
Try https://github.com/ant-design/ant-design/issues/3204#issuecomment-250358747

**Comment by huzion** [comment]
不是，主要不是`Cannot resolve 'file' or 'directory' ./locale` 的问题，这个不影响。
主要是最新版 `antd@2.4.2`、`antd@2.5.2`构建后出未定义的问题

**Comment by benjycui** [comment]
不懂你的意思，麻烦提供可重现 demo

**Comment by afc163** [comment]
需要可重现的 repo

**Comment by afc163** [comment]
@huzion

**Comment by yesmeck** [comment]
antd 没有 default export，如果要把 antd 暴露到全局话要这样：

```javascript
import * as Antd from 'antd';
window.Antd = Antd;
```
