### ISSUE TITLE
Tooltip arrow not having the correct default style

### ISSUE THREAD

**Issue by georgeat8** [ant-design/ant-design#42546]
### Reproduction link

[https://ant.design/](https://ant.design/)

### Steps to reproduce

Using any Tooltip in the application

### What is expected?

Tooltip arrow is properly rendered, with a pointy tip (just like in v4)

![image](https://github.com/ant-design/ant-design/assets/62032417/195437b6-4dbb-4a20-b052-b985297c5ba0)

### What is actually happening?

Arrow looks like a rectangle/square and the CSS seems to be broken

![image](https://github.com/ant-design/ant-design/assets/62032417/8218f393-0872-4806-ad0c-5894064ebe4a)
![image](https://github.com/ant-design/ant-design/assets/62032417/563b1c05-9425-4d0c-9a4d-0dc23733bd99)
![image](https://github.com/ant-design/ant-design/assets/62032417/f6f15a2c-6a20-4cac-8f81-5e7d3cdd2be1)

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 17.0.2 |
| System | macOS Ventura 13.3.1 |
| Browser | Chrome Version 113.0.5672.63 |

---
I encountered this bug while working to update the application from v4 -> v5

**Comment by MadCcc** [comment]
Maybe you are using `borderRadius` as `4px`? Please try to use number `4` as value, `borderRadius` only accept number type.

**Comment by andreidb** [comment]
> Maybe you are using `borderRadius` as `4px`? Please try to use number `4` as value, `borderRadius` only accept number type.

@MadCcc you're a life saver! Thank you! 💯

**Comment by li-jia-nan** [comment]
> Maybe you are using `borderRadius` as `4px`? Please try to use number `4` as value, `borderRadius` only accept number type.

感觉这里可以判断一下，如果不是 number 类型，报个 error 给用户？

**Comment by afc163** [comment]
+1

帮用户转一下也不是不行。

**Comment by shamseer-ahammed** [comment]
+1
