### ISSUE TITLE
Spin does not allow for tip without children

### ISSUE THREAD

**Issue by alex20044** [ant-design/ant-design#42548]
### Reproduction link

[https://ant.design/components/spin#components-spin-demo-basic](https://ant.design/components/spin#components-spin-demo-basic)

### Steps to reproduce

<Spin  tip='Loading...' />

### What is expected?

Tip should still be shown even without children as it was working  2 versions ago

### What is actually happening?

Tip is not being displayed

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
It's a bug before. `tip` always only work when `children` is using in doc:

<img width="845" alt="截屏2023-05-23 17 29 52" src="https://github.com/ant-design/ant-design/assets/5378891/5707fb13-5a4c-4fe0-869d-69cba37a388b">


ref: https://github.com/ant-design/ant-design/pull/42293
