### ISSUE TITLE
tree异步请求

### ISSUE THREAD

**Issue by zhangfengrui** [ant-design/ant-design#4255]
- antd 版本: 2.4.4
- 操作系统及其版本: mac
- 浏览器及其版本:chrome 55

当异步请求树节点时的样子是这样的， 这个树组件是放在modal里的
![image](http://img.blog.csdn.net/20161215111850251?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdGVybWludXNSZWFjdA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

当再一次进入modal时的样子是这个样子
![image](http://img.blog.csdn.net/20161215111649077?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdGVybWludXNSZWFjdA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

希望再一次进入的样子是
![image](http://img.blog.csdn.net/20161215112107933?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdGVybWludXNSZWFjdA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

每次在此进入的时候左侧图标都是异步请求后的状态，需要点两次才能继续发请求，请问这种状态是不是antdesign做了缓存

**Comment by afc163** [comment]
Modal 是 react 组件，不会每次显示都销毁和重新渲染，进入前需要手动清空之前的状态。

**Comment by zhangfengrui** [comment]
我已经清除了modal的状态，tree组件是我自己写的，用form包裹的，我也做了resetFields的处理，可是还会出现那种情况

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zhangfengrui** [comment]
你把我提的给关掉了。。。

**Comment by zhangfengrui** [comment]
你好，这个问题是我这边没处理好呢，还是antdesign的tree将这个状态做了缓存呢

**Comment by afc163** [comment]
你要给我们重现，我们才能确定。

**Comment by zhangfengrui** [comment]
这个牵扯了好多东西，不好重现呢，按图中所显示的不好解决么，我总感觉有个状态控制着，但没找到，

**Comment by afc163** [comment]
一般来说，维护人员开始要重现，意味着我们在本地无法重现你说的问题。

如果你没有办法提供重现，意味着维护者要嘛只能无视，要嘛只能猜测问题所在。我现在猜测是 https://github.com/ant-design/ant-design/issues/4255#issuecomment-267230924 这里的原因。

**Comment by afc163** [comment]
我还是建议你用 Tree 的 expandedKeys 属性精确控制所有的展开项，在对话框打开的时候清空它。

---

或者你希望 Modal 每次打开，里面都是初始化状态的话。

给 Modal 设置一个 key，每次显示时给它一个一个新的 key，这样每次打开的就是新的对话框了。

**Comment by zhangfengrui** [comment]
可以的，可以的，expandedKeys 试过了，这个方法不行，给modal加key这个刚刚试过了，每次都是一个新的modal，使用这个问题已经解决了，又学了一项神技能，万分感谢

**Comment by afc163** [comment]
expandedKeys 肯定也是可以的。

**Comment by zhangfengrui** [comment]
恩恩，我再试试
