### ISSUE TITLE
Error open with disabled RangePicker

### ISSUE THREAD

**Issue by BoyYangzai** [ant-design/ant-design#42552]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jin-yong-antd-5-5-1-forked-luz8f8?file=/demo.tsx)

### Steps to reproduce
如上 demo
![image](https://github.com/ant-design/ant-design/assets/94534613/68d66145-3267-44bd-9efc-6bf6e229da88)

### What is expected?

可以打开，但不能操作

### What is actually happening?

打开且可以选择

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | * |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
> 我感觉预期应该是允许打开, 但是面板不可以选择.

+1，还有个自定义渲染的接口，可能是有打开需求的
