### ISSUE TITLE
Spin in a Badge component rotates too fast

### ISSUE THREAD

**Issue by robin-lc** [ant-design/ant-design#42558]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-roentgen-hogv1u)

### Steps to reproduce

Use a Spin in a Badge component with "count" property.

### What is expected?

Spin component should rotate at a lower speed, as expected in the doc: https://ant.design/components/spin

### What is actually happening?

Spin component rotates very fast.

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | Windows 11 / Ubuntu at least |
| Browser | Chrome / Brave |

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/fb6b0bfb-671b-4e7f-8196-1aa9db33054d)
Animation of spin was overrided. Looks okay when removed.
