### ISSUE TITLE
在使用Tabs组件时出现错误

### ISSUE THREAD

**Issue by Bluecook** [ant-design/ant-design#42556]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-y4cifi?file=/index.js)

### Steps to reproduce

当tabs的宽度太小,鼠标hover省略号时,下拉多出现了一个Tab 2

### What is expected?

鼠标hover省略号时,下拉有,Tab 1,Tab 2,Tab 3

### What is actually happening?

鼠标hover省略号时,下拉有,Tab 1,Tab 2,Tab2,Tab 3,多出现了一个Tab2

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2 |
| System | win1 |
| Browser | Chrome/112.0.0.0 |

**Comment by zombieJ** [comment]
牛了，这都能发现。 。 。

**Comment by yuteng-long** [comment]
最近也发现了这个bug，现在有方案可以解决吗？

**Comment by afc163** [comment]
@yuteng-long 预期是已经修复，如果还有问题，请提供可重现的在线链接。

**Comment by Bluecook** [comment]
![image](https://github.com/ant-design/ant-design/assets/79462785/f8cbd8b1-7252-41b0-8d3b-037635dded63)
好像没有修复好，预期应该是下拉出现的效果Tab1、Tab2、Tab3的
在线链接：https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-y4cifi?file=%2Fpackage.json%3A6%2C24

**Comment by Bluecook** [comment]
> @yuteng-long 预期是已经修复，如果还有问题，请提供可重现的在线链接。

https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-y4cifi?file=%2Fpackage.json%3A6%2C24
