### ISSUE TITLE
设计文档还有许多展示问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42569]
- [x] 文档链接 404 https://github.com/ant-design/ant-design/pull/42568
- [x] 贡献者 list 跑到上面来了 https://github.com/ant-design/ant-design/pull/42568
- [x] [表单页](https://ant.design/docs/spec/research-form-cn#%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99) 三个设计原则这里没横排（对比 [4.x 文档](https://4x.ant.design/docs/spec/research-form-cn)）
  - [x] https://ant.design/docs/spec/research-empty-cn#%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99 这里也是。 @kiner-tang https://github.com/ant-design/ant-design/pull/42954
  - [x] https://ant.design/docs/spec/research-navigation-cn 这里也是。@kiner-tang https://github.com/ant-design/ant-design/pull/42954
  - [x] https://ant.design/docs/spec/visualization-page-cn 这里也是。@kiner-tang https://github.com/ant-design/ant-design/pull/42954
  - [x] https://ant.design/docs/spec/detail-page-cn 这里也是。 @kiner-tang https://github.com/ant-design/ant-design/pull/42954
- [x] [巧用过渡](https://ant.design/docs/spec/transition-cn) 这里页面内容丢失。（对比 [4.x 文档](https://4x.ant.design/docs/spec/transition-cn)）https://github.com/ant-design/ant-design/pull/43273/
- [x] 这个表单页感觉是多余的 https://ant.design/docs/spec/form-page-cn ，可以删掉 ， https://ant.design/docs/spec/research-form-cn 内容更完整。
- [x] 内容和图没有左右横排。
  - [x] https://ant.design/docs/spec/lightweight-cn https://github.com/ant-design/ant-design/pull/42952
  - [x] https://ant.design/docs/spec/data-format-cn#%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD #42951
  - [x]  https://ant.design/docs/spec/feedback-cn#%E7%BB%93%E6%9E%9C%E5%8F%8D%E9%A6%88 @kiner-tang #42956
- [x] 加粗文案失效，** 后面要加个空格。https://ant.design/docs/spec/data-format-cn https://github.com/ant-design/ant-design/pull/42744

**Comment by afc163** [comment]
先列一部分。

**Comment by kiner-tang** [comment]
@afc163 加粗文案失效，** 后面要加个空格。 这个没看到哪个有问题呀？该加粗的看起来都是有加粗的
<img width="469" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/1463f6df-5c3e-4473-b4f8-f5670efb8439">
