### ISSUE TITLE
DatePicker[picker="halfyear"] RangePicker picker="halfyear"

### ISSUE THREAD

**Issue by toddywang** [ant-design/ant-design#42566]
### What problem does this feature solve?

是否可以选择H1、H2模式。

### What does the proposed API look like?

<RangePicker picker="halfyear" />
<DatePicker picker="halfyear" />

**Comment by toddywang** [comment]
<RangePicker picker="halfyear" /> <DatePicker picker="halfyear" />

**Comment by toddywang** [comment]
RangePicker picker="halfyear" 
DatePicker picker="halfyear"

**Comment by afc163** [comment]
Duplicate of #42565
