### ISSUE TITLE
"size" property for ColorPicker

### ISSUE THREAD

**Issue by omidabd** [ant-design/ant-design#42573]
### What problem does this feature solve?

Since ColorPicker is generally used as an input component, it sounds reasonable to have "Size" property like other components

### What does the proposed API look like?

<ColorPicker size="small"/>

**Comment by RedJue** [comment]
Will released on the next minor ~

**Comment by gitstart** [comment]
@MadCcc @omidabd I would like to pick this up

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/43116
