### ISSUE TITLE
Sidebar goes under layout during reload

### ISSUE THREAD

**Issue by CBiglemon** [ant-design/ant-design#42576]
### Reproduction link

[https://stackblitz.com/edit/react-abazwu?file=demo.tsx](https://stackblitz.com/edit/react-abazwu?file=demo.tsx)

### Steps to reproduce

- Set page with layout, sider, header, content and footer

- Get on the page

- Reload the page

### What is expected?

It is expected that the page loads normally without any visual bugs.

### What is actually happening?

The page flickers for a very brief moment, the header seems to go under the footer for less than a second before getting to its normal position.

In addition, [here's a link](https://imgur.com/i4YTI1D) to a GIF showing the bug as described above.

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | macOS 13.1 |
| Browser | Google Chrome : Version 113.0.5672.126 (Official Build) (arm64)  |

**Comment by linxianxi** [comment]
you can set `hasSider` in Layout

**Comment by Tuhama** [comment]
I'm facing the same issue, but it doesn't seem to show when using (react-scripts v4 + react 17)

**Comment by nisharga** [comment]
I am also facing the same issue with Nextjs 14.
