### ISSUE TITLE
Check.Group style broken in Form demo

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42586]
<img width="433" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/659f01a0-1b3c-4061-8918-03bf9e1caf4b">

https://ant.design/components/form-cn#components-form-demo-validate-other

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/36fd8376-c425-4f1d-993c-f59a15fd5b5e)
