### ISSUE TITLE
主题定制里面 package.theme里使用自定义的 @icon-url 没有效果？

### ISSUE THREAD

**Issue by zachshelter** [ant-design/ant-design#4259]
antd 2.5.2
atool-build 0.9.3

如题， 设置了 @icon-url 属性之后还是从 alicdn 的那个网址获取iconfont

如果使用文档里 icon 的那个部署本地的教程方法去做， 实在太卡了

非常感谢

**Comment by afc163** [comment]
https://github.com/visvadw/dvajs-user-dashboard/pull/2

**Comment by yangchongduo** [comment]
"@icon-url": "'/src/static/iconfont/iconfont'"
这样引入  不往 cdn发送请求了 但是现在 iocn 没有显示 都是 小正方形

**Comment by yangchongduo** [comment]
现在统一 回复一下 问题  开发环境下是 一定要加 localhost// iconfont完整的路径
生产环境下 相对路径  这样的isuess  才好

**Comment by wangyun1517** [comment]
https://github.com/ant-design/antd-init/issues/156

**Comment by dada094551** [comment]
各位大神，我把iconfont图标放在了 antd/lib/style/core 文件夹下  
然后再defalut.less 里 重新定义了变量 @icon-url               : "./iconfont/iconfont";
运行时会报错
./node_modules/antd/lib/style/core/iconfont/iconfont.svg
Module build failed: ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding
plugin

这个问题怎么解决呢？
谢谢各位
