### ISSUE TITLE
Modal.confirm设置getContainer:false 点击弹窗不显示

### ISSUE THREAD

**Issue by git997-small** [ant-design/ant-design#42595]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5x05d7?file=/index.js)

### Steps to reproduce

点击comfrim按钮

### What is expected?

能弹窗内容

### What is actually happening?

能弹窗内容

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 17 |
| System | windows |
| Browser | chrome 101 |

---
s

**Comment by zombieJ** [comment]
静态方法没有上下文，不能设置 `false`。这个应该warning 出来给用户。

**Comment by git997-small** [comment]
老师你好,那为什么可以设置成document.body就生效呢

**Comment by zombieJ** [comment]
因为 body 是明确的元素，false 是当前上下文环境，静态方法没有上下文环境。
