### ISSUE TITLE
table组件同时使用sticky、scroll、expandable时， 内表格的sticky失效

### ISSUE THREAD

**Issue by DrMuda** [ant-design/ant-design#42600]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fast-butterfly-zt4q0v?file=/src/App.tsx)

### Steps to reproduce

展开内表格之后， 滚动表格即可

### What is expected?

滚动表格后， 外面的表头吸顶最上面， 里面的表头吸顶在外面表头的下方， 效果和移除 scroll 属性后的一样

### What is actually happening?

里面的表头没有吸附效果， 直接跟随内表格一起滚动了

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | macOs Ventura 13.3.1 (a) (22E772610a) |
| Browser | edge: 112.0.1722.46; chrome: 113.0.5672.126 |

---
sticky、scroll.x、expandable三个属性均是必要的。 y轴滚动时， 内外表头都吸顶； x轴 宽度可能比较小， 要有scroll.x属性来保持布局； expandable 内表格也是必须要有的

**Comment by afc163** [comment]
https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/

> 父级元素不能有任何overflow:visible以外的overflow设置，否则没有粘滞效果。因为改变了滚动容器（即使没有出现滚动条）。因此，如果你的position:sticky无效，看看是不是某一个祖先元素设置了overflow:hidden，移除之即可。

很遗憾，上层加了 scroll 后就有 overflow 了。

**Comment by DrMuda** [comment]
> https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/
> 
> > 父级元素不能有任何overflow:visible以外的overflow设置，否则没有粘滞效果。因为改变了滚动容器（即使没有出现滚动条）。因此，如果你的position:sticky无效，看看是不是某一个祖先元素设置了overflow:hidden，移除之即可。
> 
> 很遗憾，上层加了 scroll 后就有 overflow 了。

我清楚这个， 所以我尝试了从内表格的thead开始遍历所有的祖先节点， 凡是overflow 不为 visible 都设置为visible， 确实可以了， 但是scroll属性 加上的 overflow: auto hidden 也被干掉了， 横线滚动失效

所以实在是没有方法同时兼容这两个吗？

**Comment by afc163** [comment]
原生 sticky 属性就是这个特性，目前的实现确实鱼和熊掌不可兼得。

**Comment by DrMuda** [comment]
> 原生 sticky 属性就是这个特性，目前的实现确实鱼和熊掌不可兼得。

好吧
