### ISSUE TITLE
[InputNumber] :`placeholder` is existence, but docs not included，and TypeScript of question.

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#42609]
### Reproduction link

[https://stackblitz.com/edit/react-rccas5?file=demo.tsx](https://stackblitz.com/edit/react-rccas5?file=demo.tsx)

### Steps to reproduce

NA

### What is expected?

The `ts` type is correct.

### What is actually happening?
Wrong `ts` type, 'placeholder' does not exist
![image](https://github.com/ant-design/ant-design/assets/81673017/997c35f1-331a-490d-9a18-85d655c150c2)

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome  108.0.5359.125 |

**Comment by kiner-tang** [comment]
你可以试试看这里是否能够正常提示：https://codesandbox.io/s/qian-zhi-hou-zhi-biao-qian-antd-5-5-1-forked-t64khp
![image](https://github.com/ant-design/ant-design/assets/10286961/4d966e33-2ec5-4d13-89af-70c552fcadcf)

**Comment by RSS1102** [comment]
抱歉是我的问题，首先肯定的是在`INputNumber`上是存在`placeholder`这个属性的(不过文档好像未说明）.

---

我在`Select`使用`placeholder`：
![image](https://github.com/ant-design/ant-design/assets/81673017/01659f13-d5fb-4a0d-acaf-d7e96ab51859)
![image](https://github.com/ant-design/ant-design/assets/81673017/b3ab2014-a7eb-4cd3-88fa-7f25aaa78b7b)

--

而在`INputNumber`上使用`placeholder`：
![image](https://github.com/ant-design/ant-design/assets/81673017/e78d73cf-e0ad-4a60-9698-c218985b461b)
![image](https://github.com/ant-design/ant-design/assets/81673017/a86fed8b-c14a-4c97-a410-b5fe0c5618de)

这里是否应该统一呢？至少我在i18n下是应该会得到一个正确的预期。

**Comment by zombieJ** [comment]
InputNumber 是传给原生的 Input，Select 是自己实现的，所以后者能力会更强一些。

**Comment by RSS1102** [comment]
> InputNumber是传给原始的Input，Select是自己现实的，所以后期者能力会更强一些。

ok，希望能保持一致（接受的内容包容性更强一点）。

**Comment by afc163** [comment]
国际化的库一般都会提供返回 string 类型的 API 的，你可以试试。
