### ISSUE TITLE
DOM Events don't work on the Drawer component

### ISSUE THREAD

**Issue by robin-lc** [ant-design/ant-design#42615]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-dew-y8ug15)

### Steps to reproduce

Use a Drawer with DOM Events like **onMouseEnter** or **onClick**

### What is expected?

DOM Events should be triggered

### What is actually happening?

They are not

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | Windows 11 / Ubuntu at least |
| Browser | Chrome / Brave |

**Comment by kiner-tang** [comment]
Could you please provide the specific application scenario  about it?

**Comment by kiner-tang** [comment]
Could you please provide the specific application scenario  about it?

**Comment by robin-lc** [comment]
In v4.x, we used it to select elements before sending an email like this:

![drawer](https://github.com/ant-design/ant-design/assets/33860138/df748a82-a573-4995-a1d1-8e0e588c7aa8)
