### ISSUE TITLE
Dropdown配合Modal使用，如果通过Dropdown内部的item触发Modal展示会导致Dropdown的onOpenChange无法捕捉到关闭事件

### ISSUE THREAD

**Issue by rurounibatousai** [ant-design/ant-design#42610]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-5-1-forked-95wvt0?file=/demo.tsx)

### Steps to reproduce

点击hover me然后选择第一个item打开Modal会发现Dropdown关闭了，但是没有触发onOpenChange

### What is expected?

打开Modal的同时能够触发Dropdown的onOpenChange事件

### What is actually happening?

没有触发Dropdown的onOpenChange事件

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | ^18.0.0 |
| System | Windows 10 |
| Browser | Chrome 113.0.5672.127 |

**Comment by zombieJ** [comment]
听起来这个和 Modal 似乎没关系？就是 Dropdown 事件不全是吗？

**Comment by rurounibatousai** [comment]
> 听起来这个和 Modal 似乎没关系？就是 Dropdown 事件不全是吗？

应该是的，我说的只是表象，麻烦看一下哇~

**Comment by zombieJ** [comment]
发现修了是 break change，这个修不了了：
https://github.com/ant-design/ant-design/pull/42655#issuecomment-1564128748
