### ISSUE TITLE
Calendar 不支持 value 和 defaultValue

### ISSUE THREAD

**Issue by sunzhilei** [ant-design/ant-design#4261]
#### 发生问题的环境是：
- antd 版本:  2.5.0
- 操作系统及其版本:  windows 10 企业服务版
- 浏览器及其版本:  Chrome 54.0.2840.99

#### 您做了什么？请提供尽可能详细的重现步骤。

Calendar组件的value和defaultValue无效，官方文档中的Demo也使用了defaultValue，同样是无效的，只不过我本地的始终选择了当天的日期，
代码如下：
<Calendar defaultValue={moment('2010-10-10', 'YYYY-MM-DD')}/>

#### 您期待的结果是:

希望能支持value和defaultValue

#### 实际上的结果是:

可以通过value属性改变某天的选择状态

**Comment by benjycui** [comment]
defaultValue works https://ant.design/components/calendar/#components-calendar-demo-custom-render

**Comment by yesmeck** [comment]
希望能在标题里简单描述下问题，方便别人搜索。

**Comment by gidich** [comment]
Perhaps the following might work:

```
<Calendar defaultValue={moment('2010-10-10', 'YYYY-MM-DD').value}/>
```

**Comment by afc163** [comment]
@benjycui The current day of this demo is `now` instead of `2010-10-10`, so there is a problem in `defaultValue`.

**Comment by benjycui** [comment]
I see..

**Comment by sunzhilei** [comment]
value and defaultValue is set calendar current display date, Not set default selected date, think you everybody!
