### ISSUE TITLE
Is it possible to give tailwind classnames to antd auto generated divs. Eg: <Space>'s auto generated child div 'ant-space-item'

### ISSUE THREAD

**Issue by LizaMaharjan2001** [ant-design/ant-design#42618]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-tailwind-forked-1b9nhr?file=/pages/index.js)

### Steps to reproduce

- Navigate to pages > index.js from sidebar
- View the generated output on right side browser
- Can inspect code and check where the 'flex-grow' class is being inserted (needed in the same div's classname where ant-space-item is added

### What is expected?

- I want the 'flex-grow' tailwind class name to be added in the ant-space-item instead of the ant-space-item's child div.

### What is actually happening?

- 'flex-grow' tailwind class name is being added to the child div of the ant-space-item.

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

---
This is just an example of how im not being able to add classnames to the direct children that is auto generated by the ant components. Is there steps or tutorials for how we can access and give classnames to each of the components. eg: Item of the form can be accessed by <Form.Item.. and so on.

**Comment by MadCcc** [comment]
We would provide `classNames` and `styles` for Space.

```
<Space classNames={{ item: 'custom-item' }}>...</Space>
```

**Comment by RedJue** [comment]
Mark

**Comment by LizaMaharjan2001** [comment]
> classNames

I'm using css-in-js and emotion here on my code. is there a way to pass the classname using just the className?

**Comment by MadCcc** [comment]
> > classNames
> 
> I'm using css-in-js and emotion here on my code. is there a way to pass the classname using just the className and not 'classNames'?

Then you have to override with item class `ant-space-item`

**Comment by LizaMaharjan2001** [comment]
> > > classNames
> > 
> > 
> > I'm using css-in-js and emotion here on my code. is there a way to pass the classname using just the className and not 'classNames'?
> 
> Then you have to override with item class `ant-space-item`

How? can you provide me an example. You can edit on my codesandbox provided above.

**Comment by MadCcc** [comment]
Actually there's no way to pass `className` to Space item through `className`.
But you could override styles of items with `className` of Space.
https://codesandbox.io/p/sandbox/antd-tailwind-forked-lcz9bs?welcome=true

**Comment by LizaMaharjan2001** [comment]
> Actually there's no way to pass `className` to Space item through `className`. But you could override styles of items with `className` of Space. https://codesandbox.io/p/sandbox/antd-tailwind-forked-lcz9bs?welcome=true

Hence, this feature should be added right? To be able to pass classname to the direct auto generated classes of antd components. This feature could be great help for those using **tailwind**.
