### ISSUE TITLE
增加antd5关闭聚焦样式(无障碍能力Accessibility)的配置项

### ISSUE THREAD

**Issue by ye-admin** [ant-design/ant-design#42614]
### What problem does this feature solve?

解决了客户提出的要求

### What does the proposed API look like?

能给一个全局的或者组件级别的开启/关闭聚焦样式的配置项

**Comment by MadCcc** [comment]
试试把 `lineWidthFocus` 设为 0。
```jsx
<ConfigProvider theme={{ token: { lineWidthFocus: 0 }}}>
 {...}
</ConfigProvider>
```

**Comment by ye-admin** [comment]
> 试试把`lineWidthFocus`设置为0。
> 
> ```js
> <ConfigProvider theme={{ token: { lineWidthFocus: 0 }}}>
>  {...}
> </ConfigProvider>
> ```

有效谢谢
