### ISSUE TITLE
No 'color' prop to set Tag's color when using Select with tagRender

### ISSUE THREAD

**Issue by Yugle** [ant-design/ant-design#42613]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7b65xy?file=/index.tsx)

### Steps to reproduce

1. Set the options of Select
2. Set the tagRender for customize the tags to display
3. Can not to set the color of tags not by the 'value' props

### What is expected?

I want to set tag's color but not by the 'value' or 'label' prop

### What is actually happening?

Can not to set the color of tags not by the 'value' props

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.1.0 |
| System | WSL Ubuntu 22.04LTS |
| Browser | Edge |

**Comment by kiner-tang** [comment]
I can not understand what you want. Why are you set the color by value which typeof number?

**Comment by kiner-tang** [comment]
Maybe you can customize like this:
- https://codesandbox.io/s/antd-reproduction-template-forked-7b65xy?file=/index.tsx
<img width="1144" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/eaa7e9bd-80cd-450b-953b-8b289a9c08c8">

**Comment by afc163** [comment]
@kiner-tang Could you provide the fork codesandbox link?

**Comment by afc163** [comment]
@Yugle Please check @kiner-tang 's codesandbox.

**Comment by Yugle** [comment]
> I can not understand what you want. Why are you set the color by value which typeof number?

I want to set Select's options and these options have different lables, value and colors. And thanks.
