### ISSUE TITLE
使用antd.js表单的样式错乱

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#4262]
#### 发生问题的环境是：

- antd 版本: 1.11.1
- 操作系统及其版本: 
- 浏览器及其版本: chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

引入表单控件

#### 您期待的结果是:

正常展示

#### 实际上的结果是:

样式错乱，label没有右对齐，如图所示
![image](https://cloud.githubusercontent.com/assets/19485727/21216634/d09a7fc8-c2e2-11e6-812b-a2a216731244.png)

**Comment by infeng** [comment]
烦请提供一个可重现的演示，http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by aw6658913** [comment]
在线演示使用跟引入全局antd.js使用组建是不一样的，我写个简单的demo
`
var Form = antd.Form;
var Input = antd.Input;
const createForm = Form.create;
const FormItem = Form.Item;
const demo = {
  formulaSet: React.createClass({
          render(){
             const { getFieldDecorator } = this.props.form;
             const formulaNameV = getFieldDecorator('formulaName', {
                rules: [
                    { required:true, message: '请输入公式名称' },
                ],
              });
             return (
                <Form horizontal>
                        <FormItem
                            label="公式名称"
                            labelCol={{ span: 4 }}
                            wrapperCol={{ span: 10 }}>
                            <Input {...formulaNameV} placeholder="请输入"/>
                        </FormItem>
               </Form>
            )
        }
   })
}
dmeo.formulaSet = createForm()(demo.formulaSet);
`
这样子会发现“公式名称”并没有像这样
![image](https://cloud.githubusercontent.com/assets/19485727/21219310/381e4a42-c2ef-11e6-8965-b6e906a3334e.png)
跟输入框紧挨着，而是如我提问截图的那样是靠左的

**Comment by afc163** [comment]
你来提问也有半年了吧。。。为啥不学习一下 markdown：https://segmentfault.com/markdown

**Comment by aw6658913** [comment]
@afc163 抱歉我已经尽量把问题描述清楚了，只是有的格式确实不知道怎么弄的，提问描述一多就显得乱，所以我尽量缩短内容提供在线演示，给您带来不便实在是抱歉

**Comment by afc163** [comment]
看下文档学习一下，很简单的：https://segmentfault.com/markdown 💯

**Comment by aw6658913** [comment]
const { Form, Input } = antd;
const createForm = Form.create;
const FormItem = Form.Item;

const demo = {
formulaSet: React.createClass({
          render(){
             const { getFieldDecorator } = this.props.form;
             const formulaNameV = getFieldDecorator('formulaName', {
                rules: [
                    { required:true, message: '请输入公式名称' },
                ],
              });
             return (
                <Form horizontal>
                        <FormItem
                            label="公式名称"
                            labelCol={{ span: 4 }}
                            wrapperCol={{ span: 10 }}>
                            <Input {...formulaNameV} placeholder="请输入"/>
                        </FormItem>
               </Form>
            )
        }
})
}
demo.formulaSet = createForm()(demo.formulaSet);
ReactDOM.render(<demo.formulaSet />, document.getElementById('container'));

**Comment by afc163** [comment]
重现了再 reopen 吧，我们的官方演示都是好的。
