### ISSUE TITLE
Unpredictable behaviour of a draggable track slider

### ISSUE THREAD

**Issue by miloszmaki** [ant-design/ant-design#42628]
### Reproduction link

https://codesandbox.io/s/antd-reproduction-template-forked-6n0wd2

### Steps to reproduce

Try to click and drag the selected interval a couple of times. 

### What is expected?

There should be some fixed maximum distance (could be a percentage of the selected interval or an absolute value in pixels) which controls whether the endpoint should be moved or the entire interval should be dragged.

### What is actually happening?

You will notice that sometimes it's draggable and sometimes one of the end positions moves onto where you clicked.

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | Ubuntu 23.04 |
| Browser | Mozilla Firefox 113 |

**Comment by miloszmaki** [comment]
Sure, I updated the issue with a new reproduction link: https://codesandbox.io/s/antd-reproduction-template-forked-6n0wd2

**Comment by miloszmaki** [comment]
It seems this is actually a problem with the underlying "rc-slider"
https://codesandbox.io/s/antd-reproduction-template-forked-izgbr4

**Comment by BoyYangzai** [comment]
@miloszmaki 
done 😄
rc-slider pr https://github.com/react-component/slider/pull/908
antd pr https://github.com/ant-design/ant-design/pull/42665
