### ISSUE TITLE
在组件 token 文档处提供使用方式

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42622]
![图片](https://github.com/ant-design/ant-design/assets/507615/b090895c-9d98-4969-98db-63b34e6eb66a)

https://ant.design/components/button-cn#design-token 这里要提供用法指引。不然确实看得到token，不知道咋用。

可以放一个 `如何使用？`，hover 上去是一个 Popover。

Popover 内放一段代码示例，演示下面的 token 写在哪里。

```jsx
<ConfigProvider theme={{ }}>
</ConfigProvider>
```

另外再附上 https://ant.design/docs/react/customize-theme-cn 的链接。

**Comment by kiner-tang** [comment]
m
