### ISSUE TITLE
级联选择器动态加载数据的loading无法控制

### ISSUE THREAD

**Issue by haiNono** [ant-design/ant-design#42620]
### Reproduction link

[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce

官网的动态加载选项的示例中，删除targetOption.loading = true;和targetOption.loading = false;两句，甚至只在第一句的位置写上targetOption.loading = false;结果两种情况选择器中的loading都是存在的。

### What is expected?

期望能够通过targetOption.loading = false;控制loading效果消失

### What is actually happening?

实际上targetOption.loading对loading效果的显示和隐藏没有任何关联，是个虚假的控制字段
![动画](https://github.com/ant-design/ant-design/assets/134601929/e2028d3e-0ab1-42bf-9ef0-bb61b774c91b)

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | react |
| System | windows10 |
| Browser | chrome 113.0.5672.127（正式版本） （64 位） |

---
场景为项目中有一个bug，级联选择器到了最后一层之后，点击该选项让他发请求，loading会一直转个不停，使用loading字段无法控制其消失。5.x和4.x中都有该bug，其余版本未测试

**Comment by RedJue** [comment]
给个复现的demo吧

**Comment by zombieJ** [comment]
发现这是 3x 的特性：
https://codesandbox.io/s/flamboyant-jackson-tbc11f?file=/index.js:601-608

4x 里就没有了：
https://codesandbox.io/s/dong-tai-jia-zai-xuan-xiang-antd-4-24-10-forked-hcbnon

文档里需要清理一下。
