### ISSUE TITLE
自定义Select Option时获取Option相关状态

### ISSUE THREAD

**Issue by chongqiangchen** [ant-design/ant-design#42636]
### What problem does this feature solve?

在项目内要求多选下拉选中的样式保持类似checkbox list，而不是现有的高亮选中区域右侧打钩的展示方式，对于这样的场景我期望可以自定义这个Option，但是我发现在自定义的时候我只能变动到Option展示的部分，但是selected状态我无法控制，除非将整个value自己去控制绑定每个option内的checkbox。

### What does the proposed API look like?

所以我想询问下是否可以类似下面这样可以捕获到当前选项的相关状态：
```
<Option>{(selected) => <Checkbox checked={selected}></Checkbox>}</Option>
```

**Comment by afc163** [comment]
> 除非将整个value自己去控制绑定每个option内的checkbox。

这是正确的方式，我们建议这么做。

**Comment by chongqiangchen** [comment]
> > 除非将整个value自己去控制绑定每个option内的checkbox。
> 
> 这是正确的方式，我们建议这么做。

想学习一下，为什么建议这样做，如果交给开发者自己去实现这块的逻辑处理，那么组件本身的defaultValue之类是不是都将会失效，并且勾选时候会产生额外的高亮区域，需要进行覆写样式，但我理解我其实变动的地方仅仅是展示的ui内容，而不是变了组件本身的逻辑，却要做这么多工作

**Comment by RedJue** [comment]
> 想学习一下，为什么建议这样做
受控场景下，尽量不干涉用户的逻辑，所有非受控的逻辑应该都由用户自行实现。

**Comment by chongqiangchen** [comment]
> > 想学习一下，为什么建议这样做
> 
> 受控场景下，尽量不干涉用户的逻辑，所有非受控的逻辑应该都由用户自行实现。
有个问题，非受控场景的逻辑是指？组件内部非受控的处理吗，如果是的话组件内部非受控的状态确实不应该依赖外部的控制，只是我觉得前面提出的设计提案在我理解并没有改变Option组件的内部状态，而只是改变了它的表现形式。

关于这个是我理解有问题嘛
