### ISSUE TITLE
Loading icon does not work in Select when Select has suffixIcon prop

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#42631]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zeqose?file=/index.js)

### Steps to reproduce

Define Select, set props "suffixIcon" and "loading"

### What is expected?

When prop "loading" is true, I expect that spin icon is playing in Select 

### What is actually happening?

spin icon is not playing

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome 111 |

**Comment by MadCcc** [comment]
It is intended, you could customize to show your own loading icon.

**Comment by afc163** [comment]
I can't find `suffixIcon` in your codesandbox.

**Comment by evgeniyworkbel** [comment]
> It is intended, you could customize to show your own loading icon.

i did not see how to do it. Could you help me please?

**Comment by evgeniyworkbel** [comment]
> I can't find `suffixIcon` in your codesandbox.

I forgot to save sandbox. Now it is in actual state

**Comment by afc163** [comment]
Ehmm...`loading` actually replace `suffixIcon` to a spin icon if `suffixIcon` is not specified.
