### ISSUE TITLE
Input支持onKeyDown,onKeyUp,onKeyPress吗？

### ISSUE THREAD

**Issue by qazzhoubin** [ant-design/ant-design#4264]
#### 发生问题的环境是：

- antd 版本:1.10.0
- 操作系统及其版本:win8
- 浏览器及其版本:chorme 52.0.2743.116

#### 您做了什么？请提供尽可能详细的重现步骤。

我想在Input上绑定onKeyDown事件 

#### 您期待的结果是:

触发onKeyDown事件

#### 实际上的结果是:

没有触发onKeyDown事件

**Comment by afc163** [comment]
http://codepen.io/anon/pen/ZBmaQd?editors=001

实测可以 。

**Comment by afc163** [comment]
可重现了再 reopen 吧。
