### ISSUE TITLE
当设置  scroll.x = 'max-content' 时,  存在固定列也不会自动使用 tableLayout fixed, 长文本没换行

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#42640]
### Reproduction link

[https://codepen.io/valar123/pen/ZEqPVmZ?editors=001](https://codepen.io/valar123/pen/ZEqPVmZ?editors=001)

### Steps to reproduce

设置scroll.x = 'max-content'

### What is expected?

table-layout:fixed

### What is actually happening?

table-layout:auto

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
游览器默认行为连续文本不会被折行，需要用 `word-break: break-word;` 样式处理一下哈~

ref: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
