### ISSUE TITLE
upload上传前裁剪功能，如果上传的是png图片，裁减之后会自动加上白底

### ISSUE THREAD

**Issue by CFY6-6-6** [ant-design/ant-design#42647]
### Reproduction link

[https://ant-design.gitee.io/components/upload-cn#components-upload-demo-crop-image](https://ant-design.gitee.io/components/upload-cn#components-upload-demo-crop-image)

### Steps to reproduce

在官网中直接上传，就可以复现这个问题

### What is expected?

png图片上传并裁剪之后依旧是透明底色

### What is actually happening?

png图片上传并裁剪之后，变成白底

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | react |
| System | Windows 10 家庭中文版 64 位操作系统 |
| Browser |  Google Chrome 106.0.5249.62（正式版本） （64 位） |

**Comment by zombieJ** [comment]
这是个 Demo 哈，可以自行实现相关逻辑，也可以给 [antd-img-crop](https://github.com/nanxiaobei/antd-img-crop) 提 issue来修哈~
