### ISSUE TITLE
Tooltip prompt is not shown when used with React.cloneElement().

### ISSUE THREAD

**Issue by aswez** [ant-design/ant-design#42652]
### Reproduction link

[https://stackblitz.com/edit/react-jp3vcx?file=demo.tsx](https://stackblitz.com/edit/react-jp3vcx?file=demo.tsx)

### Steps to reproduce

Hover the text.

### What is expected?

When hover the text, Prompt is shown.

### What is actually happening?

When hover the text, Prompt is NOT shown.

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | React latest |
| System | Mac |
| Browser | Chrome lastest |

---
It worked before, but I observed that problem in the latest antd version.

**Comment by aswez** [comment]
Thanks, but when the component is cloned from other place, the problem still persists, I don't want to add some extra component for it becase it will add another node to the DOM tree.

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-jp3vcx-lf9u47?file=demo.tsx

**Comment by aswez** [comment]
Thanks for your quick replay and useful information, the problem now solved.
