### ISSUE TITLE
<InputNumber /> onChange 事件触发后表现不一致

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#4265]
`<InputNumber />` 组件在触发 onChange 事件时表现不一致，导致在 onBlur 事件里可能无法获取到最新的状态。

如下图，[查看demo](http://codepen.io/ystarlongzi/pen/XNyeKx?editors=001)

![111](https://cloud.githubusercontent.com/assets/2840462/21218483/cbea5f1c-c2eb-11e6-81d9-4d986abdcca4.gif)

是否可以考虑在[mixin.js#L76](https://github.com/react-component/input-number/blob/master/src/mixin.js#L76)加个定时器，避免这种现象？

**Comment by luckyyang** [comment]
这里还有一个bug。如果我不blur，直接在input框中输入 1 然后点击提交按钮，目前是不会触发传给form的`onFieldsChange`的，在redux也无法拿到当前的输入值。 @afc163

**Comment by benjycui** [comment]
点击提交按钮是，应该会触发 blur 的。

**Comment by luckyyang** [comment]
我的按钮没有放到form组件中，并没有触发。`onFieldsChange`中接收不到值，手动的onBlur是可以在`onFieldsChange`中接收到值的

**Comment by afc163** [comment]
@luckyyang 最好给个在线例子方便重现和调试，我看你的文字描述貌似有点自相矛盾。

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by luckyyang** [comment]
@afc163 你们有redux的模板么，我是在redux项目中发现这个问题的。

我看到blur确实被触发了，redux也接收到了变化后的值。只是问题是，我提交按钮按下后，无法保证使用的值是变化后的值

**Comment by luckyyang** [comment]
另外，为什么不让InputNumber也触发onChange事件呢?

**Comment by afc163** [comment]
因为有可能输入非数字，InputNumber 目前的实现是 onChange 只输出数字值，非数字输入在 blur 时会清除。

**Comment by luckyyang** [comment]
而实际情况是，直接手动输入值，并不会触发onChange。用户会认为这个是bug

**Comment by luckyyang** [comment]
> 我看到blur确实被触发了，redux也接收到了变化后的值。只是问题是，我提交按钮按下后，无法保证使用的值是变化后的值

请问这样的情况如何解决呢

**Comment by afc163** [comment]
提交按钮按下，blur 应该会先触发的，我本地测试了『用户手动输入数值 + 然后直接点击确定按钮』能拿到。你的问题能否尝试给我个重现，方便我调试和修复。

**Comment by luckyyang** [comment]
要复现的话，我需要单独做一个项目出来，稍等等

**Comment by afc163** [comment]
麻烦了。

**Comment by afc163** [comment]
升级了 rc-input-number，修正成用户输入，blur 时都会触发 onChange。

**Comment by ystarlongzi** [comment]
@afc163 
升级后，如果输入非数字，然后在失去焦点时，文本框内容会为空。如下图，为[官方demo](http://react-component.github.io/input-number/examples/simple.html)截图：
![111](https://cloud.githubusercontent.com/assets/2840462/22009401/e25fb3d2-dcbd-11e6-9038-66a89aca3412.gif)

**Comment by luckyyang** [comment]
@afc163 👍 你们啥时候升级antd ？

**Comment by pastelsky** [comment]
@afc163 Why is this closed? Even though `rc-input-number` (v3.0.0) has fixed the bug, the latest version of antd still points to `~v2.8.3`

**Comment by afc163** [comment]
Will released in `2.7.0` before chinese new year: `2017-01-27`

**Comment by pastelsky** [comment]
Thanks a lot.

**Comment by pastelsky** [comment]
@afc163 Sorry to bug you again with this, but antd has moved to `2.7.0` a couple of days back, but the latest on npm is still `2.6.4`. Is something holding up the release?

**Comment by afc163** [comment]
@RaoHai We can release 2.7.0 now.
