### ISSUE TITLE
Input with suffix or addonAfter can't be styled with inline styling

### ISSUE THREAD

**Issue by balboFK** [ant-design/ant-design#42662]
### Reproduction link

[https://stackblitz.com/edit/react-uyahvw?file=demo.tsx](https://stackblitz.com/edit/react-uyahvw?file=demo.tsx)

### Steps to reproduce

Just open the reproduction and try typing anything without uppercase, the text will still be lowercased.
Remove the suffix from "input1" and the addonAfter from "input2", type again without uppercase, the text will be uppercased.

### What is expected?

Even with suffix and addOnAfter it should be possible to set a inline style for uppercase and it still be applied.

### What is actually happening?

The uppercase transform is not being applied.

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | ^18.2.0 |
| System | Windows 10 |
| Browser | Edge |

---
I dont know if this is a know problem and there is a work around for it with setting a className, but I would like to try a solution that works with inlineStyles, since I can't use className on this specific control.

**Comment by BoyYangzai** [comment]
@balboFK 
hi bro
you can make it work through classNames 😄
such as: https://stackblitz.com/edit/react-uyahvw-npgjn4?file=demo.tsx,index.css

the reason why it not worked is that when you use `suffix` or `addonAfter` ，the domRef will not just a `imput` node , and will bring an extra element,so you can set the `textTransform` style by `.className input`

**Comment by afc163** [comment]
Using `className` in this situation would be a better solution: https://stackblitz.com/edit/react-uyahvw-rqkqme?file=index.css,demo.tsx

Or waiting for `classs` and `styles` https://github.com/ant-design/ant-design/discussions/40221

**Comment by balboFK** [comment]
Hello guys! Thanks for the answears @BoyYangzai  &  @afc163, i was trying to figure it out via inline styles because how I modeled my component to receive specif styling via classNames, I wasn't able to use it, but i rewrote the logic and now I'm able to use it with everything else just fine. So this is the way to go! 
Thanks for the help again.
