### ISSUE TITLE
TreeSelect keyboard navigation has inconsistent focusing

### ISSUE THREAD

**Issue by JeremyMBell** [ant-design/ant-design#42663]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mn31r2?file=/index.tsx)

#### Pre-selected value issue
1. Hit "Tab" to move focus to the  TreeSelect control
2. Press the down arrow, this will open the dropdown
3. Press the down arrow again, this will highlight the top option (unexpected)

#### Mouse-selected value issue
1. Click on the TreeSelect control to open the dropdown
2. Click on "Child Node 2" to select it, and close the dropdown.
3. Press the down arrow, which will open the dropdown again.
4. Press the down arrow again, which will highlight the top option (unexpected)

#### Mixing Hover with keyboard issue
1. Open the TreeSelect dropdown (with click or keyboard)
2. Press down arrow to highlight the top option.
3. Hover over "Child Node 2".
4. Press down arrow again. This will highlight the top option again (unexpected).
 

#### Pre-selected value issue / Mouse-selected value issue
I expected the value under the currently select value to be highlighted, just like behavior with Select components. I have provided a select component to exemplify this issue as well.

#### Mixing Hover with keyboard issue
I expected the highlight to be synced between keyboard and mouse, like the Select component. A keyboard input wouldn't start from the top of the tree.

#### Pre-selected value issue / Mouse-selected value issue
Top value of the tree is being highlighted by the keyboard.

#### Mixing Hover with keyboard issue
Top value of the tree is being highlighted by the keyboard.

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18.0.0 |
| System | macOS 13.3.1 (a)  |
| Browser | Chrome 113.0.5672.63 |

---
Here are the WAI-ARIA specifications for the `tree` role. https://www.w3.org/WAI/ARIA/apg/patterns/treeview/

**Comment by flyFatSeal** [comment]
Let me try to solve this problem
