### ISSUE TITLE
提供一个即时反馈的组件,类似复制成功后会之下而上弹出成功信息

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#42677]
### What problem does this feature solve?

message反馈 感觉太突兀

### What does the proposed API look like?

一个容器组件 ,包裹子组件即可

**Comment by zombieJ** [comment]
有图不，长什么样子看看？

**Comment by MadCcc** [comment]
> 可以搞，15年就想过做这个。

有详细设计不，听起来就是把 message 的容器放出来

**Comment by RedJue** [comment]
> 可以搞，15年就想过做这个。

有其他组件库实现过吗？

**Comment by kiner-tang** [comment]
听描述感觉有点像是 toast

**Comment by vaynevayne** [comment]
你们都没见过吗? 不会吧

**Comment by yoyo837** [comment]
这不是 message.info 那种么?

**Comment by yoyo837** [comment]
> 可以搞，15年就想过做这个。

老板get到了啥样子给大家科普一下呗

**Comment by kiner-tang** [comment]
> 你们都没见过吗? 不会吧

最好提供一下示例或详细描述，免得大家理解错了，最后做出来的东西偏离预期了

**Comment by zombieJ** [comment]
> 这不是 message.info 那种么?

类似于 Alert 但是是推移效果。当然还是贴图看看，免得理解错了。

**Comment by vaynevayne** [comment]
看到好几种即使反馈的实现
toggle tooltip: https://codepen.io/zolash/pen/rbGgJM
toggle button: https://codepen.io/knyttneve/details/BayJEqr
transform tooltip: https://gifbanana.com/post/-NJ62TUQKk9vSwVxbpoq

**Comment by zombieJ** [comment]
> 听描述感觉有点像是 toast

是 Roast，这个偏移动端。在 PC 上对应的就是 message。

**Comment by afc163** [comment]
![1](https://github.com/ant-design/ant-design/assets/507615/75dcbb6f-2606-4232-946b-a5ceeaf8aced)

其实有点像 B 站这个点赞，只不过把这个小人换成我们的 message。原意是在用户交互点附近进行提示。

**Comment by zombieJ** [comment]
> 其实有点像 B 站这个点赞，只不过把这个小人换成我们的 message。原意是在用户交互点附近进行提示。

https://github.com/ant-design/ant-design/pull/40111  快乐工作主题？

**Comment by afc163** [comment]
两回事，这个即时即地反馈只是交互优化不能算是快乐工作。

**Comment by linxianxi** [comment]
可以用 Popover 自己实现一个
https://codesandbox.io/s/san-zhong-chu-fa-fang-shi-antd-5-5-2-forked-wsllof?file=/demo.tsx

**Comment by zombieJ** [comment]
> 可以用 Popover 自己实现一个

效果居然还不错...

**Comment by afc163** [comment]
既然有 Demo 了，先不加组件了。
