### ISSUE TITLE
Form.List 删除一个Form.Item后，还会把之前填写的内容提交

### ISSUE THREAD

**Issue by sorryxc** [ant-design/ant-design#42670]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-10-forked-opl15k)

### Steps to reproduce

先填写userName，然后点击隐藏，把userName删掉，点击提交，会看到还会有userName

### What is expected?

展示当前表单存在的Form.Item的value

### What is actually happening?

会把不存在的FormItem提交

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
What you are looking for is `preserve` prop: https://ant.design/components/form-cn#form
