### ISSUE TITLE
[Component][Affix] Even though Container to scroll is set, it is affected by the window scroll event

### ISSUE THREAD

**Issue by ryuhangyeong** [ant-design/ant-design#42673]
### Reproduction link

[https://ant.design/components/affix#components-affix-demo-target](https://ant.design/components/affix#components-affix-demo-target)

### Steps to reproduce

https://ant.design/components/affix#components-affix-demo-target

### What is expected?

When the container is set to a specific DOM, it is not affected by the window scroll event

### What is actually happening?

When a container is set to a specific DOM, it is affected by window scroll events.

<img width="829" alt="image" src="https://github.com/ant-design/ant-design/assets/27342882/09f09c47-d23b-467b-8c47-c3f9cdfa31ec">

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | recent |
| System | window 11 |
| Browser | Chrome  |

---
https://antdv.com/components/affix#components-affix-demo-target

Normal in antdv

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33529#issuecomment-1004138267
