### ISSUE TITLE
datepicker选择“此刻”，只能双击不能单击

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#4268]
如题，date picker组件，选择“此刻”，只能双击，不能单击，给客户很大困扰，认为这个此刻选择是失效的。
希望修改成单击。

**Comment by benjycui** [comment]
现在就是单击触发。

**Comment by afc163** [comment]
![default](https://cloud.githubusercontent.com/assets/507615/21261017/ed7db10a-c3c3-11e6-8ea8-d22857b117ac.png)
