### ISSUE TITLE
嵌套使用 Layout 会导致内容中的 h1 字号小于 h2

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design#42699]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-5-1-forked-g48x59?file=/demo.tsx)

### Steps to reproduce

根据官网的 Layout demo https://ant.design/components/layout-cn#components-layout-demo-top-side

最简复现 代码
```tsx
import React from "react";
import "./index.css";
import { App, ConfigProvider, Layout } from "antd";
import "antd/dist/reset.css";
const { Content } = Layout;

export default () => (
  <ConfigProvider>
    <App>
      <Layout>
        <Content>
          <Layout>
            <Content>
              <h1>一级标题</h1>
              <h2>二级标题</h2>
            </Content>
          </Layout>
        </Content>
      </Layout>
    </App>
  </ConfigProvider>
);

```

### What is expected?

h1 字号大于 h2，符合 html 标准

### What is actually happening?

![image](https://github.com/immersive-translate/immersive-translate/assets/11746742/0f4b3039-fcdc-4efb-b8f1-2205b212af99)

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.0 |
| System | max |
| Browser | 谷歌 |

**Comment by Wxh16144** [comment]
好像 chrome 默认行为, 原因是 `<Layout />` render 的是一个 `<section />` 标签.  https://stackoverflow.com/a/51316685/11302760

**Comment by zombieJ** [comment]
antd v5 里不做完全覆盖了，全都推荐使用封装的组件来控制层级样式：

https://codesandbox.io/s/ji-ben-yong-fa-antd-5-5-1-forked-h96kv1?file=/demo.tsx

**Comment by xiaohuoni** [comment]
> 好像 chrome 默认行为, 原因是 `<Layout />` render 的是一个 `<section />` 标签.
> 
> **ref:**
> 
> * https://stackoverflow.com/a/51316685/11302760
> * https://stackoverflow.com/a/20644174/11302760
> * https://html.spec.whatwg.org/multipage/rendering.html#sections-and-headings

不是，一层不会。Typography 可以解，有点怪。用 antd 展示 mdx 的时候也要前套一层 Typography
