### ISSUE TITLE
Image 预览时的操作不对所有图片生效

### ISSUE THREAD

**Issue by yukuai123** [ant-design/ant-design#42693]
### What problem does this feature solve?

目前Image组件预览时，若对其中一张图片进行旋转或者放大缩小，此次预览的所有图片切换时都会受到影响，是否可以切换时重置上一张图做的操作，或者提供一个开关控制一下是否对所有图生效？
如： https://arco.design/react/components/image

## resetPreviewOpt: boolean 
* required: false
* defaultValue: false 

<Image.PreviewGroup resetPreviewOpt></Image.PreviewGroup>

**Comment by BoyYangzai** [comment]
我来做一下吧

**Comment by afc163** [comment]
preserveImageState 是不是更好一点。

**Comment by linxianxi** [comment]
现在这样改并不好，切换的时候会有还原的动画。应该改成每个图片单独的 transform。不需要加这个 api，默认就是这种行为。 https://element-plus.org/zh-CN/component/image.html#%E5%9B%BE%E7%89%87%E9%A2%84%E8%A7%88

**Comment by BoyYangzai** [comment]
> 现在这样改并不好，切换的时候会有还原的动画。应该改成每个图片单独的 transform。不需要加这个 api，默认就是这种行为。 https://element-plus.org/zh-CN/component/image.html#%E5%9B%BE%E7%89%87%E9%A2%84%E8%A7%88

确实会有还原的动画 因为他底下的 image 用的是一个
如果切换的时候重置 transform 就带上了动画
@zombieJ cc

**Comment by linxianxi** [comment]
这个应该算个 bug，不是 feature。正常来说切换是要还原的

**Comment by BoyYangzai** [comment]
@linxianxi 等巨佬们决策一下吧 你开了个新pr我的pr就先关了

**Comment by JarvisArt** [comment]
这个问题没有解决？
