### ISSUE TITLE
[checkbox.group]: options props don't have same render behavior as chidren

### ISSUE THREAD

**Issue by liixing** [ant-design/ant-design#42695]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recursing-curie-9f94xl?file=%2Fsrc%2FApp.tsx%3A12%2C50)

### Steps to reproduce

- use options to render one Checkbox.Group, and use children to render another one
- use onChange and value to make the checkbox.group to single selection 
- options components  always has the same order in onChange, which makes we can't select the front Checkbox 

### What is expected?

have the same render behavior when we use options to render Checkbox.Group

### What is actually happening?

single selection can't work well when we use options to render the components

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | macos Ventura version 13.2.1 |
| Browser | chrome Version 111.0.5563.146 (Official Build) (x86_64) |

**Comment by RicardoErii** [comment]
https://github.com/ant-design/ant-design/issues/17297

**Comment by zombieJ** [comment]
It's strange to use CheckBox as Radio. But you should not deps on the order ability since it's not a stable usage. Use diff instead:
https://codesandbox.io/p/sandbox/smoosh-hill-zdzpwx?file=%2Fsrc%2FApp.tsx%3A22%2C15

**Comment by liixing** [comment]
> It's strange to use CheckBox as Radio. But you should not deps on the order ability since it's not a stable usage. Use diff instead:
> 
> https://codesandbox.io/p/sandbox/smoosh-hill-zdzpwx?file=%2Fsrc%2FApp.tsx%3A22%2C15

Sorry ，but You're right, I apologize for the confusion. Here is a corrected version:

I am curious why the onChange behaviors of these two rendering methods are different. I think they should either be both sorted or both unsorted. It would make more sense to have consistent behavior between the two rendering approaches. Having them behave differently in how they handle onChange events can lead to unpredictability and confusion for developers.

**Comment by liixing** [comment]
> It's strange to use CheckBox as Radio. But you should not deps on the order ability since it's not a stable usage. Use diff instead:
> 
> https://codesandbox.io/p/sandbox/smoosh-hill-zdzpwx?file=%2Fsrc%2FApp.tsx%3A22%2C15

Sorry，but I am curious why the onChange behaviors of these two rendering methods are different. I think they should either be both sorted or both unsorted. It would make more sense to have consistent behavior between the two rendering approaches. Having them behave differently in how they handle onChange events can lead to unpredictability and confusion for developers.
