### ISSUE TITLE
Event inside Popover will fire parent component event listener

### ISSUE THREAD

**Issue by ziloen** [ant-design/ant-design#42698]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qoby38?file=/index.js:476-481)

### Steps to reproduce

1. Set content prop for the Popover component, `getPopupContainer={() => document.body}`
2. Add eventListener to Popover parent component 
3. Trigger event on Popover
4. Even Popover is append to body, the event will fire on parent component

### What is expected?

Parent component event listener will not be triggered

### What is actually happening?

Parent event listener was triggered

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | latest |
| System | Windows |
| Browser | Firefox, Chrome |

**Comment by zombieJ** [comment]
It's by design. React virtual dom helps bubble event in the virtual dom tree. ref:

> For example, the child can access the context provided by the parent tree, and events bubble up from children to parents according to the React tree.

* https://react.dev/reference/react-dom/createPortal#reference

You can use stopPop to prevent with `stopPropagation`:
https://codesandbox.io/s/antd-reproduction-template-forked-cky0wt?file=/index.js

**Comment by ziloen** [comment]
OK, I see, thanks for the reply!
