### ISSUE TITLE
Select mode=multiple showSearch 在失焦时清空了 search 但是没有触发 onSearch

### ISSUE THREAD

**Issue by tianjunnew** [ant-design/ant-design#42708]
### Reproduction link

[https://ant.design/components/select-cn#components-select-demo-search-box](https://ant.design/components/select-cn#components-select-demo-search-box)

### Steps to reproduce

给示例程序添加一个 mode="multiple" 即可复现。（输入搜索 -> 点击页面其他地方让输入框失焦 -> 再次点击 Select -> 展示下拉菜单且 options 为上次搜索结果）

### What is expected?

blur 时清空 search 且触发 onSearch('')

### What is actually happening?

blur 时清空 search 但没有触发 onSearch

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | react18 |
| System | macos |
| Browser | chrome113.0.5672.126 |

**Comment by tianjunnew** [comment]
同理 onSelect 后也没有触发 onSearch。

现在的 workaround 为

const clearSearch = useCallback(() => setSearch(''), [])

return <Select onBlur={clearSearch} onSelect={clearSearch} />

请确认这是一个 feature 还是一个 bug。个人更加倾向为 bug

**Comment by zombieJ** [comment]
这个以前有讨论过，有用户反馈在 `onSearch` 上搞 ajax 请求，无法感知是清空触发 `onSearch` 导致清空那次也会调用。所以这个行为就保留不动了。通过受控可以完整控制 `searchValue` 和 `onSearch`。

**Comment by tianjunnew** [comment]
get
