### ISSUE TITLE
Table dataSource中有children字段时 会自动启动 expandable 功能，要通过手动隐藏expandIcon去关闭

### ISSUE THREAD

**Issue by rick-chou** [ant-design/ant-design#42722]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-5-2-forked-wdujqm?file=/demo.tsx)

### Steps to reproduce

/

### What is expected?

/

### What is actually happening?

dataSource中有children字段时 会自动启动 expandable 功能，要通过手动隐藏expandIcon去关闭

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.2.0 |
| System | macos 12.6.3 |
| Browser | chrome |

**Comment by zombieJ** [comment]
`rowExpandable` 是单层展开，`children` 是树状展开，他们管理的内容不一样。可以 `useMemo` 过一层哈：

https://codesandbox.io/s/ji-ben-yong-fa-antd-5-5-2-forked-14s4yq?file=/demo.tsx
