### ISSUE TITLE
options有5000条数据，如何隐藏一部分下拉option的数据，搜索需要搜索所有的，包括隐藏起来的数据

### ISSUE THREAD

**Issue by d-quiet** [ant-design/ant-design#42729]
### What problem does this feature solve?

options有5000条数据，如何隐藏一部分下拉option的数据，搜索需要搜索所有的，包括隐藏起来的数据

### What does the proposed API look like?

可以隐藏一部分下拉option的数据，搜索时搜索所有的

**Comment by zhenzhenChange** [comment]
这不难吧，比如用一个状态 data 存储 5000 条，初始的时候用另一个状态 options 存 10 条，搜索之后触发事件，从 data 里过滤，改变 options 就行了。

https://codesandbox.io/s/da-shu-ju-antd-5-5-2-forked-w5vuxi?file=/demo.tsx

**Comment by zombieJ** [comment]
见 @zhenzhenChange 回复，这个 HOC 就能解。直接封装一下即可哈~
