### ISSUE TITLE
placement property for Select component not working

### ISSUE THREAD

**Issue by anastasia-adv** [ant-design/ant-design#42725]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-mclean-s9huus?file=/src/App.js)

### Steps to reproduce

Use the placement property at "bottomLeft" with a Select component. Click on the Select and scroll up and down, options position should cahnge.

### What is expected?

It's expected that if a placement property is given to the Select component, the options should be fixed at the indicated placement.

### What is actually happening?

If bottomLeft is passed, it sometimes goes to a topLeft placement.

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome latest |

---
On the doc of the Select component (https://ant.design/components/select) in the example about the placement, if you select any placement and scroll the position changes and is not the one that's been selected.

**Comment by linxianxi** [comment]
you can set `dropdownAlign={{ overflow: { adjustY: false } }}`

**Comment by MadCcc** [comment]
文档中没有透出的属性属于非标特性。目前可以通过 ConfigProvider 的 `popupOverflow` 设置弹层的响应区域 https://ant.design/components/config-provider#api

Props that not written in docs is not stable. Currently you could use `popupOverflow` in ConfigProvider to set responsive area for popups: https://ant.design/components/config-provider#api
