### ISSUE TITLE
Tour组件上一步下一步完成按钮最好增加自定义文字属性

### ISSUE THREAD

**Issue by BuGuangshuo** [ant-design/ant-design#42727]
### What problem does this feature solve?

自定义按钮文字，现在按钮文字为英文

### What does the proposed API look like?

nextButtonProps: {
   nextText: '下一步',
   preText:  '上一步'，
   okText:  '完成'
}

**Comment by li-jia-nan** [comment]
<img width="995" alt="image" src="https://github.com/ant-design/ant-design/assets/49217418/57a66525-7cd9-4d42-8f3e-410744ed524a">

**Comment by li-jia-nan** [comment]
这个功能现在有的

**Comment by linxianxi** [comment]
```
nextButtonProps: { children: '自定义文字' } 
```

**Comment by MadCcc** [comment]
也可以用自定义 locale
