### ISSUE TITLE
Carousel 自动轮播 hover暂停的bug

### ISSUE THREAD

**Issue by cage1618** [ant-design/ant-design#4272]
#### 发生问题的环境是：

- antd 版本:2.5.1
- 操作系统及其版本:mac 10.12.1
- 浏览器及其版本:chrome 54.0.2840.98 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。
引入了 Carousel

#### 您期待的结果是:
自动播放， hover时可以暂停，点击切换面板的指示点，再hover上去应该还是暂停的

#### 实际上的结果是:
hover上去确实是暂停了，但如果点了指示面板的指示点，切换到下一张后，再hover时不会暂停，依然会自动播放

#### 可重现的在线演示
官网的 demo 同样存在该问题：
https://ant.design/components/carousel-cn/

**Comment by kimown** [comment]
I think the problem is caused by [react-slick](https://github.com/akiran/react-slick), not ant-design, you should new issue in react-slick.

**Comment by afc163** [comment]
重新安装即可。
