### ISSUE TITLE
Change padding of label in vertical form layout

### ISSUE THREAD

**Issue by mantoze** [ant-design/ant-design#42728]
### Reproduction link

[https://wmzv3e.csb.app/](https://wmzv3e.csb.app/)

### Steps to reproduce

Space between label and input

### What is expected?

Need control label bottom padding

### What is actually happening?

Is there a chance to change label padding then form layout is vertical?

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | React 18.2.0 |
| System | 5.5.1 |
| Browser | Chrome 113 |

**Comment by afc163** [comment]
<img width="566" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/ffb77840-567a-4742-95c7-2115506744b1">

I can't find form in your codesandbox.

**Comment by mantoze** [comment]
Reproduction: https://wmzv3e.csb.app/

**Comment by BoyYangzai** [comment]
@mantoze 
hello 
do you mean you want to change the `padding-bottom` of label ?
if it is  
try `className` 
https://codesandbox.io/s/antd-reproduction-template-forked-9gnvg6?file=/index.css
