### ISSUE TITLE
表格组件的滚动条上下必须同时显示，否则会出现表头和表体的边框错位问题

### ISSUE THREAD

**Issue by relaxed-afternoon** [ant-design/ant-design#4273]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by benjycui** [comment]
现在不就是同时显示么？

![image](https://cloud.githubusercontent.com/assets/3580607/21257073/d6ac9a12-c3b0-11e6-9e52-97864dedc6df.png)

**Comment by benjycui** [comment]
请清楚的描述问题。

**Comment by afc163** [comment]
![default](https://cloud.githubusercontent.com/assets/507615/21265803/02737b8e-c3de-11e6-99c1-e02c785155b2.png)

神图镇楼。
