### ISSUE TITLE
notification 支持隐藏右上角的 closeIcon

### ISSUE THREAD

**Issue by jrr997** [ant-design/ant-design#42736]
### What problem does this feature solve?

notification 目前无法隐藏右上角的 closeIcon。我在 notification 的底部自定义了按钮，希望用户点击我的按钮来交互，而不是点击右上角直接把 notification 关闭。v4 能支持一下吗。

### What does the proposed API look like?

传入一个 prop 控制显隐。

**Comment by linxianxi** [comment]
可以先样式 display:none

**Comment by jrr997** [comment]
> 可以先样式 display:none

外面有层 Dom 有 hover 样式

**Comment by linxianxi** [comment]
<img width="312" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/3f1200b4-3cac-4fff-9886-c67fb6bdc05e">

**Comment by jrr997** [comment]
> <img alt="image" width="312" src="https://user-images.githubusercontent.com/47104575/242132397-3f1200b4-3cac-4fff-9886-c67fb6bdc05e.png">

这确实有用。我是通过 class 选择器来选中这个 dom 然后再加 display: none 的，还得加个 className 以防影响其他通知框。

**Comment by kiner-tang** [comment]
@jrr997 经过讨论，我们将会提供隐藏关闭按钮的方式，具体设计和开发进展会在这边同步，可以持续关注一下

**Comment by MadCcc** [comment]
v4 不添加新 feature 了，还是先魔改一下吧

**Comment by linxianxi** [comment]
v5 可以 closable={false}，但是文档和 ts 没写，v4 写死为 false 了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/42791
