### ISSUE TITLE
QRCode 设置的 icon 跨域，在  toDataURL  后报错

### ISSUE THREAD

**Issue by 1587315093** [ant-design/ant-design#42733]
### What problem does this feature solve?

报错信息 `Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

问题出在 `qrcode.react `上

目前解决方案自己是 将` icon` 的 `url `转 `base64`  再赋值给 `QRCode `的 `icon` 了
### What does the proposed API look like?

或许antd 可以处理下icon 内部转成 base64 ?

像html2canvas一样，有一个  useCORS: true,

**Comment by 1587315093** [comment]
或许应该 qrcode.react 那边来解决

复现代码

```jsx

import { QRCodeCanvas } from "qrcode.react";
import { useMemo } from "react";

const Demo1 = () => {
  const qrCodeProps = useMemo(() => {
    const imageSettings = {
      src:
        "https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web//static/favicons/favicon-32x32.png",
      x: undefined,
      y: undefined,
      height: 16,
      width: 16,
      excavate: true,
      crossOrigin: "anonymous"
    };
    return {
      value: "",
      size: 200,
      level: "H",
      fgColor: "#000",
      imageSettings: imageSettings
    };
  }, []);

  const handleClick = () => {
    const canvas = document.getElementsByClassName("qrcode")[0];
    const url = canvas.toDataURL("image/png");
    console.log(url);
  };

  return (
    <div>
      <QRCodeCanvas {...qrCodeProps} className="qrcode" />
      <button onClick={handleClick}> toDataURL</button>
    </div>
  );
};
export default Demo1;

```

**Comment by MadCcc** [comment]
跨域问题我理解应该应用处理，组件做特殊处理的话有些逾界了

**Comment by 1587315093** [comment]
> 跨域问题我理解应该应用处理，组件做特殊处理的话有些逾界了。可以讨论一下

是的，问题还是出在qrcode.react那边，现在就是看组件这边需不需要兜底之类的，或者qrcode.react那边处理

**Comment by afc163** [comment]
See https://github.com/zpao/qrcode.react/issues/143#issuecomment-918741587

**Comment by stoickeyboard** [comment]
@afc163 Why did you close this? The comment you linked to states a potential solution that hasn't been implemented yet.
