### ISSUE TITLE
onKeyDown在Tree组件中不生效

### ISSUE THREAD

**Issue by acforu** [ant-design/ant-design#42731]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mu-lu-antd-5-5-2-forked-po4utn)

### Steps to reproduce

选中tree中的node，键盘输入任意字符

### What is expected?

调用keyDownEvent函数，打印出log

### What is actually happening?

没有打印出来

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | windows |
| Browser | electron |

**Comment by BoyYangzai** [comment]
@acforu 
文档里好像没有支持这个事件 
https://ant.design/components/tree-cn#tree-props

**Comment by acforu** [comment]
> @acforu 文档里好像没有支持这个事件 https://ant.design/components/tree-cn#tree-props

文档里的确没有，但是跳转过去能看到定义。  如果我想实现这样的功能，有办法做到吗？
![image](https://github.com/ant-design/ant-design/assets/3379984/db228ae2-4690-4887-9c8a-ace0c3732f66)

**Comment by linxianxi** [comment]
<img width="1111" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/a88ff358-5150-4c8f-9681-757b553af838">
onKeyDown 是这个 input 的

**Comment by linxianxi** [comment]
Tree 不是这些，不支持也是合理的吧
<img width="1195" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/fd736aa4-be5d-4ab3-b31b-422bb35b1927">

**Comment by acforu** [comment]
我主要想给文件夹的树状UI，增加键盘输入跳转的功能，比如按A就跳到A开头的目录或文件。

**Comment by linxianxi** [comment]
触发 onSelect 并有值后，监听全局的键盘事件，取消选中后移除监听。

**Comment by acforu** [comment]
发现MUI的treeview自带这个功能。
