### ISSUE TITLE
Allow Access to Popover Container of ColorPicker component for Customization

### ISSUE THREAD

**Issue by JanFuhrmann** [ant-design/ant-design#42749]
### What problem does this feature solve?

Access to Popover Container of ColorPicker allows simple customization, e.g. to show another slider for gradients

### What does the proposed API look like?

Two possible solutions:
1. An extra method getContainer or property header/content/footer (like in Modal) to directly set ReactNodes
2. The option to integrate the ColorPicker outside of the popup

![GradientColorPicker](https://github.com/ant-design/ant-design/assets/7986696/344bb215-c6d0-40f7-921d-8fd1008def04)

**Comment by MadCcc** [comment]
Your example is totally different from antd's design. It's hard to customize to meet a new design.
So could you provide more detail on API?

**Comment by JanFuhrmann** [comment]
I just need an option to add ReactNodes within the popover (e.g. in the header before the actual ColorPicker). In the example image above these are represented by two buttons, a slider and some further fields. The bottom part is just our old implementation and therefore can be ignored (replaced by the antd ColorPicker).

**Comment by JanFuhrmann** [comment]
Currently I don't see a possible solution for my problem within this feature branch. 
Is it planned in the future that the ColorPicker popover can be modified or that gradients with multiple stops are supported?
