### ISSUE TITLE
Tabs 组件 type=“card” size=“small” 时，高度有问题

### ISSUE THREAD

**Issue by fenlgy** [ant-design/ant-design#4274]
- antd 版本:1.11.2
- 操作系统及其版本:win 10
- 浏览器及其版本:主流浏览器

#### 实际上的结果是:

![qq 20161216161939](https://cloud.githubusercontent.com/assets/2751655/21256144/8d8607c4-c3ab-11e6-8a2b-72dc7250c9e4.png)

**Comment by yesmeck** [comment]
重复 https://github.com/ant-design/ant-design/issues/3635

**Comment by fenlgy** [comment]
看来只能自己解决了。。。
