### ISSUE TITLE
Select组件在安卓端使用会自动失去焦点软键盘收起，导致输入不了，进行不了模糊搜素

### ISSUE THREAD

**Issue by 97702573** [ant-design/ant-design#42740]
### Reproduction link

[https://datav.alibaba-inc.com/share/8cca8ce85ee85678d1fe736ddd5747e7](https://datav.alibaba-inc.com/share/8cca8ce85ee85678d1fe736ddd5747e7)

### Steps to reproduce

进入网页进行模糊搜索，但是select组件先获取焦点，又马上失去焦点，导致输入不了文字。

### What is expected?

期望antd兼容安卓，使Select组件可以模糊搜索。

### What is actually happening?

进入网页进行模糊搜索，但是select组件先获取焦点，又马上失去焦点，导致输入不了文字。

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 16.13.1 |
| System | 安卓 |
| Browser | 百度浏览器最新版本 |

**Comment by jrr997** [comment]
Reproduction link 无法访问
