### ISSUE TITLE
RangPicker 360极速浏览器 会出现点击显示严重卡顿问题，关闭时不卡顿。 DatePicker 卡顿不严重。最新版本谷歌浏览器没有发现此问题。

### ISSUE THREAD

**Issue by var-lu** [ant-design/ant-design#42755]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7gwvl0)

### Steps to reproduce

主要是兼容360极速浏览器（谷歌内核78）样式问题

```jsx
<StyleProvider 
	hashPriority="high"  
	transformers={[legacyLogicalPropertiesTransformer]}
>
 
</StyleProvider>
     
```

然后在新版本谷歌浏览器正常使用日期选择器，没有卡顿问题。在360极速浏览器RangePicker点击显示会出现卡顿问题（大约1s才会显示)DatePicker 卡顿500ms

### What is expected?

在360浏览器极速浏览器上点击日期范围选择器日期选择器 能够快速显示选择器。

### What is actually happening?

在360浏览器极速浏览器上点击日期范围选择器日期选择器 显示卡顿

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.2.0 |
| System | macOS 12.2 |
| Browser | 360浏览器12.2.1664.0 谷歌内核版本：78.0.3904.108 |

**Comment by zombieJ** [comment]
= =，居然还没更新么，是不是 极速浏览器被放弃了。。。

merge into https://github.com/ant-design/ant-design/issues/39082#issuecomment-1330323053

**Comment by zombieJ** [comment]
PS:如果一定要支持。 可以在 CP 里设置 theme.motion = false，关掉动画。

**Comment by var-lu** [comment]
在点击之后我看了一眼对应dom，发现dom的类名变化也是有延迟的，应该不是动画的问题，而且像下拉框这种点击是好的，点击没有延迟，刚开始我用的antd 5.1.6 下拉框点击也是有延迟问题，但是当我升级到5.5.2时，发现下拉框延迟问题已经解决了，但是对应日期选择器延迟问题依然没有解决。
