### ISSUE TITLE
Mobile horizontal stepper

### ISSUE THREAD

**Issue by caferyukseloglu** [ant-design/ant-design#42760]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-dewdney-2khr6p?file=/src/App.js)

### Steps to reproduce

<Steps
 current={currentStep}
  responsive={false}
  direction="horizontal"
  labelPlacement="horizontal"
  progressDot
  items={steps}
  className={`quote-stepper mt-2 mb-2`}
  size="small"
 />

### What is expected?

The stepper fit the screen

### What is actually happening?

It is out of the screen

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 17.0.1 |
| System | Mac |
| Browser | Safari |

---
Can make if we can calculate inline margins

**Comment by afc163** [comment]
If you override antd's styles completely, then you have to resolve style problem by youself, Thx for understanding.
