### ISSUE TITLE
ant-design/icons使用报错

### ISSUE THREAD

**Issue by Yyutaa** [ant-design/ant-design#42767]
### Reproduction link

[https://ant.design/components/icon-cn](https://ant.design/components/icon-cn)

### Steps to reproduce

报错提示如下：
Property 'rev' is missing in type '{ className: string; onClick: () => void; }' but required in type 'Pick<AntdIconProps, "cite" | "data" | "form" | "label" | "slot" | "span" | "style" | "summary" | "title" | "pattern" | "children" | "start" | "hidden" | "color" | ... 349 more ... | "twoToneColor">'.  TS2741

### What is expected?

上面的报错提示每个引入的icon需要加rev参数，但是这个参数毫无意义，不知道加了有啥用，不加就会报错

### What is actually happening?

上面的报错提示每个引入的icon需要加rev参数，但是这个参数毫无意义，不知道加了有啥用，不加就会报错

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 17.0.1 |
| System | mac |
| Browser | 谷歌浏览器 |

**Comment by afc163** [comment]
升级 @type/react 和 @type/react-dom 到最新即可修复。

**Comment by zxhycxq** [comment]
> type/react

楼主如何解决的哈？

**Comment by ojemuyiwa** [comment]
> @ojemuyiwa Have you try upgrade @types/react and @types/react-dom version? Is there still a type error after upgrading?

Yeah sadly. Parent `React.HTMLProps` doesn't have rev attribute. if you want to add to and it should be optional.

**Comment by yifanwww** [comment]
I checked the change history of `@types/react` in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), and found that they added `rev` field into `AllHTMLAttributes` at this [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3f5d20608d31363487694535189ef64569043ff9) on Apr 04 2023.

Accroding to the time, we can know that `@types/react` supports `rev` field from [`v18.0.33`](https://www.npmjs.com/package/@types/react/v/18.0.33), [`v17.0.56`](https://www.npmjs.com/package/@types/react/v/17.0.56), [`v16.14.38`](https://www.npmjs.com/package/@types/react/v/16.14.38) and [`v15.7.14`](https://www.npmjs.com/package/@types/react/v/15.7.14).

So theoretically, once we upgrade `@types/react` to above versions or higher, we won't get that error any more. And on my side, it works.

**Comment by arturdonda** [comment]
> I checked the change history of `@types/react` in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), and found that they added `rev` field into `AllHTMLAttributes` at this [commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/3f5d20608d31363487694535189ef64569043ff9) on Apr 04 2023.
> 
> Accroding to the time, we can know that `@types/react` supports `rev` field from [`v18.0.33`](https://www.npmjs.com/package/@types/react/v/18.0.33), [`v17.0.56`](https://www.npmjs.com/package/@types/react/v/17.0.56), [`v16.14.38`](https://www.npmjs.com/package/@types/react/v/16.14.38) and [`v15.7.14`](https://www.npmjs.com/package/@types/react/v/15.7.14).
> 
> So theoretically, once we upgrade `@types/react` to above versions or higher, we won't get that error any more. And on my side, it works.


Updating `@types/react` worked for me as well. Thanks, @yifanwww

**Comment by Lemon-Cai** [comment]
![image](https://github.com/ant-design/ant-design/assets/37281618/14b1f989-a8f2-4218-9e57-910167334e4e)

![image](https://github.com/ant-design/ant-design/assets/37281618/fa63272f-7cd3-42f5-b87c-38debcff5684)

然而我按照说的把 ` @types/react ` 和 ` @types/react-dom ` 都升级到最新的版本后还是存在这个问题

**Comment by Lemon-Cai** [comment]
> @ojemuyiwa Have you try upgrade @types/react and @types/react-dom version? Is there still a type error after upgrading?您是否尝试过升级@types/反应和@types/反应-dom版本？升级后还有类型错误吗？

https://user-images.githubusercontent.com/37281618/249365955-14b1f989-a8f2-4218-9e57-910167334e4e.png

https://user-images.githubusercontent.com/37281618/249366365-fa63272f-7cd3-42f5-b87c-38debcff5684.png

然而我按照说的把 @types/react 和 @types/react-dom 都升级到最新的版本后还是存在这个问题

**Comment by afc163** [comment]
@Lemon-Cai 给个重现？

**Comment by Lemon-Cai** [comment]
> 

ok。https://github.com/Lemon-Cai/react-admin
请切换到 dev分支 ， install 后， npm run start:web。目前我增加了 ` rev={null} ` 解决报错问题
\packages\web\src\pages\Login\index.tsx； 34行

**Comment by Lemon-Cai** [comment]
> @Lemon-Cai 给个重现？

ok。https://github.com/Lemon-Cai/react-admin
还行。https://github.com/Lemon-Cai/react-admin
请切换到 dev分支 ， install 后， npm run start:web。目前我增加了 rev={null} 解决报错问题
\packages\web\src\pages\Login\index.tsx； 34行
\packages\web\src\pages\Login\index.tsx; 34行

**Comment by yifanwww** [comment]
@Lemon-Cai 无法复现你截图里的报错，相反添加 `rev={null}` 之后反而出现了新的报错
![image](https://github.com/ant-design/ant-design/assets/55199350/1580d857-3fe1-4cc9-b9f5-201b9c13c849)
删除 `rev={null}` 之后就没问题了

你升级 `@types/react` 之后重启了 tsserver 或编辑器/IDE了吗？

**Comment by afc163** [comment]
@Lemon-Cai 看上去没有问题了。

<img width="744" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/7a76e590-81da-4773-aed3-074b15fcadf4">

加上 rev 反而报错。

<img width="790" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/c9c6354a-b8b5-4870-8028-04e4d486988c">

**Comment by Lemon-Cai** [comment]
> @Lemon-Cai 看上去没有问题了。
> 
> <img alt="图片" width="744" src="https://user-images.githubusercontent.com/507615/249753868-7a76e590-81da-4773-aed3-074b15fcadf4.png">
> 加上 rev 反而报错。
> 
> <img alt="图片" width="790" src="https://user-images.githubusercontent.com/507615/249753932-c9c6354a-b8b5-4870-8028-04e4d486988c.png">

我换个电脑重新 pnpm install 后也好了，谢谢了。
