### ISSUE TITLE
优化上手文档

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#42765]
<img width="259" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/a5f3b5f0-fd03-4b8b-a86a-5a0f86baa3c9">

https://mantine.dev/guides/cra/

模板化改造一下，增加更多框架示例，现在我们的文档也比较啰嗦，其实简单点就行。

**Comment by MadCcc** [comment]
https://github.com/ant-design/create-next-app-antd
可以把这些 example 都放在一个仓库里了

**Comment by afc163** [comment]
https://ant.design/docs/react/use-with-create-react-app-cn#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE

还有比如 craco 已经不需要了。
