### ISSUE TITLE
autoFocus并未在InputNumber 中生效

### ISSUE THREAD

**Issue by ZiYi0414** [ant-design/ant-design#42770]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-emc0uk?file=/index.js)

### Steps to reproduce

autoFocus 不可用

### What is expected?

自动聚焦到InputNumber

### What is actually happening?

无效果

| Environment | Info |
| --- | --- |
| antd | 5.3.1 |
| React | 18 |
| System | MacOS 13.2.1 |
| Browser | Chrome 版本 113.0.5672.126（正式版本） (arm64) |

**Comment by Wxh16144** [comment]
https://github.com/ant-design/ant-design/assets/32004925/12b4982d-a418-41ba-8ee2-4510a8d15df8

我这边好像没有问题🤔

**Comment by BoyYangzai** [comment]
> 我这边好像没有问题🤔

+1～
