### ISSUE TITLE
Multi Draggable Component - Non Server Upload (Feature Request)

### ISSUE THREAD

**Issue by rohitjindal18** [ant-design/ant-design#4277]
- antd verison 2.5.1:

#### What did you do? Please provide as detailed a step as possible.

Using multi upload drag and drop component of antd. I just want a drag and drop component with server upload disabled.

#### The results you expect are:

Component should take a boolean prop for server upload request or not.

#### The actual result is:

Currently component makes a network request.
We need just the fileList and not the upload request to Server

**Comment by benjycui** [comment]
Try `beforeUpload`, see: https://ant.design/components/upload/

**Comment by rohitjindal18** [comment]
beforeUpload callback is only returning file, whereas rc-upload beforeUpload says it will return both the file and fileList.
