### ISSUE TITLE
filterDropdown in table not rendering

### ISSUE THREAD

**Issue by sambhav2612** [ant-design/ant-design#42773]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/patient-water-dxjbv0?file=/src/App.js)

### Steps to reproduce

Just run the code

### What is expected?

Filter dropdown should render and after adding input upon enter should return filtered values like this: 

`{name: ["filtered-value-here"], ...}`

### What is actually happening?

table which is rendered is not responding on clicking the filter icon against the columns

| Environment | Info |
| --- | --- |
| antd | 4.9.4 |
| React | 17 |
| System | macOS 13 |
| Browser | Brave |

**Comment by afc163** [comment]
Could you upgrade your antd version to latest 4.x version?

https://codesandbox.io/s/sweet-shadow-pqmxuy?file=/package.json

**Comment by sambhav2612** [comment]
> Could you upgrade your antd version to latest 4.x version?

We can't, our system is built around antd pro v4 and the layouting (+ forms) breaks on upgrading to v4 LTS

@afc163
