### ISSUE TITLE
Dropdown在shadowdom中使用有问题

### ISSUE THREAD

**Issue by luokebi** [ant-design/ant-design#42776]
### Reproduction link

[https://stackblitz.com/edit/react-c8ww4r?file=index.tsx](https://stackblitz.com/edit/react-c8ww4r?file=index.tsx)

### Steps to reproduce

设置getPopupContainer后样式消失，没法关闭

### What is expected?

样式正常，点空白处关闭

### What is actually happening?

样式消失，没法关闭

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.2.0 |
| System | Macos 13.4 |
| Browser | Chrome 104 |

**Comment by BoyYangzai** [comment]
无法关闭的原因在于当你点击生成下面彩蛋的时候
该行为所需要的 Style 是默认插在最上层的HTML上的 被 shaodowdom 隔离了 css
![image](https://github.com/ant-design/ant-design/assets/94534613/26ca0d26-f81a-45f3-8cdb-cfb75d1f1c60)

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-c8ww4r-88kql5?file=index.tsx

**Comment by luokebi** [comment]
@afc163 对不起我忘了写container，主要的一个问题是dropdown在5.5.2收起时没有动画，直接消失，然而在5.4.7是正常的，对比这个https://stackblitz.com/edit/react-c8ww4r-88kql5?file=demo.tsx

**Comment by afc163** [comment]
可以再提个 issue。

**Comment by luokebi** [comment]
ok
