### ISSUE TITLE
DefaultFilteredValue not working

### ISSUE THREAD

**Issue by rangrasjay** [ant-design/ant-design#42777]
### Reproduction link

[https://codepen.io/RangrasJay/pen/mdzZQWx?editors=001](https://codepen.io/RangrasJay/pen/mdzZQWx?editors=001)

### Steps to reproduce

It is there

### What is expected?

default value should come up

### What is actually happening?

no default value is getting populated

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 17 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
Like `<input value="value" defaultValue="defaultValue" />`,  `value` which is a controlled property  have priority over `defaultValue` the uncontrolled property.
