### ISSUE TITLE
Color Picker Initial Value is not Working With Form

### ISSUE THREAD

**Issue by firatcanulukaya** [ant-design/ant-design#42783]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-colorpicker-initial-value-bug-w5b52k?file=/index.js)

### Steps to reproduce

1. Import ColorPicker & Form from antd@5.5.2
2. Make an custom color picker component using antd's ColorPicker component
3. Wrap ColorPicker component inside of Form.Item component then wrap all components into the Form component
4. Try to set initialValue with ref (by formRef.current.setFieldsValue() function) or try to set initialValue by using initialValue in Form.Item component

### What is expected?

Setting initial value to ColorPicker component

### What is actually happening?

It's not setting the initial value to ColorPicker component

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.0.0 |
| System | Windows 10 Pro 22H2 |
| Browser | Chrome v113.0.5672.127 |

**Comment by RedJue** [comment]
You may have forgotten to pass the value to the ColorPicker. 
ref: https://codesandbox.io/s/ant-design-colorpicker-initial-value-bug-forked-ipmydd?file=/CustomColorPicker.js

**Comment by yoyo837** [comment]
And also see docs here https://ant.design/components/form#components-form-demo-customized-form-controls

**Comment by GautamiDhokte1999** [comment]
I also encountered the same issue. The solution that worked for me involved ensuring that I wasn't passing 'undefined' and instead passing a valid color value as follows

<ColorPicker
                    value={accentColor || '#1677FF'}
                    onChange={(_, hex) => {
                      form.setFieldsValue({ accentColor: hex });
                    }}
                  />
