### ISSUE TITLE
A style bug about Drivider component

### ISSUE THREAD

**Issue by kongmingLatern** [ant-design/ant-design#42796]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-wen-zi-de-fen-ge-xian-antd-5-5-2-forked-9liceo?file=/demo.tsx)

### Steps to reproduce

```tsx
     {/** Working */}  
    <Divider orientation="right" orientationMargin={20}>
       text number 20
    </Divider>

    {/** Not Working */}
    <Divider orientation="right" orientationMargin="20">
      text string 20
    </Divider>
```

### What is expected?

> Their children's style shoule be same.

```html
<span class="ant-divider-inner-text" style="margin-right: 20px;">text string 20</span>
```

### What is actually happening?

```html
<span class="ant-divider-inner-text">text string 20</span>
```

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.2.0 |
| System | Windows |
| Browser | Google Version 113.0.5672.64 |

**Comment by BoyYangzai** [comment]
![image](https://github.com/ant-design/ant-design/assets/94534613/0d4bcb77-8745-4092-80f9-e8a125177782)
the type of '20' can't be used here 
just `20` - number or '20px' can work
