### ISSUE TITLE
打包后的antd.js没有Button组件的问题

### ISSUE THREAD

**Issue by wishflyer** [ant-design/ant-design#428]
我测试了下npm run release，打包后的文件，没有把Button组件给引出来，查看了下index.js,确实没有导出Button.同时在Button目录下，也没看到该组件。麻烦处理下哩~~

**Comment by kevyu** [comment]
button现在只有样式没有react组件吧。

**Comment by elrrrrrrr** [comment]
Button 要等 0.10.0 发布之后才有哟
目前还是 0.9.x http://09x.ant.design/

**Comment by afc163** [comment]
#411
