### ISSUE TITLE
希望Popover组件能够暴露出控制内部open状态的hooks

### ISSUE THREAD

**Issue by coder-xiaotian** [ant-design/ant-design#42807]
### What problem does this feature solve?

我有这样一个组件
```js
<Popover trigger="click" content={<CutOutSetting onConfirm={() => {保存设置，然后关闭}} />}>
  <span>截取设置</span>
</Popover>;

function CutOutSetting({ onConfirm }) {
  return (
    <div>
      {/* some jsx **/}
      <Button type="primary" style={{ marginLeft: "30px" }} onClick={onConfirm}>
        确定
      </Button>
    </div>
  );
}
```
逻辑是CutOutSetting中点击确认按钮后，保存了配置就将Popover弹框关闭，按照现在的逻辑需要在Popover组件外部维护open状态，如果能够提供相关的控制状态hook的话，就可以直接在CutOutSetting组件中做关闭操作，无需定义额外状态，代码更整洁。

### What does the proposed API look like?

const {open, setOpen} = Popover.useOpen()
可能命名不太好，可以再优化

**Comment by BoyYangzai** [comment]
```ts
const {open, setOpen} = Popover.useOpen()
```
这本质上还是受控了吧 推荐直接使用受控模式

**Comment by coder-xiaotian** [comment]
```js
<Popover trigger="click" content={<CutOutSetting onConfirm={() => {保存设置，然后关闭}} />}>
  <span>截取设置</span>
</Popover>;

function CutOutSetting({ onConfirm }) {
  const {open, setOpen} = Popover.useOpen()

  return (
    <div>
      {/* some jsx **/}
      <Button type="primary" style={{ marginLeft: "30px" }} onClick={() => {
        onConfirm()
        setOpen(false)
      }}>
        确定
      </Button>
    </div>
  );
}
```
本质肯定还是受控组件，这样做的目的是为了优化代码的组织结构，让外部组件无需维护它不关心的状态（在我的这个案例中外部是无需关心open状态的），代码层次结构更好。如果有十个这样的Popover组件的话，在外部就需要维护十个相关open状态，如果有useOpen这样的hook的话就可以直接拿到Popover内部的状态并且去控制它。

**Comment by BoyYangzai** [comment]
@zombieJ 召唤豆酱看一下

**Comment by MadCcc** [comment]
有一个问题，这种情况到底是受控还是不受控？

能使用 hook 确实会很方便，但是 hook 本身是不能让上下文受控的，无法控制上下文的逻辑。

如果需要实现提到的场景的话，外层受控还是不可避免的，否则 open 还是会响应 Popover 的内部状态而不是 hook 里返回的 `open` 和 `setOpen`。

**Comment by afc163** [comment]
应该使用 open 受控属性控制（即使看上去麻烦一点），内部状态不应该被暴露出来。

**Comment by coder-xiaotian** [comment]
> 有一个问题，这种情况到底是受控还是不受控？
> 
> 能使用 hook 确实会很方便，但是 hook 本身是不能让上下文受控的，无法控制上下文的逻辑。
> 
> 如果需要实现提到的场景的话，外层受控还是不可避免的，否则 open 还是会响应 Popover 的内部状态而不是 hook 里返回的 `open` 和 `setOpen`；而如果外层受控后这个 hook 又没有意义了。

你说的hook不能让上下文受控，我不太明白，请教一下，能否详细说说。
我没理解错的话，这里的Form.useFormInstance应该是控制了上下文的
<img width="784" alt="image" src="https://github.com/ant-design/ant-design/assets/22257014/4da07338-a2f6-4374-aa78-7c4e958a8d76">
