### ISSUE TITLE
validateFields 验证的时候，value 里面的值是有的

### ISSUE THREAD

**Issue by zuimeiaj** [ant-design/ant-design#4280]
#### 发生问题的环境是：

- antd 版本:antd v2.4.2
- 操作系统及其版本: osx 10.10.5
- 浏览器及其版本:55.0.2883.95 (64-bit)
#### 您做了什么？请提供尽可能详细的重现步骤。

使用 getFieldDecorator 申明的input控件，给了 initialValue:初始值
如何下
 {
                        getFieldDecorator("Start", {
                            initialValue: PriceModel.get("Start"),
                            rules: [
                                {required: true, message: "请输入起订量,按出售单位计算"}
                            ]
                        })(<Input className={'input-item'} placeholder="请输入起订量,按出售单位计算" type="text"/>
                        )
                    }

#### 实际上的结果是:

 validateFields((error, value)=> {
                    console.log(value);
                    if (!error) func_addGoods(value, addGoodsId, updateGoodsId);
                })
![image](https://cloud.githubusercontent.com/assets/11345054/21286233/1a0b2d18-c489-11e6-80e9-586131551f11.png)

value 里面有值，但是验证却错误了

**Comment by zuimeiaj** [comment]
追加一个只有在type=number 的时候才会出现

**Comment by afc163** [comment]
```diff
rules: [
-  { required: true, message: "请输入起订量,按出售单位计算" }
+  { required: true, message: "请输入起订量,按出售单位计算", type: 'number' }
],
```

**Comment by zuimeiaj** [comment]
麻烦你们了，我在网上找到了解决办法了，谢谢

**Comment by afc163** [comment]
最好把你遇到的问题和解决方案贴一贴，方便来搜索的人。
