### ISSUE TITLE
【排序问题】Table组件的onChange事件当排序和分页同时存在时，无法区分由排序触发的事件

### ISSUE THREAD

**Issue by azx1573** [ant-design/ant-design#42829]
### Reproduction link

[https://ant.design/components/table-cn#components-table-demo-ajax](https://ant.design/components/table-cn#components-table-demo-ajax)

### Steps to reproduce

1. 给Table同时设置排序和分页
2. 当排序触发时，需要将分页的当前页重置为1，但是现在的Table组件的onChange事件当分页和排序同时存在时无法区分当前的change是由排序触发的

### What is expected?

当分页和排序同时存在时，期望能提供一个点击排序功能后的回调函数，
我们需要在触发了排序操作后将当前页的current置为1。

### What is actually happening?

当分页和排序同时存在时，无法区分由排序触发的事件

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 4.16.12 |
| System | MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) |
| Browser | 114.0.5735.90（正式版本） (x86_64) |

---
排序触发后，理应将数据的current置为1，不然如果停留在后面的页面中时，数据会因为排序发现很大变化会给用户造成困扰。

**Comment by linxianxi** [comment]
可以从 onChange action 获取
<img width="1094" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/31bafc4e-f4eb-40d2-a8f2-e2a203d8501d">

**Comment by azx1573** [comment]
>

> 可以从 onChange 第四个参数的 action 获取 <img alt="image" width="1094" src="https://user-images.githubusercontent.com/47104575/243294925-31bafc4e-f4eb-40d2-a8f2-e2a203d8501d.png">

非常感谢，亲测有效，没有注意到这个参数，😂
