### ISSUE TITLE
Antd Form example typo issue

### ISSUE THREAD

**Issue by vikramparihar** [ant-design/ant-design#42820]
### Reproduction link

[https://ant.design/components/form#components-form-demo-register](https://ant.design/components/form#components-form-demo-register)

### Steps to reproduce

In the antd form example (Registration)
In the antd form example (Registration)
<Form.Item
        name="confirm"
        label="Confirm Password"
        dependencies={['password']}
        hasFeedback
        rules={[
          {
            required: true,
            message: 'Please confirm your password!',
          },
          ({ getFieldValue }) => ({
            validator(_, value) {
              if (!value || getFieldValue('password') === value) {
                return Promise.resolve();
              }
              return Promise.reject(new Error('The two passwords that you entered do not match!'));
            },
          }),
        ]}
      >
        <Input.Password />
      </Form.Item>

### What is expected?

In above example here is syntax "The two passwords that you entered do not match"
This syntax should be "The new passwords that you entered do not match"

### What is actually happening?

Error Syntax is not matching with validation

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by BoyYangzai** [comment]
@vikramparihar 
hello bro
I think that's ok and it just a example，you can adjust it in your project.

**Comment by Ali-ovo** [comment]
i can fix this
