### ISSUE TITLE
Consolidating CSS Frameworks and Component Libraries with css variables

### ISSUE THREAD

**Issue by WilliamPeralta** [ant-design/ant-design#42832]
### What problem does this feature solve?

We currently use three CSS frameworks and component libraries in our systems and would like to consolidate our main styles into a single file. It would be perfect if we could utilize CSS variables as values in the tokens of your configuration object.

Could you please consider adding support for CSS variables in your configuration object? This would greatly enhance the flexibility and customization options for your users, and we believe it would significantly improve our development workflow.

Thank you for your attention to this matter. We look forward to your response.

Best regards,

### What does the proposed API look like?

```js
import { ThemeConfig } from "antd";
export const theme: ThemeConfig = {
  token: {
    borderRadius: 2,
    colorBgContainerDisabled: "var(--kit-disabled-bg)",
    colorBorder: "var(--kit-color-borders)",
    colorPrimary: "var(--kit-color-primary)",
  }
}
```

**Comment by zombieJ** [comment]
Thanks for advice.

Css variable is weak for algorithm realization. That's why we replace css variable customization (used in v4) with cssinjs in v5.

You can check for the algorithm for ref:
* https://github.com/ant-design/ant-design/blob/master/components/theme/themes/default/index.ts

**Comment by zombieJ** [comment]
PS: traditional `className` override is still workable which means you can do as:
```css
.ant-btn {
  color: var(--color-primary);
}
```

**Comment by WilliamPeralta** [comment]
> PS: traditional `className` override is still workable which means you can do as:
> 
> ```css
> .ant-btn {
>   color: var(--color-primary);
> }
> ```

Thank you for the response, I figured there was a reason for it not being implemented. Unfortunately, the CSS solution doesn't work in development since :where(.css-dev-only-do-not-override-ub2d98) is added to all classes. I think I will solve it with a small script that generates CSS variable files with token values, so I can use your file as the source of truth and generate files for other libraries. Thanks anyway.
