### ISSUE TITLE
5.x 版本的textarea 高度设置无效，初始化生效，页面宽度变动后直接变为height: auto;

### ISSUE THREAD

**Issue by made-02** [ant-design/ant-design#42846]
### Reproduction link

https://stackblitz.com/run?file=demo.tsx

### Steps to reproduce

只需点击demo右下角全屏展示图标调整demo示例的宽度，就可以看到原本设置的高度都失效了

### What is expected?

高度使用设置的宽度，保持不变

### What is actually happening?

页面宽度变化，textarea的高度就失效

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18 |
| System | mac |
| Browser | 113.0.5 |

**Comment by afc163** [comment]
请不要给内网链接。

**Comment by made-02** [comment]
> 请不要给内网链接。

好的，不好意思

**Comment by made-02** [comment]
> 

https://stackblitz.com/run?file=demo.tsx

**Comment by made-02** [comment]
> 你好@made-02.[请通过fork codesandbox的antd@5.x](https://u.ant.design/codesandbox-repro)或[antd@4.x](https://u.ant.design/codesandbox-repro-4x)提供在线复制，或提供最小的GitHub存储库。`Need Reproduce`如果3天内没有活动，标记为的问题将被关闭闭。
> 
> 你好@made-02, 我们需要你提供一个在线的重现实例以方便我们帮你排查问题。你可以通过点击这里创建一个antd@5.x或[antd@4.x](https://u.ant.design/codesandbox-repro)的[codesandbox](https://u.ant.design/codesandbox-repro-4x)，或提供一个最小化的 GitHub 库。 3天内未跟进此问题将被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647 563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://stackblitz.com/run?file=demo.tsx  只需加载完成后拖拽一下右边的demo面板宽度 textarea的高度就变为了auto

**Comment by afc163** [comment]
你给的例子貌似是空的。

**Comment by made-02** [comment]
> 你给的例子貌似是空的。

https://codesandbox.io/s/okw7xf 就文档内提供的textarea的demo就可以复现，只需加载完成后拖拽一下右边的demo面板宽度 textarea的高度就变为了auto

**Comment by coderStars** [comment]
> 

未能复现

**Comment by h1orz** [comment]
![image](https://github.com/ant-design/ant-design/assets/18734825/9b95b682-adb2-4fba-bc18-ddcebf6f4548)
左右拖动调整分栏宽度时，两个输入框的高度会变成auto，项目中也遇到了同样的问题，但表现不稳定，在form表单中会自动auto，在外部又没事...😂

**Comment by h1orz** [comment]
验证了下，Textarea未设置rows，通过style.height设置高度，布局发生变化时，Textarea会自动给textarea元素写入height:auto。

**Comment by coderStars** [comment]
![image](https://github.com/ant-design/ant-design/assets/39763302/b565bf98-cb3d-41ae-aefa-c322d3d5b189)
@h1orz 我拖动调整了分栏宽度，但是还是没复现啊？

**Comment by h1orz** [comment]
@coderStars https://codesandbox.io/s/okw7xf Demo示例中的height设置的是`120px`，`116px`是哪里设置的啊？
你的截图第二个`<textarea>`的`height`已经被写入`auto`了...

**Comment by made-02** [comment]
https://github.com/ant-design/ant-design/assets/56807957/5b9f92c3-1af4-4295-a4a0-5150ea1ab173

看一下我录制的重现视频，复现很简单的，只有页面有宽度变化了，高度秒变auto，链接地址 https://codesandbox.io/s/okw7xf  @afc163

**Comment by MadCcc** [comment]
Fixed in https://github.com/react-component/textarea/pull/43
It would be ok in 5.7.0, since `rc-textarea` v1.3.2 is on feature branch.
