### ISSUE TITLE
Datepicker calendar is showing Chinese

### ISSUE THREAD

**Issue by bnlambert** [ant-design/ant-design#4284]
Datepicker  showing Chinese by default instead of English. I have require and set `moment.locale('en')` to no avail.

Please help. thanks

#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by bnlambert** [comment]
I have added some come codes. Please take a look. Thanks

Boyong N. Lambert
Zend Certified Engineer

**Comment by afc163** [comment]
Add to where?

**Comment by bnlambert** [comment]
The link you sent me at code pen

Boyong N. Lambert
Zend Certified Engineer

**Comment by afc163** [comment]
You should modify and fork it to a new codepen, otherwise no one can see it than youself.

**Comment by anjikinnara** [comment]
try this
import { LocaleProvider } from 'antd';
import enUS from 'antd/lib/locale-provider/en_US';

wrap your App in <LocaleProvider locale={enUS}> </LocaleProvider>

**Comment by bnlambert** [comment]
Thank you for your response. I am using redux, how do I organize the `LocaleProvider` from `antd` and 'Provider' from `react-redux`?

Please be a little bit explicit, showing where and how to implement `LocaleProvider`

Thanks

**Comment by anjikinnara** [comment]
Localprovider takes a context. Can you try wrapping your redux provider in Localprovider and let me know. Thanks

**Comment by mdramos** [comment]
wow, thanks for this

**Comment by enzolutions** [comment]
@benjycui I see your example at http://codepen.io/benjycui/pen/KgPZrE?editors=001 and works there.

But doesn't work with Meteor (meteor.org), I read something you said related to webpack or similar, but I didn't understand.

Could you provide more information?

Best regards.

**Comment by benjycui** [comment]
Sorry, I am not familiar with Meteor.

If you want to localized DatePicker, TimePicker and Calendar, you need to do:
1. Use `antd.LocaleProvider`.
2. Use `moment.locale`, and you need to use `antd` as a npm package instead of a dist file.

**Comment by enzolutions** [comment]
Thanks @benjycui 

Couple questions to continue my research 

Moment.locale what package you mean is this https://www.npmjs.com/package/moment? I didn't find one sepecific

Kind regards

**Comment by benjycui** [comment]
@enzolutions right.

**Comment by enzolutions** [comment]
@benjycui I solved my issues in meteor after install https://github.com/ant-design/babel-plugin-import

create a .babelrc with the following content

```
{
  "plugins": [
    ["import", { "libraryName": "antd", "style": true }]
  ]
}
```

My code looks like

```
import 'antd/lib/locale-provider/style';

import locales from 'antd/lib/locale-provider/en_US';

<LocaleProvider locale={locales}>
  <Popconfirm title="Sure to delete?" onConfirm={() => this.onDelete(text,record, index)}>
    <a href="#">Delete</a>
  </Popconfirm>
</LocaleProvider>
```

Now all my components are rendering the proper language.
