### ISSUE TITLE
react-component/picker的pr等待处理

### ISSUE THREAD

**Issue by zerosrat** [ant-design/ant-design#42849]
### Reproduction link

[https://github.com/react-component/picker/pull/644](https://github.com/react-component/picker/pull/644)

### Steps to reproduce

https://github.com/react-component/picker/pull/644

### What is expected?

PR 被处理

### What is actually happening?

PR 被合入

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | ^17.0.0 |
| System | macos |
| Browser | latest |

**Comment by zerosrat** [comment]
@zombieJ 老哥康康 PR~
https://github.com/react-component/picker/pull/644

**Comment by afc163** [comment]
虽然确实有用，但不建议这样提 issue。
