### ISSUE TITLE
select的dropdownRender覆盖select无效

### ISSUE THREAD

**Issue by wq1308786830** [ant-design/ant-design#42850]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-roman-xfhrfj?file=/src/App.js)

### Steps to reproduce

在重现链接里点击select选择框

### What is expected?

下拉框dropdownRender覆盖select选框

### What is actually happening?

下拉框dropdownRender先覆盖select选框，然后闪一下又恢复到不覆盖的样式

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 16.8.6 |
| System | OSX |
| Browser | chrome |

**Comment by wq1308786830** [comment]
@afc163 大佬能看看嘛，试了几种方式都不行

**Comment by linxianxi** [comment]
为什么要设置 transform 呢。想设置偏移可以这样
```
dropdownAlign={{targetOffset: [0, 40]}}
```

**Comment by afc163** [comment]
See `dropdownAlign` https://github.com/react-component/select#select-props
