### ISSUE TITLE
Select的Option被Popover包裹时，点击Option内容，Select的选择器会自动关闭，阻止冒泡无效

### ISSUE THREAD

**Issue by laochake** [ant-design/ant-design#42854]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-01k3gt)

### Steps to reproduce

点击选项的Popover

### What is expected?

点击选项的Popover，不触发Select选择器关闭，或者可以阻止冒泡

### What is actually happening?

点击选项的Popover，会触发Select选择器关闭，阻止冒泡无效

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.2.0 |
| System | mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Select 失去焦点后关闭，和 `stopPop` 没有关系。复杂场景建议直接受控：
https://codesandbox.io/s/antd-reproduction-template-forked-leykfs?file=/index.tsx
