### ISSUE TITLE
inputNumber drag 扩展

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#42869]
### What problem does this feature solve?

参考 sketch 的输入框，不要点右侧 icon 就 focus 输入框，icon 只在 hover 状态出现，，这样 inputNumber 也可以加 suffix，，可以扩展 suffix 的拖动来增加减少。。这功能在编辑器里还是比较实用的，，比那点击吊 icon 效率要高很多。。

### What does the proposed API look like?

icon 出现状态可设 handlerShow: 'hover' | 'focus' ｜ 'all'， 增加 suffix、suffixDrag 和 prefixDrag

![Kapture 2023-06-06 at 20 40 59](https://github.com/ant-design/ant-design/assets/6802825/5b17f410-a972-41ae-9d04-a42f2d25a31b)

**Comment by afc163** [comment]
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
