### ISSUE TITLE
datepicker在开启showtime后，无法通过inputReadOnly阻止输入触发onChange

### ISSUE THREAD

**Issue by holmesliang** [ant-design/ant-design#42864]
### Reproduction link

[https://stackblitz.com/edit/react-8jvtm3?file=index.js](https://stackblitz.com/edit/react-8jvtm3?file=index.js)

### Steps to reproduce

点击第一个datepicker组件，先选择一个日期，然后通过弹框修改时间，可以看到控制台打印了修改的时间

### What is expected?

设置inputReadOnly后 输入不触发onChange

### What is actually happening?

设置inputReadOnly后 输入后触发onChange

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | mac |
| Browser | 谷歌版本 108.0.5359.98 |

---
antd版本为3.26.20

**Comment by MadCcc** [comment]
3.26.20 已经过了维护期了，不会再 patch 了
