### ISSUE TITLE
InputNumber与Input disable的样式不统一

### ISSUE THREAD

**Issue by sansheng741** [ant-design/ant-design#42878]
### Reproduction link

[https://codepen.io/sansheng741/pen/rNQNzdM?editors=0010](https://codepen.io/sansheng741/pen/rNQNzdM?editors=0010)

### Steps to reproduce

给InputNumber与Input添加前缀或者后缀和disabled=true，两个组件展现出来的样式不一致，InputNumber组件前后缀会高亮而Input组件不会。

### What is expected?

InputNumber的前后缀在添加disabled=true属性后，取消高亮

### What is actually happening?

InputNumber组件前后缀会高亮而Input组件不会

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18 |
| System | window10 |
| Browser | Google Chrome 114.0.5735.90 |

**Comment by vitalijalbu** [comment]
would be fine add also clear icon
