### ISSUE TITLE
select 下拉选择的时候,支持拿到原始每项数据的所有信息

### ISSUE THREAD

**Issue by Sophil-minn** [ant-design/ant-design#42871]
### What problem does this feature solve?

问题一:  
    是如果我的options的每一项不止有label和value,还有其他字段,比如:如下

```
 [{
    deptName: "雪山之王",
    extProperty: {
      deptName: "大猫"
    },
    id: "0111111",
    outUserNo: "111111",
    realName: "雪山之王",
    tntInstId: "",
    userChannel: "motain",
    label: " 雪豹",
    value: "snow lepoard"
  }]
```
如果直接select去选择,选中上面的选项会发现最终的结果只拿到了 

```
   [{ label: " 雪豹", value: "snow lepoard"}]
```

自己想要拿到原始值,却发现除了value和label其他都丢失了

### What does the proposed API look like?

如果直接select去选择,选中上面的选项,期望最终的结果拿到是原始值,如

```
[{
    deptName: "雪山之王",
    extProperty: {
      deptName: "大猫"
    },
    id: "0111111",
    outUserNo: "111111",
    realName: "雪山之王",
    tntInstId: "",
    userChannel: "motain",
    label: " 雪豹",
    value: "snow lepoard"
  }]

```

并不是上面所说的只拿到了 value和label部分的值,其他字段的信息都丢失了

**Comment by BoyYangzai** [comment]
@Sophil-minn 
标题有错别字 下拉 可以编辑一下

**Comment by linxianxi** [comment]
组件内部只取 label 和 value 的，你想要全部信息拿 value 去数组里 find 一下不就好了？

**Comment by Sophil-minn** [comment]
如果拿 value 去数组里 find 一下能搞定，我就不需要提这个需求了，复现问题demo: https://codesandbox.io/s/ji-ben-yong-fa-antd-5-5-2-forked-6f4zej?file=/demo.tsx
远程搜索数据的时候，这个行不通，所以我给提了PR

**Comment by linxianxi** [comment]
没看懂，要提供一下复现步骤。而且你这 pr 不是只加了 demo？

**Comment by Sophil-minn** [comment]
你可以试试这个复现demo: https://codesandbox.io/s/ji-ben-yong-fa-antd-5-5-2-forked-wkk0w8?file=/demo.tsx:3079-3082
如果有已有选中的数据回填过，再选择的时候 ，会发现这个bug

**Comment by linxianxi** [comment]
你一开始没设置 options，只设置了 value。
<img width="635" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/58160a6a-9f83-4b50-811d-2540e258470c">

**Comment by Sophil-minn** [comment]
> 你一开始没设置 options，只设置了 value。这样就行了 <img alt="image" width="635" src="https://user-images.githubusercontent.com/47104575/243885609-58160a6a-9f83-4b50-811d-2540e258470c.png">

但是你用使用远程接口请求options时，就会有问题，这个bug太隐蔽了，谁看都是没问题的，但是真正复杂业务场景里只有用到的时候才知道痛点在哪里，你可以看下这个复现 ： https://codesandbox.io/s/ji-ben-yong-fa-antd-5-5-2-forked-wkk0w8?file=/demo.tsx，仔细才会发现这个问题
