### ISSUE TITLE
Collapse with items still warns "`children` will be removed in next major version. Please use `items` instead."

### ISSUE THREAD

**Issue by DercilioFontes** [ant-design/ant-design#42873]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0dnf3d)

### Steps to reproduce

See code sandbox. 

```typescript
const items = [
  { key: "1", label: "1", children: <div>Child 1</div> },
  { key: "2", label: "2", children: <div>Child 2</div> }
];
...
<Collapse items={items} />
```

### What is expected?

To not show the warning when using items

### What is actually happening?

It is logging the warning:
```
Warning: `children` will be removed in next major version. Please use `items` instead.
```

| Environment | Info |
| --- | --- |
| antd | 5.6.0 |
| React | 18.2.0 |
| System | macOS Ventura 13.3.1 |
| Browser | Chrome Version 115.0.5762.4 (Official Build) dev (arm64) |

**Comment by periplox** [comment]
+1

**Comment by lyndonliu89757** [comment]
Still having this issue with v5.8.5. Using Tab also triggers the warning. @kiner-tang

**Comment by DiHand79** [comment]
I move my "children" element to items BUT now have crash & next err (before all good work instead Error future less support 'children')
new err: react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.

And I cant solve this - sample my code problem area :

const DrawStep = async (
    selectedProc,
    setStepJSX,
    onRemoveStep,
    moveStep,
    StepIcon,
    onAddStep
  ) => {
    let stepObj = [];
    if (selectedProc?.steps && selectedProc.steps.length > 0) {
      stepObj = selectedProc.steps.map((step, i) => {
        const title = (
          <>
            <TitleStep
              // key={Math.random() + '_' + Date.now()}
              i={i}
              step={step}
              onRemoveStep={onRemoveStep}
              moveStep={moveStep}
              onClick={(e) => console.log(e)}
              onChangeOpenSteps={onChangeOpenSteps}
            />
            <h5 style={{ marginLeft: '50px' }}>
              {`Substeps: ${step?.steps.length} ` +
                expandTitle +
                ' №' +
                selectedStepId}
            </h5>
            {openedSteps.includes(i) && (
              <>
                {step.steps.map((substep, i) => {
                  const id = `step_${selectedStepId + 1}_${i}`;
                  return (
                    <SubstepsGenerate
                      key={id}
                      id={id}
                      step={step}
                      substep={substep}
                      onUpdateSubsteps={() => console.log('Update Substep')}
                      addSubstep={() =>
                        console.log('Add Substep. TODO - send to server & CRUD')
                      }
                    />
                  );
                })}
              </>
            )}

            <h5 style={{ marginLeft: '50px' }}>
              {`Routines: ${step?.routines.length} ` +
                expandTitle +
                ' №' +
                selectedStepId}
            </h5>
            {openedSteps.includes(i) && (
              <>
                {step.routines.map((routine, i) => {
                  const id = `routine_${selectedStepId + 1}_${i}`;
                  return (
                    <RoutinesGenerate
                      key={id}
                      id={id}
                      step={step}
                      routine={routine}
                      onUpdateRoutines={() => console.log('Update Routine')}
                      addRoutine={() =>
                        console.log('Add Routine. TODO )
                      }
                    />
                  );
                })}
              </>
            )}
          </>
        );

        const icon = (
          <StepIcon
            key={step.seId + '_' + i + '_' + Date.now()}
            step={i + 1}
            class={'step-icon-circle white'}
          />
        );

        console.log('step.seId: ', step.seId); // work
        return new Object({
          // key: step.seId,
          title,
          icon,
          description: <>test description</>,
        });
      });
    }

    // add last BLUE button - +ADD STEP
    stepObj.push(
      new Object({
        // key: 'plus_' + selectedProc.steps?.length + 1 || 0,
        title: <PlusStep onAddStep={onAddStep} />,
        icon: (
          <PlusOutlined
            className='step-icon-circle blue step'
            onClick={onAddStep}
          />
        ),
        description: <>test + description</>,
      })
    );
    console.log('stepObj: ', stepObj); // work
    setStepJSX(stepObj);
  };

  const StepIcon = (props) => {
    let classList = props.class;
    let textContent = 'STEP\n' + props.step;

    return <div className={classList}>{textContent}</div>;
  };

  return (
    <Col xs={24}>
      <Steps
        key={Math.random() + Date.now()}
        direction='vertical'
        current={selectedProc?.steps?.length || 0} 
        labelPlacement='vertical'
        items={[...stepsJSX]}
      />
    </Col>
  );
