### ISSUE TITLE
Table中使用Icon导致鼠标hover样式错位，与#4197错误类似

### ISSUE THREAD

**Issue by yimi8126** [ant-design/ant-design#4287]
#### 发生问题的环境是：

- antd 版本:最新版本
- 操作系统及其版本:mac 
- 浏览器及其版本:chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

Table组件中Column中使用了Icon组件

#### 实际上的结果是:

使用的Icon哪行没有hover
第三行整行没有hover

#### 可重现的在线演示

http://codepen.io/yimi8126/pen/WoPoEo?editors=001

**Comment by RaoHai** [comment]
+ #4197

**Comment by yimi8126** [comment]
之前一直都是好的，自从某次升级以后就变了

**Comment by benjycui** [comment]
Another https://github.com/ant-design/ant-design/issues/3948

这个 demo 在 Chrome 金丝雀版和 Firefox 下面都没有问题。

感觉 antd 也做不了什么。

**Comment by afc163** [comment]
Mac + Chrome 55.0.2883.95 下没有重现。
