### ISSUE TITLE
点击 Modal 内的任意地方，会冒泡到外面

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#42891]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-6-0-forked-59tzg3)

### Steps to reproduce

1、点击 Modal 内的任意地方
2、查看控制台打印了 click

### What is expected?

不打印 click

### What is actually happening?

打印 click

| Environment | Info |
| --- | --- |
| antd | 5.6.0 |
| React | lastest |
| System | mac |
| Browser | chrome |

---
改 Image 组件发现的。应该要在底层解决下？我看了下很多地方都是用了 pointer-events: none 和 auto

**Comment by afc163** [comment]
问题是啥？默认冒泡不是对的么？

**Comment by linxianxi** [comment]
> 问题是啥？默认冒泡不是对的么？

如果 Modal 后面正好有个按钮什么的，点击 Modal 里面对应这个按钮的位置，不是就触发那个按钮的事件了么

**Comment by linxianxi** [comment]
试了下，确实不会。就最外面的 div 会

**Comment by JunyWuuuu91** [comment]
确实，是自己写的最外层元素冒泡的问题，自己写一个阻止冒泡就完事了
