### ISSUE TITLE
如何贡献英文文档

### ISSUE THREAD

**Issue by magicshui** [ant-design/ant-design#429]
由于团队中有外国人，为了帮助他们更好的使用，所以希望能够帮助贡献英文的文档，希望了解下对于这个项目怎么来执行？

**Comment by afc163** [comment]
目前没有多语言文档的工程化方案，可以先行 fork 修改。

或者帮忙实现多语言文档的工程化。

**Comment by benjycui** [comment]
又或者只提供英文文档

**Comment by afc163** [comment]
英文文档需求还是有的：#403 #359

如果后面腾出时间，可以考虑文档的多语言版本。

**Comment by yubozhao** [comment]
如有需要我可以帮忙。

**Comment by afc163** [comment]
same as #359

**Comment by benjycui** [comment]
@magicshui @yubozhao trace https://github.com/ant-design/ant-design/issues/1471

团队中有外国人的话，可以麻烦他们帮忙 review 译文么？

**Comment by magicshui** [comment]
没有问题，我@他们一下

**Comment by yubozhao** [comment]
好的。我今天review
