### ISSUE TITLE
badge 不能正确显示

### ISSUE THREAD

**Issue by yitengruntu** [ant-design/ant-design#4290]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: Windows 10.0.14393
- 浏览器及其版本: Chrome 55.0.2883.87 m

![11482124630_ pic_hd](https://cloud.githubusercontent.com/assets/12508042/21302165/771b9bde-c5ef-11e6-907d-debac2379fc3.jpg)
无法正常显示badge

**Comment by ddcat1115** [comment]
确定浏览器没有缩放？

**Comment by yitengruntu** [comment]
@ddcat1115 浏览器没有缩放 但是刚才我尝试“更改文本、应用和其他项目的大小” 从125%至100%，显示就正常了，可是现在基本win10用户都会设置为推荐的125%，请问有什么解决办法么
![41482130774_ pic_hd](https://cloud.githubusercontent.com/assets/12508042/21303835/3a79592a-c5fc-11e6-8df8-502bbe02104b.jpg)

**Comment by benjycui** [comment]
relative: https://github.com/ant-design/ant-design/issues/4176

或者 Badge 需要动态获取宽高？

**Comment by afc163** [comment]
可以有，能用纯样式解决最好。现在高度在 js 里写死了。

**Comment by benjycui** [comment]
想了下，现阶段还是要 hard code。

1. 用 JS 动态获取元素高度，不支持 SSR。
1. 用 em 而非 px 定义高度，不兼容 <=IE9。

ref: https://github.com/ant-design/ant-design/blob/588f0c3d1c9164986b82274a52c9ac5deca43d87/components/badge/ScrollNumber.tsx#L106-L121

**Comment by benjycui** [comment]
@yitengruntu 这种系统默认缩放的问题，感觉现阶段无解。。

**Comment by yitengruntu** [comment]
@benjycui 可是这种情况只发生在chrome里 国产双核浏览器，ie和ie edge都没有问题

**Comment by benjycui** [comment]
不清楚这个的行为逻辑是怎么样的，但是出错的情况来看，就是只放大了文字。

![image](https://cloud.githubusercontent.com/assets/3580607/21445099/de39cbe4-c8ef-11e6-945e-0ac451db87e7.png)

**Comment by benjycui** [comment]
有更多信息时再打开吧，没有环境不好搞。
