### ISSUE TITLE
Is it possible to make antd's Space item contain classname individually?

### ISSUE THREAD

**Issue by LizaMaharjan2001** [ant-design/ant-design#42919]
### What problem does this feature solve?

[after 5.6.0" review]
This feature could be best when you want to add class name to a specific child only. Eg: first child, last child, or any other child just like Form.Item.
The recent updated version of 5.6.0" allows you to add classnames and styles that gives the classes and styles to all the space child inside it.

### What does the proposed API look like?

```
<Space>
   <Space.Item className="first-child"> .... </Space.Item>     //different classname
   <Space.Item className="other-child"> .... </Space.Item>     //some other classname to only this child
</Space>
```

**Comment by Wxh16144** [comment]
It's not easy to implement, another `Space.Item` is a bit complicated, and it may not be easy for developers to use, because in the current implementation, Space filters empty child elements. It is not possible to get the correct order of child elements.

**Comment by RedJue** [comment]
You can solve this problem with the css pseudo-class selector, like `.custom-classname:nth-child(x)`.

**Comment by afc163** [comment]
Why not adding className to children itself?

```
<Space>
  <span className="first-child"></span>
  <Button className="other-child"></Button>
</Space>
```

**Comment by monolithed** [comment]
> Why not adding className to children itself?
> 
> ```
> <Space>
>   <span className="first-child"></span>
>   <Button className="other-child"></Button>
> </Space>
> ```

@afc163, perhaps this would be a useful option at least for managing adaptability.
In my case, setting `width: 100%` on the parent element has no effect because the parent does not have a fixed width, and to fix this, I have to adjust the internal styles of the component (`.ant-space-item`) or even abandon the use of 'Space' altogether.


```
.buttons :global(.ant-space-item) {
        width: 100%;
}
```

```tsx
<Space className={styles.buttons} wrap={true}>
    <Button block={true}>Wide button</Button>
    <Button>Narrow button</Button>
</Space>
```

**Comment by afc163** [comment]
I don't find any necessity using Space in this case, it completely override Space default styles.
