### ISSUE TITLE
Improve docs of Option of Select

### ISSUE THREAD

**Issue by Naggertooth** [ant-design/ant-design#42913]
### What problem does this feature solve?

https://ant.design/components/select?theme=dark#option-props

I guess it needs improvement

Hi, i am using select with mode multiple and options with only "key" property
Guess "value" property in this case inherits from "key" property
It is not documented but it lets me skip one row duplication

### What does the proposed API look like?

Dev expirience

**Comment by zombieJ** [comment]
Do not deps on `key`. It's compatible for legacy usage in old version of antd and just no remove the logic to avoid breaking change. In v5 it's recommend to use `options` instead of jsx structure. You will find that most of the Demo is `options` style.
