### ISSUE TITLE
Want To Deselect the Radio Button When I Reclick on Selected Radio Button

### ISSUE THREAD

**Issue by osamajavaid** [ant-design/ant-design#42925]
### What problem does this feature solve?

like checkox, it can select and unselect both, i.e on clicking the same checkbox. 
I tried every possible solution to achieve this.....ended up making another button to unselect all radio button. But i want to delesect on reclick the same button, i dont know how

### What does the proposed API look like?

possible solution:
An Extra prop should added to radio component, which allows us the control on select and deselect

**Comment by linxianxi** [comment]
I think we should follow the rules of native radio  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

**Comment by osamajavaid** [comment]
> Acutally all radio buttons works on same phenomena, i.e they can only be deselect when we select other radio button not on reclicking the same radio button....simply, here i want CheckBox like functionality but using radio buttons

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7182#issuecomment-321781572
