### ISSUE TITLE
[Dropdown   Tree]  Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by rhumbertgz** [ant-design/ant-design#42926]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/sweet-booth-wvvrqp)

### Steps to reproduce

1. Open the codesandbox example
2. Open your browser console and you will observe the warning error 

### What is expected?

No warning error

### What is actually happening?

After open the demo and check the console see the following  error:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Tree4 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
div
Tree4@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:69451:20
Tree2<@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:70878:31
DirectoryTree@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:71068:7
TriggerWrapper<@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:17800:18
DomWrapper4@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:1529:20
SingleObserver@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:1572:18
ResizeObserver3@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:1649:18
generateTrigger/Trigger<@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:17820:28
Dropdown@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:24727:22
Dropdown2@https://wvvrqp-5174.csb.app/node_modules/.vite/deps/antd.js?v=9162b410:28448:7
App preview-protocol.js:13:11232
```

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.0 |
| System | MacOS 13.4 (22F66) |
| Browser | Safari 16.5 / Chrome 114.0.5735.90  / Firefox 114.0 (64-bit) |

---
Everything else works perfect besides the warning error. I tried multiple browsers and I'm using the latest version of antd and react and the error is still there. I have found previous submitted bugs for the same warning for older version of andt, there was no solution and the error keeps showing in the latest version of antd

![Screenshot 2023-06-08 at 11 54 08](https://github.com/ant-design/ant-design/assets/10393245/c720189e-ef7d-448e-9d9f-ade394e025b1)
![Screenshot 2023-06-08 at 11 46 07](https://github.com/ant-design/ant-design/assets/10393245/519036c7-3552-4bd2-9d5b-7a54fc859886)
![Screenshot 2023-06-08 at 11 45 14](https://github.com/ant-design/ant-design/assets/10393245/056cf095-2e8c-4d46-89da-5cd6363c9b72)

**Comment by Deer404** [comment]
i have same console error too

**Comment by ybf970928** [comment]
when using react 18.3.0 or 19 , also have same console error

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/48709

**Comment by shamseer-ahammed** [comment]
+1
