### ISSUE TITLE
dva new dva-quickstart 按照报错，导致npm start运行不起来

### ISSUE THREAD

**Issue by OliveKong** [ant-design/ant-design#4292]
![image](https://cloud.githubusercontent.com/assets/7875818/21303085/d4a2663c-c5f6-11e6-9fba-a545790333a5.png)
请问知道这是什么意思吗？
下图是npm start运行后的错误提示
![image](https://cloud.githubusercontent.com/assets/7875818/21303116/05ec1e90-c5f7-11e6-8ce3-23b0f59f74b1.png)

**Comment by RaoHai** [comment]
dva 的问题请到 dva 问。。谢谢 :D
