### ISSUE TITLE
antd 4.x中的tooltip，箭头和主体中间有空隙

### ISSUE THREAD

**Issue by lovekonakona** [ant-design/ant-design#42921]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/tooltip-cn/](https://4x-ant-design.antgroup.com/components/tooltip-cn/)

### Steps to reproduce

1. 使用特定电脑和浏览器，打开上述网站
2. 鼠标移动到指定内容上，查看黑色的Tooltip展示出来

### What is expected?

箭头和主体没有分离

### What is actually happening?

箭头和主体有分离

![Screenshot](https://img.alicdn.com/imgextra/i3/O1CN01sf1xmT1icMbW6y0Ds_!!6000000004433-0-tps-1276-956.jpg)

| Environment | Info |
| --- | --- |
| antd | 4.22.4 |
| React | 18.x |
| System | 系统版本Windows10企业版LTSC |
| Browser | Chrome 版本 114.0.5735.110（正式版本） （64 位） |

**Comment by coderStars** [comment]
ok，I test lastest version，this problom still exit. I'll fix it.

**Comment by zombieJ** [comment]
是不是屏幕设置是 125%?

**Comment by zombieJ** [comment]
这个 windows 下不太好解，缩放后游览器拿到的值已经是变化过的了，所以贴边数值是不对的。

**Comment by afc163** [comment]
Trace #46094
