### ISSUE TITLE
Table does not respect column width on limiting container width after upgrading from 4.10.0 to 4.18.0

### ISSUE THREAD

**Issue by sambhav2612** [ant-design/ant-design#42931]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-table-4-18-0-mp5pvx?file=/src/App.js:847-903)

### Steps to reproduce

Above reproduction is based on antd 4.18.0 after upgrading from 4.10.0. Same reproduction for 4.10.0 is here: https://codesandbox.io/s/antd-table-4-10-0-cmpr22?file=/src/App.js 

### What is expected?

Both have been limited by setting container max width to 400px however the earlier version respects min width because it sets a `min-width` attribute in ColGroup styling which was removed by rc-table team (https://github.com/react-component/table/pull/626) in 7.15.x release (antd 4.18.0 depends on rc-table @7.21.0)

### What is actually happening?

antd 4.18.0 table does not have respect width under large column structure or smaller render window to force per column width if set via `columns` prop. Like so:

### @4.10.0:
![image](https://github.com/ant-design/ant-design/assets/19583619/88e10a93-0df5-422e-8283-5f7df317c63d)
![image](https://github.com/ant-design/ant-design/assets/19583619/0cc18cfa-7981-4b4b-8990-7ffd23506db1)

### @4.18.0:
![image](https://github.com/ant-design/ant-design/assets/19583619/e0ba8ff7-ed3b-4cd1-ab16-04f6e50eb430)
![image](https://github.com/ant-design/ant-design/assets/19583619/de651e3a-ffd3-41b2-ba28-d56c54304ae4)

| Environment | Info |
| --- | --- |
| antd | 4.18.0 |
| React | 18.2.0 |
| System | macOS 13 |
| Browser | Brave |

---
Any alternative approach without setting peer dependency (rc-table) under 7.15.x

PS. Upgrading to 4.10.0 fixed https://github.com/ant-design/ant-design/issues/42773

**Comment by sambhav2612** [comment]
@afc163

**Comment by zombieJ** [comment]
> @sambhav2612 Hi bro,I think you are right. The wrong layout is beacuse of `table-layout:'auto'`, but we need the `min-width` to limit it's width sometimes You can temporarily fix it by `ClassName` waiting for the antd team deciding how to fix this problem https://codesandbox.io/s/antd-table-4-18-0-forked-2dv3kr?file=/src/styles.css
> 
> the reson why rm it ref #30755

Follow @BoyYangzai 's reply. Table removed `fixed` by default. It will auto response to Table current width as native table behavior. You can force width with `tableLayout`:

https://codesandbox.io/s/antd-table-4-18-0-forked-w6kqw3?file=/src/App.js
