### ISSUE TITLE
Select 自定义下拉面板, 当点击面板中的按钮+号时,  会丢失 搜索值

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#42933]
### Reproduction link

[https://stackblitz.com/edit/react-djm2de?file=demo.tsx](https://stackblitz.com/edit/react-djm2de?file=demo.tsx)

https://stackblitz.com/edit/react-13vdsn?file=demo.tsx

### Steps to reproduce

输入  1, 然后点击 下拉面板中的  号

### What is expected?

点击 号, 不要清空搜索值

### What is actually happening?

点击 号, 搜索值被清空了

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by linxianxi** [comment]
这个挺怪，搜索有值时，点击按钮没反应🤔️

**Comment by vaynevayne** [comment]
会不会这个问题和自动关闭popover的issue是同一个原因

**Comment by Ali-ovo** [comment]
你可以通过配置 `searchValue，onSearch` 这两个API来达成 `受控的输入框`，这样在你点击的时候 输入框的值可以不会被清空。

**Comment by linxianxi** [comment]
> 会不会这个问题和自动关闭popover的issue是同一个原因

点击任意地方，会清空值，也是要用受控来解决。但是搜索有值时点击按钮没触发点击事件是个问题

**Comment by linxianxi** [comment]
@zombieJ 是有 bug，点击 dropdownRender 除了 menu 以外的地方都会触发 onDropdownVisibleChange false，按理说是不应该触发的。搜索有值时点击这个 + 号也不会触发 click

**Comment by zombieJ** [comment]
有几点：
* 点击关闭是因为失去焦点，case 1 `preventDefault` 放错位置了: https://stackblitz.com/edit/react-djm2de-7yvdju?file=demo.tsx
* `searchText` 在失去焦点时会重置，`autoClearSearchValue` 意思是输入框聚焦时无论选择什么都会保留输入框里的值。所以它才说明是 `mode` 为多选时才会生效。
* 始终保持 `searchText` 参考 @Ali-ovo 的回复，受控即可。

**Comment by zombieJ** [comment]
> @zombieJ 是有 bug，点击 dropdownRender 除了 menu 以外的地方都会触发 onDropdownVisibleChange false，按理说是不应该触发的。搜索有值时点击这个 + 号也不会触发 click

从无障碍设计角度出发 Select 是失去焦点后关闭，只要 `preventDefault` 不丢失焦点即可。如果是下拉还带需要焦点的元素如输入框，则需要自行受控处理：https://ant-design.antgroup.com/components/select-cn#faq

**Comment by vaynevayne** [comment]
> 
你们代码里目前是: 失去input 的焦点, 而实际上需要修正为失去 dropdown 的焦点, 试想如果失去 input 就关闭,那点击 option 岂不是应该关闭, 那为什么不关闭呢

**Comment by zombieJ** [comment]
dropdown 没有焦点，option 点击不会失去焦点。
