### ISSUE TITLE
大于5.5.x， dropdown在shadowdom中点击空白处无法关闭

### ISSUE THREAD

**Issue by luokebi** [ant-design/ant-design#42936]
### Reproduction link

[https://stackblitz.com/edit/react-c8ww4r-zh2eiv?file=demo.tsx](https://stackblitz.com/edit/react-c8ww4r-zh2eiv?file=demo.tsx)

### Steps to reproduce

https://stackblitz.com/edit/react-c8ww4r-zh2eiv?file=demo.tsx

### What is expected?

点击空白处dropdown关闭

### What is actually happening?

点击空白处dropdown不关闭

| Environment | Info |
| --- | --- |
| antd | 5.6.0 |
| React | 18.2.0 |
| System | Macos 13.4 |
| Browser | Chrome 114 |

---
5.4.7正常

**Comment by BoyYangzai** [comment]
@luokebi shadowdom导致这里事件挂载的有些问题
如果比较急的话可以先手动挂在一下
https://stackblitz.com/edit/react-c8ww4r-n2uqe7?file=index.tsx,demo.tsx,index.html,index.css

**Comment by zombieJ** [comment]
`clickInside` 检测同时触发导致其中一个 true 把另一个盖住了：

<img width="665" alt="截屏2023-06-12 19 05 51" src="https://github.com/ant-design/ant-design/assets/5378891/b276986b-6ae2-4d61-8052-0624da2ba936">
