### ISSUE TITLE
你好，Table组件的列可以拖拽吗

### ISSUE THREAD

**Issue by leesx** [ant-design/ant-design#4293]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4139

https://github.com/ant-design/ant-design/search?utf8=%E2%9C%93&q=%E5%88%97+%E6%8B%96%E6%8B%BD&type=Issues
