### ISSUE TITLE
Button在disabled状态下无法阻止子组件的链接跳转

### ISSUE THREAD

**Issue by MorningK** [ant-design/ant-design#42948]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bu-ke-yong-zhuang-tai-antd-5-6-0-forked-c8672m?file=/demo.tsx)

### Steps to reproduce

v5版本中，在Button内部使用跳转，比如`a`组件或者`react-router`的`Link`组件，设置Button的disabled属性为true时，无法阻止点击按钮后链接跳转。
```
<Button disabled>
  <a href="https://ant.design/">链接跳转</a>
</Button>
```
在v4版本，是可以正常阻止点击后跳转
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bu-ke-yong-zhuang-tai-antd-4-24-10-forked-24qzr5?file=/demo.tsx:142-214)

### What is expected?

Button在disabled状态下，点击后不会进行页面跳转

### What is actually happening?

Button在disabled状态下，点击后进行了页面跳转

| Environment | Info |
| --- | --- |
| antd | 5.6.0 |
| React | 18 |
| System | MacOS |
| Browser | chrome 114 |

---
使用Button的href属性是能够正常阻止跳转的，但是在结合`react-router`使用时，通过Button的href进行直接跳转有时会遇到其他的问题

**Comment by kiner-tang** [comment]
为什么要这么用呢？Button 本身就可以指定 href 属性用于跳转页面的

**Comment by kiner-tang** [comment]
不过这确实是个问题，如果按钮禁用，按钮的子元素应该也不能点击才对，我看看

**Comment by MorningK** [comment]
>> 使用Button的href属性是能够正常阻止跳转的，但是在结合react-router使用时，通过Button的href进行直接跳转有时会遇到其他的问题

> 为什么要这么用呢？Button 本身就可以指定 href 属性用于跳转页面的

我在描述里已经简单说明了原因。更加具体的情况是，我们在项目里使用了react-router v5的Prompt组件在表单页对用户未保存就离开页面的情况下进行二次确认的提示，如果直接使用Button的href属性跳转到这个表单页，那么在用户点击返回上一级页面的时候会无法触发这个提示，所以有些情况下我们无法直接使用Button的href属性来进行跳转。

**Comment by afc163** [comment]
```jsx
<a href="https://ant.design/">
<Button disabled>
  链接跳转
</Button>
</a>
```

**Comment by kiner-tang** [comment]
> ```js
> <a href="https://ant.design/">
> <Button disabled>
>   链接跳转
> </Button>
> </a>
> ```

这种方式目前也是有问题的，点击依然会跳转：https://codesandbox.io/s/bu-ke-yong-zhuang-tai-antd-5-6-0-forked-gxrwyh?file=/demo.tsx

**Comment by afc163** [comment]
另外，Button 里放链接之前在 Firefox 下是有问题的，现在我测了一下貌似可以了。https://github.com/ant-design/ant-design/issues/1108#issuecomment-451418892

https://stackoverflow.com/questions/16280684/nesting-a-inside-button-doesnt-work-in-firefox
