### ISSUE TITLE
setFieldsValue method triggers a TypeScript type check error with optional fields

### ISSUE THREAD

**Issue by yuki2006** [ant-design/ant-design#42941]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dank-bash-y54mhx?file=/src/Login.tsx:371-385)

### Steps to reproduce

Define a type with optional nested fields as follows:

```
type Values = {
  first?: {
    second: string;
    third: string;
  };
};
```

* Instantiate a form using the useForm<Values>() hook.

* Try to use the setFieldsValue method to update the 'second' field without specifying the 'third' field.
* A TypeScript error is triggered, stating: 

```
"Property 'third' is missing in type '{ second: string; }' but required in type '{ second: string; third: string; }'."
```

However, it should be noted that this error does not occur when using a different set of values (for example, Values2).

```
type Values2 = {
  first: {
    second: string;
    third: string;
  };
};
```

### What is expected?

The setFieldsValue method should allow the updating of values without requiring all fields inside an optional field to be specified.

### What is actually happening?

When using setFieldsValue method with optional nested fields, TypeScript requires the specification of all fields inside the optional field, which should not be necessary, leading to a type error.

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.0 |
| System | mac os 13.4 |
| Browser | Chrome 113.0.5672.126 |

---
This issue interferes with the flexibility and convenience of form handling, as it requires all fields within an optional field to be specified unnecessarily. This does not align with the nature of optional fields in TypeScript, and ideally, it should be possible to specify only some fields within an optional object without any issues.

**Comment by kiner-tang** [comment]
@yuki2006 You can fix this problem by reinstalling the dependencies now!

**Comment by TomasTarasovic** [comment]
@kiner-tang please could you fix this issue also for ant v4? We are using ant 4.24.3 version and we have the same problem mentioned on this thread.

**Comment by jeannnemelanie** [comment]
The issue stil exists with `unknown`:

```ts
type FormValues = Record<string, unknown>;

const [form] = Form.useForm<FormValues>();

const initValues: FormValues = { field1: "" };

form.setFieldsValue(initValues);
```

Gives the error:

> Argument of type 'FormValues' is not assignable to parameter of type '{ [x: string]: {}[] | undefined; }'.
>   'string' index signatures are incompatible.
>     Type 'null' is not assignable to type '{}[] | undefined'.ts(2345)
