### ISSUE TITLE
v5.x 打包后useBreakpoint报错Cannot read properties of undefined (reading 'useBreakpoint')

### ISSUE THREAD

**Issue by gouqingping** [ant-design/ant-design#42940]
### Reproduction link

[http://localhost:8099/](http://localhost:8099/)

### Steps to reproduce

vite build

### What is expected?

无报错正常加载

### What is actually happening?

Uncaught TypeError: Cannot read properties of undefined (reading 'useBreakpoint')

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by BoyYangzai** [comment]
@gouqingping 
你的链接是个本地链接 无法查看
可以上传一个复现的Github仓库

**Comment by gouqingping** [comment]
> Hello @gouqingping. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @gouqingping, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

只需要启动一个react18以及antd v5.6.0 和antd pro v2.5.5 然后随便调用几个组件打包后运行控制台就会报错

**Comment by BoyYangzai** [comment]
@gouqingping 
这个原因可能不好说 目前没人反馈过这个问题 更像是个例
包括 Vite 打包器的配置 版本 环境的一系列原因 可能难以复现
建议把有问题的项目直接传到 Github 保证我们这边可以获得和你一样的项目打包配置

**Comment by gouqingping** [comment]
> @gouqingping
> 这个原因可能不好说 目前没人反馈过这个问题 更像是个例
> 包括 Vite 打包器的配置 版本 环境的一系列原因 可能难以复现
> 建议把有问题的项目直接传到 Github 保证我们这边可以获得和你一样的项目打包配置

好的，我晚点上传一个demo

**Comment by gouqingping** [comment]
@BoyYangzai  上传到了这个仓库，使用 yarn install 后然后执行yarn build，然后将这个demo 打包成docker镜像 
https://github.com/gouqingping/antd-react-templete

**Comment by BoyYangzai** [comment]
@gouqingping 
你的 demo 没办法直接 build 会报错 我改了一下成功启动了 
本地 dev 的时候没问题 build之后 preview报错了 但是和你的错误不太一样 但也是antd的 找不到xxx
我排查了一下 
你的 `rollupOptions` 这个地方应该是有问题的 
你本地注释掉 重新build+preview试试 如果报错就可以锁定在这里了
我这里注释掉之后没报错了
![image](https://github.com/ant-design/ant-design/assets/94534613/25ac0f81-f852-4d15-b0a5-6562368d39ef)

**Comment by gouqingping** [comment]
是我环境问题

**Comment by BoyYangzai** [comment]
> 是我环境问题

👌

**Comment by gouqingping** [comment]
@BoyYangzai  我刚才也排查出了这个问题  很尴尬

**Comment by BoyYangzai** [comment]
> @BoyYangzai 我刚才也排查出了这个问题 很尴尬

哈哈哈哈 机会是同时发的 太巧了哈哈哈哈
没关系 没问题了就好🤝

**Comment by gouqingping** [comment]
@BoyYangzai 太感谢你了，幸苦了
