### ISSUE TITLE
Cascader组件存在内存泄露

### ISSUE THREAD

**Issue by h5-c** [ant-design/ant-design#42947]
### Reproduction link

[https://--](https://--)

### Steps to reproduce

1.Cascader组设置multiple
2.销毁组件
3.控制台报错内存泄露

### What is expected?

修复此问题

### What is actually happening?

--

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 17.0.2 |
| System | macOS |
| Browser | Chrome 113.0.5672.92 |

**Comment by BoyYangzai** [comment]
@h5-c 
https://stackblitz.com/edit/react-qvwg6b?file=demo.tsx
我这边使用最新的antd没有复现出来 请提供一个复现链接

**Comment by h5-c** [comment]
> @h5-c https://stackblitz.com/edit/react-qvwg6b?file=demo.tsx 我这边使用最新的antd没有复活出来 请提供一个复活链接

react版本是17.0.2，在react18.2.0中不会出现这个问题、react-dom@17.*和react-dom@18.*的卸载方式不同

**Comment by h5-c** [comment]
> Hello @h5-c. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @h5-c, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://github.com/h5-c/react-ts-app react@17.0.2  antd@5.5.1

**Comment by afc163** [comment]
<img width="1269" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/1b844146-e518-4d0d-91df-3d9d46ad6c57">

Could you provide a codesandbox ?

**Comment by h5-c** [comment]
> <img alt="图片" width="1269" src="https://user-images.githubusercontent.com/507615/244994514-1b844146-e518-4d0d-91df-3d9d46ad6c57.png">
> 你能提供一个codeandbox吗？

已开放权限

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/41572#issuecomment-1491449544

**Comment by h5-c** [comment]
antd依赖rc-overflow如果安装最新版本1.3.1会发生这个错误、安装依赖时指定rc-overflow版本为1.2.6无异常
