### ISSUE TITLE
Typography.Paragraph刚好出现滚动条时一直闪屏

### ISSUE THREAD

**Issue by wankangk1** [ant-design/ant-design#42958]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/s7um3s?file=/demo.tsx)

### Steps to reproduce

1.此为antd官网demo,将ellipsis设置成3行
2.拖动浏览器边框使demo刚好出现滚动条时，会一直闪
3.在出现滚动条的边界反复试一下

### What is expected?

出现正常的滚动条，文本没有屏闪现象

### What is actually happening?

文本屏闪

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | react17 |
| System | windows10 |
| Browser |  114.0.5735.110（正式版本） |

**Comment by wankangk1** [comment]
咋没人回复呢;
![动画](https://github.com/ant-design/ant-design/assets/26266264/60f672c0-b1a0-4352-91cc-3d90d66d944c)
改正一下，拖动使滚动条刚好消失出现的，目前使用overflow-y:scroll 能暂时避免，应该是滚动条消失时一行能显示的文字数量变了导致的，往下继续拖动触发重新计算了又正常了

**Comment by zombieJ** [comment]
Typography 带有 expand 按钮时，省略是通过 js 计算得来。这个滚动条正好卡在有滚动条要折行，于是折行后滚动条发现又不需要了又变回去。有点不太好处理。

**Comment by bbb169** [comment]
> Typography 带有 expand 按钮时，省略是通过 js 计算得来。这个滚动条正好卡在有滚动条要折行，于是折行后滚动条发现又不需要了又变回去。有点不太好处理。

https://github.com/ant-design/ant-design/pull/43039
这样可以解决，但不知道是否适合呢，烦请指导

**Comment by bbb169** [comment]
> Typography 带有 expand 按钮时，省略是通过 js 计算得来。这个滚动条正好卡在有滚动条要折行，于是折行后滚动条发现又不需要了又变回去。有点不太好处理。

https://github.com/ant-design/ant-design/pull/43039
这样可以解决，但是否适合呢？

**Comment by BoyYangzai** [comment]
@bbb169 pr 可以 reopen～

**Comment by bbb169** [comment]
https://codesandbox.io/s/hou-zhui-antd-4-24-10-forked-zxy34h

**Comment by cloudmoonocus** [comment]
@zombieJ 请问在 "antd": "4.22.8" 里，这种问题如何解决呢，是因为 `white-space: pre-line` 这个，设置成不保留换行符的属性之后就没有这种情况了，有什么解决方案可以保留换行符，还不闪烁？🤔🤔

**Comment by juanporley** [comment]
If [this PR (#43058)](https://github.com/ant-design/ant-design/pull/43058) is a fix, can it be backported to antd v4? We're experiencing this flicker with v4.24.15

**Comment by juanporley** [comment]
Issue was reported on v4 so I'm not sure why it was marked as Closed if the commit didn't make it to v4?
