### ISSUE TITLE
Form组件在宽度小于550px时， layout="horizontal"失效

### ISSUE THREAD

**Issue by junjie-lean** [ant-design/ant-design#42957]
### Reproduction link

[https://ant-design.gitee.io/components/form-cn#components-form-demo-layout](https://ant-design.gitee.io/components/form-cn#components-form-demo-layout)

### Steps to reproduce

该问题在antd官网的Form组件示例可以复现，缩小浏览器宽度，横向的Form.Item会变成上下布局，也就是说layout="horizontal"变成了  Layout="vertical"

### What is expected?

即使在Form组件宽度比较小的情况下，依旧保持horizontal布局

### What is actually happening?

没有保持horizontal布局

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2 |
| System | window11 |
| Browser | chrome@latest |

---
我猜想作者在处理这里时是故意而为之的，目的是为了在小宽度下显示不异常，但是在手机分辨率下，依旧会强制变化。

**Comment by linxianxi** [comment]
@afc163 看下小于 xs 时是否要去掉这个强制变化。

**Comment by afc163** [comment]
> 但是在手机分辨率下，依旧会强制变化。

确实是故意而为之的，目的是为了在小宽度下显示不异常。这个问题是啥？

**Comment by linxianxi** [comment]
应该是这样想的：设置 horizontal 应该一直是 horizontal，如果小宽度下有问题，应该用户自己设置 labelCol 等调整

**Comment by junjie-lean** [comment]
> 应该是这样想的：设置 horizontal 应该一直是 horizontal，如果小宽度下有问题，应该用户自己设置 labelCol 等调整

确实应该是这样，设置 horizontal 就应该一直是 horizontal，如果小宽度下有问题，用户应该想其他办法来解决，这样组件的自由度还是在用户手里。

**Comment by afc163** [comment]
懂了，看看能不能用自定义 token 解决。

**Comment by linxianxi** [comment]
感觉应该删掉，如果 mode 是 inline，小于 575 就异常了
<img width="648" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/54b47b20-b48e-4bf3-ad2b-fc75d23d5ffb">

**Comment by baiyang2292** [comment]
y，we need more width

**Comment by zombieJ** [comment]
用 Token 配置响应式范围：

https://codesandbox.io/s/biao-dan-bu-ju-antd-5-6-1-forked-3hd6lp?file=/demo.tsx

**Comment by afc163** [comment]
同一个问题：

- https://github.com/ant-design/ant-design/issues/33852
- https://github.com/ant-design/ant-design/issues/16499
