### ISSUE TITLE
AntDesign CSS not loading when deployed on Netlify 

### ISSUE THREAD

**Issue by kevinreber** [ant-design/ant-design#42950]
### Reproduction link
- Deployed Website (OLD URL): [https://648546dba16db5506ab04eb6--lucky-kitsune-32a0c5.netlify.app/](https://648546dba16db5506ab04eb6--lucky-kitsune-32a0c5.netlify.app/)
- Deployed Website (NEW URL): https://icongenn.com/
- Github Repo: https://github.com/kevinreber/ai-icon-generator

### Steps to reproduce
I deployed a Remix app to Netlify that uses AntDesign. AntDesign CSS not loading as expected on all browsers.

### What is expected?
AntDesign CSS to load on all browsers

### What is actually happening?
AntDesign CSS is not being applied to any of the elements on my deployed website on all browsers
<img width="1785" alt="image" src="https://github.com/ant-design/ant-design/assets/42260999/60d61fa6-b948-447e-8356-6039f9e4d841">

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | Remix |
| System | Mac OS |
| Browser | Google Chrome |

**Comment by kiner-tang** [comment]
In the example you provided, the css had been injected into head with production mode. But there is development mode in your html className.
![image](https://github.com/ant-design/ant-design/assets/10286961/424c9e21-af3e-4e33-9653-fb42c39c1504)
<img width="1027" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/000d3fdb-110a-4d57-a0a1-e82e033582d5">

Why use production mode in dev mode? Maybe you can unify NODE_ENV in scripts like this:
<img width="1011" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/ad072183-7d2a-4e33-9b0f-003b1aa6d8c8">

**Comment by kevinreber** [comment]
@kiner-tang I removed the `cross-env NODE_ENV=production` and changed to be only `netlify dev`, but was still facing the same issue.

I found a "hacky" solution in this thread by setting 
```tsx
<ConfigProvider
    theme={{
        hashed: false   // 🟡 <-- Added this flag to avoid hashing AntDesign CSS styles
    }}
```
Github thread: https://github.com/ant-design/ant-design/discussions/38753#discussioncomment-4261127

Seems like this is an issue others have been facing since upgrading to AntDesign v5^. Work around is fine for now since it's just a small personal project 😄

**Comment by zombieJ** [comment]
I guess it's related with netlify config or some else. antd use `process.env.NODE_ENV` for check whether it should generate production code or dev code:

https://github.com/ant-design/cssinjs/blob/97c8016af425f4daccba92dfe7be1e33a16d741e/src/hooks/useCacheToken.tsx#L14

**Comment by zombieJ** [comment]
I checked the doc seems dev will build as `development` mode which means your `cross-env NODE_ENV=production` may be replaced by netlify:
https://docs.netlify.com/site-deploys/overview/#deploy-contexts

I guess it will help to contact netlify directly which can help on your build : )
