### ISSUE TITLE
Tooltip新特性

### ISSUE THREAD

**Issue by lyp000119** [ant-design/ant-design#42959]
### What problem does this feature solve?

使用场景：在页面中有一个标签需要超过两行或者三行显示省略号，如果显示省略号时就显示Tooltip反之则不显示。

### What does the proposed API look like?

```javascript
<Tooltip title={name} byEllipsis={true}>
  <p>name</p>
<Tooltip>
```

**Comment by zombieJ** [comment]
[文档](https://ant.design/components/typography-cn#components-typography-demo-ellipsis)里有哈：

https://codesandbox.io/s/sheng-lue-hao-antd-5-6-0-forked-xhw7gc?file=/demo.tsx

**Comment by lyp000119** [comment]
好的，谢谢
