### ISSUE TITLE
给modal设置了style={{ display: "none" }}时，visible设为true后蒙层似乎一直存在

### ISSUE THREAD

**Issue by Sharang-heng** [ant-design/ant-design#42963]
### What problem does this feature solve?

想利用modal的蒙层，modal其他内容不显示，但是遮罩似乎一直存在，点击空白处时一直触发onCancel，设置了destroyOnClose也没有效果
复现地址https://codesandbox.io/s/ji-ben-antd-5-6-0-forked-8v7zd5?file=/demo.tsx

### What does the proposed API look like?

modal的visible为false时蒙层应该销毁

**Comment by Sharang-heng** [comment]
`import React, { useState } from "react";
import "./index.css";
import { Button, Modal } from "antd";

const App: React.FC = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const showModal = () => {
    setIsModalOpen(true);
  };

  return (
    <>
      <Button type="primary" onClick={showModal}>
        Open Modal
      </Button>
      <Modal
        visible={isModalOpen}
        style={{ display: "none" }}
        mask={false}
        destroyOnClose
        onCancel={() => {
          Modal.confirm({
            title: "确认关闭？",
            onOk: () => {
              setIsModalOpen(false);
            }
          });
        }}
      />
    </>
  );
};

export default App;`

**Comment by Wxh16144** [comment]
尝试将 `<Modal />` 的 `style` 属性改成 `style={{ visibility: "hidden" }}` 试试?

**Comment by zombieJ** [comment]
`display: none` 动画事件不会触发，所以会永远停留在 `appear-active` 状态。要隐藏 Modal 用 `open`，不要混合着来。

**Comment by wankangk1** [comment]
可以这样写`isModalOpen&&<Modal/>`
不过为什么加了display:none, Modal关闭不了

**Comment by zombieJ** [comment]
> `display: none` 动画事件不会触发，所以会永远停留在 `appear-active` 状态。

↑
