### ISSUE TITLE
`handleStyle` should accept array of CSSProperties if Slider with `range` mode

### ISSUE THREAD

**Issue by definite2** [ant-design/ant-design#42967]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hxzncr?file=/App.tsx)

### Steps to reproduce

Create Slider with range prop. Add custom styles for start and end handler with `handleStyle` prop. If you give array of styles it works but it gives type error.

### What is expected?

the `handleStyle` should accept array of styles if range mode,  it should accept array of css properties if range Slider.

### What is actually happening?

It seems handleStyle prop can accept array of styles but it gives type error. 

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 16.8.6 |
| System | mac12.6 |
| Browser | Chrome 114.0.5735.106 |

---

**Comment by afc163** [comment]
Please upgrade to latest antd 4.x version: https://codesandbox.io/s/antd-reproduction-template-forked-p2xk2l?file=/App.tsx
