### ISSUE TITLE
官方能不能新开一个工程，用来开发阿里的低代码编辑器的antd插件，比如说setter等

### ISSUE THREAD

**Issue by zhengguo07q** [ant-design/ant-design#42973]
### What problem does this feature solve?

可以大幅度提高业界生产力

### What does the proposed API look like?

让前端人员只需要修改业务逻辑， 其他的都是用编辑器进行产出

**Comment by zombieJ** [comment]
暂时没有这个计划哈~

**Comment by afc163** [comment]
欢迎生态贡献哈
