### ISSUE TITLE
[Dropdown] focus doesn't go to the menu when using autoFocus prop

### ISSUE THREAD

**Issue by SpaNb4** [ant-design/ant-design#42979]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wl3dkl?file=/index.js)

### Steps to reproduce

1) Click on the three dot icon to open the menu
2) Try to navigate using the keyboard, use the arrow keys to select a menu item

### What is expected?

The focus shifts to the menu and I can select a menu item

### What is actually happening?

The focus doesn't shift to the menu and I can't select a menu item

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.0 |
| System | Pop!_OS 22.04 LTS |
| Browser | Chrome 113.0.5672.126 |

---
This problem first appeared in version 5.5.0, I could not reproduce it in 5.4.7.
https://codesandbox.io/s/antd-reproduction-template-forked-wky7gz?file=/index.js

**Comment by Yuiai01** [comment]
I'll try to fix it.

**Comment by gitstart** [comment]
@SpaNb4 I would like to pick this up
