### ISSUE TITLE
Tree树组件，无论是defaultSelectedKeys还是selectedKeys都无法选中多个节点，始终只有一个节点生效

### ISSUE THREAD

**Issue by himushroom** [ant-design/ant-design#42982]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-6-0-forked-2w6f9t?file=/demo.tsx)

### Steps to reproduce

上述重现链接是直接使用的官网例子，defaultSelectedKeys中一共写入了四个节点key，只有第一个节点被选中，其他节点无反应

### What is expected?

期望写入(default)SelectedKeys中的key，对应的节点均有选中效果

### What is actually happening?

写入(default)SelectedKeys中的key，只有一个节点有选中效果

| Environment | Info |
| --- | --- |
| antd | 5.6.0 |
| React | 18.2.0 |
| System | Windows 11 家庭中文版 |
| Browser | 谷歌浏览器 114.0.5735.110（正式版本） （64 位） |

**Comment by linxianxi** [comment]
我这里看是正常的呀

**Comment by himushroom** [comment]
![image](https://github.com/ant-design/ant-design/assets/19682322/13039afa-6cb4-479f-854f-29e24afb321d)
我这里看是这样的，我又去看了一下tree-select组件，我知道我这为什么选不上了，因为没有开multiple参数……T T

**Comment by himushroom** [comment]
小声建议……可以在文档描述里加一下需要开启multiple配合使用……❤

**Comment by afc163** [comment]
@himushroom 来个 PR 如何

**Comment by linxianxi** [comment]
设置了 checkable, multiple 应该会自动开启的

**Comment by himushroom** [comment]
> 设置了 checkable, multiple 应该会自动开启的

理论上来说checkable应该和selected没有关联……不过你要是这样说的话，那它可能依然是个BUG……
![image](https://github.com/ant-design/ant-design/assets/19682322/1da7e2b3-5ebd-494d-97b3-a867aeddceb1)

**Comment by himushroom** [comment]
> @himushroom 来个 PR 如何

好呀(^—^)

**Comment by linxianxi** [comment]
TreeSelect 是这样的，不知道 Tree 是不是一样
<img width="1480" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/26310b4d-714c-4707-ba73-e883e70a620a">
