### ISSUE TITLE
drawer组件不支持传入id props，4.18.x版本之前支持，4.18.x版本后就不生效了？

### ISSUE THREAD

**Issue by yagang94** [ant-design/ant-design#42987]
### What problem does this feature solve?

通过自定传入id，获取对应drawer dom元素，做一些自定义样式或者逻辑处理

### What does the proposed API look like?

传入id，透传下去

**Comment by yagang94** [comment]
![image](https://github.com/ant-design/ant-design/assets/50126022/54b56653-da6d-4bbb-acaa-cf9dc78d6ba4)

已提供antd@4.x的

**Comment by yagang94** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-52hh3m?file=/index.js

**Comment by zombieJ** [comment]
应该是之前解构传过去的，`id` 这个看起来和 `className` 一样应该弄到 Panel 上。

**Comment by yagang94** [comment]
是的。4.18.x之前应该是直接透传过去了，4.18.x之后是没有透传了吗

**Comment by yagang94** [comment]
@zombieJ @afc163 俩位大佬，看下这个小问题啥时候能兼容下呢

**Comment by yagang94** [comment]
谢谢大佬

**Comment by yagang94** [comment]
这个预计啥时候能发一版本支持呢

**Comment by yagang94** [comment]
对的。但是之前的版本是放在最外层，最好还是保持一致吧

**Comment by yagang94** [comment]
对的。但是之前的版本是放在最外层，最好还是保持一致吧。 
![image](https://github.com/ant-design/ant-design/assets/50126022/896f0043-2261-41ed-9fa1-4c1d2ec54f26)

**Comment by yagang94** [comment]
@MuxinFeng
