### ISSUE TITLE
button type = 'link' 并且禁用的情况下 样式问题

### ISSUE THREAD

**Issue by websybin** [ant-design/ant-design#42997]
### Reproduction link

https://codesandbox.io/s/antd-reproduction-template-forked-pcwx68?file=/index.js

### Steps to reproduce

link 后面加个 href

### What is expected?

正常的link禁用样式

### What is actually happening?

正常button禁用的样式

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.0.0 |
| System | mac |
| Browser | 113.0.5672.126 |

**Comment by BoyYangzai** [comment]
@websybin 
正常的link禁用样式应该是什么样子呢
ref https://github.com/ant-design/ant-design/issues/39452

**Comment by websybin** [comment]
> @websybin 正常的链接禁止使用样式应该是什么样式呢 ref #39452

![image](https://github.com/ant-design/ant-design/assets/84109842/7f9e8940-b9ab-4a96-8a41-069a52ccbb2c)
这个样子

**Comment by BoyYangzai** [comment]
@websybin 👌，我晚上下班回家修一下

**Comment by BoyYangzai** [comment]
总共分为两类：`type` 和 `href`
明确只有 `type= link` 与样式有关  
`href` 与 `a` 标签行为一致
则总共以下三种情况：
![20230615004507_rec_](https://github.com/ant-design/ant-design/assets/94534613/7e905c7d-37c7-4434-b6f6-a03564a74c20)
