### ISSUE TITLE
Avatar prop "alt" doesn't work

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#42996]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-fork-avatar-props-alt-pvtfsc?file=/index.js)

### Steps to reproduce

1. import Avatar component
2. Specify attribute "alt"
3. Look at DOM tree to check alternative text for avatar

### What is expected?

Alternative text in corresponding avatar node into DOM tree

### What is actually happening?

Just insert span for avatar without alternative text (no attr "alt"/no WAI-role/no aria-label)

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome 114 |

---
I don't exactly know what must be rendered for a11y via "span" elements. I guess that span element should have role="img" and aria-label=alt-text. Instead of "alt-text" it needs to insert alternative text from "alt" prop

**Comment by Wxh16144** [comment]
Maybe we should improve accessibility?

**Comment by zombieJ** [comment]
Yes. You got it. For image it should pass `alt` for a11y. For string avatar, screen reader can read text directly : )
