### ISSUE TITLE
Input 组件在 React 严格模式下报错： findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by littledian** [ant-design/ant-design#42994]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4p6vfp?file=/index.js)

### Steps to reproduce

打开控制台即可

### What is expected?

不报错

### What is actually happening?

有报错

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.0 |
| System | Windows11 22621.1778 |
| Browser | Chrome  114.0.5735.110 |

**Comment by BoyYangzai** [comment]
经典问题 我来看看吧

**Comment by BoyYangzai** [comment]
@littledian 
这个标题可以改一下 是 input 这个组件的问题 cascader 只是提供 trigeer
虽然还没有改好(doge🤪

**Comment by zombieJ** [comment]
我们可能要搞个 RFC 让 `ref` 被包成其他 object 的情况可以额外透出来，比如说 `ref.element`

**Comment by zombieJ** [comment]
```tsx
<Tree ref={info => {
  info.element;
  info.scrollTo;
}} />
```

然后 antd 找 ref 的时候都会 ref 找一下节点 or ref.element 一下

**Comment by Mayvis** [comment]
This will also show the error too.

```jsx
<Popover
    content={content}
    title='...'
    trigger='click'
    overlayStyle={{
      width: '144px',
    }}
    open={open}
    onOpenChange={(open) => setOpen(open)}
>
    <Tooltip placement='top' title='find'>
        <Button icon={<SnippetsOutlined />} aria-label='find' />
    </Tooltip>
</Popover>
```

**Comment by JayCC1** [comment]
import { Dropdown, Input } from 'antd'    
<Dropdown menu={{ items }}>
      <Input
        size="large"
        suffix={<IconSearch className="g-search" fill="#008755" />}
        defaultValue="mysite"
      />
    </Dropdown>
想请教一下哈哈哈，我更新到5.9.0我这个代码好像还是会报出 ‘findDOMNode is deprecated in StrictMode.’ 错误，这个应该不是我代码的问题吧...

**Comment by JayCC1** [comment]
```JavaScript
import { Dropdown, Input } from 'antd'
<Dropdown menu={{ items }}>
  <Input
  size="large"
  suffix={}
  defaultValue="mysite"
  />
</Dropdown>
```

想请教一下哈哈哈，我更新到5.9.0我这个代码好像还是会报出 **‘findDOMNode is deprecated in StrictMode.’** 错误，这个应该不是我代码的问题吧...

**Comment by FilippoNardin** [comment]
```js
import { Tooltip, Button } from "antd";

export default function App() {
  return (
    <Tooltip title="On hover">
      <Tooltip trigger={["click"]} title="On click">
        <Button>Click me!</Button>
      </Tooltip>
    </Tooltip>
  );
}
```

This will also trigger the `findDOMNode is deprecated` warning.

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/48709

**Comment by afc163** [comment]
Fixed in antd@5.17.3: https://github.com/ant-design/ant-design/pull/48958
