### ISSUE TITLE
A way to change, remove tags in `resetForm` of antd v5

### ISSUE THREAD

**Issue by anhtran** [ant-design/ant-design#42995]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-6-1-forked-r6yn8s?file=/demo.tsx)

### Steps to reproduce

Add `fieldset` and `legend` tags.

### What is expected?

Keep fieldset and legend in default CSS

### What is actually happening?

Cannot change or remove init CSS of Form, just can modify some tokens.

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | React 18 |
| System | macOS |
| Browser | Chrome 114 |

**Comment by zombieJ** [comment]
You can use `component={false}` remove Form dom which will ignore selector match:

https://codesandbox.io/s/basic-usage-antd-5-6-1-forked-p3l3kv?file=/demo.tsx

**Comment by anhtran** [comment]
But I still want to use `onFinish` of Form. How to do that?
