### ISSUE TITLE
Cascader 的 CascaderProps 没有  getPopupContainer （tsd）

### ISSUE THREAD

**Issue by hjin-me** [ant-design/ant-design#4300]
#### 发生问题的环境是：

- antd 版本: 2.5.2
- 操作系统及其版本: Mac OS X, typescript 2.1.4
- 浏览器及其版本: Chrome 55

#### 您做了什么？请提供尽可能详细的重现步骤。

使用 tsx 开发，使用 Cascader 组件时，ts 编译器提示 Cascader 没有 getPopupContainer 的方法。
https://github.com/ant-design/ant-design/blob/master/components/cascader/index.tsx#L25

**Comment by afc163** [comment]
Give us a PR ~
