### ISSUE TITLE
Form的onValuesChange和getFieldsValue被Form.List嵌套后，和单独的Form时表现不一致

### ISSUE THREAD

**Issue by laomu1988** [ant-design/ant-design#43005]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gwt4p6?file=/index.js)

### Steps to reproduce

点击按钮1，在弹窗的表单中输入值，会触发onValuesChange

### What is expected?

期望onValueChange的第二个值是表单中的所有对象， form.getValuesValue也返回所有对象的值

### What is actually happening?

onValueChange的第二个参数values结果是空对象，同时使用form.getValuesValue返回的结果也是空对象

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18 |
| System | mac |
| Browser | chrome |

---
5.3.1版本结果是符合预期的，5.5.1版本有问题

**Comment by zombieJ** [comment]
看起来是 Context 穿透了

**Comment by laomu1988** [comment]
👍🏻，高效
