### ISSUE TITLE
Validation not run for Form.Item with dependencies inside a Form.List

### ISSUE THREAD

**Issue by tw-andri** [ant-design/ant-design#43013]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-form-list-validation-dependencies-forked-3n5xvt?file=/src/App.js)

### Steps to reproduce
Create at least two form items inside a form list field. Make one of them dependent on the other using the `dependencies` property.
In sandbox: Add a field, edit first name and last name to match. Then change first name.

### What is expected?

The last name field is dependent on the first name field. If the first name field is edited the validation on last name field should be triggered and error message shown.

### What is actually happening?

Validation not triggered.

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 17.0.2 |
| System | any |
| Browser | any |

---
This issue is really the same as https://github.com/ant-design/ant-design/issues/26351 but that issue has been closed and seems like the further comments bringing up the bug are being ignored. Hoping that the new issue will be noticed.

**Comment by zombieJ** [comment]
`dependencies` is a `namePath` list

```diff
-- dependencies={["users", field.name, "first"]}
++ dependencies={[["users", field.name, "first"]]}
```

https://codesandbox.io/s/antd-form-list-validation-dependencies-forked-mjdjtf?file=/src/App.js
