### ISSUE TITLE
Dropdown appears misaligned and cut off if scrolled to the right

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#43025]
### Reproduction link

[https://stackblitz.com/edit/react-sk6ex7?file=demo.tsx](https://stackblitz.com/edit/react-sk6ex7?file=demo.tsx)

### Steps to reproduce

Place Dropdown off screen to the right then scroll page to see it.

### What is expected?

Menu renders correctly.

### What is actually happening?

Menu is offset to the left and narrower than it should be, causing menu items to wrap.

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.0 |
| System | Windows 10.0.19044 Build 19044 |
| Browser | Chrome 114.0.5735.110 (Official Build) (64-bit) |

---
Possibly related: https://github.com/ant-design/ant-design/issues/29366

**Comment by devuxer** [comment]
@zombieJ 

![image](https://github.com/ant-design/ant-design/assets/1298521/d5b0d37c-9cd5-4b24-9646-acc0b7a230c6)

**Comment by afc163** [comment]
文本在视距外的排版异常，确实是个老问题了。

**Comment by devuxer** [comment]
@afc163, Can this be fixed? Is there a workaround?

**Comment by afc163** [comment]
It could be fixed, we are looking for solutions.

**Comment by zombieJ** [comment]
Is `max-content` style help?

https://stackblitz.com/edit/react-sk6ex7-jjj5nw?file=demo.tsx

**Comment by devuxer** [comment]
@zombieJ , YESSS! That fixes it. Thank you!

Maybe you could make that that the default?

**Comment by zombieJ** [comment]
> @zombieJ , YESSS! That fixes it. Thank you!
> 
> Maybe you could make that the default?

`max-content` maybe not the best way by default. Since if content use `flex` layout of auto `wrap`. It will count wrong width. But in most case, its safe.

**Comment by edisonLzy** [comment]
> 文本在视距外的排版异常，确实是个老问题了。

为什么会在视距外 会存在这个问题呢 ?
