### ISSUE TITLE
表格中向左固定列不生效

### ISSUE THREAD

**Issue by MrMengJ** [ant-design/ant-design#43024]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-lie-antd-5-6-1-forked-cm5pjy)

### Steps to reproduce

Full Name 列左固定不生效，其在coloumns声明中不在最前面

### What is expected?

Full Name 列左固定生效

### What is actually happening?

Full Name 列左固定不生效

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.0.0 |
| System | windows 11 |
| Browser | Chrome 114.0.5735.110 |

**Comment by zombieJ** [comment]
看一下 console 的 warning 信息哈，固定列是需要从开始连续固定，不能单独设置中间某列固定哈：

<img width="531" alt="截屏2023-06-15 10 32 46" src="https://github.com/ant-design/ant-design/assets/5378891/91898eac-2572-4f73-84f9-7e83ee14fdbe">

**Comment by MrMengJ** [comment]
> 看一下 console 的 warning 信息哈，固定列是需要从开始连续固定，不能单独设置中间某列固定哈：
> 
> <img alt="截屏2023-06-15 10 32 46" width="531" src="https://user-images.githubusercontent.com/5378891/245976645-91898eac-2572-4f73-84f9-7e83ee14fdbe.png">

固定列只能从开始连续固定吗？为什么会有这种限制呢？感觉这对使用者的限制太多了，我想将其中一列作为固定项还得重新刚给columns重新排下序，然后重新赋值给table

**Comment by yoyo837** [comment]
可以试试这样, 如果遇到需要固定的列, 设置新的columns顺序

**Comment by MrMengJ** [comment]
> 可以试试这样, 如果遇到需要固定的列, 设置新的columns顺序

现在明白了。觉得这个限制不太友好，每次设置新的固定列都要重新排下columns顺序。
