### ISSUE TITLE
当配置configProvider(theme.token.motion=false) 时， tree的expand功能有问题

### ISSUE THREAD

**Issue by g770728y** [ant-design/ant-design#43038]
### Reproduction link

[https://stackblitz.com/edit/react-kkj61s?file=demo.tsx](https://stackblitz.com/edit/react-kkj61s?file=demo.tsx)

### Steps to reproduce

1. 打开上述链接，注意代码 <ConfigProvider theme={{ token: { motion: false } }}> 设置了motion=false 以关闭动画
2. 在预览中收合根节点，成功
3. 展开根节点，失败
4. 将上述代码中的 motion:false改成motion: true
5. 重复2-3步，成功

### What is expected?

期望在motion=false时也能正常展开、收合节点

### What is actually happening?

只能展开 或 收合一次

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome Version 114.0.5735.106 (Official Build) (arm64) |

---
设置 motion: false的目的是关闭动画

**Comment by zombieJ** [comment]
试了一下，不太好解。需要 `rc-motion` 补一个事件

**Comment by g770728y** [comment]
那么，有没有其它方法 关闭 Modal 弹出动画？
（这样我可以暂时绕开这个问题）
