### ISSUE TITLE
Table title prop deprecated

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#43036]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stykts?file=/demo.tsx)

### Steps to reproduce

title prop is deprecated — Use caption instead

### What is expected?

no error/warning shown

### What is actually happening?

title prop is working but with a warning about deprecation

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | "react": "^18.2.0" |
| System | MacOS and CodeSandbox |
| Browser | Chrome 108.0.5359.124 |

**Comment by afc163** [comment]
I can't see errors in your codesandbox.

<img width="767" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/d894b853-d72c-456a-8270-00d38ae99d33">

**Comment by nonam4** [comment]
> I can't see errors in your codesandbox.
> 
> <img alt="图片" width="767" src="https://user-images.githubusercontent.com/507615/246101938-d894b853-d72c-456a-8270-00d38ae99d33.png">

The error/warning is shown on code

![Captura de Tela 2023-06-15 às 09 00 40](https://github.com/ant-design/ant-design/assets/60632638/1632ba87-c4f7-4790-a523-235abaad798d)

In VSCode, the deprecation is marked inside `rc-table/lib/interface.d.ts` on line 133
