### ISSUE TITLE
Add prop to move Tree expandIcon (switcherIcon) to the right side

### ISSUE THREAD

**Issue by nabramow** [ant-design/ant-design#43041]
### What problem does this feature solve?

Right now it's only possible to have the expandIcon (i.e. switcherIcon) on the left. I don't see a way to move this to the right, even though it's a common design use case.

### What does the proposed API look like?

Add a prop to Tree to put the expandIcon on the right side or end of the TreeNode.

This is where I want it:
<img width="336" alt="Screen Shot 2023-06-15 at 17 54 29" src="https://github.com/ant-design/ant-design/assets/18261566/5d503f03-56b3-45d2-ae8d-0278a2d8a38f">

**Comment by zombieJ** [comment]
It strange to move expand icon position. But you can use css to handle this:
https://codesandbox.io/s/ji-ben-antd-5-6-1-forked-9gkgpq?file=/index.css

**Comment by nabramow** [comment]
This doesn't work though, as it also moves the leaf line below it, then it looks quite strange:

<img width="318" alt="Screen Shot 2023-06-16 at 11 26 39" src="https://github.com/ant-design/ant-design/assets/18261566/8d74482a-6bae-46e8-aaee-a8e9b163f292">

**Comment by nabramow** [comment]
Okay nevermind, I solved it a bit differently. In case anyone else wants this in the future, this did it without messing up the lines:

´´´css
  .ant-tree-treenode {
    flex-direction: row-reverse;
  }
´´´

**Comment by phamtiendungg** [comment]
![Image](https://github.com/user-attachments/assets/fa368316-3518-4583-b71a-4f7d034a3943)

We can override the CSS to make it work — here's an example, I did it entirely with CSS.
