### ISSUE TITLE
表单disabled会disabled所有的antd录入组件,(包括自定义Item组件时，弹出modal弹框的取消，确定按钮)

### ISSUE THREAD

**Issue by x-shron** [ant-design/ant-design#43044]
### Reproduction link

https://l5yc34.csb.app/

### Steps to reproduce

无

### What is expected?

disabled可以通过向value一样透传，从而可以实现自定义

### What is actually happening?

disabled了所有的录入组件

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | ^16.14.0 |
| System | wiindow |
| Browser | 谷歌 |

**Comment by x-shron** [comment]
提供一个示例： https://l5yc34.csb.app/

> Hello @x-shron. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @x-shron, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

提供一个示例： https://l5yc34.csb.app/

**Comment by MadCcc** [comment]
应该也隔断一下上下文

**Comment by Yuiai01** [comment]
> 应该也隔断一下上下文

@MadCcc  闲夕大佬 这里是否意味着只有 form-item 或自定义 form-item 中的组件需要接收 form 的 disabled ，而这些组件内部的组件不需要接收 form 的 disabled

**Comment by Wxh16144** [comment]
感觉这个问题可修可不修, 开发者可以自行决定是否阻断:

```tsx
import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Input, Modal, version, Form } from "antd";
import { DisabledContextProvider } from "antd/es/config-provider/DisabledContext";
// import "antd/dist/antd.css";
// import "./index.css";

const CustomItem = ({ value, onChange }) => {
  const [visible, setVisible] = useState(false);
  return (
    <div>
      <Input style={{ width: "100px" }} />
      <a onClick={() => setVisible(true)}>click here</a>
      <DisabledContextProvider disabled={false}>
        <Modal
          title="modal"
          visible={visible}
          onCancel={() => setVisible(false)}
        >
          anything
        </Modal>
      </DisabledContextProvider>
    </div>
  );
};

const App = () => {
  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <Form disabled>
        <Form.Item label="label">
          <CustomItem />
        </Form.Item>
      </Form>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);
```

**Comment by xliez** [comment]
设置 ConfigProvider 的 componentDisabled 属性可以隔断上下文
