### ISSUE TITLE
表格多选框怎么行合并，如图

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#4304]
![image](https://cloud.githubusercontent.com/assets/17545551/21340425/6302b20e-c6c1-11e6-8d04-186c20b13d0d.png)

**Comment by RaoHai** [comment]
暂时不支持此功能。

**Comment by zhonggithub** [comment]
会考虑加上去吗

**Comment by afc163** [comment]
duplicate #3505
