### ISSUE TITLE
antd5.x 的form组件结合可编辑表格时当在单元格输入内容时会出现明显的性能问题

### ISSUE THREAD

**Issue by xinbo97** [ant-design/ant-design#43057]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-fxfz5p?file=/demo.tsx)

### Steps to reproduce

1、点击Edit 编辑；
2、出现可编辑单元格，在单元格输入数值；
3、会看到页面明显卡顿

### What is expected?

单元格输入值时页面不会出现明显卡顿

### What is actually happening?

单元格输入时页面卡顿

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | react18.x |
| System | macOS 12.6 (21G115) |
| Browser | chrome 107.0.5304.110（正式版本） (arm64) |

---
1、怎么能让EditCell的render次数降低，目前只要组件render了，所有的EditCell都会重新渲染；
2、为什么在可编辑状态下只有三个单元格就会这么卡顿！！

**Comment by poyiding** [comment]
1 . 这两个问题都是 你这行 代码 name={["table", index, dataIndex]} 导致，因你 Form.Item 嵌套子 Form.Item 的 name 依赖了 "table", 当你td 里的Form.Item 更新时 会触发父级 ”table“ 这个 Form.Item 渲染，所以导致整个 Table 都渲染，导致卡顿，name={dataIndex} 就OK。
2. 改完后这时你发现，为啥保存后table 没有更新，这是因为你设置了 initialValue ，它只会第一次渲染时执行。
3. 正确的做法是按antd 官方的demo 来做，提交时取state 做为字段的 value。如果你还是坚持现要包一层，请看： https://codesandbox.io/s/antd-reproduction-template-forked-cgvl87

**Comment by xinbo97** [comment]
非常感谢您的答复，但目前这种解决方案相当于Table可编辑组件 不作为 FormItem 控件来处理了。这样有个问题我在 formGet 拿form表单值的时候就是undefined。 官方demo也是将Table可编辑组件不作为 FormItem 控件来处理的，实际上，在开发业务中往往要求可编辑表格作为一个Item控件去参与form中的处理。 并会出现 整个表格的cell 一开始就是可编辑状态，并且这些单元格的变化值也是实时反映到  form 值里。也就是说当单元格值改变后，利用 formGet 获取的值也是最新的。这样还是得用Item包裹Table，还是会出现Table 里cell单元格值改变导致整个Table渲染。（但按道理来说，整个Table的渲染应该不会有多大开销呀，当前的EditCell 我用了IntersectionObserver来做优化处理，Table可视区里表单的控件不会很多的，但就算这样还是在cell值变的时候出现明显卡顿）

https://codesandbox.io/s/antd-reproduction-template-forked-wjnnxq?file=/formAndTable/index.jsx
上面链接是我结合业务里需求实现的 form 和 可编辑表格的结合。  目前的问题就是cell值变动造成页面卡顿现象，并且当MouceEnter到某一表格行时，会触发cell频繁渲染，又造成性能问题。能不能针对 这种可编辑表格作为 表单控件 时 ，做进一步的优化？

再次感谢您百忙之间抽出时间看此问题，也非常期待您针对最新链接里场景下性能问题的回复。

**Comment by poyiding** [comment]
> 非常感谢您的答复，但目前这种解决方案相当于Table可编辑组件 不作为 FormItem 控件来处理了。这样有个问题我在 formGet 拿form表单值的时候就是undefined。 官方demo也是将Table可编辑组件不作为 FormItem 控件来处理的，实际上，在开发业务中往往要求可编辑表格作为一个Item控件去参与form中的处理。 并会出现 整个表格的cell 一开始就是可编辑状态，并且这些单元格的变化值也是实时反映到 form 值里。也就是说当单元格值改变后，利用 formGet 获取的值也是最新的。这样还是得用Item包裹Table，还是会出现Table 里cell单元格值改变导致整个Table渲染。（但按道理来说，整个Table的渲染应该不会有多大开销呀，当前的EditCell 我用了IntersectionObserver来做优化处理，Table可视区里表单的控件不会很多的，但就算这样还是在cell值变的时候出现明显卡顿）
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-wjnnxq?file=/formAndTable/index.jsx 上面链接是我结合业务里需求实现的 form 和 可编辑表格的结合。 目前的问题就是cell值变动造成页面卡顿现象，并且当MouceEnter到某一表格行时，会触发cell频繁渲染，又造成性能问题。能不能针对 这种可编辑表格作为 表单控件 时 ，做进一步的优化？
> 
> 再次感谢您百忙之间抽出时间看此问题，也非常期待您针对最新链接里场景下性能问题的回复。

 你仔细看我上面的链接，onSave 里form.setFieldValue 这行注释放开，form.getFieldsValue() 能获取到。在稍微抽一下就是你现在这样

**Comment by xinbo97** [comment]
您好，我按照您的思路又改了一下，但这样还是会有卡顿问题呀，如果全部放开为可编辑表格，相当于每个单元格change的时候再执行form.setFieldValue，并且这之前还有个找更新项的数据元素操作，不是把执行时间拉的更长了吗

**Comment by xinbo97** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-wjnnxq?file=/formAndTable/testTable/index.jsx

<img width="482" alt="image" src="https://github.com/ant-design/ant-design/assets/79836349/2b71caa4-72c3-4dc6-868a-f729a6061c48">

<img width="456" alt="image" src="https://github.com/ant-design/ant-design/assets/79836349/0bc89644-8563-4bb4-bd54-880c4d5a7df1">

**Comment by poyiding** [comment]
> 您好，感谢答复，我按照您的思路又改了一下，但这样还是会有卡顿问题呀，如果全部放开为可编辑表格，相当于每个单元格change的时候再执行form.setFieldValue，form.setFieldValue会造成Table的重新渲染，并且这之前还有个找更新项的数据元素操作，这不是把执行时间拉的更长了吗？辛苦您解下惑。

我给你做了一个完整的例子，并有注释。 https://codesandbox.io/s/antd-reproduction-template-forked-254htc?file=/EditTable.tsx 

你代码的问题是你的 change 事件中调用 setFieldsValue 导致的循环问题。这个地方也是和 antd 3.x 最大的区别，确实容易犯错。
antd V4 之后 如果Form.Item 设置了name 属性，数据同步会被[form 接管 ](https://ant-design.antgroup.com/components/form-cn#dependencies)

**Comment by xinbo97** [comment]
> > 您好，感谢答复，我按照您的思路又改了一下，但这样还是会有卡顿问题呀，如果全部放开为可编辑表格，相当于每个单元格change的时候再执行form.setFieldValue，form.setFieldValue会造成Table的重新渲染，并且这之前还有个找更新项的数据元素操作，这不是把执行时间拉的更长了吗？辛苦您解下惑。
> 
> 我给你做了一个完整的例子，并有注释。 https://codesandbox.io/s/antd-reproduction-template-forked-254htc?file=/EditTable.tsx
> 
> 你代码的问题是你的 change 事件中调用 setFieldsValue 导致的循环问题。这个地方也是和 antd 3.x 最大的区别，确实容易犯错。 antd V4 之后 如果Form.Item 设置了name 属性，数据同步会被[form 接管 ](https://ant-design.antgroup.com/components/form-cn#dependencies)

非常感谢您的回复，这个demo对我很有帮助，也辛苦您百忙之余的解惑，再次感谢。

**Comment by MadCcc** [comment]
如果还有问题欢迎新开 issue 反馈

**Comment by SunXinFei** [comment]
我看核心逻辑是去掉了setDataSouce，防止table重新reRender，改成form承载数据。那么如果有部分数据不是交互的form类型，比如只是text，也需要设置成form类型承接？再比如，如果有些值没有在table展示，也需要form去承接，否则form数据会造成数据源不正确的问题

**Comment by 1273082756** [comment]
同问, 有没有什么好的解决办法

**Comment by 1273082756** [comment]
> > 您好，感谢答复，我按照您的思路又改了一下，但这样还是会有卡顿问题呀，如果全部放开为可编辑表格，相当于每个单元格change的时候再执行form.setFieldValue，form.setFieldValue会造成Table的重新渲染，并且这之前还有个找更新项的数据元素操作，这不是把执行时间拉的更长了吗？辛苦您解下惑。
> 
> 我给你做了一个完整的例子，并有注释。 https://codesandbox.io/s/antd-reproduction-template-forked-254htc?file=/EditTable.tsx
> 
> 你代码的问题是你的 change 事件中调用 setFieldsValue 导致的循环问题。这个地方也是和 antd 3.x 最大的区别，确实容易犯错。 antd V4 之后 如果Form.Item 设置了name 属性，数据同步会被[form 接管 ](https://ant-design.antgroup.com/components/form-cn#dependencies)

非常感谢大佬给出的demo, 除此之外想要请教一下大佬, 如果有新增和删除条目的情况下, 如何优化卡顿的问题呢

**Comment by SunXinFei** [comment]
> 我看核心逻辑是去掉了setDataSouce，防止table重新reRender，改成form承载数据。
> 
> 1. 那么如果有部分数据不是交互的form类型，比如只是text，也需要设置成form类型承接？再比如，如果有些值没有在table展示，也需要form去承接，否则form数据会造成数据源不正确的问题
> 2. 如果数据有增删条目呢？该如何处理

我做了这个性能优化，控制到行渲染，支持行的增删改、列的联动，目前还未开源计划
另外说下，如果有用到expand功能和rowSelection要注意，需要单独做控制，expand和rowSelection会导致普通情况下的行渲染控制失效

**Comment by zhengyalizyl** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-cgvl87

提交表单时，表格里的rule不通过，还是会提交，无法通过form.validateFields()验证表格是否有问题

**Comment by SunXinFei** [comment]
> > 我看核心逻辑是去掉了setDataSouce，防止table重新reRender，改成form承载数据。
> > 
> > 1. 那么如果有部分数据不是交互的form类型，比如只是text，也需要设置成form类型承接？再比如，如果有些值没有在table展示，也需要form去承接，否则form数据会造成数据源不正确的问题
> > 2. 如果数据有增删条目呢？该如何处理
> 
> 我做了这个性能优化，控制到行渲染，支持行的增删改、列的联动，目前还未开源计划 另外说下，如果有用到expand功能和rowSelection要注意，需要单独做控制，expand和rowSelection会导致普通情况下的行渲染控制失效
-----
上半年3月份我又做了一版性能优化，做了一个编辑表格的虚拟化，支持table虚拟化，支持编辑、拖拽、支持大保存以及实时保存、支持行高不一致、支持合并单元格，除了极端合并单元格场景，基本在table4里面运行的没啥问题。

**Comment by KunHuoJ** [comment]
> > > 我看核心逻辑是去掉了setDataSouce，防止table重新reRender，改成form承载数据。
> > > 
> > > 1. 那么如果有部分数据不是交互的form类型，比如只是text，也需要设置成form类型承接？再比如，如果有些值没有在table展示，也需要form去承接，否则form数据会造成数据源不正确的问题
> > > 2. 如果数据有增删条目呢？该如何处理
> > 
> > 
> > 我做了这个性能优化，控制到行渲染，支持行的增删改、列的联动，目前还未开源计划 另外说下，如果有用到expand功能和rowSelection要注意，需要单独做控制，expand和rowSelection会导致普通情况下的行渲染控制失效
> 
> 上半年3月份我又做了一版性能优化，做了一个编辑表格的虚拟化，支持table虚拟化，支持编辑、拖拽、支持大保存以及实时保存、支持行高不一致、支持合并单元格，除了极端合并单元格场景，基本在table4里面运行的没啥问题。

老师能否参考一下，感谢

**Comment by SunXinFei** [comment]
> > > > 我看核心逻辑是去掉了setDataSouce，防止table重新reRender，改成form承载数据。
> > > > 
> > > > 1. 那么如果有部分数据不是交互的form类型，比如只是text，也需要设置成form类型承接？再比如，如果有些值没有在table展示，也需要form去承接，否则form数据会造成数据源不正确的问题
> > > > 2. 如果数据有增删条目呢？该如何处理
> > > 
> > > 
> > > 我做了这个性能优化，控制到行渲染，支持行的增删改、列的联动，目前还未开源计划 另外说下，如果有用到expand功能和rowSelection要注意，需要单独做控制，expand和rowSelection会导致普通情况下的行渲染控制失效
> > 
> > 
> > 上半年3月份我又做了一版性能优化，做了一个编辑表格的虚拟化，支持table虚拟化，支持编辑、拖拽、支持大保存以及实时保存、支持行高不一致、支持合并单元格，除了极端合并单元格场景，基本在table4里面运行的没啥问题。
> 
> 老师能否参考一下，感谢

年底稍微有点忙，我梳理下是否要走开源计划，我3月份做主要是当时正好有半个月空闲，23年做完控制渲染发现有性能上限，而且初次渲染100条数据不分页的时候，页面加载也超级慢，同时项目又是 antd 4版本不想升级antd5。如果开源后，通知大家。

**Comment by AshanPerera98** [comment]
Hi all,
I'm having the same issue when combining antd table and form with multiple cross-row validations. I have opened an issue with a demo repo to reproduce my issue with a detailed description. Can someone look into it and, if possible, help me to find a solution?

Please find the link to my issue below
https://github.com/ant-design/ant-design/issues/57007
