### ISSUE TITLE
Select 选项配合 Badge 或 Tag 使用，选项内容底部有多余空隙

### ISSUE THREAD

**Issue by fanck0605** [ant-design/ant-design#43069]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-6-1-forked-kr8c3y?file=/demo.tsx)

### Steps to reproduce

无需操作，查看下拉框样式

### What is expected?

Badge 或 Tag 底部**无**多余空隙

### What is actually happening?

Badge 或 Tag 底部**有**多余空隙

![image](https://github.com/ant-design/ant-design/assets/28819315/82e839d0-f18e-4b44-964c-3e56eb12f60a)

| Environment | Info |
| --- | --- |
| antd | 5.2.0 |
| React | 18 |
| System | Windows 11 |
| Browser | Chrome 114 |

---
应该是这个问题导致的：https://stackoverflow.com/questions/9273016/why-is-this-inline-block-element-pushed-downward

http://jsfiddle.net/d059q1Lp/15/

![image](https://github.com/ant-design/ant-design/assets/28819315/679a8a31-338f-46f2-b4ec-f80b2ca0e645)

Antd 相关代码： https://github.com/ant-design/ant-design/blob/446e8336dc87be89a8625d6e94962726af32c757/components/select/style/dropdown.tsx#L108-L110

加上了这个会导致，options里面随便用个 span 包一下内容就会显示异常

**Comment by Yuiai01** [comment]
这个问题应该是当初解决 select 的 options 中嵌套 Typography 会存在文字不对齐的情况，或许这块代码应该 revert 掉，求CC @MadCcc  @LongHaoo

**Comment by MadCcc** [comment]
@Yuiai01 来个 PR 看看效果吧。这个确实不应该做的太耦合

**Comment by Yuiai01** [comment]
> @Yuiai01 来个 PR 看看效果吧。这个确实不应该做的太耦合

好
