### ISSUE TITLE
Popconfirm组件在react严格模式下，包裹一个自定义组件，会返回”findDOMNode is deprecated in StrictMode.“错误

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#43064]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-m5mp5g?file=/index.js)

### Steps to reproduce

设置严格模式，Popconfirm组件包裹一个自定义组件，控制台报错

### What is expected?

严格模式下，控制台不出现警告

### What is actually happening?

控制台出现警告：”Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper4 which is inside StrictMode. Instead, add a ref directly to the element you want to reference.“

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | "react": "^18.2.0" |
| System | win10 |
| Browser | chrome114 |

**Comment by zombieJ** [comment]
就如它 warning 的，你需要给自定义组件 `forwardRef`:

https://codesandbox.io/s/antd-reproduction-template-forked-xxgqdp

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/43064#issuecomment-1595739073

**Comment by wxs77577** [comment]
项目中的临时解决方案， 确保安装 `rc-resize-observer`后，在`main.tsx`中全局修复一下:

```ts
import RcResizeObserver from "rc-resize-observer";
const _render = RcResizeObserver["render"];
RcResizeObserver["render"] = (props, ref) => {
  return _render(
    {
      ...props,
      children:
        typeof props.children === "function" ? (
          props.children
        ) : (
          <span ref={ref}>{props.children}</span>
        ),
    },
    ref
  );
};
```

**Comment by wxs77577** [comment]
https://github.com/ant-design/ant-design/issues/43064#issuecomment-2456508430
