### ISSUE TITLE
自定义主题时，导入theme组件报错import { theme } from 'antd';报错Cannot find module 'antd/es/theme/style'

### ISSUE THREAD

**Issue by changguilei** [ant-design/ant-design#43066]
### Reproduction link

[https://ant.design/docs/react/customize-theme-cn](https://ant.design/docs/react/customize-theme-cn)

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

1

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 最新 |
| System | window |
| Browser | chrome |

**Comment by changguilei** [comment]
之前看有人提过这个问题，也没解决

**Comment by zombieJ** [comment]
关掉 babel-plugin-import 
Duplicate of #39344

**Comment by changguilei** [comment]
> 关掉 babel-plugin-import Duplicate of #39344

关掉？ npm uninstall  babel-plugin-import吗，但是这样启动项目就会报错

**Comment by changguilei** [comment]
> 关掉 babel-plugin-import Duplicate of #39344

我用的creat-react-app 不是vite 咋解决啊，我改成
// 按需引入antd组件
        fixBabelImports("import", {
            libraryName: "antd",
            libraryDirectory: "es",
            style: (name) => name !== 'theme' && `antd/es/${name}/style`,
        }),

还行不行

**Comment by yoyo837** [comment]
拜托你看看文档

**Comment by changguilei** [comment]
> 

看了啊，是那点我疏忽了吗？

**Comment by BoyYangzai** [comment]
> > 关掉 babel-plugin-import Duplicate of #39344
> 
> 我用的creat-react-app 不是vite 咋解决啊，我改成 // 按需引入antd组件 fixBabelImports("import", { libraryName: "antd", libraryDirectory: "es", style: (name) => name !== 'theme' && `antd/es/${name}/style`, }),
> 
> 还行不行


@changguilei 
现代的打包工具一般是自动开启 `treeshaking` 的 
而 `antd` 提供了 `es` 这个目录来做 `treeshaking`, 所以不需要使用 `babel-plugin-import `

**Comment by afc163** [comment]
可以把 fixBabelImports 这段代码去掉。

**Comment by xiaodaxuetu** [comment]
将 import {theme} from 'antd';  改成 import theme from 'antd/es/theme';
