### ISSUE TITLE
spin动画快速切换能否优化？

### ISSUE THREAD

**Issue by eastpiger** [ant-design/ant-design#4306]
- antd 版本: 2.1
- 操作系统及其版本: ALL
- 浏览器及其版本: ALL

Spin组件效果很赞，不过如果等待时间特别少的话，动画自身的淡入淡出反而会占用了更多的时间。

比如说，我在异步请求中间用spin做过渡，在内网下请求几乎是秒出的情况下，看到内容已经更新了，然而spin还在淡入，然后转一下，然后淡出😂

不知是否有优化的办法呢？

**Comment by RaoHai** [comment]
感觉跟这个有点冲突。。

https://github.com/ant-design/ant-design/issues/2398

**Comment by benjycui** [comment]
@eastpiger 你的情况就不要用 Spin 了，如果能保证加载速度的话。

**Comment by eastpiger** [comment]
@benjycui 我这种情况仅限于内网会出现秒开，外网访问还是要spin等一会的呢。感觉确实#2398 似乎和这个有关系

**Comment by benjycui** [comment]
是这个原因，加过度动画是为了解决闪烁的问题。

其实还可以加个延时出现加载动画的处理，这样能缓解秒开的问题。

**Comment by afc163** [comment]
@benjycui 可以试试。
