### ISSUE TITLE
使用 Antd  ConfigProvider 中的 iconPrefixCls 属性不能设置图标统一样式前缀

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design#43077]
### Reproduction link

[https://ant.design/components/config-provider-cn](https://ant.design/components/config-provider-cn)

### Steps to reproduce

https://github.com/ant-design/ant-design-icons/issues/579

### What is expected?

可以替换 ant-design-icons 的图标统一前缀。

### What is actually happening?

目前没有正常替换。

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | "react": "^18.2.0", |
| System | Mac OS 11.7.2 (20G1020) |
| Browser | Google Chrome  版本 109.0.5414.87（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
`npm ls @ant-design/icons` 看下是否项目中依赖的和 antd 依赖的版本不一致？

**Comment by hqwlkj** [comment]
> `npm ls @ant-design/icons` 看下是否项目中依赖的和 antd 依赖的版本不一致？
```

├── @ant-design/icons@5.1.4
└─┬ antd@5.6.1
  └── @ant-design/icons@5.1.0

```

**Comment by Yuiai01** [comment]
本地测试了一下，确实是没有设置成功，我来康康这个问题

**Comment by MadCcc** [comment]
@hqwlkj 要保证 icons 版本一致，context 才会生效。

**Comment by hqwlkj** [comment]
> @hqwlkj 要保证 icons 版本一致，context 才会生效。


好的，我试试。
