### ISSUE TITLE
Error in Customize Theme page in the docs  

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#43085]
### Reproduction link

[https://ant.design/docs/react/customize-theme](https://ant.design/docs/react/customize-theme)

### Steps to reproduce

Try to use `token.colorPrimary`

### What is expected?

Works

### What is actually happening?

> Property 'colorPrimary' does not exist on type '{ theme: Theme<SeedToken, MapToken>; token: GlobalToken; hashId: string; }'.
> ts(2339)

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome |

---
Correct the [docs](https://ant.design/docs/react/customize-theme) to say `token.token.colorPrimary`

**Comment by zombieJ** [comment]
Doc is:

```tsx
const { token } = useToken();
```

Not

```tsx
const token = useToken();
```
