### ISSUE TITLE
官网博客增加专栏链接

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#43087]
1. 文章增加专栏链接配置

```diff
  ---
  title: 静态方法之痛
  date: 2023-04-26
  author: zombieJ
+ column_url: https://zhuanlan.zhihu.com/p/633333904
  ---
```

2. 在 https://ant.design/docs/blog/why-not-static-cn 底部放一个『去专栏参与讨论』的链接，链接到上面。

**Comment by afc163** [comment]
样式要自己发挥一下了，底部应该是类似讨论区的样式。

**Comment by li-jia-nan** [comment]
这个我来搞吧

**Comment by afc163** [comment]
👍🏻 还得是你

**Comment by li-jia-nan** [comment]
大佬，这个有没有相关的可以参考的样式看一下

**Comment by li-jia-nan** [comment]
这样可以吗？

<img width="827" alt="image" src="https://github.com/ant-design/ant-design/assets/49217418/e2a60d83-b317-4e8e-9968-18b8d59237bf">

**Comment by afc163** [comment]
挺好的，👍🏻
