### ISSUE TITLE
InputNumber Safari 下的问题

### ISSUE THREAD

**Issue by arvinxx** [ant-design/ant-design#43088]
### Reproduction link

[https://ant-design.antgroup.com/components/input-number-cn#components-input-number-demo-size](https://ant-design.antgroup.com/components/input-number-cn#components-input-number-demo-size)

### Steps to reproduce

1. 用 Safari 打开上述链接；
2. 使用触控板快速点击上或下箭头 3 下，位置保持不变；

### What is expected?

值只增加 3 

### What is actually happening?

值在增加3后，开始自动增加

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18 |
| System | macOS 13 |
| Browser | Safari |

---
Chrome 下正常

**Comment by MadCcc** [comment]
暂时无法复现，给个录屏看看？

**Comment by poyiding** [comment]
在safari版本15.2 (17612.3.6.1.6) 可以复现

**Comment by kiner-tang** [comment]
这边复现了：
![屏幕录制2023-07-02 10 46 18 mov](https://github.com/ant-design/ant-design/assets/10286961/ead62cc5-b7a1-4e31-a6cf-5cded7340ced)

**Comment by kiner-tang** [comment]
这个问题有同学在跟进吗？

**Comment by kiner-tang** [comment]
应该是在 safari 当中，快速连续点击会被误判为长按，从而导致触发了长按自动累加的逻辑

**Comment by kiner-tang** [comment]
<img width="356" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/511647ba-a58c-4a20-9408-91cc148e5753">
在 safari 当中，快速连续点击可能会导致 onmouseup 事件先于 onmousedown 事件点击，从而导致逻辑混乱

**Comment by afc163** [comment]
> 这个问题有同学在跟进吗？

无。

**Comment by kiner-tang** [comment]
> > 这个问题有同学在跟进吗？
> 
> 无。

那我抽空看看有没有办法解决。
