### ISSUE TITLE
table 筛选变成多个同时展开，正常只能展开一个

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#43093]
### Reproduction link

[https://ant.design/~demos/components-table-demo-head](https://ant.design/~demos/components-table-demo-head)

![微信截图_20230619141150](https://github.com/ant-design/ant-design/assets/3166799/6e73a0f2-ea0b-46d0-a482-2f29e53c82c9)

### Steps to reproduce

操作筛选

### What is expected?

不同时可展开筛选

### What is actually happening?

同时展开多个

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.0 |
| System | win10 |
| Browser | Chrome 100 |

**Comment by afc163** [comment]
同时展开感觉也不算是问题，会有什么负向体验么？

**Comment by hihuangwei** [comment]
> 同时展开感觉也不算是问题，会有什么负向体验么？

可以加个 api 控制不同时展开，原来是不能同时展开，某个版本开始就是同时展开了

**Comment by afc163** [comment]
> 同时展开感觉也不算是问题，会有什么负向体验么？

好像没有回答我的问题？

**Comment by hihuangwei** [comment]
> > 同时展开感觉也不算是问题，会有什么负向体验么？
> 
> 好像没有回答我的问题？

多个同时展开会有重叠问题。多个同时展开并没有实际的作用

**Comment by linxianxi** [comment]
打开第二个筛选的时候，第一个筛选没有触发 onOpenChange，去掉下面阻止冒泡就可以。但是又不能去掉，去掉会冒泡引起触发排序。猜测是 rc-trigger 改造的问题 @zombieJ 
<img width="469" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/60e912e2-1934-4c86-bb2d-affd38a67a5e">

**Comment by zombieJ** [comment]
> 打开第二个筛选的时候，第一个筛选没有触发 onOpenChange，去掉下面阻止冒泡就可以。但是又不能去掉，去掉会冒泡引起触发排序。猜测是 rc-trigger 改造的问题 @zombieJ <img alt="image" width="469" src="https://user-images.githubusercontent.com/47104575/246990616-60e912e2-1934-4c86-bb2d-affd38a67a5e.png">

受控调一下就好

**Comment by NaveenKumarVUK** [comment]
Is it possible to open only one filter expansion at one time? 

If NO, then its normal behaviour or its a bug?

**Comment by DVSoftware** [comment]
This issue still happens to me, i can't figure out why. Upgraded both antd and trigger libraries.

**Comment by yoyo837** [comment]
> 

Could you provide a reproduction link and create a new issue for that?

**Comment by DVSoftware** [comment]
> > 
> 
> Could you provide a reproduction link and create a new issue for that?

I would gladly, however, i can't reproduce it on a minimal project. It would help if you could give me some pointers on how to debug this, can't find where this is handled?

**Comment by DVSoftware** [comment]
@yoyo837 When i comment out `e.stopPropagation();` as @linxianxi suggested, it works fine, however, i don't see it as a good solution to patch the library this way. I still can't figure out why it works on new project, and not in mine.

**Comment by DVSoftware** [comment]
Removing yarn.lock solved the issue. Apparently there were multiple trigger versions installed in the different dependencies of ant, which caused a discrepancy.
