### ISSUE TITLE
能不能统一一下superagent和reqwest？

### ISSUE THREAD

**Issue by haibinyu** [ant-design/ant-design#431]
ant-design的table中使用ajax库是reqwest，但是upload中使用的是superagent，这个可不可以统一使用一个呢？这样代码容易阅读，打包后也会小点。

**Comment by popomore** [comment]
统一 +1

**Comment by yiminghe** [comment]
table 会去除 ajax 功能

**Comment by kevyu** [comment]
@yiminghe table的数据源都是自己处理了?

**Comment by yiminghe** [comment]
推荐自己处理

**Comment by kevyu** [comment]
恩，自己处理更灵活一些, :+1
