### ISSUE TITLE
Form.Item normalize 在windows下全角“逗号”处理异常 macOS正常

### ISSUE THREAD

**Issue by zhouzongren** [ant-design/ant-design#43103]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-6-2-forked-kmw24z?file=/demo.tsx:599-872)

### Steps to reproduce

定义了normalize 函数 将全角逗号替换成半角逗号，输入1个全角逗号，输入框显示2个半角逗号

### What is expected?

输出的半角逗号和输入的全角逗号数量一致，仅做替换

### What is actually happening?

输出的半角逗号数量翻倍

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.0.0 |
| System | windows |
| Browser | chrome 113.0.5672.129 |

---
针对用户输入中文逗号做格式化处理

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/30164#issuecomment-820913172
