### ISSUE TITLE
how can display DatePicker Month of week???

### ISSUE THREAD

**Issue by Chars4785** [ant-design/ant-design#43105]
### What problem does this feature solve?

i used DatePicker props picker="week" but display is 2023-32th. if i chose 2023-05-03 and then i want to show like this "2023-05-1th" how can i do...?

### What does the proposed API look like?

"2023-05-1th"

**Comment by BoyYangzai** [comment]
@Chars4785 
HI bro
why you want `2023-05-1th`? what it means
 DatePicker with props `picker="week"` means the nth wekk in a month，it works correctly

**Comment by Chars4785** [comment]
hello!  @BoyYangzai  
i need to show the date. 2023-06-3th into datepicker of date text.

It is necessary that the shape shown in the DatePicker is shown as 2023-06-3th. I just want to know how many weeks this month is today. Can't I just customize the text shown?

<img width="245" alt="image" src="https://github.com/ant-design/ant-design/assets/24587071/2165eda3-524e-4b62-bc68-71f3e5f273f1">

**Comment by linxianxi** [comment]
You can do this using format
https://codesandbox.io/s/ri-qi-ge-shi-antd-5-6-2-forked-grqrw4

**Comment by Chars4785** [comment]
@linxianxi  wow....thank you !!!!!
