### ISSUE TITLE
Transfer穿梭框设置了rowKey之后，无法使用onSelectChange来设置selectedKeys

### ISSUE THREAD

**Issue by DinghaoJoe** [ant-design/ant-design#43113]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fen-ye-antd-5-6-2-forked-83cs3n)

### Steps to reproduce

使用rowkey来指定数据列的主键，手动控制selectedKeys

### What is expected?

和之前保持一致，返回所有的数据

### What is actually happening?

onSelectChange返回的sourceSelectedKeys是当前选中的数据，而不再是5.6.2之前的所有数据

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.2.0 |
| System | macos 13.4 (22F66) |
| Browser | Google Chrome 版本 114.0.5735.133（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
估计有 BUG，我看一下
