### ISSUE TITLE
是否支持横向表格？

### ISSUE THREAD

**Issue by imperio-wxm** [ant-design/ant-design#4312]
antd里的表格都是固定列的，如何才能做到固定行？

![如图](https://cloud.githubusercontent.com/assets/8111349/21347723/d2256c3a-c6e4-11e6-9cda-3060494a9f8c.png)

**Comment by benjycui** [comment]
就不能描述清楚一点么？最好有现成的参考。

**Comment by imperio-wxm** [comment]
@benjycui 呃，其实就是表格横过来，以第一列为所有表头，后面的列为数据。看到antd例子里全部是以第一行为表头，后面的行为数据。如上图，可以在数学列后面再加一列为数据，但表头依旧是所有英文字段。谢谢！

**Comment by benjycui** [comment]
> antd里的表格都是固定列的，如何才能做到固定行？

这句和你标题描述的是不同的需求吧。

**Comment by imperio-wxm** [comment]
@benjycui 固定列的意思一列只能固定一个类型，比如name列，则这一列都要是name值。固定行正好相反，这样描述不合适吗？那需求应该清楚了，antd是否可以实现？

**Comment by benjycui** [comment]
你说固定列，会和这个 feature 混淆的 https://ant.design/components/table/#components-table-demo-fixed-columns

antd 要完全支持不容易，涉及多表头，固定列等 feature 的转换，我们没有这个需求也没有人手做这事，不过如果你有兴趣可以尝试并 PR，thanks

**Comment by benjycui** [comment]
还是不考虑支持了，想了一下，antd 要完全支持横向表头的话，复杂度会提升很多，维护起来很麻烦。

**Comment by imperio-wxm** [comment]
@benjycui  好的，谢谢！
