### ISSUE TITLE
colorText, fontSize tokens don't work (Popconfirm component)

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#43127]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/popconfirm-tokens-do-not-work-mjv277)

### Steps to reproduce

1. import ConfigProvider
2. specify components tokens (colorText, fontSize) for Popconfirm
3. look at result

### What is expected?

These tokens affect component display

### What is actually happening?

These tokens don't work 

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome 114 |

**Comment by Yuiai01** [comment]
I notice that the style is overwritten. 
<img width="490" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/eeb34ca8-3b47-4f1c-a73a-4841f17904d5">

**Comment by zombieJ** [comment]
Popconfirm extends the style of Popover. I think this can be improved: 
https://codesandbox.io/s/popconfirm-tokens-do-not-work-forked-gl6nd8?file=/index.tsx

**Comment by evgeniyworkbel** [comment]
@zombieJ
- colorText token of Popover sets description text color of Popconfirm. Okay.
- fontSize token of Popover doesn't affect to font size of Popconfirm _in my project_. I saw that in your codesandbox this works, but in my project no. A bit later i will update my codesandbox sample making similar to my project using of Popconfirm

**Comment by evgeniyworkbel** [comment]
I've just updated [codesandbox sample](https://codesandbox.io/s/popconfirm-tokens-do-not-work-mjv277?file=/index.js). Now it's almost that I use antd in my project

**Comment by evgeniyworkbel** [comment]
[screenshot](https://disk.yandex.ru/i/Zl8rgfo3OgfvPQ)
