### ISSUE TITLE
Progress的size属性允许为百分比

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design#43120]
### What problem does this feature solve?

当`type=line`时，我只想改变它的宽度，在4.x下有个`strokeWidth`可以使用但在5.x下会报废弃警告

### What does the proposed API look like?

`size={["100%",20]}`

**Comment by linxianxi** [comment]
试了下可以这样
```
<Progress percent={30}  size={[-1, 20]} />
```

**Comment by IceLeach** [comment]
> 试了下可以这样
> 
> ```
> <Progress percent={30}  size={[-1, 20]} />
> <Progress percent={30}  size={[undefined, 20]} />
> <Progress percent={30}  size={[null, 20]} />
> ```

确实可以,但是类型定义是`[number, number]`，文档里也没有说明

**Comment by IceLeach** [comment]
测试了下这样使用是有效果的
```ts
<Progress percent={30}  size={["50%", 20]} />
```
是否可以考虑把定义里的`number`改成`number | string`，像-1这样的值用起来也不好理解呀

**Comment by MadCcc** [comment]
可以来个 PR

**Comment by Ali-ovo** [comment]
我来改吧
