### ISSUE TITLE
antd5.5.2版本subMenuStyle这个API不好用

### ISSUE THREAD

**Issue by 97702573** [ant-design/ant-design#43137]
### What problem does this feature solve?

为子菜单的设置 style 属性

### What does the proposed API look like?

为子菜单的设置 style 属性

**Comment by afc163** [comment]
文档里目前没有这个 API。

**Comment by 97702573** [comment]
@afc163 https://preview-42802-ant-design.surge.sh/components/menu-cn这个文档里面有的

**Comment by 97702573** [comment]
https://preview-42802-ant-design.surge.sh/components/menu-cn

**Comment by afc163** [comment]
@97702573 以官方正式文档为准：https://ant.design/components/menu-cn
