### ISSUE TITLE
Slider组件disabled状态未与上级Form同步

### ISSUE THREAD

**Issue by Starpuccino** [ant-design/ant-design#43140]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sp3z7q)

### Steps to reproduce

第一个slider应当是disabled

### What is expected?

第一个slider应当是disabled

### What is actually happening?

第一个slider不是disabled

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.0.0 |
| System | macOS 13.4 Apple silicon |
| Browser | Microsoft Edge 版本 114.0.1823.55 (正式版本) (arm64) |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/43142
