### ISSUE TITLE
table的expandIconColumnIndex在有rowSelection，开始顺序具有不同的逻辑

### ISSUE THREAD

**Issue by rocketsbigfan** [ant-design/ant-design#43143]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-lake-yrwk46?file=/index.js)

### Steps to reproduce

表现一：
1.设置rowSelection属性后，想把展开收起图标放在Name列，得把expandIconColumnIndex设置为3，似乎表格第一行是按下标1开始算的
表现二：
1.不设置rowSelection，想把展开收起图标放在Name列，只需把得把expandIconColumnIndex设置为1，这个符合我们的常规逻辑

### What is expected?

无论有没有rowSelection，expandIconColumnIndex的值都可以按照下标0开始

### What is actually happening?

设置rowSelection和不设置rowSelection，expandIconColumnIndex差了2，不知道是不是正常逻辑

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18  |
| System | macos |
| Browser | chrome 114.0.5735.133 |

**Comment by rocketsbigfan** [comment]
![WeChatd0be858b9595691fa4496cd919369806](https://github.com/ant-design/ant-design/assets/20547894/5eb2f78d-51fb-432a-98eb-b0736f6e61f9)
![image](https://github.com/ant-design/ant-design/assets/20547894/851df5b9-3934-420e-8d3c-ca34f5ffaceb)

**Comment by zombieJ** [comment]
这个 `expandIconColumnIndex` 属性不太好，最好是有 `Table.EXAND_COLUMN` 这么一个属性:
```tsx
columns={[
  { dateIndex: 'xxx' }, 
  Table.EXAND_COLUMN,
  { dateIndex: 'xxx' }, 
]}
```

**Comment by linxianxi** [comment]
> 这个 `expandIconColumnIndex` 属性不太好，最好是有 `Table.EXAND_COLUMN` 这么一个属性:
> 
> ```tsx
> columns={[
>   { dateIndex: 'xxx' }, 
>   Table.EXAND_COLUMN,
>   { dateIndex: 'xxx' }, 
> ]}
> ```

感觉这样不太好，它不是单独的一列，而是存在某一个列里的。另外 expandIconColumnIndex 文档里咋没有，是漏了还是故意不放给用户的

**Comment by rocketsbigfan** [comment]
> > 这个 `expandIconColumnIndex` 属性不太好，最好是有 `Table.EXAND_COLUMN` 这么一个属性:
> > ```tsx
> > columns={[
> >   { dateIndex: 'xxx' }, 
> >   Table.EXAND_COLUMN,
> >   { dateIndex: 'xxx' }, 
> > ]}
> > ```
> 
> 感觉这样不太好，它不是单独的一列，而是存在某一个列里的。另外 expandIconColumnIndex 文档里咋没有，是漏了还是故意不放给用户的

是的，会有需求是把这个按钮放在常规列里，像这种
![image](https://github.com/ant-design/ant-design/assets/20547894/031f19f2-9949-42e1-b1a8-36e057cb0565)

**Comment by zombieJ** [comment]
看了一下，已经是支持的。文档里没有是因为这个接口已经替换成 COLUMN 占位了：https://codesandbox.io/s/xenodochial-lena-ktwwjr?file=/index.tsx

**Comment by WangJM001** [comment]
这是两种场景需求，一个是可展开行，一个是树形展示。
当树形展示时Table.EXAND_COLUMN是不生效的，仅expandIconColumnIndex有效，所以Table.EXAND_COLUMN点位没法同时适应两种场景
