### ISSUE TITLE
How can i use colorBgTextActive?

### ISSUE THREAD

**Issue by nguyentung19** [ant-design/ant-design#43156]
Please show a example of colorBgTextActive in ConfigProvider?

### What problem does this feature solve?

Control the background color of text in active state.

### What does the proposed API look like?

colorBgTextActive

**Comment by kiner-tang** [comment]
<img width="1443" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/16bd8213-d7ba-42d1-938c-13b5f5f81f43">
You can long press the button or use development tools to set active state. And then, you will see it.

https://codesandbox.io/s/an-niu-lei-xing-antd-5-6-2-forked-yw8z4y?file=/demo.tsx

**Comment by nguyentung19** [comment]
Thank you so much
