### ISSUE TITLE
Added a column in Table to show serial number(e.g from 1 to ...100...), when page change serial number change from past number, keep the serial number column changing (still from 1 to ...100.....) 

### ISSUE THREAD

**Issue by Meet-Bhalodia** [ant-design/ant-design#43153]
### What problem does this feature solve?

This will help when the table is exported by users, and they will get the srno in respected file format(CSV, Print, PDF, JSON, etc), and it make less effort from programmer side to direct set column name in respected export functionality. 

### What does the proposed API look like?

sorry i can't help.

**Comment by afc163** [comment]
You could add it as a column in `<Table colunms={...} />`.

**Comment by Meet-Bhalodia** [comment]
{
		  title: "SrNo",
		  defaultSortOrder: "ascend",
		  sorter:(a, b) => a.id - b.id,
		  render: (id, record,srno, index) => srno.indexOf(record) + 1,
		  width: "20%",
		},

This will render 1 to 10 in every page, i need 1 to 10 for first pageand 11 to 20 for second page and so on.
