### ISSUE TITLE
2.5.2 Table表格未设置loading属性时出现loading的遮罩层

### ISSUE THREAD

**Issue by dodospace** [ant-design/ant-design#4316]
#### 发生问题的环境是：

- antd 版本: 2.5.2
- 操作系统及其版本: macOS Sierra 10.12.1
- 浏览器及其版本: Chrome 54.0.2840.59 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

引入 antd 的 Table 组件

#### 您期待的结果是:

像官网一样正常显示表格

#### 实际上的结果是:

表格是正常展现，但是会有一层loading的遮罩层覆盖于表格上；
通过React develop tool工具查看，会有一层Animate包括于Table。如下：
```javascript
<Animate component="div" className="ant-spin-nested-loading" transitionName="fade">
       ...
</Anumate>

```

#### 在线演示的代码

http://codepen.io/anon/pen/QGomNM?editors=001  实际代码如这里，但是这里显示正常，在组件里显示就如问题所述。

**Comment by yesmeck** [comment]
试试  `rm -rf node_modules && npm install`

**Comment by afc163** [comment]
确保使用的是 2.5.2 的样式代码。这个之前有人遇到过的，他的问题就是 2.4 的样式代码配合了 2.5 的 js 来用。

**Comment by dodospace** [comment]
我也找到问题的根源了，确实是引用了错误样式的问题！
