### ISSUE TITLE
<Space /> report ref error somehow 

### ISSUE THREAD

**Issue by GuichiZhao** [ant-design/ant-design#43178]
### Reproduction link

[https://ant.design/components/space](https://ant.design/components/space)

### Steps to reproduce

`<Space.Compact>` and `<Space size='small'>` will report error react-dom.development.js:86 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()
Interesting enough  `<Space>` will **NOT** report such error, I can guess there is something wrong with styleProvider implementation

### What is expected?

not error 

### What is actually happening?

error

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
Space.Compact not support `ref` currently

**Comment by GuichiZhao** [comment]
I never put `ref` on  `Space.Compact` nor `Space`, it just report some unrelated error on `Space.Compact`, when I switched to `Space`, the error is gone. It just happened when I upgraded antd today.

**Comment by GuichiZhao** [comment]
Actually, I investigate the error this afternoon and identify that something quite unrelated can cause the error. i.e. putting a `<Dropdown />` inside the `<Space />`.  My project is kind of complicated and the error seem irrelevant so I can not provide a reproducible code, sorry for that
