### ISSUE TITLE
Form.Item下使用Switch的时候，Item中写name会导致点击label也可以切换Switch状态

### ISSUE THREAD

**Issue by haiNono** [ant-design/ant-design#43175]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-leakey-r7q9rh?file=/src/App.js)

### Steps to reproduce

点击表单label

### What is expected?

点击label的时候，switch不应该切换

### What is actually happening?

点击label，switch也跟着切换了

### 截图

![动画](https://github.com/ant-design/ant-design/assets/134601929/d2294fdb-f01f-407d-824c-1b39c8f6729d)

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.2.0 |
| System | windows10 |
| Browser | chrome 113.0.5672.127（正式版本） （64 位） |

**Comment by haiNono** [comment]
地址：https://codesandbox.io/s/kind-leakey-r7q9rh?file=/src/App.js

**Comment by afc163** [comment]
这是预期的，点击 label 触发响应的控件交互，参考原生行为：https://codepen.io/afc163/pen/MWzbRGe
