### ISSUE TITLE
引入 @ant-design/charts 导致 Tooltip 箭头样式错误

### ISSUE THREAD

**Issue by wqcstrong** [ant-design/ant-design#43186]
### Reproduction link

[https://codepen.io/WQC/pen/poQRbgK?editors=001](https://codepen.io/WQC/pen/poQRbgK?editors=001)

### Steps to reproduce

- script 引入 react 、 react-dom、@ant-design/charts;
- 使用 Tooltip 组件

### What is expected?

正常显示

### What is actually happening?

箭头样式有问题

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by wqcstrong** [comment]
这个问题找的我好苦 😭。。。确认的时候我甚至有点不敢相信。。。

**Comment by wqcstrong** [comment]
这个问题找的我好苦 😭。。。确认的时候我甚至有点不敢相信。。。

**Comment by MadCcc** [comment]
antd v4 与 v5 样式混淆，改一下 v5 的 antd 的 `prefixCls` 就好了。
```
<ConfigProvider prefixCls="antd5">
  <Tooltip title="一个大B兜">
    <Button type="primary">鼠标放这里查看</Button>
  </Tooltip>
</ConfigProvider>
```

**Comment by wqcstrong** [comment]
在配置 prefixCls 之前，有很多直接在样式文件中修改 `.ant-*` 的样式。这里配置了 prefixCls 之后有什么比较好的处理建议吗

**Comment by wqcstrong** [comment]
> antd v4 与 v5 样式混淆，改一下 v5 的 antd 的 `prefixCls` 就好了。
> 
> ```
> <ConfigProvider prefixCls="antd5">
>   <Tooltip title="一个大B兜">
>     <Button type="primary">鼠标放这里查看</Button>
>   </Tooltip>
> </ConfigProvider>
> ```

@MadCcc @zombieJ 请问是什么原因导致两个版本的样式混淆。除了 prefixCls 这种方式还有别的方案吗？麻烦告知一下混淆的原因，我想从根本上解决。

**Comment by afc163** [comment]
@wqcstrong 最好是 @ant-design/charts 能支持 antd 5 ，不要两个版本混用。

**Comment by wqcstrong** [comment]
大概知道是什么原因了，因为 [@ant-design/charts 里依赖了 antd@^4.6](https://github.com/ant-design/ant-design-charts/blob/master/packages/flowchart/package.json#L51)。

一个临时解决方案，供其他人参考：如果你的项目里只是用到了 @ant-design/charts 的一部分 (比如 plot)，没有依赖 @ant-design/flowchart (和 plot 一样都是 @ant-design/charts 的一部分)，那就参考文档的[按需引入](https://charts.ant.design/manual/getting-started#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5)，不要直接用 @ant-design/charts 这个完整的包。

顺便给维护的大佬们一个反馈：我是想将一个很大的项目从 antd@^4 升级到 v5，上面这个问题最终是通过排除法发现 @ant-design/charts 导致的，也就是说 _**排查过程中控制台、审查元素都无法一眼看到是 charts 的影响**_。我不确定是不是 v5 的设计导致的，这个 debug 体验有待改善。

@afc163 @MadCcc 感谢各位 ❤️
