### ISSUE TITLE
Popover内容变化的时候会突然改变位置然后再改变回来

### ISSUE THREAD

**Issue by hungtcs** [ant-design/ant-design#43187]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-pz4kv9?file=/index.js)

### Steps to reproduce

1. 打开复现连接，可以看到一个简单的列表
2. 鼠标放在最下面的几个列表项的头像上面，会出现Popover。
3. 仔细观察Popover的位置，在1s之后，Popover的内容会改变。

### What is expected?

在空间充足的情况下，Popover的位置不变化

### What is actually happening?

在空间充足的情况下，鼠标放在最下面的几个列表项时，Popover有很大几率会闪烁一下，
位置突然变到下面，然后又突然回到上面。

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | MacOS 13.3 (22E252) |
| Browser | Google Chrome 111.0.5563.146 (arm64) |

---
鼠标放到下面的几个列表项的头像上，多试几次，很大几率会出现。

**Comment by zombieJ** [comment]
merge into #42881

**Comment by hungtcs** [comment]
@zombieJ 此问题并没有在 https://github.com/ant-design/ant-design/issues/42881 中被修复，截止目前 5.9.0 仍然可以被复现。

https://github.com/ant-design/ant-design/assets/11692935/d2a970f5-132f-41cc-baef-b388ee4ee8aa

**Comment by yoyo837** [comment]
> @zombieJ 此问题并没有在 #42881 中被修复，截止目前 5.9.0 仍然可以被复现。
> 
>  Kapture.2023-09-14.at.09.36.53.mp4

开个新Issue?

**Comment by hungtcs** [comment]
> > @zombieJ 此问题并没有在 #42881 中被修复，截止目前 5.9.0 仍然可以被复现。
> > Kapture.2023-09-14.at.09.36.53.mp4
> 
> 开个新Issue?

👌
