### ISSUE TITLE
Select组件的showSearch是从value中做检索， 应该从label中检索

### ISSUE THREAD

**Issue by rick-chou** [ant-design/ant-design#43188]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-qian-antd-5-6-3-forked-kv43f2?file=/demo.tsx:58-64)

### Steps to reproduce

输入rick 应该从label中筛选

### What is expected?

从提供的label中做筛选

### What is actually happening?

从value中筛选了 但是value用户都不可见

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | macos 12.6.3 |
| Browser | chrome |

**Comment by zombieJ** [comment]
用 `optionFilterProp` 设置 `label` 即可，默认是 `value` 是因为 `label` 能接收 ReactNode，不一定是 `string` 类型，所以不一定可以搜索。
