### ISSUE TITLE
console.error: "Warning: [antd: Form.List] Miss `name` prop."  in nested list

### ISSUE THREAD

**Issue by wheercool** [ant-design/ant-design#43195]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9s8l5y?file=/index.js)

### Steps to reproduce

The issue happens for nested Form.List

1. Create nested Form.List
2. Open console

### What is expected?

No error in console

### What is actually happening?

I assume that name =0 is treaded as undefined

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.2.0 |
| System | MacOS |
| Browser | any |

**Comment by Yuiai01** [comment]
This error is due to the conversion of 0 to false. I'll fix it.
