### ISSUE TITLE
组件Drawer通过拖拽改变 width 时十分卡顿，拖拽不流畅

### ISSUE THREAD

**Issue by luichooy** [ant-design/ant-design#43194]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wtvx4d?file=/App.jsx)

### Steps to reproduce

1. 点击按钮Open custom drawer， 打开自定义 drawer，拖动左边红色区域，体验十分流畅
2. 点击按钮Open antd drawer,打开 antd drawer, 拖动左边红色区域，体验很卡顿，宽度改变滞后鼠标位置

### What is expected?

想请教下是什么原因，是否是 antd drawer 组件内部都宽度变化做了类似于节流的操作，又或者 dom 结构过于复杂导致性能下降

### What is actually happening?

拖拽改变 drawer 组件 width 时，体验卡顿

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | MacOs |
| Browser | Edge |

**Comment by MadCcc** [comment]
有 transition，修改宽度会有动画

**Comment by zombieJ** [comment]
`transition` 影响，剥掉就好了哈：
https://codesandbox.io/s/antd-reproduction-template-forked-gjddcz?file=/App.css

**Comment by luichooy** [comment]
> `transition` 影响，剥掉就好了哈： https://codesandbox.io/s/antd-reproduction-template-forked-gjddcz?file=/App.css

好的  十分感谢

**Comment by luichooy** [comment]
> 

十分感谢🫡
