### ISSUE TITLE
modal使用destroyOnClose无法获取dom节点

### ISSUE THREAD

**Issue by Sharang-heng** [ant-design/ant-design#43196]
### Reproduction link

[https://stackblitz.com/run?file=demo.tsx](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

点击按钮打开弹窗，打印获取的dom

### What is expected?

希望打开弹窗时能获取到dom节点并给dom节点设置MutationObserver

### What is actually happening?

打印结果为null

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | window |
| Browser | Chrome |

**Comment by Sharang-heng** [comment]
https://codesandbox.io/s/antd-reproduction-template-y9vgcf?file=/index.js

**Comment by linxianxi** [comment]
可使用 setTimeout 延迟获取或使用 `afterOpenChange `
```
setTimeout(() => {  
    // 获取   
}}

afterOpenChange={(open) => {
   if(open) {
       // 获取
   }
}}
```

**Comment by afc163** [comment]
<img width="1089" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/5235fc3b-75b3-4a04-bf53-398de41d8e17">

没看到相关代码。
