### ISSUE TITLE
TreeSelect - not able to scroll horizontally with laptop touch pad

### ISSUE THREAD

**Issue by rujal408** [ant-design/ant-design#43198]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-d389wc?file=/index.js)

### Steps to reproduce

- Open the dropdown
- Open Folder
- Items with longer text length provides horizontal scrollbar
- But only mouse pointer can move scrollbar not with laptop mouse touch pad

### What is expected?

-  It is expected to be able to move with laptop touch pad horizontally

### What is actually happening?

- Horizontal scrollbar is not scrolling with scrolled with touch pad horizontally

| Environment | Info |
| --- | --- |
| antd | 4.20.4|
| React | 18 |
| System | MS Window |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Your reproduction seems has error.

**Comment by rujal408** [comment]
> Your reproduction seems has error.

![ss](https://github.com/ant-design/ant-design/assets/23138426/57bd8376-ede2-4669-be49-7b577bef0f3c)
The given code will give the output like this. You can see the horizontal scrollbar. We can scroll using mouse pointer only.

**Comment by MadCcc** [comment]
TreeSelect use virtual scroll, and not support horizontal scroll now.
