### ISSUE TITLE
Table组件显示全国的区域树，共3000多条记录，前端渲染超过10秒

### ISSUE THREAD

**Issue by xwy55555** [ant-design/ant-design#4320]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: window10
- 浏览器及其版本: chrome 55.0.2883.75 m

#### 您做了什么？请提供尽可能详细的重现步骤。

Table组件显示全国的区域树，共3000多条记录，前端渲染超过10秒

#### 您期待的结果是: 

3000多的数据量，应该在1秒内完成。我们是前后台分离的系统，后台取数据大约200ms左右。

#### 实际上的结果是:

前端渲染超过10秒

**Comment by RaoHai** [comment]
ref #3789

**Comment by xwy55555** [comment]
没看明白，能解释一下吗？

**Comment by yesmeck** [comment]
@xwy55555 能给个 demo 吗？

**Comment by xwy55555** [comment]
@yesmeck , 这个就是demo，树数据源已写在页面中，但还是要等10秒左右才会显示：
http://www.maylandstudio.com:7004/area_tree/index.html#/?_k=y71cq9

相应的源码请参见：
http://code.maylandstudio.com/git/root/area_tree

谢谢！

**Comment by yesmeck** [comment]
@ @ 你们是什么场景，需要一次性展示 3000 条数据。。。

**Comment by xwy55555** [comment]
@yesmeck  只是想用一棵树来维护全国的区域数据。之前jquery时，用ztree，在5万个节点以下，是挺快的。所以我觉得3000个节点应该不算多吧。

**Comment by yesmeck** [comment]
@xwy55555 那你应该用 Tree 而不是 table。

**Comment by yesmeck** [comment]
其实你这个 demo 里第一次渲染挺快的，大部分时间花在加载 js 和 css 上。

<img width="876" alt="wx20161222-003314 2x" src="https://cloud.githubusercontent.com/assets/465125/21397306/3f07fbac-c7de-11e6-8fcf-b944fb9bfbe8.png">

不过 Table 确实不适合用来一次性展示这么多数据，交互的时候就会很卡。

**Comment by imperio-wxm** [comment]
@yesmeck  问一下，table的data里是否支持嵌套table？

```js
   data.push({
       cTable: `${<Table />}`,
   });
```

**Comment by yesmeck** [comment]
@imperio-wxm 使用问题建议到 SegmentFault 上提。

**Comment by xwy55555** [comment]
我后来的解决方案是，把模块分成两部份：省份和市县，这样单个树的数据量就下来了。如果table性能不能提升，那就改业务的设计思路。谢谢上位的各位。
