### ISSUE TITLE
tree-select 弹出框打开时，输入框移出屏幕时，弹出框位置会变化一点点

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#43204]
### Reproduction link

[https://ant.design/components/tree-select-cn#components-tree-select-demo-placement](https://ant.design/components/tree-select-cn#components-tree-select-demo-placement)

### Steps to reproduce

1、打开弹出框
2、屏幕往上或往下移动、使输入框消失在屏幕内
3、输入框刚刚好不显示的时候，弹出框会偏移一点

https://github.com/ant-design/ant-design/assets/5378891/00dcaa43-709a-4ec4-ae77-a63c630d5870

### What is expected?

不发生抖动

### What is actually happening?

抖动位置发生偏移

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | lastest |
| System | mac |
| Browser | chrome |

---
应该是 rc-trigger 的问题？

**Comment by afc163** [comment]
> https://ant.design/components/tree-select-cn#components-tree-select-demo-placement

动画弹出方向有问题。

**Comment by afc163** [comment]
>  3、输入框刚刚好不显示的时候，弹出框会偏移一点

录个屏看看？

**Comment by bbb169** [comment]
这个是因为这段代码导致的https://github.com/react-component/trigger/blob/0583fd79373547d4c31afe30091a3d45d4535e17/src/hooks/useAlign.ts#L397，
offsetY默认为4，https://github.com/react-component/select/blob/53bf82389500ff3448136b08f75e3bb9ace2d3d8/src/SelectTrigger.tsx#L15，
调试的时候也可以发现它抖动的距离就是4，但是这个组件嵌套太深了，改了不知道怎么调试进行测试，要一个个打包替换node_module吗 @afc163

**Comment by Yuiai01** [comment]
> 这个是因为这段代码导致的[https://github.com/react-component/trigger/blob/0583fd79373547d4c31afe30091a3d45d4535e17/src/hooks/useAlign.ts#L397，](https://github.com/react-component/trigger/blob/0583fd79373547d4c31afe30091a3d45d4535e17/src/hooks/useAlign.ts#L397%EF%BC%8C) offsetY默认为4，[https://github.com/react-component/select/blob/53bf82389500ff3448136b08f75e3bb9ace2d3d8/src/SelectTrigger.tsx#L15，](https://github.com/react-component/select/blob/53bf82389500ff3448136b08f75e3bb9ace2d3d8/src/SelectTrigger.tsx#L15%EF%BC%8C) 调试的时候也可以发现它抖动的距离就是4，但是这个组件嵌套太深了，改了不知道怎么调试进行测试，要一个个打包替换node_module吗 @afc163

可以尝试使用 yarn link ~

**Comment by bbb169** [comment]
修复pr已提react-component，求CR
