### ISSUE TITLE
Multiple dropdown menus (with trigger=context) remain open

### ISSUE THREAD

**Issue by manivsh** [ant-design/ant-design#43202]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9636ml?file=/index.js)

### Steps to reproduce

when using dropdown as right-click menu for multiple elements. 
with un-controlled open status, the open status is contextual only for the single element, resulting in multiple drop-down menus open at once.

the trigger must be "contextMenu".

### What is expected?

On open of a different dropdown, all other menus should autoclose.

### What is actually happening?

multiple dropdowns remain open.

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.x |
| System | windows 10 |
| Browser | latest chrome/edge |

---
In antd@4.x.x the behavior was as expected.

**Comment by MadCcc** [comment]
Seems to be related with trigger update. Dropdown with legacy `rc-trigger` acts good: https://codesandbox.io/s/antd-reproduction-template-forked-xvwf94

**Comment by linxianxi** [comment]
这两个有点像 https://github.com/ant-design/ant-design/issues/43093
