### ISSUE TITLE
ConfigProvider > from > validateMessages not working

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#43210]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-jepsen-g6lgf2)

### Steps to reproduce

Step 1. Use ConfigProvider at _app

Step 2. Use Forms with validation on pages

### What is expected?

The error messages in the form must be the same as the ConfigProvider

### What is actually happening?

Error messages in form are not the same as ConfigProvider

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.2.0 |
| System | Macbook Air M1 2020 - macOS 13.3.1 |
| Browser | Chrome 112.0.5615.137 |

**Comment by Yuiai01** [comment]
The current version appears to be fine. https://codesandbox.io/s/ji-ben-shi-yong-antd-5-6-3-forked-k6fqld

**Comment by archisketch-thangly** [comment]
@Yuiai01 Ahh, it doesn't seem to work when the Form is in Modal

**Comment by archisketch-thangly** [comment]
> @Yuiai01 Ahh, it doesn't seem to work when the Form is in Modal

My code is like this, it seems to work fine with Form when not in Modal

<img width="712" alt="image" src="https://github.com/ant-design/ant-design/assets/105255382/de2f5e4f-3667-4dd0-ab45-8c734ae94bec">

**Comment by zombieJ** [comment]
@archisketch-thangly Pls refresh your reproduce for the code

**Comment by archisketch-thangly** [comment]
@zombieJ I think the problem occurs if there are multiple nested ConfigProviders

reproduce: https://codesandbox.io/s/configprovider-form-h3759n

**Comment by Yuiai01** [comment]
> @zombieJ I think the problem occurs if there are multiple nested ConfigProviders
> 
> reproduce: https://codesandbox.io/s/configprovider-form-h3759n

ConfigProvider provides a configuration to all React components underneath itself via the context API. You only need to wrap it once around the application.

**Comment by Yuiai01** [comment]
> > ConfigProvider provides a configuration to all React components underneath itself via the context API. You only need to wrap it once around the application.
> 
> I understand you. But it's hard if the whole site has a colorPrimary and somewhere there is a component that uses a different colorPrimary. (colorPrimary is just one example I mean.)

In this case. You may be able to declare a ConfigProvider again internally where needed, so that the component will use the configuration from the recent ConfigProvider.

**Comment by Wxh16144** [comment]
Can you be more specific about your desired outcome? I tried without finding any ambiguity.

demo: https://codesandbox.io/s/configprovider-form-forked-vywydg?file=/src/App.js

**Comment by archisketch-thangly** [comment]
> Can you be more specific about your desired outcome? I tried without finding any ambiguity.
> 
> demo: https://codesandbox.io/s/configprovider-form-forked-vywydg?file=/src/App.js

Let me explain

When I use ConfigProvider with global scope at _app, config form is here.
Then I use the ConfigProvider somewhere else, the only purpose is to change the theme, that is, the config form is not overwritten.
At this point the global config form no longer works. But interestingly, the global theme still works fine.

**Comment by archisketch-thangly** [comment]
> > > ConfigProvider provides a configuration to all React components underneath itself via the context API. You only need to wrap it once around the application.
> > 
> > 
> > I understand you. But it's hard if the whole site has a colorPrimary and somewhere there is a component that uses a different colorPrimary. (colorPrimary is just one example I mean.)
> 
> In this case. You may be able to declare a ConfigProvider again internally where needed, so that the component will use the configuration from the recent ConfigProvider.

But how can the ConfigProvider form at _app not be lost :(((?

**Comment by Wxh16144** [comment]
It seems to be caused by the #42604 refactoring 🤔
