### ISSUE TITLE
Tree控件不能显示子节点、 date-picker不能使用resetFields()清空；请尽快修复，非常感谢！

### ISSUE THREAD

**Issue by xiaoheicoder** [ant-design/ant-design#4321]
#### 发生问题的环境是：
- antd 版本:2.4.3，更新至2.5.2也不行
- chrome浏览器及其版本: 54.0.2840.59 (64-bit)

1、Tree控件不能显示子节点 

#### 您期待的结果是:
显示多级树形数据

#### 实际上的结果是:
只显示根节点一级，其他不子节点不显示；

2、date-picker不能使用resetFields()清空

#### 您期待的结果是:
清空至未选择任何值状态

#### 实际上的结果是:
未发生任何变化，也未清空；

PS：我跟几个同事在项目中都试过，都有问题；拷贝官网代码也不行；

**Comment by RaoHai** [comment]
可否提供一个可复现的 demo 呢？

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
1. 给重现再 reopen。
2. https://github.com/ant-design/ant-design/issues/3746
