### ISSUE TITLE
@import (reference) '~antd/es/style/themes/index.less';

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#43214]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/dashboard/recent?workspace=616dc16e-da52-49a9-b94a-8138ad222dcb)

### Steps to reproduce

umi3 下 升级 antd4 到 5, 
 npx -p @ant-design/codemod-v5 antd5-codemod src
重新执行 yarn run dev

### What is expected?

没有这个不存在文件的报错

### What is actually happening?

报错了

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
Duplicate of #39344

检查构建插件是不是加了 `babel-plugin-import` 之类会改写 import 的插件。

**Comment by vaynevayne** [comment]
没有啊

**Comment by afc163** [comment]
@vaynevayne 给重现吧~

**Comment by vaynevayne** [comment]
在 umi3里, 从 antd 4.x 迁移antd 5.x 会出现的,  复现就算了,我暂时不升级了
依赖关系太复杂了 proComponent  import 了 antd.css 文件
umi 也可能有缓存什么的
 
现在看来可以得到一个经验就是二次封装antd的库, 永远不要 import antd.css 文件
再次证明 css in js 更好
