### ISSUE TITLE
在运行脚本pnpm -r exec tsc -b -v时，类型检查出现错误

### ISSUE THREAD

**Issue by super04240520** [ant-design/ant-design#43221]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-lq48mg?file=/replace.d.ts，)

### Steps to reproduce

1、项目中使用menu组件；2、项目升级；3、项目配置tsconfig.json后运行 pnpm -r exec tsc -b -v

### What is expected?

能通过ts检查

### What is actually happening?

memu中的两个type声明无法通过ts类型检查
node_modles文件路径: 
antd/es/menu/index.d.ts
antd/es/menu/MenuItem.d.ts

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 17.02 |
| System | mac |
| Browser | chorme |

---
在sing-spa中，使用leran和pnpm管理的项目，需要升级其中的一个子项目。目前无法通过azure的tslint。 希望能更改这两种type类型，或者提供一种可以先覆盖/跳过这两种type的方式，来满足当前的开发需求

**Comment by MadCcc** [comment]
reproduction 跑不起来

**Comment by BoyYangzai** [comment]
@super04240520 
试试 
```ts
{
  "compilerOptions": {
  },
  "exclude": [
    "node_modules/antd/**/*"
  ]
}
```
