### ISSUE TITLE
Form.useWatch 失效

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#43222]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/dashboard/recent?workspace=616dc16e-da52-49a9-b94a-8138ad222dcb)

### Steps to reproduce

```jsx
  <QueryFilter
 initialValues={{
            channel: [],
            channel__mode: '121',
          }}>
 <ChannelSelect label="渠道" name="channel" />
</QueryFilter>



const ChannelSelect: FC<ProFormSelectProps> = ({ name, fieldProps, placeholder, ...other }) => {
  const { initialState } = useModel('@@initialState')
  const form = Form.useFormInstance()
  const radio = Form.useWatch('channel__mode', form)

  console.log('radio', radio) // 这里总是 undefined

  const onRadioChange = (val: string) => {
    console.log('onRadioChange', val)

    form.setFieldsValue({
      channel__mode: val,
    })
  }

  return  null
}
```

antd 版本 4.22

### What is expected?

useWatch radio 等 121

### What is actually happening?

radio 为undefined

| Environment | Info |
| --- | --- |
| antd | undefined |
| React |  18 |
| System | maco |
| Browser | chorme |

**Comment by zombieJ** [comment]
`useWatch` 只会监听注册的字段。如果不和 Form.Item 联动，你其实不需要使用 Form 的方法，自己管理就好了哈~

**Comment by vaynevayne** [comment]
就要使用 initialValues 来存储值, 有什么办法可以让它工作? @zombieJ

**Comment by afc163** [comment]
可以直接用 useState 就好。

**Comment by vaynevayne** [comment]
需要 form 的 context 能力以及 formRef 整体取值 ,
使用useState 会导致每个页面都要加一下, 代码会很乱
搞了个 <input hide> 先用着,在 proForm 里, 不知道计算折叠展开的数量时会不会计算进去

**Comment by afc163** [comment]
`<Form.Item name="channel__mode" hidden />` 就行。
