### ISSUE TITLE
Tooltips are automatically shown for collapsed sidebar menu items

### ISSUE THREAD

**Issue by ytambi** [ant-design/ant-design#43228]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-germain-j46nn8)

### Steps to reproduce

- Hover on all the menu items from the menu in sidebar.
- Now collapse the sidebar so that icons from Menu Items are visible.
- Note that the tooltips are still visible on top corner.

### What is expected?

Tooltips should be hidden until the collapsed Sider menu icons are hovered upon.

### What is actually happening?

Tooltips are visible as soon as Sider inline-mode menu is collapsed. They hide when we expand again.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | MacOS Ventura 13.4 |
| Browser | Brave Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (x86_64) |

---
I'm getting frustrated with this issue in my next app. Weird enough, this issue seems to be fixed in antd version `5.3.2`. However, in my case even bumping up the antd version doesn't fix this.

Can we control the tooltips in this specific scenario (Sider > Menu - inline mode). Is there a prop that I'm missing ? This is how my component looks like (more or less) - 

```
import { Layout, Menu } from "antd";
import {
  ClusterOutlined,
  FieldTimeOutlined,
  FileDoneOutlined,
  FileProtectOutlined,
  SettingOutlined,
  SolutionOutlined,
  TeamOutlined,
  UserOutlined
} from "@ant-design/icons";
import { useState } from "react";

const IconStyle = {
  fontSize: "22px"
};

const TextStyle = {
  fontSize: "16px"
};

const ContentStyle = {
  background: "#fff",
  padding: "10px",
  margin: 0,
  height: "100%"
};

const items = [
  {
    key: "users-management",
    label: <span style={TextStyle}>Manage Users</span>,
    icon: <UserOutlined style={IconStyle} />
  },
  {
    key: "teams-management",
    label: <span style={TextStyle}>Manage Teams</span>,
    icon: <TeamOutlined style={IconStyle} />
  },
  {
    key: "roles-management",
    label: <span style={TextStyle}>Manage Roles</span>,
    icon: <SolutionOutlined style={IconStyle} />
  },
  {
    key: "subscription-templates",
    label: <span style={TextStyle}>Subscription Templates</span>,
    icon: <FileDoneOutlined style={IconStyle} />
  },
  {
    key: "child-organizations",
    label: <span style={TextStyle}>Child Organizations</span>,
    icon: <ClusterOutlined style={IconStyle} />
  },
  {
    key: "audit-logs",
    label: <span style={TextStyle}>Audit Logs</span>,
    icon: <FileProtectOutlined style={IconStyle} />
  },
  {
    key: "scheduled-jobs",
    label: <span style={TextStyle}>Scheduled Jobs</span>,
    icon: <FieldTimeOutlined style={IconStyle} />
  },
  {
    key: "organization-settings",
    label: <span style={TextStyle}>Settings</span>,
    icon: <SettingOutlined style={IconStyle} />
  }
];

export default function App() {
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  return (
    <div style={{ minHeight: "100vh", backgroundColor: "white" }}>
      <Layout style={{ minHeight: "100vh" }}>
        <Layout.Header style={{ width: "100%" }} />
        <Layout style={{ minHeight: "100vh" }}>
          <Layout.Sider
            width={220}
            collapsible
            collapsed={isSidebarCollapsed}
            collapsedWidth={60}
            onCollapse={() => {
              setIsSidebarCollapsed(!isSidebarCollapsed);
            }}
          >
            <Menu
              mode="inline"
              items={items}
              style={{
                height: "100%",
                backgroundColor: "#fff",
                border: "1px solid #ccc"
              }}
             // Selects particular menu item
              onClick={() => {}}
              selectedKeys={["users-management"]}
            />
          </Layout.Sider>
          <Layout.Content style={ContentStyle}>
            <h1>This is test H1</h1>
          </Layout.Content>
        </Layout>
      </Layout>
    </div>
  );
}
```

Anyone has any idea regarding fixing this ?

**Comment by ytambi** [comment]
Behaviour - 

https://github.com/ant-design/ant-design/assets/102503628/0ba90002-cdd7-439d-96a6-5b8ab3325280


![Antd_issue_snap](https://github.com/ant-design/ant-design/assets/102503628/74bf2271-1845-4740-9895-6bf0ae67bcce)

**Comment by Yuiai01** [comment]
You can try specifying antd as the latest version `5.6.3` and then use `yarn install-force` to force the update dependency, hopefully this will help you.

**Comment by MadCcc** [comment]
Cannot reproduce, please upgrade antd and try again.

**Comment by abhishekcxpoint** [comment]
How to handle the tooltip color then? Like now it is dark but if want to add background color to white and text something like blue?
