### ISSUE TITLE
 4.x 版本里 select suffixIcon 不生效

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#43224]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-antd-4-24-10-forked-nxvrkm?file=/demo.tsx)

### Steps to reproduce

看 demo

### What is expected?

看 demo

### What is actually happening?

看 demo

| Environment | Info |
| --- | --- |
| antd | 4.24.11 |
| React | 18 |
| System | macos |
| Browser | chrome |

<img width="1172" alt="image" src="https://github.com/ant-design/ant-design/assets/124666577/16ab0dc2-128d-4c71-af97-294b1145d4bd">

**Comment by zombieJ** [comment]
`showArrow`: https://codesandbox.io/s/duo-xuan-antd-4-24-10-forked-94254x

![Uploading 截屏2023-06-27 15.44.23.png…]()

**Comment by vaynevayne** [comment]
1. 能不能正面回答问题, 这是 4.x 的代码 bug还是4.x的文档 bub ?
2. 能不能等 提问个和回答者达成共识再关闭? 
你怎么知道我要的是显示 icon, 而不是需要这个rightSlot 插槽

**Comment by yoyo837** [comment]
> 1. 能不能正面回答问题, 这是 4.x 的代码 bug还是4.x的文档 bug ?
> 2. 能不能等 提问个和回答者达成共识再关闭?
>    你怎么知道我要的是显示 icon, 而不是需要这个rightSlot 插槽
>    @zombieJ

兄die, 如果是这样, 你issue描述就应该包含想要说的内容, 其他人并不知道你还会不会有所补充, 只能基于目前看到的来处理.

**Comment by vaynevayne** [comment]
不管了, 提个 bug 也只是希望 antd 更好, 既然你们刻意回避, 我瞎操什么心
就事论事, 4.x 版本有没有右边的插槽?

**Comment by afc163** [comment]
看上去可以和 5.x 逻辑保持一致：https://codesandbox.io/s/duo-xuan-antd-4-24-10-forked-73gzhp?file=/demo.tsx

**Comment by afc163** [comment]
>  就事论事, 4.x 版本有没有右边的插槽?

你可以打开 zombieJ 提供的 codesandbox 看一下，在 4.x/5.x 里开启了 showArrow 时 suffixIcon 才能生效。加上 showArrow 后应该能解决你目前的 UI 问题。这是个隐藏逻辑。

不过感觉 4.x 和 5.x 都可以改成指定 suffixIcon 时就展示出来。

**Comment by afc163** [comment]
因为 5.x 里多选 showArrow 默认为 `true`。而 4.x 里单项时 showArrow 默认为 `true`，多选时默认为 `false`。正如 zombieJ 的截图所示。

4.x 这么做是因为 antd 在 5.x 之前的设计规范默认不展示多选的箭头。

**Comment by vaynevayne** [comment]
4.x 和 5.x 的差异并不重要, 你们也没必要花费精力去强行统一, 
但是对应版本的文档得跟代码一致, 为免其他人遇到同样的问题, 建议4.x 的文档可以改一下,  当然如果你们不 care也没事,反正我踩了坑我自己知道就行了

<img width="1000" alt="image" src="https://github.com/ant-design/ant-design/assets/124666577/65f71b89-5818-4c91-82f6-b9f29f00675b">

**Comment by afc163** [comment]
欢迎来个 PR~

**Comment by MadCcc** [comment]
感觉 `showArrow` 这个 api 可以废弃了，只用 `suffixIcon` 就行了。`suffixIcon={null}` 或者 `suffixIcon={false}` 时隐藏 arrow

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/pull/956
