### ISSUE TITLE
Input监听onInput后clear按钮点击无响应，allowClear失效

### ISSUE THREAD

**Issue by h1orz** [ant-design/ant-design#43225]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-6-3-forked-tktkk3)

### Steps to reproduce

在输入框中输入任意值，点击右侧清除按钮。

### What is expected?

清除Input的值

### What is actually happening?

未清除

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18 |
| System | Window/Mac |
| Browser | 114 |

**Comment by afc163** [comment]
`onInput` => `onChange`

点击清除不会触发 input 行为。

**Comment by h1orz** [comment]
> `onInput` => `onChange`
> 
> 点击清除不会触发 input 行为。

业务场景是类似代码提示的交互，
1. 用户输入a，提示['a', 'aa']下拉项，然后触发失焦隐藏下拉项，

**Comment by h1orz** [comment]
改了下，onChange负责保存值，onInput负责下拉项处理，没冲突。🎉
