### ISSUE TITLE
Upload 进度条消失晚一会

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/ant-design#43229]
### Reproduction link

[https://ant.design/components/upload-cn](https://ant.design/components/upload-cn)

### Steps to reproduce

在官网上随便上传一个文件，就会发现，先提示，然后进度条还是绿色的100%没有消失

### What is expected?

100%就应该消失才对。还要等一会才消失

### What is actually happening?

先提示，然后进度条还是绿色的100%没有消失
<img width="1477" alt="image" src="https://github.com/ant-design/ant-design/assets/24643779/e2e9708d-546e-492a-b33d-e937cd8f81b0">

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | last |
| System | MacOS Big Sur 11.1 |
| Browser | Chrome90.0.4430.93（正式版本） (x86_64) |

**Comment by Yuiai01** [comment]
能整个录个屏啥的吗？我这边没办法成功上传文件，失败时进度条倒是很快消失了 😂

**Comment by MadCcc** [comment]
可能可以设计的，这个需要设计确认一下

**Comment by linxianxi** [comment]
> 能整个录个屏啥的吗？我这边没办法成功上传文件，失败时进度条倒是很快消失了 😂

+1，官网我没办法成功上传

**Comment by DerrickTel** [comment]
失败的时候是比较快，如果是成功的话。就会出现我上诉的情况。其实大家可以把上传链接换成自己可以上传的链接来试。现在主要是就是设计的问题。大佬已经打了tag，等待解答吧~

**Comment by afc163** [comment]
是 bug，预期效果参考 https://4x.ant.design/components/upload-cn

**Comment by DerrickTel** [comment]
老大，merge了什么时候会发布呀？

> 是 bug，预期效果参考 https://4x.ant.design/components/upload-cn ，5.x 里动画丢了。
