### ISSUE TITLE
控制 tooltip 显示的位置

### ISSUE THREAD

**Issue by Yang-yibu** [ant-design/ant-design#43236]
### What problem does this feature solve?

给树节点添加 tooltip 显示树节点信息，树在容器中横向滚动。需要控制 tooltip 始终显示在容器右侧，如 绿色框位置显示
![1687915790123_70513D75-D32E-4554-A684-FFD06AEC1B7A](https://github.com/ant-design/ant-design/assets/23130670/9836fbdd-5056-499b-8e72-9196473df376)

### What does the proposed API look like?

align.pos = [left: number, top: number]添加 left 或 top 的属性，支持用户自己设置位置

**Comment by Wxh16144** [comment]
感觉需求很奇怪, 或许你可以在触发器上面做手脚?

**Comment by zombieJ** [comment]
既然不要对齐了，直接封一个任意位置 Tooltip 即可：
https://codesandbox.io/s/ji-ben-antd-5-6-2-forked-pcsccs?file=/demo.tsx

**Comment by Yang-yibu** [comment]
> 感觉需求很奇怪, 或许你可以在触发器上面做手脚?

我把触发器设置为树组件的容器，左右的位置是正确的，上下分位置不能与树节点对齐

**Comment by Yang-yibu** [comment]
> 既然不要对齐了，直接封一个任意位置 Tooltip 即可： https://codesandbox.io/s/ji-ben-antd-5-6-2-forked-pcsccs?file=/demo.tsx

需要左边与树组件的容器右边对齐，上下与触发的树节点对齐

**Comment by Yang-yibu** [comment]
现在犹豫树节点太长，出现了滚动条，导致 tooltip 显示的位置有点奇怪
