### ISSUE TITLE
表单validateFields方法触发onFieldsChange方法

### ISSUE THREAD

**Issue by lucky3mvp** [ant-design/ant-design#4323]
对表单设置了onFieldsChange方法以便在表单项改变时做一些监控，
然后在提交表单时调用validateFields对表单项进行验证，发现此时也调用了onFieldsChange方法

请问如何做到在validateFields时不调用onFieldsChange方法，只是用户在页面上操作改变表单项时才触发onFieldsChange方法呢？

或者在onFieldsChange方法内怎么能区分是什么引起的该方法的调用？

**Comment by RaoHai** [comment]
validateFields 时触发的  `onFieldsChange(props, field)`，`props` 和 `field` 应该都是空的吧。。

**Comment by lucky3mvp** [comment]
@RaoHai 
不是的，
props 一直都能取到，
field 分情况，因为我在 formItem 设置了校验规则，所以 field 是那些我设置了规则，但是还没有校验过的表单项，
比如：
表单项 A,  B 都设置了校验规则，现在没有值改变触发onFieldsChange这种情况，那么第一次 submit  validateFields  触发 onFieldsChange 时，field 是 A，B，而此后再 validateFields  时，fields 才是空的；
或者：
表单项 A,  B 都设置了校验规则，先手动改变 A 的值，再 submit 触发 validateFields 和 onFieldsChange，这时的 field 是 B

希望我表述清楚了。。。有点晕。。。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2934

**Comment by lucky3mvp** [comment]
@afc163 
谢谢，看了下#2934，感觉不太一样，
我在这里使用时，并没用到redux，就是给表单提供了 onFieldsChange，以及提交表单时 validateFields，

onFieldsChange 确实触发两次， 我自己理解的 onFieldsChange 触发两次就是一次在校验中（dirty 为 true, validating 为 true, error 为 undefined），一次校验完（dirty 为 false, validating 为 false, error 为 校验结果），没去纠结内部的实现机制为什么会触发两次，我也没遇到过三次的情况。。。

我是想区分 validateFields 触发 onFieldsChange 的情况，和表单项值改变时触发 onFieldsChange 的情况

**Comment by afc163** [comment]
因为 validateFields 时，表单项状态变了（值没变）。

**Comment by benjycui** [comment]
或者可以考虑增加个 `onValuesChange` 回调？ cc @yiminghe 

这块咨询量不小，大多数人搞不清 field 和 value 的区别。

**Comment by tingxinCY** [comment]
遇到同样问题，最终改成onValuesChange解决的

**Comment by SC30SC** [comment]
onValuesChange 校验的时候，变化的values 还没有被setField  ................

**Comment by damiangreen** [comment]
For any english speakers, this is how you validate before persisting.

    Form.create({
    mapPropsToFields: (props: RenameDashboardFormProps) => ({
      title: Form.createFormField({
        value: props.currentDashboard.title,
      }),
    }),
    onFieldsChange: (props: any, changedFields: any) => {
      if (!changedFields.title.validating && !changedFields.title.errors) {
        props.renameDashboard({
          dashboardId: props.currentDashboard.id,
          name: changedFields.title.value,
        })
      }
    },  }),

**Comment by deepexpert-chenkai** [comment]
遇到同样的问题，本来是打算使用onValuesChange来代替的，但是onValueChange又不带验证信息，只有value值，没法满足我的需求，最后只能放弃validateFields方法，所有验证自己来做，表单的报错用formitem里validateStatus实现了

**Comment by afc163** [comment]
onFieldsChange 里带有验证信息。
