### ISSUE TITLE
nextjs引入antd/es/button报错Cannot use import statement outside a module

### ISSUE THREAD

**Issue by homestylew** [ant-design/ant-design#43233]
### Reproduction link

[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce

nextjs项目中：
```
import Button from "antd/es/button"
function App() {
  return (<div>
    <Button>TEST</Button>
  </div>)
}
export default App
```
报错：Cannot use import statement outside a module

### What is expected?

不报错

### What is actually happening?

报错：Cannot use import statement outside a module

| Environment | Info |
| --- | --- |
| antd | 5.6.0 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome  114.0.5735.134 |

**Comment by homestylew** [comment]
还有个问题就是，nextjs引入antd以后，antd组件的样式会先显示默认的样式，然后再显示antd的样式，页面有一个跳跃的过程，体验非常差。
请问怎么能解决这个问题？

**Comment by arvinxx** [comment]
> 还有个问题就是，nextjs引入antd以后，antd组件的样式会先显示默认的样式，然后再显示antd的样式，页面有一个跳跃的过程，体验非常差。

原因是样式没插入。解决方案参考官网的样式抽取 https://ant-design.antgroup.com/docs/react/customize-theme-cn#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%B8%B2%E6%9F%93 ，或者用 [antd-style](https://ant-design.github.io/antd-style/guide/ssr#%E5%9C%A8-nextjs-%E4%B8%AD%E9%9B%86%E6%88%90) 一站式解决

**Comment by MadCcc** [comment]
> 不引入 es 就好了呀，import { Button } from 'antd'

+1

**Comment by abstain23** [comment]
> > 还有个问题就是，nextjs引入antd以后，antd组件的样式会先显示默认的样式，然后再显示antd的样式，页面有一个跳跃的过程，体验非常差。
> 
> 原因是样式没插入。解决方案参考官网的样式抽取 https://ant-design.antgroup.com/docs/react/customize-theme-cn#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%B8%B2%E6%9F%93 ，或者用 [antd-style](https://ant-design.github.io/antd-style/guide/ssr#%E5%9C%A8-nextjs-%E4%B8%AD%E9%9B%86%E6%88%90) 一站式解决

按照这个文档上的来的，把所有的css整体导出，还是没有解决闪烁问题，next13.4 antd 5.6.0

**Comment by hengkx** [comment]
奇怪  我没 我没es引入也报错 
```
Module not found: Can't resolve 'antd/es/ConfigProvider'
```
移除ConfigProvider后 报相同的错误

**Comment by yoyo837** [comment]
> 奇怪 我没 我没es引入也报错
> 
> ```
> Module not found: Can't resolve 'antd/es/ConfigProvider'
> ```
> 
> 移除ConfigProvider后 报相同的错误

https://github.com/vercel/next.js/pull/52148

**Comment by afc163** [comment]
@hengkx 没在钉钉群里？

**Comment by hengkx** [comment]
在 这个先发的

**Comment by morganney** [comment]
You publish an ES variant in the `es` folder, however you never properly define this package is `"type": "module"` so ES consumers will get the `SyntaxError: Cannot use import statement outside a module` when using your package. I do not think defining the `module` field in your package.json is sufficient. If you want to support ES and CJS distributions, you should provide a `"type": "module"` field in an `es/package.json` file that overrides the root one.
