### ISSUE TITLE
[Bug]When collapesedWidth is 0 of Layout.Sider and when it is collapsed, there is an unexpected tooltip

### ISSUE THREAD

**Issue by sherry007** [ant-design/ant-design#43237]
### Reproduction link

[https://ant.design/components/layout-cn#layoutsider](https://ant.design/components/layout-cn#layoutsider)

### Steps to reproduce
this is the config of my Sider component
```
<Layout.Sider
    className={classnames(styles.sider,'h-[calc(100%-64px)] overflow-y-hidden fixed!')}
    trigger={null}
    collapsed={siderCollapsed}
    collapsible
    collapsedWidth={0}
    width={240}
  >
```

### What is expected?

No tooltips

### What is actually happening?
There is an unexpected tooltip on the unexpected position
before
![image](https://github.com/ant-design/ant-design/assets/5960194/e25c6b11-a707-4b3a-9aec-66211ed062f2)
when collapsed
![image](https://github.com/ant-design/ant-design/assets/5960194/fcd91fad-c88b-4acc-a0f4-10cceb2de677)

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | v18.1.0 |
| System | Mac os |
| Browser | Chrome |

**Comment by sherry007** [comment]
我看到其他解决方案诸如
```less
.ant-menu-inline-collapsed-tooltip {
  display: none;
}
```
但是这种变动是全局的，也就是所有 inline Menu 的 tooltip 都被隐藏，但是如果没有设置 collapsedWidth 为0 以及 trigger 不设置为 null 的配置还是希望有 tooltip 提示的

**Comment by linxianxi** [comment]
请提供 codesanbox 复现链接

**Comment by sherry007** [comment]
确实有点难复现，头大
