### ISSUE TITLE
[Antd5.5.1] Datepicker format属性对YYYY-WW支持失效并报错

### ISSUE THREAD

**Issue by Tim0515** [ant-design/ant-design#43246]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lively-snow-h9jf99?file=/src/index.js)

### Steps to reproduce

format包含“WW”，选择就报错

### What is expected?

像antd4一样正常运行

### What is actually happening?

报错t.isoWeek is not a function

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | macOS |
| Browser | Chrome 114 |

**Comment by Wxh16144** [comment]
`WW` 在 dayjs 默认的 format 中不存在, ref: https://day.js.org/docs/en/plugin/advanced-format

**Comment by zombieJ** [comment]
@iamkun pls take a look

**Comment by Wxh16144** [comment]
貌似需要 import 这 2 个插件, 临时解决方案: https://codesandbox.io/s/solitary-moon-9jftkz?file=/src/index.js:231-385
```tsx
// ...
import advancedFormat from "dayjs/plugin/advancedFormat";
import isoWeek from "dayjs/plugin/isoWeek";
dayjs.extend(isoWeek);
dayjs.extend(advancedFormat);

```

**Comment by zombieJ** [comment]
> 貌似需要 import 这 2 个插件, 临时解决方案: https://codesandbox.io/s/solitary-moon-9jftkz?file=/src/index.js:231-385

也不算临时了，dayjs 设计就是通过插件来减少体积。如果有对应插件，你这个就是正解了。

**Comment by Tim0515** [comment]
thanks

**Comment by xdd-lisa** [comment]
请问加上advancedFormat和isoWeek plugin就好了吗，我这边antd 5.4.2 , 引入这两个plugin后还是报错

**Comment by Wxh16144** [comment]
> 请问加上advancedFormat和isoWeek plugin就好了吗，我这边antd 5.4.2 , 引入这两个plugin后还是报错

来个复现 codeSandbox

**Comment by xdd-lisa** [comment]
> > 请问加上advancedFormat和isoWeek plugin就好了吗，我这边antd 5.4.2 , 引入这两个plugin后还是报错
> 
> 来个复现 codeSandbox

https://codesandbox.io/s/brave-rain-l5xyj5?file=/src/index.js:0-1089

**Comment by Wxh16144** [comment]
> `WW` 在 dayjs 默认的 format 中不存在, ref: https://day.js.org/docs/en/plugin/advanced-format

问题出在 `dayjs(val, "YYYY-WW")` dayjs 居然不支持字符串反向 format， 需要大佬 @iamkun 协助看看

**Comment by Wxh16144** [comment]
@xdd-lisa  可以先使用非受控解决， 然后再看看有没有方法将 字符串计算成正确的格式

**Comment by iamkun** [comment]
看起来是 custom-parse-format  plugin 需要补齐反向 parse isoWeek 的 ww 的能力

**Comment by xdd-lisa** [comment]
> custom-parse-format plug



> 看起来是 custom-parse-format plugin 需要补齐反向 parse isoWeek 的 ww 的能力

季度quarter 也是一样的问题，需要补齐反向 'YYYY-[Q]Q' 解析的能力
