### ISSUE TITLE
是否考虑支持针对单个组件配置样式token

### ISSUE THREAD

**Issue by Sheepeer** [ant-design/ant-design#43244]
### What problem does this feature solve?

在很多情况下，暗黑主题中的弹窗（包括popover、dropdown、modal等）会被设计成白底黑字，现在似乎只能全局配置样式token，如果可能配置单个组件的token，那将很大程度上方便使用。

### What does the proposed API look like?

```
<Modal theme={{
    algorithm: theme.defaultAlgorithm,
    token:  {...}
}} {...otherProps} />
 ```

**Comment by Wxh16144** [comment]
可以用 `<ConfigProvider /> ` 组件单独包裹一层, docs: https://ant.design/docs/react/customize-theme-cn#%E5%B1%80%E9%83%A8%E4%B8%BB%E9%A2%98

```tsx
//...
<ConfigProvider
    theme={{
      components: {
        Modal: {
          colorPrimary: 'red'
        },
      },
    }}
  >
  <Modal />
</ConfigProvider>
//...
```

**Comment by Sheepeer** [comment]
> 可以用 `<ConfigProvider /> ` 组件单独包裹一层, docs: https://ant.design/docs/react/customize-theme-cn#%E5%B1%80%E9%83%A8%E4%B8%BB%E9%A2%98
> 
> ```tsx
> //...
> <ConfigProvider
>     theme={{
>       components: {
>         Modal: {
>           colorPrimary: 'red'
>         },
>       },
>     }}
>   >
>   <Modal />
> </ConfigProvider>
> //...
> ```

好快的回复！感谢~

**Comment by Sheepeer** [comment]
另外，还有个问题，既然容器浮层的背景色可以单独配置，那容器浮层对应的文字颜色是否也应该可以支持单独配置呢？
![image](https://github.com/ant-design/ant-design/assets/78125933/2603c9c0-9e8e-4652-9eb3-0a308988228f)

**Comment by afc163** [comment]
colorText 试试

**Comment by Wxh16144** [comment]
除了 antd 提供的 token 以外, 在 [5.6.0+](https://github.com/ant-design/ant-design/releases/tag/5.6.0) 版本中支持组件级的 token 定义

**Comment by Sheepeer** [comment]
colorText是全局的，我想使用的场景是dark全局+light浮层；目前浮层的背景色可以用colorBgElevated定义，那色彩是不是也应该有对应的colorTextElevated来定义？另外，我刚刚试了一下 @Wxh16144 上面所说的用<ConfigProvider/>包裹整个浮层组件，这样会连带着把触发图层的元素样式也修改了，而我需要修改的仅仅是浮层而已。这种场景我现在是用自定义了一套css覆盖掉antd的样式的方式来实现的，是否后续antd可以提供更好的方法？
![image](https://github.com/ant-design/ant-design/assets/78125933/f2b65045-4450-4874-8c1e-d0cb1aa8288e)


> colorText 试试

**Comment by MadCcc** [comment]
暂时没有 colorTextElevated。如果是纯浮层组件用 `colorText` 就足够了，Select 这种确实需要组件 Token 或者新的全局 Token 支持

**Comment by Wxh16144** [comment]
> 暂时没有 colorTextElevated。如果是纯浮层组件用 `colorText` 就足够了，Select 这种确实需要组件 Token 或者新的全局 Token 支持。cc @arvinxx

有一个讨论 https://github.com/ant-design/ant-design/discussions/42894 貌似是类似问题? 有点没理解

**Comment by Sheepeer** [comment]
> 

是的！和这个类似，以popover为例，希望可以通过配置token实现修改popover dropdown的样式，但不能影响popover trigger的样式

**Comment by arvinxx** [comment]
> 希望可以通过配置token实现修改popover dropdown的样式，但不能影响popover trigger的样式

@MadCcc 我理解这个应该组件层面要保证掉。比如我配置 Popover 的 colorText，那么只应该影响 Popover 的 colorText，不应该影响 Popover 子组件（比如一个 Button ）的 colorText。如果影响子组件就不对了，属于 bug。

> 暂时没有 colorTextElevated。如果是纯浮层组件用 colorText 就足够了，Select 这种确实需要组件 Token 或者新的全局 Token 支持。

再考虑 Select 的场景，Select这种要区分配置选择框和浮层的，建议加组件 token，不建议全局 token。

另外就是如果有了 CP上的组件 classNames ，应该也可以解决这个问题。

**Comment by Sheepeer** [comment]
popover组件没有回填效果，我试了下datepicker，回填会被影响：
![image](https://github.com/ant-design/ant-design/assets/78125933/48bbdfe4-74f5-4e27-a217-9fec4847aac9)
![image](https://github.com/ant-design/ant-design/assets/78125933/55b280ea-6d80-4ff2-a422-125257e01654)

**Comment by arvinxx** [comment]
> popover组件没有回填效果，我试了下datepicker，回填会被影响：
> ![image](https://user-images.githubusercontent.com/78125933/249435452-48bbdfe4-74f5-4e27-a217-9fec4847aac9.png)
> ![image](https://user-images.githubusercontent.com/78125933/249435502-55b280ea-6d80-4ff2-a422-125257e01654.png)

嗯 这种需要加组件token来解决

**Comment by MadCcc** [comment]
Popover 组件本身就不包含 trigger，你想改的应该是 Button 组件

**Comment by dbssAlan** [comment]
> 暂时没有 colorTextElevated。如果是纯浮层组件用 `colorText` 就足够了，Select 这种确实需要组件 Token 或者新的全局 Token 支持。cc @arvinxx

请问，是否可以增加单独控制Select箭头颜色的组件token? 部分暗色系UI设计下，这个箭头颜色需要单独修改的

**Comment by arvinxx** [comment]
> 请问，是否可以增加单独控制Select箭头颜色的组件token? 部分暗色系UI设计下，这个箭头颜色需要单独修改的


给个示例

**Comment by dbssAlan** [comment]
> > 请问，是否可以增加单独控制Select箭头颜色的组件token? 部分暗色系UI设计下，这个箭头颜色需要单独修改的
> 
> 给个示例

https://codesandbox.io/s/dry-architecture-8g26j5?file=/src/theme.js

两个问题：
1.  是否取消使用bordered这个属性时，将会影响Select的背景色。目前不想要边框，背景色无法单独设置
2.  采用深色系背景时，Select中的小箭头颜色将与背景色接近，无法单独设置颜色

另外，想问下，Select 下列菜单中如果想采用选项的小箭头如何能方便的设置？感到`dropdownRender`并不能很好的满足的样子，或者我的用法不对?
![image](https://github.com/ant-design/ant-design/assets/44510207/4209cc56-bb1c-4864-b457-c522d32bd986)

**Comment by arvinxx** [comment]
> 是否取消使用bordered这个属性时，将会影响Select的背景色。目前不想要边框，背景色无法单独设置

这我也觉得挺难受的 @zombieJ  理论上bordered =false 不应该改背景色。改背景色应该要用 ghost =true 这样比较好

**Comment by afc163** [comment]
bordered={false} 是一种 borderless 样式风格，不是简单的去边框。

**Comment by dbssAlan** [comment]
> bordered={false} 是一种 borderless 样式风格，不是简单的去边框。

基础组件库应该高度自定义话吧？然后上层再按照需要自行组合和封装。话说，是否可以出自定义desigen token的功能呢？感到目前的design token覆盖不够全面，很多还是需要写css去调整。例如一个input的长宽，因为加了·arrowClear·，长宽这样基础的要求就变得不一样了：
https://codesandbox.io/s/dry-architecture-8g26j5?file=/src/styles.css

**Comment by arvinxx** [comment]
> 基础组件库应该高度自定义话吧？然后上层再按照需要自行组合和封装。话说，是否可以出自定义desigen token的功能呢？感到目前的design token覆盖不够全面，很多还是需要写css去调整。例如一个input的长宽，因为加了·arrowClear·，长宽这样基础的要求就变得不一样了： https://codesandbox.io/s/dry-architecture-8g26j5?file=/src/styles.css

自定义 Token 参考：https://ant-design.github.io/antd-style/guide/custom-theme#%E8%87%AA%E5%AE%9A%E4%B9%89-token

**Comment by zombieJ** [comment]
从 `5.8.0` 起，组件 token 也支持算法配置。这个 issue 先关啦~
关于组合的讨论欢迎另起 issue 讨论。
