### ISSUE TITLE
icon ts 报错 说需要 rev 这个类型

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#43247]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-6-3-forked-m8gz4g?file=/demo.tsx)

### Steps to reproduce

直接点链接进去就可以看到ts报错
![image](https://github.com/ant-design/ant-design/assets/67216143/a72232cf-b4c3-4ea3-b407-afd5d0fed1a8)

### What is expected?

ts不报错

### What is actually happening?

ts报错

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 17.0.1 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by MadCcc** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-6-3-forked-w59wyg?file=/demo.tsx
应该和 react 和 @types/react 版本不一致有关，改成 `^` 就没问题了
