### ISSUE TITLE
Allow Table.Column class type to be possible to extend as a generic type in TypeScript

### ISSUE THREAD

**Issue by piotrwitek** [ant-design/ant-design#4324]
# Rationale
In Table class there is a Column Class Type declared as static member, making it not possible to be consumed as generic type.
But Column Class is generic and should infer the type from Table (to be able to leverage type inference for records in render method)

For instance when I try to consume the library in TypeScript I want to extend Table as a generic type like for instance: `class UserTable extends Table<User> { };`, then I can benefit from record object to be typed.
I would like to do exactly the same for Column but it is not possible, because I'm forced to use static Column member type from Table Class, like this: `const { Column } = Table;`

Expected usage in TypeScript:
```tsx
import { User } from './models/user';
import { Table } from 'antd';

class UserTable extends Table<User> { };

const users: User[] = [{...},{...},...];

<UserTable dataSource={users} rowKey={el => el.user_id}> // "el" object should infer User type
  <UserTable.Column title="Name" key="user" render={(text, record) => {
    return <UserItem user={record} />; // "record" object here should also infer User type
  } } />
...
...
```

# Initial Proposal (*rejected*)
~~My proposal is to export Column Class as Component so I can import it like Table and extend using generics the same way as with Table: `class UserColumn extends Column<User> { };`, then I could leverage typing like this:~~

# Updated Proposal:
After consideration of library constrains, my new proposal is to make it possible to extend Column Class as a generic class in the same way as it is currently possible with Table Class, that would be consistent and elegant enough for consumers.

See usage example: 
```tsx
import { Table } from "antd"

// Define a  generic Table 
class MyTable extends Table<IPhoto>{}
// Define the generic Column.
class MyColumn extends Table.Column<IPhoto>{}
```
Also please check alternative example below:  https://github.com/ant-design/ant-design/issues/4324#issuecomment-268732142

# Optimal Solution
Optimal solution would be for the Column to get the generic type out of the extended generic MyTable class type, so the following would work as expected:
```tsx
<MyTable ... >
  <MyTable.Column ... /> // should have generic type inferred from MyTable automatically
</MyTable>
```

---

Please tell me if you are accepting PRs, maybe I can look into this in my free time.

References:
- Column declaration in Table:
https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L87
- Column Class:
https://github.com/ant-design/ant-design/blob/master/components/table/Column.tsx#L22

**Comment by bang88** [comment]
@piotrwitek Please see https://github.com/Microsoft/TypeScript/issues/6395

However, if you want use Generic `Table Column` you can do it like this:

```tsx

import { Table } from "antd"
const { Column } = Table;

// Define a  generic Table 
class MyTable extends Table<IPhoto>{}
// Define the generic Column.
class MyColumn extends Column<IPhoto>{}


// Usage
<MyTable dataSource={this.props.data} bordered loading={!this.props.data.length}>
                    <MyColumn
                        title="Thumb"
                        dataIndex="thumbnailUrl"
                        key="thumbnailUrl"
                        render={(thumb, row, index) => {   
                             // Now, row has type IPhoto.                         
                            return <img src={thumb} alt="" height={75}/>
                        } } />
</MyTable>
...
...
...


```

and export Column is unnecessary. You should use it with `Table` always.

**Comment by benjycui** [comment]
Actually, children of Table must be `Table.Column`..

**Comment by piotrwitek** [comment]
@bang88 have you tested the solution that you propose with success in a real project?
Because I have tried that already before and it didn't work, that's why I have issued this proposal

There seems to be a problem with extending Column, because extended class cease to work.
So example:
```
import { Table } from "antd"
const { Column } = Table;

// Define a  generic Table 
class MyTable extends Table<IPhoto>{}
// Define the generic Column.
class MyColumn extends Column<IPhoto>{}


// Usage
<MyTable dataSource={this.props.data} bordered loading={!this.props.data.length}>
    <MyColumn ... /> \\ <- this cease to work
    <Column ... /> \\ <- this working fine
</MyTable>
```
I'm trying to figure out if this is my project setup or is it a problem in your library.

Could you please provide some minimal working setup in some repo that I could check out if you actually tested it?

**Comment by benjycui** [comment]
> Actually, children of Table must be Table.Column..

You cannot use customized component as column now.

**Comment by piotrwitek** [comment]
@benjycui @bang88 @afc163  Thanks for trying to help, but could you please elaborate a little bit more with some alternatives/solutions to the problem, I'm trying to figure out a nice convention on how to use your library in a elegant typed manner.

If I'm not able to extend Column with generic type then I believe your library is not designed correctly from consumer perspective as it should be possible to do so, especially because you library is written in TypeScript.

Could you please tell me what is your solution to this problem, should I open another issue addressing this problem specifically?

**Comment by benjycui** [comment]
ping @yesmeck

**Comment by bang88** [comment]
I don't tested in a real project,Using generic components with typescript please track the links i posted.

**Comment by yesmeck** [comment]
@piotrwitek Do you know why generic type doesn't work on static prop, but works on exported class？ Any links to the typescript doc?

**Comment by piotrwitek** [comment]
@yesmeck The error from compiler state that: 
> Static members cannot reference class type parameters 

I found this explanation:
A class has two sides to its type: the static side and the instance side. Generic classes are only generic over their instance side rather than their static side, so when working with classes, static members can not use the class’s type parameter.

@bang88 I saw the link, but I believe this use scenario is not optimal, because if you can extend Table with generic type, and __cannot__ extend Column in the same way you are breaking consistency of your interface

**Comment by yesmeck** [comment]
@piotrwitek What typescript version are you using?

**Comment by piotrwitek** [comment]
@yesmeck typescript@2.1.4

```
tsconfig.json

{
  "compilerOptions": {
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "preserveConstEnums": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "noEmit": false,
    "noEmitOnError": true,
    "noEmitHelpers": false,
    "importHelpers": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "pretty": true,
    "declaration": false,
    "isolatedModules": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "noResolve": false,
    "outDir": "../out",
    "newLine": "LF",
    "removeComments": true,
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "lib": [
      "dom",
      "es2016",
      "es2017.object"
    ]
  },
  "include": [
    "**/*"
  ],
  "exclude": [
    "node_modules/**/",
    "jspm_packages/**/"
  ],
}
```

**Comment by piotrwitek** [comment]
@yesmeck 
I believe the possible solution is to update the Column Class to be possible to extend it as generic class in the same way as with Table, that would be consistent and elegant. 

I agree with @bang88, that this should work and would fix surfaced issue without the need to extract Column or other ugly workarounds:
```
// Define a  generic Table 
class MyTable extends Table<IPhoto>{}
// Define the generic Column.
class MyColumn extends Table.Column<IPhoto>{}
```

**Comment by piotrwitek** [comment]
@yesmeck I have updated my proposal, please check it for details of possible solutions

**Comment by yesmeck** [comment]
@piotrwitek Could you send a PR, if we can resolve this issue by not exporting Column, I'd like to +1.

**Comment by piotrwitek** [comment]
@yesmeck sure I'll take a look at this in coming days

**Comment by benjycui** [comment]
@yesmeck how about this, use `getColumnConfig` instead of read props from it directly?

```jsx
class TableColumn extends React.Component {
  getColumnConfig() {
    ...
  }
}
```

**Comment by afc163** [comment]
Add some doc about `Using Table in TypeScript`

**Comment by yesmeck** [comment]
@benjycui 没看懂。

**Comment by afc163** [comment]
@yesmeck Could it to be closed?

**Comment by yesmeck** [comment]
@piotrwitek Try latest version of antd.
