### ISSUE TITLE
InputNumber onPressEnter not working properly

### ISSUE THREAD

**Issue by gregor-mueller** [ant-design/ant-design#43251]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-inputnumber-onpressenter-f3krnf?file=/index.js)

### Steps to reproduce

Run the example in any modern environment (e.g. test suites) that does not support [`KeyboardEvent.which`](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) anymore. The value will always be `0` and the callback will not be triggered.

### What is expected?

The callback provided to `onPressEnter` should be triggered in all modern environments.

### What is actually happening?

In some environments (e.g. tests running via testing-library), the callback provided to `onPressEnter` is not called. This is due to rc-input-number < 8.x using a deprecated keyboard event property ["which"](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which):

Here is the fix:
https://github.com/react-component/input-number/commit/a225ca04e57f92fc77b7c6770cd90bcbb3813f95#diff-2b8b09f37ab696a03bb4cf168ef4f3c348a99d1f5bbb4d645f5520153d8790f8R459

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | Mac |
| Browser | @testing-library/react |

---
The fix would be updating rc-input-number to 8.x, but the corresponding PR has been closed 2 weeks ago:

https://github.com/ant-design/ant-design/pull/42998

**Comment by zombieJ** [comment]
React is already handle this with [SyntheticEvent](https://legacy.reactjs.org/docs/events.html#keyboard-events), it's safe to use it:

Proxy code: https://github.com/facebook/react/blob/a1c62b8a7635c0bc51e477ba5437df9be5a9e64f/packages/react-dom-bindings/src/events/SyntheticEvent.js#L493

But I'm OK to accept PR for updating use `key` instead.

**Comment by gregor-mueller** [comment]
Glad to hear! Looking forward to the next antd release then! 🙇

**Comment by zombieJ** [comment]
Since it's low priority task and no volunteer take this, closed.

**Comment by gregor-mueller** [comment]
I see, the `rc-input-number` has been updated. So the issue is even resolved with the next release, I guess. 👍
