### ISSUE TITLE
提供更多的按钮样式，或者可以自定义按钮样式【Provide more button styles, or you can customize the button style】

### ISSUE THREAD

**Issue by HCenggel** [ant-design/ant-design#43254]
### What problem does this feature solve?

一般列表会有很多的操作按钮，红色表示删除，黄色表示有一定风险，蓝色表示平常操作等等
【Generally, the list will have a lot of operation buttons, red means delete, yellow means there is a certain risk, and blue means normal operation.】

### What does the proposed API look like?

```html
<button nz-button nzType="{{my_class}}">xxx</button>
```
```css
.ant-btn-{{my_class}} {
  // my style
}
```

**Comment by MadCcc** [comment]
这种建议自己包一层
```tsx
import { Button, ButtonProps } from 'antd';

interface MyButtonProps {
  myType: string;
}

const MyButton: FC<ButtonProps & MyButtonProps> = ({ myType, ...props }) => {
  return (
    <Button className={myType} {...props} />
  );
}
```

**Comment by HCenggel** [comment]
> 

我现在也是用类似的方式去实现的

**Comment by HCenggel** [comment]
> 这种建议自己包一层
> 
> ```tsx
> import { Button, ButtonProps } from 'antd';
> 
> interface MyButtonProps {
>   myType: string;
> }
> 
> const MyButton: FC<ButtonProps & MyButtonProps> = ({ myType, ...props }) => {
>   return (
>     <Button className={myType} {...props} />
>   );
> }
> ```

我现在也是用类似的方式去实现的
