### ISSUE TITLE
建议：能否提供可下载的1.x版本文档

### ISSUE THREAD

**Issue by kevin262516** [ant-design/ant-design#4325]
使用的是antd1.x版本，需要查看文档时候， 该链接 http://1x.ant.design/docs/react/introduce 经常会打不开，尝试过爬取页面未成功；

建议:官方能否提供一个可供下载的1.x的官方文档

**Comment by yesmeck** [comment]
把 https://github.com/ant-design/1x.ant.design clone 到本地即可。
