### ISSUE TITLE
从v4升级到v5后css样式层级更变，并且无法降低默认css的层级

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#43261]
### Steps to reproduce

例如 tab 组件
#### 当我在v4的时候
 我通过 emotion css来进行css变更，做些样式覆盖或者自定义样式的操作，由于v4还是使用的 less 文件，所以这一切都是可以 work 的
这是 v4版本的截图, 可以看到默认样式被我成功覆盖

![image](https://github.com/ant-design/ant-design/assets/67216143/78234518-63dc-4d39-9af4-2a1e9ed5f339)

####  当我在 v5 的时候
但是当我在 v5 的时候，无法再通过 emotion css 进行样式覆盖了，因为v5开发的cssinjs，权重太高了
并且我已经使用了 ` <StyleProvider hashPriority="high">` 来进行降权
这是v5版本的截图，可以看到自定义的样式无法使用，直接被覆盖掉了

![image](https://github.com/ant-design/ant-design/assets/67216143/6c9b58d6-bc4a-4b23-816b-0e720c6a9f14)

### What is expected?

不覆盖我自己的css样式

### What is actually happening?

直接覆盖掉了

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 17 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by li-jia-nan** [comment]
是不是cssinjs版本不对，读取不到上下文，建议给复现链接

**Comment by MadCcc** [comment]
`hashPriority="high"` 会提高 hash 的优先级，而不是降权

**Comment by Ali-ovo** [comment]
> `hashPriority="high"` 会提高 hash 的优先级，而不是降权

噢噢 那就是这个文档有点问题 或 是我理解错了
![image](https://github.com/ant-design/ant-design/assets/67216143/e57162bf-d62b-476d-9972-e748b1efbd2c)

我看这个文档认为 配置 `hashPriority="high"` 会移除 `:where` 选择器 从而进行降权

**Comment by MadCcc** [comment]
我觉得文档写的挺明白的，默认会保持低优先级。
这个问题先关闭了，如果有其他问题欢迎新开 issue 反馈
