### ISSUE TITLE
Drawer内使用 ConfigProvider和destroyOnClose会导致Modal.confirm重置为英文

### ISSUE THREAD

**Issue by witszc** [ant-design/ant-design#43263]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7zgyqk?file=/index.js)

### Steps to reproduce

1.先点击Modal.confirm按钮，此时是中文
2.关闭Modal后点击打开抽屉，再关闭抽屉
3.再次点击Modal.confirm按钮，此时被重置成了英文

### What is expected?

Drawer使用 ConfigProvider和destroyOnClose后不影响国际化

### What is actually happening?

Drawer使用 ConfigProvider和destroyOnClose后会导致Modal.confirm被重置成英文

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome  114.0.5735.133（正式版本） (x86_64) |

**Comment by afc163** [comment]
确实经常发现 Modal.confirm 被重置回英文。

**Comment by witszc** [comment]
因该是LocaleProvider销毁后触发了changeConfirmLocale();重置成了默认语言
React.useEffect(() => {
    changeConfirmLocale(locale && locale.Modal);
    return () => {
      changeConfirmLocale();
    };
  }, [locale]);

**Comment by witszc** [comment]
又发现个问题，就算Drawer没有开启destroyOnClose，如果在Drawer里使用了其他语言，也会导致Modal.confirm被设置成同样的语言

**Comment by Yuiai01** [comment]
那我来跟一下这个问题吧

**Comment by 841660202** [comment]
项目中遇到，只影响 Modal.confirm，临时处理方案：定制下  okText、cancelText

**Comment by 841660202** [comment]
我的项目中遇到了，目前发现只会影响 Modal.confirm，临时处理方案：定制下 okText、cancelText
