### ISSUE TITLE
功能: 组件Spin增加自定义Spinner

### ISSUE THREAD

**Issue by luoxiaobatman** [ant-design/ant-design#4326]
`<Spin spinner={React.Element} />`

**Comment by afc163** [comment]
Why? 自定义组件的话，为啥不直接调用你的 spinner。

**Comment by luoxiaobatman** [comment]
@afc163
为了提高组件的通用性，不用复写自己spinning cloak等ui逻辑
起因是自己尝试修改Spin组件，从antd@2.0.0 -> antd@2.5.2后出现问题一些小问题需要重新改，很麻烦。

**Comment by afc163** [comment]
这个扩展对 Spin 自身意义不大，建议自行封装新的组件。
