### ISSUE TITLE
颜色选择器（colorPicker）有考虑加个取色管功能吗

### ISSUE THREAD

**Issue by lengmeiyumo** [ant-design/ant-design#43262]
### What problem does this feature solve?

取当前页面的某个地方的颜色，直接吸取颜色赋值到颜色板中

### What does the proposed API look like?

点击取色管，吸取任何地方的颜色

**Comment by li-jia-nan** [comment]
原生的取色管 api 兼容太差了

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/7123d6ea-17b5-447f-ba75-d7922f8e47e2)
对浏览器版本要求很高，暂时不会考虑
