### ISSUE TITLE
TreeSelect. TreeNode的value是筛选字段，不合理

### ISSUE THREAD

**Issue by ShikiRyougi** [ant-design/ant-design#4327]
一般来说筛选字段应该和title是一致的
例如一般value都会设置为主键，title为name，搜索的时候就很不和谐

**Comment by yesmeck** [comment]
你说的没错，但是 title 可以是任意的 ReactElement，所以要做到默认基于 title 筛选是很有难度的，而且这个版本里我们也不会做这样的破坏性修改。

如果要修改筛选行为，可以通过`filterTreeNode`来实现你想要的逻辑。

**Comment by raisezhang** [comment]
这个问题可以换个思路啊，  比如在 props 里面添加 searchKey: 'key' || 'index' || 'lable'    或者直接设置为 searchText  之类    

这个需求还算比较合理， 用户肯定关心的是展现的东西，而不是程序里面所关注的key~     

多谢~

**Comment by yesmeck** [comment]
设置 searchText 的其实跟设置 filterTreeNode 也差不多了。

**Comment by ShikiRyougi** [comment]
看了一下 treeNodeFilterProp其实就是searchKey/searchText的功能 建议demo里面选一个例子增加这个属性作用的展示 这个需求还是比较常见的 按直觉ctrl+f search/select匹配不上filterTreeNode和treeNodeFilterProp 一般就会以为不支持
