### ISSUE TITLE
在Firefox,微前端iframe模式子应用加载 @ant-design/icons会报错，Tooltip组件 的位置也有问题，在chrome都是正常的

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design#43278]
### Reproduction link

[https://github.com/faner11/micro-app-demo](https://github.com/faner11/micro-app-demo)

### Steps to reproduce

# 复现流程
## 安装依赖
- cd main-app && pnpm i
- cd child-app && pnpm i

## 启动
- cd main-app && pnpm dev
- cd child-app && pnpm dev

## 其他

主要代码在 child-app/src/App.tsx 里面

### What is expected?

在firefox 表现正常

### What is actually happening?

在firefox会报错

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2 |
| System | mac os |
| Browser | firefox 104 |

---
微前端框架 @micro-zoe/micro-app: 1.0.0-beta.5

@ant-design/icons 降级到 4.x 是正常的，但是 5.x 会报错

**Comment by faner11** [comment]
https://github.com/micro-zoe/micro-app/issues/827

**Comment by faner11** [comment]
> 看报错更像是微前端的问题

@ant-design/icons 降级到 4.x 又正常，这种兼容性问题头大

**Comment by afc163** [comment]
先反馈给 https://github.com/micro-zoe/micro-app/issues 吧。
