### ISSUE TITLE
Form 点击提交时触发未预期的 onFieldsChange 事件

### ISSUE THREAD

**Issue by feix760** [ant-design/ant-design#43276]
### Reproduction link

https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-11-forked-r62slm?file=/demo.tsx

### Steps to reproduce

点击提交

### What is expected?

不要触发 `onFieldsChange`

### What is actually happening?

触发 `onFieldsChange`

| Environment | Info |
| --- | --- |
| antd | 4.24.11 |
| React | 18 |
| System | macos |
| Browser | chrome 110 |

**Comment by zombieJ** [comment]
试了一下在 `4.24.10` 也会触发，不过会少一次：https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-11-forked-rqvvjp?file=/package.json

感觉之前版本也有这个问题。
