### ISSUE TITLE
Ellipsis flickering

### ISSUE THREAD

**Issue by Alex2518-9** [ant-design/ant-design#43279]
### Reproduction link

[https://github.com/Alex2518-9/ellipsis-issue/blob/main/src/pages/index.tsx](https://github.com/Alex2518-9/ellipsis-issue/blob/main/src/pages/index.tsx)

### Steps to reproduce

1. Typography.Paragraph settings:

 ellipsis={{
            expandable: true,
            rows: 2,
            symbol: "More",
          }}

### What is expected?

Display the corresponding number of rows for the first render without flickering.

### What is actually happening?

For the first render, it shows the whole text and then collapses.

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2 |
| System | windows |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
There is indeed flickering. https://codesandbox.io/s/ji-ben-antd-5-6-3-forked-k6t585

**Comment by heiyu4585** [comment]
seam problem: https://github.com/ant-design/ant-design/issues/42958
