### ISSUE TITLE
borderRadius Token value cannot be bigger than 16

### ISSUE THREAD

**Issue by vaxevanis** [ant-design/ant-design#43271]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-dtk3d2?file=/App.tsx)

### Steps to reproduce

Customize the theme through the ConfigProvider and assign a value higher than `16` to the `borderRadius` Token.
```
<ConfigProvider
    theme={{
      token: {
        borderRadius: 17, 
      },
    }}
  >
    <Button />
  </ConfigProvider>
```

### What is expected?

borderRadius token value is expected to match the one assigned in the ConfigProvider. With the above example it should be 17.

### What is actually happening?

The borderRadius value is 16 instead of 17. A value of 16 seems to be the maximum value that is allowed as a borderRadius. Also the value 16 is used as a fallback for any value higher than that.  

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| System | Windows OS |
| Browser | Chrome |

---
Customize the Component borderRadius Token has the same outcome

**Comment by MadCcc** [comment]
It is intended. You can override by providing a custom algorithem.
Current algorithm about `borderRadius`: https://github.com/ant-design/ant-design/blob/master/components/theme/themes/shared/genRadius.ts

**Comment by zombieJ** [comment]
> It is intended. You can override by providing a custom algorithm. Current algorithm about `borderRadius`: https://github.com/ant-design/ant-design/blob/master/components/theme/themes/shared/genRadius.ts

Can we provide a doc to guide how to write a customize algorithm?

**Comment by MadCcc** [comment]
> Can we provide a doc to guide how to write a customize algorithm?

Yeah, we should. For those who want to customize algorithm, **darkAlgorithm** would be a good example: https://github.com/ant-design/ant-design/blob/master/components/theme/themes/dark/index.ts

**Comment by afc163** [comment]
这个判断感觉没太有必要。
