### ISSUE TITLE
Rename Collapse.Panel.header to label for consistency

### ISSUE THREAD

**Issue by sdt-jchau** [ant-design/ant-design#43280]
### What problem does this feature solve?

In v5, components with a title text uses a label prop.  For example, tabItem, menuItem timelineItem.  Collapse item title should follow consistent prop naming.  The prop is currently called header.  

### What does the proposed API look like?

Rename Collapse item header to label

**Comment by zombieJ** [comment]
Seems make sense. cc @ant-design/ant-design-collaborators

**Comment by sdt-jchau** [comment]
I was confused by the documentation.  Typescript typing is correct with ItemType.  Documentation was referencing old Collapse.Panel
