### ISSUE TITLE
使用自定义的字体导致组建显示不正常

### ISSUE THREAD

**Issue by falltodis** [ant-design/ant-design#4328]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: mac
- 浏览器及其版本: chome 55.0.2883.95

#### 您做了什么？请提供尽可能详细的重现步骤。

按照https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont 所示demo更换为本地字体，

#### 实际上的结果是:
搜索按钮变成文件夹，下拉按钮变成圆点
![image](https://cloud.githubusercontent.com/assets/7006864/21387081/fd4cdf7a-c7b0-11e6-9a76-c2038a849882.png)
![Uploading image.png…]()

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/HGnaTNOYnbsizjWRrhFo.png)

**Comment by falltodis** [comment]
升级到antd.2.5,字体一直是最新的，测试还是同样的问题。

**Comment by falltodis** [comment]
@afc163 清理package之后生效
