### ISSUE TITLE
Slider 组件中英文api不一致

### ISSUE THREAD

**Issue by AnYiTeng** [ant-design/ant-design#43286]
### Reproduction link

[https://ant.design/components/slider-cn](https://ant.design/components/slider-cn)

### Steps to reproduce

中文文档下没有 trackStyle、railStyle、handleStyle api

### What is expected?

中英文文档应一致

### What is actually happening?

中英文文档一致

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by ZWkang** [comment]
@MadCcc  #43296

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/43296#discussion_r1247681319
