### ISSUE TITLE
Badge 在status={"processing"}時設定color無效

### ISSUE THREAD

**Issue by TsungPao** [ant-design/ant-design#43284]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3tdv9n?file=/index.js)

### Steps to reproduce

antd版本5.6.3
<Badge status={"processing"} color={"green"} text={"True"}/>

### What is expected?

設定color為green應該要是綠色但他一樣是藍色

### What is actually happening?

設定color為green應該要是綠色但他一樣是藍色

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | Badge 在status={"processing"}時設定color無效 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
It is semantic and intented, a green `status="error"` badge would be strange.

**Comment by TsungPao** [comment]
我的意思是在status設定為processing會閃爍的狀態他預設為藍色的顏色 我想要更變成綠色但是沒有效果，在以往5.2.2的版本是正常的！

**Comment by TsungPao** [comment]
> `status` prop is semantic and intented to have default color, a green `status="error"` badge would be strange.
我的意思是在status設定為processing會閃爍的狀態他預設為藍色的顏色 我想要更變成綠色但是沒有效果，在以往5.2.2的版本是正常的！

**Comment by afc163** [comment]
这是预期的，`status="processing"` 就是蓝色的，你无法通过 color 修改进行中的色彩，否则无法保持 processing 的语义。

另外一个例子是 `status="error"` 时色彩会是红色的，如果你通过 color 修改为 `green`，那么 status error 的语义就没有办法体现了。因此使用 status 时无法通过 color 去改颜色。

不知道我说清楚了没。

**Comment by TsungPao** [comment]
> 这是预期的，`status="processing"` 就是蓝色的，你无法通过 color 修改进行中的色彩，否则无法保持 processing 的语义。
> 
> 另外一个例子是 `status="error"` 时色彩会是红色的，如果你通过 color 修改为 `green`，那么 status error 的语义就没有办法体现了。因此使用 status 时无法通过 color 去改颜色。
> 
> 不知道我说清楚了没。

但我覺得應該不會有人在error的狀態下設定為綠色的符號
如果因為此情況而扼殺掉了閃爍功能時候的顏色設置有點不靈活，再加上我喜歡讓燈號有閃爍的樣式再來搭配我自己想要的顏色

**Comment by 1587315093** [comment]
status-processing  的calss 权重比 color-green 的class 权重高

**Comment by TsungPao** [comment]
我認為在status="processing"時候顏色可以靈活自定義會比較好

**Comment by afc163** [comment]
如果你希望全局修改进行中的 Badge 的预设色彩，可以使用 ConfigProvider 进行主题定制：https://codesandbox.io/s/antd-reproduction-template-forked-slcwtm?file=/index.js

**Comment by TsungPao** [comment]
> 如果你希望全局修改进行中的 Badge 的预设色彩，可以使用 ConfigProvider 进行主题定制：https://codesandbox.io/s/antd-reproduction-template-forked-slcwtm?file=/index.js

這樣子的話只能單一種顏色了

**Comment by 1587315093** [comment]
提了加权重的 pr 了  #43289 ，允许改就合 不允许就close 吧😂

> 这是预期的，`status="processing"` 就是蓝色的，你无法通过 color 修改进行中的色彩，否则无法保持 processing 的语义。
> 
> 另外一个例子是 `status="error"` 时色彩会是红色的，如果你通过 color 修改为 `green`，那么 status error 的语义就没有办法体现了。因此使用 status 时无法通过 color 去改颜色。
> 
> 不知道我说清楚了没。

提了加权重的 pr 了  #43289 ，允许改就合 不允许就close 吧😂

**Comment by afc163** [comment]
> 這樣子的話只能單一種顏色了

确实要单独定制会麻烦一点。后面会有 styles 等更直接的属性支持。

> 但我覺得應該不會有人在error的狀態下設定為綠色的符號

这个也合理，用户改错了就接受错的结果。那就提一下优先级吧。

**Comment by TsungPao** [comment]
> > 這樣子的話只能單一種顏色了
> 
> 确实要单独定制会麻烦一点。后面会有 styles 等更直接的属性支持。
> 
> > 但我覺得應該不會有人在error的狀態下設定為綠色的符號
> 
> 这个也合理，用户改错了就接受错的结果。那就提一下优先级吧。

感謝您的諒解
