### ISSUE TITLE
Add LICENSE.md to react components

### ISSUE THREAD

**Issue by mdedetrich** [ant-design/ant-design#4329]
Due to not having a valid LICENSE valid in some of the react-components, webjars (www.webjars.org) are unable to work with ant-design

I have gone and created pull requests which add licenses to the various components, they are listed below for convenience

- [x] https://github.com/react-component/tabs/pull/47
- [x] https://github.com/react-component/util/pull/9
- [x] https://github.com/react-component/checkbox/pull/29
- [x] https://github.com/react-component/cascader/pull/17
- [X] https://github.com/react-component/menu/pull/71
- [x] https://github.com/react-component/rate/pull/4
- [x] https://github.com/react-component/form/pull/50
- [x] https://github.com/react-component/tree-select/pull/39
- [x] https://github.com/react-component/dropdown/pull/22
- [x] https://github.com/react-component/input-number/pull/38
- [x] https://github.com/react-component/notification/pull/10
- [x] https://github.com/react-component/align/pull/9
- [x] https://github.com/react-component/time-picker/pull/26
- [x] https://github.com/react-component/dialog/pull/46
- [X] https://github.com/react-component/table/pull/111
- [x] https://github.com/react-component/steps/pull/27
- [x] https://github.com/react-component/queue-anim/pull/28
- [x] https://github.com/react-component/radio/pull/2
- [X] https://github.com/react-component/collapse/pull/50
- [x] https://github.com/react-component/switch/pull/9
- [x] https://github.com/react-component/progress/pull/16
- [x] https://github.com/react-component/animate/pull/18
- [x] https://github.com/react-component/pagination/pull/46
- [x] https://github.com/react-component/tree/pull/49
- [x] https://github.com/yiminghe/css-animation/pull/9
- [x] https://github.com/yiminghe/async-validator/pull/27
- [x] https://github.com/react-component/editor-mention/pull/3
- [x] https://github.com/yiminghe/dom-align/pull/9
- [x] https://github.com/yiminghe/add-dom-event-listener/pull/1
- [x] https://github.com/react-component/editor-plugin-image/pull/1
- [x] https://github.com/react-component/select/pull/153

This is urgent, so it would be good if the above pull requests can be merged asap. I will close the ticket when everything is merged from my end

**Comment by benjycui** [comment]
👍 Thanks

**Comment by benjycui** [comment]
And others can try to help @mdedetrich

**Comment by mdedetrich** [comment]
async-validator was added to the list, it was missed before as it was a transitive dependency

**Comment by mdedetrich** [comment]
@benjycui I have added another react component which was missing (react-component/editor-mention#3
). BTW You don't need to republish the npm packages, all that is needed for webjars is for the LICENSE.md to exist in the git repo

**Comment by mdedetrich** [comment]
@benjycui @yiminghe Another dependency has been added, dom-align https://github.com/yiminghe/dom-align/pull/9

**Comment by mdedetrich** [comment]
@benjycui @yiminghe Two more dependencies have been added

**Comment by mdedetrich** [comment]
@benjycui @yiminghe @afc163 Another dependency (rc-select) was added

**Comment by mdedetrich** [comment]
All components have been added, will reopen if this issue if I find any more. Thanks!
