### ISSUE TITLE
Tree树形控件 filterTreeNode是如何使用的，目前用到这个api过滤功能不生效

### ISSUE THREAD

**Issue by liushuhui** [ant-design/ant-design#43298]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-n79ygk)

### Steps to reproduce

输入框输入关键字，过滤掉不匹配关键字的其他树节点

### What is expected?

输入框输入关键字，过滤掉不匹配关键字的其他树节点

### What is actually happening?

没有任何反应

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | ^18.2.12 |
| System | window |
| Browser | google |

<img width="357" alt="f582c0a0004d94c0dcdd5bebb3041eca" src="https://github.com/ant-design/ant-design/assets/26155477/86fd6740-77fe-4813-8409-ebc082fcd8b6">

**Comment by afc163** [comment]
inputKeyWord 始终为 `''`，导致 filterTreeNode 返回值一直是 false，请自行检查相关代码逻辑。

**Comment by liushuhui** [comment]
> inputKeyWord 始终为 `''`，导致 filterTreeNode 返回值一直是 false，请自行检查相关代码逻辑。

这是一个搜索输入框，inputKeyWord并不为空的，点击搜索图标或者回车键后inputKeyWord是有值的

**Comment by afc163** [comment]
<img width="250" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/02507bdc-6ffa-4296-83b7-dcb5eae37290">

<img width="647" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/f6e13f77-ed6a-4e09-b0e7-79033afecfad">

目前还不支持隐藏功能，可以关注 https://github.com/ant-design/ant-design/issues/27197 ，欢迎来帮忙 PR。
