### ISSUE TITLE
setFieldsValue bug with union type of Array and null

### ISSUE THREAD

**Issue by AndreiTS** [ant-design/ant-design#43305]
### Reproduction link
I cannot reproduce this on [codesanbox](https://codesandbox.io/s/antd-reproduction-template-forked-s23cfs?file=/index.tsx), probably because it's using a different typescript version, so I'm using
[TypeScript playground](https://www.typescriptlang.org/play?#code/PTAEBUAsEsGdQC4E8AOBTUBjA9gWzfAGYBOeokCCKsAXCLAgIaYDW2AbmsYQDbYDuAOhy5gjYAFYAjAGYAbBIAMMgOwAoZOlAAlNJgCuxWNE4AFRsQTRGPADzgAfKAC8oAN5rQoANqnQ0ADtQFjQkbEIIAF0AfhpPLwhfSNA0AA8ENACAE3gACkDCLlAAVQBKb2TonT1DYzMLKxtbYocK0DiExNNktIzs+GwAIwArPQRQAB9QfWy0QkC0LNAq3QMjEzRzS2s7cCSnDoS97oBuNQBfM7UQCBh4TQwRAlASMmJMAFp5tB4sr+xiKICMBAhluMw0IIsoIELANKgMKtahsto0eABBAIILL2JyuABy2AC+P0PB4jEGPDQuJS6UyOVAQ1GmHGVQ8nV8-iCITCEXAMRooEJxNJ5Mp1OOkScvXpeQKRTKbRWNXW9W2TRabUFwpJZIpVPs+1pfQZTLGy2qazqmwaO0N3QOXUiZ3O7VAjACSCuNwAInNAtArETGRE0oxcCgqYgEXC1KCuIQIRACAgAJIBAJFdkJQKZ4iCgL6XCDLgutRxrEJpPgFPueJeRiC7OdLyDQUAckG7YANPWW5gO5h233zr3OllBTWGOm820poWyRdyzcAMJEhjEfQswIAc3diBT5ZwAQYB4Yk9rrmb7qbfc6bdAnZ7d4SA8fQ5HY4SE9AC54S+uMAoDgF4Zm3YN9FgZ4kVVG11R4F5SFwUAAGUmFYAB5ThiD4fg1GPU8oIQAAxaAfhyAA1Gx9AwVxcnYaiCEFGDrVRO0pwQBxShcJw3HONQiNI8jYCongaNyDIGFKZcgLuUCAnAoJIOglVWNtGxELID1sXw9dxkEsjfhExjMWxFxQHoxjaEtZE1TRUycQ4riePcfiDOE0SaIciSU2kwDQB-DiZy4Odf1Ffx4DQBixMYDIlgQbAAovacMxC5IphmLJ-UzLJ-MwRhIN3fdj14aAWVAfhA0gZNT3ABEgA)

### Steps to reproduce

Open TypeScript playground link and check the error.

### What is expected?

Is expected that setFieldsValue supports properties of type Array | null

### What is actually happening?

setFielsValue errors on properties of type Array | null

| Environment | Info |
| --- | --- |
| antd | 5.6.3 |
| React | 18.2.0 |
| TypeScrpt | 5.1.6 |
| System | Windows 11 |
| Browser | Firefox 102 |

**Comment by afc163** [comment]
Try to reproduce by forking https://codesandbox.io/s/quizzical-carson-z4kjnl and change typescript version in package.json

**Comment by AndreiTS** [comment]
@afc163 here is a minimal reproduction: https://github.com/AndreiTS/antd-setFieldsValue-typescript

![image](https://github.com/ant-design/ant-design/assets/13489837/78401651-c559-4354-acd4-3276aa47fea0)
![image](https://github.com/ant-design/ant-design/assets/13489837/859ae2b6-c1ea-4953-ba5b-2288d74b32f8)

this problem occurs because of this RecursivePartial implementation:
![image](https://github.com/ant-design/ant-design/assets/13489837/2fe84c9c-93c0-4424-8536-04b7d0983bad)

**Comment by afc163** [comment]
https://github.com/react-component/field-form/pull/592 @kiner-tang 帮忙看看

**Comment by kiner-tang** [comment]
> [react-component/field-form#592](https://github.com/react-component/field-form/pull/592) @kiner-tang 帮忙看看

我看看

**Comment by AndreiTS** [comment]
@kiner-tang changing any to T is better but don't fix the original issue: [typescript playground](https://www.typescriptlang.org/play?#code/PTAEBUAsEsGdQC4E8AOBTUBjA9gWzfAGYBOeokCCKsAXCLAgIaYDW2AbmsYQDbYDuAOhy5gjYAFYAjAGYAbBIAMMgOwAoZOlAAlNJgCuxWNE4AFRsQTRGPADzgAfKAC8oAN5rQoANqnQ0ADtQFjQkbEIIAF0AfhpPLwhfSNA0AA8ENACAE3gACkDCLlAAVQBKb2TonT1DYzMLKxtbYocK0DiExNNktIzs+GwAIwArPQRQAB9QfWy0QkC0LNAq3QMjEzRzS2s7cCSnDoS97oBuNQBfM41UDFXaja3GngBBAIQsgHkeLPsnVwA5bABf76Hg8RiDHhoX4pdKZHKgIajTDjKoeTq+fxBEJhCLgGI0UCA4Gg8GQ6HHSJOXrwvIFIplNorGrrerbJotNqE4kgsEQqH2fawvoIpFjZbVNZ1TYNHaC7oHLqRM7ndqgRgBJBXTS3FnSx47V7vf5ofgwgFA3lkgWOYW0xEjcVo+JeTGBYKhcJRWJEy2k-kUoU0-qgfIBQrEErlSqS+5sp7NVrJbl+vnk+VUu0hsUoiV3Vky9m7IWEykqtXgK4gNTXLTgAgIK0udwu0DsGz6NCEhjEQIAczaUwCpJVNZ1EAbxVm8wCi2b6IS7Z4ne7CF7AQHySmMyycwWWVHahwAQYiAbVtL59J89bS5XPkiFxrx9PGQYU93M8Wl-f0-3N86O8uwfJ81GrI8gVPWA0AQAAxaA0G+WAADUOwwVxciA2hYwLA0mnrBgrQcUoXCcNxzjUaC4IQpDUOXNBcjfRtSRIkBERYZ9IPGKj4MQnI6M7AAmZtMLQ7D831WV8MnP9ZyyYjSPcCieJo-i0MYmTP33ViwGwDiwOATiT24mDeNotCjU+b4RKwwkJIeKSXjeKyfgI5iwQU5wyOU0zVJQiznK+LINMIljQDYrhSGIIyoN8vj-PoyyguEjDbJwySiyS757E0vc5M87zKLi8zEsC75BJChAPzyxYdPYmtwJfEzqPigS0Esk1+BssS7L1BzMuczqctCjySK8pSipakrOw601KqtOrIuwaKIOM0AVNagLjVNFLQzS+z40NQbTWGqrZMWAqJo26b2uO-gKqY6qvyyOq9KAA)

**Comment by kiner-tang** [comment]
> @kiner-tang changing any to T is better but don't fix the original issue: [typescript playground](https://www.typescriptlang.org/play?#code/PTAEBUAsEsGdQC4E8AOBTUBjA9gWzfAGYBOeokCCKsAXCLAgIaYDW2AbmsYQDbYDuAOhy5gjYAFYAjAGYAbBIAMMgOwAoZOlAAlNJgCuxWNE4AFRsQTRGPADzgAfKAC8oAN5rQoANqnQ0ADtQFjQkbEIIAF0AfhpPLwhfSNA0AA8ENACAE3gACkDCLlAAVQBKb2TonT1DYzMLKxtbYocK0DiExNNktIzs+GwAIwArPQRQAB9QfWy0QkC0LNAq3QMjEzRzS2s7cCSnDoS97oBuNQBfM41UDFXaja3GngBBAIQsgHkeLPsnVwA5bABf76Hg8RiDHhoX4pdKZHKgIajTDjKoeTq+fxBEJhCLgGI0UCA4Gg8GQ6HHSJOXrwvIFIplNorGrrerbJotNqE4kgsEQqH2fawvoIpFjZbVNZ1TYNHaC7oHLqRM7ndqgRgBJBXTS3FnSx47V7vf5ofgwgFA3lkgWOYW0xEjcVo+JeTGBYKhcJRWJEy2k-kUoU0-qgfIBQrEErlSqS+5sp7NVrJbl+vnk+VUu0hsUoiV3Vky9m7IWEykqtXgK4gNTXLTgAgIK0udwu0DsGz6NCEhjEQIAczaUwCpJVNZ1EAbxVm8wCi2b6IS7Z4ne7CF7AQHySmMyycwWWVHahwAQYiAbVtL59J89bS5XPkiFxrx9PGQYU93M8Wl-f0-3N86O8uwfJ81GrI8gVPWA0AQAAxaA0G+WAADUOwwVxciA2hYwLA0mnrBgrQcUoXCcNxzjUaC4IQpDUOXNBcjfRtSRIkBERYZ9IPGKj4MQnI6M7AAmZtMLQ7D831WV8MnP9ZyyYjSPcCieJo-i0MYmTP33ViwGwDiwOATiT24mDeNotCjU+b4RKwwkJIeKSXjeKyfgI5iwQU5wyOU0zVJQiznK+LINMIljQDYrhSGIIyoN8vj-PoyyguEjDbJwySiyS757E0vc5M87zKLi8zEsC75BJChAPzyxYdPYmtwJfEzqPigS0Esk1+BssS7L1BzMuczqctCjySK8pSipakrOw601KqtOrIuwaKIOM0AVNagLjVNFLQzS+z40NQbTWGqrZMWAqJo26b2uO-gKqY6qvyyOq9KAA)

That's because strictNullChecks is turned on by default, so you can turn it off and try again.
![image](https://github.com/ant-design/ant-design/assets/10286961/06bcbdc2-a8db-4b61-9aba-26eb998a763a)
<img width="1230" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/91b076b1-e565-4eb6-91a1-422dc90f57a0">

**Comment by kiner-tang** [comment]
> Could you support this option? It's turned on by default, and enabled is TypeScript is on strict mode

If you want to keep this option on, wouldn't it be better not to use 'null' in the type definition? You can use other types instead. This is due to strictNullChecks in Typescript, not our RecursivePartial tool

**Comment by AndreiTS** [comment]
Yes, I can. I actually replaced all null by undefined in my project where it was complaining, but it is annoying and it's probably going to affect someone else. I think there are other RecursivePartial implementations that could help if this.

**Comment by AndreiTS** [comment]
🤡 

![image](https://github.com/ant-design/ant-design/assets/13489837/0c89fffb-b05d-4ff9-b0ef-116560b94b56)

**Comment by yuki2006** [comment]
Given the issue shown in the example above, I would like to reopen this issue and request a resolution

**Comment by alex-kudryashov** [comment]
I ran into the same issue and noticed that it’s resolved by adding one more type to the list of possible ones. For example, in my form I have a field called “role”. If I specify that it can be number[] | null, then from setFieldsValue I end up getting number[] | undefined. But if I extend my type to number[] | null | string, then from the same method I get number[] | null | string | undefined.

I consider disabling the TypeScript-recommended option a bad solution, because it may lead to unexpected runtime errors.
