### ISSUE TITLE
Using i18n or LocaleProvider on dva-cli based sample

### ISSUE THREAD

**Issue by visvadw** [ant-design/ant-design#4330]
Dear Ant Design team,

How can I implement i18n (with LocaleProvider or react-intl) on [my dvajs-user-dashboard sample](https://github.com/visvadw/dvajs-user-dashboard)? Existing documentation refers to a standard (non dva-cli generated) project.

I apologise if this question for help should be raised into [dva-cli repo](https://github.com/dvajs/dva-cli).

Thank you!

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues/20#issuecomment-234847226

**Comment by visvadw** [comment]
Hello,

I just tried, you may check the [result](https://github.com/visvadw/dvajs-user-dashboard):

![image](https://cloud.githubusercontent.com/assets/14140226/21422608/1c64a8a8-c841-11e6-89ac-d61d14ff1002.png)

Thanks.

**Comment by sorrycc** [comment]
React not defined? You need import React in your `index.js`.

**Comment by visvadw** [comment]
Understood that, but adding:
```
import ReactDOM from 'react-dom';
import React from 'react';
```
the result is:
![image](https://cloud.githubusercontent.com/assets/14140226/21428236/b1413ab6-c861-11e6-9ca0-061f2fe33dcf.png)

**Comment by sorrycc** [comment]
Try this:

```diff
- const App = app.start('#root');
+ const App = app.start();
```

**Comment by visvadw** [comment]
Finally! It works! 😄  I need to further dig into dva to understand these tricks.
Many many thanks for the help! 👍

**Comment by guangming21** [comment]
@sorrycc 为什么我做多语言切换页面不更新呢
![qq 20170210111650](https://cloud.githubusercontent.com/assets/18028721/22812968/0a498576-ef83-11e6-99c4-594a12eab912.png)
![qq 20170210111723](https://cloud.githubusercontent.com/assets/18028721/22812969/0a4cd226-ef83-11e6-96a0-47ba7502eae0.png)
![qq 20170210111742](https://cloud.githubusercontent.com/assets/18028721/22812970/0a4d3ec8-ef83-11e6-92d3-5352eda59e45.png)
![qq 20170210111759](https://cloud.githubusercontent.com/assets/18028721/22812971/0a79f206-ef83-11e6-8821-72e74f3d63af.png)
最后console打印的appLocale状态已经改变了，为什么页面不更新呢

**Comment by mkrn** [comment]
@guangming21 Add `key={appLocale.locale}` prop to your `<LocalProvider>` and `<IntlProvider>`  so it will force to re-render everything inside!
