### ISSUE TITLE
Dropdown能否阻止menu展开？ 不想去单独做受控，希望能够onClick时阻止点开，能做到吗？

### ISSUE THREAD

**Issue by DroganC** [ant-design/ant-design#43318]
### What problem does this feature solve?

非受控状态下通过e.preventDefault() 阻止展开

### What does the proposed API look like?

在onChange里或其他属性

**Comment by RedJue** [comment]
受控和非受控就是字面意思，非受控情况下是没法阻止内部状态的，如果把口子暴露出来会破坏原本设计的意图。
