### ISSUE TITLE
ColorPicker对部分预定义颜色无法识别

### ISSUE THREAD

**Issue by aijunhao** [ant-design/ant-design#43322]
### Reproduction link

[https://stackblitz.com/edit/react-97cuuc?file=demo.tsx](https://stackblitz.com/edit/react-97cuuc?file=demo.tsx)

### Steps to reproduce

选择颜色预设的第3项或者倒数第2项

### What is expected?

能正常识别预设颜色

### What is actually happening?

ColorPicker 预设颜色 volcano、geekblue 被识别成 #000000。

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | 18.2.0 |
| System | mac |
| Browser | google 14.0.5735.133 |

---
业务场景：colorPicker 选择颜色（hex）通过转换为预设颜色（red、gold等）设置到 tag 中。
在 tag 标签组件中支持 volcano、geekblue 等预设颜色，但是 colorPicker 不支持这两种预设，虽然可以使用 hex 绕过，但是代码效果上差了一些些。

**Comment by MadCcc** [comment]
可以先这样取值
```
import { theme, ColorPicker } from antd;

export default () => {
  const { token } = theme.useToken();

  return <ColorPicker presets={[ label: 'Recommended', colors: [token.blue, token.green] ]} />
}

**Comment by afc163** [comment]
`'volcano'` 不是浏览器认识的标准色值，不建议直接传给 ColorPicker。
