### ISSUE TITLE
Drawer组件弹层展现后，蒙层下面的内容还是可以横向滚动且滚动条未消失

### ISSUE THREAD

**Issue by xuanxuan321** [ant-design/ant-design#43326]
### Reproduction link

[https://stackblitz.com/edit/react-smwv8b?file=demo.tsx](https://stackblitz.com/edit/react-smwv8b?file=demo.tsx)

### Steps to reproduce

1点击页面中的button
2 弹层出现，但是底部的滚动条未消失，蒙层下的内容依然可以横向滚动

### What is expected?

1点击页面中的button
2 弹层出现，底部的滚动条消失，蒙层下的内容禁止滚动

### What is actually happening?

1点击页面中的button
2 弹层出现，底部的滚动条未消失，蒙层下的内容依然可以横向滚动

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 16.12.0 |
| System | macos 13.4.1  |
| Browser | chrome 版本 114.0.5735.198（正式版本） (arm64) |

---
antd 4.16.8 版本中是没有这个问题的，因为该版本中，抽屉出现的时候，body上面会被加上touch-action: none; overflow: hidden;
但是版本5中，body中就没有加上touch-action: none; overflow: hidden;

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/43327
