### ISSUE TITLE
ConfigProvider config 设置主题色和 prefixCls 都不生效

### ISSUE THREAD

**Issue by gauseen** [ant-design/ant-design#43346]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quan-ju-yang-shi-antd-4-24-12-forked-9f7qlw?file=/demo.tsx)

### Steps to reproduce

在 demo 中修改主题色，不生效，设置 prefixCls 也不生效

### What is expected?

生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.0.0 |
| System | macOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
```diff
-- import "antd/dist/antd.css";
++ import "antd/dist/antd.variable.css";
```

https://codesandbox.io/s/quan-ju-yang-shi-antd-4-24-12-forked-djm8tr

参考文档说明哈：https://4x-ant-design.antgroup.com/docs/react/customize-theme-variable-cn

**Comment by gauseen** [comment]
@zombieJ  通过 ConfigProvider.config 设置 prefixCls 不生效是啥原因呢？是使用姿势有问题吗~

![image](https://github.com/ant-design/ant-design/assets/22701565/2825ad09-a1de-4f5f-93b0-41689f5b46e1)

**Comment by RedJue** [comment]
`ConfigProvider.config` 只会对非 hooks 的静态方法调用生效。https://4x-ant-design.antgroup.com/components/config-provider-cn/#ConfigProvider.config()-4.13.0+ , 全局组件 `prefixCls` 设置参考👇🏻
```tsx
<ConfigProvider prefixCls="custom-prefixCls">
    <App />
</ConfigProvider>
```
