### ISSUE TITLE
Popover 组件 showArrow=false 无效

### ISSUE THREAD

**Issue by RGBWang** [ant-design/ant-design#43347]
### Reproduction link

[https://github.com/RGBWang/rp-popover-showArrow](https://github.com/RGBWang/rp-popover-showArrow)

### Steps to reproduce

showArrow 设置false，界面依然出现白色三角箭头

### What is expected?

没有白色三角箭头

### What is actually happening?

有白色三角箭头

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | win10 |
| Browser | edge |

**Comment by Wxh16144** [comment]
试试 `arrow={false}`
<img width="1242" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/af363f43-2681-41d4-a836-aa590070397e">
