### ISSUE TITLE
Input.Search 宽度问题

### ISSUE THREAD

**Issue by wmzy** [ant-design/ant-design#4334]
#### 发生问题的环境是：

- antd 版本: antd@2.5.2

[Input.Search](https://ant.design/components/input-cn/#components-input-demo-search-input) 没有设置宽度，在不同浏览器表现不一致，为什么不和Input保持一致？

**Comment by RaoHai** [comment]
可以自己设置 `<Input.Search style={{ width: 200 }} />`

**Comment by wmzy** [comment]
@RaoHai 你好，你的回答并不是我问题关注的重点。
我的理解是，Search组件放到Input下，一些行为应该和它保持一致。
不知道你们的观点是什么？

**Comment by afc163** [comment]
同意。
