### ISSUE TITLE
DatePicker 日期选择框 选择年份时 点击下方的此刻没有用

### ISSUE THREAD

**Issue by zeroter** [ant-design/ant-design#43354]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gj377q)

### Steps to reproduce

1.点击DatePicker 弹出时间选择框
2.选择年份
3.点击下方的now

### What is expected?

点击now的时候可以选中当前时间并关闭弹框

### What is actually happening?

点击now后什么都没有触发

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 1.8.2.0 |
| System | Windows |
| Browser | Microsoft Edge |

**Comment by afc163** [comment]
切换到年月时应该隐藏掉的，包括 OK 也是。

**Comment by Yuiai01** [comment]
> 切换到年月时应该隐藏掉的，包括 OK 也是。

那我来整一下
