### ISSUE TITLE
Table Component: Filters do not close when another is opened

### ISSUE THREAD

**Issue by xuanxuan321** [ant-design/ant-design#43353]
### Reproduction link

[https://stackblitz.com/run?file=demo.tsx](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

Click the two filter buttons of the table respectively, and two filter boxes appear at the same time

### What is expected?

When you click on the second filter box, the first filter box closes

### What is actually happening?

Click the two filter buttons of the table respectively, and two filter boxes appear at the same time

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 16.12.0 |
| System | macos 13.4.1  |
| Browser | chrome version 114.0.5735.198 (Official version) (arm64) |

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/43093
