### ISSUE TITLE
Production build failing on Vercel since last 24 hrs, though build is success in my local

### ISSUE THREAD

**Issue by de-shine** [ant-design/ant-design#43359]
### Reproduction link

[https://vercel.com/my-project/my-project-app/{build-id}](https://vercel.com/my-project/my-project-app/{build-id})

### Steps to reproduce

On Vercel, my next js project build has started failing suddenly since last 24 hrs with "yarn run build" cmd, however in my local the build is successful. 

Error log:
----------
...
......
Detected Next.js version: 13.4.8
Running "yarn run build"
yarn run v1.22.17
$ next build
- info Loaded env from /vercel/path0/.env.production
- info Loaded env from /vercel/path0/.env
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
- info Linting and checking validity of types...
- info Creating an optimized production build...
Failed to compile.
./components/AvatarBox.js
Module not found: Can't resolve 'antd/es/Avatar'

The component code I am using to import Avatar:
---------------------------------------------------------
import { Avatar } from 'antd';

const AvatarBox = ({ children, size, dataItem }) => {
    return (
        <div className='avatar-box-container'>
            <Avatar size={size} src={dataItem.profile_images[0].url} onClick={() => alert("HII")}/>
            {children}
        </div>
    )
}

export default AvatarBox

### What is expected?

Build should get successful as it used to happen before 24 hrs.

### What is actually happening?

Build is failing showing error for all the antd components with above error

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | Vercel (next js deployment) |
| Browser | All broswer |

**Comment by MadCcc** [comment]
It's bug of nextjs v13.4.8, and still not fixed: https://github.com/vercel/next.js/pull/52031

**Comment by de-shine** [comment]
Thanks.
