### ISSUE TITLE
[Segmented] - `selected` class not applying when disabling animations

### ISSUE THREAD

**Issue by theiliad** [ant-design/ant-design#43365]
### Reproduction link

[https://stackblitz.com/edit/react-yzatgn](https://stackblitz.com/edit/react-yzatgn)

### Steps to reproduce

1. Disable animations
```jsx
<ConfigProvider
    theme={{
      token: {
        motionDurationSlow: '0',
      },
    }}
  >
```

2. Highlight selected segment item
```css
label.ant-segmented-item.ant-segmented-item-selected {
  color: red;
}
```

3. Add a segment component, & try selecting some options
```jsx
<Segmented
      options={['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Yearly']}
    />
```

### What is expected?

The `ant-segmented-item-selected` classname should be attached to the selected element

<img width="393" alt="image" src="https://github.com/ant-design/ant-design/assets/14989804/de00a751-3223-4354-ab28-0c1ff930ca51">

### What is actually happening?

The `ant-segmented-item-selected` just disappears

<img width="393" alt="image" src="https://github.com/ant-design/ant-design/assets/14989804/84289f87-fd00-416e-ae18-d902a3ca1265">

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18 |
| System | Mac latest |
| Browser | Chrome latest |

**Comment by linxianxi** [comment]
there's something wrong with the animation, but you can try `token={ motion: false }`
