### ISSUE TITLE
Controlled open state for date range picker fails to select a date range

### ISSUE THREAD

**Issue by HassanAzzam** [ant-design/ant-design#43364]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hfdn52?file=/index.js)

### Steps to reproduce

1- Click on 'Open picker' button.
2- Select a start date.

### What is expected?

To be able to select the end date for the range.

### What is actually happening?

The picker gets closed without select an end date.

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.14 |
| System | MacOS |
| Browser | Safari, Chrome |

**Comment by RedJue** [comment]
You need set your own values in controlled mode https://codesandbox.io/s/antd-reproduction-template-forked-l6ww3h?file=/index.js

**Comment by HassanAzzam** [comment]
@RedJue How does this help? Your fork still close after selecting the start date.

**Comment by RedJue** [comment]
Can you record a screen?

**Comment by HassanAzzam** [comment]
I can't select end date, the calendar closes after selecting the start date.

https://github.com/ant-design/ant-design/assets/9885144/d81096ff-4ca7-4158-bb45-ef6eb3d18f58

**Comment by RedJue** [comment]
Sorry for misunderstanding the meaning, I modified the logic to see if it meets your needs.
https://codesandbox.io/s/antd-reproduction-template-forked-l6ww3h?file=/index.js

**Comment by HassanAzzam** [comment]
No problem at all.

> https://codesandbox.io/s/antd-reproduction-template-forked-l6ww3h?file=/index.js

That's a good progress. It now keeps the calendar popped up but still doesn't select end date. 
I think the date picker component itself doesn't allow range selection when controlled.

**Comment by HassanAzzam** [comment]
I think the rc-picker closes the calendar for picking the start date then opens a new one for picking the end date. Not sure, yet.

**Comment by RedJue** [comment]
For design reasons, the components of the input type need to be focused. If you can force the focus of the date selector input box, it should meet the requirements.

**Comment by HassanAzzam** [comment]
Just found this #27263, hoping to be related.

**Comment by HassanAzzam** [comment]
I've tested the same reproduction code on [v5.4.7](https://github.com/ant-design/ant-design/tree/5.4.7) and it works just fine, misbehavior starts from [v5.5.0](https://github.com/ant-design/ant-design/tree/5.5.0).

**Comment by HassanAzzam** [comment]
Managed to workaround this by focusing the the picker ref and triggering click action on it.
https://codesandbox.io/s/antd-reproduction-template-forked-wjpqf5?file=/index.js

**Comment by HassanAzzam** [comment]
Fixed in #44105
