### ISSUE TITLE
【ConfigProvider】theme-token-borderRadius配置全局圆角后，tootip等气泡的尖角箭头样式错误

### ISSUE THREAD

**Issue by SYJ0414** [ant-design/ant-design#43369]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-y6dymw?file=/index.js)

### Steps to reproduce

configProvider: {
      theme: {
        token: {
          borderRadius: '2px',
        },
      }
    },配置之后，全局圆角会被改为2px，但是tooltip等悬浮框的三角箭头会变成方块

### What is expected?

tooltip等悬浮框的三角箭头不受影响

### What is actually happening?

tooltip等悬浮框的三角箭头会变成方块

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.1.0 |
| System | macOS 12.5.1 |
| Browser | chrome 114.0.5735.106（正式版本） (arm64) |

---
审查元素可以看出样式书写有误，猜测取到borderRadius后，未判断值有px的情况。

**Comment by SYJ0414** [comment]
注：borderRadius: 2,  如此书写可以规避此问题

**Comment by arvinxx** [comment]
'2px' 本来就不符合预期吧

**Comment by afc163** [comment]
最好用 TS，会有相应的提示。

<img width="601" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/03b708b2-c796-4548-aab0-0fa29ad63755">

**Comment by SYJ0414** [comment]
刚又看了下官网确实写了类型只支持number，可是'2px'对全局的圆角都生效，只有悬浮气泡箭头样式会错误，好容易误导js使用者= =
