### ISSUE TITLE
tabs标签页实现多项选择

### ISSUE THREAD

**Issue by kemisstep** [ant-design/ant-design#43379]
### What problem does this feature solve?

请问实现多选tabs标签页
现在做数据展示使用，用户可能会选择多个选项卡，需要实现选中效果图

### What does the proposed API look like?

暂无
![image](https://github.com/ant-design/ant-design/assets/117804089/ea1b15d8-a6c5-486e-bf69-fc4fa992093d)

**Comment by afc163** [comment]
这看上去就不是 Tabs 了，不应该用这个组件。

**Comment by afc163** [comment]
你可能需要 https://ant.design/components/tag-cn#components-tag-demo-checkable
