### ISSUE TITLE
Upload - Crop Image: The image has lost its transparent background

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#43376]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crop-image-before-uploading-antd-5-6-4-forked-cwlfwt)
![image](https://github.com/ant-design/ant-design/assets/105255382/fbce853b-39f2-4293-9491-5293447e8ec7)

### Steps to reproduce

 Access reproduction and use normal upload and upload crop

### What is expected?

 The image must remain in the format with a transparent background

### What is actually happening?

 The image loses its transparent background when using ImgCrop

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | Macbook Air M1 2020 - macOS 13.3.1 |
| Browser | Chrome 112.0.5615.137 |

**Comment by afc163** [comment]
You could report this issue to antd-img-crop.

**Comment by FlavioInacio-jf** [comment]
You can set the attribute fillColor='transparent'. It works for me.
