### ISSUE TITLE
components are too small on high dpi displays

### ISSUE THREAD

**Issue by PolarBean** [ant-design/ant-design#43389]
### What problem does this feature solve?

Does ant design use px to size components by default, it seems that components are too small on high dpi displays and too large on low dpi displays. 

### What does the proposed API look like?

Use rem instead of px internally for sizing components

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/43131#issuecomment-1599970377

https://ant.design/docs/react/compatible-style#css-logical-properties
