### ISSUE TITLE
select组件被overflow： hidden的时候，点击它会导致原来位置的select发生位置变化

### ISSUE THREAD

**Issue by bbb169** [ant-design/ant-design#43381]
### Reproduction link

https://codesandbox.io/s/ant-select-click-move-nxjqv9?file=/index.js

### Steps to reproduce

然后点击选择器

### What is expected?

原位置的select不会发生位置偏移

### What is actually happening?

原位置的select发生位置偏移

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 官网 |
| System | win11 |
| Browser | 谷歌浏览器 |

https://github.com/ant-design/ant-design/assets/102608263/dcb4a62e-dd6a-4c0a-81a6-47165b423b03

![image](https://github.com/ant-design/ant-design/assets/102608263/5daa3e91-7654-47fe-bc98-19bc73ecaa63)

**Comment by bbb169** [comment]
> ### Reproduction link
> https://ant.design/components/select-cn
> 
> ### Steps to reproduce
> 给 classname 为 code-box-demo的section 设置style：width: 10px; overflow: hidden;， 然后点击任意一个选择器
> 
> ### What is expected?
> 原位置的select不会发生位置偏移
> 
> ### What is actually happening?
> 原位置的select发生位置偏移
> 
> Environment	Info
> antd	5.6.4
> React	官网
> System	win11
> Browser	谷歌浏览器
>  1688552698687.mp4 
> ![image](https://user-images.githubusercontent.com/102608263/251122184-5daa3e91-7654-47fe-bc98-19bc73ecaa63.png)

视频看不了可以下载下来看一下

**Comment by bbb169** [comment]
视频看不了可以下载下来看一下

**Comment by afc163** [comment]
Chrome 浏览器确实有这个问题。

<img width="231" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/0d76b744-cb82-49b2-96d1-28cee4ed56c0">

**Comment by bbb169** [comment]
> https://ant.design/components/select-cn

另外测试了一下edge也会有此类问题

**Comment by bbb169** [comment]
> Chrome 浏览器确实有这个问题。
> 
> <img alt="图片" width="231" src="https://user-images.githubusercontent.com/507615/251138435-0d76b744-cb82-49b2-96d1-28cee4ed56c0.png">

另外测试了一下edge也会有此类问题

**Comment by zombieJ** [comment]
看起来是 Chrome 为了尽可让用户看到更多的输入框部分做的优化：
https://codesandbox.io/s/ant-select-click-move-forked-z62slm?file=/index.js

antd 侧如果去强制固定父元素的 scrollLeft 就太黑了。
