### ISSUE TITLE
Customizing collapse like show less and show more

### ISSUE THREAD

**Issue by vai995** [ant-design/ant-design#4338]
First of all I liked the styling and the way the code is modularized.

Is there any customization available for the default height to be set to the user given value..?? (When the user wants to close it). Like show less and show more components for collapse?

Also is there anyway to override the functions of the modules by extending them to customize/add the new params?

**Comment by benjycui** [comment]
> Is there any customization available for the default height to be set to the user given value..?? (When the user wants to close it). Like show less and show more components for collapse?

I don't understand you requirement.



> Also is there anyway to override the functions of the modules by extending them to customize/add the new params?

Try HOC.

**Comment by afc163** [comment]
It is ok to discuss only in English.

**Comment by vai995** [comment]
Thank you @afc163 . 

@benjycui 
Collapse functionality is: To open or close the node completely. 
My Requirement is: I want to show some part of the content and on click of the show more button it should expand to show the whole content. I want to customize collapse with some customized height, so that in hidden state, node will be visible till that height and when opened it should show the whole content of the node. 


For demo: Make the following changes and observe the behavior of collapse with more content inside the panel-content after 2 clicks. 

Go through the node module of rc-collapse => openAnimationFactory.js  and replace animate function with the following.

function animate(node, show, transitionName, done) {
  var height = void 0;
  return (0, _cssAnimation2["default"])(node, transitionName, {
    start: function start() {
      if (!show) {
        node.style.height = node.offsetHeight + 'px';
      } else {
        height = node.offsetHeight;
        node.style.height = 50 + "px";
      }
    },
    active: function active() {
      node.style.height = (show ? height : 50) + 'px';
    },
    end: function end() {
      node.style.height = '';
      done();
    }
  });
}

also in the less file of collapse module, replace the -inactive with the following.

    &-inactive {
      display: block;
    }

**Comment by benjycui** [comment]
Just like this? https://www.iviewui.com/components/layout#基础用法

![image](https://cloud.githubusercontent.com/assets/3580607/21445366/104be6aa-c8f3-11e6-8146-8cf9b388a43e.png)

**Comment by vai995** [comment]
Yes.....exactly. The same kind of behavior.

**Comment by vai995** [comment]
@benjycui  and @afc163  is it possible to implement?? I didn't get any update from 5 days.

**Comment by benjycui** [comment]
Our designer is working on this, sorry for late response.

**Comment by vai995** [comment]
That's fine. No need of apologies. But please make sure that is configurable ie., rather than placing an arrow icon give the user some permissions to place the text of his own requirement. 

@benjycui I've one more suggestion on "TAG". Could you please allow the user to customize the close button placement like below. Do I need to raise another issue for this or can you take care of this too?

![customtag](https://cloud.githubusercontent.com/assets/22187892/21538185/4740c74e-cdc0-11e6-99b4-534c08dda012.png)

**Comment by benjycui** [comment]
> I've one more suggestion on "TAG"

A new issue is better.

**Comment by afc163** [comment]
Won't do it.

**Comment by roboworski** [comment]
Hi guys,

Our team just encountered the same issue, we think the "show more, show less" behavior is quite common and we are honestly surprised that the outcome of this request is "won't do it".

We are working on a custom component and would be more than happy to share the result with you guys :)

**Comment by jaxxreal** [comment]
I've found out that https://dollarshaveclub.github.io/shave/ is a perfect solution for `See more/less` functionality. Hope this will be helpfull.
