### ISSUE TITLE
treeSelect 是否提供缓存能力

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#43383]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-x4lsnd?file=/index.js)

### Steps to reproduce

选择child2,之后点击只查看有权限的

### What is expected?

期望依然展示child2

### What is actually happening?

展示成了c2

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by zombieJ** [comment]
用 `labelInValue` 控制：
<img width="703" alt="截屏2023-07-05 19 04 55" src="https://github.com/ant-design/ant-design/assets/5378891/5151d0ce-6e74-4e06-a585-681e5d35de7f">
