### ISSUE TITLE
antd Form 如何实现最原始的表单提交，而不用ajax 做表单提交

### ISSUE THREAD

**Issue by alvin198761** [ant-design/ant-design#4339]
你好，我现在有一个表单，必须要是用html 原始的提交方式，因为我以前都是使用ajax 的，没有在意，刚刚在api 中找了一圈，发现没有手动提交表单的方法，这个很简单的问题，困扰了我半天了。

**Comment by benjycui** [comment]
antd 中大量的自定义表单组件，这些组件的值只能用 JS 收集，所以如果用 `form` 标签，就只能用 Input Checkbox 之类简单的组件了。

**Comment by RaoHai** [comment]
也可以用 js 构造一个 form 然后提交。。

**Comment by alvin198761** [comment]
我用document.getElelmentById("loginForm").submit() 提交，实现了
最大的梗是 ，input的名称不是name来决定的，而是id ,
但是form 的名称，却可以用name 来设定。
这跟原始的form表单有些地方有点冲突
我需要修改 input 里面的值，加密，然后提交，发现改了input 里面的值后，提交并没有获取到值
后来使用 form.setFieldsValue 修改了只，提交才正常，但是form 在前端的值，仍然没有变。
问题解决了，只是发现这个地方有点。。。。

**Comment by benjycui** [comment]
看不懂你最后的 comment @alvin198761 

所以你是用了 AJAX 提交还是 `form[action]` 提交。

**Comment by TreeVie** [comment]
antd中怎么使用js触发Form的提交？
