### ISSUE TITLE
Form.List初次更新时FormInstance.getFieldsValue()无法获取initialValues的值

### ISSUE THREAD

**Issue by tomzhu1024** [ant-design/ant-design#43394]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ftcr3g)

### Steps to reproduce

运行链接中的应用

### What is expected?

`form.getFieldsValue()` 能够获得 initialValues 的值并显示 "data"

### What is actually happening?

`form.getFieldsValue()` 不能够获得 initialValues 的值，`form.getFieldsValue()['arr']` 是 `undefined`

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | macOS Ventura 13.4.1 |
| Browser | Chrome 114.0.5735.198 (arm64) |

**Comment by Yuiai01** [comment]
貌似 `getFieldsValue()` 没有获取到 `[arr]` 字段值，可以先使用 `getFieldsValue(true)` ，就像这样： https://codesandbox.io/s/antd-reproduction-template-forked-nvhzs6?file=/index.js

**Comment by zombieJ** [comment]
继 @Yuiai01 的回复，`getFieldsValue` 默认返回的是注册字段的值。你在 `render` 阶段调用 `getFieldsValue` 它尚未收集的状态。感觉 FAQ 可以加一下。

**Comment by yoyo837** [comment]
因为 render 里会有取值做条件渲染, 特别是hook组件.

**Comment by zombieJ** [comment]
> 因为 render 里会有取值做条件渲染, 特别是hook组件.

这个可以用 `shouldUpdate` 或者 `useWatch` 来实现，Form 是尽可能默认避免全量渲染的，否则大表单一次就够呛。
