### ISSUE TITLE
Table组件 columns 属性 align 类型在编辑器中推导错误

### ISSUE THREAD

**Issue by Kerryta** [ant-design/ant-design#43399]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jh5m7v)

### Steps to reproduce

1. 如重现链接引入，并配置 align 属性 
2. 在 vscode 中 align属性会推导为string 并与 AlignType 不兼容
3.
![image](https://github.com/ant-design/ant-design/assets/78243391/e4316e6f-2ef0-44ea-8d9c-869040d26ad7)

### What is expected?

修复typescript类型冲突问题 不需要我进行 as const

### What is actually happening?

我每次使用align属性都需要进行as const

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | typescript：4.9.3 |
| Browser | 114.0.5735.199 |

### What is expected?

修复typescript类型冲突问题 不需要我进行 as const

### What is actually happening?

我每次使用align属性都需要进行as const

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | typescript：4.9.3 |
| Browser | 114.0.5735.199 |

**Comment by linxianxi** [comment]
为 columns 指定类型即可
