### ISSUE TITLE
在执行“npm install antd”之后，缺少部分组件

### ISSUE THREAD

**Issue by zhujm3617** [ant-design/ant-design#434]
在执行“npm install antd”之后，缺少部分组件

**Comment by kevyu** [comment]
有些组件（比如Button，Icon）还没有release吧。

**Comment by benjycui** [comment]
`Button` `Icon` 是集成在 antd 中的。

@zhujm3617 你安装的 antd 是什么版本的？

**Comment by zhujm3617** [comment]
antd.version = '0.9.1'

**Comment by kevyu** [comment]
@benjycui 现在通过npm安装的版本还没有Button和Icon吧。

**Comment by afc163** [comment]
`npm install antd` ==> 0.9.x http://09x.ant.design

`npm install antd@beta` ==> 0.10.x http://ant.design

**Comment by afc163** [comment]
http://ant.design/docs/download

**Comment by afc163** [comment]
#428 

#276

**Comment by GrayLiu** [comment]
@afc163  npm install antd 安装之后 插件缺失，求解决办法～

**Comment by afc163** [comment]
我擦你不看上面的回复的？！
