### ISSUE TITLE
使用table组件报 the checksum was invalid错误

### ISSUE THREAD

**Issue by forrest23** [ant-design/ant-design#4340]
#### 发生问题的环境是：

- antd 版本:2.5.2
- 操作系统及其版本:Mac 10.11.6
- 浏览器及其版本: chrome

用的https://github.com/kriasoft/react-starter-kit 这个脚手架，然后引入了antd，
在使用table时报错：

Mention.js:44Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client)  data-reactid="33"></colgroup><thead cla
 (server)  data-reactid="33"><col data-reactid="34

页面代码
 <Table dataSource={this.props.products} rowKey="id" pagination={false}>
            <Column
              title="名称"
              dataIndex="title"
              key="title"
            />
            <Column
              title="售价"
              dataIndex="sale_price"
              key="sale_price"
            />
            <Column
              title="成本价"
              dataIndex="cost_price"
              key="cost_price"
            />
            <Column
              title="到期日期"
              dataIndex="expiry_date"
              key="expiry_date"
            />
          </Table>

**Comment by yesmeck** [comment]
提供下能重现的 repo 吧。

**Comment by forrest23** [comment]
@yesmeck 源码地址：https://github.com/forrest23/ReactShop.git

点右上角的产品菜单。进入报错的页面。

用npm start运行会报错，而且数据会不显示。如果用npm start -- --release 运行数据就可以正常显示。

还有问下，react-starter-kit这个脚手架按照babel-plugin-import的文档使用["import", [{ "libraryName": "antd", "style": "css" }]]引入antd编译会报错，究竟怎样引入才能正常？

**Comment by yesmeck** [comment]
@forrest23 没看到 checksum 的错误。

**Comment by yesmeck** [comment]
babel plugin 的配置在这里 https://github.com/forrest23/ReactShop/blob/master/tools/webpack.config.js#L63-L76

**Comment by afc163** [comment]
@forrest23 有什么要补充的么

**Comment by yesmeck** [comment]
这么久不回复先关闭了，有问题再打开。
