### ISSUE TITLE
Input Numbers in Cols do not scale correctly

### ISSUE THREAD

**Issue by JanFuhrmann** [ant-design/ant-design#43406]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4fq22j)

### Steps to reproduce

Create an InputNumber within a Col and set the span to a small value (<4) or a very large value (e.g. 20)

### What is expected?

The InputNumber is correctly placed within the area defined with span and fills the whole defined area (same behavior as Inputs)

### What is actually happening?

The InputNumber overlaps the area and maybe overlaps other components within the following Col.
In some cases the control buttons are hidden behind another component, if it is too small.
Within large Cols, InputNumber also have their default size.

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome Version 114.0.5735.199 |

---
style={{ width : "100%" }} solves this problem, but it is just a workaround and should be supported by Ant directly

**Comment by afc163** [comment]
InputNumber has default width (`90px`) by design, `style={{ width : "100%" }}` is the correct workaround.
