### ISSUE TITLE
在Dropdown打开Modal进行输入的时候，输入焦点无法通过键盘左右滑动

### ISSUE THREAD

**Issue by chuangwei** [ant-design/ant-design#43409]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-6-4-forked-g3n4k6?file=/demo.tsx)

### Steps to reproduce

在Dropdown打开Modal进行输入的时候，输入焦点无法通过键盘左右滑动

### What is expected?

在Dropdown打开Modal进行输入的时候，输入焦点无法通过键盘左右滑动

### What is actually happening?

在Dropdown打开Modal进行输入的时候，输入焦点无法通过键盘左右滑动

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
`stopPropagation` 阻止冒泡：
https://codesandbox.io/s/ji-ben-antd-5-6-4-forked-ny47zj?file=/demo.tsx:707-722

**Comment by Yojay97** [comment]
谢谢，解决了问题
