### ISSUE TITLE
Cascader组件搜索功能使用左右方向键 不能移动输入框中搜索文本的光标，按下左方向键会使搜索内容消失下拉框消失

### ISSUE THREAD

**Issue by meiqig** [ant-design/ant-design#43401]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/cascader-cn/#components-cascader-demo-search](https://4x-ant-design.antgroup.com/components/cascader-cn/#components-cascader-demo-search)

### Steps to reproduce

Cascader组件搜索功能 输入搜索文本 点击键盘左方向键 搜索内容消失 下拉框也消失啦

### What is expected?

点击键盘左右方向键 搜索内容文本移动光标可修改搜索内容文本 下拉框不消失 

### What is actually happening?

Cascader组件搜索功能 输入搜索文本 点击键盘左方向键 搜索内容消失 下拉框也消失啦

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.2.14 |
| System | MacBook Pro (13-inch, M1, 2020) |
| Browser | 谷歌 版本 114.0.5735.198（正式版本） (arm64) |

---
保险业务 急需解决 期望提供可以解决的时间点

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/cascader/releases/tag/v3.12.1 and https://github.com/react-component/cascader/releases/tag/v3.7.3 

在 antd 4.x 和 5.x 都修复了，移除 lock 文件重新安装 node_modules 构建即可修复。

**Comment by meiqig** [comment]
老师 重新安装后 还是4.24.12 没有新的版本那？

**Comment by afc163** [comment]
修复在依赖 rc-cascader@3.7.3 里。

**Comment by meiqig** [comment]
您修复后的antd npm包发布了嘛？4.x最新版本号是多少？

**Comment by afc163** [comment]
@meiqig https://codesandbox.io/s/sou-suo-antd-4-24-12-forked-d52jwf?file=/package.json:213-219

我实测是可以的，直接重新安装 antd 4.24.12 应该就行了。https://codesandbox.io/s/sou-suo-antd-4-24-12-forked-d52jwf?file=/demo.tsx

<img width="310" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/11f9b322-7e26-4e14-a2b0-8a9a4c8901ba">

如果你本地还不行，可以钉钉私聊我。

**Comment by meiqig** [comment]
重新安装 在构建下 OK啦 感谢老师

**Comment by wuanke** [comment]
我现在antd版本是5.2.3    rc-cascader版本是～3.8.0 但是还是会清空 是哪里出问题了呢

**Comment by yoyo837** [comment]
> 我现在antd版本是5.2.3 rc-cascader版本是～3.8.0 但是还是会清空 是哪里出问题了呢

请提供复现打开一个新的issue.
