### ISSUE TITLE
Mentions - it's not possible to use option label for search and showing selected option in text

### ISSUE THREAD

**Issue by clmz** [ant-design/ant-design#43419]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-6-4-forked-gs565s?file=/demo.tsx)

### Steps to reproduce

I've altered the basic example to have a more common usecase, where you use different values for "value" (usually a UUID or any other identifier) and a string for "label" for the visual representation.
Type the prefix "@" in the input field to trigger the dropdown and select one of the entries; also try to search one of the entries by the characters of the label.

### What is expected?

the label is shown in the text after the prefix @ and you can search for the label within the dropdown after hitting @

### What is actually happening?

the value is used within the text and within the search.

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 114.0.5735.199 |

---
Before someone closes this without any solution: it is obvious that these basic functionalities are missing and this is simply reconizable by the fact that the examples uses the same value for the value and for the label property. In practise you won't use the label also for the value since it is not an unique identifier and will cause trouble soon or later.
Someone can implement a workaround for the first issue, but not for the second. So please add this functionality to the Mentions component because without it's often useless.

**Comment by MadCcc** [comment]
API of Mentions is designed based on Select and other similar components in antd, so it is okay that each item should have a `value` prop.
I totally agree with you that options displayed should be related with input. But since type of `label` is `ReactNode`, it would be hard to find related options. And that's why `value` exists.
