### ISSUE TITLE
RangePicker 设置了 defaultPickerValue，选择更早的日期时面板不应该跳转

### ISSUE THREAD

**Issue by OXXD** [ant-design/ant-design#43411]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-6-4-forked-v4qszv?file=/demo.tsx)

### Steps to reproduce

开始时间选择过去几个月的时间
![gif](https://i.imgur.com/8HjwVcU.gif)

### What is expected?

选择过去几个月的时间后，面板不会跳转。
效果如 Element-Plus 
[https://element-plus.org/zh-CN/component/date-picker.html#%E9%BB%98%E8%AE%A4%E5%80%BC](https://element-plus.org/zh-CN/component/date-picker.html#%E9%BB%98%E8%AE%A4%E5%80%BC)
![gif](https://i.imgur.com/QTLlagI.gif)

### What is actually happening?

选择过去几个月的时间后，面板会跳转到 defaultPickerValue 中定义的时间

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18 |
| System | win11 |
| Browser | Version 114.0.5735.199 (Official Build) (64-bit) |

**Comment by Wxh16144** [comment]
这里选择时间的体验确实有点糟糕 😰

**Comment by Wxh16144** [comment]
> 这里选择时间的体验确实有点糟糕 😰

看了一眼代码, 这里的逻辑应该设计如此, rc-picker:https://github.com/react-component/picker/blob/6663e2654c79a4018890504b087016f104c3c5e4/src/hooks/useRangeViewDates.ts#L84-L88

还得从 defaultPickerValue 下手, 设置为`[dayjs(), void 0]` 也是正常的

**Comment by OXXD** [comment]
> > 这里选择时间的体验确实有点糟糕 😰
> 
> 看了一眼代码, 这里的逻辑应该设计如此, rc-picker:https://github.com/react-component/picker/blob/6663e2654c79a4018890504b087016f104c3c5e4/src/hooks/useRangeViewDates.ts#L84-L88
> 
> 还得从 defaultPickerValue 下手, 设置为`[dayjs(), void 0]` 也是正常的

这个开起来是个目前可行的 workaround

**Comment by Ellenyyyy** [comment]
遇到了同样的问题，这个跳到当前月就很不舒服

**Comment by Ellenyyyy** [comment]
使用了上述的回答设置defaultPickerValue = [dayjs(), void 0]，可以避免了当点击开始日期时，面板不会跳转到当前月份；但是不能避免我已经选择了开始日期与结束日期，此时我再点击开始日期，面板会跳转到结束日期的的那一个月以及下一个月，我认为这样的用户体验不是很好

**Comment by Eva-HYL** [comment]
请问这个问题解决了么

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
