### ISSUE TITLE
antd能否在iconfont官网提供antd自带图标库

### ISSUE THREAD

**Issue by zuiidea** [ant-design/ant-design#4341]
希望antd能在iconfont官网提供antd自带图标库，
这样新项目可以在使用自己的图标库，也可以选择性使用官方图标库的部分图标

如果在使用官网的图标，自己再新增图标库，可能图标名会与官网图标冲突，因为iconfont的Unicode是自增的，Unicode也非常容易冲突。

另外 [定制主题](https://ant.design/docs/react/customize-theme-cn) 设置@icon-url无效

**Comment by RaoHai** [comment]
ref 4046

**Comment by afc163** [comment]
@icon-url 的问题看这里：https://github.com/ant-design/ant-design/issues/4259

**Comment by afc163** [comment]
Unicode 代码冲突通过自定义 font-family 的名称就行，一般来说不会冲突，因为 antd 里面已经重命名为 `anticon`。

**Comment by afc163** [comment]
http://www.cnblogs.com/bldxh/p/6360064.html
