### ISSUE TITLE
Popover的content中有通过createRoot的render内容时会在意料之外消失

### ISSUE THREAD

**Issue by MorningK** [ant-design/ant-design#43417]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-6-4-forked-hrh6zk?file=/demo.tsx)

### Steps to reproduce

在content中使用createRoot并render内容
```
const ChartTooltip = () => {
  useEffect(() => {
    const root = createRoot(document.getElementById("tooltip"));
    root.render(
      <>
        <p>Content</p>
        <p>Content</p>
      </>
    );
  }, []);

  return <div id="tooltip"></div>;
};

const App: React.FC = () => (
  <Popover content={<ChartTooltip />} title="Title">
    <Button type="primary">Hover me</Button>
  </Popover>
);
```

### What is expected?

在鼠标移入render部分时能够保持popover的显示

### What is actually happening?

在鼠标移入render部分时popover消失了

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18 |
| System | MacOS |
| Browser | chrome 114 |

**Comment by zombieJ** [comment]
React 创建的不同实体其事件冒泡是各自执行的，所以当你移入另一个实体时就会触发 mouseLeave 事件，antd 侧做不了什么。
如果硬要这么做，可以受控 `open` 属性，自行实现一套移入移除的检测逻辑哈~
