### ISSUE TITLE
ant lib date-picker local问题

### ISSUE THREAD

**Issue by pandboy** [ant-design/ant-design#4342]
```
ERROR in ./~/antd/lib/date-picker/locale/zh_CN.js
Module not found: Error: Cannot resolve 'file' or 'directory' E:\20161222_51257\react\node_modules\moment\min\moment.min.js/locale/zh-cn
in E:\20161222_51257\react\node_modules\antd\lib\date-picker\locale
 @ ./~/antd/lib/date-picker/locale/zh_CN.js 23:0-30
webpack: bundle is now VALID.
```
试了下其他问题论坛其他人回答的还是这个问题，
最后把node_modules\antd\lib\date-picker\locale下的zh_CH.js里的require('moment/locale/zh-cn');注释掉才不报以上错误，不知道是不是这个的bug， 2.4.1没有这个问题。
#### 发生问题的环境是：

- antd 版本:2.5.2#
- 操作系统及其版本:win10
- 浏览器及其版本:chrome55
-"webpack": "1.13.2",
 -"webpack-dev-server": "1.14.1",

**Comment by yesmeck** [comment]
`E:\20161222_51257\react\node_modules\moment\min\moment.min.js/locale/zh-cn`

好像是 windows 下的路径间隔符问题。

**Comment by benjycui** [comment]
@pandboy 你是设置了 webpack resolve alias 了吧？

**Comment by pandboy** [comment]
@benjycui 恩 配置是这样的。 `
module.exports = {
    context: rootDir,
    resolve: {
        alias: aliases
    },
    module: {
        loaders: [{
            test: /\.jsx?$/, // A regexp to test the require path. accepts either js or jsx
            loaders: (argv.inline && argv.hot ?
                    ['react-hot', 'babel?compact=false&presets[]=es2015&presets[]=react&plugins[]=transform-object-rest-spread'] :
                    ['babel?compact=false&presets[]=es2015&presets[]=react&plugins[]=transform-object-rest-spread']
            ),
            exclude: [/node_modules/]
        }, {
            test: /\.less$/,
            exclude: [/node_modules/],
            loader: 'style!css!less!autoprefixer-loader?browsers=last 10 versions'
        }, {
            test: /\.css/,
            exclude: [/node_modules/],
            loader: 'style!css'
        }, {
            test: /(\.gif|\.png)/,
            exclude: [/node_modules/],
            loader: 'url?limit=10000'
        }],
        noParse: _.values(_.pick(aliases, scripts.noParse))
    },
    plugins: [
        new webpack.IgnorePlugin(/^\.\/lang$/, /moment$/),
       // new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /de|fr|hu/),
        new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js", Infinity)
    ]
};`

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by benjycui** [comment]
完全不在乎阅读 issue 的人的感受么。。

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/21445500/bc019df4-c8f4-11e6-8fdd-9f5898e4fad8.png)

值都不给我们看看。。

**Comment by pandboy** [comment]
@benjycui  值：![image](https://cloud.githubusercontent.com/assets/3054955/21445554/8071af08-c8f5-11e6-8c9e-b6e6b2175d24.png)

**Comment by benjycui** [comment]
webpack 配置问题，非组件问题。

关于 webpack 如何配置，请自行查阅文档。
