### ISSUE TITLE
Collapse.Panel设置header无效

### ISSUE THREAD

**Issue by zhangdy2027** [ant-design/ant-design#43426]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-l4zhcq?file=/index.js)

### Steps to reproduce

用items的写法给header赋值无效，使用4x版本的写法header是生效的

### What is expected?

Collapse.Panel设置header正常

### What is actually happening?

Collapse.Panel设置header不正常

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | mac 13.4.1 |
| Browser | chrome  114.0.5735.198 |

**Comment by Yuiai01** [comment]
items 写法使用 label 替代了 header，可见https://github.com/react-component/collapse/blob/27250ca5415faab16db412b9bff2c131bb4f32fc/src/interface.ts#L9C33-L9C33
