### ISSUE TITLE
Slider组件无法修改 Tooltip 样式

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#43427]
### Reproduction link

[https://ant.design/components/slider-cn#tooltip](https://ant.design/components/slider-cn#tooltip)

### Steps to reproduce

官网demo即可发现， 当字符短的时候无法居中， 而且无法自定义这个样式， 希望可以提供一个API可以自定义样式
![image](https://github.com/ant-design/ant-design/assets/67216143/d51d4f10-47aa-4e4f-aabd-3739a43960d2)

### What is expected?

提供修改样式 API

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 17 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by afc163** [comment]
可以默认改成居中样式。

**Comment by Ali-ovo** [comment]
> 可以默认改成居中样式。

感觉提供一个样式API是不是会更好， 假如想要白色的背景色就无法改了

**Comment by Jomorx** [comment]
> 可以默认改成居中风格。

好像tooltip也没有api能直接控制tooltip文字中的自动对齐

**Comment by afc163** [comment]
> 感觉提供一个样式API是不是会更好， 假如想要白色的背景色就无法改了

有 tooltip 属性，理论上能改 tooltip 所有设置。

**Comment by Jomorx** [comment]
> 可以默认改成居中样式。

我想尝试一下🥹

**Comment by afc163** [comment]
@Jomorx 欢迎 PR，看了一下实际上是 4.x 这段样式迁丢了，补上即可：https://github.com/ant-design/ant-design/blob/4.x-stable/components/slider/style/index.less#L207-L212

实际上我本地代码都写完了，既然愿意试试，不妨你来吧。

**Comment by 1587315093** [comment]
或者说是否可以把 Tooltip 的一些属性，多暴露些给 Slider 的 tootip

比如 overlayStyle 与 overlayInnerStyle

**Comment by Jomorx** [comment]
> @Jomorx 欢迎 PR，看了一下实际上是 4.x 这段样式迁丢了，补上即可：https://github.com/ant-design/ant-design/blob/4.x-stable/components/slider/style/index.less#L207-L212
> 
> 实际上我本地代码都写完了，既然愿意试试，不妨你来吧。

非常感谢！
