### ISSUE TITLE
希望可以实现一个支持group功能的table

### ISSUE THREAD

**Issue by libinglong** [ant-design/ant-design#43425]
### What problem does this feature solve?

通常情况下，即使不支持group也不影响使用。我发现，windows和mac上，关于文件列表的排序，均已支持group，有的时候会非常有用。
![image](https://github.com/ant-design/ant-design/assets/38123153/e3621d00-490c-4320-8fb2-4a77f8f30c49)

### What does the proposed API look like?

增加一个group的属性，可以通过切换group来切换分组的展示。

**Comment by afc163** [comment]
Duplicate of #15630
