### ISSUE TITLE
TreeSelect组件样式在 4.x 和 5.x的表现不一致

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#43428]
### Reproduction link

[https://ant.design/components/tree-select-cn](https://ant.design/components/tree-select-cn)

### Steps to reproduce

查看第二个demo即可发现

在 `4.x` 中选中的 `高亮是一整行`,  在 `5.x` 版本中 选中的 `高亮只有具体的文字部分`
![image](https://github.com/ant-design/ant-design/assets/67216143/89398c0d-e522-4771-b958-f699f9a23122)

![image](https://github.com/ant-design/ant-design/assets/67216143/920b6eb5-3a47-4422-b093-d7ac6cdbb32d)

看了代码中发现是样式覆盖的问题
![image](https://github.com/ant-design/ant-design/assets/67216143/5f1fc92c-f52f-4967-b19b-2357bf76d882)

### What is expected?

样式和之前的一致

### What is actually happening?

不一致

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 17 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by afc163** [comment]
bug

**Comment by Ali-ovo** [comment]
我来改吧
