### ISSUE TITLE
Some Input tokens not being merged with global tokens

### ISSUE THREAD

**Issue by markferreiro** [ant-design/ant-design#43435]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rj6szc?file=/index.js)

### Steps to reproduce

Modify colorPrimary color in the Input token.

### What is expected?

The Input specific token colorPrimary must overwrite the global token.

### What is actually happening?

The Input border color is not changing

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | macOS 12.2.1 |
| Browser | Chrome 100.0.4896.127 |

**Comment by zombieJ** [comment]
ComponentToken only replace `AliasToken` which no participate with algorithm calculation:

https://codesandbox.io/s/antd-reproduction-template-forked-xsq55t?file=/index.js
