### ISSUE TITLE
Input放入FormItem中时，给Input的value绑定数据不起作用

### ISSUE THREAD

**Issue by iHearty** [ant-design/ant-design#4343]
antd版本: 2.5.2

操作系统: Windows 10
浏览器: Chrome 最新版

问题描述：
当使用InputsWrapper 时，传入props deptOwnerName, 在Inputs中打印控制台时deptOwnerName是有值的，并且placeholder="点击选择上级部门2"这个Input都能正常显示deptOwnerName的值，但是在FormItem中的Input不能显示值。

出问题代码如下：
class Inputs extends Component {
   render() {
      const {getFieldDecorator} = this.props.form;
      const formItemLayout = {
         labelCol: {span: 6},
         wrapperCol: {span: 18},
      };

      let deptOwnerName = this.props.deptOwnerName;

      return (
         <Form>
            <div className="row-wrapper">
               <FormItem {...formItemLayout} label="上级部门">
                  {getFieldDecorator('上级部门', {
                     rules: [{required: true, message: '请选择上级部门!'}],
                  })(
                     <Input placeholder="点击选择上级部门"
                            value={deptOwnerName}
                     />
                  )}
               </FormItem>
               <Input placeholder="点击选择上级部门2"
                      value={deptOwnerName}
               />
            </div>
            <div className="row-wrapper">
               <FormItem {...formItemLayout} label="部门名称">
                  {getFieldDecorator('部门名称', {
                     rules: [{required: true, message: '请输入部门名称!'}],
                  })(
                     <Input placeholder="请输入部门名称"/>
                  )}
               </FormItem>
            </div>
         </Form>
      );
   }
}

Inputs.propTypes = {
   form: React.PropTypes.any,
   deptOwnerName: React.PropTypes.string
};

const InputsWrapper = Form.create()(Inputs);

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options)
