### ISSUE TITLE
请删除 多余的行 ant-table-measure-row

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#43437]
### Reproduction link

[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce

会导致基于 dom 做的行拖拽库产生错误的行为

### What is expected?
会导致基于 dom 做的行拖拽库产生错误的行为

### What is actually happening?

会导致基于 dom 做的行拖拽库产生错误的行为

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by Yuiai01** [comment]
> `ant-table-measure-row` 这一行是用来测量主体列宽度的，或许可以主动过滤一下？

https://github.com/react-component/table/blob/5fb8f12c268c62a175171a2b6f9a4b99f9805814/src/Body/index.tsx#L109

**Comment by qunbotop** [comment]
```
:global{
    tr.ant-table-measure-row{
      visibility: collapse;
    }
  }
```
