### ISSUE TITLE
Nest Description borderless inside a bordered creates UI bug

### ISSUE THREAD

**Issue by patrickxunuo** [ant-design/ant-design#43446]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/border-antd-5-6-4-forked-klsv8h?file=/demo.tsx)

### Steps to reproduce

1. create a bordered description <Descriptions bordered/>
2. in one of the <Descriptions.Item /> create another description but borderless <Descriptions bordered={false}  />

### What is expected?

expected the inner <Descriptions /> to be borderless

### What is actually happening?

introduced weird UI

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | latest |
| System | all |
| Browser | all |

**Comment by Yuiai01** [comment]
I think this is due to the nesting which resulted in the outer bordered style being applied to the inside. I'll try to fix it.

**Comment by Wxh16144** [comment]
Similar questions are #39183
