### ISSUE TITLE
前台页面无法获取到DatePicker的数据

### ISSUE THREAD

**Issue by rsborn99** [ant-design/ant-design#4344]
PC端：
我的问题，页面放置一个datePicker。 但是请求的时候没有请求的值。
我的代码如下：
import { Form, message, Input, Button, Icon, DatePicker, Table, Modal } from 'antd';
const  {RangePicker}  = DatePicker;

  const getFormInputItem = function (fieldName, label) {
      return (
        <div className={Style.formItem} >
          <FormItem
            {...formLayout}
            label={label}
          >
            {getFieldDecorator(fieldName)(<Input />)}
          </FormItem>
        </div>
      );
    };
    const getFormDateTime= function (fieldName, label) {
      return (
        <div className={Style.formItem} >
          <FormItem
            {...formLayout}
            label={label}
          >
            {getFieldDecorator(fieldName)(<RangePicker 
              showTime
              format="YYYY-MM-DD HH:mm:ss"
              placeholder={['开始时间', '结束时间']}/>)}
          </FormItem>
        </div>
      );
    };

return (
      <div className={Style.searchDivWrapper} >
              <div className={Style.detailSearchWrapper} style={{ display: 'block' }}>
                    <div className={Style.formItemsWrapper} >
                      {getFormInputItem('partnerId', 'AAAAA')}
                      {getFormInputItem('scenarioId', 'BBBBB')}
                      {getFormInputItem('status', 'CCCCCC')}
                      {getFormDateTime('executeTime', 'DDDDDD')}
                    </div>

                    <div className={Style.searchButtons} >
                      <Button type="primary" onClick={this.formFetch} >搜索</Button>
                      <Button onClick={this.resetForm} >重置</Button>
                    </div>
          </div>
      </div>
    );
  现在问题是，我在请求时候， 也就是点击搜索的时候，页面可以拿到partnerId   scenarioId   status，但是拿不到时间控件的值，也就是没有executeTime。  
请求参数显示如下：
pageNum:1
pageSize:20
partnerId:
scenarioId:
status:F
_input_charset:gbk

就是没有executeTime。。。

多谢大侠帮助

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by afc163** [comment]
没反馈就关了，有需要再 reopen 。
