### ISSUE TITLE
node js v19.8.1 安装pro cli失败

### ISSUE THREAD

**Issue by infra403** [ant-design/ant-design#43455]
### Reproduction link

[https://pro.ant.design/zh-CN/docs/getting-started/](https://pro.ant.design/zh-CN/docs/getting-started/)

### Steps to reproduce

sudo npm i @ant-design/pro-cli -g

### What is expected?

正常安装

### What is actually happening?

sudo npm i @ant-design/pro-cli -g
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-compilation-targets@^7.22.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by liyunhe6** [comment]
Windows 11 亲测安装通过。

npmmirror：https://npmmirror.com/package/%40babel%2Fhelper-compilation-targets
官方源：https://www.npmjs.com/package/@babel/helper-compilation-targets
目前都有 7.22.6 这个版本

如果使用的是其他的源，可以尝试去 sync。
