### ISSUE TITLE
Tooltip acts weird on the disabled button inside the table row.

### ISSUE THREAD

**Issue by zj1926** [ant-design/ant-design#4346]
antd: "2.5.2",
windows 7 x64
chrome 55.0.2883.87

Hello. I am a big fan on antd!! but have a little problem recently.
I am trying to add tooltip around the buttons inside the table. In certain circumstance I need to have some buttons disabled. But tooltips keep showing even after the cursor moves away.
Also, even though i cannot replicate the error in the codepen demo, the tooltip location shifted a little bit. I record that in the screenshot. But this is not a big deal comparing to the previous one i guess.

Thanks

Demo: http://codepen.io/zj1926/pen/jVRvme?editors=001
screenshot: 
![image](https://cloud.githubusercontent.com/assets/5487482/21439904/5d4394b6-c85e-11e6-835b-5879554e6ef1.png)

**Comment by benjycui** [comment]
trace: https://github.com/react-component/tooltip/issues/18

**Comment by zj1926** [comment]
Thanks. That helps!
