### ISSUE TITLE
`placement` option passed to `notification` prop in `App` component does not work

### ISSUE THREAD

**Issue by Rajil1213** [ant-design/ant-design#43467]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-6-4-forked-69vn6n?file=/demo.tsx)

### Steps to reproduce

Create an App Component and pass a notification config to it via the notification prop. This config should have a placement set to "bottomLeft" (or any value other than "topRight"). The notification popup appears on the topRight.

### What is expected?

The notification popup should be displayed at a position corresponding to the placement value passed to the notification prop.

### What is actually happening?

The notification popup always appears at the topRight.

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 (react) |
| System | Mac OS Ventura 13.4.1 |
| Browser | Brave iVersion 1.52.130 Chromium: 114.0.5735.198 (Official Build) (x86_64) |

**Comment by Rajil1213** [comment]
After encountering and digging around this issue, I discovered a possible cause. Looks like the issue is with the `Holder` component. This component receives the `NotificationConfig` as its props and destructures it. But when destructuring the config, the `placement` field is not taken into account.

The actual placement is rendered by setting `styles` with the `getStyles` function. This function receives `placement` as an argument but as far as I can tell, is never invoked with the value of the placement.

A simple solution would be to destructure the `placement` field and then, change `getStyles` to close over the `placement` field instead of passing it as an argument.

[Link to Relevant code](https://github.com/ant-design/ant-design/blob/master/components/notification/useNotification.tsx#L32-L48)

Possible fix:
```tsx
const Holder = React.forwardRef<HolderRef, HolderProps>((props, ref) => {
  const {
    top,
    bottom,
    prefixCls: staticPrefixCls,
    getContainer: staticGetContainer,
    maxCount,
    rtl,
    placement, /* destructure this out */
    onAllRemoved,
  } = props;
  const { getPrefixCls, getPopupContainer } = React.useContext(ConfigContext);

  const prefixCls = staticPrefixCls || getPrefixCls('notification');

  // =============================== Style ===============================
  const getStyle = () => /* don't use `placement` as an argument */
    getPlacementStyle(placement, top ?? DEFAULT_OFFSET, bottom ?? DEFAULT_OFFSET);
```
Should I create a PR?

**Comment by afc163** [comment]
PR is welcome~

**Comment by amareshvarma** [comment]
I would like to contribute to this issue

**Comment by Rajil1213** [comment]
The pull request has been created. The issue was a bit more involved than what I initially mentioned in the above comment. Nonetheless, I have included additional tests that are now passing. 😄
