### ISSUE TITLE
antd5版本的主题怎么修改 如果用ConfigProvider theme的方式更改的话 请官方给个tokens的全部变量。

### ISSUE THREAD

**Issue by xc741852963** [ant-design/ant-design#43460]
### Reproduction link

[https://github.com/xc741852963/emergency-ts.git](https://github.com/xc741852963/emergency-ts.git)

### Steps to reproduce

1.在login 引入组件 写入toen

### What is expected?

解决问题

### What is actually happening?

实现主题自定义

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18 |
| System | 1.0.0 |
| Browser | 88 |

**Comment by MadCcc** [comment]
http://localhost:8001/docs/react/customize-theme-cn#api
