### ISSUE TITLE
使用onFieldsChange管理Form时，将FormItem的trigger设置为blur，不会触发onFieldsChange

### ISSUE THREAD

**Issue by CodeFly16** [ant-design/ant-design#43462]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-biao-dan-kong-jian-antd-5-6-4-forked-dyt3wc?file=/demo.tsx)

### Steps to reproduce

1. 为inputNumber输入任何值
2. 移除inputNumber焦点，inputNumber恢复为initialValue

### What is expected?

期望能够触发onFieldsChange，控制台打印onFieldsChange中的log，并且值不会恢复为initialValue

### What is actually happening?

实际上：未触发onFieldsChange，同时inputNumber value恢复为initialValue

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 16.14.0 |
| System | mac os monterey 12.2.1 |
| Browser | 114.0.5735.198 |

**Comment by Jomorx** [comment]
可以试试trigger是以on+事件名首字母大写，可以试试onBlur

**Comment by CodeFly16** [comment]
> trigger是以on+事件名首字母大写，可以试试onBlur

解决了，多谢。😥

**Comment by CodeFly16** [comment]
> trigger是以on+事件名首字母大写，可以试试onBlur

这里我还发现一个问题，当我输入超出边界的值时，onBlur后仍会触发onFieldsValue，并且newFields为超出边界的值。inputNumber并不会自动恢复为min或者max

<img width="1782" alt="image" src="https://github.com/ant-design/ant-design/assets/61872730/04f0b8fc-13fc-4c0a-ab83-e2bdfee9b8ae">

**Comment by zombieJ** [comment]
InputNumber 不要使用 `blur` 作为 `trigger`，`trigger` 事件给的是 blur event。`onChange` 事件才会反回封装值。

配置 `blur` 后相当于你把 InputNumber 当 Input 用了。反之则自行封装一下，把 `onChange` 里的值在 `onBlur` 里扔出来。

**Comment by hfmvin** [comment]
使用input也有异常情况，使用onBlur作为trigger时，只有当input内没有值的时候可以输入

**Comment by hfmvin** [comment]
使用input也有异常情况，使用onBlur作为trigger时，只有当input内没有值的时候可以输入
