### ISSUE TITLE
Select component does not update when "defaultValue" changes.

### ISSUE THREAD

**Issue by pastelsky** [ant-design/ant-design#4347]
I'm using a select dropdown with a dynamic `defaultValue` prop. When the value supplied to `defaultValue` changes, but the rendered select dropdown still shows the previous defaultValue. My component is uncontrolled.

```jsx
<Select defaultValue={ data.default }>
  {
    data.options.map(option => (
      <Option value={ option }> { option } </Option>
     ))
   }
</Select>
  
```

Antd version 2.5.2

**Comment by afc163** [comment]
http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by pastelsky** [comment]
@afc163 Hey, why is this closed? Should'nt select update when defaultValue changes?

**Comment by yesmeck** [comment]
@pastelsky You should use `value`. Try learning controlled/uncontrolled component concept in React.

**Comment by pastelsky** [comment]
To anyone facing a similar issue, do read https://github.com/facebook/react/issues/4101 .
React dropdowns have this slightly confusing behaviour and the only way to force re-render without making it a controlled component is by introducing a "key= {defaultValue}"
