### ISSUE TITLE
menu token does not effect dropdown menu

### ISSUE THREAD

**Issue by IamFive** [ant-design/ant-design#43472]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cascading-menu-antd-5-6-4-forked-6lmh6p)

### Steps to reproduce

move mouse to menu-item, the bg is not updated to expect red set in theme token

### What is expected?

move mouse to menu-item, the bg is set to red which defined in theme token

### What is actually happening?

move mouse to menu-item, the bg is not updated to expect red set in theme token

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | ^18.2.0 |
| System | all |
| Browser | all |

**Comment by MadCcc** [comment]
Dropdown respect token of itself. The style of Dropdown and Menu is sepatared.

**Comment by IamFive** [comment]
> Dropdown respect token of itself. The style of Dropdown and Menu is sepatared.

which token i should use to change menu-item hover/active bg color? I did not find the token related to that, may you kindly give me a prompt.

**Comment by diregraph** [comment]
I am having the same issue.

**Comment by diregraph** [comment]
I got it to work as follows 

```
<ConfigProvider
        theme={{
          components: {
            Button: {
              colorPrimaryHover: ColorPalette.DarkGray,
              colorText: ColorPalette.LightGray,
            },
            Dropdown: {
              // Ref: https://github.com/ant-design/ant-design/blob/b888c2ad68836a738d3e482fc5c1a16e1fc2df18/components/dropdown/style/index.ts#L231C59
              colorText: ColorPalette.TextLightGray,
              // Text color when selected
              colorPrimary: ColorPalette.LightBlue,
              // Background color when selected & hovering (0D -> 5% in Hex color codes)
              controlItemBgHover: `${ColorPalette.LightBlue}0D`
            },
          },
        }}
      >
```
