### ISSUE TITLE
[Modal]: body width incorrect when customizing scrollbar width 

### ISSUE THREAD

**Issue by camcam2605** [ant-design/ant-design#43485]
### Reproduction link

[https://ant.design/components/modal](https://ant.design/components/modal)

### Steps to reproduce

**1. Open DevTools** 
**2. Add some css custom styles for scrollbar :**
```
::-webkit-scrollbar {
    width: 10px;
}

::-webkit-scrollbar-thumb {
    background-color: red;
}

::-webkit-scrollbar-track-piece {
    background-color: yellow;
}
```

**3. Open Basic Modal then close.**

### What is expected?

`width` of body should be calculating correct with `width` of custom scrollbar

### What is actually happening?

`width` property of body calculating incorrect, this leads to body resizing (not fixed) when modal opening or closing.

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | React 18.x |
| System | Windows 10 |
| Browser | Chrome 114.0.5735.199 |

---
It looks like ant design modal is calculating the default scrollbar width of browser.
Should we add `scrollLocker`: `number` prop to be able to custom by ourselves ?
Can I open a Pull Request to add this feature?

**Comment by zombieJ** [comment]
fixed https://codesandbox.io/s/antd-reproduction-template-forked-9h3f4p?file=/index.css

**Comment by yunsii** [comment]
> fixed [codesandbox.io/s/antd-reproduction-template-forked-9h3f4p?file=/index.css](https://codesandbox.io/s/antd-reproduction-template-forked-9h3f4p?file=/index.css)

最新的 v5 版本这个又不正常了……官网 modal 演示也不正常
