### ISSUE TITLE
[Tree] The node to be removed is shifted(twitches) for a while when removing this node.

### ISSUE THREAD

**Issue by MaximPravenkiy** [ant-design/ant-design#43493]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-twzkpn?file=/index.js)

### Steps to reproduce

1) Open link https://codesandbox.io/s/antd-reproduction-template-forked-twzkpn?file=/index.js
2) Open development tools
3) Search the DOM-tree for a node with class="ant-tree-list-holder-inner"
4) Right-click on the found node => Break on => subtree modifications
5) Try to click "Remove node" button
6) Script execution should stop on the breakpoint (react-dom.development.js:11099)
7) Look at the removable node: it is shifted

### What is expected?

It's expected that removable node won't twitch

### What is actually happening?

The removable node always twitches when removing

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | Windows 10 Pro, 64-bit Operating System |
| Browser | Google Chrome, version 114.0.5735.199, 64-bit |

---
In fact, if you don't set the breakpoint, this issue won't be noticed for such an example for some reason, but it's a really noticeable issue in our production

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-9kwnpq?file=/index.js

Seems remove node is still need keep intend:
<img width="151" alt="截屏2023-07-12 09 50 01" src="https://github.com/ant-design/ant-design/assets/5378891/5d27c385-4d88-472c-a9fc-760345a45dc7">

**Comment by zombieJ** [comment]
ref https://github.com/react-component/tree/pull/743

For prev fix, it use `useLayoutEffect` which will not show flick in view but when for a break point you will find this.
