### ISSUE TITLE
分页栏在低分辨率下的错位问题

### ISSUE THREAD

**Issue by Dio-Zhu** [ant-design/ant-design#4349]
![image](https://cloud.githubusercontent.com/assets/20452648/21448540/e645f3e2-c91e-11e6-9704-eedcc18bb25c.png)
![image](https://cloud.githubusercontent.com/assets/20452648/21448553/0d70390a-c91f-11e6-826f-c5b6fccfac3b.png)

在低分辨率下，分页数据很多时，分页按钮数过多，引起被挤压错位了，分页默认中间固定显示5个小按钮，这个能否支持可配置，比如 配置成中间只显示成 3个按钮。

**Comment by yesmeck** [comment]
用 `size="small"` 或者 `simple` 吧。

**Comment by Dio-Zhu** [comment]
这size的另两个我们考虑过了，用户都觉得不满意...
small 用户觉得太小了，点起来不方便
simple 用户体验太差，翻起来不方便



zzjbarry@126.com
 
发件人： Wei Zhu
发送时间： 2016-12-23 14:55
收件人： ant-design/ant-design
抄送： Dio-Zhu; Author
主题： Re: [ant-design/ant-design] 分页栏在低分辨率下的错位问题 (#4349)
用 size="small" 或者 simple 吧。

**Comment by afc163** [comment]
不如把 Modal 调宽一点，不只是分页的问题，我看上面的表格也挤得难受。

**Comment by afc163** [comment]
另外，看截图里这个应用的行业看着还蛮冷门的，方便分享的话，可以到 https://github.com/ant-design/ant-design/issues/477 去留个言。:smiley:

**Comment by Dio-Zhu** [comment]
这是我们在测试 最小支持分辨率 1024 X 768情况下 才出现此问题，Modal 宽度 默认用 屏幕80%比例设置的，目前没办法就只能调整比例到 90% 了。
    
  另外： modal 能否考虑支持  拖拽窗口位置 和 调整窗口尺寸  我们同时有两个弹出Modal时，叠到一起都不能拖拽特别不方便。



zzjbarry@126.com
 
发件人： 偏右
发送时间： 2016-12-23 15:06
收件人： ant-design/ant-design
抄送： Dio-Zhu; Author
主题： Re: [ant-design/ant-design] 分页栏在低分辨率下的错位问题 (#4349)
不如把 Modal 调宽一点，不只是分页的问题，我看上面的表格也挤得难受。

**Comment by afc163** [comment]
加了响应式的优化，屏幕分辨率小于等于 1024px 时，中间只保留 3 个页签。
