### ISSUE TITLE
Select 异步加载数据，页面初始化怎么把label写上去

### ISSUE THREAD

**Issue by onlyWuj** [ant-design/ant-design#4350]
现在开发了一个Select,在点击的时候才去加载数据。遇到一个问题，就是页面初始化后，我能获取这个select的之前选中的option的id和label。要怎么注入进入。
我采用的方法是。设置labelInValue 为ture。然后把defaultValue写成{key:'',label''}。这样就可以完成显示。
但是与rc-form的数据绑定格式也变成{key:'',label''}形式了。我又不想要这种，只想要一个id值。
然后尝试用rc-form的getValueFromEvent和getValueProps来调整。但一直处理不好。
请问要怎么做呢。

**Comment by yesmeck** [comment]
> 但是与rc-form的数据绑定格式也变成{key:'',label''}形式了

感觉只能这样。

**Comment by yesmeck** [comment]
可以先给 Select 塞一个临时 Option，等真正的数据返回时候把原来的 Option 替换掉。

http://codepen.io/yesmeck/pen/woZbLB?editors=0010

**Comment by benjycui** [comment]
`labelInValue` 就是为了处理这种动态 `Option` 的情况的，`onSubmit` 时统一处理就好。

**Comment by onlyWuj** [comment]
@benjycui onSubmit时统一处理太僵硬了，不能把逻辑分散到每个控件自身里去。总觉得不够优雅。
