### ISSUE TITLE
table 排序列缺失 aria-label 属性

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#43502]
### Reproduction link

[http://www.baidu.com/撒撒](http://www.baidu.com/撒撒)

### Steps to reproduce

 121

### What is expected?

21

### What is actually happening?

21

| Environment | Info |
| --- | --- |
| antd | undefined |
| React |  18 |
| System | mac |
| Browser | latest |

<img width="650" alt="image" src="https://github.com/ant-design/ant-design/assets/124666577/ddddbbb2-f5a0-4d38-b891-0a1a069ea81a">

**Comment by crazyair** [comment]
看情况， title 不是字符串没有`aria-label`

**Comment by vaynevayne** [comment]
> 看情况， title 不是字符串没有`aria-label`

有没有办法给 dom注入title 和 dataIndex 呢? 感觉用 `aria-label` 不是很安全? @crazyair

**Comment by zombieJ** [comment]
@vaynevayne  给个 Codesandbox 看看

**Comment by vaynevayne** [comment]
复现不了, 文档没写何时有 aria-label, 我是根据自己的项目截图的, 我都不知道何时有 aria-label
