### ISSUE TITLE
表单项类似select，datepicker等有下拉弹出框，能不能在该弹出框上鼠标滚动时，禁用外面层级的滚动

### ISSUE THREAD

**Issue by mgserss** [ant-design/ant-design#43506]
### What problem does this feature solve?

优化表单录入交互，在下拉框很长的情况下不会多层级都滚动

### What does the proposed API look like?

表单项类似select，datepicker等有下拉弹出框，能不能在该弹出框上鼠标滚动时，禁用外面层级的滚动

### Link
#8408   里面提到用onPopupScroll 禁用，怎么禁用，还有最好是全局实现

**Comment by linxianxi** [comment]
这不是浏览器的默认行为么？滚到顶了再往上滚或者滚到底了再往下滚，都会这样

**Comment by mgserss** [comment]
> 这不是浏览器的默认行为么？滚到顶了再往上滚或者滚到底了再往下滚，都会这样

很常见的场景，当select列表很长，用户快速下拉寻找目标选项，当下拉列表拉到底了，突然整个页面也被快速往下拉了，这样就得重新整个页面往上拉回去，这个交互细节确实会降低一定的效率。这里最好的交互就是鼠标在下拉框中时，下拉框拉到底时就止住了，外层不要再滚动。

**Comment by linxianxi** [comment]
不应该去更改浏览器默认行为，况且每个浏览器的滚动都会有一点差别，比如 firefox 就有不同

**Comment by mgserss** [comment]
> 不应该去更改浏览器默认行为，况且每个浏览器的滚动都会有一点差别，比如 firefox 就有不同

有没有办法可以实现类似这种，hack也行 https://element.eleme.cn/#/zh-CN/component/select，这里面有个拉下框滚动的就很好的被控制住了，antd我用onMouseEnter，onMouseLeave两个事件结合去控制window的滚动行为，但是并不完美，还是会偶尔滚动。

**Comment by linxianxi** [comment]
两种，自己选一种
https://codesandbox.io/s/biao-qian-antd-5-7-0-forked-kdf9lg

**Comment by lovewinders** [comment]
6

**Comment by mgserss** [comment]
> 两种，自己选一种。第二种应该要在卸载时移除监听，我就不写了 https://codesandbox.io/s/biao-qian-antd-5-7-0-forked-kdf9lg

好的，多谢，之前没看到dropdownRender是可以拿到拉下内容的dom，所以方向想错了

**Comment by MrZhouZh** [comment]
链接失效了, 辛苦贴一下新的不😿

**Comment by linxianxi** [comment]
> 链接失效了, 辛苦贴一下新的不😿
https://stackblitz.com/edit/react-wbuy8h?file=demo.tsx
<img width="611" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/f5f21e35-1bc1-494d-afab-321422f505a5">
