### ISSUE TITLE
destroyOnClose prop not working 

### ISSUE THREAD

**Issue by oeker55** [ant-design/ant-design#43516]
### Reproduction link

[https://github.com/oeker55/nolink-private-project.git](https://github.com/oeker55/nolink-private-project.git)

### Steps to reproduce

destroyOnclose prop working on nextjs12 but not working on nextjs13

### What is expected?

what I do to solve this problem?

### What is actually happening?

I updated my project from next 12 to next 13 my drawer component destroyonClose prop is not working.

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | React18.2.0 - NextJs13.4.9 |
| System | windows 10 |
| Browser | Google Chrome 114.0.5735.199 |

**Comment by zombieJ** [comment]
hi, seems your repo link is empty. Could you help to check this?

**Comment by oeker55** [comment]
I made the callback function async in the use effect that I used in the drawer. It was fixed when I deleted async and used then-catch
