### ISSUE TITLE
Next.js compatibility feedback collection

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#43510]
### Before All

If you meet the problem, please make sure:

1. Upgrade `antd` & `next` to latest version
2. For compile issue, please try `next` `canary` version. Some problem may be fixed but not released yet.

### What to leave message in this issue?

1. leave Codesandbox url or Github repo for **minimal reproduction**.
  a. minimal reproduction is very important to us for fast dig problem
3. Tell what reproduce step to do (e.g. `npm run build`)
4. Tell what behavior is wrong (e.g. Button style missing on the page. Please check `/xxx/xxx` page)

### 在开始前

如果你遇到任何问题，请优先：

1. 升级 `antd` 与 `next` 的版本。
2. 对于编译问题，可以尝试使用 `next` 的 `canary` 版本。一些编译问题已经解决但是尚未发布。

### 这个 issue 下我该做什么？

1. 留下 Codesandbox 或 Github repo 的 **最小重现** 地址
  a. 最小重现 非常重要，复杂的代码会难以找出问题所在
3. 告知重现步骤 (例如：执行 `npm run build`)
4. 告知非预期的表现 (例如：在 `/xxx/xxx` 页面中，Button 的样式丢失了)

**Comment by Veri5ied** [comment]
<img width="1188" alt="Screenshot 2023-07-19 at 12 38 33 PM" src="https://github.com/ant-design/ant-design/assets/43749581/a07afc26-bfc2-4b4c-b8e3-e0bb3583ce0e">
This is the issue I am encountering on next ts now using antd. Form throws this warning and I can't tell what is wrong for real

**Comment by sahaja56** [comment]
![ss](https://github.com/ant-design/ant-design/assets/120172137/a9177e93-97c5-4b33-8d95-5db1a8bedfee)

I face this issue currently on next ts using antd. This error only shown after saving changes (Fast Refresh). But if I hard reload the page, it become normal again. And this keeps happening as long as I save every changes which trigger next's fast refresh. I'm not sure what is wrong with this. This fast refresh just act normal when I'm not use antd, so i guess nothing is wrong with next ts.

**Comment by headironc** [comment]
@sahaja56 I also met this problem.  Have you solved this problem yet?

**Comment by headironc** [comment]
@sahaja56 I found this [solution](https://github.com/ant-design/cssinjs/issues/127#issuecomment-1644846113), it seems nice for this problem

**Comment by zombieJ** [comment]
> TypeError: Cannot read properties of null (reading '1')

Let me check this. Seem HMR destroy the cache instance but not rebuild it

**Comment by thisisandreww** [comment]
> @sahaja56 I found this [solution](https://github.com/ant-design/cssinjs/issues/127#issuecomment-1644846113), it seems nice for this problem

Thanks, your reference to the solution fixed the issue for me.

In case anyone is searching the same error message, the message is "Cannot read properties of null (reading '1')"

**Comment by mihir-karbelkar-wiz** [comment]
https://github.com/ant-design/ant-design-examples/blob/main/examples/with-nextjs-app-router-inline-style/src/app/with-sub-components/page.tsx

Any plans to move away from sub components?

Since most usecases will require layout and form (atleast for me), it would mean I have to make every page use client otherwise I get the below error.

`Error: Unsupported Server Component type: undefined`

The way I can go around this, is by passing components as props in a client component

```
"use client";

import { Layout } from "antd";
import React, { PropsWithChildren } from "react";

const { Header, Content } = Layout;

export default function SiteLayout({
  header,
  children: content,
}: PropsWithChildren<{
  header: React.ReactNode;
}>) {
  return (
    <Layout>
      <Header style={{ display: "flex", alignItems: "center", gap: "4" }}>
        {header}
      </Header>
      <Content>{content}</Content>
    </Layout>
  );
}
```

But this doesnt seem feasible for any layout or nested layouts across an entire application.

Would love any inputs on this.

**Comment by sahaja56** [comment]
@headironc @thisisandreww I tried to update to the latest antd version and it fixes the problem now.

**Comment by WankkoRee** [comment]
https://github.com/ant-design/ant-design/issues/43510#issuecomment-1684430445

----

Same problem with sub-components. Any progress or plans for Antd or Next.js now?

I don't know how to make server-side data fetch and sub-components work together. If I use sub-components, it must need to use client component, but after that I cannot fetch data at server-side any more.

----

在子组件上遇到了同样的问题。Antd或者Next.js在这方面有任何进展或者计划吗？

我不知道怎么在使用子组件的同时在服务端完成数据获取。如果我使用了子组件，就必须要将页面转为客户端组件，此时我无法再实现服务端的数据获取。

这违背了使用Next.js实现SSR的初衷，如果数据都需要在客户端获取，使用Next.js将没有任何意义。

**Comment by zombieJ** [comment]
@WankkoRee, 
You can mix client component with RSC. It's only required a component to be server component or client component. Not limit sub node must follow parent. For the component need interactive, use client. Instead use server.

你是可以混合使用 RSC 和 CC 的。它只是限制一个组件要么是客户端渲染要么是服务端渲染，并没有限制组件的子节点要去跟随父节点。对于需要前端交互的就 `use client`，反之 RSC 即可。

**Comment by AsuraKev** [comment]
Antd styles are overriding my tailwind css classes

**Comment by Skyriis** [comment]
> Antd styles are overriding my tailwind css classes

You can use `!<tailwind class>` to prevent that

**Comment by raaaaayn** [comment]
**next build fails**

next@13.5.4
antd@5.9.4

I am currently using the form component in one of my client rendered files by importing it like so:
```ts
import { Form } from "antd";
```

```
Collecting page data  .../home/hay/projects/japangrabtech/jobbox/node_modules/antd/es/form/Form.js:11
import classNames from 'classnames';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at mod.require (/home/hay/projects/japangrabtech/jobbox/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 8351 (/home/hay/projects/japangrabtech/jobbox/.next/server/pages/index.js:1:35256)

> Build error occurred
Error: Failed to collect page data for /
    at /home/hay/projects/japangrabtech/jobbox/node_modules/next/dist/build/utils.js:1178:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

This error occurs and build fails.

I have tried:
- using [next canary](https://vercel.com/blog/next-canary)
- using dynamic import  
 ```ts 
const PhoneNumberSubmit = dynamic(import("../PhoneNumberSubmit"), {
ssr: false,
}); // does not work
```
- removing "use client";

**Comment by raaaaayn** [comment]
> **next build fails**
> 
> next@13.5.4 antd@5.9.4
> 
> I am currently using the form component in one of my client rendered files by importing it like so:
> 
> ```ts
> import { Form } from "antd";
> ```
> 
> ```
> Collecting page data  .../home/hay/projects/japangrabtech/jobbox/node_modules/antd/es/form/Form.js:11
> import classNames from 'classnames';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at internalCompileFunction (node:internal/vm:74:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1141:20)
>     at Module._compile (node:internal/modules/cjs/loader:1182:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
>     at Module.load (node:internal/modules/cjs/loader:1081:32)
>     at Module._load (node:internal/modules/cjs/loader:922:12)
>     at Module.require (node:internal/modules/cjs/loader:1105:19)
>     at mod.require (/home/hay/projects/japangrabtech/jobbox/node_modules/next/dist/server/require-hook.js:64:28)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at 8351 (/home/hay/projects/japangrabtech/jobbox/.next/server/pages/index.js:1:35256)
> 
> > Build error occurred
> Error: Failed to collect page data for /
>     at /home/hay/projects/japangrabtech/jobbox/node_modules/next/dist/build/utils.js:1178:15
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   type: 'Error'
> }
> ```
> 
> This error occurs and build fails.
> 
> I have tried:
> 
>     * using [next canary](https://vercel.com/blog/next-canary)
> 
>     * using dynamic import
> 
> 
> ```ts
> const PhoneNumberSubmit = dynamic(import("../PhoneNumberSubmit"), {
> ssr: false,
> }); // does not work
> ```
> 
>     * removing "use client";

Nvm found the issue:

if you are using useForm and importing it like this:

```ts
import { useForm } from "antd/es/form/Form";


const [form] = useForm();

```

Do not, this is what causes it, use the useForm method of the Form component instead

```ts
const [form] = Form.useForm();
```

**Comment by zombieJ** [comment]
> Do not, this is what causes it, use the useForm method of the Form component instead

You should not import from the package path since Next do some magic for the path resolution to speed up build perf.

**Comment by infodusha** [comment]
Let me introduce two bugs that i've faced when using streaming:
https://github.com/ant-design/ant-design/issues/45955

**Comment by bombillazo** [comment]
We have tried using the "whole export" process to get styles in SSR, but it never worked correctly. The layouts would get all distorted. We are currently using inline styles as specified in the guides to get the styles to work.

However, this is not working all as expected either. We get this error when using the `ConfigProvider` in our app.

```
Warning: Prop `className` did not match. Server: "ant-layout-content css-dev-only-do-not-override-1g853jt" Client: "ant-layout-content css-dev-only-do-not-override-lzn4fh"
main
```

Also, the app does not get styled correctly in the first render; only once the context of the theme changes are the style changes applied.

Our current solution is using the `NoSSR` component to wrap the children of the ConfigProvider, effectively negating the use of SSR. This has been one of our biggest upsets about AntD when using it with Next.Js. 😞

**Comment by zcx992132258** [comment]
import React from 'react'
import { Inter } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import '@/assets/styles/index.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  )
}


我是使用了antd的最新版本按照官网的写法来 但是还是出现了页面刷新抖动的现象  我还有什么需要注意的地方去避免这个抖动的发生吗
![image](https://github.com/ant-design/ant-design/assets/54138798/6f39382e-f5ca-410e-b18c-042d4b5eab1a)

**Comment by annbeemsterboer** [comment]
i am encoutering the following error after upgrading next.js, antd and @ant-design/cssinjs

 ⨯ ./node_modules/antd/node_modules/classnames/index.js
Module parse failed: Cannot use 'import.meta' outside a module (93:16)
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or

Import trace for requested module:
./node_modules/antd/node_modules/classnames/index.js
./node_modules/antd/es/date-picker/generatePicker/generateRangePicker.js
./node_modules/antd/es/date-picker/generatePicker/index.js
./node_modules/antd/es/date-picker/index.js
__barrel_optimize__?names=DatePicker!=!./node_modules/antd/es/index.js

package.json
`"@ant-design/cssinjs": "1.18.4",`
`"antd": "5.14.1",`
`"next": "14.1.0",`

next.config.js includes
`  transpilePackages: [
    '@ant-design',
    'rc-pagination',
    'rc-picker',
    'rc-util',
    'antd',
  ],`

what is causing this and does anyone have a solution?

**Comment by mxilievski** [comment]
I'm trying to port my app to use the App Router, however the styles import order is wrong. 

Reproduction code: 
// layout.jsx
`export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body>
        <AntdRegistry>
            {children}
        </AntdRegistry>
        </body>
        </html>
    );
}
`

// page.jsx
`import styles from './button.module.scss';

export default function AuditLog() {
    return <Button className={styles.button} type="primary">Primary Button</Button>;
};`

// button.module.scss
`.button {
  background: red;
}`

The above code should make the button red, however `AntdRegistry` is appending the `<style>` tag at the end of `<head>` which is overriding the css code that I've provided in my component. 
<img width="704" alt="image" src="https://github.com/ant-design/ant-design/assets/2308950/a8f5798d-8599-44d6-aaa0-7dc52bfee24f">

Versions used: 
Antd **5.14.2**
NextJS **14.1.0**

**Comment by lapidus** [comment]
> i am encoutering the following error after upgrading next.js, antd and @ant-design/cssinjs
> 
> ⨯ ./node_modules/antd/node_modules/classnames/index.js Module parse failed: Cannot use 'import.meta' outside a module (93:16) | // still a Refresh Boundary later. | // @ts-ignore importMeta is replaced in the loader

Getting the same error. @annbeemsterboer did you find a fix? :)

**Comment by annbeemsterboer** [comment]
> > i am encoutering the following error after upgrading next.js, antd and @ant-design/cssinjs
> > ⨯ ./node_modules/antd/node_modules/classnames/index.js Module parse failed: Cannot use 'import.meta' outside a module (93:16) | // still a Refresh Boundary later. | // @ts-ignore importMeta is replaced in the loader
> 
> Getting the same error. @annbeemsterboer did you find a fix? :)

to be honest i dont really know what did the trick, i started again from scratch and then it worked.

i have the suspicion it had to do with the next config for `optimizePackageImports` and `transpilePackages`, which i had adjusted in my earlier attempt. 

for me it worked with this (partial) config:

// next.config.js
`experimental: {
    optimizePackageImports: ['lodash', '@ant-design', 'antd'],
  },
  transpilePackages: [
    '@ant-design',
    'antd',
    'rc-pagination',
    'rc-picker',
    'rc-util',
  ],`
  
i had to change imports for some of the types (i am using a [custom setup](https://ant.design/docs/react/use-custom-date-library#use-date-fns) with `date-fns` for the antd DatePicker. for example, in stead of importing from `antd/es/date-picker/generatePicker`, changed to `antd/es/date-picker/generatePicker/interface`.

not sure if any of this is helpful for you, this was for my setup :)

**Comment by lapidus** [comment]
> not sure if any of this is helpful for you, this was for my setup :)

Thank you for taking the time to share @annbeemsterboer. Much appreciated. I’ll try it out :)

**Comment by phantomtet** [comment]
Re-exported Ant Design components don't have same style with the original components in Nextjs project
https://github.com/ant-design/ant-design/issues/47802

**Comment by mohammadgharouni** [comment]
> > not sure if any of this is helpful for you, this was for my setup :)
> 
> Thank you for taking the time to share @annbeemsterboer. Much appreciated. I’ll try it out :)

did u fix it?

**Comment by Mr-ChaiPeng** [comment]
![image](https://github.com/ant-design/ant-design/assets/104434916/bc046fbc-8509-4add-842f-0a96a1a4b660)
这是谷歌高版本正常运行的，当遇到不支持antd5和不支持next14的，我想让其显示下面这种：
![image](https://github.com/ant-design/ant-design/assets/104434916/979e8630-cd5b-48e5-8d05-0b97dd3d802b)
，结果在谷歌低版本中显示的样式如下：
![image](https://github.com/ant-design/ant-design/assets/104434916/cef9588d-9797-4e84-9dcf-9d29a48a1167)
antd的样式和效果都没了，麻烦支个招，怎么判断浏览器是否支持antd5.x

**Comment by fnoopv** [comment]
> ![image](https://private-user-images.githubusercontent.com/104434916/337067669-bc046fbc-8509-4add-842f-0a96a1a4b660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDM4MDIsIm5iZiI6MTcxOTkwMzUwMiwicGF0aCI6Ii8xMDQ0MzQ5MTYvMzM3MDY3NjY5LWJjMDQ2ZmJjLTg1MDktNGFkZC04NDJmLTBhOTZhMWE0YjY2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNjU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTkwZjNlZWZlYWU5Y2NmNWVkNzgxYjQyZTEwZDFlMjc5ZWY3ZWNlOTA5YzZiZDA4Y2VjYjQwZGM5ZWQxNmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cZ6ZjWNyAe3ruWc7Cs5TKpo2TfMX0ozQNYEYuMeieI0) 这是谷歌高版本正常运行的，当遇到不支持antd5和不支持next14的，我想让其显示下面这种： ![image](https://private-user-images.githubusercontent.com/104434916/337068224-979e8630-cd5b-48e5-8d05-0b97dd3d802b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDM4MDIsIm5iZiI6MTcxOTkwMzUwMiwicGF0aCI6Ii8xMDQ0MzQ5MTYvMzM3MDY4MjI0LTk3OWU4NjMwLWNkNWItNDhlNS04ZDA1LTBiOTdkZDNkODAyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNjU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTE3ODMxYjIxZjcwY2MxNTE1YjI1YmM2ZTMyNzU1ZWQ1NzcxMTdkYjU0NDhiMzFhMDI5NDIzN2E5YTYyNThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XYvbPtrvrtfmORUeDS2waaVJMG6faU6elltDB3V1JVY) ，结果在谷歌低版本中显示的样式如下： ![image](https://private-user-images.githubusercontent.com/104434916/337068818-cef9588d-9797-4e84-9dcf-9d29a48a1167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDM4MDIsIm5iZiI6MTcxOTkwMzUwMiwicGF0aCI6Ii8xMDQ0MzQ5MTYvMzM3MDY4ODE4LWNlZjk1ODhkLTk3OTctNGU4NC05ZGNmLTlkMjlhNDhhMTE2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNjU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTkyZjYxNTJhMDkwOGExNzM2YzIxMjAyMzkwYmFmYWJmNTU3YTA4NTM1ODQ4ZDI0YjUwNjg2ZjIxZTM0YjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N0jpfpse5Gxo-sy_CfVhFoI8YvrWdGtSjJDkSINap8I) antd的样式和效果都没了，麻烦支个招，怎么判断浏览器是否支持antd5.x

`antd` 使用了 `where` 选择器，去`caniuse`查一下就知道浏览器要求了，然后判断一下版本就行

**Comment by chenguzhen87** [comment]
部分语言没有切换过来
![image](https://github.com/user-attachments/assets/89d9ace5-abae-4821-be72-215d2011be1c)
antd：5.20.0
next:14.2.5

**Comment by aurora-lch** [comment]
next 15
react 18.3.1
antd 5.21.5


<img width="954" alt="image" src="https://github.com/user-attachments/assets/8b80c422-a6b3-4f9e-95ac-da4b2b4c26c9">

[兼容 react 19 什么时候修复](https://github.com/ant-design/ant-design/issues/49267)

**Comment by prakashks20** [comment]
next 15 and next 14 latest versions(page and app router with jsx) 
antd 5.22.5
When we run `next dev` throws errors
![image](https://github.com/user-attachments/assets/da35600c-f0e4-41cc-950b-cdfe1d097547)

**Comment by zombieJ** [comment]
Since there is a plan to compatible with React 19 for latest nextjs. This issue will be closed. Pls follow:
- https://github.com/ant-design/ant-design/discussions/51919
- https://github.com/ant-design/ant-design/issues/52115
