### ISSUE TITLE
rangepicker 组件 当showTime为true的时候，设置第一个时间不可编辑，修改完第二个时间后，时间面板还是会滑动到第一个时间选择，这不合理

### ISSUE THREAD

**Issue by Hcy2ly** [ant-design/ant-design#43512]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jin-yong-antd-5-7-0-forked-68kqlv?file=/demo.tsx)

### Steps to reproduce

请打开这张图片： https://mail.qq.com/cgi-bin/viewfile?f=0C561DD1CA22518FB47699231877A55E41E1BD8EE50B5B99DA32E3023AE1BB8785686FE912EB6511729501BB659293D32A3C2D6C638820CC102AFEFCF8F1FE5A9420A24120D6250D689895787E2737E78BAE369BD5073672C6A810D698002B62&mailid=ZL1712-KQs21U8IniONB28LvVxRfd7&sid=AyGVTdeVHqMNTiZC&net=3767086110

### What is expected?

不可选择的时间不展示时间选择弹窗

### What is actually happening?

会展示

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.1.0 |
| System | macos ventura 13.4.1 |
| Browser | Google Chrome 114.0.5735.198 |

---
antd 目前测试好像 4.x ，5.x, 包括5.7.0, 都有这个问题

**Comment by wongest** [comment]
是之前rc-picker优化引入的bug，我提了修复的pr， 大佬帮忙看下 @MadCcc
 https://github.com/react-component/picker/pull/659

**Comment by Hcy2ly** [comment]
666 已经发版了嘛




至少有你在这陪着我hh_
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] rangepicker 组件 当showTime为true的时候，设置第一个时间不可编辑，修改完第二个时间后，时间面板还是会滑动到第一个时间选择，这不合理 (Issue #43512)





 
是之前rc-picker优化引入的bug，我提了修复的pr， 大佬帮忙看下 @MadCcc
 react-component/picker#659
