### ISSUE TITLE
Upload控件能否提供隐藏删除图标的属性以及鼠标停留在删除图标上的提示文字怎么设置

### ISSUE THREAD

**Issue by zlh314159** [ant-design/ant-design#4351]
#### 发生问题的环境是：

- antd 版本:最新版
- 操作系统及其版本:
- 浏览器及其版本:

#### 您期待的结果是:
1. 当处于查看状态时，我希望的是图片只能查看，不能删除；当处于编辑状态时，图片可查看也可删除，目前我的做法是覆盖样式隐藏了删除图标，希望有更好的做法。谢谢！

2. 当鼠标悬停在“删除”图标上时，默认有提示文字“Remove File”，我想修改这段提示文字，不知道应该怎么改？ 谢谢！
![Uploading QQ截图20161223171615.png…]()

**Comment by RaoHai** [comment]
图没传成功 :D 

以及，参考这个issue #4241

**Comment by Foosux** [comment]
预览模式下，只想显示预览icon，不需要删除icon，如何实现？

**Comment by xiahaichao11** [comment]
这个删除和下载按钮隐藏可以实现吗，怎么实现，谢谢

**Comment by IT-worm** [comment]
可以原生js获取delete图标，修改其title属性
