### ISSUE TITLE
Tag component: There is an extra space on the right of icon if empty children

### ISSUE THREAD

**Issue by skycrazyk** [ant-design/ant-design#43515]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/status-tag-antd-5-7-0-forked-m4xhfj?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

Use Tag with icon and without children

### What is expected?

Icon in the center of Tag component

### What is actually happening?

There is an extra space on the right of icon

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | react 18 |
| System | MacOS |
| Browser | Chrome |

![image](https://github.com/ant-design/ant-design/assets/7424691/25a8ec19-d87c-424f-8b51-be1ce608890a)

**Comment by Yuiai01** [comment]
A judgment here can solve this problem, let me propose a PR.
![image](https://github.com/ant-design/ant-design/assets/112228030/6c4d51ea-4c57-4541-9efd-9ecec5b3da0e)
