### ISSUE TITLE
ColorPicker组件取色器跟随鼠标指针无法取色

### ISSUE THREAD

**Issue by AdaWongAW** [ant-design/ant-design#43529]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ky7q76?file=/index.js)

### Steps to reproduce

1. 打开取色框
2. 在选色板上同时点击鼠标左右键，这时候浏览器右键菜单会打开（模拟误触）
3. 再点击回选色板，这时候取色器会跟随鼠标且无法取色

### What is expected?

正常取色

### What is actually happening?

无法取色，且关闭取色板后重新打开也无法取色

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18 |
| System | macOS Sonoma 14.0 Beta |
| Browser | Chrome 114.0.5735.198 |

**Comment by RedJue** [comment]
mark
