### ISSUE TITLE
Modal 和Dropdown组合更多操作功能，打开Modal后hover依然能打开Dropdown的下拉

### ISSUE THREAD

**Issue by lemonlhy** [ant-design/ant-design#43527]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-kt67gq?file=/demo.tsx)

### Steps to reproduce

1.hover打开新弹框
2.鼠标离开页面
3.重新移到当前页面

### What is expected?

menu的hover不会再被唤起

### What is actually happening?

menu的hover被唤起

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.0.0 |
| System | win10 |
| Browser | 谷歌 |

**Comment by lemonlhy** [comment]
![image](https://github.com/ant-design/ant-design/assets/24663035/9fe5f7e7-adef-4342-a34f-068efbe96c7f)

**Comment by lemonlhy** [comment]
怎么没有人，大佬能看看不，项目需要。

**Comment by zombieJ** [comment]
因为你的 Modal 在 Dropdown `items` 里，hover 到 Menu 也是会冒泡给 Dropdown 的。可以考虑拆出来哈~

**Comment by lemonlhy** [comment]
> 因为你的 Modal 在 Dropdown `items` 里，hover 到 Modal 也是会冒泡给 Dropdown 的。可以考虑拆出来哈~

之前就是把modal和button包一起封装的组件，这个在业务很常用，4不会出现这个问题，现在升5才会这样，不可能所有的业务都去改的，有没有什么其他能解决呢。

**Comment by zombieJ** [comment]
v4 里是因为实现方式不够 React，为了支持 Suspence 所以给底层做了改造变成完全跟着 React 生命周期走。这使得事件可以通过冒泡传上来。我想想能不能优化一下。

**Comment by phoema** [comment]
antd 5.3.2没有此问题，可以#43813对应再现的版本替换
