### ISSUE TITLE
Segmented的onChange类型有误

### ISSUE THREAD

**Issue by cw1997** [ant-design/ant-design#43523]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-wood-fr45lk?file=/src/App.tsx)

### Steps to reproduce

如codesandbox所示

### What is expected?

期待onChange属性可以接收 (value: string) => void 类型的函数

### What is actually happening?

报类型错误

![image](https://github.com/ant-design/ant-design/assets/11588555/a784764a-329d-46ec-a4fa-544e45a6e600)

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Windows 10 21H2 |
| Browser | Chrome Version 102.0.5005.115 (Official Build) (64-bit) |

**Comment by 1587315093** [comment]
应该是不兼容直接传 setState 函数的情况， (value: React.SetStateAction<"a" | "b" | "c">) => void

直接这样是可以的   `const handleChange = (a: "a" | "b" | "c") => {};`,就是setState 把形参类型加工了

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/22cc4d63-30de-43e9-b170-33f0308c58ef)
这样写是不能够推导出字面量类型的

**Comment by RedJue** [comment]
我优化一下吧

**Comment by RedJue** [comment]
https://github.com/react-component/segmented/pull/178

**Comment by RedJue** [comment]
#https://github.com/react-component/segmented/pull/178

**Comment by RedJue** [comment]
https://codesandbox.io/s/compassionate-jennings-l2y7v5?file=/src/App.tsx 设置一下入口类型就行

**Comment by zombieJ** [comment]
这个是 setState 定义不一致导致的，定义设一下就好了：
https://codesandbox.io/s/compassionate-jennings-l2y7v5?file=/src/App.tsx

**Comment by cw1997** [comment]
> 这个是 setState 定义不一致导致的，定义设一下就好了： [codesandbox.io/s/compassionate-jennings-l2y7v5?file=/src/App.tsx](https://codesandbox.io/s/compassionate-jennings-l2y7v5?file=/src/App.tsx)

手动给onChange的参数标注类型确实也是一个解决办法，但是我仍然认为给Segmented组件增加泛型支持是有必要的，毕竟antd的Table，Select等组件都有支持泛型，所以我认为应该要reopen这个PR https://github.com/react-component/segmented/pull/178
