### ISSUE TITLE
antd4.24.2版本Cascader组件同时开启showSearch和changeOnSelect，选择二级以上的值后进行检索，检索面板中出现多余的选项，问题在高版本已经解决，但是在官网的更新日志中没有查询到相关的修复描述

### ISSUE THREAD

**Issue by battleanam** [ant-design/ant-design#43532]
### Reproduction link

[https://codepen.io/battleanam/pen/gOQvbBV](https://codepen.io/battleanam/pen/gOQvbBV)

### Steps to reproduce

1. Cascader组件同时开启showSearch和changeOnSelect
2. 选择二级以上的值
3. 对选项进行检索，检索面板中出现多余的选项

### What is expected?

只展示搜索面板

### What is actually happening?

检索面板后包含了选中的选项

| Environment | Info |
| --- | --- |
| antd | 4.24.2 |
| React | 18 |
| System | macos |
| Browser | chrome100  |

---
问题在高版本已经解决，但是在官网的更新日志中没有查询到相关的修复描述

**Comment by MadCcc** [comment]
在 rc 组件修复的可能不会写在 antd 的 changelog 里。
如果高版本已经解决的话升级即可。

**Comment by battleanam** [comment]
> 在 rc 组件修复的可能不会写在 antd 的 changelog 里。 如果高版本已经解决的话升级即可。

get
