### ISSUE TITLE
First anchor should be selected by default in horizontal anchor

### ISSUE THREAD

**Issue by ZYSzys** [ant-design/ant-design#43537]
### Reproduction link

[https://ant.design/components/anchor#components-anchor-demo-horizontal](https://ant.design/components/anchor#components-anchor-demo-horizontal)

### Steps to reproduce

https://ant.design/components/anchor#components-anchor-demo-horizontal

### What is expected?

First anchor should be selected by default in horizontal anchor, or can be able to configure which anchor be selected by defalut.

### What is actually happening?

No anchor is selected by default in horizontal anchor

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18 |
| System | macOS 13.3 |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Not like Tabs, Anchor is active when referred content is in screen, which is same both horizontal and vertical.
Try to use `getCurrentAnchor` to make Anchor controlled.

**Comment by ZYSzys** [comment]
@MadCcc As you said 
> Anchor is active when referred content is in screen

Then see the demo, obviously `Part 1` is in screen, but `Part 1` anchor is not  active.
![image](https://github.com/ant-design/ant-design/assets/23313266/13ecc1c5-6f22-4a17-964a-68e22dfad996)

**Comment by ZYSzys** [comment]
@MadCcc Can you help to see this again?
