### ISSUE TITLE
Unexpected label height when setting `label = " "` on <Form.Item>

### ISSUE THREAD

**Issue by wving5** [ant-design/ant-design#43538]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-7-0-forked-3dymnp?file=/demo.tsx:527-557)

### Steps to reproduce

**前置条件: **
1. 设置 `<Form labelCol={{ span: 24 }} wrapperCol={{ span: 24 }}>`
2. 对 `<Form.Item>` 设置  `label= " "`

```
<Form labelCol={{ span: 24 }} wrapperCol={{ span: 24 }}>
    <Form.Item label=" ">
        <Input />
    </Form.Item>
</Form>
```

### What is expected?

Form.Item 生成的元素高度保持正常。（即，label 外层 div 高度不会因为设置 `label=" "` 而发生异常

### What is actually happening?

Form.Item 生成的 label 外层 div 高度发生了异常。

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | MacOS 11.7.7 |
| Browser | Chrome  114.0.5735.198 |

---
值得一提的是，设置 `label="&nbsp;"` 可以得到正常的渲染结果……

**Comment by MuxinFeng** [comment]
看起来像是 label 标签里没有子元素造成的，或许空字符串这种情况也要在这里过滤掉？
https://github.com/ant-design/ant-design/blob/master/components/form/FormItemLabel.tsx#L69
