### ISSUE TITLE
Flickering in Tabs 

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#43541]
### Reproduction link

https://stackblitz.com/edit/nextjs-nxw3bu?file=pages%2Findex.js

### Steps to reproduce

Set a breakpoint on the DOM tree modification

<br />

**animated={false}**:

<br />

<img width="1166" alt="Screenshot 2023-07-14 at 00 38 48" src="https://github.com/ant-design/ant-design/assets/803674/ae498b77-3363-40c5-8307-3f477ec1eecf">

<br />
<br />

**animated={true}**:

<br />

<img width="1203" alt="Screenshot 2023-07-14 at 00 29 22" src="https://github.com/ant-design/ant-design/assets/803674/324f21ba-b3a6-4edb-a2e6-1e8d064b7b7b">

### What is expected?

No flickering

### What is actually happening?

I set a breakpoint on the DOM tree modification and identified the reason why the component is flickering. The content for the clicked tab is being added below the previous one and is not being fixed. 
If I make the container a fixed height, the problem goes away, but this poses a risk as the interface will only work correctly at one resolution and within only one tab.

The problem is that the previous node is not being deleted/hiding before the next one appears:

<img width="976" alt="Screenshot 2023-07-14 at 01 06 10" src="https://github.com/ant-design/ant-design/assets/803674/84b7268c-2dca-4fdc-a02b-32cce7d9a76a">

<br />
<br />

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18 |
| System | macOS |
| Browser | Chrome, Safari |

---

**Comment by zombieJ** [comment]
Could you help provide an codesandbox or github repo instead?

**Comment by monolithed** [comment]
@zombieJ, https://stackblitz.com/edit/nextjs-nxw3bu?file=pages%2Findex.js

Set a breakpoint on the DOM tree modification:

<img width="1467" alt="Screenshot 2023-07-24 at 21 59 09" src="https://github.com/ant-design/ant-design/assets/803674/204dbf23-1fcd-4edf-b2b6-0c9d6fe0c128">

**Comment by monolithed** [comment]
It seems the incident with `animated={false}:` is gone, possibly after the version update.

**Comment by silviaphungky** [comment]
It's happened to me. I already add animated={false} but it still flickering

https://github.com/ant-design/ant-design/assets/55534481/bce93f9a-6cc9-4557-9f78-bdaef47361da

**Comment by monolithed** [comment]
@silviaphungky you absolutely right, I caught it again!

<img width="1424" alt="Screenshot 2023-08-01 at 17 26 54" src="https://github.com/ant-design/ant-design/assets/803674/7fe65832-6731-4c9c-8ac8-fc9606d27d48">

**Comment by Sanjeevani-octet** [comment]
.ant-tabs-nav .ant-tabs-nav-wrap .ant-tabs-nav-list {
display: flex;
justify-content: center;
}
 .ant-tabs-tab {
  display: flex;
  flex-basis: 49%;
  text-align: center !important;
  justify-content: center;
}

**Comment by zombieJ** [comment]
I test the reproduce but not get the stack case. Could you help to check the demo?

**Comment by siddhrajcrest** [comment]
I am also facing same issue in mac chrome, but not in safari, don't know what is wrong with it

**Comment by VacuusUmbra** [comment]
> I am also facing same issue in mac chrome, but not in safari, don't know what is wrong with it

Same

**Comment by 0xAl3xH** [comment]
We have seen this as well, does anyone know the cause/fix?

**Comment by Gittenger** [comment]
> I was also getting this issue as it was so annoying and just applied this below CSS.
> 
> .ant-tabs-nav-operations { display: none !important; }

You're a god bro I've been dealing with this thing for months and this fixes it

**Comment by aleksandartrkulja** [comment]
Side effect for us was 'ResizeObserver loop completed with undelivered notifications' showing  along with flickering and this fixed both.

> I was also getting this issue as it was so annoying and just applied this below CSS.
> 
> .ant-tabs-nav-operations { display: none !important; }

**Comment by prathmesh0125** [comment]
> I was also getting this issue as it was so annoying and just applied this below CSS.
> 
> .ant-tabs-nav-operations { display: none !important; }

thank you bro

**Comment by stylder** [comment]
+1

**Comment by AlejandroRM-DEV** [comment]
+1 Only when zoom is applied

**Comment by SpringsTea** [comment]
I encountered this issue today on 5.3.1 in **firefox only**. Hiding the .ant-tabs-nav-operation class fixes it, but I have to wonder what's actually going wrong here.

I noticed that shrinking the page width to a certain amount stopped the flickering. I could even go back to fullsize and the flickering would not return (until I refresh the page of course).

**Comment by spogulis** [comment]
Hiding the tab operations is not a solution because this prevents user on a small screen to open other available tabs!

**Comment by chaudev** [comment]
🚫 Here is a solution but it is very bad:

```
.ant-tabs-nav-operations {
   display: none !important;
}
```

✅ After careful research, I found that I just need to edit the width attribute of the parent element:

```
.primary-tabs {
   width: inherit;
   // more code...
}
```

```
<div className="primary-tabs select-none">
   <Tabs {...props} />
</div>
```

Relax and like this comment 🍻🍻
