### ISSUE TITLE
Tooltip 组件处于浏览器边缘时是否支持自定义间距？

### ISSUE THREAD

**Issue by Clover-You** [ant-design/ant-design#43546]
### What problem does this feature solve?

假设 Tooltip 组件在浏览器窗口最右边弹出，组件的右边框会和浏览器窗口边框粘在一起，看着有些奇怪。添加一个 offset prop 是否会好一些？
<img width="518" alt="截屏2023-07-14 10 16 42" src="https://github.com/ant-design/ant-design/assets/50982977/2f918ef6-0545-449f-b926-7f468b2d529a">

### What does the proposed API look like?

添加一个offset prop 允许修改组件渲染位置，例如offset=10,那么向右移动 10 px，offset=-10则向左移动 10px。如果组件渲染在浏览器左边边缘，那么 -10 则向右移动，反之向左。
```tsx
<Popover offset={10}>xxx</<Popover>
```

**Comment by fnlearner** [comment]
试试
```
  <Popover
        align={{
          offset: [x, y],
        }}
      >
      {children}
      </Popover>
```

**Comment by Clover-You** [comment]
@fnlearner 好了谢谢大佬，不过有个奇怪的问题，向左移动时x方向要设置小于 -80 才会生效
```tsx
<Popover
  align={{
    offset: [-97, -15],
  }}
> 
xxx
</Popover>
```

**Comment by zombieJ** [comment]
Offset 和对齐有一套算法，具体可以看看实现代码哈~
https://github.com/react-component/trigger
