### ISSUE TITLE
Expandable Row Rendering Issue When Using Custom Expand Icons

### ISSUE THREAD

**Issue by esu-skoopin** [ant-design/ant-design#43543]
### Reproduction link

[https://codepen.io/meelybug123/pen/yLQvXEd](https://codepen.io/meelybug123/pen/yLQvXEd)

### Steps to reproduce

1. Generate some data that has children
2. Write a function to delete the children property for data objects that have an empty children array (this is so the expand icon won't appear next to childless records. For details, refer to [this comment](https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941))
3. Call your function to clean your raw data and enter it in as the dataSource in your table. Make the rows in your table expandable by adding the expandable property to `<Table>`.
```
const data = cleanChildren(rawData);

return (
    <Table 
        columns={columns} 
        dataSource={data}
        expandable={{
          childrenColumnName: 'employees'
        }}
    />
);
```
4. See the difference that it makes in the app when you import your own expand icons and use them in your code

For a shortcut, please refer to this code that doesn't use custom expand icons (<https://codepen.io/meelybug123/pen/yLQvXEd>) and this code that uses custom expand icons (<https://codepen.io/meelybug123/pen/YzReQbY>)

Preview of code that doesn't use custom expand icons:
<img width="520" alt="Screen Shot 2023-07-13 at 1 16 21 PM" src="https://i.imgur.com/G6e7ddh.png">

Preview of code that uses custom expand icons:
<img width="520" alt="Screen Shot 2023-07-13 at 1 16 21 PM" src="https://i.imgur.com/jYfkVmZ.png">

### What is expected?

Expand icon should only show where appropriate for data that is cleaned of empty children arrays

### What is actually happening?

Expand icon is showing for every record even when the data is cleaned when using custom expand icons

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 17.0.2 |
| System | Mac OS Monterey Version 12.5 |
| Browser | 114.0.5735.133 |

**Comment by linxianxi** [comment]
This may be a bug, but you can check whether the icon is displayed or not by record.employees.
```
expandIcon: ({record}) => record.employees ? ... :null;
```

**Comment by esu-skoopin** [comment]
> This may not be a bug, because there is also a placeholder when there is no icon, you can set `visibility: hidden` when employees is empty.

I don't think so. If cleaning the data works to display the default icon the right way, there's no reason the same code shouldn't work for custom icons.

**Comment by zombieJ** [comment]
https://codesandbox.io/s/shu-xing-shu-ju-zhan-shi-antd-4-24-12-forked-wcs7sx?file=/demo.tsx

As @linxianxi mentioned. `expandIcon` is always passed to developer incase they need add additional thing with the children-less node:
https://codesandbox.io/s/shu-xing-shu-ju-zhan-shi-antd-4-24-12-forked-q5nj3s?file=/demo.tsx
