### ISSUE TITLE
font-family issue with AntD and NextJS latest

### ISSUE THREAD

**Issue by huypham1411** [ant-design/ant-design#43547]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/beautiful-platform-7ztdyk?file=%2Fapp%2Flayout.tsx%3A16%2C12)

### Steps to reproduce

- `npm install yarn` and install Find font extension for chrome
- run `yarn` to install all the dependency
current version in package.json is "antd": "^5.6.4" and "next": "13.4.7"
- yarn dev to start the project, inspect the Input component font-family (is Roboto_xxx) and use Find font to check (is Roboto_xxx)
- edit the package.json file by changing the AntD and NextJS version to the latest or just run `yarn upgrade-pkg` then use space to select AntD and NextJS to upgrade these to the latest
- re-run the project and inspect the Input component font-family again (Roboto_xxx) and use Find font extension to check (is Times now)

### What is expected?

"next": "13.4.9" and "antd": "^5.7.0" should keep the font-family, in this case, when upgrading to the latest version should be Roboto_xxx, not Times when using Find font extension to check like the previous version

### What is actually happening?

Font-family change with the version

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | Mac OS Big Sur v11.7.8 |
| Browser | Chrome 114.0.5735.198 |

---
https://github.com/ant-design/ant-design/discussions/43505

**Comment by zombieJ** [comment]
As https://github.com/ant-design/ant-design/discussions/43505#discussioncomment-6436394 mentioned. antd does pass the font you are using. With the inspect you will find that style is be what you configured:

<img width="407" alt="截屏2023-07-14 11 23 23" src="https://github.com/ant-design/ant-design/assets/5378891/755e2ff9-de1c-46a6-8d69-6135cf5000c1">

I check the `Roboto` find that your json file is:
<img width="572" alt="截屏2023-07-14 11 36 33" src="https://github.com/ant-design/ant-design/assets/5378891/91de7680-f7b8-4f24-afa6-6ff07f771167">

but provided by next is:
<img width="345" alt="截屏2023-07-14 11 37 25" src="https://github.com/ant-design/ant-design/assets/5378891/738bdc03-098c-4258-875e-eb9c9dad3d3c">

`__Roboto_a17896, __Roboto_Fallback_a17896`  is not `__Roboto_5506ec,__Roboto_Fallback_5506ec`

**Comment by zombieJ** [comment]
If you do not know which `fontFamily` will dynamic be. Just inherit it:

```diff
  {
    "token": {
      "colorPrimary": "#3651d9",
      "colorError": "#EB5146",
--    "fontFamily": "__Roboto_5506ec, __Roboto_Fallback_5506ec"
++    "fontFamily": "inherit"
  }
}
```

**Comment by huypham1411** [comment]
but I wonder what makes the font-family change, the previous version still keeps the same theme config and the font-family

**Comment by huypham1411** [comment]
and why do I wrap the app with AntProvider but the next layout font still overrides the theme config?

**Comment by zombieJ** [comment]
The `roboto_xx` font is dynamic generated by nextjs. Which the suffix code is random generate. Your `theme.json` file config the `fontFamily` which not match nextjs generated one.
As above I typed, just config to `inherit`. Let ConfigProvider ignore `fontFamily` is enough.

**Comment by huypham1411** [comment]
Thank you a lot for your support!
