### ISSUE TITLE
`<Button type="ghost" disabled>` has `cursor: pointer;` style

### ISSUE THREAD

**Issue by saha80** [ant-design/ant-design#43555]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/disabled-antd-5-7-0-forked-thp5mf)

### Steps to reproduce

Set the `type` to "ghost" and set `disabled` to true for the Button.

### What is expected?

expected `disabled` Button to have "`cursor: not-allowed;`"

### What is actually happening?

`disabled` Button with the `type` "ghost" has "`cursor: pointer;`" style.

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | ^18.0.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by kiner-tang** [comment]
@saha80 We recommend that you use the `ghost` prop instead of type="ghost", as the latter will be deprecated in future versions.
https://codesandbox.io/s/disabled-antd-5-7-0-forked-gzcrp4?file=/demo.tsx

**Comment by saha80** [comment]
What class selector should be used to customize ghost Button styles? `.ant-btn-ghost` will be preserved?

**Comment by kiner-tang** [comment]
> What class selector should be used to customize ghost Button styles? `.ant-btn-ghost` will be preserved?

@saha80  You can use `ant-btn-background-ghost`

**Comment by saha80** [comment]
Thank you

**Comment by saha80** [comment]
@kiner-tang 
same issue in 5.7.1
Reproduction link: https://codesandbox.io/s/disabled-antd-5-7-1-forked-v7xmgt
