### ISSUE TITLE
Unexpected DatePicker suffix color with token `colorTextDisabled` set

### ISSUE THREAD

**Issue by wving5** [ant-design/ant-design#43553]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-p3f4p2?file=/demo.js)

### Steps to reproduce

如下设置 DatePicker 的 `colorTextDisabled`
```
  <ConfigProvider
  theme={{
    components: {
      DatePicker: {
        colorTextDisabled: '#f00',
      },
    },
  }}
>
    <DatePicker />
</ConfigProvider>
```

### What is expected?

DatePicker 控件(enable 状态) 的 suffix icon 颜色不会受到 `colorTextDisabled` token 的影响

### What is actually happening?

DatePicker 控件(enable 状态) 的 suffix icon 颜色受到了 `colorTextDisabled` token 的影响

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | MacOS 11.7.7 |
| Browser | Chrome  114.0.5735.198 |

---
可以理解 `colorTextDisabled` 作为 AliasToken 派生自  MapToken `colorTextQuaternary `，两者颜色自然是一致的(默认情况)。
不过 `colorTextDisabled` 语义上定义了一种预期，私以为跟控件的 `disabled` 保持同步比较好。

**Comment by zombieJ** [comment]
嗯，看起来的确是语义不太对。 @MadCcc 是不是这个应该用 colorIcon?

**Comment by MadCcc** [comment]
应该是误用
