### ISSUE TITLE
4.17.0 之前这段代码为什么不会造成死循环，从代码逻辑上来说这段代码应该会发生死循环啊

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#43557]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-32h6hj?file=/index.js:253-289)

### Steps to reproduce

输入框输入1

### What is expected?

死循环页面卡死

### What is actually happening?

没有发生死循环

| Environment | Info |
| --- | --- |
| antd | 4.18.2 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by zombieJ** [comment]
`shouldUpdate` 看起来已经拦起来了，死循环看起来是个 bug。
