### ISSUE TITLE
Datepicker开启showtime 时，只选择年月日，默认以当前时间设置时分秒，希望能设置默认选中的时分秒

### ISSUE THREAD

**Issue by zhangwilling** [ant-design/ant-design#4356]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: window
- 浏览器及其版本: 谷歌最新版

DatePiacker 只选择年月日，默认会以当前时间设置时分秒。
希望能设置默认选中的时分秒。
具体场景：
  例如在选择开始、结束时间时，开始时间这里，一般会以00:00:00作为开始时间。每次让用户自己设置有点麻烦。

**Comment by ddcat1115** [comment]
可以设置 `defaultValue` 么？ 设置下时分秒，好像可以满足你的要求

**Comment by benjycui** [comment]
trace: https://github.com/ant-design/ant-design/issues/2375
