### ISSUE TITLE
Radio. Dot not centered.

### ISSUE THREAD

**Issue by ms-katara** [ant-design/ant-design#43564]
### Reproduction link

[https://lh43vv.csb.app/](https://lh43vv.csb.app/)

### Steps to reproduce

Сhange browser zoom to 80.

### What is expected?

Normal form of radiobuttons - dot in center.

### What is actually happening?

Dot not centered, circle flattened.

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18 |
| System | win10 |
| Browser | Chrome, Firefox, Microsoft Edge, Internet Explorer |

---
Other versions also have this bug.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/36532#issuecomment-1185212104
