### ISSUE TITLE
table组件，使用sticky属性后，底部滚动条会出现两个滚动条

### ISSUE THREAD

**Issue by zswdaye** [ant-design/ant-design#43560]
### Reproduction link

[https://github.com/ant-design/ant-design/tree/master/components/table](https://github.com/ant-design/ant-design/tree/master/components/table)

### Steps to reproduce

table组件使用sticky属性后，表格滑动的底部后会出现两个滚动条，一个原生的，一个antd挂载的。

### What is expected?

只出现一个滚动条

### What is actually happening?

出现了两个滚动条

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | react |
| System | window |
| Browser | Chrome 103.0.5060.134（正式版本）（64 位） |

---
表格需要吸顶的滚动条，加上sticky属性后，滑动到页面底部时，发现表格底部出现两个滚动条，一个原生的一个antd自己挂载上去的

**Comment by afc163** [comment]
Duplicate of #33762
