### ISSUE TITLE
qrcode组件，默认背景居然和size设置有关系，当size为160时，背景是空。为320时，背景是白

### ISSUE THREAD

**Issue by jikoczl** [ant-design/ant-design#43566]
### Reproduction link

[https://ant.design/components/qrcode-cn#components-qrcode-demo-customsize](https://ant.design/components/qrcode-cn#components-qrcode-demo-customsize)

### Steps to reproduce

自定义尺寸，在最小和最大时，分别右键复制图片，出来的二维码的背景色
* ![image.png](https://assets.ruilisi.com/nRLudMUkcjoeflGakLFqOw==)

### What is expected?

统一为白色，不要为空

### What is actually happening?

实际为空

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome 114.0.5735.133 |

**Comment by zombieJ** [comment]
默认背景色都是 `transparent`，复制出来白色是浏览器行为。如果你需要指定背景色，使用 `bgColor` 属性：

https://ant.design/components/qrcode-cn#components-qrcode-demo-customcolor
