### ISSUE TITLE
删除select列表的某个选项(数据后台读的)之后，select的值自己变成已删除option的key值了

### ISSUE THREAD

**Issue by jasminecjc** [ant-design/ant-design#4357]
antd版本：2.5.0
组件：select

现在有一个列表，数据是从后台读的list
![image](https://cloud.githubusercontent.com/assets/13568376/21453173/8f4ecd06-c947-11e6-99b8-d2b78e765cea.png)

有一个按钮，删除当前选中的option，
![image](https://cloud.githubusercontent.com/assets/13568376/21453179/9945929a-c947-11e6-8c6c-8b33661562c9.png)

删除完毕后，后台返回新的list，已经确认后台的数据没问题，返回的是删除后的数据，展示list也没有问题，就是选择框的值自己变成了已删除option的key值
![image](https://cloud.githubusercontent.com/assets/13568376/21453181/a1610ca2-c947-11e6-9339-907710342da9.png)
我设置了initialvalue，console出来的值为正确的option value

**Comment by afc163** [comment]
对的，Select 选中的显示值依赖 Option 里的数据，如果 Option 里没了，只能显示 value。

你可以试试 `labelInValue` 或者前台保留已选择的 Option 完整数据。

**Comment by jasminecjc** [comment]
可是你这显示的也不是value是key值啊。。。

**Comment by afc163** [comment]
value 就是 key 值。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3710

**Comment by jasminecjc** [comment]
有个问题就是我刚才选中的option已经被删除了，select是删除后的组合，还显示已删除的怪怪的
