### ISSUE TITLE
useInsertionEffect error when used with Next.js + tRPC SSR

### ISSUE THREAD

**Issue by PeterTYLiu** [ant-design/ant-design#43571]
### Reproduction link

[https://github.com/PeterTYLiu/antd-trpc-ssr-error](https://github.com/PeterTYLiu/antd-trpc-ssr-error)

### Steps to reproduce

1. `npm i`
2. `npm run dev`
3. Attempt to view the app

### What is expected?

An antd button should be rendered

### What is actually happening?

The app crashes with the following:
```
error useInsertionEffect only works in Client Components.
Add the "use client" directive at the top of the file to use it.
Read more: https://nextjs.org/docs/messages/react-client-hook-in-server-component
```
Note that we are using the `pages` directory only, so the `"use client"` directive shouldn't be necessary

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | macOS Ventura 13.4.1 |
| Browser | Google Chrome 114.0.5735.198 |

---
This can be resolved by removing `ssr: true` in `src/utils/api.ts` (line 51), but we want SSR to work.

**Comment by zombieJ** [comment]
As NextJS mentioned. Config `use client`:

> TypeError: useInsertionEffect only works in Client Components.
Add the "use client" directive at the top of the file to use it.
Read more: https://nextjs.org/docs/messages/react-client-hook-in-server-component

**Comment by xiaolongkipsi** [comment]
I am exact same issue. not possible to upgrade with latest nextjs

**Comment by xiaolongkipsi** [comment]
@PeterTYLiu did you  eventually find a workaround ?

**Comment by luixo** [comment]
It is an issue in `react-ssr-prepass`, though it's not maintained much hence I created an [issue](https://github.com/trpc/trpc/issues/5133) in tRPC repo.

**Comment by PeterTYLiu** [comment]
@xiaolongkipsi tRPC 10.45 removed `react-ssr-prepass` as a dependency, resolving this issue.
