### ISSUE TITLE
Table filterDropdown - visible property not changing

### ISSUE THREAD

**Issue by YuvalPeretz** [ant-design/ant-design#43589]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ktxlu5?file=/index.js)

### Steps to reproduce

1. Create a `Table`
2. Add property `filterDropdown` to the `columns`
3. Destructure the property `visible`
4. Try to use it/log it

### What is expected?

The value `visible` to change to `false`/`true` accordingly to the visability of the dropdown

### What is actually happening?

The change happens once on the first open to `true`, then the value doesn't change

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
Wrong codesandbox link.

<img width="1258" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/502c8e5a-960e-4de1-94ff-77723a90b22b">

**Comment by jeannnemelanie** [comment]
I still have the issue. Please find the demo here: https://codesandbox.io/p/sandbox/ant-design-filter-dropdown-visible-not-working-td9dt7
