### ISSUE TITLE
select 组件的 removeIcon 没有垂直居中

### ISSUE THREAD

**Issue by hellowuxin** [ant-design/ant-design#43596]
### Reproduction link

[https://4x.ant.design/components/select-cn/#components-select-demo-size](https://4x.ant.design/components/select-cn/#components-select-demo-size)

### Steps to reproduce

查看多选下的 removeIcon

### What is expected?

removeIcon 垂直居中

### What is actually happening?

偏下

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 17 |
| System | Windows 10 专业版 |
| Browser | chrome 版本 114.0.5735.199（正式版本） （64 位） |

**Comment by hellowuxin** [comment]
![image](https://github.com/ant-design/ant-design/assets/37543498/38bc91c0-c090-442b-aab0-8643870f69df)

**Comment by Wxh16144** [comment]
和这个问题 https://github.com/ant-design/ant-design/issues/42489#issuecomment-1553948735 属于同一个问题?

**Comment by hellowuxin** [comment]
![image](https://github.com/ant-design/ant-design/assets/37543498/7270f15b-1029-448d-a2dc-418ceb581504)
![image](https://github.com/ant-design/ant-design/assets/37543498/c3e474a2-9d24-4d1c-8b75-5367411840a1)

**Comment by hellowuxin** [comment]
![image](https://github.com/ant-design/ant-design/assets/37543498/a9844105-e188-4b17-b9d8-5698e4b2e6c6)


> 是不是 windows 开了 125% 缩放？

是 100%

**Comment by Wxh16144** [comment]
我用同事的 win 观察确实存在这个问题, 交给我去看看吧

**Comment by Wxh16144** [comment]
我在 win 上测试了一下， 图标问题能解决， 貌似左边的 content 没对齐， mac 和 win 的 chrome 144， 都是 2k 屏幕

mac：

win：
![image](https://github.com/ant-design/ant-design/assets/32004925/4b647165-0b92-4b9a-af8b-108af9333796)
