### ISSUE TITLE
@antd-design/icons icons 'height' and 'width' props do nothing

### ISSUE THREAD

**Issue by illia-bohomol** [ant-design/ant-design#43591]
### Reproduction link

[https://stackblitz.com/edit/react-el5rmg?file=demo.tsx](https://stackblitz.com/edit/react-el5rmg?file=demo.tsx)

### Steps to reproduce

Import any icon from @ant-design/icons package and set width and height to 100

### What is expected?

Icon's width and height should be 100

### What is actually happening?

Icon's width and height didn't change

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18 |
| System | Linux |
| Browser | Google Chrome  |

---
Version of @ant-design/icons: 5.1.4
Why do icons have such props as height and width if they do literally nothing?

**Comment by Yuiai01** [comment]
Hi @illia-bohomol, Only Custom SVG Icon can set the width and height properties. You can refer to https://ant.design/components/icon#components-icon-demo-custom.

**Comment by MadCcc** [comment]
Use `style={{ fontSize: 100 }}` to customize size.

**Comment by gWcyWoo** [comment]
> fontSize

why use fontSize property works well? however, why are the both width and height properties ineffective?
Thanks.
