### ISSUE TITLE
InitialValues not working for nested FormItems

### ISSUE THREAD

**Issue by airoude** [ant-design/ant-design#43592]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-form-nest-items-antd-5-7-0-forked-d5dr8z?file=/demo.tsx)

### Steps to reproduce

Create a form list item or something related and provide it with initialValues.

### What is expected?

To show the initial values in the form list item with nested data.

### What is actually happening?

Renders empty nested form items.

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | react |
| System | MacOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
```diff
    users: [
      // <-- this doesn't work
--    [{ first: "Jared", last: "Dun" }],
++    { first: "Jared", last: "Dun" },
--    [{ first: "Richard", last: "Hendricks" }],
++    { first: "Richard", last: "Hendricks" },
--    [{ first: "Bertram", last: "Gilfoyle" }]
++    { first: "Bertram", last: "Gilfoyle" }
    ]
```

https://codesandbox.io/s/dynamic-form-nest-items-antd-5-7-0-forked-5g5xs4?file=/demo.tsx
