### ISSUE TITLE
日期选择器官方示例，定制单元格选择年份有bug

### ISSUE THREAD

**Issue by chuangwei** [ant-design/ant-design#43595]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nvyf9p)

### Steps to reproduce

选择年份，单元格渲染有问题

![image](https://github.com/ant-design/ant-design/assets/5902016/aa82df35-850f-41bc-bf31-7e6410966a73)

### What is expected?

选择年份，单元格渲染有问题

### What is actually happening?

选择年份，单元格渲染有问题

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by kiner-tang** [comment]
我看看

**Comment by kiner-tang** [comment]
@chuangwei 你可以按照这个实例解决这个问题，官网示例我稍后更新一下：
https://codesandbox.io/s/ding-zhi-dan-yuan-ge-antd-5-7-0-forked-mk8m52
