### ISSUE TITLE
Drawer 组件不能支持响应式宽度

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#43604]
### Reproduction link

[https://ant.design/components/drawer-cn](https://ant.design/components/drawer-cn)

### Steps to reproduce

https://ant.design/components/drawer-cn

### What is expected?

https://ant.design/components/drawer-cn

### What is actually happening?

https://ant.design/components/drawer-cn

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
你遇到了什么问题？烦请详细描述一下？

- Steps to reproduce
- What is expected?
- What is actually happening?

**Comment by vaynevayne** [comment]
<img width="1291" alt="image" src="https://github.com/ant-design/ant-design/assets/124666577/2dd591f6-dbbc-4de1-b089-632918e0e668">

我这个版本缺少这些样式, 在哪里能看到是哪个版本才具有这些样式?
因为 rc-select 那个 pr, 你们一直没处理,我现在是使用 pnpm-patch 解决的, 导致不能升级 antd 了, 有什么办法吗? @afc163

**Comment by afc163** [comment]
> 我这个版本缺少这些样式, 在哪里能看到是哪个版本才具有这些样式? 

给重现吧，不然不知道怎么排查。

> 因为 rc-select 那个 pr, 你们一直没处理,我现在是使用 pnpm-patch 解决的, 导致不能升级 antd 了, 有什么办法吗? 

到具体的 PR 下跟进吧，这里没有上下文。
