### ISSUE TITLE
The overflow-x property affects the position of AutoComplete and Select components

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#43609]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z9g5dk?file=/index.js)

### Steps to reproduce

1. Add `html  {overflow-x: hidden;}`
2. Position the AutoComplete component below the visible part of the screen.
3. Scroll down to the AutoComplete component
4. Focus and type anything

### What is expected?

The Dropdown should be positioned below the AutoComplete component

### What is actually happening?

<img width="443" alt="Screenshot 2023-07-18 at 02 33 05" src="https://github.com/ant-design/ant-design/assets/803674/068c5a62-acde-435b-b8cb-644821ee20dc">

The Dropdown is positioned above the AutoComplete component

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | last |
| System | macOS |
| Browser | Chrome |

**Comment by monolithed** [comment]
If you add the overflow-x: hidden, vertical scroll appears in the modal windows as well.

**Comment by zombieJ** [comment]
Your reproduce not have AutoComplete.

**Comment by monolithed** [comment]
> Your reproduce not have AutoComplete.

Oh, thanks! I updated the link

**Comment by bbb169** [comment]
https://github.com/react-component/trigger/pull/413/files#diff-3294a832ea2276e554177e0b3007cc2d401c082912c7fbde49fa09141bf1aed1L140

I'm not familiar with the logic of the getVisibleArea function, but the bug was caused by the html also setting overflow: hidden, which caused it to be omitted from the omission, thus affecting the overall logic.

**Comment by monolithed** [comment]
@bbb169 did you find a workaround? This affects the Select component as well (

**Comment by bbb169** [comment]
> @bbb169 did you find a workaround? This affects the Select component as well (

hello, my PR did solve this problem, but it has not got a CR.
