### ISSUE TITLE
Confusing Button.onClick type 

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#43608]
### Steps to reproduce

The button type is so confusing that I couldn't figure out which one of the following to use:

*  `React.MouseEventHandler<HTMLButtonElement>`
*  `React.MouseEventHandler<HTMLButtonElement> & React.MouseEventHandler<HTMLAnchorElement>`
*  `React.MouseEventHandler<HTMLButtonElement> & React.MouseEventHandler<HTMLAnchorElement> | undefined`

```jsx
<Button onClick={handleClick}>Send</Button>
```

```jsx
const handleClick = (event: React.MouseEventHandler<HTMLButtonElement>) => {};
```

### What is expected?

In an ideal scenario, the type should be as simple as `React.MouseEventHandler<HTMLButtonElement>`:

```jsx
const handleClick = (event: React.MouseEventHandler<HTMLButtonElement>) => {};
```

### What is actually happening?

<img width="926" alt="Screenshot 2023-07-17 at 19 32 18" src="https://github.com/ant-design/ant-design/assets/803674/7192f6de-5233-4ee9-ac48-2e4233681956">

<br/>
<br/>

| Environment | Info |
| --- | --- |
| antd | Latest |
| React | Latest |
| System | macOS |
| Browser | All |

**Comment by zombieJ** [comment]
Button will be `a` when config `href` prop:

```tsx
<Button href='https://ant.design/index-cn' />
```

**Comment by monolithed** [comment]
> Button will be `a` when config `href` prop:
> 
> ```tsx
> <Button href='https://ant.design/index-cn' />
> ```

@zombieJ, I see, but could you explain how to describe the event property type?


```tsx
const Foo = () => {
    const handleClick = (event: React.MouseEventHandler<HTMLButtonElement>) => {
                                ^^^   is not assignable to type
                  MouseEventHandler<HTMLAnchorElement> & MouseEventHandler<HTMLBUttonElement>
    };

    return <Button onClick={handleClick}>Send</Button>
};
```

I tried to set `React.MouseEventHandler<HTMLButtonElement> & React.MouseEventHandler<HTMLAnchorElement>` but also without success.

**Comment by zombieJ** [comment]
Hmmm. It should be improved.
