### ISSUE TITLE
antd tree在开启拖拽功能后，如何将treeNode拖动至右侧div

### ISSUE THREAD

**Issue by hhbusui** [ant-design/ant-design#43617]
### What problem does this feature solve?

antd tree在开启拖拽功能后，如何将treeNode拖动至右侧div

目前antd tree是可以实现树的上下拖拽的功能，但是实际情况会有将树形节点拖动到画布（div/canvas）的功能。

![image](https://github.com/ant-design/ant-design/assets/43135111/70e5ad28-6394-4cf6-833b-64aa0d0502f7)

### What does the proposed API look like?

暂无

**Comment by afc163** [comment]
还不支持，可以追踪 https://github.com/ant-design/ant-design/issues/26560
