### ISSUE TITLE
rc-cascader `popupClassName`  @deprecated 提示错误

### ISSUE THREAD

**Issue by BanShan-Alec** [ant-design/ant-design#43612]
### Reproduction link

[https://github.com/react-component/cascader/blob/master/src/Cascader.tsx#L96](https://github.com/react-component/cascader/blob/master/src/Cascader.tsx#L96)

### Steps to reproduce

从源码上看出，deprecated 注释写错行了，/** @deprecated Use `dropdownClassName` instead */

### What is expected?

![image](https://github.com/ant-design/ant-design/assets/44499686/78026e38-62bd-47b3-8903-f8aadecb0ecc)

### What is actually happening?

![image](https://github.com/ant-design/ant-design/assets/44499686/06acfea3-0f40-43ef-91c0-0caed904f4c0)
![image](https://github.com/ant-design/ant-design/assets/44499686/70ba5864-53f9-483c-a54c-d87f916d6529)

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.x, 17.x |
| System | windows |
| Browser | chrome 113 |

**Comment by zombieJ** [comment]
`rc-` 组件之前对 API 命名还没有统一，有些是相反的。这个在 antd 里统一做过处理了哈~

ref: https://github.com/ant-design/ant-design/blob/f438c133ff3302fda49083eca7021aedc69da31d/components/cascader/index.tsx#L130-L132
