### ISSUE TITLE
项目实战模块

### ISSUE THREAD

**Issue by han-hao** [ant-design/ant-design#4361]
您好，以下是我的问题：

初接触ant，正在尝试网站的 “项目实战”部分，但是一开始就卡壳了。npm start 命令一直无法启动成功。总是提示：SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode，这应该是es6编码问题吧？但是应该启动服务了就会自动编译了吧？我看到这个demo也用了eslint。但不明白为什么一直报错。

本来想自己用别的方式编译一下，但是您这边有成套的东西在这儿，也不知道怎么做修改。

因为是初学者，可能这样的问题很小白，也想不出太多其他的解决方案，不想因为刚一开始就被打击到了兴趣。还是想问问为什么一直npm start不了。

**Comment by yesmeck** [comment]
你在哪里`npm start`？把 nodejs 升级到最新。

**Comment by yesmeck** [comment]
另外建议到 https://segmentfault.com/t/antd 上做这类问题的咨询。
