### ISSUE TITLE
树形控件Tree作为表单项如何校验是否被选中

### ISSUE THREAD

**Issue by whale-jung** [ant-design/ant-design#43616]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-7-0-forked-tyxmv6?file=/demo.tsx)

### Steps to reproduce

当initValue时treeData中没有的值时，不做任何选择，提交表单成功

### What is expected?

initValue是treeData中没有的值，提交表单能够校验是否已经选择

### What is actually happening?

表单提交成功

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by whale-jung** [comment]
更正：initValue -> initialValue

**Comment by zombieJ** [comment]
复合逻辑可以考虑自定义 `validator`，如果 value 不为空 或者 initialValue 的值不在 treeData 里则通过。不过你这边 `treeData` 和 `initialValue` 是耦合的，最好是在外面做个判断，差不多这个意思：

```tsx
const requiredRule = valInTree(initialValue, treeData);

rules={[ requiredRule ? { required: true }, null ]}
```

PS: 使用问题可以开到 Discussion 里哈~
