### ISSUE TITLE
Modal对话框的【自定义渲染对话框, 可通过 react-draggable 来实现拖拽。】示例存在拖拽使用问题

### ISSUE THREAD

**Issue by wujimalayo** [ant-design/ant-design#43611]
### Reproduction link

[https://4x.ant.design/components/modal-cn/](https://4x.ant.design/components/modal-cn/)

### Steps to reproduce

【自定义渲染对话框, 可通过 react-draggable 来实现拖拽。】示例中
1. 点击Open Draggable Modal打开
2. 鼠标避开Title部分，直接点击Modal body可直接移动

**我能提供的解决方案：**
`const [disabled, setDisabled] = useState(false);`
这一行写错了，默认值应该设为true
`const [disabled, setDisabled] = useState(true);`

### What is expected?

鼠标移入title才能移动

### What is actually happening?

鼠标避开Title部分，直接点击Modal body可直接移动

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | react |
| System | windows11 |
| Browser | chrome最新版 |

**Comment by Wxh16144** [comment]
resolve #43696

**Comment by Wxh16144** [comment]
针对拖拽, 我用  `@dnd-kit/core` 写了一个在线 demo : https://codesandbox.io/s/dnd-kit-tuo-zhuai-antd-modal-mjmxrw
关于modal 我自己也封装了一个  https://github.com/Wxh16144/easy-antd-modal
