### ISSUE TITLE
**InputNuber** 按退格键时会把小数点一起删掉

### ISSUE THREAD

**Issue by ONES-Liuzhang** [ant-design/ant-design#43625]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-vps263?file=/demo.tsx)

### Steps to reproduce

1.输入 1.2
2.按退格键

### What is expected?

输入框展示 1.

### What is actually happening?

输入框展示 1

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | react 18.0 |
| System | macOs 12.2.1 |
| Browser | Microsoft Edge 113.0.1774.57 |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-jnn8xw?file=/demo.tsx

看一下文档：
![Uploading 截屏2023-07-18 19.51.31.png…]()

**Comment by ONES-Liuzhang** [comment]
> https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-jnn8xw?file=/demo.tsx
> 
> 看一下文档： <img alt="截屏2023-07-18 19 51 31" width="601" src="https://user-images.githubusercontent.com/5378891/254253999-d089ae47-b963-4a54-b69f-204e433d4d6f.png">

我尝试过这种方式，会有新的 bug。

受控模式下是 ok 的，但是非受控模式下 info.input 值是错误的。

![image](https://github.com/ant-design/ant-design/assets/18098458/2568d1f7-9089-4706-bce6-b674b6c9fb9c)


https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-26ml63?file=/demo.tsx
