### ISSUE TITLE
How to let CSS-in-JS work with shadow DOM where there are some elements to append?

### ISSUE THREAD

**Issue by xs-ekram** [ant-design/ant-design#43624]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gtzzcf?file=/index.js)

### Steps to reproduce

It can be found in the Shadow DOM Usage data from the official documentation.

### What is expected?

I am using antd in my WordPress   React project.  Where I am using shadow dom. After compiling antd script tags are appending on the head tag. But I am expecting them to append in the shadow dom. 
I have already used the Shadow DOM Usage code from antd official documentation. But the style tags are not appending in the shadow dom. How can I solve this issue?

### What is actually happening?

After using the antd cdn the style tags are appending on head tag of normal dom. For that reason, the shadow dom properties are not getting the CSS of antd.

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | Chrome Version 114.0.5735.199 |

---
The Shadow DOM Usage code from customizing theme page of antd official documentation are not working in this case. I have already used that.

I used antd modules from window.antd as I have used cdn link.

example: 
const { Button } = window.antd

**Comment by zombieJ** [comment]
Your codesandbox not work. Please fix it. In my guess, it my guess, your config `window.antd` and should also use the StyleProvider in `window.cssinjs`
