### ISSUE TITLE
autocomplete: 当label是一个 ReactNode时，onChange会触发“label of value is not same as label in Select options”警告

### ISSUE THREAD

**Issue by Lancernix** [ant-design/ant-design#43637]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-12-forked-gqqmwj?file=/demo.tsx)

### Steps to reproduce

输入后选择一个选项

### What is expected?

消除警告

### What is actually happening?

有警告

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.0.0 / 16.14.0 |
| System | MacOS |
| Browser | Chrome 102 |

---
这个问题已经有issue提到过，问题出现在rc-select这个基础组件中。[rc-select v14.5.2](https://github.com/react-component/select/releases/tag/v14.5.2) 已经修复了这个问题，但是目前antd4.24.x使用的rc-select版本固定为14.1.x，后续是否会在antd4.x中升级使用的基础组件版本来修复这个问题？
ref: [issue#946](https://github.com/react-component/select/pull/946), [issue#40205](https://github.com/ant-design/ant-design/issues/40205)

**Comment by MadCcc** [comment]
4.x 应该不会升级 rc-select 了，应该给 rc-select 14.1.x 发个 patch

**Comment by yoyo837** [comment]
https://github.com/react-component/select/releases/tag/v14.1.18
