### ISSUE TITLE
TreeSelect树选择增加点击父元素文字也可以展示和收缩子元素列表，只最低子级可以选中

### ISSUE THREAD

**Issue by sunwenjie8** [ant-design/ant-design#43639]
### What problem does this feature solve?

只点击前面的小箭头图标展开和收缩列表体验感不是特别好，因为箭头比较小，还是希望可以出一个可以点击文字展开和收缩列表的功能

### What does the proposed API look like?

添加一个配置项，比如aaa:true

**Comment by zombieJ** [comment]
试试 DirectoryTree？

**Comment by linxianxi** [comment]
https://ant.design/components/tree-cn#components-tree-demo-directory

**Comment by sunwenjie8** [comment]
> 试试 DirectoryTree
这不是下拉选择框吧  没有选择框的功能
