### ISSUE TITLE
An error occurs when the Menu component contains a secondary drop-down list

### ISSUE THREAD

**Issue by liuchf0229** [ant-design/ant-design#43636]
### Reproduction link

[https://ant.design/components/menu-cn](https://ant.design/components/menu-cn)

### Steps to reproduce

Copy the horizontal Top Navigation Menu demo of the Menu component to the local project. chrome browser opens, page hover with a drop-down submenu times error.
Error content: ResizeObserver loop limit exceeded

### What is expected?

No error reported

### What is actually happening?

Error content: ResizeObserver loop limit exceeded

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 17.0.2 |
| System | Windows 8 |
| Browser | Chrome浏览器。版本 114.0.5735.199（正式版本） （64 位） |

**Comment by gotchoo** [comment]
Hi, I think I am experiencing a similar issue. 

Using the Menu example code from https://ant.design/components/menu (and without using icons), the menu item labeled `Navigation Three - Submenu` fails to render. 

<img width="357" alt="Screen Shot 2023-07-20 at 10 17 00 AM" src="https://github.com/ant-design/ant-design/assets/93104584/7e74dcef-9b7e-4f94-9f29-bcdb45881d72">
