### ISSUE TITLE
文档支持，期待提供对Mac版Dash的支持

### ISSUE THREAD

**Issue by sunlei33** [ant-design/ant-design#4364]
期待提供对Mac版Dash的支持

**Comment by benjycui** [comment]
@yesmeck 之前尝试过，空了可以完成，或者把实现思路 post 出来让有兴趣的人做。

**Comment by yesmeck** [comment]
之前搞的有个问题， Dash 里的文档地址是这样的 `http://kunkka.local:51711/Dash/zoztvtbz/components/cascader/index.html` 里面的 `zoztvtbz` 是 Dash 随机生成的，没办法给 react-router 设置 basename。

**Comment by benjycui** [comment]
把现在碰到的问题列一下，有空再做。

这事优先级偏低。

**Comment by afc163** [comment]
@pinggod 要不要来试试，算是个有用但比较难做的大活。

**Comment by pinggod** [comment]
@afc163 我可以来试试

**Comment by yesmeck** [comment]
可能需要修改 bisheng  相关配置和代码的地方：

1. Dash 生成的地址需要给 react-router 设置 basename，但是 basename 是随机的，如：`http://kunkka.local:51711/Dash/zoztvtbz/components/cascader/index.html`;
1. Dash 生成的地址带 `index.html`，跟现在 react-router 的路由不匹配；
1. 加载 `demo.js` 和 `index.en-US.md.js` 会 404，原因也是上面的 basename。

**Comment by yesmeck** [comment]
之前搞了一半的 https://github.com/yesmeck/antd-dash ，可以参考。

**Comment by afc163** [comment]
close for no resource..

**Comment by yesmeck** [comment]
<img width="820" alt="screen shot 2018-02-10 at 13 51 00" src="https://user-images.githubusercontent.com/465125/36059009-9e583c48-0e69-11e8-86d8-f5092c288d8f.png">
