### ISSUE TITLE
Is this a menu bug ?

### ISSUE THREAD

**Issue by terminalqo** [ant-design/ant-design#43649]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cg6jcl)

### Steps to reproduce

When mouse hover nav menu item , background color disappear

### What is expected?

Item background color still there.

### What is actually happening?

Background color disappear

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2 |
| System | win10 |
| Browser | 114.0.5735.199 |

---
Vertical menu is normal. but horizontal menu is wrong.

**Comment by terminalqo** [comment]
![image](https://github.com/ant-design/ant-design/assets/20705423/622b5e8b-b09c-4fbc-baa8-5321d83b92d6)

**Comment by terminalqo** [comment]
![image](https://github.com/ant-design/ant-design/assets/20705423/db651036-790e-40a0-a41a-7c9b07f81599)

**Comment by MadCcc** [comment]
bug

**Comment by xubohuah** [comment]
5.7.1 is displayed normally
<img width="712" alt="企业微信截图_86f0ecf8-1f06-4d0d-9597-c4ebe4d2a5eb" src="https://github.com/ant-design/ant-design/assets/111177624/2b6282b7-3fd6-411f-9c26-a3f033474947">
