### ISSUE TITLE
antd 5.x是不兼容IE11了么

### ISSUE THREAD

**Issue by zhangyu0218** [ant-design/ant-design#43648]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-kilby-d6xg59?file=/package.json)

### Steps to reproduce

当我用IE11访问时 提示ant-design_icons 5.1.7 Proxy未定义 加上了polyfill 依然有这个问题，想问一下antd 5已经完全放弃IE浏览器了么

### What is expected?

支持IE11

### What is actually happening?

不支持

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | Window |
| Browser | IE11 |

**Comment by MadCcc** [comment]
是的，https://ant-design.antgroup.com/docs/react/introduce-cn#%E5%85%BC%E5%AE%B9%E7%8E%AF%E5%A2%83

**Comment by zombieJ** [comment]
antd 默认使用最新的浏览器标准。如果需要支持旧版浏览器需要设置一下编译框架以及样式兼容，可以参考：
* https://umijs.org/docs/api/config#targets (umi 的文档，其他的框架也有编译选项)
* https://ant-design.antgroup.com/docs/react/compatible-style-cn

**Comment by zhangyu0218** [comment]
即使使用了babel 也无法支持么
