### ISSUE TITLE
**InputNumber** value 受控时，formatter 的参数 `info.input` 的值错误

### ISSUE THREAD

**Issue by ONES-Liuzhang** [ant-design/ant-design#43641]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-0-forked-26ml63?file=/demo.tsx)

### Steps to reproduce

1. 输入 1

### What is expected?

控制行打印 `formatter {userTyping: false, input: "1"}`

### What is actually happening?

控制行打印 `formatter {userTyping: false, input: ""}`

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | react 18.0 |
| System | macOs 12.2.1 |
| Browser | Microsoft Edge 113.0.1774.57 |

---
value 受控和 value 非受控时，formatter 的参数 `info.input` 返回的值不一样。

**Comment by zombieJ** [comment]
看起来的确有问题
