### ISSUE TITLE
Message API loose messages in async mode

### ISSUE THREAD

**Issue by lesyk-lesyk** [ant-design/ant-design#43659]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/async-messages-issue-react-17-0-2-r2cwtk?file=/index.js)

### Steps to reproduce

Messages API loses some messages while sequential calls are in React 17.0.2. But the same code works correctly in React 18.x.
To reproduce it wrap a few calls to message API in some function and call it on promise resolve/reject.

### What is expected?

The same code should work in React 17 and 18, and all six messages should be shown to the user.

### What is actually happening?

Only four messages out of 6 are displayed, 2 messages were lost (React 17.0.2)

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | 17.0.2 |
| System | macOS 13.4.1 |
| Browser | Google Chrome v114.0.5735.198 |

**Comment by lesyk-lesyk** [comment]
Case 1. Sync: all 6 messages are shown.

  ![image](https://github.com/ant-design/ant-design/assets/16646570/d0f107ba-a001-486a-8672-c6f79e9683ee)

Case 2. Async: only 4 messages are shown (2nd and 5th were skipped for no reason)

  ![image](https://github.com/ant-design/ant-design/assets/16646570/e1523bef-67ca-4c42-a9e1-b53b8ea76670)

**Comment by zombieJ** [comment]
fixed https://codesandbox.io/s/async-messages-issue-react-17-0-2-forked-qzllp6?file=/package.json
