### ISSUE TITLE
Events type lost on the Button component

### ISSUE THREAD

**Issue by joelcampospi** [ant-design/ant-design#43654]
### Reproduction link

[https://antd-broken-onclick--joelcampospi.repl.co/](https://antd-broken-onclick--joelcampospi.repl.co/)

### Steps to reproduce

Use the onClick event of a Button component. The type of the parameter of the onClick function is now 'any' instead of the expected Event type.

### What is expected?

To have a valid Event type for the parameter of the onClick event.

### What is actually happening?

An 'any' type is being inferred

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | 18.2.0 |
| System | WSL Ubuntu 22 |
| Browser | Firefox and Edge |

---
This didn't happened on the 5.7.0 version, so it might have broken because of some changes in the latest release (5.7.0 -> 5.7.1).

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/43629

**Comment by joelcampospi** [comment]
Thank you!
