### ISSUE TITLE
Badge 的 processing 状态用于角标时有样式错误

### ISSUE THREAD

**Issue by hungtcs** [ant-design/ant-design#43653]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-w736qj?file=/index.js)

### Steps to reproduce

1. 将 Badge 为角标模式并将状态设置为 processing

```tsx
<Badge dot status="processing">
  <Button icon={<CodeSandboxOutlined />} />
</Badge>
```

### What is expected?

1. 正常显示

### What is actually happening?

2. 样式错误

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | 18.2.0 |
| System | MacOS 13.3 (22E252) |
| Browser | Google Chrome 111.0.5563.146 (arm64) |

**Comment by hungtcs** [comment]
![image](https://github.com/ant-design/ant-design/assets/11692935/d7914eb4-d7d4-4926-b119-651a6683cf01)

**Comment by Wxh16144** [comment]
感觉 `dot` 和 `status` 同时使用好奇怪  2333~
