### ISSUE TITLE
`<Button type="ghost" disabled>` has `cursor: pointer;` style

### ISSUE THREAD

**Issue by saha80** [ant-design/ant-design#43661]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/disabled-antd-5-7-1-forked-v7xmgt?file=/demo.tsx)

### Steps to reproduce

Set the type to "ghost" and set disabled to true for the Button.

### What is expected?

expected disabled Button to have "cursor: not-allowed;"

### What is actually happening?

disabled Button with the type "ghost" has "cursor: pointer;" style.

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | ^18.0.0 |
| System | Windows 10 |
| Browser | Chrome 115 |

---
The button type in the documentation mismatches with the actual button type.

https://github.com/ant-design/ant-design/blame/5.7.1/components/button/index.en-US.md#L70

https://github.com/ant-design/ant-design/blame/5.7.1/components/button/buttonHelpers.tsx#L67

the same issue has been reported.

https://github.com/ant-design/ant-design/issues/43555

**Comment by MadCcc** [comment]
@afc163 `type="ghost"` 在 v5 是缺失样式的，这个是不是要废弃掉了？

**Comment by afc163** [comment]
应该是直接用 `<Button ghost />`
