### ISSUE TITLE
Pass a link to an active element in the Collapse component

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#43664]
### What problem does this feature solve?

I suggest returning the link to the active element as the second parameter in the onChange event. This will allow quickly locating the element and calling scrollIntoView on it.
Without a reference to an active element, it's difficult to find it in the DOM because there are no identifiers available.

### What does the proposed API look like?

```js
onChange(key, activeElement);
```

**Comment by zombieJ** [comment]
This implementation is too piecemeal. In fact, under different requirements, developers have different requirements for the required dom elements. You can HOC of this:

https://codesandbox.io/s/zhe-die-mian-ban-antd-5-7-1-forked-gw9tny?file=/demo.tsx

**Comment by monolithed** [comment]
@zombieJ, thank you so much! There isn't the ref property in the docs
