### ISSUE TITLE
form里用了tree组件 如何在表单提交后清空tree的选择状态

### ISSUE THREAD

**Issue by ABoooClay** [ant-design/ant-design#4366]
form里用了tree组件 如何在表单提交后清空tree的选择状态？
<!--
antd 的用法咨询，建议通过以下渠道，官方 issues 目前没有足够精力提供此类咨询服务：

**Comment by yesmeck** [comment]
使用问题建议到 https://segmentfault.com/t/antd 上提问。

**Comment by yesmeck** [comment]
试试 `resetFields`
