### ISSUE TITLE
Table能够提供一个fit属性，使其自适应容器高度，然后自身顶天立地显示，header显示在顶部，统计、分页显示在底部，中间撑满

### ISSUE THREAD

**Issue by zkgaojianjian** [ant-design/ant-design#43671]
### What problem does this feature solve?

日常的erp系统开发中，都要求表格header居页面顶部，统计、分页居页面的最底部，中间自动撑满，然后表格高度自适应容器，页面改版大小，或者其他元素挤压的话重新自动适应。

### What does the proposed API look like?

fit 类型：boolean 是否自适应容器 默认值：false

**Comment by zombieJ** [comment]
直接 `height: 100%` 如何？

https://codesandbox.io/s/ji-ben-yong-fa-antd-5-7-1-forked-rn6jhh?file=/index.css

**Comment by zkgaojianjian** [comment]
中间容器高度撑满，内容滚动

**Comment by poyiding** [comment]
> 直接 `height: 100%` 如何？
> 
> https://codesandbox.io/s/ji-ben-yong-fa-antd-5-7-1-forked-rn6jhh?file=/index.css

他想要表头固定在页面顶部，翻页组件固定在页面底部，中间内容滚动这种

![image](https://github.com/ant-design/ant-design/assets/15643321/342db41d-a0cf-42a6-8887-b4ed6a639e9a)

**Comment by MadCcc** [comment]
Trace https://github.com/ant-design/ant-design/issues/44482
