### ISSUE TITLE
antd Table表头排序现在是整个th点击触发排序，但我需要在title中增加按钮，点按钮不触发排序

### ISSUE THREAD

**Issue by Meikongggg** [ant-design/ant-design#43678]
### Reproduction link

[https://4x.ant.design/components/table-cn/#API](https://4x.ant.design/components/table-cn/#API)

### Steps to reproduce

在columns中自定义title，类似<div><button>123</button>我是表头标题</div>,点击button会触发当前column的排序事件

### What is expected?

我期望在点击button的时候阻止这个排序事件的触发

### What is actually happening?

点击button也会触发排序

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18.2 |
| System | mac |
| Browser | chrome114 |

**Comment by Meikongggg** [comment]
![image](https://github.com/ant-design/ant-design/assets/32662465/70f92b31-4c5e-4525-8d7e-d3a2a9cbba9d)

**Comment by linxianxi** [comment]
button 加 `e.stopPropagation`

**Comment by Meikongggg** [comment]
...
