### ISSUE TITLE
Tour 组件 target={null} 时弹窗不垂直居中

### ISSUE THREAD

**Issue by zhao-xiaohu** [ant-design/ant-design#43673]
### Reproduction link

[https://ant.design/components/tour-cn](https://ant.design/components/tour-cn)

### Steps to reproduce

点击「位置」官方用例的按钮就能直接复现。
![image](https://github.com/ant-design/ant-design/assets/34085364/955f4775-9e16-4ccb-882c-ef2c9925f2d7)

### What is expected?

引导卡片垂直居中

### What is actually happening?

在 antd 版本 ~5.2 是正常的，从 ~5.3 开始一直异常。当引导内容较多时（引导卡片趋近正方形），视觉问题突出的就更明显。

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | 18.1.0 |
| System | MacOS 13.4.1 (22F82) |
| Browser | Chrome 114.0.5735.198 |

---
在 mac 上（1280*800）卡片居上（卡片的下边沿出现在屏幕中间），但在显示器上（1920*1080）卡片居下（卡片的上边沿出现在屏幕中间）

**Comment by MadCcc** [comment]
看起来确实有问题

**Comment by MuxinFeng** [comment]
`target: null` 可以保证 `triggerDom` 出现在屏幕中间，如果想让弹窗处于中间，还需要将 `placement` 设置为 `center`。
