### ISSUE TITLE
结合 react-infinite-scroller 实现滚动自动加载列表，当数据数量不多时，会显示骨架屏

### ISSUE THREAD

**Issue by Heroic-Q** [ant-design/ant-design#43677]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-galileo-5yy3qr)

### Steps to reproduce

打开链接即可

### What is expected?

只显示： [ITEM] test

### What is actually happening?

显示了 [ITEM] test 和 骨架屏

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | 18.2.0 |
| System | win10 |
| Browser | Google Chrome 114.0.5735.90 |

---
链接中用的是antd3.6.20和react16.3.2, 我本机代码是antd5.6.4和react18.2.0，都是同样的问题

**Comment by afc163** [comment]
看上去是 react-infinite-scroll-component 的使用问题，和 antd 关系不大
