### ISSUE TITLE
Tree 使用expandedKeys 触发 loadData 时，第二次无效

### ISSUE THREAD

**Issue by zhenghan2017** [ant-design/ant-design#43681]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-shu-ju-jia-zai-antd-5-7-0-forked-5nnfzk?file=/demo.tsx)

### Steps to reproduce

1. 点击展开按钮，第一个节点展开 -> onLoadData 函数被调用
2. 点击 reset loadedKeys 按钮 -> 第一个节点收起
3. 再次点开展开按钮 -> onLoadData 函数没有调用

### What is expected?

多次点开展开按钮，onLoadData都能正常调用

### What is actually happening?

多次点开展开按钮，onLoadData不能正常调用

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.0.0 |
| System | macOS 12.3 |
| Browser | Chorme  114.0.5735.198 |

**Comment by zombieJ** [comment]
节点如果已经有 `children` 就不会触发 `loadData` 了哈~

**Comment by zhenghan2017** [comment]
针对这种情况，只能通过清除treeData本身的数据来做受控嘛？

**Comment by zhenghan2017** [comment]
> 节点如果已经有 `children` 就不会触发 `loadData` 了哈~

按这个逻辑走，loadedKeys 的受控意义就没有意义了
