### ISSUE TITLE
Tooltip. Tooltip is not hidden if click to antd tabs.

### ISSUE THREAD

**Issue by griboedovvladimir** [ant-design/ant-design#43685]
### Reproduction link

https://codesandbox.io/s/antd-reproduction-template-forked-v7nhc5?file=/index.js

### Steps to reproduce

Open antd tooltip by click (trigger='click'). Click to any ant tab on the page.

### What is expected?

Tooltip should be hidden.

### What is actually happening?

Tooltip isn't hidden.

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | 18.2.0 |
| System | Ubuntu 20.04.3 LTS |
| Browser | Chrome 114.0.5735.198 (Official Build) (64-bit) |

**Comment by griboedovvladimir** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-v7nhc5?file=/index.js

**Comment by griboedovvladimir** [comment]
> To reproduce
> https://codesandbox.io/s/antd-reproduction-template-forked-v7nhc5?file=/index.js

**Comment by griboedovvladimir** [comment]
> Your reproduce seems not provide the Tooltip in code.

To reproduce
https://codesandbox.io/s/antd-reproduction-template-forked-v7nhc5?file=/index.js

**Comment by JarodFlorence** [comment]
@griboedovvladimir  I just checked the codesandbox. 
It only hides when you click the content of a tab. I think this is an issue.
