### ISSUE TITLE
getFieldProps('content')会导致样式问题

### ISSUE THREAD

**Issue by denny-lee** [ant-design/ant-design#4369]
#### 发生问题的环境是：react15.0.0+antd1.0.0

- antd 版本:1.0.0
- 操作系统及其版本:windows7
- 浏览器及其版本:chrome 55.0.2883.87 m

#### 您做了什么？请提供尽可能详细的重现步骤。
const contentProp = getFieldProps('content', {
                                        rules: [{
                                            required: true,
                                            message: '请输入content'
                                        }]
                                    });
<Input  {...contentProp}/>

#### 您期待的结果是:
显示单行的input框

#### 实际上的结果是:
显示成了高度很高的input框，有点像row=20的textarea，但它是input。
把getFieldProps('content')中的content改为content_a，input框就能够正常显示。
![image](https://cloud.githubusercontent.com/assets/3351948/21488503/975d98b6-cc1b-11e6-972d-ade0008d6c42.png)
![image1](https://cloud.githubusercontent.com/assets/3351948/21488504/975e5878-cc1b-11e6-9db8-127f93d5e2c2.png)
![image2](https://cloud.githubusercontent.com/assets/3351948/21488505/97645ac0-cc1b-11e6-9a10-6589c92c42d7.png)

**Comment by ddcat1115** [comment]
请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
为啥要用 1.0，直接用 1.11 或者 2.5。

**Comment by benjycui** [comment]
`getFieldDecorator` 和 `getFieldProps` 都会给表单域设置 `id={name}`，所以你应该是有样式设置了 `#content` 的高度。
