### ISSUE TITLE
在Form表单内设置Buttom按钮为htmlType="submit"的时候，提交能否按钮自动改成加载中，在接口返回成功后恢复原样

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#43695]
### What problem does this feature solve?

做表单的时候，特别是新增的时候，有时候接口返回慢，操作过快多次点击容易创建多条重复的数据。这样做有利于误点。

### What does the proposed API look like?

提供一个类似于loading的参数，设置为true，可以控制htmlType="submit"的按钮状态

**Comment by zombieJ** [comment]
有的，ProForm 里封装好了哈~

https://procomponents.ant.design/playground/pro-form
