### ISSUE TITLE
文档疑问

### ISSUE THREAD

**Issue by BoizZ** [ant-design/ant-design#4370]
`Form` 组件里面的 `setFields` 方法能写全点吗？设置 error ？ 设置 value ？
```
Function(obj: object)
```
How to ???

**Comment by BoizZ** [comment]
每个版本都存在的问题，就这样无视掉吗？

**Comment by yesmeck** [comment]
可以 PR 帮我们修改下吗？

**Comment by BoizZ** [comment]
:frowning: :frowning: :frowning: 什么鬼

**Comment by afc163** [comment]
欢迎对文档缺失和错误的地方直接 PR 贡献。

**Comment by afc163** [comment]
@BoizZ 可以试试么？

**Comment by afc163** [comment]
。。。还是我来吧。

@BoizZ 由于 antd 组件功能非常多，不可避免有文档缺失和错误，所以我们鼓励社区一起来完善文档。也有很多用户帮我们提交了文档：https://github.com/ant-design/ant-design/pulls?q=is%3Apr+is%3Aclosed

所以也欢迎你后续参与。

**Comment by BoizZ** [comment]
后面吧，年底你懂的 @afc163
