### ISSUE TITLE
期望Form.Item可增加固定宽度的设置，或者取消rules设置required时，自动添加required样式的

### ISSUE THREAD

**Issue by zmbxy** [ant-design/ant-design#43706]
### What problem does this feature solve?

Form使用horizonta布局，label文本左对齐，Form.Item中的Input框要对齐，需要label等宽，目前可通过labelCol来给所有labei设置等宽，但是在某些情况下，labelCol的设置会有点问题，小一个数值，label会label显示不全或者很拥挤，大一个数值，表单整体会显得偏左，基于这种情况，在不修改Form.Item样式下，会设置给Form.Item的label属性传递一个固定宽度的div，如下：
```tsx
<Form.Item
  label={<div style={{ width: 120 }}>名称</div}
  name="name"
>
  <Input/>
</Form.Item>
```
此时如果在给Form.Item设置rules，required，如下：
```tsx
<Form.Item
  label={<div style={{ width: 120 }}>名称</div}
  name="name"
  rules={[
    { required: true, message: '请输入' },
  ]}
>
  <Input/>
</Form.Item>
```
此时`required: true`属性会添加一个required样式，此时的显示由于label是固定宽度的div，会导致文本和必填标识（*）有之间很大的空白，显示效果如下：

<img width="466" alt="image" src="https://github.com/ant-design/ant-design/assets/103547464/858090df-ce0d-4bd7-840d-32de241365c0">

上述问题虽也可通过设置rules validator，自实现required判断逻辑，但也繁琐，一些简单的，还是希望能直接使用required规则来实现必输校验逻辑。

### What does the proposed API look like?

对于API的期望如下：
1. Form.Item增加labelWidth或者labelStyle来自定义label样式属性
2. 取消设置required: true，自动添加required样式，而统一由Form.Item的required来设置样式。

**Comment by Wxh16144** [comment]
可以设计一个 api 将这个问题和 https://github.com/ant-design/ant-design/issues/43494 一起解决了.

**Comment by zombieJ** [comment]
星号是可以关的：
http://ant-design.antgroup.com/components/form-cn#components-form-demo-required-mark

**Comment by zombieJ** [comment]
And labelCol 和 wrapperCol 是可以接受 flex 设置的：
https://codesandbox.io/s/ji-ben-shi-yong-antd-5-7-1-forked-9khtcy?file=/demo.tsx
