### ISSUE TITLE
Exported variable 'xxx' has or is using name 'xxx' from external module xxx" but cannot be named. ts(4023)

### ISSUE THREAD

**Issue by liboliang01** [ant-design/ant-design#43701]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jxk3py?file=%2Fsrc%2Findex.tsx%3A4%2C1)

### Steps to reproduce

重现链接的仓库会出现ts报错

### What is expected?

无ts报错

### What is actually happening?

Exported variable 'MenuV5' has or is using name 'GenericComponent' from external module "/_antd@5.7.2@antd/es/menu/index" but cannot be named. ts(4023)
Exported variable 'MentionsV5' has or is using name 'MentionsConfig' from external module "/_antd@5.7.2@antd/es/mentions/index" but cannot be named. ts(4023)
Exported variable 'DescriptionsV5' has or is using name 'CompoundedComponent' from external module "/_antd@5.7.2@antd/es/descriptions/index" but cannot be named. ts(4023)
Exported variable 'messageV5' has or is using name 'MessageMethods' from external module "/_antd@5.7.2@antd/es/message/index" but cannot be named.ts(4023)
Exported variable 'messageV5' has or is using name 'BaseMethods' from external module "/_antd@5.7.2@antd/es/message/index" but cannot be named.ts(4023)
Exported variable 'notification' has or is using name 'NoticeMethods' from external module "_antd@5.7.2@antd/es/notification/index" but cannot be named.ts(4023)
Exported variable 'notification' has or is using name 'BaseMethods' from external module "_antd@5.7.2@antd/es/notification/index" but cannot be named.ts(4023)

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.2 |
| System | macOS 12.5 |
| Browser | Chrome113.0.5672.126 |

**Comment by zombieJ** [comment]
看起来没有报错，要做什么操作么？

<img width="470" alt="截屏2023-07-21 14 52 58" src="https://github.com/ant-design/ant-design/assets/5378891/b23e6098-b19a-44ac-9e3c-91c7f4323d8b">

**Comment by liboliang01** [comment]
很奇怪，我又看了一下链接，确实没报错了。下面是我本地的报错。Menu、Description、Mentions、message、notification都出现了同样的问题
![image](https://github.com/ant-design/ant-design/assets/55911020/6b12c10e-ff7f-410a-8667-19045aa2ef00)

**Comment by afc163** [comment]
最好给个重现，不然不知道问题在哪。
