### ISSUE TITLE
Fix of issue #43615 is not pulled into antd package

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#43715]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-textarea-runtime-error-d3xdfs)

### Steps to reproduce

Test the issue in 5.7.1 and 5.7.2.

### What is expected?

Original issue https://github.com/ant-design/ant-design/issues/43615 is fixed.

### What is actually happening?

The issue is fixed in [react-component/textarea](https://github.com/react-component/textarea) repo, but antd repo does not pull this new version, thus 5.7.1 and 5.7.2 still have this issue.

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 112.0.5615.121 |

**Comment by MuxinFeng** [comment]
https://github.com/ant-design/ant-design/blob/master/package.json#L151

**Comment by panlina** [comment]
> https://github.com/ant-design/ant-design/blob/master/package.json#L151 Antd will automatically apply the latest patch version of rc-textarea, you can try to reinstall dependencies.

The version including the fix is [1.3.3](https://github.com/react-component/textarea/releases/tag/v1.3.3), not 1.3.2.

**Comment by afc163** [comment]
Please remove node_modules and yarn.lock and package-lock.json and reinstall it.
