### ISSUE TITLE
Tabs editable with drag and drop using @dnd-kit

### ISSUE THREAD

**Issue by lochdeve** [ant-design/ant-design#43714]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/draggable-tabs-antd-5-2-2-forked-gd3hj7)

### Steps to reproduce

Try to drag an drop a tab to change the order

### What is expected?

Is expected no do an smooth movement

### What is actually happening?

When you drag and drop the tab the movemente is too slow and has an strange behaviour

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | Google chrome |

**Comment by linxianxi** [comment]
probably affected by the animation, try this
```
<ConfigProvider theme={{ token: { motion: false } }}>
  <Tabs />
</ConfigProvider>
```

**Comment by lochdeve** [comment]
This help but it continue working a little strange when you have a large list of tabs. If you drag the first tab to the end, the name of the tab start to decrease it size.

**Comment by linxianxi** [comment]
you can set
```
transform: CSS.Transform.toString(transform && { ...transform, scaleX: 1 }),
```

**Comment by lochdeve** [comment]
Nice, thanks. Now it is working alright
