### ISSUE TITLE
Table组件的滚动能不能支持百分比

### ISSUE THREAD

**Issue by wyl0325** [ant-design/ant-design#43710]
### What problem does this feature solve?

解决用变量和监视视窗变化带来的代码量，简化开发流程和满足更多的需求

### What does the proposed API look like?

table的api里面scroll目前支持string和number，但是需要的都是固定像素，如果需要适配就要用变量来检测外部容器的大小变化，能不能让这个属性支持百分比的布局，例如{ y: ‘50%’ }，表示这个table的滚动区域占外部容器的百分比大小？

**Comment by afc163** [comment]
Try `y: '50vh'`
