### ISSUE TITLE
Tree拖拽时，同级Node之间高亮区域要大于事件触发（鼠标变为+号）的区域

### ISSUE THREAD

**Issue by pixystone** [ant-design/ant-design#4371]
发生在top级别的Node之间

拖拽的时候，Node上方的高亮区域要大于鼠标变为+号的区域，而实际上鼠标变为+号才能够触发事件，但区域蓝色高亮的提示要比鼠标的变化更引用户注意，所以有时候拖动到高亮出现，但事件没有发生，会造成用户困扰。

#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本:  osx
- 浏览器及其版本: Chrome

http://codepen.io/anon/pen/zoVodq?editors=0010

正如示例里面，把`3333`拖起来，`1111`和`2222`之间有一段空隙是不会触发事件的，但是会有高亮效果

可能这个留空的位置是用来触发展开子节点事件的，但是高亮的范围是否可以缩小一些？

**Comment by ddcat1115** [comment]
你是指的这种情况？

<img width="346" alt="2016-12-27 4 24 52" src="https://cloud.githubusercontent.com/assets/7017767/21495025/3e3e4dc2-cc50-11e6-8b45-16b497760625.png">

**Comment by pixystone** [comment]
是的，这种情况下放开鼠标什么事都不会发生。

**Comment by ddcat1115** [comment]
@yesmeck  能瞅瞅吗？能不能不要这块区域呢
