### ISSUE TITLE
Radio 选中样式有微弱的差别

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#4372]
Win10 Chrome55 中间的小点不居中，设计如此？
![qq 20161227151130](https://cloud.githubusercontent.com/assets/3746762/21493686/c29f26d0-cc47-11e6-96f1-2118d08b6ee8.png)
![qq 20161227151141](https://cloud.githubusercontent.com/assets/3746762/21493687/c2a07d14-cc47-11e6-87d4-ef996b8051f0.png)

**Comment by afc163** [comment]
看上去是样式兼容性问题，尝试来个 PR 如何？

**Comment by wangdao** [comment]
能力有限，交给其他人吧，我就偷偷的观望吧。。。

**Comment by afc163** [comment]
主要是无法重现，最好在你的环境看看问题出在哪。

**Comment by afc163** [comment]
@wangdao 看到问题在哪直接 PR 吧，我们这里都无法重现。

**Comment by wangdao** [comment]
@afc163  好的

**Comment by chengzhenping** [comment]
@afc163   
多个win32 chrome和mac chrome都有这样子的问题
![image](https://user-images.githubusercontent.com/6301471/33258407-6b7907ae-d394-11e7-99b8-2174975b3ef9.png)

**Comment by chengzhenping** [comment]
有的居中，有的没有居中，没有居中的比较明显

**Comment by afc163** [comment]
Try <kbd>cmd</kbd> + <kbd>0</kbd>
