### ISSUE TITLE
The slider does not move after clicking on a random spot on the track

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#43728]
### Reproduction link

[https://ant.design/components/slider](https://ant.design/components/slider)

### Steps to reproduce

https://github.com/ant-design/ant-design/assets/803674/9a9b6d3e-463a-48f0-a51b-07b0c827ce92

### What is expected?

After grabbing the slider, it should move regardless of whether we clicked on it or on a random spot on the track. 
Expected behavior is as shown here https://3x.ant.design/components/slider/. As you can see, in the third version, everything was working correctly.

### What is actually happening?

After clicking on a random spot on the track, the slider moves, but it doesn't respond to the mouse. 

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18 |
| System | Mac |
| Browser | All |

**Comment by liuchuanlllldjd** [comment]
看起来确实有这个问题，我正在尝试修复

**Comment by liuchuanlllldjd** [comment]
After reviewing the code, it appears that the new version of rc-slider does not support this feature. However, when I switched to the older version of rc-slider, the functionality was supported. I will attempt to submit a pull request to rc-slider to address this issue.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/45651
