### ISSUE TITLE
table 第一行 hover 时 background 带圆角

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#4373]
重新方法：`<Table style={{ background: 'pink'}} columns={columns} title={data => data.length} dataSource={data} showHeader={false} />`

如图，圆角应该是属于 title 的，但是分配了个第一行记录

期望：hover 时第一行 bg 没有圆角

其他信息：如果设置了 bordered 就不会有这个问题

![image](https://cloud.githubusercontent.com/assets/5318333/21494396/3682e506-cc4c-11e6-9fa7-4411035785b6.png)

BTW，能否考虑把 padding 开放出来，现在的设计稿上基本上头部和实际内容都有 padding 来包裹，分别用 render 来做总感觉很麻烦，每一个用 table 的地方都需要定义一次

**Comment by RaoHai** [comment]
这个比较纠结。。圆角是属于 table 的，而 title 并不在 table 里。。

**Comment by RaoHai** [comment]
好像就是这么设计的：https://github.com/ant-design/ant-design/commit/4b2e9bbd23b93cb146a0a2b8622d260f7eada941

**Comment by jaredleechn** [comment]
@afc163 这个是 by design 的吗？

bordered 和 非 border 在使用场景上有什么差异吗？

**Comment by afc163** [comment]
目前 bordered 也是第一列圆角。

<img width="881" alt="image" src="https://cloud.githubusercontent.com/assets/507615/21496603/b2309bae-cc5a-11e6-8155-294df5b3d696.png">

**Comment by jaredleechn** [comment]
在有 title 和 bordered 的情况下，是 title 圆角

![image](https://cloud.githubusercontent.com/assets/5318333/21497425/b7af0e9e-cc5f-11e6-88c9-7d073b7355a9.png)

**Comment by afc163** [comment]
哦是的，因为视觉部分需要是圆角。`bordered={false}` 时，title 可以看做是表格外了。

**Comment by afc163** [comment]
没 header 时，第一列不再是圆角。
