### ISSUE TITLE
The styling of the slider in version 5 differs from the 4th version

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#43732]
### Reproduction link

[https://ant.design/components/slider/](https://ant.design/components/slider/)

### Steps to reproduce

-

### What is expected?

The same behavior as in version 4 is expected, which replicates the styling of other components (buttons, checkboxes, etc.).
https://4x.ant.design/components/slider/

https://github.com/ant-design/ant-design/assets/803674/adb12e72-b39f-4095-b1c4-693e2b895e47

### What is actually happening?

https://github.com/ant-design/ant-design/assets/803674/5a037376-ff06-49e8-ba82-5b1a0a44fad8

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | All |
| System | All |
| Browser | All |

**Comment by afc163** [comment]
It is by designed, we upgraded default border radius value in antd v5.
