### ISSUE TITLE
增加组件Splitter 分割器

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#43737]
### What problem does this feature solve?

增加组件Splitter 分割器

### What does the proposed API look like?

参考 DevUI https://devui.design/components/zh-cn/splitter/demo 很实用，在B端系统里

**Comment by MadCcc** [comment]
和 Menu 的收缩类似的能力，但是更泛用些

**Comment by afc163** [comment]
https://ant.design/docs/react/recommendation-cn

**Comment by RedJue** [comment]
感觉挺不错的

**Comment by leshalv** [comment]
+1

**Comment by MadCcc** [comment]
Trace in https://github.com/ant-design/ant-design/issues/44525
这个功能覆盖面更广一些

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/50038
