### ISSUE TITLE
@ant-design/react-slick这个包0.29.2~1.0.1有什么breakChange吗，进行了什么改动，看tag也没有好好打，不敢升级

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#43748]
### Reproduction link

[https://github.com/ant-design/react-slick](https://github.com/ant-design/react-slick)

### Steps to reproduce

无

### What is expected?

有文档解释说明

### What is actually happening?

没有任何文档

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by MadCcc** [comment]
底层包，一般不需要自己用的

**Comment by afc163** [comment]
没有变化，就是发个正式版本，变化会体现在 commit history 里的。https://github.com/ant-design/react-slick/commits/master

**Comment by DY-ZYQ** [comment]
> 

我们这里进行了一些ui升级，需要直接依赖使用
