### ISSUE TITLE
Disable submit button on form

### ISSUE THREAD

**Issue by Themandunord** [ant-design/ant-design#4374]
Hi guys,

It is possible to disable the form button when all ForItem are not valided ? 
Like [react-validation](https://github.com/Lesha-spr/react-validation) does.

Thanks.

**Comment by afc163** [comment]
It can be done by passing disabled to `Button[htmlType="submit"]` via React Context. @benjycui

**Comment by benjycui** [comment]
So.. we need to find `Button[htmlType="submit"]` recursively? For the structure in Form it's unsure.

**Comment by benjycui** [comment]
What we need is a handy API to determine whether all `Form.Item` are not valided

**Comment by afc163** [comment]
Use context and add logic inside `Button[htmlType="submit"]`.

**Comment by Themandunord** [comment]
Hi guys,

So if I understand, you'll work on it ?

**Comment by afc163** [comment]
We need a `this.props.form.getFields()`.

**Comment by benjycui** [comment]
`componentDidMount` and then trigger `validateFields`, if any errors, disabled `Button`. Because, `Form.Item` will auto show errors if any, so we need to add a flag to know that whether a field is touched by users. If it's touched, show errors, otherwise, don't show errors. This is also what `react-validation` do.

To achieve the new target. We need to add `this.props.form.getFieldsError()`. And we to add `field.touched=true` flag to mark a field as touched in `rc-form`, if the value of a form component is changed, so that `Form.Item` can know whether to show errors.(Also need to expose `isTouched`)

But the problem is that, `rc-form` allows developers set initial errors with `mapPropsToFields`. If we import `field.touched`, previous codes haven't add this field in `mapPropsToFields`, then developers will found that errors won't show by `Form.Item`. This is a little breaking changes.

**Comment by benjycui** [comment]
But I think that we can add this feature, thought there is a little breaking changes.

**Comment by benjycui** [comment]
rc-form add new feature:
* `this.props.form.getFieldErrors()`
* `this.props.form.isTouched(name?)`

**Comment by benjycui** [comment]
You can do this thing in `antd@2.7` which will be release at the end of this month.

https://github.com/ant-design/ant-design/commit/f436b5c2f4d49eb78dd0e2988d72e65104dbdd70#diff-91732ba15efdab445f59d157a9e8ed84

**Comment by Themandunord** [comment]
Thanks @benjycui !
Awesome work :+1:

**Comment by jch254** [comment]
Thanks @benjycui !!

**Comment by neekey** [comment]
Hi @benjycui , instead of doing the stuff below manually:

```
// Only show error after a field is touched.
 +    const userNameError = isFieldTouched('userName') && getFieldError('userName');
 +    const passwordError = isFieldTouched('password') && getFieldError('password');
```
how about add an extra prop for form item like `showErrorOnlyTouched`?

**Comment by benjycui** [comment]
> how about adding an extra prop for form item like showErrorOnlyTouched?

Nope, it's impossible to integrate all the UX in antd's components, so just customize with code.

**Comment by neekey** [comment]
fair enough.

Anyway, I created an HOC component to implement this, just in case anyone needs it:

```js
import React from 'react';
import PropTypes from 'prop-types';
import { Form } from 'antd';
const FormItem = Form.Item;

export default function EnhancedFormItem(
  { fieldName, showErrorOnlyTouched, neverShowError, ...props }, { form }) {
  if (neverShowError) {
    return (<FormItem
      {...props}
      help=""
      validateStatus="" />);
  }

  if (showErrorOnlyTouched) {
    const { getFieldError, isFieldTouched } = form;
    const isTouched = isFieldTouched(fieldName);
    const fieldError = getFieldError(fieldName);
    const shouldShowError = isTouched && !!fieldError;
    return (<FormItem
      {...props}
      help={shouldShowError ? fieldError : ''}
      validateStatus={shouldShowError ? 'error' : ''} />);
  }
  return <FormItem {...props} />;
}

EnhancedFormItem.propTypes = {
  fieldName: PropTypes.string,
  showErrorOnlyTouched: PropTypes.bool,
  neverShowError: PropTypes.bool,
};

EnhancedFormItem.contextTypes = {
  form: PropTypes.object,
};

```

**Comment by Kamahl19** [comment]
Hi @benjycui in the context, there is no form property after upgrading to antd3-rc3, is there any way to access form in the above solution (EnhancedFormItem) except passing it as a prop?

**Comment by benjycui** [comment]
@Kamahl19 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by BenevidesLecontes** [comment]
Hi @benjycui why `isFieldTouched` doesn't work like in Angular, when i focus to input for the first time the field stays as untouched, only when i focus out it change to touched and stays as touched. But in ant design forms fields change to touched soon i focus to the field. See this Angular example https://stackblitz.com/angular/pxgvpvqkbymm

**Comment by agustif** [comment]
This is somewhat old bbut I found an official example in the login form in the docs to get this

https://ant.design/components/form/#components-form-demo-normal-login
