### ISSUE TITLE
Add autoAdjustOverflow to slider tooltip

### ISSUE THREAD

**Issue by shanpig** [ant-design/ant-design#43743]
### What problem does this feature solve?

Slider component has a tooltip props that renders a custom tooltip, but there is a basic styling problem that is solved by `autoAdjustOverflow` prop in Tooltip but not in SliderTooltip

### What does the proposed API look like?

add autoAdjustOverflow to SliderProps.tooltip

**Comment by zombieJ** [comment]
`autoAdjustOverflow` is default set to `true`. Could you help provide the reproduce that Tooltip break in Slider?

**Comment by shanpig** [comment]
@zombieJ My problem is actually hoping that i can set `autoAdjustOverflow` to false 🙏

**Comment by zombieJ** [comment]
Thx. Got it.
