### ISSUE TITLE
Fix InputNumber "formatter" prop

### ISSUE THREAD

**Issue by artrn-nt** [ant-design/ant-design#43759]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/high-precision-decimals-antd-5-7-2-forked-jzhdsv?file=/demo.tsx)

### Steps to reproduce

With `InputNumber` default value set to `100` and the formatter prop set as `formatter={(value) => `${value}`.replace(/\./g, "")}`:

1. Add `.1` to the default value to get `1001` displayed in the `InputNumber` (don't forget the `.`)
2. Now click on the increase value button (arrow up)

### What is expected?

At step 1 (before clicking the increase value button):

- **Displayed value** should be updated from `100` to `1001` (OK)
- `InputNumber` **actual value** should be `1001`

At step 2 (after clicking the increase value button):

- **Displayed value** and **actual value** should be updated from `1001` to `1002`

### What is actually happening?

At step 1 (before clicking the increase value button):

- **Displayed value** is updated from `100` to `1001` (OK)
- `InputNumber` **actual value** is `100.1`

Why is there a decorrelation between what we see - displayed value - and the `InputNumber` actual value?

At step 2 (after clicking the increase value button):

- **Displayed value** jumps from `1001` to `1011`
- `InputNumber` **actual value** is `101.1`

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | 17.0.2 |
| System | macOS Monterey version 12.2.1 |
| Browser | Chrome Version 114.0.5735.198 (Build officiel) (arm64) |

---
Issue context: I would like to prevent the user to use float numbers in an `InputNumber`, so for that I use the formatter prop and prevent the user to use `.` character inside this input.

Note: in the demo, because of an error appearing when React is set to 17.0.2, it has been set to 18.2.0

**Comment by zombieJ** [comment]
When you set `defaultValue` to `100.1`, the actual value should be `100.1` not `1001`.  `formatter` only replace the output of InputNumber. What you need is use `parser` & `formatter` to pare work to handle input & output logic.

**Comment by artrn-nt** [comment]
Hi.

I see. Thank you for the explanation.
