### ISSUE TITLE
Carousel组件当children里面只有一个节点时，style的width失效

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#43750]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-2-forked-sq7qd2?file=/demo.tsx:506-565)

### Steps to reproduce

把里面包裹的div删掉一个，宽度变成了撑满全屏，而不是400px

### What is expected?

宽度为400px

### What is actually happening?

宽度为100%

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by MuxinFeng** [comment]
确实诶，我跟下吧~

**Comment by DY-ZYQ** [comment]
再补充一个这个组件的 bug 。swipeToSlide没有用，这是沙盒https://codesandbox.io/s/ji-ben-antd-5-7-2-forked-3y5wqt?file=/demo.tsx:481-493，这是react-slick的官方示例https://react-slick.neostack.com/docs/example/swipe-to-slide @MuxinFeng

**Comment by MuxinFeng** [comment]
react-slick 要发个版吗

**Comment by afc163** [comment]
https://github.com/ant-design/react-slick/releases/tag/v1.0.2
