### ISSUE TITLE
Carousel组件 swipeToSlide 属性失效，不能再pc端用鼠标进行滑动

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#43757]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-2-forked-3y5wqt?file=/demo.tsx)

### Steps to reproduce

尝试用鼠标滑动轮播图

### What is expected?

可以进行滚动

### What is actually happening?

不能进行滚动

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

---
https://react-slick.neostack.com/docs/example/swipe-to-slide，react-slick官方示例是可以的

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28086#issuecomment-736203518

**Comment by DY-ZYQ** [comment]
> [#28086 (comment)](https://github.com/ant-design/ant-design/issues/28086#issuecomment-736203518)

有办法实现触控板左右滑动切换吗

**Comment by afc163** [comment]
> 有办法实现触控板左右滑动切换吗

目前没办法。
