### ISSUE TITLE
watermark的默认颜色应该从design token中获取，现在darkmode几乎不可见

### ISSUE THREAD

**Issue by tonny008** [ant-design/ant-design#43752]
### Reproduction link

[https://ant.design/components/watermark-cn](https://ant.design/components/watermark-cn)

### Steps to reproduce

switch to dark mode

### What is expected?

watermark content visible

### What is actually happening?

watermark content 颜色明显几乎不可见

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18 |
| System | mac |
| Browser | chrome 106 |

**Comment by li-jia-nan** [comment]
确实
