### ISSUE TITLE
Ant Design中 Tooltip 组件的 arrow 属性设置根本不生效，反而4.x的arrowPointAtCenter属性会起作用，特别是内容很少或者只是一个icon的时候，很明显的可以看出区别

### ISSUE THREAD

**Issue by bfyq** [ant-design/ant-design#43760]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-1-forked-28tsyx?file=/demo.tsx)

### Steps to reproduce

使用 Tooltip 组件，把内容变短，例如下面代码：
<Tooltip 
    title="prompt text" 
    placement="bottomLeft" 
    arrow={true}
    // arrowPointAtCenter={true}
  >
    <span>aa</span>
  </Tooltip>
分别使用 arrow， arrowPointAtCenter 属性，查看相关效果，会发现，生效的是之前的属性arrowPointAtCenter
备注：上面的链接可能没有个人保存，会失效，但是复现真的特别简单

### What is expected?

使用最新的arrow属性，箭头对齐内容

### What is actually happening?

使用最新的arrow属性，箭头偏移了，未能对齐，使用4.x的属性反而可以对齐

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.x |
| System | mac 12.1 |
| Browser | 114.0.5735.198 |

**Comment by afc163** [comment]
等效的写法是下面这样的。是具体我们哪里的文档描述不够准确，让你误解了呢？能否指出一下我们修改修改。

```diff
- arrowPointAtCenter
+ arrow={{ pointAtCenter: true }}
```

https://codesandbox.io/s/ji-ben-antd-5-7-1-forked-28tsyx?file=/demo.tsx

**Comment by zombieJ** [comment]
https://codesandbox.io/s/ji-ben-antd-5-7-1-forked-mkyf6y?file=/demo.tsx:178-214

**Comment by afc163** [comment]
<img width="670" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/a7902991-7ef9-41de-aaec-373b203e9853">

这个 warning 没写好，我来改改。

**Comment by bfyq** [comment]
> 
sorry, 我的，理解错误了，我看到 boolean类型 and default value 是true, 我误以为这样会工作，导致我以为这个属性不会生效

**Comment by bfyq** [comment]
> <img alt="图片" width="670" src="https://user-images.githubusercontent.com/507615/255554950-a7902991-7ef9-41de-aaec-373b203e9853.png">
> 这个 warning 没写好，我来改改。

thank you very much

**Comment by bfyq** [comment]
> https://codesandbox.io/s/ji-ben-antd-5-7-1-forked-mkyf6y?file=/demo.tsx:178-214

收到，我的锅，对用法理解错误了
