### ISSUE TITLE
Popover位置错误，弹出到可视范围外面

### ISSUE THREAD

**Issue by kyle-go** [ant-design/ant-design#43769]
### Reproduction link

[https://github.com/kyle-go/antd-popover-position](https://github.com/kyle-go/antd-popover-position)

### Steps to reproduce

yarn start 允许我提供的URL仓库，点击Readme图片中的红色圆圈位置（注意点击之前，需要先往下拉一点点滚动条）

### What is expected?

自动调节popover位置，不要有任何遮挡

### What is actually happening?

popover弹窗有遮挡

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2.0 |
| System | macOS 13.4.1 (c)  |
| Browser | Chrome |

**Comment by kyle-go** [comment]
可以直接用下面代码运行：
```
function App() {
    const renderProfile = () => {
        return (
            <div
                style={{
                    width: 280,
                    height: 535,
                    backgroundColor: 'gainsboro',
                }}
            >
                aaaaaaaaaaaaa
            </div>
        );
    }

    const renderPopover = (i: number) => {
        const ccc = (i + 15) * 5;
        return <Popover
            key={i}
            placement={'rightBottom'}
            content={renderProfile()}
            trigger="click"
            destroyTooltipOnHide={true}
            getPopupContainer={() => document.getElementById('root') as HTMLElement }
        >
            <div
                style={{width: 136, height: 136, backgroundColor: `rgb(${ccc},${ccc}, ${ccc})`}}
            >{i}</div>
        </Popover>
    }

    const items = [];
    for (let i = 0; i < 20; i++) {
        items.unshift(renderPopover(i));
    }

    return (
        <div className="App">
            {items}
        </div>
    );
}


// 查看图片
https://github.com/kyle-go/antd-popover-position/blob/main/bug-pic.png

![](https://github.com/kyle-go/antd-popover-position/blob/main/bug-pic.png)

**Comment by zombieJ** [comment]
可以换成 `placement=right`，当你设置为 `rightBottom` 这类固定位置的时候，它会强制按照你设置的逻辑来。如果是需要自适应，直接告知一个大致方向即可：

https://github.com/ant-design/ant-design/assets/5378891/a6545471-bcbd-417a-a72b-7bde06bbb335


文档要加一个说明。

**Comment by kyle-go** [comment]
> 可以换成 `placement=right`，当你设置为 `rightBottom` 这类固定位置的时候，它会强制按照你设置的逻辑来。如果是需要自适应，直接告知一个大致方向即可：
> 
>  Kapture.2023-07-25.at.10.05.46.mp4 
> 文档要加一个说明。

感谢大佬，原来right这种会自适应位置，rightBottom这种就不会自适应。 非常感谢。

**Comment by zombieJ** [comment]
嗯，我更新一下文档说明。
