### ISSUE TITLE
引入antd后，safari浏览器无法打开页面

### ISSUE THREAD

**Issue by hitzzc** [ant-design/ant-design#4376]
#### 发生问题的环境是

- antd 版本: 2.5.3
- 操作系统及其版本: OS X Yosemite 10.10.5
- 浏览器及其版本: Safari 8.0.8

#### 您做了什么？请提供尽可能详细的重现步骤。
根据官网的：https://ant.design/docs/react/use-with-create-react-app-cn 一步步做下来。

#### 您期待的结果是:
在safari显示出button

#### 实际上的结果是:
safari无法显示，输出的error是：TypeError: undefined is not a function (evaluating 'query.startsWith(name)')
firefox和chrome无error log, 正常输出结果
实际上，引用官网的这个步骤，是为了能重现问题。我自己写的code里，只要引入antd，在safari里就会出现这个error。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3400#issuecomment-253181445
