### ISSUE TITLE
在 iframe 中，将 Modal 挂到宿主 HTML 中， Modal 中的 Select 下拉框位置不正确

### ISSUE THREAD

**Issue by AmAzing129** [ant-design/ant-design#43787]
### Reproduction link

https://github.com/AmAzing129/antd-select-bug

### Steps to reproduce

1. 创建一个主 html 页面
2. 在 html 页面中引入 iframe
3. iframe 中的 app 通过 getPopupContainer 将 Modal 组件挂载到宿主页面，如 window.parent.document.body
4. 此时在 Modal 中如果使用 Select 组件，下拉框将无法正确显示，始终显示在其 container 左上角，而不是 Select 下方

注：iframe 不方便复现，最小复现为正常 Select，在 iframe 中无法使用

### What is expected?

Select 组件正常显示使用

### What is actually happening?

Select 组件下拉框丢失

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18 |
| System | Apple M1 13.4.1  |
| Browser | Chrome |

---
下拉选项疑似与 Select 的相对位置计算出错，样式始终为 inset: 0px auto auto 0px，下图将 container 设置为 modal 组件
![image](https://github.com/ant-design/ant-design/assets/115673583/4b2cec0c-4c5d-4a59-b7a5-fa43c7001280)

**Comment by MadCcc** [comment]
确定是 5.x 么

**Comment by zombieJ** [comment]
codesandbox 不方便的话可以做一个 github repo 哈~

**Comment by AmAzing129** [comment]
> 

5.6.4

**Comment by AmAzing129** [comment]
> codesandbox 不方便的话可以做一个 github repo 哈~

好的，稍等

**Comment by AmAzing129** [comment]
https://github.com/AmAzing129/antd-select-bug
用 umi 跑了两个项目，一个是宿主，一个是 iframe 嵌入，嵌入的是一个 Modal，其中包含有 Select
辛苦大佬看下
@zombieJ @MadCcc

**Comment by AmAzing129** [comment]
> ### Reproduction link
> https://github.com/AmAzing129/antd-select-bug
> 
> ### Steps to reproduce
> 1. 创建一个主 html 页面
> 2. 在 html 页面中引入 iframe
> 3. iframe 中的 app 通过 getPopupContainer 将 Modal 组件挂载到宿主页面，如 window.parent.document.body
> 4. 此时在 Modal 中如果使用 Select 组件，下拉框将无法正确显示，始终显示在其 container 左上角，而不是 Select 下方
> 
> 注：iframe 不方便复现，最小复现为正常 Select，在 iframe 中无法使用
> 
> ### What is expected?
> Select 组件正常显示使用
> 
> ### What is actually happening?
> Select 组件下拉框丢失
> 
> Environment	Info
> antd	5.7.3
> React	18
> System	Apple M1 13.4.1
> Browser	Chrome
> 下拉选项疑似与 Select 的相对位置计算出错，样式始终为 inset: 0px auto auto 0px，下图将 container 设置为 modal 组件 ![image](https://user-images.githubusercontent.com/115673583/255825714-4b2cec0c-4c5d-4a59-b7a5-fa43c7001280.png)

已增加复现仓库

**Comment by MadCcc** [comment]
复现仓库中没有 iframe 呀

**Comment by AmAzing129** [comment]
> 复现仓库中没有 iframe 呀

宿主应用是 parent 下的 umi 项目，子应用是外层的
在宿主应用中，parent/src/pages/index.tsx

![image](https://github.com/ant-design/ant-design/assets/115673583/a84f5064-b443-4c45-a485-3663d4cb9624)

**Comment by AmAzing129** [comment]
@zombieJ 辛苦确认下？已增加复现，可以去掉 Need Reproduce 标签

**Comment by AmAzing129** [comment]
@zombieJ @yoyo837 @MadCcc @jhsu 
辛苦大佬们先帮忙定位下？这个问题我们这边有点紧急 ><

**Comment by yoyo837** [comment]
并不太建议这样用吧? 还不如js通信后让宿主页面来弹出内容呢?

**Comment by AmAzing129** [comment]
> 并不太建议这样用吧? 还不如js通信后让宿主页面来弹出内容呢?

1. 目前宿主和iframe是两个项目，相互独立，所以需求上不太好混杂

2. 抛开使用，不知道这个是否算实现bug，因为把元素/组件挂出去的场景是存在的，比如 cssinjs 提供了 container 属性，这里是否是 Select 类组件自身样式逻辑问题？

**Comment by afc163** [comment]
> 并不太建议这样用吧? 还不如js通信后让宿主页面来弹出内容呢?

建议 iframe 之间通过 postMessage 交互，只做通信。

**Comment by zibuyu28** [comment]
the same problem  :(

**Comment by yoyo837** [comment]
目前antd在实现时并没有考虑这种场景, 部分场景能用只是巧合.

**Comment by AmAzing129** [comment]
为什么关闭呢？问题是真实存在的，如果是场景问题，建议更新文档，毕竟 issue 下也有很多 iframe 的问题

**Comment by afc163** [comment]
还是建议 iframe 之间用 postMessage 通信，再调用对应页面的 antd 实例。

**Comment by wusfe** [comment]
> 为什么关闭呢？问题是真实存在的，如果是场景问题，建议更新文档，毕竟 issue 下也有很多 iframe 的问题

same problem 🤔
你解决了吗

**Comment by AmAzing129** [comment]
> > 为什么关闭呢？问题是真实存在的，如果是场景问题，建议更新文档，毕竟 issue 下也有很多 iframe 的问题
> 
> same problem 🤔 你解决了吗

没有，最后用的 postMessage
