### ISSUE TITLE
notification description 描述的组件前缀不会被修改

### ISSUE THREAD

**Issue by JSP-Sliver** [ant-design/ant-design#43783]
### Reproduction link

[https://ant.design/components/notification-cn](https://ant.design/components/notification-cn)

### Steps to reproduce

umi框架搭建的应用，在配置了prefix前缀后，发现如果这种使用方式前缀不会被修改
notification.success({
        description: (<Button>hello world</Button>),
        duration: 0
    })
内部的Button的前缀还是原始的antd前缀
但是notification的前缀及其他的不在notification的组件前缀都可以被正常修改

修改前缀方式：
ConfigProvider.config({})
修改less变量
<ConfigProvider prefix="***"></ConfigProvider>

### What is expected?

Button的前缀会被一起更改

### What is actually happening?

notification的Button的前缀不会被修改

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 17.0 |
| System | macos Ventura 13.14.1 |
| Browser | chrome 版本 114.0.5735.198（正式版本） (arm64) |

**Comment by afc163** [comment]
https://ant.design/components/notification-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-notification-%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-contextredux-%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-configprovider-%E7%9A%84-localeprefixclstheme-%E7%AD%89%E9%85%8D%E7%BD%AE
