### ISSUE TITLE
DatePicker的周选择器 选中的value会在不同年份的相同日期会再次选中

### ISSUE THREAD

**Issue by a987607481** [ant-design/ant-design#43790]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r4pwfg?file=/index.tsx)

### Steps to reproduce

选择周后，切换年份，发现不同年份的周选择会被选上

### What is expected?

仅应突出显示当年的本周

### What is actually happening?

每年选择的同一周都会突出显示

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18 |
| System | win10 |
| Browser | chrome |

---
antd4.0版本之前也有这个问题，但是后续4.0版本已经修复，但是5.0版本又出现了同样的问题
https://github.com/ant-design/ant-design/issues/31782

这是5.0版本，会出现不同年份但是同一月份的周会重复赋值问题：
![5 0周选择器](https://github.com/ant-design/ant-design/assets/52713259/f6819a94-5c15-470b-b4c1-9c5bd3f1eddc)
这是4.0版本，已经修复了这个问题：
![4 0周选择器](https://github.com/ant-design/ant-design/assets/52713259/a352a5cd-6438-4ecf-8905-9f6f4495e53c)

**Comment by xieli08** [comment]
遇到同样的问题，麻烦尽快解决，急啊，要上线下

**Comment by yoyo837** [comment]
Duplicate of #31782

**Comment by a987607481** [comment]
> Duplicate of #31782

4.0版本的antd这个问题已经解决了，但是antd5.0版本这个问题又出现了

**Comment by yoyo837** [comment]
已经处理好了

**Comment by a987607481** [comment]
> 已经处理好了

你确定你看的是antd5.0版本吗？我刚刚去官网看这个问题还是存在，只有4.0版本才不会出现这个问题

**Comment by yoyo837** [comment]
搞错了, 等待 https://github.com/ant-design/ant-design/pull/43476, 应该要下一个minor版本发布了.

**Comment by a987607481** [comment]
> 搞错了, 等待 #43476, 应该要下一个minor版本发布了.
恩，好的，谢谢
