### ISSUE TITLE
Module not found: Error: Can't resolve 'antd/es/q-r-code' in 'xxx/src'

### ISSUE THREAD

**Issue by liboliang01** [ant-design/ant-design#43795]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zywl6n?file=/index.tsx)

### Steps to reproduce

npm run build后报错
Module not found: Error: Can't resolve 'private-antd-v5/es/q-r-code' in '/xxxx/src'

### What is expected?

我看二维码的文件夹叫qr-code，但是打包的时候找的是q-r-code

### What is actually happening?

npm run build后报错
Module not found: Error: Can't resolve 'private-antd-v5/es/q-r-code' in '/xxxx/src'

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2 |
| System | macOS 12.5 |
| Browser | Chrome113.0.5672.126 |

**Comment by liboliang01** [comment]
已经修改啦，麻烦再看下～

**Comment by afc163** [comment]
@liboliang01 我看 codesandbox 里没有报错？

**Comment by liboliang01** [comment]
@afc163 我又更新了下仓库。npm run build之后就会报错
![image](https://github.com/ant-design/ant-design/assets/55911020/898f7707-7292-4ba0-bdf5-3f101892548c)

**Comment by blackcai** [comment]
你这个 bug fix 导致了一个新的问题，比如：VXETable 转出了和上一个版本不同的结果，从而导致项目报错了。
