### ISSUE TITLE
style 标签被删除

### ISSUE THREAD

**Issue by powerdong** [ant-design/ant-design#43804]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ks6t3p)

### Steps to reproduce

antd 5在使用 css in js 方案下，会自己删除head 标签下的 style 标签，不过按照 https://ant.design/docs/react/customize-theme-cn#%E8%B0%83%E8%AF%95%E4%B8%BB%E9%A2%98 这个包的描述来看 autoclear 默认为false ，不知道是不是自己使用姿势问题。辛苦看到回复一下

### What is expected?

期望antd不自行删除style标签

### What is actually happening?

自己会删除

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18 |
| System | Mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
同一个 hash 下的组件样式是不会删除的，但是如果当前 hash 没有组件使用就会把整个 hash 相关的样式全部移除

**Comment by powerdong** [comment]
现在我们线上是出现这个情况
我们一个系统，多个组件，每个组件都有自己的antd（源码打入
就出现了antd把自己的style删掉的情况，我尝试给组件加上autocleaer false 也不好使

**Comment by zombieJ** [comment]
重现看起来没问题，操作步骤是什么？

**Comment by zombieJ** [comment]
可以给个 repo 看看，我们业务里也是这么用的，style 按理说不应该会删除才对。需要确认一下是什么逻辑走过去的。autoClear 默认是 false 是不会跑到的。

**Comment by powerdong** [comment]
@zombieJ 那有个小疑问哈，  我在这个沙盒里边  打开form modal 的时候style标签数量 是 17  关闭modal 就成 16了  这个逻辑有办法关掉吗？ autoclear 不是作用于这个的么？

**Comment by zombieJ** [comment]
autoClear 这个功能没有完成，所以是默认是关闭的。你没有配置的话它是不会去删标签的。所以我说需要搞个 repo 看看具体原因。
当然你也可以 fork `@ant-design/cssinjs` 然后把所有 removeCSS 的方法注释掉，然后 webpack alias 到你自己的 cssinjs 库。这样就不会删除了。但是这对于动态主题而言就会不断累加 style 标签，不是一个正常的状态。就如上面提到的，仅仅是把删除 style 去掉这个只是隐藏问题。可能会遇到更大的坑。

**Comment by zombieJ** [comment]
另外你到的 沙盒 是什么？qiankun 么？

**Comment by powerdong** [comment]
这个 https://codesandbox.io/s/ks6t3p?file=/demo.tsx  @zombieJ

**Comment by zombieJ** [comment]
> 这个 https://codesandbox.io/s/ks6t3p?file=/demo.tsx

这个没有错哈，打开 modal 的时候加了一个锁定 body 滚动的 css。关闭 modal 的时候删除以恢复滚动，这个是预期的：

<img width="865" alt="截屏2023-07-25 23 31 23" src="https://github.com/ant-design/ant-design/assets/5378891/3ff30e99-0e58-4842-970a-bec3b064c946">

**Comment by powerdong** [comment]
> autoClear 这个功能没有完成，所以是默认是关闭的。你没有配置的话它是不会去删标签的。所以我说需要搞个 repo 看看具体原因。
> 当然你也可以 fork `@ant-design/cssinjs` 然后把所有 removeCSS 的方法注释掉，然后 webpack alias 到你自己的 cssinjs 库。这样就不会删除了。但是这对于动态主题而言就会不断累加 style 标签，不是一个正常的状态。就如上面提到的，仅仅是把删除 style 去掉这个只是隐藏问题。可能会遇到更大的坑。

感谢  get  我也是今天debug找到内部remove的逻辑  我明天再看看  辛苦啦

**Comment by powerdong** [comment]
> > 这个 https://codesandbox.io/s/ks6t3p?file=/demo.tsx
> 
> 这个没有错哈，打开 modal 的时候加了一个锁定 body 滚动的 css。关闭 modal 的时候删除以恢复滚动，这个是预期的：
> 
> <img alt="截屏2023-07-25 23 31 23" width="865" src="https://user-images.githubusercontent.com/5378891/255952807-3ff30e99-0e58-4842-970a-bec3b064c946.png">

老哥  我排查下来 这个方法的执行导致我的样式错乱
![image](https://github.com/ant-design/ant-design/assets/45968889/6ec08647-68f2-4939-8968-34b666817e0c)

抱歉内部项目不能提供合适的 demo，我想问一下这里如果我想临时性fix有什么办法么？
这个系统马上也要迁移了🌚

**Comment by zombieJ** [comment]
`会有其他什么问题么` 就是这个：

> 当然你也可以 fork @ant-design/cssinjs 然后把所有 removeCSS 的方法注释掉，然后 webpack alias 到你自己的 cssinjs 库。这样就不会删除了。但是这对于动态主题而言就会不断累加 style 标签，不是一个正常的状态。就如上面提到的，仅仅是把删除 style 去掉这个只是隐藏问题。可能会遇到更大的坑。
