### ISSUE TITLE
Components appearing in Chinese by default

### ISSUE THREAD

**Issue by MicroDroid** [ant-design/ant-design#4380]
I use npm as my JS package manager, and I use Webpack with it. React is the JS framework I use as well.

The problem is that I did `npm install antd`, and `import`ed a component and rendered it as such:

```
import DatePicker from 'antd/libs/date-picker';

ReactDOM.render(<DatePicker />, document.getElementById('app'));
```

The issue is that the widget appears to be all Chinese. What can I do to make it English? and make it default to always be English?

**Comment by ddcat1115** [comment]
You can use [LocaleProvider](https://ant.design/components/locale-provider/) to localize the built-in text of components, the English locale package is already available.
