### ISSUE TITLE
Popconfirm组件okButtonProps loading动态为true时按钮换行，没有自动撑开

### ISSUE THREAD

**Issue by asd116725** [ant-design/ant-design#43816]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-9q34mw?file=/index.js)

### Steps to reproduce

点击页面右边通过按钮，Popconfirm弹出后点击handle loading,会发现loading的按钮被挤到下一层，而不是水平撑开

### What is expected?

okButtonProps={{ loading }} loading动态不会影响按钮的水平方向排版

### What is actually happening?

okButtonProps={{ loading }} loading为true时候, okButton会往下换行

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2.0 |
| System | macos13.4 (22F66) |
| Browser | chrome 115.0.5790.114（正式版本） (arm64) |

**Comment by asd116725** [comment]
> 
加了 overlayStyle={{ whiteSpace: 'nowrap' }} 可以解决


> 没能复现😱，是已经修复了吗

**Comment by MuxinFeng** [comment]
复现出来啦，我改下~
