### ISSUE TITLE
Error: Declaration generation failed.

### ISSUE THREAD

**Issue by liboliang01** [ant-design/ant-design#43815]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-69fmhk?file=%2Fsrc%2Findex.tsx%3A15%2C39)

### Steps to reproduce

npm run build 后报错：Error: Declaration generation failed.    
产生原因：tsconfig.json配置compilerOptions.declaration = true

### What is expected?

打包后生成.d.ts声明文件

### What is actually happening?

无法生成.d.ts声明文件

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2 |
| System | macOS 12.5 |
| Browser | Chrome113.0.5672.126 |

**Comment by zombieJ** [comment]
<img width="560" alt="截屏2023-07-26 14 15 28" src="https://github.com/ant-design/ant-design/assets/5378891/c6341283-6b93-49f3-b84d-037a46b6ed9f">

**Comment by liboliang01** [comment]
![image](https://github.com/ant-design/ant-design/assets/55911020/6e7a4203-23ce-445f-9fe3-081d32353ce1)
太怪了，我啥都没改，第一次会报错，第二次就不报错了

**Comment by liboliang01** [comment]
![image](https://github.com/ant-design/ant-design/assets/55911020/bc146db5-a974-4958-b27f-867bed78330b)
另外麻烦看一下编辑器里的报错

**Comment by MadCcc** [comment]
试试这样？
![image](https://github.com/ant-design/ant-design/assets/27722486/010a4695-b2fa-4a28-b633-44476a825a32)

**Comment by liboliang01** [comment]
> 试试这样？ ![image](https://user-images.githubusercontent.com/27722486/256162856-010a4695-b2fa-4a28-b633-44476a825a32.png)

感谢，这样可以解决目前的问题
