### ISSUE TITLE
鼠标划出划入页面时，Dropdown的Menu会自动复现

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#43813]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-6-3-forked-s7pt5d?file=/demo.tsx)

### Steps to reproduce

创建DropDown的menu时，使用Model 按钮的组合，在鼠标划出划入页面时
（我直接引入了ModalForm，自己实现A标签 一个Modal也是同理）

### What is expected?

下拉不要自动浮现

### What is actually happening?

下拉自动浮现

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18 |
| System | Win11 |
| Browser | 谷歌 |

**Comment by Wxh16144** [comment]
和 https://github.com/ant-design/ant-design/issues/43527 问题类似, 我在你提供的 codeSandbox 上面调整了一下: https://codesandbox.io/s/ji-ben-antd-5-6-3-forked-48yvpt?file=/demo.tsx 鼠标移入不会出现问题. 但是出现新的问题了

### 你提供的 codebox


https://github.com/ant-design/ant-design/assets/32004925/e705c0be-3e42-42ed-a2b5-71ee6ed147bd



### 我提供的 codebox
> 解决你描述的鼠标移入问题, 但是出现一个新问题: 点击 modal 顶部会关闭然后又打开 modal


https://github.com/ant-design/ant-design/assets/32004925/a61216ca-7b18-420f-94c3-148d651c9b6e

CC @zombieJ

**Comment by zombieJ** [comment]
奇怪，这个应该是修过了的。感觉是哪里漏进去了

**Comment by phoema** [comment]
我们将很多组件封装了触发器，这个问题影响面还是挺广的。
antd 5.3.2没有此问题，可以#43813对应再现的版本替换

**Comment by zombieJ** [comment]
确认了一下，`@rc-component/trigger` 最新版本是好的。提升一下依赖哈~

https://codesandbox.io/s/ji-ben-antd-5-6-3-forked-6ck77k?file=/demo.tsx
