### ISSUE TITLE
Color Picker color change completed callback not working when manually writing hex code

### ISSUE THREAD

**Issue by bamtheboozle** [ant-design/ant-design#43819]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y9zkxh)

### Steps to reproduce

open color picker, manually write a hex code -> color change completed callback is not called. the color does not get changed.

this works if not using the callback

### What is expected?

color should be changed

### What is actually happening?

color is not changed

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

**Comment by SnowingFox** [comment]
i want to fix this

**Comment by b5414** [comment]
same `"antd": "^5.16.1",`
