### ISSUE TITLE
datepick 时间错误 

### ISSUE THREAD

**Issue by noonnightstorm** [ant-design/ant-design#4381]
antd版本: 1.6.5
系统：Mac OS X 10.10.3
浏览器：chrome  55.0.2883.95 (64-bit)

用法：
`<DatePicker
              style={{width:"100%"}}
              showTime
              format="YYYY-MM-DD HH:mm:ss"
              placeholder="请选择最近更新时间"
            />`

选择时间时候value错误：
![lalolorups0dpm0ftg_1358_828](https://cloud.githubusercontent.com/assets/1336049/21512091/da40a5d8-cce3-11e6-8bec-d9e67448d6a3.png)

我console了组件里面change方法返回的value（发觉field里面有点奇怪）：
![lalolorvbm0dom0csa_688_824](https://cloud.githubusercontent.com/assets/1336049/21512105/0cd92ace-cce4-11e6-885c-9f1b2278a01f.png)

**Comment by ddcat1115** [comment]
我猜你看的 2.X 的文档...

**Comment by noonnightstorm** [comment]
@ddcat1115 是的 果然，修改下format就好了，谢谢。
`format="yyyy-MM-dd HH:mm:ss"`
