### ISSUE TITLE
在移动端使用form.item时，将label的before去掉，加上after，当label文字非常长达到换行时，*就会在两行中间。怎么使*保持在文字后面显示（除了给label赋值为一个reactNode外，还有啥方法吗）

### ISSUE THREAD

**Issue by rb05180518** [ant-design/ant-design#43826]
### Reproduction link

[https://ant.design/components/form-cn#components-form-demo-layout-can-wrap](https://ant.design/components/form-cn#components-form-demo-layout-can-wrap)

### Steps to reproduce

在移动端使用form.item时，将label的before去掉，加上after，当label文字非常长达到换行时，*就会在两行中间。怎么使*保持在文字后面显示（除了给label赋值为一个reactNode外，还有啥方法吗）

### What is expected?

立刻解决，*紧贴在文字后面

### What is actually happening?

*不能紧跟在文字后面

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18以上 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
给个重现看看，这么讲不知道是什么样子的哈~

**Comment by rb05180518** [comment]
现在是这个样：<img width="747" alt="image" src="https://github.com/ant-design/ant-design/assets/107897569/aee6dc45-427d-48c4-86ea-4750adffde93">
我想要成为这样：
<img width="738" alt="image" src="https://github.com/ant-design/ant-design/assets/107897569/ddd8855a-20c4-4efe-9cbb-3dfab6c11c1c">

**Comment by rb05180518** [comment]
> 给个重现看看，这么讲不知道是什么样子的哈~

麻烦看下
