### ISSUE TITLE
V4 Theme documentation improvement

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#43827]
- [x] 在[升级文档](https://ant.design/docs/react/migration-v5-cn)里没有提供使用 v4 主题包（包括 wireframe 的使用），也没有相关指引，让用户可以选择尽量少更改样式的升级方式。
- [x] [定制主题](https://ant.design/docs/react/customize-theme-cn#%E4%B8%BB%E9%A2%98%E5%B1%95%E7%A4%BA) 里的 v4 主题包链接错误，正确的链接是 https://ant-design.github.io/antd-token-previewer/editor/v4-theme
- [x]  https://ant-design.github.io/antd-token-previewer/editor/v4-theme 里没有应用 wireframe。
- [x] 首页可以提供 V4 主题的展示。

**Comment by MadCcc** [comment]
定制主题中不再提供 v4 主题包示例，转移到 v4 迁移 v5 文档中提供代码示例。
兼容包中的 v4 主题已更新
