### ISSUE TITLE
form 中  这样  有什么好的解决方式？

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#4383]
<img width="231" alt="111" src="https://cloud.githubusercontent.com/assets/7971419/21515418/6fb05c32-cd0a-11e6-9e33-19004c536dde.png">

**Comment by afc163** [comment]
目前没法解决，建议去掉 hasFeedback。

**Comment by qq645381995** [comment]
如果统一  v 这个图标放在input后面也好 
还有一个问题  就是 如果 input 用了 addonAfter  再用 Row  Col的  span  来做 居中 他判断的还只是input的宽度  不包括后面 addonAfter 的宽度

**Comment by qq645381995** [comment]
<Col span={8} offset={8}>  按理说  是居中的  但是  加上  addonAfter  就不行了

**Comment by qq645381995** [comment]
@afc163   那 span  居中那个问题呢？

**Comment by afc163** [comment]
最好一个问题一个 issue，另附图 + 重现示例。
