### ISSUE TITLE
Statistic component doesn't allow you put custom html inside value={}

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#43830]
### What problem does this feature solve?

```tsx
   <Statistic
            title="Stelle assegnate"
            value={
                <Rate defaultValue={4} />
            }
          />
```

See image here: https://ibb.co/wBvwFBd

![Screenshot 2023-07-26 alle 23 38 50](https://github.com/ant-design/ant-design/assets/40239902/06a6b5dc-31a9-44de-8772-5bc68981c68d)

### What does the proposed API look like?

```tsx
   <Statistic
            title="Stelle assegnate"
            value={
                <Rate defaultValue={4} />
            }
          />
```

**Comment by zombieJ** [comment]
Statistic is not design for custom ReactNode display. But you want so, you can use `formatter` to ignore the `value`:

https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-53pnxr?file=/demo.tsx
