### ISSUE TITLE
希望提供API获取内置status对应的颜色，比如徽标等组件，便于颜色统一

### ISSUE THREAD

**Issue by CDragonTime** [ant-design/ant-design#43840]
### What problem does this feature solve?

Ant Design中没有提供直接的API来获取status对应的颜色

### What does the proposed API look like?

import {StatusColor} from  antd/es/...

**Comment by MadCcc** [comment]
目前可以这样拿到 antd 的预设颜色

```
import {theme} from 'antd';

export default () => {
  const { token } = theme.useToken();

  // token.blue

  return null;
}
```

状态颜色的话也有对应的 token，比如 `colorError` `colorWarning`
