### ISSUE TITLE
<PlusOutlined /> icon looks squished

### ISSUE THREAD

**Issue by lscheibel** [ant-design/ant-design#43850]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-plus-icon-squished-dj9hyh?file=/index.js)

### Steps to reproduce

Open minimal reproduction and measure sizes of the icons. The horizontal bars are sometimes a pixel or two smaller than the vertical bar.
![image](https://github.com/ant-design/ant-design/assets/44374653/cc5ca86f-96aa-495b-bbfe-ea9a33ccf289)

Alternatively, open the plus icon SVG in any vector editor (Figma, etc.) and compare the width of the horizontal bar with the height of the vertical bar.

### What is expected?

The bounding box of the square icon is a square.

### What is actually happening?

The bounding box's width is less than its height.

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | any |
| System | Mac, Windows |
| Browser | Chrome, Firefox |

---
A fix and additional information can be found in this PR: https://github.com/ant-design/ant-design-icons/pull/582

I decided to open an issue in this repository because I'd like to know whether it is realistic that the changes will land. If you decide that this is by design or not worth fixing, please feel free to close this issue and the PR.

**Comment by Wxh16144** [comment]
I think it should be adopted. It's honorable.

**Comment by MadCcc** [comment]
Released in  @ant-design/icons-svg@4.3.1
