### ISSUE TITLE
modal.confirm 中的button 设置全局圆角样式不生效

### ISSUE THREAD

**Issue by xiaoxiaoxiaoge** [ant-design/ant-design#43855]
### Reproduction link

[https://ant.design/components/modal-cn](https://ant.design/components/modal-cn)

### Steps to reproduce

 theme={{
          token: {
            colorPrimary: themeColor,
            borderRadius: 2
          },
          components: {
            Modal: {
              borderRadius: 2
            }
          }
        }}

### What is expected?

modal.confirm中的button圆角为2px

### What is actually happening?

无效 是默认的6px

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 18 |
| System | window |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
<img width="617" alt="截屏2023-07-27 20 40 29" src="https://github.com/ant-design/ant-design/assets/5378891/1162cb29-78ea-4b23-9609-e1cdc220080c">

**Comment by crazyair** [comment]
modal，这个 m 是小写的

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546
