### ISSUE TITLE
Upload 和 Form.Item 组合报错

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#43869]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dian-ji-shang-chuan-antd-5-7-3-forked-3k79qn?file=/demo.tsx)

### Steps to reproduce

Upload 和 Form.Item 组合

### What is expected?

不报错，能拿到 Upload 值

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | React 18 |
| System | WIN11 |
| Browser | Chrome |

![image](https://github.com/ant-design/ant-design/assets/1730277/5293fe93-4fc2-49bf-b718-85b181d437dd)

**Comment by Wxh16144** [comment]
<img width="1175" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/3723af72-2e01-41f3-8e0d-288cd69a5ddb">
