### ISSUE TITLE
Dropdown 和Modal Button组合，打开弹框，快速hover到图标会重新唤起，但去掉modal的destroyOnClose就不会出现这个现象

### ISSUE THREAD

**Issue by lemonlhy** [ant-design/ant-design#43860]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-4pxznq?file=/demo.tsx:604-618)

### Steps to reproduce

1.hover点开弹框
2.快速hover到图标，Dropdown会被重新唤起

### What is expected?

点开后不会被重新唤起

### What is actually happening?

有30%的概率会重新唤起

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.0.0 |
| System | win10 |
| Browser | 谷歌 |

---
modal的destroyOnClose去掉后不会再唤起

**Comment by zombieJ** [comment]
> 快速hover到图标，Dropdown会被重新唤起

这个能录个屏不？我试了一下没效果。不知道是不是不够快

**Comment by lemonlhy** [comment]
录屏链接： 
https://www.loom.com/share/e9bd231205c24ec281b42832b1d21c14?sid=f269cb6b-994b-4ea2-964c-e6a4e0f52cfe

**Comment by lemonlhy** [comment]
> > 快速悬停到图标，下拉会被重新唤起
> 
> 这个能录个屏不？我试了一下没效果。不知道是不是不够快

刷新后再试

**Comment by lemonlhy** [comment]
补充一个场景，点击Open Modal放开按钮时间长一些必现重新唤起下拉（点住不放，隔几秒再放开）。
因为例子弹框简单需要这样操作，业务上弹窗比较复杂，渲染需要一点时间，在业务上正常点击也会必现。
https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-jff433?file=/demo.tsx

**Comment by phoema** [comment]
#43813
试试这个，感觉表现差不太多

**Comment by lemonlhy** [comment]
> #43813 试试这个，感觉表现差不太多

是有点像，移出去hover的已经修好了，点击久一点就出现这个问题在业务这很常见。

**Comment by lemonlhy** [comment]
再补充下场景，模拟业务上有些其他逻辑计算，出现频率很高，不需要长按，正常打开弹框就行。
https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-4z9xk8?file=/demo.tsx

**Comment by lemonlhy** [comment]
https://www.loom.com/share/3dc4224c682c4f1f9f5621feadaf5b76?sid=a976beaa-aefe-489c-a4af-050dce8f7774

**Comment by lemonlhy** [comment]
> > 快速hover到图标，Dropdown会被重新唤起
> 
> 这个能录个屏不？我试了一下没效果。不知道是不是不够快

大佬也看看这个问题，补充了几个场景，不需要手速了

**Comment by lemonlhy** [comment]
> > 快速hover到图标，Dropdown会被重新唤起
> 
> 这个能录个屏不？我试了一下没效果。不知道是不是不够快

@zombieJ  大佬， 目前什么进度，求解决

**Comment by afc163** [comment]
@lemonlhy 试试 antd 5.8.2

**Comment by lemonlhy** [comment]
> @lemonlhy 试试 antd 5.8.2

@afc163  试了 5.8.2 依然有这个问题，https://codesandbox.io/s/ji-ben-antd-5-8-2-forked-npp75j

**Comment by lemonlhy** [comment]
@zombieJ @afc163  这么久这个问题还是不能解决吗

**Comment by iShawnWang** [comment]
antd 4.x 能也解决一波这个问题吗 暂时升不到5.x 
:D

**Comment by Wxh16144** [comment]
> antd 4.x 能也解决一波这个问题吗 暂时升不到5.x :D

应该有点困难吧，底层的  rc-trigger 都重构过了🤔
