### ISSUE TITLE
antd 4.x Image.PreviewGroup 无法获取当前图片的索引

### ISSUE THREAD

**Issue by binz-i** [ant-design/ant-design#43863]
### What problem does this feature solve?

4.x 的版本 Image.PreviewGroup 无法获取当前图片的索引

### What does the proposed API look like?

需要获取图片切换，当前图片的索引

**Comment by Wxh16144** [comment]
feature request?, 貌似 4-stable 已经不接收新功能请求了, 考虑升级 antd5 呗

**Comment by afc163** [comment]
@Wxh16144 是对的。
