### ISSUE TITLE
Button的高度写死了，换行不生效

### ISSUE THREAD

**Issue by 1587315093** [ant-design/ant-design#43877]
### Reproduction link

[https://stackblitz.com/edit/react-xae5ba?file=demo.tsx,index.css](https://stackblitz.com/edit/react-xae5ba?file=demo.tsx,index.css)

### Steps to reproduce

    <Button>
      <div>111</div>
      <div>222</div>
    </Button>

无法自适应高度

![image](https://github.com/ant-design/ant-design/assets/77056991/b88522ec-f46d-446b-b44a-fe6418d1558d)

### What is expected?

自适应

### What is actually happening?

未自适应

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2 |
| System | windows |
| Browser | chorme最新 |

**Comment by MadCcc** [comment]
It is by design. You could customize with `height: auto`

**Comment by 1587315093** [comment]
> It is by design. You could customize with `height: auto`.
> 
> Button 本身就是固定高度的，你可以加上自定义样式 `height: auto`

好吧这样也行，我看button代码里改成minHeight 是不是可以更好
