### ISSUE TITLE
Moment error on DatePicker

### ISSUE THREAD

**Issue by KhushbooTaneja** [ant-design/ant-design#4387]
#### The environment in which the problem occurs is:

- antd Version: 2.5.2
- Operating system and version: OS X Yosemite 10.10.5
- Browser and its version: Google Chrome 55.0.2883.95
- Moment version: tried with 2.17.1, 2.15.2

 **I tried to use ant design datePicker but I am getting the following moment error:**

**Uncaught TypeError: (0 , _moment2.default) is not a function**
    at Function.getDefaultProps (main.js:104096)
    at Object.createClass (vendor.js:43526)
    at Object.<anonymous> (main.js:104063)
    at __webpack_require__ (vendor.js:686)
    at fn (vendor.js:111)
    at Object.<anonymous> (main.js:141960)
    at __webpack_require__ (vendor.js:686)
    at fn (vendor.js:111)
    at Object.<anonymous> (main.js:141896)
    at __webpack_require__ (vendor.js:686)
    at fn (vendor.js:111)
    at Object.<anonymous> (main.js:143082)
    at __webpack_require__ (vendor.js:686)
    at fn (vendor.js:111)
    at Object.<anonymous> (main.js:235112)
    at __webpack_require__ (vendor.js:686)

**I am also getting below warning:**

main.js:138588 [HMR] bundle has warnings:
problems @ main.js:138588
main.js:138590 [HMR] ../ui-web-blocks/node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/tanejakh/OHCM/ui-web-blocks/node_modules/moment/src/lib/locale'
resolve './locale' in '/Users/tanejakh/OHCM/ui-web-blocks/node_modules/moment/src/lib/locale'
  using description file: /Users/tanejakh/OHCM/ui-web-blocks/node_modules/moment/package.json (relative path: ./src/lib/locale)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/tanejakh/OHCM/ui-web-blocks/node_modules/moment/package.json (relative path: ./src/lib/locale)
    using description file: /Users/tanejakh/OHCM/ui-web-blocks/node_modules/moment/package.json (relative path: ./src/lib/locale/locale)
      as directory
        /Users/tanejakh/OHCM/ui-web-blocks/node_modules/moment/src/lib/locale/locale doesn't exist
[/Users/tanejakh/OHCM/ui-web-blocks/node_modules/moment/src/lib/locale/locale]
 @ ../ui-web-blocks/node_modules/moment/src/lib/locale/locales.js 55:12-39
 @ ../ui-web-blocks/node_modules/moment/src/lib/locale/locale.js
 @ ../ui-web-blocks/node_modules/moment/src/moment.js
 @ ../ui-web-blocks/lib/components/datetime/datetime.jsx
 @ ../ui-web-blocks/lib/index.js
 @ ./client/lib/index.js
 @ multi main
(anonymous) @ main.js:138590
main.js:138590 [HMR] ../ui-web-blocks/node_modules/antd/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/tanejakh/OHCM/ui-web-blocks/node_modules/antd/node_modules/moment/src/lib/locale'
resolve './locale' in '/Users/tanejakh/OHCM/ui-web-blocks/node_modules/antd/node_modules/moment/src/lib/locale'
  using description file: /Users/tanejakh/OHCM/ui-web-blocks/node_modules/antd/node_modules/moment/package.json (relative path: ./src/lib/locale)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/tanejakh/OHCM/ui-web-blocks/node_modules/antd/node_modules/moment/package.json (relative path: ./src/lib/locale)
    using description file: /Users/tanejakh/OHCM/ui-web-blocks/node_modules/antd/node_modules/moment/package.json (relative path: ./src/lib/locale/locale)
      as directory
        /Users/tanejakh/OHCM/ui-web-blocks/node_modules/antd/node_modules/moment/src/lib/locale/locale doesn't exist
[/Users/tanejakh/OHCM/ui-web-blocks/node_modules/antd/node_modules/moment/src/lib/locale/locale]
 @ ../ui-web-blocks/node_modules/antd/node_modules/moment/src/lib/locale/locales.js 55:12-39
 @ ../ui-web-blocks/node_modules/antd/node_modules/moment/src/lib/locale/locale.js
 @ ../ui-web-blocks/node_modules/antd/node_modules/moment/src/moment.js
 @ ../ui-web-blocks/node_modules/antd/lib/calendar/index.js
 @ ../ui-web-blocks/node_modules/antd/lib/index.js
 @ ../ui-web-blocks/lib/components/datetime/datetime.jsx
 @ ../ui-web-blocks/lib/index.js
 @ ./client/lib/index.js
 @ multi main
(anonymous) @ main.js:138590

**Comment by ddcat1115** [comment]
Please provide a reproducible demo 

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by KhushbooTaneja** [comment]
When we are trying to integrate this plugin with our project, we get the above error, but separately it's working fine. 
Do you have any information on this moment error "Uncaught TypeError: (0 , _moment2.default) is not a function" ??
Also I get some locale warning, see the above comment for detail.

I doubt it is some version configuration issue ...

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3363#issuecomment-256300626

**Comment by afc163** [comment]
trace on #4491
