### ISSUE TITLE
Cascader value 包含 disabled 项时，交互时存在 UI 和 value 取值错误问题

### ISSUE THREAD

**Issue by Firstsup** [ant-design/ant-design#43870]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-yps6sm?file=/index.js)

### Steps to reproduce

问题1：
        步骤1. 点选 China 或点选 shanghai（使父级变为全选）；
        步骤2. 再次点选 China 或点选 shanghai。
问题2：
        无需操作步骤。
问题3：
        步骤1. 点击组件右侧的叉。

### What is expected?

问题1：步骤1后 beijing 选项的 UI 应该依然为选中态，步骤2后 beijing 应该为选中态，且 value 为 [['China', 'beijing']]；
问题2：China 应为半选态；
问题3：选择框中为 beijing 且 value 不变。

### What is actually happening?

问题1：步骤1后 beijing 选项的 UI 变为未选中态，步骤2后 beijing 为未选中态，且 value 为 []；
问题2：China 为未选中态；
问题3：选择框内容被清空且 value 变为 []。

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2.0 |
| System | macOS Ventura 13.4.1 |
| Browser | Chrome 115.0.5790.114 |

---
问题1在 showCheckedStrategy 为 SHOW_CHILD 下不会发生，仅在 SHOW_PARENT 下会出现，问题2、问题3在两种情况下都会出现。

这些是围绕着 value 值包含 disabled 的项的一些问题，既然 disabled 的项是可以被 value 选中的，那么该项“被禁用且选中”的状态应该维持，值应该保持不变（不随着点选父选项等其他交互发生改变），且按照正常理解，某选项存在子项被选中，该选项就应该为半选态，与子项是否禁用应该独立。

**Comment by zombieJ** [comment]
嗯，`disabled` 是从传导中断开的。这种场景勾选应该是 [china, beijing] 才对。合并成 china 看起来是不太对。

**Comment by Firstsup** [comment]
@zombieJ 但是现在看起来问题2和问题3还没有解决
问题2可能会引起用户的误解（父节点下有被选中的节点，但是父节点却不是半选态，用户可能会忽略下面的节点）
问题3是个比较危险的 bug，能通过 allowClear 的清除按钮把 disabled 且选中的项也取消选中，是不合理的
请问这两个问题您觉得需要修复一下吗？
