### ISSUE TITLE
微信端访问项目，点击div，调接口，弹出modal，当手机网络断开，接口请求失败，页面会报undefined提示message

### ISSUE THREAD

**Issue by wushal** [ant-design/ant-design#43879]
### Reproduction link

[https://mdn-event.test.mudu.tv/event/j1hzgmf10e/watch/5jy5bs](https://mdn-event.test.mudu.tv/event/j1hzgmf10e/watch/5jy5bs)

### Steps to reproduce

排查出应该是antd内部检查到网络出错，给出的undefined提示

### What is expected?

不需要弹窗，提示undefined

### What is actually happening?

网络断开，操作时，会弹出undefined提示message

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 17.0.2 |
| System | ios、windows |
| Browser | 微信浏览器 |

---
业务场景中不会出现undefined的提示，应该是antd组件在网络错误下，做的出错提醒。希望能帮忙给出解决方案，或者给出解释

**Comment by zombieJ** [comment]
截个图看看提示长啥样子，antd 本身不做网络检查。

**Comment by 1587315093** [comment]
盲猜是接口失败后业务自己封装的 message 提示。。。

```js
Promise.reject().catch(()=>message.error('xxxxx'))
```
