### ISSUE TITLE
modal 会让 @ant-design/icons 的样式重复加载导致自定义样式被覆盖

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/ant-design#43884]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-lx4ccd?file=/demo.tsx)

### Steps to reproduce

打开 demo，点击 Button 展开 Dropdown 之后 icon 的颜色会从红色变成黑色

### What is expected?

icon 的样式不会被覆盖

### What is actually happening?

@ant-design/icons 的样式重复加载导致自定义样式被覆盖

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2.0 |
| System | Windows10 |
| Browser | Chrome 99.0.4844.51 |

---
经测试是 Modal 的 forceRender 导致 @ant-design/icons 的样式重复加载

**Comment by MadCcc** [comment]
这个问题是 forceRender 导致 Modal 里的图标样式插入到 body 里了
