### ISSUE TITLE
messsage 全局配置后，路由跳转后没有自动关闭！！！

### ISSUE THREAD

**Issue by leonardo110** [ant-design/ant-design#43885]
### Reproduction link

[https://  公司内网，无法链接，可以看下步骤，场景比较简单](https://  公司内网，无法链接，可以看下步骤，场景比较简单)

### Steps to reproduce

ant版本： 4.16.13

步骤是： 

父页面iframe嵌套子页面，在子页面全局配置了message，3秒自动关闭，getContainer属性指向的是父页面，使用时 提示倒是出来了，但是在它显示的时候，直接在父页面切换路由跳转到别的地方，这个提示就关不掉了，很严重的bug，没找到相关办法处理。

### What is expected?

希望在父页面能自动关闭

### What is actually happening?

无法关闭和销毁

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | ^17.0.0 |
| System | windows 11 |
| Browser | edge |

**Comment by afc163** [comment]
可以尝试全局销毁：https://ant.design/components/message-cn#%E5%85%A8%E5%B1%80%E6%96%B9%E6%B3%95

**Comment by leonardo110** [comment]
这样配置的，在哪全局销毁呢












阿努纳齐
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月28日(周五) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design] messsage 全局配置后，路由跳转后没有自动关闭！！！ (Issue #43885)




 
可以尝试全局销毁：https://ant.design/components/message-cn#%E5%85%A8%E5%B1%80%E6%96%B9%E6%B3%95

**Comment by leonardo110** [comment]
import { message } from 'antd';
message.config({
  duration: 3, // 持续时间
  getContainer: () => {
    return window.parent.document.body;
  },
  maxCount: 1, // 最大显示数, 超过限制时，最早的消息会被自动关闭
  top: 10, // 到页面顶部距离
});

这是我的iframe 子页面的全局配置，如果在跳转后自动关闭？

**Comment by leonardo110** [comment]
> 可以尝试全局销毁：https://ant.design/components/message-cn#%E5%85%A8%E5%B1%80%E6%96%B9%E6%B3%95
import { message } from 'antd';
message.config({
duration: 3, // 持续时间
getContainer: () => {
return window.parent.document.body;
},
maxCount: 1, // 最大显示数, 超过限制时，最早的消息会被自动关闭
top: 10, // 到页面顶部距离
});

这是我的iframe 子页面的全局配置，如果在跳转后自动关闭？

**Comment by afc163** [comment]
这种可能没办法，不建议用 iframe 做主子应用互相调用 antd 实例方法。
