### ISSUE TITLE
封装的Input可以加个统计字数的功能，如果自己加，该怎么扩展

### ISSUE THREAD

**Issue by CurryLiang** [ant-design/ant-design#4388]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by CurryLiang** [comment]
有没有keyDown事件可以用的呢

**Comment by motorguo** [comment]
@CurryLiang  [这里有个可以去看看](https://mobile.ant.design/components/textarea-item/#API-(-适用平台：WEB、React-Native-))

**Comment by afc163** [comment]
Input 和原生 input 事件完全一样，可自行封装。
