### ISSUE TITLE
The button click effect on PC and Mobile is different

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#43880]
### Reproduction link

[https://stackblitz.com/edit/stackblitz-starters-klqt9b](https://stackblitz.com/edit/stackblitz-starters-klqt9b)

### Steps to reproduce

Please check [StackBlitz](https://stackblitz-starters-klqt9b.stackblitz.io) on computer and phone. You will see the difference when you click the button.

On PC
![stackblitz-starters-klqt9b stackblitz io-PC](https://github.com/ant-design/ant-design/assets/105255382/469f0b72-f4a6-4087-883a-c4fe50d0143a)

On Mobile
![stackblitz-starters-klqt9b stackblitz io-Mobile](https://github.com/ant-design/ant-design/assets/105255382/63c28f5d-56d9-408b-bc53-8fe8ca4f3315)

On my project
![This-is-my-project](https://github.com/ant-design/ant-design/assets/105255382/6c4eb085-6cd9-4253-9c29-738472c6dc6c)

### What is expected?

The effect must be the same on PC and Mobile

### What is actually happening?

Effects are not uniform on PC and Mobile

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2.0 |
| System | Macbook Air M1 2020 - macOS 13.3.1 |
| Browser | Chrome 112.0.5615.137 |

**Comment by archisketch-thangly** [comment]
> Seems the Mobile device not support opacity animation?

So do I have to turn it off by css or ConfigProvider or will you guys release one to solve this problem?

**Comment by zombieJ** [comment]
Yes. here is: https://github.com/ant-design/ant-design/pull/43784
will release in next minor version.
