### ISSUE TITLE
darkAlgorithm doesn't work in Next.js app

### ISSUE THREAD

**Issue by arsicdejan** [ant-design/ant-design#43897]
### Reproduction link
https://codesandbox.io/p/sandbox/eager-snowflake-rxf5jg?file=%2Fapp%2Flayout.tsx%3A1%2C1

### Steps to reproduce

Set dark theme as a default

### What is expected?

Whole app to use dark theme

### What is actually happening?

It is using defaultAlgorithm

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React |     "next": "13.4.12" |
| System | Mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
It's wired, seems function didn't passed into ConfigProvider.

**Comment by zombieJ** [comment]
NextJS default use server render which do not support context passing to client side. You need a wrapper with `"use client"` mark:

https://codesandbox.io/p/sandbox/dank-moon-v4dl9x?file=%2Fapp%2Flayout.tsx%3A17%2C5

**Comment by arsicdejan** [comment]
Thank you!

**Comment by Farimah71** [comment]
> NextJS default use server render which do not support context passing to client side. You need a wrapper with `"use client"` mark:
> 
> https://codesandbox.io/p/sandbox/dank-moon-v4dl9x?file=%2Fapp%2Flayout.tsx%3A17%2C5

Exactly. Thanks for your answer
