### ISSUE TITLE
Confirm buttons styling don't take style from theme provider

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#43896]
### Reproduction link

[https://ibb.co/ns15cYd](https://ibb.co/ns15cYd)

### Steps to reproduce

1. set button radius on buttons in theme.json to 999pcx ("borderRadius": 999)
2. Create a confirm modal

### What is expected?

Buttons inside the confirm modal must be rounded like the any other button, but seems they don't take styling from theme provider.

### What is actually happening?

Buttons from confirm modal have their ow styling

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18 |
| System | mac |
| Browser | chrome |

<img width="1080" alt="Screenshot 2023-07-30 alle 15 08 57" src="https://github.com/ant-design/ant-design/assets/40239902/fd049345-66bc-4f63-ab41-37d9b2ce2a26">

**Comment by vitalijalbu** [comment]
https://codesandbox.io/s/confirmation-modal-dialog-antd-5-7-3-forked-95pclx?file=/demo.tsx

**Comment by afc163** [comment]
https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

**Comment by vitalijalbu** [comment]
> https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

So basically I need to do it for every modal i have inside the app? It's not a good approach I think...

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546

**Comment by afc163** [comment]
@vitalijalbu You can try App.useApp https://ant.design/components/app
