### ISSUE TITLE
textarea不存在showCount属性时, 高度无法被正确设置

### ISSUE THREAD

**Issue by Jiong-Sen** [ant-design/ant-design#43892]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/dai-zi-shu-ti-shi-de-wen-ben-yu-antd-5-7-3-forked-fm3l8k?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

textarea存在showCount属性高度能正常设置, 不存在时高度就坍塌了

### What is expected?

高度和设置的一样

### What is actually happening?

高度为auto

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome  115.0.5790.114 |

**Comment by struce2** [comment]
同样遇到这问题了

麻了,这问题搞了一天,一直以为我代码问题

搜到一个跟它差不多的问题 https://github.com/ant-design/ant-design/issues/33049 才想着来看看 issue... 

|Environment	|Info|
|  ----  | ----  |
|antd	| 5.7.3|
|React	|18.2.0|
|System	|操作系统： Manjaro Linux <br/> KDE Plasma 版本： 5.27.6 <br/> KDE 程序框架版本： 5.108.0 <br/> Qt 版本： 5.15.10 <br/> 内核版本： 6.1.41-1-MANJARO (64 位)|
|Browser	| Chrome 版本 114.0.5735.198（正式版本） （64 位）|

**Comment by struce2** [comment]
好吧,我的升级到 5.7.3 就好了,在历史 issue 里看到我的这种情况已经被修复了,跟 showCount 无关,是 height 设置生效一次后就不生效了, 刷新页面就不行了, 具体可以看 #42846

**Comment by struce2** [comment]
> 同样遇到这问题了
> 
> 麻了,这问题搞了一天,一直以为我代码问题
> 
> 搜到一个跟它差不多的问题 #33049 才想着来看看 issue...
> 
> Environment	Info
> antd	5.6.4
> React	18.2.0
> System	操作系统： Manjaro Linux
> KDE Plasma 版本： 5.27.6
> KDE 程序框架版本： 5.108.0
> Qt 版本： 5.15.10
> 内核版本： 6.1.41-1-MANJARO (64 位)
> Browser	Chrome 版本 114.0.5735.198（正式版本） （64 位）

升级到 5.7.3 依然不行

**Comment by struce2** [comment]
@zombieJ  似乎依然不生效 ,升级到了 5.8.2

下面是测试代码 

```html

  <TextArea ref={promptRef} style={{ resize: 'none', height: '120px' }} placeholder="请输入内容..."
  />
```
