### ISSUE TITLE
time-picker format bug

### ISSUE THREAD

**Issue by ziluo-tang** [ant-design/ant-design#43907]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shou-kong-zu-jian-antd-5-7-3-forked-f43dg5?file=/demo.tsx)

### Steps to reproduce

1. setValue(dayjs("10:20:01", "mm:ss"))
2. <TimePicker format="mm:ss" value={value} onChange={onChange} />

### What is expected?

UI show 20:01

### What is actually happening?

10:20

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | latest |
| System | macOS |
| Browser | Chrome 114.0.5735.248 |

**Comment by zombieJ** [comment]
Your parse format is wrong:

```diff
-- dayjs("10:20:01", "mm:ss")
++ dayjs("10:20:01", "HH:mm:ss")
```

https://codesandbox.io/s/shou-kong-zu-jian-antd-5-7-3-forked-t3344p?file=/demo.tsx
