### ISSUE TITLE
Search组件的主题切换问题

### ISSUE THREAD

**Issue by yecongling** [ant-design/ant-design#43903]
### Reproduction link

[https://vmpyl3.csb.app/](https://vmpyl3.csb.app/)

### Steps to reproduce

react工程中添加一个Search组件，最外层包一个主题切换的ConfigPrivoder，当动态切换colorPrimary时，类似想button、input等组件的颜色都发生了变化，但是Search组件的后面的搜索按钮的颜色没有发生更改

### What is expected?

期望Search组件的搜索也跟着主题一起变

### What is actually happening?

没有发生变化

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2 |
| System | Mac OS Ventura |
| Browser | google 115 |

**Comment by zombieJ** [comment]
不要从 `antd/lib` 中引入，你始终应该从 `antd` 中引入组件。框架编译的时候不一定是从 `lib` 目录来，也可能是 `es`:

https://codesandbox.io/s/antd-reproduction-template-forked-6vc6jv?file=/index.js

**Comment by yecongling** [comment]
哦哦，好的，明白了，谢谢
