### ISSUE TITLE
antd 4.15.6 4.16.3 onCell 合并结果不符合预期

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#43901]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdwei-4-15-6shi-hou-rowspanhui-shi-xiao-forked-k9lssp?file=/demo.tsx)

### Steps to reproduce

刷新demo 可看
<img width="1638" alt="image" src="https://github.com/ant-design/ant-design/assets/8169783/0a7d6aef-b999-4fbb-9d42-6d17af652db1">

### What is expected?

希望只合并设置了onCell的列，且不出现数据错位

### What is actually happening?

数据错位，除第一列外合并不符合预期
设置rowSpan 无效，设置rowspan有效

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | masOS Monterey 12.1 |
| Browser | chrome 115 |

**Comment by afc163** [comment]
4.24.12 是否符合预期呢？https://codesandbox.io/s/antdwei-4-15-6dong-tai-rowspanbu-fu-he-yu-qi-forked-nlthmd?file=/package.json:212-219

**Comment by rawbin-** [comment]
> 看看 antd@4.24.12 是否符合预期呢？https://codesandbox.io/s/antdwei-4-15-6dong-tai-rowspanbu-fu-he-yu-qi-forked-nlthmd?file=/package.json:212-219
这个也一样，也错位了

**Comment by zombieJ** [comment]
### 🔥 有问题总是先升级 antd 到最新版本，v4 最新版本为 `4.24.x` 。对过去版本反馈的 bug 很可能在之后版本已经修复了

另外，合并行代码逻辑也不对，下面这个判断永远都是 `false`：

```tsx
return item.name !== item.name;
```

lint 也提示了：

<img width="528" alt="截屏2023-07-31 10 36 51" src="https://github.com/ant-design/ant-design/assets/5378891/7f712dde-8b2b-4728-a3e5-812da2f44f80">

此外，`let sameRowCount = index` 这个也不对， 起始值总应该是 `1` 才对，如果是使用 `some` 就要从 `0` 开始。和 `index` 没有关系。`sameRowCount++` 这个逻辑位置也不正确，这个判断函数是可能遇到不等的，需要先判断再累加：

https://codesandbox.io/s/antdwei-4-15-6dong-tai-rowspanbu-fu-he-yu-qi-forked-j27qv8?file=/demo.tsx

**Comment by rawbin-** [comment]
@zombieJ 尴尬了大佬，抱歉，这个是我的锅，预期看到的不是这个版本，而是上面截图中的版本，可能网络问题后面没有保存上

首先升级这个几乎不可能了，我们尝试过升级到4.x最新，但问题不少 见 https://github.com/ant-design/ant-design/issues/40643 
后面发现问题了，4.x的文档和5.x的文档都说是render方法，结果demo中都是onCell 的demo，onCell的做法，上面这个例子在
[4.24.8版本里面看起来相当的丝滑，而且只需要在需要合并的列中配置onCell就行了也不会出现错位的情况，也是我们想要的效果，但这个放到4.16.13版本中就无效了，[4.16.13 rowSpan无效](https://codesandbox.io/s/antdwei-4-16-13dong-tai-rowspanwu-xiao-forked-qgw7tr)，需要把onCell 返回值中 rowSpan改为 rowspan才有效，但此时会出现错位 [4.16.13 rowspan有效但错位](https://codesandbox.io/s/antdwei-4-16-13dong-tai-rowspanyou-xiao-dan-cuo-wei-forked-wqmhcm)，这个时候我们尝试[使用render的方案](https://codesandbox.io/s/antdwei-4-16-13dong-tai-rowspanyou-xiao-forked-render-93kfnr?file=/demo.tsx) 发现此时rowspan和rowSpan两个属性都能起作用，但rowSpan符合预期rowspan会错位
