### ISSUE TITLE
InputNumber导致IE11卡死

### ISSUE THREAD

**Issue by HhEric** [ant-design/ant-design#4390]
#### 发生问题的环境是：win7  ie11

- antd 版本:2.5.x
- 操作系统及其版本:win7
- 浏览器及其版本:ie11

#### 您做了什么？请提供尽可能详细的重现步骤。

引入 antd 了 InputNumber,然后placeholder存在值，在多个InputNumber按Tab键切换

#### 您期待的结果是:
不会卡死，和Input一样正常使用，Input的时候placeholder存在值没问题

#### 实际上的结果是:
会在两个输入框中重复切换导致IE11卡死

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
IE11 里无法重现，给个例子再开。
