### ISSUE TITLE
bug: Progress size cannot accept number value

### ISSUE THREAD

**Issue by Meet-Bhalodia** [ant-design/ant-design#43911]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s3lw9m?file=/index.js)

### Steps to reproduce

[antd: Progress] strokeWidth is deprecated. Please use size instead.

### What is expected?

no warnings and perfect working progress bar

### What is actually happening?

while i am using size then progress bar in wokring and by size : 3 then only a single dot appearing, i need progress bar.

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | react-js |
| System | windows 10 |
| Browser | chrome 115.0.5790.110 |

**Comment by Meet-Bhalodia** [comment]
please vist codesand box and uncomment size it will only shows a single dot how to get progress bar ?

**Comment by afc163** [comment]
https://codesandbox.io/s/jin-du-tiao-antd-5-7-3-forked-vqvxsm

It is a bug.

**Comment by Meet-Bhalodia** [comment]
no

**Comment by Meet-Bhalodia** [comment]
when i upload image while uploading i need upload bar

**Comment by Meet-Bhalodia** [comment]
ok

**Comment by Meet-Bhalodia** [comment]
no sorry

**Comment by Meet-Bhalodia** [comment]
also another one here  [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead. how to handle this
