### ISSUE TITLE
Image组件预览时，点击任意按钮后Esc键无法退出预览

### ISSUE THREAD

**Issue by NoyChan** [ant-design/ant-design#43912]
### Reproduction link

[https://ant-design.gitee.io/components/image-cn#components-image-demo-preview-group](https://ant-design.gitee.io/components/image-cn#components-image-demo-preview-group)

### Steps to reproduce

1、点击图片进入预览模式  
2、点击左右切换按钮或者下方工具栏按钮  
3、键盘输入Esc键  

### What is expected?

退出预览模式

### What is actually happening?

无反应

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.2.0 |
| System | window |
| Browser | Chrome/112.0.0.0 |

**Comment by linxianxi** [comment]
本地或者 codesandbox 能不能复现？还是只有官网有这个问题？

**Comment by NoyChan** [comment]
> 
本地或codesandbox都能复现
https://codesandbox.io/s/sktmd5?file=/index.tsx

**Comment by angryLid** [comment]
Esc按键是未定义行为吧。
