### ISSUE TITLE
ant-design

### ISSUE THREAD

**Issue by Meet-Bhalodia** [ant-design/ant-design#43910]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-s3lw9m?file=/index.js)

### Steps to reproduce

 [antd: Progress] `strokeWidth` is deprecated. Please use `size` instead. 

### What is expected?

no warning

### What is actually happening?

on uploading document, warning :  [antd: Progress] `strokeWidth` is deprecated. Please use `size` instead. 

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | react-js |
| System | windows 10 |
| Browser | chrome 115.0.5790.110 |

**Comment by zombieJ** [comment]
As console mentioned. Use `size` instead : )

**Comment by afc163** [comment]
strokeWidth is deprecated. Please use size instead.
