### ISSUE TITLE
一个小问题：有没代码片段展示组件?

### ISSUE THREAD

**Issue by doerme** [ant-design/ant-design#4391]
一个小问题：有没代码展示框组件? 用来展示代码片段的

#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by afc163** [comment]
目前没有，未来应该也不会做。

**Comment by afc163** [comment]
这种能自己浏览一下就能得到的信息尽量不要开 issue。
