### ISSUE TITLE
Tooltip hover后出现气泡层在Button有disabled情况下，鼠标移动到气泡层后有很大概率气泡层会消失

### ISSUE THREAD

**Issue by lemonlhy** [ant-design/ant-design#43924]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-3wp7cn?file=/demo.tsx:0-1015)

### Steps to reproduce

1. hover按钮后的图标
2.鼠标移动到气泡层

### What is expected?

气泡层不消失

### What is actually happening?

气泡层消失

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.0.0 |
| System | win10 |
| Browser | 谷歌 |

**Comment by lemonlhy** [comment]
https://www.loom.com/share/14233ee27b3241a9a59e692bee439c18?sid=414f5e62-7721-44b3-8a01-7f96d57fc32e

**Comment by Kwailunmei1** [comment]
是鼠标滑倒disabled的按钮上了吧，换下placement是不是就行或者加下元素间距

**Comment by zombieJ** [comment]
试了一下，手感上的确不太一样。
