### ISSUE TITLE
Make Steps slide

### ISSUE THREAD

**Issue by hbatalhaStch** [ant-design/ant-design#43922]
### What problem does this feature solve?

I have horizontal steps that when it reaches a certain number it gets crunched together and it doesn't look good, besides that, the the information gets cut short.

![image](https://github.com/ant-design/ant-design/assets/114578587/d53a7624-a85e-4e63-a1dc-65a30b7736ee)

It would be really nice if it would slide [just like Tabs does](https://ant.design/components/tabs#components-tabs-demo-slide)

### What does the proposed API look like?

{
slide?: boolean // true by default
}

**Comment by MadCcc** [comment]
By setting the width of container, you can make this as you expected. But it will not be responsive

**Comment by MadCcc** [comment]
Try adding `width: max-content` to Steps and make container `overflow: auto`?

**Comment by hbatalhaStch** [comment]
> overflow

Worked perfectly. Thank you

**Comment by hbatalhaStch** [comment]
What about making this the default behavior?

**Comment by afc163** [comment]
In most cases they don't want a scroll container to hide options.
