### ISSUE TITLE
DatePicker组件相关bug

### ISSUE THREAD

**Issue by aSSmallBoy** [ant-design/ant-design#4392]
#### 环境相关信息
- antd 版本: 2.5.0
- win7 64:
- chrome 55.0.2883.75 (正式版本) （64 位）:

#### 进行如下操作
1.引入了Form,DatePicker
2.在FormItem中包含DatePicker

```
<FormItem label='单据日期'>
         {getFieldDecorator("billdate")(
            <DatePicker />
          )}
</FormItem>
```

#### 您期待的结果是:

```
 form.validateFields((err,values) => {
}
```
values中可以获取到billdate的值

#### 实际上的结果是:

获取到billdate是undefined

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
