### ISSUE TITLE
Passing more properties to options objects other than just label and value for Select component

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#43931]
### What problem does this feature solve?

Allow access to full object values to customize tag render or potentially option rendering

### What does the proposed API look like?

var options = [
   {
     label: 'Hi',
     value: '123',
     BlahBlah: '4234'
   }
];

const tagRender = (props) = {
  const { option } = props
  // option should contain the full object;
   
 return <Tag>{option.BlahBlah}</Tag>

}
<Select options={options} tagRender={tagRender}/>

**Comment by flwzz** [comment]
我这边有同样的需求，为什么tagRender入参不是option的全部数据

**Comment by flwzz** [comment]
我大概知道提问者的需求，我基于作者建了一个例子麻烦看下 https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-ry2fy2
