### ISSUE TITLE
AutoComplete 组件当value是数字 0 时，页面没有显示0

### ISSUE THREAD

**Issue by zbczbc2006** [ant-design/ant-design#43936]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-f7h97z)

### Steps to reproduce

AutoComplete value赋值数字0

### What is expected?

0应该被转换为'0'

### What is actually happening?

输入框没有显示，底层的input值是空字符串

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | react  |
| System | windows |
| Browser | chrome |

---
不知道是不是特意为之，为0显示空很奇怪

**Comment by zombieJ** [comment]
AutoComplete 是作为 Input 增加的组件，预期是输入的 string。不过如果是 `0` 不展示，那肯定是有问题的。

**Comment by ZWkang** [comment]
@zombieJ https://github.com/react-component/select/pull/968 fixed 0 value not show

**Comment by MadCcc** [comment]
Fixed in rc-select@14.7.1
