### ISSUE TITLE
tree 组件希望实现半勾选状态

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#43934]
### What problem does this feature solve?

在做权限控制管理的时候，有一种状况，例如：
父节点：员工管理；
子节点：员工信息管理，退休员工管理、员工部门管理；
如果我勾选了“员工信息管理”，那么“员工管理”应该为半勾选状态，在获取勾选值的时候，应该是：员工管理、员工信息管理两个；
如果我点击了“员工管理”，那么子节点应该都勾选上，在获取勾选值的时候，应该是：员工管理、员工信息管理、退休员工管理、员工部门管理；

### What does the proposed API look like?

提供一个是否开启半勾选的api：halfChecked，开启的话，checkedKeys 返回了父节点，那么父节点选中，子节点只选中checkedKeys返回的。
如果某个节点，子节点选中后，父节点就处于半勾选状态，获取选中值的时候，就包括选中的子节点 父节点

**Comment by zombieJ** [comment]
<img width="598" alt="截屏2023-08-01 16 08 29" src="https://github.com/ant-design/ant-design/assets/5378891/4a3282ba-129b-442b-b645-f1750b93e6ec">

**Comment by xiaoliu1990** [comment]
> <img alt="截屏2023-08-01 16 08 29" width="598" src="https://user-images.githubusercontent.com/5378891/257448105-4a3282ba-129b-442b-b645-f1750b93e6ec.png">

用了这个的，但是有个情况，如果我传递了父节点的id过来呢，那整个列表都变成已选了，本来我只是选中了一个而已
![Snipaste_2023-08-01_16-25-21](https://github.com/ant-design/ant-design/assets/17424034/2c9fd9b2-da95-44c7-a4bc-1e24926945da)
这个功能我保存的时候传递了把checkedKeys和halfChecked都传递给后台了，后台在保存后再次打开会返回三个给我，然后因为有父id，整个子节点都变成已选中了。
![Snipaste_2023-08-01_16-27-12](https://github.com/ant-design/ant-design/assets/17424034/085717c7-a280-4bab-bda3-ea333de197f1)

**Comment by codedart2018** [comment]
这个是有问题的，只能自己前端或后端再处理一次，有一种情况，比如一个节点下有两个节点。我授权的时候把节点后的两个节点都授权勾选上了。这个时候实际上是获得了三个节点信息。但是此后我后台又在这个节点下添加了一个节点。就变成四个节点了，此时你再去看树你会发现惊喜，四个节点全是勾选上的。正确的应该是爷节点不是全选状态，最后添加节点也不是勾选状态。

**Comment by xiaoliu1990** [comment]
> 这个是有问题的，只能自己前端或后端再处理一次，有一种情况，比如一个节点下有两个节点。我授权的时候把节点后的两个节点都授权勾选上了。这个时候实际上是获得了三个节点信息。但是此后我后台又在这个节点下添加了一个节点。就变成四个节点了，此时你再去看树你会发现惊喜，四个节点全是勾选上的。正确的应该是爷节点不是全选状态，最后添加节点也不是勾选状态。

就是这个情况，目前我这边需求比较简单，只有父子两层，所有父节点有个统一的pid，我直接把父节点都给过滤了。父子节点分别存在两个参数里面处理。如果层数更多的话，那就要更加复杂的处理方式了。
