### ISSUE TITLE
Select、AutoComplete 组件 onChange 事件中有请求时的问题

### ISSUE THREAD

**Issue by lyk248** [ant-design/ant-design#4393]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本: Mac OS Sierra
- 浏览器及其版本: Chrome 最新

#### 您做了什么？请提供尽可能详细的重现步骤。
在 onChange 事件中请求获取提示选项
calling an API search to update dataSource using onChange event
```
  handleChange(value) {
    if (value) {
      cFetch(API_CONFIG.getNameCN, {
        params: {
          value,
        }
      }).then((response) => {
        if (response.error) return;
        if (response.jsonResult.code === 0) {
          this.setState({ data: response.jsonResult.dataList });
        }
      });
    } else {
      this.setState({ data: [] });
    }
  }

  handleSelect(value) {
    console.log('select', value);
  }

  render() {
    return (
      this.props.getFieldDecorator(this.props.id)(
        <AutoComplete
          onChange={this.handleChange}
          onSelect={this.handleSelect}
          dataSource={this.state.data}
          placeholder="请输入合作方中文名称"
          filterOption={false}
          notFoundContent="无法找到"
        />
      )
    );
  }

```

#### 效果截图:

![image](https://media.giphy.com/media/l3vRnkYlyjXkTHLyM/giphy.gif)

#### 可重现的在线演示:
http://codepen.io/lyk248/pen/aBaeqQ

在antd 1.x 的版本里不会有这个问题。

目前的方案增加了一个 flag 变量在 setState 时判断，但这个问题在组件内解决更好。

**Comment by RaoHai** [comment]
select 也有此问题。。

**Comment by RaoHai** [comment]
此处。

https://github.com/react-component/select/blob/master/src/Select.jsx#L728

```jsx
 if (typeof document !== 'undefined' &&
      this.getInputDOMNode() &&
      document.activeElement === this.getInputDOMNode()) {
      open = true;
   }
```

当 component 的 props 更改的时候，如果焦点在 Select 的输入框里，则重新打开下拉菜单。。

**Comment by afc163** [comment]
交互参考：http://select2.github.io/examples.html#tags

选择完的 input focus 和按 tab focus 进去时的处理一样，不弹出菜单。与点击 focus 不同。

**Comment by RaoHai** [comment]
https://github.com/react-component/select/pull/165/files

这样应该可以。

**Comment by mitchelldemler** [comment]
I do not speak Chinese (relying on Google Translate), so apologies if this is not a similar issue:

I have an AutoComplete component that populates the dataSource with data from Redux, the dataSource is updated based on an API search that I am calling. The issue I am having is that I need to "re-focus" the input to get the options to appear. Even though the dataSource and children have the correct data on the Autocomplete component, I have to click, or press another key to get the dropdown options to appear.

This is a showstopper bug for me, is there a known workaround?

**Comment by lyk248** [comment]
@mitchelldemler 
I think that's the current problem after some versions' updates caused by this issue (or similar ones).
You can try this demo at antd@2.6.4 version.
http://codepen.io/lyk248/pen/gmeKdB

**Comment by yesmeck** [comment]
This bug is introduced in 2.7.0

**Comment by mitchelldemler** [comment]
Thanks, downgrading to 2.6.4 made it work 👍

**Comment by yesmeck** [comment]
Seems it has been fixed in the latest release.

**Comment by shenpvip** [comment]
Select、AutoComplete components under the same conditions，If you add the
`getPopupContainer={(triggerNode): any =>triggerNode.parentNode}`
attribute，There will still be cases where the drop-down box cannot be closed.

**Comment by krmao** [comment]
also exits
