### ISSUE TITLE
The UI of the ant-design website is breaking

### ISSUE THREAD

**Issue by 0xJaskeerat** [ant-design/ant-design#43949]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

Head over to https://ant.design/ and you will see navbar breaking on every page 
also when I navigate to components Eg: i went to form antd component and wanted to see the code of first form , the icon was not even allowing clicks , the website hanged 

### What is expected?

It should work fine

### What is actually happening?

UI is breaking
check the screenshot
<img width="1440" alt="Screenshot 2023-08-01 at 10 52 52 PM" src="https://github.com/ant-design/ant-design/assets/124770018/b1cefcf0-ebb2-4dcc-859a-79dfd4f06ee5">

| Environment | Info |
| --- | --- |
| antd | 5.8.0 |
| React | 18.2.0 |
| System | mac |
| Browser | google chrome |

---
Nope

**Comment by zombieJ** [comment]
Could you help check the network? It seems work as expect on my side:
<img width="1439" alt="截屏2023-08-02 01 40 59" src="https://github.com/ant-design/ant-design/assets/5378891/1b98c0b0-db5f-4739-94ed-881cfb40f8bb">
