### ISSUE TITLE
Warning: `clearIcon` will be removed in future. Please use `allowClear` instead.

### ISSUE THREAD

**Issue by KageyamaJie** [ant-design/ant-design#43943]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-463zfs)

### Steps to reproduce

1. Once the page finish loaded, error will show up in the console

### What is expected?

The error should not be shown, whenever input related component are used

### What is actually happening?

Error shows whenever input related component are used

| Environment | Info |
| --- | --- |
| antd | 5.8.0 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Brave, Chrome |

---
The error seems to be coming from rc-util package `node_modules/rc-util/es/warning.js`

**Comment by kaoding** [comment]
update 后，5.7.x 也有，应该是 rc- 层导致的。

**Comment by kiner-tang** [comment]
> update 后，5.7.x 也有，应该是 rc- 层导致的。 使用了 allowClear 后就报错，是不是报错提示写反了。

是 antd 中还有使用废弃属性 clearIcon , rc 看起来应该是没问题的

**Comment by JamosLi** [comment]
之前都没有 现在包重新拉 就都出来了

**Comment by JamosLi** [comment]
看不懂关闭issues是个什么操作

**Comment by kiner-tang** [comment]
> 看不懂关闭issues是个什么操作

已经在 #43945 中修复这个问题，正在发布 patch 版本，发布后就正常了

**Comment by afc163** [comment]
<img width="530" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/de794b96-a67a-4594-96bc-48e557123ead">

**Comment by kiner-tang** [comment]
<img width="1765" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/dcb01f70-9663-42a3-b6a7-ea938a7fc1cb">
5.8.1 已经不再警告了
