### ISSUE TITLE
`monthCellContentRender` and `cellContentRender` not working

### ISSUE THREAD

**Issue by codingfishman** [ant-design/ant-design#4394]
#### 发生问题的环境是：

- antd 版本: 2.5.1
- 操作系统及其版本: macOs Serria
- 浏览器及其版本: Chrome 55

#### 您做了什么？请提供尽可能详细的重现步骤。

使用 `MonthPicker`并且指定了 `monthCellContentRender` 和 `cellContentRender`，期望改变MonthPicker生成的节点内容
#### 您期待的结果是:
节点内容被改变

#### 实际上的结果是:
两个属性无效。 看到[代码中](https://github.com/ant-design/ant-design/blob/master/components/date-picker/index.tsx#L45)在调用rc-calendar的MonthCalendar时，自己有包装一层Props，而且编译后的代码也只向 `MonthCalendar`传入了自己包装过的props，`MonthCalendar`自己的props，比如 `monthCellContentRender` 没有被传入，是不是这一步导致该属性被忽略了。

#### 可重现的在线演示

http://codepen.io/anon/pen/pNMozv?editors=001#anon-login
可打开控制台查看，发现函数并未执行。

**Comment by benjycui** [comment]
这儿没有把 `monthCellContentRender` 之类传下去 https://github.com/ant-design/ant-design/blob/master/components/date-picker/createPicker.tsx#L121-L136

有兴趣 PR 个么？

**Comment by afc163** [comment]
cellContentRender 是个文档错误。

monthCellContentRender 确实有问题，上面的提交已修复，感谢反馈。

**Comment by chuhanan** [comment]
节点内容改变了,怎么让节点内容显示在 input 框内呢 ? 比如现在是 9 月, 我在使用 MonthPicker 的时候如果是 9月节点内容显示成了 至今, 我想把至今这个放在 输入框内,但是现在 输入框只支持 moment 类型, 可以处理吗 ?  thx!

**Comment by benjycui** [comment]
> 我想把至今这个放在 输入框内,但是现在 输入框只支持 moment 类型, 可以处理吗 ? thx!

目前无法处理，也没有想到好的解决办法。
