### ISSUE TITLE
DependencyNotFoundError in CodeSandbox

### ISSUE THREAD

**Issue by WeiJun-Nutanix** [ant-design/ant-design#43950]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/68ng9j)

### Steps to reproduce

Open any codeSandbox example on the official webpage. For example, refer to the minimal production link above

### What is expected?

The interactive components is loaded.

### What is actually happening?

DependencyNotFoundError Could not find dependency: 'lodash' relative to '/node_modules/@ant-design/icons/es/utils.js'

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18 |
| System | Mac M1 |
| Browser | Chrome Version 115.0.5790.114 (Official Build) (x86_64) |

**Comment by MadCcc** [comment]
Fixed in `@ant-design/icons@5.2.3`
