### ISSUE TITLE
Select mode=tags模式，optionFilterProp=label，输入某个选项value过滤可能会导致选项重复

### ISSUE THREAD

**Issue by laochake** [ant-design/ant-design#43954]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-gtvx7g?file=/demo.tsx)

### Steps to reproduce

输入框输入US搜索，然后再删除，再输入US搜索，重复操作；

### What is expected?

删除搜索内容后选项为options声明的项

### What is actually happening?

搜索几次 选项中的US就会重复几次

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

**Comment by ZWkang** [comment]
https://github.com/react-component/select/pull/969

提供一个解决方案，忽略当搜索值等于 option 里 item 的 value 值. @MadCcc
