### ISSUE TITLE
checkbox支持传入’0‘、’1‘这样的值

### ISSUE THREAD

**Issue by q1uxu** [ant-design/ant-design#43952]
### What problem does this feature solve?

目前checkbox组件勾选与否返回的值是boolean类型的，不支持自定义勾选时的值（比如勾选时的值是’1‘，没勾选的值是’0‘）。
我们后端是用’0‘和’1‘代表有没勾选的，现在前端要在获取和保存值时手动转换，这样checkbox控件一多会有点麻烦。

### What does the proposed API look like?

checkbox新增2个props，trueValue和falseValue，默认值分别是true和false。

**Comment by afc163** [comment]
建议自行转换数据结构，基础组件不适合做太多类型兼容。
