### ISSUE TITLE
tabs  组件滑动功能，我需要一个点击 左右滑动箭头按钮的点击 的事件 是否可以添加

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#4395]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本:windows7 旗舰版
- 浏览器及其版本:chrome最新版

#### 您做了什么？请提供尽可能详细的重现步骤。

tabs 组件滑动功能，我需要一个点击 左右滑动箭头按钮的点击 的事件 是否可以添加

#### 可重现的在线演示
官网demo
https://ant.design/components/tabs-cn/#components-tabs-demo-slide

**Comment by benjycui** [comment]
PR to: https://github.com/react-component/tabs

**Comment by benjycui** [comment]
@eddyzhang1986 done in https://github.com/react-component/tabs/pull/57

Could you try to PR to upgrade rc-tabs' version and API docs?
