### ISSUE TITLE
DatePicker样式问题

### ISSUE THREAD

**Issue by liekkas** [ant-design/ant-design#4396]
#### 发生问题的环境是：

- antd 版本: 2.5.3
- 操作系统及其版本: MacOS 10.12.2
- 浏览器及其版本: Chrome 54.0.2840.98

#### 您做了什么？请提供尽可能详细的重现步骤。

引入DatePicker，里面的日期图标错位，然后我又加入RangePicker，发现里面的图标正常。

#### 您期待的结果是:

像官网一样正常居中

#### 实际上的结果是:

![image](https://cloud.githubusercontent.com/assets/778747/21535236/17613e72-cdad-11e6-8f53-2e06b0b0e478.png)

#### 可重现的在线演示

http://codepen.io/liekkas/pen/jVgrON

**Comment by ddcat1115** [comment]
你在外层设置了 `display: flex`，改变了 `ant-calendar-picker`的高度，去掉 flex 设置或者 label 的 margin-bottom 就OK了

form 样式参照官网demo   https://ant.design/components/form-cn/#components-form-demo-time-related-controls
