### ISSUE TITLE
notification组件5.x的top属性失效

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#43962]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-dong-guan-bi-de-yan-shi-antd-5-8-0-forked-4389j5?file=/demo.tsx:66-78)

### Steps to reproduce

点击200或者500，出现的值都在最顶部，4.x是可以的https://codesandbox.io/s/5hsm9d?file=/demo.tsx:325-514 ，但是4.x依然有一个问题是，如果第一次点了200，点击500的时候则出现在200的后面，不会出现在500的位置

### What is expected?

点击200出现在200的位置，点击500出现在500的位置

### What is actually happening?

点击200出现在顶部

| Environment | Info |
| --- | --- |
| antd | 5.8.0 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by DY-ZYQ** [comment]
4.x复现链接，上面链接有问题https://codesandbox.io/s/ji-ben-antd-4-24-12-forked-gv7fmp?file=/demo.tsx

**Comment by zombieJ** [comment]
是故意这么设计的，因为 top 这个东西其实是由第一个元素决定的。所以只从 `.config` 里读，文档需要更新一下：
https://codesandbox.io/s/zi-dong-guan-bi-de-yan-shi-antd-5-8-0-forked-x8rlpq?file=/demo.tsx:191-194

**Comment by zombieJ** [comment]
发现已经写过了：https://ant-design.antgroup.com/docs/react/migration-v5-cn#%E7%BB%84%E4%BB%B6-api-%E8%B0%83%E6%95%B4

> * Notification
>    * 静态方法不再允许在 open 中动态设置 prefixCls maxCount top bottom getContainer，Notification 静态方法现在将只有一个实例。如果需要不同配置，请使用 useNotification。
