### ISSUE TITLE
Form 的 label 的tooltip功能

### ISSUE THREAD

**Issue by chenJJ-88** [ant-design/ant-design#43964]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/h568d6?file=/demo.tsx)

### Steps to reproduce

这里的labe tooltip ，鼠标hover上去会有有一个‘？’

### What is expected?

这个是一个bug 还是 就是这样设计的呢

### What is actually happening?

这个是一个bug 还是 就是这样设计的呢

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0 |
| System | Win11 |
| Browser | EDGE |

**Comment by MadCcc** [comment]
设计如此
![image](https://github.com/ant-design/ant-design/assets/27722486/709a0166-1b1a-4380-8dfb-9a302b25e3d7)

**Comment by chenJJ-88** [comment]
> 设计如此 ![image](https://user-images.githubusercontent.com/27722486/257740651-709a0166-1b1a-4380-8dfb-9a302b25e3d7.png)

请问那个 “？” 问号可以取消吗
