### ISSUE TITLE
有计划将table采用虚拟表格实现的同时保留现有所有属性吗

### ISSUE THREAD

**Issue by fasnow** [ant-design/ant-design#43975]
### What problem does this feature solve?

用于互联网数据采集，数据比较多，不采用分页的情况下表格需要展示很多行，同时需要有对应的右键菜单等，如果采用第三方虚拟列表实现的话，原table的事件将会无法继承；添加一个表格的全局行事件，优化在数据过多的情况下不必为每个行都添加一个相同事件。

### What does the proposed API look like?

table使用虚拟表格，继承现有的功能；优化行事件，不用为每个行都添加一个相同事件。

**Comment by zombieJ** [comment]
有：
ref https://github.com/ant-design/ant-design/discussions/41500
