### ISSUE TITLE
InputNumber中onPressEnter事件和onBlur参数中并不能得到输入框中展示的值

### ISSUE THREAD

**Issue by Perseman** [ant-design/ant-design#43979]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xmr39m?file=/index.js)

### Steps to reproduce

在输入框中输入：'123中文test'后按下回车或失焦，输入框中展示： '123', 但是通过e.target.value获取到的值是：'123中文test'

### What is expected?

123

### What is actually happening?

123中文test

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18 |
| System | Mac os 13.0 |
| Browser | Chrome114 |

---
期望能有一种办法，能够在回车后得到和输入框中相同的值

**Comment by MadCcc** [comment]
`onPressEnter` 事件触发在 `format` 之前，试试用 `onChange` 呢？

**Comment by zombieJ** [comment]
`event.target.value` 拿到的是 DOM 的值，不是组件的值。组件的值总是通过 `onChange` 获取。月经问题，得加个 FAQ。

**Comment by Perseman** [comment]
> `onPressEnter` 事件触发在 `format` 之前，试试用 `onChange` 呢？ 你的实际场景是什么样的？

需要用到输入框中的值去更改其他组件的渲染内容，onChange过于频繁了，且不符合产品设计😂

**Comment by yoyo837** [comment]
delay dispatch

**Comment by Perseman** [comment]
目前的方案是失焦后重写一个format方法后赋值给输入框

**Comment by Perseman** [comment]
> 延迟调度

也是一种方案。
个人认为应扩展功能满足，并不应该改变设计

**Comment by Perseman** [comment]
> delay dispatch

It is also a solution.
I personally think that the function should be extended to meet the needs, and the design should not be changed
