### ISSUE TITLE
`footerPaddingInline` incorrectly documented as 'Vertical padding of footer'

### ISSUE THREAD

**Issue by wving5** [ant-design/ant-design#43987]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-chu-chou-ti-antd-5-8-1-forked-vxd95h?file=/demo.tsx:215-287)

### Steps to reproduce

Check doc comments here:
https://github.com/ant-design/ant-design/blob/master/components/drawer/style/index.ts#L12-L20

### What is expected?

`footerPaddingBlock`、`footerPaddingInline` 得到正确注释

### What is actually happening?

`footerPaddingBlock`、`footerPaddingInline` 未正确注释

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | MacOS 11.7.7 |
| Browser | Chrome  114.0.5735.198 |

---
P.S.  `<Anchor/>` 也有同样的注释问题   : https://github.com/ant-design/ant-design/blob/master/components/anchor/style/index.ts#L8-L16

**Comment by MadCcc** [comment]
My bad...

**Comment by MadCcc** [comment]
@wving5 有兴趣来个 PR 吗

**Comment by wving5** [comment]
> @wving5 有兴趣来个 PR 吗

不清楚流程，我试一下吧 =.=
