### ISSUE TITLE
Antd menu item type is lost when accessing 

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#43980]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/switch-the-menu-type-antd-5-8-1-forked-mfynkk?file=/demo.tsx)

### Steps to reproduce

define menu items 

const items: MenuItem[] = [
  getItem('Navigation One', '1', <MailOutlined />),
  getItem('Navigation Two', '2', <CalendarOutlined />),
  getItem('Navigation Two', 'sub1', <AppstoreOutlined />, [
    getItem('Option 3', '3'),
    getItem('Option 4', '4'),
    getItem('Submenu', 'sub1-2', null, [getItem('Option 5', '5'), getItem('Option 6', '6')]),
  ]),
  getItem('Navigation Three', 'sub2', <SettingOutlined />, [
    getItem('Option 7', '7'),
    getItem('Option 8', '8'),
    getItem('Option 9', '9'),
    getItem('Option 10', '10'),
  ]),
  getItem(
    <a href="https://ant.design" target="_blank" rel="noopener noreferrer">
      Ant Design
    </a>,
    'link',
    <LinkOutlined />,
  ),
];

// loop to access item properties, error: Property 'disabled' does not exist on type 'MenuDividerType'
var a = items.map((x) => {
  return x.label;
});

### What is expected?

Should be able to access all properties of MenuItem

### What is actually happening?

type is lost

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by MadCcc** [comment]
`MenuItem` is a union of several item types accepted by Menu. In your case, you should specify `MenuItemType` to get proper inferring of type.

**Comment by AsuraKev** [comment]
I see, so I need to cast to specific type to handle submenu and menu group as well? I have got the menu item one working. thanks a lot

 const defaultActiveKeys = useMemo(() => {
    let activeKeys: string[] = [];
    menuItems.map((x) => {
      x = x as MenuItemType;
      if (x.key === pathname) activeKeys.push(x.key);
    });
    return activeKeys;
  }, []);

**Comment by MadCcc** [comment]
You're welcome. I'm going to closing this issue, feel free to open a new one if you have any other problem.
