### ISSUE TITLE
RangePicker locale ru_RU

### ISSUE THREAD

**Issue by Alyona94** [ant-design/ant-design#43997]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-rangepicker-qp4lmy)

### Steps to reproduce

click on the component RangePicker

### What is expected?

locale language is Russian

### What is actually happening?

locale language English

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | Google Chrome 115.0.5790.110 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-rangepicker-forked-sm5ygl?file=/src/App.js

Or try ConfigProvider https://ant.design/docs/react/i18n

**Comment by Alyona94** [comment]
> https://codesandbox.io/s/antd-rangepicker-forked-sm5ygl?file=/src/App.js
> 
> Или попробуйте ConfigProvider https://ant.design/docs/react/i18n

I tried to do as you said, but it doesn't work in my application. And reproduce it in https://codesandbox.io / it doesn't work out to show.  What can interfere ?

**Comment by afc163** [comment]
<img width="1329" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/a10266f9-1733-4e10-b817-2c68808c10cb">

This codesandbox ( https://codesandbox.io/s/antd-rangepicker-forked-sm5ygl?file=/src/App.js ) works fine, could you provide a reproduce that doesn't work?
