### ISSUE TITLE
Table不支持动态展开和收起树型数据？

### ISSUE THREAD

**Issue by seap** [ant-design/ant-design#4399]
![image](https://cloud.githubusercontent.com/assets/944003/21537148/e8401fb2-cdc7-11e6-9795-ed8cee0b2254.png)
树型层级过多，是否支持动态展开所有层级？

**Comment by yesmeck** [comment]
`expandedRowKeys`、`defaultExpandedRowKeys`、`defaultExpandAllRows`

自己看情况使用以上 API。
