### ISSUE TITLE
addOn font size should be 16 when control size is large

### ISSUE THREAD

**Issue by donysukardi** [ant-design/ant-design#43993]
### What problem does this feature solve?

<img width="548" alt="image" src="https://github.com/ant-design/ant-design/assets/410792/40c9ea52-bb6f-4b02-8c51-8ae6a495503f">

Inconsistency between using text or component for addon, as component will inherit the size set in the Form, causing it to show fontSize 16, whereas addon text stays at 14

### What does the proposed API look like?

```
.ant-input-group-wrapper-lg .ant-input-group-addon {
  font-size: 16px;
}

.ant-input-number-lg   .ant-input-number-group-addon {
  font-size: 16px;
}
```

**Comment by MadCcc** [comment]
It makes sense. PR is welcome~
