### ISSUE TITLE
RangePicker配置了showTime的禁止时间，但是选中Date后的Time会有默认值，即使这个Time是禁止的也可以确认选中

### ISSUE THREAD

**Issue by heyyybingo** [ant-design/ant-design#43999]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-wave-c735p2?file=/src/App.js)

### Steps to reproduce

代码使用了range来返回禁用的时间段，这里把时间设置为只有8点，20点可选，点击一个date之后会产生默认的时间值，之后点击ok，这个时间能够正常被选中

### What is expected?

ok按钮禁用

### What is actually happening?

ok按钮可点，并且选中了禁止的time

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.x |
| System | macos |
| Browser | chrome |

---
业务场景：首先有一个活动，这个活动报名限制了Date，比如2023-11-11～2023-11-20，同时还要限制Time，这个活动在每一天里都有Time的限制，例如只能选择8点或者20点的时间，毕竟复杂一点的场景可能是：每一天实际能选择的Time都不一样。
如果能够在showTime的defaultValue中直接选中某一天的默认值，倒是一个折中办法，起码用户不能选其他的时间了，默认给了一个正确的Time

**Comment by heyyybingo** [comment]
codesandbox 中使用5.8.2也可以复现这个操作

**Comment by heyyybingo** [comment]
🥸有人帮忙看看嘛

**Comment by yoyo837** [comment]
看看是不是和 #29023 同一个问题?

**Comment by heyyybingo** [comment]
> 看看是不是和 #29023 同一个问题?

https://codesandbox.io/s/bu-ke-xuan-ze-ri-qi-he-shi-jian-antd-4-24-13-forked-3qrqtc?file=/demo.tsx
这个issue是4版本的，按照他的说法，是禁用了当天Date，但是先选择Time时默认会选择到当天，我尝试用4.11.1版本复现，此时ok按钮是禁用的，也就是不可点状态，实际上这个值不会被确定。
我当前的描述是先选择了Date，此时会有默认Time，即使该值被禁用也能够ok确认。
这两个issue实际的操作顺序不同，并且29023这个issue实际上不能确定值，应该没啥问题，但是这里先选择Date后的Time是可以确认的。

**Comment by heyyybingo** [comment]
🧐

**Comment by heyyybingo** [comment]
这个应该算是问题吧，毕竟实际禁用的时间最终可以被选中，或者有其他方式可以避免吗？我目前没有找到方法

**Comment by heyyybingo** [comment]
确认按钮的禁用状态按照disableddate配置，可以避免被选中的问题
