### ISSUE TITLE
ant.design table 树形结构 与 展开行 不兼容

### ISSUE THREAD

**Issue by promotion-xu** [ant-design/ant-design#44009]
### Reproduction link

[https://codepen.io/xuzhen/pen/jOQdREj](https://codepen.io/xuzhen/pen/jOQdREj)

### Steps to reproduce

依据链接的数据
点击展开树形结构， 同时会展开行

### What is expected?

期望可以分开操作：
例如在第一列展开树形结构
在最后一列可以展开行

### What is actually happening?

点击展开树形结构，会同时展开行，并且树形结构没有缩进

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.0.0 |
| System | macOS |
| Browser | Chrome  latest |

**Comment by Wxh16144** [comment]
没看懂你的期望逻辑🤔， 不过没有树形结构看起来缺是怪怪的

**Comment by afc163** [comment]
这两个功能是在交互上是冲突的，无法一起使用，有相关的 warning。https://github.com/ant-design/ant-design/issues/32525#issuecomment-960575924

<img width="743" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8eacecc9-b6b1-4ae7-b6c7-271929a1b4e5">

**Comment by promotion-xu** [comment]
我试过只使用树形结构功能，然后在点击某一行中的某一列，通过操作dom, 在tr 后面再插入一行，可以实现。
但是只能添加Element, Node,  不能添加react 组件, 大佬们有什么思路吗
复现demo:
https://codepen.io/xuzhen/pen/jOQdREj


![image](https://github.com/ant-design/ant-design/assets/36992764/a1abc97c-7f08-4f06-88ce-68a07f839cfc)

**Comment by promotion-xu** [comment]
@Wxh16144 

树形结构和展开行 只能二选一

**Comment by promotion-xu** [comment]
> 我试过只使用树形结构功能，然后在点击某一行中的某一列，通过操作dom, 在tr 后面再插入一行，可以实现。 但是只能添加Element, Node, 不能添加react 组件, 大佬们有什么思路吗 复现demo: https://codepen.io/xuzhen/pen/jOQdREj
> 
> ![image](https://user-images.githubusercontent.com/36992764/258313056-a1abc97c-7f08-4f06-88ce-68a07f839cfc.png)

大佬，有其他解决方案吗， @afc163

**Comment by Wxh16144** [comment]
我听明白你的描述了，antd table 设计就这两个 api 不可以同时使用。 
至于这个
 
> 但是只能添加Element, Node, 不能添加react 组件

hack 的方法用 react-dom/server 提供的 renderToString 试试。。。

**Comment by promotion-xu** [comment]
> react-dom/server

renderToString 可以的， 不知道会不会对子组件有什么限制。

**Comment by promotion-xu** [comment]
> 我听明白你的描述了，antd table 设计就这两个 api 不可以同时使用。 至于这个
> 
> > 但是只能添加Element, Node, 不能添加react 组件
> 
> hack 的方法用 react-dom/server 提供的 renderToString 试试。。。



> 我听明白你的描述了，antd table 设计就这两个 api 不可以同时使用。 至于这个
> 
> > 但是只能添加Element, Node, 不能添加react 组件
> 
> hack 的方法用 react-dom/server 提供的 renderToString 试试。。。

curRowElement.insertAdjacentHTML('afterend', renderToString(<AdminStore />));

**Comment by promotion-xu** [comment]
renderToString 可以的，不知道对于转成string的组件 有没有什么限制

看文档是说，不支持从接口获取数据🤔️
renderToString returns a string immediately, so it does not support streaming or waiting for data.

https://react.dev/reference/react-dom/server/renderToString#alternatives

**Comment by promotion-xu** [comment]
@Wxh16144  ，renderToString 可以的，不知道对于转成string的组件 有没有什么限制

看文档是说，不支持从接口获取数据🤔️
renderToString returns a string immediately, so it does not support streaming or waiting for data.

https://react.dev/reference/react-dom/server/renderToString#alternatives

**Comment by Wxh16144** [comment]
我遇到过 context， router 等问题， 所以我不用这个方法，对于一些简单的组件可以试试。。。

**Comment by promotion-xu** [comment]
@Wxh16144 
flushSync: 刚试过，组件内可以调用接口，不知道会不会有其他问题
renderToString: 只能渲染一些静态组件
