### ISSUE TITLE
Tag标签组件，文档中的“动态添加和删除”部分的示例代码有误。

### ISSUE THREAD

**Issue by shangdong2023** [ant-design/ant-design#44008]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pzwvfl?file=/demo.tsx)

### Steps to reproduce

Tag标签组件，文档中的“动态添加和删除”部分的示例代码有误。
```js
  useEffect(() => {
    editInputRef.current?.focus();
  }, [inputValue]);
```
示例代码中的以上代码有误，应该将 `useEffect` 依赖项从 `inputValue` 调整为 `editInputValue` ，如下：
```js
  useEffect(() => {
    editInputRef.current?.focus();
  }, [editInputValue]);
```

### What is expected?

双击修改标签，应该直接聚焦input框

### What is actually happening?

双击修改标签，打开input框，并未聚焦

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18 |
| System | Windows |
| Browser | chrome最新版 |

**Comment by kiner-tang** [comment]
我来改一下吧

**Comment by shangdong2023** [comment]
补充一下，`handleEditInputConfirm` 函数中的 `setInputValue('')` 也应该改成 `setEditInputValue('')`
