### ISSUE TITLE
Duplicated Select options when searching in tags mode

### ISSUE THREAD

**Issue by michael-s-molina** [ant-design/ant-design#44007]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tags-antd-5-8-1-forked-5t2fpc)

### Steps to reproduce

The Select has mode = tags and the options have numeric values.
- Open the Select
- Search for 11
- The value appears twice
- Hit backspace twice to clear the value
- Search for 11 again
- The value now appears 3 times

### What is expected?

When searching for 11 just one option is displayed.

### What is actually happening?

It's duplicating the options for every search.

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.0.0 |
| System | Mac OS Ventura 13.5 |
| Browser | Chrome 115.0.5790.170 |

**Comment by zombieJ** [comment]
You can see the warning:

<img width="506" alt="截屏2023-08-03 22 10 13" src="https://github.com/ant-design/ant-design/assets/5378891/e96fb465-fa42-41a2-8331-86312b451f5f">


```diff
-- value: i,
++ value: String(i),
```

https://codesandbox.io/s/tags-antd-5-8-1-forked-fnft45?file=/demo.tsx:220-236

**Comment by michael-s-molina** [comment]
Oh, I didn't notice that. Thank you @zombieJ!
