### ISSUE TITLE
RangePicker closes on interacting/dragging on the footer elements

### ISSUE THREAD

**Issue by pranshuchittora** [ant-design/ant-design#44005]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6dhlkz?file=/index.js:0-1028)

### Steps to reproduce

```
import React from "react";
import { createRoot } from "react-dom/client";
import { Button, DatePicker, Space, version, Form, Slider } from "antd";
import "antd/dist/reset.css";
import "./index.css";

const { RangePicker } = DatePicker;
const App = () => {
  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <Space>
        <RangePicker
          renderExtraFooter={() => {
            return (
              <Form layout="vertical">
                <Form.Item label="Slider">
                  <Slider
                    range={{ draggableTrack: true }}
                    defaultValue={[0, 100]}
                    marks={{
                      20: "25%",
                      80: "80%"
                    }}
                  />
                </Form.Item>
              </Form>
            );
          }}
        />
        <Button type="primary">Primary Button</Button>
      </Space>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);
```

Steps
1. Open the Range Picker
2. Drag the Slider 

### What is expected?

The expected behaviour is that the RangePicker should not close during the drag gesture

### What is actually happening?

The RangePicker is getting closed

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | NA |
| Browser | NA |

**Comment by pranshuchittora** [comment]
Do let me know if there's any workaround for this

**Comment by MadCcc** [comment]
`RangePicker` will close if trigger blurred. 
It seems any input component placed in footer will have same problem.

**Comment by hydraZty** [comment]
I think footer belongs to the entire `RangePicker`, Focusing or manipulating should not cause the entire component blur. 
If this can be confirmed, i'll do something for this.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
