### ISSUE TITLE
Version 1.36.0 of rc-field-form makes name property of Form.Item to be of undefined or never type when styled by emotion/styled

### ISSUE THREAD

**Issue by krismale** [ant-design/ant-design#44001]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-carlos-fq3z6c?file=/src/App.tsx)

### Steps to reproduce

Style a Form.Item component with styled function from @emotion/styled v11.10.5 and try to enter a string in the name property.

### What is expected?

The property "name" on a emotion/styled Form.Item should accept a string, like it does on a plain Form.Item component.

### What is actually happening?

Receives error "Type 'string' is not assignable to type 'undefined'", or "Type 'string' is not assignable to type 'never'" (in CodeSandbox I was able to replicate this to make the property type equal to undefined, while in my actual code it evaluates to never for some reason)

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome |

---
A bit unsure whether or not this bug is in Antd or in emotion/styled package, or if I'm just doing something wrong, but it was introduced after rc-field-form introduced a type-check in the latest minor version they deployed 3 days ago: https://github.com/react-component/field-form/pull/603

**Comment by MadCcc** [comment]
cc @crazyair

**Comment by crazyair** [comment]
try 1.36.1

**Comment by krismale** [comment]
Same issue (if you mean rc-field-form)

**Comment by krismale** [comment]
That solved it, thanks!

**Comment by crazyair** [comment]
+ rc-field-form@1.36.2
