### ISSUE TITLE
When changing the modal antd's style, changing the transform scale(0.8) when the modal is set to open, it will be the original size for one second then only the size of the modal will be transform? Why is it? Why it is not transform during the start?

### ISSUE THREAD

**Issue by MarcusCody** [ant-design/ant-design#44002]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4t72k6?file=/index.js)

### Steps to reproduce

Click open the modal

### What is expected?

The transform origin should be applied before the modal is open, in other word is that the size of modal should be already transformed before the modal is shown to the user

### What is actually happening?

When changing the modal antd's style, changing the transform scale(0.8) when the modal is set to open, it will be the original size for one second then only the size of the modal will be transform? Why is it? Why it is not transform during the start?

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | Version	10.0.22621 Build 22621 |
| Browser | Version 115.0.5790.110 (Official Build) (64-bit) |

**Comment by MadCcc** [comment]
Because the animation is fixed from `scale(0.8)` to `scale(1)`

**Comment by MadCcc** [comment]
What do you expected exactly?

**Comment by MarcusCody** [comment]
It is the same, the animation is still there to scale from 1 to 0.5. Is there a way I can solve this issue?

**Comment by zombieJ** [comment]
Modal use animation which use the `transform` css.

**Comment by zombieJ** [comment]
here: https://github.com/ant-design/ant-design/blob/4476c9041b4f147d1401f996ac78d2b6befe1007/components/modal/Modal.tsx#L123

**Comment by MarcusCody** [comment]
Alright weird as this one is not shown in the antd official documentation. I am able to solve the issue by changing the transitionName to my own defined className in CSS.

Alright weird as this one is not shown in the antd official documentation. I am able to solve the issue by changing the transitionName to my own defined className in CSS.

**Comment by MarcusCody** [comment]
Alright weird as this one is not shown in the antd official documentation. I am able to solve the issue by changing the transitionName to my own defined className in CSS.

**Comment by MarcusCody** [comment]
There's an issue after setting the transitionName with the class below, when I close the modal, the modal will not be closed, only the modal will be closed
`.purchase-order-form-modal-container {
  transition: none !important;
}`

**Comment by zombieJ** [comment]
custom `transitionName` should provides `appear` `enter` `leave` 3 phase motion. It will not do leave motion if `leave` phase motion not set.

**Comment by zombieJ** [comment]
PS: `transitionName` is internal API which is design only for special case since we still wish developer follow the Ant Design's design pattern : )

**Comment by MarcusCody** [comment]
> custom `transitionName` should provides `appear` `enter` `leave` 3 phase motion. It will not do leave motion if `leave` phase motion not set.

May I know where can I grab detailed information on this three-phase motion and how can i change them accordingly?

**Comment by zombieJ** [comment]
ref https://github.com/react-component/motion/blob/master/docs/examples/basic.less

**Comment by MadCcc** [comment]
Since it becomes a problem with usage, I'm going to closing it. 
Feel free to open new issue if encounter with other problems.

**Comment by MarcusCody** [comment]
It is weird that I have a modal with a transition name that will be able to close the modal along with its mask, but I have another similar modal on another page, it will not close the modal but it will just close its masking. I am using the same transition class-name for both of this modal, one work but another wont work. 

This is the class name I used for my both modal.
`.purchase-order-form-modal-container {
  transition: none !important;
  animation-duration: 0s !important;
}`

Even I try to use the transitionName set to transitionName = "test" it is still not working properly, the modal will not close after giving it the transitionName props
