### ISSUE TITLE
官网的例子有个错误

### ISSUE THREAD

**Issue by zaxlct** [ant-design/ant-design#4400]
我是在这里贴出来具体哪个例子的第几行代码错误， 还是有更好的办法？

**Comment by afc163** [comment]
无论哪个都行，反正这样问应该是最差的办法了。

更好的办法是直接 PR ~

**Comment by zaxlct** [comment]
「带行编辑功能的表格」例子里：
```jsx
<div className="editable-row-text">
     {value || ' '}
 </div>
```
如果 value 正好是数字 0 就不太友好了

如果能直接编辑文档然后 PR 就好了。

**Comment by afc163** [comment]
<img width="730" alt="image" src="https://cloud.githubusercontent.com/assets/507615/21537349/8340e886-cdcb-11e6-84d2-68b0b52f7f11.png">

**Comment by zaxlct** [comment]
谢谢。
当时我大概花了一分钟，没找到编辑的入口。

**Comment by benjycui** [comment]
感觉那个小铅笔默认显示就好。

**Comment by afc163** [comment]
可以。
