### ISSUE TITLE
Spin tip不生效

### ISSUE THREAD

**Issue by hhniao** [ant-design/ant-design#44017]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xw9qmz)

### Steps to reproduce

无需重新, 代码不支持?

### What is expected?

无

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | unknow |
| System | unknow |
| Browser | unknow |

**Comment by yoyo837** [comment]
不生效还不需要重现吗?

**Comment by yoyo837** [comment]
是想说, 没有children 的时候不生效吧?

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/128d2626-03f7-455d-bad2-ea9ff17cc0ab)
设计如此

**Comment by zombieJ** [comment]
console 看看，已经告诉你了：
<img width="462" alt="截屏2023-08-04 10 51 02" src="https://github.com/ant-design/ant-design/assets/5378891/32a10818-af9a-4221-99fc-bf39511c6750">

**Comment by hhniao** [comment]
> ![image](https://user-images.githubusercontent.com/27722486/258282452-128d2626-03f7-455d-bad2-ea9ff17cc0ab.png) 设计如此

为什么会设计如此呢? 加载状态不应该设计成一个无需包裹的元素吗?

**Comment by hhniao** [comment]
> console 看看，已经告诉你了： <img alt="截屏2023-08-04 10 51 02" width="462" src="https://user-images.githubusercontent.com/5378891/258282671-32a10818-af9a-4221-99fc-bf39511c6750.png">

还真是有, 本地开发没有留意, 太多warning了. 很多warning都找不到位置.
例如, list key问题.
