### ISSUE TITLE
在Form.item中，使用ImgCrop包裹下的Upload 无法触发validator方法

### ISSUE THREAD

**Issue by chenJJ-88** [ant-design/ant-design#44027]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhu-ce-xin-yong-hu-antd-5-8-2-forked-6rr62h?file=/demo.tsx)

### Steps to reproduce

点击删除图片，rules未出现提示

### What is expected?

能够触发validator

### What is actually happening?

未能触发validator方法里面的逻辑

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0 |
| System | Win11 |
| Browser | EDGE |

**Comment by zombieJ** [comment]
因为你没有把事件透传给 Image，这个代码里 value 和 onChange 事件都扔给 ImgCrop 了。参考一下这个例子哈：
https://ant-design.antgroup.com/components/form-cn#components-form-demo-customized-form-controls

**Comment by zombieJ** [comment]
随改改，具体的东东还需要你自行调整哈：

https://codesandbox.io/s/zhu-ce-xin-yong-hu-antd-5-8-2-forked-c3p6nm?file=/demo.tsx

**Comment by chenJJ-88** [comment]
> 随改改，具体的东东还需要你自行调整哈：
> 
> https://codesandbox.io/s/zhu-ce-xin-yong-hu-antd-5-8-2-forked-c3p6nm?file=/demo.tsx

感谢大佬，恍然大悟，太愚蠢了我，谢谢谢谢谢
