### ISSUE TITLE
预览图片的操作栏，悬浮样式不太对

### ISSUE THREAD

**Issue by hellowuxin** [ant-design/ant-design#44023]
### Reproduction link

[https://ant.design/components/image-cn](https://ant.design/components/image-cn)

### Steps to reproduce

点击图片预览，鼠标移至操作图标上方

### What is expected?

高亮操作图标

### What is actually happening?

操作图标变灰

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 17 |
| System | win10 |
| Browser | chrome |

**Comment by hellowuxin** [comment]
![1691131273245_4EFEBD9F-9BD6-4cb9-93DC-4AF9010EF752](https://github.com/ant-design/ant-design/assets/37543498/d06f0e6a-e63b-4e3b-b3ad-40f24e0a60f2)
![image](https://github.com/ant-design/ant-design/assets/37543498/040af7c4-ac18-40b6-bd1b-0868e7f0ee5c)

**Comment by MadCcc** [comment]
确实和禁用的颜色混淆了，但是变灰是正确的

**Comment by MuxinFeng** [comment]
<img width="464" alt="image" src="https://github.com/ant-design/ant-design/assets/46584765/d8fdf300-a048-4d0f-8f15-483d3d71373c">

hover 时，opacity 给 0.7 如何

**Comment by kiner-tang** [comment]
或者正常状态 0.7 ，hover 1 ，disabled 0.3 ?

**Comment by ZWkang** [comment]
这个 improvement 确定一下就可以进行改动了吧  @MadCcc

**Comment by afc163** [comment]
@ZWkang 可以
