### ISSUE TITLE
DatePicker value 初始化赋值之后，打开DatePicker周的标题变为英文

### ISSUE THREAD

**Issue by zzz999** [ant-design/ant-design#4402]
#### 发生问题的环境是：
- antd 版本:2.5.3
- 操作系统及其版本:os x el capitan 10.11.6 
- 浏览器及其版本: chrome 54.0.2840.98 

#### 您期待的结果是:

周显示中文

#### 实际上的结果是:
![image](https://cloud.githubusercontent.com/assets/9794859/21538122/97e35630-cdd4-11e6-9b59-19fb82db60a8.png)

#### 可重现的在线演示
http://codepen.io/zzz999/pen/mONOgL?editors=0010

**Comment by zzz999** [comment]
import moment from 'moment';

// 推荐在入口文件全局设置 locale
import 'moment/locale/zh-cn';
moment.locale('zh-cn');

**Comment by benjycui** [comment]
这个问题只有把 `antd` 默认语言定为英文才能完美解决，不然都会有这个认知问题。

**Comment by afc163** [comment]
可以把这句默认加上好了。

```
// 推荐在入口文件全局设置 locale
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
```

**Comment by benjycui** [comment]
@zzz999 麻烦再提供一次可重现 demo ?

**Comment by zzz999** [comment]
@benjycui  http://codepen.io/zzz999/pen/dNMWzJ?editors=0010

**Comment by benjycui** [comment]
你 demo 中的行为的确不符合我们设计的预期，但本地不大好重现。。

之前的 commit https://github.com/ant-design/ant-design/commit/0aabdb3d8b970986cfdc27204289fb010d707fa7 应该修复了这个问题，这周发版后再看下吧。

**Comment by afc163** [comment]
2.6.3 依然有问题。

**Comment by benjycui** [comment]
这个感觉还是去掉，然后让开发者在 entry 设置好了 https://github.com/ant-design/ant-design/blob/ca4697be554981368b6fa427cb72f6cc396d944b/components/date-picker/locale/zh_CN.tsx#L5-L8

在开发者没有用 LocaleProvider 时，时间类组件的 locale 还是应该跟随用户设置。

强制把 moment.locale 设为中文的话，组件的 locale 属性就没意义了。
