### ISSUE TITLE
Warning: Unknown prop `separator` on <div> tag. When I using Breadcrumb 

### ISSUE THREAD

**Issue by kunsam** [ant-design/ant-design#4403]
#### 发生问题的环境是：

- antd 版本: ^2.0.1
- 操作系统及其版本: os X 10.11
- 浏览器及其版本: Chrome Version 55.0.2883.95

others: 
     "react": "^15.4.1",
    "react-addons-update": "^15.4.1",
    "react-dom": "^15.4.1",

###### 引入 antd - Breadcrumb 

{{
   `<Breadcrumb separator=">">
       {...}
    </Breadcrumb>`
}}

#### 您期待的结果是:

我期望正确得到 “>” separator 分割的breadcrumb

如像官网一样的:
 Home>Application Center>Application List>An Application

#### 实际上的结果是:
react 报错
Warning: Unknown prop `separator` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop ......

**Comment by kunsam** [comment]
我在< Breadcrumb>{ condition? <Breadcrumb.item/> : <div />} </Breadcrumb>中引入引入了 <div />
导致报错

**Comment by yesmeck** [comment]
Breadcrumb 只能嵌套 Breadcrumb.item。

试试： `< Breadcrumb>{ condition && <Breadcrumb.item/>} </Breadcrumb>`

**Comment by benjycui** [comment]
Breadcrumb 也要引入类似 Select 之类的 warning。

**Comment by benjycui** [comment]
@kunsam 可有兴趣？

**Comment by kunsam** [comment]
ok, 元旦do it
