### ISSUE TITLE
Everything about changing state in Upload Component lose efficacy when Form manage Upload in a special way .

### ISSUE THREAD

**Issue by simiooo** [ant-design/ant-design#44036]
### Reproduction link

[https://stackblitz.com/edit/react-uu9j5u?file=demo.tsx](https://stackblitz.com/edit/react-uu9j5u?file=demo.tsx)

### Steps to reproduce

1. click Button inside Upload component , and select a file  with confirming.
2. the filelist ui is stuck at loading forever (or nothing showed).
3. click delete icon in filelist ui , and nothing happen . 

### What is expected?

1. after user select a file , there is a filelist showing in filelist ui .
2. the filelist ui's state should be correct rather than showing a loading icon forever
3. when user click delete icon , the ui of file  should be removed .

### What is actually happening?

in upload action , we can inspect the invocation of getValueProps . The value passed to getValueProps is correct and the return value is correct too . But when u encode value in JSON format   in normalize prop and decode value from JSON format  to javascript Object , the Upload component didn't update correctly . the arguments and return value in Form.Item's getValueProps api and normalize api is right . This Upload component 's state is wrong . Actually the Upload compoent 's state keep initialValue forever and never actually update itself .

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.2.0 |
| System | Fedora Linux 38 Workstation |
| Browser | Chrome/115.0.0.0 |

**Comment by afc163** [comment]
```diff
    <Form.Item
      name="file"
      normalize={(e) => JSON.stringify(e.fileList)}
      getValueProps={(ele) => {
        console.log(ele, 1);
        try {
          return { fileList: JSON.parse(ele) };
        } catch (err) {
          return {
            fileList: [],
          };
        }
      }}
+     valuePropName="fileList"
    >
      <Upload {...props}>
        <Button icon={<UploadOutlined />}>Click to Upload</Button>
      </Upload>
    </Form.Item>
```

or

```diff
    <Form.Item
      name="file"
      normalize={(e) => JSON.stringify(e.fileList)}
      getValueProps={(ele) => {
        console.log(ele);
        try {
          return { fileList: JSON.parse(ele) };
        } catch (err) {
          return {
            fileList: [],
          };
        }
      }}
+     valuePropName="fileList"
    >
      <Upload {...props}>
        <Button icon={<UploadOutlined />}>Click to Upload</Button>
      </Upload>
    </Form.Item>
```

```diff
    <Form.Item
      name="file"
      normalize={(e) => JSON.stringify(e.fileList)}
      getValueProps={(ele) => {
        console.log(ele);
        try {
-         return { fileList: JSON.parse(ele) };
+         return { value: JSON.parse(ele) };
        } catch (err) {
          return {
-           fileList: [],
+           value: [],
          };
        }
      }}
    >
      <Upload {...props}>
        <Button icon={<UploadOutlined />}>Click to Upload</Button>
      </Upload>
    </Form.Item>
```

**Comment by simiooo** [comment]
Hey @afc163 afc163 , thanks for reply . you perfectly solved my problem . And could you tell me more about Upload Component ? Why can getValueProps return ``` {fileList: []} ``` normally  without JSON format ? Only if i pass data in JSON format  i should return object of  "value" key . Is there any documentation relative to this phenomenon ?

**Comment by afc163** [comment]
Check out `valuePropName` in https://ant.design/components/form/
