### ISSUE TITLE
官网组件的展示方式

### ISSUE THREAD

**Issue by yam-svg** [ant-design/ant-design#44045]
### What problem does this feature solve?

对于一些屏幕较小的屏幕,官网每排展示两个组件的方式,当展开其代码时,如果需要复制代码则需要左右拖动,不是很方便

### What does the proposed API look like?

像element官网展示组件那样,每排显示一个组件示例,展开代码后能一排显示完整代码,不需要左右拖动

**Comment by kiner-tang** [comment]
<img width="499" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/401720e5-a4ef-4e5f-94dd-c9bff8b10fc3">
可以尝试直接使用复制按钮复制
