### ISSUE TITLE
Return rows in onResize callback of Input.Textarea

### ISSUE THREAD

**Issue by PhosphorusP** [ant-design/ant-design#44048]
### What problem does this feature solve?

Currently, the onResize callback of the Input.Textarea component only returns the width and height. However, in some scenarios, we also need to know the current number of rows in the textarea. For example, when we need to adjust the layout or style of other components based on the number of rows in the textarea, this feature becomes necessary.

### What does the proposed API look like?

Proposed API looks like:
```jsx
onResize: function({ width, height, rows })
```
And here's an example demonstrates how to use the Input.Textarea component from the antd library and the useState hook in React to dynamically adjust the layout based on the number of rows in the textarea.
```jsx
import { Input } from "antd";
import { useState } from "react";

const MyComponent = () => {
  const [multipleLines, setMultipleLines] = useState(false);
  const handleSizeChange = ({ rows }) => setMultipleLines(rows > 1);
  return (
    <div
      style={{
        display: "flex",
        flexDirection: multipleLines ? "column" : "row",
      }}
    >
      <Input.Textarea
        onResize={handleSizeChange}
        autoSize={{ minRows: 1, maxRows: 6 }}
      />
      <MyToolbar />
    </div>
  );
};
```
The example aligns with the previous feature request of returning the number of rows in the onResize callback to allow for more flexible layout and style adjustments of other components.

**Comment by MadCcc** [comment]
Is `height` enough for judging rows?
In my opinion, layout should be relative with height more than rows.
