### ISSUE TITLE
使用 Upload 组件上传 GIF 后打开只会播放一次

### ISSUE THREAD

**Issue by tron-billy** [ant-design/ant-design#44044]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhao-pian-qiang-antd-4-24-13-forked-4z8jyg?file=/demo.tsx)

### Steps to reproduce

https://media.tenor.com/qMZe3e1Er7EAAAAC/example.gif
本地下载该 gif 后点击 Upload，成功后点击 Preview 查看结果

### What is expected?

从本地上传的 GIF 经过 Upload 组件后应仍然保持循环播放的格式

### What is actually happening?

本地 GIF 支持循环播放，通过 Upload 组件上传后，返回的结果打开只会播放一次

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2 |
| System | macOS |
| Browser | Chrome |

---
支持用户上传 GIF 图片，前端展示 GIF 图片（保留循环播放的效果）

**Comment by MadCcc** [comment]
无法复现，可能是浏览器配置问题或者插件导致的。

**Comment by zombieJ** [comment]
让后端看看是不是处理的图片设置了 GCE 播放次数，antd 侧不会对图片做特殊处理。如果没有的话，参考 @MadCcc 的回复。

**Comment by afc163** [comment]
![Aug-07-2023 11-00-56](https://github.com/ant-design/ant-design/assets/507615/6d163159-137c-4884-b66c-740ffe8fc65f)

有 bug，小图不会动，点开 Modal 里的能动。

**Comment by tron-billy** [comment]
> 让后端看看是不是处理的图片设置了 GCE 播放次数，antd 侧不会对图片做特殊处理。如果没有的话，参考 @MadCcc 的回复。

后端不会做额外处理。这个应该就是前端问题，但不清楚是组件还是浏览器环境导致的，我还在排查

**Comment by tron-billy** [comment]
不好意思，最开始提出 GIF 无法循环播放的问题大概定位到了，我在 mac 上直接修改了 GIF 尺寸可能导致编码格式错乱，用别的 gif editor 编辑后上传是能看到循环播放效果的。

上传 gif 后的缩略图显示为静态，这个应该是 Upload 组件的 bug，上传 gif 返回的 thumbUrl 是 png 格式
