### ISSUE TITLE
Namespace 'React' has no exported member 'JSX'

### ISSUE THREAD

**Issue by maifeeulasad** [ant-design/ant-design#44047]
### Reproduction link

[https://github.com/maifeeulasad/react-pipeline/tree/249ea4a6de57112ea152c4b84eb0db823bf900b9](https://github.com/maifeeulasad/react-pipeline/tree/249ea4a6de57112ea152c4b84eb0db823bf900b9)

### Steps to reproduce
```sh
git clone https://github.com/maifeeulasad/react-pipeline.git
git checkout antd-v5
yarn
yarn build
```

### What is expected?

An error free build

### What is actually happening?

It's generation lots issue saying: error TS2694: Namespace 'React' has no exported member 'JSX'.

ref to job log: `https://github.com/maifeeulasad/react-pipeline/actions/runs/5769994015/job/15642603017?pr=38`

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.1.0 |
| System |  ubuntu-latest |
| Browser | Chrome / Edge |

---
I can turn of these error messages by setting `skipLibCheck` to `true`. But I'm not sure if it's the correct way or not.

Main reason behind this: we are trying to import React in a `js`/`ts` file. But we need to import them on `jsX`/`tsX` file. AFAIK.

**Comment by MadCcc** [comment]
Set `skipLibCheck` to `true` is okay.

**Comment by zombieJ** [comment]
rm `yarn.lock` and upgrade packages. Your `@types/react` is OOD.
