### ISSUE TITLE
Tree component doesn't work with React Hot Loader 3

### ISSUE THREAD

**Issue by supnate** [ant-design/ant-design#4404]
- antd 版本: 2.5.3
- 操作系统及其版本: MacOS 10.12
- 浏览器及其版本: Chrome Version 55.0.2883.95 (64-bit)

It's because RHL wraps component into a "proxy" internally for hot reloading. So item.type is the wrapped one which doesn't equal to the raw TreeNode before wrapping.

I've created a PR but can't figure out why it failed on CI, anyone could help?
https://github.com/react-component/tree/pull/52

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/3550

**Comment by afc163** [comment]
trace in #3550
