### ISSUE TITLE
How to do context menu on table rows?

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44053]
### What problem does this feature solve?

Perform actions by right clicking on the table row

### What does the proposed API look like?

N/A

**Comment by kiner-tang** [comment]
You can try this way to listen onContextMenu event to show context menu.
<img width="1341" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/2b7b2ed8-3500-4749-8978-d65cd14474f7">
