### ISSUE TITLE
能否提供一个两颗同样的树之间的传输功能，例如功能节点的权限分配？

### ISSUE THREAD

**Issue by lesskao** [ant-design/ant-design#4405]
在做管理系统的时候，有菜单树，创建角色后需要一个传输组件两面分别是菜单树，用左右箭头进行菜单的增加和回退。见附件
![qq 20161229153243](https://cloud.githubusercontent.com/assets/3353407/21538841/21bbbc74-cddc-11e6-9f46-dc47c4eb7784.jpg)

**Comment by yesmeck** [comment]
自己基于 Tree 做封装吧。
