### ISSUE TITLE
Grid responsive layout flash

### ISSUE THREAD

**Issue by oceandrama** [ant-design/ant-design#44065]
### Reproduction link

[https://codesandbox.io/s/6q34j7](https://codesandbox.io/s/6q34j7)

### Steps to reproduce

Reload the page

### What is expected?

Content is displayed in 1 column

### What is actually happening?

During the first render, 2 columns are displayed, then the layout changes to 1 column
This is clearly visible on the performance tab.
![image](https://github.com/ant-design/ant-design/assets/23439079/4f686776-5033-41ec-b04c-73ca1afbcf8f)
![image](https://github.com/ant-design/ant-design/assets/23439079/6ac2f786-b434-44cd-89b8-211aea5bc200)

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Microsoft Edge 115.0.1901.188 |

**Comment by MadCcc** [comment]
Mobile viewport (iPhone 12 pro) could reproduce.
