### ISSUE TITLE
[表单验证问题] form 使用pattern会影响required的生效

### ISSUE THREAD

**Issue by weiq** [ant-design/ant-design#4406]
操作步骤：
1. 随意输入 （可以正常验证）
2. 删除输入内容 （没有提示错误，通过验证）
期望：删除输入内容时提示这一项不能为空

示例：
http://codepen.io/weiq/pen/aBeJBR?editors=001

**Comment by ddcat1115** [comment]
好像一定要加上 type: 'string' 才 ok，或者把校验拆成两条（一条 required，一条pattern）  @yiminghe

**Comment by benjycui** [comment]
这儿把 type 设为了 `pattern` https://github.com/yiminghe/async-validator/blob/master/src/index.js#L222

然后对于 `type=pattern && value=''`，这儿会认为是存在 https://github.com/yiminghe/async-validator/blob/master/src/util.js#L64-L75

**Comment by benjycui** [comment]
> 这儿把 type 设为了 pattern https://github.com/yiminghe/async-validator/blob/master/src/index.js#L222

感觉这个设计需要讨论一下 @yiminghe ，这儿算是潜规则了。有两个方案：
1. 修改代码逻辑，不再根据 pattern 自动设置 type
2. 增加 warning：`Default rule.type will be set to 'pattern' while rule.type is RegExp and rule.type is undefined...`

**Comment by benjycui** [comment]
@weiq 先按 @ddcat1115 说的方法改代码。

**Comment by yiminghe** [comment]
重装就好了
