### ISSUE TITLE
Antd Multi select tag render exactly the html when select option is a html element

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44067]
### Reproduction link

[https://stackblitz.com/edit/react-nhqm4q?file=demo.tsx](https://stackblitz.com/edit/react-nhqm4q?file=demo.tsx)

### Steps to reproduce

Populate select option and set the label of each option to be an html element

### What is expected?

Tag render and option label should be separated ... Need a way to custom render Tag thats not dependent on only label or value

### What is actually happening?

Tag renders exactly what the select option label renders

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by linxianxi** [comment]
`tagRender` ?

**Comment by AsuraKev** [comment]
The props for tag render only supports label and value. I cannot access other object properties to build my custom tag. e.g if my option is like

{
 label: <>hi</>
value: "the value",
name: "first name",
lastName: "last name"
}

I want to be able to render my tag using the name and lastName and this is not achievable.
![image](https://github.com/ant-design/ant-design/assets/52765572/3cc13649-f690-476f-a9c1-e1209caa8583)

**Comment by linxianxi** [comment]
Can you use the full options to find?
```
tagRender={({ value }) => {
  const option = options.find(i => i.value === value);
  console.log(options.name, option.lastName)
}}

```

**Comment by AsuraKev** [comment]
that sounds like a good working solution. It would be good if we can directly access the full object as props :) happy to close. thanks
