### ISSUE TITLE
Table 销毁时有个小问题

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#4407]
表格有锁定列时, 我猜可能在每次 window 的 resize 事件触发时会延迟调整行高, 这个动作在 Unmount 的时候没有判断组件的 mount 状态, 导致路由快速切换时会报错

我做的是单页面应用, 可能页面有点特殊, 我的需求是为了避免滚动条在```>0```的位置时新页面内的 Affix 组件错位和调整其他组件的大小, 每次初始化都会模拟 ```scroll``` ```resize``` 事件, 表格就是受了我这个模拟事件的影响路由快速切换时出了这个错

![dffbfbe7-fae8-4c2e-ab0a-cc118ea5eb21](https://cloud.githubusercontent.com/assets/2884665/21540736/44df507a-cdec-11e6-8124-be886040a529.png)

(不过不会影响程序运行)

**Comment by yesmeck** [comment]
重新安装下试试。

**Comment by xutou12** [comment]
抱歉上个星期出去玩了回复晚了 ^_^  表格经测试,问题解决了
