### ISSUE TITLE
Dynamic wave effects cannot be disabled by token.motion

### ISSUE THREAD

**Issue by PhosphorusP** [ant-design/ant-design#44084]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sandpack-project-forked-8zvrct?file=/app.tsx)

### Steps to reproduce

Set `token.motion` to `false`.

### What is expected?

The components do not show dynamic wave effects if `token.motion` is set to `false`

### What is actually happening?

<img width="397" alt="image" src="https://github.com/ant-design/ant-design/assets/13076466/883b41a9-130c-4f7a-9c61-18837db423d8">

The components still show dynamic wave effects.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.18 |
| System | macOS 13.4.1 (b) |
| Browser | Chrome 114.0.5705.0 |

---
The transition duration attributes in components/wave/style.ts is hard-coded and cannot respond to different `token.motion` values.

**Comment by zombieJ** [comment]
Use ConfigProvider:
https://ant.design/components/config-provider#config-provider-demo-wave
