### ISSUE TITLE
Customize antd Upload component error tooltip message.

### ISSUE THREAD

**Issue by MrFarhan** [ant-design/ant-design#44088]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tp324c)

### Steps to reproduce

Hover over the image uploader with error

### What is expected?

Error message should be customisable. 

### What is actually happening?

Unable to customise tooltip error message.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Mac mini (M1, 2020) |
| Browser | Version 115.0.5790.114 (Official Build) (arm64) |

#### The upload error tooltip should be customisable.

![Screenshot 2023-08-07 at 6 09 13 PM](https://github.com/ant-design/ant-design/assets/26528236/d79d4cd6-aeff-430f-9d0a-961bf6cbcfe3)

**Comment by MrFarhan** [comment]
@Yuiai01 is there any other way to dynamically handle error, as this is not working in my case.

**Comment by Yuiai01** [comment]
> @Yuiai01 is there any other way to dynamically handle error, as this is not working in my case.

Maybe you can change the `fileList` dynamically.

**Comment by MrFarhan** [comment]
Tried, but not working on my code:

import React, { useState } from "react";
import { Modal, Upload } from "antd";
import type { RcFile, UploadProps } from "antd/es/upload";
import type { UploadFile } from "antd/es/upload/interface";

const getBase64 = (file: RcFile): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = (error) => reject(error);
  });

type Props = {
  image?: string;
  imageSetter?: React.Dispatch<React.SetStateAction<string>>;
  customclassName?: string;
};
const ImageUploader = ({ image, imageSetter, customclassName }: Props) => {
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewImage, setPreviewImage] = useState("");
  const [previewTitle, setPreviewTitle] = useState("");
  const [fileList, setFileList] = useState<UploadFile[]>(
    image
      ? [
          {
            uid: "1",
            name: "image.png",
            status: "done",
            url: image,
            error: {
              statusText: "File type is not supported.",
            },
          },
        ]
      : []
  );

  const handleCancel = () => {
    setPreviewOpen(false);
    imageSetter?.("");
  };

  const handlePreview = async (file: UploadFile) => {
    if (!file.url && !file.preview) {
      file.preview = await getBase64(file.originFileObj as RcFile);
    }

    setPreviewImage(file.url || (file.preview as string));
    setPreviewOpen(true);
    setPreviewTitle(file.name || file.url!.substring(file.url!.lastIndexOf("/") + 1));
  };

  const handleChange: UploadProps["onChange"] = ({ fileList: newFileList }) => {
    setFileList(newFileList);
    imageSetter?.(newFileList as any);
  };

  const uploadButton = (
    <div>
      <div style={{ marginTop: 8 }}>Upload Picture</div>
    </div>
  );

  const validTypes = ["image/jpeg", "image/jpg", "image/png"];
  const HandleBeforeUpload = (file: File) => {
    const isValidImage = validTypes.includes(file.type);
    if (!isValidImage) {
      handleCancel();
      setFileList([]);
    }
    return !isValidImage;
  };
  return (
    <>
      <Upload
        className={customclassName}
        action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
        listType="picture-card"
        fileList={fileList}
        onPreview={handlePreview}
        onChange={handleChange}
        accept="image/png, image/jpeg, image/jpg"
        beforeUpload={HandleBeforeUpload}
      >
        {fileList.length >= 1 ? null : uploadButton}
      </Upload>
      <Modal open={previewOpen} title={previewTitle} footer={null} onCancel={handleCancel}>
        <img alt="example" style={{ width: "100%" }} src={previewImage} />
      </Modal>
    </>
  );
};

export default ImageUploader;

**Comment by linxianxi** [comment]
code logic
<img width="719" alt="image" src="https://github.com/ant-design/ant-design/assets/47104575/38247f30-f38c-4fc5-a158-e16a85fca7bd">

**Comment by Yuiai01** [comment]
> 

You don't seem to have set the error dynamically in this code.

**Comment by MadCcc** [comment]
Try this: https://codesandbox.io/s/pictures-wall-antd-5-8-2-forked-8xplz2?file=/demo.tsx

**Comment by MrFarhan** [comment]
Further the tooltip error message customisation should also be mentioned in the documentation, what do you say @MadCcc ?
