### ISSUE TITLE
Case-insensitive option for searching in Select

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [ant-design/ant-design#4408]
Since that is the commonly expected behavior in Western countries, I would recommend either adding an option to make it case-insensitive or the ability to pass a custom comparison function. (+creating an example for this on your website, so that people take note of the fact that it is possible to change the behavior)

**Comment by benjycui** [comment]
Try `filterOption`, and it will be better that you can PR to improve this [demo](https://ant.design/components/select/#components-select-demo-search) with `filterOption` and make it case-insensitive.

**Comment by wahidshafique** [comment]
How can I do this in "Tree Select" ?

**Comment by gsaandy** [comment]
https://github.com/ant-design/ant-design/issues/6086#issue-227584078
The case sensitive filterOption not working in **tag mode**
see https://codesandbox.io/s/awesome-bassi-fhlw1
