### ISSUE TITLE
表单设置 rules RangePicker 的一个问题

### ISSUE THREAD

**Issue by xflife** [ant-design/ant-design#4409]
发生问题的环境是：

antd 版本:2.5.2
操作系统及其版本: mac os 10.12.2
浏览器及其版本: chrome 54
您做了什么？请提供尽可能详细的重现步骤。
在一个弹框内（modal）编写了一个 form 表单
其中有一个 form 表单是 RangePicker，所有表单都是必填的
您期待的结果是:
点击确定时候显示时间必填
实际上的结果是:
第一次点击确定RangePicker没有提示必填，但是其他都显示必填，赋值之后清空，点击确定有提示RangePicker这个表单必填，同时如果不设置RangePicker的 required 点击确定也是有提示这个表单必填的

**Comment by ddcat1115** [comment]
请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by xflife** [comment]
http://codepen.io/anon/pen/PbMdgW?editors=0010

**Comment by ddcat1115** [comment]
demo 看不到任何效果。。。

**Comment by xflife** [comment]
在 codepen 的 console 出现了 "You are using prebuilt antd,
please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size."

**Comment by afc163** [comment]
和这个没关系，你代码写错了。

**Comment by xflife** [comment]
codepen好像无法重现这个问题，我的 Form 是追加上去的

**Comment by afc163** [comment]
能重现了再 reopen 吧，否则没有你的环境，我们也无从排查。

**Comment by xflife** [comment]
我找到原因，结合表单getFieldDecorator的initialValue的初始化值出错了,因为是要传二个值，我直接写的数组，但是目前的initialValue好像认为空数组是有值得，我多做了一层判断，这个问题就没有了
