### ISSUE TITLE
Delay of dismissing previous active dropdown in a table when trigger is click

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44092]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nested-tables-antd-5-8-2-forked-xhv3g9)

### Steps to reproduce

display normal table and set one of the columns to be a dropdown and set trigger to be click. When clicking on different dropdown, the previous one disappear really slow. 

### What is expected?

Previous dropdown should be dismissed quickly

### What is actually happening?

Still able to see previous dropdown for a second.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Web |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Try wrap with `ConfigProvider` and `motion: false`. Ref: https://ant.design/docs/react/customize-theme#disable-motion

**Comment by MadCcc** [comment]
https://codesandbox.io/s/nested-tables-antd-5-8-2-forked-5lrcmp
