### ISSUE TITLE
Select 下拉框滚动出屏幕时，会出现偏移

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#44096]
### Reproduction link

[https://ant.design/components/select-cn](https://ant.design/components/select-cn)

https://github.com/ant-design/ant-design/assets/47104575/f9c6b43c-7e5a-428f-90c8-e9c28801c3f2

### Steps to reproduce

1、打开下拉框，滚动页面时下拉框到屏幕外

### What is expected?

不发生抖动

### What is actually happening?

抖动

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by ningshunqiang** [comment]
插眼
