### ISSUE TITLE
Select dropdown getPopupContainer is not working and still triggers page scroll

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44094]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/get-value-of-selected-item-antd-5-8-2-forked-3z4s76?file=/demo.tsx)

### Steps to reproduce

1. Create a Select with scroll bar
2. Scroll to the bottom
3. Scroll more and the page starts scrolling

### What is expected?

Page shouldnt be scrolling when we specified getPopupContainer where the element has position relative.

### What is actually happening?

getPopupContainer is not working and page scroll is triggered

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Web |
| Browser | Chrome |

**Comment by MadCcc** [comment]
`getPopupContainer` couldn't make body not unscrollable

**Comment by AsuraKev** [comment]
hmm, in react-select theres a prop which when specified any scrolling past the bottom will not trigger body to scroll tho. 
![image](https://github.com/ant-design/ant-design/assets/52765572/5796f24c-31d3-4139-8b9b-419f64fcef59)

**Comment by linxianxi** [comment]
> hmm, in react-select theres a prop which when specified any scrolling past the bottom will not trigger body to scroll tho. ![image](https://user-images.githubusercontent.com/52765572/258966123-5796f24c-31d3-4139-8b9b-419f64fcef59.png)

this may be what you want
https://github.com/ant-design/ant-design/issues/43506
