### ISSUE TITLE
Antd Table theme controlItemBgHover is not working

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44095]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-8-2-forked-zg6p98?file=/demo.tsx)

### Steps to reproduce

1. Create a table
2. Wrap the table with ConfigProvider
3. Apply token theme on Table and set controlItemBgHover to any color
4. hover the table rows and nothing is applied

### What is expected?

Hover theme should be set by populating controlItemBgHover 

### What is actually happening?

Effect is not picking up controlItemBgHover 

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Web |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
The background color of `controlItemBgHover` token when it is not used in the row hover of the table. You can use `tableRowHoverBg` token.

**Comment by MadCcc** [comment]
> The background color of `controlItemBgHover` token when it is not used in the row hover of the table. You can use `tableRowHoverBg` token.

`tableRowHoverBg` is not a Component Token and cannot be overrided.
Trace here: https://github.com/ant-design/ant-design/issues/41884
