### ISSUE TITLE
DatePicker[picker=week]禁用时，切换年，选中项没有跟着禁用周取消选中效果

### ISSUE THREAD

**Issue by skczjun** [ant-design/ant-design#44107]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bu-ke-xuan-ze-ri-qi-he-shi-jian-antd-4-24-13-forked-ypyfnv?file=/demo.tsx)

### Steps to reproduce

关键代码：<DatePicker picker="week" disabledDate={disabledDate} />
const disabledDate: RangePickerProps['disabledDate'] = current => {
  return current && current < moment().endOf('day');
};

点击组件，选中当前week，然后控制年，切换到2022年，因为设置的无效week是本周以前，所以去年的同样的week不能选中，但是仍然显示了高亮。

### What is expected?

disabledDate周高亮取消

### What is actually happening?

disabledDate周高亮没有取消

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.0.0 |
| System | window10 |
| Browser | chrome111.0.5563.65 |

**Comment by Yuiai01** [comment]
确实有问题，不过在 v5 最新版里没有这个问题了，应该是需要升级一下 v4 对应的 rc-picker。
<img width="364" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/4c5bd26b-da47-426b-a1d1-ea3bc73af818">
<img width="360" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/bf5385a3-404d-4f26-906d-93d447d485f5">
