### ISSUE TITLE
Calendar 组件日期单元格内容文本居中样式被覆盖

### ISSUE THREAD

**Issue by zbw-zbw** [ant-design/ant-design#44102]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wlwmkw?file=/index.css)

### Steps to reproduce

Calendar 组件日期单元格内容文本居中样式被覆盖

### What is expected?

Calendar 组件日期单元格内容文本居中

### What is actually happening?

Calendar 组件日期单元格内容文本居中样式被 table 默认样式覆盖
![image](https://github.com/ant-design/ant-design/assets/64134946/30a4d469-27e7-4564-be5d-636933e89c00)

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/3a5f5e93-c994-4eb3-a10f-4b50d7627b2a)
复现里没有发现问题

**Comment by zbw-zbw** [comment]
> ![image](https://user-images.githubusercontent.com/27722486/259002611-3a5f5e93-c994-4eb3-a10f-4b50d7627b2a.png) 复现里没有发现问题

看下我本地项目的表现，table 的默认样式 text-align: start 覆盖了组件的 text-align: center
![image](https://github.com/ant-design/ant-design/assets/64134946/7445424f-a320-480a-aad3-c13010da0549)

**Comment by zbw-zbw** [comment]
> > ![image](https://user-images.githubusercontent.com/27722486/259002611-3a5f5e93-c994-4eb3-a10f-4b50d7627b2a.png) 复现里没有发现问题
> 
> 看下我本地项目的表现，table 的默认样式 text-align: start 覆盖了组件的 text-align: center ![image](https://user-images.githubusercontent.com/64134946/259063237-7445424f-a320-480a-aad3-c13010da0549.png)

我需要单独设置 table { text-align: center } 解决问题

**Comment by Yuiai01** [comment]
阿勒，怎么 table 的样式不一样，是不是本地 table 也重置了
<img width="1176" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/1fe0f32c-3b42-4525-b93d-93d2bbd6b0ee">

**Comment by zbw-zbw** [comment]
> 阿勒，怎么 table 的样式不一样，是不是本地 table 也重置了 <img alt="image" width="1176" src="https://user-images.githubusercontent.com/112228030/259065886-1fe0f32c-3b42-4525-b93d-93d2bbd6b0ee.png">

用户代理样式表里的样式是默认样式吧，我也很好奇为啥不一样咧

**Comment by afc163** [comment]
最好能给个重现，我们猜不出来的。

**Comment by zbw-zbw** [comment]
> 最好能给个重现，我们猜不出来的。

破案了。我本地项目的 html 里没有声明 `<!DOCTYPE html>` ， table  user agent stylesheet：

![image](https://github.com/ant-design/ant-design/assets/64134946/eb98e67d-f20d-49a0-9de9-ec6007cd20e4)

声明了 ` <!DOCTYPE html>` table  user agent stylesheet：
![image](https://github.com/ant-design/ant-design/assets/64134946/3ed59d6c-cc9e-464b-a9ba-3602f51dd31e)

**Comment by yoyo837** [comment]
所以, 我们可以安全的关闭这个了吗?

**Comment by zbw-zbw** [comment]
结论：HTML 5 及以上 的的 table 默认样式是包含 text-align: center 的，反之则不包含。

**Comment by zbw-zbw** [comment]
> 所以, 我们可以安全的关闭这个了吗?

嗯嗯
