### ISSUE TITLE
When you have a few items in the dropdown and the default value is at the very bottom. Select flicks when opened first time. Occurs when motion is turned off

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44100]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-8-2-forked-wsfl98?file=/demo.tsx)

### Steps to reproduce

1. Create a Select with few dropdown items 
2. Set default value thats near the bottom of the dropdown
3. turn off motion in ConfigProvider
4. Click on the Select for the first time, flicking behaviour is present
5. Click again, flicking doesnt appear again

### What is expected?

Should it flick at all?

### What is actually happening?

Flicking on first time display

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by MadCcc** [comment]
It's the scroll animation of virtual list. Seems it won't be turned off by `motion: false`, but you can add `virtual={false}` to Select to disable virtual list

**Comment by AsuraKev** [comment]
thanks, I would still need to virtual list feature tho for performance. Its not a deal breaker, but it would be great to rid of the flickering :)

**Comment by zombieJ** [comment]
Currently it use raf to force align to the position. It may flick when option height not ready. It's a bug.

**Comment by bbb169** [comment]
> Currently it use raf to force align to the position. It may flick when option height not ready. It's a bug
Could I debounce function scrollIntoView to solve this problem? where multiple calls to scroll for a short period of time only take the last one.
https://github.com/react-component/select/blob/2decf052c3f93c1b9d33651c411b16dc81311987/src/OptionList.tsx#L76

**Comment by bbb169** [comment]
> Currently it use raf to force align to the position. It may flick when option height not ready. It's a bug.

Could I debounce function scrollIntoView to solve this problem? where multiple calls to scroll for a short period of time only take the last one.
https://github.com/react-component/select/blob/2decf052c3f93c1b9d33651c411b16dc81311987/src/OptionList.tsx#L76

**Comment by bbb169** [comment]
这个问题定位到rc-virtual-list， https://github.com/bbb169/virtual-list/blob/166aba7887ab21cc0db05e3eaed07f6fc14d5dec/src/List.tsx#L214，这行代码导致虚拟列表初始化时scrollheight发生变化，从而产生了抖动。

**Comment by bbb169** [comment]
> 这个问题定位到rc-virtual-list， [https://github.com/bbb169/virtual-list/blob/166aba7887ab21cc0db05e3eaed07f6fc14d5dec/src/List.tsx#L214，这行代码导致虚拟列表初始化时scrollheight发生变化，从而产生了抖动。](https://github.com/bbb169/virtual-list/blob/166aba7887ab21cc0db05e3eaed07f6fc14d5dec/src/List.tsx#L214%EF%BC%8C%E8%BF%99%E8%A1%8C%E4%BB%A3%E7%A0%81%E5%AF%BC%E8%87%B4%E8%99%9A%E6%8B%9F%E5%88%97%E8%A1%A8%E5%88%9D%E5%A7%8B%E5%8C%96%E6%97%B6scrollheight%E5%8F%91%E7%94%9F%E5%8F%98%E5%8C%96%EF%BC%8C%E4%BB%8E%E8%80%8C%E4%BA%A7%E7%94%9F%E4%BA%86%E6%8A%96%E5%8A%A8%E3%80%82)

我来fix吧

**Comment by harshal255** [comment]
> It's the scroll animation of virtual list. Seems it won't be turned off by `motion: false`, but you can add `virtual={false}` to Select to disable virtual list

Thankyou for sharing, that working properly
