### ISSUE TITLE
Form表单中登录框checkbox删除掉valuePropName="checked"属性后，后续所有的表单提交checkbox的值都是true

### ISSUE THREAD

**Issue by huangrenfang** [ant-design/ant-design#44108]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/deng-lu-kuang-antd-5-8-2-forked-t89g35)

### Steps to reproduce

<Form.Item name="remember" valuePropName="checked" noStyle>
          <Checkbox>Remember me</Checkbox>
</Form.Item>
删除valuePropName="checked"后提交
尝试选中与未选中checkbox， 发现返回值都是true

### What is expected?

未选中checkbox返回false

### What is actually happening?

未选中checkbox返回true

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome115 |

**Comment by Wxh16144** [comment]
> 删除valuePropName="checked"后提交

为什么要删除呢？ 就是这句话导致的 bug 呀

**Comment by huangrenfang** [comment]
嗯嗯，如果我不需要传入checked该怎么处理呢

**Comment by huangrenfang** [comment]
@Wxh16144 诉求是checkbox默认不选中，是需要valuePropName传入别的值嘛

**Comment by Wxh16144** [comment]
> 诉求是checkbox默认不选中

将 `<Form />` 的 `initialValues` 中的 checkbox 的 name 设置为 false

**Comment by Wxh16144** [comment]
<img width="897" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/11f7349a-ed1a-470a-a7eb-1bc5a6df58d0">

**Comment by Wxh16144** [comment]
> OK, 我修改之后发现好使了。为啥不支持删掉valuePropName="checked"呀，没有的话表示默认false，现在的交互感觉有点奇怪😂

![image](https://github.com/ant-design/ant-design/assets/32004925/2a53fb42-1771-4639-bc94-dc8ebf0f900a)
