### ISSUE TITLE
Issue with Popover Closing on Mouse Event in Latest Ant Design 

### ISSUE THREAD

**Issue by DeepakM02** [ant-design/ant-design#44119]
### Reproduction link

[https://stackblitz.com/edit/react-msxzap?file=demo.tsx](https://stackblitz.com/edit/react-msxzap?file=demo.tsx)

### Steps to reproduce

1. Open a page with a popover component that contains a modal.
2. Click to open the popover.
3. Inside the popover, click to open the modal.
4. Observe that the popover closes unexpectedly.

### What is expected?

n previous versions (e.g., 5.2.1) of Ant Design, the popover should remain open even when interacting with components inside it, such as the modal. Clicking on the modal should not trigger the popover to close.

### What is actually happening?

In the latest version of Ant Design, the popover closes when a user interacts with components within it, such as clicking on a modal.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Mac OS 13.2 |
| Browser | Arc Version 1.2.1 (40552) |

---
This regression in behavior is impacting the user experience and needs to be addressed to maintain consistent functionality between different versions of Ant Design.

**Comment by MadCcc** [comment]
Conflict with hover trigger, which expect that hovering modal inside Popover should not open Popover itself.

**Comment by zombieJ** [comment]
It's by design to fix `stopPop` makes popup un-closable. ref: https://github.com/react-component/trigger/pull/412

Since this is a conflict requirement, we may not fix this. Sorry about this. But you can do it as control:

https://stackblitz.com/edit/react-msxzap-axyhn1?file=demo.tsx

**Comment by DeepakM02** [comment]
Thanks @zombieJ
