### ISSUE TITLE
table设置默认选中项的 key，如何能同时能拿到selectedRows的值

### ISSUE THREAD

**Issue by wj0101** [ant-design/ant-design#44113]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-94nj9s?file=/index.js)

### Steps to reproduce

设置默认选中

### What is expected?

拿到selectedRows的值

### What is actually happening?

无法获取到selectedRows，chatGpt 建议用tableRef.current.getSelectedRows()，实际没有此方法

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | mac |
| Browser | chorm |

**Comment by zombieJ** [comment]
从 `dataSource` 里按照 `key` 过滤出来哈~

另外，GPT 会瞎编回答，请以官方文档为准~
