### ISSUE TITLE
Table组件新增props：empty

### ISSUE THREAD

**Issue by Perseman** [ant-design/ant-design#44110]
### What problem does this feature solve?

我有一个自定义的empty需要使用，且Table也需要loading状态，但是现在的table不支持empty的设置。

例如这种场景的代码需要写成以下这样： https://codesandbox.io/s/antd-reproduction-template-forked-34lr8d?file=/index.js

这么写显得非常的难受，并且也不能使用Table的loading。

### What does the proposed API look like?

empty?: ReactNode
支持自定义空数据的情况展示

**Comment by linxianxi** [comment]
ConfigProvider 可以配置 renderEmpty

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7690#issuecomment-331053908

**Comment by chongqiangchen** [comment]
> [#7690 (comment)](https://github.com/ant-design/ant-design/issues/7690#issuecomment-331053908)

我尝试动态设置，不会变更，这个该如何处理

```
locale={{emptyText: !!search ? "暂无数据" : "请输入查询内容"}}
```
