### ISSUE TITLE
级联控件获焦与键盘事件

### ISSUE THREAD

**Issue by sayonly** [ant-design/ant-design#4411]
Cascader控件在点击时没有自动聚焦，且未像其它表单控件一样，提供键盘事件支持。

发生问题的环境：
ant ："1.10.0"
操作系统：Win7 64位旗舰版
浏览器版本 ：chrome  55.0.2883.87 m

做了什么：

从ant中引入Cascader组件，演示demo实例时，点击弹出，并未自动聚焦，但点击边线弹出时可以获焦

期待的结果：
希望可以如官网一般正常显示，且现在基于业务需求，需要提供键盘事件支持，发现组件外部操作困难，能否告知解决途径

**Comment by benjycui** [comment]
你说的是哪个 demo..

**Comment by sayonly** [comment]
所有都是，但codepen上难以重现，目前正在查找原因，主要是键盘事件时遇到的问题，不知外部是否可实现键盘事件这个需求？

**Comment by benjycui** [comment]
> 所有都是

我不觉得有问题，麻烦指明那个 demo 和重现步骤。

**Comment by afc163** [comment]
1. 聚焦的问题请升级到 1.11.4 或 2.x。
2. 键盘事件确实尚未支持，working on it.

**Comment by RobertM574** [comment]
希望添加，级联可多选
