### ISSUE TITLE
Datepicker select time scroll issue

### ISSUE THREAD

**Issue by elodszopos** [ant-design/ant-design#4412]
#### 发生问题的环境是：

- antd 版本: 2.5.2
- 操作系统及其版本: Mac OSX Siera 10.12.1
- 浏览器及其版本: Chrome 54.0.2840.98 64bit

#### 您做了什么？请提供尽可能详细的重现步骤。

Rendered a `Datepicker` with `showTime`

#### 您期待的结果是:

Time picker unordered list should not scroll past available options. Picker section should fit into container element.

![image](https://cloud.githubusercontent.com/assets/4669986/21550417/6b299dba-ce02-11e6-84c5-0fca3c763c6d.png)

#### 实际上的结果是:

Timer picker options can get scrolled past, going into white emptiness.

![image](https://cloud.githubusercontent.com/assets/4669986/21550402/4ed84d14-ce02-11e6-8b81-dd8a80c15428.png)

![image](https://cloud.githubusercontent.com/assets/4669986/21550429/87f1c1fc-ce02-11e6-81aa-56e75cd60dab.png)

If I only have 4 possible minute options, I can even scroll past all results, can't see anything in view to select.

![image](https://cloud.githubusercontent.com/assets/4669986/21550459/a526bab6-ce02-11e6-858d-b8d405862956.png)

#### 可重现的在线演示

http://codepen.io/anon/pen/Lbwdxe?editors=001

PS. Google translate is a good friend.

**Comment by benjycui** [comment]
We need to provide English version issue template now..

**Comment by grgur** [comment]
I could replicate this on iOS 10.1 and Android 7.1
