### ISSUE TITLE
allowClear prop in DatePicker and TimePicker doesn't work

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#44128]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pickers-antd-5-8-2-forked-k7zz5h)

### Steps to reproduce

1. Import one of picker
2. add to component return
3. set prop allowClear

### What is expected?

- When I set allowClear prop value equal false, I expect that clear icon (default as gray cross) will not be appeared and user could not reset time.
- When I set allowClear prop value equal some icon, I expect that clear icon will be display custom iconx

### What is actually happening?

It doesn't matter what value is set for allowClear prop - It doesn't affect on clear icon

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome 115.0.5790.170 (Official Build) (64-bit) |

**Comment by kiner-tang** [comment]
fix in 
- #44015

need publish patch version @zombieJ .

**Comment by evgeniyworkbel** [comment]
> fix in
> 
> * [fix: RangePicker allowClear does not disable the clear button #44015](https://github.com/ant-design/ant-design/pull/44015)
> 
> need publish patch version @zombieJ .

the bug will be fix in next patch version?

**Comment by kiner-tang** [comment]
> > In old version, it work as expect: https://codesandbox.io/s/pickers-antd-5-8-2-forked-v98x4y?file=/package.json
> > cc @kiner-tang
> 
> Also note that it is not set custom icon. Sample https://codesandbox.io/s/pickers-antd-5-8-2-forked-4cpzlh?file=/demo.tsx

It also  be fixed in #44015.

![image](https://github.com/ant-design/ant-design/assets/10286961/72c9ae0d-f81e-4901-880f-fc74829f7f4c)

**Comment by evgeniyworkbel** [comment]
> > > In old version, it work as expect: https://codesandbox.io/s/pickers-antd-5-8-2-forked-v98x4y?file=/package.json
> > > cc @kiner-tang
> > 
> > 
> > Also note that it is not set custom icon. Sample https://codesandbox.io/s/pickers-antd-5-8-2-forked-4cpzlh?file=/demo.tsx
> 
> It also be fixed in #44015.
> 
> ![image](https://user-images.githubusercontent.com/10286961/259355201-72c9ae0d-f81e-4901-880f-fc74829f7f4c.png)

Hm...this is my [sample with antd 5.8.2](https://codesandbox.io/s/pickers-antd-5-8-2-forked-k7zz5h?file=/package.json). Prop allowClear doesn't work

**Comment by kiner-tang** [comment]
> > > > In old version, it work as expect: https://codesandbox.io/s/pickers-antd-5-8-2-forked-v98x4y?file=/package.json
> > > > cc @kiner-tang
> > > 
> > > 
> > > Also note that it is not set custom icon. Sample https://codesandbox.io/s/pickers-antd-5-8-2-forked-4cpzlh?file=/demo.tsx
> > 
> > 
> > It also be fixed in #44015.
> > ![image](https://user-images.githubusercontent.com/10286961/259355201-72c9ae0d-f81e-4901-880f-fc74829f7f4c.png)
> 
> Hm...this is my [sample with antd 5.8.2](https://codesandbox.io/s/pickers-antd-5-8-2-forked-k7zz5h?file=/package.json). Prop allowClear doesn't work

It will be fixed in 5.8.3 because a patch has not been released yet.

**Comment by evgeniyworkbel** [comment]
> > > > > In old version, it work as expect: https://codesandbox.io/s/pickers-antd-5-8-2-forked-v98x4y?file=/package.json
> > > > > cc @kiner-tang
> > > > 
> > > > 
> > > > Also note that it is not set custom icon. Sample https://codesandbox.io/s/pickers-antd-5-8-2-forked-4cpzlh?file=/demo.tsx
> > > 
> > > 
> > > It also be fixed in #44015.
> > > ![image](https://user-images.githubusercontent.com/10286961/259355201-72c9ae0d-f81e-4901-880f-fc74829f7f4c.png)
> > 
> > 
> > Hm...this is my [sample with antd 5.8.2](https://codesandbox.io/s/pickers-antd-5-8-2-forked-k7zz5h?file=/package.json). Prop allowClear doesn't work
> 
> It will be fixed in 5.8.3 because a patch has not been released yet.

Now i got it, thank you

**Comment by kiner-tang** [comment]
v5.8.3 has been released. Try it again.
https://github.com/ant-design/ant-design/releases/tag/5.8.3

**Comment by quyphan97** [comment]
please check "antd": "^5.10.1" onClick in clearIcon not working :((
`allowClear={{
                    clearIcon: (
                      <CloseCircleOutlined
                        onClick={() => {
                          alert("oke");
                        }}
                      />
                    ),
                  }}`
