### ISSUE TITLE
表格被fixed的项，不受rowClassName控制

### ISSUE THREAD

**Issue by 819049639** [ant-design/ant-design#44124]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-ge-fixedxiang-bu-shou-rowclassnameshu-xing-kong-zhi-antd-5-8-2-forked-qsmjr2?file=/index.tsx)

### Steps to reproduce

被fixed固定的项修改了 rowClassName 不生效

### What is expected?

原本设计如此？或者是bug？

### What is actually happening?

希望得到答复，或解决问题

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | MacOS 13.4.1 (c) (22F770820d) |
| Browser | Microsoft Edge 版本 115.0.1901.188 (正式版本) (x86_64) |

**Comment by Wxh16144** [comment]
确实固定列的 rowClassName 实没生效，看着挺奇怪。等下午周会确认一下是不是 by design 吧

**Comment by MadCcc** [comment]
固定列有自己的背景色，这样就行了
https://codesandbox.io/s/biao-ge-fixedxiang-bu-shou-rowclassnameshu-xing-kong-zhi-antd-5-8-2-forked-9jp4yz?file=/index.css

**Comment by 819049639** [comment]
感谢各位大佬

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31483#issuecomment-884847331
