### ISSUE TITLE
checkbox 官方示例 defaultCheckedList 如果就是全选的相同值，全选按钮应该勾上

### ISSUE THREAD

**Issue by ygqygq2** [ant-design/ant-design#44123]
![image](https://github.com/ant-design/ant-design/assets/17672440/5fff5cce-3741-400d-b4ed-7c9f39320661)

### What problem does this feature solve?

是否全选应该加载时就判断，增加体验。而不是需要用户额外做处理。

### What does the proposed API look like?

```
const plainOptions = ['Apple', 'Pear', 'Orange'];
const defaultCheckedList = ['Apple', 'Pear', 'Orange' ];
```

**Comment by linxianxi** [comment]
应该你 checkAll 默认为 true 就行了

**Comment by ygqygq2** [comment]
> 应该你 checkAll 默认为 true 就行了

你说的是自己额外做处理。这肯定是可以，关键是这应该是它本身功能才对，比如默认列表为空。“全选”状态也不对
![image](https://github.com/ant-design/ant-design/assets/17672440/e0791435-17a6-4f88-97fd-647b7bbc4056)
