### ISSUE TITLE
Message 消息 maxCount 异常

### ISSUE THREAD

**Issue by cqh963852** [ant-design/ant-design#44134]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qi-ta-ti-shi-lei-xing-antd-5-8-2-forked-qvd7lt?file=/demo.tsx)

### Steps to reproduce

切换到其他标签页，等一会。切换回来，maxCount 会有一瞬间的失效

### What is expected?

maxCount 在这种情况下应该正常

### What is actually happening?

出现大量的message，数量超过 maxCount

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react18 |
| System | win11 |
| Browser | chrome 115 |

---
https://codesandbox.io/s/qi-ta-ti-shi-lei-xing-antd-4-24-13-forked-nfj4ss?file=/demo.tsx:489-527

antd4 也有同类问题

**Comment by zombieJ** [comment]
Chrome 切出去的时候动画会暂停，使得 message 会堆积在消失阶段。等切换回去的时候一次性触发动画，导致看起来超出了上限。实际上还是被 maxCount 控制的。

在组件侧做会比较黑，之后会改造 message 和 notification 的堆叠设计。就暂时先不修了哈~

**Comment by cqh963852** [comment]
@zombieJ 我们fork了一份 antd 4 和 notification 的代码。

> 之后会改造 message 和 notification 的堆叠设计

这里说的设计,可以提供一个思路吗？
