### ISSUE TITLE
Configure theme without webpack?

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design#4413]
Is there anyway to configure the theme without using webpack? I use meteor in most projects and tapping into webpack isn't that straight forward.

Are there any other strategies to do this? I usually use muiTheme() from material-ui theme when I need to customize, but am trying to use ant in a project now. I need to get custom fonts and preferably change some colors!

aside from this road block, ant is awesome so far!

**Comment by afc163** [comment]
I like material-ui's `ThemeProvider` but we are unlikely to change less variables because of the compatible issue.

You can use any http://lesscss.org/usage/#using-less-in-the-browser-modify-variables solution as long as you import less style. So, what is your assets workflow exactly?

**Comment by acomito** [comment]
Well, I've just been playing around with ant in a side project. Right now I'm importing them as needed in component files:

```
import 'antd/lib/card/style/css';
import 'antd/lib/modal/style/css';
import { Card, Modal } from 'antd';
```

**Comment by afc163** [comment]
https://ant.design/docs/react/customize-theme#2)-Overriding-Less-variables-(alternative-way)
