### ISSUE TITLE
<Input>: Render addonBefore/addonAfter as <label> and attach it to the <input /> tag

### ISSUE THREAD

**Issue by barbogast** [ant-design/ant-design#44133]
### What problem does this feature solve?

First of all, thanks a ton for this great library :-)

When using the `<Input />` component with `addonBefore` or `addonAfter` the resulting HTML doesn't treat the text as labels for the `<input />` tag.

Would it be possible to either wrap the `<input />` and the contents of `addonBefore` and `addonAfter` into `<label>` tags or attach them to the `<input />` tag via the `id` and `for` attributes? See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) for details.

I guess the latter would mean that the user has to provide an `id` prop to the `<Input />` component.

Thanks for considering.

### What does the proposed API look like?

No new API required.

**Comment by MadCcc** [comment]
Currently we do not treat `addon` as label for Input, because there maybe other data entry components like Select in it.
In your case, you can pass `label` component as `addon` of Input and add `for` yourself.
