### ISSUE TITLE
水平Menu子菜单选择项背景色错误

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#4414]
#### 发生问题的环境是：

- antd 版本: 2.5.3
- 操作系统及其版本: deepin15.3
- 浏览器及其版本: chrome57.0.2950.4 dev (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。

使用带有Submenu的水平Menu

#### 您期待的结果是:

像官网一样正常显示 

#### 实际上的结果是:

菜单项背景色不正确

#### 可重现的在线演示

https://codepen.io/infeng/pen/ObKmeB?editors=1010

**Comment by infeng** [comment]
水平导航的菜单项背景色应该都是透明

**Comment by benjycui** [comment]
怎么我不觉得有问题。。

**Comment by infeng** [comment]
theme为Dark的时候，子菜单选择项的背景色有问题

**Comment by afc163** [comment]
发现了。

**Comment by infeng** [comment]
@afc163 这样改还是不行
