### ISSUE TITLE
使用Table组件时，结合react-window 实现虚拟列表，使用fixed属性 无法固定第一列数据

### ISSUE THREAD

**Issue by xiangdongbu** [ant-design/ant-design#44145]
### Demo

[demo](https://codesandbox.io/embed/xu-ni-lie-biao-antd-5-8-2-forked-4vsgll?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

column设置fixed 无法固定第一列

### What is expected?

左右滑动时可以固定第一列

### What is actually happening?

左右滑动时无法固定第一列

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | MacOS 13.4.1 |
| Browser | 114.0.5735.198 |

**Comment by xiangdongbu** [comment]
demo[https://codesandbox.io/embed/xu-ni-lie-biao-antd-5-8-2-forked-4vsgll?fontsize=14&hidenavigation=1&theme=dark]

**Comment by afc163** [comment]
虚拟列表现在没办法和固定列一起用，可以跟踪 https://github.com/ant-design/ant-design/issues/20339
