### ISSUE TITLE
Multi select clears select item when clicking on the tag on mobile view

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44152]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9s75gz)

### Steps to reproduce

open  the multi select in mobile view and select a few items. Tap on clear all icon, and it only toggles the dropdown and does not remove all items in the box

### What is expected?

tap on clear all icon should clear away all selected items

### What is actually happening?

click on clear all icon only toggle the visibility of the dropdown and doesnt clear items

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
The item should only be cleared when click directly on the cross  icon

https://github.com/ant-design/ant-design/assets/52765572/b074ed0e-4203-404a-8961-b6d584bfff0e

**Comment by CYBYOB** [comment]
我自己试了下，目前效果是符合预期的

**Comment by ZWkang** [comment]
@MadCcc It seems to have been resolved, and it no longer exists in the latest version.
