### ISSUE TITLE
Form.List 里面使用Upload受控组件 上传状态一直卡在uploading怎么解决

### ISSUE THREAD

**Issue by Billyppppp** [ant-design/ant-design#44156]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-y9vgcf?file=/index.js)

### Steps to reproduce

 <Form.Item
      dependencies={['enableByMobile', 'validity', 'filter2AgentByMobileItems']}
      required
      noStyle
    >
      {({ getFieldValue }) =>
        getFieldValue('enableByMobile') ? (
          <Form.List name="filter2AgentByMobileItems">
            {(fields, { add, remove }) => (
              <Space
                style={{ width: '100%' }}
                direction="vertical"
                size="middle"
              >
                {fields?.map(({ key, name, fieldKey, ...restField }, index) => (
                  <Row gutter={18} key={key   uid()}>
                    <Col span={20}>
                      <Card size="small" style={{ paddingTop: 10 }}>
                        <Form.Item
                          label="拦截名单"
                          name={[name, 'mobiles']}
                          labelCol={{ span: 3 }}
                          valuePropName="fileList"
                          getValueFromEvent={normFile}
                        >
                          <Upload
                            maxCount={1}
                            accept=".xls"
                            name="mobiles"
                            {...uploadProps}
                            beforeUpload={beforeUpload}
                            onChange={(info) => handleFileChange(info, name)}
                            showUploadList={{ showDownloadIcon: true }}
                            fileList={fileList?.length ? fileList[name] : []}
                            // fileList={getFieldValue([
                            //   'filter2AgentByMobileItems',
                            //   index,
                            //   'mobiles',
                            // ])}
                          >

### What is expected?

能获取到上传状态‘done’

### What is actually happening?

在onChange事件中获取上传状态，上传状态一直卡在uploading，没有调用上传接口，beforeUpload没有返回false

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 17.0.2 |
| System | Mac OS |
| Browser | Google Chrome版本 115.0.5790.170（正式版本） (arm64) |

**Comment by zombieJ** [comment]
你的 codesandbox 没有用 Upload

**Comment by Billyppppp** [comment]
> 你的 codesandbox 没有用 Upload

https://codesandbox.io/s/antd-reproduction-template-forked-mh8z76

**Comment by afc163** [comment]
@Billyppppp 你给的例子会报错。

**Comment by Billyppppp** [comment]
> @Billyppppp 你给的例子会报错。
这是一个组件 有引用关系 麻烦您看看有没有使用错误

**Comment by afc163** [comment]
```diff
- valuePropName="mobiles"
+ valuePropName="fileList"
```
