### ISSUE TITLE
Descriptions column 属性设置响应式的对象写法，控制台打印 “Warning: [antd: Descriptions] Sum of column `span` in a line not match `column` of Descriptions.”

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design#44159]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/descriptionslie-shu-kong-zhi-tai-jing-gao-498wzz?file=/src/App.js)

### Steps to reproduce

<img width="648" alt="image" src="https://github.com/ant-design/ant-design/assets/5070722/d1350470-f769-4e21-a2d0-991d4b6f03eb">

<img width="710" alt="image" src="https://github.com/ant-design/ant-design/assets/5070722/48cf4568-e993-4352-a3f9-4f044d2eaee9">

### What is expected?

应当获取视窗宽度对应的断点值去判断，如果没有小于 `span`  不需要打印警告信息。

如上面示例，应该在视窗宽度小于576时，再打印警告信息。否则只要设置了断点和 `span` 基本上都会有这个警告信息。

### What is actually happening?

-

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | MacOS 12 |
| Browser | chrome |

**Comment by zombieJ** [comment]
这个 warning 就是为了告诉你各个响应式下可能出现的问题，否则开发者的窗口没有缩放到对应值永远都不会知道配置错了哈~

**Comment by caijf** [comment]
> 这个 warning 就是为了告诉你各个响应式下可能出现的问题，否则开发者的窗口没有缩放到对应值永远都不会知道配置错了哈~

不是配置错，是Descripts.Item  span不支持响应式配置啊。

例如有些场景默认需要2列展示，但是在小屏幕下要1列展示。

**Comment by caijf** [comment]
可以考虑下 reopen ？

**Comment by Huaxink** [comment]
我也有这个报错，你没描述清楚，这个功能比较鸡肋，容器布局响应式，但是子项目span又不是响应式
比如 一个 remark字段，文本很长，不管什么屏幕宽度下都需要顶格占用全部空间的，有些项目xxl下占用一个格子，md下占用两个格子
可能你需要重新改下描述，感觉这就是个bug

**Comment by caijf** [comment]
> 我也有这个报错，你没描述清楚，这个功能比较鸡肋，容器布局响应式，但是子项目span又不是响应式 比如 一个 remark字段，文本很长，不管什么屏幕宽度下都需要顶格占用全部空间的，有些项目xxl下占用一个格子，md下占用两个格子 可能你需要重新改下描述，感觉这就是个bug

这里他们可能不看了，你可以重新提个issue试试
