### ISSUE TITLE
RangePicker allowClear={false} not working

### ISSUE THREAD

**Issue by zuyetawarmatik** [ant-design/ant-design#44168]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v858xt?file=/demo.tsx)

### Steps to reproduce

Using the antd example, passing allowClear={false}

### What is expected?

Should not show clear button for allowClear={false}

### What is actually happening?

Still shows the clear button

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18 |
| System | Mac |
| Browser | Chrome |

**Comment by kiner-tang** [comment]
It is same issue: https://github.com/ant-design/ant-design/issues/44128. It will be fixed after v5.8.3 publish

**Comment by kiner-tang** [comment]
v5.8.3 has been released. Try it again.
https://github.com/ant-design/ant-design/releases/tag/5.8.3
