### ISSUE TITLE
table可以指定某个单元格的颜色吗？

### ISSUE THREAD

**Issue by mineralres** [ant-design/ant-design#4416]
table可以指定某个单元格的颜色吗？

#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by yesmeck** [comment]
自己通过 column.className 配合相应的 css 实现。

使用问题建议到 SegmentFault 上问。

**Comment by bytedaring** [comment]
具体是怎么解决的？

**Comment by bytedaring** [comment]
https://codepen.io/anon/pen/EmaRJL?editors=0110
