### ISSUE TITLE
【theme compact.less】变量名不同，值相同

### ISSUE THREAD

**Issue by Perisiguiendo** [ant-design/ant-design#44169]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/4.24.13/components/style/themes/compact.less](https://github.com/ant-design/ant-design/blob/4.24.13/components/style/themes/compact.less)

### Steps to reproduce

// vertical paddings
@padding-lg: 16px; // containers
@padding-md: 8px; // small containers and buttons
@padding-sm: 8px; // Form controls and items
@padding-xs: 4px; // small items
@padding-xss: 0px; // more small

// vertical margins
@margin-lg: 16px; // containers
@margin-md: 8px; // small containers and buttons
@margin-sm: 8px; // Form controls and items
@margin-xs: 4px; // small items
@margin-xss: 0px; // more small

有两个相同数值的变量

### What is expected?

@padding-md与@padding-sm有区分
@margin-md 与@margin-sm: 8px有区分

### What is actually happening?

无区分

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 17 |
| System | mac m2 pro |
| Browser | chrome |

**Comment by zombieJ** [comment]
By design. 为了方便开发者覆盖用。你可以试试分别改一下看看效果。
