### ISSUE TITLE
form.setFieldsValue not working as expected if a value is an object

### ISSUE THREAD

**Issue by leftstick** [ant-design/ant-design#44165]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-8-2-forked-dl7zm5?file=/demo.tsx)

### Steps to reproduce

1. Note: the value displayed is: `{"name":"hello"}`
2. Click "change user" button
3. the value displayed become to: `{"name":"hello","age":49}`

### What is expected?

the value displayed after clicking "change user" button should be: `{"age":49}`

### What is actually happening?

the value displayed after clicking "change user" button is: `{"name":"hello","age":49}`

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.1.0 |
| System | macOS Monterey version 12.2.1 |
| Browser | Microsoft Edge Version 115.0.1901.200 (Official build) (arm64) |

---
Why `form.setFieldsValue` not replace the `user` but merging with the previous value

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28314#issuecomment-744253708

**Comment by zombieJ** [comment]
`setFieldsValue` is patch update. It will not remove exist value.

**Comment by afc163** [comment]
Try `setFieldValue` https://codesandbox.io/s/ji-ben-shi-yong-antd-5-8-2-forked-lvvdt4?file=/demo.tsx:944-957
