### ISSUE TITLE
Modal.destroyAll() not working with Nextjs version 13.4.13

### ISSUE THREAD

**Issue by pferreirafabricio** [ant-design/ant-design#44160]
### Reproduction link

[https://github.com/pferreirafabricio/issue-next-antd-modal-destroy](https://github.com/pferreirafabricio/issue-next-antd-modal-destroy)

### Steps to reproduce

1. Init a new Nextjs project with the version v13.4.14
2. Add antd as a dependency
3. Create a new confirm modal with the `confirm` method from `antd/es/modal/confirm`
4. Try to close all the modals with `Modal.destroyAll()` method inside `onClick` property inside the `footer` attribute of the `confirm` method

### What is expected?

When `Modal.destroyAll()` is called all the modals should be closed.

### What is actually happening?

The modal opened doesn't close.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2.0 |
| System | Windows 11 22H2 OS Build 22621.2134 |
| Browser | Microsoft Edge Version 115.0.1901.200 |

---
I have a project running with Nextjs v13.4.4 and I decided to upgrade to the latest version currently available (v13.4.13). After the upgrade, I noticed that none of the modals that have been closed by `Modal.destroyAll()` are in fact being closed.

**Comment by afc163** [comment]
https://github.com/afc163/issue-next-antd-modal-destroy/pull/1
