### ISSUE TITLE
Modal修改getContainer后会导致Modal的子组件被销毁(unmount)并重建(remount)

### ISSUE THREAD

**Issue by wangzhengbo** [ant-design/ant-design#44172]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-8-3-forked-z36826?file=/demo.tsx)

### Steps to reproduce

1. 打开弹窗
2. 点击弹窗内的按将弹窗的getContainer在body和html节点之间切换

### What is expected?

Modal的Child组件不被销毁

### What is actually happening?

Modal的Child组件会被销毁(unmount)并重建(remount)

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome 115 |

**Comment by zombieJ** [comment]
React 的 `createPortal` 切换 `container` 时会，重新卸载并装在。这个是预期行为，antd 侧做不了什么哈：

https://codesandbox.io/s/ji-ben-antd-5-8-3-forked-p5ly2d?file=/demo.tsx:556-570
