### ISSUE TITLE
官网中英文切换有bug

### ISSUE THREAD

**Issue by liangjingjing** [ant-design/ant-design#4417]
#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by yesmeck** [comment]
什么 bug？别卖关子啊。。。

**Comment by afc163** [comment]
It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).
