### ISSUE TITLE
Children of the space component cannot have the space classnames

### ISSUE THREAD

**Issue by byaman** [ant-design/ant-design#44182]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-8-2-forked-c3sxfh)

### Steps to reproduce

Although I was unable to replicate the issue in my project, it still seems to be occurring.

### What is expected?

For the children components of Space, such as input and button, it is necessary to assign classnames like "ant-input-compact-item" and "ant-input-compact-first-item".

### What is actually happening?

The child components of Space behave as if they are not inside Space, therefore they are unable to obtain the classnames. 

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2.0 |
| System | Windows 11 10.0.22621 Build 22621 |
| Browser | Chrome 115.0.5790.171 |

---
In order to resolve the issue, I could import antd components like Input and Button directly into the same file and utilize them. However, my requirement is to use them in separate files.

https://github.com/ant-design/ant-design/blob/8368458bf77f5cf8170ddf95167b07776ef79419/components/space/Compact.tsx#L27C6-L27C6

I have observed that in this particular file, whenever an error occurs, the compactItemContext variable is assigned a null value. This leads to the code generating an empty string for the classNames.

**Comment by zombieJ** [comment]
Your reproduce seems work as expect. Please update reproduce for this.

In my guess, it's related your bundled multiple version of antd which can not consume same context.

**Comment by byaman** [comment]
I have updated the reproduction link. The issue is importing components from different paths. I resolved this by changing all the links from "antd". I do not know if this is a issue.

**Comment by MadCcc** [comment]
https://codesandbox.io/s/basic-usage-antd-5-8-2-forked-l35pdz?file=/components/Space/CustomSpaceCompact.tsx
You should import components from the same dir.
