### ISSUE TITLE
How to change "Menu" background color for dark theme? 

### ISSUE THREAD

**Issue by emin-karadag** [ant-design/ant-design#44188]
### What problem does this feature solve?

Hello,
I want to use Ant Design dark theme. On the "index.js" page, I set the "theme" settings for the "ConfigProvider" and chose "theme.darkAlgorithm" as the "algorithm". I also set "colorBgHeader" for "Layout" component. But I couldn't set the background color of "Menu" component from "ConfigProvider" -> "theme" setting.
How can I do it?

### What does the proposed API look like?

```
 <ConfigProvider theme={{
    algorithm: theme.darkAlgorithm,
    components: {
      Layout: {
        colorBgHeader: "rgb(20, 20, 20)",
      }
    }
  }}>
    <App />
  </ConfigProvider>
```

![image](https://github.com/ant-design/ant-design/assets/7556164/175de3e1-4339-4834-9fcd-56a3c5ca1450)

**Comment by yoyo837** [comment]
Ref: https://github.com/ant-design/ant-design/issues/41884

**Comment by MadCcc** [comment]
Use `darkItemBg` for Menu.  Ref: https://ant.design/components/menu#design-token
