### ISSUE TITLE
ant  使用dva脚手架构建项目，引用ant组件后，在IE浏览器中报错 对象不支持startwith

### ISSUE THREAD

**Issue by guojs** [ant-design/ant-design#4418]
#### 发生问题的环境是：

- antd 版本: 
- 操作系统及其版本:
- 浏览器及其版本: ie11

#### 实际上的结果是:
 
![image](https://cloud.githubusercontent.com/assets/13706435/21560252/074d35be-ce97-11e6-9171-396c6afe3003.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3400

**Comment by afc163** [comment]
@sorrycc dva-cli 默认没有 babel-runtime 么？

**Comment by sorrycc** [comment]
有的。

**Comment by afc163** [comment]
runtime 估计没有对 node_modules 里的做处理，还是需要 polyfill.

**Comment by sorrycc** [comment]
babel 现在是不对 node_modules 下的模块做处理的。

**Comment by benjycui** [comment]
更合理的应该是 antd 自身 babel-plugin-transform-runtime 处理一下。。

**Comment by benjycui** [comment]
这个可以做到下一个 minor 版本，去除 antd 对 polyfill 的依赖。

**Comment by afc163** [comment]
自身很难处理，因为最多只能把 dist 里的文件给处理好，如果用户直接依赖 https://github.com/facebook/fbjs 的源码就不行了。

**Comment by lesskao** [comment]
在CSS Loader 中包含antd 目录就可以正常按需加载了，昨天被这个问题困扰了一天。
![qq 20170103142338](https://cloud.githubusercontent.com/assets/3353407/21601060/5bf49266-d1c0-11e6-8beb-e77e383c1ff5.jpg)
