### ISSUE TITLE
官方文档 - 设计 - 全局样式 - 图标 ：设计规格部分图文优化

### ISSUE THREAD

**Issue by xiawenqi** [ant-design/ant-design#44187]
### What problem does this feature solve?

设计规格部分图文晦涩难懂，期望优化。文档地址： [设计规格](https://ant.design/docs/spec/icon-cn#%E8%AE%BE%E8%AE%A1%E8%A7%84%E6%A0%BC)。

设计师画板为1024 x 1024， 那么后面所配的图中，1024 / 16 = 64 是什么意思呢？

还有下面出血位部分所配的图，出血位是说明画布边缘预留了64px的余地， 那么所配的图live area, 896 * 896， 896这个数字是怎么算出来的呢， 上下文也没有说明。

共两张图片意思不明确。

### What does the proposed API look like?

期望图文相符，更换图片或者补充说明数字来源。

**Comment by afc163** [comment]
1024 - 64 * 2 = 896

**Comment by afc163** [comment]
1024 / 16 = 64 代表画布分成了 16 X 16 的格式，每格宽度是 64px 。
