### ISSUE TITLE
TypeError caused by conflict between CreateCache in @ant-design/cssinjs and <Link> in next.js 13 app routing inside <Menu.Item> in antd

### ISSUE THREAD

**Issue by lunwingkit** [ant-design/ant-design#44191]
### Reproduction link

[https://github.com/lunwingkit/antd-nextjs-app-route-cache-error](https://github.com/lunwingkit/antd-nextjs-app-route-cache-error)

### Steps to reproduce

npx create-next-app antd-demo --ts --eslint --tailwind --src-dir --app --no-import-alias
npm install antd --save
npm install @ant-design/cssinjs --save
npm run build
npm start
http://localhost:3000/
press "About" button to see "Application error: a client-side exception has occurred (see the browser console for more information)."

### What is expected?

page is routed from HomePage to AboutPage

### What is actually happening?

Error "Application error: a client-side exception has occurred (see the browser console for more information)" thrown

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2.0 |
| System | Windows10 版本1909(OS組建18363.1556) |
| Browser | Chrome 版本 115.0.5790.171 (正式版本) (64 位元) |

**Comment by lunwingkit** [comment]
ok I just found tha I need to move the code in-between <Layout> from src/app/layout.tsx to a newly created file in src/app/template.tsx like below
'use client';
import { Layout, Menu } from 'antd';
import { Content, Footer, Header } from 'antd/es/layout/layout';
import Link from 'next/link';

export default function Template({ children }: { children: React.ReactNode }) {
    return (
        <Layout>
            <Header>
                <Menu>
                    <Menu.Item key="1">
                        <Link href="/">Home</Link>
                    </Menu.Item>
                    <Menu.Item key="2">
                        <Link href="/about">About</Link>
                    </Menu.Item>
                    <Menu.Item key="3">
                        <Link href="/">Home</Link>
                    </Menu.Item>
                </Menu>
            </Header>
            <Content>
                {children}
            </Content>
            <Footer></Footer>
        </Layout>
    )
}

Problem solved! Thanks

**Comment by FreeDrifter** [comment]
template.tsx 是做什么的呢 ?
