### ISSUE TITLE
DatePicker 时间范围选择 ,当我只想改变开始日期而不改变结束日期时无法操作

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#4419]
#### 发生问题的环境是：

- antd 版本:ant 2.0.1
- 操作系统及其版本:windows 7旗舰版
- 浏览器及其版本:chrome 

#### 您做了什么？请提供尽可能详细的重现步骤。

DatePicker 时间范围选择 ,当我只想改变开始日期而不改变结束日期时无法操作

单击只改变开始日期而不改变结束日期

我的操作为：

1，单击选择开始日期
2，不选择结束日期而直接在空白处点击
3，我希望开始日期变化而结束日期不变化

#### 实际上的结果是:

开始和结束日期都没有变化
备注，并且附带一个问题，换句话说这个datepicker控件的时间范围选择是否允许其中的
开始或者结束日期为空，还是要选择就必须一起选择，应该和这个是同一类的问题

#### 可重现的在线演示

官网Demo即可

https://ant.design/components/date-picker-cn/

**Comment by eddyzhang1986** [comment]
因为我看到目前这个控件，值默认的，都是先设置开始日期再设置结束日期，这样一来我想单独修改某一个就称为一个难题，能区分取来当我先点击开始日期的时候就是先设置开始，点击结束日期的时候就先设置结束日期，并且，当我设置完了开始日期后会要求我设置结束日期，这个日期的范围和开始日期做对比，反过来结束日期也这样，但我知道这样做会很复杂，请问这样实现是否合适呢

**Comment by ddcat1115** [comment]
不要用 RangePicker，用分开的两个 DatePicker 吧 

https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end
