### ISSUE TITLE
Carousel doesn't respect `useTransform` prop

### ISSUE THREAD

**Issue by Gherciu** [ant-design/ant-design#44194]
### Reproduction link

[https://ant.design/components/carousel](https://ant.design/components/carousel)

### Steps to reproduce

Long story short:
Slick carousel has a property `useTransform` which is by default true, and this property is meant to restrict the usage of `transform` CSS property when `useTransform` is false, and This is needed only in few edge cases when peoples want to have a children in their carousel which may have fixed position, but there is Bug in CSS which mess the fixed position if any parent has a transform CSS property and because of that Slick implemented this `useTransform` to give the power to developers to restrict the usage of `transform` CSS properties if needed and give control to them

It doesn't matter at the moment if we give that as True or False, This is used and Respected by Slick carousel, but not by Ant design wrapper, there are some styles using Transform CSS properties even if we declare `useTransform={false}`

### What is expected?

`useTransform` prop should be respected and when it is FALSE no transform properties in CSS should be used same as SLick carousel does

### What is actually happening?

`useTrandform` property is just passed to slick carousel, but the wrapper doesn't respect that and in its styles it uses transform CSS even if we make `useTrandform={false}`
We need to respect this property even in ant design anyway users can't use it

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18 |
| System | All |
| Browser | All |

**Comment by zombieJ** [comment]
Which part not using `useTransform` ? Could provide more detail about this?

### useTransform=true
<img width="733" alt="截屏2023-08-14 10 10 27" src="https://github.com/ant-design/ant-design/assets/5378891/764ece1b-0642-41f8-8b3f-2c968fbc16ab">

### useTransform=false
<img width="589" alt="截屏2023-08-14 10 09 59" src="https://github.com/ant-design/ant-design/assets/5378891/0042c1f9-dcfb-4708-8421-5847b2bd85c0">
