### ISSUE TITLE
Table 的 filter 能否限制单选

### ISSUE THREAD

**Issue by wizawu** [ant-design/ant-design#442]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/252

**Comment by afc163** [comment]
http://ant.design/components/table/#demo-row-selection-radio

目前在 `antd@beta` 上。

**Comment by wizawu** [comment]
噗..................
对不起，我的表述有问题。我想问的是这个

```
const columns = [{
  title: '姓名',
  dataIndex: 'name',
  filters: [{
    text: '姓李的',
    value: '李'
  }, {
    text: '姓胡的',
    value: '胡'
  }]
}, {
  title: '年龄',
  dataIndex: 'age',
  sorter: true
}, {
  title: '住址',
  dataIndex: 'address'
}];
```
现在`姓李的` `姓胡的`可以一起选，因为我的翻页是自己实现的，所以希望那里只能单选。

**Comment by afc163** [comment]
http://ant.design/components/table/#demo-head

**Comment by wizawu** [comment]
嗯，这个改动不是非常好，是非常非常好 :+1:
