### ISSUE TITLE
Descriptions doesn't fit in Modal's specified height.

### ISSUE THREAD

**Issue by RezaGhx** [ant-design/ant-design#44209]
![antd](https://github.com/ant-design/ant-design/assets/54306821/95eebdd0-f8c1-4840-b9d4-f0599d71d599)
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qfhmsf?file=/index.js)

### Steps to reproduce

ant 4.x.x:
we have a simple **Modal** which has a **Descriptions** as the one and only child in its body.
according to the **Modal** APIs document, the prop, _bodyStyle_, is the only way we can apply our custom styles on the **Modal**'s body.
we specify the number 200 for the _maxHeight_ attribute of our style. (or 100px or whatever).
but a visual bug happens.
(the snippet will be written on additional comments, too.)

### What is expected?

all the children of **Modal** located on its body should be fit on the specified height for the modal using _bodyStyle_ prop.

### What is actually happening?

the **Descriptions** ignores the modal height and keeps its height as the contents' height.
also I gave the manual height to the **Descriptions** style but it doesn't work either.
https://codesandbox.io/s/antd-reproduction-template-forked-qfhmsf?file=/index.js line 34

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 17.0.1 |
| System | Windows OS |
| Browser | Chrome |

---

      <Modal
        title="Modal Title"
        closable={false}
        open={open}
        onCancel={() => setOpen(false)}
        footer={[
          <Button key="back" onClick={() => setOpen(false)}>
            Close
          </Button>
        ]}
        bodyStyle={{ maxHeight: 200 }}
      >
        <Descriptions
          bordered
          column={1}
          // style={{ maxHeight: 600 }}
        >
          <Descriptions.Item label="first name">Name</Descriptions.Item>
          <Descriptions.Item label="last name">Family Name</Descriptions.Item>
          <Descriptions.Item label="address">
            1234 NW Bobcat Lane, St. Robert, MO 65584-5678.
          </Descriptions.Item>
          <Descriptions.Item label="year">1975</Descriptions.Item>
          <Descriptions.Item label="month">August</Descriptions.Item>
        </Descriptions>
      </Modal>

**Comment by RezaGhx** [comment]
![antd](https://github.com/ant-design/ant-design/assets/54306821/604014c6-0ad8-41c0-9079-5c186c6339f6)

**Comment by zombieJ** [comment]
Add `overflowY: auto`, Descriptions content is too lot which can not fully put in:

https://codesandbox.io/s/antd-reproduction-template-forked-jcl4sh

**Comment by RezaGhx** [comment]
@zombieJ thanks! does the Descriptions itself have a scrollY prop like Table?
