### ISSUE TITLE
用Tabs组件动态载入子组件导致子组件componentDidMount执行多次

### ISSUE THREAD

**Issue by duxianwei520** [ant-design/ant-design#4420]
#### 发生问题的环境是：

- antd 版本: 2.5.0
- 操作系统及其版本:Windows10
- 浏览器及其版本:chrome54.0

#### 可重现的在线演示
https://codepen.io/dupi/pen/bBXOee?editors=1111

**Comment by yesmeck** [comment]
`{template[this.state.activeKey]}` 这里写错了，自己检查下吧。

**Comment by yesmeck** [comment]
`activeKey` 不是这么用的，要把 `activeKey` 传给 Tabs，让 Tabs 来控制显示哪个 TabPane。

**Comment by duxianwei520** [comment]
@yesmeck 我这么写的主要原因是三个tab切换里面的组件的componentDidMount事件里面都绑定了加载数据的功能   如果换成了非动态加载的话  后面每次进入当前的active的tabpane  就不会触发获取数据的接口了  不知道你有没有理解我的意思

**Comment by yesmeck** [comment]
这样的使用问题建议到 SegmentFault 上问。

**Comment by yesmeck** [comment]
另外 TabPane 里的内容是在第一次展示的时候才会 mount 的。

**Comment by benjycui** [comment]
> 我这么写的主要原因是三个tab切换里面的组件的componentDidMount事件里面都绑定了加载数据的功能

Better way: https://github.com/ReactTraining/react-router/blob/master/docs/guides/ComponentLifecycle.md#fetching-data

**Comment by duxianwei520** [comment]
@benjycui 你发的页面404了，囧

**Comment by defghy** [comment]
https://github.com/ReactTraining/react-router/blob/v3/docs/guides/ComponentLifecycle.md#fetching-data
