### ISSUE TITLE
validateFields指定校验的时候会出现校验多了其他字段

### ISSUE THREAD

**Issue by spademan** [ant-design/ant-design#4421]
#### 发生问题的环境是：

- antd 版本: 2.5.3
- 操作系统及其版本: mac
- 浏览器及其版本: chrome  55.0.2883.95 (64-bit)

#### 您做了什么？请提供尽可能详细的重现步骤。
 如果 formItem是遍历出来的
如下
```
return this.bankAccountList.map((row, index) => {
        return (
                <div className='ant-col-12'>
                  <FormItem
                    label='账户类型'
                    labelCol={{ span: 7 }}
                    wrapperCol={{ span: 14 }}
                  >
                  {getFieldDecorator(`bankDefault.accountType-${index}`,
                    {
                      initialValue: row.accountType,
                      rules: [{
                        required: true,
                        type: 'string',
                        message: ''
                      }]
                    })(<RadioGroup disabled={row.disabled}>
                      <Radio key='0' value={'0'}>个人</Radio>
                      <Radio key='1' value={'1'}>企业</Radio>
                    </RadioGroup>)}
                  </FormItem>
                  ....
                 .....
                </div>)
      })
```
这个时候
```
let bankNameArr = [`bankDefault.accountType-${index}`,
        `bankDefault.number-${index}`,
        `bankDefault.province-${index}`,
        `bankDefault.city-${index}`,
        `bankDefault.accountName-${index}`,
        `bankDefault.bankId-${index}`]
form.validateFields(bankNameArr, function (err, values) {
   console.log(values) // 会将所有的 form表单打出来 如下图
})
```
![image](https://cloud.githubusercontent.com/assets/6311122/21561245/299bf606-cea5-11e6-9bc0-aaa1c328f45c.png)

#### 您期待的结果是:

按正常来说，我点击校验按钮只传了
![image](https://cloud.githubusercontent.com/assets/6311122/21561259/526103b0-cea5-11e6-8381-86a0fe3c75d2.png)

//
应该只会校验`_0`结尾的才对呀
但是`_1`的也出现在`callback`中

**Comment by ddcat1115** [comment]
没能重现，请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
给出重现之后再 reopen 吧，另外，map 出来的元素要指定唯一和稳定的 key。

**Comment by spademan** [comment]
在写·demo的过程中才发现，如果`getFieldDecorator`的第一个参数 是 对象的形式比如`default.names`（因为业务需要 所以第一个参数这么写 ）
在`validateFields`的`callback`中能拿到 defualt下所有需要校验的属性，但是实际上我只需要我想要的那几个 
demo如下 ，辛苦各位大大了，
http://codepen.io/spademan/pen/YNXezR?editors=0010

**Comment by benjycui** [comment]
[nested-field](http://react-component.github.io/form/examples/nested-field.html) 和 [radio-group](http://react-component.github.io/form/examples/radio-group.html) 两个特性有冲突，情况比较复杂，短时间解决不了。
