### ISSUE TITLE
Tree node title wraps under icon with visual issue

### ISSUE THREAD

**Issue by sdt-jchau** [ant-design/ant-design#44218]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tree-with-line-antd-5-8-3-forked-99tyxl)

### Steps to reproduce

1. Set tree node title to very long text that wraps to the next line
2. Set icon on tree node

### What is expected?

Tree node title wraps and lines up to the right of the icon

### What is actually happening?

Tree node title wraps and goes underneath the icon

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 16.x |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
You mean this?
![image](https://github.com/ant-design/ant-design/assets/27722486/85a17f2a-e24f-49ad-b7a0-faccd57cddea)
Baseline alignment is expected.

**Comment by Zian502** [comment]
> You mean this? ![image](https://user-images.githubusercontent.com/27722486/260607653-85a17f2a-e24f-49ad-b7a0-faccd57cddea.png) Baseline alignment is expected.

I wonder if that's what he meant
![image](https://github.com/ant-design/ant-design/assets/26033663/1cd303bd-a24b-4758-88d9-34d237a5fcc0)

**Comment by MadCcc** [comment]
It wraps because "multiple line title" was wrapped in a div element, which is displayed as block.
Make `title` inline and it will be as you expected.

**Comment by sdt-jchau** [comment]
My apologies.  The codesandbox didn't save.  I updated it.  Here's a screenshot of the issue
![image](https://github.com/ant-design/ant-design/assets/87726648/3cf32a98-9d32-4216-882a-5ab29da167bb)
