### ISSUE TITLE
modal 组件在使用 info、success、warning 等方法唤起时确认按钮样式存在问题

### ISSUE THREAD

**Issue by GalliumWang** [ant-design/ant-design#44210]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/modal-cn/](https://4x-ant-design.antgroup.com/components/modal-cn/)

### Steps to reproduce

点击信息提示示例中任何一个按钮

### What is expected?

确认按钮应该为非hover状态

### What is actually happening?

确认按钮默认显示hover状态

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 16 |
| System | macos 13 |
| Browser | chrome 115.0.5790.114 |

**Comment by kiner-tang** [comment]
这个不是 hover 的样式，是 focus 的样式，打开弹框默认让确认按钮聚焦

**Comment by GalliumWang** [comment]
> 

打开弹窗默认聚焦这一点在交互上太奇怪了

**Comment by afc163** [comment]
> 打开弹窗默认聚焦这一点在交互上太奇怪了

不奇怪，主流 UI 都是这么做的。

**Comment by crazyair** [comment]
如果合`window.confirm()` 对比，还有有点区别的
