### ISSUE TITLE
Radio Group not work in Tree

### ISSUE THREAD

**Issue by ooPG233** [ant-design/ant-design#44224]
### Reproduction link

[https://9l29gc.csb.app/](https://9l29gc.csb.app/)

### Steps to reproduce

Click an unchecked radio 

### What is expected?

It was work in v5.8.1 
https://5jhldf.csb.app/

### What is actually happening?

Once clicked the radio you can find that nothing happened and even the click event are not trigged.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
There is indeed an issue with the selection.
