### ISSUE TITLE
Carousel 包含的子组件componentWillMount 两次

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#4422]
#### 发生问题的环境是：

- antd 版本: 2.5.2
- 操作系统及其版本:win10
- 浏览器及其版本:chrome55

#### 您做了什么？请提供尽可能详细的重现步骤。

```import 'antd/dist/antd.css';
import React from 'react';
import ReactDOM from 'react-dom';
import {Carousel} from 'antd';

const mountNode = document.getElementById('content');

class App extends React.Component {
  constructor() {
    super()
  }

  render() {  
    return (
      <div>
        <Carousel >
          <div style={{ height: 500 }}>
              first
          </div>
          <div>
            sec
            <MyHtml />
          </div>
        </Carousel>
      </div>
    )
  }
}

class MyHtml extends React.Component {
    constructor() {
        super();
    }
    componentWillMount() {
        console.log('MyHtml componentWillMount')
    }
    render() {        
        return (
            <div>
                测试
            </div>
        )
    }
}
ReactDOM.render(<App />, mountNode);
```
#### 您期待的结果是:
MyHtml 组件componentWillMount只执行一次

#### 实际上的结果是:
**MyHtml 组件componentWillMount执行二次componentWillMount**
![image](https://cloud.githubusercontent.com/assets/19165238/21561543/acbf4436-cea8-11e6-9101-52f22aa27a2a.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by whx76** [comment]
在线演示 http://codepen.io/anon/pen/dNPWQP?editors=0012

**Comment by afc163** [comment]
It is a https://github.com/akiran/react-slick bug, Maybe we should fork it and maintain a indepent package?

**Comment by benjycui** [comment]
I am not sure if we can replace `react-slick` with `nuka-carousel`, just as [`antd-mobile`](https://github.com/ant-design/ant-design-mobile/blob/3b1b81b120cadacc9224d957a8f2d7b61558b08d/package.json#L37) in next major version.

Carousel is complicated.. I don't think that we have time to maintain such a complicated component.

**Comment by afc163** [comment]
It is not a bug actually.

```jsx
<Carousel >
  <div />
  <div />
  <MyHtml />  // componentWillMount twice
</Carousel>
```

```jsx
<Carousel >
  <div />
  <MyHtml />  // componentWillMount once
  <div />
</Carousel>
```

---

react-slick have to create two slides for last item, to switch circularly. If this is bugging you, you can set `infinite` to `false`.
