### ISSUE TITLE
[App component]: Should support configure to disable hashId

### ISSUE THREAD

**Issue by camcam2605** [ant-design/ant-design#44225]
### What problem does this feature solve?

Avoid overriding and conflict with other styles if users develop their own components.

Before:
`<div class="css-dev-only-do-not-override-b5kdff ant-app">...</div>`

After:
`<div class="ant-app">...</div>`

### What does the proposed API look like?

`<App hashPriority={false} />`  `// remove hashId classname`

**Comment by zombieJ** [comment]
ConfigProvider has the ability: `theme.hashed`

**Comment by ko2in** [comment]
For me, I've to use `ProConfigProvider` to disable hash ID. Not working with `theme.hashed` in `ConfigProvider`.

### Doesn't work
```
<ConfigProvider theme={{ hashed: false }}>
</ConfigProvider>
```

### Work
```
<ProConfigProvider hashed={false}>
</ProConfigProvider>
```
