### ISSUE TITLE
DataPicker 组件的 table 未居中

### ISSUE THREAD

**Issue by Yilun-Sun** [ant-design/ant-design#44235]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rr2g68)

### Steps to reproduce

检查选择器的日期 table

### What is expected?

日期 table 居中

### What is actually happening?

日期 table 宽度比预期宽。
多余量 = `列数 * 2px`
<img width="342" alt="image" src="https://github.com/ant-design/ant-design/assets/43896664/38af7887-31d6-4586-9cb6-2f9a63088c3c">

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2.0 |
| System | macOS Ventura 13.4.1 (c) |
| Browser | Chrome Version 114.0.5735.198 (Official Build) (arm64) |

---
原因是日期的 th 包含 `padding: 1px`，且对浏览器的默认样式未进行 reset 的情况下，th 的 `box-sizing` 会是 `content-box`，导致计算出的 th 的宽度并不包含两侧的 padding。日期 table 的宽度便会多出 `列数 * 2px`。

**Comment by Yilun-Sun** [comment]
如果在样式文件中引入 `@import "antd/dist/reset.css";` 会解决这个问题。但是如果直接使用日期组件，在任何地方都会出现这个问题。官网内部的样式是正常的是因为官网把 padding 全都重置成了 0，这样即使没有 reset 样式，也不会有 th 宽度问题出现。
<img width="405" alt="image" src="https://github.com/ant-design/ant-design/assets/43896664/0ad36674-3bfd-49fa-960c-fd0e0011a513">

**Comment by Zian502** [comment]
> 如果在样式文件中引入 `@import "antd/dist/reset.css";` 会解决这个问题。但是如果直接使用日期组件，在任何地方都会出现这个问题。官网内部的样式是正常的是因为官网把 padding 全都重置成了 0，这样即使没有 reset 样式，也不会有 th 宽度问题出现。 <img alt="image" width="405" src="https://user-images.githubusercontent.com/43896664/260650322-0ad36674-3bfd-49fa-960c-fd0e0011a513.png">

这个去掉其实也可以，但是不知道会不会影响到其它场景
![image](https://github.com/ant-design/ant-design/assets/26033663/24c9c579-cdb0-4361-b6d1-0a5ecfb19ac3)

**Comment by Yuiai01** [comment]
可以这么设置：
<img width="325" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/3ebd669d-80f6-4bbb-b571-a838e06dbf81">
<img width="390" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/e498b66f-f2fe-48c0-85ab-8a494091a234">

**Comment by Zian502** [comment]
提了个PR，https://github.com/ant-design/ant-design/pull/44245
