### ISSUE TITLE
ConfigProvider componentSize配置对于List组件无效

### ISSUE THREAD

**Issue by 65min** [ant-design/ant-design#44248]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/configprovider-componentsize-donot-fit-list-kv59jr?file=/index.js)

### Steps to reproduce

ConfigProvider 配置componentSize属性，对于大部分组件，如Button、Card组件都是有效果的，但是对于List组件却无效。
如重现链接里的例子，页面中的radio可以切换componentSize，切换componentSize后，Button、Card组件的size都会发生变化，但是List组件的size却并未发生变化。
本地antd 5.8.2有这个问题，重现链接里的antd 是5.3.2也是一样的效果。
请确认这是否是一个bug。

### What is expected?

期望List组件能够适配ConfigProvider.componentSize属性

### What is actually happening?

List组件并未支持ConfigProvider.componentSize属性

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Windows11 |
| Browser | Chrome 90 |

**Comment by Yuiai01** [comment]
我来康康这个
