### ISSUE TITLE
Dropdown组件在第一次加载时出现左移BUG

### ISSUE THREAD

**Issue by TstName** [ant-design/ant-design#44249]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-mopsa-8r2kd3?file=/src/App.js)

### Steps to reproduce

第一次点击 “toptoptoptoptoptoptoptop”按钮

### What is expected?

无左移效果

### What is actually happening?

出现左移效果

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | react |
| System | win10 |
| Browser | 115.0.57920.171 |

**Comment by MadCcc** [comment]
Dropdown 宽度跟随 trigger 变宽时在 placement 为 `center` 或者 `right` 时有问题

**Comment by TstName** [comment]
> 问题
为top时也会存在这个问题，有没有办法在开发过程中解决这个问题尼？
在5.5版本之前是不存在这个问题的

**Comment by bbb169** [comment]
这个应该是trigger的问题，只要周边有东西并且设置了strech属性就会有这个问题

**Comment by bbb169** [comment]
pr已提 rc-trigger @MadCcc 
 https://github.com/react-component/trigger/pull/420
