### ISSUE TITLE
Dropdown menu item not all area trigger the click event

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44254]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7fd5kj)

### Steps to reproduce

create a dropdown with few items, set on click on the dropdown item to open a modal. 

### What is expected?

Clicking on all area of the item should trigger the click event

### What is actually happening?

only area that are close to the dropdown item label triggers the click

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
https://github.com/ant-design/ant-design/assets/52765572/f72798ee-8fdc-44bb-83ba-974819c08263

**Comment by linxianxi** [comment]
This codesandbox seems to have no problem

**Comment by AsuraKev** [comment]
![image](https://github.com/ant-design/ant-design/assets/52765572/118285c2-8337-4abe-8b66-49b6dc260d88)

only the background color area triggers the click event

**Comment by AsuraKev** [comment]
heres update codesandbox https://codesandbox.io/s/trigger-mode-antd-5-8-3-forked-9jkspm?file=/demo.tsx


https://github.com/ant-design/ant-design/assets/52765572/e339f386-168f-46a8-befb-6f682db0e42a

**Comment by MadCcc** [comment]
https://codesandbox.io/s/trigger-mode-antd-5-8-3-forked-3vkkss?file=/demo.tsx
Try this

**Comment by AsuraKev** [comment]
beautiful. thanks
