### ISSUE TITLE
ColorPicker 控件的清空状态， 在 size 为 large, small 时，显示变形

### ISSUE THREAD

**Issue by MadCcc** [ant-design/ant-design#44258]
### Discussed in https://github.com/ant-design/ant-design/discussions/44256

<div type='discussions-op-text'>

<sup>Originally posted by **ekuku1984** August 17, 2023</sup>
https://codesandbox.io/s/colorpicker-test-xfj4nh?file=/src/index.js

在不同的 size 状态下， 清空状态的图显示大小没有变化， 导致在 small 时，显示变形， large 下， 虽然没有变形， 单是间距变大

![image](https://github.com/ant-design/ant-design/assets/6016942/a90ae9f1-734f-4d1e-bcec-17563278b370)

</div>

**Comment by RedJue** [comment]
Mark

**Comment by RedJue** [comment]
Mark
