### ISSUE TITLE
(antd Tree component) Cannot fully display last tree node when virtual list is activated and font-size is changed

### ISSUE THREAD

**Issue by shanpig** [ant-design/ant-design#44252]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cannot-display-full-tree-when-active-virtual-list-and-different-font-size-33ghdv?file=/demo.tsx)

### Steps to reproduce

The link is a codesandbox modified by the demo sandbox from [antd tree #virtual-scroll](https://4x.ant.design/components/tree/#components-tree-demo-virtual-scroll), with additional settings neccessary to reproduce the bug. You can see that when scrolled to the bottom, the last node is not fully displayed, but was covered by the outer container.

The offset is in proportion to the `TreeProps.height` value. It is neglectable when the height is small, but then starts to get significant around 4000 and up. You can modify `TREE_HEIGHT` and see the effect.

If you remove the `font-size` setting, the bug goes away.

### What is expected?

Event if a `font-size` is set, the tree component should display all the tree nodes.

### What is actually happening?

Don't quite know the reason, but I think it might be related to the rendering method behind the rc-tree.

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 18 |
| System | macOS Ventura 13.5 (not relevant) |
| Browser | Chrome (not relavant) |

**Comment by Zian502** [comment]
It seems that the height props and font size of the Tree component conflict. Removing the height props for the Tree component is normal.
![image](https://github.com/ant-design/ant-design/assets/26033663/a800d858-9150-4907-bf31-2af263f24ee7)

**Comment by shanpig** [comment]
@Zian502 thanks for your reply 😺 
Removing the height props surely would be normal. However, in some cases when the tree is large (i.e. more than 200 tree nodes), the tree significantly lags due to huge amount of elements rendered, and that's where the height props comes in handy. With height props added, and the virtual list feature is activated, the element rendered in the browser is lower.

**Comment by Zian502** [comment]
> @Zian502 thanks for your reply 😺 Removing the height props surely would be normal. However, in some cases when the tree is large (i.e. more than 200 tree nodes), the tree significantly lags due to huge amount of elements rendered, and that's where the height props comes in handy. With height props added, and the virtual list feature is activated, the element rendered in the browser is lower.
> 
> P.S. We actually managed to fix that problem by adding font size through outer container:
> 
> ```js
> const StyledWrapper = styled.div`
>  .ant-tree-title {
>     font-size: 16px;
>   }
> `
> 
> const App = ()=>(
>   <StyledWrapper>
>     <Tree
>        {/* ... */}
>     </Tree>
>   </StyledWrapper>
> )
> ```
> 
> Despite the workaround works like a charm, it would be of utmost help if the height props goes smoothly with other styling properties.

Now look at the Demo seems to be normal, is it changed something

**Comment by shanpig** [comment]
> > @Zian502 thanks for your reply 😺 Removing the height props surely would be normal. However, in some cases when the tree is large (i.e. more than 200 tree nodes), the tree significantly lags due to huge amount of elements rendered, and that's where the height props comes in handy. With height props added, and the virtual list feature is activated, the element rendered in the browser is lower.
> > P.S. We actually managed to fix that problem by adding font size through outer container:
> > ```js
> > const StyledWrapper = styled.div`
> >  .ant-tree-title {
> >     font-size: 16px;
> >   }
> > `
> > 
> > const App = ()=>(
> >   <StyledWrapper>
> >     <Tree
> >        {/* ... */}
> >     </Tree>
> >   </StyledWrapper>
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Despite the workaround works like a charm, it would be of utmost help if the height props goes smoothly with other styling properties.
> 
> Now look at the Demo seems to be normal, is it changed something

The offset bug is in proportion to the HEIGHT variable in the sandbox example. If you change it to about 4000 it will be more obvious.

**Comment by zombieJ** [comment]
Seems not an issue for the latest `rc-virtual-list`: https://codesandbox.io/s/cannot-display-full-tree-when-active-virtual-list-and-different-font-size-forked-gztc67?file=/demo.tsx
