### ISSUE TITLE
Notification is rendered twice

### ISSUE THREAD

**Issue by bnlambert** [ant-design/ant-design#4425]
Hi 
I am using Ant notification. I noticed that each time I call the notification, two notification boxes will appear, one immediate after the other and will disappear after their time out. My code looks like this

`import React from 'react'
import { notification } from 'antd';

 const Feedback = (type) => {

  notification[type]({
    message: 'Notification Title',
    description: 'This is the content of the notification. This is the content of the notification. This is the content of the notification.',
  });

};

export default Feedback`

An I use it in my component like this

`{this.props.patient.feedback && Feedback('success')}`

I am suspecting that notification box is displayed each time react updates the component and re-renders. Please how can I insist on rendering notification just once?
Thanks

#### 发生问题的环境是：

- antd 版本:
- 操作系统及其版本:
- 浏览器及其版本:

**Comment by RaoHai** [comment]
if you want to currying notification, you can do like this:

```es6
 export default function(type) {
    return notification[type]({
      message: 'Notification Title',
      description: 'This is the content of the notification.',
    });
}
```

**Comment by bnlambert** [comment]
RaoHai thank you very much for the prompt response. This issue had nothing to do with Ant notification. What happened was that a state update to place while display notification was still true. So have intercepted the state update process and now it works as expected.

Thanks
