### ISSUE TITLE
[AntD Theme Editor] -  editing boxShadow map token crashes the page

### ISSUE THREAD

**Issue by ShubhamSj07** [ant-design/ant-design#44253]
### Reproduction link

I've prepared a screen recording reproducing the bug in theme editor page
[https://drive.google.com/file/d/1N68DZEL2pbOzJcciz42UO-eFZkT88rwd/view](https://drive.google.com/file/d/1N68DZEL2pbOzJcciz42UO-eFZkT88rwd/view)

### Editing boxShadow on Theme Editor crashes page

- head over to -> https://ant.design/theme-editor
- scroll down to edit shadow properties for our theme
- open Map Token dropdown, and edit the properties.
- start typing in input fieid, the page crashes (white page is seen)
- I have reproduced this issue and provided you with gdrive screen recording of same

### What is expected?

User should be able to edit the boxShadow properties and customise it as per need. 

### What is actually happening?

As soon as user starts typing in input field to edit boxShadow, it directly crashes the theme editor. [object Object] appears in input field and it breaks out.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | Windows 11 |
| Browser | Chrome 115 |

**Comment by Yuiai01** [comment]
I'll try to fix this issue.
