### ISSUE TITLE
【Table】自定义components的body时，固定多列，表头未正确计算left偏移量导致列表横向滚动时有问题

### ISSUE THREAD

**Issue by conan2lv** [ant-design/ant-design#44259]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xu-ni-lie-biao-antd-5-8-2-forked-9vcnz2)

### Steps to reproduce

自定义设置Table的compoents.body时，同时设置columns中超过一列以上的属性fixed: 'left'，表格横向滚动过程中，表头列固定有问题

### What is expected?

自定义components.body时表格header能跟正常情况下Table一样正确计算left的偏移量

### What is actually happening?

自定义components.body时表格header的left计算有误，都为0，导致无法正常固定多列

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.0.0 |
| System | macOS Ventura 13.2.1 |
| Browser | chrome 115.0.5790.114 |

**Comment by MadCcc** [comment]
Wait for https://github.com/ant-design/ant-design/pull/44349
