### ISSUE TITLE
In DatePicker, the conflict about defaultValue and disabledTime

### ISSUE THREAD

**Issue by paige12345** [ant-design/ant-design#44262]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/disabled-date-time-antd-5-8-3-forked-r5pgdq?file=/demo.tsx)

### Steps to reproduce

const disabledDate: RangePickerProps["disabledDate"] = (current) => {
  return current && current < dayjs().endOf("day");
};

const disabledDateTime = (current) => {
  return {
    disabledHours: () => range(0, 24).splice(4, 20),
    disabledMinutes: () => range(30, 60),
    disabledSeconds: () => [55, 56]
  };
};

<DatePicker
      format="YYYY-MM-DD HH:mm:ss"
      disabledDate={disabledDate}
      disabledTime={disabledDateTime}
      showTime={{ defaultValue: dayjs("05:40:55", "HH:mm:ss") }}
 />

1. Set the defaultValue of TimePicker to '05:40:55', which is disabled in disabledTime.
2. Open DatePicker, select a date value. Now the time value is set to 05:40:55 by default. 
3. Click OK button of the DatePicker popup panel, the invalid time value is set. 

### What is expected?

If the defaultValue of TimePicker is in the disabledTime range, it's not allowed to save the value.

### What is actually happening?

The invalid defaultValue is set.
<img width="523" alt="image" src="https://github.com/ant-design/ant-design/assets/93237887/984ae1f0-04a7-436e-9657-cf8aa6e79cf8">

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.0.0 |
| System | Mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Trace https://github.com/ant-design/ant-design/issues/44289
