### ISSUE TITLE
ERROR in ./node_modules/rc-virtual-list/es/List.js 23:0-35

### ISSUE THREAD

**Issue by simplesilence** [ant-design/ant-design#44271]
### Reproduction link

[http://localhost:3000](http://localhost:3000)

### Steps to reproduce

无法编译成功

### What is expected?

期望编译成功

### What is actually happening?

Compiled with problems:X

ERROR in ./node_modules/rc-virtual-list/es/List.js 23:0-35

Module not found: Error: Can't resolve 'rc-util' in '/Users/shaun/Downloads/work/hp/hp_github_source/myprs-frontend-admin/node_modules/rc-virtual-list/es'

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2 |
| System | Linux/MacOS |
| Browser | Chrome |

---

**Comment by simplesilence** [comment]
![image](https://github.com/ant-design/ant-design/assets/15317575/6b02cf3a-7969-4e4e-ae6c-235c93ef7e18)

**Comment by MadCcc** [comment]
重装一下依赖试试？

**Comment by afc163** [comment]
https://github.com/react-component/virtual-list/pull/211/files#r1297070261

**Comment by simplesilence** [comment]
rc-util用的是antd 5.8.3版本默认的
