### ISSUE TITLE
InputNumber 增加 cutOnly prop

### ISSUE THREAD

**Issue by topaz-h** [ant-design/ant-design#44279]
### What problem does this feature solve?

当设置了precision属性，超过的小数位会四舍五入，在某些场景我们希望直接截断（例如💰方面）

### What does the proposed API look like?

`cutOnly?:boolean` 决定是否截断

**Comment by afc163** [comment]
可以直接用 formatter 实现。

**Comment by topazur** [comment]
https://github.com/react-component/input-number/pull/590

使用 formatter 属性应该只是改变显示的值吧，不能限制实际值，可以看下这个pr吗

**Comment by topazur** [comment]
![Kapture 2023-08-21 at 14 15 39](https://github.com/ant-design/ant-design/assets/88650465/e16c19f2-6962-4464-80a8-ce84bb5995b2)
但是期待的是 1000.23，而不是 1000.24

**Comment by afc163** [comment]
onChange 里也处理一下就行了：https://codesandbox.io/s/ji-ben-antd-5-8-4-forked-5jpsxn?file=/demo.tsx

**Comment by topazur** [comment]
谢谢，明白了！自己写截断逻辑即可
