### ISSUE TITLE
Table 表格，自定义Row组件，使用onRow 方法向Row组件传递非 React.HTMLAttirbutes 的属性，ts会报错。

### ISSUE THREAD

**Issue by PengQingYao** [ant-design/ant-design#44270]
### What problem does this feature solve?

优化使用。

### What does the proposed API look like?

按照官网的例子，实现可拖拽Table表格， 但是我希望某一行row 不允许拖动， 需要向Row组件传递一个额外参数来标识当前行 不允许拖动，但是onRow要求返回React.HTMLAttirbutes，ts有报错。

**Comment by zombieJ** [comment]
用 `data-xxx` 前缀。属性是直接透传给 tr 的，报错是符合预期的哈~

**Comment by PengQingYao** [comment]
> 用 `data-xxx` 前缀。属性是直接透传给 tr 的，报错是符合预期的哈~

能说详细点吗？ 'data-xxxx' 在哪里传递？

**Comment by PengQingYao** [comment]
https://github.com/react-component/table/blob/6f538dcc5511cacc89a494003b5b186581ccb87f/src/Body/BodyRow.tsx#L133C8-L133C8
<RowComponent> 传递的参数都已经固定了， 除了data-row-key 之外， 没办法额外额外传递参数了呀。
