### ISSUE TITLE
datepicker设置showtime和多格式匹配时，手工输入时间会报错

### ISSUE THREAD

**Issue by wcmboy** [ant-design/ant-design#44275]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ri-qi-ge-shi-antd-5-8-3-forked-7m5gl9?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

手工输入时间，如2023-02-28 00:00

### What is expected?

正常接受定义的多格式输入

### What is actually happening?

报错：TypeError
(formatStr || "").replace is not a function

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 5.8.3 |
| System | mac |
| Browser | edge |

**Comment by ZWkang** [comment]
showTime 为 True 且设置 format 为 Array 有点冲突
报错点: https://github.com/react-component/picker/blob/master/src/generate/dayjs.ts#L23
从这里生成了 showTime Props https://github.com/ant-design/ant-design/blob/master/components/date-picker/util.ts#L116
透传到 rc-picker 里的时候就报错了，因为透传入 format 为数组。

不知道咋改，因为我不知道这种情况的预期是什么。 @afc163

**Comment by Zian502** [comment]
![image](https://github.com/ant-design/ant-design/assets/26033663/4503f6c9-6259-4d3f-9a06-d04747d73c5d)
![image](https://github.com/ant-design/ant-design/assets/26033663/30bea756-f3b6-4037-9e1b-5243b3891323)
组件 props 上的 showTime 为 object 类型时，其 format 会替换掉组件 props 上的 format，所以，
![image](https://github.com/ant-design/ant-design/assets/26033663/cd9eb278-5212-412b-a474-7f41f02d4d30)
预期这里的 showTime 的 format 类型应该为 string 类型。但是组件 props 上的 showTime为 boolean 类型时，showTime 的 format 类型变成了数组类型，需要做下兼容。
https://github.com/ant-design/ant-design/compare/master...Zian502:fix/date-picker?expand=1
