### ISSUE TITLE
Disable feature on Radio group works opposite between versions 4.x and 5.x

### ISSUE THREAD

**Issue by chiwiu** [ant-design/ant-design#44276]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xtpfyr?file=/index.js)

### Steps to reproduce

Just create a radio group that has "disable" defined with one condition (disabled={bool1}), and child button that is disabled with a different condition (disabled={bool2}).
I'd expect the child's disabled state to be effectively disabled={bool1 || bool2}

### What is expected?

To behave exactly like version 4.x, where if the Radio group is set disable, it will disable the whole component no matter if the child items are disabled or not.

Link here of version 4 working as expected:
https://codesandbox.io/s/antd-reproduction-template-version-4-gvjmsv

### What is actually happening?

If each child button has its own "disable" defined, the group's "disable" is ignored

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18 |
| System | All |
| Browser | Tested in firefox and chrome |

**Comment by chiwiu** [comment]
Link to the previous issue that was reopened in here https://github.com/ant-design/ant-design/issues/43147

**Comment by Yuiai01** [comment]
In the previous code, when the disabled of the radio itself is undefined or false, it will apply the disabled from the group. Therefore, when the group's disabled is true, the disabled of its internal radio will always be true, which leads to the internal radio not correctly applying its own disabled. This is incorrect.
https://github.com/ant-design/ant-design/pull/40741/files#diff-4befd0a047da31184c43bc6fef846467a6e774ecef3cf332ac25310b3d9d4a8cL58

**Comment by MadCcc** [comment]
It is intended in v5.

**Comment by chiwiu** [comment]
If it works opposite now on purpose, at least I think it should be mentioned in 
[https://ant.design/docs/react/migration-v5](https://ant.design/docs/react/migration-v5)
