### ISSUE TITLE
DatePicker 中disabledTime 禁用问题

### ISSUE THREAD

**Issue by qyjandroid** [ant-design/ant-design#44289]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bu-ke-xuan-ze-ri-qi-he-shi-jian-antd-5-8-3-forked-vz826t)

### Steps to reproduce

修改官方的不可选择日期和时间demo,把disabledDateTime中 disabledHours: () => range(0, 24).splice(4, 24), 改为：disabledHours: () => range(0, 24).splice(0, 4)，

### What is expected?

期望禁用0-4小时

### What is actually happening?

界面选择确实是禁用了，但是如果点击日期后，就会默认选中00:00:00，确认按钮也就会点亮，应当于没有禁用。

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18 |
| System | windows |
| Browser | chrome 115.0.5790.171 |

---
我希望选中日期以后，时间选择默认为没有禁用的第一个时刻。

**Comment by qyjandroid** [comment]
![image](https://github.com/ant-design/ant-design/assets/6645414/7ac3029b-b43f-4a24-930a-29ba1615270a)
效果如下：点击步骤1，日期选中，然后确认按钮就可以点击了，这个时候默认就会把禁用时间段的时间也包含进去。

**Comment by SnowingFox** [comment]
I'will try to fix this

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/44262

**Comment by yoyo837** [comment]
https://github.com/react-component/picker/pull/666#issuecomment-1738324386
