### ISSUE TITLE
Bundle size with <Localeprovider />

### ISSUE THREAD

**Issue by eric-basley** [ant-design/ant-design#4428]
When using `<LocalProvider/>` like below `bundle.js` increased of more than 200kB because moment.js and all their locales are included !!!

How to avoid this ?

```
import enUS from 'antd/lib/locale-provider/en_US';
import { LocaleProvider } from 'antd';

const root = (
  <LocaleProvider locale={enUS}>
      <App />
  </LocaleProvider>
);

render(root, mountNode);

```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3947#issuecomment-269601038
