### ISSUE TITLE
Bug Tabs and Tables when scroll attribute is set

### ISSUE THREAD

**Issue by NicolasSponton** [ant-design/ant-design#44281]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-tabs-table-bug-4tk5lv?file=/index.js)

### Steps to reproduce

Change between Tab 1 and Tab 2

### What is expected?

Smooth transition

### What is actually happening?

Table content is empty for a fraction of a second on tab transition, not showing the Empty component, resulting in an ugly transition effect.

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | Google Chrome 115.0.5790.171 |

---
The proper transition behavior can be seen when scroll attribute is not set in table components.

**Comment by bbb169** [comment]
This problem is not a problem with rc-table, it's a problem with ant design table, it has nothing to do with the tabs, as long as it triggers the rendering it will have this problem, let me fix it

**Comment by ZWkang** [comment]
It seems to have been resolved, and it no longer exists in the latest version.
Before [Before](https://codesandbox.io/s/react-tabs-table-bug-forked-mdyj6p)
Now [Now](https://codesandbox.io/s/react-tabs-table-bug-forked-sc6g5d?file=/index.js)

@MadCcc
