### ISSUE TITLE
Table pagination page size selector dropdown went flying when the switching between page with different number of rows

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44285]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/selection-and-operation-antd-5-8-3-forked-8l8snl?file=/demo.tsx)

### Steps to reproduce

Create a table with say 230 rows and set the page size to 50. This will create 5 pages with the first 4 pages of 50 items and the last page of 30. Go to any page with 50 items and click on the page size selector and then go to the last page and click the selector again, you will see the dropdown went flying

### What is expected?

dropdown should not flick

### What is actually happening?

dropdown is flicking when you have multiple pages with different number of rows

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
https://github.com/ant-design/ant-design/assets/52765572/e4dcdeb5-bbcf-406f-ae3c-03616db0b8ab

**Comment by Zian502** [comment]
![image](https://github.com/ant-design/ant-design/assets/26033663/68edee95-d4c9-4869-924c-d974c9d92792)

The bottom margin of inset suddenly changed to 92 px, and I need to see how the code caused this

**Comment by zombieJ** [comment]
reinstall `node_modules`:

https://codesandbox.io/s/selection-and-operation-antd-5-8-3-forked-272jp6?file=/demo.tsx
