### ISSUE TITLE
Combination of Simple mode pagination along with page size changer

### ISSUE THREAD

**Issue by Gudivaka** [ant-design/ant-design#44290]
### What problem does this feature solve?

If user wanted to have simple mode along with Page size changer currently this combination is not supported. 
Currently simple mode can be combined with Total items but not with page size changer 

### What does the proposed API look like?

For Navigation of pages user should be able to use either simple mode or normal pagination mode along with page size changer
showSizeChanger prop is not working along with simple prop
Link for Reference: https://codesandbox.io/s/pagination-antd-5-8-3-forked-pcjxxk

**Comment by Zian502** [comment]
mark

**Comment by Zian502** [comment]
https://github.com/react-component/pagination/pull/530
