### ISSUE TITLE
Modal：是否考虑让 footer 支持传入 render 函数，或者支持 extraFooter 

### ISSUE THREAD

**Issue by tmyeahsing** [ant-design/ant-design#44297]
### What problem does this feature solve?

有挺多的时候可能只是想在 确认/取消 按钮之外多加一个额外的操作按钮，但是按目前的配置，必须得把整个 footer 重写，并且重写的过程也要自己实现一遍 确认/取消 按钮，包括自带的 确认/取消 按钮会触发的一些事件（比如 onOk/onCancel）等也要自己手动触发，有点麻烦。
如果支持 extraFooter 甚至让 footer 支持传入 render 函数（render 函数参数包括自带的 确认/取消 按钮），是不是可以更灵活和方便。

### What does the proposed API look like?

支持 extraFooter 属性或者让 footer 属性支持传入 render 函数（render 函数参数包括自带的 确认/取消 按钮）

**Comment by MadCcc** [comment]
foot={(originNode, { ConfirmBtn, CancelBtn }) => {}}

**Comment by RedJue** [comment]
> `footer={(originNode, { ConfirmBtn, CancelBtn }) => {}}`

Breaking change？

**Comment by afc163** [comment]
已经有了 ConfirmBtn, CancelBtn 还需要 originNode 么？

**Comment by MadCcc** [comment]
> > `footer={(originNode, { ConfirmBtn, CancelBtn }) => {}}`
> 
> Breaking change？

不 break，同时支持 ReactNode 和 Function

**Comment by MadCcc** [comment]
> 已经有了 ConfirmBtn, CancelBtn 还需要 originNode 么？

render props 的基本定义 `(originNode: ReactNode, info: {}) => ReactNode`，保持和以前的 api 一样的结构

**Comment by afc163** [comment]
ConfirmBtn => confirmButton
ConfirmBtn => cancelButton

大写一般是组件。

**Comment by MadCcc** [comment]
> ConfirmBtn => confirmButton ConfirmBtn => cancelButton
> 
> 大写一般是组件。

就是提供组件出来的，和 ColorPicker 一样 https://ant.design/components/color-picker-cn#components-color-picker-demo-panel-render

**Comment by RedJue** [comment]
我来弄一下吧

**Comment by tmyeahsing** [comment]
> 

个人觉得这里没必要再支持props，因为在Modal上已经支持了okButtonProps，这里再做的话，造成props的传入方式不收敛了，实现和使用起来都有点多余。感觉这里就是纯粹地提供一个Node就好了

**Comment by tmyeahsing** [comment]
个人觉得这里没必要再支持props，因为在Modal上已经支持了okButtonProps，这里再做的话，造成props的传入方式不收敛了，实现和使用起来都有点多余。感觉这里就是纯粹地提供一个Node就好了

**Comment by MadCcc** [comment]
@tmyeahsing 4.x 原则上不新增 feature 了

**Comment by tmyeahsing** [comment]
@MadCcc get
