### ISSUE TITLE
Ability to define horizontal offset of Tour component

### ISSUE THREAD

**Issue by alex-golubtsov** [ant-design/ant-design#44305]
### What problem does this feature solve?

As of version 5.8.4 it's not possible to define horizontal offset for a `<Tour>` component.

Good example of what I mean is `<Tooltip align={{ offset: [2, -9] }}>`

### What does the proposed API look like?

Instead of current `<Tour gap={{ offset: number }}>`, I'd imagine `<Tour gap={{ offset: [number, number] }}>`

**Comment by RedJue** [comment]
mark
