### ISSUE TITLE
ConfigProvider 定制 radio组件的 theme 不生效

### ISSUE THREAD

**Issue by cloud0072** [ant-design/ant-design#44308]
### Reproduction link

[https://github.com/cloud0072/antdesiginreact-bugreport/blob/master/src/App.tsx](https://github.com/cloud0072/antdesiginreact-bugreport/blob/master/src/App.tsx)

### Steps to reproduce

Radio.Group 加入 buttonStyle={'solid'} 属性
修改 configprovider radio 的主题

### What is expected?

修改configprovider 可以生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | windows10 |
| Browser | chrome |

---
不完全测试，可能有影响的css有更多

**Comment by MadCcc** [comment]
`buttonCheckedBg` 对 `solid` 无效。可以使用 `colorPrimary` 修改

**Comment by cloud0072** [comment]
@MadCcc 也许可以修改一下文档，或者修改一下属性的名字，更容易明白一些，谢谢

**Comment by MadCcc** [comment]
加一个 `solidButtonCheckedBg` 吧
