### ISSUE TITLE
The color of links is not applied

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#44301]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-vlypmf?file=/index.js)

### Steps to reproduce

```jsx
const globalTheme = {
  token: {
    colorLink: "red"
  }
};

const localTheme = {
  token: {
    colorLink: "green"
  }
};

const App = () => {
  return (
    <ConfigProvider theme={globalTheme}>
        <a href="/">This link is blue?</a>

        <Space>
          <a href="/">Wow, red!</a>
        </Space>

        <ConfigProvider theme={localTheme}>
          <a href="/">This link is blue?</a>

          <Space>
            <a href="/">Wow, green!</a>
          </Space>

        </ConfigProvider>
    </ConfigProvider>
  );
};
```

### What is expected?

The color should be applied to all elements.

### What is actually happening?

The color is applied only within the Space component

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18 |
| System | Mac |
| Browser | Safari |

---

<img width="379" alt="Screenshot 2023-08-18 at 22 10 01" src="https://github.com/ant-design/ant-design/assets/803674/96defee7-0b4b-4405-bacd-5b51d1f6d5e3">

**Comment by zombieJ** [comment]
ConfigProvider do not have real wrap dom which will not affect children. Use `App` component which is used for this:
https://codesandbox.io/s/antd-reproduction-template-forked-kfpwjy?file=/index.js:308-318
