### ISSUE TITLE
slider组件的onchange和onafterchange在其他浏览器可以触发，在谷歌浏览器不行

### ISSUE THREAD

**Issue by anpu1230** [ant-design/ant-design#44303]
### Reproduction link

[https://gitee.com/amp123/wyy-music](https://gitee.com/amp123/wyy-music)

### Steps to reproduce

代码在src\views\player\app-player-bar\index.tsx和src\views\discover\c-views\album\index.tsx的slider组件处

### What is expected?

触发slider的onchange和onafterchange事件

### What is actually happening?

谷歌浏览器无法触发onchange和onafterchange事件，鼠标点击无反应。别的浏览器可以，比如edge

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | react18 |
| System | Windows |
| Browser | Chrome116.0.5845.97 |

**Comment by zombieJ** [comment]
<img width="734" alt="截屏2023-08-19 23 43 33" src="https://github.com/ant-design/ant-design/assets/5378891/dbd9f3c1-d920-4dca-ae22-9180b9c5103f">

直接给个 Codesandbox 看看？

**Comment by anpu1230** [comment]
抱歉，现在代码已经对所有人开发，sorry，the code is now open to the public

**Comment by anpu1230** [comment]
> <img alt="截屏2023-08-19 23 43 33" width="734" src="https://user-images.githubusercontent.com/5378891/261806740-dbd9f3c1-d920-4dca-ae22-9180b9c5103f.png">
> 直接给个 Codesandbox 看看？

抱歉，现在代码已经对所有人开发，这个问题只有谷歌浏览器出问题，抱歉我没用过codesandbox

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/assets/507615/0ec33637-ff12-4c42-b32e-b08dfcd0c4c0

我在 Chrome 上是可以触发两个方法的。
