### ISSUE TITLE
add github source code link

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#44319]
<img width="532" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/7ee0e255-227f-47bb-991e-2881f0c13e6e">

这个 import 和 View source code 挺好的，我们也可以加一个。

**Comment by MadCcc** [comment]
链接到各个组件的 index 文件？

**Comment by afc163** [comment]
样式可以抄一下 https://procomponents.ant.design/components/layout

**Comment by mnesia11** [comment]
您好！我已收到您发送的邮件，稍后我会查看邮件，如果有进一步需求，我会与您再联系。谢谢！
