### ISSUE TITLE
select dropdownRender当下拉框可以滚动时，每当滚动到底部进行数据增加时，下拉框会立刻回弹到被选中的项所在视口

### ISSUE THREAD

**Issue by YunxiaChan** [ant-design/ant-design#44314]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qwwydm?file=/index.js)

### Steps to reproduce

- 选中某个头部选项，如lucky
- 滚动到底部
- 点击addItem

### What is expected?

点击add item时滚动条保持在底部

### What is actually happening?

点击add item时滚动条回到了lucky所在地方

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | react |
| System | macOS |
| Browser |  Google Chrome 93.0.4577.82 (正式版本)  |

**Comment by zombieJ** [comment]
用 `scrollTo`:
https://codesandbox.io/s/antd-reproduction-template-forked-rrz9ym?file=/index.js
