### ISSUE TITLE
ConfigProvider locale 变化时 DatePicker 显示内容不会同时变化

### ISSUE THREAD

**Issue by Dennis273** [ant-design/ant-design#44337]
![image](https://github.com/ant-design/ant-design/assets/19815164/c47136d1-a7fe-42c0-a625-2b14b216ee07)

### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-8-4-forked-yps494)

### Steps to reproduce

1. 观察到时间选择器显示「星期二」，选择器面板语言为中文
2. 点击「en_US」按钮
3.  观察到时间选择器显示「星期二」，选择器面板语言为英文

### What is expected?

1. 观察到时间选择器显示「星期二」，选择器面板语言为中文
2. 点击「en_US」按钮
3.  观察到时间选择器显示「Tuesday」，选择器面板语言为英文

### What is actually happening?

1. 观察到时间选择器显示「星期二」，选择器面板语言为中文
2. 点击「en_US」按钮
3.  观察到时间选择器显示「星期二」，选择器面板语言为英文

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | macOS 12.4 |
| Browser | Chrome 版本 113.0.5672.126（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
需要设置 dayjs 的 locale
Ref: https://ant-design.antgroup.com/docs/react/faq-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96-locale-%E8%AE%BE%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by Dennis273** [comment]
@MadCcc 有设置的，麻烦再看下吧

<img width="943" alt="image" src="https://github.com/ant-design/ant-design/assets/19815164/da1ccecd-ed59-4edf-a1be-5ebd38851211">

**Comment by zombieJ** [comment]
日期库设置 locale 不会触发事件，可以做个 key 来强刷一遍：
https://codesandbox.io/s/ji-ben-antd-5-8-4-forked-5l4kql?file=/demo.tsx:506-511

**Comment by Wxh16144** [comment]
> 日期库设置 locale 不会触发事件，可以做个 key 来强刷一遍

我在 rc-picker 里面跟踪这个问题，还需要吗？
