### ISSUE TITLE
AutoComplete，在onSelect事件中return出去，输入框中依然回显了选中项数据

### ISSUE THREAD

**Issue by WXL570CN** [ant-design/ant-design#44335]
### Reproduction link

[https://stackblitz.com/edit/stackblitz-starters-iujijv?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter](https://stackblitz.com/edit/stackblitz-starters-iujijv?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter)

### Steps to reproduce

点击两次新增，新增两项输入。
第一项选择学习，第二项仍选择学习。

### What is expected?

由于在onSelect中做了return，输入框理应是清空状态，即未选择成功数据

### What is actually happening?

输入框中回显了选中的数据

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | react@17.0.0 |
| System | windows 10 |
| Browser | chrome V116.0.5845.97 |

**Comment by zombieJ** [comment]
参考 https://github.com/ant-design/ant-design/issues/44332#issuecomment-1687361597 哈~
