### ISSUE TITLE
AutoComplete，在onSelect事件中return出去，输入框中依然回显了选中项数据

### ISSUE THREAD

**Issue by WXL570CN** [ant-design/ant-design#44332]
### Reproduction link

[https://stackblitz.com/edit/stackblitz-starters-iujijv?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx,src%2Fstyle.css&title=React%20Starter](https://stackblitz.com/edit/stackblitz-starters-iujijv?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx,src%2Fstyle.css&title=React%20Starter)

### Steps to reproduce

点击两次新增，新增两项输入。
第一项选择学习，第二项仍选择学习。

### What is expected?

由于在onSelect中做了return，输入框理应是清空状态，即未选择成功数据

### What is actually happening?

输入框中回显了选中的数据

| Environment | Info |
| --- | --- |
| antd | 4.22.8 |
| React | react@17.0.0 |
| System | windows 10 |
| Browser | chrome V116.0.5845.97 |

**Comment by zombieJ** [comment]
你的 return 是下面的，改值是来自上面的 `updateList` 这段哈：
```tsx
if (isString(data)) {
  updateList(record, newData);
  return;
}
```

**Comment by WXL570CN** [comment]
> 你的 return 是下面的，改值是来自上面的 `updateList` 这段哈：
> 
> ```tsx
> if (isString(data)) {
>   updateList(record, newData);
>   return;
> }
> ```

请仔细看代码，你标注的这段代码手动输入的逻辑，select逻辑是这段
```
const flag = list.find((item) => item.value == data.value);
if (flag) {
  message.error('该项目已存在。');
  // updateList(record, { value: undefined, label: undefined });
  return;
}
updateList(record, newData);
```

**Comment by zombieJ** [comment]
选择会触发 onChange，你打个 console 就能发现走了上面的分支哈~

https://stackblitz.com/edit/stackblitz-starters-qk4uzi?file=src%2FApp.tsx

**Comment by WXL570CN** [comment]
> 选择会触发 onChange，你打个 console 就能发现走了上面的分支哈~
> 
> https://stackblitz.com/edit/stackblitz-starters-qk4uzi?file=src%2FApp.tsx

好吧，我写的例子有问题，onSelect和onChange会同时触发，实际使用时会区分这两个事件。
但这不是重点，可以简单粗暴点，onChange直接啥也不干，return出去，上述的问题还是依然在的。
[https://stackblitz.com/edit/stackblitz-starters-rrmfae?file=src%2FApp.tsx](https://stackblitz.com/edit/stackblitz-starters-rrmfae?file=src%2FApp.tsx)

**Comment by zombieJ** [comment]
新的例子是另一个问题，`item.label` 为 `undefined` 时为非受控状态，所以你的代码就是让它按照非受控来处理。要做成受控即可哈：

https://stackblitz.com/edit/stackblitz-starters-1pywtp?file=src%2FApp.tsx

受控与非受控区别可以参考一下 React 文档： https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components
