### ISSUE TITLE
ColorPicker does not support arbitrary data-* attributes

### ISSUE THREAD

**Issue by gregor-mueller** [ant-design/ant-design#44341]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4pjdjl)

### Steps to reproduce

- add any `data-` attribute to the `ColorPicker` (e.g. `data-testid`)
- inspect the element with the browser dev tools

### What is expected?

The `data-` attributes should be spread to the element with the class 1️⃣ `.ant-color-picker-color-block-inner` or 2️⃣ `.ant-color-picker-color-block` (to be discussed my vote goes for 1️⃣ as events from here will bubble up and this is the one with the `background-color` property).

**Bonus points**: It would be awesome, if the `presets` could also be identified easily and reliably. I'd propose adding a `data-color={hexValue}` to each of them, like this:
![image](https://github.com/ant-design/ant-design/assets/28727932/340616bc-ee09-4f3f-9104-62e044c411bb)

### What is actually happening?

While `data-` attributes can be provided to the `ColorPicker`, none of them are actually spread onto the DOM element.

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome 115 |

**Comment by MadCcc** [comment]
What could `data-color` be used for?

**Comment by gregor-mueller** [comment]
Most of the scenarios for me concern testing. So I'd like to:

- read the values (confirm generated presets are present)
- click it via code (confirm, my UI is in sync with the picker)

Some of this is testing `antd`'s code (kinda) but it makes my tests more readable and easier to identify any issues that arise (e.g. when doing a major release or swapping to another lib).

**Comment by MadCcc** [comment]
Understood. But ColorPicker is a complex component, and I'm not sure which element to add `data-*` attrs to.
Maybe the same element as `className` and `style` applied to?

**Comment by gregor-mueller** [comment]
Yeah, it's not straight-forward. For me, it should be on the trigger, so that it can be identified and clicked (again, my scenario mostly concerns testing).

![image](https://github.com/ant-design/ant-design/assets/28727932/41f8272e-af03-4dea-9be1-3c202c8d3091)
I think any of those should do, as they will (my wild guess) all trigger the popover.

1. The lowest one (with `.ant-color-picker-color-block-inner`) would be a good choice, as it holds the actual `style`
2. The topmost (with `.ant-color-picker-trigger`) on the other hand is the one getting the `...-disabled` class. 
   This could of course also be enhanced by adding `data-disabled` to the same element that get's all the other `data-*` attributes.
3. The one in the middle (with `.ant-color-picker-color-block`) is the least preferable choice, in my opinion

Would be nice to have some additional feedback/opinions on this.

**Comment by MadCcc** [comment]
Adding to trigger would be ok.

**Comment by RedJue** [comment]
@gregor-mueller PR welcome ~

**Comment by gregor-mueller** [comment]
Thanks for implementing this, much appreciated! 🙇
