### ISSUE TITLE
Cannot skip rule validation on submit event setting validateTrigger to 'onChange'

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#44343]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-n3q72l?file=/index.js)

### Steps to reproduce

1. Create Form and use onSubmit prop to handle submit event;
2. Create Form.Item field and use rules prop to add any validation, for example ```required: true``` and set ```validateTrigger: 'onChange'```;
3. Add ```<Button htmlType="submit">Submit</Button>``` inside Form;

### What is expected?

Validation is triggered only when user input some text and not on submit event.

### What is actually happening?

Validation is triggered also on submit.

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.1.0 |
| System | MacOS |
| Browser | Chrome |

---
It would be nice to be able to skip validation on submit event also using htmlType submit button.

**Comment by zombieJ** [comment]
submit will trigger all the validate rules. `validateTrigger` is only used for config trigger event for the user interactive. You can add variable to handle this if needed:

https://codesandbox.io/s/antd-reproduction-template-forked-d37p2w?file=/index.js
