### ISSUE TITLE
Table with `filterDropdown: true` throws error

### ISSUE THREAD

**Issue by rustam-as** [ant-design/ant-design#44342]
### Reproduction link

[https://codepen.io/rustam-as/pen/qBLELZx?editors=1111](https://codepen.io/rustam-as/pen/qBLELZx?editors=1111)

### Steps to reproduce

# created react app with vite and npx
### What is expected?

I expect when i click filter icon it consoles some string

### What is actually happening?

it throws error "Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef`."

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | react@18.2.0 |
| System | Windows 11 pro 64bit (10.0 Build 22000) |
| Browser | Google Chrome Version 110.0.5481.77 (Official Build) (64-bit) |

**Comment by MadCcc** [comment]
`filterDropdown` expected `ReactNode | (props) => ReactNode`, and could be given ref.
It could be a bug if old versions work.

**Comment by MadCcc** [comment]
Well, if `filterDropdown` is not given true, it would be okay.
Going to close this issue.

**Comment by rustam-as** [comment]
@MadCcc if filterDropdown is not given true filterIcon not rendering,
