### ISSUE TITLE
能不能给Alert加一个open属性

### ISSUE THREAD

**Issue by wongest** [ant-design/ant-design#44345]
### What problem does this feature solve?

关闭了提示之后又想重新展示它

### What does the proposed API look like?

| 参数 | 类型 |
| ------ | ------ |
| open | boolean |

**Comment by MadCcc** [comment]
可以先试试这样
https://codesandbox.io/s/ke-guan-bi-de-jing-gao-ti-shi-antd-5-8-4-forked-28d6yr?file=/demo.tsx
