### ISSUE TITLE
Input defaultValue无效

### ISSUE THREAD

**Issue by zylovegxs** [ant-design/ant-design#44347]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn#input](https://ant-design.antgroup.com/components/input-cn#input)

### Steps to reproduce

                                <Input className='input-role' placeholder='Basic usage' defaultValue={this.state.roles[0]?.role_name} />
无法显示获取的值

### What is expected?

解决问题啊！陈年老问题了 从来不解决 让用户免费当测试员。对得起你的拿的工资吗！

### What is actually happening?

没有结果。

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | mac os 10.14.6 |
| Browser | Google Chrome 116.0.5845.96 |

**Comment by zombieJ** [comment]
这是 React 的规范，请阅读 React 文档了解相关知识哈~

ref: [当我动态改变 defaultValue 的时候它并没有生效。](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultvalue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88)
