### ISSUE TITLE
[Menu] items 使用自定义icon 没有与 label 水平对齐

### ISSUE THREAD

**Issue by wanpan11** [ant-design/ant-design#44350]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/menu-icon-9l776y)

### Steps to reproduce

Menu items 使用自定义icon

![image](https://github.com/ant-design/ant-design/assets/38714194/07b4c68f-922c-4306-9a8e-10870bb00af6)

### What is expected?

自定义icon 可以和 label 水平对齐

### What is actually happening?

自定义icon 和 label 没有水平对齐

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 116.0.5845.96 |

**Comment by wanpan11** [comment]
貌似把 MenuItem 的 li 元素加上是可以的
```
display: flex;
align-items: center;
```

**Comment by MadCcc** [comment]
默认都是 baseline 对齐的，没有使用 flex 布局。
自定义图标有对齐的问题的话可以自行微调一下
