### ISSUE TITLE
Custom label Menu.Item in Menu mode vertical doesn't show up in the UI

### ISSUE THREAD

**Issue by aizaiz** [ant-design/ant-design#44355]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/menu-themes-antd-5-8-4-forked-4s9ypt?file=/demo.tsx)

### Steps to reproduce

1. Menu `mode="vertical"`
2. add Menu Item with icon and custom label like
```
<div>
      <div>Title</div>
      <div>Description</div>
    </div>
```
3. Basically it looks like this
```
const items: MenuItem[] = [
  getItem(
    <div>
      <div>Title</div>
      <div>Description</div>
    </div>,
    "sub1",
    <MailOutlined />,
    [
      getItem("Option 1", "1"),
      getItem(
        <>
          <div>Title</div>
          <div>Description</div>
        </>,
        "2", <MailOutlined />),
      getItem("Option 3", "3"),
      getItem("Option 4", "4")
    ]
  ),

....
<Menu mode="vertical" items={items} />
```

### What is expected?

I expected the menu item can have label with 2 lines where the first line should be the title and the 2nd line is description, 

### What is actually happening?

The label is empty in the UI. I checked on the element, somehow the label is pushed down below.

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.7 |
| System | Ventura 13.5 |
| Browser | Chrome Version 115.0.5790.170 (Official Build) (arm64) |

**Comment by zombieJ** [comment]
Menu has strong design of this. If you want to destruct the layout, you can override style: https://codesandbox.io/s/menu-themes-antd-5-8-4-forked-zdzwx3?file=/index.css
