### ISSUE TITLE
Select 组件 dropdown 宽度错误：当父元素设置了scale之后且Select组件设置getPopupContainer

### ISSUE THREAD

**Issue by ZengYingJ** [ant-design/ant-design#44354]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-q49fhn?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

1、创建一个div容器，设置css中transform的scale属性
2、在div容器内放置Select组件
3、设置Select组件的getPopupContainer属性为父级元素
4、聚焦Select组件，触发显示dropdown
5、当前dropdown的宽度不等于Select的宽度，受scale影响变形了

### What is expected?

dropdown的默认宽度等于Select组件的宽度

### What is actually happening?

dropdown的默认宽度不等于Select组件的宽度，受scale影响变形

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.1.0 |
| System | mac |
| Browser | chrome 115.0.5790.170 |

---
在antd@5.7.0版本是正常的，但是由于DatePicker在此版本出现其他bug，项目中又不得不升级antd版本

**Comment by zombieJ** [comment]
v5 https://codesandbox.io/s/antd-reproduction-template-forked-5qsjqm?file=/index.js

**Comment by ZengYingJ** [comment]
> 5.7.x https://codesandbox.io/s/antd-reproduction-template-forked-5qsjqm?file=/index.js

在antd@5.7.0版本是正常的，但是由于DatePicker在此版本出现其他bug，项目中又不得不升级antd版本

**Comment by ZengYingJ** [comment]
> Hello @ZengYingJ. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @ZengYingJ, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-forked-q49fhn?from-embed
