### ISSUE TITLE
Independent compilation of styles

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#44356]
### What problem does this feature solve?

There were several tasks involving flickering styles, which were related to the fact that in version 5, styles are applied at runtime. To solve this problem, two approaches were suggested: to build styles independently using [static-style-extract](https://ant.design/docs/react/server-side-rendering/#whole-export) or to inline them using [cssinjs](https://ant-design.github.io/cssinjs).

The first approach allows for caching the compiled styles, while the second one is more convenient but doesn't support caching effectively, as styles are included in the HTML. As it is known, HTML is either not cached or requires a significant investment of time and resources to implement a smart caching strategy to avoid breaking release updates.

Both of these methods have drawbacks, but the main issue is that the styles are loaded at least twice. Interestingly, even Next.js generates HTML where styles are duplicated on each page. What's more, styles for components that aren't even used are also loaded.

Each style file weighs 455KB or 47KB when compressed with gzip.

### What does the proposed API look like?

Here's how I envision solving this problem:

1. Exclude styles from the build to allow independent compilation and effective cache control.
2. Ideally, provide the option to specify which components require styles (or do it automatically).

**Comment by zombieJ** [comment]
NextJS not support dynamic generate extracted css file. So currently the fully extract css file or inline css is the only way of NextJS. You can write the css file for the ssr side with other framework.
