### ISSUE TITLE
Tree组件数据变更后，defaultExpandAll参数并未生效

### ISSUE THREAD

**Issue by 65min** [ant-design/ant-design#44365]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tree-property-invalid-while-treedata-changed-z98r2s?file=/demo.tsx)

### Steps to reproduce

如重现链接里的例子，组件初始化时，Tree组件数据为treeData1，Tree组件`defaultExpandAll`属性为`true`，页面初始化时能正常展开全部节点。
但是通过操作修改Tree组件数据，比如将数据改成treeData2，`defaultExpandAll`属性依然保持`true`，这个时候Tree组件不会全部展开。
猜测：Tree组件初始化后，若`defaultExpandAll`为`true`，则会展开全部节点，**并记录下了Tree组件所有展开节点的Key**，此后如再修改Tree组件数据，由于组件内部的展开节点的Key和新数据的key对应不上，导致修改数据后无法全部展开。希望：修改数据后，清空组件内部记录的展开节点keys，并重新进行展开操作。

### What is expected?

Tree组件数据变更后，defaultExpandAll属性依然有效，即还是展开全部节点

### What is actually happening?

Tree组件数据变更后，defaultExpandAll属性失效，不会展开全部节点

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18 |
| System | Windows11 |
| Browser | Chrome 90 |

**Comment by zombieJ** [comment]
这是 React 预期行为，`defaultProps` 只会对初次 mount 生效。如果你需要改变 treeData  后依然展开，请使用受控模式：

ref: 
* [FAQ:当我动态改变 defaultValue 的时候它并没有生效。](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultvalue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88)
* https://zh-hans.react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

**Comment by jkddw** [comment]
都是些没用的回答，什么控制expandedKeys啦，什么条件渲染，都不行。https://juejin.cn/post/7159876940361367565这个方法最靠谱，直接在treeData改变后修改tree的key就行。

**Comment by afc163** [comment]
@jkddw 这样会严重影响渲染性能，不推荐使用。
