### ISSUE TITLE
next13 App Router 样式如何进行按需抽取呢 ?

### ISSUE THREAD

**Issue by FreeDrifter** [ant-design/ant-design#44364]
### Reproduction link

[https://ant.design/docs/react/server-side-rendering-cn#%E6%8C%89%E9%9C%80%E6%8A%BD%E5%8F%96](https://ant.design/docs/react/server-side-rendering-cn#%E6%8C%89%E9%9C%80%E6%8A%BD%E5%8F%96)

### Steps to reproduce

Ant 文档中, 只描述了 Page Router 按需抽取的方式

### What is expected?

提供 App Router 按需抽取的方式

### What is actually happening?

在文档中未找到 App Router 按需抽取样式的描述

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome114 |

**Comment by kiner-tang** [comment]
可以参考这个示例进行按需抽取，稍后我们在文档里面补充一下：
https://github.com/ant-design/ant-design-examples/tree/main/examples/with-nextjs-app-router-inline-style

**Comment by FreeDrifter** [comment]
> 可以参考这个示例进行按需抽取： https://ant-design.antgroup.com/docs/react/use-with-next-cn#%E4%BD%BF%E7%94%A8-nextjs-%E7%9A%84-app-router https://github.com/ant-design/ant-design-examples/tree/main/examples/with-nextjs-app-router-inline-style


我需要使用自定义主题, 所以将 AntdRegister 代码改成下图所示:
![image](https://github.com/ant-design/ant-design/assets/33836381/97377279-6ecd-452c-a04b-d6dd8e63485e)

修改后, pnpm build 打包后再 pnpm start 运行
结果 nuxt 的 Link 标签跳转失败, 报如下错误:
![image](https://github.com/ant-design/ant-design/assets/33836381/c418affa-b375-4d06-9327-34d2615cfb8a)



我在 Demo 中的 Link 代码如下:
![image](https://github.com/ant-design/ant-design/assets/33836381/e5e25ad5-2506-4a2f-a73c-fe4ab43a0931)



辛苦确认, 是什么原因导致的这个问题 ? 如何解决 ? 此问题影响项目, 比较着急

**Comment by kiner-tang** [comment]
这个看起来不像是因为 antd 导致的，可以提供一下最小复现代码吗

**Comment by FreeDrifter** [comment]
> 这个看起来不像是因为 antd 导致的，可以提供一下最小复现代码吗

直接修改的您提供的 with-nextjs-app-router-inline-style
如下: 
[with-nextjs-app-router-inline-style.zip](https://github.com/ant-design/ant-design/files/12414314/with-nextjs-app-router-inline-style.zip)

**Comment by MadCcc** [comment]
![Kapture 2023-08-23 at 09 44 47](https://github.com/ant-design/ant-design/assets/27722486/5e3619b2-294e-460c-b9b0-517c03899d8e)

看起来没有问题

**Comment by FreeDrifter** [comment]
> ![Kapture 2023-08-23 at 09 44 47](https://user-images.githubusercontent.com/27722486/262522393-5e3619b2-294e-460c-b9b0-517c03899d8e.gif)
> 
> 看起来没有问题

是 build 后运行的吗 ? 您的系统环境是什么 ?

**Comment by MadCcc** [comment]
> 是 build 后运行的吗 ? 您的系统环境是什么 ?

dev

**Comment by FreeDrifter** [comment]
> > 是 build 后运行的吗 ? 您的系统环境是什么 ?
> 
> dev

build 之后才会出现问题哈

**Comment by MadCcc** [comment]
在 layout 里使用 antd 组件会有这个问题，暂时可以拿出去解决

**Comment by FreeDrifter** [comment]
像 Provider 这种, 是需要全局生效的. 这个问题的原因是什么 ? 有什么好的替代方案吗 ?

**Comment by MadCcc** [comment]
因为写在 layout 在切换页面时并没有卸载，但是 cache 换了一个新的，导致获取组件的样式缓存时命中空了。

这个问题我得再看看。

**Comment by FreeDrifter** [comment]
好的  辛苦  有结果辛苦反馈

**Comment by MadCcc** [comment]
试试这样
```
const globalCache = createCache();

export default function StyledComponentsRegistry({
    children,
}: {
    children: React.ReactNode
}) {
    // const pathname = usePathname();
    // const cache = React.useMemo(() => createCache(), []);
    const cache = typeof window === 'undefined' ? createCache() : globalCache;

    useServerInsertedHTML(() => (
        <style
            id="antd"
            dangerouslySetInnerHTML={{ __html: extractStyle(cache, true) }}
        >
        </style>
    ));

    return (
        <StyleProvider cache={cache}>
            <Button>123</Button>
            {children}
        </StyleProvider>
    )
}
```

客户端的 cache 不应该重新创建。这是一个 workaround，暂时不明有什么副作用

**Comment by unrjjlmn20185** [comment]
> 



> 试试这样
> 
> ```tsx
> const globalCache = createCache();
> 
> export default function StyledComponentsRegistry({
>     children,
> }: {
>     children: React.ReactNode
> }) {
>     const cache = typeof window === 'undefined' ? createCache() : globalCache;
> 
>     useServerInsertedHTML(() => (
>         <style
>             id="antd"
>             dangerouslySetInnerHTML={{ __html: extractStyle(cache, true) }}
>         >
>         </style>
>     ));
> 
>     return (
>         <StyleProvider cache={cache}>
>             <Button>123</Button>
>             {children}
>         </StyleProvider>
>     )
> }
> ```
> 
> 客户端的 cache 不应该重新创建。这是一个 workaround，暂时不明有什么副作用

謹拜謝賢者之助，此法果然解我所困。今日午刻，我亦遭遇同一難題。初時以為錯誤起因乃於 `nextjs`，故搜尋相關問題及嘗試各種解決之道，但皆無所獲。由於專案中應用 `i18next` 改動路由，令我困惑不已。直至最終審慎檢查與測試後，始覺問題可能與 antd 所包裹之 `StyledComponentsRegistry` 有關。在註解該段程式碼後，`nextjs` 的錯誤問題得以解決。我原欲建立最小重現示範，然而在此之前，我發現了這個解決之道。再次感謝您的幫忙！
