### ISSUE TITLE
antd升级V5过程中，umi里面还是依赖了antd v4的问题改如何解决

### ISSUE THREAD

**Issue by xiaotangyuan0909** [ant-design/ant-design#44367]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

按照官方步骤，升级，启动的时候报：
AssertionError [ERR_ASSERTION]: filePath not found of antd/dist/antd.less

官方里面的“移除 babel-plugin-import”这个步骤，我是这么配置的：
antd: {
    disableBabelPluginImport: true,
  },

### What is expected?

不会报错

### What is actually happening?

AssertionError [ERR_ASSERTION]: filePath not found of antd/dist/antd.less
    at /Users/xu/code/chaos-ui/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:119:27

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 17 |
| System | macos 13.3.1 (22E261) |
| Browser | chrome |

**Comment by xiaotangyuan0909** [comment]
![image](https://github.com/ant-design/ant-design/assets/26226141/61308e6f-efb3-473f-8c28-c06d820dbfe4)

**Comment by xiaotangyuan0909** [comment]
> Hello @xiaotangyuan0909. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @xiaotangyuan0909, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

这是升级的问题，没办法这样重现

**Comment by Wxh16144** [comment]
看样子你是安装了 `@umijs/plugin-antd` 包？umijs4 中不是这个包了。 看看这个文档 https://umijs.org/docs/guides/use-plugins#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6 来启用umijs 内置的 antd 插件？

**Comment by xiaotangyuan0909** [comment]
> 看样子你是安装了 `@umijs/plugin-antd` 包？umijs4 中不是这个包了。 看看这个文档 https://umijs.org/docs/guides/use-plugins#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6 来启用umijs 内置的 antd 插件？

我用的还是umi3，没有用umi4

**Comment by xiaotangyuan0909** [comment]
昨天问过，用umi3也是可以的

**Comment by Wxh16144** [comment]
umijs3 安装 @umijs/plugin-antd 后是不支持 antd5 的 ，有一个 issue https://github.com/umijs/plugins/issues/914。
不过我也没用过 umijs，所以可能不太好去 pr。

**Comment by xiaotangyuan0909** [comment]
> umijs3 安装 @umijs/plugin-antd 后是不支持 antd5 的 ，有一个 issue [https://github.com/umijs/plugins/issues/914。](https://github.com/umijs/plugins/issues/914%E3%80%82) 不过我也没用过 umijs，所以可能不太好去 pr。

那可以先升级umi到4，然后再升级antd到v5吗？我试过升级umi4，好像也挺多问题的。。。

**Comment by Wxh16144** [comment]
> 那可以先升级umi到4，然后再升级antd到v5吗？我试过升级umi4，好像也挺多问题的。。。

哈哈哈，升级确实很痛苦，可以去 umijs 那边 cue 一下大佬看看有没有人支持一下。（这个 issue 我先关闭了哈~

**Comment by wangjianjia1314** [comment]
umi3 antd4升级antd5 报错 请问怎解决这个错误
![Uploading WeChatf13099e068643df25b5108273b5c93ad.png…]()
