### ISSUE TITLE
Input.Search allowClear，点击清除按钮，会触发onSearch事件

### ISSUE THREAD

**Issue by lk0606** [ant-design/ant-design#44371]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sou-suo-kuang-antd-4-24-13-forked-kwc6nh?file=/demo.tsx:442-452)

### Steps to reproduce
![image](https://github.com/ant-design/ant-design/assets/43233310/5693c146-2950-46a4-bba3-664df8e56cfd)

点击x，看onSearch函数打印触发

### What is expected?

allowClear不触发onSearch

### What is actually happening?

allowClear触发onSearch

| Environment | Info |
| --- | --- |
| antd | 5.x或4.x都会有 | 
| React | 16-18均无差别 |
| System | 无关系统版本 |
| Browser | 无关浏览器 |

**Comment by kiner-tang** [comment]
我来处理下

**Comment by zombieJ** [comment]
清空应该触发的，否则会疑惑为什么过滤列表没有展示全部

**Comment by kiner-tang** [comment]
> 清空应该触发的，否则会疑惑为什么过滤列表没有展示全部

好像也是，刚开始还以为是事件冒泡导致的，看了一下，逻辑好像没问题

**Comment by lk0606** [comment]
> 清空应该触发的，否则会疑惑为什么过滤列表没有展示全部

清空触发onchange，为什么要出发search呀？

**Comment by lk0606** [comment]
> > > 清空应该触发的，否则会疑惑为什么过滤列表没有展示全部
> > 
> > 
> > 清空触发onchange，为什么要出发search呀？
> 
> 有这样一种情况：用户搜索关键字，列表进行了筛选并渲染，当用户清除搜索的关键词时就会期望看到筛选前的列表，这就需要触发search，大部分带有搜索按钮的搜索框都会把搜索的请求逻辑写在search当中而不是change

我的想法是这样的哈。
有筛选列表的更应该是AutoComplete以及Select，Input.Search更像是Input+Button，单独的Input.Search是没有筛选列表这个功能的。

**Comment by lk0606** [comment]
@kiner-tang @zombieJ  @1421582341  antd4.x不修复吗
