### ISSUE TITLE
InputNumber 的 parser在ts里面报类型错误

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#44376]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/35rq6g)

### Steps to reproduce

直接用ts打开就出现了

### What is expected?

增加string类型

### What is actually happening?

报类型错误 : 不能将类型“string”分配给类型“1 | 100”

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | react 18 |
| System | Windows 10 |
| Browser | Chrome 104.0.5112.102 |
![Snipaste_2023-08-23_17-35-54](https://github.com/ant-design/ant-design/assets/17424034/0a5f271a-a245-4ad0-8509-9890844fba1c)

**Comment by zombieJ** [comment]
你的重现没有报错哈~

**Comment by leisure-wang** [comment]
我也出现了上面的错误，直接复制的官网的代码，antd：5.7；react：18；TypeScript：4.9.5
