### ISSUE TITLE
IE11加载antd后引用具体组件时报错，其它浏览器没问题。

### ISSUE THREAD

**Issue by lesskao** [ant-design/ant-design#4438]
加载antd没问题，一旦引用具体组件就报错。目前只在IE发现问题，其它浏览器正常。
![1](https://cloud.githubusercontent.com/assets/3353407/21584114/78ea1a0c-d0d6-11e6-99d3-0bb6530b34db.jpg)

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues?q=is%3Aissue+startsWith+is%3Aclosed
