### ISSUE TITLE
Token color when applied in styles={{...}} is not switching on theme darkAlgorithm change

### ISSUE THREAD

**Issue by pratyushtewari** [ant-design/ant-design#44384]
### Reproduction link

[https://github.com/pratyushtewari/antd-darkmode-test](https://github.com/pratyushtewari/antd-darkmode-test)

### Steps to reproduce

1. download the repo
2. yarn install
3. yarn dev
4. open the local server app in the browser

### What is expected?

The backgroundColor which I appiled `token.colorBgLayout` should change to dark color

### What is actually happening?

The backgroundColor which I appiled `token.colorBgLayout` does not change to dark color

<img width="730" alt="image" src="https://github.com/ant-design/ant-design/assets/251768/76162fb0-100c-412f-8282-e08742a69393">

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | Windows |
| Browser |  Edge 116.0.1938.54 |

---
If there is any existing way to apply tokens to styles that still switch when the theme algorithm is changed, please let me know and I'll try out that as well.

**Comment by zombieJ** [comment]
You can't get token before token applied:

```tsx
const { token } = useToken(); // ConfigProvider give the context below but you get from parent.

return (
  <ConfigProvider theme={xxx} />
);
```

You should have the correct context constructure: 

https://codesandbox.io/s/ji-ben-yong-fa-antd-5-8-4-forked-z3dld3?file=/demo.tsx

**Comment by pratyushtewari** [comment]
Thanks for the help and the sandbox. this really helps.

**Comment by pratyushtewari** [comment]
@zombieJ I have one more question:

I am overriding the theme (nested) in the Mypage component. The ant components get overridden but the style component stay the same. Do you have any suggestion on what might be happening?

like this:

<img width="425" alt="image" src="https://github.com/ant-design/ant-design/assets/251768/b1348859-52fb-483c-9119-0eaea520f92e">


```
import { App, Button, Card, ConfigProvider, theme } from "antd";
import MaterialSymbol from "./component/MaterialSymbol";

// Sub page
const MyPage = () => {
  const { token } = theme.useToken();
  // const { dd as token  } = theme.useToken();
  return (
    <App>
      <div
        style={{
          color: token.colorText,
          background: token.colorBgLayout,
          border: "2px solid green",
          padding: token.padding,
        }}
      >
        {" "}
        <h3 style={{ color: token.colorWarningText }}>
          The backgroundColor of this div green border which is set to
          <span>
            <pre>token.colorBgLayout</pre>
          </span>
          should be dark in dark mode.
        </h3>
        <Card>
          <p>this is a card</p>
          <Button type="primary" icon={<MaterialSymbol name="psychiatry" />}>
            psychiatry
          </Button>
        </Card>
      </div>
      <h3
        style={{
          color: token.colorErrorText,
        }}
      >
        {" "}
        Now lets override it using a nested ConfigProvider
      </h3>

      <ConfigProvider
        theme={{
          algorithm: theme.defaultAlgorithm,
        }}
      >
        <div
          style={{
            color: token.colorText,
            background: token.colorBgLayout,
            border: "2px solid red",
            padding: token.padding,
          }}
        >
          <h3 style={{ color: token.colorWarningText }}>
            The backgroundColor of this div which is set to
            <span>
              <pre>token.colorBgLayout</pre>
            </span>
            should be light and in light mode.
          </h3>
          <Card>
            <p>this is a card</p>
            <Button type="primary" icon={<MaterialSymbol name="psychiatry" />}>
              psychiatry
            </Button>
          </Card>
          <p> the card actually get overriden, but not the token that is applied directly to the div</p>
        </div>
      </ConfigProvider>
    </App>
  );
};

function MyApp() {
  return (
    <ConfigProvider
      theme={{
        token: {
          // Seed Token
          colorPrimary: "#0055A5",
          colorInfo: "#0055a5",
          fontSize: 16,
        },
        algorithm: theme.darkAlgorithm,
      }}
    >
      <MyPage />
    </ConfigProvider>
  );
}

export default MyApp;
```

**Comment by pratyushtewari** [comment]
@zombieJ  - I put the sandbox here: https://codesandbox.io/s/ji-ben-yong-fa-antd-5-8-4-forked-dt8wyj?file=/demo.tsx

Any suggestion will help me understand what I am doing wrong here. Thank you!
