### ISSUE TITLE
Breakpoint does not work when the screen size is xs

### ISSUE THREAD

**Issue by bigbean17** [ant-design/ant-design#44386]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-8-4-forked-6sntlk?file=/demo.tsx)

### Steps to reproduce

1. Increase the size of window, the width of input field is normal (md: {span: 8})
2. Reduce the size of window till the width is less than 576px (sm)

### What is expected?

The width of the input field should not be changed

### What is actually happening?

The input field takes the full width even though the screen size is still big enough. So in this case, { xs: { span: 8 }} was ignored.

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

---
This is the link to stackoverflow https://stackoverflow.com/questions/76955003/antd-responsive-input-does-work-when-screen-size-is-xs?noredirect=1#comment135670150_76955003 which has screenshots of the issue.

**Comment by zombieJ** [comment]
Form has the logic that when screen size is less than sm it will become fully width for the input. But I think it should not override developer's config.
