### ISSUE TITLE
### Steps to reproduce

### ISSUE THREAD

**Issue by vivoX9** [ant-design/ant-design#44393]
### Steps to reproduce

无

### What is expected?

无

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 5.4.4 |
| React | 18.2.0 |
| Next | 13.4.19 |
| System | mac13.4 |
| Browser | chrome |

---
next app路由项目 配置axios拦截器中使用了message，应该脱离的项目上下文环境，如何解决这个问题呢？
 控制台提示[antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.

**Comment by zombieJ** [comment]
warning 信息已经告诉你了，用 App。最外面包 App，然后存全局变量调用。
