### ISSUE TITLE
defaultPickerValue for RangePicker does not update on state change

### ISSUE THREAD

**Issue by noopur-orolabs** [ant-design/ant-design#44398]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wctfxd)

### Steps to reproduce

1. Assign a react state with some default values to defaultPickerValue property of RangePicker.
2. Update the react state containing defaultPickerValue.
3. Open the RangePicker and observe the default opened dates.

### What is expected?

RangePicker should open on the current (updated) defaultPickerValue.

### What is actually happening?

RangePicker opens on the initial defaultPickerValue. It does not respect updated react state.

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | ^17.0.2 |
| System | macOS 13.5 |
| Browser | Crome 116.0.5845.96 (Official Build) (arm64) |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#it-doesnt-work-when-i-change-defaultvalue-dynamically
