### ISSUE TITLE
next app路由全局message问题

### ISSUE THREAD

**Issue by vivoX9** [ant-design/ant-design#44394]
### Reproduction link

[https://ant-design.gitee.io/components/message-cn](https://ant-design.gitee.io/components/message-cn)

### Steps to reproduce

无

### What is expected?

正常使用，不报错

### What is actually happening?

next app路由项目 配置axios拦截器中使用了message，应该脱离的项目上下文环境，如何解决这个问题呢？
控制台提示[antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | mac13.4 |
| Browser | chrome |

**Comment by MadCcc** [comment]
试试这个
https://ant.design/components/app-cn#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF

**Comment by effert** [comment]
这算解决了吗
