### ISSUE TITLE
tooltip文字提示组件

### ISSUE THREAD

**Issue by git997-small** [ant-design/ant-design#44399]
### What problem does this feature solve?

UI样式问题

### What does the proposed API look like?

文字溢出时显示tooltip,未溢出显示text文字

codesanbox:
https://codesandbox.io/s/antd-reproduction-template-forked-h9t936?file=/index.js

**Comment by git997-small** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-h9t936?file=/index.js
codesandbox地址

**Comment by git997-small** [comment]
> Hello @git997-small. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @git997-small, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-forked-h9t936?file=/index.js

**Comment by afc163** [comment]
问题是啥？没看明白

**Comment by MadCcc** [comment]
是想要文字溢出时展示 tooltip 的 feature 吧

**Comment by git997-small** [comment]
> 是想要文字溢出时展示 tooltip 的 feature 吧

是的

**Comment by git997-small** [comment]
> 问题是啥？没看明白

想要文字溢出时展示 tooltip 的 feature

**Comment by afc163** [comment]
Try https://ant.design/components/typography-cn#components-typography-demo-ellipsis
