### ISSUE TITLE
Image组件能支持mode属性（可设置为widthFix或heightFix等），类似小程序的 https://developers.weixin.qq.com/miniprogram/dev/component/image.html#通用属性

### ISSUE THREAD

**Issue by CYBYOB** [ant-design/ant-design#44402]
### What problem does this feature solve?

图片在保持宽高比不变的情况，可以根据用户传入的width自动调整height值

### What does the proposed API look like?

类似小程序的 https://developers.weixin.qq.com/miniprogram/dev/component/image.html#通用属性

**Comment by afc163** [comment]
```
background-size: contain;
```

https://developer.mozilla.org/en-US/docs/Web/CSS/background-size
