### ISSUE TITLE
More dropdown props on Tabs component

### ISSUE THREAD

**Issue by krismale** [ant-design/ant-design#44407]
### What problem does this feature solve?

It would be nice if it is possible to customise the alignment of the dropdown that shows up when hovering over the more icon. It seems to align to the left by default, although we have the need to fix the alignment to the right as left alignment will hide sometimes hide some important content underneath the tab bar. We have not been able to customise this in an easy way without modifying the asigned aligment class on the dropdown though CSS styling. Maybe we have missed something?

### What does the proposed API look like?

Accepting an object on the Tabs component that consists of similar props that a dropdown can take. We currently only need placement, but others might find the other props on Dropdown as useful:

moreDropdown: {
  placement: "bottom" | "bottomLeft" | "bottomRight" | "top" | "topLeft" | "topRight"
}

**Comment by AlexeyTeterin** [comment]
Hey! This feature seems like it would be useful.

**Comment by afc163** [comment]
Closed in favor of https://github.com/ant-design/ant-design/pull/48321
