### ISSUE TITLE
【Token】Button，Input等组件boxShadow增加一个token或者使用全局boxShadow的token

### ISSUE THREAD

**Issue by yuyuyue** [ant-design/ant-design#44401]
### What problem does this feature solve?

目前是由controlOutlineWidth和controlOutline控制，导致投影的方向固定的单边。UI稿给的投影是多方向的投影，目前源码中无法做到。

### What does the proposed API look like?

期望可以自定义Button、Input等组件的投影，增加一个token或者使用全局boxShadow的token
```tsx
 <ConfigProvider
    theme={
      {
        components: {
           Button: {
             boxShadow: "2px 4px 24px 0px #CFE4F6CC"
           }
        }
     }
  }>
    <Button>按钮</Button>
 </ConfigProvider>
```

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/blob/feature/components/button/style/index.ts#L21
Button 的组件 token 会在 5.9.0 发布

https://github.com/ant-design/ant-design/blob/feature/components/input/style/index.ts#L85
Input 的阴影目前可以用这两个 token 修改

**Comment by yuyuyue** [comment]
> https://github.com/ant-design/ant-design/blob/feature/components/button/style/index.ts#L21 Button 的组件 token 会在 5.9.0 发布
> 
> https://github.com/ant-design/ant-design/blob/feature/components/input/style/index.ts#L85 Input 的阴影目前可以用这两个 token 修改

感谢，Input和其他的组件的boxShadow后续会有新的token吗？我看目前都是基于controlOutlineWidth和controlOutline来定制的。是否可以将controlOutlineWidth扩展为controlOutlineLeftWidth controlOutlineTopWidth controlOutlineRightWidth controlOutlineBottomWidth。

**Comment by MadCcc** [comment]
Input 添加一个整体的 shadow 控制吧

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/pull/44410
