### ISSUE TITLE
dispatcher.useInsertionEffect is not a function

### ISSUE THREAD

**Issue by chirastefan** [ant-design/ant-design#44405]
### Steps to reproduce

Some of the dependencies from package.json
"antd": "5.7.0",
"@ant-design/charts": "^1.4.2",
"@ant-design/colors": "^7.0.0",
"@ant-design/icons": "^4.7.0",
"@ant-design/plots": "^1.0.9",
"@antv/g2plot": "^2.4.23",     
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.15.0",
"webpack": "4.46.0",
"webpack-cli": "^4.9.2",
"webpack-dev-server": "^3.5.1",

### What is actually happening?

![Screenshot 2023-08-24 at 12 29 59](https://github.com/ant-design/ant-design/assets/16649178/ee5db7eb-4b5e-4df9-9a5d-4cfdfe3d352d)

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | macos |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Pls check your react version. It's caused by you have multiple react installed.
