### ISSUE TITLE
Text in dark theme for Menu aren't visible after 2.6.0 update

### ISSUE THREAD

**Issue by pastelsky** [ant-design/ant-design#4440]
After the 2.6.0 update:

<img width="298" alt="screen shot 2017-01-02 at 11 51 10 am" src="https://cloud.githubusercontent.com/assets/8946207/21585204/0ca7d026-d0e2-11e6-81c3-9ce067157415.png">

**Comment by pierre-b** [comment]
+1 same problem here ;)

**Comment by afc163** [comment]
Keep this open until `2.6.1` released.

**Comment by afc163** [comment]
@ddcat1115 发个 2.6.1

**Comment by flyfinec** [comment]
2.6.0版本，dark主题下，黑色字体同时又是黑色背景，识别率差了很多，很难一眼看出

**Comment by afc163** [comment]
@flyfinec 别着急，本周五会发 patch 版本~

**Comment by xuliuzhu1834** [comment]
我用的2.5.3 也是同样的问题

**Comment by afc163** [comment]
`^2.5.3` is not `2.5.3`.
