### ISSUE TITLE
modal 嵌套 select 时，点击select时滚动，会导致选项溢出问题

### ISSUE THREAD

**Issue by laterdayi** [ant-design/ant-design#44400]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-8-4-forked-sk7wrc?file=/demo.tsx)

### Steps to reproduce

modal 嵌套 select 时，点击select时滚动，会导致选项溢出问题

### What is expected?

在modal内部滚动并隐藏

### What is actually happening?

modal 嵌套 select 时，点击select时滚动，会导致选项溢出问题

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | latest |
| System | window |
| Browser | 117 |

**Comment by laterdayi** [comment]
![图片](https://github.com/ant-design/ant-design/assets/122137647/605bd118-b2a2-4d34-aebf-5f5e44ef38b2)

**Comment by zombieJ** [comment]
滚动跟随是故意的。滚动隐藏对于需要核对上下内容的场景会不友善。比如：
一段非常长的描述
一些字段
------------以上在滚动外------------
Label
Select

需要向上滚动：
------------以上在滚动外------------
一段非常长的描述【参考该内容】
一些字段
Label
Select

如果需要滚动清除，可以直接通过 focus 控制哈：

https://codesandbox.io/s/ji-ben-antd-5-8-4-forked-flldl3?file=/demo.tsx

**Comment by laterdayi** [comment]
@zombieJ  感谢你的帮助， 应该如何做更精细的控制， 例如 select  tooltip popover .....
