### ISSUE TITLE
Carousel 同时设置 vertical 、draggable  属性后，左右拖拽才能触发滚动

### ISSUE THREAD

**Issue by Matyman** [ant-design/ant-design#44425]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wei-zhi-antd-5-8-4-forked-lfst5r?file=/demo.tsx)

### Steps to reproduce

左右拖拽才能滑动

### What is expected?

上下拖动滑动

### What is actually happening?

上下拖动无响应，只能左右拖动

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.0.33 |
| System | macOS ventura 13.5 |
| Browser | Google Chrome 115.0.5790.170（正式版本） (arm64) |

**Comment by RedJue** [comment]
Mark
