### ISSUE TITLE
该日期控件在IE9下直接加载不出来，导致页面报错白屏

### ISSUE THREAD

**Issue by LPicker** [ant-design/ant-design#4442]
#### 发生问题的环境是：
在IE9下报错信息：matchMedia not present, legacy browsers require a polyfill。
删除该日期控件，页面可以正常加载。

- antd 版本: 1.6.5
- 操作系统及其版本: Windows 7 专业版 6.1
- 浏览器及其版本: IE9.0.8112.16421

#### 您做了什么？请提供尽可能详细的重现步骤。

import { DatePicker } from 'antd';

<DatePicker
	defaultValue={new Date()}
	showTime={true}
	format="yyyy-MM-dd HH:mm:ss"
	onChange={(value,dateString) => {
		let obj={};
		obj['time']=dateString;
		dispatch(updatePipeDetail(obj));
	}}
/>

#### 您期待的结果是:

 在IE9中正常显示

#### 实际上的结果是:

 报错白屏

#### 可重现的在线演示

无

**Comment by afc163** [comment]
https://ant.design/docs/react/getting-started#Compatibility

https://github.com/weblinc/media-match
