### ISSUE TITLE
Unmounting TreeSelect with treeCheckable prop causes state update on unmounted component

### ISSUE THREAD

**Issue by peter2x** [ant-design/ant-design#44429]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/show-tree-line-antd-5-8-4-forked-2kqy73)

### Steps to reproduce

1. Mount TreeSelect with treeCheckable prop
2. Unmount TreeSelect

### What is expected?

No error

### What is actually happening?

"Can't perform a React state update on an unmounted component" appears in console

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 17.0.2 |
| System | Windows 10 |
| Browser | Chrome 116 |

**Comment by zombieJ** [comment]
Pls upgrade React to latest version. It's not consider a bug any more.  

> ### Notable Changes
> * No warning about setState on unmounted components: Previously, React warned about memory leaks when you call setState on an unmounted component. This warning was added for subscriptions, but people primarily run into it in scenarios where setting state is fine, **and workarounds make the code worse**. We've [remove](https://github.com/facebook/react/pull/22114) this warning.


ref https://github.com/ant-design/ant-design/issues/41572#issuecomment-1491449544
