### ISSUE TITLE
<Table/>  table header glitch when scrolling horizontally

### ISSUE THREAD

**Issue by wving5** [ant-design/ant-design#44426]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-antd-5-8-4-forked-9zpm4t?file=/demo.tsx)

Sry，我不知道这算不算一个 bug。看了一些功能类似的其他 React table  @方案，大部分都有同样的问题。

### Steps to reproduce

1. 为了更容易复现(让症状更明显)，设置 Chrome DevTool  > Performance >  CPU: 6x slowdown
2. 横向滚动表格，在频繁滚动时可以看出，table header 与 table row 有轻微/稍明显的“步调不同步”

现象跟  https://github.com/ant-design/ant-design/issues/26680  描述的比较类似，区别是我这边遇到的比较轻微。

### What is expected?

横向滚动时，table header 跟 table row 同属于一个表格整体，期望滚动时 “步调一致”

### What is actually happening?

横向滚动时，table header 跟 table row “步调不一致”

![table](https://github.com/ant-design/ant-design/assets/12070838/d5817555-4709-4400-85e5-dc789944f874)

Origin Video Capture
https://github.com/ant-design/ant-design/assets/12070838/020ea1e9-4f81-4435-a084-1e0384a98de0

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | MacOS 11.7.7 |
| Browser | Chrome  116.0.5845.96 |

---
Spec: MacBook Pro (16-inch, 2019) , i9-9880H CPU @ 2.30GHz

**Comment by MadCcc** [comment]
因为 header 不是真正的滚动，会有同步的频率和延迟问题。

**Comment by MadCcc** [comment]
虚拟滚动经常会有类似问题存在，暂时不考虑优化。有好的办法的话欢迎 PR
