### ISSUE TITLE
Input.Search 中 Button 比 Input 下边框布局突出半个像素

### ISSUE THREAD

**Issue by xnightsky** [ant-design/ant-design#44427]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn](https://ant-design.antgroup.com/components/input-cn)

### Steps to reproduce

1. 访问官网文档该地址
2. 查看 Input.Search 例子 (搜索框)
3. 如果无法看清楚，唤起 devtools 比对像素即可
4. 默认模式， Input 高度是 31.6px, Button 高度是 32px
5. size="large" 模式下，Input 高度是 39.6px, Button 高度是 40px

### What is expected?

修复

### What is actually happening?

未修复

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | react@18.2.0 |
| System | Windows10 |
| Browser | chrome 116.0.5845.111 |

**Comment by zombieJ** [comment]
看看是不是 window 系统设置缩放了？

<img width="473" alt="截屏2023-08-25 17 06 59" src="https://github.com/ant-design/ant-design/assets/5378891/09b8dcff-b001-4acd-84c5-8709b364880f">
<img width="689" alt="截屏2023-08-25 17 07 17" src="https://github.com/ant-design/ant-design/assets/5378891/04ef2c56-52c4-4fe9-baf4-b37d2bbb909e">

**Comment by xnightsky** [comment]
> 看看是不是 window 系统设置缩放了？
> 
> <img alt="截屏2023-08-25 17 06 59" width="473" src="https://user-images.githubusercontent.com/5378891/263223986-09b8dcff-b001-4acd-84c5-8709b364880f.png"> <img alt="截屏2023-08-25 17 07 17" width="689" src="https://user-images.githubusercontent.com/5378891/263224053-04ef2c56-52c4-4fe9-baf4-b37d2bbb909e.png">

无缩放问题

**Comment by xnightsky** [comment]
![image](https://github.com/ant-design/ant-design/assets/5158235/86237174-3e9b-4575-b157-bd193772184c)
![image](https://github.com/ant-design/ant-design/assets/5158235/60191b96-ae0f-41bc-ba0a-264bfd06678a)

**Comment by xnightsky** [comment]
这一组没问题
![image](https://github.com/ant-design/ant-design/assets/5158235/2b9fd099-2ba9-4ba0-ad1f-4b162138031c)
![image](https://github.com/ant-design/ant-design/assets/5158235/124ea9ba-9d13-48e5-9a16-61768217e99c)
![image](https://github.com/ant-design/ant-design/assets/5158235/521cd292-cd36-4c46-b478-98e303164baf)


来看着这一组
![image](https://github.com/ant-design/ant-design/assets/5158235/8a27cd46-4324-44cc-8095-0acf256e3ca0)
![image](https://github.com/ant-design/ant-design/assets/5158235/5ac1c01d-c664-4742-b5be-33e2b74fbd77)
![image](https://github.com/ant-design/ant-design/assets/5158235/29d91b20-1365-4e52-8a25-4e4dfeee513a)

**Comment by Yuiai01** [comment]
<img width="986" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/b1106199-ad3a-4ad6-a47a-cdb8864d2b88">
<img width="682" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/0f084bd3-4498-42c4-8cda-e4aadb455e69">
我这里好像也没问题

**Comment by wving5** [comment]
https://stackblitz.com/edit/react-vvns3h?file=demo.tsx
<img width="536" alt="image" src="https://github.com/ant-design/ant-design/assets/12070838/c8e4f7b3-cf5d-4827-b1bd-ddf9b019c0f6">

有点意思…虽然我这边高度偏差小到可以忽略不计，但是加上 `allowClear` 之后，偏差就神奇地消失了……

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | MacOS 11.7.7 |
| Browser | Chrome  116.0.5845.96 |

**Comment by wving5** [comment]
> https://stackblitz.com/edit/react-vvns3h?file=demo.tsx <img alt="image" width="536" src="https://user-images.githubusercontent.com/12070838/263394583-c8e4f7b3-cf5d-4827-b1bd-ddf9b019c0f6.png">
> 
> 有点意思…虽然我这边高度偏差小到可以忽略不计，但是加上 `allowClear` 之后，偏差就神奇地消失了……
> 
> Environment	Info
> antd	5.8.4
> React	18.2.0
> System	MacOS 11.7.7
> Browser	Chrome 116.0.5845.96, Safari 14.1.3 (16611.3.10.1.19)

@zombieJ  有时间瞅一眼不， 不知道这个算不算 reproduce ?
