### ISSUE TITLE
Image.PreviewGroup toolbarRender 怎么增加下载图标？

### ISSUE THREAD

**Issue by Design-duke** [ant-design/ant-design#44422]
### Reproduction link

[https://ant-design.antgroup.com/components/image-cn#toolbarrenderinfotype](https://ant-design.antgroup.com/components/image-cn#toolbarrenderinfotype)

### Steps to reproduce

toolbarRender函数怎么实现呀！有没有例子

### What is expected?

就在旁边加一个类似的下载图标，并添加点击事件

### What is actually happening?

添加的图标在工具栏的下方，

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18 |
| System | window |
| Browser | 谷歌 |

**Comment by Yuiai01** [comment]
你可以看看这个例子：https://ant-design.antgroup.com/components/image-cn#image-demo-toolbarrender
