### ISSUE TITLE
table 设置了ellipsis 后鼠标移动到省略的内容上显示会有延迟

### ISSUE THREAD

**Issue by fasnow** [ant-design/ant-design#44435]
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn#components-table-demo-ellipsis](https://ant-design.antgroup.com/components/table-cn#components-table-demo-ellipsis)

### Steps to reproduce

初次移动到单元格内容上时会有延迟才显示省略内容，再次移动到其他单元格上内容出现的就比较快

### What is expected?

如何才能不管是否初次移动到单元格内容都会马上显示省略的内容

### What is actually happening?

初次移动到单元格内容上时会有延迟才显示省略内容，再次移动到其他单元格上内容出现的就比较快

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
这是浏览器的原生功能，antd 做不了什么哈。
