### ISSUE TITLE
Table dataSource array objects cannot have "children" keys

### ISSUE THREAD

**Issue by amritb** [ant-design/ant-design#44434]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/muddy-sea-6y7mq5?file=/src/App.js)

### Steps to reproduce

Pass this simple array into a `<Table />` element's `dataSource`.
```
[
    {
      adults: 2,
      children: 1 // <--- Setting this to 0 fixes the problem
    },
    {
      adults: 3,
      children: 0
    }
]
```

### What is expected?

Normal functionality

### What is actually happening?

TypeError
(data || []).forEach is not a function
flattenData
https://6y7mq5.csb.app/node_modules/antd/es/table/hooks/useSelection.js:40:16
eval
https://6y7mq5.csb.app/node_modules/antd/es/table/hooks/useSelection.js:43:95
flattenData
https://6y7mq5.csb.app/node_modules/antd/es/table/hooks/useSelection.js:40:16
eval
https://6y7mq5.csb.app/node_modules/antd/es/table/hooks/useSelection.js:91:55
updateMemo
https://6y7mq5.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17246:19
Object.useMemo
https://6y7mq5.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17886:16
useMemo
https://6y7mq5.csb.app/node_modules/react/cjs/react.development.js:1650:21
useSelection
https://6y7mq5.csb.app/node_modules/antd/es/table/hooks/useSelection.js:91:48
InternalTable
https://6y7mq5.csb.app/node_modules/antd/es/table/InternalTable.js:188:80
renderWithHooks
https://6y7mq5.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16305:18
....
....

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | react 18.2.0 |
| System | Mac OS |
| Browser | Chrome, Firefox, CodeSandbox, etc. |

**Comment by zombieJ** [comment]
`children` is a key word for tree structure. You can use `childrenColumnName` to replace that : )
