### ISSUE TITLE
为什么不使用 React.memo 来开启 shallowEqual，以及相关操作来优化性能呢？

### ISSUE THREAD

**Issue by liuer147** [ant-design/ant-design#44431]
### What problem does this feature solve?

为什么不使用 React.memo 来开启 shallowEqual，以及相关操作来优化性能呢？

### What does the proposed API look like?

想了解为什么

**Comment by yoyo837** [comment]
请具体点, 哪个位置应该用而没用memo

**Comment by liuer147** [comment]
> 请具体点, 哪个位置应该用而没用memo

额，貌似很多组件，比如 Modal、Form 之类的。

**Comment by yoyo837** [comment]
链到具体的行来看看?

**Comment by liuer147** [comment]
> 链到具体的行来看看?

https://github.com/ant-design/ant-design/blob/4e9ac02b08bb967a588f00cc08809f59cf2b45f9/components/modal/Modal.tsx#L133

有疑惑，好像没有使用 React.memo() 包裹组件，，

**Comment by zombieJ** [comment]
`React.memo` 控制粒度是不够的，内部组件更新需要更精细化的 deps 管理。antd 中大量使用 `useMemo` 做优化：

https://github.com/search?q=repo%3Aant-design%2Fant-design%20useMemo&type=code
https://github.com/search?q=org%3Areact-component+useMemo&type=code

**Comment by zombieJ** [comment]
> 有疑惑，好像没有使用 React.memo() 包裹组件，，

如果只是组件没有全部包，可以看一下 React 的官方文档：https://react.dev/learn/render-and-commit

React 官方并不推荐随意进行过度优化的操作，只有当性能有明显问题是才需要处理。

**Comment by liuer147** [comment]
原来如此

**Comment by liuer147** [comment]
> > > 有疑惑，好像没有使用 React.memo() 包裹组件，，
> > 
> > 
> > 如果只是组件没有全部包，可以看一下 React 的官方文档：https://react.dev/learn/render-and-commit
> > React 官方并不推荐随意进行过度优化的操作，只有当性能有明显问题是才需要处理。
> 
> 可以参考一下这个例子体会一下为什么不应该过度优化： https://codesandbox.io/s/blazing-microservice-xpfm5v?file=/src/App.tsx

get 了，React.memo 针对存在子元素时不会生效。但是，不理解的是，并没有证明 React.memo 有什么坏处？如果这就是过度优化的场景的话，那仅仅只是有/无 React,memo 的话，其效果无区别而已。

**Comment by PuddingJoker** [comment]
> > > 有疑惑，好像没有使用 React.memo() 包裹组件，，
> > 
> > 
> > 如果只是组件没有全部包，可以看一下 React 的官方文档：https://react.dev/learn/render-and-commit
> > React 官方并不推荐随意进行过度优化的操作，只有当性能有明显问题是才需要处理。
> 
> 可以参考一下这个例子体会一下为什么不应该过度优化： https://codesandbox.io/s/blazing-microservice-xpfm5v?file=/src/App.tsx

这个例子是不是想说明 memo 包裹的情况下，也有概率会引起组件重新渲染呢？ 如果是的话，重新渲染，使用memo的性能是不是比不使用memo要差一点点呢，如果使用memo还是重新渲染了，性能也没有差多少的话为什么不用呢？ 就拿这个例子来看的话，如果用户使用我的组件 更多的是传入pure ele的话，它确实能减少重新渲染的次数，为什么不用呢，我想知道一下，另外usememo不是也可以避免重复定义吗 为什么在antd中有很多场景没有直接使用呢

**Comment by PuddingJoker** [comment]
> > > > 有疑惑，好像没有使用 React.memo() 包裹组件，，
> > > 
> > > 
> > > 如果只是组件没有全部包，可以看一下 React 的官方文档：https://react.dev/learn/render-and-commit
> > > React 官方并不推荐随意进行过度优化的操作，只有当性能有明显问题是才需要处理。
> > 
> > 
> > 可以参考一下这个例子体会一下为什么不应该过度优化： https://codesandbox.io/s/blazing-microservice-xpfm5v?file=/src/App.tsx
> 
> 这个例子是不是想说明 memo 包裹的情况下，也有概率会引起组件重新渲染呢？ 如果是的话，重新渲染，使用memo的性能是不是比不使用memo要差一点点呢，如果使用memo还是重新渲染了，性能也没有差多少的话为什么不用呢？ 就拿这个例子来看的话，如果用户使用我的组件 更多的是传入pure ele的话，它确实能减少重新渲染的次数，为什么不用呢，我想知道一下，另外usememo不是也可以避免重复定义吗 为什么在antd中有很多场景没有直接使用呢
@zombieJ @yoyo837

**Comment by yoyo837** [comment]
memo 包裹下并不是100%比不包裹性能好，memo 里需要执行的比较某些情况下或许会比直接自面量产生新值更慢。

**Comment by PuddingJoker** [comment]
> memo 包裹下并不是100%比不包裹性能好，memo 里需要执行的比较某些情况下或许会比直接字面量产生新值更慢。

如果用户使用我的组件 更多的是传入pure ele的话，它确实能减少重新渲染的次数，为什么不用呢，我想知道一下，另外usememo不是也可以避免重复定义吗 为什么在antd中有很多场景没有直接使用呢

**Comment by yoyo837** [comment]
> > memo 包裹下并不是100%比不包裹性能好，memo 里需要执行的比较某些情况下或许会比直接字面量产生新值更慢。
> 
> 如果用户使用我的组件 更多的是传入pure ele的话，它确实能减少重新渲染的次数，为什么不用呢，我想知道一下，另外usememo不是也可以避免重复定义吗 减小重复定义消耗的性能提升大不大呢

就是上面那个回答
