### ISSUE TITLE
Ant cssinjs causes the NextJS app broken in production mode

### ISSUE THREAD

**Issue by camcam2605** [ant-design/ant-design#44433]
### Reproduction link

[https://github.com/ant-design/ant-design-examples/tree/main/examples/with-nextjs-app-router-inline-style](https://github.com/ant-design/ant-design-examples/tree/main/examples/with-nextjs-app-router-inline-style)

### Steps to reproduce

1. Clone repo from the official examples: https://github.com/ant-design/ant-design-examples/tree/main/examples/with-nextjs-app-router-inline-style.
2. Run `npm i` to install dependencies. 
3. Add Link component redirect to home page in root page.tsx (app/page.tsx): 
```
  import Link from 'next/link';
  
  <Link href="/">Go Home</Link>
```
4. Run `npm run build` and `npm run start`.
5. Go to localhost:3000
6. Press to the link "Go Home"

### What is expected?

NextJS app should not broken

### What is actually happening?

NextJS app broken and throw the error in console: TypeError: Cannot read properties of null (reading '1')

See:
![image](https://github.com/ant-design/ant-design/assets/67684008/78871d65-b867-41da-8fdf-d56bf969b515)

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | React 18 |
| System | Windows |
| Browser | Chrome |

---
I checked and ensuring that the cause comes from the cssinjs package because when I trying to remove the StyleProvider component and re-build then the nextjs app works fine and vice versa.
It is similar to this issue but occurs in production mode: https://github.com/ant-design/ant-design/issues/43510#issuecomment-1646456317

**Comment by zombieJ** [comment]
Checked. `useMemo` some time will skip if component fast remove and mount back:

```tsx
const Demo = () => {
  React.useMemo(() => {
    console.log('demo memo');
  }, []);
};

render(<Demo />); // print `demo memo`
rerender(<div />);
rerender(<Demo />); // not print anything
```

**Comment by zombieJ** [comment]
@camcam2605 updated. pls check

**Comment by Belen-Luo** [comment]
请问这个问题在antd 的那个版本中

**Comment by Belen-Luo** [comment]
May I ask which version of this problem has been updated? It has been updated to @ant-design/cssinjs 1.17.2, but it still cannot be solved.
