### ISSUE TITLE
Uncaught TypeError: (0 , _Toolbar.createToolbar) is not a function

### ISSUE THREAD

**Issue by sebastiandeutsch** [ant-design/ant-design#4443]
I have a problem when deploying antd in production. I'll get a js error

```
index.js:55 Uncaught TypeError: (0 , _Toolbar.createToolbar) is not a function
````

the error comes from `import { Menu, Icon, Switch } from 'antd';`

I think it's in Mention - any way to workaround? Annoying fact - running the same script with webpack dev server works fine.

**Comment by benjycui** [comment]
Try `babel-plugin-import`.

**Comment by sebastiandeutsch** [comment]
That did the trick. I needed to include the plugin for production as well. Thanks.

**Comment by benjycui** [comment]
@sebastiandeutsch actually, it's the recommended way to use antd..
