### ISSUE TITLE
Support `Transfer[onSearchChange]`

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4444]
`Transfer[onSearchChange]` will be triggered while user input in search box.

**Comment by RaoHai** [comment]
https://github.com/ant-design/ant-design/pull/4449/files#diff-2f01482d3d81c8381efe77de06340c5eR220 这样？

**Comment by afc163** [comment]
`filterOption` could be the same in this situation.

```
filterOption={(inputValue) => { this.onSearchChange(inputValue); return true } }
```

**Comment by shaozj** [comment]
@afc163 , 如果我想后端搜索，你这样的话如果左侧有100条数据，那一下子给后端发送100条请求了。

**Comment by shaozj** [comment]
我有这样一种场景。左侧是服务端搜索，所以前端的搜索 filterOption 回调中都返回 true了，而右侧希望还是能前端搜索。请问如何获取当前的搜索是左侧还是右侧搜索？

**Comment by shaozj** [comment]
我建议针对左侧框搜索为服务端搜索的情况好好设计下，主要考虑一下几点：
1、此时禁止掉前端搜索
2、搜索结果需要和之前右侧框中的数据合并，不然会出错
3、区分左侧搜索和右侧搜索，因为右侧希望仍然是前端搜索

**Comment by afc163** [comment]
@shaozj 你说的对，filterOption 确实不适合。还是需要 @RaoHai 提交的那个 onSearchChange，你可以进去 review 一下，看看是否满足你的需求。
