### ISSUE TITLE
Default import for 'input' and 'textarea' not functioning properly within a form, specifically in relation to error border

### ISSUE THREAD

**Issue by Rey-Wang** [ant-design/ant-design#44446]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-13-forked-rmvm3w?file=/demo.tsx)

### Steps to reproduce

import default Input or Textarea from `antd/lib/Input` or `antd/lib/Input/Textarea`

### What is expected?

error style working properly

### What is actually happening?

No red border-color

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.0.0 |
| System | Macos monterey 12.4 |
| Browser | Microsoft edge 116.0.1938.54 |

**Comment by afc163** [comment]
Please use `Input.TextArea` always.
