### ISSUE TITLE
Grid 栅格 响应式如何根据容器大小而不是屏幕大小？

### ISSUE THREAD

**Issue by LengYXin** [ant-design/ant-design#44455]
### What problem does this feature solve?

Grid 栅格 响应式如何根据容器大小而不是屏幕大小

### What does the proposed API look like?

Grid 栅格 响应式如何根据容器大小而不是屏幕大小

**Comment by afc163** [comment]
现在并不支持。

**Comment by LengYXin** [comment]
> 现在并不支持。

有支持计划或者什么好的替代方案么？
