### ISSUE TITLE
Carousel Issue - 

### ISSUE THREAD

**Issue by DivyanshChaudhary17** [ant-design/ant-design#44459]
### Reproduction link

[https://ant.design/components/carousel](https://ant.design/components/carousel)

### Steps to reproduce

use the react - 18.2.0 and antd - 5.8.4 in react with the mentioned code below and you will see warning in browser console

 <Carousel
        responsive={[
          {
            breakpoint: mediaSizes.mobileM,
            settings: { slidesToShow: 1 },
          },
          {
            breakpoint: mediaSizes.mobileL,
            settings: { slidesToShow: 2 },
          },
          {
            breakpoint: mediaSizes.tabletL,
            settings: { slidesToShow: 3 },
          },
          {
            breakpoint: mediaSizes.desktopL,
            settings: { slidesToShow: 4 },
          },
        ]}
        arrows={true}
        dots={false}
        nextArrow={<RightOutlined />}
        prevArrow={<LeftOutlined />}
      >
        {[1, 2, 3, 4, 5, 6, 7, 8].map((_, index) => (
          <div key={index} className="carousel-slide-item">
            
          </div>
        ))}
      </Carousel>

### What is expected?

slideCount prop should be passed in smallcase 

### What is actually happening?

in the browser console, I see this warning

react-dom.development.js:86 Warning: React does not recognize the `slideCount` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `slidecount` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at span
    at http://localhost:3000/static/js/bundle.js:6865:25
    at LeftOutlined
    at PrevArrow (http://localhost:3000/static/js/bundle.js:8215:90)
    at div
    at InnerSlider (http://localhost:3000/static/js/bundle.js:8637:90)
    at Slider (http://localhost:3000/static/js/bundle.js:9345:90)
    at div
    at http://localhost:3000/static/js/bundle.js:24881:7
    at div
    at O (http://localhost:3000/static/js/bundle.js:119415:6)
    at div (http://localhost:3000/static/js/bundle.js:675:3)

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | mac air m1 |
| Browser | Chrome Version 116.0.5845.110 (Official Build) (arm64) |

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/issues/1195#issuecomment-390383615
