### ISSUE TITLE
【Input】输入框最后一个字显示不全

### ISSUE THREAD

**Issue by zbw-zbw** [ant-design/ant-design#44458]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-yi-chu-tu-biao-antd-5-8-4-forked-scxpcj?file=/demo.tsx)

### Steps to reproduce

输入框输入内容超出最大宽度后，输入任意一个中文字符会展示不全（如输入 c 然后回车选中“测“字，如果直接输入ce 就不会出现，估计是中英文字符占位不同导致）
![image](https://github.com/ant-design/ant-design/assets/64134946/3f6a7d4c-0840-4cc5-ab64-771de687640a)
![image](https://github.com/ant-design/ant-design/assets/64134946/bf0ba909-f4b4-47ed-b9a5-0f0c44802cc7)

### What is expected?

输入内容能全部展示

### What is actually happening?

最后一个字展示不全

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
@zbw-zbw 试试原生 input 会不会出现这个问题。

**Comment by Wxh16144** [comment]
如此刁钻的问题🤔

**Comment by zbw-zbw** [comment]
> 

刚试过了 原生 input 也会有这个问题 🤔

**Comment by zbw-zbw** [comment]
> 如此刁钻的问题🤔

我也是早上自测业务功能的时候突然发现的 😊

**Comment by zbw-zbw** [comment]
我项目里用的就是原生 input 然后发现这个问题的 然后我就顺势来看了下你们有没有发现且解决了这个问题，想参考下方案，然后发现也没有解决哈哈哈哈 所以提了这个 issue 讨论下😂

**Comment by afc163** [comment]
如果原生 input 也有这个问题的话，应该属于浏览器实现机制的层面，antd 这边也做不了太多东西。
