### ISSUE TITLE
modal 关闭 立刻销毁此modal 问题

### ISSUE THREAD

**Issue by hnsylitao** [ant-design/ant-design#4445]
#### 发生问题的环境是：

- antd 版本:2.6.0
- 操作系统及其版本:mac
- 浏览器及其版本:google chrome

#### 您做了什么？请提供尽可能详细的重现步骤。

引用 modal

modal 打开 之后 关闭 操作

立刻销毁此 modal 

例如说我关闭modal 立即进行 router 跳转

body 上的 style overflow: hidden;

#### 您期待的结果是:

我希望 关闭 后 modal 不需要等待 300 毫秒 在 进行 body style 处理

**Comment by hnsylitao** [comment]
我现在的解决方法时 modal 关闭后 是等待 300 毫秒 在进行 路由跳转

**Comment by RaoHai** [comment]
Modal 有个动画结束的回调的。。

```jsx
<Modal afterClose={() => doRedirect()} />
```

**Comment by afc163** [comment]
感觉楼主措辞上用了谷歌翻译。。

**Comment by hnsylitao** [comment]
@RaoHai 谢谢，为什么在官方文档上面没有指出

**Comment by afc163** [comment]
@hnsylitao 注意上面的 PR
