### ISSUE TITLE
UploadFileStatus 有个success状态，但是源码里没观察到文件状态为success的相关代码

### ISSUE THREAD

**Issue by Ivan-hl** [ant-design/ant-design#44467]
### What problem does this feature solve?

UploadFileStatus 有个success状态，但是源码里没观察到文件状态为success的相关代码，请问什么情况下file的status为success?

### What does the proposed API look like?

UploadFileStatus 有个success状态，但是源码里没观察到文件状态为success的相关代码，请问什么情况下file的status为success?

**Comment by zombieJ** [comment]
服务器返回的：

https://ant-design.antgroup.com/components/upload-cn#onchange

<img width="630" alt="截屏2023-08-28 17 27 47" src="https://github.com/ant-design/ant-design/assets/5378891/6db4b21d-62f9-40bc-91a8-1ffb807b468b">

**Comment by zombieJ** [comment]
发现说的是 UploadFileStatus 类型定义，这个应该是写错了。多写了一个。
