### ISSUE TITLE
你好，现在有个需求需要在upload组件基础上实现点击上传按钮弹出文件库列表

### ISSUE THREAD

**Issue by 957651480** [ant-design/ant-design#44462]
### What problem does this feature solve?

现在有个需求需要在upload组件基础上实现点击上传按钮弹出文件库列表，upload 组件虽然有openFileDialogOnClick属性，但没有onClick 事件，请问有别的方式更好的实现吗，虽然我可以在upload 里包个div 绑onclick事件，但有可能会影响到样式 

### What does the proposed API look like?

希望upload 有click事件

**Comment by Wxh16144** [comment]
> 虽然我可以在upload 里包个div 绑onclick事件，但有可能会影响到样式

为什么会影响样式呢？

**Comment by solitia7125** [comment]
如果只是要有onclick时间，在外面再包一层div不行吗

**Comment by afc163** [comment]
onClick 直接放 Button 上就行了吧？https://codesandbox.io/s/vvvn4g?file=/demo.tsx
