### ISSUE TITLE
当 Select 处于 activeElement 时，提供一个方法可以禁用按键打开下拉菜单

### ISSUE THREAD

**Issue by tianjunnew** [ant-design/ant-design#44465]
### What problem does this feature solve?

按下除空格外的按键能打开下拉菜单有点奇怪。目前似乎没有方法能阻止这个行为。

### What does the proposed API look like?

SelectProps.preventKeydownFromOpenDropdown

**Comment by zombieJ** [comment]
HOC 一下即可：

https://codesandbox.io/s/ji-ben-shi-yong-antd-5-8-4-forked-scd4tq?file=/demo.tsx
