### ISSUE TITLE
Tiny size classes

### ISSUE THREAD

**Issue by boskiv** [ant-design/ant-design#44469]
### What problem does this feature solve?

I want to get a table and buttons that are more compact than small. Can I configure it via ConfigProvider for example?
For a more general approach, I prefer to have 'tiny' size options in components like tables, buttons, tabs, and so on.

### What does the proposed API look like?

size="tiny"

**Comment by zombieJ** [comment]
You can try `compact` theme:
<img width="215" alt="截屏2023-08-28 17 49 37" src="https://github.com/ant-design/ant-design/assets/5378891/5a047d4e-68a6-4b19-a5a6-5f39b76f36f4">

### Default algorithm

<img width="359" alt="截屏2023-08-28 17 49 10" src="https://github.com/ant-design/ant-design/assets/5378891/cf9f7801-d953-45fa-a378-c9007df1c3ec">

### Compact algorithm

<img width="318" alt="截屏2023-08-28 17 49 46" src="https://github.com/ant-design/ant-design/assets/5378891/347e9f7a-6d8e-470f-974d-92524fba4e9e">

### Doc

https://ant.design/docs/react/customize-theme#algorithm

**Comment by zombieJ** [comment]
PS: if you think compact algorithm is still large, you can create a customize algorithm to get it smaller : )

**Comment by zombieJ** [comment]
Algorithm ref: https://github.com/ant-design/ant-design/blob/master/components/theme/themes/compact/index.ts
