### ISSUE TITLE
A draggable and resizable grid layout with responsive breakpoints

### ISSUE THREAD

**Issue by boskiv** [ant-design/ant-design#44470]
### What problem does this feature solve?

I want to archive https://github.com/react-grid-layout/react-grid-layout behavior with AntDesing components. Is it possible?

### What does the proposed API look like?

Option to make a grid draggable and resizable grid

**Comment by afc163** [comment]
Check https://ant.design/components/grid

**Comment by boskiv** [comment]
But there is no drag and drop behaviour? It's just a layout
