### ISSUE TITLE
DatePicker multiple date selection?

### ISSUE THREAD

**Issue by zhump** [ant-design/ant-design#4447]
现在业务场景，需要选择多个日期，进行提交处理，希望可以在一个日期面板中直观的操作完成，希望可以支持一下，多谢。

**Comment by afc163** [comment]
- http://arca-computing.github.io/MultipleDatePicker/
- http://multidatespickr.sourceforge.net/

**Comment by hengkx** [comment]
最近也遇到这个需求，有人在处理 这个 需求吗？
没人 的 话 我来 尝试下

**Comment by zhump** [comment]
@hengkx 加油

**Comment by hengkx** [comment]
预览地址 [https://deploy-preview-420--rc-calendar.netlify.com/examples/antd-multiple-calendar.html](https://deploy-preview-420--rc-calendar.netlify.com/examples/antd-multiple-calendar.html) 
因为在基础库里面 所以没有调整 UI

**Comment by hengkx** [comment]
@afc163 麻烦有时间，看一下，这个问题 还打算处理吗，thanks

**Comment by afc163** [comment]
@hengkx 只要还 open 就会做的，别着急。

**Comment by hengkx** [comment]
@afc163 我提交了 PR 看一下，现在有业务 要使用，https://github.com/react-component/calendar/pull/420

**Comment by afc163** [comment]
着急的话建议先 FORK 自行发布，这种重大特性不会那么快。

**Comment by jszjgqq** [comment]
> 最近也遇到这个需求，有人在处理 这个 需求吗？
> 没人 的 话 我来 尝试下

https://codesandbox.io/s/92xkz86y0r

为了保证风格以及组件的一致性，基于Antd中的 DatePicker组件自己实现了下，代码没优化，只是个Demo，有需要的可参考。

**Comment by aqnaruto** [comment]
@afc163 
https://codesandbox.io/s/riqiduoxuan-3oi1r?fontsize=14&hidenavigation=1&theme=dark
我想了一下这个功能，楼上的实现对现有的代码具有侵入性，其实现有组件的 dateRender 可以轻易的实现多选。连接是列子
另：
建议 输入框的value 代码不要写死，不要和选择弹出框日历值绑定，可由用户自定义。这样可做的事情会更多
在本例中，我只能用format这个属性来修改input框里的内容。算是不完美的地方吧。

**Comment by muzea** [comment]
![image](https://user-images.githubusercontent.com/7843281/71960270-8be34300-322f-11ea-98b0-f3d02e814300.png)

挺好的，是我想要的亚子。

就是失焦和清除的处理有点问题。

**Comment by aqnaruto** [comment]
> ![image](https://user-images.githubusercontent.com/7843281/71960270-8be34300-322f-11ea-98b0-f3d02e814300.png)
> 
> 挺好的，是我想要的亚子。
> 
> 就是失焦和清除的处理有点问题。

我写的那个吗？没有问题啊，我写的怎么会有问题。如果你要value绑定 在清除的时候onchange 是null的时候 进行操作就行了。

**Comment by lucasleelz** [comment]
> ```js-jsx
> multiple
> ```

都几年啦~ 还没精力嘛。

**Comment by XinYueXiao** [comment]
你们实现了吗,上面链接失效了,有效的那个不是多选

**Comment by XinYueXiao** [comment]
> ![image](https://user-images.githubusercontent.com/7843281/71960270-8be34300-322f-11ea-98b0-f3d02e814300.png)
> 
> 挺好的，是我想要的亚子。
> 
> 就是失焦和清除的处理有点问题。

你是怎么实现的

**Comment by XinYueXiao** [comment]
> https://deploy-preview-420--rc-calendar.netlify.com/examples/antd-multiple-calendar.html

你好,这个链接404 了

**Comment by phi0411141** [comment]
I will leave a code example if anyone need a temporary solution when waiting for the merge.
https://codesandbox.io/s/hungry-chandrasekhar-t8e69
PS: the sandbox wont run, I just paste the code without install any dependencies. But you get the idea.

**Comment by YukiYlf** [comment]
![image](https://user-images.githubusercontent.com/55609473/88470739-d067cf00-cf32-11ea-9760-fd9a0837ab4b.png)

**Comment by phi0411141** [comment]
@YukiYlf as I already said above in PS, just give you the idea. The js code is working fine, but for dependencies and props like onChange, value,... you need to pass by yourself. Look like you guy are getting confused about it, so I import dependencies to make it a runnable example
https://codesandbox.io/s/hungry-chandrasekhar-t8e69

**Comment by huangpfly** [comment]
> @afc163
> https://codesandbox.io/s/riqiduoxuan-3oi1r?fontsize=14&hidenavigation=1&theme=dark
> 我想了一下这个功能，楼上的实现对现有的代码具有侵入性，其实现有组件的 dateRender 可以轻易的实现多选。链接上是列子
> 另：
> 建议 输入框的value 代码不要写死，不要和选择弹出框日历值绑定，可由用户自定义。这样可做的事情会更多
> 在本例中，我只能用format这个属性来修改input框里的内容。算是不完美的地方吧。
> ps:求内推

你好，antd 4.0版本  这个已经不能用了

**Comment by hhwangS27** [comment]
坐等大佬们实现呀

**Comment by AllenChinese** [comment]
> > ![image](https://user-images.githubusercontent.com/7843281/71960270-8be34300-322f-11ea-98b0-f3d02e814300.png)
> > 挺好的，是我想要的亚子。
> > 就是失焦和清除的处理有点问题。
> 
> 我写的那个吗？没有问题啊，我写的怎么会有问题。如果你要value绑定 在清除的时候onchange 是null的时候 进行操作就行了。

你好，请问一下我设置 initValue，但日期的回显没成功，如何传 initValue

**Comment by mini0609** [comment]
利用select和datePicker实现了
https://codesandbox.io/s/antd-reproduction-template-forked-1mos9?file=/index.js

![image](https://user-images.githubusercontent.com/66118165/109460705-f8f11200-7a9b-11eb-80b0-f520019b66da.png)

**Comment by theprimone** [comment]
有点久远了啊，还没人搞定吗？希望 Calendar 能够支持多选，现在定位到 [rc-picker/PanelBody.tsx](https://github.com/react-component/picker/blob/master/src/panels/PanelBody.tsx)，争取近期把这个问题搞定。

另外看了楼上基于 react-component/calendar 修改的，找半天好像现在 antd 都没用这个组件了 🤨

**Comment by theprimone** [comment]
好像有点复杂 😂

**Comment by muyoulongjingcha** [comment]
这个需求我们也遇到了，我们利用input框和datepicker自定义单元格功能实现了，点击过的日期存入数组，然后这些日期的单元格给一个背景色就可以；点击过的日期再点击就清除。挺简单的。

**Comment by eternallycyf** [comment]
<img width="555" alt="截屏2021-11-20 下午5 25 50" src="https://user-images.githubusercontent.com/63464198/142721303-06c9c76b-4f10-4dbe-ae29-6a14ac991d1d.png">

按照楼上的select 版本, 做了个简易版
注意的是  DatePicker 的 onchange 事件 取消时触发有问题 
需要加 value={''}
## js
```js
import React, { useState } from "react";
import { DatePicker, Button } from "antd";
import moment from "moment";
import styles from './index.less';

const MultipleDatePicker = () => {
  // 选中的日期 timestamp[]
  const [selectedDate, setSelectedDate] = useState([])

  // 日期发生变化时 重复去重 没有则添加
  const onValueChange = (date) => {
    const newDate = moment(date).startOf("day").valueOf()
    if (selectedDate.includes(newDate)) {
      setSelectedDate([...selectedDate.filter(item => item !== newDate)])
    } else {
      setSelectedDate([...selectedDate, newDate])
    }
  };

  // 渲染选中日期外观
  const dateRender = (currentDate) => {
    const isSelected = selectedDate.includes(moment(currentDate).startOf("day").valueOf())
    let selectStyle = isSelected ?
      {
        position: 'relative',
        zIndex: 2,
        display: 'inlineBlock',
        width: "24px",
        height: "22px",
        lineHeight: "22px",
        backgroundColor: "#1890ff",
        color: "#fff",
        margin: "auto",
        borderRadius: "2px",
        transition: "background 0.3s, border 0.3s"
      }
      : {}
    return (<div style={selectStyle} > {currentDate.date()}  </div >)
  }

  return (
    <>
      <div className={styles.multipleDatePicker}>
        <DatePicker
          open
          dateRender={dateRender}
          onChange={onValueChange}
          showToday={false}
          value={""}
        />
        <Button type='primary' onClick={() => console.log(selectedDate)}>确定</Button>
      </div>
    </>
  )
}
export default MultipleDatePicker
```js
## css
```css
.multipleDatePicker {
  :global {
    .ant-picker-input {
      display: none !important;
    }
    .ant-picker {
      border: none;
      padding: 0;
    }
  }
}
```

**Comment by fantasy525** [comment]
2022了官方还没实现吗

**Comment by undefined9999** [comment]
马上2023年了, 官方还不考虑实现么

**Comment by ldwonday** [comment]
马上2023年了, 官方还不考虑实现么

**Comment by taosiqi** [comment]
2023年了, 官方还不考虑实现么

**Comment by limuen** [comment]
实现吧

**Comment by 12345ZMTHL** [comment]
打个卡，2023-03-30还是没处理

**Comment by CN-Qin** [comment]
2023-05-09, 还没实现嘛

**Comment by jackeyzhou9** [comment]
2023-05-11 还没有实现。。

**Comment by FrankXiong** [comment]
2023-05-22 实现了吗

**Comment by zgsgs** [comment]
2023-06-20 实现了吗

**Comment by daydayupon** [comment]
什么时候能实现啊

**Comment by Inston77** [comment]
官方催更

**Comment by zzzeke** [comment]
求实现！！

**Comment by yzi-yzi** [comment]
Waiting for this feature, any news?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
