### ISSUE TITLE
ColorPicker 颜色选择器，增加 defaultFormat 属性

### ISSUE THREAD

**Issue by CYBYOB** [ant-design/ant-design#44477]
### What problem does this feature solve?

用户能够设置默认的 format 属性值

### What does the proposed API look like?

ColorPicker 颜色选择器，增加 defaultFormat 属性

**Comment by CYBYOB** [comment]
[PR](https://github.com/ant-design/ant-design/pull/44478)

**Comment by yoyo837** [comment]
Close by #44487
