### ISSUE TITLE
Layout Responsive Header does not revert back 

### ISSUE THREAD

**Issue by bigbean17** [ant-design/ant-design#44483]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/header-sider-2-antd-5-8-5-forked-hgzf3n?file=/demo.tsx)

### Steps to reproduce

1. Wait the page to be rendered in a large screen (md at least)
2. shrink the page to xs or smaller
3.  expand the page to lg or larger

### What is expected?

1. When shrink, there should be 3 dots or menu icon to make the header elements responsive
2. When expand, the 3 dots should be gone

### What is actually happening?

 When expand, the 3 dots didn't go away but have to refresh the page

### Related link
https://github.com/ant-design/ant-design/pull/36604
Adding `<Menu style={{ minWidth: 0, flex: "auto" }} />` and `display: 'flex'` to parent (Col) does not solve the problem 

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/header-sider-2-antd-5-8-5-forked-chv8qj?file=/demo.tsx:463-472

**Comment by MadCcc** [comment]
Add `width: 100%` to Row
