### ISSUE TITLE
在nextjs 13.4.19中, ConfigProvider locale={zhCN} 并没有生效。

### ISSUE THREAD

**Issue by luozyiii** [ant-design/ant-design#44480]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/determined-moore-6rpg3c?file=/app/demo.tsx:4,41)

### Steps to reproduce

点击日期,弹窗出现了英文，demo 可复现。

### What is expected?

期待有一个解决方案

### What is actually happening?

出现了英文

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18.2 |
| System | nextjs 13.4.19 |
| Browser | chrome |

**Comment by MadCcc** [comment]
参考 https://ant.design/components/config-provider-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96-locale-%E8%AE%BE%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88
