### ISSUE TITLE
Form scrollToFirstError does not work with Rate

### ISSUE THREAD

**Issue by andyho-st** [ant-design/ant-design#44484]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/scroll-to-first-error-not-working-with-rate-mmv7f5)

### Steps to reproduce

Click submit button, no scroll action will happen.

### What is expected?

It should scroll to form item Rate when its empty.

### What is actually happening?

Put Rate in one of the Form item with rules required true, will make scrollToFirstError stop working.
Remove Rate required rule, scrollToFirstError will work again.

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.0 |
| System | debian 11 |
| Browser | chrome 115.0.5790.170  |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/rate/releases/tag/v2.9.3

https://codesandbox.io/s/scroll-to-first-error-not-working-with-rate-forked-6tsff3?file=/package.json
