### ISSUE TITLE
TreeSelect dropdown key selection design fix 

### ISSUE THREAD

**Issue by cristoferrao** [ant-design/ant-design#44492]
### What problem does this feature solve?

hi, the treeselect dropdown when opened then use down arrow to navigate the selection does not look good some is hidden like top border of outline and fix padding is possible   

### What does the proposed API look like?

first out outline should not be seen and just change the background of the focused option something like that thank you

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/335f3645-8e78-4a40-abb7-78ec4cc17852)
Style issue

**Comment by ohhoney1** [comment]
@MadCcc   How about changing it to look like the  `Option` style in `Select`，i can submit a pr

**Comment by yoyo837** [comment]
Ref: https://github.com/react-component/tree/pull/766

**Comment by dfblhmm** [comment]
> ![image](https://private-user-images.githubusercontent.com/27722486/263913088-335f3645-8e78-4a40-abb7-78ec4cc17852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzQ5OTksIm5iZiI6MTcwMjI3NDY5OSwicGF0aCI6Ii8yNzcyMjQ4Ni8yNjM5MTMwODgtMzM1ZjM2NDUtOGU3OC00YTQwLWFiYjctNzhlYzRjYzE3ODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA2MDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMDhhNzU3YzBkZDZhMWNhZjdhMmUzYzIwNTVjOTlkMzYyMGM0ZjFmYzU5NWI1OTQ1ZGVmZGVmNGUxNmI1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TKm2D4KenIBaV-VxOoF0zX8njFORegmE6WjiNJljjYg) Style issue

通过覆盖样式可以解决，貌似是因为加了 `outline` 样式
```css
.ant-tree-select-dropdown .ant-select-tree .ant-select-tree-treenode-active .ant-select-tree-node-content-wrapper {
  outline: none !important;
}
```
