### ISSUE TITLE
Custom menu icon not position in center when sidebar is collapsed

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44498]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/collapsed-inline-menu-antd-5-8-5-forked-st9q8m?file=/demo.tsx)

### Steps to reproduce

create a menu with a list of items and with custom icons of some custom sizes 

### What is expected?

the icon should aligned center regardless of sizes when sidebar collapses

### What is actually happening?

icon alignment is incorrect

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
https://github.com/ant-design/ant-design/assets/52765572/be4ef209-ef44-40ef-bde1-e4bcc1564d2d

**Comment by fcs-kazuki-furukawa** [comment]
@AsuraKev 
What is the solution to this phenomenon?

**Comment by AsuraKev** [comment]
> @AsuraKev
> What is the solution to this phenomenon?

I just apply custom style to the element so that it looks correct. The antd menu custom icon doesn’t seem to allow large icon therefore I have to apply styling to it

**Comment by ryanpratama14** [comment]
Can you share the custom style?

**Comment by Berd74** [comment]
I added custom style by wrapping my icon with a div that has marginLeft: -7px
the amount of margin depends of your icon size
e.g.:

 {key: '/docs', icon: <div style={{marginLeft: -7}}><i className='icon-book'/></div>, label: 'Docs'},
