### ISSUE TITLE
4.x版本 Form 校验时recursive可用但是ts类型不足，是否可以直接使用，有什么隐藏风险？

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#44506]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-fang-fa-diao-yong-antd-4-24-13-forked-8vh9f6?file=/demo.tsx)

### Steps to reproduce

左侧recursive报错

### What is expected?

不报错

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by MadCcc** [comment]
没有在文档里提供的都是不稳定的 api，可能会有 breaking change

**Comment by DY-ZYQ** [comment]
那如果想实现校验只校验form.list里面的表单如何实现？

**Comment by MadCcc** [comment]
v4 不保证稳定性，在 v5 会持续维护。
