### ISSUE TITLE
可能在 tsx 文件中使用 theme 中的任意变量吗？

### ISSUE THREAD

**Issue by daoyi7** [ant-design/ant-design#44508]
### What problem does this feature solve?

某个特定文案也想用 theme 里的 color

### What does the proposed API look like?

类似`theme.colorError`

```html
<span style={{color: theme.colorError}}>antd</span>
```

**Comment by Wxh16144** [comment]
静态消费可以看看这个文档： https://ant.design/docs/react/customize-theme-cn#%E9%9D%99%E6%80%81%E6%B6%88%E8%B4%B9%E5%A6%82-less

如果是组件中，可以用 theme 提供的 useToken hook

**Comment by afc163** [comment]
@daoyi7 不要用 babel-plugin-import

**Comment by FruitJ** [comment]
但是去掉这个 plugin，webpack 就不会 tree shaking antd 了，所有的组件全都打包进去了，这个怎么解呢？

**Comment by afc163** [comment]
@FruitJ antd 支持 TreeShaking，正常的构建工具会处理的。
