### ISSUE TITLE
访问网站时 document.title 会跳一下

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#44514]
https://github.com/ant-design/ant-design/assets/507615/47b875ad-b2c5-49ee-9d93-fd146b9b1b02

**Comment by zombieJ** [comment]
看起来中间跳了一下 `Ant Design` 又跳了回来。

**Comment by afc163** [comment]
是跳到 undefined 了。

<img width="296" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/80ad5b23-3544-4fbc-8b07-6f7ef278b369">

**Comment by xiaozisong** [comment]
> 是跳到 undefined 了。

https://github.com/ant-design/ant-design/assets/67359137/13ffc6ba-d1cb-477f-85e1-162ad0a60476


> 
> <img alt="图片" width="296" src="https://user-images.githubusercontent.com/507615/264007928-80ad5b23-3544-4fbc-8b07-6f7ef278b369.png">

首次访问页面时会有这个问题，但是线上的没有报出url，只是会跳出Ant Design
