### ISSUE TITLE
layout组件嵌套 刷新会导致页面闪屏 

### ISSUE THREAD

**Issue by dr-forget** [ant-design/ant-design#44518]
### Reproduction link

[https://github.com/dr-forget/react-antd-bug.git](https://github.com/dr-forget/react-antd-bug.git)

### Steps to reproduce

npm run dev 运行项目 然后刷新浏览器即可  即可复现闪屏

### What is expected?

恢复正常  不闪屏 样式不错乱

### What is actually happening?

样式错乱 刷新会造成闪屏的效果

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.2.0 |
| System | macos13.4.1 |
| Browser | chrome 116.0.5845.110 |

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/bb24efa1-78e2-43ff-95bb-b68cb979ab3c)
确实有一帧布局乱了

**Comment by afc163** [comment]
需要 hasSider 吧？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/42487
https://github.com/ant-design/ant-design/issues/42576

**Comment by dr-forget** [comment]
![image](https://github.com/ant-design/ant-design/assets/136982352/89e7a64e-2a8c-42b0-a4b6-59a5b6d80e3e)
文档上标注服务端渲染才使用 一般不用指定 所以就没指定 加上hasSider 的确解决了问题

**Comment by poyiding** [comment]
> 需要 hasSider 吧？

按文档说明，一般用户不会加上hasSider，这个是不是应该加默认更好？
