### ISSUE TITLE
Replace typescript-babel-jest with ts-jest

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#4451]
Discussions https://github.com/ant-design/ant-design/issues/4208#issuecomment-266651245

**Comment by yesmeck** [comment]
用 ts-jest 后就不能用把 TypeScript 先编译到 ES6 后再用 Babel 做转换了，这样就需要把 `target` 设为 `ES5`，但是因为 `"allowSyntheticDefaultImports": true` 的缘故，`import React from 'react'` 会被编译成 `var react_1  = requrie('react').default` 导致 `react_1` 是  undefined。

**Comment by infeng** [comment]
使用 `allowSyntheticDefaultImports": true` 只是为了跟引用类似 `moment` 这样的包统一，感觉可以去掉

**Comment by yesmeck** [comment]
看了提交记录这个确实是引入 `moment` 的时候设置的，`moment` 必须要这个设置？ @benjycui

**Comment by afc163** [comment]
`import React from 'react'` 也需要。

**Comment by benjycui** [comment]
> 使用 allowSyntheticDefaultImports": true 只是为了跟引用类似 moment 这样的包统一，感觉可以去掉

没有这个选项的话，`moment(...)` 就用不了了。。

**Comment by infeng** [comment]
把 Typescript 直接转成 es5 的话，这样用 `import * as moment from 'moment';` 没问题

**Comment by benjycui** [comment]
但是在 TS 编译时报错。。
