### ISSUE TITLE
Image 组件的在手机端预览时能否添加手势的放大缩小

### ISSUE THREAD

**Issue by amin168** [ant-design/ant-design#44529]
### What problem does this feature solve?

能否给 Image 组件，预览图片时添加手势的放大缩小，或者拖放

### What does the proposed API look like?

在手机端预览图片时，可以两指放大和缩小，或者拖放

**Comment by yoyo837** [comment]
> 双指放大缩小是指双击两下屏幕后放大和缩小吗，拖放我看官网是页面整体放大和缩小

应该是“八”手势，虎口搓大搓小

**Comment by amin168** [comment]
Image 组件预览图片的双击两下屏幕后的放大和缩小已经实现了，差双指的放大和缩小，其实你这个官网页面整体放大和缩小是一个意思，只不过是换成 Image 组件的预览图片

**Comment by wanpan11** [comment]
我尝试添加下虎口缩放功能
> https://github.com/react-component/image/pull/279

rc-image 的demo网站 在移动端好像没有禁止缩放 效果不太能看出来😂😂😂

https://github.com/ant-design/ant-design/assets/38714194/db1fc8e8-54a4-4afb-a5d8-76f0ef4a928d

**Comment by wanpan11** [comment]
@MadCcc 大佬有空看看这个PR ^_^
