### ISSUE TITLE
新增伸缩框的组件，可以自由拖动box的大小

### ISSUE THREAD

**Issue by jia-sss** [ant-design/ant-design#44525]
### What problem does this feature solve?

一个box，可以设置四条边可鼠标拖动来改变box的大小，或者左右布局里中间可拖动。arco.design有这个功能，https://arco.design/react/components/resize-box

### What does the proposed API look like?

directions 可以拖动的边
受控的宽高

```jsx
      <ResizeBox
        directions={['right', 'bottom']}
        style={{
          width: 500,
          minWidth: 100,
          maxWidth: '100%',
          height: 200,
          textAlign: 'center',
        }}
      >
          <div>...</div>
      </ResizeBox>
```

**Comment by MadCcc** [comment]
感觉和这个差不多
https://github.com/ant-design/ant-design/issues/43737

**Comment by arvinxx** [comment]
详见：https://pro-editor.antdigital.dev/components/draggable-panel

**Comment by xliez** [comment]
请问下这个有进度吗？

**Comment by 1123612483** [comment]
这种组件在大部分业务场景下使用率还是挺高的，希望尽早推出

**Comment by Colormark** [comment]
> 详见：https://pro-editor.antdigital.dev/components/draggable-panel

不好用，而且样式冲突

**Comment by Colormark** [comment]
我建议还是用第三方的吧，推荐一个：
https://zesik.com/react-splitter-layout/#/nested

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/50038
