### ISSUE TITLE
允许直接从 antd 中导出类型 BasicDataNode

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#44527]
### What problem does this feature solve?

重新定义 fieldNames 是常见的需求，但是在 typescript 中可能会报出类型错误。
其中最佳解决方式：
```ts
import type { BasicDataNode } from 'rc-tree'
interfase TreeNode extends BasicDataNode {}
```
我们使用 npm 作为包管理工具时是没有问题的，但是使用 pnpm 作为包管理工具时，就无法直接从 rc-tree 导出 BasicDataNode 。
此时，需要对 rc-tree 进行 hoist，但只是为了导出 BasicDataNode 对包进行 hoist 显然是没必要的。

### What does the proposed API look like?
```ts
import type { BasicDataNode } from 'antd' 
```
or
```ts
import type { BasicDataNode } from 'antd/lib/tree'
```

**Comment by MadCcc** [comment]
`TreeNode` 不够么

**Comment by guaijie** [comment]
> 

TreeNode 不够是什么意思？
![image](https://github.com/ant-design/ant-design/assets/30885718/b1e14226-6ec6-4bdd-9d34-1606a92d7d38)

**Comment by guaijie** [comment]
> > 
> 
> TreeNode 不够是什么意思？ ![image](https://user-images.githubusercontent.com/30885718/264265557-b1e14226-6ec6-4bdd-9d34-1606a92d7d38.png)

![image](https://github.com/ant-design/ant-design/assets/30885718/df543c9f-efc9-43f5-a44f-27d840b81c17)
DataNode 因为 key 的限制导致如果数据中没有 key 类型就会报错

**Comment by guaijie** [comment]
> > > 
> > 
> > 
> > TreeNode 不够是什么意思？ ![image](https://user-images.githubusercontent.com/30885718/264265557-b1e14226-6ec6-4bdd-9d34-1606a92d7d38.png)
> 
> ![image](https://user-images.githubusercontent.com/30885718/264265865-df543c9f-efc9-43f5-a44f-27d840b81c17.png) DataNode 因为 key 的限制导致如果数据中没有 key 类型就会报错

![image](https://github.com/ant-design/ant-design/assets/30885718/5f950542-da9c-4a00-a6b5-85061715b37c)
TreeDataNode 就是 DataNode

**Comment by guaijie** [comment]
> `TreeNode` 不够么

我用的版本是 4.24.12

**Comment by MadCcc** [comment]
> ```ts
> import type { BasicDataNode } from 'antd/lib/tree'
> ```

可以搞一下这个

**Comment by afc163** [comment]
BasicDataNode 好奇怪，应该有更正式的命名。

**Comment by zombieJ** [comment]
> BasicDataNode 好奇怪，应该有更正式的命名。

嗯，所以不准备在根目录里导出。

**Comment by xiyangranhongyan** [comment]
其他组件也会有类型导出问题，例如 Slider 的 SliderRangeProps，现在只有 SliderSingleProps ，在需要对组件进行二次封装的时候 还是需要能够拿到内部类型的。像这种组件级别的 props 或者 用的比较多的枚举等 类型能否尽量导出一下？

`antd: v4.24.13`

![image](https://github.com/ant-design/ant-design/assets/31724313/9f085d51-88d2-413d-8520-c43def9a0cb0)
![image](https://github.com/ant-design/ant-design/assets/31724313/0c7261e3-650f-4770-a9d0-89ea6478bef5)

**Comment by kiner-tang** [comment]
> > ```ts
> > import type { BasicDataNode } from 'antd/lib/tree'
> > ```
> 
> 可以搞一下这个

这个有同学跟进吗？没有的话我来搞一下
