### ISSUE TITLE
Scrolling in Select on iPhone/iPad does not work properly

### ISSUE THREAD

**Issue by IvanTsarkovV** [ant-design/ant-design#44539]
### Reproduction link

[https://ant.design/components/select](https://ant.design/components/select)

### Steps to reproduce

Open on iphone/ipad https://ant.design/components/select and try to scroll Select dropdown

### What is expected?

Select dropdown should scrolls correctly on ios devices with virtual={true} and virtual={false}

### What is actually happening?

1) if set virtual={true} - on iphone/ipad scrollableBox scrolls with page
2) if set virtual={false} - on iphone/ipad scrollableBox stuck and not smooth

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.2.0 |
| System | iPhone/iPad |
| Browser | Chrome, Safari |

---
1) Select dropdown should scrolls correctly on ios devices with virtual={true}
2) If set virtual={false} need to remove all wrappers and scripts from virtual-list .rc-virtual-list, .rc-virtual-list-holder, .rc-virtual-list-holder-inner for some reason disabled virtual feature causes stuck of scrollableBox and not smooth scrolling in iPhone/iPad

**Comment by IvanTsarkovV** [comment]
Hi! Any updates on this issue?

**Comment by yoyo837** [comment]
Mobile is not our focus, please help us to improve it.

**Comment by afc163** [comment]
Duplicate of #37674
