### ISSUE TITLE
flex 的元素中使用 Tabs 会无限抖动

### ISSUE THREAD

**Issue by liuyib** [ant-design/ant-design#44533]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fu-jia-nei-rong-antd-4-24-12-forked-ll5zvw?file=/demo.tsx)

### Steps to reproduce

在线 demo 直接可复现

### What is expected?

flex 的元素中使用 Tabs 不会抖动

### What is actually happening?

flex 的元素中使用 Tabs 会无限抖动

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.0.0 |
| System | macOS 13.3.1 |
| Browser | Chrome 116.0.5845.110 |

---
v5 版本正常，v4 版本有这个问题

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-issue-44533-forked-3s578v?file=/demo.tsx

Flex 布局要设置 `minWidth`，否则它会贪婪。两边就会竞争最大宽度。

**Comment by liuyib** [comment]
好的，涨姿势了

**Comment by liuyib** [comment]
看样子，只设置 `flex: auto` 也可以：
<img width="1301" alt="image" src="https://github.com/ant-design/ant-design/assets/38221479/788d454c-45c9-4a10-aa7d-aec5be9b23f1">
