### ISSUE TITLE
受控Input组件无法输入中文

### ISSUE THREAD

**Issue by SyraTi** [ant-design/ant-design#44532]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/green-voice-q4tqk8?file=/index.js)

### Steps to reproduce

在任意输入框中键入中文

### What is expected?

中文正常被键入到输入框中

### What is actually happening?

中文输入法会被打断，导致输入框保留拼音的结果，无法键入中文字符

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.1.0 |
| System | macOS Monterey 12.4 |
| Browser | Chrome 版本 116.0.5845.110（正式版本） (x86_64) |

---
这个demo可能稍显复杂，是业务场景中遇到的问题，同时使用了Form/Table/Input 以及valtio，我无法排查出来是哪一个环节导致了这个问题，这已经是最小化能够复现的的demo，希望得到社区的帮助。

**Comment by zombieJ** [comment]
状态管理库不会完全按照 React 生命周期走，可以查阅一下状态库相关文档或者 issue。Input 本身没有做特殊的处理。

纯 `setState` 管理可以工作：
https://codesandbox.io/s/elegant-tom-r5g367?file=/index.js

原生 `input` 一样不行：
https://codesandbox.io/s/stoic-lalande-ww24d4?file=/index.js

**Comment by poyiding** [comment]
valtio 这里有相关issue: https://github.com/pmndrs/valtio/issues/222

**Comment by SyraTi** [comment]
问题已经解决，在valtio里找到了对应的issue，使用useSnapshot的sync选项解决了，感谢支持！
https://github.com/pmndrs/valtio/issues/270#issuecomment-961763212
