### ISSUE TITLE
How to get the antd table component instance

### ISSUE THREAD

**Issue by kongkongqlg** [ant-design/ant-design#44531]
### Reproduction link

[https://ant.design/components/table-cn](https://ant.design/components/table-cn)

### Steps to reproduce

无

### What is expected?

获取table组件实例，从组件外部获取他的检索条件，以及清空检索条件

### What is actually happening?

通过ref获取不到table组件实例

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | safaria |
| Browser | 8 |

**Comment by afc163** [comment]
可以直接控制 Table 的属性来进行，尽量用 React 的方式实现 UI 逻辑。
