### ISSUE TITLE
Table组件的文字换行策略overflow-wrap: break-word 导致输入数字或者重复的字符串，比如aaaaaa的时候，无法正常换行，进而导致width设置失败

### ISSUE THREAD

**Issue by a958330481** [ant-design/ant-design#44543]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-8-5-forked-5k4d9h?file=/demo.tsx)

### Steps to reproduce

 {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 
    tags: ['nice', 'developer'],
  },

或者

 {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: '111111111111111111111111111111111111111111111', 
    tags: ['nice', 'developer'],
  },

---

  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
    width:100,
  },

会发现   width:100 无效

### What is expected?

设置宽度生效，内容正常换行

### What is actually happening?

设置宽度无效，内容没有换行

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.0.0 |
| System | windows |
| Browser | chrome  版本 116.0.5845.111（正式版本） （64 位） |

**Comment by kiner-tang** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-8-5-forked-s48mxj?file=/demo.tsx
