### ISSUE TITLE
Space 中使用两个以上 Tabs 引起无限抖动

### ISSUE THREAD

**Issue by liuyib** [ant-design/ant-design#44542]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-issue-44533-forked-6f4qct?file=/demo.tsx)

### Steps to reproduce

CodeSandbox 可直接复现

### What is expected?

Space 中使用两个以上 Tabs 正常显示，不会抖动

### What is actually happening?

Space 中使用两个以上 Tabs 引起无限抖动

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.0.0 |
| System | macOS 13.3.1 |
| Browser | Chrome Latest |

---
参照: [#44533](https://github.com/ant-design/ant-design/issues/44533)，在 `flex` 的元素中使用 `Tabs` 可以通过设置 `flex: auto; minWidth: 0;` 来解决，但使用 `Space` 组件这个方法就不行了

antd v5 没问题，v4 有问题

**Comment by zombieJ** [comment]
Space 是内联元素，不是用作块状布局。块状布局会提供一个新的组件 Flex，也会支持 #44533 里的用法：https://github.com/ant-design/ant-design/pull/44362

**Comment by liuyib** [comment]
好的好的，一直没注意到使用注意事项：

![image](https://github.com/ant-design/ant-design/assets/38221479/7dc22331-5b8e-4930-bdb4-afa472d04f0c)

主要是 Space 太好用了，随手就用上了。期待新的 Flex 组件~
