### ISSUE TITLE
Popover组件宽度设置无效

### ISSUE THREAD

**Issue by tommiyxu** [ant-design/ant-design#44544]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ting-dian-ji-dan-chu-chuang-kou-antd-5-8-5-forked-2wrklh)

### Steps to reproduce

Popover组件
定义一个style width设置为500不起作用

### What is expected?

可以设置Popover组件的宽度

### What is actually happening?

Popover组件
定义一个style width设置为500不起作用

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 16.14.0 |
| System | win 10 64位 |
| Browser | chrome 版本 116.0.5845.112（正式版本） （64 位） |

**Comment by MadCcc** [comment]
用 `overlayStyle`
