### ISSUE TITLE
Ability to add a reset operation to a ref in uncontrolled mode？

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#44546]
### 需求背景

在使用 Input.Search 时，我使用了非受控方式，并且在 onSearch 事件中直接调用接口，但是可能还需要重置操作

https://codesandbox.io/s/ji-ben-shi-yong-antd-5-8-5-forked-978dyg?file=/demo.tsx

https://github.com/ant-design/ant-design/assets/32004925/a51f5d15-64b4-4e12-80cc-8148d12524c2

**Comment by MadCcc** [comment]
`allowClear`?

**Comment by MadCcc** [comment]
受控也可以实现吧，感觉是没必要在 ref 上提供这个方法

**Comment by Wxh16144** [comment]
我不确定有没有必要加，我不用受控是避免 state 变动而 rerender

**Comment by MadCcc** [comment]
那倒是可以做一下

**Comment by afc163** [comment]
建议用 state，避免 rerender 应该用 useMemo 等方式去优化。否则和用 jQuery 就没区别了。
