### ISSUE TITLE
给予定位的弹窗一个外部定位目标

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#44550]
### What problem does this feature solve?

```tsx
const [target, setTarget] = useState<HTMLElement>()

const handleContextMenu = const handleContextMenu: TreeProps<TreeRenderNode>['onRightClick'] = ({ event, node }) => {
    event.preventDefault()
    setTarget(event.target as HTMLElement)
}

const renderContextMenu = (el?: HTMLElement) => 
   el ? <Dropdown menu={{ items }} target={el} /> : null

return <div>
    <Tree<TreeRenderNode>
      treeData={treeData}
      fieldNames={{ title: 'name', key: 'id', children: 'children' }}
      onSelect={handleSelect}
      onRightClick={handleContextMenu}
    />
   {renderContextMenu(target)}
</div>
```
这使得这些需要定位的组件使用起来更为灵活，可以有更多可能

这一思想类似于：
```tsx
import { createPortal } from 'react-dom'
import { Menu } from 'antd'

const renderContextMenu = (el?: HTMLElement) =>
    el ? createPortal(<Menu items={items} />, el) : null
```

### What does the proposed API look like?
```tsx
<Tooltip target={el} />
<Dropdown target={el} />
```

**Comment by MadCcc** [comment]
这和这样写有什么不同？
```
<Dropdown trigger={['contextMenu']}>
  <Tree />
</Dropdown>
```

**Comment by guaijie** [comment]
> 这和这样写有什么不同？
> 
> ```
> <Dropdown trigger={['contextMenu']}>
>   <Tree />
> </Dropdown>
> ```

我上述中举了一个例子，再 Tree 中没法很好的使用

**Comment by Wxh16144** [comment]
> > 这和这样写有什么不同？
> > ```
> > <Dropdown trigger={['contextMenu']}>
> >   <Tree />
> > </Dropdown>
> > ```
> 
> 我上述中举了一个例子，在 Tree 中没法很好的使用 你得使用 Dropdown 包裹每一个节点以便来触发菜单

其实我是 get 到你的需求了，我最近一段时间也在用这个组件。 在钉钉和 @zombieJ 大佬请教过这个问题。 
<img width="550" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/73490456-b6d8-4321-9c89-bdb965df79cf">

**Comment by afc163** [comment]
类似 https://tree-react-component.vercel.app/demo/contextmenu ？

**Comment by guaijie** [comment]
> > > 这和这样写有什么不同？
> > > ```
> > > <Dropdown trigger={['contextMenu']}>
> > >   <Tree />
> > > </Dropdown>
> > > ```
> > 
> > 
> > 我上述中举了一个例子，在 Tree 中没法很好的使用 你得使用 Dropdown 包裹每一个节点以便来触发菜单
> 
> 其实我是 get 到你的需求了，我最近一段时间也在用这个组件。 在钉钉和 @zombieJ 大佬请教过这个问题。 <img alt="image" width="550" src="https://user-images.githubusercontent.com/32004925/265305487-73490456-b6d8-4321-9c89-bdb965df79cf.png">

**Comment by guaijie** [comment]
> > > 这和这样写有什么不同？
> > > ```
> > > <Dropdown trigger={['contextMenu']}>
> > >   <Tree />
> > > </Dropdown>
> > > ```
> > 
> > 
> > 我上述中举了一个例子，在 Tree 中没法很好的使用 你得使用 Dropdown 包裹每一个节点以便来触发菜单
> 
> 其实我是 get 到你的需求了，我最近一段时间也在用这个组件。 在钉钉和 @zombieJ 大佬请教过这个问题。 <img alt="image" width="550" src="https://user-images.githubusercontent.com/32004925/265305487-73490456-b6d8-4321-9c89-bdb965df79cf.png">

这很 react 。 react 自己都提供了思想类似的接口  ceatePortal， 为 vue 封装组件的 UI 库也提供了类似接口，只是它通过插槽来实现

**Comment by guaijie** [comment]
> 类似 https://tree-react-component.vercel.app/demo/contextmenu ？
是的，这是一种解决方式

**Comment by zombieJ** [comment]
Dropdown 本身没有什么 Magic 的，直接 HOC 一个 div 即可：

https://codesandbox.io/s/you-jian-cai-dan-antd-5-10-0-forked-fxsv2m?file=/demo.tsx
