### ISSUE TITLE
 Cascader 组件在多选的情况下  能否增加 全选选项

### ISSUE THREAD

**Issue by lanxiaojia** [ant-design/ant-design#44558]
### What problem does this feature solve?

Cascader 能点击全选选项后 全部选择

### What does the proposed API look like?

const options = [
  {
    value: 'all',
    label: '全部',
  },
  {
    value: 'option4',
    label: '选项4',
    children: [
      { value: 'option5', label: '选项5' },
      { value: 'option6', label: '选项6' },
    ],
  },
];

**Comment by MadCcc** [comment]
UI 长什么样？

**Comment by afc163** [comment]
Duplicate of #32176

**Comment by AndyDog** [comment]
请问有解决方案吗？Cascader 在多选模式下增加全选属性开关
