### ISSUE TITLE
Upload组件的onRemove回调方法中，可以阻止移除文件的事件吗？

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#4456]
需求：想在每次点击删除文件列表时给出确认框，如果确认删除再进行删除，否则不进行删除。
示例代码见： http://codepen.io/zhulichao/pen/rjNLqL?editors=001

**Comment by benjycui** [comment]
看了下源码，应该还不支持。

**Comment by benjycui** [comment]
感觉只能增加 `onRemove(...) => false` 这种用法来阻止默认行为了 @afc163

**Comment by zhulichao** [comment]
我试过在onRemove的回调方法中return false;，但是没阻止默认行为。那我自己再看看有没有其它办法吧，谢谢您的回答。

**Comment by afc163** [comment]
@benjycui 👌

@zhulichao 注意是在讨论开发需求。
