### ISSUE TITLE
RangePicker changeOnBlur not working with allowEmpty prop 

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#44563]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/range-picker-antd-5-8-5-forked-xz8hrx?file=/demo.tsx)

### Steps to reproduce

Open console, open range picker calendar and select dates then comment `allowEmpty` prop and then reselect dates

### What is expected?

`onChange` envent should only trigger when picker callendar is closed

### What is actually happening?

`onChange` event is fired on every date selection

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.2.0 |
| System | MacOS and CodeSandbox |
| Browser | Chrome 108.0.5359.124 |

**Comment by MadCcc** [comment]
It is intended. You could make value control with `open` prop.
