### ISSUE TITLE
Add support for dynamically setting Checkbox color

### ISSUE THREAD

**Issue by Bosseskompis** [ant-design/ant-design#44564]
### What problem does this feature solve?

When using checkboxes for filters, it's useful to visually associate an option to a color. See e.g. how Google Calendar filter works.

Example:
https://imgur.com/4oC1yOp

### What does the proposed API look like?

| Props             | Description | Type | Default |
| ----------------- | ----------------- | ----------------- | ----------------- |
| color | Overrides the default checkbox color | String | |

**Comment by MadCcc** [comment]
Though not best practice, with ConfigProvider, this can meet your demand.
https://codesandbox.io/s/checkbox-zu-antd-5-8-5-forked-3k88zv?file=/demo.tsx

**Comment by MadCcc** [comment]
We would not support `color` to change color of components, because there always some color like hover color or active color related with the origin color. And in antd, props will not affect cssinjs styles dynamicly, all we recommended to customize style is to use Token.

**Comment by iuiu34** [comment]
Hi,
about this.
Imagine i have 3 checkbox in 3 colors (red,orange, green).

How you're supposed to achieve this using Token? That's for global var (aka changing all checkbox to same color)

**Comment by omerts** [comment]
We are using checkboxes for legens in a chart, and each checkbox gets the color of the legend, which is dyanmic
