### ISSUE TITLE
antd@5.8.5 watermark component crash when use content from redux dispatcher result

### ISSUE THREAD

**Issue by bahborben** [ant-design/ant-design#44573]
### Reproduction link

[https://github.com/bahborben/antd-issue-demo](https://github.com/bahborben/antd-issue-demo)

### Steps to reproduce

just npm install and start

### What is expected?

fix it

### What is actually happening?

upgrade antd to version 5.8.5, npm start and the browser show error message as below:
ERROR CanvasRenderingContext2D.drawImage: Passed-in canvas is empty

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18 |
| System | Fedora 38 |
| Browser | firefox |

**Comment by bahborben** [comment]
full error message:

ERROR
CanvasRenderingContext2D.drawImage: Passed-in canvas is empty
getClips@http://localhost:3000/web/static/js/bundle.js:164372:10
drawCanvas@http://localhost:3000/web/static/js/bundle.js:164256:48
renderWatermark@http://localhost:3000/web/static/js/bundle.js:164277:19
commitHookEffectListMount@http://localhost:3000/web/static/js/bundle.js:257697:30
commitPassiveMountOnFiber@http://localhost:3000/web/static/js/bundle.js:259190:42
commitPassiveMountEffects_complete@http://localhost:3000/web/static/js/bundle.js:259162:38
commitPassiveMountEffects_begin@http://localhost:3000/web/static/js/bundle.js:259152:45
commitPassiveMountEffects@http://localhost:3000/web/static/js/bundle.js:259142:38
flushPassiveEffectsImpl@http://localhost:3000/web/static/js/bundle.js:261027:32
flushPassiveEffects@http://localhost:3000/web/static/js/bundle.js:260979:18
performSyncWorkOnRoot@http://localhost:3000/web/static/js/bundle.js:260196:7
flushSyncCallbacks@http://localhost:3000/web/static/js/bundle.js:248233:26
commitRootImpl@http://localhost:3000/web/static/js/bundle.js:260958:7
commitRoot@http://localhost:3000/web/static/js/bundle.js:260721:23
finishConcurrentRender@http://localhost:3000/web/static/js/bundle.js:260118:23
performConcurrentWorkOnRoot@http://localhost:3000/web/static/js/bundle.js:259969:33
workLoop@http://localhost:3000/web/static/js/bundle.js:274653:46
flushWork@http://localhost:3000/web/static/js/bundle.js:274631:18
performWorkUntilDeadline@http://localhost:3000/web/static/js/bundle.js:274868:25

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/44501
