### ISSUE TITLE
Steps组件渲染错误

### ISSUE THREAD

**Issue by earthaYan** [ant-design/ant-design#44575]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-8-5-forked-myqf65?file=/package.json:238-244)

### Steps to reproduce

分别传入不同的direction：vertical和horizontal

### What is expected?

传入vertical的时候，展示竖直的步骤条
传入horizontal的时候，展示横向的步骤条

### What is actually happening?

无论传入哪一个值，展示的都是竖直步骤条

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.0.0 |
| System | windows |
| Browser | chrome 116.0.5845.111 |

**Comment by earthaYan** [comment]
代码来源于官网的demo

**Comment by kiner-tang** [comment]
<img width="1432" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/30d6ecd2-dd37-40c9-8f5e-e4e2e9353349">
这不就是横向的么

**Comment by earthaYan** [comment]
> <img alt="image" width="1432" src="https://user-images.githubusercontent.com/10286961/264973170-30d6ecd2-dd37-40c9-8f5e-e4e2e9353349.png"> 这不就是横向的么

嗯，应该是我搞错了，因为是在笔记本电脑的屏幕上打开的,右侧展示区域宽度较小，所以自动转换为纵向了
