### ISSUE TITLE
form表单中使用pattern正则校验会在html中创建一个div并且永不被销毁,导致页面出现莫名滚动条无法消除

### ISSUE THREAD

**Issue by JokerAn** [ant-design/ant-design#44581]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-9cxlzw?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

步骤较多，已经在示例代码中写明了，打开上述网址有详细的步骤，感谢

### What is expected?

form表单销毁或者提交完毕后剔除自动给添加的div元素

### What is actually happening?

页面残留了一个div并且并未出现在body中而是和body同一级别，会导致页面出现滚动条并且无法删除该元素则会一直有滚动条(如果页面本身有滚动条的情况下切换页面会导致其他页面出现不应该出现的滚动条)

| Environment | Info |
| --- | --- |
| antd | 4.24.0 |
| React | 18 |
| System | mac |
| Browser | chrome 113.0.5672.126 |

<img width="1003" alt="image" src="https://github.com/ant-design/ant-design/assets/23717175/fb05383f-5cd3-46fe-b13d-dd6fc0768f92">

**Comment by JokerAn** [comment]
改为一下仍有问题，应当是触发了校验就会出现上述问题  const number8_12F = (rules: any, value: any, callback: any) => {
    if (value) {
      if (!number8_12.test(value)) {
        callback("请输入正确的电话");
      }
    }
    callback();
  };
<Form.Item
                    label="收件人电话"
                    name={[name, "receiverPhone"]}
                    rules={[
                      {
                        required: true,
                        validator: number8_12F,
                        message: "请输入正确的收件人电话",
                      },
                    ]}
                  >
                      <Input
                        size="small"
                        style={{ width: "100%" }}
                        placeholder="请输入"
                      />
                  </Form.Item>

**Comment by JokerAn** [comment]
目前的解决办法是 将div用css设置为了display:none就解决了，感觉官方应当直接设置dispaly:none的为什么用了visibility：hidden呢？

**Comment by zombieJ** [comment]
你的重现没有看到这个元素，看看是不是因为装了什么游览器插件导致的？

**Comment by JokerAn** [comment]
> 

可能问题描述有点问题，是form校验并非单纯的pattern属性，当form校验的时候会在html下生成一个div注意并非在body中！
这个例子已经复现了 https://codesandbox.io/s/antd-reproduction-template-forked-9cxlzw?from-embed
我录制了一个gif如下
![form错误滚动条问题](https://github.com/ant-design/ant-design/assets/23717175/bacec34f-dcff-4e43-b215-c910272ef5fc)

**Comment by JokerAn** [comment]
> 
 复现链接：https://codesandbox.io/s/antd-reproduction-template-forked-9cxlzw?from-embed
gif图已在楼上回复，请在页面等待加载，图片有点大需要加载一会才能出现

**Comment by zombieJ** [comment]
> 你的重现没有看到这个元素，看看是不是因为装了什么游览器插件导致的？

关掉游览器插件试试，我这边没有这个元素：

<img width="645" alt="截屏2023-09-05 10 07 59" src="https://github.com/ant-design/ant-design/assets/5378891/3422a85e-256f-48af-abbb-9dc97c1884e5">

**Comment by JokerAn** [comment]
> > 你的重现没有看到这个元素，看看是不是因为装了什么游览器插件导致的？
> 
> 关掉游览器插件试试，我这边没有这个元素：
> 
> <img alt="截屏2023-09-05 10 07 59" width="645" src="https://user-images.githubusercontent.com/5378891/265566638-3422a85e-256f-48af-abbb-9dc97c1884e5.png">

十分抱歉，确实是一款叫做”划词翻译“的浏览器拓展，在任何输入框触发了划词选择或者双击全选input框就会在body的后边生成一个div用于存储当前选中的数据好用于翻译，关闭该插件就一切正常，感谢官方耐心指导。
