### ISSUE TITLE
Issue with responsive design on mobile resolution

### ISSUE THREAD

**Issue by Meetchou** [ant-design/ant-design#44584]
Hi everyone,

We are submitting an msteam app to microsoft submission team and everything is working properly when we testing on our mobile/web app, however on their test, ant design component are not rendering on mobile version test.

here is the version of the device they using :
![image (3)](https://github.com/ant-design/ant-design/assets/94800824/1e67de1a-3403-4b74-b653-d4cc278c4fb9)
![image (2)](https://github.com/ant-design/ant-design/assets/94800824/03402d9a-1fae-402b-97ba-c628991baa1f)

here this is the expecting result with antdesign element working:
![Screenshot from 2023-09-01 18-28-18](https://github.com/ant-design/ant-design/assets/94800824/b7671931-2ab8-4cda-93b9-c4eb9c0eda27)

and here is what they are getting:
![Screenshot from 2023-09-01 18-27-40](https://github.com/ant-design/ant-design/assets/94800824/201a7d06-8644-47ea-9f36-a3db0b6e777e)

you can see that ant design elements are not applied.
thank you !

| Environment | Info |
| --- | --- |
| antd | 5.1.4 |
| React | 18.2.0 |
| System | Andorid 8.1.0 - O_MR1 |
| Browser | app |

**Comment by afc163** [comment]
Check https://ant.design/docs/react/compatible-style
