### ISSUE TITLE
CSS of Message component not displaying correctly

### ISSUE THREAD

**Issue by ETsReal** [ant-design/ant-design#44583]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/other-types-of-message-antd-5-8-5-forked-m6cjqg)

### Steps to reproduce

1.Click Success button or other.
2.Wait to see the Message in top center position.

### What is expected?

The CSS of Message component should display correctly.

### What is actually happening?

The CSS of Message component is not displaying correctly.

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.2.0 |
| System | elementary OS 6.1 Jólnir |
| Browser | Version 113.0.5672.92 (Official Build) (64-bit) |

---
ConfigProvider is affecting the Message CSS because if i remove the ConfigProvider component wrapper the CSS is fixed, but i need the fontFamily to be Poppins and fontSize to be 14px, globally.

**Comment by afc163** [comment]
<img width="562" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8a4ea2af-e3d5-4f78-b654-1058e6e65559">

```
          fontSize: 14,
```
