### ISSUE TITLE
Webpack dev server Warning while using <Spin /> component

### ISSUE THREAD

**Issue by fedorinoGore** [ant-design/ant-design#4458]
#### Environment(required)

- antd version: latest
- OS and its version: OS X 10.12.2
- Browser and its version: Chrome 57.0.2969.0 canary (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
I added Spin component directly to avoid importing the whole library:
`import Spin from 'antd/lib/Spin'`

#### What do you expected?
To import the component without any side effects and avoiding importing the whole UI lib 

#### What happen?
I have a really annoying warning each time my `webpack-dev-server` is rebulding:

```
./~/antd/lib/Spin/index.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
...
./~/antd/lib/spin/index.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```
And everything works fine and as expected, if component is imported as usual 
`import {Spin} from 'antd'`

**Comment by afc163** [comment]
```diff
- import Spin from 'antd/lib/Spin';
+ import Spin from 'antd/lib/spin';
```
