### ISSUE TITLE
upload 组件上传图片后无法预览

### ISSUE THREAD

**Issue by zhen-ke** [ant-design/ant-design#44580]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhao-pian-qiang-antd-5-8-5-forked-w4klsz)

### Steps to reproduce

图片的链接地址本身会进行权鉴
比如这个：http://uemprod.stable.alipay.net/baseinfo/downloadOssPic.htm?ossKey=MRCHANT_BASE_INFO_LOGO_PIC_OSS_PRE_cc9e9962-a3bb-4437-af66-76bdf588768d.jpgfileId%3AA*gr62SKtEYu8AAAAAAAAAAAAAT8nJAA.jpeg

站点已经登录过了，图片的链接浏览器能直接打开，用img标签也能加载显示，但使用 upload 组件上传后无法展示

### What is expected?

需要权鉴图片图片能正常预览

### What is actually happening?

需要权鉴图片图片能正不能预览

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 16 |
| System | MacOS |
| Browser | chrome |

**Comment by afc163** [comment]
图片预览链接是否能长期访问的问题需要业务自行解决了。
