### ISSUE TITLE
ProLayout组件支持扩展吗？想左侧导航增加鼠标滑入展示，鼠标移出隐藏，并左侧有锚点功能，现在支持扩展功能吗？

### ISSUE THREAD

**Issue by ityue** [ant-design/ant-design#44590]
### What problem does this feature solve?

ProLayout组件支持扩展吗想左侧导航增加鼠标滑入展示，鼠标移出隐藏，并左侧有锚点功能，现在支持扩展功能吗？

### What does the proposed API look like?

增加左侧移入展示，移除隐藏的开关。增加左侧锚点的开关

**Comment by poyiding** [comment]
你应该去  https://github.com/ant-design/pro-components 这边提 issue.

**Comment by ityue** [comment]
> ### What problem does this feature solve?
> ProLayout组件支持扩展吗想左侧导航增加鼠标滑入展示，鼠标移出隐藏，并左侧有锚点功能，现在支持扩展功能吗？
> 
> ### What does the proposed API look like?
> 增加左侧移入展示，移除隐藏的开关。增加左侧锚点的开关
