### ISSUE TITLE
侧边布局当内容过长时Sider与子Layout变为垂直排列

### ISSUE THREAD

**Issue by aarryy** [ant-design/ant-design#4459]
#### Environment(required)

- antd version: 2.6.0
- OS and its version: MacOS 10.12.2
- Browser and its version: Google Chrome 55.0.2883.95， Safari 10.0.2

#### What did you do? Please provide steps to re-produce your problem.

使用布局中的侧边布局，在Content部件中放入一段长一点的文字

#### What do you expected?

Sider与子Layout水平排列

#### What happen?

Sider与子Layout垂直排列， 原来子Layout所占据位置空白

#### Re-producible online demo

http://codepen.io/aarryy/pen/WRNzQg

**Comment by zhenzong** [comment]
我也遇到这个问题了。
临时解决方式，覆盖antd的样式：
```
.ant-layout {
    flex-wrap: nowrap;
}

.ant-layout-header,
.ant-layout-footer {
    flex: 1 0 auto;
}
```
