### ISSUE TITLE
Input 如何配置出像arco-design那样的效果？

### ISSUE THREAD

**Issue by agileago** [ant-design/ant-design#44591]
### What problem does this feature solve?

目前的主题Input配色貌似无法配置出 arco-design那样效果的input, 默认背景是灰色， hover上去变成深灰，focus时变成白色

### What does the proposed API look like?

支持配置成arco-design的配色效果

**Comment by afc163** [comment]
你可以试试自定义主题，如果发现缺少什么具体变量可以再提 issue 我们一起来补。

**Comment by agileago** [comment]
就是试了发现没有变量配置， 主要缺少 colorBgContainer 的各种状态配置

**Comment by afc163** [comment]
直接来个 PR？
