### ISSUE TITLE
Can't solve a problem with antd.Table

### ISSUE THREAD

**Issue by ErkinRejepow** [ant-design/ant-design#44595]
### What problem does this feature solve?

Retain the scroll position at the right place while continuously adding new row on top of the ant.Table.
I think I need some new feature to handle this situation.

Problem/question is from real life project:
I have posted a question in stackoverflow about antd.Table. Still couldn't get satisfying answer or solution.
So I started to think may be for now there is no solution for my problem using ant.Table.
So may be developers could have add some new features to solve this kind of problems
Link to stackoverflow question: https://stackoverflow.com/questions/77007923/how-can-i-retain-scroll-position-using-antd-table-in-react

### What does the proposed API look like?

Code that didn't give desired result: https://codesandbox.io/s/practical-cdn-l5v9ny?file=/src/App.js
Another code that worked with self defined <ItemList /> component: https://codesandbox.io/s/exciting-brown-xw9xpt?file=/src/App.js  
Wait until rows/items overflow the screen. Then scroll downward to see difference between codes in these links

**Comment by zombieJ** [comment]
Table support scroll to seems makes sense.

**Comment by ErkinRejepow** [comment]
Thank you very much for your attention
I will be so so glad to see these kind of feature in the nearest possible version.
And I really hope that you've understood my problem
