### ISSUE TITLE
Form 动态表单 name 不变 FormItem 切换时报错

### ISSUE THREAD

**Issue by sandwich99** [ant-design/ant-design#4460]
#### Environment(required)

antd version: 2.6.0
OS and its version: MacOS 10.12.2
Browser and its version: Google Chrome 55.0.2883.95， Safari 10.0.2

#### What did you do? Please provide steps to re-produce your problem.

根据外部传入的 type 决定渲染的 form 组件, type 可以动态修改
```jsx

class DateFilter {


    renderMonthPicker() {
        const { form: { getFieldDecorator } } = this.props;
        return getFieldDecorator('date')(<MonthPicker></MonthPicker>)
    }

    renderDayPicker() {
        const { form: { getFieldDecorator } } = this.props;
        return getFieldDecorator('date')(<DatePicker></DatePicker>)
    }

    render() {

        const { type } = this.props;
        let FormControl;
        if (type = 1) {
            FormControl = this.renderDayPicker();
        } else {
            FormControl = this.renderMonthPicker();
        }

        return (
            <Form>
                <FormItem>
                    { FormControl }
                </FormItem>
                <FormItem>
                    <Button htmlType="submit" type="primary">提交</Button>
                </FormItem>
            </Form>
        )
    }
}

```

#### What do you expected?

没有报错

#### What happen?

![image](https://cloud.githubusercontent.com/assets/1179783/21630460/41b0aeec-d26c-11e6-9a8a-abb4913e4444.png)

#### [Re-producible online demo](http://codepen.io/sandwich99/pen/OWJwJz)

see:  react-component/form#53

**Comment by benjycui** [comment]
非常规用法，并且设计到 React ref 触发时机的问题，空了再看吧。

现在还是用不同的 name 就好。

**Comment by sandwich99** [comment]
正确时序应该为:

初始化数据 -> 渲染 -> 清理数据 -> 销毁 dom -> 再次初始化数据 -> 渲染

目前时序为:

初始化数据 -> 渲染 -> 再次初始化数据 -> 清理数据 -> 销毁 dom -> 渲染

只是因为目前官方 demo 只有动态 name 的 , 所以避开了 初始化数据 和 清理数据的时序问题

**Comment by benjycui** [comment]
不好意思，事多人少，如果你已经理清逻辑了，可以考虑 PR，谢谢。

**Comment by codering** [comment]
我想了2种方式去解决，看可行不？ http://codepen.io/coderingz/pen/rjxJmj?editors=0010
@sandwich99 @benjycui

**Comment by sandwich99** [comment]
@codering  不行，这两种方式本质都是一样的，是通过一个中间层代理， 移除了 ref 

```jsx
      const {value, type, onChange} = this.props // 这里隐式丢弃了其他 props
      return <DatePicker value={value} onChange={onChange}/>
```
antd 底层依赖的 rc-form 内部是通过篡改真实 FormControl 的 props， 增加 ref 属性来实现资源回收的

```javascript
// https://github.com/react-component/form/blob/master/src/createBaseForm.js#L195
const inputProps = {
    ...this.getFieldValuePropValue(fieldOption),
    ref: this.getCacheBind(name, `${name}__ref`, this.saveRef),
};

// https://github.com/react-component/form/blob/master/src/createBaseForm.js#L146
return React.cloneElement(fieldElem, {
    ...props,
    ...this.getFieldValuePropValue(fieldMeta),
});

```
 
你这样实际上是丢弃了 form 的资源回收功能

**Comment by codering** [comment]
@sandwich99 本质是不一样的。
你最初的方式由于是两个不同组件在来回切换，导致其中一个组件必然会有unmount操作，因此ref就丢掉了。 
可以想到的解决方案，就是只要能让组件不unmount不就可以了吗？
因此我把动态切换抽象到一个组件内部，保证这个组件是稳定就可以了。

> `这里隐式丢弃了其他 props`

   这个props是rc-form给的，你能用到的也就只有value和onChange了

> `丢弃了 form 的资源回收功能 和 一部分资源初始化， 可能导致组件不可预测的 BUG`

   自定义表单组件，要与rc-form整合，最简单的方式就是该组件能接收value和onChange属性,就可以了。

   貌似antd的 Select组件就是这样处理的吧？ @benjycui 不知道我理解对不对？

**Comment by benjycui** [comment]
> 你这样实际上是丢弃了 form 的资源回收功能 和 一部分资源初始化， 可能导致组件不可预测的 BUG

其实你这个场景，并不需要用到 form 回收功能吧。

资源初始化时指？

**Comment by benjycui** [comment]
不过我还是觉得， @sandwich99 你把问题复杂化了，按我的理解这个场景没这么复杂。

**Comment by sandwich99** [comment]
咳咳， 偷了个懒，只跟踪到 ref 代码 不会被触发， 具体产生什么后果就没跟踪了 。 
```javascript
      saveRef(name, _, component) {
        if (!component) {
          // after destroy, delete data
          delete this.fieldsMeta[name];
          delete this.fields[name];
          delete this.instances[name];
          delete this.cachedBind[name];
          return;
        }
        const fieldMeta = this.getFieldMeta(name);
        if (fieldMeta) {
          const ref = fieldMeta.ref;
          if (ref) {
            if (typeof ref === 'string') {
              throw new Error(`can not set ref string for ${name}`);
            }
            ref(component);
          }
        }
        this.instances[name] = component;
      },
```

确实可以满足我的需求， @codering  谢谢了。 
因为我的场景里确实不需要资源回收，就是这个办法太 hack 了， 换个人可能就掉坑里了 😆 

但是我还是觉得多写几句代码， 使用不同 name ， 添加一句注释 antd 不支持同名动态 name 好一些

**Comment by zaaack** [comment]
这个地方也坑了我好久。。看来丢ref 对我来说才是稳定可靠的解决办法，这个issue强烈建议放到文档里，这么大的 feature（bug）不加到文档里实在太坑人了

**Comment by zaaack** [comment]
我照着官方的动态表单例子对照了很久，一直想不到哪里不对，原来就是因为我手动传递了多余的props。。@sandwich99 太感谢你了哈

**Comment by zaaack** [comment]
https://github.com/ant-design/ant-design/issues/4367

**Comment by benjycui** [comment]
@zaaack 来个 PR 更新文档即可。

**Comment by zaaack** [comment]
最近太忙了。。过几天吧

**Comment by huangxinxia** [comment]
求修复，很需要，一些表单类型就是动态的，根据用户的选择动态变换表单类，切name保持不变。
