### ISSUE TITLE
Image组件弹出的图片下面的旋转按钮响应事件反了

### ISSUE THREAD

**Issue by etsvain** [ant-design/ant-design#44612]
### Reproduction link

[https://ant-design.antgroup.com/components/image-cn?direction=rtl](https://ant-design.antgroup.com/components/image-cn?direction=rtl)

### Steps to reproduce

点开弹出图片
点击向左翻转和向右翻转，图片翻转方向反过来了
![image](https://github.com/ant-design/ant-design/assets/33209586/24f93d3d-32ab-4bed-8072-ae0be45e152c)

### What is expected?

调整翻转方向

### What is actually happening?

反了

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | react18 |
| System | macos big sur 11.6.5 |
| Browser | 103.0.5060.114 |

**Comment by kiner-tang** [comment]
你给的链接是在使用 rtl 模式？

**Comment by kiner-tang** [comment]
> 你给的链接是在使用 rtl 模式？

试了一下，没有复现出来，可以提供一个演示视频么？

**Comment by Zzongke** [comment]
![image](https://github.com/ant-design/ant-design/assets/65376724/b77456aa-a6d6-4139-939e-b8b66b722b6f)


@kiner-tang 他給的鏈接就是rtl模式😊

**Comment by kiner-tang** [comment]
> ![image](https://user-images.githubusercontent.com/65376724/265865670-b77456aa-a6d6-4139-939e-b8b66b722b6f.png)
> 
> @kiner-tang 他給的鏈接就是rtl模式😊

对，但是使用提供的链接没有复现出问题

**Comment by Zzongke** [comment]
> > ![image](https://user-images.githubusercontent.com/65376724/265865670-b77456aa-a6d6-4139-939e-b8b66b722b6f.png)
> > @kiner-tang 他給的鏈接就是rtl模式😊
> 
> 对，但是使用提供的链接没有复现出问题

是的，我也沒復現出問題
