### ISSUE TITLE
onFocus not triggered when switching "disabled" property

### ISSUE THREAD

**Issue by MartinStepar** [ant-design/ant-design#44619]
### Reproduction link

[https://mln2sl.csb.app/](https://mln2sl.csb.app/)

### Steps to reproduce

1. **Click on First select** → SAVING occurs
1. **Click on Second select** → SAVING occurs
1. **Click on First select again** → No saving occurs - no onFocus triggered
1. **Click on Second select again** → SAVING occurs
1. **Click on First select for third time** → No saving occurs again - no onFocus triggered

### What is expected?

onFocus is triggered every time when select is focused on both selects (especially after focus lost - when onBlur was triggered before)

### What is actually happening?

onFocus is triggered only for the first time on First select (it's weird that onBlur is triggered every time when focus is lost)

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | Windows 11 Home |
| Browser | newest Chrome, Edge |

---
This is happening only when switching "disabled" property. Without "disabled" switching (means disabled is no set or is still set to false) everything works fine. useEffect is used for renewing focus after re-enabling disabled select.

SAVING text represents application state, when real application sending data to backend (and when all selects are disabled). Of course, there is no real saving in this minimal example.

**Comment by zombieJ** [comment]
Select internal also has state to save the focus mark. I guess when control disabled by the focus & blur event makes internal state mistake which not throw the correct event.

**Comment by Yuiai01** [comment]
I'll try to fix this.
