### ISSUE TITLE
QRCode二维码组件文档参数错误

### ISSUE THREAD

**Issue by quitelxd** [ant-design/ant-design#44627]
### Reproduction link

[https://ant-design.antgroup.com/components/qr-code-cn](https://ant-design.antgroup.com/components/qr-code-cn)

### Steps to reproduce

根据API中的icon属性（icon	二维码中图片的地址（目前只支持图片地址）	string	-）来设置二维码中的icon

### What is expected?

显示二维码中的icon图标

### What is actually happening?

未显示

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 17.x |
| System | windows11 |
| Browser | chrome 116.0.5845.141（正式版本） （64 位） |

---
经阅读源码发现设置icon属性需通过 imageSettings:ImageSettings 来设置

**Comment by Wxh16144** [comment]
https://ant-design.antgroup.com/components/qr-code-cn#qr-code-demo-icon

这样？
<img width="591" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/fac00589-7d19-41c5-8674-2195b6d681aa">

**Comment by li-jia-nan** [comment]
没啥问题吧，antd 做了一层封装，传 `icon` 就可以了，底层是 antd 把 icon 传给了 `imageSettings.src`

**Comment by quitelxd** [comment]
imageSettings

> 没啥问题吧，antd 做了一层封装，传`icon`就可以了，底层是 antd 把 icon 传给了了`imageSettings.src`

我在node_modules源码里面发现  `function QRCodeCanvas(props) `这个方法里面接收的参数 
` const _a = props, {
    value,
    size = DEFAULT_SIZE,
    level = DEFAULT_LEVEL,
    bgColor = DEFAULT_BGCOLOR,
    fgColor = DEFAULT_FGCOLOR,
    includeMargin = DEFAULT_INCLUDEMARGIN,
    style,
    imageSettings
  } = _a, otherProps = __objRest(_a, [
    "value",
    "size",
    "level",
    "bgColor",
    "fgColor",
    "includeMargin",
    "style",
    "imageSettings"
  ]);
  const imgSrc = imageSettings == null ? void 0 : imageSettings.src;`
是这样赋值的；看样子是拿到imageSettings.src赋值的；
在QRCode 组件中接收的 props 中定义的参数类型是这样的
`declare type QRProps = {
    value: string;
    size?: number;
    level?: string;
    bgColor?: string;
    fgColor?: string;
    style?: CSSProperties;
    includeMargin?: boolean;
    imageSettings?: ImageSettings;
};`
所以在接收的时候并没有icon的属性

**Comment by quitelxd** [comment]
> https://ant-design.antgroup.com/components/qr-code-cn#qr-code-demo-icon
> 
> 这样？ <img alt="图像" width="591" src="https://user-images.githubusercontent.com/32004925/265595327-fac00589-7d19-41c5-8674-2195b6d681aa.png">

对，是这样的，按照api设置icon，在我这里是没有效果的

**Comment by quitelxd** [comment]
并且通过 `imageSettings` 这只icon地址，发现会严重影响二维码识别效果，只能将二维码`width`和`height`调整大，设置`errorLevel="H"`效果不大

**Comment by Wxh16144** [comment]
先看提示：
<img width="1211" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/9a1cc2b8-8b85-4844-bf1b-5f134110c9b5">

另外根据 issue 描述的 5.8.6 版本来说，你提供的源码可能不太对，建议重新安装依赖，你也可以打开 https://npmmirror.com/package/antd/files/lib/qr-code/index.js#L58-L66 看一下这里的产物
