### ISSUE TITLE
Tree data issue

### ISSUE THREAD

**Issue by kuldeepsuccessive** [ant-design/ant-design#44621]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

creat a search input and filter data according to search

### What is expected?

if i selected any row and apply search and then select a row and clear seach previous data should selected

### What is actually happening?

if i selected any row and apply search and then select a row and clear seach previous data should selected right now its first time selected data is not selected

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | linux |
| Browser | chrome |

**Comment by zombieJ** [comment]
Your reproduce is empty.

**Comment by kuldeepsuccessive** [comment]
https://codesandbox.io/s/tree-data-antd-5-8-5-forked-xfc7xz?file=/demo.js

On this url you can check first you need select John then search joe and hit enter then select joe and clear search with hit enter. Then you can see John was not selected

**Comment by MadCcc** [comment]
Your demo cannot be interacted.
![image](https://github.com/ant-design/ant-design/assets/27722486/650e7540-b7e5-4f4f-8800-a93c562db6cb)

**Comment by kuldeepsuccessive** [comment]
But you can check its simply on tree data if we implement search than pervious selected data was not selected
