### ISSUE TITLE
RangePicker 设置disabled为数组卡死问题

### ISSUE THREAD

**Issue by eijil** [ant-design/ant-design#44622]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-zhuang-tai-antd-4-24-13-forked-c35rzr?file=/demo.tsx)

### Steps to reproduce

引入DatePicker RangePicker disable设置值为[true, false]

### What is expected?

正常展示

### What is actually happening?

控制台输出 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
https://github.com/react-component/picker/releases/tag/v2.7.4
