### ISSUE TITLE
Form 组件使用日期类控件，设置默认值后，展开选择日期显示时间异常

### ISSUE THREAD

**Issue by jinxiaoman** [ant-design/ant-design#44628]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shi-jian-lei-kong-jian-antd-5-8-6-forked-dnz2n2?file=/demo.js:1470-1544)

### Steps to reproduce

1. 使用控件
2. 使用 initialValues 或者 defaultvalue 设置默认月份后，切换日期显示异常（年份乱了）

### What is expected?

正常

### What is actually happening?

正常

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 16.8 |
| System | winodws |
| Browser | chrome |

---
const initialValues = {
  "month-picker": moment().subtract(1, "month")
};

**Comment by zombieJ** [comment]
v5 不是 moment，是 dayjs

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774
