### ISSUE TITLE
Select 组件设置 dropdownRender 渲染底部区域并渲染一个input框，mode设置为multiple，删除input框内容的时候，会清除select选中项

### ISSUE THREAD

**Issue by zzq1101921989** [ant-design/ant-design#44635]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-24-13-forked-lw3d3r?file=/demo.tsx:0-1498)

### Steps to reproduce

按照流程设置属性就可以了

### What is expected?

我删除input数据的时候，选中的项目不要删除

### What is actually happening?

我删除input数据的时候，选中的项目还是被删除了

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 17.0.0 |
| System | window10 |
| Browser | 谷歌浏览器 115.0.5790.110 |

**Comment by marong1997** [comment]
为啥关闭了 ？   我这有复现哦

**Comment by yoyo837** [comment]
> 为啥关闭了 ？ 我这有复现哦

辛苦你开个新的

**Comment by zzq1101921989** [comment]
> 为啥关闭了 ？ 我这有复现哦

issues有类似的问题，而且评论区也给了解决方法，所以我就关闭了，可以通过禁止冒泡解决

**Comment by marong1997** [comment]
没啊 ，禁止冒泡不好使

**Comment by zzq1101921989** [comment]
> 没啊 ，禁止冒泡不好使

禁止的是input的onchange方法吗？

**Comment by marong1997** [comment]
是哦

**Comment by marong1997** [comment]
> > 为啥关闭了 ？ 我这有复现哦
> 
> 辛苦你开个新的

https://github.com/ant-design/ant-design/issues/46655 开了

**Comment by marong1997** [comment]
已解决： 冒泡事件在onKeyDown部分处理
