### ISSUE TITLE
Tabs 没有根据 tabBarExtraContent 的变化而重新计算可滚动的宽度

### ISSUE THREAD

**Issue by Dunqing** [ant-design/ant-design#44632]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fu-jia-nei-rong-antd-5-8-6-forked-gnfrjp?file=/demo.tsx)

### Steps to reproduce

1. 将 Tabs 滚到最右边
2. 然后隐藏 tabsExtraContent
3. 看到不正常的结果

### What is expected?

预期是正常展示

### What is actually happening?

多余的空白

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18 |
| System | all |
| Browser | all |

**Comment by Dunqing** [comment]
Looks like same issue with [#38270](https://github.com/ant-design/ant-design/issues/38270)

**Comment by xiaozisong** [comment]
我来试试

**Comment by dxsun97** [comment]
it seems to be fixed in `rc-tabs`: https://github.com/react-component/tabs/pull/662, but still pending, @zombieJ have a look?

**Comment by zombieJ** [comment]
> it seems to be fixed in `rc-tabs`: [react-component/tabs#662](https://github.com/react-component/tabs/pull/662), but still pending, @zombieJ have a look?

@xiaozisong seems this PR can handle this issue

**Comment by xiaozisong** [comment]
let me see it
