### ISSUE TITLE
主题切换过渡效果

### ISSUE THREAD

**Issue by iyuli** [ant-design/ant-design#44644]
### What problem does this feature solve?

目前切换theme的token是没有任何动画效果的
希望可以增加动画效果

### What does the proposed API look like?
![动画1](https://github.com/ant-design/ant-design/assets/38270397/0b056d15-360f-4a01-a598-00343f3f2c59)
https://github.com/iyuli/Them-switch-animation-vue
参考这个demo，可以看到切换主题的动画效果

**Comment by zombieJ** [comment]
酷~

**Comment by iyuli** [comment]
> 酷~

怎么样，能不能支持一下

**Comment by zombieJ** [comment]
有兴趣来个 PR 不？

**Comment by iyuli** [comment]
> 有兴趣来个 PR 不？

我可能没有多余的时间，因为我现在还没有理解ant-design的源码。

**Comment by zombieJ** [comment]
> 我可能没有多余的时间，因为我现在还没有理解ant-design的源码。

OK，那我加个标签~

**Comment by RedJue** [comment]
我来试试
