### ISSUE TITLE
form的input框未输入的时候通过form的api去拿表单值时，第一次获取未填写的输入框值时获取的是undefined（符合预期），但是当在input里面输入一些值然后清空后获取的是空字符串，这在搜索的时候会引发bug

### ISSUE THREAD

**Issue by Jerryqun** [ant-design/ant-design#44645]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-8-5-forked-vsnpst?file=/demo.tsx)

### Steps to reproduce

点击提交看console

### What is expected?

输入框输入后再清空获取的任然是undefined

### What is actually happening?

输入框输入后再清空获取的是空字符 （""）

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.0.0 |
| System | mac 13.2.1 |
| Browser | 谷歌 版本 115.0.5790.170（正式版本） (arm64) |

**Comment by zombieJ** [comment]
这是符合预期的，你使用原生的 input 也是这个效果。如果需要删除时变成 `undefined` 可以  HOC 一下：

```tsx
const MyInput = ({ onChange, ...rest }) => <Input {{...rest} onChange={(e) => e.target.value ? e.target.value : undefined} />
```

**Comment by Jerryqun** [comment]
> 这是符合预期的，你使用原生的 input 也是这个效果。如果需要删除时变成 `undefined` 可以 HOC 一下：
> 
> ```tsx
> const MyInput = ({ onChange, ...rest }) => <Input {{...rest} onChange={(e) => e.target.value ? e.target.value : undefined} />
> ```

antd4.x的版本应该是处理了的。5.x没有处理了

**Comment by Jerryqun** [comment]
> 这是符合预期的，你使用原生的 input 也是这个效果。如果需要删除时变成 `undefined` 可以 HOC 一下：
> 
> ```tsx
> const MyInput = ({ onChange, ...rest }) => <Input {{...rest} onChange={(e) => e.target.value ? e.target.value : undefined} />
> ```

每一个简单的crud 都得去处理，因为接口很可能不会去过滤空字符串。这对于老项目没有进行二次封装antd 直接使用的场景，如果升级5.x简直就是深渊了

**Comment by hacker0limbo** [comment]
> > 这是符合预期的，你使用原生的 input 也是这个效果。如果需要删除时变成 `undefined` 可以 HOC 一下：
> > ```tsx
> > const MyInput = ({ onChange, ...rest }) => <Input {{...rest} onChange={(e) => e.target.value ? e.target.value : undefined} />
> > ```
> 
> 每一个简单的crud 都得去处理，因为接口很可能不会去过滤空字符串。这对于老项目没有进行二次封装antd 直接使用的场景，如果升级5.x简直就是深渊了

这个确实没办法, 我自己尝试批量的解决方式有一种是在请求里做拦截器, 例如在 axios 的请求拦截器里批量把 empty string 改为 undefined. 还有一种是比如用 query-string 来处理 params 的时候开启 [skipemptystring](https://github.com/sindresorhus/query-string#skipemptystring). 实在没办法那只能忍忍一个一个去修复了...
