### ISSUE TITLE
DatePicker: value isn't resetting fully

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#44650]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-p7v7h9?file=/index.js)

### Steps to reproduce

1. Make sure pickers empty
2. Pick any date
3. Repeat previous step
4. Click button to reset form
5. Pick any date

### What is expected?

I expect that if pickers are empty and you pick any date in DatePicker it will always be added only 5 min, not more. Regardless of clicking count before

### What is actually happening?

Now if you pick any date in DatePicker two or more times, reset form and pick date again, time in TimePicker increases to 5 min again and again

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Version 116.0.5845.140 (Official Build) (64-bit) |

---
Note that I use latest React-Hook-Form, control date and time by single field in RHF. I've already checked that RHF works correctly. You can make sure in it via RHF devtools (red square in the upper right corner).
I don't understand why null value passing after resetting form isn't set to pickers correctly

**Comment by zombieJ** [comment]
It's by design to cache prev state to enable keep the panel when reopen. You can do re-mount if need this requirement:

https://codesandbox.io/s/antd-reproduction-template-forked-5cplzy?file=/index.js
