### ISSUE TITLE
Tab component starts flickering if inside flex container

### ISSUE THREAD

**Issue by Comum** [ant-design/ant-design#44668]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-trigger-of-new-tab-antd-5-8-6-forked-ctrv7r?file=/demo.tsx)

### Steps to reproduce

Nest Tabs component in a div that has dynamic width ( flex wrapper ) the tab items start flickering. Check the codesandbox example.

### What is expected?

Wanted to vertically centre the Tabs component.

### What is actually happening?

Tabs component is centered but there is a flick because of the .ant-tabs- nav-operations and the ellipsis button.

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.2.0 |
| System | Mac OS Ventura 13.1 |
| Browser | Chrome for sure, potentially all |

**Comment by xiaozisong** [comment]
我来试试

**Comment by xiaozisong** [comment]
因为当flex布局时，元素的offsetLeft+width大于容器宽度后，就会显示operationNode，但是，是实时计算的就会出现闪屏的现象，那怎么优化useVisibleRange方法呢？？

**Comment by solitia7125** [comment]
我提个PR看看

**Comment by Comum** [comment]
Any news on the progress of the PR?

**Comment by Grawl** [comment]
It's very annoying

**Comment by solitia7125** [comment]
> Any news on the progress of the PR?
Sorry. Probably be later because im busy with interviews.

**Comment by Comum** [comment]
Hey guys, applied this patch with patch-package and the issue still happens ( a lot less ).

**Comment by jiang-zhong-xi** [comment]
I have same issue

**Comment by Grawl** [comment]
@Comum can you show how exactly you applied a patch?

**Comment by Comum** [comment]
I used [patch-package](https://www.npmjs.com/package/patch-package) on my project.

- changed the node modules manually
- then ran `npx patrch-package rc-tabs`
