### ISSUE TITLE
Transfer should be able to select all rows between Click and Shift   Click

### ISSUE THREAD

**Issue by tompenzer** [ant-design/ant-design#44669]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/33934](https://github.com/ant-design/ant-design/issues/33934)

### Steps to reproduce

Select an item on either side of the Transfer component, then hold down 'Shift' key, then select another item on the same side.

### What is expected?

All items between the two selected items should be selected.

### What is actually happening?

The text labels for all items between first and last are highlighted, but the item inputs are not selected.

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | Mac OS 13.4.1 |
| Browser | Safari 16.5.2 |

---
The linked issue seems to have been prematurely closed by the author, along with a comment that says they found a solution, but doesn't seem to make any sense as described. This feature is still needed.

**Comment by zbw-zbw** [comment]
let me try

**Comment by zbw-zbw** [comment]
@afc163 大佬，有空 review 下 pr～

**Comment by zbw-zbw** [comment]
@tompenzer  supported by 5.10.3
