### ISSUE TITLE
求教：同一个项目在不同电脑（操作系统浏览器相同）上侧边栏字体样式不同

### ISSUE THREAD

**Issue by cosyer** [ant-design/ant-design#4466]
#### Environment(required)

- antd version:2.5.1
- OS and its version:
- Browser and its version:chrome

#### 具体描述
一台电脑上的项目侧边栏字体颜色为#000，另一台为#999。
####main.less相关代码
.ant-menu-item {
    &:hover > a {
      color: @primary-color;
    }
  }

  &.ant-menu-inline {
    .ant-menu-item-selected {
      background-color: rgba(255,255,255,0.05);

      & > a {
        color: @primary-color;
      }
    }
  }

  .ant-menu-item-selected {
    color: @primary-color;
  }
}

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4440
