### ISSUE TITLE
Cascader 组件下拉图标位置不正确

### ISSUE THREAD

**Issue by WinterWoods** [ant-design/ant-design#44672]
### Reproduction link

[https://stackblitz.com/edit/react-d9z3df?file=demo.js](https://stackblitz.com/edit/react-d9z3df?file=demo.js)

### Steps to reproduce

Cascader外容器有高度之后拉下图标位置不正确.

### What is expected?

外容器有高度后,下拉图标显示正确

### What is actually happening?

Cascader外容器有高度之后拉下图标位置不正确.

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2 |
| System | window |
| Browser | chrome |

**Comment by zombieJ** [comment]
`flex` 里子元素默认 align 会表现为 `stretch`，而 Cascader 输入框本身是不允许延伸的。可以加个 `align` 配置：

https://stackblitz.com/edit/react-d9z3df-j3qzpw?file=demo.js

PS：可以看看能不能给 Cascader 做一下延伸支持。

**Comment by afc163** [comment]
Select 也有一样的问题。
