### ISSUE TITLE
3.x版本中 form.getFieldDecorator 与 React.forwardRef 同时使用时遇到组件输入内容就失焦的问题

### ISSUE THREAD

**Issue by kiccer** [ant-design/ant-design#44671]
### Reproduction link

[https://stackblitz.com/edit/react-e3axek?file=EasyForm.js](https://stackblitz.com/edit/react-e3axek?file=EasyForm.js)

### Steps to reproduce

在文本框中输入内容

### What is expected?

文本框正常输入内容

### What is actually happening?

输入内容就失焦

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 16.6.3 |
| System | win10 |
| Browser | chrome 116.0.5845.142（正式版本） （64 位） |

---
看到上面选择 antd 版本时已经没有 3.x 的选择了，不知道官方是否还维护 3.x 的版本，公司老项目了，不敢轻易升级。

我基于 antd 的 Form 重写了一个表单组件，通过配置内容生成表单。
为了解决组件越来越臃肿的问题，想将其改写为懒加载的方式引入子组件。
由于懒加载组件需要外层包裹 Suspense，导致 getFieldDecorator 无法将 props 绑定到 Suspense 内部的自定义组件，需要用通过 forwardRef 来传递。但是加上 forwardRef 后，内部自定义组件在输入内容时就会立马失去焦点(原因未查明)，导致操作体验问题。

即使不做成懒加载，原本表单配置还支持 render 方式自定义表单项，但是 render 也需要 forwardRef 包裹，所以这个问题一直存在。

**Comment by yoyo837** [comment]
3.x?

**Comment by kiccer** [comment]
> 3.x?

公司项目使用的是 3.26.17
我写的 demo 使用的是 3.26.20

**Comment by afc163** [comment]
看看 https://stackblitz.com/edit/react-e3axek-1trday?file=EasyForm.js

**Comment by kiccer** [comment]
> 看看 https://stackblitz.com/edit/react-e3axek-1trday?file=EasyForm.js

感谢！公司网不好，发完Issues就连不上github了。。一直没看到回复。回家才看到的。
我已经解决啦！不过还是感谢！！
我刚接触 react 一个月，还没用习惯哈哈。🤣
