### ISSUE TITLE
Segmented 组件 主题变量token 类型声明SegmentedComponentToken为空，导致 ts 报错

### ISSUE THREAD

**Issue by luichooy** [ant-design/ant-design#44687]
### What problem does this feature solve?

解决主题 token 使用在 ts 中不报错的问题

### What does the proposed API look like?

```typescript
interface SegmentedComponentToken {
   itemSelectedBg?: string
   // ....
}
```

**Comment by luichooy** [comment]
![image](https://github.com/ant-design/ant-design/assets/26423033/d092c266-8892-4e34-9e30-ce320c90c479)
![image](https://github.com/ant-design/ant-design/assets/26423033/6cc212bb-59ea-4109-9e91-b70c1d559186)

这里类型声明里面没写 token， 导致直接写 token 属性 ts 类型报错

**Comment by Dunqing** [comment]
看这里 https://github.com/ant-design/ant-design/releases/tag/5.6.0

`5.6.0` 才支持的这些 `ComponentToken` 你用的是 `5.4.7`

**Comment by luichooy** [comment]
> 看这里 https://github.com/ant-design/ant-design/releases/tag/5.6.0
> 
> `5.6.0` 才支持的这些 `ComponentToken` 你用的是 `5.4.7`

ok，万分感谢👍🏻

实际上我之前已经使用 `pnpm update antd` 更新到`5.8.6`，可能是 pnpm 的机制导致的。我卸载掉重新安装一遍好了
