### ISSUE TITLE
table中排序 sorter 设为true，点击↑或者↓的时候，如何触发onClick事件？

### ISSUE THREAD

**Issue by XdCareWy** [ant-design/ant-design#4468]
table中排序 sorter 设为true，点击↑或者↓的时候，如何触发onClick事件？
我看了antd的源码，当sorter设置为true的时候，直接return了，并没有做任何的处理。
是这个功能没有实现，还是我理解的有问题？

**Comment by afc163** [comment]
请看这个例子：https://ant.design/components/table-cn/#components-table-demo-ajax

当 sorter 为 true 时，意味着前端只展现排序图标，没有具体排序逻辑，点击↑或者↓时会触发 `Table[onChange]` 方法，在 onChange 里拿到排序方向向后台发送相应的请求。

**Comment by AssassinGao** [comment]
@afc163  sorter为true, 从后台拿数据,  此时能否通过一个按钮重置排序箭头的状态?

**Comment by ChaseChan** [comment]
> 请看这个例子：https://ant.design/components/table-cn/#components-table-demo-ajax
> 
> 当 sorter 为 true 时，意味着前端只展现排序图标，没有具体排序逻辑，点击↑或者↓时会触发 `Table[onChange]` 方法，在 onChange 里拿到排序方向向后台发送相应的请求。

你好，为什么我使用ant-design-pro时，设置sorter为true后，如果是发送网络请求，一旦更新state，sorter返回的值永远都是一样的呢？不更新state会返回升序，降序和空，但是一旦网络请求成功，然后更新state，就会永远只有一个状态。

**Comment by JunlinZhu-Tommy** [comment]
@afc163  优秀。
