### ISSUE TITLE
select下拉框能初始展示的时候获取焦点吗

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#4469]

**Comment by yesmeck** [comment]
Try `defaultActiveFirstOption`.

**Comment by yesmeck** [comment]
`defaultActiveFirstOption` 默认就是 `true` 的，你想要什么效果？

**Comment by XUGAOBO** [comment]
是select这个组件获取焦点,而不是它的某项option获取焦点

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/3790
