### ISSUE TITLE
Form.List中的Form.Item卸载时，未清除其name对应字段

### ISSUE THREAD

**Issue by FFRfree** [ant-design/ant-design#44697]
### Reproduction link

[[![Edit on CodeSandbox](https://codesandbox.io/s/condescending-hoover-w5fy69)](https://codesandbox.io/s/condescending-hoover-w5fy69)

### Steps to reproduce

1. 填写两个输入框的boyName
2. 点击log FormValue打印
3. 点击switch，两个boyName表单项卸载，填写两个输入框girlName
4. 点击log FormValue打印
5. 可以看到只有example2 组件卸载后的boyName字段被正常清除，example list的boyName未被清除

### What is expected?

example list的boyName未被清除

### What is actually happening?

example list表单对应boyName字段残留

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | mac arm64 |
| Browser | chrome 115.0.5790.170 |

---
那Form.List 中的FormItem boyName和girlName切换时，没有删除卸载组件的name字段对应的状态，而同时保留了girlName和boyName，这也是预期表现么😂

_Originally posted by @FFRfree in https://github.com/ant-design/ant-design/issues/44686#issuecomment-1709720099_

**Comment by zombieJ** [comment]
是的，此外我在下面也提到了。下个 minor 版本会提供过滤 FormList 字段的能力哈：

> 另外，对于 List 的情况，下一个 minor 版本会提供一个配置去拿 List 子元素的值，而忽略 List 本身的字段绑定~

**Comment by zombieJ** [comment]
Update. 错了。5.8.0 里已经提供了: `getFieldsValue({ strict: true })`
