### ISSUE TITLE
Message component : BorderRadius token not getting reflected

### ISSUE THREAD

**Issue by samanthaburboz** [ant-design/ant-design#44704]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kz4tw5?file=/index.js)

### Steps to reproduce

Create a Message component

### What is expected?

Border Radius should be updated to 2

### What is actually happening?

Border Radius is not getting updated

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 	17.0.1 |
| System | Windows 10 Enterprise |
| Browser | chrome |

**Comment by Mossimos** [comment]
use [App components](https://ant.design/components/app)

```
import { App } from 'antd';
<ConfigProvider theme={{ ... }}>
  <App>
    ...
  </App>
</ConfigProvider>
```

```
const { message} = App.useApp();
message.loading(....)

```

**Comment by MadCcc** [comment]
Ref: https://ant.design/components/config-provider#why-cant-configprovider-props-like-prefixcls-and-theme-affect-reactnode-inside-messageinfo-notificationopen-modalconfirm
