### ISSUE TITLE
Select Option not working as expected in form

### ISSUE THREAD

**Issue by Keyur1284** [ant-design/ant-design#44701]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dp8tmz)

### Steps to reproduce

Remake the whole component

### What is expected?

On clicking any option, the data value should be set 

### What is actually happening?

I'm not even able to click on any option

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | react vite |
| System | DELL |
| Browser | Brave, Edge, Chrome |

**Comment by Yuiai01** [comment]
In the codesandbox you provided, `form` is disabled, so `select` not work.

**Comment by MadCcc** [comment]
> In the codesandbox you provided, `form` is disabled, so `select` not work.

+1, any more details?
