### ISSUE TITLE
5.8.6 FloatButton.Group 中 FloatButton 一旦使用 href 方式会导致 按钮挤在一起 

### ISSUE THREAD

**Issue by Mossimos** [ant-design/ant-design#44700]
### Reproduction link

[https://codepen.io/ssiMo-Mo/pen/jOXywJW?editors=001](https://codepen.io/ssiMo-Mo/pen/jOXywJW?editors=001)

### Steps to reproduce

<FloatButton.Group shape="circle" style={{ right: 40 }}>
                <FloatButton
                    tooltip="GitHub 仓库"
                    href="https://xxxxxxxxxxx"
                    target="_blank"
                    icon={<GithubIcon />}
                />

                <FloatButton
                    tooltip="切换主题"
                    onClick={() => changeThemeModel(!isDark)}
                    icon={
                        isDark ? (
                            <Icon style={{ fontSize: 18 }} component={Light} />
                        ) : (
                            <Icon style={{ fontSize: 18 }} component={Dark} />
                        )
                    }
                />
                <FloatButton.BackTop tooltip="回到顶部" visibilityHeight={500} />
            </FloatButton.Group>

### What is expected?

使用  href 浮动按钮正常显示

### What is actually happening?

使用  href 浮动按钮显示错误 挤在了一起

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | chrome 116.0.5845.179 |

**Comment by Yuiai01** [comment]
确实，在之前的版本中是有效的，我来跟一下～

**Comment by MadCcc** [comment]
少了个 `display: block`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/44587 的 ci 没检查出来，需要加个 image test

**Comment by Yuiai01** [comment]
> #44587 的 ci 没检查出来，需要加个 image test

偏右大佬，这个咋加啊

**Comment by MadCcc** [comment]
> 偏右大佬，这个咋加啊

按这个用例改一下 demo 就行

**Comment by Yuiai01** [comment]
> > 偏右大佬，这个咋加啊
> 
> 按这个用例改一下 demo 就行

好～
