### ISSUE TITLE
form数据同步到dva，行为异常

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design#4471]
#### Environment(required)

- antd version: 2.6
- OS and its version: win10 64
- Browser and its version: chrome 54.0.2840.99 m (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

使用 onFieldsChange 同步表单数据到 dva(state)

#### What do you expected?

数据正常同步过去，表单行为正常

#### What happen?

任意一个input，在输入数据的时候会触发 onFieldsChange , 导致 form 刷新，从而使正在输入的 input 失去焦点。也因为这个问题，导致不能输入中文

#### Re-producible online demo

无

**Comment by afc163** [comment]
烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zjxpcyc** [comment]
@afc163 dva 可以在 codepen 上使用吗？ 我不会啊

**Comment by afc163** [comment]
https://github.com/dvajs/dva/issues/451#issuecomment-269846501

**Comment by zjxpcyc** [comment]
@afc163  整理了下  
[http://codepen.io/yansen/pen/wgBLQx?editors=0010](http://codepen.io/yansen/pen/wgBLQx?editors=0010)

在任意的input框中都不能输入中文
我希望的是，Form数据能同步到 dva(Redux)， 这样在我现在的场景中，就不会因为用户的胡乱操作，导致他辛辛苦苦填的数据没有了。

**Comment by zjxpcyc** [comment]
我的 Form 初始数据来源是 dva 的 state，如果不做数据双向绑定，那么会造成，Form 数据在填写之后丢失的现象

**Comment by afc163** [comment]
看了半天没看出啥缘故，@sorrycc 一起来看看是否和 dva 有关。

**Comment by yesmeck** [comment]
你把  `const CFrom = create({ onFieldsChange })(CustForm)` 写在 `MyBizComponent` 里，`MyBizComponent` 以渲染就重现生成一个 `CFrom` 了，原来的 `CFrom` 就被  unmount 掉了，当然就没焦点了。

**Comment by zjxpcyc** [comment]
@yesmeck , 没看懂你的意思。
我刚刚按照你的方法，把 MyBizComponent 这个去掉了，也不行，你可以自己试试。
另外，我这边为什么要加这一层，因为，很多时候我的Form要公用的，然后在我不同的业务主键去调用。
我不可能，一个相同的 Form， 每个业务组件里面都实现一次。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/OWVJaZ?editors=0010

**Comment by yesmeck** [comment]
看我 fork 的例子 http://codepen.io/yesmeck/pen/ZLGEqg?editors=0010

抽象用 HOC，可以去了解下。

**Comment by zjxpcyc** [comment]
@yesmeck @afc163 谢谢两位大神
另外， HOC 是什么东东? 有链接吗？

**Comment by yesmeck** [comment]
自己用 react + HOC 搜一下吧，不过从你的例子完全没看出来 MyBizComponent 的作用。
