### ISSUE TITLE
[功能请求]: `<App />` 组件添加选项控制是否需要 DOM 元素和 .ant-app 样式重置

### ISSUE THREAD

**Issue by ziloen** [ant-design/ant-design#44716]
### What problem does this feature solve?

仅使用 `<App />` 为 message / modal / notification 提供 context 时，会附带不需要的 DOM 和样式重置

### What does the proposed API look like?

```tsx 
<App abstract={boolean}>
  {...}
</App>
```

**Comment by zombieJ** [comment]
App 会提供额外的样式，比如链接、字号等等。如果没有 dom 节点，样式就注不进去了

**Comment by ziloen** [comment]
@zombieJ 其实就是不需要额外样式，但是又想使用 `App.useApp` 功能

**Comment by MadCcc** [comment]
`component`
