### ISSUE TITLE
Form.List内的组件重复卸载和加载

### ISSUE THREAD

**Issue by yumi-d** [ant-design/ant-design#44714]
### Reproduction link

[https://stackblitz.com/edit/react-xlntks-df22dx?file=demo.tsx](https://stackblitz.com/edit/react-xlntks-df22dx?file=demo.tsx)

### Steps to reproduce

1、打开浏览器控制台
2、通过  Add Sub Item按钮添加几条数据
3、删除第一条数据
4、看控制台打印的信息

### What is expected?

Form.List内的组件，非删除状态下不要重复卸载和加载

### What is actually happening?

Form.List内的组件，删除第一项，导致后面所有项重新卸载和加载，导致组件内部状态丢失和重复执行useEffect等副作用

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome116.0.5845.140 |

**Comment by MadCcc** [comment]
没有复现你描述的问题，有截屏看看么

**Comment by zombieJ** [comment]
结论：这是预期行为。

## 内部逻辑

删除第一项后，后面所有字段的 name 都会变化：

#### From

* [list, 0, second] ❌
* [list, 1, second]
* [list, 2, second]

#### To

* [list, 1, second] -> [list, 0, second]
* [list, 2, second] -> [list, 1, second]

## 原因

当字段发生变化时，Field 会被重置以对齐新的 `name` 值，防止子组件没有对 `undefined` 值进行受控逻辑处理导致的副作用。例如：

* item 0: 111
* item 1: 222
* item 2: `undefined`
* item 3: 333

在没有处理 `undefined` 的情况下，删除 `item 0` 会出现：

* item 0: 222
* item 1: 222（实际值为 `undefined`）
* item 2: 333

因为需要兜底这种情况，所以当 `name` 变化时，会强制重新渲染组件。

## 如果我确定不会有副作用可以怎么做？

可以直接实现一个自定义组件，将 `list` 作为 Form.Item 的值。然后内部进行管理。
