### ISSUE TITLE
Image点击整张图片都会触发预览，我希望点击特定按钮才会触发预览。

### ISSUE THREAD

**Issue by qingfengmy** [ant-design/ant-design#44726]
### What problem does this feature solve?

我的图片上还需要处理其他事件，比如点击选中，同时还希望有预览功能。

我希望有一个小按钮，只有点击按钮才触发预览，点击图片其他位置我自己处理事件。

### What does the proposed API look like?

<Image preview={{renderBtn: <Button>预览</Button>}}>

如果设置了renderBtn，就把预览事件加到这个btn上，而不是整个图片上

**Comment by linxianxi** [comment]
受控 visible 就行了

**Comment by MadCcc** [comment]
> 受控 visible 就行了

+1，ref: https://ant.design/components/image-cn#previewtype
