### ISSUE TITLE
Checkbox ref has a wrong type definition

### ISSUE THREAD

**Issue by LexiosAlex** [ant-design/ant-design#44725]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-chandrasekhar-yqn3wg?file=/src/App.tsx)

### Steps to reproduce

1) Import checkbox from ant.d 
2) Create a simple ReactRef for this component with the type of `HTMLInputElement`
3) Try to pass the ref to the component
4) Component receives this ref, but in fact the type is not valid, since the ref is not of type `HTMLInputElement` but type of `CheckboxRef` 

### What is expected?

The type for the `ref` should be correct `CheckboxRef` instead of `HTMLInputElement`

### What is actually happening?

Component receives this ref, but in fact the type is not valid, since the ref is not of type `HTMLInputElement` but in type of `CheckboxRef`

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | React |
| System | Desktop (Windows mac) |
| Browser | All the latest browser versions |

---
Looks like also this is also affects the `RadioButton`, the other antd input elements works fine, since there is a properly typed `InputRef`

**Comment by LexiosAlex** [comment]
I can raise PR if no one against it, since it looks like the issue coming from here
https://github.com/ant-design/ant-design/blob/master/components/checkbox/index.ts#L11C56-L11C56
 
The same we've got for `radio`
https://github.com/ant-design/ant-design/blob/master/components/radio/index.ts#L19C48-L19C48

**Comment by poyiding** [comment]
> I can raise PR if no one against it, since it looks like the issue coming from here https://github.com/ant-design/ant-design/blob/master/components/checkbox/index.ts#L11C56-L11C56
> 
> The same we've got for `radio` https://github.com/ant-design/ant-design/blob/master/components/radio/index.ts#L19C48-L19C48

you can PR  then antd team  will review it .
