### ISSUE TITLE
`Modal` missing contentStyle prop

### ISSUE THREAD

**Issue by bombillazo** [ant-design/ant-design#44722]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js)

### Steps to reproduce

1. Import Modal component
2. Try to add contentStyle prop to modify styling of the `ant-modal-content` div

### What is expected?

The ability to customize type of the modal content div like one can do with the mask and body

### What is actually happening?

The content div is not accessible for styling override via props

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | MacOS |
| Browser | All |

**Comment by kiner-tang** [comment]
We don't have `contentStyle` in modal, Maybe you mean `bodyStyle`? And the `bodyStyle` look like run unexpected in static mode and hooks mode now, let me try to fix it.

**Comment by bombillazo** [comment]
There is another component above body called content that is not accessible for styling. For some reasone the sandbox link did not save my changes and shows the template project code.

**Comment by MadCcc** [comment]
https://github.com/ant-design/ant-design/discussions/43372
