### ISSUE TITLE
全局探照灯效果

### ISSUE THREAD

**Issue by mushan0x0** [ant-design/ant-design#44733]
### What problem does this feature solve?

适合用在有边框的组件上，比如 Meue、Select、Input 和 Card 等，丰富动效，当组件更加现代。

### What does the proposed API look like?

像这个组件这样，深色主题下效果更好 https://ui.lobehub.com/components/features

https://github.com/ant-design/ant-design/assets/29084441/06834e9c-356e-433b-8f18-b3a90ea1ee9f

**Comment by mushan0x0** [comment]
配合这个 issues https://github.com/ant-design/ant-design/issues/44568 可以构建出更加现代的组件

**Comment by MadCcc** [comment]
这个设计便好有些重了

**Comment by zombieJ** [comment]
可以参考一下 https://ant-design.antgroup.com/docs/blog/config-provider-style-cn 做主题拓展。这个效果很赞，不过目前设计上应该暂时不会落。主要原因是边框渐变效果依赖于 css 实现，而这个是很难 token 化掉的。
