### ISSUE TITLE
Customize Layout, Sider and Header on ConfigProvider passing theme object

### ISSUE THREAD

**Issue by sschuf** [ant-design/ant-design#44732]
### Reproduction link

[https://u.ant.design/codesandbox-repro](https://u.ant.design/codesandbox-repro)

### Steps to reproduce

- pass object to ConfigProvider containing token, algorithm, components and inherit props. On components prop:
{ Layout: { headerBg: '#ff0000', headerHeight: 80  }}. Also adding "algorithm: true" does not change the component.

### What is expected?

To change the theme based on the theme object provided.

### What is actually happening?

By modifying the theme object does not reflect the change on the actual Layout component.

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | react |
| System | ubuntu |
| Browser | chrome |

**Comment by yoyo837** [comment]
There is no ConfigProvider in your Reproduction link.

**Comment by sschuf** [comment]
you're right, it works on codesand box, also started a new app and it works. I can not figure out why it does not work on my app. I will try to find it so I can share it with you.

**Comment by sschuf** [comment]
Found it. The bug is on version antd@5.8.6. But in 5.9.0 it works.

**Comment by sschuf** [comment]
Found it. The bug is on version antd@5.8.6. But in 5.9.0 it works.

**Comment by yoyo837** [comment]
> Found it. The bug is on version antd@5.8.6. But in 5.9.0 it works.

Layout token customization is supported starting from 5.9.0 https://github.com/ant-design/ant-design/issues/41884
