### ISSUE TITLE
DatePicker 抑制了 Form 的 submit 事件

### ISSUE THREAD

**Issue by Luncher** [ant-design/ant-design#44731]
### Reproduction link

[https://stackblitz.com/edit/react-hssuin?file=demo.tsx](https://stackblitz.com/edit/react-hssuin?file=demo.tsx)

### Steps to reproduce

在 text input 按下回车，form 的 submit 事件没有触发，如果把 DatePicker 注释掉则可以正常触发 submit 事件。

### What is expected?

不论表单里面有没有 DatePicker，在 text input 按下回车都可以正常触发 submit 事件。

### What is actually happening?

submit 事件无法触发触发 。

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | macOS |
| Browser | 版本 116.0.5845.179（正式版本） (arm64) |

**Comment by solitia7125** [comment]
这个不是antd的问题，type="text" 的控件只有一个的时候 type="submit" 可以隐性 type="text"多个的时候必须显性

**Comment by yoyo837** [comment]
It's it not antd problem.
