### ISSUE TITLE
Tooltip 文字提示是否可以提个pr加下文字颜色的api，因为背景设置浅颜色时固定的白色字体有些不明显

### ISSUE THREAD

**Issue by Now-Sprouting** [ant-design/ant-design#44749]
### What problem does this feature solve?

Tooltip 自定义文字颜色

### What does the proposed API look like?

<Tooltip textColor="red">

**Comment by zombieJ** [comment]
https://codesandbox.io/s/ji-ben-antd-5-8-6-forked-vwys3d?file=/demo.tsx
