### ISSUE TITLE
Virtual Table height is fixed when scroll.y is set and number of row items are little

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44748]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-5-9-0-forked-xdw2gc?file=/demo.tsx)

### Steps to reproduce

1. Create a virtual table
2. set scroll.y to 400
3. set data to 2 items
4. table height remains 400 even if the items doesnt take that much height

### What is expected?

scroll.y should only be triggered if the table rows exceed the specified number

### What is actually happening?

scroll.y is applied regardless of number of row items

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
![image](https://github.com/ant-design/ant-design/assets/52765572/d2ee0689-7d50-4396-93e2-11f059f0144a)

**Comment by 1123612483** [comment]
#44785
