### ISSUE TITLE
modal 导致浏览器滚动条无法使用

### ISSUE THREAD

**Issue by wm3445** [ant-design/ant-design#4475]
我发现 modal 显示的时候会增加style overflow: hidden; 关闭的时候会去掉这个style。
但是如下使用会导致无法去掉overflow: hidden; 

我为modal 组件 增加了key属性 当我提交form添加数据成功，更新state给这个key +1 这样modal 里的form表单就清空了，但是这样操作会导致无法去掉overflow: hidden; 

之前也考虑过resetFields 但是出现的效果为 我点击确认按钮loading 效果为true，服务器返回正确操作后 关闭modal，这样会出现 form清空，在提示操作成功，这样效果是不行，所以我用了上面这个特殊的方法。

**Comment by afc163** [comment]
看描述这里应该已经修复了：https://github.com/react-component/dialog/pull/45

尝试更新到最新版本且重新安装 node_modules。

若仍未修复，麻烦给出可重现的演示：http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
@wm3445

**Comment by qq645381995** [comment]
@afc163  我也遇到这个问题了 我是在modal弹出来点击提交 之后 router跳转别的页面之后就没有滚动条的 我试着更新最新版的antd  还是不行

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by qq645381995** [comment]
@afc163   react-touer 在 codepen  怎么使用？

**Comment by qq645381995** [comment]
@afc163   我写出来了 http://codepen.io/qq645381995/pen/VPvmbV?editors=0010

但是我发现问题不在antd上面了 在 ruter上面
这个用的是router的api  withRouter 然后 router.push  跳转的 
但是我的项目中直接用的browserHistory.push 滚动条才会没有

**Comment by afc163** [comment]
对的，直接用 browserHistory.push 不会触发 React 的生命周期，就没有办法触发 https://github.com/react-component/dialog/pull/45/files#diff-dd3f1f5b1f6a20cb423e56371a864c8cR105 这里的代码。

**Comment by qq645381995** [comment]
但是 

```
   this.setState({
                visible: false,
            },function () {
                this.props.router.push('/home');
            });
```

好像滚动条还是没有 这个是什么原因呢？

**Comment by afc163** [comment]
@ddcat1115 再挖一下吧，@qq645381995 提供的例子很清晰。

**Comment by ddcat1115** [comment]
感觉是这里的判断导致的： https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L107

首先有两个条件都可以触发去掉 `overflow: hidden` 的操作：

1. 组件卸载
2. visible 变为 false 触发 onAnimateLeave，因为有动效，这里从 visible -> false 到真正的 remove overflow之间其实有一段时间

给出的 demo 里，先把 visible 设置为 false（但 overflow 还没有 remove），此时组件卸载，所以并未执行componentWillUnmount 里的 removeScrollingEffect，然后跳转，overflow 得以保留...

@qq645381995 可以试下在例子里的 `handleVCode` 中直接调用 `this.props.router.push('/home');` 是ok的

@afc163 感觉这里的判断可以去掉  https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L107

**Comment by afc163** [comment]
👌

**Comment by qq645381995** [comment]
@ddcat1115  直接调用是可以的  但是我后来加上 setTimeout试了下 
现在  codepen 502了  没法看了
