### ISSUE TITLE
Layout 组件 Token 补全

### ISSUE THREAD

**Issue by consistent-k** [ant-design/ant-design#44755]
### What problem does this feature solve?

补充Header & Trigger的Token
目前只有深色的Token 没有亮色的Token，在做主题开发时比较麻烦。
![image](https://github.com/ant-design/ant-design/assets/67736912/51dddb0d-a677-46b7-885a-1c66814dea51)

### What does the proposed API look like?

支持 LightHeaderBg & LightHeaderColor & LightTriggerColor

**Comment by MadCcc** [comment]
只有 Sider 才有 theme，这里的 token 应该已经覆盖到了

**Comment by consistent-k** [comment]
> 只有 Sider 才有 theme，这里的 token 应该已经覆盖到了

![image](https://github.com/ant-design/ant-design/assets/67736912/8ae7c390-e3b9-4a86-8c68-7e1b3b1d5fd4)
好像我看错了 但是我感觉这部分也应该支持theme啊，这个示例内部的menu是支持的，Header确实没有 这个后面会考虑加一下吗

**Comment by MadCcc** [comment]
Menu 有 theme 属性，header 暂时没有计划支持，可以世界通过 `headerBg` 和 `headerColor` 修改
