### ISSUE TITLE
ant.design Upload组件 accept=".tar.gz"后缀时，mac电脑上上传文件找不到，显示是置灰状态 

### ISSUE THREAD

**Issue by lijun-wu** [ant-design/ant-design#44764]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

const { createRoot } = ReactDOM;

const {  UploadOutlined  } = icons;
const {  Button, message, Upload  } = antd;
const props = {
  name: 'file',
  action: 'https://www.mocky.io/v2/5cc8019d300000980a055e76',
  headers: {
    authorization: 'authorization-text',
  },
  accept:".tgz, .tar.gz",
  onChange(info) {
    if (info.file.status !== 'uploading') {
      console.log(info.file, info.fileList);
    }
    if (info.file.status === 'done') {
      message.success(`${info.file.name} file uploaded successfully`);
    } else if (info.file.status === 'error') {
      message.error(`${info.file.name} file upload failed.`);
    }
  },
};
const App = () => (
  <Upload {...props}>
    <Button icon={<UploadOutlined />}>Click to Upload</Button>
  </Upload>
);
const ComponentDemo = App;

createRoot(mountNode).render(<ComponentDemo />);

### What is expected?

mac笔记本上，上传文件时支持accpet=“.tar.gz” 后缀的文件

### What is actually happening?

mac笔记本上，上传文件时支持accpet=“.tar.gz” 后缀的文件，被禁用了，不支持选择

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 18.2.9 |
| System | macOS Big Sur |
| Browser | 116.0.5845.140 |

---
随便拿一个苹果电脑，都可以测试出这个问题

**Comment by yoyo837** [comment]
原生效果如此, 你多加个`*` => `*.tar.gz`, 应该不难吧!

**Comment by slp1608** [comment]
accept:".tgz, .tar.gz", 改成 accept:".tgz, application/gzip"。.tar.gz浏览器不支持，需要改成 application/gzip
