### ISSUE TITLE
Table表格虚拟滚动

### ISSUE THREAD

**Issue by 4brother** [ant-design/ant-design#44765]
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn#components-table-demo-virtual-list](https://ant-design.antgroup.com/components/table-cn#components-table-demo-virtual-list)

### Steps to reproduce

用shift 鼠标滚轮进行横向滚动

### What is expected?

shift 鼠标滚轮可以横向滚动

### What is actually happening?

无法用shift 鼠标滚轮进行横向滚动

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | win10 |
| Browser | 最新 |

---
另外Table的Api文档未说明virtual参数

**Comment by afc163** [comment]
@zombieJ 文档要先补一下。
