### ISSUE TITLE
升级2.6.0后Table组件的最右边多出了空白

### ISSUE THREAD

**Issue by since1987** [ant-design/ant-design#4476]
但是table自带的分页器是靠右对齐了，
就是说 table的主体的最右边应该和分页器的最右边是对齐的（或者说table的主体的最右边应该跟浏览器的最右边是靠近的），但是现在只有分页器是靠右的，table主体的里浏览器的最右边有很大一片空白

**Comment by yesmeck** [comment]
重现 demo http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
没有重现只能关了，有重现就再 reopen 吧。:smiley:
