### ISSUE TITLE
TreeSelect 报Invalid prop `value` supplied to `TreeSelect`错误提示

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#44767]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-9-0-forked-hv8r77?file=/demo.tsx:767-777)

### Steps to reproduce

打开链接后，F12审查元素，随便选择一个多选框，勾选就行，只有第一次报错，后续不会继续报错。

### What is expected?

去掉这个错误

### What is actually happening?

虽然报错，但是不影响使用。

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | react 18 |
| System | Windows 10 |
| Browser | Chrome 104.0.5112.102 |

![Snipaste_2023-09-11_18-08-55](https://github.com/ant-design/ant-design/assets/17424034/5e275173-54db-4191-8f75-89f5ffcbc18a)

**Comment by zombieJ** [comment]
就如 warning 告诉你的，你传入的 `value` 不对。代码中通过 `getValueFromEvent` 转换了 `value` 而在 `treeCheckStrictly` 下需要提供的是 `labelInValue` 类型哈~
