### ISSUE TITLE
Casacader 存在多选状态，子项存在disabled时，选择所有非禁用选项后会默认选择父级

### ISSUE THREAD

**Issue by heyyybingo** [ant-design/ant-design#44776]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cascader-disabled-tag-2t8r9z)

### Steps to reproduce

页面上存在两个cascader选择器（first，last），两个选择器的value应当互斥。
1.在first，选中A下的a选项
2.此时last的选项中，选中A下的a选项被禁用
3.在last，选中A下的b选项

（由于onChange的value在第3步只返回了父级，导致第3步的值可能变成A，所以这里做了处理，展开成了A-b）

### What is expected?

first选择框显示a
last选择框显示b

### What is actually happening?

first与last选择框都显示A，存在歧义
（当存在disabled时，部分选择变成了父级）

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.x |
| System | macos |
| Browser | chrome |

---
业务场景：期望创建两种区域（区域为省-市），第一种为可配送，第二种为不可配送，这两者的选择是互斥的，因此当我选择A省a市为可配送后，A省a市则不可被选择为不可配送的。

https://github.com/ant-design/ant-design/issues/34193 我阅读了该issue，但当时的解决方案是添加了showCheckedStrategy，全部显示子节点或者全部显示父节点。由于市区等子项毕竟多，展示会比较凌乱，所以显示全部子节点可能不是一个好的方法。默认的SHOW_PARENT似乎也存在歧义

能否在Cascader中增加showCheckedStrategy，或者是其他方法，当子元素存在disabled时，部分选择不变成父级

**Comment by afc163** [comment]
可以配合 displayRender 来处理。

https://codesandbox.io/s/cascader-disabled-tag-forked-pch2ms?file=/src/App.js

不过上面这个例子只处理了最简单的情况，更多逻辑需要进一步自行实现了。

**Comment by MadCcc** [comment]
Ref: https://ant.design/docs/blog/check-conduct-cn
