### ISSUE TITLE
Form.Item 组件内使用插槽不换行报错

### ISSUE THREAD

**Issue by 1517607397** [ant-design/ant-design#44788]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8qshnl?file=/index.tsx)

### Steps to reproduce

点击提交按钮，可发现 Input 组件无法正常使用。

### What is expected?

正常使用

### What is actually happening?

无法正常使用

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | ^18.2.0 |
| System | Windows 11 专业版 |
| Browser | 116.0.5845.180 (正式版本) （64 位） (cohort: Stable)  |

---
这个问题可能和 JSX 语法有关系。

这个问题将antd切换到 5.9.0 时，依旧存在。

**Comment by zombieJ** [comment]
空格也是一个元素，在警告里已经告诉你了。children 节点不唯一：

<img width="692" alt="截屏2023-09-12 17 11 03" src="https://github.com/ant-design/ant-design/assets/5378891/fbf1ece4-3b24-4497-8626-a0e6b81df6ed">

**Comment by yoyo837** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/42092
