### ISSUE TITLE
[5.9.0+]table的components重写header只能在非虚拟table中生效，我希望在虚拟table也可以生效。

### ISSUE THREAD

**Issue by congshu-du** [ant-design/ant-design#44787]
### What problem does this feature solve?

通过重写th，使用react-draggable拖拽修改列宽

### What does the proposed API look like?

希望能尽快支持

**Comment by afc163** [comment]
现在是具体什么代码不生效，有重现不？

**Comment by boy-in** [comment]
我也遇到类似问题

**Comment by cjtcjt999** [comment]
If this cannot be solved, the leader will also let me go

**Comment by yoyo837** [comment]
`components.body` not support in virtual table. See https://github.com/ant-design/ant-design/discussions/41500

**Comment by cheese0409** [comment]
will it going to support? or could anyone help to give a demo about how to achieve row editing using virtual table? thanks in advance

**Comment by cheese0409** [comment]
> will it going to support? or could anyone help to give a demo about how to achieve row editing using virtual table? thanks in advance

will it going to support? or could anyone help to give a demo about how to achieve row editing using virtual table? thanks in advance

**Comment by cheese0409** [comment]
> Virtual tables do not support `components.body`. See #41500

@yoyo837 are we going to support customized body row & cell? or could anyone help to give a code demo about how to achieve row editing when using virtual table? thanks in advance

**Comment by yoyo837** [comment]
> > Virtual tables do not support `components.body`. See #41500
> 
> @yoyo837 are we going to support customized body row & cell? or could anyone help to give a code demo about how to achieve row editing when using virtual table? thanks in advance

No, We not consider implementing it.

**Comment by yoyo837** [comment]
Now, here's some new news about it https://github.com/react-component/table/pull/1069
