### ISSUE TITLE
虚拟table中，columns 中的render方法第三个参数应该是index, 现在第三个获取的值是undefine。table的components重写header只能在非虚拟table中生效，我希望在虚拟table也可以生效

### ISSUE THREAD

**Issue by congshu-du** [ant-design/ant-design#44783]
### What problem does this feature solve?

我们使用的是虚拟滚动。希望可以实现拖拽修改列宽的功能。

### What does the proposed API look like?

希望可以内置拖拽列的功能

**Comment by congshu-du** [comment]
table的components重写header只能在非虚拟table中生效，我希望在虚拟table也可以生效。这个可以改吗？

**Comment by yoyo837** [comment]
> table的components重写header只能在非虚拟table中生效，我希望在虚拟table也可以生效。这个可以改吗？

挂个新issue吧, 这是内置表格虚拟唯一冲突的点, 因为 虚拟表格依赖components实现的.

有兴趣可以PR试试看能不能解决.

**Comment by congshu-du** [comment]
好的，我挂个新的issue，我之前是通过覆盖header 使用react-draggable实现的拖拽修改列宽，在现在的版本，虚拟列表我可以实现这个功能吗。望告知！
