### ISSUE TITLE
v0.92 组件缺失

### ISSUE THREAD

**Issue by joesonw** [ant-design/ant-design#448]
`npm install antd -S` 安装出来缺少不少组件, `npm cache clean` 之后安装也一样.
![image](https://cloud.githubusercontent.com/assets/1635441/10812868/4ffb1968-7e55-11e5-8791-c7099d9ca12b.png)

**Comment by afc163** [comment]
#439 #434

**Comment by joesonw** [comment]
看了以前写的代码,是用的`<button ></button>`,建议这种涉及调用的改动,文档分离出来.

**Comment by afc163** [comment]
#434 (comment) 这里提到了 http://09x.ant.design/
