### ISSUE TITLE
下拉选择value和onChange类型声明

### ISSUE THREAD

**Issue by HankWang1999** [ant-design/ant-design#44804]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-12-forked-7spgmd?file=/package.json)

### Steps to reproduce

无重现步骤，不属于阻塞开发的问题

### What is expected?

如果不使用labelInValue这个属性，会导致onChange函数的入参类型和value类型对不上的情况，CI扫描无法通过

### What is actually happening?

value和onChange入参的类型可以不一样

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.0.0 |
| System | macos 13.2.1 (22D68) |
| Browser | 116.0.5845.140 |

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/ade12bd8-c085-4a7e-b9c3-4d90e33beb22)
不开启 `labelInValue` 时 value 类型就不能是对象
