### ISSUE TITLE
官网 https://ant.design/components/config-provider-cn 显示异常

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#44806]
### Reproduction link

[https://ant.design/components/config-provider-cn](https://ant.design/components/config-provider-cn)

### Steps to reproduce

无

### What is expected?

无

### What is actually happening?

<img width="1382" alt="image" src="https://github.com/ant-design/ant-design/assets/37385554/a8881a11-d9ca-473b-9372-c1894c241188">

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | react@18.2.0 |
| System | macOS 13 |
| Browser | chrome 108.0.5359.124 |

**Comment by MadCcc** [comment]
网络问题，国内用户推荐访问镜像：https://ant-design.antgroup.com/index-cn
