### ISSUE TITLE
虚拟table在数据量少的时候会出现左右滑动的时候只有header跟着滚动，body不动的情况

### ISSUE THREAD

**Issue by congshu-du** [ant-design/ant-design#44813]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xu-ni-lie-biao-antd-5-9-0-forked-wdg63t?file=/demo.tsx)

### Steps to reproduce

左右滑动就可以复现

### What is expected?

期望尽快修复

### What is actually happening?

只有header跟着滚动，body不动的情况

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.1 |
| System | mac最新 |
| Browser | chrome最新 |

**Comment by zombieJ** [comment]
怎么操作？来个 gif 看看

**Comment by congshu-du** [comment]
刚刚数量写错了，你重写点一下连接，左右滑动就可以复现

**Comment by congshu-du** [comment]
重新点一下连接

**Comment by zombieJ** [comment]
https://codesandbox.io/s/xu-ni-lie-biao-antd-5-9-0-forked-cdspv8?file=/package.json

更新一下依赖，这个已经修过了哈~
