### ISSUE TITLE
暗黑模式下，Modal不生效

### ISSUE THREAD

**Issue by fybchristasker** [ant-design/ant-design#44810]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jing-tai-que-ren-dui-hua-kuang-antd-5-9-0-forked-4yc3tk)

### Steps to reproduce

暗黑模式下，点击按钮打开弹窗，深色背景未生效

### What is expected?

弹窗背景为暗黑模式背景

### What is actually happening?

仍为浅色背景

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.0.0 |
| System | macos13.2.1 |
| Browser | chrome |

---
不清楚是故意设计，还是bug

**Comment by fybchristasker** [comment]
<img width="713" alt="image" src="https://github.com/ant-design/ant-design/assets/46596982/8ffdcb3d-6041-4d39-815f-c1af63176665">

**Comment by Wxh16144** [comment]
<img width="1516" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/806a124f-33da-4ad2-b521-1bce2841ceca">

**Comment by afc163** [comment]
@ideaviewes 来个在线重现看看
