### ISSUE TITLE
Select、DatePicker等这类组件在chrome58版本报错 Warning: `NaN` is an invalid value for the `left` css style proper

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#44819]
### Reproduction link
chrome 各个版本下载地址
[https://vikyd.github.io/download-chromium-history-version/#/](https://vikyd.github.io/download-chromium-history-version/#/)

### Steps to reproduce

下载提供的示例代码，用chrome 58版本打开，访问路由地址http://localhost:8000/#/zujian，点击日期控件就行

### What is expected?

能够实现定位并且在相应位置渲染出组件

### What is actually happening?

点击报错 Warning: `NaN` is an invalid value for the `left` css style proper

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | react 18 |
| System | Windows 10 |
| Browser | Chrome 58.0.2988.0 (64-bit) |
[pcts.zip](https://github.com/ant-design/ant-design/files/12593928/pcts.zip) | 下载包在这里

**Comment by zombieJ** [comment]
可以尝试使用兼容样式：
https://ant-design.antgroup.com/docs/react/compatible-style-cn

另外，antd 兼容是有版本约束的。过于老旧的版本不会提供技术支持哈：

<img width="618" alt="截屏2023-09-13 14 11 16" src="https://github.com/ant-design/ant-design/assets/5378891/c14baec4-d89e-43fe-8f6d-531bf5399a68">
