### ISSUE TITLE
Table组件增加单元格tooltip功能

### ISSUE THREAD

**Issue by li1870959** [ant-design/ant-design#44820]
### What problem does this feature solve?

自适应表格内容宽度时，支持文本超出显示省略号而不换行

### What does the proposed API look like?

类似于Element-ui  el-table组件的show-overflow-tooltip 参数  可设置为true |  false

**Comment by li1870959** [comment]
是否可以支持 ToolTip组件

**Comment by afc163** [comment]
你需要 https://ant.design/components/table-cn#components-table-demo-ellipsis-custom-tooltip ？
