### ISSUE TITLE
Click event of <Tree> node which with empty title is not trigged

### ISSUE THREAD

**Issue by ooPG233** [ant-design/ant-design#44826]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tree-kf7pck?file=/demo.tsx)

### Steps to reproduce

Click the empty title node

### What is expected?

The click event of empty title or the title only contain space string will be trigged

### What is actually happening?

The click event or the contextmenu event is not trigged

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
You need to give height to you component: https://codesandbox.io/s/tree-forked-7zt8kq

**Comment by ooPG233** [comment]
> You need to give height to you component: https://codesandbox.io/s/tree-forked-7zt8kq

Thanks for your help!
