### ISSUE TITLE
When clicking on the Label of Form.Item, Input will focus

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#44821]
### Reproduction link

[https://ant.design/components/form](https://ant.design/components/form)

### Steps to reproduce

1. Go to https://ant.design/components/form
2. Click on the title of Form.Item
3. Input was focus (Not most Forms)

### What is expected?

I want this action to be prevented, because on mobile devices when I click on the Input tooltip it will get focus

### What is actually happening?

When clicking on the Label of Form.Item, Input will focus

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | Macbook Air M1 2020 - macOS 13.3.1 |
| Browser | Chrome 112.0.5615.137 |

**Comment by zombieJ** [comment]
It's native html behavior to link label with input component. You can call `preventDefault` to ignore it.

**Comment by archisketch-thangly** [comment]
> It's native html behavior to link label with input component. You can call `preventDefault` to ignore it.

@zombieJ Do you have any demos on preventing focus when clicking on a label?

**Comment by archisketch-thangly** [comment]
It seems that hovering on labels is also inconsistent

https://github.com/ant-design/ant-design/assets/105255382/5eb34c93-cc84-497b-a841-ec8d337cb356
