### ISSUE TITLE
Typography.Paragraph single line ellipsis is broken

### ISSUE THREAD

**Issue by zhouzhonghao** [ant-design/ant-design#44824]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8jhtkj)

### Steps to reproduce

1. insert &lt;br/&gt; tag into a Typography.Paragraph component.

### What is expected?

The single line ellipsis should be valid.

### What is actually happening?

The single line ellipsis is broken.

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | react 18.2.0 |
| System | macOS Ventura 13.4 |
| Browser | chrome 116.0.5845.179 |

**Comment by MadCcc** [comment]
Native ellipsis do not support `<br/>` to break lines. You can declare `ellipsis.suffix` or `ellipsis.row` to enable manual ellipsis.
https://codesandbox.io/s/antd-reproduction-template-forked-m5vvr2?file=/index.js

**Comment by zhouzhonghao** [comment]
Thanks for your solution.
