### ISSUE TITLE
虚拟table，checkbox 多选选中状态下，整行选中色没有。hover颜色也没有

### ISSUE THREAD

**Issue by congshu-du** [ant-design/ant-design#44823]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xu-ni-lie-biao-antd-5-9-0-forked-wdg63t?file=/demo.tsx)

### Steps to reproduce

hover 整行，选中都不变色

### What is expected?

希望和非虚拟table保持一致

### What is actually happening?

实际是没有颜色变化

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.1 |
| System | mac最新 |
| Browser | chrome最新 |

**Comment by congshu-du** [comment]
兄弟，你们什么时候发下一个antd的版本？

**Comment by yoyo837** [comment]
> 兄弟，你们什么时候发下一个antd的版本？

https://ant.design/changelog-cn#%E5%8F%91%E5%B8%83%E5%91%A8%E6%9C%9F

**Comment by congshu-du** [comment]
我遇到一个问题想请教一下，我是mac,chrome, 虚拟table 左右滚动的时候偶尔会出现滑的时候, 触发了chrome的上一步下一步操作，从而出现不能正常滚动，出现的还挺频繁的。你们遇到类似的问题了吗？怎么解决的。
