### ISSUE TITLE
Backdrop component

### ISSUE THREAD

**Issue by RezaGhx** [ant-design/ant-design#44829]
### What problem does this feature solve?

Does antd have a component like mui Backdrop component which can be used as the suspense's fallback loading component.

### What does the proposed API look like?

https://mui.com/material-ui/api/backdrop/

**Comment by MadCcc** [comment]
Is this component enough? https://ant.design/components/spin

**Comment by afc163** [comment]
We could make a `<Spin fullscreen />`. @MadCcc

**Comment by li-jia-nan** [comment]
举手！我来做

**Comment by RezaGhx** [comment]
> Is this component enough? https://ant.design/components/spin

I don't think so cause it won't behave like a built-in full screen loading.

**Comment by RezaGhx** [comment]
> We could make a `<Spin fullscreen />`. @MadCcc

thank you so much!

**Comment by Rafael-Martins** [comment]
Hey guys, I started an implementation, it's not ready yet but it's working, I will finish it in a few!

**Comment by li-jia-nan** [comment]
> Hey guys, I started an implementation, it's not ready yet but it's working, I will finish it in a few!

Thank you for your contribution, however we are still waiting for the results of the discussion with the designers

**Comment by Rafael-Martins** [comment]
> > Hey guys, I started an implementation, it's not ready yet but it's working, I will finish it in a few!
> 
> Thank you for your contribution, however we are still waiting for the results of the discussion with the designers

Oh, ok, let me know if I can help, I will post here my current implementation, it's exact like the material-ui one but with the Spin component! :smile: 


https://github.com/ant-design/ant-design/assets/27746333/dd699000-3f42-4cc7-bbff-130309c799a1

Let me know if we gonna do something similar to this and I can change/refine this implementation!

**Comment by RezaGhx** [comment]
I'm sorry I wasn't notified about this updates. Is this available now?

**Comment by Rafael-Martins** [comment]
> I'm sorry I wasn't notified about this updates. Is this available now?

Hey @RezaGhx, I'm with a pr open waiting the final review, the design decided few days ago about it and I did the changes yesterday! :smile:

PR: #44986

**Comment by RezaGhx** [comment]
> > I'm sorry I wasn't notified about this updates. Is this available now?
> 
> Hey @RezaGhx, I'm with a pr open waiting the final review, the design decided few days ago about it and I did the changes yesterday! 😄
> 
> PR: #44986

just checked it out. thanks!
