### ISSUE TITLE
同时使用rowSelection，expandedRowRender（数据源是来自record.children字段）的时候

### ISSUE THREAD

**Issue by joker-yjc** [ant-design/ant-design#44838]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-swirles-l448wv?file=/index.js:1618-1635)

### Steps to reproduce

import React from "react";
import ReactDOM from "react-dom";
import { PlusCircleTwoTone, MinusCircleTwoTone } from "@ant-design/icons";
import "antd/dist/antd.css";
import "./index.css";
import { Table } from "antd";

const columns = [
  { title: "Name", dataIndex: "name", key: "name" },
  { title: "Age", dataIndex: "age", key: "age" },
  { title: "Address", dataIndex: "address", key: "address" },
  {
    title: "Action",
    dataIndex: "",
    key: "x",
    render: () => <a>Delete</a>
  }
];

const data = [
  {
    key: 1,
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
    description:
      "My name is John Brown, I am 32 years old, living in New York No. 1 Lake Park.",
    children: [
      {
        key: 2,
        name: "Jim Green",
        age: 42,
        address: "London No. 1 Lake Park",
        description:
          "My name is Jim Green, I am 42 years old, living in London No. 1 Lake Park."
      }
    ]
  },
  {
    key: 2,
    name: "Jim Green",
    age: 42,
    address: "London No. 1 Lake Park",
    description:
      "My name is Jim Green, I am 42 years old, living in London No. 1 Lake Park."
  },
  {
    key: 3,
    name: "Not Expandable",
    age: 29,
    address: "Jiangsu No. 1 Lake Park",
    description: "This not expandable"
  },
  {
    key: 4,
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    description:
      "My name is Joe Black, I am 32 years old, living in Sidney No. 1 Lake Park."
  }
];

ReactDOM.render(
  <Table
    columns={columns}
    dataSource={data}
    rowSelection={{}}
    expandable={{
      expandedRowRender: (record) => {
        if (record.children) {
          return (
            <Table
              pagination={false}
              dataSource={record.children}
              columns={columns}
            />
          );
        } else {
          return null;
        }
      }
    }}
  />,
  document.getElementById("container")
);

### What is expected?

expandIcon的位置偏移了

### What is actually happening?

expandIcon的位置应该在第一列的位置才对

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react 18 |
| System | mac os |
| Browser | 110 |

---
如果数据的来源字段名称不是叫children的话，就是正常显示的，但是个人觉得expandedRowRender的优先级应该更高会好一点吧

**Comment by afc163** [comment]
```diff
  expandable={{
+   childrenColumnName: 'NOT_EXISTED',
  }}
```

强制不走树形数据模式即可。
