### ISSUE TITLE
Upload 上传组件能否自定义上传后生成的缩略图长宽

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#44833]
### What problem does this feature solve?

目前看来上传的时候，生成的缩略图都是正方形的，有时候某个图片需要上传的是长方形，希望缩略图显示的是等比例的长方形。

### What does the proposed API look like?

增加两个参数 thumbWidth,thumbHeight，能够按照宽高生成缩略图

**Comment by zombieJ** [comment]
使用 `previewFile` 可以自定义预览逻辑
