### ISSUE TITLE
Nested Controlled Popover won't close when click away

### ISSUE THREAD

**Issue by RetroErised** [ant-design/ant-design#44830]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/dazzling-cray-fgkzk4)

### Steps to reproduce

- click button 1
- click button 2 in popover
- click away
popover content of button 2 won't close

### What is expected?

Content of nested Controlled Popover closes when click away.

### What is actually happening?

Content of nested Controlled Popover won't close when click away.

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome  117.0.5938.62 beta （64 位） |

**Comment by xuzhiqiang0723** [comment]
The new man always gives advice.I want to fix this bug.

**Comment by MadCcc** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-9-2-forked-ws4z94?file=/demo.tsx:83-87
Possible workaround

**Comment by zombieJ** [comment]
类 Tooltip 组件在关闭时会缓存内容以防止跳动代码：
```tsx
<Popover open={!!user} content={`Hello, ${user.name}`}  />
```

这使得关闭通过 state 更新的 `open` 也被缓存而无法关闭。需要提供一个额外属性来让它可以保鲜。
