### ISSUE TITLE
Select labelInValue loss label info when mode is tags 

### ISSUE THREAD

**Issue by pwpow** [ant-design/ant-design#44832]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-dong-fen-ci-antd-5-9-0-forked-5klmpr)

### Steps to reproduce

1.输入a
2.log输出value

### What is expected?

value中包含label信息

### What is actually happening?

value中不包含label信息

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18 |
| System | windows |
| Browser | Chrome 116.0.5845.179 |

**Comment by pwpow** [comment]
在4.16.13版本中是包含label信息的

**Comment by MadCcc** [comment]
4.24.x 已经没有了，以 4.x 最新版本最准哈，这个应该是后续更新时有意去掉的。

**Comment by pwpow** [comment]
> 4.24.x 已经没有了，以 4.x 最新版本最准哈，这个应该是后续更新时有意去掉的。

这里的变化有无相关说明可以学习一下呢

**Comment by MadCcc** [comment]
对于 tag 模式来说新增的选项 value 和 label 都是一致的，使用上应该不会存在缺少信息的问题

**Comment by pwpow** [comment]
> 对于 tag 模式来说新增的选项 value 和 label 都是一致的，使用上应该不会存在缺少信息的问题

因为存在使用tag模式并配置options的情况，在这时，选中选项与手动输入得到的value表现不一致，需要特殊处理，将输入得到的value补充对应label信息

**Comment by zombieJ** [comment]
因为 `tag` mod 下，用户输入的内容是只有 `value` 没有 `label` 的。为了和 `options` 区分。所以重构后就不填充 `label` 了哈。
