### ISSUE TITLE
antd-table开启vitrual会导致主题变量组件token的设置失效

### ISSUE THREAD

**Issue by fany2001** [ant-design/ant-design#44848]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rjrr9h?file=/index.js:1943-2058)

### Steps to reproduce

尝试注释和解注释 table的virtual&scroll属性

### What is expected?

组件row样式都被更改

### What is actually happening?

开启virtual后样式修改失效

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | macos13 |
| Browser | Chrome 116.0.5845.179（正式版本） (arm64) |

---
virtual模式下rowHover/rowSelected样式设置失效，这是因为开启虚拟列表后组件token修改样式无效，可能是加入rc-virtual-list后antd全局样式穿透失败导致样式setting失败

**Comment by zombieJ** [comment]
merge into #44823
