### ISSUE TITLE
新版本谷歌浏览器中Col组件包含Input的内容，点击Input不触发Col的点击事件

### ISSUE THREAD

**Issue by jun747093801** [ant-design/ant-design#44841]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z6fqty?file=/index.js)

### Steps to reproduce

点击Input组件，点击事件没有触发，输入框未变成非禁用状态

### What is expected?

输入框变为未禁用

### What is actually happening?

输入框未响应

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.2.0 |
| System | mac os13.3.1(a) |
| Browser | 116.0.5845.179 |

**Comment by CalmWeb** [comment]
这是浏览器更新版本之后的问题，input禁用状态，会阻止冒泡，临时方案可以通过在input上添加 pointer-events:none 属性解决，具体看截图![image](https://github.com/ant-design/ant-design/assets/33945645/ad661a4e-c8b3-4e9c-91a3-7989e265b0b8)

**Comment by afc163** [comment]
尊重浏览器行为吧，我实测 Mac 的 Firefox 下也是这个逻辑，antd 尽可能不去修改底层行为。

**Comment by LBJDJW** [comment]
还有解决方案嘛
