### ISSUE TITLE
Allow passing design 'token' at the component level

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#44842]
### What problem does this feature solve?

The `ConfigProvider` design tokens introduced in `5.x` offer a convenient way to customize component styles, but it does not support defining multiple "variants" of the same component.

Adding a `token` prop to each component would allow for even more control of component customization.

### What does the proposed API look like?

```tsx
export const DangerSwitch = (props: SwitchProps) => (
  <Switch token={{handleBg: 'red'}} {...props} />
);
```

**Comment by MadCcc** [comment]
Just wrap components in ConfigProvider:
```
<ConfigProvider theme={{ components: { Switch: {...}} }}>
  <Switch />
</ConfigProvider>
```

`theme` works with Provider of context, which is not suitable to implement in components.
