### ISSUE TITLE
Not able to auto-select the Added value in Custom Select in AntD

### ISSUE THREAD

**Issue by deepanshubhalotia** [ant-design/ant-design#44846]
### What problem does this feature solve?

This  will solve the problem like i am having, i have seen the past issues for this which have not been solved but are still closed!
I want when we add any custom value in the Select, the dropdown should select that and close the dropdown rightaway but it's not doing that, em not sure why!
This is the version i am using - "antd": "4.24.10"

### What does the proposed API look like?

I tried few things like setting it up through value prop on Select, but then it would always select the added value, won't give us the authority to select more options from dropdown!

**Comment by deepanshubhalotia** [comment]
Similar ask - https://github.com/ant-design/ant-design/issues/16751
Didn't get fulfilled though!

**Comment by MadCcc** [comment]
Why not set `value` after async options are rdy?

**Comment by deepanshubhalotia** [comment]
Tried Everything here

`const SearchSelect = ({query, createMutation, createType='String', val, placeholder, resultKey, displayKey, displayFn, keyFn, createLabel='Add Item', defaultValue = {}, readOnly, ...rest}) => {
  const { loading, data, refetch } = useQuery(query, { variables: { search: '', offset: 0, limit: 50 }})

  const debouncedRefetch = debounce(refetch, 250)
  const [addValueError, setAddValueError] = useState('');

  const display = ( value ) => {
    return displayFn ?
      displayFn(value || {}) :
      (value?.[(displayKey || 'name')] || '')
  }


  return(
    <>
      { readOnly && ( 
        <div style={{ color: '#1e4a71', fontSize: '16px', paddingTop: '7px' }} >
          { display(defaultValue || {}) }
        </div>
      )}
      { !readOnly && (
        <Select
          {...rest}
          value={val ? {key: keyFn ? keyFn(val) : val.id, label: display(val)} : undefined}
          defaultValue={defaultValue?.id ? {key: defaultValue?.id, label: display(defaultValue)} : undefined}
          placeholder={ placeholder }
          dropdownRender={menu => (
            <div>
              {menu}
              {addValueError && (
                // <div style={{ color: 'red', fontSize: '12px', paddingTop: '7px' }}>
                //   {addValueError}
                // </div>
                <Alert
                message={addValueError}
                type="error"
                showIcon
                style={{ marginBottom: '16px' }}
              />
              )}
              { !!createMutation && 

                <>
                  <Divider style={{ margin: '4px 0' }} />
                  <div style={{ padding: '10px' }}>
                    <RecordForm createMutation={ createMutation } createType={createType} displayKey={ displayKey } createLabel={ createLabel } refetch={ refetch } setAddValueError={setAddValueError}/>
                  </div>
                </>
              }
            </div>
          )}
          showSearch
          filterOption={false}
          labelInValue={true}
          optionLabelProp="label"
          notFoundContent={loading ? <Spin size="small" /> : "No Results Found"}
          onFocus={() => refetch({search: ''})}
          onSearch={(value) => {
            debouncedRefetch({search: (value || '')}) 
          }}
        >
          {data && data[resultKey] && data[resultKey].results.map(d => (
            <Option 
              value={keyFn ? keyFn(d) : (d?.id || display(d))}
              label={display(d)}>
              { display(d) }
            </Option>
          ))}
        </Select>
      )}
    </>
  )
}`

Nothing is working.
Do you have any recommendation?

**Comment by deepanshubhalotia** [comment]
Can you check if this sandbox works for you?

https://codesandbox.io/embed/custom-dropdown-antd-4-24-14-wfks8r?fontsize=14&hidenavigation=1&theme=dark

**Comment by MadCcc** [comment]
What do you expect in this reproduction?

**Comment by MadCcc** [comment]
You can do this yourself by controlling `value` and `open`

**Comment by MadCcc** [comment]
https://codesandbox.io/s/custom-dropdown-antd-4-24-14-forked-7dqvm6
