### ISSUE TITLE
table 选择行 删除之后再次勾选依然包含原来的删除过的 key

### ISSUE THREAD

**Issue by fedeoo** [ant-design/ant-design#4484]
- antd version: 2.5.1 
- OS and its version: MacOS
- Browser and its version: Chrome 55

table 组件，删除选中行。删除之后，再次勾选会包含原来选中的 key。比如，选择一行删除之后，再次勾选另一行，选中包含该两行。

期望只有当前选中行

**Comment by afc163** [comment]
A re-producible online demo will be helpful.

http://codepen.io/benjycui/pen/KgPZrE?editors=001
