### ISSUE TITLE
[table] fixed、ellipsis和scroll-x并存时，没有设置width的列宽度为0

### ISSUE THREAD

**Issue by lk0606** [ant-design/ant-design#44854]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dan-yuan-ge-zi-dong-sheng-lue-antd-4-24-12-forked-25w6gf?file=/demo.js)

### Steps to reproduce

点开链接，滑动滚动条即可复现

### What is expected?

没有设置宽度的列正常展示（或许列应该提供一个minWidth和maxWidth）

### What is actually happening?
 fixed、ellipsis和scroll-x都存在时。这里age宽度设置为600是为了复现问题，解决方式不是调下就可以了，需要考虑小屏幕情况，或宽度不足情况必现问题
1. scroll.x='100%'时，没有设置宽度的列消失不见
2. scroll.x='max-content'时，ellipsis和width均无效。
![image](https://github.com/ant-design/ant-design/assets/43233310/8689437d-21ae-4de4-b839-dc02bb4f1242)

| Environment | Info |
| --- | --- |
| antd | 4.x,5.x都会出现 |
| React | 16-18均无差别 |
| System | 无关系统版本 |
| Browser | 无关浏览器 |

**Comment by zombieJ** [comment]
`scroll.x` 传入的值是直接赋在内部的 Table 上。设置 `100%` or `max-content` 其实就是利用 css 的原生能力。如果你希望出现 column，`scroll.x` 设置固定值即可。当 Table 宽度小于你的 `scroll.x` 它自己是会撑满的。

**Comment by lk0606** [comment]
> `scroll.x` 传入的值是直接赋在内部的 Table 上。设置 `100%` or `max-content` 其实就是利用 css 的原生能力。如果你希望出现 column，`scroll.x` 设置固定值即可。当 Table 宽度小于你的 `scroll.x` 它自己是会撑满的。

@zombieJ 
- 从在线案例和描述来看，在不确定表格宽度是多少的情况下，scroll.x只能设置为100%，由此出现问题1。问题2也是这么来的。 这里是期望在不确定宽度的情况下，新增column.minWidth或column.maxWidth来确保列存在，并且使ellipsis生效。
- 从回答来看，为什么会添加`needs-more-info`这个标签呢，还需要提供什么信息呢
