### ISSUE TITLE
hover in dropdown 🐛 Bug

### ISSUE THREAD

**Issue by evn1054** [ant-design/ant-design#44853]
### Reproduction link

[https://ant.design/components/dropdown](https://ant.design/components/dropdown)

### Steps to reproduce

You can use the second example in https://ant.design/components/dropdown. When you select an item from dropdown, it will move to a new tab. Let's go back to the example and hover the cursor over dropdown. The hover status on the selected menu will remain. And this is unexpected because dropdown has closed.  I assume this is due to the attribute target="_blank"

### What is expected?

When you select an item from dropdown, it will move to a new tab. Let's go back to the example and hover the cursor over dropdown. The hover state at the selected point is reset.

### What is actually happening?

The hover status on the selected menu will remain. And this is unexpected because dropdown has closed. 

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | chrome |

**Comment by MadCcc** [comment]
Could not get reproduced. Any more details like screenshot?

**Comment by zombieJ** [comment]
Close since no more response.

**Comment by evn1054** [comment]
[`link with video of this bug`](https://disk.yandex.ru/i/yZpzCGFxCr1pGw) Sorry that I'm late
