### ISSUE TITLE
期望tabs能够支持自定义 moreIcon的位置

### ISSUE THREAD

**Issue by andyFang94** [ant-design/ant-design#44858]
### What problem does this feature solve?

该功能可以自定义更多 moreIcon的位置，能够个性化
目前好像只支持更改 moreIcon图标

### What does the proposed API look like?

在 TabBarExtraContent 改为 renderTabBarExtraContent: (props, { DefaultTabBarMoreDom }) => {} 
这里能够将moreIcon相关的dom作为参数传递过来

**Comment by afc163** [comment]
Closed in favor of https://github.com/ant-design/ant-design/pull/48321
