### ISSUE TITLE
树形的table中设置rowSpan会出现 异常现象，为什么会这样呢 

### ISSUE THREAD

**Issue by spademan** [ant-design/ant-design#4485]
#### Environment(required)

- antd version: 2.6
- OS and its version: osx 10.10
- Browser and its version: chrome 

#### Re-producible online demo
第330行代码 设置为1就正常 设置为大于1就不正常
http://codepen.io/spademan/pen/apzLYX

**Comment by spademan** [comment]
@ afc163 能帮忙看看吗

**Comment by spademan** [comment]
再给个简单点的例子 
http://codepen.io/spademan/pen/JEoVrr
@benjycui @afc163

**Comment by yesmeck** [comment]
http://codepen.io/spademan/pen/JEoVrr 

@spademan 这例子你期望的样子是什么样的？

**Comment by yesmeck** [comment]
生成的 DOM 结构没问题，例子里设置 rowSpan 逻辑就有点怪。

**Comment by spademan** [comment]
@yesmeck  我的初衷是想在 某个父级 td下设置 colspan 让他和子集的td合并显示.,某些不需要

**Comment by yesmeck** [comment]
rowSpan 是向下合并的，这里生成的 DOM 结果没错，你再想想怎么写吧。有问题再 open。

**Comment by spademan** [comment]
你可能没有仔细去 交互一下，我改了一下代码 展开树形结构和关闭树形结构 就能看到异常的排版了http://codepen.io/spademan/pen/JEoVrr

**Comment by yesmeck** [comment]
http://codepen.io/yesmeck/pen/dNoeed?editors=0010

自己根据 expandedKeys 去计算 rowSpan。

**Comment by spademan** [comment]
我也是差不多这个解决方式,不过你觉得不是设计缺陷的话 ....那就没什么好说了....辛苦了

**Comment by yesmeck** [comment]
你期望什么样的行为呢？
