### ISSUE TITLE
Form.List 中的表单 initialValue 被设置后，Form.List 无法被 reset

### ISSUE THREAD

**Issue by wangpengfeido** [ant-design/ant-design#44861]
### Reproduction link

[https://codepen.io/qbswddgk-the-styleful/pen/vYvZbEb?editors=0010](https://codepen.io/qbswddgk-the-styleful/pen/vYvZbEb?editors=0010)

### Steps to reproduce

https://codepen.io/qbswddgk-the-styleful/pen/vYvZbEb?editors=0010 页面中，点击 add field，然后点击 reset 按钮

### What is expected?

调用 from.resetFields() 之后，From.List 被清空。

### What is actually happening?

调用 from.resetFields() 之后，From.List 未被清空。

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | react18 |
| System | macos |
| Browser | chrome |

**Comment by yoyo837** [comment]
遵循浏览器默认行为, reset的意思是重制到默认, 如果你需要清空, 可以用setFieldsValue  API置空

**Comment by yoyo837** [comment]
Duplicate of #23341

**Comment by yoyo837** [comment]
指的是reset List item为默认的话, reopen 先...

**Comment by crazyair** [comment]
`Form.Item` 去掉 `initialValue`。默认值使用 `add` https://ant-design.antgroup.com/components/form-cn#operation

**Comment by Wxh16144** [comment]
这是不是一个解法？
<img width="983" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/b0e0637f-d334-4e38-adfd-81c290ea1019">

**Comment by wangpengfeido** [comment]
使用 add 默认值或者 Form.List 上的 initialValue 是可以解。
但想象这样的场景，FormList 下面有很多特别复杂的表单项，我把这些表单项封装成了一个组件，我希望这些表单项的初始值逻辑能在封装的这个组件内完成，而不希望在它的外部完成。

**Comment by yoyo837** [comment]
> Form.List

做成一套,A,B组件, 一起封装Form.List  + 若干表单项呢?

**Comment by wangpengfeido** [comment]
> > Form.List
> 
> 做成一套,A,B组件, 一起封装Form.List + 若干表单项呢?

如果是再复杂的场景，Form.List 下面有 n 坨表单，如果把这 n 坨怼到一起，那么这个表单将会变得巨大。或许每个子表单组件再另外导出个hook或者方法在外部设定初始值也是合理的。

回到问题的本身吧。「Form.List 的子表单存在 initialValue 时，Form.List 不会被清空」，如果这个是预期之内的表现的话，那这个 issue 可以关闭了，我会用其他方式实现我想要的能力。非常感谢~

**Comment by crazyair** [comment]
> 使用 add 默认值或者 Form.List 上的 initialValue 是可以解。
> 
> 但想象这样的场景，FormList 下面有很多特别复杂的表单项，我把这些表单项封装成了一个组件，我希望这些表单项的初始值逻辑能在封装的这个组件内完成，而不希望在它的外部完成。
> 
> 不知道是否合理。

这个场景我理解，不过默认值还是不要跟 Form.Item 绑定，在 Form.List add 配置 defaultValue 完全能满足。

对于特殊需要加载就设置默认值的，可以在 useEffect 中执行 form.setFields 设置默认值
