### ISSUE TITLE
Mentions组件在ios 原生键盘输入中文，选择中文后无法触发onSeach

### ISSUE THREAD

**Issue by into-piece** [ant-design/ant-design#44862]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z6lxtn?file=/index.js)

### Steps to reproduce

ios 原生键盘输入中文，输入的是英文字母的时候是有触发onSearch的，但是选中对应中文后没有触发onSearch

### What is expected?

能够在选中中文的时候触发onSearch

### What is actually happening?

没有触发onSearch

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 17.02 |
| System | ios |
| Browser | safari |

**Comment by into-piece** [comment]
![D6AF6A83-54D3-4516-BB29-E3A8DC9250CB](https://github.com/ant-design/ant-design/assets/23183463/42edb28f-0e48-4532-bfcb-199c9e1376e8)
<img width="1542" alt="0D72FED0-636A-4B92-9817-E1139B146436" src="https://github.com/ant-design/ant-design/assets/23183463/87f19f0b-addf-4789-b29f-ff464b046c86">

**Comment by zombieJ** [comment]
试了一下有的，有什么额外的操作么？

![Kapture 2023-09-19 at 11 17 21](https://github.com/ant-design/ant-design/assets/5378891/40b6fca5-25f5-4121-8bf8-a2601e4104be)

**Comment by into-piece** [comment]
> 试了一下有的，有什么额外的操作么？
> 
> ![Kapture 2023-09-19 at 11 17 21](https://user-images.githubusercontent.com/5378891/268831369-40b6fca5-25f5-4121-8bf8-a2601e4104be.gif) [ ![Kapture 2023-09-19 at 11 17 21](https://user-images.githubusercontent.com/5378891/268831369-40b6fca5-25f5-4121-8bf8-a2601e4104be.gif) ](https://user-images.githubusercontent.com/5378891/268831369-40b6fca5-25f5-4121-8bf8-a2601e4104be.gif) [ ](https://user-images.githubusercontent.com/5378891/268831369-40b6fca5-25f5-4121-8bf8-a2601e4104be.gif)

这个是在移动端ios设备输入触发onSearch api的吗

**Comment by into-piece** [comment]
ios版本 16.3
