### ISSUE TITLE
Tailwind classes being overwritten by antd styles in Next js 13 App router

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44866]
### Reproduction link

[https://ant.design/docs/react/use-with-next](https://ant.design/docs/react/use-with-next)

### Steps to reproduce

1. create a next js 13 app dir project with tailwind
2. install antd
3. Create layout with header
4. add tailwind height class
5. Antd style takes precedence over tailwind classes 

### What is expected?

classnames should override antd styles

### What is actually happening?

antd styles overriding explicit classnames

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2 |
| System | Next js 13 |
| Browser | chrome |

**Comment by AsuraKev** [comment]
![image](https://github.com/ant-design/ant-design/assets/52765572/695f2959-5925-4024-9d09-019733c8d879)

**Comment by AsuraKev** [comment]
Removing StyledComponentsRegistry seems to work. whats the purpose of StyledComponentsRegistry?

**Comment by MadCcc** [comment]
Without `StyledComponentsRegistry`, styles will not be generated in server rendering.

You have to try to raise the priority of tailwindcss, have you tried `important`?

**Comment by MadCcc** [comment]
Going to closing this issue due to nothing could be done with antd.

**Comment by liubin595338764** [comment]
@MadCcc  添加`important`是不对的，因为`tailwind`是原子css，开发者新增的每一个都是项目需要的，但是`antd`的自带样式可以是不要的，所以`tailwind`的优先级应该要高于`antd`样式；

**Comment by SSakibHossain10** [comment]
This is working for me

```
"use client";

import { createCache, extractStyle, StyleProvider } from "@ant-design/cssinjs";
import type Entity from "@ant-design/cssinjs/es/Cache";
import { useServerInsertedHTML } from "next/navigation";
import React from "react";

const StyledComponentsRegistry = ({ children }: React.PropsWithChildren) => {
  const cache = React.useMemo<Entity>(() => createCache(), []);
  const isServerInserted = React.useRef<boolean>(false);
  useServerInsertedHTML(() => {
    // avoid duplicate css insert
    if (isServerInserted.current) {
      return;
    }
    isServerInserted.current = true;
    return (
      <style
        id="antd-styles-for-SSR"
        dangerouslySetInnerHTML={{
          __html: extractStyle(cache, true),
        }}
      />
    );
  });

  const AntdStyles = document.querySelector("style#antd-styles-for-SSR");
  if (AntdStyles) {
    AntdStyles.innerHTML = ""; //remove for client-side cuz it overwrites tailwind css styles (it will be on server-side only)
  }

  return <StyleProvider cache={cache}>{children}</StyleProvider>;
};

export default StyledComponentsRegistry;

```
