### ISSUE TITLE
Time-picker 组件 clearText 属性不生效

### ISSUE THREAD

**Issue by Laffery** [ant-design/ant-design#44863]
### Reproduction link

[https://stackblitz.com/edit/react-gbifab?file=demo.tsx](https://stackblitz.com/edit/react-gbifab?file=demo.tsx)

### Steps to reproduce

选择一个时间，hover 在清除按钮上

### What is expected?

显示 clearText 文案

### What is actually happening?

未显示 clearText 文案

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | latest |
| System | MacOS 13.5.1 (22G90) |
| Browser | Google Chrome 版本 117.0.5938.62（正式版本） (arm64) |

**Comment by Yuiai01** [comment]
确实没显示，我来康康

**Comment by Yuiai01** [comment]
> 确实没显示，我来康康

这个属性应该是被删除掉了。
