### ISSUE TITLE
Menu dack 主题，非选中菜单字体颜色太过于接近背景色，难以可见

### ISSUE THREAD

**Issue by xnightsky** [ant-design/ant-design#4486]
![image](https://cloud.githubusercontent.com/assets/5158235/21678642/b78d6e3e-d37a-11e6-99dc-17cdecdc2231.png)

https://ant.design/components/menu-cn/

发生问题的环境是：

antd 版本: 2.6.0
操作系统及其版本:  osx 10.11.6 
浏览器及其版本: chrome 55.0.2883.95 (64-bit)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4440
