### ISSUE TITLE
The upload not work anymore. Stuck on "https://www.mocky.io/v2/5cc8019d300000980a055e76"

### ISSUE THREAD

**Issue by Mint2896395** [ant-design/ant-design#44872]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xh7544)

### Steps to reproduce

` <Upload
        name="avatar"
        listType="picture-circle"
        className="avatar-uploader"
        showUploadList={false}
        action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
        beforeUpload={beforeUpload}
        onChange={handleChange}
      >
        {imageUrl ? <img src={imageUrl} alt="avatar" style={{ width: '100%' }} /> : uploadButton}
      </Upload>`

this link not work anymore
https://www.mocky.io/v2/5cc8019d300000980a055e76

### What is expected?

the upload button it should show image after select image.

### What is actually happening?

but it shows loading... and then got 

> POST https://www.mocky.io/v2/5cc8019d300000980a055e76 net::ERR_FAILED 503 (Service Unavailable)

and when I try to get "https://www.mocky.io/v2/5cc8019d300000980a055e76"

it shows 
> This www.mocky.io page can’t be foundNo webpage was found for the web address: https://www.mocky.io/v2/5cc8019d300000980a055e76
HTTP ERROR 404

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | nextjs 13.4 |
| System | macOS |
| Browser | chrome |

**Comment by Mint2896395** [comment]
Thank you so much it work!!!

**Comment by OmilAgarwal** [comment]
Could you please guide me how can i solve this issue
