### ISSUE TITLE
Button background transition doesn't work when it's wrapped with Tooltip

### ISSUE THREAD

**Issue by lukasdruskis** [ant-design/ant-design#44871]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/type-antd-5-9-0-forked-pjsy3p?file=/demo.tsx)

### Steps to reproduce

Wrap a Button component with Tooltip Component

### What is expected?

Button transition should work even when Button is wrapped with Tooltip component

### What is actually happening?

Transition isn't working, also when overriding button style.

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | macOS Ventura Version 13.0.1 |
| Browser | Version 107.0.5304.110 (Official Build) (arm64) |

![image](https://github.com/ant-design/ant-design/assets/38437943/a6b5831a-cb5a-4c18-ac8f-028c77a3b9a9)

**Comment by Yuiai01** [comment]
It seems that when the disabled of the button inside the Tooltip becomes true, the Tooltip creates a span to wrap the buuton, causing the button to lose its transition.
<img width="797" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/fe9d3de8-7b49-4bea-a518-b81ff01fac01">

**Comment by MadCcc** [comment]
It's okay to remove this logic since trigger has been migrate to pointer eventes.
