### ISSUE TITLE
Table scroll virtualization axis Y bug  Important: This bug there is only with Vite ! If you use cra, all ok.

### ISSUE THREAD

**Issue by GeorgiyBeloklokov** [ant-design/ant-design#44870]
### Reproduction link

[https://github.com/GeorgiyBeloklokov/antd-issue-table.git](https://github.com/GeorgiyBeloklokov/antd-issue-table.git)

### Steps to reproduce

install Vite: 4.3.9, Yarn,  React :18.2.0  Antd: 5.9.0  Styled-components: 6.0.1 // in App.tsx place this code and npm run start 

### What is expected?

I have a box, it has 7 rows and 10 columns, I set the length of the rows to 1200 pixels and the height of the box to 500 pixels and expect a horizontal scroll to appear so that I can see the entire length of the rows

### What is actually happening?

when I set the height of the box (Y axis) to be greater than its content, there is no horizontal scroll and my 15 columns are not visible.

| Environment | Info |
| Vite | 4.3.9 |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Hi, pls provide a runnable repo instead of part code.

**Comment by GeorgiyBeloklokov** [comment]
With 5.9.1 all ok, this bug doesn't exist
