### ISSUE TITLE
Virtual table body has issue after resizing the viewport

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44889]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-5-9-1-forked-9mxrl9?file=/demo.tsx)

### Steps to reproduce

1. create a virtual table
2. set the scroll y and x
3. shrink the browser window
4. scroll all the way to x
5. enlarge screen again
6. table body is not readjusting back to normal width

### What is expected?

virtual table content should restore layout after window resize

### What is actually happening?

table content remain in mobile view after window resize back to desktop view

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
https://github.com/ant-design/ant-design/assets/52765572/b397cd66-4620-4847-bec0-bfde88fd68c8

**Comment by zombieJ** [comment]
Is this same as #44745 ?

**Comment by AsuraKev** [comment]
oh yep, its mentioned there as well :)

**Comment by zombieJ** [comment]
Could you help to simplify the codesandbox and record video by the codesandbox demo? Thus I can debug on this.

**Comment by AsuraKev** [comment]
This recording is using the Codesandbox directly from the virtual table from the documentation. Hope this helps :) thanks

https://github.com/ant-design/ant-design/assets/52765572/e1b4ed5b-cce1-4d09-8bab-24e40fd46d49

**Comment by AsuraKev** [comment]
@zombieJ has this patch been releasesd in 5.9.2?

**Comment by AsuraKev** [comment]
@zombieJ this issue is still happening on antd latest :(

**Comment by yoyo837** [comment]
Please try remove lock file and reinstall.

**Comment by AsuraKev** [comment]
Removing the lock file resolved the issue. Much appreciated

**Comment by harshittiwarihrt** [comment]
not appreciated because not working! even after removing issue remains the same for me!
