### ISSUE TITLE
Antd 的 Select | Tooltip 等组件在 Shadow dom 中不能正常工作

### ISSUE THREAD

**Issue by 6174** [ant-design/ant-design#44896]
### Reproduction link
因为我的场景是做 Chrome 插件，所以复现步骤比较复杂，不过基本就是 Plasmo 的这个代码加上 Select 组件
[https://github.com/PlasmoHQ/examples/tree/6272c89994cb3a8ceab05c3820a95907e33b7cb2/with-antd](https://github.com/PlasmoHQ/examples/tree/6272c89994cb3a8ceab05c3820a95907e33b7cb2/with-antd)

### Steps to reproduce

我也在 PlasmoHQ 添加了 Issue, https://github.com/PlasmoHQ/plasmo/issues/765

### What is expected?

现在 Select 的下拉选项看不到，Tooltip 的 title 也看不到，预期可以看到

### What is actually happening?

Select 的下拉选项看不到，Tooltip 的 title 也看不到
![image](https://github.com/ant-design/ant-design/assets/3872872/1bc5bd84-ecd1-497e-a1a6-4aff05fd5a49)

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | Macosx |
| Browser | Chrome Latest version |

**Comment by 6174** [comment]
I fixed this issue by config a global set getPopupContainer on ConfigProvider

```tsx
import { theme } from "antd"
import ConfigProvider from "antd/es/config-provider"
import type { ReactNode } from "react"

export const ThemeProvider = ({ children = null as ReactNode }) => (
  <ConfigProvider
    getPopupContainer={() => document.getElementById("shadow-dom-mount-container")?.shadowRoot as any}
    >
    {children}
  </ConfigProvider>
)
```

**Comment by kuloud** [comment]
> I fixed this issue by config a global set getPopupContainer on ConfigProvider
> 
> ```tsx
> import { theme } from "antd"
> import ConfigProvider from "antd/es/config-provider"
> import type { ReactNode } from "react"
> 
> export const ThemeProvider = ({ children = null as ReactNode }) => (
>   <ConfigProvider
>     getPopupContainer={() => document.getElementById("shadow-dom-mount-container")?.shadowRoot as any}
>     >
>     {children}
>   </ConfigProvider>
> )
> ```
> 
> Then adjust the z-index of select-dropdown popover everything can work

not working

**Comment by Powderbluee** [comment]
按照上面的代码修改后，option无法点击，只能查看，如何解决？
