### ISSUE TITLE
TimePicker 国际化下自定义format解析错误

### ISSUE THREAD

**Issue by xxxxx-feng** [ant-design/ant-design#44892]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ze-shi-fen-antd-4-24-12-forked-sqlcp7?file=/demo.tsx)

### Steps to reproduce

自定义format:
1. 葡萄牙语: Lembrete a HH:mm todos os dias
2. 英文: Remind at HH:mm every day
会渲染错误, 英文和葡萄牙语 会出现AM,PM

### What is expected?

正常解析  HH:mm

### What is actually happening?

把Y、M、D、H、h、m、s、S、A解析成了时间

| Environment | Info |
| --- | --- |
| antd | 4.23.1 |
| React | react |
| System | mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
这是预期行为，请参考一下 moment 的官方文档进行转译：
https://codesandbox.io/s/xuan-ze-shi-fen-antd-4-24-12-forked-sqlcp7?file=/demo.tsx
