### ISSUE TITLE
[Table]虚拟表格的一些异常问题

### ISSUE THREAD

**Issue by 1123612483** [ant-design/ant-design#44893]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xu-ni-lie-biao-antd-5-9-1-forked-hzwxf5?file=/demo.tsx)

### Steps to reproduce

1.打开【Small】开关
2.打开或者关闭【Expandable】开关的情况下，反复打开关闭【fixed】开关
3.打开【Bordered】开关
4.打开【Bordered】和【Display flex】开关

### What is expected?
1.checkbox列不对齐
2.checkbox列或者expandable图标列宽度不一致
3.表格宽度足够的情况下仍然出现横向滚动条，滚动时出现轻微晃动
4.每一列的宽度无限增加

### What is actually happening?

1.checkbox列对齐
2.已经设置列宽的情况下，checkbox列或者expandable图标列宽度要保持一致，打开【fixed】开关的列宽是正确的。
3.表格宽度足够的情况下不出现横向滚动条
4.每一列的宽度不会无限增加

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | Win11 |
| Browser | Microsoft Edge 116.0.1938.76 |

---
测试链接：https://nlcm4k.csb.app/

**Comment by 1123612483** [comment]
1.checkbox列不对齐
![image](https://github.com/ant-design/ant-design/assets/20741541/2a02a3ab-de0a-4c09-b6b3-555cc6b88568)
2.checkbox列或者expandable图标列宽度不一致
![image](https://github.com/ant-design/ant-design/assets/20741541/89f11055-f81d-4121-a3cc-1150b1a367cf)
![image](https://github.com/ant-design/ant-design/assets/20741541/63d40f04-94cd-4ca5-aa41-63882f73ec46)
3.表格宽度足够的情况下仍然出现横向滚动条
![image](https://github.com/ant-design/ant-design/assets/20741541/54e63c4f-54d6-44da-93dc-a400b66aad9b)

**Comment by AsuraKev** [comment]
^

**Comment by zombieJ** [comment]
1. 🐞 会修一下
2. 👻 是因为所有 column 都设置了宽度且总和小于 Table 宽度，所以被平均分配
3. 我这边没有重现哈，看看是不是因为设置了百分比缩放导致的
4. 同上没有重现，另外 Table 不应该设置 `flex` 布局

**Comment by 1123612483** [comment]
> 1. 🐞 会修一下
> 2. 👻 是因为所有 column 都设置了宽度且总和小于 Table 宽度，所以被平均分配
> 3. 我这边没有重现哈，看看是不是因为设置了百分比缩放导致的
> 4. 同上没有重现，另外 Table 不应该设置 `flex` 布局

第1第2点明白了

第3点我这边浏览器的缩放是100%，原因是当所有列的总宽度略大于`scroll.x`时，就出现横向滚动条。
![image](https://github.com/ant-design/ant-design/assets/20741541/7b580ce6-dd74-413d-89f9-af577baac0b3)

![image](https://github.com/ant-design/ant-design/assets/20741541/0b3e84a4-4a87-449a-8ec8-a24abcbb1f9a)

第4点不仅设置`display:flex`，`display:table`等其他属性也会出现这种情况，在实际场景确实不应该设置这些属性，但最好还是查明原因，避免无限增大宽度的情况发生。不知道你那边为啥没重现
![image](https://github.com/ant-design/ant-design/assets/20741541/f3fd5f62-01a8-4be8-8df0-227ae90bbcd8)

**Comment by 1123612483** [comment]
火狐也出现无限增大宽度的问题
![image](https://github.com/ant-design/ant-design/assets/20741541/b97e47d8-4d12-4634-b7ba-3519c6b270c6)
