### ISSUE TITLE
Table expandedRowRender 会渲染多次

### ISSUE THREAD

**Issue by woowalker** [ant-design/ant-design#44890]
### Reproduction link

[https://stackblitz.com/edit/react-jblyjr?file=demo.tsx](https://stackblitz.com/edit/react-jblyjr?file=demo.tsx)

### Steps to reproduce

看log输出

### What is expected?

展开后只渲染一次

### What is actually happening?

渲染次数随着展开行数递增

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome 版本 116.0.5845.188（正式版本） （64 位） |

![image](https://github.com/ant-design/ant-design/assets/7894779/c89d8dc6-9113-4b5b-837d-ada47de8b226)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/22901#issuecomment-608972325

**Comment by zombieJ** [comment]
展开时防止副作用，展开行都会渲染一次。不过额外多的一次可以看看能不能优化掉。

**Comment by zombieJ** [comment]
https://github.com/react-component/table/pull/1022  去除多一次的渲染
