### ISSUE TITLE
Form.Item 在getValueFromEvent中处理自动将全角字符转换成半角字符时，getValueFromEvent（和input change）异常触发2次

### ISSUE THREAD

**Issue by lingjieding** [ant-design/ant-design#44898]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-12-forked-syy2fy?file=/demo.js)

### Steps to reproduce

1. 鼠标focus input框获得焦点  
2. 输入法切换成全角输入 一般shift   space(空格) 即可切换 ,(这一步很重要,需要在input框获得焦点后切换成全角)
3. 输入英文字母, 此时会发现 输入框显示的内容是实际键盘输入的2倍,比如键盘输入字母d, input框显示dd, 查看console日志可以看到getValueFromEvent方法被触发了2次,第一次e.target.value是d, 第二次是dd
4. 将输入法切换回半角模式,再次输入应为字母, 恢复了正常

### What is expected?

在input框获得焦点后切换成全角后,可以正常输入英文字母

### What is actually happening?

在input框获得焦点后切换成全角后,输入英文字母,input框展示的内容是实际键盘输入的2倍字符

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | >=16 |
| System | windows / codesandbox |
| Browser | chrome: 版本 114.0.5735.134（正式版本） （64 位） |

---
业务场景是 我们想实现用户输入全角字符时自动将输入中的全角字符转换成半角,谢谢.

**Comment by zombieJ** [comment]
你不能在 `getValueFromEvent` 里处理数据，因为输入法会劫持内容，导致和 React 不同步。如果你需要自动转换数据，需要封装一个 Input 组件，然后对 `composition` 事件进行监听。如果是输入法控制时，不做转换，当输入法输入结束时再进行转换哈~

**Comment by lingjieding** [comment]
👌🏻&nbsp;谢谢


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月19日(周二) 中午11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design] Form.Item 在getValueFromEvent中处理自动将全角字符转换成半角字符时，getValueFromEvent（和input change）异常触发2次 (Issue #44898)




 
你不能在 getValueFromEvent 里处理数据，因为输入法会劫持内容，导致和 React 不同步。如果你需要自动转换数据，需要封装一个 Input 组件，然后对 composition 事件进行监听。如果是输入法控制时，不做转换，当输入法输入结束时再进行转换哈~
 
&mdash;
