### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by febezhao** [ant-design/ant-design#4489]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by febezhao** [comment]
Select的Autocomplete with remote ajax data
当匹配到数据呈现在option里面的时候，如何强制性要求一定要选择一项；
option中绑定了value和显示的文字是不一样的：value=lucy，显示的text=露西，怎么在选中一项之后，设定取到的值是value，显示的文字是text？

**Comment by yesmeck** [comment]
所以你说的是 Select 还是 AutoComplete？

**Comment by febezhao** [comment]
select

**Comment by yesmeck** [comment]
设置 `optionLabelProp="children"`。
