### ISSUE TITLE
多选下拉框必填验证bug

### ISSUE THREAD

**Issue by jessiedwj** [ant-design/ant-design#449]
多选下拉框选择选项后仍然验证不通过

**Comment by simaQ** [comment]
能详细描述下案发过程吗？

**Comment by jessiedwj** [comment]
给多选下拉框加必填required验证，选择一个下拉选项或多项，仍然不会验证通过，应该是不勾选验证不通过，勾选了验证通过的

**Comment by benjycui** [comment]
`Select[multiple]` 的值是一个数组，所以把 `{required: true}` 改成 `{required: true, type: 'array'}` 就可以了。

考虑到用户大多不会去读 https://github.com/yiminghe/async-validator 的文档，我还是改一下吧，当 `Validator` 内是 `Select[multiple]` 时，自动把 `{required: true}` 改成 `{required: true, type: 'array'}`? 如何 @afc163 

还是说在文档中注明就好？

**Comment by afc163** [comment]
不要自动改，注明吧。
