### ISSUE TITLE
select样式问题

### ISSUE THREAD

**Issue by dongwenqiang3** [ant-design/ant-design#44907]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-stfgz8)

### Steps to reproduce

select 组件的选择项是div元素的时候，展示的样式和之前不一样，元素会超出选择框

### What is expected?

不超出选择框

### What is actually happening?

超出了

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | chrome 117 |

**Comment by Yuiai01** [comment]
看起来是这个伪元素导致的：
<img width="1204" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/295c4ebc-a498-4921-802a-8309acdc4b7e">

**Comment by lvisei** [comment]
### Same question

[codesandbox 🔗](https://codesandbox.io/s/antd-reproduction-template-forked-qfggmq?file=/index.js)
