### ISSUE TITLE
Remove click in tooltip sort Table Column

### ISSUE THREAD

**Issue by malcoded** [ant-design/ant-design#44903]
### What problem does this feature solve?

Hi, I think the sort tooltip in the columns should be only informative and not fulfill the action function. 

### What does the proposed API look like?

As shown in this image, the tooltip hides the buttons I have in the header and this affects the usability because instead of clicking on the button I click on the tooltip and it messes up the table, with an action by accident.

![image](https://github.com/ant-design/ant-design/assets/24488771/d00a7933-e5a3-4524-81d3-35d8be0954fc)

**Comment by afc163** [comment]
showSorterTooltip={false}

**Comment by superstaritdev** [comment]
Thanks a lot
As I follow your tips, it is ok now

**Comment by thanhnv9x** [comment]
> showSorterTooltip={false}

thanks so much Pro
