### ISSUE TITLE
How to integrate AntD with Webpack2

### ISSUE THREAD

**Issue by andrewvmail** [ant-design/ant-design#4491]
#### Environment(required)

- antd version: 2.6.0
- OS and its version: Windows 7 & Mac OS 10.11.5
- Browser and its version: Webpack issue

#### What did you do? Please provide steps to re-produce your problem.

1. https://github.com/mxstbr/react-boilerplate
2. Add antd

#### What do you expected?

A smooth process without modifying things in antd package side (datepicker module date-picker/locale/zh_CN.js:23).

I tried configuring through webpack different settings specifically dll, plugins, alias, noParse settings tried all settings from different tickets but still can't get it to work smoothly.

#### What happen?

npm run build:dll
```
ERROR in dll reactBoilerplateDeps
Module not found: Error: Can't resolve 'moment/locale' in '/Users/andrew/projects/lift/frontend'
 @ dll reactBoilerplateDeps
```

Nothing major but its only an eye sore seeing the error during the build process.
Thanks in advance
A

**Comment by afc163** [comment]
Finally I make it work at react-boilerplate：https://github.com/afc163/react-boilerplate/commit/b1366a6e78cd83fc1b8ec402950c9cf0c5c8d841, and still struggling for moment locale setting.

**Comment by afc163** [comment]
@andrewvmail You can look reply above.

**Comment by kevart** [comment]
Having the same issue (as the title - don't really understand what _moment.js_ has to do with _antd_ and _webpack2_). Would be great to see how _antd_, especially the css bit works with latest webpack. All examples I find are outdated.

**Comment by tanduong** [comment]
For anyone who landed here, this commit work: https://github.com/afc163/react-boilerplate/commit/61ec8a19df0fcb56d407b795cb6c87141e0e14a7

Just remember to rebuild your dll, by running yarn install again if you are using react boilerplate.
