### ISSUE TITLE
输入框 浏览器自动填充时 高度随输入不停的变

### ISSUE THREAD

**Issue by pwango** [ant-design/ant-design#44911]
### Reproduction link

[https://ant.design/components/form-cn](https://ant.design/components/form-cn)

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | next |
| System | windows |
| Browser | edge |

问题视频链接
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[https://www.bilibili.com/video/BV1j8411q7hE/?vd_source=6ad738295b5660c011325acf406a997b](url)

**Comment by pwango** [comment]
有人吗？你自己在windows试一试就知道了，并且已经把情况上传至bilibili，来个人看下啊

**Comment by Wxh16144** [comment]
我用 PD 虚拟机的 Edge 看了一下， 没发现啥问题呀？ 看你反馈的是 next 项目中使用。 需要你提供更多信息，然后社区有了解 next 的方便复现问题。

https://github.com/ant-design/ant-design/assets/32004925/aa3a4efc-e599-4bed-88e0-fb8004bb04fb

**Comment by pwango** [comment]
> 我用 PD 虚拟机的 Edge 看了一下， 没发现啥问题呀？ 看你反馈的是 next 项目中使用。 需要你提供更多信息，然后社区有了解 next 的方便复现问题。
> 
>  Kapture.2023-09-18.at.00.26.32.mp4

首先，谢谢您的回复。
windows edge，密码提示相关很多情况总能触发这个。我把相关代码还有这个迷你小页面 pages截图  还有明确的触发视频都放在了下面，麻烦您再看看


import { Button, Form, Input, Checkbox, Switch } from "antd";

function App() {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Form
        name="wrap"
        labelCol={{ flex: "80px" }}
        labelAlign="left"
        labelWrap
        wrapperCol={{ flex: 1 }}
        colon={false}
        style={{
          width: 500,
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%,-50%)",
        }}
      >
        <Form.Item label="特征A" name="F1" rules={[{ required: true }]}>
          <Input maxLength="15" />
        </Form.Item>

        <Form.Item label="特征B" name="F2" rules={[{ required: true }]}>
          <Input maxLength="5" />
        </Form.Item>

        <Form.Item label="特征C" name="F3" rules={[{ required: true }]}>
          <Input maxLength="5" />
        </Form.Item>

        <Form.Item label="特征D" name="F4" rules={[{ required: true }]}>
          <Input maxLength="5" />
        </Form.Item>
        <Form.Item label="特征E" name="F5" rules={[{ required: true }]}>
          <Input maxLength="5" />
        </Form.Item>
        <Form.Item label="糖尿病" name="F6" rules={[{ required: true }]}>
          <Switch checkedChildren="有" unCheckedChildren="无"  />
        </Form.Item>
        <Form.Item label="高血压" name="F7" rules={[{ required: true }]}>
          <Switch checkedChildren="有" unCheckedChildren="无" />
        </Form.Item>

        <Form.Item label=" " style={{position:"fixed",left:220}}>
          <Button type="primary" htmlType="submit">
            提交
          </Button>
        </Form.Item>
      </Form>
    </div>
  );
}

export default App;

![屏幕截图 2023-09-18 094508](https://github.com/ant-design/ant-design/assets/143368172/26bf0e4e-6f93-4b8d-bcd4-33b29d85ff39)

https://www.bilibili.com/video/BV14u4y1r7LV/?vd_source=6ad738295b5660c011325acf406a997b

**Comment by yoyo837** [comment]
请提供可直接访问的 csb.

**Comment by zombieJ** [comment]
看起来像是自动填充的字体大小和 Input 的字体大小不一致导致的闪动？还是需要一下重现，否则没办法确定。

**Comment by pwango** [comment]
> 看起来像是自动填充的字体大小和 Input 的字体大小不一致导致的闪动？还是需要一下重现，否则没办法确定。

好的，我尽量，小白不太懂，非计算机专业，有很多词都不懂，话说现在都不是很理解啥时hooks，觉得就是触发的一个函数或功能的那种小白

**Comment by pwango** [comment]
> csb.

本地的小demo，没有弄服务器 域名之类的

**Comment by pwango** [comment]
> 我用 PD 虚拟机的 Edge 看了一下， 没发现啥问题呀？ 看你反馈的是 next 项目中使用。 需要你提供更多信息，然后社区有了解 next 的方便复现问题。
> 
>  Kapture.2023-09-18.at.00.26.32.mp4

新建文件夹 (2)
https://www.aliyundrive.com/s/moQKudLEmYu
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by yoyo837** [comment]
你好 @pwango, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。

**Comment by pwango** [comment]
> 你好 @pwango, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。

您好，已经把next的out静态文件分享至阿里云，可以下载试一下

**Comment by yoyo837** [comment]
你的复现前置步骤太多, 每个issue我们都自行准备的话, 时间根本不够. 请提供可以直接查看的 codesandbox 链接.

**Comment by pwango** [comment]
> 你的复现前置步骤太多, 每个issue我们都自行准备的话, 时间根本不够. 请提供可以直接查看的 codesandbox 链接. 其他在线代码预览的也可以.

此外，这个在线预览不是edge浏览器，它没有自动填充，因此在这个无法复现。

**Comment by afc163** [comment]
codesandbox 和浏览器无关的，你用 Edge 打开就是 Edge 了。

**Comment by pwango** [comment]
> codesandbox 和浏览器无关的，你用 Edge 打开就是 Edge 了。

但我确定的是 1.这个东西很慢  2.我用的时候它没有自动补全提示  3.国内还是存在很多用windows的前端antd用户，edge是默认浏览器

**Comment by afc163** [comment]
> 国内还是存在很多用windows的前端antd用户，edge是默认浏览器

没问题，我们已经知晓了您的问题需要再 Edge 上才能重现，我们还需要更多的重现条件才能重现问题，最好是一个可直接访问的在线链接。以及完整的可重现方式，否则我们没有办法定位问题。

>  1.这个东西很慢 2.我用的时候它没有自动补全提示

如果您访问 codesandbox 很慢，也可以提供一个可重现的 github repository 项目。

**Comment by pwango** [comment]
> codesandbox 和浏览器无关的，你用 Edge 打开就是 Edge 了。

我还是给你录个视频把，
[https://www.bilibili.com/video/BV1UF411U7n8/](url)

**Comment by afc163** [comment]
> 我还是给你录个视频把

需要可运行的仓库或者可访问的在线链接，只有视频只能确定问题在您的机器上确实存在，没有办法排查问题。

**Comment by yoyo837** [comment]
> > codesandbox 和浏览器无关的，你用 Edge 打开就是 Edge 了。
> 
> 但我确定的是 1.这个东西很慢 2.我用的时候它没有自动补全提示 3.国内还是存在很多用windows的前端antd用户，edge是默认浏览器

不是不相信你,  只是没办法因为一句话投入精力去看, 大家都有自己工作的.

**Comment by pwango** [comment]
> > > codesandbox 和浏览器无关的，你用 Edge 打开就是 Edge 了。
> > 
> > 
> > 但我确定的是 1.这个东西很慢 2.我用的时候它没有自动补全提示 3.国内还是存在很多用windows的前端antd用户，edge是默认浏览器
> 
> 不是不相信你, 只是没办法因为一句话投入精力去看, 大家都有自己工作的.

算了，祝好！
