### ISSUE TITLE
Hooks-Message 全局配置不生效

### ISSUE THREAD

**Issue by Wangsong2021** [ant-design/ant-design#44925]
### Reproduction link

[http://192.168.7.198:3000/#/reseller](http://192.168.7.198:3000/#/reseller)

### Steps to reproduce

/_ 国际化 _/
import { ConfigProvider, message } from "antd";
import zhCN from "antd/es/locale/zh_CN";
import "dayjs/locale/zh-cn";
import RouterAuth from "./pages/routerAuth";
import { HappyProvider } from "@ant-design/happy-work-theme";
import "./App.css";
import "./style/common.scss";
message.config({ maxCount: 1 });

function App() {
return (
<ConfigProvider
locale={zhCN}
theme={{
				components: {
					Tabs: {
						horizontalItemPaddingLG: "0 0 16px"
					}
				}
			}} >
<HappyProvider>
<>{RouterAuth()}</>
</HappyProvider>
</ConfigProvider>
);
}

export default App;

### What is expected?

message.config配置生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 5.8.5 |
| React | 18.2.0 |
| System | Windows 11 家庭中文版 |
| Browser | Google Chrome 版本 116.0.5845.180（正式版本） （64 位） |

---
重现链接为内部项目，需自行配置。

**Comment by Wangsong2021** [comment]
https://codesandbox.io/embed/antd-reproduction-template-forked-f6rfvt?fontsize=14&hidenavigation=1&theme=dark

**Comment by Wangsong2021** [comment]
> Hello @Wangsong2021. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @Wangsong2021, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/embed/antd-reproduction-template-forked-f6rfvt?fontsize=14&hidenavigation=1&theme=dark

**Comment by Yuiai01** [comment]
hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。

**Comment by Wangsong2021** [comment]
> hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。

尝试过了，可以解决该问题，但控制台会抛出错误

**Comment by Yuiai01** [comment]
> > hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。
> 
> 尝试过了，可以解决该问题，但控制台会抛出错误

能康康是啥错误吗

**Comment by Wangsong2021** [comment]
> > > hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。
> > 
> > 
> > 尝试过了，可以解决该问题，但控制台会抛出错误
> 
> 能康康是啥错误吗

![image](https://github.com/ant-design/ant-design/assets/75063077/cb8e9aeb-e6d7-4bd8-9e6a-61341005e069)

**Comment by Wangsong2021** [comment]
> > > hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。
> > 
> > 
> > 尝试过了，可以解决该问题，但控制台会抛出错误
> 
> 能康康是啥错误吗

已经解决此问题 用App进行全局包裹。同理ts中该如何使用呢？请指点一二 谢谢

**Comment by Yuiai01** [comment]
> > > > hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。
> > > 
> > > 
> > > 尝试过了，可以解决该问题，但控制台会抛出错误
> > 
> > 
> > 能康康是啥错误吗
> 
> 已经解决此问题 用App进行全局包裹。同理ts中该如何使用呢？请指点一二 谢谢

在 ts 中应该是一样的使用方式。

**Comment by Wangsong2021** [comment]
> > > > > hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。
> > > > 
> > > > 
> > > > 尝试过了，可以解决该问题，但控制台会抛出错误
> > > 
> > > 
> > > 能康康是啥错误吗
> > 
> > 
> > 已经解决此问题 用App进行全局包裹。同理ts中该如何使用呢？请指点一二 谢谢
> 
> 在 ts 中应该是一样的使用方式。

直接抛错，无法解析，好像必须在组件内使用

**Comment by Yuiai01** [comment]
> > > > > > hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。
> > > > > 
> > > > > 
> > > > > 尝试过了，可以解决该问题，但控制台会抛出错误
> > > > 
> > > > 
> > > > 能康康是啥错误吗
> > > 
> > > 
> > > 已经解决此问题 用App进行全局包裹。同理ts中该如何使用呢？请指点一二 谢谢
> > 
> > 
> > 在 ts 中应该是一样的使用方式。
> 
> 直接抛错，无法解析，好像必须在组件内使用

参考这个试试？https://ant.design/components/app-cn#app-demo-config

**Comment by Wangsong2021** [comment]
> > > > > > > hooks 的方式不支持使用 message.config。你可以选择使用 [App](http://localhost:8001/components/app-cn) 组件包裹一下然后进行设置。
> > > > > > 
> > > > > > 
> > > > > > 尝试过了，可以解决该问题，但控制台会抛出错误
> > > > > 
> > > > > 
> > > > > 能康康是啥错误吗
> > > > 
> > > > 
> > > > 已经解决此问题 用App进行全局包裹。同理ts中该如何使用呢？请指点一二 谢谢
> > > 
> > > 
> > > 在 ts 中应该是一样的使用方式。
> > 
> > 
> > 直接抛错，无法解析，好像必须在组件内使用
> 
> 参考这个试试？https://ant.design/components/app-cn#app-demo-config

好的 感谢 看来要使用store才能解决

**Comment by MadCcc** [comment]
hooks 直接用 ConfigProvider 的 `theme` 就好了

**Comment by Janesuyue** [comment]
你好，使用store解决，message会返回空嘛
