### ISSUE TITLE
官网更新日志显示异常

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#44921]
### Reproduction link

[https://ant.design/components/badge-cn](https://ant.design/components/badge-cn)

### Steps to reproduce

下图红色框选的地方应该是组件名称？

### What is expected?

无

### What is actually happening?

<img width="1919" alt="image" src="https://github.com/ant-design/ant-design/assets/37385554/ab54ecf6-df55-490b-b642-5c2a592a59cd">

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | macOS 13 |
| Browser | 112.0.5615.137 |

**Comment by kiner-tang** [comment]
看起来应该是不支持 markdown 的 `[描述](链接)` 的语法
