### ISSUE TITLE
Badge 组件 classNames.indicator 属性不生效

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#44920]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-9-1-forked-68gs2z?file=/demo.tsx)

### Steps to reproduce

无

### What is expected?

<img width="59" alt="image" src="https://github.com/ant-design/ant-design/assets/37385554/176d1245-cf03-4b23-af04-067756db080b">

### What is actually happening?

<img width="60" alt="image" src="https://github.com/ant-design/ant-design/assets/37385554/60ee29e8-92f1-4be6-9f3a-42139dad455f">

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | macOS 13 |
| Browser | 116.0.5845.187 |

**Comment by Yuiai01** [comment]
看起来是自定义类样式被原有类样式覆盖了，也许应该提升一下自定义类的优先级。

**Comment by MadCcc** [comment]
> 看起来是自定义类样式被原有类样式覆盖了，也许应该提升一下自定义类的优先级。

+1，`classNames` 只提供了自定义类名的能力，并没有提供更高的样式优先级
