### ISSUE TITLE
Form表单中对应的Form.Item里使用InputNumber，后面跟一个元素如<span></span>，那么这个Form.Item将无法读取到内容

### ISSUE THREAD

**Issue by Jokerdeath** [ant-design/ant-design#44926]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z83fhh?file=/index.js)

### Steps to reproduce
```html
<Form.Item labelCol={{ span: 5 }} wrapperCol={{ span: 22 } } name="sourceLimit" label="请求次数数量上限">
      <>
        <InputNumber placeholder='请输入请求数量上限' style={{ width: '50%' }} />
        <span>tian</span>
     </>
</Form.Item>
```

这段代码里sourceLimit的值将无法被读取，去除掉<span>tian</span>就可以了

### What is expected?

可以正确读取到对应的值

### What is actually happening?

无法读取值

| Environment | Info |
| --- | --- |
| antd | 4.24.9 |
| React | 17.0.1 |
| System | Windows11 |
| Browser | chrome 116.0.5845.188（正式版本） （64 位） |

**Comment by crazyair** [comment]
https://zhuanlan.zhihu.com/p/422752055

**Comment by afc163** [comment]
符合预期。

https://ant.design/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-formitem-%E5%B5%8C%E5%A5%97%E5%AD%90%E7%BB%84%E4%BB%B6%E5%90%8E%E4%B8%8D%E6%9B%B4%E6%96%B0%E8%A1%A8%E5%8D%95%E5%80%BC

https://ant.design/components/form-cn#components-form-demo-complex-form-control

**Comment by Jokerdeath** [comment]
> https://zhuanlan.zhihu.com/p/422752055
> 
> ![image](https://user-images.githubusercontent.com/7971419/268552454-32cbf222-28a7-46a5-b403-7e04e5ec44d8.png)

感谢解答
