### ISSUE TITLE
table组件的colomun render函数中可以设置 className吗？

### ISSUE THREAD

**Issue by spademan** [ant-design/ant-design#4493]
#### Environment(required)

- antd version: 2.6.0
- OS and its version:
- Browser and its version: chrome

#### What do you expected?
因为在使用过程中，需要设置 不同的单元格的颜色，一列的颜色可能都不一样的， 现在好像只能写死一列的的class
虽然 在render返回中， 可以添加的dom结构，并且能设置样式，但是比如说我想修改这个td的pading（比如一列中，不同的td padding大小不一样 就需要额外的className了，不是吗）?

**Comment by afc163** [comment]
可以用 `rowClassName` 配合 `column.className`。
