### ISSUE TITLE
Virtual table horizontal scroll doesnt seem to work when scroll.x is set to true

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#44939]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-5-9-1-forked-5kv3ps?file=/demo.tsx)

### Steps to reproduce

1. Create a virtual table
2. set scroll.x to true rather than a fixed number

### What is expected?

Table scroll x should fit container 

### What is actually happening?

horizontal scroll is not working 

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | Web |
| Browser | Chrome |

**Comment by AsuraKev** [comment]
Also when there are no fixed columns the x scrolling doesnt work. Please see below example directly forked from documentation site, with **fixed** switch turned off. thanks :)

https://codesandbox.io/s/virtual-list-antd-5-9-1-forked-5kv3ps?file=/demo.tsx

**Comment by zombieJ** [comment]
When `scrollX` set to not a number, it will fallback to `scrollX: 1`. Which should warning developer that in virtual table it only accept number type.

**Comment by AsuraKev** [comment]
@zombieJ if you set a static number for scroll.x, how will it handle different screen sizes? e.g if I set scroll.x = 1600, it might look ok on screen with width 2000px but not on 3000px ...

**Comment by yogithesymbian** [comment]
Warning: `scroll.y` in virtual table must be number.
updated nextjs version 
```
Next.js (15.1.3) (Turbopack)
"antd": "^5.22.7",
```
