### ISSUE TITLE
【dropdown】当trigger为['contextMenu']时，placement不起作用

### ISSUE THREAD

**Issue by kkkisme** [ant-design/ant-design#44941]
### Reproduction link

[https://stackblitz.com/edit/react-afmn92?file=demo.tsx](https://stackblitz.com/edit/react-afmn92?file=demo.tsx)

### Steps to reproduce

打开链接，点击click me

### What is expected?

弹出菜单位置固定topLeft

### What is actually happening?

弹出菜单位置会跟随右键点击位置变动

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | window 11 |
| Browser | chrome 117 |

**Comment by kkkisme** [comment]
虽然可以自己手动绑定contextmenu事件和手动设置open，
但如果这是符合设计的，应该在文档上备注一下

**Comment by afc163** [comment]
这是符合设计的，类似操作系统桌面右键的效果。

可以来个文档备注，欢迎 PR。
