### ISSUE TITLE
Antd Tree 修改fieldNames.key为其他值时，DirectoryTree 的onSelect方法中的selectedNodes无法正确获取值

### ISSUE THREAD

**Issue by Lomathsus** [ant-design/ant-design#44947]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-p96w9l?file=/index.js)

### Steps to reproduce

将fieldNames.key改为'id'后，DirectoryTree无法通过id筛选出selectedNodes，将数据的id改回key就能够成功识别

### What is expected?

DirectoryTree的selectedNodes可以正确识别自定的key值

### What is actually happening?

返回了空数组[]

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | ^18.2.0 |
| System | macOS 13.5.1 |
| Browser | Chrome |

**Comment by Zian502** [comment]
这个我来看看

**Comment by Zian502** [comment]
看了下，DirectoryTree  目前还不支持 fieldNames，参考 rc-tree，需要加上 fillFieldNames。预计这周末提个 pr

**Comment by Zian502** [comment]
https://github.com/ant-design/ant-design/pull/45035

**Comment by Zian502** [comment]
https://github.com/ant-design/ant-design/pull/45036
