### ISSUE TITLE
Sider / Menu component "theme" property only works as expected if no specific global <ConfigProvider /> is used

### ISSUE THREAD

**Issue by Maikel-Nait** [ant-design/ant-design#44956]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-villani-gzcz36?file=/src/App.js)

### Steps to reproduce

Create a sample app, and wrap it using a ```<ConfigProvider>``` with the **darkAlgorithm** theme setting.
Use a ```<Layout>``` component with a ```<Header>``` and ```<Sider>```, both using a ```<Menu>``` , using a theme="light" property.

### What is expected?

The goal is to set the dark algorithm for the entire app, but still display either the layout Header and Sider with the "light" theme property. Only the main ```<Content>``` will follow the dark algorithm.  In other words, show a light Sider / Header while the main content is dark.

### What is actually happening?

When using the ```<ConfigProvider />``` with darkAlgorithm, setting the theme="light" on the Sider / Menu does not display styles correctly. So we can't mix a "light" Sider / Menu with a dark content as expected. Can this be done easily ?

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.2.0 |
| System | Node 18 |
| Browser | Chrome 116 |

---
When removing the ```<ConfigProvider />``` that wraps the App, the theme="light / dark" property for the Sider / Menu components works as expected.

**Comment by MadCcc** [comment]
It works as expected. Since `theme` of Layout and Menu have nothing to do with `theme` of ConfigProvider, the style could still be affected by ConfigProvider.

It you only want `<Content />` to follow dark theme, just wrap `<Content />` with `<ConfigProvider />`.

**Comment by Maikel-Nait** [comment]
I see , thanks !!
