### ISSUE TITLE
抽屉设置zIndex后,抽屉中表单的下拉框看不到了.

### ISSUE THREAD

**Issue by hhniao** [ant-design/ant-design#44958]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-59xtwg?file=/index.js)

### Steps to reproduce

删除zIndex立即生效

### What is expected?

允许设置zIndex

### What is actually happening?

zIndex设置以后, 下拉框没有了

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | latest |
| System | win10 |
| Browser | latest |

**Comment by kiner-tang** [comment]
因为 Select 下拉菜单的层级是 1050，比抽屉低被挡住了，我们讨论一下，出一个更好的 z-index 管理方案，之后有进展会在这里同步

**Comment by hhniao** [comment]
@kiner-tang 请问有临时的解决方案吗?
```
.fileSelector {
  z-index: 9999;
  position: absolute;
  :global {
    .ant-drawer {
      z-index: 9999;
    }
    .ant-select {
      z-index: 9999;
    }
  }
}
```
这样并不生效

**Comment by kiner-tang** [comment]
> @kiner-tang 请问有临时的解决方案吗?
> 
> ```
> .fileSelector {
>   z-index: 9999;
>   position: absolute;
>   :global {
>     .ant-drawer {
>       z-index: 9999;
>     }
>     .ant-select {
>       z-index: 9999;
>     }
>   }
> }
> ```
> 
> 这样并不生效
> 
> ```
> .fileSelector {
>   z-index: 9999;
>   position: absolute;
> }
> 
> :global {
>   .ant-select-dropdown {
>     z-index: 9999;
>   }
> }
> ```
> 
> 这样是有效的

你可以先尝试用 ConfigProvider 修改下拉菜单的父级临时解决这个问题：https://codesandbox.io/s/antd-reproduction-template-forked-vxll94?file=/index.js

**Comment by hhniao** [comment]
@kiner-tang 
多谢大佬

**Comment by hhniao** [comment]
@afc163 使用tinymce本地免费版, 没有文件浏览功能.
在插入图片处弄了一个弹出抽屉选择图片的. 弹出来以后被挡住了. 
就加了一个z-index

```
<Editor
        tinymceScriptSrc={"/tinymce/tinymce.min.js"}
        value={editorContent}
        init={{
          ...defaultConfig,
          language,
          file_picker_callback: (callback, value, meta) => {
            setShowChooseFile(true)
            fileBrowserCallback = (f: UserFile[]) => {
              setChoseFiles(f)
              if (f === undefined) {
                return
              }
              for (let i = 0; i < f.length; i++) {
                callback(imageUrl(f[i]?.path ?? "", f[i]?.disk ?? ""), {text: f[i]?.name})
                break
              }
            }
          },
        }}
        onEditorChange={handleEditorChange}
      />
```

**Comment by zombieJ** [comment]
指的是 tinymce 这个组件它有更高的 zIndex？

**Comment by hhniao** [comment]
他弹出来的是1300

**Comment by hhniao** [comment]
能否顺便问一下为什么拿不到值呢? 
```
const EditorComponent: React.FC<Props> = ({value, onChange}) => {
  const [showChooseFile, setShowChooseFile] = useState(false)
  return (
      <Editor
        ...
        // @ts-ignore
        init={{
          ...
          file_picker_callback: (callback, value, meta) => {
            console.log(choseFiles, "ccccccccccccccccccccc")
            }
          },
        }}
      />
 )
}

<Form.Item
  label={i18n.t("detail")}
  name="detail"
>
  <TinymceEditor/>
</Form.Item>
```

**Comment by kiner-tang** [comment]
Completed in https://github.com/ant-design/ant-design/discussions/45154
