### ISSUE TITLE
form.validateFields()无法获取到Form.List内元素的值

### ISSUE THREAD

**Issue by codercoin98** [ant-design/ant-design#44953]
### Reproduction link
![image](https://github.com/ant-design/ant-design/assets/55039022/8250c7c5-effa-4395-889c-04dbf7b84012)

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dong-tai-zeng-jian-biao-dan-xiang-antd-5-9-1-forked-4gp8h8?file=/demo.tsx)

### Steps to reproduce

点击submit打印正确结果

### What is expected?

{names:[{key:"xxx",value:"xx"}]}

### What is actually happening?

意外的值

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.0.0 |
| System | win10 |
| Browser | chrome 116 |

**Comment by zombieJ** [comment]
请查阅文档，`add` 参数是提供默认值的哈：

<img width="688" alt="截屏2023-09-19 22 11 37" src="https://github.com/ant-design/ant-design/assets/5378891/63963d83-fce2-4c9c-9d60-ba484046e8e8">


```diff
-- <Button onClick={add}>
++ <Button onClick={() => add()}>
```
