### ISSUE TITLE
Input组件启用showCount和maxLength输入enjoy表情后显示的数字不正确

### ISSUE THREAD

**Issue by AprilLastCherry** [ant-design/ant-design#44950]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-45xgfk?file=/index.js:211-212)

### Steps to reproduce

Input组件启用showCount和maxLength输入表情，😊的长度为2， 在代码里面经过 [...String(😊)] 执行后长度发生变化，变为1

```
import React from "react";
import { createRoot } from "react-dom/client";
import { Input } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const App = () => {
  return (
    <div className="App">
      <span>输入😊，无法继续输入，但是显示1/2</span>
      <Input showCount maxLength={2} />
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);
```

### What is expected?

字数显示的数字保持一致

### What is actually happening?

实际长度为原来的一半

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 16.8.6 |
| System | macOS 13.2.1 (22D68) |
| Browser | chrome 114.0.5735.198（正式版本） (arm64) |

**Comment by MadCcc** [comment]
Trace https://github.com/ant-design/ant-design/issues/37733
