### ISSUE TITLE
antd5浏览器引入不起作用

### ISSUE THREAD

**Issue by guangmang** [ant-design/ant-design#44957]
### Reproduction link

[https://github.com/guangmang/ant-design/blob/master/tests/demo](https://github.com/guangmang/ant-design/blob/master/tests/demo)

### Steps to reproduce

通过浏览器引入react,babel，antd5不能工作，Uncaught ReferenceError: Select is not defined。ant4能正常work

### What is expected?

能够antd5能够通过浏览器引入的方式正常工作

### What is actually happening?

not work

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18 |
| System | windows |
| Browser | chrome 116 |

**Comment by afc163** [comment]
```
const { Select } = window.antd;
```
