### ISSUE TITLE
中文文档翻译问题

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#44963]
### Reproduction link

[https://ant.design/components/form-cn#form](https://ant.design/components/form-cn#form)

### Steps to reproduce

下图框选部分

### What is expected?

无

### What is actually happening?

<img width="1576" alt="image" src="https://github.com/ant-design/ant-design/assets/37385554/61b23d4c-8311-4792-b244-9f4d4ef647a8">

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.2.0 |
| System | macOS 13 |
| Browser | 112.0.5615.137 |

**Comment by li-jia-nan** [comment]
我来改一下
