### ISSUE TITLE
Select scrollbar-thumb styling

### ISSUE THREAD

**Issue by lukashenkor** [ant-design/ant-design#44981]
### What problem does this feature solve?

It'll be able to specify color of scrollbar-thumb based on user/developer preferences or current theme (_day, night_). For now it's always __`rgba(0, 0, 0, 0.5)`__.

P.S. I know that it is possible to set virtual to false and then native scrollbar will appear, but for my case virtual scroll is required.

### What does the proposed API look like?

I think it should be theme property, something like `scrollbarThumbColor` or any better name.

**Comment by zombieJ** [comment]
className selector is still work. You can override it easily:
https://codesandbox.io/s/duo-xuan-antd-5-10-0-forked-2q3d6z?file=/index.css
