### ISSUE TITLE
Add design tokens for button to support underline, hover underline, and hover bold 

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#44988]
### What problem does this feature solve?

Allows for better control of button text styling, e.g., to enable a link button to appear underlined or to go from non-bold to bold when hovered.

Note, it might make sense to apply this improvement to other components, but there is a clear, obvious use case for link buttons.

### What does the proposed API look like?

Add these design tokens for Button: `textDecoration`, `hoverFontWeight`, and `hoverTextDecoration.

**Comment by MadCcc** [comment]
I would rather provide `link` in `classNames` for further customization, because these are not common variant for antd.

**Comment by devuxer** [comment]
Sure, we could go that route, but you could say the same thing for any of the design tokens you have. How do you decide which styling features should be controlled via tokens versus style/class/CSS overrides?

**Comment by MadCcc** [comment]
@devuxer 

Currently we provide tokens of css properties which antd has already used in style. We didn't expect that everything should be customized with token, or it will be hard to maintain.

In your case, `textDecoration` and `hoverFontWeight` haven't applied by antd yet, so the priority could be low and I recommend to customize with classes to override.

**Comment by devuxer** [comment]
@MadCcc , That makes sense, thanks.  I'll close this now.

**Comment by devuxer** [comment]
@MadCcc , That makes sense, thanks. I'll close this now.

**Comment by devuxer** [comment]
@MadCcc , That makes sense, thanks. I'll close this now.
