### ISSUE TITLE
buttongroup、progeress-line等组件的间隙问题

### ISSUE THREAD

**Issue by yuu2lee4** [ant-design/ant-design#4498]
buttongroup里面的button是inline-block的，所以回车的话：
&lt;button-group&gt;
     &lt;button&gt;&lt;/button&gt;
     &lt;button&gt;&lt;/button&gt;
&lt;/button-group&gt;
是会产生间隙的，可能react版的在处理的时候没有回车，所以发现不到，我在做vue版的时候就发现了，包括很多其他的组件都是，建议此类的组件都设置浮动

**Comment by afc163** [comment]
来个 PR 如何？

**Comment by afc163** [comment]
Or you can try `preserveWhitespace` option. https://github.com/vuejs/vue/releases/tag/v2.0.3

**Comment by yuu2lee4** [comment]
@afc163 谢谢 不过我用的vue1

**Comment by afc163** [comment]
有这方面的需求就直接给我们 PR 吧~
