### ISSUE TITLE
Space.Compact 数字输入框带有前/后置标签边框样式问题

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design#44997]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/space-compact-shu-zi-shu-ru-kuang-dai-you-qian-hou-zhi-biao-qian-bian-kuang-yang-shi-wen-ti-wfrkq8?file=/src/App.js)

### Steps to reproduce

无

### What is expected?

边框合并

### What is actually happening?

<img width="419" alt="image" src="https://github.com/ant-design/ant-design/assets/5070722/e7dbbdf8-39f6-4fe0-990a-024c68065b80">

<img width="1020" alt="image" src="https://github.com/ant-design/ant-design/assets/5070722/9e71b593-874b-4ca9-9ca6-7ed7a426f826">

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.2.0 |
| System | - |
| Browser | - |

**Comment by Yuiai01** [comment]
确实，给 `.ant-input-number-group-wrapper` 这个 div 加个 `margin-inline-end: -1;` 就正常了。
<img width="1308" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/d1bf91bf-a6aa-44a0-a968-989bf0556fae">

**Comment by Leiqingqing** [comment]
合并边框后，InputNumber在输入时右边少一条border
![image](https://github.com/ant-design/ant-design/assets/83442605/10046eb7-f782-4551-94d1-2b4b2cc48406)

**Comment by Yuiai01** [comment]
> 合并边框后，InputNumber在输入时右边少一条border ![image](https://user-images.githubusercontent.com/83442605/274815732-10046eb7-f782-4551-94d1-2b4b2cc48406.png)

好的，我来跟一下。
