### ISSUE TITLE
rangepicker  open属性受控下 行为有问题

### ISSUE THREAD

**Issue by adolfheir** [ant-design/ant-design#44992]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/e-wai-de-ye-jiao-antd-5-9-2-forked-kr99lw?file=/demo.tsx:388-392)

### Steps to reproduce

open受控下 onopench
![Sep-21-2023 14-29-49](https://github.com/ant-design/ant-design/assets/26828649/1f887feb-8b1b-4b43-87fe-f213bed9e3b5)
ange  没有回调

### What is expected?

open受控下 onopenchange  正确关闭

### What is actually happening?

open受控下 onopenchange  点击确定没响应

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by Yuiai01** [comment]
确实，在结束日期哪里点击确定应该关闭的，我来康康这个问题。

**Comment by Yuiai01** [comment]
看了下，你最开始点击打开时间选择面板的时候就将 isOpen 设置为了 false， 这可能是导致后续无法关闭的原因。

**Comment by adolfheir** [comment]
> 看了下，你最开始点击打开时间选择面板的时候就将 isOpen 设置为了 false， 这可能是导致后续无法关闭的原因。

 请看代码 只是默认值false 后续都是组件传出来的状态

**Comment by Yuiai01** [comment]
> > 看了下，你最开始点击打开时间选择面板的时候就将 isOpen 设置为了 false， 这可能是导致后续无法关闭的原因。
> 
> 请看代码 只是默认值false 后续都是组件传出来的状态

嗯嗯

**Comment by Yuiai01** [comment]
是 rc-picker 那边的问题，我来跟一下。

**Comment by yoyo837** [comment]
Broken by https://github.com/react-component/picker/pull/663.

**Comment by pengfan2013** [comment]
在日期选择下的open受控仍然存在问题.
https://codesandbox.io/embed/e-wai-de-ye-jiao-antd-5-9-2-forked-66jzhy?fontsize=14&hidenavigation=1&theme=dark

**Comment by Yuiai01** [comment]
> 在日期选择下的open受控仍然存在问题. https://codesandbox.io/s/e-wai-de-ye-jiao-antd-5-9-2-forked-66jzhy?from-embed @Yuiai01

好的，我来跟一下

**Comment by Yuiai01** [comment]
> 在日期选择下的open受控仍然存在问题. https://codesandbox.io/s/e-wai-de-ye-jiao-antd-5-9-2-forked-66jzhy?from-embed @Yuiai01

在 openChange 的时候将 open 设置为了 true，因此他不会关闭面板。不过初始设置为 false，按理说应该打不开面板啊 🤔

**Comment by pengfan2013** [comment]
> > 在日期选择下的open受控仍然存在问题. https://codesandbox.io/s/e-wai-de-ye-jiao-antd-5-9-2-forked-66jzhy?from-embed @Yuiai01
> 
> 在 openChange 的时候将 open 设置为了 true，因此他不会关闭面板。不过初始设置为 false，按理说应该打不开面板啊 🤔

日期选择并没有确认按钮, 应是选择日期即会失去焦点, 进而应该触发openChange, 将open设置成false, 不然的话, 这里好像没办法"受控"

**Comment by Yuiai01** [comment]
> > > 在日期选择下的open受控仍然存在问题. https://codesandbox.io/s/e-wai-de-ye-jiao-antd-5-9-2-forked-66jzhy?from-embed @Yuiai01
> > 
> > 
> > 在 openChange 的时候将 open 设置为了 true，因此他不会关闭面板。不过初始设置为 false，按理说应该打不开面板啊 🤔
> 
> 日期选择并没有确认按钮, 应是选择日期即会失去焦点, 进而应该触发openChange, 将open设置成false, 不然的话, 这里好像没办法"受控"

嗯嗯，我跟进一下。
