### ISSUE TITLE
`<Dropdown>` performs a React state update on an unmounted component

### ISSUE THREAD

**Issue by zaakn** [ant-design/ant-design#44994]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jdj6x6?file=/index.js)

### Steps to reproduce

It will appear when the component <Dropdown> is unmounted triggered by both itself event handler or other components, as long as the dropdown menu is open or has been opened.

### What is expected?

Unmount completely without state updating 

### What is actually happening?

Console reports "Warning: Can't perform a React state update on an unmounted component"

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 17.0.2 |
| System | macOS |
| Browser | Chrome 117 (latest) |

---
No such warning in React 18.2.0 (latest).

Related issues: #27887

**Comment by vitalijalbu** [comment]
I also have the same issue here : https://github.com/ant-design/ant-design/discussions/50202
@zombieJ
