### ISSUE TITLE
表格设置纵向高度后在高度足够的情况下会出现滚动条样式

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#44993]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-9-2-forked-jpnhf5?file=/demo.tsx)

### Steps to reproduce

1. 设置表格的高度： scroll={{ y: 'scroll'}} 或者：scroll={{ y: '800'}}
2. 表格实际高度小于父级容器高度（或者小于 800）
3. 表格纵向将会出现滚动条样式

![image](https://github.com/ant-design/ant-design/assets/30885718/75d5f8b9-716e-4452-be15-0246f099df75)

### What is expected?

同样设置表格横向的宽度为：scroll={{ x: 'scroll'}}
但只要表格宽度存在可分配的空间就不会出现滚动条
希望表格的纵向滚动条与横向滚动条的表现形式一致，即在空间富余的情况下不会出现滚动条样式

### What is actually happening?

在空间富余的情况下，横向滚动条不会出现，纵向滚动条会出现
antd 4.x 也会出现此类问题

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

**Comment by afc163** [comment]
Duplicate of #29082
