### ISSUE TITLE
文档内容缺失

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#44999]
### Reproduction link

[https://ant.design/components/alert-cn](https://ant.design/components/alert-cn)

### Steps to reproduce

源码中存在主题变量（Design Token）相关的定义，文档未显示

### What is expected?

无

### What is actually happening?

<img width="1558" alt="image" src="https://github.com/ant-design/ant-design/assets/37385554/5e691f1c-5b10-492f-862b-eba30cb41f60">

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.2.0 |
| System | macOS 13 |
| Browser | 112.0.5615.137 |

**Comment by Yuiai01** [comment]
加个这个应该就好
<img width="754" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/8547de57-8e6d-456a-ac7a-6400c58ba1b7">

**Comment by Wxh16144** [comment]
Welcome PR~
