### ISSUE TITLE
table 拖拽功能结合 form.list，table 的第一行数据没办法拖拽

### ISSUE THREAD

**Issue by dialYun** [ant-design/ant-design#45007]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-list-cant-drag-fp2fxy)

### Steps to reproduce

在 codesandbox 示例中，拖拽 table 第一行数据即可复现！

### What is expected?

可以拖动排序

### What is actually happening?

无法拖动排序

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18 |
| System | macos |
| Browser | chrome 117.0.5938.62（正式版本） (arm64) |

**Comment by zombieJ** [comment]
做 EditTable 的时候不需要使用 Form.List，直接使用 Form.Item 作为一个整体来用。

**Comment by linxianxi** [comment]
稍微试了下 key 不能为 0（number 类型），可能是 dnd-kit 的 bug，没仔细研究。

**Comment by dialYun** [comment]
@zombieJ  https://codesandbox.io/s/4jsr95 请问是官网的这个例子么？

**Comment by dialYun** [comment]
@linxianxi   好的谢谢！
