### ISSUE TITLE
antd 5.0 支持获取@ant-design/cssinjs 的StyleProvider

### ISSUE THREAD

**Issue by laughing-pic-zhu** [ant-design/ant-design#45019]
### What problem does this feature solve?

让独立打包的antd可以配置hashPriority
antd 是单独打包在cdn里面，业务需要把:where的去掉。看文档是需要引用@ant-design/cssinjs并且修改hashPriority，但是我这种把antd 单独打包的不生效，需要把antd打包进node_modules中才能生效。

### What does the proposed API look like?

antd 内部能直接引用出@ant-design/cssinjs 的StyleProvider

**Comment by zombieJ** [comment]
你在打包的时候把 `@ant-design/cssinjs` 也一起 external 掉。让 antd 和业务代码都消费同一个实例即可。antd 内部会用很多三方库，让 antd 一个个透出来不现实的哈~

**Comment by Beven91** [comment]
如果是引用dist/ant.min.js呢

**Comment by Beven91** [comment]
> 你在打包的时候把 `@ant-design/cssinjs` 也一起 external 掉。让 antd 和业务代码都消费同一个实例即可。antd 内部会用很多三方库，让 antd 一个个透出来不现实的哈~

我是使用dist/antd.min.js ，这种场景没法external，建议还是做下兼容
