### ISSUE TITLE
name是个数组，validateFields验证的时候数据多了一层

### ISSUE THREAD

**Issue by BennnZhang** [ant-design/ant-design#45012]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-14-forked-dj289f)

### Steps to reproduce

直接输入username，点击submit

### What is expected?

获取到的username直接是个string

### What is actually happening?

获取到的username直接是个对象

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 17.0.1 |
| System | mac |
| Browser | 116.0.5845.187 |

**Comment by yoyo837** [comment]
`name={['username', 0]}`, 返回数组是预期的

**Comment by zombieJ** [comment]
```diff
-- name={['username', 0]}
++ name="username"
```
