### ISSUE TITLE
同时给Table 设置 virtual 和  sticky, 会报错

### ISSUE THREAD

**Issue by xiangdongbu** [ant-design/ant-design#45014]
### Reproduction link

[https://stackblitz.com/edit/react-3p246e?file=demo.tsx](https://stackblitz.com/edit/react-3p246e?file=demo.tsx)

### Steps to reproduce

同时 设置  virtual 和  sticky 会报错

### What is expected?

可以同时 设置  virtual 和  sticky，即可以进行页面整体滑动固定表头 并且 使用虚拟列表

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | MacOS 13.4.1 |
| Browser | 114.0.5735.198 |

**Comment by qingfengmy** [comment]
antd的最新版本支持这个功能了吗

**Comment by yoyo837** [comment]
> antd的最新版本支持这个功能了吗

删除 lock 文件, 重新安装即可
