### ISSUE TITLE
setFieldsValue 和 setFieldValue 在设置空对象时无法生效

### ISSUE THREAD

**Issue by kuangshu** [ant-design/ant-design#45010]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/setfieldsvalue-with-empty-object-5-9-2-fkkh4l?file=/demo.tsx:1487-1500)

### Steps to reproduce

点击 ”set empty object“ 按钮

### What is expected?

重置表单的 ”id“ 、 ”name“ 字段

### What is actually happening?

没有任何效果

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18 |
| System | win11 |
| Browser | Chrome116 |

---
使用 setFieldValue 单独设置字段同样无效

**Comment by zombieJ** [comment]
`setFieldsValue` 为合并更新，这是预期行为。感觉可以加个逻辑，对于 `null` 的做清理处理。

**Comment by kuangshu** [comment]
> `setFieldsValue` 为合并更新，这是预期行为。感觉可以加个逻辑，对于 `null` 的做清理处理。

单独使用 setFieldValue 对字段设置同样无效，如果这两个预期都是 merge 那这两个 api 就以 set 开头就很迷惑。

**Comment by Wxh16144** [comment]
> 对于 null 的做清理处理

具体是啥 case，可否由我来试试

**Comment by zombieJ** [comment]
> 单独使用 setFieldValue 对字段设置同样无效，如果这两个预期都是 merge 那这两个 api 就以 set 开头就很迷惑。

当存在 `{ a: 111, b: 888, user: { name: 222, age: 333 } }` 时，`setFieldsValue({ user: { name: 4, age: 5 } })` 如果当做纯设置就成了移除 `a` `b`，这反而会不符合预期，其实是一个选择问题。

**Comment by zombieJ** [comment]
测试了一下，现在也是这个行为。这个 issue 是个复合问题：
1. Form 的确是重置了值，将字段的 `value` 变成了 `undefined`
2. Input 的 `value` 变成 `undefined` 其实是从受控变成了非受控，所以它的 `value` 变了但是展示值没有变
3. `setFieldValue` 本身没有触发组件的更新，是个 bug

ref: https://codesandbox.io/s/setfieldsvalue-with-empty-object-5-9-2-forked-jsk72c?file=/demo.tsx

**Comment by TwoOld** [comment]
> > 单独使用 setFieldValue 对字段设置同样无效，如果这两个预期都是 merge 那这两个 api 就以 set 开头就很迷惑。
> 
> 当存在 `{ a: 111, b: 888, user: { name: 222, age: 333 } }` 时，`setFieldsValue({ user: { name: 4, age: 5 } })` 如果当做纯设置就成了移除 `a` `b`，这反而会不符合预期，其实是一个选择问题。

当存在 `{ a: 111, b: 888, user: { name: 222, age: 333 } }`，`setFieldsValue({ user: { name: 6 } })` ，结果 `age: 5` 依然存在也是符合预期的吗？

**Comment by scottjeremy** [comment]
> > > 单独使用 setFieldValue 对字段设置同样无效，如果这两个预期都是 merge 那这两个 api 就以 set 开头就很迷惑。
> > 
> > 
> > 当存在 `{ a: 111, b: 888, user: { name: 222, age: 333 } }` 时，`setFieldsValue({ user: { name: 4, age: 5 } })` 如果当做纯设置就成了移除 `a` `b`，这反而会不符合预期，其实是一个选择问题。
> 
> 当存在 `{ a: 111, b: 888, user: { name: 222, age: 333 } }`，`setFieldsValue({ user: { name: 6 } })` ，结果 `age: 5` 依然存在也是符合预期的吗？

我也遇到这个问题了，请问解决了吗？
