### ISSUE TITLE
Tag 组件带上 Icon 时，文字与图标没有垂直居中对齐

### ISSUE THREAD

**Issue by Elliott-Hu** [ant-design/ant-design#45021]
### Reproduction link

[https://ant-design.antgroup.com/components/tag-cn](https://ant-design.antgroup.com/components/tag-cn)

### Steps to reproduce

官方提供的文档示例页面搜索 With icon 可以复现

### What is expected?
![image](https://github.com/ant-design/ant-design/assets/16644716/02bc2822-1ab7-4f9f-8e4a-5a2d53603c9e)

希望使用时图标与文字不用做样式处理，默认垂直居中

### What is actually happening?

图标相对图片位置偏上，行高不一致

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by LiangJavaDS** [comment]
实现思路是line-height === 容器height？

**Comment by LiangJavaDS** [comment]
@MadCcc  实现思路是line-height === 容器height吗？如果不牵扯太多是否能让我尝试修复？

**Comment by zomblemta** [comment]
我在控制台查了一下样式，是icon的vertical-align值略大，改到-.19em差不多

**Comment by zomblemta** [comment]
再次排查后，我发现是因为icon的vertical-align的单位为em，当我把外层的div的字体大小调整到12px之后，样式就正常了。

**Comment by MadCcc** [comment]
@liangkuku PR welcome~

**Comment by liangkuku** [comment]
> @liangkuku PR welcome~

I will try to fix it.

**Comment by liangkuku** [comment]
My approach is to change the parent span tag of the icons and text  from `display: 'inline-block'` to `display: 'inline-flex'` in order to achieve vertical centering.Do you think there is any issue with this approach?
![image](https://github.com/ant-design/ant-design/assets/62460957/bd7ed301-974d-48f0-b028-be84c095a704)

**Comment by liangkuku** [comment]
I went to see the demo again.It seems that the icon has been centered now.
![image](https://github.com/ant-design/ant-design/assets/62460957/434c0e5b-5697-44c5-9f62-03d774c05297)
