### ISSUE TITLE
table 组件 token: cellPaddingBlock 无效

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#45024]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zu-jian-chi-cun-antd-5-9-2-forked-ggsg97?file=/demo.tsx:198-214)

### Steps to reproduce

```tsx
import "./index.css";
import { ConfigProvider, Table } from "antd";

const App: React.FC = () => {
  return (
    <ConfigProvider
      theme={{
        components: {
          Table: {
            cellPaddingBlock: 0,
            cellPaddingBlockMD: 0,
            cellPaddingBlockSM: 0,
            cellPaddingInline: 0
          }
        }
      }}
    >
      <Table
        columns={[
          { title: "Name", dataIndex: "name" },
          { title: "Age", dataIndex: "age" }
        ]}
        dataSource={[
          { key: "1", name: "John Brown", age: 32 },
          { key: "2", name: "Jim Green", age: 42 },
          { key: "3", name: "Joe Black", age: 32 }
        ]}
      />
    </ConfigProvider>
  );
};

export default App;
```

### What is expected?

通过 ConfigProvider 设置表格上下边距（cellPaddingBlock）有效效

### What is actually happening?

通过 ConfigProvider 设置表格上下边距（cellPaddingBlock）无效

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

**Comment by ZhenhuaChen** [comment]
the same problem 😑😑
