### ISSUE TITLE
Ant Design Library v2.0.1 加载失败

### ISSUE THREAD

**Issue by skyverd** [ant-design/ant-design#4504]
Axure RP8  8.0.0.3322 导入library的时候，提示 **invalid file** unable to load file library.ant.design_Web标准包.rplib.

而Ant UX.rplib导入成功。求解

**Comment by yingxirz** [comment]
试试重启

**Comment by afc163** [comment]
@skyverd 可以继续回复，这里先关了。

**Comment by skyverd** [comment]
重启了没用，依然提示错误，好奇怪 我的OS版本 10.11.6

**Comment by gitoneman** [comment]
@skyverd 你解决了吗? 我也出现了这个问题

**Comment by skyverd** [comment]
@gitoneman 没有解决

**Comment by iloveyo123u1** [comment]
我也遇到这样的问题了， mac

**Comment by iloveyo123u1** [comment]
@skyverd   兄弟 你解决了吗   如果解决的话， 能不能分享下解决的方法  感恩

**Comment by yingxirz** [comment]
@skyverd @iloveyo123u1 @gitoneman 

你们遇到的library在Axure加载不成功的问题，的确偶尔会发生，之前有个用户也遇到这样的问题，我下载好后，从我的电脑上传给他，竟然就可以了。

目前没有找到原因和确定的解决方案，你可以尝试这样解决：

1. 使用正版Axure并更新至最新版本（8.0以上）
2. 导入别人发给你的library文件，最好是他加载成功过的(下载地址：library.ant.design）

如果完成以上两步都行不通，我也觉得很无奈，可以试试邮件给Axure问问。
