### ISSUE TITLE
[Feature Wanted]Modal 类组件动画是否可暴露 rc-motion 组件 motionDeadline 的配置

### ISSUE THREAD

**Issue by youngBrain1893** [ant-design/ant-design#45042]
### What problem does this feature solve?

微前端体系下，子系统切换相关样式被移除（通过 Modal#confirm 触发子系统切换），导致 rc-motion 动画无法执行完成，导致
1. Modal 无法移除
2. body 无法滚动

问题复现：
[https://codesandbox.io/s/dazzling-rgb-57vlzg?file=/src/App.js](https://codesandbox.io/s/dazzling-rgb-57vlzg?file=/src/App.js)
<img width="558" alt="image" src="https://github.com/ant-design/ant-design/assets/16771528/9588a04d-a9c9-4c4b-bb35-31c9d4d052dd">

1. 点击 【Modal Confirm】 按钮触发弹窗
2. 点击 Confirm 内【OK】关闭弹窗（处理逻辑包含移除 antd#modal 相关样式）
3. 此时页面样式丢失，Modal#Confirm 内容一直不消失，body 不可滚动
4. 点击【Restore Style】Modal 重新出现动画完成 Modal#Confirm 内容消失，body 可滚动

相关链接：
1. [Modal -> Dialog 内部使用 rc-motion](https://github.com/react-component/dialog/blob/master/src/Dialog/Content/index.tsx)
2. [rc-motion API 文档](https://github.com/react-component/motion)

### What does the proposed API look like?

Modal 属性添加 motionDeadline 透传，同时 Modal.method 可配置

**Comment by MadCcc** [comment]
用 `afterClose` 属性

**Comment by youngBrain1893** [comment]
> 用 `afterClose` 属性
> 
> https://codesandbox.io/s/loving-dust-kwq28h

不太能直接调整为 `afterClose`
`afterClose` 属性和 `onOk` 逻辑上是有差异的，onOk 是点击 OK 相关内容，afterClose 在 cancel，ok 阶段都会触发
