### ISSUE TITLE
在路由切换时设置为virtual的Table 报错 Cannot read properties of null (reading 'querySelector') 

### ISSUE THREAD

**Issue by clown-Jack** [ant-design/ant-design#45053]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xy9z6x?file=/home.jsx)

### Steps to reproduce

about页面或者home页面中table表格只要有一个设置virtual后，路由设置lazy懒加载之后，切换路由即可复现，去掉table的virtual属性则不报错

### What is expected?

about页面或者home页面中table表格只要有一个设置virtual后，路由设置lazy懒加载之后，切换路由不报错

### What is actually happening?

about页面或者home页面中table表格只要有一个设置virtual后，路由设置lazy懒加载之后，切换路由报错

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | ^18.2.0 |
| System | windows64 |
| Browser | Chrome最新版本 |

**Comment by MadCcc** [comment]
Fixed in 5.9.3
