### ISSUE TITLE
Button 组件配色失败

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#45054]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/an-niu-lei-xing-antd-5-9-2-forked-79nrz6?file=/demo.tsx)

### Steps to reproduce

针对于 Button 组件的主题配色，存在以下 token：
colorPrimaryBg （主题背景色，type="primay" 时的背景色？）
colorPrimaryText （主题文本色， type="primay" 时的字体颜色？）
colorPrimaryActive （主题激活色）
colorPrimaryTextActive （主题激活文本色）
colorPrimaryBgHover （主题悬浮色）
colorPrimaryTextHover （主题悬浮文本色）
但这些 token 除 colorPrimaryActive 并不能在官方文档中找到
但能在类型定义中找到，并有相关解释
在使用这些 token 时，除 colorPrimaryActive 按预期外，其他 token 并没有起到作用

### What is expected?

根据类型定义文件的解释，按预期效果显示

### What is actually happening?

除 colorPrimaryActive 按预期外，其他 token 并没有起到作用

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/theme-editor-cn
可以在这里切换 “组件” 类别来尝试修改组件 token。

简易修改 Button 主题可以直接修改 `colorPrimary` 来实现。
https://codesandbox.io/s/an-niu-lei-xing-antd-5-9-2-forked-w6xn6r

**Comment by guaijie** [comment]
> https://ant-design.antgroup.com/theme-editor-cn 可以在这里切换 “组件” 类别来尝试修改组件 token。
> 
> 简易修改 Button 主题可以直接修改 `colorPrimary` 来实现。 https://codesandbox.io/s/an-niu-lei-xing-antd-5-9-2-forked-w6xn6r

我需要的不是简单的修改主题色，包括主题色，主题字体色，主题悬浮色，主题悬浮字体色，主题激活色和主题激活背景色
而这些变量似乎可以提供我这些可能，但很可惜不行

**Comment by afc163** [comment]
> 我需要的不是简单的修改主题色，包括主题色，主题字体色，主题悬浮色，主题悬浮字体色，主题激活色和主题激活背景色
而这些变量似乎可以提供我这些可能，但很可惜不行

可否告知一下具体想修改成什么样？

**Comment by guaijie** [comment]
> > 我需要的不是简单的修改主题色，包括主题色，主题字体色，主题悬浮色，主题悬浮字体色，主题激活色和主题激活背景色
> > 而这些变量似乎可以提供我这些可能，但很可惜不行
> 
> 可否告知一下具体想修改成什么样？

type="primary"
![image](https://github.com/ant-design/ant-design/assets/30885718/6577f355-18fb-457a-9541-3aeb9cb05943)
悬浮后的背景
![image](https://github.com/ant-design/ant-design/assets/30885718/dbfc5ca9-1ba2-4f31-8673-9ff42c3b2c03)

我不知道是否是我并不理解 map token

**Comment by guaijie** [comment]
> > 我需要的不是简单的修改主题色，包括主题色，主题字体色，主题悬浮色，主题悬浮字体色，主题激活色和主题激活背景色
> > 而这些变量似乎可以提供我这些可能，但很可惜不行
> 
> 可否告知一下具体想修改成什么样？

这样写也没有任何效果，但是为何 ts 报错了，明明 designToken 包含了该有的数据返回
![image](https://github.com/ant-design/ant-design/assets/30885718/4f919e87-04dd-4a2f-9a75-77641cab62f3)

**Comment by afc163** [comment]
@MadCcc 可以看看怎么配比较好。我试了一下这里主按钮背景确实没有语义化的 token 能用。

**Comment by Koomita** [comment]
重新打开issue吧，目前这问题还没解决

**Comment by MadCcc** [comment]
最新版本中更多的组件 token 已经支持，看看是否满足需求？
![image](https://github.com/ant-design/ant-design/assets/27722486/09dcfef6-0714-4c11-91d5-f04791b98358)

**Comment by forwells** [comment]
@guaijie @Koomita 
我在本地开发遇到了这个问题, theme中配置了colorPrimary但是Button颜色显示不正确
但是build构建后正常
原因是antd本身计算的样式可能被项目中其他样式覆盖了
最好用cssinjs库把config provider中的组件都包裹起来, 我的已经正常了!
