### ISSUE TITLE
Descriptions 的 暗黑主题不显示

### ISSUE THREAD

**Issue by dzqdzq** [ant-design/ant-design#45052]
### Reproduction link

[https://github.com/dzqdzq/prefabWebUI](https://github.com/dzqdzq/prefabWebUI)

### Steps to reproduce

在index.tsx文件

```tsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import { ConfigProvider, theme } from "antd";
import './index.css';

const theme2 = { 
    algorithm: theme.darkAlgorithm,// 使用暗黑模式，就显示不了右边的属性面板。注释就正常了
};
createRoot(document.getElementById('container')).render(
    <ConfigProvider theme={theme2}>
        <App />
    </ConfigProvider>
);
```

### What is expected?

显示暗黑主题的属性面板

### What is actually happening?

不显示

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

---
感谢antd团队制作的UI库，非常棒，非常Nice！

**Comment by zombieJ** [comment]
看了一下，直接设置 html 背景色为黑色样式是对的：
<img width="993" alt="截屏2023-09-25 11 40 56" src="https://github.com/ant-design/ant-design/assets/5378891/5f462fff-b164-4286-b55b-64fc8867507e">


你的最外面需要包一个 Layout，Layout 会提供背景颜色：
https://ant-design.antgroup.com/components/layout-cn?theme=dark

另外，我看 html padding 什么都没有重置。最好还要引入一下 `dist/reset.css` 哈~

**Comment by dzqdzq** [comment]
> 看了一下，直接设置 html 背景色为黑色样式是对的： <img alt="截屏2023-09-25 11 40 56" width="993" src="https://user-images.githubusercontent.com/5378891/270222420-5f462fff-b164-4286-b55b-64fc8867507e.png">
> 
> 你的最外面需要包一个 Layout，Layout 会提供背景颜色： https://ant-design.antgroup.com/components/layout-cn?theme=dark
> 
> 另外，我看 html padding 什么都没有重置。最好还要引入一下 `dist/reset.css` 哈~

非常感谢
