### ISSUE TITLE
Controls present in the Calendar are not accessible using keyboard.

### ISSUE THREAD

**Issue by msftedad** [ant-design/ant-design#45058]
### Reproduction link

[https://codepen.io/afc163-1472555193/pen/oNXqWGP](https://codepen.io/afc163-1472555193/pen/oNXqWGP)

### Steps to reproduce

Hit the URL: DatePicker - Ant Design Demo (codepen.io).
TAB to any calendar filed and expand it.
Verify whether controls present in the Calendar are not accessible using keyboard or not.

### What is expected?

Controls present in the Calendar should be accessible using keyboard.

### What is actually happening?

Controls present in the Calendar are not accessible using keyboard.

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 17.0.2 |
| System | Windows 11 Enterprise 22H2 Version: 22621.2283 |
| Browser | Edge Version 116.0.1938.81 (Official build) (64-bit) |

Attachments:

https://github.com/ant-design/ant-design/assets/93735775/3f4316d4-f879-4403-8247-fb3ba1a118d3

**Comment by MadCcc** [comment]
shift + pgUp/pgDn?

**Comment by msftedad** [comment]
Hi @MadCcc,Issue still repro'ing even after using shift + pgUp/pgDn. Please find the below attachment.

https://github.com/ant-design/ant-design/assets/93735775/f443dd21-0e5c-4212-aa58-cec9de6abccb

**Comment by msftedad** [comment]
Hi @MadCcc , Is there any update on this issue?

**Comment by msftedad** [comment]
Hi @MadCcc, issue is still repro'ing even after using shift + pgUp/pgDn.Please reopen this issue.
