### ISSUE TITLE
Dropdown change overlay to menu, RuntimeError

### ISSUE THREAD

**Issue by swordow** [ant-design/ant-design#45059]
### Reproduction link

[https://codepen.io/swordow/pen/GRPdJwv]
(https://codepen.io/swordow/pen/GRPdJwv)

### Steps to reproduce

Change overaly to menu 

### What is expected?

Render as same as using "overlay" before changing to "menu".

### What is actually happening?

```
ERROR
Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at React$$1.Children.only (webpack:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js?:2957:39)
    at renderOverlay (webpack:///./node_modules/antd/es/dropdown/dropdown.js?:158:66)
    at eval (webpack:///./node_modules/rc-dropdown/es/Overlay.js?:14:24)
    at mountMemo (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:15442:19)
    at Object.useMemo (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:15738:16)
    at useMemo (webpack:///./node_modules/react/cjs/react.development.js?:1521:21)
    at wrappedHook (webpack:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js?:2798:14)
    at eval (webpack:///./node_modules/rc-dropdown/es/Overlay.js?:11:74)
    at renderWithHooks (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:14803:18)
    at updateForwardRef (webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:16816:20)
```

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 16.14.0 |
| System | Windows10 |
| Browser | Chrome 117.0.5938.92 |

Using Overlay
![image](https://github.com/ant-design/ant-design/assets/7107003/3ad1f1b4-cdb1-4319-80e2-058991917f74)

Using menu
![image](https://github.com/ant-design/ant-design/assets/7107003/dc983b45-e4eb-4c33-9700-00d61e97955f)

In codepen, Dropdown working as a column table does not work. It compiles failed. An in my case, it produce the runtime error..

**Comment by swordow** [comment]
> Hello @swordow. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @swordow, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

Done. The traceback is not same, but i think it is the same problem.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/41378#issuecomment-1477938291

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/42256#issuecomment-1541601316
