### ISSUE TITLE
Select组件中文文档Select props样式混乱

### ISSUE THREAD

**Issue by geekris1** [ant-design/ant-design#45066]
### Reproduction link
对应代码
[https://github.com/ant-design/ant-design/blob/master/components/select/index.zh-CN.md](https://github.com/ant-design/ant-design/blob/master/components/select/index.zh-CN.md)
对应页面

[https://ant.design/components/select-cn#select-props](https://ant.design/components/select-cn#select-props)
 

### Steps to reproduce

1.打开上述链接 即可查看 （Select英文文档是好的）

### What is expected?

Select Props能以表单的形式在文档中正常展示（目前情况如下图）

### What is actually happening?

样式混乱

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | react |
| System | macOS |
| Browser | chrome 117 |

<img width="1418" alt="image" src="https://github.com/ant-design/ant-design/assets/35247521/9d0acb97-10e7-4c35-bef9-4efdc87e1dc0">

**Comment by geekris1** [comment]
@MadCcc 不好意思，打扰了。 二货提的pr没解决这个issuse 咋就close了 能reopen吗👀

**Comment by yoyo837** [comment]
应该需要等重新部署吧

**Comment by afc163** [comment]
解决了 https://github.com/ant-design/ant-design/pull/45065 ，文档还没部署。
