### ISSUE TITLE
在nextjs app router模式下使用antd时，自定义类名优先级低于antd优先级

### ISSUE THREAD

**Issue by Mr-Nobody-li** [ant-design/ant-design#45060]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/goofy-stitch-v69742?file=%2Fsrc%2Fapp%2Fpage.tsx%3A10%2C3)

### Steps to reproduce

重现链接打开后，Carousel的class传入了一个类，但是并没有生效，发现是因为优先级低于antd内部样式。后来发现因为适配了nextjs app router模式闪烁问题，优先级才会变低
https://ant-design.antgroup.com/docs/react/use-with-next-cn#%E4%BD%BF%E7%94%A8-app-router

### What is expected?

自定义类名（css module和tailwind）优先级高于antd优先级

### What is actually happening?

在nextjs app router模式下使用antd时，自定义类名（css module和tailwind）优先级低于antd优先级

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | window10 |
| Browser | google |

**Comment by MadCcc** [comment]
由于 antd 的样式也自带具有优先级的选择器，目前只能够手动提高自定义样式的选择器优先级，tailwind 可以选择开启 important。

你也可以使用这种方法来全局提升你的 css 优先级：
```diff
--  .my-btn {
++  #root .my-btn {
      background: red;
    }
```
Ref: https://ant-design.antgroup.com/docs/react/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8
