### ISSUE TITLE
v4.24.14: Select component scroll bar does not display, v4.24.8 displays normally

### ISSUE THREAD

**Issue by Delphier** [ant-design/ant-design#45078]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-14-forked-z57pkm?file=/demo.tsx)

### Steps to reproduce

Click the select component, the scrollbar does not display.

### What is expected?

Display the scrollbar.

### What is actually happening?

Scrollbar does not display.

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.2 |
| System | Windows 11 |
| Browser | Chrome 117.0.5938.92 |

---
The v4.24.8 version displays normally.

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/5cbf579a-d987-40fc-b149-757bed9364ce)
Seems nothing wrong.

**Comment by Delphier** [comment]
Sorry, I sent the wrong sandbox link before. The previous one was v4.24.8. I have updated it. Please verify it again.
