### ISSUE TITLE
.2.6.1@antd\lib\style\index.css Unexpected token (10:5)

### ISSUE THREAD

**Issue by liangxp** [ant-design/ant-design#4507]
#### Environment(required)

- antd version:2.6.1
- OS and its version:windows 10
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.

 I just imported Button from antd 
#### What happen?

Failed to compile.

Error in f:/web/zqmy/~/.2.6.1@antd/lib/style/index.css Module parse failed: f:\web\zqmy\node_modules\.2.6.1@antd\lib\style\index.css Unexpected token (10:5) You may need an appropriate loader to handle this file type. SyntaxError: Unexpected token (10:5) @ f:/web/zqmy/~/.2.6.1@antd/lib/button/style/css.js 3:0-32

#### Re-producible online demo

`import React from 'react';
import {Button} from 'antd';

const Products = (props) => (
    <div>
    
  <h2>List of Products</h2>
  <Button type="primary">Primary</Button>
    </div>
);

export default Products;`

**Comment by benjycui** [comment]
Which version of `antd` did you use before?

And it will be better to provide a re-producible repo.

**Comment by benjycui** [comment]
IMO, it's OK:

```bash
➜  /tmp cat node_modules/antd/lib/button/style/css.js
'use strict';

require('../../style/index.css');

require('./index.css');%
```

**Comment by liangxp** [comment]
before use 2.5.2

**Comment by afc163** [comment]
![npm](https://cloud.githubusercontent.com/assets/465125/20958772/4b77c798-bc92-11e6-911b-c9aaae21ef08.jpg)

**Comment by liangxp** [comment]
yes  have rf

**Comment by benjycui** [comment]
> And it will be better to provide a re-producible repo.

**Comment by afc163** [comment]
无法重现就只能关了，给出重现示例就再 reopen 吧。
