### ISSUE TITLE
可编辑表格，中文输入法和输入法符号setFieldValue后结果不一致，中文符号会在结果后面添加一个中文字符

### ISSUE THREAD

**Issue by mumulx** [ant-design/ant-design#45073]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-fxvr4l)

### Steps to reproduce

清空第一行name的内容，使用中文输入法，输入`//`。清空内容，切换英文输入法，输入`//`。

### What is expected?

中文输入法快捷键的结果setFieldValue后不添加符号，最终的结果应和英文输入法一致

### What is actually happening?

使用中文输入法setFieldValue后，结果后面会添加一个中文字符

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.X |
| System | win10 |
| Browser | google 116.0.5845.188 |

---
场景：为可编辑表格添加快捷键使得`//`和`、、`可以复制第一行的name，`..`和`。。`可以复制上一行的name

**Comment by zombieJ** [comment]
参考一下 #44898 哈，本质原因都是因为 React 的输入事件处理不同步导致的。
