### ISSUE TITLE
TreeSelect下拉框的样式没办法修改，组件中使用的是自己定义的div来代替的浏览器中的滚动条。是否支持修改滚动条样式

### ISSUE THREAD

**Issue by Z3-FE** [ant-design/ant-design#45079]
### What problem does this feature solve?

修改下拉框滚动条样式。因为一开始滚动条并不展示，可能用户不知道底部还有可以选择的数据，所以希望数据超出范围后，能够一直展示滚动条

### What does the proposed API look like?

暴露出一个api，能够直接控制滚动条的展示

**Comment by afc163** [comment]
Try `virtual={false}`.

**Comment by Z3-FE** [comment]
> Try `virtual={false}`.尝试 virtual={false} 。
在proComponent中，使用fieldProps={ virtual:false, }并没有隐藏滚动条

**Comment by Z3-FE** [comment]
> Try `virtual={false}`.尝试 virtual(虚拟)={false} 。尝试 virtual(虚拟)={false} 。



> > Try `virtual={false}`.尝试 virtual(虚拟)={false} 。
> > 在proComponent中，使用fieldProps={ virtual(虚拟):false, }并没有隐藏滚动条，
使用的是import ProTable from '@ant-design/pro-table'; 组件

**Comment by afc163** [comment]
这样需要提到 pro-components 的仓库中。

**Comment by MadCcc** [comment]
@afc163 虚拟滚动暴露滚动条配置是不是好些？类似问题以前也提过不少次，`virtual={false}` 也不一定是用户期望

**Comment by afc163** [comment]
@MadCcc 对，需要暴露。还可以给一些虚拟滚动条的样式定制方式。

**Comment by MadCcc** [comment]
Fixed in https://github.com/react-component/virtual-list/pull/237
