### ISSUE TITLE
日历选择不超过7天范围，添加open属性，点击出现bug

### ISSUE THREAD

**Issue by xuqichao0102** [ant-design/ant-design#45077]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8g5lxp?file=/demo.js)

### Steps to reproduce

日历选择不超过7天范围，添加open属性，聚焦时无论点击任何地方都会切换select高量

### What is expected?

没有bug

### What is actually happening?

有bug

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18.2.0 |
| System | ios |
| Browser | google |

**Comment by MadCcc** [comment]
没太明白你遇到了什么问题，能不能描述的更详细点或者提供录屏

**Comment by ILoveChy** [comment]
我大概理解在说什么了,说的是
先选个1号到7号,再点开日历面板,想要的是能看到选中了1-7号,现在demo里加上openChange的效果,打开之后日期也没了 1-7的高量也没了.
But,这是因为 value是优先取值的dates的啊,dates就是日历面板的值,openChange方法里你不也看到了,清空了的.
And,这也是一部分人的需求,就比如选1-7号,限制了7天之后,我想选去年的某个日期,我只能清空日期才能再选,加上openChange清空就可以每次打开都是新的一天
@xuqichao0102 @MadCcc

**Comment by ILoveChy** [comment]
如果不是这个意思,别打我..
