### ISSUE TITLE
Type primary is not applied to tours first step 

### ISSUE THREAD

**Issue by AmrAhmedA** [ant-design/ant-design#45081]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/non-modal-antd-5-9-3-forked-hnx5tf?file=/demo.tsx)

### Steps to reproduce

It is stated in the [docs](https://ant.design/components/tour#tourstep) that the type prop affects the background color and text color.
Lets say that the tour steps are in the following order

```jsx
const steps: TourProps["steps"] = [
    {
      title: "Upload File",
      description: "Put your files here.",
      cover: (
        <img
          alt="tour.png"
          src="https://user-images.githubusercontent.com/5378891/197385811-55df8480-7ff4-44bd-9d43-a7dade598d70.png"
        />
      ),
      target: () => ref1.current,
      type: "primary" // the first step has antd primary color as background 
    },
    {
      title: "Save",
      description: "Save your changes.",
      target: () => ref2.current
    },
    {
      title: "Other Actions",
      description: "Click to see other actions.",
      target: () => ref3.current
    }
  ];
  ```
![chrome-capture-2023-8-25 (3)](https://github.com/ant-design/ant-design/assets/47694180/d1d7e861-4715-43d2-be29-1bf1817cc280)

### What is expected?
I want to apply the type primary color as the background of the first step only.

### What is actually happening?
The primary color of the first tour step is not applied when the component mounts, the primary color is applied when visiting the first step for the 2nd time using the previous button. 

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | MacOs |
| Browser |  Google chrome Version 116.0.5845.187 (Official Build) (arm64) |

**Comment by Zzongke** [comment]
- ant-design-tour
![image](https://github.com/ant-design/ant-design/assets/65376724/35de706b-3259-4f14-b62f-968dd00372db)
- rc-tour
![image](https://github.com/ant-design/ant-design/assets/65376724/ee421c8b-0108-43d9-be26-b3869bac6da0)

@MadCcc 是因为没传defaultCurrent和current时，这两个值为undefined，可以的話我來pr解決？

**Comment by MadCcc** [comment]
这个 hook 并不好，把底层 rc-tour 的内部逻辑复刻了一遍。我这边正在处理了

**Comment by Zzongke** [comment]
> 这个 hook 并不好，把底层 rc-tour 的内部逻辑复刻了一遍。我这边正在处理了

好的
