### ISSUE TITLE
upload FormItem的valuePropsName不起作用

### ISSUE THREAD

**Issue by lppoi** [ant-design/ant-design#45084]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2y6m7z?file=/index.js:357-360)

### Steps to reproduce

选择完文件点击上传后报错fileList.forEach is not function

### What is expected?

选择完文件点击上传后，Form中的值应该为fileList而不是{file,fileList}

### What is actually happening?

Form中的值{file,fileList}

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome 116 |

**Comment by MadCcc** [comment]
配合 `getValueFromEvent` 使用：https://codesandbox.io/s/antd-reproduction-template-forked-fqhc6g

文档参考：https://ant.design/components/form-cn#components-form-demo-validate-other

**Comment by lppoi** [comment]
用getValueProps转一下是正常的

> 配合 `getValueFromEvent` 使用：https://codesandbox.io/s/antd-reproduction-template-forked-fqhc6g
> 
> 文档参考：https://ant.design/components/form-cn#components-form-demo-validate-other

![image](https://github.com/ant-design/ant-design/assets/64509267/0f602c9d-caef-4559-9da2-9158e30f1297)
我是用的自定义上传 Upload event内容还是上传前的值
