### ISSUE TITLE
antd官方源码在windows跑不起来，在mac电脑能跑，官方是否有解决方案

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#4508]
ERROR in ./~/bisheng/lib/utils/data.js

2809: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| },
|   },
|   'components\upload\demo\avatar': function () {
|   return new Promise(function (resolve) {
|     require.ensure([], function (require) {
 @ ./~/bisheng/tmp/entry.index.js 12:11-42

**Comment by afc163** [comment]
目前官方不提供 windows 的本地源码开发支持，不过如果你可以解决的话，不妨给我们 PR。

**Comment by bochen2014** [comment]
我搞定了. 在windows上可以跑起来. 主要是bisheng的问题

**Comment by bochen2014** [comment]
明天去bisheng提一个PR,之后就可以在windows上跑了

**Comment by afc163** [comment]
:+1: 提前感谢贡献

**Comment by fhqdgv** [comment]
现在run dist还是报错 spawn atool-build ENOENT

**Comment by lileilei** [comment]
@bochen2014  那到底如何才能在window上跑希望把解决方案说一下。貌似现在还不支持在window上npm  run dist

**Comment by benjycui** [comment]
@lileilei 拉最新 ant-design 的代码，`rm -rf node_modules && npm i && npm start`

**Comment by lileilei** [comment]
@benjycui   首先谢谢你的回答，但是npm start 本身就没有问题。是npm run dist 报错 
@bochen2014 这位仁兄不是说是bisheng的问题，已经解决了。希望求解决方案！

环境：  window10   node v7.7.3

**Comment by benjycui** [comment]
`npm run dist` 应该是 atool-build 的问题。。

**Comment by bochen2014** [comment]
https://github.com/benjycui/bisheng/pull/62

很长时间没试了.. 当初确实是在我的windows 上跑起来了

**Comment by benjycui** [comment]
> 很长时间没试了.. 当初确实是在我的windows 上跑起来了

@bang88 不久前修过了。

**Comment by bang88** [comment]
@lileilei 确实是`antd-tools`的问题 https://github.com/ant-design/antd-tools/blob/master/lib/gulpfile.js#L32

有点暴力。 如果要支持跨平台开发的话，可以考虑使用对应的node模块，不用原生的shell.

一般不需要`npm run dist`吧，你要干什么?

**Comment by benjycui** [comment]
@lileilei @bang88 有空可以 PR，但是这个场景的确不常见，毕竟对 antd 合理的改动，应该 PR 到 ant-design，至于 antd 觉得应该由业务层实现的功能，可以考虑封装业务组件，没必要自行发布一个 antd 的分支版本。

**Comment by bang88** [comment]
这个目前来看不用修改。

**Comment by lileilei** [comment]
@bang88 @benjycui  非常感谢，我们想基于antd写些业务组件，我先手动改了antd-tools用着先

**Comment by afc163** [comment]
@lileilei 可以来个 PR

**Comment by lileilei** [comment]
@afc163 已经在 antd-tools pr代码，我的window上已经没问题了

**Comment by afc163** [comment]
报什么错？你的 node 是多少版本？

**Comment by lileilei** [comment]
node v   7.7.3 其他地方箭头函数没问题！

**Comment by afc163** [comment]
你确定不是这里的问题？https://github.com/ant-design/antd-tools/pull/36/files#diff-72802b7cccf17f1af2219db95ee31c51L13

**Comment by lileilei** [comment]
没有选择ws编辑器js版本，习惯性格式化了一下可能把这里搞错了。还是你来改吧。我确定webpack里面的错误不是这里导致的

**Comment by huangyl15** [comment]
请问 现在window能跑了吗，我还是跑不起来，哪位搞定了，可以分享下吗？？

**Comment by Lizhooh** [comment]
@afc163 为什么不提供

**Comment by yoyo837** [comment]
老帖子了，现在还不能跑吗？

**Comment by zjjjjjjjjjjd** [comment]
为啥现在还是没法跑
