### ISSUE TITLE
Virtual table body has issue after resizing the viewport #44889

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#45095]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-antd-5-9-1-forked-9mxrl9?file=/demo.tsx)

### Steps to reproduce

see #44889

### What is expected?

see #44889

### What is actually happening?

see #44889

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
hmm, I cant reproduce it on the codepen. but my project uses latest still experience issues on resize ..

**Comment by afc163** [comment]
Please upgrade to latest antd version and reinstall node_modules, don't forget remove your lock files.

**Comment by AsuraKev** [comment]
that worked lol thanks
