### ISSUE TITLE
Table Overflow in Modal Component

### ISSUE THREAD

**Issue by rick-chou** [ant-design/ant-design#45097]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/empty-paper-fgg3kd?file=%2Fsrc%2FApp.tsx%3A26%2C1)

### Steps to reproduce

click the show button, then you will see

### What is expected?

This was normal in older versions because the container on the outer layer of antd had max-width:100% set, but it seems to have been removed in recent versions, which is causing the problem.

### What is actually happening?

as the title

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.2.0 |
| System | macos 12.6.3 |
| Browser | chrome |

---
this link shows the normal case
https://codesandbox.io/s/happy-wood-j6v7dg?file=/src/App.tsx:0-530

**Comment by zombieJ** [comment]
Table will be greedy and you can wrap to handle this~

https://codesandbox.io/p/sandbox/spring-shadow-9wk2ty?file=%2Fsrc%2FApp.tsx%3A16%2C57
