### ISSUE TITLE
在使用sass的情况下如何进行主题定制？

### ISSUE THREAD

**Issue by focus7eleven** [ant-design/ant-design#4509]
官方给出的定制主题方法是针对less的，请问用了sass之后能用package.theme这种方法来进行主题定制么？

**Comment by afc163** [comment]
目前 antd 没有提供 scss 的样式源码。如果你的项目是用 scss 开发的，你可以将 scss 的业务样式代码和 antd 的 less 样式代码分开各自引用即可。主题定制依旧和文档提供的方式一致。
