### ISSUE TITLE
在window11系统下，edge浏览器开启ie11模式，无法使用antd库

### ISSUE THREAD

**Issue by Atw-Lee** [ant-design/ant-design#45105]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/menu-cn/#header](https://4x-ant-design.antgroup.com/components/menu-cn/#header)

### Steps to reproduce

该环境下打开官网，无法进行操作

### What is expected?

正常操作

### What is actually happening?

不晓得

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | * |
| System | window11 |
| Browser | edge开启ie11模式 |

---
3的版本可以，我们准备降低版本，看降到4.?多少可以，但是没有成功，但这对我们来说比较困难。

**Comment by zombieJ** [comment]
参考一下文档哈，你需要配置一下 polyfill 补齐能力：https://4x-ant-design.antgroup.com/docs/react/introduce-cn#%E5%85%BC%E5%AE%B9%E7%8E%AF%E5%A2%83

另外，V5 使用兼容配置也能兼容 IE11。如果你是从 v3 升级，可以考虑用最新的哈~
