### ISSUE TITLE
使用 Modal.info(), content 属性中的内容较长时，会超出 Modal 边界

### ISSUE THREAD

**Issue by weijie-he** [ant-design/ant-design#45102]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wr72f7?file=/demo.tsx)

### Steps to reproduce

在content内部输入一行较长的文本，例如:
        <p>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</p>
![image](https://github.com/ant-design/ant-design/assets/16081489/a3281531-1767-4553-abf2-fd1e0b45d679)

### What is expected?

content 中的内容不会超出了Modal 边界

### What is actually happening?

content 中的内容超出了Modal 边界

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.2.0 |
| System | win11 |
| Browser | edge 117 |

---
之前提过一个相同的 issue：https://github.com/ant-design/ant-design/issues/39247
当时的版本修复了，现在这个版本（5.9.3）又出现了

**Comment by afc163** [comment]
应该是某个版本又改丢了。

**Comment by vaibhav111tandon** [comment]
Hi @afc163 Anyone working on this issue? Can i take this up?

**Comment by kiner-tang** [comment]
> Hi @afc163 Anyone working on this issue? Can i take this up?

PR welcome!!
