### ISSUE TITLE
希望message组件能提供关闭按钮

### ISSUE THREAD

**Issue by undefined9999** [ant-design/ant-design#45104]
### What problem does this feature solve?

目前用户无法主动关闭message提示,只能等倒计时结束自动关闭, 会对页面上操作有干扰作用.

### What does the proposed API look like?

增加一个showClose类似字段的配置,来支持控制此message是否支持手动关闭

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/38702#issuecomment-1320135401
