### ISSUE TITLE
TABS component classNames

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#45112]
### What problem does this feature solve?

Hi, I'd like to create a status **error className** on tabs, Now I added a danger button but it hasn't good result and cannot add error **className** to tab link. 

Example:
https://ibb.co/BBhcdNH

![Screenshot 2023-09-26 alle 16 52 51](https://github.com/ant-design/ant-design/assets/40239902/ac4c9dfb-f57f-4298-b38e-6ef3c0ca54ee)

### What does the proposed API look like?

```
item: "demo tab",
classNames: "demo-here"
```

**Comment by Wxh16144** [comment]
I have a solution here. :)

<img width="1280" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/cd022ba7-70a8-4a47-a8e3-8bcc3275e716">

**Comment by vitalijalbu** [comment]
> I have a solution here. :)
> 
> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/32004925/270829567-cd022ba7-70a8-4a47-a8e3-8bcc3275e716.png">

Yes, it's the same I did but with danger button.
As you can see tab border is not red color.

My code:

```
{
      label: <Button type="text" danger={tabErrors === "addresses"}>Addresses</Button>,
      key: "addresses",
      children: (<p>demo</p>)
}
```

**Comment by Wxh16144** [comment]
I'll provide an approximate solution, written rather roughly.
![image](https://github.com/ant-design/ant-design/assets/32004925/b347f994-90f4-4e65-99b2-822dc073c251)

**Comment by vitalijalbu** [comment]
> I'll provide an approximate solution, written rather roughly. ![image](https://user-images.githubusercontent.com/32004925/270904727-b347f994-90f4-4e65-99b2-822dc073c251.png)

Hi, problem is when you have like 5 tabs, it mantains the red color for all of them, how to managed the classname based on state key of the tab?
beucase i save the error key in a state to know which tab is danger and which not
