### ISSUE TITLE
页面宽度小于575px时 inline布局的form的label会撑满宽度 而内容会被挤出去

### ISSUE THREAD

**Issue by CLXGGG** [ant-design/ant-design#45122]
### Reproduction link

[https://ant-design.antgroup.com/components/form-cn#components-form-demo-layout](https://ant-design.antgroup.com/components/form-cn#components-form-demo-layout)

### Steps to reproduce

将浏览器宽度缩小到575px以下 看inline布局的form

### What is expected?

form.item的内容不应该被label挤出去 要么换行 要么label不要撑满

### What is actually happening?

form.item的内容被挤出去

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.1.0 |
| System | windows |
| Browser | 火狐117.0.1 |

**Comment by crazyair** [comment]
是因为这个样式
![image](https://github.com/ant-design/ant-design/assets/7971419/bd6edc09-346d-41fe-b707-7804c3a65bb9)

**Comment by zombieJ** [comment]
<img width="565" alt="截屏2023-09-27 15 48 31" src="https://github.com/ant-design/ant-design/assets/5378891/8e0b5df1-2a7b-4b2a-837b-94df44438cd3">

看起来的确有点问题

**Comment by crazyair** [comment]
另外，Form 的 demo 会有对于宽度
![image](https://github.com/ant-design/ant-design/assets/7971419/1a8cac6f-4486-4cae-803b-197c4d311285)
