### ISSUE TITLE
form中如果复写了shouldComponentUpdate方法，可能导致input无法输入内容

### ISSUE THREAD

**Issue by pishilong** [ant-design/ant-design#4513]
#### Environment(required)

- antd version: 2.6.0
- OS and its version: MacOS Sierra
- Browser and its version: 所有浏览器

#### What did you do? Please provide steps to re-produce your problem.

1. form中添加shouldComponentUpdate方法
2. 在Input中输入内容
3. Input还是之前的内容，没有更新

#### What do you expected?

更新文档，注明不光stateless component会有问题，
如果复写了shouldComponentUpdate方法可能也会有问题。

#### What happen?

Input中无法输入内容
0.在Input中输入内容，触发onChange事件（此时input显示的是输入后的内容）
1.React dispatchEvent并进行batchedUpdates
2.Form的onChangeValidate能对新值进行校验
3.React->flushBatchedUpdates
....
4.React->runBatchedUpdates
5.ReactReconciler.performUpdateIfNecessary
6.internalInstance.performUpdateIfNecessary(transaction);
7. this.updateComponent
    此时this指向的是form对象，在updateComponent方法中，会检查并执行shouldComponentUpdate方法，如果方法返回false，则form不会更新，所以刚输入内容的input也不会更新value，导致输入无效。

**Comment by yesmeck** [comment]
给个重现的 demo 吧 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by pishilong** [comment]
@yesmeck 重现demo,为了简化场景，shouldComponentUpdate始终返回false.
http://codepen.io/pishilong/pen/xgGPMZ

**Comment by yesmeck** [comment]
Demo 没毛病，这就是 shouldComponentUpdate 工作的方式，shouldComponentUpdate 返回 false 的话组件就不会再 render 了，也就是说组件的内容不会再更新了。

**Comment by yesmeck** [comment]
stateless component 有问题是因为 React  的 bug，你这里说的问题是其实是组件正常的工作方式。

**Comment by pishilong** [comment]
我用stateless component做类比有问题，那个是bug，这个不是bug。
只是在使用getFieldDecorator时，因为使用了双向绑定，会去更新Input的value属性，所以如果在form中用了shouldComponentUpdate的话，可能会出现不刷新的情况，需要注意一下。
所以希望能在文档中加个tips之类的。

当然，如果觉得没必要在文档中加个tips的话也没问题。
