### ISSUE TITLE
Notification.useNotification() doesn't support getContainer

### ISSUE THREAD

**Issue by ajin-iqness** [ant-design/ant-design#45134]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duration-after-which-the-notification-box-is-closed-antd-5-9-3-forked-pxjvpz?file=/demo.js)

### Steps to reproduce

Click on "Open the notification box" button

### What is expected?

Notification element mounted on div#mount-node

### What is actually happening?

Notification element mounted on document.body

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.0.0 |
| System | Ubuntu 20.04.6 LTS |
| Browser | Google Chrome Version 117.0.5938.88 (Official Build) (64-bit) |

---
This is a working example with 4.x version. Not anymore if we update the versions.
https://codesandbox.io/s/weathered-cdn-s3yk2w?file=/index.js

**Comment by MadCcc** [comment]
Documentation never mentioned this usage, it should be like: https://codesandbox.io/s/duration-after-which-the-notification-box-is-closed-antd-5-9-3-forked-hqnwt9
