### ISSUE TITLE
DatePicker scrollbars

### ISSUE THREAD

**Issue by markaschell** [ant-design/ant-design#45130]
### Reproduction link

[https://jyh2k9.csb.app/](https://jyh2k9.csb.app/)

### Steps to reproduce

Create a DatePicker with time.  Pick the time 11:45.  Notice that most of the options in the hour and minutes list are not visible to the user because the list is scrolled all the way to the bottom of the list and the selected item is at the top of the viewport.

### What is expected?

If there are fewer options than what can possibly be displayed it would be nice not to have a scrollbar.  (ex, limiting the minutes to just 15, 30, 45, and 00 should not require a scrollbar)  Also if the last item in the list is selected then it should appear at the middle or bottom of the viewport so the user can see more of the options.

### What is actually happening?

Most the the time options are not visible to the user when one of the last items in the list is selected.

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.2.0 |
| System | Mac 13.5.2 (22G91) |
| Browser | Chrome |

**Comment by afc163** [comment]
I can't reproduce it in the codesandbox you provided.
