### ISSUE TITLE
下拉滚动加载数据，当前选中1条的时候，滚动到底部加载了更多数据时，会滚动到选择的数据的位置

### ISSUE THREAD

**Issue by darknessjs** [ant-design/ant-design#45137]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-5-9-3-forked-4ty62j?file=/demo.tsx:0-1433)

### Steps to reproduce

选中一条数据，然后滚动到底部加载数据

### What is expected?

直接加载数据

### What is actually happening?

滚动到了选中的数据的位置

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 17 |
| System | mac |
| Browser | chrome |

---
关联issue以及影响代码：https://github.com/react-component/select/issues/982

**Comment by zombieJ** [comment]
嗯，可以优化一下。打开的时候数据更新不要重新定位。
