### ISSUE TITLE
Spin 自定义指示符 `tip` 设置无效

### ISSUE THREAD

**Issue by HaceraI** [ant-design/ant-design#45131]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-zhi-shi-fu-antd-5-9-3-forked-5lkxhy?file=/demo.tsx)

### Steps to reproduce

可更改`antd`版本查看

### What is expected?

tip 自定义描述文案 正常展示

### What is actually happening?

tip未展示

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.0.0 |
| System | Windows 11 |
| Browser | Google Chrome   Version 117.0.5938.92 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
<img width="467" alt="截屏2023-09-28 12 01 26" src="https://github.com/ant-design/ant-design/assets/5378891/3f71dc6d-dc5b-409a-a98e-d39fc9e5ed04">
<img width="501" alt="截屏2023-09-28 12 02 15" src="https://github.com/ant-design/ant-design/assets/5378891/f580abaa-d19b-49d0-a8fc-54c74afd7813">

**Comment by zombieJ** [comment]
之前有版本有 bug 会透出来，可以做成 feature

**Comment by HaceraI** [comment]
我的问题，抱歉，没认真看console和文档(主要我今天升级了antd版本后就不行了，就以为是bug之类的，原来之前能显示是因为有bug)...
