### ISSUE TITLE
TreeSelect treeCheckStrictly not working as expected

### ISSUE THREAD

**Issue by neubasi** [ant-design/ant-design#45139]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-srtrws?file=/index.js)

### Steps to reproduce

1. Click on Node "Dep. Muskuloskelettales System"
2. Click on Node "Dep. Kreislauf, Thorax, Transp"
3. Expand Node "Dep. Kreislauf, Thorax, Transp"
4. Click on Node "0-1-0-0-0"

### What is expected?

I selected 3 nodes, but in "Search Bar" there are only 2 Nodes.

### What is actually happening?

That is the question

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.2.0 |
| System | Windows |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
Hi, your reproduce is empty.

**Comment by neubasi** [comment]
Is it still empty?
@zombieJ

**Comment by Yuiai01** [comment]
I think that if the parent node is selected, then all the child nodes should also be selected (currently not selected), and when all the child nodes are selected, the parent node should be selected as well. Both of these situations can be considered as one node. When selecting child nodes under the parent node, the count of nodes should be based on whether all of them are selected or not.

**Comment by MadCcc** [comment]
You should use `showCheckedStrategy={TreeSelect.SHOW_ALL}`

**Comment by neubasi** [comment]
@MadCcc Thank you so much, iam feeling stupid not fully reading API.
There it is clear:
Default: just show child nodes.
TreeSelect.SHOW_ALL | TreeSelect.SHOW_PARENT | TreeSelect.SHOW_CHILD
