### ISSUE TITLE
Select 组件在页面滚动的时候，能否加个属性让下拉面板自动隐藏

### ISSUE THREAD

**Issue by liguonan888** [ant-design/ant-design#45159]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn/](https://ant-design.antgroup.com/components/input-cn/)

### Steps to reproduce

Select 组件在页面滚动的时候，能否加个属性让下拉面板自动隐藏

### What is expected?

Select 组件在页面滚动的时候，能否加个属性让下拉面板自动隐藏

### What is actually happening?

Select 组件在页面滚动的时候，能否加个属性让下拉面板自动隐藏

| Environment | Info |
| --- | --- |
| antd | undefined |
| React |  "react": "^18.0.10", |
| System | mac |
| Browser | 谷歌106 |

**Comment by afc163** [comment]
为啥要隐藏，有什么具体的缘由么？

**Comment by yinhw0210** [comment]
> 为啥要隐藏，有什么具体的缘由么？

![image](https://github.com/ant-design/ant-design/assets/73924912/f2398a20-2f03-4c84-a7c2-32f61b1b38b5)
您好 在弹窗中的下拉面板 如果直接滚动的话就会造成这种情况 面板的层级大于modal的层级 虽然使用getPopupContainer可以解决 但是如果有好多下拉框的话那就需要每一个都加入这个属性
