### ISSUE TITLE
windows自带中文输入法不能正常输入

### ISSUE THREAD

**Issue by nianhua110** [ant-design/ant-design#4515]
- antd version:2.4.2
- OS and its version: windows 10 企业版
- Browser and its version: IE11

#### What did you do? Please provide steps to re-produce your problem.
在antd官网的Form例子中，现在用户名框中用Windows只带的输入法输入中文，然后切换到密码框继续输入，前面那个框的最后一组词会变成英文，发生很普遍，但不是每次都是这样。

#### Re-producible online demo
https://ant.design/components/form-cn/ 该页面的代码所有的演示框都可以测试。

**Comment by benjycui** [comment]
输入法的默认行为是：在还没选词的情况下就切换到别的输入框时，没有选词的那部分就会保持为你输入的拼音或五笔简码。

请认真学习输入法的使用。

**Comment by nianhua110** [comment]
你是觉得我们几个测试的都不会用输入法？ @benjycui

**Comment by nianhua110** [comment]
希望你们自己试一下，一开始测试人员告诉我这个，我也觉得是没有选词的原因．可是后来试了一下和测试的表述是一样的．或者我们真的不怎么会用输入法，怕是普通用户不熟读输入法手册，也是要被批的．

**Comment by benjycui** [comment]
那么请提供必现 demo 和步骤

**Comment by afc163** [comment]
建议第一时间尽可能把所有的信息都给我们，不要让维护者一直追问。

1. 是下面这个微软拼音输入法么？具体的输入法以及版本是什么？其他输入法有问题么？
   ![default](https://cloud.githubusercontent.com/assets/507615/21939988/2b2ab224-d9fd-11e6-8e5c-08eb5865e9e3.PNG)
2. 操作步骤是什么，你说的“切换”，是鼠标切换还是 Tab 切换。
3. 最后展示的效果是啥，最好提供截图？

**Comment by nianhua110** [comment]
抱歉这么晚回复。我们找了几台电脑测试。都没有出现上述问题。只用一台测试机器有这个问题。
测试机器使用的是windows10 企业版。
其它机器是windows专业版。因为找不到其它企业版，也不能确定是不是版本问题。
希望有使用企业版的朋友试一下。
测试步骤就是普通打字。
第一步，使用windows10企业版自带的输入法，切换到中文状态。
然后在https://ant.design/components/form-cn/ 随便找一个框，输入一段文字。
然后用鼠标切换到另外一个框。
这个时候高概率（基本10次有5次）的出现第一个框最后输入的一组词变成拼音。

**Comment by benjycui** [comment]
录个动图吧。

**Comment by nianhua110** [comment]
@benjycui ,mp4的没办法上传，还有界面涉及些私人信息，能否换个方式给你？

**Comment by benjycui** [comment]
隔离出一个业务无关的最小可重现 demo，然后录个 GIF 图。

现在这样我们什么都做不了。

**Comment by nianhua110** [comment]
![ok1](https://cloud.githubusercontent.com/assets/9710498/22058600/7c66ed92-dda4-11e6-9397-e997a31f3d81.gif)

**Comment by yesmeck** [comment]
看起来像是 React 的 bug 啊。

**Comment by nianhua110** [comment]
@yesmeck 我去试试．

**Comment by benjycui** [comment]
Close for no further information.
