### ISSUE TITLE
Alert: message is not vertical aligned relative to icon when there is no description prop

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#45151]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-bug-alert-message-is-not-centered-hr8hmw?file=/index.js)

### Steps to reproduce

1. Import Alert
2. Use in JSX
3. Set message prop
4. Set icon prop using custom icon
5. Set type "warning"
6. Not set description prop

### What is expected?

Message is opposoite centered relative to icon

### What is actually happening?

Message is upper relative to icon

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Version 117.0.5938.88 (Official Build) (64-bit) |

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/45bc3aae-8977-446a-bcba-7026a8a250be)
Actually it's center aligned.

**Comment by evgeniyworkbel** [comment]
![image](https://github.com/ant-design/ant-design/assets/93836126/c8983b45-0c8a-4e7d-bb67-576ea22371a9)

At devtools yes, but actually it is rendered not alighed

**Comment by MadCcc** [comment]
Seems font is different on your screen. `align-items` has been `center` and we can't not do more.

**Comment by MadCcc** [comment]
Going to closing this issue because it only problem with specific device.
Any PR to fix it would be welcome.
