### ISSUE TITLE
Popconfirm not opening with a custom component ( in a custom component )

### ISSUE THREAD

**Issue by gitter-me** [ant-design/ant-design#45158]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8zshgr?file=/index.js)

### Steps to reproduce

1. Create a custom component
2. Create another custom component that contains a Popconfirm and the Popconfirm contains the custom component from step 1
3. Place the component from step 2 in the app
4. Click on the component to open the Popconfirm 

(In the linked reproduction this is the first button with the text Broken)

### What is expected?

The popup should open

### What is actually happening?

No popup is opening

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.x |
| System | Not relevant |
| Browser | Not relevant |

---
If the custom component inside the Popconfirm is wrapped with a fragment <></> it is working.

(In the linked reproduction this is the second button with the text Working)
But I don't now why this workaround works and why it should be necessary.

**Comment by MadCcc** [comment]
Make sure your custom component support click event and `ref`
