### ISSUE TITLE
Table filter dropdown is overflowing outside of the table on scrolling it while open

### ISSUE THREAD

**Issue by LizaMaharjan2001** [ant-design/ant-design#45157]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-columns-antd-5-9-4-forked-y9vxg5)

### Steps to reproduce

- Open the link
- Click on the filter icon of the column ('Column 1')
- After the filter is opened, scroll the table without closing the filter
- The popped up filter container is overflowing out of the table

### What is expected?

- The popped up filter container to be inside of the table even after scrolling while it's open

### What is actually happening?

- The popped up filter container is overflowing out of the table while scrolling

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by Meet-Kalani** [comment]
Hey @LizaMaharjan, How did you manage to resolved this bug

**Comment by LizaMaharjan** [comment]
> Hey [@LizaMaharjan](https://github.com/LizaMaharjan), How did you manage to resolve this bug

It's not solved yet, because you cannot hide the overflowed content since table uses overflow-y auto scroll. 
At least that's what I read in other issues as well.
