### ISSUE TITLE
Virtualized table max height

### ISSUE THREAD

**Issue by konstantinsp** [ant-design/ant-design#45167]
### What problem does this feature solve?

is there a way to change height of virtual table in and design? 
i want to create a table of 100vh but i noticed that class="rc-virtual-list-holder" is set to max-height of 500px that is not enough.
and i dont see any option to change this value

### What does the proposed API look like?

```
<Table virtual height={"100vh"} ...{otheroptions}>
```

**Comment by hungtcs** [comment]
@konstantinsp I am use `scroll` prop to control the table height.

**Comment by konstantinsp** [comment]
@hungtcs thanks scroll prop helped.
