### ISSUE TITLE
Submenu items appear and disappear quickly in inline mode after select item of submenu in vertical mode

### ISSUE THREAD

**Issue by meskal1** [ant-design/ant-design#45160]
### Reproduction link

[https://ant.design/components/menu](https://ant.design/components/menu)

### Steps to reproduce

![bug](https://github.com/ant-design/ant-design/assets/49230105/6a14ae5c-e1f9-4954-8ba9-6b4ca88e8b5b)

https://gifyu.com/image/S6bC6 Here is the gif with the reproduction steps. You can test in your site menu example.
Collapse inline menu to vertical => hover item with submenu => select any item of submenu =>  expand vertical menu to inline menu => expand the item with submenu where you previously selected item => expand and collapse the submenu 

### What is expected?

Submenus from vertical mode should not flicker when opening and closing submenus in inline mode.

### What is actually happening?

Submenus from vertical mode flicker when opening and closing submenus in inline mode. If I once opened a submenu in vertical mode and selected some element, the flickering will remain until I reload the page. 

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | chrome 117.0.5938.132 |

---
I just made a menu on my project and discovered this flickering problem. It is also present on your website as an example of using the menu.

**Comment by Yuiai01** [comment]
There is indeed an issue. when collapsing the submenu, it appears in the wrong position.
