### ISSUE TITLE
动态切换语言时，应用状态会被重置

### ISSUE THREAD

**Issue by huxuezhi** [ant-design/ant-design#45177]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hk6k6s?file=/index.js)

### Steps to reproduce

使用ConfigProvider来动态切换语言，会发现表单里已输入的内容会被重置为初始状态，

### What is expected?

应用状态不应该被重置

### What is actually happening?

应用状态被重置为初始化状态了

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

---
如果这不是一个bug的话，请问该如何避免切换语言时丢失状态呢？

**Comment by zombieJ** [comment]
ConfigProvider 内部会有很多 Provider，是惰性渲染。你做切换的时候从 `undefined` 切换过去相当于重新添加了一层 Provider，始终提供 locale 即可：

https://codesandbox.io/s/antd-reproduction-template-forked-j4wmg5?file=/index.js
