### ISSUE TITLE
Side bar 2 level nested menu when collapsed or opened a ui glitch happens 

### ISSUE THREAD

**Issue by susantpatel** [ant-design/ant-design#45171]
### Reproduction link

[https://stackblitz.com/edit/react-rypcpc?file=demo.tsx](https://stackblitz.com/edit/react-rypcpc?file=demo.tsx)

### Steps to reproduce

open the 2 level nested menu then collapse the side bar.

Continously collapse and uncollapse the side bar a ui glitch will happen

### What is expected?

the ui glitch should not happen

### What is actually happening?

A ui glitch happens when we collapse or uncollapse the sidebar

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.2.0 |
| System | Linux-mint 21.2 cinnamon |
| Browser | Firefox version 118 |

**Comment by Yuiai01** [comment]
Hi, I tried it out, and there were no bugs. Can you provide a video or picture?
