### ISSUE TITLE
Cascader loadData not tiggered after search

### ISSUE THREAD

**Issue by Bacaaa** [ant-design/ant-design#45180]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/load-options-lazily-antd-5-9-4-forked-8vrpqr?file=/demo.tsx)

### Steps to reproduce

Combain loadMore with search
Search value
Click option to fetch option childrens - loadMore is not tiggered

### What is expected?

Tigger loadMore function after click on element after search

### What is actually happening?

LoadMore is not tiggered

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
Hi, The official documentation states that `loadData` cannot be used with `showSearch`. https://ant.design/components/cascader#cascader-demo-lazy

**Comment by Bacaaa** [comment]
not good thanks
