### ISSUE TITLE
Tour display both default button and custom button.

### ISSUE THREAD

**Issue by laux98** [ant-design/ant-design#45182]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-9-4-forked-lsvn34?file=/demo.tsx)

### Steps to reproduce

In the component Tour , in one of step, add a custom render for nextButtonProps or prevButtonProps. 

### What is expected?

My custom button replaces the default button.

### What is actually happening?

The default button and my customized button are displayed both.

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | Ubuntu 22.04 (64 Bits) |
| Browser | Chromium Version 112.0.5615.49  |

---
In the codesandbox, click "Begin Tour", then "Next", and you will see the problem because the default button "Previous" and my custom button "BONJOUR" are both displayed.

**Comment by laux98** [comment]
Find a solution for this.

If you want to change the style and content of default buttons, you have to put in prevButtonProps.children the content of the button and in prevButtonProps.style the style of button .

Exemple : 
```
const steps: TourProps["steps"] = [{
  title : "Welcome",
  description : <Row> Very Welcome </Row> ,
  nextButtonProps : {
  children : (
    <QuestionCircleOutlined style={{ color: "white" }} />
  ),
  style : {
        backgroundColor: "red",
        borderRadius: "50%",
        width: 32,
        minWidth: 32,
        height: 32,
  }
}]
```

**Comment by ula-k** [comment]
I'm switching to another library mostly because of lacking this feature.
I need custom buttons on every slide, and this just doesn't work correctly.
