### ISSUE TITLE
Currency does not change by locale

### ISSUE THREAD

**Issue by pbduy** [ant-design/ant-design#45183]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/currency-wrapper-antd-input-3ynzo)

### Steps to reproduce

1. Change any currency

### What is expected?

2. The currency in the input field changes according to the selected one

### What is actually happening?

2. The currency in the input field does not change

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | Window 11 OS version 22H2 |
| Browser | Google Chrome version 116.0.5845.188 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
InputNumber is lazy parser which means not trigger update if no `value` or other interactive called. You can add key to force trigger it:

https://codesandbox.io/s/currency-wrapper-antd-input-forked-h6pkd5?file=/src/index.js

**Comment by pbduy** [comment]
Thank you! I copied the demo from document InputNumber component, example formatter. Can you update that demo to force trigger when change the currency ?
