### ISSUE TITLE
InputNumber disable text by default, only numbers

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#45181]
### Reproduction link

[https://ant.design/components/input-number](https://ant.design/components/input-number)

### Steps to reproduce

Create a input number component
Try to inser some text
it disappears on out clicking

### What is expected?

Not being allowed to put letters inside

### What is actually happening?

Letters are allowed

| Environment | Info |
| --- | --- |
| antd | 5.9.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by Yuiai01** [comment]
It seems that the validation after input doesn't have much impact. 🤔

**Comment by vitalijalbu** [comment]
> It seems that the validation after input doesn't have much impact. 🤔

right, but let's disable it from start... 😃

**Comment by MadCcc** [comment]
Use `type="number"`
