### ISSUE TITLE
Select 在限高区域使用getPopupContainer并且多选项时渲染错位

### ISSUE THREAD

**Issue by Shen120** [ant-design/ant-design#45195]
### Reproduction link

[demo地址](https://codesandbox.io/s/pensive-chebyshev-sctk7f?file=/index.js)

### Steps to reproduce

点开选项就会出现

### What is expected?

能正常渲染弹出框

### What is actually happening?

未能正常渲染弹出框
![image](https://github.com/ant-design/ant-design/assets/33613409/fa6389d3-4083-43ea-b2a6-2ae8737c8fa2)

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 17.0.1 |
| System | win 10 |
| Browser | chorme@latest |

**Comment by Shen120** [comment]
调整容器高度不太现实，因为实际是在弹窗中使用的
![image](https://github.com/ant-design/ant-design/assets/33613409/0864e7b4-58d1-4cdc-9da3-8e55817e6cd1)

**Comment by Shen120** [comment]
看到类似的问题：[37965](https://github.com/ant-design/ant-design/issues/37965)
但是我在想官方能不能提供一个属性，让弹出框不根据容器高度自适应位置呢，比如我设置placement="bottom"后，再关闭不自适应位置这个属性，让它始终显示在一个位置，就算看不到的话那就让用户去滚动。 @afc163

**Comment by MadCcc** [comment]
试试把 popupOverflow 设为 `scroll`

**Comment by Shen120** [comment]
> 试试把 popupOverflow 设为 `scroll`
> 
> https://ant.design/components/config-provider-cn#api

不行，https://codesandbox.io/s/pensive-chebyshev-sctk7f?file=/index.js

**Comment by afc163** [comment]
可以尝试去掉 `getPopupContainer={() => document.getElementById("area")}`。

**Comment by MadCcc** [comment]
看你截图是 5.x 的 antd，但是 reproduction 是 4.x？

**Comment by MadCcc** [comment]
5.x 可以这样 https://codesandbox.io/s/affectionate-hermann-h26pkw
4.x 不会添加新的 feature 了

**Comment by Shen120** [comment]
> 5.x 可以这样 https://codesandbox.io/s/affectionate-hermann-h26pkw 4.x 不会添加新的 feature 了

4x怎么解决这个问题，总得有的啥子方案吧，大神

**Comment by lv2000-creat** [comment]
> 可以尝试去掉 `getPopupContainer={() => document.getElementById("area")}`。

这个解决了，感谢！
