### ISSUE TITLE
Module not found: Can't resolve 'antd/es/alert/style/css' after upgrade from v4 to v5

### ISSUE THREAD

**Issue by dsocha** [ant-design/ant-design#45191]
### Reproduction link

[http://the-problem-occurs-in-a-private-repo-after-upgrade](http://the-problem-occurs-in-a-private-repo-after-upgrade)

### Steps to reproduce

yarn upgrade antd --latest
yarn add @ant-design/compatible@v5-compatible-v4
yarn add @ant-design/pro-layout
yarn add @ant-design/moment-webpack-plugin --dev
npx -p @ant-design/codemod-v5 antd5-codemod src

### What is expected?

After upgrading the project from antd 4.x to the latest 5.9.4, it is not able to compile anymore. 
I expect the project to be compiled w/o errors and running fine.

### What is actually happening?

Can't compile the project: Module not found: Can't resolve 'antd/es/alert/style/css' in '.../src/containers/Admin/Mailing/Campaign'. If I comment out the Alert component in the Campaign file the same error occurs for another one.

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 17 |
| System | Mac OS 13.4.1 |
| Browser | Chrome 117.0.5938.149 |

**Comment by yoyo837** [comment]
v5 is a css-in-js project. Not include any CSS.

**Comment by dsocha** [comment]
I know, this is why I'm surprised. I've double checked and I don't have any antd/css references in the project.

**Comment by yoyo837** [comment]
Are you using babel-plugin-import？

**Comment by yoyo837** [comment]
That's the problem, stop using it.

**Comment by dsocha** [comment]
// fixBabelImports('import', {
      //   libraryName: 'antd',
      //   libraryDirectory: 'es',
      //   style: 'css',
      // }),
      
I've commented out above and the error doesn't occur anymore.

But now it fails with:
Attempted import error: 'Icon' is not exported from 'antd'.

From what I see 'Icon' from 'antd' is used more than 200 times in 80 files in the project. Is there any way to globally fix the problem or do I need to replace manually all occurrences?

**Comment by yoyo837** [comment]
`antd` no longer exports Icon since 4.x, please follow the documentation to migrate https://4x.ant.design/docs/react/migration-v4#Icon-upgrade

**Comment by tiandiyixiaoniao** [comment]
v5 is a css-in-js project. Not include any CSS.  stop using babel-plugin-import in .babelrc.js or somewhere
