### ISSUE TITLE
message 组件可以弹出多个消息的时候保留第一个或者最后一个吗？

### ISSUE THREAD

**Issue by pengxiaobao** [ant-design/ant-design#452]
如果系统发ajax请求，每发送失败就弹出消息，切设置消息隔5秒消失 。这时一个页面请求多个请求，提示框会出现多个叠加，第一个弹出框的文本非常多，第二个稍小一点，这样感觉不好。

**Comment by afc163** [comment]
不希望叠加的话，建议用 http://ant.design/components/notification/ 来做。
