### ISSUE TITLE
总览页进入组件页会有个 fallback

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#45201]
步骤：

1. 进入 https://ant.design/components/overview-cn
2. 点击按钮组件卡片，观察页面

### 预期效果

直接进入按钮组件页面，导航和侧边不会重新渲染

### 实际效果

点击按钮组件卡片后，页面会 fallback 到骨架屏效果。

https://github.com/ant-design/ant-design/assets/507615/eb16ba0b-6f95-4a22-8972-c4d12658fed8

**Comment by afc163** [comment]
还有这里的 iframe 挂了：https://ant-design.antgroup.com/components/float-button-cn

**Comment by MadCcc** [comment]
> 还有这里的 iframe 挂了：https://ant-design.antgroup.com/components/float-button-cn

这个原因应该是 demo 的 html 没有 build 出来

**Comment by MadCcc** [comment]
已验证修复
