### ISSUE TITLE
antd 如何兼容老版本浏览器样式（chrome 71）

### ISSUE THREAD

**Issue by chenJJ-88** [ant-design/ant-design#45209]
### What problem does this feature solve?

我用该版本浏览器进入antd官网都被提示浏览器无法兼容，想请教一下是否有好的解决方式

### What does the proposed API look like?

无

**Comment by chenJJ-88** [comment]
![default](https://github.com/ant-design/ant-design/assets/118970817/bc8e7636-2192-4736-ba3a-3c5d92fcc3cb)

**Comment by chenJJ-88** [comment]
因为项目需要用到这老的浏览器，一开始都不知道，后面开发差不多了才被告知5555555

**Comment by afc163** [comment]
https://ant.design/docs/react/compatible-style-cn

**Comment by afc163** [comment]
话说这个弹出提示里也有相关兼容说明可以查阅。

**Comment by crazyair** [comment]
官网需要用新版浏览器访问，开发可以做想加兼容配置。PS: 官网没有兼容版本

**Comment by chenJJ-88** [comment]
> 话说这个弹出提示里也有相关兼容说明可以查阅。
> 
> <img alt="图片" width="380" src="https://user-images.githubusercontent.com/507615/273431215-e85b2e51-d4ec-401e-a8f1-6e6c8dfb61d2.png">

配置了貌似也没有生效，不知道是否是配置出问题呢，很蒙蔽

**Comment by chenJJ-88** [comment]
![default (1)](https://github.com/ant-design/ant-design/assets/118970817/af9f907c-5f0d-420f-abfd-b8999301a6ef)
z这种无法生效，我看文档是配置transformers ，配置了还是无法生效，请问是什么原因呢
