### ISSUE TITLE
5.9.4 Tooltip    显示位置有问题

### ISSUE THREAD

**Issue by websybin** [ant-design/ant-design#45202]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wei-zhi-antd-5-9-4-forked-vw4zfp?file=/demo.tsx)

### Steps to reproduce

划入显示位置在button内部

### What is expected?

和5.9.2效果一致

### What is actually happening?

他显示在button内

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.0.0 |
| System | ios |
| Browser | 113.0.5672.126 |

**Comment by Yuiai01** [comment]
![img_v2_041c31b2-c69d-4968-bdbf-8a6ef8fdac5g](https://github.com/ant-design/ant-design/assets/112228030/d3fa5b8f-d35a-4e49-bf75-ec29be23649c)
![img_v2_e8abd72b-c0db-4823-9ee9-0f83cde0451g](https://github.com/ant-design/ant-design/assets/112228030/a90b3fda-49df-4c20-8356-fc0f86ecbe9d)
好像没啥区别...

**Comment by websybin** [comment]
![image](https:github.com/ant-design/ant-design/assets/84109842/c373a8a9-a45b-4120-8edf-6881962d9ff6)
我看到的是这个样子的

**Comment by websybin** [comment]
![image](https://github.com/ant-design/ant-design/assets/84109842/a9aba850-e77f-436a-b950-e2d98bc41b5f)
我这边看到的是这个样子

**Comment by afc163** [comment]
你给的例子里貌似是好的。

<img width="303" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/f3cec708-97f6-41b0-b4ab-71db480e8c06">

**Comment by websybin** [comment]
那么我们两个看到效果不同，导致的原因是什么您知道吗

**Comment by afc163** [comment]
@websybin 截两个完整的图看看，是在这个 https://codesandbox.io/s/wei-zhi-antd-5-9-4-forked-vw4zfp?file=/demo.tsx 里重现的？

**Comment by websybin** [comment]
![image](https://github.com/ant-design/ant-design/assets/84109842/70b8340b-e342-42ff-bea8-c5d8b4d5feb1)
5.9.4
![image](https://github.com/ant-design/ant-design/assets/84109842/508e28b7-f4ea-4f2e-9c14-27e003febf7a)
这个是5.3.2因为我不知道怎么codescandbox怎么安装5.9.2

**Comment by websybin** [comment]
是的 我是在这个链接里面复现的。

**Comment by afc163** [comment]
@websybin 试试隐身模式，看看是不是有什么插件影响了。

**Comment by websybin** [comment]
![image](https://github.com/ant-design/ant-design/assets/84109842/d4d03a15-e7aa-48c6-933f-2981923721a8)

开启无痕也会有这样的问题

**Comment by afc163** [comment]
试试升级一下 Chrome 版本。

**Comment by websybin** [comment]
目前是最新版本 ，刚才和同事们看了下 ，有好使有不好使的。就很奇怪 但是项目锁定5.9.2我这边就是好使的 就很奇怪

**Comment by websybin** [comment]
目前是最新版本 ，刚才和同事们看了下 ，有好使有不好使的，就很奇怪。 但是项目锁定5.9.2我这边就是好使的 。

**Comment by wving5** [comment]
路过复现一下…
<details>
  <summary>Screenshot</summary>
  <img width="1713" alt="截屏2023-10-11 上午11 32 35" src="https://github.com/ant-design/ant-design/assets/12070838/2fe8a10b-af6a-478c-aa74-4619e1994552">
</details>

https://codesandbox.io/s/wei-zhi-antd-5-9-4-forked-rvv3qy?file=/demo.tsx

Environment | Info
-- | --
antd | 5.9.2、5.9.4、5.10.0
React | 18.0.0
System | macOS 11.7.7
Browser | Chrome 118.0.5993.70, Safari 14.1.3, Firefox 118.0.2

**Comment by helloyou2012** [comment]
@afc163 复现环境：Windows系统（Edge、Chrome浏览器）。大体看了下好像是 5.9.3 版本修改这里导致的：https://github.com/ant-design/ant-design/blob/e5a213d804ccaef22bcd751b0fdf9d12baa04936/components/_util/placements.ts#L163C18-L163C18

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/trigger/pull/437
