### ISSUE TITLE
Tour组件placement功能在指引元素高度或者宽度长一点的情况下 topLeft,rightTop这种无预期效果

### ISSUE THREAD

**Issue by lv900901** [ant-design/ant-design#45215]
### What problem does this feature solve?

Tour组件placement功能和 Tooltip组件的placement效果一致

### What does the proposed API look like?

Tour组件placement功能和 Tooltip组件的placement效果一致

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
