### ISSUE TITLE
Select 组件 配置 optionLabelProp="label"，使用隐藏下拉列表中已选择的选项，展示内容为value，非指定的optionLabelProp值 

### ISSUE THREAD

**Issue by QF-study** [ant-design/ant-design#45218]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yin-cang-yi-xuan-ze-xuan-xiang-antd-4-24-12-forked-4d5d2p?file=/demo.tsx)

### Steps to reproduce

选择选项

### What is expected?

展示在选择框内的是label而不是vlaue

### What is actually happening?

现在是展示的value  而不是optionLabelProp 设置的label

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 16.x |
| System | Window |
| Browser | chrome |

**Comment by MadCcc** [comment]
因为你动态过滤了 options，导致选中的选项在 options 里找不到对应的选项

**Comment by MadCcc** [comment]
搭配 `labelInValue` 使用：https://codesandbox.io/s/yin-cang-yi-xuan-ze-xuan-xiang-antd-4-24-12-forked-8d7n54

**Comment by QF-study** [comment]
业务场景比较复杂  只想Value中保存Value  所以可以用 动态的去使用样式来控制https://codesandbox.io/s/yin-cang-yi-xuan-ze-xuan-xiang-antd-4-24-12-forked-xmrhms?file=/demo.tsx:0-1282
