### ISSUE TITLE
the lib compiled from src got on github cannot work well

### ISSUE THREAD

**Issue by scarlettxu** [ant-design/ant-design#4521]
#### Environment(required)

- antd version: 2.6.0
- OS and its version: MacOS 10.11.6
- Browser and its version: Chrome 50

#### What did you do? Please provide steps to re-produce your problem.

I download the ant-design source files from [github](https://github.com/ant-design/ant-design), after install the dependencies, I run `npm run compile`, `npm run dist` and `npm run pre-publish`, and copy the **lib** and **dist** folder to another project's node_modules/antd/ to replace original ones. 

#### What do you expected?

I expected the antd lib built from src file can work correctly just like I run `npm install antd`

#### What happen?

but when I try to run `npm run dev` to compile my project. there are errors in the terminal.

some modules complaining missing omit.js: 

```
ERROR in ./~/antd/lib/icon/index.js
Module not found: Error: Cannot resolve module 'omit.js' in /Users/xuhanzi762/5zztj-pc-web/zztj-web/node_modules/antd/lib/icon
 @ ./~/antd/lib/icon/index.js 23:12-30

ERROR in ./~/antd/lib/cascader/index.js
Module not found: Error: Cannot resolve module 'omit.js' in /Users/xuhanzi762/5zztj-pc-web/zztj-web/node_modules/antd/lib/cascader
 @ ./~/antd/lib/cascader/index.js 44:12-30
```

some modules complaining missing some react-components:

```
ERROR in ./~/antd/lib/date-picker/wrapPicker.js
Module not found: Error: Cannot resolve module 'rc-time-picker/lib/Panel' in /Users/xuhanzi762/5zztj-pc-web/zztj-web/node_modules/antd/lib/date-picker
 @ ./~/antd/lib/date-picker/wrapPicker.js 21:13-48
ERROR in ./~/antd/lib/tabs/index.js

Module not found: Error: Cannot resolve module 'rc-tabs/lib/ScrollableInkTabBar' in /Users/xuhanzi762/5zztj-pc-web/zztj-web/node_modules/antd/lib/tabs
 @ ./~/antd/lib/tabs/index.js 36:27-69

ERROR in ./~/antd/lib/tabs/index.js
Module not found: Error: Cannot resolve module 'rc-tabs/lib/TabContent' in /Users/xuhanzi762/5zztj-pc-web/zztj-web/node_modules/antd/lib/tabs
 @ ./~/antd/lib/tabs/index.js 40:18-51
```

and one component **queue-anim** our project dependes on is missing

```
ERROR in ./src/corehr/position/posPosition/detail/detailForms/MgmtOwnersInfo.jsx
Module not found: Error: Cannot resolve module 'antd/lib/queue-anim' in /Users/xuhanzi762/5zztj-pc-web/zztj-web/src/corehr/position/posPosition/detail/detailForms
 @ ./src/corehr/position/posPosition/detail/detailForms/MgmtOwnersInfo.jsx 7:17-47
```
#### Findings

I compared the **lib** and **dist** folder built from src with the ones installed from npm, I see for same file of same components, the content are different.

e.g. 
for /antd/lib/icon/index.js 

the src file on github use omit.js

`var _omit = require('omit.js');`
`var _omit2 = _interopRequireDefault(_omit);`
`return React.createElement('i', (0, _extends3["default"])({}, (0, _omit2["default"])(props, ['type', 'spin']), { className: classString }));`

but the lib installed from npm does not use omit.js

`return _react2["default"].createElement('i', _extends({ className: className.trim() }, other));`

and src file on github does not have **queue-anim** component, but lib installed from npm have **queue-anim** component.

#### Qustions

why the src file on github are different from the npm packages? 
If I want to use the antd lib built from src files, how can I do to avoid above problems?

**Comment by yesmeck** [comment]
Why do you want to compile source by yourself?

**Comment by scarlettxu** [comment]
Hi, we want to extend the components based our requirements.
is it supported to built from src now?

**Comment by yesmeck** [comment]
Custom source code directly is highly not recommend, but, if you do want to custom, you can fork this project, rename the package name in `package.json`, then run `npm run pub` to publish your own package, then install it via `npm install your-custom-antd`.

**Comment by scarlettxu** [comment]
you mean `npm run compile` is not the correct way to build lib? why the file content in src is different from the npm lib?

**Comment by yesmeck** [comment]
I don't see any difference. https://unpkg.com/antd@2.6.1/lib/icon/index.js

**Comment by yesmeck** [comment]
Ok, you are using 2.6.0.

**Comment by afc163** [comment]
antt's latest tag once become `1.11.5` this afternoon, I believe this is why that npm's version differ from you local compiled version. Now we set the latest tag back to `2.6.1`.

**Comment by scarlettxu** [comment]
@afc163, version of 2.6.1 has deprecated the QueueAnim component?

**Comment by afc163** [comment]
We deprecated QueueAnim at `antd@1.0.0` and removed it at `antd@2.0.0`.

http://1x.ant.design/changelog#%E6%9C%89%E5%85%BC%E5%AE%B9%E6%8F%90%E7%A4%BA%E7%9A%84%E6%94%B9%E5%8A%A8
