### ISSUE TITLE
Card.Grid 卡片圆角问题

### ISSUE THREAD

**Issue by iyuli** [ant-design/ant-design#45221]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/csvm8z)

### Steps to reproduce

在 `Card` 标签中使用 <Card.Grid />，卡片下方左右圆角消失。
![QQ截图20231008201113](https://github.com/ant-design/ant-design/assets/38270397/236d6353-1a30-486c-bac7-9a8c0ca9d6c1)

### What is expected?

四角圆角，或者提供一个全局Token可以设置圆角方式，是上左右圆角还是四角圆角

### What is actually happening?

卡片四角圆角
![QQ截图20231008201157](https://github.com/ant-design/ant-design/assets/38270397/28336f57-ce68-42b8-bd9e-6344bb54f6df)

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.21 |
| System | Windows11 |
| Browser |  116.0.1938.81 |

**Comment by MadCcc** [comment]
应该已经在 https://github.com/ant-design/ant-design/pull/44801 修复了

**Comment by iyuli** [comment]
> 在 #44801 修复了边角问题。由于 grid 布局无法确认哪一块位于角落，并且需要保留阴影，所以不能保留圆角

或者提供一个全局Token可以设置圆角方式，是上左右圆角还是四角圆角
