### ISSUE TITLE
按钮是否也可以增加菜单的溢出折叠功能？

### ISSUE THREAD

**Issue by zhongjiaguo001** [ant-design/ant-design#45223]
### What problem does this feature solve?

在后台系统中，可能有的页面会有多个按钮，但是每个使用人员的屏幕大小不是一致的，可以根据屏幕宽度的大小，尽可能的展示多购按钮不需要使用人员去下拉按钮里再点击一次的操作

### What does the proposed API look like?

像Menu组件一样自动折叠溢出的菜单项

**Comment by MadCcc** [comment]
目前没有提供按钮组的功能，一般来说这种是人为控制的

**Comment by zhongjiaguo001** [comment]
请问一下，我该如何实现这种呢，您是否可以提供一个思路呢，我看了一下menu组件的源码，是使用rc-overflow去控制的，是要再安装这个自己去实现吗

**Comment by zhongjiaguo001** [comment]
> 目前没有提供按钮组的功能，一般来说这种是人为控制的

请问一下，我该如何实现这种呢，您是否可以提供一个思路呢，我看了一下menu组件的源码，是使用rc-overflow去控制的，是要再安装这个自己去实现吗

**Comment by MadCcc** [comment]
@zhongjiaguo001 可以的，就是底层逻辑需要自己实现。rc-overflow 作为底层包我们不太能保证适配所有场景

**Comment by zhongjiaguo001** [comment]
> @zhongjiaguo001 可以的，就是底层逻辑需要自己实现。rc-overflow 作为底层包我们不太能保证适配所有场景

好的，谢谢您的解答！
