### ISSUE TITLE
scrollable Table lags

### ISSUE THREAD

**Issue by DerekHQ** [ant-design/ant-design#4522]
#### Environment(required)

- antd version: 2.6.1
- OS and its version: Windows10
- Browser and its version: Chrome \  IE11

Antd的 table组件，分页（每页二十条）显示列表数据时，
1. 在chrome浏览器内性能正常，但在IE11浏览器内，滚动条以及行高亮事件，CPU（i7）占用相当严重（40%-90%），以至卡顿无法正常使用；
2. 测试使用原生的rc-table组件，列表每页显示几百条，chrome\ie11,均表现良好

**Comment by benjycui** [comment]
具体 demo ? 

性能优化是个很细节的问题，务必提供相关场景的 demo，谢谢。

**Comment by DerekHQ** [comment]
不算优化，就是普通简单表格DEMO，静态数据，装进antd-table， IE11 就非常卡顿（滚动滚动条或者鼠标来回在表上来回的mouseover，CPU占用就很高）； 装进rc-table就没有什么问题！
尤其是表格带fixed列的情况下，尤为严重！

**Comment by DerekHQ** [comment]
最简单的就是你们用 IE11 访问你们的antd官网组件下的table页面，看看是否卡死

**Comment by yesmeck** [comment]
@DerekHQ 试了 1000 条数据每页 20 条分页并不卡，可以的话还是帮我们提供个 demo 吧，官网上例子太多很难定位问题。

**Comment by DerekHQ** [comment]
@yesmeck 谢谢，这么晚了还在处理问题！明天我准备个DEMO！^_^

**Comment by DerekHQ** [comment]
@yesmeck 在IE11下测试

    "babel-preset-es2015": "^6.0.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.0.0",

    "babel-polyfill": "^6.20.0"

[table.txt](https://github.com/ant-design/ant-design/files/693849/table.txt)

**Comment by benjycui** [comment]
@DerekHQ Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by DerekHQ** [comment]
@benjycui 'Codepen' is not support IE11.

**Comment by benjycui** [comment]
@DerekHQ it works fine while I test it in IE11..

**Comment by DerekHQ** [comment]
@benjycui demo 放到了你的codepen上了，但是IE11下无法看到运行效果，Edge能看； 实际效果是：chrome极为流畅，Edge有些卡顿，IE11极为卡顿； 我们多台笔记本测试效果都是一样！

**Comment by afc163** [comment]
@DerekHQ 你需要 fork 一份。

**Comment by DerekHQ** [comment]
@afc163  [](http://codepen.io/DerekHQ/pen/jyWMzJ?editors=0010)  ^_^

**Comment by yesmeck** [comment]
<img width="403" alt="dingtalk20170203163835" src="https://cloud.githubusercontent.com/assets/465125/22584789/3a8093aa-ea2f-11e6-9e6b-f9f536010497.png">

很奇怪这句为什么要花这么多时间。

**Comment by yesmeck** [comment]
发现跟 css 有关系，用 antd 的 `Table` 但是配合 `rc-table` 的 css 就不会卡。

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/blob/70a0cc0940714307c4804619869b339bc09f6e2f/components/table/style/index.less#L53-L56

```css
&-tbody > tr > td {
  border-bottom: @border-width-base @border-style-base @border-color-split;
  position: relative;
}
```
这几句删掉就不卡了。

**Comment by yesmeck** [comment]
有上面的 CSS 滚动时发生的 paint：

![before](https://cloud.githubusercontent.com/assets/465125/22617175/3287939a-eaf9-11e6-8892-a877373ee5ae.png)

去掉上面的 CSS 后：

![after](https://cloud.githubusercontent.com/assets/465125/22617178/38cd85de-eaf9-11e6-9db4-6eef780fbf31.png)

**Comment by yesmeck** [comment]
去掉 `position: relative` 就可以了。

@afc163 这句有没有特别的作用。

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/commit/01f5b619823f1392ebeb9b33cc4b34b1233290d0

**Comment by afc163** [comment]
有用，稍等我找下场景。

IE 真是见鬼，这居然会卡。

**Comment by afc163** [comment]
之前有需求希望把单元格设置成其他色彩的需求。当时使用了类似下面的 hack 去做：

```jsx
render: () => {
  return <div className="blue">xxx</div>
}
```

```css
.ant-table td {
  position: relative;
}
.blue:after {
  position: abolute;
  background: blue;
}
```

然后后来干脆默认在 td 直接加上 `position: relative;`，方便这样的定制。

---

现在如果有性能问题，先删掉，反正没有作为正式场景放出来。
