### ISSUE TITLE
Extra tab in the dropDownMenu with RU localization

### ISSUE THREAD

**Issue by shibaaboy** [ant-design/ant-design#45231]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-cohen-6yrk2f?file=/src/App.js)

### Steps to reproduce

You need to shrink the screen so that the last tab is not visible and open it through the dropDownMenu. The dropDownMenu will display those tabs that are not visible and the last (only RU localization!)

### What is expected?

There is no active tab in the dropDownMenu and those tabs that are not visible visually are visible

### What is actually happening?

The extra tab appears in the dropDownMenu

<img width="395" alt="image" src="https://github.com/ant-design/ant-design/assets/43315031/0b4d1a94-b4c4-4fcb-9302-a18409028bf3">
<img width="388" alt="image" src="https://github.com/ant-design/ant-design/assets/43315031/27152ca6-031d-414d-8696-9e88764e26cd">

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17.0.2 |
| System | MacOs |
| Browser | Google |

**Comment by MadCcc** [comment]
Cannot run your reproduction

**Comment by shibaaboy** [comment]
@MadCcc I updated the link 
https://codesandbox.io/s/relaxed-cohen-6yrk2f?file=/src/App.js

**Comment by shibaaboy** [comment]
https://github.com/ant-design/ant-design/assets/43315031/29c615f6-c397-401a-a594-de2299df1b01

**Comment by aliBenhenia** [comment]
did you fix it ???
