### ISSUE TITLE
Pivot support for table/virtual table

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#45238]
### What problem does this feature solve?

Allows user to use pivot in tables

### What does the proposed API look like?

In column defs, add pivot: true

and on Table add pivotMode={true}

**Comment by yoyo837** [comment]
It seems to be a request for data visualization. Let’s take a look at this?  https://github.com/antvis/s2.

**Comment by zombieJ** [comment]
Yes. Check this https://s2.antv.antgroup.com/en/
Its the scope of data virtualization.

**Comment by AsuraKev** [comment]
thanks guys, @zombieJ is this a separate package or is it part of ant.design component?
