### ISSUE TITLE
在table中设置了(defaultSelectedRowKeys)的值但是没有生效

### ISSUE THREAD

**Issue by Bluecook** [ant-design/ant-design#45249]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/table-row-tooltip-forked-7h4246?file=/demo.js)

### Steps to reproduce

查看重现链接

### What is expected?

默勾选第二个checkbox框

### What is actually happening?

没有勾选任何checkbox框

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2 |
| System | win1 |
| Browser | Chrome/112.0.0.0 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultvalue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88

**Comment by Jhh910** [comment]
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/ecd139ba9847d0c77607c86339eb8ee6939ca85143a92ae16ebf20f58325e1b6/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/table-row-tooltip-forked-7h4246?file=/demo.js)
> 
> ### Steps to reproduce
> 查看重现链接
> 
> ### What is expected?
> 默勾选第二个checkbox框
> 
> ### What is actually happening?
> 没有勾选任何checkbox框
> 
> Environment	Info
> antd	5.5.1
> React	18.2
> System	win1
> Browser	Chrome/112.0.0.0

请问你解决了吗？我也遇到了这个问题
