### ISSUE TITLE
YearPicker: 关于只选择年的日期选择器属性

### ISSUE THREAD

**Issue by songdun** [ant-design/ant-design#4524]
日期选择器能添加一个属性让它初始化就只选择年吗？目前只有日期和月

**Comment by afc163** [comment]
直接用 Select ？

**Comment by songdun** [comment]
产品比较事儿  要用日期选择器的样子 5555555555555555

**Comment by afc163** [comment]
单独维度的话，基于 DatePicker 改造成本较高且回报略低，用 Select 更简单和直接，我们在 https://ant.design/components/calendar/ 里也是这么做的。

你可以让你们的产品看这个回复。

**Comment by afc163** [comment]
Maybe we should add a YearPicker now.

**Comment by jrschumacher** [comment]
@afc163 I have a WIP pull request for YearPicker react-component/calendar#427

**Comment by yoyo837** [comment]
单纯下拉做不到 YearPicker 万年历 可选年份的需求.

@jrschumacher Why not a picker ?

**Comment by jrschumacher** [comment]
@yoyo837 because you get the ability to view decades similar to the other calendars. But most importantly, to me, is a consistent UX. For all date-time data gathering the user will experience a similar interface.

**Comment by aixfox** [comment]
@afc163 

Here are some reasons for YearPicker:

1. Same styles as DatePicker.
2. Select not exports moment instance.
3. No `disabledDate` api of Select.

Hoping more consideration of year picker, thank you!

**Comment by lx70770** [comment]
@jrschumacher 您好  请问antd大概多久可以支持 mode='year' 这个属性呢

**Comment by jrschumacher** [comment]
@lx70770 I'm not sure Google translated that correctly. Antd/rc-calendar does not support this mode. I have not heard anything from my PR.

**Comment by lx70770** [comment]
> @lx70770 I'm not sure Google translated that correctly. Antd/rc-calendar does not support this mode. I have not heard anything from my PR.
That's ok , Thank you so much!

**Comment by yeluolei** [comment]
+1 for this feature

**Comment by jrschumacher** [comment]
@yeluolei will you add your reaction here: https://github.com/react-component/calendar/issues/427

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Aladingding** [comment]
<LocaleProvider locale={zhCN}> { getFieldDecorator(field)( <DatePicker placeholder={ placeholder || '请选择年份' } locale={ zhCN } // value={ this.state.time } open={ this.state.yearStartShow } mode='year' format='YYYY' // onChange={ this.handleChange } onOpenChange={ this.handleOpenChange } onPanelChange={ this.handlePanelChange } /> } </LocaleProvider>

do like this ,you will fix this bug, combine use onOpenChange and onPanelChange （maybe you need onFocus onBlur）

tks, 一江西流 关于antd 日期组件只选择年份，设置mode=year无法获取value的解决办法

四个方法并用一定能完美实现你的需求，哈哈哈，官方说，你既然都单选了，为什么不用下拉框，说的好有道理，我竟无言以对
阿里产品真的考虑周全呀，>_< 但是我们产品说，我就要这样，我不管

**Comment by afc163** [comment]
The list of date-related pickers we may need:

- [ ] YearPicker
- [ ] RangePicker.YearPicker
- [ ] RangePicker.MonthPicker
- [ ] RangePicker.YearMonthPicker
- [ ] TimePicker.RangePicker

**Comment by Geassu** [comment]
we need YearPicker right now

**Comment by DongShi** [comment]
Is the YearPicker available in the latest antd release?
How about adding a QuarterPicker?

**Comment by zhangyanling77** [comment]
> { getFieldDecorator(field)( <DatePicker placeholder={ placeholder || '请选择年份' } locale={ zhCN } // value={ this.state.time } open={ this.state.yearStartShow } mode='year' format='YYYY' // onChange={ this.handleChange } onOpenChange={ this.handleOpenChange } onPanelChange={ this.handlePanelChange } /> }
> 
> do like this ,you will fix this bug, combine use onOpenChange and onPanelChange （maybe you need onFocus onBlur）
> 
> tks, 一江西流 [关于antd 日期组件只选择年份，设置mode=year无法获取value的解决办法](https://www.cnblogs.com/zyl-Tara/p/10197177.html)
> 
> 四个方法并用一定能完美实现你的需求，哈哈哈，官方说，你既然都单选了，为什么不用下拉框，说的好有道理，我竟无言以对
> 阿里产品真的考虑周全呀，>_< 但是我们产品说，我就要这样，我不管

因为UI风格要统一，哈哈哈
我就是一江西流

**Comment by afc163** [comment]
#16984

**Comment by CornerYoung** [comment]
RangePicker组件中设置mode为mode={['month', 'month']}，是想要实现月份区间的选择，这时候defaultValue会失效，请问该怎样显示默认时间？

**Comment by afc163** [comment]
We support all picker in v4 now: https://ant.design/components/date-picker/

**Comment by xiaoheikejj** [comment]
> 单独维度的话，基于 DatePicker 改造成本较高且回报略低，用 Select 更简单和直接，我们在 https://ant.design/components/calendar/ 里也是这么做的。
> 
> 你可以让你们的产品看这个回复。

厉害厉害 牛逼
