### ISSUE TITLE
[Doc] 官网点击哈希链接不会跳转

### ISSUE THREAD

**Issue by yyz945947732** [ant-design/ant-design#45241]
### Reproduction link

[https://ant-design.antgroup.com/components/form-cn](https://ant-design.antgroup.com/components/form-cn)

### Steps to reproduce

V5 官方文档，点击组件文档内的链接，不会跳到对应的内容。

<img width="524" alt="image" src="https://github.com/ant-design/ant-design/assets/47586954/377d342d-c0ec-489c-85f8-78a86ca56380">

### What is expected?

点击组件文档内的哈希链接，应该跳到对应内容

### What is actually happening?

点击组件文档内的哈希链接，没有跳到对应内容

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| Browser | Chrome 116.0.5845.110 |

**Comment by yyz945947732** [comment]
hash 链接都不会跳转，如果是打开外链的，或者打开新链接的，就可以。

<img width="143" alt="image" src="https://github.com/ant-design/ant-design/assets/47586954/055f6e79-3240-48e5-b9f1-1a000ca8ce48">

**Comment by yyz945947732** [comment]
https://github.com/ant-design/ant-design/blob/master/.dumi/theme/common/Link.tsx#L33

**Comment by Wxh16144** [comment]
原来不止我一个人有这个感知，之前都睁一只眼闭一只眼的，哈哈哈哈

**Comment by afc163** [comment]
点右边 Anchor 也经常跳不过去。

**Comment by Wxh16144** [comment]
@yyz945947732  想来一个 PR 吗？

**Comment by yyz945947732** [comment]
我用空的话可以看看。
