### ISSUE TITLE
DatePicker.generatePicker 类型报错

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#45257]
### Reproduction link

[https://github.com/crazyair/dumi-4/blob/main/src/DatePicker/index.tsx#L5](https://github.com/crazyair/dumi-4/blob/main/src/DatePicker/index.tsx#L5)

### Steps to reproduce

1. `clone https://github.com/crazyair/dumi-4.git`
2. `pnpm i` 使用 `pnpm v6.35.1 `
3. 查看 `Datepicker`

![image](https://github.com/ant-design/ant-design/assets/7971419/b71abd18-c4e4-4f8b-84fd-10b15fb1af28)

或者

![image](https://github.com/ant-design/ant-design/assets/7971419/4d5db9ff-de82-4cbe-9f87-0a18ff594f6b)

### What is expected?

不报错

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by Wxh16144** [comment]
貌似需要 `as` 断言？ antd 内部好像就是这样的（不太确定哈

**Comment by crazyair** [comment]
> 貌似需要 `as` 断言？ antd 内部好像就是这样的（不太确定哈

as 哪个? 这个好像不是简单类型

**Comment by afc163** [comment]
```
➜ pnpm -v
8.9.0
```

我使用这个 pnpm 版本没有重现出问题，@crazyair 也试试升级一下？

<img width="816" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/1904426e-5932-41c0-abd2-41750a41407b">

**Comment by crazyair** [comment]
> ```
> ➜ pnpm -v
> 8.9.0
> ```
> 
> 我使用这个 pnpm 版本没有重现出问题，@crazyair 也试试升级一下？
> 
> <img alt="图片" width="816" src="https://user-images.githubusercontent.com/507615/277541039-1904426e-5932-41c0-abd2-41750a41407b.png">

目前我们部门都在用 6.35.1，这个还不方便升级

**Comment by crazyair** [comment]
附上 ts 的临时解决方案 来自 @Wxh16144 
在 paths 里增加
```
"rc-picker/*": ["./node_modules/rc-picker/*"] 
```

**Comment by afc163** [comment]
那我先关了，antd 侧貌似做不了什么。
