### ISSUE TITLE
Hide table column if empty

### ISSUE THREAD

**Issue by obito** [ant-design/ant-design#45251]
### What problem does this feature solve?

I would like to hide a column in a table if the data/render is empty.

For example, if a user doesn't have a `role`, I don't want to show the column `Role`. Right now, it will show the column with an empty cell. The only workaround to hide a column is to set the width at `0` - but it's not dynamic. 

### What does the proposed API look like?

Make the `width` dynamic like the `render`, so based on the `record` I can be able to show or hide that column by setting the width to 0 or not.

**Comment by afc163** [comment]
Try `onCell`

**Comment by obito** [comment]
> Try `onCell`

I don't get how `onCell` can solve my problems as it takes an event ?

**Comment by zombieJ** [comment]
What will it be if 2 record one of it has Role but another not have?

**Comment by obito** [comment]
> What will it be if 2 record one of it has Role but another not have?

It's a collapsed table. For example, you have a list of user, then if you click on it, it shows the collapsed table with all the proprieties. I would like to hide a column if it's empty.

**Comment by zombieJ** [comment]
Seems just HOC is enough:
https://codesandbox.io/s/ji-ben-yong-fa-antd-5-10-0-forked-3gy2wd?file=/demo.tsx
