### ISSUE TITLE
Input control outline width theme is not working in latest version

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#45254]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-10-0-forked-6gt326?file=/demo.tsx)

### Steps to reproduce

see sandbox

### What is expected?

theme applies

### What is actually happening?

theme is not applied

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by MadCcc** [comment]
In 5.10.0 we removed shadow by default and `controlOutlineWidth` will not work neither.
If you want to customize, please use `activeShadow` token.

**Comment by AsuraKev** [comment]
@MadCcc  so i have added the activeShadow and its showing fine, however the controlOutlineWidth still doesnt take effect  :(

![image](https://github.com/ant-design/ant-design/assets/52765572/c68f9b14-109f-4f63-a1fb-6b766458fd54)

**Comment by AsuraKev** [comment]
and Select component doesnt have activeShadow to configure the outline ...
