### ISSUE TITLE
如何让其他可以拖拽的元素在拖动到Tree节点上时，Tree节点可以触发拖拽相关事件

### ISSUE THREAD

**Issue by ChenKun1997** [ant-design/ant-design#45256]
### What problem does this feature solve?

我的需求是表格的某一行拖拽到Tree的某个节点上时，需要根据节点的数据和表格的数据调一个接口，我现在是使用原生事件让表格的一行可拖拽，但是拖拽到Tree的节点时是没有任何反应的，不会有样式的反馈也不会触发Tree组件拖拽相关的事件，不知道是否支持
![image](https://github.com/ant-design/ant-design/assets/24249578/81e13be7-4c83-4064-9748-e0be858b4daa)

### What does the proposed API look like?

其他可拖拽节点拖拽到TreeNode节点上时也触发相关拖拽事件

**Comment by afc163** [comment]
Duplicate of #26560
