### ISSUE TITLE
Steps with progress dot style

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4525]
![](https://zos.alipayobjects.com/rmsportal/DDuHruIcGfifQiblNfJV.png)

```jsx
<Steps dot />

or

<Steps progressDot />
```

It looks like Slider but it is not.

Hide the `Steps[title]` and move `Steps[decription]` under the dot.

**Comment by ddcat1115** [comment]
The popover is not included?

**Comment by afc163** [comment]
How about `<Steps progressDot={(dot) => <Popover>{dot}</Popover>} />`?

**Comment by ddcat1115** [comment]
👌

**Comment by afc163** [comment]
已经发布上线。
