### ISSUE TITLE
The callback of the parent component of the modal is called when clicked inside the modal window

### ISSUE THREAD

**Issue by ytreu111** [ant-design/ant-design#45252]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/zen-goldwasser-2xz29f)

### Steps to reproduce

Open modal, click on content inside modal

### What is expected?

The event will only be triggered on content

### What is actually happening?

The event is called on the content and parent component of the modal

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by Yuiai01** [comment]
You can add `stopPropapation` to prevent events from bubbling.  https://codesandbox.io/p/sandbox/condescending-wood-sxk6vs?file=%2Fsrc%2FApp.tsx%3A23%2C32

**Comment by ytreu111** [comment]
But this does not solve the problems of clicking on the overlay or buttons
