### ISSUE TITLE
Segmented component icons move when switching between values [Safari]

### ISSUE THREAD

**Issue by adelinapereteatcu** [ant-design/ant-design#45250]
### Reproduction link

[https://ant.design/components/segmented#segmented-demo-icon-only](https://ant.design/components/segmented#segmented-demo-icon-only)

### Steps to reproduce

1. Have a segmented component with icons/icons only in Safari browser
2. Switch between values

### What is expected?

The placement of icons not to change

### What is actually happening?

The icons move

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | React 18 |
| System | MacOS |
| Browser | Safari Version 16.6 (18615.3.12.11.2) |

**Comment by Yuiai01** [comment]
Hi, Is that what you're referring to?
https://github.com/ant-design/ant-design/assets/112228030/c7276249-5b14-4e29-a410-c814f3a13e07

**Comment by Yuiai01** [comment]
Hi, Is that what you're referring to?

https://github.com/ant-design/ant-design/assets/112228030/0fe5da90-0aa8-43dc-a6d4-3cad06069d09

**Comment by MadCcc** [comment]
Didn't get reproduced in Safari 16.1

**Comment by afc163** [comment]
Reproduced in Safari 16.3 (18614.4.6.1.5)

**Comment by adelinapereteatcu** [comment]
> Hi, Is that what you're referring to?
> 
>  antd-video.mov

yes
