### ISSUE TITLE
Selec组件更新后样式显示错误

### ISSUE THREAD

**Issue by yk9710** [ant-design/ant-design#45261]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ding-zhi-hui-tian-nei-rong-antd-5-10-0-forked-t9vxmf)

### Steps to reproduce

使用optionViewRender属性，默认回填children

### What is expected?

期望回填的时候隐藏多余的部分

### What is actually happening?

实际上因为更新后ant-select-selection-placeholder多了个align-self: center属性导致隐藏失败

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
哪个版本的效果是预期的？

**Comment by yk9710** [comment]
> 哪个版本的效果是预期的？

5.9.0

**Comment by yk9710** [comment]
> 哪个版本的效果是预期的？

![image](https://github.com/ant-design/ant-design/assets/102608044/5b7f63a3-8896-466d-aabc-d69a4a624b37)
去除这块就ok了

**Comment by zombieJ** [comment]
看起来新的是符合预期的，过去没有对齐下强行把行顶了下去。

**Comment by yk9710** [comment]
> 看起来新的是符合预期的，过去没有对齐下强行把行顶了下去。

那就只能选择设置回填label了

**Comment by zombieJ** [comment]
关联一下相关 issue #44753
