### ISSUE TITLE
After outer component updated selectedRowKeys prop of Table, the checked rows of table doesn't change

### ISSUE THREAD

**Issue by lulut** [ant-design/ant-design#4526]
#### Environment(required)

- antd version: 2.6
- OS and its version: Mac
- Browser and its version: Chrome

#### What did you do? Please provide steps to re-produce your problem.

let rowSelection = {
            selectedRowKey: this.state.userSelectedRowKeys,
            onChange: this.userTabTableSelectChange.bind(this),
        };

我在Table的外部Component通过setState修改了userSelectedRowKeys的值，Table的选中状态没有更新。

#### What do you expected?

Table checked rows会根据userSelectedRowKeys的变化而更新

#### What happen?

没变化

**Comment by afc163** [comment]
```diff
- selectedRowKey: this.state.userSelectedRowKeys,
+ selectedRowKeys: this.state.userSelectedRowKeys,
```
