### ISSUE TITLE
Input支持清除前后空格配置

### ISSUE THREAD

**Issue by magao1991** [ant-design/ant-design#45269]
### What problem does this feature solve?

用户在输入文本信息时会误添加前后空格，影响提交校验不通过，开发人员往往需要在form.item组件或input组件中接入其他props属性进行格式转换，大量存在input时，重复工作繁琐，如果支持该功能的可选配置，则能在很大程度上减少开发的工作量

### What does the proposed API look like?

<Input trim /> 添加trim即为支持前后空格清除 或是在 ConfigProvider的input中支持开关配置

**Comment by Wxh16144** [comment]
HOC 一下呗

**Comment by MadCcc** [comment]
有类似功能的参考么，直接在 onChange 里过滤可能会导致输入不了空格

**Comment by magao1991** [comment]
> 有类似功能的参考么，直接在 onChange 里过滤可能会导致输入不了空格

我们是只需要去掉前后空格 不支持只输入空格 以前antd的老版本 是支持trim这个属性的 现在是没有了

**Comment by forwzb** [comment]
在change时，使用formRef?.current.setFieldValue() 修改;
或者 form:
   onValuesChange={(changedValues, values) => {
                    for (let changedValuesKey in changedValues) {
                        formRef?.current?.setFieldValue(changedValuesKey, changedValues[changedValuesKey].trim());
                    }
                }}
