### ISSUE TITLE
Button loading={delay: 0}是不显示加载还是不延时加载

### ISSUE THREAD

**Issue by YDFlame13** [ant-design/ant-design#45273]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dawn-brook-gwmy2q?file=/src/App.js)

### Steps to reproduce

无

### What is expected?

不延时加载

### What is actually happening?

不加载

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 117.0.5938.134 |

**Comment by zombieJ** [comment]
`delay: 0` 应该出 loading，看起来像是个 bug
