### ISSUE TITLE
Modal.confirm 类型isSilent没有暴漏出来

### ISSUE THREAD

**Issue by xingxiulaoxian** [ant-design/ant-design#45275]
### What problem does this feature solve?

功能已经存在，但是api没有暴漏出来，找起来太麻烦了

### What does the proposed API look like?

在ts类型中添加isSilent
`function confirm(config: ModalFuncProps & {isSilent: ()=> boolean})
`

**Comment by MadCcc** [comment]
没有暴露的说明是不希望用户使用的内部配置，不保证稳定性

**Comment by yoyo837** [comment]
[官方文档中没有提供的隐藏 API 我可以使用吗？](https://ant.design/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)
