### ISSUE TITLE
Tag 标签 的样式优化

### ISSUE THREAD

**Issue by Chinglik** [ant-design/ant-design#4528]
目前艳丽的 tag 是中台产品中会比较难应用，尤其当列表或卡片中会因为色调太跳而页面显得有些乱，故将色值调为 [色板的第二格（浅色）+深字]的样式。但为了考虑延展性，背景色和字体色应该保持灵活的可配。\(^o^)/~

![](https://static.dingtalk.com/media/lALOmwG4E1jNAd4_478_88.png_620x10000q90g.jpg)

**Comment by afc163** [comment]
:+1:

**Comment by afc163** [comment]
在保持现有的接口的前提下。

```
<Tag color="#xxxxxx" />
```

添加属性 `presetColor`，用于标准化色彩的标签。

```
<Tag presetColor="red" />   // background-color: @red-2;
<Tag presetColor="blue" />  // background-color: @red-3;
```

---

另外，样式上可以参照 http://blueprintjs.com/docs/#components.tag 字体也带有色彩如何？

**Comment by afc163** [comment]
<img width="440" alt="image" src="https://cloud.githubusercontent.com/assets/507615/21878693/eed71652-d8ce-11e6-8dea-7077f884f083.png">
