### ISSUE TITLE
select组件支持checkbox吗

### ISSUE THREAD

**Issue by sixcx** [ant-design/ant-design#45288]
### What problem does this feature solve?

修改默认样式 增加checkbox

### What does the proposed API look like?

添加checkable属性

**Comment by afc163** [comment]
不太理解是什么意思，能具体描述一下么？

**Comment by GeorgeHcc** [comment]
应该是想把多选的默认样式增加一种checkbox样式？

![image](https://github.com/ant-design/ant-design/assets/72842677/be09d13f-93ef-41e2-8be5-d05c0e34b5f9)

**Comment by sixcx** [comment]
> 应该是想把多选的默认样式增加一种checkbox样式？
> 
> ![image](https://user-images.githubusercontent.com/72842677/274338467-be09d13f-93ef-41e2-8be5-d05c0e34b5f9.png)

是的 在前面增加checkbox选中 去掉后面的勾选

**Comment by sixcx** [comment]
> 不太理解是什么意思，能具体描述一下么？

和@GeorgeHcc 这个描述一致

**Comment by afc163** [comment]
这个可以自行定制 option 里的 label 来实现，后面的勾选可以通过覆盖样式来去掉。
