### ISSUE TITLE
Table虚拟化，scroll.x横向区域列宽问题

### ISSUE THREAD

**Issue by cjtcjt999** [ant-design/ant-design#45281]
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn#scroll](https://ant-design.antgroup.com/components/table-cn#scroll)

### Steps to reproduce

none

### What is expected?

虚拟列表与普通列表的scroll属性表现完全不一致
1.开启虚拟化，有的列不设width是为了适应弹性布局，但是虚拟列表必须配置scroll.x，导致需要根据每列宽度计算scroll.x，而无宽度列无法计算，也无法做到适应剩余空间
2.开启虚拟化，固定列的宽度会根据scroll.x计算，做不到固定宽度

### What is actually happening?

尽量做到虚拟列表与普通列表的scroll属性表现一致

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | win11 |
| Browser | 117.0.5938.92 |

**Comment by zombieJ** [comment]
给个重现看看你的配置~

**Comment by cjtcjt999** [comment]
https://codesandbox.io/embed/xu-ni-lie-biao-antd-5-9-4-forked-2c3yvx?fontsize=14&hidenavigation=1&theme=dark

**Comment by zombieJ** [comment]
发在 `7.35.2` 上，下个 feature 会带上哈~

**Comment by melva10** [comment]
scroll 有大问题 当 不给table设置宽度时 使用scroll属性会报Cannot read properties of null (reading 'querySelector')问题

**Comment by melva10** [comment]
不对设了宽度也会报这个问题，具体来自这段代码
`function useContainerWidth(prefixCls) {
  const getContainerWidth = (ele, width) => {
    const container = ele.querySelector(`.${prefixCls}-container`);
    let returnWidth = width;
    if (container) {
      const style = getComputedStyle(container);
      const borderLeft = parseInt(style.borderLeftWidth, 10);
      const borderRight = parseInt(style.borderRightWidth, 10);
      returnWidth = width - borderLeft - borderRight;
    }
    return returnWidth;
  };
  return getContainerWidth;
}`

**Comment by hardmanhong** [comment]
> 发在 `7.35.2` 上，下个 feature 会带上哈~

当列非常多时，能否支持同时开启横向的虚拟滚动
