### ISSUE TITLE
Watermark水印包裹Modal, Drawer

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#45294]
### What problem does this feature solve?

现在是modal和drawer在子级时都会赋予水印？能加个属性判断去除吗，因为最外层和水印和弹层的水印会重叠

[示例](https://codesandbox.io/s/modal-yu-drawer-antd-5-9-2-forked-6cmwzf?file=/demo.tsx)

```javascript
<Watermark>
   <Modal />
   <Drawer/>
</Watermark>
```
### What does the proposed API look like?

modal和drawer被裹住时，可配置不出现水印

**Comment by Wxh16144** [comment]
把水印的 z-index 设置小于 1000 就好了把？

**Comment by theDoinb** [comment]
> 把水印的 z-index 设置小于 1000 就好了把？

降低`z-index`后，确实感官上好了点，但感觉还是只有一层水印比较舒服...

再者如果我要`modal`和`drawer`要加水印，其实我可以自己直接在对内容加就行了...

如果裹住时不对弹窗这类子级加水印，水印生成效率会不会更快？

**Comment by MadCcc** [comment]
> 再者如果我要`modal`和`drawer`要加水印，其实我可以自己直接在对内容加就行了...

这个我们认为是期望行为，所以默认做了优化

实际上你的问题是自己设置了 `z-index`，去掉会好很多

**Comment by theDoinb** [comment]
> > 再者如果我要`modal`和`drawer`要加水印，其实我可以自己直接在对内容加就行了...
> 
> 这个我们认为是期望行为，所以默认做了优化
> 
> 实际上你的问题是自己设置了 `z-index`，去掉会好很多

因为有的组件设置的`z-index`较高，所以水印才拉满的，不过UI看了没啥问题，我这边也不去搞了...

**Comment by Wxh16144** [comment]
> modal和drawer被裹住时，可配置不出现水印

感觉确实会出现有些 ui 层级比较高，业务代码缺少规范，可以做一个开关， @zombieJ 已经打上了 feature request。确认一下是不是要做？

**Comment by yoyo837** [comment]
z-Index 有关的RFC?

**Comment by Wxh16144** [comment]
> z-Index 有关的RFC?

我前面也想到这个，把 RFC 作者艾特出来让他设计的时候也考虑一下。（但是这个开关感觉还是有必要

**Comment by zombieJ** [comment]
两件事情，Watermark 禁止传导弹出元素 和 原本层的 zIndex 不是一件事情。只是恰好这个 issue 两边都占到了。

**Comment by theDoinb** [comment]
话说如果要改，看能不能加个时间戳的实时更新，在用户不去操作界面时，水印的时间戳仍能实时实现当前时间: `yyyy-mm-dd mm:ss`
