### ISSUE TITLE
Form.Item中使用TreeSelect组件并且添加属性treeCheckable的时候Form的initialValues给的值绑定不到value中

### ISSUE THREAD

**Issue by zhengting1025** [ant-design/ant-design#45299]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-73nwgw?file=/index.js)

### Steps to reproduce

在Form中给initialValues={{ remember: ["leaf3"] }}，初始展示TreeSelect的时候，无法显示绑定的值

### What is expected?

能够显示初始值

### What is actually happening?

不显示初始值

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
```diff
-- valuePropName="checked"
```
