### ISSUE TITLE
5.9.4升级到5.10.0后启动后控制台报rc-util导出useEvent错误

### ISSUE THREAD

**Issue by Pleilei** [ant-design/ant-design#45298]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce

Attempted import error: 'useEvent' is not exported from 'rc-util' (imported as 'useEvent').
ERROR in ./node_modules/rc-cascader/es/Panel.js 76:22-30
export 'useEvent' (imported as 'useEvent') was not found in 'rc-util' (possible exports: get, set, useMergedState, warning)
 @ ./node_modules/rc-cascader/es/index.js 2:0-28 3:0-17
 @ ./node_modules/antd/es/cascader/index.js 14:0-37 38:4-14 192:54-64
 @ ./node_modules/antd/es/index.js 16:0-49 16:0-49
 @ ./src/App.tsx 3:0-45 19:30-44 23:17-39
 @ ./src/index.tsx 12:0-24 25:33-36

### What is expected?

下个版本修复

### What is actually happening?

下个版本修复

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18 |
| System | macOS13.5.2 |
| Browser | Google Chrome 版本 116.0.5845.110（正式版本） (arm64) |

**Comment by MadCcc** [comment]
可以删了 node_modules 和 lock 文件重新安装一下依赖

**Comment by Pleilei** [comment]
感谢、删除 lock 文件重装不报错了
