### ISSUE TITLE
TreeSelect组件在showSearch和loadData共存的情况, 必现当删除搜索框最后一个字符时或者搜索后点击选择节点后, 会触发loadData请求异步数据

### ISSUE THREAD

**Issue by speakice** [ant-design/ant-design#45293]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-bu-jia-zai-antd-5-9-4-forked-y4cjf4?file=/demo.tsx)

### Steps to reproduce

1. 输入框输入to; 2. 然后一个字符一个字符的删除

### What is expected?

选项恢复筛选前数据, 不触发loadData, 无loading

### What is actually happening?

选项恢复筛选前数据, 触发loadData, loading, 大批量数据时, 会出现大量loading一直旋转, 体验极差

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | macOS 12.6.7 intel |
| Browser | 117.0.5938.149 |

---
大批量数据,虚拟滚动时, loadData有时也会自动触发

**Comment by zombieJ** [comment]
TreeSelect 不会在搜索态触发 `loadData`，是你的 `filterTreeNode` 里写了异步加载逻辑导致的。删掉即可：

```diff
      filterTreeNode={(input, treeNode) => {
        const match = `${treeNode.title}`.includes(input);

        if (input && match && !treeNode.isLeaf && !treeNode.children) {
          // Do some loading logic
          console.log("treeNode", treeNode);
--        onLoadData(treeNode as any);
        }
        return match;
      }}
```

**Comment by pengdongliang** [comment]
`antd@5.14.1` 一模一样的问题, 删掉了 `filterTreeNode` 还是一样有问题
