### ISSUE TITLE
getFieldsValue()获取值为空的表单控件值的问题

### ISSUE THREAD

**Issue by jasminecjc** [ant-design/ant-design#4530]
#### Environment(required)

- antd version: 2.5.0
- OS and its version:
- Browser and its version:  chrome

#### What did you do? Please provide steps to re-produce your problem.

表单如图
![image](https://cloud.githubusercontent.com/assets/13568376/21762920/35e31c3e-d696-11e6-994a-e6ce4d450fce.png)
时间，漏斗环节单选，乘客首单多选，如果多选的值为空期望通过getFieldsValue()获取到getFieldDecorator里设置的name并且其值为undefined

#### What happen?
如果乘客首单值为空
通过getFieldsValue()获取到的值每次会不一样
有时为
`{ funnel_stage: "", funnel_date: "最近7天"}`
有时为
`Object {funnel_id: "56", funnel_stage: "", funnel_date: "最近7天", dimension-乘客所在城市: undefined}`
这两种出现的频率可能为如果用户快速选择并点击查询就会出现第一种情况
但是我期望的是每次都为下面一种

#### Re-producible online demo
http://codepen.io/anon/pen/egpXyP?editors=0010
不知道为什么一直没运行出来，只好这样放上来了

完整的逻辑是
![image](https://cloud.githubusercontent.com/assets/13568376/21792584/ccfb7b68-d725-11e6-9258-7937fa796628.png)
随着漏斗列表选中项的不同，后面读取到的funnelDimension不同

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
<img width="590" alt="image" src="https://cloud.githubusercontent.com/assets/507615/21932042/80b87a6a-d9d9-11e6-8d7f-085cc95764f2.png">

Col 的 key 要稳定，否则随着数据的变化，React 的 VitualDom 会对不上正确的节点。
