### ISSUE TITLE
RangePicker 选中日期后为什么会自动初始化到当前时间，是否可以加个属性操控

### ISSUE THREAD

**Issue by sishen654** [ant-design/ant-design#45309]
### What problem does this feature solve?

业务需求要改回 00:00:00，而不是当前时间，每次修改会提升操作人员的操作成本（每次都要改为00:00:00）

### What does the proposed API look like?

添加一个属性可以控制时间为当前或者自定义

**Comment by sishen654** [comment]
选中日期，时间自动调整到当前
![image](https://github.com/ant-design/ant-design/assets/65691266/361bb830-7354-4d56-a93a-dc9e844692cd)

**Comment by Yuiai01** [comment]
Ref https://github.com/ant-design/ant-design/issues/44524， @zombieJ @MadCcc 大佬们看看这里需要不

**Comment by yoyo837** [comment]
> Ref [https://github.com/ant-design/ant-design/issues/44524，](https://github.com/ant-design/ant-design/issues/44524%EF%BC%8C) @zombieJ @MadCcc 大佬们看看这里需要不

推进的话, 时候直接到群里丢链接, GitHub信息太多, 他们不一定都能看到.

**Comment by Yuiai01** [comment]
> > Ref [https://github.com/ant-design/ant-design/issues/44524，](https://github.com/ant-design/ant-design/issues/44524%EF%BC%8C) @zombieJ @MadCcc 大佬们看看这里需要不
> 
> 推进的话, 时候直接到群里丢链接, GitHub信息太多, 他们不一定都能看到.

好～

**Comment by sishen654** [comment]
我还以为有官方回了。。。

**Comment by zombieJ** [comment]
感觉加属性没个头，还是需要搞个状态机让开发者可以插如处理逻辑比较好。

**Comment by sishen654** [comment]
> 感觉加属性没个头，还是需要搞个状态机让开发者可以插如处理逻辑比较好。

主要是自动切换到当前，没法改的话有点不符合用户常识，看了下字节那个框架不会

**Comment by sishen654** [comment]
> 感觉加属性没个头，还是需要搞个状态机让开发者可以插如处理逻辑比较好。

尽量简单着来吧，毕竟五的版本都出了

**Comment by sishen654** [comment]
忘了补充了， antd 版本是 4.24.14

**Comment by afc163** [comment]
```
      showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }}
```

<img width="887" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/28f1a270-6778-48a4-8777-3254080d3c0b">

**Comment by sishen654** [comment]
> ```
>       showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }}
> ```
> 
> <img alt="图片" width="887" src="https://user-images.githubusercontent.com/507615/274583428-28f1a270-6778-48a4-8777-3254080d3c0b.png">

5.x 的版本不适配 umi 框架，疯狂报错，有考虑在 4 版本中实现吗

**Comment by Yuiai01** [comment]
> > ```
> >       showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }}
> > ```
> > 
> > 
> > <img alt="图片" width="887" src="https://user-images.githubusercontent.com/507615/274583428-28f1a270-6778-48a4-8777-3254080d3c0b.png">
> 
> 5.x 的版本不适配 umi 框架，疯狂报错，有考虑在 4 版本中实现吗

5.x 默认使用 `dayjs`，这里应该是  `showTime={{ defaultValue: dayjs('00:00:00', 'HH:mm:ss') }}`

**Comment by sishen654** [comment]
> > > ```
> > >       showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }}
> > > ```
> > > 
> > > 
> > > <img alt="图片" width="887" src="https://user-images.githubusercontent.com/507615/274583428-28f1a270-6778-48a4-8777-3254080d3c0b.png">
> > 
> > 
> > 5.x 的版本不适配 umi 框架，疯狂报错，有考虑在 4 版本中实现吗
> 
> 5.x 默认使用 `dayjs`，这里应该是 `showTime={{ defaultValue: dayjs('00:00:00', 'HH:mm:ss') }}`

dayjs 是什么意思呢。4.x 的版本没有这两个属性，由于 umi 的问题无法升级到 5.x 版本

**Comment by Yuiai01** [comment]
> > > > ```
> > > >       showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }}
> > > > ```
> > > > 
> > > > 
> > > > <img alt="图片" width="887" src="https://user-images.githubusercontent.com/507615/274583428-28f1a270-6778-48a4-8777-3254080d3c0b.png">
> > > 
> > > 
> > > 5.x 的版本不适配 umi 框架，疯狂报错，有考虑在 4 版本中实现吗
> > 
> > 
> > 5.x 默认使用 `dayjs`，这里应该是 `showTime={{ defaultValue: dayjs('00:00:00', 'HH:mm:ss') }}`
> 
> dayjs 是什么意思呢。4.x 的版本没有这两个属性，由于 umi 的问题无法升级到 5.x 版本

抱歉，我以为是你使用 antd 5.x 出现了问题，不过这个属性在 4.x 版本上是有支持的。
<img width="978" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/3331fa7b-4a50-4a5c-9b68-f1601710eb6c">

**Comment by sishen654** [comment]
> > > > > ```
> > > > >       showTime={{ defaultValue: moment('00:00:00', 'HH:mm:ss') }}
> > > > > ```
> > > > > 
> > > > > 
> > > > > <img alt="图片" width="887" src="https://user-images.githubusercontent.com/507615/274583428-28f1a270-6778-48a4-8777-3254080d3c0b.png">
> > > > 
> > > > 
> > > > 5.x 的版本不适配 umi 框架，疯狂报错，有考虑在 4 版本中实现吗
> > > 
> > > 
> > > 5.x 默认使用 `dayjs`，这里应该是 `showTime={{ defaultValue: dayjs('00:00:00', 'HH:mm:ss') }}`
> > 
> > 
> > dayjs 是什么意思呢。4.x 的版本没有这两个属性，由于 umi 的问题无法升级到 5.x 版本
> 
> 抱歉，我以为是你使用 antd 5.x 出现了问题，不过这个属性在 4.x 版本上是有支持的。 <img alt="image" width="978" src="https://user-images.githubusercontent.com/112228030/274782213-3331fa7b-4a50-4a5c-9b68-f1601710eb6c.png">

不好意思我的问题，搜索错文档了，感谢解答❤️❤️❤️
