### ISSUE TITLE
Select, Tree Select, AutoComplete, Cascader missing shadow design tokens

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#45303]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qnlkcn)

### Steps to reproduce

No option to add activeShadow token

### What is expected?

Select and Tree Select have the shadow token like Input and Datepicker

### What is actually happening?

design token missing

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2 |
| System | Web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
Looks like its missing the following design tokens

![image](https://github.com/ant-design/ant-design/assets/52765572/601aabb6-a292-4bea-a335-7fda223c7418)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/45286 had reverted focus style, `controlOutlineWidth` is back now.
