### ISSUE TITLE
notification组件如何定位到浏览器的右下角？

### ISSUE THREAD

**Issue by focus7eleven** [ant-design/ant-design#4531]
notification组件，可以定位到浏览器的右下角吗？我看目前的配置里面只有top这一属性，如何根据bottom来定位呢？

**Comment by afc163** [comment]
暂时不支持，欢迎 PR ~

**Comment by liu2080019** [comment]
针对一楼提出的问题的解决方案：
1.下载antd的静态文件https://unpkg.com/antd/dist/antd.js
2.找到notification对应的设置位置的代码，将top改成bottom
```
function getNotificationInstance(prefixCls) {
	    if (notificationInstance) {
	        return notificationInstance;
	    }
	    notificationInstance = _rcNotification2["default"].newInstance({
	        prefixCls: prefixCls,
	        style: {
	            top: defaultTop,
	            right: 0
	        }
	    });
	    return notificationInstance;
	}
```
3.压缩该文件，在html里中引用。（如果你的项目一开始使用的是antd的npm包，为了不改写你的很多require的写法，可以结合webpack的external解决这个问题）
```
externals:  {antd: 'antd'}
```
吐槽一下，希望antd项目组赶快支持位置修改的配置

**Comment by ystarlongzi** [comment]
@benjycui @afc163 

再暴露出两个属性 `position`、`space`分别控制位置和空隙？然后这个有必要考虑左上角和左下角弹出不？

**Comment by afc163** [comment]
@ystarlongzi 这样如何？

```js
notification.config({
  top: 'auto',
  bottom: 100,
  duration: 3,
});
```

**Comment by ystarlongzi** [comment]
@afc163 我可以这样理解嘛？
1. `top` 和 `bottom` 都支持
2. 如果没有 `top` 和 `bottom`，默认是 `defaultTop`
3. 如果存在 `top`，但无 `bottom`，那 `bottom` 默认是 `auto`
4. 如果无`top`，但存在 `bottom`，那 `top` 默认是 `auto`

**Comment by benjycui** [comment]
@ystarlongzi 还要考虑连续弹出多个 Notification 时的情况。

**Comment by ystarlongzi** [comment]
@benjycui 哦哦，对，是的。你是指会有下面的这种场景出现吧

```javascript
// 先右下角弹出一个通知
notification.config({
  bottom: 100,
  duration: 3,
});

// 然后又在右上角弹出一个通知
notification.config({
  duration: 3,
});
```

**Comment by benjycui** [comment]
还有这种，bottom 的属性要怎么理解：

```jsx
// 先右下角弹出一个通知
notification.config({
  bottom: 100,
  duration: 3,
});

// 再在右下角弹出一个通知
notification.config({
  bottom: 100,
  duration: 3,
});
```

**Comment by liu2080019** [comment]
已经支持bottom了吗？  不好意思，我那种改法确实不太友好

**Comment by benjycui** [comment]
@liu2080019 讨论中。。

**Comment by ystarlongzi** [comment]
@benjycui 
我的理解是：连续两个右下角的通知，和现在的连续在右上角的处理一样，也是追加到 `notificationInstance` 里。

但是，如果要实现既有右上角、又有右下角弹出通知，那 [/components/notification/index.tsx#L24-L36](https://github.com/ant-design/ant-design/blob/master/components/notification/index.tsx#L24-L36) 这里或许要缓存两种类型的 `notificationInstance`。

**Comment by liu2080019** [comment]
@ystarlongzi    又有右上角 又有右下角  多了之后会重叠住吧    需不需要考虑这种情况

**Comment by ystarlongzi** [comment]
@liu2080019 是的，有这种情况。。。😂😂

**Comment by afc163** [comment]
多一个 position 确实会简单一点。

**Comment by benjycui** [comment]
> 又有右上角 又有右下角 多了之后会重叠住吧 需不需要考虑这种情况

这种交给业务代码处理把，事实上一个系统里面没必要同时存在 top 和 bottom 两种 notification 吧。

**Comment by ystarlongzi** [comment]
@benjycui 赞成！仔细想下，一个系统确实也不应该同时存在则几种情况，要不用户也会晕的。一会右上角来个通知，一会右下角也来个通知，然后一会又是左上角、左下角的通知。

@afc163 @benjycui 要不在代码里控制下只允许出现一种弹出位置？

**Comment by afc163** [comment]
没必要写死，提供全局配置即可。

**Comment by ystarlongzi** [comment]
嗯嗯，好的

**Comment by liu2080019** [comment]
@afc163  坐等新版本哦
