### ISSUE TITLE
Slider 使用ConfigProvider  样式无法全面覆盖

### ISSUE THREAD

**Issue by mkRui** [ant-design/ant-design#45316]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v2pqms?file=/app.tsx&utm_medium=sandpack)

### Steps to reproduce

鼠标hover在滚动条上 

### What is expected?

鼠标hover在滚动条上 样式没有统一

### What is actually happening?

鼠标hover在滚动条上 样式统一

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.x |
| System | mac |
| Browser | chrome |

**Comment by mkRui** [comment]
![image](https://github.com/ant-design/ant-design/assets/27624475/c056d0c9-9ced-417e-8695-ddb0ee94aa25)

**Comment by Yuiai01** [comment]
看来是这个
<img width="503" alt="image" src="https://github.com/ant-design/ant-design/assets/112228030/bf13ca66-a57c-4bc2-8497-78daa2bdf7bd">

**Comment by afc163** [comment]
```
          Slider: {
            colorPrimary: '#f0a70a',
            algorithm: true, // 启用算法
          },
```

这样是不是就好了。

**Comment by mkRui** [comment]
这样是可以的。没什么问题了 谢谢
