### ISSUE TITLE
Uncaught TypeError: derivative4 is not a function

### ISSUE THREAD

**Issue by archvlad** [ant-design/ant-design#45311]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-df69wl)

### Steps to reproduce

1. Go to here https://ant.design/theme-editor
2. Choose Dark Mode in Color section
3. Press Config and copy code
4. Paste it in theme attribute of ConfigProvider

### What is expected?

Dark mode

### What is actually happening?

Uncaught TypeError: derivative4 is not a function

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | Windows |
| Browser | Edge |

**Comment by yoyo837** [comment]
How about this https://codesandbox.io/s/antd-reproduction-template-forked-jhnzmk?file=/index.js

**Comment by yoyo837** [comment]
It seems that the config generated by the  theme-editor is incorrect.

**Comment by archvlad** [comment]
> It seems that the config generated by the theme-editor is incorrect.

That's what I am talking about. Instead of `"dark"` should be `theme.darkAlgorithm` as said in documentation: https://ant.design/docs/react/customize-theme#use-prese

**Comment by MadCcc** [comment]
In Theme Editor, algorithms have a protocol: `dark` and `compact` will be automaticly converted to `theme.darkAlgorithm` and `theme.compactAlgorithm`, for dynamicly saving in localStorage.

But antd do not handle it, you need to replace it yourself when copy it into your code. 

Maybe it's better to leave a tip.
