### ISSUE TITLE
Option to have the Drawer "push" content instead of overlay

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#45318]
### What problem does this feature solve?

Right now, the drawer always overlays over the page.  There are use cases where you'd actually want to resize the content so you can work on both the primary screen and the drawer content at the same time.

### What does the proposed API look like?

Maybe adding a new prop: `overlay={false}` or just updating the current `push` prop to somehow target the content of the contain it's in.

```ts
<>
  <Card>
    Main Content
  </Card>
  <Drawer open={true} mask={false} push={{ distance: 520 }} width={520}>
          <div>Testing</div>
  </Drawer>
</>
```

**Comment by arvinxx** [comment]
yes, we need this too.

**Comment by MadCcc** [comment]
What you expected is just removing the mask or putting the whole Drawer into container and make it occupy width?

**Comment by ChuckJonas** [comment]
ya exactly.  I need the drawer to take space instead of "overlaying" on top of the card.

Not sure the Drawer component is really setup to accomplish this, but right now `antd` seems to lack any component that can make dynamic use of space horizontally (this component, resizable panes, collapse in the horizontal orientation, etc).

A simple use case would for this would be a Markdown Editor with the ability to open a "preview" drawer to the side.

**Comment by arvinxx** [comment]
@ChuckJonas here is a component you can use: https://pro-editor.antdigital.dev/components/draggable-panel

**Comment by ChuckJonas** [comment]
@arvinxx are there English docs for this library?  I've heard of the `@ant-design/pro-components`, but not the "@ant-design/pro-editor".

**Comment by MadCcc** [comment]
Going to merge this issue into https://github.com/ant-design/ant-design/issues/44525
