### ISSUE TITLE
能否支持下表格列拖动改变宽度的，通过属性配置就能有，或者全部支持，就更elementUI一样，

### ISSUE THREAD

**Issue by tanxiaojun12** [ant-design/ant-design#45313]
### What problem does this feature solve?

在使用过程中发现当body部分设置滚动的时候我设置的拖动线条会被盖住。因为header有overflow：hidden属性。

### What does the proposed API look like?

通过属性配置就能有

**Comment by afc163** [comment]
Duplicate of #32811
