### ISSUE TITLE
Tree 组件 使用 autoExpandParent 属性 配合 ref  设置 expandedKeys 时不生效

### ISSUE THREAD

**Issue by OnlyFlyer** [ant-design/ant-design#45323]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-babbage-cw8srw?file=/src/App.tsx)

### Steps to reproduce

Tree 的  autoExpandParent 设置为 true，使用 treeRef.current.setExpandedKeys(['1.2.1']); 方式不能够生效

### What is expected?

使用 treeRef.current.setExpandedKeys 设置 expandedKeys，对应的节点能够正常展开

### What is actually happening?

使用 treeRef.current.setExpandedKeys 设置 expandedKeys，对应的节点没有正常展开

| Environment | Info |
| --- | --- |
| antd | 4.22.5 |
| React | react: 16.13.1 |
| System | Mac Monterey v12.1 |
| Browser | Chrome arm64 117.0.5938.149 |

**Comment by afc163** [comment]
不应该使用文档中没有透出的 ref.xxx 内部方法来调用，请统一使用 `expandedKeys` 控制。
