### ISSUE TITLE
validateFields不能验证FormList以及FormList表单项

### ISSUE THREAD

**Issue by r593988344** [ant-design/ant-design#45320]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-lovelace-p8rjwm?file=/index.js)

### Steps to reproduce

点击VilidateAll按钮可以校验所有表单，点击ValidateCurrentItem校验指定form.list索引的表单组

### What is expected?

点击ValidateCurrentItem校验指定form.list索引的表单组

### What is actually happening?

校验不生效

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | 苹果系统 |
| Browser | chrome版本 117.0.5938.92（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/tender-banach-mnhcxh?file=/index.js

**Comment by r593988344** [comment]
我能单独校验Form.List中的其中一组表单吗
https://codesandbox.io/s/boring-wildflower-kw8nvg?file=/index.js

**Comment by r593988344** [comment]
> https://codesandbox.io/s/tender-banach-mnhcxh?file=/index.js

我能单独校验Form.List中的其中一组表单吗
https://codesandbox.io/s/boring-wildflower-kw8nvg?file=/index.js
