### ISSUE TITLE
Using Text component as Dropdown's item label doesn't inherit disabled styling

### ISSUE THREAD

**Issue by kongolml** [ant-design/ant-design#45336]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-10-0-forked-r892ng?file=/demo.tsx)

### Steps to reproduce

1. use Text component as Dropdown item label value
2. set this item to be disabled

### What is expected?

Disabled items should be grayed out no matter what is used in label property.

### What is actually happening?

Disabled item is disabled, cursor is disabled, but text color is black.

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.0.0 |
| System | Mac OS latest |
| Browser | Chrome latest |

**Comment by zombieJ** [comment]
Text component provides default color style of it. You can use inherit style to override it:

https://codesandbox.io/s/basic-antd-5-10-0-forked-73kqdp?file=/demo.tsx
