### ISSUE TITLE
Tooltip is not hiding when moving cursor to fast

### ISSUE THREAD

**Issue by philippechevieux** [ant-design/ant-design#45331]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-tooltip-not-hidding-when-moving-cursor-fast-dqyd9x?file=/index.js)

In case you can't reproduce here is a video of it : https://streamable.com/y2exwg

### Steps to reproduce

When clicking on the button and then moving the cursor fast then sometime the tooltip is not hiding (It's look like the event mouseLeave is not trigger)

### What is expected?

To hide the tooltip when the cursor is not on it anymore

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.x |
| System | MacOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Can not see the video and not get reproduce by the codesandbox.

**Comment by philippechevieux** [comment]
Here it is : https://streamable.com/zypjn4 (sorry streamable link are only available for 2 days)

**Comment by zombieJ** [comment]
You can upload with github comment directly. No need third part site : )

**Comment by philippechevieux** [comment]
Indeed here is the full video 😄 


https://github.com/ant-design/ant-design/assets/27333961/b4a4c62f-614c-416e-aa44-a83be7832017

**Comment by zombieJ** [comment]
I want to confirm that if dont dynamic change the icon, will it still have the bug?

**Comment by philippechevieux** [comment]
I forked the sandbox to have a static icon : https://codesandbox.io/s/antd-tooltip-not-hidding-when-moving-cursor-fast-forked-64nzgh?file=/index.js 

And in this case there is no bug anymore

**Comment by zombieJ** [comment]
Check the node find that its caused by React will not trigger `onMouseLeave` event when node quick flash. I wrap the icon with `pointEvents: none` also fix this:

https://codesandbox.io/s/antd-tooltip-not-hidding-when-moving-cursor-fast-forked-xls6x6?file=/index.js

**Comment by zombieJ** [comment]
Since the event is bubble by React, I'm afraid we can do nothing on the component level:

<img width="700" alt="截屏2023-10-17 15 12 37" src="https://github.com/ant-design/ant-design/assets/5378891/38046fa2-8b27-49cc-9781-97537ccf0ac7">
(Event not trigger)

**Comment by philippechevieux** [comment]
> Check the node find that its caused by React will not trigger `onMouseLeave` event when node quick flash. I wrap the icon with `pointEvents: none` also fix this:
> 
> https://codesandbox.io/s/antd-tooltip-not-hidding-when-moving-cursor-fast-forked-xls6x6?file=/index.js

Wrapping the icon is working thanks for your help @zombieJ
