### ISSUE TITLE
Destroy Inactive tab does not work when set at tab level

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#45338]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rlrpvv?file=/index.js)

### Steps to reproduce

- Create `Tabs`
- Add a few items with `destroyInactiveTabPane: true`
- Add a `useEffect(() => alert('onMount'), [])`
- switch back and forth between tabs several times

### What is expected?

If the component was destroyed when the tab is closed, the `useEffect` should fire every time the tab is opened.

### What is actually happening?

It only fires the first time the tab is opened 

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2 |
| System | any |
| Browser | chromium |

---
I tested with both the `items` prop and the children and got the same result.  Also tried adding `forceRender`, but it doesn't do anything either.

It does work if you set the `destroyInactiveTabPane` at the component level, but in my cases this would be highly undesired to destroy all the tabs!

**Comment by Yuiai01** [comment]
I looked at the source code, and the `destroyInactiveTabPane` set at the component level is applied to the tab level.

**Comment by ChuckJonas** [comment]
so... seems like a bug then?  

The [Tab Docs have no reference of the prop](https://ant.design/components/tabs#tabitemtype) on the pane, but [it's in the types](https://github.com/react-component/tabs/blob/415ff34b8121e3353a11d8f640062fd966488603/src/TabPanelList/TabPane.tsx#L20).

Seems like it was intended to be put in place, but wasn't
