### ISSUE TITLE
Tooltip is not working in Datepicker cells while using cellRender method

### ISSUE THREAD

**Issue by yasarui** [ant-design/ant-design#45339]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5wtm5c?file=/index.js)

### Steps to reproduce

1. Create a Datepicker component
2. Cutom render the datepicker cells using cellRender
3. Add a tooltip while retruning the date from the custom method
4. Hover over the date cells

### What is expected?

I should be seeing the tooltip text

### What is actually happening?

i am not able to see the tooltip text

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | Mac book pro |
| Browser | Chrome |

---
If i use defaultOpen like this <Tooltip defaultOpen={true} title="prompt text"> <span>{date.date()}</span> </Tooltip>, tooltip is showing for all the cells initially, which wont be real time usecase. when i re hover the cells again the tooltip is not showing

**Comment by zombieJ** [comment]
DatePicker cell has a `:before` element to cover the full cell size, you can patch this for event: https://codesandbox.io/s/antd-reproduction-template-forked-z5tj4n?file=/index.css
