### ISSUE TITLE
validateTrigger type definition

### ISSUE THREAD

**Issue by wallverb** [ant-design/ant-design#4533]
Doc definition for `validateTrigger` in `getFieldDecorator(id, options)` shows that acceptable type is `string`
Similarly `Form.d.ts` has defintion
```ts
        /** 校验子节点值的时机 */
        validateTrigger?: string;
```

Example at https://ant.design/components/form/ uses:
```ts
{getFieldDecorator(`names-${k}`, {
            validateTrigger: ['onChange', 'onBlur'],
...
```

Not sure which version is right, but if validateTrigger allows to provide array of strings then probably docs and `Form.d.ts` defintion should be updated to reflect:

```ts
  validateTrigger?: string | string[]
```

**Comment by afc163** [comment]
Could you give us a PR for this? :smiley:
