### ISSUE TITLE
所有的嵌套类使用的组件都出现了ts2322的报错

### ISSUE THREAD

**Issue by ReneeDress** [ant-design/ant-design#45332]
### Reproduction link

[https://github.com/ReneeDress/vite-electron/blob/4d7cbd944990c209a67c5b18baa97af0e5b0119c/packages/renderer_react/src/components/USBDeviceCard/index.tsx](https://github.com/ReneeDress/vite-electron/blob/4d7cbd944990c209a67c5b18baa97af0e5b0119c/packages/renderer_react/src/components/USBDeviceCard/index.tsx)

### Steps to reproduce

```
import { Card } from 'antd';

const { Meta } = Card;

const USBDeviceCard = () => {
  return (
    <Card
      hoverable
      style={{ width: 240 }}
      cover={
        <img
          alt="example"
          src="https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
        />
      }
    >
      <Meta
        title="Europe Street beat"
        description="www.instagram.com"
      />
    </Card>
  );
};

```

### What is expected?

没有任何报错

### What is actually happening?

报错
Type 'Element' is not assignable to type 'ReactNode'.ts(2322)
Card.d.ts(22, 5): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & CardProps & RefAttributes<HTMLDivElement>'

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | macOS 13.5.2 (22G91) |
| Browser | Electron |

---
怀疑是@types/react的问题 但是尝试了几个18的版本都没有用

**Comment by afc163** [comment]
我看最新的 main 分支上已经是好的了？

<img width="769" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/6de5a743-1cb4-4785-a9fe-49a08dff54bd">

**Comment by ReneeDress** [comment]
@afc163 感谢回答。我发现之前切换@types/react的版本其实没有生效，因为网络问题用的`cnpm`所以拉的全是同一个缓存`18.2.28`的版本，然后这个特定版本是会报错的。其它可以参考[这个issue](https://github.com/remix-run/remix/issues/7514)，好像是升级到18之后PropsWithChildren的内容被删除/更改导致反复出现这个问题。:P 头疼死，搞了好几天。
