### ISSUE TITLE
Auto-complete 和 内部的 input 元素都有 placeholder 时，会出现两个 placeholder

### ISSUE THREAD

**Issue by kovsu** [ant-design/ant-design#45355]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-shu-ru-zu-jian-antd-5-10-1-forked-ktykgs?file=/demo.tsx)

### Steps to reproduce

直接看重现链接

### What is expected?

不会出现两个 placeholder

### What is actually happening?

出现了两个 placeholder

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18 |
| System | macOS Sonoma 版本14.0 |
| Browser | Chrome 111.0.5563.111 |

**Comment by yoyo837** [comment]
链接的demo怎么超级卡

**Comment by kovsu** [comment]
啊哈，我截图给你吧

**Comment by kovsu** [comment]
![image](https://github.com/ant-design/ant-design/assets/82451257/0386cf2e-241e-4e9f-82dd-e6f14c027cc2)

**Comment by kovsu** [comment]
> > 链接的demo怎么超级卡
> 
> 我也是，输入几下就给我卡死了...

这样吗，我这没啥问题。😂

**Comment by yoyo837** [comment]
铁定还有其他问题

**Comment by yoyo837** [comment]
不是打开csb卡,是输入的时候卡

**Comment by yoyo837** [comment]
卡得飞起...

**Comment by kovsu** [comment]
是的，我再看看

**Comment by MadCcc** [comment]
csb 的 bug，console.log 事件对象会卡

**Comment by MadCcc** [comment]
去掉一个 placeholder 是不是就可以了？

**Comment by kovsu** [comment]
本地好像没什么问题

**Comment by yoyo837** [comment]
> csb 的 bug，console.log 事件对象会卡

长知识了

**Comment by MadCcc** [comment]
AutoComplete 本身是一个 Select，不会针对 children 有没有 placeholder 属性做特殊处理。建议自定义 children 的话控制一下 placeholder 到底是给哪个元素
