### ISSUE TITLE
Typography type="secondary"时，文字color对应token为colorTextTertiary而不是colorTextSecondary

### ISSUE THREAD

**Issue by Sheepeer** [ant-design/ant-design#45368]
### Reproduction link

[https://ant.design/components/typography](https://ant.design/components/typography)

### Steps to reproduce

1. 配置全局theme token：
```
  colorText: "rgba(0, 0, 0, 0.87)",
  colorTextSecondary: "rgba(0, 0, 0, 0.60)",
  colorTextTertiary: "rgba(0, 0, 0, 0.38)",
```
![image](https://github.com/ant-design/ant-design/assets/78125933/80cd486a-31cf-4dc9-8e02-48c8121bd87c)

2. 在页面写下 <Text type="secondary">AAA</Text>
![image](https://github.com/ant-design/ant-design/assets/78125933/bccb6e72-8106-4ca6-a1fa-7f2d7cd254c0)

### What is expected?

AAA的color为colorTextSecondary

### What is actually happening?

AAA的color为colorTextTertiary
![image](https://github.com/ant-design/ant-design/assets/78125933/8e7fc1c3-d313-4dd7-a147-a34d46bd375d)

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18.0.0 |
| System | win10 |
| Browser | chrome |

**Comment by MadCcc** [comment]
两个 secondary 涵义不同。Typo 的 `type` 不完全对应 token，没有这层约束

**Comment by Sheepeer** [comment]
> 两个 secondary 涵义不同。Typo 的 `type` 不完全对应 token，没有这层约束

那感觉type很有歧义哎；后续会不会考虑新增一个字段用来对应token？

**Comment by arvinxx** [comment]
> 那感觉type很有歧义哎；

+1

**Comment by hoosin** [comment]
> > 两个 secondary 涵义不同。Typo 的 `type` 不完全对应 token，没有这层约束
> 
> 那感觉type很有歧义哎；后续会不会考虑新增一个字段用来对应token？

+1
