### ISSUE TITLE
Autocomplete. The target is not set on the dropdown list item

### ISSUE THREAD

**Issue by goldpvlv** [ant-design/ant-design#45365]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-4-24-14-forked-s7skty)

### Steps to reproduce

1. Select an item from the dropdown list
2. Open the dropdown

### What is expected?

the selected item is in a gray frame

### What is actually happening?

the selected item doesn't mark

| Environment | Info |
| --- | --- |
| antd | 4.24.9 |
| React | 18.2.0 |
| System | Win10 |
| Browser | Chrome |

---
What's I doing wrong?

**Comment by zombieJ** [comment]
AutoComplete is a input component. So the value by you pass is `first` but option value is `268`. It will never match each other.
If you want to be the label not align with value, use Select + `labelInValue` to support customize input instead.

**Comment by goldpvlv** [comment]
@zombieJ
> AutoComplete is a input component. So the value by you pass is `first` but option value is `268`. It will never match each other. If you want to be the label not align with value, use Select + `labelInValue` to support customize input instead.

Thank for answer @zombieJ
I can't use the Select component for search. When I place the cursor in the input field, then I cannot change the current value and the cursor at the beginning of the line. Can I somehow make the property labelInValue for the Autocomplete?
