### ISSUE TITLE
为什么antd4.0 5.0对比3.0性能下降很多 

### ISSUE THREAD

**Issue by okjun** [ant-design/ant-design#45377]
### Reproduction link

[https://ant.design/components/tree-cn?locale=zh-CN](https://ant.design/components/tree-cn?locale=zh-CN)

### Steps to reproduce

打开https://ant.design/components/tree-cn?locale=zh-CN,使用react developer tools查看渲染次数

### What is expected?

和3.x一样

### What is actually happening?

4.x,5.x多次渲染

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | react 16.9 |
| System | windows |
| Browser | chrome |

---
 antd4.0 5.0对比3.0性能下降很多 ，官网的例子对比都明显卡了挺多的，用react developer tools是显可以看到多次渲染

**Comment by zombieJ** [comment]
给个具体的 benchmark 看看？~

**Comment by zombieJ** [comment]
> developer tools查看渲染次数

这个推测是和 v3 及以前版本一些实现没有走 React 生命周期有关，在 React 早期版本不走周期更新的确会减少渲染次数。但是随着 React Concurrent Suspence 更新，不走生命周期的实现会导致行为的异常。所以 v4 一个很重要的重构就是改成生命周期方法。

ref https://github.com/ant-design/ant-design/issues/26136

另外，还是需要你提供一下具体的 case 才能看看是不是有什么 bug 引入了哈~
