### ISSUE TITLE
Ability to "Stop Propagation" on Dropdown.Button "trigger"

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#45372]
### What problem does this feature solve?

If you embed a dropdown button inside a `Collapse.Panel extra`, there is current no way to prevent the propagation of the trigger from Collapsing/Expanding the parent:

https://codesandbox.io/s/antd-reproduction-template-forked-hkrsth?file=/index.js

As far as I can tell, the only current work around is to take "control" of the trigger, which adds overhead for a common use-case.

### What does the proposed API look like?

Maybe a new property like `stopTriggerPropogation`:

```ts
<Dropdown.Button
      onClick={(e) => {
        e.stopPropagation();
        console.log("clicked main");
      }}
      menu={{ items: menu }}
      trigger={["click"]}
      stopTriggerPropogation
>
      Click
</Dropdown.Button>
```

**Comment by MadCcc** [comment]
Use `buttonsRender`.
https://codesandbox.io/s/antd-reproduction-template-forked-973ks9?file=/index.js
