### ISSUE TITLE
Wrong margin in RTL notification

### ISSUE THREAD

**Issue by shadoworion** [ant-design/ant-design#45384]
### Reproduction link

[https://ant.design/components/notification?direction=rtl](https://ant.design/components/notification?direction=rtl)

### Steps to reproduce

Show notification

### What is expected?

Margin from the edge of the screen

### What is actually happening?

No margin from the edge of the screen

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18.2.0 |
| System | MacOS 14.0 |
| Browser | Edge 118.0.2088.46 |

**Comment by MadCcc** [comment]
Shouldn't use `inset` in style
