### ISSUE TITLE
How can I make thei table soreter tooltip not clikcable

### ISSUE THREAD

**Issue by AnanthaKrishnanak** [ant-design/ant-design#45392]
### What problem does this feature solve?

Tooltip in the columns should be only informative and not fulfill the action function.

### What does the proposed API look like?

Should be able to control table sort tooltip actions

**Comment by afc163** [comment]
https://codesandbox.io/s/shai-xuan-he-pai-xu-antd-5-10-1-forked-sq8pjy?file=/demo.tsx

**Comment by AnanthaKrishnanak** [comment]
Now you're showing the title as "Click to sort", how the user are going to know whether it is ascending sort or descending sort?

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/45403 the fix about it.

**Comment by AnanthaKrishnanak** [comment]
Can you provide a sample code I couldn't get it.

   showSorterTooltip: {
        overlayStyle: {
          pointerEvents: "none",
        },
        
        title:"click to sort" // I need to show whether it is ascending , descending or cancel sort text here
      },

**Comment by afc163** [comment]
You can remove `title` safely to see the original title in next patch of antd (5.10.2), which is fixed in https://github.com/ant-design/ant-design/pull/45403
