### ISSUE TITLE
给 Tooltip 组件增加 disabled API，使得 Popover 和 Tooltip 组件都可以阻止点击子元素时弹出悬浮框

### ISSUE THREAD

**Issue by cloudmoonocus** [ant-design/ant-design#45393]
### What problem does this feature solve?

在一个表单增加属性，在没有可以增加的属性的时候禁用了内部的子元素 Button，但是这时候点击摁钮仍然会触发 Tooltip 的事件。在我看见以前有个 Popconfim 的组件 https://github.com/ant-design/ant-design/pull/16985/ 实现了这个属性，我想给 Tooltip 也实现。

Adding attributes to a form disables the internal child element Button when there are no attributes to add, but clicking the button still triggers the Tooltip event. Before I saw it, there was a PopConfim component that implemented this property, and I wanted to implement it for Tooltip as well.

### What does the proposed API look like?

disabled: 阻止点击子元素时弹出悬浮框

**Comment by zombieJ** [comment]
受控即可：

```tsx
<Tooltip open={false} />
```
