### ISSUE TITLE
如何在纯js中调用message？

### ISSUE THREAD

**Issue by cybermage6969** [ant-design/ant-design#45397]
### What problem does this feature solve?

目前官方文档中的message的调用都需要在react组件中，比如App内，如果要在类似于request.js的文件中直接调用message.error('xxx')该如何实现？

例：

get('https://xxxx').catch(err => {
   message.error('xxx')
})

### What does the proposed API look like?

message.error() / message.warning() ...

**Comment by crazyair** [comment]
https://ant.design/components/app-cn#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF

**Comment by Wxh16144** [comment]
- https://github.com/ant-design/ant-design/discussions/41855
- https://ant.design/docs/blog/why-not-static-cn
- https://ant.design/components/app-cn#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF
