### ISSUE TITLE
InputNumber在safari上编译出来的dom不一样

### ISSUE THREAD

**Issue by Vantown** [ant-design/ant-design#45409]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sdhj3w)

### Steps to reproduce

没有找到特定版本的antd的库，在5.7.0上是不对的，禁用的输入框的内容显示成了白色

### What is expected?

windows上和在mac上的chrome上都是黑色

### What is actually happening?

白色文字

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | macOS13.3.1 |
| Browser | safari |

---
safari版本是16.4 (18615.1.26.110.1)

**Comment by Vantown** [comment]
<img width="1665" alt="lQLPJx_qv6htuBTNBoTNDQKwCXa1LfXUuHwFIOEhqgBRAA_3330_1668" src="https://github.com/ant-design/ant-design/assets/29136022/85f86a62-54aa-419a-8ed1-bff97859be02">
<img width="1537" alt="lQLPJwPHjQl6HpTNBpTNDAKw5hZQrXrsFV4FIOFBRoBRAA_3074_1684" src="https://github.com/ant-design/ant-design/assets/29136022/71cd3fcb-f4a8-46a8-91b9-16e7c47862b8">
这个是截图

**Comment by MadCcc** [comment]
看截图 dom 没区别

**Comment by Vantown** [comment]
> 看截图 dom 没区别

第一张图的input里面那不还有一层，input带着展开箭头那不
