### ISSUE TITLE
 antd v5开启<StyleProvider hashPriority="high">样式兼容，message组件的样式未移除 `:where` 选择器封装

### ISSUE THREAD

**Issue by yindegang** [ant-design/ant-design#45404]
### Reproduction link

[https://ant-design.antgroup.com/docs/react/compatible-style-cn](https://ant-design.antgroup.com/docs/react/compatible-style-cn)

### Steps to reproduce

const px2rem = px2remTransformer({
  rootValue: document.documentElement.clientWidth * 100 / 1366, // 32px = 1rem; @default 16
});
export function rootContainer(container) {   
  return React.createElement(StyleProvider, {
    transformers: [px2rem]
    , hashPriority: "high"
  }, container);
}

### What is expected?

所有组件的样式移除`:where` 选择器封装

### What is actually happening?

message组件的样式仍然使用了`:where`，导致message无法出现在屏幕中

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | Firefox 118.0.2(64位) |

**Comment by afc163** [comment]
https://ant-design.antgroup.com/docs/react/compatible-style-cn 这个文档里要加 FAQ 了。

**Comment by yindegang** [comment]
> https://ant-design.antgroup.com/docs/react/compatible-style-cn 文档里得解释一下这个问题，FAQ 文档里也要补充一下。

什么时候更新文档，现在有解决方案吗

**Comment by zombieJ** [comment]
更新文档说明静态方法不能消费 context，用 hooks：

<img width="420" alt="截屏2023-10-18 17 32 00" src="https://github.com/ant-design/ant-design/assets/5378891/d637649c-319d-419e-8034-6398998c50bf">

**Comment by zombieJ** [comment]
Message 的 FAQ 里已经写过了：https://ant-design.antgroup.com/components/message-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-message-%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-contextredux-%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-configprovider-%E7%9A%84-localeprefixclstheme-%E7%AD%89%E9%85%8D%E7%BD%AE
