### ISSUE TITLE
Table 不能支持自定义Empty 空状态吗？

### ISSUE THREAD

**Issue by 510279293** [ant-design/ant-design#45402]
### What problem does this feature solve?

想要自定义支持 Table Empty 空状态

### What does the proposed API look like?

empty: () => void

**Comment by Wxh16144** [comment]
CP 组件支持自定义的

**Comment by zombieJ** [comment]
<img width="759" alt="截屏2023-10-18 15 55 53" src="https://github.com/ant-design/ant-design/assets/5378891/d0a819aa-78d8-42b2-9d6b-0964813d1116">

https://codesandbox.io/s/ji-ben-yong-fa-antd-5-10-0-forked-hgv7r7?file=/demo.tsx

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues?q=is%3Aissue+label%3A%E2%9D%93FAQ+is%3Aclosed+table+empty+set
