### ISSUE TITLE
Input.Search style 属性问题

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#4540]
版本 antd@2.6.1

现在 ```<Search style={{ width: 200 }} />``` 任然占了一整行, 样式加错地方了吧...是 bug 吧

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/37541e3bfe9a4702a4cce979544f95cb0f78655a

**Comment by xutou12** [comment]
ok了, 我的问题描述少了代码块, 代码没显示出来, 你居然明白了, 厉害了我的哥

**Comment by afc163** [comment]
昨天刚改的，有印象~

**Comment by xutou12** [comment]
@afc163 #4334 说是样式与 Input 一致, 我有不同意见,  因为 Search 使用场景跟 Input 不完全一样, 见的比较多的经常是跟 Select 结合使用过滤数据, 样式行为应该跟 Select 一致吧

**Comment by afc163** [comment]
Search 其实就是 Input 多个图标，其他都一样。

**Comment by xutou12** [comment]
我把 Search 和 Select 放一行, 加个 ```{ marginRight: 8px }``` 就有点悲剧了, 图标错位

**Comment by afc163** [comment]
marginRight 确实还有问题，我再看下。

**Comment by afc163** [comment]
这种情况要把 style 加到 wrapper 上。

**Comment by xutou12** [comment]
恩确实这样可以搞定

**Comment by afc163** [comment]
差不多把二楼的提交都回滚了。。。

**Comment by xutou12** [comment]
哈哈, 好吧
