### ISSUE TITLE
Tabs 当鼠标悬停的时候显示关闭按钮

### ISSUE THREAD

**Issue by dongshuai777** [ant-design/ant-design#45415]
### What problem does this feature solve?

当Tabs与路由联动的时候，希望看起来整齐。

### What does the proposed API look like?

只有在鼠标进入指定Tab的时候才显示关闭按钮。

**Comment by dongshuai777** [comment]
> css 处理一下？hover 添加 opacity
这样处理之后右侧会有一块空白
![image](https://github.com/ant-design/ant-design/assets/28584017/2619901c-da19-49b1-8ece-44263f7beb7e)

现在可以自定义标签头吗？

**Comment by zombieJ** [comment]
再加个 max-width 0 加上动画即可

**Comment by dongshuai777** [comment]
![image](https://github.com/ant-design/ant-design/assets/28584017/12de1201-7223-4f75-95bd-803c0229e308)
完美解决
非常感谢
