### ISSUE TITLE
日期组件如何全局设置format为DD/MM/YYYY？

### ISSUE THREAD

**Issue by liubin595338764** [ant-design/ant-design#45416]
### What problem does this feature solve?

日期组件如何全局设置format为DD/MM/YYYY？

### What does the proposed API look like?

期望<ConfigProvider >上可以配置RangePicker，DatePicker的默认的format格式

**Comment by Wxh16144** [comment]
CP 组件的 locale 字段可以统一配置

**Comment by afc163** [comment]
你需要 `moment.locale('xx')`。

**Comment by liubin595338764** [comment]
> 你需要 `moment.locale('xx')`。

@afc163 大佬，没明白，`moment.locale('xx')`是可以配置吗，没找到他可以配置全局格式的地方，我是想把

现在的默认格式：YYYY-MM-DD
<img width="328" alt="image" src="https://github.com/ant-design/ant-design/assets/5274428/69d8917c-70ab-4276-80d6-3853e8aeac74">


期望可以全局设置成：DD/MM/YYYY
<img width="480" alt="image" src="https://github.com/ant-design/ant-design/assets/5274428/a763ab05-cc67-4c70-83be-5aa2a6e1a3c9">

**Comment by Wxh16144** [comment]
我认为 @afc163 的回答是错误的，正如我前面说的，应该通过 CP 的 locale 去统一修改，但是 #42119 反馈目前 CP 修改是有 bug 的，我追溯了一下原因，错误是在 #20023 引入的，尽管现在单元测试用例还存在在最新代码中， 但是用例是错的。

最新的测试用例：https://github.com/ant-design/ant-design/blob/49ef16b5ff1201ba64d213e53e89928b741e05b0/components/date-picker/__tests__/other.test.tsx#L17-L45

错误引入地方：https://github.com/ant-design/ant-design/pull/20023/files#diff-f33147a574a8e8a0d4a378156aa71ae0e6720e5f384715168600a340e32082d1

解决方案要么等 antd 这边修复，要么自己二次开发一下

**Comment by zombieJ** [comment]
类似的需求 #23902

**Comment by Wxh16144** [comment]
我这两天修复一下这个问题~

**Comment by liubin595338764** [comment]
> 我这两天修复一下这个问题~

修复后可以也更新在V4的版本吗？

**Comment by Wxh16144** [comment]
> > 我这两天修复一下这个问题~
> 
> 修复后可以也更新在V4的版本吗？

当然，4.x 有 bug 还是会继续维护的

**Comment by linhf123** [comment]
应该是下面这段逻辑丢失导致的
https://github.com/ant-design/ant-design/blob/50b82ca5095966e7c9a8a1bf04e102c46b759f26/components/date-picker/wrapPicker.tsx#L26-L31

https://github.com/ant-design/ant-design/blob/50b82ca5095966e7c9a8a1bf04e102c46b759f26/components/date-picker/wrapPicker.tsx#L149-L156

**Comment by Wxh16144** [comment]
😢 这个问题看起来已经过时了，v5 重构了... (v4 已经不在维护了），[更多回复](https://github.com/ant-design/ant-design/issues/23902#issuecomment-1953622901)
