### ISSUE TITLE
How I can change Button normal href to Next <Link> instead of <a>

### ISSUE THREAD

**Issue by UnkAtreus** [ant-design/ant-design#45419]
### Reproduction link

[https://www.test.com](https://www.test.com)

### Steps to reproduce

-

### What is expected?

Button have own Link component I dont want to warp all of button component

### What is actually happening?

Right now Nextjs13 push function dont have a event on top progress bar so when I click button it must have an event on top progress bar before redirect and I try to used href pros but when I click on button it refreching whole page.

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | react:18.2.0 |
| System | Window |
| Browser | Google Chrome browser  |

**Comment by MadCcc** [comment]
Use `passHref`
