### ISSUE TITLE
[ImageViewer/图片预览] 希望增加这个组件！

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#45429]
### What problem does this feature solve?

就像“飞书”网页版登录，输入手机号后，下一步就是“填写验证码”。
![image](https://user-images.githubusercontent.com/3413930/170844682-24e9d1e8-de0a-41e7-8684-a2c2c4719eb9.png)
### 优点
- 风格统一，美观
- 第三方可能会存在性能问题
- 可能无法和TDesign中的api高度相似，降低学习成本
- 无法和Form表单一起使用
- 功能不够强大
- 第三方可能无法做到及时的维护和更新

## 希望的API
|参数名|描述|类型|默认值|
|---|---|---|---|
|count/length|输入框数量|`number`|`6`|
|group|多少个输入框为一组，<=1，表示没有分组|`number`|`3`|
|seg|分隔符，当group有效，才起作用，表示分组之间的间隔|`'ReactNode' \| 'string'`|`-（中横线）`|
|modify|内容格式是否可修改意思是说，比如：当你输入到第4个（共6个）输入框，鼠标点击前面的输入框可以直接进修改此值；<br/><br/>如果为false，则就像“飞书”似的，直接聚焦应当输入内容的输入框。|`boolean`|`-`|
|action|可以通过`箭头左右`控制光标在输入框中来回切换；<br/><br/>`鼠标滚轮`也可以控制光标；<br/><br/>`鼠标滚轮`也可以控制光标；<br/><br/>控制方式也可提炼出一个api，是否可以鼠标滚轮控制等；<br/><br/>鼠标滚轮是否是反向操作，比如前滚往后，后滚往前 切换|`string[]`|具体有哪些字符串，我不知道怎么写了，总之就是描述中的各种操作方式，在数组里表示开启那些操作方式。|
|size|输入框的尺寸|`'mini' \| 'small' \| 'default' \| 'large'`|`default`|
|disabled|是否禁用|`boolean`|`-`|
|readOnly|是否只读|`boolean`|`-`|
|placeholder|提示文字|`string`|`-`|
|error|是否是错误状态|`boolean`|`-`|
|uppercase|强制输入内容大写|`boolean`|`true`|
|addBefore|输入框前添加元素|`ReactNode`|`-`|
|addAfter|输入框后添加元素|`ReactNode`|`-`|
|prefix|添加前缀文字或者图标|`ReactNode`|`-`|
|suffix|添加后缀文字或者图标|`ReactNode`|`-`|
|allowClear|允许一键清空所有输入框|`boolean`|`-`|
|onChange|输入时的回调|`(value: string, e) => void`|`-`|
|onClear|点击清除按钮的回调|`() => void`|`-`|
|style|节点样式|`CSSProperties`|`-`|
|className|节点类名|`string \| string[]`|`-`|
|format|内容格式，全数字、字母、任意字符、正则表达式|`'number'\|'letter'\|'all'\|'Regex'`|'all'|
|value|值|与format一致|`-`|
|direction|方向，default表示：比如阿拉伯语是从右往左，就跟着从左往右输入）|`'ltr'\|'rtl'\|'default'`|`default`|

## 同时还希望支持和form表单一起使用
- 内容验证之类的，就像input似的

> 其他同类产品issues
https://github.com/Tencent/tdesign-react/issues/2314
https://github.com/arco-design/arco-design/issues/2272

**Comment by Wxh16144** [comment]
可以参考 https://github.com/lobehub/lobe-chat/blob/24f3dd7ba82c581a654bc2a73397a0c0a0aac9b9/src/app/chat/features/Conversation/ChatList/OTPInput.tsx 自行封装一个满足业务先？

新组件通常会有一个讨论的 RFC，可以关注一下 core member  的动态。

**Comment by zystudios** [comment]
这玩意自己写一个都用不了一天

**Comment by zombieJ** [comment]
Merge into #23201

**Comment by kwooshung** [comment]
> 成为一个组件一定是有代表意义的，适用于大部分场景的，且能满足多数业务需求的，有一定通用性和复杂性的
> 
> 用几个Input加flex布局，一天不到就可以做出来这种效果，建议自己完成，不仅能够熟悉React相关知识，做出来如果效果完美，可以自己开源，也是自己对开源的贡献，何乐而不为？

你说的很对，我双手赞成！
我也只是给官方提一下，如果官方打算做，我就没必要做那么完善了，只需要项目目前的功能就好了。
如果官方没有打算做，就自己做一个比较完善的，开源。
