### ISSUE TITLE
[Watermark/水印] 防删除篡改，确实解决了部分防篡改的问题，但有点形同虚设的感觉。

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#45427]
### What problem does this feature solve?

只需要通过调试工具或js，增加一个style，里面只需要这么写就能隐藏，我知道这个实现起来有点难，我不知道是不是我没有想到更好的办法。

我只是随便增加了一个外部的方式就可以实现隐藏。

![image](https://github.com/ant-design/ant-design/assets/3413930/94e05bd9-be0a-4e57-8cc9-e9324c87db1c)

更极端点儿的方式，使用循环什么的一次一次隐藏。

只在水印视觉元素.xxx > div:last-child上做各种属性的防删除、防修改意义就不大了。

如果其他的防护不做加强，这水印，在技术人手里就形同摆设。虽然我们不可能把水印防护做到滴水不漏，但是我觉的，尽可能防护还是很重要的。无论是合同，会员才能去除水印的功能之类的，这些水印就像摆设了。

大概这几种隐藏方式，除非用户自己针对性的对chrome等开源浏览器二次开发，这种在我的认知中无法做到防护，但是我说的这几种方式，还是可以做到的，这些无外乎就这常见的几种方式：

1、css控制父级或相邻元素，如：dispaly隐藏、高度为0，visibility:不可见、透明度为0、margin/padding/定位/等撑出屏幕；
2、频繁使用js隐藏某些元素，死循环调用之类的，重复设置相关css属性
3、二次开发浏览器，这个对于隐藏水印的用户来说，操作成本高，所以可以不用考虑这个功能的处理。

其实，就在刚刚我想到了一个终极思路，概念在我脑子还是个雏形：
需要考虑的一些东西很多啦，但是却避免了上述的麻烦了，同时增加了新的麻烦。思路简单，但是代码估计很复杂；大概思路就是：
水印和内容都是在canvas中，也按照样式内容生成，就是说和html表现的是一模一样的视觉效果（就光这一个，代码估计就很复杂），一个是样式的问题，一个是窗口缩放的问题（特别是缩放后文字排版的问题）

如果考虑canvas的方式实现，可以考虑加上一个类似static的属性，就是静态的。具体意思就是，如果用户内容不变，就是内容不变的情况下，可能免去很多复杂的计算，具体我也不太好描述，说到这里脑子有点乱，想到了很多，真正在这里复述的时候，有点讲不出来了。

大概就是这样；

### What does the proposed API look like?

这个功能增强，应该没有什么API了

> 其他同类产品的issues
https://github.com/Tencent/tdesign-react/issues/2559
https://github.com/arco-design/arco-design/issues/2263

**Comment by carolin913** [comment]
感谢@kwooshung的建议，其实单纯的在前端页面上加水印总是可以通过一些骚操作来跳过的，所谓防外行不防内行，想在前端浏览器页面做更周到的防护措施确实有些成本过高了，建议对安全防护性要求较高的场景可以考虑暗水印，或者如果资源为某个用户独有也可以考虑后端服务器加水印来标示资源的归属人

**Comment by zombieJ** [comment]
嗯，水印和内容分离的确是没有特别好的方式去做完全的防篡改。但是合并内容到 Canvas 对于交互内容就不行了。有兴趣欢迎来 PR 哈~

**Comment by kwooshung** [comment]
> 嗯，水印和内容分离的确是没有特别好的方式去做完全的防篡改。但是合并内容到 Canvas 对于交互内容就不行了。有兴趣欢迎来 PR 哈~

我觉得也是，目前做到这个程度，也是最大限度了限制了，其他的感觉确实比较麻烦。

**Comment by kwooshung** [comment]
> 嗯，水印和内容分离的确是没有特别好的方式去做完全的防篡改。但是合并内容到 Canvas 对于交互内容就不行了。有兴趣欢迎来 PR 哈~

对了顺便问下官方antd群，钉钉群之类的，我好像没找到，有没有呢？

**Comment by zystudios** [comment]
前端本来就没有办法做到100%的安全，所有信息只要是在浏览器里展示，都有办法修改，获取，哪怕你用图片，canvas画出来，OCR也很方便，加太多水印反而影响阅读体验，所以重点不是如何在前端防止篡改，而是做好信息安全管理，水印这种也是防止小白随便截图外发方便追溯而已
