### ISSUE TITLE
[dndxxx/拖放组件] 功能需求，希望增加这个组件！先别略过，点开考虑看看？

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#45434]
### What problem does this feature solve?

这个组件解决拖拽功能需求；组件名字没有想好，估计可以dnd什么的命名。

社区中虽然有很多优秀的拖放组件，如下所示，他们用起来功能虽然很强大，但是都很繁琐复杂，学习成本较高。
https://github.com/clauderic/dnd-kit
https://github.com/atlassian/react-beautiful-dnd/
https://github.com/react-dnd/react-dnd

我总觉得有更好的实现，甚至只需要告诉被拖拽的组件可以拖拽到那些区域，哪些区域不能拖拽。
在使用的时候，就感觉设置一个区域，打上可接受的标签tag数组；被拖拽的元素的tag；只要区域支持这个tag，他就能拖进来。

我希望功能丰富，用起来简单方便，学习成本低。阿里蚂蚁团队的工程师也许应该会有比我这更好的思路方案，实现起来对阿里蚂蚁团队来讲，应该是小菜一碟。

### What does the proposed API look like?

由于我只是提出了想法，而这个功能的API根据设计不同，不太好确定。

> 同类产品的issues
https://github.com/Tencent/tdesign-react/issues/2319
https://github.com/arco-design/arco-design/issues/2264

**Comment by so1ve** [comment]
差不多得了 自己封装一下能要你多少时间 两天在三个项目提了29个功能请求你怎么不找个傻逼免费帮你写项目 GitHub都用不明白起这种标题你是当贴吧用吗

**Comment by zombieJ** [comment]
感谢反馈，拖拽组件社区的已经相当成熟了。antd 侧应该不会提供这个能力。如果有需求，可以自己对现有的组件库进行封装哈~

**Comment by kwooshung** [comment]
> 差不多得了 自己封装一下能要你多少时间 两天在三个项目提了29个功能请求你怎么不找个傻逼免费帮你写项目 GitHub都用不明白起这种标题你是当贴吧用吗

只是提一下，又不是要求，何况我自己有现成了，确实是封装好的。我应该没得罪你对吧。虽然提交了29个，但是我是做完了自己的项目，把积累下来的问题一股脑发上来了。没错对吧。

谢谢你的谩骂。
