### ISSUE TITLE
[TopProcess/顶部进度条] 希望增加这个组件，社区中的都不是特别可心。

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#45431]
### What problem does this feature solve?

具体我自己都没想好，但是我总感觉应该有个这样的组件或包装器之类的东西。社区中虽然有 nprogress，总感觉这个设计的有些简陋，虽然可以自定义。

按照尽可能的模拟进度效果，社区中现在大部分是：进度到某个进度，比如80%，然后就卡主不动了，等待ajax或路由加载完毕，直接到100%；体验感很差！

我认为，这种不太好，比如next.js什么的路由级别页面跳转，首先进度到60%，跳转中（或异步获取中）从60%的进度但是肉眼看得出来的速度，进度到80/90%，这个时候数据如果还没加载出来，在这里再卡主，直到加载完成，也是平滑快速进度到100%。我感觉更好这种方式更好；

### What does the proposed API look like?
api要有进度回调比如：`onBefore/onStart`、`onChange(p:number)`、`onComplated/onEnd`；可以设置上述进度状态中进度，比如到多少卡主不动，慢慢的等待进度从多少到多少。每个阶段中的速度是多少。我认为TD团队考虑的很定比我完善。
最好还可以设置对应状态的className，比如：开始，等待（等待进度），完成，错误

对了最好支持next.js路由什么的。

> 同类产品的issues
https://github.com/Tencent/tdesign-react/issues/2564
https://github.com/arco-design/arco-design/issues/2269

**Comment by MadCcc** [comment]
nprogress 足够简单，并且可以搭配路由使用，感觉没有封装成 react 组件的必要。
