### ISSUE TITLE
[ColorPicker/颜色选择器] 功能/体验性 增强！

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#45437]
### What problem does this feature solve?

功能增强，比如滑块按钮变大一些，甚至可以“破格”出现，不一定非得在滑块条内部。

### What does the proposed API look like?

这个没有API，就是体验性增强：
另外功能性增强我不知道这个有没有可借鉴之处：
https://tdesign.tencent.com/react/components/color-picker

**Comment by zombieJ** [comment]
可以参考一下这篇博客做拓展哈：
https://ant-design.antgroup.com/docs/blog/config-provider-style-cn

**Comment by kwooshung** [comment]
> 可以参考一下这篇博客做拓展哈： https://ant-design.antgroup.com/docs/blog/config-provider-style-cn

多谢！
