### ISSUE TITLE
<DirectoryTree> 双击展开时，会触发两次节点的onselect事件，DirectoryTree和Tree的onselect事件不一致

### ISSUE THREAD

**Issue by xianyun279** [ant-design/ant-design#45439]
### Reproduction link

[https://codepen.io/z09876/pen/abXoWmL?editors=0011](https://codepen.io/z09876/pen/abXoWmL?editors=0011)

### Steps to reproduce

 <DirectoryTree> 添加expandAction="doubleClick" 单选模式

### What is expected?

双击展开节点时 不触发onSelect, 单击时触发，连续单击时，onSelect参数为交替的选中不选中

### What is actually happening?

双击展开是onSelect执行两次，onSelect的参数是当前点击的节点信息跟Tree的onSelect不一致（Tree中onSelect是选中/不选中）

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18 |
| System | win11 |
| Browser | google 118 |

**Comment by xianyun279** [comment]
expandAction="doubleClick"直接添加到<Tree>上也是生效的， 是否建议这样写 ？

**Comment by MadCcc** [comment]
doubleclickc 一定会触发 click 事件，这个不好处理
