### ISSUE TITLE
[RichEditor/富文本编辑器] 我知道这是天坑，也知道社区中有很多优秀的开源的组件，但还是希望大家看下这个需求，而且功能要求相对简单的多。

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#45432]
### What problem does this feature solve?

重要的事情说三遍！我知道富文本编辑器是这是天坑；我知道富文本编辑器是这是天坑；我知道富文本编辑器是这是天坑；

TDesign只需要实现富文本最最最最基本的功能就行，比如选区，浏览器兼容，插入行内节点（加粗什么的都不用实现，开发者自己去做，Ant Design只需要有对应的api就好），插入块级节点（也是和行内节点一样）。

富文本编辑器，社区中有很多优秀的组件，我相信大家都找到过不少，我最近就因为富文本，找了好多第三方开源的富文本编辑器，也看了好多资料；

tiptap：很优秀，好扩展，问题也不少（就不一一列举了）
remirror：同样很优秀，缺点也不少（同样不一一列举了）
slate.js和prosemirror：非常优秀，但是学习曲线略高。
draft.js：Facebook现在已不维护，推荐使用 lexical
lexical：虽然功能很强大很优秀，bug的确也不少，还是略显庞大。
以上部分组件，都不太好实现全选，块级没法增加选择的样式，比如图片无法在视觉上直接显示ctrl a的选中，

当然还有很多优秀的组件或框架，但是他们都有的问题是：

要么不可扩展
要么扩展费劲
要么好扩展，但文档太简陋
要么功能不少，内置了很多功能，略显臃肿
英文文档对于我来讲，虽然阅读起来不费劲。如果有自己的编辑器，而且是母语的中文文档，要比英文文档来的轻松得多
我目前用的是 lexical，和 arco design 融为一体还是需要点儿时间的。

### What does the proposed API look like?

api，我不知道官方具体怎么实现，因为这个组件复杂点儿，所以我就说说期望的组件有啥吧，功能真的很少，但是兼容性方面确实很麻烦，以下是我能想到的功能：
1. 从外观上来讲，就像个textarea一样，
2. 可以有API插入块级别元素和文本格式，具体像（加粗、斜体……）这些不用实现；
    - 开发者只需要定义命令，比如：bold
    - 执行命令：bold
    - 编辑器知道：用什么渲染，比如实现bold的html，react组件/vue组件
    - 开发者可以通过api判断光标位置或选区的内容是什么
3. 只需要实现一个段落，当然这个段落也可以开发者使用自己的组件或者Typography.Paragraph来替代。
4. 工具栏，不用实现，交给开发者
5. 可以存在placholder的定义，比如开发者插入段落的时候是一种提示，插入标题的时候是一种提示，只需要提供api，内部的逻辑开发者自己写。
6. 浮动工具栏，就是那种选中文字，在上方出现工具栏的组件，也不用实现具体内容，只需要有个类似的节点，让开发者传入即可。
7. 块级可以选中，开发者传入样式什么的就行
8. 有选择选区相关api
9. api一定要有插入换行
10. 可以给编辑器定义高度，但是不给高度，就是换行自动增高。
11. 拖拽排序段落、块级、行内的任意文本
12. 可导出html/json，一定要支持json，这样数据保存还有读取，甚至文章内容预览的时候，可以很灵活运用数据。

> 同类产品的issues
https://github.com/Tencent/tdesign-react/issues/2563
https://github.com/arco-design/arco-design/issues/2270

官方不是说了
![image](https://github.com/ant-design/ant-design/assets/3413930/5ac60f78-5c75-4e50-9397-ff9192a647ba)

# 你们呐，别喷了，喷的越多，只会让这个事儿越来越冒尖，一个社区，大家和平相处不好么？提出一些技术观点，不好么？非得喷么？还是说真的吐不出什么东西，才喷？这样你们和网上的那种喷子有啥区别呢？我只是希望，很多这种零碎的小东西，在antd 中，开箱即用，不好么？我是伸手党么？为什么喷呢？支不支持，均说出相应的观点不好么？为何非得这样刻薄呢？我犯天条了，这样恶意中伤？我就算有错，错不至死吧？

感谢 @4xii 唯一一个提出的正常建议。

**Comment by zhaogongchengsi** [comment]
***api，我不知道官方具体怎么实现，因为这个组件复杂点儿，所以我就说说期望的组件有啥吧，功能真的很少，但是兼容性方面确实很麻烦，以下是我能想到的功能***
你还真是技术不咋地，就会叭叭叭

**Comment by songrufeng666** [comment]
你还真是技术不咋地，就会叭叭叭，直接让作者给你写个项目不就完事了吗

**Comment by kwooshung** [comment]
> 你还真是技术不咋地，就会叭叭叭，直接让作者给你写个项目不就完事了吗

> _**api，我不知道官方具体怎么实现，因为这个组件复杂点儿，所以我就说说期望的组件有啥吧，功能真的很少，但是兼容性方面确实很麻烦，以下是我能想到的功能**_ 你还真是技术不咋地，就会叭叭叭

提个issues怎么了？社区怎么这个样？技术社区有你这种败类，真是丰富多彩，什么叫就会叭叭叭？凭这个就瞎胡说是不是，我11年前就一个java足够19岁就先后进入百度和腾讯，怎么了？
**我特么需要你的认可？我自己写不是不行，我只想希望官方丰富下组件库有问题？** 你牛逼，你开源个？还是说你们两个不知道编辑器是个天坑？有本事，让我看到你的开源！！你才是啥也不会，就知道叭叭叭的xxx。懒得跟你们吵架，真是，低劣的中国式程序员。

**Comment by jahnli** [comment]
凭啥给你搞 你是什么品种 ？ 伸手党 ？

**Comment by 4xii** [comment]
![image](https://github.com/ant-design/ant-design/assets/73146951/e212eb1c-7183-4ae0-84bf-254fde06de79)

请你修复一下你的isuss的bug，重要的事情说三遍！
请你修复一下你的isuss的bug，重要的事情说三遍！
请你修复一下你的isuss的bug，重要的事情说三遍！

**Comment by kwooshung** [comment]
> 凭啥给你搞 你是什么品种 ？ 伸手党 ？

哥们，我说给我搞了么？我是说丰富社区，我只是给官方提个建议。怎么就侮辱起来人了呢？

**Comment by jahnli** [comment]
![image](https://github.com/ant-design/ant-design/assets/20943608/d66fa098-08fd-4647-843c-72df361c0920)
这谁啊   对社区这么用心 ？  国内开源有希望了

**Comment by kwooshung** [comment]
> ![image](https://user-images.githubusercontent.com/73146951/276829789-e212eb1c-7183-4ae0-84bf-254fde06de79.png)
> 
> 请你修复一下你的isuss的bug，重要的事情说三遍！ 请你修复一下你的isuss的bug，重要的事情说三遍！ 请你修复一下你的isuss的bug，重要的事情说三遍！

嚯，我提交的Arco Design中的issues，忘记修改了，大家都是在喷我，就你提出了珍贵的意见。

**Comment by kwooshung** [comment]
> ![image](https://user-images.githubusercontent.com/20943608/276830399-d66fa098-08fd-4647-843c-72df361c0920.png) 这谁啊 对社区这么用心 ？ 国内开源有希望了

有问题么？我提交几个issues怎么就开始这样了？我得罪你们什么了？

**Comment by jahnli** [comment]
这年头环境这么不好了都  少爷都从村里出来打工了

**Comment by kwooshung** [comment]
> 这年头环境这么不好了都 少爷都从村里出来打工了

以后不用叫我少爷，我家没有这样的奴才。

**Comment by zhaogongchengsi** [comment]
> > @zhaogongchengsi 你还真是技术不咋地，就会叭叭叭，直接让作者给你写个项目不就完事了吗
> 
> > @songrufeng666   _**api，我不知道官方具体怎么实现，因为这个组件复杂点儿，所以我就说说期望的组件有啥吧，功能真的很少，但是兼容性方面确实很麻烦，以下是我能想到的功能**_ 你还真是技术不咋地，就会叭叭叭
> 
> 提个issues怎么了？社区怎么这个样？技术社区有你这种败类，真是丰富多彩，什么叫就会叭叭叭？凭这个就瞎胡说是不是，我11年前就一个java技术，就能让19岁高中毕业没大学文凭的我先后被百度和腾讯录用，现在你们行么？是不是还给别人打工呢？是不是还996呢？开始创业了吗？打算一辈子就给别人打工吗？每个月多少工资啊？车贷房贷还了没？还是说车房都没有呢？
> 
> **我特么需要你的认可？我自己写不是不行，我只想希望官方丰富下组件库有问题？这个功能我早特么写出来了，只不过在公司内部使用。** 你牛逼，你开源个？还是说你们两个不知道编辑器是个天坑，还是认为只需要 `div` 加上一个 `contenteditable` 属性就万事大吉了？要真是这样，我特么呵呵呵了！
> 
> 有本事，让我看到你的开源！！你才是啥也不会，就知道叭叭叭的xxx。懒得跟你们吵架，真是，低劣的中国式程序员。
> 
> 算了不说了，你们呀说的都对，对的很，我技术真不如你们，你们是神一样的存在！！让我膜拜吧！！行了，自己那一点儿小小的虚荣心满足了吗？难道只有靠贬低别人才能抬高自己么？
> 
> 你要说自己有文凭，那还真是应了 **“高学历只能过滤学渣，但过滤不了人渣”**，还不如一个高中学历的我相对有素质呢。 你要说自己没有文凭，呵呵，高学历，那还真混的不如我呢，南京创业，住房是大平层，车一辆奔驰E200，一辆宝马5系。
> 
> 哎，啥也不是~~~

怎么随便说一句 就急成这样 ，写这么大一段呢，扯这么多也还是掩盖不了你脆弱的小心灵，就知道叭叭，知道编辑器是个填坑还在这向开源项目伸手，你还真好意思，完全就是一个臭傻逼，叭叭个锤子，你才是国内开源的败类，还八年前就会java，我估计你就知道个java这个词，傻逼

**Comment by jahnli** [comment]
> > 这年头环境这么不好了都 少爷都从村里出来打工了
> 
> 以后不用叫我少爷，我家没有这样的奴才。何况，我是自己给自己打工，不像你，给别人打工，拿点儿死工资

小土鳖又急了  又菜又爱叫， 急了急了  到处求爷爷告奶奶 何必呢 ？

**Comment by so1ve** [comment]
我认为开源社区有您这样的用户是咱们八辈子修来的的福报

**Comment by wucyAAA** [comment]
@kwooshung 急 绷 乐 ！

**Comment by songrufeng666** [comment]
> > @zhaogongchengsi 你还真是技术不咋地，就会叭叭叭，直接让作者给你写个项目不就完事了吗
> 
> > @songrufeng666   _**api，我不知道官方具体怎么实现，因为这个组件复杂点儿，所以我就说说期望的组件有啥吧，功能真的很少，但是兼容性方面确实很麻烦，以下是我能想到的功能**_ 你还真是技术不咋地，就会叭叭叭
> 
> 提个issues怎么了？社区怎么这个样？技术社区有你这种败类，真是丰富多彩，什么叫就会叭叭叭？凭这个就瞎胡说是不是，我11年前就一个java技术，就能让19岁高中毕业没大学文凭的我先后被百度和腾讯录用，现在你们行么？是不是还给别人打工呢？是不是还996呢？开始创业了吗？打算一辈子就给别人打工吗？每个月多少工资啊？车贷房贷还了没？还是说车房都没有呢？
> 
> **我特么需要你的认可？我自己写不是不行，我只想希望官方丰富下组件库有问题？这个功能我早特么写出来了，只不过在公司内部使用。** 你牛逼，你开源个？还是说你们两个不知道编辑器是个天坑，还是认为只需要 `div` 加上一个 `contenteditable` 属性就万事大吉了？要真是这样，我特么呵呵呵了！
> 
> 有本事，让我看到你的开源！！你才是啥也不会，就知道叭叭叭的xxx。懒得跟你们吵架，真是，低劣的中国式程序员。
> 
> 算了不说了，你们呀说的都对，对的很，我技术真不如你们，你们是神一样的存在！！让我膜拜吧！！行了，自己那一点儿小小的虚荣心满足了吗？难道只有靠贬低别人才能抬高自己么？
> 
> 你要说自己有文凭，那还真是应了 **“高学历只能过滤学渣，但过滤不了人渣”**，还不如一个高中学历的我相对有素质呢。 你要说自己没有文凭，呵呵，高学历，那还真混的不如我呢，南京创业，住房是大平层，车一辆奔驰E200，一辆宝马5系。
> 
> 哎，啥也不是~~~



> > @zhaogongchengsi 你还真是技术不咋地，就会叭叭叭，直接让作者给你写个项目不就完事了吗
> 
> > @songrufeng666   _**api，我不知道官方具体怎么实现，因为这个组件复杂点儿，所以我就说说期望的组件有啥吧，功能真的很少，但是兼容性方面确实很麻烦，以下是我能想到的功能**_ 你还真是技术不咋地，就会叭叭叭
> 
> 提个issues怎么了？社区怎么这个样？技术社区有你这种败类，真是丰富多彩，什么叫就会叭叭叭？凭这个就瞎胡说是不是，我11年前就一个java技术，就能让19岁高中毕业没大学文凭的我先后被百度和腾讯录用，现在你们行么？是不是还给别人打工呢？是不是还996呢？开始创业了吗？打算一辈子就给别人打工吗？每个月多少工资啊？车贷房贷还了没？还是说车房都没有呢？
> 
> **我特么需要你的认可？我自己写不是不行，我只想希望官方丰富下组件库有问题？这个功能我早特么写出来了，只不过在公司内部使用。** 你牛逼，你开源个？还是说你们两个不知道编辑器是个天坑，还是认为只需要 `div` 加上一个 `contenteditable` 属性就万事大吉了？要真是这样，我特么呵呵呵了！
> 
> 有本事，让我看到你的开源！！你才是啥也不会，就知道叭叭叭的xxx。懒得跟你们吵架，真是，低劣的中国式程序员。
> 
> 算了不说了，你们呀说的都对，对的很，我技术真不如你们，你们是神一样的存在！！让我膜拜吧！！行了，自己那一点儿小小的虚荣心满足了吗？难道只有靠贬低别人才能抬高自己么？
> 
> 你要说自己有文凭，那还真是应了 **“高学历只能过滤学渣，但过滤不了人渣”**，还不如一个高中学历的我相对有素质呢。 你要说自己没有文凭，呵呵，高学历，那还真混的不如我呢，南京创业，住房是大平层，车一辆奔驰E200，一辆宝马5系。
> 
> 哎，啥也不是~~~

哇，富哥们，混得这么好，作者怎么能平白给你当牛做马打工来满足你的需求呢，建议你给作者打赏一点，好让作者有动力更新呀。

**Comment by Wxh16144** [comment]
Duplicate of #1083

**Comment by zombieJ** [comment]
感谢建议，不过目前没有计划去做富文本编辑器。在 v3 更早时期，有试着封装过 draftjs 做了 Mention 组件，但是富文本编辑器即便是使用现成库也需要非常大的精力维护，所以我们应该是不会去做的了。

**Comment by songrufeng666** [comment]
> > 这年头环境这么不好了都 少爷都从村里出来打工了
> 
> 以后不用叫我少爷，我家没有这样的奴才。何况，我是自己给自己打工，不像你，给别人打工，拿点儿死工资

不会吧不会吧，明面上自己给自己打工，实际上到处伸手当白嫖党吧？白嫖还不过瘾，还要让别人给你当牛做马？钱不会就是这样赚出来的吧？资本家还知道雇人发工资呢，你这无本万利呀，真不愧是拿活工资的！

**Comment by zombieJ** [comment]
另外各位实在不好意思，吵架不是我们想看到的。这里先把 issue 锁了哈。

**Comment by afc163** [comment]
我们认为任何围绕项目本身的意见和建议都是对 antd 社区有意义的，请各位遵循社区公约，不要在评论区发表对人不对事的内容。
