### ISSUE TITLE
希望table,loading使用的Spin也能支持delay的设置

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#4544]
原因一样的,应用在局域网内请求时基本上很多都秒出,table又是后台系统中使用比较多的一个组件.现在是数据已经加载显示了,spin才开始动画,要是能在table的spin设置delay属性,这个问题就可以解决了. 谢谢.

呃... 这个应该没有太多的牵连, https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L879
增加一个属性设置, 应该比较简单.

但是1不会pr,2水品太菜.不好意思画蛇添足.

**Comment by benjycui** [comment]
重载 `Table[loading]` 属性为 `boolean | Object`，当其为一个对象时，可以包含 `Spin` 的属性 https://ant.design/components/spin/#API

**Comment by benjycui** [comment]
@xjdata 还是希望你能尝试一下，PR 这事一回生二回熟。

**Comment by afc163** [comment]
resolved in https://github.com/ant-design/ant-design/pull/4824
