### ISSUE TITLE
Multiple notification has black shaded background in 5.10.1

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#45449]
### Reproduction link

 [https://ant.design/components/notification-cn](https://ant.design/components/notification-cn)

### Steps to reproduce

Multiple notification  pop up 

### What is expected?

Multiple notification pop up with a black shaded background

see screenshot

### What is actually happening?

![image](https://github.com/ant-design/ant-design/assets/29728228/9c0b7958-85ba-4e98-b475-ca18b5833d62)

![image](https://github.com/ant-design/ant-design/assets/29728228/77682906-0438-41fe-8aaf-732c9ecb6841)

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | Umi |
| System | windows 10 |
| Browser | chrome 118 |

**Comment by zombieJ** [comment]
这个看起来是样式不支持，确定是 Chrome 118 么？

**Comment by li-jia-nan** [comment]
好像是系统的问题，mac 是正常的，win 必现的

**Comment by zystudios** [comment]
> 这个看起来是样式不支持，确定是 Chrome 118 么？

![image](https://github.com/ant-design/ant-design/assets/29728228/c1922754-e5e2-4647-a3a3-9e19ceed56f3)

**Comment by zystudios** [comment]
![image](https://github.com/ant-design/ant-design/assets/29728228/b0e969d7-26a2-441a-9152-431762eab98f)
@zombieJ

**Comment by MadCcc** [comment]
@zystudios 去掉 backdrop-filter 正常么

**Comment by zystudios** [comment]
> @zystudios 去掉 backdrop-filter 正常么

不正常，因为这个本身也没生效

静止状态没有问题，主要是在收缩展开 transform: translate3d 的时候会出现问题
