### ISSUE TITLE
Need `optionRender` for customize option item in select list

### ISSUE THREAD

**Issue by mytharcher** [ant-design/ant-design#45445]
### What problem does this feature solve?

If use `<Select />` with remote loaded options, we need to customize all option items in select list. For now, each option only contains a label text. But if we need more information to be show in each item, it is not possible.

![](https://github.com/ant-design/ant-design/assets/525658/16c0a5be-c235-4ff6-aded-dc607a855f61)

Or we can not just use `options` property, but change to use `data.map(item => <Option>)` style.

### What does the proposed API look like?

```
function SomeFunctionComponet({ option, index, options }) {
  return (
    <div>
      <span>{index + 1}.</span>
      <span>{option.label}</span>
      <span>{option.data.date}</span>
    </div>
  );
}

function MySelect() {
  return (
    <Select
      optionRender={SomeFunctionComponet}
    />
  );
}
```

**Comment by RedJue** [comment]
Mark

**Comment by crazyair** [comment]
see https://ant-design.antgroup.com/components/select-cn#select-demo-option-label-prop

**Comment by mytharcher** [comment]
> see https://ant-design.antgroup.com/components/select-cn#select-demo-option-label-prop

I have read this. But to use raw `<Option>`s as children is not my intention. Especially to use `options` property will get better performance than JSX (which is also documented).

**Comment by crazyair** [comment]
> > see https://ant-design.antgroup.com/components/select-cn#select-demo-option-label-prop
> 
> I have read this. But to use raw `<Option>`s as children is not my intention. Especially to use `options` property will get better performance than JSX (which is also documented).

https://stackblitz.com/edit/react-py9tm8?file=demo.tsx

**Comment by mytharcher** [comment]
> > > see https://ant-design.antgroup.com/components/select-cn#select-demo-option-label-prop
> > 
> > 
> > I have read this. But to use raw `<Option>`s as children is not my intention. Especially to use `options` property will get better performance than JSX (which is also documented).
> 
> https://stackblitz.com/edit/react-py9tm8?file=demo.tsx

I'd like to apply the `optionRender` to all options, and dynamically. Sometimes the options is loaded remotely. In fact, we could do another mapping, but if `optionRender` is supported, it will be much easier for all developers.

**Comment by crazyair** [comment]
![image](https://github.com/ant-design/ant-design/assets/7971419/32177985-ca6a-4274-8aab-d74a0cba98e9)

**Comment by mytharcher** [comment]
> **In fact, we could do another mapping**, but if `optionRender` is supported, it will be much easier for all developers.
