### ISSUE TITLE
网站演示链接的体验

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4545]
访问：https://ant.design/components/table/#components-table-demo-bordered

期望：对应 demo 高亮。

实际上：先是跳到对应的演示，demo 高亮。然后跳回顶部，再跳到对应的演示上，最终 demo 未高亮。

**Comment by benjycui** [comment]
React 似乎无法很好的和 CSS 的 `:target` 协作，所以 hack 了一下。

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#Form.create(options) 

貌似又有锚点跳回顶部的问题。Chrome 也有，Firefox 下更明显一些。

**Comment by benjycui** [comment]
因为这个是 [hack](https://github.com/ant-design/ant-design/commit/e459562cdc49313636bad812903671c3e0b66f38#diff-1e4d5b52a581008b92cdf44424012826R28)，所以如果页面一开始还是在顶部，`didMount` 后才触发 anchor 跳转。
