### ISSUE TITLE
antd.css is overriding existing css in entire application

### ISSUE THREAD

**Issue by prashantvithani** [ant-design/ant-design#4546]
#### Environment(required)

- antd version: 2.6.1

#### What did you do? Please provide steps to re-produce your problem.
I Included the [antd.css](https://unpkg.com/antd@2.6.1/dist/antd.css) file at application level along with other css files. After reloading the browser, I see that all rules I have written before are overridden by the rules in antd.css

#### What do you expected?
I want the antd.css to be applied only for specific component which is used. Don't want existing style to be altered.

**Comment by benjycui** [comment]
Yep, it's recommended to use `antd` in new project, or make your old project follow Ant Design Specification

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4331#issuecomment-268722790

**Comment by edmulraney** [comment]
Is it on your road map? I've partially worked around this issue by including antd css first then my own css so that antd gets overwritten by mine, obviously this isn't ideal.

**Comment by prashantvithani** [comment]
I've found a work around by removing all the CSS rules based on Tags like html, body, a, h1 etc... Only kept CSS rules based on classes. It's helping for now.

**Comment by bochen2014** [comment]
I also thought of copying the css out and remove those global rules. but this is a hacky approach and will make my code out of sync with the latest code base -- it could be broken anytime after a `npm upgrade`
