### ISSUE TITLE
希望useToken和getDesignToken能获取到包括组件级的token定义（包括全局和组件独有的）。

### ISSUE THREAD

**Issue by WaldenLiang** [ant-design/ant-design#45469]
### What problem does this feature solve?

因为在某些样式开发场景，需要获取到组件的token定义，比如需要获取到Button组件的defaultBg定义。而目前的情况是，useToken只能获取全局的token以及显性声明的组件token，虽然5.8之后支持在组件的token定义中传入algorithm，但仍然无法获取到组件专有的token。

### What does the proposed API look like?

```tsx
import React from 'react';
import { ConfigProvider, theme } from 'antd';

const { useToken } = theme;

const CustomButton: React.FC = () => {
  const { token } = useToken();

  return (
    <button
      style={{
        background: token.Button.defaultBg,
        color: token.Button.colorPrimary,
      }}
    >
      Custom Button
    </button>
  );
};

const App: React.FC = () => (
  <>
    <ConfigProvider
      theme={{
        components: {
          Button: {
            colorPrimary: '#00b96b',
          },
        },
      }}
    >
      <CustomButton />
    </ConfigProvider>
  </>
);

export default App;
```

**Comment by MadCcc** [comment]
组件 Token 在组件内部才会初始化，现在没有途径从外部获取。
这也是为了避免不必要的开销，如果这个组件根本就没有被使用过，那么它的组件 token 就不应该被计算。

**Comment by hanjeahwan** [comment]
@MadCcc v4的时候用less项目会用组件的less variable自定义组件的样式 @form-item-label-colon-margin-right和@form-item-label-colon-margin-left v5的token是labelColonMarginInlineEnd和labelColonMarginInlineStart

升级迁移v5是不是没办法复用组件variable或token了

```
@import '~antd/es/style/themes/default.less';

.user-list {
  &-module::after {
    position: relative;
    top: -0.5px;
    margin: 0 @form-item-label-colon-margin-right 0 @form-item-label-colon-margin-left;
    content: ':';
  }

  &-name {
    max-width: 300px;
  }
}
```

**Comment by MadCcc** [comment]
> [@MadCcc](https://github.com/MadCcc) v4的时候用less项目会用组件的less variable自定义组件的样式 @form-item-label-colon-margin-right和@form-item-label-colon-margin-left v5的token是labelColonMarginInlineEnd和labelColonMarginInlineStart
> 
> 升级迁移v5是不是没办法复用组件variable或token了
> 
> ```
> @import '~antd/es/style/themes/default.less';
> 
> .user-list {
>   &-module::after {
>     position: relative;
>     top: -0.5px;
>     margin: 0 @form-item-label-colon-margin-right 0 @form-item-label-colon-margin-left;
>     content: ':';
>   }
> 
>   &-name {
>     max-width: 300px;
>   }
> }
> ```
> 
> 怎么用labelColonMarginInlineEnd和labelColonMarginInlineStart
> 
> ```
> import { createStyles } from 'antd-style';
> const useStyles = createStyles(({ token, css }) => {
>   return {
>     name: css`
>       maxwidth: 300px;
>     `,
>     module: css`
>       &::after {
>         position: relative;
>         top: -0.5px;
>         margin: 0 @form-item-label-colon-margin-right 0 @form-item-label-colon-margin-left;
>         content: ':';
>       }
>     `,
>   };
> });
> 
> export default useStyles;
> ```

v5 之后就没法使用了，组件 token 本身就是开给这个组件用的，不太稳定，建议还是使用全局的

**Comment by towertop** [comment]
那我想问，实现 HOC 时获取当前组件级别的token来对齐样式，是不是一个合理的场景。比如我现在想做一个 Input.TextArea 自带一个悬浮按钮贴靠着右下角留白内，如果能取得 token.Input.paddingBlock、token.Input.paddingInline 设置定位就灵活了。现在有其他方法实现吗？
