### ISSUE TITLE
Mismatch between Modal wrapper documentation implementation and TypeScript interface

### ISSUE THREAD

**Issue by pjbollinger** [ant-design/ant-design#45481]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-10-2-forked-lmtql2?file=/demo.tsx)

### Steps to reproduce

1. Create a `<Modal>`
2. In the `styles` properties of the `<Modal>`, try to set `wrapper` to a value. 

### What is expected?

1. Styles are applied to the wrapper of the modal.
2. No TypeScript Errors.

### What is actually happening?

1. Styles are applied to the wrapper of the modal. - OK
2. TypeScript Error: Type '{ wrapper: { backgroundColor: string; }; }' is not assignable to type 'Omit<ModalStyles, "wrapper">'. - NOT OK

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2.0 |
| System | macOS 14.0 |
| Browser | Firefox 118.0.2 |

---
In the docs, https://ant.design/components/modal, it suggests that `wrapper` should be OK to use in `styles`.

It's unclear why Omit<x, 'wrapper'> is being used here: https://github.com/ant-design/ant-design/commit/ceed98582cdd7d9d881c6bb428c8eb7d6e0228c6#diff-ac9fa8e4784b40c5c2a26fe86dc50bbd39572b8ecf42b73611745ec817d883a1R52-R53

I feel the TypeScript interface is the source of the error.

**Comment by MadCcc** [comment]
`wrapper` is not stable, please follow the typescript defination.

**Comment by MadCcc** [comment]
@kiner-tang We should omit `wrapper` in `styles`.
