### ISSUE TITLE
menu的token在light/dark模式下有bug

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#45488]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhu-ti-antd-5-10-2-forked-cx32lk?file=/demo.tsx)

### Steps to reproduce

1. 鼠标hover MenuItem或者SubMenu，或者鼠标选中MenuItem
2. 点击切换主题按钮将主题切换为dark模式
3. 重复步骤1

### What is expected?

1. light主题下，选中一个MenuItem时，它所在的SubMenu的文字颜色不应该是白色，或者文字颜色是白色，但背景色是主题设置的背景色
2. dark主题下，鼠标hover MenuItem或者SubMenu的时候，背景色应该是设置的背景色

### What is actually happening?

1. light主题下，鼠标hover MenuItem或者SubMenu时背景为设置的背景色，但是一旦选中一个MenuItem后，该MenuItem的背景色会正确改变，但是这时候SubMenu的文字颜色变成了白色
2. dark主题下，鼠标hover MenuItem或者SubMenu时背景不是设置的背景色

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.0.0 |
| System | macos13.4.1 |
| Browser | chrome 117.0.5938.92 |

**Comment by MadCcc** [comment]
暗色模式 Menu 有专用的 token
![image](https://github.com/ant-design/ant-design/assets/27722486/b1045077-ef09-4168-b9f5-33e99e30ddb2)

亮色模式下由于选择 submenu 时会让分组也处于选中状态，所以文字颜色也应用了 `itemSelectedColor`，看起来得区分下。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/52182
