### ISSUE TITLE
运行pnpm run test 时报错

### ISSUE THREAD

**Issue by chenzhuo198** [ant-design/ant-design#45480]
### Reproduction link

[https://github.com/ant-design/ant-design/tree/feature](https://github.com/ant-design/ant-design/tree/feature)

### Steps to reproduce

windows系统运行pnpm run test

### What is expected?

正常执行

### What is actually happening?

    SyntaxError: Cannot use import statement outside a module

      2 | import { act, render } from '@testing-library/react';
      3 | import MockDate from 'mockdate';
    > 4 | import { _rs as onEsResize } from 'rc-resize-observer/es/utils/observerUtil';
        | ^
      5 | import { _rs as onLibResize } from 'rc-resize-observer/lib/utils/observerUtil';
      6 | import type { ReactElement } from 'react';
      7 | import React, { StrictMode } from 'react';

      at Runtime.createScriptFromCode (node_modules/.pnpm/registry.npmmirror.com jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (tests/utils.tsx:4:1)
      at Object.require (components/config-provider/__tests__/style.test.tsx:4:1)

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2.0 |
| System | windows |
| Browser | 无 |

---
将import { _rs as onEsResize } from 'rc-resize-observer/es/utils/observerUtil';改为import { _rs as onEsResize } from 'rc-resize-observer/lib/utils/observerUtil';就好了，当时为什么要引用es下的文件呢

**Comment by zombieJ** [comment]
你看下面那行就是从 lib 引入，test 文件是共享的。es 和 lib 都会跑，所以这里两边都会调用一次确保 resize 事件触发。

**Comment by zombieJ** [comment]
另外，这个问题可以去 pnpm 发 issue 问问。这个 npm 下是可以跑的哈。
