### ISSUE TITLE
Notification 中的notice-wrapper 和 notice样式冲突

### ISSUE THREAD

**Issue by aslan-alt** [ant-design/ant-design#45482]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-morse-s7mzsm?file=/src/App.js)

### Steps to reproduce

1. 打开连接，进入codesandbox
1. 点击button
2. 查看 红色区域的样式

### What is expected?

期待一个style生效（内层或外层）

### What is actually happening?

notice-wrapper 和 notice同时生效 

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | any |
| System | any |
| Browser | any |

---
如果把pandding换成其它样式，比如旋转? 样式会更加错乱

问题定位结果：
rc-notification包中的 notification/src/NoticeList.tsx 中的 139行(外层)的configStyle和147行(内层)的config产生冲突

解决思路：
1. 将外层中的...configStyle删除 ，与configClassName的设置方式保持一致，都传给Notice
2. 将config中的 style和className 绑定到外层

如果您有更好的想法，请@我，我很乐意参与到该问题的讨论，创建修复PR

**Comment by aslan-alt** [comment]
<img width="1700" alt="截屏2023-10-22 20 53 01" src="https://github.com/ant-design/ant-design/assets/54422571/6df0eb6c-f6e8-4761-a86a-c3fe43021747">
<img width="1034" alt="截屏2023-10-22 21 35 51" src="https://github.com/ant-design/ant-design/assets/54422571/67240df6-0df7-4e9a-80ee-de907d2193de">

**Comment by afc163** [comment]
看上去是 rc-notification 的问题？

**Comment by afc163** [comment]
确实是多了一个 style，看下之前的逻辑是啥，我倾向于和 className 放在一起。
