### ISSUE TITLE
Select showSearch 失效了

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#45495]
### Reproduction link

[https://codepen.io/valar123/pen/LYqYKqo?editors=001](https://codepen.io/valar123/pen/LYqYKqo?editors=001)

### Steps to reproduce

输入jack,下拉列表为空

### What is expected?

匹配到 jack options

### What is actually happening?

 空

| Environment | Info |
| --- | --- |
| antd | undefined |
| React |  18 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
`optionFilterProp` 默认匹配 `value`，改成 `label` 即可

**Comment by vaynevayne** [comment]
> `optionFilterProp` 默认匹配 `value`，改成 `label` 即可
一直都是 label 吧, 哪个版本改成 value 的?

**Comment by afc163** [comment]
1.x 就是 value 了：https://1x.ant.design/components/select/
