### ISSUE TITLE
疑似缺陷：demo 树形控件节点主题显示相关对象index, beforeStr, afterStr 采用key属性，导致标题显示为key值；是否应该更改为title属性

### ISSUE THREAD

**Issue by chimmyhuang** [ant-design/ant-design#4549]
版本：ant-desgin v2.6.1

疑似缺陷：demo 树形控件节点主题显示相关对象index, beforeStr, afterStr 采用key属性，导致标题显示为key值；是否应该更改为title属性。

文件路径：https://github.com/ant-design/ant-design/blob/master/components/tree/demo/search.md

const loop = data => data.map((item) => {
      const index = item.**key**.search(searchValue);
      const beforeStr = item.**key**.substr(0, index);
      const afterStr = item.**key**.substr(index + searchValue.length);
      const title = index > -1 ? (
        <span>
          {beforeStr}
          <span className="ant-tree-searchable-filter">{searchValue}</span>
          {afterStr}
        </span>
      ) : <span>{item.key}</span>;
      if (item.children) {
        return (
          <TreeNode key={item.key} title={title}>
            {loop(item.children)}
          </TreeNode>
        );
      }
      return <TreeNode key={item.key} title={title} />;
    });

是否应该更改为：

const loop = data => data.map((item) => {
      const index = item.**title**.search(searchValue);
      const beforeStr = item.**title**.substr(0, index);
      const afterStr = item.**title**.substr(index + searchValue.length);
      const title = index > -1 ? (
        <span>
          {beforeStr}
          <span className="ant-tree-searchable-filter">{searchValue}</span>
          {afterStr}
        </span>
      ) : <span>{item.key}</span>;
      if (item.children) {
        return (
          <TreeNode key={item.key} title={title}>
            {loop(item.children)}
          </TreeNode>
        );
      }
      return <TreeNode key={item.key} title={title} />;
    });

**Comment by yesmeck** [comment]
没错，这里就是要显示 `key`。
