### ISSUE TITLE
Upgrade all rc-* to dumi 2 + father 4

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#45491]
Enable 
 fix vercel preview build:
<img width="397" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/0a92329f-a528-474a-8044-ddd0cb8ee597">

- [x] https://github.com/react-component/select https://github.com/react-component/select/pull/988
- [x] https://github.com/react-component/tree-select https://github.com/react-component/tree-select/pull/446
- [x] https://github.com/react-component/tree https://github.com/react-component/tree/pull/801
- [x] https://github.com/react-component/cascader
- [x] https://github.com/react-component/dialog
- [x] https://github.com/react-component/util
- [x] https://github.com/react-component/resize-observer https://github.com/react-component/resize-observer/pull/192
- [x] https://github.com/react-component/upload https://github.com/react-component/upload/pull/523
- [x] https://github.com/react-component/input-number
- [x] https://github.com/react-component/tooltip
- [x] https://github.com/react-component/overflow https://github.com/react-component/overflow/pull/42
- [x] https://github.com/react-component/virtual-list https://github.com/react-component/virtual-list/pull/255
- [x] https://github.com/react-component/segmented
- [x] https://github.com/react-component/pagination https://github.com/react-component/pagination/pull/513
- [x] https://github.com/react-component/motion
- [x] https://github.com/react-component/rate https://github.com/react-component/rate/pull/188
- [x] https://github.com/react-component/progress https://github.com/react-component/progress/pull/255
- [x] https://github.com/react-component/mutate-observer https://github.com/react-component/mutate-observer/pull/9
- [x] https://github.com/react-component/portal https://github.com/react-component/portal/pull/15
- [x] https://github.com/react-component/steps https://github.com/react-component/steps/pull/334
- [x] https://github.com/react-component/dropdown https://github.com/react-component/dropdown/pull/232
- [x] https://github.com/react-component/switch https://github.com/react-component/switch/pull/125
- [x] https://github.com/react-component/footer https://github.com/react-component/footer/pull/56

## Documents

- Upgrade dumi from 1.x to 2.x: https://d.umijs.org/guide/upgrading

**Comment by yoyo837** [comment]
有些仓库即使 dumi@2 + fatcher@4, vercel 仍然红的

**Comment by DBSDs** [comment]
> 有些仓库即使 dumi@2 + fatcher@4, vercel 仍然红的

是的，我也不清楚为什么会报错，我需要知道 vercel 部署错误的详细信息。
本来想达成 homepage 都改为 [https://react-component.github.io/{name}](https://react-component.github.io/%7Bname%7D)，但是某些库在没有 base url，如果我加上的话会导致 vercel 部署不正确 -> 页面显示为空。
最后 rc-test 没有引入dumi，因此我并没有对此仓库做升级。

**Comment by yoyo837** [comment]
> > 有些仓库即使 dumi@2 + fatcher@4, vercel 仍然红的
> 
> 是的，我也不清楚为什么会报错，我需要知道 vercel 部署错误的详细信息。 本来想达成 homepage 都改为 [https://react-component.github.io/{name}](https://react-component.github.io/%7Bname%7D)，但是某些库在没有 base url，如果我加上的话会导致 vercel 部署不正确 -> 页面显示为空。 最后 rc-test 没有引入dumi，因此我并没有对此仓库做升级。

这个只能让有权限的Core member去看了.

**Comment by afc163** [comment]
> 是的，我也不清楚为什么会报错，我需要知道 vercel 部署错误的详细信息。

除了 @zombieJ 都看不到。

**Comment by DBSDs** [comment]
@afc163 father 从2.x 升级至4.0删除了 test 命令，不同仓库中有 `umi-test` 也有` rc-test`，是用哪个？

**Comment by yoyo837** [comment]
> @afc163 father 从2.x 升级至 4.0 删除了 test 命令，不同仓库中有 `umi-test` 也有` rc-test`，是用哪个？

可以参考 https://github.com/react-component/upload/pull/523

**Comment by afc163** [comment]
All done!
