### ISSUE TITLE
整理 Table demos

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#4550]
现在的 demo:

- ajax.md
- basic.md
- bordered.md
- colspan-rowspan.md
- custom-filter-panel.md
- dynamic-settings.md
- edit-cell.md
- edit-row.md
- expand-children.md
- expand.md
- fixed-columns-header.md
- fixed-columns.md
- fixed-header.md
- grouping-columns.md
- head.md
- jsx.md
- paging.md
- reset-filter.md
- row-selection-and-operation.md
- row-selection.md
- size.md

1. `row-selection.md` 跟 `row-selection-and-operation.md` 重合，`row-selection.md` 可以去掉；
1.  `head.md(其实是 Filter and sorter)`  跟 `reset-filter.md` 重合，`head.md` 可以去掉；
1.  `paging.md`、`size.md`、`bordered.md` 、`expand.md`、`fixed-header.md` 与 `dynamic-settings.md` 重合，考虑去掉；
1.  `fixed-columns.md` 跟 `fixed-columns-header.md`，`fixed-columns.md` 可以去掉；
1.  新增子表格的 demo；
1. `reset-filter.md` 里的 `Clear filters and sorting` 不工作；

**Comment by yesmeck** [comment]
@benjycui @afc163 看看有没有要补充的。

**Comment by afc163** [comment]
reset-filter.md 是专门展现受控 filter，和 head 不冲突。

**Comment by afc163** [comment]
fixed-columns.md 不包含固定表头，大多数情况也不需要固定表头。

**Comment by afc163** [comment]
paging.md 可以去掉， 其他几个主要是展示能力，而且对设计师比较有帮助。

**Comment by benjycui** [comment]
> paging.md、size.md、bordered.md 、expand.md、fixed-header.md 与 dynamic-settings.md 重合，考虑去掉；

其实 dynamic-settings 主要还是 playground 的作用，以后还会有新增的属性，所以不认为它和其他 demo 有重合。

**Comment by benjycui** [comment]
size.md、bordered.md 合并成 style.md ？

**Comment by yesmeck** [comment]
>  reset-filter.md 是专门展现受控 filter，和 head 不冲突。

是不是合并成一个，像 size.md 那样，同时展示受控和非受控的情况。

**Comment by afc163** [comment]
> 是不是合并成一个，像 size.md 那样，同时展示受控和非受控的情况。

对于基本需求，head 就够用了。合并在一起，大部分人就会看到过于复杂的实现，不利于他对 API 的学习和理解。

**Comment by afc163** [comment]
> size.md、bordered.md 合并成 style.md ？

感觉可以。

**Comment by yesmeck** [comment]
> reset-filter.md 是专门展现外部受控 filter，和 head 不冲突。head 是最简的情况。

> 对于基本需求，head 就够用了。合并在一起，大部分人就会看到过于复杂的实现，不利于他对 API 的学习和理解。

所以还是保留现在的 `reset-filter.md` 和 `head.md` 的意思吗？

**Comment by afc163** [comment]
对的。

**Comment by afc163** [comment]
上面修复了 reset-filter.md 里的 Clear filters and sorting 不工作的问题，都没人发现，果然是没什么人用的特性。。

> PS：目前 lint 貌似会对 componets 下临时生成的 jsx 和 js 文件进行检查。

**Comment by yesmeck** [comment]
如果 Demo 右边的导航能支持二级标题，然后把标题显示全的话可能会清楚很多，Demo 多点也没关系。

![dingtalk20170111111953](https://cloud.githubusercontent.com/assets/465125/21835038/d1507f54-d7f4-11e6-87f5-acff8b9e1627.png)

![dingtalk20170111115456](https://cloud.githubusercontent.com/assets/465125/21835042/d5cd0156-d7f4-11e6-88a0-182fdf6e6361.png)

**Comment by afc163** [comment]
二级菜单可以有，可能需要设计一下 demo 的 meta 格式。

**Comment by afc163** [comment]
这个整理完了？

**Comment by yesmeck** [comment]
还没有

**Comment by FANUP** [comment]
我发现Clear filters没起作用....Table里的filteredValue好像不起作用了

**Comment by yesmeck** [comment]
@FANUP 可以的呀。

**Comment by FANUP** [comment]
我直接把 filteredValue设置为null，发现还是能筛选....所以table例子里的filteredInfo设置为null，还是没起作用

**Comment by FANUP** [comment]
antd版本是2.6.1的

**Comment by yesmeck** [comment]
1. 升到最新版；
2. 有问题另外开 issue 吧。
