### ISSUE TITLE
在 Image.PreviewGroup 组件中使用 Carousel 组件时，预览图片重复

### ISSUE THREAD

**Issue by RJM1996** [ant-design/ant-design#45516]
### Reproduction link

[https://stackblitz.com/edit/react-hvxep6?file=demo.tsx](https://stackblitz.com/edit/react-hvxep6?file=demo.tsx)

### Steps to reproduce

点击重现链接即可复现

### What is expected?

预览时显示正确的图片数量

### What is actually happening?

比如图片有2张，预览时就变成了5张，有3张是重复的
![image](https://github.com/ant-design/ant-design/assets/33800707/3e30b84b-c1e4-42de-9045-d0c41e02c68f)

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 16.8-18.2 |
| System | Mac OS |
| Browser | Chrome 版本 104.0.5112.101（正式版本） (x86_64) |

**Comment by afc163** [comment]
这是啥用法？预期效果是啥？

**Comment by afc163** [comment]
你可以加一个 `infinite={false}` 来解决：https://stackblitz.com/edit/react-hvxep6-vbmj4j?file=demo.tsx

**Comment by RJM1996** [comment]
> 你可以加一个 `infinite={false}` 来解决：https://stackblitz.com/edit/react-hvxep6-vbmj4j?file=demo.tsx

感谢大佬，可以了。这个参数的作用是啥呢？文档里没看见

**Comment by RJM1996** [comment]
> > 你可以加一个 `infinite={false}` 来解决：https://stackblitz.com/edit/react-hvxep6-vbmj4j?file=demo.tsx
> 
> 感谢大佬，可以了。这个参数的作用是啥呢？文档里没看见
<img width="477" alt="image" src="https://github.com/ant-design/ant-design/assets/33800707/b903d7e1-a7cd-4e4b-8038-9617e0c81487">
跑马灯组件使用了 https://react-slick.neostack.com/docs/api 实现，该组件有一个属性 infinite 定义是否无穷环绕，默认开启。
