### ISSUE TITLE
ColorPicker 默认值无法为空

### ISSUE THREAD

**Issue by lindaJNlinda** [ant-design/ant-design#45517]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-wf7q8k?file=/index.js)

### Steps to reproduce

1、没有给color 设置值，但是页面能到 有值 #1677FF, 点击按钮会打印form ，color 值为undefined 
2、color 为非必填，选择之后，无法再次去掉颜色， color 永远有值

### What is expected?

初始化时 RGB 可以为空，并且 选择之后可以清空

### What is actually happening?

RGB 为undefined,但是 ColorPicker 给了一个默认值，并且无法清空，清空回调函数也未执行

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by RedJue** [comment]
非受控场景下，初始颜色就是 #1677FF，为 antd 的主色，如果初始化值想为空，设置 value = "" 或者 null
ref https://codesandbox.io/s/antd-reproduction-template-forked-k9482n?file=/index.js

**Comment by afc163** [comment]
> 非受控场景下，初始颜色就是 #1677FF，为 antd 的主色

@RedJue 这个不太合理，大多数场景不需要  #1677FF 这个主色。

**Comment by RedJue** [comment]
> > 非受控场景下，初始颜色就是 #1677FF，为 antd 的主色
> 
> @RedJue 这个不太合理，大多数场景不需要 #1677FF 这个主色。

那非受控场景下显示为颜色空？

**Comment by afc163** [comment]
合理。

**Comment by yoyo837** [comment]
一同考虑下这个 https://github.com/ant-design/ant-design/discussions/45456 ?
