### ISSUE TITLE
Typography missing type of ellipsis={{ rows: 1 }}

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#45511]
https://codesandbox.io/s/sheng-lue-hao-antd-5-10-2-forked-mv6xgn?file=/demo.tsx

```
Type '{ rows: number; }' is not assignable to type 'boolean | Omit<EllipsisConfig, "expandable" | "rows" | "onExpand">'.
```

<img width="989" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/a7640d78-7c9a-479f-86e4-02211b3473ed">

**Comment by pavel-pismerov** [comment]
The same issue 
![image](https://github.com/user-attachments/assets/b016146e-68c3-439a-b841-cbe408f81c4b)

**Comment by manyuemeiquqi** [comment]
latest version same ts error?

**Comment by hsyfee** [comment]
The problem still exists with antd version 5.21.6.
