### ISSUE TITLE
DatePicker.RangePicker   Form.Item   moment 报错：Warning: Maximum update depth exceeded.

### ISSUE THREAD

**Issue by cdmalcl** [ant-design/ant-design#45532]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-vp48qc?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

打开就能看出来

### What is expected?

正常点儿

### What is actually happening?

年月不停的涨，报错：Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by cdmalcl** [comment]
补充：改为用dayjs就可以了。但想知道为啥会这样

**Comment by Yuiai01** [comment]
> 补充：改为用dayjs就可以了。但想知道为啥会这样

因为 antd 5.x 默认使用 dayjs，如果你想使用 moment 可以参考 https://ant.design/docs/react/use-custom-date-library-cn

**Comment by cdmalcl** [comment]
但怎么会导致循环渲染的？而且如果我设置value也没事儿

**Comment by zombieJ** [comment]
每个日期库底层都有对应的 generate 函数用以统一处理逻辑，dayjs 的 generate 函数不能处理 moment 对象。因为 moment 是 mutable 的，而 dayjs 是 immutable 的。

**Comment by cdmalcl** [comment]
跑了下rc-picker源码，配置dayjs格式，但设置moment值，在format时会出现非预期的值。这种情况组件重新更新值，然后反复刷新。
