### ISSUE TITLE
Collapse折叠面板不能默认全部打开吗？

### ISSUE THREAD

**Issue by andrew2558** [ant-design/ant-design#45530]
### What problem does this feature solve?

这样就一下全部显示了面板的内容

### What does the proposed API look like?

可以设置Collapse折叠面板默认全部打开或关闭

**Comment by zombieJ** [comment]
使用 `defaultActiveKey` 把 Panel 的 `key` 全填进去就好了哈~

**Comment by yoyo837** [comment]
https://codesandbox.io/s/zhe-die-mian-ban-antd-5-10-2-forked-gk8qvm?file=/demo.tsx

**Comment by Gzbox** [comment]
@zombieJ   大佬 如果是那种动态添加的 数据量还是遍历嵌套的那种  是不是这种就不合适了  要用 activeKey 但是把正如前面所说 数量多且还是遍历嵌套的 每次新加一个都要遍历一遍取出 key 在 setState 感觉怪怪的吶？

> 使用 `defaultActiveKey` 把 Panel 的 `key` 全填进去就好了哈~

**Comment by zombieyang** [comment]
动态添加的defaultActiveKey确实不生效
