### ISSUE TITLE
table的sticky如何指定粘性的元素

### ISSUE THREAD

**Issue by paywail** [ant-design/ant-design#45534]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sui-ye-mian-gun-dong-de-gu-ding-biao-tou-he-gun-dong-tiao-antd-4-24-14-forked-2xdyww?file=/demo.tsx)

### Steps to reproduce

当table的上层有多个overflow为auto的元素。如何指定粘性的元素，使得表格的头固定到指定的元素上，getContainer 不起作用

### What is expected?

使得表格的头固定到指定的元素上，

### What is actually happening?

sticky失效

| Environment | Info |
| --- | --- |
| antd | 4.24.3 |
| React | 16.8 |
| System | window |
| Browser | chrome |

**Comment by paywail** [comment]
具体原因是在滚动的元素和table-header之间还有overflow的元素，只有将中间的overflow元素移除，才可以触发sticky的效果；

**Comment by afc163** [comment]
我实测貌似没问题。

**Comment by paywail** [comment]
> 我实测貌似没问题。
我找到问题了，如果header需要被sticky，则需要保证header和滚动元素之间没有设置了overflow的元素。

**Comment by afc163** [comment]
所以问题可以关掉了？

**Comment by paywail** [comment]
> 我实测貌似没问题。

能否做到即使中间有overflow的元素也能sticky到指定的元素呢

**Comment by afc163** [comment]
> 能否做到即使中间有overflow的元素也能sticky到指定的元素呢

这个情况先给我一个重现？codesandbox 里貌似不存在这个情况。

**Comment by paywail** [comment]
> > 能否做到即使中间有overflow的元素也能sticky到指定的元素呢
> 
> 这个情况先给我一个重现？codesandbox 里貌似不存在这个情况。
codesandbox  有了, 问题应该是sticky会找到第一个有overflow的父级元素,进行sticky,但是其实有滚动条的不是这个元素导致不能sticky

**Comment by afc163** [comment]
我在你提供的 codesandbox 没有重现出不 sticky 的情况，最好先还原一下问题，我看看怎么解决。

![Oct-27-2023 15-42-21](https://github.com/ant-design/ant-design/assets/507615/a90b2cc5-e56f-461e-98b0-b6bd45fa409f)

**Comment by paywail** [comment]
> 我在你提供的 codesandbox 没有重现出不 sticky 的情况，最好先还原一下问题，我看看怎么解决。
> 
> ![Oct-27-2023 15-42-21](https://user-images.githubusercontent.com/507615/278571867-a90b2cc5-e56f-461e-98b0-b6bd45fa409f.gif) [ ![Oct-27-2023 15-42-21](https://user-images.githubusercontent.com/507615/278571867-a90b2cc5-e56f-461e-98b0-b6bd45fa409f.gif) ](https://user-images.githubusercontent.com/507615/278571867-a90b2cc5-e56f-461e-98b0-b6bd45fa409f.gif) [ ](https://user-images.githubusercontent.com/507615/278571867-a90b2cc5-e56f-461e-98b0-b6bd45fa409f.gif)

sorry,好了

**Comment by paywail** [comment]
![动画](https://github.com/ant-design/ant-design/assets/131888385/c2c62976-95f7-4c30-8113-aa3b9cf77a91)

**Comment by afc163** [comment]
懂了，sticky 是直接使用了原生 `position: sticky;` 来实现的。原生能力自带这个限制：https://www.cnblogs.com/coco1s/p/6402723.html

<img width="971" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/22262732-a7f7-418b-b352-d4c3225d032c">

所以这里 antd 可能没啥好办法。
