### ISSUE TITLE
Form.Item hasFeedback 与 addonAfter 冲突

### ISSUE THREAD

**Issue by Superman-wc** [ant-design/ant-design#4554]
#### Environment(required)

- antd version:2.6.0
- OS and its version: macOS
- Browser and its version: Chrome55
```
<Form.Item hasFeedback label="轮显时间" {...formLayout}  >
   {
      getFieldDecorator('duration', {})(<Input addonAfter="秒"/>)
   }
</Form.Item>
```
hasFeedback 的图标会遮羞 Input addonAfter 元素

**Comment by afc163** [comment]
对，hasFeedback 目前只支持裸的 Input，建议对于其他复杂表单控件，关闭掉。

**Comment by Superman-wc** [comment]
看来我只能用CSS单独控制一下了

**Comment by afc163** [comment]
有好的处理方式，也欢迎 PR 😄

**Comment by Superman-wc** [comment]
看过渲染后的元素， 最里边的<input /> 其实已经 padding-right:24px 是有空间留出来了的，但是 hasFeedback的图标是在外层的:after伪类上，定位上是在 input 父元素span上的， 而addonAfter 的span 是与input同级的 
那么可能就是 hasFeedback 这个东西要做放到input那里，这样动的刀子有点大，，呵呵， 目前好像就是用CSS单独控制一下
