### ISSUE TITLE
Ant Design "ConfigProvider" with design token "ColorBorder" test failed. 

### ISSUE THREAD

**Issue by KalanaPerera** [ant-design/ant-design#45546]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tender-pine-x675xk?file=/src/App.spec.js)

### Steps to reproduce

0. What we are trying to do is test the given <ConfigProvider> Theme token "colorBorder."
1. Goto the reproduction link.
2. Run the tests
3. The test will fail due to a mismatch in border color.

### What is expected?

expect given "colorBorder" value should match <Button>test</Button> border color.

### What is actually happening?

Returning "colorPrimary" instead of "colorBorder"

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | react |
| System | latest |
| Browser | latest |

---
Created stackoverflow question too..

**Comment by MadCcc** [comment]
Not `colorPriamry`, seems it remains `buttonface` in test, not sure what happened.

**Comment by KalanaPerera** [comment]
@MadCcc Thank you for the reply, Do you think is it possible to cover this test scenario, What are your suggestions/thoughts on this?

**Comment by MadCcc** [comment]
Seems `jsdom` didn't apply all styles to `getComputedStyle`, we can get proper style for other css properties:
![image](https://github.com/ant-design/ant-design/assets/27722486/8112d5c3-bb1b-44d5-bd88-2803a2d9ce08)
