### ISSUE TITLE
Typescript interface ModalFuncProps missing styles to replace bodyStyle

### ISSUE THREAD

**Issue by ka1** [ant-design/ant-design#45540]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/forked-antd-reproduction-template-modalfuncprops-f563n7)

### Steps to reproduce

1. Open reproduction link on code sandbox
2. Open the console
3. click on the button "click to reproduce"
4. Notice the deprecation warning "[antd: Modal] `bodyStyle` is deprecated. Please use `styles.body` instead."

### What is expected?

To resolve the deprecation warning, styles.body needs to be set. styles however is not part of the interface ModalFuncProps, while it exists on ModalProps in modal/interface.d.ts

### What is actually happening?

A deprecation warning is shown ("[antd: Modal] `bodyStyle` is deprecated. Please use `styles.body` instead.")

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | react 18.x |
| System | OSX 13 |
| Browser | Chrome 117 |

**Comment by ka1** [comment]
The same is true for the field "maskStyle", which is also deprecated and would need the "styles" field (styles.mask) to be replaced.

**Comment by Kimzify** [comment]
can I work on this issue?

**Comment by ka1** [comment]
This seems to be resolved with #45558 which also closed #45580
