### ISSUE TITLE
Tooltip组件作为Dropdown的子节点是报错

### ISSUE THREAD

**Issue by HanShuai-me** [ant-design/ant-design#45541]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-g4j46s?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

打开codebox

### What is expected?

如何避免这个控制台错误

### What is actually happening?

严格模式下Tooltip组件作为Dropdown的子节点时控制台报错
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2.0 |
| System | windows |
| Browser | edge |

**Comment by zombieJ** [comment]
Tooltip 的 ref 是 `operation`，不是 DOM。需要自行封装一下哈~

https://codesandbox.io/s/antd-reproduction-template-forked-3k4ffr?file=/index.js

**Comment by HanShuai-me** [comment]
虽然这样确实解决了问题，但是增加了使用成本

**Comment by raulmarindev** [comment]
Is the fix for this available in the last released version (5.10.3)? The warning is still there.

https://codesandbox.io/s/antd-reproduction-template-forked-4rzw6p

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/43064#issuecomment-1595739073

**Comment by wxs77577** [comment]
https://github.com/ant-design/ant-design/issues/43064#issuecomment-2456508430
