### ISSUE TITLE
The Select TagRender Property is opening the dropdown box when you click on close tag

### ISSUE THREAD

**Issue by oyungerel-chuluunsukh** [ant-design/ant-design#45554]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/late-cache-yknt8n)

### Steps to reproduce

In the <Select/> renderTag use <Tag/> to render tags make sure tag is closable and passes onClose and the type of the select is multiple.
Select some options from dropdown box.
Click on the x of the tag and the dropdown opens

### What is expected?

The dropdown should not open when you remove a selected tag

### What is actually happening?

The dropdown is opening when you remove a selected tag

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | react 18.0.0 |
| System | Ubuntu 22.04.3 LTS |
| Browser | Version 111.0.5563.64 (Official Build) (64-bit) |

**Comment by adanyal46** [comment]
use label inside tooltip to shwo information when tag hover and dont usr tagRender

**Comment by vova42matters** [comment]
> ![1713869248002](https://private-user-images.githubusercontent.com/153490837/324801416-cd778774-7d77-4197-bc8f-17f126132adc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODUwMzAsIm5iZiI6MTcxNzA4NDczMCwicGF0aCI6Ii8xNTM0OTA4MzcvMzI0ODAxNDE2LWNkNzc4Nzc0LTdkNzctNDE5Ny1iYzhmLTE3ZjEyNjEzMmFkYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxNTU4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGY3MjNkODA2ZjhkMDFkNzc0MmI3ZTg4YzAxOTk1M2E4OTE0ZjcxODg4YTJlMWEwNzhlODUxYTUyYzhhZmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D-8raW65Bw1GsUW_cNeuNxB-IvKx9lsZw5efEF1kqHc) yes, use stopPropagation is right, not click event, but mousedown event.

Works like a charm, thanks!
