### ISSUE TITLE
Dropdown 和Modal配合使用时 modal弹出后鼠标移到modal后 dropdown又展开了

### ISSUE THREAD

**Issue by echoyl** [ant-design/ant-design#45559]
### Reproduction link

[https://codesandbox.io/s/festive-glade-rfy7dn?file=/src/App.js](https://codesandbox.io/s/festive-glade-rfy7dn?file=/src/App.js)

### Steps to reproduce

dropdown 的item 是一个button组件 里面包含一个modal 点击item后modal弹出后鼠标快速移到modal层后 dropdown又会弹出

### What is expected?

不要弹出来

### What is actually happening?

额外弹出来了

效果图
![GIF 2023-10-27 17-59-48](https://github.com/ant-design/ant-design/assets/21699984/eaf21747-f9e2-439e-a30f-6c4cf6bc3d47)

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome版本 113.0.5672.127（正式版本） （64 位） |

**Comment by Wxh16144** [comment]
似曾相识的问题，看看是否和 https://github.com/ant-design/ant-design/issues/43860 类似🤔

**Comment by zombieJ** [comment]
给个 codesandbox 看看，这个应该是已经修过了。

**Comment by echoyl** [comment]
> 给个 codesandbox 看看，这个应该是已经修过了。

https://codesandbox.io/s/festive-glade-rfy7dn?file=/src/App.js

![Uploading GIF 2023-10-28 9-56-39.gif…]()
又截了个gif 鼠标没截到，重复弹出的概率还是很大的

**Comment by echoyl** [comment]
> 给个 codesandbox 看看，这个应该是已经修过了。

https://codesandbox.io/s/festive-glade-rfy7dn?file=/src/App.js

![GIF 2023-10-28 9-56-39](https://github.com/ant-design/ant-design/assets/21699984/69aa8b7b-8cc5-4f7a-9244-ce97f1d64331)
又截了个gif 鼠标没截到，重复弹出的概率还是很大的

**Comment by MadCcc** [comment]
复现不了，有没有必现的方法？

**Comment by afc163** [comment]
我这里 100% 重现。
![Nov-01-2023 19-35-04](https://github.com/ant-design/ant-design/assets/507615/7dfff5fa-9bea-42ef-ad22-b058d6e16d3e)

**Comment by echoyl** [comment]
> 复现不了，有没有必现的方法？

点击后鼠标快速移动到modal的位置

**Comment by skyfore** [comment]
> 同样的问题，我这边是在弹窗依然有的情况下鼠标移出浏览器再重新回到浏览器就会触发

升级 `@rc-component/trigger@1.18.2` 解决问题了，但是有点 hack，我是用 resolution 来解决的。
具体参考 https://github.com/ant-design/ant-design/issues/43813

**Comment by afc163** [comment]
https://codesandbox.io/p/sandbox/confident-bash-gy46y3?file=%2Fpackage.json

目测最新版本已经好了。

**Comment by echoyl** [comment]
> https://codesandbox.io/p/sandbox/confident-bash-gy46y3?file=%2Fpackage.json
> 
> 目测最新版本已经好了。

弹还是会弹 层级没那么高 显示在modal的下方影响不大
![modal](https://github.com/ant-design/ant-design/assets/21699984/b3dfaa1c-8fa3-4386-beb9-38202c8ffb15)
