### ISSUE TITLE
在 react 17 版本下 Select 控制台报错

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#45556]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-10-2-forked-v2cnrx?file=/demo.tsx)

### Steps to reproduce

查看控制台

### What is expected?

控制台不报错

### What is actually happening?

控制台报错

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
see https://github.com/ant-design/ant-design/issues/44994#issuecomment-1729070271
