### ISSUE TITLE
components/layout/demo显示异常

### ISSUE THREAD

**Issue by zerozaki0752** [ant-design/ant-design#4555]
目前components的[layout的demo](https://github.com/ant-design/ant-design/tree/master/components/layout/demo)似乎并不能如[官网中介绍](https://ant.design/components/layout-cn/)的那样显示。
className等一些元素都是缺失的，是我使用的方式不对吗？

**Comment by afc163** [comment]
提问要具体，不然不知道怎么回答。

建议按官方 issue 模板的格式。

**Comment by zerozaki0752** [comment]
@afc163
demo中的几个例子我把代码复制下 运行并没有达到官网中示例的效果
不知道用没有能够运行的demo呢？

**Comment by afc163** [comment]
建议按官方 issue 模板的格式，提供 antd 版本等信息。

**Comment by afc163** [comment]
你的 antd 版本是多少
