### ISSUE TITLE
Input.Search从2.6.0到2.6.1丢失了ant-input-search-wrapper这一层div?

### ISSUE THREAD

**Issue by iHearty** [ant-design/ant-design#4556]
Input.Search从2.6.0到2.6.1丢失了ant-input-search-wrapper这一层div?

**Comment by afc163** [comment]
是否这个问题：https://github.com/ant-design/ant-design/issues/4540

**Comment by afc163** [comment]
对的，详见：https://github.com/ant-design/ant-design/pull/4283#issuecomment-269728400
