### ISSUE TITLE
primary按钮样式会与tailwindcss样式冲突

### ISSUE THREAD

**Issue by PuddingJoker** [ant-design/ant-design#45560]
### Reproduction link

[https://ant.design/docs/react/use-with-create-react-app-cn](https://ant.design/docs/react/use-with-create-react-app-cn)

### Steps to reproduce

只要配置了tailwindcss中的 @tailwind base; 就会使primary按钮样式失效

### What is expected?

二者能兼容

### What is actually happening?

primary按钮蓝色背景失效

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 17.0.2 |
| System | mac m2 |
| Browser | chrome |

**Comment by yoyo837** [comment]
tailwindcss 自带的 modern-normalize样式, 从 `https://github.com/tailwind base;`的位置注入, 根据样式的引入顺序产生不同的覆盖或者被覆盖的效果, 你可以考虑禁用 `preflight`, 或者调整样式引入顺序. 在antd之前? 还是之后?

https://tailwindcss.com/docs/preflight

**Comment by PuddingJoker** [comment]
> tailwindcss 自带的 modern-normalize样式, 从 `@tailwind base`的位置注入, 根据样式的引入顺序产生不同的覆盖或者被覆盖的效果, 你可以考虑禁用 `preflight`, 或者调整样式引入顺序. 在antd之前? 还是之后?
> 
> https://tailwindcss.com/docs/preflight

最新的antd这边都是cssinjs了 没有引入css文件

**Comment by yoyo837** [comment]
它是cssinjs, 不是没有css

**Comment by PuddingJoker** [comment]
怎么调整顺序都不行 只有 primary button样式失效

**Comment by yoyo837** [comment]
你先试试关掉 preflight 能不能解决?

**Comment by yoyo837** [comment]
另外, 你最好给个复现.

**Comment by yoyo837** [comment]
https://ant.design/docs/react/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by PuddingJoker** [comment]
> https://ant.design/docs/react/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8

解决了 非常感谢

**Comment by delfws** [comment]
这是个很蛋疼的问题，涉及到了css选择器的优先级。

我希望的理想条件下是根据 [关闭 hash - Ant Design](https://ant-design.antgroup.com/docs/react/css-variables-cn#%E5%85%B3%E9%97%AD-hash) 去掉 `hash` ，然后我还可以在 `antd` 组件的基础上添加类似于 `className="text-white"` 来修改某个组件的样式，但是这样有一个问题，他仍然不能覆盖掉 `tailwind` 的基础样式，解决办法就是将 `tailwind` 的基础样式提前（但是我不会😅）

![image](https://github.com/ant-design/ant-design/assets/24715927/6083a0fb-39fc-4bdd-9023-31b691f03c4e)


所以我不得不妥协，我的解决方案是根据 [:where 选择器 - Ant Design](https://ant-design.antgroup.com/docs/react/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8) 添加 `hashPriority="high"` ，然后根据 [selector-strategy - Tailwind CSS](https://tailwindcss.com/docs/configuration#selector-strategy) 添加 `important: '#root'` ，这样就可以折中实现我想要的方式，只是一点都不酷...

**Comment by knight174** [comment]
https://github.com/ant-design/ant-design/discussions/41858
