### ISSUE TITLE
Antd with Next 14, UI is flickering despite @ant-design/cssinjs

### ISSUE THREAD

**Issue by pavelee** [ant-design/ant-design#45567]
### Reproduction link

[https://github.com/pavelee/next14-antd-reproduce-flickery](https://github.com/pavelee/next14-antd-reproduce-flickery)

### Steps to reproduce

refresh page to notice UI filckery

### What is expected?

It should work like with Next 13.5.6 without UI flickering when using @ant-design/cssinjs
Described here: https://ant.design/docs/react/use-with-next

### What is actually happening?

UI is flickering

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2 |
| System | MacOS Sonoma |
| Browser | Latested Chrome |

---
With Next 13.5.6 it works as expected, the problem exists with latest Next 14

**Comment by zhnd** [comment]
I also encountered the same problem.

**Comment by sfsajid91** [comment]
I have also faced this problem.

**Comment by zzkaqq** [comment]
我也遇到了同样的问题

**Comment by MadCcc** [comment]
Since Nextjs 14 didn't mention any breaking change in changelog or docs, this may be a problem with this major version.

Possible issue could trace: https://github.com/vercel/next.js/issues/57694

**Comment by nthieu1332002** [comment]
same here

**Comment by killthecreator** [comment]
Same issue. Everything was working fine before antd update to >5.10.0

**Comment by MadCcc** [comment]
Finally find why... Nextjs import `antd` from 'antd/lib' by default, and import `@ant-design/cssinjs` from `@ant-design/cssinjs/es`, which will cause context is not the same.

Current workaround: 

```ts
-- import { extractStyle } from '@ant-design/cssinjs';
++ import { extractStyle } from '@ant-design/cssinjs/lib';
```

**Comment by TimonPeng** [comment]
> Finally find why... Nextjs import `antd` from 'antd/lib' by default, and import `@ant-design/cssinjs` from `@ant-design/cssinjs/es`, which will cause context is not the same.
> 
> Current workaround:
> 
> ```diff
> -- import { createCache, extractStyle } from '@ant-design/cssinjs';
> ++ import { createCache, extractStyle } from '@ant-design/cssinjs/lib';
> ```

thanks it's works for me!

**Comment by nthieu1332002** [comment]
> Finally find why... Nextjs import `antd` from 'antd/lib' by default, and import `@ant-design/cssinjs` from `@ant-design/cssinjs/es`, which will cause context is not the same.
> 
> Current workaround:
> 
> ```diff
> -- import { createCache, extractStyle } from '@ant-design/cssinjs';
> ++ import { createCache, extractStyle } from '@ant-design/cssinjs/lib';
> ```

Thank you!

**Comment by pavelee** [comment]
> Finally find why... Nextjs import `antd` from 'antd/lib' by default, and import `@ant-design/cssinjs` from `@ant-design/cssinjs/es`, which will cause context is not the same.
> 
> Current workaround:
> 
> ```diff
> -- import { createCache, extractStyle } from '@ant-design/cssinjs';
> ++ import { createCache, extractStyle } from '@ant-design/cssinjs/lib';
> ```

Thank you! 🙏🙏🙏

I prepared PR with docs update, not sure when we could expect to solve this issue in next.js

**Comment by li-jia-nan** [comment]
- https://github.com/vercel/next.js/pull/57947

**Comment by ondery** [comment]
-- import { createCache, extractStyle } from '@ant-design/cssinjs';
++ import { createCache, extractStyle } from '@ant-design/cssinjs/lib';

When I changed with "lib" folder, now, it starts to import <style id="antd"> multiple times... :((

<img width="531" alt="image" src="https://github.com/ant-design/ant-design/assets/7957487/31ef85ff-a15a-4058-affe-1d5973f9976c">

**Comment by arvinxx** [comment]
a better solution by @Asanio06 ,which don't need to modify source code:

https://github.com/lobehub/lobe-chat/pull/434/commits/a689b96ff244a548ad92c00692c469effc4c525f

```js
// next.config.js
webpack(config) {
    config.resolve.alias['@ant-design/cssinjs'] = '@ant-design/cssinjs/lib';

    return config;
  },
```

**Comment by ondery** [comment]
> a better solution by @Asanio06 ,which don't need to modify source code:
> 
> ```js
> // next.config.js
> webpack(config) {
>     config.resolve.alias['@ant-design/cssinjs'] = '@ant-design/cssinjs/lib';
> 
>     return config;
>   },
> ```
> 
> refs: [lobehub/lobe-chat@a689b96](https://github.com/lobehub/lobe-chat/commit/a689b96ff244a548ad92c00692c469effc4c525f)

It still keeps adding <style id="antd"> to <body> many times.

**Comment by ondery** [comment]
> a better solution by @Asanio06 ,which don't need to modify source code:
> 
> ```js
> // next.config.js
> webpack(config) {
>     config.resolve.alias['@ant-design/cssinjs'] = '@ant-design/cssinjs/lib';
> 
>     return config;
>   },
> ```
> 
> refs: [lobehub/lobe-chat@a689b96](https://github.com/lobehub/lobe-chat/commit/a689b96ff244a548ad92c00692c469effc4c525f)

It still keeps adding <style id="antd"> to body many times.

**Comment by arvinxx** [comment]
@ondery how about try with `antd-style`?

refs: https://github.com/lobehub/lobe-chat/blob/main/src/app/StyleRegistry.tsx
```tsx
'use client';

import { StyleProvider, extractStaticStyle } from 'antd-style';
import { useServerInsertedHTML } from 'next/navigation';
import { PropsWithChildren, useRef } from 'react';

const StyleRegistry = ({ children }: PropsWithChildren) => {
  const isInsert = useRef(false);

  useServerInsertedHTML(() => {
    // avoid duplicate css insert
    // refs: https://github.com/vercel/next.js/discussions/49354#discussioncomment-6279917
    if (isInsert.current) return;

    isInsert.current = true;

    // @ts-ignore
    return extractStaticStyle().map((item) => item.style);
  });

  return <StyleProvider cache={extractStaticStyle.cache}>{children}</StyleProvider>;
};

export default StyleRegistry;
```

**Comment by ondery** [comment]
> @ondery how about try with `antd-style`?
> 
> refs: https://github.com/lobehub/lobe-chat/blob/main/src/app/StyleRegistry.tsx
> 
> ```tsx
> 'use client';
> 
> import { StyleProvider, extractStaticStyle } from 'antd-style';
> import { useServerInsertedHTML } from 'next/navigation';
> import { PropsWithChildren, useRef } from 'react';
> 
> const StyleRegistry = ({ children }: PropsWithChildren) => {
>   const isInsert = useRef(false);
> 
>   useServerInsertedHTML(() => {
>     // avoid duplicate css insert
>     // refs: https://github.com/vercel/next.js/discussions/49354#discussioncomment-6279917
>     if (isInsert.current) return;
> 
>     isInsert.current = true;
> 
>     // @ts-ignore
>     return extractStaticStyle().map((item) => item.style);
>   });
> 
>   return <StyleProvider cache={extractStaticStyle.cache}>{children}</StyleProvider>;
> };
> 
> export default StyleRegistry;
> ```

thank you... It really resolve the problem...

**Comment by pavelee** [comment]
I notice that with Next.js 14.0.2 problem was fixed 🥳, so we can revert trick with _@ant-design/cssinjs/lib_

Anyone else could confirm the fix? 

If it is fixed for everyone, i will revert change in docs

**Comment by ondery** [comment]
Yes, with Next.js 14.0.2, the "lib" folder problem has been resolved; but still duplicate (or mulitple times) import problem continuing. You can use @arvinxx's solution.

**Comment by fkysly** [comment]
> Yes, with Next.js 14.0.2, the "lib" folder problem has been resolved; but still duplicate (or mulitple times) import problem continuing. You can use @arvinxx's solution ([#45567 (comment)](https://github.com/ant-design/ant-design/issues/45567#issuecomment-1803179108)).

@pavelee I combine the cssinjs solution and isInsert solution, it works fine on v14.0.2.

```tsx
'use client';

import React, { useRef } from 'react';
import { createCache, extractStyle, StyleProvider } from '@ant-design/cssinjs';
import type Entity from '@ant-design/cssinjs/es/Cache';
import { useServerInsertedHTML } from 'next/navigation';

const StyledComponentsRegistry = ({ children }: React.PropsWithChildren) => {
  const cache = React.useMemo<Entity>(() => createCache(), []);
  const isInsert = useRef(false);

  useServerInsertedHTML(() => {
    // avoid duplicate css insert
    // refs: https://github.com/vercel/next.js/discussions/49354#discussioncomment-6279917
    if (isInsert.current) return;
    isInsert.current = true;

    return <style id="antd" dangerouslySetInnerHTML={{ __html: extractStyle(cache, true) }} />
  }

  );
  return <StyleProvider cache={cache}>{children}</StyleProvider>;
};

export default StyledComponentsRegistry;
```

**Comment by li-jia-nan** [comment]
> @pavelee I combine the cssinjs solution and isInsert solution, it works fine on v14.0.2.

好办法！

**Comment by jknap** [comment]
I followed the latest docs but I am still able to reproduce this issue.

I managed to reproduce here https://github.com/jknap/antd-demo/tree/main

- `npx create-next-app antd-demo`
- `npm install antd --save`
- `npm install @ant-design/cssinjs --save`
(use App Router)
- create `lib/AntdRegistry.tsx`
- Use it in `app/layout.tsx`

It works the first time.
Now if you delete the `node_modules` and run `npm install` again, then you can reproduce.
Downgrading to next@13.5.6 does not solve the issue in this case.

It seems that the cache returned by `createCache` is empty in this case.
I noticed that when the cache is not empty, [this method](https://github.com/ant-design/cssinjs/blob/92dce00796e2644dad391b49ec1def849329234a/src/Cache.ts#L19) is called multiple times, and it's never called when the issue is reproduced.
I am not sure what is triggering it so I could not dig more unfortunately, but the issue seems to come from there.

**Comment by jknap** [comment]
> I followed the latest docs but I am still able to reproduce this issue.
> 
> I managed to reproduce here https://github.com/jknap/antd-demo/tree/main
> 
> * `npx create-next-app antd-demo`
> * `npm install antd --save`
> * `npm install @ant-design/cssinjs --save`
>   (use App Router)
> * create `lib/AntdRegistry.tsx`
> * Use it in `app/layout.tsx`
> 
> It works the first time. Now if you delete the `node_modules` and run `npm install` again, then you can reproduce. Downgrading to next@13.5.6 does not solve the issue in this case.
> 
> It seems that the cache returned by `createCache` is empty in this case. I noticed that when the cache is not empty, [this method](https://github.com/ant-design/cssinjs/blob/92dce00796e2644dad391b49ec1def849329234a/src/Cache.ts#L19) is called multiple times, and it's never called when the issue is reproduced. I am not sure what is triggering it so I could not dig more unfortunately, but the issue seems to come from there.

Ok I found the issue, it was due to a mismatch between the `@ant-design/cssinjs` version and the one that antd depends on.
This can be fixed by forcing the same `@ant-design/cssinjs` version in package.json.
This is mentioned in the doc => https://ant.design/docs/react/use-with-next#using-app-router
