### ISSUE TITLE
disabled 与 initialValue 问题

### ISSUE THREAD

**Issue by wboykron** [ant-design/ant-design#4557]
#### Environment(required)

- antd version:2.6.0
- OS and its version:mac os
- Browser and its version:chrome浏览器

#### What did you do? Please provide steps to re-produce your problem.
升级了antd版本号

#### What do you expected?
设置disable后，initialValue会设置初始化值，或者通过设置什么让他form表单不能编辑

#### What happen?
升级antd版本后，disabled 与 initialValue不能共存，只是显示不能点击的效果

#### Re-producible online demo

{getFieldDecorator('XN',{
          initialValue:editRecord?editRecord.XN:'',
          rules: [{ required:true,type: 'string', message: '请输入关键字' },{ validator: _numberExists}],
          })(<Input placeholder="XXX" disabled={editRecord?true:false}/>)}

**Comment by afc163** [comment]
说实话，看不太懂。。

**Comment by wboykron** [comment]
当我点击编辑的时候，有些输入框可能是需要付初值，但是不能对它进行编辑，如下代码：{getFieldDecorator('Zhuanye', {
                    initialValue:editRecord?[editRecord.XYMC,editRecord.ZYMC]:[],
                    rules: [{ required:editRecord?true:false,type: 'array', message: '请输入关键字' }],
                  })(
                    <Cascader placeholder="专业选择查询" options={options} disabled={editRecord?true:false}/>
                  )}，现在是，disable起作用了，但是initalValue就为空。

**Comment by afc163** [comment]
initialValue 和 defaultValue 一样，只有第一次渲染会生效，后续表单值的变化需要用  `form.setFieldValue` 进行设置。

http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by wboykron** [comment]
那为什么原来的版本是可以的尼，升级antd版本后就出现错误了！
