### ISSUE TITLE
drawer中嵌套class component使用getComputedStyle(ref.current)异常

### ISSUE THREAD

**Issue by AlanQtten** [ant-design/ant-design#45588]
### Reproduction link

[https://github.com/AlanQtten/antd-error](https://github.com/AlanQtten/antd-error)

### Steps to reproduce

pnpm install 
pnpm dev
查看打印

### What is expected?

对于drawer中嵌套的函数组件和类组件，使用getComputedStyle(ref.current)可以获取一致的结果

### What is actually happening?

对于drawer中嵌套的函数组件和类组件，使用getComputedStyle(ref.current)获取了不一致的结果

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2.0 |
| System | macos ventura 13.0  |
| Browser | Chrome 114.0.5735.133 |

---
drawer中嵌套的类组件，在componentDidMount里面可以访问到dom，但使用getComputedStyle(ref.current).position时获取到了一个空串，似乎dom并没有真实被挂载？
补充：drawer中嵌套的函数组件或者不使用drawer包裹的该组件均表现正常

**Comment by zombieJ** [comment]
在 React 18 里由于 Suspence 可能会多次重复创建组件，要求所有的状态都需要通过 state 管理。

所以为了支持 React 18，把原本 render 阶段创建节点，改成了在 Effect 中创建节点（因为 render 阶段创建的节点遇到 Suspence 的多次创建是回收不了的）。而在 class component 中，did 总是会比 Effect 慢所以可以拿到内容。而 function component 则因为都是 Effect 就会有竞态问题。

这个可以加个计数器叠两次 Effect 来确保 Drawer 创建了节点来获取。
