### ISSUE TITLE
Icon组件不触发onClick事件问题

### ISSUE THREAD

**Issue by Sharang-heng** [ant-design/ant-design#45587]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-tu-biao-antd-4-24-12-forked-lm94gq?file=/demo.tsx)

### Steps to reproduce

多次点击过滤器Icon

### What is expected?

成功触发onClick事件

### What is actually happening?

onMouseDown和onMouseUp均触发成功，但onClick事件触发失败

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 17.0.2 |
| System | window |
| Browser | Chrome |

**Comment by afc163** [comment]
So weired: https://codesandbox.io/s/zi-ding-yi-tu-biao-antd-4-24-12-forked-9ydv36?file=/demo.tsx

**Comment by Sharang-heng** [comment]
> So weired: https://codesandbox.io/s/zi-ding-yi-tu-biao-antd-4-24-12-forked-9ydv36?file=/demo.tsx

这个问题我遇到过两次，一次是在Input的suffix使用自定义Icon时出现过，另外一次是在dropdown中使用单独的Icon使用是没有问题的，但是配合其他组件使用且涉及到状态管理的时会出现这个问题，我提供的demo已经是我能复现的最小demo了

**Comment by Wxh16144** [comment]
5 也有这个问题😰

**Comment by Wxh16144** [comment]
我看了一眼你的 demo， 既然 Dropdown 都已经用 open 受控了为什么还需要设置 trigger 来触发点击打开呢？ 结合上面偏右大佬的示例来看，应该是错误的使用方式导致的 bug？

**Comment by afc163** [comment]
我给的例子也是有问题的，这个问题看上去和 Dropdown 没关系，Icon 本身就有问题。

**Comment by afc163** [comment]
我知道了 component 不能写成 inline 的方式，否则每次 rerender 都是一个新的组件，会导致整个组件整体重新渲染。拿到外面定义即可：

https://codesandbox.io/s/zi-ding-yi-tu-biao-antd-4-24-12-forked-3g2g69?file=/demo.tsx
https://codesandbox.io/s/zi-ding-yi-tu-biao-antd-4-24-12-forked-d6xp7f?file=/demo.tsx

我也更新一下官网演示代码。
