### ISSUE TITLE
Tabs在map后的TabPane中，无法默认选中第一项BUG

### ISSUE THREAD

**Issue by Liuqing650** [ant-design/ant-design#4558]
tabs组件直接return(  <Tabs defaultActiveKey="1"> .... </Tabs> )没有问题， defaultActiveKey没有的时候也会默认选中第一个。当在
```jsx
         const TabPane = Tabs.TabPane;
         const logTagTest = list.map((item) => {
	 return <TabPane tab={item.name} key={item.id}>
				{item.value}
			</TabPane>
	}) 
	return (<Tabs > {logTagTest} </Tabs> )
```
页面就只有tab名了，不会默认选中第一个，看起来一片空白
[问题效果图](http://123.207.100.248/mabylove/error/images/bug-tabs.png)
不知道这算不算个BUG，或者是这样写很不规范吗？
defaultActiveKey在models中初始化值的时候如果给了值是可以出现指定选项内容的，但在reducers中给的值无效，只有初始化的值有效。也就是组件渲染出来只用了第一次获取的值，第二次的没用到，但是不指定同样没有效果。

- antd version: ^2.5.3
- dva: "1.0.0"
- Browser and its version: chrome

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by yesmeck** [comment]
@Liuqing650  我没重现出来，给个在线的可重现演示吧 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Liuqing650** [comment]
@yesmeck 可能我说复杂了，其实就是在Tabs中使用通过map出的一堆<TabPane> .... </TabPane>标签页，defaultActiveKey不设置的时候，没有打开默认的首个标签页

**Comment by yesmeck** [comment]
对的，没重现出来，说那么多不如给重现。

**Comment by Liuqing650** [comment]
@yesmeck 感谢你提供的编辑器，真心用不来，初入前端的原因，所以打算写个demo给你们，不过刚刚在本地重新写的时候，发现了这个问题的所在，我是用的dva-cli，页面渲染的时候，会进行两次取值，第一次组件取的model中初始化的值，这个时候是空的，所以默认的选项为空，选不到第一个，第二次数据获取到的时候，页面的默认显示标签页已经为空了。所以无法显示首个标签页，当我在组件中定义好了数据，或则初始化的时候已经设定好了数据，就没有问题，这个时候渲染本身就有值。

只是这种情况还真不知道如何解决

**Comment by yesmeck** [comment]
值会变化的话应该用 `value` 去控制，不是 antd 的问题就关闭了。

**Comment by qianduanMortal** [comment]
遇到了同样的问题。可能是我们的用法不对吧。
