### ISSUE TITLE
[watermark]: wrong text and background color when switches themes

### ISSUE THREAD

**Issue by cc-hearts** [ant-design/ant-design#45596]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6wt58q?file=/index.js)

### Steps to reproduce

1. click button toggle dark theme

### What is expected?

adaptive text color and background color for watermarks in black theme.

### What is actually happening?

in the black theme, the background color and text color of the watermark are white.

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18 |
| System | MacOs 13.2.1 |
| Browser | Chrome  118.0.5993.88 |

**Comment by zombieJ** [comment]
It's by design. Watermark do not provide the background color. It's only provide the text mask instead to avoid block background has image case. You should use layout if need background instead:

https://codesandbox.io/s/antd-reproduction-template-forked-nt2zl9?file=/index.js

**Comment by cc-hearts** [comment]
thx
