### ISSUE TITLE
Input输入框支持tooltips查看全部输入内容

### ISSUE THREAD

**Issue by rriwen** [ant-design/ant-design#45597]
### What problem does this feature solve?

输入框宽度比较小的时候想看全已经输入的内容。
希望激活时 超出输入框宽度内容后 浮层显示已输入的全部内容，以及失焦后鼠标悬停能看到已输入的全部内容

### What does the proposed API look like?

-

**Comment by afc163** [comment]
自行封装一个即可：https://ant.design/components/input-cn#components-input-demo-tooltip
