### ISSUE TITLE
[Button] Customization for 'box-shadow' doesn't work

### ISSUE THREAD

**Issue by ko2in** [ant-design/ant-design#45594]
### Reproduction link

[https://codepen.io/kokozin/pen/ExrKZbK](https://codepen.io/kokozin/pen/ExrKZbK)

### Steps to reproduce

Open the CodePen above. The button is customized with ConfigProvider. The button is not able to remove 'box-shadow' as seen in the codepen.

### What is expected?

The button 'box-shadow' should be set to 'none'.

### What is actually happening?

The button still has 'box-shadow: 0 2px 0 rgba(5, 145, 255, 0.1)'

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18 |
| System | All |
| Browser | All |

**Comment by MadCcc** [comment]
Button didn't use `boxShadow`, please try `primaryShadow` or `defaultShadow`.

**Comment by ko2in** [comment]
That works. Thanks.
