### ISSUE TITLE
IE8 报错

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#456]
在 IE8 会抛出 `ERR_ACCESSORS_NOT_SUPPORTED`。

定位后，发现编译后的代码使用了 `Object.defineProperty`，而在 IE8 上面，是无法 shim 出这个方法的，所以现在的情况是，在 IE8 打开 ant.design 都会报这个错。

**Comment by benjycui** [comment]
其实，以 antd 的定位，是否该放弃对 IE8/9 的支持？

**Comment by afc163** [comment]
目前无法放弃。

**Comment by afc163** [comment]
https://github.com/facebook/react/issues/5323

**Comment by afc163** [comment]
react@0.14.2 已经发布了。
