### ISSUE TITLE
[Image] wrapClassName is deprecated, please use classNames instead

### ISSUE THREAD

**Issue by lanten** [ant-design/ant-design#45600]
### Reproduction link

[https://github.com/](https://github.com/)

### Steps to reproduce

Image组件弹出预览框时控制台出现该警告
![image](https://github.com/ant-design/ant-design/assets/16203518/aeed3d49-5fc7-402d-a582-303dcbdc7ac4)

### What is expected?

没有警告

### What is actually happening?

获得警告

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18 |
| System | windows |
| Browser | any |

---
该问题至少已经存在了两个版本

警告似乎来自：
https://github.com/react-component/dialog/blob/master/src/Dialog/index.tsx#L55

**Comment by MadCcc** [comment]
Fixed in https://github.com/react-component/image/pull/285

**Comment by Wxh16144** [comment]
https://github.com/react-component/image/pull/285 这个问题修复了？
