### ISSUE TITLE
modal 下的 “确定” 和 “取消” 包裹 a 标签会有失效问题

### ISSUE THREAD

**Issue by xQuotes** [ant-design/ant-design#4560]
#### Environment(required)

- antd version: xxx
- OS and its version: mac
- Browser and its version:  firefox

#### What did you do? Please provide steps to re-produce your problem.

[firefox button 包裹 a 标签失效的问题](https://segmentfault.com/q/1010000000155827)

#### What do you expected?

modal 下的 “确定” 和 “取消” 包裹 a 标签会有失效问题

建议 [Modal](https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx#L126) 下的 “确定” 和 “取消” 外层不用`Button`包裹

**Comment by afc163** [comment]
http://stackoverflow.com/questions/802839/button-inside-of-anchor-link-works-in-firefox-but-not-in-internet-explorer/802876#802876

按照 HTML 规范，Button 不应该内嵌其他可点击元素。Firefox 应该是比较严格的实现了规范。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3085#issuecomment-248213729

**Comment by xQuotes** [comment]
嗯，谢谢～
重写 [footer props](https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx#L148)  可以解决`button`内嵌的问题～
