### ISSUE TITLE
Form creates duplicate html ids on a page when inputs have the same name, even though they are in different forms

### ISSUE THREAD

**Issue by rjroos** [ant-design/ant-design#45606]
### Reproduction link

[https://codepen.io/rjroos/pen/yLZJNGE](https://codepen.io/rjroos/pen/yLZJNGE)

### Steps to reproduce

Create a page with 2 antd forms. Add a Form.Item to both forms with the same name.

### What is expected?

If I click the label, the input of the correct form should focus.

### What is actually happening?

The first input always focusses, even though I clicked the second form. This is due to <label htmlFor={id} /> and the duplicate id attribute in the page.

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2.0 |
| Browser | Firefox |

**Comment by MadCcc** [comment]
Please give unique `name` to Form.Item in Form

**Comment by rjroos** [comment]
Thank you for your followup. And compliments for the great library!

I found a fix for my problem. It is possible to override the generated id for the <input/>. Leaving it here as a comment for the next reader.

This works for me:

```
<div id="city">This div is outside of my control and gets id=city</div>
<Form>
  <Form.Item name="city" htmlFor="use_this_as_id_for_the_city_input">
    <Input id="use_this_as_id_for_the_city_input"/>
  </Form>
</Form>
```

**Comment by afc163** [comment]
You need a a unique name to Form, not Form.Item.

```diff
-     <Form>
+     <Form name="Goldfish-form">
        <h1>Goldfish</h1>
        <Form.Item label="Dangerous" name="dangerous">
          <Checkbox />
        </Form.Item>
      </Form>
-     <Form>
+     <Form name="Lion-form">
        <h1>Lion</h1>
        <Form.Item label="Dangerous" name="dangerous">
          <Checkbox />
        </Form.Item>
      </Form>
```

**Comment by rjroos** [comment]
Thank you, that's much better!
