### ISSUE TITLE
需要导出Tabs 组件的类型声明  TabItemType 

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#45601]
### Reproduction link

[https://ant-design.antgroup.com/components/tabs#tabitemtype](https://ant-design.antgroup.com/components/tabs#tabitemtype)

### Steps to reproduce

无

### What is expected?

无

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | chrome |
| Browser | chrome |

**Comment by zombieJ** [comment]
[FAQ: 如何获取未导出的属性定义](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E6%9C%AA%E5%AF%BC%E5%87%BA%E7%9A%84%E5%B1%9E%E6%80%A7%E5%AE%9A%E4%B9%89)

Prop 定义都可以通过 `ComponentProps['PropName']` 获取哈~

**Comment by MadCcc** [comment]
`Exclude<TabsProps['items'], undefined>[number]`
