### ISSUE TITLE
5.10.3版本webpack打包会报错，看依赖是少了文件

### ISSUE THREAD

**Issue by gary-zhu** [ant-design/ant-design#45619]
### Reproduction link
(https://github.com/ant-design/ant-design/assets/46038375/14cfc8b5-b418-4a8b-a2f9-f69e0dea223c)
![image_2023_11_01T10_58_13_129Z](https://github.com/ant-design/ant-design/assets/46038375/92d4c3d2-63e3-4084-ab26-89d6e52bf207)

[https://ant.design/components/auto-complete-cn](https://ant.design/components/auto-complete-cn)

### Steps to reproduce

项目中使用AutoComplete组件然后用webpack打包会报错Module not found: Error: Can't resolve 'antd/lib/auto-complete/style'

### What is expected?

antd依赖中antd/lib/auto-complete路径下应该有style文件

### What is actually happening?

antd依赖中antd/lib/auto-complete路径下应该有style文件

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome |

**Comment by gary-zhu** [comment]
5.10.3版本webpack打包会报错，node_modules/antd/lib/auto-complete 路径下面缺少style文件

**Comment by gary-zhu** [comment]
5.10.3版本webpack打包会报错，node_modules/antd/lib/auto-complete 路径下面缺少style文件

**Comment by zombieJ** [comment]
关掉 `babel-plugin-import`，v5 里 AutoComplete 一直是没有 `style` 路径的。

**Comment by gary-zhu** [comment]
> 关掉 `babel-plugin-import`，v5 里 AutoComplete 一直是没有 `style` 路径的。

好的多谢多谢
