### ISSUE TITLE
RangePicker 交互优化

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4561]
<del>1.单击某一天，则认为是选择了开始和结束都是同一天的 range:</del>

![image](https://cloud.githubusercontent.com/assets/3580607/21834506/8443060e-d7f0-11e6-843f-92dd62c0ae56.png)

1. 对于有预设范围的情况，点击某个预设范围后，日期面板调整为选中的日期：

![image](https://cloud.githubusercontent.com/assets/3580607/21834558/dde17de4-d7f0-11e6-9531-32b5a92a93b5.png)

**Comment by afc163** [comment]
<img width="523" alt="image" src="https://cloud.githubusercontent.com/assets/507615/21834960/1b99e308-d7f4-11e6-92a0-ae6d68d1f3fc.png">

最下方多了一条边框。
