### ISSUE TITLE
sync update of 'rc-select' version

### ISSUE THREAD

**Issue by topazur** [ant-design/ant-design#45617]
### Reproduction link

[https://github.com/react-component/select/releases/tag/v14.10.0](https://github.com/react-component/select/releases/tag/v14.10.0)

### Steps to reproduce

Implement optionRender API

### What is expected?

use optionRender API 

### What is actually happening?

can't use optionRender API 

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | react |
| System | MacOS |
| Browser | Chrome |

---
update version

**Comment by zombieJ** [comment]
It's already synced in feature branch.

**Comment by yoyo837** [comment]
See https://github.com/ant-design/ant-design/pull/45529

**Comment by topazur** [comment]
Thank you！👍

**Comment by davidhsing** [comment]
@zombieJ 大佬，请问 antd 4.x 系列有希望能加入新版 rc-select 这个 optionRender 选项吗？

**Comment by yoyo837** [comment]
4.x 不会再新增新特性了。
