### ISSUE TITLE
Table scroll x doesn't work correctly inside Space

### ISSUE THREAD

**Issue by The-Fireplace** [ant-design/ant-design#45610]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jzxjhp)

### Steps to reproduce

1. Create a Table with the scroll prop
2. Assign an x value wider than the page width to scroll.x
2. Put the Table inside a Space

### What is expected?

The table can scroll along the x axis just like it does outside of a Space

### What is actually happening?

The table sticks out and the page becomes as wide as the table

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2 |
| System | Windows 11, MX Linux |
| Browser | Firefox 119, Vivaldi 6.4.3160.34 |

**Comment by zombieJ** [comment]
Space component is inline layout which will wrap element to hold the content. Use Flex component instead: https://codesandbox.io/s/antd-reproduction-template-forked-6hnccm?file=/index.js
