### ISSUE TITLE
Form input losing focus after first character entered with hasFeedback

### ISSUE THREAD

**Issue by kiwikencox** [ant-design/ant-design#45612]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-validation-antd-5-10-3-forked-2xmft3?file=/demo.tsx)

### Steps to reproduce

Create a form item with "InputNumber" and item props "hasFeedback" with a required rule, WITH "name", and WITHOUT "validateStatus".
In this instance you get a form item with a red asterisk (as required) and no validation indicator shown yet.

### What is expected?

The input shouldn't lose focus when the validation indicator first appears and should be able to enter more than one character.

### What is actually happening?

When you start typing in the input after you enter the first character the validation indicator appears and the input loses focus so you can't enter any more characters without giving the input focus again.  (This was picked up in our unit tests after migrating to v5).
Note once the validation indicator is there everything works as expected.
Note removing the "name" prop seems to fix the issue in terms of entering multiple characters, though it also results in the red asterisk not showing and the validation indicator not showing?

Here the form items are identical except one has the name prop set.
![changes](https://github.com/ant-design/ant-design/assets/3982837/fc55daba-4116-4a2a-8c55-581a477e5e74)

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome Version 119.0.6045.106 (Official Build) (64-bit) |

**Comment by MadCcc** [comment]
`feedback` is implemented with `suffix`, which will change dom structure of Input so that it will lose focus.
We should keep it stable in Form.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/34458#issuecomment-1813044320

@MadCcc 这个问题貌似还在。

**Comment by MadCcc** [comment]
> [#34458 (comment)](https://github.com/ant-design/ant-design/issues/34458#issuecomment-1813044320)
> 
> @MadCcc 这个问题貌似还在。

这个要在 4.x 上修复下

**Comment by douglasjunior** [comment]
Why this issue and #34458 are closed?

The problem still happening after 7 months, please let's keep track on this.

**Comment by zombieJ** [comment]
Hi @douglasjunior,

For v4 is no longer maintained. For v5, you're welcome to open a new issue.

Closed issues were marked as resolved at their time, yet new issues might have emerged or perhaps the resolution at the time was incorrect. Initiating a new issue also facilitates more effective problem tracking.

**Comment by douglasjunior** [comment]
Hi @zombieJ, thank you for your reply!

I understand your point, but this issue here is related to v5, not v4, and also is closed. 😓

**Comment by douglasjunior** [comment]
In fact, I forgot to mention that today this workaround is documented.

https://ant.design/components/input#why-input-lose-focus-when-change-prefixsuffixshowcount

But in my opinion, this is the type of problem that is not obvious and complete breaks the dev experience.  As a long time Antd lover, wold be nice to contribute with this fix.

**Comment by huynhvequyen** [comment]
In case anyone is also facing this issue. In antd version 5.37.1 I'm having same error but with <Input> too.

The workaround by removing **name** prob works just like @kiwikencox  said, and it doesn't show red asterisk.

The workaround by adding empty `span` mentioned by @douglasjunior also works, but it requires ALL <Input> to add the same which is kinda frustrating and unnecessary.

` <Input suffix={<span/>}/>`

**Comment by Genarito** [comment]
The issue is present in AntDesign v4.X too:
![Grabacindepantalla2024-11-14111943-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/f090f194-0f6a-4a5c-b5a5-7f9f269f8d70)

The workaround works with `suffix` prop, but I'm setting the `hasFeedback`, `validateStatus` and `help` props and It doesn't:

```ts
warningMessage
  ? {
      hasFeedback: true,
      validateStatus: 'warning',
      help: <div title='example'>{warningMessage}</div>
  }
  : {
      hasFeedback: true,
      validateStatus: 'warning',
      help: <span />
  }
```

**Comment by Genarito** [comment]
I need to show warnings in some cases, for those who need help this is my workaround:

```tsx
const className = 'your-classes-here'
const warningMessage: string | undefined = getWarningMessage()

// IMPORTANT: keeps `hasFeedback` prop immutable and adds 'no-feedback' class to prevent the input loss the focus when the feedback is shown.
// See 1: https://ant.design/components/input#why-input-lose-focus-when-change-prefixsuffixshowcount
// See 2: https://github.com/ant-design/ant-design/issues/34458
// See 3: https://github.com/ant-design/ant-design/issues/45612
const hasFeedback = warningMessage && warningMessage.length > 0
const alertParams: any = hasFeedback
    ? {
        hasFeedback: true,
        validateStatus: 'warning',
        help: <div className='ellipsis' title={warningMessage}>{warningMessage}</div>
    }
    : {
        hasFeedback: true
    }

if (!hasFeedback) {
    className += ' no-feedback'
}


// Then in the Input component:
<Form.Item
    className={className}
    // ... other props
    {...alertParams}
>
    <Input
        // ... other props
    />
</Form.Item>
```

Then I added some CSS:

```css
/* Hides the Check icon in the Input suffix when no-feedback class is present. */
.ant-form-item.no-feedback .ant-input-number-suffix,
.ant-form-item.no-feedback .ant-form-item-row div:has(> div.ant-form-item-explain) {
    display: none !important;
}
```

It works fine:
![Grabacindepantalla2024-11-14120022-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/2266cf3a-b0f2-4e7c-8c85-ec7132dc0fb6)
