### ISSUE TITLE
useMessage does not work when navigating with react-router

### ISSUE THREAD

**Issue by davidgtu** [ant-design/ant-design#45622]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-tree-mysc4n?file=/src/AnotherPage.tsx)

### Steps to reproduce

- Navigate to the create page
- Click on the button. 

### What is expected?

In older versions of message, I was previously able to navigate away and show the message at the same time. With this new API, I'm not able to see the message anymore.

### What is actually happening?

My assumption is that since `contextHolder` is now placed in JSX, when navigating away, it will not show the message since `contextHolder` won't be rendered at all.

I realized if I add async/await to `messageApi.success`, the message *will* appear for however long the default timeout is, *then* it will navigate. However, I was hoping for a more synchronous solution like in the past API.

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18.2.0 |
| System | OSX 13.2 |
| Browser | Version 118.0.5993.117 (Official Build) (arm64) |

**Comment by afc163** [comment]
You can try App component in that case: https://ant.design/components/app

https://codesandbox.io/s/exciting-dewdney-58ty8d?file=/src/index.tsx
