### ISSUE TITLE
autoFocus in Textarea in modal such as [Modal.confirm] doesn't work

### ISSUE THREAD

**Issue by LizaMaharjan2001** [ant-design/ant-design#45626]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/static-method-antd-5-10-3-forked-5kr3l2)

- I would appreciate it if you could demonstrate possible solutions given the CodeSandbox

### Steps to reproduce

- Click on open
- The input/ text area in the modal doesn't get focused even after using getContainer prop

### What is expected?

- The input or textarea that is inside the Modal.confirm modal should be focused on clicking 'Open'

### What is actually happening?

- The input/ text area in the modal doesn't get focused even after using getContainer prop

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

---
- This case is only for 'Modal.confirm' which im using it to show different cases of info, success, warning conditions.

**Comment by LizaMaharjan2001** [comment]
@MadCcc I've forked the codeSandbox not sure the update wasn't recorded, please help!

**Comment by LizaMaharjan2001** [comment]
@MadCcc  @zombieJ  I've forked the codeSandbox not sure the update wasn't recorded, please help!

**Comment by MadCcc** [comment]
`Modal.confirm` will focus on OK button automaticly, that's why textarea didn't get focused.
Use `autoFocusButton={null}` to avoid auto focusing.

**Comment by LizaMaharjan2001** [comment]
@MadCcc it still didn't worked for my case.
I've demonstrated my issue into the codesandbox here: https://codesandbox.io/s/static-method-antd-5-10-3-forked-5kr3l2?file=/demo.tsx
Please have a look on what i missed or did wrong.

**Comment by afc163** [comment]
See #41239
