### ISSUE TITLE
How to customize the popup size of DatePicker.RangePicker relative to ViewPort size

### ISSUE THREAD

**Issue by phatsp** [ant-design/ant-design#45629]
<h3> What problem does this feature solve? </h3>
I want to integrate Antd to build a customized Power BI visual. In PowerBI, there each visual/dashboard has it own Viewport. Current the popup of DatePicker is not responsive to Viewport size. Any approach to solve this?

I'm quite new so really appreciate details example though....

![issue](https://github.com/ant-design/ant-design/assets/43247670/7851dcbd-6031-4ed9-b228-1dd83b426e0a)

<h3>What does the proposed API look like? </h3>

```js
import * as React from 'react';
import { DatePicker} from 'antd';

const newPopupSize= ....;
const myUI = () => {    
    return (
        <RangePicker popupSize=newPopupSize ></RangePicker>
    );
}
```

**Comment by zombieJ** [comment]
Maybe add `transform` style on the popup. I'm not sure.

**Comment by phatsp** [comment]
> Maybe add `transform` style on the popup. I'm not sure.

Yeah, I already tried `<RangePicker size="small"/>` and `<RangePicker style={{width: "..."}} />` , but they only affect the input element, not the popup element.
