### ISSUE TITLE
Input.tsx编译后找不到Search

### ISSUE THREAD

**Issue by misliu** [ant-design/ant-design#4562]
#### Environment(required)

- antd version: 2.6.1
- OS and its version: ubuntu 16.0
- Browser and its version:  56.0.2924.21 beta (64-bit) chrome

#### What did you do? Please provide steps to re-produce your problem.
important {Input} from 'antd';
const Search = Input.Search;
console.log(Input) => {
    Group:...,
   PropTypes: ....
}
console.log(Search) => undefined;

#### What happen?
Search undefined

**Comment by yesmeck** [comment]
能把 issue 模板里的问题都回答一下吗？

**Comment by misliu** [comment]
我只是按照https://ant.design/components/input-cn/中 Search框的用法，导入Search模块，无法导入，然后看了一下node_module中，input.tsx编译出的input.js中，找不到search

**Comment by yesmeck** [comment]
Inpunt => Input

**Comment by misliu** [comment]
改正了，但不是这个问题！

**Comment by yesmeck** [comment]
提供下在线 Demo 吧
