### ISSUE TITLE
国内官方仓库版本还是5.10.2

### ISSUE THREAD

**Issue by VanChans** [ant-design/ant-design#45635]
### Reproduction link

[https://ant-design.antgroup.com/](https://ant-design.antgroup.com/)

### Steps to reproduce

https://ant-design.antgroup.com

### What is expected?

更新到最新5.10.3

### What is actually happening?

5.10.2

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | macos 11.4 |
| Browser | chrome 120.0 |

**Comment by MadCcc** [comment]
已更新
