### ISSUE TITLE
`NumberInput` always truncates decimal values when zeros

### ISSUE THREAD

**Issue by bombillazo** [ant-design/ant-design#45641]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gngvc6?file=/index.js)

### Steps to reproduce

We use a formatter function to try to always show 2 decimal places in the number input, but when the user blurs the input, the number input automatically removes the decimal places.

### What is expected?

The value stays the same as formatted by the formatted function.

### What is actually happening?

The trailing 0s after the decimal point are eliminated when the input is blurred

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2.0 |
| System | MacOS |
| Browser | All |

**Comment by MadCcc** [comment]
The return value of `formatter` in your code didn't reserve decimals, please check your code.
