### ISSUE TITLE
antd4->5，ConfigProvider配置主题不生效

### ISSUE THREAD

**Issue by JasonHuo-J** [ant-design/ant-design#45646]
### Reproduction link

[https://ant-design.antgroup.com/docs/react/migration-v5-cn](https://ant-design.antgroup.com/docs/react/migration-v5-cn)

### Steps to reproduce

按照文档从v4升级到v5，将Umi中的antd设置为了false，使用了ConfigProvider，并且设置了theme，但是主题色依旧是初始的蓝色

### What is expected?

期望自定义主题色可以生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 17.0.0 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
不用 false，umi 的 antd 配置也支持设置 theme: https://umijs.org/docs/max/antd#theme

**Comment by JasonHuo-J** [comment]
我一开始也尝试过在umi的antd中配置 但是提示 Validate config "antd" failed, "configProvider" is not allowed

**Comment by JasonHuo-J** [comment]
很抱歉因为是内部项目，暂时无法提供repo...

**Comment by yoyo837** [comment]
提供最小量的复现即可

**Comment by JasonHuo-J** [comment]
我使用的是Umi3.5的版本 是否是因为Umi3.5和antd5有一些兼容性问题 需要升级umi到4
