### ISSUE TITLE
Modal.confirm 触发按钮快速点击会多次弹出弹窗

### ISSUE THREAD

**Issue by dsjkaljldw** [ant-design/ant-design#45644]
### Reproduction link

[https://ant.design/components/modal-cn#modal-demo-hooks](https://ant.design/components/modal-cn#modal-demo-hooks)

### Steps to reproduce

连续快速点击confirm按钮

### What is expected?

只弹出一个弹窗

### What is actually happening?

连续点击多次弹出

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
Demo 只做了最简单的展示，实际上任何时候调用 `confirm` 都能弹出确认框。如果需要禁止额外的弹出。可以自行使用状态管理来确保只有一个弹出框哈~

**Comment by Hyacinth-FE** [comment]
全局配置下这个样式就可以解决这个问题
.ant-modal-mask{
  pointer-events: auto!important;
}
