### ISSUE TITLE
滚动页面，弹出层与组件脱离（Select, TimePicker 等组件）

### ISSUE THREAD

**Issue by hashplus** [ant-design/ant-design#4564]
#### Environment(required)

- antd version: antd@2.6.1
- OS and its version: all
- Browser and its version: all

#### What did you do? Please provide steps to re-produce your problem.

 滚动页面，弹出层与组件脱离

#### Re-producible online demo
http://codepen.io/hashplus/pen/ggPeab

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3487
