### ISSUE TITLE
The TextArea component's maxlength restriction behaves differently from the native textarea component.

### ISSUE THREAD

**Issue by happy-func** [ant-design/ant-design#45652]
### Reproduction link

[https://codepen.io/happy-func/pen/eYxdQoa?editors=001](https://codepen.io/happy-func/pen/eYxdQoa?editors=001)

### Steps to reproduce

Input box input text   emoji

### What is expected?

same restriction with native textarea

### What is actually happening?

differently

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | react |
| System | macos arm64 |
| Browser | chrome 118.0.5993.117 |

**Comment by MadCcc** [comment]
We provide `count` in 5.11.0, the next minor, which would solve this problem.
