### ISSUE TITLE
Transfer 组件 targetKeys的顺序问题

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#4566]
#### Environment(required)

- antd version: 2.6.x
- OS and its version: 
- Browser and its version: 

#### What did you do? Please provide steps to re-produce your problem.

从左往右选择操作两次
![image](https://cloud.githubusercontent.com/assets/2271825/21836627/97df5c88-d801-11e6-86d8-63de3a1493ac.png)

![image](https://cloud.githubusercontent.com/assets/2271825/21836636/a5949c26-d801-11e6-88eb-38ece97afe68.png)

#### What do you expected?

后移动的项能否往后追加，而不是放到前面

#### What happen?
第n(n>1)次的数据总是在上面, 设计如此吗？
我本来是想对targetKeys做排序操作的，但是每次有新的数据添加的时候，就把我已有的数据顺序打乱了。 

如果能添加到后面，就不会影响原有的顺序。

#### Re-producible online demo

官网所有demo https://ant.design/components/transfer-cn/#components-transfer-demo-search

**Comment by benjycui** [comment]
[代码](https://github.com/ant-design/ant-design/blob/29324ca59d7fa2d913d3a3866a191310bf33c4e8/components/transfer/index.tsx#L164) 是这样。

虽然不是故意如此，但是觉得没有合理的改动，因为不排除也有人使用情况跟你类似，但是希望新增 keys 在前面。

**Comment by codering** [comment]
@benjycui 你说的这种情况我也有想过。不过按照常规思路，数据的添加总有个先来后到吧，不知道当初这样实现的意图是什么，我以前见过的所有transfer实现都是放在后面的。

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/blob/29324ca59d7fa2d913d3a3866a191310bf33c4e8/components/transfer/index.tsx#L175

使用 `moveKeys` 和现有的 `targetKeys` 自行拼接 `newTargetKeys` 即可。

还是觉得没有合理的改动，毕竟 `antd` 要考虑通用性，请谅解。
