### ISSUE TITLE
TreeSelect组件当选中一个节点时，再展开下拉选项，被选中的节点样式存在问题，出现了粗蓝框

### ISSUE THREAD

**Issue by baicoding** [ant-design/ant-design#45665]
### Reproduction link

[https://codesandbox.io/s/54jv5q?file=/demo.tsx](https://codesandbox.io/s/54jv5q?file=/demo.tsx)

### Steps to reproduce

1.打开官方示例，选中节点leaf3
2.再次点击输入框，弹出下拉树，这个时候被选中的leaf3外层套了个深色的蓝框，鼠标滑动后蓝框消失
![image](https://github.com/ant-design/ant-design/assets/29280682/d6b69136-c92e-4fa4-abd3-e1e65e6350cf)

### What is expected?

选中的节点只是选中态，不出现深色的蓝框

### What is actually happening?

出现深色的蓝框

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2 |
| System | windows11 |
| Browser |  Chrome111.0.5563.111 |

**Comment by baicoding** [comment]
重现示例，https://codesandbox.io/s/54jv5q?file=/demo.tsx
![image](https://github.com/ant-design/ant-design/assets/29280682/f261bd52-c53c-4507-9fd0-91b4ac858a8b)

另外，官方demo中也可重现该问题


> Hello @baicoding. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @baicoding, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by MadCcc** [comment]
这是 focus-visible 的样式，用来告诉用户当前聚焦在哪个节点上

**Comment by MadCcc** [comment]
这里认为是符合预期的，因为打开时选中项是自动 active 的，鼠标 hover 之后 active class 消失。
样式问题 trace https://github.com/ant-design/ant-design/issues/44492
