### ISSUE TITLE
antd 文档 搜索后 页面标题与菜单内容不对应

### ISSUE THREAD

**Issue by 2218675712** [ant-design/ant-design#45679]
### What problem does this feature solve?

1. antd文档官网 进入antd color 菜单，
2. 通过左上角 搜索栏，输入 timeline ,进入 timeline 菜单
3. 页面 title 显示的是 色彩，此时页面title应该显示timeline

### What does the proposed API look like?

页面title与实际选择的菜单项应该是对应的

**Comment by zombieJ** [comment]
没重现出来，录个频看看？

<img width="621" alt="截屏2023-11-06 10 05 08" src="https://github.com/ant-design/ant-design/assets/5378891/1bb185fa-6a90-44b5-95b1-7ac992b2eae8">

**Comment by kiner-tang** [comment]
@zombieJ 
<img width="1792" alt="image" src="https://github.com/ant-design/ant-design/assets/10286961/9749fd9d-d2a2-447c-a6f9-697dc0bc0127">
说的应该是浏览器 tab 上的 title

**Comment by 2218675712** [comment]
是的，标签页的title

**Comment by 2218675712** [comment]
是的，浏览器 标签页 上的 title

**Comment by MadCcc** [comment]
`useRouteMeta` 异步之后导致的，需要在 dumi 侧做修复
