### ISSUE TITLE
uploader中限制上传格式有疑问,望解答,谢谢

### ISSUE THREAD

**Issue by encorehe** [ant-design/ant-design#4567]
有参数 accept(限制上传格式)和 beforeUpload方法 

官方文档提供了 beforeUpload 限制上传类型的方法,但是没有提供 accept 来限制上传类型的demo,我这边是把整个上传封装成了一个组件,其他人员只需要传入 accept参数,我这边通过 beforeUpload 方法来限制类型,但是在 beforeUpload 方法里面得不到 accept 参数,只可以得到 file 参数,我该怎么办呢?

**Comment by yesmeck** [comment]
`this.props.accept`?

使用问题建议提到 https://segmentfault.com/t/antd 上。

**Comment by benjycui** [comment]
accept 来自 HTML 规范，文档有提到的 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept
