### ISSUE TITLE
水印Watermark能否加个时间戳？

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#45682]
### What problem does this feature solve?

上次另一个issue提了好像没反馈，再问问。
content似乎目前不能实时变更。

https://codesandbox.io/s/duo-xing-shui-yin-antd-5-10-3-forked-hk2vh8?file=/demo.tsx

### What does the proposed API look like?

水印显示当前时间

**Comment by afc163** [comment]
Try React way: https://codesandbox.io/s/duo-xing-shui-yin-antd-5-10-3-forked-x5qpmh?file=/demo.tsx

**Comment by zombieJ** [comment]
内容是自己可以随便定的：
https://codesandbox.io/s/duo-xing-shui-yin-antd-5-10-3-forked-qpc8df?file=/demo.tsx

**Comment by theDoinb** [comment]
忘了用`state`了, - -...
