### ISSUE TITLE
How antd-tree can auto scroll to a selected node in `Virtual scroll` mode?

### ISSUE THREAD

**Issue by hatienl0i261299** [ant-design/ant-design#45680]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-tree-forked-c42plt?file=/src/App.js)

### Steps to reproduce

- Add a tree
- Set `height` prop for <Tree />

### What is expected?

We have a function that i can trigger with treeId, then tree will auto scroll to this node.

### What is actually happening?

I don't find any function like this in the document.

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 17.0.2 |
| System | macos and window and linux |
| Browser | chrome and edge and firefox |

**Comment by zombieJ** [comment]
https://ant.design/components/tree/#tree-methods

<img width="939" alt="截屏2023-11-06 10 10 07" src="https://github.com/ant-design/ant-design/assets/5378891/359e471c-1b17-4e0e-bcf3-91668a13c42c">
