### ISSUE TITLE
tree组件 文档中的onDrop代码片段有问题？

### ISSUE THREAD

**Issue by Ivan-hl** [ant-design/ant-design#45684]
### Reproduction link

[https://ant.design/components/tree-cn#components-tree-demo-draggable](https://ant.design/components/tree-cn#components-tree-demo-draggable)

### Steps to reproduce

在进行拖拽位置判断时，其中一段代码
if(xxx) { xxx }
else if (
      ((info.node as any).props.children || []).length > 0 && // Has children
      (info.node as any).props.expanded && // Is expanded
      dropPosition === 1 // On the bottom gap
    ) {}

1.这里的info.node.props.children读取是否有问题？根据实际打印结果，props内不存在children字段。
2.这个else if语句经多次测试从未满足条件执行过，请问触发条件具体是啥操作才会满足？

### What is expected?

else if (
      ((info.node as any).props.children || []).length > 0 && // Has children
      (info.node as any).props.expanded && // Is expanded
      dropPosition === 1 // On the bottom gap
    ) {}满足条件触发

### What is actually happening?

else if (
      ((info.node as any).props.children || []).length > 0 && // Has children
      (info.node as any).props.expanded && // Is expanded
      dropPosition === 1 // On the bottom gap
    ) {}从未触发

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome 111 |

---
根据个人的理解，指当drag元素到了目标元素的内容区域，此时dropToGap为false。
当dropPosition为-1时向上添加，为1或大于1时，向下添加

请问上述elseif 代码的判断意义何在

**Comment by afc163** [comment]
代码已经不可考了。 @Ivan-hl 来帮忙优化一下？

**Comment by Ivan-hl** [comment]
对这个拖动的计算原理了解的不太深入，心有余而力不足。 @afc163

**Comment by LINGyue-dot** [comment]
看了下 rc-tree 的代码，其中抛出的[ `info.node` ](https://github.com/react-component/tree/blob/69e377e09ad4242810515df5b7e65f21f7540e85/src/Tree.tsx#L755)，其中的 `info.node.props`  指向 

https://github.com/react-component/tree/blob/69e377e09ad4242810515df5b7e65f21f7540e85/src/Tree.tsx#L739C11-L743

并不存在 `children`属性 ，所以该逻辑不会触发。
