### ISSUE TITLE
Add `showCount` prop to editable Typography

### ISSUE THREAD

**Issue by juusaw** [ant-design/ant-design#45687]
### What problem does this feature solve?

Similarly to https://github.com/ant-design/ant-design/issues/23801, this would make the editable Typography component more configurable similarly to Input.Text and Input.Textarea. 

### What does the proposed API look like?

The prop would only need to be passed down to the `Input.TextArea` element rendered when editing the `Typography` and added to the `EditConfig` type.

**Comment by zombieJ** [comment]
Hmm... I'm not sure we should do this. Typography `editable` is designed as a light function. It seems get more and more complex ability.

**Comment by juusaw** [comment]
I understand the reasoning. However, since this would not involve adding new functionality (only passing an extra prop to the underlying component) I think it might be worth adding.

In my current use case I'd need a character count to a user-editable text and the option currently is to basically reimplement the editable using a `Text.TextArea` component in addition to the `Typography`.

**Comment by MadCcc** [comment]
We didn't expect this usage, but you can replace Typography with Input or TextArea yourself
