### ISSUE TITLE
Tooltip 中的 Typography 颜色与背景色均为深色看不清

### ISSUE THREAD

**Issue by 1pone** [ant-design/ant-design#45695]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-11-0-forked-7clfls?file=/demo.tsx)

### Steps to reproduce

鼠标悬浮 Tooltip

### What is expected?

提示的 Typography 显示为浅色

### What is actually happening?

提示的 Typography 显示为深色

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18 |
| System | macOS |
| Browser | Chrome |

---
希望可以为 Typography 添加处于 Tooltip 的浅色color样式，而不是手动添加 style

**Comment by afc163** [comment]
这样覆盖不完的，Tooltip 里如果加别的组件呢？我们建议 tooltip 里只有纯文本，其他复杂内容请使用 Popover。
