### ISSUE TITLE
Tag default background colour will show the bottom colour through

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#45694]
### Reproduction link

[https://ant.design/components/tag-cn](https://ant.design/components/tag-cn)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/29728228/0a50d9b6-0a7c-44d7-8dba-756928e15564)

 
### What is expected?

Tag If color is default, the background colour is indicated by rgba, so it is a semi-transparent colour, it will show the bottom colour through, if the bottom colour is not white then it is more obvious

Hope change Background RGBA to RGB

This is better
![image](https://github.com/ant-design/ant-design/assets/29728228/bd4b857d-60e8-4a16-9f2c-3f1ba8aeea05)

### What is actually happening?

background: rgba(0, 0, 0, 0.02);

![image](https://github.com/ant-design/ant-design/assets/29728228/45f5a01c-7399-46bb-b404-51db79a75c8a)

![image](https://github.com/ant-design/ant-design/assets/29728228/c2f8c28a-57d4-45bb-8e8c-ef6ebe435671)

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18 |
| System | mac/windows |
| Browser | chrome |

**Comment by zystudios** [comment]
A small suggestion 😊

I wish the tag would offer to set the background colour and border colour and text colour !
Allow customisation

bgcolor : background colour
boderColor: boder colour
color: text colour

’‘’
 <Tag bgcolor="#f50" boderColor="#000" color="#ff0000">#f50</Tag>
‘’‘

**Comment by afc163** [comment]
You are right, it works fine in https://4x.ant.design/components/tag , 5.x break it somehow. 

<img width="452" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/bacffb53-8ac3-4770-8aab-f549339c9648">

**Comment by kiner-tang** [comment]
let me try to fix it
