### ISSUE TITLE
Select has the wrong class when placement is automatically changed

### ISSUE THREAD

**Issue by philippechevieux** [ant-design/ant-design#45690]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gctt6d?file=/index.js)

### Steps to reproduce

When a Select DropDown is placed at the top (left of right it doesn't matter), if there isn't enough space the dropdown will be display bellow the select. 

This feature is great, the DropDown change automatically its class.

### What is expected?

Select classes should be updated with "ant-select-bottom".

### What is actually happening?

Dropdown classes are updated with"ant-select-dropdown-placement-bottomLeft". Hover Select classes still has "ant-select-top".

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | react 18 |
| System | macOS |
| Browser | Chrome 118 |

---
I'm facing this issue when i try to change the Select border radius depending on where the DropDown is open.

**Comment by afc163** [comment]
> I'm facing this issue when i try to change the Select border radius depending on where the DropDown is open.

https://codesandbox.io/s/antd-reproduction-template-forked-77sfqk?file=/index.css
