### ISSUE TITLE
TreeSelect 选择内容过长换行

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#4569]
浏览器: 主流浏览器
版本: antd@2.6.1

TreeSelect 如图:

![313cf9c7-cc0e-4a8a-acd6-4a04c9ea042c](https://cloud.githubusercontent.com/assets/2884665/21832691/da4b646e-d7e7-11e6-86ce-35a5074e2f38.png)

**Comment by afc163** [comment]
来个 PR ~

**Comment by xutou12** [comment]
恩好的, 我试试, 我还么做过PR

**Comment by afc163** [comment]
没关系，take your time~
