### ISSUE TITLE
Follow Babel 6 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#457]
babel-loader：https://github.com/babel/babel-loader/issues/123

**Comment by afc163** [comment]
https://github.com/babel/babel/issues/2724

**Comment by sorrycc** [comment]
好像还有不少坑，昨天试了下没切成功。

**Comment by sorrycc** [comment]
试了下，babel 6 慢好多，该配的都配过了，还没找到解决方案。https://github.com/ant-tool/atool-build/pull/7

**Comment by afc163** [comment]
http://hackernewsmobile.com/story/10472984

**Comment by afc163** [comment]
> So I've isolated the problem - babel 6.0.2 installed with npm 2.14.7 is slow, and when installed with npm 3.3.6 is fast. OS and node version is not a factor.

和 npm 版本有关？

**Comment by sorrycc** [comment]
果然。。换 npm@3 就好了。

**Comment by afc163** [comment]
antd 这边还不好搞。。

**Comment by afc163** [comment]
babel 居然把 issues 关了？
