### ISSUE TITLE
Tooltip open 值从 false 更改到 undefned 出现闪烁

### ISSUE THREAD

**Issue by JarvisArt** [ant-design/ant-design#45704]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-11-0-forked-j8kfyc)

### Steps to reproduce
https://github.com/ant-design/ant-design/assets/38420763/70953b7b-efa6-41aa-b262-b669a8482d3a

### What is actually happening?

 

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.0.0 |
| System | mac |
| Browser | chrome |

**Comment by JarvisArt** [comment]
受控模式下 open 为 false 时 hover 任然会触发 onOpenChange 中的 setOpen(true)

<img width="858" alt="image" src="https://github.com/ant-design/ant-design/assets/38420763/1803e682-14d4-41f6-a7e3-9dee601746e0">

**Comment by JarvisArt** [comment]
@zombieJ  这个算是 useMergedState 的内部问题还是 onOpenChange 的处理问题？

**Comment by zombieJ** [comment]
如果是从受控变成非受控，`useMergedState`  本身会多做一次 effect 清理，和 trigger 混合就有一些表现问题了。
这个改受控的写法本身其实并不推荐，为了支持它反而会写一些脏代码。是可以修，但是优先级不高。

**Comment by JarvisArt** [comment]
> 如果是从受控变成非受控，`useMergedState` 本身会多做一次 effect 清理，和 trigger 混合就有一些表现问题了。 这个改受控的写法本身其实并不推荐，为了支持它反而会写一些脏代码。是可以修，但是优先级不高。

从受控到非受控其实是为了做 disabled 的功能，有时候会遇到禁用  tooltip 的需求。

**Comment by afc163** [comment]
禁用 Tooltip 可以用 title 控制就行。

**Comment by JarvisArt** [comment]
> 禁用 Tooltip 可以用 title 控制就行。

光看文档确实没想到可以这么实现~
是不是可以加个禁用的demo?

**Comment by afc163** [comment]
>  是不是可以加个禁用的demo?
来个 PR~

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/45748
