### ISSUE TITLE
Custom style width on notifications are not applied correctly

### ISSUE THREAD

**Issue by erendabanlioglu** [ant-design/ant-design#45703]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wzxm5w)

### Steps to reproduce

- Go to official [antd docs](https://ant.design/components/notification#notification-demo-custom-style)
- Navigate to Customized style section
- Open notification

You can also check in codesandbox - https://codesandbox.io/s/wzxm5w, just click "open the notification box"
 

### What is expected?

Text in notification modal shouldn't overflow.

### What is actually happening?

You will see text overflow in notification modal. Notification wrapper has static width and doesn't wrap the content properly. ant-notification-notice-wrapper to be specific.

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | latest |
| System | macOS Big Sur 11.6 |
| Browser | Chrome Version 119.0.6045.105 (Official Build) (x86_64) |

**Comment by erendabanlioglu** [comment]
Changing `width` value of `ant-notification-notice-wrapper` to `auto` solves.

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/45681
