### ISSUE TITLE
Carousel does not render properly inside a Radio.Group

### ISSUE THREAD

**Issue by akang22** [ant-design/ant-design#45708]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-yw6lpc?file=/index.js)

### Steps to reproduce

Have a carousel inside a radio group. It renders outside properly, but does not render properly inside the radio group. 

### What is expected?

It should render two copies of the same carousel. The usage of this is to have multiple card-like selectable options on a carousel, with the restriction that you can only select one from radio group.

### What is actually happening?

For a second, the carousel appears to render, and then flickers away, leaving behind a tall and very wide empty component.

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.0 |
| System | Sonoma 14.0 |
| Browser | Google Chrome 118.0.5993.117 |

**Comment by akang22** [comment]
Issue appears to be styling. The width keeps increasing. None of the props did anything, but adding a width to the carousel does fix it. Makes me wonder if this is a problem in parents other than radio group.

**Comment by afc163** [comment]
You can add `style={{ maxWidth: '100%' }}` or `style={{ display: 'block' }}` to Radio.Group.

**Comment by MadCcc** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-qpcx2p?file=/index.js
