### ISSUE TITLE
Incorrect description for 'onChange' in antd Select component documentation

### ISSUE THREAD

**Issue by forgoma** [ant-design/ant-design#45719]
### Reproduction link

[https://ant.design/components/select#select-demo-search](https://ant.design/components/select#select-demo-search)

### Steps to reproduce

Type in text into the select box and select an option.

### What is expected?

'onChange' should be called when an option is selected or input value is changed, according to the documentation.

### What is actually happening?

'onChange' is called only when an option is selected.

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 17.0.2 |
| System | Windows10 |
| Browser | Chrome 119.0.6045.124 |

---
Documentation should be rewritten, or 'onChange' should also be called when input value is changed as the documentation states.  
With the current implementation, 'onChange' seems to be the same with 'onSelect'.

**Comment by afc163** [comment]
```jsx
const onChange = (value: string) => {
  console.log(`selected ${value}`);
};

const onSearch = (value: string) => {
  console.log('search:', value);
};
```

`onSearch` is triggered when when input value is changed, not `onChange`.

**Comment by MadCcc** [comment]
> `onSearch` is triggered when when input value is changed, not `onChange`.

+1
