### ISSUE TITLE
Tour 漫游式引导组件支持 getPopupContainer 接口

### ISSUE THREAD

**Issue by cxliustc-china** [ant-design/ant-design#45712]
### What problem does this feature solve?

自定义弹框挂载的节点，解决无法跟随挂载组件销毁的问题

### What does the proposed API look like?

getPopupContainer

**Comment by li-jia-nan** [comment]
- https://github.com/react-component/tour/pull/41

**Comment by li-jia-nan** [comment]
@cxliustc-china 源码中会透传进去，只是 ts 没有支持这个类型，你可以强制传 `getPopupContainer` 属性，照样会工作，只是 ts 会报错，月末下个次版本发布之后，ts 就会支持这个属性了
