### ISSUE TITLE
The popover component flickers within a horizontally scrolling element.

### ISSUE THREAD

**Issue by mmmml-zhao** [ant-design/ant-design#45714]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-antd-5-11-0-forked-cnz9qh?file=/demo.tsx)

### Steps to reproduce

1. Scroll the page to the right until the bottom.
2. Hover the mouse over the tooltip text.

### What is expected?

The popover no longer flickers.

### What is actually happening?

After hovering the mouse, the popover keeps flickering.

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.0 |
| System | macos 13.3 (22E252) |
| Browser | chrome  119.0.6045.105 (arm64) |

---
When the browser window size is smaller than the minimum document size, causing horizontal scrolling, the popover behaves abnormally.

**Comment by lkkwxy** [comment]
.ant-popover-inner-content{
  white-space: nowrap;
}

Adding this style globally may solve your problem

**Comment by sicallan** [comment]
> .ant-popover-inner-content{
> white-space: nowrap;
> }

This fixed it for me, thank you!

**Comment by gitdrums** [comment]
Thanks!

Same bug happens in Tooltip. 

Adding     

        <Tooltip
          placement="bottom" 
......
          overlayInnerStyle={{
            whiteSpace: "nowrap", // Fixes the flicker!
          }}
        </Tooltip>
