### ISSUE TITLE
Pagination not showing correct when table is pre filtered

### ISSUE THREAD

**Issue by armine87** [ant-design/ant-design#45733]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-n5lry6?file=/index.js)

### Steps to reproduce

When Page is loaded click on next page, see the total (count) value changes and the pagination updates.

### What is expected?

The pre filtered table should update the currentDataSource length on load after filter applied.

### What is actually happening?

The currentDataSource is unavailable on load with pre filtered values.

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Edge |

**Comment by afc163** [comment]
It is not antd's bug, you should set count to filtered count intially. The paganiation follow `data.length` as it's total in your code, it is expected behaviour.
