### ISSUE TITLE
Upload Dragger使用disable=true属性后，使用showRemoveIcon=true仍无法显示删除图标

### ISSUE THREAD

**Issue by fasnow** [ant-design/ant-design#45735]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rdnzp3)

### Steps to reproduce

如链接https://codesandbox.io/s/antd-reproduction-template-forked-rdnzp3
代码如下
```
import React from "react";
import { useState } from "react";
import { createRoot } from "react-dom/client";
import "antd/dist/reset.css";
import "./index.css";
import Dragger from "antd/es/upload/Dragger";

const App = () => {
  const [fileList, setFileList] = useState([]);
  const props = {
    name: "file",
    onChange(info) {
      setFileList(info.fileList);
    },
    customRequest: async (options) => {
      const formData = new FormData();
      formData.append("file", options.file);
      try {
        const response = await req.post("/uploadTmpReport", formData, {
          headers: { "Content-Type": "multipart/form-data" },
          timeout: 0,
          onUploadProgress: (progressEvent) => {
            if (progressEvent.total) {
              const percent = Math.round(
                (progressEvent.loaded * 100) / progressEvent.total
              );
              options.onProgress({ percent }, options.file);
              if (percent === 100) {
                options.onSuccess(); 
              }
            } else {
              options.onProgress(
                { loaded: progressEvent.loaded },
                options.file
              );
            }
          }
        });
        const data = response.data;
        if (data.code != 200) {
          options.onError("上传失败", options.fileList);
        }
      } catch (error) {
        options.onError("上传失败", options.fileList);
      }
    },
    showUploadList: { showRemoveIcon: true },
    disabled: fileList.length == 1
  };
  return (
    <div className="App">
      <Dragger {...props}>
        <p className="ant-upload-text">点击或拖拽上传</p>
      </Dragger>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);

```

### What is expected?

使用disabled属性时只禁用上传按钮，而不禁用文件列表的删除按钮，禁用文件列表的删除按钮应该通过showUploadList: { showRemoveIcon: false}来实现

### What is actually happening?

使用disable=false属性后，使用showRemoveIcon=true仍无法显示删除图标

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-sjkcly

> 使用disable=false属性后，使用showRemoveIcon=true仍无法显示删除图标

和你的描述貌似不太一致。

<img width="1321" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/fbf98ae0-a512-4587-b3d8-2ff5366fa545">

**Comment by fasnow** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-sjkcly
> 
> > 使用disable=false属性后，使用showRemoveIcon=true仍无法显示删除图标
> 
> 和你的描述貌似不太一致。
> 
> <img alt="图片" width="1321" src="https://user-images.githubusercontent.com/507615/281605719-fbf98ae0-a512-4587-b3d8-2ff5366fa545.png">

disable得通过一个变量控制，只允许上传一个文件，不管失败与否，计数器为1：disable=true，为0：disable=false，就像我用了fileList.length == 1来控制一样，disable为false当然没问题的，但是disable为true时，我想的是禁止上传，但是可以删除已有的

**Comment by afc163** [comment]
所以问题是：`使用disable=true属性时，使用showRemoveIcon=true仍无法显示删除图标`，对么？

**Comment by fasnow** [comment]
> 所以问题是：`使用disable=true属性时，使用showRemoveIcon=true仍无法显示删除图标`，对么？

是的，标题打飘了...

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27519 同一个问题

**Comment by fasnow** [comment]
> #27519 同一个问题

我已经查看了多个类似的问题但是都没有提出明确的解决方案，其中 https://github.com/ant-design/ant-design/issues/8677#issuecomment-627145191 提到用showUploadList: { showRemoveIcon: true },来单独控制删除图标，可是我已经设置了，但是disabled为true时仍然无法显示
