### ISSUE TITLE
Input of  type file throwing error Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string after selecting file

### ISSUE THREAD

**Issue by samanthaburboz** [ant-design/ant-design#45737]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-antd-5-11-0-forked-pppmvy?file=/demo.tsx)

### Steps to reproduce

Add form item with Input type file

    <Form.Item
      label="File"
      name="file"
      rules={[{ required: true, message: "Please upload file" }]}
    >
      <Input type="file" />
    </Form.Item>

Try to select a file to upload

### What is expected?

File should be uploaded successfully

### What is actually happening?

Throwing following error

InvalidStateError

Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.0.0 |
| System | Windows 10 Enterprise |
| Browser | chrome |

**Comment by aliBenhenia** [comment]
is solved??

**Comment by samanthaburboz** [comment]
no

**Comment by afc163** [comment]
There is something wrong with `<Input type="file" />: https://codesandbox.io/s/basic-usage-antd-5-11-0-forked-hnxlnh?file=/demo.tsx I will check it.
