### ISSUE TITLE
antd v4 modal, message, notification的静态调用支持自定义图标前缀iconPrefixCls

### ISSUE THREAD

**Issue by rendeyuwei** [ant-design/ant-design#45732]
### What problem does this feature solve?

看了下源码，以modal为例目前可以通过：
`Modal.info({prefixCls: 'test'})` 或者 `Modal.config({rootPrefixCls: 'test'})`来自定义弹出框的前缀名称，但是并没有入口去自定义弹出内容的icon的样式。

目前只能通过ConfigProvider来全局定义
```
ConfigProvider.config({
      prefixCls: 'test',
      iconPrefixCls: 'test-icon',
});
```

希望在v4版本中modal, message, notification可以通过静态方法中自定义icon前缀，而不想通过ConfigProvider来全局定义。因为在我们的场景下会存在两个版本的antd，此时假如版本一样的话，ConfigProvider的全局定义会造成污染。

p.s. 在源码中我看`getNotificationInstance`的callback中参数是有iconPrefixCls，但是在代码中并没有实际用到

### What does the proposed API look like?

以Modal为例，希望增加一个如下参数：  
`Modal.info({prefixCls: 'test', iconPrefixCls: 'test-icon'}) `  
或者  
 `Modal.config({rootPrefixCls: 'test', iconPrefixCls: 'test-icon'})`

**Comment by crazyair** [comment]
2个版本的antd，那就是2个config，怎么会污染呢

**Comment by rendeyuwei** [comment]
> 2个版本的antd，那就是2个config，怎么会污染呢

实际场景是这样，业务项目里面有一个版本的antd，可能是4的最高版本，基于antd为基础的一个业务组件库也依赖了一个antd版本，固定是4的最高版本，假如这两个版本一样的话，这样就会污染。
当然如果业务项目里不是4的最高版本，版本不一样的话就不会存在问题了

**Comment by crazyair** [comment]
可以设置2个啊
antd.ConfigProvider.config
antd2.ConfigProvider.config

**Comment by rendeyuwei** [comment]
> 可以设置2个啊 antd.ConfigProvider.config antd2.ConfigProvider.config

大佬，你的意思是对包起别名吗？没太理解意思，能拿代码举个例子吗？感谢！

**Comment by crazyair** [comment]
建议别锁版本，保证antd为项目里安装的版本

**Comment by rendeyuwei** [comment]
> 建议别锁版本，保证antd为项目里安装的版本

就是实际业务项目里可能有3版本的（老项目，升级不太现实）有4版本的，业务组件库（依赖4的最高版本antd）其实想在3或者4的antd都能完美的兼容达到样式隔离。3版本的兼容已经实现了，但是相同版本的兼容遇到了上述这样一个问题。

其次呢，我觉得既然静态方法的参数里面有了prefixCls，再加上iconPrefixCls是不是会更完善一点呢，或者说当初没加这个参数是有什么考虑吗

**Comment by afc163** [comment]
我们推荐用 `Modal.useModal`，静态方法修改 prefix 有很多边界问题。https://4x.ant.design/components/modal-cn/#Modal.useModal()

**Comment by rendeyuwei** [comment]
> 我们推荐用 `Modal.useModal`，静态方法修改 prefix 有很多边界问题。https://4x.ant.design/components/modal-cn/#Modal.useModal()

感谢大佬，看了下`useModal`的源码，发现可以通过`useModal`返回的`modal`来实现自定义的`iconPrefixCls`（虽然ts定义不支持）。
几个小问题有空可以瞅瞅：

1、`useModal`和`Modal`静态调用得到的结果都用到了`ConfirmDialog`，这个的props是`ConfirmDialogProps`，这个定义里面是有`iconPrefixCls`的，但是`useModal`返回的`modal`的`props`的定义是`ModalFuncProps`，这个里面其实是没有`iconPrefixCls`的，感觉这个ts定义是有点问题的

 
2、你提到的，“静态方法修改 prefix 有很多边界问题”是什么问题呢？是不是出于这个考虑，使得静态调用的`iconPrefixCls`其实是直接取了`globalIconPrefixCls`，而不接受`props`传入，那为什么`useModal`是可以修改`iconPrefixCls`却没有你提到的边界问题？
