### ISSUE TITLE
Tree组件复选功能子节点被设为禁用态后父级状态不会同步

### ISSUE THREAD

**Issue by easyterry** [ant-design/ant-design#45744]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shou-kong-cao-zuo-shi-li-antd-5-11-0-forked-9yvgp9)

### Steps to reproduce

子节点设置disabled:true后，父级节点的复选框状态没有同步到

### What is expected?

父级节点的复选框状态同步显示"半选/全选"状态

### What is actually happening?

父级节点的复选框状态没有同步显示"半选/全选"状态
![image](https://github.com/ant-design/ant-design/assets/24635847/9eb017b8-a205-40d8-bb8e-ebcd16edab1f)

对比ElementUI下的展示效果
![image](https://github.com/ant-design/ant-design/assets/24635847/f8fb849a-bb39-4b37-b71d-1240b17e3dc1)

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 17 |
| System | Windows 10 |
| Browser | Chrome 119.0.6045.105 |

**Comment by zombieJ** [comment]
预期行为，请参考 FAQ 或者博客：
* [disabled 节点在树中的关系是什么？](https://ant-design.antgroup.com/components/tree-cn#disabled-%E8%8A%82%E7%82%B9%E5%9C%A8%E6%A0%91%E4%B8%AD%E7%9A%84%E5%85%B3%E7%B3%BB%E6%98%AF%E4%BB%80%E4%B9%88)
* [Tree 的勾选传导](https://ant-design.antgroup.com/docs/blog/check-conduct-cn)
