### ISSUE TITLE
Table 设置 scroll.x，列使用 Typography.Text，鼠标 hover 后省略号消失

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#45741]
### Reproduction link

[https://stackblitz.com/edit/react-wtajw9?file=demo.tsx](https://stackblitz.com/edit/react-wtajw9?file=demo.tsx)

### Steps to reproduce

鼠标 hover 到`Address 1`列

### What is expected?

省略号不消失

### What is actually happening?

省略号消失

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | latest |
| System | mac |
| Browser | chrome |

---
Typography.Text 宽度设置与列宽一致会导致该问题

**Comment by crazyair** [comment]
列设置200宽度，其实 render 中只有 200 - 16 *2 的宽度，在 v4 的时候省略号没问题，v5 消失了

**Comment by crazyair** [comment]
scroll.x 设置 max-content 不会有问题，因为列设置 200，Text 宽度设置200，其实列最终宽度是 200 + 16 *2

**Comment by afc163** [comment]
表格列的宽度如果都写死的话，在屏幕比较小的时候，宽度没办法保持（这是表格的自适应特性）。在这种情况下，Text 设定了 200px 固定宽度，就会超出列的范围，从而被下一排列的背景样式影响。

列设置了宽度的话，Text 建议设置 `maxWidth: '100%'` 就好。
