### ISSUE TITLE
官网上的Form动态添加一个项目的例子再antd2.5.0正常工作，2.6.0, 2.6.1不正常工作

### ISSUE THREAD

**Issue by nianhua110** [ant-design/ant-design#4575]
#### Environment(required)

- antd version:2.6.1
- OS and its version:Ubuntu 16.4.0 lTS
- Browser and its version: chrome 
54.0
#### What did you do? Please provide steps to re-produce your problem.
将官网上的动态添加一个表单项目的的案例copy到本地运行，以前一直可以。最近将Antd升级到了2.6.1，不能正常工作了。
```javaScript
  componentWillMount() {
    this.props.form.setFieldsValue({
      keys: [0],
    });
      console.log('ip group will mount', uuid , this.props, this.props.form.getFieldsValue() , this.props.form.keys);
  }
```
 打印的keys为空。

#### Re-producible online demo
不知道怎么在该网站运行代码。sorry。就是官网的例子。

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/e4bee3425a76363fa0f1e06c77099ebe15a14d5d#diff-6fcb3d637ccedac377935c5043d442c6R74

你可能需要补上这个，我升级 rc-form 的时候也发现了。

**Comment by afc163** [comment]
#6360
