### ISSUE TITLE
【文档示例链接内容报错】布局组件中，部分 codesandbox 链接偶发打开显示“errot:file not found”的情况

### ISSUE THREAD

**Issue by zxhycxq** [ant-design/ant-design#45759]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/gu-ding-ce-bian-lan-antd-5-11-0-2dcc73)

### Steps to reproduce

上面给出的链接，是点击 https://ant-design.antgroup.com/components/layout-cn#layoutsider 的固定侧边栏示例后，跳转的链接（官方的），有时候打开是前面这个，有时候是https://codesandbox.io/s/2dcc73 （这个是正常的）

### What is expected?

期望结果为https://codesandbox.io/s/2dcc73 ，或者官网给出的其他在线编辑器平台的效果

### What is actually happening?

偶尔打开的链接显示文件找不到

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.0 |
| System | window10 |
| Browser | Edge 120 |

---
如果打开这个则会报错：https://codesandbox.io/p/sandbox/gu-ding-ce-bian-lan-antd-5-11-0-2dcc73

**Comment by zxhycxq** [comment]
![image](https://github.com/ant-design/ant-design/assets/11674203/41356b30-755c-4cbb-8fb0-7727404663fa)

**Comment by Wxh16144** [comment]
有可能是一开始 URL 里面查询参数没有，codebox 有一个默认逻辑，然后目录里面又找不到文件，所以会报错。

我试着点击侧边选中一个文件后，右边预览可以正常工作。感觉问题有点隐晦

**Comment by afc163** [comment]
没有重现，怀疑是 codesandbox 的故障。

**Comment by afc163** [comment]
现在问题还在么

**Comment by zxhycxq** [comment]
没有了。用的自己的电脑。原因不明
