### ISSUE TITLE
Property 'uploader' is private and only accessible within class 'Upload'

### ISSUE THREAD

**Issue by nonam4** [ant-design/ant-design#45765]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drag-and-drop-antd-5-11-0-forked-grmsl3?file=/demo.tsx)

### Steps to reproduce

See intellisense error on `line 33`

### What is expected?

I should be able to access `uploader` prop to open file browser by ref 

### What is actually happening?

Intellisense is throwing an error

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | React 18.0.0 |
| System | MacOS and CodeSandbox |
| Browser | Chrome 108.0.5359.124 |

---
I want to open upload file selection by clicking on an external button using `Dragger` ref.
Is this an error or should I use another type in my ref?

**Comment by zombieJ** [comment]
No. Do not call internal API that not list in doc. You can use ref outer element to `querySelector` get input element instead.

* [FAQ: Can I use internal API which is not documented on the site?](https://ant.design/docs/react/faq/#can-i-use-internal-api-which-is-not-documented-on-the-site)
