### ISSUE TITLE
InputNumber 在 Space.Compact 中如果存在 addonAfter 边框展示不对

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/ant-design#45764]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jin-cou-mo-shi-antd-5-11-0-forked-8v3jlk?file=/demo.tsx)

### Steps to reproduce

打开重现链接

### What is expected?

InputNumber 贴紧前一个组件

### What is actually happening?

边框没对齐

![image](https://github.com/ant-design/ant-design/assets/21048878/88c3f310-cbac-4382-be17-72b1a8425c89)

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.0 |
| System | Windows10 |
| Browser | Chrome 99.0.4844.51 |

**Comment by afc163** [comment]
https://codesandbox.io/s/jin-cou-mo-shi-antd-5-11-0-forked-zvlg4c?file=/demo.tsx 这样是不是可以？

**Comment by liuweiGL** [comment]
有点不一样，示例里面用的是个搜索图标，但实际场景中是个单位，比如 “吨” 字

![image](https://github.com/ant-design/ant-design/assets/21048878/65020875-971c-41cc-854b-3691efdffbfc)

**Comment by liuweiGL** [comment]
我觉得应该重新打开 issue
