### ISSUE TITLE
feat(component/select): add clickOutsideToClose api

### ISSUE THREAD

**Issue by ayangweb** [ant-design/ant-design#45763]
### What problem does this feature solve?

点击选择框之外的地方不会收起下拉框！

### What does the proposed API look like?

clickOutsideToClose: boolean

**Comment by zombieJ** [comment]
使用 `open` 受控：
```tsx
<Select open />
```

**Comment by ayangweb** [comment]
> 使用 `open` 受控：
> 
> ```tsx
> <Select open />
> ```

我就是用这个实现的，但是感觉暴露个 api 会更方便

**Comment by afc163** [comment]
> 点击选择框之外的地方不会收起下拉框

是要满足什么具体产品需求呢？

**Comment by ayangweb** [comment]
> > 点击选择框之外的地方不会收起下拉框
> 
> 是要满足什么具体产品需求呢？

只是想提供 pr 😂

**Comment by afc163** [comment]
在具体需求之前我倾向先不加。
