### ISSUE TITLE
table 样式细节

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#45777]
在 borderd 环境下, ant-table-container  有一个 border-top:1px, 
需要在 <table> 上抵消该一像素导致的错位问题

```jsx
.ant-table-bordered table {
 margin-top: -1px
}
```
### Reproduction link

[https://撒撒](https://撒撒)

### Steps to reproduce

212

### What is expected?

21

### What is actually happening?

21

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18 |
| System | latest |
| Browser | latest |

<img width="1376" alt="image" src="https://github.com/ant-design/ant-design/assets/124666577/ea9d5df1-95e7-4380-9151-1a2f90e92c63">

**Comment by afc163** [comment]
给个重现？

**Comment by vaynevayne** [comment]
> 给个重现？

不想再实现一次打印了, 
这是一个显而易见的bug  

使用 react-print 打印时, 细节问题会被放大, 
container  width 100
  table width 1000 
  可滚动, 
  这个时候就能看到 1px 的问题

**Comment by vaynevayne** [comment]
第二个问题, https://github.com/ant-design/ant-design/discussions/45778

这两个伪元素 如果没有的话, 就删了吧, 会导致打印时样式异常

**Comment by crazyair** [comment]
是使用了`fixed`固定列了吗，打印前把`fixed`移除呢？

**Comment by vaynevayne** [comment]
> 是使用了`fixed`固定列了吗，打印前把`fixed`移除呢？

我试试, 
不过 antd 考虑使用CSS scrolling shadows  吗?  https://lea.verou.me/blog/2012/04/background-attachment-local/

这样应该可以完美解决
