### ISSUE TITLE
文件上传使用拖拽功能，可以拖拽文件夹，并且在 beforeUpload 或者 onDrop 中无法区分文件和文件夹

### ISSUE THREAD

**Issue by sRoke** [ant-design/ant-design#45787]
### Reproduction link

[https://ant-design.antgroup.com/components/upload-cn#components-upload-demo-drag](https://ant-design.antgroup.com/components/upload-cn#components-upload-demo-drag)

### Steps to reproduce

.

### What is expected?

文件上传（非文件夹）的时候，不允许拖拽文件夹进入拖拽框，或者能够区分拖拽进来的是文件还是文件夹

### What is actually happening?

文件上传（非文件夹）的时候，可拖拽文件夹进入拖拽框，并且补能够区分拖拽进来的是文件还是文件夹

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | react |
| System | windows10 |
| Browser | chorm |

**Comment by afc163** [comment]
你遇到的具体问题是什么？

1. 详细的重现步骤
2. 预期行为是什么
3. 目前你观察的行为是什么？
