### ISSUE TITLE
Tooltip 位置不对

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#45784]
### Discussed in https://github.com/ant-design/ant-design/discussions/45633

https://codesandbox.io/s/competent-perlman-l8yryx?file=/src/App.js

<div type='discussions-op-text'>

<sup>Originally posted by **ekuku1984** November  2, 2023</sup>
![image](https://github.com/ant-design/ant-design/assets/6016942/47e39b10-3408-4e84-8a20-b87e8da40804)

Tooltip 把 Slider 圆点都给档住了。

随便包含一个元素， 位置都不太对

看了官网的没问题，今天也升级到了 ANTD 最新版本了，还是不对， 项目内容比较多，以为是什么内容或样式冲突引起的。

然后在项目的入口把所有的 CSS 引入去掉， 就正常了， 最终发现是引入了 antd/dist/reset.css 引起的， 经过对 reset.css 文件的删减，发现是
body {
    margin: 0
}

这个样式引起的， 去掉 margin: 0 位置就正常了。

看了官网 body 也设置了 margin 又没事，不知道是原因了</div>

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/45202#issuecomment-1803248958

**Comment by helloyou2012** [comment]
可以先这样解决下：

> <Tooltip align={{ dynamicInset: false }} />

**Comment by zombieJ** [comment]
https://codesandbox.io/s/intelligent-buck-dxrmf3?file=/package.json
