### ISSUE TITLE
Form.List's field is undefined when using getFieldsValue

### ISSUE THREAD

**Issue by Saidnazar08** [ant-design/ant-design#45793]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-form-nest-items-antd-5-11-1-forked-sxt7yg?file=/demo.tsx)

### Steps to reproduce

1. Open the codesandbox 
2. Add a list field
3. Submit the form
4. Click the "getFieldsValue" button

### What is expected?

Logged objects should be the same

### What is actually happening?

When logged using "getFieldsValue", the list field is undefined

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | Windows 11  |
| Browser | Google Chrome 117 |

![image](https://github.com/ant-design/ant-design/assets/58825986/26579156-2900-4ed0-bec1-70f6897a8526)

**Comment by MadCcc** [comment]
https://codesandbox.io/s/dynamic-form-nest-items-antd-5-11-1-forked-38n5v5
`getFieldsValue({strict: true})`
