### ISSUE TITLE
<Tooltip /> 在气泡未展示时，onVisibleChange 的参数可能会为 true

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#4579]
当最开始 `<Tooltip />` 的 `title` 为空时，在鼠标滑过元素时，`onVisibleChange`此时获取到当前组件的 `visible = true`，然后此时并没有气泡，如果值为 `false` 是不是要合理些？然后这样也会导致当下次组件的 `title` 从无到有时，气泡会突然出现，而预期的是希望滑过时才会出现气泡。

然后，看了下代码逻辑，如果在[/tooltip/index.tsx#L65](https://github.com/ant-design/ant-design/blob/master/components/tooltip/index.tsx#L65)加个对 `title`、`overlay` 是否为空的判断，应该可以解决这个问题。

见下图，[查看demo](http://codepen.io/ystarlongzi/pen/mReWmX?editors=001)

![222](https://cloud.githubusercontent.com/assets/2840462/21877975/ed3ff28c-d8c9-11e6-9fa2-1d5136301578.gif)

**Comment by benjycui** [comment]
把这几行移到你给出的那个 `onVisibleChange` 函数里面应该可以解决问题： https://github.com/ant-design/ant-design/blob/6a015f00e6be37f09d9c376f2b61c286128dd1d5/components/tooltip/index.tsx#L125-L128

**Comment by benjycui** [comment]
可以麻烦你来个 PR？

**Comment by ystarlongzi** [comment]
嗯嗯，好的，稍等
