### ISSUE TITLE
1.11.5 的 Table 的 className 有问题，边框未生效

### ISSUE THREAD

**Issue by Alex1990** [ant-design/ant-design#4580]
#### Environment(required)

- antd version: 1.11.5
- OS and its version: macOS 10.11.5
- Browser and its version: Chrome Version 55.0.2883.95 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

升级 antd 到 1.11.5 版本，然后`Table`组件使用了`bordered`。

#### What do you expected?

期望表格有边框。

#### What happen?

结果表格无边框，然后我查看了一下表格的`class`，发现如下：

```
class="ant-table ant-table-middle ${prefixCls}-bordered ${prefixCls}-empty ant-table-without-column-header ant-table-scroll-position-left"
```

即`${prefixCls}`没有转换。

**Comment by benjycui** [comment]
发布中。

**Comment by afc163** [comment]
http://1x.ant.design/components/table/#components-table-demo-bordered demo
