### ISSUE TITLE
Popover 和 Modal 在 Chrome 下在窗口大小变化时字体会变细

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#4582]
#### Environment(required)

- antd version: 2.6.1
- OS and its version: MacOS
- Browser and its version: Chrome Version 55.0.2883.95 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

在官网 Modal 的 Demo 上打开 Basic 那个 Modal，然后 resize 浏览器窗口。

#### What do you expected?

Modal  内字体无变化。

#### What happen?

Modal  内字体变细了。

窗口变化前：

<img width="536" alt="dingtalk20170112140212" src="https://cloud.githubusercontent.com/assets/465125/21878851/d3dd7bce-d8cf-11e6-8378-8e3fa886622b.png">

窗口变化后：

<img width="542" alt="dingtalk20170112140227" src="https://cloud.githubusercontent.com/assets/465125/21878857/dba9a56c-d8cf-11e6-8306-55513c75275a.png">

**Comment by yesmeck** [comment]
发现只有 retina 屏上有这个问题。

**Comment by RaoHai** [comment]
transform-origin 的问题。

**Comment by afc163** [comment]
```css
-webkit-font-smoothing: antialiased;
```

和 body 上的这个有关系，刚 insert 到 dom 里的元素没有渲染出 `-webkit-font-smoothing: antialiased;` 的效果。拖拽后貌似重新 repaint 就生效了。

**Comment by afc163** [comment]
所以本质上这个问题是，打开时文字不应该是加粗的。

**Comment by afc163** [comment]
是 chrome 的渲染问题，暂时找不到合适的解决方式。
