### ISSUE TITLE
Token 设置不同 colorPrimary 值体验不一致

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#45843]
### Reproduction link

[https://stackblitz.com/edit/react-pezrqq?file=demo.tsx](https://stackblitz.com/edit/react-pezrqq?file=demo.tsx)

### Steps to reproduce

1. 全选表格所有列
2. 鼠标 hover 列

### What is expected?

hover 后颜色有变化

### What is actually happening?

hover 后颜色无变化

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | latest |
| System | mac |
| Browser | chrome |

---
不知道为什么使用 `#5254CC` 会看不到变化，v4 生成的 hover 样式是 `#e6ebff` v5 生成的却是`#f0f2ff`

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/d638f683-a1f8-44b7-8f9e-290c5bdd9c73)
这个主色计算色板会有点偏，可以微调一下 token
