### ISSUE TITLE
Upload组件交互渲染错误, 5.x、4.x都会有影响

### ISSUE THREAD

**Issue by HaishengLiang** [ant-design/ant-design#45844]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

1、打开浏览器, 并访问上传组件 例如: https://ant.design/components/upload-cn

2、点击上传按钮 (显示文件选择界面) 

3、点击上传弹窗的空白地区(不要点击上传或者取消按钮、也不要选择文件)

4、上传弹窗消失, 但是遮罩被保留了下来

### What is expected?

当弹窗消失的时候, 遮罩也跟随消失

### What is actually happening?

遮罩无法跟随消失

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.x |
| System | macos 11.x ~ 12.x   |
| Browser | Chrome 119  |

---
按ESC可以使异常的触发遮罩消失, 不是每次都会触发大概尝试3-4次会有一次触发

![image](https://github.com/ant-design/ant-design/assets/1995687/8cbf23fe-9e89-4523-8f53-92692532b49c)

![image](https://github.com/ant-design/ant-design/assets/1995687/1519be13-65c9-4c94-b0a1-afeb26e5694c)

**Comment by zombieJ** [comment]
这个是浏览器行为，遮罩层不是组件侧提供的。我们也没办法控制这个行为，只能说是去升级系统了。
