### ISSUE TITLE
 inconsistent behavior of form values

### ISSUE THREAD

**Issue by v-zdorovcev** [ant-design/ant-design#45879]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-67xgnf?file=/index.js)

### Steps to reproduce

If you submit the form with only the initial values, then the value of `users` will be equal to its option (`options[0]`). If the select value is changed to another, then when submitting the form the `users` field will be a `number` (value key)

### What is expected?

When submitting a form, the users value must always be of the same type. Either `option[0]` or `number`

### What is actually happening?

The value of `users` changes depending on the `isFieldsTouched` flag

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | 18.2.0 |
| System | macos 14.1.1 (23B81) |
| Browser | Chrome 119.0.6045.123 (arm64) |

**Comment by afc163** [comment]
See https://codesandbox.io/s/antd-reproduction-template-forked-77fs8c?file=/index.js

**Comment by v-zdorovcev** [comment]
> See https://codesandbox.io/s/antd-reproduction-template-forked-77fs8c?file=/index.js

Thanks for the example. But this is not very obvious behavior, it’s a pity that there is no such example in the documentation

**Comment by v-zdorovcev** [comment]
If options are populated dynamically, the default value should be the option, not the option value
