### ISSUE TITLE
treeSelect的子节点展示不全

### ISSUE THREAD

**Issue by RemEmilia** [ant-design/ant-design#45888]
### Reproduction link

[https://4x.ant.design/components/tree-select-cn/#header](https://4x.ant.design/components/tree-select-cn/#header)

### Steps to reproduce

子节点文字长度超过TreeSelect输入框时，会隐藏，选择框的下拉框不放大

### What is expected?

选择框的下拉框的宽度，随着子节点宽度变化而变化

### What is actually happening?

没有变化

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | win11 |
| Browser | chrome |

**Comment by RemEmilia** [comment]
![image](https://github.com/ant-design/ant-design/assets/37118890/21872094-24a7-455c-a3d9-b6f4790a371f)

**Comment by MadCcc** [comment]
`popupMatchSelectWidth={false}` 试试这个

**Comment by MadCcc** [comment]
或者 `virtual={false}` 关闭虚拟列表

**Comment by RemEmilia** [comment]
> 或者 `virtual={false}` 关闭虚拟列表

解决了，非常感谢

**Comment by RemEmilia** [comment]
> `popupMatchSelectWidth={false}` 试试这个

4.18的treeSelect没有这个属性
