### ISSUE TITLE
Use DatePicker / TimePicker on a different timezone than user's

### ISSUE THREAD

**Issue by carmenchapa** [ant-design/ant-design#45880]
### What problem does this feature solve?

I have a DatePicker and RangePicker with showTime that needs to behave with UTC time regardless the users timezone.

e.g. Im in Madrid (CET), and I pick a date with 15:00 time, and I should see 15:00 in the picker, but the stored datetime should be 14:00 (UTC). If it is 20:00 in CET, and I click on *Now* I should see 19:00 as is the current UTC time.

I've looked at some similar issues, but the proposed solutions do not work.

- Setting
```dayjs.tz.setDefault(Timezone)```
doesn't affect picker behaviour

- Passing
```format={ date => date.utc().format("YYYY-MM-DD HH:mm")}```
changes the display datetime to utc, but picked datetime and displayed one do not match (e.g. I click 15:00 and picker will show 14:00) which is not what I need

- I know could convert the time to utc on Form submission but if I clicked *Now*, I would select user current time, not utc as I need

One more thing is that I need for this to work with uncontrolled ```<Form />```, so passing value would not solve it.

### What does the proposed API look like?

 ```
<DatePicker
  timezone='Europe/London'
  ...restProps
  />
```

**Comment by carmenchapa** [comment]
This [issue](https://github.com/ant-design/ant-design/issues/45880) is similar but it is closed and it's priori to antd using Dayjs by default

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/45502

**Comment by carmenchapa** [comment]
@afc163 
> #45502

This only sets the value of the picker to certain current timezone, but the picker does not behave as if it is in a certain timezone. Is not solving the need I mention

**Comment by afc163** [comment]
Could you try https://day.js.org/docs/en/timezone/set-default-timezone and provide a reproduce if that doesn't work.

**Comment by ipsips** [comment]
i can conbfirm that `tz.setDefault(data.timezone);` does not help this. @afc163 no repro, sry, but do you have a repro somewhere that works as expected with `tz.setDefault(data.timezone);`?
