### ISSUE TITLE
Anchor not updating when scrolling

### ISSUE THREAD

**Issue by bertilvdk** [ant-design/ant-design#45881]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-antd-5-11-1-forked-ts8838?file=/demo.tsx)

### Steps to reproduce

Clicking on an anchor does scroll to the selected section, but scrolling inside of the drawer does not change the selection of the current anchor (e.g. scrolling manually from "Info" to "Options" does not show "Options" in blue)

### What is expected?

The current scroll position is reflected in the anchor elements

### What is actually happening?

The last selected anchor stays selected

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |
| System | macOS Sonoma Version 14.0 (23A344) |
| Browser | Chrome |

**Comment by afc163** [comment]
getContainer should return a scrollable contianer: https://codesandbox.io/s/basic-antd-5-11-1-forked-2pwxfy
