### ISSUE TITLE
官网搜索框 主题颜色错误

### ISSUE THREAD

**Issue by transitiongo** [ant-design/ant-design#45887]
### Reproduction link

[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce

详见视频：https://www.youtube.com/watch?v=CxS3pzw_4hI 

### What is expected?

默认应该是浅色主题

### What is actually happening?

默认是深色主题

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | react |
| System | macos  |
| Browser | chrome 版本 119.0.6045.123（正式版本） (arm64) |

**Comment by zombieJ** [comment]
试了一下重现不出来，审查元素看看这个样式是哪儿来的？

**Comment by transitiongo** [comment]
![image](https://github.com/ant-design/ant-design/assets/26265969/328368fe-764d-495e-82fc-b73182891994)

**Comment by MadCcc** [comment]
切换过亮暗色了吧，这个和 dumi 的 color-scheme 有关，需要修复一下
刷新应该就好了

**Comment by transitiongo** [comment]
![image](https://github.com/ant-design/ant-design/assets/26265969/6ed91cff-4f0d-423e-87df-0f3472632d47)

**Comment by transitiongo** [comment]
没切换过，一直这样，好久了都，就提了个，其实没啥影响😊

**Comment by transitiongo** [comment]
应该是切换过的，无痕是没有问题的

**Comment by transitiongo** [comment]
应该是localStorage的值没有及时更新导致的
