### ISSUE TITLE
Table filterDropdown - Dropdown props

### ISSUE THREAD

**Issue by YuvalPeretz** [ant-design/ant-design#45898]
### What problem does this feature solve?

It allows the developer to have access to the full dropdown properties of the `table`'s `filterDropdown`.
For example, in my case I want to have the ability to enable the " `destroyPopupOnHide` " property of the `Dropdown`, which I don't have access to.

This is very similar to the `menu - MenuProps` property in the `Dropdown`, which overrides the properties of the `menu` inside of the `Dropdown`.

### What does the proposed API look like?

`filterDropdownProps` - `DropdownProps` (url: https://ant.design/components/dropdown#api)

**Comment by MadCcc** [comment]
https://ant.design/components/table#components-table-demo-custom-filter-panel
Try to write Dropdown yourself.

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/issues/45898
