### ISSUE TITLE
Hydrate style file will make selector priority mass

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#45894]
### Reproduction link

[https://ant-design.antgroup.com/](https://ant-design.antgroup.com/)

### Steps to reproduce

* Open https://ant-design.antgroup.com/
* In current browser tab go to tab page

### What is expected?

Preset color Tag style work

### What is actually happening?

Preset color Tag style override by default Tag style

<img width="400" alt="截屏2023-11-15 17 22 43" src="https://github.com/ant-design/ant-design/assets/5378891/83642494-325b-436f-9e4b-cd494fc052cb">

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | latest |
| System | any |
| Browser | any |

**Comment by infodusha** [comment]
That actually seems to be related the fact that for SSR mode style tag may lose attributes
