### ISSUE TITLE
使用table时添加的expandedRowRender不执行

### ISSUE THREAD

**Issue by jun95585** [ant-design/ant-design#4590]
` <Table`
`                    dataSource={props.data}`
`                    columns={columns}`
`                    pagination={false}`
`                    expandedRowRender={record => <p>{record.description}</p>}`
`                    />`
点击行前➕不会显示展开行

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

---

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by yesmeck** [comment]
没 rowKey 应该有警告的。

**Comment by hansnow** [comment]
正确设置dataSource中每一项key，或者给Table设置rowKey
