### ISSUE TITLE
Button组件同时添加href、disabled属性，在按钮上鼠标右键点击，选择在新标签页打开链接，可以直接跳转

### ISSUE THREAD

**Issue by JohniFirst** [ant-design/ant-design#45904]
### Reproduction link

[https://www.打不开沙盒链接.com](https://www.打不开沙盒链接.com)

### Steps to reproduce

<Button type="primary" danger href="http://www.baidu.com" disabled>
       删除
  </Button>

鼠标右键点击  ---->  在新标签页打开/在新窗口打开  ---->   成功跳转

### What is expected?

不能成功进行跳转

### What is actually happening?

成功跳转

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | 119.0.2151.58 (正式版本) (64 位) |

**Comment by JohniFirst** [comment]
We can fix this issue like this
![image](https://github.com/ant-design/ant-design/assets/106364743/2a7bdab2-17f3-4cb5-8145-a168b8d75785)

**Comment by MadCcc** [comment]
这个不好做，只能通过 `pointer-events: none` 来禁止 native 的操作，但这会导致 Tooltip 等组件套在 Button 上时失效
