### ISSUE TITLE
在SSR整体样式导出中存在 .css-dev-only-do-not-override-

### ISSUE THREAD

**Issue by yanggaoji** [ant-design/ant-design#45903]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-hrzyqp?file=%2Fscript%2FexportCSS.js%3A6%2C28&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clozty3tl00063r6kf2e8xrdl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clozty3tl00033r6kvfekql5s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clozty3tl00043r6kb446915u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clozty3tl00053r6kfnt0qac1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clozty3tl00033r6kvfekql5s%2522%253A%257B%2522id%2522%253A%2522clozty3tl00033r6kvfekql5s%2522%252C%2522activeTabId%2522%253A%2522clozu1fao00q83r6k7b6nedn6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clozty3tk00023r6k8yzwilov%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clozu0u1o00g63r6k5q914zyd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fscript%252Fantd.min.css%2522%252C%2522id%2522%253A%2522clozu1fao00q83r6k7b6nedn6%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clozty3tl00053r6kfnt0qac1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clozty3tl00053r6kfnt0qac1%2522%257D%252C%2522clozty3tl00043r6kb446915u%2522%253A%257B%2522id%2522%253A%2522clozty3tl00043r6kb446915u%2522%252C%2522activeTabId%2522%253A%2522clozu034c00dn3r6kjrz5d9sm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clozu034c00dn3r6kjrz5d9sm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clozu044t000eegd170mm574o%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

直接执行node exportCSS.js

### What is expected?

尝试使用remix导入css，能够正常显示

### What is actually happening?

显然类名不匹配，无样式

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | WIN 11 |
| Browser | Microsoft Edge 119 |

---
希望执行extractStyle的时候去除。

**Comment by MadCcc** [comment]
dev 环境下才会有这个标识，而且是 SSR 兼容的

**Comment by zombieJ** [comment]
打包需要配置 `NODE_ENV` 到 `production`，你如果是 node 执行脚本，也需要把环境变量填上。
