### ISSUE TITLE
【BUG】抽屉里面使用Modal弹窗，Modal弹窗里面在使用modal.confirm，modal.confirm的zIndex不对

### ISSUE THREAD

**Issue by zhengmenghuang** [ant-design/ant-design#45912]
### Reproduction link

关联问题

[https://github.com/ant-design/ant-design/pull/45346](https://github.com/ant-design/ant-design/pull/45346)

复现demo
https://codesandbox.io/s/ji-chu-chou-ti-antd-5-11-1-forked-pgdcpf

### Steps to reproduce

1. 打开Drawer
2. 打开Modal
3. 打开Modal 静态方法 modal.confirm

### What is expected?

弹窗里面的弹窗层级正确

### What is actually happening?

弹窗里面的弹窗层级不正确

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.37 |
| System | Windows 11 |
| Browser | chrome119 |

---
https://github.com/ant-design/ant-design/pull/45346
这个提交的 优化 Modal、Select 组件 z-index  优化所引发的bug

**Comment by afc163** [comment]
Fixed in 4.11.2 https://github.com/ant-design/ant-design/pull/45911
