### ISSUE TITLE
TreeSelect组件的已选框没法显示树节点的路径

### ISSUE THREAD

**Issue by q1uxu** [ant-design/ant-design#45917]
### What problem does this feature solve?

 ```
{
    value: 'zhejiang',
    label: 'Zhejiang',
    children: [
      {
        value: 'hangzhou',
        label: 'Hangzhou',
        children: [
          {
            value: 'xihu',
            label: 'West Lake',
          },
        ],
      },
    ],
  }
```
像上面这样的数据，在Cascader组件的value是xihu时，它的已选输入框显示的是 “Zhejiang / Hangzhou / West Lake”。
TreeSelect显示的“West Lake”，没法直观看到它的上级节点有哪些。
希望TreeSelect的已选输入框也能展示 “Zhejiang / Hangzhou / West Lake”。

### What does the proposed API look like?

TreeSelect组件增加一个prop，跟Cascader组件的displayRender prop一样。

**Comment by zombieJ** [comment]
两者设计上是不同的，如果你有定制 label 的需求使用 `labelInValue` 或者 `treeNodeLabelProp` 实现即可。
