### ISSUE TITLE
RangeDatePicker's inputRender prop handling

### ISSUE THREAD

**Issue by what3verCODE** [ant-design/ant-design#45918]
### What problem does this feature solve?

At the moment inputRender only supported with basic DatePicker's. Would be nice to have it for range pickers too.

### What does the proposed API look like?

Issue for react-components already exist: https://github.com/react-component/picker/issues/684
Also tried to make PR too, need to review: https://github.com/react-component/picker/pull/686

**Comment by what3verCODE** [comment]
@zombieJ can u have a look please, would be nice to have that kind of 'feature' or it is a bug

**Comment by zombieJ** [comment]
`inputRender` will be removed in next major version which will be replaced with `components` for all the customize component part.

**Comment by zombieJ** [comment]
It will be in v5. You can follow my progress here: https://github.com/react-component/picker/pull/691

PS: Since there exist over 100+ issue related with DatePicker, it does need much time on this : )

**Comment by what3verCODE** [comment]
> It will be in v5. You can follow my progress here: [react-component/picker#691](https://github.com/react-component/picker/pull/691)
> 
> PS: Since there exist over 100+ issue related with DatePicker, it does need much time on this : )

Thank you for the answer. Waiting this task so hard
