### ISSUE TITLE
Cascader 二级菜单展开自动重新定位

### ISSUE THREAD

**Issue by sam019** [ant-design/ant-design#4591]
- antd version: 2.5.3
- OS and its version: macOS 10.12.2
- Browser and its version: chrome 55 64bit

Cascader组件展开二级菜单时，会改变展开位置。
如默认placement为bottomLeft，展开二级菜单时，会按bottomRight定位
http://codepen.io/liangsen/pen/wgGmGa
希望能够避免自动重新定位，或者可以选择是否自动重新定位

**Comment by afc163** [comment]
这是一个优化，如果不自动定位，二级菜单可能就点不到了。

**Comment by sam019** [comment]
可是有时候明明离屏幕边缘有很大空间，还是会自动重新定位。是如何判断剩余空间是否足够的呢？有办法强制性的不进行自动重新定位吗？

**Comment by afc163** [comment]
不急，我来看看~ 如果着急的话也可以尝试直接给 http://github.com/react-component/cascader/  提 PR。

**Comment by afc163** [comment]
目前可以先用覆盖 builtPlacements 来达到这个目的。http://react-component.github.io/cascader/examples/adjust-overflow.html
