### ISSUE TITLE
[Upload] File selection window opens twice when using the keyboard

### ISSUE THREAD

**Issue by SpaNb4** [ant-design/ant-design#45922]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5qvddr?file=/index.js)

### Steps to reproduce

1) Press `Tab` twice to focus on the "Click to Upload" button (you need to press the key twice because the focus first shifts to the wrapper with tabindex="0", which may also confuse users who navigate using the keyboard)
2) Press `Enter` to open the file selection window
3) Press `ESC` to close the file selection window

### What is expected?

No additional window appears

### What is actually happening?

Another file selection window appears

### Additional info
I could not reproduce this issue when using the native html button.

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | Pop!_OS 22.04 |
| Browser | 119.0.6045.123 |

**Comment by liangkuku** [comment]
After removing the tabIndex attribute from the upload button wrapper span, pressing the tab key will directly focus on the button element. [PR 520](https://github.com/react-component/upload/pull/520)
