### ISSUE TITLE
Antd locale with Next.js Server Components

### ISSUE THREAD

**Issue by WhoAmIRUS** [ant-design/ant-design#45931]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/kind-easley-gsxnrn?file=%2Fapp%2Fpage.js%3A6%2C32)

### Steps to reproduce

- start dev
- open DatePicker

### What is expected?

names of months and week days in zh_CN locale

### What is actually happening?

Names of months and week days in en locale. But when we set 'use client' at the top of file we receive right result.

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | MacOS Sonoma |
| Browser | Google Chrome |

---
It is problem with Server Components in Next.js

**Comment by MadCcc** [comment]
Should be set with dayjs locale. The locale of antd is right.

**Comment by MadCcc** [comment]
DatePicker renders in client, which will not call the locale of dayjs.
Just add `use client` in files where dayjs impoted.

**Comment by MadCcc** [comment]
Should add FAQ。

**Comment by WhoAmIRUS** [comment]
Tanks, I add DayJSLocale component to global layout

`'use client';

import 'dayjs/locale/zh-cn';

const DayJSLocale = () => null;

export default DayJSLocale;`
