### ISSUE TITLE
form.item 在传递 label 时冒号的问题

### ISSUE THREAD

**Issue by lucky3mvp** [ant-design/ant-design#4593]
在给 form.itme 传递 label 时，页面上不显示冒号

使用方式如下：
```
<FormItem label='用户名'  >
{getFieldDecorator('userName')(
	<Input />
)}
</FormItem>
````
就算是给 label 的值是: '用户名：'，页面上也是只显示'用户名'，没有冒号，跟官方的例子似乎有出入。。。

antd version: 2.5.3
react version: 15.2.1

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by lucky3mvp** [comment]
@afc163 sorry...... updated

**Comment by lucky3mvp** [comment]
@yesmeck  在 codepen 里试了一下，又是有冒号的。。。好奇怪。。。为什么我自己的页面没有。。我再检查检查我的代码。。。

**Comment by lucky3mvp** [comment]
@yesmeck sorry, 请看这个：http://codepen.io/lucky3mvp/pen/apZvmq?editors=1010

**Comment by yesmeck** [comment]
看代码 vertical 没收就是不显示冒号的。

**Comment by lucky3mvp** [comment]
@yesmeck soga...之前是我搞错了，sorry sorry

**Comment by afc163** [comment]
这里有两个问题：

1. 你的问题，按 @yesmeck 所说，vertical 模式没有冒号，你也不应该用 vertical 模式去加栅格布局。
2. 我们的问题，vertical 模式下没有冒号，也不应该有强制去掉 label 中冒号的逻辑。https://github.com/ant-design/ant-design/blob/eeae03d681d71433410ed0e491720f1555b6db24/components/form/FormItem.tsx#L225

感谢反馈~

**Comment by lucky3mvp** [comment]
@afc163 恩，是的，我一开始搞混了，谢谢
