### ISSUE TITLE
Message and Notification appears in the wrong z-Index when inside more than 1 Modal

### ISSUE THREAD

**Issue by joseAAlexandre** [ant-design/ant-design#45933]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-4zrx9t)

### Steps to reproduce

Open the first Modal and click in the Message call.

Open the second Modal and click in the Message call.

### What is expected?

The second Message needs to open in the same level that second Modal

### What is actually happening?

The second Message appears at the level of the first Modal

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Microsoft Edge Version 119.0.2151.58 (64 bits) |

---
Same occurs with component Notification

**Comment by MadCcc** [comment]
Should be fixed in https://github.com/ant-design/ant-design/pull/45911
