### ISSUE TITLE
tour组件配置arrow不生效

### ISSUE THREAD

**Issue by lajidemo** [ant-design/ant-design#45936]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wei-zhi-antd-5-11-0-forked-fjtn2c?file=/demo.tsx)

### Steps to reproduce

steps配置arrow

### What is expected?

引导不居中显示

### What is actually happening?

引导居中显示

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | ^18.0.0 |
| System | window |
| Browser | chrome 103 |

---
我看tour组件传的arrowPointAtCenter默认为true
https://github.com/ant-design/ant-design/blob/5.11.0/components/tour/index.tsx#L44
拿到的 builtinPlacements 又覆盖了 restProps
https://github.com/ant-design/ant-design/blob/5.11.0/components/tour/index.tsx#L80

**Comment by MadCcc** [comment]
在 steps 里指定的 arrow 需要覆盖
