### ISSUE TITLE
Modal.methods 静态方法打开弹窗默认没有关闭按钮

### ISSUE THREAD

**Issue by nanwy** [ant-design/ant-design#45930]
### Reproduction link

[https://ant.design/components/modal-cn#modal-demo-hooks](https://ant.design/components/modal-cn#modal-demo-hooks)

### Steps to reproduce

给modal.methods的config传入closeIcon后，点击按钮，打开弹窗
```
const config = {
  title: 'Use Hook!',
  closeIcon: <div>关闭</div>,
  content: (
    <>
      <ReachableContext.Consumer>{(name) => `Reachable: ${name}!`}</ReachableContext.Consumer>
      <br />
      <UnreachableContext.Consumer>{(name) => `Unreachable: ${name}!`}</UnreachableContext.Consumer>
    </>
  ),
};
```

### What is expected?

使用modal静态方法打开弹窗，
如果参数没有closeIcon，展示默认关闭按钮CloseOutlined 
如果参数有closeIcon，展示传入的自定义关闭按钮

### What is actually happening?

使用modal静态方法打开弹窗
参数包含closeIcon，点击按钮，打开弹窗， 没有展示自定义关闭按钮
参数不包含closeIcon，点击按钮，打开弹窗， 也没有展示默认关闭按钮CloseOutlined 

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | windows |
| Browser | chrome119 |

---
看commit记录https://github.com/ant-design/ant-design/commit/378b54281bdf498135ef46e2145d2423c5946235#diff-7a204621cc9425007680c097ad01151df377979692bbc09eb2796025b85043f3
将closable的api删掉了，但是必须对静态方法传closeable才会展示关闭按钮，仅传closeIcon不会展示关闭按钮，貌似没有对静态方法的closeIcon逻辑做处理。
```
const config = {
  title: 'Use Hook!',
  closable:true,
  content: (
    <>
      <ReachableContext.Consumer>{(name) => `Reachable: ${name}!`}</ReachableContext.Consumer>
      <br />
      <UnreachableContext.Consumer>{(name) => `Unreachable: ${name}!`}</UnreachableContext.Consumer>
    </>
  ),
};
```

**Comment by zombieJ** [comment]
设计如此。静态方法默认不展示关闭按钮，需要展示关闭按钮通过 `closable` 配置：

```diff
  const config = {
++  closable: true,
    title: 'Use Hook!',
    content: (
```

https://codesandbox.io/s/shi-yong-hooks-huo-de-shang-xia-wen-antd-5-11-1-forked-cgtvp5?file=/demo.tsx:239-308

**Comment by nanwy** [comment]
> 设计如此。静态方法提供的信息设计上需要用户去确认，包括 右上角关闭图标、背景点击关闭 都是禁用掉的。需要展示关闭按钮通过 `closable` 配置：
> 
> ```diff
>   const config = {
> ++  closable: true,
>     title: 'Use Hook!',
>     content: (
> ```
> 
> https://codesandbox.io/s/shi-yong-hooks-huo-de-shang-xia-wen-antd-5-11-1-forked-cgtvp5?file=/demo.tsx:239-308

目前5.11的文档中静态方法并没有closable的描述了，这个是不是应该保留，以及closeIcon的默认值和实际表现也是不一致的。
