### ISSUE TITLE
Modal搭配Form使用时，Modal设置了destroyOnClose，Form也设置了<Form preserve={false} />，但是 Modal 关闭时也没有销毁表单字段数据。

### ISSUE THREAD

**Issue by HaiJunCai8** [ant-design/ant-design#45943]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jing-tai-que-ren-dui-hua-kuang-antd-5-11-1-forked-phgx98?file=/demo.tsx)

### Steps to reproduce

1、点击新增按钮，弹框出现后点击关闭
2、随后点击修改按钮，此时弹框中的数据不会反显，需要关闭再次点击修改按钮时，此时出现的弹框数据才会正常反显
3、如果再次关闭，然后再点击新增按钮时，弹框里面的内容是反显的，需要再次点击一次，弹框才会出现空白的表单

### What is expected?

Modal关闭时销毁表单数据

### What is actually happening?

Modal关闭时没有销毁表单数据

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | windows |
| Browser | 谷歌浏览器-119.0.6045.124 |

**Comment by MadCcc** [comment]
Reproduction 没有复现问题

**Comment by HaiJunCai8** [comment]
@MadCcc 我刚才又进去点了，一点就复现了啊，你点击新增，什么都不做，关闭弹框，然后点击修改按钮，出现的是空白的弹框表单，关闭后再点击修改就可以正常反显表单数据了

**Comment by crazyair** [comment]
Modal+Form 在使用上有个不方便的地方，推荐这个，https://zhuanlan.zhihu.com/p/388222294，让 Form 在 Modal 里面，随 Modal 打开则初始化 form，关闭卸载 form

**Comment by HaiJunCai8** [comment]
> Modal+Form 在使用上有个不方便的地方，推荐这个，https://zhuanlan.zhihu.com/p/388222294 ，让 Form 在 Modal 里面，随 Modal 打开则初始化 form，关闭卸载 form

但是官网上这里：<Modal /> 和 Form 一起配合使用时，设置 destroyOnClose 也不会在 Modal 关闭时销毁表单字段数据，需要设置 <Form preserve={false} />。这个不就是解决这个问题的吗，上面代码里设置了为啥效果不可以呢，这个我不是很理解，望大佬解惑

**Comment by crazyair** [comment]
> > Modal+Form 在使用上有个不方便的地方，推荐这个，https://zhuanlan.zhihu.com/p/388222294 ，让 Form 在 Modal 里面，随 Modal 打开则初始化 form，关闭卸载 form
> 
> 但是官网上这里： 和 Form 一起配合使用时，设置 destroyOnClose 也不会在 Modal 关闭时销毁表单字段数据，需要设置
> 
> 。这个不就是解决这个问题的吗，上面代码里设置了为啥效果不可以呢，这个我不是很理解，望大佬解惑

destroyOnClose 只是一部分，是在你没用 useForm 的前提下，如果用了，还需要其他的处理

**Comment by crazyair** [comment]
你可以把 useForm 去掉看下效果，虽然这个 demo 能解决了，如果你下次要用 useForm 就还要做别的处理，使用频繁的话，建议还是推荐封装一次

**Comment by HaiJunCai8** [comment]
> 你可以把 useForm 去掉看下效果，虽然这个 demo 能解决了，如果你下次要用 useForm 就还要做别的处理，使用频繁的话，建议还是封装一次

好的，感谢大佬的建议，我去实验下

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21740#issuecomment-644008703

**Comment by afc163** [comment]
1. 你应该用 state 来管理表单初始值的，然而你用了 ref，这会出现更多诡异情况。
2. `preserve={false}` 的意义是不保存表单内因为用户修改而保存的初始值，而 initialValues 不属于这个范围，表单打开时候的内容完全取决于 Form 渲染那一刻时传递的 initialValues。

`preserve={false}`是有效的，可以看这里的 codesandbox：https://github.com/ant-design/ant-design/issues/21740#issuecomment-660825508
