### ISSUE TITLE
ant design 表格有没有colums根据权限或者状态来判断是否展示这一列？

### ISSUE THREAD

**Issue by cangsnage** [ant-design/ant-design#45942]
### What problem does this feature solve?

ant design 表格有没有colums根据权限或者状态来判断是否展示这一列？

### What does the proposed API look like?
没有找到相对应的api
![image](https://github.com/ant-design/ant-design/assets/25116493/496b6676-94d3-4d9f-8275-366a635b48f1)

**Comment by afc163** [comment]
你可以在代码中对 columns 进行控制，无权限的就去掉对应的 column 即可。
