### ISSUE TITLE
Popconfirm

### ISSUE THREAD

**Issue by lsxqer** [ant-design/ant-design#45959]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-snow-7h872n?file=/src/App.tsx)

### Steps to reproduce

![Uploading image.png…]()

### What is expected?

没有警告

### What is actually happening?

有警告

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | react版本 |
| System | macos |
| Browser |  Microsoft Edge	119.0.2151.58 (正式版本) (arm64)  修订	33e26e7eb4fba096f2f29de91f90d34b8597be96 Chromium 版本	119.0.6045.123 操作系统	macOS 版本14.0（版号23A344） JavaScript	V8 11.9.17.7 |

---

strict-mode-find-node 禁用了findDomnode， 这是在开发环境，严格模式下，如果不开启就没有警告

**Comment by afc163** [comment]
https://codesandbox.io/s/adoring-wildflower-p9v2l2
