### ISSUE TITLE
Incorrect operation of the menu component

### ISSUE THREAD

**Issue by xDiezz** [ant-design/ant-design#45952]
### Reproduction link
[link](https://codesandbox.io/s/antd-reproduction-template-forked-wv5r3c?file=/index.js)

### Steps to reproduce

1. Make a horizontal menu from two items
2. Make the label of the first item seven russian letters long

### What is expected?

A menu with two labels is displayed

### What is actually happening?

The menu is displayed with only one label, instead of the second there are three dots

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | 18.2.0 |
| System | macOS Sohoma 14 |
| Browser | Chrome 118.0.5993.88 |

---
If the label length is 6 or 8 letters then everything works correctly

**Comment by xDiezz** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-wv5r3c?file=/index.js

**Comment by MadCcc** [comment]
Try to wrap Menu with container styled `width: 0`.
It is problem in flex layout.
