### ISSUE TITLE
使用Modal.confirm()生成的对话框,mask出现有动画延时,导致触发Modal.confirm()的按钮可以被重复点击

### ISSUE THREAD

**Issue by 513205785Xie** [ant-design/ant-design#45954]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mccg87?file=/index.js:288-295)

### Steps to reproduce

短时间连续点击两次“提示”按钮

### What is expected?

mask浮层一点击就加载, 淡入动画只作用于modal内容层

### What is actually happening?

淡入动画作用于整个modal外层, mask不能及时加载覆盖底层dom

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | "react": "18.2.0" |
| System | macOS 12.5.1 |
| Browser | chrome 119.0.6045.159 |

**Comment by afc163** [comment]
你是说这个按钮被重复触发？

<img width="346" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/1dfe2840-cd1e-4e75-b98c-ebaf2462f924">

这个目前看不属于 Modal.confirm 的负责范畴，需要你自行在触发逻辑中避免，比如点击后加上 loading。

**Comment by afc163** [comment]
看上去可以修一下，跟踪 https://github.com/ant-design/ant-design/issues/46129
