### ISSUE TITLE
移动端 : 需要阻止Select控件弹出输入法

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#45963]
### Reproduction link

[https://ant.design/components/select-cn](https://ant.design/components/select-cn)

### Steps to reproduce

可以下载该插件, 演示在移动端上的显示效果, https://chromewebstore.google.com/detail/%E4%BA%8C%E7%BB%B4%E7%A0%81%E7%94%9F%E6%88%90%E5%99%A8-quick-qr/afpbjjgbdimpioenaedcjgkaigggcdpp
antd 的 Select 组件, 点击时会弹出输入法, 
而 mantine 的 select 空间, 不弹出输入法, 参考: 希望移动端Select 时,不要唤起输入法

### What is expected?

希望移动端Select 时,不要唤起输入法

### What is actually happening?

移动端Select 时,会唤起输入法

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
注意不要开启搜索功能就行了。
