### ISSUE TITLE
ant menu 不选中的问题

### ISSUE THREAD

**Issue by cangsnage** [ant-design/ant-design#45967]
### What problem does this feature solve?

我想可以用selectedKeys控制不让他选中种状态

### What does the proposed API look like?

![image](https://github.com/ant-design/ant-design/assets/25116493/3f9769fe-41ac-41e5-b70c-8f545f0b12e5)
导航栏有两个，左侧用的是ant pro 的layout 的menu组件，右侧用的是ant design 的menu菜单导航组件。但是我页面点击右侧菜单选中，然后又点击左侧菜单，怎么吧右侧菜单的key 给去掉呢不让他选中样式

**Comment by MadCcc** [comment]
`selectedKeys={[]}`
