### ISSUE TITLE
Input组件 type="number"，获取焦点的时候无法阻止鼠标滚轮滚动修改数据

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#45961]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-5-11-2-forked-3zrlpy?file=/demo.tsx)

### Steps to reproduce

获取输入框的焦点，输入数字，滚动鼠标滚轮就可以更改数据

### What is expected?

至少能支持 onmousewheel 方法让我们自己阻止滚轮时间

### What is actually happening?

onmousewhee l方法 ts 报错

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | React17/18 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by zombieJ** [comment]
`mousewheel` 是非标事件：
https://developer.mozilla.org/zh-CN/docs/Web/API/Element/mousewheel_event

你或许需要 `wheel` 事件？
https://developer.mozilla.org/zh-CN/docs/Web/API/Element/wheel_event

**Comment by Ali-ovo** [comment]
> `mousewheel` 是非标事件： https://developer.mozilla.org/zh-CN/docs/Web/API/Element/mousewheel_event
> 
> 你或许需要 `wheel` 事件？ https://developer.mozilla.org/zh-CN/docs/Web/API/Element/wheel_event

😯 ，但是貌似 wheel 也无法阻止鼠标滚动修改数据的这个问题

**Comment by afc163** [comment]
> onmousewhee l方法 ts 报错

> 😯 ，但是貌似 wheel 也无法阻止鼠标滚动修改数据的这个问题

给个重现？

**Comment by Ali-ovo** [comment]
> > onmousewhee l方法 ts 报错
> 
> > 😯 ，但是貌似 wheel 也无法阻止鼠标滚动修改数据的这个问题
> 
> 给个重现？

上面的链接里加上这个事件就会发现不生效了  或者这个方法根本就没办法阻止输入框更改数据？

**Comment by afc163** [comment]
> 上面的链接里加上这个事件就会发现不生效了 或者这个方法根本就没办法阻止输入框更改数据？

你试一下原生 `<input type="number" />` ？这个问题是不是和 antd 没啥关系？

**Comment by yyz945947732** [comment]
这个问题我之前也遇到过，跟 antd 没关系，跟 chorme 的[更新](https://chromestatus.com/feature/5093566007214080)有关，一些事件对象被默认设为 `passive` 的了，所以 `event.preventDefault()` 是不会生效的，你的案例在控制台也是能看到报错的。

<img width="511" alt="image" src="https://github.com/ant-design/ant-design/assets/47586954/bda66d9f-a79d-44d9-b69d-d0ba868de642">

你可以试试这样写：

```js
import React, { useEffect, useRef } from "react";
import "./index.css";
import { Input } from "antd";

const App: React.FC = () => {
  const ref = useRef(null);

  useEffect(() => {
    if (ref.current) {
      ref.current.input.addEventListener("wheel", handleWheel);
    }
  }, []);

  const handleWheel = (event) => {
    event.stopPropagation();
    event.preventDefault();
  };

  return (
    <Input
      ref={ref}
      onWheel={(e) => e.preventDefault()}
      placeholder="Basic usage"
      type="number"
    />
  );
};

export default App;
```
