### ISSUE TITLE
Why not use prefix- instead of ant- in test?

### ISSUE THREAD

**Issue by xiaosansiji** [ant-design/ant-design#45966]
### Steps to reproduce

https://github.com/ant-design/ant-design/blob/cb56ddddd130e35f42f3f5f5dfbf87f835687562/components/affix/__tests__/Affix.test.tsx#L80

### What is expected?

use `defaultPrefixCls` variables instead of hardcode `ant-`, just like:
``` js
 import * as React from 'react';
 import demoTest, { rootPropsTest } from '../../../tests/shared/demoTest';
+import { defaultPrefixCls } from 'antd/es/config-provider';
 
 demoTest('cascader', {
   testRootProps: false,
 });
 
 rootPropsTest('cascader', (Cascader, props) => <Cascader {...props} />, {
-  findRootElements: () => document.querySelectorAll('.ant-cascader, .ant-cascader-dropdown'),
+  findRootElements: () => document.querySelectorAll(`.${defaultPrefixCls}-cascader, .${defaultPrefixCls}-cascader-dropdown`),
   expectCount: 2,
 });
```

### What is actually happening?

hardcode `ant-`

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | react |
| System | Mac |
| Browser | Chrome |

**Comment by xiaosansiji** [comment]
I konw that the prefix may not be changed in the future... but using prefix variables may be a better solution than hardcoding.
If I have a forked or HOC wrapped antd components, I can just reuse these test script.
If you agree with this change, please let me know. 
I can start a PR to modify them. ❤️

**Comment by Wxh16144** [comment]
It feels like a lot of work.

**Comment by xiaosansiji** [comment]
> It feels like a lot of work.

I searched and found about 150 files. 🥹

**Comment by Wxh16144** [comment]
> I can just reuse these test script.

reminds me of an earlier [discussion #42032](https://github.com/ant-design/ant-design/discussions/42032), maybe try it in that direction?

**Comment by Wxh16144** [comment]
It's better to wait for feedback from the core members, it's not too late to confirm it before you start 😄

**Comment by xiaosansiji** [comment]
Wow~ that's interesting: an independent, reusable testing library
I'll see what I can do to help.

**Comment by MadCcc** [comment]
Test is used for covering use cases, whitch is not strongly related with `prefix`.
We could test `prefixCls` for some special use case, but it's not necessary for every case.

**Comment by MadCcc** [comment]
As @Wxh16144 mentioned, any test library for antd is welcome~ 
Closing this issue cuz no necessary to do great change for antd's own tests.
