### ISSUE TITLE
在Form组件onValuesChange中setFieldsValue设置的值不对

### ISSUE THREAD

**Issue by U1in** [ant-design/ant-design#45977]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ji-ben-shi-yong-antd-4-24-12-forked-4glcwv?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

表单中输入123，

### What is expected?

执行替换，展示123,

### What is actually happening?

展示123,,

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.0 |
| System | win11 |
| Browser | 版本 119.0.6045.160（正式版本） （64 位） |

---
想帮用户纠错，把中文逗号转换成英文逗号，或许不是正确的使用方式？

**Comment by crazyair** [comment]
可以看下 https://zhuanlan.zhihu.com/p/375753910 `如何将 RangePicker 数组一分为二` 部分

**Comment by afc163** [comment]
我这里测试是好的，不过你这个场景我更推荐用 normalize：https://codesandbox.io/embed/ji-ben-shi-yong-antd-4-24-12-forked-4glcwv?fontsize=14&hidenavigation=1&theme=dark

**Comment by crazyair** [comment]
> 我这里测试是好的，不过你这个场景我更推荐用 normalize：
> 
> https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-12-forked-8df6j6?file=/demo.js

哦，对，这个需要肉眼看到也是转换过的

**Comment by U1in** [comment]
> 我这里测试是好的，不过你这个场景我更推荐用 normalize：
> 
> https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-12-forked-8df6j6?file=/demo.js

好的，那我使用normalize，这个问题确实在我电脑上存在，如果在你们那边验证不出来那就不理会吧。
