### ISSUE TITLE
PopConfirm inside of Dropdown closes immediately after opening

### ISSUE THREAD

**Issue by kyle-mcr** [ant-design/ant-design#45972]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dropdown-popconfirm-bug-6d5xtt?file=/index.js)

### Steps to reproduce

Click three dots menu and then click a menu item.

### What is expected?

PopConfirm to stay open until another action is preformed.

### What is actually happening?

PopConfirm flashes open and then closes immediately. 

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | React 18.3.0 |
| System | MacOs 14.1.1 |
| Browser | Chrome 119.0.6045.123 |

---
I saw a Bug for this in 2020 but never found a resolution.

**Comment by MadCcc** [comment]
It's because you used `destroyPopupOnHide` in Dropdown. And Dropdown will close when you clicked by default unless you control the `open` prop.

**Comment by kyle-mcr** [comment]
@MadCcc I am still unable to get this working as expected and it seems the same issue as this: [](https://github.com/ant-design/ant-design/issues/22578). It is almost working using the open prop, but am having an issue when clicking outside of dropdown menu it does not close. Is there a solution? It feels like a bug still: [](https://codesandbox.io/p/sandbox/react-antd-popconfirm-bug-sgsncd?file=%2Fsrc%2Findex.js%3A9%2C63)

**Comment by kyle-mcr** [comment]
NVM, resolved here: [Code sandbox](https://codesandbox.io/p/sandbox/react-antd-popconfirm-bug-fix-sgsncd?file=%2Fsrc%2Findex.js%3A33%2C34) using ->> `onClick={(e) => e.stopPropagation()` on my menu items.

**Comment by AttackXiaoJinJin** [comment]
@kyle-mcr thank you! your solution saved my time!

@MadCcc  can you reopen this issue？the behavior is different with antd4.x
