### ISSUE TITLE
建议 Select 选择器的 onChange 函数增加 option 参数方便回调

### ISSUE THREAD

**Issue by TimonPeng** [ant-design/ant-design#4597]
建议 Select 选择器的 onChange 函数像 onSelect 函数一样`function(value, option)`，可传入 option ，方便回调获取 props。

因为当赋值如 title、key 等 props 时，无法通过 onChange() 获取。

谢谢。

**Comment by yesmeck** [comment]
搜索的时候也会触发`onChange`，这个时候是没选择的 Option 的，给 `onChange`  传 Option 感觉会有点怪。

**Comment by yesmeck** [comment]
LZ 的需求其实可以通过让 `value` 支持 `any` 值解决。

**Comment by TimonPeng** [comment]
@yesmeck 什么`any`值？我没有理解。

**Comment by yesmeck** [comment]
就是 Option 的 value 可以是任意值，这样你要传给 `onChange` 的额外信息，都可以放在 `value` 里。 

```javascript
<Select>
  <Option value={{ x, y, z }}>Foo</Option>
</Select>
```

**Comment by TimonPeng** [comment]
@yesmeck 好的，理解了，谢谢。

**Comment by yesmeck** [comment]
@RaoHai

**Comment by RaoHai** [comment]
搜索的时候可以从 `Options` 里找对应的 `Option` 传回来的。。

**Comment by RaoHai** [comment]
如果任意 value:any  的话逻辑反而会多。选的时候是 object，输的时候是 string。

**Comment by yesmeck** [comment]
嗯，就传 Option  吧。

**Comment by benjycui** [comment]
ping~

**Comment by zyrepo** [comment]
有案例吗
