### ISSUE TITLE
关键字占用，冲突报错,https://codesandbox.io/s/antd-reproduction-template-forked-jshdv2

### ISSUE THREAD

**Issue by Zei8Shuai** [ant-design/ant-design#45983]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn](https://ant-design.antgroup.com/components/date-picker-cn)

### Steps to reproduce

datePicker的onChange回调方法中设置属性，更新对象报错
     “
  let [formObj, setFormObj] = useState({});
     <ConfigProvider locale={locale}>
                <DatePicker
                  format="YYYY.MM.DD"
                  placeholder="请选择立项时间"
                  value={formObj.createTime}
                  onChange={(date, value) => {
                    setFormObj((prev) => {
                      return { ...prev, createTime: value };
                    });
                  }}
                />
      </ConfigProvider>”
当onChange回调方法触发的时候，会报错Uncaught TypeError: date4.year is not a function，react_devtools_backend_compact.js:12966 The above error occurred in the <InnerPicker> component，经过我的尝试，将createTime更换一个名字，可以正常运行，疑似关键词冲突，我将formObj的set方法更换了一个名字后亦可以正常运行

### What is expected?

期望修复它和它相关的问题

### What is actually happening?

报错：
Uncaught TypeError: date4.year is not a function
react_devtools_backend_compact.js:12966 The above error occurred in the <InnerPicker> component

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18.2.0 |
| System | windows |
| Browser | Google |

**Comment by Zei8Shuai** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-jnxmwv

**Comment by yoyo837** [comment]
Value不是dayjs的值类型吧

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-gkcdds?file=/index.js 看看我这个

**Comment by yoyo837** [comment]
<img width="1117" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/fc68180a-2811-47db-aabf-999432f7dcb6">
