### ISSUE TITLE
Popover 内嵌 Mention

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4598]
在 Popover 内嵌 Mention，Mention 选择后 Popover 也一并关闭了。

**Comment by yesmeck** [comment]
要用 getSuggestionContainer  指定渲染位置吧，所有的 Trigger 嵌套都有这个问题。

**Comment by benjycui** [comment]
Popover 内嵌 Popover 之前好像解决过了 @afc163 ，但是相关 issue 我找不到了。。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3448

**Comment by RaoHai** [comment]
https://ant.design/components/mention/#components-mention-demo-popupContainer 这不是原本就支持的么- -。。。

rc-editor-mention@0.3.7 支持了跟 #3448 里提到的类似方法来做这个事。。

```jsx
<Mention getSuggestionContainer ={triggerNode => triggerNode.parentNode}> />
```
