### ISSUE TITLE
缺少表单报错boder颜色的修改配置

### ISSUE THREAD

**Issue by Engelce** [ant-design/ant-design#45982]
### What problem does this feature solve?

保持文本与边框的颜色统一

### What does the proposed API look like?

colorErrorBorder

![image](https://github.com/ant-design/ant-design/assets/87524394/9f87d7cc-23b4-408f-8615-3ebedcfa07e1)

**Comment by MadCcc** [comment]
Input 不属于 Form 的一部分，需要修改 Input 的 token
```
{
  "components": {
    "Form": {
      "algorithm": true,
      "colorError": "rgb(114, 46, 209)"
    },
    "Input": {
      "algorithm": true,
      "colorError": "rgb(114, 46, 209)"
    }
  }
}
```
