### ISSUE TITLE
Add `onClear` on datepicker

### ISSUE THREAD

**Issue by LienMaas** [ant-design/ant-design#45996]
### What problem does this feature solve?

The user shouldn't have to do a null check on onChange anymore

### What does the proposed API look like?

It could be an optional function -> if not provided fall back on the onChange function

**Comment by afc163** [comment]
You can use `onChange`:


```jsx
<DatePicker
  onChange={(date) => {
    if (date === null) {
      console.log("onClear");
    }
  }}
/>
```


https://codesandbox.io/s/ji-ben-antd-5-11-2-forked-f2s287?file=/demo.tsx
