### ISSUE TITLE
form 自定义异步验证 validator 之后无法使用 getFieldsError 获取到最新的错误信息。

### ISSUE THREAD

**Issue by ningshunqiang** [ant-design/ant-design#45995]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-shi-yong-antd-4-24-14-forked-6p5ykm?file=/demo.tsx)

### Steps to reproduce

1. 密码框输入值

### What is expected?

form.item 依赖项使用 getFieldsError 能够获取到最新的错误数据。

### What is actually happening?

2. 查看控制台，222 打印在 111 之前。

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.00.00 |
| System | 最新 |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
`dependencies` 改成 `shouldUpdate` 即可，`dependencies` 只监听依赖值变化，不关注校验信息哈~
