### ISSUE TITLE
File uploader resize image resolution to 200x200

### ISSUE THREAD

**Issue by 12rita** [ant-design/ant-design#45998]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-78mj62?file=/index.js)

### Steps to reproduce

Just try to use Upload component and get base64 of image. 

### What is expected?

Image is expected to be original size

### What is actually happening?

Image become the size of 200x200

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | 119.0.6045.160 |

**Comment by zombieJ** [comment]
It's by design. Pls use `previewFile` to custom what you need instead : )
