### ISSUE TITLE
Table 使用 sticky 标题 fixed 样式异常

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#45991]
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn#components-table-demo-sticky](https://ant-design.antgroup.com/components/table-cn#components-table-demo-sticky)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/7971419/b3785ff7-1857-4d1f-9b34-1caf8ac11bbb)

### What is expected?

不漏出

### What is actually happening?

漏出来了

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/28093
