### ISSUE TITLE
margin bottom of Form.Item is not working when help property is present

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#46001]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gv3scp?file=/index.js)

### Steps to reproduce

open sandbox, see margin is not working

### What is expected?

margin is applied after help element

### What is actually happening?

margin is not applied after help element, differences in margin bottom between 1 and 2, 2 and 3 items

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | 18 |
| System | mac os  |
| Browser | chrome |

**Comment by zombieJ** [comment]
It's by design. `margin` will remove when `help` provided to avoid layout shift. You can override `.ant-form-item-margin-offset` style if no need that:

https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-4xjxrg?file=%2Findex.css%3A5%2C1-5%2C29
