### ISSUE TITLE
Component page is lagging in IE11

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4600]
Windows 7 + IE11

尤其这两个页面，滚动页面和操作都能感受到非常明显的卡顿，目前不确定是网站还是组件的问题。

- https://ant.design/components/form-cn/
- https://ant.design/components/table-cn/

IE 下的性能问题得重视一下了。

**Comment by DerekHQ** [comment]
我上次提了，还提供了DEMO，主要是table列表显示页面 #4522 ， IE11卡到无法正常！
同样希望开发团队重视下该问题！！！

**Comment by afc163** [comment]
@DerekHQ 欢迎帮助一起排查。

**Comment by DerekHQ** [comment]
@afc163 感谢TEAM的积极响应！理解！希望能够大家一起把它做得更好！！

**Comment by yesmeck** [comment]
奇怪我那天看 demo 页面也很卡，今天看感觉不卡了。

**Comment by afc163** [comment]
看了下不卡了。
