### ISSUE TITLE
5.11.2版本升级导致，modal里的select下拉框看不到了，被盖在modal下。 这么明显的bug啊。。。

### ISSUE THREAD

**Issue by livingmore** [ant-design/ant-design#46005]
### Reproduction link

[https://dcode.amap.test](https://dcode.amap.test)

### Steps to reproduce

modal里的form表单，select下拉框内容看不到，被盖在modal下。 

### What is expected?

正常使用

### What is actually happening?

不能用

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | >18 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
Here is: https://codesandbox.io/p/sandbox/ji-ben-antd-5-11-2-forked-cjszg5?file=%2Fdemo.tsx%3A42%2C39-42%2C51

**Comment by Magic0323** [comment]
zIndex: 1000, // 加上就能解决
