### ISSUE TITLE
Dropdown提供的例子有问题

### ISSUE THREAD

**Issue by 153011490** [ant-design/ant-design#46003]
### Reproduction link

[https://ant.design/~demos/components-dropdown-demo-overlay-open](https://ant.design/~demos/components-dropdown-demo-overlay-open)

### Steps to reproduce

点击第一或者第二个选项，会隐藏menu

### What is expected?

点击第一或者第二个选项，不会隐藏menu

### What is actually happening?

点击第一或者第二个选项，会隐藏menu

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | 18.0.0 |
| System | windows |
| Browser | chrome 119.0.6045.160 |

**Comment by zombieJ** [comment]
thx。的确是有点问题
