### ISSUE TITLE
Deprecated `children` warning not specifying where the issue is coming from

### ISSUE THREAD

**Issue by janarvaezkng** [ant-design/ant-design#46019]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-warning-issue-68m437)

### Steps to reproduce

add a component with deprecated children to the page, and open the browser console

### What is expected?

the console error to specify which component it is (in the case, Collapse), and if possible, the file and line number where it's referenced

### What is actually happening?

It logs `Warning: `children` will be removed in next major version. Please use `items` instead.` without any specifics

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | react 18 |
| System | macos |
| Browser | chrome |

**Comment by MadCcc** [comment]
This warning should be from `rc-collapse`
