### ISSUE TITLE
table设置columns width属性不生效 版本5.10.1

### ISSUE THREAD

**Issue by BobTalk** [ant-design/ant-design#46010]
### Reproduction link

[https://github.com/BobTalk/ozfund.git ](https://github.com/BobTalk/ozfund.git )

### Steps to reproduce

直接打开页面 http://localhost:8080/ozfund/work-mange/ozc-contract/frezz-address 即可

### What is expected?

设置width生效

### What is actually happening?

设置width不生效

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18.2.0 |
| System | imac |
| Browser | google 版本119.0.6045.159 |

**Comment by zombieJ** [comment]
启动不起来：
<img width="348" alt="截屏2023-11-22 15 50 59" src="https://github.com/ant-design/ant-design/assets/5378891/91aff04a-965b-4ca5-ba05-11446341284c">

另外代码里没搜到有  `width` 的 `columns`，给个 codesandbox 看看~
