### ISSUE TITLE
`<Redio />` 组件支持 `required` 属性

### ISSUE THREAD

**Issue by nnmax** [ant-design/ant-design#46025]
### What problem does this feature solve?

`<Redio />` 组件支持 `required` 属性，这样就能支持浏览器原生的 form 表单验证功能。

### What does the proposed API look like?

此功能已经实现了，只是 `required` 的 TypeScript 类型未被导出

**Comment by afc163** [comment]
来个 PR

**Comment by nnmax** [comment]
> 来个 PR

done
