### ISSUE TITLE
Popover trigger: click 配合Radio.Group(Check) 只要外部包裹了元素， 就会导致点击文字选中选项的行为失效

### ISSUE THREAD

**Issue by Cyxwmm** [ant-design/ant-design#46020]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-32cqfl)

### Steps to reproduce

点击选项的文本内容不会选中

### What is expected?

期望能选中

### What is actually happening?

不能选中

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 18 |
| System | windows10 |
| Browser | 谷歌 |

![image](https://github.com/ant-design/ant-design/assets/22393346/3f5f6e67-5e96-4c55-bd1a-71f6f71f4657)

**Comment by zombieJ** [comment]
Check the code. `rc-trigger` refactor has fixed the issue in v5. Since v4 is using old version `rc-trigger`. We may not handle this in v4.
