### ISSUE TITLE
Table keeps showing empty table component when loading is true

### ISSUE THREAD

**Issue by alisher-aituarov** [ant-design/ant-design#46047]
### Reproduction link

[https://no-idea.have](https://no-idea.have)

### Steps to reproduce

just create table with loading attribute set to true and you will see the empty table component below the table

### What is expected?

empty table component is not shown when loading is true

### What is actually happening?

no idea

| Environment | Info |
| --- | --- |
| antd | 5.11.3 |
| React | react |
| System | dont know what that is  |
| Browser | any |

---
none

**Comment by clmz** [comment]
Reproduction? C'mon guys, just add empty array for data and set loading to true:

https://stackblitz.com/edit/react-z2eqvf?file=demo.tsx
