### ISSUE TITLE
编辑时表单读入数据的方式

### ISSUE THREAD

**Issue by slertness** [ant-design/ant-design#4604]
#### Environment(required)

- antd version: 2.6.1
- OS and its version: win10
- Browser and its version: chrome 55

#### What did you do? Please provide steps to re-produce your problem.

先说下我本来的做法：
点击编辑按钮，弹出编辑表单窗口，在componentWillReceiveProps里判断是否变为可见（nextProps.visible && !this.props.visible），通过setFieldsValue设置表单的值。
但是升级2.6.1版本后不行了，读不进数据。原因应该是新版本里没执行过getFieldDecorator无法setFieldsValue。
我想知道这是bug还是feature。莫非只能用mapPropsToFields读入数据？但是我不是很喜欢这种方式，每一次表单值变化都经过redux，感觉没有必要，产生大量无用的log，每个表单都要写actioncreater、reducer等也很麻烦。
我的目的是一次性读入数据，而不是使用redux保存表单编辑中的每个状态。所以我该怎么做？我暂时先停留在2.5的版本。

**Comment by afc163** [comment]
similar with #4575

**Comment by benjycui** [comment]
> 通过setFieldsValue设置表单的值

表单为何没有用 `getFieldDecorator` 注册？

> 我想知道这是bug还是feature。

因为在没有使用 `getFieldDecorator` 就用 `setFieldsValue` 会有潜在问题，所以加了 warning。

**Comment by slertness** [comment]
整个表单在一个组件里 弹窗没有显示的时候这个组件里的表单不会初始化 所以getFieldDecorator还没有执行到

**Comment by benjycui** [comment]
这种情况在 `componentDidMount` 里面 `setFieldsValue` 即可。

**Comment by slertness** [comment]
整个表单在一个组件里，我想在这个表单组件的父组件里给表单设置值，所以用不上`componentDidMount`。我目前能想到的方案是在父组件的`componentWillReceiveProps`里使用setTimeout来setFieldsValue。

**Comment by benjycui** [comment]
> 我想在这个表单组件的父组件里给表单设置值

`mapPropsToFields`

**Comment by benjycui** [comment]
Close 

有问题再开吧。

**Comment by luats** [comment]
@benjycui 2.10.0 官方Form动态示例基础上，在嵌套一个动态新增，{getFieldDecorator(`camaraKeys-${k}`, { initialValue: [`${k+10}`] })} 后，setFieldsValue 提示警告，而且未正常显示。去掉变量k就正常。这个是一个bug吗？
