### ISSUE TITLE
AutoComplete通过键盘回车选择时会触发children里的Input的onPressEnter

### ISSUE THREAD

**Issue by Sharang-heng** [ant-design/ant-design#46056]
### Reproduction link

[https://stackblitz.com/edit/react-sgmcdb?file=demo.tsx](https://stackblitz.com/edit/react-sgmcdb?file=demo.tsx)

### Steps to reproduce

输入搜索内容，然后回车选中

### What is expected?

利用AutoComplete模拟实现带搜索提示的聊天输入框（输入完成回车会发送消息），希望回车选中时是将选中的内容补充到Inout中，然后用户继续输入继续提供搜索提示，但由于会触发Input的onPressEnter，导致会将内容发送出去

### What is actually happening?

触发Input的onPressEnter，导致将内容发送出去

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 17.0.2 |
| System | window |
| Browser | Chrome |

**Comment by MadCcc** [comment]
这应该是预期行为，AutoComplete 在选择时是一直处于输入框聚焦状态的，自然也会触发 enter 事件。
如果希望不触发的话可以通过受控 `open` 来自定义行为

**Comment by zombieJ** [comment]
如果 AutoComplete 触发了 onSelect 就标记一下。Input 的 press 事件做个延迟，发现有过 onSelect 就不触发。另外，这个是业务逻辑问题，不是 antd 的 issue 哈~
