### ISSUE TITLE
国际化支持自定义 formatter

### ISSUE THREAD

**Issue by bowencool** [ant-design/ant-design#46057]
这是默认的校验信息，我想把 {label} 改成小写。

![image](https://github.com/ant-design/ant-design/assets/20217146/295571d4-e59a-4cb4-8294-8754642556be)

我知道可以在 rules 里面可以直接覆盖，但我仍然希望可以统一配置。

### What problem does this feature solve?

精准翻译。

### What does the proposed API look like?

``` ts
enUS.Form!.defaultValidateMessages.required = "Please enter ${label, lowercase}";
```

> 参考 https://www.i18next.com/translation-function/formatting#using-multiple-formatters

**Comment by zombieJ** [comment]
你需要的是 [messageVariables](https://ant-design.antgroup.com/components/form-cn#messagevariables):
https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-11-2-forked-5hrssw?file=%2Fdemo.tsx%3A31%2C30
