### ISSUE TITLE
Requesting new prop for `select` component.

### ISSUE THREAD

**Issue by amar9312** [ant-design/ant-design#46054]
### What problem does this feature solve?

Currently, If we use the prop `notFoundContent` on select component, it removes the icon along with changing the no found text. If we can create another prop, lets say `notFoundContentKeepIcon` which just changes the text but keeps the icon, I feel would offer more customization.

### What does the proposed API look like?

`notFoundContentKeepIcon`

**Comment by zombieJ** [comment]
It's nothing magic of the image. You can use [Empty](https://ant.design/components/empty) component to handle this.
