### ISSUE TITLE
Tree组件

### ISSUE THREAD

**Issue by yichenw7** [ant-design/ant-design#46052]
### What problem does this feature solve?

Tree组件节点拖拽功能

### What does the proposed API look like?

1.想要实现，可控制是在同级拖动
2.同级拖到包含子节点的同级节点，默认不会自动展开（子节点展开会干扰同级拖动效果，子节点展开会导致无法拖到到有子节点的同级节点位置处。）
https://codesandbox.io/p/sandbox/holy-wood-3dzhpn?file=%2Findex.js

**Comment by zombieJ** [comment]
用 `expandedKeys` 受控即可，拖拽时不允许改变 `expandedKeys` 就不会展开了。

**Comment by fribble186** [comment]
> 用 `expandedKeys` 受控即可，拖拽时不允许改变 `expandedKeys` 就不会展开了。

用 state isDraging 控制 onExpand 中是否改变 expandedKeys，onDragStart 时 set isDraging 为 true，onDragEnd 时 set isDragin 为 false，但是这么做会导致第一次拖不动，反复拖才可以拖动，可能是 setState 导致状态变动影响拖动事件

想实现拖动时不会自动展开节点，也是因为展开节点导致 expandedKeys state 变了，拖动的蓝色条就消失了

有没有其它什么好办法解决
