### ISSUE TITLE
Row 如何做到 md 自适应 5 列

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46055]
### What problem does this feature solve?

https://stackblitz.com/edit/react-zvcmtr?file=demo.tsx

小屏 4 列
![image](https://github.com/ant-design/ant-design/assets/7971419/53acc700-f2d3-4283-a3eb-526dce142867)
大屏 5 列
![image](https://github.com/ant-design/ant-design/assets/7971419/72ac2826-105b-4edd-b23d-c342f057d2a5)

### What does the proposed API look like?

`md={{ flex: '20%' }}` 设置没效果

**Comment by leixd1994** [comment]
虽然不知道怎么用row实现，但是用网格布局可以实现，请参考：
```javascript
export default function Edit() {
  const screens = useBreakpoint();
  console.log(screens);
  const arr = [];
  for (let i = 1; i <= 10; i++) {
    arr.push(i);
  }

  return (
      <div style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${screens.md === false ? 4 : 5}, 1fr)`,
        gridGap: '20px',
      }}>
        {arr.map((e) => (
            <div
                style={{
                  backgroundColor: "red",
                  color: "white",
                  height: "20px",
                  textAlign: "center",
                }}
            >
              {e}
            </div>
        ))}
      </div>
  )
}

```

![效果](https://github.com/ant-design/ant-design/assets/23328517/65a7c0e3-fc1f-4153-8963-d6393d6048e0)
