### ISSUE TITLE
Cascader.Panel 中 value变更不刷新，组件不刷新

### ISSUE THREAD

**Issue by WuJiY** [ant-design/ant-design#46069]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/bitter-glade-7znzx9?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpcas91h00g4356kxy2a7rh0%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpcas91h00g1356k6baoiogb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpcas91h00g3356kla61xikn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpcas91h00g2356kzngxm9t0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B59.45061415%252C40.54938585%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpcas91h00g1356k6baoiogb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpcaqokq0044356k6g3uuhsl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A45%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A45%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpcas91h00g1356k6baoiogb%2522%252C%2522activeTabId%2522%253A%2522clpcaqokq0044356k6g3uuhsl%2522%257D%252C%2522clpcas91h00g2356kzngxm9t0%2522%253A%257B%2522id%2522%253A%2522clpcas91h00g2356kzngxm9t0%2522%252C%2522activeTabId%2522%253A%2522clpcasyun00ia356kww2uuqpt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clpcasyun00ia356kww2uuqpt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clpcas91h00g3356kla61xikn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpcas91h00g3356kla61xikn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

两个Cascader  一个带搜索,另一个Cascader.Panel展示。如果 选择第二个Cascader.Panel之后能刷新上面的 Cascader里的值，但是选择上面第一个Cascader  的值下面的Cascader.Panel 却不更新

### What is expected?

两个Cascader 同步更新

### What is actually happening?

Cascader.Panel的value没有刷新

| Environment | Info |
| --- | --- |
| antd | 5.11.3 |
| React | 18 |
| System | windows/os |
| Browser | chrome |

**Comment by xiaozisong** [comment]
[https://github.com/react-component/cascader/pull/450](url)

**Comment by xiaozisong** [comment]
#https://github.com/react-component/cascader/pull/450

**Comment by xiaozisong** [comment]
xiaozisong/https://github.com/xiaozisong/cascader/#450

**Comment by xiaozisong** [comment]
fix xiaozisong/https://github.com/react-component/cascader#450

**Comment by xiaozisong** [comment]
[#450](xiaozisong:fix-cascader)
