### ISSUE TITLE
TreeSelect 切换搜索的时候偶是需要通过接口返回的，返回内容中会有isLeaf=false，为什么点击不触发onload

### ISSUE THREAD

**Issue by Julycc41** [ant-design/ant-design#46064]
### What problem does this feature solve?

懒记载搜索 

### What does the proposed API look like?

搜索返回后 点击子集搜索可以触发

![9691700806860_ pic](https://github.com/ant-design/ant-design/assets/80231740/d704f9ef-4f5b-46f7-98aa-f227ed31ac43)
![9701700806902_ pic](https://github.com/ant-design/ant-design/assets/80231740/3c029fa4-da63-4037-98a5-94e97dce0935)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32817#issuecomment-966080454
