### ISSUE TITLE
tree  树形控件  在  titleRender 自定义title 后想实现 超出省略 

### ISSUE THREAD

**Issue by shunshunyue** [ant-design/ant-design#46063]
### Steps to reproduce

tree  树形控件  在  titleRender 自定义title 后想实现 超出省略 
故 给
 .ant-tree-node-content-wrapper   加上 flex1  和 overflow: hidden;
省略正常 
但 拖拽指示器 不见了 应该是  overflow: hidden;  给截掉了

### What is expected?

修复

### What is actually happening?

修复

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 16.13.1 |
| System | win |
| Browser | 谷歌 |

**Comment by roddc** [comment]
.title-ellipsis { 
& .ant-tree-node-content-wrapper {
    container-type: inline-size;
  }
  & .ant-tree-title {
    width: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    display: inline-block;
    vertical-align: bottom;
  }
}
试试这个,拖拽的指示条不会被截断
