### ISSUE TITLE
Using nested tables creates duplicate rows

### ISSUE THREAD

**Issue by PierrickI3** [ant-design/ant-design#46072]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-table-issue-fz9jzd?file=%2Fsrc%2FApp.js%3A3019%2C48)

### Steps to reproduce

Click on the first "ALLINA HEALTH" item in the table. It will show a child called "Allina Health" which is expected.
However, the same child also appears as a new entry in the "Account Name" field. 
If you close the "ALLINA HEALTH" item, this duplicate entry will disappear

### What is expected?

New entry should not appear in the main list

### What is actually happening?

A duplicate child entry appears in the parent list

| Environment | Info |
| --- | --- |
| antd | 5.9.4 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome |

---
I checked the keys are they are all unique. Not sure what to look for...

**Comment by afc163** [comment]
<img width="454" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/1b81ff0d-779a-4f48-83d6-451b5126c7a3">

**Comment by afc163** [comment]
What you need is `childrenColumnName: 'not-existed'` probably.

https://codesandbox.io/p/sandbox/antd-table-issue-forked-ns9xj6?file=%2Fsrc%2FApp.js%3A3074%2C1-3075%2C1

https://ant.design/components/table#components-table-demo-tree-data

**Comment by PierrickI3** [comment]
Thank you!
