### ISSUE TITLE
RangePicker does not update when start/end date changed from outside

### ISSUE THREAD

**Issue by webdesign2be** [ant-design/ant-design#46075]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/still-resonance-4dt77f?file=%2Fsrc%2FRange.tsx%3A65%2C26)

### Steps to reproduce

Setup a component that accepts start/end date with the RangePicker.
use the component in another component that handles the input for start / end date and pass it down to the Component with the Range Picker.

### What is expected?

Whenever the start/end date changes from outside, the Picker should update.

### What is actually happening?

RangePicker does not update on changes of start/end date.
No matter if you use "initialValue" of "Form.Item" (wrapped) or "value" on the "RangePicker".

| Environment | Info |
| --- | --- |
| antd | 5.11.3 |
| React | 18.2.0 |
| System | MacOS 14.2 |
| Browser | Chrome 119.0.6045.159 (arm64) |

**Comment by zombieJ** [comment]
Pls ref official document for more info. `initialValue` only works on component first mount, which means dynamic update will do nothing about this.
Form.Item with `name` props will handle `value` prop. If you want to use control mode instead of Form handle, just no to set `name`

**Comment by radrianhp** [comment]
How can I get the fix of this issue. if anyone know please do reply.
in case, I use control using Form, how to change dynamic value inside Form.Item ?

**Comment by radrianhp** [comment]
> Pls ref official document for more info. `initialValue` only works on component first mount, which means dynamic update will do nothing about this. Form.Item with `name` props will handle `value` prop. If you want to use control mode instead of Form handle, just no to set `name`

How can I get the fix of this issue. if anyone know please do reply.
in case, I use control using Form, how to change dynamic value inside Form.Item ?

**Comment by MuhammedOzby** [comment]
This solution is working: https://ant.design/components/form#formuseform

Set only dayjs:
```javascript
const [form] = Form.useForm();
 useEffect(() => {
 	form.setFieldsValue({ formItemName: dayjs().add(2, 'year') });
 }, [a]); 
```
