### ISSUE TITLE
Tour spotlight is clickable.

### ISSUE THREAD

**Issue by syed-create** [ant-design/ant-design#46073]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-pgq47n?file=%2Findex.js%3A14%2C74)

### Steps to reproduce

- Start the tour by clicking on the **Start Tout Button**
- Click on the **heading** to change the color. 

### What is expected?

We should have a prop to disable click functionality on the spotlight area of tour. 

### What is actually happening?

Currently, we can click on the spotlight area, which may disrupt some functionalities of the desired experience, and we do not have any API prop to disable it or any class wrapper to disable it using CSS.

| Environment | Info |
| --- | --- |
| antd | 5.11.3 |
| React | ^18 |
| System | Ubuntu 22.04.3 LTS |
| Browser | Google Chrome Version 119.0.6045.105  |

**Comment by MadCcc** [comment]
It is intended that spotlight area is made for users to interact. But it make sense that sometimes we only want to show users the function.
