### ISSUE TITLE
When did table have built-in drag-and-drop column width control?

### ISSUE THREAD

**Issue by HappyAxin** [ant-design/ant-design#46098]
### What problem does this feature solve?

table have built-in drag-and-drop column width control

### What does the proposed API look like?

`<Table columnWidthControl={boolean}></Table>`

**Comment by MadCcc** [comment]
Not planned. Still could use with 3rd party drag lib.

**Comment by HappyAxin** [comment]
> Not planned. Still could use with 3rd party drag lib.

Why? It's a very useful feature, and many systems need it.

**Comment by MadCcc** [comment]
Going to closing this issue.
We will not introduce draggable or other 3rd lib into antd in order to minimize bundlesize, since they work well with current antd.
