### ISSUE TITLE
Image 组件是否可以支持 inline mode 

### ISSUE THREAD

**Issue by BBBigCat** [ant-design/ant-design#46106]
### What problem does this feature solve?

可以在指定的视窗中预览图片，如：

![CleanShot 2023-11-27 at 19 42 39](https://github.com/ant-design/ant-design/assets/31910599/1e120e0b-b790-41d5-9513-b1e3fa10eeb7)

### What does the proposed API look like?

```javascript
const container = useRef()
...
<div ref={container} >
    <Image src='xx' container={container.current} />
</div>
```

**Comment by MadCcc** [comment]
暂时没有计划。图片预览需要比较大的空间，设计上也是配合全屏使用的。

**Comment by crazyair** [comment]
如果要支持，Image 需要重新设计

**Comment by flycj** [comment]
是否可以支持 inline-mode 呢？ 因为弹窗对用户来说会阻碍用户看其他内容，对于需要对比图片细节的场景可能体验就不太好了
