### ISSUE TITLE
DatePicker.RangePicker 面板跳转问题

### ISSUE THREAD

**Issue by Eva-HYL** [ant-design/ant-design#46102]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn#components-date-picker-demo-size](https://ant-design.antgroup.com/components/date-picker-cn#components-date-picker-demo-size)

### Steps to reproduce

当有值的时候重新选择开始时间且大于原有结束时间 或 先选择结束时间且时间小于原开始时间  时，未选择的开始时间（或者结束时间）会置空，选择面板会跳转到上次选择的时间且不可选  

https://github.com/ant-design/ant-design/assets/20679225/cd6dd1f5-3661-4568-929f-e44e2a095364

### What is expected?

当结束时间为空的时候，面板不跳转至上次选择时间  且 定位于可选区域

### What is actually happening?

结束时间选择面板会跳转到上次选择的时间并且不可选

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | 18 |
| System | mac 14 |
| Browser | chrome |

**Comment by xinjiahuan** [comment]
这个问题有解吗？

**Comment by huangguangjie** [comment]
同样遇到这个问题，有折中办法吗？

**Comment by ewalti** [comment]
I'm experiencing this as well. It seems like a regression:

https://github.com/ant-design/ant-design/issues/24309
https://github.com/ant-design/ant-design/issues/21084
https://github.com/react-component/picker/pull/21

it might be the underlying library they are using for the picker.

**Comment by Eva-HYL** [comment]
更新antd 5.14.2   这个问题已经解决了
