### ISSUE TITLE
Dropdown on Form.Item in React.StrickMode gives warning "findDOMNode is deprecated in StrictMode"

### ISSUE THREAD

**Issue by konstantinsp** [ant-design/ant-design#46113]
### Reproduction link

[https://stackblitz.com/edit/react-mwq2xk?file=index.tsx](https://stackblitz.com/edit/react-mwq2xk?file=index.tsx)

### Steps to reproduce

open app and see the error in console

use  <React.StrictMode> for the app 
and add dropdown to form item
```
      <Dropdown menu={{ items }} trigger={['contextMenu']}>
              <Form.Item......>
                <Select..../>
              </Form.Item>
      </Dropdown>
```

### What is expected?

no error

### What is actually happening?

error 

![image](https://github.com/ant-design/ant-design/assets/3995264/f0fc8a56-aa59-4afe-9b28-5f47ac35821f)

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | 18.2 |
| System | windows |
| Browser | chrome 119 |

**Comment by bihongbin3027** [comment]
我也遇到相同的问题，有这个警告

**Comment by WebGhan** [comment]
我也遇到了，版本：5.15.1

<img width="783" alt="image" src="https://github.com/ant-design/ant-design/assets/34372145/45d14356-c253-4cea-89a9-763544db7c98">

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/48709
