### ISSUE TITLE
Cascader能否默认展开下拉菜单中已选中的子项？

### ISSUE THREAD

**Issue by wdyea-ya** [ant-design/ant-design#46117]
### What problem does this feature solve?

有初始值时，点击下拉菜单时默认展开对应的子级菜单
https://codesandbox.io/p/sandbox/zealous-mendeleev-wwyzf4?file=%2Fsrc%2FApp.js%3A49%2C16
上面例子中，子级菜单没有展开，需要先点击对应的父级

### What does the proposed API look like?

希望有个api能设置初始展开的菜单

**Comment by MadCcc** [comment]
默认会展开选中的子项，你的 demo 中没有是因为 zhejiang 打成了 zhengjiang

**Comment by wdyea-ya** [comment]
多选的时候不会默认展开

**Comment by wdyea-ya** [comment]
多选的时候不会默认展开
