### ISSUE TITLE
级联选择器 Cascader 多选模式是否可以仅支持子项多选？

### ISSUE THREAD

**Issue by wdyea-ya** [ant-design/ant-design#46116]
### What problem does this feature solve?

在一些需求场景下，Cascader 的二级选项是互斥的，只能选择一个，此时父级的checkbox就不能进行选择了，仅起到展示作用，希望能有一个api来支持仅子级多选
https://codesandbox.io/p/sandbox/zealous-mendeleev-wwyzf4?file=%2Fsrc%2FApp.js%3A17%2C7
在这个例子里面，通过css将父级的checkbox隐藏了

### What does the proposed API look like?

option 中可以有一个api来支持控制多选时是否隐藏checkbox

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by MadCcc** [comment]
建议自行控制一下 option 的 disabled 属性

**Comment by wdyea-ya** [comment]
选择父级的checkbox时，子项会全选，而场景要求的是同一父级下子项之间是互斥的，只能选择一个，option 的 disabled 属性不能满足要求

**Comment by zombieJ** [comment]
<img width="642" alt="截屏2023-11-29 20 32 06" src="https://github.com/ant-design/ant-design/assets/5378891/53864ef2-66a0-4b3f-9c06-e030bd723bd0">


https://ant-design.antgroup.com/components/cascader-cn#cascader-demo-multiple

**Comment by annanShao** [comment]
他的意思应该是仅支持叶子节点多选，父节点能不能支持不展示 checkbox，某些场景应该也是有这个诉求的
