### ISSUE TITLE
Select组件placement属性弹出的位置无效

### ISSUE THREAD

**Issue by guojin-long** [ant-design/ant-design#46121]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/dan-chu-wei-zhi-antd-5-11-2-2m7hrp)

### Steps to reproduce

分别点击topRight，bottomLeft，bottomRight按钮

### What is expected?

选择列表在正确的位置（topRight，bottomLeft，bottomRight）弹出

### What is actually happening?

选择列表都在左下角弹出

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | ^18.0.0 |
| System | macOs/10.15.6 |
| Browser | chrome/119.0.6045.159（正式版本） (x86_64) |

**Comment by afc163** [comment]
浏览器视窗空间不足，Select 做了自适应。空间够就行：https://codesandbox.io/p/sandbox/dan-chu-wei-zhi-antd-5-11-2-forked-6zq9n4?file=%2Fdemo.tsx%3A13%2C1
