### ISSUE TITLE
时间选择器增加:星期

### ISSUE THREAD

**Issue by 97702573** [ant-design/ant-design#46122]
### What problem does this feature solve?

时间选择器增加星期几，用户可以选择周一到周日某一天

### What does the proposed API look like?

picker="dayOfTheWeek"

**Comment by Wxh16144** [comment]
这个功能？
<img width="1153" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/f03a6e35-ce07-4752-9f4f-27e26c186488">

**Comment by sunnyxujian** [comment]
这种功能自定义render应该也可以实现吧，panelRender

**Comment by MadCcc** [comment]
星期不是一个特定的时间，视情况可以用 Select 代替

**Comment by afc163** [comment]
建议使用 Select 即可。
