### ISSUE TITLE
Frequently clicking on confirm modal button would open multiple modals

### ISSUE THREAD

**Issue by c3Vu** [ant-design/ant-design#46129]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-48k2jl)

### Steps to reproduce

Clicking on the button multiple times

### What is expected?

Exactly one modal is open, which is the default behavior in v4.

### What is actually happening?

Multiple modals are open, the click operations are not blocked

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18 |
| System | mac big sur |
| Browser | chrome |

**Comment by MadCcc** [comment]
因为 v5 的 mask 在出现动画时 `pointer-events: none` 了，导致能够再次点到 Button。

**Comment by c3Vu** [comment]
> 因为 v5 的 mask 在出现动画时 `pointer-events: none` 了，导致能够再次点到 Button。

所以这个是设计如此，还是bug呢？这样会需要用户自己维护是否被点击过的状态

**Comment by afc163** [comment]
bug
