### ISSUE TITLE
Upload - add support for maxFileSize

### ISSUE THREAD

**Issue by aleksander-lurie-codete** [ant-design/ant-design#46139]
### What problem does this feature solve?

Would be nice to have additional property what allow to set up maximum file size for uploaded file.

### What does the proposed API look like?

| Property    | Description                                                                            | Type   | Default |
|-------------|----------------------------------------------------------------------------------------|--------|---------|
| maxFileSize | Maximum file size for uploaded file (in bytes). When set to 0 there is no limit at all. | number | 0       |

**Comment by afc163** [comment]
You can try `beforeUpload`, see https://ant.design/components/upload#components-upload-demo-avatar

**Comment by aleksander-lurie-codete** [comment]
that way i can do manually almost everything ;)
would be nice to have it built in, same way as `maxCount`

**Comment by aleksander-lurie-codete** [comment]
@afc163 and actually i did it that way, but there is no possibility to throw custom error, i can just ignore file and thats it.
ofc everything can be done by customRequest, but in this case whats the reason to use this component if most of the things we have to do manually.

**Comment by Fashad-Ahmed** [comment]
I have done in this way in Ant design upload component's onChange method 

```
// for 3 MB file
    if (file.size > 3 * 1024 * 1024) {
              message.error('File size exceeds 3 MB');
              return false;
            }
```
