### ISSUE TITLE
tabs组件使用dnd-kit进行拖动时卡顿

### ISSUE THREAD

**Issue by kkfive** [ant-design/ant-design#46131]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/draggable-tabs-antd-5-2-2-forked-8h2cqz?file=%2Fdemo.tsx)

### Steps to reproduce

当使用默认`Tabs`组件属性`type`不为`line`时拖动非常的不丝滑。

### What is expected?

三种type都丝滑

### What is actually happening?

只有`type`为`line`时丝滑

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18 |
| System | Windows 10  |
| Browser | chrome 119.0.6045.160 |

![动画](https://github.com/ant-design/ant-design/assets/82026204/d77162fb-772c-43a3-829d-1e518e41505f)

![动画1](https://github.com/ant-design/ant-design/assets/82026204/88a9ef8d-ef6f-4998-a4ec-8950aafccebc)

**Comment by Mr-WangYH** [comment]
请问一下如何解决的？

**Comment by rainmax** [comment]
把.ant-tabs-tab的transition设置为none就行，默认是带有动画效果的
