### ISSUE TITLE
how to create a form with floating labels in antd 

### ISSUE THREAD

**Issue by iiitmahesh** [ant-design/ant-design#4613]
how to create a form with floating labels in antd

**Comment by afc163** [comment]
define `floating labels`

**Comment by iiitmahesh** [comment]
Can you please provide an example form item here.

**Comment by afc163** [comment]
https://ant.design/components/form/

It this what you want?

**Comment by iiitmahesh** [comment]
No, I need floting labels for inputs Like this http://codepen.io/pen/ (I am just asking is antd having such kind of labels)

**Comment by afc163** [comment]
I can't get your point, which is `floating labels for inputs` in codepen.

<img width="1435" alt="image" src="https://cloud.githubusercontent.com/assets/507615/22019686/85758890-dcef-11e6-9675-7bbe23cbfa13.png">

**Comment by pablomolnar** [comment]
Hi @afc163 , I suspect what the OP is referring is something like this:
http://www.material-ui.com/#/components/text-field (see floating label text examples).

I didn't find any ant-design example for that use case. I think it would be great addition.

**Comment by benjycui** [comment]
Floating label text is cool, but it hard to work with other form controls, e.g. Select, InputNumber, and customized component.
