### ISSUE TITLE
Form的 recursive 存在bug

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#46136]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fei-zu-sai-xiao-yan-antd-5-11-2-forked-2sxms9?file=%2Fdemo.tsx%3A13%2C10)

### Steps to reproduce

点击submit

### What is expected?

期待只有姓名被校验

### What is actually happening?

input2也被进行了校验

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by MadCcc** [comment]
https://codesandbox.io/p/sandbox/fei-zu-sai-xiao-yan-antd-5-11-2-forked-97mndr?file=%2Fdemo.tsx

validateFields 的第一个参数是数组，需要包一层括号。
