### ISSUE TITLE
upload 上传组件默认列表怎么修改他的图标呢？

### ISSUE THREAD

**Issue by cangsnage** [ant-design/ant-design#46145]
### What problem does this feature solve?

可以自定义默认列表上传的文件是图片视频还是文件类型的

### What does the proposed API look like?

可以自定义设置图标

![image](https://github.com/ant-design/ant-design/assets/25116493/45737806-8137-43fb-ab6b-6f2cd19b064b)
比如我上传的是文件我想把图片的图标改成文件图标没又这个api

**Comment by zombieJ** [comment]
`previewFile`

**Comment by cangsnage** [comment]
> `previewFile`

不是的，我这个不是上传后更改列表。
DefaultFileList 这个api

**Comment by cangsnage** [comment]
> `previewFile`

不是的，我这个不是上传后更改列表。
DefaultFileList 这个api

**Comment by Wxh16144** [comment]
> `previewFile`

貌似得用 `iconRender` 这个 props 去实现🤔

**Comment by Wxh16144** [comment]
![image](https://github.com/ant-design/ant-design/assets/32004925/0b9ffdf5-6d6b-4c82-9df8-5a721c1e74d7)

**Comment by Wxh16144** [comment]
<img width="963" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/0bb08d9e-a825-43fb-b557-7d46ca352f7b">

**Comment by cangsnage** [comment]
> <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/32004925/286453767-0bb08d9e-a825-43fb-b557-7d46ca352f7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjUwNDEsIm5iZiI6MTcwMTIyNDc0MSwicGF0aCI6Ii8zMjAwNDkyNS8yODY0NTM3NjctMGJiMDhkOWUtYTgyNS00M2ZiLWI1NTctN2Q0NmNhMzUyZjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAyMjU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjN2RjZDIxYjNmZmUxMWFkNDU2OTJlN2JiNjE4ZTUyOGE0OTE2MjhkYzcwNWU3NDY2YjU1YWVkMzk4YmViMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4gLjIIMMPz4WEVOxjdfdgtxFymNaTee6UqE2j2zya5o">

不太行哦，他这个是获取列表和列表的展示样式的api
