### ISSUE TITLE
线性进度条<Progress>组件  能否和圆形进度条一样支持锥形渐变？

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#46149]
### What problem does this feature solve?

线性进度条不能设置锥心渐变

### What does the proposed API look like?

增加conic属性

**Comment by MadCcc** [comment]
线性进度条为啥要锥形渐变？期望是什么样的？

**Comment by MadCcc** [comment]
那这和锥形渐变无关，还是线性渐变，需要优化进度条视觉效果

**Comment by afc163** [comment]
@chengshaohui 牛逼，一图胜千言
