### ISSUE TITLE
Nested Forms with differing layouts result in FormItemControl (which wraps Input) with a height of 1px

### ISSUE THREAD

**Issue by DrewHoo** [ant-design/ant-design#46141]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sxxkxy?file=/index.js)

### Steps to reproduce

Render a FormItem with a label inside a Form with layout: horizontal, inside a Form with layout: vertical. The div with ".ant-form-item-control" class gets a computed height of 1 pixel, resulting in overlap with subsequent FormItems, cutting off their label text

### What is expected?

label text doesn't get cut off when nesting forms of different layouts

### What is actually happening?

label text is cut off

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18 |
| System | macOs Sonoma 14.1  |
| Browser | Firefox 120.0 |

**Comment by MadCcc** [comment]
Could you provide a real case? We can simply use responsive layout to implement this.

**Comment by DrewHoo** [comment]
> Could you provide a real case? We can simply use responsive layout to implement this.

Issue instructions are very specific about wanting an **M**RE 😂 

I ran into this while implementing antd renderers for a json-schema forms library. When forms can be built programmatically and nested, the behavior of nested antd Form components with differing values for `layout` is undefined AFAICT; the root form with `layout:vertical` appears to supersede the nested form with `layout:horizontal` in terms of where the label gets put, but the `layout:horizontal` form's styles get applied so that the spacing is screwed up.

Any solution that doesn't give users the worst of both worlds (both the FormItem's label location being wrong and the spacing between FormItems being wrong) would be a big improvement; this was a very difficult styling bug to find & isolate.

**Comment by DrewHoo** [comment]
Closing this now that I see mixed layouts are supported in 5.18 via `Form.Item`'s `layout` prop! This bug might still be reproducible, but the actual use case for using `Form`s with different `layout` properties is virtually non-existent now.
