### ISSUE TITLE
使用ConfigProvider报错

### ISSUE THREAD

**Issue by SevenNorth** [ant-design/ant-design#46151]
### Reproduction link

[http://sevennorth.lovinghlx.cn/imgbed/20231129112136.png](http://sevennorth.lovinghlx.cn/imgbed/20231129112136.png)

### Steps to reproduce

![20231129112136](http://sevennorth.lovinghlx.cn/imgbed/20231129112136.png)

### What is expected?

import  MotionProvider  from 'rc-motion';

### What is actually happening?

MotionProvider导入方式错误

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2.0 |
| System | window |
| Browser | Chrome@119.0.6045.160 |

---
使用ConfigProvider时，发现报错控制台输出warning， 进而页面无法展示

**Comment by SevenNorth** [comment]
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-ts2rrx?file=%2Findex.js%3A24%2C3

**Comment by MadCcc** [comment]
@SevenNorth 复现中并没有报错？

**Comment by MadCcc** [comment]
截图无法帮助我们定位错误，需要提供可运行的环境。

**Comment by SevenNorth** [comment]
我先关闭， 构建出可复现的在线环境再reopen

**Comment by SevenNorth** [comment]
thx
