### ISSUE TITLE
upload组件无法覆盖样式

### ISSUE THREAD

**Issue by vual** [ant-design/ant-design#46153]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce
upload组件上加了className，也定义了样式，但是没有生效
![image](https://github.com/ant-design/ant-design/assets/25891219/1d3f706a-6eeb-4690-ab20-6cf7db72b855)
![image](https://github.com/ant-design/ant-design/assets/25891219/f1faaef3-bf90-448e-b6ca-fffb5d28eddd)

### What is expected?

能覆盖样式

### What is actually happening?

没有覆盖

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 5.11 |
| System | win10 |
| Browser | edge |

**Comment by Wxh16144** [comment]
css module？

**Comment by vual** [comment]
> css module？ 可以先自己检查一下是不是这个问题 https://github.com/css-modules/css-modules#usage-with-preprocessors

是css module，看了下，不太明白，咋解决？
