### ISSUE TITLE
Form.Item 使用Switch控件，添加tooltip属性增加提示图标，点击此图标也会切换Switch状态，感觉不合理

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#46154]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/zhu-ce-xin-yong-hu-antd-5-11-5-forked-cd3d6j?file=%2Fdemo.js%3A29%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpjd8eqt0007356hhkoz7xxe%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpjd8eqt0003356hn5o4btir%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpjd8eqt0004356hbd89grbm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpjd8eqt0006356hbfn46i2p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpjd8eqt0003356hn5o4btir%2522%253A%257B%2522id%2522%253A%2522clpjd8eqt0003356hn5o4btir%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpjdeb7q0003356i82itk1iu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A29%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A29%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpjdeb7q0003356i82itk1iu%2522%257D%252C%2522clpjd8eqt0006356hbfn46i2p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpjd8eqt0005356h3gqoffpm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpjd8eqt0006356hbfn46i2p%2522%252C%2522activeTabId%2522%253A%2522clpjd8eqt0005356h3gqoffpm%2522%257D%252C%2522clpjd8eqt0004356hbd89grbm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpjd8eqt0004356hbd89grbm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Form.Item 使用Switch控件 添加name、tooltip属性
2. tooltip使用小图标
3. 点击小图标会切换switch状态

### What is expected?

点击提示小图标不切换switch状态

### What is actually happening?

点击提示小图标切换switch状态

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | "react": "^18.2.0" |
| System | win10 |
| Browser | chrome119 |

---
最好能提供属性   控制Form组件下label和控件的关联关系

**Comment by zombieJ** [comment]
Tooltip 的图标是在 `label` 中，导致点击会被传导。的确看起来不太合理。
