### ISSUE TITLE
size 改为 sm, 但是 fontSize 并没使用 fontSizeSM

### ISSUE THREAD

**Issue by vaynevayne** [ant-design/ant-design#46150]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/5fe14019593a7dbf9085eab647309b3ffbb56aee/components/select/style/single.tsx#L17C32-L17C32](https://github.com/ant-design/ant-design/blob/5fe14019593a7dbf9085eab647309b3ffbb56aee/components/select/style/single.tsx#L17C32-L17C32)

### Steps to reproduce

如题

### What is expected?

size = 'sm' 时, 应该使用 token.fontSizeSM, 

### What is actually happening?

font-size 并没结合 size 来判断,而是写死的 token.fontSize

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | chrome |

---
ipad 和手机上,我需要小号的字体,

**Comment by vaynevayne** [comment]
这里的字体 和 height, line-height 不应该重置啊

https://github.com/ant-design/ant-design/blob/5fe14019593a7dbf9085eab647309b3ffbb56aee/components/select/style/single.tsx#L22


<img width="489" alt="image" src="https://github.com/ant-design/ant-design/assets/124666577/6e5f2a56-b1ac-4f59-8d3b-f47f4f2845b3">

**Comment by MadCcc** [comment]
`size="sm"` 和使用 `fontSizeSM` 并不直接关联，小尺寸组件为了视觉效果也会采用默认字号

**Comment by vaynevayne** [comment]
我不认同, 当 size=sm 时,我需要使用 sm 的字体,应该怎么做?

**Comment by MadCcc** [comment]
如果需要调整字体直接调整 `fontSize` 即可

**Comment by vaynevayne** [comment]
ok, 多谢
