### ISSUE TITLE
RangePicker组件，picker="month" || picker="year"  受控模式下  onOpenChange事件有问题

### ISSUE THREAD

**Issue by zx-zx22** [ant-design/ant-design#46152]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-344tqq?file=%2Findex.js%3A26%2C3)

### Steps to reproduce

import React from "react";
import { createRoot } from "react-dom/client";
import { Button, DatePicker, Space, version } from "antd";
import "antd/dist/reset.css";
import "./index.css";

const App = () => {
  const [open, setOpen] = React.useState(false);

  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <Space>
        <DatePicker.RangePicker
          picker="month"
          open={open}
          onOpenChange={(val) => {
            console.log(val);
            setOpen(val);
          }}
        />
        <Button type="primary">Primary Button</Button>
      </Space>
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);

### What is expected?

期望跟v4版本一样，月份或者年份选择完成    触发 onOpenChange事件，以关闭日期选择框

### What is actually happening?

月份或者年份选择完成   并不触发 onOpenChange事件，导致日期选择框无法关闭

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome 最新版 |

**Comment by zx-zx22** [comment]
什么意思？  现在这个问题不是bug吗？

**Comment by zx-zx22** [comment]
好的

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
