### ISSUE TITLE
Unify name of ReactNode type in document

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#4616]
Currently we have many names for ReactNode type props in document, such as:

* `React.ReactNode`
* `React.Element`
* `String/element`
* `React.Element or String`
* `String or Element`
* `string or React.ReactNode `
* ...

According to the React's declaration file:

```typescript
type ReactText = string | number;
type ReactChild = ReactElement<any> | ReactText;

// Should be Array<ReactNode> but type aliases cannot be recursive
type ReactFragment = {} | Array<ReactChild | any[] | boolean>;
type ReactNode = ReactChild | ReactFragment | boolean | null | undefined;
```

I propose to unify the name of this kind type to `string|ReactNode`.

**Comment by benjycui** [comment]
It will be better to follow TypeScript's definition.

**Comment by afc163** [comment]
ReactNode includes ReactElement, null, undefined, is much more than ReactElement.

**Comment by yesmeck** [comment]
Updated, though ReactNode includes `string`,  `string/ReactNode` is easier to understand for non-typescript users.

**Comment by yesmeck** [comment]
Create a wiki page https://github.com/ant-design/ant-design/wiki/Document-type-name-conventions

**Comment by benjycui** [comment]
Update side bar please.

![image](https://cloud.githubusercontent.com/assets/3580607/22011592/e0f2482c-dcca-11e6-8fb5-b84ea55cc8c0.png)

**Comment by afc163** [comment]
It is better to replace them by using a script.

**Comment by benjycui** [comment]
> It is better to replace them by using a script.

For example?

**Comment by afc163** [comment]
Replace text in document automaticly.
