### ISSUE TITLE
Modal的 静态确认对话框 连续快速的点击会打开两个弹窗

### ISSUE THREAD

**Issue by jia-sss** [ant-design/ant-design#46166]
### Reproduction link

[https://ant-design.antgroup.com/components/modal-cn#modal-demo-confirm](https://ant-design.antgroup.com/components/modal-cn#modal-demo-confirm)

### Steps to reproduce

官方示例快速点击两下会出现两个弹窗

### What is expected?

只允许点击一次

### What is actually happening?

会出现两次

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2.0 |
| System | mac os |
| Browser | chrome 118.0.5993.70 |

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/45954#issuecomment-1818125644

**Comment by afc163** [comment]
看上去可以修一下，跟踪 https://github.com/ant-design/ant-design/issues/46129
