### ISSUE TITLE
想问下tree组件点击父级想把子级全部收缩起来应该做呢？

### ISSUE THREAD

**Issue by cangsnage** [ant-design/ant-design#46162]
### What problem does this feature solve?

可以自己不自定义keys

### What does the proposed API look like?

希望自己不自定义keys

我用ExpandedKeys这个来进行控制。我使用onExpand这个方法进行获取keys和来控制是否展开收起，但是不知道他的父级怎么跟子级进行关联的key

**Comment by 6813abc** [comment]
` <Tree
                expandedKeys={expandedKeys}
                onExpand={(expandedKeys) => {
                  setExpandedKeys(expandedKeys);
                }}
                onSelect={(selectedKeys, info) => {
                  console.log(selectedKeys, info);
                  const key = info.node.key;
                  const index = expandedKeys.indexOf(key);
                  if (index > -1) {
                    // 如果节点已展开，则移除
                    setExpandedKeys(expandedKeys.filter((k) => k !== key));
                  } else {
                    // 如果节点未展开，则添加
                    setExpandedKeys([...expandedKeys, key]);
                  }
                }}
              />`

**Comment by 6813abc** [comment]
<Tree
                expandedKeys={expandedKeys}
                onExpand={(expandedKeys) => {
                  setExpandedKeys(expandedKeys);
                }}
                onSelect={(selectedKeys, info) => {
                  console.log(selectedKeys, info);
                  const key = info.node.key;
                  const index = expandedKeys.indexOf(key);
                  if (index > -1) {
                    // 如果节点已展开，则移除
                    setExpandedKeys(expandedKeys.filter((k) => k !== key));
                  } else {
                    // 如果节点未展开，则添加
                    setExpandedKeys([...expandedKeys, key]);
                  }
                }}
              />

**Comment by zombieJ** [comment]
遍历一下 父节点下面的子节点，然后从 `expandedKeys` 里移除。你在 `onExpanded` 事件里是可以拿到当前节点信息的。业务逻辑需要自行实现哈~
