### ISSUE TITLE
Upload, not clickable download button if component disabled

### ISSUE THREAD

**Issue by EvgenBabenko** [ant-design/ant-design#46171]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/pictures-wall-antd-4-24-15-forked-2pq8rw?file=%2Fdemo.tsx)

### Steps to reproduce

add disabled props

### What is expected?

download button is clickable 

### What is actually happening?

download button is not clickable

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 16.12.0 |
| System | window10 |
| Browser | Google Chrome 119.0.6045.160 (Official Build) (64-bit) |

---
when component is disabled, download button should be clickable, cuz it is read-only operation (like preview)

**Comment by EvgenBabenko** [comment]
> The same situation in v5 antd

yeah, just checked, latest version has the same behaviour

**Comment by MadCcc** [comment]
Show split upload btn and file list

**Comment by EvgenBabenko** [comment]
> Show split upload btn and file list

can you explain what do you mean?
