### ISSUE TITLE
antd5 主题，组件token变量不生效，例如button的defaultBg

### ISSUE THREAD

**Issue by bigyellowhsy** [ant-design/ant-design#46178]
### Reproduction link

[https://ant.design/docs/react/migrate-less-variables-cn#button-%E6%8C%89%E9%92%AE](https://ant.design/docs/react/migrate-less-variables-cn#button-%E6%8C%89%E9%92%AE)

### Steps to reproduce

<ConfigProvider wave={{disabled: true}} theme={{
      components: {
        Button: {
          "defaultBg": "rgb(255, 242, 242)",
        }
      }
    }}>
      <Button />
    </ConfigProvider>

### What is expected?

组件主题生效

### What is actually happening?

全局token变量生效，组件私有的主题变量不生效

| Environment | Info |
| --- | --- |
| antd | 5.4.7 |
| React | 18 |
| System | macOS 13.4.1 |
| Browser | chrome |

**Comment by bigyellowhsy** [comment]
> Hello @bigyellowhsy. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @bigyellowhsy，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

复现demo:https://codesandbox.io/p/sandbox/interesting-einstein-qd897p?file=%2Fsrc%2FApp.tsx%3A11%2C22

**Comment by afc163** [comment]
See https://codesandbox.io/p/sandbox/confident-bas-r4255r?file=%2Fpackage.json%3A8%2C29

1. 请升级 antd 到最新版本。
2. `defaultBg` 只对 `type="default"` 的按钮生效，即 `<Button>按钮</Button>`。

**Comment by bigyellowhsy** [comment]
![20231130113232](https://github.com/ant-design/ant-design/assets/152458490/46e3c4e1-295c-4462-a195-6ef05dff91fb)
这里ts问题要怎么解决呢

**Comment by afc163** [comment]
> 请升级 antd 到最新版本。

**Comment by bigyellowhsy** [comment]
但为什么这个编辑器里，针对不同类型（type）的button都生效呢：https://ant-design.antgroup.com/theme-editor-cn#Style

**Comment by afc163** [comment]
<img width="1415" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/c1cba217-2e10-426c-a669-648366e17b93">

我看到的是这样的，至少不会对 primary 类型的按钮生效。
