### ISSUE TITLE
期望能够在Input组件中实现输入自定义tag标签，并能限制输入的tag数量，且可用于Form组件

### ISSUE THREAD

**Issue by Taylord-Lee** [ant-design/ant-design#46183]
### What problem does this feature solve?

使用场景：
例如搭建一个中介性质的平台时，在商户入驻后，期望能够自定义一些特色标签。
提供一个表单Input输入框，自定义输入内容后，回车即完成分词，自动生成一个tag可比较高效地满足此需求。同时为了限制用户的过量输入，可为Input添加展示标签数量的计数进行上限控制。

### What does the proposed API look like?

API可借鉴Select组件，提供一个mode属性，例如：
```
<Input mode="tag" showCount maxTag={5} />
```
当应用于Form时，可受rules约束
```
<Form.Item rules={[{ maxTag: 5, message: "error msg" }]}>
    <Input mode="tag" showCount />
</Form.Item>
```

**Comment by afc163** [comment]
https://ant.design/components/select-cn#select-demo-tags

**Comment by zombieJ** [comment]
https://ant-design.antgroup.com/components/select-cn#select-demo-tags

**Comment by Taylord-Lee** [comment]
> https://ant.design/components/select-cn#select-demo-tags

可是，这个组件没有办法像Input.Textarea似的进行tag数量的计数及限制啊，设置maxTagCount的话到达数量后还是可以继续输入的

**Comment by TwT-L** [comment]
> https://ant.design/components/select-cn#select-demo-tags

想要这样的交互，不需要下拉选项框
https://tdesign.tencent.com/vue/components/tag-input?tab=api
https://arco.design/vue/component/input-tag
https://fusion.design/gov/biz/853?themeid=10576

**Comment by hzc011213** [comment]
<Select mode="tags" dropdownStyle={{display: 'none'}}  />
暂时可以这样实现
