### ISSUE TITLE
无法找到Layout，为undefined

### ISSUE THREAD

**Issue by sopaco** [ant-design/ant-design#4618]
无法找到Layout，为undefined，引用方式如下
```js
import {
   Layout
} from 'antd';
```
#### 依赖配置
```json
"dependencies": {
    "antd": "^2.6.3",
    "core-js": "^2.0.0",
    "json-loader": "^0.5.4",
    "moment": "^2.17.1",
    "normalize.css": "^4.0.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1"
  }
```

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

**Comment by afc163** [comment]
请给重现后 reopen。

**Comment by tkssharma** [comment]
Layout，为undefined

import React, { PropTypes } from 'react'
import { Layout, Row, Col, Icon, Badge, Menu, Dropdown } from 'antd'
import './index.less'
import { Link } from 'react-router'

const contextTypes = {
  router: PropTypes.object.isRequired
};
console.log(Layout);
const { Header } = Layout;

export default class commonHeader extends React.Component {
  constructor () {
    super()
  }

// const { Header } = Layout;
 @header is coming as undefined

**Comment by afc163** [comment]
@tkssharma Could you provide a re-producible demo?

**Comment by tkssharma** [comment]
this is as simple as this 
import { Layout, Row, Col, Icon, Badge, Menu, Dropdown } from 'antd'

// and just do this in your component, i am getting only row col object Layout is undefined 
@using    "antd": "^2.8.0", 
console.log(Layout)

**Comment by afc163** [comment]
I don't think you install the right version of 'antd'.

Please check it by `npm ls antd` or `cat node_modules/antd/package.json | grep version`

**Comment by rdshoep** [comment]
I had this problem too.
antd: 2.13.7

And I have tried to `rm -rf node_modules/ && npm install`，It's useless.


I found that:
1.
```js
import {Layout} from 'antd'
const {Header, Footer, Content} = Layout

render(){
    <Layout>
        <Header></Header>
        <Content></Content>
        <Footer></Footer>
    </Layout>
}
```
It's OK.

2.
```js
import {Layout} from 'antd/lib/layout'

render(){
    <Layout>
        <Layout.Header></Layout.Header>
        <Layout.Content></Layout.Content>
        <Layout.Footer></Layout.Footer>
    </Layout>
}
```
It's OK.

3.
```js
import {Layout} from 'antd'

render(){
    <Layout>
        <Layout.Header></Layout.Header>
        <Layout.Content></Layout.Content>
        <Layout.Footer></Layout.Footer>
    </Layout>
}
```
It will throw error: `Layout is not undefined`.

Thoughts:
I use the plugin named **`babel-plugin-import`**. Maybe here?

**Comment by rdshoep** [comment]
I have comment the same issue in [babel-plugin-import/issues: Menu is not defined](https://github.com/ant-design/babel-plugin-import/issues/172)

**Comment by gchansc** [comment]
Did anyone resolved this Reference Error: is not defined?

I am having the same issue.

**Comment by shaddu** [comment]
I was getting the same issue but sorted after updating by antd version to "^3.2.2",

**Comment by yummyelin** [comment]
It's related to #5060, check the solution there.

**Comment by sylhero** [comment]
if you do ```const {Header } = Layout``` jest will complain Layout undefined. Is there a way to get around of this?

**Comment by coderek** [comment]
`import Layout from 'antd/lib/layout'`

**Comment by coderek** [comment]
Came across this again. If you run jest using `--runInBand` the error seems gone.

**Comment by thiporia** [comment]
antd: 3.23.4
I also had this problem.
To solve the problem
```
import {Layout} from'antd';

...
<Layout.Content
...
```
Solved in the same form as.

If css is broken,
ʻImport'antd/dist/antd.css'`
I think you can add
