### ISSUE TITLE
增加右键菜单组件

### ISSUE THREAD

**Issue by gitxiwei** [ant-design/ant-design#46181]
### What problem does this feature solve?

在数据表格上添加大量的按钮，而右键菜单提供了一种高效的方式来管理和呈现操作选项。有时需要再Tree组件上实现右键菜单交互，自己实现往往与antd风格不一致。

### What does the proposed API look like?

import { ContextMenu } from 'antd';

<ContextMenu items={[ { key: 1, label: '打开' } ]} />

**Comment by kiner-tang** [comment]
这个不能满足需求吗？https://ant.design/~demos/components-dropdown-demo-context-menu

**Comment by zombieJ** [comment]
[右键菜单](https://ant-design.antgroup.com/components/dropdown-cn#components-dropdown-demo-context-menu)
