### ISSUE TITLE
Tab 左侧展示时出现闪烁情况

### ISSUE THREAD

**Issue by yyz945947732** [ant-design/ant-design#46198]
### Reproduction link

[https://codepen.io/yyz945947732/pen/xxMjjvZ?editors=0010](https://codepen.io/yyz945947732/pen/xxMjjvZ?editors=0010)

### Steps to reproduce

Tabs 组件在设置 `tabPosition="left"` 后，不固定高度的情况下，底部 icon 有可能出现不断切换显示隐藏的状态。

根据浏览器分辨率不同可能出现这种情况，并都可以通过缩放浏览器到某个比例复现出来。

<img width="269" alt="image" src="https://github.com/ant-design/ant-design/assets/47586954/26536512-a523-4c59-9b29-8586b84ea8d9">

https://github.com/ant-design/ant-design/assets/47586954/8b7b7968-d368-4564-a50d-24200b461d57

https://github.com/ant-design/ant-design/assets/47586954/6a8cd424-0ea4-4a5d-b5f4-777c6f5ebd9d

### What is expected?

不出现闪烁的情况。

### What is actually happening?

出现闪烁的情况。

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 无关 |
| System | 无关 |
| Browser | 116.0.5845.110 |

**Comment by yyz945947732** [comment]
https://github.com/ant-design/ant-design/issues/39079

**Comment by afc163** [comment]
Reproduce: https://stackblitz.com/edit/antd-reproduce-5x-cauuyv?file=demo.tsx
