### ISSUE TITLE
Rangepicker with limited date selection fails to set endlimit when mouseclick is used to set focus to second input field

### ISSUE THREAD

**Issue by MatthiasVermeiren** [ant-design/ant-design#46194]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/select-range-dates-in-7-days-antd-5-11-5-t672tq?file=%2Fdemo.tsx)

### Steps to reproduce

The link to minimal reproduction actually links to the Antd Datepicker demo: https://ant.design/components/date-picker#components-date-picker-demo-select-in-range

1. Click on Startdate in the rangepicker component
2. Type a valid date, for example 2023-11-30
3. Don't press enter or don't click any specific startdate in the dropdown
4. Click on the enddate input-field
5. It is possible to select or to type an enddate which is out of the allowed bounds, e.g. one month later: 2023-12-30 

### What is expected?

I would expect that when a startdate is entered and the input field loses focus (for example by clicking on the enddate inputfield), the dates which are not allowed are no longer selectable.

### What is actually happening?

Any date after the startdate is selectable, even the ones who are after startdate   7days. 

The component does correctly disable enddate selections when the user first types a startdate followed by an enter: the enddate selection is adjusted to the startdate   7 days. All the other dates are greyed out.

When the user then types an out-of-bounds enddate (which is greyed out in the component), the demo even gives a typescript error. 

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2.0 |
| System | MacOs Sonoma 14.1.1 |
| Browser | Google Chrome Version 119.0.6045.159 (Official Build) (arm64) |

---
I think there might be a bug in both the component (not correctly greying out/disabling dates), as well as in the Datepicker demo (typescript error when entering a date which is out of the allowed range   hitting enter).

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
