### ISSUE TITLE
Image   预览按钮大小和位置能否改变，比如移动到左上角

### ISSUE THREAD

**Issue by yanghtGithub** [ant-design/ant-design#46190]
### What problem does this feature solve?

预览的按钮移动到左上角，并且一直显示，而不是鼠标移过去之后才显示

### What does the proposed API look like?

无

**Comment by zombieJ** [comment]
什么组件？

**Comment by yanghtGithub** [comment]
> 什么组件？

Image

**Comment by yanghtGithub** [comment]
![Snipaste_2023-11-30_16-33-20](https://github.com/ant-design/ant-design/assets/72773874/bfbc20e4-fb82-404f-a9ef-bc8d1b752f05)
想整个这样式的，移到左上角，鼠标在其他位置上不会有遮罩的样式，预览的按钮会一直显示，点击后弹出图片预览

**Comment by MadCcc** [comment]
这个建议自行魔改一下，现在是设计如此的

**Comment by yanghtGithub** [comment]
> ![Snipaste_2023-11-30_16-33-20](https://private-user-images.githubusercontent.com/72773874/286870720-db634c96-5e2f-4ddb-af19-0dbcea7ff47b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzQ1MzksIm5iZiI6MTcwMTMzNDIzOSwicGF0aCI6Ii83Mjc3Mzg3NC8yODY4NzA3MjAtZGI2MzRjOTYtNWUyZi00ZGRiLWFmMTktMGRiY2VhN2ZmNDdiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4NTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YTM5NmE2OTY1M2E5YzEzNjM2ZTNiZjRjZDUxMjJhOTQ2MThmMDI3YjQxODE2YzczMjE4YTU2YjY1NGM0NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rX4b6NujZ43dC6kx_6qkbR75nnOFTVNHfl8s-W_PVc) 这样操作可以吗

图片上不要预览，旁边加一个按钮
