### ISSUE TITLE
Upload 组件开启多选上传, 页面变得极其卡顿

### ISSUE THREAD

**Issue by yuriwxc** [ant-design/ant-design#4620]
如题:  
  例子可以使用 https://ant.design/components/upload-cn/#components-upload-demo-fileList
   完全控制的上传列表, 同时上传5个文件以上,页面几乎无法滚动

**Comment by benjycui** [comment]
这个？ https://github.com/ant-design/ant-design/issues/3002

**Comment by yuriwxc** [comment]
好像不太一样, 我在官网上面操作完全受控那个例子, 任意选择了5个以上每个大小超过10M的任意文件, 然后页面就比较卡了,  选择更多会更卡

**Comment by benjycui** [comment]
> 任意选择了5个以上每个大小超过10M的任意文件, 然后页面就比较卡了, 选择更多会更卡

。。。。

完全受控意味着你把这五个文件就是 50M 以上的东西存在了内存。

尝试：
* 用较小的文件看还卡不卡。
* 用原生 `input[type=file]` 上传 5 个 10M 以上的文件看卡不卡。

**Comment by afc163** [comment]
@yuriwxc

**Comment by benjycui** [comment]
Close for no response, and you can re-open anytime if you can provide more info.
