### ISSUE TITLE
5.11.x版本Input组件，safari浏览器，无论受不受控，中文输入都会导致拼音字母也显示在输入框内

### ISSUE THREAD

**Issue by tcyufeng** [ant-design/ant-design#46200]
### Reproduction link

[https://github.com/tcyufeng/demo](https://github.com/tcyufeng/demo)

### Steps to reproduce

npm start
用safari访问，我的safari 版本 是15.3 (17612.4.9.1.8)

### What is expected?

可以正确输入中文

### What is actually happening?

比方我打一个的字，在输入框中显示的的 ”dde的“

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2.0 |
| System | macOS 12.2.1 (21D62) |
| Browser | safari |

**Comment by tcyufeng** [comment]
降级到5.10.x就不存在这个问题

**Comment by yoyo837** [comment]
locker文件存在私有镜像，请更新一下仓库，能直接npm install的

**Comment by MadCcc** [comment]
麻烦提供个 CodeSandbox 复现吧

**Comment by tcyufeng** [comment]
> locker文件存在私有镜像，请更新一下仓库，能直接npm install的

已经删除lock文件

**Comment by zombieJ** [comment]
> 测试了几台mac，只有我的会复现

指的是其他 MAC 的 Safari 也都是 15 版本的么？

**Comment by tcyufeng** [comment]
> > 测试了几台mac，只有我的会复现
> 
> 指的是其他 MAC 的 Safari 也都是 15 版本的么？

一台是15.6.1，一台是16.6
然后我又做了个测试，一开始我使用的是搜狗输入法，我卸载后使用mac自带输入法还是同样的结果
![0r0rs-vfyq4](https://github.com/ant-design/ant-design/assets/28287106/d2553f1a-cffe-4e46-8e71-978e1b405eb2)

**Comment by zombieJ** [comment]
这边没有旧版本的 MAC，帮忙看看？

**Comment by yyz945947732** [comment]
safari 浏览器限制了 input value 的 getter。

https://github.com/react-component/input/blob/a48e9b96a7c670001faf41ff8b1499bd975b4850/src/utils/commonUtils.ts#L61

<img width="404" alt="image" src="https://github.com/ant-design/ant-design/assets/47586954/874e44c7-d86f-40ba-9309-0961b19f033e">

<img width="841" alt="image" src="https://github.com/ant-design/ant-design/assets/47586954/99e0eff4-cd36-48b5-927e-db66a1f42258">

**Comment by congjiujiu** [comment]
同问题，请问什么时候发版

**Comment by yoyo837** [comment]
https://github.com/react-component/input/releases/tag/v1.3.11
