### ISSUE TITLE
upload组件上传到服务器并返回预览图前端配置方法

### ISSUE THREAD

**Issue by yangggggg** [ant-design/ant-design#4621]
我从后端接口那token，然后传到七牛，七牛返回图片名称，我再渲染到前台，我想问下 antd upload组件怎么配置可以实现此功能

**Comment by yesmeck** [comment]
这种使用问题建议到 https://segmentfault.com/t/antd 上提问。

**Comment by afc163** [comment]
https://github.com/die-welle/tiny-qiniu-request

**Comment by afc163** [comment]
https://segmentfault.com/a/1190000011174923
