### ISSUE TITLE
Allow Select to accept children and render them instead as Tags

### ISSUE THREAD

**Issue by LorenzoElenkov** [ant-design/ant-design#46216]
### What problem does this feature solve?

Allow developers to implement react-dnd library in order to be able to move tags inside Select.

I am trying to implement React-dnd into `<Select mode="tags" />` but I cannot since I cannot place `<DndContext>` element inside of the select component, which allows items to be dragged around and reordered on drop.

### What does the proposed API look like?

```typescript

<Select mode="tags" value={["A", "B", "C"]} onChange={onChange}>
   <DndContext>
      <SortableContext>
          { ({ values }) => {
             return values.map(value => <Tag>{value}</Tag>)
          }}
 // OR
         ReactStateValues.map(value => <Tag>{value}</Tag>)
      </SortableContext>
    </DndContext>
</Select>

``` 

Currently, all children are ignored and instead the values of the Form.Item (parent of Select) are taken into consideration.

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by LorenzoElenkov** [comment]
> What does the proposed API look like?

Updated

**Comment by afc163** [comment]
You can try `optionRender`: https://github.com/ant-design/ant-design/pull/45529

**Comment by zombieJ** [comment]
Select `children` is used for Select.Option not selector content. Use `tagRender` for customize logic
