### ISSUE TITLE
建议Tree里面每一个Node加一个extra属性 可以带上额外的用户自定义属性上去

### ISSUE THREAD

**Issue by day-xue** [ant-design/ant-design#46212]
### What problem does this feature solve?

解决了拿到每一个node的时候拿到的额外的自定义的数据，就不用递归去查询原始数据了

### What does the proposed API look like?

DataNode 这个类型新增一个extra属性

**Comment by Wxh16144** [comment]
`titleRender` 应该可以满足你的需求，之前有过 [一个 RFC](https://github.com/ant-design/ant-design/discussions/43259) 讨论结果就是和 `titleRender` 重复了。

**Comment by afc163** [comment]
现在就可以拿到的，`onCheck` 的参数里面可以拿到 node 对象。

**Comment by afc163** [comment]
> 没有好的ts支持

给个重现看看什么问题？
