### ISSUE TITLE
Table 组件在 safari 下 render 时表头闪烁的问题

### ISSUE THREAD

**Issue by lucky3mvp** [ant-design/ant-design#4622]
#### Environment(required)

- antd version: 2.5.3
- OS and its version: mac
- Browser and its version: 9.1.2

#### What did you do? Please provide steps to re-produce your problem.

safari 浏览器下表头会闪烁，例子参见官网例子：‘远程加载数据’，https://ant.design/components/table-cn/#components-table-demo-ajax  
当选择不同分页，从服务器加载数据并 render table 时，表头会先不可见再可见这么闪烁一次 

#### What do you expected?

此现象在 chrome 下未见，因此希望是像 chrome 那样，表头不会闪烁

**Comment by yesmeck** [comment]
好像是 Spin 导致的，这里[例子](https://ant.design/components/table-cn/#components-table-demo-dynamic-settings)  打开 `loading`  表头也会消失。

**Comment by afc163** [comment]
非常诡异的问题，和网站右侧的 Affix 有关，满足下面两条任意一条，问题消失。

- [ ] 移除 Affix 菜单。
- [ ] Affix 菜单的 `z-index` 变为 9。（小于 hover 的 demo 卡片的 z-index）。

**Comment by lucky3mvp** [comment]
@afc163 

呃。。。 我在项目中并没有用到affix啊，虽然有右侧菜单，但是没有affix，菜单定位也没用到fixed...

我系统的布局是这样的：
-header
-body
  |-menu
  |-content

整个上下结构，局部左右结构

我尝试你说的解决方法：移除菜单（虽然不是用affix写），问题依然存在，事实上当我移除了header后，闪烁的现象就不存在了，但是删除的操作肯定不可行啊，系统需要header或者menu

**Comment by afc163** [comment]
那只是我排查的过程而已，并不是解决方案。
