### ISSUE TITLE
Table 开启 Virtual 后Fixed的列样式丢失，滚动后才显示出来

### ISSUE THREAD

**Issue by FrattiNor** [ant-design/ant-design#46222]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-h7dnf9)

### Steps to reproduce

默认触发

### What is expected?

fixed样式显示正常

### What is actually happening?

fixed样式丢失

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | ^18.2.0 |
| System | Windows |
| Browser | Chome版本 111.0.5563.111 |

**Comment by MadCcc** [comment]
初始的时候没有滚动是没有阴影的，这是预期的
