### ISSUE TITLE
ConfigProvider 给组件 Dropdown 单独传入  motion: false 还是有动画

### ISSUE THREAD

**Issue by JackDeng666** [ant-design/ant-design#46221]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qvyrgh)

### Steps to reproduce

ConfigProvider Dropdown 传入  motion: false
      theme={{
        // token: {
        //   motion: false
        // },
        components: {
          Dropdown: {
            motion: false
          }
        },
      }}

### What is expected?

Dropdown 打开不再有动画

### What is actually happening?

Dropdown 打开还有动画

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2.0 |
| System | win11 |
| Browser | chrome 119.0.6045.161 |

**Comment by afc163** [comment]
目前还不支持单独定制某个组件的 motion。
