### ISSUE TITLE
组件 segmented 的 option.value 支持 boolean 类型

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#46234]
### What problem does this feature solve?

用于类似开关控制切换的效果，也类似 Tab 切换。

虽然 tab/switch 组件也可以做到，但是 segmented 样式以及 block 的效果会比较好看。

### What does the proposed API look like?

https://github.com/react-component/segmented/blob/master/src/index.tsx#L9

```diff
- export type SegmentedValue = string | number;
+ export type SegmentedValue = string | number | boolean;
```

```tsx
const Demo: React.FC = () => (
  <Segmented
    options={[
      { label: '教学空间', value: true },
      { label: '学习空间', value: false },
    ]}
  />
);
```

**Comment by zhenzhenChange** [comment]
顺带在此一提，`Tabs`组件是否也能够支持泛型呢？目前仅支持 string 类型，有一些场景是，使用 enum 作为 Tab 页的 key，而 enum 的值可能是 number 类型。

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/47091
