### ISSUE TITLE
Text 组件，溢出省略，悬停显示tooltip，但是一些情况下溢出省略了，悬停并没有tooltip

### ISSUE THREAD

**Issue by hzw177** [ant-design/ant-design#46238]
### What problem does this feature solve?

Text 组件，溢出省略，悬停显示tooltip

### What does the proposed API look like?

符合预期，在设定了宽度和tooltip时，有溢出的话那就都能省略且悬停显示tooltip
  return (
    <Text
      style={{ width: props?.width }}
      ellipsis={{ tooltip: props.children }}
    >
      {props.children}
    </Text>
  );
原因：滚动宽度的小数是四舍五入的，实际宽度是存在小数，页面是根据样式，所以会判断为溢出省略，但是判断是否悬停显示tooltip时是判断的四舍五入后的数，舍去后比较就会不符合悬停显示tooltip了，导致页面出现有省略号悬停不显示tooltip的bug情况

**Comment by afc163** [comment]
这是一个问题反馈，你需要使用 bug report 模板（而不是 feature request 模板）来创建 issue。
