### ISSUE TITLE
tree只支持children格式的数据吗

### ISSUE THREAD

**Issue by liu2080019** [ant-design/ant-design#4623]
之前一直用的是ztree，现在想统一风格，改成ant的，但是看了demo，初始化数据都是要带children的？才能渲染2级，3级类目？ 我们这边数据是{id:1001,pid:0.......}，pid是父级的id。 之前的ztree能直接对这个数据初始化渲染，求助。ant是不是也支持，我没找到？

**Comment by yesmeck** [comment]
`Tree` 暂不支持，自己转换下吧。

**Comment by liu2080019** [comment]
好的 谢谢 @yesmeck
