### ISSUE TITLE
List 组件中的 itemLayout 和grid 两个 API 同时用之后排版会出问题

### ISSUE THREAD

**Issue by andylili21** [ant-design/ant-design#46245]
### Reproduction link

[https://codepen.io/andylili21/pen/yLZQQGW](https://codepen.io/andylili21/pen/yLZQQGW)

### Steps to reproduce

demo：https://ant-design.antgroup.com/components/list-cn#list-demo-vertical
添加Api：<List
    grid={{ column: 2 }}
    itemLayout="vertical"
...

### What is expected?

保持竖直列表样式的基础上可以栅格化控制排版

### What is actually happening?

用栅格控制之后失去了竖直状态的样式

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.0.33 |
| System | MacOS |
| Browser |  Chrome 119.0.6045.199（正式版本） (arm64) |

**Comment by MadCcc** [comment]
没有设想过 grid 和 itemLayout 组合使用

**Comment by andylili21** [comment]
> 没有设想过 grid 和 itemLayout 组合使用

oo 所以这个问题也不需要pr和建议啥的嘛
