### ISSUE TITLE
Typography排版 定制参数 titleMarginTop 不起作用

### ISSUE THREAD

**Issue by jkiss** [ant-design/ant-design#46243]
### Reproduction link

[https://github.com/jkiss/antd-bug-20231204](https://github.com/jkiss/antd-bug-20231204)

### Steps to reproduce

1. 启动项目
```
npm run dev
```

2. 打开浏览器：http://localhost:3000/

3. 查看 Title margin-top style

### What is expected?

Title组件 margin-top 为 0

### What is actually happening?

Title组件 margin-top 为 UA 默认值 0.67em

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | ^18 |
| System | MacOS 14.1.1 |
| Browser | Google Chrome 119.0.6045.199 |

**Comment by jkiss** [comment]
> Reproduction `npm install` 不了，麻烦给个 codesandbox 吧

用 codesandbox 自带的starter建了一个demo：https://codesandbox.io/p/sandbox/elegant-keller-m5zl6c?file=%2Fsrc%2FApp.js

**Comment by MadCcc** [comment]
已经生效了，影响的是浏览器自带的 h1 样式，可以使用 `antd/dist/reset.css` 重置一下

**Comment by jkiss** [comment]
那为什么 titleMarginBottom 不需要 reset 就生效了呢？不觉得奇怪吗？@MadCcc

**Comment by jkiss** [comment]
titleMarginBottom 会设置一个 `margin-bottom: 0;`，但 titleMarginTop 就不会，这不是bug？@MadCcc

**Comment by abiriadev** [comment]
Would you recommend some current workarounds to set the `margin-top` of 'each' `<Typography.Title />` to 0? What are the possible ways as of now?

（中文）您是否会建议当前的解决方法将“each”“<Typography.Title />”的“margin-top”设置为 0？ (machine translated. may not correct.)

Regards.

**Comment by elvinasv** [comment]
The issues is still relevant. 
Documentation re. [Typography tokens](https://ant.design/components/typography#design-token) appears to be misleading or there may be a bug. 

Specifically, the token `titleMarginTop: 0` only takes effect on the second `<Typography.Title />`, while `titleMarginBottom: 0` affects both the first and second components.

i.e. 
```js
<Typography.Title level={3}>Title</Typography.Title> {/* margin-top: 12px (default  ❌); margin-bottom: 0 (titleMarginBottom ✅) */}

<Typography.Title level={3}>Title</Typography.Title> {/* margin-top: 0 (titleMarginTop ✅); margin-bottom: 0(titleMarginBottom ✅) */}
```
