### ISSUE TITLE
Slider 组件支持多个 mark 之间 step 不同

### ISSUE THREAD

**Issue by wpsumsun** [ant-design/ant-design#46247]
### What problem does this feature solve?

类似于这个页面注册资本的情况  多个mark之前step不一致
https://www.qcc.com/web/search/advance?hasState=true

### What does the proposed API look like?

期望支持

**Comment by li-jia-nan** [comment]
不如直接贴个图
<img width="383" alt="image" src="https://github.com/ant-design/ant-design/assets/49217418/91287a4b-9023-4427-99b1-ae725310cd0c">
