### ISSUE TITLE
Text 组件，溢出省略，悬停显示tooltip，但是一些情况下溢出省略了，悬停并没有tooltip

### ISSUE THREAD

**Issue by hzw177** [ant-design/ant-design#46241]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qyhmdp?file=%2Findex.js%3A17%2C3)

### Steps to reproduce

省略了，但是悬停不显示悬停的tooltip

### What is expected?

省略和悬停显示tooltip

### What is actually happening?

省略了，悬停不显示tooltip

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react18 |
| System | * |
| Browser | * |

---
原因：滚动宽度的小数是四舍五入的，实际宽度是存在小数，页面是根据样式，所以会判断为溢出省略，但是判断是否悬停显示tooltip时是判断的四舍五入后的数，舍去后比较就会不符合悬停显示tooltip了，导致页面出现有省略号悬停不显示tooltip的bug情况

**Comment by afc163** [comment]
Chrome 下还真的不行。。

**Comment by cwjTerrace** [comment]
https://github.com/tusen-ai/naive-ui/commit/3d2074d7ab4e654f34e41461c8733400eadf69d9
naive-ui的解法是多套了一层

**Comment by shengzhou1216** [comment]
好像是缩放的问题，EllipsisProps.onEllipsis 没有被调用

**Comment by hzw177** [comment]
> [tusen-ai/naive-ui@ 3d2074d](https://github.com/tusen-ai/naive-ui/commit/3d2074d7ab4e654f34e41461c8733400eadf69d9) naive-ui的解法是多套了一层

这个方法可以，自己封装了一个类似组件可以行得通
 setTooltip(
        triggerInnerRef.current &&
          textRef.current &&
          triggerInnerRef.current?.getBoundingClientRect()?.width >
            textRef.current?.getBoundingClientRect()?.width
          ? props.title || props.children
          : '',
      );

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/50315
