### ISSUE TITLE
input框建议focus状态给box-shadow添加blur

### ISSUE THREAD

**Issue by woshiguabi** [ant-design/ant-design#4624]
官网最新版本
input在focus状态下的box-shadow样式只设置了spread，没有设置blur，如果设置1-2个像素的blur会不会视觉效果更好？

目前版本：
box-shadow: 0 0 0 2px rgba(16, 142, 233, 0.2);
![shadow1](https://cloud.githubusercontent.com/assets/17465858/22011394/d28c8f64-dcc9-11e6-8b42-cf1e54fe6016.png)

修改后：
box-shadow: 0 0 2px 2px rgba(16, 142, 233, 0.2);
![shadow2](https://cloud.githubusercontent.com/assets/17465858/22011469/3f945132-dcca-11e6-9378-4fd3f7b23f04.png)

**Comment by Chinglik** [comment]
哈哈，其实『实体外发光』是我们其中的一个风格体现哦。☝️💡

**Comment by woshiguabi** [comment]
> 其实『实体外发光』是我们其中的一个风格体现哦。☝️💡
我看官网里面其他box-shadow都有添加blur效果所以特地来问问
