### ISSUE TITLE
allow treeselect item to have multiple parents

### ISSUE THREAD

**Issue by laszlo-zaptic** [ant-design/ant-design#46259]
### What problem does this feature solve?

i need the same nodes to be rendered in different parts of the hierarchy. 

### What does the proposed API look like?

now with `treeDataSimpleMode` i can only set one id for `pId: 1` but i need an array like `pId: [1,2]`. or with the regular `treeData` but allowing same `value` fields.

**Comment by MadCcc** [comment]
It doesn't make sense. TreeSelect requires each child with different `value`.
