### ISSUE TITLE
Select value 值是空字符串 placeholder 不显示

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46269]
### Reproduction link

[https://stackblitz.com/edit/react-epaif6?file=demo.tsx](https://stackblitz.com/edit/react-epaif6?file=demo.tsx)

### Steps to reproduce

打开 demo

### What is expected?

显示 placeholder

### What is actually happening?

不显示 placeholder

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
`''` 是合法值，也就不会有 `placeholder` 了：

https://stackblitz.com/edit/react-epaif6-wtxtrn?file=demo.tsx

**Comment by crazyair** [comment]
那 null 也算合法值了，https://stackblitz.com/edit/react-epaif6-guhgfi?file=demo.tsx
![image](https://github.com/ant-design/ant-design/assets/7971419/14c66f17-072f-40d5-8b7f-cb0b9adc652e)

**Comment by zombieJ** [comment]
> 那 null 也算合法值了

嗯，不过 `null` 比较特殊。它是没有的时候作为空，有的时候作为值。
