### ISSUE TITLE
Add className for inner child div's of components (i.e Card)

### ISSUE THREAD

**Issue by nadavhalfon** [ant-design/ant-design#46260]
### What problem does this feature solve?

For a better usability with TailwindCSS, I suggest that components that has one inner child that wraps everything that it'll be easy to add className, for example the body of a Card.
Moreover I think antd can improve in manner of customizations, lot's of properties are still hidden even in v5.
If tailwindcss can be used with it, it'l be great.
sometime there is a need to use important over antd classes which I didn't still realize why it rise above the immediate className being applied.

Thank you!

### What does the proposed API look like?

`<Card className="items-strech"/>` 
Or if you don't to use the className prop maybe create something similar to the `bodyStyle`

**Comment by MadCcc** [comment]
Feature request for `classNames` and `styles` of Card
