### ISSUE TITLE
Unable to use file input type

### ISSUE THREAD

**Issue by guepjo** [ant-design/ant-design#46267]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8q2w3j)

### Steps to reproduce

Select input file

### What is expected?

Input file selected

### What is actually happening?

Error: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18.2.0 |
| System | macOS Ventura 13.0 |
| Browser | Chrome 119.0.6045.123 |

**Comment by zombieJ** [comment]
感觉是命中切割逻辑了。

**Comment by zombieJ** [comment]
I though was the formatter issue but found it's not. What's the reproduce step of this?
