### ISSUE TITLE
watermark水印组件，希望它能够支持是否开启重复的功能

### ISSUE THREAD

**Issue by 350832850** [ant-design/ant-design#46263]
### What problem does this feature solve?

我希望在一个指定区域仅显示一个水印，而不是重复的多个

### What does the proposed API look like?
```
 <Watermark content="Ant Design" backgroundRepeat={false}>
    <div><div/>
  </Watermark>
```

**Comment by zombieJ** [comment]
水印目的就是覆盖内容，如果只需要单个的话直接用 image 就好了？

**Comment by MadCcc** [comment]
建议自行配置一下水印宽高以及 `gap` 和 `offset` 来只显示单个水印

**Comment by ryanwyhuang** [comment]
水印好像不支持safari浏览器？
