### ISSUE TITLE
Sourcemap error with vite

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#46273]
### Reproduction link

[https://github.com/vitejs/vite](https://github.com/vitejs/vite)

### Steps to reproduce

work with vite (5.0.3)

vite config

```ts
import { dependencies } from './package.json'

const { react: _react_dep, ...deps } = dependencies
const manualChunks = ((ids: string[]) => (id: string) => {
  for (const vendor of ids) {
    if (id.includes('modules/' + vendor)) {
      return 'third_party/' + vendor.replace('/', '-')
    }
  }
})(Object.keys(deps))

return {
    base: './',
    plugins: [dynamicImport(), react()],
    build: {
      rollupOptions: {
        output: {
          manualChunks,
        },
      },
      sourcemap: true,
    },
    server: {
      port: 5000,
    },
    resolve: {
      alias: {
        '@': path.join(__dirname, 'src'),
      },
    },
 },
```

run
```
npm run build
# vite build
```

### What is expected?

no errror complain

### What is actually happening?

![image](https://github.com/ant-design/ant-design/assets/20441896/4c4d0b08-b927-4c37-8059-97d8e69ae553)

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2 |
| System | win10 |
| Browser | 103 |

**Comment by apexof** [comment]
i have the same problem

**Comment by choyan** [comment]
Facing the same issue. Using Antd with our Vitejs setup. Getting these error messages when we are trying to build the project.

**Comment by hussion** [comment]
i have the same problem

**Comment by meme777momo777** [comment]
↑i have the same problem!!!
