### ISSUE TITLE
Mentions component supports 'allowClear' option

### ISSUE THREAD

**Issue by bbcvc** [ant-design/ant-design#46278]
### What problem does this feature solve?

1. Setting the allowClear option style is confusing. link: https://stackblitz.com/edit/react-bdlach?file=demo.tsx
2. Clear the input box with one click

### What does the proposed API look like?

```jsx
<Mentions allowClear />
```

**Comment by bbcvc** [comment]
![image](https://github.com/ant-design/ant-design/assets/52622877/b50a68de-2d04-4ece-94ce-30fb794ddbf6)

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/46396
