### ISSUE TITLE
RangePicker dropdown NaN

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#46272]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/range-picker-antd-5-12-1-forked-syqscs)

### Steps to reproduce

Please check Reproduction

### What is expected?

Still keep calendar in Dropdown

### What is actually happening?

Calendar show day is NaN

![image](https://github.com/ant-design/ant-design/assets/105255382/8928ab5d-50b1-4e27-9eff-4ef71ecd700d)

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.2.0 |
| System | Macbook Air M1 2020 - macOS 13.3.1 |
| Browser | Chrome 112.0.5615.137 |

**Comment by zombieJ** [comment]
Your reproduce dont shows NaN.

**Comment by archisketch-thangly** [comment]
@zombieJ sorry, i update reproduce

**Comment by solitia7125** [comment]
![image](https://github.com/ant-design/ant-design/assets/39177579/b0b1f7fe-d4a3-4011-bdb9-27bd280f20b9)

**Comment by afc163** [comment]
`dayjs("a")` 是非法日期。
