### ISSUE TITLE
请问Upload组件在设置了multiple: true的情况下，是否可以按照文件顺序一个一个上传，前面一个传完了才开始传下一个？

### ISSUE THREAD

**Issue by QDJobson** [ant-design/ant-design#4627]
请问Upload组件在设置了multiple: true的情况下，是否可以按照文件顺序一个一个上传，前面一个传完了才开始传下一个，而不是多个同时传。

**Comment by yesmeck** [comment]
`beforeUpload` 返回 false，然自己处理上传的请求。

使用问题建议上 https://segmentfault.com/t/antd 提问。
