### ISSUE TITLE
<Button type="secondary">

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#46282]
### What problem does this feature solve?

我们的项目中，需要用到三种按钮样式：

![image](https://github.com/ant-design/ant-design/assets/5836790/66781af3-e709-4d5c-abd5-358124a0cd3d)

我们计划从 Fusion Design 迁移到 Ant Design，而目前 Ant Design 只提供了两种 primary 和 default。

虽然 Ghost Button 能得到类似的效果，但是没有白色背景，在某些场景下还是有问题，不够灵活。

### What does the proposed API look like?

```jsx
<Button type="secondary">
```

**Comment by afc163** [comment]
Ant Design 设计规范中没有 secondary 类型，次级按钮请统一使用 default。
