### ISSUE TITLE
Button   Modal.Confirm 可以回车无限确认

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46285]
### Reproduction link

[https://ant-design.antgroup.com/components/modal-cn#modal-demo-confirm](https://ant-design.antgroup.com/components/modal-cn#modal-demo-confirm)

### Steps to reproduce

1. 点击 Confirm
2. 按下回车

### What is expected?

Confirm 关闭后，再按回车不再打开 Confirm

### What is actually happening?

回车可以无限打开 Confirm

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | latest |
| System | mac |
| Browser | chrome |

---
如果这个行为是必须的，是否可以有 api 控制关闭呢？

**Comment by zombieJ** [comment]
`focusTriggerAfterClose`
