### ISSUE TITLE
Layout 组件侧边栏自适应

### ISSUE THREAD

**Issue by pigletfly** [ant-design/ant-design#4628]
使用了 Layout 组件进行布局，采用了顶部侧边布局，发现 `Sider ` 下面 `Menu` 组件 border 的高度没有根据 `Content` 高度自适应

**Comment by ddcat1115** [comment]
Sider 默认是深灰底色，这里demo应该设置为白色，我加一下

**Comment by afc163** [comment]
<img width="987" alt="image" src="https://cloud.githubusercontent.com/assets/507615/22140578/2fb9cd90-df28-11e6-93d0-cc57fd758d5d.png">

两边高度不一致。

**Comment by ddcat1115** [comment]
已经加了 https://github.com/ant-design/ant-design/pull/4661/files#diff-733b3e4b7c75ec515b2c9c8a27224090R48
