### ISSUE TITLE
Table ref 被执行多次

### ISSUE THREAD

**Issue by woowalker** [ant-design/ant-design#46283]
### Reproduction link

[https://stackblitz.com/edit/react-qpxcfm?file=demo.tsx,index.tsx](https://stackblitz.com/edit/react-qpxcfm?file=demo.tsx,index.tsx)

### Steps to reproduce

Table 添加 ref 就行
`<Table ref={ref => console.log('ref', Math.random())} />`

### What is expected?

只执行一次

### What is actually happening?

非 StrictMode 模式下
在 stackblitz（重现链接中）执行了3次
在本人实际项目中执行了两次

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | win10 |
| Browser | Chrome 版本 119.0.6045.124（正式版本） （64 位） |

**Comment by zombieJ** [comment]
Table `ref` 不是直接传递 `dom` 元素，会通过 `useImperativeHandle` 聚合出一个包含 `nativeElement` 和 `scrollTo` 的 object。内部实现为：

```tsx
useImperativeHandle(ref, () => ({
      nativeElement: fullTableRef.current,
      scrollTo: ...
}));
```

由于 `fullTableRef` 本身也是 `RefObject`，所以不能作为 `useImperativeHandle` 的 `deps`。因而该代码没有添加 `deps` 进行去重。虽然 `ref` 会多次调用，但是这是符合 React `ref` 最后一次为目标 `ref` 的规范。

参考：
* https://react.dev/learn/referencing-values-with-refs#recap
* https://github.com/facebook/react/issues/9328

**Comment by AttackXiaoJinJin** [comment]
@zombieJ 但你这个table的ref其实是打破了开发者对react ref的固有认知，我觉得不是规范的写法：

> However, the most common use case for a ref is to access a DOM element.

https://react.dev/learn/referencing-values-with-refs#refs-and-the-dom
