### ISSUE TITLE
The number of icons in the icon library is too small, can you expand it?

### ISSUE THREAD

**Issue by HappyAxin** [ant-design/ant-design#46281]
### What problem does this feature solve?

Please add more icons to the icon library！！！
It would be better if it can be compatible with the icons under [Official Icon Library](https://www.iconfont.cn/collections/index?spm=a313x.collections_index.i1.da2e3581b.5ed03a8153MApZ&type=1).

### What does the proposed API look like?

`<IconName color={"#HEX"} size={Number} animation={boolean} style={{}}/>` is better

**Comment by afc163** [comment]
You can submit your requirement to https://github.com/ant-design/ant-design-icons/issues/71
