### ISSUE TITLE
Allow Anchor component to link to other pages (which do not start with #) again (deprecated in v5)

### ISSUE THREAD

**Issue by thomas-haufe** [ant-design/ant-design#46291]
### What problem does this feature solve?

I want to use the antd Anchor component in my sidebar as a means to navigate my app. As such, I want it to include not only anchor links which start with a # but also links to other pages of my app.

I can do this by using the `children` props of the Anchor to pass `<Link>`s from `react-router-dom`. However, this was deprecated in antd v5. Instead, I am supposed to use the `items` prop. If I do that, the URL is changed correctly, but the page also reloads which is a bad user experience.

This minimal example compares the two approaches and shows the problem: https://stackblitz.com/edit/stackblitz-starters-dgsz5i?file=src%2FMyAnchor.tsx

The change to deprecate the `children` prop of the Anchor component feels like it's removing this useful functionality. How should I solve my problem without it?

### What does the proposed API look like?

If there is a way to allow non-anchor links (links that do not start with a #) in the Anchor component using the items prop without triggering a page reload, that would be great.

If not, I propose to allow passing `<Link>`s as children as you see in the minimal example.

**Comment by MadCcc** [comment]
`title: <Link />`

**Comment by thomas-haufe** [comment]
Thank you.

For reference: This is a working example: https://stackblitz.com/edit/stackblitz-starters-vssfgx?file=src%2FMyAnchor.tsx
