### ISSUE TITLE
Vertical icon in Tabs

### ISSUE THREAD

**Issue by nadavhalfon** [ant-design/ant-design#46292]
### What problem does this feature solve?

Tabs component allow icon injection but only horizontal, allowing vertical icon will allow using Tabs similar to the Segmented with icon

### What does the proposed API look like?

```
  <Tabs
    defaultActiveKey="2"
    items={[AppleOutlined, AndroidOutlined].map((Icon, i) => {
      const id = String(i   1);
      return {
        label: <span>Tab {id}</span>,
        key: id,
        children: `Tab ${id}`,
        icon: <Icon />,
        iconAlignment: 'vertical'
      };
    })}
  />
```

**Comment by MadCcc** [comment]
It could be implemented by customizing `label`, and so as Segmented.
