### ISSUE TITLE
Dropdown下拉选中会触发父级元素监听事件

### ISSUE THREAD

**Issue by EmptyG2018** [ant-design/ant-design#46296]
### Reproduction link

[https://stackblitz.com/edit/stackblitz-starters-aheqen?file=src%2Findex.js](https://stackblitz.com/edit/stackblitz-starters-aheqen?file=src%2Findex.js)

### Steps to reproduce

    <div
      style={{ backgroundColor: 'red' }}
      onClick={() => {
        alert('触发了');
      }}
    >
      <Dropdown
        menu={{
          items: [
            {
              key: 'one',
              label: 'hello world',
            },
            {
              type: 'divider',
            },
            {
              key: 'two',
              label: 'hello jd',
            },
          ],
          onClick: (e) => {
            e.domEvent.stopPropagation();
          },
        }}
      >
        <Button onClick={(e) => e.stopPropagation()}>www</Button>
      </Dropdown>
    </div>

点击Dropdown分割线，依旧会触发事件

### What is expected?

下拉选中，不会触发父级元素事件

### What is actually happening?

Dropdown下拉选中会触发父级元素监听事件

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | Chrome 119.0.6045.159（正式版本） (arm64) |

**Comment by MadCcc** [comment]
由于是 Portal 实现，菜单事件会冒泡到外层，可以在外面包一层 span 或者 div 用来阻止冒泡

**Comment by afc163** [comment]
我看你给的例子是好的。

**Comment by afc163** [comment]
@MadCcc 可以给个 codesandbox 示例。

**Comment by EmptyG2018** [comment]
@afc163 

const Component = () => {
  return (
    <div
      style={{ backgroundColor: "red" }}
      onClick={() => {
        alert("触发了");
      }}
    >
      <span onClick={(e) => e.stopPropagation()}>
        <Dropdown
          menu={{
            items: [
              {
                key: "one",
                label: "hello world",
              },
              {
                type: "divider",
              },
              {
                key: "two",
                label: "hello jd",
              },
            ],
          }}
        >
          <Button>www</Button>
        </Dropdown>
      </span>
    </div>
  );
};

**Comment by EmptyG2018** [comment]
@afc163  在dropdown组件外层加个span阻止冒泡

```javascript
const Component = () => {
  return (
    <div
      style={{ backgroundColor: "red" }}
      onClick={() => {
        alert("触发了");
      }}
    >
      <span onClick={(e) => e.stopPropagation()}>
        <Dropdown
          menu={{
            items: [
              {
                key: "one",
                label: "hello world",
              },
              {
                type: "divider",
              },
              {
                key: "two",
                label: "hello jd",
              },
            ],
          }}
        >
          <Button>www</Button>
        </Dropdown>
      </span>
    </div>
  );
};
```
