### ISSUE TITLE
Radio组件使用CSS样式表修改圆角后出现异常竖线

### ISSUE THREAD

**Issue by sine2cr** [ant-design/ant-design#46298]
![Snipaste_2023-12-07_10-30-16](https://github.com/ant-design/ant-design/assets/85916743/1c16ca82-58fb-4572-af3e-d9077ee29cd4)

### Reproduction link

[https://ant-design.antgroup.com/components/radio-cn](https://ant-design.antgroup.com/components/radio-cn)

### Steps to reproduce

```
import React from 'react';
import { Radio } from 'antd';

const App: React.FC = () => (
  <div>
    <Radio.Group defaultValue="a" buttonStyle="solid">
      <Radio.Button value="a" style={{ marginRight: "3em", lineHeight: "3em", height: "3em" ,borderRadius:'25px'}}>Hangzhou</Radio.Button>
      <Radio.Button value="b" style={{ marginRight: "3em", lineHeight: "3em", height: "3em" ,borderRadius:'25px'}}>Shanghai</Radio.Button>
      <Radio.Button value="c" style={{ marginRight: "3em", lineHeight: "3em", height: "3em" ,borderRadius:'25px'}}>Beijing</Radio.Button>
      <Radio.Button value="d" style={{ marginRight: "3em", lineHeight: "3em", height: "3em" ,borderRadius:'25px'}}>Chengdu</Radio.Button>
    </Radio.Group>
    
  </div>
);

export default App;
```

### What is expected?

所有的单选按钮都为圆角

### What is actually happening?

除第一个按钮外的其他按钮全部在左侧出现异常竖线

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.2.0 |
| System | windows10 |
| Browser | edge 119.0.2151.97 |

**Comment by shengzhou1216** [comment]
reproduce: https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sddk8w?file=%2Findex.js%3A5%2C1-5%2C22

**Comment by shengzhou1216** [comment]
group 中 radio 前默认有一个分隔线
```
.ant-radio-button-wrapper:not(:first-child)::before {
  display: none;
}
```
可以临时解决
