### ISSUE TITLE
目录：设计-全局样式-色彩 不显示了

### ISSUE THREAD

**Issue by yxf007** [ant-design/ant-design#46297]
### Reproduction link

[https://ant-design.antgroup.com/docs/spec/colors-cn#%E5%9F%BA%E7%A1%80%E8%89%B2%E6%9D%BF](https://ant-design.antgroup.com/docs/spec/colors-cn#%E5%9F%BA%E7%A1%80%E8%89%B2%E6%9D%BF)

### Steps to reproduce

色彩不显示了

### What is expected?

显示

### What is actually happening?

未显示

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | xx |
| System | win |
| Browser | chrome |

**Comment by MadCcc** [comment]
镜像已更新
