### ISSUE TITLE
Support virtual table for editable cells

### ISSUE THREAD

**Issue by seallard** [ant-design/ant-design#46295]
### What problem does this feature solve?

Support editable cells in a table like [this](https://codesandbox.io/p/sandbox/editable-cells-antd-5-12-1-forked-ppkmkn?file=%2Fdemo.tsx%3A201%2C26). But I'm guessing the current architecture does not allow for overriding the body with custom cells and rows, as stated in the docs.

### What does the proposed API look like?

Like [this](https://codesandbox.io/p/sandbox/editable-cells-antd-5-12-1-forked-ppkmkn?file=%2Fdemo.tsx%3A201%2C26)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/46218#issuecomment-1842424241
