### ISSUE TITLE
pagination的onShowSizeChange中修改current无效

### ISSUE THREAD

**Issue by zerozaki0752** [ant-design/ant-design#4629]
- antd version: 2.6.0

使用Table自带的pagination
期望效果：当改变pageSize时当前页码current变成1
实际效果：页码会维持现状

在Table的pagination属性中声明onShowSizeChange函数
onShowSizeChange函数中调用this.setState修改current为1
```
onShowSizeChange:(current,pageSize) => {

        console.log("pageSize 变化的回调");
        this.setState({
            current:1,
            pageSize,
        });
        console.log("this.state",this.state);
      }
```
实际打印出this.state.current没有改变？

1、这是什么原因？
2、如何正确的实现这种效果？

**Comment by afc163** [comment]
http://stackoverflow.com/questions/36085726/setstate-in-reactjs-is-async-or-sync

建议自行研习 React 基础知识。
