### ISSUE TITLE
快速上手-Datepicker示例报错误

### ISSUE THREAD

**Issue by sukui** [ant-design/ant-design#463]
点击输入框触发错误信息:

Uncaught Error: Invariant Violation: ReactDOM.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React.

环境使用  antd-beta

**Comment by afc163** [comment]
试了一下，没有重现。。。

能否给出精准的操作步骤。

**Comment by benjycui** [comment]
可以试下 `rm -rf node_modules && npm install`

**Comment by sukui** [comment]
windows 7 使用 antd-init 初始化的时候有问题. 不知道跟 .net frame workd sdk2 有没有关系！
我自己用webpack 构建就没问题了！

**Comment by sukui** [comment]
解决了！  安装了 .net frame workd sdk2  所有的问题顺利解决

**Comment by afc163** [comment]
:yum:

**Comment by note520** [comment]
chrome51 下 选择日期后 显示 Fri Apr 22 2016 12:46:57 GMT+0800 (ä¸­å½æ åæ¶é´) 的乱码
firefox下正常
