### ISSUE TITLE
Layout 布局BUG

### ISSUE THREAD

**Issue by zhangzhenfei** [ant-design/ant-design#4630]
- antd version: 2.6.3
- OS and its version:
- Browser and its version:

.anticon {
    display: inline-block;
    font-style: normal;
    vertical-align: baseline;
    text-align: center;
    text-transform: none;
    line-height: 1;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

line-height: 1; 这个属性导致在collapsed的时候，图标在容器的上方了，请去掉这个属性

**Comment by afc163** [comment]
It is working in demo page: https://ant.design/components/layout/

Please provide a reproducible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by ddcat1115** [comment]
Can't reproduce either, please reopen this issue if a reproducible demo is provided.
