### ISSUE TITLE
An error occurs when the fieldNames attribute is set in the Tree component and the treeData type is used.

### ISSUE THREAD

**Issue by joker77877** [ant-design/ant-design#46302]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/shou-kong-cao-zuo-shi-li-antd-5-11-1-forked-v4gqxv?file=%2Fdemo.tsx%3A69%2C30)

### Steps to reproduce

An error occurs when the fieldNames attribute is set in the Tree component and the treeData type is used.

### What is expected?

Setting the fieldNames attribute in the Tree component to the treeData type does not report an error

### What is actually happening?

An error occurs when the fieldNames attribute is set in the Tree component and the treeData type is used.

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18 |
| System | macOS13.6 |
| Browser | chrome |

**Comment by afc163** [comment]
What error?

**Comment by joker77877** [comment]
> What error?

Type '{ label: string; value: string; children: { label: string; value: string; }[]; }[]' is not assignable to type '(BasicDataNode | DataNode)[]'.

**Comment by zombieJ** [comment]
You should define TreeNode type:

```tsx
import type { BasicDataNode } from "antd/es/tree";

// Map with `fieldNames`
interface MyTreeNode extends BasicDataNode {
  label?: React.ReactNode;
  value?: string;
  children?: MyTreeNode[];
}

<Tree<MyTreeNode>
  fieldNames={{
    title: "label",
    key: "value",
    children: "children",
  }}
  ...
/>
```

**Comment by crazyair** [comment]
```tsx
import type { BasicDataNode } from "antd/es/tree";

// Map with `fieldNames`
interface MyTreeNode extends BasicDataNode {
  label?: React.ReactNode;
  value?: string;
  children?: MyTreeNode[];
}

const treeData: MyTreeNode[] = [];

<Tree
  fieldNames={{
    title: "label",
    key: "value",
    children: "children",
  }}
 treeData={treeData}
  ...
/>
```
