### ISSUE TITLE
Checkbox边框宽度不为1的时候，选中状态对勾会偏移

### ISSUE THREAD

**Issue by jkiss** [ant-design/ant-design#46307]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/elegant-keller-m5zl6c?file=%2Fsrc%2FApp.js%3A26%2C28)

### Steps to reproduce

打开demo链接就能看到效果

### What is expected?

Checkbox选中后，对勾是居中显示的

### What is actually happening?

Checkbox选中后，对勾是偏右显示的

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | ^18 |
| System | MacOS 14.1.1 |
| Browser | Google Chrome 119.0.6045.199 |

**Comment by MadCcc** [comment]
改了边框宽度之后内容区域明显不够放了，可以自行调整一下 size。

**Comment by jkiss** [comment]
..................................................................................................................

**Comment by afc163** [comment]
@jkiss 你期望的效果是什么？

**Comment by jkiss** [comment]
![image](https://github.com/ant-design/ant-design/assets/3231326/f1a08937-a551-4473-940d-a1441a323cb5)

我期望这个白色的对勾能够上下左右居中😢 @afc163

**Comment by jkiss** [comment]
![image](https://github.com/ant-design/ant-design/assets/3231326/188e87a3-1197-46e2-9dff-a274f7660b35)

默认就这么展现就行，我这是为了复现这个问题，实际项目是2px

**Comment by jkiss** [comment]
![image](https://github.com/ant-design/ant-design/assets/3231326/5060e159-2312-4a79-9692-ca5f9a1a7c62)
![image](https://github.com/ant-design/ant-design/assets/3231326/5922efb9-071e-441e-9e05-81902e2dee61)
