### ISSUE TITLE
Select使用了dropdownRender后，里面的dom不能响应enter键？

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#46319]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/yin-cang-yi-xuan-ze-xuan-xiang-antd-4-24-12-forked-zdjdys?file=%2Fdemo.tsx%3A26%2C27)

### Steps to reproduce

-

### What is expected?

能响应或者给出原因

### What is actually happening?

textarea可以换行

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | react |
| System | macos |
| Browser | chrome最新 |

---
-

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/20625#issuecomment-576139186
