### ISSUE TITLE
Slow Performance of Table with turned on horizontal scroll 

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#4631]
Browser vertical scroll starts to lag when Table has about 20 columns and 50 rows, 2 fixed columns at right. When turn off horizontal scroll it stops lagging, could you please advice something?

**Comment by benjycui** [comment]
@yesmeck I am not sure if we can use `throttle` to wrap [`handleBodyScroll`](https://github.com/react-component/table/blob/master/src/Table.jsx#L624)

**Comment by afc163** [comment]
same as #4631, trace that.

**Comment by vorlov** [comment]
@afc163 just looked at it, everything is on Chinese. Can't understand is it fixed or not :)

**Comment by yesmeck** [comment]
Hello @vorlov , are you encountering this issue on IE?

**Comment by vorlov** [comment]
@yesmeck Hi, no lag in IE, also scroll fixed in chrome, but there is a lag with unsynchronized movement of body and header now on horizontal scroll

**Comment by yesmeck** [comment]
@vorlov Could you try 2.7.0 to see if the problem still exists?

**Comment by vorlov** [comment]
@yesmeck https://ant.design/components/table/#components-table-demo-fixed-columns-header you can see it here if you scroll fast from side to side

**Comment by yesmeck** [comment]
@vorlov A new version of `rc-table` has released, try reinstall node_modules.

**Comment by vorlov** [comment]
@yesmeck reinstalled, problem still exists

**Comment by yesmeck** [comment]
@vorlov performance improving is a long term goal, could you help us finding the bottleneck of this problem?

**Comment by vorlov** [comment]
@yesmeck I will try)

**Comment by yesmeck** [comment]
Close this since no more actions can be token.
