### ISSUE TITLE
Upload插件在Tauri2中拖拽时，OnDrop事件不触发

### ISSUE THREAD

**Issue by poohlaha** [ant-design/ant-design#46318]
### Reproduction link

[https://ant.design/components/upload-cn](https://ant.design/components/upload-cn)

### Steps to reproduce

1. 在chrome浏览器测试拖拽是 `ok` 的
2. 运行 `tauri2`, 打开桌面版应用程序, 打开控制台，拖拽文件到 `Upload 框`，`onDrop`事件 `不触发`

### What is expected?

在桌面应用程序中可以实现文件拖拽，触发 `onDrop` 事件

### What is actually happening?

onDrop事件不触发

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.2.0 |
| System | macos |
| Browser | Tauri2浏览器(appCodeName: Mozilla, appName: Netscape, appVersion: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)) |

浏览器:
![image](https://github.com/ant-design/ant-design/assets/10954901/76545932-807a-41dc-9ce5-08a9d8d7e311)

tauri
<img width="1424" alt="image" src="https://github.com/ant-design/ant-design/assets/10954901/40a103ef-2611-4fe8-8565-c1742c697360">

**Comment by poohlaha** [comment]
已改成 tauri 拖拽

**Comment by ZhahaSy** [comment]
怎么解决的

**Comment by zibo-chen** [comment]
可以将窗口的fileDropEnabled设置为false,不然会和tauri原生的拖拽冲突 @afc163 @ZhahaSy

**Comment by mozhu811** [comment]
> 可以将窗口的fileDropEnabled设置为false,不然会和tauri原生的拖拽冲突 [@afc163](https://github.com/afc163) [@ZhahaSy](https://github.com/ZhahaSy)

perfect

**Comment by yarin-zhang** [comment]
> 可以将窗口的fileDropEnabled设置为false,不然会和tauri原生的拖拽冲突 [@afc163](https://github.com/afc163) [@ZhahaSy](https://github.com/ZhahaSy)

补充一个信息，在 Tauri 2 下，fileDropEnabled 已改名，需改为 dragDropEnabled 。

```
// src-tauri/tauri.conf.json
{
  "app": {
    "windows": [
      {
        "label": "main",
        "title": "My App",
        "width": 800,
        "height": 600,
        "dragDropEnabled": false
      }
    ]
  }
}

```
