### ISSUE TITLE
Date Range Picker is not rendering correct calendar on Preset Range clicked.

### ISSUE THREAD

**Issue by ceghap** [ant-design/ant-design#46329]
### Reproduction link

[https://ant.design/~demos/components-date-picker-demo-preset-ranges](https://ant.design/~demos/components-date-picker-demo-preset-ranges)

### Steps to reproduce

let say today date is 8/12/2023

1. click date range picker.
2. date range picker open. 
3. navigate to Jan 2023 on the calendar. this will show preset range date and also a calendar Jan 2023 and Feb 2023. 
4. then clicked to preset range date, 'Last 7 Days'
5. it is selecting 2023-12-01 - 2023-12-08 which is good. 
6. click again the date range picker to open it
7. see that the calendar is not showing selected 2023-12-01 - 2023-12-08 but it is still showing Jan 2023 and Feb 2023 calendar where we are at earlier

### What is expected?

opening the date rang picker again should render it selected date range in the calandar which is  2023-12-01 - 2023-12-08 (December)

### What is actually happening?

it is rendering previously navigated calendar

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 121.0.6167.8 |

**Comment by CYBYOB** [comment]
Follow the steps above for a successful repeat

**Comment by zombieJ** [comment]
Close since fixed in `5.14.0`.
