### ISSUE TITLE
在Chrome 53下，DatePicker点开后无法通过点击其他地方进行关闭

### ISSUE THREAD

**Issue by willflier** [ant-design/ant-design#4632]
#### Environment(required)

- antd version: 2.6.3
- OS and its version: Win10
- Browser and its version: Chrome  53.0.2785.116 m

#### What did you do? Please provide steps to re-produce your problem.

官网例子可复现，https://ant.design/components/date-picker-cn/

#### What do you expected?

点击其他区域应当关闭选择器

#### What happen?

console有报错
index.js:679 Uncaught Invariant Violation: Minified React error #44; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=44 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

![qq 20170118020211](https://cloud.githubusercontent.com/assets/11646558/22033397/4fa7ecba-dd23-11e6-969a-3755b149b662.jpg)

**Comment by willflier** [comment]
TimePicker也有同样的问题，第一次进入的时候会报错，刷新页面后正常

**Comment by benjycui** [comment]
ref: https://facebook.github.io/react/docs/error-decoder.html?invariant=44

**Comment by benjycui** [comment]
感觉是 `rc-trigger` 的问题，你可以再试试 `Popconfirm` `Popover` 之类。

**Comment by benjycui** [comment]
> 第一次进入的时候会报错，刷新页面后正常

另外确认一下报错时网络资源是否都加载了。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
抱歉，我们无法重现，希望给出重现例子后再 reopen，感谢理解~
