### ISSUE TITLE
`FloatButton` 最新版本 (5.12.1) 依然报console warning

### ISSUE THREAD

**Issue by Jeremy-Hibiki** [ant-design/ant-design#46326]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/strictmode-floatbutton-backtop-error-dkkqtp)

### Steps to reproduce

```tsx
<React.StrictMode>
  <FloatButton.BackTop visibilityHeight={0} />
</React.StrictMode>
```

### What is expected?

无报错

### What is actually happening?

> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.x |
| System | Windows 11 |
| Browser | Chrome 120.0.6099.71 |

---

相关：
#45387
#45390

**Comment by CYBYOB** [comment]
确实还有问题，本人尝试修复中~

**Comment by Jeremy-Hibiki** [comment]
还发现测试用例并没有检测到 `console.error` 被调用了

https://github.com/ant-design/ant-design/blob/95b959cfd460063105ca9572e2cd40c42cfa3835/components/float-button/__tests__/back-top.test.tsx#L57-L62

改成如此可以被 `jest` 检测到 :thinking:

```diff
- it('no error when BackTop work', () => {
+ it('no error when BackTop work', async () => {
    const errSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
-   render(<BackTop visibilityHeight={0} />); 
+   await act(async () => {
+     const { container } = render(<BackTop visibilityHeight={0} />);
+     fireEvent.click(container.querySelector<HTMLButtonElement>('.ant-float-btn')!);
+   });
    expect(errSpy).not.toHaveBeenCalled();
    errSpy.mockRestore();
  });
```

```tsx
  it('no error when BackTop work', async () => {
    const errSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
    await act(async () => {
      const { container } = render(<BackTop visibilityHeight={0} />);
      fireEvent.click(container.querySelector<HTMLButtonElement>('.ant-float-btn')!);
    });
    expect(errSpy).not.toHaveBeenCalled();
    errSpy.mockRestore();
  });
```

**Comment by yoyo837** [comment]
> 还发现测试用例并没有检测到 `console.error` 被调用了
> 
> https://github.com/ant-design/ant-design/blob/95b959cfd460063105ca9572e2cd40c42cfa3835/components/float-button/__tests__/back-top.test.tsx#L57-L62
> 
> 改成如此可以被 `jest` 检测到 🤔
> 
> ```diff
> - it('no error when BackTop work', () => {
> + it('no error when BackTop work', async () => {
>     const errSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
> -   render(<BackTop visibilityHeight={0} />); 
> +   await act(async () => {
> +     const { container } = render(<BackTop visibilityHeight={0} />);
> +     fireEvent.click(container.querySelector<HTMLButtonElement>('.ant-float-btn')!);
> +   });
>     expect(errSpy).not.toHaveBeenCalled();
>     errSpy.mockRestore();
>   });
> ```
> 
> ```tsx
>   it('no error when BackTop work', async () => {
>     const errSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
>     await act(async () => {
>       const { container } = render(<BackTop visibilityHeight={0} />);
>       fireEvent.click(container.querySelector<HTMLButtonElement>('.ant-float-btn')!);
>     });
>     expect(errSpy).not.toHaveBeenCalled();
>     errSpy.mockRestore();
>   });
> ```

来个PR？

**Comment by Jeremy-Hibiki** [comment]
> 来个PR？

前面没仔细看，这个能fail的原因是fireEvent.click没拿到DOM抛异常了

正确的 能fail用例的 PR 了

#46356

1. waitFakeTimer
2. 提到第一个用例前

在第一个用例后执行就mock失败 然后PASS，这个超出我能力范围了 :cry:

**Comment by afc163** [comment]
@CYBYOB 还在修么？

**Comment by nerdess** [comment]
Any news regarding this one?

I also get the same error when I wrap a Radio.Button with a Tooltip on latest antd (v5.11.5)

```
<Radio.Group>
  <Tooltip title='This activates Yes'>
	  <Radio.Button value='1'>
		  Yes
	  </Radio.Button>
  </Tooltip>
  <Tooltip title='This activates No'>
	  <Radio.Button value='0'>
		  No
	  </Radio.Button>
  </Tooltip>
</Radio.Group>
```
<img width="694" alt="Bildschirmfoto 2024-01-12 um 14 06 12" src="https://github.com/react-component/motion/assets/711925/d19d4b43-ec15-4807-a75c-feec4f2f3e76">

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/48709
