### ISSUE TITLE
使用genComponentStyleHook创建的样式，修改样式时更新异常

### ISSUE THREAD

**Issue by lins403** [ant-design/ant-design#46322]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/an-niu-lei-xing-antd-5-12-1-forked-rl2f8x?file=%2Fdemo.style.ts%3A7%2C25)

### Steps to reproduce

使用`genComponentStyleHook`方法来解析我的业务样式，然后修改demo.style.ts的样式：

1. 24px → 14px

2. 14px → 4px

3. 4px → 24px

### What is expected?

修改样式以后能够正常更新style，并移除旧的style

### What is actually happening?

样式不能正常更新，并且旧的style没有被移除：
![https://codesandbox.io/p/sandbox/an-niu-lei-xing-antd-5-12-1-forked-rl2f8x?file=snap.png](https://codesandbox.io/p/sandbox/an-niu-lei-xing-antd-5-12-1-forked-rl2f8x?file=snap.png)

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18 |
| System | mac |
| Browser | 119 |

---
希望有关于业务项目接入antd5新主题系统的方案参考

**Comment by zombieJ** [comment]
不要使用 antd 内部方法，内部方法不会保证在版本迭代中会发生变化。antd 使用的 cssinjs 库是只为组件研发使用，不具备应用 cssinjs 库的灵活性。推荐使用应用级的 cssinjs 库。

参考：[Blog: 组件级别的 CSS-in-JS](https://ant-design.antgroup.com/docs/blog/css-in-js-cn)

另外，你的例子中 Button 的 Block 样式是生效的，只是它的高度没改： https://codesandbox.io/p/sandbox/an-niu-lei-xing-antd-5-12-1-forked-ctl82z?file=%2Fdemo.style.ts%3A8%2C9-8%2C24
