### ISSUE TITLE
export 'useId' (imported as 'useId') was not found in 'react'  WARNING in ./node_modules/antd/es/config-provider/hooks/useThemeKey.js 3:27-32

### ISSUE THREAD

**Issue by belozerov-egor** [ant-design/ant-design#46334]
### Reproduction link

[https://---](https://---)

### Steps to reproduce

export 'useId' (imported as 'useId') was not found in 'react'  WARNING in ./node_modules/antd/es/config-provider/hooks/useThemeKey.js 3:27-32

### What is expected?

Hello, we use React 17 and this problem still persists. The project is written in JS, not TS

### What is actually happening?

app dont start

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 17 |
| System | win11 |
| Browser | Chrome |

---
-

**Comment by KelvinDigit** [comment]
> Will be released in 5.12.2

Please will like to ask when is the release date for the version 5.12.2

**Comment by yoyo837** [comment]
I think this will happen next Monday.
