### ISSUE TITLE
Show code - Feature

### ISSUE THREAD

**Issue by FacundoGFlores** [ant-design/ant-design#4633]
I was searching to something similar to the show code button.

![image](https://cloud.githubusercontent.com/assets/5167196/22038886/9468f0bc-dcdb-11e6-8b8a-bb83a6ae8a01.png)

it is like the collapse component, but quite different behaviour, are you planning to include it, it would be great! Or maybe I am missing something inside the collapse component, is it possible to customize it? I mean changing the button position, icon, or style?

The following images illustrates it:

![image](https://cloud.githubusercontent.com/assets/5167196/22039047/6d6f5ec8-dcdc-11e6-8024-dac223104cd0.png)

![image](https://cloud.githubusercontent.com/assets/5167196/22039072/88167ba8-dcdc-11e6-8148-f4478fe37c86.png)

**Comment by benjycui** [comment]
You requirement is easy to implement with [Card](https://ant.design/components/card/#components-card-demo-basic).

**Comment by afc163** [comment]
You can customize the style of Collaspe: http://ant.design/components/collapse
