### ISSUE TITLE
select组件当类型为多选且包含初始值时，搜索值后点击回车键两次，原先初始值第一项消失

### ISSUE THREAD

**Issue by nulidexiaofan** [ant-design/ant-design#46336]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jlr2gp)

### Steps to reproduce

select组件当类型为多选且包含初始值时，搜索值后点击回车键两次，原先初始值第一项消失

![antd-select](https://github.com/ant-design/ant-design/assets/69844434/08b325c0-bf96-4b91-a824-71b6b47a1ca3)

### What is expected?

取消选中的应是第一次回车选中的选项

### What is actually happening?

取消选中的是初始默认的第一项

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18 |
| System | win11 |
| Browser | chrome 119.0.6045.200 |

---
此问题出自官方文档的示例中

**Comment by zombieJ** [comment]
第一次回车添加你的输入值，这时 Select 下拉列表恢复为原始列表。此时选项为第一个 `a10`，第二次回车撤销 `a10`。
这是符合预期的。
