### ISSUE TITLE
Build failed due to isClientSide Import

### ISSUE THREAD

**Issue by niish03** [ant-design/ant-design#46349]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

Build using vite and react.

npm run build
build faild due to RollupError: "isClientSide" is not exported by "node_modules/@ant-design/cssinjs/es/util.js", imported by "node_modules/@ant-design/cssinjs/es/hooks/useStyleRegister.js".

### What is expected?

It should build

### What is actually happening?

Building Failed

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.2.0 |
| System | MacOs - m1 |
| Browser | Chrome |

---
"dependencies": {
    "@ant-design/icons": "^5.2.6",
    "@ant-design/pro-layout": "^7.17.12",
    "@rollup/plugin-dynamic-import-vars": "^2.1.0",
    "@vitejs/plugin-react": "^4.0.4",
    "antd": "^5.11.0",
    "axios": "^1.6.0",
    "cross-env": "7.0.3",
    "currency.js": "2.0.4",
    "just-compare": "^2.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-quill": "^2.0.0",
    "react-redux": "^8.1.3",
    "react-router-dom": "^6.17.0",
    "redux": "^4.2.1",
    "redux-thunk": "^2.4.2",
    "reselect": "^4.1.8",
    "shortid": "^2.2.16",
    "vite": "^4.5.0"
  },

Depedecies I use

**Comment by yoyo837** [comment]
Can not to reproduce it.
