### ISSUE TITLE
Tabs,type="card"使用样式和2.6.3版本不同

### ISSUE THREAD

**Issue by Thlq** [ant-design/ant-design#4634]
Tabs,type="card"使用样式和2.6.3版本不同

**Comment by Thlq** [comment]
![1](https://cloud.githubusercontent.com/assets/21211777/22048330/3208389c-dd67-11e6-9972-0b8f926e9f69.jpg)这个是官网上的,
![2](https://cloud.githubusercontent.com/assets/21211777/22048339/4294360c-dd67-11e6-9740-7a072d8f8fa5.jpg)这个是我写的

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
给了重现再 reopen 吧。
