### ISSUE TITLE
Form: 可编辑表格中name为key的单元格编辑时会失焦

### ISSUE THREAD

**Issue by mianmabb1** [ant-design/ant-design#46340]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/biao-dan-fang-fa-diao-yong-antd-5-12-1-forked-5dzw3g?file=%2Fdemo.tsx%3A39%2C14)

### Steps to reproduce

1. 表格添加一行
2. 编辑字段【key】

### What is expected?

输入框正常输入

### What is actually happening?

编辑字段【key】时，会自动失去焦点，其他 name 字段输入正常

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.0.0 |
| System | * |
| Browser | * |

**Comment by zombieJ** [comment]
https://codesandbox.io/p/sandbox/biao-dan-fang-fa-diao-yong-antd-5-12-1-forked-6zp734?file=%2Fdemo.tsx%3A43%2C11

你把 `key` 作为字段，相当于 `dataSource` 里每个 obj 都有个 `key`，所以当 `key` 变化时会让 Table Row 重新渲染。
