### ISSUE TITLE
使用Tabel表格当columns有数据,dataSource没有数据时,出现如下Bug

### ISSUE THREAD

**Issue by Thlq** [ant-design/ant-design#4635]
在最新版本2.6.3中使用Tabel中的表头分组时,当columns有数据,dataSource没有数据时,出现如下状况:
![1](https://cloud.githubusercontent.com/assets/21211777/22049639/9d4810d4-dd6f-11e6-8210-badbaf38dd97.jpg)

**Comment by yesmeck** [comment]
Where's your 🐛 ?

**Comment by Thlq** [comment]
有人帮忙解答一下吗

**Comment by Thlq** [comment]
@yesmeck 现在问题描述好了
