### ISSUE TITLE
[Descriptions] support more html attributes like `id`

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#46350]
### What problem does this feature solve?

https://github.com/ant-design/ant-design/pull/42676
support more html attributes，

### What does the proposed API look like?

 like `id` attributes.

![image](https://github.com/ant-design/ant-design/assets/81673017/912a11a2-4f1c-484f-9504-1dd16c3d1ac3)

**Comment by li-jia-nan** [comment]
来个pr

**Comment by RSS1102** [comment]
> 来个pr

ok, wait me

**Comment by li-jia-nan** [comment]
我看了一下，其实 `id` 已经透传进去了，只是 ts 类型没有暴露出去，只需要更新 interface 就行
