### ISSUE TITLE
自定义颜色主题 菜单部分 黑白色调 二级菜单选中后 一级菜单也变成了白色 导致观感上消失

### ISSUE THREAD

**Issue by yaoyaochil** [ant-design/ant-design#46354]
### Reproduction link

[https://ant.design/theme-editor-cn?theme=happy-work](https://ant.design/theme-editor-cn?theme=happy-work)

### Steps to reproduce

itemActiveBg:#000
itemSelectedBg:#000
itemSelectedColor:#fff

### What is expected?

一级菜单选中的颜色需要独立出来

### What is actually happening?

一级菜单的颜色受二级菜单选中影响 且没有独立颜色 会导致二级选中后 一级菜单也变颜色 如果是白色背景 二级菜单背景颜色是黑色 文字为白色 一级菜单因为共用的token 也会变颜色 观感上一级菜单直接消失了

<img width="1683" alt="image" src="https://github.com/ant-design/ant-design/assets/49603204/c16213c9-2ed6-428f-8aea-7c1e8226eb4a">
<img width="1705" alt="image" src="https://github.com/ant-design/ant-design/assets/49603204/a906138e-7eab-4873-bf10-77d5f21050d8">

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.2 |
| System | Macos 14.1.1 |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/45488

**Comment by yaoyaochil** [comment]
> Duplicate of #45488

我是在非暗色模式操作的 如果使用暗色 所有的全部要重新设计

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/52182
