### ISSUE TITLE
windows版本chrome中table固定表头scroll样式问题

### ISSUE THREAD

**Issue by Catlite91** [ant-design/ant-design#4637]
windows版本chrome中table固定表头scroll样式问题

官网链接：
https://ant.design/components/table-cn/#components-table-demo-fixed-header

![image](https://cloud.githubusercontent.com/assets/9129944/22052512/98a0cfce-dd85-11e6-8290-7be54bd9fa79.png)

![image](https://cloud.githubusercontent.com/assets/9129944/22052515/9b05d6ba-dd85-11e6-927e-1626b6bc43cb.png)

**Comment by afc163** [comment]
1. 这个 scrollbar 是有用的，避免某些情况下列头和列不对齐的情况。
2. 这个 scrollbar 确实不好看，我用一些样式把它隐藏掉。

**Comment by hirohe** [comment]
设置了margin-right: -18px来隐藏scrollbar的话，Table组件如果是bordered就看得出来表头与内容不对齐
而且最后一列的表头右边框没有显示出来
columns.width设置为百分比的更明显
![](http://wx2.sinaimg.cn/mw690/97772645ly1fbz78x6vzej208v02va9w.jpg)
[codepen](http://codepen.io/anon/pen/ZLKKJv)


按照[这里的方法](http://stackoverflow.com/questions/16670931/hide-scroll-bar-but-still-being-able-to-scroll)设置 padding-right倒是没有问题

**Comment by afc163** [comment]
感谢反馈~ 😅

**Comment by afc163** [comment]
换了三种方法搞这个问题...

**Comment by nekronhuang** [comment]
终于在这里找到了答案。。。

npm安装的2.7.1版本是使用的 https://github.com/ant-design/ant-design/commit/fb421f10e079dd8b9db3fbffcc2ca2351f5e3b28 方案，但是仓库里npm run dist出来的css里没有**scroll:after的样式

查了好久。。。原来是被回滚了

**Comment by afc163** [comment]
换了三种方法还是有问题，最终还是放弃了。

**Comment by afc163** [comment]
不再尝试修复这个问题。

**Comment by uinz** [comment]
antd 2.7.2 版本

windows 下 ant-table-header 会有 `margin-bttom: -17px;` 的样式


## mac 下正常
![image](https://cloud.githubusercontent.com/assets/12208108/23196591/8958c39c-f8f5-11e6-80ee-a3d3372d7442.png)

![image](https://cloud.githubusercontent.com/assets/12208108/23196555/4e1cf118-f8f5-11e6-8564-941ffa211af7.png)

---

## windows 下样式问题:
![image](https://cloud.githubusercontent.com/assets/12208108/23196609/a4d2c712-f8f5-11e6-9a64-022548ae07fb.png)

![image](https://cloud.githubusercontent.com/assets/12208108/23196584/7a8fb776-f8f5-11e6-8bcd-4d716a5dc517.png)

**Comment by afc163** [comment]
@uinz 2.7.2 should have style like below:

<img width="271" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23196909/96de5e76-f8f7-11e6-96a3-b94a54cfa434.png">

**Comment by uinz** [comment]
@afc163 

I use jsx style API
```jsx
const { Column} = Table;

<Table
    rowKey='id'
    pagination={false}
    dataSource={this.props.upstreams}
    scroll={{y: 'calc(100vh - 55px)'}}
>
    <Column
        title='账号'
        dataIndex='account'
        key='account'
    />
</Table>
```

DOM tree:
![image](https://cloud.githubusercontent.com/assets/12208108/23197513/c8af1a0e-f8fb-11e6-9fa7-661ef4c7d912.png)

**Comment by uinz** [comment]
@afc163 
在 codepen 里

两个表现也不一致, 

![image](https://cloud.githubusercontent.com/assets/12208108/23198105/0b95742c-f900-11e6-99b0-847df7811f2b.png)

**Comment by afc163** [comment]
上面的问题在 https://github.com/ant-design/ant-design/commit/86981114a7a594dae883b11a090c3eddc14942b4 里修复了。

**Comment by uinz** [comment]
@afc163 所以windos 下的 -margin 是用来遮盖 scroll bar 的?

**Comment by lileilei** [comment]
可以参考 jquery mini  的 table做法，当数据不超过的时候是不需要显示滚动条的，当数据超过高度表头和内容框都需要显示滚动条。最好能让设置table高度，就撑满屏幕了table

**Comment by Angelki** [comment]
html {
  -ms-overflow-style: none;
  overflow: -moz-scrollbars-none;
}
::-webkit-scrollbar {
  display: none;
}

**Comment by vii120** [comment]
It works for me:
```
.ant-table-scroll .ant-table-header::-webkit-scrollbar {
    opacity: 0.001;
}
```

**Comment by afc163** [comment]
经过艰辛的探索，终于找到了解决方案：

- https://github.com/react-component/table/pull/333
- https://github.com/ant-design/ant-design/pull/16950
