### ISSUE TITLE
如何关闭tooltip的显隐动画

### ISSUE THREAD

**Issue by CaptainJon** [ant-design/ant-design#46384]
### What problem does this feature solve?

需要立即显隐，不需要transition，但是找了一圈dom，都没有找到transition在哪个dom上

### What does the proposed API look like?

可以找到动画的dom，关闭transition

**Comment by zombieJ** [comment]
[如何关闭组件动画](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E5%85%B3%E9%97%AD%E7%BB%84%E4%BB%B6%E5%8A%A8%E7%94%BB)
