### ISSUE TITLE
分页组件 simple 模式 current 受控选中分页不生效

### ISSUE THREAD

**Issue by Zt834000** [ant-design/ant-design#46383]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-9lzn92?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

import React, { useState } from "react";
import { createRoot } from "react-dom/client";

import { Pagination, Button } from "antd";

const Component = () => {
const [current, setCurrent] = useState(1);

const onChange = (page) => {
console.log(page);
setCurrent(page);
};

const pageTo = (page) => {
setCurrent(page);
};

return (
<>
<Button onClick={() => pageTo(10)}>跳转到第10页
<div style={{ margin: "30px" }}>current的值： {current}

</>
);
};

// 渲染你的 React 组件
const root = createRoot(document.getElementById("root"));
root.render();

### What is expected?

期望 分页器受控模式当前选中页 跟随current绑定值发生改变

### What is actually happening?

目前实际结果：
分页器受控模式当前选中页 未跟随current绑定值发生改变

| Environment | Info |
| --- | --- |
| antd | 5.12.0 |
| React | react |
| System | mac os  |
| Browser | chrome 119 |

**Comment by MadCcc** [comment]
Fixed in https://github.com/react-component/pagination/pull/546
删除 node_modules 和 lock 文件重新安装试试。
