### ISSUE TITLE
DatePicker: Change the value on manual input, if the format matches

### ISSUE THREAD

**Issue by alex-golubtsov** [ant-design/ant-design#46392]
### What problem does this feature solve?

When I manually type the needed date, I need to hit enter to get it applied. If the input element just loses focus, my change is gone.

### What does the proposed API look like?

No API change is required, only a change of current behavior. In the `onBlur` handler validate the input and if it matches the format, apply it instead of erasing.

**Comment by SpajicM** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/30468

**Comment by alex-golubtsov** [comment]
Thanks @SpajicM, closing this one

**Comment by alex-golubtsov** [comment]
Duplicate
