### ISSUE TITLE
antdesign为什么官方工具都是mac版本的，啥意思，操作系统歧视

### ISSUE THREAD

**Issue by finchguo666** [ant-design/ant-design#46395]
### Reproduction link

[https://ant-design.antgroup.com/docs/resources-cn](https://ant-design.antgroup.com/docs/resources-cn)

### Steps to reproduce

edge

### What is expected?

antdesign为什么官方工具都是mac版本的，啥意思，操作系统歧视

### What is actually happening?

antdesign为什么官方工具都是mac版本的，啥意思，操作系统歧视

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | widows |
| Browser | edge |

**Comment by BoyYangzai** [comment]
😂

**Comment by yoyo837** [comment]
个人觉得，设计类的工具本身Mac端更齐全，占比更大，且考虑到精力有限，有限支持。就和不支持IE一样，不是歧视。

**Comment by MadCcc** [comment]
如楼上所说，antd 的设计师主要使用 sketch 进行设计，且精力有限，其他平台的设计资源大多依赖社区力量完善，望理解。

**Comment by afc163** [comment]
官方目前没有能力支持其他操作系统。。。
