### ISSUE TITLE
Descriptions 使用 borderd 时，会有列挤压问题

### ISSUE THREAD

**Issue by Yixi** [ant-design/ant-design#46397]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-bian-kuang-de-antd-5-12-1-forked-4t8t26)

### Steps to reproduce

descriptions 分栏，使用 borderd 属性，将某个 item children 填充超长

### What is expected?

期望列宽固定，内容换行

### What is actually happening?

将其他列进行挤压

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | macos |
| Browser | Chrome Version 120.0.6099.71 |

**Comment by Yixi** [comment]
bordered 内容长度正常时
![image](https://github.com/ant-design/ant-design/assets/1411722/3cf0eac8-449d-428e-8579-9f71cdb430b8)


bordered 内容超长时的效果
![image](https://github.com/ant-design/ant-design/assets/1411722/d28d09ab-b0c3-46b0-89ba-80833ac70f90)

不待 borderd 时的超长效果
![image](https://github.com/ant-design/ant-design/assets/1411722/b58930f4-d26b-4d46-980c-4facbcb45729)

**Comment by afc163** [comment]
表格根据内容自适应在有些情况下效果更好一点：https://github.com/ant-design/ant-design/pull/46398#issuecomment-1851282908

**Comment by MadCcc** [comment]
可以加个参数是否开启 `tableLayout: auto`

**Comment by afc163** [comment]
Descriptions 不应该感知内部是否有 table 元素的。

**Comment by afc163** [comment]
@Yixi Descriptions 开启 `bordered` 模式时，目前是使用 Table 进行自动布局，具体布局属性是 `table-layout: auto;`。

这个布局在大多数情况下能比较好的适配内容，比起平均固定宽度的 `table-layout: fixed;`，具体对比效果可以看看 https://github.com/ant-design/ant-design/pull/46398#issuecomment-1851282908 因为我觉得保留默认表格布局更好一点。

对于部分内容超长导致的挤压情况，我建议在业务代码中进行限宽：https://codesandbox.io/p/sandbox/dai-bian-kuang-de-antd-5-12-1-forked-l52h84?file=%2Fdemo.tsx%3A9%2C22 或者覆盖掉 `table-layout: fixed`。
