### ISSUE TITLE
Table 能否提供拖拽事件或者开放自定义事件

### ISSUE THREAD

**Issue by lzwfly** [ant-design/ant-design#4639]
尝试使用React-Dnd与Table结合, 让Table支持拖拽, 目前能够使用的row事件太少, 感觉很难融合进去. 不知道大家有木有这样的需要.. 
      或者如果能提供一个table与React-dnd融合的dmeo也是很好的

**Comment by ligang01** [comment]
楼上说的对，现在网上资料太少希望大神提供一个简单的demo让我们学习一下。

**Comment by xutou12** [comment]
[https://motion.ant.design/exhibition/demo/table-enter-leave](https://motion.ant.design/exhibition/demo/table-enter-leave) 中有个参数可以利用 ```getBodyWrapper```

**Comment by afc163** [comment]
对行进行二次封装，可以先参考这个例子：http://react-component.github.io/table/examples/animation.html

**Comment by wufeng87** [comment]
请问getBodyWrapper接口不打算暴露到antd Table吗？

**Comment by afc163** [comment]
@wufeng87 可以用。

**Comment by yesmeck** [comment]
See these examples https://github.com/react-component/table/issues/83#issuecomment-294851402

**Comment by benjycui** [comment]
@yesmeck 把那个例子更新到 rc-table 的 demo 里面？然后这个 issue 就关了？毕竟不准备暴露到 antd 这层。

**Comment by raisezhang** [comment]
@yesmeck @benjycui  拖拽相关的方案我优化了下， 支持拖拽 Table 的 row 及 column !

Demo：
dragging rows：https://codepen.io/raisezhang/pen/MmjypX
dragging columns：https://codepen.io/raisezhang/pen/MoMoyz

HomePage：https://github.com/raisezhang/react-drag-listview

辛苦看看还有啥问题或者建议，  多谢~ 

Ref： https://github.com/react-component/table/issues/83#issuecomment-294851402

**Comment by hengkx** [comment]
请教下 树形数据的表格，可以实现拖拽吗
