### ISSUE TITLE
Scrollbar not visible in select when there are 9 or 10 options

### ISSUE THREAD

**Issue by torers-dnv** [ant-design/ant-design#46390]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-55fhd7?file=%2Findex.js)

### Steps to reproduce

Create a select with nine or ten options. Open the drop-down. Observe that only eight items are shown and that there is no scrollbar to indicate that more options are available.

### What is expected?

Scrollbar to appear when select options are scroll-able.

### What is actually happening?

Select is scroll-able, but there is no scrollbar to indicate it.

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.0 |
| System | Windows |
| Browser | Chrome |

**Comment by dimaskc** [comment]
Also happened to me

**Comment by NghiaHa-97** [comment]
Add listItemHeight={32} work for me.

**Comment by yzi-yzi** [comment]
I faced the same issue with v5.11.1 but fine for me with v5.13.1.

**Comment by so0orena** [comment]
I use ant v4 
I fix it like this:
add class name to select
 popupClassName={'visible-scroll'}
 then 
 add this to css 
 .visible-scroll {
  .rc-virtual-list-holder {
    overflow-y: scroll !important;
  }
  .rc-virtual-list-scrollbar-show {
    width: 0px !important;
  }
}
