### ISSUE TITLE
Flex 会改变字体大小

### ISSUE THREAD

**Issue by datoou** [ant-design/ant-design#46403]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/dian-xing-qia-pian-antd-5-12-2-forked-q5cp6w?file=%2Fdemo.tsx%3A6%2C20)

### Steps to reproduce

在Card的title中使用Flex

### What is expected?

字体大小不被改变

### What is actually happening?

字体大小被改变

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18 |
| System | windows 11 |
| Browser | 120.0.2210.61 |

**Comment by zombieJ** [comment]
Flex 看起来不应该做 reset。
