### ISSUE TITLE
Please allow the removal of the "X-Requested-With" header when uploading.

### ISSUE THREAD

**Issue by bowencool** [ant-design/ant-design#46402]
### What problem does this feature solve?

```
Access to XMLHttpRequest at 'https://api.imgur.com/3/upload' from origin 'http://localhost:2048' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.
```

### What does the proposed API look like?

Do not add the header of "X-Requested-With" by default.

**Comment by bowencool** [comment]
Setting it to null helps.
https://github.com/react-component/upload/blob/master/src/request.ts#L90
<img width="980" alt="image" src="https://github.com/ant-design/ant-design/assets/20217146/9c6be51c-b648-49ae-97b7-8ff1119cb40e">

**Comment by cpprookie** [comment]
> Setting it to null helps. https://github.com/react-component/upload/blob/master/src/request.ts#L90 But it still has a type issue. <img alt="image" width="980" src="https://private-user-images.githubusercontent.com/20217146/289786214-9c6be51c-b648-49ae-97b7-8ff1119cb40e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwODQ1MzcsIm5iZiI6MTczNzA4NDIzNywicGF0aCI6Ii8yMDIxNzE0Ni8yODk3ODYyMTQtOWM2YmU1MWMtYjY0OC00OWFlLTk3YjctOGZmMTExOWNiNDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDAzMjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNTA1NDViYWI1Njc2Njc3NDcwMzZjZmMwZDA1ZDBlMDViMmQ0NTg4ZTFkMWVhZTg5MjA2MzU5ODJhYzE2ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MOwQWf66T_B8kA1_Yy8YTovKu_X-ZKsA7uSL0Y1Q5pA">
Thanks for your anwser. But it still has type issue. Has to set `"X-Requested-With": null as any`.Maybe consider pass as props is better?
