### ISSUE TITLE
The Select component has an empty option by default

### ISSUE THREAD

**Issue by HappyAxin** [ant-design/ant-design#46400]
### Reproduction link

[https://ant-design.antgroup.com/components/select-cn#select-demo-multiple](https://ant-design.antgroup.com/components/select-cn#select-demo-multiple)

### Steps to reproduce

```js
const [statusList] = useState([
  {
      label: '正常营业',
      value: 0
  },
  {
      label: '暂停营业',
      value: 1
  },
  {
      label: '已查封',
      value: 2
  },
])
...
<Form>
  <FormItem label={"状态"} name="status">
    <Select
      mode={'multiple'}
      options={statusList}
      placeholder={"选择店铺状态"}
    ></Select>
  </FormItem>
</Form>
```

### What is expected?

![image](https://github.com/ant-design/ant-design/assets/46963688/44422006-4890-40eb-986f-53595a12f1eb)

### What is actually happening?

![image](https://github.com/ant-design/ant-design/assets/46963688/9dc6db8c-4708-464f-a373-4ae7d526927f)

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2 |
| System | windows |
| Browser | Chrome 119.0.6045.200（正式版本） |

**Comment by xingda** [comment]
这个问题是#46476导致的，你在用v-model:value时，需要判断null，然后改成undefined，就好了。
我觉得select团队应该修掉这个问题

**Comment by HappyAxin** [comment]
> 这个问题是#46476导致的，你在用v-model:value时，需要判断null，然后改成undefined，就好了。 我觉得select团队应该修掉这个问题

But I'm using React...😢

**Comment by yoyo837** [comment]
> 这个问题是#46476导致的，你在用v-model:value时，需要判断null，然后改成undefined，就好了。 我觉得select团队应该修掉这个问题

vue ?
