### ISSUE TITLE
Safari浏览器上，动画导致字体闪烁

### ISSUE THREAD

**Issue by BriefGuo** [ant-design/ant-design#4640]
#### Environment(required)

- antd version:2.6.1
- OS and its version:Mac OSX 10.12.2
- Browser and its version:Safari 10.0.2

#### What did you do? Please provide steps to re-produce your problem.

我发现了Menu、Spin、Table等组件，
比如Menu 的下拉、Spin的loading的过程、Table的loading过程
这些带有动画效果的组件，在Safari上
会看到，被antd内置的组件包裹过的字体，它的宽度有从细变粗的动作（也可能是透明度的变化）

但是我去看了antd的官网时，官网不会出现这种情况，让我觉得
费解，你们有必杀兼容性的某种秘密工具么

#### What do you expected?

我希望，有动画的组件，它里面的字体有动画，但是其他的、用户没有操作交互的区域，它里面的字体不会受到影响

#### Re-producible online demo

其实我看了看官方的某一个网站是这样的效果事例的，
用Safari打开[这个链接](https://motion.ant.design/language/time)可以看看

**Comment by afc163** [comment]
没有什么秘密工具，如果你本地有问题，建议自行排查一下问题所在，复现问题成功后再提个 issue。

ant-motion 的问题建议提到 http://github.com/ant-design/ant-motion 。

**Comment by jljsj33** [comment]
这个页面，在动画时文字会抖？？？明天看看。。。

**Comment by jljsj33** [comment]
不知道 safari 对 matrix 做了什么。。。。所有 matrix 的动画好像都会抖。。。。

css 动画, 加 position 和 will-change 就不会抖了。。。

```css
  position: relative;
  will-change: transform;
```

**Comment by BriefGuo** [comment]
还没时间验证一下，不好意思，明天看看。

有点想知道你按照怎么个思路排查的

发自我的 iPhone

在 2017年1月19日，上午11:39，jiang <notifications@github.com<mailto:notifications@github.com>> 写道：


不知道 safari 对 matrix 做了什么。。。。所有 matrix 的动画好像都会抖。。。。

css 动画, 加 position 和 will-change 就不会抖了。。。

  position: relative;
  will-change: transform;

―
