### ISSUE TITLE
Display the selected item by the expanded dropdown AutoComplete

### ISSUE THREAD

**Issue by goldpvlv** [ant-design/ant-design#46401]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/scrollautocomplete-d4vnlk)

### Steps to reproduce

1. Select "value" from the dropdown
2. Scroll down the dropdown
3. Close the dropdown
4. Open the dropdown

### What is expected?

After opening the dropdown, the item that is selected in the field is displayed

### What is actually happening?

The dropdown opens in an obscure place

| Environment | Info |
| --- | --- |
| antd | 4.24.9 |
| React | 18.2.0 |
| System | Win10 |
| Browser | Chrome |

---
I need to position the selected item into the visible area every time the dropdown is expanded

**Comment by zombieJ** [comment]
`value` is the same which makes it can not confirm which one you want to scroll. Pls follow React warning and fix it.

![Uploading 截屏2023-12-12 15.23.45.png…]()

**Comment by goldpvlv** [comment]
@zombieJ thank you for answer
and is it possible to set "label" instead of "value" in the input field?
