### ISSUE TITLE
cssVar 启用会导致 message 的主题定制失效

### ISSUE THREAD

**Issue by tommytroylin** [ant-design/ant-design#46411]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qy6dms?file=%2Findex.js%3A32%2C39)

### Steps to reproduce

点击两个 DEMO 按钮，分别观察消息样式。

### What is expected?

样式相同

### What is actually happening?

启用 cssVar 的消息样式出现问题。

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | macOS 14 |
| Browser | Chrome 121 |

**Comment by MadCcc** [comment]
定制的 cssvar 被内层的覆盖了
