### ISSUE TITLE
JSX element type 'DatePicker' does not have any construct or call signatures

### ISSUE THREAD

**Issue by lansefengxinzi** [ant-design/ant-design#4641]
![a59262b3-4939-4e47-b14d-018498039d25](https://cloud.githubusercontent.com/assets/12048313/22062493/ff957548-ddb4-11e6-955a-a36737c3242e.png)

**Comment by lansefengxinzi** [comment]
typeScript file use antd compents has problem

**Comment by yesmeck** [comment]
@lansefengxinzi 看你在 gitter 上问，解决了吗？

**Comment by yesmeck** [comment]
已解决

**Comment by FrankEos** [comment]
怎样解决的呢？我也碰到这个问题了，tsx里面用这个时，报相同的错误。

**Comment by FrankEos** [comment]
我这边tsconfig里面是jsx:react，如果配置成jsx:preserve其他地方就会报错
