### ISSUE TITLE
ant-design-vue@1.7.8 中table组件设置了左侧固定列，在上下滚动时，左侧固定列与右侧的表格列滚动速度不一致

### ISSUE THREAD

**Issue by BigEagleWY** [ant-design/ant-design#46425]
### Reproduction link

[https://1x.antdv.com/components/table-cn/](https://1x.antdv.com/components/table-cn/)

### Steps to reproduce

设置表格可纵向滚动，设置左侧固定列，鼠标置于表格右侧区域快速的上下滚动

### What is expected?

左侧固定列与右侧滚动同步

### What is actually happening?

左侧固定列与右侧滚动不同步

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | vue2 |
| System | windows11 |
| Browser | chrome |

**Comment by afc163** [comment]
提错地方了 👉🏻 https://github.com/vueComponent/ant-design-vue/issues

**Comment by zombieJ** [comment]
感谢反馈，antd vue 版本是社区维护的。这里不提供技术支持哈，可以到这里反馈 issue：
https://github.com/vueComponent/ant-design-vue
