### ISSUE TITLE
code转换为color-chunk错误问题

### ISSUE THREAD

**Issue by binyellow** [ant-design/ant-design#46437]
### Reproduction link

[https://ant.design/components/pagination-cn#api](https://ant.design/components/pagination-cn#api)

### Steps to reproduce

pageSizeOptions 的默认值显示错误
<img width="893" alt="image" src="https://github.com/ant-design/ant-design/assets/29519985/7df088ba-6b16-4638-8023-d88f8b4c140e">

### What is expected?

显示正确的 [10, 20, 50, 100]

### What is actually happening?

100前面带了颜色

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos 13.6 |
| Browser | 版本 120.0.6099.71（正式版本） (arm64) |

**Comment by binyellow** [comment]
@Wxh16144 大佬cc

**Comment by binyellow** [comment]
不过现在看官网还是有这个问题，是没重新构建嘛？

**Comment by Wxh16144** [comment]
> 不过现在看官网还是有这个问题，是没重新构建嘛？

是的~ 官网还没更新， 等最近的 5.12.3 发布吧
