### ISSUE TITLE
Modal  Footer 不应该激进地覆盖内部 Button 样式

### ISSUE THREAD

**Issue by tommytroylin** [ant-design/ant-design#46439]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-2jn5jy)

### Steps to reproduce

打开 code sandbox 检查弹窗 footer 中两个按钮间距

### What is expected?

 和代码一样是 16px

### What is actually happening?

16px 由 gap 实现 8px 来自

https://github.com/ant-design/ant-design/blob/12db87449be8b80c75fedd963750f98fbe418f7a/components/modal/style/index.tsx#L293

中的样式覆盖

这个写法来自于 pro-component  中的 modal form

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | macOS 14 |
| Browser | Chrome 121 |

**Comment by afc163** [comment]
为了定义方便，目前按钮间距是内置的，你可以在 footer 中写一个 Array，无须自定义 gap：https://ant.design/components/modal-cn#modal-demo-footer

**Comment by tommytroylin** [comment]
@afc163 自定义都能解决。。。可惜这个是 pro-component ModalForm 的写法。
目前什么都不干，完全默认。就会导致使用 modalForm 的按钮和用 Drawer + Form 的间距样式不一致。

我感觉这个 selector 上应该是判断直接子元素就好了，能支持 array 的 button 自动布局。
如果用户主动传递了div 包裹起来。那就应该让他自己实现 space

**Comment by afc163** [comment]
看上去是 pro-component ModalForm 的实现问题？

**Comment by afc163** [comment]
> 我感觉这个 selector 上应该是判断直接子元素就好了，能支持 array 的 button 自动布局。 如果用户主动传递了div 包裹起来。那就应该让他自己实现 space

可以试试。
