### ISSUE TITLE
Components inherit incorrect CSS vars when having nested configprovider with different prefix

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#46440]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/type-antd-5-12-2-forked-hz849q?file=%2Fdemo.tsx%3A6%2C18)

### Steps to reproduce

See Link to minimal reproduction

### What is expected?

Elements in a config provider that define a custom prefix should apply css vars related to its prefix.

### What is actually happening?

css vars are inherit from nearst config provider regardless of the prefix

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome |

**Comment by AsuraKev** [comment]
![image](https://github.com/ant-design/ant-design/assets/52765572/6ef4755b-97c3-4547-84c2-4718415d9e52)

**Comment by MadCcc** [comment]
Tokens inherit from upper ConfigProvider, your reproduction works as expected.
