### ISSUE TITLE
Menu的 icon 使用组件token调整大小会产生样式对齐问题

### ISSUE THREAD

**Issue by brightzoe** [ant-design/ant-design#46450]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-k4xsm6?file=%2Findex.js%3A46%2C25)

### Steps to reproduce

使用Menu,并使用组件token调整iconSize大小，会导致menuItem的label与子menu的label纵向对不齐。比如以上链接的 Navigation One 与 Option5 Option6 的label 不齐（下图）。

在官方提供的编辑器也可重现：https://ant-design.antgroup.com/theme-editor-cn#component-size

选择组件=>Menu组件，右侧调整iconSize的大小，调大，比如24px。

导致menuitem与submenuitem的label纵向对不齐。

### What is expected?

menu的label纵向左对齐。

### What is actually happening?

icon变大时，label无法左对齐。

当然可以调小 iconMarginInlineEnd 使 label 向左移，但这不是希望的情况。是不是调整token时，向padding计算有问题呢？

![image](https://github.com/ant-design/ant-design/assets/17716768/b573a9b1-a4c9-472a-a930-32fa091f24a7)
![image](https://github.com/ant-design/ant-design/assets/17716768/d4234dbf-0bd5-4023-9a5c-f4152d042eaa)

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18 |
| System | windows |
| Browser | edge/chrome 120 |

**Comment by MadCcc** [comment]
对齐方式其实是按照预期的，icon 也在对齐的范围内
