### ISSUE TITLE
While dragging a slider, cursor responds to other UI elements

### ISSUE THREAD

**Issue by Vern-at-Motional** [ant-design/ant-design#46464]
### Reproduction link

[https://ant.design/components/slider](https://ant.design/components/slider)

### Steps to reproduce

Go to the Ant Design Slider component documentation page. Click and drag a slider. While still dragging, move the cursor over a text Input field. Observe that the cursor changes to show the text input cursor.

Now (while still dragging the slider) hover oveer a button with a tooltip. Observe that the tooltip appears.

UI elements other than the slider should not 'react' to the mouse cursor when it's moved over them if the slider is actively being dragged. Native HTML behaves as expected, but Ant Design does not. 

### What is expected?

HTML elements other than the currently-active element should not respond to mouse-over until the mouse button is released such that the current element is no longer being actively interacted with.

### What is actually happening?

While the slider is still being dragged, other UI elements still respond to mouse-over.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | OS X 13.6.2 |
| Browser | Chrome  119.0.6045.199 |

**Comment by afc163** [comment]
Is there any suggestion about how to implement this feature?

**Comment by afc163** [comment]
I afraid that there is no available way to fix this issue.
