### ISSUE TITLE
Add Danger props to Tabs

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#46461]
### Reproduction link

[https://ibb.co/zRdHwbM](https://ibb.co/zRdHwbM)

### Steps to reproduce

https://ibb.co/zRdHwbM

### What is expected?

Would be fine to have a danger props as per menu items

### What is actually happening?

not present

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by vitalijalbu** [comment]
![Screenshot 2023-12-14 alle 13 51 30](https://github.com/ant-design/ant-design/assets/40239902/02772368-97da-42d9-b2f5-c36e98eb681f)

**Comment by afc163** [comment]
You could add warning icon as you needed.

**Comment by vitalijalbu** [comment]
> You could add warning icon as you needed.

Icon ok , bur red color??? Like menu items has danger props, would be great to have it also on tans

**Comment by afc163** [comment]
See https://codesandbox.io/p/sandbox/ji-ben-antd-5-12-2-forked-dr85vj?file=%2Fdemo.tsx%3A14%2C25
