### ISSUE TITLE
【Table】虚拟列表支持表格头拖拽设置宽度

### ISSUE THREAD

**Issue by Barrior** [ant-design/ant-design#46465]
### What problem does this feature solve?

虚拟列表模式下，表格头支持拖拽设置 column 列宽度

### What does the proposed API look like?

与现有保持一致 https://ant.design/components/table-cn#components-table-demo-resizable-column

**Comment by yoyo837** [comment]
你现在不能吗？ ref: https://github.com/react-component/table/pull/1036

**Comment by Barrior** [comment]
> 你现在不能吗？ ref: [react-component/table#1036](https://github.com/react-component/table/pull/1036)

是的，自定义的手柄没有被渲染，示例代码如下

```tsx
  <th
    {...restProps}
    onClick={(...args) => {
      // 拖拽设置宽度时，防止排序事件触发
      if (!isHandleMoving) {
        onClick?.(...args)
      }
    }}
    children={
      <>
        {children}
        <span
          // 手柄
          className="table-resizable-handle"
          onMouseDown={onResizeStart}
        />
      </>
    }
  />
```

**Comment by yoyo837** [comment]
上复现吧

**Comment by Barrior** [comment]
> 你现在不能吗？ ref: [react-component/table#1036](https://github.com/react-component/table/pull/1036)

不好意思，没仔细看日期，升级到最新版可以了，是修复了的 👍👍👍
