### ISSUE TITLE
Component 'Select' should treat null as undefined like other components in ant design to keep ant design's consistency

### ISSUE THREAD

**Issue by xingda** [ant-design/ant-design#46476]
### What problem does this feature solve?

现在select控件把null和undefined区别对待，这和整体的ant design设计理念不一致，和其他的ant design 控件的行为不一致。

我觉得这个话题有必要重新讨论一下，其实很简单，ant design应该至少保持内部的设计理念的统一。
如果其他控件像input等，null值可以显示placeholder，认为是等同于undefined，那么select控件应该和整体设计理念保持一致。
否则ant design自己就违反了设计一致性的原则，让使用者有错误的预期。

这里更奇怪的现象就是，multiple模式时，如果是null的时候，会显示一个空的东西在那里。

I think this topic need to be discussed more. and simply say, ant design should keep the design theory or principle consistent inside or all over components.
if other components like input see null as undefined, and show placehodler when the value is null, select should be same.
otherwise, users may got unexpected result when using different component in ant design, that is a bad design behavior.

### What does the proposed API look like?

null should be treated same as other components in ant design, it is undefined

**Comment by xingda** [comment]
这是原来那个被关闭的issue：https://github.com/ant-design/ant-design/issues/2367

**Comment by zombieJ** [comment]
`null` 不同于 `undefined`，一个是受控且空值，一个是非受控。Select 多选 `null` 出现空对象应该是 `Array.isArray(value) ? value : [value]` 没考虑 `null` 情况导致的 bug。

Ref: [FAQ: `undefined` 和 `null` 在 antd 的受控组件中有区别吗？](https://ant-design.antgroup.com/docs/react/faq-cn#undefined-%E5%92%8C-null-%E5%9C%A8-antd-%E7%9A%84%E5%8F%97%E6%8E%A7%E7%BB%84%E4%BB%B6%E4%B8%AD%E6%9C%89%E5%8C%BA%E5%88%AB%E5%90%97)

**Comment by zombieJ** [comment]
Select multiple bug:
https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-1-forked-82w39s?file=%2Fdemo.tsx%3A38%2C14-38%2C18

**Comment by xingda** [comment]
问题是ant design控件之间行为都不统一，这给使用者造成不可预期的结果，请至少统一控件之间的行为。单独控件应该符合整体设计范式，大家都知道null是不同于undefined，但怎么处理null，他的行为应该在ant design内统一，而不是纠结于null不同于undefined

**Comment by xingda** [comment]
> Select multiple bug: https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-1-forked-82w39s?file=%2Fdemo.tsx%3A38%2C14-38%2C18

请问这个bug什么时候，或者说哪个版本会修复？
