### ISSUE TITLE
期望SELECT组件可以全选复制 选中的内容  单选的情况下 多选如果能实现最好！

### ISSUE THREAD

**Issue by day-xue** [ant-design/ant-design#46474]
### What problem does this feature solve?

可以复制选中的内容

### What does the proposed API look like?

无api 默认支持

**Comment by Wxh16144** [comment]
个人感觉这个需求太偏业务了，组件库应该不会考虑支持。可以考虑自己二次封装一下？

**Comment by afc163** [comment]
Duplicate of #38613
