### ISSUE TITLE
点击4.v版本会显示404 画面

### ISSUE THREAD

**Issue by aa323522** [ant-design/ant-design#46482]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/overview-cn](https://4x-ant-design.antgroup.com/components/overview-cn)

### Steps to reproduce

进入https://ant-design.antgroup.com/components/overview-cn

版本 选择 4.x，画面显示404

### What is expected?

不要出现404

### What is actually happening?

404画面

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 官网 |
| System | 官网 |
| Browser | 官网 |

---
少一个/

**Comment by Wxh16144** [comment]
小问题 😁
