### ISSUE TITLE
级联菜单表单，defaultValue在disabled下失效

### ISSUE THREAD

**Issue by lorrylockie** [ant-design/ant-design#4648]
#### Environment(required)

- antd version: 2.6.0
- Browser and its version: Chrome 最新版

#### What did you do? Please provide steps to re-produce your problem.

1. 复制官方级联菜单第一个例子的demo （Basic 的demo）
2. 在riddle 创建一个demo
3. 复制级联菜单组件，并排写两个组件，同时把第二个复制的级联菜单组件添加defaultValu属性
4. 3步骤后，级联菜单上默认就会选中defaultValue所指定的value
5. 在其中一个级联菜单上添加了disabled属性， 问题出现：defautValue 不生效

#### What do you expected?

disabled下，defaultValue也是生效的，以便能够展示一个禁用状态下，但是表单上有值的级联菜单

#### What happen?

没出现

#### Re-producible online demo

--deleted--

**Comment by lorrylockie** [comment]
@luolonghao

**Comment by afc163** [comment]
不要贴内网地址。
