### ISSUE TITLE
More flexibility for Dropdown.Button

### ISSUE THREAD

**Issue by mimpushkarev** [ant-design/ant-design#46494]
### What problem does this feature solve?

I need to create full width dropdown button, at nowadays it impossible without recreating component or create custom css selector. My solution it is extend Dropdown.button props and pass it to leftButton.

### What does the proposed API look like?

I think, we need to add field `leftButtonProps`, thats repeats button props type
https://github.com/ant-design/ant-design/blob/master/components/dropdown/dropdown-button.tsx#L16
and pass it to component
https://github.com/ant-design/ant-design/blob/master/components/dropdown/dropdown-button.tsx#L113

**Comment by mimpushkarev** [comment]
Can i create PR for resolving this problem?

**Comment by MadCcc** [comment]
It's not recommended to use Dropdown.Button now. Please use `Space.compact` to combine buttons instead.
