### ISSUE TITLE
Support multiple time formats in TimePicker (in line with DatePicker and DateTimePicker)

### ISSUE THREAD

**Issue by floatline** [ant-design/ant-design#46495]
### What problem does this feature solve?

It is impossible to input time values as text, if they don't strictly match the locale format. (You cannot input 12:02:17 AM as 00:02:17 or 9:00:00 PM as 9 PM or 09:00). In case of DatePicker and DateTimePicker it is solved by passing an array of formats to `format`. Refer to this example: https://codesandbox.io/p/sandbox/date-format-antd-5-12-2-44d7tp?file=%2Fdemo.tsx%3A30%2C95

### What does the proposed API look like?

Format should become an array, as it is in DatePicker, so that it accepts arrays of formats. For example, this should work with the new API
```
format={[
'HH:mm:ss',
    'HH:mm',
    'HH',
    'hh:mm:ss A',
    'hh:mm A',
    'hh A',M
]}
```

**Comment by yoyo837** [comment]
ref: https://github.com/react-component/picker/pull/691

**Comment by zombieJ** [comment]
Supported in `5.14.0`. Close.
