### ISSUE TITLE
antd的tabs嵌套proTable切换选项卡会导致页面抖动

### ISSUE THREAD

**Issue by daifuyang** [ant-design/ant-design#46508]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/p/sandbox/cha-xun-biao-ge-forked-txx93v?file=%2FTable.tsx%3A158%2C26)

### Steps to reproduce

依次点击切换tab选项卡，会感觉到工具栏明显的抖动

### What is expected?

不抖动

### What is actually happening?

页面抖动

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | macOS |
| Browser | chrome(120.0.6099.71) |

**Comment by mzzya** [comment]
virtual={true}
scroll={{ y: windowSize.height - 170, x: windowSize.width - 8, scrollToFirstRowOnChange: true }}

看devtools显示的是自动计算宽度导致的，我的明确指定了x y后就不闪了
