### ISSUE TITLE
InputNumber bordered={false}  focus 后鼠标移到外面会出现边框

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#46506]
### Reproduction link

[https://ant.design/components/input-number-cn#input-number-demo-borderless](https://ant.design/components/input-number-cn#input-number-demo-borderless)

### Steps to reproduce

focus 后鼠标移到外面会出现边框

### What is expected?

无边框

### What is actually happening?

有边框

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by Wxh16144** [comment]
`:focus-within` 样式？

**Comment by MadCcc** [comment]
Would be fixed in https://github.com/ant-design/ant-design/pull/46435
