### ISSUE TITLE
Table 开启 虚拟列表后， 如果外部宽度 不是整数 切小数部分大于 0.5 ，会导致横向滚动条显示（在不需要滚动的情况下），因为内部宽度设置的是整数，并且是四舍五入

### ISSUE THREAD

**Issue by leiyu0932** [ant-design/ant-design#46516]
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn](https://ant-design.antgroup.com/components/table-cn)

### Steps to reproduce

调整页面宽度，使demo里的虚拟table 宽度 不是整数，删除一些较宽的列，设置scroll的x值 小一些 比如100，小数部分大于0.5 就能复现 

### What is expected?

不出现滚动条

### What is actually happening?

出现了横向滚动条

| Environment | Info |
| --- | --- |
| antd | 5.12.3 |
| React | 版本没关系 |
| System | mac os |
| Browser | Chrome |

**Comment by afc163** [comment]
来个录屏？

**Comment by leiyu0932** [comment]
https://github.com/ant-design/ant-design/assets/16496767/3b690efa-5195-4813-8202-dc7df6691217

**Comment by leiyu0932** [comment]
已提供录屏， 需要 重新 提个 issue吗 @afc163

**Comment by Alvin-F** [comment]
![table 虚拟表格出现滚动条bug](https://github.com/ant-design/ant-design/assets/20551877/e6b76d79-4672-4184-b5c7-b47488568d33)

大概问题是:  内部设置表格宽度 是四舍五入； 导致判比后触发滚动条逻辑；

需待改进： 如果 x 轴未设置或者 设置成 'max-content' 时 不应该会触发滚动条显隐的逻辑

**Comment by Alvin-F** [comment]
> 已提供录屏， 需要 重新 提个 issue吗 @afc163

有个临时解决方案：加载table 的父级的宽度设置成整数（最好是向下取整）； 我修改成这样，测试中还未重现滚动条问题；
百分比的话： 可以了解下这个 rc-resize-observer 控件

**Comment by JiangMengLei** [comment]
> > 已提供录屏， 需要 重新 提个 issue吗 @afc163
> 
> 有个临时解决方案：加载table 的父级的宽度设置成整数（最好是向下取整）； 我修改成这样，测试中还未重现滚动条问题； 百分比的话： 可以了解下这个 rc-resize-observer 控件

实在是要用百分比的话，可以把横向滚动条隐藏，不差那0.几个像素。
