### ISSUE TITLE
Warning:  `BreadcrumbItem` is required as the wrapper of children element

### ISSUE THREAD

**Issue by jaysson** [ant-design/ant-design#4651]
#### Environment(required)

- antd version: 2.6.3
- OS and its version: MacOS Sierra
- Browser and its version: Google Chrome

#### What did you do? Please provide steps to re-produce your problem.

Copy pasted following code into a react component:
```
import { Menu, Icon, Breadcrumb, Layout } from 'antd';
<Content style={{ padding: '0 50px' }}>
          <Breadcrumb>
            <Breadcrumb.Item>Home</Breadcrumb.Item>
            <Breadcrumb.Item><a href="">Application Center</a></Breadcrumb.Item>
            <Breadcrumb.Item><a href="">Application List</a></Breadcrumb.Item>
            <Breadcrumb.Item>An Application</Breadcrumb.Item>
          </Breadcrumb>
          <div style={{ background: '#fff', padding: 24, minHeight: 280 }}>{ children }</div>
        </Content>
```

#### What do you expected?

It would work fine as it is taken from official website

#### What happened?

It renders properly, but I see the following error in console

`Warning:  `BreadcrumbItem` is required as the wrapper of children element`

**Comment by yesmeck** [comment]
Are you using react-hot-loader 3?

**Comment by afc163** [comment]
Maybe we should use a static property `xxx.__name`? @yesmeck

**Comment by yesmeck** [comment]
How about this?

```javascript
class BreadcrumbItem extends React.Component {
  ...
}

BreadcrumbItem.__antBreadcrumbItem = true;

// use 
if (elment.type.__antBreadcrumbItem) {
    ...
}
```

**Comment by yesmeck** [comment]
@jaysson FYI https://github.com/gaearon/react-hot-loader/issues/304

**Comment by jaysson** [comment]
Yes, I am using react-hot-loader 3.

**Comment by yesmeck** [comment]
Traced in #4655.
