### ISSUE TITLE
弹窗中设置全局样式，导致Select选择时Select.Option浮窗选项样式变形。

### ISSUE THREAD

**Issue by 819049639** [ant-design/ant-design#46512]
### Reproduction link

[https://stackblitz.com/edit/react-bhri1b?file=index.html,demo.tsx](https://stackblitz.com/edit/react-bhri1b?file=index.html,demo.tsx)

### Steps to reproduce

.ant-modal-body 的样式设置了 overflow-y:auto之后，Select的选项浮窗就会顶着Modal的顶部悬浮，而且超过Modal的部分需要滚动才行。

### What is expected?

希望排查是否是bug导致的样式变形

### What is actually happening?

目前我看到的确实是样式出现了问题。

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | MacOS 14.1.2 |
| Browser | Microsoft Edge 版本 118.0.2088.76 (正式版本) (x86_64) |

**Comment by zombieJ** [comment]
预期行为，设置 Popup 元素到容器内 且 该容器为 overflow 时，由于超出部分会被裁剪，它会做偏移来尽可能的多展示 Popup 内容。

你的重现看，不应该添加 `getPopupContainer`:
https://stackblitz.com/edit/react-bhri1b-zyszz6?file=index.html,demo.tsx
