### ISSUE TITLE
暗黑主题下, 从黑色的加载页面切换到黑色的网站主页面时有一个白色的闪屏, 浅色主题也有但不明显

### ISSUE THREAD

**Issue by 21pages** [ant-design/ant-design#46513]
### Reproduction link

[https://github.com/21pages/umimax-antdpro-dark-theme-loading-transition-whitescreen-splash](https://github.com/21pages/umimax-antdpro-dark-theme-loading-transition-whitescreen-splash)

这个示例是用https://umijs.org/docs/max/introduce 创建, 仅添加了加载页, 并修改主题为黑色 [commit](https://github.com/21pages/umimax-antdpro-dark-theme-loading-transition-whitescreen-splash/commit/0403d6bafb8d346b875e426afd38427bb149e03b)

### Steps to reproduce

1. 运行demo
2. 刷新网页

### What is expected?

从加载页面切换到网站主页面, 没有白色的闪屏

### What is actually happening?

从加载页面切换到网站主页面, 有白色的闪屏

https://github.com/ant-design/ant-design-pro/assets/14891774/70ea9c10-5be5-4493-8a0a-d95687241710

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.1.0 |
| System | windows 11 |
| Browser | chrome 120.0.6099.109 |

**Comment by MadCcc** [comment]
把默认的 html 模版背景色改为黑色即可，闪屏是因为页面没有加载失败的白屏

**Comment by 21pages** [comment]
默认的html模板是`src/pages/document.ejs`吗? 修改root div的background-color, 还是白色
