### ISSUE TITLE
DatePicker and Radio work together, causing the time selector in RangePicker's panel to keep scrolling

### ISSUE THREAD

**Issue by Htzhangyating** [ant-design/ant-design#46511]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fan-wei-xuan-ze-qi-antd-5-12-2-forked-y7dcjv?file=%2Fdemo.tsx%3A61%2C48)

### Steps to reproduce

1. Click on a date, for example, last 7 days
2. Click the start or end time of the RangePicker, and you will find that the date selection keeps scrolling

### What is expected?

It is expected that DatePicker and Radio linkage can normally select the date and time

### What is actually happening?

DatePicker and Radio work together, causing the time selector in RangePicker's panel to keep scrolling

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | React 18.2.0 |
| System | macOS 10.15.7  |
| Browser | Chrome 120.0.6099.109 |

**Comment by chenmijiang** [comment]
no problem by using dayjs, maybe have given up adapting momentjs

**Comment by chenmijiang** [comment]
this is because antd uses dayjs by default, and you need to customize the date library，[https://ant.design/docs/react/use-custom-date-library](https://ant.design/docs/react/use-custom-date-library
)



> no problem by using dayjs, maybe have given up adapting momentjs

**Comment by Htzhangyating** [comment]
ok，using dayjs is ok，thank you
