### ISSUE TITLE
Dark theme styling issue after SSR

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#46517]
### Reproduce link

https://ant.design/docs/react/use-with-create-react-app-cn?theme=dark

### Expected

In local developement:

<img width="1295" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/2b1c3a16-52c9-40ac-aca1-ce5e934f2188">

### Actually

<img width="1295" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8dd54b5c-4439-49b0-bc0b-b4d0a4f8c7b6">

**Comment by MadCcc** [comment]
目前看有两个问题：
1. 静态导出的样式在 head 里比客户端动态生成的样式要靠后，所以动态样式变化时会被 SSR 样式覆盖。这点在 nextjs 项目中可以复现，目前想到的解决方案是将组件样式和 cssVar 样式拆分，在客户端将 SSR 生成的样式移除。
2. antd 的站点有另外的问题，具体现象是 useId 在 server 和 client 得到的结果不一样。这一点的原因可能是组件树在服务端渲染和客户端渲染不一致，但是 React 并没有报错，比较难解。

**Comment by afc163** [comment]
https://mdn.alipayobjects.com/huamei_mutawc/afts/img/A*MgfMRpa9Df8AAAAAAAAAAAAADlrGAQ/original

**Comment by MadCcc** [comment]
umi 下使用 useId 在 server 和 client 会得到不一样的结果，需要修复一下
