### ISSUE TITLE
character-function.tsx demo code causing misstype error

### ISSUE THREAD

**Issue by Megaemce** [ant-design/ant-design#46519]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/customize-character-antd-5-12-3-336334?file=%2Fdemo.tsx%3A17%2C11)

### Steps to reproduce

It's a bug in the demo source code on the official page

### What is expected?

No type errors when using the code

### What is actually happening?

````typescript
<Rate defaultValue={2} character={({ index }: { index: number }) => index + 1} />
````

This line is causing the issue: 
````
Type '({ index }: { index: number; }) => ReactNode' is not assignable to type 'ReactNode | ((props: StarProps) => ReactNode)'.
  Type '({ index }: { index: number; }) => ReactNode' is not assignable to type '(props: StarProps) => ReactNode'.
    Types of parameters '__0' and 'props' are incompatible.
      Type 'StarProps' is not assignable to type '{ index: number; }'.
        Types of property 'index' are incompatible.
          Type 'number | undefined' is not assignable to type 'number'.
            Type 'undefined' is not assignable to type 'number'.ts(2322)
````
Thus making the [whole demo](https://github.com/ant-design/ant-design/blob/6a0e8a6c9c6c290f80677444ae136283ec5da414/components/rate/demo/character-function.tsx#L15C15-L15C15) unusable (see [example](https://codesandbox.io/p/sandbox/customize-character-antd-5-12-3-336334?file=%2Fdemo.tsx%3A17%2C11))
This could be fixed like this:

````typescript
<Rate defaultValue={2} character={({ index }: { index?: number }) => index !== undefined && index + 1} />
````

_Originally posted by @Megaemce in https://github.com/ant-design/ant-design/pull/34742#discussion_r1430296942_
            

| Environment | Info |
| --- | --- |
| antd | 5.12.3 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome |

---
I was trying to use the official demo code
https://ant.design/components/rate?theme=dark#design-token

**Comment by afc163** [comment]
You could try `strict: false` in tsconfig.json: https://codesandbox.io/p/sandbox/customize-character-antd-5-12-3-forked-h7k32v?file=%2Fdemo.tsx%3A17%2C23

**Comment by afc163** [comment]
Or update types in demo: https://github.com/ant-design/ant-design/pull/46520
