### ISSUE TITLE
date-picker   样式全错乱

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#46525]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

https://ant.design/components/date-picker-cn

![image](https://github.com/ant-design/ant-design/assets/29728228/6482e884-0ac9-46ce-88b0-b48c6cf322ce)

![image](https://github.com/ant-design/ant-design/assets/29728228/23a608c8-30cd-4714-b3dd-f71382c6ee4b)

![image](https://github.com/ant-design/ant-design/assets/29728228/7e103945-6578-4380-a1c2-4f3799c02eab)

### What is expected?

https://ant.design/components/date-picker-cn

### What is actually happening?

https://ant.design/components/date-picker-cn

| Environment | Info |
| --- | --- |
| antd | 5.12.3 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
CSS 变量看起来有问题， @MadCcc
