### ISSUE TITLE
Form - Cant get field value when use ConfigProvider

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#46522]
### Reproduction link

[https://stackblitz.com/edit/react-n1o6cq?devToolsHeight=33&file=demo.tsx](https://stackblitz.com/edit/react-n1o6cq?devToolsHeight=33&file=demo.tsx)

### Steps to reproduce

1. Go to reproduction
2. Fill value to form
3. Click submit
4. Check console

### What is expected?

Form data is collected

### What is actually happening?

Form data is not collected

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | Macbook Air M1 2020 - macOS 13.3.1 |
| Browser | Chrome 112.0.5615.137 |

---
I want to use ConfigProvider only to interfere with the style of Input or Upload, I don't want it to change Form.Item

**Comment by archisketch-thangly** [comment]
Or if I use ConfigProvider to wrap Form.Item, the label will be shifted to the right

![image](https://github.com/ant-design/ant-design/assets/105255382/1128248e-0ea9-4f84-90ef-b53da397c7ef)

**Comment by afc163** [comment]
https://ant.design/components/form#components-form-demo-complex-form-control

> `<Form.Item name="field" />` will only bind the control(Input/Select) which is the only children of it.

---

There is some solutions:

1. Use two Form.Item, one for `label`, one for data binding. https://ant.design/components/form#components-form-demo-complex-form-control
2. A customized form control: https://ant.design/components/form#components-form-demo-customized-form-controls
