### ISSUE TITLE
Steps with long title will break style

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4652]
A little ugly:

![](https://static.dingtalk.com/media/lALOnvMJwMyyzQPx_1009_178.png_620x10000q90g.jpg)

**Comment by yesmeck** [comment]
这么长的标题应该写成下面的描述才对吧。

**Comment by afc163** [comment]
I didn't see any break style.

**Comment by paranoidjk** [comment]
@benjycui 的意思是两个step之间的线条长度不是均等的...

**Comment by afc163** [comment]
这个设计上就是这样的，例子也很极端，问题不大。

**Comment by LeezQ** [comment]
例子是极端的，但是也是有这种情况的吧。看下面的例子：
![image](https://cloud.githubusercontent.com/assets/972813/22133412/0e4a829e-defb-11e6-999f-4b55a189936d.png)

**Comment by afc163** [comment]
组件就是这样设计的。

**Comment by benjycui** [comment]
@LeezQ title 只是个概述，描述性的文字可以放进 description ?

https://ant.design/components/steps/#components-steps-demo-simple
