### ISSUE TITLE
[Nextjs] cssinjs flicker in streaming mode

### ISSUE THREAD

**Issue by infodusha** [ant-design/ant-design#46533]
### Reproduction link

[https://github.com/infodusha/antd-next-streaming-issue](https://github.com/infodusha/antd-next-streaming-issue)

### Steps to reproduce

Have a streamed page with timeout, that you directly navigate, and you already rendered some styles before the streaming

### What is expected?

There is no flicker

### What is actually happening?

There is a flicker when page is loaded directly.

| Environment | Info |
| --- | --- |
| antd | 5.12.3 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 120 |

**Comment by infodusha** [comment]
https://github.com/ant-design/ant-design/assets/5677047/96435cf8-5831-44a2-8c55-cfbbdb441a16

**Comment by infodusha** [comment]
The bug was also mentioned in https://github.com/ant-design/ant-design/issues/45955 if anyone wants a workaround

**Comment by MadCcc** [comment]
```diff
- "@ant-design/cssinjs": "1.17.2"
+ "@ant-design/cssinjs": "^1.17.2"
```
DO NOT lock cssinjs version, it will cause multiple instances.

**Comment by infodusha** [comment]
@MadCcc sorry to bother you

I have updated the repo to have the same (and latest ) version of cssinjs but the bug is still there
<img width="697" alt="image" src="https://github.com/ant-design/ant-design/assets/5677047/4d02dc27-d3c8-4929-83d1-afec1d51c08c">

**Comment by infodusha** [comment]
The issue seems to be related with deduplication logic copied from getting stared guide:
```ts
// avoid duplicate css insert
if (isServerInserted.current) {
  return;
}
```
I would expect it to use cache to detect if anything was changed and what css should be added when streaming
Otherwise it seems to cut off streaming part, but if i will remove the logic it may result multiple style tags with same id inserted
