### ISSUE TITLE
BUG:Transfer无法对搜索结果进行全选

### ISSUE THREAD

**Issue by freepander** [ant-design/ant-design#4654]
#### Environment(required)

- antd version:2.6.3
- OS and its version:*
- Browser and its version:*

带搜索框的穿梭框， 输入搜索内容后，点击全选框实际选择的是全部选项，而不是搜索出来的选项。
![image](https://cloud.githubusercontent.com/assets/4476975/22102205/98091462-de71-11e6-9721-95f63997e40c.png)
![image](https://cloud.githubusercontent.com/assets/4476975/22102243/b26d5df4-de71-11e6-90d2-e85bb77e571a.png)

点击全选按钮应该选择当前搜索结果。

https://ant.design/components/transfer-cn/ 官网演示可复现。

**Comment by paranoidjk** [comment]
- 目前的实现的确是search的筛选不会实时反馈到顶部的全选checkbox,  你可以从右侧`20/20 items`看出
- 感谢反馈，你提的建议需要讨论~

**Comment by benjycui** [comment]
这样的确是反直觉。

**Comment by benjycui** [comment]
@paranoidjk 有兴趣做？

**Comment by paranoidjk** [comment]
@benjycui ok，assign给我吧
