### ISSUE TITLE
Input.Search focus时会在放大镜上

### ISSUE THREAD

**Issue by zhangqhzz** [ant-design/ant-design#46540]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/sou-suo-kuang-antd-5-12-4-sd77lk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqd7ad3l0006356hg9gkim4i%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqd7ad3l0002356hdge8pdej%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqd7ad3l0003356hpv0olhth%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqd7ad3l0005356hjhttqqdu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqd7ad3l0002356hdge8pdej%2522%253A%257B%2522id%2522%253A%2522clqd7ad3l0002356hdge8pdej%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqd7ad3l0005356hjhttqqdu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqd7ad3l0004356h0t58fg4c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqd7ad3l0005356hjhttqqdu%2522%252C%2522activeTabId%2522%253A%2522clqd7ad3l0004356h0t58fg4c%2522%257D%252C%2522clqd7ad3l0003356hpv0olhth%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqd7ad3l0003356hpv0olhth%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

在第一个Input中按tab键

### What is expected?

希望根据form.getFieldInstance(字段).focus() 后，焦点在输入框内部

### What is actually happening?

不是到 Search输入框中，而是到放大镜上了

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 最新版 |
| System | windows11 |
| Browser | edge\chrome |

**Comment by zombieJ** [comment]
按照无障碍要求，Tab 到下一个可聚焦按钮是符合预期的。如果不需要这个功能，可以考虑使用 Space.Compact 自己拼一个 `tabIndex` 为 `-1` 的搜索框哈。

**Comment by zhangqhzz** [comment]
但如果是两个Search之间同样进行不会这样，只是从Input到Search会这样，这怎么解释?




求真
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Input.Search focus时会在放大镜上 (Issue #46540)





 
按照无障碍要求，Tab 到下一个可聚焦按钮是符合预期的。如果不需要这个功能，可以考虑使用 Space.Compact 自己拼一个 tabIndex 为 -1 的搜索框哈。

**Comment by zhangqhzz** [comment]
无障碍的话，1、为什么回车键 却是可以到输入框里的呢？
2、两个Search,在第一个的放大镜上时，tab键会进入第二个的输入框，而不是放大镜


https://codesandbox.io/p/sandbox/sou-suo-kuang-antd-5-12-4-forked-qxskr9?file=%2Fdemo.js%3A20%2C44


求真
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Input.Search focus时会在放大镜上 (Issue #46540)





 
按照无障碍要求，Tab 到下一个可聚焦按钮是符合预期的。如果不需要这个功能，可以考虑使用 Space.Compact 自己拼一个 tabIndex 为 -1 的搜索框哈。
