### ISSUE TITLE
Ant Design V5, Select Multiple functional requirement,the selected display is dynamic custom content

### ISSUE THREAD

**Issue by Htzhangyating** [ant-design/ant-design#46548]
### What problem does this feature solve?

For example, there are 5 pieces of data, select 2 pieces, and display '2 selected / 5 in total' in the selection box

### What does the proposed API look like?

selectedRender={() => { return ReactNode||string }}

**Comment by zombieJ** [comment]
Use `maxTagCount` + `maxTagPlaceholder` to realize it.
