### ISSUE TITLE
Modal 会影响垂直滚动条

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#46546]
### Reproduction link

[https://ant.design/components/modal-cn](https://ant.design/components/modal-cn)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/29728228/263b1ff2-0832-42bd-bd83-9918f1bbe135)

直接官网页面，弹出modal，右侧垂直滚动条隐藏了，页面会有明显的向右滚动，影响体验，之前的版本没有这个问题

对于自适应宽度100%的页面 因为有明显的抖动，体验不好

### What is expected?

不影响水平和垂直滚动条

### What is actually happening?

页面因为隐藏滚动条导致滚动，体验不好

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
Modal 弹出时会锁定 body 滚动，然后在 body 添加一个右侧等滚动条宽度的 padding 来保持容器宽度。的确在少数场景下存在绝对定位的元素会有抖动问题。由于目前还没有一个很好的不通过 `overflow: hidden` 禁止滚动的办法，这个问题估计还会持续相当一段时间。

如果确实不想要滚动锁定，可以给 body 加一个 `overflow: auto` 覆盖掉 Modal 提供的样式哈~

**Comment by zystudios** [comment]
> Modal 弹出时会锁定 body 滚动，然后在 body 添加一个右侧等滚动条宽度的 padding 来保持容器宽度。的确在少数场景下存在绝对定位的元素会有抖动问题。由于目前还没有一个很好的不通过 `overflow: hidden` 禁止滚动的办法，这个问题估计还会持续相当一段时间。
> 
> 如果确实不想要滚动锁定，可以给 body 加一个 `overflow: auto` 覆盖掉 Modal 提供的样式哈~

👌

**Comment by afc163** [comment]
符合预期，占位保持内容不跳动用的。
