### ISSUE TITLE
Tour 在高亮区域可滚动

### ISSUE THREAD

**Issue by wwwenjie** [ant-design/ant-design#46556]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qw6vvf?file=%2Findex.js%3A35%2C16)

### Steps to reproduce

当高亮元素位于一个非 body 的滚动区域时，在高亮区域进行滚动

### What is expected?

不进行滚动

### What is actually happening?

发生滚动

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18 |
| System | mac 14.2 (23C64) |
| Browser | Chrome 120.0.6099.109 |

---
注意到 rc-portal 会 lock scroll，但是样式是增加到 body 上的，对于位于另一个滚动容器的元素并不适用。Tour 组件是否能特殊 lock 到当前滚动容器？

**Comment by MadCcc** [comment]
容器可滚动的情况不好判断，Tour 无法得知是哪个容器支持滚动。建议受控 open 然后自行控制该容器的 overflow。
