### ISSUE TITLE
关于Badge组件dot和showZero属性优先级问题

### ISSUE THREAD

**Issue by LvZhenXiang** [ant-design/ant-design#46557]
### Reproduction link

[https://stackblitz.com/edit/react-n9wxkc-mwgbkh?file=demo.tsx](https://stackblitz.com/edit/react-n9wxkc-mwgbkh?file=demo.tsx)

### Steps to reproduce

Badge组件的showZero和dot属性都为true，count属性为0时

### What is expected?

即使showZero值为0，dot为true时应该展示红点

### What is actually happening?

showZero值为0时，dot为true也会显示数值0

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18.2.0 |
| System | windows |
| Browser | Chrome 119.0.6045.200 |

**Comment by zombieJ** [comment]
`showZero` 用于数值，而 `dot` 是不展示数值。两个本身就是不一起用的哈。如果你需要这个效果，可以 HOC 一下，根据数字来动态切换：
https://stackblitz.com/edit/react-n9wxkc-tzshy1?file=demo.tsx

**Comment by LvZhenXiang** [comment]
> `showZero` 用于数值，而 `dot` 是不展示数值。两个本身就是不一起用的哈。如果你需要这个效果，可以 HOC 一下，根据数字来动态切换： https://stackblitz.com/edit/react-n9wxkc-tzshy1?file=demo.tsx

ok
