### ISSUE TITLE
4.24.15版本form组件表单方法调用Class   this.formRef.current!.setFieldsValue({ note: 'Hi, man!' })写错了

### ISSUE THREAD

**Issue by xiangYu6688** [ant-design/ant-design#46555]
### Reproduction link

[https://4x.ant.design/components/form-cn/#components-form-demo-control-ref](https://4x.ant.design/components/form-cn/#components-form-demo-control-ref)

### Steps to reproduce

 this.formRef.current!.setFieldsValue({ note: 'Hi, man!' });
        return;
      case 'female':
        this.formRef.current!.setFieldsValue({ note: 'Hi, lady!' });
        return;
      case 'other':
        this.formRef.current!.setFieldsValue({ note: 'Hi there!' });

### What is expected?

!.  换成 ?.

### What is actually happening?

!.  换成 ?.

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | react |
| System | 4.24.15 |
| Browser | 谷歌 |

---
文档示例错了，!. 应该改成?.吧

**Comment by crazyair** [comment]
`!.` 写法没问题，虽然不建议，但是是可以用的，需要保证值存在
https://typescript-eslint.io/rules/no-non-null-assertion/

**Comment by xiangYu6688** [comment]
ok，ts确实可以，感谢

**Comment by xiangYu6688** [comment]
> `!.` 写法没问题，虽然不建议，但是是可以用的，需要保证值存在 https://typescript-eslint.io/rules/no-non-null-assertion/

ts确实可以，感谢回复
