### ISSUE TITLE
Autocomplete OnSelect do not work properly

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#4656]
if child of Autocomplete.Option is a react node it does not properly handle onSelect function if input value is not equal to the key of AutoComplete.Option. it places [object Object] to the input value, must be Option key

http://codepen.io/anon/pen/egvYBq?editors=0010

**Comment by RaoHai** [comment]
```jsx
<AutoComplete optionLabelProp="label" />
```

It has been set to `children` as default in AutoComplete.

https://github.com/ant-design/ant-design/blob/master/components/auto-complete/index.tsx#L29

**Comment by vorlov** [comment]
Docs must be updated
