### ISSUE TITLE
ColorPicker 组件无法完全受控

### ISSUE THREAD

**Issue by Enivia** [ant-design/ant-design#46566]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-1-forked-97qny7?file=%2Fdemo.tsx%3A13%2C31)

### Steps to reproduce

- value 传递 undefined 时，应为 cleared 状态
- cleared 状态外部无法控制
- value 传递固定值时，回显颜色和选择面板颜色不一致

### What is expected?

ColorPicker 可完全受控

### What is actually happening?

ColorPicker 无法完全受控

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 120 |

**Comment by MadCcc** [comment]
> value 传递 undefined 时，应为 cleared 状态
> cleared 状态外部无法控制

Feature in 5.13.0 (not released) https://github.com/ant-design/ant-design/pull/45993

>  value 传递固定值时，回显颜色和选择面板颜色不一致

回显颜色是 value 的值，面板颜色随用户拖动改变，否则就不可交互了
