### ISSUE TITLE
[BUG]Table TreeData

### ISSUE THREAD

**Issue by HappyAxin** [ant-design/ant-design#46563]
### Reproduction link

[Table-TreeData](https://codesandbox.io/p/sandbox/bug-table-vqrt8w?file=%2Fsrc%2FApp.js%3A183%2C22)

### Steps to reproduce

[Click It to Code](https://codesandbox.io/p/sandbox/bug-table-vqrt8w?file=%2Fsrc%2FApp.js%3A183%2C22)

### What is expected?

Shouldn't it be a click to open? Why would it open at the same time?

### What is actually happening?

Why is it that when I click on the first expansion to open it, the second one opens as well?

![image](https://github.com/ant-design/ant-design/assets/46963688/916fb3b7-1282-47e2-8656-09a5ce479c54)

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18.2 |
| System | windows |
| Browser | Chrome 119.0.6045.200（正式版本） |

**Comment by HappyAxin** [comment]
![image](https://github.com/ant-design/ant-design/assets/46963688/df65d0b2-254e-430d-ac2e-51ec1394818d)
This is official demo, datasource has the same data structure.It's outrageous!

**Comment by zombieJ** [comment]
React has tell you the reason:

<img width="747" alt="截屏2023-12-21 14 40 58" src="https://github.com/ant-design/ant-design/assets/5378891/9e88c831-ef28-4fe6-ab36-aaf1339890e5">


Use `rowKey` for the data.

**Comment by HappyAxin** [comment]
> React has tell you the reason:
> 
> <img alt="截屏2023-12-21 14 40 58" width="747" src="https://private-user-images.githubusercontent.com/5378891/292114981-9e88c831-ef28-4fe6-ab36-aaf1339890e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDE4MTUsIm5iZiI6MTcwMzE0MTUxNSwicGF0aCI6Ii81Mzc4ODkxLzI5MjExNDk4MS05ZTg4YzgzMS1lZjI4LTRmZTYtYWIzNi1hYWYxMzM5ODkwZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDY1MTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUwYTM4OTY3YmRiOGJkZjYwN2I0OWQwYTRjMTJhZGQwNThjMDQ0MjBkYWM2Mzc4NjNjY2E1OTNhYWUxMTQxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mM7DjYgXnMDqVWzB8yPns5GfLuXi6wPs97iumy36gSc">
> Use `rowKey` for the data.

ID doesn't work?

**Comment by zombieJ** [comment]
> Use `rowKey` for the data.

↑ `id` is not the keyword for React, its your business logic. Use `rowKey="id"` to map the key.
