### ISSUE TITLE
对于整个页面的Spin ，可以提供一个加载指示符显示在当前窗口的属性

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#46577]
### What problem does this feature solve?

如果页面很长，超过2屏以上，对于整个页面的Spin的加载指示符，默认是在第一屏，这样如果当前浏览在下面，就看不见这个指示符，而且页面会有白色的蒙层，建议可以有一个属性，让Spin出现的时候，指示符的top = document.documentElement.scrollTop，这样不管用户在第几屏，都可以看见指示符，体验会更好一些

### What does the proposed API look like?

<Spin
      scrollTop={true | 1000}
>

可以直接设置true，默认显示当前窗口，也可以输入具体数值，用户控制高度

**Comment by Wxh16144** [comment]
感觉有点太偏业务了，类似场景比较少。或许你可以自己操作一下？

**Comment by MadCcc** [comment]
Spin 是 fixed 的，如果页面滚动到下面看不见的话是 bug，请提供复现

**Comment by zystudios** [comment]
> Spin 的 `fullscreen` 是 fixed 的，如果页面滚动到下面看不见的话是 bug，请提供复现

![image](https://github.com/ant-design/ant-design/assets/29728228/11dac093-4357-401d-9ad5-d0ac2226f67d)

absolute定位

**Comment by zystudios** [comment]
> Spin 的 `fullscreen` 是 fixed 的，如果页面滚动到下面看不见的话是 bug，请提供复现

原来新增了fullscreen属性，我升级下版本
