### ISSUE TITLE
Chinese literals shown

### ISSUE THREAD

**Issue by SamyukthaJ** [ant-design/ant-design#4657]
I am using "antd": "^2.6.1" in my react project. The entire project is in English. I installed the above library and started using ant design. Somehow there are chinese literals / language showing up for ex:
Table with pagination, no.of records per page -
<img width="1437" alt="screen shot 2017-01-19 at 2 07 32 pm" src="https://cloud.githubusercontent.com/assets/8127173/22127413/a8c72882-de50-11e6-97c2-d6387128c9a9.png">

Range picker months and days -
<img width="523" alt="screen shot 2017-01-19 at 2 09 07 pm" src="https://cloud.githubusercontent.com/assets/8127173/22127481/e09ee29a-de50-11e6-9e66-e24539fe39e2.png">

Could someone help?

**Comment by benjycui** [comment]
Use [`LocaleProvider`](https://ant.design/components/locale-provider/)
