### ISSUE TITLE
Tooltip结合iconfy的Icon使用报Warning

### ISSUE THREAD

**Issue by hmpfeng** [ant-design/ant-design#46579]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-m452xj?file=%2Findex.js%3A16%2C24)

### Steps to reproduce

    <React.StrictMode>
      <div>
        <Tooltip title={"重置"} placement={"top"}>
          <Icon icon={"iconoir:refresh"} />
        </Tooltip>
      </div>
    </React.StrictMode>

### What is expected?

可以在严格模式下使用Tooltip   iconify的组合且没有警告信息。

### What is actually happening?

在严格模式下使用Tooltip   iconify的组合会出现：
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper4 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using。

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18 |
| System | Windows 11 |
| Browser | Edge 120.0.2210.77 (正式版本) (64 位) |

**Comment by MadCcc** [comment]
Tooltip 需求 children 支持 ref，建议自行封装一下
