### ISSUE TITLE
Table，columns列设置ellipsish后，td内容有出现出现tooltip弹窗显示全部内容，但是表头鼠标移到这上面没有出现tooltip弹窗显示title，怎分才能实现？

### ISSUE THREAD

**Issue by xian107** [ant-design/ant-design#46578]
### What problem does this feature solve?

英文title字段比较长，columns设置ellipsish后，title长度被截断了变成...，鼠标移上去也看不到title

### What does the proposed API look like?

鼠标移上去出现tooltip弹窗显示title
![1703210219693](https://github.com/ant-design/ant-design/assets/13252682/15460637-b622-4fb2-a767-a2faea130ce0)

**Comment by Wxh16144** [comment]
<img width="1430" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/803c3899-d9cc-4ee3-8fd8-e69f9785a6bf">
自己实现一下 span 的 ellipsish 然后 title 用 `<Tooltip />` 搞一下？

**Comment by xian107** [comment]
> <img alt="image" width="1430" src="https://private-user-images.githubusercontent.com/32004925/292355518-803c3899-d9cc-4ee3-8fd8-e69f9785a6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTE0OTgsIm5iZiI6MTcwMzIxMTE5OCwicGF0aCI6Ii8zMjAwNDkyNS8yOTIzNTU1MTgtODAzYzM4OTktZDljYy00ZWUzLThmZDgtZTY5Zjk3ODVhNmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAyMTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MDExNTRlMzEzMzNkYTUyNmY1NTBmNmExZDVjNjc3NDQ4Mjk3NDdlYmM1M2YwOTI4YWRmMTA3ODUxMWM1YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oLzfX-dV0NVIj7V0FYnuFXPkigKjwWhDC8U0uLKn7E"> 自己实现一下 span 的 ellipsis 然后 title 用 Tooltip 搞一下？

title长度够的话，最好不出现tooltip，因为项目是国际化得，按你这种，我所有title都得自己加tooltip，比较麻烦

**Comment by Wxh16144** [comment]
但是你内容也是套的 Tooltip，也是没有判断出现 ellipsis 才出现 Tooltip。
