### ISSUE TITLE
Tabs editable-card 关闭所有标签之后剩余的添加标签按钮样式异常

### ISSUE THREAD

**Issue by hzyhbk** [ant-design/ant-design#46584]
### Reproduction link

https://codepen.io/hzyhbk/pen/dyryNBV?editors=001

### Steps to reproduce

1. 修改 initialItems，将第三个选项的 closable: false 注释掉
2. 删除所有标签

### What is expected?

剩余的加号按钮样式正常
![image](https://github.com/ant-design/ant-design/assets/42671099/9140a094-d60b-4bde-ad5e-2ce47ec3e1a6)

### What is actually happening?

剩余的加号按钮缩小了
![image](https://github.com/ant-design/ant-design/assets/42671099/c318efd7-05b5-4661-a4db-833aaf743d0b)

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18 |
| System | macOS 14.2  |
| Browser | Microsoft Edge 版本 121.0.2256.2 (正式版本) Dev(arm64) |

**Comment by MadCcc** [comment]
请提供有内容的复现

**Comment by hzyhbk** [comment]
> 请提供有内容的复现

抱歉，之前没注意复制的链接有误。 https://codepen.io/hzyhbk/pen/dyryNBV?editors=001
