### ISSUE TITLE
Input onChange trigger two times when input chinese

### ISSUE THREAD

**Issue by qietuzi** [ant-design/ant-design#46587]
### Reproduction link
https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-4-forked-mqpl2w
### Steps to reproduce

just input chinese

### What is expected?

fix it or show how to hack it

### What is actually happening?

trigger twice

| Environment | Info |
| --- | --- |
| antd | 5.12.0 |
| React | 18.2.0 |
| System | window 10 64 |
| Browser | chrome  120.0.6099.110 |

---
i can not access to internet 

[https://gitee.com/qietuzi/remark/raw/master/20231222-151704.jpg]
(https://gitee.com/qietuzi/remark/raw/master/20231222-151704.jpg)

**Comment by qietuzi** [comment]
access to internet is so difficulty!!!

**Comment by afc163** [comment]
原生 input 也是一样的表现，应该和 antd 无关：https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-4-forked-l57gg4

**Comment by qietuzi** [comment]
![Uploading 20231222-162832.jpg…]()

**Comment by qietuzi** [comment]
![20231222-162832](https://github.com/ant-design/ant-design/assets/21035839/ccf89e48-ff16-45b9-b71e-ee806e60c946)

**Comment by qietuzi** [comment]
> 原生 input 也是一样的表现，应该和 antd 无关：https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-4-forked-l57gg4

你看看你写的demo呢，我打印出来只有一次，我这的网络不稳定，一会能上一会不能上

**Comment by yoyo837** [comment]
你两次的复现给一下？

**Comment by qietuzi** [comment]
> 你两次的复现给一下？
不就是欺负我上班时间不能访问吗

https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-4-forked-l57gg4?file=%2Fdemo.tsx%3A4%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqgdbggr0006356k8v8zsz0r%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqgdbggr0002356khe8jw97l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqgdbggr0003356khne3dh4r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqgdbggr0005356kt7w7701u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40.4103684119777%252C59.5896315880223%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqgdbggr0002356khe8jw97l%2522%253A%257B%2522id%2522%253A%2522clqgdbggr0002356khe8jw97l%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqgdbggr0005356kt7w7701u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgdbggr0004356kg2q7k912%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqgdbggr0005356kt7w7701u%2522%252C%2522activeTabId%2522%253A%2522clqgdbggr0004356kg2q7k912%2522%257D%252C%2522clqgdbggr0003356khne3dh4r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqgdbggr0003356khne3dh4r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by qietuzi** [comment]
> 你两次的复现给一下？

https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-12-4-forked-mqpl2w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqgdbggr0006356k8v8zsz0r%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqgdbggr0002356khe8jw97l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqgdbggr0003356khne3dh4r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqgdbggr0005356kt7w7701u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40.4103684119777%252C59.5896315880223%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqgdbggr0002356khe8jw97l%2522%253A%257B%2522id%2522%253A%2522clqgdbggr0002356khe8jw97l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgef6yt0002356k2zhrlo2u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqgef6yt0002356k2zhrlo2u%2522%257D%252C%2522clqgdbggr0005356kt7w7701u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgdbggr0004356kg2q7k912%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqgdbggr0005356kt7w7701u%2522%252C%2522activeTabId%2522%253A%2522clqgdbggr0004356kg2q7k912%2522%257D%252C%2522clqgdbggr0003356khne3dh4r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqgdbggr0003356khne3dh4r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by qietuzi** [comment]
看起来是rc-input 引发的

**Comment by zombieJ** [comment]
`compositionEvent` 事件会兜底再发个 `onChange` 事件以防止用户输入法漏监听的情况，这个的确是可以优化一下。

**Comment by RainyLiao** [comment]
> `compositionEvent` 事件会兜底再发个 `onChange` 事件以防止用户输入法漏监听的情况，这个的确是可以优化一下。
您好，请问下漏监听是什么情况下发生的呢？我理解`onCompositionEnd`事件在用户输入法组合结束的时候会调用，但在结束的时候也会自动触发`onChange`事件的吧，不需要在`onCompositionEnd`中进行`triggerChange`的调用了。

**Comment by RainyLiao** [comment]
您好，请问下漏监听是什么情况下发生的呢？我理解`onCompositionEnd`事件在用户输入法组合结束的时候会调用，但在结束的时候也会自动触发`onChange`事件的吧，不需要在`onCompositionEnd`中进行`triggerChange`的调用了。

**Comment by zombieJ** [comment]
> 您好，请问下漏监听是什么情况下发生的呢？我理解`onCompositionEnd`事件在用户输入法组合结束的时候会调用，但在结束的时候也会自动触发`onChange`事件的吧，不需要在`onCompositionEnd`中进行`triggerChange`的调用了。

Input 的 `count` 方法允许对裁剪进行进一步加工，所以在输入法事件后会额外触发一次。但是对于没有 `count` 的场景的确是没有必要的。
