### ISSUE TITLE
低版本浏览器兼容问题

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46588]
### Reproduction link

[https://github.com/crazyair/antd5](https://github.com/crazyair/antd5)

![image](https://github.com/ant-design/ant-design/assets/7971419/2291535d-361a-4046-a927-032292cd7116)

### Steps to reproduce

yarn start

### What is expected?

各个组件样式没问题

### What is actually happening?

样式异常

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | latest |
| System | mac |
| Browser | chrome 86 |

**Comment by MadCcc** [comment]
目前只剩下静态方法消费 StyleContext 的问题，由于静态方法处于半废弃状态，不再考虑支持了。

**Comment by jiumengs** [comment]
chrome 86样式不会再被支持了么，有很大一批用户在用360极速浏览器，他的最新版在86版本停更了
又搞了一个360极速x，  大多数用户是不知道需要重新下载的。

**Comment by crazyair** [comment]
> chrome 86样式不会再被支持了么，有很大一批用户在用360极速浏览器，他的最新版在86版本停更了 又搞了一个360极速x， 大多数用户是不知道需要重新下载的。

https://github.com/ant-design/ant-design/pull/46596

**Comment by jiumengs** [comment]
> 目前只剩下静态方法消费 StyleContext 的问题，由于静态方法处于半废弃状态，不再考虑支持了。

get到了，着手改造函数式 然后把静态方法再改了。就OK了。已经改造了半个页面，实际感受页面稍显卡顿，不知道是不是我的错觉，还是低版本浏览器的问题

**Comment by jiumengs** [comment]
![iShot_2023-12-29_15 07 47](https://github.com/ant-design/ant-design/assets/39983417/f74b11e0-a01f-4b0a-890a-4e686471ce06)
![iShot_2023-12-29_15 08 07](https://github.com/ant-design/ant-design/assets/39983417/475ba2d3-a22f-4b7f-8bc8-d0c55970e1b5)
