### ISSUE TITLE
message maxCount 失效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46581]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/qi-ta-ti-shi-lei-xing-antd-5-12-4-forked-24wjdr?file=%2Fdemo.tsx%3A10%2C7)

### Steps to reproduce

点击 `message2`

### What is expected?

`1`的提示会闪一下

### What is actually happening?

只显示`3`

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome |

---
应该是 react16 初始化问题，第一次执行会出现问题，再次执行就不出现了

**Comment by zombieJ** [comment]
Close since reproduce is invalidate.
