### ISSUE TITLE
Select组件设置maxTagCount="responsive"在宽度不为整数下可能会出现换行情况

### ISSUE THREAD

**Issue by Babyfaceqian** [ant-design/ant-design#46591]
### Reproduction link

[sandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-ycfqmc?file=%2Findex.js%3A13%2C26&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqhrttyo00063b6ifakvzr9g%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqhrttyo00023b6inla167hx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqhrttyo00033b6ihsq9ai5n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqhrttyo00053b6iludcoaou%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B66.86748008161946%252C33.13251991838054%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqhrttyo00023b6inla167hx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqhrttyo00013b6iz4a1quy6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A26%257D%255D%257D%255D%252C%2522id%2522%253A%2522clqhrttyo00023b6inla167hx%2522%252C%2522activeTabId%2522%253A%2522clqhrttyo00013b6iz4a1quy6%2522%257D%252C%2522clqhrttyo00053b6iludcoaou%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqhrttyo00043b6i864qvodn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqhrttyo00053b6iludcoaou%2522%252C%2522activeTabId%2522%253A%2522clqhrttyo00043b6i864qvodn%2522%257D%252C%2522clqhrttyo00033b6ihsq9ai5n%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqhrttyo00033b6ihsq9ai5n%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. 重现链接中，当选择框宽度和内容宽度接近，选择框宽度因为百分比的原因不为整数时会出现。
### What is expected?

选择框不换行

### What is actually happening?

选择框换行

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 17.0.1 |
| System | mac os 13.4.1 |
| Browser | Chrome 119.0.6045.199 |

### What is expected?

选择框不换行

### What is actually happening?

选择框换行

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 17.0.1 |
| System | mac os 13.4.1 |
| Browser | Chrome 119.0.6045.199 |

**Comment by Babyfaceqian** [comment]
提供了重现的codesandbox，链接贴在Reproduction link下了。

**Comment by afc163** [comment]
来个 gif 吧，这样方便重现问题。

**Comment by Babyfaceqian** [comment]
> 来个 gif 吧，这样方便重现问题。
不好意思，重新更新了重现步骤，下方是截图。
<img width="1457" alt="截屏2023-12-25 10 09 43" src="https://github.com/ant-design/ant-design/assets/20655116/214e75a3-1de2-436c-8845-5c6f02c8643d">

**Comment by MadCcc** [comment]
![image](https://github.com/ant-design/ant-design/assets/27722486/6c93278c-3045-4dcb-8756-50af04413b84)
输入框换行了

**Comment by MadCcc** [comment]
input 必须要有个宽度，这个没什么好办法解决，可以稍微修改一下宽度
