### ISSUE TITLE
table组件开启虚拟列表功能后，不能配合编辑单元格使用

### ISSUE THREAD

**Issue by gaohonglin** [ant-design/ant-design#46597]
### Reproduction link

[https://gitee.com](https://gitee.com)

### Steps to reproduce

在antd5.9.0及5.12.4版本，使用table组件，开启虚拟列表后，在使用其提供的编辑单元格功能报错
 React does not recognize the `dataIndex` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataindex` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### What is expected?

期望虚拟列表开启后，可以配合编辑单元格功能使用

### What is actually happening?

目前不能使用，报错，在DOM中渲染为<div record="[object Object]" dataindex="address" title="Address" class="ant-table-cell" style="flex: 0 0 210px; width: 210px; margin-right: 0px; pointer-events: auto;">New York No. 2 Lake Park</div>

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | 18.2.0 |
| System | window10 |
| Browser | chrome 119.0.6045.200 |

---
基于table实现列表树功能，并且实现table中的单元格可以编辑，表格会渲染大量数据，需要使用虚拟列表功能，提高表格性能

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/46218#issuecomment-1842424241
