### ISSUE TITLE
Empty e.target.files in onChange handler for Input type="file" in Safari only

### ISSUE THREAD

**Issue by eugene-khyst** [ant-design/ant-design#46598]
### Reproduction link

[https://stackblitz.com/edit/react-ss2bde?file=demo.tsx](https://stackblitz.com/edit/react-ss2bde?file=demo.tsx)

### Steps to reproduce

1. Choose any file using the Input
2. Check the message in the console "files length: ..."

### What is expected?

Expected message in the console in all browsers: `files length: 1`

Expected that `e.target.files` in the `onChange` handler will contain the chosen file.
```typescript
const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
  console.log('files length:', e.target.files?.length);
};
```

### What is actually happening?

Actual message in the console in Safari: `files length: 0`

Actual message in the console in Chrome: `files length: 1`

In Safari actually `e.target.files` in the `onChange` handler is empty:
```typescript
const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
  console.log('files length:', e.target.files?.length);
};
```

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | macOS Ventura 13.5 |
| Browser | Safari 16.6 |

---
The problem is absent in Antd 5.10.x. The problem started after update to Antd 5.11.x and is still present in Antd 5.12.5.

The problem appear in Safari on MacOS and iOS. In Google Chrome and Firefox the problem is absent.

**Comment by yoyo837** [comment]
Our upcoming release of 5.13.0 will include this fix.
