### ISSUE TITLE
官网配置 hashPriority="high" 样式异常

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46606]
### Reproduction link

[https://ant.design](https://ant.design)

![image](https://github.com/ant-design/ant-design/assets/7971419/17dde57f-737d-4a2e-9487-74e0282dd019)

### Steps to reproduce

本地启动
在 `GlobalGlobalLayout` 配置 `hashPriority="high"`

### What is expected?

样式无问题

### What is actually happening?

样式有问题

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | latest |
| System | mac |
| Browser | chrome |

---
antd 既然支持 `:where` 降级，就需要把降级后的样式也适配好

**Comment by afc163** [comment]
codesandbox 中能重现么？

**Comment by crazyair** [comment]
> codesandbox 中能重现么？

这个是官网里的样式，不是 antd 组件的样式

**Comment by MadCcc** [comment]
官网不会开启 hashPriority，组件样式没问题就行
