### ISSUE TITLE
Table 组件报错。其他组件没有错误。并且TableColumnConfig 也找不到

### ISSUE THREAD

**Issue by lansefengxinzi** [ant-design/ant-design#4660]
Table 组件报错。其他组件没有错误。并且TableColumnConfig 也找不到

![03c15fa6-98e4-4a97-b91d-049a04c64f0a](https://cloud.githubusercontent.com/assets/12048313/22140367/00bb02f8-df27-11e6-9d7a-07c48c0cbadd.png)
![536fd73f-c912-4e6e-ab1e-5eba8ce56cda](https://cloud.githubusercontent.com/assets/12048313/22140440/7880b8b4-df27-11e6-8ed0-3ca8b67b6911.png)

**Comment by afc163** [comment]
1. https://github.com/ant-design/ant-design#typescript
2. @yesmeck 看看

**Comment by yesmeck** [comment]
😢 [这里](https://github.com/ant-design/ant-design/commit/ed455c01d19891b4365ff19aac7f3bde5601edc1)不知不觉搞了个 breaking change 。。。

**Comment by yesmeck** [comment]
@lansefengxinzi 临时的方案是 `import { ColumnProps }  from 'antd/lib/table/Columns'`;

**Comment by lansefengxinzi** [comment]
好的

**Comment by yesmeck** [comment]
2.6.4 发布了，可以正常 `import { TableColumnConfig } from 'antd/lib/table/Table';` 了。
