### ISSUE TITLE
树形控件 Tree，数据量少且存在滚动的时候，不显示滚动条，官网例子也存在这个问题。

### ISSUE THREAD

**Issue by zhang-xiaoyan** [ant-design/ant-design#46612]
### Reproduction link

https://codesandbox.io/p/devbox/tree-zu-jian-gun-dong-tiao-bu-xian-shi-li-zi-mmd6r7?file=%2Fsrc%2Ftree.js

### Steps to reproduce

官网虚拟滚动的例子，数据减少，会复现。

### What is expected?

出现滚动条

### What is actually happening?

未出现滚动条

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | windows |
| Browser | 谷歌浏览器 |

**Comment by yoyo837** [comment]
你的例子能看到滚动条呢？刚打开的时候会显示，过几秒会消失

**Comment by zhang-xiaoyan** [comment]
> 你的例子能看到滚动条呢？刚打开的时候会显示，过几秒会消失

这个是官网的例子，需要把例子中的 treeData={treeData} 中的 treeData 改少一些，就会出现。

**Comment by yoyo837** [comment]
> > 你的例子能看到滚动条呢？刚打开的时候会显示，过几秒会消失
> 
> 这个是官网的例子，需要把例子中的 treeData={treeData} 中的 treeData 改少一些，就会出现。

给个直接看效果的链接

**Comment by zhang-xiaoyan** [comment]
![1703495290494](https://github.com/ant-design/ant-design/assets/16955480/fe33d26a-66bd-4fbd-907a-f8aa562bd108)

**Comment by zhang-xiaoyan** [comment]
`
const data = [
  {
    title: "parent 0-0-0",
    key: "0-0-0",
    children: [
      {
        title: "parent 0-0-1",
        key: "0-0-1",
      },
      {
        title: "parent 0-0-2",
        key: "0-0-2",
      },
      {
        title: "parent 0-0-3",
        key: "0-0-3",
      },
      {
        title: "parent 0-0-4",
        key: "0-0-4",
      },
    ],
  },
];
`

**Comment by zhang-xiaoyan** [comment]
> Hello @zhang-xiaoyan. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @zhang-xiaoyan，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
链接如下
https://codesandbox.io/p/devbox/tree-zu-jian-gun-dong-tiao-bu-xian-shi-li-zi-mmd6r7?file=%2Fsrc%2Ftree.js

**Comment by zhang-xiaoyan** [comment]
> > > 你的例子能看到滚动条呢？刚打开的时候会显示，过几秒会消失
> > 
> > 
> > 这个是官网的例子，需要把例子中的 treeData={treeData} 中的 treeData 改少一些，就会出现。
> 
> 给个直接看效果的链接
下面链接可以直接打开：
https://codesandbox.io/p/devbox/tree-zu-jian-gun-dong-tiao-bu-xian-shi-li-zi-mmd6r7?file=%2Fsrc%2Ftree.js%3A4%2C1
我想确认一下，这个是问题还是做的优化
