### ISSUE TITLE
Replace deprecated box-sizing fix by a better one 

### ISSUE THREAD

**Issue by wozitto** [ant-design/ant-design#46617]
### What problem does this feature solve?

Current implementation of box-sizing in Ant Design uses the global selector (ref: https://github.com/ant-design/ant-design/blob/e07d5214c409533407b99a556c0c966fd014e5a7/components/style/reset.css#L11C1-L15C2), which can cause difficulties in overriding this property for specific elements. This leads to limitations in component customization and potential layout issues.

### What does the proposed API look like?

Propose to change the box-sizing approach to:
```
html {
  box-sizing: border-box;
}
*, *::before, *::after {
  box-sizing: inherit;
}
```
Even Paul Irish, original author of the fix currently part of modern-normalize, has agreed on this and edited his origjnal post back from 2021: https://www.paulirish.com/2012/box-sizing-border-box-ftw/
This method allows easier customization of box-sizing on specific elements, aligning with modern CSS best practices and improving maintainability and flexibility of Ant Design components.

**Comment by MadCcc** [comment]
This may cause breaking change. We have been using this `reset.css` for a long time, this file is part of full styles of antd 4.x.
So we may not accept this PR and you could use your own css file to reset browser's default style.

Thank you all the same.
