### ISSUE TITLE
message.info 放在外面 执行 npm run test-node 报错

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46626]
### Reproduction link

[https://github.com/ant-design/ant-design/pull/46625](https://github.com/ant-design/ant-design/pull/46625)

### Steps to reproduce

本地执行 `npm run test-node`

### What is expected?

不报错

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | latest |
| System | mac |
| Browser | chrome |

---
```
 node › message › components/message/demo/info.tsx

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: document is not defined
```

**Comment by MadCcc** [comment]
这是预期的呀，node 环境没有 document
