### ISSUE TITLE
RangePicker设置指定value值后，日期面板未同步跳到指定日期区间，但实际日期区间是选中的，偶尔会生效，大部分不生效，求具体原因

### ISSUE THREAD

**Issue by xinjiahuan** [ant-design/ant-design#46621]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/dank-brook-v1csy)

### Steps to reproduce

A页面
 const [year, setYear] = useState<string>(dayjs().format('YYYY'));
 const [diff, setDiff] = useState(0);
          <DatePicker
              picker="year"
              value={dayjs(year)}
              onChange={handleChangeYear}
              allowClear={false}
              disabledDate={handleDisabledDate}
              suffixIcon={<CaretDownOutlined />}
            /> 

  const handleChangeYear = (date: Dayjs | null, dateString: string) => {
    setYear(dateString);
    const _diff = dayjs(year).diff(dateString, 'year');
    setDiff(_diff);
  };

B页面：传递diff给B页面，B页面的日期需要根据A页面选的年份变化
const dateFormat = 'YYYYMMDD';
  const [date, setDate] = useState({
    dateStart: dayjs().startOf('year').format(dateFormat),
    dateEnd: dayjs().format(dateFormat),
  });

  useEffect(() => {
    const _date = {
      dateStart: dayjs(date.dateStart).add(-diff, 'year').format(dateFormat),
      dateEnd: dayjs(date.dateEnd).add(-diff, 'year').format(dateFormat),
    };
    setDate(_date);
  }, [diff]);

// 当天及以前日期不可选择
  const disabledDate: RangePickerProps['disabledDate'] = (current) => {
    return (
      (current && current > dayjs().endOf('day')) ||
      (current && current >= dayjs(year).add(1, 'year').startOf('year')) ||
      (current && current < dayjs(year).subtract(1, 'year').endOf('year'))
    );
  }; 

<RangePicker
          disabledDate={disabledDate}
          value={[
            dayjs(date.dateStart, dateFormat),
            dayjs(date.dateEnd, dateFormat),
          ]}
          onChange={handleChange}
          allowClear={false}
          
          // format={['MM-DD', 'MM-DD']}
        />

### What is expected?

日期面板能够切换至跟指定的value值匹配，例如：我指定日期是20200101～20200110，那么面板选中20200101～20200110区间，且打开日期面板时显示的是当前选中的区间页面

### What is actually happening?

我指定日期是20200101～20200110，面板选中的也是20200101～20200110区间，但是打开日期面板时显示的是实际日期（例如今天是20231226，显示的是20231226周边的日期面板），不是当前选中的区间页面

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.45 |
| System | MAC OS ventura 13.5 |
| Browser | chrome 120.0.6099.109 |

**Comment by xinjiahuan** [comment]
打开时
![image](https://github.com/ant-design/ant-design/assets/110023514/04350781-19c9-4455-a6d1-15c5a99c8da1)
实际已经选中了，只是没有切换到这里
![image](https://github.com/ant-design/ant-design/assets/110023514/1b137117-28b7-467d-ac2d-7daa50e1ca92)

**Comment by xinjiahuan** [comment]
**### 但是奇怪的是，我写了两个一摸一样的组件，第一次点开面板的时候，一个切换到了一个没切换到
代码：**
![image](https://github.com/ant-design/ant-design/assets/110023514/3ecf1046-8555-459a-be00-2ac7d066a25c)


### 左面板第一打开
![image](https://github.com/ant-design/ant-design/assets/110023514/04630e0d-5390-4fc5-9332-423b63b09b88)
### 右面板第一打开
![image](https://github.com/ant-design/ant-design/assets/110023514/de81d22a-923a-486a-a184-7f8bc7699859)

### 明明是一样的代码，展示的缺不同

**Comment by afc163** [comment]
你提供的 codesandbox 貌似和问题貌似没什么关系？

**Comment by wangkemin** [comment]
我也遇到了这个问题，楼主你解决了吗
