### ISSUE TITLE
ConfigProvider 设置 iconPrefixCls 失效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46628]
### Reproduction link

[https://github.com/ant-design/ant-design/pull/46627](https://github.com/ant-design/ant-design/pull/46627)

![image](https://github.com/ant-design/ant-design/assets/7971419/5f77ce10-60ae-4d7a-99ed-0e92e6d60863)

### Steps to reproduce

本地执行 `npm start`

### What is expected?

iconPrefixCls 正确设置

### What is actually happening?

iconPrefixCls 无法设置

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
复现就是 https://github.com/ant-design/ant-design/pull/46627 这个 pr，checkout 到本地复现下

**Comment by yoyo837** [comment]
优先建议在线的复现，在线的实在无法复现得出来，才其他方式。

**Comment by crazyair** [comment]
> 优先建议在线的复现，在线的实在无法复现得出来，才其他方式。

这个代码在 codesendbox 看了没问题
![image](https://github.com/ant-design/ant-design/assets/7971419/ea1d1d79-a0ad-444d-a405-bc6ef5b4107b)

```tsx
import React from 'react';
import { ExclamationCircleFilled } from '@ant-design/icons';
import { Button, ConfigProvider } from 'antd';

const App: React.FC = () => (
  <ConfigProvider iconPrefixCls="aaaa" prefixCls="bbb">
    <ExclamationCircleFilled />
    <Button>aaaa</Button>
  </ConfigProvider>
);

export default App;

```

**Comment by yoyo837** [comment]
<img width="1196" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/ced5fda0-bbbe-445b-95c3-260ba3de2c62">

你的demo我本地运行正常

**Comment by crazyair** [comment]
> <img alt="image" width="1196" src="https://private-user-images.githubusercontent.com/6134547/292801759-ced5fda0-bbbe-445b-95c3-260ba3de2c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NjM0OTUsIm5iZiI6MTcwMzU2MzE5NSwicGF0aCI6Ii82MTM0NTQ3LzI5MjgwMTc1OS1jZWQ1ZmRhMC1iYmJlLTQ0NWItOTVjMy0yNjBiYTNkZTJjNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjZUMDM1OTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3NjBhNzQ1NTU5MDZiNTEzZDU2ZjE0MjY0ZDkzZGY2YjI1OTRlNDk3ZjMzZDBlNzgzNzdiYmNhODlkNDdkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lH62crABK8sUZO5vmxxj-HZ5sJwD4T7rvJ06KaZiY0I">
> 你的demo我本地运行正常

在 antd 里

**Comment by crazyair** [comment]
https://github.com/ant-design/ant-design/pull/46627
