### ISSUE TITLE
DatePicker.RangePicker 中设置open属性，在频繁切换日期时，会出现某个选相框值不能显示, 4的版本会有这个问题，5的版本不会有问题

### ISSUE THREAD

**Issue by damon-cheng** [ant-design/ant-design#46624]
### Reproduction link

[https://codepen.io/damon-cheng/pen/KKEwXWa?editors=001](https://codepen.io/damon-cheng/pen/KKEwXWa?editors=001)

### Steps to reproduce

多次切换选择时间，某个选择框不会显示时间

### What is expected?

不管选择多少次时间，两个选择框都要有时间值

### What is actually happening?

某个选择框不会显示时间

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 18.0.37 |
| System | macOS Ventura 13.4.1 |
| Browser | chrome 120.0.6099.109 |

**Comment by MadCcc** [comment]
Fixed in v5
