### ISSUE TITLE
表头固定时，更改页面缩放比例表头和表格错位

### ISSUE THREAD

**Issue by josie-l-li** [ant-design/ant-design#46632]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z6lklv?file=/index.js)

### Steps to reproduce

更改页面的缩放比例

### What is expected?

无论页面比例怎么更改，表格与表格都不会错位

### What is actually happening?

更改页面缩放比例表头和表格错位

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | windows |
| Browser | Google |

**Comment by afc163** [comment]
错位在哪，我好像没发现？

<img width="1728" alt="截屏2023-12-26 13 25 10" src="https://github.com/ant-design/ant-design/assets/507615/563c9576-e963-4791-9cc1-b7d850b980d5">

**Comment by josie-l-li** [comment]
可以缩小比例试试
![image](https://github.com/ant-design/ant-design/assets/140794953/27775f10-b3a0-45d7-adf9-35f0b207e095)

**Comment by MadCcc** [comment]
因为自定义 css 的部分产生了错位，建议自行排查一下
