### ISSUE TITLE
Form component lags during browser window width adjustment

### ISSUE THREAD

**Issue by Rolaka** [ant-design/ant-design#46631]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/table-bug-antd-5-12-5-forked-94p3rn)

### Steps to reproduce

- Set the pagination attribute of the form component to false.
- Add about 10,000 pieces of data.

And then adjust the width of the browser form.

### What is expected?

browser without lag

### What is actually happening?

browser lag

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | react 18 |
| System | windows 11 |
| Browser | chrome 120 |

**Comment by Rolaka** [comment]
![bug](https://github.com/ant-design/ant-design/assets/839943/da781928-b1cd-4120-9462-ac6f9d9e5020)
i7-12700, 16g ram

**Comment by MadCcc** [comment]
Try `virtual` for large data.
