### ISSUE TITLE
tableRef Illegal invocation

### ISSUE THREAD

**Issue by angry-day** [ant-design/ant-design#46635]
![image](https://github.com/ant-design/ant-design/assets/72498747/0f0b7960-07f1-4157-a97d-1ee9a950bbd5)

### Steps to reproduce

1、选择包含useProxyImperativeHandle hook的版本
2、使用Ref获取Table中的dom
3、使用ref对table进行dom检索

### What is expected?

能通过ref对dom进行正常操作

### What is actually happening?

得到illegal invocation的报错

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 17.0.2 |
| System | window |
| Browser | chorme |

**Comment by angry-day** [comment]
<iframe src="https://codesandbox.io/embed/m3wj7z?view=Editor+%2B+Preview&module=%2Findex.js&expanddevtools=1"
     style="width:100%; height: 500px; border:0; border-radius: 4px; overflow:hidden;"
     title="antd reproduction template (forked)"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by angry-day** [comment]
https://codesandbox.io/embed/m3wj7z?view=Editor+%2B+Preview&module=%2Findex.js&expanddevtools=1

**Comment by MadCcc** [comment]
Use `tableRef.current.nativeElement`

**Comment by zhengweipx** [comment]
Use tableRef.current.nativeElement, is good!
