### ISSUE TITLE
表头固定时，更改页面缩放比例表头和表格错位

### ISSUE THREAD

**Issue by josie-l-li** [ant-design/ant-design#46642]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-z6lklv?file=%2Findex.js%3A19%2C33)

### Steps to reproduce

在没有设置css的情况下缩小浏览器比例仍然出现错位的问题

### What is expected?

表格与表头不错位

### What is actually happening?

表格与表头错位

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | windows |
| Browser | google |

---
之前说是自己设置的css导致的，但是去除样式问题仍然存在

**Comment by josie-l-li** [comment]
![image](https://github.com/ant-design/ant-design/assets/140794953/c210bbb6-a21c-458e-a4d3-7cea3e2629ad)

**Comment by zombieJ** [comment]
Table 固定表头通过测量 tbody 的 columns 宽度来映射到 thead 的 column 上。当缩放时，游览器提供的数据与实际渲染是不同的，在代码侧**无法感知**精度差异。你可以写死 columns 宽度来减少差异，但是这仍然无法避免。
