### ISSUE TITLE
在drawer中使用steps组件导致drawer组件重复渲染

### ISSUE THREAD

**Issue by AllianceTing** [ant-design/ant-design#46648]
### Steps to reproduce

import React, { useEffect } from 'react';

import { Button, Drawer, Steps, theme } from 'antd';
import {  WithDSteps } from '../middle/Steps';
import {
  createFromIconfontCN,
  LoadingOutlined,
  SmileOutlined,
  SolutionOutlined, ThunderboltTwoTone,
  UserOutlined,
} from '@ant-design/icons';

const IconFont = createFromIconfontCN({
  scriptUrl: [
    '//at.alicdn.com/t/font_1788044_0dwu4guekcwr.js', // icon-javascript, icon-java, icon-shoppingcart (overridden)
    '//at.alicdn.com/t/font_1788592_a5xf2bdic3u.js', // icon-shoppingcart, icon-python
  ],
});

// todo 动态的修改
const steps =[
  {
    title: 'Wait',
    description:'链路前置校验...',
    icon: <ThunderboltTwoTone />,
    content:'AQCC',
    percent:40
  },
  {
    title: 'Verification',
    description: '用户信息资质校验...',
    icon: <SolutionOutlined />,
    percent:80
  },
  {
    title: 'Pay',
    description: '执行链路测试...',
    icon: <SolutionOutlined />,
  },
  {
    title: 'Done',
    icon: <SmileOutlined />,
  },
]
function WithProDrawer() {
  return function WithProDrawerComponent() {
    const [open, setOpen] = React.useState(false);
    const onClose = () => {
      setOpen(false);
    };
    const onOpen = () => {
      setOpen(false);
    };
    const [node,setNode] = React.useState(0)
    const { token } = theme.useToken();
    const [current, setCurrent] = React.useState(0);
    const contentStyle = {
      lineHeight: '260px',
      textAlign: 'center',
      color: token.colorTextTertiary,
      backgroundColor: token.colorFillAlter,
      borderRadius: token.borderRadiusLG,
      border: `1px dashed ${token.colorBorder}`,
      marginTop: 16,
    };
    const next = () => {
      setCurrent(current   1);
    };
    const prev = () => {
      setCurrent(current - 1);
    };
    return (
      <>
        <Drawer
          title="Basic Drawer"
          placement="top"
          closable={false}
          onClose={onClose}
          open={onOpen}
        >
          <Steps current={current} items={steps} />
          <div style={contentStyle}>{steps[current].content}</div>
          <div style={{ marginTop: 24 }}>
            {current < steps.length - 1 && (
              <Button type="primary" onClick={() => next()}>
                Next
              </Button>
            )}
            {current === steps.length - 1 && (
              <Button type="primary" onClick={() => message.success('Processing complete!')}>
                Done
              </Button>
            )}
            {current < steps.length && (
              <Button style={{ margin: '0 8px' }} onClick={() => prev()}>
                Previous
              </Button>
            )}
          </div>
          {/*<div>*/}
          {/*  {*/}
          {/*    (() => {*/}
          {/*      switch (node) {*/}
          {/*        case 1:*/}
          {/*          return <div>1</div>*/}
          {/*        case 2:*/}
          {/*          return <div>2</div>*/}
          {/*        case 3:*/}
          {/*          return <div>3</div>*/}
          {/*        case 4:*/}
          {/*          return <div>4</div>*/}
          {/*        case 0:*/}
          {/*          return <div>0</div>*/}
          {/*      }*/}
          {/*    })()*/}
          {/*  }*/}
          {/*</div>*/}
        </Drawer>
      </>
    );
  };
}

export default WithProDrawer;

### What is expected?

steps组件步进到下一个的时候drawer不应该重复刷新

### What is actually happening?

steps组件步进到下一个的时候drawer重复刷新

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by cbingrui** [comment]
Encountered a similar issue (Popover cannot directly contain IconFont), a temporary solution is to wrap the IconFont in an additional span
