### ISSUE TITLE
Form.List 嵌套Table触发校验后，再把原来的行删除，其余的校验会清空

### ISSUE THREAD

**Issue by huangruoliang** [ant-design/ant-design#46651]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/jolly-snowflake-r32wqx?file=%2Fpackage.json%3A1%2C2)

### Steps to reproduce

先添加几条数据，第一列blur后触发校验，数据未填写，然后删除删除第一条数据，其余的校验全都被清空

### What is expected?

希望其余的err信息保存

### What is actually happening?

其余的err信息被清空

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | react |
| System | mac |
| Browser | chrome120.0.6099.109 |

**Comment by zombieJ** [comment]
`setFieldsValue` 默认为清理数据以及校验信息。通过 `getFieldsError` 把路径对应的错误提出来，然后再通过 `setFields` 填回裁剪过的信息即可。

**Comment by huangruoliang** [comment]
> `setFieldsValue` 默认为清理数据以及校验信息。通过 `getFieldsError` 把路径对应的错误提出来，然后再通过 `setFields` 填回裁剪过的信息即可。
我即使把setFieldsValue去掉还是会有相同的问题

**Comment by Sheepeer** [comment]
有解决方法了吗？遇到了同样的问题
