### ISSUE TITLE
【Select-renderDropDown】在renderDropDown内写一个input时， 删除input搜索框内容会触发select已选择内容的删除。

### ISSUE THREAD

**Issue by marong1997** [ant-design/ant-design#46655]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-9szh6k?file=%2Findex.js)

### Steps to reproduce

点击多选框， 全选之后 在搜索框内进行搜索 再删除 会删除已选择的项

### What is expected?

期望删除input框内容 不会删除

### What is actually happening?

期望不会删除已选择的select项

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 17 |
| System | windows |
| Browser | google120.0.6099.111 |

**Comment by yoyo837** [comment]
<img width="424" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/d74f6044-8be3-48d1-8673-7c47228e5e75">

是不是还没弄好

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/28694#issuecomment-754471826
