### ISSUE TITLE
Modal下使用allow clear，会触发额外的点击

### ISSUE THREAD

**Issue by manzxiao** [ant-design/ant-design#46669]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-47rv7m?file=%2Findex.js)

### Steps to reproduce

选择时间，再点击上面的clear按钮，

### What is expected?

时间不该被清除了

### What is actually happening?

时间也被清除了

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
= =，有意思。上面删除的时候。正好下面的挪上去，导致鼠标正好在 clear 按钮上，触发了 onMouseUp 事件。

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/picker/pull/711
