### ISSUE TITLE
Warning: Failed prop type: Invalid prop `value` supplied to `Select`.

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#4666]
![qq 20170120180611](https://cloud.githubusercontent.com/assets/11780264/22145188/46380cf4-df3b-11e6-93e3-010ca2f49863.png)
![qq 20170120180800](https://cloud.githubusercontent.com/assets/11780264/22145222/6502bb02-df3b-11e6-91c0-7ae13990db12.png)

**Comment by XUGAOBO** [comment]
选择某个option的时候报waring

**Comment by afc163** [comment]
提示已经很清晰了。`Warning: Failed prop type: Invalid prop `value` supplied to `Select`.`

Option.value 的值只能是 string 类型，文档里也是这么写的。

**Comment by XUGAOBO** [comment]
我的option是这样的
<Option key='act_log'>act_log</Option>
<Option key='act_log1'>act_log1</Option>
文档中说如果key和value一致,那么则可以省略value设置

**Comment by XUGAOBO** [comment]
[<Option key='act_log'>act_log</Option>,<Option key='act_log1'>act_log1</Option>]

**Comment by XUGAOBO** [comment]
"Option key='act_log'act_log /Option"

**Comment by afc163** [comment]
selectItems 是什么，贴出来看看。

**Comment by XUGAOBO** [comment]
![qq 20170120183513](https://cloud.githubusercontent.com/assets/11780264/22146322/355a9c04-df3f-11e6-8fc5-05f02a0bedf4.png)

**Comment by afc163** [comment]
你把源码打出来。。。。

或者最好直接给一个可重现的 demo：http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
selectItemsArr 的 66 项里，肯定有 key 不是 string。

**Comment by XUGAOBO** [comment]
我先重现下

**Comment by XUGAOBO** [comment]
找到原因了，不好意思，界面form表单中有个select值为number

**Comment by ligaofeng0901** [comment]
为什么Select的Option的value必须为String类型呢？这样就导致Select也只能使用string类型的值，实际场景中经常会有是number的情况，而Radio的value却能支持任意类型。实际使用中给Select设置number类型的值也没问题，就是有类型检查的警告看着很别扭。

**Comment by afc163** [comment]
@ligaofeng0901 

trace https://github.com/ant-design/ant-design/issues/2857 and https://github.com/react-component/select/pull/229

**Comment by yuexing0921** [comment]
我就是按照你们的例子来，都会报这个错误
`
import {
	Button,
	Form,
	Input,
	Select,
	Row,
	Col
} from "antd";
const children = [];
for (let i = 10; i < 36; i++) {
  children.push(<Option key={i.toString(36) + i}>{i.toString(36) + i}</Option>);
}

class App extends Component {
	handleSelectChange = (value) => {
		console.log(value);
	}
	render() {
		
		return (
		<div className={style.warp}>
			<div className={style.content}>
				<Form >
					<FormItem
						label="选择"
						labelCol={{span: 8}}
						wrapperCol={{span: 4}}
					>
						{getFieldDecorator("mode", {

							initialValue: {mode},
							rules: [
								{
									required: true,
									message: "请选择对应的选项!"
								}
							]
						})(
							<Select placeholder="请选择对应的选项"	onChange={this.handleSelectChange}>
								{children}
							</Select>

						)}
					</FormItem>
					
				</Form>
			</div>
		</div>

		);
	}
}

`
version：2.12.6

**Comment by zhalice2011** [comment]
我的Select的Option的value是Object就报错

**Comment by RixBai** [comment]
@afc163 How is it when the `mode` is `multiple`? In this case the value should be an array, right?
Then we will get the warning?

**Comment by akarsh** [comment]
@afc163 this issue is not solved I tried with the example from the documentation like @yuexing0921 

i am using `"antd": "^3.26.7"`
