### ISSUE TITLE
去掉:where选择器之后，hashId还在，默认的css优先级会高于业务侧css优先级，无法进行样式覆盖

### ISSUE THREAD

**Issue by wdyea-ya** [ant-design/ant-design#46668]
### What problem does this feature solve?

想兼容低版本浏览器，通过设置 hashPriority="high"之后去掉:where选择器之后，hashId会提高antd样式的优先级，原本需要进行覆盖的样式就不生效了。
官网文档给出的解法是PostCSS 插件提升应用样式的优先级，但是我们使用的css modules，目前无法通过加上id选择器来提升优先级

### What does the proposed API look like?

设置 hashPriority = 'high' 可以一并去掉hashId

**Comment by zombieJ** [comment]
参考文档 [关闭 hash](https://ant-design.antgroup.com/docs/react/css-variables-cn#%E5%85%B3%E9%97%AD-hash)

**Comment by wdyea-ya** [comment]
@zombieJ 尝试过使用 theme.hashed = false 来关闭hashId，但是没有生效
