### ISSUE TITLE
定制主题后 Modal组件中按钮没有生效

### ISSUE THREAD

**Issue by W-stardust** [ant-design/ant-design#46678]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qwdfxl?file=%2Findex.js%3A46%2C28-46%2C35)

### Steps to reproduce

自定义theme 定制主题后 Modal组件中按钮颜色没有生效

### What is expected?

自定义theme 定制主题后 Modal组件中按钮主题是定制后的

### What is actually happening?

自定义theme 定制主题后 Modal组件中按钮颜色没有生效

| Environment | Info |
| --- | --- |
| antd | 5.11.4 |
| React | react |
| System | win/mac |
| Browser | 谷歌 |

**Comment by crazyair** [comment]
还需要单独设置 `ConfigProvider.config({ theme })`

**Comment by afc163** [comment]
不建议用 ConfigProvider.config ，应该用 hooks 版本的 `Modal.xxx`：https://ant.design/docs/react/faq-cn#configprovider-%E8%AE%BE%E7%BD%AE-prefixcls-%E5%90%8Emessagenotificationmodalconfirm-%E7%94%9F%E6%88%90%E7%9A%84%E8%8A%82%E7%82%B9%E6%A0%B7%E5%BC%8F%E4%B8%A2%E5%A4%B1%E4%BA%86

**Comment by k4281613** [comment]
antd4原本可以直接在普通函数里面调用的，使用hooks版本的还需要改原本的函数，多了升级成本了

**Comment by crazyair** [comment]
> antd4原本可以直接在普通函数里面调用的，使用hooks版本的还需要改原本的函数，多了升级成本了

https://ant-design.antgroup.com/components/app-cn#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF
