### ISSUE TITLE
通过theme修改主题，自定义组件样式未生效

### ISSUE THREAD

**Issue by 457375608** [ant-design/ant-design#46673]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/jz3dxk?file=%2Fsrc%2FApp.tsx%3A11%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqolss980006356hnq9arily%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqolss980002356haeo1kemc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqolss980003356h0k3m201k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqolss980005356hltqk6m38%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqolss980002356haeo1kemc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqolss970001356ha9lr4hin%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqom9z640002356hfqgz4y95%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqolss980002356haeo1kemc%2522%252C%2522activeTabId%2522%253A%2522clqom9z640002356hfqgz4y95%2522%257D%252C%2522clqolss980005356hltqk6m38%2522%253A%257B%2522id%2522%253A%2522clqolss980005356hltqk6m38%2522%252C%2522activeTabId%2522%253A%2522clqolvkry008h356hk4yihfvm%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqolvkry008h356hk4yihfvm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqolss980003356h0k3m201k%2522%253A%257B%2522id%2522%253A%2522clqolss980003356h0k3m201k%2522%252C%2522activeTabId%2522%253A%2522clqolw7kd00ct356hqj3f055l%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clqolvftv006v356h3z825dqj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clqolw7kd00ct356hqj3f055l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqolw7kf000peei060vmhs9p%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

input输入框hover，或者focus状态下，输入框下边框颜色渲染错误

### What is expected?

    <ConfigProvider
      theme={{
        token: {
          borderRadius: 0,
          colorPrimary: "orange",
        },
      }}

期望是上面设置的: 'orange'

### What is actually happening?

input下边框颜色实际是antd自带打默认值：'#1677ff'，按钮的颜色样式符合预期

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React |   "react": "18.2.0",     "react-dom": "18.2.0", |
| System | Windows 10  |
| Browser | 版本 120.0.6099.111（正式版本） （64 位 |

**Comment by 457375608** [comment]
![微信截图_20231228113311](https://github.com/ant-design/ant-design/assets/8923244/abfebb68-6e13-4184-8af4-3409a56d855f)

**Comment by afc163** [comment]
See https://codesandbox.io/p/devbox/antd-theme-forked-d9y7rc?file=%2Fsrc%2FApp.tsx%3A38%2C15
