### ISSUE TITLE
Tabs editable-card 点击 tab 列表某一项后，内容未显示

### ISSUE THREAD

**Issue by Jacleklm** [ant-design/ant-design#46677]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-tab-bug-demo-8hly72?file=%2Fpackage.json%3A5%2C18)

### Steps to reproduce

当 tab 数量较多时，会隐藏 tab 并在右边悬浮后出现一个 tab 列表（如 sandbox 所示）。点击列表中靠后的 tab，tabpane 显示为空，没有渲染该有的内容
![image](https://github.com/ant-design/ant-design/assets/50861119/60414876-5136-4f2a-b6db-ca203583b48c)
![image](https://github.com/ant-design/ant-design/assets/50861119/50778f9c-5e4b-4e93-adf6-8f61734ea2a7)

### What is expected?

tabpane 不为空，能渲染内容

### What is actually happening?

点击这个case 中的 tab10 到 tab18，下面的 tabpane 为空

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18 |
| System | Ubuntu 20.04.6 LTS |
| Browser | chrome最新版 |

**Comment by MadCcc** [comment]
`key` 使用 `string` 类型。下拉框可能内部转换数字有问题

**Comment by Jacleklm** [comment]
key 使用 string 类型后确实没问题了，多谢

**Comment by MadCcc** [comment]
这个问题是由于 Menu 的 key 会在内部转换为 string 类型，与初始的 number 类型不一致。
但是 key 类型在文档中为 `string`，ts 类型也没有 number 的用法，先关闭了。
