### ISSUE TITLE
Tour 's mask is not working properly - while zoom out the page (below to 100%)

### ISSUE THREAD

**Issue by Upanshu07Sharma** [ant-design/ant-design#46679]
### Reproduction link

[https://7wylht-3000.csb.app/](https://7wylht-3000.csb.app/)

### Steps to reproduce

1- Open the given url in the safari browser.
2- Start the tour by clicking over begin tour button
3- when tour start,    zoom out the screen size (below 100%)
4- Tour mask not cover the whole screen .

### What is expected?

1- Tour mask should cover whole screen even after zoom out (below 100%) on safari.
2- Working as expected on Chrome browser

### What is actually happening?

1- on Safari browser, Tour mask is not covering whole screen while zooming out (below 100%) 

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | Macbook pro |
| Browser | Safari |

**Comment by MadCcc** [comment]
Didn't get reproduced, could you give more details?

**Comment by Upanshu07Sharma** [comment]
step 1): open the given reproduction link into safari browser
step 2): start the tour by clicking over begin tour button
step 3): now, set screen zoom level below 100% 
step 4): you will observe that - Tour mask will not work properly. It will cover only few portion of whole screen.

please see the recorded video : [google drive link](https://drive.google.com/file/d/1Ox2dN10YkaMUGw8loL-l29FCCWT_DxNy/view?usp=drive_link)

Thanks @MadCcc
