### ISSUE TITLE
Card ConfigProvider not working

### ISSUE THREAD

**Issue by GalDayan** [ant-design/ant-design#46689]
### Steps to reproduce
```
export const antTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: colors.indigo?.primary,
    fontFamily: "Inter",
  },
  components: {
    Card: {
      boxShadow: "5px 8px 24px 5px rgba(208, 216, 243, 0.6)"
    }
  }
};
```
### What is expected?

boxShadow affects on all <Card /> instances

### What is actually happening?

boxShadow is not affected in any <Card /> usage

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | ^18 |
| System | Chrome |
| Browser | Chrome  |

**Comment by MadCcc** [comment]
Card do not use `boxShadow`, instead, it use `boxShadowTertiary`.
You can check which token is used in https://ant.design/components/card#design-token
