### ISSUE TITLE
QRCode组件的status是否可以增加已扫描状态或者通过status自定义遮罩上展示的文字、按钮、图标等

### ISSUE THREAD

**Issue by selicens** [ant-design/ant-design#46694]
### What problem does this feature solve?

一些场景下，二维码被扫描后，就希望不再被重复扫描

### What does the proposed API look like?

现有status选项为active | expired | loading，可以增加一个scan状态或者status可以自定义如:
```js
<QRCode status={<div>已扫描</div>} />
```

**Comment by Wxh16144** [comment]
加一个 `mask` props 可能更合适🤔

**Comment by selicens** [comment]
> 加一个 `mask` props 可能更合适🤔

也不是不行

**Comment by li-jia-nan** [comment]
可以加个 scan 状态，mask props 先不加，等后面有需求了再说

**Comment by afc163** [comment]
scaned

**Comment by li-jia-nan** [comment]
> scaned

这个文案应该要做一下国际化

**Comment by selicens** [comment]
wow，真快啊

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/46704
