### ISSUE TITLE
antd的Calendar日历组件自定义头部添加今天按钮会导致点击今天之后所有日期被选中并且移动到日期上面还会自动变化 

### ISSUE THREAD

**Issue by yiqiui** [ant-design/ant-design#46690]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

export const ProjectCalendar = () => {
  // 自定义渲染函数
  const renderHeader = (config: any) => {
    const { value, onChange } = config;

    // 自定义标题
    var title = `${value.year()}年 ${value.month()   1}月`;
    if(g.lang === "en"){
      const month = getMonthAbbreviation(value.month()   1)
      title = `${month} ${value.year()}`;
    }

    // 自定义操作按钮
    //今天
    const today = () => {
      const today = moment();
      console.log(value)
      console.log(today)
      onChange(today);
    };

    //上个月
    const prevMonth = () => {
      onChange(value.clone().subtract(1, 'month'));
    };

    //下个月
    const nextMonth = () => {
      onChange(value.clone().add(1, 'month'));
    };

    return (
      <div style={{ marginRight: "20px", textAlign: "right" }}>
        <span 
          onClick={today}
        >
          <Button size={"small"}>今天</Button>
        </span>
        <span 
          onClick={prevMonth} 
          style={{marginLeft: 20,cursor: "pointer", width:30, height: 30, backgroundColor: iconColor === 0?"#FFFFFF":"#F0F2F5" }} 
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
        > 
          <svg className="iconfont" width={24} height={24} style={{marginBottom:"-7px"}}>
              <use xlinkHref="#icon-zuo"></use>
          </svg>
        </span>
        <span 
          style={{
            color: "#1D2129",
            fontSize: "16px",
            fontWeight: 700,
            lineHeight: "19px",
            letterSpacing: "1px",
            textAlign: "left",
          }}
        >
          {title}
        </span>
        <span 
          onClick={nextMonth} 
          style={{cursor: "pointer", width:30, height: 30, backgroundColor: iconColor === 0?"#FFFFFF":"#F0F2F5" }} 
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
        > 
          <svg className="iconfont" width={24} height={24} style={{marginBottom:"-7px"}}>
              <use xlinkHref="#icon-you"></use>
          </svg>
        </span>
      </div>
    );
  };
    return (
        <>
          <Card headStyle={{ padding: "0 16px" }} bodyStyle={{ padding: "16px" }} title={
              <Row justify={"space-between"} align="middle">
                  <Row align="middle">
                      <Title name={formatMessage({id: 'project.visit.cycle.calendar'})}/>
                  </Row>
              </Row>
            }
          >
            <Calendar headerRender={renderHeader} dateCellRender={dateCellRender} monthCellRender={monthCellRender} />
          </Card>
        </>
    )
}
期中引用的是自定义的Calendar 

### What is expected?

期望点击今天可以正常锚定到今天

### What is actually happening?

实际是所有日期都被选择

| Environment | Info |
| --- | --- |
| antd | 4.24.1 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome版本 120.0.6099.130（正式版本） （64 位） |

**Comment by yiqiui** [comment]
export const ProjectCalendar = () => {
  const g = useGlobal()
  const intl = useIntl();
  const {formatMessage} = intl;
  const auth = useAuth()
  const envId = auth.env ? auth.env.id : null;
  const [pieOption, setPieOption] = useSafeState<any>({});
  const [barOption, setBarOption] = useSafeState<any>({});
  const [pieType, setPieType] = useSafeState(0)
  const [barType, setBarType] = useSafeState(0)
  const pieRef = useRef<any>()
  const barRef = useRef<any>()
  const [endValue, setEndValue] = useState<number>(0);

  const [attribute, setAttribute] = useState<any>(null);
  const cohortIds = auth.env?.cohorts? auth.env?.cohorts : null
  const [cohortId, setCohortId] = useState<any>(null);
  const [iconColor, setIconColor] = useSafeState(0);
  const [currentValue, setCurrentValue] = useSafeState(moment());


  function getMonthAbbreviation(month: number) {
    const months: { [key: number]: string } = {
      1: "Jan",
      2: "Feb",
      3: "Mar",
      4: "Apr",
      5: "May",
      6: "Jun",
      7: "Jul",
      8: "Aug",
      9: "Sep",
      10: "Oct",
      11: "Nov",
      12: "Dec"
    };
  
    return months[month];
  }
    
  const handleMouseEnter = () => {
    setIconColor(1)
  };

  const handleMouseLeave = () => {
    setIconColor(0)
  };

  const getListData = (value: Moment) => {
    let listData;
    switch (value.date()) {
      case 8:
        listData = [
          { type: 'warning', content: 'This is warning event.' },
          { type: 'success', content: 'This is usual event.' },
        ];
        break;
      case 10:
        listData = [
          { type: 'warning', content: 'This is warning event.' },
          { type: 'success', content: 'This is usual event.' },
          { type: 'error', content: 'This is error event.' },
        ];
        break;
      case 15:
        listData = [
          { type: 'warning', content: 'This is warning event' },
          { type: 'success', content: 'This is very long usual event。。....' },
          { type: 'error', content: 'This is error event 1.' },
          { type: 'error', content: 'This is error event 2.' },
          { type: 'error', content: 'This is error event 3.' },
          { type: 'error', content: 'This is error event 4.' },
        ];
        break;
      default:
    }
    return listData || [];
  };
      
  const getMonthData = (value: Moment) => {
    if (value.month() === 8) {
      return 1394;
    }
  };

  function convertToReactNode(element: JSX.Element): ReactNode {
    return React.Children.toArray(element);
  }

  const monthCellRender = (value: Dayjs) => {
      const momentObj = moment(value.toDate());
      const num = getMonthData(momentObj);
      return num ? 
      convertToReactNode(
        <div className="notes-month">
          <section>{num}</section>
          <span>Backlog number</span>
        </div>
      ) : null;
  };
  
  const dateCellRender = (value: Dayjs) => {
    const momentObj = moment(value.toDate());
    const listData = getListData(momentObj);
    return (
      convertToReactNode(
        <ul className="events">
          {listData.map(item => (
            <li key={item.content}>
              <Badge status={item.type as BadgeProps['status']} text={item.content} />
            </li>
          ))}
        </ul>
      )
    );
  };

  // 自定义渲染函数
  const renderHeader = (config: any) => {
    const { value, onChange } = config;

    // 自定义标题
    var title = `${value.year()}年 ${value.month() + 1}月`;
    if(g.lang === "en"){
      const month = getMonthAbbreviation(value.month() + 1)
      title = `${month} ${value.year()}`;
    }

    // 自定义操作按钮
    //今天
    const today = () => {
      const today = moment();
      console.log(value)
      console.log(today)
      onChange(today);
    };

    //上个月
    const prevMonth = () => {
      onChange(value.clone().subtract(1, 'month'));
    };

    //下个月
    const nextMonth = () => {
      onChange(value.clone().add(1, 'month'));
    };

    return (
      <div style={{ marginRight: "20px", textAlign: "right" }}>
        <span 
          onClick={today}
        >
          <Button size={"small"}>今天</Button>
        </span>
        <span 
          onClick={prevMonth} 
          style={{marginLeft: 20,cursor: "pointer", width:30, height: 30, backgroundColor: iconColor === 0?"#FFFFFF":"#F0F2F5" }} 
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
        > 
          <svg className="iconfont" width={24} height={24} style={{marginBottom:"-7px"}}>
              <use xlinkHref="#icon-zuo"></use>
          </svg>
        </span>
        <span 
          style={{
            color: "#1D2129",
            fontSize: "16px",
            fontWeight: 700,
            lineHeight: "19px",
            letterSpacing: "1px",
            textAlign: "left",
          }}
        >
          {title}
        </span>
        <span 
          onClick={nextMonth} 
          style={{cursor: "pointer", width:30, height: 30, backgroundColor: iconColor === 0?"#FFFFFF":"#F0F2F5" }} 
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
        > 
          <svg className="iconfont" width={24} height={24} style={{marginBottom:"-7px"}}>
              <use xlinkHref="#icon-you"></use>
          </svg>
        </span>
      </div>
    );
  };


    return (
        <>
          <Card headStyle={{ padding: "0 16px" }} bodyStyle={{ padding: "16px" }} title={
              <Row justify={"space-between"} align="middle">
                  <Row align="middle">
                      <Title name={formatMessage({id: 'project.visit.cycle.calendar'})}/>
                  </Row>
              </Row>
            }
          >
            <Calendar headerRender={renderHeader} dateCellRender={dateCellRender} monthCellRender={monthCellRender} />
          </Card>
        </>
    )
}
期中引用的是自定义的Calendar 
const Calendar = generateCalendar<Dayjs>(dayjsGenerateConfig);

interface customCalendarProp {
    headerRender?: HeaderRender<any>;
    dateCellRender?: ((date: Dayjs) => ReactNode) | undefined;
    monthCellRender?: ((date: Dayjs) => ReactNode) | undefined;
    value?: Dayjs | undefined;
}

function customCalendar(props: customCalendarProp) {

  return (
    <div>
      <Calendar
        headerRender={props.headerRender}
        dateCellRender={props.dateCellRender}
        monthCellRender={props.monthCellRender}
        value={props.value}
      />
    </div>
  );
}

export default customCalendar;

**Comment by yiqiui** [comment]
> Hello @yiqiui. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @yiqiui，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

你可以复制上述代码来复现，谢谢

**Comment by yoyo837** [comment]
[什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F) 这样丢代码，让别人整理出来运行，也不一定能和你看到问题的效果一样，频繁来回交流，沟通成本大，每个人都这样丢代码，成员们不用生活工作了，全在想办法整理代码别人的代码了，请直接提供可访问的复现。

**Comment by yoyo837** [comment]
谢谢
