### ISSUE TITLE
Table: Custom Filter 

### ISSUE THREAD

**Issue by michshat** [ant-design/ant-design#4670]
I'm following this guide https://ant.design/components/table/#components-table-demo-custom-filter-panel when creating a custom filter. However in my case i'm using server side filtering. Question is when assigning value to column's `FilteredValue`, how can I trigger table `onChange` event?

If there was a way to tap into `handleConfirm`?

![image](https://cloud.githubusercontent.com/assets/13825309/22177300/08693368-dfe9-11e6-909f-cc41720084d7.png)

Thanks in advance.

**Comment by yesmeck** [comment]
That demo not using Table's built-in filter function, if you are filtering data by yourself, you don't need using `filteredValue`.

**Comment by yesmeck** [comment]
And for general support questions we recommend using [StackOverflow](http://stackoverflow.com/questions/tagged/antd).

**Comment by jch254** [comment]
I was wondering the same thing - my solution was to dispatch an action to fetch the latest data with the new filter value. All works well!

**Comment by chj-damon** [comment]
@jch254 what if I need to pass the pagination and sorters with my customize filter to the server? I see that Table has 'onChange' event which contains three parameters: pagination, filters, sorters. I was wondering if there is a way that I can trigger the 'onChange' event.
