### ISSUE TITLE
Transfer中如果是tree， 则搜索之后框顶部的counter不正确。

### ISSUE THREAD

**Issue by leslie555** [ant-design/ant-design#46706]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/shu-chuan-suo-kuang-sou-suo-23xpvr?file=%2Fsrc%2FTreeTransfer.jsx%3A5%2C21)

### Steps to reproduce

- 输入breast之后，面板顶部的计数器不正确

### What is expected?

计数器应该显示2项， 或者显示1，但是当选择了筛选结果之后， 所选项不应该大于total count

### What is actually happening?

selected count is gt total count

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | macOS 14 |
| Browser | chrome v120 |

**Comment by leslie555** [comment]
经过仔细的一番研究，发现`selectAllLabels`属性 可以自己操控顶部的counter， 稍后空了更新下状态

**Comment by leslie555** [comment]
最新代码已更新到**codesandbox**, 算是一个比较完整的2级树穿梭

**Comment by LINGyue-dot** [comment]
昨天看了你之前的代码，改一下这个函数就可以正常 work
[![Edit 树穿梭框搜索 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/shu-chuan-suo-kuang-sou-suo-forked-p78j9v?file=%2Fsrc%2FTreeTransfer.jsx%3A235%2C57)
<img width="1920" alt="image" src="https://github.com/ant-design/ant-design/assets/57334095/7393cdc3-8ad2-4031-808e-1e5afcc45fc9">
原因是由于 Transfer 组件内部在计算 count 时候会调用 filterOption 函数对传入的 dataSource 进行过滤，但你之前的函数判断会导致只剩下 `Healthy breast` ，而他的父节点 `Chest` 无法通过，同时 render tree 的逻辑又是你自己控制的，所以显示是正常的。

虽然 antd 无法控制这个行为的出现，但是似乎可以在 `selectedCount > totalCount` 时候给个 dev warning ？antd 有这种设计指导吗？

**Comment by leslie555** [comment]
@LINGyue-dot  感谢你的回答。 我当时就觉得selectedCount > totalCount肯定是有问题的， 完全忽略filterOption这个属性， 因为其他问题太多了， 可谓绞尽脑汁😂。 我现在的逻辑完全可以删除filterOptions了。
