### ISSUE TITLE
Table 怎么去掉title上面的线

### ISSUE THREAD

**Issue by lansefengxinzi** [ant-design/ant-design#4671]
我尝试设置border没有效果。也没有找到这个线是哪个线。
![626c33ab-e747-4f8d-b0c8-b40dea9e838e](https://cloud.githubusercontent.com/assets/12048313/22180329/0d4d7c1c-e0a8-11e6-9fe8-40f50743ca03.png)
我想在table外面添加一个 card,然后这条线还是在外面。
![2d054005-4252-47e7-aab3-eb1c133c9be6](https://cloud.githubusercontent.com/assets/12048313/22180341/67bc0f1a-e0a8-11e6-8100-d53ba00c5619.png)

```javascript
<Card style={cardStyle}>
    <UserTable columns={this.state.columns} dataSource={this.state.columnsData} />
</Card>

const cardStyle = {
    marginLeft: "50px",
    marginRight: "50px",
};
```

**Comment by yesmeck** [comment]
这个线明显不是 Table 上的，自己检查下代码吧。

**Comment by lansefengxinzi** [comment]
确实不是。、
