### ISSUE TITLE
Bug in Space.Compact component

### ISSUE THREAD

**Issue by DmitryLebedevDev** [ant-design/ant-design#46722]
### Reproduction link

[https://stackblitz.com/edit/react-wmq8ef?file=demo.tsx](https://stackblitz.com/edit/react-wmq8ef?file=demo.tsx)

### Steps to reproduce

click on submit button many times

### What is expected?

change without the jake

### What is actually happening?

exist the jake

| Environment | Info |
| --- | --- |
| antd | 5.12.6 |
| React | 18.2.0 |
| System | linux |
| Browser | chrome |

**Comment by MadCcc** [comment]
Any more details? What do you think is a bug?

**Comment by afc163** [comment]
![Jan-02-2024 10-51-01](https://github.com/ant-design/ant-design/assets/507615/40db7965-c049-4cf0-9e3f-9ac792750b52)

**Comment by zombieJ** [comment]
Use `key` to let React align the component:
https://stackblitz.com/edit/react-wmq8ef?file=demo.tsx

**Comment by afc163** [comment]
@zombieJ 你给的例子貌似没有变化。

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-wmq8ef-7ezvhaxv?file=demo.tsx

```diff
    <Space direction="vertical">
      <Space.Compact style={{ width: 400 }}>
        <Input style={{ width: '50%' }} defaultValue="0571" />
        <Input style={{ width: '50%' }} defaultValue="26888888" />
        {test && <Input style={{ width: '50%' }} defaultValue="26888888" />}
        <Button type="primary">123</Button>
-       <Button type="primary" onClick={() => setTest(!test)}>
+       <Button type="primary" key="submit" onClick={() => setTest(!test)}>
          Submit
        </Button>
      </Space.Compact>
    </Space>
```
