### ISSUE TITLE
Can't trigger Popconfirm with custom component

### ISSUE THREAD

**Issue by mingelz** [ant-design/ant-design#4672]
#### Environment(required)

- antd version: 2.6.3, 2.6.4
- OS and its version: mac os sierra 10.12.2
- Browser and its version: chrome 55

#### What did you do? Please provide steps to re-produce your problem.

```javascript
const MyCustomComponent = ({foo}) => {
  return (
    <div>{foo}</div>
  )
}

<Popconfirm>
  <MyCustomComponent foo={bar} />
</Popconfirm>
```

#### What happen?

Can't trigger Popconfirm with custom component

#### Re-producible online demo

[demo](http://codepen.io/mingelz/pen/BpRdoq)

**Comment by yesmeck** [comment]
`Popconfirm` 需要子元素能接受 `onClick`、`onHover`  等事件。

```javascript
<Popconfirm>
  <span>
    <MyCustomComponent foo={bar} />
  </span>
</Popconfirm>
``

**Comment by afc163** [comment]
或者简单地把属性传递下去：http://codepen.io/anon/pen/jymLMj

**Comment by yesmeck** [comment]
我在文档上写一下吧。

**Comment by paranoidjk** [comment]
@yesmeck  `Popconfirm`等等这一类依赖`rc-trigger`的组件，可能都需要说明....

**Comment by mingelz** [comment]
好的，谢谢各位:)
