### ISSUE TITLE
Radio.Group options title 配置项不生效

### ISSUE THREAD

**Issue by Enivia** [ant-design/ant-design#46739]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/tian-di-de-an-niu-yang-shi-antd-5-12-5-forked-sfxyvd?file=%2Fdemo.tsx%3A13%2C58)

### Steps to reproduce

options 中添加 title 属性

### What is expected?

鼠标 hover 展示 title 文字

### What is actually happening?

鼠标 hover 未展示 title 文字

| Environment | Info |
| --- | --- |
| antd | 5.12.6 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 120 |

**Comment by Wxh16144** [comment]
审查了一下元素，title 属性是有的，只是热区比较小
<img width="745" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/a7bfbb53-0658-49a6-80f0-cce7836e6a38">

**Comment by MadCcc** [comment]
Radio 的 title 在 input 上，label 没有效果。RadioButton 的 title 所在元素 `zIndex` 是 -1，触发不了 hover 事件。
