### ISSUE TITLE
异步获取 treenode children 时，官网的例子配合 loadedKeys 使用会导致在加载到 children 为 empty array 时 stuck

### ISSUE THREAD

**Issue by yaohwu** [ant-design/ant-design#46735]
### Reproduction link

官网的例子
https://ant-design.antgroup.com/components/tree-cn#components-tree-demo-dynamic

官网例子增加 loadedKeys 之后

[https://stackblitz.com/edit/react-c8sbjq?file=demo.tsx](https://stackblitz.com/edit/react-c8sbjq?file=demo.tsx)

### Steps to reproduce

https://stackblitz.com/edit/react-c8sbjq?file=demo.tsx
点击树节点展开按钮

### What is expected?

节点正常展开

### What is actually happening?

控制台持续输出 reuse children，页面卡住

| Environment | Info |
| --- | --- |
| antd | 5.12.6 |
| React | 18.2.30 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
`loadedKeys` 就是用来控制加载的节点，当你一直留空时。它就会不断地尝试去重新加载数据。
