### ISSUE TITLE
FloatButton 悬浮按钮传入trigger属性时，支持自定义菜单弹出方向

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#46734]
### What problem does this feature solve?

解决悬浮按钮无法自定义弹出方向的问题

### What does the proposed API look like?

placement: 'top' | 'right' | 'bottom' | 'left'

**Comment by li-jia-nan** [comment]
这里有个问题，当 `placement === "left"` 或者 `placement === "right"` 的时候，菜单的垂直布局是不是也要变成水平布局？

**Comment by wsxe9988** [comment]
想法是如图
![image](https://github.com/ant-design/ant-design/assets/5828057/a4394a24-b48b-4246-8da9-f6a0e672193c)
你说的这点暂时还没考虑到

**Comment by aShu-guo** [comment]
> 这里有个问题，当 `placement === "left"` 或者 `placement === "right"` 的时候，菜单的垂直布局是不是也要变成水平布局？

应该要变成水平布局的，但是弹出菜单的顺序前后是相同的。

例如：

1. placement === "left"
菜单3    菜单2    菜单1    FloatButton

2. `placement === "right"`
FloatButton    菜单1    菜单2    菜单3

这样会不会更好点呢？

**Comment by glfeng318** [comment]
@li-jia-nan 这个功能有什么进展吗？

**Comment by li-jia-nan** [comment]
> @li-jia-nan 这个功能有什么进展吗？

我在做，预计月底可以发布
