### ISSUE TITLE
iconPrefixCls not working, import by cdn, use in html file.

### ISSUE THREAD

**Issue by zhuangtianyu** [ant-design/ant-design#46733]
### Reproduction link

[https://stackblitz.com/edit/web-platform-pcxdg5?file=index.html](https://stackblitz.com/edit/web-platform-pcxdg5?file=index.html)

### Steps to reproduce

import scripts by cdn, use in html file, prefixCls works, but iconPrefixCls not working.

### What is expected?

iconPrefixCls works.

### What is actually happening?

iconPrefixCls not working.

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | macOS Catalina |
| Browser | Google Chrome: 120.0.6099.109 (正式版本) (x86_64)  |

![image](https://github.com/ant-design/ant-design/assets/29296130/9736e77f-86fb-41b7-b658-3843699405fc)

**Comment by yoyo837** [comment]
Ref: https://github.com/ant-design/ant-design/issues/46628

**Comment by zombieJ** [comment]
ConfigProvider wrap the `iconPrefixCls` with `@ant-design/icons` lib. Which means it can not work with umd. You can call it from `@ant-design/icons` directly:

https://stackblitz.com/edit/web-platform-pzx2ce?file=index.html

**Comment by bravoy93** [comment]
Recently, I had this issue with prefixes in the icons, and it still occurs in the local environment. However, when deployed, it works fine.

**Comment by sobird** [comment]
try `yarn remove @ant-design/icons` to remove local @ant-design/icons package，because antd include @ant-design/icons.
