### ISSUE TITLE
boxShadowDrawerRight等类型定义没有

### ISSUE THREAD

**Issue by lizhen12345** [ant-design/ant-design#46741]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/sandpack-project-forked-pdcnyf?file=%2Fapp.tsx%3A26%2C13)

### Steps to reproduce

https://codesandbox.io/p/sandbox/sandpack-project-forked-pdcnyf?file=%2Fapp.tsx%3A26%2C13

### What is expected?

boxShadowDrawerRight等类型定义被抛出

### What is actually happening?

现在boxShadowDrawerRight等类型定义没有

| Environment | Info |
| --- | --- |
| antd | 5.12.6 |
| React | 18 |
| System | macos |
| Browser | 谷歌 |

**Comment by MadCcc** [comment]
故意的，仅供内部使用。
