### ISSUE TITLE
使用5.12.6版本后@ant-design/colors中升级了@ctrl/tinycolor @4.0.2，导致编译报错

### ISSUE THREAD

**Issue by lxdwxf** [ant-design/ant-design#46745]
### Steps to reproduce

报错详情：
Failed to compile with 2 errors                              下午2:21:01

 error  in ./node_modules/_@ctrl_tinycolor@4.0.2@@ctrl/tinycolor/dist/module/index.js

Module parse failed: Unexpected token (23:35)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.a = rgb.a;
|         this.roundA = Math.round(100 * this.a) / 100;
>         this.format = opts.format ?? rgb.format;
|         this.gradientType = opts.gradientType;
|         // Don't let the range of [0,255] come back in [0,1].

 @ ./node_modules/_@ctrl_tinycolor@4.0.2@@ctrl/tinycolor/dist/module/public_api.js 1:0-27 1:0-27
 @ ./node_modules/_antd@5.12.6@antd/es/theme/util/alias.js
 @ ./node_modules/_antd@5.12.6@antd/es/theme/getDesignToken.js
 @ ./node_modules/_antd@5.12.6@antd/es/theme/index.js
 @ ./node_modules/_antd@5.12.6@antd/es/index.js

Unexpected token (31:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export function isReadable(color1, color2, wcag2 = { level: 'AA', size: 'small' }) {
|     const readabilityLevel = readability(color1, color2);
>     switch ((wcag2.level ?? 'AA')   (wcag2.size ?? 'small')) {
|         case 'AAsmall':
|         case 'AAAlarge':

 @ ./node_modules/_@ctrl_tinycolor@4.0.2@@ctrl/tinycolor/dist/module/public_api.js 3:0-33 3:0-33
 @ ./node_modules/_antd@5.12.6@antd/es/theme/util/alias.js
 @ ./node_modules/_antd@5.12.6@antd/es/theme/getDesignToken.js
 @ ./node_modules/_antd@5.12.6@antd/es/theme/index.js
 @ ./node_modules/_antd@5.12.6@antd/es/index.js

### What is expected?

如何避免，或者有没有锁定版本的方案

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 5.12.6 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
正在处理中：https://github.com/ant-design/ant-design/pull/46744

**Comment by arvinxx** [comment]
可以先锁 5.12.5

**Comment by yoyo837** [comment]
> 可以先锁 5.12.5

没用，它lock文件已经更新了，还要撤回自己项目的lock文件

**Comment by Hzy0913** [comment]
> > 可以先锁 5.12.5
> 
> 没用，它lock文件已经更新了，还要撤回自己项目的lock文件吧？

"resolutions": {
    "@ctrl/tinycolor": "^3.6.0"
  }

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/releases/tag/5.12.7
