### ISSUE TITLE
Progress 支持自定义设置进度条的圆角

### ISSUE THREAD

**Issue by hyhday1** [ant-design/ant-design#46747]
### What problem does this feature solve?

之前通过简单的样式覆盖可以做到自定义border-radius，由于 https://github.com/ant-design/ant-design/pull/46209/files 这个改动，导致自定义样式的border-radius不生效

### What does the proposed API look like?

填入对应的API值样式即可生效
strokeRadius:number

**Comment by afc163** [comment]
What does the proposed API look like?
