### ISSUE TITLE
当全局设置了 scroll-behavior 为 smooth 之后， Select/TreeSelect 等组件的下拉列表滚动异常

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#46742]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/duo-xuan-antd-5-12-6-forked-pj2jmx?file=%2Findex.css%3A3%2C2)

### Steps to reproduce

1. 添加样式
2. 滚动 Select 的下拉列表
3. 观察结果

### What is expected?

正常滚动

### What is actually happening?

滚动异常

| Environment | Info |
| --- | --- |
| antd | 5.12.6 |
| React | React v18 |
| System | macOS 14.1 - arm64 Apple M2 Pro |
| Browser | Chrome: 120.0.6099.129 |

**Comment by MadCcc** [comment]
可以关闭虚拟滚动，默认虚拟滚动的情况下使用 smooth 会导致 scroll 事件里拿不到正确的值
