### ISSUE TITLE
Dropdown组件二级列表向左展开

### ISSUE THREAD

**Issue by WebPuY** [ant-design/ant-design#4674]
当屏幕宽度较窄的时候，向右展开会在底部出现左右滚动条。为了避免出现滚动条，这个时候想向左展开二级列表。目前可以实现吗？

#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by RaoHai** [comment]
```jsx
<SubMenu title="sub menu" className="aligin-right-class"></SubMenu>
```

要不先这样自己覆盖一下样式吧……

**Comment by cnfi** [comment]
同样遇到这个问题

**Comment by lanten** [comment]
同样的问题,我觉得可以加个控制弹出方向的选项...
![qq20171127-104506](https://user-images.githubusercontent.com/16203518/33248543-781201ca-d360-11e7-87ce-6fb831204bf1.gif)

**Comment by benjycui** [comment]
@lanten antd@3.0 将修复这个问题。

**Comment by gisersiy** [comment]
> @lanten antd@3.0 将修复这个问题。

我的项目在Dropdown组件中适用了多级菜单，需要全部向左展开。当前遇到的情况是：
1. 只有当Dropdown子级菜单触及页面右边界时才会将该级向左展开，否则默认向右展开；
2.这就会导致一种情况，二级列表项左展开，三级（甚至四级及其他级）列表又会向右展开遮挡一级列表；
3.展开符expandIcon应该可控，即向左或向右

请问会有相关更新么？
