### ISSUE TITLE
Custom circle's color not working on version 14

### ISSUE THREAD

**Issue by smartineindra** [ant-design/ant-design#46754]
### What problem does this feature solve?

Type '"#fc9000"' is not assignable to type '"red" | "blue" | "green" | "grey" | "gray"'.

### What does the proposed API look like?

Previously available in version 1.4.0

timeline: custom circle color (#1959) (fb3daa1), closes #1956

**Comment by MadCcc** [comment]
Didn't get what you mean, please describe your problem in detail and provide reproduction.
