### ISSUE TITLE
Watermark 组件重复渲染问题

### ISSUE THREAD

**Issue by HaceraI** [ant-design/ant-design#46765]
### Reproduction link

[https://ant.design/components/watermark-cn#watermark-demo-custom](https://ant.design/components/watermark-cn#watermark-demo-custom)

### Steps to reproduce

尝试更改 Watermark 组件包裹元素内容

### What is expected?

不应该进行大量的重复渲染 (CPU占用率增大)

https://github.com/ant-design/ant-design/assets/48341368/be2a14e9-9654-4fc6-8968-21c5e349155e

### What is actually happening?

重复渲染(计算)

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Google Chrome Version 120.0.6099.130 (Official Build) (64-bit) |

**Comment by MadCcc** [comment]
没有复现视频中的问题，开个无痕窗口再试试？

**Comment by HaceraI** [comment]
我尝试了下，开无痕窗口也存在这个问题。
好像改动的次数越多，重复渲染的次数就越多

**Comment by MadCcc** [comment]
换个浏览器试试呢？我们这边好像都没有复现过

**Comment by fpsqdb** [comment]
很神奇，难道和操作系统缩放比例有关，在windows 1920x1080 系统100%缩放比例，2560x1440 系统100%缩放比例下正常，在2560x1440 系统200%缩放比例下就能重新
![image](https://github.com/ant-design/ant-design/assets/6482819/36388db2-41e2-41c2-968d-07840cbea2b3)

https://github.com/ant-design/ant-design/assets/6482819/c7152a41-a55c-4ef1-ae52-ab8e99f6311b

**Comment by HaceraI** [comment]
以下是测试的浏览器及其版本信息，以及各自触发重复渲染的情况(使用的是win10虚拟机，分辨率 1709x918)：

| 浏览器          | 版本                                                    | 重复渲染情况 |
|-----------------|-------------------------------------------------------|--------------|
| Microsoft Edge  | Version 120.0.2210.91 (Official build) (64-bit)       | 极小概率触发多次渲染（宿主机同版本触发概率较大，无痕模式也是）|
| Google Chrome   | Version 120.0.6099.130 (Official Build) (64-bit)      | 触发重复渲染 |
| Firefox         | Version 116.0.3 (64位)                                | 未触发 |
| QQ浏览器        | 12.1.1 (5496) (32位) Chromium94.0.4606.71 \ IE11.789.19041.0 | 极易触发（切换窗口或失去焦点后不再触发）|

https://github.com/ant-design/ant-design/assets/48341368/d37a4489-1db0-4f63-8b28-436a9c3934e3



我觉得不是分辨率影响的。会不会是检测防删的那部分逻辑存在问题？我尝试删除element后，会再自动的添加上去

**Comment by HaceraI** [comment]
新发现：将版本更改到 `5.8.6` 后，`Microsoft Edge`，`Google Chrome`  恢复正常(没开虚拟机，另外两个就没测了) 
https://codesandbox.io/p/sandbox/zi-ding-yi-pei-zhi-antd-5-12-7-forked-njv8q5

再往上一个版本 `5.9.0` 会触发重复渲染
### 5.9.0 更新日志
🐞 Watermark 现在可以在嵌套的 Modal 和 Drawer 组件中生效。[#44104](https://github.com/ant-design/ant-design/pull/44104)

**Comment by zombieJ** [comment]
这个信息很有用，200% 复现了。我看看

**Comment by m430** [comment]
@zombieJ  这个问题在最新版本5.20.0中依然存在，在Modal或者Drawer出现的时候Watermark会重复渲染一次，渲染的区域就是Modal或者Drawer弹出的区域。

**Comment by m430** [comment]
如果发现Modal和Drawer中出现重复渲染，请设置Watermark的`inherit`为false。
