### ISSUE TITLE
v5 Theme with Layout Header and Sider

### ISSUE THREAD

**Issue by JamesHabben** [ant-design/ant-design#46760]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sandpack-project-forked-8spfhq?file=/app.tsx)

### Steps to reproduce

Use Layout with a Header, insert some text. then apply default style or dark algorithm.

### What is expected?

The background should be lighter for the default and darker for the dark theme. There also doesnt seem to be an ability to override the header background color with a token.

### What is actually happening?

The default style gives a dark blue background color with black text color in the header. If you change to dark algorithm then the text in the header lightens but the background stays the same dark blue.

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2 |
| System | Windows 11 |
| Browser | Edge v120 |

---
here is the code in case the sandbox link doesnt work to show the changes

  <ConfigProvider
    theme={{
      // 1. Use dark algorithm
      //algorithm: theme.darkAlgorithm,
      //algorithm: theme.defaultAlgorithm,
      // 2. Combine dark algorithm and compact algorithm
      //algorithm: [theme.darkAlgorithm, theme.compactAlgorithm]
      token: { colorPrimary: "#ff0000" }
    }}
  >
    <Layout>
      <Header>
        Something here:
        <Input placeholder="Please Input" />
        <Button type="primary">Submit</Button>
      </Header>
    </Layout>
  </ConfigProvider>

**Comment by MadCcc** [comment]
Since Layout is designed as a container component, we didn't make it adjust algorithms, and so as 4.x.
But you can customize with component tokens: https://ant.design/components/layout#design-token

**Comment by JamesHabben** [comment]
That seems a reasonable position to have in not applying theme to the container, but the problem is the container comes with a default style which visually conflicts with the default theme. Seems that if the position is that Layout is a container, then it shouldn't affect the style unless the developer chooses to use the container to apply a style.

This is the workaround I have come up with, although I am sure that it can be refined.
![image](https://github.com/ant-design/ant-design/assets/6327329/8bd0a00f-9363-4553-abfd-bc4ce89fe32b)
