### ISSUE TITLE
Form设置了preserve， 如果某些表单项动态显示提交时没有渲染，无法获取其表单项值

### ISSUE THREAD

**Issue by pangao66** [ant-design/ant-design#46773]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-4-24-12-forked-84wppd)

### Steps to reproduce

分布表单场景， 同步当前步骤动态显示相关表单项， 提交的时候想获取所有的值，但发现只能获取到当前显示的表单项的值，如下面代码中 aaa没有了
```tsx
function App() {
  const [step, setStep] = useState(1)
  const [form] = Form.useForm()
  return (
    <Form
      form={form}
      preserve
      onFinish={(values) => {
      console.log(values)
    }}>
      {
        step === 1 ? (
          <Form.Item label={'aaa'} name={'aaa'}>
            <Input></Input>
          </Form.Item>) : (
          <Form.Item labelCol={{ span: 24 }} label={'bbb'} name={'bbb'} rules={[{ required: true }]}>
            <Input></Input>
          </Form.Item>
        )
      }
      <Button
        type={'primary'} className={'btn-self'} onClick={() => {
        console.log(form.getFieldsValue())
        if (step === 1) {
          setStep(2)
        } else {
          form.submit()
        }
      }}>{step === 1 ? '下一步' : '提交'}</Button>
    </Form>
  )
}
```

### What is expected?

希望能获取到 未渲染的form.item的值

### What is actually happening?

未渲染的form.item无法获取到值

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac |
| Browser | edge |

**Comment by LINGyue-dot** [comment]
传个参数  。`form.getFieldsValue(true)`   
[![Edit 基本使用 - antd@4.24.12 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-4-24-12-forked-84wppd)
<img width="1920" alt="image" src="https://github.com/ant-design/ant-design/assets/57334095/9b229c28-7666-4833-bee2-ab779c38ad74">

preserve 的字段说明似乎可以多加一个声明？

**Comment by afc163** [comment]
> 不过文档中 preserve 的字段说明似乎也可以加个 getFieldsValue(true) 相关的内容？

可以来个 PR
