### ISSUE TITLE
ConfigProvider 设置 token screenXXL 失效

### ISSUE THREAD

**Issue by DaphnisLi** [ant-design/ant-design#46778]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-tcpjst?file=%2Findex.js%3A18%2C11)

### Steps to reproduce

将 xxl 打印出来，console.log(screens.xxl)，将 codesandbox 的效果页开启一个新页面，调整页面宽度，可以观察到当宽度为 1600 时，打印出 true，按照代码要求，应该在 2000 时才 true

![image](https://github.com/ant-design/ant-design/assets/67792799/0ab656a6-81d2-4763-bf23-4f25204c2ea9)
![image](https://github.com/ant-design/ant-design/assets/67792799/3059eb5c-1de1-48ac-84d6-0cc1ea230746)

### What is expected?

在 2000 时才 true

### What is actually happening?

在 1600  时 true

| Environment | Info |
| --- | --- |
| antd | 5.11.0 |
| React | 18 |
| System | mac 14.2.1 |
| Browser | Chrome 120.0.6099.129（正式版本） (x86_64) |

**Comment by LINGyue-dot** [comment]
`useBreakpoint` 需要在 `ConfigProvider` 的子组件调用，见 [open stackblitz](https://stackblitz.com/edit/react-vx1zw7?embed=1&file=demo.tsx)

<img width="1920" alt="image" src="https://github.com/ant-design/ant-design/assets/57334095/47194df6-0f2f-43e8-a3d3-fc995022c955">

具体原因简单来说就是：

- `ConfigProvider` 组件会初始化 DesignTokenContext ，这个 Context 就是存储传入的 theme token 等数据，并用 `DesignTokenContext.Provider` 将 children 包裹一层
-  `useBreakpoint` 会调用 `DesignTokenContext` 来获取其中的数据
