### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by hugo-syn** [ant-design/ant-design#46783]
### Reproduction link

[http://127.0.0.1/security-issue](http://127.0.0.1/security-issue)

### Steps to reproduce

Hello I'm a security researcher and I found a critical security issue, I searched on your website and on the https://github.com/ant-design/ant-design/security tab, but it is empty how should I report this vulnerability ? Thanks.

### What is expected?

A link to report a security issue.

### What is actually happening?

No link to report a security issue.

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | N/A |
| System | N/A |
| Browser | N/A |

**Comment by afc163** [comment]
Here it is https://github.com/ant-design/ant-design/security/advisories
