### ISSUE TITLE
format in TimePicker

### ISSUE THREAD

**Issue by imamaad** [ant-design/ant-design#46781]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-vnfw62)

## DatePicker

The following code works correctly for the DatePicker:

```jsx
import React from "react";
import { createRoot } from "react-dom/client";
import { TimePicker, DatePicker} from "antd";
import dayjs from "dayjs";
import customParseFormat from "dayjs/plugin/customParseFormat";

dayjs.extend(customParseFormat);

const App = () => {
  const datePickerFormatList = [
    "DD/MM/YYYY",
    "DD/MM/YY",
    "DD-MM-YYYY",
    "DD-MM-YY",
  ];

  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <DatePicker
          defaultValue={dayjs("01/01/2015", datePickerFormatList[0])}
          format={datePickerFormatList}
        />
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);
```

However, the following code for the TimePicker is not functioning correctly:

```jsx
import React from "react";
import { createRoot } from "react-dom/client";
import { TimePicker, DatePicker} from "antd";
import dayjs from "dayjs";
import customParseFormat from "dayjs/plugin/customParseFormat";


dayjs.extend(customParseFormat);

const App = () => {
  const timePickerFormatList = ["HH:mm", "HHmm", "HH"];

  return (
    <div className="App">
      <TimePicker
          defaultValue={dayjs("10:20", timePickerFormatList[0])}
          format={timePickerFormatList}
        />
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);
```
### What is expected?

The current implementation of the TimePicker is expected to handle time input in formats such as HH:mm, HHmm, and HH.

### What is actually happening?

However, the code is not producing the correct behavior, as it only accepts input in the HH:mm format and doesn't handle the other specified formats appropriately.

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2.0 |
| System | All systems |
| Browser | All Browsers |

**Comment by andersonalz** [comment]
i have this problem and very weird because this feature it worked in Previous version and I really need this feature

**Comment by metalliclambda** [comment]
I have this problem too. it makes it hard to insert time.

**Comment by zuyetawarmatik** [comment]
It is because antd has updated dayjs to 1.11.10. To my knowledge, custom time format only works up to dayjs 1.11.7, upper than that it will cause problem.

**Comment by imamaad** [comment]
> It is because antd has updated dayjs to 1.11.10. To my knowledge, custom time format only works up to dayjs 1.11.7, upper than that it will cause problem.

My dayjs version is 1.11.6

**Comment by zuyetawarmatik** [comment]
> > It is because antd has updated dayjs to 1.11.10. To my knowledge, custom time format only works up to dayjs 1.11.7, upper than that it will cause problem.
> 
> My dayjs version is 1.11.6

You need to do "resolutions" in package.json. Otherwise, antd will use its nested dayjs version, rather than your root dayjs version.

**Comment by imamaad** [comment]
> > > It is because antd has updated dayjs to 1.11.10. To my knowledge, custom time format only works up to dayjs 1.11.7, upper than that it will cause problem.
> > 
> > 
> > My dayjs version is 1.11.6
> 
> You need to do "resolutions" in package.json. Otherwise, antd will use its nested dayjs version, rather than your root dayjs version.

What is the solution?

**Comment by zuyetawarmatik** [comment]
> > > > It is because antd has updated dayjs to 1.11.10. To my knowledge, custom time format only works up to dayjs 1.11.7, upper than that it will cause problem.
> > > 
> > > 
> > > My dayjs version is 1.11.6
> > 
> > 
> > You need to do "resolutions" in package.json. Otherwise, antd will use its nested dayjs version, rather than your root dayjs version.
> 
> What is the solution?

in package.json you put:
```
"resolutions": {
  "dayjs": "1.11.7"
}
```

**Comment by imamaad** [comment]
> > > > > It is because antd has updated dayjs to 1.11.10. To my knowledge, custom time format only works up to dayjs 1.11.7, upper than that it will cause problem.
> > > > 
> > > > 
> > > > My dayjs version is 1.11.6
> > > 
> > > 
> > > You need to do "resolutions" in package.json. Otherwise, antd will use its nested dayjs version, rather than your root dayjs version.
> > 
> > 
> > What is the solution?
> 
> in package.json you put:
> 
> ```
> "resolutions": {
>   "dayjs": "1.11.7"
> }
> ```

I tried this and it didn't work.
If the problem is from dayjs, then it must be the same problem in DatePicker, but only in TimePicker

**Comment by zuyetawarmatik** [comment]
@imamaad Have you run `npm i` or `yarn` after changing the package.json? You need to do that so the library referencing is updated.

**Comment by imamaad** [comment]
> @imamaad Have you run `npm i` or `yarn` after changing the package.json? You need to do that so the library referencing is updated.

Yes, I deleted the node_modules folder and reinstalled the packages

**Comment by imamaad** [comment]
@afc163 
Please investigate this issue if possible

**Comment by yoyo837** [comment]
DatePicker is completely refactored in 5.14.0, please try this version.

**Comment by zombieJ** [comment]
Checked in latest version. Supported in `5.14.0`
