### ISSUE TITLE
antd(5.8.6) 在 ios14 中点击 按钮 Drawer 这个组件没有反应 弹窗无法弹出

### ISSUE THREAD

**Issue by Milo-Kong** [ant-design/ant-design#46785]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-y9vgcf)

### Steps to reproduce

写一个按钮 调用antd 的Drawe组件的时候   弹窗没有调用起来

### What is expected?

期望跟正常一样  弹窗可以弹起

### What is actually happening?

期望跟正常一样  弹窗可以弹起

| Environment | Info |
| --- | --- |
| antd | 5.8.6 |
| React | react-umi |
| System | ios14     |
| Browser | ios14 |

**Comment by zombieJ** [comment]
升级到最新版本呢？

**Comment by Milo-Kong** [comment]
antd 最新版本 怎么查跟umijs  所对应的版本呢

**Comment by afc163** [comment]
两者没有关联关系。

**Comment by Milo-Kong** [comment]
直接升就可以吗？

**Comment by afc163** [comment]
我猜是这个问题，解法看 https://github.com/ant-design/ant-design/issues/42154#issuecomment-1535802037
