### ISSUE TITLE
Mention组件希望支持prefix为空时可正确Suggestion

### ISSUE THREAD

**Issue by caoyi0905** [ant-design/ant-design#4678]
使用Mention组件，设置prefix={''}，会导致无法正常提示。

如有备选项'foo','bar'，按下'f‘会提示两者（因为在onSearchChange里得到的value是空），再按下'o'，则备选框为空，期望会提示'foo'。

**Comment by RaoHai** [comment]
reinstall dependencies (rc-editor-mention@0.3.9) will solve this problem..

**Comment by RaoHai** [comment]
prefix 为空的情况其实更建议用 <AutoComplete />..

**Comment by caoyi0905** [comment]
thanks!
