### ISSUE TITLE
Table 组件，树形表格，单元格合并的时候 index 获取不对

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#46796]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/practical-river-4h5kvc?file=%2Findex.js%3A85%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqz07xjj00063b6kcvtuyxmg%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqz07xjj00023b6kh9ni0may%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqz07xjj00033b6kbq5lk7gu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqz07xjj00053b6ko0dkoeya%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B47.51741972559442%252C52.48258027440558%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqz07xjj00023b6kh9ni0may%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqz07xji00013b6kkrnr11tt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A85%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A85%252C%2522endColumn%2522%253A17%257D%255D%257D%255D%252C%2522id%2522%253A%2522clqz07xjj00023b6kh9ni0may%2522%252C%2522activeTabId%2522%253A%2522clqz07xji00013b6kkrnr11tt%2522%257D%252C%2522clqz07xjj00053b6ko0dkoeya%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqz07xjj00043b6kolk5m8ri%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqz07xjj00053b6ko0dkoeya%2522%252C%2522activeTabId%2522%253A%2522clqz07xjj00043b6kolk5m8ri%2522%257D%252C%2522clqz07xjj00033b6kbq5lk7gu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqz07xjj00033b6kbq5lk7gu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

代码里设定当索引为 `1` 的时候 `隐藏后续的单元格`，初始的时候就会发现不对劲,应该是隐藏我`数型展开里面的第一个 row 的数据`,实际隐藏了表格里的数据

当展开树型组件后才会发现交互正常，折叠后又会不对

![image](https://github.com/ant-design/ant-design/assets/67216143/17d2b8f4-83fc-452a-9a76-98416402c032)

![image](https://github.com/ant-design/ant-design/assets/67216143/ed6fdba8-e3b5-4ac8-a384-2bad30d903ac)

### What is expected?

正常的计算树型表格的 row 索引

### What is actually happening?

忽略了折叠起来树型 row 的索引

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | React17/18 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by zombieJ** [comment]
用 `key` 去做映射关系，或者对 `dataSource` 的数据去做标注。不要在展开逻辑里依赖渲染数字顺序 `index`：
```tsx
onCell(_, record) {
  const realIndex = dataSource.indexOf(record);
}
```
