### ISSUE TITLE
v5.12.7版本中 Upload.Dragger的children节点无法获取父节点的Size

### ISSUE THREAD

**Issue by JacobZyy** [ant-design/ant-design#46795]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-5-12-7-ldjzvl?file=%2Fpackage.json%3A27%2C36)

### 复现仓库

由于涉及到版本问题，而复现又只能放一个链接，因此在复现步骤里放出两个仓库的链接
[5.12.7版本](https://codesandbox.io/p/sandbox/antd-5-12-7-ldjzvl?file=%2Fpackage.json%3A27%2C36)
[5.12.0版本](https://codesandbox.io/p/sandbox/antd-5-12-0-jfgpsh?file=%2Fsrc%2FApp.tsx%3A1%2C1-13%2C1)

### 情况说明

两个版本下对元素.uploadContentWrapper配置样式

```
.uploadContentWrapper {
   width: 100%;
   height: 100%;
   border: 2px #1b56ff solid;
 }
```

表现结果如下
**v5.12.0**
![image.png](https://cdn.nlark.com/yuque/0/2024/png/29436392/1704361533670-e558b7a8-613b-4b62-b093-8c49898ac139.png)
**v5.12.7**
![image.png](https://cdn.nlark.com/yuque/0/2024/png/29436392/1704361548187-292b5a56-a57e-49b6-bed1-95106f7c0607.png)
查询源码后发现在5.12.6版本更新有关体验的issue中，修改了以下样式

```
// 原代码
 [`${componentCls}-btn`]: {
   display: 'table',
   width: '100%',
   height: '100%',
   outline: 'none',
 },
  // 新代码
 [`${componentCls}-btn`]: {
   display: 'flex',
   placeContent: 'center',
   outline: 'none',
   borderRadius: token.borderRadiusLG,
   '&:focus': {
     outline: `${unit(token.lineWidthFocus)} solid ${token.colorPrimaryBorder}`,
   },
 },
```

display方式的改变，且删除了原有的width: '100%',height: '100%',导致此bug的出现。
且由于该节点的子节点.${componentCls}-drag-container 的样式为

```
[`${componentCls}-drag-container`]: {
   display: 'table-cell',
   verticalAlign: 'middle',
 },
```

其display为tabel-cell 导致该节点也无法顺利获取到其父节点的size。导致样式的异常
我不确定这个改动是否是设计如此，但是我觉得这个改动影响了本来的组件样式，是不是不太合适？

### 补充

我看到 [#46432](https://github.com/ant-design/ant-design/pull/46432) 这个pr上写的是
修复 Upload 包裹 Button 时需要 tab 两次的问题。基于 [react-component/upload#521](https://github.com/react-component/upload/pull/521)

- 在 antd 这里默认开启了 hasControlInside 因为大多数时候是和 Button 一起配合使用。
- 在 Dragger 内默认关闭了 hasControlInside，因为拖拽上传的 children 一般不是 Button。
- 先不在文档中透出 hasControlInside，因为这个属性比较难理解，一般无需关注。

但是在我上文给出的样式代码中又可以看到

```
'&:focus': {
     outline: `${unit(token.lineWidthFocus)} solid ${token.colorPrimaryBorder}`,
   },
```

实际上在点击upload上传的过程中也会触发这个focus状态，视觉上会出现一个外边框
![image.png](https://cdn.nlark.com/yuque/0/2024/png/29436392/1704361584027-b758079b-a235-41b0-9e16-53ef8eb2c1cb.png)
这是设计如此吗？
且这个字段未给出文档，作为用户面对莫名其妙多出来一个focus的框框确不知道如何关闭，是否也有点不合适呢？

### What is expected?

预期5.12.7版本的与5.12.0版本表现相同

### What is actually happening?

如标题所描述的，**v5.12.7**版本的`Dragger`无法获取父元素的size，导致其被内部元素所撑开。

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | latest |
| System | macos |
| Browser | Arc-1.21.2; chrome-120.0.6099.129 |

**Comment by afc163** [comment]
正确样式（v5.12.5）：https://codesandbox.io/p/sandbox/bold-cartwright-d8dzny
异常样式（v5.12.6 & v5.12.7）https://codesandbox.io/p/sandbox/inspiring-hoover-c3qfqz

**Comment by JacobZyy** [comment]
高效！感谢大佬！
