### ISSUE TITLE
Dropdown 下拉框弹出位置错误

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#46792]
### Reproduction link

[https://stackblitz.com/edit/react-a6fkza-wwg7vb?file=demo.tsx](https://stackblitz.com/edit/react-a6fkza-wwg7vb?file=demo.tsx)

### Steps to reproduce

我并不清楚为何会出现弹窗位置错误的原因。如重新链接所示，当满足此布局时就会出现此类问题：
弹窗溢出了屏幕
![image](https://github.com/ant-design/ant-design/assets/30885718/83b7dc4a-fb76-4051-aea5-88ca769fcba6)
使用 getPopupContainer 来重新指定挂载的节点也无法解决
![image](https://github.com/ant-design/ant-design/assets/30885718/21135ade-dc55-4c1e-9374-3161b7129110)
理论上来讲 Dropdown 的父节点设置了 fixed 脱离的文档流，理应不被父节点影响

### What is expected?

no response

### What is actually happening?

no response

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

**Comment by MadCcc** [comment]
指定 `placement="bottomRight"` 可以解。
4.x 进入不活跃维护期了哈，欢迎升级到 v5，表现是正常的：
![image](https://github.com/ant-design/ant-design/assets/27722486/315fd693-cb20-4321-aba0-df6f40750a90)

**Comment by guaijie** [comment]
> 指定 `placement="bottomRight"` 可以解。 4.x 进入不活跃维护期了哈，欢迎升级到 v5，表现是正常的： ![image](https://private-user-images.githubusercontent.com/27722486/294803232-315fd693-cb20-4321-aba0-df6f40750a90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODQ0MTksIm5iZiI6MTcwNDc4NDExOSwicGF0aCI6Ii8yNzcyMjQ4Ni8yOTQ4MDMyMzItMzE1ZmQ2OTMtY2IyMC00MzIxLWFiYTAtZGY2ZjQwNzUwYTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3MDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjM1MTI4YTQ3N2YzMjIzMmYyMjYyZDllZDlmODc5ZWE2MTUzNWIwZDA4OTJiMTBmYWI0ZmZmYzEwNzg0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVU6Zy0HqjBHDWbdSd_A4hB4NOPNS-PpcbdKcFZIbe8)

bug 都不修改吗。我不能指定 placement="bottomRight"，因为他可能需要出现在其他方位

**Comment by yoyo837** [comment]
> > 指定 `placement="bottomRight"` 可以解。 4.x 进入不活跃维护期了哈，欢迎升级到 v5，表现是正常的： ![image](https://private-user-images.githubusercontent.com/27722486/294803232-315fd693-cb20-4321-aba0-df6f40750a90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODQ0MTksIm5iZiI6MTcwNDc4NDExOSwicGF0aCI6Ii8yNzcyMjQ4Ni8yOTQ4MDMyMzItMzE1ZmQ2OTMtY2IyMC00MzIxLWFiYTAtZGY2ZjQwNzUwYTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3MDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjM1MTI4YTQ3N2YzMjIzMmYyMjYyZDllZDlmODc5ZWE2MTUzNWIwZDA4OTJiMTBmYWI0ZmZmYzEwNzg0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVU6Zy0HqjBHDWbdSd_A4hB4NOPNS-PpcbdKcFZIbe8)
> 
> bug 都不修改吗。我不能指定 placement="bottomRight"，因为他可能需要出现在其他方位

在其他地方不指定呢？逻辑化。

**Comment by guaijie** [comment]
> > > 指定 `placement="bottomRight"` 可以解。 4.x 进入不活跃维护期了哈，欢迎升级到 v5，表现是正常的： ![image](https://private-user-images.githubusercontent.com/27722486/294803232-315fd693-cb20-4321-aba0-df6f40750a90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODQ0MTksIm5iZiI6MTcwNDc4NDExOSwicGF0aCI6Ii8yNzcyMjQ4Ni8yOTQ4MDMyMzItMzE1ZmQ2OTMtY2IyMC00MzIxLWFiYTAtZGY2ZjQwNzUwYTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3MDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjM1MTI4YTQ3N2YzMjIzMmYyMjYyZDllZDlmODc5ZWE2MTUzNWIwZDA4OTJiMTBmYWI0ZmZmYzEwNzg0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVU6Zy0HqjBHDWbdSd_A4hB4NOPNS-PpcbdKcFZIbe8)
> > 
> > 
> > bug 都不修改吗。我不能指定 placement="bottomRight"，因为他可能需要出现在其他方位
> 
> 在其他地方不指定呢？逻辑化。
非常不方。而且这本就是一个 bug
