### ISSUE TITLE
support validateTrigger on Form.List

### ISSUE THREAD

**Issue by korkt-kim** [ant-design/ant-design#46817]
### What problem does this feature solve?

can handle validation trigger for form.list

### What does the proposed API look like?
```<Form.List validateTrigger='onSubmit' />```
or
```<Form.List validateTrigger={['onSubmit']} />```

**Comment by zombieJ** [comment]
It's not a good idea to add `validateTrigger` with Form.List. It should follow the list value change or will confuse user:

<img width="422" alt="截屏2024-01-08 15 26 26" src="https://github.com/ant-design/ant-design/assets/5378891/a7d0de34-bf68-47a7-b24f-9eef0905f67f">
(User fix the count after first submit but it not working immediately)

**Comment by korkt-kim** [comment]
@zombieJ thanks for your sincere reply. Then how can developers request validation for form.list only when the form is submitted? Is there any way?

**Comment by nqsjd178559344** [comment]
我也遇见了同样的问题，蹲个后续

**Comment by zombieJ** [comment]
Though its not recommend do like it. If you really want to do so, move the rule into a proxy Form.Item instead:

https://codesandbox.io/p/sandbox/dong-tai-zeng-jian-biao-dan-xiang-antd-5-12-8-forked-97frf8?file=%2Fdemo.tsx%3A39%2C17
