### ISSUE TITLE
InputNumber - suggestions

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#4681]
Suggestions:
1. Should allow formatting of value, eg '$35', '2 a.m.', etc; also will need to have two props: {numericValue} & {formattedValue}
2. Should provide kb shortcuts that allow incrementing\decrementing the value by 10 and by 0.1

See examples in https://github.com/vlad-ignatov/react-numeric-input

**Comment by afc163** [comment]
1. Good suggestion.
2. It is already supported by pressing <kbd>↑</kbd> and <kbd>↓</kbd>.

**Comment by avalanche1** [comment]
2. up and down keys inc\dec value by one.
What  I am suggesting is:
![image](https://cloud.githubusercontent.com/assets/10534563/22202016/50d753f2-e177-11e6-9105-be635104371a.png)

**Comment by afc163** [comment]
Welcome to propose PRs for those features~

**Comment by jch254** [comment]
Hi @afc163 will you be implementing formatting of value anytime soon? I need to use currency formatting with an InputNumber inside a form inside of a business app. Any help would be greatly appreciated 👍

**Comment by afc163** [comment]
Could you help us do these features? You can propose PR to http://github.com/react-component/input-number first and we will integrate these into `antd` later.

**Comment by Jiramew** [comment]
May this be a simple implementation (https://github.com/react-component/input-number/pull/47), and really sorry for my duplicated pr >.<

**Comment by afc163** [comment]
released with 2.8.0 Thx @Jiramew
