### ISSUE TITLE
ImageProps["fallback"] 支持 ReactNode 类型

### ISSUE THREAD

**Issue by bowencool** [ant-design/ant-design#46819]
### What problem does this feature solve?

使用图标展示失败

### What does the proposed API look like?

``` diff
-  placeholder?: React.ReactNode;
-  fallback?: string;
+  placeholder?: React.ReactNode | string;
+  fallback?: React.ReactNode | string;
```

**Comment by MadCcc** [comment]
fallback 不是一个单纯的字符串，而是被当作 image 的 src 使用的，所以不是额外节点。
你的需求建议使用 `onError` 来受控展示
