### ISSUE TITLE
Input 组件绑定ref 通过ref清空input的value之后 点击会再次出现上次的值

### ISSUE THREAD

**Issue by ljmCoder** [ant-design/ant-design#46816]
### Reproduction link

[https://stackblitz.com/edit/react-rhod3q?file=demo.tsx](https://stackblitz.com/edit/react-rhod3q?file=demo.tsx)

### Steps to reproduce

输入框输入值
直接点击按钮
输入框清空 再点击输入框 值会重新出现。  用antd官网的最小化input组件 demo测试， 4和5 都有这个问题
![image](https://github.com/ant-design/ant-design/assets/41459781/f751c73d-a432-463a-bff0-3393f25d2466)

### What is expected?

input清空 再次点击input。旧值不出现

### What is actually happening?

input清空 再次点击input。旧值出现

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | "react": "18.2.0" |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
不要使用 dom 操作，react 不会响应更新，直接受控就好了。

**Comment by zombieJ** [comment]
不要用 ref 操作，不符合 React 生命周期规范。了解一下受控的概念：
https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

**Comment by ljmCoder** [comment]
> 不要用 ref 操作，不符合 React 生命周期规范。了解一下受控的概念： https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

受控没问题。 既然官方提供了focus，blur, 建议也可以后续加一个clear的方法

**Comment by ljmCoder** [comment]
> > 不要用 ref 操作，不符合 React 生命周期规范。了解一下受控的概念： https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components
> 
> 受控没问题。 既然官方提供了focus，blur, 建议也可以后续加一个clear的方法

![image](https://github.com/ant-design/ant-design/assets/41459781/3635d552-571f-42a2-a3e6-5d95eea0e39f)
