### ISSUE TITLE
Fixed right table column max and min width or adoptive column size based on content

### ISSUE THREAD

**Issue by debotos** [ant-design/ant-design#46824]
### What problem does this feature solve?

Using AntD 4.10.0 Table Component.
Currently table only support px/% width value for column. 
And if not provided it's adoptive based on the content and available screen size. 
When screen size is large(more than needed by all columns content combined) then available spaces distributed among all the columns including action columns. As a result in large screen extra spaces are shown right of the action column content. If max and min size can be specified along with col width then it can be solved.

### What does the proposed API look like?

minWidth: 100,
maxWidth: 200
Props for column along with width prop.

**Comment by afc163** [comment]
Trace #20885

**Comment by debotos** [comment]
Those suggested solutions don't work on the fixed column(left/right).
