### ISSUE TITLE
[Feat] 自定义 icon 库

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#46825]
### What problem does this feature solve?

现在 antd 的绑定了 @antd/icons，且文档没有提及。
如果删除 @antd/icons 会报错，不能自定义 icon 库

### What does the proposed API look like?

**不绑定 @antd/icons**

1. export 一个 icon-binding 或者什么方法，预处理 icon，2.或者直接允许通过 api 自定义 icon

**Comment by cangSDARM** [comment]
不，他打包后有问题。antd 导致 react 没法和它分开打包 #46273，同理也会导致如果没有 @antd/icons 无法正常打包

**Comment by afc163** [comment]
> 不，他打包后有问题。antd 导致 react 没法和它分开打包 https://github.com/ant-design/ant-design/issues/46273，同理也会导致如果没有 @antd/icons 无法正常打包

请提供重现。

**Comment by yoyo837** [comment]
> 不，他打包后有问题。antd 导致 react 没法和它分开打包 #46273，同理也会导致如果没有 @antd/icons 无法正常打包

没看懂啥意思，@antd/icons  好比 antd 依赖的一个上游包，一些位置内置使用了里面的图标，为啥要“没有它”，没有当然不能用。至于“分开打包”说的是啥问题，也没看明白，提供重现吧。

**Comment by zombieJ** [comment]
webpack alias 直接别名到你自己的库就行了

**Comment by cangSDARM** [comment]
> > 不，他打包后有问题。antd 导致 react 没法和它分开打包 [https://github.com/ant-design/ant-design/issues/46273，同理也会导致如果没有](https://github.com/ant-design/ant-design/issues/46273%EF%BC%8C%E5%90%8C%E7%90%86%E4%B9%9F%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%A6%82%E6%9E%9C%E6%B2%A1%E6%9C%89) @antd/icons 无法正常打包
> 
> 请提供重现。

https://codesandbox.io/p/devbox/sls5nn?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr0jtfep0006356hnghdkwtr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr0jtfep0002356h4xu6v7mv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr0jtfep0003356hoo4i462d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr0jtfep0005356hs69q7gub%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr0jtfep0002356h4xu6v7mv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr0jtfep0001356h7bre5fym%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr0jtfep0002356h4xu6v7mv%2522%252C%2522activeTabId%2522%253A%2522clr0jtfep0001356h7bre5fym%2522%257D%252C%2522clr0jtfep0005356hs69q7gub%2522%253A%257B%2522id%2522%253A%2522clr0jtfep0005356hs69q7gub%2522%252C%2522activeTabId%2522%253A%2522clr0k3tqh0106356h54j20cnu%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5000%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clr0jznqf00bc356hidkrdui2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4173%252C%2522id%2522%253A%2522clr0k3tqh0106356h54j20cnu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr0jtfep0003356hoo4i462d%2522%253A%257B%2522id%2522%253A%2522clr0jtfep0003356hoo4i462d%2522%252C%2522activeTabId%2522%253A%2522clr0k082j00f9356hwi5du9yo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clr0jzfg7008p356hv0izyq5u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clr0k082j00f9356hwi5du9yo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr0k07t6000segi5ajhi6w57%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by cangSDARM** [comment]
之前那个 sourcemap 的也有 #46273

**Comment by MadCcc** [comment]
antd 没有 peers @ant-design/icons，是直接依赖。

> https://codesandbox.io/p/devbox/sls5nn

你给的复现中没发现哪里有报错。

**Comment by cangSDARM** [comment]
> > > 不，他打包后有问题。antd 导致 react 没法和它分开打包 [https://github.com/ant-design/ant-design/issues/46273，同理也会导致如果没有](https://github.com/ant-design/ant-design/issues/46273%EF%BC%8C%E5%90%8C%E7%90%86%E4%B9%9F%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%A6%82%E6%9E%9C%E6%B2%A1%E6%9C%89) @antd/icons 无法正常打包
> > 
> > 
> > 请提供重现。
> 
> https://codesandbox.io/p/devbox/sls5nn
> 
> npm run preview，打包后有问题



> antd 没有 peers @ant-design/icons，是直接依赖。
> 
> > https://codesandbox.io/p/devbox/sls5nn
> 
> 你给的复现中没发现哪里有报错。

**Comment by yoyo837** [comment]
> npm run preview

404，看不了
