### ISSUE TITLE
如何在没有显式定义`Layout.Header`的token的情况下动态获取其高度？

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#46838]
### Reproduction link

N/A

### Steps to reproduce

已经查阅过 https://github.com/ant-design/ant-design/issues/45469， 明白组件token在初始化前不存在，并且就算初始化了也只有显示定义的token能被获取到。 那么请问该如何拿到其高度用于一些计算呢？

如下代码目的是让这个button的右侧padding和其上部padding保持一致， 但是上部padding是由于 `align-items: center` 而自动得出的.
除了使用 `headerHeight ?? 64` 指定默认值之外请问还有其他办法吗？ 或者有什么方法可以获取到默认值？

![image](https://github.com/ant-design/ant-design/assets/45784210/4ee2c2af-0075-4af0-9804-23dc44b9757d)

谢谢。

```tsx
const AuthLayout: FC<PropsWithChildren> = ({ children }) => {

  const { token: {
    controlHeightLG,
    Layout: { headerHeight } = {},
  } } = theme.useToken();


  return (
    <ConfigProvider
      theme={{
        components: {
          Layout: {
            headerPadding: `0 ${(headerHeight - controlHeightLG) / 2}px`,
          },
        },
      }}
    >
      <Layout className="min-h-full">
        <Layout.Header className="sticky top-0 bg-transparent" flex="~ items-center row-reverse">
          <DarkModeToggler />
        </Layout.Header>

        <Layout.Content>{children}</Layout.Content>

        <Layout.Footer>Footer</Layout.Footer>
      </Layout>
    </ConfigProvider>
  );
};
```

### What is expected?

N/A

### What is actually happening?

N/A

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 120 |

---
N/A

**Comment by MadCcc** [comment]
> 除了使用 `headerHeight ?? 64` 指定默认值之外请问还有其他办法吗

这个应该就是目前最好的方法，64 可以改为 antd 的默认值 `controlHeight * 2`。

确实没有什么好办法能够提前拿到组件 token 的值，因为组件 token 有部分也是基于全局 token 计算来的，不是一个确定的字面量。

**Comment by xsjcTony** [comment]
@MadCcc 嗯应该是这样了。但是有个问题，默认值有什么办法拿到吗？ 比如现在是 `controlHeight * 2`， 但万一以后某个版本改动了，但我是hard-coded了，那就出问题了
