### ISSUE TITLE
Timepicker.Rangepicker when selecting hours the minutes are set to the current minutes

### ISSUE THREAD

**Issue by spoilerdo** [ant-design/ant-design#46832]
### Reproduction link

[https://ant.design/components/time-picker](https://ant.design/components/time-picker) check the time range picker inside the docs

### Steps to reproduce

Open the panel of the rangepicker. Select an hour, next it will select the current minutes.

### What is expected?

That the amount of minutes does not change when you select an hour.

### What is actually happening?

previsouly the default behaviour was that the amount of minutes was not changed when you selected an hour. So it was 00 instead 12 or 13, etc depending on the current time.

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox |

---
I know that there is this PR https://github.com/react-component/picker/pull/691 that should fixed it but it is still not fixed.

**Comment by zombieJ** [comment]
There were many discussions on the default selection behavior, and the current version was finally chosen. Each default behavior is reasonable under different requirements. you can use `defaultPickerValue` to modify this:

```tsx
<TimePicker.RangePicker defaultPickerValue={[dayjs(), dayjs()]} />
```
