### ISSUE TITLE
Eye dropper in ColorPicker, to select color from outside.

### ISSUE THREAD

**Issue by yash-sharma01** [ant-design/ant-design#46846]
### What problem does this feature solve?

Eye dropper in ColorPicker will let users pick colors from their webpage or browser tab.
If you want to set a color in ColorPicker, you need to get the hex from the webpage and put it inside the ColorPicker.
Adding this eye dropper will reduce the friction in the above process.

### What does the proposed API look like?

I will add an eye dropper for the ColorPicker, using Browser's Native API

**Comment by li-jia-nan** [comment]
This api has poor compatibility, we have no plans to support it for the time being

**Comment by li-jia-nan** [comment]
<img width="1511" alt="image" src="https://github.com/ant-design/ant-design/assets/49217418/c1cdefb0-206f-4216-94fb-22440febb526">

**Comment by li-jia-nan** [comment]
- #43373

**Comment by yoyo837** [comment]
- https://github.com/ant-design/ant-design/issues/42385

**Comment by yash-sharma01** [comment]
@li-jia-nan @yoyo837 Thanks for the quick response!
