### ISSUE TITLE
Next.js antd中使用ConfigProvider设置主题仅在客户端组件中生效

### ISSUE THREAD

**Issue by FanetheDivine** [ant-design/ant-design#46845]
### Reproduction link

[https://github.com/FanetheDivine/antd-bug](https://github.com/FanetheDivine/antd-bug)

### Steps to reproduce

layout.js
```
//'use client'
import { ConfigProvider, theme } from "antd";
import { AntdContext } from "./components/AntdContext";
export default function Layout(props) {
  return (
    <html>
      <body>
        <ConfigProvider theme={{ algorithm: theme.darkAlgorithm }}>{props.children}</ConfigProvider>
      </body>
    </html>
  );
}
```

### What is expected?

在服务端组件中更改主题

### What is actually happening?

仅在客户端组件中才能更改主题

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.2.0 |
| System | win11 |
| Browser | Edge |

---
Next版本为14.0.4时，不启用use client会导致异常，异常消息为客户端无法找到'antd\es\index.js#theme#darkAlgorithm'。版本为14.0.3则没有异常，但改变主题无效。

**Comment by MadCcc** [comment]
antd 所提供的组件都是客户端组件，使用 token 也必须通过 `useToken` 这类客户端 hook，是符合预期的。

**Comment by MadCcc** [comment]
另外想要 SSR 也有样式的话请参考：https://ant.design/docs/react/use-with-next-cn
