### ISSUE TITLE
Select tags - entering 2 tags with the same text causes both tags to disappear

### ISSUE THREAD

**Issue by kerensternbriya** [ant-design/ant-design#46857]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-xqy2gp)

### Steps to reproduce

Enter 2 tags with the same text

### What is expected?

1. The 2 tags are combined into one (preferred)
-Or-
2. Two tags with the same text appear

### What is actually happening?

Both tags disappear

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | * |
| System | * |
| Browser | * |

**Comment by zombieJ** [comment]
It's by design to trigger remove. But I think merge into same one seems more reasonable.

**Comment by zombieJ** [comment]
Update:

When option selected with tag mode. Type again will match the filter:
<img width="420" alt="截屏2024-01-09 14 21 13" src="https://github.com/ant-design/ant-design/assets/5378891/34e0875e-d00d-474d-a514-e146b783ea1c">

Next enter means trigger the option. This operation means select if not in value or de-select if in value. It's reasonable interactive. Or user will not allow to remove selection when active the option.
