### ISSUE TITLE
Input doesn't have "focus" effect (box-shadow) on iOS sometimes

### ISSUE THREAD

**Issue by leineveber** [ant-design/ant-design#46867]
### Reproduction link

[https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sd3r8d](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sd3r8d)
[https://ant.design/components/input](https://ant.design/components/input)

### Steps to reproduce

1. Open your "input" page
2. Click on the very first input

### What is expected?

Expected to have focus effect (box-shadow)

### What is actually happening?

No focus effect

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18 |
| System | iOS |
| Browser | latest |

---
It happens to some inputs, not all of them! If you click on the very first input on your website, it has bugs. If you click on other inputs - you'll notice that it works somewhere

**Comment by leineveber** [comment]
Hello, here is a reproduction link: https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sd3r8d

As you can see (from iPhone only, Android works as expected) - first input when you click on it has focus effect, second one doesn't have. Don't know what's the reason, but same happening on your official website input page and in my production.

**Comment by yoyo837** [comment]
> Hello, here is a reproduction link: https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sd3r8d
> 
> As you can see (from iPhone only, Android works as expected) - first input when you click on it has focus effect, second one doesn't have. Don't know what's the reason, but same happening on your official website input page and in my production.

Your reproduction is works fine in my iOS latest device.
