### ISSUE TITLE
Controlled form with initial values triggers false positive for validation rule

### ISSUE THREAD

**Issue by xavierstampslafont** [ant-design/ant-design#46869]
### Reproduction link

[https://stackblitz.com/edit/stackblitz-starters-z1fkyw?file=src%2FApp.tsx](https://stackblitz.com/edit/stackblitz-starters-z1fkyw?file=src%2FApp.tsx)

### Steps to reproduce

1. Click on "Save"

### What is expected?

The form should be valid, because the input has the value "50", which is passed in via the form's initialValues prop. So I expect "Success" to appear in the console

### What is actually happening?

The input shows the validation error, "If set, this value must be greater than 0", even though it has the value "50". 

The user can enter "50" in the input, then click "Save" again, and then it works normally. 

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.2.0 |
| System | macOS Sonoma 14.2.1 |
| Browser | Chrome 120.0.6099.129 |

---
This also happens on the current latest version of Ant, 5.12.8

**Comment by MadCcc** [comment]
You should add `type: 'number'` to this rule.
Ref: https://ant.design/components/form#rule

**Comment by xavierstampslafont** [comment]
That's what I was missing, thank you!

> You should add `type: 'number'` to this rule. Ref: https://ant.design/components/form#rule
