### ISSUE TITLE
Segmented Component Border Radius theme token issue

### ISSUE THREAD

**Issue by Aarthysekar** [ant-design/ant-design#46877]
### Reproduction link

[https://ant.design/theme-editor#component-size ](https://ant.design/theme-editor#component-size )

### Steps to reproduce

Go to ant design online Theme Editor
Copy paste the below theme json. 
----
{
  "token": {
    "borderRadiusRound": 48,
    "colorBgLayout": "#f4f7fb",
    "colorPrimary": "5d67c3",
    "colorInfo": "5d67c3"
  },
  "components": {
    "Segmented": {
      "colorBgLayout": "#FFFFFF",
      "colorTextDisabled": "rgba(255, 255, 255, 0.25)",
      "itemSelectedBg": "rgb(93, 103, 195)",
      "itemSelectedColor": "rgba(255, 255, 255, 0.85)",
      "algorithm": true,
      "borderRadius": 48
    },
    "Button": {
      "borderRadius": 48
    },
    "Layout": {
      "colorBgLayout": "#f4f7fb"
    }
  }
}
----
Application layout (page content) background is set using colorBgLayout. 
We are trying to set Segmented component border radius to 48. this makes left and right most option's border radius to 48 which is correct. but when first or last option is selected, selected background color is not with border radius which looks not fit with outer radius.

### What is expected?

selected item also to be with border radius 48.

### What is actually happening?

only segmented component border radius is changing by design token. but selected item color/background is not affected with border radius input.

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | Google Chrome 120.0.0.6099.130 |

**Comment by Aarthysekar** [comment]
[
<img width="775" alt="Screenshot 2024-01-09 at 1 43 23 PM" src="https://github.com/ant-design/ant-design/assets/27697052/f81ce5d7-de75-4964-a6a4-4b78a7f79b64">
](url)
updated the background to lightblue to see the border radius mismatch

**Comment by MadCcc** [comment]
It's because `borderRadius` has an upper limit. Perhaps it's better to remove it.

**Comment by MadCcc** [comment]
You can override `borderRadiusSM` to make item radius match what you expected.

**Comment by Aarthysekar** [comment]
> You can override `borderRadiusSM` to make item radius match what you expected.

This works :) thanks @MadCcc . will try this in application and let you know if any issues.
<img width="1175" alt="Screenshot 2024-01-09 at 3 21 43 PM" src="https://github.com/ant-design/ant-design/assets/27697052/2018a078-3431-4d10-8b28-61a093950c8b">
