### ISSUE TITLE
Input 配置 addonBefore、showCount 后接 Button 按钮，样式展示待优化

### ISSUE THREAD

**Issue by liuzhaowei55** [ant-design/ant-design#46872]
### Reproduction link

[https://stackblitz.com/edit/stackblitz-starters-hh9jwj?file=src%2FApp.tsx](https://stackblitz.com/edit/stackblitz-starters-hh9jwj?file=src%2FApp.tsx)

### Steps to reproduce

```
<Space.Compact>
    <Input addonBefore="Tag" showCount />
    <Button>提交</Button>
</Space.Compact>
```

### What is expected?

Input 与 Button 之间移除圆角效果
<img width="336" alt="image" src="https://github.com/ant-design/ant-design/assets/1835787/0849078d-2b07-4a28-b6fc-9e0c661f2b49">

### What is actually happening?

Input 配置 showCount 后与 Button 之间出现了额外的圆角效果

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.2.0 |
| System | macOS |
| Browser | Arc 1.21.3 |

**Comment by liuzhaowei55** [comment]
> Input 还有些例子没有清理掉。addonXXX 在 Space.Compact 后就都推荐用新的方式了。

是有新的使用姿势了吗，有文档链接吗，没注意到，我研究下

**Comment by zombieJ** [comment]
不是，我指的是 Input 文档应该替换掉 addonXXX 的例子。这个 issue 里的是 bug 哈~
