### ISSUE TITLE
Broken Sider collapse animation

### ISSUE THREAD

**Issue by Tsury** [ant-design/ant-design#4687]
#### Environment(required)

- antd version: 2.1.0
- OS and its version: Windows 10
- Browser and its version: Chrome 55

#### What did you do? Please provide steps to re-produce your problem.

Create a clean, new antd project.
Copied this [sider example code](https://github.com/ant-design/ant-design/blob/master/components/layout/demo/side.md)
Pressed the sider collapse button

#### What do you expected?
The animation to fully extend/collapse the sider, as seen in the [layout website](https://ant.design/components/layout/).

#### What happen?
The animation stopped prematurely, the icons are not enlarged.
[Gif recording of the animation ](https://u.nya.is/bbitlq.mp4)

**Comment by benjycui** [comment]
Try to upgrade your `antd` to the latest compatible version first.

**Comment by afc163** [comment]
Reopen it if a re-producible online demo could be provided.
