### ISSUE TITLE
Button 使用 contentFontSizeSM 设置 12px 文字不居中

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46883]
### Reproduction link

[https://stackblitz.com/edit/react-51i1j8?file=demo.tsx](https://stackblitz.com/edit/react-51i1j8?file=demo.tsx)

### Steps to reproduce

查看 Button 样式

### What is expected?

文字水平居中

### What is actually happening?

文字水平不居中

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | latest |
| System | mac |
| Browser | chrome |

使用 `contentFontSizeSM` 设置不居中，因为 `line-height` 是 18.8571px
![image](https://github.com/ant-design/ant-design/assets/7971419/c8103527-079c-4ef1-b2c6-040bb8a4acff)
使用 `fontSize` 设置是居中的，因为 `line-height` 是 20px
![image](https://github.com/ant-design/ant-design/assets/7971419/a3497718-775b-499a-822c-1128d7129dfc)

**Comment by afc163** [comment]
其实 Button line-height 统一设为 1 是不是就行了？

**Comment by MadCcc** [comment]
> 其实 Button line-height 统一设为 1 是不是就行了？

line-height 不能设为 1，会导致 `g` 等英文字符底部被裁切
