### ISSUE TITLE
DatePicker一些TimePicker的配置没有导出

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#46898]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-antd-5-12-8-forked-yqft7g?file=%2Fdemo.tsx%3A9%2C28)

### Steps to reproduce

直接打开重现链接就可以看到ts的提示，目前发现hourStep， minuteStep， secondStep这几个都提示错误。

### What is expected?

一些TimePicker，在DatePicker也能够正确判断类型

### What is actually happening?

TimePicker 的效果能够实现，但是ts会报类型错误

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | react 18 |
| System | Windows 10 |
| Browser | Chrome 104.0.5112.102 |

**Comment by Wxh16144** [comment]
TS 体操可真难，@crazyair 救救
<img width="617" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/c838c91d-1596-41bd-a885-b901cd258af8">

**Comment by crazyair** [comment]
等 https://github.com/react-component/picker/pull/691 这个吧

**Comment by zombieJ** [comment]
`showTime` 是个配置：
https://codesandbox.io/p/sandbox/ji-ben-antd-5-12-8-forked-yqft7g?file=%2Fdemo.tsx%3A8%2C16
