### ISSUE TITLE
table组件的cell里面，无法用div或者input通过 height:100% 撑满整个cell

### ISSUE THREAD

**Issue by Ali-ovo** [ant-design/ant-design#46892]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ke-bian-ji-dan-yuan-ge-antd-5-12-8-forked-53kvxv?file=%2Fdemo.tsx)

### Steps to reproduce

自定义去掉cell的padding，发现单元格里的输入框高度一直不变
![image](https://github.com/ant-design/ant-design/assets/67216143/a2f70451-49f6-43f8-851a-9ff3e65674c6)

### What is expected?

期望高度可以撑满单元格

### What is actually happening?

单元格无法被撑满

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | React17/18 |
| System | Mac |
| Browser | Chrome 版本 111.0.5563.64（正式版本） (arm64) |

**Comment by zombieJ** [comment]
这和 antd 没有关系，单纯的 CSS 使用问题：

https://codesandbox.io/p/sandbox/ke-bian-ji-dan-yuan-ge-antd-5-12-8-forked-zt8msv

**Comment by Brucia323** [comment]
@zombieJ 大佬，请问当我所有单元格都使用这种方式填满，且每个单元格的高度都是动态的，我该如何设置单元格高度避免单元格过小导致内容溢出重叠？

**Comment by Brucia323** [comment]
@zombieJ 大佬，请问如何在每一个单元格都需要撑满cell，且高度不固定的情况下，保持内容不溢出重叠？
