### ISSUE TITLE
autocomplete组件的EnterPress功能

### ISSUE THREAD

**Issue by febezhao** [ant-design/ant-design#4689]
在中文输入法环境下，每输入一次都会做数据匹配，但是我是想做到输入完成之后，再做数据匹配；就像如图所示的一样
![ime](https://cloud.githubusercontent.com/assets/24941475/22188789/43830c2e-e153-11e6-89ad-7a215f968743.gif)

**Comment by RaoHai** [comment]
虽然知道你是什么意思，但是这个动图表现的不是 “一边输入一边匹配” 么？

**Comment by febezhao** [comment]
图上的动画效果比较快，容易看错，但是确实是在中文输入完成之后，才做的匹配。

**Comment by febezhao** [comment]
这个是重新写了一个组件吗？

**Comment by afc163** [comment]
...

https://github.com/react-component/select/pull/159 这是在给 rc-select 发 PR，当然是官方的修复。

**Comment by febezhao** [comment]
那不知道多久会有官方的更新发布呢？

**Comment by RaoHai** [comment]
要等 2.7。

**Comment by febezhao** [comment]
好的，太感谢了！回复又有效，又及时！

**Comment by afc163** [comment]
@RaoHai 2.7 里貌似没有。

**Comment by RaoHai** [comment]
see https://github.com/facebook/react/issues/3926

**Comment by yesmeck** [comment]
因为 AutoComplete 支持自定义 input，其实可以自己封装一个处理了 composition 事件的 input 给 AutoComplete。

**Comment by febezhao** [comment]
那这个ant-design还修复吗？因为等了好久，也没有修复。

**Comment by yesmeck** [comment]
本质上是 React 的问题，不修正了，可以按我上面的方法做。
