### ISSUE TITLE
[建议]关于tree组件treenode可以自定义render

### ISSUE THREAD

**Issue by shengbeiniao** [ant-design/ant-design#4690]
看了下源码，目前tree组件是基于rc-tree，它的render方法很简单，就是返回一个<a/>标签，建议可以自定义render，像angular-ui-tree组件。

**Comment by yesmeck** [comment]
不熟悉 angular-ui-tree，能举个例子吗？

**Comment by shengbeiniao** [comment]
比如说一个权限系统，权限集是典型的树形结构，每个节点又分为只读和管理，那么在节点上加两个复选框是最简单的设计方法。

**Comment by yesmeck** [comment]
现在 `TreeNode` 的 `title` 是支持 `ReactNode` 的，所以你想在节点上显示什么完全可以自己控制的。

**Comment by shengbeiniao** [comment]
虽然title支持ReactNode，不过由于title是span标签，事件响应也是基于TreeNode的，如果在title里面放置checkbox，会导致事件无法传递。

**Comment by shengbeiniao** [comment]
另外如果TreeNode禁掉响应，会导致collaspe失效及样式变化。

**Comment by yesmeck** [comment]
看这个例子 http://react-component.github.io/tree/examples/basic.html

> 另外如果TreeNode禁掉响应，会导致collaspe失效及样式变化。

带个 demo  http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by shengbeiniao** [comment]
ok,解决了，用event.stopPropagation();

感谢讲解~
