### ISSUE TITLE
User defined property "dropIndicatorRender" on the Tree does not work (is overridden in Tree.tsx line 194)

### ISSUE THREAD

**Issue by trace59** [ant-design/ant-design#46908]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-9p6v2c?file=%2Findex.js%3A37%2C5)

### Steps to reproduce

Set the dropIndicatorRender attribute when dragging the tree component

### What is expected?

The dropIndicatorRender attribute can take effect in tree

### What is actually happening?

Create Tree component with draggable property, define prop dropIndicatorRender as method - never called.

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | any |
| System | any |
| Browser | any |

**Comment by zombieJ** [comment]
We do not promise `rc-component` API passing with antd component. And `dropIndicatorRender` is no plan to exported yet. You can patch the antd `className` to `rc-tree` instead if really need that.

[Can I use internal API which is not documented on the site?](https://ant.design/docs/react/faq#can-i-use-internal-api-which-is-not-documented-on-the-site)

> NOT RECOMMENDED. Internal API is not guaranteed to be compatible with future versions. It may be removed or changed in some versions. If you really need to use it, you should make sure these APIs are still valid when upgrading to a new version or just lock version for usage.
