### ISSUE TITLE
<ConfigProvider theme={{ cssVar: true }}> 失效

### ISSUE THREAD

**Issue by Minf97** [ant-design/ant-design#46909]
### Reproduction link

[https://github.com/Minf97/react-todolist](https://github.com/Minf97/react-todolist)

### Steps to reproduce

1. 根据readme提示将项目跑起来
2. 在 http://localhost:3000 打开元素审查
3. 发现 antd 组件元素没有CSS变量

### What is expected?

在浏览器中开启元素审查，antd组件元素有CSS变量

### What is actually happening?

在浏览器中开启元素审查，antd组件元素没有CSS变量，只有具体的数值

| Environment | Info |
| --- | --- |
| antd | 5.11.2 |
| React | 18 |
| System | windows10 |
| Browser | chrome |

---
我根据文档： https://ant-design.antgroup.com/docs/react/css-variables-cn 操作，

我在最外层的<ConfigProvider theme={{ cssVar: true }}> 失效了！身边人用 antd5 的很少，而我自己无从下手，只好来求助官方，拜托了哦内该

**Comment by Wxh16144** [comment]
`5.12.x`+

**Comment by zombieJ** [comment]
> `5.12.x`+
 
参考这个，`cssVar` 是 5.12.0 的 feature，5.11.x 自然是没有的。

**Comment by Minf97** [comment]
非常感谢大佬们耐心回复！我犯了个低级错误，没有注意到版本要求

**Comment by Minf97** [comment]
> > `5.12.x`+
> 
> 参考这个，`cssVar` 是 5.12.0 的 feature，5.11.x 自然是没有的。

大佬，我想在这请教一个问题：antd5如何实践**主题切换**？如：明亮|暗色模式

[官方文档推荐](https://ant-design.antgroup.com/docs/react/customize-theme-cn#%E4%BD%BF%E7%94%A8%E9%A2%84%E8%AE%BE%E7%AE%97%E6%B3%95)
[掘金文档推荐](https://juejin.cn/post/7199832444836593725)

首先，在antd4之前，常见的做法是写CSS变量 `dark.less` 和 `light.less` ，通过切换CSS变量值，达到定制主题的目的。

现在antd5中，应该是希望通过 `CP组件` 的一套 `designToken` 实现切换。

那么问题来了，我实践中发现在我普通的 `div` 盒子中如文字颜色`color`，**依然需要CSS变量来控制切换主题，这样会增加复杂度，我们的预期应当是一套 `designToken` 即可，而不是 `designToken + CSS变量` **

所以请问大佬对于这一块是如何解决和实践的呢？
