### ISSUE TITLE
官方文档 Dropdown 多级菜单样式有问题

### ISSUE THREAD

**Issue by mushan0x0** [ant-design/ant-design#46902]
### Reproduction link

[https://ant-design.antgroup.com/components/dropdown-cn#components-dropdown-demo-sub-menu](https://ant-design.antgroup.com/components/dropdown-cn#components-dropdown-demo-sub-menu)

### Steps to reproduce

鼠标放上去查看子级菜单

<img width="366" alt="image" src="https://github.com/ant-design/ant-design/assets/29084441/c0ab983a-d5a0-482f-b390-4ffece7e3dc0">

### What is expected?

大小样式正常，层级在父级上面

### What is actually happening?

偏小，层级在父级下面

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

**Comment by Wxh16144** [comment]
#46888 已经修复~
