### ISSUE TITLE
Card 设置 bordered false 还是有边框样式

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#46900]
### Reproduction link

[https://stackblitz.com/edit/react-kphqbb?file=demo.tsx](https://stackblitz.com/edit/react-kphqbb?file=demo.tsx)

### Steps to reproduce

查看样式

### What is expected?

无边框样式，无 box-shadow

### What is actually happening?

有样式

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | latest |
| System | mac |
| Browser | chrome |

![image](https://github.com/ant-design/ant-design/assets/7971419/cac30304-48c0-4384-a140-29bcdc3121b1)

**Comment by MadCcc** [comment]
这个是阴影。。

**Comment by crazyair** [comment]
> 这个是阴影。。设计如此，否则在白底上 Card 这个容器就没什么意义了

bordered 是去掉边框，好像 v4 也会去掉阴影，还是 v4 就没有阴影，那 v5 能去掉阴影吗，还是再出个 api 去掉阴影？

**Comment by crazyair** [comment]
这边是 Card + Descriptions 所以去掉边，也能用的

**Comment by afc163** [comment]
<img width="447" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/45ba925a-2ba6-4666-b2d8-bb829bb369c4">

border less 是适配这个场景的，阴影是需要的。
