### ISSUE TITLE
cascader 当数据量大时出现性能问题

### ISSUE THREAD

**Issue by syx-w** [ant-design/ant-design#46919]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/mo-ren-zhi-antd-5-12-8-forked-sscf87?file=%2Fdemo.tsx)

### Steps to reproduce

点击区块访问

### What is expected?

立马出现二级菜单

### What is actually happening?

延迟 1s 出现二级菜单

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.0.0 |
| System | mac OS 13.3.1 |
| Browser | chrome 112.0.5615.120 |

**Comment by afc163** [comment]
抱歉，你前面提的两个 issue 都被我删了，因为你的 codesandbox 里貌似泄漏了贵公司的业务信息，建议脱敏。

**Comment by syx-w** [comment]
> 抱歉，你前面提的两个 issue 都被我删了，因为你的 codesandbox 里貌似泄漏了贵公司的业务信息，建议脱敏。
帮我删一下吧 谢谢

**Comment by afc163** [comment]
你把 codesandbox 删了就行，issue 其实不重要。

**Comment by syx-w** [comment]
> 你把 codesandbox 删了就行，issue 其实不重要。

好的 我重新贴一下链接

**Comment by afc163** [comment]
codesandbox 本身去删一下，issue 编辑掉也是能看到历史的。

**Comment by syx-w** [comment]
> codesandbox 本身去删一下，issue 编辑掉也是能看到历史的。

好 感谢同学
