### ISSUE TITLE
Tabs 在缩放 110% 时发生闪烁

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#46910]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-issue-46910-antd-5-20-1-twg5pn?file=%2Fdemo.tsx%3A10%2C4)

### Steps to reproduce

用 Chrome/Safari 打开此 sandbox，调整缩放，放大至 110%，Tabs 会发生闪烁

https://github.com/ant-design/ant-design/assets/7264444/b23ba8be-ad9d-4398-b297-d69ace22aa02

### What is expected?

无闪烁

### What is actually happening?

闪烁

| Environment | Info |
| --- | --- |
| antd | ~~5.12.8~~ 5.20.1 |
| React | react@18 |
| System | macOS 11.7(M1) |
| Browser | Chrome 120 |

**Comment by afc163** [comment]
稳定重现，眼已花。

**Comment by yyz945947732** [comment]
https://github.com/ant-design/ant-design/issues/46198

**Comment by dancerphil** [comment]
看起来是在 https://github.com/react-component/tabs/pull/676 之后发生的问题，时间上也符合，所以可能是没修干净

**Comment by HaceraI** [comment]
试了下sandbox的最新代码，缩放到某些范围(125, 75)还是会发生问题.   1920的屏。

**Comment by hal9112508** [comment]
如果不需要展示...操作按钮的话可以把它隐藏掉就不会删了
 .ant-tabs-nav-operations{
        display: none;
      }

**Comment by CelineYounes** [comment]
Updates?

**Comment by hyx0217** [comment]
https://github.com/react-component/tabs/pull/667  当时提了pr，用getBoundingClientRect 处理缩放的情况下很麻烦，后续又改了下 useVisibleRange.ts 计算边界值的逻辑， 感觉这样可能会更好处理点。

**Comment by fine-wang** [comment]
tabs 设置TabPosition 为left,不设置高度调整缩放布局在90-175%会一直无限闪现,   可在官网组件tabs中 滑动模块 demo中调整复现.稳定复现

**Comment by fine-wang** [comment]
Uploading 标签页 Tabs - Ant Design - Google Chrome 2024-09-13 17-49-52.mp4…

**Comment by fine-wang** [comment]
https://github.com/user-attachments/assets/ee39a498-3ca7-401b-8837-e303fb2999a1
