### ISSUE TITLE
Form DatePicker表单开始日期显示错误  一段时间后日期数据变大   日历弹窗出错  

### ISSUE THREAD

**Issue by pengshengjie** [ant-design/ant-design#46913]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fan-wei-xuan-ze-qi-antd-5-12-5-forked-jtq2vf?file=%2Fdemo.tsx%3A26%2C13)

### Steps to reproduce

打开sandbox就看到开始日期错了，然后点开日历弹窗发现也是错的

### What is expected?

日期显示正常，且无混淆。sandbox能正常通过

### What is actually happening?

开始日期显示错误  一段时间后日期数据变大
![image](https://github.com/ant-design/ant-design/assets/117100743/21fc3dac-956a-4699-88e0-d142814f9798)
![image](https://github.com/ant-design/ant-design/assets/117100743/6293518f-c0c6-477b-9fb8-23ccbca71c94)

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.0.0 |
| System | windows10 专业版 |
| Browser | 谷歌 |

---
注明：我用的是Form的fields字段  这是依赖于老版本迁移的结果  但是现在代码太多了   想改回去已经很难了  希望官方能支持一下

**Comment by pengshengjie** [comment]
我尝试用dayjs没问题

**Comment by crazyair** [comment]
如果用了 如何将 RangePicker 数组一分为二 https://zhuanlan.zhihu.com/p/375753910，业务中使用 Picker 就没有 moment dayjs 概念了，业务都走的时间戳，就相对容易将 moment 转成 dayjs 了
