### ISSUE TITLE
cascader 组件当数据量大时存在性能问题

### ISSUE THREAD

**Issue by DY-ZYQ** [ant-design/ant-design#46921]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/mo-ren-zhi-antd-5-12-8-forked-sscf87?file=%2Fdemo.tsx%3A52%2C9)

### Steps to reproduce

点击区块访问

### What is expected?

直接打开

### What is actually happening?

延迟1s

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.0.0 |
| System | mac os 13.3.1 |
| Browser | 112.0.5615.121 |

**Comment by zombieJ** [comment]
看起来可以加个虚拟滚动支持。

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/26645
