### ISSUE TITLE
antd更新到2.6.4后，subMenu点击后爆openKeys undefined异常

### ISSUE THREAD

**Issue by jk1420** [ant-design/ant-design#4692]
#### Environment(required)

- antd version:2.6.4
- OS and its version:win7
- Browser and its version:chrome

#### What did you do? Please provide steps to re-produce your problem.

我的布局中有两个菜单一个在header中用Horizontal 部署，一个在sider中用inline部署，在升级到2.6.4前这个布局是正常使用的，当升级到2.6.4后sider的菜单点击时爆openKeys undefined异常，跟踪源码后发现只有header中Horizontal menu会把openKeys设置为undefined。怀疑两个menu都公用同一个menu对象。我删除header的Horizontal menu后sider menu工作正常！

**Comment by afc163** [comment]
可能和这个类似：https://github.com/ant-design/ant-design/pull/4677

最好给个重现的 codepen，方便重现和综合考虑。

**Comment by jk1420** [comment]
@afc163  我重新安装了2.6.3跟Menu最近一次的提交的代码作比较https://github.com/ant-design/ant-design/commit/0a689592077e72046b41ce83fca6887c1716707f， 发现对于mode!=inline, 且没有设置defaultOpenKeys和openKeys的Menu，都会把Menu.props.openKeys设置为undefined。我在2.6.3的源码components/menu/index.tsx上的render的if (this.props.mode !== 'inline') 语句段下的props.openKeys设置为undefind马上重现了在2.6.4中出现的问题

**Comment by afc163** [comment]
说这么多不如给个 demo：http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
看了一下 https://github.com/ant-design/ant-design/commit/0a689592077e72046b41ce83fca6887c1716707f ，#4677 应该能修复这个问题。我再补个用例。

**Comment by jk1420** [comment]
@afc163 https://codepen.io/jk1420/pen/bgWZXx?editors=1111 当把55行注释去掉后，路由可以正常跳转，否则会抛openKeys undefined异常

**Comment by afc163** [comment]
Thx for demo!!!

**Comment by liyunsong** [comment]
我也遇到了同样的问题

**Comment by afc163** [comment]
https://github.com/react-component/menu/pull/75 也同样修复了这个问题。我发一个 rc-menu@5.0.9 的 patch，各位重新安装 antd@2.6.4 即可。@liyunsong @jk1420

**Comment by mmacedoeu** [comment]
I have a similar problem with undefined openKeys:
http://codepen.io/mmacedoeu/pen/EZrpdX

How can I test your solution ?
