### ISSUE TITLE
Form中的Input.Search按钮上会出现多余的色块

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#46924]
### Reproduction link

[https://stackblitz.com/edit/react-nwgyz5?file=demo.tsx](https://stackblitz.com/edit/react-nwgyz5?file=demo.tsx)

https://github.com/ant-design/ant-design/assets/6482819/358b01f7-ff8b-407b-8ba6-1686aa7edb46

### Steps to reproduce

点击搜索按钮
如果屏幕分辨率较高的话，请放大看，不然可能不明显

### What is expected?

没有多余色块

### What is actually happening?

搜索按钮右上角会出现多余色块

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.2 |
| System | windows 11 |
| Browser | 120.0.6099.217 |

---
不引入Form就正常，将Form注释掉，下面的Input.Search正常
```
import React from 'react';
import './index.css';
import { Input, Form } from 'antd';

const App: React.FC = () => (
  <>
    {/* <Form>
      <Form.Item
        name="keyword"
        label="搜索"
        rules={[{ required: true, message: '请输入关键字' }]}
      >
        <Input.Search placeholder="请输入关键字" readOnly enterButton="搜索" />
      </Form.Item>
    </Form> */}
    <Input.Search placeholder="请输入关键字" readOnly enterButton="搜索" />
  </>
);

export default App;

```

**Comment by zombieJ** [comment]
是不是开了 windows 高清倍率分辨率？

**Comment by Wxh16144** [comment]
感觉有可能是 chrome 的问题，我在 Firefox 看了没有这个毛刺一样的东西。

**Comment by fpsqdb** [comment]
3个显示器，视频是在2560x1440分辨率无缩放下录的，在1920x1080 无缩放，2880x1800 200%缩放下都有这问题，只不过2880x1800的分辨率太搞了不明显
PS：缩放指的是windows操作系统的缩放，不是浏览器的

**Comment by fpsqdb** [comment]
还有一个就是描述里补充的，不引入Form就没这问题。

**Comment by MadCcc** [comment]
2K 显示器受害者了。。

**Comment by zystudios** [comment]
win的缩放确实会造成一些显示问题，不光是web，app我缩放都有错位的。。。

**Comment by afc163** [comment]
这个是浏览器渲染层面的问题，antd 貌似做不了什么事情。
