### ISSUE TITLE
`Spin` fullscreen color is overriden because of selector specificity

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#46939]
### Reproduction link

[https://ant.design/components/spin-cn#spin-demo-fullscreen](https://ant.design/components/spin-cn#spin-demo-fullscreen)

### Steps to reproduce

Refer to the official demo
![image](https://github.com/ant-design/ant-design/assets/45784210/b5bf395d-2db4-44f0-a329-5c4158e0274d)

### What is expected?

Theme color applied

### What is actually happening?

Overriden by the default white color

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 120 |

### Additional comment

Or is this intentional to use the white color? How can we enable theme's color instead?

**Comment by MadCcc** [comment]
It's by design.

**Comment by xsjcTony** [comment]
Alright, then anyway I can enable the theming for that? I don't see corresponding className / style / design token
