### ISSUE TITLE
Table Column 添加 hidden 属性 

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#46930]
### What problem does this feature solve?

动态隐藏某列是非常常见的需求，通过 onCell 较为麻烦，colSpan = 0 并不像文档所描述的整列不渲染。使用数组的方法实现较为麻烦

### What does the proposed API look like?

type ColumnType  =  {
    hidden: boolean
    // ...
}

**Comment by yeliex** [comment]
it is easy to filter in business code, implement it as need

**Comment by guaijie** [comment]
> it is easy to filter in business code, implement it as need

我不清楚你认为的简单是什么，事实上我是基于二次封装实现的 hidden，如果像你说的直接在业务代码中过滤，并不会像你说的很简单，列的隐藏会随机出现在多处。简单的处理可以通过接口 slice, filter, push , splice 等实现。复杂的通常你需要手动在列中添加加属性 hidden， 然后利用 filter 过滤掉隐藏的。因此在 ts 中，你要创建新的类型以支持 hidden 属性。而且会发现，每处的实现方式并不一致，不好维护。所以一般会基于二次封装，但与其这样做，还不如 antd 的 table column 原本就支持 hidden

**Comment by yeliex** [comment]
ts interface support merge https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces, it resolves your type problem

if want to skip render a column, just filter the list before render

or create a stackblitz to show your case more clearly

**Comment by guaijie** [comment]
支持一个 hidden 不会轻松很多吗。前面我已经表达的很清楚了。实现的方式有很多，但并不统一，导致维护不方便。你不需要跟我举例说明如何去解决类型问题，我想表达的是你需要为此去特意解决类型问题。

**Comment by afc163** [comment]
搞！欢迎来个 PR @guaijie

**Comment by guaijie** [comment]
> 搞！欢迎来个 PR @guaijie

有时间我试试哈
