### ISSUE TITLE
建议：Select的行高应该根据高度相对设定

### ISSUE THREAD

**Issue by lijunbo1018** [ant-design/ant-design#4694]
#### Environment(required)

- antd version: 2.6.3
- OS and its version: macOS 10.12.2
- Browser and its version: Chrome 55.0.2883.95 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

通过[theme.js的方式](https://ant.design/docs/react/customize-theme-cn#1\)-package.theme（推荐）)自定义了主题变量@input-height-base的值，将其从28px变为30px

#### What happen?

Select控件的默认高度变为了30px，但是**文字没有垂直居中**
![image](https://cloud.githubusercontent.com/assets/5843458/22233849/69fb2dec-e22e-11e6-926a-3a32bcc8cc1a.png)

[Select的样式文件](https://github.com/ant-design/ant-design/blob/master/components/select/style/index.less#L140-L150)中，控件高度用了变量@input-height-base值，但是行高是常量，建议可以根据高度计算，@input-height-sm/@input-height-lg类似

**Comment by afc163** [comment]
Nice suggestion, thx! 😄
