### ISSUE TITLE
`Input` missing background when `hover`ed when `cssVar` mode enabled

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#46942]
### Reproduction link

https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-vvmthn?file=%2Findex.js%3A12%2C26

### Steps to reproduce

Hover the input, it's even worse for input with prefix / suffix

![image](https://github.com/ant-design/ant-design/assets/45784210/0dd94771-c830-450f-8bd7-9dc8110b7c86)

### What is expected?

`--ant-input-hover-bg` should exist

### What is actually happening?

It's missing, causing transparent background

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 120 |

**Comment by MadCcc** [comment]
It remains unset by default, not a bug exactly.
Please provide reproduction if there's some problem with your app.

**Comment by xsjcTony** [comment]
@MadCcc There's some problem with the codesandbox share functionality. I've updated the link. Please have a look.

**Comment by xsjcTony** [comment]
If you try to remove the `cssVar` option, it's going to work as expected. I think this is definitely a bug. (可以用中文）
