### ISSUE TITLE
希望AntDesign的静态对话框适配暗黑模式

### ISSUE THREAD

**Issue by stevobm** [ant-design/ant-design#46955]
### What problem does this feature solve?

目前AntDesign(5.12.8)所有组件基本上都已经适配了暗黑模式，但是静态对话框除外。希望可以补上这一块，让暗黑模式可以全面用起来。

### What does the proposed API look like?

希望AntDesign的[静态对话框](https://ant-design.antgroup.com/components/modal-cn#modalmethod)（就是Modal.method()弹出来的对话框）也适配一下暗黑模式。

**Comment by afc163** [comment]
支持的，看下 https://ant-design.antgroup.com/components/modal-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-contextredux%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-configprovider-localeprefixclstheme-%E7%AD%89%E9%85%8D%E7%BD%AE
