### ISSUE TITLE
`Menu` component is missing important props compared to react-component/menu

### ISSUE THREAD

**Issue by pastelsky** [ant-design/ant-design#4695]
Props like `activeKey` and `defaultActiveFirst` seem to have no effect when using the Menu component. 

On further investigation, it seems like antd's version of [react-component/menu](https://github.com/react-component/menu) seems to be missing these props entirely?

<img width="364" alt="screen shot 2017-01-24 at 10 21 24 am" src="https://cloud.githubusercontent.com/assets/8946207/22234577/213e107e-e21f-11e6-83d0-c4b9bb1ce829.png">

**Comment by afc163** [comment]
`activeKey` and `defaultActiveFirst` is used in [rc-select](https://github.com/react-component/select/blob/58fe7455d162c9567ca4bcd5f93be820a502da3a/package.json#L71).

Briefly, `rc-menu` is a fundamental component, and it is not exactly same as antd's Menu.

**Comment by pastelsky** [comment]
@afc163 
The documentation on` ant.design` points to `rc-menu` for additional props. Might be better to remove / tweak that then. See https://ant.design/components/menu/#API
