### ISSUE TITLE
select支持错失options的事件并添加对应的方法去干预options

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#46966]
### What problem does this feature solve?

业务开发中经常出现搜索查询的场景，但是数据回显会有点麻烦，希望添加一个时机可以检测到并能更新options，这是简单hack的一个demo https://codesandbox.io/p/sandbox/withmissing-t75qj8?file=%2Fsrc%2FApp.tsx%3A9%2C23

### What does the proposed API look like?

  afterMissing?: (value: ValueType, options: OptionType[]) => Promise<OptionType[]> | OptionType[]
  onMissing?: (value: ValueType, options: OptionType[]) => void

**Comment by crazyair** [comment]
我都是用 lableInValue

**Comment by hans000** [comment]
> 我都是用 lableInValue

不是一个场景

**Comment by MadCcc** [comment]
建议使用 AutoComplete

**Comment by hans000** [comment]
> 建议使用 AutoComplete

好像也不太合适，而且那个组件里面也不灵活只能展示text，可能我描述的不准确吧。现在是想要透出能感知missing的事件或方法方便业务开发，不然就得自己去使用变量维护了

**Comment by hans000** [comment]
顺便问一下，onChange是用户改动时会触发，Select有能加载时就感知到选择的option吗

**Comment by MadCcc** [comment]
试试把选中的内容拼进新的 options 里呢？

**Comment by zombieJ** [comment]
antd 的 API 设计是尽量和原生保持一致，因而不会去支持受控变化触发事件的 API。最好的实现还是如你所述通过 HOC 来包一个业务组件哈。
