### ISSUE TITLE
antd5版本的Tabs，将items放入State后会导致Tab子组件无法修改父组件的State

### ISSUE THREAD

**Issue by Aaron1992** [ant-design/ant-design#46961]
### Reproduction link

https://gist.github.com/Aaron1992/eb56e250457cd559c2f1c864d0ce5df9

https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-lqs3yv?file=%2Findex.js%3A35%2C57

### Steps to reproduce

1. 使用Demo中的代码，在父组件定义名为value的State，并分别传入子组件，在Tabs的items中填上子组件。
2. 讲Tabs的items放入State中，
3. 点击子组件的按钮，希望value值每次点击加1，

### What is expected?

State的值随着每次点击加1

### What is actually happening?

State值不会改变

| Environment | Info |
| --- | --- |
| antd | 5.13.0 |
| React | react |
| System | windows |
| Browser | Chrome 120.0.6099.217 |

---
目前猜测导致State修改失效的是，存放子组件的Items数组也放入了State中，导致无法调用setState修改value值。react DevTool中的截图
![Snipaste_2024-01-13_19-31-17](https://github.com/ant-design/ant-design/assets/9067927/5cc4ae9b-2c92-4ba8-8c68-87ad2bbcc680)

**Comment by Aaron1992** [comment]
> Hello @Aaron1992. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @Aaron1992，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

Reproduce:   https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-lqs3yv?file=%2Findex.js%3A35%2C57

**Comment by Aaron1992** [comment]
> Hello @Aaron1992. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @Aaron1992，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

重现实例： https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-lqs3yv?file=%2Findex.js%3A35%2C57

**Comment by MadCcc** [comment]
是因为你的 Demo 中子组件因为被放进了 state 中，不会重新渲染了

**Comment by MadCcc** [comment]
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-lqs3yv?file=%2Findex.js%3A35%2C57&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clreaw4nq00073b6moaa18ax6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clreaw4nq00033b6mb6qnw8ao%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clreaw4nq00043b6ms47g51an%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clreaw4nq00063b6mikj8b81d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clreaw4nq00033b6mb6qnw8ao%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clreaw4nq00023b6mualw0tcz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A35%252C%2522startColumn%2522%253A57%252C%2522endLineNumber%2522%253A35%252C%2522endColumn%2522%253A57%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clreaw4nq00033b6mb6qnw8ao%2522%252C%2522activeTabId%2522%253A%2522clreaw4nq00023b6mualw0tcz%2522%257D%252C%2522clreaw4nq00063b6mikj8b81d%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clreaw4nq00053b6m3s3st640%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clreaw4nq00063b6mikj8b81d%2522%252C%2522activeTabId%2522%253A%2522clreaw4nq00053b6m3s3st640%2522%257D%252C%2522clreaw4nq00043b6ms47g51an%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clreaw4nq00043b6ms47g51an%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by Aaron1992** [comment]
> 把 children 移出 state，[参考](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-q897s2?file=%2Findex.js%3A97%2C11)

谢谢，之前是抄的文档Demo，虽然猜到了State的原因，但没想到这个改法。
