### ISSUE TITLE
'Checkbox.Group' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by jamesjianpeng** [ant-design/ant-design#46978]
### Reproduction link

[https://stackblitz.com/run?file=demo.tsx](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

在 demo.tsx 页面就会有该提示，同时在本地是无法通过打包

### What is expected?

没有错误提示，并且打包通过

### What is actually happening?

'Checkbox.Group' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'string' is not assignable to type 'Element'.(2786)
(alias) const Checkbox: CompoundedComponent
import Checkbox

| Environment | Info |
| --- | --- |
| antd | 5.13.0 |
| React | 18.2.0 |
| System | Mac M1 |
| Browser |  120.0.6099.216（正式版本） (arm64) |

**Comment by li-jia-nan** [comment]
这个已经修复了，晚些时候会发版

**Comment by qiulinaluye** [comment]
which version is published and when is it

**Comment by yoyo837** [comment]
> which version is published and when is it

https://github.com/ant-design/ant-design/releases/tag/5.13.1

**Comment by yoyo837** [comment]
Feel free to open a new issue If anyone still have this problem.
