### ISSUE TITLE
Tour 漫游式引导在打开之后浏览器窗口大小改变，遮罩无法自适应铺满

### ISSUE THREAD

**Issue by deletenothing** [ant-design/ant-design#46972]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-k63h5j?file=%2Findex.js%3A15%2C43)

### Steps to reproduce

1. 打开一个包含antdTour组件的新页面
2. 改变浏览器窗口大小（比如使其小于屏幕）
3. 点击BeginTour按钮开始，可以看到遮罩铺满浏览器窗口
4. 修改浏览器窗口大小（比如最大化或者拖到浏览器到更大的屏幕），此时遮罩未铺满浏览器窗口

### What is expected?

改变浏览器窗口大小，遮罩可以自适应铺满

### What is actually happening?

改变浏览器窗口大小，遮罩未自适应铺满

| Environment | Info |
| --- | --- |
| antd | 5.13.0 |
| React | 18.0.0 |
| System | windows11 |
| Browser |  Chrome 版本 120.0.6099.199 |

**Comment by MadCcc** [comment]
Caused by https://github.com/react-component/tour/pull/46
