### ISSUE TITLE
Upload组件国际化的问题

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#4697]
我们在使用Upload组件时，有几个地方无法实现国际化处理。
在upload组件的源码中：
components/upload/uploadList.tsx
74行：icon = <div className={`${prefixCls}-list-item-uploading-text`}>文件上传中</div>; (上传文件)
137行：<Icon type="delete" title="Remove file" onClick={() => this.handleClose(file)} />（Remove file）
140行: <Icon type="cross" title="Remove file" onClick={() => this.handleClose(file)} />（Remove file）

这几个地方请支持国际化实现。谢谢！

**Comment by afc163** [comment]
先改成英文。后续可以支持默认文案配置，类似 Table 和 DatePicker。着急的话，欢迎 PR ~
