### ISSUE TITLE
时间范围选择器没有onSelect事件，用什么代替？

### ISSUE THREAD

**Issue by 97702573** [ant-design/ant-design#46985]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/quan-xuan-antd-5-5-2-73oosx?file=%2Fdemo.tsx)

### Steps to reproduce

DatePicker时间选择器其他bug：第一次选择可选范围的时间（年月日时分秒），第二次选择禁选的日期，这时候时间也属于禁选的，但是确定按钮是可以点击的，所以我想用onSelect去判断当前时间是否是禁选，禁选的话，确定按钮就变成禁止点击。

### What is expected?

第一次选择可选范围的时间（年月日时分秒），第二次选择禁选的日期，这时候时间也属于禁选的，确定按钮要禁止点击。（目前TimePicker就没有这个bug）。

### What is actually happening?

DatePicker时间选择器其他bug：第一次选择可选范围的时间（年月日时分秒），第二次选择禁选的日期，这时候时间也属于禁选的，但是确定按钮是可以点击的。

| Environment | Info |
| --- | --- |
| antd | 5.6.1 |
| React | 最新 |
| System | mac |
| Browser | 谷歌 |

**Comment by day-xue** [comment]
这个复现是不是有问题

**Comment by zombieJ** [comment]
在 `5.14.0` 重构 Picker 之后，禁用逻辑已经修复。Close

@Oicanji，
如果新版遇到问题，欢迎重新开一个 issue 哈~
Pls feel free to open an new issue with reproduce if still meet problem
