### ISSUE TITLE
Tooltip的token:colorBgSpotlight 不应该影响<menu>组件弹出框的背景色

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#46994]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/suo-qi-nei-qian-cai-dan-antd-5-13-1-forked-3kzmvg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrfzkrf10006356laxtd4kvv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrfzkrf10002356lfqz1jn7s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrfzkrf10003356lecs21r05%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrfzkrf10005356l8bkh87rj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrfzkrf10002356lfqz1jn7s%2522%253A%257B%2522id%2522%253A%2522clrfzkrf10002356lfqz1jn7s%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrfzkrf10005356l8bkh87rj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrfzkrf10004356lz379s2tg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrfzkrf10005356l8bkh87rj%2522%252C%2522activeTabId%2522%253A%2522clrfzkrf10004356lz379s2tg%2522%257D%252C%2522clrfzkrf10003356lecs21r05%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrfzkrf10003356lecs21r05%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. 在有ConfigProvider设置的组件内，设置Tooltip的token:colorBgSpotlight
2. 引入<menu>组件
3. <menu>组件收起时，没有二级菜单的弹出层背景色，被colorBgSpotlight影响

### What is expected?

步骤三：没有二级菜单的弹出层背景色应该和<menu>的token：darkPopupBg相同

### What is actually happening?

步骤三：没有二级菜单的弹出层背景色和<Tooltip>的token：colorBgSpotlight相同

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | "react": "^18.2.0" |
| System | win10 |
| Browser | chrome120 |

**Comment by MadCcc** [comment]
这个不是 Menu 的弹出层，而是 Tooltip，所以实际上是符合预期的

**Comment by chengshaohui** [comment]
> ![image](https://private-user-images.githubusercontent.com/27722486/296961454-695c14d9-d366-47fb-9285-f0d34a608056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTI4OTgsIm5iZiI6MTcwNTM5MjU5OCwicGF0aCI6Ii8yNzcyMjQ4Ni8yOTY5NjE0NTQtNjk1YzE0ZDktZDM2Ni00N2ZiLTkyODUtZjBkMzRhNjA4MDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA4MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZjI0ZTk3NWE4MDg2OTUyZmQzZmUzNzM4OTUzYTFjNTQwYmQyYTc5Y2ZjZjVjYTM3MDc0YzQ3NTY3OWNmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0CCj8sk57KwGDrYlHU4K0eTY5c-QcqgqqUhDDGlSgAc)
> 
> 这个不是 Menu 的弹出层，而是 Tooltip，所以实际上是符合预期的

你说的没错   但是这里是否不应该用Tooltip？ 就算是用Tooltip，也应该和其他有二级菜单的背景色保持一致吧？颜色不统一，也是一个很大的问题，而且通过css也不好修改

**Comment by chengshaohui** [comment]
![image](https://github.com/ant-design/ant-design/assets/20419307/b99406ce-aa70-4b37-9728-30f36ae1afc1)
如图所示，明显不是一个很好的样式实现

**Comment by chengshaohui** [comment]
![image](https://github.com/ant-design/ant-design/assets/20419307/c297d050-ec92-424f-8296-e8ffcb171dd2)

如图所示，明显不是一个很好的样式实现
