### ISSUE TITLE
演示代码里的横向滚动条没了

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#46992]
<img width="719" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/861ca522-bf30-4583-8897-fc78a188113f">

**Comment by zombieJ** [comment]
这边能看到，但是点了没有用...

<img width="711" alt="截屏2024-01-16 14 05 08" src="https://github.com/ant-design/ant-design/assets/5378891/7c86b4c8-5362-4073-97f8-8dfb9943a09a">

**Comment by MadCcc** [comment]
Dumi 的 SourceCodeEditor bug

**Comment by supuwoerc** [comment]
问题依旧存在～
