### ISSUE TITLE
Change font size units in Global Token

### ISSUE THREAD

**Issue by RamonEspinosa** [ant-design/ant-design#46990]
### What problem does this feature solve?

The use of rem units for font sizes is a common practice. 
Using rem/em units comes with several benefits, one of which is a11y. 
For example, users with vision problems might want to increase their browser's font size to make websites easier to read. With rem units, the design proportions will stay consistent and the design will be more adaptable.

Currently, ant design only supports pixels for font sizes.

### What does the proposed API look like?

Change the following properties types to `string | number`:
- `fontSize`
- `fontSizeHeading1`
- `fontSizeHeading2`
- `fontSizeHeading3`
- `fontSizeHeading4`
- `fontSizeHeading5`

**Comment by MadCcc** [comment]
Currently not supported because `fontSize` is used to calculate height or something else, string type will make it hard to implement.

**Comment by MadCcc** [comment]
Maybe this could help: https://ant.design/docs/react/compatible-style#rem-adaptation

**Comment by RamonEspinosa** [comment]
> Maybe this could help: https://ant.design/docs/react/compatible-style#rem-adaptation

It is helpful for some people. However, i see some pain points:
- Adds a new dependency (`@ant-design/cssinjs`): Some people may already be using a different styling solution such as regular css, css modules, vanilla-extract, or a different CSS-in-JS library. Some other people may not want to use a CSS-in-JS library if they are working on a SSR app.
- The `px2remTransformer` changes all pixels to rem units. Some people may only want to target font sizes.

If `fontSize`'s type must remain a number, I suggest two options:

- A new `useRemFontSizes: boolean` property could be added.
- A new `useRemUnits: string[]` property could be added. Each item in the array is a css property. Example: `useRemUnits: ["font-size"]`

All font sizes will still be declared as numbers (pixel units). But a transformation will take place just before declaring the style so it does not interfere with internal height calculations.

**Comment by MadCcc** [comment]
It could also be implemented with custom transformer, only transform `font-size` property.
You can refer https://github.com/ant-design/cssinjs/blob/master/src/transformers/px2rem.ts to write your own transformer.

**Comment by MadCcc** [comment]
> * Adds a new dependency (`@ant-design/cssinjs`)

It is dependency of `antd`, so it's better to add it to application to avoid ghost dependencies problem.
