### ISSUE TITLE
table 怎么更改提示的范围？

### ISSUE THREAD

**Issue by hexiaochen666** [ant-design/ant-design#47005]
### What problem does this feature solve?

怎么让鼠标放到icon上显示  点击升序 ，而不是鼠标放到整列提示，缩小hover效果到icon，而不是整个th
![d4ce46d8a73ae674dabd5ac055b2d1c](https://github.com/ant-design/ant-design/assets/52769073/7ed077dd-cf91-433c-990c-f8c540609e50)

### What does the proposed API look like?

![d4ce46d8a73ae674dabd5ac055b2d1c](https://github.com/ant-design/ant-design/assets/52769073/7ed077dd-cf91-433c-990c-f8c540609e50)

**Comment by afc163** [comment]
目前的交互设计如此，如果希望只点到 icon 上那就不能用内建能力了，需要自行定义列头内容。
