### ISSUE TITLE
Form.Item with Switch remembers selection after deleting from DOM and adding it again

### ISSUE THREAD

**Issue by jg-britenet** [ant-design/ant-design#47008]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-f4kv3v?file=%2Findex.js%3A2%2C1)

### Steps to reproduce

Click switch to be mark as selected, then click toggle button that causes disappearance of select, then click toggle button again to make select visible

### What is expected?

Switch shouldn't be selected because it has been just rendered from scratch

### What is actually happening?

Switch somehow remembers its previous state and after rendering Form.Item again, it is shown as selected

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | 17.0.1 |
| System | Windows 11 |
| Browser | Brave |

**Comment by MadCcc** [comment]
Use `preserve={false}`
