### ISSUE TITLE
TextArea within Space.Compact does not display values set by form.setFieldsValue

### ISSUE THREAD

**Issue by JunhoKim01** [ant-design/ant-design#47006]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/form-bug-reproduction-95fk6q)

### Steps to reproduce

1. Click 'validate' button for validating TextAreas
2. Click 'Setting TextArea' button for setting strings for each TextAreas
3. Check TextArea within Space.Compact does not display form value of 'text 2'
4. Check console to find out form value is correctly set

### What is expected?

String set by form.setFieldsValue() is displayed on TextArea.

### What is actually happening?

Nothing is displayed, but value is correctly set in form object.

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | ^18.00 |
| System | MacBook Pro 16 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
It's not allow additional layout between Form.Item and controlled component.

Please ref customize component demo for combination usage:
https://ant-design.antgroup.com/components/form#components-form-demo-customized-form-controls

**Comment by crazyair** [comment]
https://zhuanlan.zhihu.com/p/422752055
