### ISSUE TITLE
Selector optionRender causes typescript error

### ISSUE THREAD

**Issue by Isaac1606** [ant-design/ant-design#47003]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-lr226h)

### Steps to reproduce

Use the Select component with the optionRender property

### What is expected?

The typescript compiler should not complain about the Select when optionRender property is used.

### What is actually happening?

The typescript compiler throws the following error message: 
TS2322: Type
{     children: never[];     showSearch: true;     filterOption: (input: string, option?: {         label: string;         value: string;     } | undefined) => boolean;     placeholder: string;     dropdownStyle: {         zIndex: number;     };     options: { ...; }[];     optionRender: (option: any) => Element; }
is not assignable to type
IntrinsicAttributes & SelectProps<any, {     value: string;     label: string;     desc: string; }> & {     children?: ReactNode; } & {     ref?: Ref<BaseSelectRef> | undefined; }
Property  optionRender  does not exist on type
IntrinsicAttributes & SelectProps<any, {     value: string;     label: string;     desc: string; }> & {     children?: ReactNode; } & {     ref?: Ref<BaseSelectRef> | undefined; }

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | 18.2.0 |
| System | macOs Ventura 13.6 |
| Browser | any |

**Comment by afc163** [comment]
There is no errors in your reproduce link:

<img width="1232" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/0019245c-3303-4a48-9ffd-ca755fc368d2">

**Comment by MadCcc** [comment]
Didn't get type error in your reproduction. Please check whether the return type of `optionRender` is correct as documented `ReactNode`.
