### ISSUE TITLE
DatePicker.RangePicker fires change event twice on selecting a date range

### ISSUE THREAD

**Issue by seasmiles** [ant-design/ant-design#47017]
### Reproduction link

[https://stackblitz.com/edit/react-tfvdoo?file=demo.tsx](https://stackblitz.com/edit/react-tfvdoo?file=demo.tsx)

### Steps to reproduce

1. pick a date range
2. pick a second date range that is before the first one

### What is expected?

The change event fires only when end date is selected.

### What is actually happening?

The change event fires both when start date is selected and when end date is selected.

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | react 18 |
| System | mac os  |
| Browser | chrome 118 |

**Comment by zombieJ** [comment]
`onChange` event only fires for full steps since `5.14.0`. Pls feel free to upgrade.
