### ISSUE TITLE
TimePicker.RangePicker displayed times do not update

### ISSUE THREAD

**Issue by riaz-ahmad** [ant-design/ant-design#47019]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/time-range-picker-antd-5-13-1-forked-2hcwrc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrf60yzo0006356kcgg8iu2h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrf60yzo0002356kocrlz78d%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrf60yzo0003356kfjisb48n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrf60yzo0005356k8r15ebpq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrf60yzo0002356kocrlz78d%2522%253A%257B%2522id%2522%253A%2522clrf60yzo0002356kocrlz78d%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrf60yzo0005356k8r15ebpq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrf60yzo0004356kohwotojn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrf60yzo0005356k8r15ebpq%2522%252C%2522activeTabId%2522%253A%2522clrf60yzo0004356kohwotojn%2522%257D%252C%2522clrf60yzo0003356kfjisb48n%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrf60yzo0003356kfjisb48n%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

* Set defaultValue to TimePicker.RangePicker to 9:00 and 17:00
* Change the start time selected in the picker to 10:30, click ok
* Change the end time selected in the picker to 18:15, click ok

### What is expected?

The displayed values in the time picker show new times as 10:30 and 18:15

### What is actually happening?

The default values are still displayed 9:00 and 17:00
If you click to modify the values, you do see the correct values show in the drop lists

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | 18.0.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
We move to dayjs after 5.0.0: https://codesandbox.io/p/sandbox/time-range-picker-antd-5-13-1-forked-kkxww8?file=%2Fdemo.tsx%3A3%2C35
