### ISSUE TITLE
Message 鼠标移动到上面不会自动关闭

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#47020]
### What problem does this feature solve?

Message组件，如果鼠标移动到上面，就不会自动关闭，我理解应该是antd故意为之？建议增加配置，让开发者决定是不是可以不受鼠标hover影响，或者现在有方法可以不受鼠标hover影响？

背景：

因为有时候Message中内容较多，弹出的时候会挡住页面后面的操作，虽然设置了自动关闭，但是有时候用户鼠标会移动到上面，或者弹出的时候正好在鼠标的位置，这个时候Message就无法自动关闭，必须等待鼠标移开才能自动关闭。但是这个东西很多用户不知道，也不会移开鼠标，导致就一直在那里显示

建议让开发者来决定， 如果我们觉得弹出信息重要，或者需要用户确认的，就会采取其他交互来实现

![image](https://github.com/ant-design/ant-design/assets/29728228/2f5f4bc6-d6d7-4b91-a63b-ac3fdfd5a8a6)

### What does the proposed API look like?
```
messageApi.open({
      hoverClose: true, // 提供个属性让开发者自己选择
    });
```

**Comment by Wxh16144** [comment]
设计如此，message 太多了可以用 `maxCount` 来限制一下

**Comment by afc163** [comment]
这个交互在 stack 增加之前应该是没有的，应该加一个属性控制一下。

**Comment by Wxh16144** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/17444#issuecomment-510725244

**Comment by afc163** [comment]
@Wxh16144 你是对的

**Comment by zystudios** [comment]
> Duplicate of [#17444 (comment)](https://github.com/ant-design/ant-design/issues/17444#issuecomment-510725244)

所以还是有些用户会觉得不合理，建议有机会把控制权交给用户

**Comment by zystudios** [comment]
提供一个解决思路，覆盖掉 Message的class，禁止鼠标交互就可以了，给后面人参考谢谢

pointer-events: none !important;

**Comment by luojinghui** [comment]
设计不合理的东西还不改，真不知道怎么想的，把控制权給用户不应该是正确的事情吗？控制配置加实现分分钟就搞定了。

**Comment by Wxh16144** [comment]
看到 GitHub 订阅 issues 评论给我发的评论，似乎还有人遇到这个需求。

我也认为控制权交给开发者肯定是对的，就像 antd Button 会给中文字符串加空格一样。都算是 antd 来时路的特点。

然后我翻阅了一下代码，发现之前有需求给 [rc-notification](https://github.com/react-component/notification/pull/335) 添加过 `pauseOnHover` 功能。 antd 仓库的 message 和 notification 后面都用到了 rc-notification。 所以这个配置是被透下去了。

我用 `antd@5.18.0` 和 最新的 `5.27.5` 测试了一下，是可用的，可以更新一下 TS 类型定义

_App.tsx_

```tsx
import { App as AntdApp, Button, message } from "antd";
import React from "react";

const App = () => {
  // const { message } = AntdApp.useApp();
  const countRef = React.useRef(0);

  return (
    <>
      <Button
        type="primary"
        onClick={() => {
          message.success({
            /**
             * https://github.com/ant-design/ant-design/issues/49024 给 notice 组件添加了 pauseOnHover 属性。
             * 但是在 message 组件中并没有暴露这个属性，但是实际上是可以使用的。（TS 类型定义没有更新）
             * 我用 react18 和 antd 5.18.0 测试是可以的, 最新 (5.27.5) 也可以。
             * 
             * antd.message 和 useApp 都 message 也都是可以的。
             */
            ...{
              pauseOnHover: false,
            },
            content: "This is a success message" + countRef.current++,
            duration: 2,
            onClose: () => console.log("closed"),
          });
        }}
      >
        Show Message
      </Button>
    </>
  );
};

export default App;

```

_main.tsx_

```tsx
import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import { App as AntdApp } from "antd";

createRoot(document.getElementById("root")!).render(
  <AntdApp>
    <App />
  </AntdApp>
);

```
