### ISSUE TITLE
Add property to set labelClickBehavior on Form.Item for Switch/Checkbox elementts

### ISSUE THREAD

**Issue by robskaar** [ant-design/ant-design#47035]
### What problem does this feature solve?

Based on #47031, i found that clicking a label to a input field that toggles (switch/checkbox) natively is supposed to modify the current value.

in my use-case i dont wan't the click event to modify the value, but i want the click event to focus the input element even if it is a checkbox/switch.

so please implement something like an "labelClickBehavior" attribute on the label props for switch/Checkbox elements that e.g. can be "Focus" / "Toggle"

### What does the proposed API look like?

add optional Attribute "labelClickBehavior" on label props of Form.Item, states : "Focus" | "Toggle".
default value: "Focus"

**Comment by zombieJ** [comment]
Seems it's html native behavior, we may not official provide this API. But you can still support this with HOC of Form.Item: 
https://stackblitz.com/edit/react-rdcgcm?file=demo.tsx
