### ISSUE TITLE
prefixCls作为组件属性，生成的类名错误

### ISSUE THREAD

**Issue by bigyellowhsy** [ant-design/ant-design#47038]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/interesting-einstein-qd897p?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce

https://codesandbox.io/p/sandbox/interesting-einstein-qd897p?file=%2Fsrc%2FApp.tsx

### What is expected?

期望生成的类名是 tui2-btn

### What is actually happening?

期望生成的类名是 tui2

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18 |
| System | macOS 13.4.1 |
| Browser | chrome |
![20240118173819](https://github.com/ant-design/ant-design/assets/152458490/a60e0e9c-c3f3-4821-a010-d5be54a707de)

**Comment by MadCcc** [comment]
组件上的 `prefixCls` 一直都是替代完整的类名，如果需要更改前缀请使用 ConfigProvider

**Comment by bigyellowhsy** [comment]
![Uploading lQLPJyCPXeu1GlPNBkjNCUSwNWT13C7Mq2YFmJy9VKntAA_2372_1608.png…]()

但我看源码的含义是 拼接的，把传入的prefixCls和btn拼接？[](url)

**Comment by yoyo837** [comment]
`prefixCls` 默认是 `ant-`

**Comment by Wxh16144** [comment]
看了一圈 CP 的代码， antd 的 ConfigProvider 组件的 prefixCls 默认是 ant， 其他组件都是 CP 的 prefixCls + 组件的 suffixCls[通常是组件名缩写]
ref：https://github.com/ant-design/ant-design/blob/a7cff93db73436c89aee4179bebd3f0c28bc07e7/components/config-provider/index.tsx#L363-L376
