### ISSUE TITLE
bug: Popover jump

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/ant-design#47032]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/antd-popover-bug-h2w7dj?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce

https://codesandbox.io/p/devbox/antd-popover-bug-h2w7dj?file=%2Fsrc%2FApp.tsx

### What is expected?

不会跳

### What is actually happening?

会跳（临时解决方案：设置 max-width 就好了）

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome |

**Comment by afc163** [comment]
类似的问题：https://github.com/ant-design/ant-design/issues/47819

**Comment by CooperHash** [comment]
已有 #47819 
codesandbox例子已失效打不开

this issue can be closed @yoyo837

**Comment by li-jia-nan** [comment]
这个 demo 我都删了……打不开正常

**Comment by CooperHash** [comment]
我知道...
所以更应该清理类似积压的issue不是吗

**Comment by li-jia-nan** [comment]
closed
