### ISSUE TITLE
Tree组件设置虚拟滚动后无法拿到准确的scrollTop

### ISSUE THREAD

**Issue by songjialuo** [ant-design/ant-design#47030]
### What problem does this feature solve?

两个容器的scrollTop保持一致

### What does the proposed API look like?

Tree组件设置虚拟滚动能够拿到和未开启虚拟滚动时一样的的scrollTop

**Comment by MadCcc** [comment]
什么场景？有问题的话给个复现看看

**Comment by songjialuo** [comment]
大概500条数据左右，**开启虚拟滚动**后，在onscroll输出scrollTop。
第一次先**较快的**拉动滚动条从最上到最下，观察输出的scrollTop。
然后刷新页面，用滚轮**慢慢**从最上滚到最下，观察输出的scrollTop。
会发现：开启虚拟滚动后，同样的数据，开启虚拟滚动后，从最高点滚到最低点的scrollTop不同
