### ISSUE TITLE
官网的一个bug

### ISSUE THREAD

**Issue by DualWield** [ant-design/ant-design#4704]
![2017-01-24 17_45_53](https://cloud.githubusercontent.com/assets/4132470/22242229/85b819b2-e25d-11e6-9e74-5c331c3e5647.gif)

看了下console，也有报错

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/4692, 我重新部署一下网站。

**Comment by afc163** [comment]
应该已经修复了。

**Comment by DualWield** [comment]
是的，修复了~O(∩_∩)O~
