### ISSUE TITLE
Possible to create multiple global instances of `message` component?

### ISSUE THREAD

**Issue by imsushree** [ant-design/ant-design#47042]
### Steps to reproduce

Team, I am building a component library on top of antd components, I need two global instances of `message` component that will help to align two possible use cases of the message component (One I want to show at the bottom), another is sort of a global alert that will animate from top center, without affecting global config. Is it possible to achieve this without needing multiple instances?

### What is expected?

Need multiple global instances of message

### What is actually happening?

Only one instance is present per app, seems

| Environment | Info |
| --- | --- |
| antd | 4.24.11 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

---
NA

**Comment by truedrug** [comment]
@afc163 can you help in understanding why multiple instances were not allowed with various options? For example, I don't know how to create message component both at bottom center and at the top center straightforward. If i change the config, then it affects both the places. I don't like to put hacks to reset the position using setTimeouts, that makes the usage unreliable
