### ISSUE TITLE
DatePicker 能否自定义内容

### ISSUE THREAD

**Issue by Julycc41** [ant-design/ant-design#47049]
### What problem does this feature solve?

可以自定义封装 切换自定义

### What does the proposed API look like?

添加自定义内容api

想法：
https://codesandbox.io/p/sandbox/ri-qi-shi-jian-xuan-ze-antd-5-13-1-forked-swgwlz?file=%2Fdemo.js%3A4%2C22

**Comment by zombieJ** [comment]
`5.14.0` 中支持 `components` 自定义各个部件。Closed
