### ISSUE TITLE
Modal classNames wrapper disables centered option

### ISSUE THREAD

**Issue by freejosh** [ant-design/ant-design#47041]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-zlrmmz)

### Steps to reproduce

Build a Modal with the `centered` option. Add the `classNames` option and include a value for the `wrapper` key

### What is expected?

Modal is centered

### What is actually happening?

Modal is not centered

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | react 18 |
| System | macOS 14.1.2 |
| Browser | Chrome 120 |

**Comment by sunsunmonkey** [comment]
#47076
