### ISSUE TITLE
虚拟 Table 设置列宽会影响 Typography 的 ellipsis

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47051]
### Reproduction link

[https://stackblitz.com/edit/react-a2mg6e?file=demo.tsx](https://stackblitz.com/edit/react-a2mg6e?file=demo.tsx)

### Steps to reproduce

鼠标 hover `Address 1` 列内容

### What is expected?

省略号不消失

### What is actually happening?

省略号消失

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | latest |
| System | mac |
| Browser | chrome |

---
Typography.Text 宽度设置 `100%` 可以解决这个问题，但是不开启虚拟列表，Typography.Text 的省略功能就会失效，总之有一个组件有问题

**Comment by Alvin-F** [comment]
虚拟表格：scroll  未设置 x  或者 x 设置为 max-content; 特殊情况会有滚动条出现 bug

大概原因： 内部计算的 ant-table-row  的 width 是四舍五入取整导致的（感觉要么保持一致， 要么向下取整）；

比如：父级是 980.68px ， 你们计算 ant-table-row  的 内联 widh 是 981px ； 判比后 ，猜测你们就会触发滚动条显示逻辑；

**Comment by crazyair** [comment]
在 Typography 外面包一个 div，把 maxWidth 设置到  div 上可解决此问题
