### ISSUE TITLE
DatePicker 日期选择框右键可以展开

### ISSUE THREAD

**Issue by zzzhangy** [ant-design/ant-design#47059]
### Reproduction link

[https://ant-design.gitee.io/components/date-picker-cn#rangepicker](https://ant-design.gitee.io/components/date-picker-cn#rangepicker)

### Steps to reproduce

DatePicker 日期选择框右键可以展开

### What is expected?

是否合理

### What is actually happening?

DatePicker 日期选择框右键可以展开

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | windows |
| Browser | google |

**Comment by afc163** [comment]
符合预期，好像也没啥问题。
