### ISSUE TITLE
被Dropdown包裹的Button组件size设置成large时，.ant-btn-lg这个样式里的font-size失效了，导致按钮比正常的large按钮要小。

### ISSUE THREAD

**Issue by QDJobson** [ant-design/ant-design#4705]
- antd version: 2.6.3
- OS and its version: win10
- Browser and its version: chrome 55.0.2883.87 m

被Dropdown包裹的Button组件size设置成large时，.ant-btn-lg这个样式里的font-size失效了，导致按钮比正常的large按钮要小。

**Comment by afc163** [comment]
感谢反馈~
