### ISSUE TITLE
Small button 无法设置 padding

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47053]
### Reproduction link

[https://stackblitz.com/edit/react-pbezrf?file=demo.tsx](https://stackblitz.com/edit/react-pbezrf?file=demo.tsx)

### Steps to reproduce

正常 Button 可以覆盖 padding，但是 small 的 Button 无法重置

### What is expected?

能重置

### What is actually happening?

不能重置

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
优先级不够

**Comment by crazyair** [comment]
> 优先级不够

是，但是 antd 的 Button 优先级要降下，不让覆盖不方便要加个 `.ant-btn.ant-btn-sm`，如果是 large 还要加个 `.ant-btn.ant-btn-lg`

**Comment by MadCcc** [comment]
antd 的实现就是利用选择器的级联来提高优先级保证样式的，Button 比较简单，换一个较为复杂的组件也不可能都降优先级了。可以直接 PR 试试

**Comment by afc163** [comment]
建议 .no-padding 增加优先级。

**Comment by crazyair** [comment]
这个后面我看看给 sm lg 降低优先级

**Comment by crazyair** [comment]
多一个 css-var-xxx 的优先级可以理解，现在是对比 4 又多了个 size 优先级，这个显然是不合理的
