### ISSUE TITLE
message 组件在低版本chrome浏览器无法弹出

### ISSUE THREAD

**Issue by taosimjoan** [ant-design/ant-design#47064]
### Reproduction link

[https://riddle.alibaba-inc.com/riddles/new](https://riddle.alibaba-inc.com/riddles/new)

### Steps to reproduce

点击出现弹窗

### What is expected?

弹窗可以体验出

### What is actually happening?

审查元素发现有弹窗，但是样式没有加载出来

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18 |
| System | macos |
| Browser | chrome 66 |

---
浏览器兼容性需求

这是低版本审查元素
![image](https://github.com/ant-design/ant-design/assets/23648319/47653a11-1d7a-439a-a96b-03d63e1974b8)
这是高版本的
![image](https://github.com/ant-design/ant-design/assets/23648319/e801c575-2bc2-4480-8c36-2856fd0f65eb)

antd-4 版本没有这个问题

**Comment by crazyair** [comment]
holderRender 降级

**Comment by taosimjoan** [comment]
> 你需要使用 useMessage 或者 useApp

这种方法可以，但是在 app.ts 文件中怎么处理？一般需要封装axios进行拦截

**Comment by afc163** [comment]
@taosimjoan See https://ant.design/components/app-cn#%E5%85%A8%E5%B1%80%E5%9C%BA%E6%99%AFredux-%E5%9C%BA%E6%99%AF
