### ISSUE TITLE
Select 获取服务端的选项时，Dropdown 中是否可以加一个loading 状态

### ISSUE THREAD

**Issue by Orange-Yellow** [ant-design/ant-design#47065]
### What problem does this feature solve?

目前的loading 属性 只是在select选择框尾部有loading 状态，但是选项列表会显示空列表，但是没有loading 状态。

### What does the proposed API look like?

直接使用select 现有的loading属性，但是需要把dropdown 中也展示loading状态。
期望能像下图中的样式一样：

![image](https://github.com/ant-design/ant-design/assets/40858423/17b74cd0-3608-4e37-8290-1aea6893ee79)

**Comment by MadCcc** [comment]
用 `dropdownRender`

**Comment by MadCcc** [comment]
这个自定义的味道很重，建议自行封装一下
