### ISSUE TITLE
https://ant.design/components/overview-cn/ 图片疑似没对齐

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#47062]
### Reproduction link

[https://ant.design/components/overview-cn/](https://ant.design/components/overview-cn/)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/29728228/c2cf3118-e8f6-4087-928a-4f076707600f)

![image](https://github.com/ant-design/ant-design/assets/29728228/125fed00-e19a-46ef-8f6f-9ed345bdfd98)

![image](https://github.com/ant-design/ant-design/assets/29728228/a964ebac-3e52-4a62-a310-a2a3f1dcf50d)

![image](https://github.com/ant-design/ant-design/assets/29728228/09368caf-41e4-41d9-aa13-d6397b9e0bad)

 这些图片是故意这样么？看起来怪怪的，为啥左右不对齐？但是其他组件的图片又是对齐的

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

**Comment by MadCcc** [comment]
Windows 下的 svg 问题，我这边替换一下源
