### ISSUE TITLE
DatePicker的format格式对于html的标签提示文本不生效

### ISSUE THREAD

**Issue by chengxs11** [ant-design/ant-design#47063]
### Reproduction link

[`<DatePicker format={'DD/MM/YYYY'}/>`](https://ant.design/components/date-picker-cn)

官网demo在CodeSanbox中打开，format格式调整为"DD/MM/YYYY"
### Steps to reproduce

点击日期选择输入框，鼠标移入下方日期tag并停留一秒，观察弹出的提示性文本，仍然为YYYY-MM-DD格式
![image](https://github.com/ant-design/ant-design/assets/24316985/fb84cfdc-8c43-4b2e-8d83-c23e4282d0ed)

### What is expected?

提示性文本的格式与日期输入框的格式一致

### What is actually happening?

提示性文本的格式与日期输入框的格式不一致，对于国际化用户不友好

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.0.33 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
`5.14.0` 中 DatePicker 支持 `locale.fieldXXXFormat` 对每个 cell 进行 title 的自定义。此处使用  `locale.fieldDateFormat`  可以变更。

---

In version 5.14.0, the DatePicker supports customizing the title attribute for each cell via locale.fieldXXXFormat. Specifically, you can use locale.fieldDateFormat to make this change.
