### ISSUE TITLE
<App />包裹组件中的notification配置缺少参数`duration`

### ISSUE THREAD

**Issue by Lomathsus** [ant-design/ant-design#47060]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-hysmmz?file=%2Findex.tsx%3A17%2C20)

<App notification={{ duration: `number` }} /> 无法生效
<App />包裹组件的notification参数中缺失文档中的`duration`参数

<img width="491" alt="image" src="https://github.com/ant-design/ant-design/assets/102352977/2677fa56-9ddc-4c1c-99cb-5a9ece418172">

![image](https://github.com/ant-design/ant-design/assets/102352977/3c181a7f-44e9-464e-8e7d-bcc81b182e45)

![image](https://github.com/ant-design/ant-design/assets/102352977/0b93bc65-dbf7-4168-a385-aa3261eccdb8)

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | 18.2.0 |
| System | MacOS 14.2 (23C64) |
| Browser | chrome |

**Comment by Lomathsus** [comment]
> 印象中有个版本修复了， 是 ts 类型丢了，实际还是生效的？

实际也没有生效

**Comment by zombieJ** [comment]
App 的 `notification` 来自于 `notification.useNotification`。这个配置本身是不支持 `duration` 的

**Comment by Lomathsus** [comment]
> App 的 `notification` 来自于 `notification.useNotification`。这个配置本身是不支持 `duration` 的

在App这边点击跳转到的NotificationConfig是notification.config的配置，说明文档这边是不是应该修改一下
![image](https://github.com/ant-design/ant-design/assets/102352977/99f38c2b-6f14-4c0d-9f88-9edf5b9e5794)
