### ISSUE TITLE
lineWidthFocus does not work for Inputs

### ISSUE THREAD

**Issue by ebitogu** [ant-design/ant-design#47069]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-tv7gkk)

### Steps to reproduce

**Focus on the first input field** in the minimal reproducible link above and observe that the outlines and borders remain thin, despite setting `lineWidthFocus` to 5 in the ConfigProvider. This configuration is intended to make them thick when focused.

Additionally, the image below illustrates the expected thickness of the `lineWidth` when focused. Unfortunately, it appears that the input is not picking up the `lineWidthFocus` from the ConfigProvider as intended.

![LineWidthFocus Image](https://github.com/ant-design/ant-design/assets/48493864/777ca692-a138-45ea-9abf-8daf0e1f8f63)

### What is expected?

When specifying the lineWidthFocus value, it should be consistently reflected in all of my input elements.

### What is actually happening?

The specified value for the lineWidthFocus property is not being applied within the ConfigProvider.

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | MacOS |
| Browser | Chrome,Mozilla |

**Comment by MadCcc** [comment]
`lineWidthFocus` only works for outline like this:
![image](https://github.com/ant-design/ant-design/assets/27722486/6b8a24a3-6b94-4ea4-b779-b1aef131327d)

If you want to customize `box-shadow` of Input, please use component token `activeShadow` of Input

**Comment by ebitogu** [comment]
@MadCcc If lineWidth only works on buttons as you said, then why does it affect inputs as well?

Because if I set lineWidth on inputs, it tends to increase the thickness of inputs.

Something isn't right somewhere

**Comment by ebitogu** [comment]
What I want is that I would like the input element to dynamically adjust its thickness when a user hovers over it, transitioning smoothly from a thin appearance to a more substantial thickness, approximately 2 units.
