### ISSUE TITLE
Anchor offsetTop issue

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#4706]
- antd version: 2.5.2
- Browser and its version: ie 11, chrome 55, firefox 50

Links of Anchor are scrolling to wrong position.

I'm using a div as a top bar which has position fixed and height 50px. All the content is margined from top by 50 px.
This seems to make the issue with Anchor's links. They are scrolling to wrong position 50 pixels down. I tried to set _offsetTop_ property to Anchor component but makes no difference.

**Comment by RaoHai** [comment]
could you please offer a reproducible online demo for us? http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by froston** [comment]
http://codepen.io/anon/pen/wGOWGW?editors=0010

**Comment by froston** [comment]
http://codepen.io/anon/pen/wgqmYe/?editors=1000

**Comment by FacundoGFlores** [comment]
Hi there. I am having the same issue.

**Comment by afc163** [comment]
@RaoHai

**Comment by FacundoGFlores** [comment]
Problem solved! Thank you very much!

**Comment by froston** [comment]
cool .. works! thanks a lot
