### ISSUE TITLE
 ant-design-icons在nextjs中样式延迟加载

### ISSUE THREAD

**Issue by FeiPengDev** [ant-design/ant-design#47071]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/anticon-spin-nextjs-zv6l85?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrkxgufo0007356lwhzr5nwc%2522%252C%2522sizes%2522%253A%255B67.85177228786252%252C32.14822771213748%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrkxgufo0002356l5le3gz90%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrkxgufo0004356l1otwmdt2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrkxgufo0006356l98cv120b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrkxgufo0002356l5le3gz90%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkxgufo0001356lbskti7xt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrkxgufo0002356l5le3gz90%2522%252C%2522activeTabId%2522%253A%2522clrkxgufo0001356lbskti7xt%2522%257D%252C%2522clrkxgufo0006356l98cv120b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkxgufo0005356l2k3re12k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrkxgufo0006356l98cv120b%2522%252C%2522activeTabId%2522%253A%2522clrkxgufo0005356l2k3re12k%2522%257D%252C%2522clrkxgufo0004356l1otwmdt2%2522%253A%257B%2522id%2522%253A%2522clrkxgufo0004356l1otwmdt2%2522%252C%2522activeTabId%2522%253A%2522clrkxgufo0003356l4qs5r26d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkxgufo0003356l4qs5r26d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clrkxh2sb004y356la15anb4w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrkxh1wp000yefge541r5k11%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

按照指导在使用nextjs app router时添加了@ant-design/nextjs-registry来解决页面闪动，但是icon库的样式并未按照预想的提前加载

![image](https://github.com/ant-design/ant-design/assets/139141092/8ece52ea-ed44-4d32-9a21-60581b2a9214)

https://ant.design/docs/react/use-with-next-cn#%E4%BD%BF%E7%94%A8-app-router
![spin](https://github.com/ant-design/ant-design/assets/139141092/b69e2ae7-d2d2-4fd2-a8fa-cb23924bb7ec)

### What is expected?

icon库的样式正确加载

### What is actually happening?

在nextjs中antd-icons库的样式加载顺序不正确

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | react18 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
重复 issue：https://github.com/ant-design/ant-design-icons/issues/616
