### ISSUE TITLE
Table 使用虚拟列表（virtual）时，无法自定义 Table 元素（components）

### ISSUE THREAD

**Issue by martesi** [ant-design/ant-design#47073]
### Reproduction link

[重现链接](https://codesandbox.io/p/sandbox/ji-ben-yong-fa-antd-5-12-8-forked-4mt55f?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrlfe30x00063j6hh8zs567j%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrlfe30x00023j6hyr763pub%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrlfe30x00033j6h0fw8fjrv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrlfe30x00053j6h3gjuz923%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrlfe30x00023j6hyr763pub%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrlfe30w00013j6he5anb3g2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrlfe30x00023j6hyr763pub%2522%252C%2522activeTabId%2522%253A%2522clrlfe30w00013j6he5anb3g2%2522%257D%252C%2522clrlfe30x00053j6h3gjuz923%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrlfe30x00043j6h2y3fq34j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrlfe30x00053j6h3gjuz923%2522%252C%2522activeTabId%2522%253A%2522clrlfe30x00043j6h2y3fq34j%2522%257D%252C%2522clrlfe30x00033j6h0fw8fjrv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrlfe30x00033j6h0fw8fjrv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

- 定义一个 FC Row，其中设置自定义类名
- 在 Table 的 components.body.row 中使用它
- 在未启用 virtual 属性时可以发现 DOM 元素正常地包含了设定的类名
- 启用后则没有出现设定的类名

### What is expected?

在使用 virtual 属性时，components 设定仍然正常工作

### What is actually happening?

在使用 virtual 属性后，components 定义似乎没有发挥作用

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | React 18 |
| System | Windows 10 |
| Browser | Microsoft Edge 120 |

**Comment by zombieJ** [comment]
Virtual Table 本身是通过 `components` 实现的，因而也不支持自定义替换。如果你要添加  `className`，应该通过 `onRow` 来实现。

**Comment by zombieJ** [comment]
我文档加个描述说一下这个。

**Comment by martesi** [comment]
> Virtual Table 本身是通过 `components` 实现的，因而也不支持自定义替换。如果你要添加 `className`，应该通过 `onRow` 来实现。

我的原始需求是利用 `:focus-within` 来添加行高亮效果。如果使用 `onRow` 的 `onFocus` / `onBlur` + index 来实现，在行重新渲染时和 `:focus-within` 效果不太一致（Cell 中也使用了 focus-within。重渲染后 focus 状态是丢失了，而高亮 Index 仍然存在。即行仍然是高亮的，但 Cell 不高亮了）。如果 virtual 已经占用了 components.body 的话，我想我还是直接魔改 CSS 会比较符合我的原始需求？

**Comment by martesi** [comment]
刚刚发现有单独的属性 `rowClassName`，我的需求解决了，不过 components.body 加上备注也是更好的，感谢回复。
