### ISSUE TITLE
从5.11.5升级到5.13.2后，项目无法启动，

### ISSUE THREAD

**Issue by BrightXW** [ant-design/ant-design#47077]
### Reproduction link

[https://github.com/BrightXW/antd-error.git](https://github.com/BrightXW/antd-error.git)

### Steps to reproduce

yarn add antd@5.11.5然后执行，vite --open
是可以正常启动项目的
yarn add antd@5.13.2然后执行，vite --open
项目无法正常启动
从5.12.0开始就会出现这个问题

### What is expected?

vite --open
项目可以正常启动，浏览器上会显示123以及一个按钮

### What is actually happening?

vite --open 之后，开始报错

    at failureErrorWithLog (F:\tttt\project-web\antd-error\.yarn\unplugged\esbuild-npm-0.19.11-b091158d92\node_modules\esbuild\lib\main.js:1651:15)
    at F:\tttt\project-web\antd-error\.yarn\unplugged\esbuild-npm-0.19.11-b091158d92\node_modules\esbuild\lib\main.js:1059:25
    at F:\tttt\project-web\antd-error\.yarn\unplugged\esbuild-npm-0.19.11-b091158d92\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.9.0

 *  终端进程“C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn run dev”已终止，退出代码: 1。 
 *  终端将被任务重用，按任意键关闭。 

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2.0 |
| System | windows11 |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="889" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/1be2a4bf-b223-4a16-b0db-7f5ae298e0e7">

我用你给的仓库代码，antd 版本是 5.13.2，貌似没有遇到问题。

<img width="575" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/514a8a06-6308-4bf3-a50c-c3b28b3e7dc5">

**Comment by BrightXW** [comment]
> <img alt="图片" width="889" src="https://private-user-images.githubusercontent.com/507615/298290444-1be2a4bf-b223-4a16-b0db-7f5ae298e0e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTQ1MzQsIm5iZiI6MTcwNTg5NDIzNCwicGF0aCI6Ii81MDc2MTUvMjk4MjkwNDQ0LTFiZTJhNGJmLWIyMjMtNGExNi1iMGRiLTdmNWFlMjk4ZTBlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMzMwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmI2Mjc2ZGFjYjY1ZmMxZGEwZTExNjQ3NmMzMzRhMGRlMzgyNWRiMjA0ZGE3MzNmOGIyZTQ2N2JjZDRlZTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q08aCQU3ZLaXsRUH6PwBQez08rWmwwl5MsDlSpEJ6Ic">
> 我用你给的仓库代码，antd 版本是 5.13.2，貌似没有遇到问题。
> 
> <img alt="图片" width="575" src="https://private-user-images.githubusercontent.com/507615/298290562-514a8a06-6308-4bf3-a50c-c3b28b3e7dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTQ1MzQsIm5iZiI6MTcwNTg5NDIzNCwicGF0aCI6Ii81MDc2MTUvMjk4MjkwNTYyLTUxNGE4YTA2LTYzMDgtNGJmMy1hNTBjLWMzYjI4YjNlN2RjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMzMwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmJlOWQ1NGYyYWNmNDJhYmE0OTkxODJlNjlmMjBlZDg5NjgxOWU0OWY0NGFmOTBkZGE3YWYzNzMzODI2OWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mkcyCvBtTVGYQXWKwN_AwIReKO8OkrB2Sk4hJgQvICw">

请问您是用npm来install的还是yarn，我这个项目有用到yarn，package.json配置里有写用的是yarn 4.0.2的版本，项目下载来后，直接yarn install，然后运行程序，应该就会有问题

**Comment by Wxh16144** [comment]
看来是包管理器有问题啊？那就和组件库没啥关系了

_yarn_
<img width="923" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/50a45b66-ba32-4b38-a62d-8bcfff85d554">

_npm_
<img width="1000" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/3ff3f38e-74ee-4364-af4a-7b134d01d385">

**Comment by BrightXW** [comment]
但是同样是yarn，antd，5.11.5以及之前的版本就能正常运行

**Comment by dabuside** [comment]
> 但是同样是yarn，antd，5.11.5以及之前的版本就能正常运行

你的仓库有`yarn.lock`锁，可能是间接依赖锁定到某个不适配的版本了。排查一下是什么依赖导致的，或者删掉lock重新生成试试

**Comment by BrightXW** [comment]
试过了，删除掉yarn.lock后，重新install，5.11.5的是可以正常运行的，但是更新到5.12.0之后，就出问题了，两种版本都是在删除掉yarn.lock后测试的
