### ISSUE TITLE
Form item not working with react-number-format

### ISSUE THREAD

**Issue by axeloehrli** [ant-design/ant-design#47085]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-39j65m?file=%2Findex.js%3A13%2C12&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrnt6cof0006356hgpixceby%2522%252C%2522sizes%2522%253A%255B49.20353982300885%252C50.79646017699115%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrnt6coe0002356h721pdlwd%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrnt6coe0003356hauzloefc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrnt6coe0005356hjei5paco%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrnt6coe0002356h721pdlwd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrnt6coe0001356hwib7roo5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A12%257D%255D%257D%255D%252C%2522id%2522%253A%2522clrnt6coe0002356h721pdlwd%2522%252C%2522activeTabId%2522%253A%2522clrnt6coe0001356hwib7roo5%2522%257D%252C%2522clrnt6coe0005356hjei5paco%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrnt6coe0004356hy0khum46%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrnt6coe0005356hjei5paco%2522%252C%2522activeTabId%2522%253A%2522clrnt6coe0004356hy0khum46%2522%257D%252C%2522clrnt6coe0003356hauzloefc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrnt6coe0003356hauzloefc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.537109375%257D)

### Steps to reproduce

Create a Form Item with a NumericFormat component inside and add name prop to Form Item

### What is expected?

Number should be properly formatted

### What is actually happening?

Formatting doesnt work

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | Windows 11 |
| Browser | Chrome, Mozilla, Opera. |

---
I need an input that uses dots as thousand separators and comma as decimal separator. Dots are applied automatically and cannot be typed in. Only 2 decimal places

**Comment by afc163** [comment]
antd Form.Item use `value` and `onChange` in controlled mode. react-number-format has different situation: https://github.com/s-yadav/react-number-format/blob/e2179f9e9d2c4ddd1ab714ff385412b53e9ed3e7/test/library/input_numeric_format.spec.js#L698

See full code: https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-8kyd2p?file=%2Findex.js%3A26%2C44
