### ISSUE TITLE
Type issue while using borderRadius design token from components

### ISSUE THREAD

**Issue by Aarthysekar** [ant-design/ant-design#47084]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/sandpack-project-forked-kktt89?file=%2Fapp.tsx)

### Steps to reproduce

Ant Theme Editor allows to modify borderRadius for Button Components and able to see this modified borderRadius under Button.borderRadius under theme's components object. 
1. Go to Ant theme editor https://ant.design/theme-editor 
2. Go To Components page
3. Go to Button Component & Modify borderRadius
4. Click Config  button to see the generated theme json 
<img width="1439" alt="Screenshot 2024-01-22 at 1 48 24 AM" src="https://github.com/ant-design/ant-design/assets/27697052/13a8605a-0756-4147-b786-4ad7310cbe49">

This worked for button components (borderRadius is applied successfully to buttons)
When i inspect token data that was taken from usetoken hook, able to see borderRadius under token.Button.  (see console log statement in preview). If i use that the same token in any other custom components or to  customise styles in any other antd component, it throws type issue that "property 'borderRadius' does not exist on type 'ComponentToken'".
sample use case below
https://codesandbox.io/p/sandbox/sandpack-project-forked-kktt89?file=%2Fapp.tsx%3A14%2C6
<img width="1439" alt="Screenshot 2024-01-22 at 2 03 07 AM" src="https://github.com/ant-design/ant-design/assets/27697052/b7ca1498-51b7-4504-b1aa-2362fa451898">
Actual use case in app is, we customised button border Radius and expected the same to be in PopConfirm buttons as well. 

### What is expected?

Button.borderRadius is available in token (useToken) and should not throw type issue while using in application.

### What is actually happening?

Throws type issue if we use the token available in token json.

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | All Browser |

**Comment by zombieJ** [comment]
ComponentToken is only for target component. Button is Popconfirm is also use Button's ComponentToken. In your case, I guess use global token instead of set component level is better.

**Comment by Aarthysekar** [comment]
@zombieJ , 
Button border radius is not affecting the Popconfirm buttons. We had to manually map that to pop confirm buttons. Could you check please
<img width="1439" alt="Screenshot 2024-01-22 at 1 19 41 PM" src="https://github.com/ant-design/ant-design/assets/27697052/f32ce338-adb3-41b2-98be-6e819a3a6cf8">
