### ISSUE TITLE
Tooltip使用自定义组件，hover失效

### ISSUE THREAD

**Issue by Aoyimiyak** [ant-design/ant-design#47096]
### Reproduction link

[https://codepen.io/qqvfgmab-the-builder/pen/bGZRQrB](https://codepen.io/qqvfgmab-the-builder/pen/bGZRQrB)

### Steps to reproduce

鼠标悬浮在黑色div内，无法出现Tooltip提示内容，当给自定义组件外加一个div后，功能恢复正常。

### What is expected?

功能正常

### What is actually happening?

功能不正常

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome120.0.6099.225 |

**Comment by li-jia-nan** [comment]
![image](https://github.com/ant-design/ant-design/assets/49217418/f44c3bcc-ad89-4fc2-bd7c-b4a40f888bd9)

**Comment by li-jia-nan** [comment]
props 透传给自定义组件就行了：`<div {...props} />`

**Comment by Aoyimiyak** [comment]
function App() {
  const custRef = useRef(null)
  return (
    <>
      <Tooltip
        title={'nihao'}
        placement={'right'}
        arrow={{ pointAtCenter: true }}
        destroyTooltipOnHide
        color='black'
        mouseEnterDelay={0.1}
        trigger={['hover', 'click']}
        overlayInnerStyle={{
          color: '#9aa8bb',
          padding: '8px 16px',
          borderRadius: '8px',
          fontSize: '12px'
        }}
      >
        <Icon ref={custRef} />
      </Tooltip>
    </>
  )
}
我这样使用不需要传props，这种情况怎么做？
