### ISSUE TITLE
在微前端框架micro-app中react 使用antd 的dropdown组件显示异常、定位一直在左上角

### ISSUE THREAD

**Issue by wdm-coding** [ant-design/ant-design#47094]
### Reproduction link

[https://wdm-oss.oss-cn-beijing.aliyuncs.com/logo/dropdown-%E4%B8%8D%E5%87%BA%E7%8E%B0.mp4](https://wdm-oss.oss-cn-beijing.aliyuncs.com/logo/dropdown-%E4%B8%8D%E5%87%BA%E7%8E%B0.mp4)

### Steps to reproduce

在微前端框架micro-app中react 使用antd 的dropdown组件显示异常

### What is expected?

正常显示

### What is actually happening?

显示异常、定位一直在左上角

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | window |
| Browser | chrome |

**Comment by wizardpisces** [comment]
相同的 antd 跟 react 版本，遇到了同样的问题，dropdown 都是异常的；不确定是 antd 的问题还是

**Comment by wmy94827** [comment]
+1 如何处理呀，Select弹框也有问题

**Comment by lpw171758** [comment]
> +1 如何处理呀，Select弹框也有问题

求解决方式啊，阿里的大佬们。
