### ISSUE TITLE
Throw TypeError: Cannot read properties of null (reading 'firstChild') when use with Remix

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design#47095]
### Reproduction link

[https://github.com/yutingzhao1991/remix-antd-bug](https://github.com/yutingzhao1991/remix-antd-bug)

### Steps to reproduce

- init with create-remix
- add antd Button https://github.com/yutingzhao1991/remix-antd-bug/commit/324f42e93605db5880300400b8793847682f49d1

### What is expected?

Not throw Error

### What is actually happening?

Throw TypeError: Cannot read properties of null (reading 'firstChild')

<img width="933" alt="image" src="https://github.com/ant-design/ant-design/assets/1061968/38691614-0d29-40b7-8361-937f3eb0974a">

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | ^18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by yutingzhao1991** [comment]
hmm... It's throw by a chrome extension https://chromewebstore.google.com/detail/sider-chatgpt-sidebar-+-g/difoiogjjojoaoomphldepapgpbgkhkb

**Comment by dkjonzy2** [comment]
Can you elaborate on this issue? It is occurring for ~10% of users in production for us

**Comment by jesse996** [comment]
i have the same error ,no chrome extension

**Comment by yoyo837** [comment]
> i have the same error ,no chrome extension

Please provide a reproduction and open a new issue for that.

**Comment by jesse996** [comment]
> > i have the same error ,no chrome extension
> 
> Please provide a reproduction and open a new issue for that.

use this template[remix spa template](https://github.com/remix-run/remix/tree/main/templates/spa)  ,
then ` npm install antd`
use any antd component will cause this error `Throw TypeError: Cannot read properties of null (reading 'firstChild')`

**Comment by mrhocuong** [comment]
> hmm... It's throw by a chrome extension https://chromewebstore.google.com/detail/sider-chatgpt-sidebar-+-g/difoiogjjojoaoomphldepapgpbgkhkb

Hey, in my case this comment is correct. I disable the Sider extension then it works. how and why u find out that? interesting
