### ISSUE TITLE
[Modal] Open Modal should not change body width and layout

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#47092]
### Reproduction link

[https://ant-design.antgroup.com/components/modal](https://ant-design.antgroup.com/components/modal)

### Steps to reproduce

- Related issue: #30112

1. Visit reproducible link
2. Open Modal demo
3. View body width and layout change

![2024-01-22 14-49-11 2024-01-22 14_51_12](https://github.com/ant-design/ant-design/assets/14918822/1fa9d306-a434-45e7-93dc-091a4ce2c6ea)

### What is expected?

- Open Modal should not change body width and layout.

### What is actually happening?

- Open Modal changed body width and layout.

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | ^18.0.0 |
| System | windows 10 |
| Browser | Chrome 120.0.6099.225 |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/30112#issuecomment-818373693

**Comment by MadCcc** [comment]
Fixed 元素不受 body 的影响，但这个特性主要是为了解决 body 的偏移问题
