### ISSUE TITLE
Collapse 如何默认展开全部

### ISSUE THREAD

**Issue by ascoders** [ant-design/ant-design#471]

**Comment by ascoders** [comment]
还有个优化点，展开后又箭头可以动画改成朝下

**Comment by afc163** [comment]
箭头应该是 bug ，我来改下。

**Comment by afc163** [comment]
使用 `defaultActiveKey={[ 这里把所有 key 都放进来就好 ]}` 。

**Comment by ascoders** [comment]
外层无法预知内部key的值怎么办，有考虑出一个参数吗，那样方便

**Comment by afc163** [comment]
无法预计内部 key 这个不成立呀。

**Comment by ascoders** [comment]
就算把key放进来也挺麻烦的，例如panel是数组循环生成，为了展开全部而传入[0,1,2,3..]这个逻辑应该由组件完成比较合理。直接默认展开就行了

**Comment by zhw2590582** [comment]
就算我能预知所有key，并且保存在更新前保存在state，然而defaultActiveKey还是无法展开全部

**Comment by UnicornXU** [comment]
一开始获取到的是空数组,而后得到才是所有key值,问怎样才能展开全部

**Comment by jasonlbw** [comment]
@afc163 ,<Collapse accordion defaultActiveKey={defaultActiveKey}>,我这里的 defaultActiveKey 依赖于接口，如果返回一个就展开，返回多个就全不展开，但是接口回来之后 defaultActiveKey 不生效

**Comment by vaynevayne** [comment]
同问, 非受控模式下,很难用啊
