### ISSUE TITLE
如何禁止 InputNumber 通过鼠标滚动去改变值？

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design#47109]
### What problem does this feature solve?

我鼠标悬停在 InputNumber上的时候， 只要滑动鼠标滚轮就会改变value 。  在一些场景中 InputNumber多了 就最容易发生这样的事情了

### What does the proposed API look like?

希望能用一个属性去关闭 鼠标中的滚轮 事件、

[你们可以在这里尝试鼠标停留一会儿后 往下滑动的时候 也会改变](https://ant.design/components/input-number-cn#input-number-demo-status)

**Comment by afc163** [comment]
wheel={false}
