### ISSUE TITLE
antd的Cascader  级联的下拉层级太多了，每层的label都很长，展示的下拉框都超出频幕了

### ISSUE THREAD

**Issue by chenhanqiang** [ant-design/ant-design#47117]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-nzkx4k?file=%2Findex.js%3A60%2C1)

### Steps to reproduce

点开下拉框点到最后一个层级

### What is expected?

下拉框的弹出层都展示在屏幕内

### What is actually happening?

点开下拉框点到最后一个层级，目前有五层级 ，每层有一两条数据的label比较长，但是点到最后一级第五层，整个横向宽度还是超出屏幕之外。搜索时会聚合所有层级的label，可能也会超出屏幕。严重影响用户体验

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | macOs/window |
| Browser | 谷歌   120.0.6099.216 |

---
抽屉的form表单的一个项，表示一个物品的类型

**Comment by Wxh16144** [comment]
`label` 是一个 ReactNode 可以自己设置一个最大宽度写逻辑

**Comment by chenhanqiang** [comment]
这种情况下，添加showSearch属性就失效了，啥都搜索不到了，有没有办法即支持搜索又支持像上面那样省略呢
