### ISSUE TITLE
InputNumber禁用鼠标滚轮事件

### ISSUE THREAD

**Issue by cuibeihong** [ant-design/ant-design#47115]
### What problem does this feature solve?

新版本react InputNumber开启支持了鼠标滚轮，但是没有一个关闭该功能的属性，个人认为这种升级应该是新增支持(默认关闭)，而不是默认支持，举例：在长列表中有多个InputNumber输入框(商品详情sku、自定义表单),当使用者滚动页面时光标定位到输入框，会直接改变数值，而大部分用户会无意识这个改变，甚至无法还原原输入框内的数值，这完全是一个高危操作

### What does the proposed API look like?

期望InputNumber提供是否开启鼠标滚轮属性

**Comment by MadCcc** [comment]
目前的交互不合理，我们会修改

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/47109#issuecomment-1905401352
