### ISSUE TITLE
Virtual Table is not able to scroll horizontally in mobile device

### ISSUE THREAD

**Issue by chuenchuen53** [ant-design/ant-design#47113]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/virtual-list-antd-5-13-2-7qkw44)

### Steps to reproduce

1. open https://codesandbox.io/p/sandbox/virtual-list-antd-5-13-2-7qkw44 or https://ant.design/components/table#components-table-demo-virtual-list in Android phone or IPhone.
2. try to scroll horizontally

### What is expected?

Able to scroll horizontally in mobile device

### What is actually happening?

Unable to scroll horizontally in mobile device

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | Android, IOS |
| Browser | Chrome, Safari |

**Comment by linxianxi** [comment]
Is it because the width is not enough? Try removing fixed

**Comment by chuenchuen53** [comment]
> Is it because the width is not enough? Try removing column fixed

Removing all fixed column still not able to scroll horizontally.

**Comment by hungtcs** [comment]
I have the same issues here, and sometimes, holding Shift and scroll the mouse wheel does not scroll horizontally.

**Comment by charlieTrigonal** [comment]
What version will this be fixed? I have a production release waiting for this fix as we have changed to the virtual table

**Comment by VasilNikolov** [comment]
Same issue on our application.

**Comment by zdJOJO** [comment]
如何解决 ， 目前自己用的别的虚拟表。 真的无语

**Comment by hungtcs** [comment]
@zdJOJO  可以用之前的 react-window 方案

https://github.com/ant-design/ant-design/blob/527c71d207f0eb76d301a32594e47c9af19cb75b/components/table/demo/virtual-list.tsx

**Comment by hairgc** [comment]
同遇到，什么时候修复，有计划吗？
