### ISSUE TITLE
表头固定在一些特殊条件下表头的colgroup元素消失的问题

### ISSUE THREAD

**Issue by LvZhenXiang** [ant-design/ant-design#47114]
### Reproduction link

[https://stackblitz.com/edit/react-afwbca?file=demo.tsx](https://stackblitz.com/edit/react-afwbca?file=demo.tsx)

### Steps to reproduce

使用表头固定、scroll的x为max-content、datasource的值为[]并且开启表格行可选择rowSelection

### What is expected?

期望表头宽度能正常显示

### What is actually happening?

表格没数据时表头的colgroup元素消失导致列宽度显示异常

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | 18.2.0 |
| System | windows |
| Browser | Chrome 119.0.6045.200 |

**Comment by zombieJ** [comment]
给选择列也加一个宽度：

https://stackblitz.com/edit/react-afwbca-a12g46?file=demo.tsx

**Comment by LvZhenXiang** [comment]
> 给选择列也加一个宽度：
> 
> https://stackblitz.com/edit/react-afwbca-a12g46?file=demo.tsx

ok
