### ISSUE TITLE
二维码组件暗色模式样式没覆盖到位！！！

### ISSUE THREAD

**Issue by ayangweb** [ant-design/ant-design#47126]
### What problem does this feature solve?

status 在除了 active 之外有覆盖层的情况下，暗色模式下背景颜色仍为白色！

https://ant-design.antgroup.com/components/qr-code-cn?theme=dark#qr-code-demo-status

### What does the proposed API look like?

<img width="647" alt="image" src="https://github.com/ant-design/ant-design/assets/75017711/2024aa15-f732-46a2-9a8f-de6c4d0ce97a">

**Comment by kampiu** [comment]
或许你可以暂时使用 bgColor 结合主题变化来填充对应的背景颜色
