### ISSUE TITLE
form.setFieldValue和Form.List同时使用时的问题

### ISSUE THREAD

**Issue by AlanQtten** [ant-design/ant-design#47133]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/form-list-pc2859?file=%2Fdemo.tsx)

### Steps to reproduce

点击`delete box0`按钮

### What is expected?

设置`boxes`为传入的新值(长度为1的数组)

### What is actually happening?

`boxes`在setFieldValue明确传入`长度为1的数组`时，长度仍然为2，多了一个莫名其妙的值在数组里

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2.0 |
| System | macos Sonoma 14.2.1 |
| Browser | Chrome 120.0.6099.234 |

---
不太清楚是不是跟使用了Form.useWatch有关

**Comment by zombieJ** [comment]
你不能直接通过 `index` 作为 `key`，因为这样子去掉第一个数据，会让 React 认为是删掉了第二个并改了第一个的 Prop。这导致 Form 会设置一次对第二个数据的清空操作。对数组的渲染始终应该使用 Form.List:
https://codesandbox.io/p/sandbox/form-list-forked-25w2zr?file=%2Fdemo.tsx%3A52%2C16

PS：自行实现 List 逻辑其实也行，但是你要做一个 key 的映射管理，会非常麻烦。
