### ISSUE TITLE
Large `<Button>`'s icon size is incorrect with `hashed: false`

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#47132]
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-cqpaku?file=src%2FApp.tsx](https://stackblitz.com/edit/vitejs-vite-cqpaku?file=src%2FApp.tsx)

### Steps to reproduce

use `hashed: false` in `<ConfigProvider>`.

`cssVar: true` by itself is totally fine, but as long as you use `hashed: off`, the style overwrite is missing.

It's recommended by the doc to turn off `hashed` if `cssVar` is on. https://ant.design/docs/react/css-variables-cn#%E5%85%B3%E9%97%AD-hash

### What is expected?

Icon size should be identical to font size.

### What is actually happening?

CSS overwrite from `ant-btn-lg` is missing

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 120 |

---
Maybe check for other button size as well, I didn't test small

✅可以使用中文

**Comment by MadCcc** [comment]
Currently style without hash has some problem indeed.
https://github.com/ant-design/ant-design/pull/46609
We will make it same as hashed.

**Comment by xsjcTony** [comment]
Thanks. I'll temporarily turn `hashed` on. Is there any issue I can track of that once hashed issues are all resolved, or do we keep this open?

**Comment by MadCcc** [comment]
We will keep this issue open until styles are fixed
