### ISSUE TITLE
Add custom elements (logo, buttons) to menu component

### ISSUE THREAD

**Issue by matthiasferch** [ant-design/ant-design#47131]
### What problem does this feature solve?

Previously, using the `children` prop that has now been deprecated in favor of the `items` prop, you could add custom elements to a menu component, e.g. a logo or a row of buttons (link to user profile, log out, etc.). Using the `items` prop, this is no longer possible because it can only contain menu items.

If I place the custom elements outside the menu, they are no longer styled as part of the menu, which is particularily obvious in dark mode.

So before you could do this:

```
<Menu>
  <Image ... />
  <Menu.Item />
  <Menu.Item />
  <Menu.Item />
  <Flex>
    <Button />
    <Button />
  </Flex>
</Menu>
```

But now that syntax is deprecated.

### What does the proposed API look like?

It would be great if there were a way to add custom elements either to the `items` prop or to the menu component directly.

**Comment by zombieJ** [comment]
Menu use `ul` for dom structure, it only accept Menu.Item which is `li` is correct for a11y. The Image or Flex I believe is wrong usage. It should always wrap in Menu.Item or `items` instead:
https://stackblitz.com/edit/react-zfy7bl?file=demo.tsx,index.css
