### ISSUE TITLE
onFinish output values from FormItems inside of FormList even if the field is not being rendered

### ISSUE THREAD

**Issue by gabrielsantosdev** [ant-design/ant-design#47130]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-form-list-bug-forked-qxflsv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrqmcr3l00063p6i6tvk6ztr%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrqmcr3l00023p6ikcb9412u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrqmcr3l00033p6isnzljiqz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrqmcr3l00053p6itc36rhl2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrqmcr3l00023p6ikcb9412u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrqmcr3l00013p6iud2owy6s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrqmcr3l00023p6ikcb9412u%2522%252C%2522activeTabId%2522%253A%2522clrqmcr3l00013p6iud2owy6s%2522%257D%252C%2522clrqmcr3l00053p6itc36rhl2%2522%253A%257B%2522id%2522%253A%2522clrqmcr3l00053p6itc36rhl2%2522%252C%2522activeTabId%2522%253A%2522clrqp4zbx01db3p6ivatz0g9w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrqmcr3l00043p6iui107wha%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clrqp4zbx01db3p6ivatz0g9w%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clrqmcr3l00033p6isnzljiqz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrqmcr3l00033p6isnzljiqz%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. on Select field. Select Option 'Job'
2. Fill in Notes field that will appear.
3. Change Option on select field to 'Project'
4. Click submit

### What is expected?

The value and key of  'note' is not available in the submit payload by default.

### What is actually happening?

The value of note is still available in the payload even though the field was removed.

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 18.2.0 |
| System | MacOS Sonoma 14.2.1 |
| Browser | Edge 120.0.2210.144 |

---
This happens specifically to a FormList implementation using this approach, in a default list, this problem doesn't happen, and unless explicitly stated to maintain the field value on the payload, the value is not submitted in the onFinish method. In a simple form, this result can be achieved by looking at this example in the Form documentation: https://ant.design/components/form#components-form-demo-control-hooks

**Comment by zombieJ** [comment]
FormList itself is a Form field which means it will preset in the values. If you want to get pure value. You can use `form.getFieldsValue({ strict: true })` to get only the value from Form.Item.

ref: https://ant.design/components/form#getfieldsvalue-strict-boolean-filter-filterfunc-
