### ISSUE TITLE
火狐（Firefox）浏览器上，在Form组件中使用<input type="range">会出现异常

### ISSUE THREAD

**Issue by quantumng** [ant-design/ant-design#47147]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-dqprst?file=%2Findex.js%3A11%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrsti8jt00062a65wl3upobl%2522%252C%2522sizes%2522%253A%255B90%252C10%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrsti8jt00022a65b529w1ow%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrsti8jt00032a65yzkmasfq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrsti8jt00052a658atikf70%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrsti8jt00022a65b529w1ow%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsti8jt00012a65qs4kwklq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A20%257D%255D%257D%255D%252C%2522id%2522%253A%2522clrsti8jt00022a65b529w1ow%2522%252C%2522activeTabId%2522%253A%2522clrsti8jt00012a65qs4kwklq%2522%257D%252C%2522clrsti8jt00052a658atikf70%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsti8jt00042a656i9il4d6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrsti8jt00052a658atikf70%2522%252C%2522activeTabId%2522%253A%2522clrsti8jt00042a656i9il4d6%2522%257D%252C%2522clrsti8jt00032a65yzkmasfq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrsti8jt00032a65yzkmasfq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

在火狐（Firefox）浏览器上（Chrome上是正常的），Form组件中使用自定义表单控件，控件内使用了<input type="range">标签。当拖动range控件的滑块松开后，值会恢复到上一次选择值。在input外层div标签上监听mouseMove事件，使用e.preventDefault()可以阻止这种异常。

### What is expected?

<input type="range">标签能显示正常值

### What is actually happening?

当拖动range组件的滑块松开后，值会恢复到上一次选择值

| Environment | Info |
| --- | --- |
| antd | 5.12.2 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox 122.0 |

---
我提供的链接展示了大致的代码使用。不过在线编辑器里没能复现，但在我们本地和生产环境会有这个问题。

**Comment by MadCcc** [comment]
提供不了有效复现的话我们也不清楚是什么问题，建议先自查一下是不是有其他代码影响了行为。
