### ISSUE TITLE
Table: Display Selected Filters & Sorting Columns Immediately Above the Table

### ISSUE THREAD

**Issue by zainkhan10** [ant-design/ant-design#47145]
### What problem does this feature solve?

Currently, the table lacks the display of selected filters or sorted columns, impacting the user experience. It is crucial for users to easily identify the columns on which filters or sorting have been applied. Additionally, there is no apparent option to clear all filters.

To enhance user interaction, consider implementing the following improvements:

### Show Selected Filters and Sorting Columns:
Ensure that the table prominently displays information about the selected filters and sorted columns. This allows users to quickly understand the applied settings.

### Clear All Filters Option:
Introduce a 'Clear All' button within the interface. This button should effectively remove all applied filters and sorting from every column, restoring the table to its default state. This feature enhances user control and simplifies the interaction process.

Implementing these changes will contribute to a more intuitive and user-friendly experience, allowing users to have better visibility and control over the applied filters and sorting options.

### What does the proposed API look like?

I recommend adding a new row immediately above the table to display the selected filters and sorted columns. This new row should also feature a 'Clear All' button for convenient removal of all applied filters and sorting.

**Comment by MadCcc** [comment]
Try [ProTable](https://procomponents.ant.design/en-US/components/table?tab=api&current=1&pageSize=5) ? Or you can realize it with your design.
