### ISSUE TITLE
Typography with suffix ellipsis support cause resizeObserver loop error

### ISSUE THREAD

**Issue by Rey-Wang** [ant-design/ant-design#47159]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/hou-zhui-antd-5-13-2-forked-7n6sgw?file=%2Findex.tsx%3A6%2C1)

### Steps to reproduce

refresh the page and check the console

### What is expected?

no error

### What is actually happening?

Uncaught Error: ResizeObserver loop completed with undelivered notifications.

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 16.14.0 |
| System | Macos monterey 12.4 |
| Browser | Microsoft edge 116.0.1938.54 |

---
this scenario works well in React 18, not checked in other versions

**Comment by MadCcc** [comment]
Please provide reproduction with error.

**Comment by Rey-Wang** [comment]
@MadCcc have you ever checked the sandbox?
![image](https://github.com/ant-design/ant-design/assets/45580554/2e0fb87f-4e25-4bf7-83dc-49552ea0450a)

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/26621

**Comment by AndreyVerkhusha** [comment]
the problem still exists

**Comment by Yovven** [comment]
the problem still exists

**Comment by mcshaman** [comment]
Yes! Still ongoing problem. Would love to not have to ignore all these errors.
