### ISSUE TITLE
Remove expanded line when closing it

### ISSUE THREAD

**Issue by luisflavioms** [ant-design/ant-design#47154]
### What problem does this feature solve?

When expanding a line, a line (tr) is added, but when closing it, instead of removing it from the screen, it stays as display="none", I'm trying to make a striped table, and this is causing a bug when trying paint in odd and even lines.

### What does the proposed API look like?

Completely remove the expanded line when minimizing

![image](https://github.com/ant-design/ant-design/assets/37166820/6edb29c0-2a3c-4428-ae99-d77d071f6705)

**Comment by afc163** [comment]
What does the proposed API look like?
