### ISSUE TITLE
Controlled Dropdown component rendered at wrong position

### ISSUE THREAD

**Issue by hotzenklotz** [ant-design/ant-design#47152]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jfs2vv?file=%2Findex.js%3A21%2C29&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrtaev5u00063b6gpwelxp4t%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrtaev5u00023b6gw8aiy0wq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrtaev5u00033b6g86x1cinu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrtaev5u00053b6gkoty7elr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrtaev5u00023b6gw8aiy0wq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtaev5t00013b6geng4whf3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A29%257D%255D%257D%255D%252C%2522id%2522%253A%2522clrtaev5u00023b6gw8aiy0wq%2522%252C%2522activeTabId%2522%253A%2522clrtaev5t00013b6geng4whf3%2522%257D%252C%2522clrtaev5u00053b6gkoty7elr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtaev5u00043b6getvrtnp1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrtaev5u00053b6gkoty7elr%2522%252C%2522activeTabId%2522%253A%2522clrtaev5u00043b6getvrtnp1%2522%257D%252C%2522clrtaev5u00033b6g86x1cinu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrtaev5u00033b6g86x1cinu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

- Add a antd `<Dropdown>` as acontrolled React component to your app. Configure the dropdown to trigger on right-click, aka "contextMenu" (`trigger={["contextMenu"]}`).
- Trigger the dropdown to open as a controlled component through the `open` prop (e.g. `open={isOpen}`)
- Dropdown menu is rendered at the top left corner of the screen (0,0), partially outside of the screen

### What is expected?

The dropdown menu is supposed to open at the location of the component's DOM position or parent 

### What is actually happening?

The Dropdown menu is rendered at the top left corner of the screen (0,0), partially outside of the screen

<img width="714" alt="image" src="https://github.com/ant-design/ant-design/assets/1105056/bf59f9b3-c922-4b22-b878-1b9ed9a0d3e5">

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 16 & 18 |
| System | MacOS 14.0 |
| Browser | Chrome 120.0.6099.199 |

---
- I can reliably trigger the bug by configuring the dropdown to trigger on right-click, aka "contextMenu" (`trigger={["contextMenu"]}`). The bug does not happen with `trigger={"click"}`.
- The bug only occurs if you have never triggered the Dropdown with a right-click. It must be triggered as a controlled component  through the `open` prop.

**Comment by MadCcc** [comment]
In your scenario, I recommend you to use trigger `click` instead of `contextMenu`. `contextMenu` need mouse position, which not exist when first clicking the button.

**Comment by hotzenklotz** [comment]
Unfortunately, switching to `click` is not possible for me. I want to open a right-click context menu. For discoverability / UX we also show a little `...` (three dot) overflow menu icon to trigger the `<Dropdown>` menu. 

Here is a screenshot from our web app. Right-clicking on the tree items ("Segment 123") opens the `<Dropdown>` menu and clicking the `...` icons should also trigger the Dropdown as a controlled components through the `open` props.
<img width="389" alt="image" src="https://github.com/ant-design/ant-design/assets/1105056/962c2a99-2733-4545-8cb1-5a8adb7d75d4">

This flow works without issues in antd v4.

**Comment by philippotto** [comment]
@MadCcc Any chance that there is a fix or workaround for this issue? :pray: As mentioned above, this used to work in antd v4. I think, instead of a default position of `(0, 0)`, the position of the `<Dropdown>` child should be used.

**Comment by afc163** [comment]
@philippotto PR is welcome~

**Comment by philippotto** [comment]
Alright ;) https://github.com/react-component/trigger/pull/447
