### ISSUE TITLE
Descriptions 有边框且内容为null时显示异常

### ISSUE THREAD

**Issue by AIWWJ** [ant-design/ant-design#47151]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/fwgq67?file=%2Findex.js%3A21%2C25)

### Steps to reproduce

Descriptions.items.children值设置为null

### What is expected?

Order time 对应的内容那一列右侧有边框

### What is actually happening?

缺少边框线

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
Couldn't see preview in your codesandbox

**Comment by AIWWJ** [comment]
<img width="1139" alt="WX20240125-170049@2x" src="https://github.com/ant-design/ant-design/assets/22759507/75c20bb6-2a3e-4a67-86e3-b16eb76b16f6">

**Comment by AIWWJ** [comment]
> Couldn't see preview in your codesandbox

<img width="1139" alt="WX20240125-170049@2x" src="https://github.com/ant-design/ant-design/assets/22759507/e9059cd2-a10f-4074-be99-afcf55d404e3">
