### ISSUE TITLE
Remove the condition restrictions from the tagRender of the Select component or support custom rendering.

### ISSUE THREAD

**Issue by myersguo** [ant-design/ant-design#47165]
### What problem does this feature solve?

Custom rendering is needed after selection. For example, the values in the dropdown list are:

```javascript
 <Select
            labelInValue
            filterOption={false}
            showSearch
            onSearch={mySearch}
          //After setting optionLabelProp="label", it becomes impossible to set custom rendering content but use tagRender
            optionLabelProp="label"
>
 {options.map((user) => (
<Select.Option value={user.name}>
    <div style={{ display: 'flex', alignItems: 'center' }}>
        <Avatar src={user.photo} />
        <div>
            {user.name}
        </div>
    </div>
</Select.Option>
  ))}
</Select>
```

After selection, it needs to be custom rendered as:

```javascript
<Tooltip title={user.name}>
    <Avatar src={user.photo} />
</Tooltip>
```

Similar requirements were mentioned in the following issues:
https://github.com/ant-design/ant-design/issues/34200
https://github.com/ant-design/ant-design/issues/30903

### What does the proposed API look like?

 <Select
    valueRender={valueRender}
  />

**Comment by zombieJ** [comment]
`tagRender` is only effect on the Tag sub component, which means single select do not have this part. There are 2 way to realize this requirement:
1. `optionLabelProp`: Follow the official demo: https://ant.design/components/select#select-demo-option-label-prop
2. use `labelInValue` to HOC the Select to render `label` as you needed.

**Comment by myersguo** [comment]
> `tagRender` is only effect on the Tag sub component, which means single select do not have this part. There are 2 way to realize this requirement:
> 
> 1. `optionLabelProp`: Follow the official demo: https://ant.design/components/select#select-demo-option-label-prop
> 2. use `labelInValue` to HOC the Select to render `label` as you needed.

After setting optionLabelProp="label", it becomes impossible to set custom rendering content but use tagRender

**Comment by myersguo** [comment]
> `tagRender` is only effect on the Tag sub component, which means single select do not have this part. There are 2 way to realize this requirement:
> 
> 1. `optionLabelProp`: Follow the official demo: https://ant.design/components/select#select-demo-option-label-prop
> 2. use `labelInValue` to HOC the Select to render `label` as you needed.

The optionLabelProp setting of Select is set to label in order to concatenate all content into the label for data transmission (when using the component, there is a need to obtain the label value in addition to the value). However, the logic for custom rendering is still necessary.
