### ISSUE TITLE
在使用Input.TextArea时自动添加用于处理可能情况的隐藏textarea，是否可以给他添加一个name或者id属性

### ISSUE THREAD

**Issue by Lomnus** [ant-design/ant-design#47177]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-8gsy7n?file=%2Findex.js)

### Steps to reproduce

使用Input.TextArea

### What is expected?

给这个自动添加的隐藏textarea设置一个name，不要在site上出现issue：A form field element should have an id or name attribute

### What is actually happening?

只要使用该组件就会有这个Issue: A form field element should have an id or name attribute

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome latest |

**Comment by afc163** [comment]
<img width="609" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/f88a38c5-644f-4cae-8d60-a0783a053972">

你给的例子会加上 name 属性。

**Comment by Lomnus** [comment]
@afc163 不是我手写的TextArea， 而是在使用TextArea组件时会自动添加一个隐藏的TextArea, iframe看起来没起效
![image](https://github.com/ant-design/ant-design/assets/50653281/f265f17c-5dd8-417f-8454-eca874cbc43e)

**Comment by Lomnus** [comment]
@li-jia-nan

**Comment by zombieJ** [comment]
这个是测量用的，为什么需要对它进行操作？

**Comment by Lomnus** [comment]
> 这个是测量用的，为什么需要对它进行操作？本身已经用 `aria-hidden` 藏掉了。

@zombieJ  因为会报improvement issue，虽然没有影响，但我建议加个name，很方便的事情，没有issue不是更好吗？
希望能加一下，谢谢

**Comment by zhe-he** [comment]
当浏览器碰到表单元素时，如果他没有name属性或者id属性，会报一个警告，虽然无关大雅，但对于有警告洁癖的人来说，特别难以忍受，总想把他解决才能释怀。警告截图如下：
<img width="451" alt="image" src="https://github.com/ant-design/ant-design/assets/11306583/a5f339b2-179d-4085-b88f-0b7bce9dbd58">

**Comment by zhe-he** [comment]
https://github.com/react-component/textarea/pull/59
