### ISSUE TITLE
Input and InputNumber do not have onKeyUp props

### ISSUE THREAD

**Issue by jch254** [ant-design/ant-design#4717]
#### Environment

- antd version: 2.6.4
- OS and its version: macOS Sierra v10.12.2
- Browser and its version: Google Chrome v55.0.2883.95

#### What did you expect?

Input and InputNumber do not have onKeyUp props. As the user types I need to run validation and if valid, send a request to the server with the current value of the field. onKeyDown on gives me the value of pressed key and I can access the previous value (before the key press) through event.target.value. It's possible to piece together the current value using these but onKeyUp would be more reliable.

#### What happened?

Input and InputNumber do not have onKeyUp props.

#### Re-producible online demo

https://ant.design/components/input/
https://ant.design/components/input-number/

**Comment by afc163** [comment]
Will be fixed in antd@2.7.0

**Comment by jch254** [comment]
谢谢 @afc163 !
