### ISSUE TITLE
Submenu label is not visible when hashed is false

### ISSUE THREAD

**Issue by Saidnazar08** [ant-design/ant-design#47182]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/menu-themes-antd-5-13-2-forked-j2gzkx)

### Steps to reproduce

Set hashed false
Set algorithm to the default
Create a menu with dark theme
Create a submenu for it

### What is expected?

The submenu label is visible

### What is actually happening?

The label color is black, not white

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2 |
| System | Windows 11 |
| Browser | Chrome 120.0 |

**Comment by MadCcc** [comment]
Trace https://github.com/ant-design/ant-design/issues/47132
