### ISSUE TITLE
Tree 组件 defaultExpandAll 的计算存在问题

### ISSUE THREAD

**Issue by weekbin** [ant-design/ant-design#47180]
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qcjyfr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clruy14xd00063b6fungxb1xp%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clruy14xd00023b6ferl88wj8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clruy14xd00033b6ffbqjujni%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clruy14xd00053b6fgvtc6eya%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B62.15172782379996%252C37.84827217620004%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clruy14xd00023b6ferl88wj8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clruy14xd00013b6fgg80wmpc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clruy14xd00023b6ferl88wj8%2522%252C%2522activeTabId%2522%253A%2522clruy14xd00013b6fgg80wmpc%2522%257D%252C%2522clruy14xd00053b6fgvtc6eya%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clruy14xd00043b6fla7wkfpj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clruy14xd00053b6fgvtc6eya%2522%252C%2522activeTabId%2522%253A%2522clruy14xd00043b6fla7wkfpj%2522%257D%252C%2522clruy14xd00033b6ffbqjujni%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clruy14xd00033b6ffbqjujni%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

移动 Demo 中的 p4 节点到 p2 与 p3 之间的位置，使其成为 p1, p3 的同级别节点。

### What is expected?

在配置了 defaultExpandAll 属性时，可以将 p4 节点移动到 p3 节点上方，使其成为 p1, p3 节点到兄弟节点。

### What is actually happening?

在配置了 defaultExpandAll 属性时，将 p4 节点移动到 p3 节点上方，只能成为 p2 的兄弟节点或子节点。

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.x |
| System | macOS 13.3 (22E252) |
| Browser | Chrome Version 120.0.6099.234 (Official Build) (arm64) |

---
拖拽功能在使用 defaultExpandAll 进行初次渲染时，存在一定的问题。

该问题初步判断是由于 defaultExpandAll 将所有节点都默认配置为展开节点了，即 expandKeys 当中包含了实际上没有子节点的节点。

rc-tree 关于节点落点的代码判断应该是在这里
```ts
  // Only allow cross level drop when dragging on a non-expanded node
  if (!expandKeys.includes(initialAbstractDropNodeKey)) {
    for (let i = 0; i < rawDropLevelOffset; i  = 1) {
      if (isLastChild(abstractDropNodeEntity)) {
        abstractDropNodeEntity = abstractDropNodeEntity.parent;
        dropLevelOffset  = 1;
      } else {
        break;
      }
    }
  }
```

期望 defaultExpandAll 计算 expandKeys 属性的时候，可以将实际上没有子节点的叶子结点排除在外。

**Comment by zombieJ** [comment]
好细
