### ISSUE TITLE
deps: upgrade rc-slider to 6.0.0

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4719]
http://react-component.github.io/slider/

> 6.0.0 / 2017-01-25
> [Breaking Change] Re-design and refactor, almost a new UI component.

motivation: https://github.com/react-component/slider/issues/205

* [ ] Adapter to old API
* [ ] Test case for old API

**Comment by benjycui** [comment]
API 还是不调整了，和原来一致。

**Comment by afc163** [comment]
有啥变化？

**Comment by benjycui** [comment]
rc-slider@6.0 的重构是为了 antd-mobile 那边更细粒度的按需加载，然后 Tooltip、滑块相关的定制性更高。

但 antd 这边好像没这个需求，故保持不变。
