### ISSUE TITLE
All popconfirm, popover and modal components are blinking in  Ant Design

### ISSUE THREAD

**Issue by KD1920** [ant-design/ant-design#47209]
### Reproduction link

[https://stackblitz.com/edit/react-antd-blink-issue?file=package.json,index.js,index.html](https://stackblitz.com/edit/react-antd-blink-issue?file=package.json,index.js,index.html)

### Steps to reproduce

To reproduce the issue you have to open the modal and close it. At the closing point you will see the modal blink's for once. Like close and open again and then close again in an instance.

### What is expected?

I can neither change the packages nor change the version of those packages. With that I want to close the modal without getting blink.

### What is actually happening?

Modal blinks when close. Open again and close again in an instance.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | Windows |
| Browser | Chrome latest |

---
Please help me solve this issue without changing the version of the packages.

**Comment by zombieJ** [comment]
Thanks for feedback. v3 is no longer in maintain since 2020. You can consider to lock React to 16 instead:

https://stackblitz.com/edit/react-antd-blink-issue-br5msc?file=package.json,index.js
