### ISSUE TITLE
On hover of antd Select options shows tooltip

### ISSUE THREAD

**Issue by lohi-Kosh** [ant-design/ant-design#47206]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/select-options-hover-n8tg4y?file=%2Fdemo.js%3A40%2C20)

### Steps to reproduce

Open the select dropown and hover on any option for few secs. A tooltip appears for hover of the option.

### What is expected?

Is there any prop to control that or any way to remove that.

### What is actually happening?

The tooltip text is always coming on hover of the options.

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2.0 |
| System | Ventura 13.2.1  |
| Browser | Chrome Version 120.0.6099.109 |

**Comment by afc163** [comment]
You should use feature request template.

<img width="1141" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/be7208ad-ecb1-4104-93fa-b39ddf579438">
