### ISSUE TITLE
add prop for Layout with Sider

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#4720]
Right now we have to use like this:
```jsx
<Layout>
  <Layout.Sider>...</Layout.Sider>
</Layout>
```
in that case we have classname **ant-layout-has-sider**

But if we have custom Sider like this:
```jsx

const Sider = (props) => <Layout.Sider>.....</Layout.Sider>

<Layout>
  <Sider>...</Sider>
</Layout>
```

in that case we don't have classname **ant-layout-has-sider**, because you are checking for property name:
```js
ele && ele.props && ele.props.name === 'Sider'
```

so we can fix it by 2 ways now:
1) manually add classname **ant-layout-has-sider** to Layout, but I would consider it like _internal_ feature, this classname can be changed in future

2) manually add property **name** to our custom Side, but I would consider it like _internal_ feature too, you can change that logic in future.

As possible fix I would recommend next fix add property **withSider** to Layout:
```jsx
Layout.propTypes = {
  withSider: PropTypes.bool
}
```

and check it like this:
```typescript
    const { prefixCls, className, children, name, ...others } = this.props;
    let hasSider = this.props.hasSider;

    if (name === 'Layout') {
      React.Children.forEach(children, (ele: React.ReactElement<any>) => {
        if (ele && ele.props && ele.props.name === 'Sider') {
          hasSider = true;
        }
      });
    }
```

and use it like this:
```jsx
const Sider = (props) => <Layout.Sider>.....</Layout.Sider>

<Layout withSider>
  <Sider>...</Sider>
</Layout>
```

**Comment by benjycui** [comment]
@ddcat1115 update this check as `Breadcrumb`? see: https://github.com/ant-design/ant-design/pull/4673

**Comment by benjycui** [comment]
I think `withSider` is a little confused, and it is hard to understand when to use it.

**Comment by plandem** [comment]
well, right now I'm using it like this (pass **name** prop manually):
```jsx
import { Sider, Header, Footer, Content } from '../../components/layout';
....
			<Layout className='app'>
				<Sider name='Sider' {...siderProps}/>
				<Layout>
					<Header name='Header' {...headerProps} />
					<Content name='Content'>
						<div className='container'>
							<Router.Match path='/' handler={()=><div>aaaaa</div>}/>
							<Router.Miss handler={NotFound}/>
						</div>
					</Content>
					<Footer name='Footer'/>
				</Layout>
			</Layout>
```

**Comment by plandem** [comment]
@benjycui about confusing  _withSider_ - right now it's like magic - internal implementation (check value of secret property and if it equals special value, then add additional classname). For me it looks like place for public boolean property - like we use **inline** at Form:
```jsx
 <Form inline onSubmit={this.handleSubmit}>
```

**Comment by benjycui** [comment]
Actually, we need a solution to work with both of customized component and RHL. And, I can find a perfect solution now. But the solution in #4673 can make `antd` work with RHL and customized component.
