### ISSUE TITLE
Button 设置字体大小 ，在chorme 下不起作用，在 safari 下可以。

### ISSUE THREAD

**Issue by lansefengxinzi** [ant-design/ant-design#4721]
![0d25add6-be91-4096-bd6b-03ff15a77497](https://cloud.githubusercontent.com/assets/12048313/22292255/59189330-e345-11e6-974f-3ba4785a2a56.png)
在 safari，

在chorme
![7aaf6fc6-2273-4a1b-a332-01f7f962ce59](https://cloud.githubusercontent.com/assets/12048313/22292304/7b4874c0-e345-11e6-947a-fa67a1f44170.png)

button 样式：
const buttonDefaultStyles = {
    width: "83px",
    height: "30px",
    fontSize: "10px",
};

**Comment by afc163** [comment]
chrome 不支持小于 12px 的中文字体，这个和 antd 无关。建议 Google 一下相关解决方案。

**Comment by lansefengxinzi** [comment]
好的，谢谢！
