### ISSUE TITLE
Table row overlaps with fixed columns if you change rowHoverBg via component token

### ISSUE THREAD

**Issue by MaruBlare** [ant-design/ant-design#47212]
### Reproduction link

[https://stackblitz.com/edit/react-4uhuwq?file=demo.tsx](https://stackblitz.com/edit/react-4uhuwq?file=demo.tsx)

### Steps to reproduce

1) Modify Table component token 'rowHoverBg' 
2) Fix one or more columns (no matter which side)

### What is expected?

In tables with modified 'rowHoverBg' token row's content doesn't overlap with the fixed columns and always is under it.

### What is actually happening?

If you change 'rowHoverBg' using Table component token, the content of the row is also visible over the fixed columns.

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18.2.0 |
| System | mac |
| Browser | Yandex |

**Comment by MaruBlare** [comment]
The problem is in the background color – we shouldn't use opacity to avoid this case.
Is there any token to set the background color for fixed columns, which will be shown on hover?

**Comment by afc163** [comment]
Try to avoid transparent background color.

**Comment by MadCcc** [comment]
Transparent background color will make rows overlap, try to transform it into a solid color (alpha is 1)
