### ISSUE TITLE
Add option for <Spin> to spinning in the center of the visible part of div instead of geometrical center.

### ISSUE THREAD

**Issue by abonec** [ant-design/ant-design#4722]
I have a very high table and when processing of this table I activate Spin. But because it is very high table spinner is located in the geometrical center of that table and user can't see it. Can you add an option to show spinner in the center of the visible area instead of geometrical? Or option to disable spinning at all - just to blur the element.

**Comment by afc163** [comment]
You can set `style.height` of Spin to change spinner position.

http://codepen.io/anon/pen/ggxjor?editors=001

**Comment by abonec** [comment]
I changed this example to real world one where I have long content without predefined height and this approach doesn't work.
http://codepen.io/anon/pen/rjzrKq?editors=001

**Comment by afc163** [comment]
Just fix the height: http://codepen.io/anon/pen/jyLvMv?editors=001

**Comment by abonec** [comment]
I see that bottom text is in the wrong position but it doesn't matter because this approach can't show spinner in the position when the user is scrolled.

If user trigger spinner in the middle of that block user won't see it. It should be a dynamic approach in the spinner component by the option.

**Comment by afc163** [comment]
Use className is a better way: http://codepen.io/anon/pen/rjzrKq?editors=0110

**Comment by afc163** [comment]
I will consider that and you can try to propose a PR if you have nice solution.

**Comment by abonec** [comment]
I mediocre frontend developer and even worse html\css developer. I just use your nice components.

**Comment by afc163** [comment]
Added a max-height limit for big height content.
