### ISSUE TITLE
官方文档，暗黑模式 展示有问题

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#47223]
### Reproduction link

[https://ant-design.antgroup.com/components/qr-code-cn?theme=dark](https://ant-design.antgroup.com/components/qr-code-cn?theme=dark)

### Steps to reproduce

直接访问连接（win10 + chrome）

https://ant-design.antgroup.com/components/qr-code-cn?theme=dark

![image](https://github.com/ant-design/ant-design/assets/29728228/0787f50f-3d80-4f9c-a977-972c2902335b)

![image](https://github.com/ant-design/ant-design/assets/29728228/6ee36609-8e09-4ce4-a782-15fbba103729)

![image](https://github.com/ant-design/ant-design/assets/29728228/07adbcfc-bf5f-47f2-b345-cd492372bfdb)

### What is expected?

组件应该暗黑模式

### What is actually happening?

部分组件样式错误

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="920" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/d1c89070-5383-4628-b9bb-402d9ab09ed7">

标题也有问题。

**Comment by MadCcc** [comment]
duplicate of https://github.com/ant-design/ant-design/issues/46729

**Comment by afc163** [comment]
<img width="550" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/d1fbd1f2-00eb-472a-8747-8f51092bad88">
标题依然看不见。

**Comment by afc163** [comment]
Fixed.
