### ISSUE TITLE
官方文档显示代码无法拖住滑动条左右滑动

### ISSUE THREAD

**Issue by mengshouer** [ant-design/ant-design#47230]
### Reproduction link

[https://ant-design.antgroup.com/components/auto-complete-cn](https://ant-design.antgroup.com/components/auto-complete-cn)

### Steps to reproduce

所有超过展示长度的显示代码，都无法左右拖动

![Kapture 2024-01-30 at 14 58 57](https://github.com/ant-design/ant-design/assets/36481080/41e97d6f-0304-4424-a99f-07f3f7498c7e)

### What is expected?

可以左右拖动

### What is actually happening?

无法左右拖动

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | / |
| System | mac M2 14.2.1 |
| Browser | Chrome Version 121.0.6167.85 & Firefox/121.0 |

**Comment by MadCcc** [comment]
被伪类挡住了。。
