### ISSUE TITLE
Tooltip delay option

### ISSUE THREAD

**Issue by rdworth** [ant-design/ant-design#4724]
Feature request: I love the tooltip (and popover) and want to use it where I would otherwise use the native browser tooltip via the title attribute. One feature that's missing for this is a delay on hover. Right now I'm using tooltip but without a delay it always pops up right away, even if the mouse just happens to glance across the trigger element.

**Comment by benjycui** [comment]
It had been support, and I will update the documentation.

**Comment by benjycui** [comment]
see: 	879bc93
