### ISSUE TITLE
Regarding the issue of excessive use of Segmented components

### ISSUE THREAD

**Issue by wuxin666789** [ant-design/ant-design#47255]
### What problem does this feature solve?

https://github.com/ant-design/ant-design/assets/86199312/77fda679-04ca-4bc7-91b7-d494516b44c8

I can maintain a custom border radius value when I want to transition

### What does the proposed API look like?

Segmented token, there is a border radius that can control the overall border radius value of an item

**Comment by zombieJ** [comment]
https://codesandbox.io/p/sandbox/ji-ben-antd-5-13-2-forked-vygvtv?file=%2Fdemo.tsx%3A10%2C29

**Comment by wuxin666789** [comment]
not open link

**Comment by zombieJ** [comment]
Updated.
