### ISSUE TITLE
How to switch from locally scoped css vars to that they are created at html tag, at least the general variables?

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design#47253]
### Reproduction link

[https://ant.design/docs/react/css-variables#advanced](https://ant.design/docs/react/css-variables#advanced)

### Steps to reproduce

<ConfigProvider theme={{ cssVar: true, hashed: false }}>
  <App />
</ConfigProvider>

### What is expected?

Allow to configure to place variables globally?\
final objective variable to exist on :root / html  \
ex: :root{ \
--ant-color-primary: #3235e4;\
    --ant-color-success: #3eb759;\
    --ant-color-warning: #ff843f;\
    --ant-color-error: #ff4f4f;\
    --ant-color-info: #3235e4;\
    --ant-color-link: #3235e4;\
 }  \
or  \
html{   \
--ant-color-primary: #3235e4;\
    --ant-color-success: #3eb759;\
    --ant-color-warning: #ff843f;\
    --ant-color-error: #ff4f4f;\
    --ant-color-info: #3235e4;\
    --ant-color-link: #3235e4;\
 }

### What is actually happening?

variables are created locally and duplicated, so that we can reuse the variables in common style scss / css / less etc

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18 |
| System | Windows 10 |
| Browser | Version 120.0.6099.225 (Official Build) (64-bit) |

**Comment by susanforme** [comment]
(English is not my native language, using machine translation)
You can introduce a useToken hook in the layout or any other HOC to retrieve the token object
```tsx
import type { ThemeConfig } from 'antd';
import { theme } from 'antd';
import { createRoot } from 'react-dom/client';

const { getDesignToken, useToken } = theme;

```
Then write it into the HTML
```ts
  export function setCssVariable(
    cssVars: Record<string, string>,
    id = 'global-css-variable',
  ): void {
    const oldElement = document.getElementById(id);
    const style =
      oldElement ?? document.createElement('style');
    style.id = id;
    let cssText = ':root{';
    Object.entries(cssVars).forEach(([key, value]) => {
      cssText += `--${key
        .replace(/([A-Z])/g, '-$1')
        .toLowerCase()}:${value};`;
    });
    cssText += '}';
    // clear and set
    style.innerHTML = cssText;
    if (!oldElement) {
      document.head.appendChild(style);
    }
  }
```

**Comment by MadCcc** [comment]
Actually we will not provide css vars on `:root` because all tokens are computed in runtime, and each theme has own scope.
If you prefer to place default token as css vars on `:root`, just try something like above.

**Comment by hugobarragon** [comment]
Thanks, I am already doing it manually, with useToken and injecting on head, but i found a funny way when analysing source code , to inject on html tag this way 
```
 <ConfigProvider
      prefixCls={prefixCls}
      theme={{
        algorithm: theme.defaultAlgorithm,
        cssVar: { prefix: prefixCls, key: "{} html" },
        hashed: false,
      }}
    >
```

**Comment by york-chen** [comment]
thanks @hugobarragon ,that help me a lot

**Comment by Ronchan0805** [comment]
> Thanks, I am already doing it manually, with useToken and injecting on head, but i found a funny way when analysing source code , to inject on html tag this way
> 
> ```
>  <ConfigProvider
>       prefixCls={prefixCls}
>       theme={{
>         algorithm: theme.defaultAlgorithm,
>         cssVar: { prefix: prefixCls, key: "{} html" },
>         hashed: false,
>       }}
>     >
> ```

This way you do inject styles into html, but it doesn't work with component tokens.
用这种方式确实能把样式注入html，但是对组件token无效.
