### ISSUE TITLE
`<Card />` 的 title 的 `font-size` 在 `hashed: false` 模式下不对, 被复写为了基础字号

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#47257]
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-sqshjc?file=src%2FApp.tsx](https://stackblitz.com/edit/vitejs-vite-sqshjc?file=src%2FApp.tsx)

### Steps to reproduce

启用 `hashed: false` 对比一下

### What is expected?

应该还是`16px`

### What is actually happening?

实际是`14px`, 被复写了

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 121 |

---
感觉这 `hashed: false` 开不了一点啊🤣 BUG太多了

**Comment by MadCcc** [comment]
已修复：https://github.com/ant-design/ant-design/pull/46609
5.13.4 发布
