### ISSUE TITLE
移动设备时开启表格虚拟滚动后无法横向滚动

### ISSUE THREAD

**Issue by zsj9705** [ant-design/ant-design#47256]
### Reproduction link

[https://hxv3xg.csb.app/](https://hxv3xg.csb.app/)

### Steps to reproduce

https://ant-design.gitee.io/components/table-cn#components-table-demo-virtual-list
使用官方虚拟列表示例，使用设备模拟为移动端设备。无法使用拖动进行横向滚动。

### What is expected?

表格开启虚拟列表后在移动设备时可以进行横向滚动。

### What is actually happening?

表格开启虚拟列表后在移动设备时无法进行横向滚动。

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 17 |
| System | macOS |
| Browser | Google Chrome 版本 120.0.6099.234（正式版本） (arm64) |

**Comment by zsj9705** [comment]
<img width="1273" alt="image" src="https://github.com/ant-design/ant-design/assets/142392685/46a94b07-6586-44cc-b9f6-1eb281dcd165">

拖动进行横向滚动不生效

**Comment by MadCcc** [comment]
duplicate of https://github.com/ant-design/ant-design/issues/47113
