### ISSUE TITLE
Enable Col-0

### ISSUE THREAD

**Issue by Boanerges1996** [ant-design/ant-design#47269]
### What problem does this feature solve?

I want to be able to specify the column width to 0 and make it disappear on certain screens. 
<Row>
<Col xs={0} md={12}>
</Col>
</Row>
So in this case I want to be able to set the xs to 0 and make it disappear on smaller screen

### What does the proposed API look like?

The API currently doesn't allow me to specify 0 as the column width, the minimum here is 1

**Comment by afc163** [comment]
It works: https://codesandbox.io/p/sandbox/ji-chu-zha-ge-antd-5-13-3-forked-38smzp?file=%2Fdemo.tsx%3A10%2C10

**Comment by afc163** [comment]
You can refresh it, set it to public now.
