### ISSUE TITLE
官方文档的安装方式无法生效

### ISSUE THREAD

**Issue by LugeKit** [ant-design/ant-design#47276]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

`npm install antd`

### What is expected?

successfully installed

### What is actually happening?

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ant-design/icons-svg@^4.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18.2.48 |
| System | macOS 14.0 |
| Browser | chrome |

**Comment by MadCcc** [comment]
用的什么 registry？

**Comment by zombieJ** [comment]
检查你的 npm registry，`@ant-design/icons-svg` 有的：
<img width="407" alt="截屏2024-02-01 11 20 45" src="https://github.com/ant-design/ant-design/assets/5378891/70402ede-037a-4146-8414-3372f3b7d2c0">

ref https://www.npmjs.com/package/@ant-design/icons-svg
