### ISSUE TITLE
Styling issues with fixed table headers in Google Chrome version 121  Content

### ISSUE THREAD

**Issue by limengye001** [ant-design/ant-design#47283]
### Reproduction link

[https://3x.ant.design/components/table-cn/#components-table-demo-fixed-header](https://3x.ant.design/components/table-cn/#components-table-demo-fixed-header)

### Steps to reproduce

I've noticed some styling issues with the table component when fixing headers in Google Chrome version 121. The specific manifestation is that the header does not stretch the entire row, and there are some rendering issues.

### What is expected?

![问题截图](https://github.com/ant-design/ant-design/assets/148960320/368bfb37-9416-4947-8d7c-a681267e69c9)

### What is actually happening?

![期望结果截图](https://github.com/ant-design/ant-design/assets/148960320/44282154-9f41-42be-8640-bd60e94c6ec9)

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.12.0 |
| System | macOS 14.0 (23A344) |
| Browser | Goole 121.0.6167.139（正式版本） (arm64) |

**Comment by yoyo837** [comment]
Seems like it works fine on macOS intel chips and Windows (Chrome 121)

**Comment by Return201** [comment]
I also have this issue on Google Chrome version 121
![image](https://github.com/ant-design/ant-design/assets/85044695/e940b72c-48ee-49b3-9ef4-6ea4eec5806f)

**Comment by Return201** [comment]
It seems that the scrollbar width of the header has not been set to 8px, it is still the original width

**Comment by mortalYoung** [comment]
This works for me.

https://stackblitz.com/edit/react-gktdpj?file=index.css

```css
body .scroll-div-append-to-body::-webkit-scrollbar {
  width: 8px;
  height: 8px;
}
```

This is pretty hack but works. It's aims to enable `ant-table-hide-scrollbar` for HeadTable.

[HeadTable.tsx#L22](https://github.com/react-component/table/blob/77c10752d783aa97655cc1654905dd6493942fef/src/HeadTable.tsx#L22)
