### ISSUE TITLE
Incorrect behaviuor with UTC(00:00) timezone value in DatePicker 

### ISSUE THREAD

**Issue by VladIvanov2001** [ant-design/ant-design#47299]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-4rxynq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls3j17in0006356q8u7d21sy%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls3j17in0002356q1f3hgxiq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls3j17in0003356qfrvnpbf6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls3j17in0005356qmvrzny0x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls3j17in0002356q1f3hgxiq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3j17in0001356qhbg5kvbj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls3j17in0002356q1f3hgxiq%2522%252C%2522activeTabId%2522%253A%2522cls3j17in0001356qhbg5kvbj%2522%257D%252C%2522cls3j17in0005356qmvrzny0x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3j17in0004356q2nlkhoja%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls3j17in0005356qmvrzny0x%2522%252C%2522activeTabId%2522%253A%2522cls3j17in0004356q2nlkhoja%2522%257D%252C%2522cls3j17in0003356qfrvnpbf6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls3j17in0003356qfrvnpbf6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Set UTC timesone to datepicker

### What is expected?

Expected date with UTC(00:00) timezone

### What is actually happening?

Date with system timezone on device. In my case - it's a  03:00

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by afc163** [comment]
<img width="913" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/dd63a538-0639-4363-8337-f0d2bbf1996e">

**Comment by VladIvanov2001** [comment]
It's wrong url on the screenshot. reproduction-template-forked-4rxynq - it's the part of url but in your screenshot it smth like reproduction-template-forked-kx5gs

**Comment by VladIvanov2001** [comment]
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-4rxynq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls3j17in0006356q8u7d21sy%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls3j17in0002356q1f3hgxiq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls3j17in0003356qfrvnpbf6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls3j17in0005356qmvrzny0x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls3j17in0002356q1f3hgxiq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3j17in0001356qhbg5kvbj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls3j17in0002356q1f3hgxiq%2522%252C%2522activeTabId%2522%253A%2522cls3j17in0001356qhbg5kvbj%2522%257D%252C%2522cls3j17in0005356qmvrzny0x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls3j17in0004356q2nlkhoja%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls3j17in0005356qmvrzny0x%2522%252C%2522activeTabId%2522%253A%2522cls3j17in0004356q2nlkhoja%2522%257D%252C%2522cls3j17in0003356qfrvnpbf6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls3j17in0003356qfrvnpbf6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

here's the link

**Comment by afc163** [comment]
See https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-mcs9py?file=%2Findex.js%3A14%2C48

```diff
-     <DatePicker format="YYYY-MM-DD HH:mm" value={dayjs(date).tz('UTC')} />
+     <DatePicker format="YYYY-MM-DD HH:mm" value={dayjs(date).utc()} />
```

**Comment by VladIvanov2001** [comment]
It will not work with timezones, for exmaple Africa/Abidjan, Greenwich. Timezones where UTC is equal to 0

**Comment by afc163** [comment]
> It will not work with timezones, for exmaple Africa/Abidjan, Greenwich. Timezones where UTC is equal to 0

Could you provide this reproduce? And what is expected?

**Comment by joebnb** [comment]
same issue happed，i think it should expose  global timezone configuration and component scope config to  fulfill
