### ISSUE TITLE
Virtual Table expandedRowRender ChildTable render incorrectly

### ISSUE THREAD

**Issue by Enigama** [ant-design/ant-design#47317]
### Reproduction link

[https://codepen.io/psvdfbga-the-solid/pen/bGZMGYM?editors=0010](https://codepen.io/psvdfbga-the-solid/pen/bGZMGYM?editors=0010)
![image](https://github.com/ant-design/ant-design/assets/28072229/4e6d5fe8-20d0-44a3-8218-aef23c636d8f)
![image](https://github.com/ant-design/ant-design/assets/28072229/97ac71c9-ee39-4e2e-a95b-ea8a52f9d55f)

### Steps to reproduce
 ```
   <Table
                size="small"
                virtual={true}
                rowKey={"key"}
                scroll={{ x: 1550, y: 500 }}
                expandable={{
                    columnWidth: 24,
                    expandedRowRender: () => (
                        <ChildTable {...tableProps}/>
                    ),
                }}
                columns={columns}
                dataSource={dataSource}
                pagination={false}
            />
```

### What is expected?

Child Table should render correctly inside virtual table

### What is actually happening?

Child Table tbody> tr width is not taking full space as it should be.

| Environment | Info |
| --- | --- |
| antd | 5.12.5 |
| React | 17.0.2 |
| System | Linux, Ubuntu |
| Browser | Chrome Version 121.0.6167.139 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Reproduce link is empty.

**Comment by Enigama** [comment]
@afc163 sorry, already fix the link

**Comment by afc163** [comment]
Sorry, close it accidentally~
