### ISSUE TITLE
Button Icon 上下不居中

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47313]
### Reproduction link

[https://stackblitz.com/edit/react-7xzmud?file=demo.tsx](https://stackblitz.com/edit/react-7xzmud?file=demo.tsx)

### Steps to reproduce

查看按钮

### What is expected?

上下居中

### What is actually happening?

上下不居中

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by nova1751** [comment]
You should add your own css to achieve this.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/32952

**Comment by vitalijalbu** [comment]
should be a new component :D

**Comment by MadCcc** [comment]
图标居中问题实际上很主观，换个图标可能又会觉得不居中了

**Comment by crazyair** [comment]
> 图标居中问题实际上很主观，换个图标可能又会觉得不居中了，本质上和图标本身的构造有关

不说搜索这种上下不对其的图标，这种看不出来。就用这种有边的，就能看出来
![image](https://github.com/ant-design/ant-design/assets/7971419/7eb2edeb-e6f4-4abe-9775-45fbf82b3bab)

**Comment by nova1751** [comment]
> 图标居中问题实际上很主观，换个图标可能又会觉得不居中了，本质上和图标本身的构造有关

`Button Icon`元素由于行内块元素基线对齐的缘故本身就不是严格垂直居中的，更改布局方案或许可以很好解决这个问题。

**Comment by crazyair** [comment]
这个怎么样了

**Comment by afc163** [comment]
卡在 https://github.com/ant-design/ant-design/pull/47318#discussion_r1477636093 了

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/48178
