### ISSUE TITLE
DatePicker设置了disabledTime后对于已经禁用的时间还是会出现选择成功的情况

### ISSUE THREAD

**Issue by HuaJFrame** [ant-design/ant-design#47327]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qfs2n6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls68qnyk0006356jhmqb3yzs%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls68qnyk0002356j3a3pm5p4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls68qnyk0003356jnp9ajy02%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls68qnyk0005356jq5fdhipi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls68qnyk0002356j3a3pm5p4%2522%253A%257B%2522id%2522%253A%2522cls68qnyk0002356j3a3pm5p4%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cls68qnyk0005356jq5fdhipi%2522%253A%257B%2522id%2522%253A%2522cls68qnyk0005356jq5fdhipi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls68qnyk0004356jnllnhcxn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls68qnyk0004356jnllnhcxn%2522%257D%252C%2522cls68qnyk0003356jnp9ajy02%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls68qnyk0003356jnp9ajy02%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

设置了一个最大允许选择的时间`2024-02-03 12:23:10`
超过这个时间年月日时分秒都禁用，需要根据选择的年月日来判断是否禁用时间，在`2024-02-03`时间都是可选的，当日期选择了`2024-02-03`, 小时会禁用`[13,23]`, 小时选择了`12`后，分钟会禁用掉`[24,59]`,秒类似

如果我首先选择`2024-02-03 11:25:13`(属于可选范围内)，然后在小时处选择`12`，此时`DatePicker`显示的时间是`2024-02-03 12:25:13`,超出可选范围，但是此时确定按钮是可以点击的，虽说我可以通过`onChange`来判断选择时间是否超出范围，然后调整表单的值，但是这对用户来说似乎不是那么友好
![图片](https://img2.imgtp.com/2024/02/04/HVfnFKrI.gif)

### What is expected?

时间不符合条件的的情况下无法点击确定

### What is actually happening?

时间选择已经禁用了分钟或秒后确定按钮还是可以点击

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18.1.0 |
| System | win 10 |
| Browser | Google Chrome  121.0.6167.140（正式版本） （64 位） |

**Comment by MadCcc** [comment]
先试一下 5.14.0

**Comment by zombieJ** [comment]
我看你的 Demo 新版已经是好的哈~

![Kapture 2024-02-04 at 10 43 44](https://github.com/ant-design/ant-design/assets/5378891/909b9e97-d133-4f62-9c9a-f6ce324ad54d)

**Comment by yoyo837** [comment]
5.14.0 重构了该组件，升级上来试试。

**Comment by HuaJFrame** [comment]
感谢回复，已升级
