### ISSUE TITLE
FloatButton 组件缺少拖拽功能 

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#47320]
### What problem does this feature solve?

希望 FloatButton 组件可以添加拖拽功能，FloatButton组件展开态有的文案被遮挡之后，可以进行拖拽调整位置

### What does the proposed API look like?

FloatButton 组件可以添加拖拽功能

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/46033#issuecomment-1829019892
