### ISSUE TITLE
⚠️`DatePicker` is totally not working with customzied date library

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#47339]
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-gmtkl7?file=src%2FApp.tsx,package.json](https://stackblitz.com/edit/vitejs-vite-gmtkl7?file=src%2FApp.tsx,package.json)

### Steps to reproduce

Open the link and view the console

### What is expected?

It should work

### What is actually happening?

Besides the issue of types https://github.com/ant-design/ant-design/issues/47241, the component is totally not working in `v5.14.0`. Seems like a regression in `DatePicker`'s refactor

![image](https://github.com/ant-design/ant-design/assets/45784210/826dbefa-e6b3-4289-857f-c8d3b2fe7b37)

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 121 |

**Comment by Roxannej** [comment]
![Uploading 截屏2024-02-05 下午3.56.14.png…]()

**Comment by ABruel** [comment]
From what I can see in the lock file, antd depends on a newer version of rc-picker..


I believe you can either update your rc-picker version or change the import to use the internal antd version. I did both and it seems to work fine. 

https://stackblitz.com/edit/vitejs-vite-emkzc7?file=src%2FApp.tsx,package.json,package-lock.json

**Comment by nikzanda** [comment]
I have the same problem, `DatePicker` not working using `date-fns` library.
Using the same code from the [antd documentation](https://ant.design/docs/react/use-custom-date-library#datepickertsx-1), I have the following error when focusing component:

![Screenshot 2024-02-06 at 09 56 42](https://github.com/ant-design/ant-design/assets/71180446/3b5fb1ca-05f9-48dd-b622-3a151c1cabc6)

**Comment by lihue** [comment]
@nikzanda there is already a pull request that solves this problem: https://github.com/react-component/picker/pull/289

**Comment by nikzanda** [comment]
> @nikzanda there is already a pull request that solves this problem: [react-component/picker#289](https://github.com/react-component/picker/pull/289)

UPDATES: I discovered that DatePicker with the date-fns library breaks when setting a language other than the default one, such as Italian or French. I opened a new issue, you can find it [here](https://github.com/ant-design/ant-design/issues/47600).

**Comment by xsjcTony** [comment]
@zombieJ Thanks for resolving the type issue. But also,

> But the thing is if you are using `pnpm`, you have to explicitly install it rather than import from phantom dependency.
> 
> I think the better way is that `antd` should re-export that from `rc-picker`.

Regarding this, wouldn't that be better that it's re-exported from `antd` instead?
