### ISSUE TITLE
Cascader basic demo is not compilant

### ISSUE THREAD

**Issue by CarlaPaiva** [ant-design/ant-design#47336]
### Reproduction link

https://codesandbox.io/p/sandbox/elegant-dew-ptmv36?file=%2Fdemo.tsx

### Steps to reproduce

1 - Copy basic usage from Cascader to an tsx component

2 - Observe the error on the onChange event
```
Type '(value: string[]) => void' is not assignable to type 'OnSingleChange<Option> | OnMultipleChange<Option> | undefined'.
  Type '(value: string[]) => void' is not assignable to type 'OnSingleChange<Option>'.
    Types of parameters 'value' and 'value' are incompatible.
      Type 'SingleValueType' is not assignable to type 'string[]'.
        Type 'string | number' is not assignable to type 'string'.
          Type 'number' is not assignable to type 'string'.typescript(2322)
Cascader.d.ts(75, 5): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & (PropsWithChildren<CascaderProps<Option>> & RefAttributes<CascaderRef>)'
```

### What is expected?

Is expected to this be a compilant code.

### What is actually happening?

Because this is a typing error, is not possible to generate build of the app.

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | react 18.2 |
| System | Windows 10 Home Single Language 22H2 |
| Browser | Firefox Developer Edition 123.0b6 (64-bit) |

**Comment by CarlaPaiva** [comment]
I would like to have it assigned to me and work on it, if possible.

**Comment by MadCcc** [comment]
Couldn't open your codesandbox

**Comment by CarlaPaiva** [comment]
@MadCcc Sorry it was private, made it public.

**Comment by ABruel** [comment]
Working fine here, onchange logs the selected elements correctly.

![image](https://github.com/ant-design/ant-design/assets/30672118/25307284-902f-48ab-bc4f-619d99cc8152)

**Comment by ABruel** [comment]
It's possible you have a more pedantic configuration on your local typescript config, in which case you'll want to change either the `Option.value` type to be just `string` or change the `onChange` method to receive `(string | number)[]`.

**Comment by CarlaPaiva** [comment]
Strange, on my side I have this warning already on Codesandbox:
![image](https://github.com/ant-design/ant-design/assets/51243239/b1424d1c-b1c7-426e-8253-92a508aa0628)

I switched the onChange method to receive (string | number)[] and it worked. Would it be possible to update the example on the docs?
Am I allowed to do it?
Even though the contribution guide is very clear regarding contributing to feat and bugs, it doesn't mention a lot of updating docs...

**Comment by ABruel** [comment]
Probably, yeah. I'm just starting on OSS, but from the PRs I see the template has a checkbox for docs update.
![image](https://github.com/ant-design/ant-design/assets/30672118/f54b8abc-13d3-4c44-a274-3e46052b8a55)

From what I can tell, this particular code is at `components/cascader/demo/basic.tsx`.

**Comment by CarlaPaiva** [comment]
Hey @MadCcc , could you please add the "Documentation" label? I'll be working on it ASAP.
