### ISSUE TITLE
文档里代码片段最后多了一行

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#47347]
<img width="448" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8b856544-4af0-404b-9c80-b83a66bad184">

https://ant.design/docs/react/introduce-cn

**Comment by nova1751** [comment]
这应该是`dumi`最新版本的问题，可以考虑降`dumi`版本解决。

**Comment by afc163** [comment]
疑似这个改动：https://github.com/umijs/dumi/pull/2014

**Comment by MadCcc** [comment]
这个代码片段里多了一行空行，应该不是样式的原因

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/46805 里引入的
https://preview-46805-ant-design.surge.sh/docs/react/introduce-cn
