### ISSUE TITLE
Input number Formatter Function

### ISSUE THREAD

**Issue by abdulrahman-centroid** [ant-design/ant-design#47351]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-dfs9qc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls8mjkvd0006356k1fiwdc0f%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls8mjkvd0002356kcw0w81d2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls8mjkvd0003356ksxfrbn3l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls8mjkvd0005356kk1jy7ymo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls8mjkvd0002356kcw0w81d2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls8mjkvc0001356knd6cux3q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522cls8mjkvd0002356kcw0w81d2%2522%252C%2522activeTabId%2522%253A%2522cls8mjkvc0001356knd6cux3q%2522%257D%252C%2522cls8mjkvd0005356kk1jy7ymo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls8mjkvd0004356k00evd007%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls8mjkvd0005356kk1jy7ymo%2522%252C%2522activeTabId%2522%253A%2522cls8mjkvd0004356k00evd007%2522%257D%252C%2522cls8mjkvd0003356ksxfrbn3l%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls8mjkvd0003356ksxfrbn3l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

I'm using the formatter in the InputNumber component to fix digits to two, but sometimes the formatter doesn't trigger, and the number fixed to three digits.

### What is expected?

the formatter in the InputNumber component should called all times

### What is actually happening?

the formatter doesn't trigger all times.

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by nova1751** [comment]
Please set your CodeSandBox link permission to public.

**Comment by abdulrahman-centroid** [comment]
Hi @nova1751 CodeSandBox link permission is public now. 
Thanks.

**Comment by nova1751** [comment]
Your example works fine in my laptop.I haven't encounter the case that the number is fixed to 3 digits.

**Comment by abdulrahman-centroid** [comment]
https://github.com/ant-design/ant-design/assets/135217806/4f89f7aa-61e3-423e-9ad1-ee4623a36ac3
Hi @nova1751 
This is what happened, there was one time when became 3 digits, formatter function wasn't triggered, at next time it will be triggered then the digits is 2.
Thank you.

**Comment by zombieJ** [comment]
`formatter` should always work with `parse`. Or it will not know user typing is finished with correct value.
