### ISSUE TITLE
table组件开启虚拟滚动后，在移动端(ipad,手机)无法正常侧滑

### ISSUE THREAD

**Issue by knchoi97** [ant-design/ant-design#47350]
### Reproduction link

[https://ant-design.gitee.io/components/table-cn#components-table-demo-virtual-list](https://ant-design.gitee.io/components/table-cn#components-table-demo-virtual-list)

### Steps to reproduce

移动端直接访问官网的demo

### What is expected?

 移动端能够正常侧滑

### What is actually happening?

table组件开启虚拟滚动后，在移动端(ipad,手机)无法正常侧滑

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18.2.0 |
| System | Ipad OS 17.2/Hyper OS 1.0.2.0 |
| Browser | Chrome/quark |

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/47113
