### ISSUE TITLE
Select: On hover of options shows tooltip

### ISSUE THREAD

**Issue by lohi-Kosh** [ant-design/ant-design#47359]
### What problem does this feature solve?

The Select option shows tooltip unnecessarily on hover. Needed a work around to not show the tooltip.

### What does the proposed API look like?

```
<Select 
   showTooltipOnHover={true/ false}
   ...
/>
```

**Comment by ABruel** [comment]
Do you mean this?

![image](https://github.com/ant-design/ant-design/assets/30672118/0d570366-0608-4421-b8e9-095de075fce5)

If so, this isn't a tooltip, it's an aria title. it's an accessibility feature used by screen readers. Suppose they could use the modern aria-title attribute instead, but that would likely break in some older software.

You should be able to remove it by reexporting the component and using a custom option renderer, but remember to replace it with the `aria-title`, removing accessibility is a bad thing.
