### ISSUE TITLE
getFieldDecorator on change key and value

### ISSUE THREAD

**Issue by iiitmahesh** [ant-design/ant-design#4735]
This is not working

getFieldDecorator on change key and value

```
handleSelectChange(e){
this.props.form.setFieldsValue({
            [e.target.name]: e.target.value,
        });
}

```
`  <FormItem {...formItemLayout} label="name)">
                            {getFieldDecorator('freight', {rules: [{ required: true, message: 'Please input your name!' }], onChange:this.handleSelectChange, })(
                            <Input  /> )}
                        </FormItem>`

**Comment by afc163** [comment]
What is the value of `e.target.name`.

**Comment by iiitmahesh** [comment]
Actually I want to set state key and value on input change  (Onchange).

`<FormItem label="name)">
 {getFieldDecorator('name', {rules: [{ required: true, message: 'Please input your name!' }], onChange:this.handleChange, })( <Input /> )} 
</FormItem>`

````
handleChange(key,value)
{
this.props.form.setFieldsValue({
            [key]: value,
        });
}`
```

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by iiitmahesh** [comment]
```
`const { Row, Col, Input, Form, Select, InputNumber, Radio, }
from 'antd';

const FormItem = Form.Item;
class Dummy extends Component {
    handleChange(key, value) {
        console(key+":"+value)
    }
    `
  render(){
              const { getFieldDecorator } = this.props.form
 	return (
		 	<Form>
		    <FormItem label="name)">
		        {getFieldDecorator('name1', {rules: [{ required: true, message: 'Please input your name1!' }], onChange:this.handleChange, }) (
		        <Input />)}
		    </FormItem>
        <FormItem label="name)">
		        {getFieldDecorator('name2', {rules: [{ required: true, message: 'Please input your name2!' }], onChange:this.handleChange, }) (
		        <Input />)}
		    </FormItem>
		</Form>

 	)
      
  }
}

const renderForm = Form.create()(Dummy);

ReactDOM.render(<renderForm />, document.getElementById('container'));
`
```

**Comment by benjycui** [comment]
Same as: https://github.com/ant-design/ant-design/issues/4777#issuecomment-278207421

**Comment by sebekgr** [comment]
Hi. How we can get event from inputs?
So I got <InputNumber min={1000} max={5000}> and ofcourse I can't type in more/less than is in min/max. However if I type by manually it's possible :) So I'd like to know how can I get min/max values from InputNumber and send to my changeHandler method and prevent typing by manually

if(min > e.min && e.max < max) return false;
