### ISSUE TITLE
Calendar 日历组件无法修改年或者月，选中年/月下拉框之后，再点击日期，年/月又回到的当前的时间

### ISSUE THREAD

**Issue by guojunhao118** [ant-design/ant-design#47354]
### Reproduction link

[https://ant.design/components/calendar-cn](https://ant.design/components/calendar-cn)

### Steps to reproduce

官网的例子就是这样，随便哪个组件都是如此

### What is expected?

修复此 bug

### What is actually happening?

修复此 bug

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | react |
| System | macos 14.0 |
| Browser | chrome 121.0.6167.139 |

---
没有人发现这个问题么？还是我使用的方式不对

**Comment by afc163** [comment]
bug
