### ISSUE TITLE
Autocomplete Input Styling

### ISSUE THREAD

**Issue by garyfoo** [ant-design/ant-design#4736]
Hello, I have been struggling to make my autocomplete look like the autocomplete component below.

Could anyone point me in the right direction on how to customize my autocomplete to look like the autocomplete in the picture?

![hufcsxwnosvlskl](https://cloud.githubusercontent.com/assets/5109700/22401592/d9b527c0-e614-11e6-85cf-84dd3db5e18f.png)

**Comment by Orbyt** [comment]
I'd like an answer to this as well. The `AutoComplete` component is based on `rc-select`, however both seem difficult to apply custom styles to without breaking the functionality. Is there a way to strip all provided styles of this single component?

**Comment by benjycui** [comment]
Try `InputGroup[compat]` https://ant.design/components/input/#components-input-demo-group

**Comment by afc163** [comment]
We should add a demo for this. @RaoHai

**Comment by RaoHai** [comment]
Demo should be simpler without considering alignment of dropdown and input field.
