### ISSUE TITLE
Table 分组表头固定后横向滚动时阴影异常

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#47374]
### Reproduction link

[https://stackblitz.com/edit/react-l36egz-xmeovb?file=demo.tsx](https://stackblitz.com/edit/react-l36egz-xmeovb?file=demo.tsx)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/6482819/73f1a765-96af-415c-9a31-84d05d32859a)

### What is expected?

阴影正常

### What is actually happening?

阴影异常

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
cc @kiner-tang

**Comment by kiner-tang** [comment]
> cc @kiner-tang

👌🏻
