### ISSUE TITLE
能否开放 getLocaleCode 接口?

### ISSUE THREAD

**Issue by xnightsky** [ant-design/ant-design#4738]
`import { getLocaleCode } from '../_util/getLocale';`
如上接口，因为有时候要用rc-xx控件和 antd class 编写控件
`_util` 感觉还是一个会后续变动的文件夹

例: 使用 "rc-calendar/lib/RangeCalendar" +   antd class 在 弹出 Menu 上实现非浮动时间查询（Menu 弹出 Calendar Container 会导致 Menu 失去焦点，然后自动关闭菜单）

**Comment by benjycui** [comment]
不好暴露，自定义组件没必要跟随 `LocaleProvider`，太累。

**Comment by xnightsky** [comment]
👌
