### ISSUE TITLE
Table with expandable whitespace pre-wrap is wrapped

### ISSUE THREAD

**Issue by blue-int** [ant-design/ant-design#47386]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-cx3882)

### Steps to reproduce

click on row

### What is expected?

The column width should be fixed.

### What is actually happening?

The column width is changed.

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | macOS 14.2.1(23C71) |
| Browser | Naver Whale 3.24.223.24 |

**Comment by afc163** [comment]
<img width="739" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/ec572b0e-954f-4825-a119-d7f122f94fd1">

**Comment by blue-int** [comment]
@afc163 I changed the permissions. Sorry for the mistake.

**Comment by afc163** [comment]
See https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-cx3882?file=%2Findex.js%3A51%2C42

**Comment by blue-int** [comment]
@afc163 
I forgot to mention that the issue happens when window width is around 1300px.
Could you please check once more?
Thanks

**Comment by blue-int** [comment]
![Uploading expandableTable.gif…]()

**Comment by blue-int** [comment]
![expandableTable](https://github.com/ant-design/ant-design/assets/42234614/2e6f07b7-037a-49a2-8eb8-40ae01bcbd02)

**Comment by blue-int** [comment]
I've opened a new issue
https://github.com/ant-design/ant-design/issues/47393
