### ISSUE TITLE
The rows dynamically added to the `Table` are not expanded by default with the `defaultExpandAllRows` property set to true.

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#47380]
### Reproduction link

[https://stackblitz.com/edit/stackblitz-starters-wtabhe?file=src%2FApp.tsx](https://stackblitz.com/edit/stackblitz-starters-wtabhe?file=src%2FApp.tsx)

### Steps to reproduce

In a component, add a `Table` with the `expandable={{ defaultExpandAllRows: true, expandedRowRender: /* … */ }}` property and add rows to the table dynamically, for example by modifying the state of the dataSource passed to Table.

### What is expected?

The added rows should already be expanded.

### What is actually happening?

The added rows are not expanded, but you have to press the default expandable button to expand them.

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | MacOS 14.2.1 |
| Browser | Chrome 109 |

---
Probably defaultExpandAllRows is intended for rows already present during the rendering of the Table component, it might be useful to also expand any rows added later if to the expandable property of Table you also passed the “showExpandColumn” property as false. Consequently, if showExpandColumn is false, the new rows added cannot be expanded.

**Comment by zombieJ** [comment]
default is one time operation which only sync when component mounted.

**Comment by nikzanda** [comment]
@zombieJ Is there an alternative solution?

**Comment by qiutian00** [comment]
> @zombieJ Is there an alternative solution?

@nikzanda use `expandedRowKeys` or defaultExpandAllRows  like  `{dataSource.length > 0 ?  <Table defaultExpandAllRows ... /> : null}`
