### ISSUE TITLE
Select clears the search on multiple items selected.

### ISSUE THREAD

**Issue by therbta** [ant-design/ant-design#47398]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/v8ll6h)

### Steps to reproduce

-

### What is expected?

The search words should remain in the input so that users can continue their selection.

### What is actually happening?

When items are searched for on the select component <Select />,

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | Latest |
| System | MacOS Ventura |
| Browser | Chrome Latest |

**Comment by afc163** [comment]
<img width="680" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8c779def-f913-4d1d-8811-0169a163405c">
