### ISSUE TITLE
RangePicker iOS onChange not triggering

### ISSUE THREAD

**Issue by dmitryhiccup** [ant-design/ant-design#4740]
On iOS( checked 8.0, 9.2, 10.0) when choosing date range onChange is not triggered.

**Comment by afc163** [comment]
`antd` do not privide mobile device support officially, you can try to include [react-tap-event-plugin](http://www.material-ui.com/#/get-started/installation) or use [antd-mobile](http://github.com/ant-design/ant-design-mobile/).

**Comment by neekey** [comment]
hmm.. seems like antd-mobile does not support range picker, @afc163 is it possible just make the range picker adjust its size and layout a little to responsive to mobile? Currently:

![image](https://user-images.githubusercontent.com/499870/28102587-91ddf2ee-6713-11e7-8451-35a667b56854.png)
