### ISSUE TITLE
next14 暗黑模式 预设算法 Result页面背景色与字体不协调

### ISSUE THREAD

**Issue by DongFang-Jun** [ant-design/ant-design#47405]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/DongFang-Jun/demo/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clscnx63b00063b6jfnre75m1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clscnx63b00023b6j6nxzvq62%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clscnx63b00043b6jzy621zhu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clscnx63b00053b6jp1xjrwwi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clscnx63b00023b6j6nxzvq62%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clscnx63b00013b6j717uzsb5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clscnx63b00023b6j6nxzvq62%2522%252C%2522activeTabId%2522%253A%2522clscnx63b00013b6j717uzsb5%2522%257D%252C%2522clscnx63b00053b6jp1xjrwwi%2522%253A%257B%2522id%2522%253A%2522clscnx63b00053b6jp1xjrwwi%2522%252C%2522activeTabId%2522%253A%2522clsco1xbf00p03b6j2en4dt4f%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clsco1xbf00p03b6j2en4dt4f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clscnx63b00043b6jzy621zhu%2522%253A%257B%2522id%2522%253A%2522clscnx63b00043b6jzy621zhu%2522%252C%2522activeTabId%2522%253A%2522clscnx7k1005p3b6jhp0b9q83%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clscnx63b00033b6j0sbmii6s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clscnx732000sdljaf8mo7cyw%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clscnx7k1005p3b6jhp0b9q83%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clscnxtb6007q3b6jt8tm8cr5%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

现在暗黑模式字体是白色的，背景也是白色；希望背景协调成暗色

### What is expected?

现在暗黑模式字体是白色的，背景也是白色；希望背景协调成暗色

### What is actually happening?

现在暗黑模式字体是白色的，背景也是白色

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | 121.0.6167.139 |

**Comment by MadCcc** [comment]
Result 组件不提供背景，你需要修改 html 或者 body 在暗黑模式下的背景颜色
