### ISSUE TITLE
the parameter of `onChange` is wrong when I click cancel button in `DatePicker.RangePicker`

### ISSUE THREAD

**Issue by tnyo43** [ant-design/ant-design#47404]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-datepicker-onclick-szgj28?file=%2Fsrc%2FApp.js%3A9%2C1)

### Steps to reproduce

1. open the minimal reproduction
1. open dev tool
1. click the cancel button (icon with "x")
1. see the console

### What is expected?

The first parameter of `onChange` and `onCalendarChange` should be same.
I'm not sure how it is actually, but I think `[null, null]` makes scence.

### What is actually happening?

The first parameter of `onChange` and `onCalendarChange` are different.
`onChange` ... `null`
`onCalendarChange` ... `[null, null]`

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | macOS 14.0 |
| Browser | Google Chrome Version 121.0.6167.139 |

---
The document should be updated as well https://ant.design/components/date-picker#rangepicker.

**Comment by hunxjunedo** [comment]
the sandbox link is broken.

**Comment by tnyo43** [comment]
@hunxjunedo Thanks for mentioning. I fixed it.

**Comment by tnyo43** [comment]
I've realized that this issues is come from rc-picker. I've created [an issue](https://github.com/react-component/picker/issues/757) and [a PR](https://github.com/react-component/picker/pull/758) to that package.
After it is merged, we can update the dependency of this package and solve this issue as well.

**Comment by zombieJ** [comment]
Sorry for delay. I reply for this. Pls check: https://github.com/react-component/picker/issues/757#issuecomment-1965675890
