### ISSUE TITLE
DatePicker placement="bottomRight" / "topLeft" / "topRight"

### ISSUE THREAD

**Issue by felixfirefighter** [ant-design/ant-design#47408]
### Reproduction link

[https://ant.design/components/date-picker#components-date-picker-demo-placement](https://ant.design/components/date-picker#components-date-picker-demo-placement)

### Steps to reproduce

1. Select 'topLeft'
2. Open the DatePicker (first one, not the RangePicker)
3. DatePicker popup will always align bottomLeft

### What is expected?

The popup should open at topLeft, topRight, or bottomRight depending on placement

### What is actually happening?

The popup always align bottomLeft

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18 |
| System | Windows 10 |
| Browser | Chrome 121.0.6167.86 |

---
It works on Antd version 4, which you can try it here on the doc
https://4x.ant.design/components/date-picker/#components-date-picker-demo-placement

**Comment by afc163** [comment]
4.x had a bug that DatePicker won't adjust position to fit current viewport.

The DatePicker behavior of 5.x is correct now.

![date](https://github.com/ant-design/ant-design/assets/507615/c5db9877-db48-45ba-95b6-da1de1dc5c0e)

**Comment by felixfirefighter** [comment]
Sorry if I'm mistaken, I thought if we set placement="bottomRight", the datepicker should align bottomRight. RangePicker is aligned the right way, but DatePicker is not aligned bottomRight (it will still align bottomLeft).

Can you give bottomRight a try for both DatePicker and RangePicker? Hope it's not my browser issue. Thanks!

**Comment by felixfirefighter** [comment]
@afc163 Hi just following up with the status for this ticket. "bottomRight" still does not align the DatePicker to the right side

**Comment by jaydeep-pipaliya** [comment]
yes but now what happens is if we set the date picker to 'topLeft' it doesn't open that way, it opens on placement 'bottomLeft' 

it is working only with the viewport

![Screenshot from 2024-03-22 15-17-01](https://github.com/ant-design/ant-design/assets/71074587/73397596-cae9-43a4-8969-492de8ca090d)

here in a Screenshot, i have selected a topRight still its open as bottomLeft

**Comment by helmif** [comment]
i've this issue also
