### ISSUE TITLE
The onPickerValueChange prop on the DatePicker component does not trigger a change when selecting the current day

### ISSUE THREAD

**Issue by Kenneth-Brisco** [ant-design/ant-design#47417]
### Reproduction link
[Sandbox Link](https://codesandbox.io/p/sandbox/antd-datepicker-f3k7q2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsi5zdw200063b6okjoi5h2x%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsi5zdw200023b6ottmswo4j%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsi5zdw200033b6of9bitpi6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsi5zdw200053b6ot8xuzwc4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsi5zdw200023b6ottmswo4j%2522%253A%257B%2522id%2522%253A%2522clsi5zdw200023b6ottmswo4j%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsi5zdw200053b6ot8xuzwc4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsi5zdw200043b6ocwpnpzy4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsi5zdw200053b6ot8xuzwc4%2522%252C%2522activeTabId%2522%253A%2522clsi5zdw200043b6ocwpnpzy4%2522%257D%252C%2522clsi5zdw200033b6of9bitpi6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsi5zdw200033b6of9bitpi6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

- Use the DatePicker component with the onPickerValueChange prop
- select the current day
- a change is not triggered

### What is expected?

The prop should trigger a change so that the current day can be formatted or the prop should be removed from the component because it is not a recognized prop in the documentation.

### What is actually happening?

A trigger does not happen

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2 |
| System | Mac OS |
| Browser | Chrome |

**Comment by hunxjunedo** [comment]
is that even a recognized prop ? I couldn't find it in the docs. Consider sharing a link.

**Comment by Kenneth-Brisco** [comment]
@hunxjunedo : [Link](https://codesandbox.io/p/sandbox/antd-datepicker-f3k7q2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsi5zdw200063b6okjoi5h2x%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsi5zdw200023b6ottmswo4j%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsi5zdw200033b6of9bitpi6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsi5zdw200053b6ot8xuzwc4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsi5zdw200023b6ottmswo4j%2522%253A%257B%2522id%2522%253A%2522clsi5zdw200023b6ottmswo4j%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsi5zdw200053b6ot8xuzwc4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsi5zdw200043b6ocwpnpzy4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsi5zdw200053b6ot8xuzwc4%2522%252C%2522activeTabId%2522%253A%2522clsi5zdw200043b6ocwpnpzy4%2522%257D%252C%2522clsi5zdw200033b6of9bitpi6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsi5zdw200033b6of9bitpi6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)


It's not a recognized prop in the docs, it does exist on the picker props that are applied to the DatePicker component. 
Something I noticed while upgrading versions and swapping out props.

**Comment by zombieJ** [comment]
[Can I use internal API which is not documented on the site?](https://ant.design/docs/react/faq/#can-i-use-internal-api-which-is-not-documented-on-the-site)
