### ISSUE TITLE
ts+webpack 环境下，整个包引入没有问题，按需加载得到的全部是undefined

### ISSUE THREAD

**Issue by xiaocaibird** [ant-design/ant-design#4742]
例如：
import Menu from 'antd/lib/menu';
import { Menu as m } from 'antd';

console.log(Menu,m);

前者输出undefined，后者能得到正确引用

==========================================

项目地址：https://github.com/xiaocaibird/rzyjy-sysmanage

下载后请切到   “antd按需加载异常问题”  这一个  Commits

然后
npm i -g typescript  
npm i 
npm start

在chrome里打开控制台的输出窗口，就能看到

**Comment by yesmeck** [comment]
1. `import * as Menu from 'antd/lib/menu';`
2. babel-import-plugin 没生效是因为你在 tsconfig.json  里指定了 `"module": "commonjs"`，这个要去掉；

**Comment by xiaocaibird** [comment]
我试过把 "module": "commonjs"去掉，或改成es6，但会编译错误。
而且我这里似乎也不是babel-import-plugin 插件的问题，
直接用  import Menu from 'antd/lib/menu';  得到的Menu 仍然为undefined

**Comment by yesmeck** [comment]
见第一条。

**Comment by xiaocaibird** [comment]
这样是否意味着我需要为每个导出重写d.ts文件？
有其它解决方法吗？

**Comment by yesmeck** [comment]
建议你去 StackOverflow 或者 SegmentFault 上去问。

**Comment by xiaocaibird** [comment]
好的，非常感谢

**Comment by Penggggg** [comment]
#### Environment(required)

- antd version: "^2.8.0"
- OS and its version: mac pro 10.12
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
1.  import Button from 'antd/lib/button'; 
该写法提示: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
2.  import * as Button from 'anyd/lib/button';
该写法提示：JSX element type 'Button' does not have any construct or call signatures
3.  ts+webpack+babel-pugin-import
无效（大小无变）


#### What do you expected?
能按需加载


#### What happen?
按需加载失效


#### 配置文件
####tsconfig.json:
{
    "compilerOptions": {
        "target": "es5",
        "noImplicitAny": true,
        "sourceMap": false,
        "jsx": "preserve",
        "allowSyntheticDefaultImports": true,
        "skipLibCheck": true,
        "lib": [
            "dom",
            "scripthost",
            "es6"
        ]
    },
    "exclude": [
        "node_modules",
        "web"
    ]
}
####.babelrc
{
    "presets": ["react"],
    "plugins": [
        ["import", {
            "libraryName": "antd",
            "style": "css"
        }]
    ]
}

**Comment by benjycui** [comment]
Try https://github.com/ant-design/ant-design#typescript @Penggggg

**Comment by gwuhaolin** [comment]
[ui-component-loader](https://github.com/gwuhaolin/ui-component-loader) 可以非常方便的做到。

它是一个 babel-plugin-import 的代替品，一个 Webpack Loader，优势有：
- 更简洁，性能更好；
- 能用于非 Babel 的项目，只要你的项目使用 Webpack 构建即可；
