### ISSUE TITLE
Affix在target模式下附着的问题

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [ant-design/ant-design#47425]
### Reproduction link

[http://localhost:8001/components/affix-cn#affix-demo-target](http://localhost:8001/components/affix-cn#affix-demo-target)
比如把边框调大一点，看着就可能不是很协调了
![image](https://github.com/ant-design/ant-design/assets/97073795/e473eaa5-3601-40c2-92a5-358c3aa1c2d5)

### Steps to reproduce

直接滚动，即可发现

### What is expected?

图钉按钮在滚动时依附于上边框

### What is actually happening?

图钉按钮直接附着于容器顶部

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.x.x |
| System | win11 |
| Browser | chrome 120.0.6099.218 |

**Comment by ANUGLYPLUGIN** [comment]
如果大佬们觉得这个有必要考虑，可不可以assign给我

**Comment by afc163** [comment]
这个要看具体业务场景的需求吧，和容器贴边是更简单合理的，默认考虑 border 不太合适，outline 要不要解决，box-shadow 要不要解决，border inset 如何处理。

**Comment by ANUGLYPLUGIN** [comment]
> 这个要看具体业务场景的需求吧，和容器贴边是更简单合理的，默认考虑 border 不太合适，outline 要不要解决，box-shadow 要不要解决，border inset 如何处理？
> 
> 我倾向于不处理。

有道理。
还有个震颤的小问题，可能是精度引起的
