### ISSUE TITLE
Chart component

### ISSUE THREAD

**Issue by ErkinRejepow** [ant-design/ant-design#47420]
### What problem does this feature solve?

<Chart /> component can solve problems like developing statistics pages, 

### What does the proposed API look like?

<Chart type={"pie"|"graph"|*etc*} data={{data1:[],data2:[],...,data#:[]}}  color={(*forEachdata*)} *etc* />
you can enrich properties, i just wanted to give you an example

**Comment by ErkinRejepow** [comment]
I know that ant design pro supports this type of components but  i just wanted to some simple ones to be in list of normal components please

**Comment by MadCcc** [comment]
Ant Design will not provide charts components. Maybe you need [antv](https://antv.antgroup.com/en/) or [ant design charts](https://ant-design-charts.antgroup.com/en/)
