### ISSUE TITLE
Passing null as moreIcon prop of Tabs component has no effect

### ISSUE THREAD

**Issue by alex-golubtsov** [ant-design/ant-design#47433]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/hungry-dijkstra-4k28ws?file=%2Fdemo.tsx)

### Steps to reproduce

- Open the link
- Shrink your screen (< 500px)

### What is expected?

I expect `moreIcon` to be hidden and the dropdown not triggered on hover

### What is actually happening?

Ellipsis are still shown and the dropdown is triggered

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.x |
| System | macOs |
| Browser | Chrome |

**Comment by dxsun97** [comment]
the source code is:
```tsx
moreIcon={moreIcon ?? tabs?.moreIcon ?? <EllipsisOutlined />}
```
so you can pass `false`
