### ISSUE TITLE
typescript .d.ts use of React incorrect.

### ISSUE THREAD

**Issue by delaneyj** [ant-design/ant-design#4743]
#### Environment(required)

- antd version: 2.6.4
- OS and its version: Windows 10 Pro
- Browser and its version: webpack

#### What did you do? Please provide steps to re-produce your problem.
1. `yarn add antd`
2. import * as Button from 'antd/lib/button'; in an existing .tsx file
3. `npm start`

#### What do you expected?
To compile without errors.

#### What happen?
`ERROR in [at-loader] node_modules\antd\lib\button\button.d.ts:2:8
    Module '"C:/testProject/node_modules/@types/react/index"' has no default export.`

#### What to do
It appears that all *.d.ts files are incorrect.  Locally changing to `import * as React from 'react'` instead of `import React from 'react'` makes the errors go away in Typescript.  Would make a pull request but instructions for building project in English are unclear.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design#typescript

**Comment by delaneyj** [comment]
Sorry about that.
