### ISSUE TITLE
InputNumber Component parser props not accept return undefined

### ISSUE THREAD

**Issue by psi9730** [ant-design/ant-design#47436]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-8krrpp?file=%2Findex.js%3A15%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsjzp9o700063b6nltkcnmad%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsjzp9o700023b6nmfhb8nhl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsjzp9o700033b6ntpvyddmm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsjzp9o700053b6n74hmh1zv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsjzp9o700023b6nmfhb8nhl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsjzp9o700013b6n61iffma9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clsjzp9o700023b6nmfhb8nhl%2522%252C%2522activeTabId%2522%253A%2522clsjzp9o700013b6n61iffma9%2522%257D%252C%2522clsjzp9o700053b6n74hmh1zv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsjzp9o700043b6netfb20vg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsjzp9o700053b6n74hmh1zv%2522%252C%2522activeTabId%2522%253A%2522clsjzp9o700043b6netfb20vg%2522%257D%252C%2522clsjzp9o700033b6ntpvyddmm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsjzp9o700033b6ntpvyddmm%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. enter number(ex:1234) in InputNumber
2. delete number all
3. click out of InputNumber Component

### What is expected?

InputNumber value should be empty and value is null

### What is actually happening?

InputNumber value is 1 which is last input value

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | macOs |
| Browser | Chrome |

---
I suggest InputNumber parser could return undefined in typescript or if parser return NaN set InputNumber value as undefined.
Now it can be fixed when return undefined if value is empty(''), but has typescript error because parser should return number type when  min or max is number or use InputNumber<number> component.

**Comment by nova1751** [comment]
Please set your CodeSandbox permission to public.

**Comment by roberttaylorlongshot** [comment]
I'm having the same issue - I think the problem is the type of parser is

```
parser?: (displayValue: string | undefined) => T;
```

Ideally I'd like to return null or undefined when the input is cleared so maybe this type would be better?

```
parser?: (displayValue: string | undefined) => T | undefined;
```

**Comment by magnayn** [comment]
This seems to have been ignored, and the signature still seems to be the same today. I worked around it by returning undefined with a @ts-ignore - it sets my form value to NULL not Undefined, but that's ok.
