### ISSUE TITLE
form表单因性能问题导致内容覆盖

### ISSUE THREAD

**Issue by xfourx** [ant-design/ant-design#47448]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-cmp8zg?file=%2FExpressInput.tsx%3A4%2C9)

### Steps to reproduce

点击页面按钮打开Drawer，请求获取表单内容后form.setFieldsValue填充内容。Form.List添加80多组内容，每组内容有约十个Select和Input的Form.Item普通内容项，以及一个用Form.Item包裹的，用于展示代码语句的第三方库@codemirror/view和@prometheus-io/codemirror-promql输入框。
关闭Drawer后点击另一个按钮再次打开Drawer，请求获取到新表单内容5组，form.setFieldsValue填充新内容。

### What is expected?

两次打开Drawer，其中的表单都能正常展示与交互

### What is actually happening?

第一次打开Drawer内容显示正常，第二次打开的Drawer的表单内容初始显示正常，然后交互页面任意内容或者等待几秒后页面其他逻辑触发更新（例如如滚轮滚动该表单），就会在当前表单下突然增加多个额外组别，组别数量不定且组内部分表单内容缺失。
控制台打印，发现Form.List数组中间多了多个undefined项，数组末尾多了有内容的几个项。

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.19.0 |
| System | 14.3.1 (23D60) |
| Browser | 121.0.6167.160 |

---
排查问题已排除form使用不当，最终定位问题在该第三方输入框，假如去除该输入框后表单逻辑一切正常。
因为第三方输入框在代码项目的Form表单中少量使用并无问题，猜测是本次表单加载数量庞大，我即使在关闭Drawer时触发了resetFields方法，也没有完全清理form内容，不清楚是否为性能问题。
因为antd的form没有暴露销毁方法，目前只能通过
{
    visible && <MyDrawer visible={true}>...</MyDrawer>
}
销毁整个Drawer达到form的销毁，这样使用起码能保证所有表单内容显示和使用正常

**Comment by afc163** [comment]
<img width="1093" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/bc06f888-e8ac-4ac8-997a-ccb2e9724385">
