### ISSUE TITLE
希望Avatar添加预览preview功能

### ISSUE THREAD

**Issue by asd116725** [ant-design/ant-design#47466]
### What problem does this feature solve?

有的业务场景头像很小，需要点击预览看清楚图片,希望头像可以添加Image组件一样的预览功能

### What does the proposed API look like?

preview?: boolean | ImagePreviewType;

export interface ImagePreviewType extends Omit<IDialogPropTypes, 'mask' | 'visible' | 'closable' | 'prefixCls' | 'onClose' | 'afterClose' | 'wrapClassName'> {
    src?: string;
    visible?: boolean;
    minScale?: number;
    maxScale?: number;
    onVisibleChange?: (value: boolean, prevValue: boolean) => void;
    getContainer?: GetContainer | false;
    mask?: React.ReactNode;
    maskClassName?: string;
    icons?: PreviewProps['icons'];
    scaleStep?: number;
    movable?: boolean;
    imageRender?: (originalNode: React.ReactElement, info: {
        transform: TransformType;
    }) => React.ReactNode;
    onTransform?: PreviewProps['onTransform'];
    toolbarRender?: (originalNode: React.ReactElement, info: Omit<ToolbarRenderInfoType, 'current' | 'total'>) => React.ReactNode;
}

**Comment by MadCcc** [comment]
可以组合使用，参考：https://ant.design/components/image-cn#image-demo-controlled-preview
