### ISSUE TITLE
Bug (Segmented) - when clicking an offscreen segmented, the page unexpectedly scrolls up

### ISSUE THREAD

**Issue by fribbels** [ant-design/ant-design#47461]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-xxccj3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clspom5v500062a67dg1czjeh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clspom5v500022a67q29084bf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clspom5v500032a672j02y7z1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clspom5v500052a67swk001vj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clspom5v500022a67q29084bf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clspom5v500012a67i7rg5d6f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A23%257D%255D%257D%255D%252C%2522id%2522%253A%2522clspom5v500022a67q29084bf%2522%252C%2522activeTabId%2522%253A%2522clspom5v500012a67i7rg5d6f%2522%257D%252C%2522clspom5v500052a67swk001vj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clspom5v500042a67vfldajyh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clspom5v500052a67swk001vj%2522%252C%2522activeTabId%2522%253A%2522clspom5v500042a67vfldajyh%2522%257D%252C%2522clspom5v500032a672j02y7z1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clspom5v500032a672j02y7z1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Scroll down a bit until the segmented is half off the screen, then click another option. The screen will scroll to the top which is undesired.

This also happens on the official documentation page : 

https://ant.design/components/segmented#segmented-demo-custom

If you scroll down so that the User 1/2/3 segmented is almost off the screen the click it, the whole documentation page will scroll. (The page header interferes with this so you have to scroll precisely here)

### What is expected?

I want the screen to stay in place when I click a segmented option, with no scrolling.

### What is actually happening?

The screen scrolls up

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | "react": "^18.2.0", |
| System | Windows |
| Browser | Firefox/chrome latest |

**Comment by fribbels** [comment]
Attaching video showing the bug on the official docs page https://ant.design/components/segmented#segmented-demo-custom

https://github.com/ant-design/ant-design/assets/7908525/3b84e89d-a6e5-4e41-844f-00488b7264b2

**Comment by fribbels** [comment]
This only happens if the segmented is partially offscreen, normal segmenteds generally work fine but if the segmented has height or icons that can go offscreen, then this can be disruptive.

**Comment by MadCcc** [comment]
Didn't get reproduced. Maybe a problem with windows.

**Comment by fribbels** [comment]
Yea you're right I just tried on my macbook and the Segmented will scroll so that the top of the segmented fits in the page, which is different behavior than Windows. On Windows it will try to scroll halfway up the page.

**Comment by heiyu4585** [comment]
结论: 初步怀疑为 浏览器 默认行为 差异

Uploading d95dd3cb82b29e4ee3967d2592cdbd6e.mp4…


如果部分 <label> 元素被遮挡，当用户点击该标签时，浏览器会尝试滚动到相应的输入元素位置，以确保用户可以看到所选的选项。
[link](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-zf4hx9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clspom5v500062a67dg1czjeh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clspom5v500022a67q29084bf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clspom5v500032a672j02y7z1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clspom5v500052a67swk001vj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clspom5v500022a67q29084bf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clspom5v500012a67i7rg5d6f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A11%257D%255D%257D%255D%252C%2522id%2522%253A%2522clspom5v500022a67q29084bf%2522%252C%2522activeTabId%2522%253A%2522clspom5v500012a67i7rg5d6f%2522%257D%252C%2522clspom5v500052a67swk001vj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clspom5v500042a67vfldajyh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clspom5v500052a67swk001vj%2522%252C%2522activeTabId%2522%253A%2522clspom5v500042a67vfldajyh%2522%257D%252C%2522clspom5v500032a672j02y7z1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clspom5v500032a672j02y7z1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by heiyu4585** [comment]
可以提供一些电脑的具体信息么,我用Windows并没有复现视频中的这个问题  window10
