### ISSUE TITLE
Mention组件添加是否在完成补全后自动添加空格的开关

### ISSUE THREAD

**Issue by caoyi0905** [ant-design/ant-design#4746]
Mention组件当前是在完成补全后自动添加空格的，但是我需要不添加该空格，自动添加空格可能也会对别的开发者带来困扰。或者是否有可以达成该效果的patch？

**Comment by paranoidjk** [comment]
受控模式下你可以完全控制输入的内容，参考 https://ant.design/components/mention-cn/#components-mention-demo-controllder-simple

但是建议保留空格，因为你后续应该是需要从文本里按特征提取mention的用户的

**Comment by RaoHai** [comment]
@paranoidjk 虽然是受控，但你真要自己处理 mention 的 state 的话会设计到 draft-js 的 API。。

加个配置叫 suffix 吧，默认是一个空格，可以配置为任意字符串。。

**Comment by paranoidjk** [comment]
@RaoHai  既然考虑加suffix，prefix也可以上去，或者更大自由度，做成一个render function 的 props，让用户决定把这个关键词渲染成什么样？

**Comment by RaoHai** [comment]
prefix 本来就有的，决定触发 suggestion 动作的 token。

原本的设计里，整个 mentioned 的 tag 都是可配置的（比如你可以放个图标），不过这样会很难再重新修改这个 tag，只能删掉。

**Comment by paranoidjk** [comment]
@RaoHai  get ✅  按你说的做吧~

**Comment by RaoHai** [comment]
不过还有个问题，不添加空格无法标识一个 mention 的结束。紧接着 @ 的内容输入一个字符，到底是在修改 mention，还是在输入无关的文字呢？

**Comment by paranoidjk** [comment]
说个参考，我做过webim在处理输入emoji字符是这样子的，**视觉上不能加空格，就用dom保存文本间的分段信息**
比如，选择用户完成之后可以让每个mention的整体dom带有特殊标志，类似被某个特殊class的span包裹；
这样做的缺点就是在后续输入的事件里，不可避免要去读取dom元素

**Comment by RaoHai** [comment]
是这样的，但是还是不能解决这个问题：

```html
<span class="mentioned">@paranoidjk</span>welcome
```

如果用户在 k 和 w 中间插入一个字符，如何判断用户是在更改 `@paranoidjk` ，还是在更改 welcome？ emoji 是一个整体，不存在局部修改的需求。

**Comment by paranoidjk** [comment]
的确，我的设想是用户选择了一个@对象之后是不能修改的，只能删掉...

**Comment by RaoHai** [comment]
Mention 组件其实也有不可修改只能删除的模式的。只是现在默认提供的是自由编辑的版本。

**Comment by paranoidjk** [comment]
回到最基本的，不考虑dom上的标志，要从一串文本里匹配特征提取，必然要有开头，结束的标志

所以假设只有前面的@，没有后面的空格或其他，这个需求应该是没办法的

**Comment by RaoHai** [comment]
不加空格其实改起来简单的。改完了之后交互会变得很怪。。

**Comment by benjycui** [comment]
这种有特殊意义的 token 还是要空格隔开吧，`@` 之前也自动加上空格看起来就舒服了

https://ant.design/docs/spec/typography-cn#空格规范

```
content @token content
```

**Comment by RaoHai** [comment]
`@` 之前不加空格的话， `@` 不会作为 token 被识别。

**Comment by benjycui** [comment]
我不懂你的需求 @caoyi0905 ，为什么要去掉空格？

在 `@` 前面已经加了空格的前提下，自动完成的后面也自动补上一个空格，看起来更加合理，毕竟 Ant Design 的设计规范也倾向于这样。

**Comment by caoyi0905** [comment]
@benjycui 我有一块需要支持代码补全。。感觉可以用Mention来做到。。不过还是非常感谢你们对此的讨论！

**Comment by benjycui** [comment]
没问题的话，建议自行关闭 issue.

**Comment by caoyi0905** [comment]
close #4746
