### ISSUE TITLE
Upload file by drag and drop component of Ant design doesn't work in Modal

### ISSUE THREAD

**Issue by neenachcha** [ant-design/ant-design#47465]
### What problem does this feature solve?

Currently the drag and drop component of the Upload file component won't fire the onDrop if the component is inside a modal.

### What does the proposed API look like?

onDrop should be fired, even if the component is inside the modal.

**Comment by neenachcha** [comment]
https://codesandbox.io/p/sandbox/react-dropzone-modal-forked-824c67?file=%2Fsrc%2FuploadModal.js%3A20%2C24
Drag and drop is not working if you drag through the shadow part.

**Comment by MadCcc** [comment]
Please make your codesandbox public
