### ISSUE TITLE
Why renderExtraFooter being called frequently when selecting times in RangePicker

### ISSUE THREAD

**Issue by suninuni** [ant-design/ant-design#47468]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn#components-date-picker-demo-extra-footer](https://ant-design.antgroup.com/components/date-picker-cn#components-date-picker-demo-extra-footer)

### Steps to reproduce

use dome in Ant Design

- Change renderExtraFooter like this

    ```js
    <RangePicker renderExtraFooter={() => {
            console.log('test')
            return 'extra footer';
        }} showTime />
    ```

- hover on the number to select date, and large number of 'test' will be show in console.

### What is expected?

- only be rendered when the whole range picker be randered.
- or use some API to controll this behavior.

### What is actually happening?

see the video

[screencast-ant-design.antgroup.com-2024.02.18-16_22_48.webm](https://github.com/ant-design/ant-design/assets/7345529/c25ad6e6-881a-4113-99f6-ca8a2d0d39ce)

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | latest |
| System | linux |
| Browser | latest |

**Comment by zombieJ** [comment]
All the render function will call repeatedly since it may deps on the closure data:

```tsx
const [count, setCount] = useState(0);

<DatePicker
  cellRender={() => <div onMouseEnter={() => srtCount(c => c + 1)}>...</div>}
  renderExtraFooter={() => count}
/>
```

You can call `useMemo` if no need react rerender it:

```tsx
const myFooter = useMemo(() => 'stable', []);

<DatePicker
  renderExtraFooter={() => myFooter}
/>
```
