### ISSUE TITLE
Ability to add and use more colors to the theme

### ISSUE THREAD

**Issue by AhmadMayo** [ant-design/ant-design#47460]
### What problem does this feature solve?

P.S. I'm not expert in design systems, so I may use the wrong terms, but I hope I'm able to describe the problem and the proposed solution

Currently Ant Design has the primary color and the states colors - warning/success/danger. But sometimes I use the library to build an app where the branding has a secondary or even a ternary color. The only solution I have now is to override Ant's theme using CSS to show a secondary button for example. This is cumbersome, as I always find a state that I forgot to handle - disabled, hover, focus, etc.

Having the ability to provide more colors in the theme with custom names, so that different shades will be automatically generated and used just like the primary color will be hugely beneficial.

### What does the proposed API look like?

```jsx
<ConfigProvider
  theme={{
    token: {
      colorSecondary: '#00b96b',
    },
  }}
>
  <Button
    type="secondary"
    {/* variant="secondary" */}
  >
    Theme 2
  </Button>
</ConfigProvider>
```

**Comment by MadCcc** [comment]
It's by design that ant design only have primary color, but you could implement this by HOC. For example:

```
const MyButton = (props) => (
  <ConfigProvider theme={{ token: { colorPrimary: props.type === 'secondary' ? colorSecondary : undefined } }}>
    <Button {...props} />
  </ConfigProvider>
);
```
