### ISSUE TITLE
建议添加全局滚动条，以解决在不同浏览器上滚动条一致性问题，望采纳

### ISSUE THREAD

**Issue by wsxe9988** [ant-design/ant-design#47470]
### What problem does this feature solve?

建议添加全局滚动条，以解决在不同浏览器上滚动条一致性问题，望采纳

### What does the proposed API look like?

建议添加全局滚动条，以解决在不同浏览器上滚动条一致性问题，望采纳

**Comment by afc163** [comment]
Try https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar

**Comment by Wxh16144** [comment]
不应该被添加 `won't do` 标签， 之前在 https://github.com/ant-design/ant-design/issues/43288 被认为是一个可设计的组件。请移步 #43288 讨论～
