### ISSUE TITLE
Badge component does not display correctly when browser zoom above 100%

### ISSUE THREAD

**Issue by jch254** [ant-design/ant-design#4747]
#### Environment

- antd version: 2.6.4
- OS and its version: macOS Sierra v10.12.3
- Browser and its version: Google Chrome v55.0.2883.95

#### What did you do? Please provide steps to re-produce your problem.

Increased browser zoom above 100% and rendered Badge component in ant.design documentation (https://ant.design/components/badge/#components-badge-demo-no-wrapper).

#### What did you expect?

Badge component should display correctly at all zoom levels - this is important for accessibility.

#### What happened?

Badge component is not displayed correctly when browser zoom above 100%.

<img width="575" alt="badge" src="https://cloud.githubusercontent.com/assets/3821107/22574474/21fc6e2a-ea03-11e6-9b79-b8463f20cd89.png">

#### Re-producible online demo

Visit https://ant.design/components/badge/#components-badge-demo-no-wrapper and increase browser zoom above 100%.

I found this related issue https://github.com/ant-design/ant-design/issues/4290 but could not figure out if it was solved (Google Translate struggles with Chinese).

**Comment by afc163** [comment]
I will fix this now.

**Comment by jch254** [comment]
@afc163 you are a champion, thanks!
