### ISSUE TITLE
Tooltip组件弹出层点击，会触发父元素的点击事件

### ISSUE THREAD

**Issue by atguo** [ant-design/ant-design#47476]
### Reproduction link

[https://stackblitz.com/edit/react-wed3bw?file=index.tsx](https://stackblitz.com/edit/react-wed3bw?file=index.tsx)

### Steps to reproduce

查看重现链接
1.正常写一个tooltip
2. 在tooptip外层使用div包一层。并绑定一个click事件
3. 触发tooltip，并移入弹出层点击

### What is expected?

点击弹出层能够不触发父元素的点击事件，或者提供屏蔽的方法

### What is actually happening?

现在点击会触发父元素事件，我尝试了屏蔽点击事件，但是这样当数据移入弹出层的时候，弹出层会消失

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 18.2.0 |
| System | window10 |
| Browser | Edge 121.0.2277.128  |

**Comment by afc163** [comment]
这是 React 模拟的事件冒泡，符合预期的。如果不需要请自行包装阻断。

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-wed3bw-fgbtjq?file=demo.tsx

**Comment by atguo** [comment]
> https://stackblitz.com/edit/react-wed3bw-fgbtjq?file=demo.tsx



> [<img alt="Fix this issue in StackBlitz Codeflow" width="117" height="20" src="https://camo.githubusercontent.com/5a011a63dfc9deab5e5c0ce5df3153deed677a6f50bffe1036c8258afd66edc3/68747470733a2f2f646576656c6f7065722e737461636b626c69747a2e636f6d2f696d672f6669785f746869735f69737375655f736d616c6c2e737667">](https://stackblitz.com/~/github.com/ant-design/ant-design/issues/47476?repros=react-wed3bw) _Start a new pull request in [StackBlitz Codeflow](https://stackblitz.com/~/github.com/ant-design/ant-design/issues/47476?repros=react-wed3bw)._
> 
> * [**react-wed3bw** (Open reproduction)](https://stackblitz.com/edit/react-wed3bw?issueRepo=ant-design/ant-design&issueNumber=47476)



> https://stackblitz.com/edit/react-wed3bw-fgbtjq?file=demo.tsx

没想到还有这种方式，谢谢~
