### ISSUE TITLE
Form rules max min 行为不正确

### ISSUE THREAD

**Issue by sequarius** [ant-design/ant-design#47480]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/gifted-rumple-5tfzx7?file=%2FApp.tsx%3A95%2C1-96%2C1)

### Steps to reproduce

输入任意数字

### What is expected?

max以内的数字可以pass校验

### What is actually happening?

输入任何内容都是校验不通过

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 121.0.6167.85 |

**Comment by MadCcc** [comment]
公开一下 codesandbox，现在无法访问

**Comment by sequarius** [comment]
> 公开一下 codesandbox，现在无法访问
已公开

**Comment by seeintea** [comment]
转换下数据吧 文档有 `transform` 这个字短 可以看下 [https://ant-design.antgroup.com/components/form-cn#rule](https://ant-design.antgroup.com/components/form-cn#rule)

```js
const transform = (value) => {
  return value.number || 0;
};

// 修改 rules
rules={[
  {
    max: 100,
    type: "number",
    message: "Price must be less than 100!",
    transform,
  },
]}
```
