### ISSUE TITLE
Form preserve 设置为 false，字段销毁后 getFieldValue 和 useWatch 仍能获取到字段值

### ISSUE THREAD

**Issue by Enivia** [ant-design/ant-design#47482]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-getfieldvalue-bug-rc7ctq?file=%2Fdemo.tsx%3A15%2C32&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clssnkqf80006356j9rg75e1m%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clssnkqf80002356jn3560whb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clssnkqf80003356jp374ye0y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clssnkqf80005356jth88zddl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clssnkqf80002356jn3560whb%2522%253A%257B%2522id%2522%253A%2522clssnkqf80002356jn3560whb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsso1w2g0002356juhbij6ft%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsso1w2g0002356juhbij6ft%2522%257D%252C%2522clssnkqf80005356jth88zddl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clssnkqf80004356joft0civs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clssnkqf80005356jth88zddl%2522%252C%2522activeTabId%2522%253A%2522clssnkqf80004356joft0civs%2522%257D%252C%2522clssnkqf80003356jp374ye0y%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clssnkqf80003356jp374ye0y%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

- 设置 Form preserve 属性为 false
- toggle hidden 隐藏 username 字段

### What is expected?

通过 getFieldsValue 获取的表单数据中 username 为空，但 getFieldValue 或 useWatch 仍能获取到字段值

### What is actually happening?

getFieldValue 或 useWatch 获取的 username 也为空

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 120 |

**Comment by afc163** [comment]
<img width="948" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/63f65bf4-3233-40d5-a10d-39454280f499">

**Comment by Enivia** [comment]
@afc163 已更新 demo 链接

**Comment by ces-s-l** [comment]
form的文档：在大部分场景下，我们总是推荐优先使用 Form 的 initialValues。只有存在动态字段时你才应该使用 Item 的 initialValue。
这种动态表单使用item的initialValue进行赋默认值比较好。

**Comment by Enivia** [comment]
> form的文档：在大部分场景下，我们总是推荐优先使用 Form 的 initialValues。只有存在动态字段时你才应该使用 Item 的 initialValue。 这种动态表单使用item的initialValue进行赋默认值比较好。

那 preserve 这个属性的意义是什么呢？

**Comment by zombieJ** [comment]
* `preserve=false` 时，顾名思义不会保留值，移除字段会重置回 `initialValue`。 
* `getFieldsValue` 返回的是当前存在字段的值，要获取全部字段值使用 `getFieldsValue(true)`。
* `getFieldValue` 为指定路径，会从 Form Store 里按照路径查找，而略过字段存续检查。因为一般指定路径，说明是需要这个值，就不拦截了。

**Comment by Enivia** [comment]
> @Enivia 你是从3.x升级上来吗？如果是的话，确实不一样了。

是从很早开始用的。当前的行为和认知的不一样吧。

**Comment by yoyo837** [comment]
> > @Enivia 你是从3.x升级上来吗？如果是的话，确实不一样了。
> 
> 是从很早开始用的。当前的行为和认知的不一样吧。

就是从4.x开始变的

**Comment by Enivia** [comment]
@zombieJ @yoyo837 对于动态表单，移除字段，值重置回 `initialValue` 真的合理吗？可否解释下为何这样设计。

> * `preserve=false` 时，顾名思义不会保留值，移除字段会重置回 `initialValue`。
