### ISSUE TITLE
RangePicker can't show correct date when clicking twice rapidly

### ISSUE THREAD

**Issue by cnzsb** [ant-design/ant-design#47492]
https://github.com/ant-design/ant-design/assets/9855853/9dc13b17-c96a-4edc-9f08-40c3cf6ec2ff

### Reproduction link

[https://ant.design/components/date-picker#components-date-picker-demo-range-picker](https://ant.design/components/date-picker#components-date-picker-demo-range-picker)

### Steps to reproduce

Situation A
1. Open the popup of RangePicker and select one day both as start date and end date, make sure click the date twice very rapidly.
2. Then the selected date will be only showed one in the RangePick input and another will be missing. However, the display value will be correct if you blur the RangePicker.
Situation B
1. Then don't clear the selected date above, and just repeat the above steps with a different target date as both start date and end date.
2. Now the date value will be a situation A value and a situation B value, but the value is suppose to be only the situation B date as both start date and end date.

### What is expected?

RangePicker's value should be correct displayed and `onChange`.

### What is actually happening?

Refer to -> 'Step to reproduce'

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 17 |
| System | MacOS |
| Browser | Chrome latest |

**Comment by zombieJ** [comment]
Double click will be confirm operation. Seem this is conflict with quick selection.

ref #44295
