### ISSUE TITLE
dropdown 打开 Modal 时，若打开时鼠标在其它 dropdown 上，其它 dropdown 会展开一下

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#47499]
### Reproduction link

[https://stackblitz.com/edit/react-lzj8ld?file=demo.tsx](https://stackblitz.com/edit/react-lzj8ld?file=demo.tsx)

### Steps to reproduce

1、hover 到第一个 dropdown，点击 item 打开 Modal（点击 item 时鼠标要在其它 dropdown 上）

### What is expected?

其它 dropdown 不会展开

### What is actually happening?

其它 dropdown 展开了

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
确实，应该要盖住的。
