### ISSUE TITLE
Default timezone for DatePicker

### ISSUE THREAD

**Issue by AAAAAAAAlan** [ant-design/ant-design#47490]
### What problem does this feature solve?

Currently, there is no way to set the default timezone for DatePicker. There have been multiple issues on this topic, but all were closed, and the problem still exists.

Issue #45880 - The default timezone for Day.js doesn't apply to DatePicker by itself. I think it's because DatePicker uses the `dayjs()` object, and the default timezone applies only to the `dayjs().tz()` object. Therefore, you can pass a custom function in the format prop, but it will result in disabled keyboard input and a divergence between the time in the panel and the time in the input itself.

Reproduction URL: https://codesandbox.io/p/sandbox/pedantic-bas-q7hj82 
This issue was also mentioned by other community members: https://github.com/ant-design/ant-design/issues/11012#issuecomment-1359213581

Issue #45502 - This issue was closed after Wxh16144 posted his example of a dynamic timezone change. This indeed works; however, if you remove your date completely with the X button, it resets to the default `dayjs()` object, and you see your local timezone again until you explicitly pass the `dayjs().tz()` object into your picker.

Here is the reproduction URL with slightly changed code by Wxh16144: https://codesandbox.io/p/sandbox/datepickertz-forked-rgx52p?file=%2Fdemo.tsx

### What does the proposed API look like?

We could have an ability to pass default `dayjs` objects into a picker. 
```
<DatePicker
 defaultDateObject={dayjs.tz()}
 ...restProps
 />
```
Or we could have new prop, like `carmenchapa` suggested in issue #45880.

```
<DatePicker
 timezone='Europe/London'
 ...restProps
 />
```

**Comment by MadCcc** [comment]
If you only demand static default timezone, why not just set timezone at top level?

```tsx
dayjs.extend(utc)
dayjs.extend(timezone)

dayjs.tz.setDefault("America/New_York")

const App = () => {
  // ...
}
```

**Comment by yoyo837** [comment]
It seems that this is not enough, mabey also need `dayjs(xxx)` => `dayjs.tz(xxx)`.

**Comment by zombieJ** [comment]
It's not a good idea to handle timezone logic on the component side since developer may use date object without DatePicker. It will make logic much complex.

It's better to config timezone globally like @MadCcc 's advance (https://github.com/ant-design/ant-design/issues/47490#issuecomment-1953543180).

PS: You can use `defaultPickerValue` to pass with date object of special timezone but again, I don not think it's a good idea to only handle timezone on the Picker component instead of globally config.

**Comment by AAAAAAAAlan** [comment]
> If you only demand static default timezone, why not just set timezone at top level?
> 
> ```tsx
> dayjs.extend(utc)
> dayjs.extend(timezone)
> 
> dayjs.tz.setDefault("America/New_York")
> 
> const App = () => {
>   // ...
> }
> ```

It's what I did in a first example. When DatePicker is empty, it would still use your local timezone. 
Check it out by yourself: https://codesandbox.io/p/sandbox/pedantic-bas-q7hj82

**Comment by Walter-Sparrow** [comment]
@zombieJ I don't think the issue needs to be closed, as @AAAAAAAAlan stated in https://github.com/ant-design/ant-design/issues/47490#issuecomment-1954054498 components act in local timezone whether you set `days.tz.setDefault` or/and change format in the picker

**Comment by biloholovskyi** [comment]
+1

**Comment by noklen** [comment]
+1

**Comment by moogur** [comment]
Very urgent problem

**Comment by gretskovart** [comment]
+1

**Comment by Walter-Sparrow** [comment]
In our project, I created a custom `generateConfig` and used it to generate a DatePicker using the `generatePicker` function, which can be imported from `antd/es/date-picker/generatePicker`.

The entire snippet looks like the following:
```ts
import generatePicker from "antd/es/date-picker/generatePicker";
import { Dayjs } from "dayjs";
import generateConfig from "./lib/generateConfig";

const DatePicker = generatePicker<Dayjs>(generateConfig);

export type DatePickerType = typeof DatePicker & {
  generatePicker: typeof generatePicker;
};

(DatePicker as DatePickerType).generatePicker = generatePicker;

export default DatePicker as DatePickerType;
```

I modified `generateConfig` to suit my needs, so it won't be useful for this question, but you can find an example of creating it in the [antd source code](https://github.com/react-component/picker/blob/master/src/generate/dayjs.ts) so you can just modify the `dayjs` instances to use `.tz`

**Comment by CoCoManYY** [comment]
+1

**Comment by DanielEngelhardt3TS** [comment]
+1

**Comment by wowhaha7pupu** [comment]
不明白为何这问题仍然存在著，但却是关掉了

**Comment by gostave** [comment]
still an issue

**Comment by DanielMenke** [comment]
Reopen please.

**Comment by HiddenTesla** [comment]
这个问题不修 俺就不用支付宝了

**Comment by shangxiao** [comment]
The Ant people have invented a new way to fix bugs: Just close it as completed and it magically fixes it without making any code changes. 好麻烦啦

**Comment by ahmedmelfay** [comment]
I can confirm this problem is a huge pain in the a**, But if you are using the picker inside Form.Item, theres a neat fix

In your form item props you can pass these

```
export const timeFormItemProps: FormItemProps = {
  getValueFromEvent: (value) => value?.map((time: Dayjs) => time?.utc().format("HH:mm")),
  getValueProps: (value) => ({
    value: value?.map((time: string) => dayjs.utc(time, "HH:mm").local()),
  }),
};
```

And pass in FormItem like this

```
<Form.Item label={t("pages.reports.features.time")} name="time" {...timeFormItemProps}>
  <AntdTimePicker />
</Form.Item>
```

Note that I'm using this with Range Values and timepicker not datepicker, but works also with single picker either time or date, and this was my use case which I must store the values in UTC hour and minute format which is done through getValueFromEvent and transform back to local time for rendering using getValueProps
