### ISSUE TITLE
antd组件table示例问题

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#4750]
滚动前
![default](https://cloud.githubusercontent.com/assets/11780264/22583842/0df2feae-ea2a-11e6-8061-81beea5d1397.png)

滚动后
![default](https://cloud.githubusercontent.com/assets/11780264/22583867/29d4c4ea-ea2a-11e6-9248-572a4372b905.png)

滚动前列头和列是左对齐的,但是滚动后就成居中对齐了

**Comment by yesmeck** [comment]
浏览器？

**Comment by yesmeck** [comment]
重现了。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4637

这里改坏了。:sweat:
