### ISSUE TITLE
Passing false as moreIcon prop of Tabs component

### ISSUE THREAD

**Issue by alex-golubtsov** [ant-design/ant-design#47507]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/hungry-dijkstra-4k28ws?file=%2Fdemo.tsx%3A32%2C24)

### Steps to reproduce

- Open the link
- Shrink your screen to 500px (to hide a part of tabs)
- Visually there is no icon, but if you hover over the place, where usually there is an ellipsis icon, dropdown triggers

### What is expected?

No dropdown is triggered

### What is actually happening?
Dropdown triggers, when hovering over empty space

P.S. As discussed in #47433, passing `null` instead of `false` doesn't solve the issue

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.x |
| System | macOs |
| Browser | Chrome |

**Comment by MadCcc** [comment]
So that your demand is to hide the more button? It may need more style (such as shadow) to let user know there's more tabs hidden.

**Comment by afc163** [comment]
Closed in favor of https://github.com/ant-design/ant-design/pull/48321
