### ISSUE TITLE
Need a dark mode Divider style in Menu component

### ISSUE THREAD

**Issue by zhumeisongsong** [ant-design/ant-design#47502]
### What problem does this feature solve?

When I use dark mode, since the divider color is dark, I can't see it.
<img width="492" alt="image" src="https://github.com/ant-design/ant-design/assets/18430762/1b2bc9ba-52bb-4a71-95b8-54a9527ec0e5">

### What does the proposed API look like?

If we have
```` 
[
  {
    type: "divider",
    mode: 'light' // light | dark
  }
]
````
 it will be great.

**Comment by MadCcc** [comment]
It's bug in antd official site. There's no problem with dark algorithm
![image](https://github.com/ant-design/ant-design/assets/27722486/8f735022-8bee-4d52-b8cb-fdf70405eb57)
