### ISSUE TITLE
关于Ant DS 弹出性提示只能触发一次问题(VUE)

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [ant-design/ant-design#47514]
### Reproduction link

[https://github.com/ErrorCodesForLzx/pop_result](https://github.com/ErrorCodesForLzx/pop_result)

### Steps to reproduce

1. 鼠标移动a-tooltip里面，然后移出，重复几次
2. 点击 日期选择，点击空白处，重复几次

### What is expected?

能够像文档一样多次触发

### What is actually happening?

在页面挂载完毕的时候可以正常触发一次，但是第二次触发就会闪缩一次

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | （使用的vue）3.2.13 |
| System | Windows11（Home edition） |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 |

---
使用时Chrome浏览器，vue3，
脚手架环境： 
npm: '10.2.4'
node: '20.11.0’

**Comment by li-jia-nan** [comment]
来错仓库了……

**Comment by li-jia-nan** [comment]
https://github.com/vueComponent/ant-design-vue
