### ISSUE TITLE
输入框中后面出现特殊符号

### ISSUE THREAD

**Issue by ZhuyuAndCoder** [ant-design/ant-design#47513]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-hp3w9v?file=%2Findex.js%3A15%2C31)

![issue](https://github.com/ant-design/ant-design/assets/17719076/96f87de2-69e5-41d4-adb7-25c834ce744d)

### Steps to reproduce

偶尔出现，强刷后消失

### What is expected?

不出现这种状态

### What is actually happening?

偶尔出现特殊符号

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | windows |
| Browser | chrome |

---
i

**Comment by zombieJ** [comment]
设置一下 codesandbox 权限为公开，另外你的这个看起来像是游览器插件 or 网页翻译造成的。
