### ISSUE TITLE
[DatePicker] maxDate makes the picker open in the previous month of maxDate when this prop is today or past

### ISSUE THREAD

**Issue by ofabricioS** [ant-design/ant-design#47511]
### Reproduction link

[https://stackblitz.com/edit/react-lvphck?file=demo.tsx](https://stackblitz.com/edit/react-lvphck?file=demo.tsx)

### Steps to reproduce

- Use maxDate prop
- Open the DatePicker
- Check that the picker will open in the previous month of the maxDate selected

Ps: Don't use defaultValue prop, it makes the picker open on the selected month

### What is expected?

1. Max Date is today: Open the DatePicker with the current month, for a better UX.
2. Max Date is past: Open the DatePicker with the max date month, because now it seems as it opens in a random month/year, and when using a minDate and maxDate in the same month, it's completelly nonsense to open it on previous month, where all days are disabled.

### What is actually happening?

Using max date opens in the previous month of maxDate when this prop is today or past

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by nederhayden** [comment]
The problem remains for me.

Environment | Info
antd | 5.16.2
React | 18.2.0
System | Windows 11
Browser | Edge

![maxdate](https://github.com/ant-design/ant-design/assets/33813497/2ad0dbde-7a79-4736-b273-ddad05f0cbec)
