### ISSUE TITLE
相同在代码，在5.14.1版本后，RangePicker的onChange事件失效

### ISSUE THREAD

**Issue by liujing0921** [ant-design/ant-design#47516]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js)

### Steps to reproduce

进行选择时间操作

### What is expected?

选择时间，会触发onChange事件

### What is actually happening?

选择时间，未触发onChange事件

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | ^18.2.0 |
| System | 10.0.22621版本22621 |
| Browser | 121.0.2277.128 (正式版本) (64 位) |

---
antd版为5.14.1时异常，之前都能正常使用.去除onCalendarChange和onOpenChange事件，onchange事件能正常触发，但我使用的场景需要限制时间间隔为1年，所以需要这两个事件。

**Comment by zombieJ** [comment]
之前有个 BUG，受控时如果 `value` 和提交时候的 `value` 相同还会触发 `onChange` 事件。这个代码看起来是在 `onCalendarChange` 时改了受控 `value` 导致提交时值已经是目标值所以不会触发 `onChange` 事件，是符合预期的。能细说说为什么不用 `onChange` 做受控而是用 `onCalendarChange` 不？

**Comment by liujing0921** [comment]
我不认为符合预期，当代码修改为不展示时间后：https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js%3A87%2C24，onchange事件能正常触发。如果符合预期，上述情况应该也是不能触发吧。

为什么不用 onChange 做受控而是用 onCalendarChange：
我需要控制时间选择范围在一年内,由于disabledDate参数没有当前的区间时间，所以我通过onCalendarChange去获取。

**Comment by liujing0921** [comment]
> 之前有个 BUG，受控时如果 `value` 和提交时候的 `value` 相同还会触发 `onChange` 事件。这个代码看起来是在 `onCalendarChange` 时改了受控 `value` 导致提交时值已经是目标值所以不会触发 `onChange` 事件，是符合预期的。能细说说为什么不用 `onChange` 做受控而是用 `onCalendarChange` 不？

我不认为符合预期，当代码修改为不展示时间后：https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js%3A87%2C24，onchange事件能正常触发。如果符合预期，上述情况应该也是不能触发吧。

为什么不用 onChange 做受控而是用 onCalendarChange：
我需要控制时间选择范围在一年内,由于disabledDate参数没有当前的区间时间，所以我通过onCalendarChange去获取。

**Comment by liujing0921** [comment]
> 之前有个 BUG，受控时如果 `value` 和提交时候的 `value` 相同还会触发 `onChange` 事件。这个代码看起来是在 `onCalendarChange` 时改了受控 `value` 导致提交时值已经是目标值所以不会触发 `onChange` 事件，是符合预期的。能细说说为什么不用 `onChange` 做受控而是用 `onCalendarChange` 不？
感谢你的回复，我知道原因了。衍生问题：当代码修改为不展示时间后[：[https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js%3A87%2C24](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js%3A87%2C24)，onchange事件能正常触发，这种情况应该也不能触发吧。

为什么不用 onChange 做受控而是用 onCalendarChange：
我需要控制时间选择范围在一年内,由于disabledDate参数没有当前的区间时间，所以我通过onCalendarChange去获取。目前已有解决方案：不给value赋值dates就好了。

**Comment by liujing0921** [comment]
> 之前有个 BUG，受控时如果 `value` 和提交时候的 `value` 相同还会触发 `onChange` 事件。这个代码看起来是在 `onCalendarChange` 时改了受控 `value` 导致提交时值已经是目标值所以不会触发 `onChange` 事件，是符合预期的。能细说说为什么不用 `onChange` 做受控而是用 `onCalendarChange` 不？

感谢你的回复，我知道原因了。衍生问题：当代码修改为不展示时间后：https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js%3A64%2C16-64%2C21，onchange事件能正常触发，这种情况应该也不能触发吧。
为什么不用 onChange 做受控而是用 onCalendarChange：
我需要控制时间选择范围在一年内,由于disabledDate参数没有当前的区间时间，所以我通过onCalendarChange去获取。目前已有解决方案：不给value赋值dates就好了。

**Comment by zombieJ** [comment]
新版本的 `disabledDate` 第二个参数 `info.from` 会告诉你用户的第一次选择时间。这个在每次重新选择都会重置。可以看看这个改造后的例子哈~
https://ant-design.antgroup.com/components/date-picker-cn#components-date-picker-demo-select-in-range

**Comment by BearTheMad** [comment]
> 之前有个 BUG，受控时如果 `value` 和提交时候的 `value` 相同还会触发 `onChange` 事件。这个代码看起来是在 `onCalendarChange` 时改了受控 `value` 导致提交时值已经是目标值所以不会触发 `onChange` 事件，是符合预期的。能细说说为什么不用 `onChange` 做受控而是用 `onCalendarChange` 不？

请问这个bug怎么修复，value相同onchange不触发的问题

**Comment by BearTheMad** [comment]
> > 之前有个 BUG，受控时如果 `value` 和提交时候的 `value` 相同还会触发 `onChange` 事件。这个代码看起来是在 `onCalendarChange` 时改了受控 `value` 导致提交时值已经是目标值所以不会触发 `onChange` 事件，是符合预期的。能细说说为什么不用 `onChange` 做受控而是用 `onCalendarChange` 不？
> 
> 感谢你的回复，我知道原因了。衍生问题：当代码修改为不展示时间后：[https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js%3A64%2C16-64%2C21，onchange事件能正常触发，这种情况应该也不能触发吧。](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-v3ycq4?file=%2Findex.js%3A64%2C16-64%2C21%EF%BC%8Conchange%E4%BA%8B%E4%BB%B6%E8%83%BD%E6%AD%A3%E5%B8%B8%E8%A7%A6%E5%8F%91%EF%BC%8C%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5%E5%BA%94%E8%AF%A5%E4%B9%9F%E4%B8%8D%E8%83%BD%E8%A7%A6%E5%8F%91%E5%90%A7%E3%80%82) 为什么不用 onChange 做受控而是用 onCalendarChange： 我需要控制时间选择范围在一年内,由于disabledDate参数没有当前的区间时间，所以我通过onCalendarChange去获取。目前已有解决方案：不给value赋值dates就好了。
请问你是怎么解决的，我遇到相同的问题，必须用这种表达式value={dates||value}，因为要在打开修改的的时候临时清空，关闭恢复原值，不清楚是不是依赖导致的 ，之前好像没这问题

**Comment by yoyo837** [comment]
我们在5.14.0中完全重写了DatePicker等一些列Picker组件。

**Comment by BearTheMad** [comment]
> 我们在5.14.0中完全重写了DatePicker等一些列Picker组件。

谢谢，刚试了下，升级之后确实没这问题了，不用处理dates，写法也简单很多
