### ISSUE TITLE
type: number 校验规则异常

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#47523]
### Reproduction link

[https://stackblitz.com/edit/react-wu9dsb?file=demo.tsx](https://stackblitz.com/edit/react-wu9dsb?file=demo.tsx)

### Steps to reproduce

在输入框中输入 123

### What is expected?

123 是一个合法的数字，应该没有校验错误

### What is actually happening?

校验错误

![image](https://github.com/ant-design/ant-design/assets/5836790/df69950b-07f4-4186-87f0-be2252fa8f0a)

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2.0 |
| System | maOS |
| Browser | Chrome 121 |

**Comment by Wxh16144** [comment]
输入框输入的是文本 即 `"123"`

**Comment by Wxh16144** [comment]
> 那这个错误提示是不是不对？

这个错误对的，antd 用的 async-validato 库。必须得是 `typeof val === "number"` 才行。

> 另外，这个设计和 HTML 自带的 type="number" 校验也不相符。

也是预期的

**Comment by guoyunhe** [comment]
async-validator 这个库已经死了吧，已经两年没人维护了
