### ISSUE TITLE
Form 设置 prefixCls 后样式失效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47527]
### Reproduction link

[https://stackblitz.com/edit/react-bmdx3d?file=demo.tsx](https://stackblitz.com/edit/react-bmdx3d?file=demo.tsx)

### Steps to reproduce

1. 查看 demo

### What is expected?

2 个 Form 样式一样

### What is actually happening?

2 个 Form 样式不一样

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Form 和 Form.Item 的 prefixCls 需要保持一致：https://stackblitz.com/edit/react-bmdx3d-bwcpsa?file=demo.tsx
