### ISSUE TITLE
table列头与列错位

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#4753]
环境
 win8.1

浏览器
55.0.2883.75

antd版本
v2.6.4

操作步骤
(1)  给列赋值固定宽度
(2) 添加固定操作列
(3)添加scroll属性为{x:false,y:100}  展示出y轴滚动条

现象
列头与列错位

重现地址
https://codepen.io/GAOBO/pen/ggzWzw

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/4750
