### ISSUE TITLE
Modal not destroy when fired twice time

### ISSUE THREAD

**Issue by N3iV** [ant-design/ant-design#47536]
### Reproduction link

[ https://github.com/ant-design/ant-design/assets/151809163/3889c9df-4605-41a9-a201-db0486698ded]( https://github.com/ant-design/ant-design/assets/151809163/3889c9df-4605-41a9-a201-db0486698ded)

### Steps to reproduce

When clicking open modal too fast, it will be duplicate

### What is expected?

Destroy last open modal or not duplicate

### What is actually happening?

It duplicates same modal

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | ^18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/47508
