### ISSUE TITLE
当表格固定右侧的时候，固定列和边界有比较明显的缝隙

### ISSUE THREAD

**Issue by yk9710** [ant-design/ant-design#47538]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/table-cn/#components-table-demo-fixed-columns](https://4x-ant-design.antgroup.com/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce

v4demo表格固定列
![image](https://github.com/antvis/G2/assets/102608044/db698139-8e6b-4d32-bedf-39b39071d228)

### What is expected?

无缝隙

### What is actually happening?

有明显的缝隙，发现缝隙不是一定会产生，只会在特定的情况下有

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by yk9710** [comment]
[之前有过类似的issue](https://github.com/ant-design/ant-design/issues/47538)

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/28093
