### ISSUE TITLE
ColorPicker当首次没有value和defaultValue时，通过其他方式手动赋值value，构件一直展示清除样式

### ISSUE THREAD

**Issue by L-fingerprint** [ant-design/ant-design#47539]
### Reproduction link

[https://ant.design/components/color-picker-cn](https://ant.design/components/color-picker-cn)

### Steps to reproduce

```
import React, { useState } from "react";
import "./index.css";
import { ColorPicker, Space, Button } from "antd";

const Demo = () => {
  const [colorValue, setColorValue] = useState();
  return (
      <Space direction="vertical">
        <ColorPicker
          value={colorValue}
          onChange={setColorValue}
          showText
        />
        <Button
          onClick={() => {
            setColorValue("#FF0000");
          }}
        >
          Click
        </Button>
      </Space>
  );
};
export default Demo;
```

### What is expected?

按钮点击之后应该显示正常颜色，而不是清除的样式

### What is actually happening?

颜色未正常展示

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.0.0 |
| System | mac |
| Browser | 121.0.6167.184 |

**Comment by lhojun** [comment]
I have same problem.
If the color is changed by another component, not by the color picker,
then the color preview on the color picker does not update and remains the same as the color before the change.

**Comment by yoyo837** [comment]
Has anyone worked on this? I want to claim it.

**Comment by huiliangShen** [comment]
> Has anyone worked on this? I want to take it.
I tried for a while, but got stuck in the next case...need rely on your solution. hhh

**Comment by huiliangShen** [comment]
> I have same problem. If the color is changed by another component, (In my Case, Save color and reset empty color - "" ) then the color preview on the color picker does not update and remains the same as the color before the change.

In your case, I find when `color-picker`  prop `showText = true` and follow your steps to operation, text will not changed, still show last value.

**Comment by lhojun** [comment]
> > I have same problem. If the color is changed by another component, (In my Case, Save color and reset empty color - "" ) then the color preview on the color picker does not update and remains the same as the color before the change.
> 
> In your case, I find when `color-picker` prop `showText = true` and follow your steps to operation, text will not changed, still show last value.

Thank you for your insight. However, I'm not using that prop. In my case, the color value is decided at the time of the first render `color-trigger`. It may change with the `onChange` event of `color-picker`, but when I reset the color through another component (like after a reset or submit, which clears all values including color), or if the color value is undefined at the time of rendering and changes a few milliseconds after, `color-trigger` still shows the previous color, not the changed color.

**Comment by yoyo837** [comment]
I just sent a PR to fix this problem, everyone is welcome to help review it.
