### ISSUE TITLE
Deprecated API showSecond still in types for DatePicker & Co

### ISSUE THREAD

**Issue by AO19** [ant-design/ant-design#47535]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-date-picker-showsecond-4njx6j?file=/index.js)

### Steps to reproduce

Select a date and than try to select the time.

### What is expected?

I can select time.

### What is actually happening?

Time options are not visible, they disappear.

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2.0 |
| System | 14.3.1 (23D60) |
| Browser | Chrome Version 121.0.6167.184 |

**Comment by MadCcc** [comment]
`showSecond` only works in TimePicker, just remove it.
