### ISSUE TITLE
Close select dropdown on background scroll

### ISSUE THREAD

**Issue by SonaGharibyan** [ant-design/ant-design#47532]
### What problem does this feature solve?

The problem I face is that when I have a small scrollable container with select component during scroll with open dropdown the dropdown gets out of the container. The solution for it can be using 'getPopupContainer' but in that case the dropdown gets cropped and not fully visible in case of small space and long options list. 

### What does the proposed API look like?

The solution I see is to close the dropdown on container scroll.
I expect it to either be default functionality or a boolean property and set to true the dropdown will close on container scroll

**Comment by SonaGharibyan** [comment]
The problem I've described 
![image](https://github.com/ant-design/ant-design/assets/68944069/95e64ff0-3c9f-4630-8e89-94d6d1891013)
![image](https://github.com/ant-design/ant-design/assets/68944069/a1582875-b2d3-49e2-a720-26ddb6427051)

**Comment by Mumujianguang** [comment]
you can use ref of select to make it blur when background scroll or mouse wheel
![image](https://github.com/ant-design/ant-design/assets/52249626/4695894c-afad-433b-ade9-cb1dac43739a)

**Comment by SonaGharibyan** [comment]
@Mumujianguang thanks for quick replay I guess it will work. But actually we have a custom component library based on ant and container is not always easily accessible. Do you think there is a way to do it without container ref ?

**Comment by Mumujianguang** [comment]
> @Mumujianguang thanks for quick replay I guess it will work. But actually we have a custom component library based on ant and container is not always easily accessible. Do you think there is a way to do it without container ref ?

i think it doesn't a good solution that through component to deal the issue. if you do that will introduce some side effects.
for example, the component traverses all parent elements, finds out those with scroll bars and adds scroll events to them, but DOM operation is not what react advocates.
so you should deal it in your project

**Comment by SonaGharibyan** [comment]
yeah, got you. Thanks a lot
