### ISSUE TITLE
Pagination中的onChange是否能够获得pageSize？

### ISSUE THREAD

**Issue by zerozaki0752** [ant-design/ant-design#4754]
Table中的onChange可以拿到pagination对象，而Pagination的onChange只能获得currentPage。
1、为什么这样设计？
2、单独使用Pagination应该怎样获取pageSize？

**Comment by afc163** [comment]
```
const pageSize = 20;
<Pagination pageSize={pageSize} onChange={current => this.handleChange(current, pageSize)} />
```

**Comment by afc163** [comment]
可以去给 http://github.com/react-component/pagination 提个 issue，加上必要的其他参数。
