### ISSUE TITLE
`DatePicker.RangePicker` shows empty list with props `picker="time"` and `showSecond={false}`

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#47549]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-mkjml6?file=src%2FApp.tsx)

### Steps to reproduce

Open the link and click on DatePicker

### What is expected?

It should show a list of hours and minutes.

### What is actually happening?

There is an empty list.

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 121 |

**Comment by crudo** [comment]
Probably broken by https://github.com/ant-design/ant-design/pull/46982

**Comment by Elendiar** [comment]
I noticed that this happened to me too
<img width="474" alt="image" src="https://github.com/ant-design/ant-design/assets/3886001/10996ecd-23a3-48e7-8eaf-671d512101d2">
