### ISSUE TITLE
TreeSelect 新增 needAll 属性

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#47541]
### What problem does this feature solve?

treeData 是一个数组，通常不止有一个元素，为了方便快速全选，需要在下拉列表的顶部新增一个 '全部' 的 checkbox，通过该 checkbox 快速实现全选效果。

### What does the proposed API look like?

新增 needAll 属性，该属性需要与treeCheckable搭配使用

**Comment by afc163** [comment]
Duplicate of #30041
