### ISSUE TITLE
Checkbox indeterminate state style inner not affected by the border radius

### ISSUE THREAD

**Issue by mehdi-dalil** [ant-design/ant-design#47548]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-yygrln?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsxi0rw800063b6f6xvme9au%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsxi0rw800023b6f4gp7l4ly%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsxi0rw800033b6f3xc5fdui%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsxi0rw800053b6fk6zotj3h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsxi0rw800023b6f4gp7l4ly%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxi0rw700013b6f5drtfbfi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsxi0rw800023b6f4gp7l4ly%2522%252C%2522activeTabId%2522%253A%2522clsxi0rw700013b6f5drtfbfi%2522%257D%252C%2522clsxi0rw800053b6fk6zotj3h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxi0rw800043b6fy2x793e9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsxi0rw800053b6fk6zotj3h%2522%252C%2522activeTabId%2522%253A%2522clsxi0rw800043b6fy2x793e9%2522%257D%252C%2522clsxi0rw800033b6f3xc5fdui%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsxi0rw800033b6f3xc5fdui%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Create a theme and add a border radius on the Checkbox component. Create a Table with the prop rowSelection, select only 1 item in your table and see the indeterminate inner style not being affected by the border-radius.

### What is expected?

The inner square shape should be affected by the border radius change in the theme.

### What is actually happening?

The inner square shape is not affected by the border radius change in the theme.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 17 |
| System | macOS Monterey 12.5 |
| Browser | Arc |

**Comment by MadCcc** [comment]
The indeterminate square do not have border radius, which is by design.
BTW this round checkbox looks like a radio...
