### ISSUE TITLE
Affix 组件event listener 未被正确移除

### ISSUE THREAD

**Issue by skordyr** [ant-design/ant-design#4755]
#### Environment(required)

- antd version: 2.6.4
- OS and its version: win10
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
1. 父容器使用callback的ref方式获取dom node 通过context 传递给子组件
2. 子组件通过context获取可scroll的dom node 传入Affix组件
3. Affix 组件在componentDidMount中延迟了scroll和resize事件的监听
4. 随后 组件在componentWillRecevieProps中再次监听了事件(此时didMount中的监听没执行，调用clearScrollEventListeners此时并没有达到预期效果),导致最后重复监听了事件
5. 结果Affix unmount 后监听器依然存在(原因不明)，导致react报错:findDOMNode was called on an unmounted component.

#### What do you expected?
期望事件被正确监听一次，Affix unmount后事件正确被移除
尝试在setTargetEventListeners监听事件前调用clearScrollEventListeners，结果符合预期

**Comment by jiangxy** [comment]
我也碰到了这个问题，提供一个测试页面：http://jiangxy.github.io/ant-debug
只要在有affix/无affix两个组件中来回切换几次后再尝试滚动页面，就会出现大量`findDOMNode was called on an unmounted component.`错误日志

不过我传给Affix的target不是通过ref方式获取的，而是直接document.getElement

如果将antd版本换成1.11.0就正常了

**Comment by skordyr** [comment]
你的这个原因也是因为didMount里面监听被延迟导致该监听晚于willReceive里面的监听使得重复监听了，移除的时候只移除了最后一次的，前面的被保留了，后来每次切换监听器的数量在不断增加
