### ISSUE TITLE
使用DirectoryTree时，按住shift连续多选报错

### ISSUE THREAD

**Issue by Dzxwind** [ant-design/ant-design#47552]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ammqlx?file=demo.tsx)

### Steps to reproduce

使用DirectoryTree且multiple = true的时候，当treeData的isLeaf都为true，defaultExpandAll为false，按住shift连续多选会报错

### What is expected?

不再报错

### What is actually happening?

Error in /turbo_modules/antd@4.24.12/lib/tree/utils/dictUtil.js (60:25)
Cannot read properties of undefined (reading 'includes')

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 17.x |
| System | macOS和windows都有 |
| Browser | 最新版chrome |

**Comment by wkmyws** [comment]
这个应该是因为第一层的叶子应该默认是展开状态，但事实上并没有展开导致的，我稍后尝试提个pr
