### ISSUE TITLE
Switch禁用左右箭头控制

### ISSUE THREAD

**Issue by lyndonliu89757** [ant-design/ant-design#47560]
### What problem does this feature solve?

rc-switch 可以通过左右键控制值，见 https://github.com/react-component/switch/blob/master/src/index.tsx
属性 onKeyDown（onInternalKeyDown）

### What does the proposed API look like?

增加prop => disableKeyControl: boolean

**Comment by MadCcc** [comment]
为什么需要禁用键盘呢？
