### ISSUE TITLE
Form in Modal with initialValues

### ISSUE THREAD

**Issue by hello-frontend** [ant-design/ant-design#47573]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/young-haze-ngnpgf?file=%2Findex.js)

### Steps to reproduce

- Click Edit on row A1
- Close
- Click Edit on row B1
- Close
- Click Add

### What is expected?

- Set initialValues when click add or edit table row
- Reset form when close modal

### What is actually happening?

initialValues does not work as expecte

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 121 |

**Comment by crazyair** [comment]
https://zhuanlan.zhihu.com/p/388222294

**Comment by hello-frontend** [comment]
> https://zhuanlan.zhihu.com/p/388222294



> https://zhuanlan.zhihu.com/p/388222294

Can I solve the problem with ant-design without antd-pro-max?

**Comment by crazyair** [comment]
You can learn the source code and handle the mode + form yourself

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/21740#issuecomment-644008703

**Comment by afc163** [comment]
See https://codesandbox.io/p/sandbox/test-forked-4smsn7?file=%2Findex.js%3A52%2C11

**Comment by afc163** [comment]
Put `Form.useForm` inside `<Modal destroyOnClose />` to make sure `destroyOnClose` works as expected.

**Comment by crazyair** [comment]
The use of form + mode more attention points, form needs to add a perfect example of the combination of mode

**Comment by hello-frontend** [comment]
> See https://codesandbox.io/p/sandbox/test-forked-4smsn7?file=%2Findex.js%3A52%2C11

I have ever used it, but i want to submit form when click OK button in modal footer

![Uploading Screenshot 2024-02-24 at 14.09.07.png…]()

**Comment by afc163** [comment]
See https://codesandbox.io/p/sandbox/test-forked-nh555n or

**Comment by afc163** [comment]
Or https://codesandbox.io/p/sandbox/test-forked-6jz8k7?file=%2Findex.js%3A31%2C28

**Comment by crazyair** [comment]
You can take a look at this example https://github.com/ant-design/ant-design/issues/47573
