### ISSUE TITLE
<Input type='number'/>在受控状态下回删错误

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design#4757]
使用antd form（rc form）
比如我输入了`12.2`现在按删除键，理论上应该是`12.`，但实际效果直接显示了`12`，且光标直接跳到了开头位置。

**Comment by Hancoson** [comment]
光标不移出的还不会出现的

**Comment by afc163** [comment]
Reinstall antd and thank you for reporting it!
