### ISSUE TITLE
Homepage title

### ISSUE THREAD

**Issue by Subhahdip** [ant-design/ant-design#47578]
![Screenshot (8)](https://github.com/ant-design/ant-design/assets/87298461/a3b8cd1e-b6b5-449a-b44c-068f1befbe33)
### What problem does this feature solve?

The problem is in the homepage the word "happiness" in the tagline "Help designers/developers building beautiful products more flexible and working with happiness" is not clearly readable due to the text in the background image.

### What does the proposed API look like?

We can make the tagline bigger or bold. Else we can also shift the background image more to the right side.

**Comment by afc163** [comment]
What in my screen is good:

<img width="1453" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/96c0e7c9-50d9-463d-ab10-6a19e897a946">

**Comment by Subhahdip** [comment]
Could this be a browser compatibility issue? Because I have checked in both Microsoft Edge and Google Chrome. In both the cases I face this issue.

**Comment by MadCcc** [comment]
The background of banner will get blurred when mouse is not hover.

**Comment by MadCcc** [comment]
Just a little overlapping, I think that it do not need a fix.
