### ISSUE TITLE
2:nd level menu header is indented

### ISSUE THREAD

**Issue by timlac** [ant-design/ant-design#47571]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/menu-reproduction-p8gcvv?file=%2Fsrc%2FApp.js%3A8%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsytsrc200062v6a3xwpo0vh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsytsrc200022v6a580wx0br%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsytsrc200032v6apn4gs2es%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsytsrc200052v6aymyt34bg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsytsrc200022v6a580wx0br%2522%253A%257B%2522id%2522%253A%2522clsytsrc200022v6a580wx0br%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsytw6ke00022v6abu6wr63u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsytw6ke00022v6abu6wr63u%2522%257D%252C%2522clsytsrc200052v6aymyt34bg%2522%253A%257B%2522id%2522%253A%2522clsytsrc200052v6aymyt34bg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsytsrc200042v6aznczduo9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsytsrc200042v6aznczduo9%2522%257D%252C%2522clsytsrc200032v6apn4gs2es%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsytsrc200032v6apn4gs2es%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

```
import  {  Layout,  Menu  }  from  "antd";
const { Header,  Content } =  Layout;
export  default  function  App()  {

return  (
<div  className="App">
	<Layout  className="FirstMenu">
		<Header>
			<Menu  theme="dark"  mode="horizontal"  defaultSelectedKeys={["1"]}>
				<Menu.Item  key="1">Select 1</Menu.Item>
			</Menu>
		</Header>
		<Content>
			<div  className="site-layout-content">
				<Layout  className="SecondMenu">
					<Header>
						<Menu
						theme="light"
						mode="horizontal"
						defaultSelectedKeys={["1"]}>

							<Menu.Item  key="1">Select 1</Menu.Item>
						</Menu>
					</Header>
					<Content>
						<div  className="site-layout-content"></div>
					</Content>
				</Layout>
			</div>
		</Content>
	</Layout>
</div>
);
}
```

### What is expected?

2nd Level Menu Items header with the same horizontal span as the 1:st one.

### What is actually happening?

The 2:nd Level Menu has a padding of 50px left and right, which looks ugly. I wonder how I can resolve this without changing the css-dev-only-do-not-override-6j9yrn which explicitly states it should not be overrided in it's name. 

![Screenshot from 2024-02-23 17-01-14](https://github.com/ant-design/ant-design/assets/32488097/c285f501-6cad-4eca-aaff-b6f310c510df)

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | Ubuntu |
| Browser | Brave/Chrome |

---
The relevant css looks like this:
```
:where(.css-dev-only-do-not-override-6j9yrn).ant-layout-header
```
```
    height: 64px;
    padding: 0 50px;
    color: rgba(0, 0, 0, 0.88);
    line-height: 64px;
    background: #001529;
```
if the padding is unchecked the issue resolves. But as stated above, I'd like to solve this without overriding the .css-dev-only-do-not-override-6j9yrn. There should be some neat way of doing this.

**Comment by MadCcc** [comment]
`padding` is from header, not 1st Menu or 2nd Menu.
Just override style of header.

**Comment by timlac** [comment]
Thank you, however overriding the padding for the second header I instead get this result:

![Screenshot from 2024-02-26 09-41-23](https://github.com/ant-design/ant-design/assets/32488097/b455950d-5101-45e6-8e1e-2627b78c04ec)

The desired result would be to keep the padding for the menu items the same, but having the color theme extend the full horizontal span of the header...
