### ISSUE TITLE
antd4升级5   穿梭框选择报错

### ISSUE THREAD

**Issue by yhwtest** [ant-design/ant-design#47595]
### Reproduction link

[https://ant.design/components/transfer-cn](https://ant.design/components/transfer-cn)

### Steps to reproduce

穿梭框 升级后 数据都是一样 但是 单选的时候报错  index.js:176 Uncaught TypeError: Cannot read properties of undefined (reading 'disabled')    
      onSelect({ key }, selected) {
          console.log(key,'key');
          console.log(selected,'selected');
          
          onItemSelect(key as string, selected);
        },

### What is expected?

期望单选成功 全选是没有问题

### What is actually happening?

实际的结果是报错  index.js:176 Uncaught TypeError: Cannot read properties of undefined (reading 'disabled')    

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 17 |
| System | mac |
| Browser | 最新 |

---
首先我是用穿梭框建了一些存量的数据 然后我把antd版本升级为5  同样的数据源报错 Cannot read properties of undefined (reading 'disabled')      但是当我用5的穿梭框新建了数据   同样的一模一样的数据 5就可以单选成功 但是存量的数据 单选就会失败

**Comment by Wxh16144** [comment]
帮助我们提供一个复现？

**Comment by yhwtest** [comment]
这个复现成本有点高 单前端似乎无法完成  涉及后端存储   复现路径就是 用4的穿梭框自定义table 存一个数据，然后把4升到5 再单选右侧  就报错了 
![screenshot-20240226-173944](https://github.com/ant-design/ant-design/assets/86184329/029d31a2-5a92-402a-a393-6dbe67190b00)

![screenshot-20240226-173956](https://github.com/ant-design/ant-design/assets/86184329/8e1875a7-bfc2-4442-a57a-cef32a9a8e19)

**Comment by yhwtest** [comment]
但我发现似乎可以用选择组绕过这个问题？虽然不是很规范
![image](https://github.com/ant-design/ant-design/assets/86184329/77d69b7a-17fe-47d4-8d2c-45db799919ea)

**Comment by yhwtest** [comment]
打扰了 可能是我自己的数据源问题

**Comment by yhwtest** [comment]
done

**Comment by yhwtest** [comment]
总结一下  就是我的是table穿梭框  左侧的数据是分页查询的 然后右侧是选中的  当右侧的数据不在左侧 就会报这个错误annot read properties of undefined (reading 'disabled') 所以还是我的数据源的问题 但这个事情在4的时候是不报错的
