### ISSUE TITLE
table组件的滚动条样式，不能被全局的scrollbar伪类样式修改了

### ISSUE THREAD

**Issue by zx-zx22** [ant-design/ant-design#47592]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/confident-panini-forked-ftyqq7?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce

::-webkit-scrollbar {
  width: 8px;
  height: 8px;
  -webkit-appearance: none;
}

::-webkit-scrollbar-track {
  background-color: #e1e6e6;
}

::-webkit-scrollbar-thumb {
  border-radius: 6px;
  background-color: #f7fafa;
}

全局修改了滚动条样式，之前table的滚动条样式也会被响应的修改，现在无法修改

### What is expected?

期望 table组件的滚动条样式可以被全局的scrollbar伪类修改

### What is actually happening?

实际上滚动条样式未被修改，呈现的是浏览器默认的滚动条样式

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome 最新版 |

**Comment by Wxh16144** [comment]
你提供的 codesandbox 地址是无效的，不过我猜测应该是权重不够？试试这样：
<img width="481" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/841e12b4-cafd-497f-a727-1bc5891829d9">

**Comment by zx-zx22** [comment]
奇怪 codesandbox  我可以打开呀  
试了 没效果  !important也没有效果

**Comment by zx-zx22** [comment]
.ant-table-body::-webkit-scrollbar {
  width: 8px !important;
  height: 8px !important;
  -webkit-appearance: none !important;
}

.ant-table-body::-webkit-scrollbar-track {
  background-color: var(--body-background) !important;
}

.ant-table-body::-webkit-scrollbar-thumb {
  border-radius: 6px !important;
  background-color: var(--border-color-base) !important;
}
  这样去修改table的滚动条样式也无效

**Comment by Wxh16144** [comment]
> 奇怪 codesandbox 我可以打开呀 

应该是超限制了默认不会公开

> 这样去修改table的滚动条样式也无效

我看了一下，如果是虚拟表格的话，滚动条不是浏览器的滚动条是虚拟滚动条，要通过样式去覆盖。

**Comment by zx-zx22** [comment]
不是虚拟表格，就是 table的  overflow:auto
没升级antd之前   那个滚动条样式是可以被修改的

**Comment by zx-zx22** [comment]
![image](https://github.com/ant-design/ant-design/assets/62274094/1f68e4fb-3758-4917-9fd4-27ed1474b7ae)
就这个滚动条   5.13.3版本 杨世豪都还可以被全局的  scrollbar伪类样式修改

**Comment by Wxh16144** [comment]
我本地测试没啥问题 mac 14.3 chrome 122 ，你先用 stackblitz 提供一个复现看看～

**Comment by zx-zx22** [comment]
https://codesandbox.io/p/devbox/confident-panini-forked-h87fpd?file=%2Fsrc%2Fstyles.css

**Comment by zx-zx22** [comment]
奇怪 我也搜过scroll  没搜出来这两个属性 是antd的css文件吗

**Comment by SHingCHong** [comment]
> 最近chrome121版本更新后`scrollbar-width`和`scrollbar-color`成为了标准滚动条样式属性，优先级高于伪元素。 <img alt="image" width="333" src="https://private-user-images.githubusercontent.com/97817985/307761049-4ae332fd-4d97-428c-bb04-416480a36b7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjk2MTQsIm5iZiI6MTcwOTAyOTMxNCwicGF0aCI6Ii85NzgxNzk4NS8zMDc3NjEwNDktNGFlMzMyZmQtNGQ5Ny00MjhjLWJiMDQtNDE2NDgwYTM2YjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEwMjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MmQ3NTFlMzc4ZDM3M2VjNTVhNzc1MzA1MDBmYTdjNjczN2U5ZjU3Y2Q2NDQyNjBiNDkzMzI2MDYyY2QyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6sJG2H9JjgM11PWdMddl-sNI-cyffhcm-AjIShFn0s">

原因是因为5.14.2的更新 Table内样式添加了scrollbar-color属性
 [Notice that scrollbarColor will not work with low version chrome and safari.](https://github.com/ant-design/ant-design/pull/47487#issuecomment-1953377927) 
最快的解决方式是降级到5.14.1

**Comment by nova1751** [comment]
> 奇怪 我也搜过scroll 没搜出来这两个属性 是antd的css文件吗

我只是举个例子。和楼上说的一样，目前这两个属性加一个之前的滚动条伪类选择器就废了，目前除了不用这两个属性也没有发现比较好的解决办法。

**Comment by json-q** [comment]
> > 最近chrome121版本更新后`scrollbar-width`和`scrollbar-color`成为了标准滚动条样式属性，优先级高于伪元素。 <img alt="image" width="333" src="https://private-user-images.githubusercontent.com/97817985/307761049-4ae332fd-4d97-428c-bb04-416480a36b7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjk2MTQsIm5iZiI6MTcwOTAyOTMxNCwicGF0aCI6Ii85NzgxNzk4NS8zMDc3NjEwNDktNGFlMzMyZmQtNGQ5Ny00MjhjLWJiMDQtNDE2NDgwYTM2YjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDEwMjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MmQ3NTFlMzc4ZDM3M2VjNTVhNzc1MzA1MDBmYTdjNjczN2U5ZjU3Y2Q2NDQyNjBiNDkzMzI2MDYyY2QyYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6sJG2H9JjgM11PWdMddl-sNI-cyffhcm-AjIShFn0s">
> 
> 原因是因为5.14.2的更新 Table内样式添加了scrollbar-color属性 [Notice that scrollbarColor will not work with low version chrome and safari.](https://github.com/ant-design/ant-design/pull/47487#issuecomment-1953377927) 最快的解决方式是降级到5.14.1

5.14.1 在开启css变量的情况下也会出现该问题，关闭则没问题，更低版本未测试

**Comment by nova1751** [comment]
@MadCcc 我觉得适配暗黑模式可以给所有使用暗黑算法的组件添加这样一个CSS属性来适配暗黑模式的滚动条[`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme)，不过我不太清楚怎样的修改方式比较好，能给点建议吗？

**Comment by zx-zx22** [comment]
* {
  scrollbar-width: auto;
  scrollbar-color: auto;
}    用这个样式去覆盖antd的样式，滚动条就可以继续被伪类修改了

**Comment by fandepeng1993** [comment]
我开始 发现以为是生产环境上有问题，本地开发上没有出现滚动条显示不了。直到我把本地node-module 重新install 后 发现 是antd的版本导致的（5.11.1 --- >5.15.0）。正如楼上所说版本影响
![企业微信截图_17096067611143](https://github.com/ant-design/ant-design/assets/24711462/7cd2f64a-e703-4980-bc86-a2d51b47d0f2)

**Comment by MadCcc** [comment]
> * {
>   scrollbar-width: auto;
>   scrollbar-color: auto;
>   }    用这个样式去覆盖antd的样式，滚动条样式就可以继续被伪类修改了

考虑到 antd 本身也需要对暗黑模式下的滚动条做一些定制化处理，有遇到伪类无法覆盖的可以采用这个解决办法，或者直接使用 `scrollbar-color` 进行覆盖。
这个 Issue 先关闭了。

**Comment by nannan0109** [comment]
> > * {
> >   scrollbar-width: auto;
> >   scrollbar-color: auto;
> >   }    用这个样式去覆盖antd的样式，滚动条样式就可以继续被伪类修改了
> 
> 考虑到 antd 本身也需要对暗黑模式下的滚动条做一些定制化处理，有遇到伪类无法覆盖的可以采用这个解决办法，或者直接使用 `scrollbar-color` 进行覆盖。 这个 Issue 先关闭了，有其他问题可以新开 issue 提出。

我用这个方式去改，没有改成功，表格的滚动条样式还是没有被伪类修改成功

**Comment by huchaolin** [comment]
> * {
>   scrollbar-width: auto;
>   scrollbar-color: auto;
>   }

我用这个方法改成功了 * {
  scrollbar-width: auto;
  scrollbar-color: auto;
}

**Comment by GBcui** [comment]
![image](https://github.com/user-attachments/assets/e2fd1f2c-de45-4697-9671-43e1a14a95e3)
:deep(.ant-table-body) {
  scrollbar-width: auto;
  scrollbar-color: auto;
  &::-webkit-scrollbar {
    width: 8px;
    height: 8px;
  }

  &::-webkit-scrollbar-thumb {
    background-color: rgba(167, 164, 164, 0.8);
    border-radius: 8px;
  }

  &::-webkit-scrollbar-track-piece {
    background-color: rgba(0, 0, 0, 0);
    border-radius: 0;
  }
} 直接复制这样 就可以使用了

**Comment by glzcc** [comment]
> * {
>   scrollbar-width: auto;
>   scrollbar-color: auto;
>   }    用这个样式去覆盖antd的样式，滚动条样式就可以继续被伪类修改了

太帅了，这个问题第一次遇到，在你这找到了解决方案，感谢
