### ISSUE TITLE
Upload: maxCount does not allow removing files, when files.length > maxCount

### ISSUE THREAD

**Issue by komarovalexander** [ant-design/ant-design#47594]
### Reproduction link

https://codesandbox.io/p/sandbox/crop-image-before-uploading-antd-5-14-2-forked-92nrsx

### Steps to reproduce

1) open https://codesandbox.io/p/sandbox/crop-image-before-uploading-antd-5-14-2-forked-92nrsx
2) try to remove image clicking by delete button
3) nothing happened

### What is expected?

image should be removed

### What is actually happening?

click by button does nothing

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome |

---
there is a possibility that server can return more than maxCount images, in that case user should be able to remove them by clicking by delete button

**Comment by huiliangShen** [comment]
can not open your reproduction link, plz set it public.

**Comment by komarovalexander** [comment]
@huiliangShen link updated https://codesandbox.io/p/sandbox/crop-image-before-uploading-antd-5-14-2-forked-92nrsx

**Comment by MadCcc** [comment]
`onChange` should have correct fileList when deleting
