### ISSUE TITLE
Tree has no option for double click

### ISSUE THREAD

**Issue by erikpa1** [ant-design/ant-design#47593]
### What problem does this feature solve?

Now, I have to be very creative when I want double click,...  for onSelect could be added onDoubleSelect

### What does the proposed API look like?

                <Tree
                    onDoubleSelect={(data) => {
                        anyEventEmmiter.emit(`select-${data[0]}`)
                    }}
                />

**Comment by MadCcc** [comment]
TreeNode should support `onClick` and `onDoubleClick`.

**Comment by erikpa1** [comment]
@MadCcc  there is onDoubleClick, but it's double click itself, it don't give you selected node

![image](https://github.com/ant-design/ant-design/assets/19526670/751875aa-b12c-45b4-b4f9-8629806c13bc)

**Comment by ShSher** [comment]
<DirectoryTree
              onDoubleClick={(e: any, node: EventDataNode<DataNode>): void => {
                console.log("onDoubleClick", node);
              }}
            />
