### ISSUE TITLE
antd的table开启虚拟列表,数据量很大的情况下 更改单元格高度滚动滚动会卡顿,

### ISSUE THREAD

**Issue by daidaic** [ant-design/ant-design#47604]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/xu-ni-lie-biao-antd-5-14-1-forked-fg4dk2?file=%2Fdemo.js)

### Steps to reproduce

重现链接可复现

### What is expected?

更改单元格高度后,滚动会不卡顿

### What is actually happening?

更改单元格高度后,滚动会不卡顿

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.0.0 |
| System | windows10 |
| Browser | 122.0.6261.58 |

---
保持为默认高度,滚动会不怎么卡顿,修改高度后卡顿一会儿才开始加载数据

**Comment by zombieJ** [comment]
虚拟滚动是在可见区域做渲染，如果设置 scroll.y 很高，其实就是相当于不在用虚拟滚动。自然就会慢了。
