### ISSUE TITLE
Global CSS Affecting the Element Layout

### ISSUE THREAD

**Issue by LTo666** [ant-design/ant-design#47610]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-y9vgcf?file=%2Findex.js%3A5%2C22)

### Steps to reproduce

Add code in the index.js file:

```
import '../../../node_modules/antd/dist/antd.css'
```

### What is expected?

Layout of a table (not antd component) should be displayed normally after directing to another page.

### What is actually happening?

The below css code affect the layout of a table (not antd component) that the first row of the table is showed half and some text is missing after directing to another page:

```
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 17.0.1 |
| System | Windows 10 Version 22H2 (OS Build 19045.3693) |
| Browser | Microsoft Edge for Business Version 1119.0.2151.97 |

---
You should not add some global css like these to generate the component library which makes the debug on UI harder.

**Comment by zombieJ** [comment]
It's known issue in antd v4 which is removed in v5 (not modify in v4 to avoid break change). Pls try to upgrade to v5 instead.
