### ISSUE TITLE
Button supports toggle

### ISSUE THREAD

**Issue by ericshao** [ant-design/ant-design#4761]
supports on/off toggles with the appearance of a button

#### What do you expected?

Code might be like this:

`<Button toggle/>`

its behavior looks like:
https://material.angular.io/components/component/button-toggle

**Comment by afc163** [comment]
Like this? https://ant.design/components/radio/#components-radio-demo-radiobutton

**Comment by benjycui** [comment]
Or this? https://ant.design/components/tag/#components-tag-demo-hot-tags

**Comment by ericshao** [comment]
yes, like the UncontrolledCheckableTag

**Comment by benjycui** [comment]
So, just use `Tag`.
