### ISSUE TITLE
antd pro完整demo启动成功，但页面空白，控制台看到js有错误

### ISSUE THREAD

**Issue by goeswind** [ant-design/ant-design#47611]
### Reproduction link

[https://gitee.com/yizhan56/antd-pro.git](https://gitee.com/yizhan56/antd-pro.git)

### Steps to reproduce

yarn install
yarn dev

### What is expected?

正常访问pro demo页面

### What is actually happening?

空白

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2.0 |
| System | windows11 |
| Browser | 自带edge |

---
浏览器开发面板控制台报错如下：
Uncaught Error: Absolute route path "/*" nested under path "/user" is not valid. An absolute child route path must start with the combined path of all its parent routes.
本案例源代码已提交至
https://gitee.com/yizhan56/antd-pro.git

**Comment by zombieJ** [comment]
> Uncaught Error: Absolute route path "/*" nested under path "/user" is not valid. An absolute child route path must start with the combined path of all its parent routes.

这个已经告诉你为什么了。

ref https://gitee.com/yizhan56/antd-pro/blob/master/config/routes.ts#L42


### From GPT

这个错误信息表示在使用类似于antd pro或react-router时，你试图创建一个以/*为路径的绝对路由，但是这个路由是嵌套在/user路径下的。在react-router中，子路由的路径需要根据它们的父路由的路径来确定。

假设你在组件内部定义了路由，问题可能出现在嵌套路由的配置上。例如：

```tsx
<Route path="/user" element={<UserLayout />}>
  <Route path="/*" element={<SomeComponent />} />
</Route>
```

在这个例子中，/*试图匹配所有路径，但作为嵌套路由，它必须要与父路由/user的路径相结合。正确的做法是将子路由的路径定义为相对路径，或者确保它们正确地结合了父路由的路径。例如：

```tsx
<Route path="/user" element={<UserLayout />}>
  // 这样子路由会匹配 /user/* 下的所有路径
  <Route path="*" element={<SomeComponent />} /> 
</Route>
```

请检查你的路由配置，并确保子路由的路径是相对于其父路由的路径，或者是在嵌套路由中正确结合了所有父路由的路径。

如果你正在使用react-router v6，需要注意它引入了一些与以前版本不同的路由配置方式。确保你的配置符合你使用的特定版本的react-router的要求。

**Comment by zxhans** [comment]
就是为啥要改这个呢？
