### ISSUE TITLE
Popover onOpenChange 未执行

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47617]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-xyxat1?file=demo.tsx)

### Steps to reproduce

点击 open

### What is expected?

onOpenChange 执行

### What is actually happening?

onOpenChange 未执行

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
符合预期，类比原生 input 组件的 value 和 onChange：https://stackblitz.com/edit/react-xyxat1-dkkeku?file=demo.tsx

**Comment by crazyair** [comment]
> 符合预期，类比原生 input 组件的 value 和 onChange：https://stackblitz.com/edit/react-xyxat1-dkkeku?file=demo.tsx

demo 我修改了下，click 元素放 children 里是会执行的

**Comment by afc163** [comment]
onChange 或者其他 onXxxx 只会由组件本身的行为触发，原生 input 的例子为啥是这样，你可以想一想为什么。
