### ISSUE TITLE
Popover 打开 autoFocus 组件会滚动页面顶部

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47618]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-xyxat1?file=demo.tsx)

### Steps to reproduce

1. 滚动页面到最底部
2. 点击 open

### What is expected?

页面保持不动

### What is actually happening?

页面滚动到最顶部

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
https://github.com/ant-design/ant-design/pull/47664

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/47664 是具体如何解决这个问题的？好像看不到关键改动。

**Comment by crazyair** [comment]
> #47664 是具体如何解决这个问题的？好像看不到关键改动。

demo 修改了，需要用 `preventScroll: true` 关闭聚焦滚动，这个问题没有对 Popover 做修复，具体 @zombieJ 可以看看是否需要改 Popover

**Comment by crazyair** [comment]
https://stackblitz.com/edit/react-exmehu-dy1hu7?file=demo.tsx 

通过添加 `position: 'fixed'` 也可以修复？
