### ISSUE TITLE
rangepicker save on blur still not working

### ISSUE THREAD

**Issue by wunaidage** [ant-design/ant-design#47627]
### Reproduction link

[https://react-cys3wy-skkhxd.stackblitz.io](https://react-cys3wy-skkhxd.stackblitz.io)

### Steps to reproduce

select time in start input, then click end input and select time, click OK but range is not saved.

### What is expected?

blur to save according to https://github.com/react-component/picker/pull/691

### What is actually happening?

still need to click OK button two times to save 

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
I can not open your reproduce. Could you help provider stackblitz IDE url instead?

**Comment by wunaidage** [comment]
https://stackblitz.com/edit/react-cys3wy-skkhxd?file=package.json,demo.tsx

**Comment by zombieJ** [comment]
You should click confirm button to submit. Or use `needConfirm=false` to change on blur.
