### ISSUE TITLE
Modal 设置 flex Select 超过范围

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47623]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-pec9fz?file=demo.tsx)

### Steps to reproduce

查看 demo

### What is expected?

宽度正常

### What is actually happening?

宽度异常

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | latest |
| System | mac |
| Browser | chrome |

---
v4 的时候好像没问题

**Comment by MadCcc** [comment]
https://stackblitz.com/edit/react-pec9fz-gav3pu?file=demo.tsx
