### ISSUE TITLE
Mentions 提及 输入框里如何给@内容单独增加颜色

### ISSUE THREAD

**Issue by Litao21** [ant-design/ant-design#47624]
### What problem does this feature solve?

@内容增加颜色用来区分与文本输入值的区别，很多app回复别人的时候输入框里@的人都是以蓝色呈现的

### What does the proposed API look like?

我期望能增加@内容可以设置颜色

**Comment by MadCcc** [comment]
不太好做，antd 没有做富文本编辑器的计划
