### ISSUE TITLE
Progress 组件关于动态效果造成的显示延迟

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#47626]
### What problem does this feature solve?

Progress 组件，有一个css transition 动态效果，执行需要300毫秒，这个时间挺长的
![image](https://github.com/ant-design/ant-design/assets/29728228/b65341c8-a960-4eaf-9c29-be787d585354)

如果数据变化快速，这样，造成Progress其实显示是不准确的

比如我300毫秒内，数据变化了10次，那么因为这个效果，中间的变化全都无法展示了

现在是采用样式覆盖强制设置none了，希望后面设计的时候能考虑下这种实时性展示组件的延时问题，可以让用户选择关闭动效（不太喜欢采用覆盖的方式去改一些东西）

**Comment by linxianxi** [comment]
```
关闭动画
<ConfigProvider theme={{ token: { motion: false } }}>
      <Progress />
    </ConfigProvider>
```

**Comment by MadCcc** [comment]
目前可以通过上面这种方式关闭动画。

**Comment by zystudios** [comment]
> ```
> // 关闭动画
> 
> <ConfigProvider theme={{ token: { motion: false } }}>
>   <Progress />
> </ConfigProvider>
> ```

感谢，没想到这个配置
