### ISSUE TITLE
Select display value prop if option label is an empty string

### ISSUE THREAD

**Issue by JackWang032** [ant-design/ant-design#47622]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-cys3wy?file=demo.tsx)

<img width="895" alt="image" src="https://github.com/ant-design/ant-design/assets/64318393/f24095c7-0ef5-4f59-8550-d76e0d1376bb">

### Steps to reproduce

options is : `[
      {
        value: '1',
        label: '',
      },
      {
        value: '2',
        label: 'Lucy',
      },
      {
        value: '3',
        label: 'Tom',
      }`

### What is expected?

display ' ', 'Lucy', 'Tom' in dropdown

### What is actually happening?

display '1', 'Lucy', 'Tom' in dropdown

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 18 |
| System | mac |
| Browser | Chrome v116.0.5845.110 |

---
Is this a bug or is it designed like this？

**Comment by afc163** [comment]
It is by designed, option text will fallback to value if label is falsy.
