### ISSUE TITLE
Suggestion: Reverse Slider

### ISSUE THREAD

**Issue by sonovice** [ant-design/ant-design#4763]
It would be nice to be able to have the slider rendered "reversed". This would be useful for selecting lower boundaries:
![reverse](https://cloud.githubusercontent.com/assets/8217108/22622302/333d98fa-eb37-11e6-89ca-e8cc50938917.png)

**Comment by sonovice** [comment]
I posted this on the rc-slider Issue Tracker. Sorry for being at the wrong place here...

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/18708
