### ISSUE TITLE
希望 Select 组件可以通过 ref 获取到更多数据

### ISSUE THREAD

**Issue by Arco1ris** [ant-design/ant-design#47632]
### What problem does this feature solve?

之前 3.x 版本可以通过 ref 获取到 rcSelect，然后通过 rcSelect 可以获取到 clientHeight ，inputValue，以及 setInputValue 等方法
![截屏2024-02-28 下午4 24 20](https://github.com/ant-design/ant-design/assets/10501603/08326bdd-e6e0-4c8b-8939-6282bd7cb46e)
升级到 5.x 版本以后， Select 组件通过 ref 只能拿到 focus blur scrollTo 三个方法
![截屏2024-02-28 下午4 20 31](https://github.com/ant-design/ant-design/assets/10501603/92c6c45a-8aa4-4e97-9c8f-5e4b32f04158)

请问 5.x 版本下可以如何拿到对应的 Select 的比如 clientHeight 的数据？

### What does the proposed API look like?

Select 组件

**Comment by zombieJ** [comment]
ref [官方文档中没有提供的隐藏 API 我可以使用吗？](https://ant.design/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)

你不应该通过 ref 去获取组件内部状态，应该通过受控来管理数据。

**Comment by Arco1ris** [comment]
> ref [官方文档中没有提供的隐藏 API 我可以使用吗？](https://ant.design/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)
> 
> 你不应该通过 ref 去获取组件内部状态，应该 通过受控来管理数据。

抛开升级这件事，刚才提到想要通过 ref 拿到  Select 的一些属性值，比如 clientHeight 的数据，是否可以作为 feature 来支持到呢？
