### ISSUE TITLE
Progress 设置 success 相关配置 不生效

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#47634]
### Reproduction link
https://ant.design/components/progress-cn

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/29728228/b357a534-6c74-4079-9abf-5be48185769e)

![image](https://github.com/ant-design/ant-design/assets/29728228/dca3cb2b-2b56-4b7c-be56-77a69b7e1826)

### What is expected?

成功状态进度条颜色不变

### What is actually happening?

按照设置来改变
 
 
success | 成功进度条相关配置 | { percent: number, strokeColor: string }
 

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

**Comment by MadCcc** [comment]
因为这个不是成功进度条，成功进度条是通过 `successPercent` 控制的，可以这样写：
```tsx
<Progress type="circle" percent={100} strokeColor="#1677ff" />
```
