### ISSUE TITLE
Cascader选项过长时下拉面板定位问题

### ISSUE THREAD

**Issue by Liyw-liyw** [ant-design/ant-design#47635]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-trb7sx?file=demo.tsx)

### Steps to reproduce

1. 给Cascader设置超长的选项label
2. 切换一二级选项，不选择第三级选项
3. 点击其他地方，面板消失
4. 再次点击Cascader，面板出现在输入框右下角

或者直接在几个超长的选项中切换，面板会被定位到右下角

### What is expected?

Cascader默认的placement是bottomLeft（或者直接设置为bottomLeft），无论面板里的选项有多长，默认都应该定位在输入框的左下角

### What is actually happening?

在选项的长度过长时，切换选项会使面板定位到输入框的右下角

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2.0 |
| System | Windows |
| Browser |  Google Chrome 121.0.6167.185（正式版本） |

**Comment by bbb169** [comment]
https://github.com/react-component/trigger/blob/7edea91bc76d083a9767bfb502712dbfebc7b6fa/src/hooks/useAlign.ts#L553  
trigger会缓存上一次flip的位置信息，然后应用到下一次，这个其实算符合预期的 @zombieJ

**Comment by wanpan11** [comment]
我试着 debug了下

**Comment by wanpan11** [comment]
https://github.com/ant-design/ant-design/assets/38714194/f7472f58-3c41-477e-974f-92d3b529386e

**Comment by wanpan11** [comment]
@zombieJ 大佬有空看看这个pr 🙂
https://github.com/react-component/cascader/pull/473
