### ISSUE TITLE
Radio design tokens ignored

### ISSUE THREAD

**Issue by dev4bet** [ant-design/ant-design#47642]
### Reproduction link

[https://codepen.io/dev4bet/pen/bGJbJar?editors=0010](https://codepen.io/dev4bet/pen/bGJbJar?editors=0010)

### Steps to reproduce

Open the pen at https://codepen.io/dev4bet/pen/bGJbJar?editors=0010
You see that `radioSize` affects the size of the radio button, but `buttonSolidCheckedBg` is ignored.

### What is expected?

I expect the color of the radio button (when checked) to change accordingly to `buttonSolidCheckedBg`

### What is actually happening?

The radio button color is always `#1677ff` (the default value, as stated in the documentation).

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

**Comment by MadCcc** [comment]
Use `colorPrimary` to customize checked color of Radio.Button.
`buttonSolidCheckedBg` only works for `buttonStyle="solid"`
