### ISSUE TITLE
Bug: titleMarginTop not applying to Typography.Title

### ISSUE THREAD

**Issue by dshlass** [ant-design/ant-design#47644]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-7pgtjm)

### Steps to reproduce

1. Inspect "Title with no top margin applied"
2. Notice there is no margin-top applied
3. Inspect "Title with top and bottom margin applied" 
4. Notice there is margin-top applied

### What is expected?

Both of the Typography.Title components should have the same margin-top and margin-bottom applied as per the ConfigProvider since it is at the top level

### What is actually happening?

Only the Typography.Title component as a direct child of the ConfigProvider has the correct styling applied

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by MadCcc** [comment]
> Only the Typography.Title component as a direct child of the ConfigProvider has the correct styling applied

That's not right. `titleMarginTop` is applied for Title follows other Typography component.

![image](https://github.com/ant-design/ant-design/assets/27722486/11481f6c-18cc-4624-a129-affc77c038ee)
