### ISSUE TITLE
全屏处理后，Select组件不显示弹出框

### ISSUE THREAD

**Issue by doter1995** [ant-design/ant-design#4764]
#### Environment(required)

- antd version:1.6.5
- OS and its version: win7
- Browser and its version: 火狐 谷歌

非全屏下正常。

在全屏处理后，Select组件不显示弹出框的下拉选项。

全屏处理如下：
```
 if(element.requestFullScreen) {
      element.requestFullScreen();
 }else if(element.mozRequestFullScreen) { //兼容moz
      element.mozRequestFullScreen();
 }else if(element.webkitRequestFullScreen) { //兼容webkit
  element.webkitRequestFullScreen();
 }
```

个人猜测原因：1，全屏后页面置顶，而弹出框置顶层数较低，被覆盖。

**Comment by RaoHai** [comment]
Select 的下拉菜单会默认渲染到 body 上。当你设置了某个元素为全屏的时候，就会被挡住。

你可以在全屏的使用用 Select 的 getPopupContainer，指定菜单的渲染父节点到被设置为全屏的元素上。

包括其他 Popop 的都同理。

**Comment by afc163** [comment]
#3438
