### ISSUE TITLE
Antd slowing next js compilation in dev mode

### ISSUE THREAD

**Issue by DranoelProjects** [ant-design/ant-design#47646]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/DranoelProjects/nextjs-blog/master?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt65cy9x0006356swpid5qcj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt65cy9x0002356s1u1ohyr4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt65cy9x0004356slydwhyhe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt65cy9x0005356snattecxi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt65cy9x0002356s1u1ohyr4%2522%253A%257B%2522id%2522%253A%2522clt65cy9x0002356s1u1ohyr4%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt65cy9x0005356snattecxi%2522%253A%257B%2522id%2522%253A%2522clt65cy9x0005356snattecxi%2522%252C%2522activeTabId%2522%253A%2522clt660q0n002q356sov55l69c%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clt65z6od0003356slbv6d8cz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clt660q0n002q356sov55l69c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt65cy9x0004356slydwhyhe%2522%253A%257B%2522id%2522%253A%2522clt65cy9x0004356slydwhyhe%2522%252C%2522activeTabId%2522%253A%2522clt65g8ou00e5356skkyp57zf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt65cy9x0003356svam24gnt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt65cykd000odjex6bvr9kmx%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Fjavascript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clt65fdpi004j356sjotnbyn4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clt65g8ou00e5356skkyp57zf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clt65mw2000na356sl2va34k2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt65mvsz0010djex4pts5yoi%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Easy to reproduce without codesandebox try this:
- Create the next js blog exemple : npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/main/basics/learn-starter"
- npm run dev
- Do some changes in /pages/index.js and see the refresh compilation time near 500 ms or more but less than 1s.
- stop localhost
- npm i antd
- add transpilePackages below if you get an error like this Cannot use import statement outside a module
- add import { Spin } from 'antd'; and <Spin size="large"/> in /pages/index.js or anything else
- npm run dev
- Do some changes in /pages/index.js and see the refresh compilation time more than 5s
- remove antd just in the /pages/index.js (remove the spin or anything you added and see the refresh time back to 500 ms

### What is expected?

Refresh faster, i'm my project i have time like 60 s to compile the first time, near 20 s to compile another page and more than 10 s just for a refresh.

### What is actually happening?

Taking to much time to compile the project and refresh

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | chrome version 122.0.6261.71 |

---
if you get the error Cannot use import statement outside a module
Try to add in next.config.js : 

module.exports = {
  experimental: {
    optimizePackageImports: ['antd'],
  },
  transpilePackages: [
    "antd",
    "@ant-design/plots",
    "@ant-design/icons",
    "@ant-design/icons-svg",
    "@ant-design/cssinjs",
    "rc-pagination",
    "rc-picker",
    "rc-util",
    "rc-tree",
    "rc-table",
    "rc-tooltip",
  ],
}

Unfortunately, the optimizePackageImports didn't had any effect on my side

**Comment by MadCcc** [comment]
`transpilePackges` means nextjs will compile these packages one more time, and it will slow the speed of start.
Actually I don't think antd makes nextjs slower, nextjs do have some issues on dev performance. They had done some efforts such as `optimizePacakgeImports` for and by default, but it has been removed recently because of misuse of cjs and esm.
