### ISSUE TITLE
Text color token for Text Button's states

### ISSUE THREAD

**Issue by stl-gabriela-alvarez** [ant-design/ant-design#47647]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/ea0276693496bd629774d256e2f65a40b81a6cc4/components/button/style/index.ts](https://github.com/ant-design/ant-design/blob/ea0276693496bd629774d256e2f65a40b81a6cc4/components/button/style/index.ts)

### Steps to reproduce

There isn't a token to change text color of text button for different states (hover & active)

### What is expected?

to be able to change text color

### What is actually happening?

There isn't a token to change text color of text button for different states (hover & active)

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | react 18.2.0 |
| System | Apple M2 Max |
| Browser | 120.0.6099.216 (Official Build) (arm64) |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/47870
