### ISSUE TITLE
DatePicker 显示问题

### ISSUE THREAD

**Issue by toFrankie** [ant-design/ant-design#47665]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/datepicker-reproduction-example-mtc4ny?file=%2Findex.js%3A14%2C7&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt84a8ef00063b6ja29jp9p4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt84a8ee00023b6jyxalypl0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt84a8ee00033b6jp119u3wg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt84a8ef00053b6jo9cz9523%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt84a8ee00023b6jyxalypl0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt84a8ee00013b6jpp750h16%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A7%257D%255D%257D%255D%252C%2522id%2522%253A%2522clt84a8ee00023b6jyxalypl0%2522%252C%2522activeTabId%2522%253A%2522clt84a8ee00013b6jpp750h16%2522%257D%252C%2522clt84a8ef00053b6jo9cz9523%2522%253A%257B%2522id%2522%253A%2522clt84a8ef00053b6jo9cz9523%2522%252C%2522activeTabId%2522%253A%2522clt84iivs002p3b6jpq1myxvm%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clt84iivs002p3b6jpq1myxvm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt84a8ee00033b6jp119u3wg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt84a8ee00033b6jp119u3wg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

关于 DatePicker 组件，问题有二：

1. 启用 multiple 时，未显示 Placeholder
2. 启用 multiple 时，且已选日期换行时，上下没有间隙

<img width="1025" alt="image" src="https://github.com/ant-design/ant-design/assets/26947203/7b4c62bb-4796-4343-9a69-fdd967abd462">

### What is expected?

1. 启用 multiple 时，正常显示 Placeholder
2. 已选日期换行时，上下应有间隙，类似于 `<Select mode="multiple" />` 一样，示例有给出。

### What is actually happening?

1. 启用 multiple 时，未显示 Placeholder
2. 启用 multiple 时，且已选日期换行时，上下没有间隙

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18 |
| System | macOS 14.3.1 |
| Browser | 122.0.6261.94 (arm64) |

**Comment by nova1751** [comment]
Any progress in this issue? @zombieJ

**Comment by Tim022** [comment]
Placeholder still can't be displayed

**Comment by yoyo837** [comment]
> @zombieJ Placeholder still can't be displayed

Another fix. #48387.
