### ISSUE TITLE
水印文字内容过长 页面卡死

### ISSUE THREAD

**Issue by JackShell2020** [ant-design/ant-design#47669]
### Reproduction link

[https://ant-design.antgroup.com/components/watermark-cn#watermark-demo-custom](https://ant-design.antgroup.com/components/watermark-cn#watermark-demo-custom)

### Steps to reproduce

水印内容文字改为大于300个字符串

### What is expected?

流畅处理

### What is actually happening?

卡死

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2 |
| System | mac |
| Browser | chrome |

---
mbp2017@10.15-8g-128g

**Comment by zombieJ** [comment]
看起来正常的：

<img width="721" alt="截屏2024-03-01 17 40 30" src="https://github.com/ant-design/ant-design/assets/5378891/8554a560-744c-436e-8a72-a611dd07b088">

另外，什么场景要这么长的字？
