### ISSUE TITLE
ConfigProvider Causes Uncaught TypeError

### ISSUE THREAD

**Issue by zjda** [ant-design/ant-design#47676]
### Reproduction link

[https://u.ant.design/codesandbox-repro](https://u.ant.design/codesandbox-repro)

### Steps to reproduce

1. npx create-react-app my-app --template typescript (node version:  20.11.0, npm version: 10.4.0)
2. npm install antd --save
3. App.tsx: 
```
const App: React.FC = () => (
  <ConfigProvider theme={{ token: { colorPrimary: '#00b96b' } }}>
    <h1>my content</h1>
  </ConfigProvider>
);
```
4. npm start

### What is expected?

Diplay "my content" in broswer.

### What is actually happening?

Error in console:
Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (react.development.js:1618:1)
    at ConfigProvider (index.js:372:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome and Edge |

**Comment by zjda** [comment]
I believe the problem is caused by CRA.  I upgraded TypeScript to V5 after the app is created by CRA.  Any antd component causes same error.  So we should not use CRA to create antd project.  Next.js works fine with antd, but it gives me many issues with antv (csr vs ssr).  Any suggestion on which framework we should use for antd and andv app?

**Comment by yoyo837** [comment]
I followed the steps but didn't see the issue mentioned. Did i miss something.

**Comment by zjda** [comment]
Thank yoyo837 for looking into the issue.  I tried twice yesterday and got same problem.  However, I could not reproduce it again today.  I will re-open it if I am able to find more information.

Best,
-ZJ
