### ISSUE TITLE
表单中添加 多选 DatePicker日期选择框，下拉框选中日期，不取消焦点，直接点击保存，日期字段值为undefined

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#47671]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-yq3zfc?file=%2Findex.js%3A14%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt8es9000006356kwtw4wn4r%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt8es9000002356kys6e0bot%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt8es9000003356k0shdb9vd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt8es9000005356kpmnuoh4z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt8es9000002356kys6e0bot%2522%253A%257B%2522id%2522%253A%2522clt8es9000002356kys6e0bot%2522%252C%2522activeTabId%2522%253A%2522clt8expcy0002356kh9exylxg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8esz6i004z356kh5uy85uk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clt8expcy0002356kh9exylxg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522index.js%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522endLineNumber%2522%253A14%252C%2522startColumn%2522%253A18%252C%2522endColumn%2522%253A18%257D%255D%252C%2522id%2522%253A%2522clt8eysm70036356kvwvr9j27%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clt8es9000005356kpmnuoh4z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8es9000004356kke3u9o30%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt8es9000005356kpmnuoh4z%2522%252C%2522activeTabId%2522%253A%2522clt8es9000004356kke3u9o30%2522%257D%252C%2522clt8es9000003356k0shdb9vd%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt8es9000003356k0shdb9vd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. 表单中添加 多选 DatePicker日期选择框
2. 下拉框选中日期，不取消焦点
3. 点击保存，日期字段值为undefined

### What is expected?

点击保存，日期字段值为选中的日期

### What is actually happening?

点击保存，日期字段值为undefined

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | "react": "^18.2.0" |
| System | win10 |
| Browser | chrome122 |

**Comment by zombieJ** [comment]
codesandbox 没有设置成公开：
<img width="642" alt="截屏2024-03-01 16 55 14" src="https://github.com/ant-design/ant-design/assets/5378891/d3bde3ec-a51e-47f4-9137-ea125721b163">

**Comment by chengshaohui** [comment]
![image](https://github.com/ant-design/ant-design/assets/20419307/764a1fb5-fad7-4ce7-8dfd-fd20580d8c39)
这是效果图

**Comment by zombieJ** [comment]
新版已修复，closed。
