### ISSUE TITLE
关于select在请求二级菜单时，动态加载并显示二级菜单，可是原先选中的option值被清除了

### ISSUE THREAD

**Issue by 520Yanxiaofei** [ant-design/ant-design#4767]
原理：在选择系统option值，开始请求二级菜单数据并返回，加载二级select菜单。
问题：在返回二级数据成功时，同时选择的option的value清除了，没有选中我原先的值。
解决：在请求二级菜单数据时，能保留原先选中的option值。
个人观点：只要没有请求二级业务功能，其它是没有问题的。
![image](https://cloud.githubusercontent.com/assets/16931900/22640212/9d973f34-ec8c-11e6-9932-68d8bd1e50b2.png)
![image](https://cloud.githubusercontent.com/assets/16931900/22640228/ad7009f4-ec8c-11e6-84ca-c65d7d06f314.png)

**Comment by ddcat1115** [comment]
请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001

Please provide a reproducible demo   http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by 520Yanxiaofei** [comment]
就是onselect调用接口，请求二级菜单
<Select placeholder="请选择系统" onSelect={SelOnchange}>
	{SyeSelect}
 </Select>

代码截图：
![image](https://cloud.githubusercontent.com/assets/16931900/22641243/cef65304-ec90-11e6-8326-7c7a75d24177.png)
代码复制：
import React, {
	Component,
	PropTypes
} from 'react';
import {
	Modal,
	Button,
	Icon,
	Form,
	Input,
	Select,
	Col,
	Row,
	Checkbox,
	message
} from 'antd';

const FormItem = Form.Item;
const Option = Select.Option;


const RuleModal = ({
	RuleModalvisible,
	RuleModalloading,
	CategoryList,
	RuleValidating,
	SysList,
	RuleSysValidating,
	SelOnchange,
	onCancel,
	handForm,
	// processName,
	form: {
		getFieldDecorator,
		validateFields,
		getFieldsValue,
		getFieldError
	},
}) => {
	/*新增白名单*/
	let data = {
		...getFieldsValue()
	};
	//获取数据
	function handleOk() {
		validateFields((errors) => {
			if (errors) {
				return;
			}
			console.log(data)
			handForm(data)
		});
	};
	const formItemLayout = {
		labelCol: {
			span: 5
		},
		wrapperCol: {
			span: 14
		},
	};
	const ModalList = {
		visible: RuleModalvisible,
		confirmLoading: RuleModalloading,
		title: "新增规则",
		okText: "确定",
		cancelText: "取消",
		onOk: handleOk,
		onCancel
	};
	const itemdata = {
		process_name: getFieldsValue().process_name,
		category_id: getFieldsValue().category_id,
		sys_type: getFieldsValue().sys_type,
	}
	const seloption = [{
		name: 'windows',
		typeId: 1
	}, {
		name: 'linux',
		typeId: 2
	}];
	const CategorySelect = CategoryList.map((item, index) => <Option key={index} value={item.category_id}>{item.category_name}</Option>)
	const SyeSelect = seloption.map((item, index) => <Option key={index} value={item.typeId}>{item.name}</Option>)
	return (
		<Modal {...ModalList}>
		    <Form horizontal >
                <FormItem  {...formItemLayout} label='进程' hasFeedback>
               
                  {getFieldDecorator('process_name', {
                   initialValue:itemdata.process_name,
		           rules: [{ required:true, message: '进程不能为空!' },],
		          })(
                  <Input  placeholder="请输入进程名称"/>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='类别' hasFeedback validateStatus={RuleValidating?'validating':null}>
	              {getFieldDecorator('category_id', {
	              initialValue:itemdata.category_id,
		           rules: [
		              { required:true, message: '类别不能为空!' },
		            ],
		          })(
                     <Select placeholder="请选择类别">
				       {CategorySelect}
				    </Select>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='系统' hasFeedback>
	             <Col span="11">
		             <FormItem>
		             {getFieldDecorator('sys_type', {
		              initialValue:itemdata.sys_type,
			           rules: [
			              { required:true, message: '系统不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择系统" onSelect={SelOnchange}>
					       {SyeSelect}
					    </Select>
	                  )}
	                  </FormItem>
                  </Col>
                  <Col span="2"></Col>
                  <Col span="11">
		             <FormItem>
			          {getFieldDecorator('sys_name', {
			           rules: [
			              { required:true, message: '版本不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择版本">
					      <Option value="1" >Microsoft Windows 10.0.14393</Option>
					      <Option value="0" >Microsoft Windows 6.3.9600</Option>
					    </Select>
	                  )} 
                    </FormItem>
                  </Col>
	            </FormItem>
	            <FormItem  {...formItemLayout} label='名称' hasFeedback>
               
                  {getFieldDecorator('process_details', {
		           rules: [{ required:true, message: '名称不能为空!' },],
		          })(
                  <Input  placeholder="请输入名称"/>
                  )}  
	            </FormItem>
	        </Form>
        </Modal>
	)
}



RuleModal.proptypes = {
	// Detaimodal: PropTypes.isRequired,
	// Modalvisible: PropTypes.any,
	// Modalloading: PropTypes.any,
};

export default Form.create({
	mapPropsToFields(props) {
		return {

		}
	}
})(RuleModal)

**Comment by afc163** [comment]
给出最简的可重现在线示例，你这样描述是没有办法帮助到你的。

**Comment by Tobyee** [comment]
@520Yanxiaofei 不是用级联选择组件吗，为啥不用？
https://ant.design/components/cascader-cn/

**Comment by 520Yanxiaofei** [comment]
@Tobyee 我觉得那样会更好看点，按照产品要求去做的，没办法

**Comment by ddcat1115** [comment]
不明白你说的『二级菜单』是啥，版本选择Select的Option也是写死的。。。目前的代码看起来，SyeSelect 并没有返回 <Option ...> 数组，所以Select 下拉列表展示应该是有问题的，你可以看下这块

btw...最好提供在线demo，如果可重现demo实在不方便弄，也请把代码简化一下，格式化好后再提问，别人方便看，你也能尽快得到解答~

**Comment by benjycui** [comment]
[`labelInValue`](https://ant.design/components/select/#components-select-demo-label-in-value) 就是用来处理这种情况的。

**Comment by 520Yanxiaofei** [comment]
就是这个原因，老选不中值
![gif23](https://cloud.githubusercontent.com/assets/16931900/22686192/0ed809f4-ed5e-11e6-982c-dea17e7d6454.gif)

**Comment by 520Yanxiaofei** [comment]
@bang88 @ddcat1115 @afc163

**Comment by 520Yanxiaofei** [comment]
import React, {
	Component,
	PropTypes
} from 'react';
import {
	Modal,
	Button,
	Icon,
	Form,
	Input,
	Select,
	Col,
	Row,
	Checkbox,
	message
} from 'antd';

const FormItem = Form.Item;
const Option = Select.Option;


const RuleModal = ({
	RuleModalvisible,
	RuleModalloading,
	CategoryList,
	RuleValidating,
	SysList,
	RuleSysValidating,
	SelOnchange,
	onCancel,
	handForm,
	handFormUpd,
	ProcessEditData,
	// processName,
	form: {
		getFieldDecorator,
		validateFields,
		getFieldsValue,
		getFieldError
	},
}) => {
	/*新增白名单*/
	let data = {
		...getFieldsValue()
	};
	//获取数据
	function handleOk() {
		validateFields((errors) => {
			if (errors) {
				return;
			}
			if (ProcessEditData == '') {
				handForm(data)
			} else {
				handFormUpd(data, ProcessEditData.id)
			}

		});
	};
	const formItemLayout = {
		labelCol: {
			span: 5
		},
		wrapperCol: {
			span: 14
		},
	};
	const ModalList = {
		visible: RuleModalvisible,
		confirmLoading: RuleModalloading,
		title: ProcessEditData == "" ? "新增规则" : "修改规则",
		okText: ProcessEditData == "" ? "确定" : "确定修改",
		cancelText: "取消",
		onOk: handleOk,
		onCancel
	};
	// ProcessEditData.process_name = getFieldsValue().process_name;
	// ProcessEditData.category_id = getFieldsValue().category_id;
	// ProcessEditData.sys_type = getFieldsValue().sys_type;
	const seloption = [{
		name: 'windows',
		typeId: 1
	}, {
		name: 'linux',
		typeId: 2
	}];
	console.log(SysList)
	const CategorySelect = CategoryList.map((item, index) => <Option key={index} value={item.category_id}>{item.category_name}</Option>)
	const SyeSelect = seloption.map((item, index) => <Option key={index} value={item.typeId}>{item.name}</Option>)
	return (
		<Modal {...ModalList}>
		    <Form horizontal >
                <FormItem  {...formItemLayout} label='进程' hasFeedback>
               
                  {getFieldDecorator('process_name', {
                   initialValue:ProcessEditData.process_name,
		           rules: [{ required:true, message: '进程不能为空!' },],
		          })(
                  <Input  placeholder="请输入进程名称"/>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='类别' hasFeedback validateStatus={RuleValidating?'validating':null}>
	              {getFieldDecorator('category_id', {
	              initialValue:ProcessEditData.category_id,
		           rules: [
		              { required:true, message: '类别不能为空!' },
		            ],
		          })(
                     <Select placeholder="请选择类别">
				       {CategorySelect}
				    </Select>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='系统' hasFeedback >
	             <Col span="11">
		             <FormItem>
		             {getFieldDecorator('sys_type', {
		              initialValue:ProcessEditData.sys_type,
			           rules: [
			              { required:true, message: '系统不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择系统" onSelect={SelOnchange}>
					       {SyeSelect}
					    </Select>
	                  )}
	                  </FormItem>
                  </Col>
                  <Col span="2"></Col>
                  <Col span="11">
		             <FormItem>
			          {getFieldDecorator('sys_name', {
			          	initialValue:ProcessEditData.sys_name,
			           rules: [
			              { required:true, message: '版本不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择版本">
					      <Option value="Microsoft Windows 10.0.14393" >Microsoft Windows 10.0.14393</Option>
					      <Option value="Microsoft Windows 6.3.9600" >Microsoft Windows 6.3.9600</Option>
					    </Select>
	                  )} 
                    </FormItem>
                  </Col>
	            </FormItem>
	            <FormItem  {...formItemLayout} label='名称' hasFeedback>
                  {getFieldDecorator('process_details', {
	                  initialValue:ProcessEditData.process_details,
			           rules: [{ required:true, message: '名称不能为空!' },],
			          })(
	                  <Input  placeholder="请输入名称"/>
                  )}  
	            </FormItem>
	        </Form>
        </Modal>
	)
}



RuleModal.proptypes = {
	// Detaimodal: PropTypes.isRequired,
	// Modalvisible: PropTypes.any,
	// Modalloading: PropTypes.any,
};

export default Form.create({
	mapPropsToFields(props) {
		return {

		}
	}
})(RuleModal)

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by 520Yanxiaofei** [comment]
import React, {
	Component,
	PropTypes
} from 'react';
import {
	Modal,
	Button,
	Icon,
	Form,
	Input,
	Select,
	Col,
	Row,
	Checkbox,
	message
} from 'antd';

const FormItem = Form.Item;
const Option = Select.Option;


const RuleModal = ({
	RuleModalvisible,
	RuleModalloading,
	CategoryList,
	RuleValidating,
	SysList,
	RuleSysValidating,
	SelOnchange,
	onCancel,
	handForm,
	handFormUpd,
	ProcessEditData,
	// processName,
	form: {
		getFieldDecorator,
		validateFields,
		getFieldsValue,
		getFieldError
	},
}) => {
	/*新增白名单*/
	let data = {
		...getFieldsValue()
	};
	//获取数据
	function handleOk() {
		validateFields((errors) => {
			if (errors) {
				return;
			}
			if (ProcessEditData == '') {
				handForm(data)
			} else {
				handFormUpd(data, ProcessEditData.id)
			}

		});
	};
	const formItemLayout = {
		labelCol: {
			span: 5
		},
		wrapperCol: {
			span: 14
		},
	};
	const ModalList = {
		visible: RuleModalvisible,
		confirmLoading: RuleModalloading,
		title: ProcessEditData == "" ? "新增规则" : "修改规则",
		okText: ProcessEditData == "" ? "确定" : "确定修改",
		cancelText: "取消",
		onOk: handleOk,
		onCancel
	};
	// ProcessEditData.process_name = getFieldsValue().process_name;
	// ProcessEditData.category_id = getFieldsValue().category_id;
	// ProcessEditData.sys_type = getFieldsValue().sys_type;
	const seloption = [{
		name: 'windows',
		typeId: 1
	}, {
		name: 'linux',
		typeId: 2
	}];
	console.log(SysList)
	const CategorySelect = CategoryList.map((item, index) => <Option key={index} value={item.category_id}>{item.category_name}</Option>)
	const SyeSelect = seloption.map((item, index) => <Option key={index} value={item.typeId}>{item.name}</Option>)
	return (
		<Modal {...ModalList}>
		    <Form horizontal >
                <FormItem  {...formItemLayout} label='进程' hasFeedback>
               
                  {getFieldDecorator('process_name', {
                   initialValue:ProcessEditData.process_name,
		           rules: [{ required:true, message: '进程不能为空!' },],
		          })(
                  <Input  placeholder="请输入进程名称"/>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='类别' hasFeedback validateStatus={RuleValidating?'validating':null}>
	              {getFieldDecorator('category_id', {
	              initialValue:ProcessEditData.category_id,
		           rules: [
		              { required:true, message: '类别不能为空!' },
		            ],
		          })(
                     <Select placeholder="请选择类别">
				       {CategorySelect}
				    </Select>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='系统' hasFeedback >
	             <Col span="11">
		             <FormItem>
		             {getFieldDecorator('sys_type', {
		              initialValue:ProcessEditData.sys_type,
			           rules: [
			              { required:true, message: '系统不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择系统" onSelect={SelOnchange}>
					       {SyeSelect}
					    </Select>
	                  )}
	                  </FormItem>
                  </Col>
                  <Col span="2"></Col>
                  <Col span="11">
		             <FormItem>
			          {getFieldDecorator('sys_name', {
			          	initialValue:ProcessEditData.sys_name,
			           rules: [
			              { required:true, message: '版本不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择版本">
					      <Option value="Microsoft Windows 10.0.14393" >Microsoft Windows 10.0.14393</Option>
					      <Option value="Microsoft Windows 6.3.9600" >Microsoft Windows 6.3.9600</Option>
					    </Select>
	                  )} 
                    </FormItem>
                  </Col>
	            </FormItem>
	            <FormItem  {...formItemLayout} label='名称' hasFeedback>
                  {getFieldDecorator('process_details', {
	                  initialValue:ProcessEditData.process_details,
			           rules: [{ required:true, message: '名称不能为空!' },],
			          })(
	                  <Input  placeholder="请输入名称"/>
                  )}  
	            </FormItem>
	        </Form>
        </Modal>
	)
}



RuleModal.proptypes = {
	// Detaimodal: PropTypes.isRequired,
	// Modalvisible: PropTypes.any,
	// Modalloading: PropTypes.any,
};

export default Form.create({
	mapPropsToFields(props) {
		return {

		}
	}
})(RuleModal)

**Comment by 520Yanxiaofei** [comment]
Component,
PropTypes

**Comment by 520Yanxiaofei** [comment]
import React, {
Component,
PropTypes
} from 'react';import {
Modal,
Button,
Icon,
Form,
Input,
Select,
Col,
Row,
Checkbox,
message
} from 'antd';
const FormItem = Form.Item;const Option = Select.Option;
const RuleModal = ({
RuleModalvisible,
RuleModalloading,
CategoryList,
RuleValidating,
SysList,
RuleSysValidating,
SelOnchange,
onCancel,
handForm,
handFormUpd,
ProcessEditData,
// processName,
form: {
    getFieldDecorator,
    validateFields,
    getFieldsValue,
    getFieldError
},
}) => {
/*新增白名单*/
let data = {
    ...getFieldsValue()
};
//获取数据
function handleOk() {
    validateFields((errors) => {
        if (errors) {
            return;
        }
        if (ProcessEditData == '') {
            handForm(data)
        } else {
            handFormUpd(data, ProcessEditData.id)
        }

    });
};
const formItemLayout = {
    labelCol: {
        span: 5
    },
    wrapperCol: {
        span: 14
    },
};
const ModalList = {
    visible: RuleModalvisible,
    confirmLoading: RuleModalloading,
    title: ProcessEditData == "" ? "新增规则" : "修改规则",
    okText: ProcessEditData == "" ? "确定" : "确定修改",
    cancelText: "取消",
    onOk: handleOk,
    onCancel
};
// ProcessEditData.process_name = getFieldsValue().process_name;
// ProcessEditData.category_id = getFieldsValue().category_id;
// ProcessEditData.sys_type = getFieldsValue().sys_type;
const seloption = [{
    name: 'windows',
    typeId: 1
}, {
    name: 'linux',
    typeId: 2
}];
console.log(SysList)
const CategorySelect = CategoryList.map((item, index) => <Option key={index} value={item.category_id}>{item.category_name}</Option>)
const SyeSelect = seloption.map((item, index) => <Option key={index} value={item.typeId}>{item.name}</Option>)
return (
    <Modal {...ModalList}>
        <Form horizontal >
            <FormItem  {...formItemLayout} label='进程' hasFeedback>
           
              {getFieldDecorator('process_name', {
               initialValue:ProcessEditData.process_name,
               rules: [{ required:true, message: '进程不能为空!' },],
              })(
              <Input  placeholder="请输入进程名称"/>
              )}
            </FormItem>
             <FormItem  {...formItemLayout} label='类别' hasFeedback validateStatus={RuleValidating?'validating':null}>
              {getFieldDecorator('category_id', {
              initialValue:ProcessEditData.category_id,
               rules: [
                  { required:true, message: '类别不能为空!' },
                ],
              })(
                 <Select placeholder="请选择类别">
                   {CategorySelect}
                </Select>
              )}
            </FormItem>
             <FormItem  {...formItemLayout} label='系统' hasFeedback >
             <Col span="11">
                 <FormItem>
                 {getFieldDecorator('sys_type', {
                  initialValue:ProcessEditData.sys_type,
                   rules: [
                      { required:true, message: '系统不能为空!' },
                    ],
                  })(
                     <Select placeholder="请选择系统" onSelect={SelOnchange}>
                       {SyeSelect}
                    </Select>
                  )}
                  </FormItem>
              </Col>
              <Col span="2"></Col>
              <Col span="11">
                 <FormItem>
                  {getFieldDecorator('sys_name', {
                      initialValue:ProcessEditData.sys_name,
                   rules: [
                      { required:true, message: '版本不能为空!' },
                    ],
                  })(
                     <Select placeholder="请选择版本">
                      <Option value="Microsoft Windows 10.0.14393" >Microsoft Windows 10.0.14393</Option>
                      <Option value="Microsoft Windows 6.3.9600" >Microsoft Windows 6.3.9600</Option>
                    </Select>
                  )} 
                </FormItem>
              </Col>
            </FormItem>
            <FormItem  {...formItemLayout} label='名称' hasFeedback>
              {getFieldDecorator('process_details', {
                  initialValue:ProcessEditData.process_details,
                   rules: [{ required:true, message: '名称不能为空!' },],
                  })(
                  <Input  placeholder="请输入名称"/>
              )}  
            </FormItem>
        </Form>
    </Modal>
)
}
RuleModal.proptypes = {
// Detaimodal: PropTypes.isRequired,
// Modalvisible: PropTypes.any,
// Modalloading: PropTypes.any,
};
export default Form.create({
mapPropsToFields(props) {
    return {

    }
}
})(RuleModal)

**Comment by 520Yanxiaofei** [comment]
/*新增白名单*/
let data = {
    ...getFieldsValue()
};
//获取数据
function handleOk() {
    validateFields((errors) => {
        if (errors) {
            return;
        }
        if (ProcessEditData == '') {
            handForm(data)
        } else {
            handFormUpd(data, ProcessEditData.id)
        }

    });
};
const formItemLayout = {
    labelCol: {
        span: 5
    },
    wrapperCol: {
        span: 14
    },
};
const ModalList = {
    visible: RuleModalvisible,
    confirmLoading: RuleModalloading,
    title: ProcessEditData == "" ? "新增规则" : "修改规则",
    okText: ProcessEditData == "" ? "确定" : "确定修改",
    cancelText: "取消",
    onOk: handleOk,
    onCancel
};
// ProcessEditData.process_name = getFieldsValue().process_name;
// ProcessEditData.category_id = getFieldsValue().category_id;
// ProcessEditData.sys_type = getFieldsValue().sys_type;
const seloption = [{
    name: 'windows',
    typeId: 1
}, {
    name: 'linux',
    typeId: 2
}];
console.log(SysList)
const CategorySelect = CategoryList.map((item, index) => <Option key={index} value={item.category_id}>{item.category_name}</Option>)
const SyeSelect = seloption.map((item, index) => <Option key={index} value={item.typeId}>{item.name}</Option>)
return (
    <Modal {...ModalList}>
        <Form horizontal >
            <FormItem  {...formItemLayout} label='进程' hasFeedback>
           
              {getFieldDecorator('process_name', {
               initialValue:ProcessEditData.process_name,
               rules: [{ required:true, message: '进程不能为空!' },],
              })(
              <Input  placeholder="请输入进程名称"/>
              )}
            </FormItem>
             <FormItem  {...formItemLayout} label='类别' hasFeedback validateStatus={RuleValidating?'validating':null}>
              {getFieldDecorator('category_id', {
              initialValue:ProcessEditData.category_id,
               rules: [
                  { required:true, message: '类别不能为空!' },
                ],
              })(
                 <Select placeholder="请选择类别">
                   {CategorySelect}
                </Select>
              )}
            </FormItem>
             <FormItem  {...formItemLayout} label='系统' hasFeedback >
             <Col span="11">
                 <FormItem>
                 {getFieldDecorator('sys_type', {
                  initialValue:ProcessEditData.sys_type,
                   rules: [
                      { required:true, message: '系统不能为空!' },
                    ],
                  })(
                     <Select placeholder="请选择系统" onSelect={SelOnchange}>
                       {SyeSelect}
                    </Select>
                  )}
                  </FormItem>
              </Col>
              <Col span="2"></Col>
              <Col span="11">
                 <FormItem>
                  {getFieldDecorator('sys_name', {
                      initialValue:ProcessEditData.sys_name,
                   rules: [
                      { required:true, message: '版本不能为空!' },
                    ],
                  })(
                     <Select placeholder="请选择版本">
                      <Option value="Microsoft Windows 10.0.14393" >Microsoft Windows 10.0.14393</Option>
                      <Option value="Microsoft Windows 6.3.9600" >Microsoft Windows 6.3.9600</Option>
                    </Select>
                  )} 
</FormItem>
             </Col>
           </FormItem>
           <FormItem  {...formItemLayout} label='名称' hasFeedback>
             {getFieldDecorator('process_details', {
                 initialValue:ProcessEditData.process_details,
                  rules: [{ required:true, message: '名称不能为空!' },],
                 })(
                 <Input  placeholder="请输入名称"/>
             )}  
           </FormItem>
       </Form>
   </Modal>
)

**Comment by 520Yanxiaofei** [comment]
{
import React, {
	Component,
	PropTypes
} from 'react';
import {
	Modal,
	Button,
	Icon,
	Form,
	Input,
	Select,
	Col,
	Row,
	Checkbox,
	message
} from 'antd';

const FormItem = Form.Item;
const Option = Select.Option;


const RuleModal = ({
	RuleModalvisible,
	RuleModalloading,
	CategoryList,
	RuleValidating,
	SysList,
	RuleSysValidating,
	SelOnchange,
	onCancel,
	handForm,
	handFormUpd,
	ProcessEditData,
	// processName,
	form: {
		getFieldDecorator,
		validateFields,
		getFieldsValue,
		getFieldError
	},
}) => {
	/*新增白名单*/
	let data = {
		...getFieldsValue()
	};
	//获取数据
	function handleOk() {
		validateFields((errors) => {
			if (errors) {
				return;
			}
			if (ProcessEditData == '') {
				handForm(data)
			} else {
				handFormUpd(data, ProcessEditData.id)
			}

		});
	};
	const formItemLayout = {
		labelCol: {
			span: 5
		},
		wrapperCol: {
			span: 14
		},
	};
	const ModalList = {
		visible: RuleModalvisible,
		confirmLoading: RuleModalloading,
		title: ProcessEditData == "" ? "新增规则" : "修改规则",
		okText: ProcessEditData == "" ? "确定" : "确定修改",
		cancelText: "取消",
		onOk: handleOk,
		onCancel
	};
	// ProcessEditData.process_name = getFieldsValue().process_name;
	// ProcessEditData.category_id = getFieldsValue().category_id;
	// ProcessEditData.sys_type = getFieldsValue().sys_type;
	const seloption = [{
		name: 'windows',
		typeId: 1
	}, {
		name: 'linux',
		typeId: 2
	}];
	console.log(SysList)
	const CategorySelect = CategoryList.map((item, index) => <Option key={index} value={item.category_id}>{item.category_name}</Option>)
	const SyeSelect = seloption.map((item, index) => <Option key={index} value={item.typeId}>{item.name}</Option>)
	return (
		<Modal {...ModalList}>
		    <Form horizontal >
                <FormItem  {...formItemLayout} label='进程' hasFeedback>
               
                  {getFieldDecorator('process_name', {
                   initialValue:ProcessEditData.process_name,
		           rules: [{ required:true, message: '进程不能为空!' },],
		          })(
                  <Input  placeholder="请输入进程名称"/>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='类别' hasFeedback validateStatus={RuleValidating?'validating':null}>
	              {getFieldDecorator('category_id', {
	              initialValue:ProcessEditData.category_id,
		           rules: [
		              { required:true, message: '类别不能为空!' },
		            ],
		          })(
                     <Select placeholder="请选择类别">
				       {CategorySelect}
				    </Select>
                  )}
	            </FormItem>
	             <FormItem  {...formItemLayout} label='系统' hasFeedback >
	             <Col span="11">
		             <FormItem>
		             {getFieldDecorator('sys_type', {
		              initialValue:ProcessEditData.sys_type,
			           rules: [
			              { required:true, message: '系统不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择系统" onSelect={SelOnchange}>
					       {SyeSelect}
					    </Select>
	                  )}
	                  </FormItem>
                  </Col>
                  <Col span="2"></Col>
                  <Col span="11">
		             <FormItem>
			          {getFieldDecorator('sys_name', {
			          	initialValue:ProcessEditData.sys_name,
			           rules: [
			              { required:true, message: '版本不能为空!' },
			            ],
			          })(
	                     <Select placeholder="请选择版本">
					      <Option value="Microsoft Windows 10.0.14393" >Microsoft Windows 10.0.14393</Option>
					      <Option value="Microsoft Windows 6.3.9600" >Microsoft Windows 6.3.9600</Option>
					    </Select>
	                  )} 
                    </FormItem>
                  </Col>
	            </FormItem>
	            <FormItem  {...formItemLayout} label='名称' hasFeedback>
                  {getFieldDecorator('process_details', {
	                  initialValue:ProcessEditData.process_details,
			           rules: [{ required:true, message: '名称不能为空!' },],
			          })(
	                  <Input  placeholder="请输入名称"/>
                  )}  
	            </FormItem>
	        </Form>
        </Modal>
	)
}



RuleModal.proptypes = {
	// Detaimodal: PropTypes.isRequired,
	// Modalvisible: PropTypes.any,
	// Modalloading: PropTypes.any,
};

export default Form.create({
	mapPropsToFields(props) {
		return {

		}
	}
})(RuleModal)
}

**Comment by benjycui** [comment]
还是不懂你的问题。

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
labelInValue
