### ISSUE TITLE
Typography Title doesn't have a color property to assign text color.

### ISSUE THREAD

**Issue by SharmaTushar1** [ant-design/ant-design#47685]
### What problem does this feature solve?

Makes it easier to change the color instead of disabling the Title using !important or force css color which makes the app misbehave at times.

### What does the proposed API look like?

<Title color = "white"> This title is White </Title>

// makes the title white

**Comment by SharmaTushar1** [comment]
Currently we have to explicitly use a css which works like this

```tsx
<Typography.Title style={{ color: 'white' }} >
  This is a white title
</Typography.Title>
```

Proposed feature will simplify this process to just
```tsx
<Typography.Title color = "white">
  This is a white Title
</Typography.Title>
```

**Comment by afc163** [comment]
```
<Typography.Title style={{ color: 'white' }} />
```

We believe `style.color` is enough in this situation.
