### ISSUE TITLE
table rowKey 函数使用index会导致表格非第一页多选无法选中

### ISSUE THREAD

**Issue by rawbin-** [ant-design/ant-design#47684]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-v6ufny?file=demo.tsx)

### Steps to reproduce

1、打开页面，可以尝试在第一页勾选某些数据
2、切换到第二页，再次勾选某些数据，发现无法勾选上

antd 4.17.1 和后面的几个版本都能复现，5.x demo里面的版本也能复现

<img width="1728" alt="image" src="https://github.com/ant-design/ant-design/assets/8169783/32937b4c-2cf8-4fc9-855c-b5ef5427c9ba">

### What is expected?

希望每一页的数据都能正常勾选并合并

### What is actually happening?

只有第一页的数据可以勾选上

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2 |
| System | masOS Monterey 12.1 |
| Browser | Chrome 最新 |

**Comment by afc163** [comment]
不要依赖 index 作为 rowKey，需要保证数据本身具备唯一的 key。

**Comment by rawbin-** [comment]
@afc163 这个我们是不是可以加到文档说明里面

**Comment by afc163** [comment]
可以，欢迎来个 PR~

**Comment by afc163** [comment]
可以补充到 https://ant.design/components/table-cn#%E6%B3%A8%E6%84%8F
