### ISSUE TITLE
[Drawer] antd 5.10.2升级至5.14.2后，FormDrawer footer和extra不生效，页面未渲染

### ISSUE THREAD

**Issue by lk0606** [ant-design/ant-design#47692]
### Reproduction link

旧版正常渲染：[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ecstatic-wildflower-6v8q7z?file=%2FApp.tsx%3A55%2C23)
新版demo中直接报错：[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/infallible-goodall-fs7g4s?file=%2FApp.tsx%3A87%2C6)
项目中是未渲染：
![a4823fbe-1ced-48e2-a5ca-8971a8bae250](https://github.com/ant-design/ant-design/assets/43233310/cf023127-73c6-4283-b444-bc42b215a9fb)
![715fe836-ef7e-464f-91f7-6a84fc5293ce](https://github.com/ant-design/ant-design/assets/43233310/3a306e5a-562d-484b-8639-01f64da67dcd)

### Steps to reproduce

点击打开抽屉，底部或顶部按钮未渲染

### What is expected?

期望升级后，FormDrawer.Footer FormDrawer.Extra正常渲染

### What is actually happening?

FormDrawer.Footer FormDrawer.Extra未渲染

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 16-18均无差别 |
| System | 无关系统版本 |
| Browser | 无关浏览器 |

**Comment by zombieJ** [comment]
你的 codesandbox 没有设置 public 看不到哈~

**Comment by lk0606** [comment]
@zombieJ  已设置为public，再看下是否可以~

**Comment by afc163** [comment]
看上去是 @formily/antd-v5 的问题？或者能否提供一个只包含 antd 的重现？

**Comment by lk0606** [comment]
> 看上去是 @formily/antd-v5 的问题？或者能否提供一个只包含 antd 的重现？

应该不是formily/antd-v5的问题，因为antd不升级没问题，升级后有问题。
中间的版本是否对drawer有代码改动，FormDialog是没问题的

**Comment by afc163** [comment]
能否还原到 antd 本身的 Drawer 代码，才好排除其他代码的影响，重现问题本身。

**Comment by lk0606** [comment]
> 能否还原到 antd 本身的 Drawer 代码，才好排除其他代码的影响，重现问题本身。

我这里一开始就没有使用antd本身drawer，直接使用的formily/antd-v5。
我看过他们的源码和更新日志，这里并没有做改动

**Comment by afc163** [comment]
建议先提到 formily，才好排除是否是 antd 本身的问题。可能是 antd 本身的问题，也可能 formily 是上不合适的样式覆盖或者内部方法调用造成的问题。目前我们在 Drawer 文档和测试用例中还没有发现不符合预期的情况发生：https://ant.design/components/drawer-cn

**Comment by lk0606** [comment]
问题初步排查到了，是antd改了html css结构导致，看下是谁来修？ @afc163 
老版本antd class为：ant-drawer-wrapper-body
新版本 antd class为：ant-drawer-content
![image](https://github.com/ant-design/ant-design/assets/43233310/704cc6fa-7931-457e-9a30-2dcafd557524)
![image](https://github.com/ant-design/ant-design/assets/43233310/8b70614f-7a43-49d4-8795-8a427234e08b)
![image](https://github.com/ant-design/ant-design/assets/43233310/04bcfb59-ddd4-44df-bf56-ec7f5de9da2d)

footer也是一样的道理。

**Comment by yoyo837** [comment]
应该下游适配上来吧？

**Comment by lk0606** [comment]
> 应该下游适配上来吧？

class改动算不算break change? 而且如果上游哪天又改了呢？
下游适配，关键下游社区好像不活跃呀

**Comment by afc163** [comment]
业务实现不应该依赖 antd 组件内部的 dom 结构，这些有可能是会随着迭代进行变化的，我们在官方 demo 中也未推荐过相关的写法。官方写法的 break change 我们一定会修的。

**Comment by lk0606** [comment]
算了，下游formily不知道何年月才能修复发版，业务代码暂时hack处理好了。
```js
classNames: {
  content: 'ant-drawer-wrapper-body'
}
```
