### ISSUE TITLE
RangePicker. 'ant-picker-range-arrow' not shown when passing prop 'placement=bottomRight'

### ISSUE THREAD

**Issue by a-crv** [ant-design/ant-design#47699]
### Reproduction link

[https://ant.design/components/date-picker](https://ant.design/components/date-picker)

### Steps to reproduce

Import <DatePicker.RangePicker />. Set 'bottomRight' placement.

### What is expected?

See the arrow

### What is actually happening?

There isn't arrow

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

---
You can see this on https://ant.design/components/date-picker at placement section

**Comment by a-crv** [comment]
<img width="809" alt="Снимок экрана 2024-03-04 в 13 45 13" src="https://github.com/ant-design/ant-design/assets/7212339/906a3cab-eec1-4883-b298-bb87ea344316">

**Comment by bombillazo** [comment]
any update?

**Comment by a-crv** [comment]
no, just issue was closed)))

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/pull/49333
