### ISSUE TITLE
Handle responsive use cases for all types of datepickers

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#47691]
### What problem does this feature solve?

It ll make datepickers more useable in a mobile view.

### What does the proposed API look like?

Have a new props called modal={true} which will open the datepicker in a modal

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/26758

**Comment by AsuraKev** [comment]
@afc163   It is indeed a duplicate. But there’s no formal fix for this tho. The Datepicker RFC was suppose to address this one from last time what they said
