### ISSUE TITLE
使用legacyLogicalPropertiesTransformer后.ant-menu-xx的padding错误

### ISSUE THREAD

**Issue by jackple** [ant-design/ant-design#47707]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/zi-ding-yi-chu-fa-qi-antd-5-14-1-forked-84pm2m?file=%2Fdemo.tsx%3A34%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltdn8gac00063b6i1t5cg8gw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltdn8gac00023b6iomyx05fi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltdn8gac00033b6ikp4c40h8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltdn8gac00053b6i8sclaonr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltdn8gac00023b6iomyx05fi%2522%253A%257B%2522id%2522%253A%2522cltdn8gac00023b6iomyx05fi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltdt61sf00023b6m6xkydhsy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A34%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A34%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltdt61sf00023b6m6xkydhsy%2522%257D%252C%2522cltdn8gac00053b6i8sclaonr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltdn8gac00043b6ikbxpt0oe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltdn8gac00053b6i8sclaonr%2522%252C%2522activeTabId%2522%253A%2522cltdn8gac00043b6ikbxpt0oe%2522%257D%252C%2522cltdn8gac00033b6ikp4c40h8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltdn8gac00033b6ikp4c40h8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

demo打开即可看到

### What is expected?

padding正常

### What is actually happening?

padding计算错误导致样式错乱

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome v121 |

**Comment by Wxh16144** [comment]
应该和 https://github.com/ant-design/ant-design/issues/47652 是一类问题，下班看看cssinjs 那边的 transformer 逻辑
