### ISSUE TITLE
(Proposoal) several more button types

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#4770]
The button types provided by other frameworks, such as [bootstrap](http://getbootstrap.com/css/#buttons) are a bit more extensive than those offered by antd at the moment which currently includes

- primary
- dashed
- ghost
- danger

I would like to see the following types added

- warning (yellow)
- primary (blue)
- success (green)

**Comment by ddcat1115** [comment]
What's the difference between the above primary button and the below(the one you expect)?

**Comment by megawac** [comment]
Sorry, updated the ticket to clarify. I meant adding a new type for success or similar which would be a mid blue button as the primary buttons are currently green

**Comment by afc163** [comment]
Sorry, we follow Ant Design specification which don't contain success button and warning button. You can customize your own button types by HOC way.

**Comment by gemilangpermata** [comment]
@afc163 can't you please show me how to do it?

**Comment by gemilangpermata** [comment]
@afc163 can you please show me how to do it?

**Comment by silkyland** [comment]
@gemilangpermata  put these in to your custom.css file 
`.bg-primary {
  background-color: #4190F7;
}

.bg-success {
  background-color: #70C040;
}

.bg-warning {
  background-color: #EFAF41;
}

.bg-danger {
  background-color: #E23C39;
}`

**Comment by hamid07ss** [comment]
I guess that using this CSS style is not right!
and it's better if you can create a less loop function for creating Button types and get the list of Buttons from a Less array, then we can create a button type with only a name and color!

something like this:
```
@buttons: primary blue, danger red;

.createbuttons(@iterator:1) when(@iterator <= length(@buttons)) {
    @name: extract(extract(@buttons, @iterator),1);
    @color: extract(extract(@buttons, @iterator),2);
    .cl-@{name} {
        background-color: @{color}
        color: darken(@color, 10%)
    }
    .createbuttons(@iterator + 1);
}
.createbuttons();
```

after this, we can create a `success` button type by overwriting `@buttons` variable like this:
```
@buttons: primary blue, danger red, success green;
```

**Comment by IonelLupu** [comment]
@afc163 where can we propose the "more button types" feature? Is there a repo for the Ant Design specification?

**Comment by herudi** [comment]
> @afc163 where can we propose the "more button types" feature? Is there a repo for the Ant Design specification?

use css only => https://gist.github.com/herudi/4c608737ae0816c45ba0c3b185556acf

**Comment by IonelLupu** [comment]
@herudi yes, I did that. But it would've been nice to have them built in ng-zorro

**Comment by nutjaa** [comment]
@IonelLupu  Can u guide me proper way to fixed typescript error after implement css above 
~~~
Type '"success"' is not assignable to type '"text" | "link" | "ghost" | "primary" | "default" | "dashed"'.
~~~

**Comment by IonelLupu** [comment]
@nutjaa "success" doesn't exist in the built-in types of buttons. If this is a CSS class from your styles, user the class attribute to add the style:
```
<button nz-button class="success">My button</button>
```

Be aware that you have to implement the style for the `:focus` and `:active` CSS states for your buttons to make it look great.

Example in SCSS:
```
$primary-color: #287a96;
$info-color: #8ca9bb;
$success-color: #10cfbd;
$processing-color: #1890ff;
$error-color: #e74f4b;
$highlight-color: #f5222d;
$warning-color: #ffc331;
$normal-color: #d9d9d9;
$white: #fff;
$black: #000;

$colors-list: (
    primary: $primary-color,
    info: $info-color,
    success: $success-color,
    processing: $processing-color,
    error: $error-color,
    highlight: $highlight-color,
    warning: $warning-color,
    normal: $normal-color,
);

@each $key, $val in $colors-list {
    button.btn-#{$key} {
        background-color: $val;
        border-color: shade($val, $mix-dark-percent);

        &:hover, &:focus {
            background-color: tint($val, $mix-light-percent);
            border-color: shade($val, $mix-dark-percent);
        }

        &:active {
            background-color: shade($val, $mix-dark-percent);
            border-color: shade($val, $mix-dark-percent);
        }
    }

    nz-button-group.ant-btn-group.btn-#{$key} {
        button.ant-btn {
            background-color: $val;
            border-color: shade($val, $mix-dark-percent);

            &:hover, &:focus {
                background-color: tint($val, $mix-light-percent);
            }

            &:active {
                background-color: shade($val, $mix-dark-percent);
            }

            &:first-child:not(:last-child) {
                border-color: shade($val, $mix-dark-percent);
            }

            &:last-child:not(:first-child) {
                border-color: shade($val, $mix-dark-percent);
            }
        }
    }
}
```

This might not be the perfect way but it gets the job done
