### ISSUE TITLE
请问如何动态修改menu组件 popup层中的子菜单的背景样色，我设置主题变量中的subMenuItemBg并没有效果

### ISSUE THREAD

**Issue by 1245488569** [ant-design/ant-design#47704]
### Reproduction link

[https://github.com/1245488569/xt-admin-react18](https://github.com/1245488569/xt-admin-react18)

### Steps to reproduce

在ConfigProvider的Menu中设置subMenuItemBg为 ‘f00’，无效

### What is expected?

期望菜单主题变量中的subMenuItemBg有效

### What is actually happening?

实际为默认颜色，并不是我期望的颜色

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | react |
| System | win11 |
| Browser | Edge122.0.2365.66 |

**Comment by MadCcc** [comment]
用 `popupBg`
