### ISSUE TITLE
在MAC英文输入法下，输入框输入一点内容之后，然后连续点击两次会输入一个小数点

### ISSUE THREAD

**Issue by childrentime** [ant-design/ant-design#47706]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn](https://ant-design.antgroup.com/components/input-cn)

### Steps to reproduce

使用mac英文输入法，输入一个a字母之后，快速点击两次空格

### What is expected?

不应该出现小数点

### What is actually happening?

出现了小数点

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | 18 |
| System | macos |
| Browser | chrome latest |

---
antd官网就可以浮现

**Comment by zombieJ** [comment]
试了一下，无法复现。看看是不是装了什么游览器插件？

**Comment by yoyo837** [comment]
这个是Mac系统的功能，和antd无关

**Comment by yoyo837** [comment]
中文输入下，相同的操作会打句号

**Comment by yoyo837** [comment]
<img width="640" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/a434c9c1-ea0e-40eb-99be-c594ef8e6d07">

**Comment by childrentime** [comment]
我的，别的输入框测试的时候测漏了
