### ISSUE TITLE
Button 组件 hidden={true} 功能丢失

### ISSUE THREAD

**Issue by bluexiaowei** [ant-design/ant-design#47711]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-eykmds?file=demo.tsx)

### Steps to reproduce

```tsx
const App: React.FC = () => (
    <Button type="primary" hidden >Primary Button</Button>
);
```

### What is expected?

同 v4 版本一样隐藏该按钮

### What is actually happening?

并没有隐藏

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | 18.2.0 |
| System | window 10 |
| Browser | Chrome 版本 122.0.6261.95（正式版本） （64 位） |

**Comment by zombieJ** [comment]
[官方文档中没有提供的隐藏 API 我可以使用吗？](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)

**Comment by afc163** [comment]
你需要 `antd/dist/reset.css`：https://stackblitz.com/edit/react-eykmds-zkv53b?file=demo.tsx,index.tsx
