### ISSUE TITLE
使用 Nextjs 运行项目报 SyntaxError: Unexpected token 'export' 错误

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design#47715]
### Reproduction link

[https://github.com/hqwlkj/next-antd.git](https://github.com/hqwlkj/next-antd.git)

### What is actually happening?

```
/node_modules/rc-pagination/es/locale/en_US.js:16
export default locale;
^^^^^^

SyntaxError: Unexpected token 'export'
```

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | 18.2.0 |
| System | Mac OS |
| Browser | Google Chrome  版本 122.0.6261.94（正式版本） (x86_64) |

**Comment by zombieJ** [comment]
参考一下 next  的 issue： https://github.com/vercel/next.js/issues/62472
