### ISSUE TITLE
Class类型组件中的Table column render 方法只执行一次

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [ant-design/ant-design#47726]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/basic-usage-antd-4-24-15-forked-v2yymz?file=%2FclassDemo.js%3A23%2C23)

### Steps to reproduce

背景：最近在做Antd从V3升级到V4最新版的工作，但是发现table column的render方法，在class组件中只执行了一次，自定义cell输入内容，更新state成功后，不会重新触发column render！
因为之前的项目代码大部分都是class组件，替换成function组件成本太高，这边有没有更简单的解决方案。

### What is expected?

希望自定义cell输入新值后，重新render table的column
PS: Column API shouldCellUpdate我也试了，没有帮助。

### What is actually happening?

Class类型组件中的Table column render 方法只执行一次，数据刷新不会导致重新render

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 16.9.0 |
| System | Win10 |
| Browser | Version 122.0.6261.95 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
可以 HOC 一下 Table 组件，每次渲染都是新的 column：

```tsx
const MyTable = ({ columns, ...props }) => <Table columns={[...columns]} {...props} />;
```

**Comment by JinHe-PerkinElmer** [comment]
> 可以 HOC 一下 Table 组件，每次渲染都是新的 column：
> 
> ```tsx
> const MyTable = ({ columns, ...props }) => <Table columns={[...columns]} {...props} />;
> ```

谢谢，我试试

**Comment by JinHe-PerkinElmer** [comment]
> 可以 HOC 一下 Table 组件，每次渲染都是新的 column：
> 
> ```tsx
> const MyTable = ({ columns, ...props }) => <Table columns={[...columns]} {...props} />;
> ```

@zombieJ , HOC之后好像还是不会触发render。。。
https://codesandbox.io/p/sandbox/basic-usage-antd-4-24-15-forked-v2yymz?file=%2FclassDemo.js%3A24%2C4-24%2C9

**Comment by JinHe-PerkinElmer** [comment]
最终解决方案：重构Table相关代码，将Table从Class组件中抽离出来，用Function组件重写。关键点是：数据刷新时保证Column定义中的render方法是新的，不然column不会重新渲染！
