### ISSUE TITLE
button提供一个对标disabled 的enable属性

### ISSUE THREAD

**Issue by zemmmmmmm** [ant-design/ant-design#47725]
### What problem does this feature solve?

 ```jsx
<Button disabled ={!selectedRows.length} > 批量解封 </Button>
```
总是没有那么自然 大脑要进行一个双重否定的判断
建议引入一个enable属性 貌似更自然符合直觉

### What does the proposed API look like?

 ```jsx
<Button enable={selectedRows.length} > 批量解封 </Button>
```

**Comment by zombieJ** [comment]
自行 HOC 一下哈~

**Comment by yoyo837** [comment]
不必要，enable和disabled同时给咋办！副作用太多。
