### ISSUE TITLE
Enhance Tag Component: Separate API Props for Text and Icon Color

### ISSUE THREAD

**Issue by syed-create** [ant-design/ant-design#47721]
### What problem does this feature solve?

The current implementation of the Tag component in Ant Design lacks specific API props for customizing the text color inside the component and setting the color of the icon independently. This limitation poses challenges for users who wish to apply distinct colors to the text, especially when deviating from the predefined presets. The proposed solution suggests introducing separate API props for the Tag component to allow users to independently control the text and icon colors. This enhancement offers greater customization flexibility, enabling users to create visually cohesive and aesthetically pleasing tag designs tailored to their specific requirements. The benefits include improved design options, enhanced visual appeal, and an overall more versatile and user-friendly Tag component.

### What does the proposed API look like?

textColor: string, iconColor: string

**Comment by MadCcc** [comment]
There's no need to do this. You can set color for icons when you use it.

**Comment by syed-create** [comment]
@MadCcc what about the text color with custom background colors. by default text color is white. how can we set text color ?
