### ISSUE TITLE
table子组件中的column，render动态渲染的form.item时会改变绑定的字段

### ISSUE THREAD

**Issue by jxccc1998** [ant-design/ant-design#47724]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-ghmt8c?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltf4qc970006356gszyxoi0l%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltf4qc970002356g2ighzy3l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltf4qc970003356gy8buvndh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltf4qc970005356gddijogqj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltf4qc970002356g2ighzy3l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltf)

### Steps to reproduce

先输入age20，然后点击change按钮，会改变formitem的渲染，此实会显示初始值，而不是刚刚更改的
age20

### What is expected?

希望formitem销毁时可以用之前输入的值

### What is actually happening?

formitem销毁时可以用初始的值

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 17 |
| System | win10/mac |
| Browser | chrome 120.0.6099.109 |

**Comment by crazyair** [comment]
demo 改用 stackblitz ?

**Comment by jxccc1998** [comment]
> stackblitz

现在这个不行吗

**Comment by crazyair** [comment]
是不是这里 name 写错了
![image](https://github.com/ant-design/ant-design/assets/7971419/c150cacf-f453-42d7-b4d0-66a334be7223)

**Comment by jxccc1998** [comment]
> 是不是这里 name 写错了 ![image](https://private-user-images.githubusercontent.com/7971419/310358107-c150cacf-f453-42d7-b4d0-66a334be7223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDQwODksIm5iZiI6MTcwOTcwMzc4OSwicGF0aCI6Ii83OTcxNDE5LzMxMDM1ODEwNy1jMTUwY2FjZi1mNDUzLTQyZDctYjRkMC02NmEzMzRiZTcyMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDU0MzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZlMTEyMDE5NGJiZDA3Zjg1ZDYxMmY1ZThkMTgzMDUwMTJjYWI1MzE5NzY1MDBjMTlmZDY4ZjM1MzBmZTVmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NrDoeURqCEySHH0dsqPfNcLBTGVsoTJOz2OFp-MTBQ0)

sorry写快了，重新改了下。实际业务是向子表传入一个父表的状态，状态刷新后之前的值无法留存，因为formitem无了（示例中在子表展开的后填写money）。

**Comment by crazyair** [comment]
不清楚要什么效果，看起来不像组件 bug，而是用法问题，你可以再看下

**Comment by afc163** [comment]
来个 gif 图吧，没看懂具体是怎么操作

**Comment by jxccc1998** [comment]
> 不清楚要什么效果，看起来不像组件 `bug，而是用法问题，你可以再看下`

![动画](https://github.com/ant-design/ant-design/assets/58023710/e00eabcd-bb7e-469a-a8fe-ef9a089d1431)

就是我在子表填写了money是10，然后change了之后money就无了，因为我更改了table中subTable的formitem的渲染条件，我觉得不能通过formitem是否渲染去修改form实例之前就保存的数据，不然就可以通过控制UI渲染去更改已经操作过的数据

**Comment by zombieJ** [comment]
Form.Item 设置 `name` 是需要配置子组件的 `value` 和 `onChange`，你给 MyTable 外面的 Form.Item 设置了 `name` 又没有对 MyTable 做受控，导致数据无法正确映射。而在 Table 内部又通过 `index` 做映射，`index` 只能表示当下顺序，对于数据内容不是直接映射如果要这么写需要参考 `rc-field-form` 中的 Form.List 的 key 映射逻辑。

正确的做法是 MyTable 封装成一个受控的表单子组件。参考一下这个例子哈：

https://ant-design.antgroup.com/components/form-cn#components-form-demo-customized-form-controls

**Comment by jxccc1998** [comment]
> Form.Item 设置 `name` 是需要配置子组件的 `value` 和 `onChange`，你给 MyTable 外面的 Form.Item 设置了 `name` 又没有对 MyTable 做受控，导致数据无法正确映射。而在 Table 内部又通过 `index` 做映射，`index` 只能表示当下顺序，对于数据内容不是直接映射如果要这么写需要参考 `rc-field-form` 中的 Form.List 的 key 映射逻辑。
> 
> 正确的做法是 MyTable 封装成一个受控的表单子组件。参考一下这个例子哈：
> 
> https://ant-design.antgroup.com/components/form-cn#components-form-demo-customized-form-controls

我纠结的不是这个绑定的关系，做成受控组件一定是可以的，我只是不想自己去onChange, 在示例中顺序是没有发生变化的，所以感觉index映射不影响我所描述的问题。 我想知道的地方是为什么动态改变了formItem的渲染会修改form实例的属性，当我不改变formitem的渲染时，通过namepath的绑定就是没有问题的。
