### ISSUE TITLE
modal对话框能够提供按钮大小的配置项吗？

### ISSUE THREAD

**Issue by luckykun** [ant-design/ant-design#4774]
modal对话框有visible、okText、cancelText等配置项，

但是按钮大小一直是ant-btn-lg，个人感觉不太灵活

所以能否增加一个配置项来改变按钮的大小呢？

**Comment by yesmeck** [comment]
自定义  footer 实现。

**Comment by afc163** [comment]
默认遵循了设计规范，对话框里需要使用大号按钮。特殊需求可以用 footer 进行定制。
