### ISSUE TITLE
响应式 Select 效果可以修改吗

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47743]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jselzj?file=demo.tsx)

### Steps to reproduce

查看 demo

### What is expected?

能显示最多内容

<img width="387" alt="image" src="https://github.com/ant-design/ant-design/assets/7971419/7e6c5617-a56b-4a0b-99ac-4e3801465448">

### What is actually happening?

只显示了  +1...

<img width="529" alt="image" src="https://github.com/ant-design/ant-design/assets/7971419/da00afa1-56e7-42ff-8bd6-df9c425ad3eb">

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
截图里的用 `maxTagPlaceholder` HOC 当 omit 和 value 数量一样的时候切一个出来。如果只是要至少留一个，可以考虑直接设置单个 selector 宽度。

https://stackblitz.com/edit/react-jselzj-zweymi?file=demo.tsx,index.css

**Comment by crazyair** [comment]
其实想要那个 +1... 能自动省略

**Comment by yoyo837** [comment]
> 其实想要那个 +1... 能自动省略

我们也有这个场景，HOC的

**Comment by crazyair** [comment]
> > 其实想要那个 +1... 能自动省略
> 
> 我们也有这个场景，HOC的

也是加了个 max-width 吗

**Comment by crazyair** [comment]
max-width 写上，不管用没用 responsive 都能作用到，没法区分

**Comment by yoyo837** [comment]
不是，判断了值的数量，根据情况覆盖了一下css 等

**Comment by crazyair** [comment]
max-width 这个值还不好固定，如果设置的大于 Select 宽度会失效
