### ISSUE TITLE
样式兼容 px2rem内联样式转换 

### ISSUE THREAD

**Issue by whiteroseisred** [ant-design/ant-design#47748]
### What problem does this feature solve?

解决px2rem对内联样式转换失效问题

### What does the proposed API look like?

我期望内联样式同样可转换rem

**Comment by afc163** [comment]
See https://ant-design.antgroup.com/docs/react/compatible-style-cn#rem-%E9%80%82%E9%85%8D

**Comment by ananiy** [comment]
> See https://ant-design.antgroup.com/docs/react/compatible-style-cn#rem-%E9%80%82%E9%85%8D

这个好像对css变量不生效，可以帮忙看下吗

**Comment by yoyo837** [comment]
css变量是运行时的，px2rem 是编译一次性的，你把css变量也用rem单位算好即可。

**Comment by ananiy** [comment]
> css变量是运行时的，px2rem 是编译一次性的，你把css变量也用rem单位算好即可。

我的意思是，配置里面开启了css变量，<ConfigProvider theme={{ cssVar: true }}> 之后，生成的css变量可以转成rem吗
![image](https://github.com/ant-design/ant-design/assets/33290601/aa737d80-640e-4ea3-96c5-8a2e626f8eab)

**Comment by yoyo837** [comment]
@MadCcc 这个是不是可以开个口子支持一下？

**Comment by ysl-ccc** [comment]
> ### What problem does this feature solve?
> 解决px2rem对内联样式转换失效问题
> 
> ### What does the proposed API look like?
> 我期望内联样式同样可转换rem

可以使用此方法进行暂时的代理替换：

```
import { px2remTransformer as antdPx2remTransformer } from "@ant-design/cssinjs";

const setAttribute = HTMLStyleElement.prototype.setAttribute;

export const px2remTransformer = () => {
  proxyAntdStyle();
  return antdPx2remTransformer({
    rootValue: 16, // 32px = 1rem; @default 16
  });
};

function convertPxToRem(cssTextString: string, baseFontSize = 16) {
  // 定义一个正则表达式,匹配所有的 px 值
  const pxRegex = /(\d*\.?\d+)px/g;

  // 替换 px 值为 rem 值的函数
  const replacer = (match: any, pxValue: any) => {
    const remValue = parseFloat(pxValue) / baseFontSize + "rem";
    return remValue;
  };

  // 使用 replace 方法替换 cssText 中的 px 值
  const convertedCSSText = cssTextString.replace(pxRegex, replacer);

  return convertedCSSText;
}

/** 代理antd的样式 */
function proxyAntdStyle() {
  HTMLStyleElement.prototype.setAttribute = function (
    qualifiedName: string,
    value: string
  ) {
    /** antd在设置每个组件样式的时候会在style上设置属性data-rc-order，并将值赋值给innerHTML */
    if (qualifiedName === "data-rc-order") {
      Object.defineProperty(this, "innerHTML", {
        get() {
          return this.innerText;
        },
        set(v) {
          this.innerText = convertPxToRem(v);
        },
      });
    }
    return setAttribute.call(this, qualifiedName, value);
  };
}
```

然后
```
const px2rem = px2remTransformer();
<StyleProvider transformers={[px2rem]}>
    <MyApp />
  </StyleProvider>
```

**Comment by 3Alan** [comment]
这个官方能否支持一下，上面兄弟的方案能临时解决但是有严重的性能问题

**Comment by ysl-ccc** [comment]
> 这个官方能否支持一下，上面兄弟的方案能临时解决但是有严重的性能问题

  次一点的解决方案就是开发环境开启
```
theme={{ cssVar: true }}
```
生产环境就关闭cssVar，这样也可以满足

**Comment by 3Alan** [comment]
> > 这个官方能否支持一下，上面兄弟的方案能临时解决但是有严重的性能问题
> 
> 次一点的解决方案就是开发环境开启
> 
> ```
> theme={{ cssVar: true }}
> ```
> 
> 生产环境就关闭cssVar，这样也可以满足

我现在使用的是tailwind，通过css变量来实现主题切换，如果关闭了cssVar就只能通过js的方式修改token无法共享css var变量

**Comment by ysl-ccc** [comment]
> > > 这个官方能否支持一下，上面兄弟的方案能临时解决但是有严重的性能问题
> > 
> > 
> > 次一点的解决方案就是开发环境开启
> > ```
> > theme={{ cssVar: true }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 生产环境就关闭cssVar，这样也可以满足
> 
> 我现在使用的是tailwind，通过css变量来实现主题切换，如果关闭了cssVar就只能通过js的方式修改token无法共享css var变量

这个问题官方很早就才寻求PR，没人实现，自己去简单看过源码，需要修改很底层库方法才能实现（菜鸡大致看了一下）！

**Comment by 3Alan** [comment]
> > > > 这个官方能否支持一下，上面兄弟的方案能临时解决但是有严重的性能问题
> > > 
> > > 
> > > 次一点的解决方案就是开发环境开启
> > > ```
> > > theme={{ cssVar: true }}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 生产环境就关闭cssVar，这样也可以满足
> > 
> > 
> > 我现在使用的是tailwind，通过css变量来实现主题切换，如果关闭了cssVar就只能通过js的方式修改token无法共享css var变量
> 
> 这个问题官方很早就在提了，只是没人实现，自己去简单看过源码，需要修改很底层库方法才能实现（菜鸡大致看了一下）！

是的，涉及到cssinjs那个库
