### ISSUE TITLE
rc-util版本升级后，Table设置scroll.y Header有多余元素

### ISSUE THREAD

**Issue by direwolf512** [ant-design/ant-design#47754]
### Reproduction link

[https://tndy8n.csb.app/](https://tndy8n.csb.app/)

### Steps to reproduce

1. rc-util升级到5.39.0版本（非大版本）;
2. 给Table组件设置scroll.y。
![table](https://www.sun-snowflake.cn/static_img/public/table.gif)

### What is expected?

无多余元素

### What is actually happening?

有多余元素

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.0.0 |
| System | mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
sandbox 是不是没有设置 public？

**Comment by direwolf512** [comment]
> sandbox 是不是没有设置 public？

好了
