### ISSUE TITLE
Antd Table Column Resizing 

### ISSUE THREAD

**Issue by pushpendrahpx** [ant-design/ant-design#47756]
### What problem does this feature solve?

- Currently resizing method that we have in antd re-renders whole table for every px change of column.

### What does the proposed API look like?

- We can do DOM manipulation and have a handler right next to antd columns, and by listening to some events we can calculate the width of that column, and apply it in col.style.width of that corresponding col element.

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by pushpendrahpx** [comment]
> Could you provide a reproduce link about this problem?

Here is the Link - [Code Sandbox Link](https://codesandbox.io/p/sandbox/gracious-sky-q83hgs)

> What does the proposed API look like?
 will add it ASAP

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/32811

**Comment by pushpendrahpx** [comment]
So, do we have any solution for this ?

**Comment by MadCcc** [comment]
Is `shouldCellRender: false` enough?

**Comment by pushpendrahpx** [comment]
Hey @MadCcc Do we have this method ? I don't see it in documentation. Ig we only have shouldCellUpdate().
Can we directly use DOM Manipulation and update the width in colgroup element ?
For me its working these days, So I was wondering we can use this method in AntD itself.
