### ISSUE TITLE
Form如果提供了initialValues，onFinish的回调values是否可以自动推断出类型

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design#47758]
### What problem does this feature solve?

onFinish的回调values永远暴漏的都是any

### What does the proposed API look like?

Form如果提供了initialValues，onFinish的回调values可以自动推断出类型

**Comment by zombieJ** [comment]
`initialValues` 是 FormData 的子集，不是等价关系。Form 本身就支持泛型，你应该通过泛型来填充：
```tsx
interface FormData {}

<Form<FormData> />
```

**Comment by afc163** [comment]
@rookie-luochao 不确定能不能推导出来，来试试给个 PR？

**Comment by crazyair** [comment]
首先，initialValues 使用泛型

![image](https://github.com/ant-design/ant-design/assets/7971419/db263407-1386-471e-894e-974ef0f3185b)

这里 values 还是 any 类型

![image](https://github.com/ant-design/ant-design/assets/7971419/e77d2b43-f7d9-4bad-b56a-a4495aad306e)

是因为 `form={form}` 干扰的，需要注释掉，或者 useForm<xxx> 也设置类型。使用上还是有点麻烦，不如直接 <Form<xxx>
