### ISSUE TITLE
tabs/index.d.ts lacks of  className & disabled

### ISSUE THREAD

**Issue by guissy** [ant-design/ant-design#4776]
#### Environment(required)

- antd version: 2.7.0
- OS and its version: mac 10.11
- Browser and its version: chrome 55

#### What did you do? Please provide steps to re-produce your problem.
````tsx
<Tabs.TabPane tab="快" key="k" className={'c1'} disabled></Tabs.TabPane>
````
Error:(24, 13) TS2324:Property '**className disabled**' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<TabPaneProps, ComponentState>> & { child...'.

#### What do you expected?

export interface TabPaneProps {
    /** 选项卡头显示文字 */
    tab?: React.ReactNode | string;
    style?: React.CSSProperties;
    className?: string; // 添加这个
    disabled?: boolean; // 添加这个
}

#### What happen?
tsc error

**Comment by yesmeck** [comment]
PR 😄

**Comment by afc163** [comment]
@guissy You can give us a PR for this.
