### ISSUE TITLE
How to get total event response for InputNumber?

### ISSUE THREAD

**Issue by iiitmahesh** [ant-design/ant-design#4777]
How to get total event for InputNumber with antd??

To get total event response Input has on change method but **InputNumber**  does not any method to acces total event response .

Which menas case 1 and case2 not getting same response. 
Beacause 

- case 1 --> res -->  event 
- case2 ---> res --> value.

**Ref :** 
antd/lib/input --> props types
antd/lib/input-number--> props types
(** onchange method is different for both  )
```
handleChange(res){
 console.log(res)
}

```
Case 1:
```
` <FormItem label="Note" labelCol={{ span: 4 }} wrapperCol={{ span: 8 }} >
                            {getFieldDecorator('note', { rules: [{ required: true, message: 'Please input your note!' }], onChange: this.handleChange })(
                                <Input />
                            )}
                        </FormItem>`
```
Case 2:
```
 <FormItem label="Note" labelCol={{ span: 4 }} wrapperCol={{ span: 8 }} >
                            {getFieldDecorator('note1', { rules: [{ required: true, message: 'Please input your note!' }], onChange: this.handleChange })(
                                <InputNumber />
                            )}
```

**Comment by afc163** [comment]
It is not supported now: https://github.com/react-component/input-number/blob/ee01ef48f179868d7e2ed2965217ef5383ddbe40/src/mixin.js#L62

What's your demand?

**Comment by iiitmahesh** [comment]
onchange I need  key and value of particular field .

**Comment by afc163** [comment]
What is the relationship of ` key and value of particular field` and `event`?

**Comment by iiitmahesh** [comment]
Actual need is to send key and value  to my action onchange. I have comibantion of Input and InputNumber in form. 

**case (input number)**
```
handleChange(value){
 console.log(value)
}
```
**case (input )**
```
handleChange(e){
 console.log(e.target.value, e.target.value)
}
```

**Comment by afc163** [comment]
My suggestion is that you can add judgment for different controls and it's argument types.

**Comment by benjycui** [comment]
How about this:

```jsx
<FormItem label="Note" labelCol={{ span: 4 }} wrapperCol={{ span: 8 }} >
  {getFieldDecorator('note', { rules: [{ required: true, message: 'Please input your note!' }], onChange: (e) => this.handleChange(e, 'note') })(
    <Input />
  )}
</FormItem>
```

**Comment by afc163** [comment]
<img width="341" alt="image" src="https://cloud.githubusercontent.com/assets/507615/22732212/4d7fbbaa-ee28-11e6-920b-a478f6b5ffae.png">

I don't found any `key` in these cases.

**Comment by iiitmahesh** [comment]
ohh its a typo mistake..!

I am doing something like below.
```
handleChange(e){
 console.log(e.target.name, e.target.value)
}
```

```
<FormItem label="Note" labelCol={{ span: 4 }} wrapperCol={{ span: 8 }} >
                            {getFieldDecorator('note', { rules: [{ required: true, message: 'Please input your note!' }], onChange: this.handleChange })(
                                <Input  name="note"/>
                            )}
                        </FormItem>`
```

**Comment by afc163** [comment]
I see.. You can check @benjycui 's solution.

**Comment by iiitmahesh** [comment]
@benjycui  solution only give value and string respective value.

```
<FormItem label="Note" labelCol={{ span: 4 }} wrapperCol={{ span: 8 }} >
  {getFieldDecorator('note', {
      rules: [{ required: true, message: 'Please input your note!' }],
      onChange: (e) => this.handleChange(e, 'note') // HERE!
   })(
    <Input />
  )}
</FormItem>
```

 ```
handleChange = (e, value) =>{
            console.log(e, value)
        }
```
same piece code give output : **200 , note** // 200 entered value in form

**Comment by afc163** [comment]
`'note'` is same as `e.target.name` you asked for.

**Comment by afc163** [comment]
Input and InputNumber is different component, you should not handle them by same onChange function.
