### ISSUE TITLE
TextArea: selectionEnd always 0

### ISSUE THREAD

**Issue by annkathrinf** [ant-design/ant-design#47779]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/autosizing-the-height-to-fit-the-content-antd-5-15-1-forked-qztdwr?file=%2Fdemo.tsx)

### Steps to reproduce

Create TextArea and log selectionEnd

### What is expected?

Expected selectionEnd to display cursor position

### What is actually happening?

selectionEnd is always 0

| Environment | Info |
| --- | --- |
| antd | 5.15.1 |
| React | react version 18.0.0 |
| System | macOS version 14.1.1 (23B81) |
| Browser | Chrome version 122.0.6261.94  |

---
With V4 it seems to be working fine: https://stackblitz.com/edit/react-w8u1me?file=demo.tsx

**Comment by zombieJ** [comment]
Strange. console not shows the `selectionEnd` but it work when inspect the textarea to get the `selectionEnd`

**Comment by C3maLi** [comment]
> Strange. console not shows the `selectionEnd` but it work when inspect the textarea to get the `selectionEnd`

Since the Antd version in the example is 4.24.15, it works on this version. The same problem, when we use react-number-format in customInput, it always gets 0. selectionStart and selectionEnd

https://github.com/react-component/input/pull/54

I think it's because of the change here.

**Comment by annkathrinf** [comment]
In the sandbox example where I used V5 it's not working. My original problem was that another library, react-textarea-autocomplete, stopped working after the upgrade from v4 to v5 because its trigger relies on a correct value of `selectionEnd`.
Looks like this ticket is actually a duplicate of https://github.com/react-component/input/issues/62

**Comment by C3maLi** [comment]
> V5'i kullandığım sanal alan örneğinde çalışmıyor. Asıl sorunum, başka bir kütüphane olan react-textarea-autocomplete'in v4'ten v5'e yükseltme sonrasında çalışmayı durdurmasıydı çünkü tetikleyicisi doğru bir `selectionEnd`. [Görünüşe göre bu bilet aslında react-component/input#62'nin](https://github.com/react-component/input/issues/62) kopyası[](https://github.com/react-component/input/issues/62)

Yes, this problem occurred after the development in the link I gave, since cloneNode is used, it always returns selectionStart and selectionEnd = 0. This is why it happens.

https://github.com/react-component/input/pull/54#discussion_r1423372286

I think development needs to be done here.
