### ISSUE TITLE
table隐藏滚动条后，表头和内容不对齐

### ISSUE THREAD

**Issue by Illidan0219** [ant-design/ant-design#47777]
### Reproduction link

[https://github.com/Illidan0219/ant-design-table-issue.git](https://github.com/Illidan0219/ant-design-table-issue.git)

### Steps to reproduce

1、table组件设置了scroll参数，但是在数据不多的时候，也会有滚动条的背景，所以设置ant-table-body的overflow为auto
2、这个时候没有滚动框，但是表头的操作栏和操作栏下面的内容不对齐

### What is expected?

可以有属性来设置，当数据的量不足以使表格出现滚动条的时候，可以隐藏滚动条，同时操作栏和下面的内容对齐

### What is actually happening?

操作栏和下面的内容不对齐

| Environment | Info |
| --- | --- |
| antd | 5.15.1 |
| React | 18.2.0 |
| System | windows、ios |
| Browser | 122.0.6261.69 |

**Comment by zombieJ** [comment]
魔改样式后表头要自行处理，通过 `components` 自定义 body 部分实现监听是否出现滚动条，然后 `components` 自定义 header 部分在没有滚动条的时候把滚动条的占位裁剪掉。

**Comment by front-refined** [comment]
> 魔改样式后表头要自行处理，通过 `components` 自定义 body 部分实现监听是否出现滚动条，然后 `components` 自定义 header 部分在没有滚动条的时候把滚动条的占位裁剪掉。

你这个只是第一层，还需要处理，columns 设置了 fixed: right 时会自动计算加上 Scrollbar width 的问题。只能改源码了。

很好奇这个小问题为什么这么多年了，还没有得到解决......
