### ISSUE TITLE
Button 在嵌套的情况下也会自动添加空格

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#47772]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/an-niu-lei-xing-antd-5-15-1-forked-yydgn6?file=%2Fdemo.tsx%3A21%2C3)

<img width="1172" alt="image" src="https://github.com/ant-design/ant-design/assets/51586637/3000f420-0c2b-486f-9ec0-371818a17cc0">

### Steps to reproduce

查看 codesandbox 示例

涉及代码：https://github.com/ant-design/ant-design/blob/master/components/button/style/index.ts#L69

### What is expected?

只对直接子级生效，或者给 Button 组件开放设置自动空格的 Prop

### What is actually happening?

嵌套元素下依然会自动添加空格

| Environment | Info |
| --- | --- |
| antd | 5.15.1 |
| React | 18 |
| System | Any |
| Browser | Any |

**Comment by GeorgeHcc** [comment]
@zhenzhenChange  如果只是想自定义button text与icon的间距可以这样做：
需要把icon作为直接子元素
``` jsx
<Button type="primary">
          <span style={{ marginRight: 10 }}>
            图标
          </span>
          <StarOutlined />
        </Button>
```
看官方要不要把这里换成后代子元素 @li-jia-nan 
```
 [`&${componentCls}-two-chinese-chars > *:not(${iconCls})`]: {
        marginInlineEnd: '-0.34em',
        letterSpacing: '0.34em',
      },
```

**Comment by afc163** [comment]
我的看法不同，我感觉你更需要一个 `iconPosition="right"`。

**Comment by li-jia-nan** [comment]
> 我的看法不同，我感觉你更需要一个 `iconPosition="right"`。

叫 `start` 和 `end` 会不会更好一点

**Comment by afc163** [comment]
应该是 start 和 end，这里沟通用 right 比较好懂。

**Comment by GeorgeHcc** [comment]
> 叫 `start` 和 `end` 会不会更好一点
> 
> * [FEATURE: inconLeft iconRight for <Button>, like chakra ui: #47325](https://github.com/ant-design/ant-design/discussions/47325)

期待这个feature，非常有必要！😄

**Comment by afc163** [comment]
@GeorgeHcc 要不要来个 PR，实现上应该不难。

**Comment by li-jia-nan** [comment]
默认值是 `start`，兼容现在的 `icon` ？

**Comment by li-jia-nan** [comment]
那如果用户需要同时设置 `startIcon` 和 `endIcon` 呢？

**Comment by yoyo837** [comment]
> 那如果用户需要同时设置 `startIcon` 和 `endIcon` 呢？

丑

**Comment by GeorgeHcc** [comment]
> @GeorgeHcc 要不要来个 PR，实现上应该不难。

我可以先尝试下实现

> > 那如果用户需要同时设置 `startIcon` 和 `endIcon` 呢？
> 
> 丑，直接不支持算了

赞成，同时只能设置一个  `iconPosition="start" | "end"` 默认`start`

**Comment by j-vitali** [comment]
would be great haing iconLeft and iconRight

**Comment by zhenzhenChange** [comment]
不给 Button 组件单独开放一个是否自动空格的 Prop 是有什么考量吗，只能通过 ConfigProvider 设置的是全局，或者单独用 ConfigProvider 包一个 Button

**Comment by zhenzhenChange** [comment]
如果能够独立控制自动空格，其实我不管是放左边还是右边，还是两边都放，都比较自由，空格就不受 dom 层级或指定类名（icon）的限制

**Comment by MadCcc** [comment]
可以开一个 prop，但是一般这种就是全局配置比较好

**Comment by zhenzhenChange** [comment]
我能理解为确保一致性而设定的规则，只是为了确保这个规则，付出的维护成本貌似有点点高

**Comment by afc163** [comment]
close by https://github.com/ant-design/ant-design/pull/47791
