### ISSUE TITLE
Select 组件点击时下拉框不可见,发现点击选择框时动态渲染到select节点上的类名 ant-select-dropdown slide-up-enter slide-up-enter-prepare slide-up没消失

### ISSUE THREAD

**Issue by zhuyazhen** [ant-design/ant-design#47773]
### Reproduction link

[http://192.168.3.75/system_data_operate](http://192.168.3.75/system_data_operate)

### Steps to reproduce

多个联动选择框依次选择,选择select框内容后,删除再重新选择

### What is expected?

能正常展示select option的值,调试发现点击后触发了onDropdownVisibleChange,对应的open也是true,但是渲染到select节点上的样式有 ant-select-dropdown slide-up-enter slide-up-enter-prepare slide-up这些类名存在就不会展示下拉框了

### What is actually happening?

实际是没有展示select下拉框

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | "^16.13.1" |
| System | window |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
请不要提供网站，不知道你的代码是如何书写的。请提供 stackblitz 或者 codesandbox 这种可以在线查看和运行的重现哈~

**Comment by zhuyazhen** [comment]
按描述内容应该很容易复现的,不知道应该怎么提供代码和场景

**Comment by zhuyazhen** [comment]
主要是要关注ant-select-dropdown slide-up-enter slide-up-enter-prepare slide-up这些类名为什么会渲染在select节点不消失才会导致下拉框不出现

**Comment by zombieJ** [comment]
[知乎：如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)

**Comment by zhuyazhen** [comment]
不好意思,第一次提问题,还没搞懂怎么更好提供问题描述,先发一个截图,如果能看懂更好,等我一会有时间再研究看看怎么描述更清楚
![企业微信截图_17098785657319](https://github.com/ant-design/ant-design/assets/33250620/c4b547eb-54e0-4619-b673-6c0516d420d7)
真的非常抱歉...

**Comment by zombieJ** [comment]
> 请不要提供网站，不知道你的代码是如何书写的。请提供 stackblitz 或者 codesandbox 这种可以在线查看和运行的重现哈~


点击这个，然后会打开一个在线的代码编辑器，修改代码表现你遇到的问题。然后保存。

<img width="477" alt="截屏2024-03-08 14 19 59" src="https://github.com/ant-design/ant-design/assets/5378891/fc60c69c-2f4a-47e8-aef5-2902a491d20c">

你发的网站和截图无法提供解决问题有效的信息，解决问题需要依赖于 “看写的代码 + 断点调试”。光看表现是不知道什么问题的哈~

**Comment by zhuyazhen** [comment]
好的,谢谢,我来操作一下
