### ISSUE TITLE
form.setFieldValue does not work 

### ISSUE THREAD

**Issue by DmitryLebedevDev** [ant-design/ant-design#47792]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-8-2-forked-y2fl4v?file=%2Fdemo.tsx%3A21%2C7-21%2C15&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltj2ho9e00072v6fqe2ex4fn%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltj2ho9e00032v6fo5l9jk7c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltj2ho9e00042v6fyqks3785%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltj2ho9e00062v6ftqpbzx1x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltj2ho9e00032v6fo5l9jk7c%2522%253A%257B%2522id%2522%253A%2522cltj2ho9e00032v6fo5l9jk7c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltj3i3hl00022v6fl3srbv1a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A15%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltj3i3hl00022v6fl3srbv1a%2522%257D%252C%2522cltj2ho9e00062v6ftqpbzx1x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltj2ho9e00052v6f2k4zjyiy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltj2ho9e00062v6ftqpbzx1x%2522%252C%2522activeTabId%2522%253A%2522cltj2ho9e00052v6f2k4zjyiy%2522%257D%252C%2522cltj2ho9e00042v6fyqks3785%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltj2ho9e00042v6fyqks3785%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

click to add button
click to submit button

### What is expected?

print 
Success: {user: ['jack']} {user: ['jack']} ['jack']

### What is actually happening?

print 
Success: {} {} ['jack']

| Environment | Info |
| --- | --- |
| antd | 5.15.1 |
| React | 18 |
| System | linux |
| Browser | chrome latest |

**Comment by afc163** [comment]
There is no `<Form.Item name="user">` found in Form, that is the reason `setFieldValue` can't work.
