### ISSUE TITLE
增加一种有背景颜色浅一点的 Button 类型

### ISSUE THREAD

**Issue by lin-mt** [ant-design/ant-design#47794]
### What problem does this feature solve?

使用 primary 太过于突出，使用默认的又容易被客户忽略，希望出个中间状态

类似这种：

https://arco.design/react/components/button

<img width="1056" alt="image" src="https://github.com/ant-design/ant-design/assets/58337359/84d40f10-e57e-45c4-9a21-30543a890e2a">

### What does the proposed API look like?

type='secondary'

**Comment by zombieJ** [comment]
Ant Design 中，中强调就是 Default，弱强调是 Text。如果你需要不同的按钮类型，可以考虑通过 ConfigProvider 来 HOC 任意拓展组件哈：

```tsx
const MyButton = ({ type, ...rest }) => {
  const btn = <Button {...rest} />;

  if (type === 'secondary') {
    return (
      <ConfigProvider
        theme={{
          token: {
            Button: {
              defaultBg: 'red',
              defaultBorderColor: 'transparent',
              // ...
            },
          },
        }}
      >
        {btn}
      </ConfigProvider>
    );
  }

  return btn;
};
```

ref: [设计：按钮](https://ant-design.antgroup.com/docs/spec/buttons-cn)
