### ISSUE TITLE
希望 Grid 增加 xl 尺寸(1920px) 屏幕的适配

### ISSUE THREAD

**Issue by hjin-me** [ant-design/ant-design#4780]
Grid 的 lg 尺寸对应的是 >1200px，足以应对笔记本屏幕的尺寸。
但是目前显示器的分辨率已经达到甚至超过 1920px，水平宽度增加了60%，但是还是使用1200的布局策略。效果较差。

希望增加更大的适配规则以独立适配 >1600px 的尺寸的屏幕。

**Comment by afc163** [comment]
目前的响应式尺寸是参考了 [bootstrap]() 的设置。

不过根据[这个答案](http://stackoverflow.com/a/32203074/3040605)，现在的尺寸是有点过时了。这个可以支持一下。

楼主来个 PR 发到 `feature-2.8` 上搞一搞这个特性如何？另外 xl 尺寸的大小是 `1600px` 还是 `1920px`，还有待讨论。

**Comment by afc163** [comment]
@hjin-me ping

**Comment by hjin-me** [comment]
@afc163 正在敲代码。看了一下 material 的文档，他是在 >1600px 的时候整体调整布局，变成居中模式了。

我个人期望是 1600px，理由两个

* 1600 包括了1680 和 1920 两个分辨率。
* 1200~1600，1600~1920 这两个区间范围小一点，相比1200~1920区间小一些，适配会更加平顺。

**Comment by afc163** [comment]
👌

 那这个特性你来搞下，有没有问题？时间上不着急。

**Comment by hjin-me** [comment]
没有问题。稍后更新相关的代码变更。

文档部分的修改需要帮忙斟酌一下。

**Comment by afc163** [comment]
感谢帮助，我们会及时 CR 的。
