### ISSUE TITLE
Invalid warning using InputNumber in a Form with warningOnly using TypeScript

### ISSUE THREAD

**Issue by igloo12** [ant-design/ant-design#47814]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/validation-issue-jphn8h?file=%2Fdemo.tsx%3A1%2C1-32%2C1)

### Steps to reproduce

Enter a number in to the number input

### What is expected?

No warning to show

### What is actually happening?

A warning is showing saying 'My Number Field' is not a valid undefined

| Environment | Info |
| --- | --- |
| antd | 5.15.1 |
| React | 18.2.0 |
| System | MAC OS |
| Browser | Chrome |

---
Only happens on typescript

**Comment by zombieJ** [comment]
```diff
          rules={[
            {
              required: true,
              warningOnly: true,
++            type: "number",
            },
          ]}
```
