### ISSUE TITLE
Table 中展示 Popover，滚动到边缘，Popover 会一直闪

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#47819]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-k7tqul?file=demo.tsx)

### Steps to reproduce

1、点击列名为 Name 的某一行，开启 Popover
2、向左滚动
3、当 Popover 滚到 Table 边缘时，一直闪烁

### What is expected?

不闪烁

### What is actually happening?

一直闪烁

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
箭头消失的时候 Popover 已经可以隐藏了，可以跳过这个位置检测
