### ISSUE TITLE
RangePicker 重影问题 和 Safari与Chrome显示不一致问题

### ISSUE THREAD

**Issue by zhenzong** [ant-design/ant-design#4782]
#### Environment(required)

- antd version: 2.7.0
- OS and its version: macOS Sierra 10.12.2
- Browser and its version: safari: 10.0.2;   chrome: 56.0.2924.87 (64-bit)

RangePicker使用代码
```jsx
<FormItem label="时间" hasFeedback {...formItemLayout}>
    {
        getFieldDecorator('time', {
            rules: [
                { require: true, type: 'array', message: '请选择时间段'}
            ],
            initialValue: [zhNowAfter7, zhNowAfter14]
        })(
            <RangePicker/>
        )
    }
</FormItem>
```

1. RangePicker在safari中显示会重影，应该是placeholder没有消除。如下图：
![wechatimg26](https://cloud.githubusercontent.com/assets/16067461/22698428/7c9ed7b6-ed8f-11e6-92e1-dc6430a56fd3.jpeg)
复现步骤：
a. 正常选择日期，此时不会出现上述情况；
b. 点击清除按钮，清除掉日期；
c. 重新选择日期，这时候会出现上述情况。

如果鼠标在hover一下，重影就会消失。官方例子也有这样的情况。如下图：
![wechatimg27](https://cloud.githubusercontent.com/assets/16067461/22698664/22db0334-ed90-11e6-9418-5f1d655d38da.jpeg)

期望情况：
选择时间后，显示正常。

2. RangePicker同样代码在Safari中显示与Chrome中显示不一样：
Safari显示：
![wechatimg28](https://cloud.githubusercontent.com/assets/16067461/22698761/70aa6942-ed90-11e6-8578-080fc873f96f.jpeg)
Chrome显示：
![wechatimg29](https://cloud.githubusercontent.com/assets/16067461/22698795/85dc68ec-ed90-11e6-86ca-ee8e71c49f73.jpeg)
注意途中RangePicker的长度不一样。

官方例子中也有这样的情况
Safari显示：
![wechatimg30](https://cloud.githubusercontent.com/assets/16067461/22698871/c1874308-ed90-11e6-8279-db90f4c540fe.jpeg)
Chrome显示：
![wechatimg31](https://cloud.githubusercontent.com/assets/16067461/22698891/cd565034-ed90-11e6-8fba-0406ea9ae173.jpeg)

添加css代码可以解决这样的问题：
```css 
.ant-calendar-picker {
   width: 100%;
}
```

**Comment by benjycui** [comment]
> RangePicker在safari中显示会重影，应该是placeholder没有消除。

这个问题没有重现。

> RangePicker同样代码在Safari中显示与Chrome中显示不一样

这个不确定是否 by designed，设计稿看不出。。 cc @Chinglik

**Comment by zhenzong** [comment]
> 这个问题没有重现
好吧，早上再试了一下确实不行。但是昨晚确实是有的，也截图了。郁闷。总之，谢谢啦

**Comment by afc163** [comment]
> RangePicker同样代码在Safari中显示与Chrome中显示不一样

这个是因为 input 的默认宽度在不同浏览器下不太一样，chrome 会短一点。如果希望一样长，建议用 style 属性设置宽度。

**Comment by xileliu** [comment]
@zhenzong 重影问题是怎么解决的！

**Comment by zhenzong** [comment]
这个，你也遇到了？ 我也母鸡呀，我是莫名其妙遇到了，然后又莫名其妙好了。
当时我感觉应该是选择时间后，组件的焦点有问题，后来又出不来这个问题了。

**Comment by xileliu** [comment]
我现在就是在safari 上是有的，和你描述的一样；
![image](https://cloud.githubusercontent.com/assets/13429648/25738125/f7fb4ed2-31ad-11e7-9b90-c24b63bee1c4.png)

**Comment by zhenzong** [comment]
我也母鸡呀，我的现在却是是没有问题，也确实没有改过什么。
建议把代码，复现步骤贴出来，让大大们帮帮忙。 @benjycui

**Comment by zhenzong** [comment]
我也母鸡呀，我的现在却是是没有问题，也确实没有改过什么。
建议把代码，复现步骤贴出来，请大大们帮帮忙。 @benjycui

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

麻烦提供必现的 demo 和步骤，不然都是宇宙射线的锅。

**Comment by xileliu** [comment]
https://ant.design/components/form-cn/ 这个文档用safari打开；

**Comment by qq645381995** [comment]
@benjycui 
![image](https://cloud.githubusercontent.com/assets/7971419/25741884/6b033294-31bf-11e7-8fe4-e8fe9d801f49.png)
safari 版本  
![image](https://cloud.githubusercontent.com/assets/7971419/25741895/781217ca-31bf-11e7-9774-3a1de68560e4.png)

**Comment by qq645381995** [comment]
@benjycui  你们是没发现这个问题吗？

**Comment by benjycui** [comment]
...

![image](https://cloud.githubusercontent.com/assets/3580607/25796131/ee72b544-340a-11e7-85d5-e77f88321ba1.png)

![image](https://cloud.githubusercontent.com/assets/3580607/25796084/bfcab9ee-340a-11e7-9e39-fcdbd71108a9.png)

**Comment by qq645381995** [comment]
![image](https://cloud.githubusercontent.com/assets/7971419/25796370/de174952-340b-11e7-8325-5013cd2dbaaf.png)

**Comment by qq645381995** [comment]
![image](https://cloud.githubusercontent.com/assets/7971419/25796453/24fdb626-340c-11e7-9d0d-61580bc07360.png)

**Comment by benjycui** [comment]
@qq645381995 我不是否认你们碰到的问题，所以麻烦提供必现的例子、步骤等。

**Comment by qq645381995** [comment]
@benjycui   没有例子 和 步骤 就是 官网  或者 http://codepen.io/anon/pen/wGOWGW?editors=001 
都是会发生的

**Comment by yesmeck** [comment]
@benjycui 我这能重现的，看起来像是 safari  的 bug，placeholder 的 dom 节点已经移除了，但是字还在。

**Comment by qq645381995** [comment]
@yesmeck 会解决吗？还是？

**Comment by zhenzong** [comment]
这个问题找到原因和复现步骤了吗？

**Comment by zhenzong** [comment]
这个问题找到原因和复现步骤了吗？好好奇是什么问题额。

**Comment by zhenzong** [comment]
今天我又看到了这个问题的复现。
可以比较稳定的复现方式是： 点击时间控件，然后选择时间，注意，选择的时间宽度上宽一点。确保择完后鼠标不会经过时间控件，也就是说不再触发控件的（hover 还是 mouse leave？）这样的事件。然后就出现这个问题了。多试几次，会出现的这个问题的。

修复方式： 
当存在start, end这两个时间值时，则placeholder都设置为空字符串。 我提了pr #7079。 额，因为我不知道为什么设置值后placeholder不消失。

没有修复的问题是（如下图）：
当弹出时间选择框，选择了时间后，也会有类似 #4782 的问题，这个问题应该是存在于antd RangePicker所依赖的react-component库里的calender组件里。

![wechatimg15](https://user-images.githubusercontent.com/16067461/28957681-95acafe0-7925-11e7-90f9-12a6c3059216.jpeg)

**Comment by benjycui** [comment]
Relative: https://stackoverflow.com/questions/39624902/new-input-placeholder-behavior-in-safari-10-no-longer-hides-on-change-via-java

**Comment by benjycui** [comment]
Relative: https://github.com/Matt-Esch/virtual-dom/issues/426 https://jsbin.com/rogoludahu/edit?html,js,output

但我本地的 Safari 无法重现。

**Comment by qq645381995** [comment]
![image](https://user-images.githubusercontent.com/7971419/29009950-655c4d5a-7b5a-11e7-8e1b-23711fdfcc94.png)

你的 safari  到底什么鬼

**Comment by benjycui** [comment]
> 你的 safari 到底什么鬼

可能是因为我的杀毒软件比较厉害，把 bug 都杀了。

![image](https://user-images.githubusercontent.com/3580607/29010297-b99091a4-7b5c-11e7-8042-b4416f6cfb1b.png)

对于使用 RangePicker 碰到重影的人，如果你们使用 https://jsbin.com/rogoludahu/edit?html,js,output 也能重现问题，那么只能推测是 Safari 的 bug，事实上，RangePicker 那几个地方的 placeholder 都只是原生 input 的placeholder 而已。

**Comment by zhenzong** [comment]
我第一次点击也会出现重新，然后再点一下重影消失。
![wechatimg17](https://user-images.githubusercontent.com/16067461/29010320-f7cab8c8-7b5c-11e7-8519-2af6095736c4.jpeg)
那看起来是Safari的问题。antd能否处理一下这种情况？

**Comment by zhenzong** [comment]
Safari 版本是 10.1.2 (12603.3.8)

难道是新引入的，，2333333333。。。。

**Comment by qq645381995** [comment]
@zhenzong    zhNowAfter7  这个你可以说说你是怎么封装的？

**Comment by zhenzong** [comment]
没有封装啊，用的moment库
`const zhNowAfter7 = moment().locale('zh-cn').utcOffset(8).add(7, 'days');`

**Comment by qq645381995** [comment]
好吧 高看你了  你不会 
```
const zhNowAfterDays =(day)=>{
         retunrn moment().locale('zh-cn').utcOffset(8).add(day, 'days');
}
```

**Comment by zhenzong** [comment]
额，有需要的话，就自己抽个方法。

**Comment by zhenzong** [comment]
@qq645381995  额，需要的话，就自己抽出一个方法。

@benjycui 是不是可以考虑一下兼容一下这种问题呀？不过，antd和react-component里的Calendar都需要改了。

**Comment by benjycui** [comment]
> @benjycui 是不是可以考虑一下兼容一下这种问题呀？不过，antd和react-component里的Calendar都需要改了。

Nope, see: https://discussions.apple.com/thread/7732774?start=0&tstart=0

![image](https://user-images.githubusercontent.com/3580607/29052583-a4c903a2-7c1d-11e7-9ff7-b133c78e89fe.png)

It is not worth doing so.
