### ISSUE TITLE
Dropdown items 过多时可以添加滚动条么

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#47826]
注意到 Dropdown 的 item 是用 Menu 实现的，但是内容过多时，能否和 Cascader 一样，可以固定弹出高度，出现滚动条？

<img width="1579" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/5aaeb7bb-37a1-492e-b68e-1d54c587b2e8">

出现滚动条（类似这种效果）： 

<img width="433" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/7515cb98-23cb-4c76-b2a2-787940f98e7a">

**Comment by zystudios** [comment]
可以自己写style，children里面包一层，设置maxHeight和overflow即可

**Comment by Dysas** [comment]
What about Dropdown.Button items children container height? How to control it's height?
