### ISSUE TITLE
Input 输入框中文输入法

### ISSUE THREAD

**Issue by MaoMervyn** [ant-design/ant-design#47828]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-4-24-15-forked-hwhf86)

### Steps to reproduce

看控制台输出结果
![image](https://github.com/ant-design/ant-design/assets/40554125/7b60e374-c52e-4f19-abb6-5a98083bf1b1)

### What is expected?

基于onCompositionStart onCompositionEnd防止中文输入高频触发onChange，第一次输入正常，onCompositionEnd正常触发一次；
但是，再次输入，仅触发onCompositionStart，不再触发onCompositionEnd……

### What is actually happening?

onCompositionStart、onCompositionEnd依次正常触发

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
因为你 `value` 锁定受控，导致无论输入什么都会被强制改回去。所以 `onCompositionEnd` 不会触发：
1. 输入中文，此时 `value` state 是 `undefined`，所以是非受控状态，可以任意收入。
2. 输入中文完毕，`setValue` 把 `value` 改变。
3. 之后输入任何中文，因为不会调用 `setValue` 把 `value` 改变，所以 Input 会不断被强制设置回 `value`

可以去了解一下受控和非受控的概念，受控时始终需要保持同步哈~

ref: https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

**Comment by MaoMervyn** [comment]
邮件已收到，谢谢。

**Comment by xmsz-stu** [comment]
> 因为你 `value` 锁定受控，导致无论输入什么都会被强制改回去。所以 `onCompositionEnd` 不会触发：
> 
> 1. 输入中文，此时 `value` state 是 `undefined`，所以是非受控状态，可以任意收入。
> 2. 输入中文完毕，`setValue` 把 `value` 改变。
> 3. 之后输入任何中文，因为不会调用 `setValue` 把 `value` 改变，所以 Input 会不断被强制设置回 `value`
> 
> 可以去了解一下受控和非受控的概念，受控时始终需要保持同步哈~
> 
> ref: https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components

我用原生的input也是这个表现，但是不是很理解，有没有相关的分析文章推荐

**Comment by MaoMervyn** [comment]
邮件已收到，谢谢。
