### ISSUE TITLE
使用基于vite的remix创建app，引入antd/es/locale/zh-CN，提示Cannot use import statement outside a module

### ISSUE THREAD

**Issue by xihayouyi** [ant-design/ant-design#47824]
### Reproduction link

[https://github.com/xihayouyi/demo.git](https://github.com/xihayouyi/demo.git)

### Steps to reproduce

1)npm install
2)npm run dev
3)浏览器访问http://localhost:3000

### What is expected?

日期组件(DatePicker)的占位文字可以显示中文

### What is actually happening?

启动app后，在浏览器中打开页面，提示错误
import Pagination from "rc-pagination/es/locale/zh_CN";
SyntaxError: Cannot use import statement outside a module

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | macOS Monterey12.5 |
| Browser | Chrome108.0.5359.98 |

---
如果由引入antd/es/locale/zh_CN，改为引入antd/locale/zh_CN,虽然不报错了，但日期组件的占位文字显示的还是英文，应该显示中文才对。

**Comment by zombieJ** [comment]
`Cannot use import statement outside a module` 一般是由于你引入的框架没有把 `node_modules` 中的 es 代码进行编译导致的，这和 antd 本身没有关系。可以去查看一下对应的框架文档，或者其 github issue 提问哈~
