### ISSUE TITLE
期望 Transfer 的值能支持 number 类型，目前只有 string 类型，应和 Table 的 rowSelection 的 selectRowKeys 类型一致

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#47838]
### Reproduction link

[https://ant.design/components/transfer-cn](https://ant.design/components/transfer-cn)

### Steps to reproduce

-----

### What is expected?

-----

### What is actually happening?

-----

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
先和 Table 保持一致
