### ISSUE TITLE
InvalidStateError: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.

### ISSUE THREAD

**Issue by BatuhanW** [ant-design/ant-design#47833]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-s4krx5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltn2h6ey00063b6fp47j59vr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltn2h6ey00023b6fn0t5uq25%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltn2h6ey00033b6fuxueyhsy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltn2h6ey00053b6fscv779tu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltn2h6ey00023b6fn0t5uq25%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltn2h6ey00013b6fov3beive%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A20%257D%255D%257D%255D%252C%2522id%2522%253A%2522cltn2h6ey00023b6fn0t5uq25%2522%252C%2522activeTabId%2522%253A%2522cltn2h6ey00013b6fov3beive%2522%257D%252C%2522cltn2h6ey00053b6fscv779tu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltn2h6ey00043b6fkh3f99cv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522cltn2h6ey00053b6fscv779tu%2522%252C%2522activeTabId%2522%253A%2522cltn2h6ey00043b6fkh3f99cv%2522%257D%252C%2522cltn2h6ey00033b6fuxueyhsy%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltn2h6ey00033b6fuxueyhsy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Just use input with type = email.

`<Input type="email" />`

### What is expected?

It shouldn't fail.

### What is actually happening?

Throws error:

```
InvalidStateError: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.
```

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18 |
| System | Mac |
| Browser | Chrome |

---
I think it's originated from here: https://github.com/react-component/input/pull/65/files#r1519869871

**Comment by mendahu** [comment]
I just ran into this today too. I did a deploy on Friday without issue and haven't changed versions in my `package.json` since then, but if I reinstall the package now I hit this error.

Can workaround by setting type to `text` but this may not meet accessibility guidelines.

**Comment by zombieJ** [comment]
Let me check on this.

**Comment by dhwaj1902** [comment]
When are we releasing this change? Have builds pending.
