### ISSUE TITLE
通过ConfigProvider全局设置了locale=zh_CN,但日期组件的占位文字仍然显示英文

### ISSUE THREAD

**Issue by xihayouyi** [ant-design/ant-design#47840]
### Reproduction link

[https://github.com/xihayouyi/demo.git](https://github.com/xihayouyi/demo.git)

### Steps to reproduce

1)npm install
2)npm run dev
3)浏览器访问http://localhost:3000

### What is expected?

通过ConfigProvider设置locale=zh_CN后，日期组件的占位文字显示中文

### What is actually happening?

日期组件的占位文字显示英文

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | macOS Monterey12.5 |
| Browser | Chrome108.0.5359.98 |

<img width="640" alt="image" src="https://github.com/ant-design/ant-design/assets/5661020/57fdd9de-bab1-4920-a6f5-66edb4894d29">
<img width="396" alt="image" src="https://github.com/ant-design/ant-design/assets/5661020/cc1bf469-3332-412a-af53-96c7051289b5">

**Comment by nova1751** [comment]
Could you provide a working example in sites like CodePen?

**Comment by zombieJ** [comment]
Since we do not use remix, we can help less on this. Pls feel free to open issue to framework instead.

**Comment by afc163** [comment]
ConfigProvider 无法在服务端和客户端共享 context，这个事情还挺麻烦的。

**Comment by xihayouyi** [comment]
> ConfigProvider 无法在服务端和客户端共享 context，这个事情还挺麻烦的。现在的解法只能是只在客户端用 ConfigProvider

ConfigProvider可以在服务端使用，[demo](https://github.com/xihayouyi/demo2.git)

**Comment by zombieJ** [comment]
> ConfigProvider 无法在服务端和客户端共享 context，这个事情还挺麻烦的。现在的解法只能是只在客户端用 ConfigProvider

Case 不太一样。这里是只需要中文 `locale`，因而 ConfigProvider 的 `context` 是静态化的，不需要跨端共享。只要确保服务端和客户端都有这个就行了。

> 源问题中是把代码编译成了esm，ConfigProvider配置了locale但不起作用，但如果把代码编译成cjs，ConfigProvider就有作用，[这个demo是可以的](https://github.com/xihayouyi/demo2.git)

Nice catch. 这么看应该是 `root.tsx` 中填充的 ConfigProvider 和 DatePicker 实际消费的 ConfigProviderContext 不是同一个实例。可能是一个走了 esm，另一个仍然是 cjs。
