### ISSUE TITLE
ConfigProvider 能否增加配置形态变体呢？

### ISSUE THREAD

**Issue by HaceraI** [ant-design/ant-design#47842]
### What problem does this feature solve?

变体的功能很棒！
不过目前每一次使用都需要单独配置，每个组件也需要单独去配置，如果有地方漏了可能会造成风格不统一，能否在 ConfigProvider 内增加配置所有组件变体的功能呢？

### What does the proposed API look like?

```javascript
<ConfigProvider locale={zh_CN} variant="filled">
  <AntdApp>
    {children}
  </AntdApp>
</ConfigProvider>
```

**Comment by HaceraI** [comment]
我来尝试一下添加这个api

**Comment by MadCcc** [comment]
Form 可以使用 `variant` 统一配置表单内输入组件的变体，看看是否满足需求？

**Comment by HaceraI** [comment]
可以的，我后面想了下，基本上用到的`variant`组件都会二次封装一下，直接在封装那处理好了.  谢谢
