### ISSUE TITLE
table 加了virtual 之后横向滚动条变的很短，倒置要拉很久才能到右边

### ISSUE THREAD

**Issue by xian107** [ant-design/ant-design#47845]
### Reproduction link

[https://ant-design.gitee.io/components/table-cn#components-table-demo-virtual-list](https://ant-design.gitee.io/components/table-cn#components-table-demo-virtual-list)

### Steps to reproduce

滚动条长度太短

### What is expected?

滚动条长度正常

### What is actually happening?

滚动条长度太短

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chome |

完全复制的官网例子
![db3149511134b96edd552d90d328460](https://github.com/ant-design/ant-design/assets/13252682/64df810b-ca99-40d1-b233-6fec0b7a6cf8)

**Comment by MadCcc** [comment]
已经修复过，请删除 lock 文件重新安装依赖试试
