### ISSUE TITLE
Dropdown 多层级修改方向

### ISSUE THREAD

**Issue by hyl1374961656** [ant-design/ant-design#47844]
### What problem does this feature solve?

如果元素贴右边的话，箭头方向是向右但是实际展开位置是左边
![image](https://github.com/ant-design/ant-design/assets/56420042/0ee6fdeb-2c2c-4503-8109-f56d2123667d)

https://codesandbox.io/p/sandbox/duo-ji-cai-dan-antd-5-15-1-forked-8r2s8t?file=%2Fdemo.tsx%3A62%2C14

### What does the proposed API look like?

增加方向调整

**Comment by afc163** [comment]
这是符合预期的，UI 预设是向右展开，但空间不够适配到左边。原生 UI 也是类似的行为：

<img width="1495" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/98708689-c360-4fc7-a208-20fbf7246dc1">
