### ISSUE TITLE
在 nextjs 下使用 css 变量会产生两段一样的 css 变量样式代码

### ISSUE THREAD

**Issue by ponjs** [ant-design/ant-design#47849]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/stackblitz-starters-p5cwnq?file=app%2FAntdRegistry.tsx)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/39897744/9ec177a9-3086-4ad5-8866-32562b79e3fb)

### What is expected?

去除重复的样式代码

### What is actually happening?

生成了重复样式代码

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18 |
| System | Windows11 |
| Browser | Chrome 122.0.6261.112 |

**Comment by MadCcc** [comment]
这个是刻意的。下面的是 SSR 生成的，保证首屏样式正常；上面的是运行时注入的，是动态的样式，需要覆盖 SSR 样式。
可以在运行时延迟删除 SSR 的样式，但之前没有找到一个好的时间点，所以就先留着了，不会有什么副作用。
