### ISSUE TITLE
Pagination组件是否支持自定义各个组件排列的顺序？

### ISSUE THREAD

**Issue by JunHooo** [ant-design/ant-design#47841]
### What problem does this feature solve?

可以自由配置总条数，切换上下页，当前页数等组件的排列顺序，目前增加这些组件后排列顺序是不变的

### What does the proposed API look like?

是否可以像elementUi一样支持layout属性的设置，可以自由调整顺序

**Comment by afc163** [comment]
保持一致的设计规范很重要，除非默认的顺序很不合理，我们眼下不倾向去开放这个配置。
