### ISSUE TITLE
Modal 自定义位置希望可以支持 style.bottom 等样式属性

### ISSUE THREAD

**Issue by IceLeach** [ant-design/ant-design#47851]
### What problem does this feature solve?

参考官网 https://ant.design/components/modal-cn#components-modal-demo-position 自定义位置时发现只支持`style.top`属性，bottom,left,right 都是不生效的。

https://codesandbox.io/p/sandbox/zi-ding-yi-wei-zhi-antd-5-15-1-forked-68vjjf?file=%2Fdemo.tsx%3A33%2C26

1、在一些情况下对话框需要相对其他位置定位。

2、使用`style`定位但只支持`top`属性感觉很奇怪。

### What does the proposed API look like?

```typescript
     <Modal style={{ bottom: 20 }}>
        <p>some contents...</p>
        <p>some contents...</p>
        <p>some contents...</p>
      </Modal>
```

**Comment by MadCcc** [comment]
加上 `positon: absolute` 或者 `fixed`。
