### ISSUE TITLE
Upload组件disabled后，下载按钮也被disabled了

### ISSUE THREAD

**Issue by icarusysuper** [ant-design/ant-design#47858]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ilf5ea?file=demo.tsx)

### Steps to reproduce

1、4.x版本的官网照片墙例子，点击“在 Stackblitz 中打开”
2、Upload加入以下属性
disabled
showUploadList={{
  showPreviewIcon: true,
  showRemoveIcon: true,
  showDownloadIcon: true,
}}
3、下载图标被禁止了（不期望的现象）

### What is expected?

下载图标能够点击

### What is actually happening?

下载图标不能点击

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 18.x |
| System | win10 |
| Browser | chrome122 |

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/issues/46171

**Comment by MadCcc** [comment]
抱歉，v4 已经过了维护期，我们一般不会去发新的 patch
欢迎升级到 v5，这个问题在 v5 已经解决

**Comment by icarusysuper** [comment]
@MadCcc bug类也不发补丁吗 :-(
