### ISSUE TITLE
Dropdown 下拉菜单能否支持 maxHeight 最大高度配置项

### ISSUE THREAD

**Issue by songhongkai99** [ant-design/ant-design#47855]
### What problem does this feature solve?

日常使用中经常会遇到过高的 Dropdown，期望能限制高度同时支持内部滚动，此时为了限制最大高度，直接使用 overlayStyle 或者使用样式覆盖都不是特别优雅，并且很容易导致投影样式被剪裁

### 示例

```tsx
<Dropdown

  /* 方式一: 为了局部滚动，这样会剪裁掉 menu 的投影样式 */
  overlayStyle={{ maxHeight: '200px', overflow: 'auto' }}

  /* 方式二: 这样不会剪裁掉 menu 的投影样式, 但是 cloneElement 已标记为过时的 api ， 并且复杂度较高*/
  dropdownRender={menu => (
    <>
      {/* TODO: cloneElement 已标记为过时的 api */}
      {cloneElement(menu as React.ReactElement, {
        style: {
          maxHeight: '200px',
          overflow: 'auto',
        },
      })}
    </>
  )}
>
  ...
</Dropdown>
```
### What does the proposed API look like?

```tsx
<Dropdown maxHeight="300px" ... />

// 或者扩展内部的 menu 样式 区别于 overlayStyle，将样式扩展至生成的 menu ul 节点上

<Dropdown menuStyle={{maxHeight: 200, overflow: 'auto'}} ... />
```

**Comment by Roxannej** [comment]
这种问题，其实对大部分人而言，应该还是会选择用overlayStyle改，里面描述的投影样式被裁剪，也没有给出一个例子，为了控制最大高度直接加一个新的参数是合理呢？还是不合理呢？

**Comment by songhongkai99** [comment]
> 这种问题，其实对大部分人而言，应该还是会选择用overlayStyle改，里面描述的投影样式被裁剪，也没有给出一个例子，为了控制最大高度直接加一个新的参数是合理呢？还是不合理呢？

您好，刚才提交的不够完善，表述的不清楚，刚才更新了下 问题描述

**Comment by MadCcc** [comment]
推荐还是通过 overlayStyle 修改，加上 `max-height` 也需要配合 `overflow` 使用。

**Comment by songhongkai99** [comment]
> 推荐还是通过 overlayStyle 修改，加上 `max-height` 也需要配合 `overflow` 使用。

配合 overflow 会剪切掉 menu 的投影样式，感觉不是很友好，期望能加一个 menuStyle 来灵活配置内部样式
