### ISSUE TITLE
Passing a Button to a Popconfirm "indirectly" results in "Warning: findDOMNode is deprecated in StrictMode."

### ISSUE THREAD

**Issue by luke-m** [ant-design/ant-design#47863]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-tznmza?file=package.json)

### Steps to reproduce

Open the console

### What is expected?

No warning

### What is actually happening?

Warning

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | MacOS Sonoma 14.2 |
| Browser | Chrome Version 122.0.6261.112 (Official Build) (arm64) |

---
Passing a button "directly" works. With that I mean the following:

```
<Popconfirm title="Hello">
  <Button>Click me</Button>
</Popconfirm>
```

Only when you wrap the button into its own component, you see the warning.

**Comment by afc163** [comment]
Try React.forwardRef in your own component to pass ref.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/43064#issuecomment-1595739073
