### ISSUE TITLE
cannot tab inside <Dropdown /> when `items` is falsey

### ISSUE THREAD

**Issue by theiliad** [ant-design/ant-design#47868]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wnfmvd?file=demo.tsx)

### Steps to reproduce

1. Create a dropdown
2. Do not include `items`
3. Use `dropdownRender` without using its `menu` parameter

### What is expected?

You should still be able to tab through the dropdown contents

### What is actually happening?

Dropdown closes after tabbing

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18 |
| System | Mac Sonoma |
| Browser | Chrome 122.0.6261.112 |

---
I believe this is due to this line
https://github.com/react-component/dropdown/blob/7b9fb71c3ad13695a9aaae8b5e6ef7177c339a8a/src/hooks/useAccessibility.ts#L54-L55

**Comment by theiliad** [comment]
While the auto-close logic does have some use, I think ultimately you still need to expose a prop like `allowTabbingInside` where the user can fully control this behaviour

**Comment by afc163** [comment]
Try Popover instead of Dropdown in your case.
