### ISSUE TITLE
新版本加了scrollbar-color属性后，自定义滚动条样式不生效

### ISSUE THREAD

**Issue by xjmforweb** [ant-design/ant-design#47862]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-qff6t5-9dvlsk?file=demo.jsx)

### Steps to reproduce

首先设置自定义的全局滚动条样式。例子里两个table，第一个重置了table的scrollbar-color样式，第二个保持不动，第二个样式不生效

### What is expected?

第二个table也拥有自定义滚动条样式

### What is actually happening?

第二个table还是原始样式

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2 |
| System | windows |
| Browser | 谷歌最新版 |

**Comment by MadCcc** [comment]
参考 https://github.com/ant-design/ant-design/issues/47592#issuecomment-1972831827

**Comment by xjmforweb** [comment]
> 参考 [#47592 (comment)](https://github.com/ant-design/ant-design/issues/47592#issuecomment-1972831827)

我的stackblitz里就这么做的，没有更好的办法了吗

**Comment by MadCcc** [comment]
想要兼容旧版本浏览器就先重置 `scrollbar-color` 样式，如果只考虑新版浏览器，建议直接覆盖 `scrollbar-color`
