### ISSUE TITLE
System default theme for scroll bar in Select with "popupMatchSelectWidth={false}"

### ISSUE THREAD

**Issue by fmohtadi99** [ant-design/ant-design#47867]
### Reproduction link

This is a private project with no public URL

### Steps to reproduce

- Import ``Select`` component in the project
- Set the prop ``popupMatchSelectWidth={false}``

### What is expected?

Antd theme for scroll bar

### What is actually happening?

System default theme for scroll bar

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | React v18 |
| System | Windows 11 x64 |
| Browser | Google Chrome |

---
When I set the prop "popupMatchSelectWidth" for the component "Select" to "false", style of the scroll bar is set to the system default theme.

**Comment by afc163** [comment]
@fredbellinder It is intented behaviour.
