### ISSUE TITLE
onSelect method not working in TimePicker

### ISSUE THREAD

**Issue by salekin02** [ant-design/ant-design#47871]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-nhc7sq?file=demo.tsx)

### Steps to reproduce

check the console of shared codespace. onSelect is not triggering 

### What is expected?

expected to receive value on selecting any time from list

### What is actually happening?

there is noting showing up inside the onSelect

| Environment | Info |
| --- | --- |
| antd | 5.15.1 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
[FAQ: Can I use internal API which is not documented on the site?](https://ant.design/docs/react/faq#can-i-use-internal-api-which-is-not-documented-on-the-site)

`onSelect` is a internal API which used for Calendar to use take value from PickerPanel. It's not an official API.  You can use `onCalendarChange` instead.

**Comment by salekin02** [comment]
@zombieJ it is listed on the API table of TimePicker component.
https://ant.design/components/time-picker#api

**Comment by zombieJ** [comment]
thanks for reminding. TimePicker was originally not the same underlying component as DatePicker. After refactoring, there are legacy APIs that are not aligned. I will try to make them compatible.
