### ISSUE TITLE
Trigger onChange when first value is selected on range picker component

### ISSUE THREAD

**Issue by miikaisoranta** [ant-design/ant-design#47877]
### What problem does this feature solve?

Right now triggers when both values are set. This makes it hard to set hard limit for the selection e.q max 4 months from selected first value. This is useful when using range picker on fixed contract length, in a project length picker etc, where user needs to be limited into certain time range.

### What does the proposed API look like?

This is more like feature request from non coding person.

**Comment by zombieJ** [comment]
Pls follow the official doc:
* [Demo: Select range dates in 7 days](https://ant.design/components/date-picker#components-date-picker-demo-select-in-range)
* [`onCalendarChange` to get update when select on half](https://ant.design/components/date-picker#rangepicker)
