### ISSUE TITLE
Badge 独立使用时无法在垂直方向与其他组件/文字对齐

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#47875]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/du-li-shi-yong-antd-5-15-2-kpjn9p?file=%2Fdemo.tsx%3A11%2C7-19%2C9)

### Steps to reproduce

将 Badge 单独放于文字的右侧，并用 Space 组件来尝试垂直居中。

```jsx
<Space>
  <span>文字</span>
  <Badge count={999} />
</Space>
```

### What is expected?

Badge 能通过 Space 组件与其他元素垂直居中对齐

### What is actually happening?

Badge 垂直方向总是与文字对不齐，位置偏下

![image](https://github.com/ant-design/ant-design/assets/5836790/2609e95b-0b2a-4e3e-a49f-594860a224b4)

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | macOS |
| Browser | Chrome 121 |

**Comment by MadCcc** [comment]
baseline 对齐，看起来会偏下有需要可以魔改一下。
