### ISSUE TITLE
DatePicker备选日期面板不可自定义, 选择日期困难

### ISSUE THREAD

**Issue by FloaJa** [ant-design/ant-design#47876]
### What problem does this feature solve?

https://stackblitz.com/edit/react-efhdbf?file=demo.tsx  如demo所示, 选择长期之后, 再选择起期, 选择日期面板在9999年, 想要选择当前日期附近时会很困难

### What does the proposed API look like?

pannelHolder: (value) => ({ 面板类型: ..., 面板显示时间: ... })
大概应该是在面板弹出前触发, 根据返回值控制显示面板的类型和时间

**Comment by zombieJ** [comment]
用 `defaultPickerValue` 即可
