### ISSUE TITLE
Modal afterClose does not pass event

### ISSUE THREAD

**Issue by SamyukthaJ** [ant-design/ant-design#4787]
afterClose function does not pass the event argument. 
Similarly Popconfirm onConfirm, onCancel does not pass the event.

event.stopPropagation() needed to be called on both the above handlers but event not passed.

**Comment by ddcat1115** [comment]
`afterClose` just indicates that the closing action has been completed, you can use `onOk` `onCancel` in Modal.

And the event argument has been left out in these handlers:

- Modal: `onOk` 
- Popconfirm: `onConfirm ` `onCancel `

Could you give us a PR to fix it? 😃

**Comment by afc163** [comment]
@SamyukthaJ
