### ISSUE TITLE
click-triggered Popover not closing when ESC pressed

### ISSUE THREAD

**Issue by theiliad** [ant-design/ant-design#47887]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-w61nan)

### Steps to reproduce

1. Create a popover
2. Add `trigger={['click']}`
3. Open
4. Press ESC

### What is expected?

Popover should close. This'd be consistent with `<Select />`, `<Modal />` and `<Dropdown />`

### What is actually happening?

It stays open, and focus moves to button

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18 |
| System | Mac Sonoma |
| Browser | Chrome 122.0.6261.112 |

**Comment by theiliad** [comment]
This could also be controlled through a prop, e.g. `closeOnEscape`

**Comment by afc163** [comment]
Closed by https://github.com/ant-design/ant-design/pull/47928
