### ISSUE TITLE
add open() function in `Select` ref

### ISSUE THREAD

**Issue by theiliad** [ant-design/ant-design#47888]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-baaftf?file=demo.tsx)

### Steps to reproduce

1. Add a `<Select />` to your page
2. Grab its ref
3. Inspect the contents of ref.current

### What is expected?

There should be an option to open the select through this ref.

Opening it otherwise will require either:
- binding the Select's `open` prop to the state
- or
- using `defaultOpen` and `key` to re-render the Select
- or
- querying the select's trigger element in the dom, and performing a synthetic click on it

This is not ideal in large-scale UIs, because you wouldn't want the simple opening of a Select to have to go through React's rendering & lifecycle process. It should simply be an action performed through vanilla JS, similar to how `focus()` works.

Consider a table of 1000 rows with a Select in each row.
Modifying the open or defaultOpen props for Selects in order to open them will mean React updating all 1000 rows.
This is not ideal, a more scalable solution is to perform this outside of React's lifecycle

This allows for better performance in larger apps.

Antd already follows a similar approach for rendering the Select's dropdown, where after opening the select, a separate dropdown element is appended inside document.body... I believe it's called `popupContainer`

### What is actually happening?

You'd have to implement the opening manually and do it through the React lifecycle.

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18 |
| System | Mac Sonoma |
| Browser | Chrome 122.0.6261.112 |

---
**Even though this is a new piece of work, I filed it as a bug since the currently available methods to open selects are very old-school, and do not optimize for performance (specially in larger applications)**

Consider a table of 1000 rows with a Select in each row.
Modifying the `open` or `defaultOpen` props for Selects in order to open them will mean React updating all 1000 rows.
This is not ideal, a more scalable solution is to perform this outside of React's lifecycle

**Comment by linxianxi** [comment]
I don't think adding an open method to Select is a good way, you can implement it yourself
```
const CustomSelect = React.forwardRef((props: SelectProps, ref) => {
  const [open, setOpen] = React.useState(false);
  const selectRef = useRef<RefSelectProps>(null);

  React.useImperativeHandle(ref, () => ({
    ...selectRef.current,
    open: () => setOpen(true),
  }));

  return (
    <Select
      {...props}
      ref={selectRef}
      open={open}
      onDropdownVisibleChange={setOpen}
    />
  );
});
```

**Comment by afc163** [comment]
You should use `open` and `onOpenChange`.
