### ISSUE TITLE
input: TextArea in Search

### ISSUE THREAD

**Issue by iuiu34** [ant-design/ant-design#47885]
### What problem does this feature solve?

In docs, we have Search, and TextArea. But not a  combination of those.
Where Search has a dynamic, multiline size.
I think, this usage is very common in chats.
And due llm hype, the chats popularity has grown.

### What does the proposed API look like?

<Search
 autoSize={{minRows: 2, maxRows: 6}}
/>

**Comment by afc163** [comment]
> Where Search has a dynamic, multiline size.

I don't think this is a reasonal UI component. You can use TextArea.

**Comment by iuiu34** [comment]
@afc163 
in a chat, common case is TextArea+Button. With the button inside the area. Or stacked, in aesthetic way,
Why, you say, this has to be done custom?

But, in the scenario of a search, we have the antd native Search.
Which is basically, an Input + Button.

Which arguments justify the 2nd, that doesn't justify the first?

thanks

**Comment by afc163** [comment]
Did you mean this input box in chat app?

<img width="836" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8fbf9994-5d4f-4af4-9f27-4b6d7c598f17">

I don't treat it as a Search component. It is TextArea and Button IMO. You can try https://pro-chat.antdigital.dev/en-US/components/pro-chat if you are looking for a built-in component.
