### ISSUE TITLE
Image组件可以通过代码打开一张图片吗？以便实现相册的预览功能，现在得手工点击一下才能预览

### ISSUE THREAD

**Issue by offeeyang** [ant-design/ant-design#47896]
### What problem does this feature solve?

图片自动预览，替代一些相册组件。

### What does the proposed API look like?

autoOpenPreviewImage

**Comment by Wxh16144** [comment]
轮播图？

**Comment by afc163** [comment]
Image 有提供 preview.visible 属性，可以控制预览窗口。https://ant-design.antgroup.com/components/image-cn#previewtype

**Comment by offeeyang** [comment]
Thanks, it works~
