### ISSUE TITLE
Ant-d V4 Autocomplete 选中无法展示label

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [ant-design/ant-design#47894]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/basic-usage-antd-4-24-15-forked-qtd7wm?file=%2Fdemo.js%3A15%2C6)

### Steps to reproduce

Autocomplete options配置中包含value和label属性时，选中后无法显示对应的label

### What is expected?

希望可以展示label，因为value我们一般都会配置成数据ID，UI上展示ID是没有意义的，ID目前只是为了和后台交互。

### What is actually happening?

Autocomplete options配置中包含value和label属性时，选中后无法显示对应的label

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 16.9.0 |
| System | Win10 |
| Browser | Version 122.0.6261.95 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
<img width="412" alt="截屏2024-03-15 17 04 21" src="https://github.com/ant-design/ant-design/assets/5378891/80dadf0b-bf71-4478-a174-445b8f6816b6">

你要展示 `label` 应该用 Select 动态加 `option`，AutoComplete 是输入框不是选择器。

**Comment by afc163** [comment]
> 你要展示 label 应该用 Select 动态加 option，AutoComplete 是输入框不是选择器。

+1

**Comment by JinHe-PerkinElmer** [comment]
> <img alt="截屏2024-03-15 17 04 21" width="412" src="https://private-user-images.githubusercontent.com/5378891/313130501-80dadf0b-bf71-4478-a174-445b8f6816b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTQwMDksIm5iZiI6MTcxMDQ5MzcwOSwicGF0aCI6Ii81Mzc4ODkxLzMxMzEzMDUwMS04MGRhZGYwYi1iZjcxLTQ0NzgtYTE3NC00NDViOGY2ODE2YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMDkwODI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE0YTExNzkxNDhiYWMwNjM5MGMzYzMwMTlmZGQ3NmUxODU2NzA5OGEzYmRjZTdiNDEyNTYzNWFmYTU0YmY5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P3pI6lDYrHj44AdCj9vDtxyZaXuEKB1Wm-uWJg8Woz4">
> 你要展示 `label` 应该用 Select 动态加 `option`，AutoComplete 是输入框不是选择器。

我知道，这是正常Case, 使用没有问题。
但是，我们有一个需求是这样的：一个input同时支持可输/可选。所以我们V3是用AutoComplete做了二次封装。现在发现功能没了。。。

**Comment by afc163** [comment]
最好把你的需求详细展开说说。

**Comment by JinHe-PerkinElmer** [comment]
> 最好把你的需求详细展开说说。

主要问题就是Autocomplete，options配置了 { value, label }，选择的时候是默认显示value的，无法显示label。刚才本来想通过Children的input value去自定义显示内容，好像没成功。不行只能自己写一个了，先这样吧，周末愉快。

**Comment by afc163** [comment]
我是问你的原始需求，具体是什么业务场景的**什么**输入框需要同时支持可输/可选，又在希望展示 label 而不是 value。

**Comment by afc163** [comment]
如果是多选你可以使用：https://ant.design/components/select-cn#select-demo-tags

**Comment by JinHe-PerkinElmer** [comment]
> 我是问你的原始需求，具体是什么业务场景的**什么**输入框需要同时支持可输/可选，又希望展示 label 而不是 value。另外这是单选还是多选？

原始需求其实是两个：就是输入时，1. 先调接口查询展示一个列表，供用户选择（这部分Select可满足）2. 如果列表没有匹配项，保留用户输入的结果（相当于新增一条记录，Autocomplete组件功能）
关于展示问题：为什么要展示Label而不是Value，因为value我们是我们和后台交互用的，一般都是id，显示出来没有意义，label才是用户能识别的有意义的名称。

**Comment by afc163** [comment]
> 保留用户输入的结果（相当于新增一条记录，Autocomplete组件功能）
用户输入的内容是 value 还是 label 呢？

**Comment by JinHe-PerkinElmer** [comment]
> > 保留用户输入的结果（相当于新增一条记录，Autocomplete组件功能）
> 
> 用户输入的内容是 value 还是 label 呢？

用户输入的是Label，新增成功后，后台会生成对应ID。

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-e2zkty?file=demo.tsx

tags + maxCount 感觉比较适配你的诉求。

```jsx
  <Select
    mode="tags"
    maxCount={1}
  />
```

**Comment by JinHe-PerkinElmer** [comment]
> https://stackblitz.com/edit/react-e2zkty?file=demo.tsx
> 
> tags + maxCount 感觉比较适配你的诉求。
> 
> ```js
>   <Select
>     mode="tags"
>     maxCount={1}
>   />
> ```

我明白你的意思，这是一个解决方案。实际上我已经参照autocomplete的定义，把输入、选择功能封装好了，正在调dropdown的UI。这样改，我只需要替换我们的common-lib中对应组件，不需要改其它使用的地方。

**Comment by KurumiRin** [comment]
> https://stackblitz.com/edit/react-e2zkty?file=demo.tsx
> 
> tags + maxCount 感觉比较适配你的诉求。
> 
> ```js
>   <Select
>     mode="tags"
>     maxCount={1}
>   />
> ```

可以实现可输/可选，但是更期望的不是tag这种ui表现。更接近于Select组件的搜索功能如果不选择option的话，输入框内容并不清楚，而是将当前输入的内容作为label和value，这里和动态添加options的区别在于用户不需要额外的点击动态创建的options行为。从观感上Auto Complete组件也接近这个需求，但是他的label并不作为输入框内容的展示，仅仅是options的展示

**Comment by JinHe-PerkinElmer** [comment]
> > https://stackblitz.com/edit/react-e2zkty?file=demo.tsx
> > tags + maxCount 感觉比较适配你的诉求。
> > ```js
> >   <Select
> >     mode="tags"
> >     maxCount={1}
> >   />
> > ```
> 
> 可以实现可输/可选，但是更期望的不是tag这种ui表现。更接近于Select组件的搜索功能如果不选择option的话，输入框内容并不清楚，而是将当前输入的内容作为label和value，这里和动态添加options的区别在于用户不需要额外的点击动态创建的options行为。从观感上Auto Complete组件也接近这个需求，但是他的label并不作为输入框内容的展示，仅仅是options的展示

其实主要问题是，项目中使用Autocomplete，很多场景都是Id+lable的模式，比如我的数据格式是这种：{ id: 1, label: 'name1' }, 然后绑定到组件value的值是对应的id，v3中是可以正常显示label的，v4不支持这种模式了。
所以自己写了一个组件实现autocomplete的可输可选，以及支持绑定id，显示对应的label。主要是为了兼容现有代码。

**Comment by KurumiRin** [comment]
> > > https://stackblitz.com/edit/react-e2zkty?file=demo.tsx
> > > tags + maxCount 感觉比较适配你的诉求。
> > > ```js
> > >   <Select
> > >     mode="tags"
> > >     maxCount={1}
> > >   />
> > > ```
> > 
> > 
> > 可以实现可输/可选，但是更期望的不是tag这种ui表现。更接近于Select组件的搜索功能如果不选择option的话，输入框内容并不清楚，而是将当前输入的内容作为label和value，这里和动态添加options的区别在于用户不需要额外的点击动态创建的options行为。从观感上Auto Complete组件也接近这个需求，但是他的label并不作为输入框内容的展示，仅仅是options的展示
> 
> 其实主要问题是，项目中使用Autocomplete，很多场景都是Id+lable的模式，比如我的数据格式是这种：{ id: 1, label: 'name1' }, 然后绑定到组件value的值是对应的id，v3中是可以正常显示label的，v4不支持这种模式了。 所以自己写了一个组件实现autocomplete的可输可选，以及支持绑定id，显示对应的label。主要是为了兼容现有代码。

我在用v5，似乎也不支持这种形式，想要实现类似需求至少需要用户额外做一步点击option的行为，mode tag本身ui表现就不符合需求了

**Comment by JinHe-PerkinElmer** [comment]
> > > > https://stackblitz.com/edit/react-e2zkty?file=demo.tsx
> > > > tags + maxCount 感觉比较适配你的诉求。
> > > > ```js
> > > >   <Select
> > > >     mode="tags"
> > > >     maxCount={1}
> > > >   />
> > > > ```
> > > 
> > > 
> > > 可以实现可输/可选，但是更期望的不是tag这种ui表现。更接近于Select组件的搜索功能如果不选择option的话，输入框内容并不清楚，而是将当前输入的内容作为label和value，这里和动态添加options的区别在于用户不需要额外的点击动态创建的options行为。从观感上Auto Complete组件也接近这个需求，但是他的label并不作为输入框内容的展示，仅仅是options的展示
> > 
> > 
> > 其实主要问题是，项目中使用Autocomplete，很多场景都是Id+lable的模式，比如我的数据格式是这种：{ id: 1, label: 'name1' }, 然后绑定到组件value的值是对应的id，v3中是可以正常显示label的，v4不支持这种模式了。 所以自己写了一个组件实现autocomplete的可输可选，以及支持绑定id，显示对应的label。主要是为了兼容现有代码。
> 
> 我在用v5，似乎也不支持这种形式，想要实现类似需求至少需要用户额外做一步点击option的行为，mode tag本身ui表现就不符合需求了

这要看你们具体用法了，如果只是简单的string类型搜索以及填充，现有控件应该还是能用的。数据结构复杂一点的，就不行了。提供一下我自定义组件（可输可选，支持id，选择的列表是调用后台接口的）的思路：
1,. HTML结构很简单，一个输入框+dropdown，dropdown位置通过input位置计算，定位到对应位置，position的位置建议以document作为参考系，防止父级元素定位的影响；
2.控制dropdown的显示隐藏，比如input focus/search的时候显示，blur/选择一个option后隐藏dropdown;
3, Id 支持。可以传入value formatter, 将id转换成对应的label显示。
整体完成下来，没有特别难处理的点，主要是细节比较多。

**Comment by hl33886** [comment]
我们也有这个需求。能支持显示label  
用select tags形式，本身就不符合单选UI

**Comment by JinHe-PerkinElmer** [comment]
> 我们也有这个需求。能支持显示label 用select tags形式，本身就不符合单选UI

是的，所以后来我自己写了这个控件，适配现有代码。实现思路不难，请看上边一条评论。
