### ISSUE TITLE
table中用了分页，我设置total设置45，但分页为10页

### ISSUE THREAD

**Issue by mlianghua** [ant-design/ant-design#4789]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by skordyr** [comment]
total是总的数量的意思,分页 = Math.ceil(total / pageSize)

**Comment by afc163** [comment]
Sorry, cannot find your problem: http://codepen.io/anon/pen/dNqWQQ?editors=001

**Comment by mlianghua** [comment]
你好，我是动态设置的，应该获取ajax数据，是异步的，先设置total为0， 获取到数据后重新设置为total:45,然后点击第五页的时候，出现6，7，8，9，10

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by mlianghua** [comment]
`import React from 'react';
import {Table, Icon} from 'antd';
import UserListStore1 from '../stores/UserListStore1';
import CommonUtils from '../utils/CommonUtils';
import '../App.css'


const columns = [{
    title:'用户名',
    dataIndex: 'name',
    key: 'name'
}, {
    title:'手机号码',
    dataIndex: 'mobile',
    key: 'mobile'
}, {
    title:'身份证',
    dataIndex:'cardId',
    key: 'cardId'
}, {
    title:'操作',
    key:'action',
    render: (text, record) => (
        <span>
            <a href="#"> 修改 </a>
            <span className="ant-divider" />
            <a href="#"> 查看 </a>
        </span>),
}];

function getUserData() {
    console.log("getUserData!");
    return {
        users:UserListStore1.getAll(),
        pagination:{
            current: getPage().pageNo,
            total: getPage().pageTotal,
            pageSize: getPage().pageSize
        },
        loading:false,
    };
}

function getPage() {
    var page = {};
    if (CommonUtils.isUndefined(UserListStore1.getPage())) {
        page.pageNo = 1;
        page.pageSize = 10;
        page.pageTotal = 0;
        return page;
    }

    page.pageNo = CommonUtils.isUndefined(UserListStore1.getPage().pageNo) ? 1:UserListStore1.getPage().pageNo;
    page.pageTotal = CommonUtils.isUndefined(UserListStore1.getPage().pageTotal) ? 0: UserListStore1.getPage().pageTotal;
    page.pageSize = CommonUtils.isUndefined(UserListStore1.getPage().pageNum) ? 10 : UserListStore1.getPage().pageNum;

    return page;
}


var UserList = React.createClass({
    getInitialState: function () {
        return getUserData();
    },

    componentDidMount: function() {
        UserListStore1.addChangeListener(this._onChange);
        UserListStore1.fetchData(this.state.pagination.current - 1, 10);
    },

    componentWillUnmount: function() {
        UserListStore1.removeChangeListener(this._onChange);
    },

    getTableDataSource: function getTableDataSource(data,index) {
        var item = {};
        item.key = index + (this.state.pagination.current - 1) * 10;
        item.name = data.userNick;
        item.mobile = data.mobile;
        item.userId = data.userId;
        item.lastOrderTitle = data.lastOrderTitle;
        item.cardId = data.cardId;

        return item;
    },

    render: function () {
        var dataViewItems;
        if (CommonUtils.isUndefined(this.state.users)) {
            dataViewItems = [];
        } else {
            dataViewItems = this.state.users.map(this.getTableDataSource);
        }

        console.log(this.state.pagination);
        return (
            <div>
                <Table columns={columns}
                       rowKey={record => record.key}
                       dataSource={dataViewItems}
                       pagination={this.state.pagination}
                       loading={this.state.loading}
                       onChange={this.handleTableChange} />
            </div>
        );
    },

    _onChange: function() {
        this.setState(getUserData());
    },

    handleTableChange(pagination) {
        const pager = this.state.pagination;
        pager.current = pagination.current;

        this.setState({
            pagination:pager,
            loading:true,
        });

        UserListStore1.fetchData(pager.current - 1, 10);
    },
});

module.exports = UserList;

`

**Comment by afc163** [comment]
你这样贴代码我是看不出问题的，建议用 codepen 重现出来。

**Comment by mlianghua** [comment]
我的是一个工程，不是一个文件。

**Comment by afc163** [comment]
按照你描述的情况仍然没有重现：http://codepen.io/anon/pen/egPZbW?editors=001

---

建议阅读下 [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)。

**Comment by mlianghua** [comment]
看来你没有看我的问题，我是使用了table, 组件里面自带的分页，动态设置分页的总数，出现问题。
<Table columns={columns}
                       rowKey={record => record.key}
                       dataSource={dataViewItems}
                       pagination={this.state.pagination}
                       loading={this.state.loading}
                       onChange={this.handleTableChange} />

**Comment by afc163** [comment]
```diff
    handleTableChange(pagination) {
-       const pager = this.state.pagination;
+      const pager = { ...this.state.pagination };
        pager.current = pagination.current;

        this.setState({
            pagination:pager,
            loading:true,
        });

        UserListStore1.fetchData(pager.current - 1, 10);
    },
```

**Comment by afc163** [comment]
还是没有重现：http://codepen.io/anon/pen/MJPyNp?editors=0010

建议最好花点时间把具体的问题抽取并重现出来，否则我没有你本地的环境和数据，只能在这里猜来猜去。

**Comment by afc163** [comment]
@mlianghua ping

**Comment by afc163** [comment]
无法重现也没法修复，给出重现后再 reopen 吧，感谢理解。

**Comment by 1120340041** [comment]
http://codepen.io/kevinhb/pen/pPZXjb
你好，这里我把table的pagination中的total设置了240，但是为什么分页出现却是16？
