### ISSUE TITLE
Countdown value type and docs value type mismatched

### ISSUE THREAD

**Issue by AO19** [ant-design/ant-design#47905]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/countdown-value-zhcmvm?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce

The docs say "value	Set target countdown time	number | dayjs	-	"
But the type definitions say something else.

### What is expected?

No warnings or errors.

### What is actually happening?

I get the warning: Type 'Dayjs' is not assignable to type 'valueType | undefined'.

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | 14.3.1 (23D60) |
| Browser | Chrome 122.0.6261.112 |

**Comment by afc163** [comment]
```diff
- const deadline = dayjs().add(1, "hour");
+ const deadline = dayjs().add(1, "hour").date();
```

**Comment by afc163** [comment]
Wrong documentation.
