### ISSUE TITLE
Select组件 value属性不接受number类型数值(TS2322: Type 'number' is not assignable to type 'string'.)，以前是可以的，而且文档上也是接受的，请问是什么原因

### ISSUE THREAD

**Issue by lesleyChen2016** [ant-design/ant-design#47906]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9?)

### Steps to reproduce

无

### What is expected?

可以接受value为number数值

### What is actually happening?

目前只接受string

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by zystudios** [comment]
![image](https://github.com/ant-design/ant-design/assets/29728228/67d281cf-a402-4426-a41a-ebc80f328e7b)
拿官方例子试了下没什么问题
https://stackblitz.com/edit/react-ga6edv?file=demo.tsx

**Comment by zombieJ** [comment]
你的 Codesandbox 里没有 Select。
