### ISSUE TITLE
InputGroup compact模式下border异常

### ISSUE THREAD

**Issue by skordyr** [ant-design/ant-design#4790]
#### Environment(required)

- antd version: 2.7.0
- OS and its version: win10
- Browser and its version: 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

在InputGroup compact 模式下的Input组件中右键点击，InputGroup最右组件border消失，在InputGroup外右键点击border重新出现

#### Re-producible online demo
目前官方文档例子可复现

**Comment by ddcat1115** [comment]
能截个屏吗？我这边重现不了...

**Comment by skordyr** [comment]
![](http://oewu9p387.bkt.clouddn.com/InputGroup%20border%20bug.PNG)

**Comment by ddcat1115** [comment]
右键点击的话，为什么focus效果都没有 😦

**Comment by skordyr** [comment]
有foucus 但是右键点击后border消失即使失去焦点border也是不存在的

**Comment by skordyr** [comment]
![](http://oewu9p387.bkt.clouddn.com/InputGroup%20border%20bug.gif)

**Comment by benjycui** [comment]
也重现不了。。。

**Comment by skordyr** [comment]
那可能应该不是antd的问题吧

**Comment by afc163** [comment]
页面放大了？

**Comment by skordyr** [comment]
没缩放,我研究半天没找出原因

**Comment by ddcat1115** [comment]
还专门找了个win10 😂

**Comment by afc163** [comment]
都是玄学。
