### ISSUE TITLE
What are the alternatives for bodyStyle, footerStyle, and headerStyle?

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#47929]
### Steps to reproduce

1. It's proposed to replace the property `footerStyle` with `footer`, however, `footer` already exists and it is not very clear how to, for example, remove the border. Currently, I do it like this: `footerStyle={{border: 0}}`. What is the alternative?

2. `headerStyle` used to accept styles, and you could hide it using `{{display: 'none'}}`. How should this be done now?

3. The same situation with `bodyStyle`, previously I set `{{overflow: 'hidden'}}`, how can this be done now?

4. `Property header does not exist on type IntrinsicAttributes & DrawerProps`

5. What about `rootStyle`?

I also don't see info for the new properties in the documentation, and there are no types specified for them.

### What is expected?

No warning or any alternative

### What is actually happening?

Warning

| Environment | Info |
| --- | --- |
| antd | 5.12.8 |
| React | - |
| System | - |
| Browser | - |

**Comment by monolithed** [comment]
What is needed to reproduce the example? There are no properties 'body' and 'header' [in the code](https://github.com/ant-design/ant-design/blob/de8657bf3b103ea0be4b112a6a8097934c4617ec/components/drawer/DrawerPanel.tsx#L19).

**Comment by afc163** [comment]
See https://stackblitz.com/edit/react-zxccs5?file=demo.tsx
