### ISSUE TITLE
社区精选组件这个页面 F5 会先出现404  然后才会出现该页面

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#4793]
https://ant.design/docs/react/recommendation-cn/

**Comment by afc163** [comment]
正确的地址应该是 https://ant.design/docs/react/recommendation-cn ，你是怎么拿到带斜杠的地址的。

@benjycui 自动跳转逻辑判断前，先不要展示 404 内容如何？

**Comment by qq645381995** [comment]
@afc163  在 https://ant.design/changelog-cn#2.6.2  
                新增社区精选组件页面。链接   这个链接有个 /

**Comment by afc163** [comment]
感谢反馈~
