### ISSUE TITLE
Can't properly reset fields in Form.List externally.

### ISSUE THREAD

**Issue by FomaFom** [ant-design/ant-design#47936]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-6gvn5p?file=%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltwj1tar00073x6gvttg32i7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltwj1tar00033x6gmjngrl4h%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltwj1tar00043x6gmpm9k5pl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltwj1tar00063x6g4bwjwh00%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltwj1tar00033x6gmjngrl4h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwj1tar00023x6gjyrvwzxd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cltwj1tar00033x6gmjngrl4h%2522%252C%2522activeTabId%2522%253A%2522cltwj1tar00023x6gjyrvwzxd%2522%257D%252C%2522cltwj1tar00063x6g4bwjwh00%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwj1tar00053x6gw0o7zid8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltwj1tar00063x6g4bwjwh00%2522%252C%2522activeTabId%2522%253A%2522cltwj1tar00053x6gw0o7zid8%2522%257D%252C%2522cltwj1tar00043x6gmpm9k5pl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltwj1tar00043x6gmpm9k5pl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Create several fields blocks and create several fields inside this blocks.
Click "Reset" button.

### What is expected?

The cleared paths should be deleted from view and their data should be cleared inside a form just like when we are using form.resetFields().

### What is actually happening?

When we use form.resetFields() with NamePath [] as an argument, then data inside the form is cleared, but stays visible.

| Environment | Info |
| --- | --- |
| antd | 4.24.4 |
| React | 17 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
```diff
-- ["customCard", "0", "customInnerCard"]
++ ["customCard", 0, "customInnerCard"]
```
