### ISSUE TITLE
table组件的filter相关功能在filters数量极大（约几千）会极为卡顿

### ISSUE THREAD

**Issue by PaleNeutron** [ant-design/ant-design#47938]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-antd-5-15-1-forked-cs5f42?file=%2Fdemo.js%3A64%2C23)

### Steps to reproduce

filters 长度超过1000

### What is expected?

menu用虚拟滚动或者其他方法加速显示

### What is actually happening?

卡顿大概5秒

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | ^18.2.0 |
| System | windows 10 |
| Browser | Chrome 122.0.6261.129 |

---

或者说我们能不能用 auto-complete 这种纯输入的组件替代渲染一个1000行的menu？

**Comment by zombieJ** [comment]
> 或者说我们能不能用 auto-complete 这种纯输入的组件替代渲染一个1000行的menu？

参考一下这个例子哈~

* [自定义筛选菜单](https://ant-design.antgroup.com/components/table-cn#components-table-demo-custom-filter-panel)

**Comment by PaleNeutron** [comment]
@zombieJ 感谢支持！不过没有把默认的menu改成虚拟滚动的计划吗，这个似乎修改量不大，最后的结果却很优雅。
