### ISSUE TITLE
new-issue.ant,design 中 antd@5.x 链接中  https://codesandbox.io/api/v1/sandboxes/antd-reproduction-template-forked-jyh2k9 为404

### ISSUE THREAD

**Issue by SK-Luffa** [ant-design/ant-design#47939]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/api/v1/sandboxes/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9 =>检查 => https://codesandbox.io/api/v1/sandboxes/antd-reproduction-template-forked-jyh2k9  =》{"error":"Sandbox not found"} 

### What is expected?

请修复这个问题

### What is actually happening?

{"error":"Sandbox not found"}

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18.2.66 |
| System | windows |
| Browser | chrome 122.0.6261.129 |

**Comment by zombieJ** [comment]
codesandbox 改收费策略让一些 codesandbox 变 private 了。这个页面地址能提供一下吗，我看看

**Comment by afc163** [comment]
出处在这里：https://github.com/ant-design/u.ant.design/blob/e0da9cb185bb0b85d297dccaa67ea6155a2fb35d/url.map.js#L19-L20

好了现在已经修复了。

**Comment by afc163** [comment]
<img width="1224" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/29b6740c-b0c1-47a4-81c7-92873d595e95">
