### ISSUE TITLE
Transfer Component. Pass props to a seach box

### ISSUE THREAD

**Issue by pergunt** [ant-design/ant-design#47944]
### What problem does this feature solve?

I have a transfer component in my expanded table.
I need to preserve a value provided by users in the search box so that after they open/close the expanded row, they will see the same result in the search set.
Is there a way to do that?

### What does the proposed API look like?

This functionality is not specified in the docs

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by pergunt** [comment]
There is nothing in the API regarding this case

**Comment by zombieJ** [comment]
Table do not destroy expanded row but only add `display: none` style on the row. If the content gone, pls check your code instead.
