### ISSUE TITLE
Image.PreviewGroup组件变更current下标时图片transform未重置

### ISSUE THREAD

**Issue by CNunicorn6** [ant-design/ant-design#47948]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/duo-zhang-tu-pian-yu-lan-antd-5-14-2-forked-t55dkz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltx2nerc0006356hjxoloz64%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltx2nerc0002356h43ld9zgg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltx2nerc0003356hvzj9vv53%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltx2nerc0005356hrciyrc5b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltx2nerc0002356h43ld9zgg%2522%253A%257B%2522id%2522%253A%2522cltx2nerc0002356h43ld9zgg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltx2nerc0005356hrciyrc5b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltx2nerc0004356h9pfctv41%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltx2nerc0005356hrciyrc5b%2522%252C%2522activeTabId%2522%253A%2522cltx2nerc0004356h9pfctv41%2522%257D%252C%2522cltx2nerc0003356hvzj9vv53%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltx2nerc0003356hvzj9vv53%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

点击图片打开preview组件 -> 点击工具栏rotateLeft或rotateRight按钮  -> 点击工具栏中的左右箭头切换current -> 图片切换后并未重置图片transform

### What is expected?

current改变时重置transform

### What is actually happening?

cureent并未改变transform

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | windows |
| Browser | 122.0.6261.112 |

---
由于现有的图片切换按钮颜色过于浅了不太好找，经常有人看不到左右切换的按钮，所以想把左右切换按钮放到工具栏上，从而导致了这种情况发生

**Comment by CNunicorn6** [comment]
观察源码发现是，是rc-image/lib/PreviewGroup组件的问题，不知道可不可以解决

**Comment by afc163** [comment]
可以解决，欢迎来 PR

**Comment by CNunicorn6** [comment]
> 我在你的 codesandbox 里没有重现你描述的问题，我是不是理解错了？

![image](https://github.com/ant-design/ant-design/assets/37792649/0a8a972a-c9c0-4771-8fa5-795f293323af)

**Comment by CNunicorn6** [comment]
> 我在你的 codesandbox 里没有重现你描述的问题，我是不是理解错了？

我是在toolbarRender中添加了两个切换按钮 用来切换current下标，但是切换完后图片的transform并未重置，但是官方的切换按钮是会重置transform的
![image](https://github.com/ant-design/ant-design/assets/37792649/11c555bf-fdc3-4533-9aa4-45f35af4b966)

**Comment by CNunicorn6** [comment]
![image](https://github.com/ant-design/ant-design/assets/37792649/9903c262-05db-4b73-bf6c-ee0d0aefefed)

**Comment by CNunicorn6** [comment]
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/duo-zhang-tu-pian-yu-lan-antd-5-14-2-forked-t55dkz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltx2nerc0006356hjxoloz64%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltx2nerc0002356h43ld9zgg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltx2nerc0003356hvzj9vv53%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltx2nerc0005356hrciyrc5b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltx2nerc0002356h43ld9zgg%2522%253A%257B%2522id%2522%253A%2522cltx2nerc0002356h43ld9zgg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltx2nerc0005356hrciyrc5b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltx2nerc0004356h9pfctv41%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltx2nerc0005356hrciyrc5b%2522%252C%2522activeTabId%2522%253A%2522cltx2nerc0004356h9pfctv41%2522%257D%252C%2522cltx2nerc0003356hvzj9vv53%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltx2nerc0003356hvzj9vv53%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by afc163** [comment]
<img width="746" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/a01e576c-925b-496f-b44d-ccc4bb87a214">

**Comment by CNunicorn6** [comment]
> <img alt="图片" width="746" src="https://private-user-images.githubusercontent.com/507615/313894937-a01e576c-925b-496f-b44d-ccc4bb87a214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTc4NzEsIm5iZiI6MTcxMDgxNzU3MSwicGF0aCI6Ii81MDc2MTUvMzEzODk0OTM3LWEwMWU1NzZjLTkyNWItNDk2Zi1iNDRkLWNjYzRiYjg3YTIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwMzA2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmU3Mjc2ZDY5MTQxZDA4ZjU4ZWUyYTFlYTdhOGU1MTE2MTNkZTYwOGZmMTQ3ZWZjMTAzOTlmYjc0Nzg4YjkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6yIcFaMoPwlndnGE3Hv2MrHSbyR9imONmd4lwjrrblk">

不好意思，我这边忘了改公开了，一直是私有的状态

**Comment by CollinLee007** [comment]
@CNunicorn6 testing ignore

**Comment by CNunicorn6** [comment]
我觉得是否可以在ToolbarRenderInfoType中的actions里增加切换图片的函数，这样让开发者更加灵活的配置会更好一些

**Comment by afc163** [comment]
> 我觉得是否可以在ToolbarRenderInfoType中的actions里增加切换图片的函数，这样让开发者更加灵活的配置会更好一些

我觉得可以直接在 toolbar 里增加切换的功能。

**Comment by CNunicorn6** [comment]
> > 我觉得是否可以在ToolbarRenderInfoType中的actions里增加切换图片的函数，这样让开发者更加灵活的配置会更好一些
> 
> 我觉得可以直接在 toolbar 里增加切换的功能。

是的，我觉得这样会更灵活一些，并且原有的切换按钮也需要处理

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50812
