### ISSUE TITLE
文档纠错：Image组件的rootClassName属性不是previewType的成员，而是Image组件的最外层属性

### ISSUE THREAD

**Issue by zhenyuanfu** [ant-design/ant-design#47941]
### Reproduction link

[https://ant-design.antgroup.com/components/image-cn#previewtype](https://ant-design.antgroup.com/components/image-cn#previewtype)

### Steps to reproduce

不确定是文档错误还是代码错误。源码上rootClassName是Image组件直接传入的属性，但是文档却是通过previewType传入的

### What is expected?

修正文档或代码

### What is actually happening?

文档或代码错误

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | both |
| System | 无 |
| Browser | 无 |

**Comment by afc163** [comment]
<img width="848" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/3ed00f17-d189-4b90-9c59-abb106eadb37">

preview 里也有 `rootClassName`，文档应该没问题。
