### ISSUE TITLE
When scrolling outside of a drop-down menu the whole menu will break

### ISSUE THREAD

**Issue by TinaDermaku** [ant-design/ant-design#47955]
### Reproduction link

[https://github.com/mui/material-ui/issues/41554#issue-2194553165](https://github.com/mui/material-ui/issues/41554#issue-2194553165)

### Steps to reproduce

Steps:
1.Navigate to the button;
2.Select the button;
3.Open a drop-down menu;
4.Position your mouse cursor outside the drop-down menu and scroll up or down the page;
5.Observe the outcome;

### What is expected?

We should be able to scroll through the page while there is an active drop-down menu, but the menu should stay stationed to its position.

### What is actually happening?

When trying to use drop-down menu for selecting, If you select the drop-down menu it will open, and when you position your mouse cursor outside the menu, if you start scrolling up or down the page, the drop-down menu will travel with you.

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | 18.2.0 |
| System | Ubuntu 22.04.3 |
| Browser | Google Chrome, Brave |

**Comment by afc163** [comment]
See https://ant.design/docs/react/faq#how-do-i-prevent-select-dropdown-datepicker-timepicker-popover-popconfirm-scrolling-with-the-page
