### ISSUE TITLE
能否为DatePicker组件添加点击当前项事件

### ISSUE THREAD

**Issue by starGodXy** [ant-design/ant-design#47954]
### What problem does this feature solve?

用于解决：点击选中日期后，再次点击该日期，取消选中。
提议添加点击当前项的原因是可以执行更多更广泛的操作，不仅仅局限于再次点击后取消---(毕竟添加点击项事件后可以根据数据自行判断是否是点击的选中项)。
目前DatePicker的事件中只有change事件才会返回选择时间，也就是说再次点击选中项什么事件也不会触发。

### What does the proposed API look like?

期望中的API和change类似，只不过触发条件不是变化，而是点击。即：点击任意日期，包括选中项，会返回对应信息。

**Comment by zombieJ** [comment]
DatePicker 里交互是比较复杂的，不是单纯取消选中就行，还需要考虑选中确认逻辑。不建议去做特别花的活，不过如果要做，`cellRender` 就是你要的：

https://stackblitz.com/edit/react-g2kxnb?file=demo.tsx

（如上 示例，可以实现点击事件效果，但是交互是会比较怪异的）
