### ISSUE TITLE
当FormItem 的name 置空时，children是个方法 getValueProps 起作用了，和正常情况下是ReactNode 的表现不一致

### ISSUE THREAD

**Issue by jongwong** [ant-design/ant-design#47952]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-p5ekup-xal1vx?file=demo.tsx)

### Steps to reproduce

```
    <Form.Item<FieldType>
      label="Username22"
      getValueProps={(val) => {
        console.log('======',val)
        return {value:val}
      }}
      rules={[{ required: true, message: 'Please input your username!' }]}
    >
      {() => <Input />}

    </Form.Item>

```
当FormItem 的name 置空时，children是个方法

### What is expected?

期望getValueProps 不起作用

### What is actually happening?

getValueProps 起作用

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18.2.0 |
| System | mac os 12.4 |
| Browser | 任意 |

**Comment by zombieJ** [comment]
`name` 就是做字段绑定用的，如果不设置就只是作为纯粹的 UI 组件哈~

**Comment by jongwong** [comment]
> `name` 就是做字段绑定用的，如果不设置就只是作为纯粹的 UI 组件哈~

可能你误会了，这个问题的关注点不是Input，是getValueProps 当没有name 作为UI组件时候期望是不调用，和children 是React Node 时候表现一致，getValueProps 调用的判断条件是name ，不应该多了children
