### ISSUE TITLE
Modal 内容超长，打开位置会闪一下

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47967]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-scdbw3?file=demo.tsx)

### Steps to reproduce

Open Modal

### What is expected?

位置不变

### What is actually happening?

位置变了一次

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by mithun522** [comment]
Hey @crazyair  I would like to contribute to this issue. I need some eloborative explanation of what is exactly the expected behaviour.

**Comment by crazyair** [comment]
> Hey @crazyair I would like to contribute to this issue. I need some eloborative explanation of what is exactly the expected behaviour.

This https://stackblitz.com/edit/react-scdbw3-zyr98j?file=demo.tsx

**Comment by AndyJinSS** [comment]
这个问题已经被修复了，https://github.com/react-component/dialog/pull/430
