### ISSUE TITLE
Popconfirm在页面有滚动条并且位于边缘时会出现无限位置调整导致的一直抖动

### ISSUE THREAD

**Issue by xmh0511** [ant-design/ant-design#47969]
### Reproduction link

[https://github.com/xmh0511/Popconfirm_reproduct](https://github.com/xmh0511/Popconfirm_reproduct)

### Steps to reproduce

有滚动条的情况下，将Popconfirm组件的弹出位置置于页面边缘，此时Popconfirm组件会无限计算位置导致出现一直闪烁

### What is expected?

不会一直闪烁

### What is actually happening?

一直闪烁

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18 |
| System | 所有 |
| Browser | chrome |

https://github.com/ant-design/ant-design/assets/17973891/57111bc6-5421-4297-b74b-74dd5238d09a

视频展示bug复现步骤

**Comment by afc163** [comment]
第三个同类问题了。@zombieJ

**Comment by MadCcc** [comment]
上周看类似问题的结论是当 arrow 放不下的时候就不让 popvoer 弹出了。但是看这个场景应该还是应该弹出。

**Comment by noynek** [comment]
Running into the same issue. I'm finding the repro a bit inconsistent. It does seem to be related to scrollbars some of the time. I can also trigger it intermittently when resizing or zooming.

**Comment by lixin0724** [comment]
同样问题+1
