### ISSUE TITLE
国际化配置按官网描述配置了ConfigProvider locale后，DatePicker组件只是placeHolder切换为中文，日历内容都是英文

### ISSUE THREAD

**Issue by huangrenfang** [ant-design/ant-design#47976]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fan-wei-xuan-ze-qi-antd-5-15-3-forked-jvdh6h?file=%2Fdemo.tsx%3A9%2C30)

### Steps to reproduce

从官网的sandbox跳转进去，按官网描述配置Provider locale

### What is expected?

DatePicker所有内容切换为中文

### What is actually happening?

仅placeHolder切换了，其他的内切换

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | macos |
| Browser | 122.0.6261.112 |

---
在自己项目中添加dayjs.locale('zh-cn')也不起作用

**Comment by afc163** [comment]
<img width="660" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/478121a8-e1fb-480d-abda-bef5f92c2a0e">

**Comment by huangrenfang** [comment]
sry 重新整了一份连接，版本是5.15.3，表现是一样的
https://stackblitz.com/edit/react-3t9wxz?file=demo.tsx

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96-locale-%E8%AE%BE%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-3t9wxz-yyxm2a?file=demo.tsx,package.json

**Comment by zxq08** [comment]
> sry 重新整了一份连接，版本是5.15.3，表现是一样的 https://stackblitz.com/edit/react-3t9wxz?file=demo.tsx

我最近也遇到了，说一下我的思路吧。
antd的locale配置控制的是组件本身的内容，比如placeholder；
dayjs的locale配置控制的是日期面板，比如年、月、日、一、二、三...这些。
