### ISSUE TITLE
Button 类型为 link 时主题色展示异常

### ISSUE THREAD

**Issue by a20070322** [ant-design/ant-design#47977]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/an-niu-lei-xing-antd-5-15-3-forked-q8n8r2)

### Steps to reproduce

```tsx
import React from "react";
import "./index.css";
import { Button, Flex, ConfigProvider } from "antd";

const App: React.FC = () => (
  <ConfigProvider
    theme={{
      token: { colorPrimary: "#13c2c2" },
    }}
  >
    <Flex gap="small" wrap="wrap">
      <Button type="primary">Primary Button</Button>
      <Button>Default Button</Button>
      <Button type="dashed">Dashed Button</Button>
      <Button type="text">Text Button</Button>
      <Button type="link">Link Button</Button>
    </Flex>
  </ConfigProvider>
);

export default App;

```

### What is expected?

link 按钮展示为 配置主题色

### What is actually happening?

link 按钮展示为 默认主题色

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | ^18.0.0 |
| System | mac |
| Browser | 122.0.6261.129 |

**Comment by Wxh16144** [comment]
应该用 `colorLink ` , ref: [V5 中 colorPrimary 和 colorInfo 及 colorLink 之间是什么关系？
](https://ant.design/docs/react/faq-cn#v5-%E4%B8%AD-colorprimary-%E5%92%8C-colorinfo-%E5%8F%8A-colorlink-%E4%B9%8B%E9%97%B4%E6%98%AF%E4%BB%80%E4%B9%88%E5%85%B3%E7%B3%BB)

**Comment by MadCcc** [comment]
> 应该用 `colorInfo` 或 `colorLink` , ref: [V5 中 colorPrimary 和 colorInfo 及 colorLink 之间是什么关系？ ](https://ant.design/docs/react/faq-cn#v5-%E4%B8%AD-colorprimary-%E5%92%8C-colorinfo-%E5%8F%8A-colorlink-%E4%B9%8B%E9%97%B4%E6%98%AF%E4%BB%80%E4%B9%88%E5%85%B3%E7%B3%BB)

正解
