### ISSUE TITLE
InputNumber 提供一个属性，当 precision 不为 0 时，通过 value 设置值或 onBlur 时自动清空末尾的 0

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#47970]
### What problem does this feature solve?

当 precision 为 2 时

问题：输入 1，失焦时会变成 1.00，不是很美观。

期望：输入 1，变成 1
           输入 1.1，变成 1.1
           输入 1.11，变成 1.11

### What does the proposed API look like?

clearTrailingZero

**Comment by zombieJ** [comment]
用 `formatter` 转译即可，`precision` 本身其实是 `formatter` 的语法糖实现。

**Comment by linxianxi** [comment]
这样比较麻烦，需要写逻辑
