### ISSUE TITLE
Rate组件支持配置总分

### ISSUE THREAD

**Issue by huangkairan** [ant-design/ant-design#47981]
### What problem does this feature solve?

业务中有挺多场景，Rate的总分和展示的 count 是不确定的。

如A模块中总分10，展示5颗星；B模块中总分100，展示5颗星；C模块中总分120，展示6颗星。

希望在消费Rate组件时能够提供一个max prop，在组件内部处理max、value和count的逻辑。

### What does the proposed API look like?

max: number，默认为 5

```
<Rate value={100} max={100} count={5}/> // 5颗星全亮

<Rate value={24} max={120} count={5}/> // 5颗星中亮1颗

<Rate value={8} max={10} count={5}/> // 5颗星中亮4颗
```

**Comment by CooperHash** [comment]
i get your point. 感觉这部分逻辑确实是缺失的

**Comment by afc163** [comment]
这个做一层上层组件的业务封装就行了，把 Rate 的 value 转换为对应的业务数值。
