### ISSUE TITLE
4.0和5.0文档表格组件没有可伸缩列的说明配置

### ISSUE THREAD

**Issue by JunHooo** [ant-design/ant-design#47984]
### What problem does this feature solve?

需要对表格的列宽伸缩调整

### What does the proposed API look like?

3.0中的react-resizable用起来非常难受，后续版本会出继续支持伸缩列的配置吗？

**Comment by afc163** [comment]
正是因为用起来很难受，才下掉了这个演示。

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/32811
