### ISSUE TITLE
Upload picture-card 可以更改为 flex   gap 布局，不会有多余的右 margin 和 下 margin

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#47992]
### Reproduction link

[https://ant.design/components/upload-cn#components-upload-demo-picture-card](https://ant.design/components/upload-cn#components-upload-demo-picture-card)

### Steps to reproduce

查看最右侧和最下侧的 margin

### What is expected?

最右侧和最下侧的没有 margin

### What is actually happening?

最右侧和最下侧的有 margin

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | latest |
| System | mac |
| Browser | chrome |

---
但是也要考虑下是不是会和 Tag 的 margin 一样会有 break change

**Comment by zombieJ** [comment]
可以的，这个之前其实也是因为旧版 IE 不支持
