### ISSUE TITLE
Table 组件的那个列表中有一个表头是右侧固定时，设置了scroll中的纵向值，数据多会出现滚动条，当数据不够时也会出现。这时候设置overflow-y：hidden，会出现固定的那列表头和内容不对齐

### ISSUE THREAD

**Issue by LiJinWeb** [ant-design/ant-design#47996]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-flhcp6?file=demo.js,index.css)

### Steps to reproduce

手动overflow-y：auto

### What is expected?

期望  列表数据不够不出现滚动条，且内容对齐

### What is actually happening?

出现滚动条，手动去除后 内容不对齐

| Environment | Info |
| --- | --- |
| antd | 5.13.0 |
| React | 18.2.0 |
| System | win10 |
| Browser | 122.0.6261.129 |

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/issues/47777#issuecomment-1985302307
