### ISSUE TITLE
Image Upload Not working on mac

### ISSUE THREAD

**Issue by dhwaj1902** [ant-design/ant-design#47999]
### Reproduction link

[https://ant.design/components/upload](https://ant.design/components/upload)

### Steps to reproduce

Go to antd website, try upload the image using upload Button, image popup will not open.

### What is expected?

To open folders to choose the image

### What is actually happening?

Not opening the folder

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
[FAQ: Why sometimes Chrome can not upload?](https://ant.design/components/upload/#why-sometimes-chrome-can-not-upload)

> Chrome update will also break native upload. Please restart Chrome to finish the upload work.
