### ISSUE TITLE
Add labelRender props in Select 

### ISSUE THREAD

**Issue by yunho1017** [ant-design/ant-design#47993]
### What problem does this feature solve?

I want to custom render the selected value in Select.

### What does the proposed API look like?

https://select-react-component.vercel.app/

The Select component provided by ant-design is known to be based on rc-select.
labelRender props already exist in rc-select

**Comment by yunho1017** [comment]
If this feature can be added, can I contribute it?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/47811
