### ISSUE TITLE
有没有单页应用的例子

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#480]
请问有没有人使用 ant 做 SPA 的例子,谢谢

**Comment by afc163** [comment]
试试：https://github.com/rackt/react-router

**Comment by kevyu** [comment]
[http://ant.design](http://ant.design)的官网能用ant-design做成SPA就好了，正好当演示用。

**Comment by bang88** [comment]
@afc163 请问你们后台现在是怎么使用 ant 的?单页还是其他方式

**Comment by afc163** [comment]
基本都是单页。

**Comment by bang88** [comment]
@afc163 有没有空整理一个 demo 出来分享一下,包括 dynamic router ,production webpack  的

**Comment by afc163** [comment]
单页应用的路由用法你直接看官方的例子就好：https://github.com/rackt/react-router/tree/master/examples

**Comment by bang88** [comment]
@afc163 主要是想看下你们的项目结构,以及其他的东西

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/boilerplate

**Comment by bang88** [comment]
好 先看看
