### ISSUE TITLE
React-grid-layout, antd dynamic form list

### ISSUE THREAD

**Issue by truedrug** [ant-design/ant-design#48005]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/5s2tlf)

### Steps to reproduce

- So, I have a antd dynamic form list. This is wrapped by react-grid-layout to provide drag and drop facility within the list
- When re-ordering the list, it happens perfectly fine (I get the updated layout from react-grid-layout lib), but upon trying to save the updated order into antd form (using form.setFields) - save happens, but the layout again changes out of its own

### What is expected?

It should not change automatically - this happens once I use form.setFields

### What is actually happening?

Interact with the ui to drag and re-order to understand that the re-order does not work. Only if you remove form.setFields, it works

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

**Comment by truedrug** [comment]
@afc163 mind looking into this please?

**Comment by zombieJ** [comment]
The render order is not the `fields` provided order:

<img width="1058" alt="截屏2024-03-22 14 56 27" src="https://github.com/ant-design/ant-design/assets/5378891/f28b22d0-0d54-41ee-9fc7-f2dccfd8b904">

Pls feel free to ask `react-grid-layout` instead since we can help nothing on this.
