### ISSUE TITLE
Card与Affix混合使用当Affix进行定位后，Affix的DOM元素hover时会被隐藏不可见

### ISSUE THREAD

**Issue by wonyun** [ant-design/ant-design#4800]
#### Environment(required)

- antd version: 2.5.2
- OS and its version: mac
- Browser and its version: chrome 55.0.2883.95 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

Card与Affix混合使用时，Affix作为Card的子元素，当达到指定条件Affix定位后，鼠标hover到Affix的dom元素上，其dom元素不可见

#### What do you expected?
affix的内容可见

#### Re-producible online demo
事例：[https://codepen.io/fetest/pen/jyvpbB?editors=0010](https://codepen.io/fetest/pen/jyvpbB?editors=0010)

**Comment by RaoHai** [comment]
看了一下 DEMO ，怎么操作能重现 “其dom元素不可见”，感觉挺正常。。

**Comment by afc163** [comment]
缩小垂直视窗，向下滚动。

**Comment by RaoHai** [comment]
。。居然只能在 retina 屏上复现。。

**Comment by RaoHai** [comment]
感觉好像是 chrome 的 bug ？

https://github.com/ant-design/ant-design/blame/master/components/card/style/index.less#L16

这个 z-index:1 的影响，去了就好了。 firefox，safari，和非 retina 屏都无法复现。。。 @afc163

**Comment by afc163** [comment]
蛋疼。先去掉好了。

**Comment by wonyun** [comment]
@afc163 @RaoHai 👍👍👍
