### ISSUE TITLE
使用RangePicker组件时，自定义disabledDate函数的依赖发生改变时，会导致日期选择面板关闭

### ISSUE THREAD

**Issue by hubo1990** [ant-design/ant-design#48002]
### Reproduction link

[https://ango2.recika.io/listing/details/11](https://ango2.recika.io/listing/details/11)

### Steps to reproduce

在任意React页面中使用RangePicker组件，disabledDate={disabledDate}，重写disabledDate
const disabledDate = useCallback(
    (currentDate: any, _info: { from?: any }) => {
       。。。。。
 },
  [calendarInfo，checkDates]
);

### What is expected?

期待结果是：初期显示酒店的checkIn日期(开始日期)可以选择21号，当我选择21号以后，焦点跳到checkOut(结束日期)，此时21号不可选，22号变成可选状态

### What is actually happening?

实际结果是日期选择面板被关闭隐藏了，当我手动点击时，会再次弹出日期选择面板，这个时候日期面板中的显示是上面预期的结果，唯一的问题时，重写的方法重新运行后都会导致日期面板的消失

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | windows10专业版 |
| Browser | Google Chrome 版本 122.0.6261.129（正式版本）（64 位） |

**Comment by hubo1990** [comment]
Reproduction link:
http://124.71.144.66:52066/listing/details/11

**Comment by afc163** [comment]
Could you provide a codesandbox?

**Comment by hubo1990** [comment]
![image](https://github.com/ant-design/ant-design/assets/18757134/fce3adba-50f7-44f7-86ac-d8a63cc61e9f)
![image](https://github.com/ant-design/ant-design/assets/18757134/61ffd4e7-b471-40e3-ba1c-24f669ad2d56)
奇怪，codesandbox是正常的
