### ISSUE TITLE
官网 Affix 页面快速滚动有Bug，不能恢复原位

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#4801]
antd@2.7.0
safari 10.0.3

先慢慢往下滚，触发`affix`后快速网上滚到顶，`affix`组件不会恢复原位，然后在微微滚动一下才能恢复原位。

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/4760

**Comment by xutou12** [comment]
额 好吧 没仔细搜 issue
还有触发后没有占高，设计如此呢还是？

**Comment by afc163** [comment]
应该也修复了：https://github.com/ant-design/ant-design/issues/4755

在同一个 PR 里：#4756

**Comment by xutou12** [comment]
哦哦 坐等更新拉
