### ISSUE TITLE
input 开启showCount后，className传递给input

### ISSUE THREAD

**Issue by Atw-Lee** [ant-design/ant-design#48015]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/input-cn/#components-input-demo-show-count](https://4x-ant-design.antgroup.com/components/input-cn/#components-input-demo-show-count)

### Steps to reproduce

https://4x-ant-design.antgroup.com/components/input-cn/#components-input-demo-show-count 这个demo打开写个classname

### What is expected?

希望不要传递给input标签

### What is actually happening?

传递给了input标签

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | * |
| System | all |
| Browser | all |

<img width="1393" alt="image" src="https://github.com/ant-design/ant-design/assets/95407716/0f60e00d-9741-4880-8ef0-94c0628bcdc4">

**Comment by Atw-Lee** [comment]
textArea 没有传递下去，zhe shi w这是我希望到
<img width="1512" alt="image" src="https://github.com/ant-design/ant-design/assets/95407716/bf6525fd-766a-417f-b2d4-5a4780f8aae1">

**Comment by Atw-Lee** [comment]
如果这个问题可以通过，我想尝试改一下，还没有提过pr。
<img width="1512" alt="image" src="https://github.com/ant-design/ant-design/assets/95407716/9ed0f71a-2ac0-435f-a8a0-88f69cd690c3">

**Comment by zombieJ** [comment]
[📢 v4 维护周期截止](https://ant-design.antgroup.com/docs/blog/v4-ood-cn)

> 根据我们的发布时间表，Ant Design v4 版本的维护期已于 2023 年年底正式结束。这意味着，除非发现了重大的缺陷或其他严重问题，我们不会再为 v4 推出任何新的更新或补丁版本。我们强烈建议用户尽快升级到 Ant Design v5 版本。

更改传递 className 会是一个 breaking change，v4 中不会再上了哈~
