### ISSUE TITLE
`<ColorPicker>`颜色选择组件在`<Drawer>`抽屉组件中，并被包裹在`<Form>`里。当抽屉打开时，通过`form.setFieldsValue`给`ColorPicker`设置的值，不能回显

### ISSUE THREAD

**Issue by diandian18** [ant-design/ant-design#48022]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/xiao-yan-qi-ta-zu-jian-antd-5-15-3-forked-9c52cj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu2crj1e00063b6gs2ymoq14%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu2crj1d00023b6g38b7bx2c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu2crj1d00033b6gzco2rsxz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu2crj1d00053b6gv9czhit3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu2crj1d00023b6g38b7bx2c%2522%253A%257B%2522id%2522%253A%2522clu2crj1d00023b6g38b7bx2c%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu2crj1d00053b6gv9czhit3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu2crj1d00043b6gxl9y26ah%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu2crj1d00053b6gv9czhit3%2522%252C%2522activeTabId%2522%253A%2522clu2crj1d00043b6gxl9y26ah%2522%257D%252C%2522clu2crj1d00033b6gzco2rsxz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu2crj1d00033b6gzco2rsxz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. `<ColorPicker>`颜色选择组件在`<Drawer>`抽屉组件中，并被包裹在`<Form>`里
2. 同时也写一个`<Input>`组件
2. 当抽屉打开时，通过`form.setFieldsValue`给`ColorPicker`设置值`'#ddd'`，给`<Input>`设置值`'aaaaaa'`

### What is expected?

1. `<ColorPicker>`能正确回显设置的颜色值`'#ddd'`
2. `<Input>`能正确回显设置的值`aaaaaa`

### What is actually happening?

1. `<ColorPicker>`错误地显示了“红色斜杠”（即null值）
2.  `<Input>`正确地回显设置的值`aaaaaa`

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18.2.0 |
| System | MacOS |
| Browser | 版本 122.0.6261.112（正式版本） (x86_64) |

**Comment by MadCcc** [comment]
Same as https://github.com/ant-design/ant-design/issues/47980
