### ISSUE TITLE
props.form.setFieldsValue在componentWillMount里直接使用无效

### ISSUE THREAD

**Issue by awaw00** [ant-design/ant-design#4802]
http://codepen.io/awaw00/pen/dNqqEV?editors=001

请对比取消componentWillMount里注释后的行为。

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#Form.create(options)

看下 setFieldsValue 的文档描述。

**Comment by awaw00** [comment]
@afc163 感谢回复，文档里写了componentWillReceiveProps里使用会导致死循环，issue我也搜了一下，没有发现有关于在componentWillMount里使用的注意事项。

**Comment by afc163** [comment]
是我看错了。

**Comment by benjycui** [comment]
`componentWillMount` 时 `render` 还没执行，所以 `getFieldDecorator` 也没执行，自然没有办法设置值。。

**Comment by awaw00** [comment]
@benjycui 明白了，最好还是在文档里加个提醒吧

**Comment by awaw00** [comment]
@benjycui 还有个疑问，为什么setFieldsValue没办法设置值，但是setFields可以呢？

```javascript
    ...
    this.props.form.setFields({
      test: {
        value: '123'
      }
    });
    ...
```

**Comment by benjycui** [comment]
`rc-form` 内部逻辑比较复杂，有些行为虽然 work，但不是 by designed 的话，还是不要用。
