### ISSUE TITLE
Placement props not working in DatePicker and TimePicker

### ISSUE THREAD

**Issue by jaydeep-pipaliya** [ant-design/ant-design#48026]
### Reproduction link

[https://ant.design/components/date-picker#components-date-picker-demo-placement](https://ant.design/components/date-picker#components-date-picker-demo-placement)

### Steps to reproduce

just click on placement and see if it affecting the datepicker

### What is expected?

if we select topRight then datePicker should be reflected as "topRight" side rather than bottomLeft 

### What is actually happening?

it is always placed at bottomLeft

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18 |
| System | Ubuntu 20 |
| Browser | Chrome |

**Comment by yoyo837** [comment]
@zombieJ assigned to himself at 3 days ago.

**Comment by bombillazo** [comment]
+1 to this, I though it was a browser issue but I tried Chrome and Firefox and it always pops below the input. The date range picker works as expected if there is space.
