### ISSUE TITLE
AutoComplete 官网示例，当使用setTimeout来setState的时候，下拉框不会自动显示

### ISSUE THREAD

**Issue by awaw00** [ant-design/ant-design#4804]
http://codepen.io/awaw00/pen/mRGQLV?editors=0010

输入值后需要鼠标点击后才会显示出下拉框。

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design/issues/3958

- 用户输入，`onInputChange`把`state.open`设为了true
- componentWillUpdate里的`adjustOpenState`判断到`children.length`为0又把`open`设置为false
- setTimeout被执行到，`children`有内容了，但`state.open`仍然是false, 无法显示

@RaoHai @afc163

**Comment by paranoidjk** [comment]
@RaoHai 最近忙不过来，你一并看下吧 😄

**Comment by paranoidjk** [comment]
ping @yesmeck

**Comment by afc163** [comment]
Any progress?

**Comment by paranoidjk** [comment]
测试已经 fix 了。
