### ISSUE TITLE
select 组件 单选多选从controlHeight获取高度不统一

### ISSUE THREAD

**Issue by Q-Peppa** [ant-design/ant-design#48043]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-dqxc6p?file=index.tsx,App.tsx)

### Steps to reproduce

```js
  <ConfigProvider
    theme={{
      token: {
        controlHeight: 28,
        paddingXXS: 0,
      },
    }}
  >
    <App />
  </ConfigProvider>,
----
function App() {
  return <React.Fragment>
    <Select style={{ width : 300 }}/>
    <Select  style={{ width : 300 , marginLeft : 20}} mode={"multiple"} />
  </React.Fragment>;
}
```

### What is expected?

期待两种Select组件高度一致

### What is actually happening?

单选的高度为 controlHeight: 28,是正确的, 多选则不对

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | 18 |
| System | mac |
| Browser | chrome 122  |

---
项目中配置了paddingXXS: 0, 不知为何会影响Select的高度

**Comment by Q-Peppa** [comment]
![image](https://github.com/ant-design/ant-design/assets/54980372/8325cfac-70f8-4320-877b-d068c9150b6b)

**Comment by CooperHash** [comment]
这么就没问题
![image](https://github.com/ant-design/ant-design/assets/73218815/23203321-71e5-4388-83dd-83743a6b5a8e)

挺奇怪的，我早些时候复现成功，现在又不行了

**Comment by CooperHash** [comment]
i am working on it

**Comment by CooperHash** [comment]
> i am working on it

让multi高度正常后还需要解决一些错位问题

**Comment by CooperHash** [comment]
有点奇怪的是一样的例子，issue给的例子100%复现，本地修改有时候会重现不了，但是经过多次确认有multi高度don't work的情况

**Comment by CooperHash** [comment]
有点奇怪了...
https://stackblitz.com/edit/react-dqxc6p-aka9wm?file=App.tsx
这样写没问题

**Comment by CooperHash** [comment]
> 有点奇怪的是一样的例子，issue给的例子100%复现，本地修改有时候会重现不了，但是经过多次确认有multi高度don't work的情况

源码改着改着，发现：在不修改原来代码的情况下用controlheight也没问题，好诡异
