### ISSUE TITLE
Tour组件的InternalPanel的用法在代码demo中有，但是在antd的网站Tour组件介绍下是没有写明的

### ISSUE THREAD

**Issue by Roxannej** [ant-design/ant-design#48047]
### What problem does this feature solve?

让用户能更清晰的使用组件的自定义功能去完成一些需求

### What does the proposed API look like?

能把InternalPanel的demo例子在网页展示一下

![Uploading 截屏2024-03-23 23.47.29.png…]()

**Comment by afc163** [comment]
InternalPanel 不是正式的对外 API，不建议使用，因此没有对外放出 demo 和文档。
