### ISSUE TITLE
App Modal - Theme

### ISSUE THREAD

**Issue by YuvalPeretz** [ant-design/ant-design#48056]
### What problem does this feature solve?

The inconsistency of the theming of the applicaiton when using the `App.useApp()`

### What does the proposed API look like?

```
<App theme={{ algorithm: theme.darkAlgorithm }} notification={{ theme: "dark" }}>
...
</App>
```

**Comment by MadCcc** [comment]
Use ConfigProvider to wrap App with `theme`.
