### ISSUE TITLE
AutoComplete 不支持 tags 多选模式？

### ISSUE THREAD

**Issue by lllyyylll2** [ant-design/ant-design#4805]
#### Re-producible online demo
http://codepen.io/anon/pen/NdLmWX

**Comment by benjycui** [comment]
@RaoHai [文档](https://ant.design/components/auto-complete-cn/#API) 有歧义吧。。

> 因为 AutoComplete 是基于 Select 封装的，所以除了以下 API 外，AutoComplete 跟 Select 拥有一样的 API。

**Comment by afc163** [comment]
应该是基于 `Select[combo]` 封装的。

**Comment by RaoHai** [comment]
不支持。

**Comment by afc163** [comment]
感觉这句话可以去掉，把需要的都拿过来。理论上 AutoComplete 的底层是可以被替换的，不需要跟着 Select 走。
