### ISSUE TITLE
DatePicker doesn't support tabIndex

### ISSUE THREAD

**Issue by wang-yikai** [ant-design/ant-design#48059]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/basic-antd-5-15-3-forked-2kk5qd)

### Steps to reproduce

Pass tabIndex={-1} and see that DatePicker can still be focused.

### What is expected?

DatePicker should get focused in the right order and DatePicker with -1 tabIndex shouldn't get focused.

### What is actually happening?

Press tab on the keyboard and see that DatePicker gets focused in the wrong order and DatePicker with -1 tabIndex still gets focused.

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

---
This was resolved in https://github.com/ant-design/ant-design/issues/23918 but not for AntD v5.

**Comment by afc163** [comment]
<img width="741" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/5ac6a80d-9abd-49aa-bf32-697f40c39b2f">

**Comment by wang-yikai** [comment]
@afc163 I made the sandbox public, my apologies!

**Comment by wang-yikai** [comment]
I've created https://github.com/react-component/picker/pull/779 to fix this issue.

**Comment by wang-yikai** [comment]
@zombieJ Any progress with merging https://github.com/react-component/picker/pull/779?

**Comment by nathanlao** [comment]
@afc163 Does the PR above resolve the issue?
