### ISSUE TITLE
Error with Webpack and Modal

### ISSUE THREAD

**Issue by daver182** [ant-design/ant-design#4806]
#### Environment(required)

- antd version: 2.7.0
- OS and its version: Mac OS Sierra 10.12.2
- Browser and its version: Chrome 55

#### What did you do? Please provide steps to re-produce your problem.

I just imported Modal, I'm using Webpack 1, with the long syntax import:

```
import Modal from 'antd/lib/modal';
import 'antd/lib/modal/style/index.less';
```

#### What do you expected?

It doesn't compile the code

#### What happen?

When running `webpack-dev-server --inline --hot --progress` I get an error related to Webpack: 

`TypeError: contextRegExp.test is not a function`

I followed the problem and I got this:
`
node_modules > antd > lib > modal > index.js > confirm.js
`
If I remove the line `var _locale = require('./locale')` everything works as expected.

Great library, thanks for all the work.

**Comment by benjycui** [comment]
Please provide a re-producible repo and steps, THX.

**Comment by benjycui** [comment]
Close for no response, and you can re-open if you can  provide a re-producible repo and steps, THX.
