### ISSUE TITLE
 Upload click to upload broken in Chrome

### ISSUE THREAD

**Issue by tnmarch** [ant-design/ant-design#48060]
### Reproduction link

[https://ant.design/components/upload](https://ant.design/components/upload)

### Steps to reproduce

Click on the first example button, the click no longer does anything. Works fine on Edge and Safari, but not on Chrome. 

### What is expected?

The file explorer should open up to allow file selection

### What is actually happening?

Nothing

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

---
Not sure which update caused this, but this component is now dead on Chrome. Can still drag and drop, but click to upload no longer works on both our application or on the Ant Design website.

EDIT: After talking with my team, this looks more likely to be caused by a Chrome update. We have branches using 5.10 from a few months ago and 5.15.3 on another (plus 5.15.3 is in your website) and both are broken. So could be an Ant problem or a Chrome problem.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/48007#issuecomment-2012258766

**Comment by coladeu** [comment]
I get this issue every time a new Chrome version drops on my M1. Updating Chrome always fixes it. I haven’t skipped a single version in the last two years. Not even one of those sneaky little point releases.
