### ISSUE TITLE
Cascader maxTagPlaceholder 使用 Popover 删除 value 使其不超出省略后，Popover 未消失

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#48069]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-gxgktg?file=demo.tsx)

### Steps to reproduce

1、鼠标移入  1
2、点击 Tag 的移除按钮
3、观察 Popover

### What is expected?

Popover 消失。
omitOptions 长度为 0 时，maxTagPlaceholder 应该不渲染

### What is actually happening?

Popover 还在

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
Since Overflow node is a placeholder node which may not remove for render. Here is the resolution:
https://stackblitz.com/edit/react-gxgktg-zkzcwj?file=demo.tsx

**Comment by youlostme** [comment]
how to solve click the popover will trigger select open and close?

**Comment by linxianxi** [comment]
> how to solve click the popover will trigger select open and close?

https://stackblitz.com/edit/react-gxgktg?file=demo.tsx

**Comment by youlostme** [comment]
I am deeply grateful. @linxianxi
