### ISSUE TITLE
Typography copyable not refreshing text to be copied

### ISSUE THREAD

**Issue by janarvaezkng** [ant-design/ant-design#48075]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-copyable-z2xflz)

### Steps to reproduce

in the sandbox:
- click change url
- click copy not working
- paste link in notepad: link is the previous url
- click copy working
- paste link in notepad: link is correct

### What is expected?

clicking the button to copy actually copies the latest value

### What is actually happening?

The copy text is somehow memoised to de previous value

| Environment | Info |
| --- | --- |
| antd | 5.12.4 |
| React | react 18 |
| System | macos |
| Browser | chrome |

**Comment by janarvaezkng** [comment]
> Pls set your codesandbox to public : )

😬 sorry! done

**Comment by CooperHash** [comment]
I'm not sure if it's because of `useMemo`.

**Comment by LingJinT** [comment]
I will try to fix it

**Comment by crazyair** [comment]
Because the children have changed, copying is not a problem
