### ISSUE TITLE
期望tabs能够支持自定义 moreIcon展开的触发方式，目前默认是hover展开

### ISSUE THREAD

**Issue by tmj1220** [ant-design/ant-design#48085]
### Reproduction link

[https://ant.design/components/tabs](https://ant.design/components/tabs)

### Steps to reproduce

多个tabs溢出盒子后hover moreIcon展示更多

### What is expected?

支持hover，click多种方式触发

### What is actually happening?

目前默认hover触发

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18.2.0 |
| System | macOS 14.4 |
| Browser | 123.0.6312.59 |

**Comment by afc163** [comment]
Similar to https://github.com/ant-design/ant-design/issues/44858

**Comment by yoyo837** [comment]
Tracing it in #44858

**Comment by afc163** [comment]
等 https://github.com/ant-design/ant-design/pull/48321 合并了一起关。

**Comment by afc163** [comment]
Closed in favor of https://github.com/ant-design/ant-design/pull/48321
