### ISSUE TITLE
条件渲染的时候 useWatch 拿不到正确的值

### ISSUE THREAD

**Issue by LXY02** [ant-design/ant-design#48080]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/usewatch-antd-5-4-0-forked-7k3xvz?file=%2Fdemo.tsx)

### Steps to reproduce

打开上面的链接，打开检查，看控制台log，会发现useWatch在条件渲染的情况下，拿不到initialValues里的初始值，但是form.getFieldValue的方式可以拿到。
问题截图如下：
https://img.alicdn.com/imgextra/i3/O1CN01FMv7P51SZ838VvLr9_!!6000000002260-0-tps-2840-1550.jpg

### What is expected?

useWatch能在条件渲染的情况下，拿到initialValues里对应的初始值

### What is actually happening?

useWatch能在条件渲染的情况下，拿不到initialValues里对应的初始值，输出是undefined

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | ^18.0.0 |
| System | mac |
| Browser | chrome 114.0.5735.133 |

**Comment by zombieJ** [comment]
codesandbox 没开公开看不到哈~

**Comment by LXY02** [comment]
> codesandbox 没开公开看不到哈~
现在可以看到了吗？https://codesandbox.io/p/sandbox/usewatch-antd-5-4-0-forked-7k3xvz?file=%2Fdemo.tsx

**Comment by crazyair** [comment]
<img width="1329" alt="image" src="https://github.com/ant-design/ant-design/assets/7971419/a89df861-320d-4f5d-82da-8c388cd504c9">
https://stackblitz.com/edit/react-bzbaj8?file=demo.tsx

类似这个，用 useWatch 的值才是对的，卸载了就应该是 undefined

**Comment by LXY02** [comment]
> <img alt="image" width="1329" src="https://private-user-images.githubusercontent.com/7971419/316517608-a89df861-320d-4f5d-82da-8c388cd504c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTc0MDMsIm5iZiI6MTcxMTQxNzEwMywicGF0aCI6Ii83OTcxNDE5LzMxNjUxNzYwOC1hODlkZjg2MS0zMjBkLTRmNWQtODJkYS04YzM4OGNkNTA0YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMDEzODIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWI5ZTk2MDA0ZWM1YjVmYzFkYzVmZjI3OWRiMGQxMjNjN2JjN2Y2OTY3MDFjODE0Yzk0ZjI3ZmQ4ZGM3OGM1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v6MVTB3Ly6yRFtRtOeHbzcpIBr4466gWvI50bvf2Spc"> https://stackblitz.com/edit/react-bzbaj8?file=demo.tsx
> 类似这个，用 useWatch 的值才是对的，卸载了就应该是 undefined

可是如果想要条件渲染，并且监听条件渲染里Form.Item的值的话要怎么做呢？

**Comment by LXY02** [comment]
> <img alt="image" width="1329" src="https://private-user-images.githubusercontent.com/7971419/316517608-a89df861-320d-4f5d-82da-8c388cd504c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjUzNjUsIm5iZiI6MTcxMTQyNTA2NSwicGF0aCI6Ii83OTcxNDE5LzMxNjUxNzYwOC1hODlkZjg2MS0zMjBkLTRmNWQtODJkYS04YzM4OGNkNTA0YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMDM1MTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzUzN2U2MjhhMWVmY2RmMDc4ZDRhYWFkY2MwZjllYjU1ZTU3NmQyMmRhMTZmNGM2MDJiMWY2NGY5M2I1MzZlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cGuI4dn8HocyOqWiKWEMmhBk6HMRKVb0fMGVRXHM_a8"> https://stackblitz.com/edit/react-bzbaj8?file=demo.tsx
> 类似这个，用 useWatch 的值才是对的，卸载了就应该是 undefined

谢谢，我知道怎么改了
![useEffect](https://github.com/ant-design/ant-design/assets/26700440/4d6011d1-6a65-41ee-8068-db24990400e8)
