### ISSUE TITLE
Minimal Reproduction link antd@5x: "Syntax Error Invalid left-hand side in assignment"

### ISSUE THREAD

**Issue by angles-n-daemons** [ant-design/ant-design#48083]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fast-flower-jyh2k9?file=%2Findex.js%3A10%2C35)

### Steps to reproduce

Click the "Please provide a link by forking these links [antd@5.x](https://u.ant.design/codesandbox-repro)" button to fork the minimal reproduction link. Note how the error appears on first render.

### What is expected?

No syntax error to appear. The page to load

### What is actually happening?

The below compilation error to appear:

SyntaxError
Invalid left-hand side in assignment

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18.2.0 |
| System | Apple M2 Pro Ventura 13.3 |
| Browser | Arc 1.19.1 (Chromium 119.0.6045.199) |

---
Ran into this today, trying to create a separate issue.

**Comment by zombieJ** [comment]
Seems your reproduce dont fire `Invalid left-hand side in assignment` warning.

**Comment by alyyousuf7** [comment]
I'm also facing same issue.

My codesandbox contains usage example from https://ant.design/docs/react/introduce

```tsx
import React from 'react';
import { DatePicker } from 'antd';

const App = () => {
  return <DatePicker />;
};

export default App;
```

Resulted in:
<img width="477" alt="image" src="https://github.com/ant-design/ant-design/assets/14050128/db47c8e6-b012-455b-8ac2-8e11ab6390fa">

But it seems to be something wrong with CodeSandbox, as I have exact same dependency versions in another CodeSandbox, created last week and it does not have this issue 🤔 

```
antd@5.15.2
react@18.2.0
react-dom@18.2.0
react-scripts@5.0.1
loader-utils@3.2.1
```

**Comment by MadCcc** [comment]
Issue of CodeSandbox. You could use stackblitz as alternative.
