### ISSUE TITLE
Select组件在multiple模式下 onFocus事件无效

### ISSUE THREAD

**Issue by sangxiaolong** [ant-design/ant-design#4808]
#### Environment(required)

- antd version: 2.7.0
- OS and its version: mac os
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

select 组件设置了multiple多选，并且添加了onFocus事件，focus的时候动态获取options

#### What do you expected?

能正确的触发focus事件

#### What happen?

没有触发focus事件，去掉multiple属性就可以触发事件了

**Comment by yesmeck** [comment]
reinstall node_modules.
