### ISSUE TITLE
在高分辨率下有一种“很卡”的感觉 画面不流畅

### ISSUE THREAD

**Issue by icowan** [ant-design/ant-design#4809]
如题
显示器 分辨率2k 及以上

**Comment by afc163** [comment]
可以帮忙缩小范围么，问题太大也不好下手。

**Comment by icowan** [comment]
这就不好弄了，具体我也不知道哪  所有页面的有点卡，在其他机器上也一样，你可以找台2k以上分辨率的机器试试
![](https://ofbudvg4c.qnssl.com/images/2017/02/594A28FF-A438-496C-B192-471F117B78EA.png)

**Comment by afc163** [comment]
这是用了 G2 ？会不会是可视化图表的问题？

**Comment by icowan** [comment]
没有图表的页面也有这种感觉，我觉得应该不是图表的问题。可能是渲染页面的问题，在小尺寸分辨率下并没有卡顿的感觉

**Comment by afc163** [comment]
在 iMac 上试了下没发现卡顿。感觉这个问题我们无从下手，可能需要你帮忙定位一下了~

这里先关了，有任何进一步信息可以继续回复。
