### ISSUE TITLE
Range Picker Calender Must Always Open

### ISSUE THREAD

**Issue by soumojit-technoexponent** [ant-design/ant-design#48099]
### What problem does this feature solve?

We need a prop for the date range picker to show the calendar always. Currently what happens is we have to click on the Calender Icon then the Calender is opened. It is a two-step process. 

### What does the proposed API look like?

API will look like something showCalender. So it will always show the calendar as per the user's requirement.

**Comment by CooperHash** [comment]
Can you provide a reproducible link?

**Comment by afc163** [comment]
```jsx
<RangePicker open />
```

**Comment by soumojit-technoexponent** [comment]
Here is reproduced link
https://stackblitz.com/edit/vitejs-vite-mlqml5?file=src%2FApp.tsx,src%2FTableDateRangeFilter.tsx,package.json,src%2FApp.css&terminal=dev

While using open
Calender is still opened
Although the dropdown is closed
