### ISSUE TITLE
The multilingual feature for the datepicker - Chinese - month - is not working.

### ISSUE THREAD

**Issue by TransonQ** [ant-design/ant-design#48095]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-antd-5-15-3-forked-3t3rlh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu89w3sh00063b6k2pmria5t%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu89w3sg00023b6k6e8dxy9v%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu89w3sg00033b6kannw24ok%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu89w3sg00053b6k7gdtkd1o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu89w3sg00023b6k6e8dxy9v%2522%253A%257B%2522id%2522%253A%2522clu89w3sg00023b6k6e8dxy9v%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu89w3sg00053b6k7gdtkd1o%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu89w3sg00043b6kzb68ptd2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu89w3sg00053b6k7gdtkd1o%2522%252C%2522activeTabId%2522%253A%2522clu89w3sg00043b6kzb68ptd2%2522%257D%252C%2522clu89w3sg00033b6kannw24ok%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu89w3sg00033b6kannw24ok%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. 引入：import cn from "antd/locale/zh_CN";
2.`<ConfigProvider locale={cn}> <DatePicker /></ConfigProvider>`
3. 查看日期选择器中月份显示

### What is expected?

2024 年 3月  - 中文显示

### What is actually happening?

2024 年 Mar

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18.2.21 |
| System | macos 14.4.1 |
| Browser | Chrome 123.0.6312.59 |

**Comment by CooperHash** [comment]
Please grant permissions for CodeSandbox.

**Comment by TransonQ** [comment]
I apologize for the inconvenience. Due to a private update in the sandbox, access was temporarily unavailable. However, the sandbox mentioned earlier is now accessible again. Thank you .
https://codesandbox.io/p/sandbox/ji-ben-antd-5-15-3-forked-3t3rlh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu89w3sh00063b6k2pmria5t%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu89w3sg00023b6k6e8dxy9v%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu89w3sg00033b6kannw24ok%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu89w3sg00053b6k7gdtkd1o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu89w3sg00023b6k6e8dxy9v%2522%253A%257B%2522id%2522%253A%2522clu89w3sg00023b6k6e8dxy9v%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu89w3sg00053b6k7gdtkd1o%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu89w3sg00043b6kzb68ptd2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu89w3sg00053b6k7gdtkd1o%2522%252C%2522activeTabId%2522%253A%2522clu89w3sg00043b6kzb68ptd2%2522%257D%252C%2522clu89w3sg00033b6kannw24ok%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu89w3sg00033b6kannw24ok%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by afc163** [comment]
https://ant.design/components/date-picker#localization

```jsx
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
```

**Comment by afc163** [comment]
https://ant.design/components/date-picker#date-related-components-locale-is-not-working
