### ISSUE TITLE
Default getPopupContainer gives dropdown that scrolls out of view

### ISSUE THREAD

**Issue by wang-yikai** [ant-design/ant-design#48103]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/getpopupcontainer-v5-xrrn3v)

### Steps to reproduce

Open the select dropdown and scroll down. The dropdown will scroll out of view.

### What is expected?

The dropdown should stay in place, which is the same behavior in v4: https://codesandbox.io/p/sandbox/getpopupcontainer-v4-7nx8py

### What is actually happening?

The dropdown will scroll out of view if `getPopupContainer={() => document.body}`, which is the default for `getPopupContainer`.

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

**Comment by MadCcc** [comment]
`getPopupContainer={(node) => node.parentNode}`

**Comment by zombieJ** [comment]
v4 ([reproduce](https://codesandbox.io/p/sandbox/getpopupcontainer-v5-forked-3mhqkq?file=%2Fdemo.js%3A6%2C1)) is a bug that not follow the content scroll. We will not fallback to v4.
