### ISSUE TITLE
多个 Drawer 的打开层级问题

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#48106]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wn1mfy?file=demo.tsx)

### Steps to reproduce

1. 点击 open
2. 点击 Close Drawer
3. 点击 Open Drawer

### What is expected?

当点击 Open Drawer 后，第一层的  Drawer 把 Drawer 2 盖住

### What is actually happening?

没盖住

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
Modal 一样 https://stackblitz.com/edit/react-wn1mfy-xhtvpu?file=demo.tsx，后打开的不能盖住前面打开的

**Comment by linxianxi** [comment]
添加 destroyOnClose 就行了，重新 mount z-index 会重新算

**Comment by zombieJ** [comment]
如果非 `destroyOnClose` 下可以自行控制 `zIndex`。非叠加型的 Drawer 和 Modal 覆盖顺序是业务逻辑。有的时候需要按照打开顺序，有的则是按照优先程度（比如顶层通知、配置无论其他弹层何时打开都需要盖在嘴上弥漫），这是不能说谁对谁错的，因此也不会去做特殊处理。

**Comment by crazyair** [comment]
我知道我的初始问题是什么了，比如一个 width 500 的抽屉，一个 width  250 的抽屉，虽然打开的时候可以控制后打开的覆盖先打开的，但是如果 open 状态保持，F5 刷新页面，顺序可能就会反过来。
