### ISSUE TITLE
Notification 关闭的动画有点闪烁，不够平滑

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#48113]
对比一下之前的版本：

- 当下 https://ant.design/components/notification-cn
- 之前的 https://ant-design-5-9-2.surge.sh/components/notification-cn

**Comment by MadCcc** [comment]
和这个问题一样？https://github.com/ant-design/ant-design/issues/47971

**Comment by afc163** [comment]
有点类似。

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/47971
