### ISSUE TITLE
Badge在CodeSandbox打不开demo

### ISSUE THREAD

**Issue by Roxannej** [ant-design/ant-design#48118]
<img width="722" alt="截屏2024-03-27 下午2 28 08" src="https://github.com/ant-design/ant-design/assets/52034179/3db2a380-fe81-44cb-83b9-a470fd5193fd">
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/duan-dai-antd-5-15-4-vwrxm4?file=%2Fdemo.tsx%3A7%2C34)

### Steps to reproduce

Badge.Ribbon的网站示例代码用CodeSandbox打开，发现报错

### What is expected?

希望CodeSandbox打开正常

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | React18 |
| System | OS |
| Browser | Chorme |

**Comment by MadCcc** [comment]
CodeSandbox 的问题，用 stackblitz 正常
