### ISSUE TITLE
[feature] Positioning of Dropdown menus

### ISSUE THREAD

**Issue by kappa-gooner** [ant-design/ant-design#4811]
Here's the snippet from [codepen](http://codepen.io/sk_tectus/pen/Xpxjqr?editors=0010)

Is there a way to reposition the dropdown to be center aligned with the trigger button?
I feel that some more extensibility would be great for the dropdown component. [This](http://garden.zendesk.com/react-components/#Menu) is a great reference for dropdown menus IMO. 

I'd be happy to raise a PR if you're happy to accept it :1st_place_medal:

**Comment by afc163** [comment]
It is a feature already supported in [dropdown](https://github.com/react-component/dropdown/blob/master/src/placements.js), but the documentation is missing in `antd`. 😓

**Comment by afc163** [comment]
And the direction of pop animation have some problems now.
