### ISSUE TITLE
表格列在搜索情况下，国际化失效

### ISSUE THREAD

**Issue by nqsjd178559344** [ant-design/ant-design#48110]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/shu-xing-shai-xuan-cai-dan-antd-5-15-3-forked-krxdlp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu96vpho0006356g14u7pcga%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu96vpho0002356g58lnhe9d%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu96vpho0003356gfe0ny54q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu971a7700er356gttdgg7e0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu96vpho0002356g58lnhe9d%2522%253A%257B%2522id%2522%253A%2522clu96vpho0002356g58lnhe9d%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu96ws3k0002356g52rnd7wx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A18%252C%2522startColumn%2522%253A8%252C%2522endLineNumber%2522%253A18%252C%2522endColumn%2522%253A8%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu96ws3k0002356g52rnd7wx%2522%257D%252C%2522clu96vpho0003356gfe0ny54q%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu96vpho0003356gfe0ny54q%2522%257D%252C%2522clu971a7700er356gttdgg7e0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu9714hj00en356glf21u1pi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu971a7700er356gttdgg7e0%2522%252C%2522activeTabId%2522%253A%2522clu9714hj00en356glf21u1pi%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. 展开搜索项 2. 搜索111 3. 显示NOT FOUND

### What is expected?

国际化显示正确

### What is actually happening?

国际化显示错误

| Environment | Info |
| --- | --- |
| antd | 5.13.0 |
| React | 18.2.0 |
| System | windows |
| Browser | 123.0.6312.86（正式版本） （64 位） |

**Comment by nqsjd178559344** [comment]
操作如图
![image](https://github.com/ant-design/ant-design/assets/43981368/479e6673-4b82-4fb1-882b-536b7b87dae9)

**Comment by LingJinT** [comment]
let me try
