### ISSUE TITLE
Empty 组件改变 image 会同时改变 description 字体颜色，违反直觉

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#48124]
### Reproduction link

[https://ant.design/components/empty-cn#empty-demo-basic](https://ant.design/components/empty-cn#empty-demo-basic)

### Steps to reproduce

对比 Empty.PRESENTED_IMAGE_SIMPLE 和 Empty.PRESENTED_IMAGE_DEFAULT，两者不只是换了个图片，它会影响 Empty 组件的类名，间接改变了下方文字的颜色，很违反直觉。毕竟 image 组件理论上应该只改变 image。description 的字体颜色应该用 descriptionProps 之类的属性来更改

### What is expected?

更改 image 属性不会改变 description 的字体颜色

### What is actually happening?

更改 image 属性改变了 description 的字体颜色

![image](https://github.com/ant-design/ant-design/assets/5836790/42ce162b-7728-4466-b086-f50671d4b33b) ![image](https://github.com/ant-design/ant-design/assets/5836790/400cf187-ec4f-4840-b08e-689a5517f12e)

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18.2.0 |
| System | macOS |
| Browser | Chrome 121 |

**Comment by zombieJ** [comment]
颜色应该是一样的，这个是个 BUG

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/48131#pullrequestreview-1973150858
