### ISSUE TITLE
Tabs translate when window resizing

### ISSUE THREAD

**Issue by MadFred42** [ant-design/ant-design#48122]
### Reproduction link

[fork](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jlr6sw?file=%2Findex.js)

### Steps to reproduce

You resize window to make tabs wrapper overflow: hidden, and after that you expand window width.

### What is expected?

Overflow is visible, and transform: translate is setting to (0,0). 

### What is actually happening?

Overflow continues to be hidden, and transform: translate does not change.

| Environment | Info |
| --- | --- |
| antd | 4.24.15 |
| React | Next.js 12 |
| System | Windows 11 23H2 |
| Browser | Google Chorme Version 123.0.6312.59 (Official Build) (64-bit) |

---
It works good on localhost though, the issue reproduces only on deployed project.

here's the video of the issue
https://github.com/ant-design/ant-design/assets/78760434/0612fb84-c7b0-452c-81fc-884bd52b26cc

**Comment by MadFred42** [comment]
I cant update link in the issue, so I put it here: 
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jlr6sw?file=%2Findex.js

**Comment by MadFred42** [comment]
updated

**Comment by afc163** [comment]
Cannot reproduce it in https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jlr6sw?file=%2Findex.js%3A21%2C15

**Comment by MadFred42** [comment]
Issue captured on the video, link in description. What I have in the fork I have exactly the same in the project. My project deployed and you can see incorrect tabs behavior (video)

**Comment by MadFred42** [comment]
I guess it's a v4.23.6 problem,  I updated the packages and it seems good now so far

**Comment by afc163** [comment]
So it is resolved, right?

**Comment by MadFred42** [comment]
Yes, it is resolved
