### ISSUE TITLE
V5的Sider内嵌Menu时，从收缩状态变为展开状态的过渡动画效果不平滑，V4则不存在

### ISSUE THREAD

**Issue by metouch** [ant-design/ant-design#48121]
### Reproduction link

[https://ant-design.antgroup.com/components/layout-cn?from=msidevs.net](https://ant-design.antgroup.com/components/layout-cn?from=msidevs.net)

### Steps to reproduce

通过官方文档即可复现：
1.访问antd官方文档，找到Layout组件

2.找到示例“自定义触发器”

3.点击触发器，触发收缩，展开，可以观察到展开时的动画明显抖动不平滑

### What is expected?

展开的动画过渡效果应该是平滑的

### What is actually happening?

展开的动画过渡效果在开始时出现了抖动

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18 |
| System | windows10，ubuntu22.04 |
| Browser | chrome 120.0.6099.224 |

**Comment by metouch** [comment]
[录屏 2024年03月27日 16时14分52秒.webm](https://github.com/ant-design/ant-design/assets/13144005/c0f91d90-de03-4324-9cda-2a60e90beb85)

**Comment by metouch** [comment]
可以通过修改以下样式去解决问题
`.ant-menu-inline-collapsed >.ant-menu-item{
  inset-inline-start: 0;
  padding-inline: calc(50% - calc(var(--ant-font-size-lg) / 2) - var(--ant-menu-item-margin-inline));
  text-overflow: clip;
}`
如将其修改为
`.ant-menu-inline-collapsed >.ant-menu-item{
  inset-inline-start: 0;
  padding-inline: calc(40px - calc(var(--ant-font-size-lg) / 2) - var(--ant-menu-item-margin-inline));
  text-overflow: clip;
}`

[录屏 2024年03月27日 16时25分45秒.webm](https://github.com/ant-design/ant-design/assets/13144005/46dbd1e8-0473-4e5e-939f-4cda74db7be9)

卡顿是视频录制的原因，实际不卡顿。
但感觉这并不是一个好的方案，仍需官方修复

**Comment by metouch** [comment]
可以通过修改以下样式去解决问题
`
.ant-menu-inline-collapsed >.ant-menu-item{ 

    inset-inline-start: 0; 

    padding-inline: calc(50% - calc(var(--ant-font-size-lg) / 2) - var(--ant-menu-item-margin-inline)); 

    text-overflow: clip; 
}

`


如将其修改为
.ant-menu-inline-collapsed >.ant-menu-item{ inset-inline-start: 0; padding-inline: calc(40px - calc(var(--ant-font-size-lg) / 2) - var(--ant-menu-item-margin-inline)); text-overflow: clip; }

**Comment by metouch** [comment]
``
第三方第三发萨芬
``

**Comment by metouch** [comment]
可以通过修改以下样式解决问题
``
.ant-menu-inline-collapsed >.ant-menu-item{
  inset-inline-start: 0;
  padding-inline: calc(50% - calc(var(--ant-font-size-lg) / 2) - var(--ant-menu-item-margin-inline));
  text-overflow: clip;
}
``
例如，将其修改为
``
.ant-menu-inline-collapsed >.ant-menu-item{
  inset-inline-start: 0;
  padding-inline: calc(40px - calc(var(--ant-font-size-lg) / 2) - var(--ant-menu-item-margin-inline));
  text-overflow: clip;
}
``
实际效果，录制的视频存在卡顿，实际不存在
[录屏 2024年03月27日 16时25分45秒.webm](https://github.com/ant-design/ant-design/assets/13144005/6f66e9be-0cae-479f-8f0f-6a070831704e)
这可以充作临时解决方案，但还是期待官方解决这个问题

**Comment by Atw-Lee** [comment]
https://ant-design.antgroup.com/components/menu-cn#menu-demo-sider-current 感觉单独使用也卡顿呢
