### ISSUE TITLE
Table的expandedRowRender建议

### ISSUE THREAD

**Issue by Catlite91** [ant-design/ant-design#4813]
Table的expandedRowRender是否可以作为rowSelection的参数，而非作用在整个Table上。
很多场景并不是所有行信息都有expandedRow的需求。

**Comment by ddcat1115** [comment]
expandedRowRender 可以拿到 record 参数啊，判断展示就可以，而且展开和可选在意义上很不一样，放进去还是不太合适

**Comment by Catlite91** [comment]
@ddcat1115 我说的是每行的加号➕按钮，这个不应该和checkbox是一样在rowSelection配置的么？
还有通过record怎么去掉➕？

**Comment by ddcat1115** [comment]
checkbox 是用来选中的，加号和选中没有关系，如果要隐藏某些特殊行的加号，可以结合样式：

http://codepen.io/ddcat1115/pen/VPEWgw?editors=1111

**Comment by afc163** [comment]
➕是展开，✔️是选择，两个没关系。

**Comment by Catlite91** [comment]
thanks!
