### ISSUE TITLE
设置 Select 组件字体fontSize: 12px会导致输入文本左移

### ISSUE THREAD

**Issue by mafx1024** [ant-design/ant-design#48143]
### Reproduction link

[https://ant.design/components/select-cn#select-demo-basic](https://ant.design/components/select-cn#select-demo-basic)

### Steps to reproduce

1. 设置 Select 字体为 12px;
2. 在输入框缓慢输入文字；
3. 大致输入10个文字左右，文本发生左移问题

https://github.com/ant-design/ant-design/assets/93925944/43ff33de-b9a4-4b25-93ea-24bc21493252

### What is expected?

文本不发生左移问题

### What is actually happening?

文本发生左移

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18.0.0 |
| System | macOS(arm)/14.4 |
| Browser | Chrome/123.0.6312.59 |

**Comment by zombieJ** [comment]
神奇，看起来像是精度问题

**Comment by MadCcc** [comment]
试试 token 改字号
