### ISSUE TITLE
DatePicker disabledDate 会多打印一次今天的当前年月日时分秒

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#48140]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-lh4lu6?file=demo.tsx)

### Steps to reproduce

1. 打开控制台
2. 打开 DatePicker

### What is expected?

所有的 date 都是 年月日 0:0:0

### What is actually happening?

当天显示的是当前的时分秒

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
`disabledDate` 本身并不保证单次触发，所有会涉及时间日期禁用判断的交互都会触发 `disabledDate` 判断以防止逃逸的情况。例如在文本修改、时间微调、确认提交、面板切换时都会多次触发。

在这个 case 中，包含日期时间的判断来自于 `showNow` 的判断。`showNow` 本身不针对 Picker 类型，只针对当下。不同面板都会使用 `getNow` 进行填充并进行一次判断。
