### ISSUE TITLE
slider滑块多节点滑动时， tooltip 闪烁

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#48149]
### Reproduction link

[https://ant.design/components/slider-cn](https://ant.design/components/slider-cn)

### Steps to reproduce

 参看gif，两个滑动点，只要越过其中一个点，就出现了
![example](https://github.com/ant-design/ant-design/assets/29728228/630897ba-a694-4bc1-85aa-ba659c4e5b55)

### What is expected?

不要闪烁

### What is actually happening?

会有闪烁

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18 |
| System | windows 10 |
| Browser | chrome |

**Comment by yinhw0210** [comment]
我想我可以尝试解决一下这个问题，这个问题是rc-slider引起的，在rc-slider中，所有已添加句柄的z-index始终为1，我认为被拖动（激活状态下）句柄的z-index应该高于正常状态下的句柄的z-index值。 @MadCcc

**Comment by yoyo837** [comment]
PR welcome.

**Comment by yoyo837** [comment]
> 我想我可以尝试解决一下这个问题，这个问题是rc-slider引起的，在rc-slider中，所有已添加句柄的z-index始终为1，我认为被拖动（激活状态下）句柄的z-index应该高于正常状态下的句柄的z-index值。 @MadCcc

个人猜测不是这个原因，它是松手后的闪烁，并不是拖动中的状态。

**Comment by yoyo837** [comment]
> > > 我想我可以尝试解决一下这个问题，这个问题是rc-slider引起的，在rc-slider中，所有已添加句柄的z-index始终为1，我认为被拖动（激活状态下）句柄的z-index应该高于正常状态下的句柄的z-index值。 @MadCcc
> > 
> > 
> > 个人猜测不是这个原因，它是松手后的闪烁，并不是拖动中的状态。
> 
> 我明白您的意思了 这个问题说的确实是松手后的闪烁 我再去尝试一下 然后我认为这个拖动中触发也算是一个需要得到解决的问题吧 还是说设计初就是这样考虑的

算一个另外的小问题，可以尝试一并修复
