### ISSUE TITLE
When setting timezone to GMT 0 (UTC), the TimePicker displays the value incorrectly.

### ISSUE THREAD

**Issue by gabrielsantosdev** [ant-design/ant-design#48160]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/change-on-scroll-antd-5-15-4-forked-dfm9zl?file=%2Fdemo.tsx%3A40%2C5-41%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clubmom7g00063p6lqwd9qpi3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clubmom7g00023p6l74pk7d7e%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clubmom7g00033p6lbzdm2ic9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clubmom7g00053p6la5i3yp98%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B49.68689994251679%252C50.31310005748321%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clubmom7g00023p6l74pk7d7e%2522%253A%257B%2522id%2522%253A%2522clubmom7g00023p6l74pk7d7e%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clubmzbjd00023p6ldj6kf0yo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A40%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A41%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clubmzbjd00023p6ldj6kf0yo%2522%257D%252C%2522clubmom7g00053p6la5i3yp98%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clubmom7g00043p6l24a0gd80%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clubmom7g00053p6la5i3yp98%2522%252C%2522activeTabId%2522%253A%2522clubmom7g00043p6l24a0gd80%2522%257D%252C%2522clubmom7g00033p6lbzdm2ic9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clubmom7g00033p6lbzdm2ic9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

In the example above:
* Select a time (Local timezone of the machine)
* Validate the time displayed in the watch section against the value in the picker
* Click on Set time
* Validate value in the picker against the value in the watch section.
* Notice that when we open the timePicker, the column values are correct, but the display is inaccurate 

### What is expected?

Time Picker to accurately display the value saved in the form.

### What is actually happening?

TimePicker value is different from the value we have stored in the form.

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18 |
| System | MacOS |
| Browser | Microsoft Edge Version 123.0.2420.53 (Official build) (arm64) |

---
Using dayJS library as it's the official supported library from the design system, I have a use case where the user can input a specified time using a set timezone, this timezone can vary, and it works fine for any other timezone offset except ones in UTC. In this specific case, the value that the timePicker displays is incorrect, but the value logged by the form value is correct (See e.g above) this seems to be an visual issue in the way the TimePicker displays it's info.

**Comment by zombieJ** [comment]
Picker will set `locale` to dayjs object before format to ensure it get correct format with locale. Which means it's not enough to set timezone only and should provide fully local info. Pls ref official doc of ConfigProvider with correct locale handle.

**Comment by joebnb** [comment]
> Picker will set `locale` to dayjs object before format to ensure it get correct format with locale. Which means it's not enough to set timezone only and should provide fully local info. Pls ref official doc of ConfigProvider with correct locale handle.

this not resolve all problem.


for example，some database are drop timezone info when saving

<img width="1073" alt="image" src="https://github.com/ant-design/ant-design/assets/1646883/31aa58c1-d9f2-47b8-9fb1-905a424568ce">

at this moments, when timestamp responsed to frontend,there no timezone info, set local will not take effect,may this part expose a config to developer to decied which should transform will better.


eg: trimAsUtc0: bool | display_local

mean all val will use as utc 0 , and when date picker display and select will show as local time ,when it respond onchange is still utc0

**Comment by KevinMoran99** [comment]
I got a similar issue, upgrading dayjs did it for me.

I got the bug on dayjs v1.11.10, once I upgraded to v1.11.12 (latest at time of writing), everything worked correctly.
