### ISSUE TITLE
Values of Form.List

### ISSUE THREAD

**Issue by archisketch-thangly** [ant-design/ant-design#48165]
### Discussed in https://github.com/ant-design/ant-design/discussions/48164

<div type='discussions-op-text'>

<sup>Originally posted by **archisketch-thangly** March 29, 2024</sup>
When i use Form.List and submit, i receive values as bellow. How can receive values with only fields as Form.Item's name?

![image](https://github.com/ant-design/ant-design/assets/105255382/1e39de2a-c1f1-467b-81f9-11f0261af605)
</div>

**Comment by zombieJ** [comment]
```diff
-- <Button onClick={add} />
++ <Button onClick={() => add()} />
```

**Comment by archisketch-thangly** [comment]
@zombieJ thanks, it is solved
