### ISSUE TITLE
Table component border radius inconsistency on top corners vs bottom corners when "bordered"

### ISSUE THREAD

**Issue by Aarthysekar** [ant-design/ant-design#48176]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-kcq96d?file=demo.tsx)

### Steps to reproduce

Use "bordered={true}" in Table component. 
Border radius on top corners are more than the bottom corners. 

### What is expected?

border radius to be same all sides when bordered in table component

### What is actually happening?

border radius is inconsistent in top & bottom corners
<img width="670" alt="Screenshot 2024-03-29 at 8 33 23 PM" src="https://github.com/ant-design/ant-design/assets/27697052/486f49dd-d766-4564-8c22-f30ba61381e6">

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18.2.0 |
| System | windows 10 |
| Browser |  Chrome 122.0.6261.69 |

**Comment by afc163** [comment]
It is by designed.
