### ISSUE TITLE
Input and InputNumber height is inconsistent

### ISSUE THREAD

**Issue by Aarthysekar** [ant-design/ant-design#48177]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-dk6wkz?file=demo.tsx)

### Steps to reproduce

render input and input number component and inspect the height. 

### What is expected?

Height should be same for input and input number

### What is actually happening?

Height is inconsistent for input and input number. Input height is 32px and InputNumber height seems to be 30px.
<img width="1440" alt="Screenshot 2024-03-29 at 8 42 32 PM" src="https://github.com/ant-design/ant-design/assets/27697052/de2fbdc1-dbb6-434c-bc38-c962ca0d4f54">
<img width="1438" alt="Screenshot 2024-03-29 at 8 40 32 PM" src="https://github.com/ant-design/ant-design/assets/27697052/c491d973-78c7-47e0-8848-1a3221559c66">

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 122.0.6261.69 |

**Comment by afc163** [comment]
<img width="975" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/84318cc5-b9ef-41a8-ac34-741125b158d0">

It is 32px of InputNumber's outer element.
