### ISSUE TITLE
Tree组件支持多节点拖拽

### ISSUE THREAD

**Issue by okjack365** [ant-design/ant-design#48180]
### What problem does this feature solve?

组件：<Tree.DirectoryTree multiple />   
问题：当前只支持拖拽单个节点.   
需求：支持拖拽多个选中的节点

### What does the proposed API look like?

1.当前onDrop的类型为: function({event, node, dragNode, dragNodesKeys})  
2.期望更改后的onDrop类型为：  
function({event, node, dragNodes, dragNodesKeys})  
其中：  
dragNodes的值类似：[{key: '1', title: 'node1'}, {key: '2', title: 'node2'}]  
dragNodesKeys的值类似：['1', '2']

**Comment by yuanguandong** [comment]
同求

**Comment by xmengweb** [comment]
同求

**Comment by afc163** [comment]
Duplicate of #38942
