### ISSUE TITLE
Bug: Table overflow wrong when window is small

### ISSUE THREAD

**Issue by CooperHash** [ant-design/ant-design#48181]
### Reproduction link

[https://ant.design/components/table-cn](https://ant.design/components/table-cn)

### Steps to reproduce

click to part `Virtual list`
make window width become small

### What is expected?

Table overflow is correct.

### What is actually happening?

Table‘s Virtual list’s part overflow is not correct.

![image](https://github.com/ant-design/ant-design/assets/73218815/1127e9c6-ac05-4602-a276-fcdc3758dc14)

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by MadCcc** [comment]
It's debug demo, we keep this for debug use.
