### ISSUE TITLE
Table 的 redraw() 功能

### ISSUE THREAD

**Issue by hongkang** [ant-design/ant-design#4818]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

#### What do you expected?

建议增加类似于 JqueryTable 的 redraw() 功能，比如说删除某一行后，根据当前的页码，排序，搜索项重新 请求服务器数据，就好比触发一次 onchange 调用。
请问如果不用redraw的话，还有什么好的方式吗？

**Comment by yesmeck** [comment]
> 根据当前的页码，排序，搜索项重新 请求服务器数据

自己处理。有问题的话建议到 SegmentFault 或 StackOverflow 上提问。
