### ISSUE TITLE
tsconfig.json 需要关闭 strictNullChecks 吗

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#48192]
### What problem does this feature solve?

比如如下错误

### What does the proposed API look like?

移除 `strictNullChecks: true` 配置

antd 已经开了配置，无法提供示例，现使用 `rc-table` 示例下效果，当 `rc-table` 开启 `strictNullChecks: true` 后有 `Found 243 errors in 46 files.` 错误，其中是这样的问题：

<img width="718" alt="image" src="https://github.com/ant-design/ant-design/assets/7971419/307af7de-b6db-4b26-bc54-f676451bff68">

`additionalCellProps` 默认值是 undefined，但是在 `80` 行会提示错误。

该项配置是 undefined 无法再次赋值其他类型，但是用户使用习惯上，是不友好的，因此需要关闭此配置

**Comment by afc163** [comment]
没看出来为啥要关闭此配置，strictNullChecks 是更严格的策略，应该保留。

**Comment by crazyair** [comment]
这个是 undefined 不能设置其他类型， string number 等，但是这个确实平常也能这样用，比如
```tsx
interfalce DemoProps{
    id?:stirng;
}
```

id 其实就是 undefined | string 的

strictNullChecks 这个感觉是 typescript 过度设计的东西

**Comment by afc163** [comment]
上面的代码可以修正成如下：

```
const additionalProps = column?.onHeaderCell?.(column) || {};
```

<img width="744" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/dd193b44-5daf-4869-928b-f1cb9d67eb1b">

**Comment by crazyair** [comment]
![image](https://github.com/ant-design/ant-design/assets/7971419/5917ed3d-c632-4f92-a83f-3e598956191f)

**Comment by crazyair** [comment]
> ![image](https://private-user-images.githubusercontent.com/7971419/318672791-5917ed3d-c632-4f92-a83f-3e598956191f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDEwMTAsIm5iZiI6MTcxMjA0MDcxMCwicGF0aCI6Ii83OTcxNDE5LzMxODY3Mjc5MS01OTE3ZWQzZC1jNjMyLTRmOTItYTgzZi0zZTU5ODk1NjE5MWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDY1MTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTEyYzVhMzU0MTRmOGMzZjY3ZjdiY2RmNTMxNjI1ZWQ3MDg1ZWEwMWI0NDQ3ZTRkYjhlMTE3NTU2MjA5M2VkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QakEKHSzxxQaos2Aprtyb7qg6vLg1uessSrkDKwiuBg)

这个报错，需要改成这样 `let expandRowNode: React.ReactElement | undefined;` 下面就不报错了

**Comment by crazyair** [comment]
那就有报错的地方，就加个 `| undefined` 吧

**Comment by afc163** [comment]
+1，改了才是对的。
