### ISSUE TITLE
Paragraph一行时展开后显示不正确

### ISSUE THREAD

**Issue by datoou** [ant-design/ant-design#48200]
### Reproduction link

[https://ant.design/components/typography-cn#components-typography-demo-ellipsis-controlled](https://ant.design/components/typography-cn#components-typography-demo-ellipsis-controlled)

### Steps to reproduce

rows=1时，点击展开。
![image](https://github.com/ant-design/ant-design/assets/52907799/44416afc-722b-4119-b65b-b3f88a1b7387)

### What is expected?

内容不超出

### What is actually happening?

内容超出

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18 |
| System | windows 11 |
| Browser | edge 123.0.2420.65 |

**Comment by zombieJ** [comment]
网络问题，试一下镜像站：https://ant-design.antgroup.com/components/typography-cn#components-typography-demo-ellipsis-controlled

这个可以优化一下，SSR 的时候用 css ellipsis，注水后再恢复成 js 计算。

**Comment by crazyair** [comment]
> 网络问题，试一下镜像站：https://ant-design.antgroup.com/components/typography-cn#components-typography-demo-ellipsis-controlled
> 
> 这个可以优化一下，SSR 的时候用 css ellipsis，注水后再恢复成 js 计算。

你理解错了呀，跟注水没关系，是已经完成后，点击 Switch 展开后超出了
