### ISSUE TITLE
Pagination期望增加一个direction

### ISSUE THREAD

**Issue by coding-ice** [ant-design/ant-design#48203]
### What problem does this feature solve?

控制Pagination的方向

### What does the proposed API look like?

direction：'start' | 'center' | 'end'

**Comment by catmiao8** [comment]
你希望的效果是什么样的呢

**Comment by GetWebHB** [comment]
> 你希望的效果是什么样的呢

这个feat，我会提交PR哈 感谢～

**Comment by yoyo837** [comment]
同时考虑到RTL，是不是叫start, center, end？

**Comment by GetWebHB** [comment]
> 同时考虑到RTL，是不是叫start, center, end？

嗯嗯 这样会更好一些

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/49562
