### ISSUE TITLE
Input Search 需要自定义设置搜索框位置

### ISSUE THREAD

**Issue by CooperHash** [ant-design/ant-design#48206]
### Reproduction link

[https://ant.design/components/input-cn#components-input-demo-search-input](https://ant.design/components/input-cn#components-input-demo-search-input)

### Steps to reproduce

查看components-input-demo-search-input

### What is expected?

需要一个props能自定义搜索框在左边还是右边

有时候需要这样的效果，当然可以通过antd的Input组件自己写
但是{Search} = Input，antd的Search还是有必要给自定义排布的props
![image](https://github.com/ant-design/ant-design/assets/73218815/01553e26-dcc4-45cf-84ac-2b353bcb2314)

### What is actually happening?

搜索框定在右边不能变
![image](https://github.com/ant-design/ant-design/assets/73218815/a3b9f08c-7109-41f1-9202-0f81e3797968)

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
See https://stackblitz.com/edit/react-lqcwjb?file=demo.tsx
