### ISSUE TITLE
Popover not closing when content is in focus

### ISSUE THREAD

**Issue by theiliad** [ant-design/ant-design#48219]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wwcjcv?file=demo.tsx)

### Steps to reproduce

1. Create a popover with `click` trigger
2. Include an Input in content, and focus onto it
3. Press ESC to close the popover

### What is expected?

Popover should close at this point

### What is actually happening?

Popover stays open

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18.2.0 |
| System | Mac Sonoma |
| Browser | Chrome 122.0.6261.112 |

## Additional comments
There was an update in 5.16.0 to add ESC support for Popover, however it seems to only work if you're focused on the trigger.

**Comment by zombieJ** [comment]
It can not tell what does developer want on the popover operation. For example:
* an opened Select component in the Popover.
* Modal nested in the Popover.
* Customize logic to press esc to clear the Input.

We can not tell what should be. But you can HOC on it to handle all the case:

https://stackblitz.com/edit/react-wwcjcv-iv1hei?file=demo.tsx
