### ISSUE TITLE
Copy & Paste feature in Table component

### ISSUE THREAD

**Issue by cloudmu** [ant-design/ant-design#4821]
#### Environment

- antd version: 2.7.0
- OS and its version:  Win10, OS X
- Browser and its version:  Chrome, etc.

#### What did you do? Please provide steps to re-produce your problem.
Tried to copy and paste content in the [Table](https://ant.design/components/table/) component.  Currently it's not supported.

#### What do you expected?
The [Table](https://ant.design/components/table/) component is already great. However,  it is missing one important feature: Copy & Paste.  If would be neat to allow end user to copy cells/rows, and paste to other area of the table, similar to spreadsheets like Google doc or Excel.

See the Copy & Paste support in [ag-Grid](https://www.ag-grid.com/example.php).

**Comment by ddcat1115** [comment]
Maybe you can try [editable-cells](https://ant.design/components/table/#components-table-demo-edit-cell) or [editable-rows](https://ant.design/components/table/#components-table-demo-edit-row)

or just render a input in which cell you want to paste into

**Comment by cloudmu** [comment]
@ddcat1115 thanks. But Copy & paste is very different use case. It typically deals with a block of areas of many cells, instead of single cell/row, and it works with clipboard, so it can copy and paste outside of the Table.

**Comment by benjycui** [comment]
I think this feature it hard to implement in `antd.Table`.

Maybe you can try to implement your own React table, and PR to this [list](https://ant.design/docs/react/recommendation), thanks.
