### ISSUE TITLE
DatePicker  minDate和maxDate  时分秒无效

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design#48212]
### Reproduction link

[https://ant.design/components/date-picker-cn#components-date-picker-demo-date-range](https://ant.design/components/date-picker-cn#components-date-picker-demo-date-range)

### Steps to reproduce

把format  更换成YYYY-MM-DD HH:mm  minDate 和maxDate 设置 时 分 无效 依然可以选中

### What is expected?

希望能 disable

### What is actually happening?

-

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18 |
| System | mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
这是预期的，`min/maxDate` 只对日期面板生效。面板上日期和时间是分开的，要用 `disabledHour` 系列来控制时间禁用。
