### ISSUE TITLE
Select 利用 optionRender 自定义渲染option 时，回调方法参数中增加当前 option 是否选中的参数

### ISSUE THREAD

**Issue by canyuegongzi** [ant-design/ant-design#48225]
### What problem does this feature solve?

自定义渲染 option 时需要快速的知道当前option  是否选中，目前参数中无类似的参数，只能通过onchange、额外的变量记录选中的值来判断，逻辑比较冗余。

### What does the proposed API look like?

(option: FlattenOptionData<BaseOptionType> , info: { index: number }) => React.ReactNode （现在的）
(option: FlattenOptionData<BaseOptionType> , info: { index: number; isSelect }) => React.ReactNode（期望，当然字段名可以再斟酌）

**Comment by zombieJ** [comment]
> 只能通过onchange、额外的变量记录选中的值来判断，逻辑比较冗余。

HOC 的目的就是用于这类需求的拓展，封装过一次后就可以随意使用了哈~
