### ISSUE TITLE
当Paragraph的ellipsis collapsible为collapsible时关闭按钮文案错误

### ISSUE THREAD

**Issue by Percivalll** [ant-design/ant-design#48227]
### Reproduction link

[https://codepen.io/percivalllll/pen/RwOjvzm](https://codepen.io/percivalllll/pen/RwOjvzm)

### Steps to reproduce

点击“more”按钮

### What is expected?

应该是“less”按钮

### What is actually happening?

展开的文案最下方依然是“more”按钮

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18.0.33 |
| System | macOS |
| Browser | Google Chrome 版本 123.0.6312.86（正式版本） (arm64) |

**Comment by zombieJ** [comment]
`more` 是你自己提供的哈，你应该这么写：

```diff
-- symbol: "more"
++ symbol: (expanded) => expanded ? 'less' : 'more',
```
