### ISSUE TITLE
OptGroup should have option to be selectable

### ISSUE THREAD

**Issue by jbadger** [ant-design/ant-design#4823]
There should be an option to allow users to select the option group header.

```
A
  1
  2
B
  3
  4
```

Right now, only 1, 2, 3, and 4 are selectable but there are cases where selecting A or B would be appropriate.

**Comment by afc163** [comment]
Sorry, OptGroup is only a seperator for categoring Options. If you want to select A or B, you can try make them as a normal Option and use `style.margin` to diff from other options.
