### ISSUE TITLE
FloatButton should expose other button props

### ISSUE THREAD

**Issue by sparrowek** [ant-design/ant-design#48234]
### What problem does this feature solve?

Ability to set other button props eg. disabled, loading, htmlType etc.

### What does the proposed API look like?

Expose other props from Button type

**Comment by afc163** [comment]
It is not a Button actually.

**Comment by sparrowek** [comment]
It is a pity then because you cannot use many features like a loading indicator for a floating save button.

**Comment by MadCcc** [comment]
Can you list all properties you want here?

**Comment by sparrowek** [comment]
Currently, I am missing disabled, htmlType, and loading.
It would be also good to have direction='vertical' | 'horizontal' on FloatButton.Group like in other ant components.

**Comment by li-jia-nan** [comment]
Hi, Can you provide a specific scenario to explain why you need to change the htmlType ?

**Comment by sparrowek** [comment]
The floating button can submit a form defined elsewhere

**Comment by trond-snekvik** [comment]
This has not been completed, only one of the missing props have been added.
