### ISSUE TITLE
Select单选模式下支持反选取消

### ISSUE THREAD

**Issue by Sharang-heng** [ant-design/ant-design#48238]
### What problem does this feature solve?

通过一个参数就能控制反选的话就不需要自己再手动控制onSelect然后对比是否与上一次的值一致这一系列操作了，使用起来会方便很多

### What does the proposed API look like?

提供参数控制是否支持反选

**Comment by zombieJ** [comment]
> 通过一个参数就能控制反选的话就不需要自己再手动控制onSelect然后对比是否与上一次的值一致这一系列操作了，使用起来会方便很多

HOC 就是做这个用途的哈，封装一个 Select HOC 组件就都可以通用了~
