### ISSUE TITLE
4.24.16 Modal中存在Form，调用resetFields异常

### ISSUE THREAD

**Issue by Ashiria7** [ant-design/ant-design#48231]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/resetfields-bug-v32tzd?file=%2Fdemo.tsx%3A20%2C5)

### Steps to reproduce

1. 点击复现链接进入demo
2. 点击edit，此时form初始化initialValues为{price: "aaaa"}
3. 点击Modal的Cancel，此时initialValues重置为空对象
4. 点击Create，查看输入框内容，还是之前的"aaaa"
5. 点击Modal的Cancel，再点击Create，查看输入框内容，清空了

### What is expected?

表单应该重置为空

### What is actually happening?

表单没有重置

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | macOS 14.1 |
| Browser | Chrome 123 |

---
antd版本降级到4.23.3没有此问题

**Comment by crazyair** [comment]
没有复现

**Comment by Ashiria7** [comment]
不好意思，昨天给同事演示把版本降级了，现在改回去了 @crazyair

**Comment by crazyair** [comment]
```tsx
  useEffect(() => {
    if (visible) {
      setTimeout(() => {
        formRef.resetFields();
      }, 0);
    }
  }, [visible]);
```

**Comment by Ashiria7** [comment]
我知道可以通过setTimeout解决这个问题，issue中的demo可能更贴近我的使用场景，我写了另外两个demo进行测试，一个是在隐藏的Modal中，一个是在隐藏的div中，均在表单显示的时候重置initialValues，然后在隐藏的时候调用resetFields，在显示表单，隐藏的div是可以的，但是隐藏的Modal中不行。

* 表单在隐藏的div中
操作顺序：Clear -> Hide -> Reset -> Show
https://codesandbox.io/p/sandbox/ant-form-reset-in-hidden-div-2pk5tr?file=%2Fdemo.tsx

* 表单在隐藏的Modal中
操作顺序：Show -> Cancel -> Clear -> Reset -> Show
https://codesandbox.io/p/sandbox/ant-form-reset-in-hidden-modal-n62ps6?file=%2Fdemo.tsx%3A16%2C1

**Comment by crazyair** [comment]
如果在意的话，我不建议用 resetFields 清理表单，而是用 form 实例卸载的方式清理。我推荐个 Modal + Form 的方式：
1. https://zhuanlan.zhihu.com/p/388222294
2. https://github.com/ant-design/ant-design/pull/47677
