### ISSUE TITLE
Drawer组件icon关闭图标和标题存在重叠问题，经过验证发现是官方在用户传入的icon组件外层套了一个button标签

### ISSUE THREAD

**Issue by davinyue** [ant-design/ant-design#48240]
### Reproduction link

[codesandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-r22gcg?file=%2Findex.js%3A24%2C7)

### Steps to reproduce

<Drawer {...this.props} closeIcon={
        <Button icon={<RollbackOutlined />}>关闭</Button>
      }>
        {this.props.children}
</Drawer>

### What is expected?

关闭图标和标题正常展示

### What is actually happening?

关闭图标和标题出现重叠

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18.2.0 |
| System | win11 |
| Browser | chrome124.0.6367.18 |

**Comment by davinyue** [comment]
请看样例https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-r22gcg?file=%2Findex.js%3A24%2C7，但是antd样式丢失了，不知道在codesandbox中如何解决样式丢失问题

**Comment by zombieJ** [comment]
从 a11y 角度出发，按钮需要有一个语义化的元素容器。`closeIcon` 的语义本身也是设置图标，而不是渲染关闭按钮。如果需要添加一个按钮可以考虑直接在 `title` 里加上哈：

https://stackblitz.com/edit/react-fbazgt?file=demo.tsx
