### ISSUE TITLE
Antd Datepicker allow to type value before minDate

### ISSUE THREAD

**Issue by farhanlatheef** [ant-design/ant-design#48265]
### Reproduction link

[https://farhan-ck.neetorecord.com/watch/299ae08a-8d6c-4ff1-8b98-7270076e6e65](https://farhan-ck.neetorecord.com/watch/299ae08a-8d6c-4ff1-8b98-7270076e6e65)

### Steps to reproduce

Go to https://ant.design/components/date-picker#API
- Go to minDate and maxDate section
- Enter a date before minDate

### What is expected?

User should not able to enter date that is before minDate.

### What is actually happening?

User is able to enter date that is before minDate.

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18 |
| System | macOS sonama 14.3 |
| Browser | Chrome 123 |

**Comment by zombieJ** [comment]
Typing will not fire `onChange` event, but this should be clear on the input field.

**Comment by IzelLight** [comment]
If you use datepicker with time format DD/MM/YYYY HH:mm and set minDate to 17/09/2026 09:00 for example you can input a value date before minDate (only time) for example 17/09/2026 08:00 as valid value. I think this is not correct
