### ISSUE TITLE
Ant Design  的 Calendar 组件支持周视图

### ISSUE THREAD

**Issue by SoftwareKing** [ant-design/ant-design#48272]
### What problem does this feature solve?

Ant Design 的 Calendar 组件支持周视图

### What does the proposed API look like?

Ant Design 的 Calendar 组件支持周视图

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/16440

**Comment by SoftwareKing** [comment]
@afc163 重复了，然后解决方案呢？

**Comment by afc163** [comment]
@SoftwareKing 目前还没有计划开发，欢迎讨论 RFC 和参与开发，同时社区内也有不少的替代方案可以参考选用：https://github.com/jquense/react-big-calendar
