### ISSUE TITLE
add ```addonAfter``` and ```addonBefore``` to ```Select``` component

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#48274]
### What problem does this feature solve?

Properties ```addonAfter``` and ```addonBefore``` are supported by ```Input``` but not by ```Select``` component.
My purpose is to display an addonAfter in my Select to show a clickable icon.

### What does the proposed API look like?

Property: __addonAfter__
Description: The label text displayed after (on the right side of) the input field
Type: ReactNode
Default: -

Property: __addonBefore__
Description: The label text displayed before (on the left side of) the input field
Type: ReactNode
Default: -

```html
<Select
   placeholder="Select an option"
   options={options}
   addonAfter={<Icon component={FaEye} onClick={() => doSomething()} />}
/>
```

**Comment by afc163** [comment]
Try Space.Compact https://github.com/react-component/tabs/releases/tag/v15.0.0

**Comment by shamseer-ahammed** [comment]
+1

**Comment by huykon** [comment]
any new for this?

**Comment by crazyair** [comment]
https://zhuanlan.zhihu.com/p/422752055

**Comment by azakharo** [comment]
> Try Space.Compact https://github.com/react-component/tabs/releases/tag/v15.0.0

It doesn't help if Select is in a form.
I use react-hook-form. The select is wrapped by FormItem. FormItem needs Select (not Space.Compact) as a direct child.

**Comment by Eriktse** [comment]
I found a way that maybe useful. I create a new custom component named "SpaceAddon" and use it in tag "<Space.Compact>".

```tsx
// components/SpaceAddon.tsx
import { CSSProperties } from "react"
export const SpaceAddon = ({position, children}: {position: "left" | "middle" | "right", children: React.ReactNode}) => {
    const divStyle: CSSProperties = {
        padding: "0 8px",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderTop: "1px solid #d9d9d9",
        borderBottom: "1px solid #d9d9d9",
        background: "rgba(0,0,0,0.02)",
        whiteSpace: "nowrap"
    }
    if(position === "left")Object.assign(divStyle, {
        borderTopLeftRadius: "6px",
        borderBottomLeftRadius: "6px",
        borderLeft: "1px solid #d9d9d9",
    })
    if(position === "right")Object.assign(divStyle, {
        borderTopRightRadius: "6px",
        borderBottomRightRadius: "6px",
        borderRight: "1px solid #d9d9d9",
    })
    return <div style={divStyle}>
        {children}
    </div>
}
```

then use it like this, **remember to pass the param "position"**.

```tsx
// index.tsx
<Space.Compact block className="my-space-container">
    <SpaceAddon position="left">left text</SpaceAddon>
    <Input value="1"/>
    <SpaceAddon position="middle">middle</SpaceAddon>
    <Select mode="multiple" placeholder="请选择" options={Array.from({length: 5}, (_, i) => ({label: i + 1, value: i + 1}))}/>
    <SpaceAddon position="right">right text</SpaceAddon>
</Space.Compact>
```

<img width="325" height="237" alt="Image" src="https://github.com/user-attachments/assets/1334512b-d34f-4fdf-9338-4c5dbff9654d" />

If you think inputting position param is not elegant, u can try use CSS selector like ".my-space-container:first-child", ".my-space-container:last-child" to control the border line and border-radius, but i tried and gave up.

btw, this method may break the antd attrbution "size", if u wanna fix it, u can try design a new param. :D

I noticed that u hope use it in <From>,  sorry that this solution is not work in Form, but u can try "form.setFieldValue" to update form data.

**Comment by Eriktse** [comment]
> I found a way that maybe useful. I create a new custom component named "SpaceAddon" and use it in tag "<Space.Compact>".
> 
> // components/SpaceAddon.tsx
> import { CSSProperties } from "react"
> export const SpaceAddon = ({position, children}: {position: "left" | "middle" | "right", children: React.ReactNode}) => {
>     const divStyle: CSSProperties = {
>         padding: "0 8px",
>         display: "flex",
>         flexDirection: "row",
>         alignItems: "center",
>         borderTop: "1px solid #d9d9d9",
>         borderBottom: "1px solid #d9d9d9",
>         background: "rgba(0,0,0,0.02)",
>         whiteSpace: "nowrap"
>     }
>     if(position === "left")Object.assign(divStyle, {
>         borderTopLeftRadius: "6px",
>         borderBottomLeftRadius: "6px",
>         borderLeft: "1px solid #d9d9d9",
>     })
>     if(position === "right")Object.assign(divStyle, {
>         borderTopRightRadius: "6px",
>         borderBottomRightRadius: "6px",
>         borderRight: "1px solid #d9d9d9",
>     })
>     return <div style={divStyle}>
>         {children}
>     </div>
> }
> then use it like this, **remember to pass the param "position"**.
> 
> // index.tsx
> <Space.Compact block className="my-space-container">
>     <SpaceAddon position="left">left text</SpaceAddon>
>     <Input value="1"/>
>     <SpaceAddon position="middle">middle</SpaceAddon>
>     <Select mode="multiple" placeholder="请选择" options={Array.from({length: 5}, (_, i) => ({label: i + 1, value: i + 1}))}/>
>     <SpaceAddon position="right">right text</SpaceAddon>
> </Space.Compact>
> <img alt="Image" width="325" height="237" src="https://private-user-images.githubusercontent.com/104485992/515653569-1334512b-d34f-4fdf-9338-4c5dbff9654d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ1Nzg3NjksIm5iZiI6MTc2NDU3ODQ2OSwicGF0aCI6Ii8xMDQ0ODU5OTIvNTE1NjUzNTY5LTEzMzQ1MTJiLWQzNGYtNGZkZi05MzM4LTRjNWRiZmY5NjU0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwMVQwODQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmEyMWY4NjczMzEzZTljYmJhN2ZjYmEwY2E4MzY3MjVjMTgyZTYxNTBmOTI4ZTNmZjc3NDhhYzU4NjA0MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aW1_QAByT4gbPsf26DyTMjZxviA3lEfPr1uh4trvJqs">
> If you think inputting position param is not elegant, u can try use CSS selector like ".my-space-container:first-child", ".my-space-container:last-child" to control the border line and border-radius, but i tried and gave up.
> 
> btw, this method may break the antd attrbution "size", if u wanna fix it, u can try design a new param. :D
> 
> I noticed that u hope use it in , sorry that this solution is not work in Form, but u can try "form.setFieldValue" to update form data.

I noticed a exciting news that Antd v6.0.0 is support "Space.Compact" & "Space.Addon" tags, and "addonBefore" / "addonAfter" is deprecated(remember to update ur code if upgraded Antd version). here is the link: https://ant-design.antgroup.com/components/space-cn#space-demo-compact
