### ISSUE TITLE
Range picker not working when passing in disabled and disabledDate at the same time

### ISSUE THREAD

**Issue by JessieJ0122** [ant-design/ant-design#48278]
### Reproduction link

[https://react-87g5ko.stackblitz.io/](https://react-87g5ko.stackblitz.io/)

### Steps to reproduce

click the date picker that's not disabled, select valid date, click ok.

### What is expected?

The selected date is displayed in the range picker

### What is actually happening?

new date is ignored, still showing the old value

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
Have you try 5.16.0 ?

**Comment by Roxannej** [comment]
Can you show you code, I think you judgement condition has some error
looks like：
return current && current < dayjs().endOf('day')
if (current) {
      if (current < dayjs().endOf('day')) {
        return true
      } else if (current.isSame(dayjs(), 'day')) {
        return true
      } else {
        return false
      } 
    } 
I find there has a error about css style
