### ISSUE TITLE
Options popup of AutoComplete do not open when an edge of the input field is clicked

### ISSUE THREAD

**Issue by paulinoacuna** [ant-design/ant-design#48281]
### Reproduction link

[https://ant.design/~demos/auto-complete-demo-non-case-sensitive](https://ant.design/~demos/auto-complete-demo-non-case-sensitive)

### Steps to reproduce

- Click inside the right edge of the input field more than 3 times
- you will se the popup closes automatically

### What is expected?

wherever the user click inside the input field, the popup with the input options should keep opened

### What is actually happening?

the popup closes automatically 

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | 123.0.6312.105 |

**Comment by afc163** [comment]
I can reproduce it.

**Comment by paulinoacuna** [comment]
Hello, please just follow the link https://ant.design/~demos/auto-complete-demo-non-case-sensitive you can reproduce the issue there

**Comment by vikashvishwakarma1601** [comment]
Hi @paulinoacuna, Could you please confirm if this is the issue you are currently facing?

https://github.com/ant-design/ant-design/assets/38412082/d3407b98-89a9-45ba-a544-e5e636ea3951

**Comment by Ruler1020730** [comment]
Me too.
这是我在源码console发现的原因。

https://github.com/ant-design/ant-design/assets/47056082/9288edc4-285a-42e3-a425-7944df27bccc

**Comment by paulinoacuna** [comment]
gracias
