### ISSUE TITLE
Tab type not exported for typescript

### ISSUE THREAD

**Issue by BradWells** [ant-design/ant-design#48290]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

import {Tab} from "antd";
This shows up red on my IDE as not found. However my IDE can see that there is a Tab type in the source.

### What is expected?

This to compile

### What is actually happening?

It does not compile

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18.2.0 |
| System | Windows |
| Browser | Firefox |

---
A workaround is

// Why isn't this type exported from Ant Design!!
type Tab = TabsProps['items'][0];

**Comment by kiner-tang** [comment]
Do you mean :  `import {Tabs} from "antd";`?

**Comment by zombieJ** [comment]
You can get all the props with `GetProp` ts util provided by antd.

ref [Type Util](https://ant.design/docs/blog/type-util)

**Comment by BradWells** [comment]
@kiner-tang No I don't mean the component Tabs, I mean the type of the items array passed to it.

@zombieJ Yes I can use `GetProp<TabsProps, 'items'>[0]` as a workaround similar to `TabsProps['items'][0]`.

However, my IDE (Pycharm Ultimate) can recognize that the type of `items` is already defined as Tab[], with Tab being defined in `node_modules/rc-tabs/lib/interface.d.ts` as 
```
export interface Tab extends Omit<TabPaneProps, 'tab'> {
    key: string;
    label: React.ReactNode;
}
```

Why isn't Ant Design re-exporting this type from rc-tabs? If I manually added rc-tabs to my project dependencies could I import it?

There's a similar problem with Rules with Inputs. If I try to use `InputProps['rules'][0]` or `GetProp<InputProps, 'rules'>[0]` it just resolves to `any` which doesn't help my IDE auto-complete at all, but if I ctrl+click in Pycharm it guides me to `node_modules/rc-field-form/lib/interface.d.ts`
```
export type Rule = RuleObject | RuleRender;
```
This is the complex type that I want to use in my application so my IDE auto-completes and I know I'm not setting the wrong properties on Rules.

Is there any way that I can import the types from the rc-*/lib/interface.d.ts files?
