### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'hook') - Switch

### ISSUE THREAD

**Issue by melodyxpot** [ant-design/ant-design#48301]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/live/5956d844-4ae3-4209-8f66-8c45ee97cd0a)

### Steps to reproduce

Just try to click switch component.
You can see the error in the console easily.

### What is expected?

no Error

### What is actually happening?

I get the type error

VM33:10 TypeError: Cannot set properties of undefined (setting 'hook')

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | ^18 |
| System | Windows |
| Browser | Chrome 123 |

**Comment by afc163** [comment]
I couldn't reproduce it.

<img width="1781" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8c3d5872-d381-4793-b0d5-0cac12887256">
