### ISSUE TITLE
强烈建议增加column move（列拖拽排序）功能

### ISSUE THREAD

**Issue by Shen120** [ant-design/ant-design#48306]
### What problem does this feature solve?

可以对列进行拖拽排序，我们因为没有这个功能而没有使用antd的表格，太难受了;如下图，图中是ag-grid的表格

![column-animation 5d473ccc](https://github.com/ant-design/ant-design/assets/33613409/a7c93e32-e87c-4019-b345-941c110e1794)

### What does the proposed API look like?

可配置，也可手动调用set和get方法更新/获取

**Comment by Shen120** [comment]
[示例地址](https://www.ag-grid.com/react-data-grid/column-moving/)

**Comment by crazyair** [comment]
![image](https://github.com/ant-design/ant-design/assets/7971419/75e89795-d102-4e09-8c39-8695dbdcfbb5)

https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5

**Comment by afc163** [comment]
来个 PR？

**Comment by Shen120** [comment]
> ![image](https://private-user-images.githubusercontent.com/7971419/320249038-75e89795-d102-4e09-8c39-8695dbdcfbb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTkwMzEsIm5iZiI6MTcxMjQ1ODczMSwicGF0aCI6Ii83OTcxNDE5LzMyMDI0OTAzOC03NWU4OTc5NS1kMTAyLTRlMDktOGMzOS04Njk1ZGJkY2ZiYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDI1ODUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDlhNDkwYmYxNjg2NjRhNDdkYTk2NzEyNzU4NDVkNmFlMmYxMDNkN2M4ZDhiNDI3NzAyYTU5MjNkNWJlODY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wb5XFpvvY8MXLGjpttFvYfPiL8xIeqHmS2kztLH1ty8)
> 
> https://procomponents.ant.design/components/table?tab=api&current=1&pageSize=5

我知道有这个，但是不符合需求，想要的是能够直接在表格中拖动，类似行拖动那种

**Comment by Shen120** [comment]
> 来个 PR？

代码写得撇

**Comment by crazyair** [comment]
可以参考行拖拽，再增加个列拖拽的 demo

**Comment by Shen120** [comment]
> 可以参考行拖拽，再增加个列拖拽的 demo

空了搞搞

**Comment by afc163** [comment]
Added a demo in https://github.com/ant-design/ant-design/pull/48434
