### ISSUE TITLE
npm run lint:demo not working

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4831]
`__react` should be `jsx`.

**Comment by afc163** [comment]
https://github.com/eslint/eslint-plugin-markdown#usage

**Comment by benjycui** [comment]
忘了当时改成 `__react` 是为了统一还是及技术问题了。

但是改回 `jsx` 好像也没什么问题。

**Comment by afc163** [comment]
是为了区分可运行代码和不可运行代码。
