### ISSUE TITLE
给多选框(Checkbox)加一个和单选框button模式相同的样式组件

### ISSUE THREAD

**Issue by liuxing133** [ant-design/ant-design#48310]
### What problem does this feature solve?

解决了项目单选多选框风格统一

### What does the proposed API look like?

多选框的配置项多一个optionType，修改组件选择框样式

**Comment by MadCcc** [comment]
从这个角度上考虑，提供 `useRadio` 类似的 hook 可能更方便自定义。
暂时没有计划做这些。

**Comment by afc163** [comment]
单选框button模式是给单选模式设计的，不能适用于多选。

如果需要别的样式，建议看看 https://procomponents.ant.design/components/check-card

**Comment by liuxing133** [comment]
![image](https://github.com/ant-design/ant-design/assets/117614329/dbf83ab1-6ea7-4bb8-9a2a-dad02deb3ea3)
想要这种效果

**Comment by afc163** [comment]
antd 目前不支持这种设计。

**Comment by Wxh16144** [comment]
> ![image](https://private-user-images.githubusercontent.com/117614329/320258094-dbf83ab1-6ea7-4bb8-9a2a-dad02deb3ea3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzQwMzEsIm5iZiI6MTcxMjQ3MzczMSwicGF0aCI6Ii8xMTc2MTQzMjkvMzIwMjU4MDk0LWRiZjgzYWIxLTZlYTctNGJiOC05YTJhLWRhZDAyZGViM2VhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwNzA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjFkMjY2YjNmZTc0YTU4YTBkOWJiMzJhNDdkMDc5OWE1OWFkZDE2OWYzOWYwYmFlOTFmMjA1MmZiMzQyMTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sbDrRsIFN-uy4fJ0sTfOuAa-co4VmkIMJ4YbfQy4CFU) 想要这种效果

感觉可以自己用 antd 的 button 实现一个：

```tsx

import { Button, Space } from 'antd'
import { useSelections, useControllableValue, useUpdate, useUpdateEffect } from 'ahooks';
import { Options } from 'ahooks/es/useControllableValue'

interface Item {
  key: React.Key;
  title: React.ReactNode;
}

interface SelfCheckboxProps extends Options<React.Key[]> {
  options?: Item[];
  showAll?: boolean;
}


function SelfCheckbox(props: SelfCheckboxProps) {
  const { options, showAll } = props;
  const [value, setValue] = useControllableValue(props);

  const formatOptions = Array.isArray(options) ? options : [];

  const {
    selected,
    allSelected,
    isSelected,
    toggle,
    toggleAll,
    partiallySelected
  } = useSelections(formatOptions.map(({ key }) => key), value);


  useUpdateEffect(() => {
    setValue(selected);
  }, [selected]);

  const realOptions = (function () {
    const _items = [...formatOptions].filter(Boolean)

    if (showAll) {
      _items.unshift({ key: 'all', title: 'All', __internal__type: 'ALL' });
    }

    return _items;
  }());


  const renderOption = (option: Item) => {
    const { key, title } = option;

    if ((option as any).__internal__type === 'ALL') {
      return (
        <Button
          key={key}
          type={allSelected ? 'primary' : 'default'}
          onClick={toggleAll}
        >
          {partiallySelected ? 'Clear' : 'Select All'}
        </Button>
      )
    }

    return (
      <Button
        key={key}
        ghost={isSelected(key)}
        type={isSelected(key) ? 'primary' : 'default'}
        onClick={() => toggle(key)}
      >
        {title}
      </Button>
    )
  };


  return (
    <Space.Compact>
      {realOptions.map(renderOption)}
    </Space.Compact>
  )
}


export default () => {
  return (
    <SelfCheckbox
      showAll
      options={[
        { key: '1', title: 'Option 1' },
        { key: '2', title: 'Option 2' },
        { key: '3', title: 'Option 3' },
      ]}
      onChange={(value) => {
        console.log('onChange', value);
      }}
    />
  )
}

```
