### ISSUE TITLE
Dropdown doesnt support inline mode

### ISSUE THREAD

**Issue by aljake95** [ant-design/ant-design#48315]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-pxtfl5?file=%2Findex.js%3A68%2C22)

### Steps to reproduce

Using Dropdown component

use dropdownRender property to use Menu component 

### What is expected?

children to be view in inline mode

### What is actually happening?

viewable only in vertical mode

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | react |
| System | w11 |
| Browser | chrome |

**Comment by afc163** [comment]
It is by designed.
