### ISSUE TITLE
form.validateFields在没有使用catch捕获错误时报错

### ISSUE THREAD

**Issue by cjmafei** [ant-design/ant-design#48319]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/nostalgic-dan-rl268t?file=%2Fpackage.json%3A8%2C17)

### Steps to reproduce

1.直接点击提交按钮

### What is expected?

没有错误在页面上

### What is actually happening?

错误导致页面崩掉了

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
```
import React, { useEffect } from "react";

export default function App() {
  useEffect(() => {
    throw new Error('xxx');
  }, []);

  return (
    <div>123</div>
  );
}
```

这和 antd 无关，只要任意 throw 一个错误就会被 codesandbox 展示在页面上。

可以看到同样的代码在 https://stackblitz.com/edit/react-yyapnp?file=demo.tsx 上不会有问题。
