### ISSUE TITLE
Time range picker popup position bug

### ISSUE THREAD

**Issue by heromac** [ant-design/ant-design#48329]
### Reproduction link

[https://codepen.io/heromac/pen/LYvddyd?editors=0011](https://codepen.io/heromac/pen/LYvddyd?editors=0011)

### Steps to reproduce

1、在TimerPicker.RangePicker中，使用"HH:mm"格式化时间
2、反复点击 “End Time” 输入框，弹出选择时间的popup 和 arrow 位置错开。

### What is expected?

在“End Time” 输入框下方展示popup和arrow

### What is actually happening?

在“Start Time” 输入框下方展示popup，在“End Time” 输入框下方展示arrow。

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | MacOS14 |
| Browser | edge 123.0.2420.65 (正式版本) (x86_64) |

**Comment by zombieJ** [comment]
v4 已经过了维护期，试试升级到 v5 哈。v5 中 Picker 已经重构过了~
