### ISSUE TITLE
关于`Select`的文档，感觉可以完善的地方

### ISSUE THREAD

**Issue by jzlxiaohei** [ant-design/ant-design#4832]
看到几个issue里，提到Option和Input 展示分离的文档。我今天也搞了很久，觉得文档关于`optionLabelProp`的说明太简陋。

除了 `value` 和 `children`，也可以是自定义属性名，比如 如果`Option`按如下形式render，
```javascrpit
      <Option
        dataItem={item}
        key={item.id}
        customText={item.name}
      >
        {item.description}
      </Option>
```
那么可以设置`optionLabelProp`为`customText`，这样的话展示可以完全自定义。

另外如果是上面的写法，`onSelect`回调里，第二个参数`option`, 可以通过`option.props.dataItem` 拿到原始数据。

我感觉这两个例子对于使用select来说，有必要在例子里说明一下

**Comment by RaoHai** [comment]
你可以给我们提一个 PR ，协助我们一起改善 antd 么

**Comment by jzlxiaohei** [comment]
这块感觉我的描述不一定准确，我只是猜应该是这样，然后实验成功了。
这个issue先开着，我过两天看下源代码，确认后，在提PR吧

**Comment by afc163** [comment]
直接提 PR 就好，这里先关掉了。
