### ISSUE TITLE
重新设置initialState之后使用refresh刷新无法重新渲染

### ISSUE THREAD

**Issue by KongAKun** [ant-design/ant-design#48324]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/blue-fast-85sfp6?file=%2Fsrc%2FApp.js%3A22%2C16)

### Steps to reproduce

refresh之后，执行getInitialState的时候。似乎是因为initialState里的头像的url没有变化，没有重新发起请求，但是url对应的资源是更新了的，需要重新请求

### What is expected?

refresh之后，重新发起请求，或许到最新的数据。

### What is actually happening?

根据url，再次发起请求

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | Windows 11 专业版 23H2 |
| Browser | 123.0.6312.106（正式版本） （64 位） |

**Comment by crazyair** [comment]
提问错了吧？应该提到 umi 那
