### ISSUE TITLE
DatePicker 能否出个属性，支持某天特殊颜色（支持设置其他颜色）显示

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#48333]
### What problem does this feature solve?

![image](https://github.com/ant-design/ant-design/assets/29728228/50fe20ca-825e-4f5f-8f30-2e1cc08b7e95)

现在确实可以用cellRender实现，没问题，我也实现了

但是这种实现需要覆盖几个样式，一个是要覆盖 .ant-picker-cell-selected 选中的，否则红色的文字蓝色的底不好看，选中时候还是白色

另外对于range，也需要覆盖  .ant-picker-cell-range-start ，  .ant-picker-cell-range-end，同样是因为选中的问题

不覆盖的话，蓝底红字就比较难看了，主题token里我好像也没看到设置选中日期的颜色

![image](https://github.com/ant-design/ant-design/assets/29728228/6c9b0aff-5d79-4bf4-9878-40c9b236cf76)

我个人不是很喜欢覆盖样式的形式，还是希望官方能加个属性，设置周末颜色，也不一定是周末的颜色，可以根据weekdays 来设定，或者可以是任意一个日期

比如 设置周三显示绿色

```
 <DatePicker
   dayColor="#00ff00"
   showType="weekdays"
   showDays[3]
/>
```

比如设置周日，周一红色

```
 <DatePicker
   dayColor="#ff0000"
   showType="weekdays"
   showDays[0,1] // 假设周日是0
/>
```

比如设置每个月10号，15号红色

```
 <DatePicker
   dayColor="#ff0000"
   showType="days" // showType 来指定按星期还是按普通日期
   showDays[10,15] 
/>
```

**Comment by zombieJ** [comment]
> 现在确实可以用cellRender实现，没问题，我也实现了

 业务需求请自行通过 HOC 封装哈，`cellRender` 就是 antd 侧提供的能力。选中通过 `onCalendarChange` 获取即可~
