### ISSUE TITLE
ant table 开启 virtual后,横向怎么启动虚拟加载

### ISSUE THREAD

**Issue by yanglufan** [ant-design/ant-design#48331]
### What problem does this feature solve?

ant table 开启 virtual后横向 怎么启动虚拟加载,有人知道么,在有很多列的适合,还是会卡.我发现横向滚动的时候没有虚拟加载

### What does the proposed API look like?

期望启动 virtual开启后横向滚动和纵向滚动都使用虚拟加载

**Comment by yoyo837** [comment]
顶天一个表格50个列，再多就是设计不合理了，横向不需要虚拟滚动；另外可以考虑添加个性化支持按用户隐藏个别列。

**Comment by yanglufan** [comment]
> 顶天一个表格50个列，再多就是设计不合理了，横向不需要虚拟滚动；另外可以考虑添加个性化支持按用户隐藏个别列。
现在客户的一些旧电脑加载30多列都有点卡顿.他们又不想更新电脑

**Comment by yanglufan** [comment]
> 顶天一个表格50个列，再多就是设计不合理了，横向不需要虚拟滚动；另外可以考虑添加个性化支持按用户隐藏个别列。
现在客户的一些旧电脑加载30多列都有点卡顿.他们又不想更新电脑

**Comment by yanglufan** [comment]
> 顶天一个表格50个列，再多就是设计不合理了，横向不需要虚拟滚动；另外可以考虑添加个性化支持按用户隐藏个别列。

客户的电脑配置很低,加载30多列都有卡顿.

**Comment by yoyo837** [comment]
听上去连手机都不如哦！调试一下看哪里在消耗性能

**Comment by afc163** [comment]
> 加载30多列都有卡顿.

这种情况开了虚拟滚动也不解决问题，虚拟滚动也有性能消耗。

**Comment by zombieJ** [comment]
这种比较推荐上专门的虚拟表单，antd 的虚拟化都是以行为级别做处理。

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/45605

**Comment by yanglufan** [comment]
> 这种比较推荐上专门的虚拟表单，antd 的虚拟化都是以行为级别做处理。

有什么推荐的项目可以参考么?

**Comment by yanglufan** [comment]
> 虚拟表单

确实不如手机,10年前的电脑了

**Comment by yanglufan** [comment]
> 听上去连手机都不如哦！调试一下看哪里在消耗性能

确实不如手机性能好,十年前的电脑了

**Comment by wowtrxqn** [comment]
如何实现横向虚拟滚动
