### ISSUE TITLE
Input 添加addonAfter根据变量控制失去焦点问题

### ISSUE THREAD

**Issue by itzwg** [ant-design/ant-design#48330]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/xqql64?file=%2Fsrc%2FApp.jsx%3A6%2C33&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluqnx4lu0006356gs2ko9u6x%2522%252C%2522sizes%2522%253A%255B84.1935483867742%252C15.806451613225803%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluqnx4lt0002356gc6h0gvs9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluqnx4lt0004356gqj4gtqfg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluqnx4lt0005356g3uy9rp8d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluqnx4lt0002356gc6h0gvs9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqnx4lt0001356gvnh19xjs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluqo9sjs0002356g6j3isl2s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A33%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A33%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluqnx4lt0002356gc6h0gvs9%2522%252C%2522activeTabId%2522%253A%2522cluqo9sjs0002356g6j3isl2s%2522%257D%252C%2522cluqnx4lt0005356g3uy9rp8d%2522%253A%257B%2522id%2522%253A%2522cluqnx4lt0005356g3uy9rp8d%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cluqodnaf00ew356gwf2wfv1a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluqodnaf00ew356gwf2wfv1a%2522%257D%252C%2522cluqnx4lt0004356gqj4gtqfg%2522%253A%257B%2522id%2522%253A%2522cluqnx4lt0004356gqj4gtqfg%2522%252C%2522activeTabId%2522%253A%2522cluqodh9800cb356gwwqkmh8c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqodh9800cb356gwwqkmh8c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluqodikz0011d9f838005oaz%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

<Input
       maxLength={12}
       placeholder="请输入4位数及以上的账号"
       bordered={false}
       onChange={debounce(changeAccount, 300)}
       addonAfter={checkAccount ? <CheckCircleTwoTone /> : ''}
     />
onChange修改checkAccount变量的时候会导致该input失去焦点

### What is expected?

不会失去焦点

### What is actually happening?

失去焦点

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.2.0 |
| System | Windows 10 专业版 |
| Browser |  121.0.6167.185（正式版本） （64 位） |

**Comment by itzwg** [comment]
addonAfter={checkAccount ? <CheckCircleTwoTone /> : <></> 这样是可以的

**Comment by afc163** [comment]
@itzwg got the solution.
