### ISSUE TITLE
AutoComplete with non case sensitive 

### ISSUE THREAD

**Issue by ajainvivek** [ant-design/ant-design#4834]
AutoComplete with non case sensitive doesn't work. And on selecting text key gets selected.

Is there an example to show non case sensitive AutoComplete?

**Comment by RaoHai** [comment]
Well, AutoComplete is an controlled component, you can use `onChange` and `dataSource` props to implement non-case-sensitive AutoComplete.

**Comment by ajainvivek** [comment]
I need the value to be display as is but search has to be non case sensitive.

eg. Text to be displayed: Burns Bay Road
Search Term: bu
Results: [] empty array

I am trying google places search and no luck

**Comment by RaoHai** [comment]
Sorry, but maybe you can use `filterOption` props to do that, here's a demo.

http://codepen.io/RaoHai/pen/RKEQEQ

**Comment by ajainvivek** [comment]
That certainly looks good to me. It will be great if we can add option to handle case sensitive search.

Closing the issue.
