### ISSUE TITLE
增加一个Spliter组件

### ISSUE THREAD

**Issue by noopn** [ant-design/ant-design#48349]
### What problem does this feature solve?

解决常见上下或左右布局时，需要调整大小的需求

### What does the proposed API look like?

```
<Spliter>
   <Spliter.Left>
    <Spliter.Right>
      <Spliter>
          <Spliter.Top>
          <Spliter.Bottom>
        </Spliter>
    /Spliter.Right>
</Spliter>
```

**Comment by Wxh16144** [comment]
Duplicate of #44525

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/50038
