### ISSUE TITLE
Text input of Picker component with custom input prop is not selectable

### ISSUE THREAD

**Issue by martis347** [ant-design/ant-design#48343]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-s42l3g)

### Steps to reproduce

1. Select the text contents of input 1 using the mouse cursor
2. Select the text contents of input 2 using the mouse cursor

### What is expected?

The text content of input should be selectable in both cases

### What is actually happening?

When a custom "components.input" prop is provided the input becomes non-selectable via mouse cursor (but is still is selectable via keyboard)

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.x |
| System | Windows |
| Browser | Chrome, Firefox |

**Comment by zombieJ** [comment]
Input component is not native element. Which means the ref of it is not a HTMLInputElement. Which need forward to the native dom instead:

https://stackblitz.com/edit/react-erqtzm?file=demo.tsx
