### ISSUE TITLE
Typography with dynamic Editable not rendering edit icon correctly

### ISSUE THREAD

**Issue by jaredbray** [ant-design/ant-design#48344]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wwcjcv-7d7e3p?file=demo.js)

### Steps to reproduce

1. Click a Switch to toggle editable state of typography

### What is expected?

The edit icon should appear when edit is enabled, or disappear when edit is disabled.

### What is actually happening?

The edit icon does not appear or disappear unless the editable state is interacted with somehow, e.g. by clicking the text when 'text' is allowed as a triggerType.

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2.73 |
| System | Windows 10 |
| Browser | Chrome 123.0.6312.106 |

---
Worked as expected in antd 4.24.0

**Comment by crazyair** [comment]
![image](https://github.com/ant-design/ant-design/assets/7971419/aeb6a34d-cf82-414f-a9a9-23d7fc90f87a)

If the children are guaranteed to change, the issue can be temporarily resolved and will be fixed later
