### ISSUE TITLE
Table is not scrollable and have break styles in IE11

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4835]
1. https://ant.design/components/table-cn/#components-table-demo-fixed-columns 横向滚动，阴影没有相应变化。
2. https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header 纵向滚动，固定部分没有跟随滚动。
3. 样式错位。

![image](https://cloud.githubusercontent.com/assets/507615/22854003/a778a086-f09e-11e6-81de-34c87752c395.png)

![image](https://cloud.githubusercontent.com/assets/507615/22854008/b989908c-f09e-11e6-86b8-eeeeda2b7735.png)

![image](https://cloud.githubusercontent.com/assets/507615/22854015/e393229e-f09e-11e6-935e-5b0c6bc0bc1b.png)

**Comment by afc163** [comment]
貌似 IE 下某些 rc-table 的代码没有运行，例如：https://github.com/react-component/table/blob/d297856c4bb8def645735c1e697b576c63406695/src/Table.jsx#L448-L453

**Comment by yesmeck** [comment]
网站重新部署后没问题了。
