### ISSUE TITLE
Virtual table lazy loading/pagination

### ISSUE THREAD

**Issue by Trufinol** [ant-design/ant-design#48354]
### What problem does this feature solve?

Fetch the data for the table in chunks. Useful when having a huge amount of data that takes a lot of time to download at once.

### What does the proposed API look like?

A method `loadMore` which is a Promise that returns a new data source with added items.

**Comment by zombieJ** [comment]
Since `5.16.0`, Table provide the `onScroll` event. You can HOC of table to dynamic load data if reach the end : )

Source feature issue of similar requirement: #44839
