### ISSUE TITLE
可控的筛选表格清除筛选项不生效

### ISSUE THREAD

**Issue by CoderAWei** [ant-design/ant-design#48352]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-f4mukx?file=demo.tsx,columns.tsx)

### Steps to reproduce

1. 在外部文件声明columns
2. 在页面文件引用columns，并使用map给每一列加上filterdValue使之变成可控的。
3. 筛选数据功能正常，但是点击clear filters will not work.

### What is expected?

能够清除所有的筛选条件

### What is actually happening?

没有清除筛选项

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2.0 |
| System | Windows |
| Browser | Google Chrome115.0.5790.102 |

---
需要将column声明在外部文件，放在一个页面文件就会导致该文件代码太多 没有可读性

**Comment by TallNutAlarak** [comment]
```js
 useEffect(() => {
    setColumns(
      columns.map((item) => {
        item.filteredValue = filteredInfo[item.dataIndex] || null; // <- 添加默认值 null
        return item;
      })
    );
  }, [filteredInfo]); // <- 添加 filteredInfo 依赖
```

**Comment by CoderAWei** [comment]
It works. Thanks for your reply！
