### ISSUE TITLE
Upload picture-card 顶部出现多余的空间

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#48365]
### Reproduction link

[https://ant.design/components/upload-cn#components-upload-demo-picture-card](https://ant.design/components/upload-cn#components-upload-demo-picture-card)

### Steps to reproduce

查看顶部

### What is expected?

无多余空间

### What is actually happening?

有多余空间

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | latest |
| System | mac |
| Browser | chrome |

---
ref: https://github.com/ant-design/ant-design/pull/48091

**Comment by CooperHash** [comment]
![image](https://github.com/ant-design/ant-design/assets/73218815/89185c47-c82f-4303-af3c-9e8df6139d41)

哪个地方？
