### ISSUE TITLE
更新 antd 版本后table 滚动条和原来不一样了

### ISSUE THREAD

**Issue by caihuascript** [ant-design/ant-design#48366]
### Reproduction link

[https://ant.design/components/table](https://ant.design/components/table)

### Steps to reproduce

看带有滚动条的table 就可以

### What is expected?

需要跟之前版本保持一致

### What is actually happening?

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.* |
| System | mac |
| Browser | chrome |

之前版本样式：
<img width="53" alt="image" src="https://github.com/ant-design/ant-design/assets/50008262/e8c9208c-ce8e-45b0-844b-694c91022d0a">

最新版本样式：
<img width="56" alt="image" src="https://github.com/ant-design/ant-design/assets/50008262/a9d0f73a-5ec6-40d4-b089-5c411bc0867d">

**Comment by yoyo837** [comment]
<img width="466" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/7f15c16e-73d3-4d66-8ed3-926afc5da7c4">

你这个看上去像开启了这个

**Comment by caihuascript** [comment]
并没有哦  css 样式变了

**Comment by caihuascript** [comment]
css  样式变了， 两种情况是在同一环境运行的结果

**Comment by zombieJ** [comment]
我使用 `~5.0.0` 版本也是一样的： https://stackblitz.com/edit/react-1hj5cs?file=package.json,demo.tsx

<img width="1408" alt="截屏2024-04-10 11 45 38" src="https://github.com/ant-design/ant-design/assets/5378891/37f4a752-7d07-4522-a42a-75f903f03ec8">

如果你发现样式不一样，可以看一下自己是不是设置了 `-webkit-scrollbar-` 样式魔改过。antd 使用了更标准的 `scrollbar-` 样式配置以支持暗色模式下的滚动条样式。而 `-webkit-scrollbar-` 为非标样式配置。当两者共存是会优先使用前者。

如若如此，可以考虑覆盖全局样式哈~

**Comment by caihuascript** [comment]
并没有设置 -webkit-scrollbar- 可以看一下官网  官网的table 例子也是有问题的
