### ISSUE TITLE
Menu 导航菜单项标题使用<span>元素，超长文本溢出省略样式失效

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#48369]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jwvybn-1wv4k7?file=demo.js)

### Steps to reproduce

<Menu>的菜单内容items属性，使用<span>超长文案</span>作为label属性值

### What is expected?

超长文案显示省略号

### What is actually happening?

超长文案不展示省略号

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | "react": "^18.2.0" |
| System | win10 |
| Browser | chrome123 |

---
label属性值的<span>标签会把父标签的<span>顶替掉，导致css样式发生错乱

**Comment by afc163** [comment]
```
function getItem(label, key, icon, children, type) {
  return {
    key,
    icon,
    children,
    label: <span style={{
      maxWidth: 'calc(100% - 24px)',
      overflow: 'hidden',
      textOverflow: 'ellipsis'
    }} title={label}>{label}</span>,
    type,
  };
}
```

**Comment by chengshaohui** [comment]
> ```
> function getItem(label, key, icon, children, type) {
>   return {
>     key,
>     icon,
>     children,
>     label: <span style={{
>       maxWidth: 'calc(100% - 24px)',
>       overflow: 'hidden',
>       textOverflow: 'ellipsis'
>     }} title={label}>{label}</span>,
>     type,
>   };
> }
> ```

我当然知道这样改是可以的，甚至下面这样改也可以，关键是为啥单单<span>标签不行？
`      <div style={{ display: 'inline' }} title={label}>
        {label}
      </div>
`

**Comment by afc163** [comment]
下面这种我实测 Firefox 下也不行。

**Comment by chengshaohui** [comment]
> <div style={{ display: 'inline' }} title={label}>
>         {label}
>       </div>
实测是可以的，下面是例子，问题的本质是明明label本身是支持文本溢出省略的，但是只有span标签会失效，应该是你们代码处理了所有span子标签导致的问题：
https://stackblitz.com/edit/react-hqpop5-manalf?file=demo.tsx
