### ISSUE TITLE
Select 组件选项 hover 状态样式错误

### ISSUE THREAD

**Issue by shunrong** [ant-design/ant-design#48368]
### Reproduction link

[https://ant.design/components/select-cn](https://ant.design/components/select-cn)

### Steps to reproduce

Select 组件官方文档可以复现。
1. 当 hover 某一选项时，出现 hover 状态，即背景灰色。但是当鼠标移开至外部时背景色未清除，仍出现 hover 状态
2. 当有 disabled  选项时，hover 到 disabled 的选项，此时前一个选项仍出现 hover 状态。

### What is expected?

1. hover 到选项才出现灰色背景，移开后背景应清除
2. disabled 的选项 hover 时无背景色。

### What is actually happening?

移开后 hover 状态未清楚

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | react 17 |
| System | mac os 13.5 |
| Browser | chrome 123 |

**Comment by MadCcc** [comment]
键盘交互的指示，设计如此

**Comment by zombieJ** [comment]
这个不是 hover 态，而是 active 态。如 @MadCcc 所述，鼠标悬浮会同步更新以确保无障碍的一致性。
