### ISSUE TITLE
<Table /> 在某些场景下，固定列行高度变为 auto，导致行错位

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#4836]
我们业务碰到的场景和 [demo](http://codepen.io/ystarlongzi/pen/KaGaxy?editors=0010) 里的类似，大致如下：
1. 从列表 --> 详情时，修改了 state，使 `<UserList />` 组件进入 re-render，隐藏列表，然后导致在计算 `<tr />` 的高度值为 `auto`
2. 然后从详情 --> 列表时，并没触发 `<UserList />` 再次 re-render，然后此时 `<tr />` 的高度值还是 `auto` ，就导致了错位

效果如下图：
![111](https://cloud.githubusercontent.com/assets/2840462/22859191/9e03f49a-f10e-11e6-948b-12bc9e0d1a92.gif)

**Comment by yesmeck** [comment]
因为你的 sCU 写错了，导致 Table 没有重新 render:

```javascript
  shouldComponentUpdate(nextProps, nextState) {
    if (nextState === this.state) {
      return false;
    }
    
    return true;
  },
```

要用 `shallowEqual` 或者直接继承  `React.PureComponent`。

**Comment by ystarlongzi** [comment]
@yesmeck  

demo 里是特意这样写的，用来还原业务里碰到的场景，业务里是用的 `React.PureComponent`。

**Comment by yesmeck** [comment]
把 demo 里的 sCU 去掉就好了，你看看你业务代码从详情切换到 UserList 的时候， UserList 是不是有重新 render 吧。

**Comment by yesmeck** [comment]
奥，知道了，因为你是在 `UserList` 外部 `UserList` `display: none` 了。

**Comment by ystarlongzi** [comment]
从详情 ---> 列表，`<UserList />` 没有重新 render。

然后，业务代码里如果把组件 `<UserList />` 的 sCU 去掉，则不会出现错行。

**Comment by ystarlongzi** [comment]
> 奥，知道了，因为你是在 UserList 外部 UserList display: none 了。

嗯嗯，是的

**Comment by yesmeck** [comment]
组件这边没什么好的办法，调整下你的写法吧，Table 必须重新 render 才能感知高度的变化。

**Comment by ystarlongzi** [comment]
@yesmeck 

是否可以在 [syncFixedTableRowHeight](https://github.com/react-component/table/blob/master/src/Table.jsx#L589-L609) 函数头部添加对 `<Table />` 是否隐藏的判断？假如 `<Table />` 是隐藏的，就不再计算行的高度。如下：

```javascript
syncFixedTableRowHeight() {
  const bodyTableRect = this.refs.bodyTable.getBoundingClientRect();
	
  // 正常情况下 bodyTable 的高度应该大于 0，如果发现 bodyTable 的
  // 高度 <= 0，就认为 <Table /> 是隐藏的。
  if (bodyTableRect.height <= 0) {
    return;
  }
}
```

**Comment by yesmeck** [comment]
之前也有设置 `auto` 的[疑问](https://github.com/react-component/table/pull/87)

确实可以在隐藏的时候不计算高度，不过用 `getBoundingClientRect` 判断是否隐藏靠谱吗？

**Comment by ystarlongzi** [comment]
这里是 [jQuery( ":visible" )](https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/test/data/jquery-1.9.1.js#L7470-L7476) 的实现，多了几个判断条件。然后考虑到实际中对 `<Table />` 组件的应用，我觉得通过 `getBoundingClientRect` 进行判断应该足够了。

**Comment by yesmeck** [comment]
嗯，可以的，PR 吧。

**Comment by ystarlongzi** [comment]
嗯嗯，好的

**Comment by yesmeck** [comment]
还有个问题，在你用 `PureComponent` 后，在列表切换的详情的时候，UserList 本来就不应该重新渲染的，也就是 `syncFixedTableRowHeight` 是不会计算的，但是你在 `onClickFullName` 里改了状态导致 `UserList` 渲染了。。。

**Comment by ystarlongzi** [comment]
业务中的 `<UserList />` 除了 `<Table />` 组件，还包含有其它组件，然后在点击 `姓名` 后，除了希望隐藏 `<UserList />` ，还有其它业务逻辑要处理，所以还是会修改到 `state`，造成 `<UserList />` 重新 render。

**Comment by yesmeck** [comment]
@ @ 感觉你的用法也有点奇怪，不过隐藏的时候不计算高度是可以的，用 [`this.tableNode`](https://github.com/react-component/table/blob/d297856c4bb8def645735c1e697b576c63406695/src/Table.jsx#L698) 来判断吧。

**Comment by ystarlongzi** [comment]
嗯嗯，是的。好的。
