### ISSUE TITLE
Typography: Editable icon not shown on dynamical update

### ISSUE THREAD

**Issue by la99er** [ant-design/ant-design#48378]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-7j7lw6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clutmpzs500062067ve7e0tw2%2522%252C%2522sizes%2522%253A%255B66.36513157894737%252C33.63486842105263%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clutmpzs400022067jnr6jvlr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clutmpzs400032067aiwumvow%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clutntsm5006i2067bb4vu1mu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clutmpzs400022067jnr6jvlr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clutmpzs40001206795ctxxqc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A22%257D%255D%257D%255D%252C%2522id%2522%253A%2522clutmpzs400022067jnr6jvlr%2522%252C%2522activeTabId%2522%253A%2522clutmpzs40001206795ctxxqc%2522%257D%252C%2522clutmpzs400032067aiwumvow%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clutmpzs400032067aiwumvow%2522%257D%252C%2522clutntsm5006i2067bb4vu1mu%2522%253A%257B%2522id%2522%253A%2522clutntsm5006i2067bb4vu1mu%2522%252C%2522activeTabId%2522%253A%2522cluto0i6100vd2067y9o10wbo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cluto0i6100vd2067y9o10wbo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Use the Typography component and add an editable object to it.
2. Make the icon of the editable object be different, when something changes.

### What is expected?

The Icon should switch or disappear, depending on what you provide as icon.

### What is actually happening?

The icon never switches/shows up.

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.x |
| System | Linux |
| Browser | Firefox 124.0.1 |

---
When I wrap the children of the Typography component into a `span` element for example, everything seems to work. 
In "/components/typography/Base/index.tsx" in line 400, I see that the icon is wrapped by a `Tooltip`. So maybe the `Tooltip` component has an issue with changing `children` on the fly or something like that. Also, this only happens, when the children is a primitive type. As soon as I change it to a more complex type, it seems to work as well. For example
```typescript
<Typography {...}>
  {test}
</Typography>
```
When `test` is a string for example, the issue is happening.

```typescript
<Typography {...}>
  abc{test}
</Typography>
The issue is not happening.

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by crazyair** [comment]
First, try changing the children to avoid the issue, which is already being fixed

**Comment by la99er** [comment]
Thanks for the hint! I didn't look for closed tickets :see_no_evil: My bad
