### ISSUE TITLE
日文国际化时翻译错误

### ISSUE THREAD

**Issue by liujinxian** [ant-design/ant-design#48373]
### What problem does this feature solve?

在使用TimePicker 组件时，ok和now两个按钮对应的日文国际化，ok被翻译成“决定”，正确的应该是“確定”，

### What does the proposed API look like?

希望能像对话框组件那样，自己设置两个按钮的文言

**Comment by zombieJ** [comment]
直接来个 PR 吧

**Comment by crazyair** [comment]
看看之前谁改的，可以问下，别改了，他又觉得不对了

**Comment by yoyo837** [comment]
> 看看之前谁改的，可以问下，别改了，他又觉得不对了

只有一版

**Comment by crazyair** [comment]
改吧

**Comment by liujinxian** [comment]
本地打包时，直接把node_modules下面的文件内容修改下就可以了，但是容器化时，
我在dockerFile加了这两行代码
```
# 将src目录下的文件复制到容器中
COPY src//ja_JP.js /app/src/ja_JP.js

# 将src目录下的文件替换node_modules某个包中的文件
RUN cp /app/src/ja_JP.js /app/node_modules/rc-picker/es/locale/ja_JP.js
```
没有达到预期的翻译效果，不知道怎么改，有大佬知道怎么改吗

**Comment by yoyo837** [comment]
上PR，上PR

**Comment by crazyair** [comment]
rc-picker 改了，一会就发版，更新就可以用了

**Comment by liujinxian** [comment]
> rc-picker 改了，一会就发版，更新就可以用了

感谢大佬，期待中

**Comment by yoyo837** [comment]
> > rc-picker 改了，一会就发版，更新就可以用了
> 
> 感谢大佬，期待中

意思是，求人不如求己，你自己改，antd合并它

**Comment by liujinxian** [comment]
> > > rc-picker 改了，一会就发版，更新就可以用了
> > 
> > 
> > 感谢大佬，期待中
> 
> 意思是，求人不如求己，你自己改，antd合并它

最大的问题自己不会改，我自己的办法都是直接修改node_modules下的源文件

**Comment by yoyo837** [comment]
学习一下如何PR即可

**Comment by kiner-tang** [comment]
> > > > rc-picker 改了，一会就发版，更新就可以用了
> > > 
> > > 
> > > 感谢大佬，期待中
> > 
> > 
> > 意思是，求人不如求己，你自己改，antd合并它
> 
> 最大的问题自己不会改，我自己的办法都是直接修改node_modules下的源文件

可以参考这篇文章尝试一下：https://ant-design.antgroup.com/docs/blog/to-be-collaborator-cn
欢迎加入开源社区，一起共建 antd 生态。

**Comment by crazyair** [comment]
https://github.com/react-component/picker/blob/master/src/locale/ja_JP.ts

![image](https://github.com/ant-design/ant-design/assets/7971419/a9d29300-c4e8-4cfd-8ccf-552a28c176f0)

然后跟着提示走就行了

**Comment by yoyo837** [comment]
Fixed in https://github.com/react-component/picker/pull/792
