### ISSUE TITLE
How can I override an antd style?

### ISSUE THREAD

**Issue by Tsury** [ant-design/ant-design#4838]
I'm not sure if it is a bug or not, but in antd 2.7.0, the modal footer style looks like this:

```
.ant-modal-footer {
  border-top: ...
  padding: 10px 18px 10px 10px;
  text-align: ...
  border-radius: ...
}
```

Why is the padding-right 18px and not 10px? This creates asymmetry.

I'm trying to import a less file to override it:

```
@import "../../node_modules/antd/lib/style/themes/default.less";

: global {
  .ant-modal-footer {
    padding: 10px 10px 10px 10px;
  }
}
```

But it gets overridden by the default style.

**Comment by benjycui** [comment]
You need to improve your CSS selector's specificity. And it's not a bug..

**Comment by Tsury** [comment]
Ok, thanks.

**Comment by westhacker** [comment]
@benjycui What do you mean CSS selector's specificity ? I have the same issue, can you provide a proper way to override antd style ? Thx in advance.

**Comment by benjycui** [comment]
antd's style:

```css
.ant-btn { ... }
```

Your style: 

```css
.my-btn.ant-btn { ... }
```

Then, you can override it

**Comment by mattkast** [comment]
Is there any real negative effect to overriding the styles within ant?

**Comment by LaurelineP** [comment]
I can answer for the css part padding problem : 
It seems like your syntax is not correct:  when you factorise all padding setting in one line it should represents :
.className { 
            padding : padding-top , padding-right, padding-bottom , padding-left 
             }
since you did 
 padding: 10px 18px 10px 10px;
you are saying here, padding-top = 10px, padding-right = 18px, padding-bottom = 10px, padding-left = 10px;

this is why it your padding-right is 18px instead of 10.

**Comment by tahamshahzad** [comment]
> antd's style:
> 
> ```css
> .ant-btn { ... }
> ```
> 
> Your style:
> 
> ```css
> .my-btn.ant-btn { ... }
> ```
> 
> Then, you can override it

Can you kindly show how to achive this in react components, i'm unable to override any antd styled component and it's killing me

**Comment by alekslario** [comment]
tahamshahzad

> > antd's style:
> > ```css
> > .ant-btn { ... }
> > ```
> > 
> > 
> > Your style:
> > ```css
> > .my-btn.ant-btn { ... }
> > ```
> > 
> > 
> > Then, you can override it
> 
> Can you kindly show how to achive this in react components, i'm unable to override any antd styled component and it's killing me

`styled(({className, ...props})=><Button overlayClassName={className} {...props}/>)``

**Comment by Loratadin** [comment]
> 

> > antd's style:
> > ```css
> > .ant-btn { ... }
> > ```
> > 
> > 
> > Your style:
> > ```css
> > .my-btn.ant-btn { ... }
> > ```
> > 
> > 
> > Then, you can override it
> 
> Can you kindly show how to achive this in react components, i'm unable to override any antd styled component and it's killing me

In your js file you wrap antd button inside your own parent class (e.g. "saveButtonWrapper"):

`<div className="saveButtonWrapper">
      <Button icon="check-circle">Save</Button>
  </div>`

In less file nest the .ant-... classes inside your own parent tag's className (in order to avoid overriding all the antd classes in the whole app after code compilation). Write there your own css properties, for example:

`.saveButtonWrapper {
      width: 120px;
      .ant-btn {
          width: 100%;
          background-color: @dark-navy;
          color: @white;
       }
      .ant-btn:hover,
      .ant-btn:focus,
      .ant-btn:active {
           border-color: @light-gray;
           background-color: @dark-gray;
           color: @white;
       }
      .anticon {
          color: @green,
          font-size: 16px;
          margin-right: 10px;
      }
}`

If you still need more detailed explanation, please refer to the video I posted on YouTube on how to customize Ant Design components - tabs.

**Comment by ChineduOguejiofor** [comment]
> > 
> 
> > > antd's style:
> > > ```css
> > > .ant-btn { ... }
> > > ```
> > > 
> > > 
> > > Your style:
> > > ```css
> > > .my-btn.ant-btn { ... }
> > > ```
> > > 
> > > 
> > > Then, you can override it
> > 
> > 
> > Can you kindly show how to achive this in react components, i'm unable to override any antd styled component and it's killing me
> 
> In your js file you wrap antd button inside your own parent tag (e.g. "saveButtonWrapper"):
> 
> ```
>   <div className="saveButtonWrapper">
>       <Button icon="check-circle">Save</Button>
>   </div>
> ```
> 
> In less file nest the .ant-... classes inside your own parent tag's className (in order to avoid overriding all the antd classes in the whole app after code compilation). Write there your own css properties, for example:
> 
> ```
> .saveButtonWrapper {
>       width: 120px;
>       .ant-btn {
>            width: 100%;
>            background-color: @dark-navy;
>            color: @white;
>       }
>       .ant-btn:hover,
>       .ant-btn:focus,
>       .ant-btn:active {
>            border-color: @light-gray;
>            background-color: @dark-gray;
>            color: @white;
>       }
>       .anticon {
>            color: @green,
>            font-size: 16px;
>            margin-right: 10px;
>       }
> }
> ```
> 
> If you still need more detailed explanation, please refer to the video I posted on YouTube on how to customize Ant Design components - tabs.

Can you please provide a link to this video its not really clear to me

**Comment by rotimi-best** [comment]
@ChineduOguejiofor Here is a simple example to overide styles by adding your own class name and styling it from css https://codepen.io/RB_Projects/pen/MWwmPPK

**Comment by ChineduOguejiofor** [comment]
Thanks a lot
I found this very helpful

**Comment by ridvansumset** [comment]
I'd definately suggest triple greater sign for ant design vue.

**Comment by arhoy** [comment]
Just use style components or emotion js, should be able to build on top of the existing ant style from their

**Comment by Krasy8** [comment]
> > > antd's style:
> > > ```css
> > > .ant-btn { ... }
> > > ```
> > > 
> > > 
> > > Your style:
> > > ```css
> > > .my-btn.ant-btn { ... }
> > > ```
> > > 
> > > 
> > > Then, you can override it
> > 
> > 
> > Can you kindly show how to achive this in react components, i'm unable to override any antd styled component and it's killing me
> 
> In your js file you wrap antd button inside your own parent tag (e.g. "saveButtonWrapper"):
> 
> ```
>   <div className="saveButtonWrapper">
>       <Button icon="check-circle">Save</Button>
>   </div>
> ```
> 
> In less file nest the .ant-... classes inside your own parent tag's className (in order to avoid overriding all the antd classes in the whole app after code compilation). Write there your own css properties, for example:
> 
> ```
> .saveButtonWrapper {
>       width: 120px;
>       .ant-btn {
>            width: 100%;
>            background-color: @dark-navy;
>            color: @white;
>       }
>       .ant-btn:hover,
>       .ant-btn:focus,
>       .ant-btn:active {
>            border-color: @light-gray;
>            background-color: @dark-gray;
>            color: @white;
>       }
>       .anticon {
>            color: @green,
>            font-size: 16px;
>            margin-right: 10px;
>       }
> }
> ```
> 
> If you still need more detailed explanation, please refer to the video I posted on YouTube on how to customize Ant Design components - tabs.

I tried to follow this and when I changed my css file to less (so I can nest antd classes inside my wrapper class) my app stopped picking up any of my custom styles from the file.

Do I need to do some special config of less before I star using them? Sorry but never came across less before.

All I want to achieve is change a background colour of <Select> component from antd lib.

thx in advance!

**Comment by timaMehro** [comment]
https://ant.design/docs/react/customize-theme

**Comment by timaMehro** [comment]
you need to use modifyVar function from LESS  http://lesscss.org/usage/#using-less-in-the-browser-modify-variables

**Comment by peterwiebe** [comment]
> Just use style components or emotion js, should be able to build on top of the existing ant style from their

@arhoy I am using emotion and it doesn't always work :( - see my example: https://codesandbox.io/s/antd-title-styles-bug-wg2le

**Comment by hitanshiMehta-Dev** [comment]
Hello 

> > antd's style:
> > ```css
> > .ant-btn { ... }
> > ```
> > 
> > 
> > Your style:
> > ```css
> > .my-btn.ant-btn { ... }
> > ```
> > 
> > 
> > Then, you can override it
> 
> Can you kindly show how to achive this in react components, i'm unable to override any antd styled component and it's killing me

Hello, i also had same problem

**Comment by m-ata** [comment]
@tahamshahzad you can achieve like this
.customClass.ant-class {
 //your css
}

In my case I override like this
.row.ant-row {
        display: flex;
        align-items: center;
        margin: 16px;
        border-radius: 5px;
        background-color: white;
        height: 60px;
}

<Row className={'row'}>
            <Col span={12} >
                <Input.Search placeholder={'Search brand here ..'} allowClear size={'large'} />
            </Col>
            <Col span={12}>
            <Button type="primary">
                <FontAwesomeIcon icon={faPlus} /> Add Brand
            </Button>
            </Col>
</Row>

It works in my case.

**Comment by DanielOrtel** [comment]
This is a bad design in general, it should be enough for me to say `<Button className="my-class" />` and have the css of that class take priority over the default antd styles. 

It's frankly ridiculous for a UI library to require consumers to work around this limitation with weird hacks, which are bad for a number of reasons: 

- using specific selectors`.row.ant-row {}`. This is bad because we have no control over what the selector name, seeing as it's third-party. If it changes in a version, we'd have to update it everywhere we do this. 
- adding a wrapper element: this is bad because it's a useless element in the DOM, plus some components may require specific children, not just any children. Also, it still has the same problem that the previous hack has. 

Please address this. No other UI library has this problem.

**Comment by sandeepcpatil** [comment]
Its not working for me even though I wrap them inside the wrapper div 

html:
<div nz-row *ngIf="current === 0" class="unique" >
  <div nz-col nzSpan="12" style="padding: 60px">
    <img
      class="work-img"
      src="../../../assets/Images/firstPageImg.jpg"
      alt="work-img"
    />
  </div>
  <div nz-col nzSpan="12">
    <form
      nz-form
      *ngIf="current == 0"
      [formGroup]="validateDetailsForm"
      (ngSubmit)="submitForm()"
      class="details"
    >
      <nz-form-item >
        <nz-form-label [nzSpan]="7" nzRequired  > Validator Name </nz-form-label>
        <nz-form-control
          [nzSpan]="12"
          nzErrorTip="Please give name to validator"
        >
          <input
            nz-input
            placeholder="Validator Name"
            formControlName="compName"
            [(ngModel)]="validator_obj[0].name"
          />
        </nz-form-control>
      </nz-form-item>
      <nz-form-item >
        <nz-form-label [nzSpan]="7" nzRequired >
          Validator Description
        </nz-form-label>
        <nz-form-control
          [nzSpan]="12"
          nzErrorTip="Please write something about the validator"
        >
          <textarea
            nz-input
            rows="2"
            placeholder="Validator Description"
            formControlName="compDesc"
            [(ngModel)]="validator_obj[0].description"
          ></textarea>
        </nz-form-control>
      </nz-form-item>
    </form>
  </div>
</div>


styles:
.unique {
  background: #fff;
  margin-top: 20px;
  ant-form-item-label > label {
    font-size: 16px;
    font-weight: 600;
  }
}

**Comment by HiiragiMatu** [comment]
Just give any ant component a className and specify the element start from like '.ant-card.className'.

.ant-card.myOwnCard {
}
