### ISSUE TITLE
FormInstance setFields 希望支持validateStatus 状态的控制 

### ISSUE THREAD

**Issue by ouy-o3o** [ant-design/ant-design#48390]
### What problem does this feature solve?

极大简化了复杂表单进行自定义的错误状态控制 ，现在想要在接口级别做form item 的错误展示必须受控状态，或者写一个无关的form item name 来控制，在内部表单里监听这个无关的值 再变更validateStatus，链路太长，有很多无效的表单控件被催生出来

### What does the proposed API look like?

期望在setFields 方法里添加validateStatus 的控制

**Comment by zombieJ** [comment]
Form 本身支持字段绑定的状态控制和纯 UI 的展示用途。

对于数据绑定。字段状态不是一个实体状态，在 Field 中通过 `meta` 的 `validating` `warnings` `errors` 聚合而成。在调用 `setFields` 后填充对应内容会切换至目标状态。

对于非数据驱动的需求，就是通过 FormItem 的 `validateStatus` 来控制。

这两者是不应该混合的，但是如果你硬要如此，可以 HOC `useForm` hook 返回一个封装的 `setFields`，根据 `validateStatus` 填虚假的数据到目标状态哈~
