### ISSUE TITLE
table props.rowKey 支持数组

### ISSUE THREAD

**Issue by aladdin-add** [ant-design/ant-design#48397]
### What problem does this feature solve?

在v5/v4中，table 组件的 rowKey 类型签名是：`string | function(record): string`

所以如果我需要2个字段作为主key，需要写成函数形式：
```js
const props = {rowKey: r => r.name +  r.value}; // value变化时需要更新
```

### What does the proposed API look like?

希望可以支持数组：
```js
const props = {rowKey: ["name", "value"]}; // value变化时需要更新
```

**Comment by afc163** [comment]
函数形式已经能满足需求了，需要支持数组的必要性是？

**Comment by crazyair** [comment]
`value变化时需要更新` 需要更新什么？

**Comment by aladdin-add** [comment]
不是必要，而是开发体验优化。 如果仅仅是需要多个字段作为主key，使用数组的开发体验更好。:)

如果有更高级的需求，还是需要使用函数。

**Comment by afc163** [comment]
用函数为啥开发者体验会不好呢？这点我可能没 GET 到。

**Comment by afc163** [comment]
我个人更喜欢用函数，我都想把 string 语法糖干掉。
