### ISSUE TITLE
请问我们有类似图形界面设计器的项目吗

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design#4839]
#### Environment(required)

- antd version:ant design 2.7.1
- OS and its version: windows 10
- Browser and its version: chrome

#### What did you do? Please provide steps to re-produce your problem.

请问我们有类似这种 https://github.com/ascoders/gaea-editor 图形界面设计器的项目吗

http://next.baidu.com/design/editor/8a6e673e0c0687ec28d25cfa?type=web&isExplore=1

**Comment by benjycui** [comment]
不懂，是用 antd 做的这种项目，还是能通过这种项目使用 antd.

**Comment by eddyzhang1986** [comment]
@benjycui  我的意思就是说，ant design 有提供类似 这种可视化编程的工具吗
如果目前还没有的话，有没有计划做类似的项目呢
感觉这个还不错，就是没有直接生成JSX CODE 只是生成描述JSON

**Comment by afc163** [comment]
#3540

**Comment by eddyzhang1986** [comment]
@afc163  ok明白了,那我试着在gaeaeditor 里面添加一下  ant 的插件试试

**Comment by eddyzhang1986** [comment]
他这里有个例子，我尝试一下，测试一下
https://github.com/ascoders/gaea-editor/blob/master/docs/custom-options.md
@benjycui 
@afc163
