### ISSUE TITLE
```DatePicker.RangePicker``` breaks with ```showTime``` and ```showSecond={false}```

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#48405]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-cuzmy2?file=src%2FApp.tsx)

### Steps to reproduce

1. Click on DatePicker
2. Select a date

### What is expected?

To be able to select a time as well.

### What is actually happening?

1. Time is not selectable
2. When you click on a date the app crashes

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

---
Related issue: https://github.com/ant-design/ant-design/issues/47549
Probably broken by #46982

**Comment by zombieJ** [comment]
thx for ref https://github.com/ant-design/ant-design/issues/47549

Seems worked after fix it.

https://stackblitz.com/edit/react-qnihtw?file=demo.tsx
