### ISSUE TITLE
`<Tabs>`组件宽度,在`flex布局`下,宽度无法控制

### ISSUE THREAD

**Issue by diandian18** [ant-design/ant-design#48403]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-7phgm7?file=index.css)

### Steps to reproduce

1. 容器为`flex布局`,左`div`宽度固定(`width: 200px`),右`div`宽度自适应(`flex:1`)
2. `<Tabs>`组件放在右侧`div`内,多写几个`tab items`,使组件总宽度能超过页面宽度

### What is expected?

右侧`div`可以宽度自适应

### What is actually happening?

右侧`div`宽度没有自适应,并出现了横向滚动条

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2.0 |
| System | macos |
| Browser | Chrome 版本 123.0.6312.105（正式版本） （64 位） |

**Comment by afc163** [comment]
min-width: 0;

https://stackblitz.com/edit/react-7phgm7-hd8fyu?file=index.css

**Comment by diandian18** [comment]
> min-width: 0;
> 
> https://stackblitz.com/edit/react-7phgm7-hd8fyu?file=index.css

好了.谢谢你.这是flex的特点,不是antd的问题,非常抱歉占用了你的时间.
