### ISSUE TITLE
antd Table 组件 开启虚拟表格， 移动端不支持手势的横向滚动条滑动。

### ISSUE THREAD

**Issue by zdJOJO** [ant-design/ant-design#48400]
### What problem does this feature solve?

移动端使用Table虚拟表格时，手势滑动数据， table目前只支持纵向滚动条， 不支持横向滚动条

### What does the proposed API look like?

移动端使用Table虚拟表格时，手势滑动数据， table目前只支持纵向滚动条， 也支持横向滚动条

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/47113
