### ISSUE TITLE
建议给`formItemControl wrapper`一个className

### ISSUE THREAD

**Issue by jzlxiaohei** [ant-design/ant-design#4841]
目前antd from的dom结构是
```html
<div class="ant-form-item-label">
<div>
    <div class="ant-form-item-control">...</div>
</div>
```
这样的话，我想通过`display: flex` 让 `item-control` `flex:1` 充满剩余空间，就很难做。

具体代码在
https://github.com/ant-design/ant-design/blob/master/components/form/FormItem.tsx#L193

**Comment by benjycui** [comment]
你使用的版本和调用方式？最新的是有的。

**Comment by jzlxiaohei** [comment]
我用的2.7的，另外官网上我看了下，也是没有，有的是Col 相关的class。
![719a2968-bfd0-4001-b573-222dbba82016](https://cloud.githubusercontent.com/assets/1884248/22876831/74470476-f20d-11e6-8c3e-e87cad1ba9e6.png)

**Comment by benjycui** [comment]
`[class=ant-col-*]` 不能满足你的需求？

你可以来个 PR 加上，但是要周末才能发版本。

**Comment by jzlxiaohei** [comment]
这个选择器不太好吧。另外，必须设置 labelCol 才有。
命名成`ant-form-item-control-wrapper`?

**Comment by benjycui** [comment]
OK
