### ISSUE TITLE
有自定义select中input区域的需求，能使用 getRawInputElement 吗？

### ISSUE THREAD

**Issue by happy-windman** [ant-design/ant-design#48413]
### Reproduction link

[https://github.com/react-component/select/pull/639](https://github.com/react-component/select/pull/639)

### Steps to reproduce

看到部分下拉组件是基于rc-select实现的，antd中只有cascader是支持input区域的自定义

### What is expected?

是否可以使用 getRawInputElement  自定义部分下拉组件input区域的内容，比如TreeSelect。进行二次封装时可以自己控制显示Dom。

### What is actually happening?

以上

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | 17 |
| System | mac os |
| Browser | Chrome |

---
https://github.com/react-component/select/issues/682

**Comment by zombieJ** [comment]
自定义输入组件其实问题不少，在 Cascader 里也有很多 hack 的逻辑。理论上不会再新增了。可以通过 HOC Select，隐藏掉输入框，受控 `open` 来实现自定义输入区域的效果哈~
