### ISSUE TITLE
文档demo 的TS/JS 语法切换 支持全局设置.

### ISSUE THREAD

**Issue by zhangenming** [ant-design/ant-design#48414]
### What problem does this feature solve?

个人感觉 对demo而言 js模式更适合快速查看/理解代码 因为没有ts的类型代码减少了视野干扰
但目前每个demo的语言模式 是单独控制的  所以每个都要点一遍 比较麻烦 不那么友好

### What does the proposed API look like?

新增一个新的全局切换按钮,
或者
在现在按钮的基础上 默认全局切换 并缓存本地

**Comment by zhangenming** [comment]
另外 报一个不知道是feat/bug的问题

目前文档demo上 只支持TS代码的在线编辑
js代码是只读的
并且如果修改ts代码后 切换为js代码模式 demo还是保留ts代码的结果

**Comment by afc163** [comment]
可行，来个 PR ~

**Comment by zhangenming** [comment]
我不会啊 给点指导吧 这东西的代码在哪呢 antd和dumi的仓库里找了找 都没找到

**Comment by zhangenming** [comment]
参考
https://mui.com/material-ui/react-box/
这个页面可以做到 编辑代码后 ts和js同步更新
