### ISSUE TITLE
通过`<Tabs>`组件的`renderTabBar`自定义的标签头，在某标签`active`的时候，无法定位到该标签，`ant-tabs-nav-list`元素的位移总是`transform: translate(0px, 0px);`不变

### ISSUE THREAD

**Issue by diandian18** [ant-design/ant-design#48422]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-y1ansm?file=demo.tsx)

### Steps to reproduce

1. 通过`renderTabBar`自定义，并且不使用内置提供的node，想完全自定义样式
2. 
        <Tabs
          type="editable-card"
          onChange={onChange}
          onEdit={onEdit}
          items={items}
          activeKey={activeKey}
          renderTabBar={(tabBarProps, DefaultTabBar) => (
            <DefaultTabBar {...tabBarProps}>
              {(node) => (
                <div style={{ border: '1px solid red', margin: '10px' }}>
                  111
                  {/* {node} */}
                </div>
              )}
            </DefaultTabBar>
          )}
        />

2. 在复现链接里，点击去第8个tab的按钮

### What is expected?

1. 第8个标签可以成功定位到视口
2. `ant-tabs-nav-list`元素的位移不是`transform: translate(0px, 0px);`

### What is actually happening?

1. `ant-tabs-nav-list`元素的位移总是`transform: translate(0px, 0px);`
2. 需求请求：可以提供相关类似于`scrollToTab`的api，用于在自定义Tab里定位标签

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 版本 123.0.6312.105（正式版本） （64 位） |

---
如果换成内置的node，可以顺利定位

**Comment by afc163** [comment]
可以试试：https://stackblitz.com/edit/react-y1ansm-tom9vd?file=demo.tsx 作为 workaround。

```jsx
                  <span
                    style={{
                      position: 'absolute',
                      visibility: 'hidden',
                      pointerEvents: 'none',
                    }}
                  >
                    {node}
                  </span>
```

**Comment by diandian18** [comment]
> 可以试试：https://stackblitz.com/edit/react-y1ansm-tom9vd?file=demo.tsx 作为 workaround。
> 
> ```js
>                   <span
>                     style={{
>                       position: 'absolute',
>                       visibility: 'hidden',
>                       pointerEvents: 'none',
>                     }}
>                   >
>                     {node}
>                   </span>
> ```

妙啊，赞！感谢！
