### ISSUE TITLE
低版本浏览器兼容问题

### ISSUE THREAD

**Issue by 18838209380** [ant-design/ant-design#48425]
### Reproduction link

[https://new.saledrama.com/console/login](https://new.saledrama.com/console/login)

### Steps to reproduce

访问链接后登录框样式有问题

### What is expected?

跟高版本chrome样式一致

### What is actually happening?

样式错乱  仍有where选择器

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | "react": "^18.2.0", |
| System | win10 |
| Browser | 360 极速浏览器 |

---
"@umijs/max": "^4.0.52","antd": "^5.16.1","react": "^18.2.0",
在app.ts中增加了  
export function rootContainer(container: React.ReactElement) {
    return React.createElement(
        StyleProvider,
        {
            hashPriority: 'high',
            transformers: [legacyLogicalPropertiesTransformer],
        },
        container,
    );
}

**Comment by 18838209380** [comment]
export default defineConfig({
    hash: true,
    links: [{rel: 'icon', href: '/console/favicon.ico'}],
    routes: routes,
    /**
     * @name 主题的配置
     * @description 虽然叫主题，但是其实只是 less 的变量设置
     * @doc antd的主题设置 https://ant.design/docs/react/customize-theme-cn
     * @doc umi 的theme 配置 https://umijs.org/docs/api/config#theme
     */
    theme: {
        // 如果不想要 configProvide 动态设置主题需要把这个设置为 default
        // 只有设置为 variable， 才能使用 configProvide 动态设置主色调
        'root-entry-name': 'variable',
    },
    /**
     * @name moment 的国际化配置
     * @description 如果对国际化没有要求，打开之后能减少js的包大小
     * @doc https://umijs.org/docs/api/config#ignoremomentlocale
     */
    ignoreMomentLocale: true,
    /**
     * @name 代理配置
     * @description 可以让你的本地服务器代理到你的服务器上，这样你就可以访问服务器的数据了
     * @see 要注意以下 代理只能在本地开发时使用，build 之后就无法使用了。
     * @doc 代理介绍 https://umijs.org/docs/guides/proxy
     * @doc 代理配置 https://umijs.org/docs/api/config#proxy
     */
    proxy: proxy[REACT_APP_ENV as keyof typeof proxy],
    base: '/console/',
    publicPath: '/console/',
    /**
     * @name 快速热更新配置
     * @description 一个不错的热更新组件，更新时可以保留 state
     */
    fastRefresh: true,
    //============== 以下都是max的插件配置 ===============
    /**
     * @name 数据流插件
     * @@doc https://umijs.org/docs/max/data-flow
     */
    model: {},
    /**
     * 一个全局的初始数据流，可以用它在插件之间共享数据
     * @description 可以用来存放一些全局的数据，比如用户信息，或者一些全局的状态，全局初始状态在整个 Umi 项目的最开始创建。
     * @doc https://umijs.org/docs/max/data-flow#%E5%85%A8%E5%B1%80%E5%88%9D%E5%A7%8B%E7%8A%B6%E6%80%81
     */
    initialState: {},
    /**
     * @name layout 插件
     * @doc https://umijs.org/docs/max/layout-menu
     */
    title: '智能客服',
    layout: {
        locale: true,
        ...defaultSettings,
    },
    /**
     * @name moment2dayjs 插件
     * @description 将项目中的 moment 替换为 dayjs
     * @doc https://umijs.org/docs/max/moment2dayjs
     */
    moment2dayjs: {
        preset: 'antd',
        plugins: ['duration'],
    },
    /**
     * @name 国际化插件
     * @doc https://umijs.org/docs/max/i18n
     */
    locale: {
        // default zh-CN
        default: 'zh-CN',
        antd: true,
        // default true, when it is true, will use `navigator.language` overwrite default
        baseNavigator: true,
    },
    /**
     * @name antd 插件
     * @description 内置了 babel import 插件
     * @doc https://umijs.org/docs/max/antd#antd
     */
    antd: {
        appConfig: {},
    },
    /**
     * @name 网络请求配置
     * @description 它基于 axios 和 ahooks 的 useRequest 提供了一套统一的网络请求和错误处理方案。
     * @doc https://umijs.org/docs/max/request
     */
    request: {},
    /**
     * @name 权限插件
     * @description 基于 initialState 的权限插件，必须先打开 initialState
     * @doc https://umijs.org/docs/max/access
     */
    access: {},
    /**
     * @name <head> 中额外的 script
     * @description 配置 <head> 中额外的 script
     */
    headScripts: [
        // 解决首次加载时白屏的问题
        {src: '/console/scripts/loading.js', async: true},
        // 图标
        {src: '/console/scripts/iconfont.js', async: true},
        // gojs
        {src: '/console/scripts/go.js', async: true},
        // 百度地图
        // { src: '//api.map.baidu.com/api?v=3.0&ak=', async: true }
    ],
    //================ pro 插件配置 =================
    presets: ['umi-presets-pro'],
    // 自定义插件
    plugins: ['./plugins/plugin-global'],
    /**
     * @name openAPI 插件的配置
     * @description 基于 openapi 的规范生成serve 和mock，能减少很多样板代码
     * @doc https://pro.ant.design/zh-cn/docs/openapi/
     */
    openAPI: openapi as any,
    mfsu: {
        strategy: 'normal',
    },
    requestRecord: {},
    define: {
        LOGIN_PATH: '/login',
        AGENT_PATH: ':8090/online',
    },
    extraBabelPlugins: [
        [
            '@helven/i18n',
            {
                strict: false,
                langs: ['zh-CN', 'en-US'],
                output: './src/locales',
            },
        ],
    ],
    targets: {
        chrome: '78',
        ie: '10',
    },
    legacy:{
        buildOnly:true
    },
    tailwindcss: {},
    dva: {},
    chainWebpack(memo) {
        memo.plugin('monaco-editor').use(MonacoWebpackPlugin, [
            {
                // 支持代码高亮显示的语言
                languages: ['json', 'java', 'python', 'sql', 'mysql', 'html', 'css', 'less', 'scss', 'javascript', 'typescript', 'xml'],
            },
        ]);
    },
    esbuildMinifyIIFE:true
});

**Comment by afc163** [comment]
See https://ant.design/docs/react/compatible-style-cn
