### ISSUE TITLE
在Remix项目中使用，当路由到异常页面，再浏览器返回app crash

### ISSUE THREAD

**Issue by JackyMR** [ant-design/ant-design#48423]
### Reproduction link

[https://github.com/JackyMR/RemixJS-train](https://github.com/JackyMR/RemixJS-train)

### Steps to reproduce

1. 页面首页按钮点击Log out，路由到一个错误404页面；
2. 点击浏览器返回；
3. 应用崩溃。

### What is expected?

页面正常，无错误❌，无警告。

### What is actually happening?

应用崩溃，无痕模式同样崩溃。
![image](https://github.com/ant-design/ant-design/assets/10016238/eba8752b-9bd4-4815-9d0d-cc6cd2f68fe8)

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | ^18.2.0 |
| System | MacOS 13.3.1 |
| Browser | Google Chrome 123.0.6312.87（正式版本） (x86_64) |

**Comment by JackyMR** [comment]
Can somebody check this issue?

**Comment by JackyMR** [comment]
> 复现怎么用交代一下，跑不起来，猜测应该和 antd 没关系

npm run dev需要等一下依赖安装。

**Comment by yoyo837** [comment]
> > 复现怎么用交代一下，跑不起来，猜测应该和 antd 没关系
> 
> npm run dev需要等一下依赖安装。

Invariant failed: SESSION_SECRET must be set

**Comment by JackyMR** [comment]
> > > 复现怎么用交代一下，跑不起来，猜测应该和 antd 没关系
> > 
> > 
> > npm run dev需要等一下依赖安装。
> 
> Invariant failed: SESSION_SECRET must be set

Try this [repo](https://github.com/JackyMR/Remix-train2), just a very simple Remix demo with intergation of AntD. 
This will occur the error of "TypeError: Cannot read properties of null (reading 'children') at findStyles ....".
![image](https://github.com/ant-design/ant-design/assets/10016238/5efbd200-9dfe-46ff-9e4f-cfc39bea4048)

**Comment by yoyo837** [comment]
<img width="1518" alt="image" src="https://github.com/ant-design/ant-design/assets/6134547/91d455e8-d6b0-4a2e-99f8-6fef47df501b">

**Comment by JackyMR** [comment]
1. 正常打开。

![image](https://github.com/ant-design/ant-design/assets/10016238/4f0ae7bd-2d5d-45ad-84c4-d50d8cbb64d3)

2. 路由到错误页面
![image](https://github.com/ant-design/ant-design/assets/10016238/6a14f6e4-2722-4bd9-8fdd-cf271273275d)
3. 浏览器返回即出现报错
![image](https://github.com/ant-design/ant-design/assets/10016238/4f8fa6ea-3bb5-43ab-985d-e2858a084747)

**Comment by yoyo837** [comment]
无法重现

**Comment by JackyMR** [comment]
> 无法重现

感谢。那再等等看其他同学会不会出现这个问题。

**Comment by JackyMR** [comment]
Please keep this issue is Open before fixed.

**Comment by yoyo837** [comment]
请提供可复现的链接随时打开一个新的issue.

**Comment by BruceCham** [comment]
@JackyMR @yoyo837  问题最终有解决吗？我遇到同样的问题，不过造成的原因是一些浏览器插件，比如翻译插件，高亮词插件，会引起dom diff，造成组件报错

**Comment by JackyMR** [comment]
> @JackyMR @yoyo837 问题最终有解决吗？我遇到同样的问题，不过造成的原因是一些浏览器插件，比如翻译插件，高亮词插件，会引起dom diff，造成组件报错

貌似还没解决。

**Comment by quinn** [comment]
I am also having this problem.

**Comment by afc163** [comment]
@quinn Could you help to reproduce this bug?

**Comment by BruceCham** [comment]
> @quinn Could you help to reproduce this bug?

https://github.com/ant-design/ant-design/issues/51337#issuecomment-2437103988
