### ISSUE TITLE
希望Select multiple能支持clear

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#4843]
RT
`<Select multiple allowClear />`

**Comment by RaoHai** [comment]
https://github.com/react-component/select/blob/master/src/Select.jsx#L938

是做了特殊判断的不支持。@yiminghe 这里是有什么设计么？

**Comment by yiminghe** [comment]
设计，交互 没有

**Comment by benjycui** [comment]
ping 了交互，他们讨论先吧。

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/23395234/87e7aa50-fdc8-11e6-8620-e07155c37638.png)

**Comment by benjycui** [comment]
设计稿可以了。

**Comment by afc163** [comment]
有点麻烦，有可能互相覆盖。

**Comment by benjycui** [comment]
那只能让设计再更新下设计稿了。。

**Comment by benjycui** [comment]
设计稿已更新 https://github.com/ant-design/ant-design/issues/4843#issuecomment-282961405

**Comment by benjycui** [comment]
业务需要，这周完成吧。。
