### ISSUE TITLE
Range picker not re-focus on start date input

### ISSUE THREAD

**Issue by ndc1509** [ant-design/ant-design#48445]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-nlvogm?file=demo.tsx)

### Steps to reproduce

set range picker props "open = true"

### What is expected?

after selecting a range, input should re-focus to the start input, like in version 5.13.0. To allow user select a new start date

### What is actually happening?

after selecting a range, input still focus on the end input

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

**Comment by MadCcc** [comment]
You can focus back manually

**Comment by faiz-9** [comment]
Everything is working fine , ignore A4Dragon's comment

**Comment by A4Dragon** [comment]
@MadCcc Is this issue resolved for you

**Comment by A4Dragon** [comment]
@ndc1509 you got any resolution for this

**Comment by A4Dragon** [comment]
> You can focus back manually. It was a bug before and we fixed it.

Please reply as soon as possible
