### ISSUE TITLE
在List组件中的item中使用Modal弹出的窗口遮罩层背景色会变成纯黑色，失去了默认的背景色及透明效果

### ISSUE THREAD

**Issue by lyJava** [ant-design/ant-design#48446]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-tdngjy?file=demo.tsx)

### Steps to reproduce

```typescript
import React from 'react';
import { Button, Divider, List, Modal, Typography } from 'antd';
import { useState } from 'react';

const data = [
  'Racing car sprays burning fuel into crowd.',
  'Japanese princess to wed commoner.',
  'Australian walks 100km after outback crash.',
  'Man charged over missing wedding girl.',
  'Los Angeles battles huge wildfires.',
];

const App: React.FC = () => {
  const [open2, setOpen2] = useState(false);
  const [open3, setOpen3] = useState(false);
  const [open4, setOpen4] = useState(false);

  const showModal2 = () => {
    setOpen2(true);
  };

  const hideModal2 = () => {
    setOpen2(false);
  };

  const showModal3 = () => {
    setOpen3(true);
  };

  const hideModal3 = () => {
    setOpen3(false);
  };

  const showModal4 = () => {
    setOpen4(true);
  };

  const hideModal4 = () => {
    setOpen4(false);
  };

  return (
    <>
      <Button type="primary" onClick={showModal2}>
        正常弹窗
      </Button>
      <Modal
        title="Modal"
        open={open2}
        onOk={hideModal2}
        onCancel={hideModal2}
        okText="确认"
        cancelText="取消"
      >
        <p>Bla bla ...</p>
        <p>Bla bla ...</p>
        <p>Bla bla ...</p>
      </Modal>
      <Divider orientation="left">Default Size</Divider>
      <Button type="primary" onClick={showModal3}>
        正常
      </Button>
      <Modal
        title="Modal"
        open={open3}
        onOk={hideModal3}
        onCancel={hideModal3}
        okText="确认"
        cancelText="取消"
      >
        <p>Bla bla ...</p>
        <p>Bla bla ...</p>
        <p>Bla bla ...</p>
      </Modal>
      <List
        header={<div>Header</div>}
        footer={<div>Footer</div>}
        bordered
        dataSource={data}
        renderItem={(item) => (
          <List.Item>
            <Typography.Text mark>[ITEM]</Typography.Text> {item}
            <Button  type="link" onClick={showModal4}>
              编辑
            </Button>
            <Modal
              title= {"弹窗黑色" + new Date().getTime()} 
              open={open4}
              onOk={hideModal4}
              onCancel={hideModal4}
              okText="确认"
              cancelText="取消"
            >
              <p>Bla bla ...</p>
              <p>Bla bla ...</p>
              <p>Bla bla ...</p>
            </Modal>
          </List.Item>
        )}
      ></List>
    </>
  );
};
export default App;
```

### What is expected?

正常情况下，Modal弹窗的遮罩层不是纯黑色，且有透明度

### What is actually happening?

实际上上面的<List.Item>中的Modal弹窗的遮罩层背景色纯黑色且不透明

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2.0 |
| System | macOS Monterey |
| Browser | 123.0.6312.122 (正式版本) (arm64)  |

---
直接copy代码运行就可以看到结果了，或者直接把代码在官网上面粘贴也可以

**Comment by wangyi12358** [comment]
兄弟，这是你代码问题 `open4` 一次性控制了多个 `List.Item` 下面的 `Modal`，重叠了。

**Comment by lyJava** [comment]
这种场景完全存在的，比如我在这里边弹窗进行编辑

**Comment by lyJava** [comment]
> 兄弟，这是你代码问题 `open4` 一次性控制了多个 `List.Item` 下面的 `Modal`，重叠了。


这种场景完全存在的，比如我在这里边弹窗进行编辑。而且每多一个Item，弹出的Modal的背景色会加深一点，直至变得全黑到透明度没有了。这里也可逐步减少data数组的元素，就可以观察到效果

**Comment by wanpan11** [comment]
不要在 renderItem 里面渲染 Modal，上面的代码相当于同时渲染了5个 open=true 的 Modal 

![image](https://github.com/ant-design/ant-design/assets/38714194/ea8fb2f2-757d-4964-a5f4-fdef39240cfb)

**Comment by afc163** [comment]
@wanpan11 和 @wangyi12358 的回答是正确的，你需要有两个选择：

1. 只留一个 Modal 和一个 open，避免多个 Modal 同时弹出。
2. 或者用不同的 openXxx 去控制不同的 Modal，避免多个 Modal 同时弹出。

**Comment by lyJava** [comment]
> 不要在 renderItem 里面渲染 Modal，上面的代码相当于同时渲染了5个 open=true 的 Modal
> 
> ![image](https://private-user-images.githubusercontent.com/38714194/322331992-ea8fb2f2-757d-4964-a5f4-fdef39240cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTM3MjcsIm5iZiI6MTcxMzE1MzQyNywicGF0aCI6Ii8zODcxNDE5NC8zMjIzMzE5OTItZWE4ZmIyZjItNzU3ZC00OTY0LWE1ZjQtZmRlZjM5MjQwY2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAzNTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMDAyMjUwMzg1NzBlNTIwOGUzYTNiZTZkODc3OTZjY2QwN2U1NDI5M2Y0ZjQ4NmMyZDEyNzA0YjFjM2M0YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.miUmarQY-IcNvN9NF-VBbbmvzi5K63hl_u5lQWlTV4s)

😂 理解了。谢谢大佬

**Comment by 598634123** [comment]
nb哈哈

**Comment by 598634123** [comment]
> [@wanpan11](https://github.com/wanpan11) 和 [@wangyi12358](https://github.com/wangyi12358) 的回答是正确的，你有两个改动选择：
> 
> 1. 只留一个 Modal 和一个 open，避免多个 Modal 同时弹出。
> 2. 或者用不同的 openXxx 去控制不同的 Modal，避免多个 Modal 同时弹出。

nb 哈哈 一入前端深似海
