### ISSUE TITLE
Modal 设置 getContainer 后 autoLock 失效

### ISSUE THREAD

**Issue by youngBrain1893** [ant-design/ant-design#48452]
### Steps to reproduce

弹窗展示 body 未锁定

### What is expected?

弹窗展示时 body 不可滚动

### What is actually happening?

弹窗展示时 body 可滚动（mask 下内容可滚动）

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 16.13.1 |
| System | All |
| Browser | All |

---
业务上下文：业务微前端使用 css-scope 的方式做样式隔离，需要指定 getPopupContainer 用于样式前缀生效
排查 @rc-components/portal **仅**对 getPopupContainer 返回 document.body 或 null 的时候进行 Lock 操作

相关代码：https://github.com/react-component/portal/blob/master/src/Portal.tsx#L100

**Comment by youngBrain1893** [comment]
### 复现路径
https://codesandbox.io/p/sandbox/antd-modal-ps7lj3

**Comment by MadCcc** [comment]
目前就是不支持的，可以自行封装一下 lock 逻辑

**Comment by youngBrain1893** [comment]
> 目前就是不支持的，可以自行封装一下 lock 逻辑

@MadCcc 是指自己业务内所有的 Modal 都去添加这个逻辑吗?
