### ISSUE TITLE
启动npm start报错

### ISSUE THREAD

**Issue by next2014** [ant-design/ant-design#4845]
> @ start C:\Users\Administrator.WIN7U-20150315M\antd-demo\myapp
> roadhog server

'roadhog' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--registry=https://registry.npm.taobao.org" "--cache=C:/Users/Administrator.WIN7U-20150315M/.npm/.cache/cnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=C:/Users/Administrator.WIN7U-20150315M/.cnpmrc" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ start: `roadhog server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'roadhog server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     roadhog server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator.WIN7U-20150315M\antd-demo\myapp\npm-debug.log

**Comment by benjycui** [comment]
工具问题应该提到对应的仓库

ping @sorrycc

**Comment by sorrycc** [comment]
看不出来是啥问题，会不会依赖没安装好?

**Comment by afc163** [comment]
建议提到：https://github.com/dvajs/dva-cli 并提供更多信息。
