### ISSUE TITLE
Message 使用命令式调用一次后，再次调用Message会共用instance，导致传入的getPopupContainer无法生效

### ISSUE THREAD

**Issue by onionbrowsers** [ant-design/ant-design#48458]
### Reproduction link

[https://codepen.io/out-lay/pen/JjVBedo](https://codepen.io/out-lay/pen/JjVBedo)

### Steps to reproduce

1. 注释掉useEffect中的message，点击button后发现可以在dom中弹出提示
2. 放开useEffect中的message，点击button后发现提示挂载到body中，getPopupContainer不生效

### What is expected?

期望message设置的container可以正常挂载message

### What is actually happening?

传入的getPopupContainer因与message使用同一个实例不生效
![image_a2a01001-2221-402d-a8f2-b36ed3418c32](https://github.com/ant-design/ant-design/assets/35332092/434f741e-870f-4ea2-9990-7ee2f34ca8f8)

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.2.10 |
| System | macos 12.3.1 (21E258) |
| Browser | chrome 123.0.6312.123（正式版本） (arm64) |

**Comment by zombieJ** [comment]
静态方法仅做有限支持，可以考虑使用 hooks 方法。

ref [《静态方法之痛》](https://ant-design.antgroup.com/docs/blog/why-not-static-cn)

**Comment by onionbrowsers** [comment]
> 静态方法仅做有限支持，可以考虑使用 hooks 方法。
> 
> ref [《静态方法之痛》](https://ant-design.antgroup.com/docs/blog/why-not-static-cn)

看了一下使用hooks的方式，我尝试了一下使用messageApi，传入的getPopupContainer没有生效，看了一下useMessage的源码，并没有将我传入的getPopupContainer作用上，而且如果使用hooks，我该如何限制maxCount为1呢？

https://codepen.io/out-lay/pen/JjVBedo
这是修改使用hooks后的复现链接
