### ISSUE TITLE
Select is displaying value as label when options are empty

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#48451]
### Reproduction link

[https://codepen.io/Kevin-Wang-the-selector/pen/WNWKgBx?editors=001](https://codepen.io/Kevin-Wang-the-selector/pen/WNWKgBx?editors=001)

### Steps to reproduce

set options to empty array and set value to a string. Select is showing the value as label instead of empty when values are not matching to options

### What is expected?

Select should be display empty if no provided value dont match the options

### What is actually happening?

Select display value if not matching options

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/47622#issuecomment-1968249702
