### ISSUE TITLE
[BUG: Slider] Slider marks can not work when step is null

### ISSUE THREAD

**Issue by hs-ltbyce** [ant-design/ant-design#48459]
### Reproduction link

[https://codepen.io/hs-ltbyce/pen/ZEZjqgV?editors=1111](https://codepen.io/hs-ltbyce/pen/ZEZjqgV?editors=1111)

### Steps to reproduce

使用Slider时， 通过设置 stpe = null,实现只能选择marks;

实际上能选择的点除了marks，还包含了min和max

例如在重现链接中： 

```
const marks = {
  1: "1",
  8: "8",
}

<Slider marks={marks} step={null}  min={0} max={10} />
```
实际能选择的值: 0, 1, 8 ,10

不清楚这个是属于设计问题还是bug？如果是设计问题， 那么step = null时的行为，就与文档中描述的只能选择mark点不符

### What is expected?

当 marks 不为空对象时，可以设置 step 为 null，此时 Slider 的可选值仅有 marks 标出来的部分

### What is actually happening?

当step = null时，可选值除了marks，还包含了min和max

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | ^18.2.0 |
| System | macos |
| Browser | - |

**Comment by hs-ltbyce** [comment]
> 设计如此，这个现在也不好改

可以考虑引入新的属性做补丁吗？在不影响现有逻辑的情况下。
marks如果不能完全控制，相当于无法控制

**Comment by zombieJ** [comment]
可以用受控形式，当拖拽到 min 和 max 则跳过:
https://stackblitz.com/edit/react-tymkus?file=demo.tsx
