### ISSUE TITLE
LocaleProvider状态改变，页面不刷新

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design#4846]
#### Environment(required)

- antd version: 2.7.0
- OS and its version: windows
- Browser and its version: chrome

#### What did you do? Please provide steps to re-produce your problem.

使用LocaleProvider通过按钮改变页面语言

#### What do you expected?

实现相关语言切换

#### What happen?

![qq 20170213154756](https://cloud.githubusercontent.com/assets/18028721/22875041/628f7618-f204-11e6-9f02-d511b1d9d76c.png)
![qq 20170213154843](https://cloud.githubusercontent.com/assets/18028721/22875039/61c45c4e-f204-11e6-93c9-e96ffcd6880d.png)
状态变化了，页面不刷新

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by guangming21** [comment]
@benjycui 多语言切换得做俩套页面吗

**Comment by guangming21** [comment]
难道现在不会自己更新吗？得刷新页面才可以吗

**Comment by benjycui** [comment]
> Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

重现 demo 和步骤。

**Comment by benjycui** [comment]
It works fine in demo https://ant.design/components/locale-provider/#components-locale-provider-demo-all

Close now, if you still meet this issue, please re-open and provide re-producible demo and steps, thx.
