### ISSUE TITLE
Table表头分组后使用components属性自定义单元格不生效

### ISSUE THREAD

**Issue by RJM1996** [ant-design/ant-design#48477]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-grrhbe?file=demo.tsx)

### Steps to reproduce

1. 将Table设置表头分组
2. 使用 components 属性自定义单元格

### What is expected?

Table的components属性的body.cell 函数的入参 title 值不为 undefined

### What is actually happening?

Table的components属性的body.cell 函数的入参 title 值为 undefined

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.2.0 |
| System | Mac OS |
| Browser | Microsoft Edge 版本 123.0.2420.65 (正式版本) (arm64) |

<img width="1302" alt="image" src="https://github.com/ant-design/ant-design/assets/33800707/4f40b7a1-9ccb-4985-a501-ecea6f5456a8">

**Comment by zhuba-Ahhh** [comment]
I will try to fix this bug.

**Comment by afc163** [comment]
只有当有省略号出现的时候，才会给 dom 元素增加 title。所以这并不是一个 bug。
