### ISSUE TITLE
ConfigProvider doesn't effect wrapped components built with antd package

### ISSUE THREAD

**Issue by orelHAnyvision** [ant-design/ant-design#48473]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fast-flower-jyh2k9?file=%2Findex.js)
ignore the codesandbox since I cant create storybook over there and build and import it

### Steps to reproduce

1. Create a button component based on antd Button component
2. Build with storybook and have it exported
3. Import the component and wrap it with ConfigProvider in your project
4. change primary color in token to 'red'
5. render both antd original Button component and the one imported - only the original one is red

### What is expected?

Components wrapped with ConfigProvider will inherit all the styles

### What is actually happening?

the styles aren't changing

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18 |
| System | macOS Sonoma 14.3.1 |
| Browser | Chrome |

---
wrapped component:

```
import { Button as ButtonComponent, type ButtonProps } from 'antd'
export type Props = ButtonProps
const Button = (props: Props) => {
  return <ButtonComponent {...props} />
}
export { Button }
```
build with storybook and import in another project

**Comment by 340rahul** [comment]
I am facing a similar issue. @orelHAnyvision were you able to resolve this?
