### ISSUE TITLE
Tree组件的 复选框选中状态能不能提供调用方法进行更改

### ISSUE THREAD

**Issue by LOVECYF** [ant-design/ant-design#4847]
貌似没看到有可以取消tree节点前面复选框的方法。  tree节点前面的复选框我希望是和别的地方联动起来的，别的地方有某些操作，我希望复选框的选中状态可以取消。 现在貌似只有通过手动点击事件才能取消选中状态么？

**Comment by afc163** [comment]
Use `checkedKeys` to controll Tree component.
