### ISSUE TITLE
Popover defaultOpen 失效

### ISSUE THREAD

**Issue by linhf123** [ant-design/ant-design#48483]
### Reproduction link

[https://codepen.io/huifeng-lin/pen/RwOYGRJ?editors=001](https://codepen.io/huifeng-lin/pen/RwOYGRJ?editors=001)

### Steps to reproduce

 直接打开

### What is expected?

卡片展示

### What is actually happening?

卡片未展示

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 16.14.0 |
| System | macos Monterey 12.5 |
| Browser | chrome123.0.6312.123 |

**Comment by yoyo837** [comment]
English title please.
