### ISSUE TITLE
日期时间选择组件，如果传入转换好时区的dayjs对象，理论上应该按照转换的时区渲染，America/New_York时区是没问题的，但是UTC时区有误

### ISSUE THREAD

**Issue by CoCoManYY** [ant-design/ant-design#48485]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jembcu?file=demo.tsx,package.json%3AL1)

### Steps to reproduce

打开页面即可

### What is expected?

预期：传入转换成UTC时区的dayjs后，显示UTC时区的时间

### What is actually happening?

转成了不符合预期的结果

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18.2.0 |
| System | macos 14.2.1 |
| Browser | Chrome123.0.6312.124（正式版本） (arm64) |

**Comment by zombieJ** [comment]
参考一下国际化示例：https://ant-design.antgroup.com/components/config-provider-cn#config-provider-demo-locale

DatePicker 内部格式化时间时会将当前上下文的 locale 提供进去以保持时区一致性：

```tsx
date.locale(locale).format(format);
```

所以仅仅替换日期对象的时区是不够的，请参考例子完整的 extends dayjs 和 ConfigProvider locale。不完整填充下，不论看起来正确与否其实都是不正确的哈~

**Comment by CoCoManYY** [comment]
把locale补充上去也是一样。

https://stackblitz.com/edit/react-jembcu-pmykyp?file=demo.tsx

**Comment by zombieJ** [comment]
你设置的 locale 是 `dayjs.locale('en');`，不是 UTC locale。

**Comment by CoCoManYY** [comment]
感觉UTC是个特例，貌似没有对应的locale，我尝试改成 `dayjs().tz('UTC').locale('en-gb')` 也是一样的问题。 我如果传入 dayjs().utc() 则没问题。

**Comment by CoCoManYY** [comment]
只转换时区，不考虑国际化的话，我应该是不需要手动设置locale的吧？

**Comment by yoyo837** [comment]
dayjs.tz.setDefault('Asia/Shanghai'); ?

**Comment by CoCoManYY** [comment]
> dayjs.tz.setDefault('Asia/Shanghai'); ?

我的场景不能全局设置，需要根据组件局部配置的时区来，一个页面3个datepicker组件，可能时区都不相同
