### ISSUE TITLE
upload 在安卓设备下多选失效，没有触发beforeUpload,没有任何响应

### ISSUE THREAD

**Issue by zshzsh556** [ant-design/ant-design#48491]
### Reproduction link

[https://ant-design.antgroup.com/components/upload-cn](https://ant-design.antgroup.com/components/upload-cn)

### Steps to reproduce

在微信打开upload组件找到多选上传多个文件无法触发上传事件（ios和web正常，安卓自带浏览器也正常）

### What is expected?

能够正常多选上传

### What is actually happening?

可以多选，但是无法触发上传

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | react |
| System | 安卓 |
| Browser | 微信浏览器 |

**Comment by zombieJ** [comment]
微信用的 X5 自研内核，组件侧做不了什么。建议在 `onChange` 里自行调整。
