### ISSUE TITLE
Menu组件，当选项有子菜单时候，该选项不支持触发事件

### ISSUE THREAD

**Issue by bobodeng** [ant-design/ant-design#485]
如题~让我硬生生的把一个菜单拆成两个，很尴尬的说

**Comment by yiminghe** [comment]
不知道是什么问题，提供示例到 https://github.com/react-component/menu

**Comment by bobodeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1780020/11003795/b88487d0-84ef-11e5-9e21-bd6a8db570dc.png)
就是本身“其他课程”的子菜单本来应该在 “项目实战”下面的，但是因为有了子菜单后，主菜单不可点击，导致要换成两个menu在展示，这点不太方便

**Comment by yiminghe** [comment]
菜单目录是不支持的，具体再讨论吧...
