### ISSUE TITLE
Switch doesn't show icon if there is only unCheckedChildren

### ISSUE THREAD

**Issue by wang-yikai** [ant-design/ant-design#48503]
### Reproduction link

[https://codepen.io/NotYeetKai/pen/ExJeOQY?editors=001](https://codepen.io/NotYeetKai/pen/ExJeOQY?editors=001)

### Steps to reproduce

Toggle the Switch and see that the `<CloseOutlined />` is not showing on the Switch component.

### What is expected?

The `<CloseOutlined />` should be shown if the Switch is unchecked.

### What is actually happening?

The `<CloseOutlined />` is not showing when the Switch is unchecked.

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18 |
| System | MacOS |
| Browser | Chrome |

---
The Switch does show `<CloseOutlined />` if `checkedChildren={<CheckOutlined />}` is uncommented.

**Comment by wang-yikai** [comment]
Adding the following styling seems to fix this issue:
```
.ant-switch.ant-switch-small .ant-switch-inner .ant-switch-inner-checked {
  min-height: calc(var(--control-height) / 2);
}

.ant-switch .ant-switch-inner .ant-switch-inner-checked {
  min-height: calc(var(--font-size) * var(--line-height));
}
```

**Comment by wanpan11** [comment]
I will try to fix it
