### ISSUE TITLE
Next.js 14.1.4 fails to build when using antd due to "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by kaviyarasank** [ant-design/ant-design#48512]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fast-flower-jyh2k9?)

### Steps to reproduce

just install antd in next js 14.1.1 

### What is expected?

need to use antd latest version in next js latest version

### What is actually happening?

facing error Next.js 14.1.4 fails to build when using antd due to "SyntaxError: Cannot use import statement outside a module"

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | latest |
| System | all |
| Browser | all |

**Comment by MadCcc** [comment]
Please provide version of antd, and which router did you use in Nextjs.

**Comment by SarahMohamedAbdAlkader** [comment]
I have the same problem with antd version 5.12.5
