### ISSUE TITLE
tabs组件在小分辨率下展示计算有问题

### ISSUE THREAD

**Issue by kylvia** [ant-design/ant-design#48517]
Uploading file_v3_00a1_1567396d-b7ae-4f1c-9f5a-7e7ed719931g.mp4…

### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

1. 将分辨率调整到只能展示出一个tab项，出现滑动下拉菜单
2. 切换菜单项选中'Tab 2'

### What is expected?

下拉菜单出现'Tab 1'和'Tab 3'

### What is actually happening?

此时下拉菜单出现'Tab 2'和'Tab 3'

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome  111.0.5563.64 (arm64) |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/46836
