### ISSUE TITLE
How do I reset all the table filters without re-rendering the whole table

### ISSUE THREAD

**Issue by choikh0423** [ant-design/ant-design#48523]
### Reproduction link
I apologize for the rather hastily crafted issue!

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fast-flower-jyh2k9?file=%2Findex.js)

### Steps to reproduce

N/A

### What is expected?

I want to reset all the table filters with a single button without having to re-render to whole table.

### What is actually happening?

I am not able to reset all the table column filters except in the way of re-rendering the whole table.

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | react |
| System | OS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
For the filter reset, the row list will be re-render which is what React render logic do. If you want to keep that, maybe you can customize the filter and patch hidden `rowClassName` on the `<tr />` instead of ReactNode remove or add and use `shouldCellUpdate=false` to skip cell re-render.

**Comment by choikh0423** [comment]
So, in other words, is it not possible to create a "reset all filters" button unless I keep a separate state on my filters and customize it?
