### ISSUE TITLE
onPopScroll function not working for TreeSelect

### ISSUE THREAD

**Issue by SauInu2002** [ant-design/ant-design#48528]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-w8hflc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv4xnb3200062v6iswwd3ixn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv4xnb3200022v6i0ez9qvlt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv4xnb3200032v6iszd3a1gl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv4xnb3200052v6i920zu3sk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv4xnb3200022v6i0ez9qvlt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv4xnb3200012v6i31zmobr4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv4xnb3200022v6i0ez9qvlt%2522%252C%2522activeTabId%2522%253A%2522clv4xnb3200012v6i31zmobr4%2522%257D%252C%2522clv4xnb3200052v6i920zu3sk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv4xnb3200042v6ijpn2fwq9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv4xnb3200052v6i920zu3sk%2522%252C%2522activeTabId%2522%253A%2522clv4xnb3200042v6ijpn2fwq9%2522%257D%252C%2522clv4xnb3200032v6iszd3a1gl%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clv4xnb3200032v6iszd3a1gl%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Just open the treeselect , expand the first node and scroll to bottom.

### What is expected?

The onPopupScroll or onSroll functions should be fired.

### What is actually happening?

The onPopupScroll or onSroll functions are not being fired.

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | Ubuntu 22.04.4 LTS |
| Browser | Chrome 124.0.6367.60 |

---
If possible please provide a indepth documentation or code implementation

**Comment by wanpan11** [comment]
Currently, TreeSelect does not support onPopScroll events. Let me try adding it 🤖

**Comment by SauInu2002** [comment]
@wanpan11 Thanks for your support and quick response. Any update regarding the PR merge ?

**Comment by wanpan11** [comment]
Wait for the next version to be released

**Comment by SauInu2002** [comment]
@wanpan11 and @li-jia-nan thanks for the help. By When can i except for a newer version to roll out ?

**Comment by li-jia-nan** [comment]
> @wanpan11 and @li-jia-nan thanks for the help. By When can i except for a newer version to roll out ?

next week

**Comment by SauInu2002** [comment]
@li-jia-nan the update should happen at the end of month as per given in changelog.
