### ISSUE TITLE
在使用Cascader省市联动的时候有没有提供对应的省市区的数据源

### ISSUE THREAD

**Issue by zhanfenghai** [ant-design/ant-design#4852]
如题,不知道有没有提供类似的数据源,

**Comment by yesmeck** [comment]
可以用 https://github.com/cn/GB2260

**Comment by zhanfenghai** [comment]
@yesmeck 我是需要根据这个数据来封装成符合Cascader要求的数据格式嘛

**Comment by yesmeck** [comment]
是的，你要自己处理数据。

**Comment by zhanfenghai** [comment]
@yesmeck 那这样的话我是觉得可以提供一个已封装好的数据源的，毕竟省市这块还是需要经常用到的，既然已经提供了一个省市联动的组件，那么提供数据源个人觉得也是很有必要的，也有可能是个人比较懒的原因造成

**Comment by benjycui** [comment]
`antd` 组件不会封装数据也不会增加数据请求的能力。

@zhanfenghai 自行封装，然后可以提交到 [`awesome-ant-design`](https://github.com/websemantics/awesome-ant-design)

**Comment by afc163** [comment]
内部基于 [china-division](http://npmjs.com/china-division) 封装过一个：

https://gist.github.com/afc163/7582f35654fd03d5be7009444345ea17

**Comment by qq645381995** [comment]
@afc163   太棒了

**Comment by lz101281** [comment]
我写好了一个 https://github.com/lz101281/Select-Region-China

**Comment by heerey525** [comment]
写了一份现成的数据
https://github.com/heerey525/antdCascaderDate/blob/master/src/cities.js
