### ISSUE TITLE
Table-sticky设置与否会影响列宽

### ISSUE THREAD

**Issue by Lpbzzz** [ant-design/ant-design#48539]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-pobqae?file=demo.tsx)

### Steps to reproduce

在Table中设置或取消sticky

### What is expected?

在sticky情况下，表头内容可以撑开列宽

### What is actually happening?

sticky时，表头会折行，并不会撑开列

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 任意 |
| System | macos |
| Browser | chrome@latest |

**Comment by afc163** [comment]
Check `tableLayout`: https://ant.design/components/table-cn#table

**Comment by Lpbzzz** [comment]
> Check `tableLayout`: https://ant.design/components/table-cn#table

可能是有bug吧，在sticky的时候无法设置 tableLayout='auto'

**Comment by afc163** [comment]
因为开启 sticky 后是上下两个 table 实现，为了列之间能对齐，强制 tableLayout 为 fixed。
