### ISSUE TITLE
Range Picker date select with showTime option is broken.

### ISSUE THREAD

**Issue by Chingachcook** [ant-design/ant-design#48541]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/showtime-antd-6r783y?file=/src/App.tsx:2,30-2,34)

### Steps to reproduce

1. Navigate to the page where the range picker component is located. - https://shorturl.at/kr378
2. Observe the range picker component without the showTime property enabled.
3. Attempt to select a date range by clicking once on the start date and once on the end date. Note that the selection process requires only two clicks to select both dates.
4. Enable the showTime property on the range picker component.
5. Repeat step 3 by attempting to select a date range by clicking once on the start date and once on the end date.
6. Observe that the selection process now requires two clicks on each date to select both the date and the time, resulting in a total of four clicks to complete the selection of the date range.

Currently when the user select date by clicking once, UI doesn't show correctly that date preselected until time is picked.

### What is expected?

Single click on range picker dates working with and without showTime property.

### What is actually happening?

Double-click with the showTime property on dates only select dates.

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | react |
| System | mac os, ubuntu, windows |
| Browser | chrome, safari, arc |

**Comment by zombieJ** [comment]
It's by design. `Year/Month/Date` Picker could be certain the selection finish when click the cell but the `DateTime` date click is not the end.
If you don't want user select time but only show the time in format, just use `format` instead:

https://stackblitz.com/edit/react-t867ik?file=demo.tsx

**Comment by ferretwithaberet** [comment]
Can this behavior be disabled somehow? I want the user to first select the start time then start date using 1 click, and then the end time and end date using 1 click.
