### ISSUE TITLE
The Carousel Component will trigger the click event of the child element when the slide ends on the PC side.

### ISSUE THREAD

**Issue by qs1170648307** [ant-design/ant-design#48548]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-475rsh?file=%2Findex.js%3A17%2C60)

### Steps to reproduce

Slide the Carousel a short distance and release the mouse

### What is expected?

When the sliding ends, the onClick event is prohibited from being triggered.

### What is actually happening?

When the slide ends, the onClick event is triggered

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by ygag-sanooj** [comment]
This works for me
`  
  const mouseDownCoords = (e) => {
    window.checkForDrag = e.clientX;
  };
  
const handleClick = (e) => {
    const mouseUp = e.clientX;
    if (
      mouseUp < window.checkForDrag + 5 &&
      mouseUp > window.checkForDrag - 5
    ) {
       // your onclick logic
    }
  };
  
  <div onMouseDown={(e) => mouseDownCoords(e)} >
      <Carousel draggable={true} > 
            <img  onClick={(e) => handleClick(e)} /> 
      </Carousel>
  </div>
  `
