### ISSUE TITLE
Add Button and Select group

### ISSUE THREAD

**Issue by TheMineWay** [ant-design/ant-design#48546]
### What problem does this feature solve?

It would be nice to have a Select.Group just like we have a Button.Group

### What does the proposed API look like?

We can add a <Select.Group/> that accepts Select components as child. Similar as Button.Group so development is consistent.

**Comment by TheMineWay** [comment]
This can be a **good first issue**.

**Comment by afc163** [comment]
Try Space.Compact https://ant.design/components/space#space-demo-compact

**Comment by zombieJ** [comment]
Button.Group is deprecated. Use `Space.Compact` directly. It can combine anything:

https://ant.design/components/space#space-demo-compact
