### ISSUE TITLE
Tree 组件的 filterTreeNode 可否支持隐藏不匹配的节点

### ISSUE THREAD

**Issue by wmzy** [ant-design/ant-design#4854]
我使用 filterTreeNode 属性做 tree节点的搜索功能，但是数据量比较大，希望可以隐藏不匹配的节点，目前通过覆盖样式达到了这个效果，但是升级antd可能带来隐患，不知道官方是否考虑支持这一特性？

**Comment by RaoHai** [comment]
仿照这个 DEMO ： https://ant.design/components/tree-cn/#components-tree-demo-search

不匹配的 TreeNode 不渲染，应该可以满足你的要求。

**Comment by wmzy** [comment]
多谢，我试试吧。但是感觉性能会比用css差好多。
