### ISSUE TITLE
table demo示例中远程加载数据，第一次会出现两次请求的bug

### ISSUE THREAD

**Issue by fakerlogic** [ant-design/ant-design#48550]
### Reproduction link

[https://ant.design/components/table-cn#components-table-demo-ajax](https://ant.design/components/table-cn#components-table-demo-ajax)

### Steps to reproduce

第一次进入页面会请求两次

### What is expected?

请求一次

### What is actually happening?

请求了两次

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | mac os 14.4.1  |
| Browser | chrome 123.0.6312.124 |

---
第一次请求完了，会设置tableParams，里面有个total参数肯定变了，导致在useEffect中又请求了一次。改一下依赖项就好了

**Comment by afc163** [comment]
最好把这个例子改成用 useQuery 或 useSWR 实现。
