### ISSUE TITLE
Tabs do not work properly if the tab key contains a backslash

### ISSUE THREAD

**Issue by CherryPetale** [ant-design/ant-design#48554]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sg58xw)

### Steps to reproduce

Include backslash in Tabs key.
See the reproduction sandbox.

### What is expected?

- The more and add buttons should be visible from the beginning.
- When a tab is clicked while scrolled, the scroll position is not reset and the tab becomes active.

### What is actually happening?

- More and add buttons do not visible when the scroll position is initial.
- Scroll position is reset and no longer active when tab is clicked while scrolled.

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | WebView2 (Browser in Tauri) |

---
This occurred when the file path was set to key. If it is not set, there is no problem, but the behavior is unnatural.

**Comment by MadCcc** [comment]
'\\' will be esacped in html, please do not use it.
