### ISSUE TITLE
Form中，Checkbox.Group options支持虚拟列表

### ISSUE THREAD

**Issue by magickeyyy** [ant-design/ant-design#48551]
### What problem does this feature solve?

用react-virtualized优化了大量选项显示卡顿问题。但是，只要已选中项滚过之后，再选中任一项，值被重置成最新一项，之前选中的被忽略了。

### What does the proposed API look like?

像Select一样支持虚拟列表

**Comment by afc163** [comment]
为啥会有这么多选项。。。

**Comment by magickeyyy** [comment]
现在选项已经12000+了会持续增加。用select麻烦的事选项有好几个字段需要展示，不醒目。现在是不用表单，单独管理这个配置

**Comment by afc163** [comment]
我觉得你得想想交互上的解法，12000+ 个 checkbox 用户也没法看。

**Comment by magickeyyy** [comment]
> 我觉得你得想想交互上的解法，12000+ 个 checkbox 用户也没法看。

支持搜索，结果往前排，滚动到最前面；最新加的数据排前面。是管理端项目，目前单独配置也能满足需求。

**Comment by linxianxi** [comment]
设计不合理，自己做吧，又不难，给你弄了个。https://stackblitz.com/edit/react-xmkaga?file=demo.tsx
