### ISSUE TITLE
Paragraph copyable支持修改tabindex

### ISSUE THREAD

**Issue by Veveue** [ant-design/ant-design#48557]
### What problem does this feature solve?

表单中tab 切换  复制按钮不需要获取焦点

### What does the proposed API look like?

```js
<Paragraph
      copyable={{
        icon: [<SmileOutlined key="copy-icon" />, <SmileFilled key="copied-icon" />],
        tooltips: ['click here', 'you clicked!!'],
        tabIndex: -1
      }}
    >
```

**Comment by Veveue** [comment]
<img width="433" alt="image" src="https://github.com/ant-design/ant-design/assets/11311421/b7e060c1-0604-4af4-a3b6-470bea3f6ec6">

**Comment by nova1751** [comment]
I will try to achieve this feature.
