### ISSUE TITLE
antd@5.16.3 is an empty package in npmjs

### ISSUE THREAD

**Issue by PeterPanZH** [ant-design/ant-design#48568]
### Reproduction link

[https://www.npmjs.com/package/antd/v/5.16.3?activeTab=code](https://www.npmjs.com/package/antd/v/5.16.3?activeTab=code)

### Steps to reproduce

N/A

### What is expected?

N/A

### What is actually happening?

N/A

| Environment | Info |
| --- | --- |
| antd | 5.16.3 |
| React | * |
| System | * |
| Browser | * |

**Comment by fz6m** [comment]
cc @xrkffgg

**Comment by Ladvace** [comment]
same problem here:

`Cannot find module 'antd' or its corresponding type declarations.ts(2307)`

**Comment by zombieJ** [comment]
I've update latest tag back to `5.16.2`. Still dig why publish script generate empty files. Sorry for this.

**Comment by crazyair** [comment]
> cc @xrkffgg
> 
> 建议下次加一个发布前检验吧，看看有没有产物内容。

最近在调发布功能，调好了以后就不会有问题了

**Comment by afc163** [comment]
发布前校验有的：https://github.com/ant-design/ant-design/blob/c321492eeb1bea9b8a31d2599c2eade01b678027/scripts/pre-publish.ts#L273 不知道为啥没发挥作用。

**Comment by baiwusanyu-c** [comment]
先降级🤣
