### ISSUE TITLE
Tooltip 嵌套 Select使用 严格模式下报错：Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by zhuba-Ahhh** [ant-design/ant-design#48565]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jg4mye?file=index.tsx,demo.tsx)

### Steps to reproduce

https://stackblitz.com/edit/react-jg4mye?file=index.tsx,demo.tsx

### What is expected?

不报错

### What is actually happening?

报错：Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18.2.0 |
| System | Mac Pro M2 |
| Browser | Chrome |

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/48709

**Comment by codetown** [comment]
同问

**Comment by afc163** [comment]
Fixed in antd@5.17.3: https://github.com/ant-design/ant-design/pull/48958

https://stackblitz.com/edit/react-jg4mye-p9dbu4?file=index.tsx,demo.tsx
