### ISSUE TITLE
menu组件主题色的itemActiveBg配置不生效

### ISSUE THREAD

**Issue by scyan** [ant-design/ant-design#48576]
### Reproduction link

[https://ant-design.antgroup.com/components/menu-cn](https://ant-design.antgroup.com/components/menu-cn)

### Steps to reproduce

配置itemActiveBg不生效

### What is expected?

生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 5.16.3 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by GeorgeHcc** [comment]
你可能是想改变选中态的itemBg，用这个`itemSelectedBg`token试试
