### ISSUE TITLE
Select label render 支持自定义用户自己处理迭代

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#48579]
### What problem does this feature solve?

我理解在多选模式下tagRender是可迭代的，但是labelRender应该是返回当前选择的数据用户手动去处理迭代的，但是现在两者都是处理迭代的情况，没办法做到自己处理迭代的情况，

### What does the proposed API look like?

(props: Option[]) => ReactNode。因为有些场景可能要在外层包裹一个自定义的容器

**Comment by zombieJ** [comment]
`迭代` 这个指的是什么？不好意思，我不太明白说的是啥。。。

**Comment by hans000** [comment]
抱歉，我意思是labelRender的api设计应该和maxTagPlaceholder类似才对吧（多选模式下），label应该指整体，而不是单个tag，现在提供的labelRender 相当于map的迭代器 

`
values.map(value => labelRender(value ))
`

我考虑先使用maxTagCount=0 然后使用maxTagPlaceholder来实现吧

**Comment by afc163** [comment]
What does the proposed API look like?

完整的 API 描述一下。

**Comment by hans000** [comment]
> What does the proposed API look like?
> 
> 完整的 API 描述一下。

后来我想到maxTagCount + maxTagPlaceholder 也能实现，就先这样吧

**Comment by hans000** [comment]
但其实还有一些别的问题是
我感觉 labelRender的api应该是 

labelRender -> `(option: OptionType | OptionType[], defaultDom: ReactElement| ReactElement[]) => ReactElement`

然后tagRender应该把action remove 做参数也返回，不然需要自己去做受控，实际使用有点麻烦

tagRender -> `(props: CustomTagProps, index, remove) => ReactElement`

**Comment by linxianxi** [comment]
tagRender 是有返回 onClose 属性的，可以直接用

**Comment by hans000** [comment]
> tagRender 是有返回 onClose 属性的，可以直接用

大哥，onXXX 都是事件回调

**Comment by linxianxi** [comment]
> > tagRender 是有返回 onClose 属性的，可以直接用
> 
> 大哥，onXXX 都是事件回调

```
tagRender={({ onClose }) =>  <Tag onClose={onClose} />}
```

**Comment by MadCcc** [comment]
看起来都是可以通过代码实现的功能，没其他问题先关闭了

**Comment by hans000** [comment]
> 看起来都是可以通过代码实现的功能，没其他问题先关闭了

不是啊，这API是咋设计的，名字起的有问题，close 或者 remove不就好了 ,onXXX是几个意思
<img width="728" alt="image" src="https://github.com/ant-design/ant-design/assets/26105827/38d564d7-0c22-41bf-8666-5143dd046cc9">
