### ISSUE TITLE
dropdown 位置计算错误

### ISSUE THREAD

**Issue by yyjazsf** [ant-design/ant-design#4857]
#### Environment(required)

- antd version: 2.7.1
- OS and its version: 10.12.2 (16C67)
- Browser and its version: chrome Version 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
open [this](https://ant.design/components/dropdown-cn/)

如下图，足够宽度的情况下点击 Click me , 然后缩小浏览器宽度
<img width="1006" alt="111 2x" src="https://cloud.githubusercontent.com/assets/2438224/22912926/f8dca9e4-f2a2-11e6-8f54-30b825e85c26.png">
<img width="857" alt="222 2x" src="https://cloud.githubusercontent.com/assets/2438224/22912927/fbb28fa8-f2a2-11e6-8956-7cff5b359617.png">

#### What do you expected?

正确计算下拉框位置，获取dom，计算在document的(x,y)？

#### What happen?

在响应式的网页下，下拉框位置计算错误

#### Re-producible online demo

同上 open [this](https://ant.design/components/dropdown-cn/)

**Comment by benjycui** [comment]
所有依赖于 `rc-trigger` 的组件都有这个问题，虽然 `rc-trigger` 已经启用了 `rc-align` 的 `monitorWindowResize` https://github.com/react-component/trigger/search?utf8=%E2%9C%93&q=monitorWindowResize

**Comment by yyjazsf** [comment]
我看到是给到了```rc-align```了，所以是[这里](https://github.com/react-component/align/blob/master/src/Align.jsx#L94)的问题？

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by benjycui** [comment]
This behavior is because `dom-align` will make sure that [popup element will not out of viewport](https://github.com/yiminghe/dom-align/blob/2cc0a91fda10ccf760d4e484573ae8c5cab1bd33/src/index.js#L154).

**Comment by benjycui** [comment]
And I am not going to change de behavior of `dom-align`, for this behavior is `dom-align`'s target.

Current behavior of Dropdown and Select and so on, is not perfect, but I think it is good enough, for we seldom resize window while browsing a website.

**Comment by benjycui** [comment]
Though this issue is an edge case, I think I find a way to fix it.

Trace: https://github.com/yiminghe/dom-align/pull/11
