### ISSUE TITLE
Tooltip not working on mobile devices

### ISSUE THREAD

**Issue by ali-iftikhar007** [ant-design/ant-design#48578]
### Reproduction link

[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce

When we click on the info button, tooltip does not open

### What is expected?

Tooltip should open when we click on the info button on mobile device

### What is actually happening?

Tooltip is not opening

| Environment | Info |
| --- | --- |
| antd | 4.24.6 |
| React | 18 |
| System | Android, iOS |
| Browser | Chrome, Safari and others |

**Comment by aminhdev** [comment]
I have the same problem
