### ISSUE TITLE
Tree树形控件拖拽效果抖动

### ISSUE THREAD

**Issue by alanwei0** [ant-design/ant-design#4858]
官网上的拖动示例，在拖拽过程中，UI会出现轻微抖动的情况，体验不是很好

**Comment by yesmeck** [comment]
浏览器版本？

**Comment by alanwei0** [comment]
mac 10.12
chrome 56

我看了一下效果，是因为在拖拽文件夹的时候，在target文件的上面或者下面会出现蓝色的提示线，这个会改变整个容器的高度，所以会一抖一抖的

**Comment by yesmeck** [comment]
这是正常的反馈。

**Comment by alanwei0** [comment]
提示线是正常的反馈，但是整个容器上下抖动也是正常反馈吗

**Comment by yesmeck** [comment]
@afc163 https://github.com/ant-design/ant-design/blob/597e020a45edef1692bd2ad04be14e5415f2e9fc/components/tree/style/index.less#L63

**Comment by afc163** [comment]
transition 导致了抖动么？

**Comment by RaoHai** [comment]
https://github.com/ant-design/ant-design/blob/597e020a45edef1692bd2ad04be14e5415f2e9fc/components/tree/style/index.less#L34
应该是此处添加了一个 border-top 导致。

**Comment by RaoHai** [comment]
默认上下 border 都加个 transparent 的 2px border 就不闪了。

**Comment by afc163** [comment]
会不会影响整体高度？

或者这个 `border-top: 2px @primary-color solid;` 改成不占空间的 box-shadow ？

**Comment by RaoHai** [comment]
我 PR 一个。

**Comment by RaoHai** [comment]
不过这样改了之后有可能比之前难拖一些。因为其实 2px 的 border 相当于变相增加了接受拖放到两个元素之间的区域的高度。

**Comment by benjycui** [comment]
> 默认上下 border 都加个 transparent 的 2px border 就不闪了。

其实我还是觉得这个方案比较好，同时把 https://github.com/ant-design/ant-design/blob/597e020a45edef1692bd2ad04be14e5415f2e9fc/components/tree/style/index.less#L14 的上下 padding 减小就好。

主要是觉得 `box-shadow` 的写法略费解。

![image](https://cloud.githubusercontent.com/assets/3580607/22963935/dcb40534-f390-11e6-8b56-c92726e35d4f.png)
