### ISSUE TITLE
want to placeholder to be showed permanent , don't want to show selected items in treeselect bar

### ISSUE THREAD

**Issue by jaydeep-YCS** [ant-design/ant-design#48592]
### Reproduction link

[https://ant.design/~demos/tree-select-demo-checkable](https://ant.design/~demos/tree-select-demo-checkable)

### Steps to reproduce

in multi select just click on 2 or more item and see search bar

### What is expected?

need placeholder or static key to show , nor selected items

### What is actually happening?

for now it is showing selected items

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18 |
| System | Ubuntu 20 |
| Browser | Chrome |

**Comment by MadCcc** [comment]
It's not a normal behavior, we won't accept it.

**Comment by zombieJ** [comment]
As @MadCcc  said, it's not common requirement.
You can consider to HOC a Select component (which contains 2 Select): one is show the Input part and another is to handle the selection items.
