### ISSUE TITLE
Datepick.RangePicker picker="month", set disabledDate, can't select first month to last month

### ISSUE THREAD

**Issue by qiaoyuwen** [ant-design/ant-design#48590]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

please look the vcr

### What is expected?

can select first month to last month

### What is actually happening?

can't select first month to last month

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18.2.0 |
| System | macOS 13.4 |
| Browser | Microsoft Edge 版本 114.0.1823.82 |

**Comment by qiaoyuwen** [comment]
https://github.com/ant-design/ant-design/assets/8097860/38c26fe5-34d9-4967-94bb-638515f5b60f

**Comment by zombieJ** [comment]
月份不要用 diff 对比，会被四舍五入裁剪导致被禁用掉：

https://stackblitz.com/edit/react-88zmdq?file=demo.tsx
