### ISSUE TITLE
Select组件中ant-select-show-search这个class是否多余?

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#4859]
[官网](https://ant.design/components/select-cn/)中关于Select组件的示例有一个用到了`ant-select-show-search`这个class（console里面`$('ant-select-show-search')`可以直接找到，只有一个），而且在Select组件的index.tsx中也有相关判断`[`${prefixCls}-show-search`]: showSearch`。

但是，我搜索了下，没有对应的css与之对应，也没有其他逻辑代码牵扯到这里，请教下这个的用意是什么?

**Comment by afc163** [comment]
目测应该是多余的，之前的修改遗留下来的。

**Comment by NE-SmallTown** [comment]
Translate the issue to English,hope is's helpful to the community.
