### ISSUE TITLE
父元素为position:fixed，的Select组件，Popover组件，在页面滚动后位置错位。

### ISSUE THREAD

**Issue by inkinworld** [ant-design/ant-design#4860]
#### Environment(required)

- antd version: 2.7.1
- OS and its version:mac OS 10.12.2
- Browser and its version:chrome 56.0.2924.87 (64-bit)

####  What did you do? Please provide steps to re-produce your problem.

将页面 heder 固定，heder 中使用 Select， 当Select展开时，滚动页面，展开的菜单跟随滚动，发生错位。

我看了许多的实践，几乎没有使用fiexd的案例

https://tiyan.alipay.com/experience/index.htm#/docEditor?

这个例子用户头像hover后滚动存在类似问题

#### What do you expected?

Select展开的菜单不跟随页面滚动，保持静止

#### 

antd的实现是在 body 中插入待显示的元素，而后计算在<body>中的相对位置，因此页面滚动后，其position:fixed的父元素相对 body 位置改变，二者发生错位。

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#Select-props

看 `getPopupContainer`。

**Comment by inkinworld** [comment]
thx😄
