### ISSUE TITLE
Carousel 设置了initialSlide后的位置问题

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#48607]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-zbz3q6?file=demo.tsx,index.css)

### Steps to reproduce

同样的代码，5.15.4的Carousel可以居中显示
最新的5.16.4就是偏右显示了，
看了下更新记录，5.16.0版本是有修复Carousel组件，有没有方法可以居中显示Carousel内部的元素

antd 5.16.4
https://stackblitz.com/edit/react-a6l2lg?file=index.css,demo.tsx

antd 5.15.4
https://stackblitz.com/edit/react-zbz3q6?file=demo.tsx,index.css

### What is expected?

期望能够像5.15.4一样，居中显示

### What is actually happening?

最新的5.16.4偏右显示

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | react 18 |
| System | window 10 |
| Browser | Chrome 123.0.6312.86 |

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/issues/1874

**Comment by wanpan11** [comment]
5.16.4 里去掉自定义css就好了
![image](https://github.com/ant-design/ant-design/assets/38714194/f3de00d3-f72b-41f9-afee-95155923ec9f)

**Comment by wanpan11** [comment]
> 感觉是符合预期的？

![image](https://github.com/ant-design/ant-design/assets/38714194/d126b25e-2b17-4500-af0c-9e09eaad28c4)

![image](https://github.com/ant-design/ant-design/assets/38714194/393d329e-9b96-4a90-a218-cff7896c2a56)

好像是 unslick 逻辑变了， 目前的因该是符合预期的🧐

**Comment by afc163** [comment]
确实是符合预期的，https://github.com/akiran/react-slick/pull/2330 修复了 https://github.com/akiran/react-slick/issues/1874 提到的问题。楼主把自定义样式去掉即可。
