### ISSUE TITLE
DatePicker在上下空间都不够的情况下无法展现全部

### ISSUE THREAD

**Issue by Meetacoo** [ant-design/ant-design#48603]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/issue-datepicker-knlvw5?file=%2Findex.js%3A13%2C22)

### Steps to reproduce

父容器为fixed，DatePicker为Popover的content，Popover在父容器内，此时hover popover，点击DatePicker，即可复现

### What is expected?

展示完整的DatePicker，至少DatePicker内区域可以支持滚动以查看、操作

### What is actually happening?

DatePicker浮框展示不完整，总有上或下半部分被遮住，无法操作

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 5.16.1 |
| System | windows |
| Browser | Google Chrome 124.0.6367.61（正式版本） （64 位） |

**Comment by zombieJ** [comment]
截个图看看？这里看可以完全展示：
<img width="608" alt="截屏2024-04-24 11 07 55" src="https://github.com/ant-design/ant-design/assets/5378891/080f24c4-28af-460a-9bb1-3dfa44811ebb">

**Comment by Meetacoo** [comment]
> 截个图看看？这里看可以完全展示： <img alt="截屏2024-04-24 11 07 55" width="608" src="https://private-user-images.githubusercontent.com/5378891/325062943-080f24c4-28af-460a-9bb1-3dfa44811ebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mjg1MzYsIm5iZiI6MTcxMzkyODIzNiwicGF0aCI6Ii81Mzc4ODkxLzMyNTA2Mjk0My0wODBmMjRjNC0yOGFmLTQ2MGEtOWJiMS0zZGZhNDQ4MTFlYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDMxMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTg0NjRiMDQ2OGFjOWM0NGYwZDhmMmY1YzE0NmFkMTQzNjFiMmM0ZTQ0NjE4YmY4ZjQ5NWNjODYyOGYxOGUzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.19Owtp2KecyTiv834X4xb4OgRcisdcKcdyt6AHgAL24">

![image](https://github.com/ant-design/ant-design/assets/37367461/47898b8b-2ace-4b9e-9dbf-d27c01f56384)
可以把屏幕变成小屏试试，屏幕的高短一些

**Comment by zombieJ** [comment]
想要什么样的效果呢，推上去把输入框遮住这种？

**Comment by Meetacoo** [comment]
> 想要什么样的效果呢，推上去把输入框遮住这种？

现在DatePicker的操作按钮有一部分会被遮挡住看不到，可以看到整个DatePicker的浮框是最好的，如果浮框高度不够的话，内容区域在浮框内滚动也可以

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/48547
