### ISSUE TITLE
每行有200 列，但是没有触发横向虚拟滚动，使用的是官网demo

### ISSUE THREAD

**Issue by LeeeeeeM** [ant-design/ant-design#48606]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-m6azv9?file=demo.tsx)

### Steps to reproduce

官网的demo，横向虚拟滚动

### What is expected?

触发虚拟滚动

### What is actually happening?

未触发

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18.2 |
| System | macos |
| Browser | chrome |

**Comment by yoyo837** [comment]
列这么多本身设计就有问题。

**Comment by zombieJ** [comment]
设计时认为 Column 太多不太合理，所以实现上只支持 Row 的虚拟滚动。

**Comment by LeeeeeeM** [comment]
> 列这么多本身设计就有问题。

5.x版本的行列虚拟滚动其实是没有发布，而是WIP状态对吗？

**Comment by LeeeeeeM** [comment]
> 设计时认为 Column 太多不太合理，所以实现上只支持 Row 的虚拟滚动。

https://ant-design.antgroup.com/docs/blog/virtual-table-cn

也就是说这个功能其实还是基于垂直方向上的虚拟滚动对吗？

**Comment by yoyo837** [comment]
压根没做水平的，非WIP 。

**Comment by LeeeeeeM** [comment]
> 压根没做水平的，非WIP 。

OMG

**Comment by LeeeeeeM** [comment]
问题可以关闭了

**Comment by zombieJ** [comment]
嗯嗯。如果要做大数据的话，可以考虑直接使用 react window 来实现 DataGrid。
