### ISSUE TITLE
form出现校验提示时，会轻微跳动一下

### ISSUE THREAD

**Issue by spiroo** [ant-design/ant-design#4861]
- antd version:  2.7.1
- browser: chrome 版本 55.0.2883.87 m

form表单中，添加FormItem添加label和labelCol属性后，出现校验提示时，会跳动一下，如：
<FormItem labelCol={{ span: 4 }} wrapperCol={{ span: 20 }} label="账号" hasFeedback>

正常情况下（即未出现校验提示时），formItem的height是35px，margin-bottom是24px
出现校验提示时，formItem的height是53px，margin-bottom是3px

以上

**Comment by kakera** [comment]
今天也发现了这个问题，原因可能是出现校验提示时，
附加的 `.ant-form-item-with-help` 中有写死的 `margin-bottom: -7px` 导致的。

目前我的解决办法是

1. 设置  `.ant-form-item-with-help` 的 `margin-bottom` 与 `.ant-form-item` 的值一样
2. 设置 `.ant-form-explain` 的 `position` 为 `absolute` 进行自由定位

**Comment by benjycui** [comment]
Mac 下，Chrome Firefox Safari 都没问题啊，麻烦提供重现步骤。

**Comment by spiroo** [comment]
@kakera 我的方法是
:global(.ant-form-item-with-help){
  margin-bottom: 6px;
}

**Comment by spiroo** [comment]
@benjycui 
我是在windows下，Mac下没有尝试。
直接把官方的代码（https://ant.design/components/form-cn/#components-form-demo-register）放到dva中，就会出现。

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by benjycui** [comment]
@spiroo  I tried to visit the demo you gave with Chrome@56 on Windows, it works fine. Could you try to capture GIF to show the problem?

@kakera could you provide your OS and Browser version?

**Comment by spiroo** [comment]
@benjycui 
demo：http://licensekey.honghe-tech.com/test
随意输入用户名，然后删掉，出现校验时，就会跳一下
![image](https://cloud.githubusercontent.com/assets/7858201/23047922/b7388cae-f4ed-11e6-9821-4071faa11939.png)

**Comment by benjycui** [comment]
@spiroo but I cannot re-produce it with https://ant.design/components/form/#components-form-demo-register

Please provide a re-producible demo to make sure that it's antd's problem: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by inev** [comment]
I'm not sure if this is the same problem but using Google Translate I think it is:

The error message has a negative margin and it not appearing correctly on forms when the bottom margin is changed. More specifically, when I change to ` @form-item-margin-bottom: '11px'` causes `ant-form-item-with-help` to become `-10px`.

**Comment by benjycui** [comment]
@inev Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

Thanks.

**Comment by benjycui** [comment]
Close now, if you can provide re-producible demo, just re-open.
