### ISSUE TITLE
Select popup placement issue when used in multiple scrollable surface

### ISSUE THREAD

**Issue by ArthurKnoep** [ant-design/ant-design#48613]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-7xg2gh)

### Steps to reproduce

- Create one div scrollable
- Inside this div, create another div scrollable
- Inside this div place a Select with `getPopupContainer` set to `(t) => t.parentElement`

### What is expected?

I expect the popup of the Select to be placed correctly according to the right scrollable surface, without placement lag when scrolling into the view

### What is actually happening?

The popup only consider the closest scrollable surface from the getPopupContainer props into calculation, moving the popup container attachment higher in the DOM or let to the default `document.body` cause placement lag

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.2.0 |
| System | Linux / Ubuntu 22.04 |
| Browser | Chrome 124.0.6367.60 |

---
I'm using the Antd Select inside a large table, this table is horizontally scrollable (as it has a lots of column). The vertical scroll is auto managed. This table is placed inside a scrollable surface.
I noticed that when there was a single row in the table (therefore not much vertical space), the popup of the select was miss-aligned with the select static input and scrolling away was not causing a top/bottom flip as it should do.

I know that by using `getPopupContainer={() => <scrollable surface ref>}` the popup is correctly placed and flip top/bottom when hitting borders, but it cause another issue where the popup does not follow the input when scrolling and is recalculated using javascript (giving a lag feeling)

How can I have the popup correctly placed and not lagging when we scroll anywhere in the view ?

**Comment by zombieJ** [comment]
The popup logic is to show as much as possible. So if your container not enough for popup to show, popup will shift its position to try to be seen more in the cut override container.

In most case, it's better to not to set `getPopupContainer` and just let it render in `document.body`. Only when you want to limit it, move to `parentElement`.

The popup will listen scroll event for all the parent, so it will re-align when scrolling. But yes, it will delay since scroll is an UIEvent which will not promise sync up to date.

**Comment by ArthurKnoep** [comment]
> I guess the workaround could be not to use `getPopupContainer` & add listener when the scroll event fired, close the popup instead.

Well, that's not ideal from a UX standpoint but I could see that work.

Thanks for the answer

**Comment by zombieJ** [comment]
Update. For check the related doc about `scroll` event with sync update, currently we can do nothing on the js side since browser does skip some `scroll` event trigger dynamic for perf saving.

Close and sorry for this.
