### ISSUE TITLE
select mode 为tag 的时候 每个tag 的关闭按钮事件在哪 

### ISSUE THREAD

**Issue by TryChai** [ant-design/ant-design#48626]
### What problem does this feature solve?

我的需求是这样的 我是点击select 弹出modal，然后通过设置value 显示 ，但是我需要单独点击关闭的时候 去操作value 但是我没有找到 任何事件 这个事件不能暴露出来吗？

### What does the proposed API look like?

尽量多暴露一些 接口 不要藏着掖着 最好能把大部分的事件都给开发者  自由度越高越react

**Comment by zombieJ** [comment]
可以看一下 HOC 的概念，都可以聚合出来的哈~

```tsx
const MySelect = ({ value, onChange, onTagRemove, ...props }) => {
  const onInternalChange = (nextValue) => {
    onTagRemove(value.filter(val => !nextValue.includes(val)));
  };
  return <Select {...props} onChange={onInternalChange} value={value} />;
};
```
