### ISSUE TITLE
Table virtual 下，表头和表体横向滚动不触发 onScroll

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#48629]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-dfqkuj?file=demo.tsx)

### Steps to reproduce

滚动并查看控制台

### What is expected?

触发 onScroll

### What is actually happening?

没有触发 onScroll

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
ref:
<img width="564" alt="截屏2024-04-25 17 16 30" src="https://github.com/ant-design/ant-design/assets/5378891/e2a07a0e-8878-4dce-9d11-a372e9b9b552">
