### ISSUE TITLE
Table组件设置Column属性hidden，数据提交问题

### ISSUE THREAD

**Issue by passioning** [ant-design/ant-design#48622]
### What problem does this feature solve?

表格内column使用render渲染Input组件，不同列之间有数据联动，提交的时候，隐藏列数据不会被提交

### What does the proposed API look like?

虽然隐藏，但是支持数据联动

**Comment by zombieJ** [comment]
可以考虑用 css 隐藏，`hidden` 本身就是不渲染 `column` 的哈。

**Comment by passioning** [comment]
<img width="753" alt="Snipaste_2024-04-25_14-24-24" src="https://github.com/ant-design/ant-design/assets/9817307/d7c79ae0-2553-4ebb-89d7-6932367719f9">

如上图，单行文本3设置了隐藏属性，但是数据来源是通过查询单号文本1的值，但是提交的时候没有这个column的数据

**Comment by passioning** [comment]
通过components设置header和body的Cell的方式，将td的display设置为none，数据可以获取，但是表格整体布局就会乱掉，如下图：
<img width="1044" alt="Snipaste_2024-04-25_14-27-11" src="https://github.com/ant-design/ant-design/assets/9817307/86c455ac-ec32-46f1-8a6e-c44837db2321">
单行文本3已经隐藏，但表格布局混乱

**Comment by Jhh910** [comment]
> ，但是支持数据联动

你好 隐藏属性是什么呀，为什么我没在源码和文档里找到
