### ISSUE TITLE
Dropdown 下拉菜单，带Icon，Children，弹出错位

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#48620]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wdu5uu?file=demo.tsx)

![image](https://github.com/ant-design/ant-design/assets/29728228/f6810a72-b97a-4da2-8df3-c48fca450bed)

### Steps to reproduce

打开demo链接即可复现

需要同时满足几个条件

1. 设置了min-width，出现水平滚动条
2. 下拉菜单有icon
3. 有二级菜单
 

目测是因为有了icon以后，菜单的宽度不够导致的

### What is expected?

弹出菜单不要错位

### What is actually happening?

菜单错位

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18 |
| System | windows10 |
| Browser | chrome |

**Comment by zystudios** [comment]
临时解决办法，加个宽度 style可以暂时解决

**Comment by afc163** [comment]
加个 `white-space: nowrap;` 就行。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50718
