### ISSUE TITLE
in antd table column not allow to add align prop

### ISSUE THREAD

**Issue by jeyakumar-BTR** [ant-design/ant-design#48638]
### Reproduction link

[https://codepen.io/JoyeSara/pen/bGJZEPv?editors=0010](https://codepen.io/JoyeSara/pen/bGJZEPv?editors=0010)

### Steps to reproduce

import { Button, Table } from 'antd';
export const PayBillInvoicedRecordsList = () => {
  const columns = [
    {
      title: 'Customer Name',
      dataIndex: 'leaseCompanyName',
      key: 'leaseCompanyName',
      align: 'left',
      render: (_: any, record: any) => ({
        children: <div className="">{record.leaseCompanyName}</div>,
        props: { rowSpan: record.isFirstElement ? rowSpan[record.enquiryNumber] : 0 },
      }),
    },
  ];

  return (
    <Table
      columns={columns}
      dataSource={flatten(data)}
      rowKey={(record, index) => `${record.enquiryNumber}_${index}`}
      loading={isFetchingInvoicedRecords}
      pagination={false}
      bordered
    />
  );
};

### What is expected?

it should allow

### What is actually happening?

     error:  Type '{ title: string; key: string; align: string; render: (_: any, record: any) => { children: JSX.Element; props: { rowSpan: number; }; }; dataIndex?: undefined; }' is not assignable to type 'ColumnType<{ isFirstElement: boolean; enquiryNumber: number; vatRate: string; lineTaxCode: { label: string; }; } | { isFirstElement: boolean; enquiryNumber: number; jobLineData: { lineTaxCode: { label: string; }; }[]; }>'.
        Types of property 'align' are incompatible.
          Type 'string' is not assignable to type 'AlignType | undefined'

| Environment | Info |
| --- | --- |
| antd | 4.24.6 |
| React | 18.3.0 |
| System | Windows 11 |
| Browser | Google chrome |

**Comment by afc163** [comment]
I can't see TS error in your reproduce link.
