### ISSUE TITLE
Modal 组件在内嵌的iframe子窗口里使用，怎么才能把父窗口也遮盖住呢

### ISSUE THREAD

**Issue by onlyWuj** [ant-design/ant-design#4863]
如题 
![22](https://cloud.githubusercontent.com/assets/24384154/22922593/65724b0a-f2d9-11e6-8743-aa8f398914da.jpg)

**Comment by huyansheng3** [comment]
覆写 z-index 值

**Comment by afc163** [comment]
没有办法。

**Comment by benjycui** [comment]
又或者在子窗口发消息给父窗口，在父窗口打开 Modal

**Comment by onlyWuj** [comment]
@benjycui 怎么传呢，有例子吗
