### ISSUE TITLE
Form.Item中的Table翻页组件样式异常

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#48630]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-x1b4g3?file=demo.tsx)

### Steps to reproduce

运行就能看见效果

### What is expected?

正常显示

### What is actually happening?

翻页组件样式异常
![image](https://github.com/ant-design/ant-design/assets/6482819/f128c1f2-afdb-4839-8d44-6d216b2cb391)

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18.2 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
试试 `noStyle`？

**Comment by fpsqdb** [comment]
@zombieJ `noStyle`后label和required必填标识没有了

**Comment by fpsqdb** [comment]
在4.x版本是正常的

**Comment by Wxh16144** [comment]
> 在4.x版本是正常的

可以贴一下代码片段么

**Comment by fpsqdb** [comment]
https://stackblitz.com/edit/react-gzhhnd?file=demo.tsx
![image](https://github.com/ant-design/ant-design/assets/6482819/3724b27f-15ea-4cca-94d4-0d08dda157f4)
