### ISSUE TITLE
Table不设置rowHoverable为false鼠标移动到table行会弹出错误页面

### ISSUE THREAD

**Issue by yyyyffqqqq** [ant-design/ant-design#48635]
### Reproduction link
 (不方便提供)
<img width="1361" alt="截屏2024-04-25 22 55 06" src="https://github.com/ant-design/ant-design/assets/19225441/7804a5c2-ac93-4be4-9865-091ddbe8633d">

### Steps to reproduce

鼠标移动到表格行就弹出一个错误页面

### What is expected?

正常显示

### What is actually happening?

不正常显示

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18.2.0 |
| System | mac  |
| Browser | chrome |

**Comment by zombieJ** [comment]
你好，我们不会处理不提供重现的 issue 哈~

ref: [《转载-如何提交无法解答的问题》](https://ant-design.antgroup.com/docs/blog/issue-helper-cn)
