### ISSUE TITLE
Select选完后下拉框不收回

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#4864]
有没有什么办法让下拉框在Select onChange后不收回的？

**Comment by xieyihao** [comment]
我想要它收回 = =#

**Comment by qiaoyixuan** [comment]
copy了一份Select的index.js，在render rcSelect时改写了onChange，执行onChange时传入render的rcSelect的ref，在外层调用rcSelect的setOpenState，暂时解决问题，但下拉框会闪一下，希望antd团队能帮忙解决一下

**Comment by benjycui** [comment]
现在 Select 的 open 状态不是可控属性，所以做不到自由控制。

**Comment by afc163** [comment]
确实是这样，@qiaoyixuan 更具体的需求是什么？业界的单选 select 一般也都是选完关闭的。

**Comment by qiaoyixuan** [comment]
具体需求是option中加入了checkbox，多个checkbox的操作希望能连续进行，不过现在用popover代替了


发自网易邮箱大师
在2017年02月15日 13:40，偏右 写道：

确实是这样，@qiaoyixuan 更具体的需求是什么？业界的单选 select 一般也都是选完关闭的。

**Comment by afc163** [comment]
checkbox 更像是多选。

**Comment by afc163** [comment]
用 Dropdown 和 Popover 确实更合适，用单选的 Select 实现多选功能，比较奇怪。这里先关了。
