### ISSUE TITLE
在使用Modal 对话框的时候，window尺寸变化，会导致对话框被被关闭

### ISSUE THREAD

**Issue by WeMadeCode** [ant-design/ant-design#48643]
### Reproduction link

[https://ant-design.antgroup.com/components/modal-cn](https://ant-design.antgroup.com/components/modal-cn)
### Steps to reproduce

1. 打开官网https://ant-design.antgroup.com/components/modal-cn
2.点击按钮【Open Modal with async logic】
3. 缩减Chrome浏览器视口
4.观察弹出的Modal 【The modal will be closed after two seconds】突然之间被关闭了

### What is expected?

在使用Modal 对话框的时候，window尺寸变化，不会导致对话框被被关闭

### What is actually happening?

在使用Modal 对话框的时候，window尺寸变化，会导致对话框被被关闭

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | Mac OS 14 |
| Browser | 124.0.6367.80 |

**Comment by zombieJ** [comment]
`The modal will be closed after two seconds` 的意思是 `这个窗口两秒后会关掉`，它和窗体改变大小没有关系，是 Demo 本身的逻辑。或者提供一个干净的重现代码看看？

**Comment by WeMadeCode** [comment]
@zombieJ 你好。我使用本地Demo 未能复现改问题。但是我使用官网复现了改问题。
可以参考下 如下录屏

https://github.com/ant-design/ant-design/assets/29619882/d9da5a5a-3a00-48c1-83d1-f57c7529cae4

**Comment by wanpan11** [comment]
> 我使用本地Demo 未能复现改问题。但是我使用官网复现了改问题。 可以参考下 如下录屏

业务里你能复现吗，目前我试的只有官网多demo时能复现（把其他 demo 注释掉后，也无法复现）

**Comment by WeMadeCode** [comment]
@wanpan11 业务里面也能 稳定复现。使用的代码 就是 【Open Modal with async loginc】。但是 我新建Demo 使用【Open Modal with async loginc】 也就无法复现了。不确定 是不是代码 其他影响了 这个Modal组件。

**Comment by linxianxi** [comment]
官网是因为缩小后布局改变成一列，右边这个 section 整合到左边这个 section 里了，所以卸载了重新 mount 了。你的业务有 bug 应该是你自己的问题。
![image](https://github.com/ant-design/ant-design/assets/47104575/1552f814-6f35-49ba-bbe9-95b5ae8e6b30)

**Comment by wanpan11** [comment]
@WeMadeCode Modal 本身没问题，官网的 demo 组件每次在屏幕尺寸变化导致 demo 换行的时候就会把 组件卸载掉，https://ant.design/components/modal-cn#components-modal-demo-static-info 用静态方法的就不会，你再检查下你的逻辑撒的
![image](https://github.com/ant-design/ant-design/assets/38714194/c2484ba9-9138-4703-9ce8-02734afdff7d)

**Comment by WeMadeCode** [comment]
> @WeMadeCode Modal 本身没问题，官网的 demo 组件每次在屏幕尺寸变化导致 demo 换行的时候就会把 组件卸载掉，https://ant.design/components/modal-cn#components-modal-demo-static-info 用静态方法的就不会，你再检查下你的逻辑撒的 ![image](https://private-user-images.githubusercontent.com/38714194/326241092-c2484ba9-9138-4703-9ce8-02734afdff7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTU3MTUsIm5iZiI6MTcxNDI5NTQxNSwicGF0aCI6Ii8zODcxNDE5NC8zMjYyNDEwOTItYzI0ODRiYTktOTEzOC00NzAzLTljZTgtMDI3MzRhZmRmZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA5MTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYzM0MDhiZThkZTZkMTU0OGI4MGQ4MGRhZTc2ODExOWRmYmIxMWQyMmY1ODc5YWE3ODBkYTQ3ZDNmN2Q4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3-XiptsRdjgbcttG7ln9ADbLb1nY6ihrQk6-7nZPYt4)

@wanpan11  你好，我想继续了解下 【官网的 demo 组件每次在屏幕尺寸变化导致 demo 换行的时候就会把 组件卸载掉】这个动作是 Modal做的，还是官方Demo 主动卸载的？

**Comment by wanpan11** [comment]
> 这个动作是 Modal做的，还是官方Demo 主动卸载的？

这是官网的行为 与 Modal 自身无关，看下@linxianxi 的回复 他的更清楚一些

**Comment by WeMadeCode** [comment]
> 官网是因为缩小后布局改变成一列，右边这个 section 整合到左边这个 section 里了，所以是先卸载（Modal 就没了）再重新 mount 了。你的业务有 bug 应该是你自己的问题。 ![image](https://private-user-images.githubusercontent.com/47104575/326241261-1552f814-6f35-49ba-bbe9-95b5ae8e6b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzI1NjAsIm5iZiI6MTcxNDM3MjI2MCwicGF0aCI6Ii80NzEwNDU3NS8zMjYyNDEyNjEtMTU1MmY4MTQtNmYzNS00OWJhLWJiZTktOTViNWFlOGU2YjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjY5ZmZkOTI1ZGZlOGI1ZmYwNDMyZWRmMGIyMmYzYTlhNjgxZWZlMjBkNDRjZTcwNDE2ZjZlNDM4NTc4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lSVbfSAAk-5CMUFE_rKzaJpxLSGLvChCwGerE7xrM08)

@wanpan11 是不是父元素（这里是session）尺寸位置的变化导致了 Modal被销毁了？

**Comment by wanpan11** [comment]
是 section 所有的组件卸载了，导致 Modal 也跟着卸载了

**Comment by WeMadeCode** [comment]
> 是 section 所在的组件卸载了，导致 Modal 也跟着卸载了

@wanpan11 Modal 直接挂载在 Body 下面的， 其实际直接父元素应该是Body。但是这里却受 理论上的父元素（这里是Session）的销毁影响。这是不是问题？

**Comment by wanpan11** [comment]
组件 和 dom 是不一样，可以看看相关的文章哦~

**Comment by WeMadeCode** [comment]
> 是 section 所在的组件卸载了，导致 Modal 也跟着卸载了

@wanpan11 所以 您觉得 【是 section 所在的组件卸载了，导致 Modal 也跟着卸载了】这不是问题 是么？

**Comment by wanpan11** [comment]
section 是人为卸载的 是在预期之中的。

**Comment by afc163** [comment]
看上去 antd 组件本身是没问题的，你遇到的是官网实现的预期逻辑。
