### ISSUE TITLE
Steps 自定义图标没有垂直居中对齐

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#48641]
### Reproduction link

[https://ant.design/components/steps-cn#steps-demo-icon](https://ant.design/components/steps-cn#steps-demo-icon)

### Steps to reproduce

查看图标 demo

### What is expected?

图标应该文字垂直居中对齐

### What is actually happening?

图标位置靠上，未与文字对齐

![image](https://github.com/ant-design/ant-design/assets/5836790/f9957035-4191-49b4-aaf9-54132f187778)

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18.2.0 |
| System | macOS |
| Browser | Chrome 121 |

**Comment by nova1751** [comment]
感觉可以`flex`布局一把梭🤔
