### ISSUE TITLE
在使用React 18.3.0 或者React 19 Beta版本时, Menu组件都会报findDOMNode is deprecated and will be removed错误

### ISSUE THREAD

**Issue by ybf970928** [ant-design/ant-design#48646]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-zapkh6?file=demo.tsx)

### Steps to reproduce

使用 Menu 组件即可

### What is expected?

无报错提示信息

### What is actually happening?

控制台会直接输出  findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference.

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18.3.0 |
| System | macos |
| Browser | chrome |

**Comment by Lil-Kr** [comment]
我也遇到了这个问题, 早上还好好的，晚上打开就这样了, @ybf970928 你的解决了么？

![image](https://github.com/ant-design/ant-design/assets/50562423/e03b6b4e-9497-47ef-8d80-9918ec5ee20b)

配置如下 :

![image](https://github.com/ant-design/ant-design/assets/50562423/ca0b7190-4a2a-4085-910e-660f417d9ebc)

**Comment by zhu-hong** [comment]
原因找到了
antd的基础工具库rc-util使用了findDOMNode，波及到的库应该很多，代码在
https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L2
react18.3之前在严格模式下使用这个API会报警，react18.3及更新版本，只要程序使用了这个API就会警报

**Comment by yoyo837** [comment]
> 原因找到了 antd的基础工具库rc-util使用了findDOMNode，波及到的库应该很多，代码在 https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L2 react18.3之前在严格模式下使用这个API会报警，react18.3及更新版本，只要程序使用了这个API就会警报

不准确，这个函数只是被调用处用来兜底的，实际逻辑处应该想办法修改逻辑优先使用例如ref等方式获取，问题不在兜底逻辑本身上。

**Comment by zhu-hong** [comment]
> > 原因找到了 antd的基础工具库rc-util使用了findDOMNode，波及到的库应该很多，代码在 https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L2 react18.3之前在严格模式下使用这个API会报警，react18.3及更新版本，只要程序使用了这个API就会警报
> 
> 不准确，这个函数只是被调用处用来兜底的，实际逻辑处应该想办法修改逻辑优先使用例如ref等方式获取，问题不在兜底逻辑本身上。

resize-observer直接使用findDOMNode导致的，我使用了rc-select并使用了getRawInputElement这个参数

**Comment by Yizhizhenhties** [comment]
我发现有很多组件都会出现这种情况
比如Tooltip，如果是：
```typescript
<Tooltip>
    <Checkbox/>
</Tooltip>
```
或者把 checkbox 换成 select 就会有问题
```
<Cascader>
    <Button/>
</Cascader>
```
这样也会有问题
奇怪的是 如果子组件是一些基础元素就没啥问题

**Comment by shanmugarajbe** [comment]
Also, this issue is present in Antd Tour Component,
`<Tour />`

**Comment by codedart2018** [comment]
同样此问题，我目前固定版本降到18.2.0了，18.3以上可以了踢我啊！

**Comment by shanmugarajbe** [comment]
> I have the same problem. My current fixed version has been downgraded to 18.2.0. If it is 18.3 or above, kick me!

Yes my current version is 18.3
Antd version is 5.16.4

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/48709

**Comment by shengzhou1216** [comment]
re-uitl 的问题吧，其他库都是直接调用findDOMNode的

**Comment by jekip** [comment]
> 同样此问题，我目前固定版本降到18.2.0了，18.3以上可以了踢我啊！

+1

**Comment by leshalv** [comment]
+1

**Comment by sunxun007** [comment]
> > > 原因找到了 antd的基础工具库rc-util使用了findDOMNode，波及到的库应该很多，代码在 https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L2 react18.3之前在严格模式下使用这个API会报警，react18.3及更新版本，只要程序使用了这个API就会警报
> > 
> > 
> > 不准确，这个函数只是被调用处用来兜底的，实际逻辑处应该想办法修改逻辑优先使用例如ref等方式获取，问题不在兜底逻辑本身上。
> 
> resize-observer直接使用findDOMNode导致的，我使用了rc-select并使用了getRawInputElement这个参数也会有这个警告 https://github.com/react-component/resize-observer/blob/master/src/SingleObserver/index.tsx#L40

严格模式我关闭了还是报错.不知道是不是关闭错了地方

**Comment by ybf970928** [comment]
> > > > 原因找到了 antd的基础工具库rc-util使用了findDOMNode，波及到的库应该很多，代码在 https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L2 react18.3之前在严格模式下使用这个API会报警，react18.3及更新版本，只要程序使用了这个API就会警报
> > > 
> > > 
> > > 不准确，这个函数只是被调用处用来兜底的，实际逻辑处应该想办法修改逻辑优先使用例如ref等方式获取，问题不在兜底逻辑本身上。
> > 
> > 
> > resize-observer直接使用findDOMNode导致的，我使用了rc-select并使用了getRawInputElement这个参数也会有这个警告 https://github.com/react-component/resize-observer/blob/master/src/SingleObserver/index.tsx#L40
> 
> 严格模式我关闭了还是报错.不知道是不是关闭错了地方

不是啊, 问题很简单, 源码里使用到了findDOMNode这个方法, 改成ref的方式就差不多了, 不着急, 等官方慢慢调整就好了

**Comment by zhu-hong** [comment]
> > > > 原因找到了 antd的基础工具库rc-util使用了findDOMNode，波及到的库应该很多，代码在 https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L2 react18.3之前在严格模式下使用这个API会报警，react18.3及更新版本，只要程序使用了这个API就会警报
> > > 
> > > 
> > > 不准确，这个函数只是被调用处用来兜底的，实际逻辑处应该想办法修改逻辑优先使用例如ref等方式获取，问题不在兜底逻辑本身上。
> > 
> > 
> > resize-observer直接使用findDOMNode导致的，我使用了rc-select并使用了getRawInputElement这个参数也会有这个警告 https://github.com/react-component/resize-observer/blob/master/src/SingleObserver/index.tsx#L40
> 
> 严格模式我关闭了还是报错.不知道是不是关闭错了地方

react18.3及更新版本，只要用到了就会爆警告（不限于使用了严格模式），https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-finddomnode

**Comment by hl1249** [comment]
> 同样此问题，我目前固定版本降到18.2.0了，18.3以上可以了踢我啊！

请问一下 我降到了18.2.0 为啥还在报错

**Comment by yoyo837** [comment]
> > 同样此问题，我目前固定版本降到18.2.0了，18.3以上可以了踢我啊！
> 
> 请问一下 我降到了18.2.0 为啥还在报错

npm ls react一下

**Comment by kaoding** [comment]
菜单几乎每个页面都有，所以一直有警告，这个能否加快修复一下。

**Comment by codetown** [comment]
同问，请加急修复，只要用了Menu组件，就会报这个错

**Comment by yoyo837** [comment]
Similar to #48709

**Comment by yoyo837** [comment]
There are some fixes in #48958.

**Comment by KemingRen** [comment]
> 同样此问题，我目前固定版本降到18.2.0了，18.3以上可以了踢我啊！

我也是18.2.0  为哈就不行啊

**Comment by yoyo837** [comment]
> > 同样此问题，我目前固定版本降到18.2.0了，18.3以上可以了踢我啊！
> 
> 我也是18.2.0 为哈就不行啊

npm ls react一下

**Comment by KemingRen** [comment]
> > > 同样此问题，我目前固定版本降到18.2.0了，18.3以上可以了踢我啊！
> > 
> > 
> > 我也是18.2.0 为哈就不行啊
> 
> npm ls react一下

你行吗 老哥

**Comment by afc163** [comment]
Fixed in antd@5.17.3: https://stackblitz.com/edit/react-zapkh6-gxledw?file=package.json,index.tsx

**Comment by jiaozhiye** [comment]
![image](https://github.com/ant-design/ant-design/assets/22720488/45b2f396-ab1a-41d8-bd99-04d43c4d6c10)
这个问题解决了吗？我这里react18.3.1还是报这个警告！

**Comment by LBH-95** [comment]
现在还在报错，还没有更新吗？

**Comment by ybf970928** [comment]
> 现在还在报错，还没有更新吗？ 升级antd有用吗

早就解决了, 把依赖删了重新install下试试

**Comment by leonkong** [comment]
我这把react，react-dom， @types/react, @types/react-dom都从头18.3降到18.2的版本后问题就没了，antd@5.19.3

**Comment by wxs77577** [comment]
https://github.com/ant-design/ant-design/issues/43064#issuecomment-2456508430
