### ISSUE TITLE
Select组件能否支持拿到过滤后的options列表

### ISSUE THREAD

**Issue by coder-xiaotian** [ant-design/ant-design#48655]
### What problem does this feature solve?

项目功能对option选中项有数量限制，所以需要拿到过滤后的options列表来进行限制的判断

### What does the proposed API look like?

我期望在drapdownRender函数中可以传回options，或者能够通过Select 的API获取到

**Comment by zombieJ** [comment]
不建议去拿组件内部状态，内部状态不会保证版本一致性：

ref: [为什么我不应该访问组件内部的 props 和 state？](https://ant-design.antgroup.com/docs/react/faq-cn#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%B8%8D%E5%BA%94%E8%AF%A5%E9%80%9A%E8%BF%87-ref-%E8%AE%BF%E9%97%AE%E7%BB%84%E4%BB%B6%E5%86%85%E9%83%A8%E7%9A%84-props-%E5%92%8C-state)

如果你锁版本，可以考虑看看 rc-select 底层的 Context，options 通过 context 传递。但是如上所述，不应该这么做。

**Comment by Just-Like** [comment]
老哥有办法了吗
