### ISSUE TITLE
useWatch value get frozen inside columns render function

### ISSUE THREAD

**Issue by ndtnguyen** [ant-design/ant-design#48659]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-8sf7pj?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvgdh8pf00063b6j0d5rh0od%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvgdh8pf00023b6j0ovspnvt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvgdh8pf00033b6jvrc98p67%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvgdh8pf00053b6j993f03kb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvgdh8pf00023b6j0ovspnvt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgdh8pf00013b6j5j0eozdz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A23%257D%255D%257D%255D%252C%2522id%2522%253A%2522clvgdh8pf00023b6j0ovspnvt%2522%252C%2522activeTabId%2522%253A%2522clvgdh8pf00013b6j5j0eozdz%2522%257D%252C%2522clvgdh8pf00053b6j993f03kb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvgdh8pf00043b6jmn9bo4mx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvgdh8pf00053b6j993f03kb%2522%252C%2522activeTabId%2522%253A%2522clvgdh8pf00043b6jmn9bo4mx%2522%257D%252C%2522clvgdh8pf00033b6jvrc98p67%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvgdh8pf00033b6jvrc98p67%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
<img width="1353" alt="Screenshot 2024-04-26 at 15 48 55" src="https://github.com/ant-design/ant-design/assets/22744814/17742f0e-624f-4edf-bb75-746197483018">

1. Initialize the dataSource through form values with 1 row.
2. Click 'Add'
2. Click 'Delete' on any row

### What is expected?

Selected row should be deleted

### What is actually happening?

-  throw Error because `dataSource` from `useWatch()` return the initial value - which is undefined
-  form.getFieldValue return the latest data

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 17.0.2 |
| System | Mac Sonoma 14.3 |
| Browser | Chrome |

---
When using watch value outside of column render function, it still works perfectly fine, it return the latest value of dataSource (which you can see in `addRow()`)

**Comment by zombieJ** [comment]
Thanks for feedback but this is not related with antd.

The implementation of the `deleteRow` method as a closure within your code cause the data locking issue. We kindly suggest exploring some resources on closures knowledge to help resolve this.
