### ISSUE TITLE
Input disabled 没有红色 border

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#48669]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-nww95x?file=demo.tsx)

### Steps to reproduce

点击 submit

### What is expected?

Input 红色 border

### What is actually happening?

input 没有红色 border

<img width="565" alt="image" src="https://github.com/ant-design/ant-design/assets/7971419/f2600e69-8f64-439e-be37-070b70dce902">

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by coderz-w** [comment]
这个已经有老哥修过了，还没合
[ #48616](https://github.com/ant-design/ant-design/pull/48616)

**Comment by crazyair** [comment]
> 这个已经有老哥修过了，还没合 [ #48616](https://github.com/ant-design/ant-design/pull/48616)

看了下 v4 也没红色，不知道是预期的还是早就这样了

**Comment by afc163** [comment]
应该是预期的。

**Comment by crazyair** [comment]
> 应该是预期的。

看了，加上了，已经合并发版了
