### ISSUE TITLE
Tabs组件“更多按钮”无限闪现

### ISSUE THREAD

**Issue by mrdulin** [ant-design/ant-design#48678]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-nrittl?file=demo.tsx)

### Steps to reproduce

不需要额外操作

### What is expected?

更多按钮应该是隐藏状态

### What is actually happening?

“更多”按钮无限闪现，导致整体宽度一直变化

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18.3.1 |
| System | windows 10 |
| Browser | Edge 124.0.2478.51 |

**Comment by yyz945947732** [comment]
https://github.com/ant-design/ant-design/issues/46910

https://github.com/ant-design/ant-design/issues/46198

**Comment by wanpan11** [comment]
这个例子是v4的，v5里这例子是正常的
v4 已经停止维护了，可以试试升级到v5
https://ant.design/docs/blog/v4-ood-cn

![image](https://github.com/ant-design/ant-design/assets/38714194/2acc9eff-1952-4469-894a-777313c068f2)
