### ISSUE TITLE
antd tooltip嵌套svg  点击时跳转页面 tooltip会在新页面一直存在 除非刷新

### ISSUE THREAD

**Issue by lhb2631225005** [ant-design/ant-design#48679]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/tooltip-cn/#API](https://4x-ant-design.antgroup.com/components/tooltip-cn/#API)

### Steps to reproduce

antd tooltip嵌套svg  点击时跳转页面 tooltip会在新页面一直存在 除非刷新

### What is expected?

antd tooltip嵌套svg  点击时跳转页面 tooltip不会出现在新页面

### What is actually happening?

antd tooltip嵌套svg  点击时跳转页面 tooltip会在新页面一直存在 除非刷新

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react 18.2.0 |
| System | window10 |
| Browser | google   120.0.6099.130 |

---
链接是随便弄的 按这个步骤就可以触发

**Comment by Wxh16144** [comment]
[📢 v4 维护周期截止](https://ant.design/docs/blog/v4-ood-cn)
