### ISSUE TITLE
ant-design-vue treeselect懒加载的方式，弹窗第一次点开点击父可以懒加载子节点，但是弹窗关闭重新打开之后，之前点击展开的父节点再次点击就不能加载子节点了，为什么？

### ISSUE THREAD

**Issue by xiaofei25** [ant-design/ant-design#48685]
### What problem does this feature solve?

弹窗第一次点开点击父可以懒加载子节点，但是弹窗关闭重新打开之后，之前点击展开的父节点再次点击就不能加载子节点了，为什么？

### What does the proposed API look like?

弹窗第一次点开点击父可以懒加载子节点，但是弹窗关闭重新打开之后，之前点击展开的父节点再次点击父节点还可以加载子节点

**Comment by afc163** [comment]
这里是 React 版本的库。
