### ISSUE TITLE
Form.useWatch 为 undefined 导致页面报错

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#48680]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-bxobt2?file=demo.tsx)

### Steps to reproduce

打开 demo

### What is expected?

不报错

### What is actually happening?

报错

| Environment | Info |
| --- | --- |
| antd | 5.16.5 |
| React | latest |
| System | mac |
| Browser | chrome |

name 如果不传，则是 `undefined`，但是 value 不是 undefined，而是 `{}`，希望当 name 为 undefined、null、false，返回值为 undefined

**Comment by Wxh16144** [comment]
<img width="1041" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/319c891e-e35e-4f3c-916a-7bb43146a439">

文档说了第一个参数必填，感觉没必要做太多防御性编程，应该由使用开发者自己判断。

**Comment by crazyair** [comment]
> <img alt="image" width="1041" src="https://private-user-images.githubusercontent.com/32004925/326320169-319c891e-e35e-4f3c-916a-7bb43146a439.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjAxMTcsIm5iZiI6MTcxNDM1OTgxNywicGF0aCI6Ii8zMjAwNDkyNS8zMjYzMjAxNjktMzE5Yzg5MWUtZTM1ZS00ZjNjLTkxNmEtN2JiNDMxNDZhNDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAzMDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTg3OGU5NDQ0MjFmYzYyMjMyNDdmYzdkOGU4NjBkNzViOWZmODYwODBlOTRiOTA1NGYyMzdjMDA2YWMzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qhI7B4SMOyN6iQjc3dnnJIRR5PS9O9M6cq7UZTjxsXM">
> 文档说了第一个参数必填，感觉没必要做太多防御性编程，应该由使用开发者自己判断。

类型定义的是必填的，但是其实可以
```tsx
const ddd: string | undefined = undefined;
    Form.useWatch(ddd);
```

不报错，这个 useWatch 的类型定义估计有点问题，但

如果是 `useWatch('')` 估计也不会有类型错误，

另外其实可以优化，如果 useWatch 的 name 参数找不到 value 可以返回空，不返回 `{}`

**Comment by MadCcc** [comment]
JSON.stringify

**Comment by crazyair** [comment]
应该是 useWatch 返回 undefined

**Comment by crazyair** [comment]
https://github.com/react-component/field-form/pull/690
