### ISSUE TITLE
SwitcherIconCom 组件不支持自定义loading

### ISSUE THREAD

**Issue by shanhexi** [ant-design/ant-design#48681]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/tree/utils/iconUtil.tsx](https://github.com/ant-design/ant-design/blob/master/components/tree/utils/iconUtil.tsx)

### Steps to reproduce

SwitcherIconCom 组件里如果是loading直接return了LoadingOutlined，导致无法自定义自定义Tree的loading效果

### What is expected?

可以有渠道自定义Tree的loding图标

### What is actually happening?

无法自定义Tree的loading的图标

| Environment | Info |
| --- | --- |
| antd | 5.16.5 |
| React | 18.0 |
| System | mac |
| Browser |  Chrome  123.0.6312.124（正式版本） (x86_64) |

**Comment by shanhexi** [comment]
> Hello @shanhexi. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to proper branch (feature branch for the new feature, master for bugfix and other changes), fill the [Pull Request Template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md) here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!
> 
> 你好 @shanhexi，我们完全同意你的提议/反馈，欢迎直接在此仓库 [创建一个 Pull Request](https://help.github.com/en/articles/creating-a-pull-request) 来解决这个问题。请将 Pull Request 发到正确的分支（新特性发到 feature 分支，其他发到 master 分支），务必填写 Pull Request 内的[预设模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)，提供改动所需相应的 changelog、TypeScript 定义、测试用例、文档等，并确保 CI 通过，我们会尽快进行 Review，提前感谢和期待您的贡献。
> 
> ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif) [ ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif) ](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif) [ ](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

我的建议是给Tree添加一个新的入参switcherLoadingIcon: ReactNode | ((props: AntTreeNodeProps) => ReactNode) 
如果这个方案可行，我会在稍后实现它

> Hello @shanhexi. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to proper branch (feature branch for the new feature, master for bugfix and other changes), fill the [Pull Request Template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md) here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!
> 
> 你好 @shanhexi，我们完全同意你的提议/反馈，欢迎直接在此仓库 [创建一个 Pull Request](https://help.github.com/en/articles/creating-a-pull-request) 来解决这个问题。请将 Pull Request 发到正确的分支（新特性发到 feature 分支，其他发到 master 分支），务必填写 Pull Request 内的[预设模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md)，提供改动所需相应的 changelog、TypeScript 定义、测试用例、文档等，并确保 CI 通过，我们会尽快进行 Review，提前感谢和期待您的贡献。
> 
> ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif) [ ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif) ](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif) [ ](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)

我的建议是给Tree添加一个新的入参switcherLoadingIcon: ReactNode | ((props: AntTreeNodeProps) => ReactNode) 
如果这个方案可行，我会在稍后实现它

**Comment by shanhexi** [comment]
我的建议是给Tree添加一个新的入参switcherLoadingIcon: ReactNode | ((props: AntTreeNodeProps) => ReactNode)
如果这个方案可行，我会在稍后实现它

**Comment by coding-ice** [comment]
这个还在跟进步，我来实现下

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/49716
