### ISSUE TITLE
Modal 页面打开后会跳到下面去

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#48699]
重现链接：https://ant.design/components/modal-cn
要和 https://github.com/ant-design/ant-design/issues/41239 这个问题一起看。

可以考虑用 react-focus-lock https://github.com/ant-design/ant-design/issues/47916 重构 Modal 和 Drawer 的 focus 逻辑。

**Comment by Wxh16144** [comment]
之前在社区共建群讨论的时候我去看过一眼：

<img width="887" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/73bea452-a2ac-42b4-b8f2-276b144dab77">

具体代码 https://github.com/react-component/dialog/blob/852caadf6d9e9af744c9246e8db3fcd70577f35e/src/Dialog/Content/Panel.tsx#L149

可能需要开一个口子，允许修改这个 tabindex 值。
