### ISSUE TITLE
InputNumber's changeOnWheel props ignored when type is number

### ISSUE THREAD

**Issue by devops3199** [ant-design/ant-design#48695]
### Reproduction link

[https://ant.design/components/input-number#input-number-demo-change-on-wheel](https://ant.design/components/input-number#input-number-demo-change-on-wheel)

### Steps to reproduce

try the code below.

```
<InputNumber type="number" min={1} max={10} defaultValue={3} onChange={onChange} changeOnWheel={false} />
```

### What is expected?

A wheel action should be ignored when type is number and changeOnWheel is false.

### What is actually happening?

A wheel action is still applied when type is number.

| Environment | Info |
| --- | --- |
| antd | 5.16.5 |
| React | 17.0.2 |
| System | M1 |
| Browser | Chrome 120.0.6099.109 |

**Comment by wanpan11** [comment]
The InputNumber component is working properly, which should be an issue with the editor on the official website 🧐

**Comment by devops3199** [comment]
I'm afraid that the issue has arisen in my local.

**Comment by wanpan11** [comment]
https://stackblitz.com/edit/react-zbmzv8-ikvn43?file=demo.tsx

**Comment by devops3199** [comment]
https://stackblitz.com/edit/react-zbmzv8-pxass1?file=demo.tsx

I added type attribute.

**Comment by wanpan11** [comment]
The problem is caused by type="number", removing the type is normal. I will explain this issue in the document later 🧐

**Comment by devops3199** [comment]
https://stackblitz.com/edit/react-zbmzv8-4pcc6d?file=demo.tsx

Even just `<Input type="number" />` does not work with changeOnWheel props. As a vanilla html input tag does not allow wheel actions, it's better to take this as a bug.

**Comment by wanpan11** [comment]
Vanilla input adds `type="number"` mouse wheel events are supported by default in Chrome

**Comment by jessewriter** [comment]
i can confirm this issue and it is simple as removing type prop from NumberInput to fix but unfortunately this took me a long time to figure out :/ can i suggest to throw an error if someone makes this mistake with a message on how to fix.
