### ISSUE TITLE
在某些情况下表头消失

### ISSUE THREAD

**Issue by hengyanqwe** [ant-design/ant-design#48691]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/p/github/hengyanqwe/react-test/master?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkhfz6c0006356iqz37mehb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkhfz6c0002356im6pfzznp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkhfz6c0004356itz4sjk1u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkhfz6c0005356i6ouuf6vi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkhfz6c0002356im6pfzznp%2522%253A%257B%2522id%2522%253A%2522clvkhfz6c0002356im6pfzznp%2522%252C%2522activeTabId%2522%253A%2522clvkhj2gt005y356hjgee2sbv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkhfz6c0001356iwkdhon72%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clvkhj2gt005y356hjgee2sbv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clvkhfz6c0005356i6ouuf6vi%2522%253A%257B%2522id%2522%253A%2522clvkhfz6c0005356i6ouuf6vi%2522%252C%2522activeTabId%2522%253A%2522clvkhiu8m0044356hirf8o0fz%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clvkhiu8m0044356hirf8o0fz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clvkivnfm0003356h8j8sgqg7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clvkhfz6c0004356itz4sjk1u%2522%253A%257B%2522id%2522%253A%2522clvkhfz6c0004356itz4sjk1u%2522%252C%2522activeTabId%2522%253A%2522clvkibkpg00oa356hmovp5o53%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkhfz6c0003356ieg6qksjs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvkhg43e000zdkk87tcv0wus%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clvkhg764004d356iqbobuuc7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clvkhh35e007u356i17z89f5q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvkhhts2001bdkk8hns1dxfp%2522%257D%252C%257B%2522type%2522%253A%2522GIT_LOG%2522%252C%2522shellId%2522%253A%2522clvkin9sg001jdci6b4sscne3%2522%252C%2522id%2522%253A%2522clvkibkpg00oa356hmovp5o53%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clvkif59g00an356hnyw9pyqm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)](https://codesandbox.io/p/github/hengyanqwe/react-test/master?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvkhfz6c0006356iqz37mehb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvkhfz6c0002356im6pfzznp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvkhfz6c0004356itz4sjk1u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvkhfz6c0005356i6ouuf6vi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvkhfz6c0002356im6pfzznp%2522%253A%257B%2522id%2522%253A%2522clvkhfz6c0002356im6pfzznp%2522%252C%2522activeTabId%2522%253A%2522clvkhj2gt005y356hjgee2sbv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkhfz6c0001356iwkdhon72%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clvkhj2gt005y356hjgee2sbv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clvkhfz6c0005356i6ouuf6vi%2522%253A%257B%2522id%2522%253A%2522clvkhfz6c0005356i6ouuf6vi%2522%252C%2522activeTabId%2522%253A%2522clvkhiu8m0044356hirf8o0fz%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clvkhiu8m0044356hirf8o0fz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clvkivnfm0003356h8j8sgqg7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clvkhfz6c0004356itz4sjk1u%2522%253A%257B%2522id%2522%253A%2522clvkhfz6c0004356itz4sjk1u%2522%252C%2522activeTabId%2522%253A%2522clvkibkpg00oa356hmovp5o53%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvkhfz6c0003356ieg6qksjs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvkhg43e000zdkk87tcv0wus%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clvkhg764004d356iqbobuuc7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clvkhh35e007u356i17z89f5q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvkhhts2001bdkk8hns1dxfp%2522%257D%252C%257B%2522type%2522%253A%2522GIT_LOG%2522%252C%2522shellId%2522%253A%2522clvkin9sg001jdci6b4sscne3%2522%252C%2522id%2522%253A%2522clvkibkpg00oa356hmovp5o53%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clvkif59g00an356hnyw9pyqm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

添加，然后右侧的表格删除几个就出现了

### What is expected?

正常

### What is actually happening?

表头消失

| Environment | Info |
| --- | --- |
| antd | 5.16.5 |
| React | 18 |
| System | windows |
| Browser | chrome |
![image](https://github.com/ant-design/ant-design/assets/68996932/a74cb88c-7134-4fe2-90cb-bed581499995)

**Comment by linxianxi** [comment]
![image](https://github.com/ant-design/ant-design/assets/47104575/3dfdf04c-4d94-46c3-b491-c7def95a9b18)
key 不能为数组，修改后正常。建议添加类型 const columns: TableProps['columns'] = [];

另外，提问题最好提供最小复现，你这个代码又多，又没格式化，帮你查问题的时候想🤮

**Comment by hengyanqwe** [comment]
> ![image](https://private-user-images.githubusercontent.com/47104575/326354280-3dfdf04c-4d94-46c3-b491-c7def95a9b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzYyNDAsIm5iZiI6MTcxNDM3NTk0MCwicGF0aCI6Ii80NzEwNDU3NS8zMjYzNTQyODAtM2RmZGYwNGMtNGQ5NC00NmMzLWI0OTEtYzdkZWY5NWE5YjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA3MzIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YjY1MzUyOWU5M2FhODJhMmJmMzM1NDBjYWU4NTY1MWM3NjhlODZjYTk0MDI4MTRhYWFhODZiMTNhMjRkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v6-YfmyRXdn-MAlOtzUNe84okW3cv8Y6Rhwfa2ALOE0) key 不能为数组，修改后正常。建议添加类型 const columns: TableProps['columns'] = [];
> 
> 另外，提问题最好提供最小复现，你这个代码又多，又没格式化，帮你查问题的时候想🤮

好了，谢谢大佬
