### ISSUE TITLE
select开启labelInValue后，希望把选项属性全部暴露出去或者使用扩展字段保存

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#48696]
### What problem does this feature solve?

目前从上下问中只能拿到value和label，复杂场景不能满足需求，所以就得自己做缓存
<img width="793" alt="image" src="https://github.com/ant-design/ant-design/assets/26105827/322f7bce-2ba0-4005-9311-a8f761652adf">

### What does the proposed API look like?

把option直接导出，或者增加扩展字段

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by afc163** [comment]
onChange 里的第二个参数是 option。

**Comment by mizi-lin** [comment]
> onChange 里的第二个参数是 option。

但在删除选项引起的 onChange 后，option 对象变成了 空对象

**Comment by hans000** [comment]
> > onChange 里的第二个参数是 option。
> 
> 但在删除选项引起的 onChange 后，option 对象变成了 空对象

有吗，没吧，不过我说的问题一些官方不想改，Select改不动了 QAQ
