### ISSUE TITLE
Select tagRender的上下问参数onClose有歧义

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#48697]
### What problem does this feature solve?

onXXX通常都是事件处理函数，实际使用应该却是action handler的效果，所以名字应该改一下叫close，我理解里面的传参也是不需要的，我在外面都有event了，还差那一句调用吗
<img width="635" alt="image" src="https://github.com/ant-design/ant-design/assets/26105827/37c931b1-d646-441f-8492-7cfbc6b503f9">

**Comment by Wxh16144** [comment]
你这个截图指的是：https://github.com/react-component/select/blob/424bcfd0614f9d8e013a983a2daf80fa46c906ca/src/Selector/MultipleSelector.tsx#L145 这里的逻辑吧。（你的截图不规范，还得单独去找，很麻烦

我看了一眼代码确实是一个 action 操作，但是你说的改名这会变成一个 breakchange，不太可取。

（源码也是将 onClose 直接传递给某个操作 onClick 回调函数，

**Comment by hans000** [comment]
我主要想问一下作者的看法，应该可以先注上deprecated 写上原因的，另开一个字段

**Comment by Wxh16144** [comment]
> 我主要想问一下作者的看法，应该可以先注上deprecated 写上原因的，另开一个字段

嗯嗯，可以等核心成员今天周会的时候评论一下~

**Comment by MadCcc** [comment]
onClose 指的是点击关闭按钮的这个事件，Modal 也是一样的，没有更名必要
