### ISSUE TITLE
Support for OKLCH color space

### ISSUE THREAD

**Issue by igakopi** [ant-design/ant-design#48698]
### What problem does this feature solve?

Theming should support OKLCH format. In oklch lightness value is based on human perception, so moving through the hue always renders the same lightness comparatively. It will positively influence user experience and ease of controlling contrast ratios in terms of accessibility. Oklch can also display colors the newer Display P3 gamut.

### What does the proposed API look like?

This regards Theming configuration.

**Comment by afc163** [comment]
Could you provide reproduce about how cannot antd support OKLCH color space?

**Comment by ArturBaybulatov** [comment]
Here's the bug reproduction:

https://codesandbox.io/p/sandbox/sandpack-project-forked-knd94g?file=%2Fapp.tsx%3A9%2C16

The buttons should be green:

![Image](https://github.com/user-attachments/assets/79fc8978-18ee-4aef-baf9-479096fbc2c5)
