### ISSUE TITLE
ant.design react-router 单页化

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#487]
https://github.com/ant-design/ant-design/issues/486

https://github.com/ant-design/ant-design/issues/480

**Comment by afc163** [comment]
#480 说的不是这个吧。

**Comment by yiminghe** [comment]
这个后面找人做下，算是一个很好的 demo

**Comment by wangwenjie1314** [comment]
ant.design react-router 单页化
写了个简单的入门摸索：
https://github.com/wangwenjie1314/ant-blog

**Comment by plandem** [comment]
can't read chinese, but for router this can help:

Quite good replacement for bloated react-router:
https://github.com/STRML/react-router-component

Quite good implementation via redux:
https://github.com/callum/redux-routing

just interesting article:
http://jamesknelson.com/simple-routing-redux-react/

**Comment by afc163** [comment]
#1093
