### ISSUE TITLE
Slider tooltip set to open: false, but still opens when active

### ISSUE THREAD

**Issue by orocsy** [ant-design/ant-design#48707]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

Follow example in the slider page, set tooltip={{ open: false }}

### What is expected?

Tooltip is completely hidden as described in the component description

### What is actually happening?

Tooltip is still showing when dragging the slider handle

| Environment | Info |
| --- | --- |
| antd | 5.16.5 |
| React | react18 |
| System | MacOS Ventura 13.6.3 |
| Browser | Version 124.0.6367.92 (Official Build) (x86_64) |

**Comment by wanpan11** [comment]
Waiting for the next patch version, use  `tooltip={{ formatter: null }}`

https://github.com/ant-design/ant-design/issues/48668
