### ISSUE TITLE
feature request: custom antd icon for rating component

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design#4870]
I have a use case where I need a rating component but it has to be dollar signs rather than stars-- thought I'd mention it here!

**Comment by afc163** [comment]
I'd like to add a new prop `charactor` to specify star in Rate, and it will be released in `rc-rate@2.0.0` and `antd@2.8.0`.

**Comment by acomito** [comment]
@afc163 the other thing to (maybe) think about is the option to change the highlighted and not highlighted colors of the icon.

**Comment by kvetoslavnovak** [comment]
This will be great addon! I needed exclamation icon for negative ratings.

**Comment by benjycui** [comment]
antd 2.8 里面还没升级依赖。
