### ISSUE TITLE
图片预览时为什么不会返回当前图片信息？

### ISSUE THREAD

**Issue by 15607306950** [ant-design/ant-design#48713]
### What problem does this feature solve?

图片与视频实时切换

### What does the proposed API look like?

比如在toolbarRender方法中返回对应图片信息，可根据当前图片状态或者类型来渲染的对应的功能操作按钮

**Comment by afc163** [comment]
### What does the proposed API look like?

**Comment by afc163** [comment]
欢迎 PR~

**Comment by nova1751** [comment]
I'll try to achieve this feature.

**Comment by 15607306950** [comment]
> 状态或者

可否增加类型字段与src平级 例如：type:img | video

**Comment by yoyo837** [comment]
> I'll try to achieve this feature.

再来个PR到feature更新上来？

**Comment by nova1751** [comment]
> > 状态或者
> 
> 可否增加类型字段与src平级 例如：type:img | video

这个属性代表什么呢，能解释下由什么决定吗？
