### ISSUE TITLE
select在multi模式下，可否支持allowClear

### ISSUE THREAD

**Issue by connorTang** [ant-design/ant-design#4871]
#### Environment(required)

- antd version: 2.5.3
- OS and its version: Mac OS
- Browser and its version: Latest Chrome and Firefox

#### What did you do? Please provide steps to re-produce your problem.
目前allowClear仅支持清除single mode下的选项。

#### What do you expected?

能不能支持multi mode下清除所有选项？

**Comment by yesmeck** [comment]
重复 #4843

**Comment by connorTang** [comment]
@yesmeck @yiminghe  这里能解释一下在multi模式下为什么不支持allowClear么？这应该是很有用并且很重要的一个功能。

**Comment by yesmeck** [comment]
看 #4843 的讨论。

**Comment by connorTang** [comment]
@yesmeck 我是真心没看懂那个讨论说的什么意思……而且完全不make sense啊。 可否再详细解释一下原因？

**Comment by yesmeck** [comment]
就是当时没有交互设计，就没做。

**Comment by connorTang** [comment]
@yesmeck 哦，那未来会对这个功能进行支持么？应该是很有用的功能。

**Comment by yesmeck** [comment]
请订阅 #4843 。。。

**Comment by yesmeck** [comment]
或者你觉得很急很关键的话，非常欢迎给我们 PR。

**Comment by connorTang** [comment]
好的，谢谢。
