### ISSUE TITLE
ColorPicker component should have offset option

### ISSUE THREAD

**Issue by zairlaka** [ant-design/ant-design#48730]
### What problem does this feature solve?

just like Select component `dropdownAlign={{offset: [0, 0]}}`
ColorPicker component should have offset option. 
I am creating a tooltip div for editing the page when the text is down ColorPicker obviously pop up on the top where my other select dropdowns and menu place on the first row that triggers due to the space between them.
I know I can set the placement but I want default dynamic behaviour.
![image](https://github.com/ant-design/ant-design/assets/35995446/28f862ac-5b3f-44f3-b3be-88b810ed51c2)

### What does the proposed API look like?

just add offset option in ColorPicker like we do have in Select component

**Comment by afc163** [comment]
You can try `<ColorPicker arrow={{ pointAtCenter: true }} />`.
