### ISSUE TITLE
support for styled-components?

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#4873]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by yesmeck** [comment]
Could you describe it more detailed?

**Comment by benjycui** [comment]
If you mean this [styled-components](https://www.npmjs.com/package/styled-components), it will be a breaking change.

**Comment by afc163** [comment]
No plan for now, same reason as https://github.com/ant-design/ant-design/issues/4413#issuecomment-269730280 😅
