### ISSUE TITLE
Table lost most styling

### ISSUE THREAD

**Issue by replygirl** [ant-design/ant-design#48747]
### Reproduction link

[https://ant.design/components/table](https://ant.design/components/table)

### Steps to reproduce

N/A — All tables affected

### What is expected?

Table has borders, padding, and other cell styles

### What is actually happening?

Table is missing most styles

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Arc 124.0.6367.60 (Chromium 124.x) |

---
Started with 5.17.0

**Comment by li-jia-nan** [comment]
It seems that just the style of the official website is lost ?

Or is the style of the component itself lost ?

**Comment by yoyo837** [comment]
Trace it in #48749
