### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by Ladvace** [ant-design/ant-design#48749]
### Reproduction link

[https://ant.design/components/overview/](https://ant.design/components/overview/)

### Steps to reproduce

I visited it in multiple browsers, in incognito and not, to be sure of the problem.

vistit https://ant.design/components/overview/

### What is expected?

to not be broken

### What is actually happening?

https://imgur.com/a/COa0PcJ

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | none |
| System | Macos |
| Browser | Chrome, Arc |

**Comment by djtriptych** [comment]
Confirmed broken (tried regular + incognito on Chrome and Edge latest versions)

**Comment by mnai01** [comment]
Confirmed on chrome

**Comment by NZMia** [comment]
Confirmed on chrome
![image](https://github.com/ant-design/ant-design/assets/10533181/b319841a-2f2b-4dab-91a1-76b499eb6df4)

**Comment by uunw** [comment]
Confirmed on edge

**Comment by tientq64** [comment]
Confirmed on Firefox.
![image](https://github.com/ant-design/ant-design/assets/15934554/c334516a-8f18-4ced-914a-3cff9a87c15b)
