### ISSUE TITLE
DatePicker types error using Luxon DateTime

### ISSUE THREAD

**Issue by jonmurciano** [ant-design/ant-design#48757]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/datepicker-types-rv6nrn)

### Steps to reproduce

Insert DateTime with onChange property.

### What is expected?

onChange property on DatePicker component returns typinng error not admitting nullable DateTime.

### What is actually happening?

onChange property on DatePicker component returns typinng error not admitting nullable DateTime

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | react |
| System | Windows 10 Pro 22H2 |
| Browser | Google Chrome 124.0.6367.119 (Build oficial) (64 bits) |

**Comment by afc163** [comment]
<img width="712" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/96c5ef60-a132-4458-b227-a2df7dcfeac0">

**Comment by jonmurciano** [comment]
Hello, I've already solved the access to codesandbox.

**Comment by afc163** [comment]
How could I reproduce the type error?

<img width="1782" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/9776b8ae-551b-4749-847b-9d0eccb0024b">

**Comment by pabloimrik17** [comment]
Hi, we are having some problems trying to import LuxonGenerateConfig from rc-picker in the sandbox.

This is our situtation after 5.14.

We are creating a Datepicker based on Luxon following your guide

https://ant.design/docs/react/use-custom-date-library/

![image](https://github.com/ant-design/ant-design/assets/5611863/d928ddf5-b8fe-43d5-87c6-5e1eb032cc2e)
![image](https://github.com/ant-design/ant-design/assets/5611863/7956f23e-49b5-4dc6-81a1-3fff63b99cbc)

Based on that we create our picker wrapper component, empty as showed below, nothing custom yet
![image](https://github.com/ant-design/ant-design/assets/5611863/e8721eab-47a9-409b-8f2a-4df5aaafce07)

Now the onChange event in your types is missing | null.

![image](https://github.com/ant-design/ant-design/assets/5611863/9dbe7ff7-5615-44f1-956d-3cf3d2d7cbe4)

onChange type from 5.14

![image](https://github.com/ant-design/ant-design/assets/5611863/9e43102e-7f27-4f18-b66d-39f2fe07e0fa)

before to 5.14 

![image](https://github.com/ant-design/ant-design/assets/5611863/5f03546b-6d70-4b76-81a8-def650b4ba67)

**Comment by afc163** [comment]
Could you reproduce it in your codesandbox?

**Comment by pabloimrik17** [comment]
Sorry guys, after reviewing the error was a little mistake on our side. Closing the issue

Thank for your time
