### ISSUE TITLE
Collapse item content overflow inside a wrapper with defined height

### ISSUE THREAD

**Issue by orelHAnyvision** [ant-design/ant-design#48769]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-em1bwa-vrczzz?file=demo.tsx)

### Steps to reproduce

wrap Collapse component with element with defined height
add item with greater text height then wrapper

### What is expected?

the content of the collapse item will be scrollable - not the entire collapse component

### What is actually happening?

the content overflow out of the collapse component

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18 |
| System | macOS Sonoma 14.3.1 |
| Browser | Chrome |

**Comment by orelHAnyvision** [comment]
https://github.com/ant-design/ant-design/issues/48767
as for this 
`
See https://stackblitz.com/edit/react-em1bwa-pkrept?file=demo.tsx

You should add overflow: auto; to the same element with limit height which the maxHeight style is assigned.

`

this doesn't solve the issue because the scroll is all over the collapse component. i only want it to be for the content of the items

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-em1bwa-cy96qg?file=demo.tsx
