### ISSUE TITLE
Antd reset.css is not imported when using as layer 

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#48762]
### Reproduction link

[https://ant.design/docs/react/compatible-style#layer-downgrade](https://ant.design/docs/react/compatible-style#layer-downgrade)

### Steps to reproduce

following the doc and added the following code:

Order of style precedence Tailwind -> reset css -> antd

@layer tailwind-base,
reset,
antd;
@layer tailwind-base {
    @tailwind base;
}

@import url('antd/dist/reset.css') layer(reset);
@tailwind components;
@tailwind utilities;

### What is expected?

Expect that style layer are applied and style overwrite appropriately

### What is actually happening?

Reset css style is not being applied at all

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.2 |
| System | web |
| Browser | chrome |

**Comment by AsuraKev** [comment]
Able to see Layer tailwind and antd being applied but Layer reset is missing 

![image](https://github.com/ant-design/ant-design/assets/52765572/ee6cdf27-0d5d-41d6-a1d0-9d1ea5096759)

**Comment by AsuraKev** [comment]
Or tried import reset css first but antd styles are being overwritten by reset even the order specified is correct

![image](https://github.com/ant-design/ant-design/assets/52765572/b82be463-bd27-4530-bd2c-2fdbfe25368e)
![image](https://github.com/ant-design/ant-design/assets/52765572/83a732ba-259f-4be0-b092-bd33a29f7009)

**Comment by AsuraKev** [comment]
other issue is that even removing the need for reset.css. The tailwind style seems to be overriding antd style
![image](https://github.com/ant-design/ant-design/assets/52765572/bc9835dc-54a8-4138-bef9-56157cb73eb7)
![image](https://github.com/ant-design/ant-design/assets/52765572/f1c76296-4a7d-4d90-9cb9-d15c33108def)

**Comment by afc163** [comment]
@AsuraKev Did you resolve it? Why did you close this issue?

**Comment by AsuraKev** [comment]
Hi. Yes, after restarting the solution it worked as expected. The reset css import has to come last otherwise tailwind still overrides even if you defined the order as @layer tailwind-base, reset, antd

thanks
