### ISSUE TITLE
Collapse item content overflow inside a wrapper with defined height

### ISSUE THREAD

**Issue by orelHAnyvision** [ant-design/ant-design#48767]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-em1bwa?file=demo.tsx)

### Steps to reproduce

wrap Collapse component with element with defined height
add item with greater text height then wrapper

### What is expected?

the content of the collapse item will be scrollable

### What is actually happening?

the content overflow out of the collapse

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18 |
| System | macOS Sonoma 14.3.1 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-em1bwa-pkrept?file=demo.tsx
