### ISSUE TITLE
Select with maxTagPlaceholder render content in tag instead of just render

### ISSUE THREAD

**Issue by orelHAnyvision** [ant-design/ant-design#48773]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-hkorld?file=demo.tsx)

### Steps to reproduce

use Select component with maxTagPlaceholder prop and render something

### What is expected?

whatever you render will render and override the default behavior

### What is actually happening?

whatever you render is rendered inside a built in tag without option to override it

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | 18 |
| System | macOS Sonoma 14.3.1 |
| Browser | Chrome |

**Comment by afc163** [comment]
I don't really get the problem. What is the different between expected behaviors and reality?

**Comment by orelHAnyvision** [comment]
@afc163 
Sorry maybe I didn't describe it well enough.
I would expect this code to render the tags and when it reach to max it will render just <div>test</div>

```
 <Select
        {...sharedProps}
        {...selectProps}
        maxTagPlaceholder={(omittedValues) => <div>test</div>}
      />

```

what happens is that <div>test</div> is rendered inside a Tag which I didn't define and I cant control
![Uploading Screenshot 2024-05-06 at 9.14.12.png…]()

**Comment by afc163** [comment]
Still confused, the screenshot is broken.

**Comment by orelHAnyvision** [comment]
@afc163 
![Screenshot 2024-05-06 at 9 14 12](https://github.com/ant-design/ant-design/assets/88976179/bda1aa52-7010-4147-b520-c38e54b92bdf)

**Comment by afc163** [comment]
That is a intented behaviour, what is your expectation.

**Comment by orelHAnyvision** [comment]
@afc163 
to display what we render in maxTagPlaceholder without wrapping it with something.
The problem with the current behavior is that if I want to modify the tagRender prop and render a tag with a preferred color and I want the design to be consistent I'm not able with the current implementation.

```
<Select
...
 tagRender={(props) => (
        <Tag color='red' style={{ fontSize: 12 }} bordered={false} {...props}>
          {props.label}
        </Tag>
      )}
 maxTagPlaceholder={(omittedValues) => <div>more</div>}
```

there is no way for me to set the 'more' with `color='red'`

**Comment by afc163** [comment]
So the real problem is that `tagRender` is not working on the max tag in https://stackblitz.com/edit/react-hkorld-vqpmy6?file=demo.tsx , right?

| Expected ✅ | Now ❌ |
| --- | --- |
| <img width="349" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/7baadcc4-7c61-4a2e-be1a-186e80c1d4f3"> | <img width="338" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/5da6ef82-a492-44be-93fe-2d8d141c2b99"> |

**Comment by afc163** [comment]
The same issue: https://github.com/ant-design/ant-design/issues/32072

**Comment by orelHAnyvision** [comment]
@afc163 
well, yes and no.
Same issue for this specific case when we want it to be just like the tagRender.
Not same because I could say that I want to render other element which is not related to the tagRender prop

**Comment by orelHAnyvision** [comment]
@afc163 
btw, I didn't see any solution for it here https://github.com/ant-design/ant-design/issues/32072 ?

**Comment by afc163** [comment]
Not yet

**Comment by orelHAnyvision** [comment]
@afc163 
I believe that quicker solution would be just render what we use.
`maxTagPlaceholder={(omittedValues) => <div>more</div>}`
will just render `<div>more</div>`. I guess its just condition in the source code to check whether maxTagPlaceholder provided to just render whats inside it without any wrapper.
This issue it from 2021....

**Comment by afc163** [comment]
>  I believe that quicker solution would be just render what we use.

We can't simply change this, it would be a break change for existed usage.

**Comment by orelHAnyvision** [comment]
@afc163 
maybe we could add it with another prop(boolean) to verify it

**Comment by afc163** [comment]
After https://github.com/react-component/select/pull/1044 and https://github.com/ant-design/ant-design/pull/48798 , `tagRender` will work on max tag. You can tell selected item and max tag with `isMaxTag` in `tagRender`: https://github.com/react-component/select/pull/1044/files#diff-df9117fd81d702ef2b519d89ae1f9304a648fa6bf1f06701b86a2ea6c31bda73R133
