### ISSUE TITLE
flex 布局下 card tabs 加载异常

### ISSUE THREAD

**Issue by KewenCode** [ant-design/ant-design#48775]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jfcddn?file=%2Findex.js%3A39%2C21)

### Steps to reproduce

1.构建页签内含icon的card
2.使用flex包裹

### What is expected?

正常显示

### What is actually happening?

页签不正常闪动

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18 |
| System | win10 |
| Browser | Edge124.0.2478.80 |

---
触发条件：
1、不设定card宽度
2、有两个带icon页签
3、在flex包裹下

**Comment by wanpan11** [comment]
你这个demo看不出有啥问题，可以提供下视频撒的

**Comment by KewenCode** [comment]
> 你这个demo看不出有啥问题，可以提供下视频撒的

![PixPin_2024-05-06_10-31-23](https://github.com/ant-design/ant-design/assets/93240221/c5e3a582-cf62-4a2e-ae3a-581966be54b7)
gif反应的闪动速度比较慢，实际显示的时候闪动很快

**Comment by wanpan11** [comment]
看着像是 tabs 的问题

**Comment by afc163** [comment]
Duplicate of #48678

**Comment by wanpan11** [comment]
@KewenCode 你的例子里 antd 是 v4 还是 v5 呢

**Comment by KewenCode** [comment]
V5.17.0-------- 原始邮件 --------发件人： Wanpan ***@***.***>日期： 2024年5月7日周二 12:41收件人： ant-design/ant-design ***@***.***>抄送： KewenCode ***@***.***>, Mention ***@***.***>主    题： Re: [ant-design/ant-design] flex 布局下 card tabs 加载异常 (Issue #48775)
@KewenCode 你的例子里 antd 是 v4 还是 v5 呢

**Comment by KewenCode** [comment]
> @KewenCode 你的例子里 antd 是 v4 还是 v5 呢

最新V5.17.0
