### ISSUE TITLE
antd的官网的Menu导航菜单之“切换菜单类型”例子的当前展开项的显示问题

### ISSUE THREAD

**Issue by zlh314159** [ant-design/ant-design#4877]
[

#### Environment(required)

- antd version: 官网最新版
- OS and its version:
- Browser and its version:

#### What happen?

1. 页面刷新完成时，由于设置了defaultOpenKeys={['sub1']}，所以默认展开sub1菜单，当把mode切换到vertical时，展开项菜单仍旧显示在菜单栏右侧；
![111](https://cloud.githubusercontent.com/assets/20410949/22961868/3a5ddfd2-f384-11e6-8afa-3b04f4fb95f3.png)

期望结果是：首次页面渲染完成时，将mode切换到vertical时，展开项菜单不显示在菜单栏右侧；只有当鼠标滑过一级菜单时，才能在右侧显示其子菜单展开项

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/4876

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by afc163** [comment]
http://codepen.io/anon/pen/GreNNj?editors=1010

**Comment by afc163** [comment]
I think this is correct.

When you set `defaultOpenKeys`, it meanings to set a initial open state to menu. And changing mode will never affect the open state, so sub menu will still be open.

You can use `openKeys` to control the state.

**Comment by zlh314159** [comment]
## If `defaultOpenKeys ` and `openKeys`  exist at the same time, defaultOpenKeys  doesn't work.
[http://codepen.io/wmzy/pen/oBVbQO?editors=1010]

**Comment by zlh314159** [comment]
可受控菜单组件Menu在垂直模式下，子菜单没有弹出，onOpenChange方法也未被执行:
效果如下图：
![222](https://cloud.githubusercontent.com/assets/20410949/22968791/d2cc2158-f3a6-11e6-9ed6-7f478cbf52ad.png)

代码如下：
`
import React, { createClass } from 'react';
import Page from '/components/Page';

import { Menu, Icon } from 'antd';
const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;

let Component = createClass({
	getInitialState() {
		return {
			openKeys: [],
		};
	},
	
	onOpenChange(openKeys) {
		this.setState({
			openKeys,
		});
	},
	
	render() {
		console.log(this.state.openKeys);
		return (
			<Menu
				mode="vertical"
				**openKeys={this.state.openKeys}
				onOpenChange={this.onOpenChange}**
			>
				<SubMenu key="sub1" title={<span><Icon type="mail" /><span>Navigation One</span></span>}>
					<MenuItemGroup title="Item 1">
						<Menu.Item key="1">Option 1</Menu.Item>
						<Menu.Item key="2">Option 2</Menu.Item>
					</MenuItemGroup>
					<MenuItemGroup title="Iteom 2">
						<Menu.Item key="3">Option 3</Menu.Item>
						<Menu.Item key="4">Option 4</Menu.Item>
					</MenuItemGroup>
				</SubMenu>
				<SubMenu key="sub2" title={<span><Icon type="appstore" /><span>Navigation Two</span></span>}>
					<Menu.Item key="5">Option 5</Menu.Item>
					<Menu.Item key="6">Option 6</Menu.Item>
					<SubMenu key="sub3" title="Submenu">
						<Menu.Item key="7">Option 7</Menu.Item>
						<Menu.Item key="8">Option 8</Menu.Item>
					</SubMenu>
				</SubMenu>
				<SubMenu key="sub4" title={<span><icon type="setting" /><span>Navigation Three</span></span>}>
					<Menu.Item key="9">Option 9</Menu.Item>
					<Menu.Item key="10">Option 10</Menu.Item>
					<Menu.Item key="11">Option 11</Menu.Item>
					<Menu.Item key="12">Option 12</Menu.Item>
				</SubMenu>
			</Menu>
		);
	}
});

export default Page(Component);`

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/4876
