### ISSUE TITLE
Modal对话框组件中是否可以提供类似Drawer抽屉组件中loading属性

### ISSUE THREAD

**Issue by zangnan** [ant-design/ant-design#48777]
### What problem does this feature solve?

5.17.0中，增加了Drawer组件loading属性。是否可以在弹窗中也增加这个属性？

### What does the proposed API look like?

loading: 显示旋转指示器  boolean

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/48848
