### ISSUE TITLE
<Card /> 组件在 small 尺寸下的卡片式页签出现多余的 border 边框

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#48781]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-trt56g)

### Steps to reproduce

查看 <Card /> 组件在 small 尺寸下已激活的卡片式页签

### What is expected?

已激活的卡片式页签下方与内容区无分割

### What is actually happening?

已激活的卡片式页签下方出现边框细线

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.3 |
| System | Windows 11 |
| Browser | Edge 124.0.2478.80 |

![屏幕截图 2024-05-06 130936](https://github.com/ant-design/ant-design/assets/46666511/3d993b8d-7b05-4cb7-a891-c2827dc7b6e6)

![屏幕截图 2024-05-06 131157](https://github.com/ant-design/ant-design/assets/46666511/fae91896-ead9-4aef-8291-4f885abd20b3)

**Comment by afc163** [comment]
Card 里 tabs 类型为 card 是未经设计的，size 不是 small 的样式也是有问题的。

**Comment by wanpan11** [comment]
small 下应该是 card-header 和 tabs的高度不一样导致的
![image](https://github.com/ant-design/ant-design/assets/38714194/4ad88b13-4298-4285-9a15-af13c6679374)
