### ISSUE TITLE
DatePicker里面的RangePicker，选择时间区域，偶现抖动问题

### ISSUE THREAD

**Issue by kkju** [ant-design/ant-design#48789]
### Reproduction link

[https://4x.ant.design/components/date-picker-cn/](https://4x.ant.design/components/date-picker-cn/)

### Steps to reproduce

 1、访问官网链接，选择 组件 ->Date picker -> 自定义状态demo -> 最后一个示例； 

 2、 先选择一个时间区域，点击清空；

 3、切换到前一个月，再选择一个月的第一天，然后快速划到月底或者下个月前几天；

 4、点击第一天时，或者鼠标滑动过程中，会出现抖动现象；

 5、偶现问题，需要多次重复。官网demo复现概率比较高，一般3-5次即可复现。

### What is expected?

1、不出现抖动。

### What is actually happening?

1、会出现抖动情况。

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | React17.0.14 |
| System | win10 |
| Browser | chrome 124.0.6367.91（正式版本） （64 位） |

抖动录制视频（7s-9s）：

https://github.com/ant-design/ant-design/assets/4352424/78ebc095-6f0a-4d75-96b8-ff8bd898c415

如果将浏览器缩小，或者将datepicker长度展示很长时，点击本月清除，然后点击上一个月，基本必现下面情况。
还会出现跑到右侧的情况：
![偶现右侧卡住](https://github.com/ant-design/ant-design/assets/4352424/103e5702-f24a-4fe1-87ba-6c4154143679)

**Comment by wanpan11** [comment]
https://ant.design/docs/blog/v4-ood-cn

**Comment by yjx-gitstar** [comment]
在时间选择器加上这段代码就好了  getPopupContainer={trigger => trigger.parentNode}
