### ISSUE TITLE
Typography.Title 不具备响应式应式布局

### ISSUE THREAD

**Issue by PolarishT** [ant-design/ant-design#48786]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/suspicious-babbage-rgxwsw?file=/src/App.tsx:3,34)

### Steps to reproduce

<Card style={{width:'80vw'}}>
        <main style={{display:'flex',flexDirection:'row',justifyContent: 'space-between'}}>
          <main style={{display:'flex',flexDirection:'column',flexGrow:6}}>
            {/*<Paragraph>*/}
            {/*  <Typography.Title editable={{onChange:handleChange,text:val,maxLength:60}} level={5} style={{ margin: 0}}  copyable={true} ellipsis={true}>*/}
            {/*    {val}*/}
            {/*  </Typography.Title>*/}
              <Progress percent={terns} type="line" showInfo={false} />
            {/*</Paragraph>*/}
          <article style={{ display: 'flex', flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'space-between' }}>
            <Text>轮次</Text>
            <Text>{terns}</Text>
          </article>
        </main>
          <main style={{flexGrow:4,display:'flex',flexDirection:'column',alignItems:'center',marginLeft:'6px'}}>
          <article
            style={{ display: 'flex', flexDirection: 'row',justifyContent:'center'}}>
            <Progress type="dashboard" percent={score} gapDegree={30} size={70} format={(percent) => `${percent}`} />
          </article>
            <Text>值</Text>
          </main>
        </main>
      </Card>

### What is expected?

支持响应式布局

### What is actually happening?

不支持响应式布局

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | 18 |
| System | macos |
| Browser | arc |

**Comment by afc163** [comment]
<img width="919" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/9e17810f-b707-4892-af4c-17f63681e1bd">
