### ISSUE TITLE
table 开启virtual 虚拟滚动后，表格dom由div生成，无法获取原td元素的 cellIndex

### ISSUE THREAD

**Issue by suckupon** [ant-design/ant-design#48785]
### What problem does this feature solve?

table 开启virtual 虚拟滚动后，表格dom由div生成，用户hover某单元格时，想要高亮该单元格所在的行与列，现在无法获取cellIndex，不知道hover单元格的列的索引

### What does the proposed API look like?

提供列索引参数

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by suckupon** [comment]
@afc163 类似如下代码中，需要获取当前hover单元格所在的行索引与列索引 （this.rowIndex，this.cellIndex），开启虚拟滚动后单元格改写为div元素了，无法获取this.rowIndex，this.cellIndex，能否提供单元格所在div元素的列索引？
  this.tableElement = document.getElementsByClassName("ant-table-body")[0]
  this.tableElement.addEventListener("mouseover",this.addClassName)
  addTdClassName(){
        console.log(this.cellIndex, this.rowIndex, ”this.cellIndex")
        if(this.className.includes("highlight")) return;
        this.parentElement.parentElement.querySelectorAll(`td:nth-child(${this.cellIndex+1})`)?.forEach(td=>{
            td.className += " highlight"
        })
    }

**Comment by afc163** [comment]
this.cellIndex 是什么？

**Comment by suckupon** [comment]
@afc163 this.cellIndex 是HTML DOM 属性 ，.cellIndex对象是<td>. 功能：返回单元格在行中的位置。语法：object.cellIndex
。说明:该属性只读，cellIndex用于判断当前单元格所处列的索引（从0开始）

**Comment by suckupon** [comment]
resolved

**Comment by afc163** [comment]
如何解决的？

**Comment by suckupon** [comment]
计算div.ant-table-cell在其父标签div.ant-table-row内的索引，即为该单元格所在列索引

**Comment by afc163** [comment]
其实最好不要依赖 dom 结构，从数据结构里去推更稳定。
