### ISSUE TITLE
Need a codepen for LocalProvider[locale=xxx]

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4879]
https://gitter.im/ant-design/ant-design?at=58a38ece1465c46a566675ca

**Comment by yesmeck** [comment]
Since codepen don't support CommonJS, if we want to use locale files on codepen, we need to build UMD files for every locale file.

**Comment by afc163** [comment]
we can export all locale file into individual file just for test.

**Comment by kesavkolla** [comment]
It would be great if we can make locale as string property and LocaleProvider internally can do reference to corresponding locale file.  This way we don't need to make any new export file for langs

**Comment by benjycui** [comment]
> It would be great if we can make locale as string property and LocaleProvider internally can do reference to corresponding locale file.

It will increase the bundle size. Because we had supported [seven languages](https://github.com/ant-design/ant-design/tree/master/components/locale-provider) now, and more languages will be supported in the future.

**Comment by benjycui** [comment]
Just use webpack's [multiple entry points](https://webpack.github.io/docs/multiple-entry-points.html)?

And generate dist files:

```bash
dist
  - locales
    - en_US
    - zh_CN
   ...
```

**Comment by benjycui** [comment]
2.7.2 published.

**Comment by yesmeck** [comment]
@benjycui 

Things need to to on http://codepen.io/benjycui/pen/KgPZrE?editors=001 

1. Change `https://unpkg.com/antd/dist/antd.js` to `https://unpkg.com/antd/dist/antd-with-locales.js`;
1. Add some instructions how to use codepen (eg: fork, how to use locale);

**Comment by afc163** [comment]
Also add some basic instructions for how to edit and fork codepen and import antd components.

**Comment by benjycui** [comment]
Here is another problem: we cannot set `moment.locale` in CodePen.

We need to expose moment in `dist/antd.js`?

**Comment by afc163** [comment]
Import moment by script.

**Comment by benjycui** [comment]
> Import moment by script.

It won't work, for the moment import by script is different from antd's moment.

http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
http://unpkg.com/moment@2.17.1/min/moment-with-locales.js

**Comment by benjycui** [comment]
Updated: http://codepen.io/benjycui/pen/KgPZrE?editors=0011
