### ISSUE TITLE
npm run pub or npm run beta 错误

### ISSUE THREAD

**Issue by TommyHili** [ant-design/ant-design#488]
ERROR in Cannot find module 'less'
 @ ./scripts/importCss.js 3:0-30

prenpm done
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/XXX/CodeHome/react/ant-design/dist/index.css'
    at Error (native)

**Comment by afc163** [comment]
你为什么要做这个事？

**Comment by yiminghe** [comment]
不需要做
