### ISSUE TITLE
CSS Var doesn't work inside `<App component={false}>`

### ISSUE THREAD

**Issue by notzheng** [ant-design/ant-design#48802]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/late-glade-n7phdh)

![Google Chrome  ScreentShot at 2024-05-07 15 43 54](https://github.com/ant-design/ant-design/assets/13414731/4d7a2308-dd8e-4bbb-8cdc-0dd55d8197c8)

### Steps to reproduce

`<App component={false}>`

### What is expected?

Maybe `--ant-*` set to `:root` ?

### What is actually happening?

There is no `--ant-*` CSS custom properties inside `<App component={false}>`.

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.x |
| System | macOS latest |
| Browser | Chrome latest |

**Comment by Wxh16144** [comment]
我觉得应该是预期的， App 组件可以自定义容器，没有容器的时候 cssvar 的 classname 没地方承载了

**Comment by notzheng** [comment]
> 我觉得应该是预期的， App 组件可以自定义容器，没有容器的时候 cssvar 的 classname 没地方承载了

~好的， 那么建议在文档中标注一下：~
~https://ant.design/docs/react/css-variables-cn~
~https://ant.design/components/app-cn~

谢谢。
