### ISSUE TITLE
[Button] Button-findDOMNode

### ISSUE THREAD

**Issue by wanpan11** [ant-design/ant-design#48809]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-zbmzv8-cdwnta?file=demo.tsx)

### Steps to reproduce

点击按钮 查看控制台

### What is expected?

无

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.3.1 |
| System | Windows |
| Browser | Chrome |

---
无

**Comment by wanpan11** [comment]
![image](https://github.com/ant-design/ant-design/assets/38714194/64a6d07d-2c0b-4859-9878-92adb81d6f53)

**Comment by zombieJ** [comment]
断点看了一下，ref 被正确填充，但是外部使用时却莫名置空了。奇怪。。。

**Comment by wanpan11** [comment]
<img width="928" alt="image" src="https://github.com/ant-design/ant-design/assets/38714194/a972a679-fa40-418e-b5e7-7e07180126fe">

好像是这里没有调用 setNodeRef  导致的
我本地加上这个调用就好了

**Comment by wanpan11** [comment]
<img width="593" alt="image" src="https://github.com/ant-design/ant-design/assets/38714194/93848a42-0ecf-49cb-adb7-da9a8e41260f">

这样好像就行了

**Comment by wanpan11** [comment]
https://github.com/ant-design/ant-design/issues/48709
