### ISSUE TITLE
Affix的事件监听为什么设置setTimeout？

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#4880]
该固定在顶端的元素跟着滚动了上去，好像是页面渲染完成后的滚动动作因为延时设置的监听失败

**Comment by RaoHai** [comment]
有 demo 么？

**Comment by qiaoyixuan** [comment]
@RaoHai 暂时无法给出demo，bug原因是包括用户滚动操作在内的渲染排在了Affix的setTargetEventListeners之前执行，导致监听失败，如果只是注册监听需要setTimeout吗？我的解决办法是在渲染结束后在setTimeout中执行scroll，这样能在setTargetEventListeners完成后执行scroll

**Comment by benjycui** [comment]
@qiaoyixuan do your mean [here](https://github.com/ant-design/ant-design/blob/588dd3033fa29a756462329d9f7ca63993d75198/components/affix/index.tsx#L180-L183)

It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by qiaoyixuan** [comment]
@benjycui yes

**Comment by benjycui** [comment]
> // Wait for parent component ref has its value

As the comment said.

**Comment by qiaoyixuan** [comment]
yes,but I don't understand,I removed the timeout and no exception happends.


发自网易邮箱大师
在2017年02月16日 09:28，Benjy Cui 写道：

// Wait for parent component ref has its value

As the comment said.

**Comment by benjycui** [comment]
If:

```jsx
<Parent ref="parent">
  <Affix target={() => this.refs.parent} />
</Parent>
```
