### ISSUE TITLE
图片插件-视频播放时，关闭弹窗，声音仍然在播放

### ISSUE THREAD

**Issue by 15607306950** [ant-design/ant-design#48818]
### Reproduction link

https://ant-design.antgroup.com/components/image-cn#image-demo-imagerender

### Steps to reproduce

点击自定义预览内容图片，打开视频渲染 点击播放，然后关闭 再点击图预览自定义预览内容图片（手速要快，因为视频只有三秒）

### What is expected?

关闭之后视频停止播放，回到播放前状态

### What is actually happening?

目前结果是 仍然还在播放

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | react |
| System | windows |
| Browser | chrome |

---
建议当前页面 加一个截图 图片，或者视频上传选项，方便快速理解，描述问题

**Comment by crazyair** [comment]
destroyOnClose

**Comment by linxianxi** [comment]
```
preview={{ destroyOnClose: true }}
```

**Comment by crazyair** [comment]
> ```
> preview={{ destroyOnClose: true }}
> ```

我搜文档，没搜到 destroyOnClose。。

**Comment by 15607306950** [comment]
还一个问题是 不支持.ts文件的视频播放吗？可否增加这个格式的支持？

**Comment by wanpan11** [comment]
我之前用的时候也是没有看到这个属性  手动搞的暂停😇

**Comment by Wxh16144** [comment]
fiexd by #48827
