### ISSUE TITLE
Anchor component inside Affix component throws "findDOMNode is deprecated in StrictMode"

### ISSUE THREAD

**Issue by luke-m** [ant-design/ant-design#48812]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-hglv96?file=%2Findex.js%3A12%2C5)

### Steps to reproduce

1. Use Anchor inside Affix
2. Check console

### What is expected?

No errors

### What is actually happening?

Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.2.0 |
| System | MacOS Sonoma 14.4.1 |
| Browser | Chrome Version 122.0.6261.112 (Official Build) (arm64) |

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/48709
