### ISSUE TITLE
引用form时报错，但是未影响运行

### ISSUE THREAD

**Issue by RaeZeva** [ant-design/ant-design#4881]
Warning: `Form.Item` cannot generate `validateStatus` and `help` automatically, while there are more than one `getFieldDecorator` in it.

代码：http://jsbin.com/zanaxalena/edit?html,js,output

**Comment by RaeZeva** [comment]
可能是我位置写的不对吧，这样改了后不报错了
http://jsbin.com/zameyexubu/1/edit?html,js,output

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.
