### ISSUE TITLE
[Tree] onCheck / onSelect are triggered when clicking on an empty space in a modal / popover / dialog opened by the tree node

### ISSUE THREAD

**Issue by martin-keeper** [ant-design/ant-design#48816]
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/controlled-tree-antd-4-24-16-forked-nss44m?file=%2Fdemo.tsx%3A64%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvwp7nvg00063b6hszmz4tkm%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvwp7nvf00023b6hspum554b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvwp7nvf00033b6h6pcnpntn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvwp7nvf00053b6h5gi0v6ka%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvwp7nvf00023b6hspum554b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvwp7nvf00013b6hnuvll9si%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvwp8e3a003z3b6hrf6zuhwj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A64%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A64%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvwp7nvf00023b6hspum554b%2522%252C%2522activeTabId%2522%253A%2522clvwp8e3a003z3b6hrf6zuhwj%2522%257D%252C%2522clvwp7nvf00053b6h5gi0v6ka%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvwp7nvf00043b6h5s5sf43v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvwp7nvf00053b6h5gi0v6ka%2522%252C%2522activeTabId%2522%253A%2522clvwp7nvf00043b6h5s5sf43v%2522%257D%252C%2522clvwp7nvf00033b6h6pcnpntn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvwp7nvf00033b6h6pcnpntn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Click on open popover in an unchecked tree node
2. Click on the divider inside the dropdown (or any place that is not a button)

### What is expected?

The checkbox should not be checked if `selectable={false}`
The row should not be selected if `selectable={true}`

### What is actually happening?

The checkbox is being checked if `selectable={false}`
The checkbox is being selected if `selectable={true}`

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 17 & 18 |
| System | Mac os |
| Browser | Chrome |

**Comment by zombieJ** [comment]
You should use stop pop to block the event bubble. All the event in the title node is bubble by default since React has it's own virtual dom tree for event bubble.
