### ISSUE TITLE
不全局引入ant样式的话打包后发布到线上ant的样式全部丢了

### ISSUE THREAD

**Issue by jie123js** [ant-design/ant-design#48826]
### Reproduction link

[http://172.16.19.67:11051/](http://172.16.19.67:11051/)

### Steps to reproduce

具体就是很奇怪,本地我没有全局引入样式是没问题的,公司测试环境部署也是没问题的,但是发布到内网后ant的样式全丢了,最后我必须全局import 'antd/dist/antd.css'加了这个后样式才出来,这个url你们访问不了的 内网的

### What is expected?

如果不需要全局引入,打包应该出现ant的样式

### What is actually happening?

没有全局引入import 'antd/dist/antd.css',的话,打包后发布到内网环境的线上样式就没了,只是ant的样式没了,基础的CSS样式是有的,很奇怪普通的环境不用全局引入也是好的,但是内网如果不加这个就出不来

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2 |
| System | window |
| Browser | 都是最新版本的 |

---
我只是就提问一下 到底需要全局引入这个样式吗,我看文档,文档好像都是按需加载都没写要import 'antd/dist/antd.css',

**Comment by crazyair** [comment]
使用什么脚手架？提供最小复现仓库

**Comment by jie123js** [comment]
> `import 'antd/dist/antd.css'`? 你这是还在用的 4.x 吧
create-react-app 实际项目中是不需要这行代码的 但是打包上线不加的话样式就全丢了 测试环境是不丢的 内网环境就不行
是5.0

**Comment by crazyair** [comment]
<img width="1182" alt="image" src="https://github.com/ant-design/ant-design/assets/7971419/f667d0f9-7f16-4223-af6f-67889fee675e">

我 build 后，用 serve build 启动编译文件，打开的是能看到样式的

**Comment by crazyair** [comment]
<img width="1720" alt="image" src="https://github.com/ant-design/ant-design/assets/7971419/dc1ca1a0-448a-431a-86b3-142ed52d5233">

**Comment by jie123js** [comment]
> <img alt="image" width="1720" src="https://private-user-images.githubusercontent.com/7971419/328880920-dc1ca1a0-448a-431a-86b3-142ed52d5233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzAyMzUsIm5iZiI6MTcxNTE2OTkzNSwicGF0aCI6Ii83OTcxNDE5LzMyODg4MDkyMC1kYzFjYTFhMC00NDhhLTQzMWEtODZiMy0xNDJlZDUyZDUyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTIwNTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU0MGQ4N2Y4ZTVhYjgwODU1NjhmOThjYjkwYmYyMGQ3OTdlZjNjZDFiY2FlMzIyZTA5ZTEyMjM1NDRiMjE0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kI1zZCGgJ9W5qB3EmHP8DXzc39290dsVkIqi7rXtQck">

现在我仓库的代码打包后 不管我加不加import 'antd/dist/antd.css serve都是可以的  就是内网环境就必须加这个才可以,我是好奇这个问题, 问题是已经解决了就是加上import 'antd/dist/antd.css就可以,但是就是说 文档里面也没说要加这个,不加可能会导致打包后出现ant样式丢失的问题 就是想知道原因是啥

**Comment by afc163** [comment]
antd 5.0 中都不存在 `antd/dist/antd.css` 这个文件，你这个解法明显是不合理的。

**Comment by crazyair** [comment]
antd v5没有这个 css 文件，我运行时候报错了，我注释了。

**Comment by afc163** [comment]
@jie123js 请给出重现步骤吧。

**Comment by jie123js** [comment]
> > <img alt="image" width="1720" src="https://private-user-images.githubusercontent.com/7971419/328880920-dc1ca1a0-448a-431a-86b3-142ed52d5233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzAyMzUsIm5iZiI6MTcxNTE2OTkzNSwicGF0aCI6Ii83OTcxNDE5LzMyODg4MDkyMC1kYzFjYTFhMC00NDhhLTQzMWEtODZiMy0xNDJlZDUyZDUyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTIwNTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU0MGQ4N2Y4ZTVhYjgwODU1NjhmOThjYjkwYmYyMGQ3OTdlZjNjZDFiY2FlMzIyZTA5ZTEyMjM1NDRiMjE0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kI1zZCGgJ9W5qB3EmHP8DXzc39290dsVkIqi7rXtQck">
> 
> 现在我仓库的代码打包后 不管我加不加import 'antd/dist/antd.css serve都是可以的 就是内网环境就必须加这个才可以,我是好奇这个问题, 问题是已经解决了就是加上import 'antd/dist/antd.css就可以,但是就是说 文档里面也没说要加这个,不加可能会导致打包后出现ant样式丢失的问题 就是想知道原因是啥



> antd 5.0 中都不存在 `antd/dist/antd.css` 这个文件，你这个解法明显是不合理的。



> antd v5没有这个 css 文件，我运行时候报错了，我注释了。

那真是奇了怪了  

> antd v5没有这个 css 文件，我运行时候报错了，我注释了。

你的意思是说 你特地注释了import 'antd/dist/antd.css'这行代码才能运行吗  我看我的package.json 版本没错啊 为什么会这样 能加你个V之类给你发点图吗

**Comment by jie123js** [comment]
> @jie123js 请给出重现步骤吧。

具体的可以用这2张打包后的图给你们看看
![微信截图_20240508202323](https://github.com/ant-design/ant-design/assets/70522802/b2aa624e-de50-43cf-bf1f-35253e072f40)
这个是加了import 'antd/dist/antd.css'  
然后下面不加的话是这样的
这个解压出来的CSS里面没有ant样式
![Uploading 微信图片_20240508202436.png…]()

**Comment by afc163** [comment]
请给出一步一步的重现步骤，帮助我们本地也能搭建出无法看到样式的页面。

**Comment by jie123js** [comment]
> 请给出一步一步的重现步骤，帮助我们本地也能搭建出无法看到样式的页面。
> 
> 你给的 gitee 仓库里我们是没有重现出来的。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)

我给的仓库是好的,是复现不出来的,这个问题主要我是想问为啥我不加import 'antd/dist/antd.css'这句话打包 发布到线上会有差异,有的线上样式(公司搭的测试环境)可以加载出来(不用加导入也可以加载出来),有的线上环境(甲方的内网环境)样式加载不出来必须加了这句话后才把样式打包进去(没加打包3.5M,加了打包3.7M)                     问题其实是已经解决了 我是想看看有没有人遇到一样的问题

**Comment by crazyair** [comment]
首先 antd v5 没有这个  css，具体你说加上能用，估计是哪个环节有 antd v4 的依赖吧？具体需要你自己排查了。可以打印 version 看下运行的 antd 版本

**Comment by jie123js** [comment]
> 首先 antd v5 没有这个 css，具体你说加上能用，估计是哪个环节有 antd v4 的依赖吧？具体需要你自己排查了。可以打印 version 看下运行的 antd 版本

我打印版本是5的呀 package.json里面和lock里面都是5 
![image](https://github.com/ant-design/ant-design/assets/70522802/84b2df10-55c3-40bd-87f9-f01b6a8c0940)

**Comment by afc163** [comment]
没有重现的话，我们也猜不出来什么原因。如果需要手动 import antd/dist/antd.css 样式才能生效的话，那一定是用了 antd 4 而不是 antd 5，因为 antd 5 没有这个文件。

**Comment by Chasen-Zhang** [comment]
可能是本地和线上的 antd 版本不一致导致的 @jie123js
