### ISSUE TITLE
图片-视频播放格式不支持.ts后缀视频文件播放

### ISSUE THREAD

**Issue by 15607306950** [ant-design/ant-design#48823]
### Reproduction link

[https://ant-design.antgroup.com/components/image-cn](https://ant-design.antgroup.com/components/image-cn)

### Steps to reproduce

视频文件后缀为.ts文件，无法播放

### What is expected?

希望能支持多格式播放

### What is actually happening?

目前不支持

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by crazyair** [comment]
https://ant-design.antgroup.com/components/image-cn#image-demo-imagerender 这个是渲染 video，能不能播放是 video 的问题吧？

**Comment by 15607306950** [comment]
> https://ant-design.antgroup.com/components/image-cn#image-demo-imagerender这是渲染视频，能不能播放是视频的问题吧？
视频文件格式做转换？

**Comment by MadCcc** [comment]
这个与 antd 无关，demo 只用作示例，可以自行修改
