### ISSUE TITLE
当页面刷新时upload.Dragger 组件内的icon会颜色变化

### ISSUE THREAD

**Issue by jzyhahahah** [ant-design/ant-design#48825]
### Reproduction link

[https://ant-design.antgroup.com/components/upload-cn](https://ant-design.antgroup.com/components/upload-cn)

### Steps to reproduce

在官方文档上找到upload.Dragger，页面刷新即可看到icon颜色变化

### What is expected?

页面刷新时，icon不变色

### What is actually happening?

页面刷新时，icon变色

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 17.0.2 |
| System | Ubuntu |
| Browser | Chrome & Edge |

**Comment by jzyhahahah** [comment]
![20240508-174110](https://github.com/ant-design/ant-design/assets/106150873/9b84b904-9c97-4f3c-8584-27cd463c4e74)

**Comment by afc163** [comment]
@jzyhahahah 看看现在问题还在么

**Comment by afc163** [comment]
重新部署后已修复。
