### ISSUE TITLE
TimePicker.RangePicker需要点分别点start的确定和end的确定

### ISSUE THREAD

**Issue by zxq08** [ant-design/ant-design#48820]
### Reproduction link

[https://ant-design.antgroup.com/components/time-picker-cn#time-picker-demo-range-picker](https://ant-design.antgroup.com/components/time-picker-cn#time-picker-demo-range-picker)

### Steps to reproduce

选择开始时间后直接选择结束时间，然后点击确定，不会保存选中结果

### What is expected?

按重现步骤操作后应该正确选中结果，参考5.12.0及以前版本

### What is actually happening?

不会保存选中结果，与5.12.0及以前版本表现不一致，且与日期选择的范围选择变现不一致

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.0.0 |
| System | MacOS 13.6.1 (22G313) |
| Browser | 124.0.6367.60（正式版本） (x86_64) |

**Comment by wangfangxuedaima** [comment]
选择开始时间后直接选择结束时间，然后点击确定，不会保存选中结果
在官网示例 可以复现此问题

**Comment by MadCcc** [comment]
以前的是 bug，如果不需要点 确认 可以使用 `needConfirm={false}`

**Comment by zxq08** [comment]
> 以前的是 bug，如果不需要点 确认 可以使用 `needConfirm={false}`

我不太了解你们怎么定性为bug的哈，我这边使用antd几年了，从4.x开始就是这样的，很多用户都已经习惯了这样的用法😭 这样断崖式的更新不太合理吧。
另外`needConfirm={false}`时，选择开始、结束后失焦，下拉框会弹回开始时间，这也是预期内的吗？😓
而4.x以及5.13以前不会时，可以参考4.x的demo
https://4x-ant-design.antgroup.com/components/time-picker-cn/#components-time-picker-demo-range-picker

**Comment by MadCcc** [comment]
那确实是 bug，Duplicate of https://github.com/ant-design/ant-design/issues/48623

**Comment by zxq08** [comment]
> 那确实是 bug，Duplicate of #48623 ，Trace 这个

好的 感谢回复！
