### ISSUE TITLE
RangePicker组件picker为month,value有默认值和没有默认值的时候，disableDate设置的是否可选月份有差别。

### ISSUE THREAD

**Issue by xuechao215** [ant-design/ant-design#48835]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-51b56t?file=demo.tsx)

### Steps to reproduce

value设置为当前月和设置为[]的时候，可选月份不一样

### What is expected?

当value有默认值的时候，选择了月份后可以选择当前月份不超过2个月的月份

### What is actually happening?

当value为空的时候可以，value有值的时候最大可选月份就会少一个月

| Environment | Info |
| --- | --- |
| antd | 5.15.4 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
duplicated of https://github.com/ant-design/ant-design/issues/48590#issuecomment-2078978306

看来怎么给月份做对比得写个 Demo 到文档里……
