### ISSUE TITLE
modal.confirm支持拖拽

### ISSUE THREAD

**Issue by lgz5689** [ant-design/ant-design#48837]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-q44yy4?file=%2Findex.js%3A46%2C5)

### Steps to reproduce

点击按钮，首次弹出对话框，拖拽是没有效果

### What is expected?

点击按钮，首次弹出对话框，拖拽正常

### What is actually happening?

首次弹出对话框，拖拽是没有效果

| Environment | Info |
| --- | --- |
| antd | 5.6.0 |
| React | 18.2 |
| System | mac |
| Browser | 124.0.6367.119（正式版本） (arm64) |

---
打印onStart的uiData，每次传递的都是上次的结果。打开过一次后，后面的都正常，刷新网页可以复现。

**Comment by afc163** [comment]
<img width="1782" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/8615fb2c-0cc0-4bcc-98e5-4cfcb72bb288">

**Comment by lgz5689** [comment]
> <img alt="图片" width="1782" src="https://private-user-images.githubusercontent.com/507615/329190986-8615fb2c-0cc0-4bcc-98e5-4cfcb72bb288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDY4NDYsIm5iZiI6MTcxNTI0NjU0NiwicGF0aCI6Ii81MDc2MTUvMzI5MTkwOTg2LTg2MTVmYjJjLTBjYzAtNGJjYy05OGU1LTRjZmNiNzJiYjI4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwOTIyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWVlNTFlZTc1ZjRkOTcwMWY0NjgxNjQwNDgyYjE5MjUwM2I5ZDRkNDZkZGM4ZWZmOTEwNGE1Y2FhZGJkODk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7C493Bu-zQL8eTU6UzYTLR1Sd5RtQWC2hKvabhR1dQU">

https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-q44yy4?file=%2Findex.js

**Comment by wanpan11** [comment]
应该是拖拽的逻辑有问题哈 

![image](https://github.com/ant-design/ant-design/assets/38714194/1a1b7920-ae93-4a44-a892-9e39e435a0cd)

**Comment by lgz5689** [comment]
https://ant-design.antgroup.com/components/modal-cn#components-modal-demo-modal-render

我是参考官网的写法 拖拽相关的逻辑是一样 只是使用了api来进行打开Modal

**Comment by lgz5689** [comment]
![image](https://github.com/ant-design/ant-design/assets/59052025/7462e36e-0ac8-4133-8d8c-6d91ab7a33b9)

这样修改后，可以发现每次执行onStart，都只会打印上一次的uiData，这里是否产生了闭包陷阱？

**Comment by wanpan11** [comment]
可以仔细看下 https://github.com/react-grid-layout/react-draggable 的文档，onStart 的触发时机就是这样的

![image](https://github.com/ant-design/ant-design/assets/38714194/6c0571e3-57bd-4906-aef5-def94f5d309e)

**Comment by lgz5689** [comment]
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-q44yy4?file=%2Findex.js%3A12%2C41
我最终发现 打开modal之后  使用的一直是打开modal时的state 这个我该如何解决

**Comment by wanpan11** [comment]
这个问题跟 modal  没关系，你应该去看看拖拽相关的文章

**Comment by MadCcc** [comment]
确实会有闭包问题，把 Draggable 封装到另一个组件里，不要在 confirm 的 function 里传入 onStart 这些 handler

**Comment by wanpan11** [comment]
这样是可以的 

```js
import ReactDOM from "react-dom";
import React, { useRef, useState } from "react";
import { Modal } from "antd";
import Draggable from "react-draggable";
import "antd/dist/reset.css";
import "./index.css";

const Comp = ({ modal }: any) => {
  const draggleRef = useRef(null);

  const [bounds, setBounds] = useState({
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  });

  const onStart = (_event: any, uiData: any) => {
    const { clientWidth, clientHeight } = window.document.documentElement;
    const targetRect = draggleRef.current?.getBoundingClientRect();
    if (!targetRect) {
      return;
    }
    console.log({
      left: -targetRect.left + uiData.x,
      right: clientWidth - (targetRect.right - uiData.x),
      top: -targetRect.top + uiData.y,
      bottom: clientHeight - (targetRect.bottom - uiData.y),
    });
    setBounds({
      left: -targetRect.left + uiData.x,
      right: clientWidth - (targetRect.right - uiData.x),
      top: -targetRect.top + uiData.y,
      bottom: clientHeight - (targetRect.bottom - uiData.y),
    });
  };

  return (
    <Draggable
      bounds={bounds}
      nodeRef={draggleRef}
      onStart={(event, uiData) => onStart(event, uiData)}
    >
      <div ref={draggleRef}>{modal}</div>
    </Draggable>
  );
};

const useMergeModal = () => {
  const { confirm } = Modal;

  const showMergeModal = () => {
    const current = confirm({
      onOk: () => {
        current.destroy();
      },
      modalRender: (modal) => <Comp modal={modal} />,
    });
  };

  return {
    showMergeModal,
  };
};

const App = () => {
  const { showMergeModal } = useMergeModal();
  return (
    <div>
      <button onClick={showMergeModal}>api modal</button>
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));

```

**Comment by joebnb** [comment]
i see...
Draggable 有个入参数是 handler ，会比antd官方的用起来好一点

like
```js
 <Draggable handle='.handler' bounds={bounds} onStart={(event, uiData) => onStart(event, uiData)}>
        <div ref={draggleRef}>{content}</div>
</Draggable>
```

在content 的div中确保 classname 存在 handler
