### ISSUE TITLE
Importing the components from `antd/lib/*` ignores the current configured algorithm theme

### ISSUE THREAD

**Issue by sawa-ko** [ant-design/ant-design#48852]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fast-flower-jyh2k9)

### Steps to reproduce

1. Create a React project
2. Import a component using “antd” (import { } from "antd").
3. Import the same component but now from “antd/lib” (import X from "antd/lib/X/X").
4. See how the component imported from antd/lib does not respect the color of the algorithm but the component imported from “antd” does.

### What is expected?

That both components respect the color theme of the algorithm configured in the application.

### What is actually happening?

The component that is imported from “antd” does work with the ConfigProvider component and the theme algorithm configuration, but the component imported from “antd/lib” does not, and uses the default algorithm all the time.

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Microsoft Edge Versión 124.0.2478.80 |

**Comment by zombieJ** [comment]
It's all deps on your **build framework** to decide what module will use. You should not import sub folder directly.

**Comment by sawa-ko** [comment]
@zombieJ So how should I use the typography component for example in nextjs? Since I can't use Typography.Text in a server component, and I don't want to make a client component just to use that component.

**Comment by sawa-ko** [comment]
Importing from `antd/es` seems to work correctly.

```diff
-import Title from 'antd/lib/typography/Title';
+import Title from 'antd/es/typography/Title';
```
