### ISSUE TITLE
Dropdown 嵌套按钮，使用button的封装组件，无效

### ISSUE THREAD

**Issue by neilniu888** [ant-design/ant-design#48859]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-79g9hy)

### Steps to reproduce

const CommonDropDown: React.FC<CommonDropDownProps> = (props) => {
  const menu: MenuItemType[] = props.menu.map( item => ({
    key: item.key,
    icon: item.icon ,
    disabled: item.disabled,
    danger: item.danger,
    label: <div style={ item.style } onClick={(e)=>{
      // e.stopPropagation()//阻止事件冒泡
      item.onClick ? item.onClick(e, props.record): '' }
    }
    >{item.label}</div>
  }
  ))
  return <Dropdown menu={{ items: menu }}>
     <CommonButton onClick={(e) => console.log('CommonButton clicked', e)}> {props.label} <DownOutlined />
    </CommonButton>
  </Dropdown>
}

export default CommonDropDown  
const CommonButton: React.FC<CommonButtonProps> = (props) => {
  return (
    <Button
      type={props.btnType}
      htmlType={props.htmlType}
      style={props.style}
      onClick={props.onClick}
      loading={props.loading}
      disabled={props.disabled}
    >
      { props.children || <>{ props.icon }{props.btnText}</> }
    </Button>
  )
}

export default CommonButton

### What is expected?

和正常使用button保持一致，

### What is actually happening?

按钮无效

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
Your reproduce is private.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15909
