### ISSUE TITLE
【Modal】期望Modal的onCancel只操控footer的点击事件 推出onClose来控制右上角的关闭icon

### ISSUE THREAD

**Issue by Richard-Zhang1019** [ant-design/ant-design#48854]
### What problem does this feature solve?

部分场景footer的取消按钮不只是关闭Modal 会有其他的事件 在onCancel绑定事件后右上角的关闭icon也会被绑定这个事件 而期望状态 是右上角依旧为关闭事件 目前是支持不了 需要手动的去自己渲染footer的button

![image](https://github.com/ant-design/ant-design/assets/76982270/16290f87-df7a-40fa-9d78-078b87cb1691)

### What does the proposed API look like?

添加onClose Api来支持右上角的关闭 如果没有单独使用onClose则依旧保持原有逻辑 方便兼容老的逻辑

**Comment by zombieJ** [comment]
直接自定义 footer 就行了：

Demo: [[自定义页脚](https://ant-design.antgroup.com/components/modal-cn#components-modal-demo-footer)](https://ant-design.antgroup.com/components/modal-cn#components-modal-demo-footer)

**Comment by afc163** [comment]
> 部分场景footer的取消按钮不只是关闭 Modal 会有其他的事件

- 建议用自定义 Footer。
- 也可以用 `e.currentTarget` 来区分是点了哪里。

```
  const handleCancel = (e) => {
    console.log(e.currentTarget);
  };
```
