### ISSUE TITLE
AutoComplete 修改默认输入框后status不生效

### ISSUE THREAD

**Issue by AmberSanyu** [ant-design/ant-design#48864]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ant-test-hhlkmd?file=%2Fsrc%2Findex.js)

### Steps to reproduce

        {/* 有问题的 */}
          <AutoComplete
            style={{ width: "200px" }}
            allowClear
            options={options}
            status={status}
            value={value}
            onChange={this.onChange}
          >
            <Input.TextArea rows={2} />
          </AutoComplete>
          {/* 没问题的 */}
          <AutoComplete
            style={{ width: "200px" }}
            allowClear
            options={options}
            status={status}
            value={value}
            onChange={this.onChange}
          ></AutoComplete>

### What is expected?

AutoComplete的status属性不因为写了children或子组件后失效

### What is actually happening?

AutoComplete的status属性写了children或子组件后失效

| Environment | Info |
| --- | --- |
| antd | 5.15.0 、5.17 |
| React | 17/18 |
| System | macOS Sonoma 14.2 |
| Browser | 123.0.6312.107 |

**Comment by coderz-w** [comment]
![image](https://github.com/ant-design/ant-design/assets/116932167/27dd9e6d-bfd4-464c-86b5-fcbac57cbb19)

**Comment by zombieJ** [comment]
HOC 传入，status。自定义元素的属性不一定也叫 `status`：

```tsx
const MyInput = ({ checkStatus, className, ...props }) => {
  return <input className={classNames(className, `my-status-${status}`)} {...props} />
};
```

**Comment by zombieJ** [comment]
自行封装 AutoComplete 后，你可以同时把 status 传给需要的地方。

**Comment by AmberSanyu** [comment]
> ![image](https://private-user-images.githubusercontent.com/116932167/329505271-27dd9e6d-bfd4-464c-86b5-fcbac57cbb19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTI2MDYsIm5iZiI6MTcxNTM5MjMwNiwicGF0aCI6Ii8xMTY5MzIxNjcvMzI5NTA1MjcxLTI3ZGQ5ZTZkLWJmZDQtNDY0Yy04NmI1LWZjYmFjNTdjYmIxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMTUxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDZjY2U3MTA2YzRkYjViZDAwNjMwZTBiNWQwODI2NWVlMWQ1M2RhMDhiZTk0YmEyY2MyZTRkZTIxNzEzNmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kJ-QN_Sdzfb6gzY07nZ20T1TRtkxrEgDQ8cVH9DkwbE)

重新设置分享了下 @coderz-w

**Comment by AmberSanyu** [comment]
> HOC 传入，status。自定义元素的属性不一定也叫 `status`：
> 
> ```tsx
> const MyInput = ({ checkStatus, className, ...props }) => {
>   return <input className={classNames(className, `my-status-${status}`)} {...props} />
> };
> ```
不是自己封装的，是文档提供了这个API呀，而且也没说改了输入框就不生效了
<img width="1506" alt="image" src="https://github.com/ant-design/ant-design/assets/18545388/bec66ad3-f72d-4961-8a46-7ecef5b77ecc">

**Comment by AmberSanyu** [comment]
> 自行封装 AutoComplete 后，你可以同时把 status 传给需要的地方：
> 
> ```tsx
> // 参考你的 PR，封装业务组件。而不是写死在 antd 中
> const MyAutoComplete = ({ status, ...props }) => (
>   <AutoComplete {...props} status={status}>
>     {cloneElement(...)}
>   </AutoComplete>
> );
> ```

为什么要我自己封装，不是提供了API吗？
<img width="1325" alt="image" src="https://github.com/ant-design/ant-design/assets/18545388/7f94e2d7-8b95-438c-875e-cb02c2352047">

**Comment by AmberSanyu** [comment]
@afc163 您好，这个官方会解决吗

**Comment by afc163** [comment]
我看 @zombieJ 已经给出解决方案了，而且确实有道理：https://github.com/ant-design/ant-design/pull/48871#issuecomment-2104491122 自定义组件不一定换成 antd 的，也可以换成原生 input 组件，你无法启动原生 input 也有 status 属性。

如果使用自定义组件换掉内建组件了，一些相关属性确实可能会失效，需要自己补上。不只是 status，variant 也会丢失。

**Comment by AmberSanyu** [comment]
> 我看 @zombieJ 已经给出解决方案了，而且确实有道理：[#48871 (comment)](https://github.com/ant-design/ant-design/pull/48871#issuecomment-2104491122) 。
> 
> 自定义组件也不一定都会换成 antd 的，也可以换成原生 input 组件，你无法期待原生 input 也有 status 属性。
> 
> 如果使用自定义组件换掉内建组件了，一些相关属性确实可能会失效，需要自己补上。不只是 status，variant 也会丢失。

首先，感谢上面老师给的解决方案
**然后我的问题是：**
目前**官方文档的描述来看，代码存在问题，并不符合预期。**
为什么只是仅仅在这里给我一个解决方案，然后就关闭了issue，
难道不应该去修复这个问题，或者确定不提供这个使用方式就改官方说明文档呀。
