### ISSUE TITLE
Popconfirm组件在antd@5.15.2及以上版本出现在ShadowRoot中确认按钮失效

### ISSUE THREAD

**Issue by RyzenPan** [ant-design/ant-design#48863]
### Reproduction link

[https://wujie-micro.github.io/doc/wujie/](https://wujie-micro.github.io/doc/wujie/)

### Steps to reproduce

在wujie官网预览antd的Popconfirm组件，使用Click触发的话，即可发现浮窗的确认按钮点击不生效

### What is expected?

在微前端shadow root下依然能正常使用，弹窗的按钮点击是可以的

### What is actually happening?

浮窗的确认按钮点击不生效
![image](https://github.com/ant-design/ant-design/assets/56830619/8677a7d9-4829-4e99-9fa6-dd913e900dc6)
![image](https://github.com/ant-design/ant-design/assets/56830619/8459a457-68aa-4b27-bd69-4291e4dae781)

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2 |
| System | 10 |
| Browser | 124.0.6367.119 |

---
根据排查，是由于@rc-component/trigger版本更新导致的，在@rc-component/trigger的https://github.com/react-component/trigger/compare/v1.18.3...v2.0.0  中影响，如果在pnpmlock中限定至1.18.3就没有问题，希望官方能尽快修复，使用shadow root的人应该不算少数

**Comment by Azriel-Offical** [comment]
<img width="740" alt="popOver" src="https://github.com/ant-design/ant-design/assets/160369499/6d61f33e-00da-4c93-862b-dd116cc6fa35">
补充，尝试使用Popover自行封装气泡确认组件规避该问题时。
如果trigger属性为”hover"(默认/指定)，onClick事件可以正确触发。但如果将trigger指定为非hover则onClick事件无法被触发。

**Comment by RyzenPan** [comment]
其实是target的问题，使用无界的EventTargetPlugin可解决问题
![image](https://github.com/ant-design/ant-design/assets/56830619/fc3ba767-b53c-42cc-a29e-b49d150a6981)

**Comment by biduone** [comment]
InstanceofPlugin + EventTargetPlugin 搭配确实解决了Popconfirm这个问题。
https://wujie-polyfill.github.io/doc/plugins/instanceof.html
