### ISSUE TITLE
DatePicker incorrect handles field value

### ISSUE THREAD

**Issue by IlyaLisov** [ant-design/ant-design#48873]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-datepicker-k8ldcc)

### Steps to reproduce

1) Create form with DatePicker
2) Set field value for DatePicker
3) Click on DatePicker for choosing another value

### What is expected?

Open DatePicker with selected date from field value, date can't be chosen

### What is actually happening?

After click on or move over datePicker value is changed to 5 years, I can't change date without writing it in field

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | react |
| System | macOS 14.4.1 |
| Browser | Google Chrome |

**Comment by IlyaLisov** [comment]
Solved with https://ant.design/docs/react/use-custom-date-library#antd-moment-webpack-plugin

I used `moment`, but `dayjs` is default, so I need to create custom component

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774
