### ISSUE TITLE
按钮下方有阴影

### ISSUE THREAD

**Issue by LesilyMaple** [ant-design/ant-design#48875]
### Reproduction link

[https://ant.design/components/button-cn](https://ant.design/components/button-cn)

### Steps to reproduce

官网示例
亮色模式和暗色模式都有

![image](https://github.com/ant-design/ant-design/assets/34186353/eb3b93a0-2171-4e05-b025-a2b1b211dcc3)

### What is expected?

没有下方的阴影

### What is actually happening?

按钮下方有阴影

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18 |
| System | windows10 |
| Browser | edge 124.0.2478.80 |

**Comment by Wxh16144** [comment]
设计如此，如果不需要可以参考 https://github.com/ant-design/ant-design/issues/45594 进行覆盖。
