### ISSUE TITLE
A lot of <style>

### ISSUE THREAD

**Issue by silviaphungky** [ant-design/ant-design#48883]
### Reproduction link

[https://ant.design/components/typography](https://ant.design/components/typography)

### Steps to reproduce

- inspect https://ant.design/components/typography
- search style in html

### What is expected?

minimal style injection

### What is actually happening?

a lot of style injection in head that cause bigger string in memory inspection

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

<img width="702" alt="Screenshot 2024-05-12 at 08 01 22" src="https://github.com/ant-design/ant-design/assets/55534481/58a4135d-8ad0-44fd-a2fe-9610575ab298">
<img width="672" alt="Screenshot 2024-05-12 at 08 01 43" src="https://github.com/ant-design/ant-design/assets/55534481/1f207d4b-f871-4432-bf8b-0fd3dcca267a">

**Comment by MadCcc** [comment]
Styles are injected by component. Please provide a reproduction if you encountered with performance issue.

**Comment by silviaphungky** [comment]
https://master--tangerine-sherbet-853a3a.netlify.app/ this one using antd Typography and Flex
https://euphonious-cendol-61a17d.netlify.app/ this one without antd, only inline style

memory result in chrome devtools:
1. antd: the **strings** proportion is almost same with the **code** proportion
<img width="1440" alt="Screenshot 2024-05-17 at 09 24 38" src="https://github.com/ant-design/ant-design/assets/55534481/f357c14e-c06f-4dc9-a586-3aa8516d4e84">


if we see more in the sumary, it shows a lot of repetition of Token*** and antd typography style
<img width="826" alt="Screenshot 2024-05-17 at 09 21 44" src="https://github.com/ant-design/ant-design/assets/55534481/2b614ef0-6b06-4bf0-b1c4-0caef8e1a18d">
<img width="1178" alt="Screenshot 2024-05-17 at 09 30 37" src="https://github.com/ant-design/ant-design/assets/55534481/6f2a724b-e503-423c-aa27-d4550131c8cb">
<img width="1440" alt="Screenshot 2024-05-17 at 09 31 02" src="https://github.com/ant-design/ant-design/assets/55534481/5f7f8cfc-75b2-46b5-9a6f-a59538623603">
imagine if I use a lot of components from antd, it will produce bigger strings in the memory that will cause performance issue in my website. I expect the strings is smaller without any repetition


2. inline style without antd
<img width="1426" alt="Screenshot 2024-05-17 at 09 24 15" src="https://github.com/ant-design/ant-design/assets/55534481/36924a07-922c-414e-843c-cf40038c4907">

**Comment by silviaphungky** [comment]
@MadCcc I aready attach the link for reproduce
