### ISSUE TITLE
vite-react初始化的项目无法使用antd

### ISSUE THREAD

**Issue by wanghao1993** [ant-design/ant-design#48888]
### Reproduction link

[https://github.com/wanghao1993/react-admin.git](https://github.com/wanghao1993/react-admin.git)

### Steps to reproduce

直接安装依赖，启动就会看到错误。

### What is expected?

期望能够正常运行

### What is actually happening?

只要使用组件就会报错，
This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    node_modules/.pnpm/antd@5.17.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/antd/es/notification/PurePanel.js:19:23:
      19 │ import { Notice } from 'rc-notification';
         ╵                        ~~~~~~~~~~~~~~~~~

✘ [ERROR] Failed to resolve entry for package "@ant-design/cssinjs". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.2.0 |
| System | MacOs14.4.1 |
| Browser | chrome 124.0.6367.91 |

**Comment by Wxh16144** [comment]
你的 vite config 为啥只 resolve `.tsx` 文件呢🤔? 

```diff
     react(),
   ],
   resolve: {
-    extensions: [".tsx"],
+    // extensions: [".tsx"],
     alias: [
       {
         find: "@",
```

**Comment by wanghao1993** [comment]
sorry. 阿西吧 低级错误-
