### ISSUE TITLE
Form 滚动对 Upload 无效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#48882]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-j7cmsc?file=demo.tsx)

### Steps to reproduce

1.点击 submit，input 因为必填滚动到页面中间
2.input 输入内容，再次 submit

### What is expected?

upload 滚动到页面中间

### What is actually happening?

页面没有滚动

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by Wxh16144** [comment]
示例中的代码需要调整一下，antd 内置组件获取逻辑是优先判断转发的 ref

source code：https://github.com/ant-design/ant-design/blob/470e8a8e0a269bbe28b139df346bf1081873e0d5/components/form/hooks/useForm.ts#L26-L41

调整示例

```diff
-const ItemChildrenWrapper = (props: any) => {
+const ItemChildrenWrapper = React.forwardRef((props: any, ref) => {
   const { children, ...rest } = props
-  return React.cloneElement(children, rest)
-}
+  return React.cloneElement(children, { ...rest, ref })
+})
```

**Comment by crazyair** [comment]
嗯，也找了 id，但是 display none 了

**Comment by crazyair** [comment]
不能这样改，Upload 本身的 ref 没了

**Comment by crazyair** [comment]
```tsx
 return React.cloneElement(children, { ...rest, ref })
```

不能这样改，Upload 本身的 ref 方法没了
![image](https://github.com/ant-design/ant-design/assets/7971419/3fc6bf9e-05db-4baf-b3c0-24157a2c0e75)

**Comment by Wxh16144** [comment]
群里已经讨论过了，贴一下结论：

antd 的 Form.Item 会合并 children 的 ref， 具体可以看一眼 https://github.com/ant-design/ant-design/blob/8b8021083ee9b6b1db305b62ff007503f8106ccd/components/form/hooks/useItemRef.ts Form.Item 是如何获得 ref 的
