### ISSUE TITLE
Add check file name in isImageUrl in Upload 

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#48881]
### What problem does this feature solve?

I have link with encrypted URL and this URL haven't any extension but have file name and in file name have extension so Upload don't show image preview

### What does the proposed API look like?

In this code:
```
export const isImageUrl = (file: UploadFile): boolean => {
  if (file.type && !file.thumbUrl) {
    return isImageFileType(file.type);
  }
  const url = file.thumbUrl || file.url || '';
  const extension = extname(url);
  if (
    /^data:image\//.test(url) ||
    /(webp|svg|png|gif|jpg|jpeg|jfif|bmp|dpg|ico|heic|heif)$/i.test(extension)
  ) {
    return true;
  }
  if (/^data:/.test(url)) {
    // other file types of base64
    return false;
  }
  if (extension) {
    // other file types which have extension
    return false;
  }
  return true;
};
```

just do it
```const url = file.thumbUrl || file.url || file.fileName || '';```

**Comment by afc163** [comment]
> I have link with encrypted URL and this URL haven't any extension but have file name and in file name have extension so Upload don't show image preview

Could you provide a reproduce?
