### ISSUE TITLE
TreeSelect 父节点选中，禁用后，子节点选中状态消失

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#48891]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-napqqa?file=demo.tsx)

### Steps to reproduce

1、勾选 Node2 disabled
2、查看 TreeSelect

### What is expected?

Node2 下的节点还是选中状态

### What is actually happening?

Node2 下的节点没有被选中

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | lastest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
预期行为，禁用节点不会参与传导计算。参考：
[Blog: Tree 的勾选传导](https://ant-design.antgroup.com/docs/blog/check-conduct-cn)
