### ISSUE TITLE
Add little vertifcal spacing for multiple select?  :)

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#48907]
### What problem does this feature solve?

Vertical spacing to improve some visuals

![image](https://github.com/ant-design/ant-design/assets/52765572/635ef735-f722-4f6a-af53-21c66dacce71)

### What does the proposed API look like?

css style changes

**Comment by LonelySnowman** [comment]
@AsuraKev Can you provide a link to CodeSendbox?

**Comment by AsuraKev** [comment]
Sorry it turns out to be my styling isse, default antd select is working fine. thanks
