### ISSUE TITLE
升级到2.7.1后 Menu组件的mode为vertical时，无法展开二级菜单

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#4890]
#### Environment(required)

- antd version: 2.7.1
- OS and its version: window 10
- Browser and its version: chrome 56

#### What did you do? Please provide steps to re-produce your problem.

在使用Layout  Sider, Menu组件时，当Menu组件的mode为vertical时，无法展开二级菜单。
在2.7.0版本是都是正常的，升级到2.7.1版本后出现的问题。

#### Re-producible online demo

http://codepen.io/xiaoyi_1222/pen/NdJpbG?editors=0110

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/4812 这里加了 `overflow: hidden` 导致看不见弹出菜单。
