### ISSUE TITLE
[Descriptions] Ellipsis style for dynamic content is not correct when enable copyable or editable

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#48919]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-w6ye82?file=demo.tsx)

### Steps to reproduce

- View the demo.
- wait 2 seconds and view the last `Description.Item` style.

### What is expected?

- Ellipsis style for dynamic content should be correct when enable copyable or editable.

![image](https://github.com/ant-design/ant-design/assets/14918822/71a1ab42-ee36-420d-b63c-ac3e797f0011)

### What is actually happening?

- Ellipsis style for dynamic content is not correct when enable copyable or editable.

![image](https://github.com/ant-design/ant-design/assets/14918822/9d0df2b0-b580-4a43-a797-a5852018fc87)

| Environment | Info |
| --- | --- |
| antd | 5.17.1 |
| React | 18.0.0 |
| System | MacOS |
| Browser | Chrome 120.0.6099.225 |

**Comment by MadCcc** [comment]
https://stackblitz.com/edit/react-w6ye82-jhvcyr?file=demo.tsx

给 Text 加了 style 试试
