### ISSUE TITLE
【分类搜索组件】CategorySearch 

### ISSUE THREAD

**Issue by HenryLee951020** [ant-design/ant-design#48910]
### What problem does this feature solve?

争对表单项数量过多时占用页面区域时
可参考：https://devui.design/components/zh-cn/category-search/demo

### What does the proposed API look like?

searchConfig = [
    {
      label: '搜索项1',
      key: 'filter1',
      type: 'select',
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
      ],
    },
    {
      label: '搜索项2',
      key: 'filter2',
    },
  ],
}

**Comment by afc163** [comment]
https://procomponents.ant.design/components/query-filter#queryfilter,lightfilter-demo-light-filter 看下是否符合你的需求。

**Comment by HenryLee951020** [comment]
> https://procomponents.ant.design/components/query-filter#queryfilter,lightfilter-demo-light-filter看下是否满足您的需求。

我在个人项目中尝试使用Popover、Dropdown、Tag等组件组合的方式去封装 但是存在诸多问题 所以想看看这边有没有这种组件 
![SearchBox](https://github.com/ant-design/ant-design/assets/169737025/3122a6bf-ffdb-498c-bb39-b8030bb5ce39)

这个组件在“腾讯云”的项目页也有使用
![image](https://github.com/ant-design/ant-design/assets/169737025/4ef6b964-e1fe-4bd2-9a2b-bb5ff593c22e)

我将尝试LightFilter组件的二次封装

**Comment by crazyair** [comment]
> https://procomponents.ant.design/components/query-filter#queryfilter,lightfilter-demo-light-filter 看下是否符合你的需求。

随便一试都是 bug


https://github.com/ant-design/ant-design/assets/7971419/104d885f-d15d-4754-8630-a64ce9e3c79c

**Comment by afc163** [comment]
@HenryLee951020

**Comment by HenryLee951020** [comment]
> @HenryLee951020你看下如何呢？

我在尝试将LightFilter内嵌到一个search box中 看看能否达到以上提及的效果
https://devui.design/components/zh-cn/category-search/demo#auto-scroll

**Comment by HenryLee951020** [comment]
> @HenryLee951020 你看下如何呢？

我在项目中直接使用LightFilter的示例代码报错了（.objectToMap is not a function）
![image](https://github.com/ant-design/ant-design/assets/169737025/57f4e70a-45cc-4337-9c4f-1ff976bddb52)
![image](https://github.com/ant-design/ant-design/assets/169737025/f7939f94-4894-470f-a99e-b23746a00855)

**Comment by MadCcc** [comment]
这个业务属性太强了点，看看 Cascader 是不是就符合需求了
