### ISSUE TITLE
bug: input标签的type属性为number时，form 不能正确清除input标签中的不合法内容。

### ISSUE THREAD

**Issue by sunganyu** [ant-design/ant-design#4891]
#### Environment(required)

- antd version:2.7.1
- OS and its version: MacOS
- Browser and its version: Chrome 版本 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

form组件的 resetFields() 方法，清除 input 输入框中的内容。

#### What do you expected?

当 input 标签的type属性为number时，不能预期的清除一些非常规输入。

#### What happen?

当 输入的内容为 'e333','.....'时，不能被正确的清除。

#### Re-producible online demo

https://ant.design/components/form-cn/

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by sunganyu** [comment]
https://mp.weixin.qq.com/s?__biz=MzAwNDc0MTUxMw==&mid=2649639755&idx=1&sn=329ade4a4e48b9671a3fb6230e2d833e&chksm=833dabadb44a22bb37cfa1d542add99c07a9fdea2ab8dc67610ba2be78b23ad084249cd618e3&mpshare=1&scene=1&srcid=1213CdYpwdrZTiOxcaftRadj&key=bf9387c4d02682e1dc01191f911a08f55c88217dff59e91675acc2aafc03df2a5a987c8a15268370d331127f6a09cf3d52430ac60610b40e934edf400aa2669e87b8c878c55dd3a6a38d4b3333bc61ef&ascene=0&uin=MjEyMTg0NDU1&devicetype=iMac+MacBookPro12%2C1+OSX+OSX+10.12.1+build(16B2659)&version=12010110&nettype=WIFI&fontScale=100&pass_ticket=q1VzbYbvfbo9DCEu5qahZqefky0XH%2Fns1QGCtD31FXo%3D

**Comment by sunganyu** [comment]
[这是bug重现的demo](https://mp.weixin.qq.com/s?__biz=MzAwNDc0MTUxMw==&mid=2649639755&idx=1&sn=329ade4a4e48b9671a3fb6230e2d833e&chksm=833dabadb44a22bb37cfa1d542add99c07a9fdea2ab8dc67610ba2be78b23ad084249cd618e3&mpshare=1&scene=1&srcid=1213CdYpwdrZTiOxcaftRadj&key=bf9387c4d02682e1dc01191f911a08f55c88217dff59e91675acc2aafc03df2a5a987c8a15268370d331127f6a09cf3d52430ac60610b40e934edf400aa2669e87b8c878c55dd3a6a38d4b3333bc61ef&ascene=0&uin=MjEyMTg0NDU1&devicetype=iMac+MacBookPro12%2C1+OSX+OSX+10.12.1+build(16B2659)&version=12010110&nettype=WIFI&fontScale=100&pass_ticket=q1VzbYbvfbo9DCEu5qahZqefky0XH%2Fns1QGCtD31FXo%3D)

**Comment by afc163** [comment]
This seems to be a React bug: http://codepen.io/anon/pen/MJxOYd?editors=1010

**Comment by afc163** [comment]
Have to close it now, cause it's not antd bug and we are not able to resolve it now.

You can try InputNumber to replace `input[type="number"]`.

**Comment by sunganyu** [comment]
Thank you!
