### ISSUE TITLE
Tour组件箭头有空隙，而且不支持style？

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#48929]
### What problem does this feature solve?

<img width="615" alt="image" src="https://github.com/ant-design/ant-design/assets/29728228/9667366f-bcec-4844-9d1c-c44e7cfae8f2">

目前这个弹框520px宽是写死的么，除了覆盖，还有什么办法可以支持修改宽度高度？
目前这个宽度对我来说太宽了，需要缩小

<img width="446" alt="image" src="https://github.com/ant-design/ant-design/assets/29728228/137658c1-4af2-45d2-9c58-d7af7289db59">

另外，发现箭头有空隙

### What does the proposed API look like?

对外暴露style

**Comment by MadCcc** [comment]
1. 间隙是精度问题，trigger 组件强制对齐到整数可能能解
2. Tour 的宽度可以在 TourStep 使用 style 修改

**Comment by zystudios** [comment]
> 1. 间隙是精度问题，trigger 组件强制对齐到整数可能能解
> 2. Tour 的宽度可以在 TourStep 使用 style 修改

@MadCcc 感谢，果然在step里可以写css，这个文档是不是补充一下，没提有style ，https://ant.design/components/tour-cn

**Comment by yoyo837** [comment]
Close by https://github.com/react-component/trigger/pull/465
