### ISSUE TITLE
Image 组件中 toolbarRender 的 info 参数里面的 actions，现在只暴露出了 onZoomOut 和 onZoomIn，期望能有一个 重置action

### ISSUE THREAD

**Issue by zhubincode** [ant-design/ant-design#48922]
### What problem does this feature solve?

图片放大或者缩小之后可以通过一个按钮点击达到初始化的预览效果

### What does the proposed API look like?

和 onZoomOut 同级，多暴露出一个方法 比如 onReset，或者onZoomOut 添加参数可以达到自定义缩小多少倍

**Comment by kiner-tang** [comment]
这个问题有同学跟进吗？没有的话我来跟进一下
