### ISSUE TITLE
Modal组件 confirm组件主题

### ISSUE THREAD

**Issue by freeman-xv** [ant-design/ant-design#48920]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-l347rp?file=%2Findex.js%3A23%2C13)

### Steps to reproduce

我修改了他的主题颜色,Button组件的class和confirm的确定按钮的class是一样的，但是背景颜色不一样。这是否是bug？还是不应该配置colorPrimary，应该配置其他属性。

### What is expected?

Button组件和confirm的确定按钮的背景颜色相同

### What is actually happening?

Button组件和confirm的确定按钮的背景颜色不相同

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | 18.2.0 |
| System | windows11 |
| Browser | 124.0.6367.201（正式版本） （64 位） |

**Comment by MadCcc** [comment]
1. 你的 codesandbox 是 private 的，请公开
2. 如果你使用的是静态方法，那么主题配置对其是无效的，参考：https://ant-design.antgroup.com/components/modal-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-contextredux%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-configprovider-localeprefixclstheme-%E7%AD%89%E9%85%8D%E7%BD%AE

**Comment by zombieJ** [comment]
静态方法不消费 context，参考 @MadCcc 提供的文档哈~
