### ISSUE TITLE
error TS2605 JSX element type Button is not a constructor function for JSX elements

### ISSUE THREAD

**Issue by martinnov92** [ant-design/ant-design#4892]
Hello,

since this morning I am getting errors everytime I try to use Ant Design component, I am not sure if this is Typescript´s issue or Ant Design. 

This is the error message:
error TS2605: JSX element type 'Button' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'Button'.

Does anyone has the same issue? Thank you.

- antd version: 2.7.1
- OS and its version: Windows 10
- Browser and its version: Chrome 56

#### What did you do? Please provide steps to re-produce your problem.

I imported Button to my app and the error appered right after. I am using Visual Studio Code

#### What do you expected?

It works fine as official website

**Comment by yesmeck** [comment]
Which `@types/react` version are you using?

**Comment by martinnov92** [comment]
It is `"@types/react": "^15.0.9"`

**Comment by yesmeck** [comment]
Do you have `"allowSyntheticDefaultImports": true` in tsconfig.json?

**Comment by martinnov92** [comment]
Thank you! It helped, but now I am getting another warning:
`warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.` :/

**Comment by kafein** [comment]
@martinnov92 How do you solve this? I'm getting same error.

**Comment by yesmeck** [comment]
@kafein See my comment above.

**Comment by kafein** [comment]
@yesmeck i see your comment but its already set to true.

my tsconfig.json file

{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": false,
        "moduleResolution": "node",
        "target": "es5",
        "jsx": "react",
        "allowSyntheticDefaultImports": true
    },
    "include": [
        "./src/**/*"
    ]

**Comment by martinnov92** [comment]
@kafein Hi, I think I had to change the import to `import { SomeComponent } from 'antd/lib/SomeComponent'`

**Comment by kafein** [comment]
Thanks @martinnov92 

But now i'm getting this error;

file: 'file:///Users/emrah/own/diyafram/stock/src/index.tsx'
severity: 'Error'
message: 'Module '"/Users/emrah/own/diyafram/stock/node_modules/antd/lib/date-picker/index"' has no exported member 'DatePicker'.'
at: '3,9'
source: 'ts'

**Comment by martinnov92** [comment]
@kafein Sorry, try it without {}, I don´t remember what I did exactly :D

**Comment by kafein** [comment]
@martinnov92 Thanks.

**Comment by martinnov92** [comment]
@kafein Is it working now?

**Comment by kafein** [comment]
import DatePicker from 'antd/lib/date-picker';  // for js
import 'antd/lib/date-picker/style/css';        // for css

importing with this usage not working.

but when i try

`import {DatePicker} from 'antd'; `

it works, but imports whole package which i don't want

**Comment by devmetal** [comment]
@kafein 

Same problem here. I digging in issues and comments but its not working in typescript. Its very sad because its a great component library. 

There is any solution?

**Comment by yesmeck** [comment]
@devmetal Could you provide a demo repo?

**Comment by devmetal** [comment]
@yesmeck 

Unfourtunatly its a private company repo. But i can provide some code.

My ts version is 2.1.5

```json
{
  "compilerOptions": {
    "jsx": "react",
    "module": "commonjs",
    "noImplicitAny": true,
    "outDir": "./build/",
    "preserveConstEnums": true,
    "removeComments": true,
    "target": "ES5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "lib": [
      "dom", "es6"
    ],
    "baseUrl": "./src",
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules"
  ]
}
```
```JavaScript
//this is working
import { Layout } from 'antd';

//this is not
import * as Layout from 'antd/lib/layout';

//JSX element type 'Layout' does not have any construct or call signatures.
<Layout></Layout>

//also not working, same error
//JSX element type 'Layout' does not have any construct or call signatures. 
import Layout from 'antd/lib/layout';
```

And the type hint are totally gone. All component is any. 

Thank you for help

**Comment by devmetal** [comment]
@yesmeck 

Hi, any idea or progress? :)

**Comment by yesmeck** [comment]
No idea from your config. See this [comment](https://github.com/ant-design/ant-design/issues/5426#issuecomment-288543893).

**Comment by luanped** [comment]
@devmetal @kafein I had the same issue, i fixed the problem by setting module: es6 in tsconfig, the default being commonjs which was not compatible

**Comment by icfantv** [comment]
The issue for us was that we were specifying `void` as the state argument on our react component classes that extended `React.Component<IMyProps, void>` (and it has the same issue with `null`, apparently).  The fix was to simply remove the `void` and just specify the property interface.

**Comment by llaine** [comment]
@icfantv Could you elaborate more on this topic? 
I'm using TS 2.5.2 and removing the `void` from my Component state declaration doesn't fix anything, unfortunately.

**Comment by lvlinhaohan2010** [comment]
I had the same issue, because "strictNullChecks" is true.
when set it to false,then ok.

**Comment by googol7** [comment]
I had to configure VS Code to use the correct version of TypeScript: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

**Comment by kevinschaich** [comment]
Issue for me was I had a short-circuit `return` statement in the component I was trying to import:

```
if(!blah) {
    return;
}
```

Solution was to return `null` explicitly:

```
if(!blah) {
    return null;
}
```

**Comment by amiram** [comment]
@luanped Your answer is probably the correct one. It should get into the docs.

**Comment by dgreene1** [comment]
In my case, the fix was upgrading the types. Note this was using the typescript demo that is described at: https://ant.design/docs/react/use-in-typescript

So I guess it needs to have the documentation updated:
```
yarn upgrade @types/react@latest
```
