### ISSUE TITLE
upload组件有时候点击无反应，不会弹出系统文件夹

### ISSUE THREAD

**Issue by tsuyoii** [ant-design/ant-design#48932]
### Reproduction link

[https://4x.ant.design/components/upload-cn/](https://4x.ant.design/components/upload-cn/)

### Steps to reproduce

不是必现，官网也有这个问题

### What is expected?

弹出文件选择框来选择要上传的文件

### What is actually happening?

无法弹出系统文件夹，也无报错，没有任何反应

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | Mac |
| Browser | 版本 124.0.6367.119（正式版本） (arm64) |

**Comment by Wxh16144** [comment]
<img width="1338" alt="image" src="https://github.com/ant-design/ant-design/assets/32004925/ca2be32a-9eab-4e70-b9f7-7f6b70a13fd3">

**Comment by zombieJ** [comment]
[FAQ: 为何有时 Chrome 点击 Upload 无法弹出文件选择框？](https://ant-design.antgroup.com/components/upload-cn#%E4%B8%BA%E4%BD%95%E6%9C%89%E6%97%B6-chrome-%E7%82%B9%E5%87%BB-upload-%E6%97%A0%E6%B3%95%E5%BC%B9%E5%87%BA%E6%96%87%E4%BB%B6%E9%80%89%E6%8B%A9%E6%A1%86)

**Comment by tsuyoii** [comment]
好的，谢谢大佬

**Comment by tsuyoii** [comment]
更新后又出现了，请问大佬有什么解决方案吗😭
