### ISSUE TITLE
OnBlur it works incorrectly

### ISSUE THREAD

**Issue by korzh875** [ant-design/ant-design#48942]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-4kmf1e-8gbufm?file=demo.tsx)

### Steps to reproduce

1. fill in the Username field
2. remove focus
3. try changing Username again

### What is expected?

that onBlur works fine after and before changing the field again

### What is actually happening?

input field freezes after changing again

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18.3.1 |
| System | mac os 14.4.1 |
| Browser | chrome 124.0.6367.203 |

---
screencast https://files.fm/u/5cjaxj37tb

**Comment by coderz-w** [comment]
Can you tell me about your requirements? In fact, the trigger property is used to declare the timing of the component's value change, and Form.Item will convert its child components into a controlled mode. If you set onblur, during the first rendering, because the value is undefined, the component is still in an uncontrolled state at this point, so the input behavior can change the value. However, after an onblur event is triggered once, the value is no longer undefined, and the component is now controlled. It will attempt to change the value through the onblur event, which, of course, will not update correctly. Of course, if you want to trigger validation when onblur occurs, please refer to [**validateTrigger**](https://ant.design/components/form#components-form-demo-validate-trigger).

**Comment by korzh875** [comment]
> Can you tell me about your requirements? In fact, the trigger property is used to declare the timing of the component's value change, and Form.Item will convert its child components into a controlled mode. If you set onblur, during the first rendering, because the value is undefined, the component is still in an uncontrolled state at this point, so the input behavior can change the value. However, after an onblur event is triggered once, the value is no longer undefined, and the component is now controlled. It will attempt to change the value through the onblur event, which, of course, will not update correctly. Of course, if you want to trigger validation when onblur occurs, please refer to [**validateTrigger**](https://ant.design/components/form#components-form-demo-validate-trigger).



> Can you tell me about your requirements? In fact, the trigger property is used to declare the timing of the component's value change, and Form.Item will convert its child components into a controlled mode. If you set onblur, during the first rendering, because the value is undefined, the component is still in an uncontrolled state at this point, so the input behavior can change the value. However, after an onblur event is triggered once, the value is no longer undefined, and the component is now controlled. It will attempt to change the value through the onblur event, which, of course, will not update correctly. Of course, if you want to trigger validation when onblur occurs, please refer to [**validateTrigger**](https://ant.design/components/form#components-form-demo-validate-trigger).

I need to send the value of the input field after onBlur

There is a form, somewhere there is a delay in sending data after entering, and somewhere I need to send data only when onBlur is triggered, and it turns out that after entering values I can no update the field

Also in my example on stackblitz note that input: number with onBlur, everything works fine, why is that?

**Comment by zombieJ** [comment]
`trigger` means the value which will Form.Item to collect. 

1. At the first time, the field value is `undefined`. So Input will work as uncontrolled component.
2. When `onBlur`, the `value` is set to what user input. The Input will be the controlled component. So any type will not work.

You should not use `trigger` for validation. But use `validateTrigger` instead.

**Comment by zombieJ** [comment]
> Also in my example on stackblitz note that input: number with onBlur, everything works fine, why is that?

Input follow the behavior as native input element since every time the input is what input validate value. But InputNumber has the flying status. e.g. `1.2` type `1.`, the `1.` is not validate number. If it force as controlled, user will never successfully type the `1.2`. So it will keep tracking typing status.

So if you want to follow the InputNumber behavior. You can HOC Input component to make focus not be controlled.

**Comment by korzh875** [comment]
> > Also in my example on stackblitz note that input: number with onBlur, everything works fine, why is that?
> 
> Input follow the behavior as native input element since every time the input is what input validate value. But InputNumber has the flying status. e.g. `1.2` type `1.`, the `1.` is not validate number. If it force as controlled, user will never successfully type the `1.2`. So it will keep tracking typing status.
> 
> So if you want to follow the InputNumber behavior. You can HOC Input component to make focus not be controlled.

again I need to get value in 
`<Form form={form} onValuesChange={debounceHandler}>` 
using 
`Form.Item with trigger="onBlur"` 

and whether input or textarea

Please give me an example where this would work

**Comment by coderz-w** [comment]
> again I need to get value in `<Form form={form} onValuesChange={debounceHandler}>` using `Form.Item with trigger="onBlur"`
> 
> and whether input or textarea
> 
> Please give me an example where this would work
If you need to perform some operations on `onBlur`, you can do it like this, but please make sure that the antd component you are using can accept the `onBlur` property.
![image](https://github.com/ant-design/ant-design/assets/116932167/77aa774d-cd5e-45fa-8304-091dc7545b6d)

**Comment by korzh875** [comment]
> onBlur

I need onValuesChange to only work when onBlur is enabled.

your example still fires onValuesChange during input

**Comment by coderz-w** [comment]
It feels a bit difficult to handle, as the form component triggers onValuesChange every time updateValue is called.

**Comment by korzh875** [comment]
> It feels a bit difficult to handle, as the form component triggers onValuesChange every time updateValue is called.

yes, but I still don't understand how I can create an input or textarea component that will work like inputNumber with trigger = OnBlur

to be honest, I created a HOC with state, but I don’t really like this solution

**Comment by AliceXu521** [comment]
> > onBlur
> 
> I need onValuesChange to only work when onBlur is enabled.
> 
> your example still fires onValuesChange during input

Hello~May I ask you if you have found the effective methods which can solve this problem?I have a seem problem now.I want to collect the formItem value after onBlur
