### ISSUE TITLE
麻烦更新api后，demo也修改一下啊，小哥哥喂。

### ISSUE THREAD

**Issue by cordaro** [ant-design/ant-design#4894]
form demo中 upload插件中的  normalize 应该是 getValueFromEvent好么  害我来来回回折腾了半天 心累。

**Comment by yesmeck** [comment]
帮我们改一下吧。

**Comment by cordaro** [comment]
有空研究下吧，还不会=。=

**Comment by yesmeck** [comment]
很简单的。

先找到文档有问题的地方，点击下面的编辑图标：

<img width="552" alt="1" src="https://cloud.githubusercontent.com/assets/465125/22977069/35acfae2-f3c8-11e6-87d8-4a495ba9238b.png">

跳转到 GitHub 后再点击编辑图标：

<img width="431" alt="2" src="https://cloud.githubusercontent.com/assets/465125/22977110/57d685ca-f3c8-11e6-8b96-721a2f447706.png">

然后就可以改错误了，下面写上 commit 信息：

![3](https://cloud.githubusercontent.com/assets/465125/22977141/735af43e-f3c8-11e6-9144-00a23edd83c7.png)

然后提交就可以了。

**Comment by cordaro** [comment]
哈哈，好像可以  真耐心
