### ISSUE TITLE
在webComponent自定义元素a的shadow dom里面使用TimePicker组件，把这个自定义元素a放到另外一个webComponent自定元素b的shadow dom中,TimePicker组件无法选中时间，第二次点击时间，会自动关闭时间选择框。

### ISSUE THREAD

**Issue by gdutzhendong** [ant-design/ant-design#48952]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/bold-tristan-pf2fhw?file=%2Findex.tsx%3A64%2C24)

### Steps to reproduce

点击时间输入框，打开时间选择弹框，点击其中一个时间，然后再点击另外一个不同的时间，这是没有点确认按钮，弹窗也会自动关闭

### What is expected?

在webComponent自定义元素a的shadow dom里面使用TimePicker组件，把这个自定义元素a放到另外一个webComponent自定元素b的shadow dom中,TimePicker组件功能可以正常使用。

### What is actually happening?

在webComponent自定义元素a的shadow dom里面使用TimePicker组件，把这个自定义元素a放到另外一个webComponent自定元素b的shadow dom中,TimePicker组件功能不能正常使用。

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | latest |
| System | macOs 7429.81.3 |
| Browser | chrom  124.0.6367.158 |

**Comment by gdutzhendong** [comment]
Uploading 屏幕录制2024-05-16 下午10.52.51.mov…

**Comment by gdutzhendong** [comment]
> 你的 codesandbox 是 private 的……
我已经改成public了，现在可以访问了

**Comment by gdutzhendong** [comment]
已经改成public的了


| |
gdut_hzd
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月22日 16:27 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [ant-design/ant-design] 在webComponent自定义元素a的shadow dom里面使用TimePicker组件，把这个自定义元素a放到另外一个webComponent自定元素b的shadow dom中,TimePicker组件无法选中时间，第二次点击时间，会自动关闭时间选择框。 (Issue #48952) |

你的 codesandbox 是 private 的……

**Comment by gdutzhendong** [comment]
看起来是底层依赖的react-component/trigger这个项目的问题。
在那边提交了一个pr：https://github.com/react-component/trigger/pull/462
issue ：https://github.com/react-component/trigger/issues/463
你们看看这样解决是否合适？

**Comment by gdutzhendong** [comment]
@zombieJ

**Comment by Psvensso** [comment]
Related https://github.com/react-component/trigger/pull/471 ?
