### ISSUE TITLE
qrcode disappear after switch tab in chrome

### ISSUE THREAD

**Issue by enix223** [ant-design/ant-design#48957]
### Reproduction link

[QRCode disappear](https://codesandbox.io/p/sandbox/antd-qrcode-disappear-mnxc8m)

### Steps to reproduce

1. Create qrcode
2. Open a new tab
3. Switch back to the origin tab

### What is expected?

QRCode should not disappear

### What is actually happening?

QRCode disappear after switch to another tab, and back to the tab

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by enix223** [comment]
Reproduce link updated

**Comment by afc163** [comment]
It seems to be a Chrome's bug.

**Comment by enix223** [comment]
Someone already fire an issue in [Chromium Issue Tracker](https://issues.chromium.org/issues/341105739). It is not related to this lib. Closed
