### ISSUE TITLE
Avatar.Group 增加自定义maxPopoverContent

### ISSUE THREAD

**Issue by coulis1018** [ant-design/ant-design#48950]
### What problem does this feature solve?

使用Avatar.Group 的maxCount 时，期望触发多余头像气泡弹出时，可以增加自定义popover 的content ，以便展示出更丰富的内容信息。

### What does the proposed API look like?

maxPopoverContent：ReactNode

**Comment by afc163** [comment]
```jsx
<Avatar.Group
  max={{
    count: 5,
    style: { ... },
    popover: { ... }, // Popover props
  }}
>
```

We should add a new prop `max`.

**Comment by wanpan11** [comment]
Let me give it a try

**Comment by beautiful-boyyy** [comment]
请教一下测试popover属性的实话是要把，popover组件的测试copy一份过来吗，还是有什么简便方法？

**Comment by wanpan11** [comment]
> 请教一下测试popover属性的时候是把popover组件的测试copy一份过来吗，还是说有什么简便方法？

一般测试 UI存不存在就行了，实在是测属性 可以用 jest.mock （项目里可以找到栗子）

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/49131
