### ISSUE TITLE
Select 默认只搜索 value，Cascader 默认只搜索 label

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#48961]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-bt7emp?file=demo.tsx)

### Steps to reproduce

创建一个 Select 和 Cascader，分别搜索 label 和 value

### What is expected?

搜索 label 和 value 应该都能匹配到结果

### What is actually happening?

Select 默认只搜索 value，而 Cascader 默认只搜索 label

![image](https://github.com/ant-design/ant-design/assets/5836790/35608d95-5a7b-430c-89cd-4effd28610a8)
![image](https://github.com/ant-design/ant-design/assets/5836790/7b4690fd-54f6-4d1c-8912-da62f10a1258)
![image](https://github.com/ant-design/ant-design/assets/5836790/6b997350-f62b-4f7c-99b6-361904273c4c)
![image](https://github.com/ant-design/ant-design/assets/5836790/cb7bfdc8-570e-4cb9-96cd-c185dabe3988)

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18.2.0 |
| System | macOS |
| Browser | Chrome 121 |

**Comment by zombieJ** [comment]
十分抱歉。历史债没办法改了，会造成 break change，可以使用对应 prop 修改查找字段哈~
