### ISSUE TITLE
The type of the 'record' argument of render func in the 'columns' props of the table is showing up as any.

### ISSUE THREAD

**Issue by minjinso** [ant-design/ant-design#48960]
### Reproduction link

https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-95c7mg?file=%2FApp.tsx%3A27%2C22

### Steps to reproduce

1. Make custom table component using Antd Table. (with generic <E extends object> for record type) 
2. import custom table.
3. Assigning dataSource, columns props etc.
4. Writing item object(ColumnsType<E>) in columns props array.

### What is expected?

Defining "render" method of column, the type of record should be E (that I assigned). 

### What is actually happening?

The RecordType is any, so ts error(7044) occurred.

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18.2.79 |
| System | macos |
| Browser | chrome |

---

It works as I expected when I downgrade the antd version to 5.15.4.

Through debugging, it was confirmed that this issue occurs because the RecordType = any statement was added to the TableProps of rc-table(v7.45) starting from antd version 5.16.0.

**Comment by minjinso** [comment]
> Hello @minjinso. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @minjinso，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

I added the reproduction link. https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-95c7mg?file=%2FApp.tsx%3A27%2C22

**Comment by zombieJ** [comment]
```diff
--  <CustomTable
++  <CustomTable<Temp>
```

When you wrap with HOC, ts at least need a case for infer the generic type. Your HOC component do not have it so can add on component directly.

**Comment by crazyair** [comment]
![image](https://github.com/ant-design/ant-design/assets/7971419/426526d2-1996-43c0-8009-679272f6b951)

**Comment by crazyair** [comment]
> ![image](https://private-user-images.githubusercontent.com/7971419/332722482-426526d2-1996-43c0-8009-679272f6b951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzEzMjAsIm5iZiI6MTcxNjM3MTAyMCwicGF0aCI6Ii83OTcxNDE5LzMzMjcyMjQ4Mi00MjY1MjZkMi0xOTk2LTQzYzAtODAwOS02NzkyNzJmNmI5NTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDk0MzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI4ZmMwYTIzYWY3YWE1MzI2ZDc5MWZjNjNmYWYyMWVjZmU4NDgwNzY2Mjk2YWU2N2JhNzhmNDhhNjE5MWQ5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kmGHkOOPhj-BIHTeO5rCPXl6KrNz5hPnahknlqwBbIs)

你这个类型可以实现利用 dataIndex 推导出 value 类型，但是如果 dataIndex 是数组，便无法使用了。目前还没想好到好的办法推导出 value 类型，我会持续关注 typescript 功能
