### ISSUE TITLE
upload 组件 FAQ 中的服务端 mock 方法的实现参考链接失效

### ISSUE THREAD

**Issue by CoderSerio** [ant-design/ant-design#48976]
### Reproduction link

[https://ant-design.antgroup.com/components/upload-cn#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0](https://ant-design.antgroup.com/components/upload-cn#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0)

### Steps to reproduce

1. 【重现链接】对应的官方文档最下方， FAQ > 服务端如何实现？ > 如果要做本地 mock 可以参考这个 express 的例子。
2. 点击提供的 express 的案例链接。
3. 访问到的代码 404

### What is expected?

希望能够正常访问到参考案例

### What is actually happening?

访问链接404

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18 |
| System | windows11 |
| Browser | chromeV124.0.6367.208 |

**Comment by kiner-tang** [comment]
看起来在这一次提交被删掉了，我在文档里面补一下吧
https://github.com/react-component/upload/pull/523/files#diff-a4c65ede64197e1a112899a68bf994485b889c4b143198bac4af53425b38406f
