### ISSUE TITLE
看中文的进来。 Make github issues more international friendly?

### ISSUE THREAD

**Issue by kossel** [ant-design/ant-design#4897]
可以大家都用英文描述问题吗？
很少国人的lib 和framework 能走出中国都是因为不注重国际化，ant团队那么卖力在解决这个问题我觉得我们也应该尊重**尽量使用英文**（同时也可以练英文），这样其他人遇到同样的问题搜索也简单点。
* antd 团队现在都用英文回复issues了

I can read/write Chinese but rest of my team (9 ppl) they don't,  however we chose Antd for our current long term project because it looks really promising and we feel that Antd team put a lot of effort on it.

The problem is it's very hard for non-chinese speaks to search antd related issues on github and google, we can already see antd team's initiative of answering in English even the title is Chinese. Maybe the we should remove the Chinese from the issue template and request people to use English.

**Comment by afc163** [comment]
We are replying in English because of this aiticle: https://medium.com/@yoniweisbrod/styling-react-applications-with-ant-design-92b742aab0b0#.avbmjm5oy

**Comment by kossel** [comment]
Yeah as the article states, language barrier looks like the most discussed issue for antd

**Comment by chengs** [comment]
Totally agreed. However, as issues in Chinese are inevitable currently, I suggest opening a new repo only for those issues.

**Comment by GrayChoi** [comment]
Agree

**Comment by knilink** [comment]
I spent a month trying to convince my team to use antd for the admin pages.
The final agreement was to use another library and only when a required component was not provided, we import it from antd.
The reason was half of the discussions were in chinese.

**Comment by benjycui** [comment]
We are trying to do so, and from now on, we can instruct community to write issue or comment in English with some saved reply, such as:

> It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by lokewei** [comment]
good idea

**Comment by kossel** [comment]
I think most Chinese developers have some level of English knowledge, they are already using many libs/frameworks which only have English documentation, so I think it's a cultural thing, like @benjycui  said, we just need to instruct and get use to it :D 🎉

**Comment by NE-SmallTown** [comment]
Trust me,the only way to solve this is that don't answer the question written by Chinese.

Whatever you say,the people who don't read the doc of antd or readme will still do that.They only want to know how to solve their own problem in project.Such as the readable,standardability,good description,they don't care.

**Comment by afc163** [comment]
> Trust me,the only way to solve this is that don't answer the question written by Chinese.

I like it but we can't be so arrogant.

**Comment by richardjboothe** [comment]
ant-d is a really amazing library/toolkit. I appreciate the effort that goes in to answering issues in english, but would absolutely agree that I have struggled in a few situations solely because of my ignorance in reading/speaking Chinese. Guess it's a good reason to get the Rosetta Stone for Mandarin 😅

**Comment by JiaHuiWeng** [comment]
Why Modal components can not delete confirmation and cancel buttons?

**Comment by NE-SmallTown** [comment]
@JiaHuiWeng Please remember one thing:ask questions by right way in the appropriate location.

**Comment by xgqfrms-gildata** [comment]
https://github.com/ant-design/ant-design/issues/6724

**Comment by jinliming2** [comment]
也许？可以在创建问题的时候让机器人自动识别中文内容，并自动进行修改，在标题上加上英文的机器翻译实现双语标题，并自动翻译内容，将机器翻译添加到正文末尾？（但要注明是机器翻译）

这样对于不懂英语的人会比较友好，对于英文问题搜索也会有一定帮助。

**Comment by wustzhaohui** [comment]
> Trust me,the only way to solve this is that don't answer the question written by Chinese.
> 
> Whatever you say,the people who don't read the doc or readme of antd will still do that.They only want to know how to solve their own problem in project.Such as the readable,standardability,good description,they don't care.

It's  ridiculous

**Comment by dospolov** [comment]
I'm using ant.design 5 years straight, from version 1.* and I love it. Currently, it is used on 12 of my projects: personal and client. 
Forced to admit the issue is not resolved and it becomes even worse. From my observation now the majority of tickets with vivid discussions are in Chinese. As a user, I feel myself abandoned and probably will have to switch to another UI kit in long-term perspective.

**Comment by yoyo837** [comment]
The main problem is: 

The proportion of Chinese users is relatively high, and most of them lack a good level of English.

**Comment by dospolov** [comment]
@yoyo837 I understand that.
I don't think maintainers should implement new restrictions, just by one user complaint.
But I do think that in general, when you're facing some issue - you should raise your voice.

**Comment by yoyo837** [comment]
Is it time to make some changes to this? @ant-design/ant-design-collaborators

**Comment by xrkffgg** [comment]
Actually, I think the translation tools are very convenient at the moment.
And almost all browsers have direct translation function.
So I think it's not too big of a problem.

**Comment by hengkx** [comment]
I remember there was an automatic translation robot.

**Comment by zombieJ** [comment]
@xrkffgg  @hengkx,
Auto translate give low quality in program related topic. It's removed since helpless.

@dospolov,
To enhance the experience of Chinese & English speaker. We collect frequency issue to move to the FAQ on official site since v3 continually. Maybe it's not best solution but I wish to let you know we care about this : )

**Comment by YvesChen** [comment]
> 相信我，解决这个问题的唯一方法就是不要回答中国人写的问题。
> 
> 不管你说什么，不看antd的doc或者readme的人还是会那样做。他们只想知道如何解决自己在项目中遇到的问题。比如可读性、标准性、描述性好，他们不知道关心。

v-if 之后 steps 会出现icon不加载，请问你遇到过吗？
```
<template v-if="stepsShow">
  <a-steps
    v-model:current="stepsNumber"
    :initial="0"
    type="navigation"
    size="small">
    <a-step disabled title="步骤 1"/>
    <a-step disabled title="步骤 2"/>
    <a-step disabled title="步骤 3"/>
  </a-steps>
</template>
<script>
  export default {
    data(){
      stepsNumber:0,
      stepsShow:false
    }
  }
</script>
```

![image](https://user-images.githubusercontent.com/5573829/182133146-23f4a9bd-420e-4797-8e4b-974a797ca639.png)
