### ISSUE TITLE
antd 不支持shopify/hydrogen这项目吗

### ISSUE THREAD

**Issue by Cozy490** [ant-design/ant-design#48983]
### What problem does this feature solve?

就想知道啥时候支持一下shopify/hydrogen，因为 antd 的确很好

### What does the proposed API look like?

就想知道啥时候支持一下shopify/hydrogen，因为 antd 的确很好

**Comment by afc163** [comment]
看看什么问题先。

**Comment by Cozy490** [comment]
这个是shopify/Hydrogen项目呢是个服务端渲染，主要的库是remix，我看咱们 antd 官网好像对这个库支持文档，所以我就来问一下，是不是目前不支持

**Comment by afc163** [comment]
我们不熟悉 Remix，所以目前无法给出明确的答案，但是服务端渲染框架比如 Next.js 我们是支持的。欢迎在 Remix 中使用 antd，如果遇到具体问题，欢迎过来报 bug。

**Comment by Cozy490** [comment]
好的，谢谢
