### ISSUE TITLE
form.setFieldValue 更新表单报错

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#48987]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-vdqyxx?file=%2Findex.js)

### Steps to reproduce

在 options[0].value 存在时手动进行一次 form.setFieldValue 赋值
![image](https://github.com/ant-design/ant-design/assets/30885718/9a2af3e6-7b57-49c5-9d35-ebbec9b3e156)

```ts
// 根据报错提示，改成以下代码将完成更新并且不会报错
if (options[0]?.value && initRef.current) {
    initRef.current = false;
    setTimeout(() => {
        form.setFieldValue("first", options[0].value);
    })
}
// 或者
if (options[0]?.value && initRef.current) {
    initRef.current = false;
    new Promise.resolve().then(() => {
        form.setFieldValue("first", options[0].value);
    })
}
```

### What is expected?

控制台不会打印任何错误

### What is actually happening?

控制台打印错误

| Environment | Info |
| --- | --- |
| antd | 4.24.14 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

**Comment by zombieJ** [comment]
如 React 的提示一样，你不应该在 render 中直接设置数据。`setTimeout` 和 `promise.then` 都不是标准写法。应该触发变更应该在 event or effect 中进行。具体可以参考一下 React 官网了解相关知识哈~

**Comment by guaijie** [comment]
> 如 React 的提示一样，你不应该在 render 中直接设置数据。`setTimeout` 和 `promise.then` 都不是标准写法。应该触发变更应该在 event or effect 中进行。具体可以参考一下 React 官网了解相关知识哈~

是指哪里在 render 中设置了数据
```ts
// 如果我写成一下代码并会报错呀
if (initRef.current) {
    initRef.current = false;
    form.setFieldValue("first", "first");
  }
```

**Comment by guaijie** [comment]
> 如 React 的提示一样，你不应该在 render 中直接设置数据。`setTimeout` 和 `promise.then` 都不是标准写法。应该触发变更应该在 event or effect 中进行。具体可以参考一下 React 官网了解相关知识哈~

我的代码中哪一部分是在 ‘render 中直接设置数据’的
如下图所示，如果我不使用 form.setFieldValue 而是直接使用 setName 并不会有任何报错
![image](https://github.com/ant-design/ant-design/assets/30885718/db6352c4-896b-4efc-af7a-c98fc5231a1d)
