### ISSUE TITLE
Notification 需要支持 pauseOnHover 属性

### ISSUE THREAD

**Issue by yociduo** [ant-design/ant-design#48985]
### What problem does this feature solve?

hover 到 notifications 上时，可以选择是否暂停计时器
https://github.com/react-component/notification/pull/322#issuecomment-2098083982

### What does the proposed API look like?

```
pauseOnHover: boolean = true
```

**Comment by zombieJ** [comment]
默认已经是有这个能力了，要加这个 API 是为了停用这个功能么？

**Comment by yociduo** [comment]
> 默认已经是有这个能力了，要加这个 API 是为了停用这个功能么？

现在的实现还是有点不一样的，现在不是暂停计时器，而是重新重新计时，加了进度条这个PR后会发现这个行为有些奇怪

**Comment by zombieJ** [comment]
> 现在的实现还是有点不一样的，现在不是暂停计时器，而是重新重新计时，加了进度条这个PR后会发现这个行为有些奇怪

如果是这样的话，看起来应该是没有进度条时 hover 重置，有进度条时 hover 暂停。作为默认行为就好了？感觉它不应该是一个透出的 API 到用户侧。

**Comment by yociduo** [comment]
> > 现在的实现还是有点不一样的，现在不是暂停计时器，而是重新重新计时，加了进度条这个PR后会发现这个行为有些奇怪
> 
> 如果是这样的话，看起来应该是没有进度条时 hover 重置，有进度条时 hover 暂停。作为默认行为就好了？感觉它不应该是一个透出的 API 到用户侧。

我觉得不管有没有进度条，行为应该是统一的，当时加 progress bar 的时候就觉得 hover 的时候重置会有一些奇怪。如果需要改成默认行为的话，还需要改一下基础库，我稍后更新。

**Comment by afc163** [comment]
和 https://fkhadra.github.io/react-toastify/introduction/ 行为保持一致。
