### ISSUE TITLE
antd 5.17.0版本 DatePicker 默认是英文，dayjs部分中文不生效

### ISSUE THREAD

**Issue by ZhangXDong** [ant-design/ant-design#48997]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn](https://ant-design.antgroup.com/components/date-picker-cn)

### Steps to reproduce

import enUS from 'antd/locale/en_US';

import zhCN from 'antd/locale/zh_CN';

import dayjs from 'dayjs';

import 'dayjs/locale/zh-cn';

dayjs.locale('zh-cn');

<ConfigProvider locale={locale}>
        <ReactComp />
</ConfigProvider>

### What is expected?

期望一二三四五，这种周组件可以正常展示展示中文

### What is actually happening?

始终是英文

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 17.0.2 |
| System | macos |
| Browser | chrome 版本 124.0.6367.208（正式版本） |

<img width="292" alt="image" src="https://github.com/ant-design/ant-design/assets/28100344/3a3d83ea-80e6-4366-94c9-d8867cc25950">

**Comment by ZhangXDong** [comment]
这问题总有人问，但还没被解决就关了，真奇怪

**Comment by zombieJ** [comment]
因为这不是 antd 的问题，而是你的 dayjs 多实例了。

**Comment by zombieJ** [comment]
看一下相关的 FAQ 哈~[为什么时间类组件的国际化 locale 设置不生效？](https://ant.design/docs/react/faq-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96-locale-%E8%AE%BE%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88)

**Comment by ZhangXDong** [comment]
我看了下，我依赖一个第三方库，第三方库依赖pm2，pm2/agent依赖的dayjs是1.8.36，不是1.11.10

这种情况下我也不能把pm2依赖拿掉呀，有啥好办法吗？

**Comment by yoyo837** [comment]
删除 node_modules 和 lock 文件，全新安装

**Comment by ZhangXDong** [comment]
> 删除 node_modules 和 lock 文件，全新安装

试过了，没有屌用

**Comment by yoyo837** [comment]
请提供复现

**Comment by zombieJ** [comment]
如果你确认 pm2 里提升 dayjs 是安全的，可以考虑webpack alias 直接强行指定到同一个 dayjs

**Comment by ZhangXDong** [comment]
> 可以考虑webpack alias 直接强行指定到同一个 dayjs。这样不管后端怎么样，前端构建是统一的。

按照老板们说了试了一轮，还是不生效，还有办法吗？

<img width="231" alt="image" src="https://github.com/ant-design/ant-design/assets/28100344/33d92348-bcbc-4f0a-a138-46306e2a27b3">

**Comment by afc163** [comment]
@yaoqiang 因为有两个版本的 moment 或 dayjs 的实例存在。

**Comment by wangwufan** [comment]
我也有这个问题，到现在没解决，我这里是datepicker设置范围选择时就会中英混合

**Comment by afc163** [comment]
@wangwufan 来个最小重现仓库我来帮你解决。

**Comment by wangwufan** [comment]
> @wangwufan 来个最小重现仓库我来帮你解决。

解决了，把外部的dayjs版本和antd保持一致就好了

**Comment by woowalker** [comment]
对呀，有其他外部依赖库的怎么解决？第三方库依赖的dayjs版本不一致 @ZhangXDong 楼主解决了吗

**Comment by dsaco** [comment]
![image](https://github.com/user-attachments/assets/3c37076b-442a-4c9b-9f1e-239711e46d9c)

没有安其他依赖，只有antd和@ant-design/nextjs-registry ，datepicker 依然是中英混合

**Comment by dsaco** [comment]
在next.js中，只安装了antd^5.21.4和@ant-design/nextjs-registry^1.0.1
![image](https://github.com/user-attachments/assets/65d274da-6ed7-4fa1-b104-a9d68ef4fcae)

datepicker依然有中英混合的问题

**Comment by 520Qiuyu** [comment]
https://juejin.cn/post/7118609031966490638我是4版本按照官方教程不起作用，使用的这个就好了

**Comment by f3liiix** [comment]
> 在next.js中，只安装了antd^5.21.4和@ant-design/nextjs-registry^1.0.1 ![image](https://github.com/user-attachments/assets/65d274da-6ed7-4fa1-b104-a9d68ef4fcae)
> 
> datepicker依然有中英混合的问题

跟你一样，还是解决不了。
