### ISSUE TITLE
`<Select/>`的属性`onPopupScroll`的`target`存在异常

### ISSUE THREAD

**Issue by Brucia323** [ant-design/ant-design#48990]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fast-flower-jyh2k9?file=%2Findex.js%3A7%2C1-62%2C2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clweo1wng00063p6g1om54j8v%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clweo1wng00023p6gasmbj3la%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clweo1wng00033p6gb9j8xvog%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clweo1wng00053p6gakixft3w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clweo1wng00023p6gasmbj3la%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clweo1wnf00013p6gerzwljmq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A62%252C%2522endColumn%2522%253A2%257D%255D%257D%255D%252C%2522id%2522%253A%2522clweo1wng00023p6gasmbj3la%2522%252C%2522activeTabId%2522%253A%2522clweo1wnf00013p6gerzwljmq%2522%257D%252C%2522clweo1wng00053p6gakixft3w%2522%253A%257B%2522id%2522%253A%2522clweo1wng00053p6gakixft3w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clweo1wng00043p6gw2hogzh1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clweo1wng00043p6gw2hogzh1%2522%257D%252C%2522clweo1wng00033p6gb9j8xvog%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clweo1wng00033p6gb9j8xvog%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

打开选择器并滚动

### What is expected?

target能打印出scrollTop、scrollHeight等内容，编写代码时类型也包含scrollTop、scrollHeight等。

### What is actually happening?

target打印出的是元素，类型也没有scrollTop、scrollHeight等。

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.2.0 |
| System | macOS 14.5 (23F79) |
| Browser | Edge 125.0.2535.51 |

**Comment by wanpan11** [comment]
你需要访问回调参数对象里面的 target

![image](https://github.com/ant-design/ant-design/assets/38714194/bec15350-4315-449c-9123-4b910cfae509)

![image](https://github.com/ant-design/ant-design/assets/38714194/5cadc293-5910-4d99-a208-78e329b7736c)

**Comment by afc163** [comment]
```
onPopupScroll={(e) => {
  console.log(e.target.scrollHeight);
}}
```

**Comment by Brucia323** [comment]
但是没有类型
