### ISSUE TITLE
Table 虚拟滚动暂无数据时无法横向拖动

### ISSUE THREAD

**Issue by hairgc** [ant-design/ant-design#48991]
### Reproduction link

[https://ant.design/components/table-cn#components-table-demo-virtual-list](https://ant.design/components/table-cn#components-table-demo-virtual-list)

### Steps to reproduce

1、打开官网Table 虚拟滚定demo
2、缩小屏幕尺寸至出现横向滚动条
3、切换数据为‘None‘

### What is expected?

与普通表格体验一致，可以横向拖动，以便查看所有列

### What is actually happening?

列直接被遮住，无横向滚动条可以拖动，甚至某些情况列标题被遮住一半，非常丑

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.2.0 |
| System | Win10 |
| Browser | Chrome120 |

**Comment by linxianxi** [comment]
录个视频？

**Comment by hairgc** [comment]
> 录个视频？
如图，Age后的列被遮住了
![image](https://github.com/ant-design/ant-design/assets/22745354/43a7a06f-a2fc-48ff-be4b-432111a1ca57)
