### ISSUE TITLE
Watermark在Safari浏览器上面无效

### ISSUE THREAD

**Issue by cdx111** [ant-design/ant-design#49006]
### Reproduction link

[https://ant.design/components/watermark-cn](https://ant.design/components/watermark-cn)

### Steps to reproduce

用Safari浏览器打开就可以看到没有水印效果

### What is expected?

正常显示水印

### What is actually happening?

没有正常显示水印

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18 |
| System | macos |
| Browser | 版本15.6.1 (15613.3.9.1.16, 15613) |

**Comment by zombieJ** [comment]
https://ant-design.antgroup.com/components/watermark-cn  用国内镜像访问，展示不出来应该是网络资源请求挂哈~

**Comment by cdx111** [comment]
> https://ant.design/components/watermark-cn

这个跟网络资源没有关系是一个bug，你可以用Safari浏览器打开看看
<img width="1481" alt="image" src="https://github.com/ant-design/ant-design/assets/39432333/41d2def3-260d-4605-ac2d-efd037f7e610">

**Comment by cdx111** [comment]
Safari 版本15.6.1 (15613.3.9.1.16, 15613)

**Comment by cdx111** [comment]
目前看来是跟默认rotate的angle有关系，但是其他浏览器并没有发现这个问题

**Comment by yoyo837** [comment]
17 下是好的，蹲个15的版本...

**Comment by cdx111** [comment]
> 17 下是好的，蹲个15的版本...

我发现跟rotate角度有关系，如果是0就没有问题

**Comment by cdx111** [comment]
目前加个width解决了问题

**Comment by zombieJ** [comment]
怪不得我这边复现不出来，Safari bug fix 跟着系统走。这应该是很难去修了。
