### ISSUE TITLE
Popover not working properly when use in Iframe (Eg: react-frame-component)

### ISSUE THREAD

**Issue by damdauvaotran** [ant-design/ant-design#49007]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/brave-lamarr-m4df74)

### Steps to reproduce

- Using Popover inside iframe (In this case, I using react-frame-component)
- Click the button have popover in iframe
- Re-click the button
- The popup flash before disappearing

### What is expected?

Popup of Popover display in the right place relatively with children

### What is actually happening?

Popup have css property `inset: -1000vh auto auto -1000vw;`, make it disappear from UI

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18 |
| System | Linux |
| Browser | Chrome Version 125.0.6422.60, Firefox |

**Comment by zombieJ** [comment]
I've debug the code find that the element in iframe will get empty `ref`. Which makes trigger can not get correct position of target & popup element (both ref return `null`).

Pls feel free to check `react-frame-component` doc for more info to how to pass data between fames. It's nothing magic to fill `ref` on antd side.

**Comment by damdauvaotran** [comment]
@zombieJ  I have debugged the code too and found out that `targetEle` is undefined because isDom returns false set in function https://github.com/react-component/trigger/blob/master/src/index.tsx#L264. 

![image](https://github.com/ant-design/ant-design/assets/18672186/6ce1e4af-6eb2-491f-9dc7-ce7365247dc5)

And when debug [isDom function](https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts#L7), I find that `instanceof HTMLElement` does not work in iframe

https://stackoverflow.com/questions/26248599/instanceof-htmlelement-in-iframe-is-not-element-or-object
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms
![image](https://github.com/ant-design/ant-design/assets/18672186/e76628c4-d441-4353-9405-dcc8de1b41e7)

Does this consider as bug

**Comment by damdauvaotran** [comment]
I have temporarily solved this by overwrite `iframeWindow.HTMLElement.prototype` with `HTMLElement.prototype`, to make `node instanceof HTMLElement` work in iframe

```typescript
  ref={(ref) => {
        if (ref) {
          ref.onload = () => {
            const iframeWindow = ref?.content window;
            if (iframeWindow) {
              Object.setPrototypeOf(
                iframeWindow.HTMLElement.prototype,
                HTMLElement.prototype,
              );
            }
          };
        }
      }}
```
