### ISSUE TITLE
.lock 缺少依赖包的版本锁

### ISSUE THREAD

**Issue by Yolo-00** [ant-design/ant-design#49000]
### What problem does this feature solve?

当一个开发者fork后 clone 代码需要下载依赖包时没有.lock文件；
.lock 文件能更好的解决不同开发者使用不同的node版本下载依赖版本的统一性

### What does the proposed API look like?

新增 .lock

**Comment by zombieJ** [comment]
antd 的 CI 会确保最新的依赖是可靠的，如果构建出了问题社区成员也会快速响应。只有在很少数情况下，我们会临时锁一下。对于活跃的项目，高频更新依赖锁反而得不偿失哈~
