### ISSUE TITLE
Form.useWatch doesn't return initial values

### ISSUE THREAD

**Issue by alex-golubtsov** [ant-design/ant-design#49010]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/basic-antd-5-14-1-forked-7h2g7q?file=%2Fdemo.tsx)

### Steps to reproduce

- Open the reproduction link and browser console there
- You'll see a log like `form instance: John watcher: undefined`

This means `John` value comes from `useFormInstance` and `undefined` comes from `useWatch`

### What is expected?

I'd expect both values to be equivalent

### What is actually happening?

`useWatch` returns `undefined` value for a field, but in reality it's defined by `Form`'s `initialValues`

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18 |
| System | Mac OS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Your codesandbox is private. Please help set it to public~

**Comment by alex-golubtsov** [comment]
@zombieJ right, I'm sorry, just made public

**Comment by shiyangzhaoa** [comment]
The first return of `useWatch` is undefined, not initial values. 
react-hook-form also has this problem, but provides `defaultValue` props.
https://react-hook-form.com/docs/usewatch

**Comment by crazyair** [comment]
> The first return of `useWatch` is undefined, not initial values. react-hook-form also has this problem, but provides `defaultValue` props. https://react-hook-form.com/docs/usewatch

`const name = useWatch('name') ?? 'zhangsan'`

**Comment by shiyangzhaoa** [comment]
> > The first return of `useWatch` is undefined, not initial values. react-hook-form also has this problem, but provides `defaultValue` props. https://react-hook-form.com/docs/usewatch
> 
> `const name = useWatch('name') ?? 'zhangsan'`

What if I clear it manually? For example, `Select` with `allowClear`.

**Comment by crazyair** [comment]
> > > The first return of `useWatch` is undefined, not initial values. react-hook-form also has this problem, but provides `defaultValue` props. https://react-hook-form.com/docs/usewatch
> > 
> > 
> > `const name = useWatch('name') ?? 'zhangsan'`
> 
> What if I clear it manually? For example, `Select` with `allowClear`.


you can 😁

```tsx
const nameHasDefaultValue = useWatch('name') ?? 'zhangsan'
const name = useWatch('name')
```


`useWatch` is listening to `Form.Item`, and the first execution of `useWatch`, `Form.Item` has not been loaded yet, so it is undefined

**Comment by shiyangzhaoa** [comment]
> > > > The first return of `useWatch` is undefined, not initial values. react-hook-form also has this problem, but provides `defaultValue` props. https://react-hook-form.com/docs/usewatch
> > > 
> > > 
> > > `const name = useWatch('name') ?? 'zhangsan'`
> > 
> > 
> > What if I clear it manually? For example, `Select` with `allowClear`.
> 
> you can 😁
> 
> ```tsx
> const name = useWatch('name')
> const nameHasDefaultValue = name ?? 'zhangsan'
> ```
> 
> `useWatch` is listening to `Form.Item`, and the first execution of `useWatch`, `Form.Item` has not been loaded yet, so it is undefined

😆😆😆
I said, `Select` with `allowClear`. Yes, just like your code:
```ts
const App: React.FC = () => {
  const [form] = Form.useForm();

  const name = Form.useWatch("name", form);
  const nameHasDefaultValue = name ?? "John";

  return (
    <Form form={form} initialValues={{ name: "John" }}>
      <Form.Item label="Name" name="name">
        <Select
          options={[
            {
              label: "😄",
              value: "John",
            },
            {
              label: "😭",
              value: "Roy",
            },
          ]}
          allowClear
        />
      </Form.Item>
      value: {nameHasDefaultValue}
    </Form>
  );
};
```
Guess what the value of name will become if I click clear? It will become `John`. Why?
[Example](https://codesandbox.io/p/sandbox/antd-usewatch-problem-forked-ctyy9t?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwhfq2ii00073b6krehxunja%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwhfq2ii00033b6k9rhgpvkc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwhfq2ii00043b6ki27gg7km%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwhfq2ii00063b6k881ufnu7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwhfq2ii00033b6k9rhgpvkc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhfq2ii00023b6klgw9mud7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwhfq2ii00033b6k9rhgpvkc%2522%252C%2522activeTabId%2522%253A%2522clwhfq2ii00023b6klgw9mud7%2522%257D%252C%2522clwhfq2ii00063b6k881ufnu7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhfq2ii00053b6k3glob129%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwhfq2ii00063b6k881ufnu7%2522%252C%2522activeTabId%2522%253A%2522clwhfq2ii00053b6k3glob129%2522%257D%252C%2522clwhfq2ii00043b6ki27gg7km%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwhfq2ii00043b6ki27gg7km%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
I'm just raising this question, I understand that it returns undefined the first time, but I hope there is a solution similar to react-hook-form.

**Comment by zombieJ** [comment]
As @crazyair said. `useWatch` listen the value from register field. But when the first render, field is not ready yet (useWatch is called before return children render). It will trigger another around to filled with `initialValues` when field register.

**Comment by esrk** [comment]
Using this custom hook which returns the form's value if `Form.useWatch` returns `undefined`.

```javascript
/**
* Wrapper of Form.useWatch to handle initial render race condition.
* Form.useWatch always yields undefined in the first render.
* This wrapper handles that by sending the value from form.getFieldValue if the watched value is undefined.
* This will get corrected from second render.
* @see https://github.com/ant-design/ant-design/issues/49010#issuecomment-2123979311
* @param {string|string[]} field - Field Name.
* @returns {*} Watched value
*/
export const useWatch = (...args) => {
  const form = Form.useFormInstance();
  const value = Form.useWatch(...args);
  return value !== undefined ? value : form.getFieldValue(args[0);
};
```

**Comment by binh1298** [comment]
> As @crazyair said. `useWatch` listen the value from register field. But when the first render, field is not ready yet (useWatch is called before return children render). It will trigger another around to filled with `initialValues` when field register.

I propose that it should register when useForm() is first called, maybe allow passing initialValues in there. I think this behavior is quite confusing, especially for people coming from react-hook-form

**Comment by crazyair** [comment]
> > As @crazyair said. `useWatch` listen the value from register field. But when the first render, field is not ready yet (useWatch is called before return children render). It will trigger another around to filled with `initialValues` when field register.
> 
> I propose that it should register when useForm() is first called, maybe allow passing initialValues in there. I think this behavior is quite confusing, especially for people coming from react-hook-form

The `initialValues` are executed after `useWatch`, so `useWatch` doesn't know what the name is for the first time

```tsx
const [form] = Form. useForm()
const name= Form.useWatch('name',form)
<Form initialValues={{ name: 'zhangsan'}} 
```

**Comment by jefferyssy** [comment]
antd能否改成
 通过 Form.useForm({ name: 'zhangsan' }), 设置默认值
这样初始化的值，在hooks中以及存在，这个时候 useWatch，也能拿到了

**Comment by crazyair** [comment]
```tsx
  const [form] = Form.useForm<{ name: string }>();
  const initName = form.isFieldTouched('name') ? undefined : 'init';
  const nameValue = Form.useWatch('name', form) || initName;
```
https://stackblitz.com/edit/react-fpk9br?file=demo.tsx

**Comment by yuki2006** [comment]
The initial undefined return from Form.useWatch([], form) is understood. However, there's a type safety issue for TypeScript users.   

When using FormInstance<T>, Form.useWatch([], form) infers the return type as T, but the actual initial return value is undefined. This mismatch bypasses static checks and can lead to runtime errors.

Proposal:
Could the TypeScript definition for Form.useWatch([], form) (when used with FormInstance<T>) be updated to return T | undefined?

This would accurately reflect the runtime behavior, enforce safer access patterns (?. / ?? ), and align with similar hooks in other libraries.   

Thank you for considering this improvement for TypeScript users.
