### ISSUE TITLE
Ability to keep 'RangePicker' open at all times

### ISSUE THREAD

**Issue by Nosherwan** [ant-design/ant-design#49012]
### What problem does this feature solve?

Recent design trends show that components like RangePicker are now displayed in a separate floating div above other components when required.
In such a view the RangePicker doesn't need to change visibility when selected & needs to remain open at all times regardless of interaction.
This feature is highly valued, especially for the RangePicker, and I request its inclusion.

### What does the proposed API look like?

```js
<RangePicker
        defaultValue={[
          dayjs('2015-06-06', dateFormat),
          dayjs('2015-06-06', dateFormat),
        ]}
        disabled={[false, false]}
        showTime
        stayOpen={true} OR embeddedView={true}
      />
```

**Comment by zombieJ** [comment]
What's the difference with current `open` prop?

```tsx
<RangePicker open />
```

**Comment by Nosherwan** [comment]
Thanks @zombieJ some how I didnt see it in the docs, that is what was required.
