### ISSUE TITLE
使用Antd 任意组件影响全局 dayjs 错误解析 gggg-ww 格式

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design#49015]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/faner11/procomponents-dayjs/draft/condescending-knuth)
github 仓库
https://github.com/faner11/procomponents-dayjs
### Steps to reproduce

```
// import { Button,DatePicker } from 'antd';
import dayjs from 'dayjs';
/**
 * 如果注释DatePicker/ Button 值为 2024-02-01 00:00:00
 * 如果不注释DatePicker/ Button 值为 2024-05-20 00:00:00 ，日期为当天
 */
function App() {
  return (
    <>
    {dayjs("2024-02","gggg-ww").format("YYYY-MM-DD HH:mm:ss")}
    {/* <DatePicker/> */}
    {/* <Button>222</Button> */}
    </>
  )
}
export default App

```

放开注释即可

### What is expected?

无论是否使用Antd 组件 dayjs 解析gggg-ww结果都一致

### What is actually happening?

使用Antd 组件后 dayjs 解析gggg-ww结果不一致

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.3 |
| System | mac os |
| Browser | chrome |

**Comment by Wxh16144** [comment]
复现地址404...

**Comment by faner11** [comment]
@Wxh16144 可能是权限问题，你直接访问仓库吧 
https://github.com/faner11/procomponents-dayjs

**Comment by Wxh16144** [comment]
感觉像 dayjs 的 bug 🤔

```tsx
import dayjs from 'dayjs'
import advancedFormat from 'dayjs/plugin/advancedFormat'
import weekOfYear from 'dayjs/plugin/weekOfYear'
import weekYear from 'dayjs/plugin/weekYear'

dayjs.extend(weekOfYear)
dayjs.extend(weekYear)
dayjs.extend(advancedFormat)

dayjs('2024-02', 'gggg-ww', true).format('YYYY-MM-DD HH:mm:ss') // Invalid Date

```

**Comment by Wxh16144** [comment]
> 感觉像 dayjs 的 bug 🤔

估计和 https://github.com/ant-design/ant-design/issues/43246#issuecomment-1667592164 问题一样，不支持反向 format ...

CC. @iamkun

**Comment by faner11** [comment]
@Wxh16144  我和你使用了同样的代码，我是正常的
```
import dayjs from 'dayjs';
import advancedFormat from 'dayjs/plugin/advancedFormat'
import weekOfYear from 'dayjs/plugin/weekOfYear'
import weekYear from 'dayjs/plugin/weekYear'
dayjs.extend(weekOfYear)
dayjs.extend(weekYear)
dayjs.extend(advancedFormat)

console.log(dayjs("2024-02","gggg-ww",true).format("YYYY-MM-DD HH:mm:ss")); // 2024-02-01 00:00:00
```

**Comment by zombieJ** [comment]
dayjs 需要使用 WeekOfYear 插件才能支持 `ww` 格式。你在不使用 antd 组件的时候，相当于没有配置插件状态。dayjs 对于不支持的格式会进行模糊匹配，然后把 `ww` 当成月份转换（你的代码中 `2024-02` 并没有正确转换成对应的时间）。

在 antd 中，当你使用组件会被引入 WeekOfYear 插件，所以它会按照 `ww` 来匹配。但是由于 dayjs 又不支持 `ww` 解析。所以被降级成了当前时间。

这就相当于两个都是错的，我希望错的更一致一些一样。是没有意义的。可以考虑给 dayjs 提 issue 来支持这个能力哈~

**Comment by faner11** [comment]
@zombieJ 我使用了 weekOfYear 插件，解析依然正常，但是使用Antd 组件就 返回 Invalid Date。问题没解决你别关闭呀

**Comment by Wxh16144** [comment]
> 我使用了 weekOfYear 插件，解析依然正常

你是指 `dayjs().format('gggg-ww')` 这样的用法正确么？

**Comment by faner11** [comment]
dayjs().format('gggg-ww') 无论是否使用Antd 都是正确的

出问题的是 dayjs("2024-02","gggg-ww",true).format("YYYY-MM-DD HH:mm:ss")

**Comment by zombieJ** [comment]
> @zombieJ 我使用了 weekOfYear 插件，解析依然正常，但是使用Antd 组件就 返回 Invalid Date。问题没解决你别关闭呀

`2024-02` 按照 `gggg-ww` 解析出来的时间怎么可能是 `2024-02-01`，你设置的格式是 ***周*** 不是 ***月***。`2024-02` 按照周格式解析出来是 `2024-01-08` ~ `2024-01-14` 这个时间段。

再看一下我的描述？~

**Comment by faner11** [comment]
@zombieJ 对哦，没注意，时间也是错的
