### ISSUE TITLE
Form Item dependencies doesn't work with array NamePaths like ['parent','child']

### ISSUE THREAD

**Issue by igloo12** [ant-design/ant-design#49013]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-gs5ev3?file=demo.tsx)

### Steps to reproduce

Create two input items with NamePaths that are arrays and set the dependencies to each other. e.g dependencies={['a','password']}.

I updated the example on https://ant.design/components/form#components-form-demo-dependencies to show the issue. See link to reproduce https://stackblitz.com/edit/react-gs5ev3?file=demo.tsx

### What is expected?

That it works the same as  dependencies={'password'}

### What is actually happening?

The dependency is not updating

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.3.2 |
| System | MAC OS |
| Browser | Chrome |

**Comment by afc163** [comment]
```diff
- dependencies={['a','password']}
+ dependencies={[['a','password']]}
```
