### ISSUE TITLE
TextArea: e.target.setSelectionRange not work

### ISSUE THREAD

**Issue by OCISHY** [ant-design/ant-design#49016]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-evcore-ehnv3q?file=demo.tsx)

### Steps to reproduce

在输入框中输入内容 onChange中执行 setSelectionRange 不会重置光标位置

### What is expected?

希望 setSelectionRange 生效，可以充值光标位置

### What is actually happening?

setSelectionRange 不生效

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome |

---
在 antd@5.6.1 中 setSelectionRange 和 selectionStart 都可以工作，在antd@5.12.7 中两者都不能工作，在最新版 antd@5.17.3 中selectionStart 正常， 应该和 issue #47779 问题类似

**Comment by OCISHY** [comment]
antd 5.17.14 里面 rc-textarea 1.7.0 还是依赖的 rc-input 1.5.0， 大佬能不能把input相关的 rc-input依赖都更新到1.5.1 @zombieJ

**Comment by afc163** [comment]
@OCISHY 移除 lock 文件重新安装 node_modules 即可。

**Comment by OCISHY** [comment]
[https://github.com/react-component/textarea/blob/master/package.json](url)
textarea 库依赖的还是 rc-input 1.5.0

**Comment by afc163** [comment]
~1.5.0 是包含 1.5.1 的，你按照我的建议做操作了么？

**Comment by yoyo837** [comment]
lock和node_moduels都要删

**Comment by OCISHY** [comment]
解决了 thx 是因为组件 peerdep 的 rc-input没带~符号
