### ISSUE TITLE
vite 配置babel打包后，发布公司内网访问antd样式全部丢失。

### ISSUE THREAD

**Issue by WaQuio** [ant-design/ant-design#49027]
### Reproduction link

[http://172.33.544](http://172.33.544)

### Steps to reproduce

1. 链接为公司内网，无法访问
import { defineConfig } from "vite";
import path from "path";
import react from "@vitejs/plugin-react";
import babel from "vite-plugin-babel";

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    target: "es2015",
  },
  plugins: [react(), babel()],
  resolve: {
    alias: {
      "@/": `${path.resolve(process.cwd(), "src")}/`,
    },
  },
  optimizeDeps: {
    include: ["react-dom", "classnames"],
  },
  css: {
    // 配置 css-module
    modules: {
      // 开启 camelCase 格式变量名转换
      localsConvention: "camelCase",
      // 类名 前缀
      generateScopedName: "[local]-[hash:base64:5]",
    },
    preprocessorOptions: {
      less: {
        // 支持内联 JavaScript
        javascriptEnabled: true,
      },
    },
  },
});

### What is expected?

正常样式

### What is actually happening?

全局样式丢失

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18 |
| System | windows |
| Browser | 谷歌浏览器 |

**Comment by yoyo837** [comment]
这个我们无能为力

**Comment by WaQuio** [comment]
> 我们无休止力

这个我确实没有办法demo复现，就是发布之后，审查元素也没有ant design的样式。 可能的原因是什么呢？是不是vite-plugin-babel 导致的呢？可以给一个思路吗

**Comment by WaQuio** [comment]
![Uploading 微信图片_20240522214757.png…]()

**Comment by yoyo837** [comment]
可以删除一下业务代码留下最小可复现的zip丢一个上来

**Comment by ybf970928** [comment]
请使用 alias: {
      '@': path.resolve(__dirname, '../src'),
    }
```
__dirname
```
