### ISSUE TITLE
React does not recognize the `currentSlide`(or `slideCount`) prop on a DOM element.

### ISSUE THREAD

**Issue by hoooooojjjj** [ant-design/ant-design#49028]
### Reproduction link

[https://github.com/hoooooojjjj/carousel-bug-repro/blob/main/src/App.js](https://github.com/hoooooojjjj/carousel-bug-repro/blob/main/src/App.js)

### Steps to reproduce

1. Carousel component -> props: arrows={true}
2. npm run start 
3. see console

### What is expected?

Carousel component working well. and console is clean

### What is actually happening?

Carousel component still working well. but console say : warning! React does not recognize the `currentSlide`(or `slideCount`) prop on a DOM element. 

I remove props(arrows={true}), console is clean. but l add props(arrows={true}), console say : warning! React does not recognize the `currentSlide`(or `slideCount`) prop on a DOM element.

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.3.1 |
| System | mac, vscode |
| Browser | chrome |

**Comment by yoyo837** [comment]
Caused by https://github.com/ant-design/ant-design/pull/48542

**Comment by yoyo837** [comment]
> > Caused by #48542
> 
> Is the bug fixed?

FIxed in https://github.com/ant-design/ant-design/pull/49031.

**Comment by hoooooojjjj** [comment]
> > > Caused by #48542
> > 
> > 
> > Is the bug fixed?
> 
> FIxed in #49031.

Is it reflected in the current andt version?

**Comment by hoooooojjjj** [comment]
> > > > Caused by #48542
> > > 
> > > 
> > > Is the bug fixed?
> > 
> > 
> > FIxed in #49031.
> 
> Is it reflected in the current andt version?

can i use props(arrows={true}) ?

**Comment by yoyo837** [comment]
> Is it reflected in the current andt version?

No, it will be included in a new version released this weekend.

**Comment by hoooooojjjj** [comment]
> No, it will be included in a new version released this weekend.

okey :) thank you!

**Comment by weeptao** [comment]
5.20.2版本中仍然报错 `React does not recognize the `currentSlide` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `currentslide` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by afc163** [comment]
@weeptao 给个重现？
