### ISSUE TITLE
Tree 组件通过 switchIcon 修改图标后会旋转 90 度

### ISSUE THREAD

**Issue by huangkairan** [ant-design/ant-design#49037]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-6lkbww?file=demo.tsx,index.css)

### Steps to reproduce

配置switchIcon

### What is expected?

配置 switchIcon 时图标不旋转

### What is actually happening?

关闭图标旋转90度

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18 |
| System | macos 14 |
| Browser | 版本 124.0.6367.208（正式版本） (arm64) |

**Comment by wanpan11** [comment]
应该这样 switchIcon 换的是最前面的那个箭头
文档可以优化下 写清楚点

![b25a1c7a0e241581e78a2b39699cb84cc989cac3157113947e493ae5bb23b08cQzpcVXNlcnNcd2FucGFuXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1w1MDc1MjIzOTdfdjJcSW1hZ2VGaWxlc1wxNzE2NDUxNzQwMzQ4XzA0RTM1NDRDLTk0MTAtNGQyZS1BMjhFLUMzRDY0RkU1QTgyMi5wbmc=](https://github.com/ant-design/ant-design/assets/38714194/a4dfe358-989a-4d66-b3aa-2d4da6c0bcd8)

**Comment by huangkairan** [comment]
> 应该这样 switchIcon 换的是最前面的那个箭头 文档可以优化下 写清楚点
> 
> ![b25a1c7a0e241581e78a2b39699cb84cc989cac3157113947e493ae5bb23b08cQzpcVXNlcnNcd2FucGFuXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1w1MDc1MjIzOTdfdjJcSW1hZ2VGaWxlc1wxNzE2NDUxNzQwMzQ4XzA0RTM1NDRDLTk0MTAtNGQyZS1BMjhFLUMzRDY0RkU1QTgyMi5wbmc=](https://private-user-images.githubusercontent.com/38714194/333101876-a4dfe358-989a-4d66-b3aa-2d4da6c0bcd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTM1ODQsIm5iZiI6MTcxNjQ1MzI4NCwicGF0aCI6Ii8zODcxNDE5NC8zMzMxMDE4NzYtYTRkZmUzNTgtOTg5YS00ZDY2LWIzYWEtMmQ0ZGE2YzBiY2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA4MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjUwMDhlNDQxZWJkZGY4OWM4YmJjYTM1NTViZGZmMTMxNDEzZGFmMDI5NjI0NDhiMmU0ZDEzMTlkMDBkZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ACKvliUU5zxr3ebu5Q-iqrlIStZkpCf8_dXd6oTnGO8)

我觉得这个箭头既然开放了更换的口子，且同时支持配置 close 和 open ，就应该取用户配置的 icon。
我知道用 icon 是可以配的，但通过 switchIcon 配的时候挺反直觉的

**Comment by wanpan11** [comment]
感觉应该是历史遗留问题 🤣

**Comment by afc163** [comment]
1. 我猜你需要：https://ant.design/components/tree-cn#components-tree-demo-directory
2. 可以重置相关 rotate：https://stackblitz.com/edit/react-6lkbww-w3cexg?file=demo.tsx,index.css
