### ISSUE TITLE
Input 放置拖拽元素后，设置光标位置，光标不闪烁

### ISSUE THREAD

**Issue by CristalFJJ** [ant-design/ant-design#49032]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jm8sjh?file=%2Findex.js%3A5%2C1)

### Steps to reproduce

1、将标签变量拖入Input文本域
2、光标位置移动正常，但是不会闪烁

### What is expected?

期望光标正常闪烁

### What is actually happening?

光标不闪烁

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.1 |
| System | windows 10 |
| Browser | chrome 124.0.6367.92 |

**Comment by afc163** [comment]
我试了以下场景：

1. Firefox，没有这个问题。
2. 去掉 antd，改成原生 textarea 原生，依然有这个问题。

这应该是 Chrome 本身的一个 bug，我目前判断和 antd 无关。

**Comment by CristalFJJ** [comment]
多谢，确实原生也有这个问题
