### ISSUE TITLE
Theme not working/supported for Menu Overlays from DropDown

### ISSUE THREAD

**Issue by ctalpandey** [ant-design/ant-design#4903]
#### Environment(required)

- antd version: Refer ####Re-producible online demo
- OS and its version: Refer ####Re-producible online demo
- Browser and its version: Refer ####Re-producible online demo

#### What did you do? Please provide steps to re-produce your problem.

Refer ####Re-producible online demo. Just added theme='dark' for menu in the Basic Example from [antd-dropdown](https://ant.design/components/dropdown/).

#### What do you expected?

The dropdown menu to appear with dark theme on hover over 'Hover Me'.

#### What happen?

The dropdown menu appeared with default/light theme.

#### Re-producible online demo

http://codepen.io/ctalpandey/pen/WRWbwN?editors=1111

It's forked from http://codepen.io/benjycui/pen/KgPZrE?editors=001.

**Comment by ctalpandey** [comment]
Actually I am able to change the background-color using style prop for Menu. However when SubMenu is present in Menu list, its right-Expand-Menu-Arrow (.ant-dropdown-menu-submenu-title:after) remains black i.e. rgba(0, 0, 0, 0.43) and it can't be changed. Appreciate, if you can give example where this arrow can be changed (unless supported with theme for dowdown-overlay menu).

**Comment by benjycui** [comment]
Just follow the design..

![image](https://cloud.githubusercontent.com/assets/3580607/23016146/815b1034-f470-11e6-91a1-424d3e5a684b.png)

**Comment by ctalpandey** [comment]
Sorry, I did not get it! Check below codepens:

http://codepen.io/ctalpandey/pen/vgMXGz?editors=1111
http://codepen.io/ctalpandey/pen/WRWbwN?editors=1111

Both codepens are same except the later codepen has `theme='dark'` added to Menu props, but still result is same i.e. theme is light in both cases (i.e. in dropdown menu)

**Comment by benjycui** [comment]
According to our design, there is no dark theme in dropdown menu.

**Comment by ctalpandey** [comment]
Thx [afc163](https://github.com/afc163)!
