### ISSUE TITLE
Modal.confirm onOk 函数返回值为「真值」时不会自动关闭弹窗

### ISSUE THREAD

**Issue by AnaniZhu** [ant-design/ant-design#49034]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/6h4929?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce

点击页面「确认」按钮即可复现

### What is expected?

行为应该跟无返回值一致，点击「确认」按钮自动关闭

### What is actually happening?

点击页面「确认」按钮不自动关闭弹窗

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="575" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/d3faa3fa-e4b7-4506-aa0b-e37dde7cc823">

**Comment by AnaniZhu** [comment]
> <img alt="图片" width="575" src="https://private-user-images.githubusercontent.com/507615/333074073-d3faa3fa-e4b7-4506-aa0b-e37dde7cc823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjExNzIsIm5iZiI6MTcxNjQ2MDg3MiwicGF0aCI6Ii81MDc2MTUvMzMzMDc0MDczLWQzZmFhM2ZhLWU0YjctNDUwNi1hYTBiLWUzN2RkZTdjYzgyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMDQxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YWZjYjI2NDk5YTc3ZmQ3NDhlYzkxZWY0NDI2N2MxMDIwOGM0NDlhOGY4NGNjYjllM2FhMjdlYzU5MzY4OWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PqPzmDKwa_r5wOmZKef8UWXlTZ_-XadwHp9M-a-Q6W0">

不好意思，权限忘开了，访问下这个链接试试：[点击打开](https://codesandbox.io/p/devbox/6h4929?file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwiwho8700063b6h9rjgcgko%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwiwho8700023b6hk6056cxj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwiwho8700043b6hyeol2ufd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwiwho8700053b6h5e32285k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwiwho8700023b6hk6056cxj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwiwho8700013b6ha41gaddz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwiwmnwf00023b6hxp1g8d44%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwiwho8700023b6hk6056cxj%2522%252C%2522activeTabId%2522%253A%2522clwiwmnwf00023b6hxp1g8d44%2522%257D%252C%2522clwiwho8700053b6h5e32285k%2522%253A%257B%2522id%2522%253A%2522clwiwho8700053b6h5e32285k%2522%252C%2522activeTabId%2522%253A%2522clwiwibo0008j3b6he2is49ug%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clwiwibo0008j3b6he2is49ug%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwiwho8700043b6hyeol2ufd%2522%253A%257B%2522id%2522%253A%2522clwiwho8700043b6hyeol2ufd%2522%252C%2522activeTabId%2522%253A%2522clwiwi3i5006l3b6haqwx6pc5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwiwho8700033b6hfk5hfoym%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwiwhons000adhf81ich1onz%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clwiwi3i5006l3b6haqwx6pc5%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by wanpan11** [comment]
目前好像确实是有问题

![image](https://github.com/ant-design/ant-design/assets/38714194/ba176b13-d3eb-4283-8258-b42ba72acb63)
