### ISSUE TITLE
variant可以全局设置吗，同时暗黑模式variant展示有问题

### ISSUE THREAD

**Issue by zhaoyinger623** [ant-design/ant-design#49040]
### Reproduction link

[https://ant-design.antgroup.com/components/select-cn](https://ant-design.antgroup.com/components/select-cn)

### Steps to reproduce

我们想给系统的所有表单组件variant设置为filled，是否有全局覆盖的方法。此外暗黑模式下，表单错误样式异常。

### What is expected?

1. 未找到可以全局覆盖的方法。
2. 
![image](https://github.com/ant-design/ant-design/assets/62292666/f2e305ae-f084-475e-a82d-eb770a9a970d)

### What is actually happening?
![image](https://github.com/ant-design/ant-design/assets/62292666/c76361cc-149e-449a-b221-66e8f4ecd036)

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18 |
| System | Mac |
| Browser | Chorme |

**Comment by skytt** [comment]
附议
