### ISSUE TITLE
新版本Carousel中的onSwipe失效了

### ISSUE THREAD

**Issue by iiwhiiler** [ant-design/ant-design#49045]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jzfnxf-5zjnoq?file=index.js,index.html)

### Steps to reproduce

之前的onSwipe是在滑动结束后，滑动后的卡与之前的卡不一样，才触发， 现在有的swipeEvent还能用，但是一滑动就触发
<Carousel
    autoplay={false}
    dots={false}
    infinite={false}
    swipeEvent={() => {
      console.log(5555556);
    }}
    onSwipe={() => {
      console.log(777777);
    }}
    swipe
    swipeToSlide
    draggable
  >

### What is expected?

滑动到下一张卡后onSwipe触发

### What is actually happening?

onSwipe不生效

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18 |
| System | 1 |
| Browser | google |

**Comment by afc163** [comment]
哪个版本是你预期的行为？
