### ISSUE TITLE
RangePicker resetting selected date on keyboard input

### ISSUE THREAD

**Issue by alisher-aituarov** [ant-design/ant-design#49057]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/range-picker-ant-design-demo-forked-gmtxvp?file=%2Findex.js%3A8%2C15)

### Steps to reproduce

Input `from` date from keyboard, using the mouse click switch to `to` fields, input `to` date from keyboard. Click outside picker (close it)

### What is expected?

Expected to see both date to be saved in RangePicker

### What is actually happening?

The only saved date is the one that entered last

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18.2.0 |
| System | MacOS  |
| Browser | chrome Version 124.0.6367.60 |

---
issue is present in your docs as well

**Comment by afc163** [comment]
<img width="768" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/810b2256-1db4-4170-a10a-062a343b51fb">

**Comment by alisher-aituarov** [comment]
check please now @afc163

**Comment by sc4lr** [comment]
Would love this to be fixed

**Comment by afc163** [comment]
This issue is not closed.
