### ISSUE TITLE
统一基础值类型

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#49058]
### Reproduction link
[复现链接地址](https://stackblitz.com/edit/react-2cq9nj-qe6ks8?file=demo.tsx)

![image](https://github.com/ant-design/ant-design/assets/30885718/ccba4ae0-2dae-49c2-9a37-db69b6cb9809)

### Steps to reproduce

@types/react 的 Key 类型修改为 type Key = number | string | bigint

在 antd 中有些组件的值使用的是 React.Key
有的组件值使用的是 string | number

在过去这并没有什么问题，但在最新的版本中因 Key 的类型修改导致在各个组件中进行值传递时会导致类型报错

### What is expected?

统一基础值类型，要么都为 number | string（或再联合其他类型） 类型，要么都为 React.Key 的类型（或再联合其他类型）

### What is actually happening?

no response

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

**Comment by afc163** [comment]
现在 React.Key 里有个 bigint，难受。

**Comment by guaijie** [comment]
> 现在 React.Key 里有个 bigint，难受。

我升级类型文件之后，看着报红，又决定回退版本了

**Comment by afc163** [comment]
具体问题反馈一下，提供一个重现？这样比较好下手。

**Comment by crazyair** [comment]
antd v4?

**Comment by crazyair** [comment]
fix v5

**Comment by guaijie** [comment]
@crazyair InputNumber 组件不需要支持 bigInt 吗？我那只是一个例子

**Comment by crazyair** [comment]
> @afc163 @crazyair InputNumber 组件不需要支持 bigInt 吗？我那复现只是一个例子

应该都改成泛型的方式，用户想用什么类型，都是用户自己传的

**Comment by crazyair** [comment]
> > @afc163 @crazyair InputNumber 组件不需要支持 bigInt 吗？我那复现只是一个例子
> 
> 应该都改成泛型的方式，用户想用什么类型，都是用户自己传的

你可以参考 Checkbox 这个对其他组件进行 fix

**Comment by guaijie** [comment]
@crazyair 是否要对所有支持 number 数据类型的组件都让其支持 bigint 类型？

**Comment by crazyair** [comment]
> @crazyair 是否要对所有支持 number 数据类型的组件都让其支持 bigint 类型？

不是给类型增加什么类型，而是用 T

**Comment by crazyair** [comment]
`InputNumberProps<T extends ValueType = ValueType>` 这种约束的直接去掉就可以 `InputNumberProps<T = any>`

**Comment by guaijie** [comment]
> > @crazyair 是否要对所有支持 number 数据类型的组件都让其支持 bigint 类型？
> 
> 不是给类型增加什么类型，而是用 T

我懂你的意思，我想表述的意思是否对所有支持 number  数据类型的组件都改成泛型的形式
![image](https://github.com/ant-design/ant-design/assets/30885718/04c0a386-f3e5-4e42-bef0-2689d2c0e8a5)

**Comment by guaijie** [comment]
> `InputNumberProps<T extends ValueType = ValueType>` 这种约束的直接去掉就可以 `InputNumberProps<T = any>`

当然，ValueType = number | bigint | string 这种类型约束，个人感觉更好。any 意味着任意类型 <InputNumber<number[]> /> 显然不合理

**Comment by crazyair** [comment]
> > `InputNumberProps<T extends ValueType = ValueType>` 这种约束的直接去掉就可以 `InputNumberProps<T = any>`
> 
> 当然，ValueType = number | bigint | string 这种类型约束，个人感觉更好。any 意味着任意类型 <InputNumber<number[]> /> 显然不合理

`<InputNumber value={1} ` 如果这样写了，T 就是 number

**Comment by guaijie** [comment]
> > > `InputNumberProps<T extends ValueType = ValueType>` 这种约束的直接去掉就可以 `InputNumberProps<T = any>`
> > 
> > 
> > 当然，ValueType = number | bigint | string 这种类型约束，个人感觉更好。any 意味着任意类型 <InputNumber<number[]> /> 显然不合理
> 
> `<InputNumber value={1} ` 如果这样写了，T 就是 number

我知道，但也意味着 value 可以传递任何值，因为它已经不受约束了

**Comment by guaijie** [comment]
@crazyair 当然，只是你们很多地方都有进行类型约束，比如 select options ， option.value 等，你们这样的目的，也是想在使用时就提醒到用户可以支持的类型有哪些。
当然，ts 这玩意本来就增加了库作者的负担，所以，我只是提出个人看法

**Comment by afc163** [comment]
InputNumber 目前支持不了 bigint，不只是类型的问题，组件能力还不支持。
