### ISSUE TITLE
Everything related to pop menu doesn't work within antd@^5 in IE11

### ISSUE THREAD

**Issue by simiooo** [ant-design/ant-design#49063]
### Reproduction link

[https://github.com/simiooo/ie11_antd_select_not_showing](https://github.com/simiooo/ie11_antd_select_not_showing)

### Steps to reproduce

1. run pnpm build with pnpm@^8 in reproduction demo
2. serve the artifact with web server software ( I have used nginx or vscode's live server extension)
3. open the page , and click <Select /> component 
4. <Select /> Shows nothing 

### What is expected?

<Select /> show pop panel

### What is actually happening?

The top and left attributes in  the pop-menu inline style css section are botth -9999vw .

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | ^18.3.1 |
| System | windows11 |
| Browser | ie11 |

**Comment by simiooo** [comment]
I found related test snapshot in rc-select above this version
![屏幕截图 2024-05-25 012931](https://github.com/ant-design/ant-design/assets/124264641/0c541299-b3e4-4018-9d8f-029fd5e4cd8d)

**Comment by yoyo837** [comment]
antd@5 don’t support IE 11.

**Comment by afc163** [comment]
antd don't support IE11 since 5.x.
