### ISSUE TITLE
Virtual table with rows of unequal height are rendered incorrectly

### ISSUE THREAD

**Issue by sklinov** [ant-design/ant-design#49078]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-virtual-table-tvnjz4?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwooyeyu00063b6k4v535ydr%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwooyeyu00023b6krsxm0hc8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwooyeyu00033b6kbxzrbsh5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwooyeyu00053b6k05xzc09g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60.27537851915964%252C39.72462148084036%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwooyeyu00023b6krsxm0hc8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwooyeyu00013b6k79v2qcf7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A30%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwooyeyu00023b6krsxm0hc8%2522%252C%2522activeTabId%2522%253A%2522clwooyeyu00013b6k79v2qcf7%2522%257D%252C%2522clwooyeyu00053b6k05xzc09g%2522%253A%257B%2522id%2522%253A%2522clwooyeyu00053b6k05xzc09g%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clwooyeyu00033b6kbxzrbsh5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwooyeyu00033b6kbxzrbsh5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Check out the row with ID=4.
It's pushed outside of visible area because of long content in col2 of row with ID=2.

### What is expected?

Table with variable row height is rendered correctly without clipping

### What is actually happening?

The last rows of the table are clipped if some of the preceding rows overflow with word wrap.

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 17, 18 |
| System | MacOS |
| Browser | Chrome/Arc |

**Comment by zombieJ** [comment]
Pls not ignore the warning from React:

```diff
      <Table
        virtual
        columns={columns}
        dataSource={data}
        scroll={{ x: 500, y: 800 }}
        pagination={false}
++      rowKey="id"
      />
```
