### ISSUE TITLE
Form.Item Rule设置validateTrigger无效

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#49075]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-kcxm6d?file=demo.tsx)

### Steps to reproduce

在Field A中输入

### What is expected?

Field A应该在onBlur时触发验证

### What is actually happening?

Field A没有触发验证
作为对比，Field B将`validateTrigger`放到Form.Item中则正常
![GIF 2024-05-27 14-38-48](https://github.com/ant-design/ant-design/assets/6482819/f6e626df-26f1-49e1-98ee-3b0842dc481c)

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
参考一下官方文档中对 `rule.validateTrigger` 的说明：

<img width="707" alt="截屏2024-05-27 14 42 24" src="https://github.com/ant-design/ant-design/assets/5378891/d04b5566-424e-4c88-b37b-73d8fab77a96">
