### ISSUE TITLE
menu组件中能否考虑给menu.item中添加一个属性,用来传递某些menuitem信息

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#4908]
(1)在menu.item中添加一个属性(例如:value)
(2)调用menu的onClick方法能获取到value属性及值

**Comment by afc163** [comment]
Use `key` to as your primary key to find your data.

```jsx
const menuData = {
  'menu1': { ... },
  'menu2': { ... },
};

handleClick(key) {
  // menuData[key]
}

<Menu onClick={this.handleClick} />
```

**Comment by YaoKaiLun** [comment]
Sometimes the key have prefix, even i never use React.Children.toArray. I think  adding another prop is necessary ( [#817](https://github.com/ant-design/ant-design/issues/817) ).
