### ISSUE TITLE
After entering a value, the Form.List component switches to the next input component in the List to start inputting, and the value entered by the previous component will become empty

### ISSUE THREAD

**Issue by flycj** [ant-design/ant-design#49081]
### Reproduction link

[https://github.com/flycj/antd-form-list-bug](https://github.com/flycj/antd-form-list-bug)

### Steps to reproduce

1. 安装依赖，启动项目
2. 点击首页，点击“添加阶段”按钮
3. 在任意一个输入框输入任意内容后，切换到下一个输入框进行输入，即可重现问题

### What is expected?

在任意一个输入框输入任意内容后，切换到下一个输入框进行输入，上一个输入框的内容不会被清空

### What is actually happening?

在任意一个输入框输入任意内容后，切换到下一个输入框进行输入，上一个输入框的内容会被清空

| Environment | Info |
| --- | --- |
| antd | 5.6.0-5.17.4 |
| React | 18.0.0 |
| System | Win10 |
| Browser | Chrome 113.0.5672.127 |

复现视频如下：
https://github.com/ant-design/ant-design/assets/5103045/7ea6f3fc-f0be-4b7d-a55d-3d592e0e8915

**Comment by afc163** [comment]
还不知道具体为什么，但是 `initialValues` 的值感觉很奇怪，form 的初始值应该是对象，不应该是个数组。

下面三种改法都能修复：

```diff
- <Form form={form} initialValues={[]}>
+ <Form form={form}>
```


```diff
- <Form form={form} initialValues={[]}>
+ <Form form={form} initialValues={{ treatmentPhase: [] }}>
```

```diff
- <Form form={form} initialValues={[]}>
+ <Form form={form} initialValues={{}}>
```

**Comment by flycj** [comment]
> 还不知道具体为什么，但是 `initialValues` 的值感觉很奇怪，form 的初始值在任何情况下都应该是对象，不应该是个数组。
> 
> 下面三种改法都能修复：
> 
> ```diff
> - <Form form={form} initialValues={[]}>
> + <Form form={form}>
> ```
> 
> ```diff
> - <Form form={form} initialValues={[]}>
> + <Form form={form} initialValues={{ treatmentPhase: [] }}>
> ```
> 
> ```diff
> - <Form form={form} initialValues={[]}>
> + <Form form={form} initialValues={{}}>
> ```

I'm very sorry that I didn't notice the issue here. Thank you for your reply
