### ISSUE TITLE
Modal框关闭按钮问题

### ISSUE THREAD

**Issue by liudiming** [ant-design/ant-design#49094]
### Reproduction link

[https://ant.design/components/modal-cn#modalmethod](https://ant.design/components/modal-cn#modalmethod)

### Steps to reproduce

打开modal框，查看右上角关闭按钮

### What is expected?

能正确显示hover效果，还有鼠标移入正确位置才显示hover效果

### What is actually happening?

实际效果是没有正确显示hover效果
![Image_20240528154445](https://github.com/ant-design/ant-design/assets/67784740/0787a9a7-6ef1-4370-bc53-349cbc365e82)

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 17.0.1 |
| System | window 10 |
| Browser | chrome 119.0.6045.160 |

**Comment by liudiming** [comment]
我这是antd v4 升级v5的，升级上来就会这样了

**Comment by yoyo837** [comment]
官网我这边看是正常的，请提供复现
