### ISSUE TITLE
 antd4.24.16Select组件手动将 value 设置为 null，select 应该显示placeholder，但是页面渲染没有改变

### ISSUE THREAD

**Issue by Zrs0105** [ant-design/ant-design#49093]

**Comment by coderz-w** [comment]
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/97cbe82b1619b42e1f78fce9db09104b932a9da1fd37751f4d9c41f4fe350241/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-2rx7gj?file=%2Findex.js%3A8%2C20)
> 
> ### Steps to reproduce
> 先选择“在哪里吃”下拉框，我在“食物下拉框”的 onChange 里将“哪里吃”的 value 设置为了 null，但是“在哪里吃“下拉框没有显示placeholder
> 
> ### What is expected?
> 期望将 value 设置为 null，下拉框显示placeholder
> 
> ### What is actually happening?
> 实际页面渲染没有变，还是显示上一次 value 值
> 
> Environment	Info
> antd	undefined
> React	18.2.0
> System	Mac Os
> Browser	Chrome

![image](https://github.com/ant-design/ant-design/assets/116932167/bf4553b5-101d-484c-8937-4c1274840d33)
