### ISSUE TITLE
静态调用message/Modal无法降级:where

### ISSUE THREAD

**Issue by igwhaler** [ant-design/ant-design#49108]
### What problem does this feature solve?

静态调用message/Modal无法降级:where，后续会考虑修复嘛？

### What does the proposed API look like?

无

**Comment by zombieJ** [comment]
静态方法无法消费 context，也不会读取你的 StyleProvider。请参考官方文档，使用 App 组件调用：
<img width="472" alt="截屏2024-05-29 10 38 39" src="https://github.com/ant-design/ant-design/assets/5378891/1c7059c0-321c-474c-b074-dc7249ea8c92">

**Comment by igwhaler** [comment]
有一些非组件内的场景需要调用message和modal的，既然提供了相关api，不考虑支持下嘛？

**Comment by afc163** [comment]
建议用 useApp。实在要用非 hooks 用法，可以试试 https://ant.design/components/config-provider-cn#configproviderconfig

**Comment by igwhaler** [comment]
问题解决了，代码我们前端团队感谢你！！！

**Comment by elma-cao** [comment]
请问一下，message静态方法后来是怎么解决的？

**Comment by elma-cao** [comment]
@igwhaler 请问后来是怎么解决的？
