### ISSUE TITLE
menu horizontal 菜单一级菜 key为空字符“” 会一直选中默认选中

### ISSUE THREAD

**Issue by rehe0x** [ant-design/ant-design#49106]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ykyvtn?file=demo.tsx)

### Steps to reproduce

一级菜单如果key为空字符串“” 并且下面有子菜单 会默认选中一级菜单 切换到其他还是选中状态

### What is expected?

一级菜单如果key为空字符串“” 并且下面有子菜单不作为默认选中状态

### What is actually happening?

一级菜单如果key为空字符串“” 并且下面有子菜单 会默认选中一级菜单

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18.3.1 |
| System | mac |
| Browser | Chrome arm64 |

---
https://stackblitz.com/edit/react-ykyvtn?file=demo.tsx

查看demo

**Comment by rehe0x** [comment]
![WechatIMG421](https://github.com/ant-design/ant-design/assets/19343192/182adfbe-a63a-4e4a-83b3-9ee71d5e2d26)

**Comment by crazyair** [comment]
首先这个是不是 bug？

**Comment by rehe0x** [comment]
> 首先这个是不是bug？

同样的items vertical 竖形菜单没有这个问题

**Comment by MadCcc** [comment]
空字符串作为 key 确实合法，虽然一般不推荐吧

**Comment by rehe0x** [comment]
> 空洞的谎言确实合法，虽然一般不推荐

路由和菜单的关系  如果菜单有一个附加信息字段就好了

**Comment by Zyf665** [comment]
这个bug是不是应该转到这https://github.com/react-component/menu/issues  我看在组件内部用的是这个组件rc-menu 而且单独使用rc-menu也有同样问题
