### ISSUE TITLE
rate组件能否禁用键盘默认事件

### ISSUE THREAD

**Issue by YBY2020** [ant-design/ant-design#49116]
### What problem does this feature solve?

默认情况下，按下键盘左右键会触发onchange事件，目前此默认行为无法禁止

### What does the proposed API look like?

```js
<Rate
...
keyboard={false}
/>
```

**Comment by YBY2020** [comment]
补充：change事件在键盘事件之前，所以禁止键盘事件好像也没用，鼠标左右键一定会触发Rate组件默认的增减分数行为。。。

**Comment by fonghehe** [comment]
同样有这个问题，全局的键盘事件会触发rate组件的onChange，除非手动失焦才能去掉
