### ISSUE TITLE
Table pagination default styles.

### ISSUE THREAD

**Issue by coljung** [ant-design/ant-design#4911]
Hi there, 

I'm using the **'Table'** component with a very basic table. Pagination appears to be functioning properly.

Now, for some reason, the main styles of the pagination are not being loaded. 

Resulting markup seems to be fine:

```
<ul class="ant-pagination ant-table-pagination" unselectable="unselectable">
    <li title="Previous Page" class="ant-pagination-disabled ant-pagination-prev"><a></a></li>
    <li title="1" class="ant-pagination-item ant-pagination-item-1 ant-pagination-item-active"><a>1</a></li>
    <li title="Next Page" class="ant-pagination-disabled ant-pagination-next"><a></a></li>
    <!-- react-empty: 151 -->
</ul>
```

The problem is the styles. This class '.ant-table-pagination' is compiled into my CSS, but any of the inner CSS classes required for the Pagination to be styled are not there on my compiled CSS.

I tried copying one of the examples on your website using the **'Table'** component. I got the same result:

![image](https://cloud.githubusercontent.com/assets/917671/23029980/4d0bb0da-f43a-11e6-88f7-3df2c1fd8abc.png)

Am i missing something ?

**Comment by afc163** [comment]
Could you provide a re-producible repository for this?

**Comment by coljung** [comment]
I'm not exactly sure whats happening.

I tried using the codepen you guys have: http://codepen.io/anon/pen/mRgpdj?editors=0010 and the styles for the pagination work as expected using the Basic Table example from the website.

On the other hand, if I try the **same** example from within my local component, pagination styles are simply not compiled.

Could it be an issue with the way my webpack is compiling the CSS ? 

On the same page ( and other pages ) I'm using various components which appear to be working fine and having their styles loaded properly ( button, icon, datepicker )

**Comment by NE-SmallTown** [comment]
@coljung If you can't provide a re-producible repository for this.It would be better if you put the screenshot includes the console panel.On the other hand,you also can press F12 and press the esc key in chrome,you will see the 'search' tab,and then you can enter the styles which couldn't work,check whether it will appear.

![](http://i1.piimg.com/567571/bc3a321fca8c891c.gif)

**Comment by coljung** [comment]
I get no errors on compile, and so far the other components I've used, load perfectly with their respective styles ( table, button, icon, calendar, datepicker ).

Below are the only styles being loaded related to pagination.

![image](https://cloud.githubusercontent.com/assets/917671/23139300/bdbbe092-f779-11e6-90ef-9c134de0a9c5.png)


If it helps, i have this setup for babelrc:
 ```
["import", { "libraryName": "antd", "style": true }]]'
```

And for my webpack config I have: 

```
{
	test: /(\.less|\.css)$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader!less-loader'),
},
```

**Comment by benjycui** [comment]
@coljung a re-producible repo is better, thanks.

**Comment by afc163** [comment]
Push you code to a git repo and I will check it.

**Comment by afc163** [comment]
Reopen it if you provide a re-producible repo.

**Comment by coljung** [comment]
Actually i tried to trim down my project and create a repo with it.

It is here: https://github.com/coljung/help-test

I'm aware something is wrong with my webpack config, but so far have been unable to figure out what it is exactly.

I know that right now im using css-loader to compile both css and less, and someone else in here pointed out that is wrong. But, if i try to follow the webpack configuration you guys using from atom-build, i then get all sort of errors, as described here: https://github.com/ant-design/ant-design/issues/4915#issuecomment-282012865

**Comment by benjycui** [comment]
Yep, you repo https://github.com/coljung/help-test shows that why you met issue https://github.com/ant-design/ant-design/issues/4915

But it doesn't show that why you met current issue, it cannot be run for compiling error, please update that repo, thanks.

**Comment by afc163** [comment]
close for can't reproduce it.

**Comment by coljung** [comment]
Yes, i ended up manually including the CSS for pagination. That fixed my issue, although not done properly.

Thx
