### ISSUE TITLE
Table 编辑行 ellipsis 失效 

### ISSUE THREAD

**Issue by yanglufan** [ant-design/ant-design#49128]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-a28av2?file=demo.tsx)

### Steps to reproduce

鼠标放到表格省略字上,无法弹出全部字提示框

### What is expected?

鼠标放到表格省略字上,可以弹出全部字提示框

### What is actually happening?

鼠标放到表格省略字上,无法弹出全部字提示框

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18.3.1 |
| System | windows |
| Browser | 谷歌 |

**Comment by duqigit** [comment]
ellipsis: {
        showTitle: false,
      },
      render: (address) => (
        <Tooltip placement="topLeft" title={address}>
          {address}
        </Tooltip>
      ),


用这个自定义Tooltip试下呢

**Comment by smallbonelu** [comment]
> render: (address) => (
>     <Tooltip placement="topLeft" title={address}>
>       {address}
>     </Tooltip>
>   ),

官方示例就是这样的，应该设计就是如此的

**Comment by MadCcc** [comment]
默认没有 title 或者 tooltip，有需要可以参照上面的自行加一下
