### ISSUE TITLE
Some problems of AutoComplete demo

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#4912]
link: https://ant.design/components/auto-complete/#components-auto-complete-demo-uncertain-category

- Cannot input any text. `IE11`
- Item in popup menu is mis-aligned. `FireFox`
   ![default](https://cloud.githubusercontent.com/assets/507615/23030549/16602a6a-f4a9-11e6-8559-79f96e7c67ec.PNG)
- Should not have border around button. `All Browsers`
![2](https://cloud.githubusercontent.com/assets/507615/23030733/98004898-f4a9-11e6-87d0-10f7f6aa7e48.PNG)

**Comment by afc163** [comment]
Third problem is still existed.

**Comment by RaoHai** [comment]
<img width="523" alt="screen shot 2017-02-20 at 5 24 57 pm" src="https://cloud.githubusercontent.com/assets/566097/23119059/965739f8-f791-11e6-9f1d-0a7217c0c4c5.png">

**Comment by afc163** [comment]
> Should not have border around button.

**Comment by RaoHai** [comment]
..
