### ISSUE TITLE
关于 Tooltip 的 overlayInnerStyle 属性上添加 css样式 可能会出现闪烁情况

### ISSUE THREAD

**Issue by pokeyaro** [ant-design/ant-design#49122]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-tooltip-flash-abnormal-tf8fph?file=%2Findex.js)

### Steps to reproduce

当 如下设置 display = flex，会出现闪烁，如果修复需要在 overlayInnerStyle 上设置，但是 在 overlayStyle 上设置出现闪烁 感觉不太合理
```js
overlayStyle={{
  height: '30px',
   aspectRatio: '2/1',
   display: 'flex',
   alignItems: 'center',
   justifyContent: 'center'
}}
```

### What is expected?

可以内容居中

### What is actually happening?

闪烁

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18.2.0 |
| System | mbp m1 |
| Browser | Chrome 版本 125.0.6422.112（正式版本） (arm64) |

---
自定义外tooltip边框样式

**Comment by afc163** [comment]
用户自定义的 `display: "flex"` 会覆盖用于隐藏 Tooltip 的默认 `display: none;` 样式。建议避开。
