### ISSUE TITLE
Dropdown support extra prop

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#49127]
<img width="389" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/776ab6b3-a19e-4d09-9011-74498094ee29">

```jsx
<Dropdown
  items={[{
    extra: '⌘B',
  }]}
/>
```

**Comment by arvinxx** [comment]
Menu should support too

**Comment by bunnysingh43** [comment]
![IMAGE](https://github.com/ant-design/ant-design/assets/69401878/55cb8fea-7490-45a8-bb77-03204647456e)

abcdefgh

**Comment by bunnysingh43** [comment]
[figmaTokens.json](https://github.com/ant-design/ant-design/files/15497268/figmaTokens.json)

**Comment by coding-ice** [comment]
I want to try this feature.
