### ISSUE TITLE
Select组件通过 dropdownRender 自定义虚拟列表 Table, 提示React does not recognize the offsetX prop on a DOM element

### ISSUE THREAD

**Issue by ybf970928** [ant-design/ant-design#49138]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/select-table-8ff9hf)

### Steps to reproduce

点击选择下拉框

### What is expected?

lowercase `offsetx` instead

### What is actually happening?

React does not recognize the `offsetX` prop on a DOM element.

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18.3.1 |
| System | mac |
| Browser | 最新版 |

---
自定义Select 下拉框内容, dropdownRender返回一个table组件的话, 会提示React does not recognize the offsetX prop on a DOM
<img width="864" alt="image" src="https://github.com/ant-design/ant-design/assets/63764959/6fa36aca-28f8-48da-be10-98ca1a166592">

**Comment by linxianxi** [comment]
fixed in https://github.com/ant-design/ant-design/pull/49080

**Comment by linxianxi** [comment]
现在删除 lock，重新安装也可解决

**Comment by afc163** [comment]
你给的例子里好像没有 antd，只有 react-data-grid。

**Comment by ybf970928** [comment]
> 你给的例子里好像没有 antd，只有 react-data-grid。

已经恢复了

**Comment by codedart2018** [comment]
已解决
