### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by Indyandie** [ant-design/ant-design#4914]
Hi guys,

Some of the pages are part chinese part english. It would be great to be able to switch between the two languages for consistency. 

Gracias!

**Comment by benjycui** [comment]
Could you list those pages here? Thanks.

**Comment by benjycui** [comment]
FYI, pattern(https://ant.design/docs/pattern/navigation) will be deprecated, so it's unnecessary to translate.

**Comment by NE-SmallTown** [comment]
Maybe you mean the issues?

**Comment by afc163** [comment]
The documentation aboult react components have English version now, and we are going to renew other documentation later (may with English version).
