### ISSUE TITLE
[Wrong statement]Why is component defaultValue not working when inside Form.Item?

### ISSUE THREAD

**Issue by hasakilol** [ant-design/ant-design#49148]
### Reproduction link

[https://github.com/hasakilol/umi-app/blob/master/src/components/FormPlay2/index.tsx](https://github.com/hasakilol/umi-app/blob/master/src/components/FormPlay2/index.tsx)

### Steps to reproduce

In your docs(https://ant.design/components/form), it says 

> Why is component defaultValue not working when inside Form.Item?
> Components inside Form.Item with name property will turn into controlled mode, which makes defaultValue not work anymore. Please try initialValues of Form to set default value.

```
<Form initialValues={initialValues}>
  <Form.Item name='input'>
    <Input defaultValue='hello' />
  </Form.Item>
</Form>
```

### What is expected?

Input should be displayed as empty.

### What is actually happening?

Input is displayed as 'hello'

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18.3.1 |
| System | Windows 10 |
| Browser | Chrome latest |

**Comment by afc163** [comment]
`initialValues={{ input: '' }}`

**Comment by hasakilol** [comment]
>Components inside Form.Item with name property will turn into controlled mode, which makes defaultValue not work anymore. Please try initialValues of Form to set default value.

defaultValue is 'hello', which should not take effect by the doc because the Form.Item has name property. However, the fact is 'hello' is shown in the input box. Why?

**Comment by hasakilol** [comment]
If the statement in docs is incorrect, please modify it.

**Comment by hasakilol** [comment]
@afc163
