### ISSUE TITLE
受控的Select组件，onChange中setValue为undefiend后，展示的label与实际的值不一致

### ISSUE THREAD

**Issue by JackWang032** [ant-design/ant-design#49157]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-qdxhr6?file=demo.tsx)

### Steps to reproduce

受控下拉框无初始值, 当我选择某个选项后，在onChange中会判断是否要数据变更，如果不进行数据变更，则保持value不变(不进行setValue或者setValue为undefiend)，这时展示的label还为所选的label而非空

### What is expected?

与value保持一致

### What is actually happening?

会将所选的label展示出来，但实际值还是空的， 尝试重新渲染后还是一样，如果setValue为null则不会出现该情况

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18 |
| System | mac |
| Browser | Chrome v116.0.5845.110 |

---
实际业务场景为：一个表格列表中，有很多下拉框，选完后如果列表已存在该值，则保持原来的值并进行提示，如果这个下拉框一开始就是空值，那么就会遇到上述情况

**Comment by JackWang032** [comment]
<img width="468" alt="image" src="https://github.com/ant-design/ant-design/assets/64318393/88dff550-f6af-4570-97c6-3fd1b9e1434d">

**Comment by QDyanbing** [comment]
value={value || null}这样应该能先解决；估计是value为undefined的时候被识别成了非受控模式，change的时候触发了内部改变逻辑
