### ISSUE TITLE
datepicker 能否支持修改表头星期样式

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#49167]
### What problem does this feature solve?

![image](https://github.com/ant-design/ant-design/assets/29728228/c7c40d1e-7aeb-4d53-9c65-ef4815b25eb4)

如果想修改星期样式，应该怎么做，有些业务需求要加粗，描红等，没有找到方法，cellRender里只能修改下面日期的

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by zystudios** [comment]
> What does the proposed API look like?

类似cellRender 这种方法，可以自定义整个下拉内容

**Comment by afc163** [comment]
请用代码具体描述你期望的 API 是什么样的。

**Comment by afc163** [comment]
问题解决了么？
