### ISSUE TITLE
父层级设置了scale后，Select下拉列表展开错误

### ISSUE THREAD

**Issue by Karl-Xu** [ant-design/ant-design#49163]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-kzz78c?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwukcx5e00063b6iiu07osil%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwukcx5e00023b6i7oclgezx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwukcx5e00033b6iqie0962m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwukcx5e00053b6i89gt2h89%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwukcx5e00023b6i7oclgezx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwukcx5e00013b6i1qw429ge%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A55%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwukcx5e00023b6i7oclgezx%2522%252C%2522activeTabId%2522%253A%2522clwukcx5e00013b6i1qw429ge%2522%257D%252C%2522clwukcx5e00053b6i89gt2h89%2522%253A%257B%2522id%2522%253A%2522clwukcx5e00053b6i89gt2h89%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwukcx5e00043b6if5epm9y9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwukcx5e00043b6if5epm9y9%2522%257D%252C%2522clwukcx5e00033b6iqie0962m%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwukcx5e00033b6iqie0962m%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1、点击下拉框

### What is expected?

下拉列表跟随下拉输入框

### What is actually happening?

下拉列表与下拉输入框错位

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18.x |
| System | macOS sonoma 14.5 |
| Browser | Chrome版本 124.0.6367.209（正式版本） (x86_64) |

**Comment by afc163** [comment]
Fixed in antd 5.x
