### ISSUE TITLE
table filter 如果太长没有滚动条，这个有解决方案么？

### ISSUE THREAD

**Issue by zyx4986** [ant-design/ant-design#4916]
table filter的内容如果太长，没有滚动条，有解决方案么？

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
What solution will you suggest?

**Comment by zyx4986** [comment]
英文不好，最后把filter的内容分了个类，用submenu解决了

**Comment by afc163** [comment]
我加个最大高度。
