### ISSUE TITLE
Dropdown 菜单支持展示 Checkbox

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#49161]
### What problem does this feature solve?

在某些数据录入形式的 Dropdown 中，尤其是多选，我们希望能够展示 Checkbox，让用户能够更清楚地知道列表是可以多选的

![image](https://github.com/ant-design/ant-design/assets/5836790/1f62f9c2-3a7c-43f8-9366-57ac1b63a9d3)

### What does the proposed API look like?

```jsx
<Dropdown menu={{ checkbox: true }}></Dropdown>
```

**Comment by afc163** [comment]
这是选择组件而非下拉菜单组件，建议用 Select。

**Comment by guoyunhe** [comment]
@afc163 我们这边的需求是多层多选，截图没有展示全面，是有子菜单的，所以不能用 Select,因为有多选，也不能用 Cascader。

**Comment by afc163** [comment]
Cascader 支持多选。https://ant.design/components/cascader-cn#cascader-demo-multiple

**Comment by guoyunhe** [comment]
@afc163 但是我们这边又要求是按钮展示，而 Cascader 是 Input 展示

![image](https://github.com/ant-design/ant-design/assets/5836790/71fbf3e5-721c-4d28-918b-421f23a82199)

那 Cascader 是否可以像 Dropdown 一样，提供自定义展示组件的方法，让我们用 Button 替代 Input 展示？

**Comment by afc163** [comment]
支持的：https://ant.design/components/cascader-cn#cascader-demo-custom-trigger
