### ISSUE TITLE
DatePicker crashes when input is custimized via components props

### ISSUE THREAD

**Issue by lukas-siarny** [ant-design/ant-design#49166]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-aojy8c?file=demo.tsx,index.css)

### Steps to reproduce

1/ import { DatePicker } from 'antd'

2/ use DatePicker and customize input via `components` props
```
const defaultValue = dayjs('2024-01-01');

const onChange: DatePickerProps['onChange'] = (_, dateStr) => {
    console.log('onChange:', dateStr);
};

<DatePicker
        defaultValue={defaultValue}
        locale={buddhistLocale}
        onChange={onChange}
        components={{ input: () => <div>input</div> }}
/>
``` 

3/ click on the DatePicker inputs and App will crashes with an error:
```
Error in /turbo_modules/rc-picker@4.5.0/lib/PickerInput/Selector/Input.js (103:26)
Cannot read properties of undefined (reading 'focus')
```

4/ according to the types, you should be able to pass to the input `string` value as well, but when `string` value witch contains at least one space is passed (for example `Input name`), it crashes immediately when app runs with an error:
```
Error in /turbo_modules/react-dom@18.3.1/cjs/react-dom.development.js (9784:34)
Failed to execute 'createElement' on 'Document': The tag name provided ('Some value') is not a valid name.
```

### What is expected?

Unhandled error is thrown when customizing input

### What is actually happening?

No error is thrown when customizing input

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18.3.1 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
You should make your input support `ref`

**Comment by lukas-siarny** [comment]
Could you please provide an code example?

**Comment by lukas-siarny** [comment]
Ok, I managed to get it work using React.forwardRef CB 
```
components={{
  input: React.forwardRef<HTMLDivElement, {}>((_props, ref) => {
	  return (
	    <div ref={ref}>Custom input name</div>
	  )
      })
  }}
```
