### ISSUE TITLE
当Badge的status为processing且使用tailwindcss时，闪烁效果异常

### ISSUE THREAD

**Issue by mozhu811** [ant-design/ant-design#49173]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/mozhu811/antd-demo/main)

### Steps to reproduce

同时引入tailwindcss和antd的badge组件

### What is expected?

Badge的status属性为processing时，正常闪烁

### What is actually happening?

闪烁扩散效果异常

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React |  ^18 |
| System | MacOS/Windows |
| Browser | Chrome 124.0.6367.158 |

**Comment by MadCcc** [comment]
https://ant-design.antgroup.com/docs/react/compatible-style-cn#tailwindcss-%E6%8E%92%E5%B8%83-layer
试试

**Comment by mozhu811** [comment]
https://codesandbox.io/p/github/mozhu811/antd-demo/main?file=%2Fapp%2Fglobals.css

demo中已经添加了
