### ISSUE TITLE
在table里面用Pagination，发现数据更新后，Pagination不会被初始化

### ISSUE THREAD

**Issue by FANUP** [ant-design/ant-design#4919]
在table里面用Pagination，发现数据更新后，Pagination不会被初始化。
比如，我选到第5页，然后更新数据，更新完后发现，Pagination还是停留在第5页。
这个问题该怎么解决？可以手动初始化Pagination？

**Comment by afc163** [comment]
I suggest that you should propose issue following issue template and provide a reproducible codepen.

**Comment by FANUP** [comment]
不好意思呀，下次会注意科学提问的！
仔细翻阅了api文档，找到解决方法了。

**Comment by benjycui** [comment]
@FANUP please close your issue when it's solved.

It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by EdisonSu768** [comment]
@FANUP how did you resolve it?
