### ISSUE TITLE
DatePicker picker=week情况下修改表头处内容

### ISSUE THREAD

**Issue by MuShengJiu** [ant-design/ant-design#49191]
### What problem does this feature solve?

于日期表头处，不同的产品可能存在不同的要求，希望可以按需更改日期表头

### What does the proposed API look like?

<DatePicker
  open
  picker="week"
  header={myHeader}
/>

const myHeader = () => {
  return ['自定义0', '自定义1', '自定义2, '自定义3', '自定义4', '自定义5', '自定义6', '自定义7']
}

**Comment by zombieJ** [comment]
https://stackblitz.com/edit/react-6qyn7n?file=demo.tsx

**Comment by MuShengJiu** [comment]
不仅是日期的内容，我也希望可以对周数上方的空白进行修改
