### ISSUE TITLE
官方例子的可编辑表格，修改整个datasource无效

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#49196]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ke-bian-ji-dan-yuan-ge-antd-4-24-16-forked-whpls8?file=%2Fdemo.js%3A197%2C21-197%2C31)

### Steps to reproduce

在 handleSave方法里面修改了address为 测试。但是其他的行没有变，就只有编辑的这一行修改了。

### What is expected?

应该在handleSave的时候setDataSource 其他的列也应该变化。

### What is actually happening?

在handleSave里面修改dataSource，其他行不会变化。

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 16.14.60 |
| System | windows |
| Browser | chrome 125.0.6422.113 |

**Comment by zombieJ** [comment]
你的 codesandbox 没有设置成 public：

<img width="738" alt="截屏2024-06-03 19 42 48" src="https://github.com/ant-design/ant-design/assets/5378891/03f8e591-b072-425e-b9be-3d5afd67e948">

**Comment by xgj1988** [comment]
@zombieJ  已经设置了。你在看看呢

**Comment by zombieJ** [comment]
看一下 immutable 概念，返回对象需要是新的 object。你直接改对象，会因为对象 ref 没有改变而被 memo 掉：

```diff
--  newData.forEach((item) => {
--    item.address = "测试";
++  const filledData = newData.map((item) => {
++    return {
++      ...item,
++      address: "测试",
++    };
    });

--    setDataSource(newData);
++    setDataSource(filledData);
```

**Comment by xgj1988** [comment]
@zombieJ  谢谢
