### ISSUE TITLE
DatePicker组件通过showTime.disabledTime().disabledHours属性不能禁用小时选择

### ISSUE THREAD

**Issue by mrdulin** [ant-design/ant-design#49195]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-tzuysx?file=demo.tsx)

### Steps to reproduce

打开日期控件，查看小时是否被禁用

### What is expected?

小时选择被禁用，或者可能TS types没有更新。

### What is actually happening?

使用`disabledTime().disabledHours`属性可以禁用小时选择
```jsx
<DatePicker
   disabledTime={() => ({
     disabledHours: () => [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 19, 20, 21, 22, 23],
   })} 
/>
```

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18.3.1 |
| System | windows 10 |
| Browser | edge 125.0.2535.67 |

**Comment by afc163** [comment]
```diff
  <DatePicker
    showTime={{
      showHour: true,
      showMinute: false,
      showSecond: false,
-     disabledTime={() => ({
-       disabledHours: () => [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 19, 20, 21, 22, 23],
-     })} 
+     disabledHours: () => [0, 1, 2, 3, 4, 5, 6, 7, 8, 18, 19, 20, 21, 22, 23],
    }}
    onChange={onChange}
  />
```

**Comment by zombieJ** [comment]
v4 已经不再维护了，升级到 v5 就是好的了哈：

https://stackblitz.com/edit/react-tzuysx-wpyxot?file=demo.tsx,package.json

**Comment by afc163** [comment]
4.x 确实有点问题。

**Comment by mrdulin** [comment]
> 4.x 确实有点问题。

如果用上述代码，该属性已标记为deprecated，可能类型有点问题
```ts
 /** @deprecated Please use `disabledTime` instead. */
disabledHours?: DisabledTimes['disabledHours'];
```
