### ISSUE TITLE
virtual 下的 components.body样式还是有问题 

### ISSUE THREAD

**Issue by little-time** [ant-design/ant-design#49194]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-qpczmj-mfhy5u?file=demo.tsx&issueNumber=48515&issueRepo=ant-design/ant-design)

### Steps to reproduce

https://stackblitz.com/edit/react-qpczmj-mfhy5u?file=demo.tsx&issueNumber=48515&issueRepo=ant-design/ant-design

### What is expected?

正常显示

### What is actually happening?

样式显示有问题，有遮盖

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 17 |
| System | mac |
| Browser | 谷歌 |

---
之前说解决ref问题就可以。但是解决之后并没有正常显示

**Comment by zombieJ** [comment]
不是你写了 `forwardRef` 就行的，你得把 `ref` 传下去……

```diff
    const EditableRow: React.FC<EditableRowProps> = React.forwardRef(
      ({ index, ...props }, ref) => {
        const [form] = Form.useForm();
        return (
          <Form form={form} component={false} key={index}>
            <EditableContext.Provider value={form}>
--            <tr {...props} key={index} />
++            <tr {...props} key={index} ref={ref} />
            </EditableContext.Provider>
          </Form>
        );
      }
    );
```

另外，我 fix 了一下 React warning：

https://stackblitz.com/edit/react-qpczmj-2wcura?file=demo.tsx&issueNumber=48515&issueRepo=ant-design/ant-design
