### ISSUE TITLE
Tabs component `editable-card` option showing add more button and changing layout redundantly when using with dnd-kit

### ISSUE THREAD

**Issue by abgunaydin** [ant-design/ant-design#49200]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-c6m4sc)

### Steps to reproduce

Drag the first indexed tab to the left more.

### What is expected?

The first indexed tab should stay in its place or move to the last index...

### What is actually happening?

You will see that show more button is seen additionally to add more button and the parent container width is expanded and these buttons are pushed in the end. If you click on the show more button you will see the other tabs that you moved will be shown...

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18 |
| System | macOS |
| Browser | Chrome |

<img width="747" alt="image" src="https://github.com/ant-design/ant-design/assets/146081815/d8f02fe3-bbb0-44a9-90fe-04a3c88e605b">

**Comment by gergicsmilan** [comment]
hey, any update on this? I encountered the same problem.
