### ISSUE TITLE
Popover组件渲染需要5ms 当页面同时存在几百个popover时卡顿明显 4版本popover渲染只需0.1ms

### ISSUE THREAD

**Issue by sumail43db** [ant-design/ant-design#49207]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.js)

### Steps to reproduce

1.创建版本5的popover demo，通过Profiler查询，渲染popover需要5ms
2.创建版本4的popover demo, 通过Profiler查询，渲染popover只需要0.1ms

### What is expected?

希望popover渲染速度在1ms以内，或者hover上去才计算位置。

### What is actually happening?

popover渲染需要5ms

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18.3.1 |
| System | macOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
你的重现是空的。v5 重构了 Trigger 逻辑，使得开发者不需要再向过去一样通过 `getPopupContainer` 来确保跟随。但是代价就是会有更多的事件监听，5ms 听起来并不是很大的损耗。得看看你的重现才知道是什么场景。
