### ISSUE TITLE
Input.OTP在edge浏览器中单次输入会出现两个字符的问题

### ISSUE THREAD

**Issue by CherryNo1** [ant-design/ant-design#49203]
### Reproduction link

[https://ant-design.antgroup.com/components/input-cn](https://ant-design.antgroup.com/components/input-cn)

### Steps to reproduce

直接使用官网的例子,聚焦到Input.OTP,按一下任一字符,就会输入进入2个字符.比如按1,则会填如两个1

### What is expected?

按什么键,输入什么值

### What is actually happening?

直接使用官网的例子,聚焦到Input.OTP,按一下任一字符,就会输入进入2个字符.比如按1,则会填如两个1

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18.2 |
| System | windows |
| Browser | 版本 102.0.1245.30 (正式版本) (64 位) |

**Comment by wanpan11** [comment]
edge 125.0.2535.85 (正式版本) (64 位)
无法复现
