### ISSUE TITLE
Progress: React does not recognize the `percentPosition` prop on a DOM element

### ISSUE THREAD

**Issue by gitTerebi** [ant-design/ant-design#49204]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-gwr5sl)

### Steps to reproduce

Using electron-vite

Using percentPosition trips React error

----
@react-refresh? [sm]:267 Warning: React does not recognize the `percentPosition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `percentposition` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

![image](https://github.com/ant-design/ant-design/assets/12906211/6e7ec911-4ae1-4a00-9cc0-3bec96f2dd05)

![image](https://github.com/ant-design/ant-design/assets/12906211/79997d1b-4c98-4ec8-984c-6eff225cb2cb)

### What is expected?

It works

### What is actually happening?

Doesn't work

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | "react": "^18.2.0" |
| System | Windows 10 |
| Browser | Chrome |

---
This can't be replicated on codesandbox, it might be vite build related.

**Comment by yoyo837** [comment]
Can not to reproduce https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-xpdx2n
