### ISSUE TITLE
自定义全局默认Spin后，Spin不显示

### ISSUE THREAD

**Issue by pangxzi** [ant-design/ant-design#49205]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-a7en6y-q7b4xc?file=demo.tsx)

### Steps to reproduce

```
import { LoadingOutlined } from '@ant-design/icons';

const antIcon = <LoadingOutlined spin />;
Spin.setDefaultIndicator(antIcon);
```

### What is expected?

spin可以正常显示

### What is actually happening?

spin不能正常显示

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18 |
| System | windows 11 |
| Browser | edge 125.0.2535.79  |

**Comment by wanpan11** [comment]
需要添加 font-size

```const antIcon = <LoadingOutlined style={{ fontSize: 24 }} spin />;```

![image](https://github.com/ant-design/ant-design/assets/38714194/393180ed-62c4-4bfd-89c1-3894bc9ba486)

**Comment by wanpan11** [comment]
需要默认值

**Comment by pangxzi** [comment]
> 需要添加 font-size
> 
> `const antIcon = <LoadingOutlined style={{ fontSize: 24 }} spin />;`
> 
> ![image](https://private-user-images.githubusercontent.com/38714194/336284115-393180ed-62c4-4bfd-89c1-3894bc9ba486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0Njg4MDUsIm5iZiI6MTcxNzQ2ODUwNSwicGF0aCI6Ii8zODcxNDE5NC8zMzYyODQxMTUtMzkzMTgwZWQtNjJjNC00YmZkLTg5YzEtMzg5NGJjOWJhNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAyMzUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MjczNGU4OThlMGFlZTJlZDM0ODBmMGU3Yzg3NjMyM2UzMjNiODA0NjdjYzg5NTdlMmE4MzJhMGM5NDQwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.suj1g4bkBFENKV3SuIcbN9ZNlBTUhoUYKhEHBvu-_70)

5.18之前不用设置fontSize也会显示，设置了fontSize，Spin的size就不起作用了

**Comment by wanpan11** [comment]
我看看改了撒
