### ISSUE TITLE
RangePicker会默认添加min-width样式

### ISSUE THREAD

**Issue by xiaosansiji** [ant-design/ant-design#4920]
发生问题的环境是：

antd 版本: 2.6.4
操作系统及其版本: Windows 7
浏览器及其版本: Chrome 53.0.2785.89
您做了什么？请提供尽可能详细的重现步骤。

引入RangePicker，通过设置样式改变组件宽度：
![image](https://cloud.githubusercontent.com/assets/7600149/23051324/301d5dd8-f503-11e6-96d5-316ca6947ed3.png)

您期待的结果是:

可以通过设置样式改变RangePicker组件宽度

实际上的结果是:
![image](https://cloud.githubusercontent.com/assets/7600149/23051361/6581c14e-f503-11e6-8fdb-69094d8e76fd.png)

在浏览器中，会自动增加一个行内样式：`min-width: 300px;`
不是很清楚这里是什么情况

**Comment by afc163** [comment]
Added in https://github.com/ant-design/ant-design/commit/b912f1cea6f470c16b8dd90554883460161cef47#diff-34c1c9d6622f2b32f87f4de9a64f099bR139
