### ISSUE TITLE
深色模式下，Drawer 内的文字也是深色

### ISSUE THREAD

**Issue by sunven** [ant-design/ant-design#49209]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-7m4qyj?file=%2Findex.js%3A17%2C1)

### Steps to reproduce

codesandbox

### What is expected?

文字为浅色

### What is actually happening?

文字为深色

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.2 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
codesandbox 没设置成 public 的：

![Uploading 截屏2024-06-04 10.32.09.png…]()

**Comment by sunven** [comment]
@zombieJ 改成 public 了

**Comment by kaoding** [comment]
这个问题我也发现了，在深色模式下，补设置一下文本颜色，
![image](https://github.com/ant-design/ant-design/assets/18542211/800ee985-407c-4b40-bcc4-af4201836734)

**Comment by sunven** [comment]
antd 会处理吗，还是我们用自己处理

**Comment by kaoding** [comment]
> antd 会处理吗，还是我们用自己处理
要你们处理一下
https://github.com/ant-design/ant-design/issues/49209#issuecomment-2146462871

**Comment by sunven** [comment]
> > antd 会处理吗，还是我们用自己处理
> > 要你们处理一下
> > https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-4q5vjj?file=%2Findex.js%3A7%2C11

私有的打不开

**Comment by kaoding** [comment]
> > > antd 会处理吗，还是我们用自己处理
> > > 要你们处理一下
> > > https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-4q5vjj?file=%2Findex.js%3A7%2C11
> 
> 私有的打不开

已公

**Comment by sunven** [comment]
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-s6vjw4?file=%2Findex.js%3A29%2C5

**Comment by sunven** [comment]
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-s6vjw4?file=%2Findex.js%3A29%2C5
@kaoding 麻烦问下，Tabs 深色下不生效，如何处理

**Comment by kaoding** [comment]
Tabs 我这里没有问题，但你上面的演示的确是不行，这就很让人搞不懂了。
