### ISSUE TITLE
could `form.validateFields` has a value

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#4921]

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by benjycui** [comment]
What's your use case?

For `form.validateFields` is asynchronously, it is common to use callback.

**Comment by CallMeXYZ** [comment]
e.g. A form with two input(A and B). B is not required and if B has an value it should be validated. So in my form submit function i have to do sth like this:
```javascript 
  handleSubmit= (e) => {
        e.preventDefault();
        const {form}=this.props, cell = form.getFieldValue('bName');
        if (bName&&bName.trim().length>0) {
            form.validateFields((error, values) => {
               //error operations
                if (!error) this.startSubmit();
            });
        }
        else {
            this.startSubmit();
        }
    }
```
if `form.validateFields` return a boolean value of validated then the code would be
```javascript
handleSubmit= (e) => {
    e.preventDefault();
    const {form}=this.props, cell = form.getFieldValue('bName');
    let validated=true;
    if (bName&&bName.trim().length>0) {
        validated= form.validateFields((error, values) => {
            //error operations
        });
    }
    if(validated)    this.startSubmit();
}      
```
since `form.validateFields` is asynchronously,it seems not a good idea.

**Comment by benjycui** [comment]
just use rules to validate `required` or not.

**Comment by benjycui** [comment]
> B is not required and if B has an value it should be validated.

Just use customized validation, see: https://ant.design/components/form/#components-form-demo-register

And it's impossible to make `form.validateFields` synchronously, for validation could be asynchronously and it's a feature.

**Comment by CallMeXYZ** [comment]
..it's not a good idea of mine,not judging antd~
