### ISSUE TITLE
QRCode don't support onClick

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#49214]
```jsx
<QRCode onClick={() => console.log('click')} />
```

**Comment by afc163** [comment]
icon 属性也不支持非正方形的展示样式。

<img width="253" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/e08bd7e1-af65-4699-8b47-045932163259">

**Comment by thinkasany** [comment]
QRCode本身是支持的， 但是这边iconSize写死了，所以变成正方形了，可以考虑 iconSize 是一个对象或者number不 
```
iconSize: {
width: 200.
height: 300
}
```
![image](https://github.com/ant-design/ant-design/assets/117748716/e8673087-6abf-4095-936f-efeaabe128b9)


![image](https://github.com/ant-design/ant-design/assets/117748716/26c7a5a2-bde5-4a0c-80c2-5d4187e35e72)

**Comment by afc163** [comment]
对，是准备这么做的。

**Comment by thinkasany** [comment]
让我试试修复这个bug吧~

**Comment by afc163** [comment]
当做 feature 来做吧

**Comment by thinkasany** [comment]
好的

**Comment by kecanwen** [comment]
> ```js
> <QRCode onClick={() => console.log('click')} />
> ```

能否设计一个透明蒙层 ,捕获用户的点击事件
![image](https://github.com/ant-design/ant-design/assets/68574761/0e258016-b140-4792-a216-1627d42965d9)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/49240
