### ISSUE TITLE
Typography.Text 有宽度限制时，在Safari的兼容问题

### ISSUE THREAD

**Issue by Likang0122** [ant-design/ant-design#49215]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-6t52mh?file=demo.tsx)

### Steps to reproduce

在Safari打开

### What is expected?

有省略号出现

### What is actually happening?

不受宽度限制

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18 |
| System | macos |
| Browser | Safari 17.3 |

**Comment by Likang0122** [comment]
不带 copyable 就没问题，能正常溢出省略

**Comment by zombieJ** [comment]
看起来是 Safari BUG，有了 svg 就算不出来了
