### ISSUE TITLE
DatePicker的RangePicker，showTime配置，选择日期时间后，没有回显到页面上

### ISSUE THREAD

**Issue by Liu-0114** [ant-design/ant-design#49229]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn](https://ant-design.antgroup.com/components/date-picker-cn)

### Steps to reproduce

1、就选择RangePicker，showTime的时间和日期，
2、点击确定后

### What is expected?

时间回显到input框中

### What is actually happening?

时间没有回显到input框中

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | 18.2 |
| System | mac |
| Browser | chrome121 |

<img width="1792" alt="image" src="https://github.com/ant-design/ant-design/assets/59878300/d38485eb-26f6-4a3f-979c-f199a2f2a996">

**Comment by Liu-0114** [comment]
https://codesandbox.io/p/sandbox/fast-flower-jyh2k9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx2xs8re00063b6iindoxxcy%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx2xs8re00023b6i6ugw803n%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx2xs8re00033b6ijnnu80dg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx2xs8re00053b6i3mxuzler%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx2xs8re00023b6i6ugw803n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx2xs8rd00013b6imuams4dj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx2xs8re00023b6i6ugw803n%2522%252C%2522activeTabId%2522%253A%2522clx2xs8rd00013b6imuams4dj%2522%257D%252C%2522clx2xs8re00053b6i3mxuzler%2522%253A%257B%2522id%2522%253A%2522clx2xs8re00053b6i3mxuzler%2522%252C%2522activeTabId%2522%253A%2522clx2ycm7w00703b6g453zlcqx%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clx2ycm7w00703b6g453zlcqx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clx2xs8re00033b6ijnnu80dg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx2xs8re00033b6ijnnu80dg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by Liu-0114** [comment]
就是这个时间范围选择之后必须点击一下确认，再选下一个，在点击确认才能回显，如果选择了开始时间，鼠标直接定位到结束时间，选择之后再一起点击确认的话，时间就不能回显上去，能否处理一下，谢谢！
<img width="1792" alt="image" src="https://github.com/ant-design/ant-design/assets/59878300/39e0eab3-fdff-4bd0-ac2a-6e53e477a2d7">

**Comment by DK-2013** [comment]
it is possible reproduce [here](https://ant.design/components/date-picker#components-date-picker-demo-range-picker)
version 5.18.0
```
<RangePicker showTime />
```
case:

- click on input start period
- select date in calendar (don't confirm by "OK" button!)
- click on input end period
- select date in calendar
- confirm by "OK" button

expected:
input show selected period
happening:
got empty input
