### ISSUE TITLE
日期选择week模式自定义format解析值异常

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#49222]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-mdwzab-nktqn5?file=demo.tsx)

![image](https://github.com/ant-design/ant-design/assets/49147660/9d8548cf-6b8c-4784-9f40-74fd0b256d83)

### Steps to reproduce

见重现链接，日期选择选中值与设定值对应的日期字符串不符

### What is expected?

正确解析所赋值日期

### What is actually happening?

未能正确解析所赋值日期

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | ^18.0.0 |
| System | win11 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
dayjs 不支持周解析，可以自行实现相关逻辑或者直接去给 dayjs 提一下 issue 哈~
