### ISSUE TITLE
Tooltip 定位偏移

### ISSUE THREAD

**Issue by changfu2015** [ant-design/ant-design#49220]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-3frkqx?file=%2Findex.js)

### Steps to reproduce

在body标签中 中加入transform: scale(0.8)

### What is expected?

Tooltip 消息显示正常

### What is actually happening?

在Tooltip 组件父级使用transform 缩放会影响提示框定位

| Environment | Info |
| --- | --- |
| antd | 4.24.8 |
| React | 17.0.0 |
| System | mac |
| Browser | 谷歌  |

---
不升级5.3 以上如何修复

**Comment by zombieJ** [comment]
v5 里换了一种新的实现方式来算偏移。v4 已经过了维护期了哈，这个问题 v4 里无解。

**Comment by changfu2015** [comment]
项目做大版本升级代价太大啊
