### ISSUE TITLE
Pagination设置了simple，添加了showSizeChanger，pageSize 切换器也不显示。

### ISSUE THREAD

**Issue by zhaobingwang** [ant-design/ant-design#49236]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/jian-ji-antd-4-24-12-forked-c3wlzr?file=%2Fdemo.tsx)

### Steps to reproduce

直接是官网fork的Pagination部分“简洁”例子

### What is expected?

添加了showSizeChanger属性 可以显示pageSize 切换器

### What is actually happening?

添加了showSizeChanger属性 无法显示pageSize 切换器

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18 |
| System | windows11 |
| Browser | edge 125.0.2535.79  |

---
直接按照官网例子编写的示例代码：https://4x-ant-design.antgroup.com/components/pagination-cn/#components-pagination-demo-simple，为这部分代码添加showSizeChanger，但是无法显示pageSize 切换器

**Comment by wanpan11** [comment]
建议升级到 V5 [v4 维护周期截止](https://ant.design/docs/blog/v4-ood-cn)
V5 能够满足你的需求
