### ISSUE TITLE
关于tree控件问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#4923]
这个树控件是属于antd的吗？
![image](https://cloud.githubusercontent.com/assets/19485727/23055639/de3b0f0a-f521-11e6-9da0-8321dd600108.png)

我从官网下面AntD Library 点击下载了这个包但是我在官网的API没有看到类似这样的树控件
![image](https://cloud.githubusercontent.com/assets/19485727/23055304/10a87c22-f520-11e6-9560-13033bd91215.png)

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/3854
