### ISSUE TITLE
Image组件预览的时候弹框中的图片被添加上了宽高

### ISSUE THREAD

**Issue by JokerAn** [ant-design/ant-design#49235]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-hdmwz8?file=%2Findex.js%3A3%2C30)

### Steps to reproduce

<div className="App">
        <h1>可以将antd切换到5.17.4版本在点开图片预览看效果 </h1>
        <h2>5.17.4 点开图片看预览图 图片比较大 </h2>
        <h2>
          5.18.0 点开图片看预览图
          预览图默认情况下跟缩略图一样大。需要手动点击加号放大，因为他将缩略图的宽高给设置成弹框中的宽高了！在之前版本是没有的{" "}
        </h2>

        <Image
          width={64}
          height={58}
          src="https://img12.360buyimg.com/ee/jfs/t20270528/245972/39/9009/68675/6655a631Fa702838a/8ca223b38e1acd42.png"
        />
      </div>

### What is expected?

预览大图不被限制大小

### What is actually happening?

预览大图被限制大小

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2 |
| System | mac |
| Browser | chrome版本 125.0.6422.113（正式版本） (arm64) |

**Comment by JokerAn** [comment]
![image](https://github.com/ant-design/ant-design/assets/23717175/f3b5bae2-600c-4b12-8992-e3afc6090cd6)
![image](https://github.com/ant-design/ant-design/assets/23717175/bfe75d92-2402-4b11-b820-3d73dabe0459)5.18.0
版本更新后

**Comment by wanpan11** [comment]
我来修复

**Comment by snowye7** [comment]
刚好遇到了0.0

**Comment by andyyxw** [comment]
+1，很急

**Comment by yoyo837** [comment]
可以先降级回去

**Comment by nova1751** [comment]
抱歉造成了困扰，`rc-image`那个库还有问题吗，没问题和下PR然后antd再改下依赖发个版本
