### ISSUE TITLE
Mentions禁用状态无效

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#49233]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-xfw6da-g7f7rf?file=demo.tsx)

### Steps to reproduce

设置了disabled后，依然可以进行内容的输入和编辑
![image](https://github.com/ant-design/ant-design/assets/49147660/93e2255d-2915-4bb0-b86d-0f9dea0d7f5c)

### What is expected?

呈现正确的禁用状态

### What is actually happening?

禁用状态无效

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | ^18.0.0 |
| System | win11 |
| Browser | Chrome |

**Comment by coderz-w** [comment]
我去看看

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/mentions/releases/tag/v2.13.2
