### ISSUE TITLE
ValidateFields can not perceive dynamic modification rules

### ISSUE THREAD

**Issue by starInEcust** [ant-design/ant-design#4924]
#### Environment(required)

- antd version: 2.7.1
- OS and its version: osx 10.12.3
- Browser and its version:  56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

The code is as follows:
```
{getFieldDecorator('receiverEmail', {
    rules: [
           { required: getFieldValue('billingFlag') !== '0', message: '必填项' },
    ],
 })(
      <Input />
)}
```
```
handleSubmit(e) {
      e.preventDefault();
      this.props.form.validateFields((err, values) => {
             console.log(err);
     }
}
```

#### What do you expected?

when getFieldValue('billingFlag') !== '0' changes from false to true，the validateFields  should know receicerEmail empty

#### What happen?

when getFieldValue('billingFlag') !== '0' changes from false to true, the validateFields did not find receiverEmail empty

**Comment by iiitmahesh** [comment]
Same issue for me also ..!

**Comment by starInEcust** [comment]
啊！ 顶上去啊

**Comment by benjycui** [comment]
Try https://github.com/ant-design/ant-design/issues/5740#issuecomment-294115031 ,
 if it doesn't work, please provide a re-producible online demo.

**Comment by benjycui** [comment]
More: https://github.com/ant-design/ant-design/pull/6035
