### ISSUE TITLE
这么低级的文档错误，怎么能出现在antd这么牛逼的项目中！！！！ 不能忍

### ISSUE THREAD

**Issue by Lliuxs** [ant-design/ant-design#49241]
### Reproduction link

[https://ant-design.antgroup.com/components/calendar-cn#api](https://ant-design.antgroup.com/components/calendar-cn#api)

### Steps to reproduce

https://ant-design.antgroup.com/components/calendar-cn#api

### What is expected?

文档是正确的

### What is actually happening?

文档重复内容 是不是处理git冲突选了全部接受

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18 |
| System | mac |
| Browser | google |

**Comment by Lliuxs** [comment]
![Uploading 企业微信20240605-111722@2x.png…]()

**Comment by Lliuxs** [comment]
<img width="1315" alt="企业微信20240605-111722@2x" src="https://github.com/ant-design/ant-design/assets/162529005/346e4885-c7c4-4793-b0c2-7e978001d640">

**Comment by li-jia-nan** [comment]
来个 PR

**Comment by afc163** [comment]
贡献机会来了

**Comment by afc163** [comment]
blame 一下把始作俑者抓出来批评一下

**Comment by crazyair** [comment]
我有罪
![image](https://github.com/ant-design/ant-design/assets/7971419/7c07276a-e563-412b-8c97-0e5e879fe138)

**Comment by kiner-tang** [comment]
> blame 一下把始作俑者抓出来批评一下

https://github.com/ant-design/ant-design/commit/bf9eff66d7b110400bcad629fbf4180ffbf73bcd#diff-58e290dfe67aeb90a9d97d4e3e8a790c9aa964113593229b7f2637b66f0c8a50

看起来像是合并冲突代码导致的

**Comment by wanpan11** [comment]
哈哈哈哈 大型社死现场

**Comment by crazyair** [comment]
> > blame 一下把始作俑者抓出来批评一下
> 
> [bf9eff6#diff-58e290dfe67aeb90a9d97d4e3e8a790c9aa964113593229b7f2637b66f0c8a50](https://github.com/ant-design/ant-design/commit/bf9eff66d7b110400bcad629fbf4180ffbf73bcd#diff-58e290dfe67aeb90a9d97d4e3e8a790c9aa964113593229b7f2637b66f0c8a50)
> 
> 看起来像是合并冲突代码导致的

不应该啊，git 的自动合并，怎么会有错误？这个 mr 不能解决冲突

**Comment by yoyo837** [comment]
应该是这个吧？https://github.com/ant-design/ant-design/pull/41584 @kiner-tang

**Comment by kiner-tang** [comment]
> 应该是这个吧？#41584 @kiner-tang

好像是，小丑竟是我自己。 @Lliuxs 有兴趣来个 PR 不？

**Comment by yoyo837** [comment]
> 我有罪 ![image](https://private-user-images.githubusercontent.com/7971419/336674253-7c07276a-e563-412b-8c97-0e5e879fe138.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTg2MDQsIm5iZiI6MTcxNzU1ODMwNCwicGF0aCI6Ii83OTcxNDE5LzMzNjY3NDI1My03YzA3Mjc2YS1lNTYzLTQxMmItOGM5Ny0wZTVlODc5ZmUxMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMDMzMTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE4ZDg3OTE0NTRkYzJmNTE5MDM4ODVhZDg3ZGVjYTM3MjY2ZTg4NDQxZmRjMjcxNTllZjFhYTVjOTY4N2ZkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CpRhLet1BVwgUIcTXb5NiSc-ZM5n6ubInLQYazOPwx8)

你这个也有？

**Comment by crazyair** [comment]
> > 我有罪 ![image](https://private-user-images.githubusercontent.com/7971419/336674253-7c07276a-e563-412b-8c97-0e5e879fe138.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTg2MDQsIm5iZiI6MTcxNzU1ODMwNCwicGF0aCI6Ii83OTcxNDE5LzMzNjY3NDI1My03YzA3Mjc2YS1lNTYzLTQxMmItOGM5Ny0wZTVlODc5ZmUxMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMDMzMTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE4ZDg3OTE0NTRkYzJmNTE5MDM4ODVhZDg3ZGVjYTM3MjY2ZTg4NDQxZmRjMjcxNTllZjFhYTVjOTY4N2ZkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CpRhLet1BVwgUIcTXb5NiSc-ZM5n6ubInLQYazOPwx8)
> 
> 你这个也有？

是一开始就写错位置了。。。

**Comment by zombieJ** [comment]
感觉可以加个 lint，merge 没去重靠肉眼不靠谱

**Comment by crazyair** [comment]
> 感觉可以加个 lint，merge 没去重靠肉眼不靠谱

我 merge 都是用当前分支的代码，然后看合进来的代码，手动加进来，用 git 冲突提示，解决冲突，比较困难。

**Comment by huangkairan** [comment]
围观
