### ISSUE TITLE
Select filterSort 函数需要能够获取 inputValue 来计算排序

### ISSUE THREAD

**Issue by hungtcs** [ant-design/ant-design#49248]
### What problem does this feature solve?

filterSort 可以对搜索结果进行排序，但是有时候排序需要根据 搜索字符串（inputValue）来决定。

### What does the proposed API look like?

在 filterSort 函数中添加第3个参数，值是搜索字符串。
```ts
(optionA: Option, optionB: Option, info: { inputValue: string }) => number
```

**Comment by MadCcc** [comment]
第三个参数放对象吧，可能以后也有其他参数，比如 `info: { inputValue: string }`

**Comment by hungtcs** [comment]
> 第三个参数放对象吧，可能以后也有其他参数，比如 `info: { inputValue: string }`

有道理，PR在这里 <https://github.com/react-component/select/pull/1051>

**Comment by berber1016** [comment]
看了一下 PR， 我建议将字段名由 `inputValue` 改为 `searchValue`， 与 props 参数一致，毕竟这俩个值是有关联的， `inputValue` 在rc-select 中已经废弃掉了，换成了` searchValue`

**Comment by yoyo837** [comment]
> 看了一下 PR， 我建议将字段名由 `inputValue` 改为 `searchValue`， 与 props 参数一致，毕竟这俩个值是有关联的， `inputValue` 在rc-select 中已经废弃掉了，换成了` searchValue`

个人支持

**Comment by berber1016** [comment]
> 看了一下 PR， 我建议将字段名由 `inputValue` 改为 `searchValue`， 与 props 参数一致，毕竟这俩个值是有关联的， `inputValue` 在rc-select 中已经废弃掉了，换成了` searchValue`

话说我也写了一个 PR，QAQ，提交这么多我就不提交了

**Comment by hungtcs** [comment]
PR 已更新 😆

**Comment by yoyo837** [comment]
> 话说我也写了一个 PR，QAQ，提交这么多我就不提交了

下次可以提前表明贡献意愿，挂个标签避免其他人重复劳动
