### ISSUE TITLE
Pagination select arrow missing when hover

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#49258]
<img width="634" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/d03aa47d-933f-4c20-b1bf-8b505367d099">

**Comment by consistent-k** [comment]
不懂就问 在Select里这段hover的时候把下拉箭头隐藏掉的原因是什么呢 
![image](https://github.com/user-attachments/assets/9a446993-0b91-4463-8f5f-5a0c9c4478b8)

目前我项目上有这个问题，hover Select之后 这段代码确实应用上了 但是antd自己的文档上确没有这个。
![image](https://github.com/user-attachments/assets/5a7f3569-bc5c-4e26-96ef-f82675328915)

这个issue里分页器的箭头没了 也是因为这个 我看分页器是又覆盖了一层

**Comment by afc163** [comment]
@consistent-k 给个问题重现吧。

**Comment by consistent-k** [comment]
> @consistent-k 给个问题重现吧。

我找到是哪个props影响的了 如下图  就不用写仓库了吧 直接在stackblitz试的
  getPopupContainer={(triggerNode) =>
        triggerNode?.parentElement || document.body
      }
![image](https://github.com/user-attachments/assets/203fc9f0-98e2-43b1-a6df-9e3e179620ed)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50382
