### ISSUE TITLE
Upload beforeUpload 在拖拽上传directory时预期行为不一致

### ISSUE THREAD

**Issue by mansion-sun** [ant-design/ant-design#49252]
### What problem does this feature solve?

在使用Upload Dragger做纯前端上传应用时，可以在上传directory和拖拽上传directory时，在beforeUpload二个参数中获取fileList

### What does the proposed API look like?

Upload beforeUpload 在拖拽上传directory时，第二个参数中fileList返回的是本次上传的所有文件列表；与选择文件夹上传directory时行为保持一致。
部分代码如下
```
  // 拖拽上传组件属性对象
  const draggerProps = {
    className: styles["upload-dragger-container-wrapper"],
    name: 'fileList',
    directory: true,
    showUploadList: false,
    beforeUpload: (file, fileList) => {
      console.log('beforeUpload file, fileList', file, fileList)
// 选择文件夹上传时此处fileList正常，当拖拽上传文件夹时此处是每次上传的file
      setFileList(fileList);
      return false;
    },
    // fileList,
    onChange({fileList} = {}) {
      console.log('onChange fileList', fileList)
// 每次上传都要清空fileList，不能使用此处的fileList
      // setFileList(fileList);
    },
    onDrop(e) {
      console.log('Dropped fileList', e.dataTransfer.files);
    },
  };
```
重现用例：
https://codesandbox.io/p/sandbox/tuo-zhuai-shang-chuan-antd-4-24-12-forked-kjrx4q?file=%2Fdemo.tsx%3A12%2C1

**Comment by mansion-sun** [comment]
重现用例：
https://codesandbox.io/p/sandbox/tuo-zhuai-shang-chuan-antd-4-24-12-forked-kjrx4q?file=%2Fdemo.tsx%3A22%2C29

**Comment by mansion-sun** [comment]
> Hello @mansion-sun. Please provide a online reproduction by forking codesandbox of [antd@5.x](https://u.ant.design/codesandbox-repro) or [antd@4.x](https://u.ant.design/codesandbox-repro-4x), or provide a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @mansion-sun，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [antd@5.x](https://u.ant.design/codesandbox-repro) 或 [antd@4.x](https://u.ant.design/codesandbox-repro-4x) 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
重新用例：
https://codesandbox.io/p/sandbox/tuo-zhuai-shang-chuan-antd-4-24-12-forked-kjrx4q?file=%2Fdemo.tsx%3A22%2C29

**Comment by afc163** [comment]
<img width="767" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/7bd186e9-b675-45e3-859b-7ccaf93c5144">

**Comment by mansion-sun** [comment]
> https://codesandbox.io/p/sandbox/tuo-zhuai-shang-chuan-antd-4-24-12-forked-kjrx4q?file=%2Fdemo.tsx%3A22%2C29

https://codesandbox.io/p/sandbox/tuo-zhuai-shang-chuan-antd-4-24-12-forked-kjrx4q?file=%2Fdemo.tsx%3A21%2C20-21%2C32

**Comment by coderz-w** [comment]
我来看看

**Comment by mansion-sun** [comment]
> 我来看看

大概什么时候，可以在antd4.x看到这个修复

**Comment by coderz-w** [comment]
> > 我来看看
> 
> 大概什么时候，可以在antd4.x看到这个修复

4已经不维护了吧，现在已经改好了在想怎么写单侧

**Comment by mansion-sun** [comment]
> 我来看看

大概什么时候，可以在antd4.x看到这个修复

**Comment by mansion-sun** [comment]
> 我来看看

大概什么时候，可以在antd4.x看到这个修复

**Comment by mansion-sun** [comment]
如果不升级5，有什么替代方案可以修复这个问题

**Comment by mansion-sun** [comment]
https://ant-design.antgroup.com/docs/react/migration-v5-cn#%E9%80%9A%E8%BF%87%E5%88%AB%E5%90%8D%E5%AE%89%E8%A3%85-v5
我尝试了antd-v5，目前并未生效，预计什么时候发布可以透漏下

**Comment by yoyo837** [comment]
Fixed in https://github.com/react-component/upload/pull/561

**Comment by zombieJ** [comment]
要发个 minor，我先 reopen 一下下哈~

**Comment by ZhouJiahao228** [comment]
所以现在有啥好办法解决？ 拿 file 自己去构造 fileList 之后再去使用？
