### ISSUE TITLE
Make Button Better

### ISSUE THREAD

**Issue by xieyihao** [ant-design/ant-design#4925]
#### Environment(required)

- antd version: 2.7.1

Hey guys, can Button component add "delay" API？ like [delay](https://ant.design/components/spin/#components-spin-demo-delayAndDebounce) in Spin. 

I like this attribute, Sometimes, it make UI friendly and I can realize easily

**Comment by benjycui** [comment]
Are you going to delay `loading` animation?

**Comment by xieyihao** [comment]
@benjycui  yeah, base on the Button loading

**Comment by benjycui** [comment]
How about this?

```jsx
// loading: boolean | Object { delay: number }
<Button loading={{ delay: 1000 }} />
```

**Comment by RaoHai** [comment]
My suggetion is following this [promotion](https://github.com/ant-design/ant-design/issues/4544#issuecomment-271533135),  overriding `loading` props of `Button` and other Components who has `loading` props.

**Comment by xieyihao** [comment]
@benjycui   I want to change the loading state dynamically, can it be?

```
<Button loading={{ delay: 1000, spinning: boolean }} />
```

@RaoHai   very nice .

**Comment by afc163** [comment]
Button is a simple component and `loading={{ *** }}` will make it too complex. How about adding a default loading delay which can't be changed?

**Comment by xieyihao** [comment]
Can those Components who have  ```loading``` props do better?

**Comment by RaoHai** [comment]
Smaller complexity, default 300ms delay (same as spin), without configurability.
