### ISSUE TITLE
DatePicker - Months disabled in Month Panel if first and last day of month is disabled

### ISSUE THREAD

**Issue by mkrakhofer** [ant-design/ant-design#49263]
### Reproduction link

[https://t.ly/kdE2g](https://t.ly/kdE2g)

### Steps to reproduce

- render a DatePicker
- pass in a disabledDate function that disables all Saturdays and Sundays
- enter the Month Panel of the DatePicker
- All months, where the first and last day is disabled are also disabled in the Month Panel, even though the user could select other dates of the month

Examples: June 2024, November 2025, ...

### What is expected?

As users still could select other days of the month, it should be possible to select the month.

### What is actually happening?

Users can not select the month as it is disabled and have to work around this issue.

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 125.0.6422.142 |

**Comment by mkrakhofer** [comment]
It is possible to bypass this issue by using `onPanelChange` to determine, if the DatePicker is in mode `month` and not applying the `disabledDate` function in this case.

**Comment by mkrakhofer** [comment]
(closed by accident)

**Comment by u4aew** [comment]
When the component receives mode = month, it selects the first day. Since, according to the condition, this should not be a Sunday or Saturday, it blocks this month. Maybe it should be set to mode = date?

**Comment by zombieJ** [comment]
DatePicker by default will check the month first date & last date to check if current month is disabled which is design to save perf. You can use `disabledDate` second param to get current disabled level:

```tsx
disabledDate(date, info) => {
  // info.type will be `month` so you can skip disabled.
}
```
