### ISSUE TITLE
antd5.x+next14的低版本兼容性问题

### ISSUE THREAD

**Issue by Mr-ChaiPeng** [ant-design/ant-design#49272]
在谷歌低版本中显示效果：
![image](https://github.com/ant-design/ant-design/assets/104434916/73c4d433-cfb4-48a8-a957-3775649dd19c)

想做成antd官网的这种效果，如果浏览器版本过低获取不支持，就显示一个弹窗，这种怎么实现呢
![image](https://github.com/ant-design/ant-design/assets/104434916/565fff18-d6ba-404a-ad12-435583b84e12)

**Comment by zombieJ** [comment]
可以直接 clone antd 代码搜一下关键词
