### ISSUE TITLE
通知的大小写

### ISSUE THREAD

**Issue by NexusLin** [ant-design/ant-design#49282]
### Reproduction link

[https://github.com/ant-design](https://github.com/ant-design)

### Steps to reproduce

import { Notification } from "antd"; 应该更改为import { notification } from "antd";当我使用官方推荐的import { Notification } from "antd";时候提示我Notification 不存在

### What is expected?

import { Notification } from "antd"; 应该更改为import { notification } from "antd";

### What is actually happening?

import { Notification } from "antd"; 应该更改为import { notification } from "antd";

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | react18.3.1 |
| System | win10 |
| Browser | chrome |

---
import { Notification } from "antd"; 应该更改为import { notification } from "antd";

**Comment by NexusLin** [comment]
// let res=articleList.filter(item => item.dict_code === value);

**Comment by Wxh16144** [comment]
一个是静态方法，一个是组件？

**Comment by NexusLin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在忙，暂时无法亲自回复您的邮件。结束后，我将尽快给您回复。
