### ISSUE TITLE
To make selected value editable in Treeselect

### ISSUE THREAD

**Issue by pranjal2892** [ant-design/ant-design#49293]
### What problem does this feature solve?

If the user searches and selects a value. later user wants to update the selected value partially. user does not have to write a complete string. For Ex: 
If a tree has leaf1 ... 7 
user selects leaf1.
user edits leasf1, removes 1, and puts 2 
when selected leaf2 will be there in the text field 
it should not set value in the background.
currently user has to type "leaf2". 

### What does the proposed API look like?

The Textfield of Treeselect should be a normal text field 
the selected value should be added to the value prop of the input field, not in the span field

**Comment by afc163** [comment]
It is more like a AutoComplete but a Select component.

**Comment by afc163** [comment]
I suggest that you could create a custom TreeSelect component that using a Input to save TreeSelect's selected value.
