### ISSUE TITLE
cssinjs 的钩子函数性能开销大的问题

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#49298]
### Reproduction link

[https://github.com/guoyunhe/antd-css-in-js-performance](https://github.com/guoyunhe/antd-css-in-js-performance)

### Steps to reproduce

1. git clone
2. npm install
3. npm start
4. 在 Chrome 浏览器的性能工具中，重新加载页面并记录性能

### What is expected?

cssinjs 的 CPU 开销应该只占少部分

### What is actually happening?

cssinjs 的 CPU 开销占了大部分，且主要集中在 useStyleRegister 这个钩子函数

![image](https://github.com/ant-design/ant-design/assets/5836790/543f3876-9429-4b66-a87a-d8d5c9563d3e)

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.3.0 |
| System | macOS |
| Browser | Chrome 125 |

**Comment by afc163** [comment]
合并至 #49278 讨论
