### ISSUE TITLE
Table 组件不支持 hot-loader

### ISSUE THREAD

**Issue by mydearxym** [ant-design/ant-design#493]
调试 Table 组件时不支持热加载，必须手动刷新浏览器才能看到改动后的效果。其他组件没有这个问题。

**Comment by afc163** [comment]
https://github.com/ant-design/antd-bin/blob/master/HISTORY.md

hot-loader 功能有很多问题，已经从工具上移除了。

**Comment by mydearxym** [comment]
Hi @afc163  我不是说开发工具的 hot-loader , 是说在我的项目中其他组件都能支持 hot-loader , 只有 Table 组件不行 ， 改动后必须刷新才能看到效果

**Comment by afc163** [comment]
可以帮忙排查下具体问题。

**Comment by mydearxym** [comment]
hi @afc163  是我的代码有问题，因为之前我需要在table某一行里 dispatch 一个 action ，而 table 的 columns 用的是全局的变量，没有放在 react 组件内，导致 hot-loader 失效（hot-loader貌似只负责 react 组件）。

**Comment by afc163** [comment]
:+1:
