### ISSUE TITLE
Allow Affix to have a floating title with the menu

### ISSUE THREAD

**Issue by janarvaezkng** [ant-design/ant-design#49304]
### What problem does this feature solve?

Sometimes the links themselves are not explanatory enough. It would be great to have the option to allow adding a Title (or maybe even a surrounding box with any markup on top or bottom?) that scrolls along with the menu items in the affix, so that when scrolling (and especially when deep-linking) the floating links have a better meaning for the user.

### What does the proposed API look like?

A simple prop to specify the title (of type ReactNode).
```ts 
<Anchor
    items={menuItems}
    title="Main menu"
/>
```

also, a content box that contains all the items but can add extra markup around it:
```ts 
<Anchor
    items={menuItems}
    contentBox={(itemsRender) => {
        return (
            <Card title="Article sections">
                {itemsRender}
                <Typography.Text type="secondary">This is a small footer</Typography.Text>
            </Card>
        )
    }}
/>
```

**Comment by afc163** [comment]
What is it looks like? Could you provide a screenshot?

**Comment by janarvaezkng** [comment]
Sure, these are a rough mockup as an example

Custom title:
![anchor-title](https://github.com/ant-design/ant-design/assets/127384873/9a0e8a17-d193-4a49-85ec-ea31eb63ef78)

Custom content box:
![content-box-example](https://github.com/ant-design/ant-design/assets/127384873/da0bb6d8-d1c2-4c45-bf8c-d5ad4a7687f3)

The idea is to be able to attach elements to the floating anchor, so that they scroll alongside the menu links

**Comment by afc163** [comment]
```jsx
<Affix>
  <Card>
    <Anchor affix={false} />
  </Card>
</Affix>
```

How about that?

**Comment by janarvaezkng** [comment]
🤦 exactly that! 😅 
Then nevermind about this request. 
An example in the Anchor docs would be nice, but other than that, this works great. 
Thank you for looking into it.
