### ISSUE TITLE
Form item

### ISSUE THREAD

**Issue by robertoperesneto** [ant-design/ant-design#49308]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/recursing-lumiere-nd2rd6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx4o7awc00063j6h2q7ii2kf%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx4o7awc00023j6h5a9v7rxi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx4o7awc00033j6h1k5158uw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx4o7awc00053j6hthlhdm67%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx4o7awc00023j6h5a9v7rxi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4o7awc00013j6hd33bq4l3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx4o8gzv00383j6hplhzhqhp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A51%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A51%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx4o7awc00023j6h5a9v7rxi%2522%252C%2522activeTabId%2522%253A%2522clx4o8gzv00383j6hplhzhqhp%2522%257D%252C%2522clx4o7awc00053j6hthlhdm67%2522%253A%257B%2522id%2522%253A%2522clx4o7awc00053j6hthlhdm67%2522%252C%2522activeTabId%2522%253A%2522clx4o7awc00043j6h28q9uprp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx4o7awc00043j6h28q9uprp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522CHANGELOG%2522%252C%2522id%2522%253A%2522clx4o8mao004m3j6h0w8mkb6a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clx4o7awc00033j6h1k5158uw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx4o7awc00033j6h1k5158uw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

When adding the noStyle property to the Form.Item component

### What is expected?

When using noStyle, the Label property is not lost

### What is actually happening?

When I use it with the noStyle property it loses the Label... is this on purpose?

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
It is intented behavior.

**Comment by robertoperesneto** [comment]
Is there any way I can get around this?
To use noStyle and keep the label?

**Comment by balboFK** [comment]
@afc163 @zombieJ Isnt it kinda weird as that is the "standard" behaviour, is the label considered a "style"? I dont see that as a stylistic choice or add-on. Maybe form.item should also adapt to accept "styles" and it should be able to pass props to the "label" and to the component being rendered, like others components have been migrated. That would allow to still remove the "styling" which involves the padding, margin, and others, and keep the "label", since it is indeed not a "style".

**Comment by afc163** [comment]
Why do you need a noStyle Form.Item with label, could you just remove `noStyle`?

**Comment by balboFK** [comment]
> Why do you need a noStyle Form.Item with label, could you just remove `noStyle`?

Normally to remove the styling of padding and other default stylings that the theme might have for that specific Form.Item, i imagine that this is the intended way of using it right? To remove styles/classNames from my theme of that specific item. But the label should stay, i dont think it is a "style" per say.
