### ISSUE TITLE
Fixed Anchor lacks ball functionality

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#4930]
antd version: 2.7.1
Fixed Anchor lacks ball functionality.

Not sure whether fixed anchor should or shouldn't display the ball. In [the example](https://ant.design/components/anchor/) does not.
However I would like to use the fixed anchor with the ball functionality. 
Is it possible?

Thanks for feedback ...

**Comment by RaoHai** [comment]
Small balls are designed to be invisible in fixed Anchor. 

A configuration is given in [here](https://github.com/ant-design/ant-design/pull/4960) to show it in .

**Comment by froston** [comment]
cool thanks!
