### ISSUE TITLE
【Development】Carousel 组件支持根据 Item 高度自适应

### ISSUE THREAD

**Issue by kiner-tang** [ant-design/ant-design#49319]
### What problem does this feature solve?

很多情况下，走马灯当中每一个 Slide 的高度是不一样的，当前的走马灯无法根据 Slide 的高度自适应整个走马灯的高度。期望 Swiper 支持自适应高度属性

### What does the proposed API look like?

API 和效果参考：https://www.swiper.com.cn/api/parameters/294.html 。

![2024-06-10 100623](https://github.com/ant-design/ant-design/assets/10286961/d0ea35f6-53e9-4505-82e5-438570e2da53)

```tsx
<Carousel afterChange={onChange} autoHeight>
  <div>
    <h3 style={contentStyle}>1</h3>
  </div>
  <div>
    <h3 style={contentStyle}>2</h3>
  </div>
  <div>
    <h3 style={contentStyle}>3</h3>
  </div>
  <div>
    <h3 style={contentStyle}>4</h3>
  </div>
</Carousel>
```

**Comment by afc163** [comment]
好像看不到效果。

**Comment by kiner-tang** [comment]
> 好像看不到效果。

![2024-06-10 100623](https://github.com/ant-design/ant-design/assets/10286961/d0ea35f6-53e9-4505-82e5-438570e2da53)

**Comment by wanpan11** [comment]
可以使用 adaptiveHeight 属性

```
adaptiveHeight={true}
```

更多属性可参考 [react-slick](https://react-slick.neostack.com/docs/api)
