### ISSUE TITLE
input number add precision to formatter input parameters

### ISSUE THREAD

**Issue by konstantinsp** [ant-design/ant-design#49327]
### What problem does this feature solve?

this will help to format number precision based on component precision property.
currently there is no way of creating generic function that will handle number input formatter based on precision property of component.

### What does the proposed API look like?

probably it can be added to info argument of formatter function
formatter = function(value: number | string, info: { userTyping: boolean, input: string, **precision: number** }): string

**Comment by zombieJ** [comment]
`precision` is a prop that you've already have:

```tsx
const MyInputNumber = ({ precision, formatter, ...restProps }) => (
  <InputNumber {...restProps} precision={precision} formatter={(value, info) => formatter(value, { ...info, precision })} />
);
```

**Comment by konstantinsp** [comment]
so i need to create another component to use it in formatter. not very convenient...
