### ISSUE TITLE
Tree.TreeNode's width will be 100% as Tree

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#4932]

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/23088864/1574b9c2-f5bc-11e6-85c6-051b0b2babf8.png)

**Comment by benjycui** [comment]
和这个有冲突 https://github.com/ant-design/ant-design/issues/3854 

pending

**Comment by benjycui** [comment]
> 那就半通栏吧，hover 色从文字开始，到容器结束

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/23449329/e7d7181a-fe90-11e6-89a3-8e77edd85f1e.png)

**Comment by benjycui** [comment]
Just keep component as simple as possible, so add tricks in demo, instead a new API.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/d081ab6614f12e7c0a0e42d212293bcc8e21fc4d#commitcomment-21747156

**Comment by zombieJ** [comment]
Dir tree will release in `3.7.0`
