### ISSUE TITLE
SubMenu defaultOpenKeys doesn't open if Menu inside custom Component

### ISSUE THREAD

**Issue by mmacedoeu** [ant-design/ant-design#4933]
#### Environment(required)

- antd version: "^2.7.1"
- OS and its version: Ubuntu 15.10
- Browser and its version: Chrome Version 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

Put Menu.Item inside Custom Component

#### What do you expected?

Menu Opened

#### What happen?

Menu Closed

#### Re-producible online demo

http://codepen.io/mmacedoeu/pen/aprEwJ?editors=0010#0

**Comment by afc163** [comment]
Submenu do not support HOC yet, you can trace #4853
