### ISSUE TITLE
UX of Table when change  loading prop.

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#4934]
- antd version:2.7.2
- OS and its version:window
- Browser and its version:chrome

**Table component will have the feeling of jitter when change the loading prop**

- http://codepen.io/anon/pen/RKmMyV?editors=0010

**Comment by afc163** [comment]
What do you expect?

**Comment by zhangchao828** [comment]
@afc163 更新到2.7.2之后才出现这种细微的变化，在加载切换的时候，是不是有种整个表格抖动一了一下的感觉，之前是没有的，， 原谅我英语不太好

**Comment by afc163** [comment]
![1](https://cloud.githubusercontent.com/assets/507615/23090940/12b77232-f5e5-11e6-8cd1-ea63544d2011.gif)

这是我看到的效果，不知道和你看到的是否一致。如果你的不一样，不妨录一个 gif 。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/XpwqXX

这是 2.7.1 的效果，确实柔和很多。https://github.com/ant-design/ant-design/pull/4869 的改动影响了效果，我想想鱼和熊掌能否兼得吧。

**Comment by zhangchao828** [comment]
哈哈，是的，有点强迫症，就提了一下

**Comment by lcoder** [comment]
咋解决，不升级的话，确实有抖动诶
