### ISSUE TITLE
Image add width attribute，and effect preview image width

### ISSUE THREAD

**Issue by WLyKan** [ant-design/ant-design#49350]
### Reproduction link

[https://ant-design.antgroup.com/~demos/image-demo-basic](https://ant-design.antgroup.com/~demos/image-demo-basic)

### Steps to reproduce

https://ant-design.antgroup.com/~demos/image-demo-basic

### What is expected?

preview should show full width image

### What is actually happening?

Image add width attribute，and effect preview image width

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | latest |
| System | macOS 14.5 |
| Browser | Chrome latest |

**Comment by wanpan11** [comment]
You can use imageRender to achieve this effect

**Comment by zombieJ** [comment]
reinstall `node_modules`. This has already been fixed with `rc-image@7.8.1`
