### ISSUE TITLE
菜单设置mode为inline模式，收缩菜单时子菜单仍然显示

### ISSUE THREAD

**Issue by AngusFwhaks** [ant-design/ant-design#49355]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-i5m4f5?file=demo.tsx)

### Steps to reproduce

更改defaultSelectedKeys和defaultIOpenKeys为selectedKeys和openKeys，点击收缩按钮，子菜单依然显示

### What is expected?

子菜单隐藏，鼠标经过上级菜单再显示

### What is actually happening?

子菜单一直显示

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.3.1 |
| System | mac M1 Pro 14.5 (23F79) |
| Browser | google 125.0.6422.142 |

**Comment by afc163** [comment]
这是符合预期的，当写死 openKeys 时为受控模式，菜单状态需要和 openKeys 保持一致。
