### ISSUE TITLE
Cannot find module '../../package.json'

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#4935]
```sh
Error in E:\xxx\node_modules\antd\lib\version\index.d.ts
(1,25): error TS2307: Cannot find module '../../package.json'.
```

The  latest version` 2.7.2 ` doesn't work with TypeScript project due to the version Component has import a `package.json` file. 

cc @afc163 This need fixed or try another way export version info. TypeScript can't understand json file module at this time,may be it will support it in the future.

**Comment by afc163** [comment]
I forgot `index.d.ts`.

**Comment by xuyang2** [comment]
Workaround for TypeScript 2+
in your `typings.d.ts`
```
declare module "*.json" {
    export let version;
}
```

**Comment by Penggggg** [comment]
您好！~我是小白..什么意思呀？是要改 ‘ scripts/prepub.js’ 文件吗？我找不到这个文件呀

**Comment by afc163** [comment]
@Penggggg Wait for patch version later in today.

**Comment by Penggggg** [comment]
@afc163 Thanks for your response. But i still can't resolve this problem.. would you tell me in detail? thank you ! 感谢您的回复，请问patch是已经发版了吗？

**Comment by afc163** [comment]
2.7.3
