### ISSUE TITLE
Theme algorithm switch issue for inputs and labels

### ISSUE THREAD

**Issue by AlexEmashev** [ant-design/ant-design#49365]
### Reproduction link

[https://ant.design/components/form](https://ant.design/components/form)

### Steps to reproduce

1. Open page in a Chrome based browser (system preferred scheme 'light')
2. Switch page theme to the "Dark theme" via control at the bottom right

### What is expected?

Inputs background color turns to the darker tone.
Label color turns to the light tone.

### What is actually happening?

Color of inputs and label stays the same as in light theme.

![Screen Recording 2024-06-11 at 18 39 56](https://github.com/ant-design/ant-design/assets/11290254/6598e1c9-0ac6-43ce-bb44-51d5d5574320)

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2.0 |
| System | macOS |
| Browser | 125.0.6422.142 |

---
Reproduced in Chrome, Firefox. Won't reproduce in Safari.
At the site, if I switch between sections, everything goes to normal and theme algorithm starts to work for input and labels.

In my own project I've got the same issue with inputs and labels.

**Comment by zombieJ** [comment]
Seems css var not working on the switch. cc @MadCcc

**Comment by MadCcc** [comment]
Official site only. Wait for https://github.com/ant-design/ant-design/pull/49109

**Comment by MadCcc** [comment]
For detail, it is caused by wrong hydration behavior of Umi.
If you encountered with same issue, make sure that your render node and hydrate node are the same.
