### ISSUE TITLE
Extra pads on table fixed header

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#4936]
See http://codepen.io/wmf/pen/rLqYrj?editors=0010

![wx20170218-153048](https://cloud.githubusercontent.com/assets/465125/23091365/49775bc0-f5ef-11e6-83bf-1eaec3ce70ef.png)

**Comment by yesmeck** [comment]
@ @

**Comment by afc163** [comment]
custom the opacity of webkit scrollbar will cause [this](https://github.com/react-component/table/blob/d912793ba7b3023a7c278199f6bcb4e1e29bb7fc/src/Table.jsx#L442-L447) not execute.

**Comment by afc163** [comment]
It have been a long fight will #4637 ..

**Comment by zpczpc** [comment]
![image](https://cloud.githubusercontent.com/assets/20511586/23409495/bf5c3580-fe06-11e6-9d88-20cfec0b09ad.png)
table使用expandedRowRender属性时存在的问题是：表格的列对齐有问题，展开时，水平对齐有问题

**Comment by yesmeck** [comment]
@zpczpc 请单独开 issue。

**Comment by afc163** [comment]
https://codepen.io/anon/pen/OYqjQO?&editable=true&editors=001
