### ISSUE TITLE
Adds the hability to use data-cy and data-testid to improve the performance with the integration tests with Cypress and Playwright

### ISSUE THREAD

**Issue by leandroaps** [ant-design/ant-design#49362]
### What problem does this feature solve?

This will solve the problem to find and specific element during the integration tests, like, to find the day, month inside a calendar, an option inside a select, a link inside a menu, we need to use the HTML tree to find an element and it is not the best approach. Also, most elements does not have a role or title to be used.

### What does the proposed API look like?

Add data attributes, data-cy and data-testid, on each element rendered by the component, using displayName as Kebab pattern on each HTML tag inside the component, can use the name of the CSS class, like ant-picker, ant-picker-ranger. Example:

```
<div class="ant-picker ant-picker-range ant-picker-outlined css-1okl62o sc-sLtfs kLlnaK" data-testid="ant-picker">
  <div class="ant-picker-input" data-testid="ant-picker-input">
    <input
      aria-invalid="false"
      autocomplete="off"
      data-testid="ant-picker-input-start-date"
      size="12"
      placeholder="Start date"
      date-range="start"
      value=""
    />
  </div>
  <div class="ant-picker-range-separator" data-testid="ant-picker-range-separator">
    <span aria-label="to" class="ant-picker-separator" data-testid="ant-picker-separator"
      ><span role="img" aria-label="swap-right" class="anticon anticon-swap-right" data-testid="anticon-swap-right"
        ><svg
          viewBox="0 0 1024 1024"
          focusable="false"
          data-icon="swap-right"
          width="1em"
          height="1em"
          fill="currentColor"
          aria-hidden="true"
          data-testid="icon-swap-right"
        >
          <path
            d="M873.1 596.2l-164-208A32 32 0 00684 376h-64.8c-6.7 0-10.4 7.7-6.3 13l144.3 183H152c-4.4 0-8 3.6-8 8v60c0 4.4 3.6 8 8 8h695.9c26.8 0 41.7-30.8 25.2-51.8z"
          ></path></svg></span
    ></span>
  </div>
  <div class="ant-picker-input" data-testid="ant-picker-input">
    <input
      aria-invalid="false"
      autocomplete="off"
      data-testid="ant-picker-input-end-date"
      size="12"
      placeholder="End date"
      date-range="end"
      value=""
    />
  </div>
  <div class="ant-picker-active-bar" style="position: absolute; width: 95px; left: 11px" data-testid="ant-picker-active-bar"></div>
  <span class="ant-picker-suffix" data-testid="ant-picker-suffix"
    ><span role="img" aria-label="calendar" class="anticon anticon-calendar" data-testid="anticon-calendar"
      ><svg
        viewBox="64 64 896 896"
        focusable="false"
        data-icon="calendar"
        width="1em"
        height="1em"
        fill="currentColor"
        aria-hidden="true"
        data-testid="icon-calendar"
      >
        <path
          d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zM184 392V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136H184z"
        ></path></svg></span
  ></span>
</div>
```

**Comment by leandroaps** [comment]
HTML Example:

<div class="ant-picker ant-picker-range ant-picker-outlined css-1okl62o sc-sLtfs kLlnaK" data-testid="ant-picker">
  <div class="ant-picker-input" data-testid="ant-picker-input">
    <input
      aria-invalid="false"
      autocomplete="off"
      data-testid="ant-picker-input-start-date"
      size="12"
      placeholder="Start date"
      date-range="start"
      value=""
    />
  </div>
  <div class="ant-picker-range-separator" data-testid="ant-picker-range-separator">
    <span aria-label="to" class="ant-picker-separator" data-testid="ant-picker-separator"
      ><span role="img" aria-label="swap-right" class="anticon anticon-swap-right" data-testid="anticon-swap-right"
        ><svg
          viewBox="0 0 1024 1024"
          focusable="false"
          data-icon="swap-right"
          width="1em"
          height="1em"
          fill="currentColor"
          aria-hidden="true"
          data-testid="icon-swap-right"
        >
          <path
            d="M873.1 596.2l-164-208A32 32 0 00684 376h-64.8c-6.7 0-10.4 7.7-6.3 13l144.3 183H152c-4.4 0-8 3.6-8 8v60c0 4.4 3.6 8 8 8h695.9c26.8 0 41.7-30.8 25.2-51.8z"
          ></path></svg></span
    ></span>
  </div>
  <div class="ant-picker-input" data-testid="ant-picker-input">
    <input
      aria-invalid="false"
      autocomplete="off"
      data-testid="ant-picker-input-end-date"
      size="12"
      placeholder="End date"
      date-range="end"
      value=""
    />
  </div>
  <div class="ant-picker-active-bar" style="position: absolute; width: 95px; left: 11px" data-testid="ant-picker-active-bar"></div>
  <span class="ant-picker-suffix" data-testid="ant-picker-suffix"
    ><span role="img" aria-label="calendar" class="anticon anticon-calendar" data-testid="anticon-calendar"
      ><svg
        viewBox="64 64 896 896"
        focusable="false"
        data-icon="calendar"
        width="1em"
        height="1em"
        fill="currentColor"
        aria-hidden="true"
        data-testid="icon-calendar"
      >
        <path
          d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zm-40 656H184V460h656v380zM184 392V256h128v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h256v48c0 4.4 3.6 8 8 8h56c4.4 0 8-3.6 8-8v-48h128v136H184z"
        ></path></svg></span
  ></span>
</div>

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16571#issuecomment-719527981

**Comment by leandroaps** [comment]
The example was the Date picker, but it will be good to have this on all the components as well. I am on 5.11 and there is no data atributes available. In the example of the CodePen, you use <RangePicker data-testid="range-picker" />, this is easy, but we can't do the same on the input for Start and End date. This is what I am talking about. Add the data attributes in a high level is common and usual, but not inside the HTML generated by the And component.

**Comment by afc163** [comment]
PR is welcome~

**Comment by leandroaps** [comment]
Anyone can do it? There is a guideline to follow opening a PR? My team can handle it.

**Comment by afc163** [comment]
@leandroaps https://ant.design/docs/react/contributing
