### ISSUE TITLE
能否支持一下看板组件

### ISSUE THREAD

**Issue by bitbw** [ant-design/ant-design#49368]
### What problem does this feature solve?

大多数管理系统现在都支持列表和看板之间相互切换 ，对任务类型的数据处理很友好， 是一个比较有用的功能

### What does the proposed API look like?

类似这个 https://github.com/markusenglund/react-kanban

类似这样的样式
<img width="567" alt="2" src="https://github.com/ant-design/ant-design/assets/55389796/2e95e86c-dad2-47a2-bfca-75a8f2f2a9e6">

**Comment by horizon0514** [comment]
[pragmatic-drag-and-drop](https://github.com/atlassian/pragmatic-drag-and-drop)
maybe you need this

**Comment by zombieJ** [comment]
感谢反馈，但是这个组件看起来业务属性有点太强了。不会落到原子组件库中哈~

**Comment by bitbw** [comment]
> 感谢反馈，但是这个组件看起来业务属性有点太强了。不会落到原子组件库中哈~

哈哈 好的 那能否在代码演示里给个 example 呢😁

**Comment by bitbw** [comment]
> > 感谢反馈，但是这个组件看起来业务属性有点太强了。不会落到原子组件库中哈~
> 
> 哈哈 好的 那能否在代码演示里给个 example 呢😁

I found some solutions on GitHub

- https://github.com/clauderic/dnd-kit （You can run an example to see ）
- https://github.com/atlassian/react-beautiful-dnd?tab=readme-ov-file
