### ISSUE TITLE
官网上Select组件文档有误？

### ISSUE THREAD

**Issue by XUHANLIN** [ant-design/ant-design#49375]
### Reproduction link

[https://ant-design.antgroup.com/components/select-cn#select-demo-option-render](https://ant-design.antgroup.com/components/select-cn#select-demo-option-render)

### Steps to reproduce

Select组件中optionRender应该是用来自定义下拉选项的渲染的，但是出现在了【定制回填内容】这个例子中

### What is expected?

修正一下文档

### What is actually happening?

如上

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 无关 |
| System | 无关 |
| Browser | 无关 |

**Comment by afc163** [comment]
愿意是展示 optionLabelProp 这个属性的用法的，改成 optionRender 后这层意义丢掉了。

https://4x.ant.design/components/select-cn/#components-select-demo-option-label-prop

**Comment by MadCcc** [comment]
把 demo 的描述改一下吧
