### ISSUE TITLE
当设置 StyleProvider 使用 layer 后，全局token的 colorWarning 不生效

### ISSUE THREAD

**Issue by jesse996** [ant-design/ant-design#49371]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/new/choose](https://github.com/ant-design/ant-design/issues/new/choose)

### Steps to reproduce

当设置 StyleProvider 使用 layer 后，全局token的 colorWarning 不生效，导致的组件如 Popconfirm 的icon 颜色是黑色而不是黄色

### What is expected?

期望Popconfirm图标颜色是黄色

### What is actually happening?

Popconfirm图标颜色是黑色

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.3.1 |
| System | win10 |
| Browser | 120 |

**Comment by recallwei** [comment]
Duplicate of #49377
