### ISSUE TITLE
A problem about IE11 partial module loading

### ISSUE THREAD

**Issue by OwlAford** [ant-design/ant-design#4938]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: window10
- Browser and its version: IE11

#### What did you do? Please provide steps to re-produce your problem.
When I import whole package  in the compiler vendors，nothing wrong，all the browser are working properly，but when I import package partial，there had been an error，and the project didn't work，only IE11 has this problem.

error code: **SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `RedBoxError`.**

Thanks!

#### Re-producible online demo
http://139.224.128.69:8060/inmanage/app.html

**Comment by OwlAford** [comment]
I should added that IE9 had this problem too

**Comment by benjycui** [comment]
> Check the render method of RedBoxError

?? It's a problem from RedBox?

**Comment by benjycui** [comment]
ref: https://github.com/commissure/redbox-react

**Comment by OwlAford** [comment]
@benjycui no,even if I remove it, the problem still have

**Comment by OwlAford** [comment]
英文不好，我还是用中文再描述一下吧：当我引入整个antd的包时，各大浏览器都是正常的，不会报错，但是当我局部引入组件，按照官方配置知道引入了babel-plugin-import插件，大多浏览器都是能正常运作的，但是在IE9-11下，会一直提示我 【Objects are not valid as a React child 】，即使我移除了redbox，依旧不能解决这个问题，因为它会显示其他组件有同样的错误。 @benjycui ，非常感谢回复

**Comment by benjycui** [comment]
This [error](https://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]=) is confusing

```bash
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}).
```

For `{$$typeof, type, key, ref, props, _owner}` should be valid React element.

**Comment by benjycui** [comment]
It seems that it's React's issue http://stackoverflow.com/questions/40897966/objects-are-not-valid-as-a-react-child-in-internet-explorer-11-for-react-15-4-1

**Comment by benjycui** [comment]
See: https://github.com/facebook/react/issues/8379#issuecomment-263962787

Solution: https://github.com/facebook/react/issues/8379#issuecomment-264858787

**Comment by OwlAford** [comment]
@benjycui thanks! You mean it’s a react bug ?

**Comment by OwlAford** [comment]
非常感谢，这个问题已经解决！只要在react前引入es的polyfill即可
