### ISSUE TITLE
input 带 search 的状态下，底部没有对齐

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#49385]
### Reproduction link

[https://ant.design/~demos/components-input-demo-search-input](https://ant.design/~demos/components-input-demo-search-input)

### Steps to reproduce

查看 search 左下角

### What is expected?

和输入底部对齐

### What is actually happening?

没和输入底部对齐

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3 |
| System | windows |
| Browser | chrome 版本 125.0.6422.142（正式版本） （64 位） |

**Comment by afc163** [comment]
<img width="404" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/de95ac4f-4c98-48bb-b677-64ab2e8d9749">

我这里没发现问题。

**Comment by tolerance-go** [comment]
![image](https://github.com/ant-design/ant-design/assets/37258382/b138176b-5694-459a-bfdd-01cc39700025)

下面是 edge 也复现了（无插件）

![image](https://github.com/ant-design/ant-design/assets/37258382/85fe3e7f-1efc-4705-8ce1-b7def0036531)

我的电脑是 windows Windows 11 专业版 22631.3593 Windows Feature Experience Pack 1000.22700.1003.0
