### ISSUE TITLE
Table with virtual={true} doesn't register scroll of the page in Firefox browser

### ISSUE THREAD

**Issue by sc4lr** [ant-design/ant-design#49399]
### Reproduction link

[https://codepen.io/sc4lr/pen/yLWPgpm](https://codepen.io/sc4lr/pen/yLWPgpm)

### Steps to reproduce

1. Open reproduction link in **Firefox browser**
2. Scroll to the very bottom of the page so there's a area that can be scrolled to the top
3. Put a cursor into a table (hover the only one row)
4. Try to scroll to the top

### What is expected?

Page is being scrolled.

### What is actually happening?

Page is not being scrolled. Body scroll isn't registered at all when cursor inside virtual table.

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | MacOS Sonoma 14.5 |
| Browser | Firefox 127.0 (64-bit) |

---
I tried to scroll only with mac touchpad. Don't know if there's such problem with mouse scroll.

Could reproduce this only in **Firefox**. There's no such bug in **Google Chrome** or **Safari**

**Comment by sc4lr** [comment]
@MadCcc Hi! Could you tell me what else is required to be provided to remove `unconfirmed` tag?
And is there any news or parts to look at in this bug?

Thanks!

**Comment by sc4lr** [comment]
@MadCcc
Hi! Is there any news about this issue? This bug seems really annoying for FF users

Thanks!

**Comment by sc4lr** [comment]
@afc163 @zombieJ

**Comment by afc163** [comment]
Could you provide a screen record video? I can't see the problem.

**Comment by sc4lr** [comment]
@afc163 
Screen record won't help here very much because it won't show anything. But I attached it anyway.

Please, repeat reproduction steps that I mentioned above. Make sure that body has a scroll bar. Minimize your window if it's not. Put your cursor into the only one row of the table (not header). Use Firefox browser. Try to scroll the page.

The expected behavior is that the page is being scrolled once there's no area to scroll in table

Firefox (where bug occurs) is on the left side and Google Chrome (where everything works fine) is on the right side of the video.

https://github.com/user-attachments/assets/7d207789-b724-4520-83ab-152f423ca8e0

**Comment by afc163** [comment]
I see the problem now, thx for video~

**Comment by sc4lr** [comment]
Could you remove `unconfirmed` label at least please?

**Comment by hanszeng-chn** [comment]
It's caused by the `rc-virtual-list` package, It invokes e.preventDefault no matter if it reached the top/bottom of the list at firefox. I think I can take it on.
