### ISSUE TITLE
Tooltip components in a nested overlay are not rendered correctly after being wrapped in a component.

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#49392]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-xwrkzk?file=demo.tsx)

### Steps to reproduce

Click on the two components separately, left successfully rendered, right not rendered dropdown menu

### What is expected?

Correctly rendered dropdown menu on the right

### What is actually happening?

Dropdown menu not rendered correctly on the right side

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | macOS 14.4.1 - arm64 Apple M2 Pro |
| Browser | Chrome: 125.0.6422.142 |

**Comment by zombieJ** [comment]
You should pass props to your customize component. The hover event is blocked since you not pass.

https://stackblitz.com/edit/react-xwrkzk-5ndedr?file=demo.tsx

**Comment by zhenzhenChange** [comment]
OK, thanks, that can be fixed. (Only this feels like a hidden behaviour? Can it be addressed in components, like consumption contexts and such.)

---

After wrapping, however, the console will have an additional api deprecation error.

![image](https://github.com/ant-design/ant-design/assets/51586637/537ac0d0-5960-46ed-bdd5-b720687212e5)
