### ISSUE TITLE
Layout布局不支持响应式

### ISSUE THREAD

**Issue by TommyHili** [ant-design/ant-design#494]
antd@0.9.x版本的文档被覆盖到，想看0.9版本的文档都没有！ Layout布局不支持响应式？

**Comment by afc163** [comment]
http://09x.ant.design/

**Comment by kevyu** [comment]
我不会告诉你[http://ant.design](http://ant.design)的右下角是可以切换版本的， :smile: 。

**Comment by kazaff** [comment]
貌似就是不支持响应式layout吧？

**Comment by afc163** [comment]
对，现在不支持。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/1082

暂不支持，建议直接使用 http://roylee0704.github.io/react-flexbox-grid/ 。
