### ISSUE TITLE
Can renderEmpty consume the theme context?

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#49407]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-2ygwmw?file=demo.tsx)

### Steps to reproduce

View theme configuration for demo.

### What is expected?

Custom `renderEmpty` can consume the theme context.

### What is actually happening?

Custom `renderEmpty` failed to consume the theme context.

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | macOS 14.4.1 - arm64 Apple M2 Pro |
| Browser | Chrome: 126.0.6478.62 |

---
My understanding is that the function method, renderEmpty, is only going to be called when the component is rendered, right, and isn't it able to consume the theme context at that point? Or will there be any limitations or workarounds to be done.

**Comment by zhenzhenChange** [comment]
Looking at the code, it turns out that a different theme `Token` is used based on a different `className`, and I need to set another one when I customise it.

https://github.com/ant-design/ant-design/blob/master/components/empty/index.tsx#L71

<img width="1247" alt="image" src="https://github.com/ant-design/ant-design/assets/51586637/eb04f3c2-8d27-4766-96c8-0ec20a83e3f2">

https://github.com/ant-design/ant-design/blob/master/components/empty/style/index.ts#L44

<img width="1366" alt="image" src="https://github.com/ant-design/ant-design/assets/51586637/f35a5952-c2e0-4e03-8193-cd0d574a074d">

**Comment by zhenzhenChange** [comment]
<img width="1797" alt="image" src="https://github.com/ant-design/ant-design/assets/51586637/b2e90bb2-657e-45f1-a470-a655c0ccb275">

**Comment by zombieJ** [comment]
The design of Empty text color is different when use default image. But I think this may be no need:
<img width="192" alt="截屏2024-06-14 10 34 52" src="https://github.com/ant-design/ant-design/assets/5378891/8966ab69-8662-4ec1-958b-0c614dec5a6e">
<img width="154" alt="截屏2024-06-14 10 34 57" src="https://github.com/ant-design/ant-design/assets/5378891/6f63522b-56b9-4608-8f0a-a3e160ae6ae6">
