### ISSUE TITLE
DatePicker dayjs localized formats do not work anymore

### ISSUE THREAD

**Issue by clmz** [ant-design/ant-design#49404]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-r4nhzh?file=demo.tsx)

### Steps to reproduce

See example. Just create a simple DatePicker and set one of the localized dayjs formats like 'L', 'LL' and so on. 

### What is expected?

Show the formatted localized date.

### What is actually happening?

The format string is shown.

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Chrome 125.0.6422.142 64 Bit |

**Comment by clmz** [comment]
That doesn't work or change anything. I still got this:
![image](https://github.com/ant-design/ant-design/assets/47241471/125d5bcd-e9f3-4b1c-a9c4-f65200012b44)

Using these localized formats works in general in the app, but since we've updated antd no more with the date picker.

**Comment by Shtokins** [comment]
@clmz 
`        <DatePicker
           ...
          format={t => t.format('L')}
        />`
