### ISSUE TITLE
DatePiker.RangePicker 使用年份时，先输入结束年份会报错

### ISSUE THREAD

**Issue by luoxiaowei** [ant-design/ant-design#49400]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-mmssch?file=%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxd0gxyf00063b6k2cysms5m%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxd0gxyf00023b6kdyjb0t3x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxd0gxyf00033b6k9glq27hi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxd0gxyf00053b6kb7knukru%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxd0gxyf00023b6kdyjb0t3x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxd0gxyf00013b6kxtxt7zzy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxd0gxyf00023b6kdyjb0t3x%2522%252C%2522activeTabId%2522%253A%2522clxd0gxyf00013b6kxtxt7zzy%2522%257D%252C%2522clxd0gxyf00053b6kb7knukru%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxd0gxyf00043b6kgr3xahjw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxd0gxyf00053b6kb7knukru%2522%252C%2522activeTabId%2522%253A%2522clxd0gxyf00043b6kgr3xahjw%2522%257D%252C%2522clxd0gxyf00033b6k9glq27hi%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxd0gxyf00033b6k9glq27hi%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1、年份的时间区间框，先在结束框里输入年份

### What is expected?

可以直接输入年份

### What is actually happening?

输入完会报错

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.1.0 |
| System | 13-inch, 2020, Two Thunderbolt 3 ports |
| Browser | Google Chrome  125.0.6422.142 |

---
年份的时间区间框，先在结束框里输入年份，会报错。选择面板或者先输入开始年份是没有问题的

**Comment by zombieJ** [comment]
设置一下权限：

<img width="697" alt="截屏2024-06-13 17 28 49" src="https://github.com/ant-design/ant-design/assets/5378891/fab1586a-b50d-4763-9bad-2fde9de54fe3">

**Comment by luoxiaowei** [comment]
权限放开了
