### ISSUE TITLE
dva-cli antd-init atool-build dora 这几个工具分别是干什么的？之间的关系是什么？区别是什么？ 

### ISSUE THREAD

**Issue by Midqiu** [ant-design/ant-design#4940]

**Comment by afc163** [comment]
https://github.com/ant-tool/atool-build/issues/217
https://github.com/dvajs/dva/issues/119
https://github.com/sorrycc/blog/issues/17

**Comment by afc163** [comment]
实话说我也不完全明白。

**Comment by Midqiu** [comment]
看了那几个链接，并没有解决我的困惑  ╯﹏╰

**Comment by afc163** [comment]
antd-init 以脚手架的形式封装了 atool-build 和 dora。

dva-cli 是对 antd-init 的升级和替代。

**Comment by benjycui** [comment]
And `atool-build` is a shallow wrapper of Webpack.

But I like [webpack.parts.js](https://survivejs.com/webpack/developing/composing-configuration/) rather than `atool-build` 😄
