### ISSUE TITLE
Select组件多选情况，点击Tooltips会弹出下拉选项

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#49409]
### Reproduction link

[https://ant.design/components/select-cn](https://ant.design/components/select-cn)

![image](https://github.com/ant-design/ant-design/assets/29728228/986e9b4a-b2b5-4138-af20-b3aab67cad34)

![bug](https://github.com/ant-design/ant-design/assets/29728228/c07b7f51-2487-4be9-9540-77e59e739ae5)

官方例子，直接看动图吧

### Steps to reproduce

https://ant.design/components/select-cn

### What is expected?

点击Tooltip不要弹出下拉选项

### What is actually happening?

点击Tooltip弹出下拉选项

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac/windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
嗯，demo 可以改进一下。

**Comment by zystudios** [comment]
有几个临时解决方案
1 阻止事件冒泡，这个没问题，但是Tooltip本身是不支持事件绑定的，无法直接给Tooltips设置 onMouseDown，只能针对内部元素做绑定，不是很完美，比如极端情况，鼠标点击那个小箭头还是会触发，内部元素覆盖不到
2 改变显示方式，鼠标一旦离开select，tooltip就消失，这个也可以，因为根本没给他点击的机会

但是完美情况还是点击的时候不触发，建议给Tooltip增加事件绑定，这样开发者可以自由决定

<Tooltips
onClick = ...
onMouseDown=...


>

**Comment by wanpan11** [comment]
> 有几个临时解决方案 1 阻止事件冒泡，这个没问题，但是Tooltip本身是不支持事件绑定的，无法直接给Tooltips设置 

这样可以，onMouseDown 事件对 Tooltips 组件没有实际的作用 感觉加不加都行

```tsx
          <div onMouseDown={(evt) => evt.stopPropagation()}>
            <Tooltip title={omittedValues.map(({ label }) => label).join(', ')}>
              <span>Hover Me</span>
            </Tooltip>
          </div>
```
