### ISSUE TITLE
页面缩放时(zoom样式)DatePicker的弹层定位问题 antd V4

### ISSUE THREAD

**Issue by dyxweb** [ant-design/ant-design#49403]
### Reproduction link

[https://codepen.io/dyxweb/pen/eYaeWYM](https://codepen.io/dyxweb/pen/eYaeWYM)

### Steps to reproduce

body标签上设置zoom进行页面缩放时，RangePicker的弹层定位会出现对不齐等问题，同样布局下Select的弹层定位不会有问题。

### What is expected?

body标签上设置zoom进行页面缩放时，RangePicker的弹层定位效果和没有进行缩放时相同

### What is actually happening?

body标签上设置zoom进行页面缩放时，RangePicker的弹层定位会出现对不齐等问题

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | windows |
| Browser | Chrome |

---
5.x版本好像没有上述问题，4.x版本有上述问题

**Comment by zombieJ** [comment]
v4 已经过了维护期了哈。

v5 里对对齐逻辑进行了重写，所以不会有这个问题。

**Comment by dyxweb** [comment]
如果使用v4版本有没有什么好的解决方案呢
