### ISSUE TITLE
-ms-high-constrast控制台废弃warning

### ISSUE THREAD

**Issue by dislido** [ant-design/ant-design#49413]
### Reproduction link

[https://ant.design/components/form-cn](https://ant.design/components/form-cn)

### Steps to reproduce

使用Form.Item组件

### What is expected?

控制台没有warn信息

### What is actually happening?

控制台出现warn信息：[Deprecation]-ms-high-constrast is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/ for tips on updating to the new Forced Colors Mode standard.

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | * |
| System | windows 11 |
| Browser | Edge 125 |

---
 似乎可以直接移除相关代码
https://github.com/ant-design/ant-design/blob/9f2fb20358d846b3a2886964e7fee8a7fd663b4a/components/form/style/fallbackCmp.ts#L17

**Comment by zombieJ** [comment]
这个是给 IE11 做兼容检查用的，新版本的 Edge 是不会生效的。感觉这个 warning 有点蛋疼，因为目的就是为了 Edge 不生效而 IE 生效。
