### ISSUE TITLE
After customising the fonts, the message icons are misaligned.

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#49416]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-flmde8?file=index.css)

### Steps to reproduce

Click on the button to trigger a message popup to see the layout of the icon.

### What is expected?

Typography is normal.

### What is actually happening?

Typography out of alignment.

<img width="409" alt="image" src="https://github.com/ant-design/ant-design/assets/51586637/7eb3fecf-1dcc-4ebb-b376-5f6877d20a96">

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | macOS 14.4.1 - arm64 Apple M2 Pro |
| Browser | Chrome: 126.0.6478.62 |

---
For now, setting the icon's parent to `flex` is a temporary solution.

```css
.ant-message-custom-content {
  display: flex;
} 
```

It's not clear if it's the macos fonts that are causing this, or something else.

**Comment by nova1751** [comment]
Seems changing elememt's display property to `flex` can solve this problem.
