### ISSUE TITLE
DatePicke的弹出框动画与message的弹出动画冲突问题

### ISSUE THREAD

**Issue by cai0117** [ant-design/ant-design#49417]
### Reproduction link

[https://github.com/cai0117/ant-demo](https://github.com/cai0117/ant-demo)

### Steps to reproduce

在DatePicker的onChange方法中使用message.success，会导致在点击日期时（鼠标点击后不发生移动）出现被选择日期的正下方的日期残影。初步原因判断是在关闭动画期间正下方日期略过鼠标导致残影，如果删除message则不会出现。

### What is expected?

在选择时间后input框不会出现选择日期的正下方的日期残影

### What is actually happening?

在选择时间后input框出现选择日期的正下方的日期残影

| Environment | Info |
| --- | --- |
| antd | 5.15.0 |
| React | 18.2.0 |
| System | window10 |
| Browser | Google 125.0.6422.142 |

---
在onChange中使用了message提示才会出现这种情况

**Comment by wanpan11** [comment]
升级下 antd，5.18 版本中已修复此问题
