### ISSUE TITLE
[select-component][suffixIcon] 通过 suffixIcon 添加的 antd-icon CaretDownOutlined 无法触发 select 相关事件

### ISSUE THREAD

**Issue by LongHaoo** [ant-design/ant-design#49418]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-mpmnx6?file=%2Findex.js%3A19%2C10-19%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxehwn0r00063b6jfooq5cz2%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxehwn0r00023b6jh8bh6sbm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxehwn0r00033b6jfpyf5iwn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxehwn0r00053b6j7lzdiyqw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B41.08110049565405%252C58.91889950434595%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxehwn0r00023b6jh8bh6sbm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxehwn0r00013b6jmaqb1zxp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A16%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxehwn0r00023b6jh8bh6sbm%2522%252C%2522activeTabId%2522%253A%2522clxehwn0r00013b6jmaqb1zxp%2522%257D%252C%2522clxehwn0r00053b6j7lzdiyqw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxehwn0r00043b6juy7csedq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxehwn0r00053b6j7lzdiyqw%2522%252C%2522activeTabId%2522%253A%2522clxehwn0r00043b6juy7csedq%2522%257D%252C%2522clxehwn0r00033b6jfpyf5iwn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxehwn0r00033b6jfpyf5iwn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

suffixIcon 添加 CaretDownOutlined

### What is expected?

期望替换的 CaretDownOutlined 能触发 select 相关事件

### What is actually happening?

无法触发

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18 |
| System | macOS 14.2 |
| Browser | Chrome  |

---
ant-design icon 带有 className .antIcon 导致被选中，添加了属性 pointerEvents: 'auto', 可以触发点击事件，但是相关 tigger 绑定在 selector 上无法触发相关事件。

**Comment by afc163** [comment]
这是预期行为，因为不知道用户替换的 Icon 是否需要交互，见：https://github.com/ant-design/ant-design/issues/23263

如果不需要交互，可以给 suffixIcon 自行包裹 `pointerEvents: 'none'`。

```
suffixIcon={<CaretDownOutlined style={{ fontSize: '25px', pointerEvents: 'none' }} />}
```

**Comment by LongHaoo** [comment]
那理论上应该用户自定义的所有的子级元素都 设置 pointerEvents: 'auto' ，但是目前只是选中了 antd 的 Icon

**Comment by LongHaoo** [comment]
这样会不会更好呢，然后再 suffixIcon 文档中注明与默认 icon 相反的行为
```
'> *': {
     pointerEvents: 'auto',
},
```

**Comment by afc163** [comment]
我得看看预期逻辑是不是被改挂了：https://github.com/ant-design/ant-design/pull/23448/files

**Comment by afc163** [comment]
以文档描述为准：https://github.com/ant-design/ant-design/pull/42520/files
