### ISSUE TITLE
Table crashing when using render in column

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#49412]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/table-tooltip-ttcmdj?file=%2Fsrc%2FApp.js%3A20%2C9)

### Steps to reproduce

Hover on data in the address column

### What is expected?

Tooltip should appear

### What is actually happening?

App is crashing

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Firefox |

---
I have created a component "OverflowTooltip" which adds a tooltip in the table cell if its content is large as compared to the width of the cell. The same component was working fine in Antd v4.16 until I decided to upgrade my project to the latest version.

**Comment by zombieJ** [comment]
Your reproduce is private:
<img width="676" alt="截屏2024-06-14 14 39 25" src="https://github.com/ant-design/ant-design/assets/5378891/8e6d5032-d281-4572-b235-477cde07ea9e">

**Comment by piyushk96** [comment]
@zombieJ sandbox is accessible now

**Comment by stefann01** [comment]
@piyushk96 Why don't you use `mouseEnterDelay` prop of Tooltip?

**Comment by MadCcc** [comment]
You cannot use Component as `render`
