### ISSUE TITLE
Select 官网示例模糊搜索不正确

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#49415]
### Discussed in https://github.com/ant-design/ant-design/discussions/49411

<div type='discussions-op-text'>

<sup>Originally posted by **crazyair** June 14, 2024</sup>
https://ant-design.antgroup.com/components/select-cn#select-demo-search 这个示例，用了 `optionFilterProp="children"` 又用了 `filterOption` 导致必须在 `filterOption` 中使用 `toLowerCase` 对比，但是其实可以
```tsx
<Select showSearch optionFilterProp="label" /> 
```
就可以，因为默认搜索用了 `toUpperCase`  https://github.com/react-component/select/blob/66b66670c9cff5b44c75e2cb69da5599d74dd302/src/hooks/useFilterOptions.ts#L27</div>

**Comment by afc163** [comment]
这个例子主要演示 filterOption 的使用方式，删掉不妥。

**Comment by afc163** [comment]
但是 `optionFilterProp="children"` 和 options 也确实有点看不懂，可以改成一个更适合 filterOption 的演示案例。

**Comment by crazyair** [comment]
> 这个例子主要演示 filterOption 的使用方式，去掉不妥。

有2个了
