### ISSUE TITLE
Alert 的 afterClose 被触发多次

### ISSUE THREAD

**Issue by AIWWJ** [ant-design/ant-design#49436]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-76hgs6?file=%2Findex.js%3A28%2C46)

### Steps to reproduce

Alert 设置 closable，点击关闭按钮

### What is expected?

afterClose 只触发一次

### What is actually happening?

afterClose 触发多次

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18 |
| System | mac |
| Browser | chrome |

<img width="714" alt="WX20240616-152623@2x" src="https://github.com/ant-design/ant-design/assets/22759507/42b07bd4-4562-4d8d-b40a-90b63300c779">

**Comment by afc163** [comment]
<img width="727" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/ad04689e-5b33-4252-8232-74e3d7a00574">

**Comment by AIWWJ** [comment]
> <img alt="图片" width="727" src="https://private-user-images.githubusercontent.com/507615/340073291-ad04689e-5b33-4252-8232-74e3d7a00574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjU1NTksIm5iZiI6MTcxODUyNTI1OSwicGF0aCI6Ii81MDc2MTUvMzQwMDczMjkxLWFkMDQ2ODllLTViMzMtNDI1Mi04MjMyLTc0ZTNkN2EwMDU3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwODA3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGNjN2YzM2Y4ZDA1YjdjNDIxYThmMzgxNDZkZWI5ZmMwZGM3YjZhNTdjYmEyZGYxNTkxODgwODZkY2QzMDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.axFtJc8qH-9OKvyFAibwoY9122kTwly-QI6O9qafSz0">

retry again

**Comment by AIWWJ** [comment]
> <img alt="图片" width="727" src="https://private-user-images.githubusercontent.com/507615/340073291-ad04689e-5b33-4252-8232-74e3d7a00574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NDQ0MzIsIm5iZiI6MTcxODU0NDEzMiwicGF0aCI6Ii81MDc2MTUvMzQwMDczMjkxLWFkMDQ2ODllLTViMzMtNDI1Mi04MjMyLTc0ZTNkN2EwMDU3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQxMzIyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTY0NjA0YmY3YmVmYTY4ZDJjM2Q3NmZkMDM2MTRmOWY4MmY2ZTY1ZGQ3MzJjZTk4NGI4YzNmYTdkNGY4ZTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U4ZR41Fm-tqdXU2HlnGq6KS9U2Xo4puepgMWf8hAdk0">

再访问看看

**Comment by wanpan11** [comment]
Alert 的 afterClose 传递给了 onLeaveEnd 在卸载时会被多次调用，onLeaveEnd 会被 transitionEnd 事件多次调用 不知道是否符合预期 大佬看看 @afc163 

<img width="376" alt="image" src="https://github.com/ant-design/ant-design/assets/38714194/fc7a353e-1298-4d56-a48c-80dc26d66191">

**Comment by afc163** [comment]
不符合预期。
