### ISSUE TITLE
Bug when Table  is sticky

### ISSUE THREAD

**Issue by pruginkin** [ant-design/ant-design#49430]
https://github.com/ant-design/ant-design/assets/51276573/d3c2c55e-bd1f-4717-a530-bd3b4855f682

### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-pidax8?file=demo.tsx)

### Steps to reproduce

watch StackBlitz to understand what's going on

### What is expected?

Table responsive 

### What is actually happening?

Table not responsive

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18 |
| System | Linux  |
| Browser | Firefox 127 |

---
If comment  !!! sticky={{ offsetHeader: 10 }} !!! work as expected

**Comment by MadCcc** [comment]
https://stackblitz.com/edit/react-pidax8-qt5rpd?file=demo.tsx
Add `width: 0` to the flex component
