### ISSUE TITLE
Selet组件在form的校验失败情况下文字显示的问题错误

### ISSUE THREAD

**Issue by ChanHaiWei** [ant-design/ant-design#49442]
### Reproduction link

[https://ant-design.antgroup.com/components/form-cn](https://ant-design.antgroup.com/components/form-cn)

### Steps to reproduce

Ant Design 官网就能复现问题
1、找到form表单组件
2、表单方法调用项
3、点击Submit就能触发校验
4、然后校验失败，Select下拉选择框就提示了请输入字样

### What is expected?

Select下拉选择框校验失败应该是“请选择”而不是“请输入”

### What is actually happening?

Select下拉选择框校验失败显示的“请输入Gender”

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | 谷歌126.0.6478.61 |

**Comment by afc163** [comment]
这个是内建的通用校验文案，目前没办法根据组件类型做适配，如果对通用校验文案不满意，建议都使用 message 自定义。
