### ISSUE TITLE
Table组件布局异常

### ISSUE THREAD

**Issue by skordyr** [ant-design/ant-design#4945]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: win10
- Browser and its version: 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

Table组件的pagination使用了float没有清除浮动，导致后面的Dom布局异常

#### Re-producible online demo
http://codepen.io/skordyr/pen/vgqZdX?editors=001

**Comment by benjycui** [comment]
Yep, and you can fix this by:

```diff
  <Table
+   className="clearfix"
```
