### ISSUE TITLE
文档无法访问

### ISSUE THREAD

**Issue by overdev-l** [ant-design/ant-design#49457]
### Reproduction link

[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce

直接打开地址

### What is expected?

显示文档

### What is actually happening?

白屏，控制台有错误信息

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac sonoma 14.5 |
| Browser | chrome 125.0.6422.176 |

---
Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by overdev-l** [comment]
禁用缓存也无法访问，使用无痕模式可以访问

**Comment by yoyo837** [comment]
无法复现

**Comment by MadCcc** [comment]
> 使用无痕模式可以访问

优先排查是否浏览器插件导致

**Comment by MadCcc** [comment]
最新版官网更新到了 dumi 2.4，SSR 逻辑有变化，任何会改变 dom 结构的插件都有可能导致水合失败。请先禁用这些插件（如有道翻译等）
