### ISSUE TITLE
DatePicker embedded in Dropdown menu closes when dropdown closes

### ISSUE THREAD

**Issue by devabhishekpal** [ant-design/ant-design#49458]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/dropdown-bug-repro-yly59z?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxjup1c100063b6mtvbtvaog%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxjup1c100023b6m0ngzhvws%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxjup1c100033b6mu3xthj8d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxjup1c100053b6mtxb9sufz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxjup1c100023b6m0ngzhvws%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxjup1c100013b6mukcy2eaa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A28%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A58%252C%2522endColumn%2522%253A70%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxjup1c100023b6m0ngzhvws%2522%252C%2522activeTabId%2522%253A%2522clxjup1c100013b6mukcy2eaa%2522%257D%252C%2522clxjup1c100053b6mtxb9sufz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxjup1c100043b6mr8ozpbqt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxjup1c100053b6mtxb9sufz%2522%252C%2522activeTabId%2522%253A%2522clxjup1c100043b6mr8ozpbqt%2522%257D%252C%2522clxjup1c100033b6mu3xthj8d%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxjup1c100033b6mu3xthj8d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Create a DatePicker component as a menu item for DropDown component.
DatePicker will close as soon as we click on the select date option as the dropdown menu closes on changing context

### What is expected?

The DatePicker panel should be open even when the Dropdown menu closes.

### What is actually happening?

The DatePicker panel closes when the Dropdown menu closes

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 16.8.6 |
| System | MacOS, Windows |
| Browser | Chrome Version 126.0.6478.57, Firefox Version 126 |

---
This could be related to another issue of DatePicker auto-closing when embedded in a Select component.
Reference: https://github.com/ant-design/ant-design/issues/17516

**Comment by Roxannej** [comment]
现在Dropdown的关闭应该是只要在鼠标点击组件外部就触发了

**Comment by devabhishekpal** [comment]
Hi @Roxannej, thanks for the quick reply.
The problem with trying to close on click outside menu is that there isn't a straightforward way.
We need to maintain extra states, and also onBlur argument causes different issues depending on which component we are adding it to.
Best case scenario we have a calendar panel which doesn't close even when we are clicking outside the panel
Worst case we are having the same panel auto closing on focus change/blur.

**Comment by devabhishekpal** [comment]
Found a workaround for this.
It seems if we are passing stopPropagation on DatePicker onClick handler, it is working properly.
```
<DatePicker
    format="YYYY-MM-DD"
    onClick={(e) => {e.stopPropagation()}}
    placement="topRight" />
```

**Comment by MadCcc** [comment]
`stopPropagation` is right.
