### ISSUE TITLE
Adding title Design Token to Table Component

### ISSUE THREAD

**Issue by achom4nu** [ant-design/ant-design#49466]
### What problem does this feature solve?

This would ease the styling of ant-table-title without needing to overwrite on an independent stylesheet.

### What does the proposed API look like?

textColor -> Color of the title text
textBg -> Background color of the title
...
Basically a number of properties that exist in other components but applied to table's titles

**Comment by zombieJ** [comment]
What's the usage code look like?

**Comment by achom4nu** [comment]
On the component token 
![image](https://github.com/ant-design/ant-design/assets/123540762/c48f0329-def1-40e0-9062-c1b0c107c8a6)

Because right now I don't have any antd tool to manage table title's styles
![image](https://github.com/ant-design/ant-design/assets/123540762/7cceefeb-f5ed-4d9d-9c7a-2bba1fdcacc5)

**Comment by MadCcc** [comment]
Should provide semantic className for table

**Comment by achom4nu** [comment]
Isn't `ant-table-title` the className for table title?

**Comment by aojunhao123** [comment]
I'd love to contribute to this issue by implementing the design tokens for the Table component title. Could someone provide guidance on where to start or if there are specific requirements for the implementation?

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/49782
