### ISSUE TITLE
5.18.2 版本，表格列排序 icon 激活态有问题

### ISSUE THREAD

**Issue by AnaniZhu** [ant-design/ant-design#49467]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-4q7jhq?file=%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwj4hrfl00063b6hywpp0kqe%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwj4hrfk00023b6h7vs6qpu5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwj4hrfk00033b6hstrj6md1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwj4hrfk00053b6h2iosg7xf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwj4hrfk00023b6h7vs6qpu5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwj4hrfk00013b6h88pmxa2n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A21%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwj4hrfk00023b6h7vs6qpu5%2522%252C%2522activeTabId%2522%253A%2522clwj4hrfk00013b6h88pmxa2n%2522%257D%252C%2522clwj4hrfk00053b6h2iosg7xf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwj4hrfk00043b6hjtlbuos5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwj4hrfk00053b6h2iosg7xf%2522%252C%2522activeTabId%2522%253A%2522clwj4hrfk00043b6hjtlbuos5%2522%257D%252C%2522clwj4hrfk00033b6hstrj6md1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwj4hrfk00033b6hstrj6md1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

点击 `Name` 列的排序 icon，触发重新查询

### What is expected?

排序 icon 应该被激活

### What is actually happening?

实际上未被激活

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 18.2 |
| System | mac |
| Browser | chrome |

---
将 columns 定义在函数组件外面，保持引用地址不变的话，就不会有此 bug。

**Comment by crazyair** [comment]
![image](https://github.com/ant-design/ant-design/assets/7971419/9fd165ca-559e-4afe-9efa-9d55fb937643)

**Comment by AnaniZhu** [comment]
> ![image](https://private-user-images.githubusercontent.com/7971419/340624164-9fd165ca-559e-4afe-9efa-9d55fb937643.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDM2ODksIm5iZiI6MTcxODcwMzM4OSwicGF0aCI6Ii83OTcxNDE5LzM0MDYyNDE2NC05ZmQxNjVjYS01NTllLTRhZmUtOWVmYS05ZDU1ZmI5Mzc2NDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDkzNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQzY2YyZDE5M2IyYzYxY2M4ODMxNjE3ODVlYTk0MDZkODg3NjlkYjk5YzE5YjI2ZjRlN2Q0Njg0OTdlNjg3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9iSrGBNXb36olvsVs7gpo1QjQs9yuPD0GuTJ6F6RJiA)

权限问题，我重新配置了下

**Comment by AnaniZhu** [comment]
> codesendbox 已经从 antd 移除了，怎么还能用这个？

我创建 issue 时，让我提供复现 demo，我点进去就是 codesandbox
