### ISSUE TITLE
[antd4.x][Pagination] itemRender，page>3 return null 时，分页按钮还在，只是具体数字空白

### ISSUE THREAD

**Issue by lk0606** [ant-design/ant-design#49469]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/shang-yi-bu-he-xia-yi-bu-antd-4-24-16-forked-pf8qph?file=%2Fdemo.tsx%3A5%2C35)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/43233310/d0504903-8c9b-49f4-8dd5-47046a334551)

以上链接可以直接复现

### What is expected?

期望，return null false 等节点时，不渲染整个页码按钮，和antd5一样

### What is actually happening?

分页按钮还在，只是具体数字空白

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 16-18均无差别 |
| System | 无关系统版本 |
| Browser | 无关浏览器 |

**Comment by afc163** [comment]
4.x 已于不进行支持维护了（[📢 v4 维护周期截止](https://ant.design/docs/blog/v4-ood-cn)），建议升级到 5.x。

**Comment by lk0606** [comment]
> 4.x 已于不进行支持维护了（[📢 v4 维护周期截止](https://ant.design/docs/blog/v4-ood-cn)），建议升级到 5.x。

我看了源码，锁定5.x的rc-pagination的版本4.0.4就可以解决
