### ISSUE TITLE
【Collapse】icon 和 header 部分没有水平对齐

### ISSUE THREAD

**Issue by wanpan11** [ant-design/ant-design#49474]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-b9mjyk-7yddwu?file=demo.tsx)

### Steps to reproduce

<img width="625" alt="image" src="https://github.com/ant-design/ant-design/assets/38714194/586acd52-e9ba-4b01-969d-de9f38931d70">

### What is expected?

折叠 icon 可以和默认水平 header 对齐

### What is actually happening?

折叠 icon 和 header 没有默认水平对齐

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 18.2.0 |
| System | mac os |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/49486#issuecomment-2177468619
