### ISSUE TITLE
Alert closable时的关闭动画结束的时候有点卡顿

### ISSUE THREAD

**Issue by AIWWJ** [ant-design/ant-design#49477]
### Reproduction link

[https://ant-design.antgroup.com/components/alert-cn#components-alert-demo-closable](https://ant-design.antgroup.com/components/alert-cn#components-alert-demo-closable)

### Steps to reproduce

点击上述官方demo（第一或者第二个会比较明显）里面的关闭按钮，结束的时候感觉有点卡顿，4.24.12版本目测没那么明显https://4x-ant-design.antgroup.com/components/alert-cn/

### What is expected?

关闭动画流畅一些

### What is actually happening?

有点卡顿

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by wanpan11** [comment]
是这个 demo 的问题，Space 组件会带有间距，Alert 组件卸载后 那一块的间距没有了 导致了最后拿一下的收缩

![image](https://github.com/ant-design/ant-design/assets/38714194/a9e9a502-4423-428d-b94a-d91df63730af)

**Comment by fyw24373** [comment]
alert组件有内边距，动画结束后上下内边距造成高度残留，修改样式，把alert的上下内边距改为0，把边距加到内容的margin里，就可以了
