### ISSUE TITLE
5.18.2修改useSorter后导致: 更新表格列后，排序失效

### ISSUE THREAD

**Issue by 3764446961** [ant-design/ant-design#49482]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wythmx?file=demo.tsx,package.json)

### Steps to reproduce

https://stackblitz.com/edit/react-wythmx?file=demo.tsx,package.json

### What is expected?

更新columns，排序仍存在

### What is actually happening?

更新columns，排序丢失

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0.0 |
| System | mac |
| Browser | chrome |

**Comment by 3764446961** [comment]
复现地址
5.18.1 点击更新按钮，排序仍存在（正确）：https://stackblitz.com/edit/react-wythmx?file=demo.tsx,package.json
5.18.2 点击更新按钮，排序丢失（错误）： https://stackblitz.com/edit/react-2vtqbz-g4rzdy?file=demo.tsx,package.json

**Comment by 3764446961** [comment]
> 复现地址 5.18.1 点击更新按钮，排序仍存在（正确）：https://stackblitz.com/edit/react-wythmx?file=demo.tsx,package.json 5.18.2 点击更新按钮，排序丢失（错误）： https://stackblitz.com/edit/react-2vtqbz-g4rzdy?file=demo.tsx,package.json

5.18.2 更新内容：https://github.com/ant-design/ant-design/pull/49289/files#diff-33a34c8ef463c5e1cad14a8046c87aa47265d4927644753c226a65211511dc41

**Comment by afc163** [comment]
我没有重现出你提到的问题。

**Comment by 3764446961** [comment]
5.18.2

<img width="1109" alt="image" src="https://github.com/ant-design/ant-design/assets/168057074/07fac2b2-5462-4cae-aa55-b0d69c256258">
<img width="1118" alt="image" src="https://github.com/ant-design/ant-design/assets/168057074/32b23393-2dae-44b3-a974-eef83547d2ac">

**Comment by 3764446961** [comment]
5.18.1

<img width="1121" alt="image" src="https://github.com/ant-design/ant-design/assets/168057074/44d88e52-c7e3-485e-ba25-d2d2f213a7ca">
<img width="1103" alt="image" src="https://github.com/ant-design/ant-design/assets/168057074/fa094497-1330-432e-931e-e9cbc9843e43">

**Comment by afc163** [comment]
你看下我这个 5.18.2 的例子？ https://stackblitz.com/edit/react-wythmx-dccyu7?file=demo.tsx,package.json

我操作的 gif 如下，好像没发现你截图里的问题，我是不是有哪里操作错了？

![Jun-19-2024 19-22-04](https://github.com/ant-design/ant-design/assets/507615/ae3fe2fe-332f-40e0-a373-58d3e29cbe1b)

**Comment by afc163** [comment]
>  5.18.2 点击更新按钮，排序失效（错误）： https://stackblitz.com/edit/react-2vtqbz-g4rzdy?file=demo.tsx,package.json

你给的这个链接，我操作的 gif 如下，同样没发现问题：

![Jun-19-2024 19-24-52](https://github.com/ant-design/ant-design/assets/507615/4a2a78bf-eda1-4550-ba33-73e1cb35e20c)

**Comment by afc163** [comment]
哦，我知道了，是我理解错了操作步骤。正确的重现步骤是：

1. 先点击 math 这一列使其进入排序状态，排序图标变成蓝色
2. 再点击更新，此时观察排序图标

预期：排序状态的蓝色还在
4.18.2 实际：排序状态丢失

---

这个问题已经在 4.18.3 里修复了，欢迎升级测试：https://stackblitz.com/edit/react-wythmx-gus1dk?file=demo.tsx,package.json
