### ISSUE TITLE
Pagination组件使用simple参数时showQuickJumper默认false效果失效

### ISSUE THREAD

**Issue by Hyacinth-FE** [ant-design/ant-design#49499]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-mkmrty?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxlgrua70006356i39js8xwu%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxlgrua70002356id0z9mulm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxlgrua70003356ix26k7k25%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxlgrua70005356ift1tzhp9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxlgrua70002356id0z9mulm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlgrua60001356ii797y4za%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxlgrua70002356id0z9mulm%2522%252C%2522activeTabId%2522%253A%2522clxlgrua60001356ii797y4za%2522%257D%252C%2522clxlgrua70005356ift1tzhp9%2522%253A%257B%2522id%2522%253A%2522clxlgrua70005356ift1tzhp9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxlgrua70004356iktv13ac9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxlgrua70004356iktv13ac9%2522%257D%252C%2522clxlgrua70003356ix26k7k25%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxlgrua70003356ix26k7k25%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

      <Pagination
        simple
        defaultCurrent={1}
        total={50}
        hideOnSinglePage
        defaultPageSize={5}
        size="small"
      />

### What is expected?

simple属性下快捷跳转可以自定义调控

### What is actually happening?

快捷跳转在simple属性下始终存在

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2.0 |
| System | 版本:Windows 11 家庭中文版 版本号:23H2 |
| Browser | chrome 125.0.6422.176（正式版本） （64 位） |

**Comment by wanpan11** [comment]
是不想要这个吗

![image](https://github.com/ant-design/ant-design/assets/38714194/fd3665ae-b4cb-46b3-b4fb-d76281ac40bf)

----

这个才是快捷跳转吧

![image](https://github.com/ant-design/ant-design/assets/38714194/c3a8d548-3f9c-404f-bceb-cdfb9ef75791)

**Comment by coding-ice** [comment]
应该就是加个属性在控制下`input` ，让它成为不可输入的，是这个意思不
<img width="170" alt="image" src="https://github.com/ant-design/ant-design/assets/49827327/b03558e3-57f7-45e0-b89b-d85c3bec6524">

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/49562
