### ISSUE TITLE
datePicker 周 类型组件的展示问题

### ISSUE THREAD

**Issue by yuqiang1999** [ant-design/ant-design#49504]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn](https://ant-design.antgroup.com/components/date-picker-cn)

### Steps to reproduce

官方 demo 即可复现 

### What is expected?

去除多余的列

### What is actually happening?
![image](https://github.com/ant-design/ant-design/assets/55423664/f409a057-5801-48c4-95f1-d41d7ef9896a)

展示了多余的列 导致用户无法理解

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18 |
| System | mac |
| Browser | chrome 125.0.6422.144 |

**Comment by afc163** [comment]
这不是多余的列，这是第几周。
