### ISSUE TITLE
v4升级到v5时如果项目中引用了v4 less文件中变量只能手动处理吗？

### ISSUE THREAD

**Issue by jiang-zhong-xi** [ant-design/ant-design#49503]
### What problem does this feature solve?

v4到v5升级
例如下图
![image](https://github.com/ant-design/ant-design/assets/59865643/c321a3e8-415f-4066-9501-a175e4beeba3)

### What does the proposed API look like?

@ant-design/codemod-v5工具能自动解决这个问题

**Comment by huangkairan** [comment]
https://ant-design.antgroup.com/docs/react/migration-v5-cn#less-%E8%BF%81%E7%A7%BB

**Comment by afc163** [comment]
目前只能手动处理，欢迎给 @ant-design/codemod-v5 提交 PR 来处理这个问题。
