### ISSUE TITLE
Calendar opens several time if there is no need to confirm

### ISSUE THREAD

**Issue by MaruBlare** [ant-design/ant-design#49512]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sdlk3f)

### Steps to reproduce

1. Set needFonfirm to false for the range picker
2. Select both dates
3. Lose focus on input

### What is expected?

Both dates are set, and the calendar is closed.

### What is actually happening?

Calendar opens after closing.

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.2.0 |
| System | mac |
| Browser | Yandex |

---
I want to set dates without confirmation.
However, I faced a problem where the calendar shows up again after closing.
https://github.com/ant-design/ant-design/assets/29026396/e1bb3b2d-402c-419c-af79-3ec47604d4b4

Is it possible to use the "needConfirm" prop when it's a range picker?

**Comment by afc163** [comment]
<img width="876" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/5ddca941-5398-4f3b-8fe4-d9ea5e4b743f">

**Comment by MaruBlare** [comment]
Sorry, it was private
[Here](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-sdlk3f) it is again
