### ISSUE TITLE
希望支持全局配置形态变体（variant）

### ISSUE THREAD

**Issue by skytt** [ant-design/ant-design#49514]
### What problem does this feature solve?

形态变体的样式解决了项目风格上的问题，很 nice；
但是当前设置 `variant` 的方式只能通过每个组件设置，或通过 Form 提供的 variant API 注入。对于项目而言，有非常多的页面会用到 Form 组件，且后续新搭建页面的时候也要留意 Form 是否添加了这个变量来保证样式统一，增加 Coding 的记忆负担。

类似请求：
* https://github.com/ant-design/ant-design/issues/47842
* https://github.com/ant-design/ant-design/issues/49040

### What does the proposed API look like?

因此，希望：
* 提供一个 ConfigProvider 配置 variant 的方式（最好，因为不是所有控件都在 Form 下）
* 或 Form 提供一个 variant 的 ConfigProvider 配置

感谢！

**Comment by MadCcc** [comment]
```
<ConfigProvider input={{ variant: 'filled' }} form={{ variant: 'filled' }}>
```

这样是否足够呢，每个支持 `variant` 的组件都可以在 ConfigProvider 上配置

**Comment by skytt** [comment]
> ```
> <ConfigProvider input={{ variant: 'filled' }} form={{ variant: 'filled' }}>
> ```
> 
> 这样是否足够呢，每个支持 `variant` 的组件都可以在 ConfigProvider 上配置

能这样修改就太好了！
还有个担心，如果以后有新的组件支持了变体，还得往 ConfigProvider 上暴露一下这个配置能力才能支持全局配置，可能不一定注意得到；variant 有可能只在 provider 的一个属性里集中配置么，有点类似 theme dark 的感觉（不过 dark 是样式层面，可能有点不一样）

**Comment by MadCcc** [comment]
```
<ConfigProvider variant="filled">
```
一起支持看起来好点

**Comment by zybzzc** [comment]
filled variant 在 inline form 中将 label 放到控件框中作为前缀要更好看一点，那么是否能让所有的输入框类样式的输入组件都支持 prefix 呢？同时 Form 和 Form.Item 也支持配置 label 的位置

**Comment by skytt** [comment]
> ```
> <ConfigProvider variant="filled">
> ```
> 
> 一起支持看起来好点

这样很方便

**Comment by skytt** [comment]
> filled variant 在 inline form 中将 label 放到控件框中作为前缀要更好看一点，那么是否能让所有的输入框类样式的输入组件都支持 prefix 呢？同时 Form 和 Form.Item 也支持配置 label 的位置

感觉这是另一个话题，类似 material UI 那种么
