### ISSUE TITLE
Image自定义预览内容后工具栏不起作用

### ISSUE THREAD

**Issue by Sayi** [ant-design/ant-design#49516]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-tt63dd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxmmwgd000063b6j188urxyk%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxmmwgd000023b6jzrcxmlh6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxmmwgd000033b6j3sibz7oc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxmmwgd000053b6jxqdza8av%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxmmwgd000023b6jzrcxmlh6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxmmwgd000013b6jg13zpp1u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxmmwgd000023b6jzrcxmlh6%2522%252C%2522activeTabId%2522%253A%2522clxmmwgd000013b6jg13zpp1u%2522%257D%252C%2522clxmmwgd000053b6jxqdza8av%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxmmwgd000043b6j8of0sfbu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxmmwgd000053b6jxqdza8av%2522%252C%2522activeTabId%2522%253A%2522clxmmwgd000043b6j8of0sfbu%2522%257D%252C%2522clxmmwgd000033b6j3sibz7oc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxmmwgd000033b6j3sibz7oc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

- 拷贝官方Image自定义工具栏和预览内容的示例代码
- 自定义imageRender

```js
imageRender: (originalNode, info) => {
        return (
          <img
            src={
              "https://gw.alipayobjects.com/zos/antfincdn/cV16ZqzMjW/photo-1473091540282-9b846e7965e3.webp"
            }
          />
        );
      },
```

### What is expected?

工具栏工具可以正确获取图片引用，可以进行旋转等操作

### What is actually happening?

工具栏的按钮无法操作，**rc-image的方法onRotateLeft等无法获取imgRef对象进行操作**

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18  |
| System | mac14  |
| Browser | chrome125  |

**Comment by wanpan11** [comment]
升级下 文档忘更新了

![image](https://github.com/ant-design/ant-design/assets/38714194/3867c195-5d81-44fb-8883-28ea2858e1dd)

**Comment by zombieJ** [comment]
imageRef 里的 `originNode` 有 `ref` 但是叫 `imgRef`  要拿过来用感觉不够直觉，可以考虑在 `imageRender` 的 `info` 里把 ref 透出来。

**Comment by Sayi** [comment]
> 升级下 文档忘更新了
> 
> ## ![image](https://private-user-images.githubusercontent.com/38714194/341249694-3867c195-5d81-44fb-8883-28ea2858e1dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTI1ODQsIm5iZiI6MTcxODg1MjI4NCwicGF0aCI6Ii8zODcxNDE5NC8zNDEyNDk2OTQtMzg2N2MxOTUtNWQ4MS00NGZiLTg4ODMtMjhlYTI4NThlMWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAyNTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDI0ZTdkOTIzZWIxZTFjYTczNjliNjRmNzdhNDQ5OWY4YjIzY2Y3NTEwOGIzMzVhMWU2NDY5MGMzMTE5ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sJvIO-4QUIwMDBwyOAdN5f39RCUWDpiLEoy9-Vlk2l4)
> ![image](https://private-user-images.githubusercontent.com/38714194/341250003-71161721-6635-4f3e-b51c-221783dbc22b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTI1ODQsIm5iZiI6MTcxODg1MjI4NCwicGF0aCI6Ii8zODcxNDE5NC8zNDEyNTAwMDMtNzExNjE3MjEtNjYzNS00ZjNlLWI1MWMtMjIxNzgzZGJjMjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAyNTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNGJiYzNkYTg1MjU2ODgyNzc0ZjgzMDlkYTQyNGRlYzY1ZTI5ZTYwZjRjZjJjYWJjM2ViYTJjMjMwNTZiMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pqKhHoHnLzmM08gaMgpuS0Jq1Nt5Sp2GVidhEP7t59A)

这个不行啊，我是相册模式，在`Image.PreviewGroup`里面自定义的函数。

**Comment by Sayi** [comment]
> imageRef 里的 `originNode` 有 `ref` 但是叫 `imgRef` 要拿过来用感觉不够直觉，可以考虑在 `imageRender` 的 `info` 里把 ref 透出来。

哈喽，可以给个目前能用的写法示例吗？🙏

**Comment by linxianxi** [comment]
cloneElement 即可 https://github.com/ant-design/ant-design/issues/43857

**Comment by Sayi** [comment]
@linxianxi 这个cloneElement复制了一份原来的对象，我并不希望用原来的对象，imageRender里面我的场景会只放一个<svg></svg>标签。

按照我的理解，rc-image工具栏的操作是对**某个element**进行style样式transform等变换，不知道有没有办法能**指定这个element**。

**Comment by Sayi** [comment]
我们可以在这里把imgRef透传出来吗，就像透传imageInfo那样？

```js
<div className={`${prefixCls}-img-wrapper`}>
          {imageRender
            ? imageRender(imgNode, { transform, image, ...(groupContext ? { current } : {}) })
            : imgNode}
        </div>
```

然后在imageRender里面就像这样去写：
```js
<img
      ref={ref => {
        imgRef.current = ref;
        getImgRef(ref);
      }}
      {...props}
      {...srcAndOnload}
    />
```

PS: 我是一个后端，问的问题可能比较低级，见谅。

**Comment by linxianxi** [comment]
不止 imgRef，还有其它属性和事件的。你的 svg 用 src 的方式使用吧，cloneElement(originalNode, { src: 'svg 的 src' })

**Comment by wanpan11** [comment]
> 可以考虑在 imageRender 的 info 里把 ref 透出来

新增个这个 应该就行了

**Comment by Sayi** [comment]
svg用src的方式引用会有很多限制，比如svg里面引用的图片、字体都不会显示，所以svg要用标签方式使用。

**Comment by wanpan11** [comment]
> 可以考虑在 imageRender 的 info 里把 ref 透出来

这个不行，所有的事件都在 originNode 上，imgRef 传出来也没啥用。不用 originNode 相对于说有的操作都要自己手动了，要改的话就是 breake change=。=

```
export default function Base() {
  const imgRef = React.useRef<HTMLImageElement>(null);

  return (
    <Image
      src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
      preview={{
        imageRender: (_, { transform: { flipY } }) => (
          <img
            ref={imgRef}
            style={{ transform: `rotateY(${flipY ? '180deg' : '0'})` }}
            // onWheel={} 鼠标事件都需要自己实现
            src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
          />
        ),
        toolbarRender: (_, { actions: { onFlipY } }) => (
          <SwapOutlined rotate={90} onClick={onFlipY} />
        ),
      }}
    />
  );
}
```


![image](https://github.com/ant-design/ant-design/assets/38714194/ef476177-2d61-436e-9918-4ad82fadbf0c)

**Comment by Sayi** [comment]
@wanpan11  Great Job! 🫰
