### ISSUE TITLE
Expansion items cannot be scrolled after table columns are fixed. 表格列固定后，扩展项无法滚动

### ISSUE THREAD

**Issue by ApeWhoLovesCode** [ant-design/ant-design#49518]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-table-expandable-svcgj5?file=%2Fsrc%2FApp.tsx%3A8%2C21)

### Steps to reproduce

为 columns 的某项添加 fixed: 'left' 后，expandable 的扩展项无法跟随列表一起滚动

### What is expected?

期望扩展项能跟随列表一起滚动。

### What is actually happening?

扩展项无法跟随列表一起滚动

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

---
我们这边的需求是：扩展项的是子订单的内容，所以子订单和父订单是一一对齐的，当添加 fixed 后，展开的子订单就无法滚动了。

**Comment by afc163** [comment]
```
      <Table
        columns={columns}
        dataSource={orderList}
        rowKey="id"
        scroll={{ x: true }}
        pagination={false}
        childrenColumnName="childOrders"
      />
```

这样是不是就行了，你这个更像是树形表格，而非扩展行。

**Comment by ApeWhoLovesCode** [comment]
> ```diff
>       <Table
>         columns={columns}
>         dataSource={orderList}
>         rowKey="id"
>         scroll={{ x: true }}
>         pagination={false}
> +       childrenColumnName="childOrders"
>       />
> ```
> 
> 这样是不是就行了，你这个更像是树形表格，而非扩展行。

感谢这样应该可以满足需求，我额外处理一下或许就满足需求了。还是对组件库属性不够熟悉😭
