### ISSUE TITLE
Table 用了scroll的属性后 不加fixed属性 表格头和内容对不齐

### ISSUE THREAD

**Issue by changyijie** [ant-design/ant-design#4951]
#### Environment(required)

- antd version:2.7.2
- OS and its version:
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.
Table 用了scroll的属性后 不加fixed属性 表格头和内容对不齐
![image](https://cloud.githubusercontent.com/assets/22167211/23111942/1a82de06-f767-11e6-9c53-c021772e3383.png)
这是代码
![image](https://cloud.githubusercontent.com/assets/22167211/23111952/29693262-f767-11e6-8102-dff2b3e5ebd2.png)

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/86981114a7a594dae883b11a090c3eddc14942b4

**Comment by afc163** [comment]
Yes, it was fixed in https://github.com/ant-design/ant-design/commit/86981114a7a594dae883b11a090c3eddc14942b4
