### ISSUE TITLE
官网 breadcrumb 部分demo加载失败 bug

### ISSUE THREAD

**Issue by moon548834** [ant-design/ant-design#49524]
### Reproduction link

[https://ant.design/components/breadcrumb-cn?tab=design](https://ant.design/components/breadcrumb-cn?tab=design)

### Steps to reproduce

访问 https://ant.design/components/breadcrumb-cn?tab=design
切换到设计tab

### What is expected?

正常的demo

### What is actually happening?
![截屏2024-06-20 15 33 04](https://github.com/ant-design/ant-design/assets/31240060/533edae0-d4a8-4d76-8f10-681d5bb9b1d0)

```
ChunkLoadError
    at es.chunkEnsures.jsonp (runtime_entry.js:97:25)
    at runtime_entry.js:70:42
    at Array.reduce (<anonymous>)
    at es.ensure (runtime_entry.js:66:49)
    at index.$tab-design.zh-CN.md:5:38
    at eZ (react.production.min.js:18:161)
    at eN (react-dom.production.min.js:290:296)
    at sG (react-dom.production.min.js:279:389)
    at sQ (react-dom.production.min.js:279:362)
    at sE (react-dom.production.min.js:267:300)
```

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18 |
| System | mac os 13.3.1 |
| Browser | edge 126.0.2592.56 |

---
这不是一个关于antd的bug，而是一个关于antd官网的bug

**Comment by simplecode101** [comment]
![image](https://github.com/ant-design/ant-design/assets/143469354/80295e6c-938d-4a84-a35a-f044d8c1c439)
官网根本打不开，糟心。。。

**Comment by afc163** [comment]
@simplecode101 关掉这个插件 https://chromewebstore.google.com/detail/microsoft-%E7%BC%96%E8%BE%91%E5%99%A8%E6%8B%BC%E5%86%99%E5%92%8C%E8%AF%AD%E6%B3%95%E6%A3%80%E6%9F%A5%E5%99%A8/gpaiobkfhnonedkhhfjpmhdalgeoebfa?hl=zh-CN

**Comment by simplecode101** [comment]
> @simplecode101 关掉这个插件 https://chromewebstore.google.com/detail/microsoft-%E7%BC%96%E8%BE%91%E5%99%A8%E6%8B%BC%E5%86%99%E5%92%8C%E8%AF%AD%E6%B3%95%E6%A3%80%E6%9F%A5%E5%99%A8/gpaiobkfhnonedkhhfjpmhdalgeoebfa?hl=zh-CN

没有这个插件哦

**Comment by simplecode101** [comment]
> @simplecode101 关掉这个插件 https://chromewebstore.google.com/detail/microsoft-%E7%BC%96%E8%BE%91%E5%99%A8%E6%8B%BC%E5%86%99%E5%92%8C%E8%AF%AD%E6%B3%95%E6%A3%80%E6%9F%A5%E5%99%A8/gpaiobkfhnonedkhhfjpmhdalgeoebfa?hl=zh-CN

可以了，是我的darkreader的插件问题

**Comment by LearnShare** [comment]
> @simplecode101 关掉这个插件 https://chromewebstore.google.com/detail/microsoft-%E7%BC%96%E8%BE%91%E5%99%A8%E6%8B%BC%E5%86%99%E5%92%8C%E8%AF%AD%E6%B3%95%E6%A3%80%E6%9F%A5%E5%99%A8/gpaiobkfhnonedkhhfjpmhdalgeoebfa?hl=zh-CN

[uBlock Origin](https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) 同样会导致 <https://ant.design/> 页面崩溃

**Comment by scris** [comment]
dark reader 是一个市场占有率很高的插件，是否应该考虑进行重新适配？用户可能会认为是网站自身的问题

**Comment by afc163** [comment]
@scris 我们尽快想办法解决

**Comment by afc163** [comment]
目前问题已经修复，暂时回滚了 dumi 版本：https://github.com/ant-design/ant-design/pull/49550
