### ISSUE TITLE
Three way switch or switches with dynamic number of values

### ISSUE THREAD

**Issue by emirozmen07** [ant-design/ant-design#49529]
### What problem does this feature solve?

Currently we have a switch that we can only off and on, but a three way switch can do more complex operations in a compact way. Also, we could make it dynamic so devs can set it to whatever number of states they need

### What does the proposed API look like?

There can be prop named `possibleValues:SwitchValue[]` Which devs can set values. According to their orders, these values will be set to the selection.
```
interface SwitchValue {
    label:string,
    value:any
}
possibleValues={[{label: "Empty", value : 0}, {label: "Half Full", value : 0.5}, {label: "Full", value : 1}]}
```

**Comment by smallbonelu** [comment]
I think he wants a switch has a function like this:
<img width="177" alt="image" src="https://github.com/ant-design/ant-design/assets/15611493/d34a5752-854d-41f1-8610-ffffdd703176">

**Comment by afc163** [comment]
You need https://ant.design/components/segmented
