### ISSUE TITLE
Problem with hiding options and showing `notFoundContent` in Select "tags" mode

### ISSUE THREAD

**Issue by ssoft-auky** [ant-design/ant-design#49537]
### What problem does this feature solve?

In Select "tags" mode, we would like to hide already selected options, and also show `notFoundContent prop` when all options are selected. But we also need the ability to add new option from "tags" mode, which "multiple" mode does not provide.

We have tried the filter option method as shown in this [official demo](https://ant.design/components/select#select-demo-hide-selected), but apparently it only works for "multiple" mode.
We have also tried "hiding selected options with css" method mentioned from below issue, but this ended up showing a blank dropdown after selecting all options, and we would like to show `notFoundContent` instead.

Similar issues found:
- https://github.com/ant-design/ant-design/issues/29135
- https://github.com/ant-design/ant-design/discussions/46422?sort=new

### What does the proposed API look like?

Currently could only think of adding support for filtered `options` to properly reflect in "tags" mode.
Or is there any viable way to achieve this?

Thanks for the effort!

**Comment by ssoft-auky** [comment]
Figured out that we could use `dropdownRender` to achieve the desired result.
Another way we thought off but didn't try is to use `Select.Option` to render conditionally.
Nevertheless, would be glad if "tags" mode can reflect the filtered options as well.

**Comment by Masadow** [comment]
@ssoft-auky How did you manage to do it with `dropdownRender` props as it doesn't accept `null` ?
