### ISSUE TITLE
[Input]chrome浏览器上微软中文输入法输入123,4会自动变成123,44被多加了一位（可能是对value格式化引起的）

### ISSUE THREAD

**Issue by huangwei9527** [ant-design/ant-design#49538]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jsuksz-rrhggn?file=demo.tsx)

### Steps to reproduce

如链接代码，删掉所有输入法保留微软输入法，切换到中文输入框输入数字1234
![录屏](https://github.com/ant-design/ant-design/assets/18244110/4ea08f01-a9a6-4cf2-9c02-c56108484c46)

去掉对value的格式化就没问题，有什么解决办法

### What is expected?

正确显示格式化之后的123,4

### What is actually happening?

实际显示123,44

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | React |
| System | win11 |
| Browser | chrome 125 |

**Comment by afc163** [comment]
试试原生组件有没有一样的问题。
