### ISSUE TITLE
使用谷歌浏览器的插件DARK READER的暗黑模式，ant-design的网站会报错打不开

### ISSUE THREAD

**Issue by Roxannej** [ant-design/ant-design#49544]
![截屏2024-06-21 下午6 15 05](https://github.com/ant-design/ant-design/assets/52034179/d1dec393-7ff2-4de8-98dd-592726bbb1e2)
<img width="317" alt="截屏2024-06-21 下午6 20 04" src="https://github.com/ant-design/ant-design/assets/52034179/b62b8368-1f17-4108-9cfa-e1ca859e62af">
### Reproduction link

[https://ant.design](https://ant.design)

### Steps to reproduce

谷歌浏览器安装DARK READER插件，点击开启，然后打开ant-design的官网

### What is expected?

正常打开

### What is actually happening?

因为报错，页面空白

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | React18 |
| System | OS |
| Browser | Chorme |

---
后面补充截图

**Comment by afc163** [comment]
和 https://github.com/ant-design/ant-design/issues/49524 同一个问题。

**Comment by afc163** [comment]
目前问题已经修复，暂时回滚了 dumi 版本：https://github.com/ant-design/ant-design/pull/49550
