### ISSUE TITLE
Incorrect decimal formatting/parsing in InputNumber component

### ISSUE THREAD

**Issue by juanurcola** [ant-design/ant-design#49549]
### Reproduction link

[https://stackblitz.com/edit/react-x7qd85?file=demo.tsx](https://stackblitz.com/edit/react-x7qd85?file=demo.tsx)

### Steps to reproduce

1. Enter number with decimals, e.g. 1000.12345678
2. The format generated in that example is: 1,000.123,456,789 

### What is expected?

The format I want: 1,000.123456789.

### What is actually happening?

In my case, depending on the regional location where this component is used, I define the format and parse it.
Example: 
In Argentina the correct format would be: 1.000,123456789
In Mexico the correct format would be: 1,000.123456789 

I couldn't find a solution that contemplates both possible cases.

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2.0 |
| System | mac |
| Browser | chrome |

**Comment by smallbonelu** [comment]
you can adjust your `parser` and `formatter` like this:
```javascript
<InputNumber<number>
  defaultValue={1000}
  formatter={(value) => {
    const parts = `${value}`.split('.');
    const integerPart = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',');
    const decimalPart = parts[1] ? `.${parts[1]}` : '';
    return `${integerPart}${decimalPart}`;
  }}
  parser={(value) => {
    return value ? parseFloat(value.replace(/,/g, '')) : '';
  }}
  onChange={onChange}
/>
```
