### ISSUE TITLE
自定义全局组件的 Empty 样式后，Table的过滤面板没生效

### ISSUE THREAD

**Issue by wangchaoHeart** [ant-design/ant-design#49542]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-mwgpaq?file=demo.js)

### Steps to reproduce

打开Table的过滤面板

### What is expected?

表格过滤面板空状态应该渲染的是自己全局定义的空状态组件

### What is actually happening?

表格过滤面板空状态还是自己的空状态组件

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.3.1 |
| System | windows11 |
| Browser | chrome  125.0.6422.176（正式版本） |

**Comment by Wxh16144** [comment]
感觉可以加一个 Feature， 允许修改其内部的 Empty 组件

**Comment by duqigit** [comment]
正确的显示应该是空白

**Comment by duqigit** [comment]
是不是可以返回一个空的组件用来代替undefined呢，
`const customizeRenderEmpty2 = () => (
  <div></div>
)`

**Comment by wangchaoHeart** [comment]
> 正确的显示应该是空白

不是呀，正确的应该显示我全局定义的Empty，而不是antd自身的Empty。即表格过滤面板的空状态应该和表格的空状态一样
![image](https://github.com/ant-design/ant-design/assets/117444298/0baa8bbe-69e2-4c11-b450-58b86090b3cf)
![image](https://github.com/ant-design/ant-design/assets/117444298/e8404d31-da80-4486-ba33-0e8909610919)

**Comment by duqigit** [comment]
不好意思，明白了

**Comment by zombieJ** [comment]
Table filter 里的 Empty 写死了一个 Image，导致改不了了。

**Comment by yoyo837** [comment]
Since #49548 has been reverted by #49600, reopen this.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/49613
