### ISSUE TITLE
Table组件的中当数据源中存在BigInt数据类型时，无法渲染此类型的Bug

### ISSUE THREAD

**Issue by TyerLi4000** [ant-design/ant-design#49551]
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-x1uk9u](https://stackblitz.com/edit/vitejs-vite-x1uk9u)

### Steps to reproduce

请按照 [AntdTable Issue For BigInt](https://stackblitz.com/edit/vitejs-vite-x1uk9u/) 这个链接重现步骤。

### What is expected?

Table组件的中当数据源中存在BigInt数据类型时，应该能显示此BigInt类型的值。

### What is actually happening?

Table组件的中当数据源中存在BigInt数据类型时，无法渲染此类型的值。

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.3.1 |
| System | Windows 10 |
| Browser | Chrome 126.0.6478.115 |

---
在前端中我们项目在大量使用BigInt类型，希望Table及其它组件能支持这个类型。

**Comment by afc163** [comment]
Could not open your reproduce link.

**Comment by TyerLi4000** [comment]
https://stackblitz.com/edit/vitejs-vite-x1uk9u

> Could not open your reproduce link.
Try it out https://stackblitz.com/edit/vitejs-vite-x1uk9u

**Comment by afc163** [comment]
这个数字直接渲染也是渲染不出来的，应该和 antd 没什么关系：https://stackblitz.com/edit/vitejs-vite-mbccxj?file=src%2FApp.jsx,src%2FTableIssue.jsx

**Comment by TyerLi4000** [comment]
@afc163 
使用{number2.toString()} 可以渲染出数值。
能否让Table组件在遇到BigInt类型时，自动调用这个类型的toString()方法？

**Comment by afc163** [comment]
组件层不应该越俎代庖，应遵循原本的渲染逻辑。
