### ISSUE TITLE
执行ant-design的代码，vscode终端没有报错，但是没有办法加载出来，就算把自己新加的代码注释了，也是没办法加载出来

### ISSUE THREAD

**Issue by Roxannej** [ant-design/ant-design#49566]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

1、yarn start启动项目
2、随便某个页面下新增代码，再刷新，发现无法加载
3、注释自己增加的全部代码，还是没办法加载

### What is expected?

注释自己增加的代码后，应该也是可以正常加载项目的

### What is actually happening?

注释自己增加的代码后，无法正常加载浏览器报错

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | React18 |
| System | OS |
| Browser | Chorme |

<img width="1438" alt="截屏2024-06-23 18 48 45" src="https://github.com/ant-design/ant-design/assets/52034179/47364aff-9014-4fa5-b887-9f65bd7e6535">
<img width="895" alt="截屏2024-06-23 18 49 09" src="https://github.com/ant-design/ant-design/assets/52034179/fa83393f-4a1d-43c7-a8e6-c4f2b6b60b8b">

**Comment by wanpan11** [comment]
maka 打包看不到进度，要自己刷新。最新的提交已经把dumi回退了，重新 install 下应该就好了

**Comment by afc163** [comment]
<img width="376" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/3018b9cf-39be-4d92-917c-911897b96a58">

这个是还在 building，要等他跑完才能访问链接。

**Comment by afc163** [comment]
后续 mako 会优化这块的 log 展示方式。cc @sorrycc
