### ISSUE TITLE
a-table希望能添加虚拟纵向滚动条-方便查看数据。

### ISSUE THREAD

**Issue by onlyscv** [ant-design/ant-design#49567]
### What problem does this feature solve?

如果表格高度超过了当前屏幕的高度。
恰好我需要看第54条数据的，Y 滚动条后面的。
那我这时候不得不翻到表格最底下，横向滚动，然后再找到低54行的数据...。

这样的体验是非常不友好的。

### What does the proposed API look like?

横向滚动条能固定到屏蔽底部，方便随时左右滚动查看数据，

需要翻到最底下，才能左右滚动。
![2](https://github.com/ant-design/ant-design/assets/33649764/f5205ecb-e90f-441f-a449-08c5b9e1fc96)

**Comment by fnoopv** [comment]
`a-table`是社区维护的`vue`版本？应该去[antd-vue](https://antdv.com/components/table-cn)提

**Comment by onlyscv** [comment]
> `a-table`是社区维护的`vue`版本？应该去[antd-vue](https://antdv.com/components/table-cn)提

额··好的，确实搞错地方了。尴尬
