### ISSUE TITLE
tags导航  布局bug

### ISSUE THREAD

**Issue by redCar007** [ant-design/ant-design#49561]
### What problem does this feature solve?

你们组件功能在页面显示会有抖动   tags 的 上下左右切换    屏幕放大到115%的时候 出现抖动持续性的

### What does the proposed API look like?

切换是正常的显示

![1](https://github.com/ant-design/ant-design/assets/171399428/2a37eafa-9681-4963-a078-c79203d3b2ba)
![2](https://github.com/ant-design/ant-design/assets/171399428/40138226-bafa-4ccc-9cc5-b218c1d938a8)

https://github.com/ant-design/ant-design/assets/171399428/360f1e35-70db-4e1d-93ec-04e0c9bf6981

**Comment by yyz945947732** [comment]
https://github.com/ant-design/ant-design/issues/48678

**Comment by smallbonelu** [comment]
你指的应该是tabs吧

**Comment by zombieJ** [comment]
视频看不到，重新录一下？

**Comment by redCar007** [comment]
谷歌浏览器比例110%&nbsp; &nbsp;QQ浏览器115%&nbsp; 都存在&nbsp; mac也有




◆◇═█━━
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月25日(星期二) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] tags导航  布局bug (Issue #49561)





 
Hello @redCar007. Please provide a online reproduction by forking codesandbox of ***@***.*** or ***@***.***, or provide a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 3 days.
 
你好 @redCar007，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 ***@***.*** 或 ***@***.*** 的 codesandbox，或者提供一个最小化的 GitHub 仓库。3 天内未跟进此 issue 将会被自动关闭。
  
什么是最小化重现，为什么这是必需的？
  

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

bug2.mp4 (3.98M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5c3363361262a69e99778ba24737544e19475550510e03044c025554591a5e0756504e035107564c5251565251545e575150070f613f6603145451180c4752615c&t=exs_ftn_download&code=a3c6a7fa




bug.mp4 (3.90M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=0a3033625db8f299ce74dbf6123401494e440356010006051b030b515019035150521e555151514b0556015b0c000356540702563433330443571d0f4400335b&t=exs_ftn_download&code=603b443f

**Comment by yyz945947732** [comment]
https://github.com/ant-design/ant-design/issues/48775

https://github.com/ant-design/ant-design/issues/48678

https://github.com/ant-design/ant-design/issues/46198

**Comment by redCar007** [comment]
感谢感谢




◆◇═█━━
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月27日(星期四) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] tags导航  布局bug (Issue #49561)





 
#48775
 
#48678
 
#46198
