### ISSUE TITLE
3.x Table' cell not align properly

### ISSUE THREAD

**Issue by mortalYoung** [ant-design/ant-design#49572]
### Reproduction link

[https://3x.ant.design/components/table/#components-table-demo-fixed-header](https://3x.ant.design/components/table/#components-table-demo-fixed-header)

[https://3x.ant.design/components/table/#components-table-demo-fixed-columns-header](https://3x.ant.design/components/table/#components-table-demo-fixed-columns-header)

### Steps to reproduce

.

### What is expected?

.

### What is actually happening?

.

| Environment | Info |
| --- | --- |
| antd | 3.x |
| React | - |
| System | macOS |
| Browser | chrome |

**Comment by mortalYoung** [comment]
I don't think it's a issue that should be closed. It's a bug could be re-produced on Website. 

I agree with 3.x is out of the maintenance, but as least you should tell users the Why and How fix this, do you?

**Comment by yoyo837** [comment]
First, 3.x is no longer maintained. Second, there is no valuable problem description in the issue. We don't know what the issue is about. Finally, I guess your problem may be the same as https://github.com/ant-design/ant-design/issues/47283

**Comment by zombieJ** [comment]
Thank you for comment. I understand your concern regarding the bug while it's true that the 3.x is no longer maintained, I want to clarify the reasons and provide some guidance on how to proceed.

As with many open-source projects, maintenance is typically based on contributor availability and project priorities. In this case, 3.x has reached its end-of-life, meaning:

* No Active Support: The maintainers are no longer actively working on updates or fixes for this version.
* Community Focus: The community and maintainers have shifted focus to newer versions which offer better performance, more features, and active support.
