### ISSUE TITLE
Tabel 组件的固定表头，scroll属性无法设置y:‘auto’

### ISSUE THREAD

**Issue by chengshaohui** [ant-design/ant-design#49573]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wthezd?file=demo.js)

### Steps to reproduce

Tabel设置scroll={{y: 'auto'}}，表格默认使用scroll方式展示滚动条

### What is expected?

一般情况下，表格更友好的交互是当高度足够时，不展示纵向滚动条，高度不足时，再展示纵向滚动条，所以建议增加scroll={{y: 'auto',maxHeight:  400}}这样的功能

### What is actually happening?

固定表头一直展示滚动条，哪怕只有一行内容，最好是内容不足时，隐藏滚动条

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | "react": "^18.2.0" |
| System | win10 |
| Browser | chrome126 |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/29082

**Comment by huangwei9527** [comment]
太需要这个功能了
