### ISSUE TITLE
[Draggable Tabs Demo] Drag the tab to the edge will appear abnormal

### ISSUE THREAD

**Issue by 1ib0** [ant-design/ant-design#49586]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

1. Select the tab2
2. Drag the tab2 to the right edge, and then drop.

### What is expected?

When dragging and dropping, tab2 and tab3 exchange the position.

### What is actually happening?
![image](https://github.com/ant-design/ant-design/assets/42805389/c514a359-46a0-4bba-b014-c980514746df)

1. when dragging, tab2 and tab3 began to exchange positions, but tab2 suddenly returned to the original position again.
2. when dropping, tab2 and tab3 change the position, but highlight is abnormal for the active tab.

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.3.1 |
| System | Mac 13.5.2 |
| Browser | Google Chrome 126.0.6478.114 |

---
I think we need to set collisionDetection={closestCenter} for the DndContext. and the closestCenter is imported from the @dnd-kit/core.

**Comment by Wxh16144** [comment]
I think you are right
