### ISSUE TITLE
tsconfig.json内部的配置有报错

### ISSUE THREAD

**Issue by Roxannej** [ant-design/ant-design#49582]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

tsconfig.json文件，查看配置

### What is expected?

没有错误提示

### What is actually happening?

有错误提示

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | React18 |
| System | OS |
| Browser | Chorme |

<img width="897" alt="截屏2024-06-24 21 44 51" src="https://github.com/ant-design/ant-design/assets/52034179/6e7cc8a0-dd5a-48d8-8fbc-7e2a10c45099">
<img width="813" alt="截屏2024-06-24 21 47 03" src="https://github.com/ant-design/ant-design/assets/52034179/35eb98f1-5616-4509-a743-d67ad03ab2dc">

**Comment by afc163** [comment]
支持 bundlers 的：https://www.typescriptlang.org/tsconfig/#moduleResolution
