### ISSUE TITLE
Cascader has wrong white background in dark theme

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#49589]
<img width="1782" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/c168c28d-30c1-469a-9c93-e69e3f605d1a">

https://ant.design/components/cascader?theme=dark#examples

**Comment by zombieJ** [comment]
@MadCcc 是不是还是 dumi 的那个问题？

**Comment by MadCcc** [comment]
和 @Jinbao1001 确认了下，umi 的 ssr 分支没有带过来，带上那个分支代码就好了。
包括之前的顶部导航问题也是这个导致的。
