### ISSUE TITLE
pageSizeOptions 这个属性是设置怎样的字符格式？ 

### ISSUE THREAD

**Issue by webliving** [ant-design/ant-design#4959]
#### Environment(required)

- antd version:2.6.1
- OS and its version: macOS 10.12.3
- Browser and its version: chrome 54

#### What did you do? Please provide steps to re-produce your problem.

pageSizeOptions 这个属性是设置怎样的字符格式？ 
pageSizeOptions={['10', '20', '30', '40']}
pageSizeOptions="{['10', '20', '30', '40']"

#### What do you expected?

期望正确设置分页组件的页码数量选择器

#### What happen?

浏览器直接崩溃，假死了

**Comment by afc163** [comment]
http://codepen.io/anon/pen/pRXazg?editors=0010

---

Do not create duplicated issue: #4957 . That was very rude. 😠

**Comment by webliving** [comment]
@afc163 😭  , 以为没创建成功。。

**Comment by afc163** [comment]
~~~ 估计网络不太好，建议翻下墙。
