### ISSUE TITLE
按照文档把TimePicker替换momentjs成dayjs，TimePicker. RangePicker无法使用

### ISSUE THREAD

**Issue by dyxweb** [ant-design/ant-design#49591]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-forked-g4jq0?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

按照https://4x.ant.design/docs/react/replace-moment-cn文档操作即可

### What is expected?

可以正常使用TimePicker. RangePicker

### What is actually happening?

TimePicker. RangePicker不可使用

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | windows |
| Browser | Chrome |

---
此问题和https://github.com/ant-design/ant-design/issues/32616一个以往被关闭的issue一样的问题，但是代码和官方提供的文档https://4x.ant.design/docs/react/replace-moment-cn一样，应该怎么调整代码才能使用TimePicker. RangePicker呢，按照官方文档无法使用

**Comment by dyxweb** [comment]
此问题和  https://github.com/ant-design/ant-design/issues/32616  一个以往被关闭的issue一样的问题，但是代码和官方提供的文档  https://4x.ant.design/docs/react/replace-moment-cn 一样，应该怎么调整代码才能使用TimePicker. RangePicker呢，按照官方文档无法使用

**Comment by zombieJ** [comment]
TimePicker 本身就是 DatePicker 的 `picker="time"`。所以 TimePicker 的 RangePicker 自然也是 DatePicker.RangePicker 的 `picker="time"`：

```tsx
const TimePicker = (...) => {
  return <DatePicker ... />
});

// 子组件有需要同样自己套一个即可
TimePicker.RangePicker = (...) => {
  return <DatePicker.RangePicker ... />
};
```
