### ISSUE TITLE
inputnumber组件设置precision=0控制选择整数时，输入多个小数点导致form表单拿到的结果异常

### ISSUE THREAD

**Issue by Arthaskj** [ant-design/ant-design#49593]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-4-24-16-forked-pcl25v?file=%2Fdemo.tsx%3A1%2C1-39%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxu0iymi0006356lyv76f8yb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxu0iymi0002356l2550h14j%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxu0iymi0003356lwu7u4gpz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxu0iymi0005356lurlfg681%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxu0iymi0002356l2550h14j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu0iymh0001356lsfmprmaa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxu0o6md0002356ije3r8dr9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A39%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxu0iymi0002356l2550h14j%2522%252C%2522activeTabId%2522%253A%2522clxu0o6md0002356ije3r8dr9%2522%257D%252C%2522clxu0iymi0005356lurlfg681%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu0iymi0004356lcuytj1vf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxu0iymi0005356lurlfg681%2522%252C%2522activeTabId%2522%253A%2522clxu0iymi0004356lcuytj1vf%2522%257D%252C%2522clxu0iymi0003356lwu7u4gpz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxu0iymi0003356lwu7u4gpz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

在使用form表单时，inputnumber组件如果设置 precision=0，在输入时如果输入多个小数点，inputnumber显示正常，但是form表单submit获取的数据异常，例如输入 ’123.456.789‘，inputnumber显示‘123’，但是form表单结果是 '123.456'

### What is expected?

form表单拿到的值与显示的值一致

### What is actually happening?

form表单值与显示值不一致

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | react |
| System | windows |
| Browser | chrome 125.0.6422.142（正式版本） （64 位） |

**Comment by zombieJ** [comment]
v4 已经过了维护期了，建议升级到 v5。试了一下，v5 里是对的：

https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-4-24-16-forked-ff8cqr

**Comment by Arthaskj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
