### ISSUE TITLE
Theme font-family not applied to Dropdown cascading menu

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#49616]
### Reproduction link

[https://codepen.io/devuxer/pen/qBGwoyG?editors=001](https://codepen.io/devuxer/pen/qBGwoyG?editors=001)

![2024-06-26 22_41_16-Arc](https://github.com/ant-design/ant-design/assets/1298521/6c13a4da-9fed-407b-b3a2-38e9121be265)

(Notice that the font of the cascading menu is Times New Roman.)

### Steps to reproduce

Create a React project with a cascading dropdown menu (or just open the repro). Compare the font-family of the cascading menu with the parent menu.

### What is expected?

The font-family of the cascading menu is the same as the parent menu.

### What is actually happening?

The font-family is Times New Roman (the browser default), while the parent menu has the expected font family (`-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`)

### Why?

I think the problem is that the parent menu `li` elements are under a div with the class `ant-dropdown`, which has the `font-family` set, while the child `li` elements are not under a div with `ant-dropdown`, so the `font-family` never gets set for the children, resulting in them showing up with the default font-family.

### Workaround

Add this to your CSS:

```css
/* fix dropdown cascading menu font-family bug */
div.ant-dropdown-menu-submenu {
    font-family: "Segoe UI";
}
```

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.3.1 |
| System | Windows 11 (Version 10.0.22631 Build 22631) |
| Browser | Chromium version 126.0.6478.62 (Official Build) (64-bit) |

**Comment by afc163** [comment]
被 https://github.com/ant-design/ant-design/pull/48893 影响了。

**Comment by wanpan11** [comment]
> 被 #48893 影响了。cc @wanpan11

俺 看看
