### ISSUE TITLE
https://ant-design.antgroup.com/index-cn 全局样式-字体-字体颜色，16进制颜色值标注有误

### ISSUE THREAD

**Issue by willczar** [ant-design/ant-design#49610]
### Reproduction link

[https://ant-design.antgroup.com/index-cn](https://ant-design.antgroup.com/index-cn)

### Steps to reproduce

https://ant-design.antgroup.com/index-cn
全局样式-字体-字体颜色，16进制颜色值标注

### What is expected?

标题字体
#000000

### What is actually happening?

标题字体
#000000E0

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 未知 |
| System | win11 |
| Browser | Microsoft Edge 版本 126.0.2592.68 (正式版本) (64 位) |

---
https://ant-design.antgroup.com/index-cn 
全局样式-字体-字体颜色，16进制颜色值标注有误

**Comment by zombieJ** [comment]
6位是RGB，8位是RGBA哈~
