### ISSUE TITLE
Cascader 级联选择能否添加一个,mouseEnterDelay (	鼠标移入后延时多少才显示，单位：秒)

### ISSUE THREAD

**Issue by ajaxpost** [ant-design/ant-design#49629]
### What problem does this feature solve?

有时数据多了,鼠标滑动快了,很容易将上一级数据划走

### What does the proposed API look like?

mouseEnterDelay = {0.5}

**Comment by zombieJ** [comment]
没明白，`有时数据多了,鼠标滑动快了,很容易将上一级数据划走` 这个是什么意思？具体说说，或者来个 gif 看看？
