### ISSUE TITLE
InputNumber 输入的值会覆盖 suffix

### ISSUE THREAD

**Issue by daigang1228** [ant-design/ant-design#49621]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-qxxghg?file=demo.tsx,package.json)

### Steps to reproduce

https://stackblitz.com/edit/react-qxxghg?file=demo.tsx,package.json

### What is expected?

不覆盖后缀

### What is actually happening?

value覆盖后缀

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18 |
| System | windows |
| Browser | chrome |

---
https://stackblitz.com/edit/react-qxxghg?file=demo.tsx,package.json

**Comment by zombieJ** [comment]
suffix 是固定位置，的确可以优化一下

**Comment by coding-ice** [comment]
mark一下，交给我吧

**Comment by coding-ice** [comment]
目前看来，如果`suffix`不走绝对定位的话，应该要把层级改变下（`controls`），改变到和`suffix`同一层下
另外`InputNumber`好像没有标注`suffix` API，是否也需要增加下呢


<img width="1501" alt="image" src="https://github.com/ant-design/ant-design/assets/49827327/891a3af7-18c5-4bd9-924a-67f33a4788fe">

**Comment by MadCcc** [comment]
InputNumber 不支持配置 suffix 的，现在没有 suffix 的相关设计，仅作为内部使用的 api

**Comment by MadCcc** [comment]
InputNumber 不支持配置 suffix 的，现在没有 suffix 的相关设计，仅作为内部使用的 api

**Comment by afc163** [comment]
InputNumber 目前还不支持 suffix，能显示出来是个 bug。。

**Comment by iceweb1999** [comment]
> InputNumber 目前还不支持 suffix，能显示出来是个 bug。。

哈哈哈哈哈，如果要隐藏 俺来处理～

**Comment by afc163** [comment]
也别隐藏了，会被当做 breakchange，看看这个问题本身有没有解的可能吧。

**Comment by coding-ice** [comment]
我的想法是，`suffix`和`controls `同时存在的时候，hover的时候显示隐藏`toggle `可行吗

**Comment by afc163** [comment]
没懂，显示还是隐藏？

**Comment by coding-ice** [comment]
> 没懂，显示还是隐藏？

默认 -> suffix显示
hover -> controls显示 suffix隐藏

**Comment by afc163** [comment]
如果 suffix 是需要点击操作的呢？

**Comment by coding-ice** [comment]
点击的话确实不行，或者所有的元素并排放
确实没啥比较完美的方案，都要取舍一些...

**Comment by afc163** [comment]
不 hover 的时候，只有 suffix，正常位置放。

```
[----------------------------]
[                            ]
[                     suffix ]
[                            ]
[----------------------------]
```

hover 的时候 controls 出现。

```
[----------------------------]
[                       | +  ]
[                suffix |----]
[                       | -  ]
[----------------------------]
```

1. controls 的出现动画是从右往左 slide-in。
2. 然后 suffix 以一个平滑的动画相应向左移动。

**Comment by coding-ice** [comment]
嗯嗯，我来试试～

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/49674
