### ISSUE TITLE
Form validations errors read in reverse order on submit of form by screen reader

### ISSUE THREAD

**Issue by kethridge-wss** [ant-design/ant-design#49628]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qy5pz8)

### Steps to reproduce

1. Leave all inputs blank
2. Click inside the 'Name' input
3. Press enter (or just click Submit button)
4. Observe screen reader reads validation errors from Form.Item in reverse order as they appear on screen and in the DOM

### What is expected?

Screen reader will read validation errors on submit of a form in the order form items appear in the DOM.  In my example, top to bottom.

### What is actually happening?

Screen reader is reading validation errors in reverse order.  In example given it is reading 'Please add your email' and then 'Please add your name'.

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18.x |
| System | Windows 10 Pro 19045.4529 |
| Browser | Chrome 126.0.6478.114 |

---
The validation trigger is empty on the Form.Item components so it will not perform validation in real time.  Validation is not to be performed until the form is submitted.  This behavior happens even if there are more than two inputs, and will read them in reverse order.  We discovered this with accessibility testing on one of our forms that has four inputs that are not validated until form submission.  It will read all four validation inputs in reverse order they appear in the DOM.

The screen reader being used is NVDA.  Here is a picture showing the NVDA speech viewer showing the alerts being read in reverse order after hitting submit:

![2024-06-27 12_07_03-Windows Media Player](https://github.com/ant-design/ant-design/assets/137907332/a2c654f2-2b7e-44d2-83bf-7b2b547013c5)

Screen Recording:

https://github.com/ant-design/ant-design/assets/137907332/2b7ce824-c268-4fff-84ef-b75791ae1c55

**Comment by MadCcc** [comment]
Can you reproduce it in 5.x?

**Comment by kethridge-wss** [comment]
Yes this is reproducible in 5.x as well.  Same behavior as outlined in the original issue post.  Hitting 'Enter' immediately to submit the form or just clicking the 'Submit' button without entering anything in either input, NVDA will read the validation errors in reverse order.

Here is a reproduction application-
https://stackblitz.com/edit/antd-reproduce-5x-r9mwdh?file=demo.tsx
https://antd-reproduce-5x-r9mwdh.stackblitz.io/
