### ISSUE TITLE
tour‘结束导览’是否支持更改为其他的自定义文案

### ISSUE THREAD

**Issue by Jackierchan** [ant-design/ant-design#49622]
### Reproduction link

[https://github.com/react-component/tour/blob/master/src/TourStep/DefaultPanel.tsx](https://github.com/react-component/tour/blob/master/src/TourStep/DefaultPanel.tsx)

### Steps to reproduce

tour结束导览是否支持更改为其他的自定义文案

### What is expected?

tour结束导览是否支持更改为其他的自定义文案

### What is actually happening?

没有找到类似的props

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
```jsx
  const steps: TourProps['steps'] = [
    ...,
    {
      title: '最后一个步骤',
      description: 'Click to see other actions.',
      target: () => ref3.current,
      nextButtonProps: { children: '结束按钮' },
    },
  ];
```

**Comment by waterbang** [comment]
or

```vue
 <el-tour-step
          :target="targetRefs.downloadRef"
          :next-button-props="{ link: true, color: '#000', children: '结束' }"
          :prev-button-props="{ link: true, color: '#000' }"
        >
</el-tour-step>
```
