### ISSUE TITLE
体积太大，希望优化包体积

### ISSUE THREAD

**Issue by ljianc** [ant-design/ant-design#49623]
### What problem does this feature solve?

仅仅引用一个 `<Spin />` 组件，ant及其依赖项所占体积就有大几十K，实在太大了。
对比了字节的 `arco design `(15K以内)，`semi design` （10K以内）。
示例代码：
```
import { Spin } from "antd";

export default function Component() {
  return <Spin />;
}
```
webpack添加splitChunks有助于查看
```
   vendors: {
          test: /[\\/]node_modules[\\/]/,
          name(module) {
            const packageName = module.context.match(
              /[\\/]node_modules[\\/](.*?)([\\/]|$)/
            )[1];
            return packageName.replace("@", "");
          },
          chunks: "all",
          enforce: true,
        },
```

### What does the proposed API look like?

![image](https://github.com/ant-design/ant-design/assets/10055508/25ddc369-7d27-4ca0-a960-453c4044fc4e)
![1719486203189](https://github.com/ant-design/ant-design/assets/10055508/78724d91-c5dd-4552-88ae-47ef42b8c86d)

**Comment by MadCcc** [comment]
包含了一些公用的 cssinjs 以及主题相关的文件，如果使用组件数增加的话这些是不会增长的

**Comment by ljianc** [comment]
> 包含了一些公用的 cssinjs 以及主题相关的文件，如果使用组件数增加的话这些是不会增长的

打算用在C端的，这体积直接劝退了，这样设计只适合B端项目了

**Comment by afc163** [comment]
C端建议用 antd-mobile。

**Comment by ljianc** [comment]
> C端建议用 antd-mobile。

我说的是C端的网站，字节的两个，还有tdesign初始体积都没这么夸张，我觉得可以优化一下体积

**Comment by afc163** [comment]
尺寸会持续优化的，如果具体的优化想法欢迎直接给 PR 或者修改思路。
