### ISSUE TITLE
table滚动条显示不出来，内容显示重叠

### ISSUE THREAD

**Issue by hornetbillow** [ant-design/ant-design#4963]
#### Environment(required)

- antd version:3.10.9

- OS and its version:windows10
- Browser and its version:Google  57.0.2970.0 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
```javascript
const tableConfig = {
        rowKey: 'id',
        bordered: true,
        loading: false,
        size: 'small',
        title,
        scroll: {
            x: true,// 此处设置true后，内容显示重叠，而且横向滚动条无法正常显示，设置为1300后，正常显示，不清楚原因，是否是新引入的Bug
            y: false
        },
        pagination: {
            total: props.total,
            pageSize: props.currentSize,
            pageSizeOptions: ['10', '20', '30', '40'],
            onShowSizeChange: (currentSize, changeAfterSize) => onShowSizeChange(currentSize, changeAfterSize),
            showSizeChanger: true,
            onChange: currentIndex => {
                if(onPageIndexChanged)
                    onPageIndexChanged(currentIndex);
            }
        }
    };

<Table loading={props.loading}
                   {...tableConfig}
                   style={{
                       whiteSpace: 'nowrap'
                   }}
                   columns={props.columns}
                   dataSource={props.rowData}/>

```

#### What do you expected?
table内容正常显示，且横向滚动条正常出来以及解释出现此处Bug的原因

#### What happen?
table内容显示重叠

**Comment by hornetbillow** [comment]
![Uploading RTX截图未命名.png…]()

**Comment by cxyxc** [comment]
同样的问题。
win10 Chrome56.0.2924.87 
antd 版本 3.10.8 升级到 3.10.9 后 ，表格属性设为 scroll={{x: 1300}}时
表格的最大宽度变为 1300px，而在 3.10.8 版本上为自适应布局，无最大宽度。
如图所示
![image](https://cloud.githubusercontent.com/assets/20027281/23118606/bb8a20b6-f78f-11e6-827d-ee5174a8ff65.png)
![image](https://cloud.githubusercontent.com/assets/20027281/23118620/c7720e98-f78f-11e6-8c86-745a1c2aec5e.png)

**Comment by benjycui** [comment]
？？？ 

antd 现在最新版是 2.7.x
