### ISSUE TITLE
TreeSelect的treeTitleRender选中节点后，输入框无法显示选中的内容

### ISSUE THREAD

**Issue by xiaomaodml** [ant-design/ant-design#49631]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-n3w9uy?file=demo.tsx)

### Steps to reproduce

使用treeTitleRender重新渲染节点后，选中节点，TreeSelect输入框无法显示已选中的值

### What is expected?

能正常显示选中值

### What is actually happening?

选中后，无法显示

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.3.3 |
| System | windows 11 |
| Browser | Chrome 126.0.6478.115 |

**Comment by zombieJ** [comment]
配置 `fieldNames` 的时候，`treeNodeData` 和 `labelInValueData` 不一致： https://github.com/react-component/tree-select/pull/447/files#diff-7d33ac261ea6333c407d1a824d21d20a379c9251945b1425112b50692e211cbeR448

cc @huangkairan

**Comment by MadCcc** [comment]
Fixed in v5.19.0

**Comment by MrZhouZh** [comment]
不升级版本的情况下, 有什么方式可以 hack 一下
