### ISSUE TITLE
虚拟列表横向滚动条鼠标选中拖动移动过快，无法掌控

### ISSUE THREAD

**Issue by cjtcjt999** [ant-design/ant-design#49638]
### Reproduction link

[https://codepen.io/cjtcjt999/pen/NWVVWqx?editors=0010](https://codepen.io/cjtcjt999/pen/NWVVWqx?editors=0010)

### Steps to reproduce

拖动横向滚动条，列表内容快速移动，无法像普通Table一样精确移动

### What is expected?

拖动横向滚动条，列表内容像普通Table一样精确移动

### What is actually happening?

拖动横向滚动条，列表内容快速移动，无法像普通Table一样精确移动

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.2.0 |
| System | win11 |
| Browser | 126.0.6478.126 |

**Comment by zombieJ** [comment]
更新一下 node_modules，这个已经修复了哈~
