### ISSUE TITLE
期望 Autocomplete 选中可以展示label

### ISSUE THREAD

**Issue by zx-zx22** [ant-design/ant-design#49633]
### What problem does this feature solve?

目前有一个需求是一个可输入可选择的组件，options是label和value，有些业务场景下可以直接选择选项，但是如果回填的是value感觉很奇怪，因为我们的value是一个ID，有些业务场景下需要属于一个表达式。目前Autocomplete 满足不了这个需求，如果使用Select动态添加options操作不太方便，因为需要用户再点击一下输入的那个选项

### What does the proposed API look like?

我期望Autocomplete 回填的直接是label字段

**Comment by zombieJ** [comment]
AutoComplete 是输入组件，正解就是你提到的 HOC Select。点击问题受控 `onSearch` 来填充即可。

封装过一次后，其他地方也就可以用了哈~

**Comment by Junlin-Zhu** [comment]
我们也有此需求。

**Comment by uioonm** [comment]
> 我们也有此需求。

` 
可以通过value，onSearch，onSelect来实现这个需求
const [searchValue, setSearchValue] = useState("");           
<AutoComplete
                placeholder="请输入名称"
                options={options}
                value={searchValue}
                onSearch={setSearchValue}
                onSelect={(value, option) => {
                    setSearchValue(option.label);
                    onSelectNode(value);
                }}
                filterOption={(input, option) => (option?.label ?? "").toLowerCase().includes(input.toLowerCase())}
            />`

**Comment by uioonm** [comment]
> 我们也有此需求。

可以通过value，onSearch，onSelect来实现这个需求，参考下面的demo
const [searchValue, setSearchValue] = useState("");            
<AutoComplete
      placeholder="请输入名称" 
      options={options} 
      value={searchValue}
      onSearch={setSearchValue} 
      onSelect={(value, option) => { setSearchValue(option.label); onSelectNode(value); }} 
      filterOption={(input, option) => (option?.label ?? "").toLowerCase().includes(input.toLowerCase())} 
/>
