### ISSUE TITLE
antd DatePicker 组件 表单返回值是 YYYY-MM-DDTHH:mm:ssZ 需要转换YYYY-MM-DD HH:mm:ss

### ISSUE THREAD

**Issue by xcxiao7710** [ant-design/ant-design#49642]
### What problem does this feature solve?

<FormItem locale={locale} label="结束时间" key='stopTime' name='stopTime'
rules={[{required: true, message: '请选择结束时间'}]}>

通过格式化无效 使用 loacle 无效 版本从

"antd": "^5.13.2", 升级到antd": "^5.18.0", 也不行 求各位一个解决方案
返回的是:"stopTime": "2024-06-27T16:00:00.000Z"
当然我查看了onChange 的数据是正常的2024-06-29 00:00:00 也是中国的区域标准时间

### What does the proposed API look like?

我需要: "stopTime": "2024-06-29 00:00:00", 这种数据

**Comment by Wxh16144** [comment]
用 Form.Item 的 `getValueFromEvent` api 自己转换一下呗

**Comment by xcxiao7710** [comment]
好的感谢

&nbsp;


与海
***@***.***

15520510119


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月28日(星期五) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] antd DatePicker 组件 表单返回值是 YYYY-MM-DDTHH:mm:ssZ 需要转换YYYY-MM-DD HH:mm:ss (Issue #49642)














 
用 Form.Item 的 getValueFromEvent api 自己转换一下呗

**Comment by xcxiao7710** [comment]
转换后出现问题
date.isValid is not a function 组件&nbsp;DatePicker 支持dayjs 但是不支持string转换后的值 可以提供转换的代码提供参考吗




与海
***@***.***

15520510119


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] antd DatePicker 组件 表单返回值是 YYYY-MM-DDTHH:mm:ssZ 需要转换YYYY-MM-DD HH:mm:ss (Issue #49642)





 
用 Form.Item 的 getValueFromEvent api 自己转换一下呗

**Comment by Wxh16144** [comment]
看文档吧：https://ant.design/components/form-cn#components-form-demo-getvalueprops-normalize
