### ISSUE TITLE
Tooltip，Popover 在zoom缩放下错乱

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#49640]
### Reproduction link

[https://ant.design/components/popover-cn](https://ant.design/components/popover-cn)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/29728228/90086358-0202-4a85-8f68-cf676fe07762)

![image](https://github.com/ant-design/ant-design/assets/29728228/3ef30881-f1c6-452a-b19d-17452693037d)

不上demo了，直接官方例子，打开开发者工具随便给父容器加一个zoom就复现了

这个问题应该是个普遍问题，凡是涉及到absolute定位的组件应该都存在（我没有一一验证，只是发现了一些项目中遇到的）

因为目标系统支持zoom缩放，所以，父容器只要有zoom，则Tooltip Popover 就必定错乱了，因为zoom改变了整体的定位

以前没有4k屏，可能没什么影响，现在4k，8k显示器逐步普及，除了pc操作系统和浏览器本身的缩放，很多系统也支持自己zoom缩放

又多了一个需要处理的前端问题

### What is expected?

希望不要错乱

### What is actually happening?

错乱了

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18 |
| System | mac/windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
transform 的 scale 拦过了，zoom 估计获取值会不太一样。得看看

**Comment by afc163** [comment]
我记得之前没这个问题，最近有两个同类 issue，看看是不是哪里改挂了。

https://github.com/ant-design/ant-design/issues/49627

**Comment by zombieJ** [comment]
查了一下相关内容，这是 webkit 的 BUG。`getBoundingClientRect` 不会计算 `zoom` 的值，而在 Firefox 中则是正确计算。但是 Chromium 团队认为 spec 里没有，所以不算 BUG 所以不会修复：

* ref https://bugs.chromium.org/p/chromium/issues/detail?id=429140&no_tracker_redirect=1

**Comment by afc163** [comment]
@zombieJ 最近底层是有什么改动么？

**Comment by zombieJ** [comment]
> @zombieJ 最近底层是有什么改动么？

没有。是一直都不支持 `zoom`

**Comment by Wxh16144** [comment]
很早以前我在写 demo 的时候也用 zoom, 推荐用 `transform: scale(1.5);` 等方式代替..

**Comment by zombieJ** [comment]
> 查了一下相关内容，这是 webkit 的 BUG。`getBoundingClientRect` 不会计算 `zoom` 的值，而在 Firefox 中则是正确计算。但是 Chromium 团队认为 spec 里没有（`zoom` 不是一个标准 CSS 属性），所以不算 BUG 所以不会修复：
> 
> * ref https://bugs.chromium.org/p/chromium/issues/detail?id=429140&no_tracker_redirect=1

考虑到 zoom 不是一个标准 CSS，对其做支持需要递归计算上游所有的 box rect 会有显著的性能损耗。antd 侧不准备对其进行支持，请使用 `transform` 代替。但是你仍可以通过覆盖 `getBoundingClientRect` 来支持非标的 `zoom` 属性以满足自身的需求。

**Comment by maze1943** [comment]
实测chrome128.0.0.0以下没有问题，近期大量用户升级到128.0.0.0以上出现了类似问题

**Comment by zystudios** [comment]
> 遍问题，凡是涉及到absolute定位的组件应该都存在（我没有一一验证，只是发现了一些项目中遇到的）
> 
> 因为目标系统支持zoom缩放，所以，父容器只要有zoom，则Tooltip Popover 就必定错乱了，因为zoom改变了整体的定位
> 
> 以前没有4k屏，可能没什么影响，现在4k，8k显示器逐步普及，除了pc操作系统和浏览器本身的缩放，很多系统也

128以下一样有问题，我提issue的时候就低于128

用zoom好处是简单，chrome兼容性好，既然官方不支持那也没办法，transform 可以用，但是需要自己解决一些问题，我这边相同的页面，直接body上zoom一切完美，transform 会有部分样式错位需要自己根据实际情况解决了

**Comment by zystudios** [comment]
> 实测chrome128.0.0.0以下没有问题，近期大量用户升级到128.0.0.0以上出现了类似问题

128以下一样有问题，我提issue的时候就低于128

用zoom好处是简单，chrome兼容性好，既然官方不支持那也没办法，transform 可以用，但是需要自己解决一些问题，我这边相同的页面，直接body上zoom一切完美，transform 会有部分样式错位需要自己根据实际情况解决了

**Comment by chuyinweilai** [comment]
我这边用 transform:scale 也会出现偏移，你们是可以的吗？

**Comment by SkrMiiKio** [comment]
因 Firefox 和 Chrome >=128版本中停用了标准化 CSS `zoom` 功能，`getBoundingClientRect`, `getClientRects` 获取到的 `DOMRect` 实例不再计算所有父元素中的缩放层级，导致获取到的属性不准确。目前临时的解决方案是：
```js
/** [Polyfill] 修复 DOMRect 属性不受 zoom 变化的问题 */
if (CSS.supports('zoom', '1') && (/Firefox\//.test(navigator.userAgent) || /Chrome\/(\d+)/.exec(navigator.userAgent)?.[1] >= 128)) {
  const $getBoundingClientRect = Element.prototype.getBoundingClientRect
  const $getClientRects = Element.prototype.getClientRects
  const getRealZoom = function (el) {
    let target = el, zoom = 1
    while (target) {
      zoom /= +getComputedStyle(target).zoom || 1
      target = target.parentElement
    }
    return zoom
  }
  Element.prototype.getBoundingClientRect = function () {
    let rect = $getBoundingClientRect.call(this), zoom = getRealZoom(this)
    return zoom != 1 ? new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom) : rect
  }
  Element.prototype.getClientRects = function () {
    let list = $getClientRects.call(this), zoom = getRealZoom(this)
    if (zoom != 1) {
      list = [...list].map(rect => new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom))
      Object.defineProperty(list, 'item', { value(i) { return this[i] } })
      Object.setPrototypeOf(list, DOMRectList.prototype)
    }
    return list
  }
}
```

**Comment by SkrMiiKio** [comment]
因 Firefox 和 Chrome >=128版本中停用了标准化 CSS `zoom` 功能，`getBoundingClientRect`, `getClientRects` 获取到的 `DOMRect` 实例不再计算所有父元素中的缩放层级，导致获取到的属性不准确。目前临时的解决方案是：
```js
/** [Polyfill] 修复 DOMRect 属性不受 zoom 变化的问题 */
if (CSS.supports('zoom', '1') && (/Firefox\//.test(navigator.userAgent) || /Chrome\/(\d+)/.exec(navigator.userAgent)?.[1] >= 128)) {
  const _getBoundingClientRect = Element.prototype.getBoundingClientRect
  const _getClientRects = Element.prototype.getClientRects
  const getRealZoom = function (el) {
    let target = el, zoom = 1
    while (target) {
      zoom /= +getComputedStyle(target).zoom || 1
      target = target.parentElement
    }
    return zoom
  }
  Element.prototype.getBoundingClientRect = function () {
    let rect = _getBoundingClientRect.call(this), zoom = getRealZoom(this)
    return zoom != 1 ? new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom) : rect
  }
  Element.prototype.getClientRects = function () {
    let list = _getClientRects.call(this), zoom = getRealZoom(this)
    if (zoom != 1) {
      list = [...list].map(rect => new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom))
      Object.defineProperty(list, 'item', { value(i) { return this[i] } })
      Object.setPrototypeOf(list, DOMRectList.prototype)
    }
    return list
  }
}
```
