### ISSUE TITLE
table横向滚动条无法正常显示，且显示内容有重叠

### ISSUE THREAD

**Issue by hornetbillow** [ant-design/ant-design#4965]
#### Environment(required)

- antd version:3.10.9

- OS and its version:windows10
- Browser and its version:Google  57.0.2970.0 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
```javascript
const tableConfig = {
        rowKey: 'id',
        bordered: true,
        loading: false,
        size: 'small',
        title,
        scroll: {
            x: true,// 此处设置true后，内容显示重叠，而且横向滚动条无法正常显示，设置为1300后，正常显示，不清楚原因，是否是新引入的Bug
            y: false
        },
        pagination: {
            total: props.total,
            pageSize: props.currentSize,
            pageSizeOptions: ['10', '20', '30', '40'],
            onShowSizeChange: (currentSize, changeAfterSize) => onShowSizeChange(currentSize, changeAfterSize),
            showSizeChanger: true,
            onChange: currentIndex => {
                if(onPageIndexChanged)
                    onPageIndexChanged(currentIndex);
            }
        }
    };

<Table loading={props.loading}
                   {...tableConfig}
                   style={{
                       whiteSpace: 'nowrap'
                   }}
                   columns={props.columns}
                   dataSource={props.rowData}/>

```

#### What do you expected?
table内容正常显示，且横向滚动条正常出来以及解释出现此处Bug的原因

#### What happen?
table内容显示重叠

**Comment by cxyxc** [comment]
win10 Chrome56.0.2924.87 
antd 版本 3.10.8 升级到 3.10.9 后 ，表格属性设为 scroll={{x: 1300}}时
表格的最大宽度变为 1300px，而在 3.10.8 版本上为自适应布局，无最大宽度。
如图所示
3.10.8
![bb8a20b6-f78f-11e6-827d-ee5174a8ff65](https://cloud.githubusercontent.com/assets/20027281/23118834/99b6c222-f790-11e6-9144-852618a0e824.jpg)
3.10.9
![c7720e98-f78f-11e6-8c86-745a1c2aec5e](https://cloud.githubusercontent.com/assets/20027281/23118839/9edfe756-f790-11e6-9d43-51347262803d.png)

**Comment by afc163** [comment]
There is not `3.10.9` version of `antd`.

Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by cxyxc** [comment]
抱歉我看错了， 3.x 是我的npm版本。

**Comment by FANUP** [comment]
@cxyxc 请问你解决了吗？我也遇到了这样的问题

**Comment by cxyxc** [comment]
在版本 2.7.1 中指定 `scroll={{ x: true }}` , 然后设置单元格内容的 `white-space: nowrap` 样式强制不自动换行。若表格过长，且未设置单元格 width， 如下所示：
```javascript
columns: [{
                dataIndex: 'code',
                title: 'XXX'
            }, ... ]  // 省略其他列配置 
```
会导致屏幕宽度不足时表格内容重叠：
![qq 20170221104245](https://cloud.githubusercontent.com/assets/20027281/23148793/aac1631e-f822-11e6-9e97-10dac06dbfa1.jpg)
有没有不设置表格宽度仍可以自适应而且不会出现重叠现象的方式？

**Comment by afc163** [comment]
`white-space: nowrap` 时，宽度会被内容撑开。换句话说，当单元格宽度需要指定时，就不必设定 `white-space: nowrap` 了。

**Comment by cxyxc** [comment]
当表格内容超出一屏很多，并且不指定宽度时，仅设置`scroll={{ x: true }}`  `white-space: nowrap`会导致表格内容重叠显示，若不设置 `white-space: nowrap`，而采取设置宽度的方式，又可能出现某单元格内容过多导致换行。
理想效果是：
1.屏幕较小时，不发生重叠，而是出现横向滚动条
2.屏幕较大时，不限制最大宽度，可自适应
3.任何情况下，单元格内容都不能换行
请问这种效果能实现吗？谢谢！

**Comment by afc163** [comment]
http://codepen.io/anon/pen/MJNprN?editors=0110

Is this demo helpful?

**Comment by afc163** [comment]
@hornetbillow 如果同时设定 `white-space: nowrap` 和固定宽度，注意宽度不要小于内容宽度。

**Comment by afc163** [comment]
@cxyxc 你的问题看 #4976，我现在修一下。

**Comment by cxyxc** [comment]
好的，谢谢
