### ISSUE TITLE
Enable customizing margin-bottom property of ant-tabs-bar style of Tabs component

### ISSUE THREAD

**Issue by aaronplanell** [ant-design/ant-design#4966]
Hello,

The margin-bottom property of the bar of the _Tabs_ component is fixed to 16px. It will be useful to allow modify this proportion with a property of the compoment or, at least, with a less variable. 

Best regards.

**Comment by benjycui** [comment]
Actually, you can override it by CSS selector now.

Or you can PR to add a LESS variable.

**Comment by afc163** [comment]
Maybe we can add a `tabBarStyle` prop?

**Comment by aaronplanell** [comment]
Thanks a lot @afc163 !!! :racehorse: How fast!!! :smile:

**Comment by afc163** [comment]
Will released in antd@2.8.0 by the end of February.
