### ISSUE TITLE
AutoComplete 使用 slate editor 作为自定义输入组件时无法通过鼠标点击调整光标位置

### ISSUE THREAD

**Issue by gwy15** [ant-design/ant-design#49677]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-itxh5b?file=demo.tsx)

### Steps to reproduce

在 https://stackblitz.com/edit/react-itxh5b?file=demo.tsx 中，点击输入部分后，通过左右键可以调整光标位置，但是无法通过鼠标点击调整光标位置。

### What is expected?

可以通过鼠标点击调整光标位置。

### What is actually happening?

无法通过鼠标点击调整光标位置。

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18 |
| System | macOS Sonoma 14.4 |
| Browser | 126 |

**Comment by gwy15** [comment]
@MadCcc 如果是 not planned，antd 请在文档中明确写上目前支持的自定义输入组件，或者写上自定义输入组件应该支持的事件(像 [Popconfirm的文档](https://ant.design/components/popconfirm-cn#%E6%B3%A8%E6%84%8F) ），目前的文档没有什么帮助性。

**Comment by wanpan11** [comment]
在 Slate 组件外套一层节点 可以解决 [demo](https://stackblitz.com/edit/react-itxh5b-2mqcyw?file=demo.tsx)，Slate 组件内部不是用的 input textarea 这些元素实现的（用的是是这个 contenteditable="true"）。AutoComplete 组件没有额外处理这种元素

![image](https://github.com/ant-design/ant-design/assets/38714194/6ea915d8-c536-4475-8d27-7c29a7ad7fa4)
