### ISSUE TITLE
【Form.Item】children render不渲染

### ISSUE THREAD

**Issue by a949066041** [ant-design/ant-design#49676]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-7vhjkf?file=demo.tsx,package.json,index.tsx)

### Steps to reproduce

Form.Item children 
添加函数
{(props) => <Input {...props} />}

### What is expected?

进行输入框渲染

### What is actually happening?

未渲染任何组件

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | window |
| Browser | chrome |

**Comment by zombieJ** [comment]
请关注一下控制台的 warning 信息，`renderProps` 不能和 `name` 一起使用：
<img width="530" alt="截屏2024-07-02 11 04 22" src="https://github.com/ant-design/ant-design/assets/5378891/762754e9-8e01-4753-8c5d-217f0e6bfe22">
