### ISSUE TITLE
Tabs 的 ConfigProvider   不生效

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#49679]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-vw6jfg?file=demo.tsx,index.html)

### Steps to reproduce

![image](https://github.com/ant-design/ant-design/assets/29728228/f7e5a8e9-13c8-4854-a1a8-0dcbc0daa970)

设置一个背景色好像没什么效果

### What is expected?

主题生效

### What is actually happening?

不生效

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18 |
| System | mac/windows |
| Browser | chrome |

**Comment by afc163** [comment]
cardBg 只针对 type="card" 的 Tabs 生效：https://stackblitz.com/edit/react-vw6jfg-nscmgd?file=demo.tsx,index.html
