### ISSUE TITLE
table virtual 开启 x轴滑动太快

### ISSUE THREAD

**Issue by 791060555** [ant-design/ant-design#49675]
### Reproduction link

[https://ant.design/components/table-cn](https://ant.design/components/table-cn)

### Steps to reproduce

官网案例，虚拟滚动水平滑动太快了，拖动计算有问题
table 开启 virtual

### What is expected?

拖动丝滑

### What is actually happening?

手动拖动太快了，没法滚动到具体的位置

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.2.0 |
| System | window |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
thx。
这个已经修复过了，官网没更新。得更一下。

**Comment by zombieJ** [comment]
已同步~

**Comment by 791060555** [comment]
我本地测试5.19还是很快，体验并不是很好

**Comment by su1924** [comment]
@zombieJ  我已经更新到5.19.1了，直接copy官网的代码下来还是不行，官网的倒是可以

**Comment by yoyo837** [comment]
删除lock文件和node_modules重新安装

**Comment by su1924** [comment]
@yoyo837 可以了，感谢大佬

**Comment by su1924** [comment]
我的场景有上百个横向字段，没虚拟前只是渲染慢，但上下左右滑都不卡，用了虚拟滚动渲染快了一点，但是纵向滚动很卡，横向不卡

**Comment by yoyo837** [comment]
上复现，开个issue
