### ISSUE TITLE
Ellipsis does not show when `onEllipsis` is used

### ISSUE THREAD

**Issue by tim-richter** [ant-design/ant-design#49670]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-fltuco?file=demo.tsx)

### Steps to reproduce

- use antd 5.18.1 or higher
- wrap Typography.Text component with a antd Button or Tag (other components probably produce the same result)
- set maxWidth/width on the wrapper component to simulate an ellipsis
- pass `onEllipsis` to the `ellipsis` prop from Typography.Text component

### What is expected?

the text should have an ellipsis because the wrapper component has a smaller width than the text

### What is actually happening?

the ellipsis does not show and the `onEllipsis` callback is not called

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.3.1 |
| System | NixOS |
| Browser | Version 125.0.6422.112 (Official Build) (64-bit) |

---
This is a regression to antd 5.18.0. You can test this in the provided stackblitz link. 5.18.0 works as expected, but 5.18.1 or higher shows the mentioned bug.

I suspect any of these changes from 5.18.1 to created this problem, but I could not pin point an exact line: https://github.com/ant-design/ant-design/pull/49221 and https://github.com/ant-design/ant-design/pull/49168

**Comment by MadCcc** [comment]
Fixed in v5.19.0
