### ISSUE TITLE
描述列表组件样式问题

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#49671]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-lpp4cb?file=demo.tsx)

### Steps to reproduce

查看 demo

### What is expected?

有右间距

### What is actually happening?

无右间距，挨在一起
![image](https://github.com/ant-design/ant-design/assets/7971419/bcbd2ba7-615b-4279-9cd6-28da77956174)

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
`paddingSM` would be ok

**Comment by crazyair** [comment]
> `paddingSM` would be ok

不是要 padding，是要 gap 的效果
