### ISSUE TITLE
expandedRowRender  加号 点击没有无效，并没有展开

### ISSUE THREAD

**Issue by lansefengxinzi** [ant-design/ant-design#4968]
<UserTable columns={columns} dataSource={columnsData}
                                               style={{backgroundColor: "white"}} scroll={{x: 1700}} pagination={pagination}
                                    onChange={tableChange} expandedRowRender={(record: any) => <p>{record.ua}</p>} rowKey="ui"/>

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by dhshen** [comment]
@lansefengxinzi 我之前也遇到过，应该是dataSource={columnsData}这个columnsData里面的对象没有key属性，加一个key属性就ok了

**Comment by afc163** [comment]
Close for no response.

**Comment by lansefengxinzi** [comment]
是缺少key 属性 ，谢谢

**Comment by motorguo** [comment]
@afc163 请问一定要依赖 key 么? 有些疑惑  通过 **react** 插件查看，发现其实每一条数据都是有添加 `key` 的
也有个 `rowKey`

**Comment by czy0729** [comment]
我今天都遇到了，这个自动使用dataSource里面的key不太好吧，就不能根据expandedRowRender里面组件的key来解决吗？
