### ISSUE TITLE
Select组件动态显示下拉选项的内容

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#4969]
需求是在每次点击Select组件显示下拉选项的时候，需要根据页面中的其它条件显示不同的下拉项，现在没有找到触发点。有什么方法或者建议吗？

**Comment by afc163** [comment]
What is your needs exactly? Could you give us more details about it?

**Comment by hansnow** [comment]
you'd better think in data-driven model, not event-driven model. According to your description, we assume that all info are stored in component's state, then what you need to do is just generate different Select.Option in component's render() method according to state and put these dynamic Select.Options into a `<Select></Select>` tag.

**Comment by zhulichao** [comment]
需求描述（这是类比的）：页面有两个Input，一个Select组件，每次点击Select的时候需要根据前两个Input进行数据的过滤，比如第一个Input输入的是中国，第二个Input输入的是北京，那我点击Select的时候只能显示北京的各个区名。
我现在能想到的方式是在两个Input发生变化的时候去修改Select对应的state值，但是感觉不太好，想最好在点击Select也要展示下拉列表的时候再去根据Input值修改state进行展示。

**Comment by benjycui** [comment]
Actually, you use case is similar to https://ant.design/components/select-cn/#components-select-demo-coordinate

**Comment by afc163** [comment]
> 在两个Input发生变化的时候去修改Select对应的state值

推荐你这么做。
