### ISSUE TITLE
Why is the default Header background black?

### ISSUE THREAD

**Issue by igalci** [ant-design/ant-design#49695]
### Reproduction link

[https://ant.design/components/layout](https://ant.design/components/layout)

### Steps to reproduce

The default background color of the Header is black. Why? shouldn't this only be in dark-mode?

I see the official Ant.design website made their header white...

### What is expected?

White header

### What is actually happening?

Black header

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
It's by design. You could override it with custom style.
