### ISSUE TITLE
5.19版本RangePicker组件选择的日期存在选中的日期与回填的日期不一致问题，官网例子可复现

### ISSUE THREAD

**Issue by 909288037** [ant-design/ant-design#49706]
### Reproduction link

[https://ant-design.antgroup.com/~demos/components-date-picker-demo-size](https://ant-design.antgroup.com/~demos/components-date-picker-demo-size)

### Steps to reproduce

重复选择几次日期即可复现

### What is expected?

正确回填选中的日期

### What is actually happening?

回填的日期不是选中的日期

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | react |
| System | mac |
| Browser | chrome |

---
回退到5.18.3版本没有问题

**Comment by zombieJ** [comment]
co'de'pencodepen 500 报错了，给个 Stackbliz？

<img width="736" alt="截屏2024-07-03 18 05 34" src="https://github.com/ant-design/ant-design/assets/5378891/b3954715-0e11-43f3-98ff-e15aff5a52d7">

**Comment by 909288037** [comment]
> co'de'pencodepen 500 报错，给个 Stackbliz？
> 
> <img alt="截屏2024-07-03 18 05 34" width="736" src="https://private-user-images.githubusercontent.com/5378891/345377948-b3954715-0e11-43f3-98ff-e15aff5a52d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDE0OTcsIm5iZiI6MTcyMDAwMTE5NywicGF0aCI6Ii81Mzc4ODkxLzM0NTM3Nzk0OC1iMzk1NDcxNS0wZTExLTQzZjMtOThmZi1lMTVhZmY1YTUyZDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMTAwNjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MThjMzQ2YmNmZDk3OWM1MGYwYTRjZTRjZjlkNWMyOTMxZjA0MzIxZWJmMTZiYjY0MjAxYjRjMTFkOTYzZTI5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p7g_JTfGtvn2tg39nMXN1UfxRoG-U4HDyxP9DRd7leI">

更新了，直接用的antd的分享地址https://ant-design.antgroup.com/~demos/components-date-picker-demo-size

**Comment by 909288037** [comment]
> 你好@909288037[。请提供antd@5.x](https://u.ant.design/codesandbox-repro)或[antd@4.x](https://u.ant.design/codesandbox-repro-4x)的 codesandbox 在线复刻版本，或提供最小化的 GitHub 仓库。标为 的 Issues `Need Reproduce`3 天内无动态将被关闭。
> 
> 你好@909288037，我们需要你提供一个在线的重现实示例以便我们帮你排查问题。你可以通过点击这里创建一个[antd@5.x](https://u.ant.design/codesandbox-repro)或[antd@4.x](https://u.ant.design/codesandbox-repro-4x)的codesandbox，或者提供一个最小化的GitHub仓库。3天内未跟进此问题将会被自动关闭。
> 
> > [什么是低温重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/b97631cde1534cb1d5ea925e54a031b9532bfec8154cdb0671e93e51790f66a7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

[https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-nhz98d?file=%2Findex.js](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-nhz98d?file=%2Findex.js)

https://github.com/ant-design/ant-design/assets/29726587/0a859b97-fc7d-4204-86d3-f6428574d545
