### ISSUE TITLE
[Descriptions] 内容溢出

### ISSUE THREAD

**Issue by jddxf** [ant-design/ant-design#49704]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-nbocqg?file=demo.tsx)

### Steps to reproduce

从 demo 中可以看到 Label2 的内容溢出了。

### What is expected?

内容不溢出

### What is actually happening?

内容溢出

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | * |
| System | * |
| Browser | * |

**Comment by iceweb1999** [comment]
先给`ant-descriptions-item-content`加个`overflow: hidden`，可以解决，它被拉伸了

**Comment by coding-ice** [comment]
先给ant-descriptions-item-content加个overflow: hidden，可以解决，它被拉伸了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/49707#issuecomment-2205746608
