### ISSUE TITLE
在 <Affix /> 内放置 <Image /> 和 <Anchor /> 报告 findDOMNode is deprecated

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#49719]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-bequtd?file=demo.tsx)

### Steps to reproduce

1. 使用 `<Affix />` 组件
2. 将 `<Image />` 和 `<Anchor />` 放入 `<Affix />` 组件里
3. 访问 Console 控制台查看报错

### What is expected?

Console 控制台没有报错

### What is actually happening?

Console 控制台报告三个错误：
1. FindDOMNode is deprecated and will be removed in the next major release.
2. Find more than one child node with `children` in ResizeObserver. Please use ResizeObserver.Collection instead.
3. SecurityError: Failed to read a named property 'addEventListener' from 'Window': Blocked a frame with origin "https://antd-reproduce-5x-bequtd.stackblitz.io" from accessing a cross-origin frame.

![屏幕截图 2024-07-04 151108](https://github.com/ant-design/ant-design/assets/46666511/ab55913e-37ca-47e3-a65e-42e878ac21a7)

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3 |
| System | Windows 11 |
| Browser | Edge 126.0.2592.87 |

**Comment by wanpan11** [comment]
应该这样  

```
    <Affix>
      <div>
        <Image />
        <Anchor />
      </div>
    </Affix>
```

这是原因 https://github.com/ant-design/ant-design/issues/48709#issuecomment-2179729456
