### ISSUE TITLE
spin

### ISSUE THREAD

**Issue by soguagirl** [ant-design/ant-design#4971]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by soguagirl** [comment]
antd:2.7.2
macos:10.12.3
chrome:56.0.2924.87 (64-bit);

Spin，当把内容内嵌到 Spin中之后，若子元素还有Spin，则子元素的Spin，会继承父级Spin的一切属性。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by soguagirl** [comment]
http://codepen.io/shengyong/pen/YNmqzL
