### ISSUE TITLE
Antd time range picker dropdown misalign with version >=5.16.5

### ISSUE THREAD

**Issue by Archana-SO** [ant-design/ant-design#49721]
### Reproduction link

[https://ant.design/~demos/time-picker-demo-status](https://ant.design/~demos/time-picker-demo-status)

### Steps to reproduce

1. Use format='HH:mm'
2. Click Start time
3. Click away from time range component
4. Click End time
![antd time range picker](https://github.com/ant-design/ant-design/assets/174688973/16bf54e9-f30c-4ba4-a6ab-08bb564f90be)

### What is expected?

Proper alignment of arrow pointing to the field (end time) and the dropdown should move with the arrow

### What is actually happening?

arrow pointing to the field (end time), but the dropdown does not.

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | >=17.0.0 <19.0.0 |
| System | Microsoft Windows 10 Enterprise |
| Browser | Chrome Version 126.0.6478.127 |

**Comment by zombieJ** [comment]
I can not reproduce this:
![Kapture 2024-07-04 at 15 56 59](https://github.com/ant-design/ant-design/assets/5378891/4214c314-01f6-4cb8-85eb-1ca6d350f432)

**Comment by Archana-SO** [comment]
First click on start time and Click away from time range picker  component and then select end time

**Comment by MadCcc** [comment]
Cannot reproduce in chrome, can you provide more details?
