### ISSUE TITLE
Datepicker when empty is not honoring the locale

### ISSUE THREAD

**Issue by kesavkolla** [ant-design/ant-design#4972]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: macOS
- Browser and its version: Chrome Version 58.0.3018.0 canary (64-bit)

####

Run the default code pen for demonstrating english locale.  By default it shows date picker with today date selected.  Click on clear icon to clear the date and then click on the component to select new date.  Now the months showing is not from selected locale.

#### Correct Behavior

The date selector should show the text in selected locale.

![image](https://cloud.githubusercontent.com/assets/274645/23128778/f98e917c-f734-11e6-9d59-12bc178d4303.png)

#### Date picker shows wrong locale

![image](https://cloud.githubusercontent.com/assets/274645/23128796/120f853a-f735-11e6-9cba-9a3e23f9584d.png)

#### Re-producible online demo

[Official Codepen](http://codepen.io/benjycui/pen/KgPZrE?editors=001l)

**Comment by benjycui** [comment]
Yep, in CodePen, moment in antd is different from moment that you import. So, when you set `moment.locale` by the moment you import, it won't affect moment in antd. As we discussed before @afc163 

But this will works fine when you use npm and webpack.
