### ISSUE TITLE
editable table 有些行会被遮挡显示不全

### ISSUE THREAD

**Issue by asevenm** [ant-design/ant-design#49722]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-typurz?file=index.css,demo.tsx)

### Steps to reproduce

请看链接

### What is expected?

显示正常

### What is actually happening?

有些被遮挡了

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18 |
| System | any |
| Browser | any |

**Comment by zombieJ** [comment]
遮挡指的是什么地方遮挡？截个图看看？

**Comment by asevenm** [comment]
![image](https://github.com/ant-design/ant-design/assets/22423693/622db2ee-7d4c-4cd5-845e-8850f9469ec6)
datasource 是有两条数据的

**Comment by asevenm** [comment]
这里是用virtual 和 scroll 属性之后出现了这个问题

**Comment by asevenm** [comment]
谢谢
