### ISSUE TITLE
DatePicker picker='month' 设置 disabledDate，选择第一个可选月份时，选取不了

### ISSUE THREAD

**Issue by coulis1018** [ant-design/ant-design#49724]
### Reproduction link

[https://ant.design/components/date-picker-cn#components-date-picker-demo-mask](https://ant.design/components/date-picker-cn#components-date-picker-demo-mask)

### Steps to reproduce

官方文档中的禁用月份案例可以复现。设置picker="month"，设置禁用当前日期之前的月份。点击可选的当前月，无法触发onChange事件

### What is expected?

可以选中未被禁用的任意日期。

### What is actually happening?

第一位不能被选中

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 17 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
我推测应该是你 `disabledDate` 里没有关注 `info` 参数里的类型，它会告诉你当前禁用是否是 `month`。但是没有重现代码所以仅仅是推测。

**Comment by coulis1018** [comment]
> 我推测应该是你 `disabledDate` 里没有关注 `info` 参数里的类型，它会告诉你当前禁用是否是 `month`。但是没有重现代码所以仅仅是推测。

https://stackblitz.com/edit/react-hypote?file=demo.tsx
这里是复现的链接，按照文档写法设置今天及之前的日期不可选，但是结果是当前月没被禁用但也无法选择，注释中是我目前找到能绕过问题的写法

**Comment by zombieJ** [comment]
如果你是月份选择器，应该对月份进行判断而不是通过当前天来判断。这相当于 `disabledDate` 里提供的月份判断有时候告知当前月可选，有时候又告知不可选，自然 DatePicker 的选择行为也就混乱了。

**Comment by LonelySteve** [comment]
@zombieJ 我想请教一下这个问题如果在 v4 里该怎么解决？似乎可以利用 onPanelChange 来跟踪一下当前面板类型，不过初始状态就需要开发者来把握了。
