### ISSUE TITLE
Form disabled 可以支持 NamePath[] 设置多个表单字段禁用

### ISSUE THREAD

**Issue by baiwumm** [ant-design/ant-design#49725]
### What problem does this feature solve?

公司目前业务有个需求，编辑状态下有很多的分步表单，但该需求只能修改其中一个字段，其它字段需要禁用并且可以查看，目前我只能透传给子组件一个一个设置

### What does the proposed API look like?

希望 disabled 可以支持设置成 NamePath[]，类型：boolean | NamePath[]，当我设置 disabled={['field1','field2']} 的时候，表单应该禁用这两个子项

**Comment by MadCcc** [comment]
这不是我们提供 disabled 的初衷，你可以自行封装来实现业务上需要的效果。
