### ISSUE TITLE
popover用()=>ReactNode的形式返回值样式异常

### ISSUE THREAD

**Issue by Zeyull** [ant-design/ant-design#49731]
### Reproduction link

[https://ant-design.antgroup.com/components/popover-cn](https://ant-design.antgroup.com/components/popover-cn)

### Steps to reproduce

配置 popover组件的content内容为回调函数，且返回null，<Popover content={()=> null}>

### What is expected?

不弹出弹窗

### What is actually happening?

弹出空弹窗

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.0.33 |
| System | win11 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Popover 无论是不是 `renderProps` 都会弹出窗口，可以使用 `open` 来受控是否需要展示内容哈~

**Comment by Zeyull** [comment]
> Popover 无论是不是 `renderProps` 都会弹出窗口，可以使用 `open` 来受控是否需要展示内容哈~

如果是<Popover content={(null}>，那么就不会弹出窗口。
