### ISSUE TITLE
Modal部分transitionName失效

### ISSUE THREAD

**Issue by CNFeffery** [ant-design/ant-design#49733]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-7qcq3d?file=demo.js)

### Steps to reproduce

复现链接中所有的过渡动画类型（transitionName），在antd v4版本中均可生效，但在antd v5版本中，当transitionName设置为'ant-zoom-big'、'ant-zoom-big-fast'、'ant-slide-left'、'ant-slide-right'、'ant-move-left'、'ant-move-right'时，动画失效且Modal打开后无法关闭

### What is expected?

相关动画类型恢复正常

### What is actually happening?

相关动画类型异常

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | ^18.0.0 |
| System | win11 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
这些 `transitionName` 是 antd v4 的内部过渡动画，并不保证稳定提供，在 v4 中也不应该直接使用。当你使用 `transitionName` 时，应该自行实现相关动画 `keyframe` 哈~
