### ISSUE TITLE
Pagination组件total配置无效

### ISSUE THREAD

**Issue by zptime** [ant-design/ant-design#49734]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-7p1rj5?file=demo.tsx)

### Steps to reproduce

// 直接安装后正常使用

import { Pagination } from "antd";
<Pagination
        simple
        total={30}
        current={2}
        showTotal={(total) => `Total：${total}`}
      />
      <Pagination
        simple
        total={50}
        current={2}
        showTotal={(total) => `Total：${total}`}
      />
      <Pagination
        simple
        total={62}
        current={2}
        showTotal={(total) => `Total：${total}`}
      />
      <Pagination
        simple
        total={55}
        current={2}
        showTotal={(total) => `Total：${total}`}
      />

### What is expected?

Total:30   2/30
Total:50   2/50
Total:62   2/62
Total:55   2/55

### What is actually happening?

实际展示页码变成 total/10 了，而且向上取整

Total:30   2/3
Total:50   2/5
Total:62   2/7
Total:55   2/6   

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | macOS |
| Browser | Google Chrome  126.0.6478.127 |

**Comment by Wxh16144** [comment]
有没有可能是不小心把 `total` 和 `pageTotal` 搞混了？

**Comment by afc163** [comment]
目前的展示符合预期，默认 pageSize 是 10 。
