### ISSUE TITLE
Layout vs Content with Sider Documentation

### ISSUE THREAD

**Issue by cannin** [ant-design/ant-design#4973]
Is Layout and Content interchangeable? In the [Layout documentation](https://ant.design/components/layout/), under Basic Structure this overall Layout is given:  

    <Layout>
      <Sider>Sider</Sider>
      <Content>
        <Header>Header</Header>
        <Content>Content</Content>
        <Footer>Footer</Footer>
      </Content>
    </Layout>

Under Custom Trigger, this is given:

    <Layout>
      <Sider
        trigger={null}
        collapsible
        collapsed={this.state.collapsed}
      >
      ...
      </Sider>
      <Layout>
        <Header style={{ background: '#fff', padding: 0 }}>
          <Icon
            className="trigger"
            type={this.state.collapsed ? 'menu-unfold' : 'menu-fold'}
            onClick={this.toggle}
          />
        </Header>
        <Content style={{ margin: '24px 16px', padding: 24, background: '#fff', minHeight: 280 }}>
          Content
        </Content>
      </Layout>
    </Layout>

It seems that Layout and Content can be interchanged, but I'm not sure about the side effects. 

What I'm trying to achieve is the above overall layout, but with a fixed header. When I simply add position: fixed, the header is fixed, but the header is shorter than width: 100% (only big enough to fill any nested content). It looks like the [Sider has a width set, 200px](https://github.com/ant-design/ant-design/blob/7d3cbfd9d99de7a5d3d01b308d9a26118491fce4/components/layout/Sider.tsx), but the sibling Layout/Content with the Header and Content do not have a width set. I'm not sure if there is a workaround.

**Comment by ddcat1115** [comment]
`Layout` and `Content` are not interchangeable, when you need to wrap `Header` `Footer` and etc, you should use `Layout`. Sorry for the documentation bug and I'll fix it ~ 

And the Layout component is designed for some certain kinds of page layouts, by now it can't support those which has fixed items. Maybe you need to add some styles to achieve this.
