### ISSUE TITLE
是否可以将DisabledContext暴露出来？

### ISSUE THREAD

**Issue by zzcwzhang** [ant-design/ant-design#49736]
### What problem does this feature solve?

在Form中使用自定义的组件，使用时无法拿到通过Form设置的disabled状态，是否可以把DisabledContext，让自定义的组件可以实现Form中的禁用功能

### What does the proposed API look like?

可以
```javascript
import { DisabledContext } from 'antd';
``` 
或者可以从antd的某个子目录获取，目前尝试了`import { DisabledContext } from 'antd/es/config-provider/DisabledContext';`
和`import { DisabledContext } from 'antd/lib/config-provider/DisabledContext';`
中获取的都不好用

**Comment by MadCcc** [comment]
可以使用 `ConfigProvider.useConfig`

```
import { ConfigProvider } from 'antd';

export default () => {
  const { componentDisabled } = ConfigProvider.useConfig();

  // ....
}
```

**Comment by zzcwzhang** [comment]
> 可以使用 `ConfigProvider.useConfig`
> 
> ```
> import { ConfigProvider } from 'antd';
> 
> export default () => {
>   const { componentDisabled } = ConfigProvider.useConfig();
> 
>   // ....
> }
> ```

是否可以把value也暴露出来，因为有时候自定义组件需要判断value是否为空来显示默认值。我主要用在自定义上传组件，当disabled状态后，value也是空的状态下，显示一片空白。所以我先根据value是否存在来显示一段提示文字

**Comment by hardmanhong** [comment]
额，似乎只有5.X才能使用这个 useConfig ，4.x 有方法在组件内拿到配置信息吗

**Comment by GrayYoung** [comment]
真是太恶心了，升级要改很多，不升级又不能用。
