### ISSUE TITLE
Steps with icon fail to dynamically adjust after resizing the icon size as well as the description

### ISSUE THREAD

**Issue by Dmaziyo** [ant-design/ant-design#49742]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-k2bd6x?file=demo.tsx)

### Steps to reproduce

set the icon size

### What is expected?

Steps with icons dynamically adjust spacing between the progress bar

### What is actually happening?

it didn't

| Environment | Info |
| --- | --- |
| antd | 5.19.1 |
| React | 18.3.1 |
| System | window |
| Browser | chrome |

**Comment by MadCcc** [comment]
If you want to place the icon right at the center, you could adjust by setting styles of this icon.
Currently it is top-left aligned.
