### ISSUE TITLE
form的 onValuesChange 只能在包装组件里使用吗？

### ISSUE THREAD

**Issue by icepoint0** [ant-design/ant-design#4974]
如题，我想单纯的通过 <Form onValuesChange={}> 似乎不可行？文档中也没有明确提及到这个用法？

**Comment by benjycui** [comment]
I think this demo is clear enough: https://ant.design/components/form/#components-form-demo-global-state

It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: https://github.com/ant-design/ant-design/issues/4897
