### ISSUE TITLE
submenu on table filter does not work well

### ISSUE THREAD

**Issue by rqzheng2015** [ant-design/ant-design#4975]
#### Environment(required)

- antd version:2.7.2
- OS and its version:macOS 10.12.3
- Browser and its version:Chrome v56

#### What did you do? Please provide steps to re-produce your problem.
I tested the demo table on https://ant.design/components/table/ , and found out that submenu on filter options did not work as expected

#### What do you expected?
make the filter submenu visible.

#### What happen?

Style is not as expected.
![image](https://cloud.githubusercontent.com/assets/13147584/23148210/4c619256-f81f-11e6-86df-1261b9752557.png)
#### Re-producible online demo
https://ant.design/components/table/

**Comment by afc163** [comment]
Style breaks after https://github.com/ant-design/ant-design/issues/4916
