### ISSUE TITLE
codebox styles broken

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#49760]
<img width="457" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/e865d09d-ac28-49fa-b5db-a18d353957c4">

图标明显对不齐。

**Comment by li-jia-nan** [comment]
看了一下，需要给 `typography-copy-icon-only` 的父元素加上 `line-height: 0`，这样的话需要把 `icon-only` 这个 className 移到父元素上，有点麻烦

**Comment by MadCcc** [comment]
左边那个按钮之前用来提示代码区域可以编辑的，现在感觉可以去掉了

**Comment by li-jia-nan** [comment]
- #49814
