### ISSUE TITLE
关于2.7.1版本，表格的scroll属性问题

### ISSUE THREAD

**Issue by FANUP** [ant-design/ant-design#4976]
- antd version:2.7.1
- OS and its version:window7
- Browser and its version:Chrome 55.0.2883.87 m

#### What do you expected?
antd 版本 2.6.4 升级到 2.7.1 后 ，表格列设置不同的百分比，表格属性设为 scroll={{x: 1300}}。在2.6.4上，当表格大于1300px时，表格自适应扩大，而在 2.7.1 ，当表格大于1300px时，表格没有自适应扩大。而是固定表格宽度为1300px。请问要如何解决才能使2.7.1版本表格也自适应？
如图所示
2.6.4
![image](https://cloud.githubusercontent.com/assets/22515562/23148526/48cc7bae-f821-11e6-83ea-00c93e677add.png)
2.7.1
![image](https://cloud.githubusercontent.com/assets/22515562/23148534/57cdf056-f821-11e6-9a3a-d210eee6a210.png)

#### Re-producible online demo
http://codepen.io/anon/pen/EZqPvP

**Comment by afc163** [comment]
I can't find any problem in you codepen link.

**Comment by afc163** [comment]
Reopen it if you can provide another re-producible online demo.

**Comment by zuiidea** [comment]
确实有问题，2.7.1上
![image](https://cloud.githubusercontent.com/assets/16070518/23244241/d7a52918-f9be-11e6-91c5-fc3acecd8074.png)
![image](https://cloud.githubusercontent.com/assets/16070518/23244262/ff135f1a-f9be-11e6-9c8a-bcf4a1fffa14.png)
这个节点上被设置了`width`的属性，讲道理应该是`min-width`

**Comment by afc163** [comment]
<img width="230" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23245438/723c7df2-f9c7-11e6-8d03-19415e08872b.png">

There is a `min-width: 100%`.

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by zuiidea** [comment]
![image](https://cloud.githubusercontent.com/assets/16070518/23246622/fcca451e-f9cf-11e6-85eb-7f7df78bc606.png)
本地的代码已经精简成这样和这里http://codepen.io/zuiidea/pen/OpLYee几乎一样，但是本地还是出现问题了，其原因是没有`ant-table-scroll`这层`div`，导致table没有`min-width:100%`这个样式

**Comment by afc163** [comment]
我上面疑惑的地方也是这里，为啥会没有 `ant-table-scroll`。

我看楼主和你的 codepen，包括 http://zuiidea.com/antd-admin/#/users?_k=dh613l 里都有 `ant-table-scroll`。

**Comment by afc163** [comment]
我大概知道问题出在哪了，感谢 @zuiidea 分析。

https://github.com/react-component/table/commit/0dca8492715bcf3c6c751a319f0298e6b81e29ce

**Comment by zuiidea** [comment]
我也很奇怪，你现在重新刷一下http://zuiidea.com/antd-admin/#/users?_k=48ea8x，这里复现了，刚刚是那里用的前面的版本

**Comment by afc163** [comment]
已经在 rc-table@5.2.12 修复了，各位重新安装 node_modules 即可。
