### ISSUE TITLE
Form.Item 的 validateTrigger 能否指定为 当前form的其他值，即在 当前form的其他值 改变时校验？

### ISSUE THREAD

**Issue by nqsjd178559344** [ant-design/ant-design#49779]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-7jfc3i?file=demo.tsx)

### Steps to reproduce

1. field输入111
2. value输入111
3. 观察是否 value 校验通过

### What is expected?

validateTrigger 既能 在自身onChange时触发校验，又能在 当前form的其他值 改变时校验

### What is actually happening?

只能自身onChange时触发校验

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | ^18.3.1 |
| System | win10 |
| Browser | 123.0.6312.124（正式版本） （64 位） |

**Comment by afc163** [comment]
你需要的是 `dependencies`。

**Comment by nqsjd178559344** [comment]
> 你需要的是 `dependencies`。

你先别关,我试了一下,还是不能做到重新触发校验啊

**Comment by yoyo837** [comment]
试了 `dependencies` 还有问题，可以携带复现开一个新的issue.
