### ISSUE TITLE
`List` wrong index for paginated data

### ISSUE THREAD

**Issue by vojty** [ant-design/ant-design#49770]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-9epply?file=demo.tsx)

### Steps to reproduce

Click on page 2

### What is expected?

The `index` is added as a prefix to each row's title. On the second page, there should be `3` and `4`

### What is actually happening?

`index` is reset for each page and starts from `0` again

| Environment | Info |
| --- | --- |
| antd | 5.19.1 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome |

---
`index` should be either fixed or there should be an additional parameter to represent the absolute index

**Comment by zombieJ** [comment]
The `index` is the current render list `index`, not all of the index of data list.
