### ISSUE TITLE
分页器Pagination bug

### ISSUE THREAD

**Issue by cainiaobo** [ant-design/ant-design#4977]
#### Environment(required)

- antd version:2.0.1
- OS and its version: windows 10
- Browser and its version:chrome 56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

使用分页器自定义pageSizeOptions，（e.g.['10', '20', '30', '40']），当第一个不为10时，分页器默认显示10；（e.g.['20', '30', '40', '50']）设置为此时，默认值为10而不是20/page

**Comment by afc163** [comment]
目前就是这么设计的，pageSizeOptions 不控制 pageSize，你需要用 pageSize 去指定。

https://github.com/ant-design/ant-design/issues/4959#issuecomment-281013141
