### ISSUE TITLE
Button组件autoInsertSpace不生效

### ISSUE THREAD

**Issue by Jonclex** [ant-design/ant-design#49783]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x)

### Steps to reproduce

 <Button type="primary" icon={<PlusCircleOutlined />} autoInsertSpace>
            新增
          </Button>
Button组件中添加icon，添加 autoInsertSpace

### What is expected?

 <Button type="primary" icon={<PlusCircleOutlined />} autoInsertSpace>
            新增
          </Button>
Button组件中添加icon，添加autoInsertSpace之后，汉字之间出现空格

### What is actually happening?

 <Button type="primary" icon={<PlusCircleOutlined />} autoInsertSpace>
            新增
          </Button>
Button组件中添加icon，添加autoInsertSpace之后，汉字之间没有出现空格

| Environment | Info |
| --- | --- |
| antd | 5.18.3 |
| React | 18.3.1 |
| System | win |
| Browser | edge |

**Comment by zombieJ** [comment]
设计如此哈，盘古之白只有二个纯中文文字才会添加。设置图标后是不会添加的。如果有需要可以考虑自行 HOC 添加相关逻辑。

**Comment by li-jia-nan** [comment]
`autoInsertSpace` 就是会出现空格，这是符合预期的行为，如果要去掉空格，可以设置 `autoInsertSpace={false}`
