### ISSUE TITLE
upload 组件defaultFileList 和 fileList使用问题

### ISSUE THREAD

**Issue by huyansheng3** [ant-design/ant-design#4979]
#### Environment(required)

- antd version: 2.6.0
- OS and its version: mac os 
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.

将已存在的图片list作为 defaultFileList 属性传入， 将 this.state.photoList 作为 fileList属性传入，结果默认图片无法展示。

#### What do you expected?

默认图片可以展示，之后上传的图片也能正常显示。

#### What happen?
![image](https://cloud.githubusercontent.com/assets/11534583/23152232/8c864e1e-f83b-11e6-87f8-992dfc70a439.png)
应该是此处判断为空不正确，!![] 为 true。
不确定官方期望的defaultFileList 和 fileList两种属性的用途与我期望一致。
defaultFileList 传入此前已经上传过的文件列表，fileList 用于维护文件列表。

ps: 
已通过设置   this.state.photoList 为 null 折中实现

**Comment by afc163** [comment]
You shouldn't use `defaultFileList` and `fileList` both.

Read more about it: http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by huyansheng3** [comment]
多谢，受控组件用 value，非受控组件用 defaultValue。
顺便问下，upload 组件应该不支持拖拽排序吧。 有后续支持的计划的吗？

**Comment by afc163** [comment]
目前没有计划。
