### ISSUE TITLE
When I first set the column to an array with a length, the defaultSortOrder does not take effect.

### ISSUE THREAD

**Issue by yuqimao854** [ant-design/ant-design#49799]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ajnpb6?file=demo.tsx)

### Steps to reproduce

click add column button,and the age column defaultSortOrder is not working.

### What is expected?

I want to know why the defaultSortOrder does not take effect after the column is changed.

### What is actually happening?

The defaultSortOrder does not take effect after the column is changed.

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
defaultXxx only works on first render. See https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultvalue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88

**Comment by yuqimao854** [comment]
`const [newColumn, setNewColumn] = useState(columns);`
Add columns as  default value will make defaultSortOrder working,but why when column changed,the defaultSortOrder not working?

Antd source code use a hook in Table component. I think when columns changed, sortStates will also change.

`  const [transformSorterColumns, sortStates, sorterTitleProps, getSorters] = useSorter<RecordType>({
    prefixCls,
    mergedColumns,
    onSorterChange,
    sortDirections: sortDirections || ['ascend', 'descend'],
    tableLocale,
    showSorterTooltip,
  });`

**Comment by yuqimao854** [comment]
> `const [newColumn, setNewColumn] = useState(columns);` Add columns as default value will make defaultSortOrder working,but why when column changed,the defaultSortOrder not working?
> 
> Antd source code use a hook in Table component. I think when columns changed, sortStates will also change.
> 
> ` const [transformSorterColumns, sortStates, sorterTitleProps, getSorters] = useSorter<RecordType>({ prefixCls, mergedColumns, onSorterChange, sortDirections: sortDirections || ['ascend', 'descend'], tableLocale, showSorterTooltip, });`

I have not change defutal value
@afc163

**Comment by yuqimao854** [comment]
> defaultXxx only works on first render. See https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultvalue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88

I have not change defutalXXX， I just change columns
