### ISSUE TITLE
Popover除了点击外部,能否考虑提供控制显隐的prop

### ISSUE THREAD

**Issue by skyblue** [ant-design/ant-design#498]

**Comment by benjycui** [comment]
你需要实现的交互方式是？

**Comment by skyblue** [comment]
![image](https://cloud.githubusercontent.com/assets/248937/11055802/ade9ddde-87b5-11e5-8042-c272943f44eb.png)
在popover里放表单, 表单保存完成或点击取消的时候关闭popover

**Comment by benjycui** [comment]
@skyblue 不考虑 [Modal](http://ant.design/components/modal/)?

@afc163 感觉增加这种属性，会和 `trigger` 有冲突。

**Comment by afc163** [comment]
是支持的，可能文档中没有写全。可以参考这个例子：http://ant.design/components/popover/#demo-control

**Comment by woodccc** [comment]
that's so smart, really great！
