### ISSUE TITLE
在Modal内的tabs accessKey不会被更新选项

### ISSUE THREAD

**Issue by CarbonPool** [ant-design/ant-design#49806]
### Reproduction link

[https://github.com/CarbonPool/antd_tabs_error_report](https://github.com/CarbonPool/antd_tabs_error_report)

### Steps to reproduce

每次点击按钮设置modal open为显示，modal内有tabs选项卡

### What is expected?

每次点击显示modal的自定义函数会重置tabs的accessKey state，tabs始终第一个tab显示

### What is actually happening?

modal每次显示，tabs依然是上一个选项卡

| Environment | Info |
| --- | --- |
| antd | 5.19.1 |
| React | 18 |
| System | windows11 22631 |
| Browser | chrome 126 |

---
modal已添加forceRender

**Comment by MadCcc** [comment]
你是不是指 `activeKey`?

**Comment by CarbonPool** [comment]
> 你是不是指 `activeKey`?

确定有效，我看语法补充个accessKey没有注意到这个，但是文档又没有写accessKey，弄混了，解决了
