### ISSUE TITLE
Affix onChange bug

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#4980]
`<Affix onChange={this.onFilterFixedChange}>
         <div><Checkbox onChange={...do something} /></div>
</Affix>`
The 'onChange' in Checkbox propagates to Affix.Shouldn't rename 'onChange' in Affix?

**Comment by benjycui** [comment]
Actually, name is OK.

But we should not pass `onChange` to `div`, and should remove it from [here](https://github.com/ant-design/ant-design/blob/54dde4f5bc07286ec2a71af92c619ec6560b0159/components/affix/index.tsx#L225).

**Comment by benjycui** [comment]
Are you interesting in trying to PR to fix this? Thanks 😄
