### ISSUE TITLE
I have not change defutalXXX， I just change columns.   https://github.com/ant-design/ant-design/issues/49799

### ISSUE THREAD

**Issue by yuqimao854** [ant-design/ant-design#49800]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ajnpb6?file=demo.tsx)

### Steps to reproduce

click add column button,and the age column defaultSortOrder is not working.

### What is expected?

const [newColumn, setNewColumn] = useState(columns); Add columns as default value will make defaultSortOrder working,but why when column changed,the defaultSortOrder not working?

Antd source code use a hook in Table component. I think when columns changed, sortStates will also change.

 const [transformSorterColumns, sortStates, sorterTitleProps, getSorters] = useSorter<RecordType>({ prefixCls, mergedColumns, onSorterChange, sortDirections: sortDirections || ['ascend', 'descend'], tableLocale, showSorterTooltip, });

### What is actually happening?

The defaultSortOrder does not take effect after the column is changed.

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
defutalXxx only works on first render.

**Comment by afc163** [comment]
GPT-4o 的回答：

> antd 中，Table 定义了 defaultSortOrder，columns 为空，点击按钮更新了 columns，此时 defaultSortOrder 不生效，为什么？如何解决？

在 Ant Design (antd) 的 Table 组件中，当你定义了 `defaultSortOrder` 并且 `columns` 为空，然后通过按钮更新了 `columns`，如果 `defaultSortOrder` 没有生效，可能是因为 `defaultSortOrder` 仅在组件初始化时生效。

`defaultSortOrder` 是一种默认的排序状态，它在 Table 组件首次渲染时生效，但如果在后续更新中修改 `columns` 属性，它不会重新应用。因此，在更新 `columns` 时需要确保排序状态也随之更新。

以下是一个可能的解决方案：你可以在更新 `columns` 的同时设置 Table 的 `sorter` 状态。

### 示例代码

```jsx
import React, { useState } from 'react';
import { Table, Button } from 'antd';

const App = () => {
  const [columns, setColumns] = useState([
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: 'Age',
      dataIndex: 'age',
      key: 'age',
    },
    {
      title: 'Address',
      dataIndex: 'address',
      key: 'address',
    },
  ]);

  const [data, setData] = useState([
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      address: 'New York No. 1 Lake Park',
    },
    {
      key: '2',
      name: 'Jim Green',
      age: 42,
      address: 'London No. 1 Lake Park',
    },
    {
      key: '3',
      name: 'Joe Black',
      age: 32,
      address: 'Sydney No. 1 Lake Park',
    },
  ]);

  const updateColumns = () => {
    setColumns([
      {
        title: 'Name',
        dataIndex: 'name',
        key: 'name',
        sorter: (a, b) => a.name.localeCompare(b.name),
        defaultSortOrder: 'ascend',
      },
      {
        title: 'Age',
        dataIndex: 'age',
        key: 'age',
        sorter: (a, b) => a.age - b.age,
      },
      {
        title: 'Address',
        dataIndex: 'address',
        key: 'address',
      },
    ]);
  };

  return (
    <div>
      <Button onClick={updateColumns}>Update Columns</Button>
      <Table columns={columns} dataSource={data} />
    </div>
  );
};

export default App;
```

在这个示例中，`updateColumns` 函数被调用时，新的 `columns` 设置了 `defaultSortOrder` 和 `sorter`。这样可以确保在更新 `columns` 时，默认排序状态也被重新应用。

**Comment by afc163** [comment]
你说得对。使用受控模式可以确保在任何时候都能精确地控制表格的排序状态。

下面是使用受控模式的示例代码：

```jsx
import React, { useState } from 'react';
import { Table, Button } from 'antd';

const App = () => {
  const [sorter, setSorter] = useState({
    order: 'ascend',
    field: 'name',
    columnKey: 'name'
  });

  const [columns, setColumns] = useState([
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      sorter: true,
      sortOrder: sorter.field === 'name' && sorter.order,
    },
    {
      title: 'Age',
      dataIndex: 'age',
      key: 'age',
      sorter: true,
      sortOrder: sorter.field === 'age' && sorter.order,
    },
    {
      title: 'Address',
      dataIndex: 'address',
      key: 'address',
    },
  ]);

  const [data, setData] = useState([
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      address: 'New York No. 1 Lake Park',
    },
    {
      key: '2',
      name: 'Jim Green',
      age: 42,
      address: 'London No. 1 Lake Park',
    },
    {
      key: '3',
      name: 'Joe Black',
      age: 32,
      address: 'Sydney No. 1 Lake Park',
    },
  ]);

  const handleTableChange = (pagination, filters, sorter) => {
    setSorter(sorter);
  };

  const updateColumns = () => {
    setColumns([
      {
        title: 'Name',
        dataIndex: 'name',
        key: 'name',
        sorter: true,
        sortOrder: sorter.field === 'name' && sorter.order,
      },
      {
        title: 'Age',
        dataIndex: 'age',
        key: 'age',
        sorter: true,
        sortOrder: sorter.field === 'age' && sorter.order,
      },
      {
        title: 'Address',
        dataIndex: 'address',
        key: 'address',
      },
    ]);
  };

  return (
    <div>
      <Button onClick={updateColumns}>Update Columns</Button>
      <Table
        columns={columns}
        dataSource={data}
        onChange={handleTableChange}
        pagination={false}
      />
    </div>
  );
};

export default App;
```

### 关键点

1. **受控模式**：通过维护 `sorter` 状态来控制表格的排序状态，并将其传递给 `columns`。
2. **`handleTableChange` 方法**：在表格排序或过滤发生变化时，更新 `sorter` 状态。
3. **在更新 `columns` 时设置 `sortOrder`**：确保在每个列的 `sortOrder` 中根据当前 `sorter` 状态进行设置。

这样，当你点击按钮更新 `columns` 时，表格的排序状态将保持一致。

---

你也可以在更新 `columns` 后再渲染 `Table` 组件。这种方法可以确保 `defaultSortOrder` 生效，因为 `Table` 组件在更新 `columns` 后才会被渲染。以下是一个示例：

```jsx
import React, { useState } from 'react';
import { Table, Button } from 'antd';

const App = () => {
  const [columns, setColumns] = useState([]);
  const [data, setData] = useState([
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      address: 'New York No. 1 Lake Park',
    },
    {
      key: '2',
      name: 'Jim Green',
      age: 42,
      address: 'London No. 1 Lake Park',
    },
    {
      key: '3',
      name: 'Joe Black',
      age: 32,
      address: 'Sydney No. 1 Lake Park',
    },
  ]);

  const updateColumns = () => {
    setColumns([
      {
        title: 'Name',
        dataIndex: 'name',
        key: 'name',
        sorter: (a, b) => a.name.localeCompare(b.name),
        defaultSortOrder: 'ascend',
      },
      {
        title: 'Age',
        dataIndex: 'age',
        key: 'age',
        sorter: (a, b) => a.age - b.age,
      },
      {
        title: 'Address',
        dataIndex: 'address',
        key: 'address',
      },
    ]);
  };

  return (
    <div>
      <Button onClick={updateColumns}>Update Columns</Button>
      {columns.length > 0 && (
        <Table columns={columns} dataSource={data} pagination={false} />
      )}
    </div>
  );
};

export default App;
```

### 关键点

1. **初始 `columns` 为空数组**：在初始状态下，`columns` 被设置为空数组，因此 Table 组件不会被渲染。
2. **更新 `columns` 后渲染 `Table`**：当 `columns` 被更新时，`Table` 组件才会被渲染，此时 `defaultSortOrder` 生效。
3. **条件渲染 `Table` 组件**：使用条件渲染，确保只有在 `columns` 被更新后才渲染 `Table` 组件。

这种方法简单且有效，确保在更新 `columns` 后默认排序状态能够生效。

**Comment by yuqimao854** [comment]
> 你说得对。使用受控模式可以确保在任何时候都能精确地控制表格的排序状态。
> 
> 下面是使用受控模式的示例代码：
> 
> ```js
> import React, { useState } from 'react';
> import { Table, Button } from 'antd';
> 
> const App = () => {
>   const [sorter, setSorter] = useState({
>     order: 'ascend',
>     field: 'name',
>     columnKey: 'name'
>   });
> 
>   const [columns, setColumns] = useState([
>     {
>       title: 'Name',
>       dataIndex: 'name',
>       key: 'name',
>       sorter: true,
>       sortOrder: sorter.field === 'name' && sorter.order,
>     },
>     {
>       title: 'Age',
>       dataIndex: 'age',
>       key: 'age',
>       sorter: true,
>       sortOrder: sorter.field === 'age' && sorter.order,
>     },
>     {
>       title: 'Address',
>       dataIndex: 'address',
>       key: 'address',
>     },
>   ]);
> 
>   const [data, setData] = useState([
>     {
>       key: '1',
>       name: 'John Brown',
>       age: 32,
>       address: 'New York No. 1 Lake Park',
>     },
>     {
>       key: '2',
>       name: 'Jim Green',
>       age: 42,
>       address: 'London No. 1 Lake Park',
>     },
>     {
>       key: '3',
>       name: 'Joe Black',
>       age: 32,
>       address: 'Sydney No. 1 Lake Park',
>     },
>   ]);
> 
>   const handleTableChange = (pagination, filters, sorter) => {
>     setSorter(sorter);
>   };
> 
>   const updateColumns = () => {
>     setColumns([
>       {
>         title: 'Name',
>         dataIndex: 'name',
>         key: 'name',
>         sorter: true,
>         sortOrder: sorter.field === 'name' && sorter.order,
>       },
>       {
>         title: 'Age',
>         dataIndex: 'age',
>         key: 'age',
>         sorter: true,
>         sortOrder: sorter.field === 'age' && sorter.order,
>       },
>       {
>         title: 'Address',
>         dataIndex: 'address',
>         key: 'address',
>       },
>     ]);
>   };
> 
>   return (
>     <div>
>       <Button onClick={updateColumns}>Update Columns</Button>
>       <Table
>         columns={columns}
>         dataSource={data}
>         onChange={handleTableChange}
>         pagination={false}
>       />
>     </div>
>   );
> };
> 
> export default App;
> ```
> 
> ### 关键点
> 1. **受控模式**：通过维护 `sorter` 状态来控制表格的排序状态，并将其传递给 `columns`。
> 2. **`handleTableChange` 方法**：在表格排序或过滤发生变化时，更新 `sorter` 状态。
> 3. **在更新 `columns` 时设置 `sortOrder`**：确保在每个列的 `sortOrder` 中根据当前 `sorter` 状态进行设置。
> 
> 这样，当你点击按钮更新 `columns` 时，表格的排序状态将保持一致。
> 
> 你也可以在更新 `columns` 后再渲染 `Table` 组件。这种方法可以确保 `defaultSortOrder` 生效，因为 `Table` 组件在更新 `columns` 后才会被渲染。以下是一个示例：
> 
> ```js
> import React, { useState } from 'react';
> import { Table, Button } from 'antd';
> 
> const App = () => {
>   const [columns, setColumns] = useState([]);
>   const [data, setData] = useState([
>     {
>       key: '1',
>       name: 'John Brown',
>       age: 32,
>       address: 'New York No. 1 Lake Park',
>     },
>     {
>       key: '2',
>       name: 'Jim Green',
>       age: 42,
>       address: 'London No. 1 Lake Park',
>     },
>     {
>       key: '3',
>       name: 'Joe Black',
>       age: 32,
>       address: 'Sydney No. 1 Lake Park',
>     },
>   ]);
> 
>   const updateColumns = () => {
>     setColumns([
>       {
>         title: 'Name',
>         dataIndex: 'name',
>         key: 'name',
>         sorter: (a, b) => a.name.localeCompare(b.name),
>         defaultSortOrder: 'ascend',
>       },
>       {
>         title: 'Age',
>         dataIndex: 'age',
>         key: 'age',
>         sorter: (a, b) => a.age - b.age,
>       },
>       {
>         title: 'Address',
>         dataIndex: 'address',
>         key: 'address',
>       },
>     ]);
>   };
> 
>   return (
>     <div>
>       <Button onClick={updateColumns}>Update Columns</Button>
>       {columns.length > 0 && (
>         <Table columns={columns} dataSource={data} pagination={false} />
>       )}
>     </div>
>   );
> };
> 
> export default App;
> ```
> 
> ### 关键点
> 1. **初始 `columns` 为空数组**：在初始状态下，`columns` 被设置为空数组，因此 Table 组件不会被渲染。
> 2. **更新 `columns` 后渲染 `Table`**：当 `columns` 被更新时，`Table` 组件才会被渲染，此时 `defaultSortOrder` 生效。
> 3. **条件渲染 `Table` 组件**：使用条件渲染，确保只有在 `columns` 被更新后才渲染 `Table` 组件。
> 
> 这种方法简单且有效，确保在更新 `columns` 后默认排序状态能够生效。

@afc163  非常感谢你的回答，我只是不明白的一点是，antd 源码中，table使用了自定义hook useSorter(),并且传入columns作为依赖，这样话是不是意味着columns变化每次都会更新useSorter的内部逻辑呢？

**Comment by afc163** [comment]
是。

**Comment by afc163** [comment]
ChatGPT：

 在 React 的函数组件中，使用自定义 Hook （例如 `useSorter()`）时，如果你将某些值（如 `columns`）作为依赖项传入到该 Hook 中，则每当这些依赖项发生变化时，Hook 的内部逻辑就会重新运行。

假设 `useSorter()` Hook 是这样定义的：

```javascript
function useSorter(columns) {
    // ... 一些依赖于 columns 的逻辑 ...
}
```

并且在组件中这样使用：

```javascript
const MyTableComponent = ({ columns }) => {
    const sortedData = useSorter(columns);
    // ... 组件的其他逻辑 ...
}
```

那么，每当传入 `MyTableComponent` 组件的 `columns` 属性发生变化时，`useSorter()` Hook 的调用将会被触发，内部逻辑也会相应地更新。

但是，值得注意的是，这种更新行为是否发生取决于如何定义 `useSorter()` 这个自定义 Hook。如果 `useSorter()` 使用了 `useEffect` 或 `useMemo` 之类的 Hook，并且将 `columns` 作为依赖项，则当 `columns` 变化时确实会触发更新逻辑。如果 `useSorter()` 仅仅是包含了一些计算逻辑而没有使用到任何响应依赖变化的 Hook，那么 `columns` 的变化本身并不会触发重新计算，除非组件重新渲染。

为了减少不必要的计算，有时候可以通过使用 `useCallback` 对函数进行包装，或者使用 `useMemo` 对复杂计算结果进行缓存，以此来避免因依赖项变化而导致的过多的重计算。

对于 `antd` 的 `Table` 组件使用的 `useSorter()` 这一点，如果你想要避免不必要的更新，你应该保证传递给 `columns` 的引用在渲染之间保持稳定，这样即使 `useSorter()` 依赖于 `columns`，也不会因为 `columns` 的每次变化而重复运行逻辑。这通常通过使用 `useMemo` 或者在组件外部定义 `columns` 来实现。

**Comment by yuqimao854** [comment]
> ChatGPT：
> 
> 在 React 的函数组件中，使用自定义 Hook （例如 `useSorter()`）时，如果你将某些值（如 `columns`）作为依赖项传入到该 Hook 中，则每当这些依赖项发生变化时，Hook 的内部逻辑就会重新运行。
> 
> 假设 `useSorter()` Hook 是这样定义的：
> 
> ```js
> function useSorter(columns) {
>     // ... 一些依赖于 columns 的逻辑 ...
> }
> ```
> 
> 并且在组件中这样使用：
> 
> ```js
> const MyTableComponent = ({ columns }) => {
>     const sortedData = useSorter(columns);
>     // ... 组件的其他逻辑 ...
> }
> ```
> 
> 那么，每当传入 `MyTableComponent` 组件的 `columns` 属性发生变化时，`useSorter()` Hook 的调用将会被触发，内部逻辑也会相应地更新。
> 
> 但是，值得注意的是，这种更新行为是否发生取决于如何定义 `useSorter()` 这个自定义 Hook。如果 `useSorter()` 使用了 `useEffect` 或 `useMemo` 之类的 Hook，并且将 `columns` 作为依赖项，则当 `columns` 变化时确实会触发更新逻辑。如果 `useSorter()` 仅仅是包含了一些计算逻辑而没有使用到任何响应依赖变化的 Hook，那么 `columns` 的变化本身并不会触发重新计算，除非组件重新渲染。
> 
> 为了减少不必要的计算，有时候可以通过使用 `useCallback` 对函数进行包装，或者使用 `useMemo` 对复杂计算结果进行缓存，以此来避免因依赖项变化而导致的过多的重计算。
> 
> 对于 `antd` 的 `Table` 组件使用的 `useSorter()` 这一点，如果你想要避免不必要的更新，你应该保证传递给 `columns` 的引用在渲染之间保持稳定，这样即使 `useSorter()` 依赖于 `columns`，也不会因为 `columns` 的每次变化而重复运行逻辑。这通常通过使用 `useMemo` 或者在组件外部定义 `columns` 来实现。

谢谢你的帮助，我最后发现其实是这段代码导致了这个问题。


```js
 if ('sortOrder' in column) {
        // Controlled
        pushState(column, columnPos);
      } else if (init && column.defaultSortOrder) {
        // Default sorter
        sortStates.push({
          column,
          key: getColumnKey(column, columnPos),
          multiplePriority: getMultiplePriority(column),
          sortOrder: column.defaultSortOrder!,
        });
      }`
 ```

  ```js
  const [sortStates, setSortStates] = React.useState<SortState<RecordType>[]>(
    collectSortStates(mergedColumns, true),
  );
  
  const mergedSorterStates = React.useMemo<SortState<RecordType>[]>(() => {

    //内部方法

    return validateStates;
  }, [mergedColumns, sortStates]);
  
  ```
  
  @afc163   是否考虑去掉init这个参数呢？ 我觉得column的变化使其defaultSort重新计算是应该的，是有其他的考虑吗？
