### ISSUE TITLE
Table组件中的列过滤受控属性filteredValue在某些时候会丢失数据

### ISSUE THREAD

**Issue by wangchaoHeart** [ant-design/ant-design#49801]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-y8qpny-o7zpxv?file=demo.js)

### Steps to reproduce

1.点击Name的过滤图标，至少选中一个过滤选项，然后点击ok按钮
2.再次点击Name的过滤图标，把刚才勾选上的过滤选项取消，不要点击ok, 等待5秒 
3.此时发现第2步取消勾选上的过滤选项又重置为第1步的状态了

### What is expected?

filteredValue应该受控

### What is actually happening?

第2次点击过滤图标，把勾选上的过滤选项取消后，等待5秒后勾选上的过滤选项不应该变化

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | windows11 |
| Browser | chrome  126.0.6478.127（正式版本） |

---
测试发现是
  useRequest(fetchData, {
    pollingInterval: 5000,
    pollingErrorRetryCount: 0,
  }); 
这个方法导致的问题，去除这个请求就没问题了，但是项目上有业务需要轮询请求接口

**Comment by yuqimao854** [comment]
使用useMemo

`  const columns =  useMemo(()=>[
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      filters: [
        {
          text: 'Joe',
          value: 'Joe',
        },
        {
          text: 'Jim',
          value: 'Jim',
        },
      ],
      filteredValue: filteredInfo.name,
      onFilter: (value, record) => record.name.includes(value),
    },
  ],[filteredInfo]);`

**Comment by afc163** [comment]
+1 保持 columns 的引用不变即可。

**Comment by wangchaoHeart** [comment]
> 使用useMemo
> 
> ` const columns = useMemo(()=>[ { title: 'Name', dataIndex: 'name', key: 'name', filters: [ { text: 'Joe', value: 'Joe', }, { text: 'Jim', value: 'Jim', }, ], filteredValue: filteredInfo.name, onFilter: (value, record) => record.name.includes(value), }, ],[filteredInfo]);`

非常感谢，确实是因为columns引用变化导致的问题
