### ISSUE TITLE
Tree 组件Token，仅提供了nodeSelectedBg，没有提供选中节点文本的颜色设置

### ISSUE THREAD

**Issue by zmbxy** [ant-design/ant-design#49819]
### What problem does this feature solve?
<img width="1340" alt="image" src="https://github.com/ant-design/ant-design/assets/103547464/17b837bc-e33b-4eee-871a-531f3ef7923a">

目前nodeSelectedBg默认为浅色背景，选中态节点的文本为黑色，当通过nodeSelectedBg修改Tree节点选中态背景颜色为深色时，无法通过token配套同步修改选中态节点文本的颜色，导致选中态下，选中态节点背景和文本颜色对比度不够

### What does the proposed API look like?

类似目录树节点的token变量，提供Tree组件节点选中态文本颜色 token变量

**Comment by zmbxy** [comment]
@afc163 嗨，这个issue我在7月份提了之后，好长时间也一直没有回复，补充一些描述以及期望的效果、期望的Api，共讨论：

<img width="687" alt="image" src="https://github.com/user-attachments/assets/572464aa-3ed4-41de-b251-5ca9ec3dce5f">
<img width="271" alt="image" src="https://github.com/user-attachments/assets/64f1df4f-a87a-4de8-b6f9-01ba784f36f0">
如图所示，使用了ConfigProvider修改了Tree节点的节点选中时的背景颜色，背景颜色可以看到以生效，但文字仍然是黑色的，目前的API中并未提供相应的方案，来同步调整节点文字的颜色。

期望效果：提供节点选中的背景颜色和节点文字颜色

期望API：
1. 一是在Token中同步增加选中节点的文字背景设置
2.二是在titleRender中提供节点选中等状态

**Comment by afc163** [comment]
@zmbxy 欢迎 PR，可以按需增加 token。

**Comment by zmbxy** [comment]
@afc163 
<img width="1351" alt="image" src="https://github.com/user-attachments/assets/53f91c64-2413-41ca-a29b-f8770a1a36a2">
节点悬浮的这个和节点选中是一样的，可以一起给加上一个token不

**Comment by afc163** [comment]
可以加，来 PR。
