### ISSUE TITLE
Cascader组件在使用loadData加载数据时，当加载的数据量很大的时候，页面直接卡死了

### ISSUE THREAD

**Issue by yaangel7** [ant-design/ant-design#49822]
### What problem does this feature solve?

处理大数据加载，我这边有个场景，返回的城市有58000个，直接卡死了，最后就崩溃了
5000多个的时候能成功加载，但是在点开和隐藏下拉框的时候大概需要4秒的时间

### What does the proposed API look like?

能承载大量数据的场景

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/26645
