### ISSUE TITLE
希望 tree 可以支持一个接口从外部定义 节点 dom 的 title

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#49833]
### What problem does this feature solve?

ant-tree-node-content-wrapper 的 title，也就是鼠标悬停显示的元素属性，现在是通过 treeData 影响的，但是这样树结构数据和节点信息数据就耦合了，目前 icon，titleRender 都是横向控制节点渲染的，希望提供一个 xxxRender 来进一步控制渲染

### What does the proposed API look like?

nodeRender nodeContentWrapperRender

**Comment by echoyl** [comment]
#https://github.com/ant-design/ant-design/issues/45884
treeTitleRender 用这个试试，不过也有点问题

**Comment by MadCcc** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/45884
