### ISSUE TITLE
Nextjs 14.x 中 Antd 和 tailwind 样式冲突，有什么好的兼容方式吗

### ISSUE THREAD

**Issue by yxplus1116** [ant-design/ant-design#49838]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

在我的页面中放了一个 antd 的 Button 按钮。 但是这个按钮只有当我 hover 的时候才能看到

### What is expected?

样式兼容

### What is actually happening?

但是这个按钮只有当我 hover 的时候才能看到

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 16.x |
| System | Mac |
| Browser | Google |

**Comment by li-jia-nan** [comment]
https://ant.design/docs/react/compatible-style-cn#%E5%85%BC%E5%AE%B9%E4%B8%89%E6%96%B9%E6%A0%B7%E5%BC%8F%E5%BA%93

**Comment by zombieJ** [comment]
参考一下 @li-jia-nan 提供的文档链接哈。
