### ISSUE TITLE
Space vertical与small Card连用时顶部出现多余的间隙

### ISSUE THREAD

**Issue by hhhhhhhhhhhg** [ant-design/ant-design#49840]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-mhtfao-vmmkm9?file=demo.tsx)

### Steps to reproduce

垂直布局的Space中使用small Card

### What is expected?

两个div高度应该是相同的，而且Space顶部也没有间隔

### What is actually happening?

两个div高度不相同，而且small Card所处的Space顶部存在间隔，而且small的高度比default大
![image](https://github.com/user-attachments/assets/d52a4c26-d58f-4f57-a4a1-78c9d4556333)

| Environment | Info |
| --- | --- |
| antd | 5.19.1 |
| React | 18.3.1 |
| System | Windows 11 专业版 23H2 |
| Browser | Microsoft Edge 版本 126.0.2592.87 (正式版本) (64 位) |

**Comment by zombieJ** [comment]
Space 是 `inline-flex`，所以会和 lineHeight 相互作用。按照你的场景，应该直接使用 Flex 布局：

https://stackblitz.com/edit/react-mhtfao-pwqbg6?file=demo.tsx
