### ISSUE TITLE
RangePicker 在showTime为true时选择起始时间后不会自动切换到结束时间

### ISSUE THREAD

**Issue by LiuZHolmes** [ant-design/ant-design#49843]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-gsunsg?file=demo.tsx)

### Steps to reproduce

点选起始时间

### What is expected?

会自动focus到结束时间，并让下一次的选择应用到结束时间

### What is actually happening?

仍是在选择起始时间

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | Windows 10 22H2 |
| Browser | Microsoft Edge Version 125.0.2535.92 |

---
在showTime为false时，上述行为明显不一致。并且使用needConfirm后的behavior也一样是很迷惑。

**Comment by LiuZHolmes** [comment]
不知道是不是期望的行为，粗略看了下rc-picker确实是有这个问题的。当showtime为true时判定为complexPicker，所以select的时候没有去triggerPartConfirm
![image](https://github.com/user-attachments/assets/637145b7-53f8-4665-b04f-864082fc13e4)
![image](https://github.com/user-attachments/assets/501cd1c5-02c9-47a6-8bf4-189642c1d854)

**Comment by afc163** [comment]
是预期行为，showTime 时其实没有明确的结束点（选日期、小时、分钟或者秒作为结束点，都会有点奇怪）。
