### ISSUE TITLE
Carousel自动播放时，当重新render后停止

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#4984]
一个简单的复现方式在示例界面：https://ant.design/components/carousel-cn/
看其中的自动切换的例子，改变窗口大小，界面会重新render，这时自动切换停止。
在我的代码中，只要触发到render就会停止。请问有办法解决吗？

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/issues/337

**Comment by afc163** [comment]
Found a workaround.
