### ISSUE TITLE
Please add disable prop to Search. Search is input combined with button.

### ISSUE THREAD

**Issue by levelMalakhovSergey** [ant-design/ant-design#49847]
### What problem does this feature solve?

I had an issue when I wanted to stop the user from searching until the form is valid (containing only numbers). So, I wanted to disable the search button. Since you don't have this functionality built-in, I used the enterButton prop.
enterButton={
          <Button
            onClick={e => onSearch((e.target as HTMLInputElement).value)}
            disabled={searchError}
            icon={<SearchOutlined />}
          />
        }
Because I didn't want to use useState, I tried to get e.target.value from the onChange event to call the request. This worked fine until I started typing quickly and pressing search. 

I've already realized that it would work fine without the onClick event. But still, disabling the search button could be useful.

### What does the proposed API look like?

  const [searchError, setSearchError] = useState(false); 
<Search
        type="text"
        disableSearchIcon={searchError}
        onSearch={onSearch}
      />

**Comment by levelMalakhovSergey** [comment]
What does the proposed API look like?
const [searchError, setSearchError] = useState(false);
<Search
        searchIconDisabled={true}
        onSearch={onSearch}
      />

**Comment by MadCcc** [comment]
Consider to use `addonAfter` to construct Search component yourself. Currently we don't support customize button.
