### ISSUE TITLE
在table中组件中更新mobx状态，未实时更新

### ISSUE THREAD

**Issue by 352718784** [ant-design/ant-design#49844]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-table-mobx-bug-ltvy8y)

### Steps to reproduce

点击第二行数据时

### What is expected?

点击第二行数据时，页面会实时更新

### What is actually happening?

点击第二行数据时，页面未更新

| Environment | Info |
| --- | --- |
| antd | 5.19.1 |
| React | 18 |
| System | window |
| Browser | 126.0.6478.127 |

**Comment by zombieJ** [comment]
当 `dataSource`  `columns` 更新时才会触发 Table 更新，当你的数据是 `mutable` 的时会被 memo 跳过。这个和 antd 没有关系，可以去 mobx 看一下相关文档或者 issue 哈~
