### ISSUE TITLE
RangePicker显示日期自动更改的体验问题

### ISSUE THREAD

**Issue by dongzhangli** [ant-design/ant-design#4985]
#### Environment(required)

- antd version:2.6.0
- OS and its version:OS X 10.11.6
- Browser and its version:Google Chrome 版本 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

例：
使用RangePicker组件，开始时间选择2015-1-1，结束时间选择2016-1-1
选择开始时间日历标题会自动跳到结束时间的上个月

![image](https://cloud.githubusercontent.com/assets/11748156/23163078/fead8310-f86b-11e6-83ec-cd8577faf061.png)

点击红色框的日期时，前面已经选中的日期会**自动跳转到2017年**
正常的思维是，已经选中的开始日期不变，当选择结束日期时，只更改结束日期

**Comment by benjycui** [comment]
这个问题在于交互设计就是把这两个面板绑定了

![image](https://cloud.githubusercontent.com/assets/3580607/23194697/9e9dd95a-f8ea-11e6-8f97-7fce591c2822.png)

**Comment by dongzhangli** [comment]
这样会误以为显示的开始时间就是点击“确定”按钮后出现在文本框的开始时间，而点击“确定”后，显示在文本框的开始时间并不是看到的。如果交互是这样，我能通过接口实现修改交互吗?

**Comment by benjycui** [comment]
发给交互评估了，个人也觉得不合理。

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/23453734/6c9fc016-fea4-11e6-8777-ef47726c7190.png)

**Comment by benjycui** [comment]
Online demo: https://rawgit.com/longbill/jquery-date-range-picker/master/index.html

**Comment by dongzhangli** [comment]
第5步，是不是选中结束时间会切换开始时间面板？
个人觉得修改结束时间时不自动更改开始时间就可以了，已选中的开始时间始终固定不变，开始时间面板显示的时间也不变

**Comment by yesmeck** [comment]
按 jquery-date-range-picker 逻辑左右两个面板应该完全绑定的。这里第五步的意思是点击左边的箭头切换年份时，右边的年份也要跟着变？

**Comment by benjycui** [comment]
@yesmeck 内部沟通，交互文字说不清。。

**Comment by afc163** [comment]
市面上 RangePicker 都是左右面板绑定的，我觉得没必要改。

**Comment by benjycui** [comment]
> Online demo: https://rawgit.com/longbill/jquery-date-range-picker/master/index.html

其实这个例子里面就不是绑定的。

不过现在的问题是，我们最近人手更紧了，有需求建议 PR。

**Comment by afc163** [comment]
@benjycui 这个例子不错。

**Comment by dongzhangli** [comment]
个人觉得，切换切换两次月份就晕了，其他用户也会遇到同样的问题。RangePicker的做法也不一定是最佳做法，这个交互优化一下，比RangePicker更好用：）
