### ISSUE TITLE
`Card`中的`cover`属性放入非`img`内容时，圆角被覆盖

### ISSUE THREAD

**Issue by YMNNs** [ant-design/ant-design#49854]
### Reproduction link

[https://codepen.io/dmsfrc/pen/eYwNKYv](https://codepen.io/dmsfrc/pen/eYwNKYv)

### Steps to reproduce

- 在第一个`Card`组件写入`cover={<div style={{backgroundColor:"blue", opacity:0.15, height:200}}/>}`
- 在第二个`Card`组件写入`cover={<img style={{backgroundColor:"blue", opacity:0.15, height:200}}/>}`

### What is expected?

组件圆角正常显示

### What is actually happening?

第一个组件上面的圆角被`cover`内容覆盖，第二个正常

| Environment | Info |
| --- | --- |
| antd | 5.19.1 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome 126 |

![image](https://github.com/user-attachments/assets/74cf8306-f03d-4394-a0e6-c4c78cb1d933)

**Comment by wanpan11** [comment]
目前是只对 img 元素做了圆角处理，大佬们看看需不需要支持 @zombieJ @afc163 

<img width="677" alt="image" src="https://github.com/user-attachments/assets/5767d82f-28fc-4935-94e0-4ce6127675d0">

**Comment by YMNNs** [comment]
> 目前是只对 img 元素做了圆角处理，大佬们看看需不需要支持 @zombieJ @afc163
> 
> <img alt="image" width="677" src="https://private-user-images.githubusercontent.com/38714194/348492765-5767d82f-28fc-4935-94e0-4ce6127675d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MzM3MjgsIm5iZiI6MTcyMDkzMzQyOCwicGF0aCI6Ii8zODcxNDE5NC8zNDg0OTI3NjUtNTc2N2Q4MmYtMjhmYy00OTM1LTk0ZTAtNGNlNjEyNzY3NWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA1MDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NDE1NGE3ZWEzYzI4OGJjZTJmOTk0YzU0NDMzYmI2ZDk3ZDlmMjA1YzliOGQ1ZTgwODllNjc2YjRjYjMwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.giDtg3NIJwjAfvRf-Ko1zx29s9Zw4dvhLd9jENXw4DQ">

如果只支持img是不是需要在文档中说明一下并且对其他元素弹个警告
