### ISSUE TITLE
Input & Select line-height and padding performing the same

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#4987]
riddleId: 140128f5

希望 input 和 select 的 line-height 和 padding 表现情况一致，也就是在
```
{ this.state.input
  ? <Input />
  : <Select />
}
```
切换的时候，没有位移和闪烁

**Comment by jaredleechn** [comment]
placeHolder 的行高好像也是有问题的，打开 riddle 看下，会有一个 y 轴的位移

**Comment by afc163** [comment]
奇怪了，怎么会没提交上来。。

**Comment by afc163** [comment]
不小心把本地改动 `git checkout` 掉了。

**Comment by paranoidjk** [comment]
@afc163 `git reflog` 还可以恢复的

**Comment by afc163** [comment]
https://codepen.io/anon/pen/gmYreE?editors=0010

**Comment by benjycui** [comment]
@jaredleechn 你本地可以重现？然后本地是用 babel-plugin-import 还是直接使用 dist/antd.js?

**Comment by jaredleechn** [comment]
可以重现，babel-plugin 方式

不过我看现在的问题应该是这个改动导致了 safari 下表现异常了么？

**Comment by afc163** [comment]
暂时不知道怎么解决，貌似和浏览器排版机制有关系。

**Comment by jaredleechn** [comment]
我看 chrome 下这个的 line-height 是无效的，怎么调整都没有影响，但是 safari 下是生效的，28 height，32 的 line-height，所以错位


![image](https://cloud.githubusercontent.com/assets/5318333/23205914/9b68ab66-f926-11e6-9c6b-a8062f03d0a5.png)

**Comment by afc163** [comment]
用了一个 chrome-only 的 hack 搞定。

**Comment by jaredleechn** [comment]
还有那个微小的 margin 问题，7 -> 8～～那个应该不会导致 safari 异常～

**Comment by afc163** [comment]
7 到 8 没有回滚。

**Comment by afc163** [comment]
5b20a5fc3e09844bc0fb05af579e3cd6a057bd9d cause #5091 and I gone just to ignore it.
