### ISSUE TITLE
Table组件怎么实现表头过滤，排序图标位置自定义？

### ISSUE THREAD

**Issue by wangchaoHeart** [ant-design/ant-design#49874]
### What problem does this feature solve?

让用户自定义表头过滤，排序图标的位置

### What does the proposed API look like?

暂时不知道怎么实现

**Comment by wangchaoHeart** [comment]
![image](https://github.com/user-attachments/assets/c5d0c3e0-f298-4935-8b4d-52e4fe6fe0b2)
类似这种UI布局

**Comment by wangchaoHeart** [comment]
目前的antd Table表头的过滤和排序都是在最右边的区域的，没法修改

**Comment by afc163** [comment]
What does the proposed API look like?
