### ISSUE TITLE
Extend copyable API (#2)

### ISSUE THREAD

**Issue by revidovich** [ant-design/ant-design#49879]
Please, add options to copyable text

### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-x5rpye?file=demo.tsx)

### Steps to reproduce

click 'copy'

### What is expected?

I hate commas 

### What is actually happening?

I, hate, commas 

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | 17 |
| System | windows |
| Browser | chrome |

---
need option 'text/plain' to copy function
![image](https://github.com/user-attachments/assets/eeb75d8c-4532-4a91-969f-04acadb88859)  
🙏 options: {format: 'text/plain'}🙏

**Comment by zombieJ** [comment]
Use `copyable.text` prop to customize your copy content : )

**Comment by revidovich** [comment]
replacing the text does not solve the copying problem if the strings are dynamic (coming from the server) @zombieJ

**Comment by crazyair** [comment]
promise `text: string | (() => string | Promise<string>)`

**Comment by revidovich** [comment]
I had to install the copy-to-clipboard library, (which is already IN the ant design), just to skip the option

**Comment by zombieJ** [comment]
https://ant.design/components/typography-cn#copyable

**Comment by revidovich** [comment]
Now you can close it :)  Or you can put it as a low priority, the problem is solved with a hack 
`copyable.text: textRef.current?.textContent?.split(`${t('copy')}`)[0] `and HTML character entity references. Thank you.

**Comment by revidovich** [comment]
My task has been changed, now I have conditional rendering, I can't use useRef. The value of the ref is set at the first rendering, then it behaves unpredictably due to the condition. so..
Reopen :)))

**Comment by revidovich** [comment]
I have commas and [Object, object] in copied text.
need option 'text/plain' 🙏 to fix it

**Comment by crazyair** [comment]
support options,but `String(children)`
```
copy(text || String(children) || '', copyOptions);
```

**Comment by crazyair** [comment]
Options cannot solve the problem because https://stackblitz.com/edit/antd-reproduce-5x-gjoq2i?file=demo.tsx
![image](https://github.com/user-attachments/assets/f96f5837-c985-4305-a09e-c101afa941f5)

No problem, it's because I used it `textContent`
