### ISSUE TITLE
怎么设置单独设置 message 的层级

### ISSUE THREAD

**Issue by wangdabo123** [ant-design/ant-design#49884]
### What problem does this feature solve?

三层层弹窗里面有 Tooltip， Popconfirm，各自设置了较高的zIndex，导致message 被遮挡了

### What does the proposed API look like?

message 可单独设置 zIndex

**Comment by wanpan11** [comment]
用 ConfigProvider 修改 zIndexPopup 试试

![image](https://github.com/user-attachments/assets/092f65a3-9ccb-4dac-9877-4574b0fe55ac)

**Comment by afc163** [comment]
在 Ant Design 5 中，`message` 组件的使用方式依然类似于之前的版本，你可以通过 `message.config` 来全局配置消息组件的层级（z-index）。不过，如果你想单独设置某个 `message` 实例的层级，目前 Ant Design 并未直接提供这种功能。

以下是如何通过全局配置来设置 `message` 组件的 z-index 的示例：

```javascript
import { message } from 'antd';

message.config({
  top: 100,
  duration: 2,
  maxCount: 3,
  zIndex: 1000,  // 设置 message 组件的 z-index 值
});
```

如果你确实需要单独为某个 `message` 实例设置 z-index，可以考虑以下变通方法：

### 1. 使用 CSS 覆盖

首先定义一个自定义 CSS 类，例如：

```css
.custom-message {
  z-index: 2000 !important; /* 设置更高的 z-index 值 */
}
```

然后可以在页面加载时通过 JavaScript 动态添加此类到特定的 `message` 元素中。以下是一个简单的示例：

```javascript
import { message } from 'antd';

const showMessage = () => {
  const hide = message.loading('Loading...', 0);
  setTimeout(() => {
    // 通过 querySelector 获取到 message 元素
    const messageElement = document.querySelector('.ant-message');
    if (messageElement) {
      // 动态添加自定义 CSS 类
      messageElement.classList.add('custom-message');
    }
    hide();
  }, 1000);
};

showMessage();
```

### 2. 使用 `getContainer` 自定义容器

你也可以通过 `getContainer` 属性自定义 `message` 的容器，以便控制其样式：

```javascript
import { message } from 'antd';
import ReactDOM from 'react-dom';

const container = document.createElement('div');
container.style.zIndex = '2000';
document.body.appendChild(container);

message.config({
  getContainer: () => container,
});

message.info('This is a message with custom zIndex');
```

这种方法允许你为特定的 `message` 实例提供一个自定义的容器，从而控制其层级和其他样式。

希望这能帮助你更灵活地控制 `message` 组件的显示效果。

**Comment by wanpan11** [comment]
文档里没写 config zIndex 配置🤧

**Comment by loulaner** [comment]
同上，@afc163  config zIndex 设置无效，请看看
