### ISSUE TITLE
after selecting autocomplete option, the input position is at the start and not scroll to the cursor position which is at the rightmost

### ISSUE THREAD

**Issue by byte-ma** [ant-design/ant-design#49889]
### Reproduction link

[https://wzj1qw--run.stackblitz.io/](https://wzj1qw--run.stackblitz.io/)

### Steps to reproduce

input some letters and select any option in the option list

### What is expected?

the cursor position is at the rightmost and scroll to the rightmost

### What is actually happening?

the input position is at the original place and not at the rightmost

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | macos |
| Browser | 119 |

**Comment by dagadbm** [comment]
i have something similar but in my case the focus just totally dissapears when the `options` change

**Comment by MadCcc** [comment]
Cannot open your reproduction, please make sure you save your stackblitz.
