### ISSUE TITLE
cssinjs useGlobalCache 会产生内存泄漏

### ISSUE THREAD

**Issue by blackie4** [ant-design/ant-design#49885]
### Reproduction link

[https://ant-design.antgroup.com/components/button-cn](https://ant-design.antgroup.com/components/button-cn)

### Steps to reproduce

1. 打开重现链接
2. 打开控制台 - Memory - task snapshot
3. 查看堆信息下Constructor - String 下一堆“token%5.19.0-true”开头的堆信息

### What is expected?

优化性能，降低内存占用

### What is actually happening?

项目使用组件库后内存占用升高

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.x |
| System | windows 10 |
| Browser | chrome 125.0.6422.113 |

![image](https://github.com/user-attachments/assets/2021c65a-f2a5-4616-8c14-00804b1a1225)

**Comment by blackie4** [comment]
> 给个重现看看？另外也顺便来个贴图哈~

贴图附上了。官方文档站点能重现：

1. 打开重现链接 https://ant-design.antgroup.com/components/button-cn
2. 打开控制台 - Memory - task snapshot
3. 查看堆信息下Constructor - String 下一堆“token%5.19.0-true”开头的堆信息

**Comment by MadCcc** [comment]
找不到你说的 String，给个录屏看看吧

**Comment by blackie4** [comment]
> 找不到你说的 String，给个录屏看看吧

[screencast-ant.design-2024.07.17-22_55_11.webm](https://github.com/user-attachments/assets/2cb874e0-b412-49ef-96a5-6fd8ea460b43)

**Comment by blackie4** [comment]
> 找不到你说的 String，给个录屏看看吧

[screencast-ant.design-2024.07.17-22_55_11.webm](https://github.com/user-attachments/assets/1cfdc479-de27-4afa-b2d5-7534dd117147)

**Comment by Junlin-Zhu** [comment]
确实有问题，我这边也能复现。

**Comment by DONGNEZHA** [comment]
有后续处理方案么

**Comment by lunady** [comment]
遇到了相同的问题

**Comment by zombieJ** [comment]
查看了一下，这个 string 是来自于 React 的 `useMemo`。组件渲染时，通过 `useMemo` + `token` 判断是否需要更新样式。当主题变化时则重新渲染 `style`：

<img width="596" alt="截屏2024-09-11 15 29 46" src="https://github.com/user-attachments/assets/1ae07475-3a32-437c-a3ab-fcb8dd76b7e8">

组件销毁时，string 占用的内存会被释放。如果有确实遇到内存泄漏的情况，可以提供一下复现。

**Comment by DONGNEZHA** [comment]
复现仓库 https://github.com/DONGNEZHA/create-react-app-antd
一个简单的场景，点击第一个按钮来控制第二个按钮组件是否显示。我的疑问是为什么这里的memory快照会有多条同样的"token" 开头的string，并且还有一个现象是多次点击第一个按钮后，再次获取memory快照 会发现 这个string增多了。我每次获取快照前都会手动点击垃圾回收按钮。
![image](https://github.com/user-attachments/assets/45ccd8dc-0e34-48e0-8230-72b5ac8792bd)
![image](https://github.com/user-attachments/assets/021e57e8-1d94-4405-b865-bf25a053e078)

**Comment by LilyGithub** [comment]
<img width="946" alt="image" src="https://github.com/user-attachments/assets/1699fd7a-b164-4b7f-860e-bffee760d144">
鄙人修复fang an方案，有用的兄弟可以参考下。           给@ant-design/cssinjs  打个补丁。
修改文件中`es/hooks/useGlobalCache.js`

**Comment by DONGNEZHA** [comment]
> <img alt="image" width="946" src="https://private-user-images.githubusercontent.com/18751232/366746595-1699fd7a-b164-4b7f-860e-bffee760d144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjI4MTYsIm5iZiI6MTcyNjEyMjUxNiwicGF0aCI6Ii8xODc1MTIzMi8zNjY3NDY1OTUtMTY5OWZkN2EtYjE2NC00YjdmLTg2MGUtYmZmZWU3NjBkMTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMmZiOTVmNDZlOGY4ODdkYTZiYTE1MmRmZjZjMmUwOGRkMGIyYzc3ODkyNzQxNmZmMDY3MDg5ZDMxMTEzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OFeTKchy_qWoNNbEQJS0gNjecS4kIwYjsrJTSmj9XAE"> 鄙人修复fang an方案，有用的兄弟可以参考下。 给@ant-design/cssinjs 打个补丁。 修改文件中`es/hooks/useGlobalCache.js`

有用，谢谢
