### ISSUE TITLE
Wrong importation of React in typings

### ISSUE THREAD

**Issue by hlehmann** [ant-design/ant-design#4990]
All typings starts with 
`import React from 'react';`
Because React doesn't have a default, in typescript it should be
`import * as React from 'react';`

As a result I get diagnostic errors like 
```
Error:(21, 13) TS2605:JSX element type 'Menu' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'Menu'.
```

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design#typescript

**Comment by Odonno** [comment]
Thanks for the tip. I think it should be more visible somewhere. I did not know why I got the error but hopefully I found the solution by reading this issue.

**Comment by benjycui** [comment]
@Odonno trace: https://github.com/ant-design/ant-design/issues/5426 https://github.com/ant-design/ant-design/pull/6193

Hope to get advice from you.

**Comment by Odonno** [comment]
@benjycui Yeah. That's great.
