### ISSUE TITLE
RangePiceker 5.18.0 与 5.19.0 交互发生不一致

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#49904]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-s5z99t?file=demo.tsx)

### Steps to reproduce

5.18.0 https://stackblitz.com/edit/react-s5z99t-6bbtok?file=demo.tsx
5.19.0 https://stackblitz.com/edit/react-s5z99t?file=demo.tsx

各个打开，进行如下步骤
1. 打开选择 1 - 7 日
2. 打开选择开始时间 21 日，然后关闭弹窗

### What is expected?

2个版本交互一致

### What is actually happening?

2个版本交互不一致

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | latest |
| System | mac |
| Browser | chrome |

---
5.18.0 会恢复为 1-7日
5.19.0 会变成 21-21日

**Comment by Wxh16144** [comment]
5.18 是预期的么🤔

**Comment by crazyair** [comment]
> 5.18 是预期的么🤔

这个交互2个都可，主要看希望怎样的

**Comment by zombieJ** [comment]
搬运一下评论：两个交互都行，只是过去的交互在动态 disabledDate 的 panel 切换时会有个穿透问题。所以 minor 版本里在最后一个环节还会再拦一次。
