### ISSUE TITLE
DatePicker 在表单中不同平台值不一致

### ISSUE THREAD

**Issue by faner11** [ant-design/ant-design#49901]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-4hthnt?file=demo.tsx)

### Steps to reproduce

stackblitz：https://stackblitz.com/edit/react-4hthnt?file=demo.tsx
自己的demo：https://github.com/faner11/procomponents-dayjs

### What is expected?

表单onFinish 时间字段一致

### What is actually happening?

stackblitz  平台基于官方DEMO添加DatePicker 后点击提交拿到的是IOS 8601 格式的字符串。
但是我在本地的demo中，一样的代码拷贝后，拿到的是dayjs 对象

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | 18.2.0 |
| System | mac os |
| Browser | chorme 126 |

**Comment by Wxh16144** [comment]
> stackblitz 平台基于官方DEMO添加DatePicker 后点击提交拿到的是IOS 8601 格式的字符串。

是一个 dayjs 对象呀

<img width="1703" alt="image" src="https://github.com/user-attachments/assets/d30e08cd-1b36-4851-afd5-316383ef4f99">

**Comment by zombieJ** [comment]
官方也是 dayjs 对象，DatePicker `onChange` 返回的永远都是 dayjs 对象，不会去做特殊转换的。

**Comment by faner11** [comment]
![image](https://github.com/user-attachments/assets/811454dd-0608-476f-bc3b-d07e4d36bdec)
我是这样

**Comment by zombieJ** [comment]
这个 console 不是真的 console 是这个平台对 console 做了 toString。你打开开发者控制台看到的才是原装的。
