### ISSUE TITLE
希望 <FloatButton /> 悬浮按钮能够指定滚动容器与自定义位置

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#49911]
### What problem does this feature solve?

这里有个简单的代码片段：
[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-vmh3xv?file=demo.tsx)

我希望在可滚动的侧边栏里添加一个悬浮按钮，
但它的默认行为是滚动整个页面，而不是滚动侧边栏，
而且该按钮默认显示的位置在页面右下角，而不在侧边栏内部。

![屏幕截图 2024-07-17 014944](https://github.com/user-attachments/assets/315be662-db8c-45b3-a74a-07c8907ce6a6)

### What does the proposed API look like?

1. 为 `<FloatButton />` 悬浮按钮增加指定滚动容器的属性
2. 为 `<FloatButton />` 悬浮按钮增加指定显示位置的属性

**Comment by afc163** [comment]
Try `target` and `style`: https://stackblitz.com/edit/react-vmh3xv-bo6hts?file=demo.tsx
