### ISSUE TITLE
Header Extra height In Table with fixed  Header and Columns.

### ISSUE THREAD

**Issue by javpaw** [ant-design/ant-design#4991]
#### Environment(required)
- antd version: 2.7.2
- OS and its version: MacOs Sierra 10.12.3 (16D32)
- Browser and its version: Google Chrome 56.0.2924.87, Safari 10.0.3 (12602.4.8)

#### What did you do? Please provide steps to re-produce your problem.

I was creating a table with fixed columns and header.

#### What do you expected?

A table rendered with the rows aligned and consistent header height.

#### What happen?
The height for the non fixed columns is greater than the height for the fixed columns.
This makes the rows to be misaligned.

#### Additional information
This is happening to me even in the documentation page: 
https://ant.design/components/table/#components-table-demo-fixed-columns-header

Screenshot:
![screen shot 2017-02-21 at 16 18 37](https://cloud.githubusercontent.com/assets/838679/23171535/02fec550-f853-11e6-9d59-7bdab2bc435f.png)

#### Re-producible online demo
http://codepen.io/anon/pen/apeYre?editors=0010

##### Edit
The operating system has three configurations related to show scroll bars:
- Automatic based on mouse or trackpad.
- Only when scrolling.
- Always.

This error happens if we pick the first or second options.
If the scrollbar is always visible there is no error.

<img width="1426" alt="scrollbar" src="https://cloud.githubusercontent.com/assets/838679/23173986/38e1e83e-f85b-11e6-96c3-683b1078bad0.png">

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/4936
