### ISSUE TITLE
Carousel 走马灯当方向为竖列的时候在移动端滑动方向出现问题

### ISSUE THREAD

**Issue by shiyanaaa** [ant-design/ant-design#49912]
### Reproduction link

[https://ctab.pages.dev/](https://ctab.pages.dev/)

### Steps to reproduce

将Carousel 走马灯设置为infinite，竖向，在移动端触摸左右滑动与上下滑动

### What is expected?

上下滑动无法滚动，左右滑动可以滚动

### What is actually happening?

上下滑动可以滚动，左右滑动无法滚动

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | 18.3.1 |
| System | 均可 |
| Browser | 均可 |

**Comment by MadCcc** [comment]
给个 stackblitz 复现吧，好看下代码实现

**Comment by shiyanaaa** [comment]
> 给个 stackblitz 复现吧，好看下代码实现

在移动端时，动画时上下切换，触摸手势需要左右滑动

**Comment by shiyanaaa** [comment]
> 给个 stackblitz 复现吧，好看下代码实现

我已经给出了代码，请问现在进度是什么，将会修复吗
