### ISSUE TITLE
Button，当设置disabled为true时，拿不到点击事件了

### ISSUE THREAD

**Issue by zdxxxxxx** [ant-design/ant-design#49910]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-xxpib8?file=demo.tsx)

### Steps to reproduce
```js
const someComponent = ({disabled = true })=>{
 const handleClick = () => {
    // 并不执行
    message.info({
      content: '加班开发中，敬请期待',
      icon: <Icon name="attention" style={{ marginRight: 3 }}></Icon>,
    })
  }

  return 
      <Button
        onClick={handleClick}
        disabled={disabled}
        block
      >
        某个未完成的功能
      </Button>
}
```
### What is expected?

可以拿到点击事件

### What is actually happening?

拿不到点击回调

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18 |
| System | mac os |
| Browser | chrome |

---
业务场景：想要disabled样式，又想加toast提示

**Comment by zombieJ** [comment]
这是原生行为，和组件库无关哈~

**Comment by Wxh16144** [comment]
> 业务场景：想要disabled样式，又想加toast提示

多套一个 div， 在 div 用 onClick 解

**Comment by zdxxxxxx** [comment]
> > 业务场景：想要disabled样式，又想加toast提示
> 
> 多套一个 div， 在 div 用 onClick 解

怎么嵌套？

**Comment by yoyo837** [comment]
丢div里面

**Comment by yoyo837** [comment]
click往div移
