### ISSUE TITLE
InputNumber组件无法输入Infinity，Infinity应作为number类型允许被输入

### ISSUE THREAD

**Issue by cjtcjt999** [ant-design/ant-design#49916]
### Reproduction link

[https://codepen.io/cjtcjt999/pen/xxoZKrP?editors=001](url)

### Steps to reproduce

输入Infinity，输入框会被清空

### What is expected?

输入Infinity，输入框不会被清空

### What is actually happening?

输入Infinity，输入框会被清空

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | 18.2.0 |
| System | win11 |
| Browser | Chrome126.0.6478.127 |

---
在Antd3.x版本中，Infinity可被输入，在4以后无法实现

**Comment by MadCcc** [comment]
复现是空的

**Comment by cjtcjt999** [comment]
> 复现是空的

https://codepen.io/cjtcjt999/pen/xxoZKrP?editors=001
输入Infinity，onChange未被触发

**Comment by MadCcc** [comment]
字符串 Infinity 不支持的，目前 Number.Infinity 也不支持，因为无法适配 step

**Comment by MadCcc** [comment]
可以试试 parse 和 format 自己处理一下 Infinity 的逻辑？

**Comment by cjtcjt999** [comment]
> 可以试试 parse 和 format 自己处理一下 Infinity 的逻辑？

![InputNumber](https://github.com/user-attachments/assets/95eed47e-9e18-4e24-beff-ca435a0edb62)
目前差不多是这么实现的，在旧版本的antd3.x里Infinity是被支持的，在Infinity的step递进是不变化的

**Comment by zombieJ** [comment]
移除是因为早期版本不支持 `string` 模式，导致数字太大会飞。此外对自定义格式也是不支持的。所以在重构支持 `string` number 后，就去掉了。解法就是你们聊的，自己封装一下就能还原回来。
