### ISSUE TITLE
希望 <Select /> 选择器能够支持滚动加载

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#49919]
### What problem does this feature solve?

文档为 `<Select />` 选择器提供了 “大数据” 的示例 Demo，

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ubb932?file=demo.tsx)

![屏幕截图 2024-07-17 133202](https://github.com/user-attachments/assets/328c8a0c-4ebe-4f73-abbb-3ae73b5404ba)

![屏幕截图 2024-07-17 133253](https://github.com/user-attachments/assets/9e6e0100-a5d1-40d5-ac0a-8cf82d0fa8e8)

根据这个示例描述：
> Select 默认针对大数据开启了虚拟滚动，因而获得了更好的性能，可以通过 virtual={false} 关闭。

**但这必须一次性加载所有数据**，我希望 `<Select />` 选择器能提供滚动到底部，动态加载数据的方式，就像 `<List />` 组件的滚动加载一样。

### What does the proposed API look like?

希望 `<Select />` 选择器提供滚动到底部，动态加载数据的方式。

![屏幕截图 2024-07-17 133603](https://github.com/user-attachments/assets/bc4d1692-19cb-4347-ac1b-9f4eb54952fc)

**Comment by MadCcc** [comment]
试试用 `onPopupScroll` 来自行实现。
