### ISSUE TITLE
Select组件多选输入字符抖动

### ISSUE THREAD

**Issue by Keyves** [ant-design/ant-design#4992]
https://ant.design/components/select-cn/
Select组件在多选的情况下，在输入的同时字符会小幅度左右摆动，看了源码和结构我发现内部input的width是实时计算的，使用了span标签做镜像再测量宽度。我建议在将input的值拷贝给镜像的时候可以在尾部插入一个空白字符在进行测量，增大宽度的容错空间。

**Comment by benjycui** [comment]
Yep, I notice that our input will re-align when it match some option.

It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
And could you try to PR to fix this?

**Comment by Keyves** [comment]
ok, i had PR to rc-select

**Comment by benjycui** [comment]
This can be re-produced when we zoom browser and try to type Chinese in [`Select[multiple]`](https://ant.design/components/select/#components-select-demo-multiple)
