### ISSUE TITLE
使用Menu组件报Warning: findDOMNode is deprecated错误

### ISSUE THREAD

**Issue by FanSun521** [ant-design/ant-design#49922]
### Reproduction link

[https://github.com/didi/LogicFlow/tree/feat/site](https://github.com/didi/LogicFlow/tree/feat/site)

### Steps to reproduce

无

### What is expected?

解决报错

### What is actually happening?

无

| Environment | Info |
| --- | --- |
| antd | 5.12.7 |
| React | 18.2.0 |
| System | mac pro |
| Browser | 126.0.6478.114（正式版本） (arm64) |

---
无

**Comment by fnoopv** [comment]
更新`antd`版本, #48646
