### ISSUE TITLE
Style folder for components

### ISSUE THREAD

**Issue by crhk** [ant-design/ant-design#49934]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-j7skma?file=token.ts)

### Steps to reproduce

just check the type of AutoComplete in theme.ts, it says it does not exist in ComponentsConfig but an API exists on ant design component page.

### What is expected?

AutoComplete should be accepted as a component (same goes for TimePicker).

### What is actually happening?

AutoComplete provides an error when used as a key for token component

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome v126.0.6478.126 |

---
I saw when building ant design that AutoComplete does not have a style folder, I guess this is related:
- either AutoComplete can't be styled with token
- either there is a fail when building AutoComplete

Same goes for TimePicker for example.

Thanks

**Comment by crhk** [comment]
I don't understand your comment, there is a reproduction link

**Comment by afc163** [comment]
> AutoComplete provides an error when used as a key for token component

I can't see any errors in reproduction link you provided.

<img width="1781" alt="图片" src="https://github.com/user-attachments/assets/f26f4793-9e13-44af-8179-17ba168f574f">

**Comment by crhk** [comment]
Sorry I didn't mention you have to wait for several seconds before it appears

**Comment by MadCcc** [comment]
AutoComplete do not have styles, but Input style could work.

**Comment by crhk** [comment]
then it means this doc is not up to date: https://ant.design/components/auto-complete#design-token
