### ISSUE TITLE
Select 多选模式长按回车会不断执行 onChange

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#49941]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-sbsy3z?file=demo.tsx)

### Steps to reproduce

鼠标点击 Select，按住回车不松开

### What is expected?

只执行一次 onChange

### What is actually happening?

一直不断执行 onChange

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by RedJue** [comment]
感觉合理的吧，每删除一个元素自然要触发 `onChange`，怎么避免多次触发是用户需要考虑的事，比如加防抖

**Comment by RedJue** [comment]
是有啥很难解决的问题么，需要把这个改成一次?

**Comment by crazyair** [comment]
> 是有啥很难解决的问题么，需要把这个改成一次?

对，如果回车会调接口等一些事情，不小心按到回车了，会很容易让页面崩掉
