### ISSUE TITLE
dropdown's onVisibleChange not trigger

### ISSUE THREAD

**Issue by alanwei0** [ant-design/ant-design#4994]
#### Environment(required)

- antd version: 1.7.1
- OS and its version: mac os 10.12.3
- Browser and its version: chrome 56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

just add a dropdown component, and listen `onVisibleChange` event

#### What happened?

when i click on a menu item,  the menu is hidden, but not trigger the `onVisibleChange` event

#### Re-producible online demo

http://codepen.io/alanwei0/pen/bqbNEa?editors=0011

**Comment by benjycui** [comment]
It's by designed.

See: https://github.com/react-component/dropdown/commit/f304a249a17b3596c8252f5f2ec10a2b64804a32

And https://github.com/react-component/dropdown/issues/10

**Comment by benjycui** [comment]
ping @yiminghe , what's your reason?

**Comment by afc163** [comment]
You can use menu click to catch this behavious for now: http://codepen.io/anon/pen/oZjmVx?editors=0011

**Comment by alanwei0** [comment]
@afc163 you mean i have to listen the menu click event to simulate the `onVisibleChange` event???

**Comment by afc163** [comment]
Yep, I afraid you have to according to this comment: https://github.com/react-component/dropdown/commit/f304a249a17b3596c8252f5f2ec10a2b64804a32#diff-1875c38d700963f069aab5b639150402R73 , though I don't know why either.

**Comment by alanwei0** [comment]
ok, thanks

**Comment by afc163** [comment]
Oh, I see. If `onVisibleChange` is triggered when click menu item, then it is hard to keep menu open when click menu item by using controlled Dropdown.

**Comment by delesseps** [comment]
@afc163, @alanwei0  I'd like to reopen this a bug as it's still on a problem in ant 3.1.0, the API onVisibleChange is a little misleading.  Is there a way of triggering onVisibleChange event via another method on the Dropdown component?

**Comment by joenot443** [comment]
@afc163 I've also found this method to not be working. It shouldn't be in the documentation at all if the functionality has been abandoned.

**Comment by RyanLiu0235** [comment]
@afc163 Has this problem been solved?

**Comment by standbyoneself** [comment]
Still actual
