### ISSUE TITLE
Select displaying option value with reduced spaces

### ISSUE THREAD

**Issue by Pabl1k** [ant-design/ant-design#49948]
### Reproduction link

[https://ant.design/components/select#API](https://ant.design/components/select#API)

### Steps to reproduce

Add options with more than one space between words, for example: 
options={[
        { value: 'jack', label: 'Jack' },
        { value: 'lucy', label: 'Lucy' },
        { value: 'Yiminghe', label: 'yiminghe' },
        { value: 'NameWithSpaces', label: 'Name    With    Spaces' },
        { value: 'disabled', label: 'Disabled', disabled: true },
      ]}

### What is expected?

To display the same value as the label with all spaces (or to have a prop to decide which one to display)

### What is actually happening?

Spaces between words are trimmed

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | any |
| System | Windows 11 |
| Browser | Chrome |

**Comment by Pabl1k** [comment]
@afc163 The issue can be reproduced right in your documentation [here](https://ant.design/components/select#select-demo-basic), by adding/editing the option 
![image](https://github.com/user-attachments/assets/fbf487c8-232d-4bed-91b3-106b33be0973)

**Comment by afc163** [comment]
<img width="629" alt="图片" src="https://github.com/user-attachments/assets/1f176228-c95f-4f7a-930f-87badfa950b0">

Is it any problem? LGTM

**Comment by afc163** [comment]
OK, I see.

It is a native behavior of browser, not a antd's issue, see https://codepen.io/afc163-1472555193/pen/OJeMBLo?editors=0010
