### ISSUE TITLE
UploadDragger in sperate component and use in Form with scrollToFirstError not scroll

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#49944]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ecwpcq?file=demo.tsx)

### Steps to reproduce

When is create custom component with Upload Dragger and use in Form with scrollToFirstError  and into Form.Item add custom component into it and add rules require and when submit button don't scroll to first error

### What is expected?

must scroll to first error

### What is actually happening?

--

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | chrome |

**Comment by afc163** [comment]
You need `forwardRef`, see https://stackblitz.com/edit/react-ecwpcq-gq3ssf?file=UploadComp.tsx

```
import React from 'react';
import { InboxOutlined } from '@ant-design/icons';
import { Upload } from 'antd';

const UploadComp = React.forwardRef(({ ...rest }, ref) => {
  return (
    <Upload.Dragger name="files" action="/upload.do" {...rest} ref={ref}>
      <p className="ant-upload-drag-icon">
        <InboxOutlined />
      </p>
      <p className="ant-upload-text">
        Click or drag file to this area to upload
      </p>
      <p className="ant-upload-hint">Support for a single or bulk upload.</p>
    </Upload.Dragger>
  );
});

export default UploadComp;
```
