### ISSUE TITLE
 DatePicker - Incorrect Display of Dates in Turkish Date Format

### ISSUE THREAD

**Issue by C3maLi** [ant-design/ant-design#49956]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-datepicker-turkish-57dwc4)

### Steps to reproduce

In the DatePicker component, there was an issue with the incorrect display of days in Turkish date format. I resolved this by using the weekStart: 0 setting. However, the days are still displayed incorrectly. For example, even though July 2 falls on a Tuesday, the date popup still shows it as July 1.

### What is expected?

Accurate display of dates.

### What is actually happening?

Dates are displayed incorrectly.

[5.19.0](https://github.com/ant-design/ant-design/releases/tag/5.19.0) 
The problem started with this version.

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | 18 |
| System | Windows |
| Browser | Chrome  |

**Comment by afc163** [comment]
<img width="627" alt="图片" src="https://github.com/user-attachments/assets/370bbf34-bea4-4931-95ae-05a605e2e68b">

**Comment by C3maLi** [comment]
@afc163, I apologize for the lack of access, this problem arose because I did not make my project public. I would appreciate it if you had the opportunity to review it again.

**Comment by zombieJ** [comment]
Maybe https://github.com/react-component/picker/pull/848 fixed this?

**Comment by zombieJ** [comment]
Pls feel free to create new issue if still meet problem. Closed

**Comment by C3maLi** [comment]
> Maybe [react-component/picker#848](https://github.com/react-component/picker/pull/848) fixed this?

Thank you for your interest, the problem has been resolved.
