### ISSUE TITLE
Select  点击下拉框触发onSelect / onChange 事件， 在该事件中发请求得到结果后setState，这时候下拉框不消失，会重新弹出来。

### ISSUE THREAD

**Issue by Zuoguangcheng** [ant-design/ant-design#4996]
#### Environment(required)

- antd version:^2.7.1
- OS and its version：mac os 10.12.3
- Browser and its version:chrome 55.0.2883.95

#### What did you do? Please provide steps to re-produce your problem.

import React from 'react';
import {Select, Input} from 'antd';

import classNames from 'classnames';

const Option = Select.Option;

export default class List extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: ['a', 'b', 'c', 'd'],
    };

    [
      'handleSelect',
    ].map(method => this[method] = this[method].bind(this));
  }

  handleSelect(value) {
    this.setState({key: value});
    setTimeout(() => {
      this.setState({key: value});
    }, 200);
  }

  render() {
    let {data, key} = this.state;

    const searchCls = classNames({
      'ant-search-input': true,
      'ant-search-input-focus': focus,
    });

    let value = data[key];

    return (
      <Input.Group className={searchCls} style={{width: '200px'}}>
        <Select
          combobox
          size="large"
          notFoundContent="暂无信息"
          defaultActiveFirstOption={false}
          showArrow={false}
          filterOption={false}
          onSelect={this.handleSelect}
          onFocus={this.handleFocus}
          onBlur={this.handleBlur}
          dropdownStyle={{maxHeight: '200px'}}
        >
          {data.map((item, index) =>
            <Option key={index}>{item}</Option>
          )}
        </Select>
      </Input.Group>
    );
  }
}

点击下拉框触发onSelect / onChange 事件， 在该事件中发请求得到结果后setState，这时候下拉框不消失，会重新弹出来。这里使用延时模拟发请求返回数据setState。当直接setState点击下拉框是可以消失的，但是请求回来的数据再setState 重新渲染，下拉框就不会消失。

#### What do you expected?

点击下拉框，下拉框消失。

**Comment by afc163** [comment]
https://segmentfault.com/markdown

Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by Zuoguangcheng** [comment]
http://codepen.io/zuoguangcheng/pen/wJwGNv
@afc163 
已经复现。

**Comment by afc163** [comment]
BTW, it will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by Zuoguangcheng** [comment]
yes, later I will.@afc163

**Comment by RaoHai** [comment]
#4393

**Comment by afc163** [comment]
OK, trace on #4393
