### ISSUE TITLE
TreeSelect 搜索功能，命中关键字为中文时不加粗，英文时加粗

### ISSUE THREAD

**Issue by yyk112233** [ant-design/ant-design#49969]
### Reproduction link

[https://codepen.io/yyk111111111111/pen/bGPpNBa?editors=0010](https://codepen.io/yyk111111111111/pen/bGPpNBa?editors=0010)

### Steps to reproduce

搜索即可复现

### What is expected?

期望搜索关键字命中中文也会加粗

### What is actually happening?

搜索关键字命中中文不会加粗

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.3.1 |
| System | windows |
| Browser | chrome |

**Comment by Wxh16144** [comment]
其实是有加粗的，之不过权重是 500， 在 win 上面可能就不那么明显了，可以通过 css 样式覆盖字体字重为 blod 或者 600

**Comment by Wxh16144** [comment]
其实是有加粗的，只不过权重是 500， 在 win 上面可能就不那么明显了，可以通过 css 样式覆盖字体字重为 blod 或者 600

**Comment by afc163** [comment]
字体加粗不明显的问题，并非实现问题。
