### ISSUE TITLE
基于Antd封装上层业务组件，如何合并外部（调用方）传入的ConfigProvider theme配置？

### ISSUE THREAD

**Issue by gmqiyue** [ant-design/ant-design#49965]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-4cj6qk?file=demo.tsx)

### Steps to reproduce

1. 现有业务组件
```tsx
// BizButton.tsx
import { ConfigProvider, Button, Checkbox, Input, theme } from 'antd';

const BizButton = (props: any) => {
  // 这里返回的token数据类型为`GlobalToken`
  // `GlobalToken`内部类型定义是`AliasToken & ComponentTokenMap`
  // `ConfigProvider theme`属性类型为`ThemeConfig` => `{ token?: Partial<AliasToken>; components?: ComponentsConfig; ... }`
  const { token } = theme.useToken()

  return (
    <ConfigProvider
      // 这里是Biz组件内置的默认主题
      theme={{
        token: {
          colorPrimary: 'red',
        },
        components: {
          Button: {
            colorPrimary: '#141414',
          },
          Input: {
            colorPrimary: '#141414',
            borderRadius: 10000,
          },
          Checkbox: {
            borderRadius: 10000,
          },
        },
        ...token,
      }}
    >
      <Button {...props} />
      <Input />
      <Checkbox />
    </ConfigProvider>
  );
};

export default BizButton;
```

2. 业务使用

```tsx
// Page.tsx
import BizButton from './BizButton';

export default (props: any) => {
  return (
    <ConfigProvider
      // 这里是业务定制的主题
      theme={{
        token: {
          colorPrimary: 'green',
        },
        components: {
          Button: {
            colorPrimary: 'white',
          },
          Input: {
            colorPrimary: 'white',
            borderRadius: 0,
          },
          Checkbox: {
            borderRadius: 0,
          },
        },
      }}
    >
      <BizButton>按钮</BizButton>
    </ConfigProvider>
  );
};
```

### What is expected?

希望BizButton支持透传外部定制的主题，当外部没有传入时，使用内置的主题配置

### What is actually happening?

没有办法正确合并config并向下透传

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | macOS |
| Browser | Chrome126.0.6478.128 |

---
1. 通过`theme.useToken()`拿到的token属性类型是一个联合类型`AliasToken & ComponentTokenMap`，与ConfigProvider的theme数据结构不匹配。
2. BizButton是一个案例，可能里面有使用很多个antd的组件，在这里逐个拿到外部传入的token去覆盖不太现实，antd内部是否有提供拿到符合ConfigProvider theme属性数据结构的API？
3. `ConfigProvider theme`属性类型为`ThemeConfig` => `{ token?: Partial<AliasToken>; components?: ComponentsConfig; ... }`
4. `theme.useToken()`返回的`token`属性类型为`GlobalToken` => `AliasToken & ComponentTokenMap`

**Comment by zombieJ** [comment]
`useToken` 获取的是计算后的值，包含了所有推导的色盘。是 `theme` 的超集。如果你需要的是原始态的 `theme` 可以参考 antd 的 ConfigProvider 的实现自行封装一个 ConfigProvider 将需要的内容传递下去。

**Comment by gmqiyue** [comment]
> `useToken` 获取的是计算后的值，包含了所有推导的色盘。是 `theme` 的超集。如果你需要的是原始态的 `theme` 可以参考 antd 的 ConfigProvider 的实现自行封装一个 ConfigProvider 将需要的内容传递下去。

意思是说我需要自己实现一个BizConfigProvider给业务层来使用，而不是用antd 的 ConfigProvider，请问我这样理解对么？

**Comment by Wxh16144** [comment]
不明觉厉，其实我感觉你可以无脑用 `lodash.merge` 即可

**Comment by gmqiyue** [comment]
> 不明觉厉，其实我感觉你可以无脑用 `lodash.merge` 即可

尝试过了，这两个数据结构不同，合并后，useToken中的配置并不会覆盖BizButton里的components和token

**Comment by Wxh16144** [comment]
业务调用你的组件，也用了 antd 的 CP 包裹，你内部实现某个组件也用 antd CP 包裹。 antd 默认就 merge 了吧 🤔

**Comment by Wxh16144** [comment]
推荐你看看 [antd-style](https://ant-design.github.io/antd-style/zh-CN/guide)，借鉴一下 [lobe-ui](https://ui.lobehub.com/) 是如何扩展主题包的。 （我司的组件库就是参考 lobe-ui 方式实现的

**Comment by gmqiyue** [comment]
> 业务调用你的组件，也用了 antd 的 CP 包裹，你内部实现某个组件也用 antd CP 包裹。 antd 默认就 merge 了吧 🤔

antd的CP采用的策略是就近原则，以上面的例子来说，外部传入components.Button主题配置，我的button组件也用了antd的CP，配置了同样的属性，那么就是以我的配置为主的

**Comment by gmqiyue** [comment]
> 推荐你看看 [antd-style](https://ant-design.github.io/antd-style/zh-CN/guide)，借鉴一下 [lobe-ui](https://ui.lobehub.com/) 是如何扩展主题包的。 （我司的组件库就是参考 lobe-ui 方式实现的

好的，我去学习一下，感谢
