### ISSUE TITLE
Checkbox.Group 中配置Options的非预期行为，value值会错误的按照options中索引排序

### ISSUE THREAD

**Issue by RushKoala** [ant-design/ant-design#49972]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-yzbm4w?file=demo.tsx)

### Steps to reproduce

const options = [
     { label: 'A', value: 'A' },
      { label: 'B', value: 'B' },
]

<Checkbox.Group
  options={options}
/>

<Checkbox.Group>
  {options.map(({ label, value }) => (
      <Checkbox value={value}>{label}</Checkbox>
  ))}
<Checkbox.Group>

这两种配置options的方式，在onChange时和表单中value的表现不同
第一种value会按options的顺序强制排序 先勾选B再勾选A是["A", "B"]
第二种value的顺序和选择顺序一致，先勾选B再勾选A是["B", "A"]

这种现象在antd4/5中都存在

### What is expected?

value的顺序和选择顺序一致，先勾选B再勾选A是["B", "A"]

### What is actually happening?

按options的顺序强制排序 先勾选B再勾选A是["A", "B"]

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | mac |
| Browser | chrome |

---
https://github.com/ant-design/ant-design/blob/master/components/checkbox/Group.tsx

onChange?.(
        newValue
          .filter((val) => registeredValues.includes(val))
          .sort((a, b) => {
            const indexA = memoOptions.findIndex((opt) => opt.value === a);
            const indexB = memoOptions.findIndex((opt) => opt.value === b);
            return indexA - indexB;
          }),
      );

扫了下源码 应该是这个引起的，不知道是什么需求要求按索引排序

**Comment by Wxh16144** [comment]
https://github.com/ant-design/ant-design/commit/c8d5243b9759b7cf0e85fde445105e18ac1a1fe2 这次提交加入的排序 @ yoyo837

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/17297 
https://github.com/ant-design/ant-design/pull/17342

我去找大佬要个指导意见

**Comment by yoyo837** [comment]
@zombieJ 求一个修改指导意见

**Comment by MadCcc** [comment]
依赖顺序不太可靠，有什么需求是需要依赖这个顺序的？

**Comment by RushKoala** [comment]
> #17297 #17342
> 
> 我去找大佬要个指导意见

有结论了么？目前最主要的是Checkbox.Group通过options和children两种形式开发的表现不同，如果需要sort的话建议增加一个api

**Comment by zombieJ** [comment]
我的错。排序没有意义， React 里通过 `key` 调整顺序这种收集也是感知不到的。

ref: https://github.com/ant-design/ant-design/issues/17297#issuecomment-505771475

但是已经有了的就先不下掉了，也没有必要全部都拉成一致的。
