### ISSUE TITLE
Popconfirm包裹ConfigProvider后 Popconfirm无效

### ISSUE THREAD

**Issue by oyjs1989** [ant-design/ant-design#49974]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-zkfj6i?file=demo.tsx)

### Steps to reproduce

我希望之改变当前Button的颜色背景，外层的Popconfirm不变化，在使用ConfigProvider包裹Button，外层Popconfirm失效

### What is expected?

弹出提示窗

### What is actually happening?

未弹出Popconfirm

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.2.0 |
| System | linux |
| Browser | chrome 126.0.6478.127 |

**Comment by Wxh16144** [comment]
临时解法：多套一个 `<div >`, 因为需要把点击事件透传下去

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/49982#issuecomment-2242286296
