### ISSUE TITLE
Security Vulnerability in Ant-Design

### ISSUE THREAD

**Issue by pwntester** [ant-design/ant-design#49971]
### Reproduction link

[https://securitylab.github.com/](https://securitylab.github.com/)

### Steps to reproduce

Cant disclose publicly

### What is expected?

The library is secure

### What is actually happening?

The library contains critical security vulnerabilities

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | all |
| System | all |
| Browser | all |

---
Please enable Private Vulnerability Report (PVR) on your GitHub repo or provide an email address in your Security Policy so I can disclose the details

请在您的 GitHub 仓库中启用私有漏洞报告（PVR），或在您的安全政策中提供一个电子邮件地址，以便我可以披露详细信息。

**Comment by zombieJ** [comment]
PVR enabled. Pls feel free to report
