### ISSUE TITLE
Some Safari issues

### ISSUE THREAD

**Issue by NeonXP** [ant-design/ant-design#4997]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: macOS 10.12.3
- Browser and its version: Safari 10.0.3 (12602.4.8)

#### What did you do? Please provide steps to re-produce your problem.

I just open documentation on ant.design website https://ant.design/components/input-number/ and https://ant.design/components/form/ pages.

#### What do you expected?

Correct work on Safari

#### What happen?

InputNumber has no bottom border, placeholders on some fields not in center 

#### Re-producible online demo

Just open https://ant.design/components/input-number/ and https://ant.design/components/form/ on Safari 10.0.3
<img width="1014" alt="2017-02-22 10 58 03" src="https://cloud.githubusercontent.com/assets/190940/23202410/e2d3e28c-f8ee-11e6-8d08-595ec9ee5b66.png">
<img width="998" alt="2017-02-22 10 57 33" src="https://cloud.githubusercontent.com/assets/190940/23202417/e6fe5428-f8ee-11e6-9928-f73ddf7725ac.png">
<img width="346" alt="2017-02-22 10 57 24" src="https://cloud.githubusercontent.com/assets/190940/23202422/eba602be-f8ee-11e6-9096-a5c435b0f6bc.png">

.

**Comment by afc163** [comment]
ref #4987
