### ISSUE TITLE
antd-table 如何根据表格数据中的颜色值，更改表格行的背景色,rowClassName并不能满足要求，颜色值是服务端提供的，事先不知道会有多少个颜色，不能通过声明class样式来使用rowClassName

### ISSUE THREAD

**Issue by yyyyffqqqq** [ant-design/ant-design#49989]
### What problem does this feature solve?

antd-table 根据表格数据中的颜色值，更改表格行的背景色。目前table属性只提供rowClassName进行样式修改，并不能满足要求，而是根据后端返回的颜色值进行修改，如果的render方法里面进行单元格的自定义的话，自定义标签设置的颜色会覆盖表格的hover的高亮颜色

### What does the proposed API look like?

antd-table 能够根据表格数据中的颜色值，更改表格行的背景色，目前值提供rowClassName的属性，并不能满足要求，希望能够提供rowStyle的属性进行配置，例如： rowStyle ={(record) => {
  return { background: record.rowColor }
}

**Comment by afc163** [comment]
```jsx
<Table
  onRow={(record) => ({
    style: { backgroundColor: '#000' },
  })}
/>
```

**Comment by yyyyffqqqq** [comment]
试过这个，我使用background没成功
onRow={(record) => ({
    style: { background: '#000' },
  })}

**Comment by afc163** [comment]
我试了一下是 ok 的：https://codepen.io/afc163-1472555193/pen/NWZNaZP?editors=0010

**Comment by yyyyffqqqq** [comment]
还是不行，初始化完成的时候是看到设置为黑色了，但是渲染完成onRow配置的颜色就被覆盖了
onRow={(record) => ({
style: { background: '#000' },
})}

**Comment by yyyyffqqqq** [comment]
使用的是最新版本的5.18.3

**Comment by yyyyffqqqq** [comment]
列加上fixed: 'left', 就不行，不加这个就可以

**Comment by afc163** [comment]
试试 https://github.com/ant-design/ant-design/issues/6730#issuecomment-313017332 后一个。
