### ISSUE TITLE
DatePicker disabledDateTime 函数入参总是会传入此时此刻的时间

### ISSUE THREAD

**Issue by DerrickTel** [ant-design/ant-design#49988]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn](https://ant-design.antgroup.com/components/date-picker-cn)

### Steps to reproduce

const disabledDateTime = (current) => {
  console.log(dayjs(current).format('YYYY-MM-DD HH:mm:ss'))
  return {
  disabledHours: () => range(0, 24).splice(4, 20),
  disabledMinutes: () => range(30, 60),
  disabledSeconds: () => [55, 56],
}};

### What is expected?

不要再调用了，我选了时间之后，确实输出了我选择的日期，但是随后立即又调用了，并且传入了此时此刻的日期，导致我要设置不可用时间的时候出现了问题。

### What is actually happening?

入参不要出现此时此刻的时间

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | latest |
| System | window |
| Browser | latest |

---
目前的需求是：默认时间假设是2024-07-18 18:18:18
如果用户选择了2024-07-17 禁用时间就需要改为空，都允许选择，如果是2024-07-18的的话18:18:18后面的时间就不允许选择

**Comment by DerrickTel** [comment]
https://stackblitz.com/run?file=demo.tsx

**Comment by afc163** [comment]
> 导致我要设置不可用时间的时候出现了问题。

出现了什么问题，请具体描述你期待的日期组件行为表现，和你认为是异常的日期组件的行为表现。

入参出现此时此刻的时间不代表是异常，需要明确这个默认行为如何造成了问题。

**Comment by DerrickTel** [comment]
> > 导致我要设置不可用时间的时候出现了问题。
> 
> 出现了什么问题，请具体描述你期待的日期组件行为表现，和你认为是异常的日期组件的行为表现。
> 
> 入参出现此时此刻的时间不代表是异常，需要明确这个默认行为如何造成了问题。

抱歉，我这里没法截图。我只能复制。或者描述
我先描述一下：比如我选择了2024年6月20日这个日期。
在disabledDateTime 这个函数的回调里面默认会传参
```
const disabledDateTime = (current) => {
  console.log(dayjs(current).format('YYYY-MM-DD HH:mm:ss'))
  return {
  disabledHours: () => range(0, 24).splice(4, 20),
  disabledMinutes: () => range(30, 60),
  disabledSeconds: () => [55, 56],
}};
```
这个current，他会输出两次。一次是2024年6月20日，还有一次是此时此刻。
您可以跑一下这个demo：https://ant-design.antgroup.com/components/date-picker-cn
任意在线例子都可以复现，然后把disabledDateTime 用我的代码去log，就知道了。

**Comment by DerrickTel** [comment]
2024-07-30 00:00:00

**Comment by DerrickTel** [comment]
```
import React from 'react';
import './index.css';
import { DatePicker, Space } from 'antd';
import type { GetProps } from 'antd';
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';

type RangePickerProps = GetProps<typeof DatePicker.RangePicker>;

dayjs.extend(customParseFormat);

const { RangePicker } = DatePicker;

const range = (start: number, end: number) => {
  const result = [];
  for (let i = start; i < end; i++) {
    result.push(i);
  }
  return result;
};

// eslint-disable-next-line arrow-body-style
const disabledDate: RangePickerProps['disabledDate'] = (current) => {
  // Can not select days before today and today
  return current && current < dayjs().endOf('day');
};

const disabledDateTime = (current) => {
  console.log(dayjs(current).format('YYYY-MM-DD HH:mm:ss'))
  return {
  disabledHours: () => range(0, 24).splice(4, 20),
  disabledMinutes: () => range(30, 60),
  disabledSeconds: () => [55, 56],
}};

const disabledRangeTime: RangePickerProps['disabledTime'] = (_, type) => {
  if (type === 'start') {
    return {
      disabledHours: () => range(0, 60).splice(4, 20),
      disabledMinutes: () => range(30, 60),
      disabledSeconds: () => [55, 56],
    };
  }
  return {
    disabledHours: () => range(0, 60).splice(20, 4),
    disabledMinutes: () => range(0, 31),
    disabledSeconds: () => [55, 56],
  };
};

const App: React.FC = () => (
  <Space direction="vertical" size={12}>
    <DatePicker
      disabledDate={disabledDate}
      disabledTime={disabledDateTime}
      showTime={{ defaultValue: dayjs('00:00:00', 'HH:mm:ss') }}
    />
    <DatePicker picker="month" disabledDate={disabledDate} />
    <RangePicker disabledDate={disabledDate} />
    <RangePicker
      disabledDate={disabledDate}
      disabledTime={disabledRangeTime}
      showTime={{
        hideDisabledOptions: true,
        defaultValue: [dayjs('00:00:00', 'HH:mm:ss'), dayjs('11:59:59', 'HH:mm:ss')],
      }}
      format="YYYY-MM-DD HH:mm:ss"
    />
  </Space>
);

export default App;
```

**Comment by DerrickTel** [comment]
我的需求是：如果默认时间是2024-07-19 18:18:18
当我选择2024-07-18 的时候，disableTime 应该全部放开
如果选择的是2024-07-19。那么就要根据时分秒可以设置disable
比如选了18点，那么分就只能选00~17
而秒就可以选00~59

**Comment by DerrickTel** [comment]
我在想，是不是这个disable 应该根据我给的dayjs 来进行配置呢，我发现如果要我来配置disableDate和disableTime。会显得非常吃力，比如这个例子

> 我的需求是：如果默认时间是2024-07-19 18:18:18 当我选择2024-07-18 的时候，disableTime 应该全部放开 如果选择的是2024-07-19。那么就要根据时分秒可以设置disable 比如选了18点，那么分就只能选00-17 而秒就可以选00-59

**Comment by DerrickTel** [comment]
> 我在想，是不是这个disable 应该根据我给的dayjs 来进行配置呢，我发现如果要我来配置disableDate和disableTime。会显得非常吃力，比如这个例子
> 
> > 我的需求是：如果默认时间是2024-07-19 18:18:18 当我选择2024-07-18 的时候，disableTime 应该全部放开 如果选择的是2024-07-19。那么就要根据时分秒可以设置disable 比如选了18点，那么分就只能选00-17 而秒就可以选00-59

我的小时，分钟，秒都是需要额外的去写判断但是如果直接用dayjs，只需要isBefore，isAfter就可以完成了

**Comment by DerrickTel** [comment]
@afc163 大佬有空帮忙看看哈

**Comment by afc163** [comment]
> 我在想，是不是这个disable 应该根据我给的dayjs 来进行配置呢，我发现如果要我来配置disableDate和disableTime。

这个写起来确实是非常麻烦，新的 limit API 还没开始设计。cc @zombieJ

**Comment by afc163** [comment]
目前确实会跑两边，原因不明：

https://github.com/react-component/picker/blob/c8b9c0a7cd9c7606e49318a37238ae9b4e68e444/src/hooks/useTimeInfo.ts#L107
https://github.com/react-component/picker/blob/c8b9c0a7cd9c7606e49318a37238ae9b4e68e444/src/hooks/useTimeInfo.ts#L190

可能需要 @zombieJ 有空看看。

**Comment by zombieJ** [comment]
点击此刻会设置 DateTime 为当前时间，所以需要传递给 disabled 方法来确定一下 `此刻` 是否可以点击。你不应该依赖 `disabledTime` 来确定用户当前选择的日期是什么，而是如实的根据传入日期做判断即可。

> 当我选择2024-07-18 的时候，disableTime 应该全部放开
> 如果选择的是2024-07-19。那么就要根据时分秒可以设置disable

直接照着写就行了，DatePicker 会正确的反应到面板上（此刻只会被此刻消费， 面板不会消费它）：

https://stackblitz.com/edit/react-co2qyn?file=demo.tsx

#### 选择 07-18

<img width="511" alt="截屏2024-07-24 17 17 06" src="https://github.com/user-attachments/assets/f134da96-06ac-435c-bc7b-25c00402085d">

#### 选择 07-19

<img width="487" alt="截屏2024-07-24 17 17 25" src="https://github.com/user-attachments/assets/4c1cad5a-9279-4037-98bc-b61d4b8050dc">

**Comment by zombieJ** [comment]
这里就先关了哈~

**Comment by DerrickTel** [comment]
我走了一下你的demo，你是限定好了特殊日期的时间的disable，我现在希望7月19日之前的日期都是disabled的要怎么做呢？

类似
```
const disabledDate: RangePickerProps['disabledDate'] = (current) => {
  // Can not select days before today and today
  return current && current < dayjs().endOf('day');
};
```

这种的就没法完成，因为固定会传入一个此刻的时间

**Comment by DerrickTel** [comment]
> 我走了一下你的demo，你是限定好了特殊日期的时间的disable，我现在希望7月19日之前的日期的时间都是disabled的要怎么做呢？
> 
> 类似
> 
> ```
> const disabledDate: RangePickerProps['disabledDate'] = (current) => {
>   // Can not select days before today and today
>   return current && current < dayjs().endOf('day');
> };
> ```
> 
> 这种的就没法完成，因为固定会传入一个此刻的时间
> 
> @zombieJ

@zombieJ 哥，有空帮忙看看
