### ISSUE TITLE
希望可以给table设置固定高度

### ISSUE THREAD

**Issue by Qyokizzzz** [ant-design/ant-design#49980]
### What problem does this feature solve?

目前的table高度是根据数据数量动态变化，数据过多时用户需要拉到底部才能看到分页器，两页之间数据量不一致时会导致分页器时上时下。给table设置固定高度可以解决这两个问题。

### What does the proposed API look like?

bodyHeight={100}或者bodyStyle={{ height: '100px' }}

**Comment by afc163** [comment]
Duplicate of #49445
