### ISSUE TITLE
ant design table render issue with nexths, Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.

### ISSUE THREAD

**Issue by TrumpDk** [ant-design/ant-design#49983]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/nextjs-dzyqv9?file=app%2Fpage.tsx,service%2Faxios.ts)

### Steps to reproduce

I am quite new to Nextjs. here are the steps to reproduce the issue I am facing. If don't add  'use server' directive to render functionality of columns data, it will throw error like this 'Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". 
```const columns: TableColumnsType = [
  {
    title: "",
    dataIndex: "id",
    key: "id",
  },
  {
    title: "歌曲名称",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "时长",
    dataIndex: "dt",
    key: "dt",
  },
  {
    title: "歌手",
    render: async (record) => {
      const tempStrArr: string[] = [];
      record.ar.forEach((artist: IArtistType) => {
        tempStrArr.push(artist.name);
      });

      return tempStrArr.join(",");
    },
  },
  {
    title: "专辑",
    render: async (record) => {
      return record.al.name;
    },
  },
]```

// If add 'use server' directive, the error will disapear, but 'getInitData' functionality will be called many times from client side.
```const columns: TableColumnsType = [
  {
    title: "",
    dataIndex: "id",
    key: "id",
  },
  {
    title: "歌曲名称",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "时长",
    dataIndex: "dt",
    key: "dt",
  },
  {
    title: "歌手",
    render: async (record) => {
     'use server'
      const tempStrArr: string[] = [];
      record.ar.forEach((artist: IArtistType) => {
        tempStrArr.push(artist.name);
      });
      return tempStrArr.join(",");
    },
  },
  {
    title: "专辑",
    render: async (record) => {
     'use server'
      return record.al.name;
    },
  },
]```

### What is expected?

expect that 'getInitData' functionality only be called once from server side.

### What is actually happening?

'getInitData' functionality just be called once from server side but so many times from client side.

| Environment | Info |
| --- | --- |
| nextjs | 14.2.5 |
| antd | 5.19.1 |
| React | 18.3.3 |
| System | win11 |
| Browser | chrome 126.0.6478.128 |

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by TrumpDk** [comment]
here are the screen shots:
![Screenshot 2024-07-20 004744](https://github.com/user-attachments/assets/822d675e-b1d8-4b58-8ceb-6b499e9a0bb8)
![Screenshot 2024-07-20 004827](https://github.com/user-attachments/assets/0966f488-a3bb-4009-ae6e-0e0167fa6e4e)

**Comment by kistgabe** [comment]
Same here, any solution?

**Comment by HaoxuanGuo** [comment]
This is because next.js believes that all functions should be executed on the server side. However, functions in antd are to be executed on the client side. This problem can be solved by manually marking it as being executed on the client side, that is, adding `"use client";` at the beginning of the file;

**Comment by TrumpDk** [comment]
> This is because next.js believes that all functions should be executed on the server side. However, functions in antd are to be executed on the client side. This problem can be solved by manually marking it as being executed on the client side, that is, adding `"use client";` at the beginning of the file;

you mean we can only render this table via client component, will ant design table support server side rendering in the future?
@HaoxuanGuo

**Comment by HaoxuanGuo** [comment]
Yes, the table component can only be rendered on the client side, and pre-rendering on the server side will not work.

Like you, I am only a user of ant design, not a developer, so I don't know the future plans. But from my intuition, it should be very difficult to render something like a table that needs to be dynamically refreshed on the server side. Even Next UI, which is as good as its own, does not support this feature, not to mention the third-party ant design.

@TrumpDk

**Comment by TrumpDk** [comment]
Resolved by using client component.
