### ISSUE TITLE
tab切换问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#4999]
关闭tab页面的时候即使关闭的不是当前显示tab页面也会有一个切换的动作，实际上若是关闭的不是当前显示的tab页不应该是页面不发生变化，只是tab标签减少了么？
演示见官网案例
https://ant.design/components/tabs-cn/

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
If we close tabs before current, this bug will occur.

If we close tabs after current, it works fine.

**Comment by yesmeck** [comment]
看起来已经被修正了？

**Comment by benjycui** [comment]
@afc163 发现切换动画被关掉了，是设计规范被更新了么？

**Comment by afc163** [comment]
啥动画？没变啊

**Comment by benjycui** [comment]
@afc163 我理解错了 type=card 时 animated 默认 false。

@yesmeck 这个问题没有修复，只是 https://ant.design/components/tabs-cn/#components-tabs-demo-editable-card 没有开启动画而已，你加上 Tabs[animated] 就知道了。

**Comment by afc163** [comment]
这是正常的，关闭左侧 tab 有一个 margin-left 的变动，导致有动画出现。
