### ISSUE TITLE
将 css 变量通过 config-provider 注入到 document.documentElement

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#49999]
### What problem does this feature solve?

解决 message、notification、modal 等组件无法应用 css 变量的问题。因为这些组件的上下文没有处于 config-provider 组件中，导致变量无法正常得到应用，需要借助 useApp().message 或者 message.useMessage()。但这样并不利于用户迁移，而且使用麻烦。

### What does the proposed API look like?

在原有功能保持不变的基础上，提供一个新的变量 root: boolean 用以实现将 css 变量注入到 document.documentElement 中
```tsx
<ConfigProvider
      locale={zhCN}
      theme={{ cssVar: true, token, components, hashed: false, root: true }}
    >
</ConfigProvider>
```

**Comment by Wxh16144** [comment]
之前遇到过有人将 App 的 component 设置为 false 导致样式无法挂载，然后建议改成 `:root`,  但是现在是每一个 CP 都会有个 hash id 来确保生效范围。

如果将样式放在 documentElement ，这类组件也会出现上下文错误问题，如果项目没有多层 CP 改主题（局部主题）其实可以忽略 message 的静态警告

**Comment by zhaokejian** [comment]
可以用 ConfigProvider.config
https://ant.design/components/config-provider-cn/#configproviderconfig

**Comment by MadCcc** [comment]
不支持挂在 root 上，会破坏局部主题效果，root 上的不生效的

**Comment by guaijie** [comment]
> 不支持挂在 root 上，会破坏局部主题效果，root 上的不生效的 推荐使用 useApp，静态方法会在后续版本中废弃

如果你废弃掉静态注入，那在非组件中使用就会出现样式问题（比如再拦截器中使用）
