### ISSUE TITLE
Slider onChangeComplete is not called when clicking a mark

### ISSUE THREAD

**Issue by pbrzosko** [ant-design/ant-design#49997]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-lnb21s?file=demo.tsx)

### Steps to reproduce

1. Drag top slider with a mouse and drop
2. Click top slider's mark

### What is expected?

When you click a mark, it is expected to have onChange and then onChangeCompleted handlers called.

### What is actually happening?

There is only onChange handler called, when you click a mark.

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 18.3.1 |
| System | macOS Sonoma 14.5 |
| Browser | Google Chrome Version 126.0.6478.127 (Official Build) (arm64) |

---
This is a little awkward, because on onChangeCompleted one would normally send updates up, because those intermediate ones when user drags are not needed. And it can not be achieved, because this is not called when you click a mark.

**Comment by MadCcc** [comment]
Cannot reproduce, anymore details?

**Comment by pbrzosko** [comment]
Hmm, in the reproduction repo link, when you click on a mark of the slider, do you get one console log (with onChange) or two console logs (with onChange and onChangeComplete) ?

I get only one, but I think both callback should be called.

**Comment by pbrzosko** [comment]
Here is the video:
https://github.com/user-attachments/assets/8c70d537-a924-4acd-8b9b-6c87453f292c

**Comment by pbrzosko** [comment]
Thanks a lot. In which antd version I can expect this fix?

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/slider/releases/tag/v11.1.5

Please remove node_modules / package-lock.json / yarn.lock / pnpm-lock.yaml and reinstall.

**Comment by pbrzosko** [comment]
@afc163 that won't work, as antd has a dependency to rc-slide with 10.x version: `"rc-slider": "~10.6.2",`. So when can I expect this to be included in antd?

**Comment by afc163** [comment]
Upgraded in feature branch, next minor version(5.20.0) will include it which should released in this month.
