### ISSUE TITLE
出现多个 Notification 时 Notification 会闪烁

### ISSUE THREAD

**Issue by SuperCodeCandy** [ant-design/ant-design#49990]
### Reproduction link

[https://ant-design.antgroup.com/components/notification-cn](https://ant-design.antgroup.com/components/notification-cn)

### Steps to reproduce

点击按钮即可

### What is expected?

多个 Notification  不闪烁

### What is actually happening?

有多个Notification 时，Notification 会闪烁

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18 |
| System | Windows 11 |
| Browser | Google 版本 124.0.6367.61 |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/48608
