### ISSUE TITLE
select组件显示值而非描述

### ISSUE THREAD

**Issue by dqaria** [ant-design/ant-design#50]
![](https://t.alipayobjects.com/images/T1sllgXnNoXXXXXXXX.png)
建议默认显示描述，或者提供配置项

**Comment by yiminghe** [comment]
是否暴露 optionLabelProp ？

http://react-component.github.io/select/examples/force-suggest.html

**Comment by dqaria** [comment]
配置optionLabelProp="children"后显示正常，但感觉默认显示label内容比较合理

**Comment by afc163** [comment]
确实默认显示 label 较合理。

**Comment by yiminghe** [comment]
这个变更不兼容了，目前首页search 组件点击后，input 内容是 [object]

**Comment by afc163** [comment]
在 [这里](https://github.com/ant-design/ant-design/commit/0611570caa68576a194a01db2c01745d5566c13e) 修复了这个问题。

但问题的实质是 search 搜索框的 inputValue 无法接受 React.Element 的值。https://github.com/react-component/select/blob/a05ac8e2809fa19e197d82624186dbde1144a14d/src/Select.jsx#L211

是否在 `optionLabelProp="children"` 的情况下转成 text ？

**Comment by yiminghe** [comment]
这个不合理，不应该转啊，用户应该自己选择，下拉只是一个展示而已，真实 input 的值需要指定
