### ISSUE TITLE
因为加了一个行高属性导致影响部分form表单内容

### ISSUE THREAD

**Issue by jianhuagao** [ant-design/ant-design#50007]
### Reproduction link

[https://ant-design.antgroup.com/components/form-cn#components-form-demo-normal-login](https://ant-design.antgroup.com/components/form-cn#components-form-demo-normal-login)

### Steps to reproduce

表单内自定义的内容以前的行高是继承的父级的，因为content加了lineHeight: '100%',导致之前写的内容继承的行高丢失了，很多内容出现了样式问题，在官网的form的login demo就找到一处受影响的
造成样式问题的pr  -》 #49635  

### What is expected?

修复对齐bug不能影响子级的行高

### What is actually happening?
![Snipaste_2024-07-22_17-59-56](https://github.com/user-attachments/assets/eccbdd84-9b53-4154-ba56-7068d446fb80)
![Snipaste_2024-07-22_18-03-15](https://github.com/user-attachments/assets/84a9e88c-76b0-4f9b-9b2e-d6de7d7c6443)

![Snipaste_2024-07-22_17-54-06](https://github.com/user-attachments/assets/e2589887-ff9e-44e5-96d4-894ede057803)
![Snipaste_2024-07-22_17-55-06](https://github.com/user-attachments/assets/377c86f9-c41c-4db7-8709-57bfdee325b0)

因为修复对齐bug导致影响了更多元素

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.0 |
| System | Windows10 |
| Browser | Microsoft Edge 100.0.1185.50 (正式版本) (64 位) |

**Comment by jianhuagao** [comment]
https://stackblitz.com/edit/react-2ggx6r?file=index.css,demo.tsx

@afc163  这个是官网的demo，也是受到这个样式导致的，这个样式破坏性蛮大的，以前很多继承的行高都会丢失

**Comment by afc163** [comment]
@wanpan11 https://github.com/ant-design/ant-design/pull/49635 确实会影响文本的默认 line-height，我倾向于先回滚。

**Comment by wanpan11** [comment]
我看看🤧

**Comment by wanpan11** [comment]
好像没有太好的办法 我先回滚吧

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50020
