### ISSUE TITLE
关于Popconfirm嵌套一个disabled的Button，是否能给Popconfirm加个disabled属性

### ISSUE THREAD

**Issue by leifeng** [ant-design/ant-design#5000]
antd 版本:2.7.2
操作系统及其版本:windows10
浏览器及其版本:chrome最新版

Popconfirm嵌套一个disabled的Button,能否点击时不弹出层，或者Popconfirm也能有个disabled的属性阻止弹出,

http://codepen.io/leifeng/pen/MpgyZJ

**Comment by afc163** [comment]
It is not neccessary.

```jsx
const { disabled } = this.state;
const btn = <Button disabled={disabled} />;
return {disabled ? <Popconfirm>{btn}</Popconfirm> : btn};
```
