### ISSUE TITLE
import type { CheckboxValueType } from 'antd/es/checkbox/Group' 失效

### ISSUE THREAD

**Issue by wb-wenbei** [ant-design/ant-design#50000]
### Reproduction link

[https://github.com/ant-design/ant-design/pull/49073](https://github.com/ant-design/ant-design/pull/49073)

### Steps to reproduce

在代码里写入下面一行代码
```typescript
import type { CheckboxValueType } from 'antd/es/checkbox/Group'
```
在antd5.15.1版本中正常使用，升级到5.19.3时出现引入报错

### What is expected?

兼容5.15.1版本

### What is actually happening?

不兼容5.15.1版本

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome |

**Comment by crazyair** [comment]
现在 Checkbox 已经是自动推导了，不需要写死的 CheckboxValueType 了

**Comment by zombieJ** [comment]
参考 [antd 里常用的 TypeScript 工具方法](https://ant-design.antgroup.com/docs/blog/type-util-cn)，不要直接依赖内部类型。这是不保证版本一致的。

**Comment by wb-wenbei** [comment]
好的，十分感谢你们为开源社区所做的付出！ @li-jia-nan @crazyair @zombieJ

**Comment by afc163** [comment]
哇，50000 靓号被你拿到了！
