### ISSUE TITLE
[Collapse] event.stopPropagation() not work when used in conjunction with Modal

### ISSUE THREAD

**Issue by vanvixi** [ant-design/ant-design#50006]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-rgilqp-13kwtl?file=demo.tsx)

### Steps to reproduce

Case 1: Click `SettingIcon` -> Click outsite Modal.

Case 2: Click `SettingIcon` -> Click close Modal.

### What is expected?

Active state of the Collapse component will not be changed.

### What is actually happening?

The Active state of the Collapse component is being changed when clicking outside the Modal or when the Modal is closed.

| Environment | Info |
| --- | --- |
| antd | 5.19.2 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome, Safari, Edge |

https://github.com/user-attachments/assets/a3eb4d7a-2760-45cb-84cf-7455366052d0

**Comment by hiimtrung** [comment]
same issues

**Comment by duydktastech** [comment]
same issue

**Comment by Wxh16144** [comment]
Wrap it in a container and prevent the event from spreading.

```diff
   return (
-    <>
+    <div onClick={(event) => event.stopPropagation()}>
       <SettingOutlined
         onClick={(event) => {
           showModal();
           // If you don't want click extra trigger collapse, you can prevent this:
           event.stopPropagation();
         }}
       />
       <Modal
         title="Basic Modal"
         open={isModalOpen}
         onOk={handleOk}
         onCancel={handleCancel}
         maskClosable={false}
         // getContainer={() => containterRef.current}
       >
         <p>Some contents...</p>
         <p>Some contents...</p>
         <p>Some contents...</p>
       </Modal>
-    </>
+    </div>
   );

```
