### ISSUE TITLE
change OTP inputs type to number 

### ISSUE THREAD

**Issue by zMohammadz84** [ant-design/ant-design#50015]
### What problem does this feature solve?

 OTP input type is text but it must be number

### What does the proposed API look like?

add type props to OTP inputs

**Comment by zombieJ** [comment]
OTP is not number only (e.g. Steam use 0-9A-Z). But maybe it can support `type=number` instead.

**Comment by hungtcs** [comment]
+1, very useful when using TOTP (Time-based One-Time Password).

I'm currently using [antd-input-otp](https://www.npmjs.com/package/antd-input-otp), which provides an inputType property similar to the one above to control the type of input.

Incidentally, it would be nice to have support for autoSubmit.
