### ISSUE TITLE
关于Checkbox 文字与勾选框上下不对称问题

### ISSUE THREAD

**Issue by GoDotDotDot** [ant-design/ant-design#5001]
![image](https://cloud.githubusercontent.com/assets/18232635/23206690/89eac678-f929-11e6-9df7-5730cf101a96.png)
渲染出来的效果看上去有点别扭，Checkbox勾选框偏下，而文字偏上。是否可以考虑两者都相对于外层的`class`为`ant-checkbox-wrapper`的label做垂直居中。
![image](https://cloud.githubusercontent.com/assets/18232635/23206575/242eb0e2-f929-11e6-9226-69f1c5f14ce4.png)
本人采用tabel布局，line-height设为0，做了效果演示，个人感觉好看点。
修改前后对比：
![image](https://cloud.githubusercontent.com/assets/18232635/23207291/bd98f024-f92b-11e6-9c98-4f078c422a22.png)
不知道是否符合大众审美。

**Comment by afc163** [comment]
<img width="115" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23208909/db9d24f4-f931-11e6-9013-bd8d2653f6c6.png">

That is what I see in Chome 56. So what is your browser and OS? 

I strongly suggest you to report bug according to issue template.

**Comment by GoDotDotDot** [comment]
@afc163 


#### Environment(required)

- antd version:2.7.2
- OS and its version:Windows 10
- Browser and its version:Chrome   55.0.2883.87 m (64-bit)

#### What did you do? Please provide steps to re-produce your problem.


I just use ant-init scaffold tool to create a demo and import Checkbox from antd.
#### code : 
```react
import React from 'react'
import ReactDOM from 'react-dom'
import './index.css'
import { Checkbox } from 'antd'

function App () {
  return (
    <div style={{ margin: 100 }}>
      <h1>AntDesign Demo</h1>
      <hr /><br />
      <Checkbox>选择 Checkbox</Checkbox>
    </div>
  )
}

ReactDOM.render(<App />, document.getElementById('root'))
```

#### What do you expected?


Checkboxe and text are not vertically centered.

#### What happen?


 Style is not as expected. 
#### result:
![image](https://cloud.githubusercontent.com/assets/18232635/23211774/a84fe0a2-f93e-11e6-96bb-0d5f815dbcd2.png)
![image](https://cloud.githubusercontent.com/assets/18232635/23211803/c1936d5e-f93e-11e6-8235-3066c8365d2a.png)
![image](https://cloud.githubusercontent.com/assets/18232635/23211829/dde6c762-f93e-11e6-89cf-464cda722295.png)

**Comment by GoDotDotDot** [comment]
![image](https://cloud.githubusercontent.com/assets/18232635/23212978/1b878516-f944-11e6-9016-b85c69c2f53e.png)
This is in Chrome 56

**Comment by afc163** [comment]
I made some change, you can check it after I re-deploy the site.

And I think the Checkbox in you modification is slightly higher.

**Comment by GoDotDotDot** [comment]
ok,thank you.

**Comment by budiga** [comment]
本人采用tabel布局，line-height设为0，做了效果演示，个人感觉好看点。
问下你是怎么修改的，对antd.css进行了修改？
