### ISSUE TITLE
Add showSizeChangerSearch prop to Pagination's select to disable searching/filtering

### ISSUE THREAD

**Issue by 3sbi** [ant-design/ant-design#50014]
### What problem does this feature solve?

A few of our users were confused about inserting a page size value into this select, because:
1. Now it only has 3 options (10, 20, 50), there is no need to search among 3 options;
2. they thought it was possible to insert a custom page size instead of 3 predefined values;
I wanted to keep the `SizeChanger` component but disable the ability to search for a specific variant, but there is currently no way to do that.

### What does the proposed API look like?

add the `showSizeChangerSearch` boolean property to the Pagination component. Search should be enabled by default to ensure consistency of API component between versions.

Pagination with disabled searching would look like this: 
```javascript
<Pagination showSizeChangerSearch={false} />
```

**Comment by afc163** [comment]
https://github.com/react-component/pagination/pull/554#issuecomment-1884129690

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/50952
