### ISSUE TITLE
form 表单项有校验信息时  extra 出现非预期的间距

### ISSUE THREAD

**Issue by xsbear** [ant-design/ant-design#50026]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-e7cstv?file=index.css,demo.tsx)

### Steps to reproduce

使用官方文档中的注册新用户表单case，通过design token设置 itemMarginBottom 或用自定义样式覆盖 .ant-form-item的margin-bottom, 超出默认的24px，当表单项验证错误，显示校验文本时，表单项的 extra 距离校验文本多出了 item margin-bottom的间距，这应该是不符合预期的，原因是与校验文本同级的div中多出了一个div，内联设置高度为 item的 margin-bottom

### What is expected?

extra与校验文本元素间不应该有item margin-bottom 的间距

### What is actually happening?

extra与校验文本元素间出现了 item margin-bottom 的间距

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | react |
| System | Mac |
| Browser | Chrome |

**Comment by xsbear** [comment]
如下图所示：
![image](https://github.com/user-attachments/assets/376d7c6f-5a86-4ea0-a3a9-324db82f41fb)

**Comment by clydee-geng** [comment]
I'm following up on this

**Comment by clydee-geng** [comment]
> > I'm following up on this
> 
> Are you still working on this issue? @clydee-geng 

I don't have a new solution for the time being, you can take over
