### ISSUE TITLE
使用form.setFieldValue给嵌套的list设置值之后，无法通过校验

### ISSUE THREAD

**Issue by Disappera-01** [ant-design/ant-design#50021]
### Reproduction link

https://stackblitz.com/edit/vitejs-vite-qe58r8?file=index.html

### Steps to reproduce

由于选择日期组件是联动选择，接口需要的数据是开始时间和结束时间两个字段。
于是我在选择时间的同时，使用
 # form.setFieldValue(
      ["parents", name, "linkTypes", index, "startTime"],
      startTime
    ) 
 给隐藏的两个Form.Item 赋值 ；

 <Form.Item name={[index, "startTime"]} hidden>
        <Input />
 </Form.Item>
  <Form.Item name={[index, "endTime"]} hidden>
        <Input />
   </Form.Item>
最后赋值成功，但是无法通过校验

### What is expected?

正常通过校验

### What is actually happening?

在onFinishFailed方法获取的到的错误信息如下：
{
    "values": {
        "linkSet": 0,
        "parents": [
            {
                "linkTypes": [
                    {
                        "type": 0,
                        "name": "测试环节1",
                        "linkType": 0,
                        "selfEvaluateType": 0,
                        "dates": [
                            "2024-07-23 11:38",
                            "2024-07-29 11:38"
                        ],
                        "startTime": "2024-07-23 11:38",
                        "endTime": "2024-07-29 11:38"
                    }
                ]
            }
        ]
    },
    "errorFields": [],
    "outOfDate": true
}

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | react18 |
| System | windows64 |
| Browser | 123.0.6312.59（正式版本） （64 位） |

**Comment by Wxh16144** [comment]
> 由于选择日期组件是联动选择，接口需要的数据是开始时间和结束时间两个字段。

先看这个 [封装 Form.Item 实现数组转对象](https://ant.design/docs/blog/form-names-cn)

再看这个 https://ant.design/docs/blog/issue-helper-cn

**Comment by Disappera-01** [comment]
> ### Reproduction link
> https://gitee.com/lxq777/antd-nested-list-assignment
> 
> ### Steps to reproduce
> 由于选择日期组件是联动选择，接口需要的数据是开始时间和结束时间两个字段。 于是我在选择时间的同时，使用
> 
> # form.setFieldValue(
> ```
>   ["parents", name, "linkTypes", index, "startTime"],
>   startTime
> ) 
> ```
> 
> 给隐藏的两个Form.Item 赋值 ；
> 
> <Form.Item name={[index, "startTime"]} hidden> </Form.Item> <Form.Item name={[index, "endTime"]} hidden> </Form.Item> 最后赋值成功，但是无法通过校验
> 
> ### What is expected?
> 正常通过校验
> 
> ### What is actually happening?
> 在onFinishFailed方法获取的到的错误信息如下： { "values": { "linkSet": 0, "parents": [ { "linkTypes": [ { "type": 0, "name": "测试环节1", "linkType": 0, "selfEvaluateType": 0, "dates": [ "2024-07-23 11:38", "2024-07-29 11:38" ], "startTime": "2024-07-23 11:38", "endTime": "2024-07-29 11:38" } ] } ] }, "errorFields": [], "outOfDate": true }
> 
> Environment	Info
> antd	5.7.3
> React	react18
> System	windows64
> Browser	123.0.6312.59（正式版本） （64 位）

**Comment by Disappera-01** [comment]
@github-actions 你好，已提供复现仓库地址 https://gitee.com/lxq777/antd-nested-list-assignment

**Comment by Disappera-01** [comment]
> > 由于选择日期组件是联动选择，接口需要的数据是开始时间和结束时间两个字段。
> 
> 先看这个 [封装 Form.Item 实现数组转对象](https://ant.design/docs/blog/form-names-cn)
> 
> 再看这个 https://ant.design/docs/blog/issue-helper-cn

你好，请看下是bug还是我的写法有问题 https://gitee.com/lxq777/antd-nested-list-assignment

**Comment by Disappera-01** [comment]
@Wxh16144  你好，请看下是bug还是我的额写法有问题

**Comment by MadCcc** [comment]
给个 stackblitz 或者 codesandbox 吧，看起来是封装组件的问题

**Comment by afc163** [comment]
<img width="1182" alt="图片" src="https://github.com/user-attachments/assets/0b4b002d-f1e7-43c2-995d-675615e20876">

**Comment by Disappera-01** [comment]
> ```js
>           <Form.Item
>             extra="注：在自评时间段内提交自评结果及自我评价信息；"
>             label="自评时间设置"
>             name={[index, 'dates']}
>             rules={[{ required: true, message: '请选择时间!' }]}
>           >
>             <RangePickerCom
>               showTime
>               formatType="dateTimeMinute"
>               // key={parents?.[name]?.link?.startTime}
>               defaultValue={
>                 linkTypesItem?.startTime
>                   ? [linkTypesItem?.startTime, linkTypesItem?.endTime]
>                   : null
>               }
>               setValue={setTimes}
>             />
>             {/* <RangePicker showTime className="w" /> */}
>           </Form.Item>
> ```
> 
> 这段代码感觉不太对。
> 
> <img alt="图片" width="1182" src="https://private-user-images.githubusercontent.com/507615/351748451-0b4b002d-f1e7-43c2-995d-675615e20876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODgwMjQsIm5iZiI6MTcyMTg4NzcyNCwicGF0aCI6Ii81MDc2MTUvMzUxNzQ4NDUxLTBiNGIwMDJkLWYxZTctNDNjMi05OTVkLTY3NTYxNWUyMDg3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNjA4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTM1NWFlYjBmODZlYzM5MmJiZDQ3ODQwOWFkMmQwZWYxM2UzZTEyMTQ4NTVlNGVhZDkzMTA2ZjIzZWYxZTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OOaLKM-fe28txf_iAEIosMGvm-3zn1iTxpwPgPGOqHQ">

这是我自己写的组件呀，这样在提交的时候不用手动处理时间格式了

**Comment by crazyair** [comment]
转换时间戳，可以看
https://ant.design/components/form-cn#components-form-demo-getvalueprops-normalize https://zhuanlan.zhihu.com/p/375753910

RangePicker 要平铺 2 个 name，可以看 https://ant.design/docs/blog/form-names-cn

**Comment by Disappera-01** [comment]
> 转换时间戳，可以看 https://ant.design/components/form-cn#components-form-demo-getvalueprops-normalize https://zhuanlan.zhihu.com/p/375753910
> 
> RangePicker 要平铺 2 个 name，可以看 https://ant.design/docs/blog/form-names-cn

谢谢，都看过了，嵌套的Form.List好像并不适用

**Comment by crazyair** [comment]
> > 转换时间戳，可以看 https://ant.design/components/form-cn#components-form-demo-getvalueprops-normalize https://zhuanlan.zhihu.com/p/375753910
> > RangePicker 要平铺 2 个 name，可以看 https://ant.design/docs/blog/form-names-cn
> 
> 谢谢，都看过了，嵌套的Form.List好像并不适用

这个处理的是组件本身，跟 Form.Item Form.List 没有任何关系，等我重新写个文章

**Comment by Disappera-01** [comment]
> > > 转换时间戳，可以看 https://ant.design/components/form-cn#components-form-demo-getvalueprops-normalize https://zhuanlan.zhihu.com/p/375753910
> > > RangePicker 要平铺 2 个 name，可以看 https://ant.design/docs/blog/form-names-cn
> > 
> > 
> > 谢谢，都看过了，嵌套的Form.List好像并不适用
> 
> 这个处理的是组件本身，跟 Form.Item Form.List 没有任何关系，等我重新写个文章

不太明白，因为我想要的效果是提交直接就是需要的数据，上面的方法如果不是list都可以满足，但是是list的话就不好用。也可能是我太菜了不知道怎么用

**Comment by crazyair** [comment]
> > > > 转换时间戳，可以看 https://ant.design/components/form-cn#components-form-demo-getvalueprops-normalize https://zhuanlan.zhihu.com/p/375753910
> > > > RangePicker 要平铺 2 个 name，可以看 https://ant.design/docs/blog/form-names-cn
> > > 
> > > 
> > > 谢谢，都看过了，嵌套的Form.List好像并不适用
> > 
> > 
> > 这个处理的是组件本身，跟 Form.Item Form.List 没有任何关系，等我重新写个文章
> 
> 不太明白，因为我想要的效果是提交直接就是需要的数据，上面的方法如果不是list都可以满足，但是是list的话就不好用。也可能是我太菜了不知道怎么用

新写了个直接能用的文档 https://zhuanlan.zhihu.com/p/710926773

**Comment by afc163** [comment]
你给的代码过于复杂了，能否给出最小化的重现？去掉一些无关代码。
