### ISSUE TITLE
Progress component's colors are hardcoded

### ISSUE THREAD

**Issue by WaldoJeffers** [ant-design/ant-design#5002]
#### Environment (required)

- antd version: 2.7.2
- OS and its version: Windows 10
- Browser and its version: Chrome 	56.0.2924.87 (64 bits)

#### What did you do? Please provide steps to re-produce your problem.
I modified the default colors to create a custom theme by importing a custom less file, and used the Progress (type circle) component with a `success` status.

#### What did you expect?
I expected the Progress component to use my custom theme's colors (the `success-color`).

#### What happens?
The Progress component does not use my custom theme's colors, because they are hardcoded in JavaScript [in the Progress component file](https://github.com/ant-design/ant-design/blob/master/components/progress/progress.tsx#L6).

If you provide the ability to use custom colors (which is great!), every component should use them and there should be a single file to define them (whether it's a JSON, a JS, or a LESS file). Wouldn't it be possible to set the colors for the SVG shape in CSS only (I don't know much about SVG) ?

**Comment by afc163** [comment]
Actually, I don't know we can stying svg by css before your issue. 😃
