### ISSUE TITLE
treeSelect组件，动态设置disabled属性出现非期望结果。

### ISSUE THREAD

**Issue by z2131023** [ant-design/ant-design#50039]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-ddi8au?file=demo.tsx)

### Steps to reproduce

1-选中工资福利费用
2-遍历树的数据，设置非同级的disabled为true
3-checkbox没有根据disabled正确渲染
4-鼠标移动到树选择器弹出窗口外
5-鼠标移动到窗口内，此时checkBox正确渲染

### What is expected?

更改树treeData的disabled，正确渲染checkbox

### What is actually happening?

需要鼠标移动到弹出窗口外，在移动回去，或者关闭打开选择器后才能正确渲染checkbox

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.2.0 |
| System | windows11 |
| Browser | chrome 126.0.6478.128 |

---
根据选择的节点，期望后续选择节点只能是第一个选择节点的同级

**Comment by MadCcc** [comment]
用一个 state 把 treeData 装一下，否则 react 不会更新。
https://stackblitz.com/edit/antd-reproduce-5x-yccjm7?file=formTreeSelect.tsx
