### ISSUE TITLE
Table defaultSortOrder not apply for columns with the responsive prop set 

### ISSUE THREAD

**Issue by AlexEmashev** [ant-design/ant-design#50033]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-8edh84?file=demo.tsx)

### Steps to reproduce

1. Use Table component. 
2. Setup columns template for the table. Set defaultSortOrder prop of a column to 'ascend' or 'descend'.
3. Set responsive prop for the same column.

### What is expected?

Table data is sorted according to defaultSortOrder of the column.

### What is actually happening?

Sort order is not applied.

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome 126.0.6478.183  |

---
Found a similar issue #35408, but it is quite outdated and it's reproduction link doesn't work anymore.

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/32847
