### ISSUE TITLE
Tooltip flash when click slider handler in chrome

### ISSUE THREAD

**Issue by sundayha** [ant-design/ant-design#5003]
[ant-design2.7.2，Slider=>](https://ant.design/components/slider-cn/)，在Chrome for Mac 版本（56.0.2924.87 (64-bit)），Slider滑动条组件，当点击该组件的横轴时，弹出的文字提示闪烁。在Safari中无此现象。在ant-design2.7.0版本中，在Chrome for Mac 版本（56.0.2924.87 (64-bit)）上时，Slider滑动条组件，当点击该组件的横轴时是正常的状态。

**Comment by afc163** [comment]
Also:

- [ ] Tooltip misplace a little.
- [ ] When click handler in safari, tooltip just disappear.

**Comment by afc163** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by sundayha** [comment]
@afc163 Thanks for your advice.

**Comment by benjycui** [comment]
The bug in Safari is because a bug of webkit, I had met it in Chrome before, but after Chrome update, it works fine.
