### ISSUE TITLE
表格支持树形数据的展示，当数据中有 children 字段时会自动展示为树形表格

### ISSUE THREAD

**Issue by zhanglp520** [ant-design/ant-design#50034]
### What problem does this feature solve?

children为空数组时，不需要用户特殊处理。不然还是显示为树节点。

### What does the proposed API look like?

树形数据展示
表格支持树形数据的展示，当数据中有 children 字段并且有子节点时才会自动展示为树形表格

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941
