### ISSUE TITLE
[Table] table组件希望添加自动填充的功能，类似Excel：单元格选中鼠标向下拖动自动填充赋值或者累加赋值

### ISSUE THREAD

**Issue by AlieLife** [ant-design/ant-design#50042]
### What problem does this feature solve?

提高用户可操作性行，优化用户体验，批量操作数据，而不是一条一条操作

### What does the proposed API look like?

onAutoFill: (record, columnName) => ReactNode | string

**Comment by MadCcc** [comment]
这个有点重了，推荐自行实现哈，antd 只提供基础的组件
