### ISSUE TITLE
Descriptions item 设置 style 未生效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#50044]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-fgxhwe?file=demo.tsx)

![image](https://github.com/user-attachments/assets/cb0f37fe-abba-4797-bba1-9a9bb5309c9a)

### Steps to reproduce

查看 demo

### What is expected?

变成红色

### What is actually happening?

黑色

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by MadCcc** [comment]
contentStyle
labelStyle

**Comment by thinkasany** [comment]
![image](https://github.com/user-attachments/assets/0f56de9b-eae0-442c-84f6-8e1d82612695)
