### ISSUE TITLE
Image 组件名字 和 lib.dom 关键字 有冲突

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#50041]
### What problem does this feature solve?

Image  组件  
```
import { Image } from "antd" ;
```

如果我的代码里正好有

```
let img = new Image()
```

就会报错了

解决办法就是给Image组件起个别名

建议可以把Image组件 改为 Picture 组件

**Comment by MadCcc** [comment]
别名一下吧，贸然改组件名不太合适。
