### ISSUE TITLE
Checkbox.Group 删除第一条以后，所有多选按钮都不能点击了。

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#50048]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-revgxv?file=demo.tsx)

### Steps to reproduce

打开重现链接，直接点击删除一条数据按钮，删除以后在点击多选选择框，不能选中

### What is expected?

删除一条数据后，其余的还是能够继续选中

### What is actually happening?

删除一条数据后，就不能选中了

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | react 18 |
| System | window 10 |
| Browser | Chrome 123.0.6312.86 |

**Comment by zombieJ** [comment]
`key` 按照 `value` 对应： 
https://stackblitz.com/edit/react-revgxv-4udumr?file=demo.tsx
