### ISSUE TITLE
Want to know something about react-component 

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#5005]
I notice that many components of antd come from or base on [react-component](https://github.com/react-component)(for convenient, we call it 'rc' below).

So,why not directly use rc or modify the src code of rc,just because TypeScript?And on the other hand,I think antd did something repetitive with the rc.

**Comment by afc163** [comment]
You can read more about it at: https://gitter.im/ant-design/ant-design?at=5809b34cb17b667961dfbf44

**Comment by afc163** [comment]
Briefly, If you choose react-component, you choose scalability and more work of coding styles. Unless you are going to create a UI library, antd is a better choice.

Also, react-component won't supply simple and small components more like design principle: button, timeline, tag, badge or icons.

**Comment by NE-SmallTown** [comment]
@afc163 Thanks for your reply.I consider this from two sights.

1.For rc,I can overwrite it's style by css-modules and design the UI whatever I want and use most of it's logic code.But for antd,I dont's use typescript and if we encapsulate our own library by rc,it would reduce many unnecessary code.

2.I will read both the src code of rc and antd,it's a good opportunity to learn your code,and if some code can be improved,I can try my best to send a pr,it's also a good  opportunity to train my knowledge.

**Comment by NE-SmallTown** [comment]
One more question,the pr about rc sended on rc is better or antd?

**Comment by afc163** [comment]
It depend. 😅

**Comment by afc163** [comment]
It depends. 😅

**Comment by afc163** [comment]
1. You don't have to use TypeScript just for antd, you can import it just by using es2015.
2. The "encapsulate our own library" idea is great, and you can also see [uxcore](https://github.com/uxcore/uxcore), which is also built upon rc-components.

**Comment by NE-SmallTown** [comment]
@afc163 Ye,I know that I don't use ts,but sometimes I will read the src code,althought ts won't impede me to read in most situations,but I don't like it,at least for now.

And uxcore is cool,I will give it a try.Thanks.
