### ISSUE TITLE
Upload.Dragger 组件使用customRequest自定义上传的时候，回调onProgress({percent: 100})之后，文件列表前面的图标还是一直loading的状态

### ISSUE THREAD

**Issue by jiajiaxing1** [ant-design/ant-design#50067]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/jjx-demo?file=demo.tsx)

### Steps to reproduce

https://stackblitz.com/edit/jjx-demo?file=demo.tsx

### What is expected?

percent: 100之后就结束loading状态

### What is actually happening?

一直在loading，不知道如何取消或者关闭loading
<img width="472" alt="image" src="https://github.com/user-attachments/assets/c3e6551e-1919-45a2-b25c-1ec4136d797c">

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.3.1 |
| System | maxOS14.4.1  |
| Browser | Chrome126.0.6478.128（正式版本） (arm64) |

**Comment by DroganC** [comment]
我是这样做的 
onChange存一下对应文件的status的状态，在为终态done或者error的时候 ，取消onProgress

**Comment by jiajiaxing1** [comment]
> 我是这样做的 onChange存一下对应文件的status的状态，在为终态done或者error的时候 ，取消onProgress

有示例代码能发来看看吗

**Comment by MadCcc** [comment]
onSuccess 放在最后就可以
