### ISSUE TITLE
Autocomplete auto-selecting the first value

### ISSUE THREAD

**Issue by MickaelBZH** [ant-design/ant-design#5006]
Is there a way to avoid this behavior? 
If the user press enter, I want the input ... not the first completed result.

**Comment by benjycui** [comment]
Try `defaultActiveFirstOption={false}`

**Comment by MickaelBZH** [comment]
Thanks. However the suggestions list is still opened after selecting with this option. Any way to close it?

**Comment by benjycui** [comment]
> However the suggestions list is still opened after selecting with this option. Any way to close it?

This maybe an issue.

**Comment by benjycui** [comment]
rc-select is so complicated and heavy now, need to be refactored & re-designed

**Comment by afc163** [comment]
duplicate #4393, trace https://github.com/react-component/select/pull/165
