### ISSUE TITLE
Pdf preview

### ISSUE THREAD

**Issue by Olegelcrack** [ant-design/ant-design#50075]
### What problem does this feature solve?

A button or linkable text that opens a modal with a PDF file inside would be really useful for displaying the content of the PDF. Currently, there is an upload component that supports PDFs, but there isn’t anything to visualize it.

### What does the proposed API look like?

<PdfPreview blob={blobVariableOfPdf}>
<PdfPreview base64={b64VariableOfPdf}>

**Comment by afc163** [comment]
You could try https://react-pdf.org/ or https://github.com/diegomura/react-pdf or https://react-pdf-viewer.dev/
