### ISSUE TITLE
hasFeedback and validateStatus not working when importing controls directly from antd/lib/...

### ISSUE THREAD

**Issue by sparrowek** [ant-design/ant-design#50073]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/basic-usage-antd-4-24-16-forked-5lvntc?file=%2Fdemo.tsx)

### Steps to reproduce

```
import React from "react";
import "antd/dist/antd.css";
import { Form, Input } from "antd";
import { default as Input2 } from "antd/lib/input";

const App: React.FC = () => (
  <>
    <Form.Item hasFeedback validateStatus="error" help="error icon showing">
      <Input />
    </Form.Item>
    <Form.Item
      hasFeedback
      validateStatus="error"
      help="error icon and border not showing"
    >
      <Input2 />
    </Form.Item>
  </>
);

export default App;
```

### What is expected?

feedback icon and border should be shown not matter if we import ant controls from the barrel file "antd" or "antd/lib/input"

### What is actually happening?

When importing ant controls from "antd/lib/input" feedback icon is not shown but when importing from "antd" everything is working correctly.

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | Windows |
| Browser | Firefox |

**Comment by afc163** [comment]
<img width="676" alt="图片" src="https://github.com/user-attachments/assets/f3b5d293-fe86-4d3c-8fdd-8f03edddfb0e">

**Comment by sparrowek** [comment]
fixed

**Comment by afc163** [comment]
```diff
- import { default as InputNumber2 } from "antd/lib/input-number";
+ import { default as InputNumber2 } from "antd/es/input-number";
```

Different import path leads to different context.

**Comment by sparrowek** [comment]
Thanks, I understand. Is this documented somewhere?
