### ISSUE TITLE
Validating a Select with Tags

### ISSUE THREAD

**Issue by PiereDome** [ant-design/ant-design#5007]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: Windows 10
- Browser and its version: Chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

Create a form with the Form.create method
Then create a getFieldDecorator on a Select Component with tags
Set rules to type of array and defaultField of email
Try to put message in defaultField or base or rules object, but doesn't render any error when an invalid email

I created a simple example of what I am trying to accomplish below

#### What do you expected?

An error message to be displayed, async-validator is console.warning the validation, need to get that to display to the end user

#### What happen?

You can see in the screenshot that async-validator is validating correctly

![image](https://cloud.githubusercontent.com/assets/1903016/23231395/d4ae71a2-f904-11e6-8342-8dc1c0f38514.png)

#### Re-producible online demo

[CodePen](http://codepen.io/PiereDome/pen/jBNpXG?editors=0010)

**Comment by PiereDome** [comment]
You can close this ticket I was able to get this resolved with the custom validator

Here is the [codepen ](http://codepen.io/PiereDome/pen/bqbOeo?editors=0010)with the fix

**Comment by benjycui** [comment]
Actually, you can close issue on your own.
