### ISSUE TITLE
table虚拟加载，不到1000条数据，列数增加到10列以上就特别卡顿

### ISSUE THREAD

**Issue by yyyyffqqqq** [ant-design/ant-design#50071]
### What problem does this feature solve?

现有的虚拟加载有bug，希望能支持10000条数据（10 列以上）以内的虚拟加载，帧率稳定在50 

### What does the proposed API look like?

能支持10000条数据以内的虚拟加载，帧率稳定在50

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/46980

**Comment by ay233** [comment]
@afc163 超过10列以上提别卡，这个可以优化吗？目前是每页200条，40多列

**Comment by BoyXuanzai** [comment]
解决方案呢？？？

**Comment by leiyangs** [comment]
为什么关闭了，已经解决了吗
