### ISSUE TITLE
Sorting on children column doesn't work after updating to 5.19.3

### ISSUE THREAD

**Issue by adriankrystkiewicz** [ant-design/ant-design#50084]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-fx5tsy?file=demo.tsx)

### Steps to reproduce

I have attached a working sample running on antd 5.19.2. To reproduce update to 5.19.3 and then sorting will not work.

### What is expected?

Sorting should work.

### What is actually happening?

Sorting is not working

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.1 |
| System | Windows 10 |
| Browser | Google Chrome 126.0.6478.183 |

**Comment by afc163** [comment]
@Zyf665 Could you help to check this issue which could break by https://github.com/ant-design/ant-design/pull/49533
