### ISSUE TITLE
Upload.Dragger directory drop does not work

### ISSUE THREAD

**Issue by bdproduction** [ant-design/ant-design#50080]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-dwcz5h?file=demo.tsx)

### Steps to reproduce

Use dragger component, set properties: directory, multiple. Drag and drop directory in the zone

### What is expected?

To list the file contents. 
To trigger events like onChange, beforeUpload.

### What is actually happening?

Nothing. 

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.1 |
| System | Windows 11 Pro |
| Browser | Version 127.0.6533.73 (Official Build) (64-bit) |

---
The only way it works is if you click the box and then select the folder.

**Comment by afc163** [comment]
Because you return false in `beforeUpload`.

**Comment by bdproduction** [comment]
That has nothing to do with drag&drop directory. 
Remove it and the result is the same. 

Here I added a console log for you to see that event is not triggered by drag&drop but it does work when clicking to toggle the upload window.

You obviously have not read the expectation, not have tried it yourself.

**Comment by afc163** [comment]
You got me, it should be bug. Upload.Dragger and `directory` didn't work well.

**Comment by huiliangShen** [comment]
This seems to be a problem caused by  RcUpload

**Comment by zhenzhenChange** [comment]
Dragging and dropping a directory now only trigger the `onDrop` event ...
