### ISSUE TITLE
日期时间范围选择器无法选择

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#50099]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn#components-date-picker-demo-range-picker](https://ant-design.antgroup.com/components/date-picker-cn#components-date-picker-demo-range-picker)

### Steps to reproduce

1. 选择开始时间，不点击确定
2. 点击结束时间，然后选择，点击确定

### What is expected?

能够选择上值

### What is actually happening?

不能选择值

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | latest |
| System | macOS 14.5 (23F79) |
| Browser | 谷歌 latest |

**Comment by XianZhengquan** [comment]
https://github.com/user-attachments/assets/3f883665-54ed-43d1-9fcf-9eee3662ccf0

**Comment by XianZhengquan** [comment]
在v4的版本中，是可以这样交互的

**Comment by Wxh16144** [comment]
`needConfirm={false}`?

**Comment by XianZhengquan** [comment]
> `needConfirm={false}`？

这样的话，那个确定按钮就没有了，在V4中，是可以这样操作的

**Comment by Wxh16144** [comment]
那就等豆酱大佬看看

**Comment by zombieJ** [comment]
v4 有穿透问题，v5 是要么都确认，要么都不确认。感觉可以多做一个拦截，对于选择时间没有点确认的时候不让点另一个 Input

**Comment by XianZhengquan** [comment]
> v4 有穿透问题，v5 是要么都确认，要么都不确认。感觉可以多做一个拦截，对于选择时间没有点确认的时候不让点另一个 Input

v4这个情况是属于一个bug?

**Comment by sakuraee** [comment]
应该是按楼主的意思更好点么不该是，理解那应该是即使其中一个不点确认，但是选上了值，另一个点了确认后也应该是将值存下吧，需要修复成这样么 @zombieJ

**Comment by XianZhengquan** [comment]
> 应该是按楼主的意思更好点么不该是，理解那应该是即使其中一个不点确认，但是选上了值，另一个点了确认后也应该是将值存下吧，需要修复成这样么 @zombieJ

然而并没有这样修复，现在是阻止了
