### ISSUE TITLE
希望optionRender提供属性设置Select.Option的类名

### ISSUE THREAD

**Issue by Dmaziyo** [ant-design/ant-design#50106]
### What problem does this feature solve?

自定义option样式

### What does the proposed API look like?

optionRootClassName

https://stackblitz.com/edit/react-drzy2s?file=demo.tsx  当使用Select.Option时可以自定义option的根组件的类名称，而使用optionRender无法实现

当前效果：
![image](https://github.com/user-attachments/assets/77d30525-a461-484e-8d15-33ccd43ee490)
想要的效果：
![image](https://github.com/user-attachments/assets/32d50e46-cebe-4a64-be3d-9387ec85edad)

**Comment by afc163** [comment]
感觉这个 optionRender 没啥用。。。

**Comment by Dmaziyo** [comment]
> 感觉这个 optionRender 没啥用。。。
确实感觉没啥用
![image](https://github.com/user-attachments/assets/2839e7b3-6ee4-44bd-acef-77c2d62c7acb)
我看文档说之后6.0会移除Select.option，那我怎么才能修改这个option的样式呢？有其他方法能访问这个option的root吗？

**Comment by MadCcc** [comment]
直接给 option 加 className

```
<Select
      defaultValue="lucy"
      style={{ width: 120 }}
      onChange={handleChange}
      options={[
        { value: 'jack', label: 'Jack', className: 'test' },
        { value: 'lucy', label: 'Lucy' },
        { value: 'Yiminghe', label: 'yiminghe' },
        { value: 'disabled', label: 'Disabled', disabled: true },
      ]}
    />
```
