### ISSUE TITLE
Standardize the Usage of React Imports and Destructuring

### ISSUE THREAD

**Issue by cidkumagai** [ant-design/ant-design#50102]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/_util/__tests__/hooks.test.tsx#L142](https://github.com/ant-design/ant-design/blob/master/components/_util/__tests__/hooks.test.tsx#L142)

### Steps to reproduce

1.	Open the codebase.
2.	Search for files that import React components and hooks.
3.	Identify files using the full React.Component or React.useState syntax and files using destructuring, like `{ Component, useState }.`

### What is expected?

•	The codebase should have a consistent import style for React components and hooks.
•	This consistency should improve code readability and ease of maintenance.

### What is actually happening?

•	The codebase currently has mixed styles, with some files using React.Component and others using { Component }.
•	This inconsistency can lead to confusion and makes the codebase harder to maintain.

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18 |
| System | macOS |
| Browser | Chrome 125 |

**Comment by cidkumagai** [comment]
I'll try it.

**Comment by MadCcc** [comment]
Not necessary, all code after compiling are the same.
