### ISSUE TITLE
Table's filter cannot focus in the input

### ISSUE THREAD

**Issue by xiiiAtCn** [ant-design/ant-design#5010]
#### Environment(required)

I import Table from antd, set Tables's scroll, make the first column's fixed left, and add a filter to this column.And then I click the filter's input to focus, it just retract. So I can't input a word to filter this column.I lost the fixed property in my last re-produce.Sorry for that.Here is the problematic re-produce.http://codepen.io/anon/pen/qrWvRM?editors=0010.

**Comment by afc163** [comment]
It is a tricky bug..

**Comment by afc163** [comment]
It is hard to write test case cause it is related to non-react-dom-event: https://github.com/react-component/trigger/blob/9edc5af9cbd5f1e200fb13e984f7f369d9d95dac/src/Trigger.jsx#L148 So I gone to pass it.
