### ISSUE TITLE
Menu selectedKeys, drop context when adding some <div> in between <Menu> and <Menu.Item>

### ISSUE THREAD

**Issue by JosepSalvat** [ant-design/ant-design#50104]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-dutupg?file=demo.tsx)

### Steps to reproduce

I did one example that it works and another one that doesn't. It's easy

### What is expected?

To work even if u are wrapping the Menu Items.

### What is actually happening?

If u wrap the Menu.Item(s) in a div, fragment or something else, it doesn't work

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 1.18.3 |
| System | Linux |
| Browser | Chrome |

**Comment by afc163** [comment]
That is correct, it is by designed.
