### ISSUE TITLE
Cascader配合mobx报错，Cannot read properties of undefined (reading 'nodes')

### ISSUE THREAD

**Issue by gonlyk** [ant-design/ant-design#50114]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-wrncda?file=src%2FApp.tsx)

### Steps to reproduce

动态添加选项后选择报错

### What is expected?

正常选择

### What is actually happening?

Cannot read properties of undefined (reading 'nodes')

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.1 |
| System | window |
| Browser | chrome127.0.6533.72 |

**Comment by yoyo837** [comment]
看不到错误呢，只看到key重复警告

**Comment by gonlyk** [comment]
忘记更新key值了，修改了一下，添加选项后选择发生错误
![image](https://github.com/user-attachments/assets/67a0625c-456a-4e13-a01a-a2e1ff7b0d85)

**Comment by MadCcc** [comment]
看下 mobx 的问题吧
