### ISSUE TITLE
InputNumber decimal bug

### ISSUE THREAD

**Issue by erdun** [ant-design/ant-design#5012]
when InputNumber is wrapped by getFieldDecorator in Form, it's strange that if input 1.0, it will be 1 when i want to input a number 1.05. It was failed even add the property of 'step'. here's the [demo](http://codepen.io/erdun/pen/LWYVjj?editors=0010)

**Comment by lucky3mvp** [comment]
inputnumber 本来就是输入数字的啊，integer啊

**Comment by benjycui** [comment]
Did you try [InputNumber[step]](https://ant.design/components/input-number/#components-input-number-demo-digit)?

It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
And if you still meet this issue, please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
It is a problem in `rc-input-number`'s controlled mode.

**Comment by erdun** [comment]
thx😊  @benjycui, have rewritten the dec and added the live demo, may help others
