### ISSUE TITLE
table默认排序失效

### ISSUE THREAD

**Issue by 3764446961** [ant-design/ant-design#50123]
表格默认排序失效

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-2vtqbz-g4rzdy?file=demo.tsx,package.json)

**Comment by 3764446961** [comment]
复现地址
5.19.2 点击更新按钮，排序仍存在（正确）：https://stackblitz.com/edit/react-wythmx?file=demo.tsx,package.json
5.19.3 点击更新按钮，排序丢失（错误）： https://stackblitz.com/edit/react-2vtqbz-g4rzdy?file=demo.tsx,package.json

**Comment by afc163** [comment]
@Zyf665 cc

**Comment by Zyf665** [comment]
https://stackblitz.com/edit/antd-reproduce-5x-hcdtca?file=demo.tsx  你这个antd的版本是5.18.2

**Comment by 3764446961** [comment]
> https://stackblitz.com/edit/antd-reproduce-5x-hcdtca?file=demo.tsx 你这个antd的版本是5.18.2

没有问题了，close吧
