### ISSUE TITLE
Form.List中remove其中一项后，该项后面的Form.Item校验均会失效

### ISSUE THREAD

**Issue by Sheepeer** [ant-design/ant-design#50120]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-4hj4hr?file=demo.tsx)

### Steps to reproduce

1. 填入3条不合法手机号
2. 删除第二条
3. 第三条手机号的校验错误消失

### What is expected?

期望删除第二条后，第三条手机号的校验错误信息不消失

### What is actually happening?

Form.List校验有误

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18.0.0 |
| System | win10 |
| Browser | chrome |

**Comment by crazyair** [comment]
https://ant.design/components/form-cn#components-form-demo-dynamic-form-items
要加 `restField`
