### ISSUE TITLE
next.js中使用 Input.TextArea ,Link跳转切换多语言后，AutoSize失效

### ISSUE THREAD

**Issue by xuqssq** [ant-design/ant-design#50124]
### Reproduction link

[https://antd-textarea-bug.vercel.app](https://antd-textarea-bug.vercel.app)

### Steps to reproduce

点击前2个多语言切换组件，进行多语言切换，下面的 textarea 的 AutoSize 属性直接失效

### What is expected?

Link切换多语言，AutoSize保持正常，跟a标签跳转的效果一样

### What is actually happening?

nextjs使用Link切换语言AutoSize失效

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | react@18,next.js@14.2.2 |
| System | macos |
| Browser | chrome@126.0.6478.185 |

---
代码地址：https://github.com/xuqssq/antd-textarea-bug
部署地址：https://antd-textarea-bug.vercel.app

已经尝试过antd@5.19.3，依然存在

**Comment by Liammcl** [comment]
I also encountered this problem.

**Comment by wjx19990323** [comment]
I also encountered this problem.

**Comment by MadCcc** [comment]
你的复现直接点进去就是无法 resize 的。

**Comment by xuqssq** [comment]
https://antd-textarea-bug.vercel.app/

这个在线示例就是啊，默认是5行，Link跳转后，AutoSize失效
![image](https://github.com/user-attachments/assets/031752f6-f526-473d-945a-acf5890127e5)

**Comment by xuqssq** [comment]
我设置了resize: "none"，不给拖动调整

**Comment by xuqssq** [comment]
![image](https://github.com/user-attachments/assets/741631bc-490f-4c9b-bf86-cfb386569832)

**Comment by xuqssq** [comment]
没人修吗
