### ISSUE TITLE
rangepicker 选择交互问题

### ISSUE THREAD

**Issue by ShallowSummertime** [ant-design/ant-design#50126]
### Reproduction link

[https://codepen.io/Kai-Li-the-styleful/pen/vYqgBPx?editors=001](https://codepen.io/Kai-Li-the-styleful/pen/vYqgBPx?editors=001)

### Steps to reproduce

开始时间选择后 （不点击确定按钮）点击输入框内的结束时间范围 双击选择时间 ，会发现之前选中的时间被清空了

### What is expected?

期望正常显示选中的时间

### What is actually happening?

选择的时间被清空了

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | react18 |
| System | mac m1 |
| Browser |  127.0.6533.72 |

**Comment by ShallowSummertime** [comment]
https://github.com/user-attachments/assets/31e8831c-3def-449d-9d81-cde0b630f339

**Comment by MadCcc** [comment]
需要先确认开始时间

**Comment by zombieJ** [comment]
可以优化一下，如果是选择开始时间并且没有提交的话就禁止切换到结束时间。
