### ISSUE TITLE
treeselect tree 为什么默认fieldNames不统一

### ISSUE THREAD

**Issue by kushu001** [ant-design/ant-design#50128]
### What problem does this feature solve?

Tree组件的默认fieldNames是{ title: title, key: key, children: children }，而TreeSelect的默认fieldNames是{ label: label, value: value, children: children }，请问是有什么考量？

### What does the proposed API look like?

能够统一配置，方便适配

**Comment by zombieJ** [comment]
Tree 组件是展示组件，TreeSelect 是输入组件（类似 Select）。对于 Tree 是没有 `value` 的概念的。同时 `value` 内部处理其实是同时转成 `value` & `key` 帮用户处理掉了 `key` 的情况。同理，`label` 是选项概念，在 Tree 中则没有。

如果需要可以自行 HOC 一下，强行对齐到一起去。

PS: 当年在重构的时候，我也是认为统一名称会好记一些。但是因为语义上的确不同，所以没有进一步做这个改动。

**Comment by kushu001** [comment]
> Tree 组件是展示组件，TreeSelect 是输入组件（类似 Select）。对于 Tree 是没有 `value` 的概念的。同时 `value` 内部处理其实是同时转成 `value` & `key` 帮用户处理掉了 `key` 的情况。同理，`label` 是选项概念，在 Tree 中则没有。
> 
> 如果需要可以自行 HOC 一下，强行对齐到一起去。
> 
> PS: 当年在重构的时候，我也是认为统一名称会好记一些。但是因为语义上的确不同，所以没有进一步做这个改动。

感谢，这样我就理解了
