### ISSUE TITLE
ColorPicker组件，滑动颜色滑块时，触发onChange事件，onChange={(colorItem) => console.log(colorItem)} 打印后发现无论怎么滑动选择色值，metaColor的rgba分别为0、0、0、1

### ISSUE THREAD

**Issue by Summer-for-work** [ant-design/ant-design#50127]
### Reproduction link

[https://ant-design.antgroup.com/components/color-picker-cn](https://ant-design.antgroup.com/components/color-picker-cn)

### Steps to reproduce

ColorPicker组件，不赋颜色初始值。滑动颜色滑块时，触发onChange事件，onChange={(colorItem) => console.log(colorItem)} 

### What is expected?

希望滑动颜色滑块时（透明度上面那个条条），metaColor的rgba正确。

### What is actually happening?

发现无论怎么滑动，metaColor的rgba分别为0、0、0、1

| Environment | Info |
| --- | --- |
| antd | 5.19.1 |
| React | 18 |
| System | MacBook Pro 13.6.1 (22G313) |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
不设置初始值，颜色是 hsv(0, 0, 0)。当你滑动时 hue 条时，它只是 hsv(0 ~ 360, 0, 0) 之间变化。生成 rgba 都是 `0/0/0`。这个体验的确比较怪异。可以优化一下。

**Comment by Summer-for-work** [comment]
> 不设置初始值，颜色是 hsv(0, 0, 0)。当你滑动时 hue 条时，它只是 hsv(0 ~ 360, 0, 0) 之间变化。生成 rgba 都是 `0/0/0`。这个体验的确比较怪异。可以优化一下。

好的，期待你们尽快优化～～
