### ISSUE TITLE
window系统下运行npm run complile或者npm run clean的时候一直报错

### ISSUE THREAD

**Issue by dafeng345** [ant-design/ant-design#50122]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x?file=demo.tsx)

### Steps to reproduce

运行指令
npm run complile或者npm run clean

### What is expected?

success

### What is actually happening?

 ./scripts/cleanup.sh

'.' is not recognized as an internal or external command,
operable program or batch file.

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | ^16.4.2 |
| System | window |
| Browser | chrome |

**Comment by IsKaros** [comment]
我的windows电脑下面运行npm run compile，最后会在clean失败。
![image](https://github.com/user-attachments/assets/3d5d5333-4921-4e99-ab81-d5bbbd197c23)

**Comment by MadCcc** [comment]
拉到 master 最新的 commit 呢

**Comment by DDDDD12138** [comment]
哈哈哈，`rm -rf` 是一个 Unix/Linux 命令，在 Windows CMD 下跑，就会报 `不是内部或外部命令，也不是可运行的程序`
当然，Windows 下也不是完全不能跑，使用 `git bash`, 这个语法是兼容的
