### ISSUE TITLE
Need to Custom Skeleton

### ISSUE THREAD

**Issue by khawarshehzad786** [ant-design/ant-design#50138]
### What problem does this feature solve?

Currently, Ant Design's Skeleton component cannot display certain elements, such as tables, cards, and smaller components, effectively. For example, on YouTube's mobile app, when videos are loading, the title and channel image are shown as skeletons, providing a better user experience. This feature aims to offer similar functionality, allowing developers to create custom skeletons for various elements in their applications.

### What does the proposed API look like?

The proposed API would enable developers to create custom skeletons for their applications. For instance, developers could implement a skeleton similar to YouTube's home page skeleton, allowing for more flexibility and improved user experience.

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by coding-ice** [comment]
I think, too.  
API: `<Skeleton.Custom style={{ width: 100, height: 100 }}></Skeleton.Custom>`
Can consider removing `Skeleton.Image Skeleton.Node...`?  Let the user customize.

For example.
<img width="226" alt="image" src="https://github.com/user-attachments/assets/f5580186-e848-4c98-b48e-82abf46114b6">

**Comment by khawarshehzad786** [comment]
Acknowledged Thanks

**Comment by coding-ice** [comment]
@afc163 佬，这个考虑open下不 因为我司用的也比较多，现在都是自己写的，比较麻烦

**Comment by afc163** [comment]
看上去就是 Skeleton.Node ？

**Comment by coding-ice** [comment]
是的，但是有一个默认值，这样才能实现预期效果
```tsx
  <Skeleton.Node active style={{ width: 100, height: 80 }}>
    {false}
  </Skeleton.Node>
```
简单看了下`Node/Image`的区别，好像就`children`不一样，感觉可以简化一下，全部让用户自定义

**Comment by afc163** [comment]
这个默认值感觉很奇怪，我感觉可以直接去掉。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50278
