### ISSUE TITLE
Dropdown children不能传入ReactNode类型，跟实际类型不符

### ISSUE THREAD

**Issue by coding-ice** [ant-design/ant-design#50135]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-wayfrm?file=demo.tsx)

### Steps to reproduce

打开分享链接

### What is expected?

兼容 React.ReactNode类型

### What is actually happening?

React.Children.only expected to receive a single React element child.

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.3 |
| System | Mac |
| Browser | 谷歌 |

**Comment by MadCcc** [comment]
是不能兼容 ReactNode 的，children 必须支持 onClick 等事件才行，必须是一个 ReactElement。

**Comment by coding-ice** [comment]
类型方面好像不行，如果改了其他地方也挂了
要么不是`element`加个`span`（虽然也不是好办法）

**Comment by afc163** [comment]
>  要么不是element加个span（虽然也不是好办法）

我觉得可以，string 或 number 类型就包个 span。
