### ISSUE TITLE
Form表单使用自己维护的数据源的时候不能使用验证

### ISSUE THREAD

**Issue by gonlyk** [ant-design/ant-design#50139]
### What problem does this feature solve?

在使用自定义数据源实现受控表单时需要自己去维护help和validate状态而不能使用rules选项

### What does the proposed API look like?

validateFields可以验证传入的value

**Comment by afc163** [comment]
详细描述一下需求吧，具体是什么场景，你希望的 API 是长怎么样的？为什么这个新的 API 能解决你的问题？

**Comment by crazyair** [comment]
现有api能满足场景，提供复现，给你改改

**Comment by gonlyk** [comment]
https://stackblitz.com/edit/vitejs-vite-huuneh?file=src%2FApp.tsx

在某些动态表单场景下不好去使用表单自带的数据管理，需要自己去管理，但是自己管理的情况下不能使用表单的rules验证，请问能不能做到验证时取用传入的value进行验证

**Comment by crazyair** [comment]
> https://stackblitz.com/edit/vitejs-vite-huuneh?file=src%2FApp.tsx
> 
> 在某些动态表单场景下不好去使用表单自带的数据管理，需要自己去管理，但是自己管理的情况下不能使用表单的rules验证，请问能不能做到验证时取用传入的value进行验证

`<Form.Item name='xx'><Select/>xxx` 
Form.Item 包裹的组件就不需要 value onChange了， 因为已经用 Form 受控了。

**Comment by gonlyk** [comment]
> > https://stackblitz.com/edit/vitejs-vite-huuneh?file=src%2FApp.tsx
> > 在某些动态表单场景下不好去使用表单自带的数据管理，需要自己去管理，但是自己管理的情况下不能使用表单的rules验证，请问能不能做到验证时取用传入的value进行验证
> 
> `<Form.Item name='xx'><Select/>xxx` Form.Item 包裹的组件就不需要 value onChange了， 因为已经用 Form 受控了。

在这种场景下无法使用useWatch进行视图控制，所以没使用name而是使用了useState数据源，实际开发时可能会使用redux、mobx数据源。在这种情况下rules提供的校验会失效。

**Comment by crazyair** [comment]
> > > https://stackblitz.com/edit/vitejs-vite-huuneh?file=src%2FApp.tsx
> > > 在某些动态表单场景下不好去使用表单自带的数据管理，需要自己去管理，但是自己管理的情况下不能使用表单的rules验证，请问能不能做到验证时取用传入的value进行验证
> > 
> > 
> > `<Form.Item name='xx'><Select/>xxx` Form.Item 包裹的组件就不需要 value onChange了， 因为已经用 Form 受控了。
> 
> 在这种场景下无法使用useWatch进行视图控制，所以没使用name而是使用了useState数据源，实际开发时可能会使用redux、mobx数据源。在这种情况下rules提供的校验会失效。

Form.Item 要设置 name 才能激活 rules 功能

**Comment by afc163** [comment]
rules 和数据绑定这两个功能从设计上就是一体的，是不能分开用的。如果要自行管理数据流，则也需要自行进行校验。
