### ISSUE TITLE
FloatButton.Group的菜单模式只能向上展开吗，如果按钮在最上方怎么做到向下展开

### ISSUE THREAD

**Issue by wangxiaogang94** [ant-design/ant-design#50130]
### What problem does this feature solve?

FloatButton.Group在最上方时可以向下展开

### What does the proposed API look like?

FloatButton.Group上增加方向配置，除了向下展开以外，如果有向左向右展开就更好了

**Comment by wangxiaogang94** [comment]
好的，谢谢

**Comment by li-jia-nan** [comment]
相关 issue：

- #50130

**Comment by li-jia-nan** [comment]
看了一下，如果要支持其它方向的话，要改成 `position: absolute` 的布局了，不然没办法实现
