### ISSUE TITLE
Reduced motion media query changes components behavior

### ISSUE THREAD

**Issue by xylor182** [ant-design/ant-design#50131]
### Reproduction link

[https://antd-reproduce-5x-ebav1t.stackblitz.io](https://antd-reproduce-5x-ebav1t.stackblitz.io)
[https://stackblitz.com/edit/antd-reproduce-5x-ebav1t?file=demo.tsx,index.css](Code)

### Steps to reproduce

In order for that code to work, open devtools then press Ctrl   Shift   P. Type reduce motion and turn it on.

### What is expected?

Select options to open next to select container

### What is actually happening?

Select option is rendered outside screen (check inset values).

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 18.2.0 |
| System | Windows 11 Pro 64-bit |
| Browser | All browsers |

---
This happens not just for selects but other components.

**Comment by MadCcc** [comment]
Try https://ant.design/docs/react/customize-theme#disable-motion
Or lack of motion will make antd components broken.
