### ISSUE TITLE
Select组件在搜狗输入法中文模式下的搜索再选中选项，选中的项不对

### ISSUE THREAD

**Issue by zx-zx22** [ant-design/ant-design#50146]
### Reproduction link

[https://xxxxxx](https://xxxxxx)

### Steps to reproduce

在官网的Select示例可以进行测试
Select组件在搜狗输入法 - 中文模式下输入字母进行搜索再选中选项，选中的值是没搜索前的那个索引的值
图片放在评论区，这里上传不了图片

### What is expected?

期望搜索后能正常选中值

### What is actually happening?

实际上搜索后选中的是没搜索前的列表的相同索引的值

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome 最新版 |

**Comment by zx-zx22** [comment]
在官网这个示例复现问题
![image](https://github.com/user-attachments/assets/f4d7a8e2-ff86-40b0-b4b5-8462fdd0f4e6)
meis没搜索时第四条是  Identified
![image](https://github.com/user-attachments/assets/a8c75f8c-e8ca-433c-bd16-3417c05220e5)
然后搜狗输入法，中文模式下输入字母，此时列表变了，进行了搜索，第四条是 Resolved
![image](https://github.com/user-attachments/assets/913b0144-b2ed-4ddb-b6b4-aedb8cba0192)
点击 Resolved,然后选中的是Identified
![image](https://github.com/user-attachments/assets/a1d0b26d-d9a8-434f-a97e-99306df463c4)

**Comment by zombieJ** [comment]
感觉是点击的时候，输入法认为结束输入直接重置了导致变成空的了？能搞个视频看看不

**Comment by zx-zx22** [comment]
![GIFantd](https://github.com/user-attachments/assets/8aaf0cd5-9388-4287-839d-ebfa7e7f9aba)

**Comment by zombieJ** [comment]
gif 里看的确就是输入法的问题，你点 resolved 的时候输入法清空了输入然后变成了原本的顺序。

**Comment by zx-zx22** [comment]
但是AutoComplete这个组件同样的操作就可以正确选中

**Comment by zombieJ** [comment]
AutoComplete 是 Input，不是 Select。它在输入时已经 `value` 配对，Select 是在选择时配对。

**Comment by zombieJ** [comment]
<img width="589" alt="截屏2024-07-30 15 37 59" src="https://github.com/user-attachments/assets/31da963c-7636-4899-91d1-0d72905c537f">

**Comment by zx-zx22** [comment]
我都删了你还能看到啊（笑哭emoji） 不行 AutoComplete 也不行 跟Select一样 选中项也会错乱

**Comment by zombieJ** [comment]
那就说明 输入法 表里如一了，哈哈哈~

回过头来，这个组件侧面不好处理。因为会正常触发 input 的 `onChange` 事件，组件自身是不知道这个来自于输入法的。

**Comment by zx-zx22** [comment]
我发现了一个办法，可以让AutoComplete看起来正常
就是options使用一个useState  每次输入的时候在onChange事件里做筛选逻辑，然后重新set值

但是Select输入的时候不触发onChange事件

**Comment by zombieJ** [comment]
Select 里也有 `onSearch` 和 `searchValue` 可以受控，另外这个 issue 从组件侧看是正常行为，所以我这边就先关了哈~

**Comment by zx-zx22** [comment]
好的  感谢
