### ISSUE TITLE
Modal静态确认对话框中确认、关闭按钮样式在ConfigProvider主题下不生效

### ISSUE THREAD

**Issue by lian-bl** [ant-design/ant-design#50144]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-uekasg-3d2kka?embed=1&file=demo.tsx)

### Steps to reproduce

- 组件外层包裹ConfigProvider

- 全局配置主题色colorPrimary、colorInfo

- 代码片段如下：

  ```javascript
  const App: React.FC = () => (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: '#fa541c',
          colorInfo: '#fa541c',
        },
      }}
    >
      <Space wrap>
        <Button onClick={showConfirm}>Confirm</Button>
        <Button onClick={showPromiseConfirm}>With promise</Button>
        <Button onClick={showDeleteConfirm} type="dashed">
          Delete
        </Button>
        <Button onClick={showPropsConfirm} type="dashed">
          With extra props
        </Button>
      </Space>
    </ConfigProvider>
  );
  ```

### What is expected?

Modal对话框中确认、关闭按钮样式与ConfigProvider全局配置主题色保持一致

### What is actually happening?

Modal对话框中确认、关闭按钮样式未改变，仍是Antd默认主题色

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Chrome118 |

**Comment by zombieJ** [comment]
静态方法不支持 context，自然无法消费主题：
<img width="640" alt="截屏2024-07-30 10 55 47" src="https://github.com/user-attachments/assets/7a18eed0-d79b-4a08-a872-6400f0fc340c">

**Comment by crazyair** [comment]
如果你的主题色不需要动态改变，你可以用 ConfigProvider.holderRender

**Comment by lian-bl** [comment]
@zombieJ 又翻了下官网，问题已经解决了，灰常感谢！

**Comment by stylehuan** [comment]
> @zombieJ 又翻了下官网，问题已经解决了，灰常感谢！

有其他的方案吗？

**Comment by 8696** [comment]
我也是找了好久，我是从V4升级上去的，我以为要把所有通过静态方法调用的要改成Hook方式调用，终于找到了这个方法。连类组件都支持了。只需要放在ConfigProvider组件下的一个顶层组件中即可

https://ant-design.antgroup.com/components/config-provider-cn#config-provider-demo-holderrender

**Comment by crazyair** [comment]
> 我也是找了好久，我是从V4升级上去的，我以为要把所有通过静态方法调用的要改成Hook方式调用，终于找到了这个方法。连类组件都支持了。只需要放在ConfigProvider组件下的一个顶层组件中即可。原来使用的方式不需要改动
> 
> https://ant-design.antgroup.com/components/config-provider-cn#config-provider-demo-holderrender

我加的功能，能对大家有帮助，很是欣慰

**Comment by zhimng** [comment]
But i can not apply like this way - set `classNames` for `Modal`

```javascript
useLayoutEffect(() => {
    ConfigProvider.config({
      holderRender: (children) => (
        <StyleProvider hashPriority="high">
          <ConfigProvider
            prefixCls="static"
            iconPrefixCls="icon"
            locale={locale}
            theme={theme}
            modal={{
              classNames: {
                header: "red",
              },
            }}
          >
            <App message={{ maxCount: 1 }} notification={{ maxCount: 1 }}>
              {children}
            </App>
          </ConfigProvider>
        </StyleProvider>
      ),
    });
  }, [locale, theme]);
```
