### ISSUE TITLE
Antd export ComponentsConfig type

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#50147]
### What problem does this feature solve?

Exporting this type allows user to build custom component theme while still getting the Type

### What does the proposed API look like?

export type ComponentsConfig

![image](https://github.com/user-attachments/assets/c5731357-df90-48e1-bb13-484eae9edb98)

**Comment by zombieJ** [comment]
Use `GetProp` util for any type, ref https://ant.design/components/_util#getprops :

```tsx
import type { GetProp, ConfigProviderProps } from 'antd';

type ComponentsConfig = GetProp<ConfigConsumerProps, 'theme'>['components'];
```
