### ISSUE TITLE
添加`App`在使用自定义组件作为`component`时的使用说明

### ISSUE THREAD

**Issue by dislido** [ant-design/ant-design#50145]
### What problem does this feature solve?

`component`可能会被误解为类似`children`的功能，使用自定义组件作为`component`时如果没有接收`className`和`children`，会导致样式丢失和`useApp`不能正常使用

### What does the proposed API look like?

在文档中添加相关说明

**Comment by Wxh16144** [comment]
印象中我改进过这部分说明🤔。

> component可能会被误解为类似children的功能

我感觉开发者没有认真看文档才会有这个疑惑。

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/66f83feb-6a06-478e-be1c-9b0d0334b74f">

**Comment by dislido** [comment]
确实是脑子没转过来，明白component可以用来替换默认的`<div>`，但没意识到它是作为容器而不是内容
```tsx
const Component = ({ children, ...props }) => <div id="aaa" {...props}>bbb{children}</div>;
<App component={Component} />

// 实际用法应该是
<App component={(...props) => <div id="aaa" {...props} />}>bbb</App>
```
