### ISSUE TITLE
 Typography的text省略了但Tooltip无法显示

### ISSUE THREAD

**Issue by Dmaziyo** [ant-design/ant-design#50143]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-mkruhi?file=demo.tsx)

### Steps to reproduce

当父元素的宽度非常接近文本内容宽度的时候，文本会省略，但是无法显示tooltip

### What is expected?

希望能够显示tooltip

### What is actually happening?

未能显示tooltip

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.1 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
精度的老问题，js 里获取的宽度是一致的。导致以为没有在省略。
