### ISSUE TITLE
Bottom placed notification is not showing up

### ISSUE THREAD

**Issue by eljose47** [ant-design/ant-design#50155]
### Reproduction link

[https://ant.design/components/notification#notification-demo-placement](https://ant.design/components/notification#notification-demo-placement)

### Steps to reproduce

Click the "bottom" button

### What is expected?

A notification on the bottom part of the screen is shown

### What is actually happening?

No notification is show at all.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.2.0 |
| System | Linux Mint 21.2 |
| Browser | Firefox 128 |

---
Other placement options work just fine. I also asked my colleagues on macOS and Windows on Firefox and it works for them.

**Comment by Wxh16144** [comment]
It seems to work very well?

https://github.com/user-attachments/assets/34ac55d8-00a1-4fd9-92f4-135ce97e8f28

**Comment by afc163** [comment]
I can't reproduce it. Could you provide a screen record video?

**Comment by eljose47** [comment]
Ok, somehow turning this extension off ([https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/](url)) resolved the issue for me

Here is a video of when the extension is on and the button is not working
https://github.com/user-attachments/assets/6530efd5-ae2a-4046-b699-d41f46714a07

**Comment by afc163** [comment]
> Ok, somehow turning this extension off ([https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/](https://github.com/ant-design/ant-design/issues/url)) resolved the issue for me

That is it.
