### ISSUE TITLE
Ant Design Table grouping columns does not apply sorting (5.19.4)

### ISSUE THREAD

**Issue by hayagamal** [ant-design/ant-design#50154]
### Reproduction link

[https://ant.design/~demos/table-demo-grouping-columns](https://ant.design/~demos/table-demo-grouping-columns)

### Steps to reproduce

Either click on Age header or sorting arrows for this grouping column child

### What is expected?

expected to sort Column Age when clicking on Age header

### What is actually happening?

nothing occurs

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.3.1 |
| System | MacOS 14.0 |
| Browser | Google Chrome Version 127.0.6533.72 (Official Build) (arm64) |

**Comment by afc163** [comment]
cc @Zyf665
