### ISSUE TITLE
DatePicker picker=week支持showWeek=false，允许隐藏周序号

### ISSUE THREAD

**Issue by Jiny3213** [ant-design/ant-design#50157]
### What problem does this feature solve?

周序号可能会使用户困惑，有功能冗余，希望能够提供隐藏周序号的功能

### What does the proposed API look like?

```
<DatePicker
   picker="week"
   showWeek={false}
/>
```

![截屏2024-07-30 20 18 13](https://github.com/user-attachments/assets/dbf3de1c-95aa-41e1-b85c-b1b817cdbd3f)

**Comment by afc163** [comment]
是支持的 https://ant.design/changelog-cn#5140 ，但是好像针对 `picker="weeker"` 是失效的。

https://stackblitz.com/edit/react-kpjsc5?file=demo.tsx

**Comment by Jiny3213** [comment]
[rc-picker#853](https://github.com/react-component/picker/pull/853)
提交了pr

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/picker/releases/tag/v4.6.11
