### ISSUE TITLE
Select not working inside segmented

### ISSUE THREAD

**Issue by shazebCeloxis** [ant-design/ant-design#50153]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-gwpxqv?file=demo.tsx)

### Steps to reproduce

Click on any of the segmented options to display a select component. Now, click on it to open the dropdown menu and select an option. If you click on the same select component again, the dropdown menu won't open.

### What is expected?

I should be able to open the dropdown after clicking on select which is inside segmented component.

### What is actually happening?

I have placed a select component inside a segmented component. When I click on one of the segmented options, the select component gets mounted correctly. However, the issue arises when I try to open the dropdown of the select component: it opens the first time, but after that, the dropdown does not open again.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.2.0 |
| System | Sonoma 14.5 |
| Browser | Version 126.0.6478.182 (Official Build) (arm64) |

**Comment by zombieJ** [comment]
Prevent event for the element what you need: https://stackblitz.com/edit/react-gwpxqv-6upxy3?file=demo.tsx

**Comment by crazyair** [comment]
> Prevent event for the element what you need: https://stackblitz.com/edit/react-gwpxqv-6upxy3?file=demo.tsx

`blockEvent` should be placed on `Select`
