### ISSUE TITLE
[Checkbox/多选框 & Radio/单选框] 希望增加2个api，可能会更方便

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50163]
### What problem does this feature solve?

1. Size尺寸，就像input那样
2. 状态样式自定义，比如传入自定义的组件表示状态什么的。

### What does the proposed API look like?

- size:大中小，就像input那样，如果还能传入数字，自定义尺寸就更好了。（如果打算这样做，更建议 input 等有size的组件，也要统一api）
- 状态我就不知道用什么合适了，比如render？这样无论是对号还是什么其他的图标，就比较自由了。当然checkbox的indeterminate也得可以自定义。比如半选，用一个横条表示可能更符合，否则通过其他的方式改起来都不如官方支持最简单有效。

**Comment by afc163** [comment]
> Size尺寸，就像input那样

在设计规范上目前 checkbox 没有大中小的表达需求。

> 状态样式自定义，比如传入自定义的组件表示状态什么的。

这个没有太理解，有 API 描述或者截图解释么？解决什么问题？

**Comment by kwooshung** [comment]
> 这个没有太理解，有 API 描述或者截图解释么？解决什么问题？

我写个伪代码吧：
```
import React from 'react';
import { Checkbox } from 'antd';
import type { CheckboxProps } from 'antd';

const App: React.FC = () => <Checkbox onChange={onChange} stateChecked={xxx} stateUnChecked={yyy}  stateIndeterminate={nnn}>Checkbox</Checkbox>;

export default App;
```

就是stateChecked、stateUnChecked、stateIndeterminate可以传入自己的组件或图表之类的，作为不同状态的显示。

**Comment by afc163** [comment]
这样基本上相当于把组件原本的 UI 完全换掉了，只保留点击 toggle 的交互，Checkbox 已经是很原子的组件了，做这种完全的自定义不太合理。这种场景建议自行实现一个自定义 Checkbox，成本也不会高。

**Comment by kwooshung** [comment]
> 这样基本上相当于把组件原本的 UI 完全换掉了，只保留点击 toggle 的交互，Checkbox 已经是很原子的组件了，做这种彻底的自定义不太合理。这种场景建议自行实现一个自定义 Checkbox，成本也不会高。

说的也是
