### ISSUE TITLE
[Tour/漫游式引导] 希望高亮的地方，可以支持圆角，甚至可以设置圆角尺寸

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50164]
### What problem does this feature solve?

不然视觉上太突兀了，antd的设计无论按钮还是什么都是圆角的，结果到了这个组件上，是直角的，有点格格不入。

**Comment by afc163** [comment]
应该可以暴露出一个 token 出来。

**Comment by MadCcc** [comment]
现在的 mask 是四个 svg 拼起来的，如果改成 box-shadow 实现可能可以实现这个需求

**Comment by kwooshung** [comment]
> 现在的 mask 是四个 svg 拼起来的，如果改成 box-shadow 实现可能可以实现这个需求

![image](https://github.com/user-attachments/assets/9446de6d-bf3b-4440-ad2a-17a37930de09)

这样做确实可以 @afc163 @MadCcc

**Comment by afc163** [comment]
这个问题好像没解决？

**Comment by kwooshung** [comment]
> 这个问题好像没解决？

是的，不知道官方还愿意修复否。

**Comment by sakuraee** [comment]
我看了下代码，感觉这个高亮区域是支持圆角的啊，默认是2px，然后可以在Tour组件上添加gap属性例如gap={{radius: "20px"}}

得到修改，但是看到文档和实例上都没有提及到

**Comment by IsKaros** [comment]
rc-tour的demo中gap字段的radius应该能满足这个需求？看代码是svg的rx做的
![image](https://github.com/user-attachments/assets/c020f59a-cad0-4e7b-b742-67f28fa78982)

**Comment by afc163** [comment]
@IsKaros 来个 PR 帮忙补一下？感谢

**Comment by IsKaros** [comment]
> @IsKaros 来个 PR 帮忙补一下？感谢

好的，我明天弄一下。
