### ISSUE TITLE
DatePicker 使用 disabledDate 的 info.from 后，组件展示问题

### ISSUE THREAD

**Issue by DelMemory** [ant-design/ant-design#50167]
### Reproduction link

[https://stackblitz.com/edit/react-9xobvj?file=demo.tsx](https://stackblitz.com/edit/react-9xobvj?file=demo.tsx)

### Steps to reproduce

在demo中，
先选择开始时间，
之后直接点击选择器结束时间上方的 年（例如： 2024 年），
在该操作之后，面板无法进行下一步操作，所有年份都被置灰，且开始时间选中的年份也不可点击

https://github.com/user-attachments/assets/48b18826-97d9-4a83-9ceb-d24b14f8c132

### What is expected?

可选择在限制中可选的十年、年、月

### What is actually happening?

在时间限制足够小的情况下，用户只要点击到上方的年月切换按钮，就会无法进行下一步操作，只能取消重来

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | react |
| System | macos ventura 13.4.1 (22F82) |
| Browser | chrome 126.0.6478.185 |

---
进行版本升级后碰到该问题，原有的问题在 antd v4 版本中不存在，且原有系统时间组件使用的 disabledDate 时间限制，也会碰到该问题

**Comment by zombieJ** [comment]
> 先点击时间选择器右边的清空选项

默认是不展示这个的，怎么点击？来个录屏看看吧~~

**Comment by DelMemory** [comment]
Uploading 屏幕录制2024-07-31 10.28.20.mov…

直接操作也可以展示该问题

**Comment by DelMemory** [comment]
@zombieJ 已更新上传录屏了，你问的截图部分我删除掉了，实际上不论原来有没有参数，只需要先点击开始时间都会触发

**Comment by DelMemory** [comment]
> > 先点击时间选择器右边的清空选项
> 
> 默认是不展示这个的，怎么点击？来个录屏看看吧~~

已更新上传录屏了，你问的截图部分我删除掉了，实际上不论原来有没有参数，只需要先点击开始时间都会触发

**Comment by DelMemory** [comment]
@zombieJ 已更新demo 和 录屏，截图部分不触发也会导致年不可选，只需要先选择开始时间即可，v4版本的简易代码也在demo中

**Comment by MadCcc** [comment]
demo 问题

**Comment by DelMemory** [comment]
![image](https://github.com/user-attachments/assets/4c41a41e-20ef-45c2-bad2-d425f5991f1b)
@zombieJ 十年的问题没解决
