### ISSUE TITLE
Upgrade to TypeScript 2.2

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#5016]
- https://blogs.msdn.microsoft.com/typescript/2017/02/22/announcing-typescript-2-2/
- https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-22
- https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-22

---

- https://github.com/ant-design/ant-design/blob/2bf6e226537744a1de9e662ae313fb7d92f6b4f2/package.json#L135
- https://github.com/ant-design/antd-tools/blob/c5ec9ea279443c2becdf98de5a694ac76ddec028/package.json#L51

**Comment by infeng** [comment]
`Form.create()` should update through `Mix-in classes`

**Comment by afc163** [comment]
Any progress? @ddcat1115

**Comment by ddcat1115** [comment]
working on it ...

**Comment by ddcat1115** [comment]
@infeng I'm not sure how to make this change, could you explain in more detail or make a pr when you are free?

**Comment by afc163** [comment]
https://www.zhihu.com/question/33629737/answer/148571752

@infeng @bang88 About 2.2 mixin class.
