### ISSUE TITLE
[Spin/加载中] 希望在指定自定义指示符的时候，percent进度也一样可以生效

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50162]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-antd-issues-50162?file=demo.tsx)

### Steps to reproduce

```
<Spin
        percent={mergedPercent}
        // 按理说，应该也会有进度变化，可是自定义了样式，就没有进度变化了。也就是说 indicator 和 percent 功能，只能二选一了。
        indicator={<LoadingOutlined spin />}
        size="small"
      />
```

### What is expected?

自定义指示符，percent不会失效，一样能切换

### What is actually happening?

现在只有自定义提示符起作用，无法切换到percent

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18 |
| System | MacOS/Windows11 |
| Browser | Chrome/Edge 都是截止到提交问题前的最新版本 |

**Comment by afc163** [comment]
> 自定义指示符，percent失效了

从你的表达方式来看，我感觉你是在反馈 bug，而不是一个 feature request。请使用 bug report 的模板，并提供问题重现链接。

**Comment by kwooshung** [comment]
> 从你的表达方式来看，我感觉你是在反馈 bug，而不是一个 feature request。请使用 bug report 的模板，并提供问题重现链接。

很抱歉，是我的疏忽，给你们添加麻烦了，我现在重新按照规定修改了内容。

**Comment by afc163** [comment]
```
<Spin percent={mergedPercent} indicator={<LoadingOutlined spin />} />
```

对于这样的代码，你希望 UI 长什么样？百分比如何用 `<LoadingOutlined spin />` 表达？

```
<Spin percent={mergedPercent} indicator={<span>加载中</span>} />
```

或者这样的，要如何表达？

**Comment by kwooshung** [comment]
可能是我没说清楚，就是说官方的这个案例，应该不止可以默认的样式变成那个圆圈的进度，设置了indicator也可以变换成其他的。
![image](https://github.com/user-attachments/assets/80ecacc9-4713-4646-9c1d-b3d83d2a357a)

我看官方也是两个样式互相切换，就像下图那样。
![image](https://github.com/user-attachments/assets/8463d10f-ef6d-4254-9e4b-808e34dd5689)

**Comment by afc163** [comment]
问题就是不知道应该变成什么样，当指定了 indicator 内容就固化了，想加 percent 也不知道应该怎么加了。

**Comment by kwooshung** [comment]
我的意思是，他们之间不影响，你看下面的gif，不知道我是不是说明白了呢.
![预期效果2](https://github.com/user-attachments/assets/229815bf-d3f7-46b2-841a-1eb4c505014d)

**Comment by afc163** [comment]
这是目前的表现，indicator 的优先级最高，直接覆盖了 percent：https://codepen.io/afc163-1472555193/pen/GRbWrEM?editors=0010

<img width="91" alt="图片" src="https://github.com/user-attachments/assets/d6db89ad-d8c9-4fbe-b335-cdfd58729409">

```
      <Spin indicator={<span>ing</span>} />
      <br />
      <Spin percent={0} indicator={<span>ing</span>} />
      <br />
      <Spin percent={50} indicator={<span>ing</span>} />
      <br />
      <Spin percent={100} indicator={<span>ing</span>} />
      <br />
      <Spin percent="auto" indicator={<span>ing</span>} />
```

---

你期望的 UI 是什么，可以从上到下写一下。

**Comment by kwooshung** [comment]
嗨，我发现是我自己理解的错误，这部分是自己实现的。
