### ISSUE TITLE
使用antd-V5版本组件的css会出现一直在使用缓存，无法清除

### ISSUE THREAD

**Issue by 18046163690** [ant-design/ant-design#50172]
### Reproduction link

[https://ant-design.antgroup.com/components/icon-cn](https://ant-design.antgroup.com/components/icon-cn)

### Steps to reproduce

1. 在一个类命中增加一段css
.lessonSettingWrap{
      : global {
          .ant-btn .anticon {
              color: #6492ed;
          }
      }
}

2. 此时页面上能够正常展示css的效果
3. 当我将这段样式去掉之后，这段css并没有失效，而是缓存了下来
4. 我尝试将.umi文件删除后重启，发现还是一样
5. 之间的v4版本并没有这样的缓存问题，是不是用了css-in-js的原因？？
 

### What is expected?

css代码删除之后，不再使用缓存

### What is actually happening?

css缓存仍存在，且不知道怎么清空该缓存

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2 |
| System | window |
| Browser | Chrome 127.0.6533.73 |

**Comment by MadCcc** [comment]
cssinjs 无关，这是你自己添加的样式。

**Comment by 18046163690** [comment]
> cssinjs 无关，这是你自己添加的样式。

主要是我已经把样式在我代码那边删了，在调试工具那边看还是存在，而且样式有生效

**Comment by afc163** [comment]
@18046163690 你这个问题看上去与 antd 本身无关。

**Comment by 18046163690** [comment]
> @18046163690 你这个问题看上去与 antd 本身无关，更像是研发框架的问题。

你指的是pro框架做的一些处理？还是项目里面的，我全局搜了没有这个类名，只有我之前写的，但是已经删掉了，现在看好像是缓存了

**Comment by 18046163690** [comment]
![QQ20240801-092618](https://github.com/user-attachments/assets/7550c1de-9590-4c1c-ab60-af306186e515)
