### ISSUE TITLE
Date Picker 的 `cellRender` 中获取的日期不正确

### ISSUE THREAD

**Issue by TecFancy** [ant-design/ant-design#50175]
### Reproduction link

[https://codepen.io/smpower/pen/oNrBKWd](https://codepen.io/smpower/pen/oNrBKWd)

### Steps to reproduce

1. 使用 Date Picker 组件；
2. cellRender 自定义渲染单元格内容和样式。

### What is expected?

文档中说明，可以用 cellRender 方法渲染单元格的内容和样式。但是在 current 中的日期默认输出当前面板的日期，对于相邻的月份的日期无法自定义渲染单元格的内容和样式。

所以，希望能输出正确月份的日期。

### What is actually happening?

渲染的日期无法区分年份、月份和日子

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18.2.0 |
| System | Windows |
| Browser | Version 127.0.6533.72 (Official Build) (64-bit) |

**Comment by afc163** [comment]
> 但是在 current 中的日期默认输出当前面板的日期，对于相邻的月份的日期无法自定义渲染单元格的内容和样式。

这句话我没有理解，你预期的正确行为是什么，目前实际的表现是什么，两者的区别是什么？

**Comment by TecFancy** [comment]
多谢提醒，通过 current.format() 方法确实可以拿到正确的日期 ;-)

**Comment by afc163** [comment]
current 是一个当前单元格对应的 dayjs 对象。
