### ISSUE TITLE
[Spin/加载中] 希望可以将indicator属性，可以在全局设置。

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50182]
### What problem does this feature solve?

就像标题说的这样，因为如果整个项目都想修改一下这个效果，总不能用一次，修改一次，对吧。

### What does the proposed API look like?

这个属于功能改善，没有什么更多的api说明

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by kwooshung** [comment]
> What does the proposed API look like?

我的意思全局token，直接在ConfigProvider中配置

**Comment by afc163** [comment]
可行。

**Comment by kwooshung** [comment]
一直没有仔细了解antd5版本，而且目前赶时间做项目；
有时间研究下，目前可能对我来讲提交pr，可能有点困难。

**Comment by coding-ice** [comment]
> 一直没有仔细了解antd5版本，而且目前赶时间做项目； 有时间研究下，目前对我来讲提交pr，一时半会可能没有时间。 过段时间抽出空，我试试，熟练地伙伴也可提交。

我来～

**Comment by wanpan11** [comment]
这个功能好像是支持的

![image](https://github.com/user-attachments/assets/f310bf0b-7777-41ab-8a14-8de93b4dae0d)

**Comment by kwooshung** [comment]
@wanpan11 哎哟，我没看仔细，已经有了这个。不过吧，我觉得可能在ConfigProvider中，更统一些吧。

**Comment by coding-ice** [comment]
臣附议，感觉这种统一会好点，减少点学习成本

**Comment by kwooshung** [comment]
> 臣附议，感觉这种统一会好点，减少点学习成本

赞同！！
