### ISSUE TITLE
[InputTag/标签输入框] 希望增加这个组件

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50181]
### What problem does this feature solve?

tag输入框，用于输入文本标签。

### What does the proposed API look like?

可以参考这个：https://arco.design/react/components/input-tag

-------
Input一次性密码框的5个改善功能，issues关闭了，应该是我没有正确表达出我所说的改善的需求，在这个 https://github.com/ant-design/ant-design/issues/50165 中，我重新表达了一下，希望能再看下。

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/50165
