### ISSUE TITLE
Tooltip is not working with forwardRef element

### ISSUE THREAD

**Issue by shadoworion** [ant-design/ant-design#50186]
### Reproduction link

[https://codesandbox.io/p/devbox/still-dawn-forked-sflx42?workspaceId=251b18e6-0539-446b-84fb-ce3e0efa698a](https://codesandbox.io/p/devbox/still-dawn-forked-sflx42?workspaceId=251b18e6-0539-446b-84fb-ce3e0efa698a)

### Steps to reproduce

> Why does the warning findDOMNode is deprecated some times appear in strict mode?
This is due to the implementation of rc-trigger. rc-trigger forces children to accept ref, otherwise it will fall back to findDOMNode, so children need to be native html tags. If not, you need to use React.forwardRef transparently passes ref to native html tags.

```
import { forwardRef, LegacyRef } from "react";
import cx from "classnames";

type Props = {
  icon: JSX.Element;
  classNames?: string;
};

export const RefIcon = forwardRef(
  ({ icon, classNames }: Props, ref: LegacyRef<HTMLSpanElement>) => {
    return (
      <span ref={ref} className={cx("anticon", classNames)}>
        {icon}
      </span>
    );
  }
);
```

```
import { Tooltip } from "antd";
import { GrDocumentTest } from "react-icons/gr";
import { RefIcon } from "../RefIcon";

<Tooltip title="test">
  <RefIcon icon={<GrDocumentTest size="1.2rem" />} />
</Tooltip>
```

### What is expected?

On hover, I see a tooltip.

### What is actually happening?

I don't see a tooltip.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.3.1 |
| System | MacOS 14.5 |
| Browser | Edge 127.0.2651.74 |

**Comment by shadoworion** [comment]
@afc163 

https://codesandbox.io/p/devbox/9h2xzp?migrateFrom=87h5dk

**Comment by shadoworion** [comment]
@afc163 

https://codesandbox.io/p/devbox/still-dawn-forked-sflx42?workspaceId=251b18e6-0539-446b-84fb-ce3e0efa698a

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15909
