### ISSUE TITLE
antd自带的图标，如何用字符串来渲染图标

### ISSUE THREAD

**Issue by kushu001** [ant-design/ant-design#50193]
### What problem does this feature solve?

比如我有个图标选择器，里面包含了系统自带的图标显示，那我保存的时候应该是 `"StepBackwardOutlined"`, `"StepForwardOutlined"`这样的字符串

然后在另外一个页面上要渲染我这个设置的图标我需要类似于` iconType='StepBackwardOutlined' <Icon type={iconType} />`,  这样子来渲染

目前系统中好像只能写死的组件`<StepBackwardOutlined />`或者用条件判断来处理（本质还是固定组件的写法）

### What does the proposed API look like?

类似于这样的吧 `<Icon type="StepBackwardOutlined" />`

**Comment by csic21** [comment]
可以自己封装一个map映射一下

**Comment by afc163** [comment]
> 可以自己封装一个map映射一下

+1

**Comment by yoyo837** [comment]
参见 https://github.com/ant-design/ant-design/issues/12011 ，你说的是之前的用的被弃用的方式。

**Comment by afc163** [comment]
在 Ant Design (antd) 中，你可以使用 `@ant-design/icons` 库中的图标，并通过字符串来动态渲染图标。这需要结合 React 的动态组件渲染功能。以下是具体步骤：

1. **安装依赖**：确保你已经安装了 `@ant-design/icons` 库。如果没有安装，可以运行以下命令：

    ```bash
    npm install @ant-design/icons
    ```

2. **导入图标**：导入所有需要的图标。这里使用 `import * as Icons` 的方式导入所有图标，这样可以通过字符串来动态渲染图标。

3. **动态渲染图标**：通过字符串匹配相应的图标并渲染。

以下是一个完整的示例代码：

```jsx
import React from 'react';
import * as Icons from '@ant-design/icons';
import { Select } from 'antd';

// 示例图标名称数组
const iconNames = [
  'HomeOutlined',
  'SettingOutlined',
  'UserOutlined',
  'BellOutlined',
  'MailOutlined',
];

// 动态图标渲染组件
const DynamicIcon = ({ iconName }) => {
  const IconComponent = Icons[iconName];
  return IconComponent ? <IconComponent /> : null;
};

const App = () => {
  const [selectedIcon, setSelectedIcon] = React.useState(iconNames[0]);

  return (
    <div>
      <h1>Ant Design 图标动态渲染示例</h1>
      <Select
        value={selectedIcon}
        onChange={setSelectedIcon}
        style={{ width: 200 }}
      >
        {iconNames.map((iconName) => (
          <Select.Option key={iconName} value={iconName}>
            {iconName}
          </Select.Option>
        ))}
      </Select>
      <div style={{ marginTop: 20 }}>
        <DynamicIcon iconName={selectedIcon} />
      </div>
    </div>
  );
};

export default App;
```

### 说明

1. **导入所有图标**：
   ```jsx
   import * as Icons from '@ant-design/icons';
   ```
   这将 `@ant-design/icons` 中的所有导出都放在 `Icons` 对象中。

2. **动态图标渲染组件**：
   ```jsx
   const DynamicIcon = ({ iconName }) => {
     const IconComponent = Icons[iconName];
     return IconComponent ? <IconComponent /> : null;
   };
   ```
   这个组件通过传入的 `iconName` 从 `Icons` 对象中动态获取对应的图标组件并渲染。

3. **在应用中使用**：
   ```jsx
   const App = () => {
     const [selectedIcon, setSelectedIcon] = React.useState(iconNames[0]);

     return (
       <div>
         <h1>Ant Design 图标动态渲染示例</h1>
         <Select
           value={selectedIcon}
           onChange={setSelectedIcon}
           style={{ width: 200 }}
         >
           {iconNames.map((iconName) => (
             <Select.Option key={iconName} value={iconName}>
               {iconName}
             </Select.Option>
           ))}
         </Select>
         <div style={{ marginTop: 20 }}>
           <DynamicIcon iconName={selectedIcon} />
         </div>
       </div>
     );
   };
   ```

   在应用中使用 `Select` 组件来选择图标，通过 `DynamicIcon` 组件来动态渲染选中的图标。

这种方法可以让你根据字符串动态渲染 Ant Design 的图标，非常灵活和实用。

**Comment by afc163** [comment]
通过字符串动态渲染 Ant Design 图标虽然灵活，但也有一些缺点，这也是为什么 Ant Design 默认不采用这种方式引用图标的原因。主要缺点包括：

1. **体积较大**：
   - 导入 `@ant-design/icons` 中的所有图标会增加应用的体积，即使只使用其中一部分图标。这会导致应用的初始加载时间变长，尤其是对于移动设备和低带宽环境。
   
2. **无法进行 Tree Shaking**：
   - Tree Shaking 是一种去除未使用代码的优化技术。通过字符串动态渲染图标，Tree Shaking 无法有效地去除未使用的图标代码，因为它无法静态分析出哪些图标实际被使用。

3. **性能问题**：
   - 动态导入所有图标并根据字符串渲染可能会增加运行时的开销，尤其是在大量图标频繁切换或更新的情况下。

4. **类型安全性**：
   - 动态字符串渲染图标缺乏类型安全性。字符串拼写错误或无效的图标名称在编译时不会报错，而是在运行时才会暴露问题，这增加了调试和维护的难度。

5. **潜在的代码分割问题**：
   - 由于所有图标都被一次性导入，这可能会影响代码分割和懒加载的效果，使得某些页面加载不必要的图标资源。

### Ant Design 默认不使用这种方式的原因

为了避免上述缺点，Ant Design 默认采用了按需引入图标的方式。具体做法如下：

1. **按需引入**：
   - 只引入需要的图标，例如 `import { HomeOutlined, SettingOutlined } from '@ant-design/icons';`，这样只会打包和加载这些特定的图标。

2. **更好的 Tree Shaking 支持**：
   - 通过按需引入，Tree Shaking 可以有效地去除未使用的图标代码，减少打包后的体积。

3. **性能优化**：
   - 按需引入减少了初始加载时间和运行时的开销，提高了应用性能。

4. **类型安全性**：
   - 通过显式地导入图标，可以在编译时捕获拼写错误或无效的图标引用，提高了代码的类型安全性和可维护性。

5. **代码分割和懒加载**：
   - 按需引入有助于更好地进行代码分割，使得页面只加载需要的资源，进一步优化加载性能。

### 示例：按需引入图标

下面是一个按需引入图标的示例：

```jsx
import React from 'react';
import { HomeOutlined, SettingOutlined, UserOutlined } from '@ant-design/icons';
import { Select } from 'antd';

const iconMap = {
  HomeOutlined: HomeOutlined,
  SettingOutlined: SettingOutlined,
  UserOutlined: UserOutlined,
};

const App = () => {
  const [selectedIcon, setSelectedIcon] = React.useState('HomeOutlined');

  const IconComponent = iconMap[selectedIcon];

  return (
    <div>
      <h1>Ant Design 图标按需引入示例</h1>
      <Select value={selectedIcon} onChange={setSelectedIcon} style={{ width: 200 }}>
        {Object.keys(iconMap).map((iconName) => (
          <Select.Option key={iconName} value={iconName}>
            {iconName}
          </Select.Option>
        ))}
      </Select>
      <div style={{ marginTop: 20 }}>
        {IconComponent && <IconComponent />}
      </div>
    </div>
  );
};

export default App;
```

### 总结

通过字符串动态渲染图标虽然灵活，但在性能、体积、类型安全性和代码维护方面有明显缺点。因此，Ant Design 默认采用按需引入图标的方式，以优化应用的性能和开发体验。
