### ISSUE TITLE
table columns 中配置的filter怎么动态刷新

### ISSUE THREAD

**Issue by Jinsdw** [ant-design/ant-design#50195]
![1722566624461](https://github.com/user-attachments/assets/638e9093-f559-4746-a914-20888089d030)
### What problem does this feature solve?

columns 中配置的filter没有动态刷新

### What does the proposed API look like?

提供一个手动刷新的方法

**Comment by Jinsdw** [comment]
<img width="205" alt="11" src="https://github.com/user-attachments/assets/668db789-e42e-45b2-bf99-bad00eef1ae5">
求助 ， 我这个filters?.countries是设置的status数据，当我从接口拿到新数据set的时候columns没有刷新，我应该怎么处理能让他刷新columns

**Comment by afc163** [comment]
> columns 中配置的filter没有动态刷新

反馈 bug 需要重现链接。

**Comment by day-xue** [comment]
> <img alt="11" width="205" src="https://private-user-images.githubusercontent.com/94216074/354442848-668db789-e42e-45b2-bf99-bad00eef1ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjY4MjAsIm5iZiI6MTcyMjgyNjUyMCwicGF0aCI6Ii85NDIxNjA3NC8zNTQ0NDI4NDgtNjY4ZGI3ODktZTQyZS00NWIyLWJmOTktYmFkMDBlZWYxYWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAyNTUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YmM3NGMxMTMyNTdkNGZlNWM0ZWVmNzdiNGJlZDJkYjk1YzIwNDk2MjQ3YWMxOGVhY2ZjZjFhMjg2NWY0N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98SpW2Xjc61ITHSmzwc3Bd-iO5peoaJOzk007slqxvs"> 求助 ， 我这个filters?.countries是设置的status数据，当我从接口拿到新数据set的时候columns没有刷新，我应该怎么处理能让他刷新columns

useMemo 包裹一下依赖接口返回的
