### ISSUE TITLE
message 弹出后页面没有响应了

### ISSUE THREAD

**Issue by crapthings** [ant-design/ant-design#5019]
看上去是因为 message 复制了一个 react 根节点然后把 message box append 到新的节点了

antd 2.7.2

meteor + flow router + react-mounter 最新版本

osx browser chrome 最新版本

<img width="982" alt="wx20170223-125656 2x" src="https://cloud.githubusercontent.com/assets/1147704/23245465/a23f9f98-f9c7-11e6-950e-9c36c7cd98a5.png">

FlowRouter 进入路由执行了 action

mounter 负责和 render 类似的行为把 组件放进 layout 中

https://github.com/kadirahq/react-mounter/blob/master/lib/client.js

或者说我可以通过配置一下  react mounter 来兼容 antd ?

**Comment by afc163** [comment]
Sorry about you problem but it works fine in http://ant.design/components/message/ .

You should check your code first and provide a reproducible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by crapthings** [comment]
看一下你们源码 兼容性确实不是很好

https://github.com/react-component/notification/blob/master/src/Notification.jsx#L93

**Comment by afc163** [comment]
If something of our code can be improved to make your code work, just propose PR.

**Comment by afc163** [comment]
https://github.com/react-component/notification/pull/14
