### ISSUE TITLE
Select component displays value instead of label

### ISSUE THREAD

**Issue by JenniferGoijman** [ant-design/ant-design#50190]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-nditzv?file=src%2Fcomponents%2FDynamicForm.tsx,src%2FApp.tsx)

### Steps to reproduce

After applying the filter, when I select an option from the filtered list, the Select component displays the value (the id of the field) instead of the label (the name of the field).

### What is expected?

The Select component should display the name of the field after selection.

### What is actually happening?

The Select component displays the id of the field after selection.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.3.1 |
| System | macOs Sonoma 14.5 |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
When the option will remove from the `options`, you can use `labelInValue` to keep the `label` content removed option.
