### ISSUE TITLE
With the table header background colour set to transparency, the fixed column cannot hide the text behind it.

### ISSUE THREAD

**Issue by zhenzhenChange** [ant-design/ant-design#50196]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-mtrhhk?file=demo.tsx)

### Steps to reproduce

<img width="969" alt="image" src="https://github.com/user-attachments/assets/3776e880-3851-450b-b67c-dfd6ef35c1d0">

### What is expected?

None

### What is actually happening?

None

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.3.1 |
| System | macOS 14.4.1 - arm64 Apple M2 Pro |
| Browser | Chrome: 126.0.6478.62 |

**Comment by afc163** [comment]
We can do nothing, don't make it alpha color.
