### ISSUE TITLE
input ref 设置默认值，聚焦输入时会消失

### ISSUE THREAD

**Issue by likelikeit** [ant-design/ant-design#50197]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/determined-bush-m7g8nz?file=%2Fsrc%2FApp.tsx)

### Steps to reproduce

点击codesandbox打开页面，聚焦input输入框，会发现默认值test消失了

### What is expected?

聚焦输入时，默认值不应该消失

### What is actually happening?

默认值消失

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by Wxh16144** [comment]
好奇有什么理由不用非受控使用输入框？

**Comment by zombieJ** [comment]
[FAQ: 官方文档中没有提供的隐藏 API 我可以使用吗？](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)

不要去调用内部内容，不会保证它的行为正确性，也不会认为其任何表现是 BUG。

**Comment by likelikeit** [comment]
> 消失掉确实很奇怪，用原生代替都不会！不过我好奇有什么理由不用非受控使用输入框？

比如说这样一个场景：
点击某个按钮的时候打开一个弹窗，进行改名，如果可以使用ref，我不用关系受控的value
![image](https://github.com/user-attachments/assets/66d31f91-8553-4986-9e3f-75a96df35ee7)
