### ISSUE TITLE
Dropdown items[] not reading state (nextjs 14)

### ISSUE THREAD

**Issue by vitalijalbu** [ant-design/ant-design#50204]
### Reproduction link

[https://github.com/ant-design/ant-design/discussions/50202](https://github.com/ant-design/ant-design/discussions/50202)

### Steps to reproduce

Hi guys, yesterday it worked fine, but today I have a very strange bug...
Basically I have Tables and each row has a Dropdown component.
When I click on Dropdown, I setState of the selected record to access then information of the record inside the Dropdown items[].

State is setting correctly, but items read undefined... how come? Anyone ever had this type of issue?

### What is expected?

Reading state (if i create a new button and click to read teh state, it works fine)

### What is actually happening?

Error

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by vitali-bc** [comment]
@zombieJ code is already on the discussion, sorry i cannot do a **codesandbox**

**Comment by vitalijalbu** [comment]
my fault, issue was because i tried to extend the table and add a switch to toggle columns visibility

**Comment by vitalijalbu** [comment]
btw, anyone knows how to do a dropdown to show/hide columns inside a table??
