### ISSUE TITLE
Also add the ```disabled``` property to the form controls after wrapping the component by ```Form.Item```

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#50212]
### What problem does this feature solve?

In my project, I created a custom input component. When wrapping it with Form.Item, I find the `value` and `onChange` properties as stated in the documentation. In my opinion, it would be useful to also pass the `disabled` property because currently, I can’t manage it unless I explicitly pass it to my component.

### What does the proposed API look like?

https://stackblitz.com/edit/vitejs-vite-pjddhj?file=src%2Fcomponents%2FMyInput.tsx

**Comment by afc163** [comment]
You should create issue by bug report template if you are reporting a bug.

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/49736#issuecomment-2210464526

https://stackblitz.com/edit/vitejs-vite-a6um1k?file=src%2Fcomponents%2FMyInput.tsx,src%2FApp.tsx
