### ISSUE TITLE
Use the Select component in “tags” mode without rendering the dropdown

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#50210]
### What problem does this feature solve?

I would like an input where I can type multiple words (tags) without rendering the dropdown, without search filters, etc. I just want to be able to write, press “enter,” and see the tag with the written word, and so on.
It could be a new dedicated component, or a property could be added to the ‘Select’ component to avoid rendering the dropdown, replicating the required functionality.

[discussion](https://github.com/ant-design/ant-design/discussions/50173#discussion-6997961)

### What does the proposed API look like?

New component or new Select prop:
| Property | Description | Type | Default |
| --- | --- | --- | --- |
| hideDropdown | Hide dropdown, it works only in "tags" mode | boolean | false |

**Comment by afc163** [comment]
`open={false}`: https://codepen.io/afc163-1472555193/pen/QWXpePy?editors=0010
