### ISSUE TITLE
Make Result Component "404, 403, 500" Status Illustrations customizable / replaceable

### ISSUE THREAD

**Issue by mropohl-parloa** [ant-design/ant-design#50224]
### What problem does this feature solve?

My team would love to be able to customize the illustration of the Result component when status is 404, 403, 500. Ideally, it should be possible to set a custom icon which would overwrite the illustration being there, but also be possible to change the illustration.

### What does the proposed API look like?

`<Result status="404" icon={<Icon />} />`

In this case, I would expect that the custom icon I defined overwrites the illustration that is used right now.

**Comment by MadCcc** [comment]
Just remove `status="404"` and custom icon would work.
