### ISSUE TITLE
not working icons on the site that show example code under elements

### ISSUE THREAD

**Issue by Mobsman** [ant-design/ant-design#50231]
### Reproduction link

[https://ant.design/components/calendar](https://ant.design/components/calendar)

### Steps to reproduce

https://ant.design/components/calendar  and another components on site

### What is expected?

sample code appears

### What is actually happening?

when clicking on the icons under the component nothing happens

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | react |
| System | windows 10 |
| Browser | chrome last version and another browsers |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/7b7525ad09b49aa562875ddac039cca3e4f7c70d
