### ISSUE TITLE
ChunkLoadError -Modal Component Page Becames Blank on reload

### ISSUE THREAD

**Issue by alex7842** [ant-design/ant-design#50232]
### Reproduction link

[https://antd-reproduce-5x-u1qvmt.stackblitz.io](https://antd-reproduce-5x-u1qvmt.stackblitz.io)

### Steps to reproduce

Check the UseEffest and handle the state properly

### What is expected?

To Prevent blank page when page loaded and solve chunkload error

### What is actually happening?

Modal Component Page Becames Blank on reload

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | Windows |
| Browser | Microsoft Edge |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/7b7525ad09b49aa562875ddac039cca3e4f7c70d
