### ISSUE TITLE
Table 组件开启固定列后，且首次渲染容器是被隐藏的，固定列显示不正常

### ISSUE THREAD

**Issue by Liuxl1996** [ant-design/ant-design#50247]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/table-cn/#components-table-demo-fixed-columns](https://4x-ant-design.antgroup.com/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce

1.Tabs标签页包含 Table 组件，且Table开启固定列
2.将Tab页签通过forceRender=true设置为强制渲染。
3.切换至对应页签查看表格

### What is expected?

显示正常

### What is actually happening?

列头出现空白元素

| Environment | Info |
| --- | --- |
| antd | 4.24.13 |
| React | 18.2.0 |
| System | win10 |
| Browser | 任意 |

**Comment by Wxh16144** [comment]
看你 Reproduction 链接和环境信息都是 4.x，但是 [v4 维护周期截止](https://ant.design/docs/blog/v4-ood-cn)。
