### ISSUE TITLE
Paragraph copyable 图标高度没对齐

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#50240]
### Reproduction link

[https://ant.design/components/typography-cn](https://ant.design/components/typography-cn)

### Steps to reproduce

查看 icon 位置，icon 位置偏上
![image](https://github.com/user-attachments/assets/1dc34e09-892c-4d6a-a440-6c9d9a574a8b)

### What is expected?

对其

### What is actually happening?

没对齐

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/49221/files#diff-ea701e5e0e91db732eccb7142c5f211b95bce0f34c97a44f112b7511b9e0bd30R22 

这里导致的。

**Comment by afc163** [comment]
其实 visual diff 也发现了：https://github.com/ant-design/ant-design/pull/49221#issuecomment-2146947605

**Comment by crazyair** [comment]
> 其实 visual diff 也发现了：[#49221 (comment)](https://github.com/ant-design/ant-design/pull/49221#issuecomment-2146947605)

diff 如果是这样3排铺开，图太小了，看不清，第三张更看不清，要对比，还是切换 1、2

可以改成

默认显示 1，然后鼠标点击显示 2，点击显示 1，来回切换
1 2 拼接一张图片，新建标签页打开，可以左右肉眼对比

**Comment by afc163** [comment]
不太好搞，回滚的话会导致 Safari 的问题 https://github.com/ant-design/ant-design/issues/49215 重现出现。
