### ISSUE TITLE
路由懒加载时，menu切换时，会闪缩

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design#50257]
### Reproduction link

[https://github.com/rookie-luochao/create-vite-react-app/blob/master/src/pages/main/MainLayoutComp.tsx#L26](https://github.com/rookie-luochao/create-vite-react-app/blob/master/src/pages/main/MainLayoutComp.tsx#L26)

### Steps to reproduce

点击切换任意menu item

### What is expected?

menu不闪烁

### What is actually happening?

menu闪烁

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.3.1 |
| System | mac os |
| Browser | chrome 126.0.6478.183 |

**Comment by wanpan11** [comment]
![image](https://github.com/user-attachments/assets/948d2260-8a83-4664-9168-7c74f2b1e954)


Outlet 是个懒加载组件，你没在他的上层使用 Suspense 导致 LazyImportComponent 的 Suspense 被触发了

**Comment by rookie-luochao** [comment]
> ![image](https://private-user-images.githubusercontent.com/38714194/356170568-948d2260-8a83-4664-9168-7c74f2b1e954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzYwOTMsIm5iZiI6MTcyMzE3NTc5MywicGF0aCI6Ii8zODcxNDE5NC8zNTYxNzA1NjgtOTQ4ZDIyNjAtOGE4My00NjY0LTkxNjgtN2M3NGYyYjFlOTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAzNTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkOTVkYjlmMjQ2ZjlhZTY1YzRiYjQ0ODlkZGNlNGUyMmQ2NmJhZjhkNzQyMmUwNmI2ZTRkYWVkNDQ1NTE3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jFiUJRLK4jd2dtfaDyP_f2Nj8H9JHYXKmJtHeYY3r7k)
> 
> Outlet 是个懒加载组件，你没在他的上层使用 Suspense 导致 LazyImportComponent 的 Suspense 被触发了，造成了重渲染 在 Outlet 外套一层就好了

我空了试试，谢谢大佬，我都没理解Suspense，正好看看
