### ISSUE TITLE
```Tree```: draggable and expandable icons are not vertically aligned

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#50255]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-5hykus?file=src%2FApp.tsx)

### Steps to reproduce

Render the `Tree` component and use the `titleRender` property to render any element that exceeds the normal height of the Tree row.
![Screenshot 2024-08-05 at 16 00 02](https://github.com/user-attachments/assets/bb0da062-1ca8-440e-82cf-1f3a291696d4)

### What is expected?

The draggable and expandable icons should be vertically aligned.

### What is actually happening?

Draggable and expandable icons are not vertically aligned.

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Switch & Checkbox is design to always pin at the block start. The hover background seems buggy:

<img width="395" alt="截屏2024-08-08 17 50 01" src="https://github.com/user-attachments/assets/00f4680b-a984-4a7b-bdbd-e5650ff92727">

Which should be:

<img width="379" alt="截屏2024-08-08 17 50 30" src="https://github.com/user-attachments/assets/86f97794-3acb-448f-8419-083d502b038c">
