### ISSUE TITLE
Popconfirm 内嵌入非 antd 组件时会报 findDOMNode is deprecated 的错

### ISSUE THREAD

**Issue by congjiujiu** [ant-design/ant-design#50267]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-ptclbf?file=button.tsx,demo.tsx,index.tsx)

### Steps to reproduce

- `Popconfirm` 组件内嵌入一些自定义组件
- `Tooltip` 组件内嵌入其他图标库的图标

### What is expected?

不会抛出 `findDOMNode is deprecated` 的 error

### What is actually happening?

看起来是 `rc-util/Dom/findDOMNode.js` 的问题，里面依然有调用 `ReactDOM.findDOMNode`

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.3.1 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/48055/files

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/43064#issuecomment-1595739073

**Comment by xiaomaodml** [comment]
在react19中，forwardRef已经被标注为废弃，后续该如何解决呢？
