### ISSUE TITLE
[qrcode/二维码] 中间的icon设置，能否丰富下api？例如设置圆角、边距等。

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50262]
### What problem does this feature solve?

- 风格统一，就像之前提出的 https://github.com/ant-design/ant-design/issues/50164 这个issue，不然风格感觉不统一。
- 还能避免如下图所示的，icon若是png透明的情况，从而生成的二维码中心视觉上的不统一。换句话说，从视觉上感觉icon的白边（留白）粗细不够平衡。

![image](https://github.com/user-attachments/assets/9c3146bf-9f31-461d-8aa2-2df1a3ab5657)

**如果通过api能做成类似下面的效果，感觉视觉上会更好些。**
![image](https://github.com/user-attachments/assets/d61d6aea-c004-4c5f-931b-35a49feb0ff7)

### 为什么不直接在这个图片上设计出这个效果

- **资源冗余**
    - 每次更改图标设计都需要生成新的图片文件，增加了图片资源的数量和管理成本。
    - 对于一个追求极致性能的前端开发者来说，每次额外的资源请求都会影响页面加载速度和性能（比如这个logo可能与网站主导航上的logo一样）。
- **设计和开发的沟通成本**
    - 每次调整图标样式都需要设计师重新设计并导出图片，增加了设计师和开发者之间的沟通和协调成本。
    - 多次往返的设计和审核流程会延长项目的开发周期。
- **一致性维护**
    - 不同图标可能由不同的设计师设计，可能会导致风格不统一的问题。
    - 在多个地方使用相同图标时，每个图标的更新都需要手动替换所有相关的图片，增加了维护复杂度。
- **灵活性不足**
    - 直接在图片上设计效果后，图标的样式就固定了，后期如果需要调整边距、阴影或边框样式等，就需要重新设计图片。
    - 在响应式设计中，不同设备和屏幕尺寸可能需要不同的图标样式，直接使用图片无法灵活调整。 
- **主题切换的复杂性**
    - 如果需要支持主题切换，每种主题下的图标都需要单独设计并生成图片，增加了设计和维护的复杂度。

### What does the proposed API look like?
下面的 API 只是简单的罗列，设计肯定不合理，仅作为参考之用。

| 参数 | 说明 | 类型 | 默认值 |
| --- | --- | --- | --- |
|iconRad|圆角弧度|number|0|
|iconMargin|图标外边距（方便调整图标外部间隙）|number|0|
|iconPadding|图标内边距（方便调整图标内部间隙，避免图标太靠近边框）|number|0|
|iconBorderWidth|图标边框线宽|number|0|
|iconBorderColor|图标边框色|string|-|
|iconBorderStyle|图标边框样式|string|-|
|iconBackgroundColor|图标底色，没指定的时候，默认是支持主题色切换（保证png图标，留白的问题）|string|-|
|iconShadow|外阴影|string|-|
|iconShadowInset|内阴影|string|-|

### 当然上面的这些设置，也应该支持全局设置
不支持全局的话，就变得像 https://github.com/ant-design/ant-design/issues/50182 中说的那样，会出现，每当使用一次，就需要重复设置一次。

**Comment by Wxh16144** [comment]
RFC 写的挺不错，学习了一下 [@rc-component/qrcode](https://github.com/react-component/qrcode) 中的实现。

如果是 canvas 的话，用的是 `ctx.drawImage` 实现，指路：https://github.com/react-component/qrcode/blob/0822265032c9daaa257495ee0206724890a15256/src/QRCodeCanvas.tsx#L114-L119

如果是 svg 的话用的是 svg images 标签实现，指路： https://github.com/react-component/qrcode/blob/0822265032c9daaa257495ee0206724890a15256/src/QRCodeSVG.tsx#L51-L65

如果需要添加样式貌似还挺复杂（最终等 core member 会议拿主意），个人感觉不如你说的直接在图片上设计效果来的简单

**Comment by kwooshung** [comment]
@Wxh16144 再说下我的拙见：

如果是一个图，或者网站中只有几个二维码，而且icon是固定的，确实不如直接设计图容易。可是就怕多呀，而且是动态的，有效期的那种。就麻烦咯。

如果仅是为了视觉效果，那么可能直接在上面再覆盖一层图片，直接用css搞定样式也行。可是如果二维码要实现用户可以保存或下载，那就又麻烦了。如果这么用css搞定了，那么这个组件存在icon的意义就很小了。感觉不是一个完整的功能。

**Comment by afc163** [comment]
这个感觉做不完，相当于在 canvas 里把 css 重新包装一份，确实不如直接业务直接在图片上做文章来的容易。

**Comment by kwooshung** [comment]
@zombieJ 经过你的案例展示，我觉得这样确实不错，功能加的太多，会臃肿，经过自己的处理，再这样传入，自定义空间比较大。
