### ISSUE TITLE
希望在md文档里写明当前版本对浏览器版本的的兼容

### ISSUE THREAD

**Issue by wangchaoHeart** [ant-design/ant-design#50265]
### What problem does this feature solve?

我当前项目使用的antd版本是5.17.0，但是我查阅了咱们官网资料，只标注了 Firefox Chrome Safari等支持最近 2 个版本的现代浏览器，但是我测试发现并不准确，怎么才能获取当前antd版本对浏览器版本的具体支持？比如5.17.0版本支持 chrome>=88， FireFox>= ……

### What does the proposed API look like?

能够罗列出当前版本对各个浏览器的具体兼容，而不是模糊的说持最近 2 个版本的现代浏览器

**Comment by zombieJ** [comment]
我能理解你的疑惑，但是很抱歉我们不会提供这个数据。

最近两个版本的意思就是当你遇到 BUG 时，我们会对在最近版本出现的问题进行维护。而对于过于古老的浏览器版本则不保证提供维护，从而保证社区成员有足够的精力。所以 antd 支持的版本可以理解为是超过约定版本的，但是并不会承诺具体维护到哪个古老的版本为止。

**Comment by wangchaoHeart** [comment]
非常感谢你的回答
