### ISSUE TITLE
Set focus to spin component when fullscreen?

### ISSUE THREAD

**Issue by anthonyhoegberg** [ant-design/ant-design#50263]
### Reproduction link

Not needed
### Steps to reproduce

Just add a spin component as full screen spin component and a text component to a page, then set spin component loading state to true and when the spin component is full screen, we can still edit text in the back if we selected the text component before the spin became full screen

### What is expected?

Spin component should have a focus property so we can request focus to it and block input etc

### What is actually happening?

Its not focusing the spin component letting us type in elements behind it etc

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18 |
| System | Windows 11 |
| Browser | Chrome |

**Comment by anthonyhoegberg** [comment]
https://github.com/anthonyhoegberg/antd-bug-reproduction

Here you go

If u start typing in the box after 3 seconds it will open the spinner for 3 seconds, while the spinner is open with fullscreen we can still continue typing inside the input box

**Comment by afc163** [comment]
You can try to control focus state mannually. https://stackblitz.com/edit/react-4pe3lx?file=demo.tsx

**Comment by anthonyhoegberg** [comment]
Thats not really a solution in a real world application
That will only work if u know what input is selected or etc, it would be better to focus the spinner so any background element at all does not get selected
