### ISSUE TITLE
change to @ant-design/fast-color created a failure in CRA build

### ISSUE THREAD

**Issue by eladonline** [ant-design/ant-design#50269]
this change created a failiure 
im using CRA - react-scripts V4
I think it might be related to babel versions collision 
![image](https://github.com/user-attachments/assets/e2843e8a-060d-4a15-afe0-9fd08fe54d75)

_Originally posted by @eladonline in https://github.com/ant-design/ant-design/issues/49846#issuecomment-2270592362_

**Comment by yoyo837** [comment]
Fixed by https://github.com/ant-design/fast-color/pull/50
