### ISSUE TITLE
为什么Select组件的input元素的opacity=0

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [ant-design/ant-design#50268]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/ddcdb2a6a2a0d2674b57a79cfe2cfac6d1835d22/components/select/__tests__/__snapshots__/index.test.tsx.snap#L24](https://github.com/ant-design/ant-design/blob/ddcdb2a6a2a0d2674b57a79cfe2cfac6d1835d22/components/select/__tests__/__snapshots__/index.test.tsx.snap#L24)

### Steps to reproduce

点击上方链接

### What is expected?

移除opacity，因为我自己测试了下，有没有opacity都不影响select的input展示，但我自己写单元测试，这个opacity=0会让断言认为下拉组件不存在

### What is actually happening?

单测认为Select组件不可见

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.2.0 |
| System | mac |
| Browser |  127.0.6533.89 |

---
Form内嵌套Select
```
 <Form.Item
              label="aaa"
              name="aaa"
            >
              <Select options={[]}  />
            </Form.Item>
```
然后渲染出来，发现下拉组件的input的opacity=0，下面这个id应该是antd自己动态添加的
```
<input type="search" id="aaa" style="opacity: 0;">
```

**Comment by zombieJ** [comment]
Select 的 Input 只有在 Select 开启 `showSearch` 并且聚焦的时候才需要展示，此外仅作为焦点元素使用。`opacity` 目的就是为了无障碍能识别而不让人看到。
你寻找下拉组件应该用 `ant-select`，而不是从内部元素去搜索。这在重构结构时是非常容易被 break 的。

**Comment by AttackXiaoJinJin** [comment]
@zombieJ 你意思是利用类名去搜索吗，也就是说`ant-select`/`ant-card`这些类名在迭代中是稳定的？
