### ISSUE TITLE
run tsc cause error after import antd

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#5027]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: macOS 10.12
- Browser and its version: 57.0.2979.0

#### What did you do? Please provide steps to re-produce your problem.

1. import antd in my typescript project.
2. run `tsc`.

#### What do you expected?

can compile successfully.

#### What happen?

cause error.
![antd-error](https://cloud.githubusercontent.com/assets/16483610/23252128/9e512276-f9ea-11e6-93c9-13402814224f.png)

**Comment by benjycui** [comment]
Should be fixed in https://github.com/ant-design/ant-design/commit/8283a36b2e963edc1a7fc8659319f6be1cb33f99

And duplicated: https://github.com/ant-design/ant-design/issues/4935
