### ISSUE TITLE
官网table-demo-edit用例在Stackblitz 中打开报错

### ISSUE THREAD

**Issue by Dmaziyo** [ant-design/ant-design#50270]
### Reproduction link

[https://ant.design/components/table-cn#table-demo-edit-cell](https://ant.design/components/table-cn#table-demo-edit-cell)

### Steps to reproduce

点击在 Stackblitz 中打开

### What is expected?

样例正常运行

### What is actually happening?

样例报错
![image](https://github.com/user-attachments/assets/d63a45a9-aab2-4234-9fd5-a84aae05856a)
我在本地调试，好像是`CodePreviewer.tsx`里面没有处理```
![image](https://github.com/user-attachments/assets/fbf27c7f-179a-40a1-862e-0511921fbc04)

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.3.1 |
| System | win10 |
| Browser | chrome |

**Comment by Dmaziyo** [comment]
还有就是想问一下，为什么我本地无论怎么改`edit-cell.md`，页面的内容都没有发生变化
![image](https://github.com/user-attachments/assets/891c4f00-9959-464d-a4c6-d60b447d19a5)
![image](https://github.com/user-attachments/assets/c06ead08-aa88-4ba0-ad46-c1bf806692e2)

**Comment by zombieJ** [comment]
感觉这个 css 可以去掉了。改动没用是需要改完重启才行，因为 markdown 写的样式是不会动态更新的。
