### ISSUE TITLE
According to DatePicker's Turkish locale, it should start from Monday. But it starts from Tuesday

### ISSUE THREAD

**Issue by Sekunev** [ant-design/ant-design#50274]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-rndfp4?file=demo.tsx)

### Steps to reproduce

According to DatePicker's Turkish locale, it should start from Monday. But it starts from Tuesday

### What is expected?

According to DatePicker's Turkish locale, it should start from Monday. But it starts from Tuesday

### What is actually happening?

According to DatePicker's Turkish locale, it should start from Monday. But it starts from Tuesday

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.3.1 |
| System | 5.4.0 |
| Browser | Google Chrome 127.0.6533.89 |

---
According to DatePicker's Turkish locale, it should start from Monday. But it starts from Tuesday

**Comment by afc163** [comment]
https://stackblitz.com/edit/antd-reproduce-5x-7tpitw?file=demo.tsx

```js
<DatePicker locale={tr_TR.DatePicker} placeholder={'Tarih Seçiniz'} />
```

**Comment by Sekunev** [comment]
Thanks friends
