### ISSUE TITLE
npm run dist 报错

### ISSUE THREAD

**Issue by lei40251** [ant-design/ant-design#5028]
请问
clone下来后执行
npm install
然后
npm run dist
然后报错
![qq 20170223172653](https://cloud.githubusercontent.com/assets/648155/23252916/7fbfae9c-f9ed-11e6-9b08-f9443f9c623c.png)

**Comment by lei40251** [comment]
nodejs 是 7

**Comment by benjycui** [comment]
It works fine in Mac.

Could you try to find the problem and fix it? Because we have no Windows..

**Comment by benjycui** [comment]
Hope that other Windows' users can try this, too.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4508

**Comment by lei40251** [comment]
thanks
