### ISSUE TITLE
<Input> 传入 onClear 参数会导致 react-dom 警告

### ISSUE THREAD

**Issue by gwy15** [ant-design/ant-design#50289]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-yqehkv?file=demo.tsx)

### Steps to reproduce

打开 https://stackblitz.com/edit/react-yqehkv?file=demo.tsx，控制台会报错

### What is expected?

控制台没有报错

### What is actually happening?

控制台警告
```
Warning: Unknown event handler property `onClear`. It will be ignored.
at input
at eval (https://react-yqehkv.stackblitz.io/turbo_modules/rc-input@1.6.2/lib/BaseInput.js:20:23)
at eval (https://react-yqehkv.stackblitz.io/turbo_modules/rc-input@1.6.2/lib/Input.js:26:28)
at eval (https://react-yqehkv.stackblitz.io/turbo_modules/antd@5.20.0/lib/input/Input.js:63:18)
at App
```

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.3 |
| System | macOS Sonoma 14.4 |
| Browser | 126 |

---
由 https://github.com/ant-design/ant-design/pull/49905 引入

**Comment by spwgi** [comment]
Will using onClear in the input component of React version 18.2.0 trigger an alarm? version of React upgrade do I need to talk ?
