### ISSUE TITLE
preserve为false的FormItem销毁时会触发所有添加了shouldUpdate表单rerender

### ISSUE THREAD

**Issue by JackWang032** [ant-design/ant-design#50283]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-gqg4vf?file=src%2FApp.tsx)

### Steps to reproduce

1. 在B中随便输入点内容
2. 在A中切换隐藏B
3. 打开控制台，添加了shouldUpdate（永远返回false）的C表单render了一遍

### What is expected?

C表单不进行render

### What is actually happening?

C表单render了一遍

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18 |
| System | mac |
| Browser | Chrome v116.0.5845.110 |

---
可能会引起性能问题
定位源码是remove时判断的是`shouldUpdate`而不是`shouldUpdate && requireUpdate(shouldUpdate, xxx, xxx)`, 不知道是否是为了解决注释中提到的依赖传递的问题而这样写的。
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/98c0c63a-ebb9-41bd-b1ce-57c037c379fa">

**Comment by crazyair** [comment]
为什么 B 要有内容呢？

**Comment by JackWang032** [comment]
> 为什么 B 要有内容，才会触发 C render 呢？

注销effect里会判断当前值是否与inititalValue值相等才会触发remove类型的storeChange
<img width="922" alt="image" src="https://github.com/user-attachments/assets/6b281be5-cba8-413d-9c8d-4ad3c0a41968">

**Comment by zombieJ** [comment]
是的，shouldUpdate 会重新跑一次防止 preserve 的负作用。我感觉也是可以跑一次 shouldUpdate 来看看要不要 rerender。
