### ISSUE TITLE
DatePicker.RangePicker cannot select end time in shadow dom

### ISSUE THREAD

**Issue by shiyangzhaoa** [ant-design/ant-design#50284]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-picker-qrgr82?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzj9xla300063b6ot2ek1jnb%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzj9xla300023b6ogoh97mum%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzj9xla300033b6okljkm973%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzj9xla300053b6ou384x8kz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzj9xla300023b6ogoh97mum%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzj9xla200013b6og6w5fk7q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clzj9xla300023b6ogoh97mum%2522%252C%2522activeTabId%2522%253A%2522clzj9xla200013b6og6w5fk7q%2522%257D%252C%2522clzj9xla300053b6ou384x8kz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzj9xla300043b6ohphs8f31%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzj9xla300053b6ou384x8kz%2522%252C%2522activeTabId%2522%253A%2522clzj9xla300043b6ohphs8f31%2522%257D%252C%2522clzj9xla300033b6okljkm973%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzj9xla300033b6okljkm973%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Click End Date to select a date, and Start Date will always be focused

### What is expected?

Click End Date, and select End Date instead of Start Date

### What is actually happening?

https://github.com/react-component/picker/blob/8ea9dbd630df2f7f08561fe30db3422dbabdbc9c/src/PickerInput/RangePicker.tsx#L431

因为 rc-picker 组件内部直接取 document 的 activeElement，导致了这个问题，这里是否应该用配置的 container 而不是 document

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by shiyangzhaoa** [comment]
通过 pnpm patch 处理了，但我感觉 rc 组件不止这一个有这种问题
```ts
if (!selectorRef.current.nativeElement.contains(event.target.getRootNode().activeElement)) {
// ...
```

**Comment by afc163** [comment]
@shiyangzhaoa 可以来个 PR~

**Comment by shiyangzhaoa** [comment]
@afc163  我尝试修了下，然后补了用例，但用例始终跑不过，看了下测试环境的 shadowRoot 的 activeElement 始终是 null
```
it('the end date selector can be selected in shadow dom', () => {
  const shadowHost = document.createElement('div');
  const shadowRoot = document.createElement('div');
  shadowHost.attachShadow({ mode: 'open' }).appendChild(shadowRoot);

  const { container } = render(<DayRangePicker />, { container: shadowRoot });

  openPicker(container, 1);

  expect(container.querySelectorAll('.rc-picker-input')[1]).toHaveClass('rc-picker-input-active');
})
```
以为是 jsdom 的问题，又尝试:
```js
const { JSDOM } = require("jsdom");
const { window } = new JSDOM();
const { document } = window;

const input = document.createElement("input");
const shadowHost = document.createElement("div");
const shadowRoot = document.createElement("div");
shadowHost.attachShadow({ mode: "open" }).appendChild(shadowRoot);
shadowRoot.appendChild(input);
document.body.appendChild(shadowHost);

input.focus();

console.log("activeElement---", shadowHost.shadowRoot, shadowHost.shadowRoot.activeElement);
```

<img width="389" alt="image" src="https://github.com/user-attachments/assets/d255efb5-53ac-414f-bf72-7ca614d2e5e9">

也是正常的，忙活了半天，没有查出什么有用的信息...

放弃，这个 issue 我先关了 😣

**Comment by afc163** [comment]
参考一下 https://github.com/react-component/trigger/blob/e6ac87a198fa5c15d3f75c4cea8d58fe91a90af9/tests/shadow.test.tsx#L44 ？
