### ISSUE TITLE
Progress的属性strokeColor添加之后type为"circle"的圆角消失

### ISSUE THREAD

**Issue by xblackh** [ant-design/ant-design#50285]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-dugn2h?file=demo.tsx)

### Steps to reproduce

添加 strokeColor={{
              "0%": "#FFD700",
              "100%": "#FF8C00",
            }}

### What is expected?

圆形进度条的两端是圆角

### What is actually happening?

borderRadius为0

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | ^18.2.0 |
| System | window11 |
| Browser | 127.0.6533.89 |

**Comment by DDDDD12138** [comment]
渐变色封装，`circle` 与 `dashboard` 设置渐变时 `strokeLinecap` 会被忽略。
[ant-design: 自定义进度条渐变色](https://ant-design.antgroup.com/components/progress-cn#components-progress-demo-gradient-line)

**Comment by zombieJ** [comment]
见 @DDDDD12138 所述，文档中已经说明渐变色边缘设定会失效。

**Comment by xblackh** [comment]
没有办法解决这个问题么？
