### ISSUE TITLE
Oh no, the site of ant design index.js size is 6MB

### ISSUE THREAD

**Issue by monkindey** [ant-design/ant-design#5029]
> Sorry for reporting here, I have not found the site of ant design repo

#### Environment(required)

My bandwidth ~ 10MB

#### What did you do? Please provide steps to re-produce your problem.

I try to access the site and search some component, and when I enter the site, I waited almost 1 min.

![image](https://cloud.githubusercontent.com/assets/6913898/23261246/5a23eab8-fa10-11e6-8dd1-86b5176ea3c2.png)

and eventually download the index.js, I found out it have 6MB(which is crazy)

#### What do you expected?

Toooo big

#### What happen?

Because of download index.js  for a long time and the first-paint time is so long.

**Comment by afc163** [comment]
Actually, index.js only 1MB thanks to gzip, you don't have to download 6MB. And I strongly suggest that you should get a VPN against china GFW.

```
🎯   ~  curl -H "Accept-Encoding: gzip" -I https://ant.design/index.js | grep Content-Length
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 1074k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Content-Length: 1099930
```

<img width="706" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23262210/eb06c86c-fa14-11e6-8752-1a95ea895416.png">

**Comment by monkindey** [comment]
Thanks for your answer, My bad. :)
