### ISSUE TITLE
Popover 的弹出层不会随 DOM 的变化而动态推移

### ISSUE THREAD

**Issue by dhzhme** [ant-design/ant-design#50296]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-nnexue?file=package.json)

### Steps to reproduce

1、进入 stackblitz
2、focus input 使 popover 出现
3、不断点击 add item 的按钮

### What is expected?

希望在第二步出现的 popover 能够随着 input 的向下推移而动态更新下移

### What is actually happening?

popover 会停留在首次出现的位置遮挡住一部分 dom

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 17 |
| System | MacOS 14.5 |
| Browser | Version 127.0.6533.89 (Official Build) (arm64) |

**Comment by afc163** [comment]
```css
#create-inc-modal-unique {
  position: relative;
}
```

**Comment by crazyair** [comment]
为啥不内置，也是因为 children 可能不是元素吗？
