### ISSUE TITLE
input 和 select 组件  token 应用失败

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#50299]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-8a41yu-srukna?file=demo.tsx)

### Steps to reproduce

修改 input 和 select 组件的 component token 后，修改后的 token 没有应用成功
![image](https://github.com/user-attachments/assets/c135e574-4f5f-4071-b2b6-760f84e96c8b)

### What is expected?

no response

### What is actually happening?

https://stackblitz.com/edit/react-8a41yu-srukna?file=demo.tsx

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.0.0 |
| System | windows |
| Browser | edge 114.0.1823.37 |

**Comment by thinkasany** [comment]
你改的好像是全局token，似乎全局token应该是这样子用
https://ant.design/docs/react/customize-theme-cn#%E4%BF%AE%E6%94%B9%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8F
![image](https://github.com/user-attachments/assets/28211df1-eddc-403d-962c-b34886ec4d8f)


![image](https://github.com/user-attachments/assets/e9ed15d7-b985-45b8-84c9-5bc8b2b548cf)

**Comment by guaijie** [comment]
> 你改的好像是全局token，似乎全局token应该是这样子用 https://ant.design/docs/react/customize-theme-cn#%E4%BF%AE%E6%94%B9%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8F ![image](https://private-user-images.githubusercontent.com/117748716/356064598-28211df1-eddc-403d-962c-b34886ec4d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODYxNDUsIm5iZiI6MTcyMzA4NTg0NSwicGF0aCI6Ii8xMTc3NDg3MTYvMzU2MDY0NTk4LTI4MjExZGYxLWVkZGMtNDAzZC05NjJjLWIzNDg4NmVjNGQ4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMjU3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWU3MjRiYTI4OTQ1MGVhOWE4Mzc4M2EwZDk1MzkyYjNjYzRkNzdjZTIzMzlmMDYwZjc4MDJiNDUzMWZlMGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NgQDOYapXCo3YVJ7Tk0FKxpLVEe_RP0OxIGXgnrDo2U)
> 
> ![image](https://private-user-images.githubusercontent.com/117748716/356064391-e9ed15d7-b985-45b8-84c9-5bc8b2b548cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODYxNDUsIm5iZiI6MTcyMzA4NTg0NSwicGF0aCI6Ii8xMTc3NDg3MTYvMzU2MDY0MzkxLWU5ZWQxNWQ3LWI5ODUtNDViOC04NGM5LTViYzhiMmI1NDhjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMjU3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmRhMTI5YmNjZjNmZWFlZTEwMzhmNmU4MzI3ODkyMDU4YWE4OTA0YjRiNGM1Y2Q0YTFkNDIxYzY4ZDEwMDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P-zghYrPnQsLz0wCwEI7gc85vepFTm6fPoOdUFSC0HE)

这是官方给出的回答
![image](https://github.com/user-attachments/assets/9f5b7b6d-cf19-4efa-8b21-5356ce7b4bfb)

**Comment by zombieJ** [comment]
因为错误提示文字是 Form 给的，不是 Select 和 Input 组件给的。反过来想，如果使用原生的 input 错误提示也是可以渲染的咧~

https://stackblitz.com/edit/react-8a41yu-hbbmzw?file=demo.tsx
