### ISSUE TITLE
Tour组件样式无法通过:global或styled-components修改样式

### ISSUE THREAD

**Issue by 3764446961** [ant-design/ant-design#50295]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ivzfgk?file=demo.tsx)

### What is expected?

字体颜色改变

### What is actually happening?

 字体颜色未改变

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.0 |
| System | mac |
| Browser | chrome |

**Comment by 3764446961** [comment]
还有是否支持修改Tour组件高亮区域的圆角呢

**Comment by wanpan11** [comment]
![image](https://github.com/user-attachments/assets/f4d70052-e0f2-4b7a-9e8e-b2f5870a16ff)

可以使用 rootClassName 直接写在Tour 节点上就行了

**Comment by wanpan11** [comment]
> 还有是否支持修改Tour组件高亮区域的圆角呢

- ref https://github.com/ant-design/ant-design/issues/50164

**Comment by 3764446961** [comment]
> ![image](https://private-user-images.githubusercontent.com/38714194/356055194-f4d70052-e0f2-4b7a-9e8e-b2f5870a16ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODY2NTUsIm5iZiI6MTcyMzA4NjM1NSwicGF0aCI6Ii8zODcxNDE5NC8zNTYwNTUxOTQtZjRkNzAwNTItZTBmMi00YjdhLTllOGUtYjJmNTg3MGExNmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzMDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZjE4YzFmZTMzNDVkNDAxOTg5NzhlMTBkZjM2Yzk5ZDVlYTk2YWNmN2Q5ZGQ2OGZlZWI2MGNkOWM2NWVlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pRriStj03kvAbP91FWUSPPSqSzFVoGb2JAnakC6gcaU)
> 
> 可以使用 rootClassName 直接写在Tour 节点上就行了

还是不生效呢，是我加的不对吗😳
https://stackblitz.com/edit/react-ivzfgk-r78hol?file=demo.tsx
<img width="951" alt="image" src="https://github.com/user-attachments/assets/db0706fa-7496-42bb-a424-f781161fc5a3">

**Comment by wanpan11** [comment]
https://stackblitz.com/edit/react-ivzfgk-zgy8ka?file=demo.tsx

![image](https://github.com/user-attachments/assets/1635e845-b6b9-4103-8baf-6095c1754ff6)

**Comment by zombieJ** [comment]
https://stackblitz.com/edit/react-ivzfgk-ek4scy?file=demo.tsx

**Comment by afc163** [comment]
@zombieJ Tour 不打算支持 className 么？

**Comment by zombieJ** [comment]
> @zombieJ Tour 不打算支持 className 么？

浮动元素标准是用 `rootClassName` or `classNames` 语义化方案。否则和其他带浮层组件定义会有出入。

**Comment by afc163** [comment]
Modal/Drawer 也支持 className 的。

**Comment by zombieJ** [comment]
> Modal/Drawer 也支持 className 的。

就是上面提到的，className 对于浮层组件没有语义化的问题。在 Drawer 和 Modal 放的位置都不太一样：

#### Modal 在外容器上

<img width="534" alt="截屏2024-08-08 17 57 14" src="https://github.com/user-attachments/assets/e0c3f389-db58-4c6b-92e7-3b70b63c57f6">

#### Drawer 在内容器上

<img width="1028" alt="截屏2024-08-08 17 58 09" src="https://github.com/user-attachments/assets/8433dd4e-16e8-45a6-b8b9-2972db88440e">

浮动元素没有统一标准应该放那里，可以认为是最外层 wrapper、可以是弹出层容器、可以是弹出元素。每种都在不同的场景看都是合理的。

**Comment by afc163** [comment]
Modal 放的位置是对的，这个和 Tour 的区域应该是一致的。

放的位置是一回事，支不支持是另一回事吧，不支持 className 就会导致和 styled-components 配合使用时多一层解释成本。

**Comment by afc163** [comment]
Modal 的 className 在对话框弹层区域，rootClassName 在外框。

<img width="1781" alt="图片" src="https://github.com/user-attachments/assets/4dc3b17e-fe79-4b2f-b6b0-ad0b509bc060">

Tour 如果要支持 className，也应该在弹层区域。

<img width="1064" alt="图片" src="https://github.com/user-attachments/assets/6eb7746c-8ec4-460b-afa3-164fbfb25e45">

不过 Tour 由于 mask 和 ant-tour 不在同一个 wrapper 内，所以 rootClassName 也放到了 .ant-tour 这一层。

**Comment by afc163** [comment]
因此我的结论是给 Tour 增加 className 属性，赋值到 .ant-tour 这一级上。rootClassName 已经存在了，也没办法删，保持原样。
