### ISSUE TITLE
ConfigProvider 支持自定义 Popconfirm 的 className 和 style

### ISSUE THREAD

**Issue by projectcss** [ant-design/ant-design#50303]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/config-provider/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/config-provider/index.tsx)

### Steps to reproduce

https://github.com/ant-design/ant-design/blob/master/components/config-provider/index.tsx

### What is expected?

ConfigProvider支持对Popconfirm进行样式覆盖

### What is actually happening?

ConfigProvider不支持对Popconfirm进行样式覆盖

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.3.1 |
| System | mac |
| Browser | 120 |

**Comment by zombieJ** [comment]
Popconfirm 是封装的 Popover，感觉文档要提一下。

**Comment by zombieJ** [comment]
> 样式覆盖用的是 `theme.components.{ComponentName}` 方式。你直接搜源码肯定没有啊

+1  https://stackblitz.com/edit/react-mnpgak?file=demo.tsx

**Comment by projectcss** [comment]
> 样式覆盖用的是 `theme.components.{ComponentName}` 方式。你直接搜源码肯定没有啊

用theme是token覆盖，我是说用classname进行样式覆盖

**Comment by projectcss** [comment]
> 用theme是token覆盖，我是说用classname进行样式覆盖

用theme是token覆盖，我是说用classname进行样式覆盖

**Comment by Wxh16144** [comment]
> > 用theme是token覆盖，我是说用classname进行样式覆盖
> 
> 用theme是token覆盖，我是说用classname进行样式覆盖

你可以整理一下你的提问，很难 get 到，我猜你说的应该是通用属性追加 classname 操作吧？

**Comment by projectcss** [comment]
> > > 用theme是token覆盖，我是说用classname进行样式覆盖
> > 
> > 
> > 用theme是token覆盖，我是说用classname进行样式覆盖
> 
> 你可以整理一下你的提问，很难 get 到，我猜你说的应该是通用属性追加 classname 操作吧？

是的

**Comment by Wxh16144** [comment]
> 是的

貌似没有这个 feature， 得提交一个 PR，或者给 core member 评审一下。
