### ISSUE TITLE
Table的sticky属性无法和Watermark组件一同使用

### ISSUE THREAD

**Issue by kkk360** [ant-design/ant-design#50306]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-clgjsw?file=demo.tsx)

### Steps to reproduce

添加Watermark组件后,粘性header失效

### What is expected?

正常粘性滚动

### What is actually happening?

失效

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 17.0.2 |
| System | macos |
| Browser |  127.0.6533.90 |

---
5.19.3版本中是正常的, 最新版本不可用

**Comment by zombieJ** [comment]
WaterMark 之前有个 bug 会允许用户通过设置 height 进行穿透，所以改成了 overflow，可以通过 自定义样式去除： https://stackblitz.com/edit/react-clgjsw-4jwhf7?file=demo.tsx

感觉文档里要加一下说明。
