### ISSUE TITLE
栅格布局Row指定height高度时，Col换行展示垂直高度为什么是自动平分的？

### ISSUE THREAD

**Issue by andyforever** [ant-design/ant-design#50310]
### Reproduction link

[https://hitu.antgroup-inc.cn/codeblocks/e82567c0](https://hitu.antgroup-inc.cn/codeblocks/e82567c0)

### Steps to reproduce

查看海兔链接即可

### What is expected?

期望两个Col元素垂直间距为0

### What is actually happening?

两个Col元素在Row内垂直是平均布局的

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
你给的链接外网打不开。

**Comment by andyforever** [comment]
换了个外网链接 https://codepen.io/aqcejojs-the-bashful/pen/MWMEZNM?editors=001
