### ISSUE TITLE
Turn off internal date disabling in RangePicker 

### ISSUE THREAD

**Issue by Diman142** [ant-design/ant-design#50318]
### What problem does this feature solve?

Hi can you help me. 
I can`t find the possibility to turn off internal date disabling for the RangePicker component.
For example if we chose start date the dates that less than start date are disabled.
For example I want to implement RangePicker without any date disable and handle the case when start date more than end date. 
How can I turn off the internal date disable logic?
I tryed to do
 <RangePicker
  disabledDate={() => false}
/>
But it is not working

### What does the proposed API look like?

  <RangePicker 
     internaldatesDisabling={false}
/>

**Comment by Diman142** [comment]
Hello, I prepared demo:
https://codesandbox.io/p/sandbox/range-picker-ant-design-demo-forked-l2fvld?file=%2Findex.js

I meant the next disabling
![image](https://github.com/user-attachments/assets/04a157b1-04ad-4851-a219-c6c023fd95e1)

**Comment by afc163** [comment]
Try antd 5.x which won't be a problem: https://ant.design/components/date-picker#date-picker-demo-range-picker

**Comment by Diman142** [comment]
Thanks for your advice. 
But is it really do on preveous version cause I have some legacy code when we use  "antd": "^4.24.10". and I have more than 300 errors after bump on antd 5.x?
