### ISSUE TITLE
Textbox autosize prop bug

### ISSUE THREAD

**Issue by ondery** [ant-design/ant-design#50323]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-j8bvmq?file=demo.tsx)

### Steps to reproduce

use in a react component this   <Input.TextArea autoSize={{ minRows: 4, maxRows: 6 }} />

### What is expected?

only one textbox

### What is actually happening?

when use prop "autoSize" it adds a new second hidden textarea such as: 

<textarea tab-index="-1" aria-hidden="true" style="letter-spacing:normal;line-height:22px;pa......."></textarea>

(but without name or id; therefore chrome indicate an issue also that exist a form element without name or id)

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | React |
| System | Win11 64 Bit |
| Browser | Chrome 127.0.6533.100 (64 bit) version |

**Comment by zombieJ** [comment]
This hidden element is used for measuring row count. Seems it's Chrome bug since `aria-hidden` should not take into count.
