### ISSUE TITLE
4.x.stable版本文档站加载demo出错

### ISSUE THREAD

**Issue by yanhongli** [ant-design/ant-design#50325]
### Reproduction link

[https://github.com/ant-design/ant-design/tree/4.x-stable](https://github.com/ant-design/ant-design/tree/4.x-stable)

### Steps to reproduce

1.安装antd项目中的依赖
2.启动文档站项目 npm run start
3.在浏览器访问文档站，预览组件的demo示例

### What is expected?

demo可以正常预览

### What is actually happening?

所有组件的demo示例均报如下错误：
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `Demo`.

    at ErrorBoundary (http://localhost:8001/index.js:2870:5)
    at section
    at section
    at Demo (http://localhost:8001/index.js:349553:5)
    at injectIntl(Demo)
    at div
    at http://localhost:8001/index.js:13047:75
    at div
    at http://localhost:8001/index.js:13263:34
    at article
    at ComponentDoc (http://localhost:8001/index.js:348825:5)
    at injectIntl(ComponentDoc)
    at section
    at div
    at http://localhost:8001/index.js:13047:75
    at div
    at http://localhost:8001/index.js:13263:34
    at div
    at MainContent (http://localhost:8001/index.js:350159:5)
    at injectIntl(MainContent)

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | react |
| System | macOS sonoma 14.5 |
| Browser | edge |

**Comment by zombieJ** [comment]
推测是一些依赖导致的编译问题。因为 4.0 已经过了维护，社区不会提供相关的支持哈~

**Comment by afc163** [comment]
得修一下吧，偶尔我们自己也需要更新文档。

**Comment by afc163** [comment]
<img width="1781" alt="图片" src="https://github.com/user-attachments/assets/7c2430a8-344a-4657-8e53-cf4245ae576b">

我没有遇到问题。
