### ISSUE TITLE
Antd nested form inside custom input not showing error correctly

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design#50335]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-nbpszj?file=demo.tsx)

### Steps to reproduce

Create a form, and create a custom input that has a form inside

### What is expected?

error to show on correct place inside form below input to add item

### What is actually happening?

error showing on parent form item outside select dropdown

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18 |
| System | Windows 10 |
| Browser | Version 127.0.6533.89 (Official Build) (64-bit) |

---
Later i found out that the weird error happends when noStyle prop is provided input gets error border but error starts showing on parent input

  

[Demo.txt](https://github.com/user-attachments/files/16559118/Demo.txt)

**Comment by zombieJ** [comment]
`noStyle` is by design to raise the error message to parent FormItem whose not set `noStyle`. If you want to show up but in Form. Just wrap another FormItem instead:

https://stackblitz.com/edit/antd-reproduce-5x-qrunr6?file=demo.tsx
