### ISSUE TITLE
Can not typecheck project without setting SkipLibCheck to false

### ISSUE THREAD

**Issue by HatemMn** [ant-design/ant-design#50334]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-yfbj4q?file=package.json)

### Steps to reproduce

```
// download the repository locally to be able to use the console
npm install
cd src
tsc --noEmit
```

### What is expected?

No errors

### What is actually happening?

" 7 errors in the same file, starting at: ../node_modules/antd/es/theme/util/genStyleUtils.d.ts:6 "

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18 |
| System | Ubuntu 22.04 |
| Browser | Chromium latest |

---
I tried to fix this but it is impossible to compile any project with antd if I do not disable checking all of the .d.ts files. Can this be fixed to keep the integrity of projects ?

**Comment by zombieJ** [comment]
Your reproduce seems not follow your reproduce step.

**Comment by HatemMn** [comment]
Dear @zombieJ ,
I downloaded the reproduction repo that I cited earlier and tried it, I had the expected result (ie : an error )
Here is a screenshot : 
![image](https://github.com/user-attachments/assets/19380cd5-6059-4ef7-8ded-fac80357ee74)

If you can't reproduce it, please tell me what is the error you get ? Have you tried to download it ? Thanks in advance

**Comment by leoswing** [comment]
> Dear @zombieJ , I downloaded the reproduction repo that I cited earlier and tried it, I had the expected result (ie : an error ) Here is a screenshot : ![image](https://private-user-images.githubusercontent.com/19950216/356985211-19380cd5-6059-4ef7-8ded-fac80357ee74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDQxODUsIm5iZiI6MTcyNTM0Mzg4NSwicGF0aCI6Ii8xOTk1MDIxNi8zNTY5ODUyMTEtMTkzODBjZDUtNjA1OS00ZWY3LThkZWQtZmFjODAzNTdlZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA2MTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzExY2U2NDU4ODY0ZTZhN2EyZDM3NWEwMDkwMjBmZTVlZTI0NWUxODE5ZjMzZTY4N2M5Nzk4MDljMDM3OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LVm6RS47oiiTS1YwSMRr56y0kuAUnX3vcE3MCdLOy3c)
> 
> If you can't reproduce it, please tell me what is the error you get ? Have you tried to download it ? Thanks in advance

The same issue happened, anyone could help to solve this?

**Comment by leoswing** [comment]
<img width="1798" alt="image" src="https://github.com/user-attachments/assets/4e3873f6-d755-4d20-9392-46922036a141">
@zombieJ Could you help to solve this typescript issue ?

**Comment by tommy26tan** [comment]
bro, i got same issue, yarn build error
