### ISSUE TITLE
Antd virtual table becomes unresponsive when dataset and scroll Y is large

### ISSUE THREAD

**Issue by AsuraKev** [ant-design/ant-design#50343]
### Reproduction link

[https://codepen.io/Kevin-Wang-the-selector/pen/eYwGmrw?editors=0010](https://codepen.io/Kevin-Wang-the-selector/pen/eYwGmrw?editors=0010)

### Steps to reproduce

The example uses the one from the documentation, by increasing the data to 10000 rows and set a big number for scrollY so that it displays a lot of rows. 

Checkbox selection becomes realllly slow. The performance issue experienced from normal Table is replicated in virtual table 

### What is expected?

Table should be responsive at a minimum amount of dataset

### What is actually happening?

Table selection and other table operations freeze due to performance issue

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.2 |
| System | Windows |
| Browser | Chrome |

**Comment by MadCcc** [comment]
`scrollY` is too high, which makes too many rows in screen. Try to reduce the height to get better performance.
