### ISSUE TITLE
[WWW]: Crash when opening Typography docs

### ISSUE THREAD

**Issue by wishyoudie** [ant-design/ant-design#50368]
### Reproduction link

[https://ant.design/components/typography](https://ant.design/components/typography)

### Steps to reproduce

Open Typography docs in official WWW, wait for about 1 sec.

Get this error:
Uncaught ChunkLoadError
    at e_.chunkEnsures.jsonp (runtime_entry.js:109:25)
    at runtime_entry.js:82:42
    at Array.reduce (<anonymous>)

### What is expected?

Definitely not a crash :)

### What is actually happening?

A crash

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | does not matter |
| System | macOS |
| Browser | Chrome |

---
See thrown error in Step to reproduce section.

**Comment by coding-ice** [comment]
If you can, use the mirror for a while

**Comment by bzhn** [comment]
I have the same problem... Opening documentation for the component (https://ant.design/components/*) ends up with a blank page. I have tried in Chrome and Firefox.

**Comment by coding-ice** [comment]
The site is being repaired, please use the mirror site first.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/5533b037a78be8144c7518e4d2527f48b9b35118
