### ISSUE TITLE
文档网页报错

### ISSUE THREAD

**Issue by Brucia323** [ant-design/ant-design#50369]
### Reproduction link

[https://ant.design/components/descriptions-cn](https://ant.design/components/descriptions-cn)

### Steps to reproduce

划到底

### What is expected?

正常使用

### What is actually happening?

白屏

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.3.1 |
| System | 14.6.1 (23G93) |
| Browser | Microsoft Edge 版本 127.0.2651.98 (正式版本) (x86_64) |

<img width="1552" alt="截屏2024-08-12 上午10 32 42" src="https://github.com/user-attachments/assets/358fd6d8-6a20-4620-8909-bf080abbf3bf">

**Comment by coding-ice** [comment]
先临时用镜像代替下~ https://ant-design.antgroup.com/

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/5533b037a78be8144c7518e4d2527f48b9b35118
