### ISSUE TITLE
Tale组件渲染2000条数据内存（不分页）内超1G以上

### ISSUE THREAD

**Issue by whaleluo** [ant-design/ant-design#50360]
### What problem does this feature solve?

Table组件渲染内存优化

### What does the proposed API look like?

希望可以分析下原因， 原生页面table组件2000条数据大概60mb，不知道为啥ant table会占用这么高

最小demo实现   
https://stackblitz.com/edit/react-lplqxp-qrhnnb?file=demo.tsx

可以直接打开控制台，查看内存

**Comment by zombieJ** [comment]
antd 使用的 babel 编译产物会对 es 进行转译来做尽可能的浏览器兼容，由此会导致性能和内存的额外开销。虽然 antd 官方说是最近两个浏览器版本，但是实际上支持的版本更长久。

在下个大版本我们会移除旧版浏览器兼容所需的转译。
