### ISSUE TITLE
I can not approaching Components pages

### ISSUE THREAD

**Issue by chjh6107** [ant-design/ant-design#50370]
### Reproduction link

[https://ant.design/components/overview](https://ant.design/components/overview)

### Steps to reproduce

An error occurs 1 second after approaching the page.

(ex. components/overview, components/flex ...)

### What is expected?

Pages below components are inaccessible.

### What is actually happening?

404 error occurs

- GET https://ant.design/_CjzfzGS-async.837f3a76.js net::ERR_ABORTED 404 (Not Found)
- Uncaught ChunkLoadError
![image](https://github.com/user-attachments/assets/0145277e-e3ff-479c-be53-4fca53a244cd)

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.2.0 |
| System | maxOS Sonoma 14.5 |
| Browser | Google Chrome version  127.0.6533.100 (arm64) |

**Comment by Wxh16144** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/5533b037a78be8144c7518e4d2527f48b9b35118
