### ISSUE TITLE
栅格布局Row指定height高度时，Col换行展示垂直高度为什么是自动平分的？

### ISSUE THREAD

**Issue by andyforever** [ant-design/ant-design#50378]
### Reproduction link

[https://codepen.io/aqcejojs-the-bashful/pen/MWMEZNM?editors=001](https://codepen.io/aqcejojs-the-bashful/pen/MWMEZNM?editors=001)

### Steps to reproduce

访问重现链接即可

### What is expected?

期望两个Col元素垂直间距为0

### What is actually happening?

两个Col元素在Row内垂直是平均布局的

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by andyforever** [comment]
之前的issue被自动关掉了，换了一个外网链接

**Comment by zombieJ** [comment]
Flex 的水平布局下，设置 `height` 后其中的元素对齐都会按照这个 `height` 来进行。如果你需要设置容器样式，可以考虑再套一层，然后把容器样式放在外层上：

https://stackblitz.com/edit/react-p34wmp?file=demo.tsx

**Comment by andyforever** [comment]
> Flex 的水平布局下，设置 `height` 后其中的元素对齐都会按照这个 `height` 来进行。如果你需要设置容器样式，可以考虑再套一层，然后把容器样式放在外层上：
> 
> https://stackblitz.com/edit/react-p34wmp?file=demo.tsx

我要把其他的Col往这个Row里拖动，如果Row没有占位高度的话很难拖进去，设置了高度又给平均

**Comment by zombieJ** [comment]
> 我要把其他的Col往这个Row里拖动，如果Row没有占位高度的话很难拖进去，设置了高度又给平均

一样的，外面那个套壳 div 处理拖拽就行了
