### ISSUE TITLE
Form documentation page is crashing

### ISSUE THREAD

**Issue by jooshford** [ant-design/ant-design#50385]
### Reproduction link

[https://ant.design/components/form](https://ant.design/components/form)

### Steps to reproduce

Load the page

### What is expected?

The page content is visible

### What is actually happening?

The page crashes and shows a white screen after 1-2 seconds

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | N/A |
| System | MacOS Ventura 13.5 |
| Browser | Chrome |

**Comment by afc163** [comment]
Fixed now.
