### ISSUE TITLE
虚拟列表在滚动后清除dom再恢复dom显示白屏，问题场景例如有的页面标签切换是销毁真实dom，切换页面再切回来恢复真实dom会导致虚拟列表白屏

### ISSUE THREAD

**Issue by cjtcjt999** [ant-design/ant-design#50397]
### Reproduction link

[https://codepen.io/cjtcjt999/pen/abgVBKp?editors=001](https://codepen.io/cjtcjt999/pen/abgVBKp?editors=001)

### Steps to reproduce

打开F12，滚动一部分虚拟列表，然后删除整个Table元素后再ctrl z撤销回来，列表内容显示白屏。
猜测列表渲染计算只绑定了滚动事件，未考虑Table真实dom移除后返回的现象，部分页面标签库采取的方案为离屏销毁dom，返回页面恢复dom

### What is expected?

虚拟列表滚动后，销毁真实dom再恢复，列表位于指定滚动区域依然能渲染出数据

### What is actually happening?

虚拟列表滚动后，销毁真实dom再恢复，列表位于指定滚动区域展示白屏

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.2.0 |
| System | win11 |
| Browser | 126.0.6478.126 |

---
猜测列表渲染计算只绑定了滚动事件，未考虑Table真实dom移除后返回的现象，部分页面标签库采取的方案为离屏销毁dom，返回页面恢复dom

**Comment by zombieJ** [comment]
React 研发不应该直接操作 dom，这些事情交给 React 生命周期来处理。

**Comment by cjtcjt999** [comment]
> React 研发不应该直接操作 dom，这些事情交给 React 生命周期来处理。

我只是为了方便重现操作，实际是项目用的页面标签组件内部实现，整个区域dom都会被销毁，返回页面dom会回来

**Comment by zombieJ** [comment]
就如我回复的，销毁 dom 应该让 React 来操作。

**Comment by cjtcjt999** [comment]
> 就如我回复的，销毁 dom 应该让 React 来操作。

页面标签用的react-stillness-component类似keep-alive的组件，在切换页面再切回能保存之前的页面状态，内部实现我不了解，但是我看真实dom被销毁了，并不是我去实现的，我业务代码并未操作任何真实dom

**Comment by cjtcjt999** [comment]
> 就如我回复的，销毁 dom 应该让 React 来操作。

页面标签用的react-stillness-component类似keep-alive的组件，在切换页面再切回能保存之前的页面状态，内部实现我不了解，但是我看真实dom被销毁了，并不是我去实现的，我业务代码并未操作任何真实dom

**Comment by cjtcjt999** [comment]
我看其他的虚拟列表如AgGrid，滚动后销毁dom后恢复，会在指定滚动区域重新再渲染出数据

**Comment by zombieJ** [comment]
无所谓谁写的销毁 DOM 代码，没有人需要来为此承担责任哈。React 生命周期外的 dom 操作是否会出现问题只看你在销毁的时候是否 React 又执行了生命周期方法导致 React 状态是否被污染。

AgGrid 使用的 callback 获取高度，antd 使用 ResizeObserver 获取高度。前者不支持动态变化高度，而后者在 Table 中的元素变化不需要开发者做额外的事情。

对于 offscreen，这是 React 所欠缺的能力。因而一些三方实现的确会有瑕疵。React 19 有提过会提供官方实现，可以关注一下。
