### ISSUE TITLE
InputNumber on focus doesn't show unformatted value

### ISSUE THREAD

**Issue by js0502** [ant-design/ant-design#50405]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jbuvhy?file=demo.tsx)

### Steps to reproduce

1. Click/ Focus on the InputNumber. 

### What is expected?

It is expected that on focus, the input number should display the unformatted value ( without the % ). 

### What is actually happening?

We still see the formatted value on focus

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.3.1 |
| System | Mac OS 14.4 |
| Browser | Chrome Version 127.0.6533.100 |

**Comment by afc163** [comment]
It is intented behaviour to show formatted value on focus.
