### ISSUE TITLE
关于form中initialValue，影响到校验图标的问题

### ISSUE THREAD

**Issue by YoFoon** [ant-design/ant-design#5040]
`{
      rules: [{ required: true,validator: this.handleCheck }],
      initialValue: item.value ? item.value : null
}`

有些组件我并不知道是否不要初始值，
然后这样子写，在没有数据的情况下
![image](https://cloud.githubusercontent.com/assets/9361203/23293573/d974358e-faa1-11e6-92bb-e770ea24955c.png)
也会出现这个校验通过的icon。

但是我并没有填写数据，所以不希望出现这个图标
于是我变成了这个样子
`{...getFieldProps( "title", _.merge(
                    {
                      rules: [{ required: true,validator: this.handleCheck }],
                    } , item.defaultValue ? {initialValue: item.defaultValue} : null))}`

略微的有点心累

**Comment by afc163** [comment]
It works well in http://codepen.io/anon/pen/gmOyMr?editors=0010

Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
closing for no response.
