### ISSUE TITLE
Typography.Text会始终显示Tooltip

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#50414]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-mhogkk?file=demo.tsx)

### Steps to reproduce

鼠标移动到文本上
![image](https://github.com/user-attachments/assets/eb496329-957e-472a-b282-ec1287dad98f)

### What is expected?

能显示全的情况下不应该显示Tooltip

### What is actually happening?

显示Tooltip

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
重现不出来，是不是有设置过屏幕缩放？

**Comment by fpsqdb** [comment]
我这缩放200% 2880x1800、无缩放1920x1080、无缩放2560x1440都能重现，之前5.19.0版本是没有问题的
这是5.20.1
![GIF 2024-08-14 14-10-19](https://github.com/user-attachments/assets/6cd93428-822f-4338-a6d2-d29e6378f5a6)

这是5.19.0
https://stackblitz.com/edit/react-mhogkk-mfcnvj?file=demo.tsx

![GIF 2024-08-14 14-22-29](https://github.com/user-attachments/assets/844757d8-6260-4e2e-b83d-585c80b07e6b)

**Comment by fpsqdb** [comment]
在火狐浏览器上无法重现，chrome可以，我的chrome版本是Version 127.0.6533.120 (Official Build) (64-bit)

**Comment by Dmaziyo** [comment]
![image](https://github.com/user-attachments/assets/5c5d065f-fc62-4013-a809-e51d7fdb15e5)
看了下好像是精度的问题，scrollWidth和offsetWidth不一样导致的
React.useEffect(() => {
    const textEle = typographyRef.current;

    if (enableEllipsis && cssEllipsis && textEle) {
      if(className?.includes('cesss')){
        debugger
      }
      const [offsetWidth, offsetHeight] = getEleSize(textEle);

      const currentEllipsis = cssLineClamp
        ? offsetHeight < textEle.scrollHeight
        : offsetWidth < textEle.scrollWidth;

      if (isNativeEllipsis !== currentEllipsis) {
        setIsNativeEllipsis(currentEllipsis);
      }
    }
  }, [enableEllipsis, cssEllipsis, children, cssLineClamp, isNativeVisible, ellipsisWidth]);

**Comment by Dmaziyo** [comment]
#50143 感觉和这个差不多？我可以提个pr？

**Comment by zombieJ** [comment]
有点麻烦，精度这个东西丢失了恢复不回来。多兜底又会导致另一种精度问题。
