### ISSUE TITLE
Pagination 组件的 align 不生效，且类型提示不存在该属性

### ISSUE THREAD

**Issue by nimeidezxj** [ant-design/ant-design#50417]
### Reproduction link

[https://ant-design.antgroup.com/components/pagination-cn#%E4%BD%95%E6%97%B6%E4%BD%BF%E7%94%A8](https://ant-design.antgroup.com/components/pagination-cn#%E4%BD%95%E6%97%B6%E4%BD%BF%E7%94%A8)

### Steps to reproduce

不用提供demo，直接引入就可以复现
<Pagination
      align="end"
      size="small"
      total={50}
      showTotal={(total) => `共 ${total} 条`}
/>

### What is expected?

希望属性可以生效

### What is actually happening?

align 属性设置成 end 并不生效，且类型检测报错，类型“IntrinsicAttributes & PaginationProps”上不存在属性“align”

| Environment | Info |
| --- | --- |
| antd | 5.17.0 |
| React | 18.1.0 |
| System | Mac 版本14.5 (23F79) |
| Browser | Chrome 版本 127.0.6533.100（正式版本） (arm64) |

**Comment by zombieJ** [comment]
文档漏写版本了，感谢提醒。
