### ISSUE TITLE
slider组件的range双滑块模式，是否可以支持可以不让互相交叉滑动，也就是说左边的滑动范围不能超过右边，右边的滑动范围不能超过左边

### ISSUE THREAD

**Issue by xiaoyingzi258** [ant-design/ant-design#50425]
### What problem does this feature solve?

场景是当右侧滑块A滑到左侧滑块B的左边，会导致左侧的数据变成了A滑块当前的数据，右侧的数据变成了B滑块的数据。我们的需求希望右侧A滑块往左侧滑动不能小于左侧滑块的数据，希望右侧滑块一直代表右侧数据，左侧同理。

### What does the proposed API look like?

可以增加一个滑块是否能够交叉滑动的开关，例如crossSlider: true（默认true， false的话则是我描述的场景）

**Comment by afc163** [comment]
`allowCross={false}`
