### ISSUE TITLE
Input.OTP 在使用mask时ctrl+z撤销操作行为异常

### ISSUE THREAD

**Issue by dislido** [ant-design/ant-design#50421]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-6jy92t?file=demo.tsx)

### Steps to reproduce

给`Input.OTP`设置mask, 输入内容，使用ctrl+z进行撤销操作

### What is expected?

正常撤销输入的内容

### What is actually happening?

根据使用的mask字符数量和已输入的内容数量，ctrl+z有不同的异常表现如：
- 连续ctrl z多次才会开始撤销
- 只移动光标，没有清除内容
- 移动到第一个输入框
- 多输入一个字符

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | Edge 125 |

**Comment by li-jia-nan** [comment]
@zombieJ 我感觉不好修，是因为替换 value 导致和原生的撤销有冲突，所以用了 mask 之后出现异常了，所以要修这个的话，无论如何是需要去改内部受控的 value，那么如果改了 value，mask 就失效了

如果一定要修的话，只能通过一些奇怪的方式糊弄过去，比如上层放一个带透明文字的 Input，下层才是真正的 Input，等于是在 dom 层面做文章了，这样的话难度就很大了，比如光标也要自己实现，光标位置也要实时计算，我觉得还不如不修了，性价比太低

另外 OTP 的时候做撤销本来就是一件奇怪的事情，一般输错了就是直接清空，就算要撤销的话也是按退格进行回退
