### ISSUE TITLE
table组件的固定头和列功能中 横向滚动条滚动时左边固定的列的数据没有固定，也在移动

### ISSUE THREAD

**Issue by djllhs** [ant-design/ant-design#5043]
![image](https://cloud.githubusercontent.com/assets/17997964/23296208/fffc6228-faae-11e6-9f4d-43b094b5eb8b.png)

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/dded4bcde463355c5ce6694e063c40667c984d7c

I re-deploy site.
