### ISSUE TITLE
Breadcrumb showing black text on dark theme

### ISSUE THREAD

**Issue by nidrizi** [ant-design/ant-design#50435]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-jz4yuk?file=demo.tsx)

### Steps to reproduce

Breadcrumb has wrong text color when wrapped with <ConfigProvider> See stackblitz example.

### What is expected?

1. Breadcrumb text color should be white when the theme is dark.
2. Breadcrumb text color should be black when the theme is light.

### What is actually happening?

Showing dark text on dark background.
Showing white text on white background.

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | "react": "^18.3.1" |
| System | MacOS Sonoma 14.5 |
| Browser | Chrome Version 127.0.6533.100 (Official Build) (arm64) |

**Comment by zombieJ** [comment]
You reproduce is work as expect:

<img width="558" alt="截屏2024-08-15 18 04 13" src="https://github.com/user-attachments/assets/0be29516-49d7-45d9-bd52-fd77c45155d7">


https://stackblitz.com/edit/antd-reproduce-5x-exj33n?file=demo.tsx

**Comment by nidrizi** [comment]
Hi, 

thnx for the fast reply. Here is a screenshot of how it looks on my PC.

![image](https://github.com/user-attachments/assets/2f7a38a0-d0b4-4a9d-b9c2-b82fd7ca29d9)


We have the same issue in many PCs on production.

**Comment by nidrizi** [comment]
Oh I just saw your stackbliz demo. I need to have a div or something with dark background. The demo looks fine after I made the change. Will see where's the problem on our codebase. 

Thank you for your effort.
