### ISSUE TITLE
Typography.Paragraph内部增加span标签、内容过多时、只显示省略号问题

### ISSUE THREAD

**Issue by choutuan** [ant-design/ant-design#50434]
### What problem does this feature solve?

比如我想单独设置文本中部分文字的样式，需要单独给文字加className, 现在在内部添加html代码后，会默认收起并不展示本该展示的内容，只显示了省略号...

**Comment by afc163** [comment]
> 比如我想单独设置文本中部分文字的样式，需要单独给文字加className, 现在在内部添加html代码后，会默认收起并不展示本该展示的内容，只显示了省略号...

给个重现吧。

**Comment by choutuan** [comment]
> > 比如我想单独设置文本中部分文字的样式，需要单独给文字加className, 现在在内部添加html代码后，会默认收起并不展示本该展示的内容，只显示了省略号...
> 
> 给个重现吧。

![image](https://github.com/user-attachments/assets/7c006181-554f-40ed-8a09-57b7c82d4e86)
![image](https://github.com/user-attachments/assets/0edd4116-7ce8-4a64-9aa7-4226026dd729)
比如图一写法就会得到图二 无法正常显示默认收起时内容

**Comment by Wxh16144** [comment]
> > > 比如我想单独设置文本中部分文字的样式，需要单独给文字加className, 现在在内部添加html代码后，会默认收起并不展示本该展示的内容，只显示了省略号...
> > 
> > 
> > 给个重现吧。
> 
> 比如图一写法就会得到图二 无法正常显示默认收起时内容

用行内元素代替块级元素就好了。

**Comment by Wxh16144** [comment]
```tsx

import React, { useState } from 'react';
import { Flex, Slider, Switch, Typography } from 'antd';

const App = () => {
  const [rows, setRows] = useState(2);
  const [expanded, setExpanded] = useState(false);

  return (
    <Flex gap={16} vertical>
      <Flex gap={16} align="center">
        <Switch
          checked={expanded}
          onChange={() => setExpanded((c) => !c)}
          style={{ flex: 'none' }}
        />
        <Slider min={1} max={20} value={rows} onChange={setRows} style={{ flex: 'auto' }} />
      </Flex>

      <Typography.Paragraph
        ellipsis={{
          rows,
          expandable: 'collapsible',
          expanded,
          onExpand: (_, info) => setExpanded(info.expanded),
        }}
        copyable
      >
        {
          [
            <span style={{ color: 'yellow' }}>ant</span>,
            'design',
            <span style={{ color: 'blue' }}>ant design</span>
          ]
            .reduce(
              (acc, item) => [...acc, new Array(100).fill(item)],
              []
            )
        }
      </Typography.Paragraph>
    </Flex>
  );
};

export default App;

```

### Preview

https://github.com/user-attachments/assets/508776fe-b904-4c18-902c-4f1ea237daf1

**Comment by afc163** [comment]
目前只支持纯文本或 inline 元素，比如 span。

**Comment by choutuan** [comment]
> ```tsx
> import React, { useState } from 'react';
> import { Flex, Slider, Switch, Typography } from 'antd';
> 
> const App = () => {
>   const [rows, setRows] = useState(2);
>   const [expanded, setExpanded] = useState(false);
> 
>   return (
>     <Flex gap={16} vertical>
>       <Flex gap={16} align="center">
>         <Switch
>           checked={expanded}
>           onChange={() => setExpanded((c) => !c)}
>           style={{ flex: 'none' }}
>         />
>         <Slider min={1} max={20} value={rows} onChange={setRows} style={{ flex: 'auto' }} />
>       </Flex>
> 
>       <Typography.Paragraph
>         ellipsis={{
>           rows,
>           expandable: 'collapsible',
>           expanded,
>           onExpand: (_, info) => setExpanded(info.expanded),
>         }}
>         copyable
>       >
>         {
>           [
>             <span style={{ color: 'yellow' }}>ant</span>,
>             'design',
>             <span style={{ color: 'blue' }}>ant design</span>
>           ]
>             .reduce(
>               (acc, item) => [...acc, new Array(100).fill(item)],
>               []
>             )
>         }
>       </Typography.Paragraph>
>     </Flex>
>   );
> };
> 
> export default App;
> ```
> 
> ### Preview
>  Kapture.2024-08-15.at.19.01.29.mp4

当内容过多时，仍然会出现最上面提到的问题，比如：
![3fdfa6104f8a1bd83c265c9ea975feff](https://github.com/user-attachments/assets/bd1851a8-182c-4c30-815c-95c4bc09def8)

**Comment by choutuan** [comment]
> 目前只支持纯文本或 inline 元素，比如 span。

span中内容过多时，就会出现省略号不显示内容的情况

**Comment by choutuan** [comment]
> 目前只支持纯文本或 inline 元素，比如 span。

span中内容过多时，就会出现省略号不显示内容的情况
![Uploading 3fdfa6104f8a1bd83c265c9ea975feff.png…]()

**Comment by choutuan** [comment]
> ```tsx
> import React, { useState } from 'react';
> import { Flex, Slider, Switch, Typography } from 'antd';
> 
> const App = () => {
>   const [rows, setRows] = useState(2);
>   const [expanded, setExpanded] = useState(false);
> 
>   return (
>     <Flex gap={16} vertical>
>       <Flex gap={16} align="center">
>         <Switch
>           checked={expanded}
>           onChange={() => setExpanded((c) => !c)}
>           style={{ flex: 'none' }}
>         />
>         <Slider min={1} max={20} value={rows} onChange={setRows} style={{ flex: 'auto' }} />
>       </Flex>
> 
>       <Typography.Paragraph
>         ellipsis={{
>           rows,
>           expandable: 'collapsible',
>           expanded,
>           onExpand: (_, info) => setExpanded(info.expanded),
>         }}
>         copyable
>       >
>         {
>           [
>             <span style={{ color: 'yellow' }}>ant</span>,
>             'design',
>             <span style={{ color: 'blue' }}>ant design</span>
>           ]
>             .reduce(
>               (acc, item) => [...acc, new Array(100).fill(item)],
>               []
>             )
>         }
>       </Typography.Paragraph>
>     </Flex>
>   );
> };
> 
> export default App;
> ```
> 
> ### Preview
>  Kapture.2024-08-15.at.19.01.29.mp4

span中内容过多时，就会出现省略号不显示内容的情况
![Uploading 3fdfa6104f8a1bd83c265c9ea975feff.png…]()

**Comment by Wxh16144** [comment]
> span中内容过多时，就会出现省略号不显示内容的情况

转个弯呗，同一句话同样式，根据字符串拆分成多个 span 标签不就规避这个问题了么。

另外 antd 的省略号也是通过 js 计算的。即便支持你说的 html 标签，也没办法做到省略吧。不是万金油

**Comment by choutuan** [comment]
> > span中内容过多时，就会出现省略号不显示内容的情况
> 
> 转个弯呗，同一句话同样式，根据字符串拆分成多个 span 标签不就规避这个问题了么。
> 
> 另外 antd 的省略号也是通过 js 计算的。即便支持你说的 html 标签，也没办法做到省略吧。不是万金油

是的、感谢！
