### ISSUE TITLE
RangePicker 当showTime时，确定按钮没有回调事件

### ISSUE THREAD

**Issue by JhinDeng** [ant-design/ant-design#5044]
#### Environment(required)

- antd version: ^2.6.4
- OS and its version: mac 10.12.3
- Browser and its version: chrome 56.0.2924.87 (64-bit)

**Comment by JhinDeng** [comment]
只能通过 onOpenChange，来判断是否完成操作。
点击RangePicker之外的区域（也许，我只是想取消这次操作），也会触发 onOpenChange。
无法判断用户的行为。

**Comment by afc163** [comment]
There is `onOk`, I fixed document up.

**Comment by JhinDeng** [comment]
I test onOK again, it`s not work.
`
<RangePicker  showTime onOK={() => console.log('hello')} />

`

**Comment by JhinDeng** [comment]
I test onOK again, its not work.
`<RangePicker showTime onOK={() => console.log('hello')} />`

**Comment by afc163** [comment]
```diff
- onOK
+ onOk
```

**Comment by benjycui** [comment]
We can add warning for `onOK`, just like React do this for `componentShouldUpdate`.
