### ISSUE TITLE
Node20版本中 Form.item 跨页面调用 无法使用对应的form.getFieldValue

### ISSUE THREAD

**Issue by archer0621** [ant-design/ant-design#50445]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/form-item-vtdcsy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzw9i9xx00063b6ivaqr8frr%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzw9i9xx00023b6inxgvblkx%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzw9i9xx00033b6id89ia09o%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzw9i9xx00053b6i550qam5w%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzw9i9xx00023b6inxgvblkx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzw9i9xw00013b6ievac1d7o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clzw9i9xx00023b6inxgvblkx%2522%252C%2522activeTabId%2522%253A%2522clzw9i9xw00013b6ievac1d7o%2522%257D%252C%2522clzw9i9xx00053b6i550qam5w%2522%253A%257B%2522id%2522%253A%2522clzw9i9xx00053b6i550qam5w%2522%252C%2522activeTabId%2522%253A%2522clzw9rtl8008l3b6iysxwrxfk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzw9i9xx00043b6iye1z0z7s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzw9rtl8008l3b6iysxwrxfk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzw9i9xx00033b6id89ia09o%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzw9i9xx00033b6id89ia09o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

引入ChildrenItem组件

### What is expected?

正常打印对应log

### What is actually happening?

提示Cannot read properties of undefined (reading 'getFieldsValue')

| Environment | Info |
| --- | --- |
| Node.js | 20 |
| React | 16 |
| Antd | 4.17.0 |
| System | Mac |
| Browser | Google Chrome 127.0.6533.90 |

**Comment by afc163** [comment]
<img width="702" alt="图片" src="https://github.com/user-attachments/assets/658693f4-91f5-4bf9-a69d-80626d6a9ce7">
