### ISSUE TITLE
日期DatePicker选择日期自动触发onBlur事件导致无法选择日期时间

### ISSUE THREAD

**Issue by 13113415033** [ant-design/ant-design#50444]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/13113415033/antd-5-18-2/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzw7kktd00063j6jem2yu6c2%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzw7kktc00023j6jf3fe7l7a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzw7kktc00043j6jx8blv9s0%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzw7kktd00053j6jw09ka2g7%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzw7kktc00023j6jf3fe7l7a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzw7kktc00013j6jc0cac9jy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzw7nkop00023j6jqnylma87%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A66%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A66%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzw7kktc00023j6jf3fe7l7a%2522%252C%2522activeTabId%2522%253A%2522clzw7nkop00023j6jqnylma87%2522%257D%252C%2522clzw7kktd00053j6jw09ka2g7%2522%253A%257B%2522id%2522%253A%2522clzw7kktd00053j6jw09ka2g7%2522%252C%2522activeTabId%2522%253A%2522clzw7lryf002e3j6j8blfjkdi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clzw7klmy000b3j6juwxq2h41%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzw7lryf002e3j6j8blfjkdi%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzw7kktc00043j6jx8blv9s0%2522%253A%257B%2522id%2522%253A%2522clzw7kktc00043j6jx8blv9s0%2522%252C%2522activeTabId%2522%253A%2522clzw7llc7001w3j6j1z3wkab1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzw7kktc00033j6j14rr781o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522NEW_TERMINAL%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzw7llc7001w3j6j1z3wkab1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

点击左上角按钮弹出菜单，选择日期

### What is expected?

值保存，窗口不关闭

### What is actually happening?

触发onBlur事件，日期弹窗被关闭，值未保存

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.2.0 |
| System | windows |
| Browser | edga |

---
当日期控件下面有按钮时会发送上面的bug，按钮在控件上方则不会。
在IonMenu组件中会存在这种问题，在IonPage中则不会

**Comment by MadCcc** [comment]
能给个只有 antd 的简单用例么，你的复现中依赖了其他组件库，看不出问题所在

**Comment by 13113415033** [comment]
> 能给个只有 antd 的简单用例么，你的复现中依赖了其他组件库，看不出问题所在

不好意思，我没有仅使用 antd 的用例，我补充一个信息，getPopupContainer	定义浮层的容器，默认为 body 上新建 div，当我将浮层的容器设置为父节点就没问题。如下
`        <DatePicker
            getPopupContainer={(trigger) => {
              return trigger.parentNode as HTMLElement;
            }}
          />
`
但是加了这个配置之后浮层超出父容器的部分会被隐藏
