### ISSUE TITLE
InputNumber设置controls={false }后，hover时增减按钮的样式占位还是在。在有suffix情况下导致右边出现较大空隙

### ISSUE THREAD

**Issue by ExtJSFantasy** [ant-design/ant-design#50442]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-2nuyxc)

### Steps to reproduce

<InputNumber
      suffix="RMB"
      controls={false}
      style={{
        width: '100%',
      }}
    />

### What is expected?

增减按钮的样式占位消失

### What is actually happening?

增减按钮的样式占位依旧在，在有suffix情况下导致右边出现较大空隙

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.3.1 |
| System | Apple M2 Pro 14.5 (23F79) |
| Browser | Chrome 127.0.6533.100（正式版本） (arm64) |

**Comment by afc163** [comment]
@coding-ice
