### ISSUE TITLE
ColorPicker 能否增加禁用选择颜色格式的功能

### ISSUE THREAD

**Issue by virzs** [ant-design/ant-design#50447]
### What problem does this feature solve?

禁止用户选择颜色格式，当前没有api限制，比如接口限制只能是hex格式的颜色，用户选择其他类型的颜色提交时需要转换为hex格式，由于不同颜色格式在转换时可能会出现误差，希望在组件上直接限制

### What does the proposed API look like?

```jsx
import { ColorPicker } from "antd";

export default () => {
  return <ColorPicker disabledFormat defaultFormat="hex" />;
};
```

**Comment by zombieJ** [comment]
返回的是 Color 对象，消费的时候直接用 Hex 不就行了么？Color 对象本身支持多种格式转换，format 是 UI 上的。

**Comment by virzs** [comment]
> 返回的是 Color 对象，消费的时候直接用 Hex 不就行了么？Color 对象本身支持多种格式转换，format 是 UI 上的。

因为现在没办法直接禁用格式选择
