### ISSUE TITLE
antd动态主题被第三方库干扰

### ISSUE THREAD

**Issue by heimiguoguo** [ant-design/ant-design#50452]
### Reproduction link

[https://heimiguoguo.github.io/](https://heimiguoguo.github.io/)

### Steps to reproduce

在点击表单编辑器菜单前，动态主题生效，点击表单编辑器后，动态主题被覆盖，表单编辑器用form-render实现，会加载antd的less样式文件

### What is expected?

第三方包form-render引用不干扰antd的动态主题功能

### What is actually happening?

第三方包form-render引用干扰到了antd的动态主题功能

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 6.12.0 |
| System | macOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
动态主题指的是什么？看起来并没有使用 antd 5

**Comment by heimiguoguo** [comment]
> 动态主题指的是什么？看起来并没有使用 antd 5
使用的antd 4.x
https://4x-ant-design.antgroup.com/docs/react/customize-theme-variable-cn
页面对应位置
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/cd380061-6bd3-4ba1-9dd1-a2b5c861ab09">

**Comment by zombieJ** [comment]
看起来是引入了多份样式导致的冲突：

<img width="350" alt="截屏2024-08-19 11 23 27" src="https://github.com/user-attachments/assets/7d011d87-61c4-4e94-acff-2ed7d445cc9c">

这个和 antd 本身没有关系，可以自行排查一下哪里多引入了。
