### ISSUE TITLE
Antd-Snippets for VS Code users

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#5045]
https://marketplace.visualstudio.com/items?itemName=bang.antd-snippets

I just published a VS Code ext. 😄

**Comment by afc163** [comment]
We can put it into https://github.com/websemantics/awesome-ant-design .

**Comment by bang88** [comment]
😄
-- 
bang

**Comment by infeng** [comment]
Cool!

**Comment by benjycui** [comment]
And this should be recommended to our full-stack developers 😄
