### ISSUE TITLE
Progress can't change normal color

### ISSUE THREAD

**Issue by gregorysl** [ant-design/ant-design#5046]
I've checked source for progress, and there is following object:
progress.js:53
var statusColorMap = {
    normal: '#108ee9',
    exception: '#ff5500',
    success: '#87d068'
};
ant there is no ability to change it

#### Environment(required)
- antd version:    "antd": "^2.7.2",

#### What do you expected?

Ability to customize colors, at least for normal.

#### What happen?
After changing less variable for 
    'primary-color': 'black'
color for progress doesn't change
 Style is not as expected. 

#### Re-producible online demo
Can't reproduce online, as codepen has css source, no less

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/5002

**Comment by Jiajia-Yang** [comment]
I need a definite answer to change the color
