### ISSUE TITLE
rowSelection columnWidth is ignored when other columns have width set

### ISSUE THREAD

**Issue by alexander-shch** [ant-design/ant-design#50464]
### Reproduction link

[https://codepen.io/GrimR1P/pen/zYVpmdO?editors=0010](https://codepen.io/GrimR1P/pen/zYVpmdO?editors=0010)

### Steps to reproduce

Set columnWidth for rowSelection to be 40 and set any data column width to X
selection column width is ignored and stretched to fill the table space

### What is expected?

column width to be respected

### What is actually happening?

column width isn't respected

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18.1.0 |
| System | macOS 14 Sonoma |
| Browser | Chrome / FF / Safari / * |

**Comment by afc163** [comment]
That is native behaviour of table element, try leave one column without specified width at least.
