### ISSUE TITLE
Unify react components test workflow

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#50461]
[rc 组件](https://github.com/react-component/)里 ci 流程不太一致，要升级或优化的时候要改所有的仓库，比如 https://github.com/ant-design/ant-design/issues/50387

解法：参考 [reusing-workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) 统一 yml 文件到此处：https://github.com/react-component/rc-test/blob/main/.github/workflows/test.yml

可以参考 https://github.com/react-component/footer/pull/74 和 https://github.com/react-component/select/pull/1059 。

拷贝以下文件内容并更新对应仓库的 yml 文件：

```yml
name: ✅ test
on: [push, pull_request]
jobs:
  test:
    uses: react-component/rc-test/.github/workflows/test.yml@main
    secrets: inherit
```

- [x] https://github.com/react-component/select https://github.com/react-component/select/pull/1059
- [x] https://github.com/react-component/footer https://github.com/react-component/footer/pull/74
- [x] https://github.com/react-component/portal https://github.com/react-component/portal/pull/20
- [x] https://github.com/react-component/tour https://github.com/react-component/tour/pull/65
- [x] https://github.com/react-component/async-validator https://github.com/react-component/async-validator/pull/17
- [x] https://github.com/react-component/align https://github.com/react-component/align/pull/301
- [x] https://github.com/react-component/dom-align https://github.com/react-component/dom-align/pull/45
- [x] https://github.com/react-component/color-picker https://github.com/react-component/color-picker/pull/267
- [x] https://github.com/react-component/mutate-observer https://github.com/react-component/mutate-observer/pull/12
- [x] https://github.com/react-component/cascader https://github.com/react-component/cascader/pull/528
- [x] https://github.com/react-component/checkbox https://github.com/react-component/checkbox/pull/291
- [x] https://github.com/react-component/context https://github.com/react-component/context/pull/49
- [x] https://github.com/react-component/collapse https://github.com/react-component/collapse/pull/351
- [x] https://github.com/react-component/dialog https://github.com/react-component/dialog/pull/457
- [x] https://github.com/react-component/drawer https://github.com/react-component/drawer/pull/476
- [x] https://github.com/react-component/dropdown https://github.com/react-component/dropdown/pull/237
- [x] https://github.com/react-component/field-form https://github.com/react-component/field-form/pull/720
- [x] https://github.com/react-component/image https://github.com/react-component/image/pull/369
- [x] https://github.com/react-component/input https://github.com/react-component/input/pull/78
- [x] https://github.com/react-component/input-number https://github.com/react-component/input-number/pull/670
- [x] https://github.com/react-component/mentions https://github.com/react-component/mentions/pull/275
- [x] https://github.com/react-component/menu https://github.com/react-component/menu/pull/739
- [x] https://github.com/react-component/motion https://github.com/react-component/motion/pull/54
- [x] https://github.com/react-component/notification https://github.com/react-component/notification/pull/360
- [x] https://github.com/react-component/pagination https://github.com/react-component/pagination/pull/606
- [x] https://github.com/react-component/picker https://github.com/react-component/picker/pull/868
- [x] https://github.com/react-component/progress https://github.com/react-component/progress/pull/299
- [x] https://github.com/react-component/rate https://github.com/react-component/rate/pull/192
- [x] https://github.com/react-component/resize-observer https://github.com/react-component/resize-observer/pull/210
- [x] https://github.com/react-component/segmented https://github.com/react-component/segmented/pull/254
- [x] https://github.com/react-component/slider https://github.com/react-component/slider/pull/1031
- [x] https://github.com/react-component/steps https://github.com/react-component/steps/pull/368
- [x] https://github.com/react-component/switch https://github.com/react-component/switch/pull/156
- [x] https://github.com/react-component/table https://github.com/react-component/table/pull/1179
- [x] https://github.com/react-component/tabs https://github.com/react-component/tabs/pull/738
- [x] https://github.com/react-component/textarea https://github.com/react-component/textarea/pull/65
- [x] https://github.com/react-component/tooltip https://github.com/react-component/tooltip/pull/482
- [x] https://github.com/react-component/tree https://github.com/react-component/tree/pull/861
- [x] https://github.com/react-component/tree-select https://github.com/react-component/tree-select/pull/554
- [x] https://github.com/react-component/upload https://github.com/react-component/upload/pull/569
- [x] https://github.com/react-component/util https://github.com/react-component/util/pull/580
- [x] https://github.com/react-component/virtual-list https://github.com/react-component/virtual-list/pull/285
- [x] https://github.com/react-component/trigger https://github.com/react-component/trigger/pull/476
- [x] https://github.com/ant-design/ant-design-colors https://github.com/ant-design/ant-design-colors/pull/93
- [x] https://github.com/ant-design/fast-color https://github.com/ant-design/fast-color/pull/65
- [x] https://github.com/ant-design/cssinjs https://github.com/ant-design/cssinjs/pull/194
- [x] https://github.com/ant-design/cssinjs-utils https://github.com/ant-design/cssinjs-utils/pull/19
- [x] https://github.com/ant-design/react-slick https://github.com/ant-design/react-slick/pull/118

**Comment by Layouwen** [comment]
看了一下, 好像都已经处理过了

**Comment by afc163** [comment]
We made it! @Layouwen @Ali-ovo @IsKaros
