### ISSUE TITLE
Popconfirm width is too narrow and text doesn't display properly

### ISSUE THREAD

**Issue by lobosan** [ant-design/ant-design#5047]
Hi, I'm following this [example](https://ant.design/docs/react/practical-projects) on a Windows 10 with Google Chrome and the [Popconfirm](https://ant.design/components/popconfirm/) is too narrow to display the text properly. Is this an issue or how can I change the width?

![image](https://cloud.githubusercontent.com/assets/314886/23320465/e3490038-faa8-11e6-849c-bb0920d95bb1.png)

**Comment by NE-SmallTown** [comment]
@lobosan  A re-producible demo would be better,thanks.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
my bad: https://github.com/react-component/trigger/pull/43

**Comment by afc163** [comment]
Fixed in `rc-trigger@1.8.3`, try to reinstall antd.

**Comment by lobosan** [comment]
Thanks for your quick support
