### ISSUE TITLE
DatePicker的RangePicker组件选完时间会清空

### ISSUE THREAD

**Issue by ZeroCodeLin** [ant-design/ant-design#50485]
### Reproduction link

[https://ant.design/components/date-picker-cn](https://ant.design/components/date-picker-cn)

### Steps to reproduce

带时分秒的范围选择器，点击开始时间输入框选择日期后不选择时分秒，点击结束日期输入框选择日期后点击确定，所选的时间会全部清空。5.13的版本还是正常，5.14后会出现这个问题

### What is expected?

保留所选时间

### What is actually happening?

清空了所选时间

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 18 |
| System | win |
| Browser | chrome |

**Comment by ZeroCodeLin** [comment]
https://codepen.io/debugger119/pen/JjQLyze?editors=001

5.13的版本还是正常，5.14后会出现这个问题

操作步骤：
1. 开始时间选择到日
2. 不点击时分秒，直接点击结束时间的输入框选择时间后确定

**Comment by laughing-pic-zhu** [comment]
问题➕1，请尽快修复下～

**Comment by ZeroCodeLin** [comment]
这个麻烦问题帮忙看下呀 @afc163 @MadCcc
