### ISSUE TITLE
upload组件在安卓手机上多选不能触发上传

### ISSUE THREAD

**Issue by hjhwel** [ant-design/ant-design#50480]
### Reproduction link

[https://ant-design.antgroup.com/components/upload-cn](https://ant-design.antgroup.com/components/upload-cn)

### Steps to reproduce

找到多选模式demo的在华为或者一加的安卓手机上，选择多个照片并不会触发上传，但是只选择一个照片就可以

### What is expected?

期望能支持多选

### What is actually happening?

现在只能单选上传

| Environment | Info |
| --- | --- |
| antd | 5.20.1 |
| React | 17.0.0 |
| System | 安卓 |
| Browser | 安卓浏览器 |

**Comment by zombieJ** [comment]
Upload 用的原生的 input 实现上传能力，如果手机不支持 `multiple` 属性，那组件侧也做不了什么哈。
