### ISSUE TITLE
preact support?

### ISSUE THREAD

**Issue by breeswish** [ant-design/ant-design#5048]
It seems that some components (e.g. tabs) do not work well when using preact.

**Comment by benjycui** [comment]
We don't use preact, but you can PR to make antd work with it, thanks.

**Comment by bang88** [comment]
@breeswish  Antd should work with  `preact`, but need `preact-compat`  installed.

**Comment by breeswish** [comment]
@bang88 `preact-compat` is installed though.. I will take a look at the reason of the incompatibility when I'm free.

**Comment by plandem** [comment]
rc-animation is not working well with preact. At least I'm getting errors for this lib.

**Comment by afc163** [comment]
Anyone who want to use antd in preact is welcome to PR to make it work.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1839

**Comment by yesmeck** [comment]
Close since it's not high priority for us now.

**Comment by mindplay-dk** [comment]
Maybe consider reopening this since Preact X has now been released?

It should be a lot more compatible with modern React.

**Comment by kernel-dang** [comment]
is this issue re-opened?

**Comment by Gervwyk** [comment]
Has anyone tried this?

**Comment by xr0master** [comment]
For the sake of interest, I launched the project on a `preact` instead of `react` with the `@preact/compat` package. Everything worked well!

One issue is with icons (`@ant-design/icons`) and TS, their types do not match in `preact`.

The bundle size decreased by 20%. On a quick look, everything worked as expected.

**Comment by ferretwithaberet** [comment]
Seems like preact + antd has some sort of a memory leak. Taking snapshots periodically with the firefox devtools shows the used memory keeps increasing. Tested by only importing and using `<Button />` in a newly created preact app.
