### ISSUE TITLE
Form API NamePath length

### ISSUE THREAD

**Issue by VasilNikolov** [ant-design/ant-design#50484]
### What problem does this feature solve?

The form api got a better typing in the lates 5.20 release, which is really nice, but only allows up to 5 levels of nesting of the NamePath arguments for example for the formInstance.getFieldValue.
I think the issue is in the DeepNamePath type which allows a length of 5, but the functionality supports more than 5.

### What does the proposed API look like?

Increase limit to match functionality.

**Comment by Wxh16144** [comment]
'DeepNamePath' may have performance issues ref #49185, there has been feedback before. Personally, I don't like this depth. It would be nice if the TS description file could override this default value. I've tried many times, but haven't solved it.

**Comment by VasilNikolov** [comment]
Idk if there's a way to make it configurable.

**Comment by zombieJ** [comment]
Currently TS does not support dynamic configurable : (. You can consider to defs types override it. (But yes, I think deep loop def dig is a create feature)
