### ISSUE TITLE
访问 demo 独立链接会先跳到 404 页面再渲染演示

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#50488]
https://ant.design/~demos/button-demo-basic

**Comment by Wxh16144** [comment]
插眼 👀

看了一圈 dumi 和 umijs ，不知道 route 是怎么套的。

感觉有可能是 dumi 这里插入顺序问题，也有可能是 `parentId` 计算嵌套问题。

https://github.com/umijs/dumi/blob/6ae3a6451442d6786c72bb13b9d074cb88405f06/src/features/routes.ts#L259-L277

**Comment by MadCcc** [comment]
现在还有吗，我没有复现了

**Comment by afc163** [comment]
确实没了，神奇。。。
