### ISSUE TITLE
bug: incorrect style

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/ant-design#50498]
### Reproduction link

[https://ant.design/components/float-button-cn#float-button-demo-group](https://ant.design/components/float-button-cn#float-button-demo-group)

按钮组 hover 圆角：

![image](https://github.com/user-attachments/assets/3ad866b5-d08d-4f14-a0cc-fbed3c575a3f)

菜单模式 hover 圆角：

![image](https://github.com/user-attachments/assets/5c9feae9-93b2-4bfd-a24b-27c4e292b9bd)

### Steps to reproduce

https://ant.design/components/float-button-cn#float-button-demo-group

### What is expected?

菜单模式的圆角和按钮组的圆角一样

### What is actually happening?

菜单模式的圆角和按钮组的圆角不一样

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Chrome999 |

**Comment by afc163** [comment]
上面更好一点。

**Comment by li-jia-nan** [comment]
这个得在 feature 分支修，样式在 feature 重构过
