### ISSUE TITLE
Datepicker inside modal problem

### ISSUE THREAD

**Issue by alancastro** [ant-design/ant-design#505]
I'm having a problem with Datepicker inside a Modal. 
To see the issue, do the following steps:
1. Open your modal that has a Datepicker in it
2. Open your Datepicker
3. Close your Datepicker
4. Close your Modal

After theses steps, you should still see the Datepicker selection box.
I'm using version: 0.10.0-beta23

**Comment by benjycui** [comment]
I tried, but the `Datepicker` will disappear with `Modal` as expected. Could you provide more information?

And this is my test case:
```jsx
import { Modal, Button, Datepicker } from 'antd';

const App = React.createClass({
  getInitialState() {
    return { visible: false };
  },
  showModal() {
    this.setState({
      visible: true
    });
  },
  handleOk() {
    console.log('点击了确定');
    this.setState({
      visible: false
    });
  },
  handleCancel() {
    this.setState({
      visible: false
    });
  },
  render() {
    return <div>
      <Button type="primary" onClick={this.showModal}>显示对话框</Button>
      <Modal title="第一个 Modal" visible={this.state.visible}
      onOk={this.handleOk} onCancel={this.handleCancel}>
        <Datepicker defaultValue="2015-12-12" />
      </Modal>
    </div>;
  }
});

ReactDOM.render(<App /> , document.getElementById('components-modal-demo-basic'));
```

**Comment by alancastro** [comment]
I still see the issue with this code.

![screen shot 2015-11-10 at 10 38 29 pm](https://cloud.githubusercontent.com/assets/147017/11082474/ea93e284-87fb-11e5-9212-4a2a56791c28.png)

When I close the modal

![screen shot 2015-11-10 at 10 38 46 pm](https://cloud.githubusercontent.com/assets/147017/11082480/f7f56a38-87fb-11e5-89fb-81cabc1c915b.png)

**Comment by alancastro** [comment]
The commit did not fix it. I added
&-hidden {
    display: none;
  }
inside .@{calendar-prefix-cls}-picker-container to Picker.less and my problem went away.

**Comment by yiminghe** [comment]
No, you do not need, the popup calendar will be destroyed after hide.

Maybe you need to install the latest

**Comment by alancastro** [comment]
How can I install the latest beta from npm?

Em quarta-feira, 11 de novembro de 2015, yiminghe <notifications@github.com>
escreveu:

> No, you do not need, the popup calendar will be destroyed after hide.
>
> Maybe you need to install the latest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/505#issuecomment-155978348>
> .
>


-- 
Alan

**Comment by afc163** [comment]
try `npm install antd@beta`

**Comment by alancastro** [comment]
Guys, sorry about that, just noticed that I was including React twice in my development environment. I fixed it and can't reproduce the problem anymore!
Thanks for the help!
