### ISSUE TITLE
findDOMNode is not a function

### ISSUE THREAD

**Issue by Muthuram05** [ant-design/ant-design#50505]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/jolly-neumann-hnpkdt)

### Steps to reproduce

Upgrade react 19 version 

### What is expected?

none

### What is actually happening?

Getting error "TypeError: react_dom__WEBPACK_IMPORTED_MODULE_8___default(...).findDOMNode is not a function"

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 19 |
| System | Mac |
| Browser | Chrome |

**Comment by Muthuram05** [comment]
<img width="1792" alt="Screenshot 2024-08-20 at 5 57 13 PM" src="https://github.com/user-attachments/assets/2aa4762e-3fd5-4b05-b5fd-39ee60e2cd26">

**Comment by afc163** [comment]
<img width="573" alt="图片" src="https://github.com/user-attachments/assets/f14bb86c-35e0-4a93-9301-3102a61c985d">

**Comment by Muthuram05** [comment]
Reproduce like -> https://codesandbox.io/p/devbox/jolly-neumann-hnpkdt

**Comment by afc163** [comment]
Can't reproduce in your codesandbox.

<img width="1434" alt="image" src="https://github.com/user-attachments/assets/0df4fd52-2536-449c-9a0f-d0dacb01d025">
