### ISSUE TITLE
Segmented组件增加 竖起排列  主要是好看

### ISSUE THREAD

**Issue by 741599086** [ant-design/ant-design#50519]
### What problem does this feature solve?

好看

### What does the proposed API look like?

position = “xxxx”

**Comment by zombieJ** [comment]
长什么样子的？~

**Comment by 741599086** [comment]
> 长什么样子的？~

![image](https://github.com/user-attachments/assets/0afe1f19-d0e4-4d01-b350-e788e55e42ae)

**Comment by kwooshung** [comment]
感觉可以支持下，确实有类似的需求。

**Comment by ONLY-yours** [comment]
会不会和现有 menu 有点重复

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50708
