### ISSUE TITLE
Wrong link auto parse

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#5051]
https://ant.design/changelog-cn#2.6.2

<img width="348" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23332938/2fea7ed4-fbbd-11e6-8c1a-566d707d91d4.png">

**Comment by benjycui** [comment]
写文档时无需考虑链接里的 locale，渲染时会自动加上。

**Comment by afc163** [comment]
如果已经加了，不要自动加。
