### ISSUE TITLE
https://registry.npm.taobao.org/ 解决证书失效问题

### ISSUE THREAD

**Issue by guoyongchang** [ant-design/ant-design#50516]
### What problem does this feature solve?

https://registry.npm.taobao.org/ 解决证书失效问题

### What does the proposed API look like?

https://registry.npm.taobao.org/ 解决证书失效问题。

你们阿里怎么老是搞这种掉链子的东西？1月证书就到期了，到现在都不续？
赶紧解决一下，别耽误大家用。现在网上一搜npm和证书全他妈是你们阿里这个npm源干的。

**Comment by guoyongchang** [comment]
<img width="896" alt="image" src="https://github.com/user-attachments/assets/dab7afb5-8b38-46ad-9437-fe737ff2741b">


好好看看

**Comment by yoyo837** [comment]
这个域名都申明废弃一年多了，你还在用，是不是也该挨骂？

**Comment by yoyo837** [comment]
https://zhuanlan.zhihu.com/p/432578145

**Comment by yoyo837** [comment]
想必也是个行业脱节的程序员。

**Comment by RedJue** [comment]
爱用不用，不带点脑子就喷

**Comment by zombieJ** [comment]
参考官方说明，域名已经迁移，请及时替换。

另外，这似乎和我们也没有关系哈~

**Comment by guoyongchang** [comment]
@yoyo837 @RedJue 

一个运维动动手就能解决的事情，现在让全行业使用这个源的开发者改，如果这是合理的，网上也不会有这么多问题了。


@zombieJ 

发这里是因为这里用户量较大且同为阿里系。

**Comment by yoyo837** [comment]
> @yoyo837 @RedJue
> 
> 一个运维动动手就能解决的事情，现在让全行业使用这个源的开发者改，如果这是合理的，网上也不会有这么多问题了。
> 
> @zombieJ
> 
> 发这里是因为这里用户量较大且同为阿里系。

这个事儿里面有些关系你没有理清楚，或者不知情，再者，很多事情也没有办法按单个人的意志尽善尽美。我还想百度不要加广告呢，他不听我的。

**Comment by fengmk2** [comment]
> @yoyo837 @RedJue
> 
> 一个运维动动手就能解决的事情，现在让全行业使用这个源的开发者改，如果这是合理的，网上也不会有这么多问题了。
> 
> @zombieJ
> 
> 发这里是因为这里用户量较大且同为阿里系。

非常抱歉，我是负责维护 npmmirror 的人，给你带来困扰了。由于历史原因 npmmiror 不能再使用淘宝域名，所以才不得不做出这样的选择，真的不是「一个运维动动手就能解决的事情」，能让 npmmiror 可以持续提供服务已经不容易，请大家多多包涵 🧎🏻

**Comment by FatTigerWang** [comment]
谁让你用taobao源呢，export https_proxy 不会用么？另外请原理任何阿里魔改的东西，今天方便你，明天就成为阻碍你的东西
