### ISSUE TITLE
Warning 'there are more than one `getFieldDecorator` in it.'

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#5052]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.
I wont FormItem contain more than one  component . 
this case always use. for excampels
```
       <FormItem label='Age'>
            {getFieldDecorator('Age',  {rules: [{required: true, message: 'Age require' }]})(
              <Input style={{ width: 100 }} size="small" />
            )}
            {getFieldDecorator('AgeUnit',  {rules: [{required: true, message: 'AgeUnit require' }]})(
              <Select allowClear size="small" style={{ width: 65 }}>
              <Option value="year">year</Option>
              <Option value="month">month</Option>
              <Option value="day">day</Option>
            </Select>
            )}
          </FormItem>
 
console waring  `Form.Item` cannot generate `validateStatus` and `help` automatically, while there are more than one `getFieldDecorator` in it.

in this case,how can i do?

以后会支持这种场景吗，去除警告吗，这种场景经常使用，相关联的多个组件在一个formitem内输入。

<!-- e.g. I just imported Button from antd -->

#### What do you expected?

<!-- e.g. It works fine as official website -->

#### What happen?

<!-- e.g. Style is not as expected. (And it will be better to provide screenshot) -->

#### Re-producible online demo

<!-- Please fork http://codepen.io/benjycui/pen/KgPZrE?editors=001 to re-produce you issue -->

**Comment by afc163** [comment]
One `FormItem` should match one getFieldDecorator, that is this warning existed for.

See more: https://ant.design/components/form-cn/#Form.Item

**Comment by whx76** [comment]
这个我看到了，我想说的是，经常有业务场景需要在一个formitem下包含多个组件，比如输入金额及金额单位，年龄年龄单位，起止时间（-ant提供了组件）等等，如果都通过自定义组件实现，工作量比较大，如果可以支持formitem下包含多个组件，那就可以很方便将多个字段组件包含在一个formitem下，业务表单看起来比较舒服。而不是多个formitem分离比较远。所以是想问能否增强下这个formitem，支持这种业务场景。

**Comment by afc163** [comment]
API 暂时不会变动。

虽然 `FormItem` 不能嵌入多个 `getFieldDecorator`。FormItem 还是可以互相嵌套的，你可以看下 https://ant.design/components/form-cn/#components-form-demo-validate-static 这个例子。

<img width="378" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23340673/5fc5ec52-fc75-11e6-9e59-be10b75003ef.png">

**Comment by whx76** [comment]
谢谢，这个是个好例子
