### ISSUE TITLE
tour

### ISSUE THREAD

**Issue by Jackierchan** [ant-design/ant-design#50525]
### What problem does this feature solve?

移动端上想实现下一步按钮和整体区域分离开，类似于支付宝的里的那种，用这个组件可以吗，有什么推荐的组件吗

### What does the proposed API look like?

移动端上想实现下一步按钮和整体区域分离开，类似于支付宝的里的那种，用这个组件可以吗，有什么推荐的组件吗

![image](https://github.com/user-attachments/assets/eb51b853-d81b-4695-994e-4fdd2982402e)

**Comment by afc163** [comment]
See https://stackblitz.com/edit/react-8awzq8?file=demo.tsx
