### ISSUE TITLE
windows上chrome浏览器升级到最新版本（128.0.6613.85），zoom缩放的情况下，下拉和dropdown组件选项偏移不对，导致被遮蔽或者无选项或者有偏移

### ISSUE THREAD

**Issue by JornyWang** [ant-design/ant-design#50539]
### Reproduction link

[https://4x.ant.deign/components/select-cn](https://4x.ant.deign/components/select-cn)

### Steps to reproduce

设置body的zoom成0.8

### What is expected?

windows上chrome浏览器升级到最新版本（128.0.6613.85），zoom缩放的情况下，下拉和dropdown组件选项偏移不对，导致被遮蔽或者无选项或者有偏移

### What is actually happening?

windows上chrome浏览器升级到最新版本（128.0.6613.85），zoom缩放的情况下，下拉和dropdown组件选项偏移不对，导致被遮蔽或者无选项或者有偏移

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | windows |
| Browser | chrome 128.0.6613.85 |

**Comment by wanpan11** [comment]
参考这个
https://github.com/ant-design/ant-design/issues/49640#issuecomment-2199466400

**Comment by JornyWang** [comment]
> 参考这个 [#49640 (comment)](https://github.com/ant-design/ant-design/issues/49640#issuecomment-2199466400)
chrome新版本128.0.6613.85版本下，使用transform也一样，https://4x.ant.deign/components/select-cn官网上设置一下就知道了

**Comment by afc163** [comment]
@JornyWang 需要升级到 5.x 上，5.x 解决了 transform 下的浮层组件定位问题。

**Comment by JornyWang** [comment]
> @JornyWang 需要升级到 5.x 上，5.x 解决了 transform 下的浮层组件定位问题。

5很多组件方法都变了，有些老项目根本升不上去的

**Comment by hhyzz** [comment]
我也遇到这个问题了，请问你现在有解决这个问题的办法吗

**Comment by yaokaiqd** [comment]
看起来5.X确实没问题  
不过我们这边用的antd-design-vue 1.x
目前临时的解决方案是 判断浏览器版本 大于等于128的把组件的getPopupContainer绑定到body上 小于128继续不变绑定到父元素上 
```
function getPopupContainer(triggerNode) {
  const userAgent = navigator.userAgent;
  const index = userAgent.indexOf('Chrome/')
  const chromeVersion = userAgent.substring(index + 7);
  const versionParts = chromeVersion.split(' ');
  const majorVersion = parseInt(versionParts[0], 10);

  if (index > -1 && majorVersion >= 128) {
    return document.body
  }
  return triggerNode.parentNode
}
```

**Comment by studyisnotsimple** [comment]
antd-vue4  前来报到

**Comment by dushenshen111** [comment]
我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀

**Comment by testAdmin-dev** [comment]
我在v4.16.1也出现组件偏移问题，请问在v4版本中有解决方案吗？

**Comment by chuqizhen** [comment]
v4 一样的问题

**Comment by yxy297376376** [comment]
https://developer.chrome.google.cn/release-notes/128?hl=zh_tw  看起来像停用標準化 CSS 縮放功能导致的。
`
const isChromeHighVersion = () => {
  const ua = navigator.userAgent.toLowerCase();
  const chromeIndex = ua.indexOf('chrome');
  if (chromeIndex > -1) {
    const version = ua.substring(chromeIndex + 7);
    const majorVersion = parseInt(version.split('.')[0], 10);
    return majorVersion >= 127;
  }
  return false;
};

 function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;

  // 原因：https://developer.chrome.google.cn/release-notes/128?hl=zh_tw
  // chrome在128大版本中停用了停用標準化 CSS 縮放功能
  if (!isChromeHighVersion()) {
    return;
  }

  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const m = detectZoom();
    // @ts-ignore: Unreachable code error
    const zoom = Number(document.body.style.zoom || 1);

    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom,
    );
    return newRect;
  };
}
`

**Comment by yxy297376376** [comment]
https://developer.chrome.google.cn/release-notes/128?hl=zh_tw  看起来是停用標準化 CSS 縮放功能这个改动导致的。
`const isChromeHighVersion = () => {
  const ua = navigator.userAgent.toLowerCase();
  const chromeIndex = ua.indexOf('chrome');
  if (chromeIndex > -1) {
    const version = ua.substring(chromeIndex + 7);
    const majorVersion = parseInt(version.split('.')[0], 10);
    return majorVersion >= 127;
  }
  return false;
};

export function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;

  // 原因：https://developer.chrome.google.cn/release-notes/128?hl=zh_tw
  // chrome在128大版本中停用了停用標準化 CSS 縮放功能
  if (!isChromeHighVersion()) {
    return;
  }

  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const m = detectZoom();
    // @ts-ignore: Unreachable code error
    const zoom = Number(document.body.style.zoom || 1);

    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom,
    );
    return newRect;
  };
}`

**Comment by yxy297376376** [comment]
[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw ](url) 看起来像128版本中停用標準化 CSS 縮放功能引发的。
`function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;
  const isChromeHighVersion = () => {
    const ua = navigator.userAgent.toLowerCase();
    const chromeIndex = ua.indexOf('chrome');
    if (chromeIndex > -1) {
      const version = ua.substring(chromeIndex + 7);
      const majorVersion = parseInt(version.split('.')[0], 10);
      return majorVersion > 127;
    }
    return false;
  };

  if(!isChromeHighVersion()){
    return;
  }

  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const zoom = Number(document.body.style.zoom || 1);

    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom,
    );
    return newRect;
  };
}`

**Comment by yxy297376376** [comment]
[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url)看起来像chrome 128版本的停用標準化 CSS 縮放功能引发的。


`
const isChromeHighVersion = () => {
  const ua = navigator.userAgent.toLowerCase();
  const chromeIndex = ua.indexOf('chrome');
  if (chromeIndex > -1) {
    const version = ua.substring(chromeIndex + 7);
    const majorVersion = parseInt(version.split('.')[0], 10);
    return majorVersion > 127;
  }
  return false;
};

`


`
export function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;

  if(!isChromeHighVersion()){
    return;
  }

  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const zoom = Number(document.body.style.zoom || 1);

    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom,
    );
    return newRect;
  };
}
`

**Comment by yxy297376376** [comment]
> 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀

看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)

**Comment by afc163** [comment]
<img width="969" alt="image" src="https://github.com/user-attachments/assets/5092837f-d3f7-4443-afc0-aace8af48ec7">

**Comment by triangle959** [comment]
看起来我们是在错误的路上再往前走了一些。
不过transform: scale()对于v2也会出现这个问题，看样子如果渲染在父节点上的left top计算逻辑是没有包含scale？

**Comment by studyisnotsimple** [comment]
transform:scale 缩放 依然会偏移

**Comment by studyisnotsimple** [comment]
> > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> 
> 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)

请问，应该在什么时机调用zoomPlugin呢  我在main.js中调用不起作用

**Comment by yxy297376376** [comment]
> > > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> > 
> > 
> > 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)
> 
> 请问，应该在什么时机调用zoomPlugin呢 我在main.js中调用不起作用
在设置zoom之后 接着调用就可以

**Comment by yxy297376376** [comment]
> > > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> > 
> > 
> > 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)
> 
> 请问，应该在什么时机调用zoomPlugin呢 我在main.js中调用不起作用


在设置zoom之后接着调用就可以

**Comment by testAdmin-dev** [comment]
> > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> 
> 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)

非常感谢，我用你的方法解决了我的问题

**Comment by studyisnotsimple** [comment]
> > > > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> > > 
> > > 
> > > 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)
> > 
> > 
> > 请问，应该在什么时机调用zoomPlugin呢 我在main.js中调用不起作用
> 
> 在设置zoom之后接着调用就可以

可以了，，谢谢大佬~

**Comment by Greyy-Y** [comment]
> > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> 
> 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)

感谢 ！

**Comment by zzefff** [comment]
> > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> 
> 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)

nice, worked for me

**Comment by liangpishu** [comment]
我是通过安装新的react-component/trigger，然后在package.json中添加
 "resolutions": {
	"rc-trigger": "npm:rc-compnent/trigger"
}
来替换antd 的rc-trigger，这对我有效

**Comment by wsypower** [comment]
> > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> 
> 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)

请问这个zoomPlugin的链接无法获取了，还有能找到这个 zoomPlugin插件的地方么

**Comment by wsypower** [comment]
@yxy297376376 请问这个zoomPlugin的链接无法获取了，还有能找到这个 zoomPlugin插件的地方么

**Comment by yxy297376376** [comment]
> @yxy297376376 请问这个zoomPlugin的链接无法获取了，还有能找到这个 zoomPlugin插件的地方么

`const isChromeHighVersion = () => {
  const ua = navigator.userAgent.toLowerCase();
  const chromeIndex = ua.indexOf("chrome");
  if (chromeIndex > -1) {
    const version = ua.substring(chromeIndex + 7);
    const majorVersion = parseInt(version.split(".")[0], 10);
    return majorVersion > 127;
  }
  return false;
};
export function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;
  if (!isChromeHighVersion()) {
    return;
  }
  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const zoom = Number(document.body.style.zoom) || 1;
    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom
    );
    return newRect;
  };
}
`

**Comment by yxy297376376** [comment]
> @yxy297376376 请问这个zoomPlugin的链接无法获取了，还有能找到这个 zoomPlugin插件的地方么

const isChromeHighVersion = () => {
  const ua = navigator.userAgent.toLowerCase();
  const chromeIndex = ua.indexOf("chrome");
  if (chromeIndex > -1) {
    const version = ua.substring(chromeIndex + 7);
    const majorVersion = parseInt(version.split(".")[0], 10);
    return majorVersion > 127;
  }
  return false;
};
export function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;
  if (!isChromeHighVersion()) {
    return;
  }
  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const zoom = Number(document.body.style.zoom) || 1;
    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom
    );
    return newRect;
  };
}

**Comment by yxy297376376** [comment]
```javascript
const isChromeHighVersion = () => {
  const ua = navigator.userAgent.toLowerCase();
  const chromeIndex = ua.indexOf("chrome");
  if (chromeIndex > -1) {
    const version = ua.substring(chromeIndex + 7);
    const majorVersion = parseInt(version.split(".")[0], 10);
    return majorVersion > 127;
  }
  return false;
};
export function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;
  if (!isChromeHighVersion()) {
    return;
  }
  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const zoom = Number(document.body.style.zoom) || 1;
    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom
    );
    return newRect;
  };
}

```

**Comment by yxy297376376** [comment]
> @yxy297376376 请问这个zoomPlugin的链接无法获取了，还有能找到这个 zoomPlugin插件的地方么

```javascript
const isChromeHighVersion = () => {
  const ua = navigator.userAgent.toLowerCase();
  const chromeIndex = ua.indexOf("chrome");
  if (chromeIndex > -1) {
    const version = ua.substring(chromeIndex + 7);
    const majorVersion = parseInt(version.split(".")[0], 10);
    return majorVersion > 127;
  }
  return false;
};
export function zoomPlugin() {
  const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;
  if (!isChromeHighVersion()) {
    return;
  }
  Element.prototype.getBoundingClientRect = function () {
    const rect = originalGetBoundingClientRect.call(this);
    const zoom = Number(document.body.style.zoom) || 1;
    const newRect = new DOMRect(
      rect.x / zoom,
      rect.y / zoom,
      rect.width / zoom,
      rect.height / zoom
    );
    return newRect;
  };
}

```

**Comment by ViktorMachine** [comment]
> > @yxy297376376 请问这个zoomPlugin的链接无法获取了，还有能找到这个 zoomPlugin插件的地方么
> 
> ```js
> const isChromeHighVersion = () => {
>   const ua = navigator.userAgent.toLowerCase();
>   const chromeIndex = ua.indexOf("chrome");
>   if (chromeIndex > -1) {
>     const version = ua.substring(chromeIndex + 7);
>     const majorVersion = parseInt(version.split(".")[0], 10);
>     return majorVersion > 127;
>   }
>   return false;
> };
> export function zoomPlugin() {
>   const originalGetBoundingClientRect = Element.prototype.getBoundingClientRect;
>   if (!isChromeHighVersion()) {
>     return;
>   }
>   Element.prototype.getBoundingClientRect = function () {
>     const rect = originalGetBoundingClientRect.call(this);
>     const zoom = Number(document.body.style.zoom) || 1;
>     const newRect = new DOMRect(
>       rect.x / zoom,
>       rect.y / zoom,
>       rect.width / zoom,
>       rect.height / zoom
>     );
>     return newRect;
>   };
> }
> ```

大佬 请收下我的膝盖

**Comment by SkrMiiKio** [comment]
因 Firefox 和 Chrome >128版本中停用了标准化 CSS `zoom` 功能，`getBoundingClientRect`, `getClientRects` 获取到的 `DOMRect` 实例不再计算所有父元素中的缩放层级，导致获取到的属性不准确。目前临时的解决方案是：
```js
/** [Polyfill] 修复 DOMRect 属性不受 zoom 变化的问题 */
if (CSS.supports('zoom', '1') && (/Firefox\//.test(navigator.userAgent) || /Chrome\/(\d+)/.exec(navigator.userAgent)?.[1] > 128)) {
  const $getBoundingClientRect = Element.prototype.getBoundingClientRect
  const $getClientRects = Element.prototype.getClientRects
  const getRealClientRect = function (el, rect) {
    let target = el, zoom = 1
    while (target) {
      zoom /= +getComputedStyle(target).zoom || 1
      target = target.parentElement
    }
    return zoom == 1 ? rect : new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom)
  }
  Element.prototype.getBoundingClientRect = function () {
    return getRealClientRect(this, $getBoundingClientRect.call(this))
  }
  Element.prototype.getClientRects = function () {
    let list = $getClientRects.call(this), data = []
    for (let i = 0, l = list.length; i < l; i++) data[i] = getRealClientRect(this, list[i])
    data.item = function (i) { return this[i] }
    return Object.setPrototypeOf(data, DOMRectList.prototype)
  }
}
```

**Comment by SkrMiiKio** [comment]
因 Firefox 和 Chrome >=128版本中停用了标准化 CSS `zoom` 功能，`getBoundingClientRect`, `getClientRects` 获取到的 `DOMRect` 实例不再计算所有父元素中的缩放层级，导致获取到的属性不准确。目前临时的解决方案是：
```js
/** [Polyfill] 修复 DOMRect 属性不受 zoom 变化的问题 */
if (CSS.supports('zoom', '1') && (/Firefox\//.test(navigator.userAgent) || /Chrome\/(\d+)/.exec(navigator.userAgent)?.[1] >= 128)) {
  const $getBoundingClientRect = Element.prototype.getBoundingClientRect
  const $getClientRects = Element.prototype.getClientRects
  const getRealZoom = function (el) {
    let target = el, zoom = 1
    while (target) {
      zoom /= +getComputedStyle(target).zoom || 1
      target = target.parentElement
    }
    return zoom
  }
  Element.prototype.getBoundingClientRect = function () {
    let rect = $getBoundingClientRect.call(this), zoom = getRealZoom(this)
    return zoom != 1 ? new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom) : rect
  }
  Element.prototype.getClientRects = function () {
    let list = $getClientRects.call(this), zoom = getRealZoom(this)
    if (zoom != 1) {
      list = [...list].map(rect => new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom))
      Object.defineProperty(list, 'item', { value(i) { return this[i] } })
      Object.setPrototypeOf(list, DOMRectList.prototype)
    }
    return list
  }
}
```

**Comment by SkrMiiKio** [comment]
因 Firefox 和 Chrome >=128版本中停用了标准化 CSS `zoom` 功能，`getBoundingClientRect`, `getClientRects` 获取到的 `DOMRect` 实例不再计算所有父元素中的缩放层级，导致获取到的属性不准确。目前临时的解决方案是：
```js
/** [Polyfill] 修复 DOMRect 属性不受 zoom 变化的问题 */
if (CSS.supports('zoom', '1') && (/Firefox\//.test(navigator.userAgent) || /Chrome\/(\d+)/.exec(navigator.userAgent)?.[1] >= 128)) {
  const _getBoundingClientRect = Element.prototype.getBoundingClientRect
  const _getClientRects = Element.prototype.getClientRects
  const getRealZoom = function (el) {
    let target = el, zoom = 1
    while (target) {
      zoom /= +getComputedStyle(target).zoom || 1
      target = target.parentElement
    }
    return zoom
  }
  Element.prototype.getBoundingClientRect = function () {
    let rect = _getBoundingClientRect.call(this), zoom = getRealZoom(this)
    return zoom != 1 ? new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom) : rect
  }
  Element.prototype.getClientRects = function () {
    let list = _getClientRects.call(this), zoom = getRealZoom(this)
    if (zoom != 1) {
      list = [...list].map(rect => new DOMRect(rect.x * zoom, rect.y * zoom, rect.width * zoom, rect.height * zoom))
      Object.defineProperty(list, 'item', { value(i) { return this[i] } })
      Object.setPrototypeOf(list, DOMRectList.prototype)
    }
    return list
  }
}
```

**Comment by nancy12138** [comment]
你是怎么调用的？我使用了这个之后没有效果，还是偏移

**Comment by liangpishu** [comment]
> > 我也是body设置zoom这个怎么解决antdesign组件偏移的问题呀
> 
> 看起来是[https://developer.chrome.google.cn/release-notes/128?hl=zh_tw](url) chrome 128版本中停用標準化 CSS 縮放功能造成的。 目前我是这么解决的[http://cdn.boyxy.cn/js/zoomPlugin.js](url)

目前发现调用zoomPlugin之后，slider组件会受影响导致选中位置发生偏移
