### ISSUE TITLE
a link color doesn't work

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#50533]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-k3yhnv?file=demo.tsx,package.json)

### Steps to reproduce

View the demo.

### What is expected?

![image](https://github.com/user-attachments/assets/bfa12ce7-ed65-49b7-b306-cb73185713f7)

### What is actually happening?

![image](https://github.com/user-attachments/assets/6bdd2ab7-1f26-4325-b8ed-18ae8c711403)

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome 120.0.6099.225 |

**Comment by Meetacoo** [comment]
+1

**Comment by zhipenglin** [comment]
<img width="252" alt="C167C231-56A8-42c3-904C-D505D6BD02F3" src="https://github.com/user-attachments/assets/b23e9f85-54dc-4757-b8f9-a5af04642529">

这一段样式不知道为什么没有了，而且antd我们是固定版本的，版本也没有升级还能出问题

**Comment by afc163** [comment]
antd 的底层依赖 [stylis](https://github.com/thysultan/stylis) 发布了新版本干挂了，我们正在排查问题。

**Comment by arvinxx** [comment]
@afc163 所以解决方案是啥？锁 stylis 版本吗？ 

refs: https://github.com/lobehub/lobe-chat/issues/3544

**Comment by keer6** [comment]
> <img alt="C167C231-56A8-42c3-904C-D505D6BD02F3" width="252" src="https://private-user-images.githubusercontent.com/8214855/360319721-b23e9f85-54dc-4757-b8f9-a5af04642529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTY4MTYsIm5iZiI6MTcyNDMxNjUxNiwicGF0aCI6Ii84MjE0ODU1LzM2MDMxOTcyMS1iMjNlOWY4NS01NGRjLTQ3NTctYjhmOS1hNWFmMDQ2NDI1MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDg0ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTcwZmEzZmU4NjMxY2ZkZTIwNWRiZTgzNGVkNWNjZjQwOGFkMjhmMDEyNGU4ODM3ODNmZGNhNzllMjUwZWIyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YhtZLK8RJyjUdn7BvrA5pvdw2UEfiNDu6HY_pCGLSBM">
> 这一段样式不知道为什么没有了，而且antd我们是固定版本的，版本也没有升级还能出问题

你看看你有提交lock文件吗？然后再去排查一些Jenkins脚本，我今天也碰到这个问题，才发现运维在Jenkins脚本加了
移除lock 的命令。。。麻了
![企业微信截图_17243174027460](https://github.com/user-attachments/assets/703addf8-10c0-4958-9835-fbdbf6bfda79)

**Comment by zhipenglin** [comment]
> > <img alt="C167C231-56A8-42c3-904C-D505D6BD02F3" width="252" src="https://private-user-images.githubusercontent.com/8214855/360319721-b23e9f85-54dc-4757-b8f9-a5af04642529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTY4MTYsIm5iZiI6MTcyNDMxNjUxNiwicGF0aCI6Ii84MjE0ODU1LzM2MDMxOTcyMS1iMjNlOWY4NS01NGRjLTQ3NTctYjhmOS1hNWFmMDQ2NDI1MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDg0ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTcwZmEzZmU4NjMxY2ZkZTIwNWRiZTgzNGVkNWNjZjQwOGFkMjhmMDEyNGU4ODM3ODNmZGNhNzllMjUwZWIyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YhtZLK8RJyjUdn7BvrA5pvdw2UEfiNDu6HY_pCGLSBM">
> > 这一段样式不知道为什么没有了，而且antd我们是固定版本的，版本也没有升级还能出问题
> 
> 你看看你有提交lock文件吗？然后再去排查一些Jenkins脚本，我今天也碰到这个问题，才发现运维在Jenkins脚本加了 移除lock 的命令。。。麻了 ![企业微信截图_17243174027460](https://private-user-images.githubusercontent.com/33250972/360369827-703addf8-10c0-4958-9835-fbdbf6bfda79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTkwMzEsIm5iZiI6MTcyNDMxODczMSwicGF0aCI6Ii8zMzI1MDk3Mi8zNjAzNjk4MjctNzAzYWRkZjgtMTBjMC00OTU4LTk4MzUtZmJkYmY2YmZkYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5Nzc3MjYzZWY4ZjY4OGQyZWJiODlkNTc2Y2ZkYzBjZTRjNjc5N2RlMWE3NTNmZWIyOWQyOWU1YWZiNzExMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SJBwTOqENMID2fRW5yWd26AwGPi-tdNSTg-aXw5KZJY)

哎，我们的项目都没有加lock文件，也是麻了，暂时自己加了一段样式fix了一下

**Comment by Meetacoo** [comment]
> @afc163 所以解决方案是啥？锁 stylis 版本吗？
> 
> refs: [lobehub/lobe-chat#3544](https://github.com/lobehub/lobe-chat/issues/3544)

自己加了样式做了个覆盖

**Comment by keer6** [comment]
> > > <img alt="C167C231-56A8-42c3-904C-D505D6BD02F3" width="252" src="https://private-user-images.githubusercontent.com/8214855/360319721-b23e9f85-54dc-4757-b8f9-a5af04642529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTY4MTYsIm5iZiI6MTcyNDMxNjUxNiwicGF0aCI6Ii84MjE0ODU1LzM2MDMxOTcyMS1iMjNlOWY4NS01NGRjLTQ3NTctYjhmOS1hNWFmMDQ2NDI1MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDg0ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTcwZmEzZmU4NjMxY2ZkZTIwNWRiZTgzNGVkNWNjZjQwOGFkMjhmMDEyNGU4ODM3ODNmZGNhNzllMjUwZWIyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YhtZLK8RJyjUdn7BvrA5pvdw2UEfiNDu6HY_pCGLSBM">
> > > 这一段样式不知道为什么没有了，而且antd我们是固定版本的，版本也没有升级还能出问题
> > 
> > 
> > 你看看你有提交lock文件吗？然后再去排查一些Jenkins脚本，我今天也碰到这个问题，才发现运维在Jenkins脚本加了 移除lock 的命令。。。麻了 ![企业微信截图_17243174027460](https://private-user-images.githubusercontent.com/33250972/360369827-703addf8-10c0-4958-9835-fbdbf6bfda79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTkwMzEsIm5iZiI6MTcyNDMxODczMSwicGF0aCI6Ii8zMzI1MDk3Mi8zNjAzNjk4MjctNzAzYWRkZjgtMTBjMC00OTU4LTk4MzUtZmJkYmY2YmZkYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5Nzc3MjYzZWY4ZjY4OGQyZWJiODlkNTc2Y2ZkYzBjZTRjNjc5N2RlMWE3NTNmZWIyOWQyOWU1YWZiNzExMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SJBwTOqENMID2fRW5yWd26AwGPi-tdNSTg-aXw5KZJY)
> 
> 哎，我们的项目都没有加lock文件，也是麻了，暂时自己加了一段样式fix了一下

不加lock是大忌啊，你前面说你们都有锁antd 版本，但是没有lock的话，antd的依赖版本锁不住啊。等生产出个事故不就提桶了

**Comment by zhipenglin** [comment]
> 不加lock是大忌啊，你前面说你们都有锁antd 版本，但是没有lock的话，antd的依赖版本锁不住啊。等生产出个事故不就提桶了

用的ci/cd每次随机一个服务器执行任务，偷了个懒，没有设置lock文件的缓存

**Comment by MadCcc** [comment]
@ant-design/cssinjs@1.21.1 已经修复该问题

**Comment by manbuxinghe** [comment]
> > > > <img alt="C167C231-56A8-42c3-904C-D505D6BD02F3" width="290.25" height="21" src="https://private-user-images.githubusercontent.com/8214855/360319721-b23e9f85-54dc-4757-b8f9-a5af04642529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTY4MTYsIm5iZiI6MTcyNDMxNjUxNiwicGF0aCI6Ii84MjE0ODU1LzM2MDMxOTcyMS1iMjNlOWY4NS01NGRjLTQ3NTctYjhmOS1hNWFmMDQ2NDI1MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDg0ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTcwZmEzZmU4NjMxY2ZkZTIwNWRiZTgzNGVkNWNjZjQwOGFkMjhmMDEyNGU4ODM3ODNmZGNhNzllMjUwZWIyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YhtZLK8RJyjUdn7BvrA5pvdw2UEfiNDu6HY_pCGLSBM">
> > > > 这一段样式不知道为什么没有了，而且antd我们是固定版本的，版本也没有升级还能出问题
> > > 
> > > 
> > > 你看看你有提交lock文件吗？然后再去排查一些Jenkins脚本，我今天也碰到这个问题，才发现运维在Jenkins脚本加了 移除lock 的命令。。。麻了 <img alt="企业微信截图_17243174027460" width="211.46875" height="21" src="https://private-user-images.githubusercontent.com/33250972/360369827-703addf8-10c0-4958-9835-fbdbf6bfda79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTkwMzEsIm5iZiI6MTcyNDMxODczMSwicGF0aCI6Ii8zMzI1MDk3Mi8zNjAzNjk4MjctNzAzYWRkZjgtMTBjMC00OTU4LTk4MzUtZmJkYmY2YmZkYTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5Nzc3MjYzZWY4ZjY4OGQyZWJiODlkNTc2Y2ZkYzBjZTRjNjc5N2RlMWE3NTNmZWIyOWQyOWU1YWZiNzExMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SJBwTOqENMID2fRW5yWd26AwGPi-tdNSTg-aXw5KZJY">
> > 
> > 
> > 哎，我们的项目都没有加lock文件，也是麻了，暂时自己加了一段样式fix了一下
> 
> 不加lock是大忌啊，你前面说你们都有锁antd 版本，但是没有lock的话，antd的依赖版本锁不住啊。等生产出个事故不就提桶了

大佬们，问个问题，我项目package.json写死了"antd": "5.15.3",在npm install 的时候也会更新antd吗？为什么这次bug会影响到我们项目呢？

**Comment by keer6** [comment]
> 大佬们，问个问题，我项目package.json写死了"antd": "5.15.3",在npm install 的时候也会更新antd吗？为什么这次bug会影响到我们项目呢？

会，因为antd 也依赖了别的第三方库，而antd 作为一个开源库是不会去锁定版本的，所有没有lock文件。这样你每次安装antd ，它所依赖的第三方都会保持最新版本。这也是为什么本次更新，没有lock文件的项目都会收到波及的问题。
当然，这个问题并不是antd 的问题。所以强烈建议项目内添加lock文件，以免产生不必要的更新所带来的麻烦。
这样说你明白了吗？
