### ISSUE TITLE
table 组件 ref调用 scrollTo，参数top为0的时候被忽略

### ISSUE THREAD

**Issue by Carnia** [ant-design/ant-design#50547]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

# 例子
```html
      <Table
        ref={tableContainerRef}
      >
```
## 调用`tableContainerRef.current.scrollTo({top: 0})`不生效，排查到源码是做了如下处理：
```js
     scrollTo: function scrollTo2(config) {
        var _scrollBodyRef$curren3;
        if (scrollBodyRef.current instanceof HTMLElement) {
          var index3 = config.index, top = config.top, key = config.key;
         // 问题出在这里，number 0 会被视为false
          if (top) {
            var _scrollBodyRef$curren;
            (_scrollBodyRef$curren = scrollBodyRef.current) === null || _scrollBodyRef$curren === void 0 || _scrollBodyRef$curren.scrollTo({
              top
            });
          } else {
         .... 省略
           }
      }
```

### What is expected?

tableContainerRef.current.scrollTo({top: 0}) 生效，表格内容滚到顶部

### What is actually happening?

tableContainerRef.current.scrollTo({top: 0}) 不生效，表格不滚动

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | react |
| System | 所有 |
| Browser | 所有 |

**Comment by li-jia-nan** [comment]
已经排查到这个地步了，来个 PR？

**Comment by Carnia** [comment]
> 既然已经排查到这个地步了，来个 PR？

找不到scrollTo这个源码在哪，能力有限...

**Comment by Ali-ovo** [comment]
> > 既然已经排查到这个地步了，来个 PR？
> 
> 找不到scrollTo这个源码在哪，能力有限...

https://github.com/react-component/table 应该是这个 repo

**Comment by li-jia-nan** [comment]
- https://github.com/react-component/table/pull/1182
