### ISSUE TITLE
DatePicker焦点onBlur和onFocus问题

### ISSUE THREAD

**Issue by kfinder** [ant-design/ant-design#50552]
### What problem does this feature solve?

在4.24.12中鼠标点击输入框onFocus触发一次，通过日期面板选择日期后焦点回到输入框中，不会触发onBlur
在5.20.2中鼠标点击输入框onFocus触发一次，点击日期面板选择日期时触发一次onBlur并立即触发一次onFocus，选择完成日期回填后再次触发一次onFocus，然后焦点立即跳走并再次触发onBlur

### What does the proposed API look like?

4.24.12的方式是合理的，5.20.2onFocus和onBlur的触发不合理

**Comment by kfinder** [comment]
import React from 'react';
import './index.css';
import type { DatePickerProps } from 'antd';
import { DatePicker, Space } from 'antd';

const onChange: DatePickerProps['onChange'] = (date, dateString) => {
  console.log(date, dateString);
};

const handleFocus = () => {
  console.log('handleFocus', 'handleFocus');
};

const handleBlur = () => {
  console.log('handleBlur', 'handleBlur');
};

const App: React.FC = () => (
  <Space direction="vertical">
    <DatePicker onChange={onChange} onFocus={handleFocus} onBlur={handleBlur} />
    <DatePicker onChange={onChange} onFocus={handleFocus} onBlur={handleBlur} picker="week" />
    <DatePicker onChange={onChange} onFocus={handleFocus} onBlur={handleBlur} picker="month" />
    <DatePicker onChange={onChange} onFocus={handleFocus} onBlur={handleBlur} picker="quarter" />
    <DatePicker onChange={onChange} onFocus={handleFocus} onBlur={handleBlur} picker="year" />
  </Space>
);

export default App;

**Comment by kfinder** [comment]
https://github.com/user-attachments/assets/708abf5e-a221-4942-8512-76935ef0ebcf

**Comment by lizhengxing2024** [comment]
@kfinder 哇，同问

**Comment by xukhxukh** [comment]
同问
