### ISSUE TITLE
Cascader.Panel - Proposal to modify the behaviour of onChange method to return only the checked options in multiple mode

### ISSUE THREAD

**Issue by saitejas** [ant-design/ant-design#50576]
### What problem does this feature solve?

Currently, we have a hierarchy where there is only child per parent at all levels. For eg: India -> Karnataka -> Bangalore. Selecting Bangalore gives the value of India instead of Bangalore since there is only one child per parent. This is very critical as we are using it for access management where we try to give access only to people over Bangalore but it gives access to entire India instead. So proposing to add another prop to modify the behaviour of onChange where it will return only the info of the checked options.

### What does the proposed API look like?

We can have a prop called onChangeStrategy with two modes 'DEFAULT' & 'ONLY_CHECKED' where DEFAULT will follow the existing behaviour and ONLY_CHECKED will return only the info of the checked options in onChange method

**Comment by MadCcc** [comment]
Try `showCheckedStrategy={Cascader.SHOW_CHILD}`

**Comment by saitejas** [comment]
No, even when I use SHOW_CHILD, I'm not able to find which is the actual selected one since it is returning the entire hierarchy. I want to have the info of only the checked options.

**Comment by saitejas** [comment]
@MadCcc
