### ISSUE TITLE
Is it possible to sort Table by more than 1 column?

### ISSUE THREAD

**Issue by Tsury** [ant-design/ant-design#5057]
I want to have primary sort by NAME and secondary sort by DATE, so that all the entries will be sorted by NAME, but keep entries with the same NAME sorted by DATE.

**Comment by afc163** [comment]
Sorry, multiple column sort is too complex and hard to understand. I don't think we gone to provide this feature, You can customize the column header.

**Comment by abonec** [comment]
@afc163 maybe you add multiple sort just to `onChange` method? If multiple sort option is set user can select multiple columns to sort and `onChange` method in `sorter` argument received array or sorters.
It is not too hard to implement as implement sorters that actually sorts data but it can be very useful.

**Comment by 19majkel94** [comment]
> Sorry, multiple column sort is too complex and hard to understand. 

I can't agree with that. Multiple sort is easy to understand, if the first field comparison gives equality, then the second comparison takes place and decide the order of the items with the same previous field value.

Also it is really easy to implement:
```js
var obj = [
  {
    alfa: 1,
    beta: 2,
    gamma: 7
  },
  {
    alfa: 3,
    beta: 5,
    gamma: 3
  },
  {
    alfa: 1,
    beta: 2,
    gamma: 1
  },
  {
    alfa: 1,
    beta: 2,
    gamma: 3
  },
];

const alfaComp = (a, b) => a.alfa - b.alfa;
const betaComp = (a, b) => a.beta - b.beta;
const gammaComp = (a, b) => a.gamma - b.gamma;

function multipleSort(compFunctions) {
    return function (a, b) {
        for (const func of compFunctions) {
            const result = func(a, b);
            if (result !== 0) {
                return result;
            }
        }
    }
}

var arr = obj.sort(multipleSort([alfaComp, betaComp, gammaComp]));

/*
logs:
​​​​​[ { alfa: 1, beta: 2, gamma: 1 },​​​​​
​​​​​  { alfa: 1, beta: 2, gamma: 3 },​​​​​
​​​​​  { alfa: 1, beta: 2, gamma: 7 },​​​​​
​​​​​  { alfa: 3, beta: 5, gamma: 3 } ]​​​​​
*/
```
So all that devs need to do is to define the priority of the sortable columns so the data will be first sorted eg. by name, second by age if multiple sorts are selected.

**Comment by Beej126** [comment]
Telerik/Progress "KendoReact" datatable provides this very cleanly: https://www.telerik.com/kendo-react-ui/components/grid/sorting/#toc-customize-sorting

Their API provides a "SortDescriptor" object with expected properties (fieldname and direction) and then simply manages an array of those... they provide helper functions that accept this array as well as even the more complicated scenario of multiple FILTERS in addition to sort.

I will say the ant-d UX for filter direction is preferable in my personal opinion :)

**Comment by matyasfodor** [comment]
Yes, this would be a really useful feature.

**Comment by ColinCee** [comment]
Added since v4 - https://github.com/ant-design/ant-design/issues/10946#issuecomment-598580948
