### ISSUE TITLE
gradient color pickers gives error msg with certain behaviour on [Ant Design Website]

### ISSUE THREAD

**Issue by DesertGanzo** [ant-design/ant-design#50589]
### Reproduction link

[https://www.youtube.com/watch?v=_ghYEb7vZns&feature=youtu.be](https://www.youtube.com/watch?v=_ghYEb7vZns&feature=youtu.be)

### Steps to reproduce

open gradient picker
change all pickers but the one above then the one above somwhat slowly it will show error
i recorded a full reproduction of the error unlisted on my youtube here
https://www.youtube.com/watch?v=_ghYEb7vZns&feature=youtu.be
sorry for the breathing sounds

### What is expected?

fixing it if possible ;)

### What is actually happening?

react error showing on website

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | react |
| System | windows 10 |
| Browser | chrome |

---
iam new to react so i was exploring componenets that could enhance my website .. was playing around with componenets

**Comment by MadCcc** [comment]
Is there any stable way to reproduce?

**Comment by afc163** [comment]
Cannot reproduce it.
