### ISSUE TITLE
token 配置不同，样式丢失

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#50587]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-qcufgv?file=demo.tsx)

### Steps to reproduce

查看 demo

### What is expected?

文字红色

### What is actually happening?

没有样式

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by Wxh16144** [comment]
<img width="997" alt="image" src="https://github.com/user-attachments/assets/9a127041-d305-40a7-a8ba-5257a8358116">

CP 组件设置了 `theme` 会多套一个 token 的 provider。 每个 CP 的 css hashid 貌似都会不一样

你这个示例链接需要把 modal 设置一个 getContainer 属性，插入到当前容器组件中。

然后编写的 css 也需要注意选择器权重。 （如图）

<img width="565" alt="image" src="https://github.com/user-attachments/assets/2e62d2c6-fffe-4267-a906-5c65e55bdf79">

**Comment by Wxh16144** [comment]
那唯一的方法 应该就关闭 hash 这个东西

**Comment by crazyair** [comment]
> 那唯一的方法 应该就关闭 hash 这个东西

不清楚，antd 的就可以多次嵌套，antd 的 style 为什么没问题？

**Comment by zombieJ** [comment]
`theme` 和 `theme` 之间是隔离的，自然不同的 `theme` 之间样式不会共享。这个是预期行为。

**Comment by crazyair** [comment]
不对啊，我这个跟 antd 的不是一个，我这个是自己生成的

**Comment by crazyair** [comment]
> 不对啊，我这个跟 antd 的不是一个，我这个是自己生成的

我自己生成的 style，应该能用的，但是被 ConfigProvider 包裹 2 次就失效了

**Comment by zombieJ** [comment]
> 不对啊，我这个跟 antd 的不是一个，我这个是自己生成的

你用的就是 antd 的 `token`:

```tsx
const { useToken } = theme;

useStyleRegister(
  { theme, token, hashId, path: [component, prefixCls, iconPrefixCls] },
```

自己完全新建就不会被影响，你复用了它所以 useToken 拿到的总是跟着 antd 的 scope 走的。

**Comment by crazyair** [comment]
> > 不对啊，我这个跟 antd 的不是一个，我这个是自己生成的
> 
> 你用的就是 antd 的 `token`:
> 
> ```tsx
> const { useToken } = theme;
> 
> useStyleRegister(
>   { theme, token, hashId, path: [component, prefixCls, iconPrefixCls] },
> ```
> 
> 自己完全新建就不会被影响，你复用了它所以 useToken 拿到的总是跟着 antd 的 scope 走的。

为什么 antd 内置的样式就不会因为包了多个 CP 就无样式呢？

**Comment by zombieJ** [comment]
每层新的 `token` 都会创建一套样式，你的代码只调用了一次  `useStyle`，自然自己就只创建了一个了~

**Comment by crazyair** [comment]
知道了，可以这样改，里面的也加上 hash 就可以有样式了

```tsx
<ConfigProvider theme={{ token: { fontSize: 14 } }}>
    <Modal title="aaa" open={open} destroyOnClose onCancel={() => setOpen(false)}>
        <Button className={`${hashId} demo`}>aaa</Button>
    </Modal>
</ConfigProvider>
```
