### ISSUE TITLE
Date picker fails to allow manual selection of immediate enabled month when a few previous months are disabled antd@5.18.2v onwards

### ISSUE THREAD

**Issue by vimala-siravi** [ant-design/ant-design#50585]
![Datepicker_issue](https://github.com/user-attachments/assets/5135a8c2-f8fb-43a5-957d-0588152a7b6a)
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-xs7ktm?file=demo.tsx)

### Steps to reproduce

1. Click on date picker
2. Try to select the very next month after the disabled ones

### What is expected?

Should be able to select the very next month after the disabled ones

### What is actually happening?

We are unable to select the very next month after the disabled ones

| Environment | Info |
| --- | --- |
| antd | 5.18.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | 127.0.6533.122 |

---
This isn't working above 5.11.0v and above versions

**Comment by zombieJ** [comment]
When you use in MonthPicker, should not check validation in day level. MonthPicker will give any date in the month for `disabledDate` to check.

```diff
--  return current && current < dayjs().endOf('day');
++  return current && current < dayjs().endOf('month');
```

https://stackblitz.com/edit/antd-reproduce-5x-fltez8?file=demo.tsx
