### ISSUE TITLE
Shouldn't the Select component display an arrow up when option list is visible?

### ISSUE THREAD

**Issue by stefann01** [ant-design/ant-design#50593]
### Reproduction link

[https://ant.design/components/select](https://ant.design/components/select)

### Steps to reproduce

Open any simple select on your own docs page. 

### What is expected?

I suppose the select component should display an arrow up when it is opened and an arrow down when it is closed. 
Probably there should also be props for suffixIcon in both states. 

### What is actually happening?

Arrow is always arrow down

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

---
Whoever uses it can indeed handle the icon change themselves through the suffixIcon prop but that should be the component responsibility.

**Comment by afc163** [comment]
> Arrow is always arrow down

It is by designed defaultly, you could customize suffixIcon to accomplish this.

**Comment by stefann01** [comment]
> > Arrow is always arrow down
> 
> It is by designed defaultly, you could customize suffixIcon to accomplish this.

Yes, it is possible to customize via suffixIcon, but requires extra logic. I believe that logic should be inside the component as it is relevant to it.
