### ISSUE TITLE
spin样式问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#5059]
原本我antd版本是1.11的，升级到2.7后发现spin加载的时候只要页面一长就得下拉才能看得到，是因为升级到在‘ant-spin-nested-loading’加了相对定位，然后里面的‘ant-spin ant-spin-spinning’又设置了百分之百高度，导致高度以内容高度为准，内容多高spin高度就多高，只要内容一多就得下拉才能看得到，去掉‘ant-spin-nested-loading’的相对定位就发现无论内容多长加载图标就是一直定位在中间
![image](https://cloud.githubusercontent.com/assets/19485727/23346548/0dcb2d84-fcd6-11e6-9c1a-cd760418eb18.png)
![image](https://cloud.githubusercontent.com/assets/19485727/23346564/3693c0d2-fcd6-11e6-82bc-bcb8fa5a201b.png)

**Comment by aw6658913** [comment]
补充一张去掉'ant-spin- nested-loading'的相对定位，这时候图标就能看得到了
![image](https://cloud.githubusercontent.com/assets/19485727/23346671/4dd3f202-fcd7-11e6-8fd3-80c128f95ec2.png)

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by aw6658913** [comment]
在线演示如下，我需要下拉才能看到加载图标，实际上我们看到的加载状态图标不是应该一直在可见的页面中间么:
http://codepen.io/anon/pen/dvoNQj?editors=0010

**Comment by afc163** [comment]
之前有类似的问题，我想想怎么优化。

我上面的意思是 1.x 就是这样的。

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/4722 , close it now.

**Comment by aw6658913** [comment]
恩，应该是1.x的时候我没使用大数据发现这个问题

**Comment by afc163** [comment]
可以先这样写：http://codepen.io/anon/pen/ggxjor?editors=0010

**Comment by aw6658913** [comment]
想来想去好像也没啥更好的方法~页面太多也不好一个个这样改，我还是先重置'ant-spin- nested-loading'的样式，以body作为相对定位元素，先保证页面初始状态是能看到加载的
