### ISSUE TITLE
Date-Picker配置了components以及onOpenChange和open后，焦点问题

### ISSUE THREAD

**Issue by kfinder** [ant-design/ant-design#50603]
### What problem does this feature solve?

Date-Picker配置了components以及onOpenChange和open后，点击输入框弹出下拉日期框后输入框的焦点失去

### What does the proposed API look like?

不应该失去焦点

代码：
https://stackblitz.com/edit/react-4vm8tg?file=demo.tsx

演示

https://github.com/user-attachments/assets/520aff17-df35-411c-8d91-31761991c0e0

**Comment by afc163** [comment]
See https://stackblitz.com/edit/react-4vm8tg-8fmjzo?file=demo.tsx
