### ISSUE TITLE
Integrating with react-boilerplate

### ISSUE THREAD

**Issue by inev** [ant-design/ant-design#5060]
#### Environment(required)

- antd version: latest
- OS and its version: Ubuntu 16.04
- Browser and its version: Chrome, latest

#### What did you do? Please provide steps to re-produce your problem.

- Download and install [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/)
- Download and install `antd`
- Add the following to the dev webpack config to make it work:
```
babelQuery: {
    plugins: [["import", { libraryName: "antd", style: true }]],
  },
```
- Add the same to production config. Use `npm build` to build production assets. 

#### What do you expected?

 - Expect components to work normally, like in dev environment.

#### What happen?

I get errors like `ReferenceError: Menu is not defined`

#### Re-producible online demo

I cant reproduce this online because it seems like a build issue.

**Comment by afc163** [comment]
Try https://github.com/afc163/react-boilerplate

https://github.com/afc163/react-boilerplate/commit/61ec8a19df0fcb56d407b795cb6c87141e0e14a7

**Comment by timbrand** [comment]
@afc163 I'm having the exact same issue. I've tried the repo you link to and that works, but when adding something like a dropdown with a Menu, and then building and starting the production version, you get the "Menu is not defined" error.

**Comment by timbrand** [comment]
It seems to be an issue with the Menu component only (for now). 
When I replace the use of Menu with the internally used RcMenu, it's working fine in the production-environment too.

Menu code I used:
```
<RcMenu>
  <Item>
    <span>Test</span>
  </Item>
</RcMenu>
```

**Comment by afc163** [comment]
It works!

<img width="832" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23459772/dea10c7a-febc-11e6-9f72-07b975ce03c4.png">

**Comment by afc163** [comment]
<img width="645" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23460044/10617a0a-febe-11e6-8908-baa552291320.png">

It works on both Dropdown and Menu.

**Comment by timbrand** [comment]
I've tried your commit, but it only works in debug-build.
try to run: 
```npm run build && npm run start:prod```

**Comment by afc163** [comment]
I see it, that is strange. Menu and Menu.Item is not undefined, actually.

<img width="1102" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23460611/2ac2c478-fec1-11e6-8847-9d22aff59118.png">

**Comment by afc163** [comment]
I found a workaround but I don't know why yet. The dot can't existed in JSX expression for production environment of react-boilerplate.

```diff
+ const MenuItem = Menu.Item;

...

<Menu>
- <Menu.Item></Menu.Item>
+ <MenuItem></MenuItem>
</Menu>
```

**Comment by timbrand** [comment]
I can confirm this workaround works. Thanks for providing this workaround!

**Comment by afc163** [comment]
<img width="375" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23461961/f6ecc35a-fec6-11e6-8929-9194437dcf71.png">

The `Menu.Item` inside JSX is not compressed.

**Comment by afc163** [comment]
https://github.com/babel/babel/issues/3728

**Comment by afc163** [comment]
Remove this line https://github.com/afc163/react-boilerplate/blob/3153341152b160017bb1966a807786453e649ae8/package.json#L72 and it works fine.

**Comment by danielbiloglav** [comment]
I had the same issue and resolved it by removing the plugin transform-react-inline-elements as @afc163 suggests

**Comment by afc163** [comment]
I think it a babel-plugin-transform-react-inline-elements issue rather than antd's.

**Comment by kamalbennani** [comment]
I am having the same problem, does any one have a real solution to it.

**Comment by sleva13** [comment]
@kamalbennani you use [react-optimize](https://github.com/thejameskyle/babel-react-optimize) which contains [transform-react-inline-elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-inline-elements) and other plugins. I replaced react-optimize with plugins in it except [transform-react-constant-elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements) and it works for me.

**Comment by xxryan1234** [comment]
I am getting an error everytime I run `npm run build` with antd

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets:
  0.82e471b3aae749b299c1.chunk.js (536 kB)
```

Is there something I should do before I add antd with react-boilerplate?

**Comment by evanhunt** [comment]
@
