### ISSUE TITLE
Tooltip 的 max-width 能不能通过属性自定义，虽然可以css覆盖，感觉不是那么优雅；或者props直接指定，没有最大宽度限制。

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50601]
### What problem does this feature solve?

就像 Popover 一样，内容是默认自适应的。
我甚至感觉可以去除 max-width 的限制，需要限制的话，用户自己定义css就行。

**Comment by Wxh16144** [comment]
> 虽然可以css覆盖，...或者props直接指定

个人觉得用 css 覆盖比 props 优雅，props 和 内联 style 类似操作，其他人无法用 css 覆盖（加权重）。

> 没有最大宽度限制。

那直接用 popover 组件代替 tooltips 如何？

**Comment by afc163** [comment]
没有最大宽度限制就会出现一行超长的 Tooltip，默认体验不是特别好。还是建议自行处理一下，建议用 ConfigProvider 来覆盖 token。

**Comment by kwooshung** [comment]
@tooltip-max-width 嘿，我竟然没发现它
