### ISSUE TITLE
ie9下好多特性都没法用，麻烦文档上别写支持IE9以上好么

### ISSUE THREAD

**Issue by yuwenxing** [ant-design/ant-design#5061]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by ImJoeHs** [comment]
你这个。。除了啥问题爆出来啊，发这么个东西是啥意思？

**Comment by afc163** [comment]
支持 IE9 的意思不是 IE9 下毫无问题，而是 IE9 的问题我们会排查和修复。

另外，提 issue 最好言之有物，单纯吐槽并不能得到帮助。
