### ISSUE TITLE
Table 组件在鸿蒙系统下显示异常—— 固定列背景色丢失，scroll滚动头失效，分页样式错乱，长表格左滑内容重叠

### ISSUE THREAD

**Issue by 123vera** [ant-design/ant-design#50610]
### Reproduction link

[https://wecom.test.avatr.com/drivingboard/dashboard/salesCoreMonitor](https://wecom.test.avatr.com/drivingboard/dashboard/salesCoreMonitor)

### Steps to reproduce

直接查看

### What is expected?

Table组件 兼容鸿蒙系统，显示正常

### What is actually happening?

显示错乱

| Environment | Info |
| --- | --- |
| antd | 5.16.2 |
| React | react |
| System | 无 |
| Browser | 鸿蒙系统 内嵌app的H5 |

**Comment by Wxh16144** [comment]
什么？鸿蒙系统，两眼一黑😨

**Comment by zombieJ** [comment]
你的重现里没看到 antd 的 Table，搞一个 stackbliz 看看？
