### ISSUE TITLE
CSS build for SSR shows warning

### ISSUE THREAD

**Issue by hassoubeat** [ant-design/ant-design#50611]
### Reproduction link

[https://ant.design/docs/blog/extract-ssr#static-extract-style](https://ant.design/docs/blog/extract-ssr#static-extract-style)

### Steps to reproduce

https://ant.design/docs/blog/extract-ssr#static-extract-style

### What is expected?

The warning disappears.

### What is actually happening?

A warning is displayed.

For details, please refer to the link.

https://github.com/ant-design/static-style-extract/issues/15

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18.2.0 |
| System | MacOS 14.2.1 |
| Browser | none |

---
I had written an issue for static-style-extract, but since there has been no response for a long time, I will write an issue here as well.

https://github.com/ant-design/static-style-extract/issues/15

**Comment by zombieJ** [comment]
Thx for feedback. extract use template for generation. Seems some component should not be empty in use.
