### ISSUE TITLE
Table组件分组展示数据时，全选，再选择每个组中的子项，无法取消勾选

### ISSUE THREAD

**Issue by catmiao8** [ant-design/ant-design#50621]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-m7by8s-frfdtz?file=demo.tsx)

### Steps to reproduce

第一个问题：
1、选择全选
2、选择某个分组下面的某一项，但该项无法取消选择
第二个问题：
1、选择全选
2、选择某个分组，取消选择
3、再点击该分组下的选项，选项和父选项不再关联

### What is expected?

1、当开始选择全选后，分组下面的某一项可以被取消选择
2、选择全选，选择某个分组，取消选择，再点击该分组下的选项，选项和父选项不再关联

### What is actually happening?

1、开始选择全选后，分组下面的某一项无法被取消选择
2、选择全选，选择某个分组，取消选择，再点击该分组下的选项，选项和父选项可以关联

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18.3.1 |
| System | mac |
| Browser | chrom |

**Comment by AsuraKev** [comment]
+1

**Comment by MadCcc** [comment]
checkStrictly 为 true 是没问题的，false 有 bug

**Comment by AsuraKev** [comment]
But i cant replicate it in the example in the documentation site :/

**Comment by catmiao8** [comment]
> 但我无法在文档站点的示例中复制它：/

我正在尝试修复这个问题，看起来应该外层节点的context有关系，因为我在项目中或者官方文档中也无法复现这个问题，但如果整个应用只有Table，那就能复现了

**Comment by Jarryxin** [comment]
`preserveSelectedRowKeys： true`
`checkStrictly: false`
配置这两项，错误可复现

**Comment by catmiao8** [comment]
> `preserveSelectedRowKeys： true` `checkStrictly: false` 配置这两项，错误可复现

但是在官网上复现不了的  只有整个应用只有Table节点的时候  才能复现
