### ISSUE TITLE
Switch 组件属性

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#5062]
我在Form组件的FormItem中使用下面的方式可以显示。
```
getFieldDecorator(item.ITEM_CODE, fieldPropsOptions)(
  <Switch checkedChildren={{label:'开', value:'1'}} unCheckedChildren={{label:'关', value: '0'}} />
);
```
但直接使用下面的形式会报错。
```
<Switch checkedChildren={{label:'开', value:'1'}} unCheckedChildren={{label:'关', value: '0'}} />
```
![image](https://cloud.githubusercontent.com/assets/18158633/23347394/1b6031cc-fcdd-11e6-9d1a-88cf37a4b85c.png)
我想问一下是我用的不对还是怎么回事，Switch需要自定义显示的label和value，就像上面代码中一样。

**Comment by afc163** [comment]
We do't provide usage like that. The FormItem case would be also failed: http://codepen.io/anon/pen/OpVRab?editors=0010

Read the documentation.
