### ISSUE TITLE
Pagination/Table pagination SizeChanger select input customisation?

### ISSUE THREAD

**Issue by debotos** [ant-design/ant-design#50630]
### What problem does this feature solve?

I want to change the down arrow icon of the size changer dropdown to match my design.

### What does the proposed API look like?

sizeChangerInputProps={props available for a select input}

**Comment by Wxh16144** [comment]
Refactoring 'rc-pagination' to support 'components' to allow developers to customize select components. In this way, your need can also be addressed. 

ref: https://github.com/react-component/pagination/pull/595#discussion_r1671576180

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/50952
