### ISSUE TITLE
Form.Item 如果有子元素包裹，无法正常使用

### ISSUE THREAD

**Issue by kwooshung** [ant-design/ant-design#50634]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-qarfsv?file=demo.tsx)

> 虽然可以自定义组件，但是像案例中的简单包裹，没必要专门去做个组件。

### Steps to reproduce

重现链接里面写清楚了，而且一看就知道什么问题了

### What is expected?

可以正常使用，与包裹元素没关系；

### What is actually happening?

无法正确的获取到对应的表单元素

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18 |
| System | mac/windows |
| Browser | Microsoft Edge 127.0.2651.105/ Chrome 128.0.6613.114 |

---
## 个人拙见：
子元素层级多，没关系，可以加个什么标记指定那个元素是用来绑定的，比如元素的id和Form.Item 的 name一致即可；
如果没有设定，则查找子元素里面第一个表单元素；

**Comment by ybf970928** [comment]
文档里有说明, 你可以用类似两个form.item
```js
      <Form.Item<FieldType>
        name="a"
      >
        <Space>
          <Form.Item<FieldType> label="xxxxxx">
            <Input />
          </Form.Item>
          <Button>浏览</Button>
        </Space>
      </Form.Item>
```

**Comment by zombieJ** [comment]
> 子元素层级多，没关系，可以加个什么标记指定那个元素是用来绑定的，比如元素的id和Form.Item 的 name一致即可；
如果没有设定，则查找子元素里面第一个表单元素；

感谢反馈，但是 antd 侧不会去实现非 React 生命周期的事件绑定逻辑。有以下几点原因：

1. 元素标记是一种约定，仅当子组件为自研时才能实现该约定。当你使用三方组件库时，其并不会去遵守某个库的约定。
2. 元素查找仅对原生元素（如 input、select）有效，对于基于 React 实现的组件（如 Slider、TreeSelect）并不会有什么原生的 `onChange` 事件来触发。就更别提通过元素定位来绑定事件。而如果通过 `props.children` 来进行递归搜索，这对于 HOC 组件是无效的。
3. 继上，表单元素不是一个绝对概念。比如 ColorPicker 是通过 `div` 组合实现的，如何知道 `div` 变成一个输入组件了？

在存在布局需求的场景下，一般推荐开发者实现一个 绑定代理组件 通过 API 传入需要绑定的组件来将事件正确传递至目标。而非通过递归查找方式，因为 React 不是这么工作的。

此外，如果你可以确保业务中使用的子组件可以通过某种约定来查找，可以考虑自行 HOC Form.Item 实现非 React 生命周期的事件绑定逻辑。

**Comment by kwooshung** [comment]
@zombieJ 懂了，所以最好的方式还是自己再做一个的组件，然后通过api指定就好了，对吧。
