### ISSUE TITLE
The Upload component's name attribute isn't reflecting on the input tag.

### ISSUE THREAD

**Issue by macinjoke** [ant-design/ant-design#50643]
### Reproduction link

[https://codepen.io/macinjoke/pen/rNErrPb?editors=1010](https://codepen.io/macinjoke/pen/rNErrPb?editors=1010)

### Steps to reproduce

View input tags in the developer tools.

### What is expected?

The input tag has a name attribute.

### What is actually happening?

Input tags do not have a name attribute.

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18 |
| System | macOS 13.6.9 |
| Browser | chrome 127.0.6533.120 |

---
The minimal reproduction is a copy of the Upload sample on Ant Design official page.
This is a Dragger sample, but other Upload components will not have a name attribute as well.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/50652
