### ISSUE TITLE
datepicker picker为year时设置maxDate,minDate异常

### ISSUE THREAD

**Issue by zhy19950705** [ant-design/ant-design#50646]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-xqxthh?file=demo.tsx)

### Steps to reproduce

```
import React from 'react';
import './index.css';
import { DatePicker } from 'antd';
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';

dayjs.extend(customParseFormat);

const dateFormat = 'YYYY-MM-DD';

const App: React.FC = () => (
  <DatePicker
    minDate={dayjs('2022-01-01', dateFormat)}
    maxDate={dayjs('2022-12-31', dateFormat)}
    picker="year"
  />
);

export default App;
```

### What is expected?

2021被禁用

### What is actually happening?

2021未被禁用

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18.3.1 |
| System | mac |
| Browser |  128.0.6613.84 |

**Comment by Wxh16144** [comment]
看了半天 rc-picker 的代码逻辑，结果没注意到你提供复线 antd 版本为 5.18.1，而你在 issue 反馈的又是 5.20.3

但是这个 bug 在 rc-picker https://github.com/react-component/picker/pull/850 这次提交已经修复。 也就是说 antd 5.20.0+ 是修复了这个问题...
