### ISSUE TITLE
[Card] loading state for card view should be more customized

### ISSUE THREAD

**Issue by hckhanh** [ant-design/ant-design#5065]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: Windows 10 Pro x64
- Browser and its version: Chrome 56.0.2924.87 x64

The card view should be more customizable for loading state. Cause in almost cases, people will always customize the card content. As you can see my work here.

> https://games-searcher-dev.herokuapp.com/

I think it would be nice if the content of loading state can be customized

**Comment by afc163** [comment]
I think you can achieve that by specifying the children of Card, rather than using default loading prop.

http://codepen.io/anon/pen/EWjNyq?editors=0010

**Comment by weslleyaraujo** [comment]
@afc163 do you think its a good idea to have [`ant-card-loading-block`](https://github.com/ant-design/ant-design/blob/master/components/card/index.tsx#L28) as separated component?

I think it would be very useful in a lot of cases.. also it would be easy to build what @hckhanh is looking for if we could just:

```js
import { LoadingBlock } from 'antd';

render(<LoadingBlock width="90%" />);
```

I can work on a pr if you agree on that 😃

**Comment by benjycui** [comment]
> I think you can achieve that by specifying the children of Card, rather than using default loading prop. -- from @afc163 

> @afc163 do you think its a good idea to have ant-card-loading-block as separated component? -- from @weslleyaraujo

@weslleyaraujo there is no different, actually.
