### ISSUE TITLE
增加自定义 Message 和 Notification 组件的自定义成功、警告、错误等图标的能力

### ISSUE THREAD

**Issue by ilxqx** [ant-design/ant-design#50669]
### What problem does this feature solve?

目前Message和Notification组件在ConfigProvider中能够配置的只有className和style，希望可以增加successIcon、warningIcon、errorIcon、infoIcon的配置项，可以自定义success、warning、error以及info形式下的icon图标，因为可能有些项目就是想要定制这些图标（使用我们自己的图标）。

ConfigProvider配置属性截图：
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/2fd43dea-c62d-41e6-b58d-83eb2120d7e7">

### What does the proposed API look like?

虽然可以通过 open 方法来模拟实现（或许 success 等方法内部本质上也是 open 的调用），但是这样就会失去 success、info、warning等方法与生俱来的便利性，需要自己封装一套util方法，繁琐且不怎么优雅。既然ConfigProvider 可以支持组件细粒度级别的控制，那通过这个实现再好不过了。

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/50458
