### ISSUE TITLE
timeline 样式异常

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#50666]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-dxuu7n?file=demo.tsx)

### Steps to reproduce

无

### What is expected?

1. 首行距离不应该紧贴上边框
2. 使用自定义 dot 时，能够自适应位置，不超出边框

<img width="317" alt="image" src="https://github.com/user-attachments/assets/f17fe5fd-4166-4490-aaca-99ceeac5d81d">

### What is actually happening?

1.首行紧贴边框
2. 自定义 dot 超出边框

<img width="345" alt="image" src="https://github.com/user-attachments/assets/6511769a-9bc5-41e7-9d60-a6200353aee0">

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18.2.0 |
| System | macOS 14.6.1 |
| Browser | chrome 122.0.6261.57 |

**Comment by afc163** [comment]
dot 需要垂直居中的，不然更奇怪，不算是 bug。

**Comment by wanghui2021** [comment]
<img width="1406" alt="image" src="https://github.com/user-attachments/assets/9de8ffac-5ce5-46ee-86c0-58ee9d689eb0">

如上图，第一条数据的行高是不是存在问题

**Comment by wanghui2021** [comment]
> dot 需要垂直居中的

垂直居中这个是没有问题的。
但是自定义 dot 节点的时候，dot 会超出父节点元素的边框范围，这个应该有问题吧？

**Comment by afc163** [comment]
这个可能需要你自行指定 Timeline 的 padding 了，目前的实现方式是无法自动识别 dot 的大小的。
