### ISSUE TITLE
DatePicker.RangePicker  只禁用起始日期的选择，结束日期选择也有问题

### ISSUE THREAD

**Issue by AnaniZhu** [ant-design/ant-design#50660]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-a66ggu?file=demo.tsx)

### Steps to reproduce

直接选择日期就可以复现

### What is expected?

应该能正常选择「结束日期」，「开始日期」不可选择。

### What is actually happening?

选择「结束日期」后，一瞬间又会切回之前的值

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | 18 最新 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
参考 warning 信息，当配置 disabled 且被 disabled 的字段需要留空，需要配合 allowEmpty 一同配置：

<img width="444" alt="截屏2024-08-30 22 51 41" src="https://github.com/user-attachments/assets/7b2890ba-3b80-44a0-bb51-332de20f6a8e">
