### ISSUE TITLE
Turn off table row hover style when there is rowSpan and colSpan?

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#5067]
https://segmentfault.com/q/1010000008474739

**Comment by yesmeck** [comment]
Setting background on `td` has a better performance than setting background on `tr`:

Setting background on `tr`:

![before mov](https://cloud.githubusercontent.com/assets/465125/23357078/353be41c-fd17-11e6-8bfe-7927823bb09b.gif)

Setting background on `td`:

![after mov](https://cloud.githubusercontent.com/assets/465125/23357084/3b61aaac-fd17-11e6-8cdc-8573f987df96.gif)

**Comment by yesmeck** [comment]
For those who don't want hover effect, they can always override hover background by CSS/
