### ISSUE TITLE
DatePicker[picker=week]   拿到选中的周日期不对，第一天是上周日，最后一天是本周六

### ISSUE THREAD

**Issue by BWA-579** [ant-design/ant-design#50684]
### Reproduction link

[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce

 const customWeekStartEndFormat: DatePickerProps['format'] = (
                value,
              ) =>
                `${dayjs(value).startOf('week').format('MM/DD')} ~ ${dayjs(
                  value,
                )
                  .endOf('week')
                  .format('MM/DD')}`;

<DatePicker format={customWeekStartEndFormat} picker="week" />

### What is expected?

加上defaultValue={dayjs()}  就正常了，但不加就会出现描述的bug

### What is actually happening?

..0

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | win11 |
| Browser | 谷歌 |

**Comment by BWA-579** [comment]
![image](https://github.com/user-attachments/assets/ac6a5030-2896-41f0-823f-0f4f21a29593)

**Comment by MadCcc** [comment]
给一个在线复现吧

**Comment by postbird** [comment]
> 给一个在线复现吧

![image](https://github.com/user-attachments/assets/cebbee51-0108-4b77-9b51-24a113ebd568)

This bug can be reproduced in the website. https://ant-design.antgroup.com/components/date-picker-cn

https://stackblitz.com/run?file=demo.tsx

**Comment by tunshiyu** [comment]
这个怎么解决了，关闭了？ 这第一列的数据也是有问题的
![image](https://github.com/user-attachments/assets/c52c8330-a455-4fb9-9e7b-96953f7c87c2)
