### ISSUE TITLE
Select能不能暴露出compositionstart和compositionend事件？

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#5068]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: OSX
- Browser and its version: Chrome

#### What did you do? Please provide steps to re-produce your problem.

Select根据输入内容从远程获取数据的时候，如果是中文拼音输入，我并不希望在打拼音的时候就触发拿数据

#### What do you expected?

希望如截图那样只有在“上”被确认输入后才获取数据，只要这2个接口暴露出来我就能自己控制了

#### What happen?

![1](https://cloud.githubusercontent.com/assets/4329120/23350261/58314e8a-fcf4-11e6-8a59-ba22f85a46b8.gif)

**Comment by RaoHai** [comment]
ref #4689

and https://github.com/facebook/react/issues/3926
