### ISSUE TITLE
antd 提供的 GetRef 貌似和 React.ElementRef 功能重合了

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#50682]
### Reproduction link

[https://www.totaltypescript.com/strongly-type-useref-with-elementref](https://www.totaltypescript.com/strongly-type-useref-with-elementref)

### Steps to reproduce

null

### What is expected?

也许这里应该重构改为  `export type { ElementRef as GetRef} from 'react';` 即可

但是测试用例中 https://github.com/ant-design/ant-design/blob/b66ca0482898f7fcccc1720aab1661ac420a58ad/components/_util/__tests__/type.test.tsx#L57 的泛型是  `GetRef<CC>` ，而用 ElementRef 则应该是 `ElementRef<typeof CC>`

### What is actually happening?

Custom implementation

| Environment | Info |
| --- | --- |
| antd | 5.20.4 |
| React | latest |
| System | macos |
| Browser | latest |

**Comment by Wxh16144** [comment]
X post: https://x.com/AdamRackis/status/1830357946414366875

**Comment by zombieJ** [comment]
可以替换，另外这个测试的 CC 是 class component，本身就是定义所以不需要 typeof

**Comment by Wxh16144** [comment]
> 本身就是定义所以不需要 typeof 

我意思是替换了以后，原本的使用方式可能就会报错，

我倒是期望可以替换掉减少维护成本。 至于报错应该让开发者自行调整。 CC 组件应该很少人用了

**Comment by Wxh16144** [comment]
close reason: https://github.com/ant-design/ant-design/pull/50685#issuecomment-2330774532
