### ISSUE TITLE
当鼠标移出 <Badge /> 徽标组件时需要过渡动画

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#50681]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-zv1zo9-pbh7nt?file=demo.tsx)

### Steps to reproduce

1. 鼠标移出 <Badge /> 徽标组件，没有过渡动画
2. 移除重现链接里的注释，并 import './index.css'
3. 再次移出 <Badge /> 徽标组件，出现过渡动画

### What is expected?

当鼠标移出 <Badge /> 徽标组件时需要过渡动画

![移出](https://github.com/user-attachments/assets/7be7d57b-6705-4f4c-bef2-a0986ab4e629)

### What is actually happening?

当鼠标移出 <Badge /> 徽标组件时没有过渡动画

![移入](https://github.com/user-attachments/assets/b3cf605f-7bc4-48e7-a12b-d4dd50bbb399)

| Environment | Info |
| --- | --- |
| antd | 5.20.4 |
| React | 18.3 |
| System | Windows 11 |
| Browser | 128.0.2739.54 |

---
原问题 issue 地址：
https://github.com/ant-design/ant-design/issues/50402
Fixed Pull Request：
https://github.com/ant-design/ant-design/pull/50607

**Comment by Wxh16144** [comment]
看起来 #50670 加的这个过渡动画权重不够高
