### ISSUE TITLE
二次包裹的组件无法显示 Popover 气泡

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#50694]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-z8jurj?file=demo.tsx)

### Steps to reproduce

1. 将 AntD 的原生 `<Badge />` 组件二次包裹成 `<BadgeDot />`
2. 将二次包裹的组件 `<BadgeDot />` 放入 `<Popover />` 组件的 children 中
3. 将鼠标 hover 悬浮于 `<BadgeDot />` 之上，无法唤出 Popover 气泡弹窗

![屏幕截图 2024-09-03 183050](https://github.com/user-attachments/assets/8636a174-de52-4c00-8c44-33e500b3ecdd)

### What is expected?

鼠标悬浮于二次包裹的组件时，能够显示 Popover

### What is actually happening?

鼠标悬浮于二次包裹的组件时，无法显示 Popover

| Environment | Info |
| --- | --- |
| antd | 5.20.4 |
| React | 18.3 |
| System | Windows 11 |
| Browser | EDGE 128.0.2739.54 |

**Comment by Wxh16144** [comment]
我猜应该是这个问题？
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/3f82ae83-6b67-42f8-917e-c529747f8f98">

**Comment by Wxh16144** [comment]
```diff
 // 注意这里的 Badge 组件被二次包裹
-const BadgeDot: React.FC = () => (
-  <Badge>
+const BadgeDot: React.FC = (props) => (
+  <Badge {...props}>
     <Button type="primary" size="large">

```
