### ISSUE TITLE
component Icon spin does not work on OS X Chrome

### ISSUE THREAD

**Issue by ufohjl** [ant-design/ant-design#5069]
#### Environment(required)

- antd version: 2.7.2
- OS and its version: OS X Yosemite 10.10.5
- Browser and its version: chrome version 41.0.2272.104 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
<Icon type="loading" spin={true} />

#### What do you expected?
rotating

#### What happen?
DID not rotate 

#### Re-producible online demo
none

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

It works here: https://ant.design/components/spin/

**Comment by afc163** [comment]
chrome 41? I think it is too old.

**Comment by ufohjl** [comment]
I tried to update my Chrome to 55 and it seems to be OK. Thanks!
