### ISSUE TITLE
在使用 textarea 组建时，如果文本内容超过 200k，页面会明显卡顿，有可能页面崩溃

### ISSUE THREAD

**Issue by millionbug** [ant-design/ant-design#50692]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-cv6bud?file=demo.tsx)

### Steps to reproduce

可以将test.text 文件中的内容复制粘贴到这个textarea内，可以复现

### What is expected?

浏览器原生的textarea标签，在复制粘贴 200k 的文本场景下是不会卡顿的

### What is actually happening?

即使页面中只有一个 Textarea 组件，浏览器仍然会卡顿十多秒

| Environment | Info |
| --- | --- |
| antd | 5.20.4 |
| React | 18 latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
Chrome 在一些字体下长文本渲染有 BUG，会导致性能问题。如果有长文本需求，可以考虑直接把字体换掉：

https://stackblitz.com/edit/antd-reproduce-5x-vvqwpb?file=test.text,demo.tsx,index.tsx
