### ISSUE TITLE
Please reopen this issue https://github.com/ant-design/ant-design/issues/48423

### ISSUE THREAD

**Issue by quinn** [ant-design/ant-design#50702]
### Reproduction link

[https://github.com/ant-design/ant-design/issues/48423](https://github.com/ant-design/ant-design/issues/48423)

### Steps to reproduce

https://github.com/ant-design/ant-design/issues/48423

### What is expected?

https://github.com/ant-design/ant-design/issues/48423

### What is actually happening?

https://github.com/ant-design/ant-design/issues/48423

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | https://github.com/ant-design/ant-design/issues/48423 |
| System | https://github.com/ant-design/ant-design/issues/48423 |
| Browser | https://github.com/ant-design/ant-design/issues/48423 |

**Comment by mnesia11** [comment]
您好！我已收到您发送的邮件，稍后我会查看邮件，如果有进一步需求，我会与您再联系。谢谢！
