### ISSUE TITLE
Popover style corrupts on Meteor production env.

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design#5070]
- antd version: 2.7.3
- OS and its version: ubuntu 14.04
- Browser and its version: chrome 56.0.2924.87

When used  in dev env on local pc, it works fine. But when we deploy it with docker on our production machine, the style corrupted.

on dev env
![image](https://cloud.githubusercontent.com/assets/3808838/23352550/c3b1caa0-fd02-11e6-86c1-47e4181864bf.png)

on production env
![image](https://cloud.githubusercontent.com/assets/3808838/23352567/e2bafde0-fd02-11e6-8d3f-d06e22d96261.png)

Please note the positions marked with red circle. I found in production env, this part of style is wrong. When I corrected it to mimic what in dev env, the style restored. I spent some time in finding the related source code, but didn't find any clue where there style was set.

the following is my `.babelrc`
```
{
  "presets": [
    "env",
    "stage-0",
    "react"
  ],
  "plugins": [
    "react-require",
    [
      "import",
      [
        {
          "libraryName": "antd",
          "style": true
        }
      ]
    ]
  ]
}
```

**Comment by zhaoyao91** [comment]
I have found the position where the style is set, but I am still not clear why they are not correct in production env.

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/5047#issuecomment-282632927 

just reinstall node_modules.

**Comment by zhaoyao91** [comment]
Thanks. I thought it's the docker cache which stuck the packeges in the production env.
