### ISSUE TITLE
RangePicker在打开表单表单编辑回显数据后该组件无法正常编辑

### ISSUE THREAD

**Issue by lw20001210** [ant-design/ant-design#50710]
### Steps to reproduce

1.点击表格的编辑打开,这时候数据是正确显示的
2.然后点击RangePicker组件,无法正常编辑时间
![屏幕截图 2024-09-04 171307](https://github.com/user-attachments/assets/19f25e1f-becd-4f50-8b81-648f7e0339d5)

### What is expected?

可以正常编辑时间

### What is actually happening?

无法正常编辑时间

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | react18.2.0 |
| System | window10 |
| Browser | chrome |

---
   <Form.Item
            label="起止时间"
            name="timerRange"
            rules={[{ required: true, message: "请选择广告开始、截止时间！" }]}
          >
             <RangePicker showTime />
          </Form.Item>
    this.addForm[0].setFieldsValue({
      name: res.data.data.name,
      pointId: res.data.data.pointId,
      point: res.data.data.point,
      link: res.data.data.link,
      timerRange: [moment(res.data.data.timeBegin), moment(res.data.data.timeEnd)],//res.data.data.timeBegin是时间撮
      photo: obj?.name,
      address,
    });

**Comment by lw20001210** [comment]
![Uploading 屏幕截图 2024-09-04 171307.png…]()

**Comment by lw20001210** [comment]
> 你好@lw20001210[。请通过fork此代码](https://u.ant.design/repro)提供在线恢复版本或提供最小化的GitHub存储库（如[create-react-app-antd ）](https://github.com/ant-design/create-react-app-antd)`Need Reproduce`。如果3天内没有活动，则标记为的问题将被关闭。
> 
> 你好@lw20001210，我们为您提供一个在线的重置实例以便需要我们帮助排查问题。您可以通过fork[在线重置箱子](https://u.ant.design/repro)，或者提供一个最小化的GitHub仓库（类似[create-react-app-antd](https://github.com/ant-design/create-react-app-antd)）。3未解决此问题将被自动关闭。
> 
> > [什么是最小化重置，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647 563652e676966](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)



> 你好@lw20001210[。请通过fork此代码](https://u.ant.design/repro)提供在线恢复版本或提供最小化的GitHub存储库（如[create-react-app-antd ）](https://github.com/ant-design/create-react-app-antd)`Need Reproduce`。如果 3 日没有活动，则标记为的问题将被关闭。
> 
> 你好@lw20001210，我们为您提供一个在线的重置实例，以便需要我们帮助排查问题。您可以通过fork[在线重置箱子](https://u.ant.design/repro)，或者提供一个最小化的GitHub仓库（类似[create-react-app-antd](https://github.com/ant-design/create-react-app-antd)）。3未解决此问题问题将被自动关闭。
> 
> > [什么是最小化重置，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647 563652e676966](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
我写了个demo,把项目拉下来跑一下就可以复现那个bug了
https://github.com/lw20001210/RangePicker.git

**Comment by lw20001210** [comment]
https://github.com/lw20001210/RangePicker.git这是我写的一个demo,你们拉下来跑下就可以复现那个bug

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774

**Comment by lw20001210** [comment]
> See [#50622 (comment)](https://github.com/ant-design/ant-design/issues/50622#issuecomment-2317050774)

谢谢
