### ISSUE TITLE
请求增加滚动条相关的功能

### ISSUE THREAD

**Issue by ltwlyanxi** [ant-design/ant-design#50711]
### What problem does this feature solve?

可以美化滚动条以及增强滚动条的功能。
具体来说，pc端的滚动条样式不统一，手机上和电脑上显示的也不一样。
在 Modal 中，出现申请表单，我给Modal 设置最大高度为屏幕的80%，那么Modal就会出现滚动条，而且滚动条距离Modal右侧还有一定的距离…我通过增加css来让Modal中的滚动条贴着Modal最右侧的边界。
在滚动条增强中，主要是增加容器内定位。虽然有点类似 【Anchor 锚点】组件，但是针对在容器中的文章不适合。在用户体验上，就比如一些协议，往往是在一个页面的容器内，例如弹出Modal，中间一个容器显示协议，在Modal的footer里有个checkbox 是 我已阅读并同意xxx协议这样的布局中，我想实现点击协议头部的文本可以跳转到协议的某段中，这通常需要自己编写代码来实现。除了协议这种情况（可能用到的不多），在一些后台页面中，也存在某些容器（自定义较为复杂的列表，或者是文字），点击某个按钮（可能容器内的也可能容器外的）可以定位容器内某个元素所在的位置，可以将滚动条滚动到某个位置。
除此之外还有其他的就不说明了，这些虽然可以自行编写代码，但是如果antd中集成了这些并再此基础上进行更多的功能扩展，这也是个非常不错的组件！

### What does the proposed API look like?

没思考过

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/43288

**Comment by ltwlyanxi** [comment]
ok

**Comment by kwooshung** [comment]
https://github.com/ant-design/ant-design/issues/45433 我也提交过，不过官方好像没有要做这个的意思。

**Comment by ltwlyanxi** [comment]
> #45433 我也提交过，不过官方好像没有要做这个的意思。

antd官网有样式调整，还有左侧的menu菜单，我的menu很长，有个滚动条很影响美观的，唉
