### ISSUE TITLE
Carousel   bug

### ISSUE THREAD

**Issue by chibaoshui** [ant-design/ant-design#5071]
组件上添加autoplay之后，beforeChange(from,to)里面的from和to，
控制台显示为
1，1
2，2
0，0
但是用鼠标手动点击焦点控制台显示
0，1
1，2
2，0

- antd version:2.7.2
- OS and its version:win10
- Browser and its version: chrome 58.0.3000.4

**Comment by benjycui** [comment]
It works fine when I test locally.

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
http://codepen.io/anon/pen/vxNbwg?editors=0010

It works fine. Reopen if you can privide reproducible demo.

**Comment by chibaoshui** [comment]
// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { Carousel } = antd;
function _beforeChange(from, to) {
    console.log('from:'+from+'-----to:'+to);
}
function _afterChange(current) {
    console.log('当前是第'+current+'节点');
}
let settings = {
            effect: 'fade',	//动画效果函数，可取 scrollx, 默认值fade
            autoplay: true,//是否自动切换	boolean	默认值false
            easing: 'linear'	,//动画效果	string	默认值linear
            autoplaySpeed: 3000,
            pauseOnHover: true, //鼠标悬停轮播暂停
        };
        let jsonData = [{"color":"orange"},{"color":"gray"}];
        let arr = jsonData.map( (data,index) => {
            console.log(data.color);
            return (
                <div key={index}>
                    <div style={{height:'100px',background:'orange'}}>{data.color}</div>
                </div>
            )
        });
ReactDOM.render(
  <div>
     <Carousel  beforeChange={_beforeChange} afterChange={_afterChange} {...settings}>
     {arr}
     </Carousel>
  </div>
, mountNode);

**Comment by benjycui** [comment]
It works fine in CodePen.
