### ISSUE TITLE
fontSizeSM should be possible to apply on Typography.Text

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design#50729]
### What problem does this feature solve?

There is a fontSizeSM  token, that is not being applied, and some texts that should be displayed in a smaller size than 14px, in this case the 12px, there is no way to use size in Typography.Text to use this token native from antd and i think it makes sense to use a smaller text in some use cases

### What does the proposed API look like?

<Typography.Text size="small"  
should use the existing fontSizeSM  token

**Comment by drcc20** [comment]
same here
