### ISSUE TITLE
Table(scroll) causes responsive bug in Mobile Safari and Wechat

### ISSUE THREAD

**Issue by 18601673727** [ant-design/ant-design#5072]
- antd version: 2.7.3
- OS, Browser and their version: 
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1
```
Use code below, then rotate your phone:
```
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0">
```

```
<Card title={"dummyData"} bodyStyle={{ padding: '0' }} >
  <Table
    columns={columns}
    dataSource={dataSource}
    pagination={false}
    scroll={{ x: 600 }}
  />
</Card>
```

You'll find `<Table>` component trigger a responsive bug, the ratio of the page would became smaller than it was used to be, sorry for not presenting a online demo.

**Comment by benjycui** [comment]
I try demos of ant.design in Safari@iPhone 5S, everything works fine.

**Comment by benjycui** [comment]
You had better to provide online demo and steps to reproduce it.

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
@18601673727

**Comment by 18601673727** [comment]
@afc163 @benjycui Okay, I'll do that asap.

**Comment by 18601673727** [comment]
I made a [pen](http://codepen.io/18601673727/pen/QpNrKX) but unfortunately it cannot be re-illustrated, so I record a gif for you, please be attention on the top menu.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3302620/23545911/407ee3a0-0038-11e7-82d1-ba3fbf918dd8.gif)

**Comment by benjycui** [comment]
It's hard to tell anything wrong.. 

Can you try to provide a demo with gh-pages and something like this? If you cannot reproduce it with CodePen.

**Comment by afc163** [comment]
I think it is better to dig this bug by youself and give us PR.
