### ISSUE TITLE
卡片组件 <Card /> 无法自适应 Flex 宽度

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#50724]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-35vn7u?file=demo.tsx)

### Steps to reproduce

1. 紫色代表 Flex 容器，假设存在一组横向排列，且宽度与高度均一致的卡片

![1](https://github.com/user-attachments/assets/904f2dd1-48e7-4aa2-a840-bbba137863f3)

2. 缩短 Flex 容器宽度，卡片无法自适应 Flex 宽度

![2](https://github.com/user-attachments/assets/bef55896-3939-437c-b2a1-a2b21b9f500d)

3. 将样式应用于 Card.Meta，当卡片宽度小于 Flex 时，能够被拉伸至 Flex 等宽，但依然有卡片溢出 Flex 容器

![3](https://github.com/user-attachments/assets/cb2fcb71-2666-41a4-938b-f537b36efc6a)

4. 且上面这种写法导致横向排列时，卡片高度不一致

![4](https://github.com/user-attachments/assets/4904f579-d3a8-43ba-89f2-9ffb4893074e)

### What is expected?

我希望能同时满足：
1. 横向排列时，卡片的宽度与高度均保持一致
3. 纵向排列时，卡片宽度等同于 Flex 宽度

### What is actually happening?

卡片组件 `<Card />` 无法自适应 Flex 宽度

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | 18.3 |
| System | Windows 11 |
| Browser | EDGE 128.0.2739.54 |

**Comment by zombieJ** [comment]
`flex` 布局元素样式都需要在一级子元素，嵌套元素不会有效：

https://stackblitz.com/edit/react-35vn7u-txsivt?file=demo.tsx

这和 antd 本身没有什么关系哈，先关了~
