### ISSUE TITLE
Typography  ellipsis 宽度不够会不显示内容

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#50732]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-r1t7jn?file=demo.tsx)

### Steps to reproduce

查看 demo

### What is expected?

能显示内容

### What is actually happening?

不显示内容

![image](https://github.com/user-attachments/assets/458ec36a-c350-4673-b6e1-a5158cda5ebc)

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | latest |
| System | chrome |
| Browser | mac |

**Comment by MadCcc** [comment]
空间不够被挡住了

**Comment by crazyair** [comment]
> 空间不够被挡住了

但是不应该 width 0

**Comment by yezhonghu0503** [comment]
![image](https://github.com/user-attachments/assets/d3361cb9-d9a6-4a52-8b1a-f18d66593703)

-item-content的min-width设置为0是不是不太合适，即便是父元素宽度小于子元素宽度，也应该保持descriptions组件的最小宽度至少为一个相对单位1em，至少显示一个字符以表现此处是有元素内容
