### ISSUE TITLE
Recommend：develop a feature of callback function to the component of Message

### ISSUE THREAD

**Issue by lcoder** [ant-design/ant-design#5073]
现在的参数配置有
```
message.success(content, duration)
```
一个content、一个duration、常用的感觉就是加一个content的调用方式吧，第二个，场景不是特别大，但是有一个使用场景使用比较多，当message消失的时候，需要做一个些事情，比如刷新浏览器。
也不是不需要duration这个参数，判断第二个参数是object就是配置了，如果是function就是回调，第三个参数也可以是配置，{ duration , top }  这样子也和全局config一致配置了。

现在一般都是知道duration了，设置个定时器setTimeout( callback , duration )。然后去做一些事情，有点繁琐了。

大家觉得怎么样。

**Comment by bang88** [comment]
See https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx#L7

Please read the documents more patients

**Comment by afc163** [comment]
There is a `onClose` in config both message and notification.

But we miss ducumentation in message: https://ant.design/components/message/#API

Could you try and help us to add this API instruction? @lcoder

**Comment by bang88** [comment]
...

**Comment by lcoder** [comment]
@bang88 thanks

**Comment by lcoder** [comment]
@afc163 I'd like to.but with my poor usage of github. I will try. thanks

**Comment by afc163** [comment]
Actually, I added onClose in 2015: https://github.com/ant-design/ant-design/commit/1e5271491e33a583af22a8693f6a57446ec6d9d4

I don't know why I forgot the documentation... 😅
