### ISSUE TITLE
RangePicker 的开始位置中选择大于结束位置的时间，会把选中的开始时间交换到结束位置，导致没办法继续选择结束时间

### ISSUE THREAD

**Issue by kelokeloo** [ant-design/ant-design#50740]
### Reproduction link

[https://4x-ant-design.antgroup.com/components/date-picker-cn/#components-date-picker-demo-range-picker](https://4x-ant-design.antgroup.com/components/date-picker-cn/#components-date-picker-demo-range-picker)

### Steps to reproduce

1. 使用官网文档中-> DatePicker日期选择框->范围选择器 -> 第二个组件 ```<RangePicker showTime />```
2. 选择时间[2024-9-6 10:00:00, 2024-9-6 12:00:00]
3. 然后点击开始位置，选择2024-9-6 13:00:00，确认。这样我选择的开始时间就会被交换到组件的结束位置上，此时组件选中的是结束时间，导致我没办法再选择结束时间了！

演示视频：https://github.com/user-attachments/assets/9b29a70b-5910-4991-a068-b1556c2df9db

### What is expected?

在开始时间大于结束时间时，我在开始位置选择的开始时间不会被交换到结束位置

预期行为像5.20.4，https://github.com/user-attachments/assets/8a529b26-56f0-405f-990a-be636ab19f49

### What is actually happening?

在开始时间大于结束时间时，我开始位置选择的时间会被交换到结束位置，导致我没办法再选择结束时间。

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 16.8.6 |
| System | macOs Big Sur 11.7.10 |
| Browser | chrome 128.0.6613.113 |

---
演示链接：https://github.com/user-attachments/assets/9b29a70b-5910-4991-a068-b1556c2df9db

然而5.20.4并没有这个问题，链接：https://github.com/user-attachments/assets/8a529b26-56f0-405f-990a-be636ab19f49

其他注意：日期选择好像不会出错，只有选择时间的时候会出错

**Comment by afc163** [comment]
你给的两个视频都是 4.x 的，正确的行为是什么样的？

**Comment by zombieJ** [comment]
在 v5 中 Picker 重构了相关选择逻辑。v4 已经过了维护期了，如果有需求可以考虑升级哈。这里就先关了。

**Comment by kelokeloo** [comment]
> 你给的两个视频都是 4.x 的，正确的行为是什么样的？

oh! 不好意思！我修改了commented，现在可以看到正常的行为了🤯

**Comment by kelokeloo** [comment]
> 在 v5 中 Picker 重构了相关选择逻辑。v4 已经过了维护期了，如果有需求可以考虑升级哈。这里就先关了。
用了超多v4多组件，现在好难升到v5😨
