### ISSUE TITLE
请问Upload组件的data参数应该如何使用？

### ISSUE THREAD

**Issue by zerozaki0752** [ant-design/ant-design#5074]
[文档](https://ant.design/components/upload-cn/)中没有找到data参数的使用示例

| 参数       | 说明                                                         | 类型        | 默认值|
|------------|--------------------------------------------------------------| ----------- |-------|
| data       | 上传所需参数或返回上传参数的方法                   | object\|function(file) | 无    |
| onChange   | 上传文件改变时的状态，详见 onChange                | Function    | 无    |

1、data是用来组织上传参数的吗？
2、发现onChange({file})的file中可以得到文件的base64，但是data中却拿不到。是否能够让data中得到file的base64格式，再通过指定参数POST到服务器呢？

**Comment by afc163** [comment]
http://codepen.io/anon/pen/ZeGRvZ?editors=0010
