### ISSUE TITLE
Typography组件bug，直接造成页面崩溃， 暂时不清楚什么原因

### ISSUE THREAD

**Issue by whaleluo** [ant-design/ant-design#50749]
### Reproduction link

[https://ant-design.antgroup.com/components/typography-cn#typography-demo-ellipsis-controlled](https://ant-design.antgroup.com/components/typography-cn#typography-demo-ellipsis-controlled)

### Steps to reproduce

1. 上面这个链接是官网typography-的demo链接
2. 错误为官方demo的bug.   因为最近在使用typography组件时，发现有性能问题，查看官网demo的时候触发了这个bug
3. bug Demo为 【受控省略展开/收起】这节
4. 连续拖动 行数 滑块， 基本10次以内可复现

![](https://whaleluo.oss-cn-beijing.aliyuncs.com/images20240907123513.png)

### What is expected?

1. 想知道为什么会造成这个原因
2. 我自己用这个组件无论怎么滑动都不会出现这个bug,  也不确定什么原因了，好像只有在官网才能复现

### What is actually happening?

ERROR
Minified React error #185; visit https://react.dev/errors/185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error stack

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | 18 |
| System | window |
| Browser | edge |

**Comment by afc163** [comment]
Fixed in 5.20.5: https://github.com/ant-design/ant-design/pull/50688

**Comment by jk4235** [comment]
这个问题在最新版本依旧存在
