### ISSUE TITLE
主题编辑器颜色选择器无法使用

### ISSUE THREAD

**Issue by flycran** [ant-design/ant-design#50744]
### Reproduction link

[https://ant-design.antgroup.com/theme-editor-cn](https://ant-design.antgroup.com/theme-editor-cn)

### Steps to reproduce

1.选择任意一个颜色打开颜色选择器
2.点击或拖动颜色滑块，（色相或透明度）

### What is expected?

颜色出现改变

### What is actually happening?

颜色未改变，滑块没有被拖动

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | 18 |
| System | windows |
| Browser | edge 128.0.2739.54 |

**Comment by afc163** [comment]
需要重新部署 theme editor 才能修复。
