### ISSUE TITLE
主题定制时，一些类型定义不完善

### ISSUE THREAD

**Issue by s3327884** [ant-design/ant-design#50757]
### What problem does this feature solve?

使用定制主题时，需要进行移动端适配，但token中的某些属性的类型定义仅有```number```类型
希望能适配一下

### What does the proposed API look like?

```tsx
<ConfigProvider
      theme={{
        token: {

          borderRadius: '0.5vh',
          fontSize: '2vh',
        },
      }}
    />
```
![image](https://github.com/user-attachments/assets/2d1d0e32-961f-4ecb-bffa-48805befb9ef)
![image](https://github.com/user-attachments/assets/1c2a2ce6-acf6-470a-a3c5-eb11c5355619)

**Comment by MadCcc** [comment]
当前不支持 string，短期内也没有计划，因为 token 会参与运算
