### ISSUE TITLE
table的 header 与 col 并没有对齐

### ISSUE THREAD

**Issue by icowan** [ant-design/ant-design#5075]
如下图: 
![](http://source.lattecake.com/images/2017/02/14/e0/7f/59/20170227-fc3575322455f5ee7069a989e08d2e7059514452.jpeg?imageView2/2/w/1280)

不知是否是一个bug   我仔细数了一下 列数没错

**Comment by afc163** [comment]
antd version? Have you try latest version 2.7.3?

**Comment by afc163** [comment]
Reopen if you can provide a re-producible demo.

**Comment by sunyongjian** [comment]
是bug啊！！！！怎么解决啊

**Comment by yesmeck** [comment]
@sunyongjian  提 bug http://new-issue.ant.design/
