### ISSUE TITLE
The Tooltip is not displayed when it is used in a Dropdown and its parent element is an A tag

### ISSUE THREAD

**Issue by hwjom** [ant-design/ant-design#50758]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/relaxed-gwen-4hp5dx)

### Steps to reproduce

The Tooltip is not displayed when it is used in a Dropdown and its parent element is an A tag

### What is expected?

The Tooltip is displayed.

### What is actually happening?

The Tooltip is not displayed

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | windows |
| Browser | chrome/128.0.0.0 |

**Comment by zombieJ** [comment]
`a` in Menu has a magic style to add `:after` to take 100% place of the MenuItem space to make sure user can click to go to the link even in the white space. Which overlap the real span element. You can remove the `:after` element to realize hover but the click area should handle self:

https://stackblitz.com/edit/react-avscdi?file=demo.tsx,index.css
