### ISSUE TITLE
Dropdown实现Tree组件右键菜单，Dropdown的渲染层已经阻止冒泡，但是菜单disabled时点击会触发Tree组件的onSelect事件

### ISSUE THREAD

**Issue by three-water666** [ant-design/ant-design#50765]
### Reproduction link

[https://codepen.io/three-water666/pen/gONqmLO](https://codepen.io/three-water666/pen/gONqmLO)

### Steps to reproduce

打开console控制台，右击Tree节点，点击没有disabled的菜单，不触发onSelect事件，点击disabeld的菜单，触发了onSelect事件，控制台输出了"onSelect 被触发了"

### What is expected?

点击disabeld的菜单，不触发onSelect事件

### What is actually happening?

点击disabeld的菜单，触发了onSelect事件

| Environment | Info |
| --- | --- |
| antd | 5.20.4 |
| React | 18 |
| System | windows 10 |
| Browser | Chrome  128.0.6613.86（正式版本)（64 位） |

**Comment by zombieJ** [comment]
https://codepen.io/zombieJ/pen/BagMWmK
