### ISSUE TITLE
RangePicker - defaultPickerValue配合disabledDate范围选择使用时，无法选择范围内的第一个日期

### ISSUE THREAD

**Issue by bigflytime** [ant-design/ant-design#50766]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-3axfcg?file=src%2FApp.tsx)

### Steps to reproduce

- 创建一个日期选择器
- 使用`disabledDate`设定日期选择器的可选择范围，如：202201-202401
- 使用`defaultPickerValue`设定日期面板，如：`[dayjs('202101'), dayjs('202101')]`
- 选择202201 - 202202

### What is expected?

结果为：2022年1月-2022年2月

### What is actually happening?

值为空

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.3.1 |
| System | Mac OS |
| Browser | Chrome 128.0.6613.114 |

---
1. 可选范围是过去的日期，希望通过`defaultPickerValue`控制日期面板展开后能够直接定位到可选日期的年份，而不是今年 明年
2. 只有从可选范围的第一个日期选择时会有问题，比如选择202202-202203就没问题

**Comment by zombieJ** [comment]
`>=` & `<=` 都会包含当月的第一天或者最后一天，导致从月份的比较变成了日期的比较。 要比较月份就要把交集 `=`去掉，或者直接用 dayjs 提供的 `isBefore(date, type)` 比较。

**Comment by bigflytime** [comment]
感谢两位大佬解答。
