### ISSUE TITLE
onBlur and onFocus are missing in types

### ISSUE THREAD

**Issue by MudulOzan** [ant-design/ant-design#50768]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-3alssj?file=demo.tsx)

### Steps to reproduce

Just add onBlur to any data entry component

### What is expected?

To have types that internally has onBlur and onFocus events

### What is actually happening?

  console.log(`blurred:`);
  console.log(e);
};

const App: React.FC = () => (
  <Checkbox onBlur={onBlur} onChange={onChange}>
    Checkbox
  </Checkbox>
);

Type '{ children: string; onBlur: (e: any) => void; onChange: (e: CheckboxChangeEvent) => void; }' is not assignable to type 'IntrinsicAttributes & CheckboxProps & RefAttributes<CheckboxRef>'.
  Property 'onBlur' does not exist on type 'IntrinsicAttributes & CheckboxProps & RefAttributes<CheckboxRef>'.(2322)

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Chrome all |

---
In our current project we use 4.x but to be sure if it is fixed or not I prepared an environment with latest

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50842
