### ISSUE TITLE
antd Table 中 开启 virtural ，summary消失的问题

### ISSUE THREAD

**Issue by AlieLife** [ant-design/ant-design#50782]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-fb1yba?file=demo.tsx)

### Steps to reproduce

1. count改为100条，table中添加代码
         summary={() => {
            return <div>我是底部</div>;
          }}
运行后 summary 未显示
2. 注释 virtual 正常显示在底部

### What is expected?

virtual 开启时正常显示 summary

### What is actually happening?

virtual 开启时未显示summary
![image](https://github.com/user-attachments/assets/80303133-bee6-4721-8b36-83da6b0713f2)

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | macOS 10.15.2 |
| Browser | chrome 128.0.6613.120 |

**Comment by zombieJ** [comment]
请参考官方例子改：
https://stackblitz.com/edit/react-ihoxvu?file=demo.tsx
