### ISSUE TITLE
Menu 组件显示不一致

### ISSUE THREAD

**Issue by jacksonwen001** [ant-design/ant-design#50783]
### Reproduction link

[https://ant.design/components/menu-cn#menu-demo-inline](https://ant.design/components/menu-cn#menu-demo-inline)

### Steps to reproduce

https://ant.design/components/menu-cn#menu-demo-inline

### What is expected?

Menu 组件显示不一致

### What is actually happening?

Menu 组件显示不一致

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | mac |
| Browser | chrome |

![3991142018](https://github.com/user-attachments/assets/1d67c2bd-9093-4e10-a6e5-be014f5bff58)

**Comment by coding-ice** [comment]
显示不一致，指的是什么 这两个贴图不是一模一样吗，只是你框出来的位置不同

**Comment by coding-ice** [comment]
一个是有子菜单的，一个是没有子菜单的，所以展现的形式不同
