### ISSUE TITLE
引入 antd.css 和 antd.less 效果不一致的问题

### ISSUE THREAD

**Issue by akecn** [ant-design/ant-design#5078]
#### 本地环境

- antd 版本: 2.7.2
- 操作系统及其版本：osx 10.12.3
- 浏览器及其版本: chrome   56.0.2924.87 (64-bit)
#### 你做了什么？

不使用antd-init 等工具。

创建 `use_css.less` 和 `use_less.less`，内容分别为

```
@import '~antd/dist/antd.css';
```

和

```
@import '~antd/dist/antd.less';
```

页面分别引入这两个文件，查看效果。

测试代码地址：https://riddle.alibaba-inc.com/riddles/8447d83a

#### 你期待的结果是：

像官网一样正常显示
样式定义应该是一致的。

#### 实际上的结果：

部分样式的顺序不同。Cascader 组件中的 Input 组件 disabled 的样式有差异。

如果引入 `use_css.less`，则 `.ant-cascader-input.ant-input` 类的定义会覆盖 `ant-input[disabled]` 类的定义。
如果引入 `use_less.less`，则 `ant-input[disabled]` 类的定义会覆盖 `.ant-cascader-input.ant-input` 类的定义

导致 disabled 时看不到文本。
![image](https://cloud.githubusercontent.com/assets/352465/23364421/f7a85f0e-fd39-11e6-97b6-c9dc4aa24f1a.png)

#### 可重现的在线演示

图一，使用 `antd.less`：
![use antd.less](https://cloud.githubusercontent.com/assets/352465/23363837/8c14949e-fd37-11e6-9cc4-8dd2cbb88d38.png)

图二，使用 `antd.css`：
![use antd.css](https://cloud.githubusercontent.com/assets/352465/23363994/36470a3c-fd38-11e6-925e-60dbd24b5f7d.png)

**Comment by akecn** [comment]
与之前提过的问题是一样的
#2400

**Comment by lorrylockie** [comment]
同样遇到过

**Comment by benjycui** [comment]
不是很懂，你设置了 `Cascader[disabled]`，所以使用 Less 时的情况才是符合预期的？

**Comment by afc163** [comment]
抱歉，由于 antd.css 和 antd.less 生成的方式目前不完全一样，所以组件的顺序会有些不一致。目前暂时没有好的方案，只能用样式优先级的方式碰到一个改一个。

**Comment by akecn** [comment]
@benjycui 两者都使得组件不可用了，但是使用less的时候，文本内容被覆盖了。你可以看描述中的第一张图，然后比较下 https://riddle.alibaba-inc.com/riddles/8447d83a 这里的效果就知道啦
