### ISSUE TITLE
use `InputNumber` in `AutoComplete` will shows with clear icon incorrectly

### ISSUE THREAD

**Issue by linaaaqi** [ant-design/ant-design#50784]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/6qqrmm)

### Steps to reproduce

1. hover the input bar
2. see the clear icon

### What is expected?

no more clear icon

### What is actually happening?

show with clear icon

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.2.0 |
| System | macOS |
| Browser | chrome |

**Comment by zombieJ** [comment]
AutoComplete will pass props to sub component. Just:

```diff
      <InputNumber
        {...restProps}
        controls={false}
        precision={0}
        value={value}
        onChange={onChange}
++      type="input"
      />
```
