### ISSUE TITLE
Typography.Text组件添加ellipsis和copy后在tabel中渲染卡顿和窗口改变时渲染问题

### ISSUE THREAD

**Issue by whaleluo** [ant-design/ant-design#50786]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-5megdp-rsrhbo?file=demo.tsx)

### Steps to reproduce

1. 如上链接，打开
2. 切换到table页，

### What is expected?

优化显示

### What is actually happening?

1. table首次渲染可以看到第一列先变长后变短，(记得Typography的这个bug好像修复了，但我换了antd最新版本，还是出现了)
2. 然后调节窗口宽度，可以看到第一列在不断step渲染，直到列的最大宽度为止

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.6 |
| System | window |
| Browser | chrome |

---
可以再看下内存，100条数据，内存在800mb左右，不知道是哪儿造成的。
场景：table组件第一列自适应，超出宽度出现省略号并可以拷贝

**Comment by zombieJ** [comment]
### 关于卡顿

当配置 `copy` + `ellipsis` 时，Typography 会降级为 JS 省略，因而会产生性能损耗。每次所在空间的宽度变化都会导致其重新触发省略计算，而在 Table 中的列宽由于自适应会放大重复计算。

### 关于初次渲染会展示全部

继上。原本逻辑为初次渲染不展示内容，待到 JS 运行时切分完毕再渲染。这导致 SSR 时展示为空文本，使得 SEO 不友好。因而改成了初次渲染总是全部渲染。

### 如何优化

移除 `copy` 配置使其变成 CSS 省略，或者通过 Flex 布局实现 Copy 将其与 Typography 解耦：

https://stackblitz.com/edit/react-5megdp-7qfujy?file=demo.tsx,index.tsx

#### 😡 那为什么 Typography.Text 不这么实现？

因为 Typography.Text 语义是文本 `span`，用于 inline 使用，使用 `flex` or `inline-flex` 都会导致 inline 布局的 break。而你的场景里作为 block 来使用，因而可以组合出这个效果。

**Comment by whaleluo** [comment]
OK，明白了，感谢，解决了好几个困惑
