### ISSUE TITLE
flutter 支持

### ISSUE THREAD

**Issue by songangweb** [ant-design/ant-design#50789]
### What problem does this feature solve?

现在国内基本上没有维护 flutter 版本的 ui 库,唯一还有更新的就是腾讯的tdesign（但是更新速度很慢），相对来说还是有需求的。

不考虑投入太多人力去做的话，为什么不考虑创建一个仓库 让社区去来完善这块功能？   我看 github 上  原本是有几个项目的，但是都给没有持续维护了，如果给一些宣传的资源的话，会有人愿意去贡献代码的

### What does the proposed API look like?

ant设计风格的 flutter ui 库

**Comment by songangweb** [comment]
比如   https://github.com/CalsRanna/ant_design_flutter   其实已经实现不少样式了

**Comment by IsKaros** [comment]
今天已经回复过了#50781

**Comment by songangweb** [comment]
上个问题也是我问的，其实就是想确认下是不是完全不会给资源宣传什么的    因为纯个人开发贡献，因为用户量小，会导致更新不下去

**Comment by songangweb** [comment]
> 这个问题今天已经回复过了#50781。既然有人已经在做了，那感觉就更没必要再开新坑。如果觉得更新慢，也可以给这个flutter仓库提供一些支持。

这个项目已经很久不更新

**Comment by zombieJ** [comment]
> 不考虑投入太多人力去做的话，为什么不考虑创建一个仓库 让社区去来完善这块功能？

并不是出现一个仓库就会出现这么一些人，这两者是没有关系的。这个是 antd mobile 的仓库 https://github.com/ant-design/ant-design-mobile，社区贡献者与活跃度远少于 antd。从 antd 角度看，以 antd 的名义建一个本身不会去迭代的仓库让人可以随意 PR 就合并，代码质量与安全都无法得到保证。也是不负责任的表现。而如果要正式的去维护一个项目，那就又回到了 https://github.com/ant-design/ant-design/issues/14548#issuecomment-457470755 所提到的人力精力问题。

> 其实就是想确认下是不是完全不会给资源宣传什么的 因为纯个人开发贡献，因为用户量小，会导致更新不下去

antd 也是从 0 做起的，也走到了现在。开源说到底仍然是用爱发电的问题，有人愿意持之以恒的贡献。那它就能成长，如果不能，就会随着时间而消逝。当一个项目成熟了，给 antd 提 PR 加入推荐是可以的：https://ant-design.antgroup.com/docs/spec/introduce-cn#%E5%89%8D%E7%AB%AF%E5%AE%9E%E7%8E%B0

另外，如之前的 issue 所回复。我们目前没有计划支持。所以这个 issue 就先关了哈~
