### ISSUE TITLE
How to make select in multiple mode inline with form label when overflow

### ISSUE THREAD

**Issue by NicolasCwy** [ant-design/ant-design#50788]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/bug-report-antd-rxqpm7)

### Steps to reproduce

1. Create select item in multiple mode
2. Wrap select in form item and add a label
3. Select options, till second row is filled
4. label is now on top of select input box instead of inline

### What is expected?

Label remains inline with select and select does not expand and occupy its own row

### What is actually happening?

Select occupies a new row when selecting too many options and is not inline with the form label

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
There many ways to realize: `labelRender` or `optionLabelProp`.

**Comment by NicolasCwy** [comment]
@zombieJ I don't think either of these options help me in my case but I have created a discussion [here](https://github.com/ant-design/ant-design/discussions/50820)
