### ISSUE TITLE
今年再次询问 会不会支持 flutter 

### ISSUE THREAD

**Issue by songangweb** [ant-design/ant-design#50781]
### What problem does this feature solve?

flutter官方的 Material 3  觉得设计上不好看

### What does the proposed API look like?

直接基于  flutter Material 3 代码   修改为 ant design 的 ui 样式即可， 这样开发量也会小很多，迁移的门槛会低很多

**Comment by li-jia-nan** [comment]
不会支持，虽然我不能代表官方，但是我觉得官方也大概率不会支持

**Comment by zombieJ** [comment]
目前结论没有改变哈，抱歉： https://github.com/ant-design/ant-design/issues/14548#issuecomment-457470755
