### ISSUE TITLE
Mentions Component Fails to Detect "@" on AZERTY Keyboards (AltGr +  à) in Chrome and Edge Browsers

### ISSUE THREAD

**Issue by oumAds** [ant-design/ant-design#50795]
### Reproduction link

[https://ant.design/~demos/mentions-demo-form](https://ant.design/~demos/mentions-demo-form)

### Steps to reproduce

Switch your system's keyboard layout to AZERTY, then focus on the Mentions input in the browser and press AltGr +  à to type the "@" symbol. Observe that the dropdown for mentions does not appear. For comparison, switch to a QWERTY keyboard and press Shift   2 to type "@". Note that the Mentions dropdown is triggered correctly with the QWERTY layout. The expected behavior is for the dropdown to appear when "@" is typed, regardless of the keyboard layout or input method.

### What is expected?

The dropdown with mention suggestions should appear when "@" is typed, regardless of the keyboard layout or how "@" is input (AltGr   à on AZERTY or Shift   2 on QWERTY).

### What is actually happening?

The dropdown for mentions does not appear

| Environment | Info |
| --- | --- |
| antd | 5.20.5 |
| React | 18.2.0 |
| System | all |
| Browser | chrome/edge |

**Comment by Jarryxin** [comment]
I am willing to solve it

**Comment by Jarryxin** [comment]
![image](https://github.com/user-attachments/assets/08054ea7-db8e-49d7-b23a-be514bf64f0f)
![image](https://github.com/user-attachments/assets/87b786d3-f9b0-4fec-aa6e-aadf0b0dadf9)

May I ask if your button is AltGr+à or AltGr+` ?

**Comment by oumAds** [comment]
I am using AltGr+à, and even when I paste "@" with the AZERTY keyboard, the mentions list doesn't appear.
I have other users in my application who also use the AZERTY keyboard.

**Comment by Jarryxin** [comment]
> I am using AltGr+à, and even when I paste "@" with the AZERTY keyboard, the mentions list doesn't appear. I have other users in my application who also use the AZERTY keyboard.

Use AZERTY input AltGr+à，get "ø" character？

**Comment by Jarryxin** [comment]
> I am using AltGr+à, and even when I paste "@" with the AZERTY keyboard, the mentions list doesn't appear. I have other users in my application who also use the AZERTY keyboard.

What is the value of the input? Can you provide a picture showing AltGr + à?

**Comment by oumAds** [comment]
![Capture d’écran 2024-09-11 164316](https://github.com/user-attachments/assets/45b7bbcf-a29e-49b5-9ead-056554a7cd15)

**Comment by abdeljalil09** [comment]
@Jarryxin AltGr+à shows "@" charachter , also it's windows platform

**Comment by Jarryxin** [comment]
> @Jarryxin AltGr+à shows "@" charachter , also it's windows platform

What is displayed in the mentions

**Comment by oumAds** [comment]
[screen-capture (20).webm](https://github.com/user-attachments/assets/18071bcb-d664-4681-87a9-7439d3c74d05)

**Comment by Jarryxin** [comment]
> screen-capture.20.webm 
> It displays nothing

input  AltGr+à ，what is the value onChange return , what is the KeyCode ?

Do you have an email? It's convenient to contact you

**Comment by abdeljalil09** [comment]
@Jarryxin it's 

![image](https://github.com/user-attachments/assets/7298d1ef-f9d6-442e-8f48-b766c625255f)

**Comment by Jarryxin** [comment]
> @Jarryxin it's
> 
> ![image](https://private-user-images.githubusercontent.com/101262837/367014614-7298d1ef-f9d6-442e-8f48-b766c625255f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTM1MzAsIm5iZiI6MTcyNjE5MzIzMCwicGF0aCI6Ii8xMDEyNjI4MzcvMzY3MDE0NjE0LTcyOThkMWVmLWY5ZDYtNDQyZS04ZjQ4LWI3NjZjNjI1MjU1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwMjA3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjY2NjU1NDlmZjBkNDdkY2MwYzMwMmVkZGE0MDFjYTVkZmUzY2U5M2EzMTcxYzc5ODc3Y2FlMzhlNDg2ZWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jmyoSdBWiUjqcbg-e4gu96TjCpVw5-hNEo4yfH9_yeM)

[https://github.com/react-component/mentions/pull/277](will support)

**Comment by ilyassBZ** [comment]
I spent 2 hours debugging and fixing the issue. When I pushed and tried to link it, I found that you had already solved it. Hahaha, gj @Jarryxin

**Comment by ilyassBZ** [comment]
@Jarryxin never mind it didnt work in azer keybord we dont use ALT  to make @ we use ALTGR whiche is ;  `key === 'AltGraph' ||` you can check  for the fix ([](https://github.com/react-component/mentions/pull/280/commits/ac6176ea1a03a01d81675ccaa95739702be10dbf))

**Comment by Jarryxin** [comment]
> never mind it didnt work in azer keybord we dont use ALT to make @ we use ALTGR whiche is ; `key === 'AltGraph' ||` you can check for the fix

Hi, please pull the latest code [mentions](https://github.com/react-component/mentions) and try to debug it properly? By the way, could you please print out the key for your AltGraph device? I have asked the person who asked the question, and he can use the latest code to tune it up.

**Comment by Jarryxin** [comment]
<img width="1175" alt="screenshot" src="https://github.com/user-attachments/assets/2fab6858-fc09-4599-acb2-06ba157260cd">

**Comment by Jarryxin** [comment]
@ilyassBZ Thank you for your correction.
