### ISSUE TITLE
Refactor modal 

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#5079]
Modal has a few static methods with`any` type, this is not friendly for typescript users, because its `any` type always.

should we consider move it into index.tsx or give a more friendly type definitions, i recommend move it into index.tsx so we don't need write types anymore. any thoughts ?

```ts

export default class Modal extends React.Component<ModalProps, any> {
  static info: any;
  static success: any;
  static error: any;
  static warn: any;
  static warning: any;
  static confirm: any;

...

```

**Comment by afc163** [comment]
@infeng @yesmeck

**Comment by infeng** [comment]
I agree move it into index.tsx, but the usage may change.

**Comment by yesmeck** [comment]
> move it into index.tsx

Could you send a PR to make it more clear?

**Comment by bang88** [comment]
Found a circular dependencies in `confirm.tsx` and `index.tsx` both of them are require `Modal` component, so can't move Modal code to index. if we dont want change the usage behavior, we can write a type definitions  for these static methods.

I will file a PR later, please take a look.

Thanks.

**Comment by yesmeck** [comment]
How about move interface/type definition to a separate file like [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react) [do](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.Props.ts) and antd-mobile already have  [separate definition file](https://github.com/ant-design/ant-design-mobile/blob/master/components/drawer/PropsType.tsx).

**Comment by bang88** [comment]
I don't think we need to do that.
