### ISSUE TITLE
Links working with enclosing tags issue

### ISSUE THREAD

**Issue by FacundoGFlores** [ant-design/ant-design#5080]
I am trying to add an `Icon` for an `Anchor Link`, but it is giving me some problems when I try to enclose it.

So the thing is, when I enclose the `Link` and `Icon` and then I click on the `anchor`, I get a JS error:

`Uncaught TypeError: e.stopPreventDefault is not a function`

I don't know if it is the correct way to add an `Icon` to the `Link`, but it would be useful.  Here is the codepen:

http://codepen.io/FacundoGFlores/pen/GWJdNK?editors=001

Could it be fixed? 

Thank you very much.

**Comment by RaoHai** [comment]
The `title` props of Link could be a React element:

```jsx
<Link title={<span> <Icon type="check" /> Foo </span>} />
```

**Comment by RaoHai** [comment]
`children` props of `Link` is designed for constructing recursive `Link` structure.

**Comment by afc163** [comment]
Should `stopPreventDefault` be removed?
