### ISSUE TITLE
增加一个 workflow，所有打上其他标签的 issues/pull request, 自动取消 unconfirmed 标签

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#50801]
unconfirmed 这个标签缺乏自动清理机制，现在没法用。

**Comment by crazyair** [comment]
必须要有标签吗，默认如果就不加这个 unconfirmed 呢

**Comment by afc163** [comment]
- [] 每日统计最近七天的 unconfirmed issues，并发送到钉钉群内。

**Comment by afc163** [comment]
> 必须要有标签吗，默认如果就不加这个 unconfirmed 呢

这也是一种处理方式，当初加这个标签的初衷是尽量保证所有 issues 被及时反馈，需要有个机制标注需要处理的 issues。

**Comment by thinkasany** [comment]
> * [ ]  每日统计最近七天的 unconfirmed issues，并发送到钉钉群内。

在这个pr中 #50810，我用 actions/github-script 和 schedule 做了一个小的实现，辛苦老板看看

![image](https://github.com/user-attachments/assets/771dc73e-8efc-4479-aa43-001d37bb6c41)
