### ISSUE TITLE
Please remove hardcode css fontFamily at Pagination component

### ISSUE THREAD

**Issue by tringo8311** [ant-design/ant-design#50806]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/components/pagination/style/index.ts](https://github.com/ant-design/ant-design/blob/master/components/pagination/style/index.ts)

### Steps to reproduce

File: components/pagination/style/index.ts
Line: 401
Content: fontFamily: 'Arial, Helvetica, sans-serif',

### What is expected?

Please remove fontFamily that was hardcode

### What is actually happening?

Arial font is a proprietary font family owned by Monotype. You need to purchase a license to use it for commercial purposes.
Helvetica is generally not free to use for commercial purposes

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react |
| System | all |
| Browser | all |

**Comment by zombieJ** [comment]
`font-family` is used the font only when user PC has the font. It will fallback if user not have these. We do not provide the external font resources in antd. 

You can use `font-family` to set the font user have but when use `@font-face` it will get legal issue.

**Comment by tringo8311** [comment]
I don't ask you to provide external font. And I also know I can use @font-face. 
But
- Why hardcode fontFamily at Pagination component?
- Why not hardcode fontFamily for other components?

**Comment by zombieJ** [comment]
As #50808 ref. In old version Pagination use font to show the arrow icon. And the latest code has replaced with `@ant-design/icons`. So yes, it's no need anymore.
