### ISSUE TITLE
colorPrimaryBorderHover 不生效

### ISSUE THREAD

**Issue by tinlee** [ant-design/ant-design#50817]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/sandpack-project-forked-kv7p8n)

### Steps to reproduce

设置colorPrimaryBorderHover ，但是悬浮状态按钮的边框颜色未改变

```js
import { Button, ConfigProvider, Space } from 'antd';
import React from 'react';

const App: React.FC = () => (
  <ConfigProvider
    theme={{
      token: {
        // Seed Token，影响范围大
    
        colorPrimaryBorderHover:"#f55a00",

      },
    }}
  >
    <Space>
      <Button type="primary">Primary</Button>
      <Button>Default</Button>
    </Space>
  </ConfigProvider>
);

export default App;
```
### What is expected?

边框颜色正常显示

### What is actually happening?

设置无效

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18 |
| System | mac |
| Browser | chrome  127.0.6533.122 |

**Comment by zombieJ** [comment]
如果要改 default 的样式的边框用 `defaultHoverColor` & `defaultHoverBorderColor`，primary 边框使用的是透明色，hover 改动的也是 `colorPrimaryHover` 哈~

可以用官网的编辑器调试，会比较直观：https://ant-design.antgroup.com/theme-editor-cn
