### ISSUE TITLE
Form add typescript type ValidateErrorEntity

### ISSUE THREAD

**Issue by cuikaipeng** [ant-design/ant-design#50814]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-5vyrha?file=demo.tsx)

### Steps to reproduce

The onFinishFailed method of the Form component requires the ValidateErrorEntity type, but this type is not exported.

### What is expected?

import { ValidateErrorEntity } from "antd/lib/form/interface";

### What is actually happening?

import { ValidateErrorEntity } from "rc-field-form/lib/interface";

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | MacOS14 |
| Browser | chrome |

**Comment by zombieJ** [comment]
```diff
--  import { Form } from 'antd';
++ import { Form, type FormProps } from 'antd';
--  import { ValidateErrorEntity } from 'antd/lib/form/interface';

--  const onFinishFailed = (errorInfo: ValidateErrorEntity) => {
++  const onFinishFailed: FormProps['onFinishFailed'] = (errorInfo) => {
      console.log('Failed:', errorInfo);
    };
```

<img width="849" alt="截屏2024-09-11 17 43 11" src="https://github.com/user-attachments/assets/96024980-8126-403f-a4eb-9ed02abe0305">
