### ISSUE TITLE
Table: `rowSpan` and `expandable` do not work together

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#50822]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-dcofav?file=src%2FApp.tsx)

### Steps to reproduce

Expand the first row or the second one.

### What is expected?

By expanding the second row, I should see a row with the content of the expandable (in this case, the content is ‘test’). The other rows in the table should remain graphically unchanged.

### What is actually happening?

The first column of the third row ‘disappears’, the second column of the third row (the one with content ‘C’) instead becomes the first column. The ‘disappeared’ column actually overlaps with the expandable of the second row.

No expanded rows:
<img width="805" alt="Screenshot 2024-09-11 at 16 50 01" src="https://github.com/user-attachments/assets/c9f272bc-f4d5-4e9d-8f91-c61da086cf24">

First row expanded:
<img width="805" alt="Screenshot 2024-09-11 at 16 51 30" src="https://github.com/user-attachments/assets/7ddd12ac-0cbe-436d-bbae-2136dd784644">

Second row expanded (same as first row expanded):
<img width="805" alt="Screenshot 2024-09-11 at 16 51 39" src="https://github.com/user-attachments/assets/429cc787-3f1a-4ac3-8b6b-d8eeae18e3a5">

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome |

---
Idea: In tables where there are both expandable rows and ‘rowSpan’, when I expand one of the rows that includes the rowSpan, the content of the single cell is shown again: in the example you can find in the reproduction link, if I expand any of the first three rows, ‘Mike’ might be shown again in the first column instead of showing nothing.

**Comment by zombieJ** [comment]
`rowSpan` is a native td prop. So when use it for merging, it should handle with `expandedRowKeys` together:

https://stackblitz.com/edit/react-pmzdx4?file=demo.tsx,index.css
