### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by BackWorld** [ant-design/ant-design#5082]
我使用了less-loader，怎么还是有问题，我是手动集成的。

webpack + react

/lib/menu/style/index.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../../style/themes/default";
| @import "../../style/mixins/index";
|

**Comment by benjycui** [comment]
You had better ask this question in webpack's community, thanks.
