### ISSUE TITLE
Select组件添加了fileNames以后，添加filterOption筛选不起作用了

### ISSUE THREAD

**Issue by xiumubai** [ant-design/ant-design#50835]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-zyuucw?file=demo.tsx)

### Steps to reproduce

看demo

### What is expected?

能筛选

### What is actually happening?

不能筛选

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.3.1 |
| System | mac |
| Browser | google |

**Comment by zombieJ** [comment]
重现里好像没有用到 `filterOption`，更新一下哈~

**Comment by xiumubai** [comment]
我已经实现了，我起初起的代码是这样的
```js
<Select
  showSearch
  allowClear
  placeholder="请选择"
  options={options.customerType}
  fieldNames={{ label: 'key', value: 'value' }}
  filterOption={(input, option) =>
    (option?.label ?? '').toLowerCase().includes(input.toLowerCase())
  }
</Select>

```
改成这样就可以正常使用filter功能了
```js
Select
  mode="multiple"
  showSearch
  allowClear
  showArrow={true}
  placeholder="请选择扣款类型"
  filterOption={(input, option) =>
    (option?.label ?? '').toLowerCase().includes(input.toLowerCase())
  }
>
  {Array.isArray(options?.deductType) && options.deductType.length > 0
    ? options.deductType.map(item => {
        return (
          <Select.Option key={item.value} value={item.value} label={item.key}>
            {item.key}
          </Select.Option>
        );
      })
    : null}
</Select>
```
antd功能很强大，有时候需要自己去探索，可能并不是傻瓜式的直接用api就可以实现了，得需要探索各种不同的方式才能实现自己想要的效果，非常赞，希望官方可以出一些业务场景下的demo

**Comment by starlight321** [comment]
使用fieldNames 后，在filterOption 中 要用option?. key 来进行过滤了

**Comment by xiumubai** [comment]
> 使用fieldNames 后，在filterOption 中 要用option?. key 来进行过滤了

属实没想到啊，我人傻了
