### ISSUE TITLE
Can not scroll X when use use Table with summary

### ISSUE THREAD

**Issue by lequangkhanh2901** [ant-design/ant-design#50833]
### Reproduction link

[https://github.com/lequangkhanh2901/antd-table-summary-bug](https://github.com/lequangkhanh2901/antd-table-summary-bug)

### Steps to reproduce

Start app with `npm run dev`

### What is expected?

I can swipe on header or summary to scroll the table in X axis

### What is actually happening?

I can not swipe on header or summary to scroll the table

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | ubuntu 20.04 |
| Browser | Brave |

---
The summary of table default is at bottom, to make the summary to top, I must set scroll.y of table = '100%' (may be I use wrong way). In this case, It will happen the bug.

**Comment by zombieJ** [comment]
`fixed: top` only used when `scroll.y` or ` sticky`. If you want to use it, you can consider patch any of it:


https://stackblitz.com/edit/react-azavy6?file=demo.tsx
