### ISSUE TITLE
Steps component window resizing problem

### ISSUE THREAD

**Issue by lironerman7** [ant-design/ant-design#5083]
Steps component window resizing problem

- antd version: 2.7.3
- OS and its version: mac 10.12.3
- Browser and its version: chrome 56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

I use steps component, when opening the window it's looks great:
[http://prntscr.com/edx6vd](http://prntscr.com/edx6vd)

But after I resize the window (Look at the line):
[http://prntscr.com/edx7r6](http://prntscr.com/edx7r6)

#### What do you expected?

The line to adjust to the new window size

#### Re-producible online demo
[http://codepen.io/liron_e/pen/OpVxpx?editors=001](http://codepen.io/liron_e/pen/OpVxpx?editors=001)

**Comment by afc163** [comment]
Thx!
