### ISSUE TITLE
Select 设置 getPopupContainer 挂载到父级元素，且在 Descriptions 中时，下拉列表显示异常

### ISSUE THREAD

**Issue by json-q** [ant-design/ant-design#50848]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-cfkffe?file=demo.tsx)

### Steps to reproduce

Select 设置 getPopupContainer 挂载到父级元素，且放在在 Descriptions 中，此时下拉列表显示异常，下拉列表超出 Descriptions 的部分会被隐藏掉。
原因是 Descriptions 在 5.19.4 做出的更改：https://github.com/ant-design/ant-design/pull/49946

### What is expected?

正常显示

### What is actually happening?

Select显示异常

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | react |
| System | windows |
| Browser | Chrome |

**Comment by afc163** [comment]
@leefinder `overflow: hidden;` 确实有这个副作用。

https://github.com/ant-design/ant-design/pull/49946
