### ISSUE TITLE
在Form List与Table结合的场景下使用的属性dependencies存在不生效情况

### ISSUE THREAD

**Issue by xuerui0709** [ant-design/ant-design#50844]
### Reproduction link

[https://codepen.io/xuerui0709/pen/GRbLQKK?editors=0010](https://codepen.io/xuerui0709/pen/GRbLQKK?editors=0010)

### Steps to reproduce

修改任意一行的姓名（即username字段）把“胡”字去掉，此行的age的验证不触发，
但如果手动修改此行的年龄（即age字段）后，再修改此行的姓名（即username字段），此行的年龄（即age字段）的验证即可正常触发

### What is expected?

修改任意一行的姓名（即username字段）把“胡”字去掉，此行的年龄（即age字段）的验证立即触发

### What is actually happening?

修改任意一行的姓名（即username字段）把“胡”字去掉，此行的age的验证不触发，
需要手动修改此行的年龄（即age字段）后，再修改此行的姓名（即username字段），此行的年龄（即age字段）的验证才能正常触发

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | react |
| System | window11 |
| Browser | 谷歌浏览器 128.0.6613.137（正式版本） （64 位） |

**Comment by xuerui0709** [comment]
在线蹲，麻烦尽快修一下可以吗？

**Comment by MadCcc** [comment]
试下 ProTable 吧

**Comment by xuerui0709** [comment]
这不是一个bug吗？
