### ISSUE TITLE
Typography.Text设置了ellipsis.tooltip，没有显示省略号时，也显示了tooltip

### ISSUE THREAD

**Issue by midfar** [ant-design/ant-design#50847]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-typography-text-n4fs9g)

### Steps to reproduce

1. 打开页面
2. 按 CTRL - 或 CTRL  + 键来调整浏览器缩放比例

### What is expected?

文字能显示完全时，鼠标经过不显示tooltip；
文字显示不完全时，显示...，并且鼠标经过显示tooltip;

### What is actually happening?

文字能显示完全时，鼠标经过可能会显示tooltip，也可能不会显示tooltip

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | Windows 10 |
| Browser | Chrome 128.0.6613.121 |

---
希望文字没显示完整时，鼠标经过显示完整内容；文字能显示完整时，鼠标经过没效果。

**Comment by midfar** [comment]
重现步骤：
1. 打开页面
2. 按 【CTRL】 和【减号】键 、 【CTRL】和【加号】键 来动态调整浏览器缩放比例

上面的加号减号转义了，没显示出来。为了避免歧义，特意说明下。

**Comment by zombieJ** [comment]
感谢反馈，这是已知问题。缩放导致的精度丢失在 js 侧无法感知，也没有办法兜底。如果有强烈需求，可以考虑 `ellipsis={{ suffix: '...' }}` 强行转成 js ellipsis。不过性能会有较大损耗哈~

**Comment by midfar** [comment]
> 感谢反馈，这是已知问题。缩放导致的精度丢失在 js 侧无法感知，也没有办法兜底。如果有强烈需求，可以考虑 `ellipsis={{ suffix: '...' }}` 强行转成 js ellipsis。不过性能会有较大损耗哈~

不对吧，我试了下，如果设置了 ellipsis={{ tooltip: "text", suffix: "..." }} 那么即使能显示完全，末尾也会显示...
