### ISSUE TITLE
国际化ar_EG语言部分组件缺失

### ISSUE THREAD

**Issue by movemoving** [ant-design/ant-design#50841]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-2admxc?file=demo.tsx)

### Steps to reproduce

Image组件语言设置为ar_EG即可复现

### What is expected?

组件的国际化能达到预期，阿拉伯语言下展示的是阿拉伯语

### What is actually happening?

组件的国际化能为达到预期，阿拉伯语言下展示的是英文

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | react |
| System | mac os 14.5 |
| Browser | chrome 128 |

**Comment by nathanlao** [comment]
Submitted a PR and used google translation to double check, do you perhaps wanna have a check as well?
