### ISSUE TITLE
表格expandable中设置fixed：right不生效

### ISSUE THREAD

**Issue by zhuqiaoyue** [ant-design/ant-design#50846]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-cv3tug?file=demo.jsx)

### Steps to reproduce

<Table
    columns={columns}
    dataSource={userRoleData}
    rowKey={(row) => row.id}
    pagination={false}
    expandable={{
      fixed: 'right',
      expandedRowRender: (row) => {
        return <></>;
      },
      onExpand: (expanded, row) => {
        console.log(expanded, row);
      },
    }}
    scroll={{ y: 200 }}
  ></Table>

### What is expected?

展开列固定在行右侧

### What is actually happening?

展开列固定在行左侧

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 17.0.2 |
| System | win10 |
| Browser | Google |

**Comment by yezhonghu0503** [comment]
fixed值在rc-table上的应用有些问题，可以先用expandIconColumnIndex来控制位置

**Comment by yoyo837** [comment]
Fixed in https://github.com/react-component/table/pull/1193

**Comment by JamesFiitWork** [comment]
你确定这个问题修复了？没指定 expandedRowRender 的时候还是不生效。没修彻底，需要重新打开这个问题。
