### ISSUE TITLE
tree控件，半选状态的控制需求

### ISSUE THREAD

**Issue by koen301** [ant-design/ant-design#5085]
#### Environment(required)

- antd version:1.11.2
- OS and its version:windows 10
- Browser and its version:chrome 53

#### What did you do? Please provide steps to re-produce your problem.

后台的权限需要用树表达，因此选用了tree控件，但有个问题是，tree控件某个子菜单选择，父菜单并没有自动选上（全选才会选上），但对后台来说，子菜单如果有权限，那么父菜单一定也有权限，因为这样才能进入子菜单，因此父菜单需要选上，而且值也需要传回给后台。

目前tree控件某个子菜单选中，父菜单界面上是显示半选状态的，但没办法获取这个值，也没没法设置这个半选状态。

#### What do you expected?

希望可以设置某些值是勾选，某些值是半选，同时可以获取半选的key。

**Comment by yesmeck** [comment]
`onCheck` 的第二个参数里会有 `halfCheckedKeys`，是可以拿到父节点的。
