### ISSUE TITLE
在form里使用InputNumber无法重置，通过setFieldsValue，值改变了，但是显示还是原来的值

### ISSUE THREAD

**Issue by frankFree** [ant-design/ant-design#5086]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
http://codepen.io/anon/pen/ZebPzN?editors=001

It works fine, reopen if you provide re-producible demo.
