### ISSUE TITLE
notification 内存泄漏

### ISSUE THREAD

**Issue by zhourengui** [ant-design/ant-design#50863]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-k7x7wy?file=demo.tsx)

### Steps to reproduce

将api放到useEffect中执行 使用setInterval 另一种是同时调用两次也会造成内存泄漏

### What is expected?

预期 就是把我们浏览器的内存吐出来 不要泄漏了

### What is actually happening?

内存泄漏

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | Mac |
| Browser | Chrome |

**Comment by zhourengui** [comment]
@afc163 @jhsu @edd @yang 问题点在motion动画 包括stack也会造成内存泄漏

**Comment by zhourengui** [comment]
@afc163 @jhsu @edd @yang  https://github.com/react-component/notification/pull/361 解决stack造成内存泄漏的pr

**Comment by zhourengui** [comment]
解决motion的内存泄漏pr https://github.com/react-component/motion/pull/55

**Comment by zhourengui** [comment]
最后有个建议 stack hover的时候 应该只对一个notification进行时间的停留 而不是所有 这样如果长时间停留 元素一直在不断增加 网页也会变卡

**Comment by zhourengui** [comment]
https://github.com/fkhadra/react-toastify 一个可以参考的例子 希望antd越来越好 
![image](https://github.com/user-attachments/assets/1145c648-0769-49f1-a2c6-c457ffd2365b)

**Comment by yoyo837** [comment]
fixed in https://github.com/react-component/motion/pull/55
