### ISSUE TITLE
Auto switches documentation theme according to system theme

### ISSUE THREAD

**Issue by rakleed** [ant-design/ant-design#50867]
### What problem does this feature solve?

At night, bright white light is very unpleasant for the eyes, so I have the system set to automatically turn on the dark theme. But your site does not support it.

### What does the proposed API look like?

You can use `prefers-color-scheme` to automatically enable a dark theme.

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/23371
