### ISSUE TITLE
Typography component not longer inherits font in v5

### ISSUE THREAD

**Issue by pbrzosko** [ant-design/ant-design#50879]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-fguhno?file=demo.tsx)

### Steps to reproduce

See reproduction link for v5 (https://stackblitz.com/edit/antd-reproduce-5x-fguhno?file=demo.tsx) and 
v4 (https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-vc2m69?file=%2Findex.js%3A10%2C46).

In v5 text in typography component has 14px, because this is what generated for typography component. In v4 though it has 20px, because of the parent.

### What is expected?

I would expect some switch in theme config for Typography component, that would allow to return back to this behavior.

### What is actually happening?

Font size is not inherited in Typography component.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.3.1 |
| System | macOS Sonoma 14.5 |
| Browser | Google Chrome Version 126.0.6478.127 (Official Build) (arm64) |

**Comment by MadCcc** [comment]
It is intended in v5. You can config it with ConfigProvider globally.

**Comment by pbrzosko** [comment]
Why did you close it? I can not configure it in ConfigProvider to achieve same result as in v4, because fontsize can only be a number?
