### ISSUE TITLE
message 提示框默认不在中间了

### ISSUE THREAD

**Issue by crapthings** [ant-design/ant-design#5087]
antd 2.7.3
rc-notification 1.4.0

![image](https://cloud.githubusercontent.com/assets/1147704/23390331/4e810b32-fda8-11e6-9456-633a8adfe384.png)

**Comment by afc163** [comment]
1. antd@2.7.3 depends on ` rc-notification@1.3.4`, not ` rc-notification@1.4.0`: https://github.com/ant-design/ant-design/blob/2.7.3/package.json#L55
2. It works fine in https://ant.design/components/message/

Please check you development enviornment, make sure you don't import styles of old antd version.

**Comment by afc163** [comment]
You can reopen it if you have re-producible demo.
