### ISSUE TITLE
去掉自定义svg图标配合 Icon 组件的 fill currentColor 属性

### ISSUE THREAD

**Issue by ilxqx** [ant-design/ant-design#50877]
### What problem does this feature solve?

莫名奇妙的填充了图标的颜色。
官方代码：
<img width="469" alt="image" src="https://github.com/user-attachments/assets/9c53d363-900b-46e2-a1b5-041c535f1402">
这样所有按照如下方式：
<img width="443" alt="image" src="https://github.com/user-attachments/assets/71e23d1c-477b-4065-9148-f53a50c5b537">
使用的图标都会默认有个 fill: currentColor，导致原本图标是这样的：
<img width="245" alt="image" src="https://github.com/user-attachments/assets/241d5937-04d6-449f-9674-60a80f2df1b1">
渲染后成了这样：
<img width="148" alt="image" src="https://github.com/user-attachments/assets/1bcb3c0e-a727-4636-9e0f-b62e43196123">

除了写：
<img width="750" alt="image" src="https://github.com/user-attachments/assets/29746cac-7b8f-4a2d-a548-56578937721e">
还有别的办法解决吗？

### What does the proposed API look like?

可以改成 fill: none，至于 fill 到底填什么由使用者自己去传递决定

**Comment by ilxqx** [comment]
写了个在线能打开的示例：
https://stackblitz.com/edit/antd-icon-issue-reproduce?file=src%2Fmain.tsx

**Comment by afc163** [comment]
不能改，会导致 `createFromIconfontCN` `iconfont` 的去色图标就无法设置颜色了。在 https://github.com/ant-design/ant-design-icons/pull/672 里回滚了，只能通过你提供的方式来解决。

![image](https://github.com/user-attachments/assets/c6a60405-8fe8-4fec-b058-12abec9b3860)


https://github.com/ant-design/ant-design/pull/50880#issuecomment-2359896886
