### ISSUE TITLE
Input and Input.Search requires to hit enter double time after clear to search correctly

### ISSUE THREAD

**Issue by alenocera** [ant-design/ant-design#50884]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-qe3zcq?file=demo.tsx,package.json)

### Steps to reproduce

Fill the input.search with some text
Clear the text with the "clear icon" or by deleting it
Fill the input.search with the new text
Hit enter

### What is expected?

Search can be done every time at the first enter hit

### What is actually happening?

At first enter hit, nothing appear
Ar the second one, the search works as expected

| Environment | Info |
| --- | --- |
| antd | 5.19.0 |
| React | 18.3.1 |
| System | nodejs 20.10.0 |
| Browser | chrome latest |

---
Using Redux. This issue does not appears with AntD 5.18.3
I totally don't know where this is issue can be related to. Using AntD > 5.18.3 the issue appears in my environment. 

My peace of code:

```
<Input.Search
        data-cy="global-search-input-text"
        size='small'
        allowClear
        disabled={tableLoad}
        value={valueInput}
        placeholder="Search"
        enterButton
        autoComplete='off'
        onChange={(e) => {
          if (e.target.value === '') {
            setShowMinCharsAlert(false);
            dispatcher(e.target.value);
          }
          setValueInput(e.target.value);
        }}
        onSearch={(qry) => {
          if (qry.length === 0 || qry.length <= 1) {
            setShowMinCharsAlert(true);
          } else {
            dispatcher(qry);
          }
        }}
        onBlur={(e) => {
          if (e.target.value.length >= 2) {
            dispatcher(e.target.value);
          }
        }}
      />
```

**Comment by alenocera** [comment]
This is weird, I noticed that this works in stackblitz but I don't know if this happens because the env is different. I mean: no redux, no cross logic and other stuff like that.
Also, after the lib upgrade I've asked to my team to test and all the members have this behaviour (after delete or clear, needs double enter hit to search.
We have scheduled a session in which we upgrade to the last AntD release and we will perform debug about this, but we are run out of idea right now, all works fine with 5.18.3

**Comment by alenocera** [comment]
UPDATE:
after debugging and testing this issue I've found (kinda) a workaround to not have this behaviour. By adding this piece of code 
```
onKeyDown={(e) => {
   if (e.key === 'Enter') {
       search(e.target.value);
    }
}}
```
as a prop of the <Input.Search />, the behaviour of the search is correct.
`search()` is react callback hook.

Anyway the issue still remaining with the last version of AntD (5.21.1) but continue to work with the 5.18.3.

Still confused on this.

**Comment by alenocera** [comment]
With `5.21.2` the issue seems resolved. I'm going to investigate deeply on all my components, but looks good at the moment.

**Comment by MadCcc** [comment]
Feel free to open new issue if this happened again.
