### ISSUE TITLE
Adjust alignment in Select

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#5088]
![image](https://cloud.githubusercontent.com/assets/3580607/23390585/1711ff88-fdaa-11e6-9f27-c5f0cd1167f1.png)

![image](https://cloud.githubusercontent.com/assets/3580607/23390601/26a075d8-fdaa-11e6-9e21-63cb6264f762.png)

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/23448799/0ee1f540-fe8e-11e6-8efa-67d89065aa6a.png)

**Comment by benjycui** [comment]
ping @afc163

**Comment by afc163** [comment]
- [ ] Dropdown
- [ ] Select
- [ ] Cascader
