### ISSUE TITLE
It'd be better if Tabs has an option to disable the switch-animation of the short horizontal line.

### ISSUE THREAD

**Issue by xieguanglei** [ant-design/ant-design#5089]
It'd be better if Tabs has an option to disable the switch-animation of the short horizontal line.

**Comment by benjycui** [comment]
Do you mean inkBar?


![image](https://cloud.githubusercontent.com/assets/3580607/23393467/039bf58a-fdbe-11e6-8607-bbf66c4f4846.png)

**Comment by xieguanglei** [comment]
Yes, that's right.

**Comment by benjycui** [comment]
Maybe we can make `Tabs[animated]` to control InkBar animation and TabPane animation at the same time?

**Comment by xieguanglei** [comment]
It may depends on ant-design : should we always enable/disable the two animation at the same time.

To me, either a single prop or two seperated props is ok.

**Comment by benjycui** [comment]
`Tabs[animate]` could be `boolean`, which means that enable or disable animation for InkBar and TabPane animation at the same time.

And it could be `Object { inkBar: boolean, tabPane: boolean }`, which will control InkBar and TabPane respectively.

**Comment by benjycui** [comment]
@xieguanglei you can try.

**Comment by xieguanglei** [comment]
working on it.

**Comment by benjycui** [comment]
ping~ @xieguanglei

**Comment by xieguanglei** [comment]
sorry,I went to some trouble setting up the typescript dev-enviroment and I was too busy to figure out how to make it right.

so could I have an extra week on this issue? @benjycui

**Comment by benjycui** [comment]
Take your time. I just ping you, in case that you had forgot..

**Comment by xieguanglei** [comment]
done @benjycui
