### ISSUE TITLE
运行后class没有了，是怎么回事呢?

### ISSUE THREAD

**Issue by GrayLiu** [ant-design/ant-design#509]
class="ant-btn ant-btn-primary" 的 button
运行后看的button 新增属性 data-reactid=".0.1"
但是 class 缺失了，没有样式是怎么回事呢？
 版本号 0.9.x

**Comment by afc163** [comment]
`className="ant-btn ant-btn-primary"`

不如先看看 react 的官方文档？http://facebook.github.io/react/
