### ISSUE TITLE
select单选和多选，搜索栏可输入内容的宽度表现不一致

### ISSUE THREAD

**Issue by liu-collab** [ant-design/ant-design#50904]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

在搜索栏输入字符搜索

### What is expected?

搜索栏可输入内容的宽度表现不一致

### What is actually happening?

搜索栏可输入内容的宽度表现一致

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2 |
| System | win10 |
| Browser | chrome 122 |

单选 
![image](https://github.com/user-attachments/assets/2c3becc5-e67e-44d2-bda6-9d653293c5e8)
多选 
![image](https://github.com/user-attachments/assets/9f730006-d217-4290-a760-16b5e2bbc3b2)

**Comment by yezhonghu0503** [comment]
这个bug我正在处理，稍后提个pr讨论一下
