### ISSUE TITLE
Layout sider width dynamic adjustment has higher latency

### ISSUE THREAD

**Issue by tuyu79** [ant-design/ant-design#50900]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-mip51x?embed=1&file=demo.tsx)

### Steps to reproduce

Just drag the scroll bar on horizon, and compare blue scroll bar with purple scroll bar to see the latency differecen

### What is expected?

Layout sider resize the width as smooth as original div

### What is actually happening?

Layout Sider has higher latency than original div

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | Umi 4.3.19 |
| System | MacOS Sonoma |
| Browser | 128.0.2739.79  (arm64) |

**Comment by wanpan11** [comment]
Because layout-sider has a transition attribute，v5.21.0 will have a new component Splitter, you can try it later

![image](https://github.com/user-attachments/assets/e02e6832-a790-4ed9-9d81-2d54cb97d049)

**Comment by afc163** [comment]
https://stackblitz.com/edit/antd-reproduce-5x-7vpq6y?file=demo.tsx

```diff
- <Sider width={siderWidth}>
+ <Sider width={siderWidth} style={{ transition: 'none' }}>
```

**Comment by tuyu79** [comment]
it works, thanks a lot
