### ISSUE TITLE
Antd Select component mutates list on scroll when a duplicate value exists in OptGroup

### ISSUE THREAD

**Issue by divyeshsachan** [ant-design/ant-design#50903]
### Reproduction link

[https://codepen.io/aggagi/pen/RwzzEwV?editors=001](https://codepen.io/aggagi/pen/RwzzEwV?editors=001)

### Steps to reproduce

Put Option with same value in multiple OptGroup and scroll up and down few times, which shows the error.

### What is expected?

Scroll should function correctly

### What is actually happening?

Option list duplicates same items multiple times on scroll up/down

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | react |
| System | All |
| Browser | All |

---
In previous same related question, it was reported when multiple Options exists with same value ([#39718 ](https://github.com/ant-design/ant-design/issues/39718)).

In OptGroup, we have multiple use cases where we need to show Options with same or another label in various OptGroup with same value.
For example (In top show Top Cities OptGroup with few items, and then another OptGroup with "All Cities").

It breaks Select component. Same value with unique "key" should be allowed.

Currently "value" is used as a "key" in Option/OptGroup, There are cases where we need to show item with same value in more than one groups and it breaks the Select.

Consider and allow "key" in Option props, and use its "key" when specified or use "value" when "key" is not provided.

**Comment by afc163** [comment]
That is intended, the items with duplicated key leads to unexpected behavior, even belongs to different OptGroup.
