### ISSUE TITLE
chrome开启Experimental Web Platform features      input输入框输入----- 前面内容会自动增加间距

### ISSUE THREAD

**Issue by 13621272512** [ant-design/ant-design#50901]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-ch8ta6?file=demo.tsx)

### Steps to reproduce

chrome开启Experimental Web Platform features   进入antd官网   输入框输入‘123任意文字---------------’  任意文字前方会自动增加间距

### What is expected?

不增加间距

### What is actually happening?

增加间距

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.2.0 |
| System | win10 |
| Browser | chrome |

---
关联issues地址https://github.com/ant-design/ant-design/issues/50862   重现视频在关联issues

**Comment by 13621272512** [comment]
重现视频
https://github.com/user-attachments/assets/3205d22c-fad6-4698-8b76-ba736333b05e
chrome需开启Experimental Web Platform features
![image](https://github.com/user-attachments/assets/6a6616b6-2a09-45ec-9686-0798870f2ca5)

**Comment by afc163** [comment]
实验性的特性本身不太稳定，很可能是浏览器本身的 bug，不建议针对这些开关去做修复。

**Comment by 13621272512** [comment]
> 实验性的特性本身并不稳定，很可能是浏览器本身的bug，不建议针对这些开关进行修复。

项目播放器有需求需开启Experimental Web Platform features实现   跟输入框这个问题冲突   我应该怎么处理这个问题

**Comment by afc163** [comment]
可以看看源码帮忙看看是否有解法

**Comment by 13621272512** [comment]
![d88cd25771d4d98d30cbdb39cd06f142](https://github.com/user-attachments/assets/83b90a09-f405-4ab3-abd9-3edf13786843)
chrome浏览器的问题  原生输入框也是这样  建议关闭issues

**Comment by afc163** [comment]
@13621272512 你是可以自己关掉的。
