### ISSUE TITLE
input中placeholder和输入文字闪烁问题

### ISSUE THREAD

**Issue by jpdan** [ant-design/ant-design#5091]
antd version:2.7.3
@media (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm){
    input.ant-input{
      line-height: inherit;
    }
  }
上述样式在chrome上正常，在360浏览器下不管是兼容还是急速模式，都会发生闪烁问题
不得已只能重写覆盖了，如下
@media (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm){
    input.ant-input{
      line-height: normal;
    }
  }
以前是没问题的，昨天更新到最新版本出现的

**Comment by afc163** [comment]
`line-height: normal` can not resolve this issue: https://github.com/ant-design/ant-design/issues/4987

**Comment by afc163** [comment]
I can't found any flash in 360@8.1 , could you provide a GIF of what you see?

<img width="1133" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23396734/1a3dc8b0-fdd0-11e6-9e9a-d4add39425c2.png">

**Comment by jpdan** [comment]
360版本：8.1.1.248
内核版本：45.0.2454.101
![qq 20170228164742](https://cloud.githubusercontent.com/assets/3361732/23397992/b0d86668-fdd5-11e6-9ea5-655303537157.png)

**Comment by jpdan** [comment]
找到问题了，是用了官方示例中高级搜索中的样式.ant-advanced-search-form，以前这个样式是这样的：
.ant-advanced-search-form {
      padding: 16px 8px;
      margin-bottom: 16px;
      background: #f8f8f8;
      border: 1px solid #d9d9d9;
      border-radius: 6px;
    }

    /* 由于输入标签长度不确定，所以需要微调使之看上去居中 */
    .ant-advanced-search-form > .ant-row {
      position: relative;
      left: -6px;
    }

    .ant-advanced-search-form .ant-btn + .ant-btn {
      margin-left: 8px;
    }

**Comment by jpdan** [comment]
![image](https://cloud.githubusercontent.com/assets/3361732/23399570/a1502cac-fddb-11e6-9ff6-390971834ca7.png)
现在官方示例中高级搜索在360上，鼠标移上去也会闪烁

**Comment by afc163** [comment]
Fixed in 2.7.4
