### ISSUE TITLE
[2.7.3] TreeSelect不出菜单选项了，紧急

### ISSUE THREAD

**Issue by pixystone** [ant-design/ant-design#5092]
demo可以复现：

http://codepen.io/anon/pen/qrOONR?editors=001

今天突然发现线上有这个问题，但是开发环境`2.7.0`不存在问题。

没改过任何代码，但发布过一次，所以由依赖`^2.7.0`直接装的应该是最新的`2.7.3`了。

**Comment by xuyang2** [comment]
@pixystone 你可以先把 `^2.7.0` 改成 `2.7.0`  精确版本再发布一次

**Comment by yesmeck** [comment]
Demo is also broken https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable

**Comment by afc163** [comment]
introduced by https://github.com/react-component/trigger/pull/43 ..

**Comment by pixystone** [comment]
指定`2.7.0`发布到日常，还是有问题，有办法通过css先workround么？

**Comment by pixystone** [comment]
![image](https://cloud.githubusercontent.com/assets/3050696/23397852/23783d20-fdd5-11e6-8942-e8c8260e603e.png)

我试图通过css解决，但是在这里加上`height: 100%`后，TreeSelect选项可以看见了，但是这个div会覆盖住整个页面，无法交互

**Comment by afc163** [comment]
是的，我也发现了。

**Comment by afc163** [comment]
你可以暂时先加上来修复。

```
.ant-select-dropdown {
  max-height: 100vh !important;
}
```

**Comment by pixystone** [comment]
我打算暂时限定`react-component/trigger`的版本为`1.8.2`，可行吗？ @afc163

**Comment by pixystone** [comment]
限制`rc-trigger`的版本确实没有效果，我先用css试试

**Comment by pixystone** [comment]
@afc163 你说的可行，但我发现这样也行：

![image](https://cloud.githubusercontent.com/assets/3050696/23398950/6675cc1a-fdd9-11e6-8faa-87b964e2366f.png)

**Comment by afc163** [comment]
https://github.com/react-component/trigger/pull/44

**Comment by afc163** [comment]
要等 patch 版本。

**Comment by afc163** [comment]
Fixed in 2.7.4
