### ISSUE TITLE
Upload 设置 directory={true} 之后无法选择单个文件

### ISSUE THREAD

**Issue by sugia** [ant-design/ant-design#50927]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-ztdews?file=demo.tsx)

### Steps to reproduce

点击页面正中间上传文件大按钮；
随意选择单个文件；
单个文件显示灰色，无法选择单个文件上传。

### What is expected?

应该能允许单个文件上传，即使是在设置了 directory={true} 之后。

### What is actually happening?

Upload 设置了 directory={true} 之后，模块不允许单个文件上传。

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | 18.3.1 |
| System | Ubuntu 22.04 LTS |
| Browser | Firefox 129.0.2 (64-bit) |

**Comment by kiner-tang** [comment]
只能选择目录是符合预期的，设置 directory 时，实际上用的是原生的 `webkitdirectory ` 能力。
参考：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/input/file#webkitdirectory
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/43f27bae-1e41-498f-9977-5b6fe960a1c3">

**Comment by sugia** [comment]
感谢回复。请问如何才能让模块同时支持：1.上传目录；2.上传单个文件

**Comment by afc163** [comment]
在 HTML 中，`<input type="file">` 元素不能同时支持**单个文件上传**和**目录上传**，因为：

- **单个文件上传**可以通过 `multiple` 属性允许选择多个文件。
- **目录上传**依赖于非标准属性 `webkitdirectory` 和 `directory`，这两个属性告诉浏览器允许选择整个目录。

但是，浏览器在同一个 `<input>` 元素上不能同时支持这两个行为。你无法通过一个 `<input>` 元素同时让用户选择**单个文件**和**目录**，因为它们的行为是互斥的：当你选择了 `webkitdirectory` 之后，浏览器不再允许你选择单个文件。

### 可能的变通方案

为了实现“**同一输入框既能选择单个文件也能选择目录**”，你可以使用 JavaScript 动态切换 `<input>` 的属性，具体步骤如下：

1. 使用一个 `<input>` 元素。
2. 通过 JavaScript 动态设置该 `<input>` 元素是允许**单个文件**还是**目录上传**。
3. 提供一个切换按钮或开关，让用户选择是在上传文件还是上传目录。

### 实现方案示例

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>文件和目录上传</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .upload-container {
            margin-bottom: 20px;
        }
        label {
            display: inline-block;
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            cursor: pointer;
            border-radius: 4px;
        }
        #fileList {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h2>文件/目录上传</h2>

    <!-- 选择上传模式 -->
    <div class="upload-container">
        <label for="uploadMode">请选择上传模式：</label>
        <select id="uploadMode">
            <option value="file">上传文件</option>
            <option value="directory">上传目录</option>
        </select>
    </div>

    <!-- 上传按钮 -->
    <div class="upload-container">
        <label for="fileInput" id="fileInputLabel">选择文件</label>
        <input type="file" id="fileInput" multiple>
    </div>

    <div id="fileList"></div>

    <script>
        const fileInput = document.getElementById('fileInput');
        const fileInputLabel = document.getElementById('fileInputLabel');
        const uploadMode = document.getElementById('uploadMode');
        const fileList = document.getElementById('fileList');

        // 动态切换输入框的模式
        uploadMode.addEventListener('change', function() {
            if (this.value === 'directory') {
                fileInput.setAttribute('webkitdirectory', ''); // 设置为目录上传
                fileInput.setAttribute('directory', '');
                fileInputLabel.textContent = '选择目录';
            } else {
                fileInput.removeAttribute('webkitdirectory'); // 移除目录上传属性
                fileInput.removeAttribute('directory');
                fileInputLabel.textContent = '选择文件';
            }
        });

        // 处理文件选择
        fileInput.addEventListener('change', function() {
            const files = this.files;
            displayFiles(files);
        });

        // 显示选中的文件或目录
        function displayFiles(files) {
            fileList.innerHTML = '<h3>已选择的项目：</h3>';
            for (let i = 0; i < files.length; i++) {
                const file = files[i];
                const fileInfo = document.createElement('p');
                fileInfo.textContent = `${file.webkitRelativePath || file.name} - ${file.size} 字节`;
                fileList.appendChild(fileInfo);
            }
        }

    </script>
</body>
</html>
```

### 如何运行：

1. **上传模式选择**：提供了一个下拉菜单，用户可以选择上传模式：
   - **上传文件**：可以选择单个或多个文件。
   - **上传目录**：可以选择整个目录。
   
2. **动态切换输入框模式**：
   - 当用户选择“上传目录”时，`<input>` 的 `webkitdirectory` 和 `directory` 属性会被动态添加，以允许目录上传。
   - 当用户选择“上传文件”时，`webkitdirectory` 和 `directory` 属性会被移除，只允许文件上传。

### 关键点：

- **动态属性更改**：通过 JavaScript 动态添加或移除 `webkitdirectory` 和 `directory` 属性来实现“同一个输入框”支持文件和目录上传。
- **用户体验**：用户可以通过下拉菜单选择上传模式，界面清晰明了。

### 总结

虽然 HTML 本身不支持在同一个 `<input>` 元素上同时上传文件和目录，但通过 JavaScript 动态切换属性，可以实现类似的效果。
