### ISSUE TITLE
DatePicker设置disabledDate范围区间开始日期不可选

### ISSUE THREAD

**Issue by Arnaul** [ant-design/ant-design#50932]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jc4yhd?file=demo.tsx)

### Steps to reproduce

设置disabledDate范围区间2024-09-20 10:00:00 到2024-09-22 10:00:00。20号日期被disable了

### What is expected?

设置disabledDate范围区间2024-09-20 10:00:00 到2024-09-22 10:00:00。20号日期可选

### What is actually happening?

设置disabledDate范围区间2024-09-20 10:00:00 到2024-09-22 10:00:00。20号日期被disable了

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16 |
| System | mac |
| Browser | chrome |

---
import React from 'react';
import './index.css';
import { DatePicker, Space } from 'antd';
import type { GetProps } from 'antd';
import dayjs from 'dayjs';
import customParseFormat from 'dayjs/plugin/customParseFormat';

type RangePickerProps = GetProps<typeof DatePicker.RangePicker>;

dayjs.extend(customParseFormat);

const { RangePicker } = DatePicker;

// eslint-disable-next-line arrow-body-style
const disabledDate: RangePickerProps['disabledDate'] = (current) => {
  // Can not select days before today and today
  // return current && current < dayjs().startOf('day');
  return current && current < dayjs('2024-09-20 11:00:00');
};

const App: React.FC = () => (
  <Space direction="vertical" size={12}>
    <DatePicker
      format="YYYY-MM-DD HH:mm:ss"
      disabledDate={disabledDate}
      showTime
    />
  </Space>
);

export default App;

**Comment by zombieJ** [comment]
如果你需要按照日期比较，那 `disabledDate` 里的比较逻辑就应该按照 date 来而不是 hour。把 `10:00:00` 改成 `00:00:00`，或者如你写的 `dayjs('2024-09-20 10:00:00').startOf('day')`。
