### ISSUE TITLE
AutoComplete嵌套Input.TextArea当浮层没展示时，arrow up down也不生效

### ISSUE THREAD

**Issue by hans000** [ant-design/ant-design#50935]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-k1wjbb?file=demo.tsx)

### Steps to reproduce

多行文本下，按arrow up down没效果
```
      <AutoComplete>
        <Input.TextArea />
      </AutoComplete>
```

### What is expected?

-

### What is actually happening?

-

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | react |
| System | macos |
| Browser | chrome最新 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/36371#issuecomment-2271640837
