### ISSUE TITLE
Table中 一行包含树形数据 嵌套子表格， 树形数据分级没有缩进，只有子表格缩进

### ISSUE THREAD

**Issue by idvuweiuvbwiuevbweubviuwqve** [ant-design/ant-design#50930]
### Reproduction link

https://lightly.teamcode.com/c9ae8513/antd-table-demo

### Steps to reproduce

 <Table
            expandable={{
                expandedRowRender,
                rowExpandable: (record) => true, // 控制行是否可展开
            }}/>
    const expandedRowRender = (unit: any) => {
        return (
            <Table
                columns={productColumns}
                className="product-table"
                dataSource={unit.productAndQtys}
                pagination={false}
                scroll={{ x: 1500, y: 600 }}
            />
        );
    };

### What is expected?

希望能够子表格和分级数据都能缩进

### What is actually happening?

只有子表格缩进，分级数据没有缩进

| Environment | Info |
| --- | --- |
| antd | 5.10.0 |
| React | 18.2 |
| System | macOS ventura 13.67 |
| Browser | 128.0.6613.138 |

**Comment by idvuweiuvbwiuevbweubviuwqve** [comment]
OK了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/44009#issuecomment-1665037044
