### ISSUE TITLE
`xs` breakpoint not true as screen grows

### ISSUE THREAD

**Issue by bombillazo** [ant-design/ant-design#50939]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-8rhlbh?file=demo.tsx)

### Steps to reproduce

- Setup Grid.useBreakpoint hook
- Resize screen to see that `xs` breakpoint is not true when it passes to `sm`, while all others remain true as the screen grows

### What is expected?

`xs` remains true when the screen grows

### What is actually happening?

`xs` becomes false when going to the `sm` screen size

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | https://stackblitz.com/edit/antd-reproduce-5x-8rhlbh?file=demo.tsx |
| System | MacOS |
| Browser | Chrome |

**Comment by mystic3333** [comment]
let me try this problem

**Comment by zombieJ** [comment]
I've check the media query. `xs` is special for fallback usage. I'm not sure whether this is by design:

<img width="188" alt="截屏2024-09-23 11 47 58" src="https://github.com/user-attachments/assets/6de32af8-61b5-4a75-9cdc-2f2fc161de5b">

**Comment by zombieJ** [comment]
The `xs` is used for some mobile check logic. Some developer may use `xs` mark for checking. Modify may cause break change. Let me add doc instead.

**Comment by bombillazo** [comment]
It's super counter intuitive if this is by design, specially for a mobile first approach.

We'll simply not use XS then.
