### ISSUE TITLE
[input/输入框] 希望增加AutoCompleteSource功能，在输入时自动匹配历史记录

### ISSUE THREAD

**Issue by Bonge-chen** [ant-design/ant-design#50968]
### What problem does this feature solve?

原netframework框架系统控件textbox具备该功能，希望该控件同样具备该功能，谢谢

### What does the proposed API look like?

as you wish

**Comment by Bonge-chen** [comment]
> 没理解这个功能是干什么的，具体点？

https://www.cnblogs.com/LuoCore/p/14303283.html

**Comment by Bonge-chen** [comment]
> 没理解这个功能是干什么的，具体点？

当前input控件没有这个属性

**Comment by Bonge-chen** [comment]
> https://www.cnblogs.com/LuoCore/p/14303283.html

模糊输入，自动补全功能。textbox（input）和combbox（selet）都可具备该功能，具体参考这个链接https://www.cnblogs.com/LuoCore/p/14303283.html
谢谢

**Comment by afc163** [comment]
antd AutoComplete 是纯粹的 UI 组件，不具备服务端存储能力，需要自行构建。

**Comment by Bonge-chen** [comment]
> antd AutoComplete 是纯粹的 UI 组件，不具备服务端存储能力，需要自行建设。

那用input控件如何实现自动补全这个功能呢，input控件没有AutoCompleteSource属性，数据也绑定不了呢

**Comment by afc163** [comment]
看下 AutoComplete 的 demo：https://ant.design/components/auto-complete-cn

**Comment by Bonge-chen** [comment]
> 看下 AutoComplete 的 demo：https://ant.design/components/auto-complete-cn

收到，谢谢。我看了下，这个是web的控件demo，我正在开发的是winform桌面程序，使用的这个开源控件
https://github.com/AntdUI/AntdUI
这个控件里面的input输入框可能没有这个功能
谢谢了

**Comment by afc163** [comment]
不如去那里提个 issue?

**Comment by Bonge-chen** [comment]
> 不如去那里提个 issue?

哈哈，已经在gitee源码那里提问了，使用winform的人太少，那边门可罗雀，不像这边门庭若市，哈哈。总之，非常感谢帮忙解答
