### ISSUE TITLE
Cascader.Panel 无法通过disabled进行禁用 依旧可以选择

### ISSUE THREAD

**Issue by daidaic** [ant-design/ant-design#50961]
### What problem does this feature solve?

解决Cascader的APi一致性问题
https://codepen.io/Aliceiii/pen/gOVObWg?editors=001

### What does the proposed API look like?

Cascader增加disabled,一致性api

**Comment by daidaic** [comment]
> 给 `<Cascader.Panel /> ` 提供的 `options` 中添加 `disabled` 字段就好了。
> 
> 另外上下文中的 disable 可以通过 `const { componentDisabled } = ConfigProvider.useConfig()` 得到
> 
> ```tsx
> import { StrictMode } from 'react'
> import { createRoot } from 'react-dom/client'
> import 'normalize.css'
> import 'antd/dist/reset.css'
> import { Cascader } from 'antd'
> 
> const App = () => {
>   return (
>     <Cascader.Panel
>       options={[
>         {
>           value: 'zhejiang',
>           label: 'Zhejiang',
>           disabled: true,
>           children: [
>             {
>               value: 'hangzhou',
>               label: 'Hangzhou',
>               disabled: true,
>               children: [
>                 {
>                   value: 'xihu',
>                   disabled: true,
>                   label: 'West Lake',
>                 },
>               ],
>             },
>           ],
>         },
>       ]}
>     />
>   )
> }
> 
> createRoot(document.getElementById('root')!).render(
>   <StrictMode>
>     <App />
>   </StrictMode>,
> )
> ```

你好 ,我需要的是全局禁用, 和Select Input Checkbox那样 
![image](https://github.com/user-attachments/assets/ab24ba31-b403-4245-976f-55aea0bb495d)

**Comment by aojunhao123** [comment]
I would love to do this feature

**Comment by aojunhao123** [comment]
@li-jia-nan @Wxh16144 @afc163 @zombieJ 大佬们这个issue可以关了
