### ISSUE TITLE
5.21.0 Button link 的颜色跟随了主题色，与之前不同

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#50960]
### Reproduction link

5.21.0

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-4zlkbr?file=demo.tsx)

5.20.6

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-roxbwp?file=demo.tsx)
### Steps to reproduce

点击不同链接进行对比

### What is expected?

与之前版本颜色一致

### What is actually happening?

与之前版本颜色不一致

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
建两个 stackblitz 对比一下。
