### ISSUE TITLE
table  rowClassName 固定列，会出现行样式不统一

### ISSUE THREAD

**Issue by wuxinheng** [ant-design/ant-design#50966]
### Reproduction link

[https://codepen.io/wuxinheng/pen/ZEgEExa?editors=0110](https://codepen.io/wuxinheng/pen/ZEgEExa?editors=0110)

### Steps to reproduce

table 使用fixed 通过 rowClassName实现斑马纹，固定列样式没有生效

### What is expected?

rowClassName 每一行样式一致

### What is actually happening?

滚动行样式生效，固定列的行样式不生效

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 官网示例版本 |
| System | 已经复现 |
| Browser | firefox 130.0.1 |

**Comment by wuxinheng** [comment]
建议1不显示，
建议2不能到达效果，https://codepen.io/wuxinheng/pen/ZEgEExa?editors=0110

**Comment by wuxinheng** [comment]
建议1不显示，
建议2不能到达效果，https://codepen.io/wuxinheng/pen/ZEgEExa?editors=0110

**Comment by wuxinheng** [comment]
目前不考虑建议1，
建议2测试不能到达效果，https://codepen.io/wuxinheng/pen/ZEgEExa?editors=0110

**Comment by afc163** [comment]
See 

- https://github.com/ant-design/ant-design/issues/31483#issuecomment-884847331
- https://github.com/ant-design/ant-design/issues/44124
- https://github.com/ant-design/ant-design/issues/39161#issuecomment-1471863588
