### ISSUE TITLE
[ant design]在Form中使用Table，配置了列筛选，筛选后js报错，页面直接崩溃了

### ISSUE THREAD

**Issue by Karl-Xu** [ant-design/ant-design#50977]
### Reproduction link

[https://codepen.io/Karl-Xu/pen/yLmLjpq](https://codepen.io/Karl-Xu/pen/yLmLjpq)

### Steps to reproduce

1、clone github项目
2、npm intall
3、npm start
4、点击”姓名“列筛选icon
5、在展开的下拉列表选择”张三“
6、点击”OK“按钮

### What is expected?

表格正常筛选出仅含有”张三“的数据

### What is actually happening?
页面崩了
![IMG_4055](https://github.com/user-attachments/assets/62016825-e561-41b0-9816-7ba434325a0d)

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18.x |
| System | macOS sonoma 14.5 |
| Browser | Chrome版本 124.0.6367.209（正式版本） (x86_64) |

**Comment by coding-ice** [comment]
最好提供一个可复线在线的 demo 哦，比如：stackblitz

**Comment by Karl-Xu** [comment]
> 最好提供一个在线的可复线 demo 哦，比如：stackblitz

你好，已提供在线demo：https://codepen.io/Karl-Xu/pen/yLmLjpq
