### ISSUE TITLE
renderTabBar 编写 Select 组件后，内部的 onTabClick 都不执行

### ISSUE THREAD

**Issue by James-23-i** [ant-design/ant-design#50971]
### Reproduction link

[https://ant-design.antgroup.com/components/tabs-cn#tabs](https://ant-design.antgroup.com/components/tabs-cn#tabs)

### Steps to reproduce

```HTML
<Tabs
    style={{ width: '100%' }}
    onTabClick={(key) => {
        console.log(key, 'tabs key')
        setTabType(key);
    }}
    type="card"
    size="small"
    renderTabBar={(props, DefaultTabBar) => {
        return <Select options={[
        { label: '1', value: 'dept' },
        { label: '2', value: 'role' },
        { label: '3', value: 'user' },
        { label: '4', value: 'orgType' },
        { label: '5', value: 'personGroup' },
        ]} onChange={(key) => setTabType(key)}>
        <DefaultTabBar {...props} onTabClick={(key) => {
            console.log('执行', key, 'DefaultTabBar')
            setTabType(key)
        }}>
            {(tabNode) => {
            // ...针对每个 tab 做一些操作
            return <div>{tabNode}</div>
            }}
        </DefaultTabBar>
        </Select>
    }}
/>
```

### What is expected?

能正常执行 onTabClick

### What is actually happening?

不能正常执行 onTabClick

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16 |
| System | win11 |
| Browser | chrome |

**Comment by afc163** [comment]
Select 的 children 不能传一个 DefaultTabBar，应该说 Select 的 children 不支持 Select.Option 以外的任何其他节点。

**Comment by James-23-i** [comment]
> Select 的 children 不能传一个 DefaultTabBar，应该说 Select 的 children 不支持 Select.Option 以外的任何其他节点。

那应该如何编写才能将 tab 替换成 select，如果 DefaultTabBar 的 children 为 Select，那么又会出现重复的 tabs

**Comment by afc163** [comment]
什么需要将 tab 替换成 select ？

**Comment by James-23-i** [comment]
> 什么需求需要将 tab 替换成 select ？

tab 在移动端展示过多，需换成 select 让用户下拉选择，减少占比空间。如果用 tab 自带的滚动，单个 tab 用户无法预知可滚动。
