### ISSUE TITLE
RangePicker组件选完时间会清空

### ISSUE THREAD

**Issue by ZeroCodeLin** [ant-design/ant-design#50979]
### Reproduction link

[https://codepen.io/debugger119/pen/JjQLyze?editors=001](https://codepen.io/debugger119/pen/JjQLyze?editors=001)

### Steps to reproduce

1.开始时间选择到日
2.不点击时分秒，直接点击结束时间的输入框选择时间后确定
![1](https://github.com/user-attachments/assets/dd00adc2-dcd4-4337-832f-854de3c3a80b)

### What is expected?

保留所选时间

### What is actually happening?

清空了所选时间

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 18 |
| System | windows |
| Browser | chrome |

---
5.13的版本还是正常，5.14后会出现这个问题
带时分秒的范围选择器，点击开始时间输入框选择日期后不选择时分秒，点击结束日期输入框选择日期后点击确定，所选的时间会全部清空。5.13的版本还是正常，5.14后会出现这个问题

**Comment by ZeroCodeLin** [comment]
@Wxh16144 @zombieJ

**Comment by zombieJ** [comment]
交互逻辑需要调整成打开一个后不选择不能跳另一个，感觉不太好改，得看看
