### ISSUE TITLE
Tree 组件增加缩进indent 设置

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#50981]
### What problem does this feature solve?

难看的antd默认indent，你们这个indent是给人看的？自己demo看过么

![image](https://github.com/user-attachments/assets/6cc8a9df-d404-4f74-a4d3-d4df732d7310)

### What does the proposed API look like?

indentSize

**Comment by MadCcc** [comment]
暂时没有 api 提供呢，但是可以通过 css 修改这个元素的 width 来实现
![image](https://github.com/user-attachments/assets/3beee4a4-cd57-4fff-bd05-fe4967505dab)

**Comment by cangSDARM** [comment]
> 暂时没有 api 提供呢，但是可以通过 css 修改这个元素的 width 来实现 ![image](https://private-user-images.githubusercontent.com/27722486/370120429-3beee4a4-cd57-4fff-bd05-fe4967505dab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDkzOTgsIm5iZiI6MTcyNzE0OTA5OCwicGF0aCI6Ii8yNzcyMjQ4Ni8zNzAxMjA0MjktM2JlZWU0YTQtY2Q1Ny00ZmZmLWJkMDUtZmU0OTY3NTA1ZGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAzMzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMzc1NTcxMGZkOWZmZmYzOTkyMjU0MWZiNWVjYTk0NWE1OTEyZDk5MDc1ZGRiM2Q3YjUyM2JhYjg1YjcxNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2DBZYIJAJBg_rSX5NGK8_T_gk2DrSMo7jqiW3GjRuoY)

这个css改了后和 showLine设置有冲突

![image](https://github.com/user-attachments/assets/a6cda765-eb27-451f-a75a-95a489d4a762)

line 就没对齐了

**Comment by zombieJ** [comment]
预期的样式是什么样子的，给个图看看哈~

**Comment by cangSDARM** [comment]
> 期望的缩进长啥样的🤔

Icon 不至于说在demo上那么宽吧？
![image](https://github.com/user-attachments/assets/5a6c8f6c-e128-4b21-8d84-5cf776372d6a)

我改的
![image](https://github.com/user-attachments/assets/ec48748f-7a34-4438-a8bc-5f3b56637534)

**Comment by zombieJ** [comment]
感谢贴图，看到你的另一个 issue 了：https://github.com/ant-design/ant-design/issues/50983

的确这几个图标宽度可以保持一致，thx

**Comment by afc163** [comment]
确实可以整体调整一下。

**Comment by zombieJ** [comment]
有兴趣来个 PR 不

**Comment by afc163** [comment]
另外，建议遵守一下社区评论的准则，避免不友善的发言：https://github.com/ant-design/ant-design/blob/master/CODE_OF_CONDUCT.md

**Comment by arvinxx** [comment]
说实话，antd 的 Tree 是不好看… style 过于陈旧了

**Comment by yoyo837** [comment]
PR #50989 has been reverted in #51009

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/51010
