### ISSUE TITLE
希望Typography在copyable的基础上拓展双击复制的能力

### ISSUE THREAD

**Issue by ByYogi** [ant-design/ant-design#50982]
### What problem does this feature solve?

我认为默认的复制`icon`在内容少的情况不好看，我想使用灰色`icon`第一时间也无从下手
自己处理样式太麻烦。但是又有便捷复制的需求。

如果是**双击复制**的话比较优雅
![image](https://github.com/user-attachments/assets/d55a051f-96c1-415d-88b3-48e27f260b32)

### What does the proposed API look like?

```js
<Paragraph
      copyable={{
         doubleCopy: true
      }}
    >
  Custom Context
</Paragraph>
```

**Comment by MadCcc** [comment]
可以自行实现一下，antd 也是封装的三方包逻辑
