### ISSUE TITLE
全屏状态下点击尝试上传文件，此刻会默认退出全屏(浏览器默认行为)，但是退出后上传不能正常使用，二次上传才能恢复正常

### ISSUE THREAD

**Issue by fzh199410** [ant-design/ant-design#50996]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-lbg1i5?file=src%2FApp.tsx)

### Steps to reproduce

1. 点击【进入全屏】
2.点击【上传】-> 点击【Click-to-Upload】
3.第一次上传附件无响应
4.第二次上传正常

### What is expected?

期望上传正常

### What is actually happening?

第一次上传附件无响应

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | react@17.0.55 |
| System | macOS |
| Browser | chrome 版本 128.0.6613.139（正式版本） (arm64) |

**Comment by afc163** [comment]
请检查 `<input type="file" />` 是否有一样的问题，如果是，则可能是浏览器原生问题，与 antd 无关。

**Comment by fzh199410** [comment]
> 请检查 `<input type="file" />` 是否有一样的问题，如果是，则可能是浏览器原生问题，与 antd 无关。

Reproduction link 中添加了file类型的input，确实是有一样的问题。问题应该是出自ConfigProvider中的配置，屏蔽掉getPopupContainer就正常上传， 您可以试试。

**Comment by afc163** [comment]
先看看这些链接：https://github.com/ant-design/ant-design/issues/26942#issuecomment-700494936

**Comment by fzh199410** [comment]
> 先看看这些链接：[#26942 (comment)](https://github.com/ant-design/ant-design/issues/26942#issuecomment-700494936)

这些链接里面相关的基本是api使用层面的问题，和我提供的Reproduction中file不生效没有关系吧？我在链接中采取控制变量的方式重新写了3个场景，麻烦您确认下 “ConfigProvider使用动态getPopupContainer 是否会影响上传正常”

**Comment by MadCcc** [comment]
打不开复现，这里看是白屏的

**Comment by MadCcc** [comment]
看起来不使用动态的 getPopupContainer 就可以，因为弹出文件选择的时候 input 会重新渲染，导致选择文件后不是同一个 input 了
