### ISSUE TITLE
menu点击其中一个选项后会触发父级Dropdown面板的关闭

### ISSUE THREAD

**Issue by taptaq** [ant-design/ant-design#50992]
### Reproduction link

[https://ant-design.antgroup.com/index-cn](https://ant-design.antgroup.com/index-cn)

### Steps to reproduce

目前是在Dropdown组件里面渲染一个Menu的组件，当点击Menu的其中一项时，DropDown面板会自动关闭；
尝试在点击Menu中的一项时进行e.stopPropagation和e.preventDefault也无法让DropDown面板不关闭。

### What is expected?

DropDown面板不关闭

### What is actually happening?

DropDown面板关闭

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 17.0.2 |
| System | macOS Big Sur 11.2 |
| Browser | chrome 128.0.6613.138（正式版本） (arm64) |

**Comment by taptaq** [comment]
<img width="507" alt="截屏2024-09-24 下午5 22 58" src="https://github.com/user-attachments/assets/c8480684-33b9-49ad-a85f-5c330c0bb29c">
但我之前也尝试过，还是不太行

**Comment by taptaq** [comment]
> 这个 bot 说的应该是对的

<img width="507" alt="截屏2024-09-24 下午5 22 58" src="https://github.com/user-attachments/assets/9c902b70-2ce2-46e3-bd0a-ab25393dd1f4">

但我之前也尝试过，还是不太行

**Comment by taptaq** [comment]
补充：4.x版本不会出现这种情况，5.x版本会出现

**Comment by taptaq** [comment]
> 能否把你的代码片段用 https://stackblitz.com/edit/antd-reproduce-5x 贴一下呢, 方便维护者审查具体效果。

好，下面是demo链接
https://stackblitz.com/edit/antd-reproduce-5x-6sbjxz?file=demo.tsx,index.css

**Comment by afc163** [comment]
看下 https://ant.design/components/dropdown-cn#dropdown-demo-overlay-open

info.source 为 menu 时，不去触发受控即可。

```jsx
      onOpenChange={(visible, info) => {
        if (info.source === 'trigger') {
          setDropDownVisible(visible);
        }
      }}
```

**Comment by taptaq** [comment]
可以了，十分感谢

**Comment by taptaq** [comment]
> 看下 https://ant.design/components/dropdown-cn#dropdown-demo-overlay-open
> 
> info.source 为 menu 时，不去触发受控即可。
> 
> ```js
>       onOpenChange={(visible, info) => {
>         if (info.source === 'trigger') {
>           setDropDownVisible(visible);
>         }
>       }}
> ```
> 
> See https://stackblitz.com/edit/antd-reproduce-5x-8sceas?file=demo.tsx,index.css

可以了，十分感谢
