### ISSUE TITLE
BUG? when the Steps' last title was chinese，the step component would be dither frequency 

### ISSUE THREAD

**Issue by garview** [ant-design/ant-design#5099]
- antd version:2.7.3
- OS and its version:win8.1 专业版
- Browser and its version:chrome56

#### What did you do? Please provide steps to re-produce your problem.

steps里最后的step的title为中文，step便会高频抖动。

#### What happen?

![111](https://cloud.githubusercontent.com/assets/18555554/23396630/acea2d6c-fdcf-11e6-8d2b-2a531611e0d0.gif)

#### Re-producible online demo

没有在线例子。我尝试使用codepen复现，但无法重现。也许是环境冲突导致的，不断地对本机配置进行简化，问题依然存在。本机上则可以轻易地复现出来。
附上简化的工程，npm start 后就能看到现象：

[demo.zip](https://github.com/ant-design/ant-design/files/806065/demo.zip)

#### 工程中的部分代码：
```javascript
import React from 'react'
import { Steps, Button, message } from 'antd';
const Step = Steps.Step;


const statuses = [{
    alias: "First",
}, {
    alias: "Second",
}, {
    alias: "中文",
}];

class StatusShow extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                <Steps current={0}>
                    {statuses.map(item => <Step key={item.alias} title={item.alias}/>)}
                </Steps>

            </div>
        )
    }
}

export default StatusShow;
```

**Comment by afc163** [comment]
I fixed a similar issue: https://github.com/react-component/steps/issues/22

Seems that it not be resolved it yet.

**Comment by garview** [comment]
i think they are the same problem. 
i have installed the latest antd/react/babel-plugin-import, but nothing changed.

**Comment by afc163** [comment]
I try to fix it in https://github.com/react-component/steps/commit/635745021aaa043c8bdce8b3c8649b0d21497d0d

But since I can't reproduce it in my machine, you can try new version of antd at end of this week, then we check this again.

**Comment by garview** [comment]
It seems the cache problem though I have clear the cache many times throuh "ctrl+shift+del" .
After uninstall the chrome including clear the browser data at all and install chrome again, the Steps component working fine.
