### ISSUE TITLE
Button组件设置data-xx属性在onClick事件中通过event.target.dataset获取不到

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#5100]
## 前提
现有一表格，colums的定义中有一列是 Button。其render 定义如下所示
```js
 <Button onClick={this.props.closeShelfRow.bind(this, record.id)}>取消</Button>
```
为了减少重绘次数，避免使用bind
因此改写render

```js
 onClick(e) {
            this.props.closeShelfRow(e.target.dataset.id);
 }

 <Button data-id={record.id} onClick={this.onClick}>取消</Button>
```
根据官方文档描述
> `<Button>Hello world!</Button>` 最终会被渲染为` <button>Hello world!</button>`，并且除了上表中的属性，其它属性都会直接传到 `<button></button>`

## 结果
点击按钮的时候，没有成功。
因为最终生成的button 如下所示
```js
<button type="button" data-id="1" class="ant-btn ant-btn-primary">
            <span>确 定</span>
  </button>
```
导致onClick事件的e.target 是`<span>确 定</span>`，其上没有`data-id="1"`属性

## 期望
有什么解决方法

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
Actually, I don't recommend to store data on DOM.

**Comment by afc163** [comment]
You can look up Bonus: Passing Arguments Without Bind` section of [this article]( https://daveceddia.com/avoid-bind-when-passing-props/)`. We strongly don't recommend the `data-*` way.

**Comment by yunxifd** [comment]
thanks 

I finally Solve the problem by wrap the button to implement  my own logic

**Comment by yunxifd** [comment]
find that we can use `event.currentTarget` to get the target witch the event attach to
