### ISSUE TITLE
Method validateFields with validateOnly does not work with "fields" and "onFieldsChange"

### ISSUE THREAD

**Issue by vmalay** [ant-design/ant-design#51007]
### Reproduction link

Simple Button validation (with Button) with "fields" :  [![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-pnx82a-up7seb?file=demo.tsx)

Global validation with "fields" : [![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-pnx82a-xups1w?file=demo.tsx)

### Steps to reproduce

- Have a working Form
- Form should be using fields and onFieldsChange
- Have a Button or something else that trigger `form.validateFields({ validateOnly: true })`

### What is expected?

We expect the form to be validated **without** the error messages displayed because we are using "validateOnly: true".

### What is actually happening?

The error messages are displayed.

When calling `form.validateFields({ validateOnly: true });` with "validateOnly: true", the error messages should not be displayed even when using fields/onFieldsChange. When calling "validateFields", it's directly calling onFieldsChange twice, and then the error messages are displayed. Maybe a solution would be : 
- Either to not call the onFieldsChange when validateFields with "validateOnly: true" is called.
- Or the onFieldsChange should not display the error messages when triggered from source "validateOnly: true".

I'm trying to do that because I want to combine "global validation" with fields. I'm not able to combine: 
- the use of "fields" (antd demo here : https://ant.design/components/form#form-demo-global-state)
- and global validation (antd demo here : https://ant.design/components/form#form-demo-validate-only).

I combined the two here in this sandbox, issue is that it's not validating only, error messages are displayed on all fields when we start typing :

 [![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-pnx82a-xups1w?file=demo.tsx)

Maybe I'm missing something, or if you have any workaround for this issue I'll gladly look into it.

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | react |
| System | Windows |
| Browser | Chrome |

Greetings,

**Comment by zombieJ** [comment]
It's passed by your `setFields` not `validateOnly`:

https://stackblitz.com/edit/react-pnx82a-whgfzw?file=demo.tsx
