### ISSUE TITLE
Select multiple 时报错 Animate.js:296 Uncaught Error: must set key for <rc-animate> children

### ISSUE THREAD

**Issue by GitHub-Haisheng** [ant-design/ant-design#5101]
#### Environment(required)

- antd version:       0.12.17
- OS and its version:   macOS 10.12.1 
- Browser and its version:  chrome 版本 50.0.2661.102 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.

I want to set up a multiple select

#### What do you expected?

![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

#### What happen?

select is not render 
Error: Animate.js:296 Uncaught Error: must set key for <rc-animate> children

**Comment by GitHub-Haisheng** [comment]
Select 多选时报错

**Comment by afc163** [comment]
<img width="434" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23400287/773b2ae0-fdde-11e6-950f-e3f7dd016e63.png">

**Comment by GitHub-Haisheng** [comment]
@afc163   不好意思 我这时正在注册codepen  请见谅.

**Comment by afc163** [comment]
@GitHub-Haisheng 抱歉我戾气比较重，看到无法帮助解决的问题容易恼火。

**Comment by GitHub-Haisheng** [comment]
![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

**Comment by GitHub-Haisheng** [comment]
![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

**Comment by GitHub-Haisheng** [comment]
![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

**Comment by GitHub-Haisheng** [comment]
![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

**Comment by GitHub-Haisheng** [comment]
![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

**Comment by GitHub-Haisheng** [comment]
![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

**Comment by GitHub-Haisheng** [comment]
![Uploading 1285B8F9-66D6-498B-A91E-0B1FB04F5749.png…]()

**Comment by afc163** [comment]
网络不好的话，最好翻一下墙。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/search?utf8=%E2%9C%93&q=select+must+set+key+for+children&type=Issues

**Comment by afc163** [comment]
Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

**Comment by GitHub-Haisheng** [comment]
@afc163   好的谢谢 希望今后越用用熟练 能更加的方便你们协助 也方便我们提问  谢谢了 你们做的真不错   但是 新手刚来肯定会有摸不着头脑的地方   难为你们了 要面对这么多参差不齐的人群  真心的谢谢。

**Comment by afc163** [comment]
不是特别针对楼主，主要是下午突然多了很多问了和没问差不多的 issue，例如 #5087 #5097 #5082 。

**Comment by GitHub-Haisheng** [comment]
理解 我这时再看你给我推荐的那几个问题  还是有些不明白  明天要是还弄不懂  再请教一下你

**Comment by afc163** [comment]
我现在只能猜你是这个问题：https://github.com/ant-design/ant-design/issues/3734#issuecomment-261836598
