### ISSUE TITLE
Table Colums类型定义问题

### ISSUE THREAD

**Issue by consistent-k** [ant-design/ant-design#51019]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-fr38al?file=demo.tsx)

![image](https://github.com/user-attachments/assets/a3769e9a-f52c-4298-ad32-f7a5d1c0db81)

<img width="565" alt="image" src="https://github.com/user-attachments/assets/c6322710-2420-4e12-a162-da0220f81b85">

### Steps to reproduce

遍历已定义好的colums数据 在取值的时候如上图 item项里没有自动联想出dataIndex。虽然直接取值可以取到，类型却没有联想出来， 在本地的编辑器内则会有ts报错。

### What is expected?

期望有dataIndex

### What is actually happening?

实际没有

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.3.1 |
| System | Mac OS |
| Browser | Chrome  129.0.6668.58 |

**Comment by crazyair** [comment]
先判断下 object ？

**Comment by MadCcc** [comment]
ColumnsType 有两种，这里自动 infer 到了没有 dataIndex 的 ColumnGroupType。可以尝试下直接指定为 ColumnType

**Comment by crazyair** [comment]
> ColumnsType 有两种，这里自动 infer 到了没有 dataIndex 的 ColumnGroupType。可以尝试下直接指定为 ColumnType

强制指定不太好

**Comment by consistent-k** [comment]
> ColumnType
这个类型下也没有dataIndex
![image](https://github.com/user-attachments/assets/b83b5272-886e-4a91-b125-56fdf840efef)
