### ISSUE TITLE
Table 设置scroll后  在Flex 布局下 无限变宽

### ISSUE THREAD

**Issue by Veveue** [ant-design/ant-design#51013]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-2dk3xb?file=demo.tsx)

### Steps to reproduce

浏览器缩放 或者 注释 启用 scroll 属性

### What is expected?

正常

### What is actually happening?

无限变宽

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 18 |
| System | ubantu |
| Browser | 128 |

**Comment by Veveue** [comment]
@petercat-assistant

**Comment by mjw-git** [comment]
flex:1,width:0
