### ISSUE TITLE
Input、select组件默认的 placeholder 为什么要设计为 value 为 undefined 才能显示，不能空字符串('')也显示 placeholder 吗

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design#51028]
### What problem does this feature solve?

后端如果返回了的字段为空字符串，我们还需要 fieldValue || undefined 才能显示placeholder，写多了也显得很烦琐

### What does the proposed API look like?

希望 Input、select组件也能支持空字符串也展示 placeholder

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/2367

**Comment by rookie-luochao** [comment]
> Duplicate of #2367

偏右大佬，看完了 2367 的讨论，意思就是目前必须要前端自己兼容各种空值吗？

**Comment by zombieJ** [comment]
> 偏右大佬，看完了 2367 的讨论，意思就是目前必须要前端自己兼容各种空值吗？

是的。空值带有业务属性，这个调整过很多次。最终收束为：

[FAQ: undefined 和 null 在 antd 的受控组件中有区别吗？](https://ant-design.antgroup.com/docs/react/faq-cn#undefined-%E5%92%8C-null-%E5%9C%A8-antd-%E7%9A%84%E5%8F%97%E6%8E%A7%E7%BB%84%E4%BB%B6%E4%B8%AD%E6%9C%89%E5%8C%BA%E5%88%AB%E5%90%97)
