### ISSUE TITLE
Drawer、Modal、Tab多标题、Pop等弹层层级遮挡问题

### ISSUE THREAD

**Issue by imeime** [ant-design/ant-design#51029]
### What problem does this feature solve?

解决业务系统使用多层级Z-index1000,1050等组件在界面显示问题，不阻断业务操作

### What does the proposed API look like?

多弹层组件的层级不应由业务处理（系统的嵌套层级不固定），太不灵活了，后来者自动z-index  ，期望API的z-index可以根据组件自适应

**Comment by zombieJ** [comment]
zIndex 是自动叠加的，来个重现看看是不是遇到了 bug。

**Comment by zhouzhouya1** [comment]
我也遇到同样问题。页面使用了两次modal基础上，之后再用一个二次封装确认弹窗的modal， 这个确认弹窗应该在最上面的，结果被遮挡住了

> Hello @imeime. Please provide a online reproduction by forking [this one](https://u.ant.design/repro) or provide a minimal GitHub repository like [create-react-app-antd](https://github.com/ant-design/create-react-app-antd). Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @imeime，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过 fork 这个[在线重现案例](https://u.ant.design/repro) ，或者提供一个最小化的 GitHub 仓库（类似 [create-react-app-antd](https://github.com/ant-design/create-react-app-antd)）。3 天内未跟进此 issue 将会被自动关闭。
> 
> > [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)
> 
> ![](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/69e47d742e57b34c17c3040a8b06a75a98ac4db9541c8b95db304bdfb280326d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
