### ISSUE TITLE
Tabs 切换后按下 shift 会有个粗的边框

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51026]
### Reproduction link

[https://ant.design/components/tabs-cn](https://ant.design/components/tabs-cn)

### Steps to reproduce

切换 tabs，然后按下 shift

https://github.com/user-attachments/assets/26499006-266a-4ef1-9c02-6a825939c05f

### What is expected?

没有边框

### What is actually happening?

有边框

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by li-jia-nan** [comment]
这不是可访问的那个 tabIndex 属性吗

**Comment by afc163** [comment]
这是可访问性需要的 focus 样式，不建议去掉。

**Comment by coding-ice** [comment]
这个是浏览器的默认样式, 类似这样可以解决
```css
*:focus {
  outline: none !important;
}
```

**Comment by zombieJ** [comment]
v5 a11y 支持，特意加的……
