### ISSUE TITLE
Error from customized component which is built on AutoComplete

### ISSUE THREAD

**Issue by fariyAhill** [ant-design/ant-design#5102]
#### Environment(required)

- antd version:2.7.3
- OS and its version:macOS  10.12.3
- Browser and its version: chrome 56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

按照官网的"自定义输入组件"示例引用AutoComplete生成一个自定义组件A，然后在其他模块组件B中引用该自定义组件A

#### What do you expected?

期望组件能正常显示

#### What happen?

发生错误，报“ no key or value for [object Object]”

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
close for no response.
