### ISSUE TITLE
DatePicker 选择0分0秒 时间转时间戳时间 有误

### ISSUE THREAD

**Issue by ouy-o3o** [ant-design/ant-design#51027]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/p9n4jk?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm1irubus00063b6jzc6tyj14%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm1irubus00023b6jeluh06zr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm1irubus00033b6jkxk1hlzc%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm1irubus00053b6jhsyf2w0f%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm1irubus00023b6jeluh06zr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1irubus00013b6jmkq1axbp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522cm1irubus00023b6jeluh06zr%2522%252C%2522activeTabId%2522%253A%2522cm1irubus00013b6jmkq1axbp%2522%257D%252C%2522cm1irubus00053b6jhsyf2w0f%2522%253A%257B%2522id%2522%253A%2522cm1irubus00053b6jhsyf2w0f%2522%252C%2522activeTabId%2522%253A%2522cm1irutjf001y3b6jimpth3b5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm1irubus00043b6jjvt88eb5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm1irutjf001y3b6jimpth3b5%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm1irubus00033b6jkxk1hlzc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm1irubus00033b6jkxk1hlzc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

选择时间为2024-09-26 00:00:01 和2024-09-26 00:00:00 转时间戳的结果分别是 1727280000381 1727280001381 末尾多了381的时间戳

### What is expected?

期望数字转换成1727280000000

### What is actually happening?

1727280000381

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.0 |
| System | mac |
| Browser | 128.0.6613.138 |

**Comment by ouy-o3o** [comment]
> 你的毫秒没处理...

能具体点吗，没太理解这个处理毫秒的操作

**Comment by ouy-o3o** [comment]
> > > 你的毫秒没处理...
> > 
> > 
> > 能具体点吗，没太理解这个处理毫秒的操作
> 
> <img alt="image" width="610" src="https://private-user-images.githubusercontent.com/32004925/371000319-a47efcdd-b219-4970-9db7-579538841c1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzAwNDAsIm5iZiI6MTcyNzMyOTc0MCwicGF0aCI6Ii8zMjAwNDkyNS8zNzEwMDAzMTktYTQ3ZWZjZGQtYjIxOS00OTcwLTlkYjctNTc5NTM4ODQxYzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1NDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YjFjZjgxMDYzYTJlNmUzNTliNTViYmVkYzViM2Y3OWVkYzJhZWUxN2RmZTU2NmI0ODAwYmY1NGE5ZDQ2NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qTa_D0sLRxy46NO5sikaGvYWkfog0Nc6wDcUWNewwmc">
 我使用组件参数返回值转毫秒会有多余的毫秒数
<img width="542" alt="image" src="https://github.com/user-attachments/assets/5fd851c9-b9fc-4c27-99f8-fa0d06b94f1d">
如果是moment直接调用是正常的
![Uploading image.png…]()

**Comment by ouy-o3o** [comment]
<img width="447" alt="image" src="https://github.com/user-attachments/assets/b10f1eaa-e04f-4de5-b2ce-2a66dfc195f6">

**Comment by afc163** [comment]
组件默认值是 `Date.now()` 建议 `value.startOf('second')` 处理一下。

https://codesandbox.io/p/sandbox/ri-qi-shi-jian-xuan-ze-antd-4-24-12-forked-2gcrkm?file=%2Fdemo.tsx%3A13%2C7
