### ISSUE TITLE
New Splitter component - Bug - Cannot hide the panel

### ISSUE THREAD

**Issue by jsdk1701** [ant-design/ant-design#51022]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-4whfd4?file=demo.tsx)

### Steps to reproduce

Just go to the https://ant.design/components/splitter component and open up any stackblitz. Try the Collapsible one. 

On your website you can collapse all the way down to zero height and hide the whole splitter panel. But when you go to stackblitz for some reason the minimum is limited to the size of the divs inside of the panel. So you cannot hide the whole panel. Which should be allowed.

### What is expected?

The ability to hide the panel completely.

### What is actually happening?

It stops at its own minimum which is the height of the data inside of it.

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.3.1 |
| System | Mac OS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Seems overflowY style missing in where prefix mode

**Comment by Zhuohui-Li** [comment]
Same here

**Comment by wanpan11** [comment]
> Seems overflowY style missing in where prefix mode

It seems that the panel style is lost. The same situation occurs in `hashPriority="high"` mode.
