### ISSUE TITLE
a-tree 树结构组织架构同一叶子节点下布局凌乱

### ISSUE THREAD

**Issue by 123LCQ** [ant-design/ant-design#51031]
a-tree 树结构组织架构在同一叶子节点下的缩进各不一样，导致页面布局凌乱，发现是设置了:field-names="fieldNames"就会乱，const fieldNames = {   children: 'children',   title: 'orgName',   key: 'orgId' }

**Comment by li-jia-nan** [comment]
a-tree 是 antd-vue 吗？那你应该去这里提 issue：

- https://github.com/vueComponent/ant-design-vue

**Comment by 123LCQ** [comment]
<img width="806" alt="企业微信截图_374e479b-2dfa-476e-9f9b-ad362c8067b8" src="https://github.com/user-attachments/assets/18690825-df79-471f-ba5f-3d5b8ad4cd68">
<img width="796" alt="企业微信截图_2520cd83-97f6-402c-91bf-5b3714966f1c" src="https://github.com/user-attachments/assets/4f48d572-de84-48f5-ad74-5e9ea14937b7">

**Comment by li-jia-nan** [comment]
> a-tree 是 antd-vue 吗？那你应该去这里提 issue：
> 
> * https://github.com/vueComponent/ant-design-vue

这是两个库，不是同一个团队在维护
