### ISSUE TITLE
Table 嵌套子表格，当子表格与父表格共用一个表头时，数据展示问题

### ISSUE THREAD

**Issue by yaangel7** [ant-design/ant-design#51038]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

可以在上面的链接里去复现，帮忙看看，有点急
```
const { createRoot } = ReactDOM;

const {  DownOutlined  } = icons;
const {  Badge, Dropdown, Space, Table  } = antd;

const dataSource = Array.from({
  length: 3,
}).map((_, i) => ({
  key: i.toString(),
  name: 'Screen',
  platform: 'iOS',
  version: '10.3.4.5654',
  upgradeNum: 500,
  creator: 'Jack',
  createdAt: '2014-12-24 23:12:00',
  children: [{
      name: 'Screen',
      platform: 'iOS',
      version: '10.3.4.5654',
      upgradeNum: 500,
      creator: 'Jack',
      createdAt: '2014-12-24 23:12:00',
    }]
}));
const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Platform',
    dataIndex: 'platform',
    key: 'platform',
  },
  {
    title: 'Version',
    dataIndex: 'version',
    key: 'version',
  },
  {
    title: 'Upgraded',
    dataIndex: 'upgradeNum',
    key: 'upgradeNum',
  },
  {
    title: 'Creator',
    dataIndex: 'creator',
    key: 'creator',
  },
  {
    title: 'Date',
    dataIndex: 'createdAt',
    key: 'createdAt',
  },
  {
    title: 'Action',
    key: 'operation',
    render: () => <a>Publish</a>,
  },
];
const expandedRowRender = (children) => (
  <Table columns={columns} dataSource={children} size="small" bordered/>
);
const App = () => (
  <>
    <Table
      columns={columns}
      expandable={{
        expandedRowRender: (record) =>expandedRowRender(record?.children || []),
        rowExpandable: (record) => record?.children?.length
      }}
      dataSource={dataSource}
      bordered
      size="small"
    />
  </>
);
const ComponentDemo = App;


createRoot(mountNode).render(<ComponentDemo />);
```

### What is expected?

antd 表格嵌套表格，共用表头，仅子表格展示就好，不要让父也展示一次

### What is actually happening?

antd 表格嵌套表格，共用表头，展开的数据重复展示，子表格和父表格均展示了

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | react18 |
| System | Mac |
| Browser | Chrome |

**Comment by yaangel7** [comment]
<img width="1474" alt="Jietu20240926-173815@2x" src="https://github.com/user-attachments/assets/3667ab31-2db6-43c9-bd82-3e01fd6bd787">
红色是多余的

**Comment by DrMuda** [comment]
你的复现链接没东西， 点一下右上角的 save 按钮

**Comment by yaangel7** [comment]
> 你的复现链接没东西， 点一下右上角的 save 按钮

我贴了代码，大佬

**Comment by DrMuda** [comment]
> > 你的复现链接没东西， 点一下右上角的 save 按钮
> 
> 我贴了代码，大佬

你那个链接是保存前的， 发个新的出来

**Comment by DrMuda** [comment]
准确来说不是父table的数据重复显示， 而是子table的数据重复了，dataSource[0].children ， 改一下这个children字段名就行了， Table组件自动用children字段的数据生成嵌套表了， 而你又实用 expandedRowRender 重新渲染了一个出来， 子Table就重复了

**Comment by DrMuda** [comment]
> 准确来说不是父table的数据重复显示， 而是子table的数据重复了，dataSource[0].children ， 改一下这个children字段名就行了， Table组件自动用children字段的数据生成嵌套表了， 而你又实用 expandedRowRender 重新渲染了一个出来， 子Table就重复了

随便改成 childrenData、children1、这些就行， 或者既然表头都是一样的就直接不写 expandedRowRender 就好了

**Comment by yaangel7** [comment]
> > 准确来说不是父table的数据重复显示， 而是子table的数据重复了，dataSource[0].children ， 改一下这个children字段名就行了， Table组件自动用children字段的数据生成嵌套表了， 而你又实用 expandedRowRender 重新渲染了一个出来， 子Table就重复了
> 
> 随便改成 childrenData、children1、这些就行， 或者既然表头都是一样的就直接不写 expandedRowRender 就好了

谢谢大佬，是这个问题，太感谢啦
