### ISSUE TITLE
Notification component stacking issues  

### ISSUE THREAD

**Issue by hyjhbzzal** [ant-design/ant-design#51033]
### Reproduction link

[https://ant.design/components/notification-cn](https://ant.design/components/notification-cn)

### Steps to reproduce

Click the open notification button a few times, and notice that the first notification is overwritten by the second, while the third notification appears below as normal

### What is expected?

When the maximum value is not reached, it is displayed in order
 
<img width="414" alt="image" src="https://github.com/user-attachments/assets/46fd00e5-3fe3-4f8c-ac9c-1866a5267c1d">

### What is actually happening?

The first card is covered by the second card

<img width="421" alt="image" src="https://github.com/user-attachments/assets/c5472f1c-9f65-4af4-b050-d8301e1f86ae">
 

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | >18.0 |
| System | mac |
| Browser | Google Chrome 128.0.6613.138 |

---
When the overlap occurs, move the mouse over the notification card to trigger a re-render and it works again

**Comment by hyjhbzzal** [comment]
> ## 你用的哪个示例打开通知的，感觉这个 demo 很难区分出顺序。 稍微调整了一下。
> Which example are you using to open notifications? It feels hard to distinguish the order in this demo. I've made some adjustments.
> 
>  Kapture.2024-09-26.at.18.52.04.mp4

随便一个示例都能够复现，就像视频中所展示的，点击通知按钮三次，第一个通知正常出现，第二个通知会覆盖在第一个通知上（主要是这个问题），第三个通知才正常排列在下方，这个时候还没有达到通知收起的限制条数，应该三条全部平摊展开的，我自己看了下源码发现是这里红框中标记的地方第二个通知弹出时会计算出NaN值，
<img width="785" alt="image" src="https://github.com/user-attachments/assets/2e4aa054-815b-4c56-b55c-b9b76a3d5e66">

**Comment by MadCcc** [comment]
> 并且我还发现一个问题，右上角打开通知，新增加的弹窗应该在前面的通知之后，（4.x）是正常的。

stack 开启了就是这个顺序，因为收起时会把其他的都收到最上面一条 notification 的下方。关闭 stack 就是以前的顺序。

**Comment by MadCcc** [comment]
Fixed in rc-notification@5.6.2
