### ISSUE TITLE
radio.button 组件在不同的分辨率下 中间的分割线粗细不一样

### ISSUE THREAD

**Issue by lbrjms** [ant-design/ant-design#51045]
### Reproduction link

[https://ant-design.antgroup.com/components/radio-cn](https://ant-design.antgroup.com/components/radio-cn)

### Steps to reproduce

你们自己的示例项目就有这个bug
在缩放浏览器的情况下 Radio.Group组件button模式下， 中间分割线会出现一边粗 一边细的情况

### What is expected?

radio切换的时候 中间的分割线一样粗细

### What is actually happening?

中间分割线会出现一边粗 一边细的情况

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.2.0 |
| System | mac、window |
| Browser | chrome |

**Comment by lbrjms** [comment]
组件测也做不了什么事情是什么意思；只要在网页中缩放 必现这个bug; 
有时候不管怎么点击 中间分割线都是细的  
有时候不管怎么点击 中间分割线都是粗的  
有时候点击左边是细的 点击右边是粗的  （主要是这种情况 很难受）

**Comment by zombieJ** [comment]
感谢反馈。缩放后会丢失精度，这由浏览器与系统决定如何渲染（其中 windows 的精度问题更甚）。组件侧无法感知。

**Comment by zombieJ** [comment]
另外粗细这个东西，和屏幕分辨率也有很大关系。如果用 4K 会好很多，但是这种就是无法空的外部因素了。

**Comment by lbrjms** [comment]
各位有什么解决办法没

**Comment by lbrjms** [comment]
这bug怎么就直接关了 大神们都怎么解决的
