### ISSUE TITLE
DatePicker showTime  在 Modal 时，无法滚动，选不了时间

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#51049]
### Reproduction link

https://stackblitz.com/edit/react-qhfn8x?file=demo.tsx

### Steps to reproduce

打开 DatePicker

### What is expected?

可以选到时间

### What is actually happening?

选不了

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | latest |
| System | mac |
| Browser | chrome |

现在要单独设置 getPopupContainer 才可以，比较麻烦

**Comment by afc163** [comment]
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/39077b13-5529-45aa-a003-eba1ecb158c0">

这个和 Modal 有关系么？感觉是页面宽度问题？

<img width="445" alt="image" src="https://github.com/user-attachments/assets/7a22da1b-18f5-43fb-b4c0-065a48067dfd">
