### ISSUE TITLE
splitter 在触屏设备上无法拖拽

### ISSUE THREAD

**Issue by mainhanu** [ant-design/ant-design#51046]
### Reproduction link

[https://ant.design/~demos/splitter-demo-size](https://ant.design/~demos/splitter-demo-size)

### Steps to reproduce

在触屏设备上拖拽 splitter bar 异常

### What is expected?

像 pc 设备鼠标操作一样效果

### What is actually happening?

无法拖拽

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.x |
| System | macOS |
| Browser | all |

**Comment by sakuraee** [comment]
是由于这里没加对touch的监听么,我修改了一版让功能可用了  https://github.com/ant-design/ant-design/blob/d0bcb188ee74b942e1fdf8fbd9fa33d777398559/components/splitter/SplitBar.tsx#L92-L98
