### ISSUE TITLE
RangePicker disabledDate没有type="start"|"end"

### ISSUE THREAD

**Issue by cangSDARM** [ant-design/ant-design#51047]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn](https://ant-design.antgroup.com/components/date-picker-cn)

### Steps to reproduce

https://github.com/ant-design/ant-design/issues/33237
https://github.com/ant-design/ant-design/issues/3446

### What is expected?

disabledTime 有 type = "start" | "end" 信息，但是我不理解为啥 disabledDate 里没有？

### What is actually happening?

只有from和type="date"

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.2 |
| System | win10 |
| Browser | 103 |

---
相关issue里有人提到过，但是对应issue不是强相关，且被关闭了

**Comment by zombieJ** [comment]
在 RangePicker 里，用户点击 end field 选择日期，会转到 start field。这个时候用户仍然可以选择比 end field 更后面的日期。所以这个 start 和 end 是不可靠的。所以加了一个 `from`，当用户第一次展开 RangePicker 的时候，以行为初始而不是字段位置。

给个需要强相关的 start 和 end 的例子看看？

**Comment by afc163** [comment]
GPT 的回复：

在 Ant Design 的 `RangePicker` 组件中，`disabledDate` 方法并没有像 `disabledTime` 那样提供 `type = "start" | "end"` 参数，这与组件的设计和数据流控制有关。

### 背后的原因：
1. **`disabledDate` 设计的简单性：**  
   `disabledDate` 的主要目的是用来禁用特定的日期，不管是开始日期还是结束日期，开发者只需判断日期是否应该禁用，而不需要知道是对开始日期或结束日期的禁用，因此它保持了一个相对简单的接口。

2. **逻辑通用：**  
   一般来说，`disabledDate` 的逻辑对开始和结束日期是通用的。例如，你可能希望禁用今天之前的所有日期，这个规则对起始和结束日期都适用，无需区分。

3. **复杂的时间控制：**  
   `disabledTime` 则更复杂，时间的选择往往需要针对起始和结束分别控制。例如，你可能想要在选择了某个开始日期和时间后，限制结束日期的时间范围。这就需要知道 `type` 是 `"start"` 还是 `"end"` 来区分不同的禁用逻辑。

### 如何实现类似功能：
如果你确实需要区分 `start` 和 `end` 的 `disabledDate` 逻辑，可以通过 `RangePicker` 的 `onCalendarChange` 或 `onChange` 来获得已经选择的日期，然后根据选择的状态进行逻辑判断。例如，当用户选择了开始日期后，你可以通过状态变量来动态地控制结束日期的可选范围。

#### 简单示例：
```jsx
import { DatePicker } from 'antd';
import { useState } from 'react';

const { RangePicker } = DatePicker;

function MyRangePicker() {
  const [startValue, setStartValue] = useState(null);

  const disabledDate = (current) => {
    if (!startValue) {
      return false; // 无开始日期时，禁用逻辑为 false
    }
    return current && current < startValue; // 开始日期已选时，禁用开始日期之前的结束日期
  };

  const handleCalendarChange = (values) => {
    setStartValue(values ? values[0] : null); // 记录选择的开始日期
  };

  return (
    <RangePicker
      disabledDate={disabledDate}
      onCalendarChange={handleCalendarChange}
    />
  );
}

export default MyRangePicker;
```

在这个例子里，当用户选择了开始日期后，结束日期就会基于 `startValue` 动态禁用过去的日期。这种做法可以在不需要 `type` 参数的情况下实现类似效果。

**Comment by cangSDARM** [comment]
我要限制结束日期能设置的区间总是比开始时间晚。现在虽然会自动切换早晚时间，但是PR就是要这个功能。他说这样视觉和操作上比较合理，但你后面切过去用户会感觉很奇怪

**Comment by cangSDARM** [comment]
虽然GPT的回答里能解决问题，但是我觉得和disabledTime一样暴露一个这个type是否更为合理，api也更为统一

**Comment by zombieJ** [comment]
> 我要限制结束日期能设置的区间总是比开始时间晚。现在虽然会自动切换早晚时间，但是PR就是要这个功能。他说这样视觉和操作上比较合理，但你后面切过去用户会感觉很奇怪

这个在 v4 早期的时候是这个限制，用户普遍反应体验很糟糕。可以和设计再确认一下是否要这么做。
