### ISSUE TITLE
Input otp onchange not working when clearing inputs

### ISSUE THREAD

**Issue by siva-rama-pandiyan** [ant-design/ant-design#51042]
### Reproduction link

[https://codepen.io/Siva_developer/pen/rNXaEOe?editors=0011](https://codepen.io/Siva_developer/pen/rNXaEOe?editors=0011)

### Steps to reproduce

Enter inputs in otp input. After entering all input box on change will trigger. you can see it in console but after clearing the input on change will not trigger.

### What is expected?

While clearing otp it needs to trigger on change then only we can do validation based on its state value.

### What is actually happening?

Currently it is not triggering on change when clearing. It only trigger on change when user enter all input

| Environment | Info |
| --- | --- |
| antd | 5.17.0|
| React | 18.3.1 |
| Browser | 129.0.6668.70 |

**Comment by siva-rama-pandiyan** [comment]
Share me the link of already reported issue @petercat-assitant

**Comment by LeleDallas** [comment]
> ### Reproduction link
> https://codepen.io/Siva_developer/pen/rNXaEOe?editors=0011
> 
> ### Steps to reproduce
> Enter inputs in otp input. After entering all input box on change will trigger. you can see it in console but after clearing the input on change will not trigger.
> 
> ### What is expected?
> While clearing otp it needs to trigger on change then only we can do validation based on its state value.
> 
> ### What is actually happening?
> Currently it is not triggering on change when clearing. It only trigger on change when user enter all input
> 
> Environment	Info
> antd	5.17.0
> React	18.3.1
> Browser	129.0.6668.70

Same issue here

**Comment by MadCcc** [comment]
Providing `onInput` would be nice.

**Comment by aojunhao123** [comment]
I would love to do this feature

**Comment by aojunhao123** [comment]
> Providing `onInput` would be nice.提供 `onInput` 会很不错。

Regarding this feature, I have an additional question. Currently, the **onChange** event is triggered only when all the input fields are filled. From a functional standpoint, it seems more appropriate to design it as **onComplete**. However, since the component has been released for some time, changing the API now might not be ideal. That said, would it be possible to offer **onComplete** as an alias for developers to use, as it would better align with the semantics?
