### ISSUE TITLE
Table 组件   react-dnd, 固定表头后滚动表格到一定位置后, 拖拽偏移不准确

### ISSUE THREAD

**Issue by MrZhouZh** [ant-design/ant-design#51044]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/funny-brattain-nhplmg)

### Steps to reproduce

![20240927183054_rec_](https://github.com/user-attachments/assets/770a74e5-2f70-4dae-ab37-ee13fb93b343)

### What is expected?

拖拽预览图不受table 内部滚动影响

![image](https://github.com/user-attachments/assets/4efebbf2-3786-4bb5-9846-048f39f84111)

### What is actually happening?

拖拽预览图偏移会随着滚动而偏移

![image](https://github.com/user-attachments/assets/25f773b7-4a5a-4384-9843-0a5c194e0deb)

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/p/sandbox/dazzling-panka-98s8kl?workspaceId=fb8d496a-cbdc-482b-9003-b38c3155f290

我改成原生 div 貌似也有一样的问题，所以这个是不是和 antd Table 无关，是一个 react-dnd 的使用问题？

**Comment by MrZhouZh** [comment]
> [codesandbox.io/p/sandbox/dazzling-panka-98s8kl?workspaceId=fb8d496a-cbdc-482b-9003-b38c3155f290](https://codesandbox.io/p/sandbox/dazzling-panka-98s8kl?workspaceId=fb8d496a-cbdc-482b-9003-b38c3155f290)
> 
> 我改成原生 div 貌似也有一样的问题，所以这个是不是和 antd Table 无关，是一个 react-dnd 的使用问题？

大佬, 是我没说明白, 抱歉...预期应该是预览图应该跟随在鼠标下方, 但是随着滚动条的移动, 预览图在光标的很下面的地方

**Comment by afc163** [comment]
确实，而且是 Chrome only 的 bug。

**Comment by l123wx** [comment]
https://codesandbox.io/p/sandbox/competent-nash-k7vmsz?workspaceId=c8004b36-5da6-4d72-b1a4-467faa714cc5

这个问题跟 ant-design 和 dnd 都没关系，直接用原生的 e.dataTransfer.setDragImage 也会有这个问题

当溢出元素（父元素 overflow: scroll/hidden） 使用了 position: relative 等定位属性时，拖动的时候就会出现这个问题

**Comment by afc163** [comment]
@l123wx 👍🏻，确实不是 antd 这侧能解决的问题。

**Comment by MrZhouZh** [comment]
😂 我找到这个 [DragPreview is positioned wrong when using translate3d on child nodes](https://github.com/react-dnd/react-dnd/issues/267#issuecomment-141111602)

1. 替换 React DnD backend
2. 自定义
