### ISSUE TITLE
Popover should render content when it is shown, not initially

### ISSUE THREAD

**Issue by pbrzosko** [ant-design/ant-design#51057]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-yiocut?file=demo.tsx)

### Steps to reproduce

Just run with developer tools.

### What is expected?

Breakpoint should not be hit on initial render. Only after text is hovered and popover is opened.

### What is actually happening?

Breakpoint is hit on initial render, meaning popup content is not lazy loaded.

| Environment | Info |
| --- | --- |
| antd | 5.19.4 |
| React | 18.3.1 |
| System | macOS Sonoma 14.5 |
| Browser | Google Chrome Version 126.0.6478.127 (Official Build) (arm64) |

---
It works properly in v4. See here: https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-ssylq6

**Comment by MadCcc** [comment]
React render all components in tree, but dom will not be created until popover is shown.

**Comment by zombieJ** [comment]
It's not related with antd but React work logic. `useMemo` in your code will always execute even you are not use Popover.

**Comment by pbrzosko** [comment]
Why it worked perfectly with ant4? Because of different React version? I think it started to fail for us when we migrated to ant5 so I am not totally convinced...

**Comment by ted341** [comment]
@pbrzosko - did you find a solution/workaround for this?

**Comment by pbrzosko** [comment]
No, we did some workaround for our popover content itself.
