### ISSUE TITLE
select 组件 activeBorderColor  在 variant="filled" 下，修改不生效

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/ant-design#51052]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-q5vgns?file=demo.tsx)

### Steps to reproduce

点击select 即可

### What is expected?

可以通过 activeBorderColor 这个token 修改 border 颜色
<img width="161" alt="image" src="https://github.com/user-attachments/assets/a6cb52d5-1391-4f12-af8f-f9e9d6f450a4">

### What is actually happening?

通过 activeBorderColor 这个token 修改 border 颜色 不生效
<img width="148" alt="image" src="https://github.com/user-attachments/assets/9734638b-76a6-49b6-b6d5-f0b86d213a40">

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.2.0 |
| System | macOS 14.6.1 |
| Browser | chrome 122.0.6261.57 |

**Comment by coding-ice** [comment]
这行代码导致的：https://github.com/ant-design/ant-design/blob/master/components/select/style/variants.ts#L149

**Comment by coding-ice** [comment]
另外设置颜色应该使用，`transparent`, `none` 是无效的哦～
