### ISSUE TITLE
Issue when overriding default table components

### ISSUE THREAD

**Issue by breakone** [ant-design/ant-design#51058]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x-5leahl?file=demo.tsx)

### Steps to reproduce

Insert Data into the inputs in the tables. 
The first table works as ecpected.

### What is expected?

Inserting data into the inputs should work

### What is actually happening?

After 1 keyboard hit, the component is rerendered and the focus is lost.

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | react 18.3.1 |
| System | MacOS |
| Browser | Arc |

**Comment by afc163** [comment]
You should move Row component out of App: https://stackblitz.com/edit/antd-reproduce-5x-f21hnb?file=demo.tsx

**Comment by breakone** [comment]
@afc163 
that ease...thanks a lot!
