### ISSUE TITLE
最新版的按钮的hidden属性无效, 根据官方解决方案导入reset.css之后会破坏ant-desgin基础样式, 比如基础对话框下面的取消和确认的间距会被抹除, 主按钮的白色文字变成黑色

### ISSUE THREAD

**Issue by 1057105012** [ant-design/ant-design#51063]
### Reproduction link

无

### Steps to reproduce

按钮的hidden无法开箱即用, 导入reset.css无法解决, 会破坏ant基础样式带来别的问题

### What is expected?

hidden正常工作, 开箱即用

### What is actually happening?

无法开箱即用, 给出的解决方案会破坏样式(测试发现, 对话框间距会被删除, 主按钮字体变成了黑色) 不符合预期

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | react |
| System | window |
| Browser | chrome |

---
希望开箱即用, 不要带来过多和业务和开发无关的心智负担

**Comment by wanpan11** [comment]
Button 好像没有 hidden 参数，提供下复现吧

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design/issues/47711

如果不想要其他样式，可以自行引入这段代码即可：https://github.com/ant-design/ant-design/blob/cce261263f8adf06d1967d66727b1838a01799ef/components/style/reset.css#L247-L249
