### ISSUE TITLE
Bring codesandbox back 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#51073]
<img width="335" alt="image" src="https://github.com/user-attachments/assets/a42bfcaa-b949-4cbc-b1f9-8c58d55f133f">

revert https://github.com/ant-design/ant-design/pull/49746
revert https://github.com/ant-design/ant-design/pull/49746
update https://github.com/ant-design/u.ant.design/pull/9

**Comment by crazyair** [comment]
懒得打字，复制粘贴。。。
