### ISSUE TITLE
findDOMNode is deprecated and will be removed in the next major release.

### ISSUE THREAD

**Issue by yuzh0816** [ant-design/ant-design#51077]
### Reproduction link

[https://github.com/yuzh0816/antd-test](https://github.com/yuzh0816/antd-test)

### Steps to reproduce

执行npm run dev后，打开控制台即可看到报错

### What is expected?

希望这处报错被解决。

### What is actually happening?

报错：
Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. 

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | 18.3.1 |
| System | Windows Server 2022 |
| Browser | 所有浏览器 |

**Comment by afc163** [comment]
如何重现？

<img width="1782" alt="image" src="https://github.com/user-attachments/assets/8931af0c-7091-4364-9a2f-0682bce07df2">

**Comment by yuzh0816** [comment]
> 如何重现？我这里没有看到警告信息。
> 
> <img alt="image" width="1782" src="https://private-user-images.githubusercontent.com/507615/371984799-8931af0c-7091-4364-9a2f-0682bce07df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODEzMzYsIm5iZiI6MTcyNzY4MTAzNiwicGF0aCI6Ii81MDc2MTUvMzcxOTg0Nzk5LTg5MzFhZjBjLTcwOTEtNDM2NC05YTJmLTA2ODJiY2UwN2RmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNzIzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGMxZDNjNmU2OWUzOTM1ZjY3YzVkOGY3NDBkNzZkNjE2NjBjZjY4MTMzMzIzZGVkNDQwZWQ4NGI2MTNkOTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ugAFqlJ1oIQyEZvv-XzIpnzdWV7S-Qg9kZ-5P3TO4pM">

问题刚刚排查出来，是react版本的问题，似乎为18.2.0时不会报错。

**Comment by yuzh0816** [comment]
> 如何重现？我这里没有看到警告信息。
> 
> <img alt="image" width="1782" src="https://private-user-images.githubusercontent.com/507615/371984799-8931af0c-7091-4364-9a2f-0682bce07df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODEzMzYsIm5iZiI6MTcyNzY4MTAzNiwicGF0aCI6Ii81MDc2MTUvMzcxOTg0Nzk5LTg5MzFhZjBjLTcwOTEtNDM2NC05YTJmLTA2ODJiY2UwN2RmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNzIzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGMxZDNjNmU2OWUzOTM1ZjY3YzVkOGY3NDBkNzZkNjE2NjBjZjY4MTMzMzIzZGVkNDQwZWQ4NGI2MTNkOTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ugAFqlJ1oIQyEZvv-XzIpnzdWV7S-Qg9kZ-5P3TO4pM">

版本一旦变为18.3.1后就会报错。

**Comment by yuzh0816** [comment]
> 如何重现？我这里没有看到警告信息。
> 
> <img alt="image" width="1782" src="https://private-user-images.githubusercontent.com/507615/371984799-8931af0c-7091-4364-9a2f-0682bce07df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODE5ODIsIm5iZiI6MTcyNzY4MTY4MiwicGF0aCI6Ii81MDc2MTUvMzcxOTg0Nzk5LTg5MzFhZjBjLTcwOTEtNDM2NC05YTJmLTA2ODJiY2UwN2RmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNzM0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjcxZWM4NjAzNjA1YWJkMmJmOWZlZWYyYTI1OWZkYzgxNjMwODZmM2I1MGYzZmJkMzgyM2NkYjFjYWU5OTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IewRF82dzlcqkX0KyqMyU5mTrwr26zb-Qt6WSt7KdDc">

麻烦您重新测试下刚刚的[仓库](https://github.com/yuzh0816/antd-test)，我更新了下package信息，将react版本切换至了18.3.1，问题即可复现。
