### ISSUE TITLE
Two validation messages shown for InputNumber Form.Item required validation

### ISSUE THREAD

**Issue by LiangZugeng** [ant-design/ant-design#51075]
### Reproduction link

[https://stackblitz.com/edit/antd-reproduce-5x-k8mtyb?file=demo.tsx](https://stackblitz.com/edit/antd-reproduce-5x-k8mtyb?file=demo.tsx)

### Steps to reproduce

1. Run the app in Stackblitz provided in the minimal reproduction link.
2. Enter any number in the "Text Input Number" text box.
3. Delete the number in the text box so the text box is empty.

### What is expected?

There should be only one validation message shown:
```
'inputNumber' is required
```

### What is actually happening?

There are two validation messages shown:
```
'inputNumber' is required
'inputNumber' is not a valid number
```

| Environment | Info |
| --- | --- |
| antd | 5.20.4 |
| React | react 18.3.1 |
| System | macOS 15.0 |
| Browser | Microsoft Edge 129.0.2792.52 (Official build) (arm64) |

**Comment by LiangZugeng** [comment]
@petercat-assistant when you say there is an issue already submitted for this problem, you referred to the exact issue I submitted.

I'll try your workaround but this should not be the permanent solution for this problem, the problem should be addressed in Ant Design library instead of forcing developers to add an extra validation logic to every usage for InputNumber Form.Item required validation.

**Comment by SINK-MASTER** [comment]
What about this?🙂
```tsx
    <Form layout={"inline"}>
      <Form.Item
        name={"number"}
        label={"number"}
        rules={[
          { required: true, message: "Please input" },
          {
            required: false,
            validator(rule, value, callback) {
              if (value > 5) {
                return Promise.reject(new Error("Upper limit reached"));
              }
              return Promise.resolve();
            },
          },
        ]}
      >
        <InputNumber />
      </Form.Item>
    </Form>
```

**Comment by LiangZugeng** [comment]
@SINK-MASTER Thanks, your suggestion worked!

From the API design perspective, I do think the required and min, max validation rule should work as expected instead of being forced to add a new validation rule, any chance that the Ant Design team will triage this as an issue and fix it?

I'm willing to submit a PR if I'm given necessary guidance on where to make the changes.

**Comment by afc163** [comment]
```diff
      <Form.Item
        label={'Test Input1 Number'}
        name={['inputNumber']}
        rules={[
          {
            type: 'number',
            required: true,
+           message: 'Number is not valid',
            min: 0,
            max: 50000,
          },
        ]}
      >
        <InputNumber />
      </Form.Item>
```

You can try `message` to combine validator feedback too.
