### ISSUE TITLE
TreeSelect的showSearch和loadData功能冲突

### ISSUE THREAD

**Issue by Sliect** [ant-design/ant-design#51080]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ssvwfy?file=demo.tsx)

### Steps to reproduce

1. 搜索 ex
2. 选中一个节点或者触发onBlur事件，会发起多个loadData事件
3. 再次打开TreeSelect, 子节点没有按预期添加到所有搜索到的节点上

### What is expected?

展开的节点都被添加正确的子节点
onBlur不应该触发loadData, 选中应该只触发一次loadData

### What is actually happening?

结果随机，部分子节点被添加了

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | win11 |
| Browser | chrome128 |

**Comment by Sliect** [comment]
根据官方例子添加了 showSearch

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/fc91464a9a95d8789ec64c3bb24372823650447c/components/cascader/demo/lazy.md?plain=1#L5

**Comment by Meowu** [comment]
https://github.com/ant-design/ant-design/issues/36873 这个问题还存在，搜索到的父节点没有展开图标，无法手动展开。
看了一下 `rc-tree` 的代码，搜索到的节点不能被展开，但是会被当成可以 load 的节点去触发 loadData 事件。
假设搜索到的是 leaf 节点，不会触发 loadData 事件。
