### ISSUE TITLE
Cascader 级联选择在多选模式下能否支持选择单个节点，且不会一并选择它的父节点和所有子节点

### ISSUE THREAD

**Issue by mediocrity-z** [ant-design/ant-design#51089]
### What problem does this feature solve?

多选时，例如用户只想选择一个直辖市的范围，而并非将它上面的所属省级单位和下面的各种区县单位一起选中

### What does the proposed API look like?

在级联选择的多选模式下选择单个节点，不会一并选择它的父节点和所有子节点

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/46538#issuecomment-1863773995

**Comment by mediocrity-z** [comment]
sorry市级范围不是直辖市

**Comment by afc163** [comment]
你是否需要的是：https://ant.design/components/cascader-cn#cascader-demo-change-on-select

**Comment by afc163** [comment]
在 Ant Design 的 `Cascader` 组件中，默认的多选行为会选择父节点和子节点，无法单独选择某个节点而不选中其父节点或子节点。如果你想在多选模式下，只选择单个节点（例如一个直辖市），而不会连带选择父级和子级节点，可以通过以下方法实现： **取消父子联动**：通过设置 `changeOnSelect` 和自定义 `onChange`，可以避免父子节点联动选择。

### 解决方案示例：

```tsx
import React, { useState } from 'react';
import { Cascader } from 'antd';

const options = [
  {
    value: 'china',
    label: 'China',
    children: [
      {
        value: 'beijing',
        label: 'Beijing',
        children: [
          { value: 'chaoyang', label: 'Chaoyang' },
          { value: 'haidian', label: 'Haidian' },
        ],
      },
      {
        value: 'shanghai',
        label: 'Shanghai',
        children: [
          { value: 'huangpu', label: 'Huangpu' },
          { value: 'pudong', label: 'Pudong' },
        ],
      },
    ],
  },
];

const CustomCascader = () => {
  const [selectedValues, setSelectedValues] = useState([]);

  const handleChange = (value) => {
    // 在这里自定义你的选择逻辑，比如仅允许选择单独节点而不影响父级或子级
    setSelectedValues(value);
  };

  return (
    <Cascader
      multiple
      options={options}
      value={selectedValues}
      onChange={handleChange}
      changeOnSelect
      showCheckedStrategy="SHOW_CHILD" // 仅展示子节点的选择，不显示父节点
    />
  );
};

export default CustomCascader;
```

### 关键点：
1. **`changeOnSelect`**：允许用户选择任意级别的节点，而不是必须选择完整路径。
2. **`showCheckedStrategy="SHOW_CHILD"`**：仅显示子节点选中状态，避免显示父节点的联动选择。
3. **`onChange`**：通过自定义 `onChange` 逻辑，可以控制选中行为，只允许选择单个节点，而不选中父节点或子节点。

这样你就可以在多选模式下自由选择单个节点，而不会一并选择父级和子级节点。

**Comment by SeeYuzuru** [comment]
“onChange：通过自定义 onChange 逻辑，可以控制选中行为，只允许选择单个节点，而不选中父节点或子节点。”
以上这种方法并不能实现“选中父标签，不批量选中子标签”的功能。
