### ISSUE TITLE
Input组件应当为清空按钮增加一个onClear事件来阻止冒泡

### ISSUE THREAD

**Issue by CaptainJon** [ant-design/ant-design#51081]
### What problem does this feature solve?

Input组件自带的清空按钮（设置allowClear后）事件并没有暴露出来，导致使用者没法阻止它导致的事件冒泡。清空输入框时，会触发其父元素的click事件，或者select事件等。

### What does the proposed API look like?

暴露一个onClear事件，表示用户点击了清空按钮，既可以通过逻辑判断来阻止清除，也可以通过暴露的事件对象来选择是否阻止其点击事件的冒泡行为。

**Comment by CaptainJon** [comment]
> 楼上机器人回答的几个链接还有点用，antd 5.20.0 已经提供了 `onClear` ，但是没有提供 event，所以你还是没办法阻止...
> 
> 感觉可以提一个 PR 改进一下。
> 
> 现阶段只能通过 `allowClear.clearIcon={}` 修改 清除图标，然后重写 click 事件。

希望4.x的版本也能出

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/16862#issuecomment-507616942 and https://github.com/ant-design/ant-design/pull/49905
