### ISSUE TITLE
Using the Table component causes the unit test run to fail

### ISSUE THREAD

**Issue by hoangthien910630** [ant-design/ant-design#51090]
### Reproduction link

[https://github.com/hoangthien910630/test-ui-kit-public.git](https://github.com/hoangthien910630/test-ui-kit-public.git)

### Steps to reproduce

1. yarn install
2. yarn run test

### What is expected?

Run unit test pass

### What is actually happening?

**Run unit test fail.**
Table run failed with error: **Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'addListener')]**

**_Can see more error files in the repository._**

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | React JS |
| System | Unit test |
| Browser | Unit test |

**Comment by afc163** [comment]
See https://github.com/akiran/react-slick/blob/bae881766024deeccab7d67ddf5d1a323f9355c8/test-setup.js

**Comment by hoangthien910630** [comment]
Console log result:
 
 ` console.log
    <body>
      <div>
        <div>
          No data
        </div>
      </div>
    </body>`
    
   Image error: 
![Run test Fail - Table](https://github.com/user-attachments/assets/d6d79390-3789-4cf2-8c3d-925a135cc1ef)

My code:
![Run test Fail - Table - code](https://github.com/user-attachments/assets/9b9e5e78-4fd3-4a0e-a30f-9204100a6a26)

**Comment by afc163** [comment]
https://github.com/hoangthien910630/test-ui-kit-public/pull/1

**Comment by hoangthien910630** [comment]
Many thanks. I tried again and it worked.
