### ISSUE TITLE
Splitter: invalid value for the "flexBasis" css style property

### ISSUE THREAD

**Issue by sberequek** [ant-design/ant-design#51106]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fpld9r)

### Steps to reproduce

When using the Splitter component inside a Tabs component and changing the size of the panels by dragging and finally changing the Tab the following error is generated:
"Warning: `NaN` is an invalid value for the `flexBasis` css style property."

### What is expected?

no warning

### What is actually happening?

The value for the css property "flexBasis" is NaN

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | react@18.3.1 |
| System | macOS 14.6.1 |
| Browser | Chrome Version 129.0.6668.90(x86_64) |

**Comment by li-jia-nan** [comment]
- #51096

**Comment by kiner-tang** [comment]
> * [There are unexpected gaps when the Splitter is in Flex #51095](https://github.com/ant-design/ant-design/issues/51095)
> * [fix(Splitter): fix the issue about Splitter had unexpected gaps in Flex #51096](https://github.com/ant-design/ant-design/pull/51096)

@li-jia-nan It doesn't seem to be the same problem. How can I fix it
