### ISSUE TITLE
"Warning: findDOMNode is deprecated and will be removed in the next major release" when using Dropdown

### ISSUE THREAD

**Issue by kaiyoma** [ant-design/ant-design#51107]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/finddomnode-forked-sjxwz5?workspaceId=1b72be1a-43a5-4335-8231-c6c61fc1819c)

### Steps to reproduce

Render a Dropdown component in React 18.3.

### What is expected?

No console errors.

### What is actually happening?

Console error.

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | Any |
| Browser | Chrome |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/51101/files

**Comment by wxs77577** [comment]
hotfix: https://github.com/ant-design/ant-design/issues/43064#issuecomment-2456508430
