### ISSUE TITLE
build fails due to antd qr-code rollup in vitejs

### ISSUE THREAD

**Issue by alenocera** [ant-design/ant-design#51100]
### Reproduction link
https://stackblitz.com/edit/antd-reproduce-5x-3z3k5b?file=vite.config.js

### Steps to reproduce

run the vite build without any particular commands.
```
{
"build": "vite build",
}
```

### What is expected?

The vite build can process all the import without block the process.

### What is actually happening?

The build process throw an error:
```
✓ 125 modules transformed.
x Build failed in 1.56s
error during build:
[vite]: Rollup failed to resolve import "@rc-component/qrcode" from "/app/node_modules/antd/es/qr-code/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:65532:17)
    at onwarn (/app/node_modules/@vitejs/plugin-react/dist/index.cjs:281:9)
    at onRollupWarning (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:65562:5)
    at onwarn (file:///app/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:65227:7)
    at file:///app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19393:13
    at Object.logger [as onLog] (file:///app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:21119:9)
    at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:20008:26)
    at file:///app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19966:26
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | node 20.10.0 |
| Browser | Chrome latest |

---
This issue block the build at all and we are not able to complete our deploy process.

**Comment by alenocera** [comment]
Reproduction link: https://antd-reproduce-5x-3z3k5b.stackblitz.io

Anyway I don't understand how we can build into stackblitz...but maybe doesn't matter.

**Comment by alenocera** [comment]
UPDATE:
I've rollback the library of ant from the `5.21.2` to the `5.18.3` and the build process works as expected. 
No changes happened with my `vite.config.js` file, so it is not related to vite.
Please help me by fixing the rollout issue above, I think the `qr-code` module have something issued.

**Comment by afc163** [comment]
> [antd-reproduce-5x-3z3k5b.stackblitz.io](https://antd-reproduce-5x-3z3k5b.stackblitz.io/)

I can't reproduce the error you describe, anything I miss?

**Comment by alenocera** [comment]
> .18.3

can yo utry this link? https://stackblitz.com/edit/antd-reproduce-5x?file=demo.tsx
sorry for the mistake

**Comment by afc163** [comment]
Still can't reproduce

<img width="1782" alt="image" src="https://github.com/user-attachments/assets/b3fbf68e-5e8d-42e5-abb1-aa69d2880893">

**Comment by alenocera** [comment]
How in stackblitz you can build the project?
You need to execute npm run build, don’t know how to achieve that into
stackblitz.

But for sure when I build the project into out env, the rollup step stop
the process and all fails.
This doesn’t happens with the 5.18.3 version.

Let me know if you need other type of info.

*Alessandro Nocera*
Quality Automation Supervisor
[image: Docebo]
Docebo | www.docebo.com
*Follow us: *LinkedIn <https://www.linkedin.com/company/docebo> | Facebook
<https://www.facebook.com/Docebo> | Twitter <https://twitter.com/docebo> |
Instagram <https://www.instagram.com/docebolearn/>
*Company Phone:* +39 039 232 3286

*Where leaders in learning get inspired* ✨
Inspire DALLAS | September 9 - 11
Inspire ROME | November 19 - 21

[image: Inspire 2024] <https://www.docebo.com/inspire/>


Il giorno sab 5 ott 2024 alle 15:09 afc163 ***@***.***> ha
scritto:

**Comment by afc163** [comment]
Could you provide a github repository?

**Comment by alenocera** [comment]
> Could you provide a minimal github repository?

Hi afc, the link for you:
https://github.com/alenocera/antd-51100

Please consider that we use the build through GitLab pipelines to build the project and then deploy it, so I can't post something else related to this. But I guess this is not relevant because the error that I've post days ago is pretty clear.

Let me know, I hope this will helpful for the community.

**Comment by afc163** [comment]
The exact steps to reproduce?

**Comment by alenocera** [comment]
Doing the build, we use into our docker file this:
`RUN npm install -g serve && npm i && npm run build`
So I guess you can build the project to look for the issue.
If it is doesn't appears locally, I was wondering you needs to recreate the docker container...but I don't know the time effort and the other tasks related to achieve that.

**Comment by dagadbm** [comment]
we had the same problem to latest version 5.23 and we had a major incident because of this blocking all users from using our app. would be nice if this actually gets looked at as we are not the only ones
