### ISSUE TITLE
Style of Table[expandedRowRender] is broken

### ISSUE THREAD

**Issue by zpczpc** [ant-design/ant-design#5113]
表格的列对齐有问题，展开时，水平对齐有问题

![image](https://cloud.githubusercontent.com/assets/20511586/23443017/1578d9d6-fe67-11e6-962a-3f26b3779e1a.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by zpczpc** [comment]
a re-producible demo:http://codepen.io/anon/pen/yMYZwG?editors=0010#anon-login

**Comment by benjycui** [comment]
This is what I see after expand. It seems that fixed table doesn't follow main table's height.

![image](https://cloud.githubusercontent.com/assets/3580607/23444762/e4b4c7d2-fe71-11e6-8b57-1a89f824f5b6.png)

**Comment by benjycui** [comment]
And I remember that we had decided not to support expandRowRender to work with fixed column? @afc163 

I cannot find that issue..

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/3394

**Comment by afc163** [comment]
and this one: https://github.com/ant-design/ant-design/issues/1898

We removed extra expandRowRender content from right-fixed table and leave style broken.

**Comment by afc163** [comment]
Maybe we should sync height of fixed column's expandedRow in rc-table too. @yesmeck

**Comment by yesmeck** [comment]
@afc163 I'll try.

**Comment by yesmeck** [comment]
@zpczpc Try reinstall node_modules.

**Comment by zpczpc** [comment]
@yesmeck @afc163 @benjycui     Thank you very much!  You are professional,respectable and  dedicated engineers, I worship you very much！

**Comment by badaljain** [comment]
HI, Similar to this but another issue:
![screen shot 2018-02-15 at 2 09 28 pm](https://user-images.githubusercontent.com/8784571/36283649-f7f07b46-1259-11e8-8bea-d8e2eb64ffe3.png)

**Comment by yesmeck** [comment]
@badaljain Please file a separator issue.
