### ISSUE TITLE
Splitter使用时，高度设置为自适应，会出现无限滚动条

### ISSUE THREAD

**Issue by 18830974630** [ant-design/ant-design#51146]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-poewyr?file=demo.tsx)

### Steps to reproduce

拖动即可出现

### What is expected?

可正常拖动，不会出现无限滚动条

### What is actually happening?

拖动后，出现无限滚动条

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | react |
| System | windows |
| Browser | 谷歌浏览器129.0.6668.90（正式版本） （64 位） |

**Comment by kiner-tang** [comment]
@18830974630 给的示例打不开
![image](https://github.com/user-attachments/assets/c9da9fc2-21c5-45c7-ac02-e898f1b46875)

**Comment by 18830974630** [comment]
> @18830974630给那些打不开 ![图像](https://private-user-images.githubusercontent.com/10286961/374380731-c9da9fc2-21c5-45c7-ac02-e898f1b46875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTM1NTMsIm5iZiI6MTcyODM1MzI1MywicGF0aCI6Ii8xMDI4Njk2MS8zNzQzODA3MzEtYzlkYTlmYzItMjFjNS00NWM3LWFjMDItZTg5OGYxYjQ2ODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZmZjNmZmODcyYTE3YjVkYjc0ZjYxYTZjYzU4ODc2NDRlYjAwNzk2OTU3YmZlMzc2NGI2ZTQ0ODc0NGUxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4EwSi19IkXK4DnFM0DazzcMG0zdyeJirpy8qpV9heGA)

试一下这个呢：https://stackblitz.com/edit/react-poewyr?file=demo.tsx

**Comment by zombieJ** [comment]
看了一下，已经修复过了。你升级一下版本：
https://stackblitz.com/edit/react-poewyr-it9qsa?file=demo.tsx,package.json
