### ISSUE TITLE
DirectoryTree点击范围不是整行

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#51145]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-m6kp8f?file=demo.tsx)

https://github.com/ant-design/ant-design/discussions/50915
### Steps to reproduce

点击任意一条数据行左侧空白部分
![image](https://github.com/user-attachments/assets/cf2ce62c-c55e-4cc8-a072-8ca7ef3e0fbe)

### What is expected?

整行都可以点击

### What is actually happening?

左侧空白部分点击无效

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by Meowu** [comment]
我看了一下，这个问题需要修改 `rc-tree` 的 `InternalTreeNode` ，目前底层仅能点击 title 的节点，也就是组件 `titleRender` 渲染的部份。
经过测试，要支持这个的话，可以给最外层的元素添加事件，这样空白的 Indent 和 Switcher-noop 部份都支持点击，包括点击元素之间的空白部份也会触发选中。
如果仅支持 DirectoryTree 这样点击，还需要修改这里的样式，以及传递一个 prop 去启用最外层的选择事件。

**Comment by afc163** [comment]
@Meowu 4.x 是可以的，先看看哪次修改改坏了。

**Comment by Meowu** [comment]
> @Meowu 4.x 是可以的，先看看哪次修改改坏了。

@afc163 我测了一下，从 4.x 开始就不可以了，3.x 都是可以的。

**Comment by afc163** [comment]
发现是 5 年前 @zombieJ 改造时改坏的，这里把 before 伪元素从内层 content-wrapper 节点移到外面了：https://github.com/ant-design/ant-design/pull/18172/files#diff-f27b9532d1fece5efa83797376f2bec755af1034a01fea65240e1307ade214b0R11-R21

但这个 before 伪元素不只是为了 hover 背景效果，也有交互响应的作用，挪出来之后交互没了。

五年了才被发现，给 @fpsqdb 点赞啊！

**Comment by fpsqdb** [comment]
既然是整行点击，感觉这个展开图标的hover效果可以去了，有点突兀
![image](https://github.com/user-attachments/assets/17b39fb2-e167-4b86-af21-309d7a5cb611)

**Comment by Meowu** [comment]
> 发现是 5 年前 @zombieJ 改造时改坏的，这里把 before 伪元素从内层 content-wrapper 节点移到外面了：https://github.com/ant-design/ant-design/pull/18172/files#diff-f27b9532d1fece5efa83797376f2bec755af1034a01fea65240e1307ade214b0R11-R21
> 
> 但这个 before 伪元素不只是为了 hover 背景效果，也有交互响应的作用，挪出来之后交互没了。
> 
> 五年了才被发现，给 @fpsqdb 点赞啊！

是的，我昨天也发现了是这里导致的。但是还没有找到解决办法。
因为 node-contente-wrapper 设置了 positive, 导致它的 :before 伪类不好相对于外面的 tree-node 进行绝对定位从而占满整行。
