### ISSUE TITLE
badge can't render 

### ISSUE THREAD

**Issue by DavidCHN** [ant-design/ant-design#5114]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by yesmeck** [comment]
请仔细阅读下 issue 模板。

**Comment by DavidCHN** [comment]
OK
西安图智信息技术有限公司 魏海龙 
地 址：陕西省西安市高新区高新三路8号橙仕空间1419室邮 编：710075手 机：15295182360Q  Q：1085550637电 话：029-89527330Email：weihl@geowit.cn网 址：http://www.geowit.cn
------------------------------------------------------------------发件人：Wei Zhu <notifications@github.com>发送时间：2017年3月1日(星期三) 11:48收件人：ant-design/ant-design <ant-design@noreply.github.com>抄　送：魏海龙 <weihl@geowit.cn>; Author <author@noreply.github.com>主　题：Re: [ant-design/ant-design] badge can't render (#5114)
请仔细阅读下 issue 模板。—
