### ISSUE TITLE
Select组件tags模式小疑问

### ISSUE THREAD

**Issue by Promisezhangbo** [ant-design/ant-design#51157]
### What problem does this feature solve?

是否可以新增一个属性，在onBlur时不添加tag或者不改变用户输入的值，现在用户在前后输入空格都会被自动清除，是否有办法规避这种行为

rc关联问题: 
https://github.com/react-component/select/issues/1075

https://github.com/react-component/select/pull/953

https://github.com/react-component/select/issues/952

### What does the proposed API look like?

在tags模式中，在失焦时可以不改变用户的输入,比如用户输入前后有空格失焦后可以不清除，或者失焦后在不新增选项

**Comment by Promisezhangbo** [comment]
重复点了，不好意思

**Comment by zombieJ** [comment]
纯键盘操作的系统中，输入完 tab 走作为提交是比较贴近直觉。如果不需要的话用 `onBlur` 事件 HOC 一下撤销 `searchValue` 即可。
