### ISSUE TITLE
FloatButton 悬浮按钮的菜单模式，触发条件是hover的情况下，无法点击菜单里面的图标

### ISSUE THREAD

**Issue by 894480109** [ant-design/ant-design#51158]
### Reproduction link

[https://ant-design.antgroup.com/components/float-button-cn#float-button-demo-group-menu](https://ant-design.antgroup.com/components/float-button-cn#float-button-demo-group-menu)

### Steps to reproduce

直接使用官方的例子试一下就可以，很难点击到菜单里面的2个图标，只要鼠标移动出悬浮按钮的范围，上面的菜单就收起来了，之前使用5.18.1版本的时候没有这个问题

### What is expected?

期望点击菜单按钮或者点击别的地方才关闭菜单

### What is actually happening?

菜单自动关闭，无法点击菜单内的图片

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | macOS 15.0.1 |
| Browser | chrome129 |

**Comment by aojunhao123** [comment]
经过排查，定位到问题是因为5.21.x的版本中，float-button-group组件使用了position:absolute，导致包裹的悬浮菜单脱离文档流。我尝试修复这个问题（移除绝对定位），但是发现源码的design token中大量使用了绝对定位的特性来计算样式😢，希望能得到后续的一些帮助 @Wxh16144 ,十分感谢！

**5.18.3**
![QQ_1728700817233](https://github.com/user-attachments/assets/dbee2a2c-ead3-4516-a08c-75a83b79701e)
**5.21.0**
![QQ_1728700630192](https://github.com/user-attachments/assets/db88baa5-d5f6-4ec9-b4dd-3e04695ba119)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50407 @li-jia-nan 这里改坏的？

**Comment by li-jia-nan** [comment]
> #50407 @li-jia-nan 这里改坏的？这个问题影响可用性了。

确实是 #50407 这里改坏的，感觉不太好修

**Comment by afc163** [comment]
@li-jia-nan 统一换成 rc-trigger 实现就行。

**Comment by li-jia-nan** [comment]
> @li-jia-nan 统一换成 rc-trigger 实现就行。

那是不是得封装一个底层的 rc-floatButton 组件了？我看 rc-trigger 在 antd 侧好像没有用到？都是底层组件暴露出来

**Comment by li-jia-nan** [comment]
另外这个还用到了 rc-motion

**Comment by afc163** [comment]
简单的做法是在这里加个透明的伪元素。

<img width="74" alt="截屏2024-10-14 09 59 27" src="https://github.com/user-attachments/assets/fbe7cadb-fe13-4db8-8389-5801a5f846a6">

**Comment by aojunhao123** [comment]
> 简单的做法是在这里加个透明的伪元素。
> 
> <img alt="截屏2024-10-14 09 59 27" width="74" src="https://private-user-images.githubusercontent.com/507615/376089679-fbe7cadb-fe13-4db8-8389-5801a5f846a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzE2ODcsIm5iZiI6MTcyODg3MTM4NywicGF0aCI6Ii81MDc2MTUvMzc2MDg5Njc5LWZiZTdjYWRiLWZlMTMtNGRiOC04Mzg5LTU4MDFhNWY4NDZhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwMjAzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDhhMTY0N2UyZTE4MGU0MTdmNWI3MDA1YzQ0NGMyZDE1MGMwNTY5YzMwMjUwZTY3YzkyZDEwZTMzZDNkN2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hKFWwifnNQz2GDVjK_h0bYjK7ezALo6xua4iYNzNJpw">

我来！🙋

**Comment by aojunhao123** [comment]
已修复，请review #51208
