### ISSUE TITLE
npm run dist failed

### ISSUE THREAD

**Issue by UtherPim** [ant-design/ant-design#51155]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/~/github.com/UtherPim/ant-design)

### Steps to reproduce

1. clone repository;
2. npm i;
3. npm run dist;
![image](https://github.com/user-attachments/assets/2ad263cb-714a-4b81-bf52-479f5eff72f5)

### What is expected?

正常打包

### What is actually happening?

dist打包失败

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | win10 |
| Browser | chrome@128 |

### What is expected?

正常打包

### What is actually happening?

dist打包失败

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | win10 |
| Browser | chrome@128 |

**Comment by UtherPim** [comment]
> 楼上机器人回复可以参考一下，我用 macos 最新代码(#42a3770e7d)是可以构建并且分析的，不排除是 win 和 macos 差异。webpack config 最近在 #51098 有更新

我用mac也可以，但是公司是windows。楼上机器人回复都试过了，没用。。。你们用windows可以成功dist吗。。

**Comment by zombieJ** [comment]
试试 yarn，stackbliz 依赖太多下载不下来，我用 gitpod 试了一下 yarn 可以：

<img width="826" alt="截屏2024-10-08 17 22 47" src="https://github.com/user-attachments/assets/dfed663c-f10f-44c1-87bd-343dd40ef79e">

**Comment by UtherPim** [comment]
> 试试 yarn，几个 web ide 都成功了：
> 
> #### Stackbliz
> <img alt="截屏2024-10-08 19 28 05" width="843" src="https://private-user-images.githubusercontent.com/5378891/374536683-2adb931a-22af-4307-b81b-1a39c1a8ec3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTM2MDQsIm5iZiI6MTcyODM5MzMwNCwicGF0aCI6Ii81Mzc4ODkxLzM3NDUzNjY4My0yYWRiOTMxYS0yMmFmLTQzMDctYjgxYi0xYTM5YzFhOGVjM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTMxNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU1MTI1ZTU4OWU2NGZlNDY4ZmRjMmI3ZmY1ODZkYTllYzhkYTBhYjkwYmQyZGY2NDEzYzY5ODYxMzQ3NzYzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2_8bRdIE1l9FkXzasPWDePr-W22_cHjcq4FfnIJ4y3U">
> #### gitpod
> <img alt="截屏2024-10-08 17 22 47" width="826" src="https://private-user-images.githubusercontent.com/5378891/374494925-dfed663c-f10f-44c1-87bd-343dd40ef79e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTM2MDQsIm5iZiI6MTcyODM5MzMwNCwicGF0aCI6Ii81Mzc4ODkxLzM3NDQ5NDkyNS1kZmVkNjYzYy1mMTBmLTQ0YzEtODdiZC0zNDNkZDQwZWY3OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTMxNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhhMDUxZTEzNzg5OTM5NThiNDg1OGVmOTg0MjBkNGYwZWY0M2NlMmJmNGRiNTAyNjkxNDlkMDVmY2IwMGE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WqNPaLcK0MXsA89f1xLybZ1nn4nOQE8ZlUkXDTwbB0k">

用yarn确实可以，但是为啥呀。。。

**Comment by zombieJ** [comment]
pkg manager 实现各不相同，有时候就会遇到某个出问题用不了。习惯性就切另一个，大概率就好了。毕竟代码人写的，保不齐会遇到问题。

**Comment by afc163** [comment]
@UtherPim 试试更新到 npm 最新版本。
