### ISSUE TITLE
希望增加table筛选下拉，默认展示方向，默认是bottomRight

### ISSUE THREAD

**Issue by liluxin-s** [ant-design/ant-design#51151]
### What problem does this feature solve?

自定义了筛选图标位置，期望默认筛选下拉浮层也能支持配置，以在筛选层面保持一致

### What does the proposed API look like?

filterDirection = ‘bottomLeft’

**Comment by MadCcc** [comment]
暂时还不支持，可以先使用 `filterDropdown` 来自定义下拉菜单实现 https://ant.design/components/table-cn#table-demo-custom-filter-panel

**Comment by wangchaoHeart** [comment]
我也遇到了这个问题， 我自定义了筛选图标位置，导致筛选下拉浮层会溢出我想要他展示的区域，因为他总是bottomLeft，
能否加一个配置可以控制展示方向？
![image](https://github.com/user-attachments/assets/5cfa94ba-5dcc-435d-b68d-0dad0890e198)

**Comment by wangchaoHeart** [comment]
> 暂时还不支持，可以先使用 `filterDropdown` 来自定义下拉菜单实现 https://ant.design/components/table-cn#table-demo-custom-filter-panel

filterDropdown只可以自定义弹框里面的内容，而不能配置弹框本身

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/45515 搞了一半，谁来继续搞完就能支持了。

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/issues/45898

**Comment by liluxin-s** [comment]
如果我现在的antd版本是4.x，该怎么实现呢
