### ISSUE TITLE
Twitchy Paragraph

### ISSUE THREAD

**Issue by ValeriiL17** [ant-design/ant-design#51162]
### Reproduction link

[https://codepen.io/barsiculier-yes-zhZHonov/pen/qBeaxxo?editors=001](https://codepen.io/barsiculier-yes-zhZHonov/pen/qBeaxxo?editors=001)

### Steps to reproduce

Reproduce the rendering of the "Paragraph" component from "Typography", with a large text content and "ellipsis" properties with "defaultExpanded" and "expanded" parameters set to "false", preferably with "throttling" enabled in the DevTools so that it's easier to see the state of the component.

### What is expected?

It is expected that the component will be immediately displayed in a collapsed state

### What is actually happening?

Now, when rendering, the component is displayed first in open form, after which it is immediately redrawn and displayed in collapsed form, a jerky effect is obtained when drawing. Although the "ellipsis" parameters pass the "defaultExpanded" and "expanded" parameters as "false"

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | React 18.2.0 |
| System | Windows 11 |
| Browser | Yandex Browser 24.7.4.1316 (64-bit) |

---
After rendering, the component is displayed in an expanded form, and then in a closed one. The twitching effect is obtained. Why is the component not displayed immediately in closed form, because the "defaultExpanded" and "expanded" parameters are passed as "false" in the"ellipsis" props

**Comment by zombieJ** [comment]
It's by design. Since SSR env do not have the browser context which will make all ellipsis for the first hydrate. So ellipsis is always render full content and then cut to ellipsis.

If you want to ellipsis as native css effect. You can remove expand config which will not use js ellipsis and use css ellipsis instead.
