### ISSUE TITLE
使用Splitter组件，使用复杂组合时，意外出现滚动条

### ISSUE THREAD

**Issue by 18830974630** [ant-design/ant-design#51167]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-f13bxj?file=demo.tsx)

### Steps to reproduce

右侧区域将下方的内容拉取到隐藏即可出现滚动条

### What is expected?

没有滚动条出现

### What is actually happening?

有滚动条出现

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | react |
| System | windows |
| Browser | 谷歌浏览器129.0.6668.90（正式版本） （64 位） |

**Comment by 18830974630** [comment]
如果demo地址不能访问的话，使用官方文档中的复杂组合demo中也可出现相关问题

**Comment by zombieJ** [comment]
需要不出现滚动条加个 div 设置 overflow hidden 即可。展示滚动条是预期的，否则用户拉紧了超出内容就看不到了：

https://stackblitz.com/edit/react-f13bxj-aztgi5?file=demo.tsx

**Comment by 18830974630** [comment]
![image](https://github.com/user-attachments/assets/c5c5ae86-6ed3-4562-b818-655ec6ed662f)
是这个滚动条啊

**Comment by zombieJ** [comment]
> 是这个滚动条啊

soga，我误解了。感觉如果 Panel 只有 Splitter 子元素可以直接hidden 一下。

**Comment by 18830974630** [comment]
> > 是这个滚动条啊
> 
> soga，我忘了。感觉如果Panel只有Splitter子元素可以直接隐藏一下。
这个方式可以解决又滚动条的问题，但是在一定程度，使用起来感觉很奇怪，极端情况下，需要多次嵌套，那就需要在很多结构中

**Comment by 18830974630** [comment]
> > 是这个滚动条啊
> 
> soga，我误解了。感觉如果 Panel 只有 Splitter 子元素可以直接hidden 一下。

这个方式可以解决这个滚动条的问题，但是，使用起来感觉很奇怪，比如极端情况，需要多次嵌套组合，那就需要在每一个上都加上hidden

**Comment by zombieJ** [comment]
对的，我在 PR，稍等哈~
