### ISSUE TITLE
calendar期望支持 日/月/年 切换

### ISSUE THREAD

**Issue by Mrcxt** [ant-design/ant-design#51163]
### What problem does this feature solve?

期望增加颗粒度为一天的功能

### What does the proposed API look like?

期望支持 日/月/年 切换

**Comment by MadCcc** [comment]
你期望的 api 和交互是什么样的？

**Comment by Mrcxt** [comment]
> 你期望的 api 和交互是什么样的？

目前想实现一个类似飞书日历的功能，我目前使用的是fullcalendar来实现的，交互的话就是实现年月日切换，以及任务显示。

<img width="865" alt="image" src="https://github.com/user-attachments/assets/85b6153e-0bc9-47ff-994d-8cb11c01b77b">

<img width="877" alt="image" src="https://github.com/user-attachments/assets/d7dfe914-ddfc-41d0-8665-9f58012aa723">

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/8024
