### ISSUE TITLE
Select menu search single mode

### ISSUE THREAD

**Issue by KagChi** [ant-design/ant-design#51177]
### What problem does this feature solve?

when creating form with so much value that need select menu and search. this resolve the issue

### What does the proposed API look like?

```js
<Form.Item
          name="customer"
          label="Customer"
          rules={[{ required: false }]}
          getValueFromEvent={(x: { value: string }) => x.value}
      >
          <DebounceSelect
              mode="single"
              value={selectedItem?.customer ? { value: selectedItem?.customer?.id, label: `${selectedItem.customer?.name} (${selectedItem?.customer?.contact_person})` } : null}
              placeholder="Pilih Customer"
              fetchOptions={fetchCustomer}
              style={{ width: "100%" }}
          />
</Form.Item>
```

**Comment by afc163** [comment]
How about https://ant.design/components/select-cn ?

**Comment by KagChi** [comment]
> How about https://ant.design/components/select ?

Select search DOES not support single mode. only multiple and tags.

**Comment by afc163** [comment]
https://ant.design/components/select#select-demo-search

![Oct-10-2024 09-59-24](https://github.com/user-attachments/assets/757bf52c-94c2-4fe6-8e70-003b6756307c)

**Comment by KagChi** [comment]
> https://ant.design/components/select#select-demo-search
> 
> ![Oct-10-2024 09-59-24](https://private-user-images.githubusercontent.com/507615/375184324-757bf52c-94c2-4fe6-8e70-003b6756307c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDE4NDEsIm5iZiI6MTcyODU0MTU0MSwicGF0aCI6Ii81MDc2MTUvMzc1MTg0MzI0LTc1N2JmNTJjLTk0YzItNGZlNi04ZTcwLTAwM2I2NzU2MzA3Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNjI1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWU0Mzc0NjhjNTY1Yzk3NjI2NTI0YThhYzk1YmVjMTcwMThiNzVlYTc5YTIyNGQ0OTdiNDY3NWZmYTZiZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bwc5i62yd-my9o3trYblTg0RPPKd64DXK3S3Nato8L4) [ ![Oct-10-2024 09-59-24](https://private-user-images.githubusercontent.com/507615/375184324-757bf52c-94c2-4fe6-8e70-003b6756307c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDE4NDEsIm5iZiI6MTcyODU0MTU0MSwicGF0aCI6Ii81MDc2MTUvMzc1MTg0MzI0LTc1N2JmNTJjLTk0YzItNGZlNi04ZTcwLTAwM2I2NzU2MzA3Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNjI1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWU0Mzc0NjhjNTY1Yzk3NjI2NTI0YThhYzk1YmVjMTcwMThiNzVlYTc5YTIyNGQ0OTdiNDY3NWZmYTZiZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bwc5i62yd-my9o3trYblTg0RPPKd64DXK3S3Nato8L4) ](https://private-user-images.githubusercontent.com/507615/375184324-757bf52c-94c2-4fe6-8e70-003b6756307c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDE4NDEsIm5iZiI6MTcyODU0MTU0MSwicGF0aCI6Ii81MDc2MTUvMzc1MTg0MzI0LTc1N2JmNTJjLTk0YzItNGZlNi04ZTcwLTAwM2I2NzU2MzA3Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNjI1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWU0Mzc0NjhjNTY1Yzk3NjI2NTI0YThhYzk1YmVjMTcwMThiNzVlYTc5YTIyNGQ0OTdiNDY3NWZmYTZiZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bwc5i62yd-my9o3trYblTg0RPPKd64DXK3S3Nato8L4) [ ](https://private-user-images.githubusercontent.com/507615/375184324-757bf52c-94c2-4fe6-8e70-003b6756307c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDE4NDEsIm5iZiI6MTcyODU0MTU0MSwicGF0aCI6Ii81MDc2MTUvMzc1MTg0MzI0LTc1N2JmNTJjLTk0YzItNGZlNi04ZTcwLTAwM2I2NzU2MzA3Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwNjI1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWU0Mzc0NjhjNTY1Yzk3NjI2NTI0YThhYzk1YmVjMTcwMThiNzVlYTc5YTIyNGQ0OTdiNDY3NWZmYTZiZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Bwc5i62yd-my9o3trYblTg0RPPKd64DXK3S3Nato8L4)

i want to combine with ajax

**Comment by KagChi** [comment]
Soo any arguments about this?

**Comment by KagChi** [comment]
sir @afc163 ?

**Comment by IsKaros** [comment]
You can fetch data using the prop `onSearch` .Check the `fetch` function in the demo quoted please.
