### ISSUE TITLE
select组件在多选受控场景，value内出现相同内容，组件tag展示会有问题。

### ISSUE THREAD

**Issue by CoCoManYY** [ant-design/ant-design#51175]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-tq3rcn?file=demo.tsx)

### Steps to reproduce

刷新下页面，首先value的tag为 a10、a10，过1秒后，setValue为 a13、a10，组件tag却展示成了a10、a13、a10
![img_v3_02fg_89218e14-63d6-4d4f-b98b-d95347816a4g](https://github.com/user-attachments/assets/c3937892-4cdb-414c-94e8-76816ab40419)

### What is expected?

期望能够展示 a13、a10

### What is actually happening?

a10、a13、a10

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
value 不应该重复。
