### ISSUE TITLE
Form.useWatch() 支持 debounce

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design#51173]
### What problem does this feature solve?

当 Form.useWatch() 监听一个 text input 组件时，键盘打字会导致 state 频繁变化从而使组件不停地刷新，这可能会导致性能问题，尤其是在移动端。因此我们希望在 Form 的 value 变成 state 之前，进行 debounce，以减少更新频率。

### What does the proposed API look like?

```js
// debounce 500ms
const phone = Form.useWatch('phone', { form, debounce: 500 });
```

**Comment by afc163** [comment]
要为 `Form.useWatch()` 添加防抖功能，可以使用 `lodash` 库中的 `debounce` 函数。下面是一个基本的实现示例：

```jsx
import React, { useEffect, useState } from 'react';
import { Form, Input } from 'antd';
import debounce from 'lodash/debounce';

const MyComponent = () => {
  const [form] = Form.useForm();
  const [debouncedValue, setDebouncedValue] = useState();

  const watchedValue = Form.useWatch('myField', form);

  useEffect(() => {
    const handler = debounce((value) => {
      setDebouncedValue(value);
    }, 300); // 300ms 的防抖间隔

    handler(watchedValue);

    return () => {
      handler.cancel();
    };
  }, [watchedValue]);

  return (
    <Form form={form}>
      <Form.Item name="myField" label="My Field">
        <Input />
      </Form.Item>
      <p>Debounced Value: {debouncedValue}</p>
    </Form>
  );
};

export default MyComponent;
```

**解释**：

1. **Form.useWatch**: 用于监视表单字段的值。
2. **debounce**: 引入 `lodash` 的 `debounce` 函数来防止值过于频繁地更新。
3. **useEffect**: 每当 `watchedValue` 变化时，触发防抖函数，并在组件卸载或 `watchedValue` 变更前取消上一个防抖调用。

这种方式确保了输入的变化被限制在一定的频率内，从而提高性能并减少不必要的重渲染。

**Comment by afc163** [comment]
当然！我们可以封装一个 `useDebounceWatch` 自定义 Hook。这个 Hook 可以接收表单实例、字段名称以及防抖延迟时间，然后返回防抖后的值。

```jsx
import { useState, useEffect } from 'react';
import { Form } from 'antd';
import debounce from 'lodash/debounce';

const useDebounceWatch = (name, form, delay = 300) => {
  const [debouncedValue, setDebouncedValue] = useState();
  const watchedValue = Form.useWatch(name, form);

  useEffect(() => {
    const handler = debounce((value) => {
      setDebouncedValue(value);
    }, delay);

    handler(watchedValue);

    return () => {
      handler.cancel();
    };
  }, [watchedValue, delay]);

  return debouncedValue;
};

export default useDebounceWatch;
```

你可以在组件中这样使用这个 Hook：

```jsx
import React from 'react';
import { Form, Input } from 'antd';
import useDebounceWatch from './useDebounceWatch';

const MyComponent = () => {
  const [form] = Form.useForm();
  const debouncedValue = useDebounceWatch('myField', form, 300);

  return (
    <Form form={form}>
      <Form.Item name="myField" label="My Field">
        <Input />
      </Form.Item>
      <p>Debounced Value: {debouncedValue}</p>
    </Form>
  );
};

export default MyComponent;
```

**说明**：

- **useDebounceWatch**: 自定义 Hook，使用 `Form.useWatch` 监控字段值变化，并通过 `debounce` 实现防抖。
- **delay 参数**: 允许你设置防抖的时间间隔，默认为 300 毫秒。

这样封装后，可以轻松在多个组件中使用这个功能。

**Comment by guoyunhe** [comment]
@afc163 你的这种实现虽然实现了防抖，但是仍然会导致 React 组件渲染次数过多的问题，导致打字时界面卡顿。消除卡顿，提升性能是我提这个需求的主要目的。Form value 应该在转换为 state 之前进行防抖，而不是之后。

**Comment by crazyair** [comment]
防抖不都是这样用的吗？https://ahooks.js.org/zh-CN/hooks/use-debounce#usedebounce-demo1

**Comment by crazyair** [comment]
如果 render 卡，那现在 render 跟等一秒 render 都问题，比如在一秒后 render 的时候，再输入内容，页面不一样会卡？

**Comment by afc163** [comment]
@guoyunhe 你需要 `startTransition`，而非 debounce。

**Comment by afc163** [comment]
请给一个 antd Form useWatch 和 startTransition 一起使用的例子，用于解决以下问题：当 Form.useWatch() 监听一个 text input 组件时，键盘打字会导致 state 频繁变化从而使组件不停地刷新，这可能会导致性能问题，尤其是在移动端。

---

可以结合 useWatch 和 startTransition 来解决 Form.useWatch 监听输入时的性能问题。useWatch 在输入过程中频繁触发状态更新，而 startTransition 允许在性能敏感的情况下，延迟非紧急的状态更新，减少渲染压力。

以下是一个使用 Form.useWatch 和 startTransition 结合的例子：

import React, { useState, useTransition } from 'react';
import { Form, Input } from 'antd';

const MyForm = () => {
  const [form] = Form.useForm();
  const [inputValue, setInputValue] = useState('');
  const [isPending, startTransition] = useTransition();

  // 使用 useWatch 监听输入框的值
  const watchedValue = Form.useWatch('textInput', form);

  // 当 useWatch 监控到变化时，通过 startTransition 延迟处理更新
  React.useEffect(() => {
    startTransition(() => {
      setInputValue(watchedValue || '');
    });
  }, [watchedValue]);

  return (
    <Form form={form}>
      <Form.Item name="textInput" label="Text Input">
        <Input placeholder="Type something..." />
      </Form.Item>
      <div>
        <p>Watched Value (Updated with transition): {isPending ? 'Loading...' : inputValue}</p>
      </div>
    </Form>
  );
};

export default MyForm;

代码说明：

	1.	Form.useWatch：监听表单项（textInput）的值。
	2.	startTransition：当输入框值发生变化时，通过 startTransition 包裹状态更新逻辑，以减少不必要的重渲染。即使输入值变化很频繁，它将推迟状态更新的优先级，使性能更平稳。
	3.	isPending：标记状态更新是否正在处理中，防止过多的 UI 渲染导致性能瓶颈。

这样就能在大量输入的情况下减轻 UI 过于频繁的刷新。

**Comment by guoyunhe** [comment]
> 如果 render 卡，那现在 render 跟等一秒 render 都有问题，比如在一秒后 render 的时候，再输入内容，页面不一样会卡

@crazyair 打字比较快的情况，比如一秒钟输入五次，不 debounce 一秒要渲染五次，debounce 的话，一秒只渲染一次，区别还是很大的。

**Comment by guoyunhe** [comment]
@afc163 只要使用了 useWatch，就会触发重新渲染，再用 startTransition 应该是没有用的。

**Comment by linxianxi** [comment]
其实还是少用 useWatch，你可以给个代码写出你的场景，我们看下是不是一定要用 useWatch。Form 本来就是用来减少 render 的，useWatch 又会增加 render。

**Comment by guoyunhe** [comment]
> 其实还是少用 useWatch，你可以给个代码写出你的场景，我们看下是不是一定要用 useWatch。Form 本来就是用来减少 render 的，useWatch 又会增加 render。

@linxianxi 当然很多场景都可以不用 useWatch，甚至可以不用 React 来直接操作 DOM。但是这样做必然会导致要手写很多逻辑，降低开发效率。提供 useWatch 本来就是为了平衡运行性能与开发效率，这里建议增加 debounce 并不是说没有 debounce 就实现不了，而是有 debounce 更便利可以减少开发工作量。

**Comment by linxianxi** [comment]
你可以在 Input 的 onChange 里自己 debounce 一下。

**Comment by afc163** [comment]
> 当然！我们可以封装一个 `useDebounceWatch` 自定义 Hook。这个 Hook 可以接收表单实例、字段名称以及防抖延迟时间，然后返回防抖后的值。
> 
> ```js
> import { useState, useEffect } from 'react';
> import { Form } from 'antd';
> import debounce from 'lodash/debounce';
> 
> const useDebounceWatch = (name, form, delay = 300) => {
>   const [debouncedValue, setDebouncedValue] = useState();
>   const watchedValue = Form.useWatch(name, form);
> 
>   useEffect(() => {
>     const handler = debounce((value) => {
>       setDebouncedValue(value);
>     }, delay);
> 
>     handler(watchedValue);
> 
>     return () => {
>       handler.cancel();
>     };
>   }, [watchedValue, delay]);
> 
>   return debouncedValue;
> };
> 
> export default useDebounceWatch;
> ```
> 
> 你可以在组件中这样使用这个 Hook：
> 
> ```js
> import React from 'react';
> import { Form, Input } from 'antd';
> import useDebounceWatch from './useDebounceWatch';
> 
> const MyComponent = () => {
>   const [form] = Form.useForm();
>   const debouncedValue = useDebounceWatch('myField', form, 300);
> 
>   return (
>     <Form form={form}>
>       <Form.Item name="myField" label="My Field">
>         <Input />
>       </Form.Item>
>       <p>Debounced Value: {debouncedValue}</p>
>     </Form>
>   );
> };
> 
> export default MyComponent;
> ```
> 
> **说明**：
> 
>     * **useDebounceWatch**: 自定义 Hook，使用 `Form.useWatch` 监控字段值变化，并通过 `debounce` 实现防抖。
> 
>     * **delay 参数**: 允许你设置防抖的时间间隔，默认为 300 毫秒。
> 
> 
> 这样封装后，可以轻松在多个组件中使用这个功能。

我感觉这个是符合预期的，试试看？

**Comment by linxianxi** [comment]
这样只是最后的值 debounce 了，render 没有 debounce，还是会一直 render，因为 useWatch 内部的 state 一直在变。

**Comment by crazyair** [comment]
测试了吗，redner 只是 hooks 里 render，外面使用也会有吗？

**Comment by afc163** [comment]
问了多次得到一个版本：https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-21-3-forked-vc86ps?file=%2Fdemo.tsx%3A19%2C10

---

你遇到的问题是因为 Form.useWatch 返回的值变化时，组件每次都会渲染，即使在应用了 debounce 之后。这是因为 Form.useWatch 本身会导致组件更新。

为了解决这个问题，可以使用 useRef 来存储当前的 watchedValue，这样可以避免组件的过度渲染。useRef 不会导致重新渲染，而是保持引用到当前值，然后通过 startTransition 处理状态更新，以降低优先级，防止频繁渲染。

修改后的解决方案如下：

```jsx
import React, { useState, useEffect, useRef, useTransition } from 'react';
import { Form, Input } from 'antd';
import { debounce } from 'lodash';

// 自定义 useDebounceWatch 钩子
const useDebounceWatch = (fieldName: string, form: any, delay: number) => {
  const watchedValue = Form.useWatch(fieldName, form); // 监听表单字段变化
  const [debouncedValue, setDebouncedValue] = useState(watchedValue);
  const valueRef = useRef(watchedValue);
  const [isPending, startTransition] = useTransition(); // React 18 的 startTransition

  useEffect(() => {
    valueRef.current = watchedValue;

    // debounce 函数用于更新 debouncedValue
    const handler = debounce(() => {
      startTransition(() => {
        setDebouncedValue(valueRef.current);
      });
    }, delay);

    handler();

    // 清除上一次的 debounce 函数
    return () => {
      handler.cancel();
    };
  }, [watchedValue, delay]);

  return debouncedValue;
};

const MyComponent = () => {
  const [form] = Form.useForm();
  const debouncedValue = useDebounceWatch("myField", form, 1000); // 1秒的 debounce

  console.log("render", debouncedValue); // 只有 debouncedValue 变化时才会触发

  return (
    <Form form={form}>
      <Form.Item name="myField" label="My Field">
        <Input />
      </Form.Item>
      <p>Debounced Value: {debouncedValue}</p>
    </Form>
  );
};

export default MyComponent;
```

解决方式的关键点：

1.	useRef: valueRef.current 保留了 watchedValue 的最新值，但它不会触发组件重新渲染，因此每次输入时不会强制刷新组件。
2.	startTransition: React 18 的 startTransition 用来标记低优先级更新，它将 setDebouncedValue 的更新延迟到适合的时机来触发，这样可以避免组件过度渲染。
3.	debounce: debounce 的作用是减少频繁的状态更新，只有在经过 1 秒的延迟后才会更新 debouncedValue。

这样一来，只有当 debouncedValue 改变时组件才会重新渲染，避免了每次输入都会立即触发 render 的问题。

**Comment by linxianxi** [comment]
不是一直在打印 render 吗😂？只能改 useWatch 源码才行的。

**Comment by crazyair** [comment]
这是个伪需求，如果这个页面很大，render 一次就很卡，那每次输入都卡，跟隔一秒卡一次都影响用户使用

应该把 render 控制在小范围。比如把需要获取 watch 值的抽离为一个小子组件，则可以小范围 render，页面就不会卡了

**Comment by zombieJ** [comment]
useWatch 就是为了 render 同步做的，如果要防抖就直接 onFieldsChange 里 HOC 了。

**Comment by crazyair** [comment]
```tsx
import React, { useState } from 'react';
import { useDebounceFn } from 'ahooks';
import { Form, Input } from 'antd';

const Demo = () => {
    const [form] = Form.useForm();

    const [name, setName] = useState<string>();
    const { run } = useDebounceFn(value => setName(value), { wait: 500 });

    console.log('name', name);

    return (
        <Form<{ name?: string }>
            form={form}
            onFieldsChange={field => {
                const data = field.find(item => `${item.name}` === 'name');
                if (data) {
                    run(data.value);
                }
            }}
        >
            <Form.Item label="姓名" name="name">
                <Input />
            </Form.Item>
        </Form>
    );
};
export default Demo;

```

**Comment by afc163** [comment]
> 不是一直在打印 render 吗😂？只能改 useWatch 源码才行的。

@linxianxi 我没保存上，你再访问试试。

**Comment by linxianxi** [comment]
> > 不是一直在打印 render 吗😂？只能改 useWatch 源码才行的。
> 
> @linxianxi 我没保存上，你再访问试试。

不行，不可能行的🤪

**Comment by huchaolin** [comment]
> 要为 `Form.useWatch()` 添加防抖功能，可以使用 `lodash` 库中的 `debounce` 函数。下面是一个基本的实现示例：
> 
> import React, { useEffect, useState } from 'react';
> import { Form, Input } from 'antd';
> import debounce from 'lodash/debounce';
> 
> const MyComponent = () => {
>   const [form] = Form.useForm();
>   const [debouncedValue, setDebouncedValue] = useState();
> 
>   const wat
>   useEffect(() => {
>     const handler = debounce((value) => {
>       setDebouncedValue(value);
>     }, 300); // 300ms 的防抖间隔
> 
>     handler(watchedValue);
> 
>     return () => {
>       handler.cancel();
>     };
>   }, [watchedValue]);
> chedValue = Form.useWatch('myField', form);
> 
>   return (
>     <Form form={form}>
>       <Form.Item name="myField" label="My Field">
>         <Input />
>       </Form.Item>
>       <p>Debounced Value: {debouncedValue}</p>
>     </Form>
>   );
> };
> 
> export default MyComponent;
> **解释**：
> 
> 1. **Form.useWatch**: 用于监视表单字段的值。
> 2. **debounce**: 引入 `lodash` 的 `debounce` 函数来防止值过于频繁地更新。
> 3. **useEffect**: 每当 `watchedValue` 变化时，触发防抖函数，并在组件卸载或 `watchedValue` 变更前取消上一个防抖调用。
> 
> 这种方式确保了输入的变化被限制在一定的频率内，从而提高性能并减少不必要的重渲染。

debounce 不是这样使用的， 上面的写法相当于 每次值变动都生成一个新的debounce的函数， 你应该把debounce提到useEffect外面 并用useMemo封装并且useMemo不应该有任何变动的依赖， 参考：


import debounce from 'lodash/debounce';

export default () => {
 const [form] = Form.useForm();
const [debouncedValue, setDebouncedValue] = useState();

const debouncedHandler = useMemo(() =>debounce(
			(params) => {
				//  需要debounce的逻辑
                                 setDebouncedValue()params;
			},
			300, // 防抖时间
			{ // 以下配置根据使用自行场景调整
				leading: false, // （默认为 false）：如果设置为 true，则在函数首次被调用时立即执行一次函数，而不是在等待延迟时间后执行。如果设置为 false 或未提供该参数，则第一次函数调用会等待指定的延迟时间后才执行。
				trailing: true // （默认为 true）：如果设置为 true 或未提供该参数，则在函数最后一次被调用后，再等待指定的延迟时间后执行一次函数。如果设置为 false，则最后一次函数调用不会触发延迟执行。
			}
		), []);

useEffect(() => {

    debouncedHandler(watchedValue);

return () => {
     debouncedHandler.cancel();
};
 }, [watchedValue]);

return xxxxxxx
}
