### ISSUE TITLE
yarn build error 

### ISSUE THREAD

**Issue by tommy26tan** [ant-design/ant-design#51171]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antd-reproduce-5x?file=demo.tsx)

### Steps to reproduce

yarn build

### What is expected?

no build error

### What is actually happening?

build error 

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | react@18.3.1 |
| System | windows |
| Browser | chrome |

---
This is my tsconfig. 
{
  "compilerOptions": {
    "jsx": "react",
    "module": "NodeNext",
    "target": "ESNext",
    "moduleResolution": "NodeNext",
    "outDir": "out",
    "lib": ["ES2022", "DOM"],
    "sourceMap": true,
    "rootDir": "./",
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedParameters": true,
    "allowJs": true,
    "types": ["mocha", "node"],
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "include": ["src", "test"],
  "exclude": ["node_modules", ".vscode-test"]
}

**Comment by tommy26tan** [comment]
yarn build
yarn run v1.22.22
$ run-s build:*
$ tsc
node_modules/antd/es/form/Form.d.ts:5:30 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("scroll-into-view-if-needed")' call instead.

5 import type { Options } from 'scroll-into-view-if-needed';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/es/form/interface.d.ts:2:47 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("scroll-into-view-if-needed")' call instead.

2 export type { Options as ScrollOptions } from 'scroll-into-view-if-needed';
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/es/theme/util/genStyleUtils.d.ts:6:221 - error TS2304: Cannot find name 'CompTokenMap'.        

6     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C], undefined> extends infer T extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_1], undefined> ? { [key in T]: boolean; } : never) | undefined;
  
                                                                                                             ~~~~~~~~~~~~

node_modules/antd/es/theme/util/genStyleUtils.d.ts:6:247 - error TS2304: Cannot find name 'C_1'.

6     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C], undefined> extends infer T extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_1], undefined> ? { [key in T]: boolean; } : never) | undefined;
  

                      ~~~

node_modules/antd/es/theme/util/genStyleUtils.d.ts:17:225 - error TS2304: Cannot find name 'CompTokenMap'.       

17     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C_2], undefined> extends infer T_2 extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_2_1], undefined> ? { [key_2 in T_2]: boolean; } : never) | undefined;
   

 ~~~~~~~~~~~~

node_modules/antd/es/theme/util/genStyleUtils.d.ts:17:251 - error TS2552: Cannot find name 'C_2_1'. Did you mean 
'C_2'?

17     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C_2], undefined> extends infer T_2 extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_2_1], undefined> ? { [key_2 in T_2]: boolean; } : never) | undefined;
   

                           ~~~~~

node_modules/antd/es/theme/util/genStyleUtils.d.ts:25:225 - error TS2304: Cannot find name 'CompTokenMap'.       

25     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C_1], undefined> extends infer T_1 extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_1_1], undefined> ? { [key_1 in T_1]: boolean; } : never) | undefined;
   

 ~~~~~~~~~~~~

node_modules/antd/es/theme/util/genStyleUtils.d.ts:25:251 - error TS2304: Cannot find name 'C_1_1'.

25     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C_1], undefined> extends infer T_1 extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_1_1], undefined> ? { [key_1 in T_1]: boolean; } : never) | undefined;
   

                           ~~~~~

node_modules/antd/es/theme/util/genStyleUtils.d.ts:25:251 - error TS2552: Cannot find name 'C_1_1'. Did you mean 
'C_1'?

25     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C_1], undefined> extends infer T_1 extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_1_1], undefined> ? { [key_1 in T_1]: boolean; } : never) | undefined;
   

                           ~~~~~

node_modules/rc-picker/lib/PickerPanel/index.d.ts:40:18 - error TS2430: Interface 'SinglePickerPanelProps<DateType>' incorrectly extends interface 'BasePickerPanelProps<DateType>'.
  Types of property 'defaultValue' are incompatible.
    Type 'DateType | null | undefined' is not assignable to type 'DateType | undefined'.
      Type 'null' is not assignable to type 'DateType | undefined'.

40 export interface SinglePickerPanelProps<DateType extends object = any> extends BasePickerPanelProps<DateType> 
{
                    ~~~~~~~~~~~~~~~~~~~~~~


Found 10 errors in 4 files.

Errors  Files
     1  node_modules/antd/es/form/Form.d.ts:5
     1  node_modules/antd/es/form/interface.d.ts:2
     7  node_modules/antd/es/theme/util/genStyleUtils.d.ts:6
     1  node_modules/rc-picker/lib/PickerPanel/index.d.ts:40
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:tsc" exited with 2.
error Command failed with exit code 1.

**Comment by afc163** [comment]
@tommy26tan Could you provide a reproducible github repo?

**Comment by tommy26tan** [comment]
In node_modules/antd/es/form/Form.d.ts. 
![Screenshot 2024-10-10 095623](https://github.com/user-attachments/assets/210d1dc5-f206-43bc-9d7b-a139666f29c1
我的項目設置的是NodeNest as module resolution, typescript把T.DS認成CommonJS module了， 然後import 的是 ES module.

**Comment by tommy26tan** [comment]
import type { Options } from 'scroll-into-view-if-needed' assert { "resolution-mode": "import" }; 改成這樣就SOLVE了， 這樣TypeScript就把他當成ES 而不是 CJS import ESM

**Comment by tommy26tan** [comment]
還是有幾個其他的ERROR， for type checking in d.ts
yarn run v1.22.22
$ run-s build:*
$ tsc
node_modules/antd/es/theme/util/genStyleUtils.d.ts:6:221 - error TS2304: Cannot find name 'CompTokenMap'.

6     unitless?: (keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<ComponentTokenMap, AliasToken>[C], undefined> extends infer T extends keyof Exclude<import("@ant-design/cssinjs-utils").OverrideTokenMap<CompTokenMap, AliasToken>[C_1], undefined> ? { [key in T]: boolean; } : never) | undefined;

**Comment by tommy26tan** [comment]
https://github.com/ant-design/ant-design/issues/50334
這個哥們已經report 了 必須skipLibCheck 爲什麽Close了

**Comment by afc163** [comment]
@tommy26tan 我们没有重现出问题，请务必帮助我们重现。

> [什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/ant-design/wiki/%E4%BB%80%E4%B9%88%E6%98%AF%E6%9C%80%E5%B0%8F%E5%8C%96%E9%87%8D%E7%8E%B0%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E6%98%AF%E5%BF%85%E9%9C%80%E7%9A%84%EF%BC%9F)

**Comment by tommy26tan** [comment]
https://codesandbox.io/p/devbox/antd-5-21-2-comptokenmap-forked-xdrqff?file=%2Ftsconfig.json%3A12%2C6-12%2C23
@afc163

**Comment by afc163** [comment]
@tommy26tan Removed pnpm-lock.yml and it works fine: https://codesandbox.io/p/devbox/antd-5-21-2-comptokenmap-forked-5hdxn9

<img width="1782" alt="image" src="https://github.com/user-attachments/assets/543dff81-7932-4ef5-81e9-d1c0f05d9721">

**Comment by tommy26tan** [comment]
did you run "yarn build" in the terminal?
l

**Comment by tommy26tan** [comment]
@afc163  removed the yml file and run "yarn build" in the terminal, error persist

**Comment by tommy26tan** [comment]
@afc163 
Thanks for fixing the issue. 
I got one more question if i change moudle to NodeNext and moduleResolution to NodeNext there is other build error, but the error is gone if i set Module to ESNext and moduleResolution to bundler
{
  "compilerOptions": {
    "jsx": "react",
    "module": "NodeNext",
    "target": "ESNext",
    "moduleResolution": "NodeNext",
    "outDir": "out",
    "lib": ["ES2022", "DOM"],
    "sourceMap": true,
    "rootDir": "./",
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedParameters": true,
    "allowJs": true,
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}

Error log:
➜  workspace git:(master) ✗ yarn build
yarn run v1.22.19
$ tsc --noEmit && vite build
node_modules/.pnpm/antd@5.21.2_react-dom@18.2.0_react@18.2.0/node_modules/antd/es/form/Form.d.ts:5:30 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("scroll-into-view-if-needed")' call instead.

5 import type { Options } from 'scroll-into-view-if-needed';

**Comment by tommy26tan** [comment]
@afc163 . It should support Module:NodeNext and ModuleResolution:NodeNext?
