### ISSUE TITLE
Table scroll x设置固定值后固定列缺失阴影

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#51170]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-onzefe?file=demo.tsx,index.tsx)

### Steps to reproduce

https://github.com/user-attachments/assets/b249d9a4-0276-4fd9-bd72-70c1a442fc87

5.20.6是正常的
https://stackblitz.com/edit/react-onzefe-nxghhf?file=demo.tsx,index.tsx

https://github.com/user-attachments/assets/29915b28-ebf9-489e-b0c7-179e1678309f

### What is expected?

固定列能正常显示阴影

### What is actually happening?

固定列无阴影

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by linxianxi** [comment]
可以先把 scrollX 的值设置成所有 column width 相加的值，例子里是 1500
