### ISSUE TITLE
Forms cannot persist state when use with Step component.

### ISSUE THREAD

**Issue by kamote** [ant-design/ant-design#5118]
#### Environment(required)

- antd version: 2.7.4
- OS and its version: macOS Sierra 10.12.3
- Browser and its version: Google Chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
Step Steps content is a Form using getFieldDecorator. 
1. To reproduce put something on the input 
2. Hit Next, value will persist on second step.
3. Hit Prev, value will not persist anymore.

#### What do you expected?

Expect to persist the state of form even going back to previous step.

#### What happen?
State/value does not persists

#### Re-producible online demo

http://codepen.io/kamote/pen/EWVMrZ?editors=0010

**Comment by benjycui** [comment]
Yep, because field will be destroyed when it is not rendered.

Just set `display: none | hidden` to hide fields which you don't want to show.
