### ISSUE TITLE
Splitter 组件支持 lazy 高性能模式

### ISSUE THREAD

**Issue by sheng-di** [ant-design/ant-design#51190]
### What problem does this feature solve?

这个支持 lazy 模式吗？
比如一些组件大小发生变化，就需要进行大量的计算。
能否有这样的功能：
用户拖动时，不实际进行 resize，等用户放下鼠标后，再触发 resize。

这样只会 resize 一次，性能会好一些。

拖动过程中，可以有一个临时的 splitter 移动的效果。

### What does the proposed API look like?

这个支持 lazy 模式吗？
比如一些组件大小发生变化，就需要进行大量的计算。
能否有这样的功能：
用户拖动时，不实际进行 resize，等用户放下鼠标后，再触发 resize。

这样只会 resize 一次，性能会好一些。

拖动过程中，可以有一个临时的 splitter 移动的效果。

**Comment by afc163** [comment]
挺好的需求。

**Comment by zombieJ** [comment]
> 拖动过程中，可以有一个临时的 splitter 移动的效果。

脑补一个矩形线框，感觉不错

**Comment by crazyair** [comment]
拖拽有2种形式，一种实时变位置，一种只有标记，放在才换位置

**Comment by wanpan11** [comment]
在你的组件外层加一层 div 然后定义一个 width ，当 onResizeEnd 触发式 再更新这个 width

这样应该也能实现吧

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/51557

**Comment by roddc** [comment]
加了lazy后为什么onResizeEnd的sizes是上一次的尺寸?

**Comment by wanpan11** [comment]
> 加了lazy后为什么onResizeEnd的sizes是上一次的尺寸?

可以新开 issues 提供复现，目前看好像没问题
