### ISSUE TITLE
Carousel bug

### ISSUE THREAD

**Issue by chibaoshui** [ant-design/ant-design#5120]
代码在楼下

组件上添加autoplay之后，beforeChange（from，to）里面的从和到
控制台显示为
1,1 
2,2 
0,0 
但是用鼠标手动点击焦点控制台显示
0,1 
1,2 
2,0

antd版本：2.7.2
操作系统及其版本：win10
浏览器及此版本：chrome 58.0.3000.4

**Comment by chibaoshui** [comment]
// You should fork and save if you had updated this CodePend and want to send it to others.
// Note: antd.locales are only support by `dist/antd`
const { Carousel } = antd;
function _beforeChange(from, to) {
    console.log('from:'+from+'-----to:'+to);
}
function _afterChange(current) {
    console.log('当前是第'+current+'节点');
}
let settings = {
            effect: 'fade',	//动画效果函数，可取 scrollx, 默认值fade
            autoplay: true,//是否自动切换	boolean	默认值false
            easing: 'linear'	,//动画效果	string	默认值linear
            autoplaySpeed: 3000,
            pauseOnHover: true, //鼠标悬停轮播暂停
        };
        let jsonData = [{"color":"orange"},{"color":"gray"}];
        let arr = jsonData.map( (data,index) => {
            console.log(data.color);
            return (
                <div key={index}>
                    <div style={{height:'100px',background:'orange'}}>{data.color}</div>
                </div>
            )
        });
ReactDOM.render(
  <div>
     <Carousel  beforeChange={_beforeChange} afterChange={_afterChange} {...settings}>
     {arr}
     </Carousel>
  </div>
, mountNode);

**Comment by afc163** [comment]
duplicate https://github.com/ant-design/ant-design/issues/5071

Still don't provide re-producible demo.
