### ISSUE TITLE
Nextjs, Antd, ConfigProvider Could not find the module

### ISSUE THREAD

**Issue by C-L-STARK** [ant-design/ant-design#51200]
### Reproduction link

[https://None](https://None)

### Steps to reproduce

```typescript
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, theme } from "antd";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* defaultAlgorithm, compactAlgorithm */}
        <ConfigProvider theme={{ algorithm: [theme.darkAlgorithm, theme.compactAlgorithm] }}>
          <AntdRegistry>{children}</AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}

```

### What is expected?

```
```

### What is actually happening?

Unhandled Runtime Error
```
Error: Could not find the module "~/Desktop/fastx-ai.com/antd-next-template/node_modules/.pnpm/antd@5.21.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/antd/es/index.js@__barrel_optimize__?names=ConfigProvider,theme#theme#darkAlgorithm" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
```

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18^ |
| System | macos |
| Browser | latest |

---
```
{
  "name": "antd-next-template",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@ant-design/nextjs-registry": "^1.0.1",
    "antd": "^5.21.3",
    "next": "14.2.15",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.15",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}

```

**Comment by C-L-STARK** [comment]
follow this guide `https://ant-design.antgroup.com/docs/react/use-with-next-cn`

**Comment by C-L-STARK** [comment]
按照官方文档必现；算了不浪费时间了。

**Comment by afc163** [comment]
function 参数在 RSC 里没法序列化传给 client 端，因此 algorithm 目前只能在 client 组件里使用。

**Comment by afc163** [comment]
@zombieJ algorithm 这个缺陷在 server component 里不太好用，是不是设计一个 `theme={ mode: ['dark', 'compact'] }}` 更好？

**Comment by C-L-STARK** [comment]
使用Nextjs，在最外层layout，因为ConfigProvider原因，设置为"use client"是不是不太友好；这样的话和直接使用react貌似没什么多大的区别；

> function 参数在 RSC 里没法序列化传给 client 端，因此 algorithm 目前只能在 client 组件里使用。
> 
> ```
>  ⨯ Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
>   [function derivative, ...]
>    ^^^^^^^^^^^^^^^^^^^
>     at stringify (<anonymous>)
>     at stringify (<anonymous>)
> ```

**Comment by C-L-STARK** [comment]
使用Nextjs，在最外层layout，因为ConfigProvider原因，设置为"use client"是不是不太友好；这样的话和直接使用react貌似没什么多大的区别；

> function 参数在 RSC 里没法序列化传给 client 端，因此 algorithm 目前只能在 client 组件里使用。
> 
> ```
>  ⨯ Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
>   [function derivative, ...]
>    ^^^^^^^^^^^^^^^^^^^
>     at stringify (<anonymous>)
>     at stringify (<anonymous>)
> ```

**Comment by zombieJ** [comment]
> @zombieJ algorithm 这个缺陷在 server component 里不太好用，是不是设计一个 `theme={ mode: ['dark', 'compact'] }}` 更好？

这样会把很多算法都打进去，另外如果是自定义的算法的这个语法糖是没用的。

**Comment by afc163** [comment]
那现在这个问题有啥好解法么？

**Comment by C-L-STARK** [comment]
我暂时是放弃了ant-design；只能暂时选择其他的

**Comment by wongyat88** [comment]
[NextJs 14 App Route with Ant Design Theme Switch](https://github.com/wongyat88/NextJs14AppRouteWithAntDesignThemeing)

我不确定我在 Next.js 14 中使用 App Router 和 Ant Design 主题的设置是否正确。我使用 `next-themes` 来处理主题切换，并且在客户端渲染所有 Ant Design 元素（因为如果在服务器端渲染会出现闪烁）。

我看到有人提到 `theme.darkAlgorithm` 在服务器端不受支持，但我也看到其他 UI 框架也需要用 `'use client'` 来包装 Theme Provider。

根据 [Next.js 14 的文档](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#interleaving-server-and-client-components)，它说服务器端组件仍然可以通过 props 传递给客户端组件，而服务器端组件将继续在服务器端渲染。

我对 Next.js 很陌生，所以我不知道如何测试它。但如果我理解正确，`app/xxx/page.tsx` 应该是一个服务器端组件。如果你需要与用户交互（比如带有 `onClick` 的按钮），那么你需要创建一个新的组件文件 `HitLikeButton.tsx` 并将其传递给 `app/xxx/page.tsx`。所以 `app/xxx/page.tsx` 仍将在服务器端渲染，而 `HitLikeButton.tsx` 将在客户端渲染。

因此，为了 SEO，我认为我们只需要在 `app/[productID]/page.tsx` 中使用 `await` 来获取元数据，并创建一些隐藏的 `<p>` 元素来存储一些产品数据。然后，其他漂亮的 Ant Design 元素可以在其他组件中，并传递回 `app/[productID]/page.tsx`，这样就可以了（元数据将从 `app/[productID]/page.tsx` 获取并服务器渲染，而 Ant Design 元素和其他数据将在客户端渲染）。

------------------------------

I am unsure if I have the correct setup of Next.js 14 with the App Router and Ant Design Theme. I use `next-themes` to handle theme switching and also client-side render all Ant Design elements (as there will be flickering if rendered on the server side).

I see people mentioning that `theme.darkAlgorithm` is not supported on the server side, but I have seen other UI frameworks also require wrapping the Theme Provider with `'use client'`.

According to the [Next.js 14 documentation](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#interleaving-server-and-client-components), it says that a server-side component can still be passed to a client-side component via props while the server-side component will still be server-side rendered.

I am new to Next.js, so I don't know how to test it. But if I understand correctly, `app/xxx/page.tsx` should be a server-side component. If you need to interact with the user (like a button with `onClick`), you then need to create a new component file `HitLikeButton.tsx` and pass it to `app/xxx/page.tsx`. So `app/xxx/page.tsx` will still be server-side, and `HitLikeButton.tsx` will be client-side.

So for SEO, I think we just need to `await` fetch the metadata in `app/[productID]/page.tsx` and create some hidden `<p>` elements to store some product data. Then other Ant Design beautiful elements can be in some other components and passed back to `app/[productID]/page.tsx`, which will be fine (metadata will be obtained from `app/[productID]/page.tsx` and server-rendered, while Ant Design elements and other data will be client-side rendered).

**Comment by farmer00317558** [comment]
@zombieJ 这个问题有什么进展吗？

**Comment by C-L-STARK** [comment]
> @zombieJ 这个问题有什么进展吗？搞笑的是 @C-L-STARK 为啥一直在 close 这个 issue？😄

Because I am a person with severe obsessive-compulsive disorder
因为我是一个强迫症很重的人

**Comment by yoyo837** [comment]
有需要的话，可以新开一个issue

**Comment by jellohouse** [comment]
Is there a way to use the darkAlgorithm in a server component?

I tried to do `import darkAlgorithm from 'antd/lib/theme/themes/dark';`

But also getting this:
```
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  {algorithm: function derivative, token: ...}
```
