### ISSUE TITLE
PaginationConfig ts定义中 align 属性没了

### ISSUE THREAD

**Issue by xuchaoying** [ant-design/ant-design#51207]
### Reproduction link

[https://ant.design/components/list-cn#list-demo-pagination](https://ant.design/components/list-cn#list-demo-pagination)

### Steps to reproduce

官网List的分页demo可以复现

### What is expected?

pagination中可以设置align属性

### What is actually happening?

现在提示Object literal may only specify known properties, and 'align' does not exist in type 'PaginationConfig'.

<img width="864" alt="image" src="https://github.com/user-attachments/assets/8b876c71-5755-4303-a233-7b9e7a8cbea2">

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18 |
| System | macOS |
| Browser | chrome |

**Comment by aojunhao123** [comment]
这应该是**@stackblitz/sdk**的bug，使用Codesandbox打开则没有这种情况，以及使用Stackblitz打开antd仓库的对应demo文件也不会产生这个ts报错。

**Comment by xuchaoying** [comment]
> 这应该是**@stackblitz/sdk**的bug，使用Codesandbox打开则没有这种情况，以及使用Stackblitz打开antd仓库的对应demo文件也不会产生这个ts报错。

不是哦，确实去掉了，不知道为什么

https://github.com/ant-design/ant-design/commit/e76e3869668c00f0d19ddd4afd734dabafb7cd97#diff-6ded05884b813a9ee306b10152a2e379ac9c8c724ade740984c1aed485d14352L35

**Comment by LonelySnowman** [comment]
@xuchaoying 去掉是因为最终继承了 rc-pagination 中的 align 属性，我这边是正常的。看看是不是你 vscode 插件的问题，或者尝试重装下依赖。

**Comment by xuchaoying** [comment]
> @xuchaoying 去掉是因为最终继承了 rc-pagination 中的 align 属性，我这边是正常的。看看是不是你 vscode 插件的问题，或者尝试重装下依赖。

我的 rc-pagination 中没有这个align属性，版本 3.2.0
