### ISSUE TITLE
使用 Remix 时打包生成 sourcemap 错误

### ISSUE THREAD

**Issue by banqinghe** [ant-design/ant-design#51213]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/remix-run-remix-ksafw7)

### Steps to reproduce

```shell
npm install
npm run build
```

### What is expected?

无报错，成功打包

### What is actually happening?

打包成功，但输出生成 sourcemap 错误：

```
node_modules/antd/es/affix/index.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/antd/es/app/index.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/antd/es/auto-complete/index.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/antd/es/card/index.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
...
```

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.2.0 |
| System | macOS Ventura |
| Browser | Chrome 131.0.6770.0（正式版本）canary (arm64) |

---
与 https://github.com/ant-design/ant-design/issues/46273 指出的错误一致，但我用 vite 没复现出该错误，使用 remix 的最小模板则可以复现。

**Comment by zombieJ** [comment]
这个看起来是 remix -> vite -> rollup 的问题，组件侧没什么可以做的。可以参考一下 vite 的 issue 追踪一下 bug fix 或者配置 ignore 掉：

https://github.com/vitejs/vite/issues/15012

**Comment by banqinghe** [comment]
感谢提示，看到了这个 [https://github.com/pmndrs/jotai/issues/2269#issuecomment-1826427962](https://github.com/pmndrs/jotai/issues/2269#issuecomment-1826427962)，加了 `rollup-preserve-directives` 这个插件确实解决了。
