### ISSUE TITLE
resizeSpinnerSize 这个命名不妥

### ISSUE THREAD

**Issue by tylerlong** [ant-design/ant-design#51218]
### Reproduction link

[https://ant.design/components/splitter](https://ant.design/components/splitter)

### Steps to reproduce

https://ant.design/components/splitter

### What is expected?

修改 resizeSpinnerSize 命名

### What is actually happening?

resizeSpinnerSize 命名很随意. Spinner 的意思在这里用不合适.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.3.1 |
| System | macOS |
| Browser | Chrome 129.0.6668.90  |

---
可以考虑把 spinner 改为 toggler

**Comment by afc163** [comment]
确实不妥，感觉是打错了。cc @wanpan11

**Comment by wanpan11** [comment]
我改下
