### ISSUE TITLE
Image.PreviewGroup 如果只存在一张图片，countRender API不生效

### ISSUE THREAD

**Issue by A9074o** [ant-design/ant-design#51216]
### What problem does this feature solve?

目前我使用的版本为4.21.2。
但是在4.24.0的版本中发现countRender 可以正常生效了。
项目公司过于庞大，没办法不计成本和代价更新到4.24.0。
所以希望能不能再4.21.2。改进一下这个API，这两天项目要上线了，突然发现这个问题。有点急

### What does the proposed API look like?

在4.21.2版本中Image.PreviewGroup中哪怕只有一张图片也可以正常去走countRender。显示出对应的render。

![image](https://github.com/user-attachments/assets/ae2d2eee-cf05-416a-b9dd-ceb089b7d107)

**Comment by A9074o** [comment]
由于需要在预览图片的时候显示对应的图片名称。可是发现countRender在一张图片的时候不生效了。

![image](https://github.com/user-attachments/assets/bde974c8-a773-400c-9a93-bb18f397b159)

**Comment by banqinghe** [comment]
如果实在不能升级的话，用 npm/yarn/pnpm 的包别名能力，再装一个版本的 antd，从新版本 antd 里引这个组件就行了吧。

[https://stackoverflow.com/questions/56134857/how-to-install-npm-package-under-alias-or-different-name](https://stackoverflow.com/questions/56134857/how-to-install-npm-package-under-alias-or-different-name)
