### ISSUE TITLE
动态表单name, 提交的值不对

### ISSUE THREAD

**Issue by joey2217** [ant-design/ant-design#51215]
### Reproduction link

[https://codepen.io/joey2217/pen/OJKWjKQ](https://codepen.io/joey2217/pen/OJKWjKQ)

### Steps to reproduce

输入name, 切换lang, 再输入name,点击提交

### What is expected?

提交的值和 form.getFieldValue 获取的值一致

### What is actually happening?

提交的值和 form.getFieldValue 获取的不一致, value 的 name 只包含最后 lang 的 key

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.3.1 |
| System | Windows |
| Browser | Edge129 |

**Comment by crazyair** [comment]
看代码，有好几处问题，你先尝试换成 useWatch 试试。

**Comment by joey2217** [comment]
> 看代码，有好几处问题，你先尝试换成 useWatch 试试。

现在用 form.getFieldValue 能获取的预期的值,我只想 sbmit 能直接获取预期值
