### ISSUE TITLE
ant-design Grid system need 576px threshold

### ISSUE THREAD

**Issue by chikara-chan** [ant-design/ant-design#5122]
#### Environment(required)

- antd version: whatever
- OS and its version: whatever
- Browser and its version: whatever

#### What did you do? Please provide steps to re-produce your problem.

Recently, I started with ant-design. I wanna a grid to make layout responsive. However,  I discover in ant-design, the smallest  grid threshold is 768px rather than 576px or smaller. The problem is that the ui looks so wide in a bit less than 768px. It cannot be accepted!

#### Re-producible online demo

Goto the link and resize the window. Tell me what do you feel. Thank you

http://codepen.io/chikara-chan/pen/BWogPG?editors=0010

**Comment by afc163** [comment]
How aboult add a new break pointer `xxs` for `576px`?

**Comment by chikara-chan** [comment]
But now, `xs` represent the smallest breakpoint, and always has float layout. Use `xxs` is not reasonable and  make incompatible API changes. The best solution is to redesign grid system in next major version

**Comment by afc163** [comment]
Your best solution now is [customize theme](https://ant.design/docs/react/customize-theme) and override the [@screen-sm](https://github.com/ant-design/ant-design/blob/570e2ce1dcfe60cddae5bcdd96b7f3a755ca4eef/components/style/themes/default.less#L128).

**Comment by chikara-chan** [comment]
Override style cannot resolve the original problem. The problem is now the breakpoint `768 992 1200` is not enough. So my proposal is refactor it in ant-design 3.

**Comment by afc163** [comment]
What a perfect breakpoints system you suggest?

**Comment by afc163** [comment]
We just add a 1600 breakpoint at `feature-2.8`: https://github.com/ant-design/ant-design/pull/4796

**Comment by chikara-chan** [comment]
We do need 1600px, it's great for 1920px width screen.  However,  the current smallest breakpoint 768px is too wide.
And Bootstrap 4 set `sm` to 576px, Gaia set `sm` to 570px, Pure CSS set `sm` to 568px. These could be a reference.

**Comment by univentco** [comment]
any updates on this?

**Comment by bodaz** [comment]
any updates on this?

**Comment by devuxer** [comment]
@afc163,

Just looking at v4 breakpoints...there *still* should be an `xxs`.

With the way it is now, an iPhone 5 (viewport width 320px) has to have the same layout as an iPhone 8 Plus (viewport width 414px).

That means you get no advantage if you have a modern, large phone with a wider screen.

Also, name me a device that has a viewport width between 576 and 767px. I don't see any in [this list](https://yesviz.com/devices.php). So, that one is kind of a waste.

To me, it would be better to put the breakpoints between major categories of devices that actually exist. This would be a better list:

- **xxs** - old, narrow phone - <350px
- **xs** - modern, regular phone - 351px-400px
- **sm** - modern, wide phone - 401px-600px
- **md** - small tablet - 701px-900px
- **lg** - large tablet - 901px-1200px
- **xl** - laptop/desktop - 1201px-1800px
- **xxl** - HD laptop/desktop - >1800px

**Comment by Muhammadsajid12** [comment]
ant design have no XXS breake point?

**Comment by Muhammadsajid12** [comment]
i have to cover XXS screen how to do?
