### ISSUE TITLE
table Column render  返回参数的api

### ISSUE THREAD

**Issue by chengdick** [ant-design/ant-design#51227]
### What problem does this feature solve?

在table 中添加进度条问题

### What does the proposed API look like?

The render function of cell, has three params: the text of this cell, the record of this row, the index of this row, it's return an object:{ children: value, props: { colSpan: 1, rowSpan:1 } } ==> 'children' is the text of this cell, props is some setting of this cell, eg: 'colspan' set td colspan, 'rowspan' set td rowspan   我看到rc-table 有这个api，antd没有对应的demo，api使用方法

**Comment by chengdick** [comment]
期望加上

**Comment by afc163** [comment]
> 我看到rc-table 有这个api，antd没有对应的demo，api使用方法

antd 也支持的，如果不支持，可以提供一个重现看看。
