### ISSUE TITLE
希望ant-design增加原子组件以支持复杂场景（比如仅保留基础样式的table）， 类似shadcn ui

### ISSUE THREAD

**Issue by 1057105012** [ant-design/ant-design#51222]
### What problem does this feature solve?

1. 对于较为基础的需求来说， datatable以及ant desgin的大部分组件已经满足需求， 但是对于复杂场景或者较多自定义出现的时候， 就不得不关注如何修改ant desgin的原本结构， 这个过程需要大量的阅读文档， 以了解如何嵌入相关代码。 比如我的card的title期望是一个动画或者一个动态文本？ 或者我的表格期望展示为非ant desgin默认样式？， 或者我期望使用tanstack table而不是ant table, 我仅仅需要ant desgin的样式。这些需求在缺乏原子组件的情况下都变得比较复杂

### What does the proposed API look like?

期望ant desgin的设计抽离逻辑到ant table hook , ant select hook, 然后抽离样式组件实现为原子组件， th->tr->td, select->options. 这样也许更为灵活。 比如table的树形菜单， 也许th->tr->expandsPanel->td->expandsContent比起配置方式更为灵活。或者说支持类似shadcn ui 那种原子化组件

**Comment by zombieJ** [comment]
设计系统的初衷就是对原子组件进行封装（这里的原子组件和你这边理解的有一些出入），纯 headless 组件本身的缺点就是功能无法复杂化，一旦能力上去那样式的耦合度就会急剧上升。

在 Ant Design 中，底层使用 rc-xx 库做底层能力支持。如果你希望是不带 antd 样式，可以考虑直接使用 rc 库（在 antd 的 package.json 中 rc- 开头的便是），rc 库有基础的 less 样式可以自行选择用或者不用。

**Comment by 1057105012** [comment]
我想表达的是过多的功能和封装程度阻碍了对于组件的绝对控制。对于有些人来说功能并不必须，而仅仅需要基础美观的样式组件而已。headless的终极目的是去除功能而不是样式。具体可以参考shadcn和tanstack table hook结合的table操作方式。个人认为这种方式更为灵活

**Comment by yoyo837** [comment]
antd不是这种模式，选择了antd就无法获得你要的模式

**Comment by warmhug** [comment]
@zombieJ  rc 组件的底层思路, 跟现在的 headless 在设计上差别还是挺大的. 

但是 antd 功能复杂, 按 类似 shadcn ui 新模式 抽象的话 要有挺多工作量, 船大难掉头 价值收益对公司来说不算太大.
不过 material ui 在年初是开始干这个事了, 只是感觉进度有点慢. 
https://mui.com/blog/base-ui-2024-plans/
![image](https://github.com/user-attachments/assets/4f73f369-50bc-4ba3-ab02-3348b8878bc3)

当然 antd 如果做个底层大重构, 也有个很大的好处, 比如 能更加扩大社区到国外. 
比如现在有贸易战和审查, 国内太卷 有些国内出海的公司 会被要求禁用国人开发的技术.
这样 antd 这种高度封装的大型库 就不能用了. 如果能像 shadcn 一样 可以只用某几个组件, 那还是可以继续使用.

类似需求 以后可能越来越多, 不管 antd 最终要不要做, 感觉 @afc163  可以给个最终答复哈.
