### ISSUE TITLE
Typography.Link 添加了user-select: none;导致无法被选中

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#51232]
### Reproduction link

[https://ant.design/components/typography-cn](https://ant.design/components/typography-cn)

### Steps to reproduce

如下

https://github.com/user-attachments/assets/1fcbf0bf-5467-4024-a988-aed0432c281e

### What is expected?

可以选中

### What is actually happening?

不可选中

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by lucas200631** [comment]
这个会修复吗 还是说将来就是这样了 不让复制？

**Comment by afc163** [comment]
@lucas200631 不如直接来个 PR 修一下？

**Comment by lucas200631** [comment]
> @lucas200631 不如直接来个 PR 修一下？

等我再发现一定搞一个pr
