### ISSUE TITLE
validateFields无法校验自定义组件设置的值

### ISSUE THREAD

**Issue by niuweili** [ant-design/ant-design#51237]
### Reproduction link

[https://codepen.io/niuweili66/pen/bGXqpOz?editors=1111](https://codepen.io/niuweili66/pen/bGXqpOz?editors=1111)

### Steps to reproduce

在使用PriceInput自定义组件的onChange事件中通过setFieldValue修改表单的值后再调用validateFields后，并没有执行validator绑定的checkPrice

### What is expected?

期望通过调用validateFields进行validator中的规则校验

### What is actually happening?

调用validateFields后未执行validator中的规则校验

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | 18.2 |
| System | 14.6 (23G80) |
| Browser | chrome  129.0.6668.59 |

**Comment by zombieJ** [comment]
[FAQ: 为什么 Form.Item 嵌套子组件后，不更新表单值？](https://ant-design.antgroup.com/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-formitem-%E5%B5%8C%E5%A5%97%E5%AD%90%E7%BB%84%E4%BB%B6%E5%90%8E%E4%B8%8D%E6%9B%B4%E6%96%B0%E8%A1%A8%E5%8D%95%E5%80%BC)

**Comment by niuweili** [comment]
> [FAQ: 为什么 Form.Item 嵌套子组件后，不更新表单值？](https://ant-design.antgroup.com/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-formitem-%E5%B5%8C%E5%A5%97%E5%AD%90%E7%BB%84%E4%BB%B6%E5%90%8E%E4%B8%8D%E6%9B%B4%E6%96%B0%E8%A1%A8%E5%8D%95%E5%80%BC)

这个没有解决我的问题，问题在于调用validateFields没有执行validator所绑定的校验函数

**Comment by niuweili** [comment]
> [FAQ: 为什么 Form.Item 嵌套子组件后，不更新表单值？](https://ant-design.antgroup.com/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-formitem-%E5%B5%8C%E5%A5%97%E5%AD%90%E7%BB%84%E4%BB%B6%E5%90%8E%E4%B8%8D%E6%9B%B4%E6%96%B0%E8%A1%A8%E5%8D%95%E5%80%BC)

[录屏2024-10-14 19.41.55.zip](https://github.com/user-attachments/files/17363385/2024-10-14.19.41.55.zip)
这个没有解决我的问题，附上录屏
setFieldValue方法没有重置当前表单的错误信息，validateFields也无效

**Comment by chenmijiang** [comment]
> > [FAQ: 为什么 Form.Item 嵌套子组件后，不更新表单值？](https://ant-design.antgroup.com/components/form-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-formitem-%E5%B5%8C%E5%A5%97%E5%AD%90%E7%BB%84%E4%BB%B6%E5%90%8E%E4%B8%8D%E6%9B%B4%E6%96%B0%E8%A1%A8%E5%8D%95%E5%80%BC)
> 
> [录屏2024-10-14 19.41.55.zip](https://github.com/user-attachments/files/17363385/2024-10-14.19.41.55.zip) 这个没有解决我的问题，附上录屏 setFieldValue方法没有重置当前表单的错误信息，validateFields也无效
请把包裹 PriceInput外的div去掉，faq已经说的很明白了
![image](https://github.com/user-attachments/assets/369bc580-9947-49bb-93a1-f48dadfb2e9f)
