### ISSUE TITLE
Add Close Icon Position for Drawer

### ISSUE THREAD

**Issue by Sarthak-ONS** [ant-design/ant-design#51230]
### What problem does this feature solve?

By default, close icon in drawer is aligned on left of header, we need a feature to change the icon position to right or left.

### What does the proposed API look like?

We can pass props named closeIconPosition to Drawer Component, and change the insets from left ro right

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/35776
