### ISSUE TITLE
弹出窗口报Ｊｓ错误，在最新的ｅｄｇｅ或ｃｈｒｏｍｅ浏览器中

### ISSUE THREAD

**Issue by HuaFangYun** [ant-design/ant-design#51246]
### Reproduction link
![image](https://github.com/user-attachments/assets/b5746739-c054-4935-b34c-76f9911a49a2)

[https://4x.ant.design/components/modal/](https://4x.ant.design/components/modal/)

### Steps to reproduce

打开这个链接，https://4x.ant.design/components/modal/
再单击 Open Modal  按钮，按F12

### What is expected?

消除错误提示

### What is actually happening?

       Failed to load resource: the server responded with a status of 404 ()
modal/:1 Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. <div tabindex=​"0" aria-hidden=​"true" style=​"width:​ 0px;​ height:​ 0px;​ overflow:​ hidden;​ outline:​ none;​">​</div>​
modal/:1 Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. <div tabindex=​"0" aria-hidden=​"true" style=​"width:​ 0px;​ height:​ 0px;​ overflow:​ hidden;​ outline:​ none;​">​</div>​
demo.f223fb.js:129 Clicked cancel button
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.
Chrome is moving towards a new experience that lets people make an informed choice with respect to third-party cookies.

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 4.24.16 |
| System | Win11 |
| Browser | Edge最新版 |

**Comment by zombieJ** [comment]
v4 已经过了维护期了哈~~
