### ISSUE TITLE
Cascader showSearch 的 limit 设为 false 后依然只展示前 50 条匹配结果

### ISSUE THREAD

**Issue by dongbanban** [ant-design/ant-design#51248]
<img width="852" alt="企业微信截图_8b977691-cb20-43f4-9041-690684b5e9a4" src="https://github.com/user-attachments/assets/f9151473-9e01-444f-9844-c9a11bbfbcf3">
<img width="758" alt="企业微信截图_e7c39267-094d-4627-a482-96c84326f488" src="https://github.com/user-attachments/assets/f4f29e74-28b7-4294-92eb-d685305a3164">
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-7fohdv?file=demo.js,package.json)

### Steps to reproduce

直接搜索 Asia(bug出在limit=false进入<=0的判断，然后被 delete之后再取出来因为此时 limit = undefined 又被赋予了 50 的 default value)

### What is expected?

返回所有 100 条 demo 数据

### What is actually happening?

只返回前 50 条

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | 18.3.1 |
| System | macos |
| Browser | chrome 129.0.6668.100 |

**Comment by thinkasany** [comment]
https://github.com/react-component/cascader/pull/541
