### ISSUE TITLE
Cascader defaultValue无效

### ISSUE THREAD

**Issue by encorehe** [ant-design/ant-design#5125]
//主页面 引用下面的组件
import { ClassProductModal} from '../../../components/pageComponents'
function ClassProductInfo ({ location, dispatch, classProductManger }) {
   const { categoryList,defaultTypeValue,item} = classProductManger;
  //级联菜单

  const loadData = (selectedOptions) => {
    const targetOption = selectedOptions[selectedOptions.length - 1];
    targetOption.loading = true;
    // load options lazily
    setTimeout(() => {
      dispatch({
        type: 'classProductManger/getCategoryList',
        payload: {
          parentId:targetOption.id,
          oldData:categoryList,
          item:item,
          defaultTypeValue:defaultTypeValue
        }
      })
      targetOption.loading = false;
    }, 600);
  };

const cSelectProp = {
    options:categoryList?categoryList:[],
    loadData:loadData,
    defaultValue:defaultTypeValue?defaultTypeValue:[]
  }

}
//组件页面 ClassProductModal
`import {Cascader,Form} from 'antd'`
cons Work = Form.create()(
   (props) => {
     
      const {cascaderSelectProp} = props;
      return(   <FormItem label='所属分类' hasFeedback {...formItemLayout}>
                 <Cascader {...cascaderSelectProp} />
               </FormItem> )
   }
);

#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

**Comment by afc163** [comment]
Please follow issue template to create issue, make sure you problem is readable and re-produible, Thanks!
