### ISSUE TITLE
[Timeline]: 数据量过大造成渲染性能问题

### ISSUE THREAD

**Issue by NickJiangDev** [ant-design/ant-design#51253]
### What problem does this feature solve?

数据如果通过动态加载，或者一次性加载过万数据，渲染比较吃力。

### What does the proposed API look like?

useVirual? 
或者结合虚拟滚动库处理

**Comment by MadCcc** [comment]
给个复现看看

**Comment by zombieJ** [comment]
你是什么场景需要给 Timeline 做这么多节点？

**Comment by NickJiangDev** [comment]
@zombieJ @MadCcc @Wxh16144 
我们使用时间轴表示一个完整的数据采集流程，节点为在流程中的一个任务或者一个事件，在涉及到表单采集和填报的流程中，可能会有上千人同时完成采集工作(提交/审核/驳回/下发/等等)，也就意味着至少会产生上千个节点，我用图片举个例子，但并不是一个强需求。
![image](https://github.com/user-attachments/assets/d6e6388b-afc7-4f12-99b5-3b1548aaf062)
