### ISSUE TITLE
Form.List删除列表数据异常

### ISSUE THREAD

**Issue by xushuaiABC** [ant-design/ant-design#51250]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9?file=%2Findex.tsx%3A12%2C53)

### Steps to reproduce

我在项目中想使用antdForm的Form.List对一组数据进行增删操作，奇怪的是，我是用一类封装是正常的，另一类是异常的（每次都删除最后一个元素，比如有三个元素，我点击第一个的删除，并传了index为0，但是会删除第三个）
<Form.Item label={<Label>回复答案</Label>} name="answerTypes">
              <Form.List name="answerTypes">
                {(answerTypes, { add, remove }) => (
                  <>
                    {answerTypes.length < 10 && (
                      <AddListItem onClick={() => add()}>
                        <CreateIcon />
                        添加答案
                      </AddListItem>
                    )}
                    {answerTypes.map((answerType, index) => (
                      <Form.Item {...answerType} key={index}>
                        <AnswerCard
                          onRemove={() => {
                            console.log('index', index);// index打印正常
                            remove(index);// 但是删除不正常
                          }}
                        />
                      </Form.Item>
                    ))}
                  </>
                )}
              </Form.List>
            </Form.Item>

### What is expected?

正确删除

### What is actually happening?

删除总是从最后一个进行

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18.2.0 |
| System | 不懂 |
| Browser | Chrome |

**Comment by flycreate** [comment]
我也是遇到一样的问题，经过排查发现，是Form.list中的带有name属性的Form.item中包裹了多个子元素导致删除操作异常如会清空后面表单项的值等![错误代码截图](https://github.com/user-attachments/assets/e67ae018-62ab-4f46-ba4a-e86abec4a0ad) 可能跟官网中有一段资料说明有关：
![Uploading 官网文档截图.jpg…]()

**Comment by xushuaiABC** [comment]
> 我也是遇到一样的问题，经过排查发现，是Form.list中的带有name属性的Form.item中包裹了多个子元素导致删除操作异常。如会清空后面表单项的值等![错误代码截图](https://private-user-images.githubusercontent.com/56260484/379284890-e67ae018-62ab-4f46-ba4a-e86abec4a0ad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzMyMjMsIm5iZiI6MTczMDg3MjkyMywicGF0aCI6Ii81NjI2MDQ4NC8zNzkyODQ4OTAtZTY3YWUwMTgtNjJhYi00ZjQ2LWJhNGEtZTg2YWJlYzRhMGFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA2MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZDc3MjFmZGZiM2Y2ZjE5M2RlOWFkNzE1ODBlODU4MDQ2OTM0ZGM4ZjhjNjNhNmE0ZDdlNmFkMTQ4NzU4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZL7bT4VPej6BHRPSzTve4kDm_s-2EilPe8spiylE26Q) 可能跟官网中有一段资料说明有关： ![官网文档截图](https://private-user-images.githubusercontent.com/56260484/379289285-f819fecb-b1e8-437f-a33f-232584ff66f6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzMyMjMsIm5iZiI6MTczMDg3MjkyMywicGF0aCI6Ii81NjI2MDQ4NC8zNzkyODkyODUtZjgxOWZlY2ItYjFlOC00MzdmLWEzM2YtMjMyNTg0ZmY2NmY2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA2MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYTFlYjAwNDA1MDI3MmQ1NmEyNTUzNWIyM2UwYmM1MWEyYjcwYmFjODI1NGI2OWZkYzU0MmQxODMxNDdmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E5CAiXXvN03jSUOk-zzZBEwcu9qjmjYaMVFp4fsTvV4)

非常感谢回答，我会在有空的时候尝试修改并反馈结果~~
