### ISSUE TITLE
Splitter panel changes size after page load

### ISSUE THREAD

**Issue by matisszemturis** [ant-design/ant-design#51268]
### Reproduction link

[https://ant.design/components/splitter](https://ant.design/components/splitter)

https://github.com/user-attachments/assets/03eeb93d-0636-4fb1-a128-37dbe4b63003

### Steps to reproduce

1. Open https://ant.design/components/splitter
2. First panel initially is as wide as "First"
3. After a second or two panels jump and both take 50/50 width

### What is expected?

When both panels have width provided, they should not be jumping/changin width after page loads.

### What is actually happening?

Initially panel width is not set, only after a second or two.

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

**Comment by shulkme** [comment]
在组件首次加载时，面板内容会出现布局抖动

**Comment by wanpan11** [comment]
Antd's official website uses SSR, and the element size cannot be obtained during server-side rendering, so it cannot be calculated immediately.
