### ISSUE TITLE
Select options 用法怎么增加自定义渲染

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51261]
### What problem does this feature solve?

选中后也用红色展示

![image](https://github.com/user-attachments/assets/fb644671-dccd-47b4-aa2b-dfe2e2b3d8ed)

https://stackblitz.com/edit/kjikge?file=demo.tsx

### What does the proposed API look like?

无需新增 API

**Comment by zombieJ** [comment]
那直接 label 包 span 为红色不就得了？~

**Comment by crazyair** [comment]
> 那直接 label 包 span 为红色不就得了？~

可以，刚才设置 style 竟然发现只能下拉用。。。

**Comment by linxianxi** [comment]
laberRender
