### ISSUE TITLE
Tooltip is visible when render function returns undefined.

### ISSUE THREAD

**Issue by AsaoOoo0o0o** [ant-design/ant-design#51275]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/32vgvz)

### Steps to reproduce

Hover the second text，it show a empty tooltip.

### What is expected?

Tooltip is invisible when render function returns invalid value.

### What is actually happening?

Tooltip is visible when render function returns undefined.

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | react |
| System | MacOS 14.1 |
| Browser | Chrome 129.0.6668.91 |

**Comment by AsaoOoo0o0o** [comment]
> It should be expected.

But when the title value is undefined, the tooltip is not displayed. These two logics together look a bit strange.

**Comment by zombieJ** [comment]
Thanks for feedback.

When using renderFunc, whether it is empty cannot be detected in advance. Tooltip will leave the rendering to the developer **for performance consideration**.
