### ISSUE TITLE
Multiple datepicker onChange trigger on value change and not just onOpenChange(false)

### ISSUE THREAD

**Issue by vutpov** [ant-design/ant-design#51283]
### What problem does this feature solve?

I'm trying to make it easier for user to select multiple date by adding an input to allow user to select the same date but on different months incrementally from the first selected date. I see that the input would not get the latest value and DatePicker's onChange does not fire unless I trigger onOpen(false). Here's the reproduction https://codesandbox.io/p/sandbox/tvtjsm

### What does the proposed API look like?

```
<DatePicker multiple fresh/>
```

**Comment by MadCcc** [comment]
`onCalendarChange`?
