### ISSUE TITLE
Cascader component in smoke test

### ISSUE THREAD

**Issue by haydonduan** [ant-design/ant-design#5128]
#### Environment(required)

- antd version: 2.7.4
- OS and its version: mac
- Browser and its version: firefox

#### What did you do? Please provide steps to re-produce your problem.

Our project has smoke test and we use **watir (a framework by selenium)**.
We use the 'Cascader', and trigger event is **'hover'**, but it not work when watir access the 'Cascader'. and use the jQuery <pre>$(".xxxx").click() </pre> or <pre> $(".xxxx").hover()</pre> not works, too!
But modify the 'hover' to 'click', it works!

#### What do you expected?
We want use trigger event **'hide'** in **Cascader**

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/1088#issuecomment-279336644
