### ISSUE TITLE
分割面板

### ISSUE THREAD

**Issue by LarycX** [ant-design/ant-design#51281]
### Reproduction link

[https://ant-design.antgroup.com/components/splitter-cn](https://ant-design.antgroup.com/components/splitter-cn)

### Steps to reproduce

任意配置其中一个Splitter.Panel的max或者min，或者都配置，并且开启可折叠。比如配置三个Panel，max分别为25%,100%,25%，然后任意折叠最左边或者最右边的Panel，再展开，就会发现Panel只展开了max的一半，即12.5%。

### What is expected?

折叠前宽度为多少，展开后宽度就为多少，或者为defaultSize或者max。

### What is actually happening?

展开后，宽度少了一半

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.2.0 |
| System | macOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
merge into #51152
