### ISSUE TITLE
edge 浏览器输入框选中历史记录，会出发其他下拉框展开下拉

### ISSUE THREAD

**Issue by yusongh** [ant-design/ant-design#51292]
### Reproduction link

[https://ant-design.antgroup.com/components/form-cn#form-demo-register](https://ant-design.antgroup.com/components/form-cn#form-demo-register)

### Steps to reproduce

官方例子就可重现

<img width="700" alt="image" src="https://github.com/user-attachments/assets/274326f0-a615-463b-9674-e8c0c7384bbd">
<img width="779" alt="image" src="https://github.com/user-attachments/assets/960ff366-4bf4-4248-9683-88926c643116">

### What is expected?

选中浏览器的历史记录，不自动展开下拉框

### What is actually happening?

选中浏览器的历史记录，自动展开下拉框了

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React |  react |
| System | mac |
| Browser | edge |

**Comment by MadCcc** [comment]
给个录屏看看

**Comment by yusongh** [comment]
> 给个录屏看看


https://github.com/user-attachments/assets/91575d97-333b-4b8d-8d86-cb9cfe24f118

**Comment by LiuYnag** [comment]
有啥临时解决办法么？遇到同样问题

**Comment by yusongh** [comment]
> 有啥临时解决办法么？遇到同样问题

我这边把浏览器历史记录给禁用了来暂时避免这个问题

**Comment by Yxuechun** [comment]
请问如何解决的？
