### ISSUE TITLE
ant-table's width will be larger infinitely if it has scroll y props and it's parent node not set width

### ISSUE THREAD

**Issue by aoiu** [ant-design/ant-design#51300]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-antd-5-21-4-forked-k4v4wz)

### Steps to reproduce

1. set a Table with props `scroll={{ y: 600 }}` (any y value)
2. set the table's grandparent node with `display: flex`
3. set the table's dataSource to `[]`

### What is expected?

don't change the table's width

### What is actually happening?

the width is being larger and larger

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | 18 |
| System | windows 11 |
| Browser | chrome |

---
![demo4](https://github.com/user-attachments/assets/75d5ef99-18e6-4527-9f92-2c00219c59ae)

set the parent node with `width: 100%` will solve this problem

**Comment by zombieJ** [comment]
`flex` layout will try to take as much as possible. Set `minWidth: 0` will make as not extenable:

```css
  .wrap {
    min-wdith: 0;
  }
```
