### ISSUE TITLE
Typing error: Property 'ref' incompatibility when assigning SegmentedProps variable to the `Segmented` component

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#51305]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-xkdgya?file=src%2FMySegmented.tsx)

### Steps to reproduce

- Declare a variable of type SegmentedProps and initialize it as desired;
- Spread this variable to the Segmented component.

### What is expected?

No errors.

### What is actually happening?

The following error is returned:

```
Type '{ options: (ViewMode | SegmentedLabeledOption<ViewMode>)[]; list?: string | undefined; size?: SizeType; defaultValue?: ViewMode | undefined; ... 362 more ...; block?: boolean | undefined; }' is not assignable to type 'RefAttributes<HTMLDivElement>'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<HTMLDivElement> | undefined' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
      Type 'string' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
```

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
Could you try antd@5.21.4 ?

**Comment by nikzanda** [comment]
> Could you try antd@5.21.4 ?

I have the same error even with antd@5.21.4. Actually, the problem seems to be due to React version 18.2.0; indeed, updating to React ^18.3.1 makes the typing error disappear. Can this error be resolved with version 18.2.0, or is updating React the only solution?

**Comment by nikzanda** [comment]
> Could you try antd@5.21.4 ?

I have the same error even with antd@5.21.4.

**Comment by afc163** [comment]
It works in here: https://stackblitz.com/edit/react-wsdg1s?file=demo.tsx,index.tsx

**Comment by afc163** [comment]
You could try latest version of `@types/react` and `@types/react-dom` too.

**Comment by nikzanda** [comment]
ok, after updating `@types/react` and `@types/react-dom` I don't have the reported error anymore, thanks!
