### ISSUE TITLE
Webpack css loading

### ISSUE THREAD

**Issue by GuillaumeCisco** [ant-design/ant-design#5132]
#### Environment(required)

- antd version: 2.7.4
- OS and its version: Xubuntu 16.04
- Browser and its version: Chromium 55.0.2883.87

#### What did you do? Please provide steps to re-produce your problem.

Just importing a antd component.
Using babel-plugin-import 1.1.1 with:
```
                        ["import", {
                            "libraryName": "antd",
                            style: 'css'
                        }]
```
I use webpack 2 with a css loader as:
```
test: /\.s?css$/,
        exclude: /node_modules/,
        loaders: ["style-loader", "css-loader?sourceMap", "postcss-loader", "sass-loader?sourceMap&sourceComments"]
```

If I don't include `style: 'css'` in babel import, webpack compiles, but ant styles are not loaded in my web application.

#### What do you expected?

Webpack compile with no problem. Styles are loaded

#### What happen?

```
ERROR in ./~/antd/lib/button/style/index.css
Module parse failed: /home/guillaume/Projects/bender-front-new/node_modules/antd/lib/button/style/index.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

**Comment by GuillaumeCisco** [comment]
I succeeded to make it works with this configuration:
```
["import", {
                            "libraryName": "antd",
                            style: true
                        }]
```

Installing less-loader and less

Then adding the rule:
```javascript
{
        test: /\.less$/,
        use: ["style-loader", {loader: 'css-loader', options: {sourceMap: 1}}, "postcss-loader", "less-loader"]
    }
```

Is another way without having to install less is possible?
Thank you

**Comment by NE-SmallTown** [comment]
If you solve a issue,you can put your answer as a comment, and then you should close the issue,thanks.

**Comment by GuillaumeCisco** [comment]
@NE-SmallTown, it is not solved...

**Comment by benjycui** [comment]
Maybe a re-producible repo is better.

**Comment by afc163** [comment]
@GuillaumeCisco

**Comment by afc163** [comment]
close for no response

**Comment by GuillaumeCisco** [comment]
Hello, sorry for late response.
I was very busy at work these last days.
I've just took time to create a repository.
I've tried to remove a lot of boilerplate I use in my projects, you can test it:
https://github.com/GuillaumeCisco/antd-less-compil

For making the compilation work, juste uncomment the commented lines in the rules.js file :+1: https://github.com/GuillaumeCisco/antd-less-compil/blob/master/webpack/rules.js#L42

Please reopen the issue @afc163 

Thank you,

**Comment by afc163** [comment]
You excluded `node_modules` in css-loader.

**Comment by GuillaumeCisco** [comment]
@afc163 What if we wnat to exclude `node_modules` for other reasons?

**Comment by GuillaumeCisco** [comment]
The correct way for excluding `node_module` for scss file and including antd less files was to add:
```
        {
            test: /antd.*\.less$/,
            ...(PRODUCTION ? {
                    use: ExtractTextPlugin.extract({
                        fallback: 'style-loader',
                        use: ['css-loader?importLoaders=1', 'postcss-loader', 'less-loader']
                    })
                } : {use: ["style-loader", {loader: 'css-loader', options: {sourceMap: 1}}, "postcss-loader", "less-loader"]} )
        },
```

**Comment by afc163** [comment]
Just don't exclude `node_modules/antd`.

**Comment by GuillaumeCisco** [comment]
lol...
Sometimes you need to, for making things to work.

**Comment by efishocean** [comment]
`{
			test: /\.css$/,
			exclude:/node_modules/^(?!antd)/,
			loader:"style-loader!css-loader!postcss-loader"
		}`
this config works for me to load css from antd

**Comment by lxm7** [comment]
This issue is resolved when i remove part of the recommended babelrc config for ant-design

Before:

```
"plugins": [
        ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css"}]
 ]
```

After:

```
"plugins": [
        ["import", { "libraryName": "antd"}]
]
```

**Comment by guoxiangwen** [comment]
@afc163 Just don't exclude node_modules/antd.

But。how can i use css module in my own .less and  no use in antd.less

**Comment by davidfurlong** [comment]
> But。how can i use css module in my own .less and no use in antd.less

you can use `test` and `exclude` to match exactly the `less` files you need

```
 test: /\.less$/,
exclude: /antd.*\.less$/,
```

**Comment by drawlix** [comment]
out of my view is this the easiest way is to announce the andt packages in Webpack. After the announcing you can use  your normal  
   ```
 entry: [

    'webpack-hot-middleware/client?reload=true',

    path.resolve(__dirname, './node_modules/antd/dist/antd.js'),

    path.resolve(__dirname, './node_modules/antd/dist/antd.less'),

```
