### ISSUE TITLE
Table Column custom `render` function has "text" parameter always as `any` 

### ISSUE THREAD

**Issue by janarvaezkng** [ant-design/ant-design#51329]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-ellipsis-forked-ntpsw2)

### Steps to reproduce

- Create a table with a typed dataSource
- Define the columns prop with a custom `render` function and a `dataIndex` prop
- Try to get the correct type for the first param in the render function

### What is expected?

The first param in the `render` function should be typed to the dataSource type, indexed by the dataIndex.

### What is actually happening?

The first param in the `render` function is aways `any`

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | react 18 |
| System | macos |
| Browser | chrome |

**Comment by MadCcc** [comment]
This type infer caused performance issue when built with typescript, so we keep it as `any`.
