### ISSUE TITLE
TreeData 设置 fieldNames.value 后，搜索功能失效

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51336]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-lj6npy?file=demo.tsx)

### Steps to reproduce

查看 demo

### What is expected?

搜索功能可用

### What is actually happening?

搜索功能不可用

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
<img width="828" alt="截屏2024-10-22 15 25 30" src="https://github.com/user-attachments/assets/1d0dbafd-5593-4d70-8ca6-2666ad2522a7">

https://stackblitz.com/edit/react-lj6npy-2nxfzd?file=demo.tsx
