### ISSUE TITLE
不兼容 react@19

### ISSUE THREAD

**Issue by arvinxx** [ant-design/ant-design#51339]
### Reproduction link

[https://github.com/arvinxx/antd-next-cssvar](https://github.com/arvinxx/antd-next-cssvar)

### Steps to reproduce

```
git clone https://github.com/arvinxx/antd-next-cssvar

pnpm i / yarn i / bun i

npm run dev
```

### What is expected?

不抛错

### What is actually happening?

抛若干错误:

1. wave 不生效 

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/db16af01-e667-4be1-a8fb-209772bd3482">

2. TypeError: reactRender is not a function

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/e739a296-6537-453c-b1e0-06623401e52d">

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | 19(rc) |
| System | any |
| Browser | any |

---
next 15 已经发布正式版，测试了 react 19（rc），发现存在不兼容的问题

**Comment by arvinxx** [comment]
相关问题： #51344

**Comment by cookabc** [comment]
Basically it's caused by react components which are not updated to be compatible with React 19.

**Comment by dgtllion** [comment]
having the same issue. Any update to fix that?

**Comment by jizhi0v0** [comment]
Is there a temporary solution?

**Comment by infodusha** [comment]
@jizhi0v0 there is a patch created by @jimvandijk in https://github.com/ant-design/ant-design/issues/51344 that you could use as a temporary solution
It worked for me

**Comment by jizhi0v0** [comment]
> @jizhi0v0 there is a patch created by @jimvandijk in #51344 that you could use as a temporary solution It worked for me

Thanks a lot.I will try it!

**Comment by dgtllion** [comment]
I made it a bit closer to fix it.
Those patches are created with pnpm.

1. patches/@rc-component__trigger@2.2.5.patch
```diff
diff --git a/es/TriggerWrapper.js b/es/TriggerWrapper.js
index c5ac0ccdd132b6a56e1b5458592e47d726035211..34c01f412e1596a6accdda21e165fa4cb6971d7b 100644
--- a/es/TriggerWrapper.js
+++ b/es/TriggerWrapper.js
@@ -9,7 +9,7 @@ var TriggerWrapper = /*#__PURE__*/React.forwardRef(function (props, ref) {
   var setRef = React.useCallback(function (node) {
     fillRef(ref, getTriggerDOMNode ? getTriggerDOMNode(node) : node);
   }, [getTriggerDOMNode]);
-  var mergedRef = useComposeRef(setRef, children.ref);
+  var mergedRef = useComposeRef(setRef, children.props.ref);
   return canUseRef ? /*#__PURE__*/React.cloneElement(children, {
     ref: mergedRef
   }) : children;

```

2. patches/antd@5.22.1.patch
```diff
diff --git a/es/_util/wave/index.js b/es/_util/wave/index.js
index 5c248a0fbc0ce43f192049035b7770f488c660dd..639e38ba40e745ac47027426e836d4086bab6f20 100644
--- a/es/_util/wave/index.js
+++ b/es/_util/wave/index.js
@@ -47,7 +47,7 @@ const Wave = props => {
   if (! /*#__PURE__*/React.isValidElement(children)) {
     return children !== null && children !== void 0 ? children : null;
   }
-  const ref = supportRef(children) ? composeRef(children.ref, containerRef) : containerRef;
+  const ref = supportRef(children) ? composeRef(children.props.ref, containerRef) : containerRef;
   return cloneElement(children, {
     ref
   });
```

3. patches/rc-motion@2.9.3.patch
```diff
diff --git a/es/CSSMotion.js b/es/CSSMotion.js
index c75a0519a5c7df267819f82fbfae824de4181f70..11175005eaf3f95552bf08b0cb60ed9fbcbc3198 100644
--- a/es/CSSMotion.js
+++ b/es/CSSMotion.js
@@ -121,7 +121,7 @@ export function genCSSMotion(config) {
     // Auto inject ref if child node not have `ref` props
     if ( /*#__PURE__*/React.isValidElement(motionChildren) && supportRef(motionChildren)) {
       var _ref = motionChildren,
-        originNodeRef = _ref.ref;
+        originNodeRef = _ref.props.ref;
       if (!originNodeRef) {
         motionChildren = /*#__PURE__*/React.cloneElement(motionChildren, {
           ref: setNodeRef
```

4. rc-resize-observer@1.4.0.patch
```diff
diff --git a/es/SingleObserver/index.js b/es/SingleObserver/index.js
index bb187240080258c1c3fa097b9a80be2d3124616a..0d589e82aee4255b88145ef5814d98b3b8e30d68 100644
--- a/es/SingleObserver/index.js
+++ b/es/SingleObserver/index.js
@@ -27,7 +27,7 @@ function SingleObserver(props, ref) {
 
   // ============================= Ref ==============================
   var canRef = !isRenderProps && /*#__PURE__*/React.isValidElement(mergedChildren) && supportRef(mergedChildren);
-  var originRef = canRef ? mergedChildren.ref : null;
+  var originRef = canRef ? mergedChildren.props.ref : null;
   var mergedRef = useComposeRef(originRef, elementRef);
   var getDom = function getDom() {
     var _elementRef$current;
```

5. patches/rc-util@5.43.0.patch
```diff
diff --git a/es/React/render.js b/es/React/render.js
index 169f01b2998a21ba42fa7b7a397ee526ad2aacb4..614653fcc5beba8513f220db0563541ae63563d7 100644
--- a/es/React/render.js
+++ b/es/React/render.js
@@ -3,6 +3,7 @@ import _asyncToGenerator from "@babel/runtime/helpers/esm/asyncToGenerator";
 import _typeof from "@babel/runtime/helpers/esm/typeof";
 import _objectSpread from "@babel/runtime/helpers/esm/objectSpread2";
 import * as ReactDOM from 'react-dom';
+import { createRoot as reactDomCreateRoot } from 'react-dom/client';
 // Let compiler not to search module usage
 var fullClone = _objectSpread({}, ReactDOM);
 var version = fullClone.version,
@@ -12,7 +13,7 @@ var createRoot;
 try {
   var mainVersion = Number((version || '').split('.')[0]);
   if (mainVersion >= 18) {
-    createRoot = fullClone.createRoot;
+    createRoot = reactDomCreateRoot;
   }
 } catch (e) {
   // Do nothing;
```

**Comment by jizhi0v0** [comment]
> I made it a bit closer to fix Antd with React 19 (workaround). Those patches are created with `pnpm patch`. Patches are done for Antd and the dependent submodules of Antd.
> 
> 1. `patches/@rc-component__trigger@2.2.5.patch`
> 
> ```diff
> diff --git a/es/TriggerWrapper.js b/es/TriggerWrapper.js
> index c5ac0ccdd132b6a56e1b5458592e47d726035211..34c01f412e1596a6accdda21e165fa4cb6971d7b 100644
> --- a/es/TriggerWrapper.js
> +++ b/es/TriggerWrapper.js
> @@ -9,7 +9,7 @@ var TriggerWrapper = /*#__PURE__*/React.forwardRef(function (props, ref) {
>    var setRef = React.useCallback(function (node) {
>      fillRef(ref, getTriggerDOMNode ? getTriggerDOMNode(node) : node);
>    }, [getTriggerDOMNode]);
> -  var mergedRef = useComposeRef(setRef, children.ref);
> +  var mergedRef = useComposeRef(setRef, children.props.ref);
>    return canUseRef ? /*#__PURE__*/React.cloneElement(children, {
>      ref: mergedRef
>    }) : children;
> ```
> 
> 2. `patches/antd@5.22.1.patch`
> 
> ```diff
> diff --git a/es/_util/wave/index.js b/es/_util/wave/index.js
> index 5c248a0fbc0ce43f192049035b7770f488c660dd..639e38ba40e745ac47027426e836d4086bab6f20 100644
> --- a/es/_util/wave/index.js
> +++ b/es/_util/wave/index.js
> @@ -47,7 +47,7 @@ const Wave = props => {
>    if (! /*#__PURE__*/React.isValidElement(children)) {
>      return children !== null && children !== void 0 ? children : null;
>    }
> -  const ref = supportRef(children) ? composeRef(children.ref, containerRef) : containerRef;
> +  const ref = supportRef(children) ? composeRef(children.props.ref, containerRef) : containerRef;
>    return cloneElement(children, {
>      ref
>    });
> diff --git a/es/form/hooks/useItemRef.js b/es/form/hooks/useItemRef.js
> index 5bea27d3fb33ae0df46abd3bd770ae51126bb819..8ab2b5ccdfdcf474441edf8b83f08f4d71bf2c0d 100644
> --- a/es/form/hooks/useItemRef.js
> +++ b/es/form/hooks/useItemRef.js
> @@ -7,7 +7,7 @@ export default function useItemRef() {
>    } = React.useContext(FormContext);
>    const cacheRef = React.useRef({});
>    function getRef(name, children) {
> -    const childrenRef = children && typeof children === 'object' && children.ref;
> +    const childrenRef = children && typeof children === 'object' && typeof children.props === 'object' && children.props.ref;
>      const nameStr = name.join('_');
>      if (cacheRef.current.name !== nameStr || cacheRef.current.originRef !== childrenRef) {
>        cacheRef.current.name = nameStr;
> diff --git a/es/menu/OverrideContext.js b/es/menu/OverrideContext.js
> index fa6c0a26a8afd413fcef783df85db5e90642e59f..6d7af8c6e351f64278e2536f4d49e723a21c9232 100644
> --- a/es/menu/OverrideContext.js
> +++ b/es/menu/OverrideContext.js
> @@ -25,7 +25,7 @@ export const OverrideProvider = /*#__PURE__*/React.forwardRef((props, ref) => {
>    // restProps.validator, Not mark as deps since this is a function
>    ]);
>    const canRef = supportNodeRef(children);
> -  const mergedRef = useComposeRef(ref, canRef ? children.ref : null);
> +  const mergedRef = useComposeRef(ref, canRef ? children.props.ref : null);
>    return /*#__PURE__*/React.createElement(OverrideContext.Provider, {
>      value: context
>    }, /*#__PURE__*/React.createElement(ContextIsolator, {
> diff --git a/lib/_util/wave/index.js b/lib/_util/wave/index.js
> index 1b6f3fd33a4f3b38c06acdcb1e8d71561b1d0c7b..34e97ab129365603fb1c9d8952ce5fde88040d81 100644
> --- a/lib/_util/wave/index.js
> +++ b/lib/_util/wave/index.js
> @@ -55,7 +55,7 @@ const Wave = props => {
>    if (! /*#__PURE__*/_react.default.isValidElement(children)) {
>      return children !== null && children !== void 0 ? children : null;
>    }
> -  const ref = (0, _ref.supportRef)(children) ? (0, _ref.composeRef)(children.ref, containerRef) : containerRef;
> +  const ref = (0, _ref.supportRef)(children) ? (0, _ref.composeRef)(children.props.ref, containerRef) : containerRef;
>    return (0, _reactNode.cloneElement)(children, {
>      ref
>    });
> diff --git a/lib/form/hooks/useItemRef.js b/lib/form/hooks/useItemRef.js
> index 95a66b8337be154c300121d3e1f19f46f54451fc..3afc470222ccc28974d99dcba1f023d00754910c 100644
> --- a/lib/form/hooks/useItemRef.js
> +++ b/lib/form/hooks/useItemRef.js
> @@ -14,7 +14,7 @@ function useItemRef() {
>    } = React.useContext(_context.FormContext);
>    const cacheRef = React.useRef({});
>    function getRef(name, children) {
> -    const childrenRef = children && typeof children === 'object' && children.ref;
> +    const childrenRef = children && typeof children === 'object' && typeof children.props === 'object' && children.props.ref;
>      const nameStr = name.join('_');
>      if (cacheRef.current.name !== nameStr || cacheRef.current.originRef !== childrenRef) {
>        cacheRef.current.name = nameStr;
> ```
> 
> 3. `patches/rc-motion@2.9.3.patch`
> 
> ```diff
> diff --git a/es/CSSMotion.js b/es/CSSMotion.js
> index c75a0519a5c7df267819f82fbfae824de4181f70..11175005eaf3f95552bf08b0cb60ed9fbcbc3198 100644
> --- a/es/CSSMotion.js
> +++ b/es/CSSMotion.js
> @@ -121,7 +121,7 @@ export function genCSSMotion(config) {
>      // Auto inject ref if child node not have `ref` props
>      if ( /*#__PURE__*/React.isValidElement(motionChildren) && supportRef(motionChildren)) {
>        var _ref = motionChildren,
> -        originNodeRef = _ref.ref;
> +        originNodeRef = _ref.props.ref;
>        if (!originNodeRef) {
>          motionChildren = /*#__PURE__*/React.cloneElement(motionChildren, {
>            ref: setNodeRef
> ```
> 
> 4. `rc-resize-observer@1.4.0.patch`
> 
> ```diff
> diff --git a/es/SingleObserver/index.js b/es/SingleObserver/index.js
> index bb187240080258c1c3fa097b9a80be2d3124616a..0d589e82aee4255b88145ef5814d98b3b8e30d68 100644
> --- a/es/SingleObserver/index.js
> +++ b/es/SingleObserver/index.js
> @@ -27,7 +27,7 @@ function SingleObserver(props, ref) {
>  
>    // ============================= Ref ==============================
>    var canRef = !isRenderProps && /*#__PURE__*/React.isValidElement(mergedChildren) && supportRef(mergedChildren);
> -  var originRef = canRef ? mergedChildren.ref : null;
> +  var originRef = canRef ? mergedChildren.props.ref : null;
>    var mergedRef = useComposeRef(originRef, elementRef);
>    var getDom = function getDom() {
>      var _elementRef$current;
> ```
> 
> 5. `patches/rc-util@5.43.0.patch`
> 
> ```diff
> diff --git a/es/React/render.js b/es/React/render.js
> index 169f01b2998a21ba42fa7b7a397ee526ad2aacb4..614653fcc5beba8513f220db0563541ae63563d7 100644
> --- a/es/React/render.js
> +++ b/es/React/render.js
> @@ -3,6 +3,7 @@ import _asyncToGenerator from "@babel/runtime/helpers/esm/asyncToGenerator";
>  import _typeof from "@babel/runtime/helpers/esm/typeof";
>  import _objectSpread from "@babel/runtime/helpers/esm/objectSpread2";
>  import * as ReactDOM from 'react-dom';
> +import { createRoot as reactDomCreateRoot } from 'react-dom/client';
>  // Let compiler not to search module usage
>  var fullClone = _objectSpread({}, ReactDOM);
>  var version = fullClone.version,
> @@ -12,7 +13,7 @@ var createRoot;
>  try {
>    var mainVersion = Number((version || '').split('.')[0]);
>    if (mainVersion >= 18) {
> -    createRoot = fullClone.createRoot;
> +    createRoot = reactDomCreateRoot;
>    }
>  } catch (e) {
>    // Do nothing;
> ```
> 
> 6. `patches/rc-dropdown@4.2.0.patch`
> 
> ```diff
> diff --git a/es/Dropdown.js b/es/Dropdown.js
> index c760f1c31481d46f704bda9efef410ec16dc4cc3..db18f36c7f79a80e7be0f9f06675c756482dc585 100644
> --- a/es/Dropdown.js
> +++ b/es/Dropdown.js
> @@ -96,7 +96,7 @@ function Dropdown(props, ref) {
>    };
>    var childrenNode = /*#__PURE__*/React.cloneElement(children, {
>      className: classNames((_children$props = children.props) === null || _children$props === void 0 ? void 0 : _children$props.className, mergedVisible && getOpenClassName()),
> -    ref: supportRef(children) ? composeRef(childRef, children.ref) : undefined
> +    ref: supportRef(children) ? composeRef(childRef, children.props.ref) : undefined
>    });
>    var triggerHideAction = hideAction;
>    if (!triggerHideAction && trigger.indexOf('contextMenu') !== -1) {
> diff --git a/es/Overlay.js b/es/Overlay.js
> index 00d51a5c6d3b36d9087227cb7f80a5705f774c81..59c81db839f18f2554de6499b8963187a0fef759 100644
> --- a/es/Overlay.js
> +++ b/es/Overlay.js
> @@ -13,7 +13,7 @@ var Overlay = /*#__PURE__*/forwardRef(function (props, ref) {
>      }
>      return overlayElement;
>    }, [overlay]);
> -  var composedRef = composeRef(ref, overlayNode === null || overlayNode === void 0 ? void 0 : overlayNode.ref);
> +  var composedRef = composeRef(ref, overlayNode === null || overlayNode === void 0 ? void 0 : overlayNode.props.ref);
>    return /*#__PURE__*/React.createElement(React.Fragment, null, arrow && /*#__PURE__*/React.createElement("div", {
>      className: "".concat(prefixCls, "-arrow")
>    }), /*#__PURE__*/React.cloneElement(overlayNode, {
> diff --git a/lib/Dropdown.js b/lib/Dropdown.js
> index 54b405db5fbee70b7662e5c24d9745c1008f4e49..867c60a6f4ec82b34dcf3362a4adf56c434354c0 100644
> --- a/lib/Dropdown.js
> +++ b/lib/Dropdown.js
> @@ -103,7 +103,7 @@ function Dropdown(props, ref) {
>    };
>    var childrenNode = /*#__PURE__*/_react.default.cloneElement(children, {
>      className: (0, _classnames.default)((_children$props = children.props) === null || _children$props === void 0 ? void 0 : _children$props.className, mergedVisible && getOpenClassName()),
> -    ref: (0, _ref.supportRef)(children) ? (0, _ref.composeRef)(childRef, children.ref) : undefined
> +    ref: (0, _ref.supportRef)(children) ? (0, _ref.composeRef)(childRef, children.props.ref) : undefined
>    });
>    var triggerHideAction = hideAction;
>    if (!triggerHideAction && trigger.indexOf('contextMenu') !== -1) {
> diff --git a/lib/Overlay.js b/lib/Overlay.js
> index b753d97668a87447d6b04aefe7dfa6533bdbe2b7..558b14208c6d9c0c273847c12267025be515635f 100644
> --- a/lib/Overlay.js
> +++ b/lib/Overlay.js
> @@ -20,7 +20,7 @@ var Overlay = /*#__PURE__*/(0, _react.forwardRef)(function (props, ref) {
>      }
>      return overlayElement;
>    }, [overlay]);
> -  var composedRef = (0, _ref.composeRef)(ref, overlayNode === null || overlayNode === void 0 ? void 0 : overlayNode.ref);
> +  var composedRef = (0, _ref.composeRef)(ref, overlayNode === null || overlayNode === void 0 ? void 0 : overlayNode.props.ref);
>    return /*#__PURE__*/_react.default.createElement(_react.default.Fragment, null, arrow && /*#__PURE__*/_react.default.createElement("div", {
>      className: "".concat(prefixCls, "-arrow")
>    }), /*#__PURE__*/_react.default.cloneElement(overlayNode, {
> ```
> 
> This what i have in mine `package.json`
> 
> ```json
> {
>   "dependencies": {
>   ...
>   },
>   ...
>   "pnpm": {
>     "overrides": {
>       "@types/react": "npm:types-react@19.0.0-rc.1",
>       "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
>     },
>     "patchedDependencies": {
>       "@rc-component/trigger@2.2.5": "patches/@rc-component__trigger@2.2.5.patch",
>       "antd@5.22.1": "patches/antd@5.22.1.patch",
>       "rc-motion@2.9.3": "patches/rc-motion@2.9.3.patch",
>       "rc-resize-observer@1.4.0": "patches/rc-resize-observer@1.4.0.patch",
>       "rc-util@5.43.0": "patches/rc-util@5.43.0.patch",
>       "rc-dropdown@4.2.0": "patches/rc-dropdown@4.2.0.patch"
>     }
>   }
> }
> ```
> 
> After adding those patches to folder run `pnpm i`

Nice Work!

**Comment by li-jia-nan** [comment]
- #51919

**Comment by kirill-linnik** [comment]
any plans to actually fix it? now, with react 19 being official, it does cause me the same issue:
```
TypeError
reactRender is not a function
```

**Comment by luongductrong** [comment]
React version 19 has been officially released. We hope you will soon provide a compatible version of Ant Design

**Comment by dinfer** [comment]
可以通过禁用wave来临时避免`TypeError: reactRender is not a function`报错
You can disable wave to avoid `TypeError: reactRender is not a function` error temporarily like this

```jsx
<ConfigProvider wave={{ disabled: true }}>
  <Button>click</Button>
</ConfigProvider>
```

**Comment by arvinxx** [comment]
antd v5 已经完成 react 19 兼容，参见官方文档： https://ant.design/docs/react/v5-for-19-cn 。此 issue 可以关闭了

----

antd v5 has completed compatibility with React 19, see the official documentation: https://ant.design/docs/react/v5-for-19

**Comment by khanakia** [comment]
> antd v5 已经完成 react 19 兼容，参见官方文档： https://ant.design/docs/react/v5-for-19-cn 。此 issue 可以关闭了
> 
> antd v5 has completed compatibility with React 19, see the official documentation: https://ant.design/docs/react/v5-for-19

does not works
https://github.com/ant-design/ant-design/issues/51458#issuecomment-2571708636
