### ISSUE TITLE
[New component] Progress bar

### ISSUE THREAD

**Issue by iacopo-schianchi** [ant-design/ant-design#51357]
### What problem does this feature solve?

A new component for developers to use when displaying progress to users. Examples of uses include loading progress, a user's task progress, etc.

### What does the proposed API look like?

New component with props for `min`, `max`, `value`, `className`, `progressColor`, `backgroundColor`, `height`, `borderRadius`.

**Comment by zombieJ** [comment]
What's this look like?

**Comment by afc163** [comment]
How about https://ant.design/components/progress
