### ISSUE TITLE
[Segmented] options 使用 SegmentedItemType[] 类型时 value 类型错误

### ISSUE THREAD

**Issue by wanpan11** [ant-design/ant-design#51356]
### Reproduction link

[https://ant.design/components/segmented-cn#segmenteditemtype](https://ant.design/components/segmented-cn#segmenteditemtype)

### Steps to reproduce

无

![image](https://github.com/user-attachments/assets/26e8a94d-6dc1-4f32-9930-f24cc5ea5afd)
![image](https://github.com/user-attachments/assets/37af97b5-8d0b-4c05-ad0e-28dd34aadd29)
![image](https://github.com/user-attachments/assets/e0541f04-f28c-436b-9668-1a7ce64b9c94)

ValueType 同时赋值给了  options 和 value

### What is expected?

类型正确

### What is actually happening?

类型错误

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.3.1 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
```tsx
  <Segmented<string>
    options={[
      { value: "1", label: "111" },
      { value: "2", label: "222" },
    ]}
    value="2"
    onChange={(value) => {
      console.log(value); // string
    }}
  />
```

**Comment by wanpan11** [comment]
我的 我的 我没给 SegmentedProps传类型 😶‍🌫️

![image](https://github.com/user-attachments/assets/7eaa76dc-84c0-4063-a298-9eb6dc2f6c69)
