### ISSUE TITLE
[BUG]RangePicker中的disabledDate缺少info参数

### ISSUE THREAD

**Issue by Mrcxt** [ant-design/ant-design#51352]
### Reproduction link

[https://ant.design/components/date-picker-cn#date-picker-demo-select-in-range](https://ant.design/components/date-picker-cn#date-picker-demo-select-in-range)

### Steps to reproduce

最新版的antd（@5.21.5）中的RangePicker，disabledDate的info参数为undefined。但是ts类型中提示info: {
    type: PanelMode;
    from?: dayjs.Dayjs | undefined;
}。降级到5.17.0版本后，info参数可以获取到。
<img width="546" alt="image" src="https://github.com/user-attachments/assets/c210b5b9-2365-43c7-8fec-cfe348ee98c5">

### What is expected?

disabledDate可以获取到info参数

### What is actually happening?

disabledDate的info参数为undefined

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | 18 |
| System | mac |
| Browser | Chrome |

**Comment by MadCcc** [comment]
给个复现吧，官网貌似不能重现你说的问题
