### ISSUE TITLE
form控件的label为什么没有title属性

### ISSUE THREAD

**Issue by 957236298** [ant-design/ant-design#5136]
这是官网例子里面的结构，有title。
![image](https://cloud.githubusercontent.com/assets/23330717/23491119/3e9086a4-ff37-11e6-956b-df889f2f3a6f.png)

这个是我自己写的结构，里面没有title。
![image](https://cloud.githubusercontent.com/assets/23330717/23491138/5f2650ce-ff37-11e6-95bd-5d191e1eb349.png)

而且我在api中也并没有发现有关这个title的配置的地方，这是为什么呢？

**Comment by yesmeck** [comment]
Check your antd version.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/511db23fcda74b10183fef484872a886eb380d86

**Comment by 957236298** [comment]
@yesmeck  Which version should I  upgrade to at least

**Comment by yesmeck** [comment]
2.7.4

**Comment by afc163** [comment]
Always latest version. 😃

**Comment by 957236298** [comment]
ok,I've solved it. thank you~~  @yesmeck @afc163
