### ISSUE TITLE
[Menu] 导航菜单中，菜单项标题 label 中，Flex 布局设置的属性失效

### ISSUE THREAD

**Issue by ninekirin** [ant-design/ant-design#51361]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-43xydr)

### Steps to reproduce

1. 打开 CodeSandbox 链接。
2. 在侧边栏中查看菜单项的布局。
3. 注意菜单项 `label` 中的 `justifyContent: 'space-between'` 属性无法正常工作，导致右侧的下拉按钮与左侧的文本没有正确对齐。

若想查看预期效果，请参考使用 antd 版本 5.20.6 的 [CodeSandbox 链接](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jzyy3m)。

### What is expected?

`justifyContent: 'space-between'` 应该使 `label` 中的元素（文本和下拉按钮）在左右两边对齐。

### What is actually happening?

`justifyContent: 'space-between'` 属性失效，导致文本和下拉按钮没有正确对齐，按钮紧靠文本显示。

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 18.3.1 |
| System | macOS 15.0.1 |
| Browser |  Google Chrome 129.0.6668.101 (arm64) |

---
使用 Ant Design 5.20.6 版本时，布局是正常的。升级到 5.21.x 后，问题开始出现，`label` 中的 Flex 布局属性没有正确应用。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/50431 引入的，@coding-ice 帮忙看看？

**Comment by coding-ice** [comment]
跟我这里描述的是同一个问题：https://github.com/ant-design/ant-design/pull/50794#issuecomment-2342518226
变为 flex 导致的 ：`.ant-menu-title-content: inline-flex`
