### ISSUE TITLE
formRef.current.setFieldValue 的name参数 在FormValue类型是不确定字段时 会推导错误

### ISSUE THREAD

**Issue by DrMuda** [ant-design/ant-design#51376]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/x2ps6f)

### Steps to reproduce

直接打开复现链接就能看到setFieldValue那里的name参数TS报错

### What is expected?

能正确推导出 [string, number, string] 类型

### What is actually happening?

类型不准确

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | 18.2.0 |
| System | 无关 |
| Browser | 无关 |

---
typescript：5.5.4

业务场景： 我项目的表单是通过接口获取数据动态生成的， 这个时候表单的字段名是不确定的， 值的类型是类似SomeType这样的其中几种， 在这种情况下 setFieldValue 没办法把数组类型推导出来

**Comment by zombieJ** [comment]
是不是mei没有开共享？

<img width="718" alt="截屏2024-10-25 16 42 00" src="https://github.com/user-attachments/assets/5505c219-9b3f-403e-b80d-d7a710fd9022">

**Comment by DrMuda** [comment]
> 是不是mei没有开共享？
> 
> <img alt="截屏2024-10-25 16 42 00" width="718" src="https://private-user-images.githubusercontent.com/5378891/380081974-5505c219-9b3f-403e-b80d-d7a710fd9022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDYxMTQsIm5iZiI6MTcyOTg0NTgxNCwicGF0aCI6Ii81Mzc4ODkxLzM4MDA4MTk3NC01NTA1YzIxOS05YjNmLTQwM2UtYjgwZC1kN2E3MTBmZDkwMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMDg0MzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE5Zjc1NDRkYzE3MDVkYmQzOWJlZjVjNDYyNDY1MGZhYzUzMzBiNjA5MDM1MDlkOGU3OGZjMTI5YTYyYTBhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vh2FcJra9_4fe5uzRYvXjx7VtgqmZIU5Jt1z5tSHwlg">

抱歉， 忘了改，现在公开了

**Comment by MadCcc** [comment]
TS 推导能力有限，这个我们不太好做优化。有兴趣可以来 PR 试试
