### ISSUE TITLE
antd5Tooltip内容较窄时样式异常

### ISSUE THREAD

**Issue by AliceXu521** [ant-design/ant-design#51373]
### Reproduction link

[https://codepen.io/pen?&editors=001](https://codepen.io/pen?&editors=001)

### Steps to reproduce

修改<Tooltip/>的title为"p"或其他较窄的内容，设置placement为"bottomLeft"或"topLeft"，会出现偏移的样式异常

### What is expected?

样式正常

### What is actually happening?

箭头异常
能上传图片不？好像不能，那就麻烦去复现下吧

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | chrome Version 130.0.6723.70 (Official Build) (64-bit)和edge 版本 130.0.2849.52 (正式版本) (64 位) |

---
使用Table渲染表格数据，第一列的内容需要悬浮显示全部数据

**Comment by MadCcc** [comment]
![image](https://github.com/user-attachments/assets/61c8ddc7-7532-4365-bed1-08e069378e6f)
确实有问题

**Comment by AliceXu521** [comment]
> 内容过小箭头确实会移位，本质上就是内容太少了，撑不起来。有几个解决方案
> 
> 1. 内容过少时，不用 Tootips。
> 2. 通过 `overlayInnerStyle` 设置一个内边距或者最小宽度。
> 3. 通过 `arrow={false}` 关闭箭头。
> 
> <img alt="image" width="631" src="https://private-user-images.githubusercontent.com/32004925/380011408-2da3a95c-bf69-4607-b851-1c861da3fb3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDc2MzMsIm5iZiI6MTczMDQ0NzMzMywicGF0aCI6Ii8zMjAwNDkyNS8zODAwMTE0MDgtMmRhM2E5NWMtYmY2OS00NjA3LWI4NTEtMWM4NjFkYTNmYjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA3NDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZWJhMGIwOTdlMGJkZWY2ZDFhNzRjM2QyNWU3MTFmMDA1OTRkMDIyZTI4YTI1MDhiZTI4YTlhM2IwNjc1NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IUElMJtu5SoQxrDSCnlXHD7GqSgoeWBx62OiFx0jdoA">

谢谢回答

**Comment by lqzhgood** [comment]
那么修复方式应该采用什么？

**Comment by zombieJ** [comment]
> 那么修复方式应该采用什么？

设置 offset 让其在较少的时候强行偏移，对于过小的内容还是会有拼接问题：

<img width="270" alt="截屏2024-12-05 11 31 16" src="https://github.com/user-attachments/assets/3ab2232c-b9e0-42bb-9e3e-98dbbcf8c7e4">

如果 token 中设置纯圆 `2.5em` 也不对：

<img width="327" alt="截屏2024-12-05 11 34 52" src="https://github.com/user-attachments/assets/443052c9-a43d-4fd7-849f-7e60cfff1d93">

不过 minWidth 的确是个思路，感觉可以把 arrow 的宽度 + border radius 的宽度，这样就一定在里面了。
