### ISSUE TITLE
Popover component default mouseover trigger event doesn't work well on mobile device.

### ISSUE THREAD

**Issue by simengli** [ant-design/ant-design#5137]
#### Environment(required)

- antd version: latest
- OS and its version: iphone6s. IOS10
- Browser and its version: safari

#### What did you do? Please provide steps to re-produce your problem.
Using popover component's default settings (show popovers on mouse over).
On mobile device, click on the trigger button, popover shows up. 

#### What do you expect?
Popover close properly on mobile.
It doesn't work on official website as well. 

#### What happen?
On mobile device, not able to close the popovers properly by click on any open area on the page. 
This is necessary for a responsive design project.  I need the hover over behavior works find on both desktop and mobile at a same time. 
#### Re-producible online demo
Antd Site, popover component page.

**Comment by benjycui** [comment]
I think we can remove [this line](https://github.com/react-component/trigger/blob/da5bbc29706ecfeab88be84769f288cd726014f5/src/Trigger.jsx#L153).

No matter which trigger we are using, just close the overlay when we click outside it.

**Comment by afc163** [comment]
Agree with @benjycui.

**Comment by afc163** [comment]
Reinstall node_modules.
