### ISSUE TITLE
AutoComplete can't alignment in the Form.Item

### ISSUE THREAD

**Issue by kangpoves** [ant-design/ant-design#5139]
#### Environment(required)

- antd version: 2.7.4
- OS and its version: window10
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
I have updated antdesign to 2.7.4 version, Find a problem with existing page.

Form inline and AutoComplete propertie ‘size=small’  in Form.Item cannot align with label

There is no problem before updating.

I find a css properties ‘display:inline-block’ in the class children, I tried to delete it in the browser debugger,Its style is back to normal. 

Finally  I solved the problem and set a property   ‘style={{display: 'inherit'}} ‘    in AutoComplete, But I hope the AntDesign can solve the problem.

**Comment by kangpoves** [comment]
` <FormItem label={` name:`}>
            {getFieldDecorator('password', {
              rules: [{ required: true, message: 'Please input your Password!' }],
            })(
                <AutoComplete
                    size="small"
                    dataSource={dataSource}
                    onSelect={onSelect}
                    onChange={this.handleChange}
                    placeholder="input here"
                />
            )}
          </FormItem>`

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
