### ISSUE TITLE
ThemeConfig配置token无法使用写在root的变量

### ISSUE THREAD

**Issue by Lomnus** [ant-design/ant-design#51391]
### Reproduction link

https://codesandbox.io/p/sandbox/an-niu-tu-biao-wei-zhi-antd-5-21-5-forked-v35jzk?workspaceId=3ba78f26-883e-4907-8ed2-cf15d914a83c

### Steps to reproduce

 ```
token: {
    colorPrimary: "var(--test-primary-color)",
    controlOutline: "var(--test-primary-color)"
  },
```

### What is expected?

可以使用root变量

### What is actually happening?

不起效果

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | 18.3.1 |
| System | win11 |
| Browser | Chrome |

**Comment by wanpan11** [comment]
未公开

![image](https://github.com/user-attachments/assets/4a87f0ab-8183-4303-944b-8ef757fed63a)

**Comment by Lomnus** [comment]
> 未公开
> 
> ![image](https://private-user-images.githubusercontent.com/38714194/380549195-4a87f0ab-8183-4303-944b-8ef757fed63a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODg0MDMsIm5iZiI6MTczMDA4ODEwMywicGF0aCI6Ii8zODcxNDE5NC8zODA1NDkxOTUtNGE4N2YwYWItODE4My00MzAzLTk0NGItOGVmNzU3ZmVkNjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA0MDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZDBjOGMzZmNkMjg4MTg3NzFjYzEwZGE5OTI5OThiMTk2ZDJkYTZmMGYwNzhlZmVkM2M5ZDYxZTYyYzgxYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OhgYVXHBsXBsAKF6bMIRGXOaoPStHF-jVmbiXRSSs-E)

https://codesandbox.io/p/sandbox/an-niu-tu-biao-wei-zhi-antd-5-21-5-forked-v35jzk?workspaceId=3ba78f26-883e-4907-8ed2-cf15d914a83c

**Comment by Lomnus** [comment]
@wanpan11

**Comment by wanpan11** [comment]
cssVar 只能用于 ComponentToken 

![image](https://github.com/user-attachments/assets/674d2d6e-0bfd-4be7-abf1-71d4be926409)

**Comment by wanpan11** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/49041
