### ISSUE TITLE
Notification 增加onChange

### ISSUE THREAD

**Issue by GeorgeHcc** [ant-design/ant-design#51398]
### What problem does this feature solve?

某些场景，需要拿到消息队列中的显示的消息

### What does the proposed API look like?

 const [api, contextHolder] = notification.useNotification({
...,
onChange(notifications:T[]){
//do something
}
});

**Comment by afc163** [comment]
onChange 表示什么意思？

**Comment by crazyair** [comment]
没见过钩子加 cb 的

**Comment by yoyo837** [comment]
没见过钩子加 cb 的

**Comment by CCherry07** [comment]
> 没见过钩子加 cb 的

React sensor hook that fires a callback when user starts typing. Can be used to focus default input field on the page.

@yoyo837 @crazyair 
这种case还是有很多的
[useStartTyping](https://streamich.github.io/react-use/?path=/story/sensors-usestarttyping--docs)

```ts
import {useStartTyping} from 'react-use';

const Demo = () => {
  useStartTyping(() => alert('Started typing...'));

  return null;
};
```
