### ISSUE TITLE
实现表格列宽根据内容自适应

### ISSUE THREAD

**Issue by chim-hong** [ant-design/ant-design#51397]
### What problem does this feature solve?

当表格的列头有很多项时，需要展示表格的完整内容。但是目前我看到的解决办法都是直接动态计算列宽，是否有办法实现自动计算列头内容跟表格内容，取其最大值。这样不需要手动计算最大值是多少。另外，我在测试的时候大概实现了这个功能，即column中指定width为auto，scroll中指定x为true或者max-content，能实现自动计算列头内容跟表格内容的宽度并取其最大值，但是当指定了scroll的y之后就只会取表格内容的最大值，不知道应该如何解决？

### What does the proposed API look like?

Table的scroll以及columnAPI

**Comment by afc163** [comment]
看上去和 https://github.com/ant-design/ant-design/issues/51394 是一个问题。

**Comment by chim-hong** [comment]
> 看上去和 #51394 是一个问题。

看样子大体一样 可能有些微差别 我会关注该issue  感谢
