### ISSUE TITLE
mixins 使用 es6要怎么用?

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#514]
目前好像还不支持 mixins, 如果使用 es6写的组件, ant 的 mixin 要怎么配合使用,谢谢.

**Comment by afc163** [comment]
https://facebook.github.io/react/docs/reusable-components.html#no-mixins

**Comment by bang88** [comment]
那意思是如果我们在 es6 里面用 ant 的话,那些 mixins 就要自己处理?
