### ISSUE TITLE
theme.useToken() 內的 Dropdown 找不到 colorBgElevated 參數

### ISSUE THREAD

**Issue by RexHung0302** [ant-design/ant-design#51408]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9)

因為這個是 TS 定義問題，就沒有特別在 clone 一個出來

### Steps to reproduce

只要使用 `theme.useToken()`，然後把 Dropdown console.log 出來，就會發現裡面至少有五個屬性
```
colorBgElevated
colorText
colorTextDescription
controlItemBgHover
zIndexPopup
```

但是 typescript 裡面 DropdownComponentToken 只有定義兩個屬性 `zIndexPopup` 及 `paddingBlock`

### What is expected?

能夠正常從 `theme.useToken()` 裡面透過 Dropdown 拿取 colorBgElevated 參數

### What is actually happening?

拿不到 colorBgElevated 參數

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.2.0 |
| System | macOS Sequoia 15.0.1 |
| Browser | Chrome 129.0.6668.90 |

**Comment by MadCcc** [comment]
如果说的是 useToken 里取 Dropdown 的 token 的话，那我们是不期望这样使用的，应该是 merge 对象时带进去了
