### ISSUE TITLE
Table Summary 为什么不做成 items 形式

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51401]
### What problem does this feature solve?

统一数组形式，目前是组件形式
![image](https://github.com/user-attachments/assets/17bf6ce6-eddf-4183-93ae-79040869382e)

### What does the proposed API look like?

```tsx
<Table.Summary items={[{label: 'demo'}]}/>
```

**Comment by zombieJ** [comment]
靠近元素结构的用 jsx，靠近数据结构的用 data。主要就看使用中是否会把 `children` 转成 `data` 而舍弃其 jsx 结构。Summary 这个是纯拼搭出 dom 结构哈~
