### ISSUE TITLE
v5.21.6 更新后 TreeSelect 下拉内容有遮挡

### ISSUE THREAD

**Issue by october-rain** [ant-design/ant-design#51415]
### Reproduction link

[https://ant.design/~demos/tree-select-demo-basic](https://ant.design/~demos/tree-select-demo-basic)

### Steps to reproduce

下拉

### What is expected?

最下面的一个选项不被遮挡

### What is actually happening?

最下面的一个选项是被遮挡的
![image](https://github.com/user-attachments/assets/3808a049-0ca2-4d2e-9aa1-ec1d839cd79e)

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | react@18.3.1 |
| System | macos 14.4.1 (23E224) |
| Browser | Chrome 130.0.6723.70 (Official Build) (arm64) |

---
在我们业务内部有复现，然后发现antd demo 里也是有这个问题的，本地安装 v5.21.5 是正常了，也就是问题出现在 v5.21.6 里

**Comment by ustcfury** [comment]
working on it

**Comment by ilxqx** [comment]
确实如何，你倒是发现的挺快啊

**Comment by zyzztz** [comment]
antd:^5.3.0 也发现这个问题了，每个节点多了个下间距的样式，我找不到原因只能在全局覆盖这个样式了。
![image](https://github.com/user-attachments/assets/5eb98d0e-72fb-491c-8676-82c8b20d9d2f)

**Comment by erinz2020** [comment]
found this issue too when working on "antd": "^5.21.6"

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/51485

**Comment by chenxiaochun** [comment]
现在最新版本依然有问题

**Comment by afc163** [comment]
@chenxiaochun 有重现么？

**Comment by samllLuck** [comment]
同理，我们也出现了这个bug，在使用虚拟dom的时候，展开叶子节点，底部会有展示不全的bug

**Comment by forzalianjunting** [comment]
virtual设置为true时，依然有这个问题，版本5.26.6
