### ISSUE TITLE
(#51074)重构UploadList导致的组件内部报错 of undefined (reading 'preventDefault')  at onInternalPreview

### ISSUE THREAD

**Issue by GaoJuqian** [ant-design/ant-design#51418]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/holy-hooks-3wwl63)

### Steps to reproduce

> [refactor: refactor components/upload/UploadList/index.tsx (#51074)](https://github.com/ant-design/ant-design/pull/51074)

这次提交的重构内容，由于去掉了onInternalPreview方法的第二个参数的?:可选参数，以及e?.preventDefault();的可选调用。
影响了按照之前版本使用itemRender调用preview方法。导致了组件内部这个错误。

注：这个问题会导致很多，自定itemRender调用preview无法使用的情况。

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/5588f481-bc1b-4e03-90fb-e360ade62b2b">

### What is expected?

能够调用预览方法
```javascript
  const onInternalPreview = (file: UploadFile, e: React.SyntheticEvent<HTMLElement>) => {
    if (!onPreview) {
      return;
    }
    e.preventDefault();  // TODO  error
    return onPreview(file);
  };
```

### What is actually happening?

```javascript
Uncaught TypeError: Cannot read properties of undefined (reading 'preventDefault')
    at onInternalPreview (/node_modules/antd/es/upload/UploadList/index.js:65:7)
    at onClick (/index.tsx:92:31)
```

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | win mac |
| Browser | ^ |

---
运维内网npm包依赖更新，内部二次封装antd组件。
开发人员使用二次封装，更新后的antd导致的问题。

**Comment by yoyo837** [comment]
这个应该是外部ref使用handlePreview时没有主动传入第二个event参数

**Comment by zombieJ** [comment]
`itemRender` 里透过去的，看起来原来的使用方式的确没问题。有兴趣来个 PR 改回 optional 不？
