### ISSUE TITLE
使用Image.PreviewGroup的时候不能在Image中自定义预览渲染

### ISSUE THREAD

**Issue by fengzai6** [ant-design/ant-design#51428]
### What problem does this feature solve?

能够为每个不同的情况进行渲染预览组件

### What does the proposed API look like?

Image中的imageRender比Image.PreviewGroup中的优先级高

**Comment by fengzai6** [comment]
my repo：https://github.com/fengzai6/react-antd-image

**Comment by afc163** [comment]
来一个 codesandbox ？

**Comment by fengzai6** [comment]
> 来一个 codesandbox ？

我后面新开的issue中有，可以看看，如需补充更多还请告诉我，https://github.com/ant-design/ant-design/issues/51474#issue-2631584226

**Comment by afc163** [comment]
Duplicate of #51474
