### ISSUE TITLE
弹窗或者抽屉里用DatePicker日期选择器设置默认时间，设置以后在页面选择时间就不行了

### ISSUE THREAD

**Issue by guilin-jun** [ant-design/ant-design#51426]
### Reproduction link

[https://github.com/guilin-jun/antd-DatePicker-bug.git](https://github.com/guilin-jun/antd-DatePicker-bug.git)

### Steps to reproduce

1.点击弹窗，选择日期

### What is expected?

正常显示当前日期，点击日期下拉框能正常选择日期

### What is actually happening?

选择日期的时候，下拉框里面的时间全部都选中了，并且切换年月的时候不是挨个加减的

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.2.0 |
| System | window11 |
| Browser | Microsoft Edge 版本 130.0.2849.46 (正式版本) (64 位) |

**Comment by MadCcc** [comment]
给个代码复现，在你的 github repo 中貌似没看见相关代码

**Comment by guilin-jun** [comment]
最小化的 GitHub 仓库：guilin-jun/antd-DatePicker-bug: antd




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月30日(星期三) 下午4:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] 弹窗或者抽屉里用DatePicker日期选择器设置默认时间，设置以后在页面选择时间就不行了 (Issue #51426)














 
Hello @guilin-jun. Please provide a online reproduction by forking this one or provide a minimal GitHub repository like create-react-app-antd. Issues labeled by Need Reproduce will be closed if no activities in 3 days.
 
你好 @guilin-jun，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过 fork 这个在线重现案例 ，或者提供一个最小化的 GitHub 仓库（类似 create-react-app-antd）。3 天内未跟进此 issue 将会被自动关闭。
  
什么是最小化重现，为什么这是必需的？

**Comment by BuyTmall** [comment]
我也遇到了, 给定dayjs默认值, 再选就报错, 不给默认值直接选, 里面月份和星期是英文的
