### ISSUE TITLE
Tree.DirectoryTree Expand/Collapse unexpectedly triggered onSelect callback

### ISSUE THREAD

**Issue by Wxh16144** [ant-design/ant-design#51430]
### Steps to reproduce

https://github.com/user-attachments/assets/165ea04c-c571-4ef3-81da-4078f02373b1

### What is expected?

不确定？ 之前的版本 比如 5.13.0 是不会触发。。

### What is actually happening?

点击 展开/收起 操作触发了 onSelect

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.2.0 |
| System | OSX |
| Browser | chrome 129.0.6668.101 |

**Comment by MadCcc** [comment]
应该只有 title 区域可以触发 onSelect
