### ISSUE TITLE
Input 值没有改变，但是还是会执行 onValuesChange 

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51432]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-l8f1hk?file=demo.tsx)

### Steps to reproduce

修改 Input 的值

### What is expected?

onValuesChange 不执行

### What is actually happening?

onValuesChange 执行了

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
的确有点怪异，虽然执行 `onValuesChange` 是符合预期的，但是它给出来的居然不是输入值，而是被受控的值。

**Comment by crazyair** [comment]
https://github.com/ant-design/ant-design/pull/51437
