### ISSUE TITLE
🐛 [BUG]: path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j No fix available

### ISSUE THREAD

**Issue by Samuel-Muriuki** [ant-design/ant-design#51449]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-njhjdb?file=package.json,README.md&terminal=dev)

### Steps to reproduce

#
$ npm audit
**# npm audit report**

**path-to-regexp**  2.0.0 - 3.2.0
Severity: **high**
**path-to-regexp outputs backtracking regular expressions** - https://github.com/advisories/GHSA-9wv6-86v2-598j
**No fix available**
node_modules/@refinedev/antd/node_modules/path-to-regexp
  **@ant-design/pro-layout**  <=4.3.2 || 4.7.3 - 7.20.0
  Depends on vulnerable versions of **path-to-regexp**
  node_modules/@refinedev/antd/node_modules/@ant-design/pro-layout
    **@refinedev/antd  ***
    Depends on vulnerable versions of **@ant-design/pro-layout**
    node_modules/@refinedev/antd

3 **high** severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

#

$ npm ls path-to-regexp
my-project
├─┬ @refinedev/antd@5.43.1
│ └─┬ @ant-design/pro-layout@7.17.12
│   └── path-to-regexp@2.4.0
└─┬ @refinedev/cli@2.16.39
  └─┬ @refinedev/devtools-server@1.1.37 invalid: "1.1.36" from node_modules/@refinedev/devtools
    └─┬ express@4.21.1
      └── path-to-regexp@0.1.10

#

$ npm ls send
my-project
└─┬ @refinedev/cli@2.16.39
  └─┬ @refinedev/devtools-server@1.1.37 invalid: "1.1.36" from node_modules/@refinedev/devtools
    └─┬ express@4.21.1
      ├── send@0.19.0
      └─┬ serve-static@1.16.2
        └── send@0.19.0 deduped
#

### What is expected?

$ npm audit
found 0 vulnerabilities

### What is actually happening?

$ npm audit
# npm audit report

path-to-regexp  2.0.0 - 3.2.0
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
No fix available
node_modules/@refinedev/antd/node_modules/path-to-regexp
  @ant-design/pro-layout  <=4.3.2 || 4.7.3 - 7.20.0
  Depends on vulnerable versions of path-to-regexp
  node_modules/@refinedev/antd/node_modules/@ant-design/pro-layout
    @refinedev/antd  *
    Depends on vulnerable versions of @ant-design/pro-layout
    node_modules/@refinedev/antd

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | react@18.3.1 |
| System | Linux |
| Browser | Version 1.71.118 Chromium: 130.0.6723.70 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
`@refinedev/antd` is not owned by us. and `@ant-design/pro-layout` is already use `path-to-regexp@8.0.0`
