### ISSUE TITLE
duplicate same style content with hash 

### ISSUE THREAD

**Issue by chienweiluo** [ant-design/ant-design#51457]
### Reproduction link

[https://ant.design/components/input](https://ant.design/components/input)

### Steps to reproduce

Open https://ant.design/components/input, and take a look at the <style> in head. there's multiple same style content with different hash.

### What is expected?

keep the style tag unique and be only one. Is it caused by mutiple ConfigProvider?

### What is actually happening?

insert multiple style tag with same content like
```
.anticon{display:inline-flex;align-items:center;color:inherit;font-style:normal;line-height:0;text-align:center;text-transform:none;vertical-align:-0.125em;text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}.anticon >*{line-height:1;}.anticon svg{display:inline-block;}.anticon .anticon .anticon-icon{display:block;}
```

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | all |
| System | all |
| Browser | all |

---
<style data-rc-order="prependQueue" data-css-hash="1hiqce2" data-token-hash="1zfd89">.anticon{display:inline-flex;align-items:center;color:inherit;font-style:normal;line-height:0;text-align:center;text-transform:none;vertical-align:-0.125em;text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}.anticon >*{line-height:1;}.anticon svg{display:inline-block;}.anticon .anticon .anticon-icon{display:block;}</style>
<style data-rc-order="prependQueue" data-css-hash="1hiqce2" data-token-hash="1zfd89">.anticon{display:inline-flex;align-items:center;color:inherit;font-style:normal;line-height:0;text-align:center;text-transform:none;vertical-align:-0.125em;text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}.anticon >*{line-height:1;}.anticon svg{display:inline-block;}.anticon .anticon .anticon-icon{display:block;}</style>
<style data-rc-order="prependQueue" data-css-hash="f09m49" data-token-hash="ghzubh">.anticon{display:inline-flex;align-items:center;color:inherit;font-style:normal;line-height:0;text-align:center;text-transform:none;vertical-align:-0.125em;text-rendering:optimizeLegibility;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}.anticon >*{line-height:1;}.anticon svg{display:inline-block;}.anticon .anticon .anticon-icon{display:block;}</style>
...

**Comment by zombieJ** [comment]
Seems we can move the `useResetIconStyle` out of csp cofig? 

ref https://github.com/ant-design/ant-design/blob/3f8943e2744f41f6c1434225b8f72d2813b1b722/components/theme/util/genStyleUtils.ts#L34

cc @YumoImer

**Comment by YumoImer** [comment]
Ok, let me look at this issue

**Comment by chienweiluo** [comment]
thanks guys @zombieJ & @YumoImer. Looking forward to your update. If  any further information, plz kindly let me know.

**Comment by chienweiluo** [comment]
@zombieJ @YumoImer Hi guys, which version of antd I should use to solve this issue? or is there any update about this?

**Comment by YumoImer** [comment]
> @zombieJ @YumoImer Hi guys, which version of antd I should use to solve this issue? or is there any update about this?

I've been very busy this past week, but I'll try to handle it as soon as possible. Sorry about that.

**Comment by chienweiluo** [comment]
now worries. thanks for your reply.

**Comment by chienweiluo** [comment]
Any update? or is there any workaround to fix this?

**Comment by YumoImer** [comment]
> Any update? or is there any workaround to fix this?

抱歉，我会在本周内完成。
