### ISSUE TITLE
RangePicker组件给了初始值，禁用了开始时间，选择结束时间后又回到了初始值

### ISSUE THREAD

**Issue by zhuangweixin** [ant-design/ant-design#51455]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-tgkl2f-zgq4sj?file=demo.tsx)

### Steps to reproduce

RangePicker组件给了初始值，禁用了开始时间，选择结束时间后又回到了初始值，选择后又跳回去了

### What is expected?

展示选中的时间

### What is actually happening?

选择后回到了初始值

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3 |
| System | Macos |
| Browser | 谷歌 |

---
在antd5.17的版本不存在问题，但是另一个项目版本比这个高，最新的也存在这个问题，该情况禁用了之前的时间和天数，很奇怪的bug，onchange也没有触发，设置了disabled，disabledDate，disabledTime，把disabledDate去掉又可以了。。。。

**Comment by zhuangweixin** [comment]
defaultValue={[
        dayjs('2024-10-31 00:00:00', 'YYYY-MM-DD HH:mm:ss'),
        dayjs('2024-10-31 10:59:59', 'YYYY-MM-DD HH:mm:ss'),
      ]} 
    默认值同一天得去掉disabledTime才能正常

   defaultValue={[
        dayjs('2024-10-30 00:00:00', 'YYYY-MM-DD HH:mm:ss'),
        dayjs('2024-10-31 10:59:59', 'YYYY-MM-DD HH:mm:ss'),
      ]}
    默认值不同一天去掉disabledDate才能正常

**Comment by zombieJ** [comment]
rc-picker 发了 patch，重装一下应该就好了~~
