### ISSUE TITLE
tree 组件开启虚拟滚动展示不全

### ISSUE THREAD

**Issue by Mooo-star** [ant-design/ant-design#51465]
### Reproduction link

[https://ant.design/components/tree-cn#tree-demo-virtual-scroll](https://ant.design/components/tree-cn#tree-demo-virtual-scroll)

### Steps to reproduce

直接往下拉就行，不管展开不展开都一样

### What is expected?

展示完整的结果

### What is actually happening?

没有展示完整的结果

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | macos |
| Browser | google |

**Comment by ustcfury** [comment]
> https://ant.design/components/tree-cn#tree-demo-virtual-scroll

确实是一个问题，修复后这里也没问题了，大佬看下我的代码？https://github.com/ant-design/ant-design/pull/51422

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/51485
