### ISSUE TITLE
DatePicker maxDate and minDate

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#5146]
It would be awesome to be able to set the `maxDate` and `minDates` that are considered selectable in the datePicker and timePicker. For example, using the range picker, I want to the user to only be able to select past dates/times. With something like jqueryui's date picker you can set it with [the `(max/min)Date` apis](http://api.jqueryui.com/datepicker/#option-maxDate).

Currently this is sort of possible with validation but its not a great user experience.

**Comment by benjycui** [comment]
Just for other developers: try [disabledDate and disabledTime](https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date).

**Comment by Bobinhos** [comment]
I would like to have minDate and maxDate too.
**disabledDate** rule works only for days in month, not for months and years, so user can change months and years even though all dates in month/year are disabled.
Or you can approve **disabledDate** behaviour for month/year pickers

**Comment by xTaz1** [comment]
Any updates here?

**Comment by pitops** [comment]
Any updates on this?

**Comment by TomasHubelbauer** [comment]
I was able to get the minimum date to work with the date picker by using the `disabledDate` prop like this:

```jsx
<DatePicker value={value} onChange={this.onDatePickerChange} disabledDate={d => !d || d.isBefore(minimum)} />
```

@Bobinhos can you elaborate on how one can select an invalid date with this setup? I clicked on the year/month selector and I can drill down to a month which is disabled as a whole, when I go to a month which is completely in the past, is that what you meant? It's impossible to select any dates there, but the component could probably be smarter and realize the whole month is off limits and disable navigating to it. For that however the `disabledDate` would have to be different because to ensure a whole month is off limits, the calendar would have to iterate all the possible date values and run them through the `disabledDate` function, which is not feasible.

**Comment by abhipanorian** [comment]
I was able to accomplish this by

`<DatePicker
      disabledDate={d =>
        !d || d.isAfter("2002-12-31") || d.isSameOrBefore("1960-01-01")
      }
      format="YYYY-MM-DD HH:mm:ss"
      defaultPickerValue={moment("2002-12-31")}
      placeholder="Start"
    />`

**Comment by Jab0rnal** [comment]
A stackblitzthat shows how to only pick this week:

https://stackblitz.com/edit/react-fcce79?file=index.js

Easily modifiable to allow other scenarios.

**Comment by jatindumka** [comment]
> @benjycui I would like to have minDate and maxDate too.
> **disabledDate** rule works only for days in month, not for months and years, so user can change months and years even though all dates in month/year are disabled.
> Or you can approve **disabledDate** behaviour for month/year pickers

@benjycui  were you able to disable month in month range selector????
For me disableDate only works for mode="days" ,if mode is 'month" i.e its a month picker disableDate prop does not work.....

**Comment by abhishekchotaliya** [comment]
it worked @abhipanorian !!! thanks
disabledDate={d => !d || d.isAfter("2002-12-31") || d.isSameOrBefore("1960-01-01") }

**Comment by shivamragnar** [comment]
Any updates on disabling years in the month picker if all the months in a year are disabled? It is not a good experience to select years and then not able to select months in it. I think it is necessary to have years disabled whose all months are disabled.

**Comment by lukasgjetting** [comment]
To anyone else wondering how to make this work for both date and time, here's how we solved it:

```js
const minDate = moment('XXXX-XX-XX YY:YY');
const maxDate = moment('XXXX-XX-XX YY:YY');

const getRange = (start, end) => [
	...Array((end - start) + 1).keys(),
].map((
	(i) => i + start
));

const disabledDate = useCallback((d) => {
	if (d == null) {
		return null;
	}

	return (
		(minDate != null && d.isBefore(minDate) && !d.isSame(minDate, 'day')) ||
		(maxDate != null && d.isAfter(maxDate) && !d.isSame(maxDate, 'day'))
	);
}, [minDate, maxDate]);

const disabledTime = useCallback((d) => {
	if (d == null) {
		return null;
	}

	if (d.isSame(minDate, 'day')) {
		return {
			disabledHours: () => (minDate.hour() > 0 ? getRange(0, minDate.hour() - 1) : []),
			disabledMinutes: (hour) => (hour === minDate.hour() && minDate.minutes() > 0 ?
				getRange(0, minDate.minutes() - 1) :
				[]
			),
		};
	}

	if (d.isSame(maxDate, 'day')) {
		return {
			disabledHours: () => getRange(maxDate.hour() + 1, 24),
			disabledMinutes: (hour) => (hour === maxDate.hour() ?
				getRange(maxDate.minutes() + 1, 60) :
				[]
			),
		};
	}

	return null;
}, [minDate, maxDate]);
```

**Comment by popadi** [comment]
Any update on this? I'd like to make the user able to select any date and time from the future (to schedule a job), but at the moment there's a lot of useless code that needs to be written to achieve this behavior. Easy for dates, very annoying for time + dates.

**Comment by nishant-k1** [comment]
Any updates??

**Comment by alvinAdler** [comment]
> I was able to accomplish this by
> 
> `<DatePicker disabledDate={d => !d || d.isAfter("2002-12-31") || d.isSameOrBefore("1960-01-01") } format="YYYY-MM-DD HH:mm:ss" defaultPickerValue={moment("2002-12-31")} placeholder="Start" />`

Worked like a charm. Thank you!

**Comment by cosmicknox** [comment]
` <DatePicker
                        style={{
                          width: "69%",
                          background: "black",
                          border: "none",
                          marginTop: "10px",
                          marginLeft: "-13px",
                        }}
                        disabledDate={(d) =>
                          !d ||
                          d.isAfter(
                            Date.now() + +1000 * 60 * 60 * 24 * 30 * 6
                          ) ||
                          d.isSameOrBefore(Date.now())
                        }
                        format="YYYY-MM-DD HH:mm:ss"
                      />
                      
                      `

adds 6  months Max limit  for the picker

**Comment by javsco** [comment]
I was able to disable days before today by:

`const minDate = dayjs().add(0, 'day');`

`    const disableDaysBeforeToday = useCallback(
        (d) => {
            if (d == null) {
                return null;
            }

            return (
                minDate != null &&
                d.isBefore(minDate) &&
                !d.isSame(minDate, 'day')
            );
        },
        [minDate],
    );`
    
  ` <DatePicker
            disabledDate={
            disableDaysBeforeToday
           }
/>`

**Comment by suhailgupta03** [comment]
```javascript
import React from 'react';
import { DatePicker } from 'antd';

const App = () => {
  const disabledDate = (current) => {
    // Can not select days before today and today
    return current && current.valueOf() < Date.now();
  };

  return (
    <div>
      <DatePicker disabledDate={disabledDate} />
    </div>
  );
};

export default App;

```
