### ISSUE TITLE
antd5设置了兼容，message静态调用无样式，使用App包裹umijs的rootContainer能解决，但是同样版本的另一个后台系统无法解决，antd的版本一样，唯一不一样的就是css-injs的版本问题了

### ISSUE THREAD

**Issue by qwe5117022** [ant-design/ant-design#51461]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-tgkl2f-s53vtf?file=app.ts)

### Steps to reproduce

# 1.引入依赖
```
import { ConfigProvider, App } from 'antd';
import { StyleProvider } from '@ant-design/cssinjs';
```
# 2.配置umijs 的app.tsx入口文件
```
export function rootContainer(container: React.ReactElement) {
  return <ConfigProvider>
    <StyleProvider hashPriority="high" transformers={[legacyLogicalPropertiesTransformer]}>
      <App style={{ height: '100%' }}>
        {container}
      </App>
    </StyleProvider>
  </ConfigProvider>
}
```
# 3.版本区别
能成功message有样式的版本号：
1.antd@5.20.2    css-in-js@1.16.2

不成功成功message有样式的版本号：
1.antd@5.20.2    css-in-js@1.16.2
2.antd@5.20.2     css-in-js@1.21.1

### What is expected?

能否找出针对的方法一次性解决，我这里十多个管理系统，去一个个改hook和替换引入也太麻烦，到时候

### What is actually happening?

无法用相同的antd的版本得到实际一样的结果

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18 |
| System | windows |
| Browser | Chrome/83.0.4103.116 |

---
能成功message有样式的版本号：
1.antd@5.20.2    css-in-js@1.16.2

不成功成功message有样式的版本号：
1.antd@5.20.2    css-in-js@1.16.2
2.antd@5.20.2     css-in-js@1.21.1
Chrome/83.0.4103.116

**Comment by zombieJ** [comment]
你给的 stackbliz 没有复现所述问题，改一下？

另外从你的描述看，应该是 node_modules 重复安装了不同的 `@ant-design/cssinjs` 依赖导致 antd 使用的和你的 StyleProvider 使用的 cssinjs 不是一个版本。

**Comment by qwe5117022** [comment]
没有呀，我是直接安装 "antd": "^5.2.2",css-in-js里面版本不一样，应该不是我这里的问题，我没单独进行安装，只是我排查的时候，发现cssinjs版本不一样

**Comment by qwe5117022** [comment]
> 你给的 stackbliz 没有复现所述问题，改一下？
> 
> 另外从你的描述看，应该是 node_modules 重复安装了不同的 `@ant-design/cssinjs` 依赖导致 antd 使用的和你的 StyleProvider 使用的 cssinjs 不是一个版本。

没有呀，我是直接安装 "antd": "^5.2.2",我去看依赖包，css-in-js里面版本不一样，应该不是我这里的问题，我没单独进行安装，只是我排查的时候，发现cssinjs版本不一样

**Comment by qwe5117022** [comment]
> > 你给的 stackbliz 没有复现所述问题，改一下？
> > 另外从你的描述看，应该是 node_modules 重复安装了不同的 `@ant-design/cssinjs` 依赖导致 antd 使用的和你的 StyleProvider 使用的 cssinjs 不是一个版本。
> 
> 没有呀，我是直接安装 "antd": "^5.2.2",我去看依赖包，css-in-js里面版本不一样，应该不是我这里的问题，我没单独进行安装，只是我排查的时候，发现cssinjs版本不一样

**Comment by qwe5117022** [comment]
> 你给的 stackbliz 没有复现所述问题，改一下？
> 
> 另外从你的描述看，应该是 node_modules 重复安装了不同的 `@ant-design/cssinjs` 依赖导致 antd 使用的和你的 StyleProvider 使用的 cssinjs 不是一个版本。

目前，我尝试不开启^泛版本，锁定版本为5.8.3，能够解决这个问题，为啥反而在最新版本，反而App无法解决静态message样式问题呢？

**Comment by qwe5117022** [comment]
> > 你给的 stackbliz 没有复现所述问题，改一下？
> > 另外从你的描述看，应该是 node_modules 重复安装了不同的 `@ant-design/cssinjs` 依赖导致 antd 使用的和你的 StyleProvider 使用的 cssinjs 不是一个版本。
> 
> 目前，我尝试不开启^泛版本，锁定版本为5.8.3，能够解决这个问题，为啥反而在最新版本.5.20.3，反而App无法解决静态message样式问题呢？

另外，虽然我能通过锁定版本到5.8.3，并且在umijs的rootContainer里添加App包裹来解决，静态方法message的context样式问题，但是这里也存在一个问题，当系统数量多的时候，或刚开始未使用hook形式和公用组件封装库的情况下，会导致维护比较困难

**Comment by MadCcc** [comment]
保证 @ant-design/cssinjs 的版本唯一吧

**Comment by afc163** [comment]
你需要保证 @ant-design/cssinjs 的版本是同一个，且统一使用 useMessage 来调用。
