### ISSUE TITLE
antd5FormchangedValues获取不到正确数据

### ISSUE THREAD

**Issue by AliceXu521** [ant-design/ant-design#51464]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-21-6-forked-9r6qs9)

## 4、失焦后，在handleValuesChange中，打印changedValues和allValues，结果不相同，changedValues获取prologueCopy错误，而allValues获取prologueCopy正确
[![formerror.png](https://i.postimg.cc/SNJ0pSJb/formerror.png)](https://postimg.cc/ppbcftfs)

### What is expected?

changedValues获取prologueCopy正确

### What is actually happening?

changedValues获取prologueCopy错误

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18.2.0 |
| System | windows 11 |
| Browser | chrome |

**Comment by zombieJ** [comment]
changedValues 只会涉及被改变的字段，其余字段不会填入。所以在数组场景下，也只会填入对应 `index` 的值。

**Comment by xushuaiABC** [comment]
> changedValues 只会涉及被改变的字段，其余字段不会填入。所以在数组场景下，也只会填入对应 `index` 的值。

感谢回答，但是如果我更改第二个输入框的内容，第一个输入框的值（是有值的），在handleValuesChange的changedValues会被置空，这是符合预期的吗

**Comment by AliceXu521** [comment]
> changedValues 只会涉及被改变的字段，其余字段不会填入。所以在数组场景下，也只会填入对应 `index` 的值。

感谢回答，但是如果我更改第二个输入框的内容，第一个输入框的值（是有值的），在handleValuesChange的changedValues会被置空，这是符合预期的吗

**Comment by AliceXu521** [comment]
> changedValues 只会涉及被改变的字段，其余字段不会填入。所以在数组场景下，也只会填入对应 `index` 的值。

就是这种情况：
[![formerror2.png](https://i.postimg.cc/PJK2LwJr/formerror2.png)](https://postimg.cc/Pvpm9N1B)
