### ISSUE TITLE
弹窗或者抽屉里用DatePicker日期选择器给设置默认时间，页面再选择时间无法实现

### ISSUE THREAD

**Issue by guilin-jun** [ant-design/ant-design#51462]
### Reproduction link

[https://github.com/guilin-jun/antd-DatePicker-bug.git](https://github.com/guilin-jun/antd-DatePicker-bug.git)

### Steps to reproduce

运行后选择日期

### What is expected?

运行后点开下拉框只选中当前默认日期，在页面能正常再选择日期，切换月份年份的时候能正常挨个切换

### What is actually happening?

运行后点开日期下拉框所有日期都选中了，而且切换年份或者月份跳跃的累加

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | "react": "^18.3.1", |
| System | window11 |
| Browser | Microsoft Edge 版本 130.0.2849.56 (正式版本) (64 位) |

**Comment by MadCcc** [comment]
![image](https://github.com/user-attachments/assets/4532738e-6365-4a85-aedc-16300539834a)
dayjs 和 moment 不能混用

**Comment by afc163** [comment]
antd 5.x 使用 dayjs 了。
