### ISSUE TITLE
使用Image.PreviewGroup的时候不能在Image中自定义预览渲染

### ISSUE THREAD

**Issue by fengzai6** [ant-design/ant-design#51474]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-qmngqf)

### Steps to reproduce

将image放入preview Group中并定义image中preview的image render

### What is expected?

image中设置的preview自定义render生效

### What is actually happening?

image中设置的preview自定义render不生效，仅在preview Group中的image render生效

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3.1 |
| System | mac-14.6.1 |
| Browser | edge-版本 130.0.2849.56 (正式版本) (arm64) |

**Comment by MadCcc** [comment]
符合预期，以 PreviewGroup 的 imageRender 为准。

**Comment by fengzai6** [comment]
> 符合预期，以 PreviewGroup 的 imageRender 为准。

我的场景是需要对多个情况进行渲染，如pdf自定义显示pdf，image正常，video又需要进行处理，这些判断能够在map Image的Item的时候传递type进行判断，但是在PreviewGroup中拿不到相应的自定义type的信息，根据url判断不太合适因为url不一定会带有相关信息；或者当PreviewGroup为设置imageRender的时候，以image中的为准？

**Comment by fengzai6** [comment]
> 这个问题我今天也遇到了，最后是大概这么解决的
> 
> ```
> previewList[idx + ""] = {
>             src: 1231312313,
>             mediaType: 2,
> };
> 
> <Image.PreviewGroup
>               items={previewList}
>               preview={{
>                 destroyOnClose: true,
>                 visible: preview.visible,
>                 current: preview.currentIdx,
>                 onVisibleChange: (value) => {
>                   setPreview((pre) => {
>                     return { ...pre, visible: value };
>                   });
>                 },
>                 imageRender: (_, info) => {
>                   const node = previewList[info.current + ""];
>                   if (node.mediaType == 2) {
>                     return (
>                       <video
>                         className="max-h-full max-w-full"
>                         controls
>                         autoPlay
>                         src={node.src}
>                       />
>                     );
>                   } else {
>                     return <img src={node.src} />;
>                   }
>                 },
>               }}
>             />
> ```

感谢你的思路😝
