### ISSUE TITLE
代码判断优化下哈

### ISSUE THREAD

**Issue by shiki-gm** [ant-design/ant-design#51471]
### Reproduction link

[https://github.com/ant-design/ant-design/blob/master/webpack.config.js](https://github.com/ant-design/ant-design/blob/master/webpack.config.js)

### Steps to reproduce

42行判断逻辑是否正确？
```
if (!process.env.CI || process.env.ANALYZER) {
```

### What is expected?

优化下判断逻辑，使其更明确

### What is actually happening?

优化下判断逻辑，使其更明确

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
这个环境变量在 CI 中会注入，没有问题哈~
