### ISSUE TITLE
暗黑主题下Menu Select Tree Table选中颜色不明显

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#51476]
### Reproduction link

[https://ant.design/components/tree-cn?theme=dark](https://ant.design/components/tree-cn?theme=dark)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/83e16713-7767-4b44-a577-f3d96cc1719b)

目录树选中的效果就很明显

![image](https://github.com/user-attachments/assets/4f77cf46-7e85-47c6-9f50-f680e4173689)

![image](https://github.com/user-attachments/assets/b27ef8c9-54ca-4a39-a6fa-8e1618b4c99e)

![image](https://github.com/user-attachments/assets/ed410cde-96a1-463e-be89-844b601cdd70)

### What is expected?

更易识别

### What is actually happening?

颜色太暗看不清

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | chrome latest |

**Comment by afc163** [comment]
Duplicate of #30524
