### ISSUE TITLE
create event by drag mouse within days in calendar

### ISSUE THREAD

**Issue by salekin02** [ant-design/ant-design#51475]
### What problem does this feature solve?

Right now I am not able to create a single event for a date range. Also there are no way to show event title on date ranges.

### What does the proposed API look like?

It can be like: https://fullcalendar.io/demos

**Comment by MadCcc** [comment]
Event in Calendar has been a feature request for a long time

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/12591
