### ISSUE TITLE
The Tooltip component is rendered over the draggable element till dragging

### ISSUE THREAD

**Issue by Ohar** [ant-design/ant-design#51470]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-h5wgxz)

### Steps to reproduce

1. Hover over any text on the page
2. Wait till Tooltip is rendered over it
3. Drag text away
4. See how part of tooltip is cropped and dragged after the text, which is unexpected and not desirable. 

### What is expected?

Draggable element has no any cropped tooltip part over it.

### What is actually happening?

Draggable element has a cropped tooltip part over it.

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | 18.2.0 |
| System | MacOS Sohoma 14.1 (23B2073)) |
| Browser | Chrome 130.0.6723.70 (arm64) |

---
There is also a [GitHub demo repository](https://github.com/Ohar/bug_antd.tooltip_react.dnd) and a screenshot ![screenshot](https://raw.githubusercontent.com/Ohar/bug_antd.tooltip_react.dnd/refs/heads/main/bug_example.png) of the bug.

**Comment by MadCcc** [comment]
DragDnd crop the image when dragging, not related with antd.
