### ISSUE TITLE
Drawer: 抽屉组件收起动画和组件hidden时机不一致导致会有一条黑线

### ISSUE THREAD

**Issue by 513205785Xie** [ant-design/ant-design#51487]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-uhv3s6?file=demo.tsx)

### Steps to reproduce

点击打开弹窗，然后关闭，在抽屉收起的方向上会有一条shadow的阴影，在抽屉收起后过一段时间才消失，hidden类名设置的时机与动画设置的时间不同步

### What is expected?

hidden类名设置的时机与动画设置的时间同步

### What is actually happening?

hidden类名设置的时机与动画设置的时间不同步

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | "react": "18.2.0" |
| System | macOS 12.5.1 |
| Browser | chrome 119.0.6045.159 |

**Comment by zombieJ** [comment]
没太理解这个“黑线”，你的重现看似乎把 duration 给关了并没有用动画。

**Comment by 513205785Xie** [comment]
> 没太理解这个“黑线”，你的重现看似乎把 duration 给关了并没有用动画。

是的，我把动画时长设置为零了，但是`ant-drawer-content-wrapper`这个节点被设置`ant-drawer-content-wrapper-hidden`类名的时机会比动画时长要长一些，这样会导致在收起方向上存留一小段时间的上述节点的shadow样式阴影，就是上面问题我描述的“黑线”。但是如果把这个时机跟动画时长同步了像是会导致收起最后闪一下的效果，确实不是很好处理，除非单独为关闭动画的情况设置一个同步hidden时机...

**Comment by zombieJ** [comment]
录个屏看看？
