### ISSUE TITLE
【Tree】虚拟滚动高度不正确

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#51485]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-vnokz2?file=demo.tsx)

### Steps to reproduce

1. 将数据出现的高度小于Tree设置的高度
2. 展开Tree的节点，就会发现Tree高度问题，也无法滚动

### What is expected?

Tree高度正常

### What is actually happening?

Tree高度不正常

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | latest |
| System | macOS |
| Browser | chrome130.0.6723.92 |

https://github.com/user-attachments/assets/76e07dfd-ccba-4a9b-90fd-49de1b071add

**Comment by samllLuck** [comment]
请问这个问题解决了吗，我也遇到了，初始化是能显示全的，然后展开再收起的时候，显示不全，并且无法滚动到最底部

**Comment by chenxiaochun** [comment]
现在我用 5.23.1 版本，在默认开启 virtual 的情况下，依然有问题

**Comment by wozien** [comment]
遇到同样的问题，特别是titleRender修改item的高度的话，height计算有问题，倒是内容显示不全

**Comment by XianZhengquan** [comment]
> 遇到同样的问题，特别是titleRender修改item的高度的话，height计算有问题，倒是内容显示不全

看这个 issue 关闭了，还是没有解决吗？我现在项目里用的，好像没有这个问题了
