### ISSUE TITLE
Switch inside Form.Item will be toggled when clicking label

### ISSUE THREAD

**Issue by hasakilol** [ant-design/ant-design#51499]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/broken-forest-6zll8y?file=%2Fsrc%2FApp.js%3A18%2C43)

### Steps to reproduce

Click on the label, you will see the switch toggling between on/off.

### What is expected?

The switch component should not change when user clicks form item label.

### What is actually happening?

The switch component toggles when user clicks form item label.

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | >= 17.0.0 |
| System | Windows 10 |
| Browser | Chrome latest |

---
If you remove the name attribute of form item, switch will not change.

**Comment by joket1999** [comment]
.ant-form-item-label > label {
 	pointer-events: none;
}
