### ISSUE TITLE
TreeSelect 组件多选模式下控制最大选择数量

### ISSUE THREAD

**Issue by ilxqx** [ant-design/ant-design#51490]
### What problem does this feature solve?

`Select` 组件有一个属性 `maxCount` 用来控制最大选择的数量（多选模式下），`TreeSelect`并没有此属性，希望官方可以增加一下🙏🙏🙏
<img width="1543" alt="image" src="https://github.com/user-attachments/assets/f1329a26-21cd-42d3-b90d-141f529d5b1e">

### What does the proposed API look like?

增加 `maxCount` 属性控制最大选择数量

**Comment by aojunhao123** [comment]
我来！😤

**Comment by Mrcxt** [comment]
迫切需要这个能力

**Comment by aojunhao123** [comment]
下个minor会上线这个功能，耐心等待下🤓
