### ISSUE TITLE
onChange method is not definition in Form.d.ts

### ISSUE THREAD

**Issue by DavidCHN** [ant-design/ant-design#5149]
#### Environment(required)

- antd version:2.7.4
- OS and its version: Win10
- Browser and its version: IE11

onChange method is not definition in Form.d.ts

![image](https://cloud.githubusercontent.com/assets/26082204/23535664/c0da8a9c-fffa-11e6-907a-0e62d424a2d8.png)
![image](https://cloud.githubusercontent.com/assets/26082204/23535716/12cdf17c-fffb-11e6-977c-ad8ab6827668.png)

**Comment by benjycui** [comment]
Actually, we don't need to.

Just pass `onChange` to form controls directly, see [demo](https://ant.design/components/form/#components-form-demo-validate-other).

**Comment by DavidCHN** [comment]
Can you describe it carefully?

**Comment by benjycui** [comment]
```jsx
{getFieldDecorator('input')(
  <Input onChange={...} />
)}
```
