### ISSUE TITLE
自定义规则中，defaultField的使用问题

### ISSUE THREAD

**Issue by GuoSTZ** [ant-design/ant-design#51494]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-antd-5-21-6-forked-dy5ch9)

### Steps to reproduce

是使用问题吗？关于defaultField的自定义规则，目前也没有看到相关的使用说明。

```tsx
import React from 'react';
import { Checkbox, Form } from 'antd';

const App = () => {
  return (
    <Form labelCol={{ span: 4 }}>
      <Form.Item
        name="checkbox"
        label="多选框组合"
        rules={[{ 
          type: 'array',
          max: 4,
          defaultField: {
            type: 'number',
            min: 30,
            message: '数组每项的值都要>=30' 
          },
          message: '最多只能选择4项'
        }]}
      >
        <Checkbox.Group
          style={{ width: '100%' }}
          options={[
            {label: '值为10', value: 10},
            {label: '值为20', value: 20},
            {label: '值为30', value: 30},
            {label: '值为40', value: 40},
            {label: '值为50', value: 50},
          ]}
        />
      </Form.Item>
    </Form>
  );
};

export default App;
```

### What is expected?

1. 如果不满足外层rule规则，应该仅提示外层rule的message
2. 如果满足外层rule规则，但是不满足defaultField内的规则，应该仅提示一次报错信息，而不是每有一项规则不符，就提示一次

### What is actually happening?

1. 数组元素中，只要有n条不满足的数据，就是有n条message被显示出来
2. 当最外层rule也有message时，message的显示会有问题，复现方式为，反复触发外层校验成功与失败

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | >=18.0.0 |
| System | mac15.0.1 |
| Browser | chrome129.0.6668.101 |

**Comment by zombieJ** [comment]
重现没设置为公开哈：

<img width="798" alt="截屏2024-11-05 16 48 23" src="https://github.com/user-attachments/assets/4286d529-2e57-48ab-9fbf-9f2e51059a14">

**Comment by GuoSTZ** [comment]
> 重现没设置为公开哈：
> 
> <img alt="截屏2024-11-05 16 48 23" width="798" src="https://private-user-images.githubusercontent.com/5378891/383071142-4286d529-2e57-48ab-9fbf-9f2e51059a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTY5MzIsIm5iZiI6MTczMDc5NjYzMiwicGF0aCI6Ii81Mzc4ODkxLzM4MzA3MTE0Mi00Mjg2ZDUyOS0yZTU3LTQ4YWItOWZiZi05ZjJlNTEwNTlhMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMDg1MDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNjODFmZGE4ZjFiNWU4NmE2YWQ0NWEyN2E3NmRjZDEwN2ZjNDgwYTI3NTVkY2NkZjhjZDljYmYzYTU5NzFhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QZSUfR_cnvGKbLUumzYkdEo5J-8Ag01OGaO-ro4bJS4">

不好意思，目前已设置放开

**Comment by zombieJ** [comment]
多个相同提示是预期行为，但是这里看起来有 React key warning 需要修一下。
