### ISSUE TITLE
Allow antd form's setFields' errors' field to accept not only array of string but also array of ReactNode

### ISSUE THREAD

**Issue by wtusfo** [ant-design/ant-design#51505]
### What problem does this feature solve?

I and probably a lot of devs need to wrap their erorrs in some html before setting them. But current API allows to pass only `string[]` to setFields method (`setFields({errors: string[]})`. Although if we pass `ReactNode[]` that works fine but one needs to type cast it, which is not the best thing to do. 
This change made we can wrap errors in any html we want, whether it is addidng locators for automated testing purposes or just changing the appereance of the error.

### What does the proposed API look like?

```
setFields: ({
    touched: boolean;
    validating: boolean;
    errors: (string | ReactNode)[];
    warnings: string[];
    name: InternalNamePath;
    validated: boolean;
})) => void

<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by MadCcc** [comment]
Actually you can pass ReactNode into `errors`. But we keep `string` as type of error because ReactNode is not by design, and may cause style issue.
