### ISSUE TITLE
[FloatButton] `shape` cannot have two states in one group.

### ISSUE THREAD

**Issue by RSS1102** [ant-design/ant-design#51518]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-ykt2wq?file=demo.js)

### Steps to reproduce

Two different `shape` are set in one group 

### What is expected?

Two different `shape` of states

### What is actually happening?

but there is only one type.

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | ^18.3.1 |
| System | win11 |
| Browser | Chrome 版本 130.0.6723.93（正式版本） （64 位） |

---
But `type` can set two different states

**Comment by zombieJ** [comment]
Why do you want this feature? This requirement seems strange.

**Comment by RSS1102** [comment]
> Why do you want this feature? This requirement seems strange.

No, I just accidentally discovered it during the coding process. I thought it was a bug, so I brought it up. 
Maybe someone may use it, after all, it should be controlled by users themselves, not because the product manager said it might seem strange and restricts users 'actions at the bottom level(For personal thoughts only, the issue can be closed if it is inappropriate.🤔🤔)

**Comment by zombieJ** [comment]
Thanks for reply.

For discussion, it seems not follow the design of FloatButton. So we may not support this.
