### ISSUE TITLE
Tree组件增加右键菜单

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#5151]
tree组件需要有右键上下文菜单，经常需要在某个节点上进行操作。
现在tree没有这个属性

**Comment by yesmeck** [comment]
See http://react-component.github.io/tree/examples/contextmenu.html

**Comment by bf185003** [comment]
这个例子给我没用，我是用antD的。

**Comment by yesmeck** [comment]
antd 的组件都是基于 react-component 封装的，上面的例子可以直接参考。

**Comment by jcy2004x** [comment]
我实现了，看下关键的几行代码就明白了


<Tree onRightClick={this.treeNodeonRightClick} >

// 实现这个方法 treeNodeonRightClick
treeNodeonRightClick(e) {
        this.setState({
            rightClickNodeTreeItem: {
                pageX: e.event.pageX,
                pageY: e.event.pageY,
                id: e.node.props['data-key'],
                categoryName: e.node.props['data-title']
            }
        });
    }

// id 和 categoryName 是生成时绑上去的

<TreeNode
                        key={item.id}
                        title={title}
                        data-key={item.id}
                        data-title={item.categoryName}
                    />);

// 最后绑个菜单就可以实现了
getNodeTreeRightClickMenu() {
        const {pageX, pageY} = {...this.state.rightClickNodeTreeItem};
        const tmpStyle = {
            position: 'absolute',
            left: `${pageX - 220}px`,
            top: `${pageY - 70}px`
        };
        const menu = (
            <Menu
                onClick={this.handleMenuClick}
                style={tmpStyle}
                className={style.categs_tree_rightmenu}
            >
                <Menu.Item key='1'><Icon type='plus-circle'/>{'加同级'}</Menu.Item>
                <Menu.Item key='2'><Icon type='plus-circle-o'/>{'加下级'}</Menu.Item>
                <Menu.Item key='4'><Icon type='edit'/>{'修改'}</Menu.Item>
                <Menu.Item key='3'><Icon type='minus-circle-o'/>{'删除目录'}</Menu.Item>
            </Menu>
        );
        return (this.state.rightClickNodeTreeItem == null) ? '' : menu;
    }

**Comment by chj-damon** [comment]
@jcy2004x 请问您定义的这个getNodeTreeRightClickMenu方法是在哪里调用的？

**Comment by jcy2004x** [comment]
@chj-damon 
生成主界面的时候完成的（方法 render ），因为每一次state的变化后，render方法都会执行，所以变一下任意的this.state里面的状态，就会执行render() ，这样，getNodeTreeRightClickMenu方法放在render方法里来生成界面的一部分。就可以了

**Comment by kimyengil** [comment]
@jcy2004x   请问下，您这个有完整的示例代码么？多谢了

**Comment by fxn9801** [comment]
还是不知道你这个getNodeTreeRightClickMenu方法是在哪里调用的？ @jcy2004x 
可以详细说下吗？

**Comment by fxn9801** [comment]
@jcy2004x getNodeTreeRightClickMenu方法是怎么放在render方法里的呢？我没研究明白。可以说一下吗？谢谢

**Comment by TengFeiHao** [comment]
可以写明白点吗？调用getNodeTreeRightClickMenu函数 后 那个 menu 怎么显示到页面上？

**Comment by lemonnoodle** [comment]
@TengFeiHao   根据@jcy2004x 的方法弄的，可以参考下https://github.com/lemonnoodle/react-mobx-dashboard/blob/master/src/components/ios/Create.jsx

**Comment by itskaiway** [comment]
上面的方法可行，不过里面有个获取位置的方法建议用`e.event.currentTarget.getBoundingClientRect()`方法，目前直接用`e.event.pageX`以及`e.event.pageX`感觉有点问题。
### 建议写法

```
onRightClick = (e) => {
    const positionInfo = e.event.currentTarget.getBoundingClientRect();
    const x = positionInfo.right;
    const y = positionInfo.bottom;
    this.setState({
      NodeTreeItem: {
        pageX: x,
        pageY: y,
        parentKey: e.node.props.dataRef.parentKey,
        id: e.node.props.eventKey,
      },
    });
  };
```

**Comment by dargonpaul** [comment]
可以不用自己写，也不用antd的tree的右键事件熟悉，antd官方推荐了两个优秀的右键菜单组件，我只用了其中一个https://github.com/fkhadra/react-contexify
tree的子节点组件是TreeNode ，  它有一个title属性是用来传递每个节点显示的给用户看到内容的，可以在这里，把右键菜单的组件ContextMenuProvider包进去，关键代码如下：

import { ContextMenu, Item, Separator, Submenu, ContextMenuProvider } from 'react-contexify';
import 'react-contexify/dist/ReactContexify.min.css';
const onContextMenuClick = ({ event, ref, data, dataFromProvider }) => console.log(ref.dataset.key);
        // create your menu first
        const MyAwesomeMenu = () => (
            <ContextMenu id='menu_id'>
              <Item onClick={onContextMenuClick}>Lorem</Item>
              <Item onClick={onContextMenuClick}>Ipsum</Item>
              <Separator />
              <Item disabled>Dolor</Item>
              <Separator />
              <Submenu label="Foobar">
                <Item onClick={onContextMenuClick}>Foo</Item>
                <Item onClick={onContextMenuClick}>Bar</Item>
              </Submenu>
            </ContextMenu>
        );
const title = (<ContextMenuProvider id='menu_id'  data-key={item.key}><span>{item.title}</span></ContextMenuProvider>);

<Tree>
  <TreeNode key={item.key} title={title}></TreeNode>
</Tree>

**Comment by lyuehh** [comment]
@dargonpaul  你的这个例子里 `<MyAwesomeMenu />` 在哪渲染啊

**Comment by guirenpei** [comment]
@dargonpaul 
只要一用ContextMenu就报错，有什么好的解决办法吗
```react
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CContextMenu`.
```

**Comment by ruihelin** [comment]
@guirenpei  用Menu替换ContextMenu就可以

**Comment by guirenpei** [comment]
> @guirenpei 用Menu替换ContextMenu就可以

ok, thx

**Comment by ChinaShrimp** [comment]
```javascript
import React from 'react';

import { Tree } from 'antd';
import { Menu, Item, MenuProvider } from 'react-contexify';
import 'react-contexify/dist/ReactContexify.min.css';

// contextMenu: { menuId, items: { name, handler }} 上下文菜单
// dataSource: 树节点
const TreeWithContextMenu = ({ dataSource, contextMenu }) => {
  // 上下文菜单
  const ContextMenu = () => (
    <Menu id={contextMenu.menuId}>
      {contextMenu.items.map(item => (
        <Item onClick={item.handler}>{item.name}</Item>
      ))}
    </Menu>
  );

  // 渲染树节点，主要目的是为了通过react-contexify包裹上下文菜单
  const renderEntityTreeNodes = data => {
    return data.map(item => {
      const title = (
        <MenuProvider id={contextMenu.menuId} data-key={item.key}>
          <span>{item.title}</span>
        </MenuProvider>
      );

      if (item.children) {
        const result = (
          <Tree.TreeNode {...item} key={item.key} title={title}>
            {renderEntityTreeNodes(item.children)}
          </Tree.TreeNode>
        );

        return result;
      }

      return <Tree.TreeNode {...item} key={item.key} title={title} />;
    });
  };

  return (
    <div>
      <Tree defaultExpandedKeys={['0-0-0']}>{renderEntityTreeNodes(dataSource)}</Tree>
      <ContextMenu />
    </div>
  );
};

export default TreeWithContextMenu;
```

In case有人需要，贴个完整版的组件。

**Comment by truewq** [comment]
> 我实现了，看下关键的几行代码就明白了
> 
> `<Tree onRightClick={this.treeNodeonRightClick} >`
> 
> // 实现这个方法 treeNodeonRightClick
> 
> ```
> treeNodeonRightClick(e) {
>         this.setState({
>             rightClickNodeTreeItem: {
>                 pageX: e.event.pageX,
>                 pageY: e.event.pageY,
>                 id: e.node.props['data-key'],
>                 categoryName: e.node.props['data-title']
>             }
>         });
>     }
> ```
> 
> // id 和 categoryName 是生成时绑上去的
> 
> ```
> <TreeNode
>                         key={item.id}
>                         title={title}
>                         data-key={item.id}
>                         data-title={item.categoryName}
>                     />);
> ```
> 
> // 最后绑个菜单就可以实现了
> 
> ```
> getNodeTreeRightClickMenu() {
>         const {pageX, pageY} = {...this.state.rightClickNodeTreeItem};
>         const tmpStyle = {
>             position: 'absolute',
>             left: `${pageX - 220}px`,
>             top: `${pageY - 70}px`
>         };
>         const menu = (
>             <Menu
>                 onClick={this.handleMenuClick}
>                 style={tmpStyle}
>                 className={style.categs_tree_rightmenu}
>             >
>                 <Menu.Item key='1'><Icon type='plus-circle'/>{'加同级'}</Menu.Item>
>                 <Menu.Item key='2'><Icon type='plus-circle-o'/>{'加下级'}</Menu.Item>
>                 <Menu.Item key='4'><Icon type='edit'/>{'修改'}</Menu.Item>
>                 <Menu.Item key='3'><Icon type='minus-circle-o'/>{'删除目录'}</Menu.Item>
>             </Menu>
>         );
>         return (this.state.rightClickNodeTreeItem == null) ? '' : menu;
>     }
> ```

菜单是弹出来了，但是位置始终不对。

**Comment by truewq** [comment]
> ```js
> import React from 'react';
> 
> import { Tree } from 'antd';
> import { Menu, Item, MenuProvider } from 'react-contexify';
> import 'react-contexify/dist/ReactContexify.min.css';
> 
> // contextMenu: { menuId, items: { name, handler }} 上下文菜单
> // dataSource: 树节点
> const TreeWithContextMenu = ({ dataSource, contextMenu }) => {
>   // 上下文菜单
>   const ContextMenu = () => (
>     <Menu id={contextMenu.menuId}>
>       {contextMenu.items.map(item => (
>         <Item onClick={item.handler}>{item.name}</Item>
>       ))}
>     </Menu>
>   );
> 
>   // 渲染树节点，主要目的是为了通过react-contexify包裹上下文菜单
>   const renderEntityTreeNodes = data => {
>     return data.map(item => {
>       const title = (
>         <MenuProvider id={contextMenu.menuId} data-key={item.key}>
>           <span>{item.title}</span>
>         </MenuProvider>
>       );
> 
>       if (item.children) {
>         const result = (
>           <Tree.TreeNode {...item} key={item.key} title={title}>
>             {renderEntityTreeNodes(item.children)}
>           </Tree.TreeNode>
>         );
> 
>         return result;
>       }
> 
>       return <Tree.TreeNode {...item} key={item.key} title={title} />;
>     });
>   };
> 
>   return (
>     <div>
>       <Tree defaultExpandedKeys={['0-0-0']}>{renderEntityTreeNodes(dataSource)}</Tree>
>       <ContextMenu />
>     </div>
>   );
> };
> 
> export default TreeWithContextMenu;
> ```
> 
> In case有人需要，贴个完整版的组件。


还是你这个方案好，上面直接用onRightClick鼠标位置都不正确。不过数据结构应该是个数组吧
// contextMenu: { menuId, items: [{ name, handler }]} 上下文菜单
感谢感谢

**Comment by daixianceng** [comment]
```js
    <a-dropdown :trigger="['contextmenu']">
      <a-tree>
      </a-tree>
      <a-menu slot="overlay">
        <a-menu-item key="1">1st menu item</a-menu-item>
        <a-menu-item key="2">2nd menu item</a-menu-item>
        <a-menu-item key="3">3rd menu item</a-menu-item>
      </a-menu>
    </a-dropdown>
```

**Comment by ShawLyon** [comment]
> ```js
> import React from 'react';
> 
> import { Tree } from 'antd';
> import { Menu, Item, MenuProvider } from 'react-contexify';
> import 'react-contexify/dist/ReactContexify.min.css';
> 
> // contextMenu: { menuId, items: { name, handler }} 上下文菜单
> // dataSource: 树节点
> const TreeWithContextMenu = ({ dataSource, contextMenu }) => {
>   // 上下文菜单
>   const ContextMenu = () => (
>     <Menu id={contextMenu.menuId}>
>       {contextMenu.items.map(item => (
>         <Item onClick={item.handler}>{item.name}</Item>
>       ))}
>     </Menu>
>   );
> 
>   // 渲染树节点，主要目的是为了通过react-contexify包裹上下文菜单
>   const renderEntityTreeNodes = data => {
>     return data.map(item => {
>       const title = (
>         <MenuProvider id={contextMenu.menuId} data-key={item.key}>
>           <span>{item.title}</span>
>         </MenuProvider>
>       );
> 
>       if (item.children) {
>         const result = (
>           <Tree.TreeNode {...item} key={item.key} title={title}>
>             {renderEntityTreeNodes(item.children)}
>           </Tree.TreeNode>
>         );
> 
>         return result;
>       }
> 
>       return <Tree.TreeNode {...item} key={item.key} title={title} />;
>     });
>   };
> 
>   return (
>     <div>
>       <Tree defaultExpandedKeys={['0-0-0']}>{renderEntityTreeNodes(dataSource)}</Tree>
>       <ContextMenu />
>     </div>
>   );
> };
> 
> export default TreeWithContextMenu;
> ```
> 
> In case有人需要，贴个完整版的组件。


这行改成  `<MenuProvider id={contextMenu.menuId} data={item}>`， 不然有坑

**Comment by PeiHaigang** [comment]
Now you don't need react-contexify any more. Use antd Dropdown component is better, you still need to custom the title of the tree node, then use Dropdown to wrapper it, like below:
`
<Dropdown overlay={treeMenu} trigger={['contextMenu']}>
    <span>{`${item.title}`}</span>
</Dropdown>
`
treeMenu like this:
`
 const treeMenu = (
    <Menu>
      <Menu.Item key="1">1st menu item</Menu.Item>
      <Menu.Item key="2">2nd menu item</Menu.Item>
      <Menu.Item key="3">3rd menu item</Menu.Item>
    </Menu>
  );
`

**Comment by rancy98** [comment]
> 上面的方法可行，不过里面有个获取位置的方法建议用`e.event.currentTarget.getBoundingClientRect()`方法，目前直接用`e.event.pageX`以及`e.event.pageY`感觉有偏移。
> 
> ### 个人写法
> ```
> onRightClick = (e) => {
>     const positionInfo = e.event.currentTarget.getBoundingClientRect();
>     const x = positionInfo.right;
>     const y = positionInfo.bottom;
>     this.setState({
>       NodeTreeItem: {
>         pageX: x,
>         pageY: y,
>         parentKey: e.node.props.dataRef.parentKey,
>         id: e.node.props.eventKey,
>       },
>     });
>   };
> ```

如果这个菜单在一个滚动容器内，点击坐标怎么获取呢

**Comment by nickrogit** [comment]
> ContextMenuProvi

> ```js
> MenuProvider
> ```

react-contexify哪个版本?，react-contexify 5.0.0没有这个MenuProvider呀。

**Comment by nickrogit** [comment]
> ```js
> MenuProvider
> ```

什么版本？没有MenuProvider

**Comment by ityoung** [comment]
> Now you don't need react-contexify any more. Use antd Dropdown component is better, you still need to custom the title of the tree node, then use Dropdown to wrapper it, like below: ` <Dropdown overlay={treeMenu} trigger={['contextMenu']}> <span>{`${item.title}`}</span> </Dropdown> ` treeMenu like this: `const treeMenu = ( <Menu> <Menu.Item key="1">1st menu item</Menu.Item> <Menu.Item key="2">2nd menu item</Menu.Item> <Menu.Item key="3">3rd menu item</Menu.Item> </Menu> );`

4.5以上版本基于 @PeiHaigang 的补充：

使用 `titleRender` + `treeData` **不需要**再遍历树结构、生成TreeNode

```
<Tree 
  ...
  titleRender={(item) => (<Dropdown><span>{item.title}</span></Dropdown>)}
  treeData={treeData}
/>
```

**Comment by felixsfan** [comment]
typescript、react、ant design实现tree实现目录树增删改

`import React, { useState } from 'react';
import { Tree, Modal, Input, Popover, Menu } from 'antd';
import { EllipsisOutlined,EditOutlined,DeleteOutlined,DiffOutlined } from '@ant-design/icons';
import type { DataNode, DirectoryTreeProps } from 'antd/es/tree';

const { DirectoryTree } = Tree;

const treeData: DataNode[] = [
  {
    title: 'toc收入',
    key: '0',
    children: [
      { title: '月结任务', key: '0-0-0', isLeaf: true },
      { title: '数据同步', key: '0-0-1', isLeaf: true }
    ],
		isLeaf: false
  },
  {
    title: 'tob收入',
    key: '1',
    children: [
      { title: '月结任务', key: '0-1-0', isLeaf: true },
      { title: '数据同步', key: '0-1-1', isLeaf: true },
    ],
		isLeaf: false
  },
];

const App: React.FC = () => {
  const [visible, setVisible] = useState(false);
  const [editNode, setEditNode] = useState<DataNode | null>(null);
  const [treeDataState, setTreeDataState] = useState<DataNode[]>(treeData);

  const onSelect: DirectoryTreeProps['onSelect'] = (keys, info) => {
    console.log('Trigger Select', keys, info);
  };

  const onExpand: DirectoryTreeProps['onExpand'] = (keys, info) => {
    console.log('Trigger Expand', keys, info);
  };

  const onEditNode = (node: DataNode) => {
    setEditNode(node);
    setVisible(true);
  };

  const onDeleteNode = (node: DataNode) => {
  };

  const onModalOk = (value: string) => {
    const newTreeData = [...treeDataState];
    if (editNode) {
      // 编辑节点
      editNode.title = value;
    } else {
      }
    }
    setTreeDataState(newTreeData);
    setVisible(false);
  };

  const onModalCancel = () => {
    setVisible(false);
  };

  const findParentNode = (treeData: DataNode[], key: any): DataNode | null => {
    for (let i = 0; i < treeData.length; i++) {
      const node = treeData[i];
      if (node.key === key) {
        return null;
      }
      if (node.children) {
        const parentNode = findParentNode(node.children, key);
        if (parentNode) {
          return parentNode;
        }
      }
    }
    return null;
  };

	const menu_file = (node) => (
		<Menu>
			<Menu.Item key="edit" icon={<EditOutlined />} onClick={() => onEditNode(node)}>
				编辑视图
			</Menu.Item>
			<Menu.Item key="delete" icon={<DeleteOutlined />} onClick={() => onDeleteNode(node)}>
				删除视图
			</Menu.Item>
		</Menu>
	);
	const menu_directory = (node) => (
		<Menu>
			<Menu.Item key="add" icon={<DiffOutlined />} onClick={() => onEditNode(node)}>
				新建视图
			</Menu.Item>
			<Menu.Item key="edit" icon={<EditOutlined />} onClick={() => onEditNode(node)}>
				编辑文件夹
			</Menu.Item>
			<Menu.Item key="delete" icon={<DeleteOutlined />} onClick={() => onDeleteNode(node)}>
				删除文件夹
			</Menu.Item>
		</Menu>
	);
	const titleRender = (node) => {
		console.log(node);
		if (node.isLeaf){
			return (
				<span>
					{node.title}
					<Popover content={menu_file(node)} trigger="click" placement="rightTop">
						<EllipsisOutlined style={{ marginLeft: 8 , fontSize: 20}} />
					</Popover>
				</span>
			);
		}else{
			return (
				<span>
					{node.title}
					<Popover content={menu_directory(node)} trigger="click" placement="rightTop">
						<EllipsisOutlined style={{ marginLeft: 8 , fontSize: 20}} />
					</Popover>
				</span>
			);
		}
	};
	
	return (
		<>
			<DirectoryTree
				multiple
				defaultExpandAll
				onSelect={onSelect}
				onExpand={onExpand}
				treeData={treeDataState}
				titleRender={titleRender}
			/>
			<Modal
				title={editNode ? 'Edit Node' : 'Add Node'}
				visible={visible}
				onOk={(e) => onModalOk((e.target as HTMLInputElement).value)}
				onCancel={onModalCancel}
			>
				<Input defaultValue={editNode?.title} />
			</Modal>
		</>
	);
}
export default App;
`
