### ISSUE TITLE
CSP nonce 未完全生效

### ISSUE THREAD

**Issue by justiceti** [ant-design/ant-design#51511]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/stackblitz-starters-cbgxmq?file=src%2FApp.tsx)

### Steps to reproduce

我在使用message后，页面新插入了关于message的style标签，但是这个标签没有带上ConfigProvider设置的nonce

### What is expected?

新加入的style标签有nonce属性

### What is actually happening?

新加入的style标签没有nonce属性

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18.1.0 |
| System | MacOS 12.7.5 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
静态方法不消费 ConfigProvider 的 context，请关注一下控制台的报错信息哈：

<img width="451" alt="截屏2024-11-06 17 53 55" src="https://github.com/user-attachments/assets/3e21f976-090a-4bd0-8a50-26d62d536bf7">

**Comment by justiceti** [comment]
@zombieJ  谢谢，不过我应该怎么处理呢？我的问题是因为CSP不建议设置unsafe-inline 但是这样的style我又设置不上nonce导致加载不了样式

**Comment by afc163** [comment]
用 useMessage 或者 useApp。

**Comment by afc163** [comment]
看看是不是有不同的 @ant-design/icons 版本共存了？

**Comment by justiceti** [comment]
确实是有版本共存

**Comment by chienweiluo** [comment]
> 确实是有版本共存

能請教下老哥後來是怎麼解決的嗎? 加resolutions後好像還是有這個問題
