### ISSUE TITLE
TreeSelect with treeCheckable={true} prop is not recognizable by screen readers.

### ISSUE THREAD

**Issue by aliendrippin** [ant-design/ant-design#51517]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/w928py)

### Steps to reproduce

Use any screen reader (tested  with VoiceOver on MacOS and NVDA on Windows).

### What is expected?

To be able to recognize TreeSelect treeCheckable={true} with screen reader.

### What is actually happening?

Screen reader does not recognize this element with such prop.

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | React v17.0.1 |
| System | MacOS |
| Browser | Google Chrome v130.0.6723.71 |

---
With treeCheckable={true} <div class="ant-select-selection-search" /> and inner <div class="ant-select-selection-search-input" /> which has role="combobox" and is responsible for accessability are wrapped by <div class="ant-select-selection-overflow" /> and inner <div class="ant-select-selection-overflow-item" /> So i've tested both values of treeCheckable prop and i guess this is the reason. Also 5.x version of Ant Design TreeSelect has the same behavior. I do not expect you to fix this bug in v4.24.12 but maybe you will suggest any solutions?

**Comment by aojunhao123** [comment]
WIP
