### ISSUE TITLE
Pagination 分页器- pageSize切换器的高度需要受 controlHeight token 影响

### ISSUE THREAD

**Issue by AnaniZhu** [ant-design/ant-design#51515]
### What problem does this feature solve?

可以统一分页器的高度

### What does the proposed API look like?

controlHeight token 可以改变 pageSize切换器的高度。现在整个分页组件只有这个控件不受影响，其他都受影响，在改了 controlHeight 的情况下很不协调

![image](https://github.com/user-attachments/assets/c90b39d1-b29b-47fd-b6b3-75421debf126)

**Comment by zombieJ** [comment]
https://stackblitz.com/edit/react-jbe7yh?file=demo.tsx

**Comment by zombieJ** [comment]
Pagination 是由多个组件组成的，所以如果你是直接改 `controlHeight` 都会生效。如果是改组件 Token 的话就需要把 Select 的也一并改了哈~

**Comment by AnaniZhu** [comment]
> Pagination 是由多个组件组成的，所以如果你是直接改 `controlHeight` 都会生效。如果是改组件 Token 的话就需要把 Select 的也一并改了哈~

但我期望的就是，只在分页器场景改 Select 的高度，其余场景的 select 应该还是原始高度。而且理论上 token 从设计上应该是集成的，我改 Pagination 的 `controlHeight`，那它下面的控件应该都生效，毕竟 `controlHeight` 中间有个单词是 `contro`。

按照你的说法，"Pagination 是由多个组件组成的"，`controlHeight` 只对自身生效的话，那 Pagination 下面的 Input 框也不应该受影响（但它的确受影响了）。

而且目前的现象是，我改了 Pagination 的 `controlHeight`，除了页码变小，跳页的输入框也变小了，只有下拉框没变小，这种更像是「下拉框 Select」遗漏了对这个 token 的消费。
