### ISSUE TITLE
Modal的footer中带图标的Button错位

### ISSUE THREAD

**Issue by xsjcTony** [ant-design/ant-design#51520]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/vitejs-vite-wqqfjz?file=src%2FApp.tsx)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/f2e41fe9-2bca-4f3f-8df4-70d6b1676c9b)

### What is expected?

在同一水平线上

### What is actually happening?

带图标的按钮会往上2个像素

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Chrome 130 |

---
是 `inline-flex` 导致的 https://github.com/ant-design/ant-design/pull/51381 没时间研究为啥

**Comment by afc163** [comment]
Introduced by https://github.com/ant-design/ant-design/pull/51381 @Wxh16144

**Comment by afc163** [comment]
不只在 Modal 中有问题。

<img width="516" alt="image" src="https://github.com/user-attachments/assets/875c96c2-16eb-4403-9e2c-4e9129a86b58">

**Comment by junlin365** [comment]
revert 了吗，按钮内用vertical-align: middle处理的文字、图片垂直居中也都不生效了

**Comment by li-jia-nan** [comment]
revert 之后今天可以发个 patch ？
