### ISSUE TITLE
Menu组件文本超出宽度被截断，没有省略

### ISSUE THREAD

**Issue by liz-gong** [ant-design/ant-design#51526]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-bdqztc-ktc7eb?file=demo.tsx)

### Steps to reproduce

打开重现链接，查看Menu侧边栏

### What is expected?

期望文本不被截断，可以出现省略号，鼠标hover上去出现完整的文案

### What is actually happening?

文本超出宽度 被截断了，有的还出现了多余的省略号

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3.4 |
| System | mac pro |
| Browser | 谷歌128.0.6613.120（正式版本） (arm64) |

---
看了一下可能是display：inline这个样式影响的，去掉这个样式可以正常展示

**Comment by iceweb1999** [comment]
同一个问题 https://github.com/ant-design/ant-design/issues/51361#issuecomment-2434111538，已经在修了

**Comment by coding-ice** [comment]
同一个问题 https://github.com/ant-design/ant-design/issues/51361#issuecomment-2434111538，已经在修了
