### ISSUE TITLE
use 'Tabs' components's  bug

### ISSUE THREAD

**Issue by jaune001** [ant-design/ant-design#5152]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

#### What do you expected?
no error when use 'Tabs' components

#### What happen?
when I upgrade antd-mobile@1.0.1

--error tips--
![image](https://cloud.githubusercontent.com/assets/19927938/23537442/1b2932ee-0007-11e7-9c5b-ae0e9659aa19.png)

#### Re-producible online demo
![image](https://cloud.githubusercontent.com/assets/19927938/23537429/044ecab6-0007-11e7-9cd2-25a943c3b637.png)

**Comment by benjycui** [comment]
Please create issue in right repo.
