### ISSUE TITLE
TreeSelect popup cut data

### ISSUE THREAD

**Issue by Dobroeutro1** [ant-design/ant-design#51547]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-ptlhrr?file=%2Findex.tsx%3A34%2C35)

### Steps to reproduce

Open many data in tree popup

### What is expected?

Data is not cutting

### What is actually happening?

Data is cutting

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.2.0 |
| System | Mac Os |
| Browser | Chrome |

**Comment by Dobroeutro1** [comment]
<img width="729" alt="image" src="https://github.com/user-attachments/assets/b9993c61-c562-4b09-a1f0-519be73455b9">

**Comment by Dobroeutro1** [comment]
<img width="710" alt="image" src="https://github.com/user-attachments/assets/defef088-e741-4702-8551-d6866c918a90">

**Comment by naor-navina** [comment]
@zombieJ 
This issue is still happening with 5.22.1
The only way I found that fixes it is virtual={false} but of course it makes everything slower.
It would be great to have a better solution, thanks 😄

**Comment by afc163** [comment]
@naor-navina Could you provide a codesandbox reproduce?
