### ISSUE TITLE
Table 的 datasource 中，数据的 children 字段会和 「expandedRowRender」发生量子纠缠

### ISSUE THREAD

**Issue by RaoHai** [ant-design/ant-design#51543]
### Reproduction link

[[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fervent-bird-nuzpr)](https://codesandbox.io/p/sandbox/kind-star-4wd522)

### Steps to reproduce

展开第一行，会发现子表格的 row 会在主表格中重复渲染。但是如果数据不放在 children 字段，而是其他字段，则不会有此效果

<img width="821" alt="image" src="https://github.com/user-attachments/assets/93614bef-4e89-4ddc-ba5e-4544f9ef9197">

### What is expected?

不与 children 字段发生量子纠缠

### What is actually happening?

-

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.0.0 |
| System | macOS |
| Browser | chrome |

**Comment by zombieJ** [comment]
代码和截图看起来不太一样

**Comment by RaoHai** [comment]
> 代码和截图看起来不太一样

已更新 https://codesandbox.io/p/sandbox/kind-star-4wd522

**Comment by zombieJ** [comment]
childrenColumnName

**Comment by afc163** [comment]
你需要 childrenColumnName 字段。

**Comment by RaoHai** [comment]
虽然但是。这个现象太难联想到 `childrenColumnName` 这个字段了。
