### ISSUE TITLE
日期时间选择组件的TS类型问题

### ISSUE THREAD

**Issue by ilxqx** [ant-design/ant-design#51548]
### Reproduction link

[https://www.abc.com/类型问题无需重现](https://www.abc.com/类型问题无需重现)

### Steps to reproduce

类型问题列表：
#### TimePicker 组件缺少泛型
当然缺少泛型参数不致命，致命的是 onChange 类型标注不正确，如下截图所示：
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/3e728529-3211-46f2-bf02-daf3166f5db8">
这里我无奈只能 `as any` 大法（实在是难受啊），要么把 `TimePicker` 组件泛型加上，要么把onChange的参数类型矫正正确，我推荐增加泛型，因为参数写死了 `Dayjs` 实例类型，万一用户使用的不是dayjs就尴尬了。。。

#### DatePicker 泛型优化问题
`DatePicker` 组件虽然已支持泛型，但是onChange属性的泛型没有利用好，如截图所示：
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/e2654ad2-bc8a-4127-94bc-3d5a5329b73c">
但是相比之下，value 属性的类型就很正确：
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/777f2073-26b7-4d89-84d6-3808e2a15b40">

### What is expected?

合理的TS类型

### What is actually happening?

TS类型混乱

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3.1 |
| System | MacOS最新 |
| Browser | Chrome最新 |

**Comment by ilxqx** [comment]
复现链接
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9

**Comment by afc163** [comment]
没发现问题。

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/0a84fb46-5780-410f-87cb-2336f46c6f91">

**Comment by ilxqx** [comment]
@afc163 抱歉，没有保存成功，这次就对了：
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-l548nm

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/a458e714-28b1-494e-824a-cdc372ca0215">

**Comment by ilxqx** [comment]
另外有个问题就是 TimePicker 组件不支持泛型，跟值相关的类型默认就全是 Dayjs 类型了，这个是不是不符合预期？万一有人用的是 Moment，那这个是不是就不对了？这个问题我用在线的那个复现不了，它解析复杂类型的能力好像很差（连DatePicker组件的泛型都识别不了，但实际DatePicker是有泛型的）。
TimePicker 和 DatePicker 他们我猜应该是都包了一个公用的组件，这个公用的组件是有泛型的，所以我推测应该是 TimePicker组件没有透传泛型导致的。

**Comment by ilxqx** [comment]
我找了一下源码，大概瞅了一下，确实是没有透传泛型，而是写死了 Dayjs 类型：
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/e96a0809-3675-4268-8c30-3c2b1bfb2c7b">

**Comment by afc163** [comment]
自定义日期库先参考一下 https://ant.design/docs/react/use-custom-date-library-cn ，也有 TS 类型的解法。
