### ISSUE TITLE
why we always need `callback()` in validator function at Form component? 为什么表单验证的 rules 中使用 validator 时，其方法体总是需要调用 callback()

### ISSUE THREAD

**Issue by TinkGu** [ant-design/ant-design#5155]
感谢提供 Form 等一系列组件。

# 问题描述
由于要在提交前，需要对表单内的各个 field 进行再次校验，使用了 `validateFieldsAndScroll`。但发现并未生效。

后来经调试，发现如果对该函数传入一组指定的 field，是可以生效的。但只要这组 fileds 中，包含了任意一个在校验规则中指定使用 `validator` 辅助校验的，则整个 `validateFields` 方法都不生效。

最后，才发现，是因为，我一开始并没有在对应的 `validator` 回调中，总是返回 `callback()` （觉得很多余，而且一开始不写也可以对单个 input 做正常校验）。加上以后就 ok 了。

# 疑惑
请问，这属于 bug 吗？ 因为文档中并没有指出，`validator` 中必须要返回 `callback()`。
如果确实是必须要返回 `callback` ，建议要在文档中提醒开发者注意，或者默认可以缺省。

# 代码片段
```javascript
handleSubmit = (e) => {
        e.preventDefault()

        const { onSubmit } = this.props
        const { validateFieldsAndScroll, getFieldsValue, resetFields } = this.props.form

        validateFieldsAndScroll((err, values) => {
              if (!err) {
                  onSubmit(getFieldsValue())
              }
        })
}
```

```javascript
handleConfirmPassword = (rule, value, callback) => {
        const { getFieldValue } = this.props.form
        if (value && value !== getFieldValue('newPassword')) {
            callback('两次输入不一致！')
        }

        // Note: 必须总是返回一个 callback，否则 validateFieldsAndScroll 无法响应
        callback()
 }
```

`render()`
```javascript
<FormItem
    {...formItemLayout}
    label="确认密码"
>
{
    getFieldDecorator('confirmPassword', {
           rules: [{
                  required: true,
                  message: '请再次输入以确认新密码',
            }, {
                  validator: this.handleConfirmPassword
            }],
    })(<Input type="password" />)
}
</FormItem>
```

# Environment

- antd version: 最新
- OS and its version: OS X
- Browser and its version: chrome 最新

**Comment by benjycui** [comment]
It's by designed: https://github.com/yiminghe/async-validator/

BTW, how does async-validator know an asynchronous procedure is end, if you don't use `callback` to notify it?

**Comment by afc163** [comment]
被人吐槽了 https://www.zhihu.com/question/33629737/answer/150154145

可以加一个文档说明，我们做开源的原则之一是兵来将挡水来土掩。

**Comment by afc163** [comment]
文档已更新。

**Comment by LukerSpringtree** [comment]
你好是否 这种用法 只能用 class 的写法?
能否用 纯函数的 写法 写 React Component .如果有,有没有案例啊?

**Comment by lianruhe** [comment]
你好！问一下异步校验怎么写？当请求回来我再 callback(),这时候已经校验完了，会认为我没有调callback()...

**Comment by neekey** [comment]
这个API设计真的是很不优雅，感受下我只是想做一下某个checkbox是否选中的检查：

```js
rules: [
            {
              message: 'You need to agree to our terms to sign up.',
              validator: (rule, value, cb) => (value === true ? cb() : cb(true)),
            },
          ],
```
并且给到callback的第一个参数是错误信息，和`message`也是冗余（虽然似乎只要返回任何东西都会使用`message`了，应该是`message` 覆盖了错误信息）。

大部分使用者预期的使用方式应该是直接返回`true`或者`false`来决定对错：

```js
rules: [
            {
              message: 'You need to agree to our terms to sign up.',
              validator: (rule, value, cb) => value === true,
            },
          ],
```

可用，但是还是建议优化这个API，即使用的是  https://github.com/yiminghe/async-validator/，但是ANT这边完成全可以在调用上封装一下

**Comment by afc163** [comment]
@neekey 可以去给 async-validator 提个兼容的 PR

**Comment by PeaFull** [comment]
请问为什么我自定义的校验方法只能进一次，控件中发生变化后就不再进入到校验方法了？
`{form.getFieldDecorator('messageContent', {
            rules: [
              { required: true},
              { validator: this.MessageContentValidator }
            ],
            validateTrigger: ['onBlur','onChange']
          })(
            <Ckeditor
              ckeditorName={'myCkeditor'}
              contentChange={this.getMessageContent}
              disabled={getDetailType==="view"}
              historyValue={historyMessageDetail.messageContent}
             />
          )}`

`MessageContentValidator=(rule:any, value:any, callback:any)=>{
    //只能进入一次
    if(this.state.formData.messageContent===""||this.state.formData.messageContent===undefined){
      callback("请输入消息内容！")
    }else{
      callback()
    }
  }`

**Comment by PeaFull** [comment]
请问为什么我自定义的校验方法只能进一次，控件中发生变化后就不再进入到校验方法了？

**Comment by petitspois** [comment]
@afc163 antd@2.12.x   
```js
<FormItem {...formItemLayout} label="确认密码">
     {
                                    getFieldDecorator('newPasswd2', {
                                        rules:[{
                                            required:true,
                                            min:6,
                                            message:'请再次输入以确认新密码！',
                                        },{
                                            validator: this.checkpwd
                                        }]
                                    })(
                                        <Input type="password" placeholder="输入您的新密码"></Input>
                                    )
                                }
                            </FormItem>                           
```
```js
checkpwd = (_rule:any, value:any, callback:(message:string)=>void) =>{
        const { getFieldValue } = this.props.form
        if (value && value !== getFieldValue('newPasswd')) {
            callback('两次密码输入不一致！')
        }
        callback('')
    }
```
![ce852657-1273-4b1f-b0f4-4d70ffc60ce4](https://user-images.githubusercontent.com/9461149/35315239-38f12948-0106-11e8-884b-16f356b82ff1.png)

之前是好好的。

**Comment by xiaoxiangmoe** [comment]
@neekey 这是为了有些异步的操作，还有为了支持不同的错误返回不同的message，有没有更好的方式啊？

**Comment by aliasese** [comment]
<Row>
                <Col span={24} key={"method"}>
                    <FormItem {...formItemMethodLayout} label="请求方法">
                        {getFieldDecorator("method", {
                            initialValue: this.state.data.method,
                            validateTrigger: "onChange",
                            rules: [{
                                required: true,
                                message: `请选择请求方法`
                            }, {
                                //validator: this.state.checkUnique ? this.checkConfirmMethod.bind(this) : (rule, value, callback) => {callback();},
                                validator: (这如何判断当前组件是否开始校验了) ？
 this.checkConfirmMethod.bind(this) : (如果不是当前组件开始校验，就调用其他函数),
                            }]
                        })(
                            <Select placeholder={"请选择请求方法"} onChange={::this.handleChange.bind(this)}>
                                {this.state.apiRequestMethodSelect}
                            </Select>
                        )}
                    </FormItem>
                </Col>
            </Row

**Comment by lcoder** [comment]
每次碰到函数的校验，都会来这里看一次，真的不好记

**Comment by jeffrey-fu** [comment]
### validator 函数
***

```
startNumValidator = (rule, value, callback) => {
    const { exportDataCount } = this.props;
    const reg = /^[1-9][0-9]*$/;
    let errors = [];
    if (!reg.test(value) || value > exportDataCount) {
      errors.push(new Error('illegal value'));
    }
    callback(errors);
  }
```
**不是统一callback errors么，也挺合理的啊感觉**
**不知道新版的antd开始区分异步和同步校验了没? validator(同步) asyncValidator(异步)**

**Comment by chiove** [comment]
在请求后，后台返回的回调里面怎么调用这个消息提示

**Comment by zerpor** [comment]
在使用rule中validator 做自定义校验，遇到一个问题
validateFunc = (rule, value, callback) => {
    if (true) {
      console.log(11);
      callback('Error message');
      return;
    }
    callback();
  };
callback执行后，'Error message'没有在对应的FormItem组件下显示，而是在控制台打印出来，这是为什么？

**Comment by aliasese** [comment]
**你`在对应的FormItem组件下显示`的逻辑是怎么书写的？**

**Comment by lcoder** [comment]
> @neekey 可以去给 async-validator 提个兼容的 PR

有人提了，yiminghe说，[反对。callback 更直接](https://github.com/yiminghe/async-validator/pull/133#issuecomment-434923373)。都9102年了，还用callback，坐等真香

**Comment by zerpor** [comment]
> **你`在对应的FormItem组件下显示`的逻辑是怎么书写的？**

我把自定义校验的方案改了，在onFieldsChange()中判断，不符合自定义的规则就直接改errors,然后就会在控件中显示error信息
`
onFieldsChange(props, changedFields) {
    const { dispatch, detail } = props;
const finalChangedFields = { ...changedFields };
    // 校验时间大小是否符合规则
    if (
      _.has(changedFields, 'currentDate') &&
      detail?.targetDate &&
      compareCurrentTimeEarlierThanTargetTime(
        finalChangedFields.currentDate,
        detail?.targetDate
      )
    ) {
      finalChangedFields.currentDate.errors = [
        {
          message: 'current Date should be latter than target Date',
          field: 'currentDate',
        },
      ];
    }
dispatch({
      type: 'controllerModel/saveDetail',
      payload: {
        changedFields: finalChangedFields,
        data: detail,
      },
    });
  }`

**Comment by jiufengdadi** [comment]
校验通过后下面的提示不消失是怎么回事

**Comment by mengdianliang** [comment]
问一个问题，这个validator能不能在页面加载的时候，不做校验？

**Comment by Kiiiwiii** [comment]
@neekey 
**must call a callback** feature is a big drawback in async situation:
```jsx
<Form>
          <Form.Item ...>
            {getFieldDecorator('name', {validator: (rule, value, callback) => setTimeout(callback(), 1000)})(
                <Input placeholder="name" />
            )}
          </Form.Item>
....
```
and before the setTimeout is fired, the whole component is unmounted. Then the timeout is fired, its callback is fired and <Form> component will use `setState`(I guess) which will result in the following error:
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

The callback is not cancellable ! No way to avoid this error !

**Comment by petitspois** [comment]
当删除某个错误key, 其他错误一直存在。 
```js
const remove = (k) => {
		const keys = getFieldValue('keys');
		setFieldsValue({
			keys: keys.filter(key => key !== k),
		});
	}
```
```js
const equality = (rule, value, callback) => {
		const deviceNo = getFieldValue('deviceNo');
		const curIndex = rule.field.slice(-2, -1);
		const other = deviceNo.filter((v, i) => i != curIndex);
		console.log(rule, deviceNo, other, value)
		if (!!value && other.some(v=>v == value)){
			callback('存在相同设备号')
		}
		callback();
	}
```
```js
getFieldDecorator(`deviceNo[${item}]`, {
	rules:[
	     {
		required:true,
		message:'请填写设备号'
	    },
	   {
		validator: equality
	   }
	]
})(
	<Input placeholder="请输入设备编号" />
)
```
当点击save 不会在触发 validator

**Comment by gxvv** [comment]
@jiufengdadi 
I encountered this problem.
My solution is pass `undefined` into the `callback`. The validator will pass when the first parameter of the `callback` is an empty array. And it set a default value to the parameter, so `undefined` is also work.

the `callback` definition: [L146](https://github.com/yiminghe/async-validator/blob/master/src/index.js#L146)

**Comment by k983551019** [comment]
为什么我自定义验证通过了 还出现async-validator: [""] ，

**Comment by LastStranger** [comment]
如果有两个校验的话,第一个会失效,为什么?
```
 rules: [
                {
                  required: true,
                  message: '请输入手机号',
                },
                {
                  validator: (rule, value, callback) => {
                    try {
                      if (this.props.form.getFieldValue('prefix') == 86 && value) {
                        const reg = /^1\d{10}$/;
                        if (!reg.test(value)) {
                          throw new Error('Something wrong!');
                        }
                      }
                    } catch (err) {
                      callback(err);
                    }
                  },
                  message: '请输入有效手机号',
                },
              ],

**Comment by yoyo837** [comment]
```js
 rules: [
                {
                  required: true,
                  message: '请输入手机号',
                },
                {
                  validator: (rule, value, callback) => {
                    try {
                      if (this.props.form.getFieldValue('prefix') == 86 && value) {
                        const reg = /^1\d{10}$/;
                        if (!reg.test(value)) {
                          throw new Error('Something wrong!');
                        }
                      }
                    } catch (err) {
                      callback(err);
                       return // +
                    }
                     callback() // +
                  },
                  message: '请输入有效手机号',
                },
              ],
```

**Comment by daweilun** [comment]
> 在使用rule中validator 做自定义校验，遇到一个问题
> validateFunc = (rule, value, callback) => {
> if (true) {
> console.log(11);
> callback('Error message');
> return;
> }
> callback();
> };
> 我想要校验结果'Error message'在对应的FormItem组件下显示，但是callback执行后，'Error message'没有在对应的FormItem组件下显示，而是在控制台打印出来，这是为什么？



> 在使用rule中validator 做自定义校验，遇到一个问题
> validateFunc = (rule, value, callback) => {
> if (true) {
> console.log(11);
> callback('Error message');
> return;
> }
> callback();
> };
> 我想要校验结果'Error message'在对应的FormItem组件下显示，但是callback执行后，'Error message'没有在对应的FormItem组件下显示，而是在控制台打印出来，这是为什么？

你解决了吗，遇到同个情况

**Comment by Composur** [comment]
> ```js
>  rules: [
>                 {
>                   required: true,
>                   message: '请输入手机号',
>                 },
>                 {
>                   validator: (rule, value, callback) => {
>                     try {
>                       if (this.props.form.getFieldValue('prefix') == 86 && value) {
>                         const reg = /^1\d{10}$/;
>                         if (!reg.test(value)) {
>                           throw new Error('Something wrong!');
>                         }
>                       }
>                     } catch (err) {
>                       callback(err);
>                        return // +
>                     }
>                      callback() // +
>                   },
>                   message: '请输入有效手机号',
>                 },
>               ],
> ```

message提示不会重复吗？'请输入手机号 请输入有效手机号' 类似这样

**Comment by k983551019** [comment]
> > ```js
> >  rules: [
> >                 {
> >                   required: true,
> >                   message: '请输入手机号',
> >                 },
> >                 {
> >                   validator: (rule, value, callback) => {
> >                     try {
> >                       if (this.props.form.getFieldValue('prefix') == 86 && value) {
> >                         const reg = /^1\d{10}$/;
> >                         if (!reg.test(value)) {
> >                           throw new Error('Something wrong!');
> >                         }
> >                       }
> >                     } catch (err) {
> >                       callback(err);
> >                        return // +
> >                     }
> >                      callback() // +
> >                   },
> >                   message: '请输入有效手机号',
> >                 },
> >               ],
> > ```
> 
> message提示不会重复吗？'请输入手机号 请输入有效手机号' 类似这样

不会

**Comment by jasonzhangdong** [comment]
![image](https://user-images.githubusercontent.com/13717586/68834155-16a43780-06f0-11ea-8add-36d0f887e17a.png)

做如下操纵
![image](https://user-images.githubusercontent.com/13717586/68834208-2de32500-06f0-11ea-94cb-b1c1c8c035f9.png)

为什么红色的校验还不消失呢？？？都满足规格了

**Comment by yoyo837** [comment]
rule的validator 成功失败与否都要调用callback，区别是传不传参数

**Comment by Ivan-hl** [comment]
> > 在使用rule中validator 做自定义校验，遇到一个问题
> > validateFunc = (rule, value, callback) => {
> > if (true) {
> > console.log(11);
> > callback('Error message');
> > return;
> > }
> > callback();
> > };
> > 我想要校验结果'Error message'在对应的FormItem组件下显示，但是callback执行后，'Error message'没有在对应的FormItem组件下显示，而是在控制台打印出来，这是为什么？
> 
> > 在使用rule中validator 做自定义校验，遇到一个问题
> > validateFunc = (rule, value, callback) => {
> > if (true) {
> > console.log(11);
> > callback('Error message');
> > return;
> > }
> > callback();
> > };
> > 我想要校验结果'Error message'在对应的FormItem组件下显示，但是callback执行后，'Error message'没有在对应的FormItem组件下显示，而是在控制台打印出来，这是为什么？
> 
> 你解决了吗，遇到同个情况

我也遇到了这个问题， 如果initialvalue为空， 在正常输入内容后通过onblur时间可以正常触发自定义校验器并有错误的情况下会进行提示， 但一旦初始initialvalue是有值的情况下， 在validatefields 进行所有表单组件统一校验时， err打印出来是null, 过了一会后 又会在控制台弹出校验失败， 自定义验证器是异步action

**Comment by wenk001** [comment]
我觉得你把函数里的return;删掉，再试一试，或许有用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ivan-hl"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 下午5:19
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "wk"<1109243952@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] why we always need `callback()` in validator function at Form component? 为什么表单验证的 rules 中使用 validator 时，其方法体总是需要调用 callback() (#5155)



  
在使用rule中validator 做自定义校验，遇到一个问题
 validateFunc = (rule, value, callback) =&gt; {
 if (true) {
 console.log(11);
 callback('Error message');
 return;
 }
 callback();
 };
 我想要校验结果'Error message'在对应的FormItem组件下显示，但是callback执行后，'Error message'没有在对应的FormItem组件下显示，而是在控制台打印出来，这是为什么？
   
在使用rule中validator 做自定义校验，遇到一个问题
 validateFunc = (rule, value, callback) =&gt; {
 if (true) {
 console.log(11);
 callback('Error message');
 return;
 }
 callback();
 };
 我想要校验结果'Error message'在对应的FormItem组件下显示，但是callback执行后，'Error message'没有在对应的FormItem组件下显示，而是在控制台打印出来，这是为什么？
  
你解决了吗，遇到同个情况
  
我也遇到了这个问题， 如果initialvalue为空， 在正常输入内容后通过onblur时间可以正常触发自定义校验器并有错误的情况下会进行提示， 但一旦初始initialvalue是有值的情况下， 在validatefields 进行所有表单组件统一校验时， err打印出来是null, 过了一会后 又会在控制台弹出校验失败， 自定义验证器是异步action

**Comment by CyberBunker** [comment]
太坑了

**Comment by rejunjie** [comment]
校验函数里面如果出现异常，没有任何提示。
坑了半天。。。

**Comment by kongling94** [comment]
我在想这个AntdV是不维护了么

**Comment by afc163** [comment]
@kongling94 ?

**Comment by l19861225q** [comment]
同样遇到这个问题，没下文了？

**Comment by runningvip** [comment]
`<a-input id="code" placeholder="请输入用户ID"v-decorator="[
                'code',
                {rules: [{ required: true, message: '请输入用户ID' }, { validator: handleUsername }], validateTrigger: 'change'}
              ]"
					>
					</a-input>`
`handleUsername(rule, value, callback) {
				value = value.trim()
				if (value.length == 0) {
					this.username = '';
					callback();
				} else {
					fetchUsername({
							code: value
						})
						.then((rest) => {
							if (rest.code == 200) {
								this.username = rest.data;
								//callback();
							} else {
								this.username = '';
								callback(new Error(rest.msg))
								return;
							}
						}).finally(() => {
							callback()
						})
				}
			},`
`<a-form :label-col="labelCol" :wrapper-col="wrapperCol" :form="form" @submit="handleSubmit">
     <a-button type="primary" htmlType="submit">确定</a-button>
</a-form>
`
点确定没有任何反应 不进行任何提示，在console 里面输入async-validator:["code is required"]
根本没有进validateFields 
去掉 validator 和 validateTrigger 点确定就会正常提示。
这是什么问题？

**Comment by Nicole1991** [comment]
> `<a-input id="code" placeholder="请输入用户ID"v-decorator="[ 'code', {rules: [{ required: true, message: '请输入用户ID' }, { validator: handleUsername }], validateTrigger: 'change'} ]" > </a-input>`
> `handleUsername(rule, value, callback) { value = value.trim() if (value.length == 0) { this.username = ''; callback(); } else { fetchUsername({ code: value }) .then((rest) => { if (rest.code == 200) { this.username = rest.data; //callback(); } else { this.username = ''; callback(new Error(rest.msg)) return; } }).finally(() => { callback() }) } },`
> `<a-form :label-col="labelCol" :wrapper-col="wrapperCol" :form="form" @submit="handleSubmit"> <a-button type="primary" htmlType="submit">确定</a-button> </a-form> `
> 点确定没有任何反应 不进行任何提示，在console 里面输入async-validator:["code is required"]
> 根本没有进validateFields
> 去掉 validator 和 validateTrigger 点确定就会正常提示。
> 这是什么问题？

请问你这个问题解决了吗？同样碰到了这个问题

**Comment by daweilun** [comment]
> > `<a-input id="code" placeholder="请输入用户ID"v-decorator="[ 'code', {rules: [{ required: true, message: '请输入用户ID' }, { validator: handleUsername }], validateTrigger: 'change'} ]" > </a-input>`
> > `handleUsername(rule, value, callback) { value = value.trim() if (value.length == 0) { this.username = ''; callback(); } else { fetchUsername({ code: value }) .then((rest) => { if (rest.code == 200) { this.username = rest.data; //callback(); } else { this.username = ''; callback(new Error(rest.msg)) return; } }).finally(() => { callback() }) } },`
> > `<a-form :label-col="labelCol" :wrapper-col="wrapperCol" :form="form" @submit="handleSubmit"> <a-button type="primary" htmlType="submit">确定</a-button> </a-form> `
> > 点确定没有任何反应 不进行任何提示，在console 里面输入async-validator:["code is required"]
> > 根本没有进validateFields
> > 去掉 validator 和 validateTrigger 点确定就会正常提示。
> > 这是什么问题？
> 
> 请问你这个问题解决了吗？同样碰到了这个问题
```
// 自定义密码校验
  handleConfirmPassword = (rule, value, callback) => {
    const { getFieldValue } = this.props.form;
    if (value && value !== getFieldValue('newPwd')) {
      callback('两次输入不一致！');
    }

    // Note: 必须总是返回一个 callback，否则 validateFieldsAndScroll 无法响应
    callback();
  };
我是这么解决的
```

**Comment by angle12138** [comment]
validatorFun(rule, value, callback) {
      const psw = this.form.getFieldValue('newPwd')
      if (value && value !== psw) {
        rule.message = '两次密码不一致'
        callback(rule)
      }
      callback()
    }

**Comment by RainLucky** [comment]
我遇到的问题是我使用了a-radio-group的，然后我只对其进行空值校验，因为有需求要在选择两个条件后发起请求，所以又对radio-group做了@change监听，两个单选组必须都选择了才发起请求，此时用@change来validate这两个条件值是否为空，一开始为空时，正常提示，后面两个值都不为空时不走validate().then()而是走的catch(error)为什么？而且console.log(error)打印出来的errorFields是空的，value显示两个校验字段都有值了，百思不得解。
![image](https://user-images.githubusercontent.com/24352122/113499412-6d5e1b80-9548-11eb-8b0c-cf33af5b9ba6.png)

`  <a-form
              :label-col="labelCol"
              :wrapper-col="wrapperCol"
              :scroll-to-first-error="true"
              name="form"
            >
              <a-form-item v-bind="validateInfos.radio1" label="条件1">
                <a-radio-group
                  name="radioGroup"
                  v-model:value=“radio1"
                  @change="onRadioChange()"
                >
               
                <a-radio value="001">ceshi1</a-radio>
                <a-radio value="002">ceshi2</a-radio>
                <a-radio value="003">ceshi3</a-radio>

                </a-radio-group>
              </a-form-item>

              <a-form-item v-bind="validateInfos.radio2" label="条件2">
                <a-radio-group
                  name="radioGroup2"
                  v-model:value="radio2"
                  @change="onRadioChange()"
                >
                  <a-radio value="1">1</a-radio>
                  <a-radio value="2">2</a-radio>
                
                </a-radio-group>
              </a-form-item>
            
              <a-form-item label="查询结果">
                <a-row>
                  <a-col span="14">
                    <span class="none_text">暂无信息</span>
                    <span class="enough">充足</span>
                    <span class="full">已满</span>
                  </a-col>
                  <a-col span="10" align="right" v-if="isAllowSignBtn">
                    <a-button
                      class="submit"
                      type="primary"
                      @click="onSubmit"
                      >提交</a-button
                    >
                  </a-col>
                </a-row>
              </a-form-item>
              
              <a-form-item
                label="图形验证码"
                v-bind="validateInfos.ImgCode"
              >
                <a-row>
                  <a-col :lg="8" :md="10" :sm="12"
                    ><a-input
                      v-model:value="ImgCode"
                      placeholder="请输入图形验证码"
                  /></a-col>
                  <a-col :lg="4" :md="5" :sm="6" style="top: -1px"
                    ><img
                      class="img_code"
                      v-bind:src="ImgSrc"
                      @click="onRefreshImg()"
                  /></a-col>
                </a-row>
              </a-form-item>
              
            </a-form>
            
            
   <script>
     // 校验规则
    const rulesRef = reactive({
      radio1: [
        {
          required: true,
          validator:async (rule, value) => {
    if (value === "") {
      return Promise.reject("条件1不能为空");
    } 
    else  {
      return Promise.resolve();
    }
  },
          trigger: "change",
          whitespace: true,
        },
      ],
      subId: [
        {
          required: true,
          validator:async (rule, value) => {
    if (value === "") {
      return Promise.reject("条件2不能为空");
    } 
    else  {
      return Promise.resolve();
    }
  },
          trigger: "change",
          whitespace: true,
        },
      ],
      ImgCode: [
        {
          required: true,
          validator: validateRule.validateImgCode,
          trigger: "change",
        },
      ]

    });

    const onSchoolIdChange = () => {
      validate(['radio1', 'radio2']).then(() => {
        console.log('校验通过，是否发起了查询');
     
      }).catch((error) =>{
      //控制台输出此信息，为什么？？
        console.log('onRadioChange error',error);
      })
    }
    
   const onSubmit = () => {
   console.log('点击了提交')
    validate().then(() => {
        console.log('radio1，radio2，ImgCode校验通过')
    }).catch((error) => {
        console.log('error',error);
    })
   }
   <script>`

**Comment by woshidashengtadie** [comment]
const money = (rule: any, value: any, callback:any) => { console.log(rule, value);callback('请输入合法金额数字') };

**Comment by woshidashengtadie** [comment]
<a-form-item
                    label="转账金额"
                    :name="['infor', 'money']"
                    :rules="[{ validator: money }]"
                    required
                >
                    <a-input class="flex-1" prefix="￥" v-model:value="formState.infor.money"></a-input>
                </a-form-item>

**Comment by woshidashengtadie** [comment]
<a-form-item
                    label="转账金额"
                    :name="['infor', 'money']"
                    :rules="[{ validator: money }]"
                    required
                >
                    <a-input class="flex-1" prefix="￥" v-model:value="formState.infor.money"></a-input>
                </a-form-item>    const money = (rule: any, value: any, callback:any) => { console.log(rule, value);callback('请输入合法金额数字') }     warning.js:6 Warning: `callback` is deprecated. Please return a promise instead.

**Comment by LSunnyCN** [comment]
我在提交前进行所有字段校验时报错，定位到是因为一个自定义校验，但不知道为什么会报错。
自定义校验
`<a-form-item label="联系电话">
          <a-input
            v-else
            v-decorator="['phoneNumber', {rules: [{required: true, min: 1, message: '联系电话不能为空！'}, {pattern: /^(1[3|4|5|6|7|8|9])[0-9]{9}$/, message: '手机号码格式错误！'}, {validator: phoneCheck}]}]"
          />
        </a-form-item>`
`async phoneCheck (rule, value, callbackFn) {
      const that = this
      await validatePhoneNumber(value).then(res => {
        if (that.userInfoParams.phoneNumber !== value && res.data) {
          callbackFn('该手机号已被使用，请修改后重试！')
          return false
        }
      })
      await callbackFn()
    }`
提交后的校验
`form.validateFields((errors, values) => {})`
error信息
```
{
    "phoneNumber": {
        "expired": true,
        "errors": [
            {
                "message": "phoneNumber need to revalidate",
                "field": "phoneNumber"
            }
        ]
    }
}
```

**Comment by BoBoooooo** [comment]
> 这个API设计真的是很不优雅，感受下我只是想做一下某个checkbox是否选中的检查：
> 
> ```js
> rules: [
>             {
>               message: 'You need to agree to our terms to sign up.',
>               validator: (rule, value, cb) => (value === true ? cb() : cb(true)),
>             },
>           ],
> ```
> 
> 并且给到callback的第一个参数是错误信息，和`message`也是冗余（虽然似乎只要返回任何东西都会使用`message`了，应该是`message` 覆盖了错误信息）。
> 
> 大部分使用者预期的使用方式应该是直接返回`true`或者`false`来决定对错：
> 
> ```js
> rules: [
>             {
>               message: 'You need to agree to our terms to sign up.',
>               validator: (rule, value, cb) => value === true,
>             },
>           ],
> ```
> 
> 可用，但是还是建议优化这个API，即使用的是 [https://github.com/yiminghe/async-validator/，但是ANT这边完成全可以在调用上封装一下](https://github.com/yiminghe/async-validator/%EF%BC%8C%E4%BD%86%E6%98%AFANT%E8%BF%99%E8%BE%B9%E5%AE%8C%E6%88%90%E5%85%A8%E5%8F%AF%E4%BB%A5%E5%9C%A8%E8%B0%83%E7%94%A8%E4%B8%8A%E5%B0%81%E8%A3%85%E4%B8%80%E4%B8%8B)

2023年了。。请问这个 validator: ()=> boolean的方法有计划支持么。。

**Comment by liebodyuebai** [comment]
> 我在提交前进行所有字段校验时报错，定位到是因为一个自定义校验，但不知道为什么会报错。 自定义校验
> 
> ```
> <a-form-item label="联系电话">
>           <a-input
>             v-else
>             v-decorator="['phoneNumber', {rules: [{required: true, min: 1, message: '联系电话不能为空！'}, {pattern: /^(1[3|4|5|6|7|8|9])[0-9]{9}$/, message: '手机号码格式错误！'}, {validator: phoneCheck}]}]"
>           />
>         </a-form-item>
> ```
> 
> ```
> async phoneCheck (rule, value, callbackFn) {
>       const that = this
>       await validatePhoneNumber(value).then(res => {
>         if (that.userInfoParams.phoneNumber !== value && res.data) {
>           callbackFn('该手机号已被使用，请修改后重试！')
>           return false
>         }
>       })
>       await callbackFn()
>     }
> ```
> 
> 提交后的校验 `form.validateFields((errors, values) => {})` error信息
> 
> ```
> {
>     "phoneNumber": {
>         "expired": true,
>         "errors": [
>             {
>                 "message": "phoneNumber need to revalidate",
>                 "field": "phoneNumber"
>             }
>         ]
>     }
> }
> ```

解决了么
