### ISSUE TITLE
Support variant in `Radio.Button`

### ISSUE THREAD

**Issue by drizzlesconsin** [ant-design/ant-design#51553]
### What problem does this feature solve?

It would be great if the Radio.Button component could support a variant property to toggle between different style options. For example, using `variant="outlined"` or `variant="filled"` to choose the button style. This would increase the component’s flexibility and meet more UI requirements.

<img width="421" alt="s_2024-11-09_17-18-33" src="https://github.com/user-attachments/assets/40380e59-14c3-4c3c-a147-ae0ba78df05f">

### What does the proposed API look like?

```tsx
<Radio.Group variant="filled" defaultValue="a" buttonStyle="solid">
  <Radio.Button value="a">Hangzhou</Radio.Button>
  <Radio.Button value="b">Shanghai</Radio.Button>
  <Radio.Button value="c">Beijing</Radio.Button>
  <Radio.Button value="d">Chengdu</Radio.Button>
</Radio.Group>
```

**Comment by zombieJ** [comment]
Are you looking for [Segmented](https://ant.design/components/segmented) ?

**Comment by drizzlesconsin** [comment]
emmm...Although it visually resembles the Segmented component, using Radio.Button with a global variant="filled" configuration in forms makes the overall appearance feel inconsistent.

**Comment by zombieJ** [comment]
Even the variant to support filled, I guess it's still not same as your snapshot above. It's more like:

<img width="290" alt="截屏2024-11-13 17 37 53" src="https://github.com/user-attachments/assets/b5d4875d-f17a-4b45-b291-665f8cb1c761">

**Comment by drizzlesconsin** [comment]
If it looked like your screenshot, that would be better—at least it wouldn’t have a border.

**Comment by afc163** [comment]
https://ant.design/components/segmented is the one.
