### ISSUE TITLE
table 开启虚拟滚动后，滚动条过几秒消失了 

### ISSUE THREAD

**Issue by weilun0510** [ant-design/ant-design#51552]
### Reproduction link

[https://ant-design.antgroup.com/~demos/table-demo-virtual-list](https://ant-design.antgroup.com/~demos/table-demo-virtual-list)

### Steps to reproduce

官网虚拟列表demo即可复现。
![image](https://github.com/user-attachments/assets/c6b99296-965f-4d83-9e94-f2d9dbc00edb)
当我在表格中随意点击或不点击时，过了2s左右滚动条就消失了。这时候我只能将光标移出表格再移进来，滚动条才会出现。我希望光标在表格中时滚动条不会消失

### What is expected?

滚动条不消失

### What is actually happening?

滚动条消失了

| Environment | Info |
| --- | --- |
| antd | 5.20.3 |
| React | react |
| System | windows |
| Browser | chrome  130.0.6723.117 |

**Comment by weilun0510** [comment]
@petercat-assistant 你们官网也有这个问题

**Comment by liyou-Leo** [comment]
这个问题我看还是存在呀，横向滚动条自动消失；

**Comment by weilun0510** [comment]
> 这个问题我看还是存在呀，横向滚动条自动消失；

试试 ProTable

**Comment by liyou-Leo** [comment]
> > 这个问题我看还是存在呀，横向滚动条自动消失；
> 
> 试试 ProTable

我这边不太好换Table组件，最终通过样式强行展示滚动条不让其消失....

<img width="806" height="513" alt="Image" src="https://github.com/user-attachments/assets/2a239024-f2f7-473c-96be-67706f56ae41" />
