### ISSUE TITLE
modal的静态方法也能够支持 mousePosition 属性

### ISSUE THREAD

**Issue by tgxpuisb** [ant-design/ant-design#51569]
### What problem does this feature solve?

Modal组件允许类似`<Modal mousePosition={{x: 300, y:300}}/>`的属性来控制动画的初始位置，这个Feature是该 https://github.com/ant-design/ant-design/issues/38571 中新增的

但是使用`useModal`和`modal.confirm`时，传入`mousePosition`时Typescript不会报错，实际在`ConfirmDialog.js`文件的render过程中并未透传`mousePosition`属性，造成两者表现不一致

### What does the proposed API look like?

期望`Modal`的静态方法和`useModal`返回的`modal`能够支持 `mousePosition`的透传

```
const [modal, contextHolder] = Modal.useModal();

modal.confirm({
  mousePosition: {x: 300, y: 300}
})
```

**Comment by zombieJ** [comment]
hooks 感觉可以加，静态方法就别了。静态方法一些功能不支持是刻意的。

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/51576

Waited for next minor version.
