### ISSUE TITLE
[popover] any way to not trigger onOpenChange when click the children element 

### ISSUE THREAD

**Issue by congjiujiu** [ant-design/ant-design#51568]
### What problem does this feature solve?

When set the popover/tooltip trigger to "click", it will trigger show/hide action each time i click the children. however sometimes i dont want it to trigger it especially when i control the status with `open & onOpenChange`.

For example, wrap the `Popover` with an `Input` component, whenever i click the input means i want to show the popover, but it will trigger the `hide` action the second time i click `Input`.

So, how about pass the event parameter in `onOpenChange`, i found you guys already add the type definition but nothing really passed.

```
export interface PopoverProps extends AbstractTooltipProps {
    onOpenChange?: (open: boolean, e?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLDivElement>) => void;
}
```

or just any other workarounds?

### What does the proposed API look like?

```
onOpenChange?: (open: boolean, e?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLDivElement>) => void
```

**Comment by zombieJ** [comment]
You can HOC the Popover to filter it:

https://stackblitz.com/edit/react-zvbqw8?file=demo.tsx
