### ISSUE TITLE
Collapse Item font color is overridden when style or class are provided

### ISSUE THREAD

**Issue by Tuhama** [ant-design/ant-design#51572]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-iss27f?file=demo.tsx)

### Steps to reproduce

just provide a style with any color 

### What is expected?

the text should be colored

### What is actually happening?

default text color for text

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | win 11 |
| Browser | chrome |

---
 other styling is working (ex: fontWeight)

**Comment by IsKaros** [comment]
check the annotation of the ItemType plz.I am sorry that i don't see the `style` prop but the `styles` prop。
![image](https://github.com/user-attachments/assets/256ecef9-b2d2-4877-b90d-f789e329370a)

**Comment by IsKaros** [comment]
![image](https://github.com/user-attachments/assets/666c8889-e90b-42bc-83f0-281c959324d1)

**Comment by Tuhama** [comment]
I think it's still an issue since some styles were applied and some not.
and the same problem is for "className" and "classNames".

**Comment by Tuhama** [comment]
> ![image](https://private-user-images.githubusercontent.com/45893455/384851513-666c8889-e90b-42bc-83f0-281c959324d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzMxMzAsIm5iZiI6MTczMTMzMjgzMCwicGF0aCI6Ii80NTg5MzQ1NS8zODQ4NTE1MTMtNjY2Yzg4ODktZTkwYi00MmJjLTgzZjAtMjgxYzk1OTMyNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDEzNDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YmRiMGZkMjgzN2I2NzE4OTY3NzA2NWIzN2I0MzdjZDhkYzhkZGFkYjllNzMwYzBkYmRmODRlZWVlNDk2YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fXdTQDhjhnegZBUAijQHvjojrJ3RA0Zx8-jp2R4nYcs)

**Comment by Tuhama** [comment]
![image](https://github.com/user-attachments/assets/100d4766-1f0a-4965-9776-b589097b0915)

**Comment by IsKaros** [comment]
![image](https://github.com/user-attachments/assets/fbe2509c-d70f-4d8a-bd55-5f0198196672)
The prop `classNames`  takes effect, but it seems that the priority of the className you have added  is not high enough.

**Comment by Tuhama** [comment]
exactly, that's why I said the color is "overridden", is it an intended behavior?

**Comment by afc163** [comment]
You should handle the priority of css selector properly.
