### ISSUE TITLE
Form.useForm的参数为什么没有在文档中体现？

### ISSUE THREAD

**Issue by AlanQtten** [ant-design/ant-design#51575]
### What problem does this feature solve?

看源码useForm是可以传入一个FormInstance的，但官方文档中这个hook的类型并没有体现这一点，是出于什么原因不希望外侧这样调用吗，还是文档的遗漏？

### What does the proposed API look like?

和ts保持一致即可

**Comment by zombieJ** [comment]
[FAQ: 官方文档中没有提供的隐藏 API 我可以使用吗？](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)
