### ISSUE TITLE
Select wrapped in Form.Item with hasFeedback and no status has incorrect clear icon placement

### ISSUE THREAD

**Issue by nking07049925** [ant-design/ant-design#51577]
### Reproduction link

https://codepen.io/nking07049925/pen/RwXELxv

### Steps to reproduce

Wrap a `<Select allowClear />` in `<Form.Item hasFeedback>` and no status, set a value and hover over the input

### What is expected?

The close icon is drawn on top of the select arrow icon
![image](https://github.com/user-attachments/assets/9858bb9c-0e6c-4460-9615-4490cd4ee018)

### What is actually happening?

The close icon is drawn to the left of the select arrow icon
![image](https://github.com/user-attachments/assets/c92509d9-543b-4a58-95a0-428084e1d366)

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | Win11 |
| Browser | Microsoft Edge 130.0.2849.80 Chromium version 130.0.6723.117 |

---
We noticed this issue when migrating our project from antd4 to antd5

Same codepen in antd4, where this works correctly    
https://codepen.io/nking07049925/pen/jOgXGvM

hasFeedback is set to true with no status as per https://github.com/ant-design/ant-design/issues/34458#issuecomment-1066313811 to avoid issues with focus on inputs with validation when status has to be set

**Comment by afc163** [comment]
It is by designed, otherwise feedback icon will overlap with clear icon when form validation is invalid.

<img width="472" alt="图片" src="https://github.com/user-attachments/assets/e3e76b7d-da90-41ab-be16-60752ec492f3">

**Comment by nking07049925** [comment]
> It is by designed, otherwise feedback icon will overlap with clear icon when form validation is invalid.
> 
> <img alt="图片" width="472" src="https://private-user-images.githubusercontent.com/507615/384956262-e3e76b7d-da90-41ab-be16-60752ec492f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzU1ODcsIm5iZiI6MTczMTMzNTI4NywicGF0aCI6Ii81MDc2MTUvMzg0OTU2MjYyLWUzZTc2YjdkLWRhOTAtNDFhYi1iZTE2LTYwNzUyZWM0OTJmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxNDI4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjZjZDI4YTY3YThlYjhhMTI4ZGZmYzEwNTBmMDAyOWE5ZjEwOWQ5YjUyZDRhMzNmNzc1OGE1YjM3NzVmYTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MDI-foNBd5i_nA-sSz36fmnIQqjZ3R07YNKd3Opy8lM">

In antd4 this was not the case when validation status is empty (so no validation icon is displayed) and as discussed in https://github.com/ant-design/ant-design/issues/20927 the clear icon overlapping the select arrow icon is an intentional design choice

**Comment by nking07049925** [comment]
https://codepen.io/nking07049925/pen/OJKrzao

![image](https://github.com/user-attachments/assets/50627fd1-f9b9-43f7-a4e6-ed4dcb079693)
