### ISSUE TITLE
Too few attributes can be set by the sense tree，can set custom attributes？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#5157]

**Comment by afc163** [comment]
Why do you need custom attributes?

**Comment by aw6658913** [comment]
For example, access to the parent node is through the cycle, if you can customize the property, I can put the parent node inside the custom attributes, of course, this is just an example, a lot of time API several attributes are not enough

**Comment by aw6658913** [comment]
The bottom of the tree in the rendering of the data into the field directly into it, so that the custom is feasible?Now click on the tree can only get the settings of these properties feel not enough。
![image](https://cloud.githubusercontent.com/assets/19485727/23545349/f63a9264-0035-11e7-84d0-3a380181d3b3.png)

**Comment by afc163** [comment]
You mean this? http://codepen.io/anon/pen/bqpKEV?editors=0010

**Comment by aw6658913** [comment]
yes,this makes the tree more flexible

**Comment by afc163** [comment]
So, it is supported now.

**Comment by aw6658913** [comment]
Can this be? Sorry, I do not it is supported, I see other people to find the parent node is a cycle tree。I'll try

**Comment by aw6658913** [comment]
Thanks. It's feasible
