### ISSUE TITLE
Select: the problem of rendering the list after changing the zoom in the browser

### ISSUE THREAD

**Issue by Alyona94** [ant-design/ant-design#51578]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

1. open the Select; 
2. scroll to the end of the list; 
3. close the Select; 
4. change the zoom in the browser; 
5. open the Select;

This problem is also observed on the component documentation pages [Select](https://ant.design/components/select) . 

### What is expected?

Correctly rendered content

### What is actually happening?

The content is rendered incorrectly

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | React ^18 |
| System | win 10, 11 |
| Browser | chrome |

### Screenshot
![Снимок экрана 2024-11-11 192311](https://github.com/user-attachments/assets/b07176e8-e68a-43ad-a6e6-da153f0cb212)

**Comment by zombieJ** [comment]
Thanks for feedback. Zoom browser in using is not a normal behavior but resolve to check the size change will cause performance issue. We may not help to resolve this.
