### ISSUE TITLE
Select with multiple and responsive maxTagCount broken 

### ISSUE THREAD

**Issue by gustavoFKGrupo** [ant-design/ant-design#51581]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/responsive-maxtagcount-antd-5-22-0-forked-m2c4n4?workspaceId=0cee2eec-d865-421c-82c0-7e8ae1e4eda4)

### Steps to reproduce

Choose one option in select

### What is expected?

Display the selected options

### What is actually happening?

The options are not being displayed

| Environment | Info |
| --- | --- |
| antd | 5.22.0 |
| React | 18.0.0 |
| System | Win11 |
| Browser | Chrome |

**Comment by IsKaros** [comment]
the type of prop`maxTagCount` is Number. Therefore, use number 3 instead of string '3' plz.

**Comment by raindrop93** [comment]
使用官方 demo，将默认的多选取消再进行选择就会有问题，下拉框中选项是选中的，但是选择框是空的。
https://ant.design/components/select-cn#select-demo-responsive
![image](https://github.com/user-attachments/assets/05cf136a-4492-4f2e-8011-7084374e3307)

**Comment by balboFK** [comment]
Can confirm the problem here too. If responsive is not available for use anymore, it should be removed from the docs and Typescript types.

**Comment by balboFK** [comment]
> the type of prop`maxTagCount` is Number. Therefore, use number 3 instead of string '3' plz.

@IsKaros test it with "responsive" instead of a set number, it does not work aswell.

**Comment by zombieJ** [comment]
Pls feel free to upgrade to `5.22.1` which has fixed this : )

**Comment by thinkasany** [comment]
fixed by https://github.com/ant-design/ant-design/pull/51605
