### ISSUE TITLE
In the case of code-spliting，babel-plugin-import leads to commonChunks unnormal

### ISSUE THREAD

**Issue by yesuanzao** [ant-design/ant-design#5159]
#### Environment

- antd version:  1.11.6
- OS and its version:  mac
- Browser and its version:  chrome
- webpack: 2.2.1

#### problem
I'm using code-spliting, I expect antd will be bundled to commonChunks instead of everywhere
```
"plugins": [
   ["import", { "libraryName": "antd", "style": true}]
]
```

```
new webpack.optimize.CommonsChunkPlugin({
  name: 'vender',
  children: true,
  minChunks: 2,
  async: true
}),
```
in the condition of babel-plugin-import，
![wechatimg9](https://cloud.githubusercontent.com/assets/10268293/23584104/e7ac906e-0191-11e7-82aa-8953c44e8e0c.jpeg)

not babel-plugin-import，
![wechatimg8](https://cloud.githubusercontent.com/assets/10268293/23584107/f6dc3d8c-0191-11e7-96d8-06d23ea046d3.jpeg)

Compare two parts, the latter meets expectations. Antd has been bundled to main.js instead of other chunks. so what is wrong with the babel-plugin-import?

**Comment by benjycui** [comment]
Could you highlight differences between these cases?

And what is your expected behavior.

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by afc163** [comment]
I think you should propose this to https://github.com/ant-design/babel-plugin-import
