### ISSUE TITLE
RangePicker 弹窗后上方的三角形箭头位置错位

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#51592]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-spbclj?file=demo.tsx)

### Steps to reproduce

打开重现链接就可以看到，在日期面板被挤到左边的时候，三角形箭头没有移动到右边去。

### What is expected?

根据面板位于输入框的左右两边动态确定三角形箭头的位置

### What is actually happening?

在日期面板被挤到左边的时候，三角形箭头没有移动到右边去

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | react 18 |
| System | window 10 |
| Browser | Chrome 123.0.6312.86 |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/51071
