### ISSUE TITLE
请求更改文档的显示逻辑，每次看文档要等半天加载，别的文档都可以点开就能看到内容

### ISSUE THREAD

**Issue by LanHuangJG** [ant-design/ant-design#51599]
### What problem does this feature solve?

文档能直接被看到而不是需要等待加载

### What does the proposed API look like?

文档能直接被看到而不是需要等待加载

**Comment by LanHuangJG** [comment]
![image](https://github.com/user-attachments/assets/ef07cadc-4c28-4126-9ec7-733e07313dc7)

**Comment by LanHuangJG** [comment]
这个问题非常困扰我，会打断我的开发思路

**Comment by LanHuangJG** [comment]
非常感谢开发团队

**Comment by afc163** [comment]
你需要国内镜像：https://ant-design.antgroup.com/

**Comment by Elaine87** [comment]
以前都能迅速打开，现在怎么科学都不行，是官网换了技术栈了吗？国内的镜像也不行，更慢

**Comment by zombieJ** [comment]
我这边使用镜像很快，但是 chunk 的确比较多可能会导致网络拥堵。我改一下配置试试：
https://github.com/ant-design/ant-design/pull/51604

**Comment by yoyo837** [comment]
别的很多文档站点可能只是纯文档和code 示例，没有demo跑

**Comment by liuchuzhang** [comment]
@afc163 @zombieJ 现在还是慢，我看有的时候 network 里没有任何 chunk 和请求在加载了，它还是要继续显示骨架屏一段时间

**Comment by afc163** [comment]
https://ant-design.antgroup.com/components/table-cn 比 https://ant.design/components/table-cn 慢很多，有问题。

<img width="1784" alt="图片" src="https://github.com/user-attachments/assets/9c52b32f-9e3c-4aa8-99be-12b5fda4d7b2">

**Comment by liuchuzhang** [comment]
https://ant.design/components/table-cn 今天这个样子就比较快了，前几天还挺慢的

**Comment by liuchuzhang** [comment]
sorry, 我点新组件还是慢，有缓存

**Comment by gin-lsl** [comment]
我发现加载了上百个 SVG，不知道是否与这个有关：
![image](https://github.com/user-attachments/assets/453d0592-35b0-401a-acb3-ca70d389e2bf)

**Comment by LanHuangJG** [comment]
> 别的很多文档站点可能只是纯文档和code 示例，没有demo跑

感觉可以不需要demo的，或者默认是没有demo，给个按钮让用户选择是否需要demo，直接纯文档和code示例的话，文档显示的速度会快很多

**Comment by afc163** [comment]
https://ant-design.antgroup.com/components/table-cn 已经解决了水合失败的问题，现在打开很快了。

**Comment by liuchuzhang** [comment]
很快了👍
