### ISSUE TITLE
Multiple `Progress` colors with tooltips

### ISSUE THREAD

**Issue by nikzanda** [ant-design/ant-design#51597]
### What problem does this feature solve?

Currently, the Progress component can only display 2 several parts with different status (example [here](https://ant.design/components/progress#progress-demo-segment)). I believe it would be very useful to enhance the component by adding the ability to display more states with different colors.
Additionally, it would be even better if a tooltip could be displayed when hovering over each status.

Introducing these features would eliminate the need to install additional libraries, such as [Ant Design Charts](https://ant-design-charts.antgroup.com/en), which lacks a simple "Progress" component like the one found in Ant Design.

### What does the proposed API look like?

<img width="468" alt="Screenshot 2024-11-12 at 14 29 18" src="https://github.com/user-attachments/assets/cbe9d958-10ec-4a83-8b16-b8cba8218f6d">

```tsx
<Progress
    percent={60}
    statuses={[
        { tooltip: 'success status', color: 'green', percent: 40 },
        { tooltip: 'danger status', color: 'red', percent: 10 },
        { tooltip: 'warning status', color: 'orange', percent: 10 }
    ]}
/>
```

**Comment by zombieJ** [comment]
Thanks for feedback. But we are trying to avoid make Progress to be a chart lib, since it may have lots of requirement. So we only follow the basic design from the designer.

Sorry again

**Comment by nikzanda** [comment]
> Thanks for feedback. But we are trying to avoid make Progress to be a chart lib, since it may have lots of requirement. So we only follow the basic design from the designer.
> 
> Sorry again

I agree that we shouldn't turn the Progress component into a chart library. My suggestion is to simply add the ability to include multiple states/colors to increase flexibility, without adding animations or additional controls. A straightforward example can be seen in Bootstrap [here](https://getbootstrap.com/docs/4.0/components/progress/#multiple-bars).

@zombieJ  If this feature request isn't implemented, do you have any suggestions on how to achieve the desired result while maintaining the Ant Design layout?
