### ISSUE TITLE
select 配置  maxTagCount="responsive" 时，选项无法正常回显

### ISSUE THREAD

**Issue by AnaniZhu** [ant-design/ant-design#51607]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-h8y7nj)

### Steps to reproduce

下拉框随便选中任意选项

### What is expected?

无法回显选项

### What is actually happening?

正常回显选项

| Environment | Info |
| --- | --- |
| antd | 5.22.0 |
| React | 18 最新 |
| System | mac |
| Browser | chrome |

**Comment by iPuppyG** [comment]
I encountered the same problem today

**Comment by iPuppyG** [comment]
I encountered the same problem today

**Comment by MingwieJin** [comment]
> me too, v5.22.0

fied at v5.22.1 
https://github.com/ant-design/ant-design/pull/51605
