### ISSUE TITLE
Modal.method() needs to support afterOpenChange 

### ISSUE THREAD

**Issue by hungtcs** [ant-design/ant-design#51606]
### What problem does this feature solve?

https://stackblitz.com/edit/react-9cqkwb?file=demo.tsx,index.tsx

Perform some operations on the dom inside the modal, for example, let input get focus

### What does the proposed API look like?

```tsx
modal.confirm({
    afterClose: () => {
      console.log('after close...');
    },
    // new props
    afterOpenChange: (open) => {
      console.log('after open change,,,', { open });
    },
  });
```

**Comment by DDDDD12138** [comment]
Awaiting feature outcome: #51576

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/51576

Waited for next minor version.
