### ISSUE TITLE
Select组件为什么把输入值作为option的一项，怎么取消，现在只能通过dropdownRender，但是很繁琐

### ISSUE THREAD

**Issue by huangnan20030709** [ant-design/ant-design#51613]
### What problem does this feature solve?

取消输入的搜索值作为options的第一项

### What does the proposed API look like?

取消输入的搜索值作为options的第一项

**Comment by afc163** [comment]
你要实现的具体需求是什么样的？

**Comment by huangnan20030709** [comment]
> 你要实现的具体需求是什么样的？

不要展示searchValue作为options的第一项，

**Comment by huangnan20030709** [comment]
> 你要实现的具体需求是什么样的？

![image](https://github.com/user-attachments/assets/befb9aea-2354-4652-a5ad-781136d03956)
之前做成受控组件很繁琐，现在只需要不展示searchValue这一项就行

**Comment by DDDDD12138** [comment]
你是添加了自动分词的功能吧？`tokenSeparators` 把这个去掉试试

**Comment by huangnan20030709** [comment]
![image](https://github.com/user-attachments/assets/99a87273-939b-4506-9714-6dbd8a41df96)
是多选模式，然后可以输入searchValue

**Comment by DDDDD12138** [comment]
设置 `mode="multiple"` 试试

**Comment by huangnan20030709** [comment]
谢谢谢谢谢谢谢谢谢谢，这，上次也因为这还大费周张

**Comment by zombieJ** [comment]
嗯呢，`tags` 允许输入即添加，`multiple` 只允许选择。

**Comment by DDDDD12138** [comment]
> 嗯呢，`tags` 允许输入即添加，`multiple` 只允许选择。

确实容易混淆，感觉是不是可以在文档中说明一下区别？

**Comment by huangnan20030709** [comment]
> > 嗯呢，`tags` 允许输入即添加，`multiple` 只允许选择。
> 
> 确实容易混淆，感觉是不是可以在文档中说明一下区别？

这段解释可以，
