### ISSUE TITLE
drag some element into tree component

### ISSUE THREAD

**Issue by alanwei0** [ant-design/ant-design#5161]
i wrap the `Tree` component to a folder navigator, and i have some files(maybe a img element) outside the tree. how can i drag the `img` element into the tree??

i make a (demo)[http://codepen.io/alanwei0/pen/RpaJmr?editors=0010], but i failed with error.

is there any approach???

**Comment by benjycui** [comment]
I remember that this feature had been requested before, but I cannot find that issue.

**Comment by warmhug** [comment]
Ref https://github.com/react-component/tree/issues/8 ,not yet implemented.

**Comment by alanwei0** [comment]
is that say i have to code a tree totally, or i can override some code to achieve this function?

**Comment by afc163** [comment]
We don't have plan to support this now.
