### ISSUE TITLE
官网文档，组件DatePicker部分，看不到API

### ISSUE THREAD

**Issue by zmbxy** [ant-design/ant-design#51628]
### What problem does this feature solve?

打开官网文档，组件DatePicker部分，不显示API部分内容。
<img width="1804" alt="image" src="https://github.com/user-attachments/assets/99b90af5-aa5d-41d5-860b-42ddf2761d16">

### What does the proposed API look like?

可以正常显示API部分

**Comment by afc163** [comment]
请访问：https://ant.design/components/date-picker-cn

**Comment by li-jia-nan** [comment]
切换到 design tab 了？
![image](https://github.com/user-attachments/assets/061acfcd-d79d-45d2-a831-d0eb4fe51434)
