### ISSUE TITLE
Help needed to customize theme for a barebones boilerplate app

### ISSUE THREAD

**Issue by lionkeng** [ant-design/ant-design#5163]
#### Environment(required)

- antd version: 2.7.4
- OS and its version: Any OS
- Browser and its version: Any browser

#### What did you do? Please provide steps to re-produce your problem.
I am putting together a barebones boilerplate app [here](https://github.com/lionkeng/bare-ant) using ant-design and a few other tools. I am installing ant-design as a package via webpack. 

I am having trouble implementing customization of the ant design theme.

I am doing something simple, overriding the primary color.

#### What do you expected?
I have followed the discussions at issue #4822 and #4915. I have added the `webpack` configuration changes to process the `less` and `css` code separately.
https://github.com/lionkeng/bare-ant/blob/master/webpack.config.js#L6-L8
https://github.com/lionkeng/bare-ant/blob/master/webpack.config.js#L66-L74

But it doesn't seem to be working. When I set `style` to `true` for `babel-plugin-import` in my `.babelrc` to `true`, webpack compiles, but the app loses all of ant design's style/CSS.

Would appreciate some guidance here. Many thanks!

**Comment by afc163** [comment]
https://github.com/lionkeng/bare-ant/pull/1
