### ISSUE TITLE
CSS Variables not loaded when components aren't directly used

### ISSUE THREAD

**Issue by mehmetdemiray** [ant-design/ant-design#51638]
### What problem does this feature solve?

When I set cssVar: true, I noticed that the CSS variables for the design tokens I defined for components are not applied in the styles if that specific component isn’t present on the page. For example, design tokens defined for the Table component (or any design tokens not specifically defined) aren’t included in the CSS if the Table component isn’t used on the current page. I couldn’t find a way to include all design tokens as CSS variables without manually importing each component.

Is there a way to include all design tokens as CSS variables globally without needing to import the component? If not, could such a feature be planned?

### What does the proposed API look like?

Maybe a configuration option like exportGlobally could enable this functionality without requiring each component to be imported.

**Comment by afc163** [comment]
You can import `<App />`: https://ant.design/components/app/
