### ISSUE TITLE
希望优化一下Form.List的性能

### ISSUE THREAD

**Issue by heyizhiyuan** [ant-design/ant-design#51644]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fu-za-de-dong-tai-zeng-jian-biao-dan-xiang-antd-5-21-6-forked-jqgdzd?file=%2Fdemo.tsx%3A6%2C30)

### Steps to reproduce

-

### What is expected?

优化Form.List的性能

### What is actually happening?

Form.List比较差，批量添加50条数据时会有明显的卡顿

| Environment | Info |
| --- | --- |
| antd | 5.21.5 |
| React | 18.3.1 |
| System | macos |
| Browser | Chrome/130.0.0.0 |

**Comment by zombieJ** [comment]
拉一下火焰图，看起来就是 50 次的正常 first time render 渲染也不卡：

<img width="1158" alt="截屏2024-11-15 10 56 35" src="https://github.com/user-attachments/assets/4619e81a-c2fd-4d39-b620-2a9e8a7828a7">

是不是还有什么东东没有在 reproduce 里还原出来？

**Comment by heyizhiyuan** [comment]
复现的代码有点问题，这是我调整后 first time render 渲染得到的火焰图。性能明显比上图要差得多
<img width="1599" alt="image" src="https://github.com/user-attachments/assets/aed32f07-4fe7-44bd-b45b-198002af9a66">

**Comment by zombieJ** [comment]
从新的 reproduce 看大部分都是 React Dev 自己打的 mark 损耗：

<img width="425" alt="截屏2024-11-20 17 21 03" src="https://github.com/user-attachments/assets/e45eb9ff-9c72-4288-ad00-ffcb29008a21">

React 并不推荐过早优化，只有当 prod 下有性能问题时才需要尝试优化：

* ref: https://legacy.reactjs.org/docs/optimizing-performance.html

**Comment by zombieJ** [comment]
这边就先关了，如果还遇到问题的话可以开一个新的哈~~
