### ISSUE TITLE
antd3.x升级到antd4.x样式错乱以及组件结构异常

### ISSUE THREAD

**Issue by Leeero** [ant-design/ant-design#51648]
### Reproduction link

[https://github.com/ant-design/codemod-v4/blob/master/README.zh-CN.md](https://github.com/ant-design/codemod-v4/blob/master/README.zh-CN.md)

### Steps to reproduce

根据codemod-v4使用文档对 react 项目进行升级，升级后本地 run dev时，一切正常，但是 build 之后组件的结构以及样式全部错乱。
例如select组件

### What is expected?

`<div class="ant-form-item-control-input"><div class="ant-form-item-control-input-content"><div class="ant-select ant-select-in-form-item ant-select-single ant-select-allow-clear ant-select-show-arrow" style="width: 180px;"><div class="ant-select-selector"><span class="ant-select-selection-search"><input type="search" id="status" autocomplete="off" class="ant-select-selection-search-input" role="combobox" aria-haspopup="listbox" aria-owns="status_list" aria-autocomplete="list" aria-controls="status_list" aria-activedescendant="status_list_0" readonly="" unselectable="on" value="" style="opacity: 0;"></span><span class="ant-select-selection-placeholder"></span></div><span class="ant-select-arrow" unselectable="on" aria-hidden="true" style="user-select: none;"><span role="img" aria-label="down" class="anticon anticon-down ant-select-suffix"><svg viewBox="64 64 896 896" focusable="false" data-icon="down" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M884 256h-75c-5.1 0-9.9 2.5-12.9 6.6L512 654.2 227.9 262.6c-3-4.1-7.8-6.6-12.9-6.6h-75c-6.5 0-10.3 7.4-6.5 12.7l352.6 486.1c12.8 17.6 39 17.6 51.7 0l352.6-486.1c3.9-5.3.1-12.7-6.4-12.7z"></path></svg></span></span></div></div></div>`

### What is actually happening?

`<div class="ant-col ant-form-item-control-wrapper"><div class="ant-form-item-control"><span class="ant-form-item-children"><div class="ant-select ant-select-enabled ant-select-allow-clear" style="width: 180px;"><div class="ant-select-selection
            ant-select-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-controls="e3fa72b4-6f63-4afa-a71d-d9e57bd42677" aria-expanded="false" tabindex="0"><div class="ant-select-selection__rendered"></div><span class="ant-select-arrow" unselectable="on" style="user-select: none;"><i aria-label="图标: down" class="anticon anticon-down ant-select-arrow-icon"><svg viewBox="64 64 896 896" focusable="false" class="" data-icon="down" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M884 256h-75c-5.1 0-9.9 2.5-12.9 6.6L512 654.2 227.9 262.6c-3-4.1-7.8-6.6-12.9-6.6h-75c-6.5 0-10.3 7.4-6.5 12.7l352.6 486.1c12.8 17.6 39 17.6 51.7 0l352.6-486.1c3.9-5.3.1-12.7-6.4-12.7z"></path></svg></i></span></div></div></span></div></div>`

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 16.11.0 |
| System | mac |
| Browser | 谷歌版本 130.0.6723.117（正式版本） (arm64) |

**Comment by zombieJ** [comment]
感谢反馈，但是 v4 也已经过了维护期很久了。不会提供支持了哈，抱歉。
