### ISSUE TITLE
Select 組件能使用 onPaste 但 typescript 無此屬性

### ISSUE THREAD

**Issue by conmy2002** [ant-design/ant-design#51654]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/biao-qian-antd-5-22-1-forked-w6swl6?file=%2Fdemo.tsx%3A6%2C30)

### Steps to reproduce

於 Select 組件添加 onPaste 可以正常運作，但 typescript 驗證無法通過

### What is expected?

Select 組件是否有支援 onPaste 的 event？如果有支援是否要調整 type？

### What is actually happening?

Select 組件能使用 onPaste 但 typescript 無此屬性

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18 |
| System | ubuntu 22.04 |
| Browser | chrome |

**Comment by zombieJ** [comment]
Select 里会把一些属性向下透传到 dom 上，但是这些都是非标支持的。非文档里的属性都可能是意想不到的巧合。参考：

[FAQ: 官方文档中没有提供的隐藏 API 我可以使用吗？](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)

**Comment by afc163** [comment]
不要用，不支持。
