### ISSUE TITLE
antd5 使用了 ConfigProvider 全局化配置的 theme 主题后，页面加载性能降低。

### ISSUE THREAD

**Issue by evelope** [ant-design/ant-design#51656]
### Reproduction link

[https://无](https://无)

### Steps to reproduce

<ConfigProvider theme={token:{}} />

只要写了  theme={token:{}} 后， react 路由跳转页面的时间会增加 50ms-100ms 左右
删除了以后，会缩减50ms-100ms。

使用的 react-router-dom 的 useNavigate ， navigate跳转页面，
跳转之前加个时间戳，页面 加载完成后，再记录时间戳，看时间差。

加上   theme={token:{}} 后，时间增加一些。
可能是因为antd5 的 CSS-in-JS 方案 导致的一些影响，看能不能出个解决办法？

### What is expected?

不影响页面加载性能。

### What is actually happening?

页面加载时间增加 100ms 左右

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | react18 |
| System | mac |
| Browser | chrome |

**Comment by evelope** [comment]
求教 怎样 把 css var 打开？

**Comment by yoyo837** [comment]
https://ant.design/docs/react/customize-theme-cn

看文档
