### ISSUE TITLE
Tabs and CustomTabPane

### ISSUE THREAD

**Issue by GuillaumeCisco** [ant-design/ant-design#5165]
Hello,

Sorry I'm not a chinese speaking user and sorry this is not really an issue.
I'd like to know if it is possible to pass a custom `TabPane` to `Tabs` instead of a `TabPane` component.

Exemple:

Classic:
```javascript 
import {Tabs} from 'antd';
const TabPane = Tabs.TabPane;

    <Tabs defaultActiveKey='1' animated={false}>
        <TabPane key={'1'} tab={<h4>One title</h4>}>
                {some components that use props my_prop}
        </TabPane>
        <TabPane key={'2'} tab={<h4>Another title</h4>}>
                {some components that use props my_prop}
        </TabPane>
    </Tabs>;
```

What I try to achieve:
```javascript

import {Tabs} from 'antd';
const TabPane = Tabs.TabPane;

     const CustomTabPane = ({key, my_prop, title}) =>
        <TabPane key={key} tab={<h4>{title}</h4>}>
                {some components that use props my_prop}
        </TabPane>;

    <Tabs defaultActiveKey='1' animated={false}>
        <CustomTabPane key={'1'} my_prop={a} title="One title"/>
        <CustomTabPane key={'2'} my_prop={b} title="Another Title"/>
    </Tabs>;
```

The second Option does not display a thing. What should I add for using a custom component for `Tabs` to be able to render my `CustomTabPane`?

Thank you,

**Comment by paranoidjk** [comment]
just try to wrapper your `<CustomTabPane/>`  in  a` < TabPane />`

**Comment by GuillaumeCisco** [comment]
Tank you @paranoidjk but I'm trying to achieve the opposite in order to further use high order component composition.

**Comment by benjycui** [comment]
I cannot find any code in `rc-tabs` which make it only works with provided TabPane.

So, what is your use case, and please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by GuillaumeCisco** [comment]
Thank you @benjycui , you can see the behavior in action here: http://codepen.io/AgentCisco/pen/wJzMYR?editors=001

I've just copied what I've written in my precedent post.

**Comment by benjycui** [comment]
OK, you must put `tab` on your customized TabPane, for Tabs will try to read `tab` from its children's props.

**Comment by benjycui** [comment]
I am not sure if we can pass callback to inner TabPane by `context`, and then inner TabPane can pass it's props to closest Tabs by callback.

**Comment by paranoidjk** [comment]
@GuillaumeCisco  i don't see any reason why you need high order component composition, just try this

```js
const { Tabs } = antd;
const TabPane = Tabs.TabPane;

const customTabPane = (my_prop, title) =>
   <TabPane key={title} tab={<h4>{title}</h4>}>
        {my_prop}
    </TabPane>;

ReactDOM.render(
  <Tabs defaultActiveKey='a' animated={false}>
        {customTabPane('1', 'a')}
        {customTabPane('2', 'b')}
  </Tabs>
, mountNode);
```

**Comment by paranoidjk** [comment]
if you have any further question, feel free to repoen

**Comment by GuillaumeCisco** [comment]
@paranoidjk Doing what you're suggesting is not a good practice.
React is about components and thinking with components. Not using interpolation hack everywhere...
Also it will break rendering performance optimization. With this code, you cannot use `shouldComponentUpdate` and avoid some rendering. It's a huge no no.

Last thing, using high ordering component is very used in real life.
You can for example write:

```javascript
import {Tabs} from 'antd';
const TabPane = Tabs.TabPane;

const NestedComponent1 = ({my_prop}) => <div>1 {my_prop}</div>
const NestedComponent2 = ({my_prop}) => <div>2 {my_prop}</div>

const HOC = (Component) =>
     const CustomTabPane = ({key, my_prop, title}) =>
        <TabPane key={key} tab={<h4>{title}</h4>}>
                <Component my_prop={my_prop} />
        </TabPane>;

     return CustomTabPane;

const TabPane1 = HOC(NestedComponent1);
const TabPane2 = HOC(NestedComponent2);

ReactDOM.render(
    <Tabs defaultActiveKey='1' animated={false}>
        <TabPane1 key={'1'} my_prop={a} title="One title"/>
        <TabPane2 key={'2'} my_prop={b} title="Another Title"/>
    </Tabs>
, mountNode);
```

It allows us to completely control each component and its render cycle.
It is easier to read and to understand.
Using composition allow to change one of the component in the chain list and using the other. Overriding only the component we want. For example in a case of the html tag `table`, we know we can have a `tbody`, `tr`, `td`. If we define a component for each of these html tag based on our needs and use them. Further in the project we want to use them but with a different implementations of `tr` for example.
High ordering component composition allow you to only change this particular component thanks to ... composition. Code will look this way `const CustomTable = TableHOC(TableBodyHOC(MyNewTrHOC(Td)))`, and then pass your props to `CustomTable` like you normally do. This is extremely powerful and reliable.

I don't know what's going on with the current implementation of antd and customs TabPane not being recognized by Tabs... Not even a single error message is thrown... We can see the same use case with Material UI and Table component, it expects Tbody and Thead components. But you can use a custom component by adding it a `muiName` for making it works...
I was looking for this kind of answer posting this issue.

I don't have the correct rights to reopen this issue.
But one thing sure, this is not solved yet...

**Comment by paranoidjk** [comment]
@GuillaumeCisco you just need to do this, bypass all restProps
```js
const HOC = (Component) => {
     const CustomTabPane = ({key, my_prop, title, ...restProps}) =>
        <TabPane key={key} tab={<h4>{title}</h4>} {...restProps}>
                <Component my_prop={my_prop} />
        </TabPane>;

     return CustomTabPane;
}
```

**Comment by paranoidjk** [comment]
@GuillaumeCisco http://codepen.io/paranoidjk/pen/qrqBGW

**Comment by GuillaumeCisco** [comment]
Thank you for this huge piece of information `restProps` for understanding how antd works under the hood.

We can make it work based on my first codepen example with : http://codepen.io/AgentCisco/pen/vxyERZ?editors=001

```javascript
const { Tabs } = antd;
const TabPane = Tabs.TabPane;

const CustomTabPane = ({my_prop, key, ...restProps}) =>
  <TabPane key={key} {...restProps}>
      {my_prop}
  </TabPane>;

ReactDOM.render(
  <Tabs defaultActiveKey='1' animated={false}>
        <CustomTabPane tab={"One title"} key={'1'} my_prop={'a'}/>
        <CustomTabPane tab={"Another Title"} key={'2'} my_prop={'b'}/>
    </Tabs>
, mountNode);
```

Here the CustomTabPane includes the tab, so the parent Tabs can display it.
But if I want further granularity and decoupling the tab for CustomTabPane to manage it, it won't work anymore. But we have the content of the tabs thanks to restProps : http://codepen.io/AgentCisco/pen/Wpobza?editors=001

```javascript
const { Tabs } = antd;
const TabPane = Tabs.TabPane;

const CustomTabPane = ({my_prop, title, key, ...restProps}) =>
  <TabPane tab={title} key={key} {...restProps}>
      {my_prop}
  </TabPane>;

ReactDOM.render(
  <Tabs defaultActiveKey='1' animated={false}>
        <CustomTabPane title={"One title"} key={'1'} my_prop={'a'}/>
        <CustomTabPane title={"Another Title"} key={'2'} my_prop={'b'}/>
    </Tabs>
, mountNode);
```

I don't know if there is a clean way to implement this with the current design of antd.
But it sure will be soon or later mandatory for evolving and decoupling components.

Issue is still pending.

**Comment by benjycui** [comment]
> I don't know if there is a clean way to implement this with the current design of antd.

Not yet.

> I am not sure if we can pass callback to inner TabPane by context, and then inner TabPane can pass it's props to closest Tabs by callback.

And this is what I want to discuss, to find a solution.

**Comment by afc163** [comment]
any process?

**Comment by benjycui** [comment]
How about this:

```jsx
// Tabs
class Tabs extends React.Component {
  getChildContext() {
    return {
      register(props) {
        // store props in tabs, as it collect props from children now.
      }
    };
  }
}
```

```jsx
// TabPane
class TabPane extends React.Comonent {
  componentWillReceiveProps(nextProps, nextContext) {
    nextContext.register(nextPropse);
  }
}
```

**Comment by benjycui** [comment]
The above solution doesn't work for rc-tabs, for it need [children's key](https://github.com/react-component/tabs/blob/505bd4ad19e862601f62d94ec739e6e5b79e53e6/src/TabBarMixin.js#L28) while rendering TabBar.

So, just use the following solution:

> OK, you must put tab on your customized TabPane, for Tabs will try to read tab from its children's props.

**Comment by GuillaumeCisco** [comment]
Why closing an issue not solved?
There is clearly a problem of implementation. It will occur in a lot of future component creation.
I don't understand this urge of closing issues...

**Comment by afc163** [comment]
I think `restProps` is a good enough solution for your issue. And if you have better idea, we can still continue to discuss about it here.

**Comment by benjycui** [comment]
@GuillaumeCisco sorry, but I cannot find a solution which will not introduce breaking changes.

If someone can find a solution to solve this problem without breaking changes, just post your solution in this issue, and maybe a PR, thanks.

**Comment by GuillaumeCisco** [comment]
I've just looked at the code of `rc-tabs` : https://github.com/react-component/tabs
As you point out @benjycui, Tab titles are bond to TabPanes from Tabs children.
TabPane is not the master for dealing with the Tab titles. That's the big problem and a breaking change.
`Tabs` could handle the Tab titles for allowing `TabPane` to do only what it meant for.
As for now, `TabPanes` cannot work alone, they need Tabs. And `Tabs` cannot handle custom components because its direct children need to have `tab` and `key` props.

We could imagine something like:
```javascript
const {Tabs} = antd;
const TabPane = Tabs.TabPane;

const CustomTabPane = ({my_prop, key, ...restProps}) =>
  <TabPane key={key} {...restProps}>
      {my_prop}
  </TabPane>;

const titles = ["One title", "Another Title"];
// key is the mandatory prop for customTabPane
ReactDOM.render(
  <Tabs defaultActiveKey='1' animated={false} titles={titles}>
        <CustomTabPane key={'1'} my_prop={'a'}/>
        <CustomTabPane key={'2'} my_prop={'b'}/>
    </Tabs>,
   mountNode);
```

With an `invariant` check on the Tabs constructor if the number of children is not equal to the number of titles.
This way, we could have correct decoupling.
It is just an idea, and I'm still not satisfied by it.

**Comment by benjycui** [comment]
```jsx
<Tabs defaultActiveKey='1' animated={false} titles={titles}>
```

It's unstable to depend on the order of `TabPane`.

And we put `TabPane[tab]` on `TabPane`, so that relative code will be group together. So we don't want to remove `TabPane[tab]` from `TabPane`.

**Comment by GuillaumeCisco** [comment]
Yep, it's not the right way to go.
The real issue ils that Tabs handle the tabs titles by refering to its direct children. It acts like a wrapper by contract. Si I think the best thing to do right now for supporting custom tab panes with HOC is to put an invariant check on its direct children to force them to declare a tab props.
It will help a lot to have this error raised in the console.

Thoughts ?

**Comment by benjycui** [comment]
> Si I think the best thing to do right now for supporting custom tab panes with HOC is to put an invariant check on its direct children to force them to declare a tab props.

Yep, could your PR to add a warning? To https://github.com/react-component/tabs

**Comment by benjycui** [comment]
ref: https://github.com/react-component/tabs/pull/64
