### ISSUE TITLE
自定义form表单，微软拼音输入汉字有问题（原始input就有这个问题）

### ISSUE THREAD

**Issue by zhouchunguang2020** [ant-design/ant-design#51655]
### Reproduction link

[https://codepen.io/chunguang-zhou/pen/MWNxLJN](https://codepen.io/chunguang-zhou/pen/MWNxLJN)

### Steps to reproduce

在window11下，使用微软拼音，多次输入汉字

### What is expected?

正常输入

### What is actually happening?

输入结果不正确

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18 |
| System | window11 |
| Browser | 谷歌最新版 |

**Comment by zombieJ** [comment]
没有 win11……能录个屏看看不~

**Comment by zhouchunguang2020** [comment]
https://github.com/user-attachments/assets/cce517b1-b9eb-4a23-8a94-98838ca87ef7

**Comment by zhouchunguang2020** [comment]
> 没有 win11……能录个屏看看不~

已发

**Comment by afc163** [comment]
你试试原生 input 是否有一样的问题，如果是，那么并非 antd 本身的问题。

**Comment by zhouchunguang2020** [comment]
> 你试试原生 input 是否有一样的问题，如果是，那么并非 antd 本身的问题。

应该是里面formatValue方法的影响，不加的话，一切正常

**Comment by afc163** [comment]
所以原始 input + formatValue 也有一样的问题，这个问题和 antd 无关，对么？

**Comment by zhouchunguang2020** [comment]
> 所以原始 input + formatValue 也有一样的问题，这个问题和 antd 无关，对么？

是的，原始input会有这个问题，不好意思。
