### ISSUE TITLE
TreeSelect下拉内容溢出无法显示完整内容

### ISSUE THREAD

**Issue by boiboif** [ant-design/ant-design#51668]
### Reproduction link

[https://ant-design.antgroup.com/components/tree-select-cn](https://ant-design.antgroup.com/components/tree-select-cn)

### Steps to reproduce
![image](https://github.com/user-attachments/assets/80f81e1a-2e18-4caf-849d-d9e2e6c67c6b)

官方文档中，
异步加载例子

### What is expected?

溢出部分滚动到底完整显示

### What is actually happening?

内容无法完整显示

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/51567

**Comment by wzxm** [comment]
这个问题在 5.22.3 版本还存在呀，修复了吗？

**Comment by afc163** [comment]
@wzxm 给个重现链接

**Comment by boiboif** [comment]
> 这个问题在 5.22.3 版本还存在呀，修复了吗？

把lock文件删了重新安装依赖

**Comment by Nathanielna** [comment]
![Image](https://github.com/user-attachments/assets/0b3cea12-ec7a-42ba-a3ae-07ad2343f8e5)5.24.6还复现了
