### ISSUE TITLE
Item 自动继承 Form 的泛型

### ISSUE THREAD

**Issue by ianzone** [ant-design/ant-design#51662]
### What problem does this feature solve?

为了限定 Item 中的 name 字段，需要将 ValueType 手动传递给每个 Item，比较繁琐。

### What does the proposed API look like?

只需将 ValueType 传递给 Form，当前 Form 下的 Item 组件自动继承 ValueType。
```tsx
type ValueType = {
  email: string;
  password: string;
}

<Form<ValueType>>
  <Item name='asdf' > // <--IDE可检查报错
    <Input />
  </Item>
</Form>
```

**Comment by fnoopv** [comment]
实现不了吧, 泛型没有这样用的

**Comment by fnoopv** [comment]
可以看看这个 https://stackoverflow.com/questions/70937525/infer-child-component-generics-from-parent-type
