### ISSUE TITLE
Form setFieldsValue can not set extra field if no getFieldDecorator.

### ISSUE THREAD

**Issue by wuguanghai45** [ant-design/ant-design#5167]
#### Environment(required)

- antd version:  2.7.3

#### What did you do? 
因为用了rails 的 nested form 功能, 保存之后需要把id 存到fieldvalue 里面用来保证二次编辑的时候是更新而不是创建。 但是用setFieldsValue 发现不能改变增加没有用getFieldDecorator包裹的字段， 能否有个API来定义 setFieldsValue 扩展字段.

**Comment by yesmeck** [comment]
This is by design.
