### ISSUE TITLE
表格开启虚拟滚动，全长场景下横向滚动时会导致表格列和表格内容显示错位 

### ISSUE THREAD

**Issue by Lew14310** [ant-design/ant-design#51691]
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn](https://ant-design.antgroup.com/components/table-cn)

### Steps to reproduce

此BUG我在5.22.1也发现了 官网目前最新的5.21.6也一样 ，请翻到虚拟列表展示那栏，横向滚动条进行超级快速的横向滚动， 是超级快速滚动一次完毕停下来看看，会发现大部分情况下都会导致错位问题

### What is expected?

期望在虚拟滚动下 列头和内容不会出现内容错位问题

### What is actually happening?

现在只要不发生横向滚动是可以的，横向滚动了就会有BUG

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18.2.0 |
| System | Window11 |
| Browser | chrome版本 130.0.6723.117（正式版本） （64 位） |

**Comment by Lew14310** [comment]
<img width="829" alt="lx_clip1731986085763" src="https://github.com/user-attachments/assets/a5dcf041-9530-43da-8f11-ad5e915785b4"> 我操作后发现的问题此时应该显示Group但是它显示了Address 2

**Comment by Lew14310** [comment]
https://github.com/user-attachments/assets/6f4c2408-d4d0-4d5b-a236-3efdb843776e

**Comment by DDDDD12138** [comment]
视频省流：前一分钟都在加载页面，可以直接快进

BUG如图：
![image](https://github.com/user-attachments/assets/2d1b3ec7-bb23-4878-85c5-9dce082f5c09)

官网demo: [demo](https://ant.design/components/table-cn#table-demo-virtual-list)

**Comment by zombieJ** [comment]
我重现不出这个问题，能不能帮忙确认一下是否是 windows only 的？

**Comment by linlinjiang** [comment]
目前的确只能在windows复现，mac没有问题
