### ISSUE TITLE
Range picker (>= 5.21.4) returns wrong dates onChange when manually change date time without pressing OK button.

### ISSUE THREAD

**Issue by suupham2506** [ant-design/ant-design#51693]
### Reproduction link

[https://go.screenpal.com/watch/cZXqiJnVZF5](https://go.screenpal.com/watch/cZXqiJnVZF5)

### Steps to reproduce

- Select start date (for example: 18/11)=> press OK 
- Select end date (for example: 19/11)=> press OK
=> work fine at the first time
- Select start time (for example: 5/11)
- manually move to end time and select end time for example: 6/11)=> press OK 
Observe the result.

### What is expected?

Start time should be 5/11
End time should be 6/11

### What is actually happening?

Start time is 6/11
End time is 18/11

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | 18.2.0 |
| System | macos sonoma 14.2.1 |
| Browser | 127.0.6533.120 Chrome |

---
This behavior is so weird.
Suggestion:
1. Fix the time return from onChange callback function to be correct.
2. Any way to disable that manual change, must press OK to submit the change.

**Comment by zombieJ** [comment]
Field switch should be locked even when the field already has the values.

**Comment by Zyf665** [comment]
ok

**Comment by suupham2506** [comment]
@Zyf665 @zombieJ could you update the progress?

**Comment by Zyf665** [comment]
> @Zyf665 @zombieJ could you update the progress?

Sorry for the late response. I've submitted a PR for this issue and it's currently waiting for review:https://github.com/react-component/picker/pull/897
I've been quite busy lately but I'll keep tracking the progress and update here once it's reviewed.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/52102
