### ISSUE TITLE
Checkbox.Group存在低级的勾选bug

### ISSUE THREAD

**Issue by HEJIN2016** [ant-design/ant-design#51690]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/checkbox-zu-antd-5-21-6-forked-m84ylx?from-embed=)

### Steps to reproduce

```
const options = [
  { label: "A", value: "A" },
  { label: "A1", value: "A1" },
];
return (
<Checkbox.Group options={options} value={"A1"} />
)
```
此时，A和A1都会勾选，而且不止这个单子会出现，任意A B，以及字符A的选项组合，当value是A B时，两项都会勾选

### What is expected?

只勾选一个

### What is actually happening?

两个都会勾选

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.0.0 |
| System | mac ox |
| Browser | 版本 130.0.6723.117（正式版本） (x86_64) |

**Comment by afc163** [comment]
```diff
- <Checkbox.Group options={options} value={"123"} />
+ <Checkbox.Group options={options} value={["123"]} />
```

value 类型是数组而非字符串，注意 TS 提示。

<img width="912" alt="图片" src="https://github.com/user-attachments/assets/aab69569-74c4-4f03-a621-8a2f52c66291">
