### ISSUE TITLE
Input addonAfter 添加 Dropdown 报错 React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#51706]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-c6xcxa?file=demo.tsx)

### Steps to reproduce

我想在Input后面加一个下拉菜单

或者Select组件有类似功能？可以自由输入，也可以下拉选择，早期版本有个combobox属性，现在废弃了

我不需要AutoComplete组件，不需要输入的时候去匹配

![image](https://github.com/user-attachments/assets/3b72fe23-c9ed-471f-aa34-8ddf503efb00)

``` javascript
import React from 'react';
import './index.css';
import { Dropdown, Input, Space } from 'antd';
import { DownOutlined } from '@ant-design/icons';

const App: React.FC = () => (
  <Input
    placeholder="Basic usage"
    addonAfter={
      <>
        <Dropdown
          menu={
            [
              {
                key: '1',
                label: 'http://www.baidu.comwww.baidu.com',
              },
              {
                key: '2',
                label: 'http://www.google.comwww.google.com1',
              },
            ] as any
          }
        >
          <a onClick={(e) => e.preventDefault()}>
            <Space>
              <DownOutlined />
            </Space>
          </a>
        </Dropdown>
      </>
    }
  />
);

export default App;
```

### What is expected?

正常运行

### What is actually happening?

React.Children.only expected to receive a single React element child.

![image](https://github.com/user-attachments/assets/399cbf07-8b3e-439f-8a86-b4f1dc0e8029)

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18 |
| System | mac/windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
不要硬转 any，ts 已经告诉你哪里错了：

```diff
-- menu={[ ... ] as any}
++ menu={{ items: [...] }}
```

https://stackblitz.com/edit/react-c6xcxa-jhknyg?file=demo.tsx
