### ISSUE TITLE
Modal里面的表单设置preserve={false}，Form.List有多个的时候，删除前面的数据，后面的会清空

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design#51702]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-f856bm?file=demo.tsx,index.css)

### Steps to reproduce

打开重现链接后按下面的步骤操作：
1、添加三行数据，先把所有行的输入框都赋值；
2、删除第二行数据，第三行数据会清空，第一行不会清空；
3、preserve={true}后，数据就不会清空了。

### What is expected?

设置preserve={false}的时候后面的数据也不清空

### What is actually happening?

preserve={false}的时候后面的数据清空了

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | react 18 |
| System | window 10 |
| Browser | Chrome 123.0.6312.86 |

**Comment by zombieJ** [comment]
看起来不用 Modal。直接 preserve false 也能重现：

https://stackblitz.com/edit/react-f856bm-ds7fhy?file=demo.tsx

**Comment by zombieJ** [comment]
ref: https://github.com/react-component/field-form/pull/258/files

处理了嵌套 Form.List 情况又导致非嵌套情况的 `preserve` 会有问题，需要有种方式标记到路径是来自哪个移除项。

**Comment by crazyair** [comment]
List 需要特殊兼容，这个不是手动移除，是挤上去的，不应该值清空
