### ISSUE TITLE
Allow override of default loading icon for Button component

### ISSUE THREAD

**Issue by insertmike** [ant-design/ant-design#51707]
### What problem does this feature solve?

Currently, the loading prop on the Ant Design Button only supports the default spinner icon, which limits customization options. In many use cases, designers and developers want to use custom icons for the loading state to align with the application’s branding or user experience. The absence of a customizable loading icon forces workarounds, such as overriding the icon prop and disabling the default loading spinner. This adds unnecessary complexity to the codebase.

### What does the proposed API look like?

1. Inline override via prop 

```
<Button
  loading={true}
  loadingIcon={<CustomSpinnerIcon />}
>
  Submit
</Button>

```

2. Global Override via Theme

```
{
  components: {
    Button: {
      loadingIcon: <CustomSpinnerIcon />,
    },
  },
}

```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/51758
