### ISSUE TITLE
Website of Ant Design not work periodically

### ISSUE THREAD

**Issue by KalyDanil** [ant-design/ant-design#51713]
### Reproduction link

[https://ant.design/](https://ant.design/)

### Steps to reproduce

Open link several times, if it loaded, try some tabs.

### What is expected?

Website of Ant Design work.

### What is actually happening?

For about two weeks website of Ant Design not work periodically: takes a long time to load and gives out ERR_CONNECTION_CLOSED or ERR_TIMED_OUT. Sometimes website work, but not long. 

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | React |
| System | Windows 10 |
| Browser | Google Chrome, Microsoft edge |

---
I didn't use any third-party programs.

**Comment by afc163** [comment]
https://downforeveryoneorjustme.com/ant.design
