### ISSUE TITLE
在 react-starter-kit 同构渲染脚手架中集成报错

### ISSUE THREAD

**Issue by MinJieLiu** [ant-design/ant-design#5171]
#### 环境

- antd version: `2.7.4`
- OS and its version: `node.js v7.6`
- Browser and its version: `chrome v56`

#### 问题出现步骤

在脚手架 `https://github.com/kriasoft/react-starter-kit` 中集成 `antd` ，
我按照官方的说明添加 `babel-plugin-import`：
```js
plugins: [
  ['import', { libraryName: 'antd', style: 'css' }],
],
```
并且也添加了 `less-loader`。
运行报错：
```
\react-starter-kit\node_modules\antd\lib\style\index.css:10
html {
     ^
SyntaxError: Unexpected token {
...
```
#### 我的期望

这个脚手架用的人还挺多，算是服务端渲染中最完美的一个了。这个问题我在网上也找了很久，最终还是没能得到完美的解决。期望能好好看一下这个问题。谢谢 😊

**Comment by afc163** [comment]
https://github.com/kriasoft/react-starter-kit/issues/947

**Comment by MinJieLiu** [comment]
@afc163 谢谢😊

**Comment by afc163** [comment]
我有时间看看有啥解决方案。

**Comment by MinJieLiu** [comment]
好的，谢谢

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4723
https://github.com/ant-design/ant-design/issues/4507

**Comment by afc163** [comment]
Check https://github.com/ant-design/react-starter-kit

1. Do not import antd css in server side.
2. Do not import antd css as css-modules.

**Comment by MinJieLiu** [comment]
非常感谢😊😊 @afc163

**Comment by MinJieLiu** [comment]
@afc163 刚克隆下来跑起来，发现 `antd` 组件中 `css` 没有被提取出来🙄，也就是 `Button` 没有样式

**Comment by tim-soft** [comment]
@afc163 
I've followed [ant-design/react-starter-kit@6e345f6](https://github.com/ant-design/react-starter-kit/commit/6e345f69bf7dd639ca2c56e4f51f928926c0ee76) and still have OP's issue

**Comment by jin-cheng-li** [comment]
react-starter-kit更新了版本，解决方案貌似不灵了。能否更新一下

**Comment by MinJieLiu** [comment]
貌似在  react-starter-kit  中，我并没有找出完美的办法解决，除非全局引入 css ...

**Comment by afc163** [comment]
几位帮忙一起看下，最近事情比较多~

**Comment by jin-cheng-li** [comment]
各位大神帮忙看看，react-starter-kit最新版本集成antd配置给个例子。

**Comment by EncourageCong** [comment]
问题其实是SSR时，babel-plugins-import 自动 require(控件.css) ，babel 无法识别css 语法，所以报syntaxerror 异常。@afc163 的解决思路是对的，就是webpack 打包时，服务端不使用babel-plugins-import 也就不会引用 .css文件，SSR时就不会报错；客户端添加babel-plugins-import 配置，页端就能引用控件样式了。
@afc163 的解决方案之所以没成功，主要是因为react-starter-kit/tools/start.js 启动应用时，会添加babel-loader的 plugins，导致 @afc163 在webpack.config.js文件中添加的配置失效。只需要修改start.js 中的这段代码就可以了
`config.module.loaders.filter(x => x.loader === 'babel-loader').forEach(x => (x.query = {
      plugins: [
        ['react-transform', {
          transforms: [
            {
              transform: 'react-transform-hmr',
              imports: ['react'],
              locals: ['module'],
            }, {
              transform: 'react-transform-catch-errors',
              imports: ['react', 'redbox-react'],
            },
          ],
        },
        ], [
          'import', {
            libraryName: 'antd', libraryDirectory: 'lib', style: 'css',
          },
        ],
      ],
    }));`

**Comment by jin-cheng-li** [comment]
https://github.com/kriasoft/react-starter-kit/blob/master/tools/start.js
@EncourageCong 这里并没有找到你所说的这段代码哦，可否说的具体一点，在第几行。

**Comment by tim-soft** [comment]
@EncourageCong can you post a code snippet from your `react-starter-kit/tools/start.js` and `react-starter-kit/tools/webpack.config.js` ?

**Comment by pengliaoye** [comment]
问题解决了么。我也没在start.js看到这段代码也。而且我是按照
https://github.com/ant-design/react-starter-kit
这个来修改的。

**Comment by tim-soft** [comment]
@afc163 Thank you!!

The new config does appear to work, although this presents a new problem: [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)

Using ExtractTextPlugin among other things will likely help curb FOUC in this case

**Comment by viviancpy** [comment]
@tim-soft , I cloned ant-design/react-starter-kit and ran it local just now. It is built without a problem, but the button is not an Antd button (it does not have the css). How did you make it work? Would you mind making pr to rectify it?

**Comment by sleva13** [comment]
@tim-soft Do you have modified webpack configuration which solves FOUC issue? Thanks

**Comment by tim-soft** [comment]
@sleva13 I actually said "screw webpack, this is driving me freaking crazy" and import CSS for each component individually for now via withStyles(), this way the CSS is guaranteed to be preloaded. It's not ideal, but it works great.

Getting ant-design loaded into SSR apps has proven to be really tricky, maybe v3.0 can alleviate some of the webpack headaches?

**Comment by sleva13** [comment]
@tim-soft thanks for replying. I actually load styles via withStyles() but it's not perfect - there is still FOUC. I hope in v3.0 it will be fixed.

**Comment by bennygenel** [comment]
@afc163 I tried using [https://github.com/ant-design/react-starter-kit](https://github.com/ant-design/react-starter-kit) also tried making the changes manually but even though I am successfully importing Button component I can't get the styling to work. It just looks like a normal button. I don't get any errors but styles don't apply.

I have the same problem with @viviancpy.

Can you give me some help about this problem please?

**Comment by tim-soft** [comment]
In case anyone is wondering, here's how to modify the latest revision of RSK to load antd via babel-import-plugin

```javascript
const config = {
  {stuff ...}

  module: {
    {stuff ...}

    rules: [
    {stuff ...}

      // Load antd here
      {
        test: /\.css$/,
        include: [/node_modules\/.*antd/],
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
          },
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: './tools/postcss.config.js',
              },
            },
          },
        ],
      },

      // Rules for Style Sheets
      {
        test: reStyle,
        exclude: [/node_modules\/.*antd/], // Don't load antd here!
        rules: [
          {stuff ...}
        ],

{a bunch of stuff ...}

// Only use babel-plugin-import in client side
clientConfig.module.rules[0].options.plugins = [...clientConfig.module.rules[0].options.plugins];
clientConfig.module.rules[0].options.plugins.push(['import', { libraryName: 'antd', style: 'css' }]);

export default [clientConfig, serverConfig];
```

**Comment by leohuangyi** [comment]
@tim-soft I use your way，it worked 。
But it will `Only use babel-plugin-import in client side`.When the html loaded，the client's antd style did't load，there is no antd's style on the DOM.It will trigger flash or jump when the dom style changed.
So is there Anyway to solve this Question? Thank you.

**Comment by tim-soft** [comment]
@leohuangyi use ExtractTextPlugin

`webpack.config.js`
```js
import ExtractTextPlugin from 'extract-text-webpack-plugin';

{...stuff}

{
        test: /\.less$/,
        include: [/node_modules\/.*antd/],
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: [
            {
              loader: "css-loader" // translates CSS into CommonJS
            },
            {
              loader: "less-loader", // compiles Less to CSS
              options: {
                modifyVars: themeVariables,
              }
            }
          ],
        })

{... stuff}

const clientConfig = {
  ...config,

  name: 'client',
  target: 'web',

  entry: {
    client: ['@babel/polyfill', './src/client.js'],
  },

  plugins: [
    new ExtractTextPlugin("antStyles.css"),
```

So now you have a file called antStyles.css that you must include _somewhere_, you could slap it in `html.js` to make sure it's all working
```js
<link rel="stylesheet" type="text/css" href="/assets/antStyles.css" />
```

The idea is that you don't want to inline a colossal amount of styles in your JS, which bottlenecks your JS downloading and executing. With extract text plugin, the styles you need get dumped into `antStyles.css` , this file can get sent to the client _in parallel` to your JS *and* get cached by your web browser. I think this is the best way to integrate with a lib like ant-design.

Maybe I could update the rsk example?

**Comment by joenot443** [comment]
@tim-soft - is your solution above what you ultimately ended up going with?

 You seem to be the authority on getting the RSK and antd to play nicely, though even using your solution above I'm yet to find success. Very curious what your ultimate decision was, and whether you think antd is usable in production despite the issues in getting it packed correctly.

**Comment by tim-soft** [comment]
@joenot443 I use antd in production using my solution above. I'll try to set up an RSK repo with antd integration in the next day or so since I've gotten a lot of questions about it

**Comment by joenot443** [comment]
@tim-soft, that'd be phenomenal. I and I'm sure many others would appreciate that.

**Comment by tim-soft** [comment]
@joenot443 what I'm realizing now is that it's tricky to get the paths right on all platforms, these should do the trick
```
{
            test: /\.css$/,
            include: [/[\\/]node_modules[\\/].*antd/],
            loader: 'style-loader',
            options: {
              sourceMap: isDebug,
            },
          },

          // Convert CSS into JS module
          {
            issuer: { not: [reStyle] },
            exclude: [/[\\/]node_modules[\\/].*antd/],
            use: 'isomorphic-style-loader',
          },

clientConfig.module.rules[0].options.plugins = [
  ...clientConfig.module.rules[0].options.plugins,
  ['import', { libraryName: 'antd', style: 'css' }],
];
```

**Comment by justQing00** [comment]
处理css的做一下判断，当为服务器的时候不进行处理

[https://github.com/zeit/next-plugins/issues/70](https://github.com/zeit/next-plugins/issues/70)

**Comment by hakankaraduman** [comment]
I followed this https://github.com/ant-design/react-starter-kit/commit/6e345f69bf7dd639ca2c56e4f51f928926c0ee76 

My webpack script runs okay, my own css works but antd components are still without style. What should I try?

**Comment by damiangreen** [comment]
I dunno how the heck you guys got this working .. i tried all of above

**Comment by zhangyuang** [comment]
ssr+antd最佳实践看这个example，https://github.com/ykfe/egg-react-ssr/tree/dev/example/ssr-with-antd
比上面贴的所有解决方案都优秀
