### ISSUE TITLE
GenericComponent is not exported from Menu component

### ISSUE THREAD

**Issue by msyavuz** [ant-design/ant-design#51714]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/typescript-f9axop?file=index.ts)

### Steps to reproduce

Import the menu component and export with changing name.

### What is expected?

No typescript error

### What is actually happening?

Typescript errors with:
Exported variable 'CustomMenu' has or is using name 'GenericComponent' from external module "stackblitz:/node_modules/antd/es/menu/index" but cannot be named.

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 16.9.0 |
| System | Fedora 41 |
| Browser | Firefox |

---
There is a similar issue and fix for the MenuItem. I will open a pr with a similar fix for Menu itself.

**Comment by zombieJ** [comment]
Why not?

```diff
--  const CustomMenu = Menu;
++  const CustomMenu: typeof Menu = Menu;
```

**Comment by msyavuz** [comment]
Thank you and that is a good working solution but i think it should not be necessary to explicitly annotate the type.
