### ISSUE TITLE
在form中，使用了collapse，并且加了forceRender属性未生效。没有正确收集表单数据

### ISSUE THREAD

**Issue by GravesDXD** [ant-design/ant-design#51745]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-h55q2k?file=%2Findex.tsx%3A14%2C26-14%2C30)

### Steps to reproduce

第一次直接点击提交，表单数据是空，但是展开之后，就可以收集到数据了，即使是收起也能收集到数据了

### What is expected?

form收集到所有的数据

### What is actually happening?

没有被展开的表单项的数据没有被收集到

| Environment | Info |
| --- | --- |
| antd | 5.17.2 |
| React | react18.2 |
| System | ios |
| Browser | chrome |

**Comment by afc163** [comment]
```diff
- initValues={{ a: "1111" }}
+ initialValues={{ a: "1111" }}
```

**Comment by GravesDXD** [comment]
非常感谢您的解答。但是我换成了initialValues也没有生效。虽然在collapse上加了forceRender，但是collpase中的元素并没有被渲染

**Comment by afc163** [comment]
https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-wscvh9?file=%2Findex.tsx%3A13%2C25&workspaceId=fb8d496a-cbdc-482b-9003-b38c3155f290

**Comment by afc163** [comment]
forceRender 是 item 的属性，并非 Collapse 的属性。
