### ISSUE TITLE
[bug] 使用 tree 展开的时候遇到了结尾部分折叠消失的问题

### ISSUE THREAD

**Issue by radiorz** [ant-design/ant-design#51747]
### Reproduction link

[https://github.com/radiorz/react-project-base/blob/main/packages/react-ui/lib/search-tree/search-tree.demo.tsx](https://github.com/radiorz/react-project-base/blob/main/packages/react-ui/lib/search-tree/search-tree.demo.tsx)

### Steps to reproduce

使用 search-tree 
然后展开树节点
结果: 部分结尾会折叠消失
使用的组件是以下组件
https://github.com/radiorz/react-project-base/blob/main/packages/react-ui/lib/search-tree/search-tree.tsx

### What is expected?

展开 不会错误折叠部分结尾 ,如果超出高度之后, 应变成滚动的形式.

### What is actually happening?

展开错误折叠部分结尾 

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.3.1 |
| System | windows12 |
| Browser | edge 131.0.2903.63  |

**Comment by radiorz** [comment]
最小案例
/**
 * @author
 * @file TestTree.tsx
 * @fileBase TestTree
 * @path projects\react-template\src\components\TestTree.tsx
 * @from
 * @desc
 * @example
 */

import { Tree } from "antd";
export interface TestTreeProps {
  // value: any
}
import treeData from "./tree.consts.json";
export const TestTree: React.FC<TestTreeProps> = () => {
  const maxHeight = 800;

  return (
    <Tree
      // 这个32是padding...
      height={maxHeight}
      className="p-4 bg-white dark:bg-black !rounded-md"
      treeData={treeData}
      blockNode
      titleRender={(item) => <div>{item?.title}</div>}
    />
  );
};

**Comment by radiorz** [comment]
5.21.4 版本则正常显示.

**Comment by afc163** [comment]
@radiorz 移除 pnpm-lock.yaml 后重装 node_modules 再试试。

**Comment by radiorz** [comment]
@afc163 重新安装即可以,是不是rc-tree 底层依赖升级的问题.

**Comment by afc163** [comment]
问题应该是在 https://github.com/react-component/virtual-list/pull/291 里修复的。
