### ISSUE TITLE
Mention component does not have 'disabled' prop

### ISSUE THREAD

**Issue by jch254** [ant-design/ant-design#5175]
#### Environment

- antd version: 2.7.4
- OS and its version: macOS Sierra v10.12.3
- Browser and its version: Google Chrome v56.0.2924.87

#### What did you expect?

Mention component should have a disabled prop - this is important for use in forms.

#### What happened?

Mention component does not have disabled prop.

#### Re-producible online demo

https://ant.design/components/mention/#API

**Comment by 422809585mls** [comment]
没懂 有解决吗

**Comment by afc163** [comment]
@422809585mls Yep.

**Comment by afc163** [comment]
Don't create duplicate issue if someone else already created one.

**Comment by RaoHai** [comment]
样式在 antd 里搞。
