### ISSUE TITLE
Modal in Dark Theme shows as Light Theme

### ISSUE THREAD

**Issue by jsdk1701** [ant-design/ant-design#51766]
### Reproduction link

[https://react-e5u1bx.stackblitz.io](https://react-e5u1bx.stackblitz.io)

### Steps to reproduce

Click on the confirm button and the modal shows up in light theme. Even though the theme is set to dark in the ConfigProvider.  

### What is expected?

The modal should be in dark theme.

### What is actually happening?

The modal is in light theme

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.3.1 |
| System | mac Sequioa 15.0.1 |
| Browser | Chrome Version 131.0.6778.70 |
![Screenshot 2024-11-25 at 1 09 35 PM](https://github.com/user-attachments/assets/c8aea6f6-943e-4881-9149-366bc1a3df46)

**Comment by afc163** [comment]
Try `useModal` instead of static methods: https://ant.design/components/modal#why-i-can-not-access-context-redux-configprovider-localeprefixcls-in-modalxxx

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/40546
