### ISSUE TITLE
在 Next.js 15 框架中，使用 <Menu mode="horizontal" /> 组件会出现报错提示

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#51773]
该问题出现在 Next.js 框架里，为了尽快复现，我贴心地提供了最简项目：

[https://github.com/ylqylq001/AntD-issue-01](https://github.com/ylqylq001/AntD-issue-01)

这个项目结构极为简单，只有区区四个文件：

```
./AntD-issue-01
├─ app
│  ├─ layout.js
│  └─ page.jsx
├─ package.json
└─ README.md
```

它仅用到了两个依赖，分别是 `Next.js` 和 `Ant Design`：

```json
// package.json
{
  "dependencies": {
    "antd": "^5.22.2",
    "next": "^15.0.3"
  }
}
```

复现错误的核心代码也极为简单，只有短短 39 行：

```tsx
"use client";
import { useState, useEffect } from "react";
import { App, Menu, Button } from "antd";

const MenuBtn = () => (
  <Menu
    mode="horizontal"
    items={[
      {
        key: "",
        label: "首页",
      },
    ]}
  />
);

const Demo = () => {
  const { modal } = App.useApp();
  const [modalIsOpen, setModal] = useState(false);

  useEffect(() => {
    modalIsOpen && modal.confirm();
  }, [modalIsOpen]);

  return (
    <>
      <Button type="primary" onClick={() => setModal(!modalIsOpen)}>
        Click Me!
      </Button>
      {modalIsOpen && <MenuBtn />}
    </>
  );
};

export default () => (
  <App>
    <Demo />
  </App>
);
```

访问上面提供的 [Github 仓库](https://github.com/[ylqylq001/AntD-issue-01](https://github.com/ylqylq001/AntD-issue-01)) 并将它克隆 clone 到本地，接下来按照 Readme：

1. 执行 `npm install` 安装 Next.js 和 AntD 依赖。
2. 执行 `npx next dev` 启动 Next.js 服务。
3. 访问浏览器，注意左下角提示的错误信息！

```bash
 ▲ Next.js 15.0.3
   - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 12.4s
```

### 报错 1：Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

启动项目之后，就能看到左下角的一个报错，这个问题我在 #49267 看到有大量用户反馈，但不知为何官方迟迟不修复。

![屏幕截图 2024-11-25 174407](https://github.com/user-attachments/assets/d2d18d47-e668-438b-a3b3-2742cf53bb14)

![屏幕截图 2024-11-25 174711](https://github.com/user-attachments/assets/0bce490d-7522-4871-b8fa-90ad4e1c74d5)

### 报错 2：Cannot update a component (`HotReload`) while rendering a different component (`SingleObserver`). To locate the bad setState() call inside `SingleObserver`, follow the stack trace as described in https://react.dev/link/setstate-in-render

点击 Demo 左上角的 Click Me！按钮，左下角的错误变成了九个：

![屏幕截图 2024-11-25 174834](https://github.com/user-attachments/assets/c57cd40f-ec75-4f63-bdbe-e61e209934d7)

![屏幕截图 2024-11-25 174908](https://github.com/user-attachments/assets/4341311d-f8d4-4b4f-86f4-681c12a56bbd)

**Comment by li-jia-nan** [comment]
Next.js 15 使用了最新的 React19 版本，但是 antd 目前还不支持 React19，计划将在下个大版本支持19，但是需要等待 React19 正式版发布

如果需要临时解决这个问题，可以将 Next 降低到 v14

**Comment by ZianTT** [comment]
> Next.js 15 使用了最新的 React19 版本，但是 antd 目前还不支持 React19，计划将在下个大版本支持19，但是需要等待 React19 正式版发布
> 
> 如果需要临时解决这个问题，可以将 Next 降低到 v14

antd6有大概发版时间吗

**Comment by li-jia-nan** [comment]
以当初发布v5为参考的话，至少需要两个月吧

我的回答并不能代表官方，可以问问 @afc163 @zombieJ @MadCcc 官方的大佬

**Comment by ZianTT** [comment]
> 以当初发布v5为参考的话，至少需要两个月吧
> 
> 我的回答并不能代表官方，可以问问 @afc163 @zombieJ @MadCcc 官方的大佬

明白了，谢谢！

**Comment by arvinxx** [comment]
antd v5 已经完成 react 19 兼容，参见官方文档： https://ant.design/docs/react/v5-for-19-cn 。此 issue 可以关闭了
