### ISSUE TITLE
modal弹窗打开时，按下 enter 键，会触发弹窗底下页面的form的submit行为

### ISSUE THREAD

**Issue by rookie-luochao** [ant-design/ant-design#51770]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

登录页面，弹出忘记密码弹窗，不用点击忘记密码弹窗里面的任何内容，直接在忘记密码弹窗按下 enter 键, 会触发弹窗底下页面的form的submit行为

### What is expected?

不触发弹窗底下页面的form的submit行为

### What is actually happening?

会触发弹窗底下页面的form的submit行为

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.3.1 |
| System | mac os |
| Browser | chrome 131.0.6778.86 |

**Comment by rookie-luochao** [comment]
modal 没有 onKeyDown 这个props参数

**Comment by rookie-luochao** [comment]
modal 没有 onKeyDown 这个props参数 @petercat-assistant

**Comment by rookie-luochao** [comment]
可是我在弹窗中没有选中任何焦点的情况下，按下的 enter 键 @petercat-assistant

**Comment by rookie-luochao** [comment]
还是没有效果

**Comment by rookie-luochao** [comment]
> Is there only one input field in the form? [When there is only one single-line text input field in a form, the user agent should accept Enter in that field as a request to submit the form.](https://www.w3.org/MarkUp/html-spec/html-spec_8.html#SEC8.2) This is a default behavior.

有账号和密码两个输入框

**Comment by Wxh16144** [comment]
> 有账号和密码两个输入框

你的 issue 被标记了 `Need Reproduce` 标签，用 codebox 来一个简单的复现吧。社区会有很多人帮你 debug 的～

**Comment by rookie-luochao** [comment]
> > 有账号和密码两个输入框
> 
> 你的 issue 被标记了 `Need Reproduce` 标签，用 codebox 来一个简单的复现吧。社区会有很多人帮你 debug 的～

好的，下午弄一个幅现环境，谢谢了

**Comment by rookie-luochao** [comment]
已经排查到问题

**Comment by roddc** [comment]
请问是怎么解决的
