### ISSUE TITLE
.ant-btn >span went from `display: inline-block` to `display: inline-flex` (5.21.5 > 5.21.6)

### ISSUE THREAD

**Issue by ctoppel** [ant-design/ant-design#51780]
### Reproduction link

[https://playcode.io/2167891](https://playcode.io/2167891)

### Steps to reproduce

Use 5.21.6 vs 5.21.5

### What is expected?

Not sure what the behavior should be, but this was a breaking change in a minor version update.

### What is actually happening?

divs in buttons used to display on 2 lines, but now are both inline  on 1 line creating a UI bug as it overflows into the next cell

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.2.0 |
| System | mac OS Sonoma 14.3 (23D56) |
| Browser | Chrome Version 130.0.6723.117 (Official Build) (arm64) |

---
We have a table that has buttons that have names in it that until 5.21.6 was displayed on 2 lines. Now the names are displayed on one line due to the style change in 5.21.6 (.ant-btn >span went from `display: inline-block` (5.21.5) to `display: inline-flex` (5.21.6)). Trying to find out the reasoning behind this update as it was a breaking change for us and it was a minor update. Thanks!

**Comment by ctoppel** [comment]
If this is expected behavior and it was made to solve issues generally, then all good. I am able to make adjustments to the button, but typically don't see breaking changes in a minor update like this

**Comment by Wxh16144** [comment]
Sorry, This is an error I introduced while solving issue #51380. I ignored the developers' usage, which led to destructive changes, and this commit was rolled back in `5.22.1`.

Affected versions include: `5.21.6` and `5.22.0`;

`5.22.1` has fixed this issue.

**Comment by Wxh16144** [comment]
An additional note, this repository has a [bug version file](https://github.com/ant-design/ant-design/blob/master/BUG_VERSIONS.json) with a serious error record; you can check if the version of your project's dependencies is not recommended.
