### ISSUE TITLE
AutoComplete 在一些输入法下无法正确响应用户的选择

### ISSUE THREAD

**Issue by Mickey-Xzh** [ant-design/ant-design#51787]
### What problem does this feature solve?

使用一些会提供候选词输入法（比如注音输入法或拼音输入法等）时，输入信息但没有选择候选词时，会弹出匹配的选择项，但选中后无法回填

既然能够在没有选择候选词时就可以展示出可用的数据选项，就应该让用户可以进行选择，否则用户就会认为是功能bug，造成误解

### What does the proposed API look like?

期望在使用输入法但是没有选择候选词时，AutoComplete 能够正确响应用户的选择

**Comment by Mickey-Xzh** [comment]
官方的基本使用示例中即可复现：
[https://ant-design.antgroup.com/components/auto-complete-cn#auto-complete-demo-basic](https://ant-design.antgroup.com/components/auto-complete-cn#auto-complete-demo-basic)

复现操作如下：
![AutoComplete](https://github.com/user-attachments/assets/1811d9dc-e2ea-4efe-8699-be3cb4c48aea)

**Comment by DDDDD12138** [comment]
没毛病，`aa` 的候选项中有 `aaaaaa`

**Comment by Mickey-Xzh** [comment]
> 没毛病，`aa` 的候选项中有 `aaaaaa`

是的，`aa` 的候选项中有 `aaaaaa` 这个我没问题；
我的问题是：在这种情况下我想选择 候选项中的`aaaaaa` 但是选不到！

**Comment by afc163** [comment]
为啥选不到，看截图我没有 GET 到选不到这个点。

**Comment by DDDDD12138** [comment]
![QeoO5A2jGh](https://github.com/user-attachments/assets/6880fcf2-1e9d-484b-8df5-be43cca7de72)
> 是这样操作嘛，似乎没问题

**Comment by Mickey-Xzh** [comment]
> ![QeoO5A2jGh](https://private-user-images.githubusercontent.com/43703884/390225191-6880fcf2-1e9d-484b-8df5-be43cca7de72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzM2NTQsIm5iZiI6MTczMjY3MzM1NCwicGF0aCI6Ii80MzcwMzg4NC8zOTAyMjUxOTEtNjg4MGZjZjItMWU5ZC00ODRiLThkZjUtYmU0M2NjYTdkZTcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYjQ2MzQzMjRlN2M4NTNkMmE5MzQwZGIzMTRhZWMxMmViNzcxYzc2ZThlNjMwYzU1Yzg5N2E4ZDBkYmM1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UmSvX30INCkKaWtHlL5ZlxEDTB12sCIQWcHH8i5ZY0U) [ ![QeoO5A2jGh](https://private-user-images.githubusercontent.com/43703884/390225191-6880fcf2-1e9d-484b-8df5-be43cca7de72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzM2NTQsIm5iZiI6MTczMjY3MzM1NCwicGF0aCI6Ii80MzcwMzg4NC8zOTAyMjUxOTEtNjg4MGZjZjItMWU5ZC00ODRiLThkZjUtYmU0M2NjYTdkZTcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYjQ2MzQzMjRlN2M4NTNkMmE5MzQwZGIzMTRhZWMxMmViNzcxYzc2ZThlNjMwYzU1Yzg5N2E4ZDBkYmM1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UmSvX30INCkKaWtHlL5ZlxEDTB12sCIQWcHH8i5ZY0U) ](https://private-user-images.githubusercontent.com/43703884/390225191-6880fcf2-1e9d-484b-8df5-be43cca7de72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzM2NTQsIm5iZiI6MTczMjY3MzM1NCwicGF0aCI6Ii80MzcwMzg4NC8zOTAyMjUxOTEtNjg4MGZjZjItMWU5ZC00ODRiLThkZjUtYmU0M2NjYTdkZTcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYjQ2MzQzMjRlN2M4NTNkMmE5MzQwZGIzMTRhZWMxMmViNzcxYzc2ZThlNjMwYzU1Yzg5N2E4ZDBkYmM1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UmSvX30INCkKaWtHlL5ZlxEDTB12sCIQWcHH8i5ZY0U) [ ](https://private-user-images.githubusercontent.com/43703884/390225191-6880fcf2-1e9d-484b-8df5-be43cca7de72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzM2NTQsIm5iZiI6MTczMjY3MzM1NCwicGF0aCI6Ii80MzcwMzg4NC8zOTAyMjUxOTEtNjg4MGZjZjItMWU5ZC00ODRiLThkZjUtYmU0M2NjYTdkZTcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYjQ2MzQzMjRlN2M4NTNkMmE5MzQwZGIzMTRhZWMxMmViNzcxYzc2ZThlNjMwYzU1Yzg5N2E4ZDBkYmM1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UmSvX30INCkKaWtHlL5ZlxEDTB12sCIQWcHH8i5ZY0U)
> 
> > 是这样操作嘛，似乎没问题

需要用中文拼音输入法输入`aa`（不按空格或回车键），

**Comment by Mickey-Xzh** [comment]
微软拼音输入法试着确实可以，我用的搜狗拼音输入法就不行了

**Comment by DDDDD12138** [comment]
应该，找搜狗？🤔
