### ISSUE TITLE
<InputNumber> `onChange` callbacked before `onFocus`

### ISSUE THREAD

**Issue by wving5** [ant-design/ant-design#51786]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-zzi2zs?file=demo.tsx)

### Steps to reproduce

直接点击 `<InputNumber />` 的增减操作按钮

### What is expected?

回调顺序为 onFocus -> onChange

### What is actually happening?

回调顺序为 onChange -> onFocus

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.3.1 |
| System | macos 14.7 |
| Browser | Chrome 131.0.6778.86 |

**Comment by zombieJ** [comment]
`onChange` 来源于 `mouseDown` 是优先于 `focus` 事件的，这个顺序是预期的哈~
