### ISSUE TITLE
antd v5 版本中 Table组件与dnd-kit结合实现列拖拽排序时，设置table的 rowSelection={{type:"checkbox"}}，全选以后，就无法拖动了。

### ISSUE THREAD

**Issue by yahong2018** [ant-design/ant-design#51803]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jys3gx?file=demo.tsx)

### Steps to reproduce

进入重现连接，找到演示源代码 dataSource={dataSource}的下面，插入  rowSelection={{type:"checkbox"}}  ，然后在预览界面点击全选，这个时候就发现无法拖动列进行排序了。重新加载，不全选，就可以拖动列排序。

### What is expected?

全选以后，也可以拖动列排序

### What is actually happening?

全选以后，拖动列无法排序。取消选择也不可以进行排序，只能刷新整个页面，重新加载才可以进行列排序。

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18 |
| System | Windows/OSX |
| Browser | Chrome/Edge |

**Comment by OysterD3** [comment]
![image](https://github.com/user-attachments/assets/68115f5c-b202-47db-b75f-9b25da38e530)

Checkbox没有ID，你给它赋值就没问题了，你试试

**Comment by yahong2018** [comment]
问题解决，非常感谢 ！[OysterD3](https://github.com/OysterD3)
