### ISSUE TITLE
iphone6以上，safari隐私浏览模式下，表单数据无法存储

### ISSUE THREAD

**Issue by gaoxt9** [ant-design/ant-design#5181]
如题。非因为模式可用

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
What is your use case?

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
close for no response
