### ISSUE TITLE
Select组件多选模式时，options更新后，选中的值未更新

### ISSUE THREAD

**Issue by 214132049** [ant-design/ant-design#51819]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-9krtgs?file=demo.tsx)

### Steps to reproduce

1、点击删除A1按钮
2、观察选中的值和选项列表

### What is expected?

下拉框中展示已删除A1选项的value, 效果类似单选。

### What is actually happening?

未展示已删除选项的value, 依然展示已删除选项的label

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.3.1 |
| System | MacOS 14.6.1 |
| Browser | Microsoft Edge 131.0.2903.70 |

---
用户打开两个浏览器tab页，在其中一个tab页打开下拉选项的管理页，并删除某个选项后，另一个使用选项列表的tab页需要实时更新选项列表，用于提示用户此项已被删除

**Comment by 214132049** [comment]
希望可以更新展示，已提示用户。

**Comment by Wxh16144** [comment]
你删除 options  的时候， value 并没有被删除啊。 符合预期的

**Comment by afc163** [comment]
@Wxh16144 是对的。
