### ISSUE TITLE
邮箱校验问题

### ISSUE THREAD

**Issue by lovehall** [ant-design/ant-design#51813]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/qian-tao-jie-gou-yu-xiao-yan-xin-xi-antd-5-22-2-forked-vxk7g6?file=%2Fdemo.tsx%3A36%2C16-36%2C28)

### Steps to reproduce

直接复制「x-x_x@aa.com.my 」到Email选项输入框直接会校验通过但是末尾多了一个空格不符合邮件规范

### What is expected?

校验出不符合规范的邮箱地址，不是直接通过

### What is actually happening?

没校验出x-x_x@aa.com.my 后面的空格

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 17 |
| System | mac |
| Browser | chrome |

---
antd4或5版本都有问题，x-x_x@aa.com.my此类邮箱直接粘贴没校验出邮箱末尾的空格

**Comment by Wxh16144** [comment]
看了一下 async-validator 校验规则，应该是正则表达式不够完善。

https://github.com/react-component/async-validator/blob/0a02b9d1c946a1b63db6141d60425f4fbb8c4bca/src/rule/type.ts#L7-L10

临时解决方案是，HOC 一下输入框，将接收的内容 trim 一下，或者自己替换正则表达式。 🤔

**Comment by Wxh16144** [comment]
我的回答好像有些错误， string.match 和 regex.test 的结果貌似不一样。我再验证一下。

**Comment by Wxh16144** [comment]
破案了， [这次提交](https://github.com/react-component/async-validator/commit/a378e5d8f213827ec6ed3cce572d536d49a558c2) 支持某些 Unicode 字符导致的。应该不好操作了。 自己换回原来的正则表达式吧

```tsx
<Form.Item
      initialValue="x-x_x@aa.com.my "
      name={["user", "email"]}
      label="Email"
      rules={[
        {
          type: "string",
          // https://emailregex.com/
          //https://github.com/ant-design/ant-design/issues/51813
          pattern:
            /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
          message: "Invalid email address",
        },
      ]}
    >
      <Input />
    </Form.Item>
```

**Comment by lovehall** [comment]
> 你提供的复现地址中，后面的空格是一个[不间断的空格](https://codepoints.net/U+00A0) 刚好就匹配过了...
> 
> <img alt="image" width="405" src="https://private-user-images.githubusercontent.com/32004925/390748707-0ae3db9a-7c2d-42b6-a60b-29ff0010ca30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTc2NDYsIm5iZiI6MTczMjc5NzM0NiwicGF0aCI6Ii8zMjAwNDkyNS8zOTA3NDg3MDctMGFlM2RiOWEtN2MyZC00MmI2LWE2MGItMjlmZjAwMTBjYTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEyMzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGQ3OWZlZWNjNzMzY2JlYWE3NTQzOTUwMDU0NjAzYTQ4ODIwNjU3NWJmM2Q5NzBhYTZiMGIxN2FhYmE4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gGsSSYBJd_KZCXhjrdkRREvSoirWZfsK-2tJhNFnKaM">
> 如果是一个普通的空格还是能校验出来

确实是这样 感谢～我这通过额外加一个validator判断临时解决了 async-validator是否可以考虑进去？

**Comment by Wxh16144** [comment]
>  async-validator是否可以考虑进去？

看 core member 的决定吧， 个人感觉不好修复的。你看我前面提到的那个提交。 他把很大一个范围的 字符串都包括进去了

**Comment by zombieJ** [comment]
> 你提供的复现地址中，后面的空格是一个[不间断的空格](https://codepoints.net/U+00A0) 刚好就匹配过了...

牛逼，这真是发现不了……

Form 有个规则是 `whitespace` 可以配置空格，但是和你的 case 不一样。就是如你提到的，自行写个 rule 吧~
