### ISSUE TITLE
Header and Column Misaligned when navaigated through Tab

### ISSUE THREAD

**Issue by ashishgupta-sf** [ant-design/ant-design#51824]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-xz3sgr?file=%2Findex.html&workspaceId=35e0b665-6f95-46ba-ae6c-7db0c02f6e0e)

### Steps to reproduce

Press tab on a scrollable antd table. The table and headers misalign

### What is expected?

Header and columns should move together on pressing tab

### What is actually happening?

The table and headers misalign

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | ^18.0.0 |
| System | Apple M3 Pro |
| Browser | Version 130.0.6723.117 (Official Build) (arm64) |

**Comment by afc163** [comment]
<img width="1268" alt="图片" src="https://github.com/user-attachments/assets/5ce9d7f5-1653-499a-9a4d-6d32e213e7e7">

Can't see the problem.

**Comment by ashishgupta-sf** [comment]
Uploading Screen Recording 2024-11-29 at 11.35.20 AM.mov…
