### ISSUE TITLE
ColorPicker defaultValue can't be css string returned from toCssString() in gradient mode

### ISSUE THREAD

**Issue by antoniosk10** [ant-design/ant-design#51823]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/5njpjt?file=%2Fsrc%2FApp.js%3A12%2C11)

### Steps to reproduce

Use <ColorPicker mode={["gradient"]} /> as Form.Item with ability to normalise value as css string

### What is expected?

Css string returned from toCssString() method can be used as value for ColorPicker

### What is actually happening?

ColorPicker can't transform css string to Color object

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://ant.design/components/form#form-demo-getvalueprops-normalize

`normalize` should work with `getValueProps` to make sure ColorPicker get the right value.
