### ISSUE TITLE
table 组件设置了fixed后放大比例110% 改变页面高度会导致边框缺失

### ISSUE THREAD

**Issue by pigzzzzzz** [ant-design/ant-design#51830]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/mystifying-pond-j4yt8v)

### Steps to reproduce

边框设置fixed。页面比例放大到110%  高度要达到指定高度后，点击展开收起改变元素高度

### What is expected?

边框正常

### What is actually happening?

边框出现缺失

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18 |
| System | win10 |
| Browser | 谷歌131.0.6778.70 |

---
在搜索页面的时候，搜索表头是有高级查询的展开收起，但展开收起的时候会出现table 的边框缺失
![image](https://github.com/user-attachments/assets/ea4d760d-ff29-4882-bdfa-e6ab77812bd0)

**Comment by zombieJ** [comment]
duplicated of #51045

老生常谈的问题了，这个是浏览器的行为，组件侧做不了什么。
