### ISSUE TITLE
form.validateFieldsAndScroll() does not work properly while using textarea

### ISSUE THREAD

**Issue by gaoxt9** [ant-design/ant-design#5184]
#### Environment(required)

- antd version: 2.7.4
- OS and its version: macOS Sierra 10.12.3
- Browser and its version: Chrome  56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
When using Input's textarea in the Form, data can be validated but would not be scrolled to the target while clicking submit button.  There would be no problem after deleting type="textarea"

#### What do you expected?
scroll!!!

**Comment by afc163** [comment]
reinstall node_modules
