### ISSUE TITLE
Form.List 如果不传 isListField 会非常卡

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51848]
### Reproduction link

[[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/8usaz4?file=demo.tsx)](https://stackblitz.com/edit/react-jg6vu5?file=demo.tsx)

### Steps to reproduce

快速点击 remove

### What is expected?

删除无卡顿

### What is actually happening?

删除卡顿

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
嵌套 List 也卡 https://stackblitz.com/edit/react-jg6vu5-odh2zq?file=demo.tsx

**Comment by zombieJ** [comment]
`isListField` 添加与否是没有关系的，它现在版本已经不需要这个属性了。context 会传下去

**Comment by crazyair** [comment]
给 Form.List 加个 state，检测加载卸载，加载组件耗时很长

**Comment by zombieJ** [comment]
Updated. 新版本里修复了这个~

**Comment by afc163** [comment]
@zombieJ 在哪修复的，没关联到 issue
