### ISSUE TITLE
Checkbox or Radio component's root element will receive twice click event when user click span element that contained by label element.

### ISSUE THREAD

**Issue by iwfan** [ant-design/ant-design#51842]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-23dvqh)

### Steps to reproduce

Just click the text content of Checkbox / Radio, And see the different called count between component click and root element's click.

### What is expected?

The same call count is expected.

### What is actually happening?

The root element's click event are fired twice, This will popup file chooser dialog twice when you wrap Radio/Checkbox with Upload component.

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18 |
| System | Windows11 |
| Browser | Microsoft Edge 版本 131.0.2903.70 (正式版本) (64 位) |

---
The root cause is because of label element will relay the click event to input element when user clicked none Form-associated elements .

This behaviour are defined in [html spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element).

**Comment by zombieJ** [comment]
It's not recommend to bind event on native dom since it's out of React life cycle. But for Upload case in your demo, I think it's a good problem.
