### ISSUE TITLE
分页器

### ISSUE THREAD

**Issue by wuricong** [ant-design/ant-design#51850]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/dd2jpt?file=%2Findex.html%3A14%2C5)

### Steps to reproduce

无

### What is expected?

提供一个分页器 pageSize切换显示中英文的配置

### What is actually happening?

pageSize切换默认是英文 且无法变成中文

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.2.0 |
| System | 15.0.1 (24A348) |
| Browser | chrome  131.0.6778.86（正式版本） (arm64) |

**Comment by zombieJ** [comment]
https://ant-design.antgroup.com/components/config-provider-cn#config-provider-demo-locale
