### ISSUE TITLE
ant design tree node节点造成tree父节点前面的三角消失

### ISSUE THREAD

**Issue by yangguixue** [ant-design/ant-design#5186]
#### Environment(required)

- antd version:^2.0.0-beta.13
- OS and its version:  macOS Sierra 10.12.3
- Browser and its version: Chrome 56.0.2924.87 (64-bit)

#### What did you do? Please provide steps to re-produce your problem.
1.这样的代码可以正常显示，操作正常

```
{ topic.map(item => (
    <TreeNode title={item.name} key={item._id}>
      {
        part(item).map(p => (
          <TreeNode title={p.name} key={p._id} />
        ))
      }
    </TreeNode>
  ))}

```
正常如图
![image](https://cloud.githubusercontent.com/assets/22880233/23604470/ef35e544-0293-11e7-8791-a7cb70bd7266.png)

2.我想要在子节点的那一列的最后一个添加一个title是+的节点，所以添加了如下代码

```
{ topic.map(item => (
    <TreeNode title={item.name} key={item._id}>
      {
        part(item).map(p => (
          <TreeNode title={p.name} key={p._id} />
        ))
      }
      <TreeNode title="+" key={`${item._id}1`} /> //增加的那行代码
    </TreeNode>
))}

```

#### What happen?

此时变为如下状况，不知为何
![image](https://cloud.githubusercontent.com/assets/22880233/23604526/32bd9d0c-0294-11e7-8403-64a179f5100a.png)

**Comment by ddcat1115** [comment]
First check the validity of your TreeNode data built for the Tree, if not resolved, please provide the most simplified reproducible demo  

 http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by yangguixue** [comment]
http://codepen.io/anon/pen/KWgJeM?editors=0011

demo link

**Comment by afc163** [comment]
I think you codepen works just fine: 

<img width="202" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23640406/6bf0ab52-0328-11e7-9d38-35e2f89f4fd8.png">

**Comment by afc163** [comment]
You should use `antd@2.8.0` than `antd@2.0.0-beta.13` which is a old beta version a year ago.

**Comment by yangguixue** [comment]
![image](https://cloud.githubusercontent.com/assets/22880233/23640676/22eff73a-032a-11e7-80a9-2f7cdd7f75d1.png)
that's wrong

**Comment by afc163** [comment]
So it is a error?

<img width="1113" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23641098/79c77e8c-032c-11e7-8f39-76d870bdc5a9.png">

**Comment by yangguixue** [comment]
我上面标了注释的，注释的那部分是出bug的部分，我想要在二级菜单的最后一个都添加上一个+的treenode 但是我加上之后不会报错，而是二级菜单打不开了，demo上是直接就什么都没有了 @afc163 @afc163

**Comment by afc163** [comment]
Ok, I think it is a bug of antd.

**Comment by yangguixue** [comment]
![image](https://cloud.githubusercontent.com/assets/22880233/23641362/24a9cd0e-032e-11e7-8ac1-70446f7a0179.png)
那现在有没有办法可以让这两块分开的，彼此点击不会影响的办法，我先舍弃那个 @afc163

**Comment by yesmeck** [comment]
Reinstall node_modules.

自定义 node 内容可以参考 http://react-component.github.io/tree/examples/basic.html

**Comment by yangguixue** [comment]
你们这个改好了之后什么时候发版啊？ @afc163

**Comment by yesmeck** [comment]
@yangguixue 重新安装 node_modules 就可以了。

**Comment by yangguixue** [comment]
我重新npm install 了，然后按我之前的写法写，并不好使呢 @yesmeck

**Comment by yesmeck** [comment]
用 antd@2.8.0

**Comment by yangguixue** [comment]
是的
![image](https://cloud.githubusercontent.com/assets/22880233/23645184/cccbb102-0345-11e7-99ba-983f721f9615.png)
我刚把node_modules删了重新装的，清了缓存也不行。。
![image](https://cloud.githubusercontent.com/assets/22880233/23645210/f5265d3c-0345-11e7-8d88-6f04f6be94a2.png)
就是这个写法

**Comment by yesmeck** [comment]
上面的 commit 只修正了报错的问题，三角的的问题还没修正。

**Comment by yangguixue** [comment]
好的，🙏

**Comment by afc163** [comment]
三角的问题目前我们没有重现出来。

**Comment by yangguixue** [comment]
![image](https://cloud.githubusercontent.com/assets/22880233/23688921/3a50ad84-03f2-11e7-9fa7-8043efb0901b.png)
![image](https://cloud.githubusercontent.com/assets/22880233/23688938/5f5f8bfe-03f2-11e7-8fbd-c442b5949b0c.png)

**Comment by yesmeck** [comment]
三角问题也修正了。

**Comment by yangguixue** [comment]
我重新下载了node_modules，
![image](https://cloud.githubusercontent.com/assets/22880233/23779202/fd79ba70-0579-11e7-8ed7-72c83f0eb1a1.png)
还是这样，，，这个跟什么有关系么，是不是我哪里出错了

**Comment by yangguixue** [comment]
和之前的情况一样的

**Comment by yangguixue** [comment]
`<Tree>
          {[0, 1].map(i => (
            <TreeNode title={i} key={i}>
              {[2, 3].map(j => <TreeNode title={j} key={j} />)}
              <TreeNode title="4" key="4" />  //这个key在最外层遍历的时候，会有重复的吧，允许这样吗
            </TreeNode>
          ))}
        </Tree>`

**Comment by yesmeck** [comment]
是 antd@2.8 吗？

**Comment by yesmeck** [comment]
> 这个key在最外层遍历的时候，会有重复的吧，允许这样吗

对。同一层级的 key 不要有重复。

**Comment by yangguixue** [comment]
版本号是对的

![image](https://cloud.githubusercontent.com/assets/22880233/23780153/1827c4ce-0580-11e7-900f-7c3a2bc0b07f.png)

但是三角还是不出来，，不晓得怎么回事了

**Comment by yesmeck** [comment]
`rc-tree` 的版本呢？ `npm list rc-tree`。

**Comment by yangguixue** [comment]
![image](https://cloud.githubusercontent.com/assets/22880233/23780352/4e8d08ca-0581-11e7-9a09-5c254b66764f.png)

**Comment by yangguixue** [comment]
我在我这要import一下吗

**Comment by afc163** [comment]
npm list rc-tree

**Comment by yesmeck** [comment]
你自己的 `package.json` 里不需要有 `rc-tree` 的。

**Comment by yangguixue** [comment]
![image](https://cloud.githubusercontent.com/assets/22880233/23780922/bd8a7c0a-0584-11e7-8b8a-53491f087a72.png)

**Comment by yesmeck** [comment]
你是用的  `dist/antd.js` ?

**Comment by yangguixue** [comment]
![image](https://cloud.githubusercontent.com/assets/22880233/23780980/224e215a-0585-11e7-9e21-a4b4f3f9114e.png)

**Comment by yesmeck** [comment]
@ @ 好吧，能不能建个能重现的 repo 出来？

**Comment by yangguixue** [comment]
之前建的那个就和我的一样，
http://codepen.io/anon/pen/KWgJeM?editors=0011

只是这上边还有那个之前你处理过的那个报错，我不知道怎么改，

**Comment by yesmeck** [comment]
GitHub 上建个重现的仓库，codepen 上的 rc-tree 是旧版本。

**Comment by yangguixue** [comment]
我什么都没有改，然后写了一个demo，demo是好使的，然后现在，我又看我的项目，试了一下，解决了

**Comment by lijunzhou** [comment]
@afc163 @yesmeck 我也出现没有箭头的情况了，使用官方文档最简单的tree的例子的代码，都没有箭头。能点，就是看不见箭头。
└─┬ antd@2.12.6
  └── rc-tree@1.7.1

**Comment by benjycui** [comment]
@lijunzhou please file a new issue and provide an online demo. 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by lijunzhou** [comment]
@benjycui 我把antd降级后就可以了。2.12.5 => 2.9.3

**Comment by benjycui** [comment]
> @benjycui 我把antd降级后就可以了。2.12.5 => 2.9.3

我们需要排查问题，而不仅仅是解决你的问题。

 Please file a new issue and provide an online demo. Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by lijunzhou** [comment]
@benjycui 出现这个问题后，我直接使用了官方的tree的demo的代码，在我的环境中依然有这个问题。
https://ant.design/components/tree-cn/ 基本示例。
antd的版本是^2.12.5,,react 版本是^15.4.1 
如果有必要，我可以把package.json贴上来。

**Comment by afc163** [comment]
请提供可运行的 repo 和重现步骤，否则只能是猜来猜去。

---

Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by benjycui** [comment]
@lijunzhou 请确认你使用的 antd.css 与 antd.js 的版本一致。

**Comment by lijunzhou** [comment]
@benjycui 出现这个问题后，我重新把node_module文件夹删除了，重新安装的依赖。

**Comment by zhangzs000** [comment]
> [`没有前面的三角形__`](

- 
<img width="168" alt="aaaaaaaaaaaaa" src="https://user-images.githubusercontent.com/16148355/33873757-365ffd10-df57-11e7-9068-aaa600a8f014.png">

- [ ] 1. url

)

**Comment by zhangzs000** [comment]
"dependencies": {
    "antd": "^2.8.0",
