### ISSUE TITLE
extraStyle with layer result in duplicated "@layer antd" for table style

### ISSUE THREAD

**Issue by kennedy0527** [ant-design/ant-design#51867]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/6522p7)

### Steps to reproduce

1. 使用 AntdRegistry from @ant-design/nextjs-registry with layer 
2. 包住ConfigProvider

### What is expected?

Table header 成功吃到custom theme

### What is actually happening?

在nextjs 專案內 使用@ant-design/nextjs-registry
sample code如下
```jsx
<AntdRegistry layer>
    <Provider>{children}</Provider>
</AntdRegistry>
```
Provider 是另外封裝的 Antd ConfigProvider

瀏覽頁面 AntdRegistry 成功建立了一個Style tag with id `antd-cssinjs` 
但將其內容 複製出來 format後 檢查 發現table 的樣式 會多一個 `@layer antd `
這導致Table 沒辦法吃到 custom theme

刪除其中一個 `@layer antd` 就正常了
<img width="853" alt="Screenshot 2024-12-02 at 7 23 57 PM" src="https://github.com/user-attachments/assets/38f438e3-7468-47a1-be58-66e8a1dfdceb">

不確定是否是cssinjs 的問題

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| @ant-design/cssinjs | 1.22.0 |
| @ant-design/nextjs-registry | 1.0.1 |
| React | 18.3.1 |
| System | macOS 15.1.1 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
能剥离一个不带 nextjs 的最小重现不？排查链路有点长。

**Comment by Wxh16144** [comment]
> 能剥离一个不带 nextjs 的最小重现不？排查链路有点长。

饭前看了一下，我排查到 pro-component 的 pro-table 和 antd 的 table 一起用就会有问题

**Comment by kennedy0527** [comment]
> 能剥离一个不带 nextjs 的最小重现不？排查链路有点长。

https://codesandbox.io/p/sandbox/lsktjj

這個版本 是沒有nextjs的
直接將extraStyle的結果秀出來
但這次 duplicated `@layer antd` 並未出現在table 的style上
這次是出現在empty 的style上
<img width="747" alt="Screenshot 2024-12-03 at 10 23 07 PM" src="https://github.com/user-attachments/assets/d8fe8897-b7f6-4dd3-b5ee-62f4cc67e3a5">

有注意到 duplicated `@layer antd` 有可能不會出現在同個位置
但具體如何重現 目前還不知道

第一個nextjs 的版本 目前都是出現在table的style上

@Wxh16144 大 可能已發現根本原因
非常感謝

待 stylis 修復此問題後 會再進行測試

**Comment by MadCcc** [comment]
cssinjs 可以先兜个底 @Wxh16144
