### ISSUE TITLE
Controlled ellipsis expand/collapse

### ISSUE THREAD

**Issue by setyarp** [ant-design/ant-design#51877]
### Reproduction link

[https://ant.design/components/typography](https://ant.design/components/typography)

### Steps to reproduce

Sliding Controlled ellipsis expand/collapse got error.

### What is expected?

Should be not error.

### What is actually happening?

I think is from your component.

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | NextJS 15 |
| System | Windows |
| Browser | Brave Browser |

**Comment by IsKaros** [comment]
AntD 5 is not supported in nextjs 15 until react 19 is released.Maybe you can try nextjs@14.
