### ISSUE TITLE
col如果右对齐的话，和左对齐的col的内容高度不一致

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design#5187]
截图发不上来，请联系内网 @钟熊

**Comment by ddcat1115** [comment]
请提供下最简化的可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001

Please provide the most simplified reproducible demo   http://codepen.io/anon/pen/wGOWGW?editors=001

---

如果是内网，可以提供可重现的 [riddle](http://riddle.alibaba-inc.com/riddles/new) 片段  去[蚁问平台](http://ask.inc.alipay.net/) 或 Ant Design || Dva 咨询群提问~

**Comment by bf185003** [comment]
蚁问平台崩溃访问不了，ant design群的群号是多少？能用钉钉搜索到吗？或者请将钟熊拉进去。

**Comment by ddcat1115** [comment]
已拉入群，这里先close掉了~
