### ISSUE TITLE
RangePicker does not sync panel date when switching range inputs

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#51880]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/choose-time-antd-5-22-3-forked-42lxf6?file=%2Fdemo.tsx)

### Steps to reproduce

Click on start or end range input. While the popup panel is open, click on the other range input. 

### What is expected?

RangePicker panel date to be synced with its focused input field

### What is actually happening?

RangePicker panel calendar doesn't sync date when switching between input fields 

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 18 |
| System | Windows |
| Browser | Firefox |

---
This bug is present since v5.14.0. 
v5.13.3 worked as expected

**Comment by zombieJ** [comment]
Thanks for feedback. This is by design to keep stable to resolve user select one but next jumping. Instead to give the ability back, we offer the `pickerValue` prop to enable developer control the logic if needed.
