### ISSUE TITLE
virtual table 自定义srcollBar（禁用原生）后无法自动滚动跟随选中项。

### ISSUE THREAD

**Issue by CoCoManYY** [ant-design/ant-design#51888]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-jhugri?file=demo.tsx)

### Steps to reproduce

从第一行数据开始向下选区。
![20241204143355_rec_](https://github.com/user-attachments/assets/f2a1931c-00e2-4c21-8c2d-969ee3abc4cf)

放开原生的滚动条后，可正常自动滚动
![20241204143726_rec_](https://github.com/user-attachments/assets/9dbab85f-5fef-48d9-863a-a4b98ac32902)

### What is expected?

自动向下滚动。
参考其他的虚拟列表：
![20241204143430_rec_](https://github.com/user-attachments/assets/c66c618b-63ae-48e9-8541-c54f1bc928ac)

### What is actually happening?

未自动滚动

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 18.3.1 |
| System | macos 14.2.1 (23C71) |
| Browser | chrome 131.0.6778.86（正式版本） |

**Comment by CoCoManYY** [comment]
实际场景就是，我再开启了虚拟表格的情况下，还需要进行拖拽排序，现在无法自动滚动，拖拽排序无法从第一项拖动到最后一项。

**Comment by zombieJ** [comment]
嗯，可以加。
