### ISSUE TITLE
Suggestion for RangePicker

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#5188]
![image](https://cloud.githubusercontent.com/assets/4524983/23614640/98b172a8-02be-11e7-8abd-5bdcc19f7078.png)

当选择时间范围时 如果可以给用户可以看到 当前所选择的具体时间就好了.

当然 点击后控件最上方 本身就是显示的,  但是我面向的 是一些年龄40+ 不得不用的心态用户.

他们不会去关心 我们看起来很明显的内容, 更希望 汉字+相对醒目一些的显示方式

我截图文字颜色 为了配合整个界面的风格.   实际上肯定要深一些的. 

PS:英语实在太差, 无法相应官方的英语提问建议, 忘谅解.  谢谢.

**Comment by ddcat1115** [comment]
简单的标红可以解决问题么？

<img width="518" alt="2017-03-07 12 14 21" src="https://cloud.githubusercontent.com/assets/7017767/23618484/68d197d6-02cb-11e7-9074-004e3ab615f2.png">

**Comment by xjdata** [comment]
@ddcat1115  也是一种办法,  但是不够明显.  也许人们更希望知道 自己选择了多少天. 或者几个月. 这样对于用户来说也更人性化一点.

**Comment by ddcat1115** [comment]
如果想要提示选择了多长时间，能否在关掉选择面板后的输入控件下方自定义呢？因为除了配置了 showTime 的，其他日期选择都是选择后直接关掉弹框，在面板里提示了也看不到

**Comment by xjdata** [comment]
又提供了另一种方法. 当然也可以. 

我想着 哪里的事情 哪里解决  

毕竟 我们自己在进行某个控件的操作之后(心里暗示已经准确操作的) 谁还会去关注那个控件的结果呢

当然 也许只是我自己这么认为吧.  我那些最终用户 即便将你我说的办法都用上也许还是会说   我没看到啊....   呵呵.

**Comment by benjycui** [comment]
用户在移动鼠标的过程中，在他们 hover 的当前 end date 上用 Tooltip 显示，已选中 N 天可以?

**Comment by afc163** [comment]
楼主截图的高亮区域开放自定义渲染即可解决。

**Comment by benjycui** [comment]
@xjdata 还没实现，issue 应该保持 open..

**Comment by sangxiaolong** [comment]
@afc163 日期范围组件默认是左边显示当前月，右边显示下个月
![1](https://cloud.githubusercontent.com/assets/77712/23935853/90e72d52-0989-11e7-9bd6-7e4ccfed57c5.jpg)

能否增加个属性设置成打开时右边显示当前月，左边显示上个月呢，因为查看的大部分是历史数据，需要用户再手动点一下上个月再选择范围
![2](https://cloud.githubusercontent.com/assets/77712/23935858/94c37ba6-0989-11e7-8632-02f5aa795d83.jpg)

**Comment by benjycui** [comment]
@sangxiaolong 不要在别人的 issue 里面贴无关的信息。

Try `RangePicker[defaultPickerValue=[prevMonth, thisMonth]]`

**Comment by benjycui** [comment]
I think there is a better idea, will try it when have time..

**Comment by afc163** [comment]
I think it is most of RangePicker's way. No need to change it.

**Comment by benjycui** [comment]
我的想法行不通。。

**Comment by benjycui** [comment]
或这样。

![image](https://cloud.githubusercontent.com/assets/3580607/24391794/a5ad3210-13c3-11e7-822a-d2c41be96bd3.png)

就现在的信息而言，觉得 `extraFooterRender` 意义不大。

**Comment by afc163** [comment]
主要诉求是选择过程中可以实时展现信息吧。

**Comment by benjycui** [comment]
这个问题，感觉非常主观，无法提供一个能称之为解决方案的方案，先关吧。

**Comment by benjycui** [comment]
If we render customized footer to here, it will conflict with `Today` or `Back to today`.

![image](https://cloud.githubusercontent.com/assets/3580607/26617507/0b667f5a-4608-11e7-9ed2-3e55af0b8299.png)

**Comment by afc163** [comment]
<img width="484" alt="image" src="https://cloud.githubusercontent.com/assets/507615/26778173/cf1c26ee-4a12-11e7-9969-b2c176a9f4f1.png">

Add a extra footer.
