### ISSUE TITLE
[bug] 穿梭框组件的“反选当页”功能对树组件无效

### ISSUE THREAD

**Issue by ayangweb** [ant-design/ant-design#51882]
### Reproduction link

[https://ant-design.antgroup.com/components/transfer-cn#transfer-demo-tree-transfer](https://ant-design.antgroup.com/components/transfer-cn#transfer-demo-tree-transfer)

### Steps to reproduce

在树穿梭框的[官网示例](https://ant-design.antgroup.com/components/transfer-cn#transfer-demo-tree-transfer)中，将 Transfer 组件的 `showSelectAll={false}` 删除后，即可复现该问题。

https://github.com/user-attachments/assets/1267daf2-cba9-4d22-9f9f-d842adf7b236

### What is expected?

支持反选当页

### What is actually happening?

无效

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | ^18 |
| System | MacOS 14 |
| Browser | Chrome 版本 131.0.6778.86（正式版本） (arm64) |

**Comment by zombieJ** [comment]
自定义组件的反选逻辑需要自行实现，为了代码简单所以在 Demo 里是特地关闭了全/反选的展示：

<img width="888" alt="截屏2024-12-05 11 26 50" src="https://github.com/user-attachments/assets/45b7ee1b-8358-4a4e-a22c-8057b100515a">

如果有全反选需求，可以在 Demo 基础上继续改哈。并非是 bug。

**Comment by afc163** [comment]
@zombieJ demo 里留个备注？

**Comment by ayangweb** [comment]
@zombieJ 是示例里的这段代码吗？

<img width="829" alt="image" src="https://github.com/user-attachments/assets/239bb755-2ec6-4fe4-b6d8-15aaee698b6a">

**Comment by ayangweb** [comment]
Transfer 的 props 里并没有反选事件，我应该怎么手动实现呢？

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/1cf6fdf2-f273-4144-be03-6881a1c78186">
