### ISSUE TITLE
Table在sticky为true的情况下，当触发吸顶效果时，会出现双滚动条

### ISSUE THREAD

**Issue by chenduxiuhaha** [ant-design/ant-design#51893]
### Reproduction link

[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce

当页面很高，往下滚动的时候，滚动到表格底部，出现双滚动条

### What is expected?

期望滚动到底部时只有一个滚动条

### What is actually happening?

滚动到底部有两个滚动条

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 17 |
| System | window |
| Browser | chrome 版本 131.0.6778.86（正式版本） （64 位） |

**Comment by zombieJ** [comment]
有图看看么？

**Comment by LLmoskk** [comment]
@chenduxiuhaha  可以这样解决   https://github.com/ant-design/ant-design/issues/33762
.ant-table-sticky-scroll-bar {
    display: none;
 }

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/30868#issuecomment-1260524746
