### ISSUE TITLE
目前dropdown类的弹窗都是默认挂在到body并且关闭不会销毁，是否可以提供一个全局的参数可以配置是否销毁这个行为

### ISSUE THREAD

**Issue by dnwu** [ant-design/ant-design#51891]
### What problem does this feature solve?

1、有时候想把这些销毁，但是要在每个组件上配置相应的参数，并且有些没有提供相关参数的，例如datapicker
2、有时候在被suspense包括的时候，会出现动画的闪动，但是又不想关闭动画

### What does the proposed API look like?

在ConfigProvider新增全局参数， 修改是否销毁的这个默认行为

**Comment by zombieJ** [comment]
感觉是 xy 问题，Suspence 里闪动搞个重现看看？

**Comment by dnwu** [comment]
> 感觉是 xy 问题，Suspence 里闪动搞个重现看看？

https://github.com/ant-design/ant-design/issues/47563 类似于这个issue吧，
