### ISSUE TITLE
Tabs组件type="editable-card"，尺寸‘middle’和‘small’的高度存在问题，都是40px

### ISSUE THREAD

**Issue by ink0101** [ant-design/ant-design#51890]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-xzkzrl?workspaceId=ws_KwHfjpbGthMLp5vHBokRDq)

### Steps to reproduce

切换尺寸，查看高度

### What is expected?

size=small，高度为36px

### What is actually happening?

size=small，高度为40px

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 18 |
| System | windows11 |
| Browser | chrome 131.0.6778.86 |

**Comment by ink0101** [comment]
应该是修改这个问题引入的：https://github.com/ant-design/ant-design/issues/46584

**Comment by afc163** [comment]
@hzyhbk 看看？
