### ISSUE TITLE
移动端点击可点击区域时，可点击区域内会出现背景色

### ISSUE THREAD

**Issue by Meetacoo** [ant-design/ant-design#51907]
### What problem does this feature solve?

在移动端时，点击可点击区域，移除点击时出现的背景色效果

### What does the proposed API look like?

新增一个参数或者直接将移动端点击效果去掉

**Comment by Meetacoo** [comment]
https://github.com/user-attachments/assets/942d2a61-c0f8-4669-8843-21639ebcc5f6

此处是有问题的效果视频

**Comment by zombieJ** [comment]
如果是反馈 bug，请用 bug 模板提交 issue。不带重现的 issue 是无法查看问题的。这里就先关了哈~
