### ISSUE TITLE
DatePicker, RangePicker javascript API to show time picker

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#5190]
In the `DatePicker` and `RangePicker` it would be useful to have a javascript API to open the time picker. I want to open the time picker interface after the user selects a date instead of having the user click the select time picker to update the time. This would force the user to acknowledge the time they've set.

**Comment by benjycui** [comment]
How about:

```jsx
DatePicker[mode=year|month|date|time] 
DatePicker[onPanelChange(mode): void]
```

We can set which panel are showed now, and listen to panel change.

**Comment by megawac** [comment]
Yeah that would meet my needs; it would also be nice to be able to detect if a value was changed with the date picker or time picker. Though this can be inferred at the moment so it is not a big deal

**Comment by benjycui** [comment]
So, just, similar to https://ant.design/components/calendar/:

```jsx
DatePicker[mode=year|month|date|time] 
DatePicker[onPanelChange(value, mode): void]
```

**Comment by badplum** [comment]
DatePicker[mode=year|month|date|time] 

This one is very useful.

**Comment by benjycui** [comment]
You can try to PR.

**Comment by benjycui** [comment]
After we implement this feature, we can make RangePicker works like RangeYearPicker, RangeMonthPicker, RangeTimePicker:

```jsx
<RangePicker format="YYYY" showPanels={['year', 'year']} />
<RangePicker format="YYYY-MM" showPanels={['month', 'month']} />
<RangePicker format="HH:mm:ss" showPanels={['time', 'time']} />
```

**Comment by ueedon** [comment]
Is there a schedule ?

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/calendar/pull/284

**Comment by beiduo** [comment]
this feature would be really awesome! (just looking for if there is any official solution with month range picker then found this exciting message and really thrilled for it)

**Comment by jkim506** [comment]
https://ant.design/components/date-picker/

Under 'controlled panels', it shows DatePicker using modes and onPanelChanged but these typings are only on RangePicker. Also, the example shown isn't even working.

**Comment by aibaiejoy** [comment]
<RangePicker format="YYYY" showPanels={['year', 'year']} />
<RangePicker format="YYYY-MM" showPanels={['month', 'month']} />
<RangePicker format="HH:mm:ss" showPanels={['time', 'time']} />


这个showPanels 的api在3.0以上的最新版本里面，有api吗？没有看到。

**Comment by OPY-bbt** [comment]
现在还没支持showPanels吗？
