### ISSUE TITLE
Select 多选模式默认开启搜索但是搜索不出内容

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51906]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-aa3a2w?file=demo.tsx)

### Steps to reproduce

搜索张三

### What is expected?

能搜到

### What is actually happening?

不能搜到
![image](https://github.com/user-attachments/assets/80fa65ad-ea31-419a-ba84-204054517ebb)

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by Wxh16144** [comment]
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/ff4bc81a-eb16-4dfb-b9b0-840404da830d">

**Comment by crazyair** [comment]
应该是默认行为吧？

**Comment by zombieJ** [comment]
`label` 可以是 ReactNode，所以以 `value` 为准。

**Comment by crazyair** [comment]
可以判断如果 label 不是元素，默认是 label，如果 label 是元素就默认 value？

**Comment by zombieJ** [comment]
那太随机了，你上一行代码还是好的。然后改了一个为 ReactNode，行为挂了。如果需要可以 HOC 一下。

**Comment by Wxh16144** [comment]
回旋镖？ https://github.com/ant-design/ant-design/issues/49415, 有 filterOption 选项了，完全可以自己定义了呀

**Comment by crazyair** [comment]
> 那太随机了，你上一行代码还是好的。然后改了一个为 ReactNode，行为挂了。如果需要可以 HOC 一下。

说实话，我这边有2个方案

1、搜索是默认 value label 2个的，可以更兼容，比如：value: zan.zhang label: 张三，就可以输入拼音就能搜索到，类似钉钉搜人的效果
2、label 我这里会用一个 getText 方法获取元素的文本内容，用这个搜索

**Comment by crazyair** [comment]
> 回旋镖？ #49415, 有 filterOption 选项了，完全可以自己定义了呀

讨论的是2个事情，那个已经改了示例

**Comment by Wxh16144** [comment]
没必要纠结搜索的是 label 还是 value，感觉像是 api 太老了，况且 options 不一定只有这几个选项，如果有自定义字段，那 antd 组件搜索是不是也遍历所有的 key 和 value呢。 直接用前面提到的 filterOption 更合理。

**Comment by crazyair** [comment]
是这样的，比如你 Select 开启多选后，会默认开启搜索功能，导致用户使用就会出现 BUG，搜不到内容

**Comment by crazyair** [comment]
要保证最简单的 demo，是没有 bug 的

**Comment by zombieJ** [comment]
搞 CP 支持全局配置会好点，不要去默认做这个事情

**Comment by crazyair** [comment]
> 搞 CP 支持全局配置会好点，不要去默认做这个事情

放开不是收紧，还好吧？

**Comment by crazyair** [comment]
不是啊，都说了，现在不是多选，产品要求支持多选，一般人只会加 `mode="multiple"` 导致上线了，用户发现可以搜索，但是搜索不到内容，就说是 bug

**Comment by Wxh16144** [comment]
额.. 算是业务bug，不过对组件不熟悉/文档没细看的开发者确实难搞。

看起来不是搜索的问题，而是 `showSearch` 的行为

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/119423f8-ec65-453b-b186-2aae5076117c">

**多选情况下，默认开启了搜索**

**Comment by crazyair** [comment]
其实从一开始搜索就可以健壮些，这是辅助功能，能搜跟不能搜，体验完全不一样

**Comment by Wxh16144** [comment]
> 其实从一开始搜索就可以健壮些，这是辅助功能

这又回到前面那个去了， antd 搜索

1.`value` 和 `label` 以及 `[fieldNames.label]` ，`[fieldNames.value]` 呢，

2.还是一整个 option 的所有 value

不好定这个度。 诚然第一种可能更好。

**Comment by crazyair** [comment]
不需要所有，只需要 提交的字段跟显示就可以，当然提交的 pro 的功能，antd 其实不用支持

**Comment by Wxh16144** [comment]
那就改进搜索， 将 `value` 和 `label` 以及 `[fieldNames.label]` ，`[fieldNames.value]` 的 value 都过一遍搜索判断。

感觉最坑的还是 **多选情况下，默认开启了搜索** 。 select 的搜索还是用最新的 `filterOption` 自己控制好了。 不过目前估计是不好改了。 让大佬评估一下 丢 v6 计划去吧。

**Comment by Wxh16144** [comment]
顺手贴一个 `filterOption` 的示例好了，方便别人也追溯到这里

```tsx
import React from 'react';
import { Select } from 'antd';
import { toLower, isString, isNumber,values } from 'lodash-es';

const compareString = (str1: string, str2: string) =>
  toLower(`${str1}`).includes(toLower(`${str2}`));

const isSearchableValue = (value: any) => isString(value) || isNumber(value);

const App: React.FC = () => (
  <Select
    showSearch
    placeholder="Select a person"
    filterOption={(input, option) => 
      values(option)
        .some((value) => isSearchableValue(value) && compareString(value as string, input))
    }
    options={[
      { value: '1', label: 'Jack', job: 'developer' },
      { value: '2', label: <strong>Lucy</strong>, job: 'designer' },
      { value: '3', label: 'Tom', job: 'manager' },
    ]}
  />
);

export default App;

```

**Comment by crazyair** [comment]
我现在都是这样用 

```tsx
    filterOption: (input, option) => {
        const str = getText([option?.value, option?.label]).join('');
        return str.toLowerCase().includes(input.toLowerCase());
    },
```

**Comment by purple-force** [comment]
> 那就改进搜索， 将 `value` 和 `label` 以及 `[fieldNames.label]` ，`[fieldNames.value]` 的 value 都过一遍搜索判断。
> 
> 感觉最坑的还是 **多选情况下，默认开启了搜索** 。 select 的搜索还是用最新的 `filterOption` 自己控制好了。 不过目前估计是不好改了。 让大佬评估一下 丢 v6 计划去吧。

总要被坑一回😂
