### ISSUE TITLE
DatePicker 在多选的情况下， 展开日期面板后，再点击iframe区域， 无法关闭面板

### ISSUE THREAD

**Issue by DrMuda** [ant-design/ant-design#51903]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/gfzwl8)

### Steps to reproduce

1. 点击任意一个日期选择器，展开日期面板
2. 点击下方的iframe区域

### What is expected?

在步骤2点击iframe区域时， 日期选择器的日期面板应和点击非iframe区域时一样， 会关闭日期面板

### What is actually happening?

日期面板并没有关闭

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 18.2.0 |
| System | macos13 |
| Browser | chrome 131.0.6778.86 |

---
业务场景：页面嵌入 metabase 或其他BI报表， 并接管筛选项时， 该问题会导致自定义的筛选栏用起来不太舒服

**Comment by zombieJ** [comment]
`iframe` 里的事件是不会冒泡出来的，这个是浏览器限制。组件库层面做不了什么，如果你有混合使用的需求，可以在 iframe 里加 postMessage 把点击事件扔出来，然后外部 DatePicker 通过 `open` 受控来关闭。

**Comment by DrMuda** [comment]
> `iframe` 里的事件是不会冒泡出来的，这个是浏览器限制。组件库层面做不了什么，如果你有混合使用的需求，可以在 iframe 里加 postMessage 把点击事件扔出来，然后外部 DatePicker 通过 `open` 受控来关闭。

但是为何`Select`组件在同样是多选的情况下， 不会有这个问题呢(我的复现链接增加了这个实例)？ 我的理解是当它们是单选时， 可以选中之后直接关闭面板， 而多选则需要点击面板区域外才关闭。多选的 Select 和 DatePicker 理论上可以使用相同的 “判断是否点击了面板区域外” 的方法
