### ISSUE TITLE
antd5.22.3 中 datepicker 设置为中文时故障, 里面使用dayjs给定默认值报错, 不给默认值里面就是英文的

### ISSUE THREAD

**Issue by BuyTmall** [ant-design/ant-design#51902]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/fast-flower-jyh2k9?file=%2Findex.html)

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

1

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 18 |
| System | window11 |
| Browser | chrome 131.0.6778.87 |

---
解决这个bug

**Comment by zombieJ** [comment]
你的重现里没有设置中文的代码。
