### ISSUE TITLE
react v19, Fragment as Space children not spaced

### ISSUE THREAD

**Issue by magicdawn** [ant-design/ant-design#51918]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/react-v19-space-cvqzg5?file=%2Findex.tsx%3A27%2C67)

### Steps to reproduce

react v18
https://codesandbox.io/p/sandbox/react-v18-space-7kzftc?file=%2Findex.tsx%3A3%2C22&workspaceId=ws_Xc5CpgbTZxP3dGSddpet5R
![image](https://github.com/user-attachments/assets/a56d12ed-ed35-4e06-a81f-8c60b88435b6)

react v19
https://codesandbox.io/p/sandbox/react-v19-space-cvqzg5?file=%2Findex.tsx%3A27%2C67
![image](https://github.com/user-attachments/assets/2546fb3a-05e9-4d9e-81c2-7733255d736f)

### What is expected?

有 space

### What is actually happening?

没有 space

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 19.0.0 |
| System | macOS |
| Browser | 版本 131.0.6778.87（正式版本） (arm64) |

**Comment by ppjjzz** [comment]
react 19 下一点击 button 还会报错
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/951ce1fb-8065-4332-baa5-e6a9900e857e">

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/discussions/51919

**Comment by MissNanLan** [comment]
@magicdawn  Fragment 为什么会有间距呢，它是个虚拟的包装器组件
