### ISSUE TITLE
Tag 动态删除异常

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#51926]
### Reproduction link

https://codesandbox.io/p/sandbox/yu-fa-tang-antd-5-22-3-forked-6vpv9m?file=%2Fdemo.tsx%3A18%2C20

### Steps to reproduce

点击 2 

### What is expected?

应该留下 2 3 （demo 中写死的）

### What is actually happening?

只留下 3 

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Tag 有个历史债一直继承下来了。

<img width="878" alt="图片" src="https://github.com/user-attachments/assets/8f775ac9-6210-48a4-a89d-1322fc7989d7">

**Comment by crazyair** [comment]
可以加个 新 close api，然后旧的 onClose 废弃，就能过度了

**Comment by crazyair** [comment]
但是本来就是点自己，但是关了2个？

**Comment by afc163** [comment]
```diff
    <div>
      {list.map((item, index) => (
        <Tag
          key={index}
          closable
          onClose={(e) => {
+           e.preventDefault();
            setList([1, 3]);
          }}
        >
          {item}
        </Tag>
      ))}
    </div>
```

去掉默认的行为就好了。
