### ISSUE TITLE
tabs默认选择非第一项时，ant-tabs-ink的transform距离出现偏差

### ISSUE THREAD

**Issue by cherryrui** [ant-design/ant-design#5192]
```
<Tabs type="card" defaultActiveKey={this.state.process.id+""} onChange={this.changeProcess.bind(this)}>
	{this.state.process_list.map(item => {
		return <TabPane tab={item.name} key={item.id+""}></TabPane>;
	})}
/Tabs>
```
version：2.8.0
当默认tab非第一项时，ant-tabs-ink的transform距离出现偏差，不能正确出现在tab的正下方

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

And **please** follow issue template to report bug.

**Comment by afc163** [comment]
It works fine as you description: http://codepen.io/anon/pen/jBMJrm?editors=001

And there should be no `ant-tabs-ink` when `type="card"`.

**Comment by cherryrui** [comment]
我使用的是line模式，问题的前提是在Modal中使用，采用card不会出现这个问题

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

@cherryrui

**Comment by walking11** [comment]
![image](https://cloud.githubusercontent.com/assets/14257970/25606711/798355b4-2f45-11e7-9775-4bb5390620d9.png)
我这也是这个问题，小概率出现transform偏差

**Comment by minzhang2** [comment]
我也遇到这个问题，前提是在modal里面含有一个tabs，小概率事件会出现，@abc163
