### ISSUE TITLE
Motion elements is not smooth first time opening

### ISSUE THREAD

**Issue by alexander-lipnitskiy** [ant-design/ant-design#51924]
### Steps to reproduce

I have some laggs in my electron app, when first time openning modal or drawer(flickering, not smooth). Second time and so on it's open smoothly

### What is expected?

smoothly open

### What is actually happening?

flickering, not smooth

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 18.3.3 |
| System | Windows |
| Browser | Google 131.0.6778.109 |

**Comment by alexander-lipnitskiy** [comment]
It's happening in Electron Application... I can't reproduce this issue in browser

**Comment by afc163** [comment]
Could you post a minimal github repo to reproduce?

**Comment by alexander-lipnitskiy** [comment]
Well, I couldn't repeat with the minimal app. It seems like a have some optimization issues in my project

> Could you post a minimal github repo to reproduce?

**Comment by alexander-lipnitskiy** [comment]
https://github.com/alexander-lipnitskiy/electron-app-modal-antd

**Comment by alexander-lipnitskiy** [comment]
if you will open in browser ( http://localhost:5173/)  it will work smooth, but in electron app it has lags

**Comment by alexander-lipnitskiy** [comment]
I found soultion: app.disableHardwareAcceleration()
