### ISSUE TITLE
tree can not add TreeNode

### ISSUE THREAD

**Issue by yangguixue** [ant-design/ant-design#5193]
#### Environment(required)

- antd version:^2.0.0-beta.13
- OS and its version:macOS Sierra 10.12.3
- Browser and its version:Chrome 56.0.2924.87 (64-bit)

#### What happen?
http://codepen.io/anon/pen/KWgJeM?editors=0011 @ddcat1115

demo link

**Comment by afc163** [comment]
`^2.0.0-beta.13`?

Use `2.8.0`.

And it seems to be a duplicated codepen as #5186
