### ISSUE TITLE
flex - the table of the grid of the scroll bar under ie11 and ege browser does not support the mouse wheel

### ISSUE THREAD

**Issue by shadow-Fiend** [ant-design/ant-design#5194]
As long as the mouse wheel rolling will report error.
![1488857678 1](https://cloud.githubusercontent.com/assets/24544648/23640699/431362ae-032a-11e7-8657-0c25f21c60bc.png)
![1488857759 1](https://cloud.githubusercontent.com/assets/24544648/23640698/430f2478-032a-11e7-9e11-78889f978be6.png)
Hope the great god help to solve this problem, thank you!

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by afc163** [comment]
Have you import es6-shim or babel-polyfill?

**Comment by afc163** [comment]
closing for cannot reproduce.
