### ISSUE TITLE
我想知道一个组件的类型

### ISSUE THREAD

**Issue by sidecity-li** [ant-design/ant-design#51947]
### What problem does this feature solve?

通过组件的类型，确定出用户的点击位置，比如用户点击了title为xxx的对话框，文案为xxx的按钮，从而做到埋点上报自动化

### What does the proposed API look like?

给每一个组件都添加一个标志，用户标记这个组件的类型，例如：
Modal.displayName = 'Modal'
Button.displayName = 'Button'

**Comment by zombieJ** [comment]
按照业界标准的做法，`displayName` 并不会在 Prod 下添加，都会被压缩成非语义化的组件名。如果你需要做埋点上报，可以考虑通过 className 来获取对应的组件类型。这在现在的 antd 的组件上都是有的哈~

**Comment by sidecity-li** [comment]
@medayz 这种做法会不会不太好，另外我有点担心会有这样的情况，比如说Tabs上有一个class tabs, TabPanel上也有个class tabs，如果存在这种情况的话，我就识别不出来这个是tabs组件还是tabpane组件
