### ISSUE TITLE
【DatePicker】 React 18   DatePicker 情况下，开启 allowClear 时点击清除内容会错误触发面板打开 

### ISSUE THREAD

**Issue by pipi-1997** [ant-design/ant-design#51946]
### Reproduction link

https://codesandbox.io/p/sandbox/ji-ben-antd-4-24-12-forked-j6dsl2?file=%2Fdemo.tsx

### Steps to reproduce

点击 allowClear icon ，日期面板会错误打开，在React 16与17环境下不会

### What is expected?

清除日期内容，日期面板不打开

### What is actually happening?

清除日期内容，日期面板弹出

| Environment | Info |
| --- | --- |
| antd | 4.24.12 |
| React | 18.2.0 |
| System | macos 14.5 (23F79) |
| Browser | chrome  131.0.6778.86 |

**Comment by zombieJ** [comment]
感谢反馈。不过 v4 已经过了维护期1年了哈，不会再处理相关问题了~

**Comment by pipi-1997** [comment]
> 感谢反馈。不过 v4 已经过了维护期1年了哈，不会再处理相关问题了~

v4是否有相对稳定的版本可以支持 React 18 呢，网络中似乎有找到4.24.20的版本，但是实际npmjs中找不到
