### ISSUE TITLE
Select 选择器 无法选中文本

### ISSUE THREAD

**Issue by cccsaber** [ant-design/ant-design#51955]
### What problem does this feature solve?

有一个 姓名选择器   选择某一个名称后 想复制 这个名称出来

### What does the proposed API look like?

最好是 有个开关就好了

**Comment by cccsaber** [comment]
因为我要维护1000多张表单，每个表单里面有大量的 <a-select>组件调用，所以来官方这边请教

**Comment by Wxh16144** [comment]
antd 没有提供自定义 Select 的触发器功能，或者你可以另辟蹊径。

1. 二次封装一个组件。可以点击复制 Select 选中值。

```tsx
import { CopyOutlined } from "@ant-design/icons";
import {
  Space,
  Select,
  Button,
  Tag
} from "antd";

const App = () => {

  return (
    <div style={{ margin: 120 }}>
      <Space.Compact>
        <Select
          // prefix={<Tag color="blue">姓名:</Tag>}
          options={[
            {
              label: "张三",
              value: "zhangsan"
            },
            {
              label: "李四",
              value: "lisi"
            },
            {
              label: "王五",
              value: "wangwu"
            }
          ]}
        />
        <Button
          type="primary"
          icon={<CopyOutlined />}
          onClick={() => {
            alert("Hello, World!");
          }}
        />
      </Space.Compact>
    </div>
  );
}

export default App;

```
<img width="187" alt="image" src="https://github.com/user-attachments/assets/216ed5fb-19d4-47e3-8d7f-6a3e9bfab599">



或者其他通过样式覆盖重写触发器逻辑。

**Comment by cccsaber** [comment]
> antd 没有提供自定义 Select 的触发器功能，或者你可以另辟蹊径。
> 
> 1. 二次封装一个组件。可以点击复制 Select 选中值。
> 
> ```tsx
> import { CopyOutlined } from "@ant-design/icons";
> import {
>   Space,
>   Select,
>   Button,
>   Tag
> } from "antd";
> 
> const App = () => {
> 
>   return (
>     <div style={{ margin: 120 }}>
>       <Space.Compact>
>         <Select
>           // prefix={<Tag color="blue">姓名:</Tag>}
>           options={[
>             {
>               label: "张三",
>               value: "zhangsan"
>             },
>             {
>               label: "李四",
>               value: "lisi"
>             },
>             {
>               label: "王五",
>               value: "wangwu"
>             }
>           ]}
>         />
>         <Button
>           type="primary"
>           icon={<CopyOutlined />}
>           onClick={() => {
>             alert("Hello, World!");
>           }}
>         />
>       </Space.Compact>
>     </div>
>   );
> }
> 
> export default App;
> ```
> 
> <img alt="image" width="187" src="https://private-user-images.githubusercontent.com/32004925/393795542-216ed5fb-19d4-47e3-8d7f-6a3e9bfab599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTUwNDMsIm5iZiI6MTczMzc1NDc0MywicGF0aCI6Ii8zMjAwNDkyNS8zOTM3OTU1NDItMjE2ZWQ1ZmItMTlkNC00N2UzLThkN2YtNmEzZTliZmFiNTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE0MzIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjkwMmEzODE1MWM1MGU1MDNkMmYzODNhOGM0OGQ4MDAwOGI0NjBiMWM2ZjMyZjMwNjhlNmJiZWM0YzM5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JrUL7FBAdh09pWmcgNxhEgDwXQREAGc9lEn-ZS_dEfo">
> 或者其他通过样式覆盖重写触发器逻辑。

我记得2.0一个版本 选项框里面的内容是可以选中 然后 ctrl + c 复制出来的

**Comment by Wxh16144** [comment]
2.0 太远古了，我接触的只有4 和5，你这个问题可以看看 core member 有没有更好的建议吧～

**Comment by MadCcc** [comment]
不考虑支持，设计上就是不可选中的。可以考虑上面的 workaround

**Comment by whale2002** [comment]
遇到了同样的问题，select 组件在 disabled 状态下无法复制文本。看这篇博客解决的 https://www.cnblogs.com/zpy521hl/p/17807269.html
