### ISSUE TITLE
Pagination组件showSizeChanger属性设置showSearch: false无效

### ISSUE THREAD

**Issue by rongcl9219** [ant-design/ant-design#51961]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/geng-duo-antd-5-22-2-forked-d7mhsz?workspaceId=ws_QN8hkEJiJywWV8PuvheVzk)

### Steps to reproduce

Pagination组件showSizeChanger属性设置showSearch: false

### What is expected?

设置showSearch: false生效，取消搜索

### What is actually happening?

设置后仍然有搜索

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | Google Chrome 131.0.6778.109 |

**Comment by alex-word** [comment]
showSizeChanger  type boolean | SelectProps 支持 SelectProps 设置参数 不能控制 希望尽快修复

**Comment by alex-word** [comment]
showSizeChanger type boolean | SelectProps 支持 SelectProps 设置参数 不能控制 希望尽快修复 @petercat-assistant
