### ISSUE TITLE
modal支持类似el-dialog的sizable

### ISSUE THREAD

**Issue by softboy99** [ant-design/ant-design#51965]
### What problem does this feature solve?

一些对话框需要用户可以交互式的改变对话框大小

### What does the proposed API look like?

类似el-dialog的sizable

**Comment by Wxh16144** [comment]
类似的问题有 #16613

**Comment by softboy99** [comment]
Hi,@Wxh16144 , 拖曳和最大化功能已经有了

**Comment by MadCcc** [comment]
需求是合理的，但是 antd 目前没有集成拖拽的三方包，如果只有 resizable 的话会比较奇怪。可以先自行封装实现一个

**Comment by afc163** [comment]
Duplicate of #32604
