### ISSUE TITLE
antd@5.22.4不兼容nextjs@15与react@18版本

### ISSUE THREAD

**Issue by jm1jm2jm** [ant-design/ant-design#51963]
### Reproduction link

[http://123.com](http://123.com)

### Steps to reproduce

安装antd，nextjs 与react最新版本，然后运行

### What is expected?

不出现任何语法兼容

### What is actually happening?

SyntaxError: Cannot use import statement outside a module
    at <unknown> (/Users/jo.liao/work/elchk-console-web/node_modules/rc-util/es/React/render.js:1)

| Environment | Info |
| --- | --- |
| antd | 5.22.4 |
| React | 18.3.1 |
| System | 131.0.6778.86（正式版本） (arm64) |
| Browser | chrome |

**Comment by zombieJ** [comment]
* nextjs 15 用的是 React 19，不支持 18。
* 目前 antd 本身是不支持 React 19。
* `Cannot use import statement outside a module` 是配置问题，不是 antd 的问题。
