### ISSUE TITLE
Typography 排版 官网组件有bug

### ISSUE THREAD

**Issue by yufengshaobiao** [ant-design/ant-design#51969]
### Reproduction link

[https://ant-design.antgroup.com/components/typography-cn](https://ant-design.antgroup.com/components/typography-cn)

### Steps to reproduce

直接拖到最大

### What is expected?

不应该有bug

### What is actually happening?

不应该有bug

| Environment | Info |
| --- | --- |
| antd | 5.22.4 |
| React | react1 |
| System | windows |
| Browser | google |

**Comment by yufengshaobiao** [comment]
![企业微信截图_17338244908963](https://github.com/user-attachments/assets/3dc1fc82-8a4d-4593-bec3-2e34cbd81592)
![企业微信截图_17338242853537](https://github.com/user-attachments/assets/8acac4ec-1f63-46ec-a1b4-f97e3e4adfd5)

**Comment by yufengshaobiao** [comment]
![企业微信截图_17338246539951](https://github.com/user-attachments/assets/a95bd79e-a2e1-472a-a4ba-8e6e107f422f)

**Comment by yufengshaobiao** [comment]
在最大处 来回拖动，官网有报错
![企业微信截图_17338246539951](https://github.com/user-attachments/assets/ea11c0bc-9b38-4338-9ff4-da3ee16ad16d)

**Comment by MadCcc** [comment]
给个录屏看看，我这里没有复现

**Comment by xiaochena** [comment]
https://github.com/user-attachments/assets/2e8fa70e-f275-42c8-b215-98b343f484f0
@MadCcc
