### ISSUE TITLE
pagination  showSizeChanger 设置 showSearch false 无效

### ISSUE THREAD

**Issue by alex-word** [ant-design/ant-design#51975]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-antd-5-22-4-forked-jw6s5y?file=%2Fdemo.tsx%3A14%2C1)

### Steps to reproduce

直接点pagesize  select 

### What is expected?

既然已经支持了SelectProps ，应该支持selectProps的参数

### What is actually happening?

点击框默认showSearch ：true  然后传参数无法修改

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3.1 |
| System | macOs 14.3.1 |
| Browser | 130.0 |

**Comment by alex-word** [comment]
@petercat-assistan 这个他是支持SelectProps 但是还是不行

**Comment by Wxh16144** [comment]
![Uploading image.png…]()

看起来是不行，可以自己先用 `selectComponentClass`  重写 Select 。 但是前两天说这个 api 在下一个大版本会废弃。

**Comment by MadCcc** [comment]
Fixed in 5.22.5
