### ISSUE TITLE
npm 安装 dva-cli后无法使用dav -v命令

### ISSUE THREAD

**Issue by kentTanL** [ant-design/ant-design#5197]
## 问题描述

下面是项目实战中的一段原文：
>
 #### 安装 dva-cli

通过 npm 安装 dva-cli 并确保版本是 `0.7.0` 或以上。

```bash
$ npm install dva-cli -g
$ dva -v
0.7.0
```
>END

但是在执行完 `npm install dva-cli -g` 之后，我无法立即使用 `dva -v` 命令，多次重复依然无法使用。

## 解决办法

在系统的环境变量 `PATH` 配置 nodejs\node_global 目录，方可。

建议：因为非专业前端开发，很少使用类似的产品，所以只能跟着文档的流程走，但是一旦出错则有点无头绪，所以希望能在文档中描述可能出现的意外，感谢

**Comment by afc163** [comment]
感谢提示。

**Comment by afc163** [comment]
不过说实话，npm 和 node 的环境问题可能有几百种，我们作为前端组件的问题不可能涵盖所有的情况。

**Comment by kentTanL** [comment]
嗯嗯，感谢回复  因为我做后端开发，对前端的这些框架还不太了解，正在开始学习中，感谢你们能开源这么棒的产品:hreat_eyes:
