### ISSUE TITLE
TransferItem 能否支持 hide 属性

### ISSUE THREAD

**Issue by OriginRing** [ant-design/ant-design#51974]
### What problem does this feature solve?

Transfer 的值在部分情况下不展示在列表中，但是又希望默认选中且不展示的值传递出来

### What does the proposed API look like?

hide: boolean

**Comment by Wxh16144** [comment]
> 不展示在列表中

已选择 xx 项怎么显示呢？ 不如开发者自己追加隐藏的值。

**Comment by MadCcc** [comment]
详细讲一下需求吧，为什么会有隐藏的 item

**Comment by zombieJ** [comment]
https://ant-design.antgroup.com/docs/blog/to-be-what-you-see-cn

参考一下这个文章，组件应该“所见即所得”

**Comment by OriginRing** [comment]
> > 不展示在列表中
> 
> 已选择 xx 项怎么显示呢？ 不如开发者自己追加隐藏的值。

已选择项可以过滤 hide:true

**Comment by OriginRing** [comment]
> 详细讲一下需求吧，为什么会有隐藏的 item

这个值在返回配置里默认给用户设置了，当前因未完善交互上先不透露，但保存时这个值也要传过去

**Comment by MadCcc** [comment]
antd 的组件会保持所见即所得的原则，所以不会提供类似的 api。可以通过其他方式魔改一下
