### ISSUE TITLE
Select组件在Modal中，弹出面板样式有问题

### ISSUE THREAD

**Issue by catmiao8** [ant-design/ant-design#51980]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/biao-dan-fang-fa-diao-yong-antd-5-22-2-forked-yfl3g7?file=%2Fdemo.tsx%3A23%2C9-26%2C10)

### Steps to reproduce

1、Modal设置body样式，maxHeight: 400，overflowY: "auto"
2、Select设置属性getPopupContainer={(triggerNode) => triggerNode.parentElement || document.body}
3、点击Select组件，观察弹出面板

### What is expected?

面板样式无问题

### What is actually happening?

面板样式有问题

| Environment | Info |
| --- | --- |
| antd | 5.22.4 |
| React | 18.0.0 |
| System | mac |
| Browser | chrom |

**Comment by zombieJ** [comment]
`overflow: hidden` 的容器里，放里面的元素超出容器范围都会被截断掉，这是预期行为。
如果希望不要被截断，去掉 `overflow: hidden` 或者 不要设置`getPopupContainer` 到滚动容器里。
