### ISSUE TITLE
Modal可以增加最大化及最小化按钮吗？

### ISSUE THREAD

**Issue by encorehe** [ant-design/ant-design#5198]
#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.
希望Modal可以增加最大化或最小化按钮 放到关闭按钮旁边 或者像Footer一样可以自定义也行...

**Comment by afc163** [comment]
不支持，可以去掉 close 的 x 并自定义 title 。
