### ISSUE TITLE
Transfer改变dataSource后会冲掉已选择的内容

### ISSUE THREAD

**Issue by Elderkly** [ant-design/ant-design#51989]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-yong-fa-antd-5-21-6-forked-r8lqr3?workspaceId=ws_TiwWQFbvDSwXGnUe2b12f7)

### Steps to reproduce

1.将左侧列表选中元素后添加到后侧选中区域
2.点击顶部update type to key2

### What is expected?

选中的内容能够保存

### What is actually happening?

一开始选中的内容被冲掉

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | win10 |
| Browser | chrome131 |

**Comment by Elderkly** [comment]
或者有没有可能一开始待选列表我可以渲染所有的数据，但是这些item可以根据我目标的type来控制是否显示

**Comment by Elderkly** [comment]
#51974

**Comment by zombieJ** [comment]
`dataSource` 的变化是会影响列表渲染的，这个是预期行为。如果你要保留数据的话，新的 `dataSource` 要带上你之前勾选的 item 数据。如果你希望实现 hidden 的效果，那需要自行在外层做一份数据管理来记录隐藏的 item 列表。
