### ISSUE TITLE
Tree component to receive inside padding

### ISSUE THREAD

**Issue by Dorious** [ant-design/ant-design#51995]
### What problem does this feature solve?

I'm trying to add 8x padding inside the Tree component, but I can't because rc-virtual-list calculated item per some their calculation not the real size of the content (plus padding).

### What does the proposed API look like?

<Tree style={{padding: '8px'}} /> or any padding classNames will add nice padding and will be used for scroll height calculations. They are not.

**Comment by Dorious** [comment]
For everybody facing this. I've a work around that seems to work. rc-virtual-list actually looks for elements height so just add padding to the tree-node elements, some sass that fixed that for me:
```
&-list-holder-inner {
    .ant-tree-treenode {
      padding: 0 8px;
    }

    & > div:first-child {
      padding-top: 8px;
    }

    & > div:last-child {
      padding-bottom: 8px;
    }
  }
```

**Comment by pikpok** [comment]
@Dorious Thanks for posting this! I've tried your solution at first, but noticed that upgrading `rc-virtual-list` in package manager lockfile to the latest version (3.16.1 as of writing this) also resolves this issue. In my case (using yarn berry), running `yarn up rc-virtual-list -R` did the trick

**Comment by MadCcc** [comment]
Can you add padding outside tree component?
