### ISSUE TITLE
Remove @types/antd from DefinitelyTyped

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#5199]
See: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13364 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14419

**Comment by yesmeck** [comment]
Removed, npm will show warning when `npm install @types/antd`.

```
warning @types/antd@1.0.0: This is a stub types definition for antd (https://github.com/ant-design/ant-design). antd provides its own type definitions, so you don't need @types/antd installed!
```

**Comment by tianlizhao** [comment]
@yesmeck 现在定义要手动引入么？像这样`import {FormComponentProps} from "antd/lib/form/Form";`

**Comment by yesmeck** [comment]
是的

**Comment by tianlizhao** [comment]
好吧，谢谢你。再问一句，那有没有稍微自动些的办法？

**Comment by yesmeck** [comment]
没有。

**Comment by tianlizhao** [comment]
好的，再次感谢。。
