### ISSUE TITLE
ConfigProvider会导致样式出错

### ISSUE THREAD

**Issue by mqliutie** [ant-design/ant-design#51992]
### Reproduction link

[https://github.com/mqliutie/antd-themeprovider](https://github.com/mqliutie/antd-themeprovider)

### Steps to reproduce

1. clone 仓库
2. yarn install 
3. npm run start
4. 页面中先点击 Modal.info 关闭弹层， 再点击 hook 在关闭弹层， 再次点击 Modal.info， 样式乱了

### What is expected?

正常显示

### What is actually happening?

样式丢了

| Environment | Info |
| --- | --- |
| antd | 5.22.4 |
| React | 18.2.0 |
| System | windows11 |
| Browser | chrome 131.0.6778.109 |

**Comment by MadCcc** [comment]
createRoot 是为了实现什么？
另外代码中 Modal 处于 ConfigProvider 外层，这会导致问题，请保证使用 cssvar 模式的时候 ConfigProvider 作用全局

**Comment by mqliutie** [comment]
`Modal` 不处于 `ConfigProvider` 这个是正常的吧。默认 `Modal` 不是向 `body` 中插入吗？

`createRoot` 这个就是想自己封装的 `modal` 自己管理。 

目前现象是 `Modal` 的出错了。触发顺序是 `Modal -> createRoot Modal -> Modal`

如果顺序变成先触发 `createRoot Modal` 那么样式乱的现象将永远不会触发。

不理解。。。
