### ISSUE TITLE
Upload中的Dragger多选时，偶现上传失败

### ISSUE THREAD

**Issue by Summer-for-work** [ant-design/ant-design#51994]
### Reproduction link

[http://gmpsso-test01.dotfashion.cn/ccst/zh/font](http://gmpsso-test01.dotfashion.cn/ccst/zh/font)

### Steps to reproduce

使用Upload中的Dragger，maxCount={10}、multiple={true}，本地测试时（代理到测试环境），多选文件，上传速度快且文件状态都为done不报错；测试环境，上传速度非常慢，经常出现个别文件上传失败（status 为"error"）

### What is expected?

希望测试环境或线上，上传速度快且文件状态都为done不报错。

### What is actually happening?

本地测试时（代理到测试环境），多选文件，上传速度快且文件状态都为done不报错；测试环境，上传速度非常慢，经常出现个别文件上传失败（status 为"error"）

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | 18 |
| System | MacBook Pro 13.6.1 Apple M2 |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
Upload 内部用的是原生的 `input` 进行上传，如果你在不同环境表现不一样，应该看一下网络报错是什么。尤其是你提到 `测试环境，上传速度非常慢` 这显然不是组件库做的事情哈~
