### ISSUE TITLE
Modal中使用Form，给Modal增加了key，会导致数据丢失

### ISSUE THREAD

**Issue by L-x-C** [ant-design/ant-design#5200]
DEMO：http://codepen.io/superlxc/pen/peNzPj

![1](https://cloud.githubusercontent.com/assets/4329120/23651765/85d5968e-0361-11e7-83cf-c4c3771967fa.gif)

可以看到在这个demo中，每次Modal出来里面的数据会有时有有时没有....
如果把Modal的key去掉，那就不会有问题...
求解....

**Comment by afc163** [comment]
key 应该唯一且稳定，换了 key react 就会把这节点当成是新的并重新渲染。

这个和 antd 没啥关系。https://facebook.github.io/react/docs/lists-and-keys.html
