### ISSUE TITLE
use message.success('text') Api throw Error in react19,  Error info:  Uncaught TypeError: reactRender is not a function 

### ISSUE THREAD

**Issue by shunseven** [ant-design/ant-design#52025]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

use  message.success('text')

### What is expected?

alert  success message ‘text’

### What is actually happening?

throw Error, info:  Uncaught TypeError: reactRender is not a function

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 19.0.0 |
| System | Mac  |
| Browser | chrome 131.0.6778.108 |

**Comment by zombieJ** [comment]
v5 not support React 19. View more info with https://github.com/ant-design/ant-design/discussions/51919
