### ISSUE TITLE
onCancel not being called for modals

### ISSUE THREAD

**Issue by elios264** [ant-design/ant-design#5203]
#### Environment(required)

- antd version:  2.7.4
- OS and its version: Windows 10
- Browser and its version: chrome  56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

        Modal.confirm({
          title: 'Sample title',
          content: `Sample content`,
          onCancel: () => console.log('cancelling') });

#### What do you expected?

a console log when pressing ESC key

#### What happens?

The modal closes but the log is not printed

#### Re-producible online demo

http://codepen.io/elios264/pen/RpoVeE

**Comment by NE-SmallTown** [comment]
I think it's not a bug,maybe it's brower's behavior(i.e.,remove all nodes which are masks ),you can use `alert()` or `confirm()` on the browser and then press "Esc" key,you will see that they will disappear.

Maybe these help?

[Five unexpected uses for the Esc key](http://www.macworld.com/article/1143530/esckey.html)

[bootstrap modal handle esc](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js)

[bootstrap modal doc](https://getbootstrap.com/javascript/#js-programmatic-api)

[relevant issue1](https://github.com/twbs/bootstrap/issues/13929)

[relevant issue2](https://github.com/twbs/bootstrap/issues/13816)

**Comment by elios264** [comment]
Hi @NE-SmallTown, 

It is not browser behaviour, I checked the underline source code but I couldn't figure out because the library uses rc-dialog underneath, but the rc-dialog does calls onCancel when pressing ESC,

I read "cancel button and x button"  too,  I just think they missed that case.

**Comment by benjycui** [comment]
We need to trigger `props.onCancel` and pass event as argument [here](https://github.com/ant-design/ant-design/blob/6bca3ba87fcde17e845f4cf04f22c6006212fd20/components/modal/confirm.tsx#L33)

Could you try to PR to fix this? @elios264 @NE-SmallTown

**Comment by NE-SmallTown** [comment]
@elios264 Sorry for that I don't check [rc-dialog](https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L137),it does handle the "ESC" key.

```
 if (props.keyboard && e.keyCode === KeyCode.ESC) {
      this.close(e);
 }
```

It does is a bug like @benjycui says,when you press "ESC" key,the execute order is:

```
react-component-dialog: onKeyDown ->>  react-component-dialog: close ->> react-component-dialog.props.onClose(e) ->> ant-design-Modal: handleCancel ->> ant-design-Modal.props.onCancel(e) ->> ant-design-confirm: onCancel ->>  function close() {
    const unmountResult = ReactDOM.unmountComponentAtNode(div);
    if (unmountResult && div.parentNode) {
      div.parentNode.removeChild(div);
    }
  }
```

So,the final handle function is `close` function above,**but it doesn't call `props.onCancel(e)` which you define at your component** like @benjycui says.
