### ISSUE TITLE
Progress strokeLinecap="square" 圆环没有对齐

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#52031]
### Reproduction link

[https://ant.design/components/progress-cn](https://ant.design/components/progress-cn)

### Steps to reproduce

```
 <Progress type="circle" strokeLinecap="square" strokeWidth={20} strokeColor= "#ff0000" trailColor="#00ff00" percent={75} />
```

 strokeLinecap="square" 时候，进度环没有完整对齐

![image](https://github.com/user-attachments/assets/eb01f093-cf3b-4da0-b094-10e7a9d85448)

### What is expected?

希望能够对齐

### What is actually happening?

没有对齐

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 18 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
用 `strokeLinecap="butt"`。square 原始表现就是这样的，不要用：https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute/stroke-linecap
