### ISSUE TITLE
antd5 input,textarea 等组件在低版本 Safari 浏览器，输入时，每次输入一个字符，输入框就失去焦点

### ISSUE THREAD

**Issue by fengyangbj-kanyun** [ant-design/ant-design#52037]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

直接使用官方 demo， 升级到 Antd5之后，input 之类在低版本 Safari 浏览器上，每当输入一个字符，输入框就自动失去焦点，不知道 antd5相对 4 做了哪些变化？

### What is expected?

input之类组件在低版本浏览器正常

### What is actually happening?

输入时表现正常

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2 |
| System | mac os 10.15.2 |
| Browser | Safari  12.1 |

**Comment by afc163** [comment]
Duplicate of #issues
