### ISSUE TITLE
Windows 中的 char 无效

### ISSUE THREAD

**Issue by xiyouwei** [ant-design/ant-design#52043]
### Reproduction link

[https://github.com/react-component/resize-observer](https://github.com/react-component/resize-observer)

### Steps to reproduce

yarn add antd

➤ YN0001： │ Error: While persisting /C：/Users/---/---/---/---/.yarn/cache/rc-resize-observer-npm-1.4.1-95fdc1562f-259067f09d.zip/node_modules/rc-resize-observer/ -> /C：/Users/---/---/---/---/node_modules/rc-resize-observer ENOENT：no such file or directory，mkdir 'C：\Users------------\node_modules\rc-resize-observer\dist~demos：id'

### What is expected?

安装成功

### What is actually happening?

安装失败

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
参考 AI 的回复，这个是你的包管理工具问题。在 antd 以及底层依赖并没有写死过路径。yarn 如果不行也可以考虑换其他的包管理工具哈~

**Comment by lyt8384** [comment]
一样的问题，看了下应该是rc-resize-observer的问题。先降个antd版本了只能

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/resize-observer/pull/214 , please reinstall node_modules after remove all lock files.

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/41357#issuecomment-1476187323

**Comment by xiyouwei** [comment]
谢谢
