### ISSUE TITLE
unexpected scrolling on table, select

### ISSUE THREAD

**Issue by InSIkHwang** [ant-design/ant-design#52042]
### Reproduction link
https://ant.design/components/table#table-demo-virtual-list
https://ant.design/components/select#select-demo-multiple

### Steps to reproduce

https://ant.design/components/table#table-demo-virtual-list
https://ant.design/components/select#select-demo-multiple

### What is expected?

i don't want scroll

### What is actually happening?

I don't want it to scroll, but it automatically scrolls down when I click on it.

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 18.3.1 |
| System | window |
| Browser | chrome |

---
It cannot be reproduced in an online IDE such as CodeSandbox, but can be checked on the official page.

**Comment by zombieJ** [comment]
Reinstall `node_modules`. This has been fixed in `rc-virtual-list`
