### ISSUE TITLE
MicroApp微前端和antd适配性问题

### ISSUE THREAD

**Issue by lpw171758** [ant-design/ant-design#52040]
### Reproduction link

[https://github.com/react-component/util](https://github.com/react-component/util)

### Steps to reproduce

MicroApp微前端框架

### What is expected?

期望 select下拉框正常显示

### What is actually happening?

select下拉框、日期弹出框 都会在浏览器左上角显示

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18.2.0 |
| System | mac |
| Browser | 火狐任何版本 |

---
wechat: 15624992111 非常紧急，感谢各位大佬和路人~

**Comment by consistent-k** [comment]
子应用里所有的弹出层都要设置getPopupContainer 属性 让子应用的弹层弹在子应用内容就ok了。

原因是：弹出层默认是在body上创建节点  微前端做了样式隔离 所以加载不到子应用的样式

**Comment by lpw171758** [comment]
> 子应用里所有的弹出层都要设置getPopupContainer 属性 让子应用的弹层弹在子应用内容就ok了。
> 
> 原因是：弹出层默认是在body上创建节点 微前端做了样式隔离 所以加载不到子应用的样式

大佬设置过了，没用啊。

**Comment by lpw171758** [comment]
> 子应用里所有的弹出层都要设置getPopupContainer 属性 让子应用的弹层弹在子应用内容就ok了。
> 
> 原因是：弹出层默认是在body上创建节点 微前端做了样式隔离 所以加载不到子应用的样式

 getPopupContainer={triggerNode => triggerNode.parentElement}
 大佬设置过了，没用啊。可以留个联系方式吗？请教一下，困扰好几天了。

**Comment by sususu7** [comment]
对，我也遇到这个问题了，各种网上的办法都试过了改不好。就火狐浏览器不兼容，任何直接在主界面内使用涉及到悬浮弹窗显示的组件都会报错。主应用使用antd没问题，内嵌的子应用则会定位错乱并且报错。子应用我这边写的是嵌在主应用的一个菜单界面内，弹层定位方法报错。

**Comment by sususu7** [comment]
![5ba99195f03e4b822c9d78a195aba54](https://github.com/user-attachments/assets/21d7e487-71ea-4400-b51d-7b0c1a62fa53)
![01b89ad4d8c920677e95d686b91b67d](https://github.com/user-attachments/assets/c648e8cb-a353-48e2-92da-6bda07643b7e)

**Comment by lpw171758** [comment]
> ![5ba99195f03e4b822c9d78a195aba54](https://private-user-images.githubusercontent.com/58975297/397203563-21d7e487-71ea-4400-b51d-7b0c1a62fa53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NzkzNDgsIm5iZiI6MTczNDU3OTA0OCwicGF0aCI6Ii81ODk3NTI5Ny8zOTcyMDM1NjMtMjFkN2U0ODctNzFlYS00NDAwLWI1MWQtN2IwYzFhNjJmYTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAzMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODMzZTVmNDBhOWMxM2U2MThjNDE3ZGY1NDJjNDU3NGU5ZmM2NmQ3MmYxZDE2M2QxZjI1ZjJmYzU3ZTRlMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vGoCbrcxDS8ZkZnACnwYUSKNz7D_oJRqg8WR7Nd7ZWI) ![01b89ad4d8c920677e95d686b91b67d](https://private-user-images.githubusercontent.com/58975297/397203586-c648e8cb-a353-48e2-92da-6bda07643b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NzkzNDgsIm5iZiI6MTczNDU3OTA0OCwicGF0aCI6Ii81ODk3NTI5Ny8zOTcyMDM1ODYtYzY0OGU4Y2ItYTM1My00OGUyLTkyZGEtNmJkYTA3NjQzYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAzMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDBmNGY1MGIzZWRkZDJmMjliYzY2YzJhMDM3MDBiYmU1YzdkMTc3MDM4OTQ1ZTM1YzQ2YTY0OGQyOGM1NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jOLWl0dUExc0_xQFxmZLPPc63Y5I5jM_R_0Or6TJAHA)

竟然和我错误一模一样，最终是rc-until的findEventNode方法有问题吧？

**Comment by lpw171758** [comment]
![Uploading w9d8piz9.png…]()

**Comment by lpw171758** [comment]
![w9d8piz9](https://github.com/user-attachments/assets/51e9bf12-9bb8-4da4-971a-095c387db98f)

**Comment by lpw171758** [comment]
@afc163

**Comment by afc163** [comment]
@lpw171758 需要重现：https://github.com/ant-design/ant-design/issues/52040#issuecomment-2550248901

**Comment by lpw171758** [comment]
> @lpw171758 需要重现：[#52040 (comment)](https://github.com/ant-design/ant-design/issues/52040#issuecomment-2550248901)

项目是别人搭建的，我是菜鸟不会起项目，你们是阿里的大神。随便搭一个 MicroApp + antd 就复现了。

**Comment by lpw171758** [comment]
> @lpw171758 需要重现：[#52040 (comment)](https://github.com/ant-design/ant-design/issues/52040#issuecomment-2550248901)

项目是别人搭建的，我是菜鸟不会起项目，你们是阿里的大神。随便搭一个 MicroApp + antd 就复现了。

**Comment by lpw171758** [comment]
> @lpw171758 需要重现：[#52040 (comment)](https://github.com/ant-design/ant-design/issues/52040#issuecomment-2550248901)

项目是别人搭建的，我是菜鸟不会起项目，你们是阿里的大神。随便搭一个 MicroApp + antd 就复现了。@afc163
