### ISSUE TITLE
Cannot uncheck table row select rows programatically

### ISSUE THREAD

**Issue by kdipika** [ant-design/ant-design#5204]
Used rowSelect to add checkboxes to table. Everything works fine if selecting and un selecting the checkboxes manually. But I don't see an l option to un select the checkboxes programatically through the code.I have to clear the selections on some other action.

Can some one please help how to achieve this?

![screen shot 2017-03-07 at 11 17 51 am](https://cloud.githubusercontent.com/assets/26258993/23673646/def004e6-0327-11e7-8359-b6b31a1ba629.png)

#### Environment(required)

- antd version:
- OS and its version:
- Browser and its version:

#### What did you do? Please provide steps to re-produce your problem.

I tried unckecing the checkboxes using jquery but that did not really clear the rows and selected row data

#### What do you expected?
I expect to have an option to un select the selected rows

**Comment by ddcat1115** [comment]
You can achieve this by setting `selectedRowKeys ` of `rowSelection`, refer to https://ant.design/components/table/#components-table-demo-row-selection-and-operation

**Comment by afc163** [comment]
You should not use jquery to operate React component, use React's way.
