### ISSUE TITLE
Can `InputNumber` component use different props for precision and step?

### ISSUE THREAD

**Issue by jungor** [ant-design/ant-design#5205]
#### Environment(required)

- antd version: 1.11.6
- OS and its version: win10
- Browser and its version: chrome 56.0.2924.87 (64-bit)

#### Feature request
Can `InputNumber` component use different props for precision and step? It seems that it now use `step` prop for both purposes. There are case where I want the step (when i click the up or down button),  is different from the precision. For example I want the input number to be a real number but step is 1.

**Comment by afc163** [comment]
Try `antd@2.8.0`
