### ISSUE TITLE
表格拖拽会影响从每行打开的Modal使用

### ISSUE THREAD

**Issue by wencai123** [ant-design/ant-design#52052]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/table-4s4xj2?file=%2Fsrc%2FApp.tsx%3A36%2C5)

### Steps to reproduce

1.表格展示后，点击编辑
2.modal显示后，点击select，鼠标按住不松开移动，样式异常，且可以影响外层排序
3.modal空白处，鼠标按住不松开移动，也会样式异常，且可以影响外层排序

### What is expected?

期望样式不受影响，不影响外层排序

### What is actually happening?

样式异常，且影响外层排序

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 18.xx和19.xx |
| System | mac os 12.2.1 |
| Browser | 131.0.6778.140 |

**Comment by zombieJ** [comment]
React Virtual DOM Tree 月经问题，在 Modal 外加一个 div 然后 stopPop 让事件不要冒泡出去。

**Comment by wencai123** [comment]
> React Virtual DOM Tree遍历问题，在Modal外面加一个div然后stopPop让事件不要冒泡出去。

感谢回复！好像不太行，我是这样写的，执行后还是会复现这个问题
![image](https://github.com/user-attachments/assets/8c405b07-ffe8-4d62-abdf-caae55aa53c4)

![image](https://github.com/user-attachments/assets/418df2b4-8fb4-4058-8806-e23f7324e67d)
