### ISSUE TITLE
DatePicker组件在4.1版本后新增的picker=quarter在使用中format="YYYY-[Q]Q"无法格式化，导致出现全部是2024-QQ的选项

### ISSUE THREAD

**Issue by Zhaohanqi12** [ant-design/ant-design#52058]
### What problem does this feature solve?

现状展示为2024-QQ,选项 全是 QQ？
![image](https://github.com/user-attachments/assets/c2dc8ab2-b98a-420c-a714-085e5619f858)
### What does the proposed API look like?

期望值默认值2024-Q1,选项为Q1,Q2,Q3,Q4

**Comment by zombieJ** [comment]
v4 已经过了维护，不再会处理相关 issue 了哈。如果你在 v5 遇到了相同的问题，请使用问题模版，feature request 模版提 issue 会被直接关闭哈~

**Comment by LingYe-007** [comment]
v5.2也有这个问题
