### ISSUE TITLE
希望可以给Form.Item配置一个全局生效的rule

### ISSUE THREAD

**Issue by lemonied** [ant-design/ant-design#52067]
#### 背景
在我的业务中，有大量表单场景，用户在填写表单时，数据来源可能会从某些文档中复制（Word，PDF等），而复制的内容中经常会带有零宽字符：
- 零宽空格 (U 200B)：用于在不添加空格的情况下分隔单词或字符。
- 零宽非连接符 (U 200C)：用于阻止字符之间的连接行为，常用于阿拉伯语或波斯语等需要字符连接的语言。
- 零宽连接符 (U 200D)：用于强制字符之间的连接行为，常用于需要连字的语言。
- 零宽不换行空格 (U FEFF)：用于指示文本的字节顺序（字节顺序标记，BOM），但也可以作为零宽字符使用。

例如这个字符：`H​e​l​l​o`，看不出任何问题吧，如果复制到控制台可以发现`'H​e​l​l​o'.length`长度为9，其中包含了4个`\u200B`，这种字符用户不可能主动输入，都是复制粘贴时不小心贴进去的，视觉上不可见导致数据提交人和审核人都无法发现，从而引发线上故障。

### What does the proposed API look like?

现在我的解决办法只能是给所有的`Form.Item`加上`rules`，希望antd可以提供一个全局配置的功能来校验这种错误，例如：
```tsx
<ConfigProvider
  form={{
    ItemRules: [
      {
        validator(rule, value) {
          if (typeof value === 'string' && /[\u200B-\u200D\uFEFF]/.test(value)) {
            const charCodes = value.split('').filter(v => /[\u200B-\u200D\uFEFF]/.test(v)).map(v => `\\u${v.charCodeAt(0).toString(16)}`);
            return Promise.reject(
              new Error(`存在非法字符：${Array.from(new Set(charCodes))}，请检查！`),
            );
          }
          return Promise.resolve();
        },
      },
    ],
  }}
>{children}</ConfigProvider>
```

**Comment by crazyair** [comment]
可以自己 HOC 实现

**Comment by lemonied** [comment]
> 可以自己 HOC 实现

HOC的话，`pro-components`里的组件又覆盖不到了

**Comment by crazyair** [comment]
那建议在 pro 加功能，可以在那提 pr
