### ISSUE TITLE
How can I prevent the default hover event in the Select component of Ant Design v4.20?

### ISSUE THREAD

**Issue by khangviet1996** [ant-design/ant-design#52061]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/yp232r)

### Steps to reproduce

this is a default example in the doc

### What is expected?

Hovering should not trigger a re-render of all items.

### What is actually happening?

Hovering triggers a re-render of all items

| Environment | Info |
| --- | --- |
| antd | 4.24.11 |
| React | 16.13.1 |
| System | Intel Core i7 - 10700 CPU 2.9GHZ, window 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
You are asking a X-Y question. Select using virtual list which meaning re-render is not perf heavy. Since v4 is not in maintain anymore. I will close this issue.

If you have same question on v5. Please create a new issue and provide more detail about why do not need re-render for visible items : )
