### ISSUE TITLE
使用RangePicker时，用户进行了点击打开操作，怎么可以点击结束时间时自动跳转到开始时间？

### ISSUE THREAD

**Issue by itsatan** [ant-design/ant-design#52062]
### What problem does this feature solve?

有什么办法可以控制吗，我看到了onFocus方法可以获取range，可是我怎么设置新的range并让组件切换过去呢？

### What does the proposed API look like?

可能会是activePanel

**Comment by zombieJ** [comment]
可以 css 写个伪类，盖住输入框范围。DatePicker 有个特点，点击如果不是在 Input 上就会默认打开第一个：

https://stackblitz.com/edit/react-peszvuwn?file=package.json,demo.tsx,index.css

简单写写，真实使用时可能还要自己调整一下
