### ISSUE TITLE
Ant Design causing error : reactRender is not a Function

### ISSUE THREAD

**Issue by daffafikri19** [ant-design/ant-design#52079]
When I use the button from antd (So far I only use the button), when I click on it, the TypeError error occurs: reactRender is not a function.

I've checked it works regardless of whether you use the client or the server. I am using extjs 15 and the latest version of antd. I also tried to create a new clean next project and try it there, but the error is the same.

![image](https://github.com/user-attachments/assets/5b541f64-9491-4fe9-bdcf-1957f8dcd5cb)

**Comment by afc163** [comment]
Duplicate of #52080
