### ISSUE TITLE
【bug】【docs】文档中代码样例使用 stackblitz 打开报错

### ISSUE THREAD

**Issue by baiwusanyu-c** [ant-design/ant-design#52098]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/run?file=package.json)

### Steps to reproduce

打开链接，页面无法渲染报错

### What is expected?

样例页面正常渲染

### What is actually happening?

页面报错
![image](https://github.com/user-attachments/assets/08a43200-680e-42d0-aea5-3aeb36f6d1d4)

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 18.3.1 |
| System | win10 |
| Browser | Chrome 126.0.6452.3 |

**Comment by afc163** [comment]
StackBlitz 的问题，貌似 antd 做不了啥。
