### ISSUE TITLE
Datepicker  点击确定以后如何获取值

### ISSUE THREAD

**Issue by F2EVarMan** [ant-design/ant-design#521]
onSelect 是点一个日期就获得一次, onChange 无效果
![image](https://cloud.githubusercontent.com/assets/10355060/11136723/14952de4-89ec-11e5-89c0-7dfe95189e1c.png)
![image](https://cloud.githubusercontent.com/assets/10355060/11136731/1ca86dac-89ec-11e5-828a-8ebfbed1e9d1.png)

**Comment by afc163** [comment]
可以 onSelect 的时候保存日期，确定时拿到这个保存的日期。

**Comment by likezero** [comment]
确定时。。。你确定 那个确定button有事件回调么。。。

**Comment by afc163** [comment]
onOk

**Comment by afc163** [comment]
http://ant.design/components/datepicker/#demo-time

**Comment by afc163** [comment]
如果不是 showTime 的情况，直接用 onChange 。
