### ISSUE TITLE
官方示例中的confirm with promise 示例不work

### ISSUE THREAD

**Issue by glin7976** [ant-design/ant-design#52106]
### Reproduction link

[https://ant.design/components/modal-cn#modal-demo-confirm](https://ant.design/components/modal-cn#modal-demo-confirm)

### Steps to reproduce

点击“with promise” 按钮后，点击“确定”按钮

### What is expected?

点击“with promise” 按钮后，点击“确定”按钮，弹窗关闭

### What is actually happening?

点击“with promise” 按钮后，点击“确定”按钮，弹窗未关闭

| Environment | Info |
| --- | --- |
| antd | 5.22.6 |
| React | 18 |
| System | macOs 14.5 |
| Browser | Chrome Version 131.0.6778.205 |

**Comment by zombieJ** [comment]
试了一下 `5.22.5` 还是好的，的确有问题。

**Comment by zombieJ** [comment]
找到原因，官网的 `unstableSetRender` 注册逻辑有点问题导致重复渲染无法关闭。不影响 antd 包，只影响官网。
