### ISSUE TITLE
Replace @ctrl/tinycolor to @ant-design/fast-color

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#52107]
https://github.com/search?q=repo%3Aant-design%2Fant-design%20%40ctrl%2Ftinycolor&type=code

- [x] `@ant-design/colors` https://github.com/ant-design/ant-design-colors/pull/94
- [ ] `dumi-plugin-color-chunk` ???
- [x] `antd` https://github.com/ant-design/ant-design/pull/52157

**Comment by aojunhao123** [comment]
1

**Comment by aojunhao123** [comment]
@Wxh16144 @afc163  大佬们，dumi-plugin-color-chunk这个包要做替换吗

**Comment by afc163** [comment]
可以换。

**Comment by afc163** [comment]
这个不影响 antd 包体积，只影响官网打包，可以另开 PR 跟进。

**Comment by aojunhao123** [comment]
ok

**Comment by Wxh16144** [comment]
> [@Wxh16144](https://github.com/Wxh16144) [@afc163](https://github.com/afc163) 大佬们，dumi-plugin-color-chunk这个包要做替换吗

https://github.com/Wxh16144/dumi-plugin-color-chunk/pull/7 故意这样弄的，不过我倒是想不锁 `@rc-component/color-picker` 重新 CV 出来用..
