### ISSUE TITLE
inline表单去掉了marginBottom， 导致在inline表单项有校验的时候，会出现撑开form-item的情况，出现样式问题

### ISSUE THREAD

**Issue by waveheart** [ant-design/ant-design#52100]
### Reproduction link

[https://ant-design.antgroup.com/components/form-cn#form-demo-layout](https://ant-design.antgroup.com/components/form-cn#form-demo-layout)

### Steps to reproduce

1. 创建一个inline 表单， 下方随意放任意组件
2. 表单项第一个改为必填
3. 直接提交表单，必填项检验出错
4. 表单高度被撑开，样式错乱

### What is expected?

当表单项有必填校验时，表单项的marginBottom: 24 应该保留

### What is actually happening?

当表单项有必填校验时，inline 表单项的marginBottom: 24 被强行删除， 校验出错时， 样式错乱

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | >18 |
| System | Mac OS |
| Browser | chrome 最新 |

**Comment by waveheart** [comment]
![image](https://github.com/user-attachments/assets/2a85f40c-d55f-41b5-8524-d47d126e813a)

**Comment by zombieJ** [comment]
`inline` 设计就是做轻量级内联，对于错误会垂直方向顶开是预期设计：

<img width="487" alt="截屏2024-12-23 16 48 06" src="https://github.com/user-attachments/assets/c58738da-d9a9-4fda-82b7-2b1b4c6918d3" />

<img width="497" alt="截屏2024-12-23 16 48 10" src="https://github.com/user-attachments/assets/e607acc1-7770-4d20-b674-27ee121ef263" />

如果你需要固定 margin，直接 `style` 加上即可。
