### ISSUE TITLE
issue in datepicker

### ISSUE THREAD

**Issue by malekhmaissy** [ant-design/ant-design#52114]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-dxnrzm?workspaceId=ws_K7mzYm5mcQ28vwxHZ3HagB)

### Steps to reproduce

issue in datepicker when it has a value fetched it gives all dates picked and whenever i move the cursor the date keeps increasing until years later

### What is expected?

when i fetch data in datepciker i don't want datepicker to have issue with cursor

### What is actually happening?

when i fetch data in datepicker the datepicker doesn't work correctly anymore unless i click on x button or today button otherwise whenever i move the cursor the date increases by many years

| Environment | Info |
| --- | --- |
| antd | 5.20.6 |
| React | react 18 |
| System | windows 11 |
| Browser | chrome |

**Comment by zombieJ** [comment]
Your reproduce is not public:

<img width="579" alt="截屏2024-12-24 19 21 16" src="https://github.com/user-attachments/assets/be3855a7-b560-44d6-879b-66c123f452ed" />
