### ISSUE TITLE
表单控件的onChange可以安排在onFieldsChange之后吗

### ISSUE THREAD

**Issue by yangbin1994** [ant-design/ant-design#5212]
前提：根据官方提供的api实现了表单的双向绑定
问题：控件change之后，希望发起一些异步操作，在onFieldsChange里面做了分支判断，但是发现onFieldsChange会触发2次，因为数据是异步获得的，2次请求的中间如果拉取的数据发生变化，最终得到的结果并不是我想要的
解决：使用空间自己的onChange，但是发现它的调用在onFieldsChange之后，如果我是通过参数传值的方式，感觉我实现双向表单绑定的意义就没有了
希望：可以帮忙解决2次触发的问题，或者标题所述

**Comment by afc163** [comment]
onFieldsChange => onValuesChange

**Comment by afc163** [comment]
Missing in changelog of 2.7.0
