### ISSUE TITLE
从antd4 升级到 antd5之后 Select和dropdown 下拉菜单打开动画卡顿

### ISSUE THREAD

**Issue by pandaxue** [ant-design/ant-design#52139]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/hkmmq9?file=%2Fdemo.tsx)

### Steps to reproduce

就是升级到antd5.x最新版本Select下拉菜单展示变卡顿了，隐藏下拉列表不卡顿

### What is expected?

动画不卡顿

### What is actually happening?

打卡下拉列表卡顿

| Environment | Info |
| --- | --- |
| antd | 5.22.6 |
| React | 17.0.1 |
| System | win11 |
| Browser | chrome |

**Comment by pandaxue** [comment]
> 您提到在将 Ant Design 从版本 4 升级到版本 5 后，Select 和 Dropdown 的下拉菜单动画出现卡顿的问题。为了帮助您解决这个问题，我建议您尝试以下步骤：
> 
> 1. **检查样式和动画配置**：确保在升级过程中没有遗漏或错误地配置样式和动画相关的设置。Ant Design 5 可能对动画和样式有一些更新，确保您的项目中使用的是最新的配置。
> 2. **性能优化**：检查是否有不必要的重渲染或复杂的计算影响了性能。可以使用 React 的性能分析工具来查看是否有性能瓶颈。
> 3. **更新依赖**：确保所有相关的依赖项（如 React 和其他库）都是最新版本，以便与 Ant Design 5 兼容。
> 4. **测试不同的浏览器和设备**：有时问题可能与特定的浏览器或设备相关，尝试在不同的环境中测试以确认问题的范围。
> 
> 如果这些步骤没有解决问题，您可以查看 Ant Design 的 GitHub 仓库中的相关问题，看看是否有其他用户报告了类似的问题，或者是否有相关的修复或建议。
> 
> 如果您需要进一步的帮助，请随时告诉我！
> 
> 🪧 Tips

怎么看已经使用了 antd5 最新的样式

**Comment by zombieJ** [comment]
我这边感觉不到卡顿，你能录个屏看看不？看看是不是 MAC 和 Windows 会不一样

**Comment by pandaxue** [comment]
> 我这边感觉不到卡顿，你能录个屏看看不？看看是不是 MAC 和 Windows 会不一样

http://xhslink.com/a/g1Sz6nRKwmp2，视频链接，视频大传不上来

**Comment by pandaxue** [comment]
> 我这边感觉不到卡顿，你能录个屏看看不？看看是不是 MAC 和 Windows 会不一样


https://github.com/user-attachments/assets/a5d2d56f-efd3-4b74-b8a8-48107f8266e5

**Comment by afc163** [comment]
感觉是起始动画丢了，不是卡顿。

**Comment by afc163** [comment]
@pandaxue 官网和 codesandbox 你会感觉到一样的卡顿么？也能录个屏看看么？

**Comment by pandaxue** [comment]
> @pandaxue 官网和 codesandbox 你会感觉到一样的卡顿么？也能录个屏看看么？

官网看着很丝滑，我用 antd4 的时候也是正常，就刚升级的 antd5 运行自己的项目就有这个问题

**Comment by afc163** [comment]
如果 5.x 官网和 Codesandbox 没问题的话，应该是你自己的项目里有其他样式污染了 antd Select 的进场动画样式。

**Comment by pandaxue** [comment]
> 如果 5.x 官网和 Codesandbox 没问题的话，应该是你自己的项目里有其他样式污染了 antd Select 的进场动画样式。

这种该怎么排查，我看 dropdown 也是这样没有进场动画，主要排查 transition 属性吗

**Comment by pandaxue** [comment]
> 如果 5.x 官网和 Codesandbox 没问题的话，应该是你自己的项目里有其他样式污染了 antd Select 的进场动画样式。

我把所有的全局样式都注释了还是一样，会不会有可能 antd5 的样式没有导入

**Comment by afc163** [comment]
@pandaxue 给出重现才能帮忙排查，我也猜不出来。
