### ISSUE TITLE
表格的tr的border问题

### ISSUE THREAD

**Issue by 957236298** [ant-design/ant-design#5213]
最开始是给table的tr设置hover事件，给当前tr加border，发现加不了。然后直接给表格的tr设置border也是不行，我给table标签设置了border-collapse:collapse，但是会出现很奇怪的现象，tr的底部会多出一条黑线。这是为什么啊

**Comment by afc163** [comment]
Try report as issue template.

**Comment by 957236298** [comment]
@afc163 我需要把它当成一个bug完整的整理好提出来?
