### ISSUE TITLE
vue table组件中复选框rowSelection 设置自定义选择框标题columnTitle后，选择框自动消失，标题和选择框无法同时存在。希望可以增加设置，支持渲染单个或者同时渲染

### ISSUE THREAD

**Issue by jane0412** [ant-design/ant-design#52147]
### What problem does this feature solve?

表格中选择框列，有时需要在选择框旁边加入文字描述，目前API不支持，无法同时显示选择框和文字描述

### What does the proposed API look like?

columnTitle：string|VNode   // 选择框自定义标题
hideSelectAll: boolean  // 隐藏全选勾选框与自定义选择项
上述为table rowSelection中现有API参数，目前columnTitle设置后，hideSelectAll设置失效，希望两者可以单独设置，互不影响

**Comment by afc163** [comment]
这里是 React 官方仓库，不负责 Vue 的相关问题。
