### ISSUE TITLE
Table的tr设置border时border-bottom会多一条黑色

### ISSUE THREAD

**Issue by 957236298** [ant-design/ant-design#5214]
#### Environment(required)

- antd version: 2.7.4
- OS and its version: win 10
- Browser and its version: Google Chrome,54.0.2840.87 m

想给表格的tr hover，让他的border变化。

最开始是给table的tr设置hover事件，给当前tr加border，发现加不了。然后直接给表格的tr设置border也是不行，我给table标签设置了border-collapse:collapse，但是会出现很奇怪的现象，tr的底部会多出一条黑线。这是为什么啊

![image](https://cloud.githubusercontent.com/assets/23330717/23699426/0d74b2be-042a-11e7-931c-da5eece9a0e2.png)

![image](https://cloud.githubusercontent.com/assets/23330717/23699495/4455b0b2-042a-11e7-8ee9-fe1d5a207ee1.png)

**Comment by yesmeck** [comment]
请提供可重现的在线演示 http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by 957236298** [comment]
@yesmeck   http://codepen.io/anon/pen/xqgLmG?editors=0110

**Comment by 957236298** [comment]
@benjycui ok,thank you~
