### ISSUE TITLE
Replace icons with external library?

### ISSUE THREAD

**Issue by thj-dk** [ant-design/ant-design#5216]
Is it possible to replace the built in icons with icons from an external library, such as Font Awesome?

**Comment by afc163** [comment]
You can use https://github.com/andreypopp/react-fa directly

**Comment by thj-dk** [comment]
Yes - thanks. But can I replace the calendar icon of the DatePicker with one from react-fa?

**Comment by afc163** [comment]
You have to override css style by your own.
