### ISSUE TITLE
定制menu的时候，选择子菜单时，父级会itemSelectedColor显示字体颜色，但是背景颜色没有根据itemSelectedBg显示

### ISSUE THREAD

**Issue by linyana** [ant-design/ant-design#52166]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-729rk5?file=%2Findex.tsx%3A22%2C35)

### Steps to reproduce

选中task，然后选择settings/account，对比两次选择时settings的颜色和背景颜色

### What is expected?

父元素的color和bcColor同子元素一起被全局token控制，或者单独增加父元素的控制项

### What is actually happening?

父元素的color同子元素一起被全局token控制，但是bcColor没有，导致深浅色不一致

| Environment | Info |
| --- | --- |
| antd | 5.22.7 |
| React | 19 |
| System | windows |
| Browser | chrome |

**Comment by linyana** [comment]
![image](https://github.com/user-attachments/assets/18ba7c3b-cc84-48ef-ac3c-48af75c71e5f)
![image](https://github.com/user-attachments/assets/3a3d7e2b-0797-4d08-b50c-a1c3d25a16ac)

**Comment by linyana** [comment]
理想结果：
![image](https://github.com/user-attachments/assets/3adbec03-b013-4e9d-9be5-6b579ac7d81f)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/52182

**Comment by linyana** [comment]
> Fixed in #52182

Thx
