### ISSUE TITLE
Can Select suppport a truncate selected options feature when the number of selections becomes very large ？

### ISSUE THREAD

**Issue by codTango** [ant-design/ant-design#5217]
#### Environment(required)

- antd version: 2.5.3
- OS and its version: Mac OS
- Browser and its version: FireFox & Chrome (latest)

#### What did you do? Please provide steps to re-produce your problem.
1. populate Select with 1000+ options
2. select all items
3. see the select explodes as below
![screen shot 2017-03-08 at 10 03 18 am](https://cloud.githubusercontent.com/assets/5359697/23709397/47deba50-03e7-11e7-9de8-3283c45e6586.png)

#### What do you expected?
I'd like to see select has a truncate feature that could be turned on/off; When turning on, it should truncate the selected options and display "... N more" in the input area if the number of selections exceed a certain number. For example, if it has more than 3 selections, it will behave as below:
![screen shot 2017-03-08 at 10 10 01 am](https://cloud.githubusercontent.com/assets/5359697/23709557/dcd2cbc4-03e7-11e7-8338-4128b07a4613.png)

I have tried to create an option called "... N more", and pass it along with other selected options as `value` prop, but the problem is it only works if the dropdown menu is close, however, it will display the rest of selected options as unselected in the dropdown menu if the dropdown menu is open.

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment. See: #4897

**Comment by benjycui** [comment]
Actually, I think [Transfer](https://ant.design/components/transfer/) is better in your use case.

**Comment by codTango** [comment]
@benjycui Thanks for pointing it out, it's probably easier for me to write it up in English, I tried hard to put that together in Chinese to describe my scenario. 

I don't think the Transfer is good in my case, as I have no space for two selection area; if I do so, my pm would kill me as well. >_< I think this feature is common enough  for a select component, hope you guys or someone can support that. Meanwhile, I have been looking at the source code and trying to do a MR myself, but the old react standard/pattern really slows me down.

**Comment by codTango** [comment]
@benjycui @yiminghe Is it acceptable if I make a PR to add this feature for Select?

**Comment by benjycui** [comment]
May be you can try to use customized children? cc @RaoHai

**Comment by benjycui** [comment]
It's really an edge case..

**Comment by codTango** [comment]
@benjycui I'm not sure I'm following, if you can explain more or give me an example on customized children? Yea, that large amount of options might be an edge case, but even with a normal number of options, it's still kind an issue. For example, 40 or 50 items. If I select half of that, the input area will still expand, which might not be a friendly UI at some place with limited space place.

If I'm not wrong, the dropdown menu and the input area are all populated by the `value` prop I passed in, now I just have an idea - if I can make an extra prop (maybe call it `truncatedValue`), and inside Select, we can check if this prop presents, if so, input area can use this extra prop and the dropdown menu will be populated by the `value` prop. Then the issue would be solved by this way, and it's an opt-in feature.

**Comment by afc163** [comment]
I suggestion to wrap a HOC for your case, that is a special usage and we don't have enough time to implement it now. 😅
