### ISSUE TITLE
Problem using this with megaboilerplate

### ISSUE THREAD

**Issue by eldyvoon** [ant-design/ant-design#5218]
I use https://github.com/sahat/megaboilerplate and installed antd. I wish to use it without manually import the css/less so I also installed this plugin https://github.com/ant-design/babel-plugin-import

when I trying to start my server I can't resolve .less files. I even tried to use the css option, I got error too. I've installed css-loader, less-loader but still doesn't work. My webpack file look like this

http://pastebin.com/kn08JFsg

**Comment by danielbiloglav** [comment]
You are defining the import plugin with "style": "css", which will load css files. You should change the import plugin to the following to use less:
["import", { "libraryName": "antd", "style": true }]

**Comment by eldyvoon** [comment]
able to use the component but didn't see the style, so I guess babel-plugin-import is working now. But do I need to include anything in my index.html for styles? I see Button without any style applied.

**Comment by benjycui** [comment]
A re-producible repo is better.

**Comment by afc163** [comment]
Sorry, you have to try it by yourself and let me know if you make it work. 😅

**Comment by eldyvoon** [comment]
@benjycui https://github.com/eldyvoon/ant-temp what's wrong with my usage? I created a Button component in app/components/Home.js

**Comment by benjycui** [comment]
@eldyvoon you had better to make you repo simpler., it even need a MongoDB right now. It too big for just a demo repo.

**Comment by eldyvoon** [comment]
@benjycui just git clone and run it, the mongodb credential I don't mind make it public, as this is just a temporary demo.

**Comment by benjycui** [comment]
The problem is that I cannot connect to your database.

> make you repo simpler
