### ISSUE TITLE
Tooltip组件使用:global覆盖内部宽度时，贴边偏移有问题

### ISSUE THREAD

**Issue by ZhaoXR429** [ant-design/ant-design#52189]
### Reproduction link

[https://codepen.io/ZhaoXR429/pen/zxOEEWx](https://codepen.io/ZhaoXR429/pen/zxOEEWx)

### Steps to reproduce

在css文件中设置:global覆盖.ant-tooltip-inner类的默认宽度或者在Tooltip组件的overlayInnerStyle中设置宽度时，贴边偏移会有问题。
如下图，使用官方示例设置overlayInnerStyle={{ width: '500px' }}时，向右滚动时，贴边异常。
![PixPin_2024-12-31_17-51-10.gif](https://s2.loli.net/2024/12/31/ELYJyjsUaxM9pZ2.gif)

### What is expected?

设置Tooltip内部的宽度时，贴边不失效。

### What is actually happening?

设置Tooltip内部的宽度时，贴边异常。

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | Windows |
| Browser | Chrome 版本 131.0.6778.205（正式版本） （64 位） |

**Comment by afc163** [comment]
默认样式中 overlay 上有个 `max-width: 250px` 影响了这个表现，需要一起重置掉：https://codepen.io/afc163-1472555193/pen/YPKrrjQ?editors=1010
