### ISSUE TITLE
Cannot find module "rc-upload"

### ISSUE THREAD

**Issue by F2EVarMan** [ant-design/ant-design#522]
![image](https://cloud.githubusercontent.com/assets/10355060/11136837/37573876-89ed-11e5-8f2b-54d1e256f532.png)

**Comment by afc163** [comment]
请给出重现步骤。

**Comment by afc163** [comment]
参照 https://github.com/ant-design/ant-design/issues/new?title=%E8%AF%B7%E5%A1%AB%E5%86%99%E7%AE%80%E6%B4%81%E6%9C%89%E6%95%88%E7%9A%84%E6%A0%87%E9%A2%98&body=**%E9%97%AE%E9%A2%98%E6%8F%8F%E8%BF%B0**%0A%0A%EF%BC%88%E6%8F%8F%E8%BF%B0%E4%B8%80%E4%B8%8B%E9%97%AE%E9%A2%98%EF%BC%89%0A%0A**%E5%8F%91%E7%94%9F%E7%8E%AF%E5%A2%83**%0A%0A-%20antd%20%E7%89%88%E6%9C%AC%EF%BC%9A%0A-%20%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E5%8F%8A%E7%89%88%E6%9C%AC%EF%BC%9A%0A-%20%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8F%8A%E7%89%88%E6%9C%AC%EF%BC%9A%0A-%20%E5%9C%A8%E7%BA%BF%E6%BC%94%E7%A4%BA%E5%9C%B0%E5%9D%80%EF%BC%9A%0A%0A**%E9%87%8D%E7%8E%B0%E6%AD%A5%E9%AA%A4**%0A%0A1.%20...%0A2.%20...%0A

**Comment by bang88** [comment]
@F2EVarMan rc-upload 依赖的版本问题,使用1.7.0即可
1.6.4 好像 npm 安装的时候下载下来的文件少了 lib 目录.

**Comment by afc163** [comment]
try `0.10.0-beta24`
