### ISSUE TITLE
Issue with implicit 'any' type when using typescript

### ISSUE THREAD

**Issue by danielbiloglav** [ant-design/ant-design#5221]
#### Environment(required)

- antd version: 2.8.0
- OS and its version: macOS Sierra 10.12.3
- Browser and its version: Chrome 56.0.2924.87 (64-bit)
- Webpack version: 2.2.1
- Typescript version: 2.2.1

#### What did you do? Please provide steps to re-produce your problem.

1. Imported antd with babel-import-loader
babelrc: ["import", { "libraryName": "antd" }]

2. Specified "noImplicitAny": true in tsconfig

3. Used the following loaders in webpack
{
   test: /\.tsx?$/,
   use: ["babel-loader", "awesome-typescript-loader"],
   exclude: /node_modules/
},
{
   test: /\.less$/,
   use: ExtractTextPlugin.extract(["css-loader", "less-loader", "postcss-loader"]),
},
{
   test: /.(png|jpg|jpeg|gif|svg|woff|woff2|eot|ttf)(\?v=\d+\.\d+\.\d+)?$/,
   loader: 'url-loader'
}

#### What do you expected?

No errors when compiling with webpack

#### What happen?

Received the following error:
ERROR in [at-loader] ./node_modules/antd/lib/table/SelectionCheckboxAll.d.ts:13:30
TS7006: Parameter 'item' implicitly has an 'any' type.

**Comment by benjycui** [comment]
It should be fixed in https://github.com/ant-design/ant-design/pull/5207

**Comment by benjycui** [comment]
You should read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before ask a question, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by danielbiloglav** [comment]
Ok, I see that the fix was merged to master a couple of hours before I posted the issue.

Sorry for that.
